LLDB: ABIAArch64.cpp File Reference
ABIAArch64.cpp File Reference
#include "lldb/lldb-types.h"
#include "ABIAArch64.h"
#include "ABIMacOSX_arm64.h"
#include "ABISysV_arm64.h"
#include "Utility/ARM64_DWARF_Registers.h"
#include "Utility/ARM64_ehframe_Registers.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Target/Process.h"
#include <bitset>
#include <optional>
Functions
static void addPartialRegisters (std::vector< lldb_private::DynamicRegisterInfo::Register > &regs, llvm::ArrayRef< std::optional< uint32_t > > full_reg_indices, uint32_t full_reg_size, const char *partial_reg_format, uint32_t partial_reg_size, lldb::Encoding encoding, lldb::Format format)
Function Documentation
addPartialRegisters()
void addPartialRegisters (std::vector< lldb_private::DynamicRegisterInfo::Register > & regs, llvm::ArrayRef< std::optional< uint32_t > > full_reg_indices, uint32_t full_reg_size, const char * partial_reg_format, uint32_t partial_reg_size, lldb::Encoding encoding, lldb::Format format) static
Definition at line 104 of file ABIAArch64.cpp.
References lldb_private::addSupplementaryRegister(), LLDB_INVALID_INDEX32, and LLDB_INVALID_REGNUM.
Referenced by ABIAArch64::AugmentRegisterInfo(), and ABIX86::AugmentRegisterInfo().