LLDB: ABIMacOSX_arm.cpp File Reference
ABIMacOSX_arm.cpp File Reference
#include "ABIMacOSX_arm.h"
#include <optional>
#include <vector>
#include "llvm/ADT/STLExtras.h"
#include "llvm/TargetParser/Triple.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Value.h"
#include "lldb/Symbol/UnwindPlan.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/RegisterValue.h"
#include "lldb/Utility/Scalar.h"
#include "lldb/Utility/Status.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
#include "Plugins/Process/Utility/ARMDefines.h"
#include "Utility/ARM_DWARF_Registers.h"
#include "Utility/ARM_ehframe_Registers.h"
Variables
static const RegisterInfo g_register_infos []
static const uint32_t k_num_register_infos = std::size(g_register_infos)
Variable Documentation
g_register_infos
const RegisterInfo g_register_infos[] static
Definition at line 38 of file ABIMacOSX_arm.cpp.
Referenced by GetPrivateRegisterInfoVector(), GetPrivateRegisterInfoVector(), GetRegisterInfo_i386(), GetRegisterInfo_i386(), ABIMacOSX_arm::GetRegisterInfoArray(), ABISysV_arm::GetRegisterInfoArray(), ABISysV_hexagon::GetRegisterInfoArray(), ABISysV_mips::GetRegisterInfoArray(), ABISysV_msp430::GetRegisterInfoArray(), ABISysV_ppc::GetRegisterInfoArray(), ABISysV_s390x::GetRegisterInfoArray(), RegisterContextDarwin_arm::GetRegisterInfoAtIndex(), RegisterContextDarwin_riscv32::GetRegisterInfoAtIndex(), RegisterContextDarwin_x86_64::GetRegisterInfoAtIndex(), RegisterContextDarwin_arm::GetRegisterInfos(), RegisterContextDarwin_riscv32::GetRegisterInfos(), RegisterContextDarwin_x86_64::GetRegisterInfos(), GetSharedRegisterInfoVector_i386(), and RegisterContextDarwin_riscv32::LogGPR().
k_num_register_infos
const uint32_t k_num_register_infos = std::size(g_register_infos) static
Definition at line 1288 of file ABIMacOSX_arm.cpp.
Referenced by RegisterContextDarwin_arm64::GetRegisterCount(), RegisterContextDarwin_arm::GetRegisterCount(), RegisterContextDarwin_riscv32::GetRegisterCount(), RegisterContextDarwin_x86_64::GetRegisterCount(), ABIMacOSX_arm::GetRegisterInfoArray(), ABISysV_arm::GetRegisterInfoArray(), ABISysV_hexagon::GetRegisterInfoArray(), ABISysV_mips64::GetRegisterInfoArray(), ABISysV_mips::GetRegisterInfoArray(), ABISysV_msp430::GetRegisterInfoArray(), ABISysV_ppc::GetRegisterInfoArray(), ABISysV_s390x::GetRegisterInfoArray(), RegisterContextDarwin_arm64::GetRegisterInfoAtIndex(), RegisterContextDarwin_arm::GetRegisterInfoAtIndex(), RegisterContextDarwin_riscv32::GetRegisterInfoAtIndex(), RegisterContextDarwin_x86_64::GetRegisterInfoAtIndex(), RegisterContextDarwin_arm64::GetRegisterInfosCount(), RegisterContextDarwin_arm::GetRegisterInfosCount(), RegisterContextDarwin_riscv32::GetRegisterInfosCount(), and RegisterContextDarwin_x86_64::GetRegisterInfosCount().