LLDB: ABIMacOSX_arm64.cpp File Reference
ABIMacOSX_arm64.cpp File Reference
#include "ABIMacOSX_arm64.h"
#include <optional>
#include <vector>
#include "llvm/ADT/STLExtras.h"
#include "llvm/TargetParser/Triple.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Value.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/RegisterValue.h"
#include "lldb/Utility/Scalar.h"
#include "lldb/Utility/Status.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
Functions
static bool LoadValueFromConsecutiveGPRRegisters (ExecutionContext &exe_ctx, RegisterContext *reg_ctx, const CompilerType &value_type, bool is_return_value, uint32_t &NGRN, uint32_t &NSRN, DataExtractor &data)
static addr_t DoFixAddr (addr_t addr, bool is_code, ProcessSP process_sp)
Consults the process for its {code, data} address masks and applies it to addr.
Variables
static const char * pluginDesc = "Mac OS X ABI for arm64 targets"
constexpr addr_t tbi_mask = 0xff80000000000000ULL
constexpr addr_t pac_sign_extension = 0x0080000000000000ULL
Function Documentation
DoFixAddr()
addr_t DoFixAddr (addr_t addr, bool is_code, ProcessSP process_sp) static
Consults the process for its {code, data} address masks and applies it to addr.
Definition at line 765 of file ABIMacOSX_arm64.cpp.
References LLDB_INVALID_ADDRESS_MASK, pac_sign_extension, and tbi_mask.
Referenced by ABIMacOSX_arm64::FixCodeAddress(), and ABIMacOSX_arm64::FixDataAddress().
LoadValueFromConsecutiveGPRRegisters()
bool LoadValueFromConsecutiveGPRRegisters (ExecutionContext & exe_ctx, RegisterContext * reg_ctx, const CompilerType & value_type, bool is_return_value, uint32_t & NGRN, uint32_t & NSRN, DataExtractor & data) static
Definition at line 433 of file ABIMacOSX_arm64.cpp.
References lldb_private::RegisterInfo::byte_size, lldb_private::RegisterContext::ConvertRegisterKindToRegisterNumber(), lldb::eRegisterKindGeneric, error(), lldb_private::Process::GetAddressByteSize(), lldb_private::RegisterValue::GetAsMemoryData(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::Process::GetByteOrder(), lldb_private::CompilerType::GetByteSize(), lldb_private::ExecutionContext::GetProcessRef(), lldb_private::RegisterContext::GetRegisterInfoAtIndex(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::CompilerType::IsHomogeneousAggregate(), LLDB_INVALID_ADDRESS, LLDB_INVALID_REGNUM, LLDB_REGNUM_GENERIC_ARG1, lldb_private::Process::ReadMemory(), lldb_private::RegisterContext::ReadRegister(), lldb_private::RegisterContext::ReadRegisterAsUnsigned(), lldb_private::DataExtractor::SetAddressByteSize(), lldb_private::DataExtractor::SetByteOrder(), and lldb_private::DataExtractor::SetData().
Referenced by ABIMacOSX_arm64::GetReturnValueObjectImpl(), and ABISysV_arm64::GetReturnValueObjectImpl().
Variable Documentation
pac_sign_extension
addr_t pac_sign_extension = 0x0080000000000000ULL constexpr
Definition at line 761 of file ABIMacOSX_arm64.cpp.
Referenced by DoFixAddr(), ABISysV_arm64::FixAddress(), ABIAArch64::FixCodeAddress(), ABISysV_arm64::FixCodeAddress(), ABIAArch64::FixDataAddress(), and ABISysV_arm64::FixDataAddress().
pluginDesc
const char* pluginDesc = "Mac OS X ABI for arm64 targets" static
Definition at line 35 of file ABIMacOSX_arm64.cpp.
Referenced by ABIMacOSX_arm64::Initialize().
tbi_mask
addr_t tbi_mask = 0xff80000000000000ULL constexpr
Definition at line 760 of file ABIMacOSX_arm64.cpp.
Referenced by DoFixAddr().