LLDB: ABISysV_arm64.cpp File Reference
ABISysV_arm64.cpp File Reference
#include "ABISysV_arm64.h"
#include <optional>
#include <vector>
#include "llvm/ADT/STLExtras.h"
#include "llvm/TargetParser/Triple.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Value.h"
#include "lldb/Symbol/UnwindPlan.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/RegisterValue.h"
#include "lldb/Utility/Scalar.h"
#include "lldb/Utility/Status.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
Functions
static Status PushToLinuxGuardedControlStack (addr_t return_addr, RegisterContext *reg_ctx, Thread &thread)
static bool LoadValueFromConsecutiveGPRRegisters (ExecutionContext &exe_ctx, RegisterContext *reg_ctx, const CompilerType &value_type, bool is_return_value, uint32_t &NGRN, uint32_t &NSRN, DataExtractor &data)
static lldb::addr_t ReadLinuxProcessAddressMask (lldb::ProcessSP process_sp, llvm::StringRef reg_name)
Function Documentation
LoadValueFromConsecutiveGPRRegisters()
bool LoadValueFromConsecutiveGPRRegisters (ExecutionContext & exe_ctx, RegisterContext * reg_ctx, const CompilerType & value_type, bool is_return_value, uint32_t & NGRN, uint32_t & NSRN, DataExtractor & data) static
Definition at line 476 of file ABISysV_arm64.cpp.
References lldb_private::RegisterInfo::byte_size, lldb::eRegisterKindGeneric, error(), lldb_private::Process::GetAddressByteSize(), lldb_private::RegisterValue::GetAsMemoryData(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::Process::GetByteOrder(), lldb_private::CompilerType::GetByteSize(), lldb_private::ExecutionContext::GetProcessRef(), lldb_private::RegisterContext::GetRegisterInfo(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::CompilerType::IsHomogeneousAggregate(), LLDB_INVALID_ADDRESS, LLDB_REGNUM_GENERIC_ARG1, lldb_private::Process::ReadMemory(), lldb_private::RegisterContext::ReadRegister(), lldb_private::RegisterContext::ReadRegisterAsUnsigned(), lldb_private::DataExtractor::SetAddressByteSize(), lldb_private::DataExtractor::SetByteOrder(), and lldb_private::DataExtractor::SetData().
PushToLinuxGuardedControlStack()
Status PushToLinuxGuardedControlStack (addr_t return_addr, RegisterContext * reg_ctx, Thread & thread) static
Definition at line 61 of file ABISysV_arm64.cpp.
References error(), lldb_private::Expressions, lldb_private::GetLog(), lldb_private::RegisterContext::GetRegisterInfoByName(), LLDB_INVALID_ADDRESS, LLDB_LOGF, lldb_private::RegisterContext::ReadRegisterAsUnsigned(), lldb_private::Status, and lldb_private::RegisterContext::WriteRegisterFromUnsigned().
Referenced by ABISysV_arm64::PrepareTrivialCall().
ReadLinuxProcessAddressMask()
lldb::addr_t ReadLinuxProcessAddressMask (lldb::ProcessSP process_sp, llvm::StringRef reg_name) static
Definition at line 806 of file ABISysV_arm64.cpp.
References lldb::eRegisterKindLLDB, lldb_private::RegisterInfo::kinds, LLDB_INVALID_ADDRESS, and LLDB_INVALID_ADDRESS_MASK.
Referenced by ABISysV_arm64::FixCodeAddress(), and ABISysV_arm64::FixDataAddress().