LLDB: ABISysV_riscv.cpp File Reference
ABISysV_riscv.cpp File Reference
#include "ABISysV_riscv.h"
#include <array>
#include <limits>
#include <sstream>
#include "llvm/ADT/STLExtras.h"
#include "llvm/IR/DerivedTypes.h"
#include "Utility/RISCV_DWARF_Registers.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Value.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/RegisterValue.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
Namespaces
namespace dwarf
Macros
#define DEFINE_REG_NAME(reg_num)
#define DEFINE_REG_NAME_STR(reg_name)
#define DEFINE_GENERIC_REGISTER_STUB(dwarf_num, str_name, generic_num)
#define DEFINE_REGISTER_STUB(dwarf_num, str_name)
Functions
static size_t AugmentArgSize (bool is_rv64, size_t size_in_bytes)
static size_t TotalArgsSizeInWords (bool is_rv64, const llvm::ArrayRef< ABI::CallArgument > &args)
static bool UpdateRegister (RegisterContext *reg_ctx, const lldb::RegisterKind reg_kind, const uint32_t reg_num, const addr_t value)
static void LogInitInfo (Log &log, const Thread &thread, addr_t sp, addr_t func_addr, addr_t return_addr, const llvm::ArrayRef< addr_t > args)
template<typename T>
static void SetInteger (Scalar &scalar, uint64_t raw_value, bool is_signed)
static bool SetSizedInteger (Scalar &scalar, uint64_t raw_value, uint8_t size_in_bytes, bool is_signed)
static bool SetSizedFloat (Scalar &scalar, uint64_t raw_value, uint8_t size_in_bytes)
static ValueObjectSP GetValObjFromIntRegs (Thread &thread, const RegisterContextSP &reg_ctx, llvm::Triple::ArchType machine, uint32_t type_flags, uint32_t byte_size)
static ValueObjectSP GetValObjFromFPRegs (Thread &thread, const RegisterContextSP &reg_ctx, llvm::Triple::ArchType machine, uint32_t arch_fp_flags, uint32_t type_flags, uint32_t byte_size)
static uint32_t GetGenericNum (llvm::StringRef name)
Variables
static constexpr size_t g_regs_for_args_count = 8U
Macro Definition Documentation
DEFINE_GENERIC_REGISTER_STUB
#define DEFINE_GENERIC_REGISTER_STUB (dwarf_num, str_name, generic_num)
Value:
  {                                                                            \
    DEFINE_REG_NAME(dwarf_num), DEFINE_REG_NAME_STR(str_name), 0, 0,           \
        eEncodingInvalid, eFormatDefault,                                      \
        {dwarf_num, dwarf_num, generic_num, LLDB_INVALID_REGNUM, dwarf_num},   \
        nullptr, nullptr, nullptr,                                             \
  }
Definition at line 34 of file ABISysV_riscv.cpp.
DEFINE_REG_NAME
#define DEFINE_REG_NAME (reg_num)
Value:
ConstString(#reg_num).GetCString()
Definition at line 28 of file ABISysV_riscv.cpp.
DEFINE_REG_NAME_STR
#define DEFINE_REG_NAME_STR (reg_name)
Value:
ConstString(reg_name).GetCString()
Definition at line 29 of file ABISysV_riscv.cpp.
DEFINE_REGISTER_STUB
#define DEFINE_REGISTER_STUB (dwarf_num, str_name)
Value:
  DEFINE_GENERIC_REGISTER_STUB(dwarf_num, str_name, LLDB_INVALID_REGNUM)
Definition at line 42 of file ABISysV_riscv.cpp.
Function Documentation
AugmentArgSize()
size_t AugmentArgSize (bool is_rv64, size_t size_in_bytes) inline static
Definition at line 153 of file ABISysV_riscv.cpp.
References word_size.
Referenced by TotalArgsSizeInWords().
GetGenericNum()
uint32_t GetGenericNum (llvm::StringRef name) static
Definition at line 817 of file ABISysV_riscv.cpp.
References LLDB_INVALID_REGNUM, LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_ARG2, LLDB_REGNUM_GENERIC_ARG3, LLDB_REGNUM_GENERIC_ARG4, LLDB_REGNUM_GENERIC_ARG5, LLDB_REGNUM_GENERIC_ARG6, LLDB_REGNUM_GENERIC_ARG7, LLDB_REGNUM_GENERIC_ARG8, LLDB_REGNUM_GENERIC_FP, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_RA, and LLDB_REGNUM_GENERIC_SP.
GetValObjFromFPRegs()
ValueObjectSP GetValObjFromFPRegs (Thread & thread, const RegisterContextSP & reg_ctx, llvm::Triple::ArchType machine, uint32_t arch_fp_flags, uint32_t type_flags, uint32_t byte_size) static
Definition at line 565 of file ABISysV_riscv.cpp.
References lldb_private::ValueObjectConstResult::Create(), lldb_private::ArchSpec::eRISCV_float_abi_double, lldb_private::ArchSpec::eRISCV_float_abi_quad, lldb_private::ArchSpec::eRISCV_float_abi_single, lldb_private::ArchSpec::eRISCV_float_abi_soft, lldb_private::Value::GetScalar(), GetValObjFromIntRegs(), lldb_private::Value::Scalar, SetSizedFloat(), and lldb_private::Value::SetValueType().
GetValObjFromIntRegs()
ValueObjectSP GetValObjFromIntRegs (Thread & thread, const RegisterContextSP & reg_ctx, llvm::Triple::ArchType machine, uint32_t type_flags, uint32_t byte_size) static
Definition at line 490 of file ABISysV_riscv.cpp.
References lldb_private::ValueObjectConstResult::Create(), lldb::eRegisterKindGeneric, error(), lldb_private::RegisterValue::GetAsMemoryData(), lldb_private::Value::GetScalar(), LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_ARG2, lldb_private::Value::Scalar, lldb_private::Value::SetBytes(), SetSizedFloat(), SetSizedInteger(), lldb_private::Value::SetValueType(), and UINT32_MAX.
Referenced by GetValObjFromFPRegs().
LogInitInfo()
void LogInitInfo (Log & log, const Thread & thread, addr_t sp, addr_t func_addr, addr_t return_addr, const llvm::ArrayRef< addr_t > args) static
Definition at line 190 of file ABISysV_riscv.cpp.
References lldb_private::Log::PutString(), and sp.
SetInteger()
template<typename T> void SetInteger (Scalar & scalar, uint64_t raw_value, bool is_signed) static
Definition at line 438 of file ABISysV_riscv.cpp.
Referenced by SetSizedInteger().
SetSizedFloat()
bool SetSizedFloat (Scalar & scalar, uint64_t raw_value, uint8_t size_in_bytes) static
Definition at line 472 of file ABISysV_riscv.cpp.
Referenced by GetValObjFromFPRegs(), and GetValObjFromIntRegs().
SetSizedInteger()
bool SetSizedInteger (Scalar & scalar, uint64_t raw_value, uint8_t size_in_bytes, bool is_signed) static
Definition at line 446 of file ABISysV_riscv.cpp.
References SetInteger().
Referenced by GetValObjFromIntRegs().
TotalArgsSizeInWords()
size_t TotalArgsSizeInWords (bool is_rv64, const llvm::ArrayRef< ABI::CallArgument > & args) static
Definition at line 159 of file ABISysV_riscv.cpp.
References AugmentArgSize(), reg_size, lldb_private::ABI::CallArgument::TargetValue, and word_size.
UpdateRegister()
bool UpdateRegister (RegisterContext * reg_ctx, const lldb::RegisterKind reg_kind, const uint32_t reg_num, const addr_t value) static
Definition at line 174 of file ABISysV_riscv.cpp.
References lldb_private::Expressions, lldb_private::GetLog(), lldb_private::RegisterContext::GetRegisterInfo(), LLDB_LOG, lldb_private::RegisterInfo::name, and lldb_private::RegisterContext::WriteRegisterFromUnsigned().
Variable Documentation
g_regs_for_args_count
size_t g_regs_for_args_count = 8U static constexpr
Definition at line 128 of file ABISysV_riscv.cpp.