LLDB: ABISysV_arm.cpp File Reference
ABISysV_arm.cpp File Reference
#include "ABISysV_arm.h"
#include <optional>
#include <vector>
#include "llvm/ADT/STLExtras.h"
#include "llvm/TargetParser/Triple.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Value.h"
#include "lldb/Symbol/UnwindPlan.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/RegisterValue.h"
#include "lldb/Utility/Scalar.h"
#include "lldb/Utility/Status.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
#include "Plugins/Process/Utility/ARMDefines.h"
#include "Utility/ARM_DWARF_Registers.h"
#include "Utility/ARM_ehframe_Registers.h"
Functions
static bool GetReturnValuePassedInMemory (Thread &thread, RegisterContext *reg_ctx, size_t byte_size, Value &value)
Variables
static const RegisterInfo g_register_infos []
static const uint32_t k_num_register_infos = std::size(g_register_infos)
Function Documentation
GetReturnValuePassedInMemory()
bool GetReturnValuePassedInMemory (Thread & thread, RegisterContext * reg_ctx, size_t byte_size, Value & value) static
Definition at line 1504 of file ABISysV_arm.cpp.
References lldb::eRegisterKindGeneric, error(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::DataBufferHeap::GetByteSize(), lldb_private::RegisterContext::GetRegisterInfo(), LLDB_REGNUM_GENERIC_ARG1, lldb_private::RegisterContext::ReadRegisterAsUnsigned(), lldb_private::Value::SetBytes(), and UINT32_MAX.
Referenced by ABISysV_arm::GetReturnValueObjectImpl().
Variable Documentation
g_register_infos
const RegisterInfo g_register_infos[] static
Definition at line 40 of file ABISysV_arm.cpp.
k_num_register_infos
const uint32_t k_num_register_infos = std::size(g_register_infos) static
Definition at line 1291 of file ABISysV_arm.cpp.