LLDB: ABISysV_arc.cpp File Reference
ABISysV_arc.cpp File Reference
#include "ABISysV_arc.h"
#include <array>
#include <limits>
#include <type_traits>
#include "llvm/IR/DerivedTypes.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/TargetParser/Triple.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Value.h"
#include "lldb/Symbol/UnwindPlan.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/RegisterValue.h"
#include "lldb/Utility/Status.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
#include "lldb/ValueObject/ValueObjectMemory.h"
#include "lldb/ValueObject/ValueObjectRegister.h"
Namespaces
namespace dwarf
Macros
#define DEFINE_REG_NAME(reg_num)
#define DEFINE_REG_NAME_STR(reg_name)
#define DEFINE_GENERIC_REGISTER_STUB(dwarf_num, str_name, generic_num)
#define DEFINE_REGISTER_STUB(dwarf_num, str_name)
Functions
static size_t AugmentArgSize (size_t size_in_bytes)
static size_t TotalArgsSizeInWords (const llvm::ArrayRef< ABI::CallArgument > &args)
template<typename T>
static void SetInteger (Scalar &scalar, uint64_t raw_value, bool is_signed)
static bool SetSizedInteger (Scalar &scalar, uint64_t raw_value, uint8_t size_in_bytes, bool is_signed)
static bool SetSizedFloat (Scalar &scalar, uint64_t raw_value, uint8_t size_in_bytes)
static uint64_t ReadRawValue (const RegisterContextSP &reg_ctx, uint8_t size_in_bytes)
Variables
static const size_t word_size = 4U
static const size_t reg_size = word_size
Macro Definition Documentation
DEFINE_GENERIC_REGISTER_STUB
#define DEFINE_GENERIC_REGISTER_STUB (dwarf_num, str_name, generic_num)
Value:
  {                                                                           \
    DEFINE_REG_NAME(dwarf_num), DEFINE_REG_NAME_STR(str_name),                \
    0, 0, eEncodingInvalid, eFormatDefault,                                   \
    { dwarf_num, dwarf_num, generic_num, LLDB_INVALID_REGNUM, dwarf_num },    \
    nullptr, nullptr, nullptr,                                                \
  }
Definition at line 44 of file ABISysV_arc.cpp.
DEFINE_REG_NAME
#define DEFINE_REG_NAME (reg_num)
Value:
ConstString(#reg_num).GetCString()
Definition at line 38 of file ABISysV_arc.cpp.
DEFINE_REG_NAME_STR
#define DEFINE_REG_NAME_STR (reg_name)
Value:
ConstString(reg_name).GetCString()
Definition at line 39 of file ABISysV_arc.cpp.
DEFINE_REGISTER_STUB
#define DEFINE_REGISTER_STUB (dwarf_num, str_name)
Value:
  DEFINE_GENERIC_REGISTER_STUB(dwarf_num, str_name, LLDB_INVALID_REGNUM)
Definition at line 52 of file ABISysV_arc.cpp.
Function Documentation
AugmentArgSize()
size_t AugmentArgSize (size_t size_in_bytes) inline static
Definition at line 173 of file ABISysV_arc.cpp.
References word_size.
Referenced by TotalArgsSizeInWords().
ReadRawValue()
uint64_t ReadRawValue (const RegisterContextSP & reg_ctx, uint8_t size_in_bytes) static
Definition at line 428 of file ABISysV_arc.cpp.
References lldb::eRegisterKindGeneric, LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_ARG2, UINT32_MAX, and UINT64_MAX.
Referenced by ABISysV_arc::GetReturnValueObjectImpl(), and ABISysV_arc::GetReturnValueObjectSimple().
SetInteger()
template<typename T> void SetInteger (Scalar & scalar, uint64_t raw_value, bool is_signed) static
Definition at line 376 of file ABISysV_arc.cpp.
Referenced by SetSizedInteger().
SetSizedFloat()
bool SetSizedFloat (Scalar & scalar, uint64_t raw_value, uint8_t size_in_bytes) static
Definition at line 410 of file ABISysV_arc.cpp.
Referenced by ABISysV_arc::GetReturnValueObjectImpl(), and ABISysV_arc::GetReturnValueObjectSimple().
SetSizedInteger()
bool SetSizedInteger (Scalar & scalar, uint64_t raw_value, uint8_t size_in_bytes, bool is_signed) static
Definition at line 384 of file ABISysV_arc.cpp.
References SetInteger().
Referenced by ABISysV_arc::GetReturnValueObjectImpl(), and ABISysV_arc::GetReturnValueObjectSimple().
TotalArgsSizeInWords()
size_t TotalArgsSizeInWords (const llvm::ArrayRef< ABI::CallArgument > & args) static
Definition at line 178 of file ABISysV_arc.cpp.
References AugmentArgSize(), reg_size, lldb_private::ABI::CallArgument::TargetValue, and word_size.
Variable Documentation
reg_size
const size_t reg_size = word_size static
Definition at line 171 of file ABISysV_arc.cpp.
Referenced by ABISysV_loongarch::CreateDefaultUnwindPlan(), ABISysV_riscv::CreateDefaultUnwindPlan(), lldb_private::npdb::GetVariableLocationInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_P(), ABISysV_arc::SetReturnValueObject(), ABISysV_loongarch::SetReturnValueObject(), ABISysV_riscv::SetReturnValueObject(), TotalArgsSizeInWords(), and TotalArgsSizeInWords().
word_size
const size_t word_size = 4U static
Definition at line 170 of file ABISysV_arc.cpp.
Referenced by AugmentArgSize(), AugmentArgSize(), lldb_private::PlatformWindows::DoLoadImage(), DYLDRendezvous::Resolve(), HexagonDYLDRendezvous::Resolve(), TotalArgsSizeInWords(), and TotalArgsSizeInWords().