LLDB: ABISysV_x86_64.cpp File Reference
ABISysV_x86_64.cpp File Reference
#include "ABISysV_x86_64.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/TargetParser/Triple.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Value.h"
#include "lldb/Symbol/UnwindPlan.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/DataExtractor.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/RegisterValue.h"
#include "lldb/Utility/Status.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
#include "lldb/ValueObject/ValueObjectMemory.h"
#include "lldb/ValueObject/ValueObjectRegister.h"
#include <optional>
#include <vector>
Enumerations
enum dwarf_regnums {
dwarf_rax = 0 , dwarf_rdx , dwarf_rcx , dwarf_rbx ,
dwarf_rsi , dwarf_rdi , dwarf_rbp , dwarf_rsp ,
dwarf_r8 , dwarf_r9 , dwarf_r10 , dwarf_r11 ,
dwarf_r12 , dwarf_r13 , dwarf_r14 , dwarf_r15 ,
dwarf_rip
}
Functions
static bool ReadIntegerArgument (Scalar &scalar, unsigned int bit_width, bool is_signed, Thread &thread, uint32_t *argument_register_ids, unsigned int &current_argument_register, addr_t &current_stack_argument)
static bool FlattenAggregateType (Thread &thread, ExecutionContext &exe_ctx, CompilerType &return_compiler_type, uint32_t data_byte_offset, std::vector< uint32_t > &aggregate_field_offsets, std::vector< CompilerType > &aggregate_compiler_types)
Enumeration Type Documentation
dwarf_regnums
enum dwarf_regnums
Enumerator
dwarf_rax
dwarf_rdx
dwarf_rcx
dwarf_rbx
dwarf_rsi
dwarf_rdi
dwarf_rbp
dwarf_rsp
dwarf_r8
dwarf_r9
dwarf_r10
dwarf_r11
dwarf_r12
dwarf_r13
dwarf_r14
dwarf_r15
dwarf_rip
Definition at line 42 of file ABISysV_x86_64.cpp.
Function Documentation
FlattenAggregateType()
bool FlattenAggregateType (Thread & thread, ExecutionContext & exe_ctx, CompilerType & return_compiler_type, uint32_t data_byte_offset, std::vector< uint32_t > & aggregate_field_offsets, std::vector< CompilerType > & aggregate_compiler_types) static
Definition at line 571 of file ABISysV_x86_64.cpp.
References FlattenAggregateType(), lldb_private::CompilerType::GetBitSize(), lldb_private::CompilerType::GetFieldAtIndex(), lldb_private::CompilerType::GetNumFields(), lldb_private::CompilerType::GetTypeInfo(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), and lldb_private::CompilerType::IsPointerType().
Referenced by FlattenAggregateType(), ABISysV_x86_64::GetReturnValueObjectImpl(), and ABIWindows_x86_64::GetReturnValueObjectImpl().
ReadIntegerArgument()
bool ReadIntegerArgument (Scalar & scalar, unsigned int bit_width, bool is_signed, Thread & thread, uint32_t * argument_register_ids, unsigned int & current_argument_register, addr_t & current_stack_argument) static
Definition at line 192 of file ABISysV_x86_64.cpp.
References error(), and lldb_private::Scalar::SignExtend().