LLDB: Address.cpp File Reference
Address.cpp File Reference
#include "lldb/Core/Address.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Declaration.h"
#include "lldb/Core/DumpDataExtractor.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleList.h"
#include "lldb/Core/Section.h"
#include "lldb/Symbol/Block.h"
#include "lldb/Symbol/LineEntry.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Symbol/Symbol.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Symbol/SymbolVendor.h"
#include "lldb/Symbol/Symtab.h"
#include "lldb/Symbol/Type.h"
#include "lldb/Symbol/Variable.h"
#include "lldb/Symbol/VariableList.h"
#include "lldb/Target/ABI.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/ExecutionContextScope.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/SectionLoadList.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/AnsiTerminal.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/DataExtractor.h"
#include "lldb/Utility/Endian.h"
#include "lldb/Utility/FileSpec.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/Stream.h"
#include "lldb/Utility/StreamString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Compiler.h"
#include "llvm/TargetParser/Triple.h"
#include <cstdint>
#include <memory>
#include <vector>
#include <cassert>
#include <cinttypes>
#include <cstring>
Namespaces
namespace lldb_private
A class that represents a running process on the host machine.
Functions
static size_t ReadBytes (ExecutionContextScope *exe_scope, const Address &address, void *dst, size_t dst_len)
static bool GetByteOrderAndAddressSize (ExecutionContextScope *exe_scope, const Address &address, ByteOrder &byte_order, uint32_t &addr_size)
static uint64_t ReadUIntMax64 (ExecutionContextScope *exe_scope, const Address &address, uint32_t byte_size, bool &success)
static bool ReadAddress (ExecutionContextScope *exe_scope, const Address &address, uint32_t pointer_size, Address &deref_so_addr)
static bool DumpUInt (ExecutionContextScope *exe_scope, const Address &address, uint32_t byte_size, Stream *strm)
static size_t ReadCStringFromMemory (ExecutionContextScope *exe_scope, const Address &address, Stream *strm)
Function Documentation
DumpUInt()
bool DumpUInt (ExecutionContextScope * exe_scope, const Address & address, uint32_t byte_size, Stream * strm) static
Definition at line 163 of file Address.cpp.
References lldb_private::DumpDataExtractor(), lldb::eByteOrderInvalid, lldb::eFormatHex, GetByteOrderAndAddressSize(), LLDB_INVALID_ADDRESS, ReadBytes(), and UINT32_MAX.
Referenced by lldb_private::Address::Dump().
GetByteOrderAndAddressSize()
bool GetByteOrderAndAddressSize (ExecutionContextScope * exe_scope, const Address & address, ByteOrder & byte_order, uint32_t & addr_size) static
Definition at line 78 of file Address.cpp.
References lldb_private::ExecutionContextScope::CalculateTarget(), lldb::eByteOrderInvalid, and lldb_private::Address::GetModule().
Referenced by DumpUInt(), and ReadUIntMax64().
ReadAddress()
bool ReadAddress (ExecutionContextScope * exe_scope, const Address & address, uint32_t pointer_size, Address & deref_so_addr) static
Definition at line 127 of file Address.cpp.
References lldb_private::ExecutionContextScope::CalculateExecutionContext(), lldb_private::Address::GetModule(), lldb_private::ExecutionContext::GetTargetPtr(), lldb_private::Target::HasLoadedSections(), ReadUIntMax64(), lldb_private::Target::ResolveLoadAddress(), and lldb_private::Address::SetRawAddress().
Referenced by lldb_private::Address::Dump().
ReadBytes()
size_t ReadBytes (ExecutionContextScope * exe_scope, const Address & address, void * dst, size_t dst_len) static
Definition at line 63 of file Address.cpp.
References lldb_private::ExecutionContextScope::CalculateTarget(), and error().
Referenced by DumpUInt(), ReadCStringFromMemory(), and ReadUIntMax64().
ReadCStringFromMemory()
size_t ReadCStringFromMemory (ExecutionContextScope * exe_scope, const Address & address, Stream * strm) static
Definition at line 191 of file Address.cpp.
References lldb_private::DumpDataExtractor(), lldb::eFormatChar, lldb_private::Address::GetOffset(), lldb_private::endian::InlHostByteOrder(), LLDB_INVALID_ADDRESS, lldb_private::Stream::PutChar(), ReadBytes(), lldb_private::Address::SetOffset(), and UINT32_MAX.
Referenced by lldb_private::Address::Dump().
ReadUIntMax64()
uint64_t ReadUIntMax64 (ExecutionContextScope * exe_scope, const Address & address, uint32_t byte_size, bool & success) static
Definition at line 103 of file Address.cpp.
References lldb::eByteOrderInvalid, GetByteOrderAndAddressSize(), lldb_private::DataExtractor::GetU64(), and ReadBytes().
Referenced by ReadAddress().