LLDB: Host.cpp File Reference
Host.cpp File Reference
#include "lldb/Host/Host.h"
#include "lldb/Host/posix/Support.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/ProcessInfo.h"
#include "lldb/Utility/Status.h"
#include "llvm/BinaryFormat/XCOFF.h"
#include <dirent.h>
#include <sys/proc.h>
#include <sys/procfs.h>
Functions
static ProcessInstanceInfo::timespec convert (pr_timestruc64_t t)
static bool GetStatusInfo (::pid_t pid, ProcessInstanceInfo &processInfo, ProcessState &State)
static bool GetExePathAndIds (::pid_t pid, ProcessInstanceInfo &process_info)
static bool GetProcessAndStatInfo (::pid_t pid, ProcessInstanceInfo &process_info, ProcessState &State)
Function Documentation
convert()
ProcessInstanceInfo::timespec convert (pr_timestruc64_t t) static
Definition at line 38 of file aix/Host.cpp.
References lldb_private::ProcessInstanceInfo::timespec::tv_sec, and lldb_private::ProcessInstanceInfo::timespec::tv_usec.
Referenced by GetStatusInfo(), and GetStatusInfo().
GetExePathAndIds()
bool GetExePathAndIds (::pid_t pid, ProcessInstanceInfo & process_info) static
Definition at line 84 of file aix/Host.cpp.
References lldb_private::eArchTypeXCOFF, lldb_private::ProcessInfo::GetExecutableFile(), lldb_private::getProcFile(), LLDB_INVALID_CPUTYPE, lldb_private::ArchSpec::SetArchitecture(), lldb_private::ProcessInfo::SetArchitecture(), lldb_private::ProcessInstanceInfo::SetEffectiveGroupID(), lldb_private::ProcessInstanceInfo::SetEffectiveUserID(), lldb_private::FileSpec::SetFile(), lldb_private::ProcessInfo::SetGroupID(), lldb_private::ProcessInstanceInfo::SetParentProcessID(), lldb_private::ProcessInstanceInfo::SetProcessGroupID(), lldb_private::ProcessInstanceInfo::SetProcessSessionID(), and lldb_private::ProcessInfo::SetUserID().
Referenced by GetProcessAndStatInfo().
GetProcessAndStatInfo()
bool GetProcessAndStatInfo (::pid_t pid, ProcessInstanceInfo & process_info, ProcessState & State) static
Definition at line 117 of file aix/Host.cpp.
References lldb_private::ProcessInstanceInfo::Clear(), GetExePathAndIds(), GetStatusInfo(), LLDB_INVALID_PROCESS_ID, and lldb_private::ProcessInfo::SetProcessID().
Referenced by lldb_private::Host::FindProcessesImpl(), and lldb_private::Host::GetProcessInfo().
GetStatusInfo()
bool GetStatusInfo (::pid_t pid, ProcessInstanceInfo & processInfo, ProcessState & State) static
Definition at line 45 of file aix/Host.cpp.
References convert(), lldb_private::getProcFile(), lldb_private::ProcessInstanceInfo::SetCumulativeSystemTime(), lldb_private::ProcessInstanceInfo::SetCumulativeUserTime(), lldb_private::ProcessInstanceInfo::SetIsZombie(), lldb_private::ProcessInstanceInfo::SetSystemTime(), and lldb_private::ProcessInstanceInfo::SetUserTime().
Referenced by lldb_private::getPIDForTID(), and GetProcessAndStatInfo().