LLDB: AppleObjCTypeEncodingParser.cpp File Reference
AppleObjCTypeEncodingParser.cpp File Reference
#include "AppleObjCTypeEncodingParser.h"
#include "Plugins/ExpressionParser/Clang/ClangUtil.h"
#include "Plugins/TypeSystem/Clang/TypeSystemClang.h"
#include "lldb/Symbol/CompilerType.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "clang/Basic/TargetInfo.h"
#include <optional>
#include <vector>
Functions
static char popChar (llvm::StringRef &str)
Function Documentation
popChar()
char popChar (llvm::StringRef & str) static
Definition at line 24 of file AppleObjCTypeEncodingParser.cpp.
Referenced by lldb_private::AppleObjCTypeEncodingParser::BuildType(), lldb_private::AppleObjCTypeEncodingParser::ReadNumber(), lldb_private::AppleObjCTypeEncodingParser::ReadQuotedString(), and lldb_private::AppleObjCTypeEncodingParser::ReadStructName().