LLDB: ArchSpec.cpp File Reference
ArchSpec.cpp File Reference
#include "lldb/Utility/ArchSpec.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/StringList.h"
#include "lldb/lldb-defines.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/BinaryFormat/COFF.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/BinaryFormat/MachO.h"
#include "llvm/BinaryFormat/XCOFF.h"
#include "llvm/Support/Compiler.h"
#include "llvm/TargetParser/ARMTargetParser.h"
Classes
struct lldb_private::CoreDefinition
struct ArchSpecValidator< I >
struct ArchSpecValidator< ArchSpec::kNumCores >
struct ArchDefinitionEntry
struct ArchDefinition
Namespaces
namespace lldb_private
A class that represents a running process on the host machine.
Macros
#define CPU_ANY (UINT32_MAX)
#define SUBTYPE_MASK 0x00FFFFFFu
Functions
static bool cores_match (const ArchSpec::Core core1, const ArchSpec::Core core2, bool try_inverse, bool enforce_exact_match)
static const ArchDefinition * FindArchDefinition (ArchitectureType arch_type)
static const CoreDefinition * FindCoreDefinition (llvm::StringRef name)
static const CoreDefinition * FindCoreDefinition (ArchSpec::Core core)
static const ArchDefinitionEntry * FindArchDefinitionEntry (const ArchDefinition *def, uint32_t cpu, uint32_t sub)
static const ArchDefinitionEntry * FindArchDefinitionEntry (const ArchDefinition *def, ArchSpec::Core core)
static bool IsCompatibleEnvironment (llvm::Triple::EnvironmentType lhs, llvm::Triple::EnvironmentType rhs)
Variables
static constexpr const CoreDefinition g_core_definitions []
ArchSpecValidator< ArchSpec::eCore_arm_generic > validator
static const ArchDefinitionEntry g_macho_arch_entries []
static const ArchDefinition g_macho_arch_def
static const ArchDefinitionEntry g_elf_arch_entries []
static const ArchDefinition g_elf_arch_def
static const ArchDefinitionEntry g_coff_arch_entries []
static const ArchDefinition g_coff_arch_def
static const ArchDefinitionEntry g_xcoff_arch_entries []
static const ArchDefinition g_xcoff_arch_def
static const ArchDefinition * g_arch_definitions []
Macro Definition Documentation
CPU_ANY
#define CPU_ANY (UINT32_MAX)
Definition at line 294 of file ArchSpec.cpp.
SUBTYPE_MASK
#define SUBTYPE_MASK 0x00FFFFFFu
Definition at line 301 of file ArchSpec.cpp.
Function Documentation
cores_match()
bool cores_match (const ArchSpec::Core core1, const ArchSpec::Core core2, bool try_inverse, bool enforce_exact_match) static
Definition at line 1083 of file ArchSpec.cpp.
References cores_match(), lldb_private::ArchSpec::eCore_arm_aarch64, lldb_private::ArchSpec::eCore_arm_arm64, lldb_private::ArchSpec::eCore_arm_arm64_32, lldb_private::ArchSpec::eCore_arm_arm64e, lldb_private::ArchSpec::eCore_arm_armv6m, lldb_private::ArchSpec::eCore_arm_armv7, lldb_private::ArchSpec::eCore_arm_armv7em, lldb_private::ArchSpec::eCore_arm_armv7f, lldb_private::ArchSpec::eCore_arm_armv7k, lldb_private::ArchSpec::eCore_arm_armv7l, lldb_private::ArchSpec::eCore_arm_armv7m, lldb_private::ArchSpec::eCore_arm_armv7s, lldb_private::ArchSpec::eCore_arm_armv8, lldb_private::ArchSpec::eCore_arm_armv8l, lldb_private::ArchSpec::eCore_arm_generic, lldb_private::ArchSpec::eCore_mips32, lldb_private::ArchSpec::eCore_mips32el, lldb_private::ArchSpec::eCore_mips32r2, lldb_private::ArchSpec::eCore_mips32r2el, lldb_private::ArchSpec::eCore_mips32r3, lldb_private::ArchSpec::eCore_mips32r3el, lldb_private::ArchSpec::eCore_mips32r5, lldb_private::ArchSpec::eCore_mips32r5el, lldb_private::ArchSpec::eCore_mips32r6, lldb_private::ArchSpec::eCore_mips32r6el, lldb_private::ArchSpec::eCore_mips64, lldb_private::ArchSpec::eCore_mips64el, lldb_private::ArchSpec::eCore_mips64r2, lldb_private::ArchSpec::eCore_mips64r2el, lldb_private::ArchSpec::eCore_mips64r3, lldb_private::ArchSpec::eCore_mips64r3el, lldb_private::ArchSpec::eCore_mips64r5, lldb_private::ArchSpec::eCore_mips64r5el, lldb_private::ArchSpec::eCore_mips64r6, lldb_private::ArchSpec::eCore_mips64r6el, lldb_private::ArchSpec::eCore_x86_64_amd64, lldb_private::ArchSpec::eCore_x86_64_x86_64, lldb_private::ArchSpec::eCore_x86_64_x86_64h, lldb_private::ArchSpec::kCore_any, lldb_private::ArchSpec::kCore_arm_any, lldb_private::ArchSpec::kCore_arm_first, lldb_private::ArchSpec::kCore_arm_last, lldb_private::ArchSpec::kCore_hexagon_any, lldb_private::ArchSpec::kCore_hexagon_first, lldb_private::ArchSpec::kCore_hexagon_last, lldb_private::ArchSpec::kCore_mips32_first, lldb_private::ArchSpec::kCore_mips32_last, lldb_private::ArchSpec::kCore_mips32el_first, lldb_private::ArchSpec::kCore_mips32el_last, lldb_private::ArchSpec::kCore_mips64_first, lldb_private::ArchSpec::kCore_mips64_last, lldb_private::ArchSpec::kCore_mips64el_first, lldb_private::ArchSpec::kCore_mips64el_last, lldb_private::ArchSpec::kCore_ppc64_any, lldb_private::ArchSpec::kCore_ppc64_first, lldb_private::ArchSpec::kCore_ppc64_last, lldb_private::ArchSpec::kCore_ppc_any, lldb_private::ArchSpec::kCore_ppc_first, lldb_private::ArchSpec::kCore_ppc_last, lldb_private::ArchSpec::kCore_thumb_first, lldb_private::ArchSpec::kCore_thumb_last, lldb_private::ArchSpec::kCore_x86_32_any, lldb_private::ArchSpec::kCore_x86_32_first, lldb_private::ArchSpec::kCore_x86_32_last, lldb_private::ArchSpec::kCore_x86_64_any, lldb_private::ArchSpec::kCore_x86_64_first, and lldb_private::ArchSpec::kCore_x86_64_last.
Referenced by cores_match(), and lldb_private::ArchSpec::IsMatch().
FindArchDefinition()
const ArchDefinition * FindArchDefinition (ArchitectureType arch_type) static
Definition at line 467 of file ArchSpec.cpp.
References g_arch_definitions.
Referenced by lldb_private::ArchSpec::SetArchitecture().
FindArchDefinitionEntry() [1/2]
const ArchDefinitionEntry * FindArchDefinitionEntry (const ArchDefinition * def, ArchSpec::Core core) static
Definition at line 506 of file ArchSpec.cpp.
References ArchDefinition::entries, and ArchDefinition::num_entries.
FindArchDefinitionEntry() [2/2]
const ArchDefinitionEntry * FindArchDefinitionEntry (const ArchDefinition * def, uint32_t cpu, uint32_t sub) static
Definition at line 492 of file ArchSpec.cpp.
References ArchDefinition::entries, and ArchDefinition::num_entries.
Referenced by lldb_private::ArchSpec::GetMachOCPUSubType(), lldb_private::ArchSpec::GetMachOCPUType(), and lldb_private::ArchSpec::SetArchitecture().
FindCoreDefinition() [1/2]
const CoreDefinition * FindCoreDefinition (ArchSpec::Core core) inline static
Definition at line 484 of file ArchSpec.cpp.
References g_core_definitions.
FindCoreDefinition() [2/2]
const CoreDefinition * FindCoreDefinition (llvm::StringRef name) static
Definition at line 476 of file ArchSpec.cpp.
References g_core_definitions.
Referenced by lldb_private::ArchSpec::CoreUpdated(), lldb_private::ArchSpec::GetAddressByteSize(), lldb_private::ArchSpec::GetArchitectureName(), lldb_private::ArchSpec::GetDefaultEndian(), lldb_private::ArchSpec::GetMachine(), lldb_private::ArchSpec::GetMachOCPUSubType(), lldb_private::ArchSpec::GetMachOCPUType(), lldb_private::ArchSpec::GetMaximumOpcodeByteSize(), lldb_private::ArchSpec::GetMinimumOpcodeByteSize(), lldb_private::ArchSpec::SetArchitecture(), and lldb_private::ArchSpec::UpdateCore().
IsCompatibleEnvironment()
bool IsCompatibleEnvironment (llvm::Triple::EnvironmentType lhs, llvm::Triple::EnvironmentType rhs) static
Definition at line 936 of file ArchSpec.cpp.
Referenced by lldb_private::ArchSpec::IsMatch().
Variable Documentation
g_arch_definitions
const ArchDefinition* g_arch_definitions[] static
Initial value:
= {
    &g_macho_arch_def, &g_elf_arch_def, &g_coff_arch_def, &g_xcoff_arch_def}
Definition at line 460 of file ArchSpec.cpp.
Referenced by FindArchDefinition().
g_coff_arch_def
const ArchDefinition g_coff_arch_def static
Initial value:
= {
    eArchTypeCOFF,
    std::size(g_coff_arch_entries),
    g_coff_arch_entries,
    "pe-coff",
}
Definition at line 437 of file ArchSpec.cpp.
g_coff_arch_entries
const ArchDefinitionEntry g_coff_arch_entries[] static
Initial value:
= {
    {ArchSpec::eCore_x86_32_i386,   llvm::COFF::IMAGE_FILE_MACHINE_I386},
    {ArchSpec::eCore_ppc_generic,   llvm::COFF::IMAGE_FILE_MACHINE_POWERPC},
    {ArchSpec::eCore_ppc_generic,   llvm::COFF::IMAGE_FILE_MACHINE_POWERPCFP},
    {ArchSpec::eCore_arm_generic,   llvm::COFF::IMAGE_FILE_MACHINE_ARM},
    {ArchSpec::eCore_arm_armv7,     llvm::COFF::IMAGE_FILE_MACHINE_ARMNT},
    {ArchSpec::eCore_thumb,         llvm::COFF::IMAGE_FILE_MACHINE_THUMB},
    {ArchSpec::eCore_x86_64_x86_64, llvm::COFF::IMAGE_FILE_MACHINE_AMD64},
    {ArchSpec::eCore_arm_arm64,     llvm::COFF::IMAGE_FILE_MACHINE_ARM64}
}
Definition at line 425 of file ArchSpec.cpp.
g_core_definitions
const CoreDefinition g_core_definitions[] static constexpr
Definition at line 44 of file ArchSpec.cpp.
Referenced by lldb_private::ArchSpec::AutoComplete(), FindCoreDefinition(), FindCoreDefinition(), and lldb_private::ArchSpec::ListSupportedArchNames().
g_elf_arch_def
const ArchDefinition g_elf_arch_def static
Initial value:
= {
    eArchTypeELF,
    std::size(g_elf_arch_entries),
    g_elf_arch_entries,
    "elf",
}
Definition at line 418 of file ArchSpec.cpp.
g_elf_arch_entries
const ArchDefinitionEntry g_elf_arch_entries[] static
Definition at line 383 of file ArchSpec.cpp.
g_macho_arch_def
const ArchDefinition g_macho_arch_def static
Initial value:
= {eArchTypeMachO,
                                                std::size(g_macho_arch_entries),
                                                g_macho_arch_entries, "mach-o"}
Definition at line 373 of file ArchSpec.cpp.
Referenced by lldb_private::ArchSpec::GetMachOCPUSubType(), and lldb_private::ArchSpec::GetMachOCPUType().
g_macho_arch_entries
const ArchDefinitionEntry g_macho_arch_entries[] static
Definition at line 304 of file ArchSpec.cpp.
g_xcoff_arch_def
const ArchDefinition g_xcoff_arch_def static
Initial value:
= {
    eArchTypeXCOFF,
    std::size(g_xcoff_arch_entries),
    g_xcoff_arch_entries,
    "xcoff",
}
Definition at line 451 of file ArchSpec.cpp.
g_xcoff_arch_entries
const ArchDefinitionEntry g_xcoff_arch_entries[] static
Initial value:
= {
    {ArchSpec::eCore_ppc_generic,   llvm::XCOFF::TCPU_COM},
    {ArchSpec::eCore_ppc64_generic, llvm::XCOFF::TCPU_PPC64}
}
Definition at line 445 of file ArchSpec.cpp.
validator
ArchSpecValidator<ArchSpec::eCore_arm_generic> validator
Definition at line 267 of file ArchSpec.cpp.