LLDB: ArchitecturePPC64.cpp File Reference
ArchitecturePPC64.cpp File Reference
#include "Plugins/Architecture/PPC64/ArchitecturePPC64.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Symbol/Function.h"
#include "lldb/Symbol/Symbol.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/ArchSpec.h"
#include "llvm/BinaryFormat/ELF.h"
Functions
static int32_t GetLocalEntryOffset (const Symbol &sym)
Function Documentation
GetLocalEntryOffset()
int32_t GetLocalEntryOffset (const Symbol & sym) static
Definition at line 42 of file ArchitecturePPC64.cpp.
References lldb_private::Symbol::GetFlags().
Referenced by lldb_private::ArchitecturePPC64::AdjustBreakpointAddress(), and lldb_private::ArchitecturePPC64::GetBytesToSkip().