LLDB: Args.cpp File Reference
Args.cpp File Reference
#include "lldb/Utility/Args.h"
#include "lldb/Utility/FileSpec.h"
#include "lldb/Utility/Stream.h"
#include "lldb/Utility/StringList.h"
#include "llvm/ADT/StringSwitch.h"
Functions
static llvm::StringRef ParseDoubleQuotes (llvm::StringRef quoted, std::string &result)
static size_t ArgvToArgc (const char **argv)
static llvm::StringRef ltrimForArgs (llvm::StringRef str, size_t &shift)
static std::tuple< std::string, char, llvm::StringRef > ParseSingleArgument (llvm::StringRef command)
Function Documentation
ArgvToArgc()
size_t ArgvToArgc (const char ** argv) static
Definition at line 58 of file Args.cpp.
Referenced by lldb_private::Args::AppendArguments(), and lldb_private::Args::SetArguments().
ltrimForArgs()
llvm::StringRef ltrimForArgs (llvm::StringRef str, size_t & shift) static
Definition at line 69 of file Args.cpp.
Referenced by lldb_private::Args::SetCommandString(), and lldb_private::OptionsWithRaw::SetFromString().
ParseDoubleQuotes()
llvm::StringRef ParseDoubleQuotes (llvm::StringRef quoted, std::string & result) static
Definition at line 23 of file Args.cpp.
Referenced by ParseSingleArgument().
ParseSingleArgument()
std::tuple< std::string, char, llvm::StringRef > ParseSingleArgument (llvm::StringRef command) static
Definition at line 82 of file Args.cpp.
References ParseDoubleQuotes().
Referenced by lldb_private::Args::SetCommandString(), and lldb_private::OptionsWithRaw::SetFromString().