LLDB: Block.cpp File Reference
Block.cpp File Reference
#include "lldb/Symbol/Block.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/Section.h"
#include "lldb/Symbol/Function.h"
#include "lldb/Symbol/SymbolFile.h"
#include "lldb/Symbol/VariableList.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include <memory>
Functions
static AddressRange ToAddressRange (const Address &func_addr, const Block::Range &block_range)
Function Documentation
ToAddressRange()
AddressRange ToAddressRange (const Address & func_addr, const Block::Range & block_range) static
Definition at line 286 of file Block.cpp.
References lldb_private::Range< B, S >::base, lldb_private::Address::GetFileAddress(), lldb_private::Address::GetModule(), and lldb_private::Range< B, S >::size.
Referenced by lldb_private::Block::GetRangeAtIndex(), lldb_private::Block::GetRanges(), and lldb_private::Block::GetStartAddress().