LLDB: BreakpointList.cpp File Reference
BreakpointList.cpp File Reference
#include "lldb/Breakpoint/BreakpointList.h"
#include "lldb/Target/Target.h"
#include "llvm/Support/Errc.h"
Functions
static void NotifyChange (const BreakpointSP &bp, BreakpointEventType event)
Function Documentation
NotifyChange()
void NotifyChange (const BreakpointSP & bp, BreakpointEventType event) static
Definition at line 18 of file BreakpointList.cpp.
Referenced by lldb_private::BreakpointList::Add(), lldb_private::BreakpointList::Remove(), lldb_private::BreakpointList::RemoveAll(), and lldb_private::BreakpointList::RemoveAllowed().