LLDB: Breakpoint.cpp File Reference
Breakpoint.cpp File Reference
#include "llvm/Support/Casting.h"
#include "lldb/Breakpoint/Breakpoint.h"
#include "lldb/Breakpoint/BreakpointLocation.h"
#include "lldb/Breakpoint/BreakpointLocationCollection.h"
#include "lldb/Breakpoint/BreakpointPrecondition.h"
#include "lldb/Breakpoint/BreakpointResolver.h"
#include "lldb/Breakpoint/BreakpointResolverFileLine.h"
#include "lldb/Core/Address.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleList.h"
#include "lldb/Core/SearchFilter.h"
#include "lldb/Core/Section.h"
#include "lldb/Symbol/CompileUnit.h"
#include "lldb/Symbol/Function.h"
#include "lldb/Symbol/Symbol.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Target/SectionLoadList.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/ThreadSpec.h"
#include "lldb/Utility/AnsiTerminal.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/Stream.h"
#include "lldb/Utility/StreamString.h"
#include <memory>
Functions
static bool SymbolContextsMightBeEquivalent (SymbolContext &old_sc, SymbolContext &new_sc)
Function Documentation
SymbolContextsMightBeEquivalent()
bool SymbolContextsMightBeEquivalent (SymbolContext & old_sc, SymbolContext & new_sc) static
Definition at line 674 of file Breakpoint.cpp.
References lldb_private::SymbolContext::comp_unit, lldb_private::Mangled::Compare(), lldb_private::SymbolContext::function, lldb_private::Symbol::GetMangled(), lldb_private::Function::GetName(), lldb_private::CompileUnit::GetPrimaryFile(), lldb_private::SymbolContext::module_sp, and lldb_private::SymbolContext::symbol.
Referenced by lldb_private::Breakpoint::ModuleReplaced().