LLDB: BreakpadRecords.cpp File Reference
BreakpadRecords.cpp File Reference
#include "Plugins/ObjectFile/Breakpad/BreakpadRecords.h"
#include "lldb/lldb-defines.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/FormatVariadic.h"
#include <optional>
Functions
template<typename T>
static T stringTo (llvm::StringRef Str)
template<>
Token stringTo< Token > (llvm::StringRef Str)
template<>
llvm::Triple::OSType stringTo< llvm::Triple::OSType > (llvm::StringRef Str)
template<>
llvm::Triple::ArchType stringTo< llvm::Triple::ArchType > (llvm::StringRef Str)
template<typename T>
static T consume (llvm::StringRef &Str)
template<typename T>
static constexpr size_t hex_digits ()
Return the number of hex digits needed to encode an (POD) object of a given type.
static UUID parseModuleId (llvm::Triple::OSType os, llvm::StringRef str)
template<typename T>
static std::optional< T > parseNumberName (llvm::StringRef Line, Token TokenType)
static bool parsePublicOrFunc (llvm::StringRef Line, bool &Multiple, lldb::addr_t &Address, lldb::addr_t *Size, lldb::addr_t &ParamSize, llvm::StringRef &Name)
Function Documentation
consume()
template<typename T> T consume (llvm::StringRef & Str) static
Definition at line 87 of file BreakpadRecords.cpp.
References stringTo().
Referenced by lldb_private::breakpad::Record::classify(), lldb_private::breakpad::InfoRecord::parse(), lldb_private::breakpad::InlineRecord::parse(), lldb_private::breakpad::ModuleRecord::parse(), lldb_private::breakpad::StackCFIRecord::parse(), lldb_private::breakpad::StackWinRecord::parse(), parseNumberName(), and parsePublicOrFunc().
hex_digits()
template<typename T> constexpr size_t hex_digits () static constexpr
Return the number of hex digits needed to encode an (POD) object of a given type.
Definition at line 95 of file BreakpadRecords.cpp.
Referenced by parseModuleId().
parseModuleId()
UUID parseModuleId (llvm::Triple::OSType os, llvm::StringRef str) static
Definition at line 99 of file BreakpadRecords.cpp.
References hex_digits(), and UNUSED_IF_ASSERT_DISABLED.
Referenced by lldb_private::breakpad::ModuleRecord::parse().
parseNumberName()
template<typename T> std::optional< T > parseNumberName (llvm::StringRef Line, Token TokenType) static
Definition at line 230 of file BreakpadRecords.cpp.
References consume().
Referenced by lldb_private::breakpad::FileRecord::parse(), and lldb_private::breakpad::InlineOriginRecord::parse().
parsePublicOrFunc()
bool parsePublicOrFunc (llvm::StringRef Line, bool & Multiple, lldb::addr_t & Address, lldb::addr_t * Size, lldb::addr_t & ParamSize, llvm::StringRef & Name) static
Definition at line 269 of file BreakpadRecords.cpp.
References consume().
Referenced by lldb_private::breakpad::FuncRecord::parse(), and lldb_private::breakpad::PublicRecord::parse().
stringTo()
template<typename T> T stringTo (llvm::StringRef Str) static
Referenced by consume().
stringTo< llvm::Triple::ArchType >()
template<> llvm::Triple::ArchType stringTo< llvm::Triple::ArchType > (llvm::StringRef Str)
Definition at line 69 of file BreakpadRecords.cpp.
stringTo< llvm::Triple::OSType >()
template<> llvm::Triple::OSType stringTo< llvm::Triple::OSType > (llvm::StringRef Str)
Definition at line 59 of file BreakpadRecords.cpp.
stringTo< Token >()
template<> Token stringTo< Token > (llvm::StringRef Str)
Definition at line 41 of file BreakpadRecords.cpp.
Referenced by lldb_private::breakpad::StackCFIRecord::parse().