LLDB: ClangExpressionSourceCode.cpp File Reference
ClangExpressionSourceCode.cpp File Reference
#include "ClangExpressionSourceCode.h"
#include "ClangExpressionUtil.h"
#include "clang/AST/TypeBase.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/FileManager.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Lex/Lexer.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/StringRef.h"
#include "Plugins/ExpressionParser/Clang/ClangModulesDeclVendor.h"
#include "Plugins/ExpressionParser/Clang/ClangPersistentVariables.h"
#include "lldb/Symbol/Block.h"
#include "lldb/Symbol/CompileUnit.h"
#include "lldb/Symbol/DebugMacros.h"
#include "lldb/Symbol/TypeSystem.h"
#include "lldb/Symbol/VariableList.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/Language.h"
#include "lldb/Target/Platform.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/lldb-forward.h"
Macros
#define PREFIX_NAME "<lldb wrapper prefix>"
#define SUFFIX_NAME "<lldb wrapper suffix>"
Functions
static void AddMacros (const DebugMacros *dm, CompileUnit *comp_unit, AddMacroState &state, StreamString &stream)
static clang::Qualifiers GetFrameCVQualifiers (StackFrame *frame)
Return qualifers of the current C++ method.
Macro Definition Documentation
PREFIX_NAME
#define PREFIX_NAME "<lldb wrapper prefix>"
Definition at line 38 of file ClangExpressionSourceCode.cpp.
SUFFIX_NAME
#define SUFFIX_NAME "<lldb wrapper suffix>"
Definition at line 39 of file ClangExpressionSourceCode.cpp.
Function Documentation
AddMacros()
void AddMacros (const DebugMacros * dm, CompileUnit * comp_unit, AddMacroState & state, StreamString & stream) static
Definition at line 141 of file ClangExpressionSourceCode.cpp.
References AddMacros(), lldb_private::ConstString::AsCString(), lldb_private::DebugMacroEntry::DEFINE, lldb_private::DebugMacroEntry::END_FILE, lldb_private::DebugMacroEntry::GetFileSpec(), lldb_private::DebugMacroEntry::GetIndirectDebugMacros(), lldb_private::DebugMacroEntry::GetLineNumber(), lldb_private::DebugMacros::GetMacroEntryAtIndex(), lldb_private::DebugMacroEntry::GetMacroString(), lldb_private::DebugMacros::GetNumMacroEntries(), lldb_private::DebugMacroEntry::GetType(), lldb_private::DebugMacroEntry::INDIRECT, lldb_private::Stream::Printf(), lldb_private::DebugMacroEntry::START_FILE, and lldb_private::DebugMacroEntry::UNDEF.
Referenced by AddMacros(), and lldb_private::ClangExpressionSourceCode::GetText().
GetFrameCVQualifiers()
clang::Qualifiers GetFrameCVQualifiers (StackFrame * frame) static
Return qualifers of the current C++ method.
Definition at line 194 of file ClangExpressionSourceCode.cpp.
References lldb_private::StackFrame::FindVariable().
Referenced by lldb_private::ClangExpressionSourceCode::GetText().