LLDB: NullDiagnosticConsumer Class Reference
NullDiagnosticConsumer Class Reference
Public Member Functions
NullDiagnosticConsumer ()
void HandleDiagnostic (DiagnosticsEngine::Level DiagLevel, const clang::Diagnostic &info) override
DiagnosticConsumer * clone (DiagnosticsEngine &Diags) const
Private Attributes
Log * m_log
Detailed Description
Definition at line 631 of file TypeSystemClang.cpp.
Constructor & Destructor Documentation
NullDiagnosticConsumer()
NullDiagnosticConsumer::NullDiagnosticConsumer () inline
Definition at line 633 of file TypeSystemClang.cpp.
References lldb_private::Expressions, lldb_private::GetLog(), and m_log.
Referenced by clone().
Member Function Documentation
clone()
DiagnosticConsumer * NullDiagnosticConsumer::clone (DiagnosticsEngine & Diags) const inline
Definition at line 645 of file TypeSystemClang.cpp.
References NullDiagnosticConsumer().
HandleDiagnostic()
void NullDiagnosticConsumer::HandleDiagnostic (DiagnosticsEngine::Level DiagLevel, const clang::Diagnostic & info) inline override
Definition at line 635 of file TypeSystemClang.cpp.
References LLDB_LOGF, and m_log.
Member Data Documentation
m_log
Log* NullDiagnosticConsumer::m_log private
Definition at line 650 of file TypeSystemClang.cpp.
Referenced by HandleDiagnostic(), and NullDiagnosticConsumer().
The documentation for this class was generated from the following file:
TypeSystemClang.cpp