LLDB: lldb_private::NativeRegisterContextRegisterInfo Class Reference
lldb_private::NativeRegisterContextRegisterInfo Class Reference
#include <NativeRegisterContextRegisterInfo.h>
Public Member Functions
NativeRegisterContextRegisterInfo (NativeThreadProtocol &thread, RegisterInfoInterface *register_info_interface)
Construct a NativeRegisterContextRegisterInfo, taking ownership of the register_info_interface pointer.
uint32_t GetRegisterCount () const override
uint32_t GetUserRegisterCount () const override
const RegisterInfo * GetRegisterInfoAtIndex (uint32_t reg_index) const override
const RegisterInfoInterface & GetRegisterInfoInterface () const
Public Member Functions inherited from lldb_private::NativeRegisterContext
NativeRegisterContext (NativeThreadProtocol &thread)
virtual ~NativeRegisterContext ()
const char * GetRegisterSetNameForRegisterAtIndex (uint32_t reg_index) const
virtual uint32_t GetRegisterSetCount () const =0
virtual const RegisterSet * GetRegisterSet (uint32_t set_index) const =0
virtual Status ReadRegister (const RegisterInfo *reg_info, RegisterValue &reg_value)=0
virtual Status WriteRegister (const RegisterInfo *reg_info, const RegisterValue &reg_value)=0
virtual Status ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp)=0
virtual Status WriteAllRegisterValues (const lldb::DataBufferSP &data_sp)=0
uint32_t ConvertRegisterKindToRegisterNumber (uint32_t kind, uint32_t num) const
virtual uint32_t NumSupportedHardwareBreakpoints ()
virtual uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual bool ClearHardwareBreakpoint (uint32_t hw_idx)
virtual Status ClearAllHardwareBreakpoints ()
virtual Status GetHardwareBreakHitIndex (uint32_t &bp_index, lldb::addr_t trap_addr)
virtual uint32_t NumSupportedHardwareWatchpoints ()
virtual uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, uint32_t watch_flags)
virtual bool ClearHardwareWatchpoint (uint32_t hw_index)
virtual Status ClearWatchpointHit (uint32_t hw_index)
virtual Status ClearAllHardwareWatchpoints ()
virtual Status IsWatchpointHit (uint32_t wp_index, bool &is_hit)
virtual Status GetWatchpointHitIndex (uint32_t &wp_index, lldb::addr_t trap_addr)
virtual Status IsWatchpointVacant (uint32_t wp_index, bool &is_vacant)
virtual lldb::addr_t GetWatchpointAddress (uint32_t wp_index)
virtual lldb::addr_t GetWatchpointHitAddress (uint32_t wp_index)
virtual bool HardwareSingleStep (bool enable)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, size_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, size_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual NativeThreadProtocol & GetThread ()
virtual std::vector< uint32_t > GetExpeditedRegisters (ExpeditedRegs expType) const
virtual bool RegisterOffsetIsDynamic () const
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (uint32_t reg_kind, uint32_t reg_num)
lldb::addr_t GetPC (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
virtual lldb::addr_t GetPCfromBreakpointLocation (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
Status SetPC (lldb::addr_t pc)
lldb::addr_t GetSP (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
Status SetSP (lldb::addr_t sp)
lldb::addr_t GetFP (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
Status SetFP (lldb::addr_t fp)
const char * GetRegisterName (uint32_t reg)
lldb::addr_t GetReturnAddress (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
lldb::addr_t GetFlags (lldb::addr_t fail_value=0)
lldb::addr_t ReadRegisterAsUnsigned (uint32_t reg, lldb::addr_t fail_value)
lldb::addr_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, lldb::addr_t fail_value)
Status WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
Status WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
Protected Attributes
std::unique_ptr< RegisterInfoInterface > m_register_info_interface_up
Protected Attributes inherited from lldb_private::NativeRegisterContext
NativeThreadProtocol & m_thread
Detailed Description
Definition at line 18 of file NativeRegisterContextRegisterInfo.h.
Constructor & Destructor Documentation
NativeRegisterContextRegisterInfo()
NativeRegisterContextRegisterInfo::NativeRegisterContextRegisterInfo (NativeThreadProtocol & thread, RegisterInfoInterface * register_info_interface)
Construct a NativeRegisterContextRegisterInfo, taking ownership of the register_info_interface pointer.
Definition at line 15 of file NativeRegisterContextRegisterInfo.cpp.
References m_register_info_interface_up, and lldb_private::NativeRegisterContext::NativeRegisterContext().
Referenced by lldb_private::process_aix::NativeRegisterContextAIX::NativeRegisterContextAIX(), lldb_private::NativeRegisterContextDBReg_x86::NativeRegisterContextDBReg_x86(), and lldb_private::process_linux::NativeRegisterContextLinux::NativeRegisterContextLinux().
Member Function Documentation
GetRegisterCount()
uint32_t NativeRegisterContextRegisterInfo::GetRegisterCount () const override virtual
Implements lldb_private::NativeRegisterContext.
Definition at line 23 of file NativeRegisterContextRegisterInfo.cpp.
References m_register_info_interface_up.
Referenced by GetRegisterInfoAtIndex().
GetRegisterInfoAtIndex()
const RegisterInfo * NativeRegisterContextRegisterInfo::GetRegisterInfoAtIndex (uint32_t reg_index) const override virtual
Implements lldb_private::NativeRegisterContext.
Definition at line 31 of file NativeRegisterContextRegisterInfo.cpp.
References GetRegisterCount(), and m_register_info_interface_up.
Referenced by lldb_private::NativeRegisterContextDBReg_x86::GetDR(), lldb_private::process_linux::NativeRegisterContextLinux::GetPtraceOffset(), lldb_private::process_linux::NativeRegisterContextLinux::ReadRegisterRaw(), and lldb_private::process_linux::NativeRegisterContextLinux::WriteRegisterRaw().
GetRegisterInfoInterface()
const RegisterInfoInterface & NativeRegisterContextRegisterInfo::GetRegisterInfoInterface () const
Definition at line 40 of file NativeRegisterContextRegisterInfo.cpp.
References m_register_info_interface_up.
Referenced by lldb_private::NativeRegisterContextDBReg_x86::GetDR(), and lldb_private::process_linux::NativeRegisterContextLinux::GetGPRSize().
GetUserRegisterCount()
uint32_t NativeRegisterContextRegisterInfo::GetUserRegisterCount () const override virtual
Implements lldb_private::NativeRegisterContext.
Definition at line 27 of file NativeRegisterContextRegisterInfo.cpp.
References m_register_info_interface_up.
Member Data Documentation
m_register_info_interface_up
std::unique_ptr<RegisterInfoInterface> lldb_private::NativeRegisterContextRegisterInfo::m_register_info_interface_up protected
Definition at line 37 of file NativeRegisterContextRegisterInfo.h.
Referenced by GetRegisterCount(), GetRegisterInfoAtIndex(), GetRegisterInfoInterface(), GetUserRegisterCount(), and NativeRegisterContextRegisterInfo().
The documentation for this class was generated from the following files:
NativeRegisterContextRegisterInfo.h
NativeRegisterContextRegisterInfo.cpp