LLDB: lldb_private::OptionValueDictionary Class Reference
lldb_private::OptionValueDictionary Class Reference
#include <OptionValueDictionary.h>
Public Member Functions
OptionValueDictionary (uint32_t type_mask=UINT32_MAX, OptionEnumValues enum_values=OptionEnumValues(), bool raw_value_dump=true)
~OptionValueDictionary () override=default
OptionValue::Type GetType () const override
void DumpValue (const ExecutionContext *exe_ctx, Stream &strm, uint32_t dump_mask) override
llvm::json::Value ToJSON (const ExecutionContext *exe_ctx) const override
Status SetValueFromString (llvm::StringRef value, VarSetOperationType op=eVarSetOperationAssign) override
void Clear () override
lldb::OptionValueSP DeepCopy (const lldb::OptionValueSP &new_parent) const override
bool IsAggregateValue () const override
bool IsHomogenous () const
size_t GetNumValues () const
lldb::OptionValueSP GetValueForKey (llvm::StringRef key) const
lldb::OptionValueSP GetSubValue (const ExecutionContext *exe_ctx, llvm::StringRef name, Status &error) const override
Status SetSubValue (const ExecutionContext *exe_ctx, VarSetOperationType op, llvm::StringRef name, llvm::StringRef value) override
bool SetValueForKey (llvm::StringRef key, const lldb::OptionValueSP &value_sp, bool can_replace=true)
bool DeleteValueForKey (llvm::StringRef key)
size_t GetArgs (Args &args) const
Status SetArgs (const Args &args, VarSetOperationType op)
Public Member Functions inherited from lldb_private::Cloneable< OptionValueDictionary, OptionValue >
std::shared_ptr< typename OptionValue::TopmostBase > Clone () const override
Public Member Functions inherited from lldb_private::OptionValue
OptionValue ()=default
virtual ~OptionValue ()=default
OptionValue (const OptionValue &other)
OptionValue & operator= (const OptionValue &other)
virtual bool ValueIsTransparent () const
virtual const char * GetTypeAsCString () const
virtual lldb::OptionValueSP DeepCopy (const lldb::OptionValueSP &new_parent) const
virtual void AutoComplete (CommandInterpreter &interpreter, CompletionRequest &request)
virtual llvm::StringRef GetName () const
virtual bool DumpQualifiedName (Stream &strm) const
uint32_t GetTypeAsMask ()
OptionValueArch * GetAsArch ()
const OptionValueArch * GetAsArch () const
OptionValueArray * GetAsArray ()
const OptionValueArray * GetAsArray () const
OptionValueArgs * GetAsArgs ()
const OptionValueArgs * GetAsArgs () const
OptionValueBoolean * GetAsBoolean ()
const OptionValueBoolean * GetAsBoolean () const
OptionValueChar * GetAsChar ()
const OptionValueChar * GetAsChar () const
OptionValueDictionary * GetAsDictionary ()
const OptionValueDictionary * GetAsDictionary () const
OptionValueEnumeration * GetAsEnumeration ()
const OptionValueEnumeration * GetAsEnumeration () const
OptionValueFileSpec * GetAsFileSpec ()
const OptionValueFileSpec * GetAsFileSpec () const
OptionValueFileSpecList * GetAsFileSpecList ()
const OptionValueFileSpecList * GetAsFileSpecList () const
OptionValueFormat * GetAsFormat ()
const OptionValueFormat * GetAsFormat () const
OptionValueLanguage * GetAsLanguage ()
const OptionValueLanguage * GetAsLanguage () const
OptionValuePathMappings * GetAsPathMappings ()
const OptionValuePathMappings * GetAsPathMappings () const
OptionValueProperties * GetAsProperties ()
const OptionValueProperties * GetAsProperties () const
OptionValueRegex * GetAsRegex ()
const OptionValueRegex * GetAsRegex () const
OptionValueSInt64 * GetAsSInt64 ()
const OptionValueSInt64 * GetAsSInt64 () const
OptionValueString * GetAsString ()
const OptionValueString * GetAsString () const
OptionValueUInt64 * GetAsUInt64 ()
const OptionValueUInt64 * GetAsUInt64 () const
OptionValueUUID * GetAsUUID ()
const OptionValueUUID * GetAsUUID () const
OptionValueFormatEntity * GetAsFormatEntity ()
const OptionValueFormatEntity * GetAsFormatEntity () const
bool AppendFileSpecValue (FileSpec file_spec)
bool OptionWasSet () const
void SetOptionWasSet ()
void SetParent (const lldb::OptionValueSP &parent_sp)
lldb::OptionValueSP GetParent () const
void SetValueChangedCallback (std::function< void()> callback)
void NotifyValueChanged ()
template<typename T, std::enable_if_t<!std::is_pointer_v< T >, bool > = true>
std::optional< T > GetValueAs () const
template<typename T, typename U = typename std::remove_const< typename std::remove_pointer<T>::type>::type, std::enable_if_t< std::is_pointer_v< T >, bool > = true>
T GetValueAs () const
bool SetValueAs (bool v)
bool SetValueAs (char v)
bool SetValueAs (uint64_t v)
bool SetValueAs (int64_t v)
bool SetValueAs (UUID v)
bool SetValueAs (llvm::StringRef v)
bool SetValueAs (lldb::LanguageType v)
bool SetValueAs (lldb::Format v)
bool SetValueAs (FileSpec v)
bool SetValueAs (ArchSpec v)
bool SetValueAs (const FormatEntity::Entry &v)
template<typename T, std::enable_if_t< std::is_enum_v< T >, bool > = true>
bool SetValueAs (T t)
Protected Attributes
uint32_t m_type_mask
OptionEnumValues m_enum_values
llvm::StringMap< lldb::OptionValueSP > m_values
bool m_raw_value_dump
Protected Attributes inherited from lldb_private::OptionValue
lldb::OptionValueWP m_parent_wp
std::function< void()> m_callback
bool m_value_was_set = false
Additional Inherited Members
Public Types inherited from lldb_private::OptionValue
enum Type {
eTypeInvalid = 0 , eTypeArch , eTypeArgs , eTypeArray ,
eTypeBoolean , eTypeChar , eTypeDictionary , eTypeEnum ,
eTypeFileLineColumn , eTypeFileSpec , eTypeFileSpecList , eTypeFormat ,
eTypeLanguage , eTypePathMap , eTypeProperties , eTypeRegex ,
eTypeSInt64 , eTypeString , eTypeUInt64 , eTypeUUID ,
eTypeFormatEntity
}
enum {
eDumpOptionName = (1u << 0) , eDumpOptionType = (1u << 1) , eDumpOptionValue = (1u << 2) , eDumpOptionDescription = (1u << 3) ,
eDumpOptionRaw = (1u << 4) , eDumpOptionCommand = (1u << 5) , eDumpOptionDefaultValue = (1u << 6) , eDumpGroupValue = (eDumpOptionName | eDumpOptionType | eDumpOptionValue) ,
eDumpGroupHelp , eDumpGroupExport = (eDumpOptionCommand | eDumpOptionName | eDumpOptionValue)
}
Static Public Member Functions inherited from lldb_private::OptionValue
static const char * GetBuiltinTypeAsCString (Type t)
static uint32_t ConvertTypeToMask (OptionValue::Type type)
static OptionValue::Type ConvertTypeMaskToType (uint32_t type_mask)
static lldb::OptionValueSP CreateValueFromCStringForTypeMask (const char *value_cstr, uint32_t type_mask, Status &error)
Protected Types inherited from lldb_private::OptionValue
using TopmostBase = OptionValue
Detailed Description
Definition at line 19 of file OptionValueDictionary.h.
Constructor & Destructor Documentation
OptionValueDictionary()
lldb_private::OptionValueDictionary::OptionValueDictionary (uint32_t type_mask = UINT32_MAX, OptionEnumValues enum_values = OptionEnumValues(), bool raw_value_dump = true) inline
Definition at line 22 of file OptionValueDictionary.h.
References m_enum_values, m_raw_value_dump, m_type_mask, and UINT32_MAX.
Referenced by DeepCopy().
~OptionValueDictionary()
lldb_private::OptionValueDictionary::~OptionValueDictionary () override default
Member Function Documentation
Clear()
void lldb_private::OptionValueDictionary::Clear () inline override virtual
Implements lldb_private::OptionValue.
Definition at line 43 of file OptionValueDictionary.h.
References lldb_private::OptionValue::m_value_was_set, and m_values.
Referenced by SetArgs().
DeepCopy()
OptionValueSP OptionValueDictionary::DeepCopy (const lldb::OptionValueSP & new_parent) const override
Definition at line 348 of file OptionValueDictionary.cpp.
References lldb_private::OptionValue::DeepCopy(), lldbassert, and OptionValueDictionary().
DeleteValueForKey()
bool OptionValueDictionary::DeleteValueForKey (llvm::StringRef key)
Definition at line 338 of file OptionValueDictionary.cpp.
References m_values.
Referenced by SetArgs().
DumpValue()
void OptionValueDictionary::DumpValue (const ExecutionContext * exe_ctx, Stream & strm, uint32_t dump_mask) override virtual
Implements lldb_private::OptionValue.
Definition at line 22 of file OptionValueDictionary.cpp.
References lldb_private::OptionValue::ConvertTypeMaskToType(), lldb_private::OptionValue::DumpValue(), lldb_private::OptionValue::eDumpOptionCommand, lldb_private::OptionValue::eDumpOptionDefaultValue, lldb_private::OptionValue::eDumpOptionRaw, lldb_private::OptionValue::eDumpOptionType, lldb_private::OptionValue::eDumpOptionValue, lldb_private::Stream::EOL(), lldb_private::OptionValue::eTypeArray, lldb_private::OptionValue::eTypeBoolean, lldb_private::OptionValue::eTypeChar, lldb_private::OptionValue::eTypeDictionary, lldb_private::OptionValue::eTypeEnum, lldb_private::OptionValue::eTypeFileLineColumn, lldb_private::OptionValue::eTypeFileSpec, lldb_private::OptionValue::eTypeFileSpecList, lldb_private::OptionValue::eTypeFormat, lldb_private::OptionValue::eTypeInvalid, lldb_private::OptionValue::eTypePathMap, lldb_private::OptionValue::eTypeProperties, lldb_private::OptionValue::eTypeSInt64, lldb_private::OptionValue::eTypeString, lldb_private::OptionValue::eTypeUInt64, lldb_private::OptionValue::eTypeUUID, lldb_private::OptionValue::GetBuiltinTypeAsCString(), lldb_private::OptionValue::GetTypeAsCString(), lldb_private::Stream::Indent(), lldb_private::Stream::IndentLess(), lldb_private::Stream::IndentMore(), m_raw_value_dump, m_type_mask, m_values, lldb_private::Stream::Printf(), lldb_private::Stream::PutChar(), and lldb_private::Stream::PutCString().
GetArgs()
size_t OptionValueDictionary::GetArgs (Args & args) const
Definition at line 105 of file OptionValueDictionary.cpp.
References lldb_private::Args::AppendArgument(), lldb_private::Args::Clear(), lldb_private::OptionValue::eDumpOptionRaw, lldb_private::OptionValue::eDumpOptionValue, lldb_private::Args::GetArgumentCount(), lldb_private::StreamString::GetString(), m_values, and lldb_private::Stream::Printf().
Referenced by lldb_private::OptionValueProperties::GetPropertyAtIndexAsArgs().
GetNumValues()
size_t lldb_private::OptionValueDictionary::GetNumValues () const inline
Definition at line 59 of file OptionValueDictionary.h.
References m_values.
GetSubValue()
lldb::OptionValueSP OptionValueDictionary::GetSubValue (const ExecutionContext * exe_ctx, llvm::StringRef name, Status & error) const override virtual
Reimplemented from lldb_private::OptionValue.
Definition at line 244 of file OptionValueDictionary.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::OptionValue::GetTypeAsCString(), and GetValueForKey().
Referenced by SetSubValue().
GetType()
OptionValue::Type lldb_private::OptionValueDictionary::GetType () const inline override virtual
Implements lldb_private::OptionValue.
Definition at line 32 of file OptionValueDictionary.h.
References lldb_private::OptionValue::eTypeDictionary.
GetValueForKey()
lldb::OptionValueSP OptionValueDictionary::GetValueForKey (llvm::StringRef key) const
Definition at line 313 of file OptionValueDictionary.cpp.
References m_values.
Referenced by GetSubValue(), EmulationStateARM::LoadRegistersStateFromDictionary(), EmulationStateARM::LoadStateFromDictionary(), lldb_private::EmulateInstructionARM::TestEmulation(), and lldb_private::Instruction::TestEmulation().
IsAggregateValue()
bool lldb_private::OptionValueDictionary::IsAggregateValue () const inline override virtual
Reimplemented from lldb_private::OptionValue.
Definition at line 51 of file OptionValueDictionary.h.
IsHomogenous()
bool lldb_private::OptionValueDictionary::IsHomogenous () const inline
Definition at line 53 of file OptionValueDictionary.h.
References lldb_private::OptionValue::ConvertTypeMaskToType(), lldb_private::OptionValue::eTypeInvalid, and m_type_mask.
SetArgs()
Status OptionValueDictionary::SetArgs (const Args & args, VarSetOperationType op)
Definition at line 116 of file OptionValueDictionary.cpp.
References Clear(), lldb_private::OptionValue::CreateValueFromCStringForTypeMask(), DeleteValueForKey(), error(), lldb_private::OptionValue::eTypeEnum, lldb_private::eVarSetOperationAppend, lldb_private::eVarSetOperationAssign, lldb_private::eVarSetOperationClear, lldb_private::eVarSetOperationInsertAfter, lldb_private::eVarSetOperationInsertBefore, lldb_private::eVarSetOperationInvalid, lldb_private::eVarSetOperationRemove, lldb_private::eVarSetOperationReplace, lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::Args::GetArgumentCount(), m_enum_values, m_type_mask, lldb_private::OptionValue::m_value_was_set, SetValueForKey(), and lldb_private::OptionValue::SetValueFromString().
Referenced by lldb_private::OptionValueProperties::SetPropertyAtIndexFromArgs(), and SetValueFromString().
SetSubValue()
Status OptionValueDictionary::SetSubValue (const ExecutionContext * exe_ctx, VarSetOperationType op, llvm::StringRef name, llvm::StringRef value) override virtual
Reimplemented from lldb_private::OptionValue.
Definition at line 296 of file OptionValueDictionary.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormat(), and GetSubValue().
SetValueForKey()
bool OptionValueDictionary::SetValueForKey (llvm::StringRef key, const lldb::OptionValueSP & value_sp, bool can_replace = true)
Definition at line 321 of file OptionValueDictionary.cpp.
References m_type_mask, and m_values.
Referenced by SetArgs().
SetValueFromString()
Status OptionValueDictionary::SetValueFromString (llvm::StringRef value, VarSetOperationType op = eVarSetOperationAssign) override virtual
Reimplemented from lldb_private::OptionValue.
Definition at line 234 of file OptionValueDictionary.cpp.
References error(), lldb_private::OptionValue::NotifyValueChanged(), and SetArgs().
ToJSON()
llvm::json::Value OptionValueDictionary::ToJSON (const ExecutionContext * exe_ctx) const override virtual
Implements lldb_private::OptionValue.
Definition at line 97 of file OptionValueDictionary.cpp.
References m_values.
Member Data Documentation
m_enum_values
OptionEnumValues lldb_private::OptionValueDictionary::m_enum_values protected
Definition at line 81 of file OptionValueDictionary.h.
Referenced by OptionValueDictionary(), and SetArgs().
m_raw_value_dump
bool lldb_private::OptionValueDictionary::m_raw_value_dump protected
Definition at line 83 of file OptionValueDictionary.h.
Referenced by DumpValue(), and OptionValueDictionary().
m_type_mask
uint32_t lldb_private::OptionValueDictionary::m_type_mask protected
Definition at line 80 of file OptionValueDictionary.h.
Referenced by DumpValue(), IsHomogenous(), OptionValueDictionary(), SetArgs(), and SetValueForKey().
m_values
llvm::StringMap<lldb::OptionValueSP> lldb_private::OptionValueDictionary::m_values protected
Definition at line 82 of file OptionValueDictionary.h.
Referenced by Clear(), DeleteValueForKey(), DumpValue(), GetArgs(), GetNumValues(), GetValueForKey(), SetValueForKey(), and ToJSON().
The documentation for this class was generated from the following files:
OptionValueDictionary.h
OptionValueDictionary.cpp