LLDB: InstrumentationRuntimeASanLibsanitizers Class Reference
InstrumentationRuntimeASanLibsanitizers Class Reference
#include <InstrumentationRuntimeASanLibsanitizers.h>
Public Member Functions
~InstrumentationRuntimeASanLibsanitizers () override
llvm::StringRef GetPluginName () override
virtual lldb::InstrumentationRuntimeType GetType ()
Public Member Functions inherited from lldb_private::InstrumentationRuntime
void ModulesDidLoad (lldb_private::ModuleList &module_list)
Look for the instrumentation runtime in module_list.
bool IsActive () const
virtual lldb::ThreadCollectionSP GetBacktracesFromExtendedStopInfo (StructuredData::ObjectSP info)
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static lldb::InstrumentationRuntimeSP CreateInstance (const lldb::ProcessSP &process_sp)
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static lldb::InstrumentationRuntimeType GetTypeStatic ()
Static Public Member Functions inherited from lldb_private::InstrumentationRuntime
static void ModulesDidLoad (lldb_private::ModuleList &module_list, Process *process, InstrumentationRuntimeCollection &runtimes)
Private Member Functions
InstrumentationRuntimeASanLibsanitizers (const lldb::ProcessSP &process_sp)
const lldb_private::RegularExpression & GetPatternForRuntimeLibrary () override
Return a regular expression which can be used to identify a valid version of the runtime library.
bool CheckIfRuntimeIsValid (const lldb::ModuleSP module_sp) override
Check whether module_sp corresponds to a valid runtime library.
void Activate () override
Register a breakpoint in the runtime library and perform any other necessary initialization.
void Deactivate ()
Static Private Member Functions
static bool NotifyBreakpointHit (void *baton, lldb_private::StoppointCallbackContext *context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id)
Additional Inherited Members
Protected Member Functions inherited from lldb_private::InstrumentationRuntime
InstrumentationRuntime (const lldb::ProcessSP &process_sp)
lldb::ProcessSP GetProcessSP ()
lldb::ModuleSP GetRuntimeModuleSP ()
void SetRuntimeModuleSP (lldb::ModuleSP module_sp)
lldb::user_id_t GetBreakpointID () const
void SetBreakpointID (lldb::user_id_t ID)
void SetActive (bool IsActive)
virtual bool MatchAllModules ()
Detailed Description
Definition at line 14 of file InstrumentationRuntimeASanLibsanitizers.h.
Constructor & Destructor Documentation
~InstrumentationRuntimeASanLibsanitizers()
InstrumentationRuntimeASanLibsanitizers::~InstrumentationRuntimeASanLibsanitizers () override
Definition at line 49 of file InstrumentationRuntimeASanLibsanitizers.cpp.
References Deactivate().
InstrumentationRuntimeASanLibsanitizers()
InstrumentationRuntimeASanLibsanitizers::InstrumentationRuntimeASanLibsanitizers (const lldb::ProcessSP & process_sp) inline private
Definition at line 35 of file InstrumentationRuntimeASanLibsanitizers.h.
References lldb_private::InstrumentationRuntime::InstrumentationRuntime().
Referenced by CreateInstance(), and NotifyBreakpointHit().
Member Function Documentation
Activate()
void InstrumentationRuntimeASanLibsanitizers::Activate () override private virtual
Register a breakpoint in the runtime library and perform any other necessary initialization.
The runtime library is guaranteed to be loaded.
Implements lldb_private::InstrumentationRuntime.
Definition at line 85 of file InstrumentationRuntimeASanLibsanitizers.cpp.
References lldb_private::Stoppoint::GetID(), lldb_private::InstrumentationRuntime::GetProcessSP(), lldb_private::InstrumentationRuntime::GetRuntimeModuleSP(), lldb_private::InstrumentationRuntime::IsActive(), NotifyBreakpointHit(), lldb_private::InstrumentationRuntime::SetActive(), lldb_private::InstrumentationRuntime::SetBreakpointID(), lldb_private::Breakpoint::SetBreakpointKind(), lldb_private::Breakpoint::SetCallback(), and lldb_private::ReportRetriever::SetupBreakpoint().
CheckIfRuntimeIsValid()
bool InstrumentationRuntimeASanLibsanitizers::CheckIfRuntimeIsValid (const lldb::ModuleSP module_sp) override private virtual
Check whether module_sp corresponds to a valid runtime library.
Implements lldb_private::InstrumentationRuntime.
Definition at line 61 of file InstrumentationRuntimeASanLibsanitizers.cpp.
References lldb::eSymbolTypeAny.
CreateInstance()
lldb::InstrumentationRuntimeSP InstrumentationRuntimeASanLibsanitizers::CreateInstance (const lldb::ProcessSP & process_sp) static
Definition at line 27 of file InstrumentationRuntimeASanLibsanitizers.cpp.
References InstrumentationRuntimeASanLibsanitizers().
Referenced by Initialize(), and Terminate().
Deactivate()
void InstrumentationRuntimeASanLibsanitizers::Deactivate () private
Definition at line 109 of file InstrumentationRuntimeASanLibsanitizers.cpp.
References lldb_private::InstrumentationRuntime::GetBreakpointID(), lldb_private::InstrumentationRuntime::GetProcessSP(), LLDB_INVALID_BREAK_ID, lldb_private::InstrumentationRuntime::SetActive(), and lldb_private::InstrumentationRuntime::SetBreakpointID().
Referenced by ~InstrumentationRuntimeASanLibsanitizers().
GetPatternForRuntimeLibrary()
const RegularExpression & InstrumentationRuntimeASanLibsanitizers::GetPatternForRuntimeLibrary () override private virtual
Return a regular expression which can be used to identify a valid version of the runtime library.
Implements lldb_private::InstrumentationRuntime.
Definition at line 55 of file InstrumentationRuntimeASanLibsanitizers.cpp.
GetPluginName()
llvm::StringRef InstrumentationRuntimeASanLibsanitizers::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 30 of file InstrumentationRuntimeASanLibsanitizers.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef InstrumentationRuntimeASanLibsanitizers::GetPluginNameStatic () inline static
Definition at line 26 of file InstrumentationRuntimeASanLibsanitizers.h.
Referenced by GetPluginName(), and Initialize().
GetType()
virtual lldb::InstrumentationRuntimeType InstrumentationRuntimeASanLibsanitizers::GetType () inline virtual
Definition at line 32 of file InstrumentationRuntimeASanLibsanitizers.h.
References GetTypeStatic().
GetTypeStatic()
lldb::InstrumentationRuntimeType InstrumentationRuntimeASanLibsanitizers::GetTypeStatic () static
Definition at line 45 of file InstrumentationRuntimeASanLibsanitizers.cpp.
References lldb::eInstrumentationRuntimeTypeLibsanitizersAsan.
Referenced by GetType(), and Initialize().
Initialize()
void InstrumentationRuntimeASanLibsanitizers::Initialize () static
Definition at line 33 of file InstrumentationRuntimeASanLibsanitizers.cpp.
References CreateInstance(), GetPluginNameStatic(), GetTypeStatic(), and lldb_private::PluginManager::RegisterPlugin().
NotifyBreakpointHit()
bool InstrumentationRuntimeASanLibsanitizers::NotifyBreakpointHit (void * baton, lldb_private::StoppointCallbackContext * context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id) static private
Definition at line 69 of file InstrumentationRuntimeASanLibsanitizers.cpp.
References lldb_private::InstrumentationRuntime::GetProcessSP(), InstrumentationRuntimeASanLibsanitizers(), and lldb_private::ReportRetriever::NotifyBreakpointHit().
Referenced by Activate().
Terminate()
void InstrumentationRuntimeASanLibsanitizers::Terminate () static
Definition at line 40 of file InstrumentationRuntimeASanLibsanitizers.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
The documentation for this class was generated from the following files:
InstrumentationRuntimeASanLibsanitizers.h
InstrumentationRuntimeASanLibsanitizers.cpp