LLDB: lldb_private::postfix::InitialValueNode Class Reference
lldb_private::postfix::InitialValueNode Class Reference
A node representing the canonical frame address.
#include <PostfixExpression.h>
Public Member Functions
InitialValueNode ()
Public Member Functions inherited from lldb_private::postfix::Node
Kind GetKind () const
Static Public Member Functions
static bool classof (const Node *node)
Additional Inherited Members
Public Types inherited from lldb_private::postfix::Node
enum Kind {
BinaryOp , InitialValue , Integer , Register ,
Symbol , UnaryOp
}
Protected Member Functions inherited from lldb_private::postfix::Node
Node (Kind kind)
Detailed Description
A node representing the canonical frame address.
Definition at line 79 of file PostfixExpression.h.
Constructor & Destructor Documentation
InitialValueNode()
lldb_private::postfix::InitialValueNode::InitialValueNode () inline
Definition at line 81 of file PostfixExpression.h.
References lldb_private::postfix::Node::InitialValue, and lldb_private::postfix::Node::Node().
Member Function Documentation
classof()
bool lldb_private::postfix::InitialValueNode::classof (const Node * node) inline static
Definition at line 83 of file PostfixExpression.h.
References lldb_private::postfix::Node::GetKind(), lldb_private::postfix::Node::InitialValue, and lldb_private::postfix::Node::Node().
The documentation for this class was generated from the following file:
PostfixExpression.h