LLDB: lldb_private::TargetProperties Class Reference
lldb_private::TargetProperties Class Reference
#include <Target.h>
Public Member Functions
TargetProperties (Target *target)
~TargetProperties () override
ArchSpec GetDefaultArchitecture () const
void SetDefaultArchitecture (const ArchSpec &arch)
bool GetMoveToNearestCode () const
lldb::DynamicValueType GetPreferDynamicValue () const
bool SetPreferDynamicValue (lldb::DynamicValueType d)
bool GetPreloadSymbols () const
void SetPreloadSymbols (bool b)
bool GetDisableASLR () const
void SetDisableASLR (bool b)
bool GetInheritTCC () const
void SetInheritTCC (bool b)
bool GetDetachOnError () const
void SetDetachOnError (bool b)
bool GetDisableSTDIO () const
void SetDisableSTDIO (bool b)
llvm::StringRef GetLaunchWorkingDirectory () const
bool GetParallelModuleLoad () const
const char * GetDisassemblyFlavor () const
const char * GetDisassemblyCPU () const
const char * GetDisassemblyFeatures () const
InlineStrategy GetInlineStrategy () const
RealpathPrefixes GetSourceRealpathPrefixes () const
llvm::StringRef GetArg0 () const
void SetArg0 (llvm::StringRef arg)
bool GetRunArguments (Args &args) const
void SetRunArguments (const Args &args)
Environment GetEnvironment () const
Environment GetInheritedEnvironment () const
Environment GetTargetEnvironment () const
void SetEnvironment (Environment env)
bool GetSkipPrologue () const
PathMappingList & GetSourcePathMap () const
PathMappingList & GetObjectPathMap () const
bool GetAutoSourceMapRelative () const
FileSpecList GetExecutableSearchPaths ()
void AppendExecutableSearchPaths (const FileSpec &)
FileSpecList GetDebugFileSearchPaths ()
FileSpecList GetClangModuleSearchPaths ()
bool GetEnableAutoImportClangModules () const
ImportStdModule GetImportStdModule () const
DynamicClassInfoHelper GetDynamicClassInfoHelper () const
bool GetEnableAutoApplyFixIts () const
uint64_t GetNumberOfRetriesWithFixits () const
bool GetEnableNotifyAboutFixIts () const
FileSpec GetSaveJITObjectsDir () const
bool GetEnableSyntheticValue () const
bool ShowHexVariableValuesWithLeadingZeroes () const
uint32_t GetMaxZeroPaddingInFloatFormat () const
uint32_t GetMaximumNumberOfChildrenToDisplay () const
std::pair< uint32_t, bool > GetMaximumDepthOfChildrenToDisplay () const
Get the max depth value, augmented with a bool to indicate whether the depth is the default.
uint32_t GetMaximumSizeOfStringSummary () const
uint32_t GetMaximumMemReadSize () const
FileSpec GetStandardInputPath () const
FileSpec GetStandardErrorPath () const
FileSpec GetStandardOutputPath () const
void SetStandardInputPath (llvm::StringRef path)
void SetStandardOutputPath (llvm::StringRef path)
void SetStandardErrorPath (llvm::StringRef path)
void SetStandardInputPath (const char *path)=delete
void SetStandardOutputPath (const char *path)=delete
void SetStandardErrorPath (const char *path)=delete
bool GetBreakpointsConsultPlatformAvoidList ()
SourceLanguage GetLanguage () const
llvm::StringRef GetExpressionPrefixContents ()
uint64_t GetExprErrorLimit () const
uint64_t GetExprAllocAddress () const
uint64_t GetExprAllocSize () const
uint64_t GetExprAllocAlign () const
bool GetUseHexImmediates () const
bool GetUseFastStepping () const
bool GetDisplayExpressionsInCrashlogs () const
LoadScriptFromSymFile GetLoadScriptFromSymbolFile () const
LoadCWDlldbinitFile GetLoadCWDlldbinitFile () const
Disassembler::HexImmediateStyle GetHexImmediateStyle () const
MemoryModuleLoadLevel GetMemoryModuleLoadLevel () const
bool GetUserSpecifiedTrapHandlerNames (Args &args) const
void SetUserSpecifiedTrapHandlerNames (const Args &args)
bool GetDisplayRuntimeSupportValues () const
void SetDisplayRuntimeSupportValues (bool b)
bool GetDisplayRecognizedArguments () const
void SetDisplayRecognizedArguments (bool b)
const ProcessLaunchInfo & GetProcessLaunchInfo () const
void SetProcessLaunchInfo (const ProcessLaunchInfo &launch_info)
bool GetInjectLocalVariables (ExecutionContext *exe_ctx) const
bool GetUseDIL (ExecutionContext *exe_ctx) const
void SetUseDIL (ExecutionContext *exe_ctx, bool b)
void SetRequireHardwareBreakpoints (bool b)
bool GetRequireHardwareBreakpoints () const
bool GetAutoInstallMainExecutable () const
void UpdateLaunchInfoFromProperties ()
void SetDebugUtilityExpression (bool debug)
bool GetDebugUtilityExpression () const
Public Member Functions inherited from lldb_private::Properties
Properties ()
Properties (const lldb::OptionValuePropertiesSP &collection_sp)
virtual ~Properties ()
lldb::OptionValuePropertiesSP GetValueProperties () const
virtual lldb::OptionValueSP GetPropertyValue (const ExecutionContext *exe_ctx, llvm::StringRef property_path, Status &error) const
virtual Status SetPropertyValue (const ExecutionContext *exe_ctx, VarSetOperationType op, llvm::StringRef property_path, llvm::StringRef value)
virtual Status DumpPropertyValue (const ExecutionContext *exe_ctx, Stream &strm, llvm::StringRef property_path, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllPropertyValues (const ExecutionContext *exe_ctx, Stream &strm, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllDescriptions (CommandInterpreter &interpreter, Stream &strm) const
size_t Apropos (llvm::StringRef keyword, std::vector< const Property * > &matching_properties) const
template<typename T>
T GetPropertyAtIndexAs (uint32_t idx, T default_value, const ExecutionContext *exe_ctx=nullptr) const
template<typename T, typename U = typename std::remove_pointer<T>::type, std::enable_if_t< std::is_pointer_v< T >, bool > = true>
const U * GetPropertyAtIndexAs (uint32_t idx, const ExecutionContext *exe_ctx=nullptr) const
template<typename T>
bool SetPropertyAtIndex (uint32_t idx, T t, const ExecutionContext *exe_ctx=nullptr) const
Private Member Functions
std::optional< bool > GetExperimentalPropertyValue (size_t prop_idx, ExecutionContext *exe_ctx=nullptr) const
void Arg0ValueChangedCallback ()
void RunArgsValueChangedCallback ()
void EnvVarsValueChangedCallback ()
void InputPathValueChangedCallback ()
void OutputPathValueChangedCallback ()
void ErrorPathValueChangedCallback ()
void DetachOnErrorValueChangedCallback ()
void DisableASLRValueChangedCallback ()
void InheritTCCValueChangedCallback ()
void DisableSTDIOValueChangedCallback ()
void CheckJITObjectsDir ()
Environment ComputeEnvironment () const
Private Attributes
ProcessLaunchInfo m_launch_info
std::unique_ptr< TargetExperimentalProperties > m_experimental_properties_up
Target * m_target
Additional Inherited Members
Static Public Member Functions inherited from lldb_private::Properties
static llvm::StringRef GetExperimentalSettingsName ()
static bool IsSettingExperimental (llvm::StringRef setting)
Protected Attributes inherited from lldb_private::Properties
lldb::OptionValuePropertiesSP m_collection_sp
Detailed Description
Definition at line 86 of file Target.h.
Constructor & Destructor Documentation
TargetProperties()
TargetProperties::TargetProperties (Target * target)
Definition at line 4467 of file Target.cpp.
References Arg0ValueChangedCallback(), CheckJITObjectsDir(), lldb_private::OptionValueProperties::CreateLocalCopy(), DetachOnErrorValueChangedCallback(), DisableASLRValueChangedCallback(), DisableSTDIOValueChangedCallback(), EnvVarsValueChangedCallback(), ErrorPathValueChangedCallback(), lldb_private::Properties::GetExperimentalSettingsName(), lldb_private::Process::GetGlobalProperties(), lldb_private::Target::GetGlobalProperties(), lldb_private::Properties::GetValueProperties(), InheritTCCValueChangedCallback(), InputPathValueChangedCallback(), lldb_private::Properties::m_collection_sp, m_experimental_properties_up, m_launch_info, m_target, OutputPathValueChangedCallback(), lldb_private::Properties::Properties(), and RunArgsValueChangedCallback().
Referenced by lldb_private::Target::GetGlobalProperties(), and lldb_private::Target::Target().
~TargetProperties()
TargetProperties::~TargetProperties () override default
Member Function Documentation
AppendExecutableSearchPaths()
void TargetProperties::AppendExecutableSearchPaths (const FileSpec & dir)
Definition at line 4848 of file Target.cpp.
References lldb_private::OptionValueFileSpecList::AppendCurrentValue(), and lldb_private::Properties::m_collection_sp.
Arg0ValueChangedCallback()
void TargetProperties::Arg0ValueChangedCallback () private
Definition at line 5198 of file Target.cpp.
References GetArg0(), and m_launch_info.
Referenced by TargetProperties(), and UpdateLaunchInfoFromProperties().
CheckJITObjectsDir()
void TargetProperties::CheckJITObjectsDir () private
Definition at line 4914 of file Target.cpp.
References lldb_private::FileSystem::Exists(), lldb_private::FileSpec::GetPath(), GetSaveJITObjectsDir(), lldb_private::FileSystem::Instance(), lldb_private::FileSystem::IsDirectory(), lldb_private::Properties::m_collection_sp, m_target, and lldb_private::Debugger::ReportError().
Referenced by TargetProperties().
ComputeEnvironment()
Environment TargetProperties::ComputeEnvironment () const private
Definition at line 4743 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs(), lldb_private::Properties::m_collection_sp, and m_target.
Referenced by EnvVarsValueChangedCallback(), and GetEnvironment().
DetachOnErrorValueChangedCallback()
void TargetProperties::DetachOnErrorValueChangedCallback () private
Definition at line 5227 of file Target.cpp.
References GetDetachOnError(), and m_launch_info.
Referenced by TargetProperties(), and UpdateLaunchInfoFromProperties().
DisableASLRValueChangedCallback()
void TargetProperties::DisableASLRValueChangedCallback () private
Definition at line 5234 of file Target.cpp.
References GetDisableASLR(), and m_launch_info.
Referenced by TargetProperties(), and UpdateLaunchInfoFromProperties().
DisableSTDIOValueChangedCallback()
void TargetProperties::DisableSTDIOValueChangedCallback () private
Definition at line 5248 of file Target.cpp.
References GetDisableSTDIO(), and m_launch_info.
Referenced by TargetProperties(), and UpdateLaunchInfoFromProperties().
EnvVarsValueChangedCallback()
void TargetProperties::EnvVarsValueChangedCallback () private
Definition at line 5208 of file Target.cpp.
References ComputeEnvironment(), and m_launch_info.
Referenced by TargetProperties(), and UpdateLaunchInfoFromProperties().
ErrorPathValueChangedCallback()
void TargetProperties::ErrorPathValueChangedCallback () private
Definition at line 5222 of file Target.cpp.
References GetStandardErrorPath(), and m_launch_info.
Referenced by TargetProperties(), and UpdateLaunchInfoFromProperties().
GetArg0()
llvm::StringRef TargetProperties::GetArg0 () const
Definition at line 4720 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by Arg0ValueChangedCallback(), and CommandObjectProcessLaunch::DoExecute().
GetAutoInstallMainExecutable()
bool TargetProperties::GetAutoInstallMainExecutable () const
Definition at line 5192 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetAutoSourceMapRelative()
bool TargetProperties::GetAutoSourceMapRelative () const
Definition at line 4842 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::BreakpointResolverFileLine::DeduceSourceMapping().
GetBreakpointsConsultPlatformAvoidList()
bool TargetProperties::GetBreakpointsConsultPlatformAvoidList ()
Definition at line 5065 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Target::ModuleIsExcludedForUnconstrainedSearches(), and lldb_private::Target::ModuleIsExcludedForUnconstrainedSearches().
GetClangModuleSearchPaths()
FileSpecList TargetProperties::GetClangModuleSearchPaths ()
Definition at line 4866 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::ClangModulesDeclVendor::Create().
GetDebugFileSearchPaths()
FileSpecList TargetProperties::GetDebugFileSearchPaths ()
Definition at line 4861 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Target::GetDefaultDebugFileSearchPaths().
GetDebugUtilityExpression()
bool TargetProperties::GetDebugUtilityExpression () const
Definition at line 5255 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::FunctionCaller::ExecuteFunction().
GetDefaultArchitecture()
ArchSpec TargetProperties::GetDefaultArchitecture () const
Definition at line 4581 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Target::GetDefaultArchitecture().
GetDetachOnError()
bool TargetProperties::GetDetachOnError () const
Definition at line 4646 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by DetachOnErrorValueChangedCallback(), and CommandObjectProcessLaunch::DoExecute().
GetDisableASLR()
bool TargetProperties::GetDisableASLR () const
Definition at line 4624 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by DisableASLRValueChangedCallback(), and CommandObjectProcessLaunch::DoExecute().
GetDisableSTDIO()
bool TargetProperties::GetDisableSTDIO () const
Definition at line 4657 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by DisableSTDIOValueChangedCallback(), and CommandObjectProcessLaunch::DoExecute().
GetDisassemblyCPU()
const char * TargetProperties::GetDisassemblyCPU () const
Definition at line 4692 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Disassembler::FindPluginForTarget(), lldb_private::StackFrame::GetStatus(), lldb_private::CommandObjectDisassemble::CommandOptions::OptionParsingStarting(), and lldb_private::Target::ReadInstructions().
GetDisassemblyFeatures()
const char * TargetProperties::GetDisassemblyFeatures () const
Definition at line 4699 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Disassembler::FindPluginForTarget(), lldb_private::StackFrame::GetStatus(), lldb_private::CommandObjectDisassemble::CommandOptions::OptionParsingStarting(), and lldb_private::Target::ReadInstructions().
GetDisassemblyFlavor()
const char * TargetProperties::GetDisassemblyFlavor () const
Definition at line 4679 of file Target.cpp.
References g_x86_dis_flavor_value_types, and lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Disassembler::FindPluginForTarget(), lldb_private::CommandObjectDisassemble::CommandOptions::OptionParsingStarting(), and lldb_private::Target::ReadInstructions().
GetDisplayExpressionsInCrashlogs()
bool TargetProperties::GetDisplayExpressionsInCrashlogs () const
Definition at line 5083 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb::SBFrame::EvaluateExpression().
GetDisplayRecognizedArguments()
bool TargetProperties::GetDisplayRecognizedArguments () const
Definition at line 5138 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetDisplayRuntimeSupportValues()
bool TargetProperties::GetDisplayRuntimeSupportValues () const
Definition at line 5127 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb::SBFrame::GetVariables(), and lldb::SBFrame::GetVariables().
GetDynamicClassInfoHelper()
DynamicClassInfoHelper TargetProperties::GetDynamicClassInfoHelper () const
Definition at line 4884 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetEnableAutoApplyFixIts()
bool TargetProperties::GetEnableAutoApplyFixIts () const
Definition at line 4891 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::CommandObjectExpression::CommandOptions::GetEvaluateExpressionOptions().
GetEnableAutoImportClangModules()
bool TargetProperties::GetEnableAutoImportClangModules () const
Definition at line 4871 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::ClangExpressionSourceCode::GetText(), and SetupDeclVendor().
GetEnableNotifyAboutFixIts()
bool TargetProperties::GetEnableNotifyAboutFixIts () const
Definition at line 4903 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::CommandObjectDWIMPrint::DoExecute(), and lldb_private::UserExpression::Evaluate().
GetEnableSyntheticValue()
bool TargetProperties::GetEnableSyntheticValue () const
Definition at line 4947 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetEnvironment()
Environment TargetProperties::GetEnvironment () const
Definition at line 4771 of file Target.cpp.
References ComputeEnvironment().
Referenced by CommandObjectProcessLaunch::DoExecute(), and CommandObjectTargetShowLaunchEnvironment::DoExecute().
GetExecutableSearchPaths()
FileSpecList TargetProperties::GetExecutableSearchPaths ()
Definition at line 4856 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Target::GetDefaultExecutableSearchPaths(), and lldb_private::Target::GetOrCreateModule().
GetExperimentalPropertyValue()
std::optional< bool > TargetProperties::GetExperimentalPropertyValue (size_t prop_idx, ExecutionContext * exe_ctx = nullptr) const private
Definition at line 4543 of file Target.cpp.
References ePropertyExperimental, lldb_private::OptionValueProperties::GetPropertyAtIndexAs(), lldb_private::Property::GetValue(), and lldb_private::Properties::m_collection_sp.
Referenced by GetInjectLocalVariables().
GetExprAllocAddress()
uint64_t TargetProperties::GetExprAllocAddress () const
Definition at line 5047 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetExprAllocAlign()
uint64_t TargetProperties::GetExprAllocAlign () const
Definition at line 5059 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetExprAllocSize()
uint64_t TargetProperties::GetExprAllocSize () const
Definition at line 5053 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetExprErrorLimit()
uint64_t TargetProperties::GetExprErrorLimit () const
Definition at line 5041 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetExpressionPrefixContents()
llvm::StringRef TargetProperties::GetExpressionPrefixContents ()
Definition at line 5027 of file Target.cpp.
References lldb_private::OptionValueFileSpec::GetFileContents(), and lldb_private::Properties::m_collection_sp.
Referenced by lldb_private::Target::EvaluateExpression().
GetHexImmediateStyle()
Disassembler::HexImmediateStyle TargetProperties::GetHexImmediateStyle () const
Definition at line 5103 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by InstructionLLVMC::CalculateMnemonicOperandsAndComment().
GetImportStdModule()
ImportStdModule TargetProperties::GetImportStdModule () const
Definition at line 4877 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by shouldRetryWithCppModule().
GetInheritedEnvironment()
Environment TargetProperties::GetInheritedEnvironment () const
Definition at line 4775 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs(), lldb_private::Properties::m_collection_sp, and m_target.
GetInheritTCC()
bool TargetProperties::GetInheritTCC () const
Definition at line 4635 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by CommandObjectProcessLaunch::DoExecute(), and InheritTCCValueChangedCallback().
GetInjectLocalVariables()
bool TargetProperties::GetInjectLocalVariables (ExecutionContext * exe_ctx) const
Definition at line 4554 of file Target.cpp.
References GetExperimentalPropertyValue().
Referenced by lldb_private::ClangExpressionSourceCode::GetText().
GetInlineStrategy()
InlineStrategy TargetProperties::GetInlineStrategy () const
Definition at line 4706 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Target::CreateBreakpoint(), and CommandObjectSourceList::DoExecute().
GetLanguage()
SourceLanguage TargetProperties::GetLanguage () const
Definition at line 5022 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::UserExpression::Evaluate(), lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::EvaluateExpression(), and lldb::SBFrame::EvaluateExpression().
GetLaunchWorkingDirectory()
llvm::StringRef TargetProperties::GetLaunchWorkingDirectory () const
Definition at line 4667 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by CommandObjectProcessLaunch::DoExecute().
GetLoadCWDlldbinitFile()
LoadCWDlldbinitFile TargetProperties::GetLoadCWDlldbinitFile () const
Definition at line 5096 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::CommandInterpreter::SourceInitFileCwd().
GetLoadScriptFromSymbolFile()
LoadScriptFromSymFile TargetProperties::GetLoadScriptFromSymbolFile () const
Definition at line 5089 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetMaximumDepthOfChildrenToDisplay()
std::pair< uint32_t, bool > TargetProperties::GetMaximumDepthOfChildrenToDisplay () const
Get the max depth value, augmented with a bool to indicate whether the depth is the default.
When the user has customized the max depth, the bool will be false.
Returns
the max depth, and true if the max depth is the system default, otherwise false.
Definition at line 4972 of file Target.cpp.
References lldb_private::Properties::m_collection_sp.
GetMaximumMemReadSize()
uint32_t TargetProperties::GetMaximumMemReadSize () const
Definition at line 4986 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by CommandObjectMemoryRead::DoExecute().
GetMaximumNumberOfChildrenToDisplay()
uint32_t TargetProperties::GetMaximumNumberOfChildrenToDisplay () const
Definition at line 4965 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetMaximumSizeOfStringSummary()
uint32_t TargetProperties::GetMaximumSizeOfStringSummary () const
Definition at line 4980 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by CommandObjectMemoryRead::DoExecute(), and lldb_private::ValueObject::ReadPointedString().
GetMaxZeroPaddingInFloatFormat()
uint32_t TargetProperties::GetMaxZeroPaddingInFloatFormat () const
Definition at line 4959 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetMemoryModuleLoadLevel()
MemoryModuleLoadLevel TargetProperties::GetMemoryModuleLoadLevel () const
Definition at line 5110 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by ObjectFileMachO::ParseSymtab().
GetMoveToNearestCode()
bool TargetProperties::GetMoveToNearestCode () const
Definition at line 4591 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Target::CreateBreakpoint(), and lldb_private::Target::CreateSourceRegexBreakpoint().
GetNumberOfRetriesWithFixits()
uint64_t TargetProperties::GetNumberOfRetriesWithFixits () const
Definition at line 4897 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::CommandObjectExpression::CommandOptions::GetEvaluateExpressionOptions().
GetObjectPathMap()
PathMappingList & TargetProperties::GetObjectPathMap () const
Definition at line 4834 of file Target.cpp.
References lldb_private::OptionValuePathMappings::GetCurrentValue(), and lldb_private::Properties::m_collection_sp.
Referenced by lldb_private::Target::GetOrCreateModule().
GetParallelModuleLoad()
bool TargetProperties::GetParallelModuleLoad () const
Definition at line 4673 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Target::ModulesDidLoad().
GetPreferDynamicValue()
lldb::DynamicValueType TargetProperties::GetPreferDynamicValue () const
Definition at line 4597 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Process::UpdateThreadListIfNeeded().
GetPreloadSymbols()
bool TargetProperties::GetPreloadSymbols () const
Definition at line 4609 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs(), INTERRUPT_REQUESTED, and m_target.
Referenced by lldb_private::Target::ModulesDidLoad().
GetProcessLaunchInfo()
const ProcessLaunchInfo & TargetProperties::GetProcessLaunchInfo () const
Definition at line 5149 of file Target.cpp.
References m_launch_info.
Referenced by CommandObjectProcessLaunch::DoExecute(), lldb_private::ScriptedProcess::DoLoadCore(), and lldb_private::Target::SaveScriptedLaunchInfo().
GetRequireHardwareBreakpoints()
bool TargetProperties::GetRequireHardwareBreakpoints () const
Definition at line 5181 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Target::CreateBreakpoint().
GetRunArguments()
bool TargetProperties::GetRunArguments (Args & args) const
Definition at line 4732 of file Target.cpp.
References lldb_private::Properties::m_collection_sp.
Referenced by CommandObjectPlatformProcessLaunch::DoExecute(), and RunArgsValueChangedCallback().
GetSaveJITObjectsDir()
FileSpec TargetProperties::GetSaveJITObjectsDir () const
Definition at line 4909 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by CheckJITObjectsDir().
GetSkipPrologue()
bool TargetProperties::GetSkipPrologue () const
Definition at line 4820 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Target::CreateBreakpoint(), and lldb_private::Target::CreateFuncRegexBreakpoint().
GetSourcePathMap()
PathMappingList & TargetProperties::GetSourcePathMap () const
Definition at line 4826 of file Target.cpp.
References lldb_private::OptionValuePathMappings::GetCurrentValue(), and lldb_private::Properties::m_collection_sp.
Referenced by lldb_private::Target::CreateBreakpoint(), and lldb_private::BreakpointResolverFileLine::DeduceSourceMapping().
GetSourceRealpathPrefixes()
RealpathPrefixes TargetProperties::GetSourceRealpathPrefixes () const
Definition at line 4715 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::BreakpointResolverFileLine::SearchCallback().
GetStandardErrorPath()
FileSpec TargetProperties::GetStandardErrorPath () const
Definition at line 5012 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by ErrorPathValueChangedCallback(), and lldb_private::Target::FinalizeFileActions().
GetStandardInputPath()
FileSpec TargetProperties::GetStandardInputPath () const
Definition at line 4992 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Target::FinalizeFileActions(), and InputPathValueChangedCallback().
GetStandardOutputPath()
FileSpec TargetProperties::GetStandardOutputPath () const
Definition at line 5002 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Target::FinalizeFileActions(), and OutputPathValueChangedCallback().
GetTargetEnvironment()
Environment TargetProperties::GetTargetEnvironment () const
Definition at line 4803 of file Target.cpp.
References lldb_private::Properties::m_collection_sp.
GetUseDIL()
bool TargetProperties::GetUseDIL (ExecutionContext * exe_ctx) const
Definition at line 4560 of file Target.cpp.
References ePropertyExperimental, lldb_private::OptionValueProperties::GetPropertyAtIndexAs(), lldb_private::Property::GetValue(), and lldb_private::Properties::m_collection_sp.
Referenced by lldb_private::StackFrame::GetValueForVariableExpressionPath().
GetUseFastStepping()
bool TargetProperties::GetUseFastStepping () const
Definition at line 5077 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Process::AdvanceAddressToNextBranchInstruction(), and lldb_private::ThreadPlanStepRange::ThreadPlanStepRange().
GetUseHexImmediates()
bool TargetProperties::GetUseHexImmediates () const
Definition at line 5071 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by InstructionLLVMC::CalculateMnemonicOperandsAndComment().
GetUserSpecifiedTrapHandlerNames()
bool TargetProperties::GetUserSpecifiedTrapHandlerNames (Args & args) const
Definition at line 5117 of file Target.cpp.
References lldb_private::Properties::m_collection_sp.
Referenced by CommandObjectTargetModulesShowUnwind::DoExecute().
InheritTCCValueChangedCallback()
void TargetProperties::InheritTCCValueChangedCallback () private
Definition at line 5241 of file Target.cpp.
References GetInheritTCC(), and m_launch_info.
Referenced by TargetProperties(), and UpdateLaunchInfoFromProperties().
InputPathValueChangedCallback()
void TargetProperties::InputPathValueChangedCallback () private
Definition at line 5212 of file Target.cpp.
References GetStandardInputPath(), and m_launch_info.
Referenced by TargetProperties(), and UpdateLaunchInfoFromProperties().
OutputPathValueChangedCallback()
void TargetProperties::OutputPathValueChangedCallback () private
Definition at line 5217 of file Target.cpp.
References GetStandardOutputPath(), and m_launch_info.
Referenced by TargetProperties(), and UpdateLaunchInfoFromProperties().
RunArgsValueChangedCallback()
void TargetProperties::RunArgsValueChangedCallback () private
Definition at line 5202 of file Target.cpp.
References GetRunArguments(), and m_launch_info.
Referenced by TargetProperties(), and UpdateLaunchInfoFromProperties().
SetArg0()
void TargetProperties::SetArg0 (llvm::StringRef arg)
Definition at line 4726 of file Target.cpp.
References m_launch_info, and lldb_private::Properties::SetPropertyAtIndex().
Referenced by SetProcessLaunchInfo().
SetDebugUtilityExpression()
void TargetProperties::SetDebugUtilityExpression (bool debug)
Definition at line 5261 of file Target.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
SetDefaultArchitecture()
void TargetProperties::SetDefaultArchitecture (const ArchSpec & arch)
Definition at line 4586 of file Target.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
Referenced by lldb_private::Target::SetDefaultArchitecture().
SetDetachOnError()
void TargetProperties::SetDetachOnError (bool b)
Definition at line 4652 of file Target.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
Referenced by SetProcessLaunchInfo().
SetDisableASLR()
void TargetProperties::SetDisableASLR (bool b)
Definition at line 4630 of file Target.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
Referenced by SetProcessLaunchInfo().
SetDisableSTDIO()
void TargetProperties::SetDisableSTDIO (bool b)
Definition at line 4663 of file Target.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
Referenced by SetProcessLaunchInfo().
SetDisplayRecognizedArguments()
void TargetProperties::SetDisplayRecognizedArguments (bool b)
Definition at line 5144 of file Target.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
SetDisplayRuntimeSupportValues()
void TargetProperties::SetDisplayRuntimeSupportValues (bool b)
Definition at line 5133 of file Target.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
SetEnvironment()
void TargetProperties::SetEnvironment (Environment env)
Definition at line 4814 of file Target.cpp.
References lldb_private::Properties::m_collection_sp.
Referenced by SetProcessLaunchInfo().
SetInheritTCC()
void TargetProperties::SetInheritTCC (bool b)
Definition at line 4641 of file Target.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
Referenced by SetProcessLaunchInfo().
SetPreferDynamicValue()
bool TargetProperties::SetPreferDynamicValue (lldb::DynamicValueType d)
Definition at line 4604 of file Target.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
Referenced by lldb_private::Process::UpdateThreadListIfNeeded().
SetPreloadSymbols()
void TargetProperties::SetPreloadSymbols (bool b)
Definition at line 4619 of file Target.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
SetProcessLaunchInfo()
void TargetProperties::SetProcessLaunchInfo (const ProcessLaunchInfo & launch_info)
Definition at line 5153 of file Target.cpp.
References lldb_private::ProcessInfo::GetArg0(), lldb_private::ProcessInfo::GetArguments(), lldb_private::ProcessInfo::GetEnvironment(), lldb_private::ProcessLaunchInfo::GetFileActionForFD(), lldb_private::FileAction::GetFileSpec(), lldb_private::ProcessLaunchInfo::GetFlags(), lldb_private::FileSpec::GetPath(), m_launch_info, SetArg0(), SetDetachOnError(), SetDisableASLR(), SetDisableSTDIO(), SetEnvironment(), SetInheritTCC(), SetRunArguments(), SetStandardErrorPath(), SetStandardInputPath(), SetStandardOutputPath(), and lldb_private::Flags::Test().
Referenced by CommandObjectPlatformProcessLaunch::DoExecute(), CommandObjectProcessLaunch::DoExecute(), and lldb_private::Target::SaveScriptedLaunchInfo().
SetRequireHardwareBreakpoints()
void TargetProperties::SetRequireHardwareBreakpoints (bool b)
Definition at line 5187 of file Target.cpp.
References lldb_private::Properties::m_collection_sp.
SetRunArguments()
void TargetProperties::SetRunArguments (const Args & args)
Definition at line 4737 of file Target.cpp.
References lldb_private::Properties::m_collection_sp, and m_launch_info.
Referenced by CommandObjectProcessLaunch::DoExecute(), and SetProcessLaunchInfo().
SetStandardErrorPath() [1/2]
void lldb_private::TargetProperties::SetStandardErrorPath (const char * path) delete
SetStandardErrorPath() [2/2]
void TargetProperties::SetStandardErrorPath (llvm::StringRef path)
Definition at line 5017 of file Target.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
Referenced by SetProcessLaunchInfo().
SetStandardInputPath() [1/2]
void lldb_private::TargetProperties::SetStandardInputPath (const char * path) delete
SetStandardInputPath() [2/2]
void TargetProperties::SetStandardInputPath (llvm::StringRef path)
Definition at line 4997 of file Target.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
Referenced by SetProcessLaunchInfo().
SetStandardOutputPath() [1/2]
void lldb_private::TargetProperties::SetStandardOutputPath (const char * path) delete
SetStandardOutputPath() [2/2]
void TargetProperties::SetStandardOutputPath (llvm::StringRef path)
Definition at line 5007 of file Target.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
Referenced by SetProcessLaunchInfo().
SetUseDIL()
void TargetProperties::SetUseDIL (ExecutionContext * exe_ctx, bool b)
Definition at line 4572 of file Target.cpp.
References ePropertyExperimental, lldb_private::Property::GetValue(), lldb_private::Properties::m_collection_sp, and lldb_private::OptionValueProperties::SetPropertyAtIndex().
SetUserSpecifiedTrapHandlerNames()
void TargetProperties::SetUserSpecifiedTrapHandlerNames (const Args & args)
Definition at line 5122 of file Target.cpp.
References lldb_private::Properties::m_collection_sp.
ShowHexVariableValuesWithLeadingZeroes()
bool TargetProperties::ShowHexVariableValuesWithLeadingZeroes () const
Definition at line 4953 of file Target.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
UpdateLaunchInfoFromProperties()
void TargetProperties::UpdateLaunchInfoFromProperties ()
Definition at line 4530 of file Target.cpp.
References Arg0ValueChangedCallback(), DetachOnErrorValueChangedCallback(), DisableASLRValueChangedCallback(), DisableSTDIOValueChangedCallback(), EnvVarsValueChangedCallback(), ErrorPathValueChangedCallback(), InheritTCCValueChangedCallback(), InputPathValueChangedCallback(), OutputPathValueChangedCallback(), and RunArgsValueChangedCallback().
Referenced by lldb_private::Target::Target().
Member Data Documentation
m_experimental_properties_up
std::unique_ptr<TargetExperimentalProperties> lldb_private::TargetProperties::m_experimental_properties_up private
Definition at line 305 of file Target.h.
Referenced by TargetProperties().
m_launch_info
ProcessLaunchInfo lldb_private::TargetProperties::m_launch_info private
Definition at line 304 of file Target.h.
Referenced by Arg0ValueChangedCallback(), DetachOnErrorValueChangedCallback(), DisableASLRValueChangedCallback(), DisableSTDIOValueChangedCallback(), EnvVarsValueChangedCallback(), ErrorPathValueChangedCallback(), GetProcessLaunchInfo(), InheritTCCValueChangedCallback(), InputPathValueChangedCallback(), OutputPathValueChangedCallback(), RunArgsValueChangedCallback(), SetArg0(), SetProcessLaunchInfo(), SetRunArguments(), and TargetProperties().
m_target
Target* lldb_private::TargetProperties::m_target private
Definition at line 306 of file Target.h.
Referenced by CheckJITObjectsDir(), ComputeEnvironment(), GetInheritedEnvironment(), GetPreloadSymbols(), and TargetProperties().
The documentation for this class was generated from the following files:
Target.h
Target.cpp