LLDB: lldb_private::SymbolVendor Class Reference
lldb_private::SymbolVendor Class Reference
#include <SymbolVendor.h>
Public Member Functions
SymbolVendor (const lldb::ModuleSP &module_sp)
void AddSymbolFileRepresentation (const lldb::ObjectFileSP &objfile_sp)
SymbolFile * GetSymbolFile ()
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::ModuleChild
ModuleChild (const lldb::ModuleSP &module_sp)
Construct with owning module.
~ModuleChild ()
Destructor.
const ModuleChild & operator= (const ModuleChild &rhs)
Assignment operator.
lldb::ModuleSP GetModule () const
Get const accessor for the module pointer.
void SetModule (const lldb::ModuleSP &module_sp)
Set accessor for the module pointer.
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static SymbolVendor * FindPlugin (const lldb::ModuleSP &module_sp, Stream *feedback_strm)
Protected Attributes
std::unique_ptr< SymbolFile > m_sym_file_up
Protected Attributes inherited from lldb_private::ModuleChild
lldb::ModuleWP m_module_wp
The Module that owns the object that inherits from this class.
Detailed Description
Definition at line 31 of file SymbolVendor.h.
Constructor & Destructor Documentation
SymbolVendor()
SymbolVendor::SymbolVendor (const lldb::ModuleSP & module_sp)
Definition at line 60 of file SymbolVendor.cpp.
References m_sym_file_up, and lldb_private::ModuleChild::ModuleChild().
Referenced by FindPlugin(), SymbolVendorELF::SymbolVendorELF(), SymbolVendorMacOSX::SymbolVendorMacOSX(), SymbolVendorPECOFF::SymbolVendorPECOFF(), and lldb_private::wasm::SymbolVendorWasm::SymbolVendorWasm().
Member Function Documentation
AddSymbolFileRepresentation()
void SymbolVendor::AddSymbolFileRepresentation (const lldb::ObjectFileSP & objfile_sp)
Definition at line 64 of file SymbolVendor.cpp.
References lldb_private::SymbolFile::FindPlugin(), lldb_private::ModuleChild::GetModule(), and m_sym_file_up.
Referenced by lldb_private::wasm::SymbolVendorWasm::CreateInstance(), SymbolVendorELF::CreateInstance(), SymbolVendorMacOSX::CreateInstance(), and SymbolVendorPECOFF::CreateInstance().
FindPlugin()
SymbolVendor * SymbolVendor::FindPlugin (const lldb::ModuleSP & module_sp, lldb_private::Stream * feedback_strm) static
Definition at line 26 of file SymbolVendor.cpp.
References lldb_private::ObjectFile::FindPlugin(), lldb_private::PluginManager::GetSymbolVendorCreateCallbackAtIndex(), lldb_private::FileSystem::Instance(), and SymbolVendor().
Referenced by lldb_private::Module::GetSymbolFile().
GetPluginName()
llvm::StringRef lldb_private::SymbolVendor::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Reimplemented in lldb_private::wasm::SymbolVendorWasm, SymbolVendorELF, SymbolVendorMacOSX, and SymbolVendorPECOFF.
Definition at line 44 of file SymbolVendor.h.
GetSymbolFile()
SymbolFile * lldb_private::SymbolVendor::GetSymbolFile () inline
Definition at line 41 of file SymbolVendor.h.
References m_sym_file_up.
Member Data Documentation
m_sym_file_up
std::unique_ptr<SymbolFile> lldb_private::SymbolVendor::m_sym_file_up protected
Definition at line 47 of file SymbolVendor.h.
Referenced by AddSymbolFileRepresentation(), GetSymbolFile(), and SymbolVendor().
The documentation for this class was generated from the following files:
SymbolVendor.h
SymbolVendor.cpp