LLDB: lldb_private::RegInfoBasedABI Class Reference
lldb_private::RegInfoBasedABI Class Reference abstract
#include <ABI.h>
Public Member Functions
void AugmentRegisterInfo (std::vector< DynamicRegisterInfo::Register > &regs) override
Public Member Functions inherited from lldb_private::ABI
~ABI () override
virtual size_t GetRedZoneSize () const =0
virtual bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const =0
virtual bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::Type &prototype, llvm::ArrayRef< CallArgument > args) const
virtual bool GetArgumentValues (Thread &thread, ValueList &values) const =0
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, CompilerType &type, bool persistent=true) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, llvm::Type &type, bool persistent=true) const
virtual Status SetReturnValueObject (lldb::StackFrameSP &frame_sp, lldb::ValueObjectSP &new_value)=0
virtual lldb::UnwindPlanSP CreateFunctionEntryUnwindPlan ()=0
virtual lldb::UnwindPlanSP CreateDefaultUnwindPlan ()=0
virtual bool RegisterIsVolatile (const RegisterInfo *reg_info)=0
virtual bool GetFallbackRegisterLocation (const RegisterInfo *reg_info, UnwindPlan::Row::AbstractRegisterLocation &unwind_regloc)
virtual bool CallFrameAddressIsValid (lldb::addr_t cfa)=0
virtual bool CodeAddressIsValid (lldb::addr_t pc)=0
virtual lldb::addr_t FixAnyAddress (lldb::addr_t pc)
Use this method when you do not know, or do not care what kind of address you are fixing.
llvm::MCRegisterInfo & GetMCRegisterInfo ()
virtual bool GetPointerReturnRegister (const char *&name)
virtual uint64_t GetStackFrameSize ()
virtual lldb::addr_t FixCodeAddress (lldb::addr_t pc)
Some targets might use bits in a code address to indicate a mode switch.
virtual lldb::addr_t FixDataAddress (lldb::addr_t pc)
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
virtual llvm::StringRef GetPluginName ()=0
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Protected Member Functions
bool GetRegisterInfoByName (llvm::StringRef name, RegisterInfo &info)
virtual const RegisterInfo * GetRegisterInfoArray (uint32_t &count)=0
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Protected Member Functions inherited from lldb_private::ABI
virtual lldb::ValueObjectSP GetReturnValueObjectImpl (Thread &thread, CompilerType &ast_type) const =0
virtual lldb::ValueObjectSP GetReturnValueObjectImpl (Thread &thread, llvm::Type &ir_type) const
lldb::ProcessSP GetProcessSP () const
Request to get a Process shared pointer.
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Additional Inherited Members
Static Public Member Functions inherited from lldb_private::ABI
static lldb::ABISP FindPlugin (lldb::ProcessSP process_sp, const ArchSpec &arch)
Static Protected Member Functions inherited from lldb_private::ABI
static std::unique_ptr< llvm::MCRegisterInfo > MakeMCRegisterInfo (const ArchSpec &arch)
Utility function to construct a MCRegisterInfo using the ArchSpec triple.
Protected Attributes inherited from lldb_private::ABI
lldb::ProcessWP m_process_wp
std::unique_ptr< llvm::MCRegisterInfo > m_mc_register_info_up
Detailed Description
Definition at line 175 of file ABI.h.
Member Function Documentation
ABI()
lldb_private::ABI::ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up) inline protected
Definition at line 156 of file ABI.h.
AugmentRegisterInfo()
void RegInfoBasedABI::AugmentRegisterInfo (std::vector< DynamicRegisterInfo::Register > & regs) override virtual
Implements lldb_private::ABI.
Definition at line 251 of file ABI.cpp.
References lldb::eRegisterKindDWARF, lldb::eRegisterKindEHFrame, lldb::eRegisterKindGeneric, GetRegisterInfoByName(), lldb_private::RegisterInfo::kinds, and LLDB_INVALID_REGNUM.
Referenced by ABISysV_loongarch::AugmentRegisterInfo(), and ABISysV_riscv::AugmentRegisterInfo().
GetRegisterInfoArray()
virtual const RegisterInfo * lldb_private::RegInfoBasedABI::GetRegisterInfoArray (uint32_t & count) protected pure virtual
Implemented in ABIMacOSX_arm, ABISysV_arc, ABISysV_arm, ABISysV_hexagon, ABISysV_loongarch, ABISysV_mips64, ABISysV_mips, ABISysV_msp430, ABISysV_ppc64, ABISysV_ppc, ABISysV_riscv, and ABISysV_s390x.
Referenced by GetRegisterInfoByName().
GetRegisterInfoByName()
bool RegInfoBasedABI::GetRegisterInfoByName (llvm::StringRef name, RegisterInfo & info) protected
Definition at line 46 of file ABI.cpp.
References lldb_private::RegisterInfo::alt_name, GetRegisterInfoArray(), and lldb_private::RegisterInfo::name.
Referenced by AugmentRegisterInfo().
The documentation for this class was generated from the following files:
ABI.h
ABI.cpp