LLDB: CommandObjectWatchpointCommandAdd::CommandOptions Class Reference
CommandObjectWatchpointCommandAdd::CommandOptions Class Reference
Public Member Functions
CommandOptions ()=default
~CommandOptions () override=default
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext *execution_context) override
Set the value of an option.
void OptionParsingStarting (ExecutionContext *execution_context) override
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Public Member Functions inherited from lldb_private::Options
Options ()
virtual ~Options ()
void BuildGetoptTable ()
void BuildValidOptionSets ()
uint32_t NumCommandOptions ()
Option * GetLongOptions ()
Get the option definitions to use when parsing Args options.
void OptionSeen (int short_option)
llvm::Error VerifyOptions ()
llvm::Error VerifyPartialOptions ()
void OutputFormattedUsageText (Stream &strm, const OptionDefinition &option_def, uint32_t output_max_columns, bool use_color)
void GenerateOptionUsage (Stream &strm, CommandObject &cmd, uint32_t screen_width, bool use_color)
bool SupportsLongOption (const char *long_option)
void NotifyOptionParsingStarting (ExecutionContext *execution_context)
llvm::Expected< Args > Parse (const Args &args, ExecutionContext *execution_context, lldb::PlatformSP platform_sp, bool require_validation)
Parse the provided arguments.
llvm::Expected< Args > ParseAlias (const Args &args, OptionArgVector *option_arg_vector, std::string &input_line)
OptionElementVector ParseForCompletion (const Args &args, uint32_t cursor_index)
Status NotifyOptionParsingFinished (ExecutionContext *execution_context)
bool HandleOptionCompletion (lldb_private::CompletionRequest &request, OptionElementVector &option_map, CommandInterpreter &interpreter)
Handles the generic bits of figuring out whether we are in an option, and if so completing it.
virtual void HandleOptionArgumentCompletion (lldb_private::CompletionRequest &request, OptionElementVector &opt_element_vector, int opt_element_index, CommandInterpreter &interpreter)
Handles the generic bits of figuring out whether we are in an option, and if so completing it.
Public Attributes
bool m_use_commands = false
bool m_use_script_language = false
lldb::ScriptLanguage m_script_language = eScriptLanguageNone
bool m_use_one_liner = false
std::string m_one_liner
bool m_stop_on_error
std::string m_function_name
Additional Inherited Members
Protected Types inherited from lldb_private::Options
typedef std::set< int > OptionSet
typedef std::vector< OptionSet > OptionSetVector
Protected Member Functions inherited from lldb_private::Options
OptionSetVector & GetRequiredOptions ()
OptionSetVector & GetOptionalOptions ()
bool IsASubset (const OptionSet &set_a, const OptionSet &set_b)
size_t OptionsSetDiff (const OptionSet &set_a, const OptionSet &set_b, OptionSet &diffs)
void OptionsSetUnion (const OptionSet &set_a, const OptionSet &set_b, OptionSet &union_set)
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Protected Attributes inherited from lldb_private::Options
std::vector< Option > m_getopt_table
OptionSet m_seen_options
OptionSetVector m_required_options
OptionSetVector m_optional_options
Detailed Description
Definition at line 192 of file CommandObjectWatchpointCommand.cpp.
Constructor & Destructor Documentation
CommandOptions()
CommandObjectWatchpointCommandAdd::CommandOptions::CommandOptions () default
Referenced by CommandObjectWatchpointCommandAdd::DoExecute().
~CommandOptions()
CommandObjectWatchpointCommandAdd::CommandOptions::~CommandOptions () override default
Referenced by CommandObjectWatchpointCommandAdd::DoExecute().
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > CommandObjectWatchpointCommandAdd::CommandOptions::GetDefinitions () inline override virtual
Reimplemented from lldb_private::Options.
Definition at line 257 of file CommandObjectWatchpointCommand.cpp.
Referenced by CommandObjectWatchpointCommandAdd::DoExecute().
OptionParsingStarting()
void CommandObjectWatchpointCommandAdd::CommandOptions::OptionParsingStarting (ExecutionContext * execution_context) inline override virtual
Implements lldb_private::Options.
Definition at line 246 of file CommandObjectWatchpointCommand.cpp.
Referenced by CommandObjectWatchpointCommandAdd::DoExecute().
SetOptionValue()
Status CommandObjectWatchpointCommandAdd::CommandOptions::SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext * execution_context) inline override virtual
Set the value of an option.
Parameters
[in] option_idx The index into the "struct option" array that was returned by Options::GetLongOptions().
[in] option_arg The argument value for the option that the user entered, or nullptr if there is no argument for the current option.
[in] execution_context The execution context to use for evaluating the option. May be nullptr if the option is to be evaluated outside any particular context.
See also
Args::ParseOptions (Options&)
man getopt_long_only
Implements lldb_private::Options.
Definition at line 198 of file CommandObjectWatchpointCommand.cpp.
References CommandObjectWatchpointCommandAdd::WatchpointOptionsCallbackFunction().
Referenced by CommandObjectWatchpointCommandAdd::DoExecute().
Member Data Documentation
m_function_name
std::string CommandObjectWatchpointCommandAdd::CommandOptions::m_function_name
Definition at line 271 of file CommandObjectWatchpointCommand.cpp.
Referenced by CommandObjectWatchpointCommandAdd::DoExecute().
m_one_liner
std::string CommandObjectWatchpointCommandAdd::CommandOptions::m_one_liner
Definition at line 269 of file CommandObjectWatchpointCommand.cpp.
Referenced by CommandObjectWatchpointCommandAdd::DoExecute().
m_script_language
lldb::ScriptLanguage CommandObjectWatchpointCommandAdd::CommandOptions::m_script_language = eScriptLanguageNone
Definition at line 265 of file CommandObjectWatchpointCommand.cpp.
Referenced by CommandObjectWatchpointCommandAdd::DoExecute().
m_stop_on_error
bool CommandObjectWatchpointCommandAdd::CommandOptions::m_stop_on_error
Definition at line 270 of file CommandObjectWatchpointCommand.cpp.
Referenced by CommandObjectWatchpointCommandAdd::DoExecute().
m_use_commands
bool CommandObjectWatchpointCommandAdd::CommandOptions::m_use_commands = false
Definition at line 263 of file CommandObjectWatchpointCommand.cpp.
Referenced by CommandObjectWatchpointCommandAdd::DoExecute().
m_use_one_liner
bool CommandObjectWatchpointCommandAdd::CommandOptions::m_use_one_liner = false
Definition at line 268 of file CommandObjectWatchpointCommand.cpp.
Referenced by CommandObjectWatchpointCommandAdd::DoExecute().
m_use_script_language
bool CommandObjectWatchpointCommandAdd::CommandOptions::m_use_script_language = false
Definition at line 264 of file CommandObjectWatchpointCommand.cpp.
Referenced by CommandObjectWatchpointCommandAdd::DoExecute().
The documentation for this class was generated from the following file:
CommandObjectWatchpointCommand.cpp