LLDB: lldb_private::HostThreadWindows Class Reference
lldb_private::HostThreadWindows Class Reference
#include <HostThreadWindows.h>
Public Member Functions
HostThreadWindows ()
HostThreadWindows (lldb::thread_t thread)
virtual ~HostThreadWindows ()
void SetOwnsHandle (bool owns)
Status Join (lldb::thread_result_t *result) override
Status Cancel () override
void Reset () override
bool EqualsThread (lldb::thread_t thread) const override
lldb::tid_t GetThreadId () const
Public Member Functions inherited from lldb_private::HostNativeThreadBase
HostNativeThreadBase ()=default
HostNativeThreadBase (lldb::thread_t thread)
virtual ~HostNativeThreadBase ()=default
virtual bool IsJoinable () const
lldb::thread_t Release ()
lldb::thread_t GetSystemHandle () const
lldb::thread_result_t GetResult () const
Private Member Functions
HostThreadWindows (const HostThreadWindows &)=delete
const HostThreadWindows & operator= (const HostThreadWindows &)=delete
Private Attributes
bool m_owns_handle
Additional Inherited Members
Static Protected Member Functions inherited from lldb_private::HostNativeThreadBase
static lldb::thread_result_t THREAD_ROUTINE ThreadCreateTrampoline (lldb::thread_arg_t arg)
Protected Attributes inherited from lldb_private::HostNativeThreadBase
lldb::thread_t m_thread = LLDB_INVALID_HOST_THREAD
lldb::thread_result_t m_result = 0
Detailed Description
Definition at line 18 of file HostThreadWindows.h.
Constructor & Destructor Documentation
HostThreadWindows() [1/3]
lldb_private::HostThreadWindows::HostThreadWindows (const HostThreadWindows &) private delete
References HostThreadWindows().
Referenced by HostThreadWindows(), and operator=().
HostThreadWindows() [2/3]
HostThreadWindows::HostThreadWindows ()
Definition at line 23 of file HostThreadWindows.cpp.
References lldb_private::HostNativeThreadBase::HostNativeThreadBase(), and m_owns_handle.
HostThreadWindows() [3/3]
HostThreadWindows::HostThreadWindows (lldb::thread_t thread)
Definition at line 26 of file HostThreadWindows.cpp.
References lldb_private::HostNativeThreadBase::HostNativeThreadBase(), and m_owns_handle.
~HostThreadWindows()
HostThreadWindows::~HostThreadWindows () virtual
Definition at line 29 of file HostThreadWindows.cpp.
References Reset().
Member Function Documentation
Cancel()
Status HostThreadWindows::Cancel () override virtual
Implements lldb_private::HostNativeThreadBase.
Definition at line 51 of file HostThreadWindows.cpp.
References lldb::eErrorTypeWin32, error(), ExitThreadProxy(), lldb_private::HostNativeThreadBase::m_thread, and lldb_private::Status.
EqualsThread()
bool HostThreadWindows::EqualsThread (lldb::thread_t thread) const override virtual
Reimplemented from lldb_private::HostNativeThreadBase.
Definition at line 70 of file HostThreadWindows.cpp.
References GetThreadId().
GetThreadId()
lldb::tid_t HostThreadWindows::GetThreadId () const
Definition at line 59 of file HostThreadWindows.cpp.
References lldb_private::HostNativeThreadBase::m_thread.
Referenced by EqualsThread().
Join()
Status HostThreadWindows::Join (lldb::thread_result_t * result) override virtual
Implements lldb_private::HostNativeThreadBase.
Definition at line 33 of file HostThreadWindows.cpp.
References lldb::eErrorTypeWin32, error(), lldb_private::HostNativeThreadBase::IsJoinable(), lldb_private::HostNativeThreadBase::m_thread, Reset(), and lldb_private::Status.
operator=()
const HostThreadWindows & lldb_private::HostThreadWindows::operator= (const HostThreadWindows &) private delete
References HostThreadWindows().
Reset()
void HostThreadWindows::Reset () override virtual
Reimplemented from lldb_private::HostNativeThreadBase.
Definition at line 63 of file HostThreadWindows.cpp.
References LLDB_INVALID_HOST_THREAD, m_owns_handle, lldb_private::HostNativeThreadBase::m_thread, and lldb_private::HostNativeThreadBase::Reset().
Referenced by Join(), and ~HostThreadWindows().
SetOwnsHandle()
void HostThreadWindows::SetOwnsHandle (bool owns)
Definition at line 31 of file HostThreadWindows.cpp.
References m_owns_handle.
Member Data Documentation
m_owns_handle
bool lldb_private::HostThreadWindows::m_owns_handle private
Definition at line 37 of file HostThreadWindows.h.
Referenced by HostThreadWindows(), HostThreadWindows(), Reset(), and SetOwnsHandle().
The documentation for this class was generated from the following files:
HostThreadWindows.h
HostThreadWindows.cpp