LLDB: lldb_private::IOHandlerPythonInterpreter Class Reference
lldb_private::IOHandlerPythonInterpreter Class Reference
#include <ScriptInterpreterPythonImpl.h>
Public Member Functions
IOHandlerPythonInterpreter (Debugger &debugger, ScriptInterpreterPythonImpl *python)
~IOHandlerPythonInterpreter () override=default
llvm::StringRef GetControlSequence (char ch) override
void Run () override
void Cancel () override
bool Interrupt () override
void GotEOF () override
Public Member Functions inherited from lldb_private::IOHandler
IOHandler (Debugger &debugger, IOHandler::Type type)
IOHandler (Debugger &debugger, IOHandler::Type type, const lldb::FileSP &input_sp, const lldb::LockableStreamFileSP &output_sp, const lldb::LockableStreamFileSP &error_sp, uint32_t flags)
virtual ~IOHandler ()
bool IsActive ()
void SetIsDone (bool b)
bool GetIsDone ()
Type GetType () const
virtual void Activate ()
virtual void Deactivate ()
virtual void TerminalSizeChanged ()
virtual void Refresh ()
virtual const char * GetPrompt ()
virtual bool SetPrompt (llvm::StringRef prompt)
virtual bool SetUseColor (bool use_color)
bool SetPrompt (const char *)=delete
virtual const char * GetCommandPrefix ()
virtual const char * GetHelpPrologue ()
int GetInputFD ()
int GetOutputFD ()
int GetErrorFD ()
lldb::FileSP GetInputFileSP ()
lldb::LockableStreamFileSP GetOutputStreamFileSP ()
lldb::LockableStreamFileSP GetErrorStreamFileSP ()
Debugger & GetDebugger ()
void * GetUserData ()
void SetUserData (void *user_data)
Flags & GetFlags ()
const Flags & GetFlags () const
bool GetIsInteractive ()
Check if the input is being supplied interactively by a user.
bool GetIsRealTerminal ()
Check if the input is coming from a real terminal.
void SetPopped (bool b)
void WaitForPop ()
virtual void PrintAsync (const char *s, size_t len, bool is_stdout)
Protected Attributes
ScriptInterpreterPythonImpl * m_python
Protected Attributes inherited from lldb_private::IOHandler
Debugger & m_debugger
lldb::FileSP m_input_sp
lldb::LockableStreamFileSP m_output_sp
lldb::LockableStreamFileSP m_error_sp
Predicate< bool > m_popped
Flags m_flags
Type m_type
void * m_user_data
bool m_done
bool m_active
Additional Inherited Members
Public Types inherited from lldb_private::IOHandler
enum class Type {
CommandInterpreter , CommandList , Confirm , Curses ,
Expression , REPL , ProcessIO , PythonInterpreter ,
LuaInterpreter , PythonCode , Other
}
Detailed Description
Definition at line 426 of file ScriptInterpreterPythonImpl.h.
Constructor & Destructor Documentation
IOHandlerPythonInterpreter()
lldb_private::IOHandlerPythonInterpreter::IOHandlerPythonInterpreter (Debugger & debugger, ScriptInterpreterPythonImpl * python) inline
Definition at line 428 of file ScriptInterpreterPythonImpl.h.
References lldb_private::IOHandler::IOHandler(), m_python, and lldb_private::IOHandler::PythonInterpreter.
~IOHandlerPythonInterpreter()
lldb_private::IOHandlerPythonInterpreter::~IOHandlerPythonInterpreter () override default
Member Function Documentation
Cancel()
void lldb_private::IOHandlerPythonInterpreter::Cancel () inline override virtual
Implements lldb_private::IOHandler.
Definition at line 485 of file ScriptInterpreterPythonImpl.h.
GetControlSequence()
llvm::StringRef lldb_private::IOHandlerPythonInterpreter::GetControlSequence (char ch) inline override virtual
Reimplemented from lldb_private::IOHandler.
Definition at line 435 of file ScriptInterpreterPythonImpl.h.
GotEOF()
void lldb_private::IOHandlerPythonInterpreter::GotEOF () inline override virtual
Implements lldb_private::IOHandler.
Definition at line 489 of file ScriptInterpreterPythonImpl.h.
Interrupt()
bool lldb_private::IOHandlerPythonInterpreter::Interrupt () inline override virtual
Implements lldb_private::IOHandler.
Definition at line 487 of file ScriptInterpreterPythonImpl.h.
References m_python.
Run()
void lldb_private::IOHandlerPythonInterpreter::Run () inline override virtual
Implements lldb_private::IOHandler.
Definition at line 442 of file ScriptInterpreterPythonImpl.h.
References lldb_private::ScriptInterpreterPythonImpl::Locker::AcquireLock, lldb_private::ScriptInterpreterPythonImpl::Locker::FreeAcquiredLock, lldb_private::StreamString::GetData(), lldb_private::IOHandler::GetInputFD(), lldb_private::ScriptInterpreterPythonImpl::Locker::InitGlobals, lldb_private::ScriptInterpreterPythonImpl::Locker::InitSession, lldb_private::Terminal::IsATerminal(), m_python, lldb_private::Stream::Printf(), lldb_private::python::RunSimpleString(), lldb_private::Terminal::SetCanonical(), lldb_private::Terminal::SetEcho(), lldb_private::IOHandler::SetIsDone(), and lldb_private::ScriptInterpreterPythonImpl::Locker::TearDownSession.
Member Data Documentation
m_python
ScriptInterpreterPythonImpl* lldb_private::IOHandlerPythonInterpreter::m_python protected
Definition at line 492 of file ScriptInterpreterPythonImpl.h.
Referenced by Interrupt(), IOHandlerPythonInterpreter(), and Run().
The documentation for this class was generated from the following file:
ScriptInterpreterPythonImpl.h