LLDB: lldb_private::plugin::dwarf::DWARFDebugInfoEntry Class Reference
lldb_private::plugin::dwarf::DWARFDebugInfoEntry Class Reference
DWARFDebugInfoEntry objects assume that they are living in one big vector and do pointer arithmetic on their this pointers.
#include <DWARFDebugInfoEntry.h>
Public Types
typedef std::vector< DWARFDebugInfoEntry > collection
typedef collection::iterator iterator
typedef collection::const_iterator const_iterator
using Recurse = DWARFBaseDIE::Recurse
Public Member Functions
DWARFDebugInfoEntry ()
operator bool () const
bool operator== (const DWARFDebugInfoEntry &rhs) const
bool operator!= (const DWARFDebugInfoEntry &rhs) const
void BuildFunctionAddressRangeTable (DWARFUnit *cu, DWARFDebugAranges *debug_aranges) const
This function is builds a table very similar to the standard .debug_aranges table, except that the actual DIE offset for the function is placed in the table instead of the compile unit offset.
bool Extract (const DWARFDataExtractor &data, const DWARFUnit &cu, lldb::offset_t *offset_ptr)
DWARFAttributes GetAttributes (const DWARFUnit *cu, Recurse recurse=Recurse::yes) const
Get all attribute values for a given DIE, optionally following any specifications and abstract origins and including their attributes in the result too.
dw_offset_t GetAttributeValue (const DWARFUnit *cu, const dw_attr_t attr, DWARFFormValue &formValue, dw_offset_t *end_attr_offset_ptr=nullptr, bool check_elaborating_dies=false) const
const char * GetAttributeValueAsString (const DWARFUnit *cu, const dw_attr_t attr, const char *fail_value, bool check_elaborating_dies=false) const
uint64_t GetAttributeValueAsUnsigned (const DWARFUnit *cu, const dw_attr_t attr, uint64_t fail_value, bool check_elaborating_dies=false) const
std::optional< uint64_t > GetAttributeValueAsOptionalUnsigned (const DWARFUnit *cu, const dw_attr_t attr, bool check_elaborating_dies=false) const
DWARFDIE GetAttributeValueAsReference (const DWARFUnit *cu, const dw_attr_t attr, bool check_elaborating_dies=false) const
uint64_t GetAttributeValueAsAddress (const DWARFUnit *cu, const dw_attr_t attr, uint64_t fail_value, bool check_elaborating_dies=false) const
dw_addr_t GetAttributeHighPC (const DWARFUnit *cu, dw_addr_t lo_pc, uint64_t fail_value, bool check_elaborating_dies=false) const
bool GetAttributeAddressRange (const DWARFUnit *cu, dw_addr_t &lo_pc, dw_addr_t &hi_pc, uint64_t fail_value, bool check_elaborating_dies=false) const
llvm::Expected< llvm::DWARFAddressRangesVector > GetAttributeAddressRanges (DWARFUnit *cu, bool check_hi_lo_pc, bool check_elaborating_dies=false) const
const char * GetName (const DWARFUnit *cu) const
const char * GetMangledName (const DWARFUnit *cu, bool substitute_name_allowed=true) const
const char * GetPubname (const DWARFUnit *cu) const
bool GetDIENamesAndRanges (DWARFUnit *cu, const char *&name, const char *&mangled, llvm::DWARFAddressRangesVector &rangeList, std::optional< int > &decl_file, std::optional< int > &decl_line, std::optional< int > &decl_column, std::optional< int > &call_file, std::optional< int > &call_line, std::optional< int > &call_column, DWARFExpressionList *frame_base=nullptr) const
const llvm::DWARFAbbreviationDeclaration * GetAbbreviationDeclarationPtr (const DWARFUnit *cu) const
lldb::offset_t GetFirstAttributeOffset () const
dw_tag_t Tag () const
bool IsNULL () const
dw_offset_t GetOffset () const
bool HasChildren () const
void SetHasChildren (bool b)
DWARFDebugInfoEntry * GetParent ()
const DWARFDebugInfoEntry * GetParent () const
DWARFDebugInfoEntry * GetSibling ()
const DWARFDebugInfoEntry * GetSibling () const
DWARFDebugInfoEntry * GetFirstChild ()
const DWARFDebugInfoEntry * GetFirstChild () const
void SetSiblingIndex (uint32_t idx)
void SetParentIndex (uint32_t idx)
bool IsGlobalOrStaticScopeVariable () const
Protected Attributes
dw_offset_t m_offset: DW_DIE_OFFSET_MAX_BITSIZE
dw_offset_t m_parent_idx: 64 - DW_DIE_OFFSET_MAX_BITSIZE
uint32_t m_sibling_idx: 31
uint32_t m_has_children: 1
uint16_t m_abbr_idx = 0
dw_tag_t m_tag = llvm::dwarf::DW_TAG_null
A copy of the DW_TAG value so we don't have to go through the compile unit abbrev table.
Detailed Description
DWARFDebugInfoEntry objects assume that they are living in one big vector and do pointer arithmetic on their this pointers.
Don't pass them by value. Due to the way they are constructed in a std::vector, we cannot delete the copy constructor.
Definition at line 34 of file DWARFDebugInfoEntry.h.
Member Typedef Documentation
collection
typedef std::vector<DWARFDebugInfoEntry> lldb_private::plugin::dwarf::DWARFDebugInfoEntry::collection
Definition at line 36 of file DWARFDebugInfoEntry.h.
const_iterator
typedef collection::const_iterator lldb_private::plugin::dwarf::DWARFDebugInfoEntry::const_iterator
Definition at line 38 of file DWARFDebugInfoEntry.h.
iterator
typedef collection::iterator lldb_private::plugin::dwarf::DWARFDebugInfoEntry::iterator
Definition at line 37 of file DWARFDebugInfoEntry.h.
Recurse
using lldb_private::plugin::dwarf::DWARFDebugInfoEntry::Recurse = DWARFBaseDIE::Recurse
Definition at line 54 of file DWARFDebugInfoEntry.h.
Constructor & Destructor Documentation
DWARFDebugInfoEntry()
lldb_private::plugin::dwarf::DWARFDebugInfoEntry::DWARFDebugInfoEntry () inline
Definition at line 40 of file DWARFDebugInfoEntry.h.
References DW_INVALID_OFFSET, m_has_children, m_offset, m_parent_idx, and m_sibling_idx.
Referenced by BuildFunctionAddressRangeTable(), GetFirstChild(), GetFirstChild(), GetParent(), GetParent(), GetSibling(), GetSibling(), IsGlobalOrStaticScopeVariable(), operator!=(), and operator==().
Member Function Documentation
BuildFunctionAddressRangeTable()
void DWARFDebugInfoEntry::BuildFunctionAddressRangeTable (DWARFUnit * cu, DWARFDebugAranges * debug_aranges) const
This function is builds a table very similar to the standard .debug_aranges table, except that the actual DIE offset for the function is placed in the table instead of the compile unit offset.
Definition at line 614 of file DWARFDebugInfoEntry.cpp.
References lldb_private::plugin::dwarf::DWARFDebugAranges::AppendRange(), BuildFunctionAddressRangeTable(), lldb_private::DebugInfo, DWARFDebugInfoEntry(), GetAttributeAddressRanges(), GetAttributeValueAsOptionalUnsigned(), GetFirstChild(), lldb_private::GetLog(), GetOffset(), GetSibling(), LLDB_LOG_ERROR, and m_tag.
Referenced by BuildFunctionAddressRangeTable(), and lldb_private::plugin::dwarf::DWARFUnit::GetFunctionAranges().
Extract()
bool DWARFDebugInfoEntry::Extract (const DWARFDataExtractor & data, const DWARFUnit & cu, lldb::offset_t * offset_ptr)
Definition at line 43 of file DWARFDebugInfoEntry.cpp.
References GetAbbreviationDeclarationPtr(), lldb_private::ModuleChild::GetModule(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::plugin::dwarf::DWARFUnit::GetSymbolFileDWARF(), lldb_private::DataExtractor::GetULEB128(), m_abbr_idx, m_has_children, m_offset, m_parent_idx, m_sibling_idx, m_tag, and lldb_private::plugin::dwarf::DWARFFormValue::SkipValue().
Referenced by lldb_private::plugin::dwarf::DWARFUnit::ExtractDIEsRWLocked(), and lldb_private::plugin::dwarf::DWARFUnit::PeekDIEName().
GetAbbreviationDeclarationPtr()
const llvm::DWARFAbbreviationDeclaration * DWARFDebugInfoEntry::GetAbbreviationDeclarationPtr (const DWARFUnit * cu) const
Definition at line 645 of file DWARFDebugInfoEntry.cpp.
References lldb_private::plugin::dwarf::DWARFUnit::GetAbbreviations(), and m_abbr_idx.
Referenced by Extract(), GetAttributeValue(), and GetDIENamesAndRanges().
GetAttributeAddressRange()
bool DWARFDebugInfoEntry::GetAttributeAddressRange (const DWARFUnit * cu, dw_addr_t & lo_pc, dw_addr_t & hi_pc, uint64_t fail_value, bool check_elaborating_dies = false) const
Definition at line 524 of file DWARFDebugInfoEntry.cpp.
References GetAttributeHighPC(), and GetAttributeValueAsAddress().
Referenced by GetAttributeAddressRanges().
GetAttributeAddressRanges()
llvm::Expected< llvm::DWARFAddressRangesVector > DWARFDebugInfoEntry::GetAttributeAddressRanges (DWARFUnit * cu, bool check_hi_lo_pc, bool check_elaborating_dies = false) const
Definition at line 540 of file DWARFDebugInfoEntry.cpp.
References GetAttributeAddressRange(), GetAttributeValue(), GetRanges(), and LLDB_INVALID_ADDRESS.
Referenced by lldb_private::plugin::dwarf::DWARFCompileUnit::BuildAddressRangeTable(), and BuildFunctionAddressRangeTable().
GetAttributeHighPC()
dw_addr_t DWARFDebugInfoEntry::GetAttributeHighPC (const DWARFUnit * cu, dw_addr_t lo_pc, uint64_t fail_value, bool check_elaborating_dies = false) const
Definition at line 501 of file DWARFDebugInfoEntry.cpp.
References lldb_private::plugin::dwarf::DWARFFormValue::Address(), lldb_private::plugin::dwarf::DWARFFormValue::Form(), GetAttributeValue(), and lldb_private::plugin::dwarf::DWARFFormValue::Unsigned().
Referenced by GetAttributeAddressRange().
GetAttributes()
DWARFAttributes DWARFDebugInfoEntry::GetAttributes (const DWARFUnit * cu, Recurse recurse = Recurse::yes) const
Get all attribute values for a given DIE, optionally following any specifications and abstract origins and including their attributes in the result too.
When following specifications/abstract origins, the attributes on the referring DIE are guaranteed to be visited before the attributes of the referenced DIE.
Parameters
[in] cu DWARFUnit that this entry belongs to.
[in] recurse If set to Recurse::yes, will include attributes on DIEs referenced via DW_AT_specification and DW_AT_abstract_origin (including across multiple levels of indirection).
Returns
DWARFAttributes that include all attributes found on this DIE (and possibly referenced DIEs). Attributes may appear multiple times (e.g., if a declaration and definition both specify the same attribute). On failure, the returned DWARFAttributes will be empty.
Definition at line 357 of file DWARFDebugInfoEntry.cpp.
References lldb_private::plugin::dwarf::DWARFAttributes::Clear(), and GetAttributes().
Referenced by lldb_private::plugin::dwarf::DWARFUnit::AddUnitDIE(), and GetAttributes().
GetAttributeValue()
dw_offset_t DWARFDebugInfoEntry::GetAttributeValue (const DWARFUnit * cu, const dw_attr_t attr, DWARFFormValue & formValue, dw_offset_t * end_attr_offset_ptr = nullptr, bool check_elaborating_dies = false) const
Definition at line 389 of file DWARFDebugInfoEntry.cpp.
References lldb_private::plugin::dwarf::DWARFFormValue::ExtractValue(), GetAbbreviationDeclarationPtr(), GetAttributeValue(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), lldb_private::plugin::dwarf::DWARFUnit::GetData(), lldb_private::plugin::dwarf::DWARFDIE::GetDIE(), GetFirstAttributeOffset(), lldb_private::plugin::dwarf::DWARFFormValue::Reference(), lldb_private::plugin::dwarf::DWARFFormValue::SetForm(), lldb_private::plugin::dwarf::DWARFFormValue::SetUnit(), lldb_private::plugin::dwarf::DWARFFormValue::SetValue(), and lldb_private::plugin::dwarf::DWARFFormValue::SkipValue().
Referenced by GetAttributeAddressRanges(), GetAttributeHighPC(), GetAttributeValue(), GetAttributeValueAsAddress(), GetAttributeValueAsOptionalUnsigned(), GetAttributeValueAsReference(), GetAttributeValueAsString(), GetAttributeValueAsUnsigned(), and lldb_private::plugin::dwarf::DWARFUnit::PeekDIEName().
GetAttributeValueAsAddress()
uint64_t DWARFDebugInfoEntry::GetAttributeValueAsAddress (const DWARFUnit * cu, const dw_attr_t attr, uint64_t fail_value, bool check_elaborating_dies = false) const
Definition at line 485 of file DWARFDebugInfoEntry.cpp.
References lldb_private::plugin::dwarf::DWARFFormValue::Address(), and GetAttributeValue().
Referenced by GetAttributeAddressRange().
GetAttributeValueAsOptionalUnsigned()
std::optional< uint64_t > DWARFDebugInfoEntry::GetAttributeValueAsOptionalUnsigned (const DWARFUnit * cu, const dw_attr_t attr, bool check_elaborating_dies = false) const
Definition at line 463 of file DWARFDebugInfoEntry.cpp.
References GetAttributeValue(), and lldb_private::plugin::dwarf::DWARFFormValue::Unsigned().
Referenced by BuildFunctionAddressRangeTable(), and GetDWOId().
GetAttributeValueAsReference()
DWARFDIE DWARFDebugInfoEntry::GetAttributeValueAsReference (const DWARFUnit * cu, const dw_attr_t attr, bool check_elaborating_dies = false) const
Definition at line 476 of file DWARFDebugInfoEntry.cpp.
References GetAttributeValue(), and lldb_private::plugin::dwarf::DWARFFormValue::Reference().
GetAttributeValueAsString()
const char * DWARFDebugInfoEntry::GetAttributeValueAsString (const DWARFUnit * cu, const dw_attr_t attr, const char * fail_value, bool check_elaborating_dies = false) const
Definition at line 441 of file DWARFDebugInfoEntry.cpp.
References lldb_private::plugin::dwarf::DWARFFormValue::AsCString(), and GetAttributeValue().
Referenced by lldb_private::plugin::dwarf::DWARFUnit::ComputeAbsolutePath(), lldb_private::plugin::dwarf::DWARFUnit::ComputeCompDirAndGuessPathStyle(), GetDWOName(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwoSymbolFileForCompileUnit(), GetMangledName(), GetName(), lldb_private::plugin::dwarf::DWARFDIE::GetName(), GetPubname(), lldb_private::plugin::dwarf::DWARFUnit::ParseProducerInfo(), and lldb_private::plugin::dwarf::DWARFUnit::PeekDIEName().
GetAttributeValueAsUnsigned()
uint64_t DWARFDebugInfoEntry::GetAttributeValueAsUnsigned (const DWARFUnit * cu, const dw_attr_t attr, uint64_t fail_value, bool check_elaborating_dies = false) const
Definition at line 453 of file DWARFDebugInfoEntry.cpp.
References GetAttributeValue(), and lldb_private::plugin::dwarf::DWARFFormValue::Unsigned().
Referenced by lldb_private::plugin::dwarf::DWARFUnit::GetDWARFLanguageType(), and lldb_private::plugin::dwarf::DWARFUnit::GetIsOptimized().
GetDIENamesAndRanges()
bool DWARFDebugInfoEntry::GetDIENamesAndRanges (DWARFUnit * cu, const char *& name, const char *& mangled, llvm::DWARFAddressRangesVector & rangeList, std::optional< int > & decl_file, std::optional< int > & decl_line, std::optional< int > & decl_column, std::optional< int > & call_file, std::optional< int > & call_line, std::optional< int > & call_column, DWARFExpressionList * frame_base = nullptr) const
Definition at line 105 of file DWARFDebugInfoEntry.cpp.
References lldb_private::plugin::dwarf::DWARFFormValue::Address(), lldb_private::plugin::dwarf::DWARFFormValue::AsCString(), lldb_private::plugin::dwarf::DWARFFormValue::BlockData(), ExtractAttrAndFormValue(), lldb_private::plugin::dwarf::DWARFFormValue::ExtractValue(), lldb_private::plugin::dwarf::DWARFFormValue::Form(), GetAbbreviationDeclarationPtr(), lldb_private::plugin::dwarf::DWARFUnit::GetBaseAddress(), lldb_private::DataExtractor::GetByteSize(), lldb_private::plugin::dwarf::DWARFUnit::GetData(), lldb_private::DataExtractor::GetDataStart(), GetFirstAttributeOffset(), lldb_private::plugin::dwarf::DWARFUnit::GetLocationData(), GetRanges(), lldb_private::plugin::dwarf::DWARFUnit::GetSymbolFileDWARF(), LLDB_INVALID_ADDRESS, lldb_private::plugin::dwarf::DWARFUnit::ParseDWARFLocationList(), lldb_private::plugin::dwarf::DWARFFormValue::Reference(), lldb_private::DWARFExpressionList::SetFuncFileAddress(), lldb_private::plugin::dwarf::DWARFFormValue::Unsigned(), and lldb_private::DataExtractor::ValidOffset().
GetFirstAttributeOffset()
lldb::offset_t DWARFDebugInfoEntry::GetFirstAttributeOffset () const
Definition at line 640 of file DWARFDebugInfoEntry.cpp.
References GetOffset(), and m_abbr_idx.
Referenced by GetAttributeValue(), and GetDIENamesAndRanges().
GetFirstChild() [1/2]
DWARFDebugInfoEntry * lldb_private::plugin::dwarf::DWARFDebugInfoEntry::GetFirstChild () inline
Definition at line 167 of file DWARFDebugInfoEntry.h.
References DWARFDebugInfoEntry(), and HasChildren().
Referenced by BuildFunctionAddressRangeTable().
GetFirstChild() [2/2]
const DWARFDebugInfoEntry * lldb_private::plugin::dwarf::DWARFDebugInfoEntry::GetFirstChild () const inline
Definition at line 170 of file DWARFDebugInfoEntry.h.
References DWARFDebugInfoEntry(), and HasChildren().
GetMangledName()
const char * DWARFDebugInfoEntry::GetMangledName (const DWARFUnit * cu, bool substitute_name_allowed = true) const
Definition at line 571 of file DWARFDebugInfoEntry.cpp.
References GetAttributeValueAsString().
GetName()
const char * DWARFDebugInfoEntry::GetName (const DWARFUnit * cu) const
Definition at line 562 of file DWARFDebugInfoEntry.cpp.
References GetAttributeValueAsString().
GetOffset()
dw_offset_t lldb_private::plugin::dwarf::DWARFDebugInfoEntry::GetOffset () const inline
Definition at line 142 of file DWARFDebugInfoEntry.h.
References m_offset.
Referenced by BuildFunctionAddressRangeTable(), CompareDIEOffset(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwoSymbolFileForCompileUnit(), and GetFirstAttributeOffset().
GetParent() [1/2]
DWARFDebugInfoEntry * lldb_private::plugin::dwarf::DWARFDebugInfoEntry::GetParent () inline
Definition at line 150 of file DWARFDebugInfoEntry.h.
References DWARFDebugInfoEntry(), and m_parent_idx.
Referenced by lldb_private::plugin::dwarf::UniqueDWARFASTTypeList::Find(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetTypeForDIE(), and IsGlobalOrStaticScopeVariable().
GetParent() [2/2]
const DWARFDebugInfoEntry * lldb_private::plugin::dwarf::DWARFDebugInfoEntry::GetParent () const inline
Definition at line 153 of file DWARFDebugInfoEntry.h.
References DWARFDebugInfoEntry(), and m_parent_idx.
GetPubname()
const char * DWARFDebugInfoEntry::GetPubname (const DWARFUnit * cu) const
Definition at line 594 of file DWARFDebugInfoEntry.cpp.
References GetAttributeValueAsString().
GetSibling() [1/2]
DWARFDebugInfoEntry * lldb_private::plugin::dwarf::DWARFDebugInfoEntry::GetSibling () inline
Definition at line 158 of file DWARFDebugInfoEntry.h.
References DWARFDebugInfoEntry(), and m_sibling_idx.
Referenced by BuildFunctionAddressRangeTable().
GetSibling() [2/2]
const DWARFDebugInfoEntry * lldb_private::plugin::dwarf::DWARFDebugInfoEntry::GetSibling () const inline
Definition at line 161 of file DWARFDebugInfoEntry.h.
References DWARFDebugInfoEntry(), and m_sibling_idx.
HasChildren()
bool lldb_private::plugin::dwarf::DWARFDebugInfoEntry::HasChildren () const inline
Definition at line 144 of file DWARFDebugInfoEntry.h.
References m_has_children.
Referenced by lldb_private::plugin::dwarf::DWARFUnit::ExtractDIEsRWLocked(), GetFirstChild(), and GetFirstChild().
IsGlobalOrStaticScopeVariable()
bool DWARFDebugInfoEntry::IsGlobalOrStaticScopeVariable () const
Definition at line 657 of file DWARFDebugInfoEntry.cpp.
References DWARFDebugInfoEntry(), GetParent(), and Tag().
IsNULL()
bool lldb_private::plugin::dwarf::DWARFDebugInfoEntry::IsNULL () const inline
Definition at line 140 of file DWARFDebugInfoEntry.h.
References m_abbr_idx.
Referenced by lldb_private::plugin::dwarf::DWARFUnit::ExtractDIEsRWLocked().
operator bool()
lldb_private::plugin::dwarf::DWARFDebugInfoEntry::operator bool () const inline explicit
Definition at line 44 of file DWARFDebugInfoEntry.h.
References DW_INVALID_OFFSET, and m_offset.
operator!=()
bool DWARFDebugInfoEntry::operator!= (const DWARFDebugInfoEntry & rhs) const
Definition at line 687 of file DWARFDebugInfoEntry.cpp.
References DWARFDebugInfoEntry().
operator==()
bool DWARFDebugInfoEntry::operator== (const DWARFDebugInfoEntry & rhs) const
Definition at line 680 of file DWARFDebugInfoEntry.cpp.
References DWARFDebugInfoEntry(), m_abbr_idx, m_has_children, m_offset, m_parent_idx, m_sibling_idx, and m_tag.
SetHasChildren()
void lldb_private::plugin::dwarf::DWARFDebugInfoEntry::SetHasChildren (bool b) inline
Definition at line 146 of file DWARFDebugInfoEntry.h.
References m_has_children.
SetParentIndex()
void lldb_private::plugin::dwarf::DWARFDebugInfoEntry::SetParentIndex (uint32_t idx) inline
Definition at line 175 of file DWARFDebugInfoEntry.h.
References m_parent_idx.
Referenced by lldb_private::plugin::dwarf::DWARFUnit::ExtractDIEsRWLocked().
SetSiblingIndex()
void lldb_private::plugin::dwarf::DWARFDebugInfoEntry::SetSiblingIndex (uint32_t idx) inline
Definition at line 174 of file DWARFDebugInfoEntry.h.
References m_sibling_idx.
Tag()
dw_tag_t lldb_private::plugin::dwarf::DWARFDebugInfoEntry::Tag () const inline
Definition at line 138 of file DWARFDebugInfoEntry.h.
References m_tag.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::GetTypeForDIE(), and IsGlobalOrStaticScopeVariable().
Member Data Documentation
m_abbr_idx
uint16_t lldb_private::plugin::dwarf::DWARFDebugInfoEntry::m_abbr_idx = 0 protected
Definition at line 193 of file DWARFDebugInfoEntry.h.
Referenced by Extract(), GetAbbreviationDeclarationPtr(), GetFirstAttributeOffset(), IsNULL(), and operator==().
m_has_children
uint32_t lldb_private::plugin::dwarf::DWARFDebugInfoEntry::m_has_children protected
Definition at line 192 of file DWARFDebugInfoEntry.h.
Referenced by DWARFDebugInfoEntry(), Extract(), HasChildren(), operator==(), and SetHasChildren().
m_offset
dw_offset_t lldb_private::plugin::dwarf::DWARFDebugInfoEntry::m_offset protected
Definition at line 184 of file DWARFDebugInfoEntry.h.
Referenced by DWARFDebugInfoEntry(), Extract(), GetOffset(), operator bool(), and operator==().
m_parent_idx
dw_offset_t lldb_private::plugin::dwarf::DWARFDebugInfoEntry::m_parent_idx protected
Definition at line 187 of file DWARFDebugInfoEntry.h.
Referenced by DWARFDebugInfoEntry(), Extract(), GetParent(), GetParent(), operator==(), and SetParentIndex().
m_sibling_idx
uint32_t lldb_private::plugin::dwarf::DWARFDebugInfoEntry::m_sibling_idx protected
Definition at line 192 of file DWARFDebugInfoEntry.h.
Referenced by DWARFDebugInfoEntry(), Extract(), GetSibling(), GetSibling(), operator==(), and SetSiblingIndex().
m_tag
dw_tag_t lldb_private::plugin::dwarf::DWARFDebugInfoEntry::m_tag = llvm::dwarf::DW_TAG_null protected
A copy of the DW_TAG value so we don't have to go through the compile unit abbrev table.
Definition at line 196 of file DWARFDebugInfoEntry.h.
Referenced by BuildFunctionAddressRangeTable(), Extract(), operator==(), and Tag().
The documentation for this class was generated from the following files:
DWARFDebugInfoEntry.h
DWARFDebugInfoEntry.cpp