LLDB: lldb_private::npdb::PdbAstBuilderClang Class Reference
lldb_private::npdb::PdbAstBuilderClang Class Reference
#include <PdbAstBuilderClang.h>
Public Member Functions
PdbAstBuilderClang (TypeSystemClang &clang)
CompilerDecl GetOrCreateDeclForUid (PdbSymUid uid) override
CompilerDeclContext GetOrCreateDeclContextForUid (PdbSymUid uid) override
CompilerDeclContext GetParentDeclContext (PdbSymUid uid) override
void EnsureFunction (PdbCompilandSymId func_id) override
void EnsureInlinedFunction (PdbCompilandSymId inlinesite_id) override
void EnsureBlock (PdbCompilandSymId block_id) override
void EnsureVariable (PdbCompilandSymId scope_id, PdbCompilandSymId var_id) override
void EnsureVariable (PdbGlobalSymId var_id) override
CompilerType GetOrCreateType (PdbTypeSymId type) override
CompilerType GetOrCreateTypedefType (PdbGlobalSymId id) override
bool CompleteType (CompilerType ct) override
void ParseDeclsForContext (CompilerDeclContext context) override
CompilerDeclContext FindNamespaceDecl (CompilerDeclContext parent_ctx, llvm::StringRef name) override
void Dump (Stream &stream, llvm::StringRef filter, bool show_color) override
clang::QualType GetBasicType (lldb::BasicType type)
clang::QualType GetOrCreateClangType (PdbTypeSymId type)
clang::DeclContext * GetOrCreateClangDeclContextForUid (PdbSymUid uid)
CompilerDecl ToCompilerDecl (clang::Decl *decl)
CompilerType ToCompilerType (clang::QualType qt)
CompilerDeclContext ToCompilerDeclContext (clang::DeclContext *context)
clang::QualType FromCompilerType (CompilerType ct)
clang::Decl * FromCompilerDecl (CompilerDecl decl)
clang::DeclContext * FromCompilerDeclContext (CompilerDeclContext context)
bool CompleteTagDecl (clang::TagDecl &tag)
TypeSystemClang & clang ()
ClangASTImporter & GetClangASTImporter ()
Public Member Functions inherited from lldb_private::npdb::PdbAstBuilder
virtual ~PdbAstBuilder ()=default
Private Types
using TypeIndex = llvm::codeview::TypeIndex
using NamespaceSet = llvm::DenseSet<clang::NamespaceDecl *>
Private Member Functions
CompilerDeclContext GetTranslationUnitDecl ()
clang::DeclContext * GetParentClangDeclContext (PdbSymUid uid)
clang::Decl * TryGetDecl (PdbSymUid uid) const
clang::FunctionDecl * GetOrCreateFunctionDecl (PdbCompilandSymId func_id)
clang::FunctionDecl * GetOrCreateInlinedFunctionDecl (PdbCompilandSymId inlinesite_id)
clang::BlockDecl * GetOrCreateBlockDecl (PdbCompilandSymId block_id)
clang::VarDecl * GetOrCreateVariableDecl (PdbCompilandSymId scope_id, PdbCompilandSymId var_id)
clang::VarDecl * GetOrCreateVariableDecl (PdbGlobalSymId var_id)
clang::QualType CreatePointerType (const llvm::codeview::PointerRecord &pointer)
clang::QualType CreateModifierType (const llvm::codeview::ModifierRecord &modifier)
clang::QualType CreateArrayType (const llvm::codeview::ArrayRecord &array)
clang::QualType CreateRecordType (PdbTypeSymId id, const llvm::codeview::TagRecord &record)
clang::QualType CreateEnumType (PdbTypeSymId id, const llvm::codeview::EnumRecord &record)
clang::QualType CreateFunctionType (TypeIndex args_type_idx, TypeIndex return_type_idx, llvm::codeview::CallingConvention calling_convention)
clang::QualType CreateType (PdbTypeSymId type)
void CreateFunctionParameters (PdbCompilandSymId func_id, clang::FunctionDecl &function_decl, uint32_t param_count)
clang::Decl * GetOrCreateSymbolForId (PdbCompilandSymId id)
clang::VarDecl * CreateVariableDecl (PdbSymUid uid, llvm::codeview::CVSymbol sym, clang::DeclContext &scope)
clang::NamespaceDecl * GetOrCreateNamespaceDecl (const char *name, clang::DeclContext &context)
clang::FunctionDecl * CreateFunctionDeclFromId (PdbTypeSymId func_tid, PdbCompilandSymId func_sid)
clang::FunctionDecl * CreateFunctionDecl (PdbCompilandSymId func_id, llvm::StringRef func_name, TypeIndex func_ti, CompilerType func_ct, uint32_t param_count, clang::StorageClass func_storage, bool is_inline, clang::DeclContext *parent)
void ParseNamespace (clang::DeclContext &parent)
void ParseAllTypes ()
void ParseAllFunctionsAndNonLocalVars ()
void ParseDeclsForSimpleContext (clang::DeclContext &context)
void ParseBlockChildren (PdbCompilandSymId block_id)
std::pair< clang::DeclContext *, std::string > CreateDeclInfoForType (const llvm::codeview::TagRecord &record, TypeIndex ti)
std::pair< clang::DeclContext *, std::string > CreateDeclInfoForUndecoratedName (llvm::StringRef uname)
clang::QualType CreateSimpleType (TypeIndex ti)
Private Attributes
TypeSystemClang & m_clang
ClangASTImporter m_importer
llvm::once_flag m_parse_functions_and_non_local_vars
llvm::once_flag m_parse_all_types
llvm::DenseMap< clang::Decl *, DeclStatus > m_decl_to_status
llvm::DenseMap< lldb::user_id_t, clang::Decl * > m_uid_to_decl
llvm::DenseMap< lldb::user_id_t, clang::QualType > m_uid_to_type
llvm::DenseMap< lldb::opaque_compiler_type_t, llvm::SmallSet< std::pair< llvm::StringRef, CompilerType >, 8 > > m_cxx_record_map
NamespaceSet m_parsed_namespaces
NamespaceSet m_known_namespaces
llvm::DenseMap< clang::DeclContext *, NamespaceSet > m_parent_to_namespaces
Detailed Description
Definition at line 53 of file PdbAstBuilderClang.h.
Member Typedef Documentation
NamespaceSet
using lldb_private::npdb::PdbAstBuilderClang::NamespaceSet = llvm::DenseSet<clang::NamespaceDecl *> private
Definition at line 169 of file PdbAstBuilderClang.h.
TypeIndex
using lldb_private::npdb::PdbAstBuilderClang::TypeIndex = llvm::codeview::TypeIndex private
Definition at line 110 of file PdbAstBuilderClang.h.
Constructor & Destructor Documentation
PdbAstBuilderClang()
PdbAstBuilderClang::PdbAstBuilderClang (TypeSystemClang & clang)
Definition at line 164 of file PdbAstBuilderClang.cpp.
References m_clang.
Member Function Documentation
clang()
TypeSystemClang & lldb_private::npdb::PdbAstBuilderClang::clang () inline
Definition at line 93 of file PdbAstBuilderClang.h.
References m_clang.
CompleteTagDecl()
bool PdbAstBuilderClang::CompleteTagDecl (clang::TagDecl & tag)
Definition at line 450 of file PdbAstBuilderClang.cpp.
References lldb_private::npdb::PdbSymUid::asTypeSym(), lldb_private::npdb::UdtRecordCompleter::complete(), error(), lldb_private::npdb::GetBestPossibleDecl(), lldb_private::npdb::GetFieldListIndex(), lldb_private::npdb::SymbolFileNativePDB::GetIndex(), lldb_private::npdb::PdbTypeSymId::index, lldb_private::npdb::IsForwardRefUdt(), lldb_private::npdb::IsTagRecord(), lldbassert, lldb_private::npdb::LookThroughModifierRecord(), m_clang, m_cxx_record_map, m_decl_to_status, lldb_private::npdb::DeclStatus::resolved, lldb_private::TypeSystemClang::SetHasExternalStorage(), ToCompilerType(), lldb_private::npdb::PdbIndex::tpi(), and lldb_private::npdb::DeclStatus::uid.
Referenced by CompleteType(), and ParseDeclsForSimpleContext().
CompleteType()
bool PdbAstBuilderClang::CompleteType (CompilerType ct) override virtual
Implements lldb_private::npdb::PdbAstBuilder.
Definition at line 432 of file PdbAstBuilderClang.cpp.
References CompleteTagDecl(), lldb_private::ClangASTImporter::CompleteType(), FromCompilerType(), and GetClangASTImporter().
CreateArrayType()
clang::QualType PdbAstBuilderClang::CreateArrayType (const llvm::codeview::ArrayRecord & array) private
Definition at line 1222 of file PdbAstBuilderClang.cpp.
References lldb_private::CompilerType::GetOpaqueQualType(), GetOrCreateClangType(), lldb_private::npdb::GetSizeOfType(), m_clang, lldb_private::TypeSystemClang::RequireCompleteType(), ToCompilerType(), and lldb_private::npdb::PdbIndex::tpi().
Referenced by CreateType().
CreateDeclInfoForType()
std::pair< clang::DeclContext *, std::string > PdbAstBuilderClang::CreateDeclInfoForType (const llvm::codeview::TagRecord & record, TypeIndex ti) private
Definition at line 172 of file PdbAstBuilderClang.cpp.
References AnyScopesHaveTemplateParams(), CreateDeclInfoForUndecoratedName(), GetOrCreateClangType(), GetOrCreateNamespaceDecl(), and m_clang.
Referenced by CreateEnumType(), CreateRecordType(), and ParseNamespace().
CreateDeclInfoForUndecoratedName()
std::pair< clang::DeclContext *, std::string > PdbAstBuilderClang::CreateDeclInfoForUndecoratedName (llvm::StringRef uname) private
Definition at line 328 of file PdbAstBuilderClang.cpp.
References FromCompilerDeclContext(), GetOrCreateClangType(), GetOrCreateNamespaceDecl(), MSVCUndecoratedNameParser::GetSpecifiers(), GetTranslationUnitDecl(), m_clang, and lldb_private::npdb::PdbIndex::tpi().
Referenced by CreateDeclInfoForType(), and GetParentClangDeclContext().
CreateEnumType()
clang::QualType PdbAstBuilderClang::CreateEnumType (PdbTypeSymId id, const llvm::codeview::EnumRecord & record) private
Definition at line 1199 of file PdbAstBuilderClang.cpp.
References CreateDeclInfoForType(), lldb_private::CompilerType::GetOpaqueQualType(), GetOrCreateClangType(), m_clang, lldb_private::TypeSystemClang::SetHasExternalStorage(), lldb_private::TypeSystemClang::StartTagDeclarationDefinition(), and ToCompilerType().
Referenced by CreateType().
CreateFunctionDecl()
clang::FunctionDecl * PdbAstBuilderClang::CreateFunctionDecl (PdbCompilandSymId func_id, llvm::StringRef func_name, TypeIndex func_ti, CompilerType func_ct, uint32_t param_count, clang::StorageClass func_storage, bool is_inline, clang::DeclContext * parent) private
Definition at line 880 of file PdbAstBuilderClang.cpp.
References lldb_private::npdb::CVTagRecord::asTag(), lldb_private::npdb::CVTagRecord::create(), CreateFunctionParameters(), lldb::eAccessPublic, error(), lldb_private::CompilerType::GetOpaqueQualType(), m_clang, m_cxx_record_map, ToCompilerType(), and lldb_private::npdb::PdbIndex::tpi().
Referenced by CreateFunctionDeclFromId(), and GetOrCreateFunctionDecl().
CreateFunctionDeclFromId()
clang::FunctionDecl * PdbAstBuilderClang::CreateFunctionDeclFromId (PdbTypeSymId func_tid, PdbCompilandSymId func_sid) private
Definition at line 993 of file PdbAstBuilderClang.cpp.
References CreateFunctionDecl(), FromCompilerDeclContext(), GetOrCreateClangDeclContextForUid(), GetOrCreateClangType(), GetOrCreateNamespaceDecl(), GetTranslationUnitDecl(), lldb_private::npdb::PdbTypeSymId::index, lldb_private::npdb::PdbIndex::ipi(), lldb_private::npdb::PdbTypeSymId::is_ipi, lldbassert, m_clang, and ToCompilerType().
Referenced by GetOrCreateInlinedFunctionDecl().
CreateFunctionParameters()
void PdbAstBuilderClang::CreateFunctionParameters (PdbCompilandSymId func_id, clang::FunctionDecl & function_decl, uint32_t param_count) private
Definition at line 1124 of file PdbAstBuilderClang.cpp.
References lldb_private::npdb::PdbIndex::compilands(), lldb_private::npdb::CompileUnitIndex::GetCompiland(), GetOrCreateClangType(), lldbassert, m_clang, lldb_private::npdb::CompilandIndexItem::m_debug_stream, m_uid_to_decl, lldb_private::npdb::PdbCompilandSymId::modi, lldb_private::npdb::PdbCompilandSymId::offset, and lldb_private::npdb::toOpaqueUid().
Referenced by CreateFunctionDecl().
CreateFunctionType()
clang::QualType PdbAstBuilderClang::CreateFunctionType (TypeIndex args_type_idx, TypeIndex return_type_idx, llvm::codeview::CallingConvention calling_convention) private
Definition at line 1239 of file PdbAstBuilderClang.cpp.
References lldb_private::CompilerType::GetOpaqueQualType(), GetOrCreateClangType(), IsCVarArgsFunction(), m_clang, ToCompilerType(), lldb_private::npdb::PdbIndex::tpi(), and TranslateCallingConvention().
Referenced by CreateType().
CreateModifierType()
clang::QualType PdbAstBuilderClang::CreateModifierType (const llvm::codeview::ModifierRecord & modifier) private
Definition at line 605 of file PdbAstBuilderClang.cpp.
References GetOrCreateClangType().
Referenced by CreateType().
CreatePointerType()
clang::QualType PdbAstBuilderClang::CreatePointerType (const llvm::codeview::PointerRecord & pointer) private
Definition at line 532 of file PdbAstBuilderClang.cpp.
References GetOrCreateClangType(), and m_clang.
Referenced by CreateType().
CreateRecordType()
clang::QualType PdbAstBuilderClang::CreateRecordType (PdbTypeSymId id, const llvm::codeview::TagRecord & record) private
Definition at line 618 of file PdbAstBuilderClang.cpp.
References CreateDeclInfoForType(), lldb::eAccessPrivate, lldb::eAccessPublic, lldb::eLanguageTypeC_plus_plus, lldb_private::CompilerType::GetOpaqueQualType(), lldb_private::CompilerType::IsValid(), lldbassert, m_clang, lldb_private::TypeSystemClang::SetHasExternalStorage(), lldb_private::ClangASTMetadata::SetIsDynamicCXXType(), lldb_private::ClangASTMetadata::SetUserID(), lldb_private::TypeSystemClang::StartTagDeclarationDefinition(), lldb_private::npdb::toOpaqueUid(), and TranslateUdtKind().
Referenced by CreateType().
CreateSimpleType()
clang::QualType PdbAstBuilderClang::CreateSimpleType (TypeIndex ti) private
Definition at line 510 of file PdbAstBuilderClang.cpp.
References lldb::eBasicTypeInvalid, lldb::eBasicTypeNullPtr, GetBasicType(), lldb_private::npdb::GetCompilerTypeForSimpleKind(), GetOrCreateClangType(), and m_clang.
Referenced by CreateType().
CreateType()
clang::QualType PdbAstBuilderClang::CreateType (PdbTypeSymId type) private
Definition at line 776 of file PdbAstBuilderClang.cpp.
References lldb_private::npdb::CVTagRecord::asClass(), lldb_private::npdb::CVTagRecord::asEnum(), lldb_private::npdb::CVTagRecord::asUnion(), lldb_private::npdb::CVTagRecord::create(), CreateArrayType(), CreateEnumType(), CreateFunctionType(), CreateModifierType(), CreatePointerType(), CreateRecordType(), CreateSimpleType(), lldb_private::npdb::CVTagRecord::Enum, lldb_private::npdb::PdbTypeSymId::index, lldb_private::npdb::IsTagRecord(), lldb_private::npdb::CVTagRecord::kind(), m_clang, lldb_private::npdb::PdbIndex::tpi(), and lldb_private::npdb::CVTagRecord::Union.
Referenced by GetOrCreateClangType().
CreateVariableDecl()
clang::VarDecl * PdbAstBuilderClang::CreateVariableDecl (PdbSymUid uid, llvm::codeview::CVSymbol sym, clang::DeclContext & scope) private
Definition at line 691 of file PdbAstBuilderClang.cpp.
References GetOrCreateClangType(), lldb_private::npdb::GetVariableNameInfo(), m_clang, m_decl_to_status, m_uid_to_decl, lldb_private::npdb::VariableInfo::name, lldb_private::npdb::DeclStatus::resolved, lldb_private::npdb::toOpaqueUid(), lldb_private::npdb::VariableInfo::type, and lldb_private::npdb::DeclStatus::uid.
Referenced by GetOrCreateVariableDecl(), and GetOrCreateVariableDecl().
Dump()
void PdbAstBuilderClang::Dump (Stream & stream, llvm::StringRef filter, bool show_color) override virtual
Implements lldb_private::npdb::PdbAstBuilder.
Definition at line 1520 of file PdbAstBuilderClang.cpp.
References lldb_private::Stream::AsRawOstream(), and m_clang.
EnsureBlock()
void PdbAstBuilderClang::EnsureBlock (PdbCompilandSymId block_id) override virtual
Implements lldb_private::npdb::PdbAstBuilder.
Definition at line 1111 of file PdbAstBuilderClang.cpp.
References GetOrCreateBlockDecl().
EnsureFunction()
void PdbAstBuilderClang::EnsureFunction (PdbCompilandSymId func_id) override virtual
Implements lldb_private::npdb::PdbAstBuilder.
Definition at line 1102 of file PdbAstBuilderClang.cpp.
References GetOrCreateFunctionDecl().
EnsureInlinedFunction()
void PdbAstBuilderClang::EnsureInlinedFunction (PdbCompilandSymId inlinesite_id) override virtual
Implements lldb_private::npdb::PdbAstBuilder.
Definition at line 1106 of file PdbAstBuilderClang.cpp.
References GetOrCreateInlinedFunctionDecl().
EnsureVariable() [1/2]
void PdbAstBuilderClang::EnsureVariable (PdbCompilandSymId scope_id, PdbCompilandSymId var_id) override virtual
Implements lldb_private::npdb::PdbAstBuilder.
Definition at line 1115 of file PdbAstBuilderClang.cpp.
References GetOrCreateVariableDecl().
EnsureVariable() [2/2]
void PdbAstBuilderClang::EnsureVariable (PdbGlobalSymId var_id) override virtual
Implements lldb_private::npdb::PdbAstBuilder.
Definition at line 1120 of file PdbAstBuilderClang.cpp.
References GetOrCreateVariableDecl().
FindNamespaceDecl()
CompilerDeclContext PdbAstBuilderClang::FindNamespaceDecl (CompilerDeclContext parent_ctx, llvm::StringRef name) override virtual
Implements lldb_private::npdb::PdbAstBuilder.
Definition at line 1526 of file PdbAstBuilderClang.cpp.
References FindNamespaceDecl(), FromCompilerDeclContext(), m_known_namespaces, m_parent_to_namespaces, and ToCompilerDeclContext().
Referenced by FindNamespaceDecl().
FromCompilerDecl()
clang::Decl * PdbAstBuilderClang::FromCompilerDecl (CompilerDecl decl)
Definition at line 1509 of file PdbAstBuilderClang.cpp.
References lldb_private::ClangUtil::GetDecl(), and lldb_private::CompilerDecl::GetTypeSystem().
Referenced by GetOrCreateClangDeclContextForUid().
FromCompilerDeclContext()
clang::DeclContext * PdbAstBuilderClang::FromCompilerDeclContext (CompilerDeclContext context)
Definition at line 1516 of file PdbAstBuilderClang.cpp.
References lldb_private::CompilerDeclContext::GetOpaqueDeclContext().
Referenced by CreateDeclInfoForUndecoratedName(), CreateFunctionDeclFromId(), FindNamespaceDecl(), GetOrCreateClangDeclContextForUid(), GetOrCreateVariableDecl(), GetParentClangDeclContext(), and ParseDeclsForContext().
FromCompilerType()
clang::QualType PdbAstBuilderClang::FromCompilerType (CompilerType ct)
Definition at line 1500 of file PdbAstBuilderClang.cpp.
References lldb_private::ClangUtil::GetQualType().
Referenced by CompleteType().
GetBasicType()
clang::QualType PdbAstBuilderClang::GetBasicType (lldb::BasicType type)
Definition at line 771 of file PdbAstBuilderClang.cpp.
References lldb_private::CompilerType::GetOpaqueQualType(), and m_clang.
Referenced by CreateSimpleType().
GetClangASTImporter()
ClangASTImporter & lldb_private::npdb::PdbAstBuilderClang::GetClangASTImporter () inline
Definition at line 94 of file PdbAstBuilderClang.h.
References m_importer.
Referenced by CompleteType().
GetOrCreateBlockDecl()
clang::BlockDecl * PdbAstBuilderClang::GetOrCreateBlockDecl (PdbCompilandSymId block_id) private
Definition at line 672 of file PdbAstBuilderClang.cpp.
References GetParentClangDeclContext(), m_clang, m_decl_to_status, m_uid_to_decl, lldb_private::npdb::DeclStatus::resolved, lldb_private::npdb::toOpaqueUid(), TryGetDecl(), and lldb_private::npdb::DeclStatus::uid.
Referenced by EnsureBlock(), and GetOrCreateSymbolForId().
GetOrCreateClangDeclContextForUid()
clang::DeclContext * PdbAstBuilderClang::GetOrCreateClangDeclContextForUid (PdbSymUid uid)
Definition at line 310 of file PdbAstBuilderClang.cpp.
References lldb_private::npdb::PdbSymUid::asCompilandSym(), lldb_private::npdb::CompilandSym, FromCompilerDecl(), FromCompilerDeclContext(), GetOrCreateDeclForUid(), GetTranslationUnitDecl(), lldb_private::npdb::PdbSymUid::kind(), and lldb_private::npdb::PdbCompilandSymId::offset.
Referenced by CreateFunctionDeclFromId(), GetOrCreateDeclContextForUid(), GetOrCreateVariableDecl(), and GetParentClangDeclContext().
GetOrCreateClangType()
clang::QualType PdbAstBuilderClang::GetOrCreateClangType (PdbTypeSymId type)
Definition at line 830 of file PdbAstBuilderClang.cpp.
References CreateType(), lldb_private::npdb::GetBestPossibleDecl(), GetOrCreateClangType(), lldb_private::npdb::PdbTypeSymId::index, lldb_private::npdb::IsTagRecord(), lldbassert, m_clang, m_decl_to_status, m_uid_to_type, lldb_private::npdb::DeclStatus::resolved, lldb_private::npdb::toOpaqueUid(), lldb_private::npdb::PdbIndex::tpi(), and lldb_private::npdb::DeclStatus::uid.
Referenced by CreateArrayType(), CreateDeclInfoForType(), CreateDeclInfoForUndecoratedName(), CreateEnumType(), CreateFunctionDeclFromId(), CreateFunctionParameters(), CreateFunctionType(), CreateModifierType(), CreatePointerType(), CreateSimpleType(), CreateVariableDecl(), GetOrCreateClangType(), GetOrCreateDeclForUid(), GetOrCreateFunctionDecl(), GetOrCreateType(), GetOrCreateTypedefType(), ParseAllTypes(), and ParseNamespace().
GetOrCreateDeclContextForUid()
CompilerDeclContext PdbAstBuilderClang::GetOrCreateDeclContextForUid (PdbSymUid uid) override virtual
Implements lldb_private::npdb::PdbAstBuilder.
Definition at line 323 of file PdbAstBuilderClang.cpp.
References GetOrCreateClangDeclContextForUid(), and ToCompilerDeclContext().
GetOrCreateDeclForUid()
CompilerDecl PdbAstBuilderClang::GetOrCreateDeclForUid (PdbSymUid uid) override virtual
Implements lldb_private::npdb::PdbAstBuilder.
Definition at line 280 of file PdbAstBuilderClang.cpp.
References lldb_private::npdb::PdbSymUid::asCompilandSym(), lldb_private::npdb::PdbSymUid::asTypeSym(), lldb_private::npdb::CompilandSym, GetOrCreateClangType(), GetOrCreateSymbolForId(), lldb_private::npdb::PdbSymUid::kind(), m_uid_to_decl, ToCompilerDecl(), lldb_private::npdb::toOpaqueUid(), TryGetDecl(), and lldb_private::npdb::Type.
Referenced by GetOrCreateClangDeclContextForUid().
GetOrCreateFunctionDecl()
clang::FunctionDecl * PdbAstBuilderClang::GetOrCreateFunctionDecl (PdbCompilandSymId func_id) private
Definition at line 1048 of file PdbAstBuilderClang.cpp.
References CreateFunctionDecl(), GetOrCreateClangType(), GetParentClangDeclContext(), lldbassert, m_clang, m_decl_to_status, m_uid_to_decl, lldb_private::npdb::PdbIndex::ReadSymbolRecord(), lldb_private::npdb::DeclStatus::resolved, ToCompilerType(), lldb_private::npdb::toOpaqueUid(), TryGetDecl(), and lldb_private::npdb::DeclStatus::uid.
Referenced by EnsureFunction(), GetOrCreateSymbolForId(), and ParseAllFunctionsAndNonLocalVars().
GetOrCreateInlinedFunctionDecl()
clang::FunctionDecl * PdbAstBuilderClang::GetOrCreateInlinedFunctionDecl (PdbCompilandSymId inlinesite_id) private
Definition at line 954 of file PdbAstBuilderClang.cpp.
References lldb_private::npdb::PdbIndex::compilands(), CreateFunctionDeclFromId(), lldb_private::npdb::CompileUnitIndex::GetCompiland(), lldbassert, m_clang, lldb_private::npdb::CompilandIndexItem::m_debug_stream, m_decl_to_status, m_uid_to_decl, lldb_private::npdb::PdbCompilandSymId::modi, lldb_private::npdb::PdbCompilandSymId::offset, lldb_private::npdb::DeclStatus::resolved, lldb_private::npdb::toOpaqueUid(), TryGetDecl(), and lldb_private::npdb::DeclStatus::uid.
Referenced by EnsureInlinedFunction(), and GetOrCreateSymbolForId().
GetOrCreateNamespaceDecl()
clang::NamespaceDecl * PdbAstBuilderClang::GetOrCreateNamespaceDecl (const char * name, clang::DeclContext & context) private
Definition at line 661 of file PdbAstBuilderClang.cpp.
References IsAnonymousNamespaceName(), m_clang, m_known_namespaces, and m_parent_to_namespaces.
Referenced by CreateDeclInfoForType(), CreateDeclInfoForUndecoratedName(), and CreateFunctionDeclFromId().
GetOrCreateSymbolForId()
clang::Decl * PdbAstBuilderClang::GetOrCreateSymbolForId (PdbCompilandSymId id) private
Definition at line 245 of file PdbAstBuilderClang.cpp.
References lldb_private::npdb::PdbSymUid::asCompilandSym(), GetOrCreateBlockDecl(), GetOrCreateFunctionDecl(), GetOrCreateInlinedFunctionDecl(), GetOrCreateVariableDecl(), GetParentClangDeclContext(), isLocalVariableType(), m_clang, m_decl_to_status, and lldb_private::npdb::PdbIndex::ReadSymbolRecord().
Referenced by GetOrCreateDeclForUid(), and ParseBlockChildren().
GetOrCreateType()
CompilerType PdbAstBuilderClang::GetOrCreateType (PdbTypeSymId type) override virtual
Implements lldb_private::npdb::PdbAstBuilder.
Definition at line 873 of file PdbAstBuilderClang.cpp.
References GetOrCreateClangType(), and ToCompilerType().
GetOrCreateTypedefType()
CompilerType PdbAstBuilderClang::GetOrCreateTypedefType (PdbGlobalSymId id) override virtual
Implements lldb_private::npdb::PdbAstBuilder.
Definition at line 739 of file PdbAstBuilderClang.cpp.
References lldb_private::CompilerType::CreateTypedef(), lldb_private::npdb::DropNameScope(), GetOrCreateClangType(), GetParentClangDeclContext(), lldbassert, m_clang, m_decl_to_status, lldb_private::npdb::PdbIndex::ReadSymbolRecord(), lldb_private::npdb::DeclStatus::resolved, ToCompilerDeclContext(), ToCompilerType(), lldb_private::npdb::toOpaqueUid(), TryGetDecl(), and lldb_private::npdb::DeclStatus::uid.
GetOrCreateVariableDecl() [1/2]
clang::VarDecl * PdbAstBuilderClang::GetOrCreateVariableDecl (PdbCompilandSymId scope_id, PdbCompilandSymId var_id) private
Definition at line 710 of file PdbAstBuilderClang.cpp.
References CreateVariableDecl(), GetOrCreateClangDeclContextForUid(), m_clang, lldb_private::npdb::PdbIndex::ReadSymbolRecord(), and TryGetDecl().
Referenced by EnsureVariable(), EnsureVariable(), GetOrCreateSymbolForId(), and ParseAllFunctionsAndNonLocalVars().
GetOrCreateVariableDecl() [2/2]
clang::VarDecl * PdbAstBuilderClang::GetOrCreateVariableDecl (PdbGlobalSymId var_id) private
Definition at line 727 of file PdbAstBuilderClang.cpp.
References CreateVariableDecl(), FromCompilerDeclContext(), GetTranslationUnitDecl(), m_clang, lldb_private::npdb::PdbIndex::ReadSymbolRecord(), and TryGetDecl().
GetParentClangDeclContext()
clang::DeclContext * PdbAstBuilderClang::GetParentClangDeclContext (PdbSymUid uid) private
Definition at line 365 of file PdbAstBuilderClang.cpp.
References lldb_private::npdb::PdbSymUid::asCompilandSym(), lldb_private::npdb::PdbSymUid::asGlobalSym(), lldb_private::npdb::PdbSymUid::asTypeSym(), lldb_private::npdb::CompilandSym, CreateDeclInfoForUndecoratedName(), lldb_private::npdb::FieldListMember, FromCompilerDeclContext(), GetOrCreateClangDeclContextForUid(), GetParentClangDeclContext(), GetTranslationUnitDecl(), lldb_private::npdb::GlobalSym, lldb_private::npdb::PdbTypeSymId::index, lldb_private::npdb::PdbSymUid::kind(), m_clang, lldb_private::npdb::PdbIndex::ReadSymbolRecord(), and lldb_private::npdb::Type.
Referenced by GetOrCreateBlockDecl(), GetOrCreateFunctionDecl(), GetOrCreateSymbolForId(), GetOrCreateTypedefType(), GetParentClangDeclContext(), and GetParentDeclContext().
GetParentDeclContext()
CompilerDeclContext PdbAstBuilderClang::GetParentDeclContext (PdbSymUid uid) override virtual
Implements lldb_private::npdb::PdbAstBuilder.
Definition at line 428 of file PdbAstBuilderClang.cpp.
References GetParentClangDeclContext(), and ToCompilerDeclContext().
GetTranslationUnitDecl()
lldb_private::CompilerDeclContext PdbAstBuilderClang::GetTranslationUnitDecl () private
Definition at line 167 of file PdbAstBuilderClang.cpp.
References m_clang, and ToCompilerDeclContext().
Referenced by CreateDeclInfoForUndecoratedName(), CreateFunctionDeclFromId(), GetOrCreateClangDeclContextForUid(), GetOrCreateVariableDecl(), and GetParentClangDeclContext().
ParseAllFunctionsAndNonLocalVars()
void PdbAstBuilderClang::ParseAllFunctionsAndNonLocalVars () private
Definition at line 1352 of file PdbAstBuilderClang.cpp.
References lldb_private::npdb::PdbIndex::compilands(), lldb_private::npdb::PdbIndex::dbi(), lldb_private::npdb::CompileUnitIndex::GetOrCreateCompiland(), GetOrCreateFunctionDecl(), GetOrCreateVariableDecl(), m_clang, lldb_private::npdb::CompilandIndexItem::m_debug_stream, and m_parse_functions_and_non_local_vars.
Referenced by ParseDeclsForContext(), and ParseNamespace().
ParseAllTypes()
void PdbAstBuilderClang::ParseAllTypes () private
Definition at line 1334 of file PdbAstBuilderClang.cpp.
References GetOrCreateClangType(), lldb_private::npdb::IsTagRecord(), m_clang, m_parse_all_types, and lldb_private::npdb::PdbIndex::tpi().
Referenced by ParseDeclsForContext().
ParseBlockChildren()
void PdbAstBuilderClang::ParseBlockChildren (PdbCompilandSymId block_id) private
Definition at line 1413 of file PdbAstBuilderClang.cpp.
References lldb_private::npdb::PdbIndex::compilands(), lldb_private::npdb::CompileUnitIndex::GetOrCreateCompiland(), GetOrCreateSymbolForId(), lldbassert, m_clang, lldb_private::npdb::CompilandIndexItem::m_debug_stream, m_uid_to_decl, lldb_private::npdb::PdbCompilandSymId::modi, lldb_private::npdb::PdbCompilandSymId::offset, ParseBlockChildren(), lldb_private::npdb::PdbIndex::ReadSymbolRecord(), skipFunctionParameters(), and lldb_private::npdb::toOpaqueUid().
Referenced by ParseBlockChildren(), and ParseDeclsForSimpleContext().
ParseDeclsForContext()
void PdbAstBuilderClang::ParseDeclsForContext (CompilerDeclContext context) override virtual
Implements lldb_private::npdb::PdbAstBuilder.
Definition at line 1464 of file PdbAstBuilderClang.cpp.
References FromCompilerDeclContext(), isBlockDecl(), isFunctionDecl(), isTagDecl(), ParseAllFunctionsAndNonLocalVars(), ParseAllTypes(), ParseDeclsForSimpleContext(), and ParseNamespace().
ParseDeclsForSimpleContext()
void PdbAstBuilderClang::ParseDeclsForSimpleContext (clang::DeclContext & context) private
Definition at line 1444 of file PdbAstBuilderClang.cpp.
References lldb_private::npdb::PdbSymUid::asCompilandSym(), CompleteTagDecl(), isBlockDecl(), isFunctionDecl(), lldbassert, m_decl_to_status, and ParseBlockChildren().
Referenced by ParseDeclsForContext().
ParseNamespace()
void PdbAstBuilderClang::ParseNamespace (clang::DeclContext & parent) private
Definition at line 1295 of file PdbAstBuilderClang.cpp.
References lldb_private::npdb::CVTagRecord::asTag(), lldb_private::npdb::CVTagRecord::create(), CreateDeclInfoForType(), GetOrCreateClangType(), lldb_private::npdb::PdbTypeSymId::index, lldb_private::npdb::IsTagRecord(), m_clang, m_parsed_namespaces, ParseAllFunctionsAndNonLocalVars(), and lldb_private::npdb::PdbIndex::tpi().
Referenced by ParseDeclsForContext().
ToCompilerDecl()
CompilerDecl PdbAstBuilderClang::ToCompilerDecl (clang::Decl * decl)
Definition at line 1492 of file PdbAstBuilderClang.cpp.
References m_clang.
Referenced by GetOrCreateDeclForUid().
ToCompilerDeclContext()
CompilerDeclContext PdbAstBuilderClang::ToCompilerDeclContext (clang::DeclContext * context)
Definition at line 1505 of file PdbAstBuilderClang.cpp.
References m_clang.
Referenced by FindNamespaceDecl(), GetOrCreateDeclContextForUid(), GetOrCreateTypedefType(), GetParentDeclContext(), and GetTranslationUnitDecl().
ToCompilerType()
CompilerType PdbAstBuilderClang::ToCompilerType (clang::QualType qt)
Definition at line 1496 of file PdbAstBuilderClang.cpp.
References m_clang.
Referenced by CompleteTagDecl(), CreateArrayType(), CreateEnumType(), CreateFunctionDecl(), CreateFunctionDeclFromId(), CreateFunctionType(), GetOrCreateFunctionDecl(), GetOrCreateType(), and GetOrCreateTypedefType().
TryGetDecl()
clang::Decl * PdbAstBuilderClang::TryGetDecl (PdbSymUid uid) const private
Definition at line 653 of file PdbAstBuilderClang.cpp.
References m_uid_to_decl, and lldb_private::npdb::toOpaqueUid().
Referenced by GetOrCreateBlockDecl(), GetOrCreateDeclForUid(), GetOrCreateFunctionDecl(), GetOrCreateInlinedFunctionDecl(), GetOrCreateTypedefType(), GetOrCreateVariableDecl(), and GetOrCreateVariableDecl().
Member Data Documentation
m_clang
TypeSystemClang& lldb_private::npdb::PdbAstBuilderClang::m_clang private
Definition at line 154 of file PdbAstBuilderClang.h.
Referenced by clang(), CompleteTagDecl(), CreateArrayType(), CreateDeclInfoForType(), CreateDeclInfoForUndecoratedName(), CreateEnumType(), CreateFunctionDecl(), CreateFunctionDeclFromId(), CreateFunctionParameters(), CreateFunctionType(), CreatePointerType(), CreateRecordType(), CreateSimpleType(), CreateType(), CreateVariableDecl(), Dump(), GetBasicType(), GetOrCreateBlockDecl(), GetOrCreateClangType(), GetOrCreateFunctionDecl(), GetOrCreateInlinedFunctionDecl(), GetOrCreateNamespaceDecl(), GetOrCreateSymbolForId(), GetOrCreateTypedefType(), GetOrCreateVariableDecl(), GetOrCreateVariableDecl(), GetParentClangDeclContext(), GetTranslationUnitDecl(), ParseAllFunctionsAndNonLocalVars(), ParseAllTypes(), ParseBlockChildren(), ParseNamespace(), PdbAstBuilderClang(), ToCompilerDecl(), ToCompilerDeclContext(), and ToCompilerType().
m_cxx_record_map
llvm::DenseMap<lldb::opaque_compiler_type_t, llvm::SmallSet<std::pair<llvm::StringRef, CompilerType>, 8> > lldb_private::npdb::PdbAstBuilderClang::m_cxx_record_map private
Definition at line 167 of file PdbAstBuilderClang.h.
Referenced by CompleteTagDecl(), and CreateFunctionDecl().
m_decl_to_status
llvm::DenseMap<clang::Decl *, DeclStatus> lldb_private::npdb::PdbAstBuilderClang::m_decl_to_status private
Definition at line 159 of file PdbAstBuilderClang.h.
Referenced by CompleteTagDecl(), CreateVariableDecl(), GetOrCreateBlockDecl(), GetOrCreateClangType(), GetOrCreateFunctionDecl(), GetOrCreateInlinedFunctionDecl(), GetOrCreateSymbolForId(), GetOrCreateTypedefType(), and ParseDeclsForSimpleContext().
m_importer
ClangASTImporter lldb_private::npdb::PdbAstBuilderClang::m_importer private
Definition at line 156 of file PdbAstBuilderClang.h.
Referenced by GetClangASTImporter().
m_known_namespaces
NamespaceSet lldb_private::npdb::PdbAstBuilderClang::m_known_namespaces private
Definition at line 175 of file PdbAstBuilderClang.h.
Referenced by FindNamespaceDecl(), and GetOrCreateNamespaceDecl().
m_parent_to_namespaces
llvm::DenseMap<clang::DeclContext *, NamespaceSet> lldb_private::npdb::PdbAstBuilderClang::m_parent_to_namespaces private
Definition at line 176 of file PdbAstBuilderClang.h.
Referenced by FindNamespaceDecl(), and GetOrCreateNamespaceDecl().
m_parse_all_types
llvm::once_flag lldb_private::npdb::PdbAstBuilderClang::m_parse_all_types private
Definition at line 158 of file PdbAstBuilderClang.h.
Referenced by ParseAllTypes().
m_parse_functions_and_non_local_vars
llvm::once_flag lldb_private::npdb::PdbAstBuilderClang::m_parse_functions_and_non_local_vars private
Definition at line 157 of file PdbAstBuilderClang.h.
Referenced by ParseAllFunctionsAndNonLocalVars().
m_parsed_namespaces
NamespaceSet lldb_private::npdb::PdbAstBuilderClang::m_parsed_namespaces private
Definition at line 172 of file PdbAstBuilderClang.h.
Referenced by ParseNamespace().
m_uid_to_decl
llvm::DenseMap<lldb::user_id_t, clang::Decl *> lldb_private::npdb::PdbAstBuilderClang::m_uid_to_decl private
Definition at line 160 of file PdbAstBuilderClang.h.
Referenced by CreateFunctionParameters(), CreateVariableDecl(), GetOrCreateBlockDecl(), GetOrCreateDeclForUid(), GetOrCreateFunctionDecl(), GetOrCreateInlinedFunctionDecl(), ParseBlockChildren(), and TryGetDecl().
m_uid_to_type
llvm::DenseMap<lldb::user_id_t, clang::QualType> lldb_private::npdb::PdbAstBuilderClang::m_uid_to_type private
Definition at line 161 of file PdbAstBuilderClang.h.
Referenced by GetOrCreateClangType().
The documentation for this class was generated from the following files:
PdbAstBuilderClang.h
PdbAstBuilderClang.cpp