LLDB: lldb_private::RegisterInfoAndSetInterface Class Reference
lldb_private::RegisterInfoAndSetInterface Class Reference abstract
#include <RegisterInfoAndSetInterface.h>
Public Member Functions
RegisterInfoAndSetInterface (const lldb_private::ArchSpec &target_arch)
virtual size_t GetFPRSize () const =0
virtual const lldb_private::RegisterSet * GetRegisterSet (size_t reg_set) const =0
virtual size_t GetRegisterSetCount () const =0
virtual size_t GetRegisterSetFromRegisterIndex (uint32_t reg_index) const =0
Public Member Functions inherited from lldb_private::RegisterInfoInterface
RegisterInfoInterface (const lldb_private::ArchSpec &target_arch)
virtual ~RegisterInfoInterface ()=default
virtual size_t GetGPRSize () const =0
virtual const lldb_private::RegisterInfo * GetRegisterInfo () const =0
virtual uint32_t GetRegisterCount () const =0
virtual uint32_t GetUserRegisterCount () const
const lldb_private::ArchSpec & GetTargetArchitecture () const
Detailed Description
Definition at line 20 of file RegisterInfoAndSetInterface.h.
Constructor & Destructor Documentation
RegisterInfoAndSetInterface()
lldb_private::RegisterInfoAndSetInterface::RegisterInfoAndSetInterface (const lldb_private::ArchSpec & target_arch) inline
Definition at line 22 of file RegisterInfoAndSetInterface.h.
References lldb_private::RegisterInfoInterface::RegisterInfoInterface().
Referenced by RegisterInfoPOSIX_arm::RegisterInfoPOSIX_arm(), RegisterInfoPOSIX_arm64::RegisterInfoPOSIX_arm64(), RegisterInfoPOSIX_loongarch64::RegisterInfoPOSIX_loongarch64(), RegisterInfoPOSIX_riscv32::RegisterInfoPOSIX_riscv32(), and RegisterInfoPOSIX_riscv64::RegisterInfoPOSIX_riscv64().
Member Function Documentation
GetFPRSize()
virtual size_t lldb_private::RegisterInfoAndSetInterface::GetFPRSize () const pure virtual
Implemented in RegisterInfoPOSIX_arm64, RegisterInfoPOSIX_arm, RegisterInfoPOSIX_loongarch64, RegisterInfoPOSIX_riscv32, and RegisterInfoPOSIX_riscv64.
GetRegisterSet()
virtual const lldb_private::RegisterSet * lldb_private::RegisterInfoAndSetInterface::GetRegisterSet (size_t reg_set) const pure virtual
Implemented in RegisterInfoPOSIX_arm64, RegisterInfoPOSIX_arm, RegisterInfoPOSIX_loongarch64, RegisterInfoPOSIX_riscv32, and RegisterInfoPOSIX_riscv64.
GetRegisterSetCount()
virtual size_t lldb_private::RegisterInfoAndSetInterface::GetRegisterSetCount () const pure virtual
Implemented in RegisterInfoPOSIX_arm64, RegisterInfoPOSIX_arm, RegisterInfoPOSIX_loongarch64, RegisterInfoPOSIX_riscv32, and RegisterInfoPOSIX_riscv64.
GetRegisterSetFromRegisterIndex()
virtual size_t lldb_private::RegisterInfoAndSetInterface::GetRegisterSetFromRegisterIndex (uint32_t reg_index) const pure virtual
Implemented in RegisterInfoPOSIX_arm64, RegisterInfoPOSIX_arm, RegisterInfoPOSIX_loongarch64, RegisterInfoPOSIX_riscv32, and RegisterInfoPOSIX_riscv64.
The documentation for this class was generated from the following file:
RegisterInfoAndSetInterface.h