LLDB: lldb_private::PipePosix Class Reference
lldb_private::PipePosix Class Reference
A posix-based implementation of Pipe, a class that abtracts unix style pipes.
#include "lldb/Host/posix/PipePosix.h"
Public Member Functions
PipePosix ()
PipePosix (lldb::pipe_t read, lldb::pipe_t write)
PipePosix (const PipePosix &)=delete
PipePosix (PipePosix &&pipe_posix)
PipePosix & operator= (const PipePosix &)=delete
PipePosix & operator= (PipePosix &&pipe_posix)
~PipePosix () override
Status CreateNew () override
Status CreateNew (llvm::StringRef name) override
Status CreateWithUniqueName (llvm::StringRef prefix, llvm::SmallVectorImpl< char > &name) override
Status OpenAsReader (llvm::StringRef name) override
llvm::Error OpenAsWriter (llvm::StringRef name, const Timeout< std::micro > &timeout) override
bool CanRead () const override
bool CanWrite () const override
lldb::pipe_t GetReadPipe () const override
lldb::pipe_t GetWritePipe () const override
int GetReadFileDescriptor () const override
int GetWriteFileDescriptor () const override
int ReleaseReadFileDescriptor () override
int ReleaseWriteFileDescriptor () override
void CloseReadFileDescriptor () override
void CloseWriteFileDescriptor () override
void Close () override
Status Delete (llvm::StringRef name) override
llvm::Expected< size_t > Write (const void *buf, size_t size, const Timeout< std::micro > &timeout=std::nullopt) override
llvm::Expected< size_t > Read (void *buf, size_t size, const Timeout< std::micro > &timeout=std::nullopt) override
Public Member Functions inherited from lldb_private::PipeBase
virtual ~PipeBase ()
Static Public Attributes
static int kInvalidDescriptor = -1
Private Member Functions
bool CanReadUnlocked () const
bool CanWriteUnlocked () const
int GetReadFileDescriptorUnlocked () const
int GetWriteFileDescriptorUnlocked () const
int ReleaseReadFileDescriptorUnlocked ()
int ReleaseWriteFileDescriptorUnlocked ()
void CloseReadFileDescriptorUnlocked ()
void CloseWriteFileDescriptorUnlocked ()
void CloseUnlocked ()
Private Attributes
int m_fds [2]
std::mutex m_read_mutex
Mutexes for m_fds;.
std::mutex m_write_mutex
Detailed Description
A posix-based implementation of Pipe, a class that abtracts unix style pipes.
A class that abstracts the LLDB core from host pipe functionality.
Definition at line 22 of file PipePosix.h.
Constructor & Destructor Documentation
PipePosix() [1/4]
PipePosix::PipePosix ()
Definition at line 58 of file PipePosix.cpp.
References kInvalidDescriptor, m_fds, and PipePosix().
Referenced by operator=(), operator=(), PipePosix(), PipePosix(), and PipePosix().
PipePosix() [2/4]
PipePosix::PipePosix (lldb::pipe_t read, lldb::pipe_t write)
Definition at line 61 of file PipePosix.cpp.
References m_fds.
PipePosix() [3/4]
lldb_private::PipePosix::PipePosix (const PipePosix &) delete
References PipePosix().
PipePosix() [4/4]
PipePosix::PipePosix (PipePosix && pipe_posix)
Definition at line 64 of file PipePosix.cpp.
References m_fds, PipePosix(), ReleaseReadFileDescriptor(), and ReleaseWriteFileDescriptor().
~PipePosix()
PipePosix::~PipePosix () override
Definition at line 80 of file PipePosix.cpp.
References Close().
Member Function Documentation
CanRead()
bool PipePosix::CanRead () const override virtual
Implements lldb_private::PipeBase.
Definition at line 257 of file PipePosix.cpp.
References CanReadUnlocked(), and m_read_mutex.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess().
CanReadUnlocked()
bool PipePosix::CanReadUnlocked () const private
Definition at line 262 of file PipePosix.cpp.
References kInvalidDescriptor, m_fds, and READ.
Referenced by CanRead(), CloseReadFileDescriptorUnlocked(), CreateNew(), CreateNew(), OpenAsReader(), OpenAsWriter(), and Read().
CanWrite()
bool PipePosix::CanWrite () const override virtual
Implements lldb_private::PipeBase.
Definition at line 266 of file PipePosix.cpp.
References CanWriteUnlocked(), and m_write_mutex.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess().
CanWriteUnlocked()
bool PipePosix::CanWriteUnlocked () const private
Definition at line 271 of file PipePosix.cpp.
References kInvalidDescriptor, m_fds, and WRITE.
Referenced by CanWrite(), CloseWriteFileDescriptorUnlocked(), CreateNew(), CreateNew(), OpenAsReader(), OpenAsWriter(), and Write().
Close()
void PipePosix::Close () override virtual
Implements lldb_private::PipeBase.
Definition at line 243 of file PipePosix.cpp.
References CloseUnlocked(), m_read_mutex, and m_write_mutex.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess(), and ~PipePosix().
CloseReadFileDescriptor()
void PipePosix::CloseReadFileDescriptor () override virtual
Implements lldb_private::PipeBase.
Definition at line 275 of file PipePosix.cpp.
References CloseReadFileDescriptorUnlocked(), and m_read_mutex.
Referenced by lldb_private::ProcessLauncherPosixFork::LaunchProcess().
CloseReadFileDescriptorUnlocked()
void PipePosix::CloseReadFileDescriptorUnlocked () private
Definition at line 279 of file PipePosix.cpp.
References CanReadUnlocked(), kInvalidDescriptor, m_fds, and READ.
Referenced by CloseReadFileDescriptor(), and CloseUnlocked().
CloseUnlocked()
void PipePosix::CloseUnlocked () private
Definition at line 248 of file PipePosix.cpp.
References CloseReadFileDescriptorUnlocked(), and CloseWriteFileDescriptorUnlocked().
Referenced by Close(), and CreateNew().
CloseWriteFileDescriptor()
void PipePosix::CloseWriteFileDescriptor () override virtual
Implements lldb_private::PipeBase.
Definition at line 286 of file PipePosix.cpp.
References CloseWriteFileDescriptorUnlocked(), and m_write_mutex.
Referenced by lldb_private::ProcessLauncherPosixFork::LaunchProcess(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess().
CloseWriteFileDescriptorUnlocked()
void PipePosix::CloseWriteFileDescriptorUnlocked () private
Definition at line 291 of file PipePosix.cpp.
References CanWriteUnlocked(), kInvalidDescriptor, m_fds, and WRITE.
Referenced by CloseUnlocked(), and CloseWriteFileDescriptor().
CreateNew() [1/2]
Status PipePosix::CreateNew () override virtual
Implements lldb_private::PipeBase.
Definition at line 82 of file PipePosix.cpp.
References CanReadUnlocked(), CanWriteUnlocked(), CloseUnlocked(), lldb::eErrorTypePOSIX, error(), lldb_private::Status::FromErrno(), kInvalidDescriptor, m_fds, m_read_mutex, m_write_mutex, READ, lldb_private::Status, and WRITE.
Referenced by CreateWithUniqueName(), lldb_private::ProcessLauncherPosixFork::LaunchProcess(), lldb_private::ScriptInterpreterIORedirect::ScriptInterpreterIORedirect(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess().
CreateNew() [2/2]
Status PipePosix::CreateNew (llvm::StringRef name) override virtual
Implements lldb_private::PipeBase.
Definition at line 110 of file PipePosix.cpp.
References CanReadUnlocked(), CanWriteUnlocked(), error(), lldb_private::Status::FromErrno(), lldb_private::Status::FromErrorString(), m_read_mutex, and m_write_mutex.
CreateWithUniqueName()
Status PipePosix::CreateWithUniqueName (llvm::StringRef prefix, llvm::SmallVectorImpl< char > & name) override virtual
Implements lldb_private::PipeBase.
Definition at line 121 of file PipePosix.cpp.
References lldb_private::FileSpec::AppendPathComponent(), CreateNew(), error(), and lldb_private::FileSpec::GetPath().
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess().
Delete()
Status PipePosix::Delete (llvm::StringRef name) override virtual
Implements lldb_private::PipeBase.
Definition at line 253 of file PipePosix.cpp.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess().
GetReadFileDescriptor()
int PipePosix::GetReadFileDescriptor () const override virtual
Implements lldb_private::PipeBase.
Definition at line 203 of file PipePosix.cpp.
References GetReadFileDescriptorUnlocked(), and m_read_mutex.
Referenced by GetReadPipe(), and lldb_private::ProcessLauncherPosixFork::LaunchProcess().
GetReadFileDescriptorUnlocked()
int PipePosix::GetReadFileDescriptorUnlocked () const private
Definition at line 208 of file PipePosix.cpp.
References m_fds, and READ.
Referenced by GetReadFileDescriptor(), and Read().
GetReadPipe()
lldb::pipe_t lldb_private::PipePosix::GetReadPipe () const inline override virtual
Implements lldb_private::PipeBase.
Definition at line 46 of file PipePosix.h.
References GetReadFileDescriptor().
GetWriteFileDescriptor()
int PipePosix::GetWriteFileDescriptor () const override virtual
Implements lldb_private::PipeBase.
Definition at line 212 of file PipePosix.cpp.
References GetWriteFileDescriptorUnlocked(), and m_write_mutex.
Referenced by GetWritePipe().
GetWriteFileDescriptorUnlocked()
int PipePosix::GetWriteFileDescriptorUnlocked () const private
Definition at line 217 of file PipePosix.cpp.
References m_fds, and WRITE.
Referenced by GetWriteFileDescriptor(), and Write().
GetWritePipe()
lldb::pipe_t lldb_private::PipePosix::GetWritePipe () const inline override virtual
Implements lldb_private::PipeBase.
Definition at line 49 of file PipePosix.h.
References GetWriteFileDescriptor().
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess().
OpenAsReader()
Status PipePosix::OpenAsReader (llvm::StringRef name) override virtual
Implements lldb_private::PipeBase.
Definition at line 145 of file PipePosix.cpp.
References CanReadUnlocked(), CanWriteUnlocked(), error(), lldb_private::Status::FromErrno(), lldb_private::Status::FromErrorString(), lldb_private::FileSystem::Instance(), m_fds, m_read_mutex, m_write_mutex, O_NONBLOCK, lldb_private::FileSystem::Open(), and READ.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess().
OpenAsWriter()
llvm::Error PipePosix::OpenAsWriter (llvm::StringRef name, const Timeout< std::micro > & timeout) override virtual
Implements lldb_private::PipeBase.
Definition at line 163 of file PipePosix.cpp.
References CanReadUnlocked(), CanWriteUnlocked(), m_fds, m_write_mutex, Now(), O_NONBLOCK, OPEN_WRITER_SLEEP_TIMEOUT_MSECS, and WRITE.
operator=() [1/2]
PipePosix & lldb_private::PipePosix::operator= (const PipePosix &) delete
References PipePosix().
operator=() [2/2]
PipePosix & PipePosix::operator= (PipePosix && pipe_posix)
Definition at line 69 of file PipePosix.cpp.
References m_fds, m_read_mutex, m_write_mutex, PipePosix(), READ, and WRITE.
Read()
llvm::Expected< size_t > PipePosix::Read (void * buf, size_t size, const Timeout< std::micro > & timeout = std::nullopt) override virtual
Implements lldb_private::PipeBase.
Definition at line 298 of file PipePosix.cpp.
References CanReadUnlocked(), error(), SelectHelper::FDSetRead(), GetReadFileDescriptorUnlocked(), m_read_mutex, SelectHelper::Select(), SelectHelper::SetTimeout(), and lldb_private::Status::takeError().
Referenced by lldb_private::SharedSocket::GetNativeSocket(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess().
ReleaseReadFileDescriptor()
int PipePosix::ReleaseReadFileDescriptor () override virtual
Implements lldb_private::PipeBase.
Definition at line 221 of file PipePosix.cpp.
References m_read_mutex, and ReleaseReadFileDescriptorUnlocked().
Referenced by PipePosix(), and lldb_private::ScriptInterpreterIORedirect::ScriptInterpreterIORedirect().
ReleaseReadFileDescriptorUnlocked()
int PipePosix::ReleaseReadFileDescriptorUnlocked () private
Definition at line 226 of file PipePosix.cpp.
References kInvalidDescriptor, m_fds, and READ.
Referenced by ReleaseReadFileDescriptor().
ReleaseWriteFileDescriptor()
int PipePosix::ReleaseWriteFileDescriptor () override virtual
Implements lldb_private::PipeBase.
Definition at line 232 of file PipePosix.cpp.
References m_write_mutex, and ReleaseWriteFileDescriptorUnlocked().
Referenced by lldb_private::ProcessLauncherPosixFork::LaunchProcess(), PipePosix(), and lldb_private::ScriptInterpreterIORedirect::ScriptInterpreterIORedirect().
ReleaseWriteFileDescriptorUnlocked()
int PipePosix::ReleaseWriteFileDescriptorUnlocked () private
Definition at line 237 of file PipePosix.cpp.
References kInvalidDescriptor, m_fds, and WRITE.
Referenced by ReleaseWriteFileDescriptor().
Write()
llvm::Expected< size_t > PipePosix::Write (const void * buf, size_t size, const Timeout< std::micro > & timeout = std::nullopt) override virtual
Implements lldb_private::PipeBase.
Definition at line 323 of file PipePosix.cpp.
References CanWriteUnlocked(), error(), SelectHelper::FDSetWrite(), GetWriteFileDescriptorUnlocked(), m_write_mutex, SelectHelper::Select(), SelectHelper::SetTimeout(), and lldb_private::Status::takeError().
Member Data Documentation
kInvalidDescriptor
int PipePosix::kInvalidDescriptor = -1 static
Definition at line 24 of file PipePosix.h.
Referenced by CanReadUnlocked(), CanWriteUnlocked(), CloseReadFileDescriptorUnlocked(), CloseWriteFileDescriptorUnlocked(), CreateNew(), PipePosix(), ReleaseReadFileDescriptorUnlocked(), and ReleaseWriteFileDescriptorUnlocked().
m_fds
int lldb_private::PipePosix::m_fds[2] private
Definition at line 85 of file PipePosix.h.
Referenced by CanReadUnlocked(), CanWriteUnlocked(), CloseReadFileDescriptorUnlocked(), CloseWriteFileDescriptorUnlocked(), CreateNew(), GetReadFileDescriptorUnlocked(), GetWriteFileDescriptorUnlocked(), OpenAsReader(), OpenAsWriter(), operator=(), PipePosix(), PipePosix(), PipePosix(), ReleaseReadFileDescriptorUnlocked(), and ReleaseWriteFileDescriptorUnlocked().
m_read_mutex
std::mutex lldb_private::PipePosix::m_read_mutex mutable private
Mutexes for m_fds;.
Definition at line 88 of file PipePosix.h.
Referenced by CanRead(), Close(), CloseReadFileDescriptor(), CreateNew(), CreateNew(), GetReadFileDescriptor(), OpenAsReader(), operator=(), Read(), and ReleaseReadFileDescriptor().
m_write_mutex
std::mutex lldb_private::PipePosix::m_write_mutex mutable private
Definition at line 89 of file PipePosix.h.
Referenced by CanWrite(), Close(), CloseWriteFileDescriptor(), CreateNew(), CreateNew(), GetWriteFileDescriptor(), OpenAsReader(), OpenAsWriter(), operator=(), ReleaseWriteFileDescriptor(), and Write().
The documentation for this class was generated from the following files:
PipePosix.h
PipePosix.cpp