LLDB: lldb_private::CoreFileMemoryRanges Class Reference
lldb_private::CoreFileMemoryRanges Class Reference
#include <CoreFileMemoryRanges.h>
Public Member Functions
Status FinalizeCoreFileSaveRanges ()
Finalize and merge all overlapping ranges in this collection.
Public Member Functions inherited from lldb_private::RangeDataVector< lldb::addr_t, lldb::addr_t, CoreFileMemoryRange >
RangeDataVector (std::less< CoreFileMemoryRange > compare=std::less< CoreFileMemoryRange >())
~RangeDataVector ()=default
void Append (const Entry &entry)
bool Erase (uint32_t start, uint32_t end)
void Sort ()
void CombineConsecutiveEntriesWithEqualData ()
void Clear ()
bool IsEmpty () const
size_t GetSize () const
const Entry * GetEntryAtIndex (size_t i) const
Entry * GetMutableEntryAtIndex (size_t i)
Entry & GetEntryRef (size_t i)
uint32_t FindEntryIndexThatContains (lldb::addr_t addr) const
uint32_t FindEntryIndexesThatContain (lldb::addr_t addr, std::vector< uint32_t > &indexes)
Entry * FindEntryThatContains (lldb::addr_t addr)
const Entry * FindEntryStartsAt (lldb::addr_t addr) const
const Entry * FindEntryThatContainsOrFollows (lldb::addr_t addr) const
uint32_t FindEntryIndexThatContainsOrFollows (lldb::addr_t addr) const
Entry * Back ()
const_iterator begin () const
const_iterator end () const
Additional Inherited Members
Public Types inherited from lldb_private::RangeDataVector< lldb::addr_t, lldb::addr_t, CoreFileMemoryRange >
typedef lldb_private::Range< lldb::addr_t, lldb::addr_t > Range
typedef RangeData< lldb::addr_t, lldb::addr_t, CoreFileMemoryRange > Entry
typedef AugmentedRangeData< lldb::addr_t, lldb::addr_t, CoreFileMemoryRange > AugmentedEntry
typedef llvm::SmallVector< AugmentedEntry, 0 > Collection
using const_iterator
Static Public Member Functions inherited from lldb_private::RangeDataVector< lldb::addr_t, lldb::addr_t, CoreFileMemoryRange >
static bool BaseLessThan (const Entry &lhs, const Entry &rhs)
Protected Attributes inherited from lldb_private::RangeDataVector< lldb::addr_t, lldb::addr_t, CoreFileMemoryRange >
Collection m_entries
std::less< CoreFileMemoryRange > m_compare
Detailed Description
Definition at line 48 of file CoreFileMemoryRanges.h.
Member Function Documentation
FinalizeCoreFileSaveRanges()
Status CoreFileMemoryRanges::FinalizeCoreFileSaveRanges ()
Finalize and merge all overlapping ranges in this collection.
Ranges will be separated based on permissions.
Definition at line 37 of file CoreFileMemoryRanges.cpp.
References lldb_private::RangeDataVector< lldb::addr_t, lldb::addr_t, CoreFileMemoryRange >::Erase(), error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::RangeDataVector< lldb::addr_t, lldb::addr_t, CoreFileMemoryRange >::GetMutableEntryAtIndex(), lldb_private::RangeDataVector< lldb::addr_t, lldb::addr_t, CoreFileMemoryRange >::GetSize(), OnlyIntersects(), Overlaps(), PermissionsMatch(), and lldb_private::RangeDataVector< lldb::addr_t, lldb::addr_t, CoreFileMemoryRange >::Sort().
Referenced by lldb_private::Process::CalculateCoreFileSaveRanges().
The documentation for this class was generated from the following files:
CoreFileMemoryRanges.h
CoreFileMemoryRanges.cpp