LLDB: lldb_private::CommandObjectExpression::CommandOptions Class Reference
lldb_private::CommandObjectExpression::CommandOptions Class Reference
#include <CommandObjectExpression.h>
Public Member Functions
CommandOptions ()
~CommandOptions () override
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext *execution_context) override
void OptionParsingStarting (ExecutionContext *execution_context) override
EvaluateExpressionOptions GetEvaluateExpressionOptions (const Target &target, const OptionGroupValueObjectDisplay &display_opts)
Return the appropriate expression options used for evaluating the expression in the given target.
bool ShouldSuppressResult (const OptionGroupValueObjectDisplay &display_opts) const
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Public Attributes
bool top_level
bool unwind_on_error
bool ignore_breakpoints
bool allow_jit
bool show_types
bool show_summary
bool debug
uint32_t timeout
bool try_all_threads
lldb::LanguageType language
LanguageRuntimeDescriptionDisplayVerbosity m_verbosity
LazyBool auto_apply_fixits
LazyBool suppress_persistent_result
bool cpp_ignore_context_qualifiers
Detailed Description
Definition at line 25 of file CommandObjectExpression.h.
Constructor & Destructor Documentation
CommandOptions()
CommandObjectExpression::CommandOptions::CommandOptions () default
~CommandOptions()
CommandObjectExpression::CommandOptions::~CommandOptions () override default
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > CommandObjectExpression::CommandOptions::GetDefinitions () override virtual
Implements lldb_private::OptionGroup.
Definition at line 201 of file CommandObjectExpression.cpp.
Referenced by SetOptionValue().
GetEvaluateExpressionOptions()
EvaluateExpressionOptions CommandObjectExpression::CommandOptions::GetEvaluateExpressionOptions (const Target & target, const OptionGroupValueObjectDisplay & display_opts)
Return the appropriate expression options used for evaluating the expression in the given target.
Definition at line 206 of file CommandObjectExpression.cpp.
References allow_jit, auto_apply_fixits, cpp_ignore_context_qualifiers, debug, lldb_private::EvaluateExpressionOptions::default_execution_policy, lldb_private::eExecutionPolicyNever, lldb_private::eExecutionPolicyTopLevel, lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolYes, lldb_private::TargetProperties::GetEnableAutoApplyFixIts(), lldb_private::TargetProperties::GetNumberOfRetriesWithFixits(), ignore_breakpoints, language, lldb_private::EvaluateExpressionOptions::SetAutoApplyFixIts(), lldb_private::EvaluateExpressionOptions::SetCoerceToId(), lldb_private::EvaluateExpressionOptions::SetCppIgnoreContextQualifiers(), lldb_private::EvaluateExpressionOptions::SetDebug(), lldb_private::EvaluateExpressionOptions::SetExecutionPolicy(), lldb_private::EvaluateExpressionOptions::SetGenerateDebugInfo(), lldb_private::EvaluateExpressionOptions::SetIgnoreBreakpoints(), lldb_private::EvaluateExpressionOptions::SetKeepInMemory(), lldb_private::EvaluateExpressionOptions::SetLanguage(), lldb_private::EvaluateExpressionOptions::SetRetriesWithFixIts(), lldb_private::EvaluateExpressionOptions::SetTimeout(), lldb_private::EvaluateExpressionOptions::SetTryAllThreads(), lldb_private::EvaluateExpressionOptions::SetUnwindOnError(), lldb_private::EvaluateExpressionOptions::SetUseDynamic(), timeout, top_level, try_all_threads, unwind_on_error, lldb_private::OptionGroupValueObjectDisplay::use_dynamic, and lldb_private::OptionGroupValueObjectDisplay::use_object_desc.
OptionParsingStarting()
void CommandObjectExpression::CommandOptions::OptionParsingStarting (ExecutionContext * execution_context) override virtual
Implements lldb_private::OptionGroup.
Definition at line 175 of file CommandObjectExpression.cpp.
References allow_jit, auto_apply_fixits, cpp_ignore_context_qualifiers, debug, lldb_private::eLanguageRuntimeDescriptionDisplayVerbosityCompact, lldb::eLanguageTypeUnknown, lldb_private::eLazyBoolCalculate, lldb_private::ExecutionContext::GetProcessSP(), ignore_breakpoints, language, m_verbosity, show_summary, suppress_persistent_result, timeout, top_level, try_all_threads, and unwind_on_error.
Referenced by lldb_private::CommandObjectExpression::DoExecute().
SetOptionValue()
Status CommandObjectExpression::CommandOptions::SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext * execution_context) override virtual
Implements lldb_private::OptionGroup.
Definition at line 39 of file CommandObjectExpression.cpp.
References allow_jit, auto_apply_fixits, cpp_ignore_context_qualifiers, debug, lldb_private::eLanguageRuntimeDescriptionDisplayVerbosityFull, lldb::eLanguageTypeUnknown, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, error(), lldb_private::Status::FromErrorStringWithFormat(), GetDefinitions(), lldb_private::Language::GetLanguageTypeFromString(), lldb_private::StreamString::GetString(), ignore_breakpoints, language, m_verbosity, lldb_private::Stream::Printf(), lldb_private::Language::PrintSupportedLanguagesForExpressions(), lldb_private::Status, suppress_persistent_result, timeout, lldb_private::OptionArgParser::ToBoolean(), lldb_private::OptionArgParser::ToOptionEnum(), top_level, try_all_threads, and unwind_on_error.
ShouldSuppressResult()
bool CommandObjectExpression::CommandOptions::ShouldSuppressResult (const OptionGroupValueObjectDisplay & display_opts) const
Definition at line 246 of file CommandObjectExpression.cpp.
References lldb_private::eLanguageRuntimeDescriptionDisplayVerbosityCompact, lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolYes, m_verbosity, suppress_persistent_result, and lldb_private::OptionGroupValueObjectDisplay::use_object_desc.
Member Data Documentation
allow_jit
bool lldb_private::CommandObjectExpression::CommandOptions::allow_jit
Definition at line 50 of file CommandObjectExpression.h.
Referenced by GetEvaluateExpressionOptions(), OptionParsingStarting(), and SetOptionValue().
auto_apply_fixits
LazyBool lldb_private::CommandObjectExpression::CommandOptions::auto_apply_fixits
Definition at line 58 of file CommandObjectExpression.h.
Referenced by GetEvaluateExpressionOptions(), OptionParsingStarting(), and SetOptionValue().
cpp_ignore_context_qualifiers
bool lldb_private::CommandObjectExpression::CommandOptions::cpp_ignore_context_qualifiers
Definition at line 60 of file CommandObjectExpression.h.
Referenced by GetEvaluateExpressionOptions(), OptionParsingStarting(), and SetOptionValue().
debug
bool lldb_private::CommandObjectExpression::CommandOptions::debug
Definition at line 53 of file CommandObjectExpression.h.
Referenced by lldb_private::CommandObjectExpression::DoExecute(), GetEvaluateExpressionOptions(), OptionParsingStarting(), and SetOptionValue().
ignore_breakpoints
bool lldb_private::CommandObjectExpression::CommandOptions::ignore_breakpoints
Definition at line 49 of file CommandObjectExpression.h.
Referenced by lldb_private::CommandObjectExpression::DoExecute(), GetEvaluateExpressionOptions(), OptionParsingStarting(), and SetOptionValue().
language
lldb::LanguageType lldb_private::CommandObjectExpression::CommandOptions::language
Definition at line 56 of file CommandObjectExpression.h.
Referenced by GetEvaluateExpressionOptions(), OptionParsingStarting(), and SetOptionValue().
m_verbosity
LanguageRuntimeDescriptionDisplayVerbosity lldb_private::CommandObjectExpression::CommandOptions::m_verbosity
Definition at line 57 of file CommandObjectExpression.h.
Referenced by OptionParsingStarting(), SetOptionValue(), and ShouldSuppressResult().
show_summary
bool lldb_private::CommandObjectExpression::CommandOptions::show_summary
Definition at line 52 of file CommandObjectExpression.h.
Referenced by OptionParsingStarting().
show_types
bool lldb_private::CommandObjectExpression::CommandOptions::show_types
Definition at line 51 of file CommandObjectExpression.h.
suppress_persistent_result
LazyBool lldb_private::CommandObjectExpression::CommandOptions::suppress_persistent_result
Definition at line 59 of file CommandObjectExpression.h.
Referenced by OptionParsingStarting(), SetOptionValue(), and ShouldSuppressResult().
timeout
uint32_t lldb_private::CommandObjectExpression::CommandOptions::timeout
Definition at line 54 of file CommandObjectExpression.h.
Referenced by lldb_private::CommandObjectExpression::DoExecute(), GetEvaluateExpressionOptions(), OptionParsingStarting(), and SetOptionValue().
top_level
bool lldb_private::CommandObjectExpression::CommandOptions::top_level
Definition at line 47 of file CommandObjectExpression.h.
Referenced by GetEvaluateExpressionOptions(), OptionParsingStarting(), and SetOptionValue().
try_all_threads
bool lldb_private::CommandObjectExpression::CommandOptions::try_all_threads
Definition at line 55 of file CommandObjectExpression.h.
Referenced by lldb_private::CommandObjectExpression::DoExecute(), GetEvaluateExpressionOptions(), OptionParsingStarting(), and SetOptionValue().
unwind_on_error
bool lldb_private::CommandObjectExpression::CommandOptions::unwind_on_error
Definition at line 48 of file CommandObjectExpression.h.
Referenced by lldb_private::CommandObjectExpression::DoExecute(), GetEvaluateExpressionOptions(), OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following files:
CommandObjectExpression.h
CommandObjectExpression.cpp