LLDB: RegisterContextCorePOSIX_loongarch64 Class Reference
RegisterContextCorePOSIX_loongarch64 Class Reference
#include <RegisterContextPOSIXCore_loongarch64.h>
Public Member Functions
~RegisterContextCorePOSIX_loongarch64 () override
bool ReadRegister (const lldb_private::RegisterInfo *reg_info, lldb_private::RegisterValue &value) override
bool WriteRegister (const lldb_private::RegisterInfo *reg_info, const lldb_private::RegisterValue &value) override
Public Member Functions inherited from RegisterContextPOSIX_loongarch64
RegisterContextPOSIX_loongarch64 (lldb_private::Thread &thread, std::unique_ptr< RegisterInfoPOSIX_loongarch64 > register_info)
~RegisterContextPOSIX_loongarch64 () override
void invalidate ()
void InvalidateAllRegisters () override
size_t GetRegisterCount () override
virtual size_t GetGPRSize ()
virtual unsigned GetRegisterSize (unsigned reg)
virtual unsigned GetRegisterOffset (unsigned reg)
const lldb_private::RegisterInfo * GetRegisterInfoAtIndex (size_t reg) override
size_t GetRegisterSetCount () override
const lldb_private::RegisterSet * GetRegisterSet (size_t set) override
Public Member Functions inherited from lldb_private::RegisterContext
RegisterContext (Thread &thread, uint32_t concrete_frame_idx)
~RegisterContext () override
void InvalidateIfNeeded (bool force)
virtual lldb::ByteOrder GetByteOrder ()
virtual bool ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp)
virtual bool WriteAllRegisterValues (const lldb::DataBufferSP &data_sp)
virtual bool RegisterWriteCausesReconfigure (const llvm::StringRef name)
virtual bool ReconfigureRegisterInfo ()
virtual bool ReadAllRegisterValues (lldb_private::RegisterCheckpoint &reg_checkpoint)
virtual bool WriteAllRegisterValues (const lldb_private::RegisterCheckpoint &reg_checkpoint)
bool CopyFromRegisterContext (lldb::RegisterContextSP context)
virtual uint32_t ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num)
Convert from a given register numbering scheme to the lldb register numbering scheme.
virtual uint32_t NumSupportedHardwareBreakpoints ()
virtual uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual bool ClearHardwareBreakpoint (uint32_t hw_idx)
virtual uint32_t NumSupportedHardwareWatchpoints ()
virtual uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, bool read, bool write)
virtual bool ClearHardwareWatchpoint (uint32_t hw_index)
virtual bool HardwareSingleStep (bool enable)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, uint32_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, uint32_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual Thread & GetThread ()
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num)
uint64_t GetPC (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetThreadPointer (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool GetPCForSymbolication (Address &address)
Get an address suitable for symbolication.
bool SetPC (uint64_t pc)
bool SetPC (Address addr)
uint64_t GetSP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetSP (uint64_t sp)
uint64_t GetFP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetFP (uint64_t fp)
const char * GetRegisterName (uint32_t reg)
uint64_t GetReturnAddress (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetFlags (uint64_t fail_value=0)
uint64_t ReadRegisterAsUnsigned (uint32_t reg, uint64_t fail_value)
uint64_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, uint64_t fail_value)
bool WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
bool WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
bool ConvertBetweenRegisterKinds (lldb::RegisterKind source_rk, uint32_t source_regnum, lldb::RegisterKind target_rk, uint32_t &target_regnum)
lldb::TargetSP CalculateTarget () override
lldb::ProcessSP CalculateProcess () override
lldb::ThreadSP CalculateThread () override
lldb::StackFrameSP CalculateStackFrame () override
void CalculateExecutionContext (ExecutionContext &exe_ctx) override
Reconstruct the object's execution context into sc.
uint32_t GetStopID () const
void SetStopID (uint32_t stop_id)
Public Member Functions inherited from lldb_private::ExecutionContextScope
virtual ~ExecutionContextScope ()=default
Static Public Member Functions
static std::unique_ptr< RegisterContextCorePOSIX_loongarch64 > Create (lldb_private::Thread &thread, const lldb_private::ArchSpec &arch, const lldb_private::DataExtractor &gpregset, llvm::ArrayRef< lldb_private::CoreNote > notes)
Protected Member Functions
RegisterContextCorePOSIX_loongarch64 (lldb_private::Thread &thread, std::unique_ptr< RegisterInfoPOSIX_loongarch64 > register_info, const lldb_private::DataExtractor &gpregset, llvm::ArrayRef< lldb_private::CoreNote > notes)
bool ReadGPR () override
bool ReadFPR () override
bool WriteGPR () override
bool WriteFPR () override
Protected Member Functions inherited from RegisterContextPOSIX_loongarch64
virtual const lldb_private::RegisterInfo * GetRegisterInfo ()
bool IsGPR (unsigned reg)
bool IsFPR (unsigned reg)
bool IsLSX (unsigned reg)
bool IsLASX (unsigned reg)
size_t GetFPRSize ()
uint32_t GetRegNumFCSR () const
virtual bool ReadLSX ()
virtual bool ReadLASX ()
virtual bool WriteLSX ()
virtual bool WriteLASX ()
Protected Member Functions inherited from lldb_private::RegisterContext
virtual bool BehavesLikeZerothFrame () const
Indicates that this frame is currently executing code, that the PC value is not a return-pc but an actual executing instruction.
Private Attributes
lldb_private::DataExtractor m_gpr
lldb_private::DataExtractor m_fpr
Additional Inherited Members
Protected Attributes inherited from RegisterContextPOSIX_loongarch64
std::unique_ptr< RegisterInfoPOSIX_loongarch64 > m_register_info_up
Protected Attributes inherited from lldb_private::RegisterContext
Thread & m_thread
uint32_t m_concrete_frame_idx
uint32_t m_stop_id
Detailed Description
Definition at line 22 of file RegisterContextPOSIXCore_loongarch64.h.
Constructor & Destructor Documentation
~RegisterContextCorePOSIX_loongarch64()
RegisterContextCorePOSIX_loongarch64::~RegisterContextCorePOSIX_loongarch64 () override default
RegisterContextCorePOSIX_loongarch64()
RegisterContextCorePOSIX_loongarch64::RegisterContextCorePOSIX_loongarch64 (lldb_private::Thread & thread, std::unique_ptr< RegisterInfoPOSIX_loongarch64 > register_info, const lldb_private::DataExtractor & gpregset, llvm::ArrayRef< lldb_private::CoreNote > notes) protected
Definition at line 27 of file RegisterContextPOSIXCore_loongarch64.cpp.
References lldb_private::FPR_Desc, lldb_private::DataExtractor::GetByteOrder(), lldb_private::DataExtractor::GetByteSize(), lldb_private::DataExtractor::GetDataStart(), lldb_private::getRegset(), m_fpr, m_gpr, RegisterContextPOSIX_loongarch64::m_register_info_up, and RegisterContextPOSIX_loongarch64::RegisterContextPOSIX_loongarch64().
Referenced by Create().
Member Function Documentation
Create()
std::unique_ptr< RegisterContextCorePOSIX_loongarch64 > RegisterContextCorePOSIX_loongarch64::Create (lldb_private::Thread & thread, const lldb_private::ArchSpec & arch, const lldb_private::DataExtractor & gpregset, llvm::ArrayRef< lldb_private::CoreNote > notes) static
Definition at line 16 of file RegisterContextPOSIXCore_loongarch64.cpp.
References RegisterContextCorePOSIX_loongarch64().
Referenced by ThreadElfCore::CreateRegisterContextForFrame().
ReadFPR()
bool RegisterContextCorePOSIX_loongarch64::ReadFPR () override protected virtual
Implements RegisterContextPOSIX_loongarch64.
Definition at line 49 of file RegisterContextPOSIXCore_loongarch64.cpp.
ReadGPR()
bool RegisterContextCorePOSIX_loongarch64::ReadGPR () override protected virtual
Implements RegisterContextPOSIX_loongarch64.
Definition at line 47 of file RegisterContextPOSIXCore_loongarch64.cpp.
ReadRegister()
bool RegisterContextCorePOSIX_loongarch64::ReadRegister (const lldb_private::RegisterInfo * reg_info, lldb_private::RegisterValue & value) override virtual
Implements lldb_private::RegisterContext.
Definition at line 61 of file RegisterContextPOSIXCore_loongarch64.cpp.
References lldb_private::RegisterInfo::byte_offset, lldb_private::RegisterInfo::byte_size, lldb::eByteOrderLittle, lldb::eRegisterKindLLDB, error(), RegisterContextPOSIX_loongarch64::GetGPRSize(), RegisterContextPOSIX_loongarch64::IsFPR(), RegisterContextPOSIX_loongarch64::IsGPR(), lldb_private::RegisterInfo::kinds, m_fpr, m_gpr, and lldb_private::RegisterValue::SetFromMemoryData().
WriteFPR()
bool RegisterContextCorePOSIX_loongarch64::WriteFPR () override protected virtual
Implements RegisterContextPOSIX_loongarch64.
Definition at line 56 of file RegisterContextPOSIXCore_loongarch64.cpp.
WriteGPR()
bool RegisterContextCorePOSIX_loongarch64::WriteGPR () override protected virtual
Implements RegisterContextPOSIX_loongarch64.
Definition at line 51 of file RegisterContextPOSIXCore_loongarch64.cpp.
WriteRegister()
bool RegisterContextCorePOSIX_loongarch64::WriteRegister (const lldb_private::RegisterInfo * reg_info, const lldb_private::RegisterValue & value) override virtual
Implements lldb_private::RegisterContext.
Definition at line 81 of file RegisterContextPOSIXCore_loongarch64.cpp.
Member Data Documentation
m_fpr
lldb_private::DataExtractor RegisterContextCorePOSIX_loongarch64::m_fpr private
Definition at line 55 of file RegisterContextPOSIXCore_loongarch64.h.
Referenced by ReadRegister(), and RegisterContextCorePOSIX_loongarch64().
m_gpr
lldb_private::DataExtractor RegisterContextCorePOSIX_loongarch64::m_gpr private
Definition at line 54 of file RegisterContextPOSIXCore_loongarch64.h.
Referenced by ReadRegister(), and RegisterContextCorePOSIX_loongarch64().
The documentation for this class was generated from the following files:
RegisterContextPOSIXCore_loongarch64.h
RegisterContextPOSIXCore_loongarch64.cpp