LLDB: lldb_private::python::PythonInteger Class Reference
lldb_private::python::PythonInteger Class Reference
#include <PythonDataObjects.h>
Public Member Functions
PythonInteger ()
PythonInteger (int64_t value)
void SetInteger (int64_t value)
StructuredData::IntegerSP CreateStructuredInteger () const
StructuredData::UnsignedIntegerSP CreateStructuredUnsignedInteger () const
StructuredData::SignedIntegerSP CreateStructuredSignedInteger () const
TypedPythonObject (PyRefType type, PyObject *py_obj)
TypedPythonObject ()=default
Public Member Functions inherited from lldb_private::python::TypedPythonObject< PythonInteger >
TypedPythonObject (PyRefType type, PyObject *py_obj)
Public Member Functions inherited from lldb_private::python::PythonObject
PythonObject ()=default
PythonObject (PyRefType type, PyObject *py_obj)
PythonObject (const PythonObject &rhs)
PythonObject (PythonObject &&rhs)
~PythonObject ()
void Reset ()
void Dump (Stream &strm) const
PyObject * get () const
PyObject * release ()
PythonObject & operator= (PythonObject other)
PyObjectType GetObjectType () const
PythonString Repr () const
PythonString Str () const
PythonObject ResolveName (llvm::StringRef name) const
template<typename T>
T ResolveName (llvm::StringRef name) const
bool HasAttribute (llvm::StringRef attribute) const
PythonObject GetAttributeValue (llvm::StringRef attribute) const
bool IsNone () const
bool IsValid () const
bool IsAllocated () const
operator bool () const
template<typename T>
T AsType () const
StructuredData::ObjectSP CreateStructuredObject () const
template<typename... T>
llvm::Expected< PythonObject > CallMethod (const char *name, const T &... t) const
template<typename... T>
llvm::Expected< PythonObject > Call (const T &... t) const
llvm::Expected< PythonObject > GetAttribute (const llvm::Twine &name) const
llvm::Expected< PythonObject > GetType () const
llvm::Expected< bool > IsTrue ()
llvm::Expected< long long > AsLongLong () const
llvm::Expected< unsigned long long > AsUnsignedLongLong () const
llvm::Expected< unsigned long long > AsModuloUnsignedLongLong () const
llvm::Expected< bool > IsInstance (const PythonObject &cls)
Static Public Member Functions
static bool Check (PyObject *py_obj)
Static Public Member Functions inherited from lldb_private::python::PythonObject
static PythonObject ResolveNameWithDictionary (llvm::StringRef name, const PythonDictionary &dict)
template<typename T>
static T ResolveNameWithDictionary (llvm::StringRef name, const PythonDictionary &dict)
Additional Inherited Members
Protected Attributes inherited from lldb_private::python::PythonObject
PyObject * m_py_obj = nullptr
Detailed Description
Definition at line 469 of file PythonDataObjects.h.
Constructor & Destructor Documentation
PythonInteger() [1/2]
lldb_private::python::PythonInteger::PythonInteger () inline
Definition at line 473 of file PythonDataObjects.h.
References TypedPythonObject().
PythonInteger() [2/2]
PythonInteger::PythonInteger (int64_t value) explicit
Definition at line 455 of file PythonDataObjects.cpp.
References SetInteger().
Member Function Documentation
Check()
bool PythonInteger::Check (PyObject * py_obj) static
Definition at line 457 of file PythonDataObjects.cpp.
Referenced by lldb_private::python::PythonObject::GetObjectType().
CreateStructuredInteger()
StructuredData::IntegerSP PythonInteger::CreateStructuredInteger () const
Definition at line 470 of file PythonDataObjects.cpp.
References CreateStructuredSignedInteger(), and CreateStructuredUnsignedInteger().
Referenced by lldb_private::python::PythonObject::CreateStructuredObject().
CreateStructuredSignedInteger()
StructuredData::SignedIntegerSP PythonInteger::CreateStructuredSignedInteger () const
Definition at line 489 of file PythonDataObjects.cpp.
References lldb_private::python::PythonObject::AsLongLong().
Referenced by CreateStructuredInteger().
CreateStructuredUnsignedInteger()
StructuredData::UnsignedIntegerSP PythonInteger::CreateStructuredUnsignedInteger () const
Definition at line 477 of file PythonDataObjects.cpp.
References lldb_private::python::PythonObject::AsUnsignedLongLong().
Referenced by CreateStructuredInteger().
SetInteger()
void PythonInteger::SetInteger (int64_t value)
Definition at line 466 of file PythonDataObjects.cpp.
References lldb_private::python::Take().
Referenced by PythonInteger().
TypedPythonObject() [1/2]
lldb_private::python::TypedPythonObject< T >::TypedPythonObject () default
TypedPythonObject() [2/2]
lldb_private::python::TypedPythonObject< T >::TypedPythonObject (PyRefType type, PyObject * py_obj) inline
Definition at line 400 of file PythonDataObjects.h.
Referenced by PythonInteger().
The documentation for this class was generated from the following files:
PythonDataObjects.h
PythonDataObjects.cpp