LLDB: lldb_private::dil::BooleanLiteralNode Class Reference
lldb_private::dil::BooleanLiteralNode Class Reference
#include <DILAST.h>
Public Member Functions
BooleanLiteralNode (uint32_t location, bool value)
llvm::Expected< lldb::ValueObjectSP > Accept (Visitor *v) const override
bool GetValue () const &
Public Member Functions inherited from lldb_private::dil::ASTNode
ASTNode (uint32_t location, NodeKind kind)
virtual ~ASTNode ()=default
uint32_t GetLocation () const
NodeKind GetKind () const
Static Public Member Functions
static bool classof (const ASTNode &node)
Private Attributes
bool m_value
Detailed Description
Definition at line 241 of file DILAST.h.
Constructor & Destructor Documentation
BooleanLiteralNode()
lldb_private::dil::BooleanLiteralNode::BooleanLiteralNode (uint32_t location, bool value) inline
Definition at line 243 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), lldb_private::dil::eBooleanLiteralNode, and m_value.
Member Function Documentation
Accept()
llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::BooleanLiteralNode::Accept (Visitor * v) const override virtual
Implements lldb_private::dil::ASTNode.
Definition at line 50 of file DILAST.cpp.
References lldb_private::dil::Visitor::Visit().
classof()
bool lldb_private::dil::BooleanLiteralNode::classof (const ASTNode & node) inline static
Definition at line 250 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), lldb_private::dil::eBooleanLiteralNode, and lldb_private::dil::ASTNode::GetKind().
GetValue()
bool lldb_private::dil::BooleanLiteralNode::GetValue () const & inline
Definition at line 248 of file DILAST.h.
References m_value.
Referenced by lldb_private::dil::Interpreter::Visit().
Member Data Documentation
m_value
bool lldb_private::dil::BooleanLiteralNode::m_value private
Definition at line 255 of file DILAST.h.
Referenced by BooleanLiteralNode(), and GetValue().
The documentation for this class was generated from the following files:
DILAST.h
DILAST.cpp