LLDB: lldb_private::minidump::RegisterContextMinidump_ARM64 Class Reference
lldb_private::minidump::RegisterContextMinidump_ARM64 Class Reference
#include <RegisterContextMinidump_ARM64.h>
Classes
struct Context
Public Types
enum class Flags : uint32_t { ARM64_Flag = 0x80000000 , Integer = ARM64_Flag | 0x00000002 , FloatingPoint = ARM64_Flag | 0x00000004 }
Public Member Functions
RegisterContextMinidump_ARM64 (lldb_private::Thread &thread, const DataExtractor &data)
~RegisterContextMinidump_ARM64 () override=default
void InvalidateAllRegisters () override
size_t GetRegisterCount () override
const lldb_private::RegisterInfo * GetRegisterInfoAtIndex (size_t reg) override
size_t GetRegisterSetCount () override
const lldb_private::RegisterSet * GetRegisterSet (size_t set) override
const char * GetRegisterName (unsigned reg)
bool ReadRegister (const RegisterInfo *reg_info, RegisterValue &reg_value) override
bool WriteRegister (const RegisterInfo *reg_info, const RegisterValue &reg_value) override
uint32_t ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num) override
Convert from a given register numbering scheme to the lldb register numbering scheme.
Public Member Functions inherited from lldb_private::RegisterContext
RegisterContext (Thread &thread, uint32_t concrete_frame_idx)
~RegisterContext () override
void InvalidateIfNeeded (bool force)
virtual lldb::ByteOrder GetByteOrder ()
virtual bool ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp)
virtual bool WriteAllRegisterValues (const lldb::DataBufferSP &data_sp)
virtual bool RegisterWriteCausesReconfigure (const llvm::StringRef name)
virtual bool ReconfigureRegisterInfo ()
virtual bool ReadAllRegisterValues (lldb_private::RegisterCheckpoint &reg_checkpoint)
virtual bool WriteAllRegisterValues (const lldb_private::RegisterCheckpoint &reg_checkpoint)
bool CopyFromRegisterContext (lldb::RegisterContextSP context)
virtual uint32_t NumSupportedHardwareBreakpoints ()
virtual uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual bool ClearHardwareBreakpoint (uint32_t hw_idx)
virtual uint32_t NumSupportedHardwareWatchpoints ()
virtual uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, bool read, bool write)
virtual bool ClearHardwareWatchpoint (uint32_t hw_index)
virtual bool HardwareSingleStep (bool enable)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, uint32_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, uint32_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual Thread & GetThread ()
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num)
uint64_t GetPC (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetThreadPointer (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool GetPCForSymbolication (Address &address)
Get an address suitable for symbolication.
bool SetPC (uint64_t pc)
bool SetPC (Address addr)
uint64_t GetSP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetSP (uint64_t sp)
uint64_t GetFP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetFP (uint64_t fp)
const char * GetRegisterName (uint32_t reg)
uint64_t GetReturnAddress (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetFlags (uint64_t fail_value=0)
uint64_t ReadRegisterAsUnsigned (uint32_t reg, uint64_t fail_value)
uint64_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, uint64_t fail_value)
bool WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
bool WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
bool ConvertBetweenRegisterKinds (lldb::RegisterKind source_rk, uint32_t source_regnum, lldb::RegisterKind target_rk, uint32_t &target_regnum)
lldb::TargetSP CalculateTarget () override
lldb::ProcessSP CalculateProcess () override
lldb::ThreadSP CalculateThread () override
lldb::StackFrameSP CalculateStackFrame () override
void CalculateExecutionContext (ExecutionContext &exe_ctx) override
Reconstruct the object's execution context into sc.
uint32_t GetStopID () const
void SetStopID (uint32_t stop_id)
Public Member Functions inherited from lldb_private::ExecutionContextScope
virtual ~ExecutionContextScope ()=default
Protected Attributes
Context m_regs
Protected Attributes inherited from lldb_private::RegisterContext
Thread & m_thread
uint32_t m_concrete_frame_idx
uint32_t m_stop_id
Additional Inherited Members
Protected Member Functions inherited from lldb_private::RegisterContext
virtual bool BehavesLikeZerothFrame () const
Indicates that this frame is currently executing code, that the PC value is not a return-pc but an actual executing instruction.
Detailed Description
Definition at line 29 of file RegisterContextMinidump_ARM64.h.
Member Enumeration Documentation
Flags
enum class lldb_private::minidump::RegisterContextMinidump_ARM64::Flags : uint32_t strong
Enumerator
ARM64_Flag
Integer
FloatingPoint
Definition at line 70 of file RegisterContextMinidump_ARM64.h.
Constructor & Destructor Documentation
RegisterContextMinidump_ARM64()
RegisterContextMinidump_ARM64::RegisterContextMinidump_ARM64 (lldb_private::Thread & thread, const DataExtractor & data)
Definition at line 771 of file RegisterContextMinidump_ARM64.cpp.
References lldb_private::DataExtractor::GetData(), lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU64(), k_num_reg_infos, k_num_regs, m_regs, and lldb_private::RegisterContext::RegisterContext().
~RegisterContextMinidump_ARM64()
lldb_private::minidump::RegisterContextMinidump_ARM64::~RegisterContextMinidump_ARM64 () override default
Member Function Documentation
ConvertRegisterKindToRegisterNumber()
uint32_t RegisterContextMinidump_ARM64::ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num) override virtual
Convert from a given register numbering scheme to the lldb register numbering scheme.
There may be multiple ways to enumerate the registers for a given architecture. ABI references will specify one to be used with DWARF, the register numberings from process plugin, there may be a variation used for eh_frame unwind instructions (e.g. on Darwin), and so on. Register 5 by itself is meaningless - RegisterKind enumeration tells you what context that number should be translated as.
Inside lldb, register numbers are in the eRegisterKindLLDB scheme; arguments which take a register number should take one in that scheme.
eRegisterKindGeneric is a special numbering scheme which gives us constant values for the pc, frame register, stack register, etc., for use within lldb. They may not be defined for all architectures but it allows generic code to translate these common registers into the lldb numbering scheme.
This method translates a given register kind + register number into the eRegisterKindLLDB register numbering.
Parameters
[in] kind The register numbering scheme (RegisterKind) that the following register number is in.
[in] num A register number in the 'kind' register numbering scheme.
Returns
The equivalent register number in the eRegisterKindLLDB numbering scheme, if possible, else LLDB_INVALID_REGNUM.
Reimplemented from lldb_private::RegisterContext.
Definition at line 826 of file RegisterContextMinidump_ARM64.cpp.
References g_reg_infos, k_num_regs, and LLDB_INVALID_REGNUM.
GetRegisterCount()
size_t RegisterContextMinidump_ARM64::GetRegisterCount () override virtual
Implements lldb_private::RegisterContext.
Definition at line 787 of file RegisterContextMinidump_ARM64.cpp.
References k_num_regs.
GetRegisterInfoAtIndex()
const RegisterInfo * RegisterContextMinidump_ARM64::GetRegisterInfoAtIndex (size_t reg) override virtual
Implements lldb_private::RegisterContext.
Definition at line 790 of file RegisterContextMinidump_ARM64.cpp.
References g_reg_infos, and k_num_reg_infos.
GetRegisterName()
const char * RegisterContextMinidump_ARM64::GetRegisterName (unsigned reg)
Definition at line 806 of file RegisterContextMinidump_ARM64.cpp.
References g_reg_infos, and k_num_reg_infos.
GetRegisterSet()
const RegisterSet * RegisterContextMinidump_ARM64::GetRegisterSet (size_t set) override virtual
Implements lldb_private::RegisterContext.
Definition at line 800 of file RegisterContextMinidump_ARM64.cpp.
References g_reg_sets, and k_num_reg_sets.
GetRegisterSetCount()
size_t RegisterContextMinidump_ARM64::GetRegisterSetCount () override virtual
Implements lldb_private::RegisterContext.
Definition at line 796 of file RegisterContextMinidump_ARM64.cpp.
References k_num_reg_sets.
InvalidateAllRegisters()
void lldb_private::minidump::RegisterContextMinidump_ARM64::InvalidateAllRegisters () inline override virtual
Implements lldb_private::RegisterContext.
Definition at line 36 of file RegisterContextMinidump_ARM64.h.
ReadRegister()
bool RegisterContextMinidump_ARM64::ReadRegister (const RegisterInfo * reg_info, RegisterValue & reg_value) override virtual
Implements lldb_private::RegisterContext.
Definition at line 812 of file RegisterContextMinidump_ARM64.cpp.
References lldb_private::RegisterInfo::byte_offset, lldb_private::RegisterInfo::byte_size, lldb::eByteOrderLittle, error(), m_regs, and lldb_private::RegisterValue::SetFromMemoryData().
WriteRegister()
bool RegisterContextMinidump_ARM64::WriteRegister (const RegisterInfo * reg_info, const RegisterValue & reg_value) override virtual
Implements lldb_private::RegisterContext.
Definition at line 821 of file RegisterContextMinidump_ARM64.cpp.
Member Data Documentation
m_regs
Context lldb_private::minidump::RegisterContextMinidump_ARM64::m_regs protected
Definition at line 78 of file RegisterContextMinidump_ARM64.h.
Referenced by ReadRegister(), and RegisterContextMinidump_ARM64().
The documentation for this class was generated from the following files:
RegisterContextMinidump_ARM64.h
RegisterContextMinidump_ARM64.cpp