LLDB: lldb::SBLaunchInfo Class Reference
lldb::SBLaunchInfo Class Reference
#include <SBLaunchInfo.h>
Public Member Functions
SBLaunchInfo (const char **argv)
~SBLaunchInfo ()
SBLaunchInfo (const SBLaunchInfo &rhs)
SBLaunchInfo & operator= (const SBLaunchInfo &rhs)
lldb::pid_t GetProcessID ()
uint32_t GetUserID ()
uint32_t GetGroupID ()
bool UserIDIsValid ()
bool GroupIDIsValid ()
void SetUserID (uint32_t uid)
void SetGroupID (uint32_t gid)
SBFileSpec GetExecutableFile ()
void SetExecutableFile (SBFileSpec exe_file, bool add_as_first_arg)
Set the executable file that will be used to launch the process and optionally set it as the first argument in the argument vector.
SBListener GetListener ()
Get the listener that will be used to receive process events.
void SetListener (SBListener &listener)
Set the listener that will be used to receive process events.
SBListener GetShadowListener ()
Get the shadow listener that receive public process events, additionally to the default process event listener.
void SetShadowListener (SBListener &listener)
Set the shadow listener that will receive public process events, additionally to the default process event listener.
uint32_t GetNumArguments ()
const char * GetArgumentAtIndex (uint32_t idx)
void SetArguments (const char **argv, bool append)
uint32_t GetNumEnvironmentEntries ()
const char * GetEnvironmentEntryAtIndex (uint32_t idx)
void SetEnvironmentEntries (const char **envp, bool append)
Update this object with the given environment variables.
void SetEnvironment (const SBEnvironment &env, bool append)
Update this object with the given environment variables.
SBEnvironment GetEnvironment ()
Return the environment variables of this object.
void Clear ()
const char * GetWorkingDirectory () const
void SetWorkingDirectory (const char *working_dir)
uint32_t GetLaunchFlags ()
void SetLaunchFlags (uint32_t flags)
const char * GetProcessPluginName ()
void SetProcessPluginName (const char *plugin_name)
const char * GetShell ()
void SetShell (const char *path)
bool GetShellExpandArguments ()
void SetShellExpandArguments (bool expand)
uint32_t GetResumeCount ()
void SetResumeCount (uint32_t c)
bool AddCloseFileAction (int fd)
bool AddDuplicateFileAction (int fd, int dup_fd)
bool AddOpenFileAction (int fd, const char *path, bool read, bool write)
bool AddSuppressFileAction (int fd, bool read, bool write)
void SetLaunchEventData (const char *data)
const char * GetLaunchEventData () const
bool GetDetachOnError () const
void SetDetachOnError (bool enable)
const char * GetScriptedProcessClassName () const
void SetScriptedProcessClassName (const char *class_name)
lldb::SBStructuredData GetScriptedProcessDictionary () const
void SetScriptedProcessDictionary (lldb::SBStructuredData dict)
Protected Member Functions
const lldb_private::ProcessLaunchInfo & ref () const
void set_ref (const lldb_private::ProcessLaunchInfo &info)
Protected Attributes
std::shared_ptr< lldb_private::SBLaunchInfoImpl > m_opaque_sp
Friends
class SBPlatform
class SBTarget
class lldb_private::ScriptInterpreter
Detailed Description
Definition at line 24 of file SBLaunchInfo.h.
Constructor & Destructor Documentation
SBLaunchInfo() [1/2]
SBLaunchInfo::SBLaunchInfo (const char ** argv)
Definition at line 43 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by operator=(), SBLaunchInfo(), and ~SBLaunchInfo().
~SBLaunchInfo()
SBLaunchInfo::~SBLaunchInfo () default
References AddCloseFileAction(), AddDuplicateFileAction(), AddOpenFileAction(), AddSuppressFileAction(), Clear(), GetArgumentAtIndex(), GetDetachOnError(), GetEnvironment(), GetEnvironmentEntryAtIndex(), GetExecutableFile(), GetGroupID(), GetLaunchEventData(), GetLaunchFlags(), GetListener(), GetNumArguments(), GetNumEnvironmentEntries(), GetProcessID(), GetProcessPluginName(), GetResumeCount(), GetScriptedProcessClassName(), GetScriptedProcessDictionary(), GetShadowListener(), GetShell(), GetShellExpandArguments(), GetUserID(), GetWorkingDirectory(), GroupIDIsValid(), operator=(), SBLaunchInfo(), SetArguments(), SetDetachOnError(), SetEnvironment(), SetEnvironmentEntries(), SetExecutableFile(), SetGroupID(), SetLaunchEventData(), SetLaunchFlags(), SetListener(), SetProcessPluginName(), SetResumeCount(), SetScriptedProcessClassName(), SetScriptedProcessDictionary(), SetShadowListener(), SetShell(), SetShellExpandArguments(), SetUserID(), SetWorkingDirectory(), and UserIDIsValid().
SBLaunchInfo() [2/2]
SBLaunchInfo::SBLaunchInfo (const SBLaunchInfo & rhs)
Definition at line 52 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBLaunchInfo().
Member Function Documentation
AddCloseFileAction()
bool SBLaunchInfo::AddCloseFileAction (int fd)
Definition at line 285 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
AddDuplicateFileAction()
bool SBLaunchInfo::AddDuplicateFileAction (int fd, int dup_fd)
Definition at line 291 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
AddOpenFileAction()
bool SBLaunchInfo::AddOpenFileAction (int fd, const char * path, bool read, bool write)
Definition at line 297 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
AddSuppressFileAction()
bool SBLaunchInfo::AddSuppressFileAction (int fd, bool read, bool write)
Definition at line 304 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
Clear()
void SBLaunchInfo::Clear ()
Definition at line 204 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
GetArgumentAtIndex()
const char * SBLaunchInfo::GetArgumentAtIndex (uint32_t idx)
Definition at line 148 of file SBLaunchInfo.cpp.
References lldb_private::ConstString::GetCString(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
GetDetachOnError()
bool SBLaunchInfo::GetDetachOnError () const
Definition at line 328 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
GetEnvironment()
SBEnvironment SBLaunchInfo::GetEnvironment ()
Return the environment variables of this object.
Returns
An lldb::SBEnvironment object which is a copy of the SBLaunchInfo's environment.
Definition at line 199 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBEnvironment.
Referenced by ~SBLaunchInfo().
GetEnvironmentEntryAtIndex()
const char * SBLaunchInfo::GetEnvironmentEntryAtIndex (uint32_t idx)
Definition at line 175 of file SBLaunchInfo.cpp.
References lldb_private::ConstString::GetCString(), GetNumEnvironmentEntries(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
GetExecutableFile()
SBFileSpec SBLaunchInfo::GetExecutableFile ()
Definition at line 117 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBFileSpec.
Referenced by ~SBLaunchInfo().
GetGroupID()
uint32_t SBLaunchInfo::GetGroupID ()
Definition at line 87 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
GetLaunchEventData()
const char * SBLaunchInfo::GetLaunchEventData () const
Definition at line 316 of file SBLaunchInfo.cpp.
References lldb_private::ConstString::GetCString(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
GetLaunchFlags()
uint32_t SBLaunchInfo::GetLaunchFlags ()
Definition at line 222 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
GetListener()
SBListener SBLaunchInfo::GetListener ()
Get the listener that will be used to receive process events.
If no listener has been set via a call to SBLaunchInfo::SetListener(), then an invalid SBListener will be returned (SBListener::IsValid() will return false). If a listener has been set, then the valid listener object will be returned.
Definition at line 130 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBListener.
Referenced by ~SBLaunchInfo().
GetNumArguments()
uint32_t SBLaunchInfo::GetNumArguments ()
Definition at line 142 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
GetNumEnvironmentEntries()
uint32_t SBLaunchInfo::GetNumEnvironmentEntries ()
Definition at line 169 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by GetEnvironmentEntryAtIndex(), and ~SBLaunchInfo().
GetProcessID()
lldb::pid_t SBLaunchInfo::GetProcessID ()
Definition at line 75 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
GetProcessPluginName()
const char * SBLaunchInfo::GetProcessPluginName ()
Definition at line 234 of file SBLaunchInfo.cpp.
References lldb_private::ConstString::GetCString(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
GetResumeCount()
uint32_t SBLaunchInfo::GetResumeCount ()
Definition at line 273 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
GetScriptedProcessClassName()
const char * SBLaunchInfo::GetScriptedProcessClassName () const
Definition at line 334 of file SBLaunchInfo.cpp.
References lldb_private::ConstString::AsCString(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
GetScriptedProcessDictionary()
lldb::SBStructuredData SBLaunchInfo::GetScriptedProcessDictionary () const
Definition at line 357 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, lldb::SBStructuredData::m_impl_up, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
GetShadowListener()
SBListener SBLaunchInfo::GetShadowListener ()
Get the shadow listener that receive public process events, additionally to the default process event listener.
If no listener has been set via a call to SBLaunchInfo::SetShadowListener(), then an invalid SBListener will be returned (SBListener::IsValid() will return false). If a listener has been set, then the valid listener object will be returned.
Definition at line 393 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBListener.
Referenced by ~SBLaunchInfo().
GetShell()
const char * SBLaunchInfo::GetShell ()
Definition at line 246 of file SBLaunchInfo.cpp.
References lldb_private::ConstString::AsCString(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
GetShellExpandArguments()
bool SBLaunchInfo::GetShellExpandArguments ()
Definition at line 261 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
GetUserID()
uint32_t SBLaunchInfo::GetUserID ()
Definition at line 81 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
GetWorkingDirectory()
const char * SBLaunchInfo::GetWorkingDirectory () const
Definition at line 210 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
GroupIDIsValid()
bool SBLaunchInfo::GroupIDIsValid ()
Definition at line 99 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
operator=()
SBLaunchInfo & SBLaunchInfo::operator= (const SBLaunchInfo & rhs)
Definition at line 58 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBLaunchInfo().
Referenced by ~SBLaunchInfo().
ref()
const lldb_private::ProcessLaunchInfo & SBLaunchInfo::ref () const protected
Definition at line 67 of file SBLaunchInfo.cpp.
References m_opaque_sp.
Referenced by lldb::SBPlatform::Launch(), lldb::SBTarget::Launch(), lldb_private::ScriptInterpreter, and lldb::SBTarget::SetLaunchInfo().
set_ref()
void SBLaunchInfo::set_ref (const lldb_private::ProcessLaunchInfo & info) protected
Definition at line 71 of file SBLaunchInfo.cpp.
References m_opaque_sp.
Referenced by lldb::SBTarget::GetLaunchInfo(), lldb::SBPlatform::Launch(), lldb::SBTarget::Launch(), and lldb_private::ScriptInterpreter.
SetArguments()
void SBLaunchInfo::SetArguments (const char ** argv, bool append)
Definition at line 155 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by lldb::SBTarget::LaunchSimple(), and ~SBLaunchInfo().
SetDetachOnError()
void SBLaunchInfo::SetDetachOnError (bool enable)
Definition at line 322 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
SetEnvironment()
void SBLaunchInfo::SetEnvironment (const SBEnvironment & env, bool append)
Update this object with the given environment variables.
If append is false, the provided environment will replace the existing environment. Otherwise, existing values will be updated of left untouched accordingly.
Parameters
[in] env The new environment variables.
[in] append Flag that controls whether to replace the existing environment.
Definition at line 188 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBEnvironment::ref().
Referenced by SetEnvironmentEntries(), and ~SBLaunchInfo().
SetEnvironmentEntries()
void SBLaunchInfo::SetEnvironmentEntries (const char ** envp, bool append)
Update this object with the given environment variables.
If append is false, the provided environment will replace the existing environment. Otherwise, existing values will be updated of left untouched accordingly.
Parameters
[in] envp The new environment variables as a list of strings with the following format name=value
[in] append Flag that controls whether to replace the existing environment.
Definition at line 183 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, lldb::SBEnvironment, and SetEnvironment().
Referenced by lldb::SBTarget::LaunchSimple(), and ~SBLaunchInfo().
SetExecutableFile()
void SBLaunchInfo::SetExecutableFile (SBFileSpec exe_file, bool add_as_first_arg)
Set the executable file that will be used to launch the process and optionally set it as the first argument in the argument vector.
This only needs to be specified if clients wish to carefully control the exact path will be used to launch a binary. If you create a target with a symlink, that symlink will get resolved in the target and the resolved path will get used to launch the process. Calling this function can help you still launch your process using the path of your choice.
If this function is not called prior to launching with SBTarget::Launch(...), the target will use the resolved executable path that was used to create the target.
Parameters
[in] exe_file The override path to use when launching the executable.
[in] add_as_first_arg If true, then the path will be inserted into the argument vector prior to launching. Otherwise the argument vector will be left alone.
Definition at line 123 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBFileSpec::ref().
Referenced by lldb::SBTarget::LaunchSimple(), and ~SBLaunchInfo().
SetGroupID()
void SBLaunchInfo::SetGroupID (uint32_t gid)
Definition at line 111 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
SetLaunchEventData()
void SBLaunchInfo::SetLaunchEventData (const char * data)
Definition at line 310 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
SetLaunchFlags()
void SBLaunchInfo::SetLaunchFlags (uint32_t flags)
Definition at line 228 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
SetListener()
void SBLaunchInfo::SetListener (SBListener & listener)
Set the listener that will be used to receive process events.
By default the SBDebugger, which has a listener, that the SBTarget belongs to will listen for the process events. Calling this function allows a different listener to be used to listen for process events.
Definition at line 136 of file SBLaunchInfo.cpp.
References lldb::SBListener::GetSP(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
SetProcessPluginName()
void SBLaunchInfo::SetProcessPluginName (const char * plugin_name)
Definition at line 240 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
SetResumeCount()
void SBLaunchInfo::SetResumeCount (uint32_t c)
Definition at line 279 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
SetScriptedProcessClassName()
void SBLaunchInfo::SetScriptedProcessClassName (const char * class_name)
Definition at line 348 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
SetScriptedProcessDictionary()
void SBLaunchInfo::SetScriptedProcessDictionary (lldb::SBStructuredData dict)
Definition at line 372 of file SBLaunchInfo.cpp.
References lldb::eStructuredDataTypeInvalid, lldb::SBStructuredData::IsValid(), LLDB_INSTRUMENT_VA, lldb::SBStructuredData::m_impl_up, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
SetShadowListener()
void SBLaunchInfo::SetShadowListener (SBListener & listener)
Set the shadow listener that will receive public process events, additionally to the default process event listener.
By default a process have no shadow event listener. Calling this function allows public process events to be broadcasted to an additional listener on top of the default process event listener. If the listener argument is invalid (SBListener::IsValid() will return false), this will clear the shadow listener.
Definition at line 402 of file SBLaunchInfo.cpp.
References lldb::SBListener::GetSP(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
SetShell()
void SBLaunchInfo::SetShell (const char * path)
Definition at line 255 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
SetShellExpandArguments()
void SBLaunchInfo::SetShellExpandArguments (bool expand)
Definition at line 267 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
SetUserID()
void SBLaunchInfo::SetUserID (uint32_t uid)
Definition at line 105 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
SetWorkingDirectory()
void SBLaunchInfo::SetWorkingDirectory (const char * working_dir)
Definition at line 216 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by lldb::SBTarget::LaunchSimple(), and ~SBLaunchInfo().
UserIDIsValid()
bool SBLaunchInfo::UserIDIsValid ()
Definition at line 93 of file SBLaunchInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBLaunchInfo().
Friends And Related Symbol Documentation
lldb_private::ScriptInterpreter
friend class lldb_private::ScriptInterpreter friend
Definition at line 213 of file SBLaunchInfo.h.
References ref(), and set_ref().
SBPlatform
friend class SBPlatform friend
Definition at line 210 of file SBLaunchInfo.h.
References SBPlatform.
Referenced by SBPlatform.
SBTarget
friend class SBTarget friend
Definition at line 211 of file SBLaunchInfo.h.
References SBTarget.
Referenced by SBTarget.
Member Data Documentation
m_opaque_sp
std::shared_ptr<lldb_private::SBLaunchInfoImpl> lldb::SBLaunchInfo::m_opaque_sp protected
Definition at line 218 of file SBLaunchInfo.h.
Referenced by AddCloseFileAction(), AddDuplicateFileAction(), AddOpenFileAction(), AddSuppressFileAction(), Clear(), GetArgumentAtIndex(), GetDetachOnError(), GetEnvironment(), GetEnvironmentEntryAtIndex(), GetExecutableFile(), GetGroupID(), GetLaunchEventData(), GetLaunchFlags(), GetListener(), GetNumArguments(), GetNumEnvironmentEntries(), lldb_private::ScriptInterpreter::GetOpaqueTypeFromSBLaunchInfo(), GetProcessID(), GetProcessPluginName(), GetResumeCount(), GetScriptedProcessClassName(), GetScriptedProcessDictionary(), GetShadowListener(), GetShell(), GetShellExpandArguments(), GetUserID(), GetWorkingDirectory(), GroupIDIsValid(), operator=(), ref(), SBLaunchInfo(), SBLaunchInfo(), set_ref(), SetArguments(), SetDetachOnError(), SetEnvironment(), SetExecutableFile(), SetGroupID(), SetLaunchEventData(), SetLaunchFlags(), SetListener(), SetProcessPluginName(), SetResumeCount(), SetScriptedProcessClassName(), SetScriptedProcessDictionary(), SetShadowListener(), SetShell(), SetShellExpandArguments(), SetUserID(), SetWorkingDirectory(), and UserIDIsValid().
The documentation for this class was generated from the following files:
SBLaunchInfo.h
SBLaunchInfo.cpp