LLDB: lldb_private::breakpad::SymbolFileBreakpad Class Reference
lldb_private::breakpad::SymbolFileBreakpad Class Reference
#include <SymbolFileBreakpad.h>
Classes
struct Bookmark
class CompUnitData
class LineIterator
struct UnwindData
Public Member Functions
SymbolFileBreakpad (lldb::ObjectFileSP objfile_sp)
~SymbolFileBreakpad () override=default
uint32_t CalculateAbilities () override
void InitializeObject () override
Initialize the SymbolFile object.
lldb::LanguageType ParseLanguage (CompileUnit &comp_unit) override
lldb::FunctionSP GetOrCreateFunction (CompileUnit &comp_unit)
size_t ParseFunctions (CompileUnit &comp_unit) override
bool ParseLineTable (CompileUnit &comp_unit) override
bool ParseDebugMacros (CompileUnit &comp_unit) override
bool ParseSupportFiles (CompileUnit &comp_unit, SupportFileList &support_files) override
size_t ParseTypes (CompileUnit &cu) override
bool ParseImportedModules (const SymbolContext &sc, std::vector< lldb_private::SourceModule > &imported_modules) override
size_t ParseBlocksRecursive (Function &func) override
void FindGlobalVariables (ConstString name, const CompilerDeclContext &parent_decl_ctx, uint32_t max_matches, VariableList &variables) override
size_t ParseVariablesForContext (const SymbolContext &sc) override
Type * ResolveTypeUID (lldb::user_id_t type_uid) override
std::optional< ArrayInfo > GetDynamicArrayInfoForUID (lldb::user_id_t type_uid, const lldb_private::ExecutionContext *exe_ctx) override
If type_uid points to an array type, return its characteristics.
bool CompleteType (CompilerType &compiler_type) override
uint32_t ResolveSymbolContext (const Address &so_addr, lldb::SymbolContextItem resolve_scope, SymbolContext &sc) override
uint32_t ResolveSymbolContext (const SourceLocationSpec &src_location_spec, lldb::SymbolContextItem resolve_scope, SymbolContextList &sc_list) override
void GetTypes (SymbolContextScope *sc_scope, lldb::TypeClass type_mask, TypeList &type_list) override
void FindFunctions (const Module::LookupInfo &lookup_info, const CompilerDeclContext &parent_decl_ctx, bool include_inlines, SymbolContextList &sc_list) override
void FindFunctions (const RegularExpression &regex, bool include_inlines, SymbolContextList &sc_list) override
llvm::Expected< lldb::TypeSystemSP > GetTypeSystemForLanguage (lldb::LanguageType language) override
CompilerDeclContext FindNamespace (ConstString name, const CompilerDeclContext &parent_decl_ctx, bool only_root_namespaces) override
Finds a namespace of name name and whose parent context is parent_decl_ctx.
void AddSymbols (Symtab &symtab) override
llvm::Expected< lldb::addr_t > GetParameterStackSize (const Symbol &symbol) override
Return the number of stack bytes taken up by the parameters to this function.
lldb::UnwindPlanSP GetUnwindPlan (const Address &address, const RegisterInfoResolver &resolver) override
llvm::StringRef GetPluginName () override
uint64_t GetDebugInfoSize (bool load_all_debug_info=false) override
Metrics gathering functions.
Public Member Functions inherited from lldb_private::SymbolFileCommon
SymbolFileCommon (lldb::ObjectFileSP objfile_sp)
~SymbolFileCommon () override=default
uint32_t GetAbilities () override
Get a mask of what this symbol file supports for the object file that it was constructed with.
Symtab * GetSymtab (bool can_create=true) override
ObjectFile * GetObjectFile () override
const ObjectFile * GetObjectFile () const override
ObjectFile * GetMainObjectFile () override
void SectionFileAddressesChanged () override
Notify the SymbolFile that the file addresses in the Sections for this module have been changed.
uint32_t GetNumCompileUnits () override
lldb::CompUnitSP GetCompileUnitAtIndex (uint32_t idx) override
llvm::Expected< lldb::TypeSystemSP > GetTypeSystemForLanguage (lldb::LanguageType language) override
void Dump (Stream &s) override
uint64_t GetDebugInfoSize (bool load_all_debug_info=false) override
Metrics gathering functions.
bool GetDebugInfoIndexWasLoadedFromCache () const override
Accessors for the bool that indicates if the debug info index was loaded from, or saved to the module index cache.
void SetDebugInfoIndexWasLoadedFromCache () override
bool GetDebugInfoIndexWasSavedToCache () const override
void SetDebugInfoIndexWasSavedToCache () override
bool GetDebugInfoHadFrameVariableErrors () const override
Accessors for the bool that indicates if there was debug info, but errors stopped variables from being able to be displayed correctly.
void SetDebugInfoHadFrameVariableErrors () override
lldb::TypeSP MakeType (lldb::user_id_t uid, ConstString name, std::optional< uint64_t > byte_size, SymbolContextScope *context, lldb::user_id_t encoding_uid, Type::EncodingDataType encoding_uid_type, const Declaration &decl, const CompilerType &compiler_qual_type, Type::ResolveState compiler_type_resolve_state, uint32_t opaque_payload=0) override
This function is used to create types that belong to a SymbolFile.
lldb::TypeSP CopyType (const lldb::TypeSP &other_type) override
bool isA (const void *ClassID) const override
LLVM RTTI support.
Public Member Functions inherited from lldb_private::SymbolFile
SymbolFile ()=default
~SymbolFile () override=default
virtual SymbolFile * GetBackingSymbolFile ()
SymbolFileOnDemand class overrides this to return the underlying backing SymbolFile implementation that loads on-demand.
virtual std::recursive_mutex & GetModuleMutex () const
Symbols file subclasses should override this to return the Module that owns the TypeSystem that this symbol file modifies type information in.
virtual bool GetLoadDebugInfoEnabled ()
Whether debug info will be loaded or not.
virtual void SetLoadDebugInfoEnabled ()
Specify debug info should be loaded.
virtual XcodeSDK ParseXcodeSDK (CompileUnit &comp_unit)
Return the Xcode SDK comp_unit was compiled against.
virtual llvm::SmallSet< lldb::LanguageType, 4 > ParseAllLanguages (CompileUnit &comp_unit)
This function exists because SymbolFileDWARFDebugMap may extra compile units which aren't exposed as "real" compile units.
virtual bool ForEachExternalModule (lldb_private::CompileUnit &comp_unit, llvm::DenseSet< lldb_private::SymbolFile * > &visited_symbol_files, llvm::function_ref< bool(Module &)> lambda)
Apply a lambda to each external lldb::Module referenced by this comp_unit.
virtual bool ParseIsOptimized (CompileUnit &comp_unit)
virtual void ParseDeclsForContext (CompilerDeclContext decl_ctx)
virtual CompilerDecl GetDeclForUID (lldb::user_id_t uid)
virtual CompilerDeclContext GetDeclContextForUID (lldb::user_id_t uid)
virtual CompilerDeclContext GetDeclContextContainingUID (lldb::user_id_t uid)
virtual std::vector< CompilerContext > GetCompilerContextForUID (lldb::user_id_t uid)
Status GetFrameVariableError (StackFrame &frame)
Get an error that describes why variables might be missing for a given symbol context.
virtual Status CalculateFrameVariableError (StackFrame &frame)
Subclasses will override this function to for GetFrameVariableError().
virtual void DumpClangAST (Stream &s, llvm::StringRef filter, bool show_colors)
virtual void FindGlobalVariables (const RegularExpression &regex, uint32_t max_matches, VariableList &variables)
virtual void FindFunctions (llvm::ArrayRef< Module::LookupInfo > lookup_infos, const CompilerDeclContext &parent_decl_ctx, bool include_inlines, SymbolContextList &sc_list)
virtual void FindTypes (const TypeQuery &query, TypeResults &results)
Find types using a type-matching object that contains all search parameters.
virtual void GetMangledNamesForFunction (const std::string &scope_qualified_name, std::vector< ConstString > &mangled_names)
virtual llvm::Expected< SymbolContext > ResolveFunctionCallLabel (FunctionCallLabel &label)
Resolves the function corresponding to the specified LLDB function call label.
virtual void PreloadSymbols ()
virtual std::vector< std::unique_ptr< CallEdge > > ParseCallEdgesInFunction (UserID func_id)
virtual StatsDuration::Duration GetDebugInfoParseTime ()
Return the time taken to parse the debug information.
virtual StatsDuration::Duration GetDebugInfoIndexTime ()
Return the time it took to index the debug information in the object file.
virtual void ResetStatistics ()
Reset the statistics for the symbol file.
virtual ModuleList GetDebugInfoModules ()
Get the additional modules that this symbol file uses to parse debug info.
virtual bool GetSeparateDebugInfo (StructuredData::Dictionary &d, bool errors_only, bool load_all_debug_info=false)
Return true if separate debug info files are supported and this function succeeded, false otherwise.
virtual DWOStats GetDwoStats ()
Retrieves statistics about DWO files associated with this symbol file.
std::unordered_map< lldb::CompUnitSP, Args > GetCompileOptions ()
Returns a map of compilation unit to the compile option arguments associated with that compilation unit.
std::string GetObjectName () const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static void DebuggerInitialize (Debugger &debugger)
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static SymbolFile * CreateInstance (lldb::ObjectFileSP objfile_sp)
static bool classof (const SymbolFileCommon *obj)
Static Public Member Functions inherited from lldb_private::SymbolFile
static SymbolFile * FindPlugin (lldb::ObjectFileSP objfile_sp)
static bool classof (const SymbolFile *obj)
Private Types
using CompUnitMap = RangeDataVector<lldb::addr_t, lldb::addr_t, CompUnitData>
using UnwindMap = RangeDataVector<lldb::addr_t, lldb::addr_t, Bookmark>
Private Member Functions
llvm::iterator_range< LineIterator > lines (Record::Kind section_type)
uint32_t CalculateNumCompileUnits () override
lldb::CompUnitSP ParseCompileUnitAtIndex (uint32_t index) override
lldb::addr_t GetBaseFileAddress ()
void ParseFileRecords ()
void ParseCUData ()
void ParseLineTableAndSupportFiles (CompileUnit &cu, CompUnitData &data)
void ParseUnwindData ()
llvm::ArrayRef< uint8_t > SaveAsDWARF (postfix::Node &node)
lldb::UnwindPlanSP ParseCFIUnwindPlan (const Bookmark &bookmark, const RegisterInfoResolver &resolver)
bool ParseCFIUnwindRow (llvm::StringRef unwind_rules, const RegisterInfoResolver &resolver, UnwindPlan::Row &row)
lldb::UnwindPlanSP ParseWinUnwindPlan (const Bookmark &bookmark, const RegisterInfoResolver &resolver)
void ParseInlineOriginRecords ()
Private Attributes
std::optional< std::vector< FileSpec > > m_files
std::optional< CompUnitMap > m_cu_data
std::optional< std::vector< llvm::StringRef > > m_inline_origins
std::optional< UnwindData > m_unwind_data
llvm::BumpPtrAllocator m_allocator
Static Private Attributes
static char ID
LLVM RTTI support.
bool isA (const void *ClassID) const override
LLVM RTTI support.
static bool classof (const SymbolFile *obj)
Additional Inherited Members
Public Types inherited from lldb_private::SymbolFile
enum Abilities {
CompileUnits = (1u << 0) , LineTables = (1u << 1) , Functions = (1u << 2) , Blocks = (1u << 3) ,
GlobalVariables = (1u << 4) , LocalVariables = (1u << 5) , VariableTypes = (1u << 6) , kAllAbilities = ((1u << 7) - 1u)
}
Protected Member Functions inherited from lldb_private::SymbolFileCommon
virtual TypeList & GetTypeList ()
void SetCompileUnitAtIndex (uint32_t idx, const lldb::CompUnitSP &cu_sp)
Protected Member Functions inherited from lldb_private::SymbolFile
void AssertModuleLock ()
virtual void GetCompileOptions (std::unordered_map< lldb::CompUnitSP, lldb_private::Args > &args)
Protected Attributes inherited from lldb_private::SymbolFileCommon
lldb::ObjectFileSP m_objfile_sp
std::optional< std::vector< lldb::CompUnitSP > > m_compile_units
TypeList m_type_list
uint32_t m_abilities = 0
bool m_calculated_abilities = false
bool m_index_was_loaded_from_cache = false
bool m_index_was_saved_to_cache = false
bool m_debug_info_had_variable_errors = false
Set to true if any variable feteching errors have been found when calling GetFrameVariableError().
Detailed Description
Definition at line 24 of file SymbolFileBreakpad.h.
Member Typedef Documentation
CompUnitMap
using lldb_private::breakpad::SymbolFileBreakpad::CompUnitMap = RangeDataVector<lldb::addr_t, lldb::addr_t, CompUnitData> private
Definition at line 218 of file SymbolFileBreakpad.h.
UnwindMap
using lldb_private::breakpad::SymbolFileBreakpad::UnwindMap = RangeDataVector<lldb::addr_t, lldb::addr_t, Bookmark> private
Definition at line 224 of file SymbolFileBreakpad.h.
Constructor & Destructor Documentation
SymbolFileBreakpad()
lldb_private::breakpad::SymbolFileBreakpad::SymbolFileBreakpad (lldb::ObjectFileSP objfile_sp) inline
Definition at line 52 of file SymbolFileBreakpad.h.
References lldb_private::SymbolFileCommon::SymbolFileCommon().
Referenced by CreateInstance().
~SymbolFileBreakpad()
lldb_private::breakpad::SymbolFileBreakpad::~SymbolFileBreakpad () override default
Member Function Documentation
AddSymbols()
void SymbolFileBreakpad::AddSymbols (Symtab & symtab) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 451 of file SymbolFileBreakpad.cpp.
References lldb_private::Symtab::AddSymbol(), lldb::eSymbolTypeCode, lldb_private::Symtab::Finalize(), lldb_private::SectionList::FindSectionContainingFileAddress(), GetBaseFileAddress(), lldb_private::GetLog(), lines(), LLDB_INVALID_ADDRESS, LLDB_LOG, lldb_private::SymbolFileCommon::m_objfile_sp, lldb_private::breakpad::PublicRecord::parse(), lldb_private::breakpad::Record::Public, and lldb_private::Symbols.
CalculateAbilities()
uint32_t SymbolFileBreakpad::CalculateAbilities () override virtual
Implements lldb_private::SymbolFile.
Definition at line 181 of file SymbolFileBreakpad.cpp.
References lldb_private::SymbolFile::CompileUnits, lldb_private::SymbolFile::Functions, lldb_private::SymbolFile::LineTables, and lldb_private::SymbolFileCommon::m_objfile_sp.
CalculateNumCompileUnits()
uint32_t SymbolFileBreakpad::CalculateNumCompileUnits () override private virtual
Implements lldb_private::SymbolFileCommon.
Definition at line 188 of file SymbolFileBreakpad.cpp.
References m_cu_data, and ParseCUData().
classof()
bool lldb_private::breakpad::SymbolFileBreakpad::classof (const SymbolFile * obj) inline static
Definition at line 34 of file SymbolFileBreakpad.h.
References ID, lldb_private::SymbolFile::isA(), and lldb_private::SymbolFile::SymbolFile().
CompleteType()
bool lldb_private::breakpad::SymbolFileBreakpad::CompleteType (CompilerType & compiler_type) inline override virtual
Implements lldb_private::SymbolFile.
Definition at line 102 of file SymbolFileBreakpad.h.
CreateInstance()
SymbolFile * lldb_private::breakpad::SymbolFileBreakpad::CreateInstance (lldb::ObjectFileSP objfile_sp) inline static
Definition at line 47 of file SymbolFileBreakpad.h.
References lldb_private::SymbolFile::SymbolFile(), and SymbolFileBreakpad().
Referenced by Initialize(), and Terminate().
DebuggerInitialize()
void lldb_private::breakpad::SymbolFileBreakpad::DebuggerInitialize (Debugger & debugger) inline static
Definition at line 40 of file SymbolFileBreakpad.h.
Referenced by Initialize().
FindFunctions() [1/2]
void SymbolFileBreakpad::FindFunctions (const Module::LookupInfo & lookup_info, const CompilerDeclContext & parent_decl_ctx, bool include_inlines, SymbolContextList & sc_list) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 424 of file SymbolFileBreakpad.cpp.
References lldb_private::SymbolContextList::AppendIfUnique(), lldb_private::SymbolContext::comp_unit, lldb_private::SymbolContext::function, lldb_private::SymbolFileCommon::GetCompileUnitAtIndex(), lldb_private::Module::LookupInfo::GetLookupName(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::SymbolFileCommon::GetNumCompileUnits(), GetOrCreateFunction(), and lldb_private::SymbolContext::module_sp.
FindFunctions() [2/2]
void SymbolFileBreakpad::FindFunctions (const RegularExpression & regex, bool include_inlines, SymbolContextList & sc_list) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 445 of file SymbolFileBreakpad.cpp.
FindGlobalVariables()
void lldb_private::breakpad::SymbolFileBreakpad::FindGlobalVariables (ConstString name, const CompilerDeclContext & parent_decl_ctx, uint32_t max_matches, VariableList & variables) inline override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 87 of file SymbolFileBreakpad.h.
FindNamespace()
CompilerDeclContext lldb_private::breakpad::SymbolFileBreakpad::FindNamespace (ConstString name, const CompilerDeclContext & parent_decl_ctx, bool only_root_namespaces) inline override virtual
Finds a namespace of name name and whose parent context is parent_decl_ctx.
If
!parent_decl_ctx.IsValid()
then this function will consider all namespaces that match the name. If only_root_namespaces is true, only consider in the search those DIEs that represent top-level namespaces.
Reimplemented from lldb_private::SymbolFile.
Definition at line 127 of file SymbolFileBreakpad.h.
GetBaseFileAddress()
addr_t SymbolFileBreakpad::GetBaseFileAddress () private
Definition at line 773 of file SymbolFileBreakpad.cpp.
References lldb_private::SymbolFileCommon::m_objfile_sp.
Referenced by AddSymbols(), GetOrCreateFunction(), ParseCFIUnwindPlan(), ParseCUData(), ParseLineTableAndSupportFiles(), ParseUnwindData(), and ParseWinUnwindPlan().
GetDebugInfoSize()
uint64_t SymbolFileBreakpad::GetDebugInfoSize (bool load_all_debug_info = false) override virtual
Metrics gathering functions.
Return the size in bytes of all loaded debug information or total possible debug info in the symbol file.
If the debug information is contained in sections of an ObjectFile, then this call should add the size of all sections that contain debug information. Symbols the symbol tables are not considered debug information for this call to make it easy and quick for this number to be calculated. If the symbol file is all debug information, the size of the entire file should be returned. The default implementation of this function will iterate over all sections in a module and add up their debug info only section byte sizes.
Parameters
load_all_debug_info If true, force loading any symbol files if they are not yet loaded and add to the total size. Default to false.
Returns
Total currently loaded debug info size in bytes
Implements lldb_private::SymbolFile.
Definition at line 914 of file SymbolFileBreakpad.cpp.
References lldb_private::SymbolFileCommon::m_objfile_sp.
GetDynamicArrayInfoForUID()
std::optional< ArrayInfo > lldb_private::breakpad::SymbolFileBreakpad::GetDynamicArrayInfoForUID (lldb::user_id_t type_uid, const lldb_private::ExecutionContext * exe_ctx) inline override virtual
If type_uid points to an array type, return its characteristics.
To support variable-length array types, this function takes an optional ExecutionContext. If exe_ctx is non-null, the dynamic characteristics for that context are returned.
Implements lldb_private::SymbolFile.
Definition at line 96 of file SymbolFileBreakpad.h.
GetOrCreateFunction()
FunctionSP SymbolFileBreakpad::GetOrCreateFunction (CompileUnit & comp_unit)
Definition at line 229 of file SymbolFileBreakpad.cpp.
References lldb_private::CompileUnit::AddFunction(), lldb_private::breakpad::SymbolFileBreakpad::CompUnitData::bookmark, lldb_private::breakpad::Record::classify(), lldb_private::CompileUnit::FindFunctionByUID(), lldb_private::SectionList::FindSectionContainingFileAddress(), lldb_private::breakpad::Record::Func, GetBaseFileAddress(), lldb_private::UserID::GetID(), lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), LLDB_INVALID_ADDRESS, LLDB_LOG, m_cu_data, lldb_private::SymbolFileCommon::m_objfile_sp, lldb_private::breakpad::FuncRecord::parse(), lldb_private::Mangled::SetValue(), and lldb_private::Symbols.
Referenced by FindFunctions(), and ParseFunctions().
GetParameterStackSize()
llvm::Expected< lldb::addr_t > SymbolFileBreakpad::GetParameterStackSize (const Symbol & symbol) override virtual
Return the number of stack bytes taken up by the parameters to this function.
Reimplemented from lldb_private::SymbolFile.
Definition at line 501 of file SymbolFileBreakpad.cpp.
References lldb_private::Symbol::GetAddress(), lldb_private::Address::GetFileAddress(), lldb_private::SymbolFileCommon::m_objfile_sp, m_unwind_data, lldb_private::breakpad::StackWinRecord::parse(), ParseUnwindData(), and lldb_private::breakpad::Record::StackWin.
GetPluginDescriptionStatic()
llvm::StringRef lldb_private::breakpad::SymbolFileBreakpad::GetPluginDescriptionStatic () inline static
Definition at line 43 of file SymbolFileBreakpad.h.
Referenced by Initialize().
GetPluginName()
llvm::StringRef lldb_private::breakpad::SymbolFileBreakpad::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 142 of file SymbolFileBreakpad.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::breakpad::SymbolFileBreakpad::GetPluginNameStatic () inline static
Definition at line 41 of file SymbolFileBreakpad.h.
Referenced by GetPluginName(), and Initialize().
GetTypes()
void lldb_private::breakpad::SymbolFileBreakpad::GetTypes (SymbolContextScope * sc_scope, lldb::TypeClass type_mask, TypeList & type_list) inline override virtual
Implements lldb_private::SymbolFile.
Definition at line 111 of file SymbolFileBreakpad.h.
GetTypeSystemForLanguage()
llvm::Expected< lldb::TypeSystemSP > lldb_private::breakpad::SymbolFileBreakpad::GetTypeSystemForLanguage (lldb::LanguageType language) inline override virtual
Implements lldb_private::SymbolFile.
Definition at line 122 of file SymbolFileBreakpad.h.
GetUnwindPlan()
UnwindPlanSP SymbolFileBreakpad::GetUnwindPlan (const Address & address, const RegisterInfoResolver & resolver) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 629 of file SymbolFileBreakpad.cpp.
References lldb_private::Address::GetFileAddress(), m_unwind_data, ParseCFIUnwindPlan(), ParseUnwindData(), and ParseWinUnwindPlan().
Initialize()
void SymbolFileBreakpad::Initialize () static
Definition at line 171 of file SymbolFileBreakpad.cpp.
References CreateInstance(), DebuggerInitialize(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
InitializeObject()
void lldb_private::breakpad::SymbolFileBreakpad::InitializeObject () inline override virtual
Initialize the SymbolFile object.
The SymbolFile object with the best set of abilities (detected in "uint32_t SymbolFile::GetAbilities()) will have this function called if it is chosen to parse an object file. More complete initialization can happen in this function which will get called prior to any other functions in the SymbolFile protocol.
Reimplemented from lldb_private::SymbolFile.
Definition at line 59 of file SymbolFileBreakpad.h.
isA()
bool lldb_private::breakpad::SymbolFileBreakpad::isA (const void * ClassID) const inline override virtual
LLVM RTTI support.
Reimplemented from lldb_private::SymbolFile.
Definition at line 31 of file SymbolFileBreakpad.h.
References ID, and lldb_private::SymbolFileCommon::isA().
lines()
llvm::iterator_range< SymbolFileBreakpad::LineIterator > SymbolFileBreakpad::lines (Record::Kind section_type) private
Definition at line 133 of file SymbolFileBreakpad.cpp.
References lldb_private::SymbolFileCommon::m_objfile_sp.
Referenced by AddSymbols(), ParseFileRecords(), and ParseInlineOriginRecords().
ParseBlocksRecursive()
size_t SymbolFileBreakpad::ParseBlocksRecursive (Function & func) override virtual
Implements lldb_private::SymbolFile.
Definition at line 293 of file SymbolFileBreakpad.cpp.
References lldb_private::breakpad::SymbolFileBreakpad::CompUnitData::bookmark, lldb_private::breakpad::Record::classify(), lldb_private::breakpad::Record::Func, lldb_private::Function::GetAddress(), lldb_private::Function::GetBlock(), lldb_private::Function::GetCompileUnit(), lldb_private::UserID::GetID(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::Address::GetOffset(), lldb_private::breakpad::Record::Inline, lldbassert, m_cu_data, m_files, m_inline_origins, lldb_private::SymbolFileCommon::m_objfile_sp, lldb_private::breakpad::InlineRecord::parse(), and ParseInlineOriginRecords().
ParseCFIUnwindPlan()
UnwindPlanSP SymbolFileBreakpad::ParseCFIUnwindPlan (const Bookmark & bookmark, const RegisterInfoResolver & resolver) private
Definition at line 642 of file SymbolFileBreakpad.cpp.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb::eRegisterKindLLDB, GetBaseFileAddress(), LLDB_INVALID_ADDRESS, lldb_private::SymbolFileCommon::m_objfile_sp, lldb_private::breakpad::StackCFIRecord::parse(), ParseCFIUnwindRow(), lldb_private::UnwindPlan::Row::SetOffset(), and lldb_private::breakpad::Record::StackCFI.
Referenced by GetUnwindPlan().
ParseCFIUnwindRow()
bool SymbolFileBreakpad::ParseCFIUnwindRow (llvm::StringRef unwind_rules, const RegisterInfoResolver & resolver, UnwindPlan::Row & row) private
Definition at line 575 of file SymbolFileBreakpad.cpp.
References lldb::eRegisterKindLLDB, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::GetLog(), lldb_private::postfix::SymbolNode::GetName(), GetRule(), LLDB_LOG, lldb_private::SymbolFileCommon::m_objfile_sp, lldb_private::postfix::MakeNode(), lldb_private::postfix::ParseOneExpression(), ResolveRegister(), ResolveRegisterOrRA(), lldb_private::postfix::ResolveSymbols(), SaveAsDWARF(), lldb_private::UnwindPlan::Row::AbstractRegisterLocation::SetIsDWARFExpression(), lldb_private::UnwindPlan::Row::FAValue::SetIsDWARFExpression(), lldb_private::UnwindPlan::Row::SetRegisterInfo(), and lldb_private::Symbols.
Referenced by ParseCFIUnwindPlan().
ParseCompileUnitAtIndex()
CompUnitSP SymbolFileBreakpad::ParseCompileUnitAtIndex (uint32_t index) override private virtual
Implements lldb_private::SymbolFileCommon.
Definition at line 193 of file SymbolFileBreakpad.cpp.
References lldb_private::breakpad::SymbolFileBreakpad::CompUnitData::bookmark, lldb_private::breakpad::Record::classify(), lldb::eLanguageTypeUnknown, lldb_private::eLazyBoolNo, lldb_private::breakpad::Record::Func, lldb_private::breakpad::Record::Inline, m_cu_data, m_files, lldb_private::SymbolFileCommon::m_objfile_sp, lldb_private::breakpad::LineRecord::parse(), ParseFileRecords(), and lldb_private::SymbolFileCommon::SetCompileUnitAtIndex().
ParseCUData()
void SymbolFileBreakpad::ParseCUData () private
Definition at line 803 of file SymbolFileBreakpad.cpp.
References lldb_private::breakpad::Record::Func, GetBaseFileAddress(), lldb_private::GetLog(), LLDB_INVALID_ADDRESS, LLDB_LOG, m_cu_data, lldb_private::SymbolFileCommon::m_objfile_sp, lldb_private::breakpad::FuncRecord::parse(), and lldb_private::Symbols.
Referenced by CalculateNumCompileUnits().
ParseDebugMacros()
bool lldb_private::breakpad::SymbolFileBreakpad::ParseDebugMacros (CompileUnit & comp_unit) inline override virtual
Implements lldb_private::SymbolFile.
Definition at line 73 of file SymbolFileBreakpad.h.
ParseFileRecords()
void SymbolFileBreakpad::ParseFileRecords () private
Definition at line 782 of file SymbolFileBreakpad.cpp.
References lldb_private::breakpad::Record::File, lldb_private::GetLog(), lldb_private::FileSpec::GuessPathStyle(), lines(), LLDB_LOG, m_files, lldb_private::breakpad::FileRecord::parse(), and lldb_private::Symbols.
Referenced by ParseCompileUnitAtIndex().
ParseFunctions()
size_t SymbolFileBreakpad::ParseFunctions (CompileUnit & comp_unit) override virtual
Implements lldb_private::SymbolFile.
Definition at line 265 of file SymbolFileBreakpad.cpp.
References lldb_private::SymbolFile::GetModuleMutex(), and GetOrCreateFunction().
ParseImportedModules()
bool lldb_private::breakpad::SymbolFileBreakpad::ParseImportedModules (const SymbolContext & sc, std::vector< lldb_private::SourceModule > & imported_modules) inline override virtual
Implements lldb_private::SymbolFile.
Definition at line 79 of file SymbolFileBreakpad.h.
ParseInlineOriginRecords()
void SymbolFileBreakpad::ParseInlineOriginRecords () private
Definition at line 347 of file SymbolFileBreakpad.cpp.
References lldb_private::GetLog(), lldb_private::breakpad::Record::InlineOrigin, lines(), LLDB_LOG, m_inline_origins, lldb_private::breakpad::InlineOriginRecord::parse(), and lldb_private::Symbols.
Referenced by ParseBlocksRecursive().
ParseLanguage()
lldb::LanguageType lldb_private::breakpad::SymbolFileBreakpad::ParseLanguage (CompileUnit & comp_unit) inline override virtual
Implements lldb_private::SymbolFile.
Definition at line 63 of file SymbolFileBreakpad.h.
References lldb::eLanguageTypeUnknown.
ParseLineTable()
bool SymbolFileBreakpad::ParseLineTable (CompileUnit & comp_unit) override virtual
Implements lldb_private::SymbolFile.
Definition at line 270 of file SymbolFileBreakpad.cpp.
References lldb_private::UserID::GetID(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::breakpad::SymbolFileBreakpad::CompUnitData::line_table_up, m_cu_data, ParseLineTableAndSupportFiles(), and lldb_private::CompileUnit::SetLineTable().
ParseLineTableAndSupportFiles()
void SymbolFileBreakpad::ParseLineTableAndSupportFiles (CompileUnit & cu, CompUnitData & data) private
Definition at line 830 of file SymbolFileBreakpad.cpp.
References lldb_private::LineTable::AppendLineEntryToSequence(), lldb_private::breakpad::SymbolFileBreakpad::CompUnitData::bookmark, lldb_private::breakpad::Record::classify(), lldb_private::breakpad::Record::Func, GetBaseFileAddress(), lldb_private::CompileUnit::GetPrimaryFile(), lldb_private::breakpad::Record::Inline, lldb_private::breakpad::SymbolFileBreakpad::CompUnitData::line_table_up, LLDB_INVALID_ADDRESS, m_files, lldb_private::SymbolFileCommon::m_objfile_sp, lldb_private::breakpad::LineRecord::parse(), and lldb_private::breakpad::SymbolFileBreakpad::CompUnitData::support_files.
Referenced by ParseLineTable(), and ParseSupportFiles().
ParseSupportFiles()
bool SymbolFileBreakpad::ParseSupportFiles (CompileUnit & comp_unit, SupportFileList & support_files) override virtual
Implements lldb_private::SymbolFile.
Definition at line 281 of file SymbolFileBreakpad.cpp.
References lldb_private::SupportFileList::Append(), lldb_private::UserID::GetID(), lldb_private::SymbolFile::GetModuleMutex(), m_cu_data, ParseLineTableAndSupportFiles(), and lldb_private::breakpad::SymbolFileBreakpad::CompUnitData::support_files.
ParseTypes()
size_t lldb_private::breakpad::SymbolFileBreakpad::ParseTypes (CompileUnit & cu) inline override virtual
Implements lldb_private::SymbolFile.
Definition at line 77 of file SymbolFileBreakpad.h.
ParseUnwindData()
void SymbolFileBreakpad::ParseUnwindData () private
Definition at line 880 of file SymbolFileBreakpad.cpp.
References GetBaseFileAddress(), lldb_private::GetLog(), LLDB_INVALID_ADDRESS, LLDB_LOG, lldb_private::SymbolFileCommon::m_objfile_sp, m_unwind_data, lldb_private::breakpad::StackCFIRecord::parse(), lldb_private::breakpad::StackWinRecord::parse(), lldb_private::breakpad::Record::StackCFI, lldb_private::breakpad::Record::StackWin, and lldb_private::Symbols.
Referenced by GetParameterStackSize(), and GetUnwindPlan().
ParseVariablesForContext()
size_t lldb_private::breakpad::SymbolFileBreakpad::ParseVariablesForContext (const SymbolContext & sc) inline override virtual
Implements lldb_private::SymbolFile.
Definition at line 92 of file SymbolFileBreakpad.h.
ParseWinUnwindPlan()
UnwindPlanSP SymbolFileBreakpad::ParseWinUnwindPlan (const Bookmark & bookmark, const RegisterInfoResolver & resolver) private
Definition at line 683 of file SymbolFileBreakpad.cpp.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb::eRegisterKindLLDB, GetBaseFileAddress(), lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::GetLog(), lldb_private::RegisterInfo::kinds, LLDB_INVALID_ADDRESS, LLDB_LOG, lldb_private::SymbolFileCommon::m_objfile_sp, lldb_private::postfix::MakeNode(), lldb_private::breakpad::StackWinRecord::parse(), lldb_private::postfix::ParseFPOProgram(), ResolveRegister(), lldb_private::postfix::ResolveSymbols(), SaveAsDWARF(), lldb_private::UnwindPlan::Row::AbstractRegisterLocation::SetIsDWARFExpression(), lldb_private::UnwindPlan::Row::FAValue::SetIsDWARFExpression(), lldb_private::UnwindPlan::Row::FAValue::SetRaSearch(), lldb_private::UnwindPlan::Row::SetRegisterInfo(), lldb_private::breakpad::Record::StackWin, and lldb_private::Symbols.
Referenced by GetUnwindPlan().
ResolveSymbolContext() [1/2]
uint32_t lldb_private::breakpad::SymbolFileBreakpad::ResolveSymbolContext (const Address & so_addr, lldb::SymbolContextItem resolve_scope, SymbolContext & sc) override virtual
Implements lldb_private::SymbolFile.
ResolveSymbolContext() [2/2]
uint32_t SymbolFileBreakpad::ResolveSymbolContext (const SourceLocationSpec & src_location_spec, lldb::SymbolContextItem resolve_scope, SymbolContextList & sc_list) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 409 of file SymbolFileBreakpad.cpp.
References lldb_private::SymbolFileCommon::GetCompileUnitAtIndex(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::SymbolFileCommon::GetNumCompileUnits(), lldb_private::SymbolContextList::GetSize(), and lldb_private::CompileUnit::ResolveSymbolContext().
ResolveTypeUID()
Type * lldb_private::breakpad::SymbolFileBreakpad::ResolveTypeUID (lldb::user_id_t type_uid) inline override virtual
Implements lldb_private::SymbolFile.
Definition at line 95 of file SymbolFileBreakpad.h.
SaveAsDWARF()
llvm::ArrayRef< uint8_t > SymbolFileBreakpad::SaveAsDWARF (postfix::Node & node) private
Definition at line 565 of file SymbolFileBreakpad.cpp.
References lldb_private::Stream::eBinary, lldb_private::ArchSpec::GetAddressByteSize(), lldb_private::ArchSpec::GetByteOrder(), m_allocator, and lldb_private::SymbolFileCommon::m_objfile_sp.
Referenced by ParseCFIUnwindRow(), and ParseWinUnwindPlan().
Terminate()
void SymbolFileBreakpad::Terminate () static
Definition at line 177 of file SymbolFileBreakpad.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Member Data Documentation
ID
char SymbolFileBreakpad::ID static private
LLVM RTTI support.
Definition at line 26 of file SymbolFileBreakpad.h.
Referenced by classof(), and isA().
m_allocator
llvm::BumpPtrAllocator lldb_private::breakpad::SymbolFileBreakpad::m_allocator private
Definition at line 230 of file SymbolFileBreakpad.h.
Referenced by SaveAsDWARF().
m_cu_data
std::optional<CompUnitMap> lldb_private::breakpad::SymbolFileBreakpad::m_cu_data private
Definition at line 221 of file SymbolFileBreakpad.h.
Referenced by CalculateNumCompileUnits(), GetOrCreateFunction(), ParseBlocksRecursive(), ParseCompileUnitAtIndex(), ParseCUData(), ParseLineTable(), and ParseSupportFiles().
m_files
std::optional<std::vector<FileSpec> > lldb_private::breakpad::SymbolFileBreakpad::m_files private
Definition at line 220 of file SymbolFileBreakpad.h.
Referenced by ParseBlocksRecursive(), ParseCompileUnitAtIndex(), ParseFileRecords(), and ParseLineTableAndSupportFiles().
m_inline_origins
std::optional<std::vector<llvm::StringRef> > lldb_private::breakpad::SymbolFileBreakpad::m_inline_origins private
Definition at line 222 of file SymbolFileBreakpad.h.
Referenced by ParseBlocksRecursive(), and ParseInlineOriginRecords().
m_unwind_data
std::optional<UnwindData> lldb_private::breakpad::SymbolFileBreakpad::m_unwind_data private
Definition at line 229 of file SymbolFileBreakpad.h.
Referenced by GetParameterStackSize(), GetUnwindPlan(), and ParseUnwindData().
The documentation for this class was generated from the following files:
SymbolFileBreakpad.h
SymbolFileBreakpad.cpp