LLDB: lldb_private::MemoryHistoryASan Class Reference
lldb_private::MemoryHistoryASan Class Reference
#include <MemoryHistoryASan.h>
Public Member Functions
~MemoryHistoryASan () override=default
llvm::StringRef GetPluginName () override
lldb_private::HistoryThreads GetHistoryThreads (lldb::addr_t address) override
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static lldb::MemoryHistorySP CreateInstance (const lldb::ProcessSP &process_sp)
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
Static Public Member Functions inherited from lldb_private::MemoryHistory
static lldb::MemoryHistorySP FindPlugin (const lldb::ProcessSP process)
Private Member Functions
MemoryHistoryASan (const lldb::ProcessSP &process_sp)
Private Attributes
lldb::ProcessWP m_process_wp
Detailed Description
Definition at line 19 of file MemoryHistoryASan.h.
Constructor & Destructor Documentation
~MemoryHistoryASan()
lldb_private::MemoryHistoryASan::~MemoryHistoryASan () override default
MemoryHistoryASan()
MemoryHistoryASan::MemoryHistoryASan (const lldb::ProcessSP & process_sp) private
Definition at line 61 of file MemoryHistoryASan.cpp.
References m_process_wp.
Referenced by CreateInstance().
Member Function Documentation
CreateInstance()
MemoryHistorySP MemoryHistoryASan::CreateInstance (const lldb::ProcessSP & process_sp) static
Definition at line 35 of file MemoryHistoryASan.cpp.
References CreateInstance(), and MemoryHistoryASan().
Referenced by CreateInstance(), Initialize(), and Terminate().
GetHistoryThreads()
HistoryThreads MemoryHistoryASan::GetHistoryThreads (lldb::addr_t address) override virtual
Implements lldb_private::MemoryHistory.
Definition at line 141 of file MemoryHistoryASan.cpp.
References lldb_private::SymbolContextList::Append(), CreateHistoryThreadFromValueObject(), DoNoSelectMostRelevantFrame, lldb::eExpressionCompleted, lldb::eLanguageTypeObjC_plus_plus, lldb_private::UserExpression::Evaluate(), lldb_private::GetPreferredAsanModule(), lldb_private::StreamString::GetString(), m_process_wp, memory_history_asan_command_format, memory_history_asan_command_prefix, lldb_private::Stream::Printf(), lldb_private::Debugger::ReportWarning(), lldb_private::EvaluateExpressionOptions::SetAutoApplyFixIts(), lldb_private::EvaluateExpressionOptions::SetIgnoreBreakpoints(), lldb_private::EvaluateExpressionOptions::SetLanguage(), lldb_private::EvaluateExpressionOptions::SetPreferredSymbolContexts(), lldb_private::EvaluateExpressionOptions::SetPrefix(), lldb_private::EvaluateExpressionOptions::SetStopOthers(), lldb_private::EvaluateExpressionOptions::SetTimeout(), lldb_private::EvaluateExpressionOptions::SetTryAllThreads(), and lldb_private::EvaluateExpressionOptions::SetUnwindOnError().
GetPluginName()
llvm::StringRef lldb_private::MemoryHistoryASan::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 32 of file MemoryHistoryASan.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::MemoryHistoryASan::GetPluginNameStatic () inline static
Definition at line 30 of file MemoryHistoryASan.h.
Referenced by GetPluginName(), and Initialize().
Initialize()
void MemoryHistoryASan::Initialize () static
Definition at line 52 of file MemoryHistoryASan.cpp.
References CreateInstance(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Terminate()
void MemoryHistoryASan::Terminate () static
Definition at line 57 of file MemoryHistoryASan.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Member Data Documentation
m_process_wp
lldb::ProcessWP lldb_private::MemoryHistoryASan::m_process_wp private
Definition at line 39 of file MemoryHistoryASan.h.
Referenced by GetHistoryThreads(), and MemoryHistoryASan().
The documentation for this class was generated from the following files:
MemoryHistoryASan.h
MemoryHistoryASan.cpp