LLDB: lldb_private::Declaration Class Reference
lldb_private::Declaration Class Reference
A class that describes the declaration location of a lldb object.
#include "lldb/Core/Declaration.h"
Public Member Functions
Declaration ()=default
Default constructor.
Declaration (const FileSpec &file_spec, uint32_t line=0, uint16_t column=LLDB_INVALID_COLUMN_NUMBER)
Construct with file specification, and optional line and column.
Declaration (const Declaration *decl_ptr)
Construct with a pointer to another Declaration object.
void Clear ()
Clear the object's state.
bool FileAndLineEqual (const Declaration &declaration, bool full) const
Checks if this object has the same file and line as another declaration object.
void Dump (Stream *s, bool show_fullpaths) const
Dump a description of this object to a Stream.
bool DumpStopContext (Stream *s, bool show_fullpaths) const
FileSpec & GetFile ()
Get accessor for file specification.
const FileSpec & GetFile () const
Get const accessor for file specification.
uint32_t GetLine () const
Get accessor for the declaration line number.
uint16_t GetColumn () const
Get accessor for the declaration column number.
operator bool () const
Convert to boolean operator.
bool IsValid () const
size_t MemorySize () const
Get the memory cost of this object.
void SetFile (const FileSpec &file_spec)
Set accessor for the declaration file specification.
void SetLine (uint32_t line)
Set accessor for the declaration line number.
void SetColumn (uint16_t column)
Set accessor for the declaration column number.
Static Public Member Functions
static int Compare (const Declaration &lhs, const Declaration &rhs)
Compare two declaration objects.
Protected Attributes
FileSpec m_file
The file specification that points to the source file where the declaration occurred.
uint32_t m_line = 0
Non-zero values indicates a valid line number, zero indicates no line number information is available.
uint16_t m_column = LLDB_INVALID_COLUMN_NUMBER
Non-zero values indicates a valid column number, zero indicates no column information is available.
Detailed Description
A class that describes the declaration location of a lldb object.
The declarations include the file specification, line number, and the column info and can help track where functions, blocks, inlined functions, types, variables, any many other debug core objects were declared.
Definition at line 24 of file Declaration.h.
Constructor & Destructor Documentation
Declaration() [1/3]
lldb_private::Declaration::Declaration () default
Default constructor.
Referenced by Compare(), Declaration(), FileAndLineEqual(), and MemorySize().
Declaration() [2/3]
lldb_private::Declaration::Declaration (const FileSpec & file_spec, uint32_t line = 0, uint16_t column = LLDB_INVALID_COLUMN_NUMBER) inline
Construct with file specification, and optional line and column.
Parameters
[in] file_spec The file specification that describes where this was declared.
[in] line The line number that describes where this was declared. Set to zero if there is no line number information.
[in] column The column number that describes where this was declared. Set to zero if there is no column number information.
Definition at line 42 of file Declaration.h.
References LLDB_INVALID_COLUMN_NUMBER, m_column, m_file, and m_line.
Declaration() [3/3]
lldb_private::Declaration::Declaration (const Declaration * decl_ptr) inline
Construct with a pointer to another Declaration object.
Definition at line 47 of file Declaration.h.
References Declaration(), LLDB_INVALID_COLUMN_NUMBER, m_column, and m_line.
Member Function Documentation
Clear()
void lldb_private::Declaration::Clear () inline
Clear the object's state.
Sets the file specification to be empty, and the line and column to zero.
Definition at line 57 of file Declaration.h.
References m_column, m_file, and m_line.
Referenced by lldb_private::ValueObject::GetDeclaration(), and DWARFASTParserClang::GetUniqueTypeNameAndDeclaration().
Compare()
int Declaration::Compare (const Declaration & lhs, const Declaration & rhs) static
Compare two declaration objects.
Compares the two file specifications from lhs and rhs. If the file specifications are equal, then continue to compare the line number and column numbers respectively.
Parameters
[in] lhs The Left Hand Side const Declaration object reference.
[in] rhs The Right Hand Side const Declaration object reference.
Returns
-1 if lhs < rhs 0 if lhs == rhs 1 if lhs > rhs
Definition at line 58 of file Declaration.cpp.
References lldb_private::FileSpec::Compare(), Declaration(), m_column, m_file, and m_line.
Referenced by lldb_private::FunctionInfo::Compare(), lldb_private::SourceLocationSpec::Compare(), lldb::SBDeclaration::operator!=(), and lldb::SBDeclaration::operator==().
Dump()
void Declaration::Dump (Stream * s, bool show_fullpaths) const
Dump a description of this object to a Stream.
Dump a description of the contents of this object to the supplied stream s.
Parameters
[in] s The stream to which to dump the object description.
Definition at line 14 of file Declaration.cpp.
References LLDB_INVALID_COLUMN_NUMBER, m_column, m_file, m_line, and lldb_private::Stream::Printf().
DumpStopContext()
bool Declaration::DumpStopContext (Stream * s, bool show_fullpaths) const
Definition at line 35 of file Declaration.cpp.
References LLDB_INVALID_COLUMN_NUMBER, m_column, m_file, m_line, and lldb_private::Stream::Printf().
Referenced by lldb::SBValue::Watch().
FileAndLineEqual()
bool Declaration::FileAndLineEqual (const Declaration & declaration, bool full) const
Checks if this object has the same file and line as another declaration object.
Parameters
[in] declaration The const Declaration object to compare with.
[in] full Same meaning as Full in FileSpec::Equal. True means an empty directory is not equal to a specified one, false means it is equal.
Returns
Returns true if declaration is at the same file and line, false otherwise.
Definition at line 73 of file Declaration.cpp.
References lldb_private::FileSpec::Compare(), Declaration(), m_file, and m_line.
Referenced by lldb_private::CompileUnit::ResolveSymbolContext().
GetColumn()
uint16_t lldb_private::Declaration::GetColumn () const inline
Get accessor for the declaration column number.
Returns
Non-zero indicates a valid column number, zero indicates no column information is available.
Definition at line 131 of file Declaration.h.
References m_column.
Referenced by lldb::SBBlock::GetInlinedCallSiteColumn(), lldb_private::SymbolContext::GetParentOfInlinedScope(), lldb_private::operator==(), lldb_private::CompileUnit::ResolveSymbolContext(), and lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint().
GetFile() [1/2]
FileSpec & lldb_private::Declaration::GetFile () inline
Get accessor for file specification.
Returns
A reference to the file specification object.
Definition at line 111 of file Declaration.h.
References m_file.
Referenced by lldb_private::Block::AddRange(), lldb_private::VariableAnnotator::AnnotateStructured(), lldb_private::BreakpointResolverFileLine::FilterContexts(), lldb::SBBlock::GetInlinedCallSiteFile(), lldb_private::InstrumentationRuntimeTSan::GetLocationDescription(), lldb_private::SymbolContext::GetParentOfInlinedScope(), lldb_private::operator==(), lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint(), lldb_private::SymbolContextSpecifier::SymbolContextMatches(), and lldb::SBValue::Watch().
GetFile() [2/2]
const FileSpec & lldb_private::Declaration::GetFile () const inline
Get const accessor for file specification.
Returns
A const reference to the file specification object.
Definition at line 117 of file Declaration.h.
References m_file.
GetLine()
uint32_t lldb_private::Declaration::GetLine () const inline
Get accessor for the declaration line number.
Returns
Non-zero indicates a valid line number, zero indicates no line information is available.
Definition at line 124 of file Declaration.h.
References m_line.
Referenced by lldb_private::Block::AddRange(), lldb_private::VariableAnnotator::AnnotateStructured(), lldb_private::BreakpointResolverFileLine::FilterContexts(), lldb::SBBlock::GetInlinedCallSiteLine(), lldb_private::InstrumentationRuntimeTSan::GetLocationDescription(), lldb_private::SymbolContext::GetParentOfInlinedScope(), lldb_private::operator==(), lldb_private::CompileUnit::ResolveSymbolContext(), and lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint().
IsValid()
bool lldb_private::Declaration::IsValid () const inline
Definition at line 149 of file Declaration.h.
References LLDB_INVALID_LINE_NUMBER, m_file, and m_line.
Referenced by lldb_private::BreakpointResolverFileLine::FilterContexts(), operator bool(), and lldb_private::plugin::dwarf::UniqueDWARFASTType::UpdateToDefDIE().
MemorySize()
size_t Declaration::MemorySize () const
Get the memory cost of this object.
Returns
The number of bytes that this object occupies in memory. The returned value does not include the bytes for any shared string values.
Definition at line 56 of file Declaration.cpp.
References Declaration().
operator bool()
lldb_private::Declaration::operator bool () const inline explicit
Convert to boolean operator.
This allows code to check a Declaration object to see if it contains anything valid using code such as:
Declaration decl(...);
if (decl)
{ ...
Returns
A true if both the file_spec and the line are valid, false otherwise.
Definition at line 147 of file Declaration.h.
References IsValid().
SetColumn()
void lldb_private::Declaration::SetColumn (uint16_t column) inline
Set accessor for the declaration column number.
Parameters
[in] column Non-zero indicates a valid column number, zero indicates no column information is available.
Definition at line 179 of file Declaration.h.
References m_column.
Referenced by AddSourceInfoToDecl(), DWARFASTParserClang::ParseChildEnumerators(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE(), SymbolFilePDB::ParseVariableForPDBData(), and lldb::SBDeclaration::SetColumn().
SetFile()
void lldb_private::Declaration::SetFile (const FileSpec & file_spec) inline
Set accessor for the declaration file specification.
Parameters
[in] file_spec The new declaration file specification.
Definition at line 165 of file Declaration.h.
References m_file.
Referenced by AddSourceInfoToDecl(), DWARFASTParserClang::ParseChildEnumerators(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE(), SymbolFilePDB::ParseVariableForPDBData(), and lldb::SBDeclaration::SetFileSpec().
SetLine()
void lldb_private::Declaration::SetLine (uint32_t line) inline
Set accessor for the declaration line number.
Parameters
[in] line Non-zero indicates a valid line number, zero indicates no line information is available.
Definition at line 172 of file Declaration.h.
References m_line.
Referenced by AddSourceInfoToDecl(), DWARFASTParserClang::ParseChildEnumerators(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE(), SymbolFilePDB::ParseVariableForPDBData(), and lldb::SBDeclaration::SetLine().
Member Data Documentation
m_column
uint16_t lldb_private::Declaration::m_column = LLDB_INVALID_COLUMN_NUMBER protected
Non-zero values indicates a valid column number, zero indicates no column information is available.
Definition at line 190 of file Declaration.h.
Referenced by Clear(), Compare(), Declaration(), Declaration(), Dump(), DumpStopContext(), GetColumn(), and SetColumn().
m_file
FileSpec lldb_private::Declaration::m_file protected
The file specification that points to the source file where the declaration occurred.
Definition at line 184 of file Declaration.h.
Referenced by Clear(), Compare(), Declaration(), Dump(), DumpStopContext(), FileAndLineEqual(), GetFile(), GetFile(), IsValid(), and SetFile().
m_line
uint32_t lldb_private::Declaration::m_line = 0 protected
Non-zero values indicates a valid line number, zero indicates no line number information is available.
Definition at line 187 of file Declaration.h.
Referenced by Clear(), Compare(), Declaration(), Declaration(), Dump(), DumpStopContext(), FileAndLineEqual(), GetLine(), IsValid(), and SetLine().
The documentation for this class was generated from the following files:
Declaration.h
Declaration.cpp