LLDB: lldb_private::LogHandler Class Reference
lldb_private::LogHandler Class Reference abstract
#include <Log.h>
Public Member Functions
virtual ~LogHandler ()=default
virtual void Emit (llvm::StringRef message)=0
virtual bool isA (const void *ClassID) const
Static Public Member Functions
static bool classof (const LogHandler *obj)
Static Private Attributes
static char ID
Detailed Description
Definition at line 48 of file Log.h.
Constructor & Destructor Documentation
~LogHandler()
virtual lldb_private::LogHandler::~LogHandler () virtual default
Member Function Documentation
classof()
bool lldb_private::LogHandler::classof (const LogHandler * obj) inline static
Definition at line 54 of file Log.h.
References ID, and isA().
Emit()
virtual void lldb_private::LogHandler::Emit (llvm::StringRef message) pure virtual
Implemented in lldb_private::CallbackLogHandler, lldb_private::RotatingLogHandler, lldb_private::StreamLogHandler, lldb_private::SystemLogHandler, and lldb_private::TeeLogHandler.
isA()
virtual bool lldb_private::LogHandler::isA (const void * ClassID) const inline virtual
Reimplemented in lldb_private::CallbackLogHandler, lldb_private::RotatingLogHandler, lldb_private::StreamLogHandler, lldb_private::SystemLogHandler, and lldb_private::TeeLogHandler.
Definition at line 53 of file Log.h.
References ID.
Referenced by lldb_private::CallbackLogHandler::classof(), classof(), lldb_private::RotatingLogHandler::classof(), lldb_private::StreamLogHandler::classof(), lldb_private::SystemLogHandler::classof(), and lldb_private::TeeLogHandler::classof().
Member Data Documentation
ID
char LogHandler::ID static private
Definition at line 57 of file Log.h.
Referenced by classof(), and isA().
The documentation for this class was generated from the following files:
Log.h
Log.cpp