LLDB: lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions Class Reference
lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions Class Reference
#include <StringPrinter.h>
Public Member Functions
ReadStringAndDumpToStreamOptions ()=default
ReadStringAndDumpToStreamOptions (ValueObject &valobj)
void SetLocation (Address l)
const Address & GetLocation () const
void SetTargetSP (lldb::TargetSP t)
lldb::TargetSP GetTargetSP () const
void SetHasSourceSize (bool e)
bool HasSourceSize () const
Public Member Functions inherited from lldb_private::formatters::StringPrinter::DumpToStreamOptions
DumpToStreamOptions ()=default
void SetStream (Stream *s)
Stream * GetStream () const
void SetPrefixToken (const std::string &p)
void SetPrefixToken (std::nullptr_t)
const char * GetPrefixToken () const
void SetSuffixToken (const std::string &p)
void SetSuffixToken (std::nullptr_t)
const char * GetSuffixToken () const
void SetQuote (char q)
char GetQuote () const
void SetSourceSize (uint32_t s)
uint32_t GetSourceSize () const
void SetNeedsZeroTermination (bool z)
bool GetNeedsZeroTermination () const
void SetBinaryZeroIsTerminator (bool e)
bool GetBinaryZeroIsTerminator () const
void SetEscapeNonPrintables (bool e)
bool GetEscapeNonPrintables () const
void SetIgnoreMaxLength (bool e)
bool GetIgnoreMaxLength () const
void SetEscapeStyle (EscapeStyle style)
EscapeStyle GetEscapeStyle () const
Private Attributes
Address m_location
lldb::TargetSP m_target_sp
bool m_has_source_size = false
True iff we know the source size of the string.
Detailed Description
Definition at line 102 of file StringPrinter.h.
Constructor & Destructor Documentation
ReadStringAndDumpToStreamOptions() [1/2]
lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::ReadStringAndDumpToStreamOptions () default
Referenced by ReadStringAndDumpToStreamOptions().
ReadStringAndDumpToStreamOptions() [2/2]
lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::ReadStringAndDumpToStreamOptions (ValueObject & valobj)
Definition at line 364 of file StringPrinter.cpp.
References lldb_private::ValueObject::GetTargetSP(), ReadStringAndDumpToStreamOptions(), and lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetEscapeNonPrintables().
Member Function Documentation
GetLocation()
const Address & lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::GetLocation () const inline
Definition at line 110 of file StringPrinter.h.
References m_location.
Referenced by lldb_private::formatters::ReadEncodedBufferAndDumpToStream().
GetTargetSP()
lldb::TargetSP lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::GetTargetSP () const inline
Definition at line 114 of file StringPrinter.h.
References m_target_sp.
Referenced by lldb_private::formatters::ReadEncodedBufferAndDumpToStream().
HasSourceSize()
bool lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::HasSourceSize () const inline
Definition at line 118 of file StringPrinter.h.
References m_has_source_size.
Referenced by lldb_private::formatters::ReadEncodedBufferAndDumpToStream().
SetHasSourceSize()
void lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::SetHasSourceSize (bool e) inline
Definition at line 116 of file StringPrinter.h.
References m_has_source_size.
Referenced by lldb_private::formatters::NSStringSummaryProvider().
SetLocation()
void lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::SetLocation (Address l) inline
Definition at line 108 of file StringPrinter.h.
References l, and m_location.
Referenced by CharStringSummaryProvider(), lldb_private::formatters::NSStringSummaryProvider(), and lldb_private::formatters::WCharStringSummaryProvider().
SetTargetSP()
void lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::SetTargetSP (lldb::TargetSP t) inline
Definition at line 112 of file StringPrinter.h.
References m_target_sp.
Referenced by CharStringSummaryProvider(), lldb_private::formatters::NSStringSummaryProvider(), and lldb_private::formatters::WCharStringSummaryProvider().
Member Data Documentation
m_has_source_size
bool lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::m_has_source_size = false private
True iff we know the source size of the string.
Definition at line 124 of file StringPrinter.h.
Referenced by HasSourceSize(), and SetHasSourceSize().
m_location
Address lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::m_location private
Definition at line 121 of file StringPrinter.h.
Referenced by GetLocation(), and SetLocation().
m_target_sp
lldb::TargetSP lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::m_target_sp private
Definition at line 122 of file StringPrinter.h.
Referenced by GetTargetSP(), and SetTargetSP().
The documentation for this class was generated from the following files:
StringPrinter.h
StringPrinter.cpp