LLDB: lldb_private::NativeRegisterContextDBReg Class Reference
lldb_private::NativeRegisterContextDBReg Class Reference abstract
#include <NativeRegisterContextDBReg.h>
Classes
struct DREG
Debug register info for hardware breakpoints and watchpoints management.
struct WatchpointDetails
Public Types
enum DREGType { eDREGTypeWATCH = 0 , eDREGTypeBREAK }
Public Member Functions
NativeRegisterContextDBReg (uint32_t enable_bit)
uint32_t NumSupportedHardwareBreakpoints () override
uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size) override
bool ClearHardwareBreakpoint (uint32_t hw_idx) override
Status ClearAllHardwareBreakpoints () override
Status GetHardwareBreakHitIndex (uint32_t &bp_index, lldb::addr_t trap_addr) override
uint32_t NumSupportedHardwareWatchpoints () override
uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, uint32_t watch_flags) override
bool ClearHardwareWatchpoint (uint32_t hw_index) override
Status ClearAllHardwareWatchpoints () override
Status GetWatchpointHitIndex (uint32_t &wp_index, lldb::addr_t trap_addr) override
lldb::addr_t GetWatchpointHitAddress (uint32_t wp_index) override
lldb::addr_t GetWatchpointAddress (uint32_t wp_index) override
Public Member Functions inherited from lldb_private::NativeRegisterContextRegisterInfo
NativeRegisterContextRegisterInfo (NativeThreadProtocol &thread, RegisterInfoInterface *register_info_interface)
Construct a NativeRegisterContextRegisterInfo, taking ownership of the register_info_interface pointer.
uint32_t GetRegisterCount () const override
uint32_t GetUserRegisterCount () const override
const RegisterInfo * GetRegisterInfoAtIndex (uint32_t reg_index) const override
const RegisterInfoInterface & GetRegisterInfoInterface () const
Public Member Functions inherited from lldb_private::NativeRegisterContext
NativeRegisterContext (NativeThreadProtocol &thread)
virtual ~NativeRegisterContext ()
const char * GetRegisterSetNameForRegisterAtIndex (uint32_t reg_index) const
virtual uint32_t GetRegisterSetCount () const =0
virtual const RegisterSet * GetRegisterSet (uint32_t set_index) const =0
virtual Status ReadRegister (const RegisterInfo *reg_info, RegisterValue &reg_value)=0
virtual Status WriteRegister (const RegisterInfo *reg_info, const RegisterValue &reg_value)=0
virtual Status ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp)=0
virtual Status WriteAllRegisterValues (const lldb::DataBufferSP &data_sp)=0
uint32_t ConvertRegisterKindToRegisterNumber (uint32_t kind, uint32_t num) const
virtual Status ClearWatchpointHit (uint32_t hw_index)
virtual Status IsWatchpointHit (uint32_t wp_index, bool &is_hit)
virtual Status IsWatchpointVacant (uint32_t wp_index, bool &is_vacant)
virtual bool HardwareSingleStep (bool enable)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, size_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, size_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual NativeThreadProtocol & GetThread ()
virtual std::vector< uint32_t > GetExpeditedRegisters (ExpeditedRegs expType) const
virtual bool RegisterOffsetIsDynamic () const
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (uint32_t reg_kind, uint32_t reg_num)
lldb::addr_t GetPC (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
virtual lldb::addr_t GetPCfromBreakpointLocation (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
Status SetPC (lldb::addr_t pc)
lldb::addr_t GetSP (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
Status SetSP (lldb::addr_t sp)
lldb::addr_t GetFP (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
Status SetFP (lldb::addr_t fp)
const char * GetRegisterName (uint32_t reg)
lldb::addr_t GetReturnAddress (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
lldb::addr_t GetFlags (lldb::addr_t fail_value=0)
lldb::addr_t ReadRegisterAsUnsigned (uint32_t reg, lldb::addr_t fail_value)
lldb::addr_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, lldb::addr_t fail_value)
Status WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
Status WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
Protected Types
using BreakpointDetails = WatchpointDetails
Protected Member Functions
bool WatchpointIsEnabled (uint32_t wp_index)
bool BreakpointIsEnabled (uint32_t bp_index)
virtual bool ValidateBreakpoint (size_t size, lldb::addr_t addr)
virtual std::optional< WatchpointDetails > AdjustWatchpoint (const WatchpointDetails &details)=0
virtual BreakpointDetails AdjustBreakpoint (const BreakpointDetails &details)
virtual uint32_t MakeBreakControlValue (size_t size)=0
virtual uint32_t MakeWatchControlValue (size_t size, uint32_t watch_flags)=0
virtual uint32_t GetWatchpointSize (uint32_t wp_index)=0
virtual llvm::Error ReadHardwareDebugInfo ()=0
virtual llvm::Error WriteHardwareDebugRegs (DREGType hwbType)=0
virtual lldb::addr_t FixWatchpointHitAddress (lldb::addr_t hit_addr)
Protected Attributes
std::array< struct DREG, 16 > m_hbp_regs
std::array< struct DREG, 16 > m_hwp_regs
uint32_t m_max_hbp_supported
uint32_t m_max_hwp_supported
const uint32_t m_hw_dbg_enable_bit
Protected Attributes inherited from lldb_private::NativeRegisterContextRegisterInfo
std::unique_ptr< RegisterInfoInterface > m_register_info_interface_up
Protected Attributes inherited from lldb_private::NativeRegisterContext
NativeThreadProtocol & m_thread
Detailed Description
Definition at line 22 of file NativeRegisterContextDBReg.h.
Member Typedef Documentation
BreakpointDetails
using lldb_private::NativeRegisterContextDBReg::BreakpointDetails = WatchpointDetails protected
Definition at line 91 of file NativeRegisterContextDBReg.h.
Member Enumeration Documentation
DREGType
enum lldb_private::NativeRegisterContextDBReg::DREGType
Enumerator
eDREGTypeWATCH
eDREGTypeBREAK
Definition at line 56 of file NativeRegisterContextDBReg.h.
Constructor & Destructor Documentation
NativeRegisterContextDBReg()
lldb_private::NativeRegisterContextDBReg::NativeRegisterContextDBReg (uint32_t enable_bit) inline explicit
Definition at line 25 of file NativeRegisterContextDBReg.h.
References m_hw_dbg_enable_bit.
Referenced by lldb_private::NativeRegisterContextDBReg_arm::NativeRegisterContextDBReg_arm(), lldb_private::NativeRegisterContextDBReg_arm64::NativeRegisterContextDBReg_arm64(), and lldb_private::NativeRegisterContextDBReg_loongarch::NativeRegisterContextDBReg_loongarch().
Member Function Documentation
AdjustBreakpoint()
virtual BreakpointDetails lldb_private::NativeRegisterContextDBReg::AdjustBreakpoint (const BreakpointDetails & details) inline protected virtual
Reimplemented in lldb_private::NativeRegisterContextDBReg_arm.
Definition at line 92 of file NativeRegisterContextDBReg.h.
Referenced by SetHardwareBreakpoint().
AdjustWatchpoint()
virtual std::optional< WatchpointDetails > lldb_private::NativeRegisterContextDBReg::AdjustWatchpoint (const WatchpointDetails & details) protected pure virtual
Implemented in lldb_private::NativeRegisterContextDBReg_arm64, lldb_private::NativeRegisterContextDBReg_arm, and lldb_private::NativeRegisterContextDBReg_loongarch.
Referenced by SetHardwareWatchpoint().
BreakpointIsEnabled()
bool NativeRegisterContextDBReg::BreakpointIsEnabled (uint32_t bp_index) protected
Definition at line 184 of file NativeRegisterContextDBReg.cpp.
References m_hbp_regs, and m_hw_dbg_enable_bit.
Referenced by ClearAllHardwareBreakpoints(), GetHardwareBreakHitIndex(), and SetHardwareBreakpoint().
ClearAllHardwareBreakpoints()
Status NativeRegisterContextDBReg::ClearAllHardwareBreakpoints () override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 149 of file NativeRegisterContextDBReg.cpp.
References BreakpointIsEnabled(), lldb_private::Breakpoints, eDREGTypeBREAK, error(), lldb_private::Status::FromError(), lldb_private::GetLog(), LLDB_LOGF, m_hbp_regs, m_hw_dbg_enable_bit, m_max_hbp_supported, ReadHardwareDebugInfo(), lldb_private::Status, and WriteHardwareDebugRegs().
ClearAllHardwareWatchpoints()
Status NativeRegisterContextDBReg::ClearAllHardwareWatchpoints () override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 317 of file NativeRegisterContextDBReg.cpp.
References eDREGTypeWATCH, error(), lldb_private::Status::FromError(), m_hwp_regs, m_max_hwp_supported, ReadHardwareDebugInfo(), lldb_private::Status, WatchpointIsEnabled(), and WriteHardwareDebugRegs().
ClearHardwareBreakpoint()
bool NativeRegisterContextDBReg::ClearHardwareBreakpoint (uint32_t hw_idx) override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 88 of file NativeRegisterContextDBReg.cpp.
References lldb_private::Breakpoints, eDREGTypeBREAK, error(), lldb_private::GetLog(), LLDB_LOG, LLDB_LOG_ERROR, m_hbp_regs, m_hw_dbg_enable_bit, m_max_hbp_supported, ReadHardwareDebugInfo(), and WriteHardwareDebugRegs().
ClearHardwareWatchpoint()
bool NativeRegisterContextDBReg::ClearHardwareWatchpoint (uint32_t hw_index) override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 277 of file NativeRegisterContextDBReg.cpp.
References eDREGTypeWATCH, error(), lldb_private::GetLog(), LLDB_LOG, LLDB_LOG_ERROR, m_hw_dbg_enable_bit, m_hwp_regs, m_max_hwp_supported, ReadHardwareDebugInfo(), lldb_private::Watchpoints, and WriteHardwareDebugRegs().
FixWatchpointHitAddress()
virtual lldb::addr_t lldb_private::NativeRegisterContextDBReg::FixWatchpointHitAddress (lldb::addr_t hit_addr) inline protected virtual
Definition at line 101 of file NativeRegisterContextDBReg.h.
Referenced by GetWatchpointHitIndex().
GetHardwareBreakHitIndex()
Status NativeRegisterContextDBReg::GetHardwareBreakHitIndex (uint32_t & bp_index, lldb::addr_t trap_addr) override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 128 of file NativeRegisterContextDBReg.cpp.
References BreakpointIsEnabled(), lldb_private::Breakpoints, lldb_private::GetLog(), LLDB_INVALID_INDEX32, LLDB_LOGF, m_hbp_regs, m_max_hbp_supported, and lldb_private::Status.
GetWatchpointAddress()
lldb::addr_t NativeRegisterContextDBReg::GetWatchpointAddress (uint32_t wp_index) override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 387 of file NativeRegisterContextDBReg.cpp.
References lldb_private::GetLog(), LLDB_INVALID_ADDRESS, LLDB_LOG, m_hwp_regs, m_max_hwp_supported, WatchpointIsEnabled(), and lldb_private::Watchpoints.
GetWatchpointHitAddress()
lldb::addr_t NativeRegisterContextDBReg::GetWatchpointHitAddress (uint32_t wp_index) override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 400 of file NativeRegisterContextDBReg.cpp.
References lldb_private::GetLog(), LLDB_INVALID_ADDRESS, LLDB_LOG, m_hwp_regs, m_max_hwp_supported, WatchpointIsEnabled(), and lldb_private::Watchpoints.
GetWatchpointHitIndex()
Status NativeRegisterContextDBReg::GetWatchpointHitIndex (uint32_t & wp_index, lldb::addr_t trap_addr) override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 349 of file NativeRegisterContextDBReg.cpp.
References error(), FixWatchpointHitAddress(), lldb_private::Status::FromError(), lldb_private::GetLog(), GetWatchpointSize(), LLDB_INVALID_INDEX32, LLDB_LOG, m_hwp_regs, m_max_hwp_supported, ReadHardwareDebugInfo(), lldb_private::Status, WatchpointIsEnabled(), and lldb_private::Watchpoints.
GetWatchpointSize()
virtual uint32_t lldb_private::NativeRegisterContextDBReg::GetWatchpointSize (uint32_t wp_index) protected pure virtual
Implemented in lldb_private::NativeRegisterContextDBReg_arm64, lldb_private::NativeRegisterContextDBReg_arm, and lldb_private::NativeRegisterContextDBReg_loongarch.
Referenced by GetWatchpointHitIndex().
MakeBreakControlValue()
virtual uint32_t lldb_private::NativeRegisterContextDBReg::MakeBreakControlValue (size_t size) protected pure virtual
Implemented in lldb_private::NativeRegisterContextDBReg_arm64, lldb_private::NativeRegisterContextDBReg_arm, and lldb_private::NativeRegisterContextDBReg_loongarch.
Referenced by SetHardwareBreakpoint().
MakeWatchControlValue()
virtual uint32_t lldb_private::NativeRegisterContextDBReg::MakeWatchControlValue (size_t size, uint32_t watch_flags) protected pure virtual
Implemented in lldb_private::NativeRegisterContextDBReg_arm64, lldb_private::NativeRegisterContextDBReg_arm, and lldb_private::NativeRegisterContextDBReg_loongarch.
Referenced by SetHardwareWatchpoint().
NumSupportedHardwareBreakpoints()
uint32_t NativeRegisterContextDBReg::NumSupportedHardwareBreakpoints () override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 17 of file NativeRegisterContextDBReg.cpp.
References lldb_private::Breakpoints, error(), lldb_private::GetLog(), LLDB_LOG, LLDB_LOG_ERROR, m_max_hbp_supported, and ReadHardwareDebugInfo().
NumSupportedHardwareWatchpoints()
uint32_t NativeRegisterContextDBReg::NumSupportedHardwareWatchpoints () override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 188 of file NativeRegisterContextDBReg.cpp.
References error(), lldb_private::GetLog(), LLDB_LOG_ERROR, m_max_hwp_supported, ReadHardwareDebugInfo(), and lldb_private::Watchpoints.
ReadHardwareDebugInfo()
virtual llvm::Error lldb_private::NativeRegisterContextDBReg::ReadHardwareDebugInfo () protected pure virtual
Referenced by ClearAllHardwareBreakpoints(), ClearAllHardwareWatchpoints(), ClearHardwareBreakpoint(), ClearHardwareWatchpoint(), GetWatchpointHitIndex(), NumSupportedHardwareBreakpoints(), NumSupportedHardwareWatchpoints(), SetHardwareBreakpoint(), and SetHardwareWatchpoint().
SetHardwareBreakpoint()
uint32_t NativeRegisterContextDBReg::SetHardwareBreakpoint (lldb::addr_t addr, size_t size) override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 33 of file NativeRegisterContextDBReg.cpp.
References AdjustBreakpoint(), BreakpointIsEnabled(), lldb_private::Breakpoints, eDREGTypeBREAK, error(), lldb_private::GetLog(), LLDB_INVALID_INDEX32, LLDB_LOG, LLDB_LOG_ERROR, m_hbp_regs, m_hw_dbg_enable_bit, m_max_hbp_supported, MakeBreakControlValue(), ReadHardwareDebugInfo(), ValidateBreakpoint(), and WriteHardwareDebugRegs().
SetHardwareWatchpoint()
uint32_t NativeRegisterContextDBReg::SetHardwareWatchpoint (lldb::addr_t addr, size_t size, uint32_t watch_flags) override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 200 of file NativeRegisterContextDBReg.cpp.
References AdjustWatchpoint(), eDREGTypeWATCH, error(), lldb_private::GetLog(), LLDB_INVALID_INDEX32, LLDB_LOG, LLDB_LOG_ERROR, m_hw_dbg_enable_bit, m_hwp_regs, m_max_hwp_supported, MakeWatchControlValue(), ReadHardwareDebugInfo(), WatchpointIsEnabled(), lldb_private::Watchpoints, and WriteHardwareDebugRegs().
ValidateBreakpoint()
virtual bool lldb_private::NativeRegisterContextDBReg::ValidateBreakpoint (size_t size, lldb::addr_t addr) inline protected virtual
Reimplemented in lldb_private::NativeRegisterContextDBReg_arm.
Definition at line 80 of file NativeRegisterContextDBReg.h.
Referenced by SetHardwareBreakpoint().
WatchpointIsEnabled()
bool NativeRegisterContextDBReg::WatchpointIsEnabled (uint32_t wp_index) protected
Definition at line 380 of file NativeRegisterContextDBReg.cpp.
References lldb_private::GetLog(), LLDB_LOG, m_hw_dbg_enable_bit, m_hwp_regs, and lldb_private::Watchpoints.
Referenced by ClearAllHardwareWatchpoints(), GetWatchpointAddress(), GetWatchpointHitAddress(), GetWatchpointHitIndex(), and SetHardwareWatchpoint().
WriteHardwareDebugRegs()
virtual llvm::Error lldb_private::NativeRegisterContextDBReg::WriteHardwareDebugRegs (DREGType hwbType) protected pure virtual
Referenced by ClearAllHardwareBreakpoints(), ClearAllHardwareWatchpoints(), ClearHardwareBreakpoint(), ClearHardwareWatchpoint(), SetHardwareBreakpoint(), and SetHardwareWatchpoint().
Member Data Documentation
m_hbp_regs
std::array<struct DREG, 16> lldb_private::NativeRegisterContextDBReg::m_hbp_regs protected
Definition at line 68 of file NativeRegisterContextDBReg.h.
Referenced by BreakpointIsEnabled(), ClearAllHardwareBreakpoints(), ClearHardwareBreakpoint(), GetHardwareBreakHitIndex(), and SetHardwareBreakpoint().
m_hw_dbg_enable_bit
const uint32_t lldb_private::NativeRegisterContextDBReg::m_hw_dbg_enable_bit protected
Definition at line 73 of file NativeRegisterContextDBReg.h.
Referenced by BreakpointIsEnabled(), ClearAllHardwareBreakpoints(), ClearHardwareBreakpoint(), ClearHardwareWatchpoint(), lldb_private::NativeRegisterContextDBReg_arm64::MakeBreakControlValue(), lldb_private::NativeRegisterContextDBReg_loongarch::MakeBreakControlValue(), lldb_private::NativeRegisterContextDBReg_arm64::MakeWatchControlValue(), lldb_private::NativeRegisterContextDBReg_loongarch::MakeWatchControlValue(), NativeRegisterContextDBReg(), SetHardwareBreakpoint(), SetHardwareWatchpoint(), and WatchpointIsEnabled().
m_hwp_regs
std::array<struct DREG, 16> lldb_private::NativeRegisterContextDBReg::m_hwp_regs protected
Definition at line 69 of file NativeRegisterContextDBReg.h.
Referenced by ClearAllHardwareWatchpoints(), ClearHardwareWatchpoint(), GetWatchpointAddress(), GetWatchpointHitAddress(), GetWatchpointHitIndex(), lldb_private::NativeRegisterContextDBReg_arm64::GetWatchpointSize(), lldb_private::NativeRegisterContextDBReg_arm::GetWatchpointSize(), lldb_private::NativeRegisterContextDBReg_loongarch::GetWatchpointSize(), SetHardwareWatchpoint(), and WatchpointIsEnabled().
m_max_hbp_supported
uint32_t lldb_private::NativeRegisterContextDBReg::m_max_hbp_supported protected
Definition at line 71 of file NativeRegisterContextDBReg.h.
Referenced by ClearAllHardwareBreakpoints(), ClearHardwareBreakpoint(), GetHardwareBreakHitIndex(), NumSupportedHardwareBreakpoints(), and SetHardwareBreakpoint().
m_max_hwp_supported
uint32_t lldb_private::NativeRegisterContextDBReg::m_max_hwp_supported protected
Definition at line 72 of file NativeRegisterContextDBReg.h.
Referenced by ClearAllHardwareWatchpoints(), ClearHardwareWatchpoint(), GetWatchpointAddress(), GetWatchpointHitAddress(), GetWatchpointHitIndex(), NumSupportedHardwareWatchpoints(), and SetHardwareWatchpoint().
The documentation for this class was generated from the following files:
NativeRegisterContextDBReg.h
NativeRegisterContextDBReg.cpp