LLDB: lldb_private::LineTable Class Reference
lldb_private::LineTable Class Reference
A line table class.
#include "lldb/Symbol/LineTable.h"
Classes
struct Entry
struct EntrySearchInfo
class LessThanBinaryPredicate
class Sequence
Public Types
typedef lldb_private::RangeVector< lldb::addr_t, lldb::addr_t, 32 > FileAddressRanges
typedef RangeDataVector< lldb::addr_t, lldb::addr_t, lldb::addr_t > FileRangeMap
Public Member Functions
LineTable (CompileUnit *comp_unit)
Construct with compile unit.
LineTable (CompileUnit *comp_unit, std::vector< Sequence > &&sequences)
Construct with entries found in sequences.
~LineTable ()
Destructor.
void InsertLineEntry (lldb::addr_t file_addr, uint32_t line, uint16_t column, uint16_t file_idx, bool is_start_of_statement, bool is_start_of_basic_block, bool is_prologue_end, bool is_epilogue_begin, bool is_terminal_entry)
Adds a new line entry to this line table.
void InsertSequence (Sequence sequence)
void Dump (Stream *s, Target *target, Address::DumpStyle style, Address::DumpStyle fallback_style, bool show_line_ranges)
Dump all line entries in this line table to the stream s.
void GetDescription (Stream *s, Target *target, lldb::DescriptionLevel level)
uint32_t lower_bound (const Address &so_addr) const
Returns the index of the first line entry which ends after the given address (i.e., the first entry which contains the given address or it comes after it).
std::pair< uint32_t, uint32_t > GetLineEntryIndexRange (const AddressRange &range) const
Returns the (half-open) range of line entry indexes which overlap the given address range.
bool FindLineEntryByAddress (const Address &so_addr, LineEntry &line_entry, uint32_t *index_ptr=nullptr)
Find a line entry that contains the section offset address so_addr.
uint32_t FindLineEntryIndexByFileIndex (uint32_t start_idx, uint32_t file_idx, const SourceLocationSpec &src_location_spec, LineEntry *line_entry_ptr)
Find a line entry index that has a matching file index and source line number.
uint32_t FindLineEntryIndexByFileIndex (uint32_t start_idx, const std::vector< uint32_t > &file_idx, const SourceLocationSpec &src_location_spec, LineEntry *line_entry_ptr)
size_t FindLineEntriesForFileIndex (uint32_t file_idx, bool append, SymbolContextList &sc_list)
bool GetLineEntryAtIndex (uint32_t idx, LineEntry &line_entry)
Get the line entry from the line table at index idx.
uint32_t GetSize () const
Gets the size of the line table in number of line table entries.
size_t GetContiguousFileAddressRanges (FileAddressRanges &file_ranges, bool append)
Gets all contiguous file address ranges for the entire line table.
LineTable * LinkLineTable (const FileRangeMap &file_range_map)
Static Public Member Functions
static void AppendLineEntryToSequence (Sequence &sequence, lldb::addr_t file_addr, uint32_t line, uint16_t column, uint16_t file_idx, bool is_start_of_statement, bool is_start_of_basic_block, bool is_prologue_end, bool is_epilogue_begin, bool is_terminal_entry)
Protected Types
typedef std::vector< lldb_private::Section * > section_collection
The collection type for the sections.
typedef std::vector< Entry > entry_collection
The collection type for the line entries.
Protected Member Functions
bool ConvertEntryAtIndexToLineEntry (uint32_t idx, LineEntry &line_entry)
Protected Attributes
CompileUnit * m_comp_unit
The compile unit that this line table belongs to.
entry_collection m_entries
The collection of line entries in this line table.
Private Member Functions
LineTable (const LineTable &)=delete
const LineTable & operator= (const LineTable &)=delete
template<typename T>
uint32_t FindLineEntryIndexByFileIndexImpl (uint32_t start_idx, T file_idx, const SourceLocationSpec &src_location_spec, LineEntry *line_entry_ptr, std::function< bool(T, uint16_t)> file_idx_matcher)
Detailed Description
A line table class.
Definition at line 25 of file LineTable.h.
Member Typedef Documentation
entry_collection
typedef std::vector<Entry> lldb_private::LineTable::entry_collection protected
The collection type for the line entries.
Definition at line 330 of file LineTable.h.
FileAddressRanges
typedef lldb_private::RangeVector<lldb::addr_t, lldb::addr_t, 32> lldb_private::LineTable::FileAddressRanges
Definition at line 183 of file LineTable.h.
FileRangeMap
typedef RangeDataVector<lldb::addr_t, lldb::addr_t, lldb::addr_t> lldb_private::LineTable::FileRangeMap
Definition at line 201 of file LineTable.h.
section_collection
typedef std::vector<lldb_private::Section *> lldb_private::LineTable::section_collection protected
The collection type for the sections.
Definition at line 328 of file LineTable.h.
Constructor & Destructor Documentation
LineTable() [1/3]
LineTable::LineTable (CompileUnit * comp_unit)
Construct with compile unit.
Parameters
[in] comp_unit The compile unit to which this line table belongs.
Definition at line 21 of file LineTable.cpp.
References m_comp_unit, and m_entries.
Referenced by lldb_private::LineTable::LessThanBinaryPredicate::LessThanBinaryPredicate(), LineTable(), LinkLineTable(), and operator=().
LineTable() [2/3]
LineTable::LineTable (CompileUnit * comp_unit, std::vector< Sequence > && sequences)
Construct with entries found in sequences.
Parameters
[in] sequences Unsorted list of line sequences.
Definition at line 24 of file LineTable.cpp.
References m_comp_unit, and m_entries.
~LineTable()
LineTable::~LineTable () default
Destructor.
LineTable() [3/3]
lldb_private::LineTable::LineTable (const LineTable &) private delete
References LineTable().
Member Function Documentation
AppendLineEntryToSequence()
void LineTable::AppendLineEntryToSequence (Sequence & sequence, lldb::addr_t file_addr, uint32_t line, uint16_t column, uint16_t file_idx, bool is_start_of_statement, bool is_start_of_basic_block, bool is_prologue_end, bool is_epilogue_begin, bool is_terminal_entry) static
Definition at line 59 of file LineTable.cpp.
References lldb_private::LineTable::Entry::file_idx, lldb_private::LineTable::Entry::is_prologue_end, and lldb_private::LineTable::Sequence::m_entries.
Referenced by lldb_private::npdb::SymbolFileNativePDB::ParseLineTable(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseLineTable(), and lldb_private::breakpad::SymbolFileBreakpad::ParseLineTableAndSupportFiles().
ConvertEntryAtIndexToLineEntry()
bool LineTable::ConvertEntryAtIndexToLineEntry (uint32_t idx, LineEntry & line_entry) protected
Definition at line 230 of file LineTable.cpp.
References lldb_private::LineEntry::column, lldb_private::LineTable::Entry::column, lldb_private::LineTable::Entry::file_addr, lldb_private::LineTable::Entry::file_idx, lldb_private::LineEntry::file_sp, lldb_private::AddressRange::GetBaseAddress(), lldb_private::LineEntry::is_epilogue_begin, lldb_private::LineTable::Entry::is_epilogue_begin, lldb_private::LineEntry::is_prologue_end, lldb_private::LineTable::Entry::is_prologue_end, lldb_private::LineEntry::is_start_of_basic_block, lldb_private::LineTable::Entry::is_start_of_basic_block, lldb_private::LineEntry::is_start_of_statement, lldb_private::LineTable::Entry::is_start_of_statement, lldb_private::LineEntry::is_terminal_entry, lldb_private::LineTable::Entry::is_terminal_entry, lldb_private::LineEntry::line, lldb_private::LineTable::Entry::line, m_comp_unit, m_entries, lldb_private::LineEntry::original_file_sp, lldb_private::LineEntry::range, lldb_private::AddressRange::SetByteSize(), and lldb_private::Address::Slide().
Referenced by Dump(), FindLineEntriesForFileIndex(), FindLineEntryByAddress(), FindLineEntryIndexByFileIndexImpl(), GetDescription(), and GetLineEntryAtIndex().
Dump()
void LineTable::Dump (Stream * s, Target * target, Address::DumpStyle style, Address::DumpStyle fallback_style, bool show_line_ranges)
Dump all line entries in this line table to the stream s.
Parameters
[in] s The stream to which to dump the object description.
[in] style The display style for the address.
See also
Address::DumpStyle
Definition at line 326 of file LineTable.cpp.
References ConvertEntryAtIndexToLineEntry(), lldb_private::LineEntry::Dump(), lldb_private::Stream::EOL(), m_entries, and lldb_private::LineEntry::original_file_sp.
FindLineEntriesForFileIndex()
size_t LineTable::FindLineEntriesForFileIndex (uint32_t file_idx, bool append, SymbolContextList & sc_list)
Definition at line 298 of file LineTable.cpp.
References lldb_private::SymbolContextList::Append(), lldb_private::SymbolContextList::Clear(), ConvertEntryAtIndexToLineEntry(), lldb_private::SymbolContext::line_entry, m_comp_unit, and m_entries.
Referenced by lldb_private::FileLineResolver::SearchCallback().
FindLineEntryByAddress()
bool LineTable::FindLineEntryByAddress (const Address & so_addr, LineEntry & line_entry, uint32_t * index_ptr = nullptr)
Find a line entry that contains the section offset address so_addr.
Parameters
[in] so_addr A section offset address object containing the address we are searching for.
[out] line_entry A copy of the line entry that was found if true is returned, otherwise entry is left unmodified.
[out] index_ptr A pointer to a 32 bit integer that will get the actual line entry index if it is not nullptr.
Returns
Returns true if so_addr is contained in a line entry in this line table, false otherwise.
Definition at line 210 of file LineTable.cpp.
References ConvertEntryAtIndexToLineEntry(), lldb_private::Address::GetFileAddress(), GetSize(), lower_bound(), m_entries, and UINT32_MAX.
Referenced by lldb_private::Function::GetPrologueByteSize(), lldb_private::Function::GetStartLineSourceInfo(), and lldb_private::ThreadPlanStepOverRange::ShouldStop().
FindLineEntryIndexByFileIndex() [1/2]
uint32_t LineTable::FindLineEntryIndexByFileIndex (uint32_t start_idx, const std::vector< uint32_t > & file_idx, const SourceLocationSpec & src_location_spec, LineEntry * line_entry_ptr)
Definition at line 286 of file LineTable.cpp.
References FindLineEntryIndexByFileIndexImpl().
FindLineEntryIndexByFileIndex() [2/2]
uint32_t LineTable::FindLineEntryIndexByFileIndex (uint32_t start_idx, uint32_t file_idx, const SourceLocationSpec & src_location_spec, LineEntry * line_entry_ptr)
Find a line entry index that has a matching file index and source line number.
Finds the next line entry that has a matching file_idx and source line number line starting at the start_idx entries into the line entry collection.
Parameters
[in] start_idx The number of entries to skip when starting the search.
[out] file_idx The file index to search for that should be found prior to calling this function using the following functions: CompileUnit::GetSupportFiles() FileSpecList::FindFileIndex (uint32_t, const FileSpec &) const
[in] src_location_spec The source location specifier to match.
[out] line_entry_ptr A pointer to a line entry object that will get a copy of the line entry if true is returned, otherwise line_entry is left untouched.
Returns
Returns true if a matching line entry is found in this line table, false otherwise.
See also
CompileUnit::GetSupportFiles()
FileSpecList::FindFileIndex (uint32_t, const FileSpec &) const
Definition at line 275 of file LineTable.cpp.
References FindLineEntryIndexByFileIndexImpl().
Referenced by lldb_private::CompileUnit::FindLineEntry(), and lldb_private::CompileUnit::ResolveSymbolContext().
FindLineEntryIndexByFileIndexImpl()
template<typename T> uint32_t lldb_private::LineTable::FindLineEntryIndexByFileIndexImpl (uint32_t start_idx, T file_idx, const SourceLocationSpec & src_location_spec, LineEntry * line_entry_ptr, std::function< bool(T, uint16_t)> file_idx_matcher) inline private
Definition at line 344 of file LineTable.h.
References ConvertEntryAtIndexToLineEntry(), lldb_private::SourceLocationSpec::GetColumn(), lldb_private::SourceLocationSpec::GetExactMatch(), lldb_private::SourceLocationSpec::GetLine(), LLDB_INVALID_COLUMN_NUMBER, m_entries, and UINT32_MAX.
Referenced by FindLineEntryIndexByFileIndex(), and FindLineEntryIndexByFileIndex().
GetContiguousFileAddressRanges()
size_t LineTable::GetContiguousFileAddressRanges (FileAddressRanges & file_ranges, bool append)
Gets all contiguous file address ranges for the entire line table.
Parameters
[out] file_ranges A collection of file address ranges that will be filled in by this function.
[out] append If true, then append to file_ranges, otherwise clear file_ranges prior to adding any ranges.
Returns
The number of address ranges added to file_ranges
Definition at line 351 of file LineTable.cpp.
References lldb_private::RangeVector< B, S, N >::Append(), lldb_private::Range< B, S >::Clear(), lldb_private::RangeVector< B, S, N >::Clear(), lldb_private::LineTable::Entry::file_addr, lldb_private::Range< B, S >::GetRangeBase(), lldb_private::RangeVector< B, S, N >::GetSize(), lldb_private::LineTable::Entry::is_terminal_entry, LLDB_INVALID_ADDRESS, m_entries, lldb_private::Range< B, S >::SetRangeBase(), and lldb_private::Range< B, S >::SetRangeEnd().
GetDescription()
void LineTable::GetDescription (Stream * s, Target * target, lldb::DescriptionLevel level)
Definition at line 340 of file LineTable.cpp.
References ConvertEntryAtIndexToLineEntry(), lldb_private::Stream::EOL(), lldb_private::LineEntry::GetDescription(), m_comp_unit, and m_entries.
Referenced by DumpCompileUnitLineTable().
GetLineEntryAtIndex()
bool LineTable::GetLineEntryAtIndex (uint32_t idx, LineEntry & line_entry)
Get the line entry from the line table at index idx.
Parameters
[in] idx An index into the line table entry collection.
Returns
A valid line entry if idx is a valid index, or an invalid line entry if idx is not valid.
See also
LineTable::GetSize()
LineEntry::IsValid() const
Definition at line 157 of file LineTable.cpp.
References lldb_private::LineEntry::Clear(), ConvertEntryAtIndexToLineEntry(), and m_entries.
Referenced by lldb::SBCompileUnit::GetLineEntryAtIndex(), lldb_private::Function::GetPrologueByteSize(), lldb_private::Function::GetSourceInfo(), and lldb_private::ThreadPlanStepOverRange::ShouldStop().
GetLineEntryIndexRange()
std::pair< uint32_t, uint32_t > LineTable::GetLineEntryIndexRange (const AddressRange & range) const
Returns the (half-open) range of line entry indexes which overlap the given address range.
Line entries partially overlapping the range (on either side) are included as well. Returns an empty range (first==second) pointing to the "right" place in the list if there are no such line entries. Empty input ranges always result in an empty output range.
Definition at line 188 of file LineTable.cpp.
References lldb_private::LineTable::Entry::file_addr, lldb_private::AddressRange::GetBaseAddress(), lldb_private::AddressRange::GetByteSize(), lldb_private::Address::GetFileAddress(), GetSize(), lower_bound(), and m_entries.
Referenced by CommandObjectThreadUntil::DoExecute(), and lldb_private::Function::GetSourceInfo().
GetSize()
uint32_t LineTable::GetSize () const
Gets the size of the line table in number of line table entries.
Returns
The number of line table entries in this line table.
Definition at line 155 of file LineTable.cpp.
References m_entries.
Referenced by FindLineEntryByAddress(), GetLineEntryIndexRange(), lldb::SBCompileUnit::GetNumLineEntries(), and lower_bound().
InsertLineEntry()
void LineTable::InsertLineEntry (lldb::addr_t file_addr, uint32_t line, uint16_t column, uint16_t file_idx, bool is_start_of_statement, bool is_start_of_basic_block, bool is_prologue_end, bool is_epilogue_begin, bool is_terminal_entry)
Adds a new line entry to this line table.
All line entries are maintained in file address order.
Parameters
[in] line_entry A const reference to a new line_entry to add to this line table.
See also
Address::DumpStyle
Definition at line 37 of file LineTable.cpp.
References m_entries.
InsertSequence()
void LineTable::InsertSequence (Sequence sequence)
Definition at line 92 of file LineTable.cpp.
References m_entries, and lldb_private::LineTable::Sequence::m_entries.
LinkLineTable()
LineTable * LineTable::LinkLineTable (const FileRangeMap & file_range_map)
Definition at line 376 of file LineTable.cpp.
References lldb_private::Range< B, S >::Contains(), lldb_private::RangeData< B, S, T >::data, lldb_private::LineTable::Entry::file_addr, lldb_private::RangeDataVector< B, S, T, N, Compare >::FindEntryThatContains(), lldb_private::Range< B, S >::GetRangeBase(), lldb_private::Range< B, S >::GetRangeEnd(), lldb_private::LineTable::Entry::is_terminal_entry, LineTable(), LLDB_INVALID_ADDRESS, m_comp_unit, m_entries, lldb_private::LineTable::Sequence::m_entries, and UNUSED_IF_ASSERT_DISABLED.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::LinkOSOLineTable().
lower_bound()
uint32_t LineTable::lower_bound (const Address & so_addr) const
Returns the index of the first line entry which ends after the given address (i.e., the first entry which contains the given address or it comes after it).
Returns GetSize() if there is no such entry.
Definition at line 166 of file LineTable.cpp.
References lldb_private::LineTable::Entry::file_addr, lldb_private::Address::GetFileAddress(), lldb_private::Address::GetModule(), GetSize(), LLDB_INVALID_ADDRESS, m_comp_unit, and m_entries.
Referenced by FindLineEntryByAddress(), and GetLineEntryIndexRange().
operator=()
const LineTable & lldb_private::LineTable::operator= (const LineTable &) private delete
References LineTable().
Member Data Documentation
m_comp_unit
CompileUnit* lldb_private::LineTable::m_comp_unit protected
The compile unit that this line table belongs to.
Definition at line 333 of file LineTable.h.
Referenced by ConvertEntryAtIndexToLineEntry(), FindLineEntriesForFileIndex(), GetDescription(), LineTable(), LineTable(), LinkLineTable(), and lower_bound().
m_entries
entry_collection lldb_private::LineTable::m_entries protected
The collection of line entries in this line table.
Definition at line 335 of file LineTable.h.
Referenced by ConvertEntryAtIndexToLineEntry(), Dump(), FindLineEntriesForFileIndex(), FindLineEntryByAddress(), FindLineEntryIndexByFileIndexImpl(), GetContiguousFileAddressRanges(), GetDescription(), GetLineEntryAtIndex(), GetLineEntryIndexRange(), GetSize(), InsertLineEntry(), InsertSequence(), LineTable(), LineTable(), LinkLineTable(), and lower_bound().
The documentation for this class was generated from the following files:
LineTable.h
LineTable.cpp