LLDB: CFCMutableArray Class Reference
CFCMutableArray Class Reference
#include <CFCMutableArray.h>
Public Member Functions
CFCMutableArray (CFMutableArrayRef array=NULL)
CFCMutableArray (const CFCMutableArray &rhs)
CFCMutableArray & operator= (const CFCMutableArray &rhs)
~CFCMutableArray () override
CFIndex GetCount () const
CFIndex GetCountOfValue (const void *value) const
CFIndex GetCountOfValue (CFRange range, const void *value) const
const void * GetValueAtIndex (CFIndex idx) const
bool SetValueAtIndex (CFIndex idx, const void *value)
bool AppendValue (const void *value, bool can_create=true)
bool AppendCStringAsCFString (const char *cstr, CFStringEncoding encoding=kCFStringEncodingUTF8, bool can_create=true)
bool AppendFileSystemRepresentationAsCFString (const char *s, bool can_create=true)
Public Member Functions inherited from CFCReleaser< CFMutableArrayRef >
CFCReleaser (CFMutableArrayRef ptr=NULL)
virtual ~CFCReleaser ()
CFCReleaser & operator= (const CFCReleaser< CFMutableArrayRef > &rhs)
CFMutableArrayRef * ptr_address (bool enforce_null=true)
CFMutableArrayRef get ()
void reset (CFMutableArrayRef ptr=NULL)
CFMutableArrayRef release ()
Detailed Description
Definition at line 14 of file CFCMutableArray.h.
Constructor & Destructor Documentation
CFCMutableArray() [1/2]
CFCMutableArray::CFCMutableArray (CFMutableArrayRef array = NULL)
Definition at line 13 of file CFCMutableArray.cpp.
References CFCReleaser< CFMutableArrayRef >::CFCReleaser().
Referenced by CFCMutableArray(), and operator=().
CFCMutableArray() [2/2]
CFCMutableArray::CFCMutableArray (const CFCMutableArray & rhs) default
References CFCMutableArray().
~CFCMutableArray()
CFCMutableArray::~CFCMutableArray () override default
Member Function Documentation
AppendCStringAsCFString()
bool CFCMutableArray::AppendCStringAsCFString (const char * cstr, CFStringEncoding encoding = kCFStringEncodingUTF8, bool can_create = true)
Definition at line 94 of file CFCMutableArray.cpp.
References CFCReleaser< T >::get(), CFCReleaser< CFMutableArrayRef >::get(), and CFCReleaser< CFMutableArrayRef >::reset().
AppendFileSystemRepresentationAsCFString()
bool CFCMutableArray::AppendFileSystemRepresentationAsCFString (const char * s, bool can_create = true)
Definition at line 113 of file CFCMutableArray.cpp.
References CFCReleaser< T >::get(), CFCReleaser< CFMutableArrayRef >::get(), CFCReleaser< CFMutableArrayRef >::reset(), and CFCString::SetFileSystemRepresentation().
AppendValue()
bool CFCMutableArray::AppendValue (const void * value, bool can_create = true)
Definition at line 78 of file CFCMutableArray.cpp.
References CFCReleaser< CFMutableArrayRef >::get(), and CFCReleaser< CFMutableArrayRef >::reset().
GetCount()
CFIndex CFCMutableArray::GetCount () const
Definition at line 33 of file CFCMutableArray.cpp.
References CFCReleaser< CFMutableArrayRef >::get().
Referenced by GetCountOfValue().
GetCountOfValue() [1/2]
CFIndex CFCMutableArray::GetCountOfValue (CFRange range, const void * value) const
Definition at line 40 of file CFCMutableArray.cpp.
References CFCReleaser< CFMutableArrayRef >::get().
GetCountOfValue() [2/2]
CFIndex CFCMutableArray::GetCountOfValue (const void * value) const
Definition at line 48 of file CFCMutableArray.cpp.
References CFCReleaser< CFMutableArrayRef >::get(), and GetCount().
GetValueAtIndex()
const void * CFCMutableArray::GetValueAtIndex (CFIndex idx) const
Definition at line 55 of file CFCMutableArray.cpp.
References CFCReleaser< CFMutableArrayRef >::get().
operator=()
CFCMutableArray & CFCMutableArray::operator= (const CFCMutableArray & rhs)
Definition at line 23 of file CFCMutableArray.cpp.
References CFCMutableArray().
SetValueAtIndex()
bool CFCMutableArray::SetValueAtIndex (CFIndex idx, const void * value)
Definition at line 66 of file CFCMutableArray.cpp.
References CFCReleaser< CFMutableArrayRef >::get().
The documentation for this class was generated from the following files:
CFCMutableArray.h
CFCMutableArray.cpp