LLDB: lldb_private::SourceManager Class Reference
lldb_private::SourceManager Class Reference
#include <SourceManager.h>
Classes
class File
class SourceFileCache
The SourceFileCache class separates the source manager from the cache of source files.
struct SupportFileAndLine
Public Types
typedef std::shared_ptr< File > FileSP
Public Member Functions
~SourceManager ()
FileSP GetLastFile ()
bool AtLastLine (bool reverse)
size_t DisplaySourceLinesWithLineNumbers (SupportFileNSP support_file_nsp, uint32_t line, uint32_t column, uint32_t context_before, uint32_t context_after, const char *current_line_cstr, Stream *s, const SymbolContextList *bp_locs=nullptr, lldb::LanguageType language_type=lldb::eLanguageTypeUnknown)
size_t DisplaySourceLinesWithLineNumbersUsingLastFile (uint32_t start_line, uint32_t count, uint32_t curr_line, uint32_t column, const char *current_line_cstr, Stream *s, const SymbolContextList *bp_locs=nullptr, lldb::LanguageType language_type=lldb::eLanguageTypeUnknown)
size_t DisplayMoreWithLineNumbers (Stream *s, uint32_t count, bool reverse, const SymbolContextList *bp_locs=nullptr, lldb::LanguageType language_type=lldb::eLanguageTypeUnknown)
bool SetDefaultFileAndLine (SupportFileNSP support_file_nsp, uint32_t line)
std::optional< SupportFileAndLine > GetDefaultFileAndLine ()
bool DefaultFileAndLineSet ()
void FindLinesMatchingRegex (SupportFileNSP support_file_nsp, RegularExpression &regex, uint32_t start_line, uint32_t end_line, std::vector< uint32_t > &match_lines)
FileSP GetFile (SupportFileNSP support_file_nsp)
SourceManager (const lldb::DebuggerSP &debugger_sp)
A source manager can be made with a valid Target, in which case it can use the path remappings to find source files that are not in their build locations.
SourceManager (const lldb::TargetSP &target_sp)
Protected Attributes
SupportFileNSP m_last_support_file_nsp
uint32_t m_last_line
uint32_t m_last_count
bool m_default_set
lldb::TargetWP m_target_wp
lldb::DebuggerWP m_debugger_wp
Private Member Functions
SourceManager (const SourceManager &)=delete
const SourceManager & operator= (const SourceManager &)=delete
Detailed Description
Definition at line 35 of file SourceManager.h.
Member Typedef Documentation
FileSP
typedef std::shared_ptr<File> lldb_private::SourceManager::FileSP
Definition at line 118 of file SourceManager.h.
Constructor & Destructor Documentation
SourceManager() [1/3]
SourceManager::SourceManager (const lldb::DebuggerSP & debugger_sp)
A source manager can be made with a valid Target, in which case it can use the path remappings to find source files that are not in their build locations.
Without a target it won't be able to do this.
Definition at line 72 of file SourceManager.cpp.
References m_debugger_wp, m_default_set, m_last_count, m_last_line, m_last_support_file_nsp, and m_target_wp.
Referenced by operator=(), and SourceManager().
SourceManager() [2/3]
lldb_private::SourceManager::SourceManager (const lldb::TargetSP & target_sp)
~SourceManager()
SourceManager::~SourceManager () default
SourceManager() [3/3]
lldb_private::SourceManager::SourceManager (const SourceManager &) private delete
References SourceManager().
Member Function Documentation
AtLastLine()
bool lldb_private::SourceManager::AtLastLine (bool reverse) inline
Definition at line 162 of file SourceManager.h.
References m_last_line, and UINT32_MAX.
Referenced by DisplayMoreWithLineNumbers(), and CommandObjectSourceList::DoExecute().
DefaultFileAndLineSet()
bool lldb_private::SourceManager::DefaultFileAndLineSet () inline
Definition at line 196 of file SourceManager.h.
References GetFile(), and m_last_support_file_nsp.
DisplayMoreWithLineNumbers()
size_t SourceManager::DisplayMoreWithLineNumbers (Stream * s, uint32_t count, bool reverse, const SymbolContextList * bp_locs = nullptr, lldb::LanguageType language_type = lldb::eLanguageTypeUnknown)
Definition at line 353 of file SourceManager.cpp.
References AtLastLine(), DisplaySourceLinesWithLineNumbersUsingLastFile(), GetDefaultFileAndLine(), GetLastFile(), m_default_set, m_last_count, m_last_line, and UINT32_MAX.
Referenced by CommandObjectSourceList::DoExecute().
DisplaySourceLinesWithLineNumbers()
size_t SourceManager::DisplaySourceLinesWithLineNumbers (SupportFileNSP support_file_nsp, uint32_t line, uint32_t column, uint32_t context_before, uint32_t context_after, const char * current_line_cstr, Stream * s, const SymbolContextList * bp_locs = nullptr, lldb::LanguageType language_type = lldb::eLanguageTypeUnknown)
Definition at line 326 of file SourceManager.cpp.
References DisplaySourceLinesWithLineNumbersUsingLastFile(), GetFile(), GetLastFile(), m_last_line, and m_last_support_file_nsp.
Referenced by CommandObjectSourceList::DisplayFunctionSource(), CommandObjectSourceList::DoExecute(), lldb_private::StackFrame::GetStatus(), and lldb_private::Disassembler::PrintInstructions().
DisplaySourceLinesWithLineNumbersUsingLastFile()
size_t SourceManager::DisplaySourceLinesWithLineNumbersUsingLastFile (uint32_t start_line, uint32_t count, uint32_t curr_line, uint32_t column, const char * current_line_cstr, Stream * s, const SymbolContextList * bp_locs = nullptr, lldb::LanguageType language_type = lldb::eLanguageTypeUnknown)
Definition at line 227 of file SourceManager.cpp.
References lldb_private::ansi::FormatAnsiTerminalCodes(), GetDefaultFileAndLine(), GetLastFile(), m_debugger_wp, m_default_set, m_last_count, m_last_line, lldb_private::SymbolContextList::NumLineEntriesWithLine(), lldb_private::Stream::Printf(), lldb_private::Stream::PutChar(), lldb_private::Debugger::ReportWarning(), should_show_stop_column_with_caret(), should_show_stop_line_with_ansi(), lldb_private::toString(), and UINT32_MAX.
Referenced by DisplayMoreWithLineNumbers(), DisplaySourceLinesWithLineNumbers(), and CommandObjectSourceList::DoExecute().
FindLinesMatchingRegex()
void SourceManager::FindLinesMatchingRegex (SupportFileNSP support_file_nsp, RegularExpression & regex, uint32_t start_line, uint32_t end_line, std::vector< uint32_t > & match_lines)
Definition at line 451 of file SourceManager.cpp.
References GetFile().
GetDefaultFileAndLine()
std::optional< SourceManager::SupportFileAndLine > SourceManager::GetDefaultFileAndLine ()
Definition at line 410 of file SourceManager.cpp.
References lldb_private::LineEntry::file_sp, lldb_private::Module::FindFunctions(), GetLastFile(), lldb_private::ModuleFunctionSearchOptions::include_inlines, lldb_private::ModuleFunctionSearchOptions::include_symbols, lldb_private::LineEntry::line, m_default_set, m_last_line, m_last_support_file_nsp, m_target_wp, and SetDefaultFileAndLine().
Referenced by DisplayMoreWithLineNumbers(), DisplaySourceLinesWithLineNumbersUsingLastFile(), and GetDefaultFile().
GetFile()
SourceManager::FileSP SourceManager::GetFile (SupportFileNSP support_file_nsp)
Definition at line 85 of file SourceManager.cpp.
References lldb_private::GetLog(), lldb_private::FileSystem::Instance(), LLDB_LOG, m_debugger_wp, m_target_wp, and lldb_private::Source.
Referenced by DefaultFileAndLineSet(), DisplaySourceLinesWithLineNumbers(), FindLinesMatchingRegex(), GetLastFile(), and SetDefaultFileAndLine().
GetLastFile()
FileSP lldb_private::SourceManager::GetLastFile () inline
Definition at line 161 of file SourceManager.h.
References GetFile(), and m_last_support_file_nsp.
Referenced by DisplayMoreWithLineNumbers(), DisplaySourceLinesWithLineNumbers(), DisplaySourceLinesWithLineNumbersUsingLastFile(), CommandObjectSourceList::DoExecute(), and GetDefaultFileAndLine().
operator=()
const SourceManager & lldb_private::SourceManager::operator= (const SourceManager &) private delete
References SourceManager().
SetDefaultFileAndLine()
bool SourceManager::SetDefaultFileAndLine (SupportFileNSP support_file_nsp, uint32_t line)
Definition at line 394 of file SourceManager.cpp.
References GetFile(), m_default_set, m_last_line, and m_last_support_file_nsp.
Referenced by GetDefaultFileAndLine().
Member Data Documentation
m_debugger_wp
lldb::DebuggerWP lldb_private::SourceManager::m_debugger_wp protected
Definition at line 213 of file SourceManager.h.
Referenced by DisplaySourceLinesWithLineNumbersUsingLastFile(), GetFile(), and SourceManager().
m_default_set
bool lldb_private::SourceManager::m_default_set protected
Definition at line 211 of file SourceManager.h.
Referenced by DisplayMoreWithLineNumbers(), DisplaySourceLinesWithLineNumbersUsingLastFile(), GetDefaultFileAndLine(), SetDefaultFileAndLine(), and SourceManager().
m_last_count
uint32_t lldb_private::SourceManager::m_last_count protected
Definition at line 210 of file SourceManager.h.
Referenced by DisplayMoreWithLineNumbers(), DisplaySourceLinesWithLineNumbersUsingLastFile(), and SourceManager().
m_last_line
uint32_t lldb_private::SourceManager::m_last_line protected
Definition at line 209 of file SourceManager.h.
Referenced by AtLastLine(), DisplayMoreWithLineNumbers(), DisplaySourceLinesWithLineNumbers(), DisplaySourceLinesWithLineNumbersUsingLastFile(), GetDefaultFileAndLine(), SetDefaultFileAndLine(), and SourceManager().
m_last_support_file_nsp
SupportFileNSP lldb_private::SourceManager::m_last_support_file_nsp protected
Definition at line 208 of file SourceManager.h.
Referenced by DefaultFileAndLineSet(), DisplaySourceLinesWithLineNumbers(), GetDefaultFileAndLine(), GetLastFile(), SetDefaultFileAndLine(), and SourceManager().
m_target_wp
lldb::TargetWP lldb_private::SourceManager::m_target_wp protected
Definition at line 212 of file SourceManager.h.
Referenced by GetDefaultFileAndLine(), GetFile(), and SourceManager().
The documentation for this class was generated from the following files:
SourceManager.h
SourceManager.cpp