LLDB: lldb_private::plugin::dwarf::DWARFContext Class Reference
lldb_private::plugin::dwarf::DWARFContext Class Reference
#include <DWARFContext.h>
Classes
struct SectionData
Public Member Functions
DWARFContext (SectionList *main_section_list, SectionList *dwo_section_list)
const DWARFDataExtractor & getOrLoadAbbrevData ()
const DWARFDataExtractor & getOrLoadAddrData ()
const DWARFDataExtractor & getOrLoadArangesData ()
const DWARFDataExtractor & getOrLoadDebugInfoData ()
const DWARFDataExtractor & getOrLoadLineData ()
const DWARFDataExtractor & getOrLoadLineStrData ()
const DWARFDataExtractor & getOrLoadLocData ()
const DWARFDataExtractor & getOrLoadLocListsData ()
const DWARFDataExtractor & getOrLoadMacroData ()
const DWARFDataExtractor & getOrLoadRangesData ()
const DWARFDataExtractor & getOrLoadRngListsData ()
const DWARFDataExtractor & getOrLoadStrData ()
const DWARFDataExtractor & getOrLoadStrOffsetsData ()
const DWARFDataExtractor & getOrLoadDebugTypesData ()
bool isDwo ()
llvm::DWARFContext & GetAsLLVM ()
Private Member Functions
const DWARFDataExtractor & LoadOrGetSection (std::optional< lldb::SectionType > main_section_type, std::optional< lldb::SectionType > dwo_section_type, SectionData &data)
const DWARFDataExtractor & getOrLoadCuIndexData ()
const DWARFDataExtractor & getOrLoadTuIndexData ()
Private Attributes
SectionList * m_main_section_list
SectionList * m_dwo_section_list
std::unique_ptr< llvm::DWARFContext > m_llvm_context
SectionData m_data_debug_abbrev
SectionData m_data_debug_addr
SectionData m_data_debug_aranges
SectionData m_data_debug_cu_index
SectionData m_data_debug_info
SectionData m_data_debug_line
SectionData m_data_debug_line_str
SectionData m_data_debug_loc
SectionData m_data_debug_loclists
SectionData m_data_debug_macro
SectionData m_data_debug_ranges
SectionData m_data_debug_rnglists
SectionData m_data_debug_str
SectionData m_data_debug_str_offsets
SectionData m_data_debug_tu_index
SectionData m_data_debug_types
Detailed Description
Definition at line 21 of file DWARFContext.h.
Constructor & Destructor Documentation
DWARFContext()
lldb_private::plugin::dwarf::DWARFContext::DWARFContext (SectionList * main_section_list, SectionList * dwo_section_list) inline explicit
Definition at line 58 of file DWARFContext.h.
References m_dwo_section_list, and m_main_section_list.
Member Function Documentation
GetAsLLVM()
llvm::DWARFContext & DWARFContext::GetAsLLVM ()
Definition at line 128 of file DWARFContext.cpp.
References getOrLoadCuIndexData(), getOrLoadDebugInfoData(), getOrLoadDebugTypesData(), getOrLoadLineStrData(), getOrLoadTuIndexData(), isDwo(), and m_llvm_context.
Referenced by lldb_private::plugin::dwarf::DWARFUnit::extract(), ParseLLVMLineTable(), and ParseLLVMLineTablePrologue().
getOrLoadAbbrevData()
const DWARFDataExtractor & DWARFContext::getOrLoadAbbrevData ()
Definition at line 55 of file DWARFContext.cpp.
References lldb::eSectionTypeDWARFDebugAbbrev, lldb::eSectionTypeDWARFDebugAbbrevDwo, LoadOrGetSection(), and m_data_debug_abbrev.
getOrLoadAddrData()
const DWARFDataExtractor & DWARFContext::getOrLoadAddrData ()
Definition at line 65 of file DWARFContext.cpp.
References lldb::eSectionTypeDWARFDebugAddr, LoadOrGetSection(), and m_data_debug_addr.
Referenced by lldb_private::plugin::dwarf::DWARFFormValue::Address().
getOrLoadArangesData()
const DWARFDataExtractor & DWARFContext::getOrLoadArangesData ()
Definition at line 60 of file DWARFContext.cpp.
References lldb::eSectionTypeDWARFDebugAranges, LoadOrGetSection(), and m_data_debug_aranges.
getOrLoadCuIndexData()
const DWARFDataExtractor & DWARFContext::getOrLoadCuIndexData () private
Definition at line 45 of file DWARFContext.cpp.
References lldb::eSectionTypeDWARFDebugCuIndex, LoadOrGetSection(), and m_data_debug_cu_index.
Referenced by GetAsLLVM().
getOrLoadDebugInfoData()
const DWARFDataExtractor & DWARFContext::getOrLoadDebugInfoData ()
Definition at line 70 of file DWARFContext.cpp.
References lldb::eSectionTypeDWARFDebugInfo, lldb::eSectionTypeDWARFDebugInfoDwo, LoadOrGetSection(), and m_data_debug_info.
Referenced by GetAsLLVM().
getOrLoadDebugTypesData()
const DWARFDataExtractor & DWARFContext::getOrLoadDebugTypesData ()
Definition at line 123 of file DWARFContext.cpp.
References lldb::eSectionTypeDWARFDebugTypes, lldb::eSectionTypeDWARFDebugTypesDwo, LoadOrGetSection(), and m_data_debug_types.
Referenced by GetAsLLVM().
getOrLoadLineData()
const DWARFDataExtractor & DWARFContext::getOrLoadLineData ()
Definition at line 75 of file DWARFContext.cpp.
References lldb::eSectionTypeDWARFDebugLine, LoadOrGetSection(), and m_data_debug_line.
Referenced by ParseLLVMLineTable(), and ParseLLVMLineTablePrologue().
getOrLoadLineStrData()
const DWARFDataExtractor & DWARFContext::getOrLoadLineStrData ()
Definition at line 80 of file DWARFContext.cpp.
References lldb::eSectionTypeDWARFDebugLineStr, LoadOrGetSection(), and m_data_debug_line_str.
Referenced by lldb_private::plugin::dwarf::DWARFFormValue::AsCString(), and GetAsLLVM().
getOrLoadLocData()
const DWARFDataExtractor & DWARFContext::getOrLoadLocData ()
Definition at line 85 of file DWARFContext.cpp.
References lldb::eSectionTypeDWARFDebugLoc, lldb::eSectionTypeDWARFDebugLocDwo, LoadOrGetSection(), and m_data_debug_loc.
Referenced by lldb_private::plugin::dwarf::DWARFUnit::GetLocationData().
getOrLoadLocListsData()
const DWARFDataExtractor & DWARFContext::getOrLoadLocListsData ()
Definition at line 90 of file DWARFContext.cpp.
References lldb::eSectionTypeDWARFDebugLocLists, lldb::eSectionTypeDWARFDebugLocListsDwo, LoadOrGetSection(), and m_data_debug_loclists.
Referenced by lldb_private::plugin::dwarf::DWARFUnit::GetLocationData().
getOrLoadMacroData()
const DWARFDataExtractor & DWARFContext::getOrLoadMacroData ()
Definition at line 96 of file DWARFContext.cpp.
References lldb::eSectionTypeDWARFDebugMacro, LoadOrGetSection(), and m_data_debug_macro.
getOrLoadRangesData()
const DWARFDataExtractor & DWARFContext::getOrLoadRangesData ()
Definition at line 101 of file DWARFContext.cpp.
References lldb::eSectionTypeDWARFDebugRanges, LoadOrGetSection(), and m_data_debug_ranges.
getOrLoadRngListsData()
const DWARFDataExtractor & DWARFContext::getOrLoadRngListsData ()
Definition at line 106 of file DWARFContext.cpp.
References lldb::eSectionTypeDWARFDebugRngLists, lldb::eSectionTypeDWARFDebugRngListsDwo, LoadOrGetSection(), and m_data_debug_rnglists.
Referenced by lldb_private::plugin::dwarf::DWARFUnit::GetRnglistData().
getOrLoadStrData()
const DWARFDataExtractor & DWARFContext::getOrLoadStrData ()
Definition at line 112 of file DWARFContext.cpp.
References lldb::eSectionTypeDWARFDebugStr, lldb::eSectionTypeDWARFDebugStrDwo, LoadOrGetSection(), and m_data_debug_str.
Referenced by lldb_private::plugin::dwarf::DWARFFormValue::AsCString().
getOrLoadStrOffsetsData()
const DWARFDataExtractor & DWARFContext::getOrLoadStrOffsetsData ()
Definition at line 117 of file DWARFContext.cpp.
References lldb::eSectionTypeDWARFDebugStrOffsets, lldb::eSectionTypeDWARFDebugStrOffsetsDwo, LoadOrGetSection(), and m_data_debug_str_offsets.
Referenced by lldb_private::plugin::dwarf::DWARFUnit::SetDwoStrOffsetsBase().
getOrLoadTuIndexData()
const DWARFDataExtractor & DWARFContext::getOrLoadTuIndexData () private
Definition at line 50 of file DWARFContext.cpp.
References lldb::eSectionTypeDWARFDebugTuIndex, LoadOrGetSection(), and m_data_debug_tu_index.
Referenced by GetAsLLVM().
isDwo()
bool lldb_private::plugin::dwarf::DWARFContext::isDwo () inline
Definition at line 78 of file DWARFContext.h.
References m_dwo_section_list.
Referenced by lldb_private::plugin::dwarf::DWARFUnit::extract(), and GetAsLLVM().
LoadOrGetSection()
const DWARFDataExtractor & DWARFContext::LoadOrGetSection (std::optional< lldb::SectionType > main_section_type, std::optional< lldb::SectionType > dwo_section_type, SectionData & data) private
Definition at line 33 of file DWARFContext.cpp.
References lldb_private::plugin::dwarf::DWARFContext::SectionData::data, and lldb_private::plugin::dwarf::DWARFContext::SectionData::flag.
Referenced by getOrLoadAbbrevData(), getOrLoadAddrData(), getOrLoadArangesData(), getOrLoadCuIndexData(), getOrLoadDebugInfoData(), getOrLoadDebugTypesData(), getOrLoadLineData(), getOrLoadLineStrData(), getOrLoadLocData(), getOrLoadLocListsData(), getOrLoadMacroData(), getOrLoadRangesData(), getOrLoadRngListsData(), getOrLoadStrData(), getOrLoadStrOffsetsData(), and getOrLoadTuIndexData().
Member Data Documentation
m_data_debug_abbrev
SectionData lldb_private::plugin::dwarf::DWARFContext::m_data_debug_abbrev private
Definition at line 32 of file DWARFContext.h.
Referenced by getOrLoadAbbrevData().
m_data_debug_addr
SectionData lldb_private::plugin::dwarf::DWARFContext::m_data_debug_addr private
Definition at line 33 of file DWARFContext.h.
Referenced by getOrLoadAddrData().
m_data_debug_aranges
SectionData lldb_private::plugin::dwarf::DWARFContext::m_data_debug_aranges private
Definition at line 34 of file DWARFContext.h.
Referenced by getOrLoadArangesData().
m_data_debug_cu_index
SectionData lldb_private::plugin::dwarf::DWARFContext::m_data_debug_cu_index private
Definition at line 35 of file DWARFContext.h.
Referenced by getOrLoadCuIndexData().
m_data_debug_info
SectionData lldb_private::plugin::dwarf::DWARFContext::m_data_debug_info private
Definition at line 36 of file DWARFContext.h.
Referenced by getOrLoadDebugInfoData().
m_data_debug_line
SectionData lldb_private::plugin::dwarf::DWARFContext::m_data_debug_line private
Definition at line 37 of file DWARFContext.h.
Referenced by getOrLoadLineData().
m_data_debug_line_str
SectionData lldb_private::plugin::dwarf::DWARFContext::m_data_debug_line_str private
Definition at line 38 of file DWARFContext.h.
Referenced by getOrLoadLineStrData().
m_data_debug_loc
SectionData lldb_private::plugin::dwarf::DWARFContext::m_data_debug_loc private
Definition at line 39 of file DWARFContext.h.
Referenced by getOrLoadLocData().
m_data_debug_loclists
SectionData lldb_private::plugin::dwarf::DWARFContext::m_data_debug_loclists private
Definition at line 40 of file DWARFContext.h.
Referenced by getOrLoadLocListsData().
m_data_debug_macro
SectionData lldb_private::plugin::dwarf::DWARFContext::m_data_debug_macro private
Definition at line 41 of file DWARFContext.h.
Referenced by getOrLoadMacroData().
m_data_debug_ranges
SectionData lldb_private::plugin::dwarf::DWARFContext::m_data_debug_ranges private
Definition at line 42 of file DWARFContext.h.
Referenced by getOrLoadRangesData().
m_data_debug_rnglists
SectionData lldb_private::plugin::dwarf::DWARFContext::m_data_debug_rnglists private
Definition at line 43 of file DWARFContext.h.
Referenced by getOrLoadRngListsData().
m_data_debug_str
SectionData lldb_private::plugin::dwarf::DWARFContext::m_data_debug_str private
Definition at line 44 of file DWARFContext.h.
Referenced by getOrLoadStrData().
m_data_debug_str_offsets
SectionData lldb_private::plugin::dwarf::DWARFContext::m_data_debug_str_offsets private
Definition at line 45 of file DWARFContext.h.
Referenced by getOrLoadStrOffsetsData().
m_data_debug_tu_index
SectionData lldb_private::plugin::dwarf::DWARFContext::m_data_debug_tu_index private
Definition at line 46 of file DWARFContext.h.
Referenced by getOrLoadTuIndexData().
m_data_debug_types
SectionData lldb_private::plugin::dwarf::DWARFContext::m_data_debug_types private
Definition at line 47 of file DWARFContext.h.
Referenced by getOrLoadDebugTypesData().
m_dwo_section_list
SectionList* lldb_private::plugin::dwarf::DWARFContext::m_dwo_section_list private
Definition at line 24 of file DWARFContext.h.
Referenced by DWARFContext(), and isDwo().
m_llvm_context
std::unique_ptr<llvm::DWARFContext> lldb_private::plugin::dwarf::DWARFContext::m_llvm_context mutable private
Definition at line 25 of file DWARFContext.h.
Referenced by GetAsLLVM().
m_main_section_list
SectionList* lldb_private::plugin::dwarf::DWARFContext::m_main_section_list private
Definition at line 23 of file DWARFContext.h.
Referenced by DWARFContext().
The documentation for this class was generated from the following files:
DWARFContext.h
DWARFContext.cpp