LLDB: lldb_private::CompilerDeclContext Class Reference
lldb_private::CompilerDeclContext Class Reference
Represents a generic declaration context in a program.
#include <CompilerDeclContext.h>
Public Member Functions
CompilerDeclContext ()=default
Constructs an invalid CompilerDeclContext.
CompilerDeclContext (TypeSystem *type_system, void *decl_ctx)
Constructs a CompilerDeclContext with the given opaque decl context and its respective TypeSystem instance.
operator bool () const
bool operator< (const CompilerDeclContext &rhs) const
bool IsValid () const
std::vector< lldb_private::CompilerContext > GetCompilerContext () const
Populate a valid compiler context from the current decl context.
std::vector< CompilerDecl > FindDeclByName (ConstString name, const bool ignore_using_decls)
bool IsClassMethod ()
Checks if this decl context represents a method of a class.
lldb::LanguageType GetLanguage ()
Determines the original language of the decl context.
bool IsContainedInLookup (CompilerDeclContext other) const
Check if the given other decl context is contained in the lookup of this decl context (for example because the other context is a nested inline namespace).
TypeSystem * GetTypeSystem () const
void * GetOpaqueDeclContext () const
void SetDeclContext (TypeSystem *type_system, void *decl_ctx)
void Clear ()
ConstString GetName () const
ConstString GetScopeQualifiedName () const
Private Attributes
TypeSystem * m_type_system = nullptr
void * m_opaque_decl_ctx = nullptr
Detailed Description
Represents a generic declaration context in a program.
A declaration context is data structure that contains declarations (e.g. namespaces).
This class serves as an abstraction for a declaration context inside one of the TypeSystems implemented by the language plugins. It does not have any actual logic in it but only stores an opaque pointer and a pointer to the TypeSystem that gives meaning to this opaque pointer. All methods of this class should call their respective method in the TypeSystem interface and pass the opaque pointer along.
See also
lldb_private::TypeSystem
Definition at line 31 of file CompilerDeclContext.h.
Constructor & Destructor Documentation
CompilerDeclContext() [1/2]
lldb_private::CompilerDeclContext::CompilerDeclContext () default
Constructs an invalid CompilerDeclContext.
Referenced by IsContainedInLookup(), and operator<().
CompilerDeclContext() [2/2]
lldb_private::CompilerDeclContext::CompilerDeclContext (TypeSystem * type_system, void * decl_ctx) inline
Constructs a CompilerDeclContext with the given opaque decl context and its respective TypeSystem instance.
This constructor should only be called from the respective TypeSystem implementation.
See also
lldb_private::TypeSystemClang::CreateDeclContext(clang::DeclContext*)
Definition at line 43 of file CompilerDeclContext.h.
References m_opaque_decl_ctx, and m_type_system.
Member Function Documentation
Clear()
void lldb_private::CompilerDeclContext::Clear () inline
Definition at line 103 of file CompilerDeclContext.h.
References m_opaque_decl_ctx, and m_type_system.
FindDeclByName()
std::vector< CompilerDecl > CompilerDeclContext::FindDeclByName (ConstString name, const bool ignore_using_decls)
Definition at line 17 of file CompilerDeclContext.cpp.
References IsValid(), m_opaque_decl_ctx, and m_type_system.
Referenced by lldb_private::ClangExpressionDeclMap::LookupLocalVariable().
GetCompilerContext()
std::vector< lldb_private::CompilerContext > CompilerDeclContext::GetCompilerContext () const
Populate a valid compiler context from the current decl context.
Returns
A valid vector of CompilerContext entries that describes this declaration context. The first entry in the vector is the parent of the subsequent entry, so the topmost entry is the global namespace.
Definition at line 63 of file CompilerDeclContext.cpp.
References IsValid(), m_opaque_decl_ctx, and m_type_system.
Referenced by lldb_private::plugin::dwarf::DebugNamesDWARFIndex::GetNamespacesWithParents(), and lldb_private::TypeQuery::TypeQuery().
GetLanguage()
lldb::LanguageType CompilerDeclContext::GetLanguage ()
Determines the original language of the decl context.
Definition at line 43 of file CompilerDeclContext.cpp.
References IsValid(), m_opaque_decl_ctx, and m_type_system.
GetName()
ConstString CompilerDeclContext::GetName () const
Definition at line 25 of file CompilerDeclContext.cpp.
References IsValid(), m_opaque_decl_ctx, and m_type_system.
Referenced by lldb_private::ClangExpressionDeclMap::FindExternalVisibleDecls(), and lldb_private::plugin::dwarf::SymbolFileDWARF::FindNamespace().
GetOpaqueDeclContext()
void * lldb_private::CompilerDeclContext::GetOpaqueDeclContext () const inline
Definition at line 96 of file CompilerDeclContext.h.
References m_opaque_decl_ctx.
Referenced by lldb_private::ClangExpressionDeclMap::AddOneFunction(), lldb_private::TypeSystemClang::DeclContextGetAsCXXMethodDecl(), lldb_private::TypeSystemClang::DeclContextGetAsDeclContext(), lldb_private::TypeSystemClang::DeclContextGetAsFunctionDecl(), lldb_private::TypeSystemClang::DeclContextGetAsNamespaceDecl(), lldb_private::TypeSystemClang::DeclContextGetAsObjCMethodDecl(), DWARFASTParserClang::EnsureAllDIEsInDeclContextHaveBeenParsed(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindNamespace(), SymbolFilePDB::FindNamespace(), lldb_private::npdb::PdbAstBuilderClang::FromCompilerDeclContext(), DWARFASTParserClang::GetDeclContextForBlock(), lldb_private::operator!=(), lldb_private::operator==(), SymbolFilePDB::ParseDeclsForContext(), and lldb_private::ClangExpressionDeclMap::SearchFunctionsInSymbolContexts().
GetScopeQualifiedName()
ConstString CompilerDeclContext::GetScopeQualifiedName () const
Definition at line 31 of file CompilerDeclContext.cpp.
References IsValid(), m_opaque_decl_ctx, and m_type_system.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::ParseType().
GetTypeSystem()
TypeSystem * lldb_private::CompilerDeclContext::GetTypeSystem () const inline
Definition at line 94 of file CompilerDeclContext.h.
References m_type_system.
Referenced by lldb_private::ClangExpressionDeclMap::AddOneFunction(), lldb_private::TypeSystemClang::DeclContextGetMetaData(), lldb_private::TypeSystemClang::DeclContextGetTypeSystemClang(), lldb_private::plugin::dwarf::SymbolFileDWARF::DeclContextMatchesThisSymbolFile(), SymbolFilePDB::DeclContextMatchesThisSymbolFile(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindNamespace(), lldb_private::ClangExpressionDeclMap::GetTypeSystemClang(), IsClangDeclContext(), lldb_private::ClangExpressionDeclMap::LookUpLldbClass(), lldb_private::ClangExpressionDeclMap::LookUpLldbObjCClass(), lldb_private::ClangExpressionDeclMap::LookupLocalVarNamespace(), lldb_private::operator!=(), lldb_private::operator==(), lldb_private::npdb::SymbolFileNativePDB::ParseDeclsForContext(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseDeclsForContext(), and lldb_private::ClangExpressionDeclMap::SearchFunctionsInSymbolContexts().
IsClassMethod()
bool CompilerDeclContext::IsClassMethod ()
Checks if this decl context represents a method of a class.
Returns
Returns true if this is a decl context that represents a method in a struct, union or class.
Definition at line 37 of file CompilerDeclContext.cpp.
References IsValid(), m_opaque_decl_ctx, and m_type_system.
Referenced by lldb_private::ClangExpressionDeclMap::LookupFunction(), and lldb_private::ClangExpressionDeclMap::SearchFunctionsInSymbolContexts().
IsContainedInLookup()
bool CompilerDeclContext::IsContainedInLookup (CompilerDeclContext other) const
Check if the given other decl context is contained in the lookup of this decl context (for example because the other context is a nested inline namespace).
Parameters
[in] other The other decl context for which we should check if it is contained in the lookoup of this context.
Returns
Returns true iff the other decl context is contained in the lookup of this decl context.
Definition at line 49 of file CompilerDeclContext.cpp.
References CompilerDeclContext(), IsValid(), m_opaque_decl_ctx, and m_type_system.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::DIEInDeclContext(), and lldb_private::plugin::dwarf::SymbolFileDWARF::FindGlobalVariables().
IsValid()
bool lldb_private::CompilerDeclContext::IsValid () const inline
Definition at line 55 of file CompilerDeclContext.h.
References m_opaque_decl_ctx, and m_type_system.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::DeclContextMatchesThisSymbolFile(), SymbolFilePDB::DeclContextMatchesThisSymbolFile(), lldb_private::plugin::dwarf::SymbolFileDWARF::DIEInDeclContext(), FindDeclByName(), lldb_private::npdb::SymbolFileNativePDB::FindFunctions(), lldb_private::npdb::SymbolFileNativePDB::FindGlobalVariables(), SymbolFilePDB::FindGlobalVariables(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindNamespace(), GetCompilerContext(), lldb_private::plugin::dwarf::ManualDWARFIndex::GetFunctions(), GetLanguage(), GetName(), GetScopeQualifiedName(), IsClangDeclContext(), IsClassMethod(), IsContainedInLookup(), lldb_private::ClangExpressionDeclMap::LookupLocalVariable(), operator bool(), and lldb_private::plugin::dwarf::DWARFIndex::ProcessFunctionDIE().
operator bool()
lldb_private::CompilerDeclContext::operator bool () const inline explicit
Definition at line 48 of file CompilerDeclContext.h.
References IsValid().
operator<()
bool lldb_private::CompilerDeclContext::operator< (const CompilerDeclContext & rhs) const inline
Definition at line 50 of file CompilerDeclContext.h.
References CompilerDeclContext(), m_opaque_decl_ctx, and m_type_system.
SetDeclContext()
void lldb_private::CompilerDeclContext::SetDeclContext (TypeSystem * type_system, void * decl_ctx) inline
Definition at line 98 of file CompilerDeclContext.h.
References m_opaque_decl_ctx, and m_type_system.
Member Data Documentation
m_opaque_decl_ctx
void* lldb_private::CompilerDeclContext::m_opaque_decl_ctx = nullptr private
Definition at line 114 of file CompilerDeclContext.h.
Referenced by Clear(), CompilerDeclContext(), FindDeclByName(), GetCompilerContext(), GetLanguage(), GetName(), GetOpaqueDeclContext(), GetScopeQualifiedName(), IsClassMethod(), IsContainedInLookup(), IsValid(), operator<(), and SetDeclContext().
m_type_system
TypeSystem* lldb_private::CompilerDeclContext::m_type_system = nullptr private
Definition at line 113 of file CompilerDeclContext.h.
Referenced by Clear(), CompilerDeclContext(), FindDeclByName(), GetCompilerContext(), GetLanguage(), GetName(), GetScopeQualifiedName(), GetTypeSystem(), IsClassMethod(), IsContainedInLookup(), IsValid(), operator<(), and SetDeclContext().
The documentation for this class was generated from the following files:
CompilerDeclContext.h
CompilerDeclContext.cpp