LLDB: ToTimeSpec Class Reference
ToTimeSpec Class Reference
Public Member Functions
ToTimeSpec (std::optional< MainLoopPosix::TimePoint > point)
ToTimeSpec (const ToTimeSpec &)=delete
ToTimeSpec & operator= (const ToTimeSpec &)=delete
operator struct timespec * ()
Private Attributes
struct timespec m_ts
struct timespec * m_ts_ptr
Detailed Description
Definition at line 72 of file MainLoopPosix.cpp.
Constructor & Destructor Documentation
ToTimeSpec() [1/2]
ToTimeSpec::ToTimeSpec (std::optional< MainLoopPosix::TimePoint > point) inline explicit
Definition at line 74 of file MainLoopPosix.cpp.
References m_ts, and m_ts_ptr.
Referenced by operator=(), and ToTimeSpec().
ToTimeSpec() [2/2]
ToTimeSpec::ToTimeSpec (const ToTimeSpec &) delete
References ToTimeSpec().
Member Function Documentation
operator struct timespec *()
ToTimeSpec::operator struct timespec * () inline
Definition at line 89 of file MainLoopPosix.cpp.
References m_ts_ptr.
operator=()
ToTimeSpec & ToTimeSpec::operator= (const ToTimeSpec &) delete
References ToTimeSpec().
Member Data Documentation
m_ts
struct timespec ToTimeSpec::m_ts private
Definition at line 92 of file MainLoopPosix.cpp.
Referenced by ToTimeSpec().
m_ts_ptr
struct timespec* ToTimeSpec::m_ts_ptr private
Definition at line 93 of file MainLoopPosix.cpp.
Referenced by operator struct timespec *(), and ToTimeSpec().
The documentation for this class was generated from the following file:
MainLoopPosix.cpp