LLDB: lldb::SBTypeMemberFunction Class Reference
lldb::SBTypeMemberFunction Class Reference
#include <SBType.h>
Public Member Functions
SBTypeMemberFunction ()
SBTypeMemberFunction (const lldb::SBTypeMemberFunction &rhs)
~SBTypeMemberFunction ()
lldb::SBTypeMemberFunction & operator= (const lldb::SBTypeMemberFunction &rhs)
operator bool () const
bool IsValid () const
const char * GetName ()
const char * GetDemangledName ()
const char * GetMangledName ()
lldb::SBType GetType ()
lldb::SBType GetReturnType ()
uint32_t GetNumberOfArguments ()
lldb::SBType GetArgumentTypeAtIndex (uint32_t)
lldb::MemberFunctionKind GetKind ()
bool GetDescription (lldb::SBStream &description, lldb::DescriptionLevel description_level)
Protected Member Functions
void reset (lldb_private::TypeMemberFunctionImpl *)
lldb_private::TypeMemberFunctionImpl & ref ()
const lldb_private::TypeMemberFunctionImpl & ref () const
Protected Attributes
lldb::TypeMemberFunctionImplSP m_opaque_sp
Friends
class SBType
Detailed Description
Definition at line 65 of file SBType.h.
Constructor & Destructor Documentation
SBTypeMemberFunction() [1/2]
SBTypeMemberFunction::SBTypeMemberFunction ()
Definition at line 917 of file SBType.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by SBTypeMemberFunction().
SBTypeMemberFunction() [2/2]
SBTypeMemberFunction::SBTypeMemberFunction (const lldb::SBTypeMemberFunction & rhs)
Definition at line 921 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBTypeMemberFunction().
~SBTypeMemberFunction()
SBTypeMemberFunction::~SBTypeMemberFunction () default
Member Function Documentation
GetArgumentTypeAtIndex()
lldb::SBType SBTypeMemberFunction::GetArgumentTypeAtIndex (uint32_t i)
Definition at line 1003 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, SBType, and lldb::SBType::SetSP().
GetDemangledName()
const char * SBTypeMemberFunction::GetDemangledName ()
Definition at line 953 of file SBType.cpp.
References lldb_private::ConstString::GetCString(), lldb_private::Mangled::GetDemangledName(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetDescription()
bool SBTypeMemberFunction::GetDescription (lldb::SBStream & description, lldb::DescriptionLevel description_level)
Definition at line 1022 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBStream::ref().
GetKind()
lldb::MemberFunctionKind SBTypeMemberFunction::GetKind ()
Definition at line 1014 of file SBType.cpp.
References lldb::eMemberFunctionKindUnknown, LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetMangledName()
const char * SBTypeMemberFunction::GetMangledName ()
Definition at line 967 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetName()
const char * SBTypeMemberFunction::GetName ()
Definition at line 945 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetNumberOfArguments()
uint32_t SBTypeMemberFunction::GetNumberOfArguments ()
Definition at line 995 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetReturnType()
lldb::SBType SBTypeMemberFunction::GetReturnType ()
Definition at line 985 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, SBType, and lldb::SBType::SetSP().
GetType()
SBType SBTypeMemberFunction::GetType ()
Definition at line 975 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, SBType, and lldb::SBType::SetSP().
IsValid()
bool SBTypeMemberFunction::IsValid () const
Definition at line 935 of file SBType.cpp.
References LLDB_INSTRUMENT_VA.
operator bool()
SBTypeMemberFunction::operator bool () const explicit
Definition at line 939 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator=()
lldb::SBTypeMemberFunction & SBTypeMemberFunction::operator= (const lldb::SBTypeMemberFunction & rhs)
Definition at line 926 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
ref() [1/2]
TypeMemberFunctionImpl & SBTypeMemberFunction::ref () protected
Definition at line 1038 of file SBType.cpp.
References m_opaque_sp.
ref() [2/2]
const TypeMemberFunctionImpl & SBTypeMemberFunction::ref () const protected
Definition at line 1044 of file SBType.cpp.
References m_opaque_sp.
reset()
void SBTypeMemberFunction::reset (lldb_private::TypeMemberFunctionImpl * type_member_impl) protected
Definition at line 1034 of file SBType.cpp.
References m_opaque_sp.
Referenced by lldb::SBType::GetMemberFunctionAtIndex().
Friends And Related Symbol Documentation
SBType
friend class SBType friend
Definition at line 99 of file SBType.h.
References SBType.
Referenced by GetArgumentTypeAtIndex(), GetReturnType(), GetType(), and SBType.
Member Data Documentation
m_opaque_sp
lldb::TypeMemberFunctionImplSP lldb::SBTypeMemberFunction::m_opaque_sp protected
Definition at line 107 of file SBType.h.
Referenced by GetArgumentTypeAtIndex(), GetDemangledName(), GetDescription(), GetKind(), GetMangledName(), GetName(), GetNumberOfArguments(), GetReturnType(), GetType(), operator bool(), operator=(), ref(), ref(), reset(), and SBTypeMemberFunction().
The documentation for this class was generated from the following files:
SBType.h
SBType.cpp