LLDB: lldb::SBQueue Class Reference
lldb::SBQueue Class Reference
#include <SBQueue.h>
Public Member Functions
SBQueue ()
SBQueue (const SBQueue &rhs)
const SBQueue & operator= (const lldb::SBQueue &rhs)
~SBQueue ()
operator bool () const
bool IsValid () const
void Clear ()
lldb::SBProcess GetProcess ()
lldb::queue_id_t GetQueueID () const
const char * GetName () const
uint32_t GetIndexID () const
uint32_t GetNumThreads ()
lldb::SBThread GetThreadAtIndex (uint32_t)
uint32_t GetNumPendingItems ()
lldb::SBQueueItem GetPendingItemAtIndex (uint32_t)
uint32_t GetNumRunningItems ()
lldb::QueueKind GetKind ()
Protected Member Functions
SBQueue (const QueueSP &queue_sp)
void SetQueue (const lldb::QueueSP &queue_sp)
Private Attributes
std::shared_ptr< lldb_private::QueueImpl > m_opaque_sp
Friends
class SBProcess
class SBThread
Detailed Description
Definition at line 19 of file SBQueue.h.
Constructor & Destructor Documentation
SBQueue() [1/3]
SBQueue::SBQueue ()
Definition at line 213 of file SBQueue.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by SBQueue(), and SBThread.
SBQueue() [2/3]
SBQueue::SBQueue (const SBQueue & rhs)
Definition at line 220 of file SBQueue.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBQueue().
~SBQueue()
SBQueue::~SBQueue () default
References Clear(), GetIndexID(), GetNumPendingItems(), GetNumRunningItems(), GetNumThreads(), GetPendingItemAtIndex(), GetProcess(), GetQueueID(), GetThreadAtIndex(), and IsValid().
SBQueue() [3/3]
SBQueue::SBQueue (const QueueSP & queue_sp) protected
Definition at line 215 of file SBQueue.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Member Function Documentation
Clear()
void SBQueue::Clear ()
Definition at line 248 of file SBQueue.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBQueue().
GetIndexID()
uint32_t SBQueue::GetIndexID () const
Definition at line 264 of file SBQueue.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBQueue().
GetKind()
lldb::QueueKind SBQueue::GetKind ()
Definition at line 314 of file SBQueue.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetName()
const char * SBQueue::GetName () const
Definition at line 271 of file SBQueue.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetNumPendingItems()
uint32_t SBQueue::GetNumPendingItems ()
Definition at line 290 of file SBQueue.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBQueue().
GetNumRunningItems()
uint32_t SBQueue::GetNumRunningItems ()
Definition at line 302 of file SBQueue.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBQueue().
GetNumThreads()
uint32_t SBQueue::GetNumThreads ()
Definition at line 277 of file SBQueue.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBQueue().
GetPendingItemAtIndex()
SBQueueItem SBQueue::GetPendingItemAtIndex (uint32_t idx)
Definition at line 296 of file SBQueue.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBQueue().
GetProcess()
SBProcess SBQueue::GetProcess ()
Definition at line 308 of file SBQueue.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBProcess.
Referenced by ~SBQueue().
GetQueueID()
lldb::queue_id_t SBQueue::GetQueueID () const
Definition at line 258 of file SBQueue.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBQueue().
GetThreadAtIndex()
SBThread SBQueue::GetThreadAtIndex (uint32_t idx)
Definition at line 283 of file SBQueue.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBThread.
Referenced by ~SBQueue().
IsValid()
bool SBQueue::IsValid () const
Definition at line 238 of file SBQueue.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBQueue().
operator bool()
SBQueue::operator bool () const explicit
Definition at line 242 of file SBQueue.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator=()
const lldb::SBQueue & SBQueue::operator= (const lldb::SBQueue & rhs)
Definition at line 229 of file SBQueue.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
SetQueue()
void SBQueue::SetQueue (const lldb::QueueSP & queue_sp) protected
Definition at line 254 of file SBQueue.cpp.
References m_opaque_sp.
Referenced by lldb::SBThread::GetQueue(), lldb::SBProcess::GetQueueAtIndex(), and SBThread.
Friends And Related Symbol Documentation
SBProcess
friend class SBProcess friend
Definition at line 56 of file SBQueue.h.
References SBProcess.
Referenced by GetProcess(), and SBProcess.
SBThread
friend class SBThread friend
Definition at line 57 of file SBQueue.h.
References SBQueue(), SBThread, and SetQueue().
Referenced by GetThreadAtIndex(), and SBThread.
Member Data Documentation
m_opaque_sp
std::shared_ptr<lldb_private::QueueImpl> lldb::SBQueue::m_opaque_sp private
Definition at line 64 of file SBQueue.h.
Referenced by Clear(), GetIndexID(), GetKind(), GetName(), GetNumPendingItems(), GetNumRunningItems(), GetNumThreads(), GetPendingItemAtIndex(), GetProcess(), GetQueueID(), GetThreadAtIndex(), operator bool(), operator=(), SBQueue(), SBQueue(), SBQueue(), and SetQueue().
The documentation for this class was generated from the following files:
SBQueue.h
SBQueue.cpp