LLDB: lldb_private::BreakpointName Class Reference
lldb_private::BreakpointName Class Reference
#include <BreakpointName.h>
Classes
class Permissions
Public Member Functions
BreakpointName (ConstString name, const char *help=nullptr)
BreakpointName (const BreakpointName &rhs)
ConstString GetName () const
BreakpointOptions & GetOptions ()
const BreakpointOptions & GetOptions () const
void SetOptions (const BreakpointOptions &options)
Permissions & GetPermissions ()
const Permissions & GetPermissions () const
void SetPermissions (const Permissions &permissions)
bool GetPermission (Permissions::PermissionKinds permission) const
void SetHelp (const char *description)
const char * GetHelp ()
bool GetDescription (Stream *s, lldb::DescriptionLevel level)
void ConfigureBreakpoint (lldb::BreakpointSP bp_sp)
Private Attributes
ConstString m_name
BreakpointOptions m_options
Permissions m_permissions
std::string m_help
Detailed Description
Definition at line 30 of file BreakpointName.h.
Constructor & Destructor Documentation
BreakpointName() [1/2]
lldb_private::BreakpointName::BreakpointName (ConstString name, const char * help = nullptr) inline
Definition at line 140 of file BreakpointName.h.
References m_name, m_options, and SetHelp().
Referenced by BreakpointName().
BreakpointName() [2/2]
lldb_private::BreakpointName::BreakpointName (const BreakpointName & rhs) inline
Definition at line 146 of file BreakpointName.h.
References BreakpointName(), m_help, m_name, m_options, and m_permissions.
Member Function Documentation
ConfigureBreakpoint()
void BreakpointName::ConfigureBreakpoint (lldb::BreakpointSP bp_sp)
Definition at line 71 of file BreakpointName.cpp.
References GetOptions(), and GetPermissions().
Referenced by lldb_private::Target::AddNameToBreakpoint(), and lldb_private::Target::ApplyNameToBreakpoints().
GetDescription()
bool BreakpointName::GetDescription (Stream * s, lldb::DescriptionLevel level)
Definition at line 45 of file BreakpointName.cpp.
References lldb_private::BreakpointName::Permissions::GetDescription(), lldb_private::BreakpointOptions::GetDescription(), GetOptions(), GetPermissions(), lldb_private::Stream::Indent(), lldb_private::Stream::IndentLess(), lldb_private::Stream::IndentMore(), m_help, lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
Referenced by CommandObjectBreakpointNameList::DoExecute(), and lldb::SBBreakpointName::GetDescription().
GetHelp()
const char * lldb_private::BreakpointName::GetHelp () inline
Definition at line 178 of file BreakpointName.h.
References m_help.
Referenced by lldb::SBBreakpointName::GetHelpString().
GetName()
ConstString lldb_private::BreakpointName::GetName () const inline
Definition at line 151 of file BreakpointName.h.
References m_name.
Referenced by lldb_private::Target::ApplyNameToBreakpoints().
GetOptions() [1/2]
BreakpointOptions & lldb_private::BreakpointName::GetOptions () inline
Definition at line 152 of file BreakpointName.h.
References m_options.
Referenced by ConfigureBreakpoint(), lldb_private::Target::ConfigureBreakpointName(), lldb::SBBreakpointName::GetAutoContinue(), lldb::SBBreakpointName::GetCommandLineCommands(), lldb::SBBreakpointName::GetCondition(), GetDescription(), lldb::SBBreakpointName::GetIgnoreCount(), lldb::SBBreakpointName::GetQueueName(), lldb::SBBreakpointName::GetThreadID(), lldb::SBBreakpointName::GetThreadIndex(), lldb::SBBreakpointName::GetThreadName(), lldb::SBBreakpointName::IsEnabled(), lldb::SBBreakpointName::IsOneShot(), lldb::SBBreakpointName::SetAutoContinue(), lldb::SBBreakpointName::SetCallback(), lldb::SBBreakpointName::SetCommandLineCommands(), lldb::SBBreakpointName::SetCondition(), lldb::SBBreakpointName::SetEnabled(), lldb::SBBreakpointName::SetIgnoreCount(), lldb::SBBreakpointName::SetOneShot(), lldb::SBBreakpointName::SetQueueName(), lldb::SBBreakpointName::SetScriptCallbackBody(), lldb::SBBreakpointName::SetScriptCallbackFunction(), lldb::SBBreakpointName::SetThreadID(), lldb::SBBreakpointName::SetThreadIndex(), and lldb::SBBreakpointName::SetThreadName().
GetOptions() [2/2]
const BreakpointOptions & lldb_private::BreakpointName::GetOptions () const inline
Definition at line 153 of file BreakpointName.h.
References m_options.
GetPermission()
bool lldb_private::BreakpointName::GetPermission (Permissions::PermissionKinds permission) const inline
Definition at line 165 of file BreakpointName.h.
References m_permissions.
Referenced by lldb_private::BreakpointIDList::FindAndReplaceIDRanges().
GetPermissions() [1/2]
Permissions & lldb_private::BreakpointName::GetPermissions () inline
Definition at line 159 of file BreakpointName.h.
References m_permissions.
Referenced by ConfigureBreakpoint(), lldb_private::Target::ConfigureBreakpointName(), lldb::SBBreakpointName::GetAllowDelete(), lldb::SBBreakpointName::GetAllowDisable(), lldb::SBBreakpointName::GetAllowList(), GetDescription(), lldb::SBBreakpointName::SetAllowDelete(), lldb::SBBreakpointName::SetAllowDisable(), and lldb::SBBreakpointName::SetAllowList().
GetPermissions() [2/2]
const Permissions & lldb_private::BreakpointName::GetPermissions () const inline
Definition at line 160 of file BreakpointName.h.
References m_permissions.
SetHelp()
void lldb_private::BreakpointName::SetHelp (const char * description) inline
Definition at line 170 of file BreakpointName.h.
References m_help.
Referenced by BreakpointName(), CommandObjectBreakpointNameConfigure::DoExecute(), and lldb::SBBreakpointName::SetHelpString().
SetOptions()
void lldb_private::BreakpointName::SetOptions (const BreakpointOptions & options) inline
Definition at line 155 of file BreakpointName.h.
References m_options.
SetPermissions()
void lldb_private::BreakpointName::SetPermissions (const Permissions & permissions) inline
Definition at line 161 of file BreakpointName.h.
References m_permissions.
Member Data Documentation
m_help
std::string lldb_private::BreakpointName::m_help private
Definition at line 192 of file BreakpointName.h.
Referenced by BreakpointName(), GetDescription(), GetHelp(), and SetHelp().
m_name
ConstString lldb_private::BreakpointName::m_name private
Definition at line 189 of file BreakpointName.h.
Referenced by BreakpointName(), BreakpointName(), and GetName().
m_options
BreakpointOptions lldb_private::BreakpointName::m_options private
Definition at line 190 of file BreakpointName.h.
Referenced by BreakpointName(), BreakpointName(), GetOptions(), GetOptions(), and SetOptions().
m_permissions
Permissions lldb_private::BreakpointName::m_permissions private
Definition at line 191 of file BreakpointName.h.
Referenced by BreakpointName(), GetPermission(), GetPermissions(), GetPermissions(), and SetPermissions().
The documentation for this class was generated from the following files:
BreakpointName.h
BreakpointName.cpp