LLDB: lldb_private::Searcher Class Reference
lldb_private::Searcher Class Reference abstract
General Outline: Provides the callback and search depth for the SearchFilter search.
#include "lldb/Core/SearchFilter.h"
Public Types
enum CallbackReturn { eCallbackReturnStop = 0 , eCallbackReturnContinue , eCallbackReturnPop }
Public Member Functions
Searcher ()
virtual ~Searcher ()
virtual CallbackReturn SearchCallback (SearchFilter &filter, SymbolContext &context, Address *addr)=0
virtual lldb::SearchDepth GetDepth ()=0
virtual void GetDescription (Stream *s)
Prints a canonical description for the searcher to the stream s.
Detailed Description
General Outline: Provides the callback and search depth for the SearchFilter search.
Class that is driven by the SearchFilter to search the SymbolContext space of the target program.
Definition at line 42 of file SearchFilter.h.
Member Enumeration Documentation
CallbackReturn
enum lldb_private::Searcher::CallbackReturn
Enumerator
eCallbackReturnStop
eCallbackReturnContinue
eCallbackReturnPop
Definition at line 44 of file SearchFilter.h.
Constructor & Destructor Documentation
Searcher()
Searcher::Searcher () default
Referenced by lldb_private::FileLineResolver::FileLineResolver().
~Searcher()
Searcher::~Searcher () virtual default
Member Function Documentation
GetDepth()
virtual lldb::SearchDepth lldb_private::Searcher::GetDepth () pure virtual
Implemented in ExceptionBreakpointResolver, lldb_private::AddressResolverFileLine, lldb_private::BreakpointResolverAddress, lldb_private::BreakpointResolverFileLine, lldb_private::BreakpointResolverFileRegex, lldb_private::BreakpointResolverName, lldb_private::BreakpointResolverScripted, and lldb_private::FileLineResolver.
Referenced by lldb_private::SearchFilter::DoCUIteration(), lldb_private::SearchFilter::DoModuleIteration(), lldb_private::SearchFilter::Search(), lldb_private::SearchFilterByModule::Search(), lldb_private::SearchFilterByModuleList::Search(), lldb_private::SearchFilterByModuleListAndCU::Search(), and lldb_private::SearchFilter::SearchInModuleList().
GetDescription()
void Searcher::GetDescription (Stream * s) virtual
Prints a canonical description for the searcher to the stream s.
Parameters
[in] s Stream to which the output is copied.
Reimplemented in ExceptionBreakpointResolver, lldb_private::AddressResolver, lldb_private::AddressResolverFileLine, lldb_private::BreakpointResolver, lldb_private::BreakpointResolverAddress, lldb_private::BreakpointResolverFileLine, lldb_private::BreakpointResolverFileRegex, lldb_private::BreakpointResolverName, lldb_private::BreakpointResolverScripted, and lldb_private::FileLineResolver.
Definition at line 70 of file SearchFilter.cpp.
SearchCallback()
virtual CallbackReturn lldb_private::Searcher::SearchCallback (SearchFilter & filter, SymbolContext & context, Address * addr) pure virtual
Implemented in ExceptionBreakpointResolver, lldb_private::AddressResolverFileLine, lldb_private::BreakpointResolverAddress, lldb_private::BreakpointResolverFileLine, lldb_private::BreakpointResolverFileRegex, lldb_private::BreakpointResolverName, lldb_private::BreakpointResolverScripted, and lldb_private::FileLineResolver.
Referenced by lldb_private::SearchFilter::DoCUIteration(), lldb_private::SearchFilter::DoModuleIteration(), lldb_private::SearchFilter::Search(), lldb_private::SearchFilterByModule::Search(), lldb_private::SearchFilterByModuleList::Search(), lldb_private::SearchFilterByModuleListAndCU::Search(), and lldb_private::SearchFilter::SearchInModuleList().
The documentation for this class was generated from the following files:
SearchFilter.h
SearchFilter.cpp