LLDB: lldb_private::Properties Class Reference
lldb_private::Properties Class Reference
#include <UserSettingsController.h>
Public Member Functions
Properties ()
Properties (const lldb::OptionValuePropertiesSP &collection_sp)
virtual ~Properties ()
lldb::OptionValuePropertiesSP GetValueProperties () const
virtual lldb::OptionValueSP GetPropertyValue (const ExecutionContext *exe_ctx, llvm::StringRef property_path, Status &error) const
virtual Status SetPropertyValue (const ExecutionContext *exe_ctx, VarSetOperationType op, llvm::StringRef property_path, llvm::StringRef value)
virtual Status DumpPropertyValue (const ExecutionContext *exe_ctx, Stream &strm, llvm::StringRef property_path, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllPropertyValues (const ExecutionContext *exe_ctx, Stream &strm, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllDescriptions (CommandInterpreter &interpreter, Stream &strm) const
size_t Apropos (llvm::StringRef keyword, std::vector< const Property * > &matching_properties) const
template<typename T>
T GetPropertyAtIndexAs (uint32_t idx, T default_value, const ExecutionContext *exe_ctx=nullptr) const
template<typename T, typename U = typename std::remove_pointer<T>::type, std::enable_if_t< std::is_pointer_v< T >, bool > = true>
const U * GetPropertyAtIndexAs (uint32_t idx, const ExecutionContext *exe_ctx=nullptr) const
template<typename T>
bool SetPropertyAtIndex (uint32_t idx, T t, const ExecutionContext *exe_ctx=nullptr) const
Static Public Member Functions
static llvm::StringRef GetExperimentalSettingsName ()
static bool IsSettingExperimental (llvm::StringRef setting)
Protected Attributes
lldb::OptionValuePropertiesSP m_collection_sp
Detailed Description
Definition at line 33 of file UserSettingsController.h.
Constructor & Destructor Documentation
Properties() [1/2]
Properties::Properties () default
Referenced by lldb_private::CommandInterpreter::CommandInterpreter(), lldb_private::Debugger::Debugger(), DynamicLoaderDarwinKernelProperties::DynamicLoaderDarwinKernelProperties(), PlatformDarwinProperties::PlatformDarwinProperties(), lldb_private::trace_intel_pt::TraceIntelPT::PluginProperties::PluginProperties(), lldb_private::ProcessExperimentalProperties::ProcessExperimentalProperties(), lldb_private::ProcessProperties::ProcessProperties(), sddarwinlog_private::StructuredDataDarwinLogProperties::StructuredDataDarwinLogProperties(), lldb_private::TargetExperimentalProperties::TargetExperimentalProperties(), lldb_private::TargetProperties::TargetProperties(), and lldb_private::ThreadProperties::ThreadProperties().
Properties() [2/2]
Properties::Properties (const lldb::OptionValuePropertiesSP & collection_sp)
Definition at line 35 of file UserSettingsController.cpp.
References m_collection_sp.
~Properties()
Properties::~Properties () virtual default
Member Function Documentation
Apropos()
size_t Properties::Apropos (llvm::StringRef keyword, std::vector< const Property * > & matching_properties) const
Definition at line 79 of file UserSettingsController.cpp.
References m_collection_sp.
Referenced by lldb_private::CommandObjectApropos::DoExecute().
DumpAllDescriptions()
void Properties::DumpAllDescriptions (CommandInterpreter & interpreter, Stream & strm) const virtual
Definition at line 63 of file UserSettingsController.cpp.
References m_collection_sp, and lldb_private::Stream::PutCString().
Referenced by CommandObjectSettingsList::DoExecute().
DumpAllPropertyValues()
void Properties::DumpAllPropertyValues (const ExecutionContext * exe_ctx, Stream & strm, uint32_t dump_mask, bool is_json = false) virtual
Definition at line 53 of file UserSettingsController.cpp.
References m_collection_sp, and lldb_private::Stream::Printf().
Referenced by CommandObjectSettingsShow::DoExecute(), and CommandObjectSettingsWrite::DoExecute().
DumpPropertyValue()
Status Properties::DumpPropertyValue (const ExecutionContext * exe_ctx, Stream & strm, llvm::StringRef property_path, uint32_t dump_mask, bool is_json = false) virtual
Definition at line 70 of file UserSettingsController.cpp.
References m_collection_sp.
GetExperimentalSettingsName()
llvm::StringRef Properties::GetExperimentalSettingsName () static
Definition at line 85 of file UserSettingsController.cpp.
Referenced by lldb_private::OptionValueProperties::GetSubValue(), IsSettingExperimental(), lldb_private::ProcessProperties::ProcessProperties(), and lldb_private::TargetProperties::TargetProperties().
GetPropertyAtIndexAs() [1/2]
template<typename T, typename U = typename std::remove_pointer<T>::type, std::enable_if_t< std::is_pointer_v< T >, bool > = true> const U * lldb_private::Properties::GetPropertyAtIndexAs (uint32_t idx, const ExecutionContext * exe_ctx = nullptr) const inline
Definition at line 89 of file UserSettingsController.h.
References m_collection_sp.
GetPropertyAtIndexAs() [2/2]
template<typename T> T lldb_private::Properties::GetPropertyAtIndexAs (uint32_t idx, T default_value, const ExecutionContext * exe_ctx = nullptr) const inline
Definition at line 80 of file UserSettingsController.h.
References m_collection_sp.
Referenced by lldb_private::TargetProperties::ComputeEnvironment(), lldb_private::TargetProperties::GetArg0(), lldb_private::Debugger::GetAutoConfirm(), sddarwinlog_private::StructuredDataDarwinLogProperties::GetAutoEnableOptions(), lldb_private::Debugger::GetAutoIndent(), lldb_private::TargetProperties::GetAutoInstallMainExecutable(), lldb_private::Debugger::GetAutoOneLineSummaries(), lldb_private::TargetProperties::GetAutoSourceMapRelative(), lldb_private::Debugger::GetAutosuggestionAnsiPrefix(), lldb_private::Debugger::GetAutosuggestionAnsiSuffix(), lldb_private::TargetProperties::GetBreakpointsConsultPlatformAvoidList(), lldb_private::ModuleListProperties::GetClangModulesCachePath(), lldb_private::TargetProperties::GetClangModuleSearchPaths(), lldb_private::TargetProperties::GetDebugFileSearchPaths(), lldb_private::TargetProperties::GetDebugUtilityExpression(), lldb_private::TargetProperties::GetDefaultArchitecture(), lldb_private::ProcessProperties::GetDetachKeepsStopped(), lldb_private::TargetProperties::GetDetachOnError(), lldb_private::TargetProperties::GetDisableASLR(), lldb_private::Debugger::GetDisabledAnsiPrefix(), lldb_private::Debugger::GetDisabledAnsiSuffix(), lldb_private::ProcessProperties::GetDisableLangRuntimeUnwindPlans(), lldb_private::ProcessProperties::GetDisableMemoryCache(), lldb_private::TargetProperties::GetDisableSTDIO(), lldb_private::TargetProperties::GetDisassemblyCPU(), lldb_private::TargetProperties::GetDisassemblyFeatures(), lldb_private::TargetProperties::GetDisassemblyFlavor(), lldb_private::Debugger::GetDisassemblyFormat(), lldb_private::Debugger::GetDisassemblyLineCount(), lldb_private::TargetProperties::GetDisplayExpressionsInCrashlogs(), lldb_private::TargetProperties::GetDisplayRecognizedArguments(), lldb_private::TargetProperties::GetDisplayRuntimeSupportValues(), lldb_private::Debugger::GetDWIMPrintVerbosity(), lldb_private::TargetProperties::GetDynamicClassInfoHelper(), lldb_private::CommandInterpreter::GetEchoCommands(), lldb_private::CommandInterpreter::GetEchoCommentCommands(), lldb_private::TargetProperties::GetEnableAutoApplyFixIts(), lldb_private::TargetProperties::GetEnableAutoImportClangModules(), lldb_private::ModuleListProperties::GetEnableExternalLookup(), lldb_private::LanguageProperties::GetEnableFilterForLineBreakpoints(), lldb_private::ModuleListProperties::GetEnableLLDBIndexCache(), lldb_private::TargetProperties::GetEnableNotifyAboutFixIts(), sddarwinlog_private::StructuredDataDarwinLogProperties::GetEnableOnStartup(), lldb_private::TargetProperties::GetEnableSyntheticValue(), lldb_private::Debugger::GetEscapeNonPrintables(), lldb_private::TargetProperties::GetExecutableSearchPaths(), lldb_private::CommandInterpreter::GetExpandRegexAliases(), lldb_private::TargetProperties::GetExprAllocAddress(), lldb_private::TargetProperties::GetExprAllocAlign(), lldb_private::TargetProperties::GetExprAllocSize(), lldb_private::TargetProperties::GetExprErrorLimit(), lldb_private::Debugger::GetExternalEditor(), lldb_private::trace_intel_pt::TraceIntelPT::PluginProperties::GetExtremelyLargeDecodingThreshold(), lldb_private::ProcessProperties::GetFollowForkMode(), lldb_private::Debugger::GetFrameFormat(), lldb_private::Debugger::GetFrameFormatUnique(), lldb_private::TargetProperties::GetHexImmediateStyle(), lldb_private::Debugger::GetHighlightSource(), lldb_private::ProcessProperties::GetHighmemVirtualAddressableBits(), lldb_private::ProcessProperties::GetIgnoreBreakpointsInExpressions(), lldb_private::TargetProperties::GetImportStdModule(), lldb_private::trace_intel_pt::TraceIntelPT::PluginProperties::GetInfiniteDecodingLoopVerificationThreshold(), lldb_private::TargetProperties::GetInheritedEnvironment(), lldb_private::TargetProperties::GetInheritTCC(), lldb_private::TestingProperties::GetInjectVarLocListError(), lldb_private::TargetProperties::GetInlineStrategy(), lldb_private::ProcessProperties::GetInterruptTimeout(), lldb_private::TargetProperties::GetLanguage(), lldb_private::TargetProperties::GetLaunchWorkingDirectory(), lldb_private::ThreadProperties::GetLibrariesToAvoid(), lldb_private::ModuleListProperties::GetLLDBIndexCacheExpirationDays(), lldb_private::ModuleListProperties::GetLLDBIndexCacheMaxByteSize(), lldb_private::ModuleListProperties::GetLLDBIndexCacheMaxPercent(), lldb_private::ModuleListProperties::GetLLDBIndexCachePath(), lldb_private::TargetProperties::GetLoadCWDlldbinitFile(), DynamicLoaderDarwinKernelProperties::GetLoadKexts(), lldb_private::TargetProperties::GetLoadScriptFromSymbolFile(), lldb_private::ModuleListProperties::GetLoadSymbolOnDemand(), lldb_private::Debugger::GetMarkHiddenFrames(), lldb_private::ThreadProperties::GetMaxBacktraceDepth(), lldb_private::TargetProperties::GetMaximumMemReadSize(), lldb_private::TargetProperties::GetMaximumNumberOfChildrenToDisplay(), lldb_private::TargetProperties::GetMaximumSizeOfStringSummary(), lldb_private::TargetProperties::GetMaxZeroPaddingInFloatFormat(), lldb_private::ProcessProperties::GetMemoryCacheLineSize(), lldb_private::TargetProperties::GetMemoryModuleLoadLevel(), lldb_private::PlatformProperties::GetModuleCacheDirectory(), lldb_private::TargetProperties::GetMoveToNearestCode(), lldb_private::Debugger::GetNotifyVoid(), lldb_private::TargetProperties::GetNumberOfRetriesWithFixits(), lldb_private::CommandInterpreter::GetOpenTranscriptInEditor(), lldb_private::TargetProperties::GetParallelModuleLoad(), lldb_private::TargetProperties::GetPreferDynamicValue(), lldb_private::TargetProperties::GetPreloadSymbols(), lldb_private::Debugger::GetPrintDecls(), lldb_private::Debugger::GetPrompt(), lldb_private::Debugger::GetPromptAnsiPrefix(), lldb_private::Debugger::GetPromptAnsiSuffix(), lldb_private::CommandInterpreter::GetPromptOnQuit(), lldb_private::ProcessProperties::GetPythonOSPluginPath(), lldb_private::Debugger::GetRegexMatchAnsiPrefix(), lldb_private::Debugger::GetRegexMatchAnsiSuffix(), lldb_private::CommandInterpreter::GetRepeatPreviousCommand(), lldb_private::Debugger::GetREPLLanguage(), lldb_private::CommandInterpreter::GetRequireCommandOverwrite(), lldb_private::TargetProperties::GetRequireHardwareBreakpoints(), lldb_private::platform_android::PlatformAndroid::GetRunAs(), lldb_private::TargetProperties::GetSaveJITObjectsDir(), lldb_private::CommandInterpreter::GetSaveSessionDirectory(), lldb_private::CommandInterpreter::GetSaveSessionOnQuit(), lldb_private::CommandInterpreter::GetSaveTranscript(), DynamicLoaderDarwinKernelProperties::GetScanType(), lldb_private::Debugger::GetScriptLanguage(), lldb_private::Debugger::GetSeparator(), lldb_private::ModuleListProperties::GetSharedCacheBinaryLoading(), lldb_private::Debugger::GetShowDontUsePoHint(), lldb_private::Debugger::GetShowInlineDiagnostics(), lldb_private::Debugger::GetShowProgress(), lldb_private::Debugger::GetShowProgressAnsiPrefix(), lldb_private::Debugger::GetShowProgressAnsiSuffix(), lldb_private::Debugger::GetShowStatusline(), lldb_private::ThreadProperties::GetSingleThreadPlanTimeout(), lldb_private::TargetProperties::GetSkipPrologue(), lldb_private::TargetProperties::GetSourceRealpathPrefixes(), lldb_private::CommandInterpreter::GetSpaceReplPrompts(), lldb_private::TargetProperties::GetStandardErrorPath(), lldb_private::TargetProperties::GetStandardInputPath(), lldb_private::TargetProperties::GetStandardOutputPath(), lldb_private::Debugger::GetStatuslineFormat(), lldb_private::ThreadProperties::GetStepInAvoidsNoDebug(), lldb_private::ThreadProperties::GetStepOutAvoidsNoDebug(), lldb_private::ProcessProperties::GetSteppingRunsAllThreads(), lldb_private::CommandInterpreter::GetStopCmdSourceOnError(), lldb_private::Debugger::GetStopDisassemblyDisplay(), lldb_private::Debugger::GetStopDisassemblyMaxSize(), lldb_private::ProcessProperties::GetStopOnExec(), lldb_private::ProcessProperties::GetStopOnSharedLibraryEvents(), lldb_private::Debugger::GetStopShowColumn(), lldb_private::Debugger::GetStopShowColumnAnsiPrefix(), lldb_private::Debugger::GetStopShowColumnAnsiSuffix(), lldb_private::Debugger::GetStopShowLineMarkerAnsiPrefix(), lldb_private::Debugger::GetStopShowLineMarkerAnsiSuffix(), lldb_private::Debugger::GetStopSourceLineCount(), lldb_private::ModuleListProperties::GetSymbolAutoDownload(), lldb_private::ThreadProperties::GetSymbolsToAvoidRegexp(), lldb_private::Debugger::GetTabSize(), lldb_private::Debugger::GetTerminalHeight(), lldb_private::Debugger::GetTerminalWidth(), lldb_private::Debugger::GetThreadFormat(), lldb_private::Debugger::GetThreadStopFormat(), lldb_private::ThreadProperties::GetTraceEnabledState(), lldb_private::ProcessProperties::GetUnwindOnErrorInExpressions(), lldb_private::Debugger::GetUseAutosuggestion(), lldb_private::Debugger::GetUseColor(), lldb_private::Debugger::GetUseExternalEditor(), lldb_private::TargetProperties::GetUseFastStepping(), lldb_private::TargetProperties::GetUseHexImmediates(), lldb_private::PlatformProperties::GetUseModuleCache(), lldb_private::Debugger::GetUseSourceCache(), lldb_private::ProcessProperties::GetUtilityExpressionTimeout(), lldb_private::ProcessProperties::GetVirtualAddressableBits(), lldb_private::ProcessProperties::GetWarningsOptimization(), lldb_private::ProcessProperties::GetWarningsUnsupportedLanguage(), lldb_private::TargetProperties::ShowHexVariableValuesWithLeadingZeroes(), lldb_private::ProcessProperties::TrackMemoryCacheChanges(), and lldb_private::ModuleListProperties::UpdateSymlinkMappings().
GetPropertyValue()
lldb::OptionValueSP Properties::GetPropertyValue (const ExecutionContext * exe_ctx, llvm::StringRef property_path, Status & error) const virtual
Definition at line 41 of file UserSettingsController.cpp.
References error(), and m_collection_sp.
Referenced by sddarwinlog_private::ParseAutoEnableOptions().
GetValueProperties()
lldb::OptionValuePropertiesSP lldb_private::Properties::GetValueProperties () const inline
Definition at line 41 of file UserSettingsController.h.
References m_collection_sp.
Referenced by lldb_private::OptionValueProperties::CreateLocalCopy(), lldb_private::Debugger::Debugger(), lldb_private::process_gdb_remote::ProcessGDBRemote::DebuggerInitialize(), ProcessKDP::DebuggerInitialize(), CommandObjectSettingsClear::DoExecute(), CommandObjectSettingsList::DoExecute(), GetDebuggerPropertyForPlugins(), GetDebuggerPropertyForPluginsOldStyle(), ProcessOptionValueProperties::GetPropertyAtIndex(), TargetOptionValueProperties::GetPropertyAtIndex(), lldb_private::ProcessProperties::ProcessProperties(), lldb_private::CommandCompletions::SettingsNames(), and lldb_private::TargetProperties::TargetProperties().
IsSettingExperimental()
bool Properties::IsSettingExperimental (llvm::StringRef setting) static
Definition at line 90 of file UserSettingsController.cpp.
References GetExperimentalSettingsName().
Referenced by lldb_private::OptionValueProperties::GetSubValue(), and lldb_private::OptionValueProperties::SetSubValue().
SetPropertyAtIndex()
template<typename T> bool lldb_private::Properties::SetPropertyAtIndex (uint32_t idx, T t, const ExecutionContext * exe_ctx = nullptr) const inline
Definition at line 95 of file UserSettingsController.h.
References m_collection_sp.
Referenced by lldb_private::TargetProperties::SetArg0(), lldb_private::Debugger::SetAutoIndent(), lldb_private::ModuleListProperties::SetClangModulesCachePath(), lldb_private::TargetProperties::SetDebugUtilityExpression(), lldb_private::TargetProperties::SetDefaultArchitecture(), lldb_private::ProcessProperties::SetDetachKeepsStopped(), lldb_private::TargetProperties::SetDetachOnError(), lldb_private::TargetProperties::SetDisableASLR(), lldb_private::ProcessProperties::SetDisableLangRuntimeUnwindPlans(), lldb_private::TargetProperties::SetDisableSTDIO(), lldb_private::TargetProperties::SetDisplayRecognizedArguments(), lldb_private::TargetProperties::SetDisplayRuntimeSupportValues(), lldb_private::CommandInterpreter::SetEchoCommands(), lldb_private::CommandInterpreter::SetEchoCommentCommands(), lldb_private::ModuleListProperties::SetEnableExternalLookup(), lldb_private::ModuleListProperties::SetEnableLLDBIndexCache(), lldb_private::Debugger::SetExternalEditor(), lldb_private::ProcessProperties::SetHighmemVirtualAddressableBits(), lldb_private::ProcessProperties::SetIgnoreBreakpointsInExpressions(), lldb_private::TargetProperties::SetInheritTCC(), lldb_private::ModuleListProperties::SetLLDBIndexCachePath(), lldb_private::CommandInterpreter::SetOpenTranscriptInEditor(), lldb_private::TargetProperties::SetPreferDynamicValue(), lldb_private::TargetProperties::SetPreloadSymbols(), lldb_private::Debugger::SetPrintDecls(), lldb_private::Debugger::SetPrompt(), lldb_private::CommandInterpreter::SetPromptOnQuit(), lldb_private::ProcessProperties::SetPythonOSPluginPath(), lldb_private::Debugger::SetREPLLanguage(), lldb_private::CommandInterpreter::SetSaveSessionDirectory(), lldb_private::CommandInterpreter::SetSaveSessionOnQuit(), lldb_private::CommandInterpreter::SetSaveTranscript(), lldb_private::Debugger::SetScriptLanguage(), lldb_private::Debugger::SetSeparator(), lldb_private::Debugger::SetShowInlineDiagnostics(), lldb_private::Debugger::SetShowProgress(), lldb_private::TargetProperties::SetStandardErrorPath(), lldb_private::TargetProperties::SetStandardInputPath(), lldb_private::TargetProperties::SetStandardOutputPath(), lldb_private::Debugger::SetStatuslineFormat(), lldb_private::ProcessProperties::SetStopOnSharedLibraryEvents(), lldb_private::Debugger::SetTabSize(), lldb_private::Debugger::SetTerminalHeight(), lldb_private::Debugger::SetTerminalWidth(), lldb_private::ProcessProperties::SetUnwindOnErrorInExpressions(), lldb_private::Debugger::SetUseColor(), lldb_private::Debugger::SetUseExternalEditor(), lldb_private::PlatformProperties::SetUseModuleCache(), lldb_private::Debugger::SetUseSourceCache(), and lldb_private::ProcessProperties::SetVirtualAddressableBits().
SetPropertyValue()
Status Properties::SetPropertyValue (const ExecutionContext * exe_ctx, VarSetOperationType op, llvm::StringRef property_path, llvm::StringRef value) virtual
Reimplemented in lldb_private::Debugger.
Definition at line 46 of file UserSettingsController.cpp.
References m_collection_sp.
Referenced by lldb_private::Debugger::SetPropertyValue().
Member Data Documentation
m_collection_sp
lldb::OptionValuePropertiesSP lldb_private::Properties::m_collection_sp protected
Definition at line 101 of file UserSettingsController.h.
Referenced by lldb_private::TargetProperties::AppendExecutableSearchPaths(), Apropos(), lldb_private::TargetProperties::CheckJITObjectsDir(), lldb_private::CommandInterpreter::CommandInterpreter(), lldb_private::TargetProperties::ComputeEnvironment(), lldb_private::Debugger::Debugger(), DumpAllDescriptions(), DumpAllPropertyValues(), DumpPropertyValue(), DynamicLoaderDarwinKernelProperties::DynamicLoaderDarwinKernelProperties(), lldb_private::TargetProperties::GetExperimentalPropertyValue(), lldb_private::TargetProperties::GetExpressionPrefixContents(), lldb_private::ProcessProperties::GetExtraStartupCommands(), PlatformDarwinProperties::GetIgnoredExceptions(), PlatformDarwinProperties::GetIgnoredExceptionValue(), lldb_private::TargetProperties::GetInheritedEnvironment(), lldb_private::TargetProperties::GetMaximumDepthOfChildrenToDisplay(), lldb_private::TargetProperties::GetObjectPathMap(), lldb_private::ProcessProperties::GetOSPluginReportsAllThreads(), GetPropertyAtIndexAs(), GetPropertyAtIndexAs(), GetPropertyValue(), lldb_private::TargetProperties::GetRunArguments(), lldb_private::TargetProperties::GetSourcePathMap(), lldb_private::TargetProperties::GetTargetEnvironment(), lldb_private::TargetProperties::GetUseDIL(), lldb_private::TargetProperties::GetUserSpecifiedTrapHandlerNames(), GetValueProperties(), lldb_private::LanguageProperties::LanguageProperties(), lldb_private::ModuleListProperties::ModuleListProperties(), lldb_private::RemoteAwarePlatform::Platform(), PlatformDarwinProperties::PlatformDarwinProperties(), lldb_private::trace_intel_pt::TraceIntelPT::PluginProperties::PluginProperties(), lldb_private::Process::Process(), lldb_private::ProcessExperimentalProperties::ProcessExperimentalProperties(), lldb_private::ProcessProperties::ProcessProperties(), Properties(), lldb_private::PlatformProperties::SetDefaultModuleCacheDirectory(), lldb_private::TargetProperties::SetEnvironment(), lldb_private::ProcessProperties::SetExtraStartupCommands(), lldb_private::PlatformProperties::SetModuleCacheDirectory(), lldb_private::ProcessProperties::SetOSPluginReportsAllThreads(), SetPropertyAtIndex(), SetPropertyValue(), lldb_private::TargetProperties::SetRequireHardwareBreakpoints(), lldb_private::TargetProperties::SetRunArguments(), lldb_private::TargetProperties::SetUseDIL(), lldb_private::TargetProperties::SetUserSpecifiedTrapHandlerNames(), sddarwinlog_private::StructuredDataDarwinLogProperties::StructuredDataDarwinLogProperties(), lldb_private::TargetExperimentalProperties::TargetExperimentalProperties(), lldb_private::TargetProperties::TargetProperties(), lldb_private::TestingProperties::TestingProperties(), and lldb_private::ThreadProperties::ThreadProperties().
The documentation for this class was generated from the following files:
UserSettingsController.h
UserSettingsController.cpp