LLDB: lldb_private::ThreadSpec Class Reference
lldb_private::ThreadSpec Class Reference
#include <ThreadSpec.h>
Public Member Functions
ThreadSpec ()
ThreadSpec (Thread &thread)
StructuredData::ObjectSP SerializeToStructuredData ()
void SetIndex (uint32_t index)
void SetTID (lldb::tid_t tid)
void SetName (llvm::StringRef name)
void SetQueueName (llvm::StringRef queue_name)
uint32_t GetIndex () const
lldb::tid_t GetTID () const
const char * GetName () const
const char * GetQueueName () const
bool TIDMatches (lldb::tid_t thread_id) const
bool TIDMatches (Thread &thread) const
bool IndexMatches (uint32_t index) const
bool IndexMatches (Thread &thread) const
bool NameMatches (const char *name) const
bool NameMatches (Thread &thread) const
bool QueueNameMatches (const char *queue_name) const
bool QueueNameMatches (Thread &thread) const
bool ThreadPassesBasicTests (Thread &thread) const
bool HasSpecification () const
void GetDescription (Stream *s, lldb::DescriptionLevel level) const
Static Public Member Functions
static std::unique_ptr< ThreadSpec > CreateFromStructuredData (const StructuredData::Dictionary &data_dict, Status &error)
static const char * GetSerializationKey ()
Private Types
enum class OptionNames {
ThreadIndex = 0 , ThreadID , ThreadName , QueueName ,
LastOptionName
}
Static Private Member Functions
static const char * GetKey (OptionNames enum_value)
Private Attributes
uint32_t m_index = UINT32_MAX
lldb::tid_t m_tid = LLDB_INVALID_THREAD_ID
std::string m_name
std::string m_queue_name
Static Private Attributes
static const char * g_option_names [(size_t) OptionNames::LastOptionName]
Detailed Description
Definition at line 33 of file ThreadSpec.h.
Member Enumeration Documentation
OptionNames
enum class lldb_private::ThreadSpec::OptionNames strong private
Enumerator
ThreadIndex
ThreadID
ThreadName
QueueName
LastOptionName
Definition at line 112 of file ThreadSpec.h.
Constructor & Destructor Documentation
ThreadSpec() [1/2]
ThreadSpec::ThreadSpec ()
Definition at line 20 of file ThreadSpec.cpp.
References m_name, and m_queue_name.
Referenced by CreateFromStructuredData().
ThreadSpec() [2/2]
ThreadSpec::ThreadSpec (Thread & thread)
Definition at line 22 of file ThreadSpec.cpp.
References GetName(), GetQueueName(), m_index, m_name, m_queue_name, and m_tid.
Member Function Documentation
CreateFromStructuredData()
std::unique_ptr< ThreadSpec > ThreadSpec::CreateFromStructuredData (const StructuredData::Dictionary & data_dict, Status & error) static
Definition at line 26 of file ThreadSpec.cpp.
References error(), GetKey(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsInteger(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsString(), LLDB_INVALID_THREAD_ID, ThreadID, ThreadIndex, ThreadName, ThreadSpec(), and UINT32_MAX.
Referenced by lldb_private::BreakpointOptions::CreateFromStructuredData().
GetDescription()
void ThreadSpec::GetDescription (Stream * s, lldb::DescriptionLevel level) const
Definition at line 135 of file ThreadSpec.cpp.
References lldb::eDescriptionLevelBrief, GetIndex(), GetName(), GetQueueName(), GetTID(), HasSpecification(), LLDB_INVALID_THREAD_ID, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and UINT32_MAX.
Referenced by lldb_private::ScriptedFrameProviderDescriptor::Dump().
GetIndex()
uint32_t lldb_private::ThreadSpec::GetIndex () const inline
Definition at line 57 of file ThreadSpec.h.
References m_index.
Referenced by GetDescription(), lldb::SBBreakpoint::GetThreadIndex(), lldb::SBBreakpointName::GetThreadIndex(), and lldb_private::BreakpointLocation::GetThreadIndex().
GetKey()
const char * lldb_private::ThreadSpec::GetKey (OptionNames enum_value) inline static private
Definition at line 121 of file ThreadSpec.h.
References g_option_names.
Referenced by CreateFromStructuredData(), and SerializeToStructuredData().
GetName()
const char * ThreadSpec::GetName () const
Definition at line 72 of file ThreadSpec.cpp.
References m_name.
Referenced by GetDescription(), lldb::SBBreakpointName::GetThreadName(), lldb_private::BreakpointLocation::GetThreadName(), and ThreadSpec().
GetQueueName()
const char * ThreadSpec::GetQueueName () const
Definition at line 76 of file ThreadSpec.cpp.
References m_queue_name.
Referenced by GetDescription(), lldb::SBBreakpointName::GetQueueName(), lldb_private::BreakpointLocation::GetQueueName(), and ThreadSpec().
GetSerializationKey()
const char * lldb_private::ThreadSpec::GetSerializationKey () inline static
Definition at line 45 of file ThreadSpec.h.
Referenced by lldb_private::BreakpointOptions::CreateFromStructuredData(), and lldb_private::BreakpointOptions::SerializeToStructuredData().
GetTID()
lldb::tid_t lldb_private::ThreadSpec::GetTID () const inline
Definition at line 59 of file ThreadSpec.h.
References m_tid.
Referenced by lldb_private::BreakpointLocation::Dump(), GetDescription(), lldb::SBBreakpointName::GetThreadID(), and lldb_private::BreakpointLocation::GetThreadID().
HasSpecification()
bool ThreadSpec::HasSpecification () const
Definition at line 130 of file ThreadSpec.cpp.
References LLDB_INVALID_THREAD_ID, m_index, m_name, m_queue_name, m_tid, and UINT32_MAX.
Referenced by GetDescription(), and ThreadPassesBasicTests().
IndexMatches() [1/2]
bool ThreadSpec::IndexMatches (Thread & thread) const
Definition at line 88 of file ThreadSpec.cpp.
References IndexMatches(), m_index, and UINT32_MAX.
IndexMatches() [2/2]
bool lldb_private::ThreadSpec::IndexMatches (uint32_t index) const inline
Definition at line 74 of file ThreadSpec.h.
References m_index, and UINT32_MAX.
Referenced by IndexMatches(), and ThreadPassesBasicTests().
NameMatches() [1/2]
bool lldb_private::ThreadSpec::NameMatches (const char * name) const inline
Definition at line 83 of file ThreadSpec.h.
References m_name.
Referenced by NameMatches(), and ThreadPassesBasicTests().
NameMatches() [2/2]
bool ThreadSpec::NameMatches (Thread & thread) const
Definition at line 95 of file ThreadSpec.cpp.
References m_name, and NameMatches().
QueueNameMatches() [1/2]
bool lldb_private::ThreadSpec::QueueNameMatches (const char * queue_name) const inline
Definition at line 94 of file ThreadSpec.h.
References m_queue_name.
Referenced by QueueNameMatches(), and ThreadPassesBasicTests().
QueueNameMatches() [2/2]
bool ThreadSpec::QueueNameMatches (Thread & thread) const
Definition at line 103 of file ThreadSpec.cpp.
References m_queue_name, and QueueNameMatches().
SerializeToStructuredData()
StructuredData::ObjectSP ThreadSpec::SerializeToStructuredData ()
Definition at line 57 of file ThreadSpec.cpp.
References GetKey(), LLDB_INVALID_THREAD_ID, m_index, m_name, m_queue_name, m_tid, QueueName, ThreadID, ThreadIndex, ThreadName, and UINT32_MAX.
SetIndex()
void lldb_private::ThreadSpec::SetIndex (uint32_t index) inline
Definition at line 47 of file ThreadSpec.h.
References m_index.
Referenced by lldb::SBBreakpointName::SetThreadIndex(), and lldb_private::BreakpointLocation::SetThreadIndex().
SetName()
void lldb_private::ThreadSpec::SetName (llvm::StringRef name) inline
Definition at line 51 of file ThreadSpec.h.
References m_name.
Referenced by lldb::SBBreakpointName::SetThreadName(), and lldb_private::BreakpointLocation::SetThreadName().
SetQueueName()
void lldb_private::ThreadSpec::SetQueueName (llvm::StringRef queue_name) inline
Definition at line 53 of file ThreadSpec.h.
References m_queue_name.
Referenced by lldb::SBBreakpointName::SetQueueName(), and lldb_private::BreakpointLocation::SetQueueName().
SetTID()
void lldb_private::ThreadSpec::SetTID (lldb::tid_t tid) inline
Definition at line 49 of file ThreadSpec.h.
References m_tid.
Referenced by lldb_private::BreakpointOptions::SetThreadID(), and lldb_private::WatchpointOptions::SetThreadID().
ThreadPassesBasicTests()
bool ThreadSpec::ThreadPassesBasicTests (Thread & thread) const
Definition at line 111 of file ThreadSpec.cpp.
References HasSpecification(), IndexMatches(), NameMatches(), QueueNameMatches(), and TIDMatches().
Referenced by lldb_private::Thread::MatchesSpec().
TIDMatches() [1/2]
bool lldb_private::ThreadSpec::TIDMatches (lldb::tid_t thread_id) const inline
Definition at line 65 of file ThreadSpec.h.
References LLDB_INVALID_THREAD_ID, and m_tid.
Referenced by ThreadPassesBasicTests(), and TIDMatches().
TIDMatches() [2/2]
bool ThreadSpec::TIDMatches (Thread & thread) const
Definition at line 80 of file ThreadSpec.cpp.
References LLDB_INVALID_THREAD_ID, m_tid, and TIDMatches().
Member Data Documentation
g_option_names
const char * ThreadSpec::g_option_names static private
Initial value:
{"Index", "ID", "Name",
                                              "QueueName"}
Definition at line 119 of file ThreadSpec.h.
Referenced by GetKey().
m_index
uint32_t lldb_private::ThreadSpec::m_index = UINT32_MAX private
Definition at line 125 of file ThreadSpec.h.
Referenced by GetIndex(), HasSpecification(), IndexMatches(), IndexMatches(), SerializeToStructuredData(), SetIndex(), and ThreadSpec().
m_name
std::string lldb_private::ThreadSpec::m_name private
Definition at line 127 of file ThreadSpec.h.
Referenced by GetName(), HasSpecification(), NameMatches(), NameMatches(), SerializeToStructuredData(), SetName(), ThreadSpec(), and ThreadSpec().
m_queue_name
std::string lldb_private::ThreadSpec::m_queue_name private
Definition at line 128 of file ThreadSpec.h.
Referenced by GetQueueName(), HasSpecification(), QueueNameMatches(), QueueNameMatches(), SerializeToStructuredData(), SetQueueName(), ThreadSpec(), and ThreadSpec().
m_tid
lldb::tid_t lldb_private::ThreadSpec::m_tid = LLDB_INVALID_THREAD_ID private
Definition at line 126 of file ThreadSpec.h.
Referenced by GetTID(), HasSpecification(), SerializeToStructuredData(), SetTID(), ThreadSpec(), TIDMatches(), and TIDMatches().
The documentation for this class was generated from the following files:
ThreadSpec.h
ThreadSpec.cpp