LLDB: lldb_private::NativeProcessProtocol::Manager Class Reference
lldb_private::NativeProcessProtocol::Manager Class Reference abstract
#include <NativeProcessProtocol.h>
Public Member Functions
Manager (MainLoop &mainloop)
Manager (const Manager &)=delete
Manager & operator= (const Manager &)=delete
virtual ~Manager ()
virtual llvm::Expected< std::unique_ptr< NativeProcessProtocol > > Launch (ProcessLaunchInfo &launch_info, NativeDelegate &native_delegate)=0
Launch a process for debugging.
virtual llvm::Expected< std::unique_ptr< NativeProcessProtocol > > Attach (lldb::pid_t pid, NativeDelegate &native_delegate)=0
Attach to an existing process.
virtual Extension GetSupportedExtensions () const
Get the bitmask of extensions supported by this process plugin.
Protected Attributes
MainLoop & m_mainloop
Detailed Description
Definition at line 271 of file NativeProcessProtocol.h.
Constructor & Destructor Documentation
Manager() [1/2]
lldb_private::NativeProcessProtocol::Manager::Manager (MainLoop & mainloop) inline
Definition at line 273 of file NativeProcessProtocol.h.
References m_mainloop.
Referenced by Manager(), and operator=().
Manager() [2/2]
lldb_private::NativeProcessProtocol::Manager::Manager (const Manager &) delete
References Manager().
~Manager()
NativeProcessProtocol::Manager::~Manager () virtual default
Member Function Documentation
Attach()
virtual llvm::Expected< std::unique_ptr< NativeProcessProtocol > > lldb_private::NativeProcessProtocol::Manager::Attach (lldb::pid_t pid, NativeDelegate & native_delegate) pure virtual
Attach to an existing process.
Parameters
[in] pid pid of the process locatable
[in] native_delegate The delegate that will receive messages regarding the inferior. Must outlive the NativeProcessProtocol instance.
[in] mainloop The mainloop instance with which the process can register callbacks. Must outlive the NativeProcessProtocol instance.
Returns
A NativeProcessProtocol shared pointer if the operation succeeded or an error object if it failed.
Implemented in lldb_private::NativeProcessWindows::Manager, lldb_private::process_aix::NativeProcessAIX::Manager, lldb_private::process_freebsd::NativeProcessFreeBSD::Manager, lldb_private::process_linux::NativeProcessLinux::Manager, and lldb_private::process_netbsd::NativeProcessNetBSD::Manager.
GetSupportedExtensions()
virtual Extension lldb_private::NativeProcessProtocol::Manager::GetSupportedExtensions () const inline virtual
Get the bitmask of extensions supported by this process plugin.
Returns
A NativeProcessProtocol::Extension bitmask.
Reimplemented in lldb_private::process_freebsd::NativeProcessFreeBSD::Manager, lldb_private::process_linux::NativeProcessLinux::Manager, and lldb_private::process_netbsd::NativeProcessNetBSD::Manager.
Definition at line 326 of file NativeProcessProtocol.h.
Launch()
virtual llvm::Expected< std::unique_ptr< NativeProcessProtocol > > lldb_private::NativeProcessProtocol::Manager::Launch (ProcessLaunchInfo & launch_info, NativeDelegate & native_delegate) pure virtual
Launch a process for debugging.
Parameters
[in] launch_info Information required to launch the process.
[in] native_delegate The delegate that will receive messages regarding the inferior. Must outlive the NativeProcessProtocol instance.
[in] mainloop The mainloop instance with which the process can register callbacks. Must outlive the NativeProcessProtocol instance.
Returns
A NativeProcessProtocol shared pointer if the operation succeeded or an error object if it failed.
Implemented in lldb_private::NativeProcessWindows::Manager, lldb_private::process_aix::NativeProcessAIX::Manager, lldb_private::process_freebsd::NativeProcessFreeBSD::Manager, lldb_private::process_linux::NativeProcessLinux::Manager, and lldb_private::process_netbsd::NativeProcessNetBSD::Manager.
operator=()
Manager & lldb_private::NativeProcessProtocol::Manager::operator= (const Manager &) delete
References Manager().
Member Data Documentation
m_mainloop
MainLoop& lldb_private::NativeProcessProtocol::Manager::m_mainloop protected
Definition at line 329 of file NativeProcessProtocol.h.
Referenced by lldb_private::process_freebsd::NativeProcessFreeBSD::Manager::Attach(), lldb_private::process_netbsd::NativeProcessNetBSD::Manager::Attach(), lldb_private::process_freebsd::NativeProcessFreeBSD::Manager::Launch(), lldb_private::process_netbsd::NativeProcessNetBSD::Manager::Launch(), and Manager().
The documentation for this class was generated from the following files:
NativeProcessProtocol.h
NativeProcessProtocol.cpp