LLDB: lldb_private::ProcessDebugger Class Reference
lldb_private::ProcessDebugger Class Reference
#include <ProcessDebugger.h>
Public Member Functions
virtual ~ProcessDebugger ()
virtual void OnExitProcess (uint32_t exit_code)
virtual void OnDebuggerConnected (lldb::addr_t image_base)
virtual ExceptionResult OnDebugException (bool first_chance, const ExceptionRecord &record)
virtual void OnCreateThread (const HostThread &thread)
virtual void OnExitThread (lldb::tid_t thread_id, uint32_t exit_code)
virtual void OnLoadDll (const ModuleSpec &module_spec, lldb::addr_t module_addr)
virtual void OnUnloadDll (lldb::addr_t module_addr)
virtual void OnDebugString (const std::string &string)
virtual void OnDebuggerError (const Status &error, uint32_t type)
Protected Member Functions
Status DetachProcess ()
Status LaunchProcess (ProcessLaunchInfo &launch_info, DebugDelegateSP delegate)
Status AttachProcess (lldb::pid_t pid, const ProcessAttachInfo &attach_info, DebugDelegateSP delegate)
Status DestroyProcess (lldb::StateType process_state)
Status HaltProcess (bool &caused_stop)
Status GetMemoryRegionInfo (lldb::addr_t load_addr, MemoryRegionInfo &range_info)
Status ReadMemory (lldb::addr_t addr, void *buf, size_t size, size_t &bytes_read)
Status WriteMemory (lldb::addr_t addr, const void *buf, size_t size, size_t &bytes_written)
Status AllocateMemory (size_t size, uint32_t permissions, lldb::addr_t &addr)
Status DeallocateMemory (lldb::addr_t addr)
lldb::pid_t GetDebuggedProcessId () const
Status WaitForDebuggerConnection (DebuggerThreadSP debugger, HostProcess &process)
Protected Attributes
llvm::sys::Mutex m_mutex
std::unique_ptr< ProcessWindowsData > m_session_data
Detailed Description
Definition at line 48 of file ProcessDebugger.h.
Constructor & Destructor Documentation
~ProcessDebugger()
lldb_private::ProcessDebugger::~ProcessDebugger () virtual
Definition at line 66 of file ProcessDebugger.cpp.
Member Function Documentation
AllocateMemory()
Status lldb_private::ProcessDebugger::AllocateMemory (size_t size, uint32_t permissions, lldb::addr_t & addr) protected
Definition at line 335 of file ProcessDebugger.cpp.
References ConvertLldbToWinApiProtect(), lldb::eErrorTypeWin32, error(), lldb_private::Status::FromErrorString(), lldb_private::GetLog(), lldb_private::HostProcess::GetNativeProcess(), lldb_private::HostNativeProcessBase::GetSystemHandle(), LLDB_INVALID_ADDRESS, LLDB_LOG, m_mutex, m_session_data, lldb_private::Memory, and lldb_private::Status.
Referenced by lldb_private::NativeProcessWindows::AllocateMemory(), and lldb_private::ProcessWindows::DoAllocateMemory().
AttachProcess()
Status lldb_private::ProcessDebugger::AttachProcess (lldb::pid_t pid, const ProcessAttachInfo & attach_info, DebugDelegateSP delegate) protected
Definition at line 171 of file ProcessDebugger.cpp.
References error(), lldb_private::ProcessAttachInfo::GetContinueOnceAttached(), lldb_private::GetLog(), LLDB_LOG, m_session_data, lldb_private::Process, and WaitForDebuggerConnection().
Referenced by lldb_private::ProcessWindows::DoAttachToProcessWithID(), and lldb_private::NativeProcessWindows::NativeProcessWindows().
DeallocateMemory()
Status lldb_private::ProcessDebugger::DeallocateMemory (lldb::addr_t addr) protected
Definition at line 364 of file ProcessDebugger.cpp.
References lldb::eErrorTypeWin32, lldb_private::Status::FromErrorString(), lldb_private::GetLog(), lldb_private::HostProcess::GetNativeProcess(), lldb_private::HostNativeProcessBase::GetSystemHandle(), LLDB_LOG, m_mutex, m_session_data, lldb_private::Memory, and lldb_private::Status.
Referenced by lldb_private::NativeProcessWindows::DeallocateMemory(), and lldb_private::ProcessWindows::DoDeallocateMemory().
DestroyProcess()
Status lldb_private::ProcessDebugger::DestroyProcess (lldb::StateType process_state) protected
Definition at line 211 of file ProcessDebugger.cpp.
References error(), lldb::eStateDetached, lldb::eStateExited, GetDebuggedProcessId(), lldb_private::GetLog(), LLDB_LOG, m_mutex, m_session_data, lldb_private::Process, and lldb_private::Status.
Referenced by lldb_private::ProcessWindows::DoDestroy(), and lldb_private::NativeProcessWindows::Kill().
DetachProcess()
Status lldb_private::ProcessDebugger::DetachProcess () protected
Definition at line 74 of file ProcessDebugger.cpp.
References error(), lldb_private::GetLog(), LLDB_LOG, m_mutex, m_session_data, lldb_private::Process, and lldb_private::Status.
Referenced by lldb_private::NativeProcessWindows::Detach(), and lldb_private::ProcessWindows::DoDetach().
GetDebuggedProcessId()
lldb::pid_t lldb_private::ProcessDebugger::GetDebuggedProcessId () const protected
Definition at line 68 of file ProcessDebugger.cpp.
References LLDB_INVALID_PROCESS_ID, and m_session_data.
Referenced by DestroyProcess(), lldb_private::ProcessWindows::DoAttachToProcessWithID(), lldb_private::NativeProcessWindows::NativeProcessWindows(), lldb_private::NativeProcessWindows::NativeProcessWindows(), lldb_private::NativeProcessWindows::OnDebuggerConnected(), and lldb_private::NativeProcessWindows::Resume().
GetMemoryRegionInfo()
Status lldb_private::ProcessDebugger::GetMemoryRegionInfo (lldb::addr_t load_addr, MemoryRegionInfo & range_info) protected
Definition at line 389 of file ProcessDebugger.cpp.
References lldb_private::MemoryRegionInfo::Clear(), lldb::eErrorTypeWin32, lldb_private::MemoryRegionInfo::eNo, error(), lldb_private::MemoryRegionInfo::eYes, lldb_private::Status::FromErrorString(), lldb_private::MemoryRegionInfo::GetExecutable(), lldb_private::GetLog(), lldb_private::HostProcess::GetNativeProcess(), lldb_private::MemoryRegionInfo::GetRange(), lldb_private::MemoryRegionInfo::GetReadable(), lldb_private::HostNativeProcessBase::GetSystemHandle(), lldb_private::MemoryRegionInfo::GetWritable(), IsPageExecutable(), IsPageReadable(), IsPageWritable(), LLDB_INVALID_ADDRESS, LLDB_INVALID_PROCESS, LLDB_LOG, LLDB_LOGV, m_mutex, m_session_data, lldb_private::Memory, lldb_private::Range< B, S >::SetByteSize(), lldb_private::MemoryRegionInfo::SetExecutable(), lldb_private::MemoryRegionInfo::SetMapped(), lldb_private::Range< B, S >::SetRangeBase(), lldb_private::Range< B, S >::SetRangeEnd(), lldb_private::MemoryRegionInfo::SetReadable(), lldb_private::MemoryRegionInfo::SetWritable(), and lldb_private::Status.
Referenced by lldb_private::ProcessWindows::DoGetMemoryRegionInfo(), lldb_private::NativeProcessWindows::GetMemoryRegionInfo(), and ReadMemory().
HaltProcess()
Status lldb_private::ProcessDebugger::HaltProcess (bool & caused_stop) protected
Definition at line 247 of file ProcessDebugger.cpp.
References lldb::eErrorTypeWin32, error(), lldb_private::GetLog(), LLDB_LOG, m_mutex, m_session_data, lldb_private::Process, and lldb_private::Status.
Referenced by lldb_private::ProcessWindows::DoHalt(), and lldb_private::NativeProcessWindows::Halt().
LaunchProcess()
Status lldb_private::ProcessDebugger::LaunchProcess (ProcessLaunchInfo & launch_info, DebugDelegateSP delegate) protected
Definition at line 105 of file ProcessDebugger.cpp.
References error(), lldb_private::Status::Fail(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::ProcessInfo::GetExecutableFile(), lldb_private::ProcessLaunchInfo::GetFlags(), lldb_private::GetLog(), lldb_private::FileSpec::GetPath(), lldb_private::HostProcess::GetProcessId(), lldb_private::StreamString::GetString(), lldb_private::ProcessLaunchInfo::GetWorkingDirectory(), lldb_private::FileSystem::Instance(), LLDB_LOG, m_session_data, lldb_private::Stream::Printf(), lldb_private::Process, lldb_private::FileSystem::Resolve(), lldb_private::ProcessInfo::SetProcessID(), lldb_private::Flags::Test(), and WaitForDebuggerConnection().
Referenced by lldb_private::ProcessWindows::DoLaunch(), and lldb_private::NativeProcessWindows::NativeProcessWindows().
OnCreateThread()
void lldb_private::ProcessDebugger::OnCreateThread (const HostThread & thread) virtual
Reimplemented in lldb_private::NativeProcessWindows, and lldb_private::ProcessWindows.
Definition at line 530 of file ProcessDebugger.cpp.
OnDebugException()
ExceptionResult lldb_private::ProcessDebugger::OnDebugException (bool first_chance, const ExceptionRecord & record) virtual
Reimplemented in lldb_private::NativeProcessWindows, and lldb_private::ProcessWindows.
Definition at line 495 of file ProcessDebugger.cpp.
References BreakInDebugger, lldb_private::Exception, lldb_private::ExceptionRecord::GetExceptionAddress(), lldb_private::ExceptionRecord::GetExceptionCode(), lldb_private::GetLog(), LLDB_LOG, m_mutex, m_session_data, and SendToApplication.
Referenced by lldb_private::NativeProcessWindows::OnDebugException().
OnDebuggerConnected()
void lldb_private::ProcessDebugger::OnDebuggerConnected (lldb::addr_t image_base) virtual
Reimplemented in lldb_private::NativeProcessWindows, and lldb_private::ProcessWindows.
Definition at line 492 of file ProcessDebugger.cpp.
OnDebuggerError()
void lldb_private::ProcessDebugger::OnDebuggerError (const Status & error, uint32_t type) virtual
Reimplemented in lldb_private::ProcessWindows.
Definition at line 549 of file ProcessDebugger.cpp.
References error(), lldb_private::GetLog(), LLDB_LOG, m_mutex, m_session_data, and lldb_private::Process.
Referenced by OnExitProcess().
OnDebugString()
void lldb_private::ProcessDebugger::OnDebugString (const std::string & string) virtual
Reimplemented in lldb_private::ProcessWindows.
Definition at line 547 of file ProcessDebugger.cpp.
OnExitProcess()
void lldb_private::ProcessDebugger::OnExitProcess (uint32_t exit_code) virtual
Reimplemented in lldb_private::NativeProcessWindows, and lldb_private::ProcessWindows.
Definition at line 481 of file ProcessDebugger.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormatv(), m_session_data, and OnDebuggerError().
Referenced by lldb_private::NativeProcessWindows::OnExitProcess(), and lldb_private::ProcessWindows::OnExitProcess().
OnExitThread()
void lldb_private::ProcessDebugger::OnExitThread (lldb::tid_t thread_id, uint32_t exit_code) virtual
Reimplemented in lldb_private::NativeProcessWindows, and lldb_private::ProcessWindows.
Definition at line 534 of file ProcessDebugger.cpp.
OnLoadDll()
void lldb_private::ProcessDebugger::OnLoadDll (const ModuleSpec & module_spec, lldb::addr_t module_addr) virtual
Reimplemented in lldb_private::NativeProcessWindows, and lldb_private::ProcessWindows.
Definition at line 538 of file ProcessDebugger.cpp.
OnUnloadDll()
void lldb_private::ProcessDebugger::OnUnloadDll (lldb::addr_t module_addr) virtual
Reimplemented in lldb_private::NativeProcessWindows, and lldb_private::ProcessWindows.
Definition at line 543 of file ProcessDebugger.cpp.
ReadMemory()
Status lldb_private::ProcessDebugger::ReadMemory (lldb::addr_t addr, void * buf, size_t size, size_t & bytes_read) protected
Definition at line 262 of file ProcessDebugger.cpp.
References lldb::eErrorTypeWin32, error(), lldb_private::MemoryRegionInfo::eYes, lldb_private::Status::FromErrorString(), lldb_private::GetLog(), lldb_private::MemoryRegionInfo::GetMapped(), GetMemoryRegionInfo(), lldb_private::MemoryRegionInfo::GetRange(), lldb_private::Range< B, S >::GetRangeEnd(), LLDB_LOG, m_mutex, m_session_data, lldb_private::Memory, ReadProcessMemory(), and lldb_private::Status.
Referenced by lldb_private::ProcessWindows::DoReadMemory(), and lldb_private::NativeProcessWindows::ReadMemory().
WaitForDebuggerConnection()
Status lldb_private::ProcessDebugger::WaitForDebuggerConnection (DebuggerThreadSP debugger, HostProcess & process) protected
Definition at line 574 of file ProcessDebugger.cpp.
References lldb_private::Breakpoints, lldb::eErrorTypeWin32, lldb_private::GetLog(), LLDB_LOG, m_session_data, lldb_private::Process, and lldb_private::Status.
Referenced by AttachProcess(), and LaunchProcess().
WriteMemory()
Status lldb_private::ProcessDebugger::WriteMemory (lldb::addr_t addr, const void * buf, size_t size, size_t & bytes_written) protected
Definition at line 305 of file ProcessDebugger.cpp.
References lldb::eErrorTypeWin32, error(), lldb_private::Status::FromErrorString(), lldb_private::GetLog(), lldb_private::HostProcess::GetNativeProcess(), lldb_private::HostNativeProcessBase::GetSystemHandle(), LLDB_LOG, m_mutex, m_session_data, lldb_private::Memory, and lldb_private::Status.
Referenced by lldb_private::ProcessWindows::DoWriteMemory(), and lldb_private::NativeProcessWindows::WriteMemory().
Member Data Documentation
m_mutex
llvm::sys::Mutex lldb_private::ProcessDebugger::m_mutex protected
Definition at line 97 of file ProcessDebugger.h.
Referenced by AllocateMemory(), DeallocateMemory(), DestroyProcess(), DetachProcess(), lldb_private::ProcessWindows::DidAttach(), lldb_private::ProcessWindows::DoResume(), GetMemoryRegionInfo(), HaltProcess(), lldb_private::NativeProcessWindows::OnCreateThread(), lldb_private::ProcessWindows::OnCreateThread(), lldb_private::NativeProcessWindows::OnDebugException(), OnDebugException(), lldb_private::ProcessWindows::OnDebugException(), lldb_private::ProcessWindows::OnDebuggerConnected(), OnDebuggerError(), lldb_private::ProcessWindows::OnDebuggerError(), lldb_private::NativeProcessWindows::OnExitThread(), lldb_private::ProcessWindows::OnExitThread(), ReadMemory(), lldb_private::ProcessWindows::RefreshStateAfterStop(), lldb_private::NativeProcessWindows::Resume(), and WriteMemory().
m_session_data
std::unique_ptr<ProcessWindowsData> lldb_private::ProcessDebugger::m_session_data protected
Definition at line 98 of file ProcessDebugger.h.
Referenced by AllocateMemory(), AttachProcess(), DeallocateMemory(), DestroyProcess(), DetachProcess(), lldb_private::ProcessWindows::DidAttach(), lldb_private::ProcessWindows::DoDetach(), lldb_private::ProcessWindows::DoResume(), lldb_private::ProcessWindows::DoUpdateThreadList(), GetDebuggedProcessId(), GetMemoryRegionInfo(), HaltProcess(), LaunchProcess(), lldb_private::ProcessWindows::OnCreateThread(), OnDebugException(), lldb_private::ProcessWindows::OnDebugException(), lldb_private::NativeProcessWindows::OnDebuggerConnected(), lldb_private::ProcessWindows::OnDebuggerConnected(), OnDebuggerError(), lldb_private::ProcessWindows::OnDebuggerError(), OnExitProcess(), lldb_private::ProcessWindows::OnExitThread(), ReadMemory(), lldb_private::ProcessWindows::RefreshStateAfterStop(), lldb_private::NativeProcessWindows::Resume(), WaitForDebuggerConnection(), and WriteMemory().
The documentation for this class was generated from the following files:
ProcessDebugger.h
ProcessDebugger.cpp