LLDB: lldb_private::UnwindPlan Class Reference
lldb_private::UnwindPlan Class Reference
#include <UnwindPlan.h>
Classes
class Row
Public Member Functions
UnwindPlan (lldb::RegisterKind reg_kind)
UnwindPlan (const UnwindPlan &rhs)=default
UnwindPlan & operator= (const UnwindPlan &rhs)=default
UnwindPlan (UnwindPlan &&rhs)=default
UnwindPlan & operator= (UnwindPlan &&)=default
~UnwindPlan ()=default
void Dump (Stream &s, Thread *thread, lldb::addr_t base_addr) const
void AppendRow (Row row)
void InsertRow (Row row, bool replace_existing=false)
const UnwindPlan::Row * GetRowForFunctionOffset (std::optional< int64_t > offset) const
lldb::RegisterKind GetRegisterKind () const
void SetRegisterKind (lldb::RegisterKind kind)
void SetReturnAddressRegister (uint32_t regnum)
uint32_t GetReturnAddressRegister () const
uint32_t GetInitialCFARegister () const
void SetPlanValidAddressRanges (std::vector< AddressRange > ranges)
bool PlanValidAtAddress (Address addr) const
bool IsValidRowIndex (uint32_t idx) const
const UnwindPlan::Row * GetRowAtIndex (uint32_t idx) const
const UnwindPlan::Row * GetLastRow () const
lldb_private::ConstString GetSourceName () const
void SetSourceName (const char *)
lldb_private::LazyBool GetSourcedFromCompiler () const
void SetSourcedFromCompiler (lldb_private::LazyBool from_compiler)
lldb_private::LazyBool GetUnwindPlanValidAtAllInstructions () const
void SetUnwindPlanValidAtAllInstructions (lldb_private::LazyBool valid_at_all_insn)
lldb_private::LazyBool GetUnwindPlanForSignalTrap () const
void SetUnwindPlanForSignalTrap (lldb_private::LazyBool is_for_signal_trap)
int GetRowCount () const
void Clear ()
const RegisterInfo * GetRegisterInfo (Thread *thread, uint32_t reg_num) const
Private Attributes
std::vector< Row > m_row_list
std::vector< AddressRange > m_plan_valid_ranges
lldb::RegisterKind m_register_kind
uint32_t m_return_addr_register
lldb_private::ConstString m_source_name
lldb_private::LazyBool m_plan_is_sourced_from_compiler
lldb_private::LazyBool m_plan_is_valid_at_all_instruction_locations
lldb_private::LazyBool m_plan_is_for_signal_trap
Detailed Description
Definition at line 53 of file UnwindPlan.h.
Constructor & Destructor Documentation
UnwindPlan() [1/3]
lldb_private::UnwindPlan::UnwindPlan (lldb::RegisterKind reg_kind) inline
Definition at line 431 of file UnwindPlan.h.
References lldb_private::eLazyBoolCalculate, LLDB_INVALID_REGNUM, m_plan_is_for_signal_trap, m_plan_is_sourced_from_compiler, m_plan_is_valid_at_all_instruction_locations, m_register_kind, and m_return_addr_register.
Referenced by lldb_private::UnwindPlan::Row::AbstractRegisterLocation::Dump(), lldb_private::UnwindPlan::Row::Dump(), lldb_private::UnwindPlan::Row::FAValue::Dump(), operator=(), operator=(), UnwindPlan(), and UnwindPlan().
UnwindPlan() [2/3]
lldb_private::UnwindPlan::UnwindPlan (const UnwindPlan & rhs) default
References UnwindPlan().
UnwindPlan() [3/3]
lldb_private::UnwindPlan::UnwindPlan (UnwindPlan && rhs) default
References UnwindPlan().
~UnwindPlan()
lldb_private::UnwindPlan::~UnwindPlan () default
Member Function Documentation
AppendRow()
void UnwindPlan::AppendRow (Row row)
Definition at line 395 of file UnwindPlan.cpp.
References lldb_private::UnwindPlan::Row::GetOffset(), and m_row_list.
Referenced by lldb_private::x86AssemblyInspectionEngine::AugmentUnwindPlanFromCallSite(), EmulateInstructionARM64::CreateFunctionEntryUnwind(), EmulateInstructionMIPS64::CreateFunctionEntryUnwind(), EmulateInstructionMIPS::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionARM::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionPPC64::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionRISCV::CreateFunctionEntryUnwind(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_arm64(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_armv7(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_i386(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_x86_64(), lldb_private::x86AssemblyInspectionEngine::GetNonCallSiteUnwindPlanFromAssembly(), and lldb_private::ArmUnwindInfo::GetUnwindPlan().
Clear()
void lldb_private::UnwindPlan::Clear () inline
Definition at line 531 of file UnwindPlan.h.
References lldb_private::eLazyBoolCalculate, lldb::eRegisterKindDWARF, m_plan_is_for_signal_trap, m_plan_is_sourced_from_compiler, m_plan_is_valid_at_all_instruction_locations, m_plan_valid_ranges, m_register_kind, m_row_list, and m_source_name.
Referenced by EmulateInstructionARM64::CreateFunctionEntryUnwind(), EmulateInstructionMIPS64::CreateFunctionEntryUnwind(), EmulateInstructionMIPS::CreateFunctionEntryUnwind(), lldb_private::EmulateInstruction::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionARM::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionPPC64::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionRISCV::CreateFunctionEntryUnwind(), and lldb_private::x86AssemblyInspectionEngine::GetNonCallSiteUnwindPlanFromAssembly().
Dump()
void UnwindPlan::Dump (Stream & s, Thread * thread, lldb::addr_t base_addr) const
Definition at line 511 of file UnwindPlan.cpp.
References lldb_private::Address::DumpStyleSectionNameOffset, lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb_private::Stream::EOL(), lldb_private::Stream::Format(), m_plan_is_for_signal_trap, m_plan_is_sourced_from_compiler, m_plan_is_valid_at_all_instruction_locations, m_plan_valid_ranges, m_row_list, m_source_name, lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
Referenced by DumpUnwindRowsToLog().
GetInitialCFARegister()
uint32_t lldb_private::UnwindPlan::GetInitialCFARegister () const inline
Definition at line 470 of file UnwindPlan.h.
References LLDB_INVALID_REGNUM, and m_row_list.
Referenced by UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly().
GetLastRow()
const UnwindPlan::Row * UnwindPlan::GetLastRow () const
Definition at line 447 of file UnwindPlan.cpp.
References lldb_private::GetLog(), LLDB_LOG, m_row_list, and lldb_private::Unwind.
Referenced by lldb_private::x86AssemblyInspectionEngine::AugmentUnwindPlanFromCallSite(), UnwindAssembly_x86::AugmentUnwindPlanFromCallSite(), and UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly().
GetRegisterInfo()
const RegisterInfo * UnwindPlan::GetRegisterInfo (Thread * thread, uint32_t reg_num) const
Definition at line 572 of file UnwindPlan.cpp.
References lldb_private::RegisterContext::ConvertRegisterKindToRegisterNumber(), lldb::eRegisterKindLLDB, lldb_private::RegisterContext::GetRegisterInfoAtIndex(), LLDB_INVALID_REGNUM, and m_register_kind.
Referenced by lldb_private::UnwindPlan::Row::AbstractRegisterLocation::Dump(), and DumpRegisterName().
GetRegisterKind()
lldb::RegisterKind lldb_private::UnwindPlan::GetRegisterKind () const inline
Definition at line 460 of file UnwindPlan.h.
References m_register_kind.
Referenced by lldb_private::x86AssemblyInspectionEngine::AugmentUnwindPlanFromCallSite(), UnwindAssembly_x86::AugmentUnwindPlanFromCallSite(), and UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly().
GetReturnAddressRegister()
uint32_t lldb_private::UnwindPlan::GetReturnAddressRegister () const inline
Definition at line 468 of file UnwindPlan.h.
References m_return_addr_register.
GetRowAtIndex()
const UnwindPlan::Row * UnwindPlan::GetRowAtIndex (uint32_t idx) const
Definition at line 437 of file UnwindPlan.cpp.
References lldb_private::GetLog(), LLDB_LOG, m_row_list, and lldb_private::Unwind.
Referenced by lldb_private::x86AssemblyInspectionEngine::AugmentUnwindPlanFromCallSite(), and PlanValidAtAddress().
GetRowCount()
int lldb_private::UnwindPlan::GetRowCount () const inline
Definition at line 529 of file UnwindPlan.h.
References m_row_list.
Referenced by lldb_private::x86AssemblyInspectionEngine::AugmentUnwindPlanFromCallSite(), UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly(), and PlanValidAtAddress().
GetRowForFunctionOffset()
const UnwindPlan::Row * UnwindPlan::GetRowForFunctionOffset (std::optional< int64_t > offset) const
Definition at line 423 of file UnwindPlan.cpp.
References m_row_list.
Referenced by UnwindAssembly_x86::AugmentUnwindPlanFromCallSite().
GetSourcedFromCompiler()
lldb_private::LazyBool lldb_private::UnwindPlan::GetSourcedFromCompiler () const inline
Definition at line 496 of file UnwindPlan.h.
References m_plan_is_sourced_from_compiler.
GetSourceName()
ConstString UnwindPlan::GetSourceName () const
Definition at line 570 of file UnwindPlan.cpp.
References m_source_name.
Referenced by lldb_private::x86AssemblyInspectionEngine::AugmentUnwindPlanFromCallSite().
GetUnwindPlanForSignalTrap()
lldb_private::LazyBool lldb_private::UnwindPlan::GetUnwindPlanForSignalTrap () const inline
Definition at line 521 of file UnwindPlan.h.
References m_plan_is_for_signal_trap.
GetUnwindPlanValidAtAllInstructions()
lldb_private::LazyBool lldb_private::UnwindPlan::GetUnwindPlanValidAtAllInstructions () const inline
Definition at line 507 of file UnwindPlan.h.
References m_plan_is_valid_at_all_instruction_locations.
InsertRow()
void UnwindPlan::InsertRow (Row row, bool replace_existing = false)
Definition at line 411 of file UnwindPlan.cpp.
References lldb_private::UnwindPlan::Row::GetOffset(), and m_row_list.
Referenced by lldb_private::x86AssemblyInspectionEngine::AugmentUnwindPlanFromCallSite(), and UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly().
IsValidRowIndex()
bool UnwindPlan::IsValidRowIndex (uint32_t idx) const
Definition at line 433 of file UnwindPlan.cpp.
References m_row_list.
operator=() [1/2]
UnwindPlan & lldb_private::UnwindPlan::operator= (const UnwindPlan & rhs) default
References UnwindPlan().
operator=() [2/2]
UnwindPlan & lldb_private::UnwindPlan::operator= (UnwindPlan &&) default
References UnwindPlan().
PlanValidAtAddress()
bool UnwindPlan::PlanValidAtAddress (Address addr) const
Definition at line 456 of file UnwindPlan.cpp.
References lldb_private::AddressRange::ContainsFileAddress(), lldb_private::Address::Dump(), lldb_private::Address::DumpStyleSectionNameOffset, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::StreamString::GetData(), lldb_private::GetLog(), GetRowAtIndex(), GetRowCount(), lldb_private::UnwindPlan::Row::FAValue::GetValueType(), lldb_private::Address::IsValid(), LLDB_LOGF, m_plan_valid_ranges, m_source_name, lldb_private::UnwindPlan::Row::FAValue::unspecified, and lldb_private::Unwind.
SetPlanValidAddressRanges()
void lldb_private::UnwindPlan::SetPlanValidAddressRanges (std::vector< AddressRange > ranges) inline
Definition at line 479 of file UnwindPlan.h.
References m_plan_valid_ranges.
Referenced by lldb_private::x86AssemblyInspectionEngine::AugmentUnwindPlanFromCallSite(), lldb_private::x86AssemblyInspectionEngine::GetNonCallSiteUnwindPlanFromAssembly(), and lldb_private::CompactUnwindInfo::GetUnwindPlan().
SetRegisterKind()
void lldb_private::UnwindPlan::SetRegisterKind (lldb::RegisterKind kind) inline
Definition at line 462 of file UnwindPlan.h.
References m_register_kind.
Referenced by EmulateInstructionARM64::CreateFunctionEntryUnwind(), EmulateInstructionMIPS64::CreateFunctionEntryUnwind(), EmulateInstructionMIPS::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionARM::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionPPC64::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionRISCV::CreateFunctionEntryUnwind(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_arm64(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_armv7(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_i386(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_x86_64(), lldb_private::x86AssemblyInspectionEngine::GetNonCallSiteUnwindPlanFromAssembly(), and lldb_private::ArmUnwindInfo::GetUnwindPlan().
SetReturnAddressRegister()
void lldb_private::UnwindPlan::SetReturnAddressRegister (uint32_t regnum) inline
Definition at line 464 of file UnwindPlan.h.
References m_return_addr_register.
Referenced by EmulateInstructionARM64::CreateFunctionEntryUnwind(), EmulateInstructionMIPS64::CreateFunctionEntryUnwind(), EmulateInstructionMIPS::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionARM::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionPPC64::CreateFunctionEntryUnwind(), and lldb_private::EmulateInstructionRISCV::CreateFunctionEntryUnwind().
SetSourcedFromCompiler()
void lldb_private::UnwindPlan::SetSourcedFromCompiler (lldb_private::LazyBool from_compiler) inline
Definition at line 501 of file UnwindPlan.h.
References m_plan_is_sourced_from_compiler.
Referenced by lldb_private::x86AssemblyInspectionEngine::AugmentUnwindPlanFromCallSite(), EmulateInstructionARM64::CreateFunctionEntryUnwind(), EmulateInstructionMIPS64::CreateFunctionEntryUnwind(), EmulateInstructionMIPS::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionARM::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionPPC64::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionRISCV::CreateFunctionEntryUnwind(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_arm64(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_armv7(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_i386(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_x86_64(), lldb_private::x86AssemblyInspectionEngine::GetNonCallSiteUnwindPlanFromAssembly(), and lldb_private::ArmUnwindInfo::GetUnwindPlan().
SetSourceName()
void UnwindPlan::SetSourceName (const char * source)
Definition at line 566 of file UnwindPlan.cpp.
References m_source_name.
Referenced by lldb_private::x86AssemblyInspectionEngine::AugmentUnwindPlanFromCallSite(), EmulateInstructionARM64::CreateFunctionEntryUnwind(), EmulateInstructionMIPS64::CreateFunctionEntryUnwind(), EmulateInstructionMIPS::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionARM::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionPPC64::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionRISCV::CreateFunctionEntryUnwind(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_arm64(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_armv7(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_i386(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_x86_64(), lldb_private::x86AssemblyInspectionEngine::GetNonCallSiteUnwindPlanFromAssembly(), and lldb_private::ArmUnwindInfo::GetUnwindPlan().
SetUnwindPlanForSignalTrap()
void lldb_private::UnwindPlan::SetUnwindPlanForSignalTrap (lldb_private::LazyBool is_for_signal_trap) inline
Definition at line 525 of file UnwindPlan.h.
References m_plan_is_for_signal_trap.
Referenced by EmulateInstructionARM64::CreateFunctionEntryUnwind(), EmulateInstructionMIPS64::CreateFunctionEntryUnwind(), EmulateInstructionMIPS::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionARM::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionPPC64::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionRISCV::CreateFunctionEntryUnwind(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_arm64(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_armv7(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_i386(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_x86_64(), lldb_private::x86AssemblyInspectionEngine::GetNonCallSiteUnwindPlanFromAssembly(), and lldb_private::ArmUnwindInfo::GetUnwindPlan().
SetUnwindPlanValidAtAllInstructions()
void lldb_private::UnwindPlan::SetUnwindPlanValidAtAllInstructions (lldb_private::LazyBool valid_at_all_insn) inline
Definition at line 513 of file UnwindPlan.h.
References m_plan_is_valid_at_all_instruction_locations.
Referenced by lldb_private::x86AssemblyInspectionEngine::AugmentUnwindPlanFromCallSite(), EmulateInstructionARM64::CreateFunctionEntryUnwind(), EmulateInstructionMIPS64::CreateFunctionEntryUnwind(), EmulateInstructionMIPS::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionARM::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionPPC64::CreateFunctionEntryUnwind(), lldb_private::EmulateInstructionRISCV::CreateFunctionEntryUnwind(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_arm64(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_armv7(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_i386(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_x86_64(), lldb_private::x86AssemblyInspectionEngine::GetNonCallSiteUnwindPlanFromAssembly(), and lldb_private::ArmUnwindInfo::GetUnwindPlan().
Member Data Documentation
m_plan_is_for_signal_trap
lldb_private::LazyBool lldb_private::UnwindPlan::m_plan_is_for_signal_trap private
Definition at line 556 of file UnwindPlan.h.
Referenced by Clear(), Dump(), GetUnwindPlanForSignalTrap(), SetUnwindPlanForSignalTrap(), and UnwindPlan().
m_plan_is_sourced_from_compiler
lldb_private::LazyBool lldb_private::UnwindPlan::m_plan_is_sourced_from_compiler private
Definition at line 554 of file UnwindPlan.h.
Referenced by Clear(), Dump(), GetSourcedFromCompiler(), SetSourcedFromCompiler(), and UnwindPlan().
m_plan_is_valid_at_all_instruction_locations
lldb_private::LazyBool lldb_private::UnwindPlan::m_plan_is_valid_at_all_instruction_locations private
Definition at line 555 of file UnwindPlan.h.
Referenced by Clear(), Dump(), GetUnwindPlanValidAtAllInstructions(), SetUnwindPlanValidAtAllInstructions(), and UnwindPlan().
m_plan_valid_ranges
std::vector<AddressRange> lldb_private::UnwindPlan::m_plan_valid_ranges private
Definition at line 545 of file UnwindPlan.h.
Referenced by Clear(), Dump(), PlanValidAtAddress(), and SetPlanValidAddressRanges().
m_register_kind
lldb::RegisterKind lldb_private::UnwindPlan::m_register_kind private
Definition at line 546 of file UnwindPlan.h.
Referenced by Clear(), GetRegisterInfo(), GetRegisterKind(), SetRegisterKind(), and UnwindPlan().
m_return_addr_register
uint32_t lldb_private::UnwindPlan::m_return_addr_register private
Definition at line 549 of file UnwindPlan.h.
Referenced by GetReturnAddressRegister(), SetReturnAddressRegister(), and UnwindPlan().
m_row_list
std::vector<Row> lldb_private::UnwindPlan::m_row_list private
Definition at line 544 of file UnwindPlan.h.
Referenced by AppendRow(), Clear(), Dump(), GetInitialCFARegister(), GetLastRow(), GetRowAtIndex(), GetRowCount(), GetRowForFunctionOffset(), InsertRow(), and IsValidRowIndex().
m_source_name
lldb_private::ConstString lldb_private::UnwindPlan::m_source_name private
Definition at line 553 of file UnwindPlan.h.
Referenced by Clear(), Dump(), GetSourceName(), PlanValidAtAddress(), and SetSourceName().
The documentation for this class was generated from the following files:
UnwindPlan.h
UnwindPlan.cpp