LLDB: lldb::SBAddress Class Reference
lldb::SBAddress Class Reference
#include <SBAddress.h>
Public Member Functions
SBAddress ()
SBAddress (const lldb::SBAddress &rhs)
SBAddress (lldb::SBSection section, lldb::addr_t offset)
SBAddress (lldb::addr_t load_addr, lldb::SBTarget &target)
~SBAddress ()
const lldb::SBAddress & operator= (const lldb::SBAddress &rhs)
operator bool () const
bool operator!= (const SBAddress &rhs) const
bool IsValid () const
void Clear ()
addr_t GetFileAddress () const
addr_t GetLoadAddress (const lldb::SBTarget &target) const
void SetAddress (lldb::SBSection section, lldb::addr_t offset)
void SetLoadAddress (lldb::addr_t load_addr, lldb::SBTarget &target)
bool OffsetAddress (addr_t offset)
bool GetDescription (lldb::SBStream &description)
lldb::SBSymbolContext GetSymbolContext (uint32_t resolve_scope)
lldb::SBSection GetSection ()
lldb::addr_t GetOffset ()
lldb::SBModule GetModule ()
lldb::SBCompileUnit GetCompileUnit ()
lldb::SBFunction GetFunction ()
lldb::SBBlock GetBlock ()
lldb::SBSymbol GetSymbol ()
lldb::SBLineEntry GetLineEntry ()
Protected Member Functions
lldb_private::Address * operator-> ()
const lldb_private::Address * operator-> () const
lldb_private::Address * get ()
lldb_private::Address & ref ()
const lldb_private::Address & ref () const
SBAddress (const lldb_private::Address &address)
void SetAddress (const lldb_private::Address &address)
Private Attributes
std::unique_ptr< lldb_private::Address > m_opaque_up
Friends
class SBAddressRange
class SBBlock
class SBBreakpoint
class SBBreakpointLocation
class SBFrame
class SBFunction
class SBLineEntry
class SBInstruction
class SBModule
class SBSection
class SBSymbol
class SBSymbolContext
class SBTarget
class SBThread
class SBThreadPlan
class SBValue
class SBQueueItem
bool LLDB_API operator== (const SBAddress &lhs, const SBAddress &rhs)
Detailed Description
Definition at line 17 of file SBAddress.h.
Constructor & Destructor Documentation
SBAddress() [1/5]
SBAddress::SBAddress ()
Definition at line 24 of file SBAddress.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by operator!=(), operator=(), operator==, SBAddress(), and ~SBAddress().
SBAddress() [2/5]
SBAddress::SBAddress (const lldb::SBAddress & rhs)
Definition at line 31 of file SBAddress.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBAddress().
SBAddress() [3/5]
SBAddress::SBAddress (lldb::SBSection section, lldb::addr_t offset)
Definition at line 37 of file SBAddress.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
SBAddress() [4/5]
SBAddress::SBAddress (lldb::addr_t load_addr, lldb::SBTarget & target)
Definition at line 43 of file SBAddress.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and SetLoadAddress().
~SBAddress()
SBAddress::~SBAddress () default
References Clear(), GetBlock(), GetCompileUnit(), GetDescription(), GetFileAddress(), GetFunction(), GetLineEntry(), GetLoadAddress(), GetModule(), GetOffset(), GetSection(), GetSymbol(), GetSymbolContext(), IsValid(), OffsetAddress(), operator!=(), operator=(), SBAddress(), SetAddress(), and SetLoadAddress().
SBAddress() [5/5]
SBAddress::SBAddress (const lldb_private::Address & address) protected
Definition at line 28 of file SBAddress.cpp.
References m_opaque_up.
Member Function Documentation
Clear()
void SBAddress::Clear ()
Definition at line 82 of file SBAddress.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBAddress().
get()
Address * SBAddress::get () protected
Definition at line 186 of file SBAddress.cpp.
References m_opaque_up.
Referenced by lldb::SBBreakpoint::AddLocation(), lldb::SBTarget::GetInstructionsWithFlavor(), operator==, lldb::SBThreadPlan::QueueThreadPlanForRunToAddress(), lldb::SBThreadPlan::QueueThreadPlanForStepInRange(), lldb::SBThreadPlan::QueueThreadPlanForStepOverRange(), and lldb::SBTarget::ReadInstructions().
GetBlock()
SBBlock SBAddress::GetBlock ()
Definition at line 240 of file SBAddress.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, SBBlock, and lldb::SBBlock::SetPtr().
Referenced by ~SBAddress().
GetCompileUnit()
SBCompileUnit SBAddress::GetCompileUnit ()
Definition at line 222 of file SBAddress.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBCompileUnit::reset().
Referenced by ~SBAddress().
GetDescription()
bool SBAddress::GetDescription (lldb::SBStream & description)
Definition at line 188 of file SBAddress.cpp.
References lldb_private::Address::DumpStyleModuleWithFileAddress, lldb_private::Address::DumpStyleResolvedDescription, LLDB_INSTRUMENT_VA, m_opaque_up, lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
Referenced by ~SBAddress().
GetFileAddress()
lldb::addr_t SBAddress::GetFileAddress () const
Definition at line 98 of file SBAddress.cpp.
References LLDB_INSTRUMENT_VA, LLDB_INVALID_ADDRESS, and m_opaque_up.
Referenced by ~SBAddress().
GetFunction()
SBFunction SBAddress::GetFunction ()
Definition at line 231 of file SBAddress.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, lldb::SBFunction::reset(), and SBFunction.
Referenced by ~SBAddress().
GetLineEntry()
SBLineEntry SBAddress::GetLineEntry ()
Definition at line 258 of file SBAddress.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, SBLineEntry, and lldb::SBLineEntry::SetLineEntry().
Referenced by ~SBAddress().
GetLoadAddress()
lldb::addr_t SBAddress::GetLoadAddress (const lldb::SBTarget & target) const
Definition at line 107 of file SBAddress.cpp.
References lldb::SBTarget::GetSP(), LLDB_INSTRUMENT_VA, LLDB_INVALID_ADDRESS, m_opaque_up, and SBTarget.
Referenced by lldb::SBTarget::CreateValueFromAddress(), lldb::SBTarget::ReadInstructions(), and ~SBAddress().
GetModule()
SBModule SBAddress::GetModule ()
Definition at line 203 of file SBAddress.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, SBModule, and lldb::SBModule::SetSP().
Referenced by ~SBAddress().
GetOffset()
lldb::addr_t SBAddress::GetOffset ()
Definition at line 161 of file SBAddress.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBAddress().
GetSection()
lldb::SBSection SBAddress::GetSection ()
Definition at line 152 of file SBAddress.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBSection::SetSP().
Referenced by ~SBAddress().
GetSymbol()
SBSymbol SBAddress::GetSymbol ()
Definition at line 249 of file SBAddress.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, lldb::SBSymbol::reset(), and SBSymbol.
Referenced by ~SBAddress().
GetSymbolContext()
SBSymbolContext SBAddress::GetSymbolContext (uint32_t resolve_scope)
Definition at line 212 of file SBAddress.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, lldb::SBSymbolContext::ref(), and SBSymbolContext.
Referenced by ~SBAddress().
IsValid()
bool SBAddress::IsValid () const
Definition at line 72 of file SBAddress.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBBreakpoint::AddLocation(), lldb::SBTarget::BreakpointCreateBySBAddress(), lldb::SBTarget::CreateValueFromAddress(), lldb::SBSymbolContext::GetParentOfInlinedScope(), lldb::SBBlock::GetRangeIndexForBlockAddress(), lldb::operator==(), lldb::SBModule::ResolveSymbolContextForAddress(), lldb::SBTarget::ResolveSymbolContextForAddress(), and ~SBAddress().
OffsetAddress()
bool SBAddress::OffsetAddress (addr_t offset)
Definition at line 139 of file SBAddress.cpp.
References LLDB_INSTRUMENT_VA, LLDB_INVALID_ADDRESS, and m_opaque_up.
Referenced by lldb::SBLineEntry::GetEndAddress(), lldb::SBLineEntry::GetSameLineContiguousAddressRangeEnd(), and ~SBAddress().
operator bool()
SBAddress::operator bool () const explicit
Definition at line 76 of file SBAddress.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
operator!=()
bool SBAddress::operator!= (const SBAddress & rhs) const
Definition at line 66 of file SBAddress.cpp.
References LLDB_INSTRUMENT_VA, and SBAddress().
Referenced by ~SBAddress().
operator->() [1/2]
Address * SBAddress::operator-> () protected
Definition at line 169 of file SBAddress.cpp.
References m_opaque_up.
Referenced by SBQueueItem.
operator->() [2/2]
const Address * SBAddress::operator-> () const protected
Definition at line 171 of file SBAddress.cpp.
References m_opaque_up.
operator=()
const SBAddress & SBAddress::operator= (const lldb::SBAddress & rhs)
Definition at line 52 of file SBAddress.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBAddress().
Referenced by ~SBAddress().
ref() [1/2]
Address & SBAddress::ref () protected
Definition at line 173 of file SBAddress.cpp.
References m_opaque_up.
Referenced by lldb::SBBreakpoint::AddLocation(), lldb::SBTarget::BreakpointCreateBySBAddress(), lldb::SBModule::GetObjectFileEntryPointAddress(), lldb::SBModule::GetObjectFileHeaderAddress(), lldb::SBSymbolContext::GetParentOfInlinedScope(), lldb::SBBlock::GetRangeEndAddress(), lldb::SBBlock::GetRangeIndexForBlockAddress(), lldb::SBBlock::GetRangeStartAddress(), lldb::operator==(), operator==, lldb::SBTarget::ReadMemory(), lldb::SBModule::ResolveFileAddress(), lldb::SBTarget::ResolveFileAddress(), lldb::SBTarget::ResolveLoadAddress(), lldb::SBTarget::ResolvePastLoadAddress(), lldb::SBModule::ResolveSymbolContextForAddress(), lldb::SBTarget::ResolveSymbolContextForAddress(), SetAddress(), SetAddress(), lldb::SBQueueItem::SetAddress(), and SetLoadAddress().
ref() [2/2]
const Address & SBAddress::ref () const protected
Definition at line 179 of file SBAddress.cpp.
References m_opaque_up.
SetAddress() [1/2]
void SBAddress::SetAddress (const lldb_private::Address & address) protected
Definition at line 96 of file SBAddress.cpp.
References ref().
SetAddress() [2/2]
void SBAddress::SetAddress (lldb::SBSection section, lldb::addr_t offset)
Definition at line 88 of file SBAddress.cpp.
References lldb::SBSection::GetSP(), LLDB_INSTRUMENT_VA, ref(), lldb_private::Address::SetOffset(), and lldb_private::Address::SetSection().
Referenced by lldb::SBInstruction::GetAddress(), lldb::SBQueueItem::GetAddress(), lldb::SBLineEntry::GetEndAddress(), lldb::SBSymbol::GetEndAddress(), lldb::SBLineEntry::GetSameLineContiguousAddressRangeEnd(), lldb::SBFunction::GetStartAddress(), lldb::SBLineEntry::GetStartAddress(), lldb::SBSymbol::GetStartAddress(), operator==, and ~SBAddress().
SetLoadAddress()
void SBAddress::SetLoadAddress (lldb::addr_t load_addr, lldb::SBTarget & target)
Definition at line 122 of file SBAddress.cpp.
References lldb::SBTarget::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_up, ref(), and lldb::SBTarget::ResolveLoadAddress().
Referenced by SBAddress(), and ~SBAddress().
Friends And Related Symbol Documentation
operator==
bool LLDB_API operator== (const SBAddress & lhs, const SBAddress & rhs) friend
References get(), LLDB_API, ref(), SBAddress(), and SetAddress().
SBAddressRange
friend class SBAddressRange friend
Definition at line 89 of file SBAddress.h.
References SBAddressRange.
Referenced by SBAddressRange.
SBBlock
friend class SBBlock friend
Definition at line 90 of file SBAddress.h.
References SBBlock.
Referenced by GetBlock(), and SBBlock.
SBBreakpoint
friend class SBBreakpoint friend
Definition at line 91 of file SBAddress.h.
References SBBreakpoint.
Referenced by SBBreakpoint.
SBBreakpointLocation
friend class SBBreakpointLocation friend
Definition at line 92 of file SBAddress.h.
References SBBreakpointLocation.
Referenced by SBBreakpointLocation.
SBFrame
friend class SBFrame friend
Definition at line 93 of file SBAddress.h.
References SBFrame.
Referenced by SBFrame.
SBFunction
friend class SBFunction friend
Definition at line 94 of file SBAddress.h.
References SBFunction.
Referenced by GetFunction(), and SBFunction.
SBInstruction
friend class SBInstruction friend
Definition at line 96 of file SBAddress.h.
References SBInstruction.
Referenced by SBInstruction.
SBLineEntry
friend class SBLineEntry friend
Definition at line 95 of file SBAddress.h.
References SBLineEntry.
Referenced by GetLineEntry(), and SBLineEntry.
SBModule
friend class SBModule friend
Definition at line 97 of file SBAddress.h.
References SBModule.
Referenced by GetModule(), and SBModule.
SBQueueItem
friend class SBQueueItem friend
Definition at line 105 of file SBAddress.h.
References operator->(), and SBQueueItem.
Referenced by SBQueueItem.
SBSection
friend class SBSection friend
Definition at line 98 of file SBAddress.h.
References SBSection.
Referenced by SBSection.
SBSymbol
friend class SBSymbol friend
Definition at line 99 of file SBAddress.h.
References SBSymbol.
Referenced by GetSymbol(), and SBSymbol.
SBSymbolContext
friend class SBSymbolContext friend
Definition at line 100 of file SBAddress.h.
References SBSymbolContext.
Referenced by GetSymbolContext(), and SBSymbolContext.
SBTarget
friend class SBTarget friend
Definition at line 101 of file SBAddress.h.
References SBTarget.
Referenced by GetLoadAddress(), and SBTarget.
SBThread
friend class SBThread friend
Definition at line 102 of file SBAddress.h.
References SBThread.
Referenced by SBThread.
SBThreadPlan
friend class SBThreadPlan friend
Definition at line 103 of file SBAddress.h.
References SBThreadPlan.
Referenced by SBThreadPlan.
SBValue
friend class SBValue friend
Definition at line 104 of file SBAddress.h.
References SBValue.
Referenced by SBValue.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::Address> lldb::SBAddress::m_opaque_up private
Definition at line 126 of file SBAddress.h.
Referenced by Clear(), get(), GetBlock(), GetCompileUnit(), GetDescription(), GetFileAddress(), GetFunction(), GetLineEntry(), GetLoadAddress(), GetModule(), GetOffset(), GetSection(), GetSymbol(), GetSymbolContext(), OffsetAddress(), operator bool(), operator->(), operator->(), operator=(), ref(), ref(), SBAddress(), SBAddress(), SBAddress(), SBAddress(), SBAddress(), and SetLoadAddress().
The documentation for this class was generated from the following files:
SBAddress.h
SBAddress.cpp