LLDB: lldb_private::DiagnosticEventData Class Reference
lldb_private::DiagnosticEventData Class Reference
#include <DebuggerEvents.h>
Public Member Functions
DiagnosticEventData (lldb::Severity severity, std::string message, bool debugger_specific)
~DiagnosticEventData () override=default
const std::string & GetMessage () const
bool IsDebuggerSpecific () const
lldb::Severity GetSeverity () const
llvm::StringRef GetPrefix () const
void Dump (Stream *s) const override
llvm::StringRef GetFlavor () const override
Public Member Functions inherited from lldb_private::EventData
EventData ()
virtual ~EventData ()
virtual Log * GetLogChannel ()
Static Public Member Functions
static llvm::StringRef GetFlavorString ()
static const DiagnosticEventData * GetEventDataFromEvent (const Event *event_ptr)
static StructuredData::DictionarySP GetAsStructuredData (const Event *event_ptr)
Protected Member Functions
DiagnosticEventData (const DiagnosticEventData &)=delete
const DiagnosticEventData & operator= (const DiagnosticEventData &)=delete
Protected Attributes
std::string m_message
lldb::Severity m_severity
const bool m_debugger_specific
Detailed Description
Definition at line 77 of file DebuggerEvents.h.
Constructor & Destructor Documentation
DiagnosticEventData() [1/2]
lldb_private::DiagnosticEventData::DiagnosticEventData (lldb::Severity severity, std::string message, bool debugger_specific) inline
Definition at line 79 of file DebuggerEvents.h.
References m_debugger_specific, m_message, and m_severity.
Referenced by DiagnosticEventData(), GetAsStructuredData(), and operator=().
~DiagnosticEventData()
lldb_private::DiagnosticEventData::~DiagnosticEventData () override default
DiagnosticEventData() [2/2]
lldb_private::DiagnosticEventData::DiagnosticEventData (const DiagnosticEventData &) protected delete
References DiagnosticEventData().
Member Function Documentation
Dump()
void DiagnosticEventData::Dump (Stream * s) const override virtual
Reimplemented from lldb_private::EventData.
Definition at line 87 of file DebuggerEvents.cpp.
References lldb_private::Stream::AsRawOstream(), lldb::eSeverityWarning, lldb_private::Stream::Flush(), GetMessage(), GetPrefix(), and m_severity.
Referenced by PrivateReportDiagnostic().
GetAsStructuredData()
StructuredData::DictionarySP DiagnosticEventData::GetAsStructuredData (const Event * event_ptr) static
Definition at line 111 of file DebuggerEvents.cpp.
References DiagnosticEventData(), lldb_private::EventData::Event, GetEventDataFromEvent(), GetMessage(), GetPrefix(), and IsDebuggerSpecific().
Referenced by lldb::SBDebugger::GetDiagnosticFromEvent().
GetEventDataFromEvent()
const DiagnosticEventData * DiagnosticEventData::GetEventDataFromEvent (const Event * event_ptr) static
Definition at line 106 of file DebuggerEvents.cpp.
References lldb_private::EventData::Event, and GetEventDataFromEventImpl().
Referenced by GetAsStructuredData(), and lldb_private::Debugger::HandleDiagnosticEvent().
GetFlavor()
llvm::StringRef DiagnosticEventData::GetFlavor () const override virtual
Implements lldb_private::EventData.
Definition at line 101 of file DebuggerEvents.cpp.
References GetFlavorString().
GetFlavorString()
llvm::StringRef DiagnosticEventData::GetFlavorString () static
Definition at line 97 of file DebuggerEvents.cpp.
Referenced by GetFlavor().
GetMessage()
const std::string & lldb_private::DiagnosticEventData::GetMessage () const inline
Definition at line 85 of file DebuggerEvents.h.
References m_message.
Referenced by Dump(), and GetAsStructuredData().
GetPrefix()
llvm::StringRef DiagnosticEventData::GetPrefix () const
Definition at line 75 of file DebuggerEvents.cpp.
References lldb::eSeverityError, lldb::eSeverityInfo, lldb::eSeverityWarning, and m_severity.
Referenced by Dump(), and GetAsStructuredData().
GetSeverity()
lldb::Severity lldb_private::DiagnosticEventData::GetSeverity () const inline
Definition at line 87 of file DebuggerEvents.h.
References m_severity.
IsDebuggerSpecific()
bool lldb_private::DiagnosticEventData::IsDebuggerSpecific () const inline
Definition at line 86 of file DebuggerEvents.h.
References m_debugger_specific.
Referenced by GetAsStructuredData().
operator=()
const DiagnosticEventData & lldb_private::DiagnosticEventData::operator= (const DiagnosticEventData &) protected delete
References DiagnosticEventData().
Member Data Documentation
m_debugger_specific
const bool lldb_private::DiagnosticEventData::m_debugger_specific protected
Definition at line 105 of file DebuggerEvents.h.
Referenced by DiagnosticEventData(), and IsDebuggerSpecific().
m_message
std::string lldb_private::DiagnosticEventData::m_message protected
Definition at line 103 of file DebuggerEvents.h.
Referenced by DiagnosticEventData(), and GetMessage().
m_severity
lldb::Severity lldb_private::DiagnosticEventData::m_severity protected
Definition at line 104 of file DebuggerEvents.h.
Referenced by DiagnosticEventData(), Dump(), GetPrefix(), and GetSeverity().
The documentation for this class was generated from the following files:
DebuggerEvents.h
DebuggerEvents.cpp