LLDB: lldb::SBTypeFilter Class Reference
lldb::SBTypeFilter Class Reference
#include <SBTypeFilter.h>
Public Member Functions
SBTypeFilter ()
SBTypeFilter (uint32_t options)
SBTypeFilter (const lldb::SBTypeFilter &rhs)
~SBTypeFilter ()
operator bool () const
bool IsValid () const
uint32_t GetNumberOfExpressionPaths ()
const char * GetExpressionPathAtIndex (uint32_t i)
bool ReplaceExpressionPathAtIndex (uint32_t i, const char *item)
void AppendExpressionPath (const char *item)
void Clear ()
uint32_t GetOptions ()
void SetOptions (uint32_t)
bool GetDescription (lldb::SBStream &description, lldb::DescriptionLevel description_level)
lldb::SBTypeFilter & operator= (const lldb::SBTypeFilter &rhs)
bool IsEqualTo (lldb::SBTypeFilter &rhs)
bool operator== (lldb::SBTypeFilter &rhs)
bool operator!= (lldb::SBTypeFilter &rhs)
Protected Member Functions
lldb::TypeFilterImplSP GetSP ()
void SetSP (const lldb::TypeFilterImplSP &typefilter_impl_sp)
SBTypeFilter (const lldb::TypeFilterImplSP &)
bool CopyOnWrite_Impl ()
Protected Attributes
lldb::TypeFilterImplSP m_opaque_sp
Friends
class SBDebugger
class SBTypeCategory
class SBValue
Detailed Description
Definition at line 17 of file SBTypeFilter.h.
Constructor & Destructor Documentation
SBTypeFilter() [1/4]
SBTypeFilter::SBTypeFilter ()
Definition at line 19 of file SBTypeFilter.cpp.
References LLDB_INSTRUMENT_VA.
SBTypeFilter() [2/4]
SBTypeFilter::SBTypeFilter (uint32_t options)
Definition at line 21 of file SBTypeFilter.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
SBTypeFilter() [3/4]
SBTypeFilter::SBTypeFilter (const lldb::SBTypeFilter & rhs)
Definition at line 26 of file SBTypeFilter.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
~SBTypeFilter()
SBTypeFilter::~SBTypeFilter () default
References AppendExpressionPath(), Clear(), GetDescription(), GetExpressionPathAtIndex(), GetNumberOfExpressionPaths(), GetOptions(), IsEqualTo(), IsValid(), operator!=(), operator=(), operator==(), ReplaceExpressionPathAtIndex(), and SetOptions().
SBTypeFilter() [4/4]
SBTypeFilter::SBTypeFilter (const lldb::TypeFilterImplSP & typefilter_impl_sp) protected
Definition at line 163 of file SBTypeFilter.cpp.
References m_opaque_sp.
Member Function Documentation
AppendExpressionPath()
void SBTypeFilter::AppendExpressionPath (const char * item)
Definition at line 106 of file SBTypeFilter.cpp.
References CopyOnWrite_Impl(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeFilter().
Clear()
void SBTypeFilter::Clear ()
Definition at line 70 of file SBTypeFilter.cpp.
References CopyOnWrite_Impl(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeFilter().
CopyOnWrite_Impl()
bool SBTypeFilter::CopyOnWrite_Impl () protected
Definition at line 166 of file SBTypeFilter.cpp.
References GetExpressionPathAtIndex(), GetNumberOfExpressionPaths(), GetOptions(), IsValid(), m_opaque_sp, and SetSP().
Referenced by AppendExpressionPath(), Clear(), ReplaceExpressionPathAtIndex(), and SetOptions().
GetDescription()
bool SBTypeFilter::GetDescription (lldb::SBStream & description, lldb::DescriptionLevel description_level)
Definition at line 58 of file SBTypeFilter.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeFilter().
GetExpressionPathAtIndex()
const char * SBTypeFilter::GetExpressionPathAtIndex (uint32_t i)
Definition at line 85 of file SBTypeFilter.cpp.
References lldb_private::ConstString::GetCString(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by CopyOnWrite_Impl(), IsEqualTo(), and ~SBTypeFilter().
GetNumberOfExpressionPaths()
uint32_t SBTypeFilter::GetNumberOfExpressionPaths ()
Definition at line 77 of file SBTypeFilter.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by CopyOnWrite_Impl(), IsEqualTo(), and ~SBTypeFilter().
GetOptions()
uint32_t SBTypeFilter::GetOptions ()
Definition at line 43 of file SBTypeFilter.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by CopyOnWrite_Impl(), IsEqualTo(), and ~SBTypeFilter().
GetSP()
lldb::TypeFilterImplSP SBTypeFilter::GetSP () protected
Definition at line 157 of file SBTypeFilter.cpp.
References m_opaque_sp.
Referenced by lldb::SBTypeCategory::AddTypeFilter(), and SBValue.
IsEqualTo()
bool SBTypeFilter::IsEqualTo (lldb::SBTypeFilter & rhs)
Definition at line 131 of file SBTypeFilter.cpp.
References GetExpressionPathAtIndex(), GetNumberOfExpressionPaths(), GetOptions(), IsValid(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTypeFilter().
IsValid()
bool SBTypeFilter::IsValid () const
Definition at line 33 of file SBTypeFilter.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBTypeCategory::AddTypeFilter(), CopyOnWrite_Impl(), GetDescription(), GetExpressionPathAtIndex(), GetNumberOfExpressionPaths(), GetOptions(), IsEqualTo(), operator!=(), operator==(), and ~SBTypeFilter().
operator bool()
SBTypeFilter::operator bool () const explicit
Definition at line 37 of file SBTypeFilter.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator!=()
bool SBTypeFilter::operator!= (lldb::SBTypeFilter & rhs)
Definition at line 148 of file SBTypeFilter.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeFilter().
operator=()
lldb::SBTypeFilter & SBTypeFilter::operator= (const lldb::SBTypeFilter & rhs)
Definition at line 113 of file SBTypeFilter.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeFilter().
operator==()
bool SBTypeFilter::operator== (lldb::SBTypeFilter & rhs)
Definition at line 122 of file SBTypeFilter.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeFilter().
ReplaceExpressionPathAtIndex()
bool SBTypeFilter::ReplaceExpressionPathAtIndex (uint32_t i, const char * item)
Definition at line 97 of file SBTypeFilter.cpp.
References CopyOnWrite_Impl(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeFilter().
SetOptions()
void SBTypeFilter::SetOptions (uint32_t value)
Definition at line 51 of file SBTypeFilter.cpp.
References CopyOnWrite_Impl(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeFilter().
SetSP()
void SBTypeFilter::SetSP (const lldb::TypeFilterImplSP & typefilter_impl_sp) protected
Definition at line 159 of file SBTypeFilter.cpp.
References m_opaque_sp.
Referenced by CopyOnWrite_Impl(), lldb::SBValue::GetTypeFilter(), and SBValue.
Friends And Related Symbol Documentation
SBDebugger
friend class SBDebugger friend
Definition at line 57 of file SBTypeFilter.h.
References SBDebugger.
Referenced by SBDebugger.
SBTypeCategory
friend class SBTypeCategory friend
Definition at line 58 of file SBTypeFilter.h.
References SBTypeCategory.
Referenced by SBTypeCategory.
SBValue
friend class SBValue friend
Definition at line 59 of file SBTypeFilter.h.
References GetSP(), SBValue, and SetSP().
Referenced by SBValue.
Member Data Documentation
m_opaque_sp
lldb::TypeFilterImplSP lldb::SBTypeFilter::m_opaque_sp protected
Definition at line 65 of file SBTypeFilter.h.
Referenced by AppendExpressionPath(), Clear(), CopyOnWrite_Impl(), GetDescription(), GetExpressionPathAtIndex(), GetNumberOfExpressionPaths(), GetOptions(), GetSP(), operator bool(), operator!=(), operator=(), operator==(), ReplaceExpressionPathAtIndex(), SBTypeFilter(), SBTypeFilter(), SBTypeFilter(), SetOptions(), and SetSP().
The documentation for this class was generated from the following files:
SBTypeFilter.h
SBTypeFilter.cpp