LLDB: lldb_private::AddressResolverFileLine Class Reference
lldb_private::AddressResolverFileLine Class Reference
"lldb/Core/AddressResolverFileLine.h" This class finds address for source file and line.
#include <AddressResolverFileLine.h>
Public Member Functions
AddressResolverFileLine (SourceLocationSpec location_spec)
~AddressResolverFileLine () override
Searcher::CallbackReturn SearchCallback (SearchFilter &filter, SymbolContext &context, Address *addr) override
lldb::SearchDepth GetDepth () override
void GetDescription (Stream *s) override
Prints a canonical description for the searcher to the stream s.
Public Member Functions inherited from lldb_private::AddressResolver
AddressResolver ()
~AddressResolver () override
virtual void ResolveAddress (SearchFilter &filter)
virtual void ResolveAddressInModules (SearchFilter &filter, ModuleList &modules)
std::vector< AddressRange > & GetAddressRanges ()
size_t GetNumberOfAddresses ()
AddressRange & GetAddressRangeAtIndex (size_t idx)
Public Member Functions inherited from lldb_private::Searcher
Searcher ()
virtual ~Searcher ()
Protected Attributes
SourceLocationSpec m_src_location_spec
Protected Attributes inherited from lldb_private::AddressResolver
std::vector< AddressRange > m_address_ranges
Private Member Functions
AddressResolverFileLine (const AddressResolverFileLine &)=delete
const AddressResolverFileLine & operator= (const AddressResolverFileLine &)=delete
Additional Inherited Members
Public Types inherited from lldb_private::AddressResolver
enum MatchType { Exact , Regexp , Glob }
Public Types inherited from lldb_private::Searcher
enum CallbackReturn { eCallbackReturnStop = 0 , eCallbackReturnContinue , eCallbackReturnPop }
Detailed Description
"lldb/Core/AddressResolverFileLine.h" This class finds address for source file and line.
Optionally, it will look for inlined instances of the file and line specification.
Definition at line 29 of file AddressResolverFileLine.h.
Constructor & Destructor Documentation
AddressResolverFileLine() [1/2]
AddressResolverFileLine::AddressResolverFileLine (SourceLocationSpec location_spec)
Definition at line 31 of file AddressResolverFileLine.cpp.
References lldb_private::AddressResolver::AddressResolver(), and m_src_location_spec.
Referenced by AddressResolverFileLine(), and operator=().
~AddressResolverFileLine()
AddressResolverFileLine::~AddressResolverFileLine () override default
AddressResolverFileLine() [2/2]
lldb_private::AddressResolverFileLine::AddressResolverFileLine (const AddressResolverFileLine &) private delete
References AddressResolverFileLine().
Member Function Documentation
GetDepth()
lldb::SearchDepth AddressResolverFileLine::GetDepth () override virtual
Implements lldb_private::Searcher.
Definition at line 67 of file AddressResolverFileLine.cpp.
References lldb::eSearchDepthCompUnit.
GetDescription()
void AddressResolverFileLine::GetDescription (Stream * s) override virtual
Prints a canonical description for the searcher to the stream s.
Parameters
[in] s Stream to which the output is copied.
Implements lldb_private::AddressResolver.
Definition at line 71 of file AddressResolverFileLine.cpp.
References m_src_location_spec, and lldb_private::Stream::Printf().
operator=()
const AddressResolverFileLine & lldb_private::AddressResolverFileLine::operator= (const AddressResolverFileLine &) private delete
References AddressResolverFileLine().
SearchCallback()
Searcher::CallbackReturn AddressResolverFileLine::SearchCallback (SearchFilter & filter, SymbolContext & context, Address * addr) override virtual
Implements lldb_private::Searcher.
Definition at line 38 of file AddressResolverFileLine.cpp.
References lldb_private::Breakpoints, lldb_private::SymbolContext::comp_unit, lldb_private::Searcher::eCallbackReturnContinue, lldb_private::Address::GetFileAddress(), lldb_private::GetLog(), lldb_private::Address::IsValid(), LLDB_LOGF, lldb_private::AddressResolver::m_address_ranges, m_src_location_spec, and lldb_private::CompileUnit::ResolveSymbolContext().
Member Data Documentation
m_src_location_spec
SourceLocationSpec lldb_private::AddressResolverFileLine::m_src_location_spec protected
Definition at line 44 of file AddressResolverFileLine.h.
Referenced by AddressResolverFileLine(), GetDescription(), and SearchCallback().
The documentation for this class was generated from the following files:
AddressResolverFileLine.h
AddressResolverFileLine.cpp