LLDB: lldb_private::PlatformQemuUser Class Reference
lldb_private::PlatformQemuUser Class Reference
#include <PlatformQemuUser.h>
Public Member Functions
llvm::StringRef GetPluginName () override
llvm::StringRef GetDescription () override
UserIDResolver & GetUserIDResolver () override
std::vector< ArchSpec > GetSupportedArchitectures (const ArchSpec &process_host_arch) override
Get the platform's supported architectures in the order in which they should be searched.
lldb::ProcessSP DebugProcess (ProcessLaunchInfo &launch_info, Debugger &debugger, Target &target, Status &error) override
Subclasses do not need to implement this function as it uses the Platform::LaunchProcess() followed by Platform::Attach ().
lldb::ProcessSP Attach (ProcessAttachInfo &attach_info, Debugger &debugger, Target *target, Status &status) override
Attach to an existing process using a process ID.
uint32_t FindProcesses (const ProcessInstanceInfoMatch &match_info, ProcessInstanceInfoList &proc_infos) override
Attach to an existing process by process name.
bool GetProcessInfo (lldb::pid_t pid, ProcessInstanceInfo &proc_info) override
bool IsConnected () const override
void CalculateTrapHandlerSymbolNames () override
Ask the Platform subclass to fill in the list of trap handler names.
Environment GetEnvironment () override
MmapArgList GetMmapArgumentList (const ArchSpec &arch, lldb::addr_t addr, lldb::addr_t length, unsigned prot, unsigned flags, lldb::addr_t fd, lldb::addr_t offset) override
Public Member Functions inherited from lldb_private::Platform
Platform (bool is_host_platform)
Default Constructor.
~Platform () override
The destructor is virtual since this class is designed to be inherited from by the plug-in instance.
virtual Status ResolveExecutable (const ModuleSpec &module_spec, lldb::ModuleSP &exe_module_sp)
Set the target's executable based off of the existing architecture information in target given a path to an executable exe_file.
virtual Status ResolveSymbolFile (Target &target, const ModuleSpec &sym_spec, FileSpec &sym_file)
Find a symbol file given a symbol file module specification.
virtual bool ResolveRemotePath (const FileSpec &platform_path, FileSpec &resolved_platform_path)
Resolves the FileSpec to a (possibly) remote path.
virtual llvm::VersionTuple GetOSVersion (Process *process=nullptr)
Get the OS version from a connected platform.
bool SetOSVersion (llvm::VersionTuple os_version)
std::optional< std::string > GetOSBuildString ()
std::optional< std::string > GetOSKernelDescription ()
llvm::StringRef GetName ()
virtual const char * GetHostname ()
virtual ConstString GetFullNameForDylib (ConstString basename)
virtual void GetStatus (Stream &strm)
Report the current status for this platform.
virtual bool GetRemoteOSVersion ()
virtual std::optional< std::string > GetRemoteOSBuildString ()
virtual std::optional< std::string > GetRemoteOSKernelDescription ()
virtual ArchSpec GetRemoteSystemArchitecture ()
virtual FileSpec GetRemoteWorkingDirectory ()
virtual bool SetRemoteWorkingDirectory (const FileSpec &working_dir)
virtual Status GetFileWithUUID (const FileSpec &platform_file, const UUID *uuid_ptr, FileSpec &local_file)
Locate a file for a platform.
virtual FileSpecList LocateExecutableScriptingResources (Target *target, Module &module, Stream &feedback_stream)
virtual Status GetSharedModule (const ModuleSpec &module_spec, Process *process, lldb::ModuleSP &module_sp, llvm::SmallVectorImpl< lldb::ModuleSP > *old_modules, bool *did_create_ptr)
void CallLocateModuleCallbackIfSet (const ModuleSpec &module_spec, lldb::ModuleSP &module_sp, FileSpec &symbol_file_spec, bool *did_create_ptr)
virtual bool GetModuleSpec (const FileSpec &module_file_spec, const ArchSpec &arch, ModuleSpec &module_spec)
virtual Status ConnectRemote (Args &args)
virtual Status DisconnectRemote ()
virtual size_t GetSoftwareBreakpointTrapOpcode (Target &target, BreakpointSite *bp_site)
virtual Status LaunchProcess (ProcessLaunchInfo &launch_info)
Launch a new process on a platform, not necessarily for debugging, it could be just for running the process.
virtual Status ShellExpandArguments (ProcessLaunchInfo &launch_info)
Perform expansion of the command-line for this launch info This can potentially involve wildcard expansion environment variable replacement, and whatever other argument magic the platform defines as part of its typical user experience.
virtual Status KillProcess (const lldb::pid_t pid)
Kill process on a platform.
virtual bool IsCompatibleArchitecture (const ArchSpec &arch, const ArchSpec &process_host_arch, ArchSpec::MatchType match, ArchSpec *compatible_arch_ptr)
Lets a platform answer if it is compatible with a given architecture and the target triple contained within.
virtual bool CanDebugProcess ()
Not all platforms will support debugging a process by spawning somehow halted for a debugger (specified using the "eLaunchFlagDebug" launch flag) and then attaching.
virtual lldb::ProcessSP ConnectProcess (llvm::StringRef connect_url, llvm::StringRef plugin_name, Debugger &debugger, Target *target, Status &error)
virtual lldb::ProcessSP ConnectProcessSynchronous (llvm::StringRef connect_url, llvm::StringRef plugin_name, Debugger &debugger, Stream &stream, Target *target, Status &error)
ProcessInstanceInfoList GetAllProcesses ()
virtual lldb::BreakpointSP SetThreadCreationBreakpoint (Target &target)
virtual lldb_private::ConstString GetSDKDirectory (lldb_private::Target &target)
virtual llvm::Expected< std::pair< XcodeSDK, bool > > GetSDKPathFromDebugInfo (Module &module)
Search each CU associated with the specified 'module' for the SDK paths the CUs were compiled against.
virtual llvm::Expected< std::string > ResolveSDKPathFromDebugInfo (Module &module)
Returns the full path of the most appropriate SDK for the specified 'module'.
virtual llvm::Expected< XcodeSDK > GetSDKPathFromDebugInfo (CompileUnit &unit)
Search CU for the SDK path the CUs was compiled against.
virtual llvm::Expected< std::string > ResolveSDKPathFromDebugInfo (CompileUnit &unit)
Returns the full path of the most appropriate SDK for the specified compile unit.
bool IsHost () const
bool IsRemote () const
const ArchSpec & GetSystemArchitecture ()
void SetSystemArchitecture (const ArchSpec &arch)
ArchSpec GetAugmentedArchSpec (llvm::StringRef triple)
If the triple contains not specify the vendor, os, and environment parts, we "augment" these using information from the platform and return the resulting ArchSpec object.
size_t GetMaxUserIDNameLength () const
size_t GetMaxGroupIDNameLength () const
const std::string & GetSDKRootDirectory () const
void SetSDKRootDirectory (std::string dir)
const std::string & GetSDKBuild () const
void SetSDKBuild (std::string sdk_build)
virtual bool SupportsModules ()
virtual void AddClangModuleCompilationOptions (Target *target, std::vector< std::string > &options)
FileSpec GetWorkingDirectory ()
bool SetWorkingDirectory (const FileSpec &working_dir)
virtual bool ModuleIsExcludedForUnconstrainedSearches (Target &target, const lldb::ModuleSP &module_sp)
virtual Status MakeDirectory (const FileSpec &file_spec, uint32_t permissions)
virtual Status GetFilePermissions (const FileSpec &file_spec, uint32_t &file_permissions)
virtual Status SetFilePermissions (const FileSpec &file_spec, uint32_t file_permissions)
virtual lldb::user_id_t OpenFile (const FileSpec &file_spec, File::OpenOptions flags, uint32_t mode, Status &error)
virtual bool CloseFile (lldb::user_id_t fd, Status &error)
virtual lldb::user_id_t GetFileSize (const FileSpec &file_spec)
virtual void AutoCompleteDiskFileOrDirectory (CompletionRequest &request, bool only_dir)
virtual uint64_t ReadFile (lldb::user_id_t fd, uint64_t offset, void *dst, uint64_t dst_len, Status &error)
virtual uint64_t WriteFile (lldb::user_id_t fd, uint64_t offset, const void *src, uint64_t src_len, Status &error)
virtual Status GetFile (const FileSpec &source, const FileSpec &destination)
virtual Status PutFile (const FileSpec &source, const FileSpec &destination, uint32_t uid=UINT32_MAX, uint32_t gid=UINT32_MAX)
virtual Status CreateSymlink (const FileSpec &src, const FileSpec &dst)
virtual Status Install (const FileSpec &src, const FileSpec &dst)
Install a file or directory to the remote system.
virtual bool GetFileExists (const lldb_private::FileSpec &file_spec)
virtual Status Unlink (const FileSpec &file_spec)
virtual bool GetSupportsRSync ()
virtual void SetSupportsRSync (bool flag)
virtual const char * GetRSyncOpts ()
virtual void SetRSyncOpts (const char *opts)
virtual const char * GetRSyncPrefix ()
virtual void SetRSyncPrefix (const char *prefix)
virtual bool GetSupportsSSH ()
virtual void SetSupportsSSH (bool flag)
virtual const char * GetSSHOpts ()
virtual void SetSSHOpts (const char *opts)
virtual bool GetIgnoresRemoteHostname ()
virtual void SetIgnoresRemoteHostname (bool flag)
virtual lldb_private::OptionGroupOptions * GetConnectionOptions (CommandInterpreter &interpreter)
virtual lldb_private::Status RunShellCommand (llvm::StringRef command, const FileSpec &working_dir, int *status_ptr, int *signo_ptr, std::string *command_output, const Timeout< std::micro > &timeout)
virtual lldb_private::Status RunShellCommand (llvm::StringRef shell, llvm::StringRef command, const FileSpec &working_dir, int *status_ptr, int *signo_ptr, std::string *command_output, const Timeout< std::micro > &timeout)
virtual void SetLocalCacheDirectory (const char *local)
virtual const char * GetLocalCacheDirectory ()
virtual std::string GetPlatformSpecificConnectionInformation ()
virtual llvm::ErrorOr< llvm::MD5::MD5Result > CalculateMD5 (const FileSpec &file_spec)
virtual uint32_t GetResumeCountForLaunchInfo (ProcessLaunchInfo &launch_info)
virtual const lldb::UnixSignalsSP & GetRemoteUnixSignals ()
lldb::UnixSignalsSP GetUnixSignals ()
virtual std::string GetQueueNameForThreadQAddress (Process *process, lldb::addr_t dispatch_qaddr)
Locate a queue name given a thread's qaddr.
virtual lldb::queue_id_t GetQueueIDForThreadQAddress (Process *process, lldb::addr_t dispatch_qaddr)
Locate a queue ID given a thread's qaddr.
virtual const std::vector< ConstString > & GetTrapHandlerSymbolNames ()
Provide a list of trap handler function names for this platform.
virtual lldb::UnwindPlanSP GetTrapHandlerUnwindPlan (const ArchSpec &arch, ConstString name)
Try to get a specific unwind plan for a named trap handler.
virtual FileSpec LocateExecutable (const char *basename)
Find a support executable that may not live within in the standard locations related to LLDB.
virtual uint32_t GetDefaultMemoryCacheLineSize ()
Allow the platform to set preferred memory cache line size.
uint32_t LoadImage (lldb_private::Process *process, const lldb_private::FileSpec &local_file, const lldb_private::FileSpec &remote_file, lldb_private::Status &error)
Load a shared library into this process.
uint32_t LoadImageUsingPaths (lldb_private::Process *process, const lldb_private::FileSpec &library_name, const std::vector< std::string > &paths, lldb_private::Status &error, lldb_private::FileSpec *loaded_path)
Load a shared library specified by base name into this process, looking by hand along a set of paths.
virtual uint32_t DoLoadImage (lldb_private::Process *process, const lldb_private::FileSpec &remote_file, const std::vector< std::string > *paths, lldb_private::Status &error, lldb_private::FileSpec *loaded_path=nullptr)
virtual Status UnloadImage (lldb_private::Process *process, uint32_t image_token)
virtual size_t ConnectToWaitingProcesses (lldb_private::Debugger &debugger, lldb_private::Status &error)
Connect to all processes waiting for a debugger to attach.
virtual llvm::Expected< StructuredData::DictionarySP > FetchExtendedCrashInformation (lldb_private::Process &process)
Gather all of crash informations into a structured data dictionary.
virtual bool LoadPlatformBinaryAndSetup (Process *process, lldb::addr_t addr, bool notify)
Detect a binary in memory that will determine which Platform and DynamicLoader should be used in this target/process, and update the Platform/DynamicLoader.
virtual CompilerType GetSiginfoType (const llvm::Triple &triple)
virtual lldb::StopInfoSP GetStopInfoFromSiginfo (Thread &thread)
virtual Args GetExtraStartupCommands ()
void SetLocateModuleCallback (LocateModuleCallback callback)
Set locate module callback.
LocateModuleCallback GetLocateModuleCallback () const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
Static Public Member Functions inherited from lldb_private::Platform
static void Initialize ()
static void Terminate ()
static PlatformProperties & GetGlobalPlatformProperties ()
static lldb::PlatformSP GetHostPlatform ()
Get the native host platform plug-in.
static const char * GetHostPlatformName ()
static void SetHostPlatform (const lldb::PlatformSP &platform_sp)
static lldb::PlatformSP Create (llvm::StringRef name)
static ArchSpec GetAugmentedArchSpec (Platform *platform, llvm::StringRef triple)
Augments the triple either with information from platform or the host system (if platform is null).
Private Member Functions
PlatformQemuUser ()
Static Private Member Functions
static lldb::PlatformSP CreateInstance (bool force, const ArchSpec *arch)
static void DebuggerInitialize (Debugger &debugger)
Additional Inherited Members
Public Types inherited from lldb_private::Platform
typedef std::function< Status(const ModuleSpec &module_spec, FileSpec &module_file_spec, FileSpec &symbol_file_spec)> LocateModuleCallback
Protected Types inherited from lldb_private::Platform
typedef std::map< uint32_t, ConstString > IDToNameMap
Protected Member Functions inherited from lldb_private::Platform
lldb::ProcessSP DoConnectProcess (llvm::StringRef connect_url, llvm::StringRef plugin_name, Debugger &debugger, Stream *stream, Target *target, Status &error)
Private implementation of connecting to a process.
Status GetCachedExecutable (ModuleSpec &module_spec, lldb::ModuleSP &module_sp)
virtual Status DownloadModuleSlice (const FileSpec &src_file_spec, const uint64_t src_offset, const uint64_t src_size, const FileSpec &dst_file_spec)
virtual Status DownloadSymbolFile (const lldb::ModuleSP &module_sp, const FileSpec &dst_file_spec)
virtual const char * GetCacheHostname ()
Static Protected Member Functions inherited from lldb_private::Platform
static std::vector< ArchSpec > CreateArchList (llvm::ArrayRef< llvm::Triple::ArchType > archs, llvm::Triple::OSType os)
Create a list of ArchSpecs with the given OS and a architectures.
Protected Attributes inherited from lldb_private::Platform
bool m_is_host
bool m_os_version_set_while_connected
bool m_system_arch_set_while_connected
std::string m_sdk_sysroot
std::string m_sdk_build
FileSpec m_working_dir
std::string m_hostname
llvm::VersionTuple m_os_version
ArchSpec m_system_arch
std::mutex m_mutex
size_t m_max_uid_name_len
size_t m_max_gid_name_len
bool m_supports_rsync
std::string m_rsync_opts
std::string m_rsync_prefix
bool m_supports_ssh
std::string m_ssh_opts
bool m_ignores_remote_hostname
std::string m_local_cache_directory
std::vector< ConstString > m_trap_handlers
bool m_calculated_trap_handlers
const std::unique_ptr< ModuleCache > m_module_cache
LocateModuleCallback m_locate_module_callback
Detailed Description
Definition at line 18 of file PlatformQemuUser.h.
Constructor & Destructor Documentation
PlatformQemuUser()
lldb_private::PlatformQemuUser::PlatformQemuUser () inline private
Definition at line 76 of file PlatformQemuUser.h.
References lldb_private::Platform::Platform().
Referenced by CreateInstance().
Member Function Documentation
Attach()
lldb::ProcessSP lldb_private::PlatformQemuUser::Attach (ProcessAttachInfo & attach_info, Debugger & debugger, Target * target, Status & error) inline override virtual
Attach to an existing process using a process ID.
Each platform subclass needs to implement this function and attempt to attach to the process with the process ID of pid. The platform subclass should return an appropriate ProcessSP subclass that is attached to the process, or an empty shared pointer with an appropriate error.
Returns
An appropriate ProcessSP containing a valid shared pointer to the default Process subclass for the platform that is attached to the process, or an empty shared pointer with an appropriate error fill into the error object.
Implements lldb_private::Platform.
Definition at line 42 of file PlatformQemuUser.h.
References lldb_private::Status::FromErrorString().
CalculateTrapHandlerSymbolNames()
void lldb_private::PlatformQemuUser::CalculateTrapHandlerSymbolNames () inline override virtual
Ask the Platform subclass to fill in the list of trap handler names.
For most Unix user process environments, this will be a single function name, _sigtramp. More specialized environments may have additional handler names. The unwinder code needs to know when a trap handler is on the stack because the unwind rules for the frame that caused the trap are different.
The base class Platform ivar m_trap_handlers should be updated by the Platform subclass when this method is called. If there are no predefined trap handlers, this method may be a no-op.
Implements lldb_private::Platform.
Definition at line 60 of file PlatformQemuUser.h.
CreateInstance()
PlatformSP PlatformQemuUser::CreateInstance (bool force, const ArchSpec * arch) static private
Definition at line 101 of file PlatformQemuUser.cpp.
References PlatformQemuUser().
Referenced by Initialize(), and Terminate().
DebuggerInitialize()
void PlatformQemuUser::DebuggerInitialize (Debugger & debugger) static private
Definition at line 91 of file PlatformQemuUser.cpp.
References lldb_private::PluginManager::CreateSettingForPlatformPlugin(), GetGlobalProperties(), GetPluginNameStatic(), and lldb_private::PluginManager::GetSettingForPlatformPlugin().
Referenced by Initialize().
DebugProcess()
lldb::ProcessSP PlatformQemuUser::DebugProcess (ProcessLaunchInfo & launch_info, Debugger & debugger, Target & target, Status & error) override virtual
Subclasses do not need to implement this function as it uses the Platform::LaunchProcess() followed by Platform::Attach ().
Remote platforms will want to subclass this function in order to be able to intercept STDIO and possibly launch a separate process that will debug the debuggee.
Reimplemented from lldb_private::Platform.
Definition at line 160 of file PlatformQemuUser.cpp.
References lldb_private::Args::AppendArguments(), lldb_private::Flags::Clear(), ComputeLaunchEnvironment(), lldb_private::Target::CreateProcess(), error(), lldb_private::Status::FromErrorString(), get_arg_range(), lldb_private::Target::GetArchitecture(), lldb_private::ProcessInfo::GetArg0(), lldb_private::ProcessInfo::GetArguments(), lldb_private::Host::GetEnvironment(), lldb_private::ProcessInfo::GetEnvironment(), lldb_private::ProcessInfo::GetExecutableFile(), lldb_private::ProcessLaunchInfo::GetFlags(), GetGlobalProperties(), lldb_private::ProcessInfo::GetHijackListener(), lldb_private::ProcessInfo::GetListener(), lldb_private::GetLog(), lldb_private::FileSpec::GetPath(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetPluginNameStatic(), lldb_private::PseudoTerminal::GetPrimaryFileDescriptor(), lldb_private::ProcessLaunchInfo::GetPTY(), lldb_private::Platform::GetSDKRootDirectory(), lldb_private::ArchSpec::GetTriple(), lldb_private::FileSystem::Instance(), lldb_private::PseudoTerminal::invalid_fd, lldb_private::Host::LaunchProcess(), LLDB_LOG, LLDB_LOG_ERROR, lldb_private::ProcessLaunchInfo::NoOpMonitorCallback(), lldb_private::Platform, lldb_private::PseudoTerminal::ReleasePrimaryFileDescriptor(), lldb_private::FileSystem::ResolveExecutableLocation(), lldb_private::ProcessInfo::SetArguments(), lldb_private::ProcessLaunchInfo::SetLaunchInSeparateProcessGroup(), lldb_private::ProcessLaunchInfo::SetMonitorProcessCallback(), lldb_private::FileSpec::SetPath(), and lldb_private::ProcessLaunchInfo::SetUpPtyRedirection().
FindProcesses()
uint32_t lldb_private::PlatformQemuUser::FindProcesses (const ProcessInstanceInfoMatch & match_info, ProcessInstanceInfoList & proc_infos) inline override virtual
Attach to an existing process by process name.
This function is not meant to be overridden by Process subclasses. It will first call Process::WillAttach (const char *) and if that returns true, Process::DoAttach (const char *) will be called to actually do the attach. If DoAttach returns true, then Process::DidAttach() will be called.
Parameters
[in] process_name A process name to match against the current process list.
Returns
Returns pid if attaching was successful, or LLDB_INVALID_PROCESS_ID if attaching fails.
Reimplemented from lldb_private::Platform.
Definition at line 48 of file PlatformQemuUser.h.
GetDescription()
llvm::StringRef lldb_private::PlatformQemuUser::GetDescription () inline override virtual
Implements lldb_private::Platform.
Definition at line 27 of file PlatformQemuUser.h.
References GetPluginDescriptionStatic().
GetEnvironment()
Environment PlatformQemuUser::GetEnvironment () override virtual
Reimplemented from lldb_private::Platform.
Definition at line 248 of file PlatformQemuUser.cpp.
References lldb_private::Host::GetEnvironment(), and GetGlobalProperties().
GetMmapArgumentList()
MmapArgList lldb_private::PlatformQemuUser::GetMmapArgumentList (const ArchSpec & arch, lldb::addr_t addr, lldb::addr_t length, unsigned prot, unsigned flags, lldb::addr_t fd, lldb::addr_t offset) inline override virtual
Reimplemented from lldb_private::Platform.
Definition at line 64 of file PlatformQemuUser.h.
References lldb_private::Platform::GetHostPlatform().
GetPluginDescriptionStatic()
llvm::StringRef PlatformQemuUser::GetPluginDescriptionStatic () static
Definition at line 77 of file PlatformQemuUser.cpp.
Referenced by GetDescription(), and Initialize().
GetPluginName()
llvm::StringRef lldb_private::PlatformQemuUser::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 26 of file PlatformQemuUser.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::PlatformQemuUser::GetPluginNameStatic () inline static
Definition at line 23 of file PlatformQemuUser.h.
Referenced by DebuggerInitialize(), GetPluginName(), and Initialize().
GetProcessInfo()
bool lldb_private::PlatformQemuUser::GetProcessInfo (lldb::pid_t pid, ProcessInstanceInfo & proc_info) inline override virtual
Reimplemented from lldb_private::Platform.
Definition at line 53 of file PlatformQemuUser.h.
GetSupportedArchitectures()
std::vector< ArchSpec > PlatformQemuUser::GetSupportedArchitectures (const ArchSpec & process_host_arch) override virtual
Get the platform's supported architectures in the order in which they should be searched.
Parameters
[in] process_host_arch The process host architecture if it's known. An invalid ArchSpec represents that the process host architecture is unknown.
Implements lldb_private::Platform.
Definition at line 108 of file PlatformQemuUser.cpp.
References GetGlobalProperties().
GetUserIDResolver()
UserIDResolver & lldb_private::PlatformQemuUser::GetUserIDResolver () inline override virtual
Reimplemented from lldb_private::Platform.
Definition at line 31 of file PlatformQemuUser.h.
Initialize()
void PlatformQemuUser::Initialize () static
Definition at line 81 of file PlatformQemuUser.cpp.
References CreateInstance(), DebuggerInitialize(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
IsConnected()
bool lldb_private::PlatformQemuUser::IsConnected () const inline override virtual
Reimplemented from lldb_private::Platform.
Definition at line 58 of file PlatformQemuUser.h.
Terminate()
void PlatformQemuUser::Terminate () static
Definition at line 87 of file PlatformQemuUser.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
The documentation for this class was generated from the following files:
PlatformQemuUser.h
PlatformQemuUser.cpp