LLDB: lldb_private::dil::ErrorNode Class Reference
lldb_private::dil::ErrorNode Class Reference
#include <DILAST.h>
Public Member Functions
ErrorNode ()
llvm::Expected< lldb::ValueObjectSP > Accept (Visitor *v) const override
Public Member Functions inherited from lldb_private::dil::ASTNode
ASTNode (uint32_t location, NodeKind kind)
virtual ~ASTNode ()=default
uint32_t GetLocation () const
NodeKind GetKind () const
Static Public Member Functions
static bool classof (const ASTNode &node)
Detailed Description
Definition at line 81 of file DILAST.h.
Constructor & Destructor Documentation
ErrorNode()
lldb_private::dil::ErrorNode::ErrorNode () inline
Definition at line 83 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), and lldb_private::dil::eErrorNode.
Member Function Documentation
Accept()
llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::ErrorNode::Accept (Visitor * v) const override virtual
Implements lldb_private::dil::ASTNode.
Definition at line 14 of file DILAST.cpp.
classof()
bool lldb_private::dil::ErrorNode::classof (const ASTNode & node) inline static
Definition at line 86 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), lldb_private::dil::eErrorNode, and lldb_private::dil::ASTNode::GetKind().
The documentation for this class was generated from the following files:
DILAST.h
DILAST.cpp