LLDB: lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd Class Reference
lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd Class Reference
Public Member Functions
MsvcStlTreeSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
~MsvcStlTreeSyntheticFrontEnd () override=default
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Member Functions
ValueObjectSP GetValueAt (size_t idx, size_t max_depth)
Returns the ValueObject for the _Tree_node at index idx.
Private Attributes
ValueObject * m_tree = nullptr
ValueObject * m_begin_node = nullptr
size_t m_count = UINT32_MAX
std::map< size_t, MapIterator > m_iterators
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
Definition at line 178 of file MsvcStlTree.cpp.
Constructor & Destructor Documentation
MsvcStlTreeSyntheticFrontEnd()
lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd::MsvcStlTreeSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
Definition at line 245 of file MsvcStlTree.cpp.
References lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd(), and Update().
~MsvcStlTreeSyntheticFrontEnd()
lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd::~MsvcStlTreeSyntheticFrontEnd () override default
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd::CalculateNumChildren () override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 253 of file MsvcStlTree.cpp.
References m_count, m_tree, and UINT32_MAX.
GetChildAtIndex()
lldb::ValueObjectSP lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd::GetChildAtIndex (uint32_t idx) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 299 of file MsvcStlTree.cpp.
References lldb_private::SyntheticChildrenFrontEnd::CalculateNumChildrenIgnoringErrors(), lldb_private::StreamString::GetString(), GetValueAt(), m_begin_node, m_tree, and lldb_private::Stream::Printf().
GetIndexOfChildWithName()
llvm::Expected< size_t > lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd::GetIndexOfChildWithName (ConstString name) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 339 of file MsvcStlTree.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::formatters::ExtractIndexFromString(), and lldb_private::ConstString::GetCString().
GetValueAt()
ValueObjectSP lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd::GetValueAt (size_t idx, size_t max_depth) private
Returns the ValueObject for the _Tree_node at index idx.
Parameters
[in] idx The child index that we're looking to get the value for.
[in] max_depth The maximum search depth after which we stop trying to find the node for.
Returns
On success, returns the ValueObjectSP corresponding to the _Tree_node's _Myval member. On failure, nullptr is returned.
Definition at line 269 of file MsvcStlTree.cpp.
References m_begin_node, and m_iterators.
Referenced by GetChildAtIndex().
Update()
lldb::ChildCacheState lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd::Update () override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 324 of file MsvcStlTree.cpp.
References lldb::eRefetch, lldb_private::SyntheticChildrenFrontEnd::m_backend, m_begin_node, m_count, m_iterators, m_tree, and UINT32_MAX.
Referenced by MsvcStlTreeSyntheticFrontEnd().
Member Data Documentation
m_begin_node
ValueObject* lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd::m_begin_node = nullptr private
Definition at line 206 of file MsvcStlTree.cpp.
Referenced by GetChildAtIndex(), GetValueAt(), and Update().
m_count
size_t lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd::m_count = UINT32_MAX private
Definition at line 207 of file MsvcStlTree.cpp.
Referenced by CalculateNumChildren(), and Update().
m_iterators
std::map<size_t, MapIterator> lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd::m_iterators private
Definition at line 208 of file MsvcStlTree.cpp.
Referenced by GetValueAt(), and Update().
m_tree
ValueObject* lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd::m_tree = nullptr private
Definition at line 205 of file MsvcStlTree.cpp.
Referenced by CalculateNumChildren(), GetChildAtIndex(), and Update().
The documentation for this class was generated from the following file:
MsvcStlTree.cpp