LLDB: lldb::SBProcessInfoList Class Reference
lldb::SBProcessInfoList Class Reference
#include <SBProcessInfoList.h>
Public Member Functions
SBProcessInfoList ()
~SBProcessInfoList ()
SBProcessInfoList (const lldb::SBProcessInfoList &rhs)
const lldb::SBProcessInfoList & operator= (const lldb::SBProcessInfoList &rhs)
uint32_t GetSize () const
bool GetProcessInfoAtIndex (uint32_t idx, SBProcessInfo &info)
void Clear ()
Private Member Functions
SBProcessInfoList (const lldb_private::ProcessInfoList &impl)
Private Attributes
friend SBPlatform
std::unique_ptr< lldb_private::ProcessInfoList > m_opaque_up
Detailed Description
Definition at line 22 of file SBProcessInfoList.h.
Constructor & Destructor Documentation
SBProcessInfoList() [1/3]
SBProcessInfoList::SBProcessInfoList () default
Referenced by ~SBProcessInfoList().
~SBProcessInfoList()
SBProcessInfoList::~SBProcessInfoList () default
References Clear(), GetProcessInfoAtIndex(), GetSize(), operator=(), and SBProcessInfoList().
SBProcessInfoList() [2/3]
SBProcessInfoList::SBProcessInfoList (const lldb::SBProcessInfoList & rhs)
Definition at line 28 of file SBProcessInfoList.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, and m_opaque_up.
SBProcessInfoList() [3/3]
SBProcessInfoList::SBProcessInfoList (const lldb_private::ProcessInfoList & impl) private
Definition at line 23 of file SBProcessInfoList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Member Function Documentation
Clear()
void SBProcessInfoList::Clear ()
Definition at line 54 of file SBProcessInfoList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBProcessInfoList().
GetProcessInfoAtIndex()
bool SBProcessInfoList::GetProcessInfoAtIndex (uint32_t idx, SBProcessInfo & info)
Definition at line 61 of file SBProcessInfoList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBProcessInfo::SetProcessInfo().
Referenced by ~SBProcessInfoList().
GetSize()
uint32_t SBProcessInfoList::GetSize () const
Definition at line 45 of file SBProcessInfoList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBProcessInfoList().
operator=()
const lldb::SBProcessInfoList & SBProcessInfoList::operator= (const lldb::SBProcessInfoList & rhs)
Definition at line 36 of file SBProcessInfoList.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBProcessInfoList().
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::ProcessInfoList> lldb::SBProcessInfoList::m_opaque_up private
Definition at line 41 of file SBProcessInfoList.h.
Referenced by Clear(), GetProcessInfoAtIndex(), GetSize(), operator=(), SBProcessInfoList(), and SBProcessInfoList().
SBPlatform
friend lldb::SBProcessInfoList::SBPlatform private
Definition at line 38 of file SBProcessInfoList.h.
The documentation for this class was generated from the following files:
SBProcessInfoList.h
SBProcessInfoList.cpp