LLDB: lldb_private::plugin::dwarf::SymbolFileDWARF Class Reference
lldb_private::plugin::dwarf::SymbolFileDWARF Class Reference
#include <SymbolFileDWARF.h>
Public Types
typedef std::map< ConstString, lldb::ModuleSP > ExternalTypeModuleMap
typedef llvm::DenseMap< const DWARFDebugInfoEntry *, lldb::VariableSP > DIEToVariableSP
Public Types inherited from lldb_private::SymbolFile
enum Abilities {
CompileUnits = (1u << 0) , LineTables = (1u << 1) , Functions = (1u << 2) , Blocks = (1u << 3) ,
GlobalVariables = (1u << 4) , LocalVariables = (1u << 5) , VariableTypes = (1u << 6) , kAllAbilities = ((1u << 7) - 1u)
}
Public Member Functions
SymbolFileDWARF (lldb::ObjectFileSP objfile_sp, SectionList *dwo_section_list)
~SymbolFileDWARF () override
uint32_t CalculateAbilities () override
void InitializeObject () override
Initialize the SymbolFile object.
lldb::LanguageType ParseLanguage (CompileUnit &comp_unit) override
XcodeSDK ParseXcodeSDK (CompileUnit &comp_unit) override
Return the Xcode SDK comp_unit was compiled against.
size_t ParseFunctions (CompileUnit &comp_unit) override
bool ParseLineTable (CompileUnit &comp_unit) override
bool ParseDebugMacros (CompileUnit &comp_unit) override
bool ForEachExternalModule (CompileUnit &, llvm::DenseSet< SymbolFile * > &, llvm::function_ref< bool(Module &)>) override
bool ParseSupportFiles (CompileUnit &comp_unit, SupportFileList &support_files) override
bool ParseIsOptimized (CompileUnit &comp_unit) override
size_t ParseTypes (CompileUnit &comp_unit) override
bool ParseImportedModules (const SymbolContext &sc, std::vector< SourceModule > &imported_modules) override
size_t ParseBlocksRecursive (Function &func) override
size_t ParseVariablesForContext (const SymbolContext &sc) override
std::optional< ArrayInfo > GetDynamicArrayInfoForUID (lldb::user_id_t type_uid, const ExecutionContext *exe_ctx) override
If type_uid points to an array type, return its characteristics.
bool CompleteType (CompilerType &compiler_type) override
Type * ResolveType (const DWARFDIE &die, bool assert_not_being_parsed=true, bool resolve_function_context=false)
CompilerDecl GetDeclForUID (lldb::user_id_t uid) override
CompilerDeclContext GetDeclContextForUID (lldb::user_id_t uid) override
CompilerDeclContext GetDeclContextContainingUID (lldb::user_id_t uid) override
std::vector< CompilerContext > GetCompilerContextForUID (lldb::user_id_t uid) override
void ParseDeclsForContext (CompilerDeclContext decl_ctx) override
uint32_t ResolveSymbolContext (const Address &so_addr, lldb::SymbolContextItem resolve_scope, SymbolContext &sc) override
Status CalculateFrameVariableError (StackFrame &frame) override
Subclasses will override this function to for GetFrameVariableError().
uint32_t ResolveSymbolContext (const SourceLocationSpec &src_location_spec, lldb::SymbolContextItem resolve_scope, SymbolContextList &sc_list) override
void FindGlobalVariables (ConstString name, const CompilerDeclContext &parent_decl_ctx, uint32_t max_matches, VariableList &variables) override
void FindGlobalVariables (const RegularExpression &regex, uint32_t max_matches, VariableList &variables) override
void FindFunctions (const Module::LookupInfo &lookup_info, const CompilerDeclContext &parent_decl_ctx, bool include_inlines, SymbolContextList &sc_list) override
void FindFunctions (const RegularExpression &regex, bool include_inlines, SymbolContextList &sc_list) override
void GetMangledNamesForFunction (const std::string &scope_qualified_name, std::vector< ConstString > &mangled_names) override
uint64_t GetDebugInfoSize (bool load_all_debug_info=false) override
Metrics gathering functions.
void FindTypes (const lldb_private::TypeQuery &match, lldb_private::TypeResults &results) override
Find types using a type-matching object that contains all search parameters.
void GetTypes (SymbolContextScope *sc_scope, lldb::TypeClass type_mask, TypeList &type_list) override
llvm::Expected< lldb::TypeSystemSP > GetTypeSystemForLanguage (lldb::LanguageType language) override
CompilerDeclContext FindNamespace (ConstString name, const CompilerDeclContext &parent_decl_ctx, bool only_root_namespaces) override
Finds a namespace of name name and whose parent context is parent_decl_ctx.
void PreloadSymbols () override
std::recursive_mutex & GetModuleMutex () const override
Symbols file subclasses should override this to return the Module that owns the TypeSystem that this symbol file modifies type information in.
llvm::StringRef GetPluginName () override
llvm::DWARFDebugAbbrev * DebugAbbrev ()
DWARFDebugInfo & DebugInfo ()
DWARFDIE GetDeclContextDIEContainingDIE (const DWARFDIE &die)
bool HasForwardDeclForCompilerType (const CompilerType &compiler_type)
CompileUnit * GetCompUnitForDWARFCompUnit (DWARFCompileUnit &dwarf_cu)
virtual void GetObjCMethods (ConstString class_name, llvm::function_ref< IterationAction(DWARFDIE die)> callback)
DebugMacrosSP ParseDebugMacros (lldb::offset_t *offset)
lldb::ModuleSP GetExternalModule (ConstString name)
const ExternalTypeModuleMap & getExternalTypeModules () const
Return the list of Clang modules imported by this SymbolFile.
virtual SymbolFileDWARF * GetDIERefSymbolFile (const DIERef &die_ref)
Given a DIERef, find the correct SymbolFileDWARF.
virtual DWARFDIE GetDIE (const DIERef &die_ref)
DWARFDIE GetDIE (lldb::user_id_t uid)
std::shared_ptr< SymbolFileDWARFDwo > GetDwoSymbolFileForCompileUnit (DWARFUnit &dwarf_cu, const DWARFDebugInfoEntry &cu_die)
std::optional< uint64_t > GetDWOId ()
If this is a DWARF object with a single CU, return its DW_AT_dwo_id.
DWARFUnit * GetSkeletonUnit (DWARFUnit *dwo_unit)
Given a DWO DWARFUnit, find the corresponding skeleton DWARFUnit in the main symbol file.
std::vector< std::unique_ptr< CallEdge > > ParseCallEdgesInFunction (UserID func_id) override
void Dump (Stream &s) override
void DumpClangAST (Stream &s, llvm::StringRef filter, bool show_colors) override
bool GetSeparateDebugInfo (StructuredData::Dictionary &d, bool errors_only, bool load_all_debug_info=false) override
List separate dwo files.
DWOStats GetDwoStats () override
Gets statistics about dwo files associated with this symbol file.
DWARFContext & GetDWARFContext ()
const std::shared_ptr< SymbolFileDWARFDwo > & GetDwpSymbolFile ()
FileSpec GetFile (DWARFUnit &unit, size_t file_idx)
StatsDuration::Duration GetDebugInfoParseTime () override
Return the time taken to parse the debug information.
StatsDuration::Duration GetDebugInfoIndexTime () override
Return the time it took to index the debug information in the object file.
StatsDuration & GetDebugInfoParseTimeRef ()
void ResetStatistics () override
Reset the statistics for the symbol file.
virtual lldb::offset_t GetVendorDWARFOpcodeSize (const DataExtractor &data, const lldb::offset_t data_offset, const uint8_t op) const
virtual bool ParseVendorDWARFOpcode (uint8_t op, const DataExtractor &opcodes, lldb::offset_t &offset, RegisterContext *reg_ctx, lldb::RegisterKind reg_kind, std::vector< Value > &stack) const
ConstString ConstructFunctionDemangledName (const DWARFDIE &die)
std::optional< uint64_t > GetFileIndex () const
void SetFileIndex (std::optional< uint64_t > file_index)
virtual llvm::DenseMap< const DWARFDebugInfoEntry *, Type * > & GetDIEToType ()
virtual llvm::DenseMap< lldb::opaque_compiler_type_t, DIERef > & GetForwardDeclCompilerTypeToDIE ()
virtual DIEToVariableSP & GetDIEToVariable ()
virtual UniqueDWARFASTTypeMap & GetUniqueDWARFASTTypeMap ()
bool ClassOrStructIsVirtual (const DWARFDIE &die)
SymbolFileDWARFDebugMap * GetDebugMapSymfile ()
virtual DWARFDIE FindDefinitionDIE (const DWARFDIE &die)
virtual lldb::TypeSP FindCompleteObjCDefinitionTypeForDIE (const DWARFDIE &die, ConstString type_name, bool must_be_implementation)
Type * ResolveTypeUID (lldb::user_id_t type_uid) override
Type * ResolveTypeUID (const DWARFDIE &die, bool assert_not_being_parsed)
Type * ResolveTypeUID (const DIERef &die_ref)
DWARFIndex * getIndex ()
Returns the DWARFIndex for this symbol, if it exists.
Public Member Functions inherited from lldb_private::SymbolFileCommon
SymbolFileCommon (lldb::ObjectFileSP objfile_sp)
~SymbolFileCommon () override=default
uint32_t GetAbilities () override
Get a mask of what this symbol file supports for the object file that it was constructed with.
Symtab * GetSymtab (bool can_create=true) override
ObjectFile * GetObjectFile () override
const ObjectFile * GetObjectFile () const override
ObjectFile * GetMainObjectFile () override
void SectionFileAddressesChanged () override
Notify the SymbolFile that the file addresses in the Sections for this module have been changed.
uint32_t GetNumCompileUnits () override
lldb::CompUnitSP GetCompileUnitAtIndex (uint32_t idx) override
bool GetDebugInfoIndexWasLoadedFromCache () const override
Accessors for the bool that indicates if the debug info index was loaded from, or saved to the module index cache.
void SetDebugInfoIndexWasLoadedFromCache () override
bool GetDebugInfoIndexWasSavedToCache () const override
void SetDebugInfoIndexWasSavedToCache () override
bool GetDebugInfoHadFrameVariableErrors () const override
Accessors for the bool that indicates if there was debug info, but errors stopped variables from being able to be displayed correctly.
void SetDebugInfoHadFrameVariableErrors () override
lldb::TypeSP MakeType (lldb::user_id_t uid, ConstString name, std::optional< uint64_t > byte_size, SymbolContextScope *context, lldb::user_id_t encoding_uid, Type::EncodingDataType encoding_uid_type, const Declaration &decl, const CompilerType &compiler_qual_type, Type::ResolveState compiler_type_resolve_state, uint32_t opaque_payload=0) override
This function is used to create types that belong to a SymbolFile.
lldb::TypeSP CopyType (const lldb::TypeSP &other_type) override
Public Member Functions inherited from lldb_private::SymbolFile
SymbolFile ()=default
~SymbolFile () override=default
virtual SymbolFile * GetBackingSymbolFile ()
SymbolFileOnDemand class overrides this to return the underlying backing SymbolFile implementation that loads on-demand.
virtual bool GetLoadDebugInfoEnabled ()
Whether debug info will be loaded or not.
virtual void SetLoadDebugInfoEnabled ()
Specify debug info should be loaded.
virtual llvm::SmallSet< lldb::LanguageType, 4 > ParseAllLanguages (CompileUnit &comp_unit)
This function exists because SymbolFileDWARFDebugMap may extra compile units which aren't exposed as "real" compile units.
virtual bool ForEachExternalModule (lldb_private::CompileUnit &comp_unit, llvm::DenseSet< lldb_private::SymbolFile * > &visited_symbol_files, llvm::function_ref< bool(Module &)> lambda)
Apply a lambda to each external lldb::Module referenced by this comp_unit.
Status GetFrameVariableError (StackFrame &frame)
Get an error that describes why variables might be missing for a given symbol context.
virtual void FindFunctions (llvm::ArrayRef< Module::LookupInfo > lookup_infos, const CompilerDeclContext &parent_decl_ctx, bool include_inlines, SymbolContextList &sc_list)
virtual void AddSymbols (Symtab &symtab)
virtual lldb::UnwindPlanSP GetUnwindPlan (const Address &address, const RegisterInfoResolver &resolver)
virtual llvm::Expected< lldb::addr_t > GetParameterStackSize (const Symbol &symbol)
Return the number of stack bytes taken up by the parameters to this function.
virtual ModuleList GetDebugInfoModules ()
Get the additional modules that this symbol file uses to parse debug info.
std::unordered_map< lldb::CompUnitSP, Args > GetCompileOptions ()
Returns a map of compilation unit to the compile option arguments associated with that compilation unit.
std::string GetObjectName () const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static void DebuggerInitialize (Debugger &debugger)
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static SymbolFile * CreateInstance (lldb::ObjectFileSP objfile_sp)
static bool SupportedVersion (uint16_t version)
static DWARFDIE GetParentSymbolContextDIE (const DWARFDIE &die)
static bool DIEInDeclContext (const CompilerDeclContext &parent_decl_ctx, const DWARFDIE &die, bool only_root_namespaces=false)
static llvm::Expected< lldb::TypeSystemSP > GetTypeSystem (DWARFUnit &unit)
static DWARFASTParser * GetDWARFParser (DWARFUnit &unit)
static CompilerDecl GetDecl (const DWARFDIE &die)
static CompilerDeclContext GetDeclContext (const DWARFDIE &die)
static CompilerDeclContext GetContainingDeclContext (const DWARFDIE &die)
static lldb::LanguageType LanguageTypeFromDWARF (uint64_t val)
static lldb::LanguageType GetLanguage (DWARFUnit &unit)
static lldb::LanguageType GetLanguageFamily (DWARFUnit &unit)
Same as GetLanguage() but reports all C++ versions as C++ (no version).
static bool classof (const SymbolFileCommon *obj)
Static Public Member Functions inherited from lldb_private::SymbolFile
static SymbolFile * FindPlugin (lldb::ObjectFileSP objfile_sp)
static bool classof (const SymbolFile *obj)
Protected Types
typedef llvm::SetVector< Type * > TypeSet
typedef RangeDataVector< lldb::addr_t, lldb::addr_t, Variable * > GlobalVariableMap
typedef std::unordered_map< lldb::offset_t, DebugMacrosSP > DebugMacrosMap
typedef std::set< DIERef > DIERefSet
typedef llvm::StringMap< DIERefSet > NameToOffsetMap
Protected Member Functions
SymbolFileDWARF (const SymbolFileDWARF &)=delete
const SymbolFileDWARF & operator= (const SymbolFileDWARF &)=delete
virtual void LoadSectionData (lldb::SectionType sect_type, DWARFDataExtractor &data)
bool DeclContextMatchesThisSymbolFile (const CompilerDeclContext &decl_ctx)
uint32_t CalculateNumCompileUnits () override
lldb::CompUnitSP ParseCompileUnitAtIndex (uint32_t index) override
TypeList & GetTypeList () override
lldb::CompUnitSP ParseCompileUnit (DWARFCompileUnit &dwarf_cu)
virtual DWARFCompileUnit * GetDWARFCompileUnit (CompileUnit *comp_unit)
DWARFUnit * GetNextUnparsedDWARFCompileUnit (DWARFUnit *prev_cu)
bool GetFunction (const DWARFDIE &die, SymbolContext &sc)
Function * ParseFunction (CompileUnit &comp_unit, const DWARFDIE &die)
size_t ParseBlocksRecursive (CompileUnit &comp_unit, Block *parent_block, DWARFDIE die, lldb::addr_t function_file_addr)
size_t ParseTypes (const SymbolContext &sc, const DWARFDIE &die, bool parse_siblings, bool parse_children)
lldb::TypeSP ParseType (const SymbolContext &sc, const DWARFDIE &die, bool *type_is_new)
bool ParseSupportFiles (DWARFUnit &dwarf_cu, const lldb::ModuleSP &module, SupportFileList &support_files)
lldb::VariableSP ParseVariableDIE (const SymbolContext &sc, const DWARFDIE &die, const lldb::addr_t func_low_pc)
lldb::VariableSP ParseVariableDIECached (const SymbolContext &sc, const DWARFDIE &die)
void ParseAndAppendGlobalVariable (const SymbolContext &sc, const DWARFDIE &die, VariableList &cc_variable_list)
size_t ParseVariablesInFunctionContext (const SymbolContext &sc, const DWARFDIE &die, const lldb::addr_t func_low_pc)
size_t ParseVariablesInFunctionContextRecursive (const SymbolContext &sc, const DWARFDIE &die, lldb::addr_t func_low_pc, DIEArray &accumulator)
size_t PopulateBlockVariableList (VariableList &variable_list, const SymbolContext &sc, llvm::ArrayRef< DIERef > variable_dies, lldb::addr_t func_low_pc)
DIEArray MergeBlockAbstractParameters (const DWARFDIE &block_die, DIEArray &&variable_dies)
llvm::Expected< SymbolContext > ResolveFunctionCallLabel (FunctionCallLabel &label) override
Resolves the function corresponding to the specified LLDB function call label.
bool ResolveFunction (const DWARFDIE &die, bool include_inlines, SymbolContextList &sc_list)
void ResolveFunctionAndBlock (lldb::addr_t file_vm_addr, bool lookup_block, SymbolContext &sc)
Resolve functions and (possibly) blocks for the given file address and a compile unit.
Symbol * GetObjCClassSymbol (ConstString objc_class_name)
lldb::TypeSP GetTypeForDIE (const DWARFDIE &die, bool resolve_function_context=false)
void SetDebugMapModule (const lldb::ModuleSP &module_sp)
DWARFDIE FindBlockContainingSpecification (const DIERef &func_die_ref, dw_offset_t spec_block_die_offset)
DWARFDIE FindBlockContainingSpecification (const DWARFDIE &die, dw_offset_t spec_block_die_offset)
bool ClassContainsSelector (const DWARFDIE &class_die, ConstString selector)
std::vector< std::unique_ptr< CallEdge > > CollectCallEdges (lldb::ModuleSP module, DWARFDIE function_die)
Parse call site entries (DW_TAG_call_site), including any nested call site parameters (DW_TAG_call_site_parameter).
lldb::addr_t FixupAddress (lldb::addr_t file_addr)
If this symbol file is linked to by a debug map (see SymbolFileDWARFDebugMap), and file_addr is a file address relative to an object file, adjust file_addr so that it is relative to the main binary.
bool FixupAddress (Address &addr)
void GetTypes (const DWARFDIE &die, dw_offset_t min_die_offset, dw_offset_t max_die_offset, uint32_t type_mask, TypeSet &type_set)
GlobalVariableMap & GetGlobalAranges ()
void UpdateExternalModuleListIfNeeded ()
void BuildCuTranslationTable ()
std::optional< uint32_t > GetDWARFUnitIndex (uint32_t cu_idx)
void FindDwpSymbolFile ()
const SupportFileList * GetTypeUnitSupportFiles (DWARFTypeUnit &tu)
void InitializeFirstCodeAddressRecursive (const SectionList &section_list)
void InitializeFirstCodeAddress ()
void GetCompileOptions (std::unordered_map< lldb::CompUnitSP, Args > &args) override
Protected Member Functions inherited from lldb_private::SymbolFileCommon
void SetCompileUnitAtIndex (uint32_t idx, const lldb::CompUnitSP &cu_sp)
Protected Member Functions inherited from lldb_private::SymbolFile
void AssertModuleLock ()
virtual void GetCompileOptions (std::unordered_map< lldb::CompUnitSP, lldb_private::Args > &args)
Protected Attributes
lldb::ModuleWP m_debug_map_module_wp
SymbolFileDWARFDebugMap * m_debug_map_symfile
llvm::once_flag m_dwp_symfile_once_flag
std::shared_ptr< SymbolFileDWARFDwo > m_dwp_symfile
DWARFContext m_context
llvm::once_flag m_info_once_flag
std::unique_ptr< DWARFDebugInfo > m_info
std::unique_ptr< llvm::DWARFDebugAbbrev > m_abbr
std::unique_ptr< GlobalVariableMap > m_global_aranges_up
DebugMacrosMap m_debug_macros_map
ExternalTypeModuleMap m_external_type_modules
std::unique_ptr< DWARFIndex > m_index
bool m_fetched_external_modules: 1
NameToOffsetMap m_function_scope_qualified_name_map
UniqueDWARFASTTypeMap m_unique_ast_type_map
llvm::DenseMap< const DWARFDebugInfoEntry *, Type * > m_die_to_type
DIEToVariableSP m_die_to_variable_sp
llvm::DenseMap< lldb::opaque_compiler_type_t, DIERef > m_forward_decl_compiler_type_to_die
llvm::DenseMap< dw_offset_t, std::unique_ptr< SupportFileList > > m_type_unit_support_files
std::vector< uint32_t > m_lldb_cu_to_dwarf_unit
lldb::addr_t m_first_code_address = LLDB_INVALID_ADDRESS
DWARF does not provide a good way for traditional (concatenating) linkers to invalidate debug info describing dead-stripped code.
StatsDuration m_parse_time
std::atomic_flag m_dwo_warning_issued = ATOMIC_FLAG_INIT
std::optional< uint64_t > m_file_index
If this DWARF file a .DWO file or a DWARF .o file on mac when no dSYM file is being used, this file index will be set to a valid value that can be used in DIERef objects which will contain an index that identifies the .DWO or .o file.
Protected Attributes inherited from lldb_private::SymbolFileCommon
lldb::ObjectFileSP m_objfile_sp
std::optional< std::vector< lldb::CompUnitSP > > m_compile_units
TypeList m_type_list
uint32_t m_abilities = 0
bool m_calculated_abilities = false
bool m_index_was_loaded_from_cache = false
bool m_index_was_saved_to_cache = false
bool m_debug_info_had_variable_errors = false
Set to true if any variable feteching errors have been found when calling GetFrameVariableError().
Private Member Functions
llvm::Expected< DWARFDIE > FindFunctionDefinition (const FunctionCallLabel &label, const DWARFDIE &declaration)
Find the definition DIE for the specified label in this SymbolFile.
Static Private Attributes
static char ID
LLVM RTTI support.
Friends
class SymbolFileDWARFDebugMap
class SymbolFileDWARFDwo
class DebugMapModule
class DWARFCompileUnit
class DWARFDIE
class DWARFASTParser
bool isA (const void *ClassID) const override
LLVM RTTI support.
static bool classof (const SymbolFile *obj)
Detailed Description
Definition at line 66 of file SymbolFileDWARF.h.
Member Typedef Documentation
DebugMacrosMap
typedef std::unordered_map<lldb::offset_t, DebugMacrosSP> lldb_private::plugin::dwarf::SymbolFileDWARF::DebugMacrosMap protected
Definition at line 539 of file SymbolFileDWARF.h.
DIERefSet
typedef std::set<DIERef> lldb_private::plugin::dwarf::SymbolFileDWARF::DIERefSet protected
Definition at line 546 of file SymbolFileDWARF.h.
DIEToVariableSP
typedef llvm::DenseMap<const DWARFDebugInfoEntry *, lldb::VariableSP> lldb_private::plugin::dwarf::SymbolFileDWARF::DIEToVariableSP
Definition at line 354 of file SymbolFileDWARF.h.
ExternalTypeModuleMap
typedef std::map<ConstString, lldb::ModuleSP> lldb_private::plugin::dwarf::SymbolFileDWARF::ExternalTypeModuleMap
Definition at line 233 of file SymbolFileDWARF.h.
GlobalVariableMap
typedef RangeDataVector<lldb::addr_t, lldb::addr_t, Variable *> lldb_private::plugin::dwarf::SymbolFileDWARF::GlobalVariableMap protected
Definition at line 505 of file SymbolFileDWARF.h.
NameToOffsetMap
typedef llvm::StringMap<DIERefSet> lldb_private::plugin::dwarf::SymbolFileDWARF::NameToOffsetMap protected
Definition at line 547 of file SymbolFileDWARF.h.
TypeSet
typedef llvm::SetVector<Type *> lldb_private::plugin::dwarf::SymbolFileDWARF::TypeSet protected
Definition at line 498 of file SymbolFileDWARF.h.
Constructor & Destructor Documentation
SymbolFileDWARF() [1/2]
SymbolFileDWARF::SymbolFileDWARF (lldb::ObjectFileSP objfile_sp, SectionList * dwo_section_list)
Definition at line 481 of file SymbolFileDWARF.cpp.
References m_context, m_debug_map_module_wp, m_debug_map_symfile, m_fetched_external_modules, lldb_private::SymbolFileCommon::m_objfile_sp, and lldb_private::SymbolFileCommon::SymbolFileCommon().
Referenced by CreateInstance(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetBaseSymbolFile(), GetDIE(), GetDIERefSymbolFile(), operator=(), SymbolFileDWARF(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::SymbolFileDWARFDwo(), and lldb_private::plugin::dwarf::SymbolFileWasm::SymbolFileWasm().
~SymbolFileDWARF()
SymbolFileDWARF::~SymbolFileDWARF () override default
References DWARFDIE.
SymbolFileDWARF() [2/2]
lldb_private::plugin::dwarf::SymbolFileDWARF::SymbolFileDWARF (const SymbolFileDWARF &) protected delete
References SymbolFileDWARF().
Member Function Documentation
BuildCuTranslationTable()
void SymbolFileDWARF::BuildCuTranslationTable () protected
Definition at line 860 of file SymbolFileDWARF.cpp.
References lldb_private::plugin::dwarf::DWARFDebugInfo::ContainsTypeUnits(), DebugInfo(), lldb_private::plugin::dwarf::DWARFDebugInfo::GetNumUnits(), lldb_private::plugin::dwarf::DWARFDebugInfo::GetUnitAtIndex(), and m_lldb_cu_to_dwarf_unit.
Referenced by CalculateNumCompileUnits(), GetDWARFUnitIndex(), and ParseCompileUnit().
CalculateAbilities()
uint32_t SymbolFileDWARF::CalculateAbilities () override virtual
Implements lldb_private::SymbolFile.
Definition at line 609 of file SymbolFileDWARF.cpp.
References lldb_private::SymbolFile::Blocks, lldb_private::SymbolFile::CompileUnits, DebugAbbrev(), DW_DIE_OFFSET_MAX_BITSIZE, error(), lldb::eSectionTypeDWARFDebugAbbrev, lldb::eSectionTypeDWARFDebugInfo, lldb::eSectionTypeDWARFDebugLine, lldb::eSectionTypeDWARFDebugStr, lldb_private::ObjectFile::eTypeDebugInfo, lldb_private::SectionList::FindSectionByName(), lldb_private::SectionList::FindSectionByType(), lldb_private::SymbolFile::Functions, lldb_private::Section::GetChildren(), GetDWARFMachOSegmentName(), lldb_private::Section::GetFileSize(), GetUnsupportedForms(), lldb_private::SymbolFile::GlobalVariables, lldb_private::SymbolFile::LineTables, lldb_private::SymbolFile::LocalVariables, lldb_private::SymbolFileCommon::m_objfile_sp, and lldb_private::SymbolFile::VariableTypes.
CalculateFrameVariableError()
Status SymbolFileDWARF::CalculateFrameVariableError (StackFrame & frame) override virtual
Subclasses will override this function to for GetFrameVariableError().
This allows GetFrameVariableError() to set the member variable m_debug_info_had_variable_errors correctly without users having to do it manually which is error prone.
Reimplemented from lldb_private::SymbolFile.
Definition at line 4569 of file SymbolFileDWARF.cpp.
References lldb_private::Status::Clone(), lldb_private::SymbolContext::comp_unit, DWARFCompileUnit, lldb_private::plugin::dwarf::DWARFUnit::ExtractUnitDIEIfNeeded(), lldb_private::Status::Fail(), lldb_private::Status::FromErrorString(), GetDWARFCompileUnit(), lldb_private::plugin::dwarf::DWARFUnit::GetDWARFLanguageType(), lldb_private::plugin::dwarf::DWARFUnit::GetDwoError(), GetModuleMutex(), lldb_private::StackFrame::GetSymbolContext(), lldb_private::plugin::dwarf::DWARFUnit::HasAny(), and lldb_private::Status.
CalculateNumCompileUnits()
uint32_t SymbolFileDWARF::CalculateNumCompileUnits () override protected virtual
Implements lldb_private::SymbolFileCommon.
Definition at line 886 of file SymbolFileDWARF.cpp.
References BuildCuTranslationTable(), DebugInfo(), lldb_private::plugin::dwarf::DWARFDebugInfo::GetNumUnits(), and m_lldb_cu_to_dwarf_unit.
ClassContainsSelector()
bool lldb_private::plugin::dwarf::SymbolFileDWARF::ClassContainsSelector (const DWARFDIE & class_die, ConstString selector) protected
References DWARFDIE.
classof()
bool lldb_private::plugin::dwarf::SymbolFileDWARF::classof (const SymbolFile * obj) inline static
Definition at line 76 of file SymbolFileDWARF.h.
References ID, lldb_private::SymbolFile::isA(), and lldb_private::SymbolFile::SymbolFile().
ClassOrStructIsVirtual()
bool SymbolFileDWARF::ClassOrStructIsVirtual (const DWARFDIE & die)
Definition at line 1401 of file SymbolFileDWARF.cpp.
References lldb_private::plugin::dwarf::DWARFDIE::children(), and DWARFDIE.
CollectCallEdges()
std::vector< std::unique_ptr< lldb_private::CallEdge > > SymbolFileDWARF::CollectCallEdges (lldb::ModuleSP module, DWARFDIE function_die) protected
Parse call site entries (DW_TAG_call_site), including any nested call site parameters (DW_TAG_call_site_parameter).
Collect call graph edges present in a function DIE.
Definition at line 4155 of file SymbolFileDWARF.cpp.
References lldb_private::plugin::dwarf::DWARFFormValue::Address(), lldb_private::CallEdge::AfterCall, lldb_private::plugin::dwarf::DWARFAttributes::AttributeAtIndex(), lldb_private::plugin::dwarf::DWARFFormValue::BlockData(), lldb_private::plugin::dwarf::DWARFFormValue::Boolean(), lldb_private::CallEdge::Call, lldb_private::plugin::dwarf::DWARFDIE::children(), CollectCallSiteParameters(), DWARFDIE, lldb::eDescriptionLevelBrief, lldb_private::plugin::dwarf::DWARFAttributes::ExtractFormValueAtIndex(), FixupAddress(), lldb_private::plugin::dwarf::DWARFFormValue::Form(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetAttributeValueAsUnsigned(), lldb_private::GetLog(), lldb_private::plugin::dwarf::DWARFDIE::GetPubname(), lldb_private::StreamString::GetString(), lldb_private::plugin::dwarf::DWARFFormValue::IsBlockForm(), LLDB_INVALID_ADDRESS, LLDB_LOG, lldb_private::plugin::dwarf::DWARFBaseDIE::no, lldb_private::plugin::dwarf::DWARFFormValue::Reference(), lldb_private::plugin::dwarf::DWARFAttributes::Size(), lldb_private::Step, and lldb_private::plugin::dwarf::DWARFFormValue::Unsigned().
Referenced by ParseCallEdgesInFunction().
CompleteType()
bool SymbolFileDWARF::CompleteType (CompilerType & compiler_type) override virtual
Implements lldb_private::SymbolFile.
Definition at line 1564 of file SymbolFileDWARF.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::plugin::dwarf::DWARFASTParser::CompleteTypeFromDWARF(), lldb_private::DebugInfo, lldb_private::plugin::dwarf::DW_TAG_value_to_name(), DWARFASTParser, DWARFDIE, FindDefinitionDIE(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FindDefinitionDIE(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), GetDebugMapSymfile(), lldb_private::plugin::dwarf::DWARFDIE::GetDIE(), GetDIE(), GetDIEToType(), GetDWARFParser(), GetForwardDeclCompilerTypeToDIE(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetID(), lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), GetModuleMutex(), lldb_private::Type::GetName(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::CompilerType::GetOpaqueQualType(), lldb_private::CompilerType::GetTypeSystem(), lldb_private::ClangUtil::RemoveFastQualifiers(), SymbolFileDWARFDebugMap, lldb_private::plugin::dwarf::DWARFBaseDIE::Tag(), and lldb_private::TypeCompletion.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompleteType().
ConstructFunctionDemangledName()
ConstString SymbolFileDWARF::ConstructFunctionDemangledName (const DWARFDIE & die)
Definition at line 943 of file SymbolFileDWARF.cpp.
References ASSERT_MODULE_LOCK, lldb_private::plugin::dwarf::DWARFASTParser::ConstructDemangledNameFromDWARF(), DWARFASTParser, DWARFDIE, lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), GetLanguage(), lldb_private::GetLog(), GetTypeSystemForLanguage(), lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), LLDB_LOG, LLDB_LOG_ERROR, and lldb_private::Symbols.
Referenced by lldb_private::plugin::dwarf::DWARFIndex::ProcessFunctionDIE().
CreateInstance()
SymbolFile * SymbolFileDWARF::CreateInstance (lldb::ObjectFileSP objfile_sp) static
Definition at line 338 of file SymbolFileDWARF.cpp.
References lldb_private::SymbolFile::SymbolFile(), and SymbolFileDWARF().
Referenced by Initialize(), and Terminate().
DebugAbbrev()
llvm::DWARFDebugAbbrev * SymbolFileDWARF::DebugAbbrev ()
Definition at line 708 of file SymbolFileDWARF.cpp.
References lldb_private::DebugInfo, elapsed(), error(), lldb_private::DWARFDataExtractor::GetAsLLVM(), lldb_private::DataExtractor::GetByteSize(), lldb_private::GetLog(), LLDB_LOG_ERROR, m_abbr, m_context, and m_parse_time.
Referenced by CalculateAbilities().
DebuggerInitialize()
void SymbolFileDWARF::DebuggerInitialize (Debugger & debugger) static
Definition at line 318 of file SymbolFileDWARF.cpp.
References lldb_private::PluginManager::CreateSettingForSymbolFilePlugin(), GetGlobalPluginProperties(), and lldb_private::PluginManager::GetSettingForSymbolFilePlugin().
Referenced by Initialize().
DebugInfo()
DWARFDebugInfo & SymbolFileDWARF::DebugInfo ()
Definition at line 731 of file SymbolFileDWARF.cpp.
References LLDB_SCOPED_TIMER, m_context, m_info, and m_info_once_flag.
Referenced by BuildCuTranslationTable(), CalculateNumCompileUnits(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::FindSingleCompileUnit(), GetDebugInfoSize(), GetDIE(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetDIE(), GetDIERefSymbolFile(), GetDWARFCompileUnit(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetDWOCompileUnitForHash(), GetDwoStats(), lldb_private::plugin::dwarf::DebugNamesDWARFIndex::GetForeignTypeUnit(), GetMangledNamesForFunction(), GetSeparateDebugInfo(), GetSkeletonUnit(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexImpl(), ParseCompileUnitAtIndex(), ParseVariablesForContext(), and UpdateExternalModuleListIfNeeded().
DeclContextMatchesThisSymbolFile()
bool SymbolFileDWARF::DeclContextMatchesThisSymbolFile (const CompilerDeclContext & decl_ctx) protected
Definition at line 2283 of file SymbolFileDWARF.cpp.
References lldb_private::GetLog(), lldb_private::TypeSystem::GetMinimumLanguage(), lldb_private::ModuleChild::GetModule(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::CompilerDeclContext::GetTypeSystem(), GetTypeSystemForLanguage(), lldb_private::CompilerDeclContext::IsValid(), LLDB_LOG_ERROR, lldb_private::Lookups, and lldb_private::Symbols.
Referenced by FindFunctions(), FindGlobalVariables(), and FindNamespace().
DIEInDeclContext()
bool SymbolFileDWARF::DIEInDeclContext (const CompilerDeclContext & parent_decl_ctx, const DWARFDIE & die, bool only_root_namespaces = false) static
Definition at line 2660 of file SymbolFileDWARF.cpp.
References DWARFASTParser, DWARFDIE, lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), GetDWARFParser(), lldb_private::plugin::dwarf::DWARFDIE::GetParent(), lldb_private::CompilerDeclContext::IsContainedInLookup(), lldb_private::CompilerDeclContext::IsValid(), and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
Referenced by FindNamespace(), lldb_private::plugin::dwarf::ManualDWARFIndex::GetFunctions(), lldb_private::plugin::dwarf::DWARFIndex::ProcessFunctionDIE(), and lldb_private::plugin::dwarf::DWARFIndex::ProcessNamespaceDieMatchParents().
Dump()
void SymbolFileDWARF::Dump (lldb_private::Stream & s) override virtual
Reimplemented from lldb_private::SymbolFileCommon.
Definition at line 4324 of file SymbolFileDWARF.cpp.
References lldb_private::SymbolFileCommon::Dump(), and m_index.
DumpClangAST()
void SymbolFileDWARF::DumpClangAST (Stream & s, llvm::StringRef filter, bool show_colors) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 4329 of file SymbolFileDWARF.cpp.
References lldb_private::Stream::AsRawOstream(), lldb::eLanguageTypeC_plus_plus, and GetTypeSystemForLanguage().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::DumpClangAST().
FindBlockContainingSpecification() [1/2]
DWARFDIE SymbolFileDWARF::FindBlockContainingSpecification (const DIERef & func_die_ref, dw_offset_t spec_block_die_offset) protected
Definition at line 3835 of file SymbolFileDWARF.cpp.
References FindBlockContainingSpecification(), and GetDIE().
Referenced by FindBlockContainingSpecification(), FindBlockContainingSpecification(), and ParseVariablesInFunctionContextRecursive().
FindBlockContainingSpecification() [2/2]
DWARFDIE SymbolFileDWARF::FindBlockContainingSpecification (const DWARFDIE & die, dw_offset_t spec_block_die_offset) protected
Definition at line 3845 of file SymbolFileDWARF.cpp.
References lldb_private::plugin::dwarf::DWARFDIE::children(), DWARFDIE, FindBlockContainingSpecification(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetOffset(), lldb_private::plugin::dwarf::DWARFDIE::GetReferencedDIE(), and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
FindCompleteObjCDefinitionTypeForDIE()
TypeSP SymbolFileDWARF::FindCompleteObjCDefinitionTypeForDIE (const DWARFDIE & die, ConstString type_name, bool must_be_implementation) virtual
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 3115 of file SymbolFileDWARF.cpp.
References lldb_private::Continue, DEBUG_PRINTF, DIE_IS_BEING_PARSED, DWARFDIE, lldb_private::plugin::dwarf::DWARFBaseDIE::GetAttributeValueAsUnsigned(), lldb_private::plugin::dwarf::DWARFDIE::GetDIE(), GetDIEToType(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetID(), GetObjCClassSymbol(), IsStructOrClassTag(), m_index, lldb_private::SymbolFileCommon::m_objfile_sp, ResolveType(), lldb_private::Stop, and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FindCompleteObjCDefinitionTypeForDIE(), and lldb_private::plugin::dwarf::SymbolFileDWARFDwo::FindCompleteObjCDefinitionTypeForDIE().
FindDefinitionDIE()
DWARFDIE SymbolFileDWARF::FindDefinitionDIE (const DWARFDIE & die) virtual
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 3157 of file SymbolFileDWARF.cpp.
References lldb_private::plugin::dwarf::DWARFDeclContext::AppendDeclContext(), lldb_private::Continue, lldb_private::plugin::dwarf::DW_TAG_value_to_name(), DWARFASTParser, DWARFDIE, lldb::eLanguageTypeUnknown, lldb_private::plugin::dwarf::DWARFBaseDIE::GetAttributeValueAsUnsigned(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), lldb_private::plugin::dwarf::DWARFASTParser::GetDIEClassTemplateParams(), lldb_private::plugin::dwarf::DWARFDIE::GetDWARFDeclContext(), GetLanguage(), lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), lldb_private::plugin::dwarf::DWARFDIE::GetName(), lldb_private::Language::GetNameForLanguageType(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetOffset(), lldb_private::plugin::dwarf::DWARFDeclContext::GetQualifiedName(), GetTypeSystemForLanguage(), IsStructOrClassTag(), LLDB_LOG_ERROR, lldb_private::Lookups, m_index, lldb_private::Stop, lldb_private::Symbols, lldb_private::plugin::dwarf::DWARFBaseDIE::Tag(), and lldb_private::TypeCompletion.
Referenced by CompleteType(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FindDefinitionDIE(), and lldb_private::plugin::dwarf::SymbolFileDWARFDwo::FindDefinitionDIE().
FindDwpSymbolFile()
void lldb_private::plugin::dwarf::SymbolFileDWARF::FindDwpSymbolFile () protected
FindFunctionDefinition()
llvm::Expected< DWARFDIE > SymbolFileDWARF::FindFunctionDefinition (const FunctionCallLabel & label, const DWARFDIE & declaration) private
Find the definition DIE for the specified label in this SymbolFile.
Returns
A valid definition DIE on success.
Definition at line 2545 of file SymbolFileDWARF.cpp.
References lldb_private::Continue, lldb_private::FunctionCallLabel::discriminator, DWARFDIE, lldb::eLanguageTypeUnknown, lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), lldb_private::FunctionCallLabel::lookup_name, m_index, lldb_private::Module::LookupInfo::MakeLookupInfos(), lldb_private::Stop, and lldb_private::CPlusPlusLanguage::SubstituteStructorAliases_ItaniumMangle().
Referenced by ResolveFunctionCallLabel().
FindFunctions() [1/2]
void SymbolFileDWARF::FindFunctions (const Module::LookupInfo & lookup_info, const CompilerDeclContext & parent_decl_ctx, bool include_inlines, SymbolContextList & sc_list) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 2685 of file SymbolFileDWARF.cpp.
References lldb_private::Continue, DeclContextMatchesThisSymbolFile(), DWARFDIE, lldb_private::ConstString::GetCString(), lldb_private::plugin::dwarf::DWARFDIE::GetDIE(), lldb_private::GetLog(), lldb_private::Module::LookupInfo::GetLookupName(), lldb_private::ModuleChild::GetModule(), GetModuleMutex(), lldb_private::Module::LookupInfo::GetNameTypeMask(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::SymbolContextList::GetSize(), lldb_private::ConstString::GetStringRef(), lldb_private::ConstString::IsEmpty(), lldb_private::Lookups, m_index, and ResolveFunction().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FindFunctions(), and lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FindFunctions().
FindFunctions() [2/2]
void SymbolFileDWARF::FindFunctions (const RegularExpression & regex, bool include_inlines, SymbolContextList & sc_list) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 2758 of file SymbolFileDWARF.cpp.
References lldb_private::Continue, DWARFDIE, lldb_private::plugin::dwarf::DWARFDIE::GetDIE(), lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), GetModuleMutex(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::RegularExpression::GetText(), LLDB_SCOPED_TIMERF, lldb_private::Lookups, m_index, and ResolveFunction().
FindGlobalVariables() [1/2]
void SymbolFileDWARF::FindGlobalVariables (const RegularExpression & regex, uint32_t max_matches, VariableList & variables) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 2405 of file SymbolFileDWARF.cpp.
References lldb_private::SymbolContext::comp_unit, lldb_private::Continue, DWARFCompileUnit, DWARFDIE, GetCompUnitForDWARFCompUnit(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), GetModuleMutex(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::VariableList::GetSize(), lldb_private::RegularExpression::GetText(), lldb_private::Lookups, m_index, lldb_private::SymbolFileCommon::m_objfile_sp, lldb_private::SymbolContext::module_sp, ParseAndAppendGlobalVariable(), and lldb_private::Stop.
FindGlobalVariables() [2/2]
void SymbolFileDWARF::FindGlobalVariables (ConstString name, const CompilerDeclContext & parent_decl_ctx, uint32_t max_matches, VariableList & variables) override virtual
If the actual namespace is inline (i.e., had a DW_AT_export_symbols) and a child (possibly through other layers of inline namespaces) of the namespace referred to by 'basename', allow the lookup to succeed.
Reimplemented from lldb_private::SymbolFile.
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 2314 of file SymbolFileDWARF.cpp.
References lldb_private::SymbolContext::comp_unit, lldb_private::Continue, DeclContextMatchesThisSymbolFile(), DWARFASTParser, DWARFDIE, lldb_private::Mangled::eManglingSchemeNone, lldb_private::CPlusPlusLanguage::ExtractContextAndIdentifier(), GetCompUnitForDWARFCompUnit(), lldb_private::ConstString::GetCString(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), GetDWARFParser(), lldb_private::GetLog(), lldb_private::Mangled::GetManglingScheme(), lldb_private::ModuleChild::GetModule(), GetModuleMutex(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::VariableList::GetSize(), lldb_private::ConstString::GetStringRef(), lldb_private::VariableList::GetVariableAtIndex(), lldb_private::CompilerDeclContext::IsContainedInLookup(), lldb_private::Lookups, m_index, lldb_private::SymbolFileCommon::m_objfile_sp, lldb_private::SymbolContext::module_sp, ParseAndAppendGlobalVariable(), lldb_private::VariableList::RemoveVariableAtIndex(), lldb_private::Stop, and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FindGlobalVariables(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FindGlobalVariables(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::FindGlobalVariables(), and lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::PrivateFindGlobalVariables().
FindNamespace()
CompilerDeclContext SymbolFileDWARF::FindNamespace (ConstString name, const CompilerDeclContext & parent_decl_ctx, bool only_root_namespaces) override virtual
Finds a namespace of name name and whose parent context is parent_decl_ctx.
If
!parent_decl_ctx.IsValid()
then this function will consider all namespaces that match the name. If only_root_namespaces is true, only consider in the search those DIEs that represent top-level namespaces.
Reimplemented from lldb_private::SymbolFile.
Definition at line 2969 of file SymbolFileDWARF.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::Continue, DeclContextMatchesThisSymbolFile(), DIEInDeclContext(), DWARFASTParser, DWARFDIE, lldb_private::ConstString::GetCString(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), lldb_private::plugin::dwarf::DWARFASTParser::GetDeclContextForUIDFromDWARF(), GetDWARFParser(), lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), GetModuleMutex(), lldb_private::CompilerDeclContext::GetName(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::CompilerDeclContext::GetOpaqueDeclContext(), lldb_private::CompilerDeclContext::GetTypeSystem(), lldb_private::CompilerDeclContext::IsValid(), lldb_private::Lookups, m_index, and lldb_private::Stop.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FindNamespace().
FindTypes()
void SymbolFileDWARF::FindTypes (const lldb_private::TypeQuery & query, lldb_private::TypeResults & results) override virtual
Find types using a type-matching object that contains all search parameters.
See also
lldb_private::TypeQuery
Parameters
[in] query A type matching object that contains all of the details of the type search.
[in] results Any matching types will be populated into the results object using TypeMap::InsertUnique(...).
Reimplemented from lldb_private::SymbolFile.
Definition at line 2855 of file SymbolFileDWARF.cpp.
References lldb_private::TypeResults::AlreadySearched(), lldb_private::TypeQuery::ContextMatches(), lldb_private::Continue, lldb_private::TypeResults::Done(), DWARFDIE, lldb_private::plugin::dwarf::DWARFDIE::GetDeclContext(), lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), GetModuleMutex(), lldb_private::TypeQuery::GetModuleSearch(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::TypeQuery::GetSearchByMangledName(), lldb_private::TypeMap::GetSize(), lldb_private::TypeQuery::GetTypeBasename(), lldb_private::plugin::dwarf::DWARFDIE::GetTypeLookupContext(), lldb_private::TypeResults::GetTypeMap(), lldb_private::TypeResults::InsertUnique(), lldb_private::Lookups, m_external_type_modules, m_index, ResolveType(), lldb_private::Stop, UpdateCompilerContextForSimpleTemplateNames(), and UpdateExternalModuleListIfNeeded().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FindTypes().
FixupAddress() [1/2]
bool SymbolFileDWARF::FixupAddress (Address & addr) protected
Definition at line 975 of file SymbolFileDWARF.cpp.
References GetDebugMapSymfile(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::LinkOSOAddress(), and SymbolFileDWARFDebugMap.
FixupAddress() [2/2]
lldb::addr_t SymbolFileDWARF::FixupAddress (lldb::addr_t file_addr) protected
If this symbol file is linked to by a debug map (see SymbolFileDWARFDebugMap), and file_addr is a file address relative to an object file, adjust file_addr so that it is relative to the main binary.
Returns the adjusted address, or file_addr if no adjustment is needed, on success and LLDB_INVALID_ADDRESS otherwise.
Definition at line 968 of file SymbolFileDWARF.cpp.
References GetDebugMapSymfile(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::LinkOSOFileAddress(), and SymbolFileDWARFDebugMap.
Referenced by CollectCallEdges(), and ParseFunction().
ForEachExternalModule()
bool SymbolFileDWARF::ForEachExternalModule (CompileUnit & , llvm::DenseSet< SymbolFile * > & , llvm::function_ref< bool(Module &)>) override
Definition at line 1048 of file SymbolFileDWARF.cpp.
References m_external_type_modules, and UpdateExternalModuleListIfNeeded().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ForEachExternalModule().
GetCompileOptions()
void SymbolFileDWARF::GetCompileOptions (std::unordered_map< lldb::CompUnitSP, Args > & args) override protected
Definition at line 4602 of file SymbolFileDWARF.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::GetAttributeValueAsString(), lldb_private::SymbolFileCommon::GetCompileUnitAtIndex(), GetDWARFCompileUnit(), lldb_private::SymbolFileCommon::GetNumCompileUnits(), and lldb_private::plugin::dwarf::DWARFUnit::GetUnitDIEOnly().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetCompileOptions().
GetCompilerContextForUID()
std::vector< CompilerContext > SymbolFileDWARF::GetCompilerContextForUID (lldb::user_id_t uid) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 1470 of file SymbolFileDWARF.cpp.
References DWARFDIE, GetDIE(), and GetModuleMutex().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetCompilerContextForUID().
GetCompUnitForDWARFCompUnit()
CompileUnit * SymbolFileDWARF::GetCompUnitForDWARFCompUnit (DWARFCompileUnit & dwarf_cu)
Definition at line 1649 of file SymbolFileDWARF.cpp.
References DWARFCompileUnit, GetCompUnitForDWARFCompUnit(), lldb_private::plugin::dwarf::DWARFUnit::GetLLDBCompUnit(), lldb_private::plugin::dwarf::DWARFUnit::GetSkeletonUnit(), lldb_private::plugin::dwarf::DWARFUnit::GetSymbolFileDWARF(), lldb_private::plugin::dwarf::DWARFUnit::IsDWOUnit(), and ParseCompileUnit().
Referenced by FindGlobalVariables(), FindGlobalVariables(), GetCompUnitForDWARFCompUnit(), GetFile(), GetFunction(), and GetTypeForDIE().
GetContainingDeclContext()
CompilerDeclContext SymbolFileDWARF::GetContainingDeclContext (const DWARFDIE & die) static
Definition at line 4526 of file SymbolFileDWARF.cpp.
References DWARFASTParser, DWARFDIE, lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), and GetDWARFParser().
Referenced by GetDeclContextContainingUID().
GetDebugInfoIndexTime()
StatsDuration::Duration SymbolFileDWARF::GetDebugInfoIndexTime () override virtual
Return the time it took to index the debug information in the object file.
Returns
0.0 if the file doesn't need to be indexed or if it hasn't been indexed yet, or a valid duration if it has.
Reimplemented from lldb_private::SymbolFile.
Definition at line 4557 of file SymbolFileDWARF.cpp.
References m_index.
GetDebugInfoParseTime()
StatsDuration::Duration lldb_private::plugin::dwarf::SymbolFileDWARF::GetDebugInfoParseTime () inline override virtual
Return the time taken to parse the debug information.
Returns
0.0 if no information has been parsed or if there is no computational cost to parsing the debug information.
Reimplemented from lldb_private::SymbolFile.
Definition at line 317 of file SymbolFileDWARF.h.
References m_parse_time.
GetDebugInfoParseTimeRef()
StatsDuration & lldb_private::plugin::dwarf::SymbolFileDWARF::GetDebugInfoParseTimeRef () inline
Definition at line 322 of file SymbolFileDWARF.h.
References m_parse_time.
GetDebugInfoSize()
uint64_t SymbolFileDWARF::GetDebugInfoSize (bool load_all_debug_info = false) override virtual
Metrics gathering functions.
Return the size in bytes of all loaded debug information or total possible debug info in the symbol file.
If the debug information is contained in sections of an ObjectFile, then this call should add the size of all sections that contain debug information. Symbols the symbol tables are not considered debug information for this call to make it easy and quick for this number to be calculated. If the symbol file is all debug information, the size of the entire file should be returned. The default implementation of this function will iterate over all sections in a module and add up their debug info only section byte sizes.
Parameters
load_all_debug_info If true, force loading any symbol files if they are not yet loaded and add to the total size. Default to false.
Returns
Total currently loaded debug info size in bytes
Reimplemented from lldb_private::SymbolFileCommon.
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 2833 of file SymbolFileDWARF.cpp.
References DebugInfo(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetDebugInfoSize(), lldb_private::SymbolFileCommon::GetDebugInfoSize(), lldb_private::plugin::dwarf::DWARFUnit::GetDwoSymbolFile(), GetDwpSymbolFile(), lldb_private::plugin::dwarf::DWARFDebugInfo::GetNumUnits(), lldb_private::plugin::dwarf::DWARFDebugInfo::GetUnitAtIndex(), and SymbolFileDWARFDwo.
GetDebugMapSymfile()
SymbolFileDWARFDebugMap * SymbolFileDWARF::GetDebugMapSymfile ()
Definition at line 4408 of file SymbolFileDWARF.cpp.
References m_debug_map_module_wp, m_debug_map_symfile, and SymbolFileDWARFDebugMap.
Referenced by CompleteType(), FixupAddress(), FixupAddress(), GetDIERefSymbolFile(), GetDIEToType(), GetDwoSymbolFileForCompileUnit(), GetForwardDeclCompilerTypeToDIE(), GetTypeList(), GetTypeSystemForLanguage(), GetUniqueDWARFASTTypeMap(), ParseCompileUnit(), ParseLineTable(), and ParseVariableDIE().
GetDecl()
CompilerDecl SymbolFileDWARF::GetDecl (const DWARFDIE & die) static
Definition at line 4513 of file SymbolFileDWARF.cpp.
References DWARFASTParser, DWARFDIE, lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), and GetDWARFParser().
Referenced by DWARFASTParserClang::GetClangDeclForDIE(), and GetDeclForUID().
GetDeclContext()
CompilerDeclContext SymbolFileDWARF::GetDeclContext (const DWARFDIE & die) static
Definition at line 4519 of file SymbolFileDWARF.cpp.
References DWARFASTParser, DWARFDIE, lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), and GetDWARFParser().
Referenced by DWARFASTParserClang::GetClangDeclForDIE(), and GetDeclContextForUID().
GetDeclContextContainingUID()
CompilerDeclContext SymbolFileDWARF::GetDeclContextContainingUID (lldb::user_id_t uid) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 1459 of file SymbolFileDWARF.cpp.
References DWARFDIE, GetContainingDeclContext(), GetDIE(), and GetModuleMutex().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetDeclContextContainingUID().
GetDeclContextDIEContainingDIE()
DWARFDIE SymbolFileDWARF::GetDeclContextDIEContainingDIE (const DWARFDIE & die)
Definition at line 3049 of file SymbolFileDWARF.cpp.
References DWARFDIE, GetDeclContextDIEContainingDIE(), lldb_private::plugin::dwarf::DWARFDIE::GetParent(), lldb_private::plugin::dwarf::DWARFDIE::GetReferencedDIE(), and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
Referenced by GetDeclContextDIEContainingDIE(), ParseVariableDIE(), and ResolveTypeUID().
GetDeclContextForUID()
CompilerDeclContext SymbolFileDWARF::GetDeclContextForUID (lldb::user_id_t uid) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 1446 of file SymbolFileDWARF.cpp.
References DWARFDIE, GetDeclContext(), GetDIE(), and GetModuleMutex().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetDeclContextForUID(), and ParseType().
GetDeclForUID()
CompilerDecl SymbolFileDWARF::GetDeclForUID (lldb::user_id_t uid) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 1433 of file SymbolFileDWARF.cpp.
References DWARFDIE, GetDecl(), GetDIE(), and GetModuleMutex().
GetDIE() [1/2]
DWARFDIE SymbolFileDWARF::GetDIE (const DIERef & die_ref) virtual
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 1735 of file SymbolFileDWARF.cpp.
References DebugInfo(), lldb_private::plugin::dwarf::DIERef::die_offset(), DW_INVALID_OFFSET, DWARFDIE, lldb_private::plugin::dwarf::DWARFDebugInfo::GetDIE(), GetDIERefSymbolFile(), GetModuleMutex(), lldb_private::plugin::dwarf::DIERef::section(), and SymbolFileDWARF().
Referenced by CompleteType(), FindBlockContainingSpecification(), GetCompilerContextForUID(), GetDeclContextContainingUID(), GetDeclContextForUID(), GetDeclForUID(), GetDIE(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetDIE(), GetDynamicArrayInfoForUID(), GetMangledNamesForFunction(), MergeBlockAbstractParameters(), ParseCallEdgesInFunction(), ParseVariablesForContext(), ParseVariablesInFunctionContextRecursive(), PopulateBlockVariableList(), ResolveFunctionCallLabel(), ResolveTypeUID(), and ResolveTypeUID().
GetDIE() [2/2]
DWARFDIE SymbolFileDWARF::GetDIE (lldb::user_id_t uid)
Definition at line 1431 of file SymbolFileDWARF.cpp.
References GetDIE().
GetDIERefSymbolFile()
SymbolFileDWARF * SymbolFileDWARF::GetDIERefSymbolFile (const DIERef & die_ref) virtual
Given a DIERef, find the correct SymbolFileDWARF.
A DIERef contains a file index that can uniquely identify a N_OSO file for DWARF in .o files on mac, or a .dwo or .dwp file index for split DWARF. Calling this function will find the correct symbol file to use so that further lookups can be done on the correct symbol file so that the DIE offset makes sense in the DIERef.
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 1701 of file SymbolFileDWARF.cpp.
References DebugInfo(), lldb_private::plugin::dwarf::DIERef::file_index(), GetDebugMapSymfile(), lldb_private::plugin::dwarf::DWARFUnit::GetDwoSymbolFile(), GetDwpSymbolFile(), GetFileIndex(), lldb_private::plugin::dwarf::DWARFDebugInfo::GetUnitAtIndex(), lldb_private::plugin::dwarf::DIERef::k_file_index_mask, SymbolFileDWARF(), and SymbolFileDWARFDebugMap.
Referenced by GetDIE(), and lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetDIERefSymbolFile().
GetDIEToType()
llvm::DenseMap< const DWARFDebugInfoEntry *, Type * > & SymbolFileDWARF::GetDIEToType () virtual
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 496 of file SymbolFileDWARF.cpp.
References GetDebugMapSymfile(), m_die_to_type, and SymbolFileDWARFDebugMap.
Referenced by CompleteType(), DWARFASTParserClang::CopyUniqueClassMethodTypes(), FindCompleteObjCDefinitionTypeForDIE(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetDIEToType(), and GetTypeForDIE().
GetDIEToVariable()
virtual DIEToVariableSP & lldb_private::plugin::dwarf::SymbolFileDWARF::GetDIEToVariable () inline virtual
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 356 of file SymbolFileDWARF.h.
References m_die_to_variable_sp.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetDIEToVariable(), ParseAndAppendGlobalVariable(), and ParseVariableDIECached().
GetDWARFCompileUnit()
DWARFCompileUnit * SymbolFileDWARF::GetDWARFCompileUnit (CompileUnit * comp_unit) protected virtual
Definition at line 740 of file SymbolFileDWARF.cpp.
References DebugInfo(), DWARFCompileUnit, lldb_private::UserID::GetID(), lldb_private::plugin::dwarf::DWARFUnit::GetLLDBCompUnit(), lldb_private::plugin::dwarf::DWARFDebugInfo::GetUnitAtIndex(), and lldb_private::plugin::dwarf::DWARFUnit::SetLLDBCompUnit().
Referenced by CalculateFrameVariableError(), GetCompileOptions(), GetDWOId(), ParseBlocksRecursive(), ParseDebugMacros(), ParseFunctions(), ParseImportedModules(), ParseIsOptimized(), ParseLanguage(), ParseLineTable(), ParseSupportFiles(), ParseTypes(), ParseXcodeSDK(), and ResolveFunctionAndBlock().
GetDWARFContext()
DWARFContext & lldb_private::plugin::dwarf::SymbolFileDWARF::GetDWARFContext () inline
Definition at line 293 of file SymbolFileDWARF.h.
References m_context.
Referenced by lldb_private::plugin::dwarf::DWARFFormValue::Address(), lldb_private::plugin::dwarf::DWARFUnit::GetLocationData(), lldb_private::plugin::dwarf::DWARFUnit::GetRnglistData(), and lldb_private::plugin::dwarf::DWARFUnit::SetDwoStrOffsetsBase().
GetDWARFParser()
DWARFASTParser * SymbolFileDWARF::GetDWARFParser (DWARFUnit & unit) static
Definition at line 4501 of file SymbolFileDWARF.cpp.
References DWARFASTParser, lldb_private::GetLog(), GetTypeSystem(), LLDB_LOG_ERROR, and lldb_private::Symbols.
Referenced by CompleteType(), DWARFASTParserClang::CopyUniqueClassMethodTypes(), DIEInDeclContext(), FindGlobalVariables(), FindNamespace(), GetContainingDeclContext(), GetDecl(), and GetDeclContext().
GetDWARFUnitIndex()
std::optional< uint32_t > SymbolFileDWARF::GetDWARFUnitIndex (uint32_t cu_idx) protected
Definition at line 877 of file SymbolFileDWARF.cpp.
References BuildCuTranslationTable(), and m_lldb_cu_to_dwarf_unit.
Referenced by ParseCompileUnit(), and ParseCompileUnitAtIndex().
GetDWOId()
std::optional< uint64_t > SymbolFileDWARF::GetDWOId ()
If this is a DWARF object with a single CU, return its DW_AT_dwo_id.
Definition at line 1759 of file SymbolFileDWARF.cpp.
References DWARFCompileUnit, lldb_private::SymbolFileCommon::GetCompileUnitAtIndex(), GetDWARFCompileUnit(), and lldb_private::SymbolFileCommon::GetNumCompileUnits().
Referenced by UpdateExternalModuleListIfNeeded().
GetDwoStats()
DWOStats SymbolFileDWARF::GetDwoStats () override virtual
Gets statistics about dwo files associated with this symbol file.
For split-dwarf files, this reports the counts for successfully loaded DWO CUs, total DWO CUs, and the number of DWO CUs with loading errors. For non-split-dwarf files, this reports 0 for all.
Reimplemented from lldb_private::SymbolFile.
Definition at line 4628 of file SymbolFileDWARF.cpp.
References DebugInfo(), lldb_private::DWOStats::dwo_error_count, lldb_private::DWOStats::dwo_file_count, lldb_private::Status::Fail(), lldb_private::plugin::dwarf::DWARFUnit::GetDwoError(), lldb_private::plugin::dwarf::DWARFUnit::GetDWOId(), lldb_private::plugin::dwarf::DWARFUnit::GetDwoSymbolFile(), lldb_private::plugin::dwarf::DWARFDebugInfo::GetNumUnits(), lldb_private::plugin::dwarf::DWARFDebugInfo::GetUnitAtIndex(), lldb_private::DWOStats::loaded_dwo_file_count, and lldb_private::SymbolFile::SymbolFile().
GetDwoSymbolFileForCompileUnit()
std::shared_ptr< SymbolFileDWARFDwo > SymbolFileDWARF::GetDwoSymbolFileForCompileUnit (DWARFUnit & dwarf_cu, const DWARFDebugInfoEntry & cu_die)
Definition at line 1774 of file SymbolFileDWARF.cpp.
References lldb_private::FileSpecList::Append(), lldb_private::FileSpec::AppendPathComponent(), DWARFCompileUnit, lldb_private::FileSystem::Exists(), lldb_private::ObjectFile::FindPlugin(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::plugin::dwarf::DWARFDebugInfoEntry::GetAttributeValueAsString(), GetDebugMapSymfile(), lldb_private::Target::GetDefaultDebugFileSearchPaths(), lldb_private::plugin::dwarf::DWARFUnit::GetDWOId(), GetDWOName(), GetDwpSymbolFile(), lldb_private::FileSpec::GetFilename(), lldb_private::FileSpecList::GetFileSpecAtIndex(), lldb_private::UserID::GetID(), lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::plugin::dwarf::DWARFDebugInfoEntry::GetOffset(), lldb_private::FileSpec::GetPath(), lldb_private::FileSpecList::GetSize(), lldb_private::FileSystem::Instance(), lldb_private::FileSpec::IsRelative(), LLDB_LOGF, m_dwo_warning_issued, lldb_private::SymbolFileCommon::m_objfile_sp, lldb_private::FileSpec::PrependPathComponent(), lldb_private::FileSystem::Resolve(), lldb_private::plugin::dwarf::DWARFUnit::SetDwoError(), lldb_private::FileSpec::SetFile(), and lldb_private::Symbols.
GetDwpSymbolFile()
const std::shared_ptr< SymbolFileDWARFDwo > & SymbolFileDWARF::GetDwpSymbolFile ()
Definition at line 4419 of file SymbolFileDWARF.cpp.
References lldb_private::FileSpecList::Append(), lldb_private::FileSpecList::files(), lldb_private::ObjectFile::FindPlugin(), lldb_private::Target::GetDefaultDebugFileSearchPaths(), lldb_private::FileSpec::GetFilename(), lldb_private::FileSpec::GetFileNameStrippingExtension(), lldb_private::ModuleSpec::GetFileSpec(), lldb_private::GetLog(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::ModuleSpec::GetSymbolFileSpec(), lldb_private::ModuleSpec::GetUUID(), lldb_private::FileSystem::Instance(), lldb_private::plugin::dwarf::DIERef::k_file_index_mask, LLDB_LOG, lldb_private::PluginManager::LocateExecutableSymbolFile(), m_dwp_symfile, m_dwp_symfile_once_flag, lldb_private::SymbolFileCommon::m_objfile_sp, lldb_private::FileSpec::SetFilename(), and lldb_private::SplitDwarf.
Referenced by GetDebugInfoSize(), GetDIERefSymbolFile(), and GetDwoSymbolFileForCompileUnit().
GetDynamicArrayInfoForUID()
std::optional< SymbolFile::ArrayInfo > SymbolFileDWARF::GetDynamicArrayInfoForUID (lldb::user_id_t type_uid, const ExecutionContext * exe_ctx) override virtual
If type_uid points to an array type, return its characteristics.
To support variable-length array types, this function takes an optional ExecutionContext. If exe_ctx is non-null, the dynamic characteristics for that context are returned.
Implements lldb_private::SymbolFile.
Definition at line 1491 of file SymbolFileDWARF.cpp.
References DWARFDIE, GetDIE(), GetModuleMutex(), and lldb_private::plugin::dwarf::DWARFASTParser::ParseChildArrayInfo().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetDynamicArrayInfoForUID().
GetExternalModule()
lldb::ModuleSP SymbolFileDWARF::GetExternalModule (ConstString name)
Definition at line 1693 of file SymbolFileDWARF.cpp.
References m_external_type_modules, and UpdateExternalModuleListIfNeeded().
Referenced by GetContainingClangModule().
getExternalTypeModules()
const ExternalTypeModuleMap & lldb_private::plugin::dwarf::SymbolFileDWARF::getExternalTypeModules () const inline
Return the list of Clang modules imported by this SymbolFile.
Definition at line 236 of file SymbolFileDWARF.h.
References m_external_type_modules.
GetFile()
FileSpec SymbolFileDWARF::GetFile (DWARFUnit & unit, size_t file_idx)
Definition at line 1109 of file SymbolFileDWARF.cpp.
References GetCompUnitForDWARFCompUnit(), lldb_private::SupportFileList::GetFileSpecAtIndex(), and GetTypeUnitSupportFiles().
GetFileIndex()
std::optional< uint64_t > lldb_private::plugin::dwarf::SymbolFileDWARF::GetFileIndex () const inline
Definition at line 343 of file SymbolFileDWARF.h.
References m_file_index.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::AddOSOARanges(), lldb_private::plugin::dwarf::NameToDIE::FindAllEntriesForUnit(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetDIE(), and GetDIERefSymbolFile().
GetForwardDeclCompilerTypeToDIE()
llvm::DenseMap< lldb::opaque_compiler_type_t, DIERef > & SymbolFileDWARF::GetForwardDeclCompilerTypeToDIE () virtual
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 503 of file SymbolFileDWARF.cpp.
References GetDebugMapSymfile(), m_forward_decl_compiler_type_to_die, and SymbolFileDWARFDebugMap.
Referenced by CompleteType(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetForwardDeclCompilerTypeToDIE(), and HasForwardDeclForCompilerType().
GetFunction()
bool SymbolFileDWARF::GetFunction (const DWARFDIE & die, SymbolContext & sc) protected
Definition at line 1672 of file SymbolFileDWARF.cpp.
References lldb_private::Function::CalculateSymbolContextModule(), lldb_private::SymbolContext::Clear(), lldb_private::SymbolContext::comp_unit, DWARFDIE, lldb_private::CompileUnit::FindFunctionByUID(), lldb_private::SymbolContext::function, GetCompUnitForDWARFCompUnit(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetID(), lldb_private::SymbolContext::module_sp, and ParseFunction().
Referenced by GetTypeForDIE(), and ResolveFunction().
GetGlobalAranges()
SymbolFileDWARF::GlobalVariableMap & SymbolFileDWARF::GetGlobalAranges () protected
Definition at line 2055 of file SymbolFileDWARF.cpp.
References lldb_private::DWARFExpressionList::Evaluate(), lldb_private::Value::FileAddress, lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), lldb_private::SymbolFileCommon::GetObjectFile(), LLDB_INVALID_ADDRESS, LLDB_LOG_ERROR, m_global_aranges_up, and lldb_private::Symbols.
getIndex()
DWARFIndex * lldb_private::plugin::dwarf::SymbolFileDWARF::getIndex () inline
Returns the DWARFIndex for this symbol, if it exists.
Definition at line 376 of file SymbolFileDWARF.h.
References m_index.
GetLanguage()
LanguageType SymbolFileDWARF::GetLanguage (DWARFUnit & unit) static
Definition at line 4546 of file SymbolFileDWARF.cpp.
References lldb_private::plugin::dwarf::DWARFUnit::GetDWARFLanguageType(), and LanguageTypeFromDWARF().
Referenced by ConstructFunctionDemangledName(), FindDefinitionDIE(), GetTypeSystem(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexUnit(), IsSizeAndDeclarationMatching(), DWARFASTParserClang::MapDeclDIEToDefDIE(), ParseFunction(), DWARFASTParserClang::ParseFunctionFromDWARF(), ParseLanguage(), DWARFASTParserClang::ParseRustVariantPart(), DWARFASTParserClang::ParseStructureLikeDIE(), ParseType(), DWARFASTParserClang::ParseTypeModifier(), and ParseVariableDIE().
GetLanguageFamily()
LanguageType SymbolFileDWARF::GetLanguageFamily (DWARFUnit & unit) static
Same as GetLanguage() but reports all C++ versions as C++ (no version).
Definition at line 4550 of file SymbolFileDWARF.cpp.
References lldb_private::plugin::dwarf::DWARFUnit::GetDWARFLanguageType(), and LanguageTypeFromDWARF().
Referenced by DWARFASTParserClang::ParseTypeFromClangModule(), and lldb_private::plugin::dwarf::DWARFIndex::ProcessTypeDIEMatchQuery().
GetMangledNamesForFunction()
void SymbolFileDWARF::GetMangledNamesForFunction (const std::string & scope_qualified_name, std::vector< ConstString > & mangled_names) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 2781 of file SymbolFileDWARF.cpp.
References DebugInfo(), DWARFDIE, GetDIE(), lldb_private::plugin::dwarf::DWARFUnit::GetDwoSymbolFile(), lldb_private::plugin::dwarf::DWARFDIE::GetMangledName(), GetMangledNamesForFunction(), lldb_private::plugin::dwarf::DWARFDebugInfo::GetNumUnits(), lldb_private::plugin::dwarf::DWARFDebugInfo::GetUnitAtIndex(), m_function_scope_qualified_name_map, and SymbolFileDWARFDwo.
Referenced by GetMangledNamesForFunction().
GetModuleMutex()
std::recursive_mutex & SymbolFileDWARF::GetModuleMutex () const override virtual
Symbols file subclasses should override this to return the Module that owns the TypeSystem that this symbol file modifies type information in.
Reimplemented from lldb_private::SymbolFile.
Definition at line 2276 of file SymbolFileDWARF.cpp.
References lldb_private::ModuleChild::GetModule(), lldb_private::SymbolFileCommon::GetObjectFile(), and m_debug_map_module_wp.
Referenced by CalculateFrameVariableError(), CompleteType(), FindFunctions(), FindFunctions(), FindGlobalVariables(), FindGlobalVariables(), FindNamespace(), FindTypes(), GetCompilerContextForUID(), GetDeclContextContainingUID(), GetDeclContextForUID(), GetDeclForUID(), GetDIE(), GetDynamicArrayInfoForUID(), GetTypeList(), ParseBlocksRecursive(), ParseDebugMacros(), ParseFunctions(), ParseImportedModules(), ParseIsOptimized(), ParseLanguage(), ParseLineTable(), ParseSupportFiles(), ParseTypes(), ParseVariablesForContext(), ParseXcodeSDK(), PreloadSymbols(), ResolveFunctionCallLabel(), and ResolveTypeUID().
GetNextUnparsedDWARFCompileUnit()
DWARFUnit * lldb_private::plugin::dwarf::SymbolFileDWARF::GetNextUnparsedDWARFCompileUnit (DWARFUnit * prev_cu) protected
References DWARFDIE.
GetObjCClassSymbol()
Symbol * SymbolFileDWARF::GetObjCClassSymbol (ConstString objc_class_name) protected
Definition at line 3100 of file SymbolFileDWARF.cpp.
References lldb_private::Symtab::eDebugNo, lldb::eSymbolTypeObjCClass, lldb_private::Symtab::eVisibilityAny, lldb_private::Symtab::FindFirstSymbolWithNameAndType(), and lldb_private::SymbolFileCommon::m_objfile_sp.
Referenced by FindCompleteObjCDefinitionTypeForDIE().
GetObjCMethods()
void SymbolFileDWARF::GetObjCMethods (ConstString class_name, llvm::function_ref< IterationAction(DWARFDIE die)> callback) virtual
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 1666 of file SymbolFileDWARF.cpp.
References DWARFDIE, and m_index.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetObjCMethods().
GetParentSymbolContextDIE()
DWARFDIE SymbolFileDWARF::GetParentSymbolContextDIE (const DWARFDIE & die) static
Definition at line 462 of file SymbolFileDWARF.cpp.
References DWARFDIE, lldb_private::plugin::dwarf::DWARFDIE::GetParent(), and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
Referenced by ParseAndAppendGlobalVariable(), ParseVariableDIE(), and DWARFASTParserClang::UpdateSymbolContextScopeForType().
GetPluginDescriptionStatic()
llvm::StringRef SymbolFileDWARF::GetPluginDescriptionStatic () static
Definition at line 334 of file SymbolFileDWARF.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef lldb_private::plugin::dwarf::SymbolFileDWARF::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 208 of file SymbolFileDWARF.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::plugin::dwarf::SymbolFileDWARF::GetPluginNameStatic () inline static
Definition at line 93 of file SymbolFileDWARF.h.
Referenced by GetPluginName(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetSymbolFileAsSymbolFileDWARF(), and Initialize().
GetSeparateDebugInfo()
bool SymbolFileDWARF::GetSeparateDebugInfo (StructuredData::Dictionary & d, bool errors_only, bool load_all_debug_info = false) override virtual
List separate dwo files.
Reimplemented from lldb_private::SymbolFile.
Definition at line 4341 of file SymbolFileDWARF.cpp.
References lldb_private::StructuredData::Array::AddItem(), lldb_private::StructuredData::Dictionary::AddItem(), lldb_private::StructuredData::Dictionary::AddStringItem(), lldb_private::Status::AsCString(), DebugInfo(), DWARFCompileUnit, lldb_private::plugin::dwarf::DWARFUnit::GetDIE(), lldb_private::plugin::dwarf::DWARFUnit::GetDwoError(), lldb_private::plugin::dwarf::DWARFUnit::GetDWOId(), GetDWOName(), lldb_private::plugin::dwarf::DWARFUnit::GetDwoSymbolFile(), lldb_private::ObjectFile::GetFileSpec(), lldb_private::SymbolFileCommon::GetMainObjectFile(), lldb_private::plugin::dwarf::DWARFDebugInfo::GetNumUnits(), lldb_private::SymbolFile::GetObjectFile(), lldb_private::plugin::dwarf::DWARFUnit::GetOffset(), lldb_private::FileSpec::GetPath(), lldb_private::plugin::dwarf::DWARFDebugInfo::GetUnitAtIndex(), lldb_private::plugin::dwarf::DWARFUnit::GetUnitDIEOnly(), and lldb_private::SymbolFile::SymbolFile().
GetSkeletonUnit()
DWARFUnit * SymbolFileDWARF::GetSkeletonUnit (DWARFUnit * dwo_unit)
Given a DWO DWARFUnit, find the corresponding skeleton DWARFUnit in the main symbol file.
DWP files can have their DWARFUnits parsed without the skeleton compile units having been parsed, so sometimes we need to find the skeleton compile unit for a DWO DWARFUnit so we can fill in this link. Currently unless the skeleton compile unit has been parsed and the Unit DIE has been parsed, the DWO unit will not have a backward link setup correctly which was causing crashes due to an assertion that was firing in SymbolFileDWARF::GetCompUnitForDWARFCompUnit().
Definition at line 1769 of file SymbolFileDWARF.cpp.
References DebugInfo(), and lldb_private::plugin::dwarf::DWARFDebugInfo::GetSkeletonUnit().
Referenced by lldb_private::plugin::dwarf::DWARFUnit::GetSkeletonUnit().
GetTypeForDIE()
TypeSP SymbolFileDWARF::GetTypeForDIE (const DWARFDIE & die, bool resolve_function_context = false) protected
Definition at line 3015 of file SymbolFileDWARF.cpp.
References DIE_IS_BEING_PARSED, DWARFDIE, GetCompUnitForDWARFCompUnit(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), lldb_private::plugin::dwarf::DWARFDIE::GetDIE(), GetDIEToType(), GetFunction(), lldb_private::ModuleChild::GetModule(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::plugin::dwarf::DWARFDebugInfoEntry::GetParent(), lldb_private::plugin::dwarf::DWARFDIE::GetParent(), ParseType(), and lldb_private::plugin::dwarf::DWARFDebugInfoEntry::Tag().
Referenced by ResolveType().
GetTypeList()
TypeList & SymbolFileDWARF::GetTypeList () override protected virtual
Reimplemented from lldb_private::SymbolFileCommon.
Definition at line 346 of file SymbolFileDWARF.cpp.
References GetDebugMapSymfile(), GetModuleMutex(), lldb_private::SymbolFileCommon::GetTypeList(), and SymbolFileDWARFDebugMap.
GetTypes() [1/2]
void SymbolFileDWARF::GetTypes (const DWARFDIE & die, dw_offset_t min_die_offset, dw_offset_t max_die_offset, uint32_t type_mask, TypeSet & type_set) protected
Definition at line 352 of file SymbolFileDWARF.cpp.
References lldb_private::plugin::dwarf::DWARFDIE::children(), DWARFDIE, lldb_private::plugin::dwarf::DWARFBaseDIE::GetOffset(), GetTypes(), ResolveTypeUID(), and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
GetTypes() [2/2]
void lldb_private::plugin::dwarf::SymbolFileDWARF::GetTypes (SymbolContextScope * sc_scope, lldb::TypeClass type_mask, TypeList & type_list) override virtual
Implements lldb_private::SymbolFile.
Referenced by GetTypes(), and lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetTypes().
GetTypeSystem()
llvm::Expected< lldb::TypeSystemSP > SymbolFileDWARF::GetTypeSystem (DWARFUnit & unit) static
Definition at line 4497 of file SymbolFileDWARF.cpp.
References GetLanguage(), lldb_private::plugin::dwarf::DWARFUnit::GetSymbolFileDWARF(), and GetTypeSystemForLanguage().
Referenced by GetDWARFParser().
GetTypeSystemForLanguage()
llvm::Expected< lldb::TypeSystemSP > SymbolFileDWARF::GetTypeSystemForLanguage (lldb::LanguageType language) override virtual
Reimplemented from lldb_private::SymbolFileCommon.
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 518 of file SymbolFileDWARF.cpp.
References GetDebugMapSymfile(), lldb_private::SymbolFileCommon::GetTypeSystemForLanguage(), and SymbolFileDWARFDebugMap.
Referenced by ConstructFunctionDemangledName(), DeclContextMatchesThisSymbolFile(), DumpClangAST(), FindDefinitionDIE(), GetTypeSystem(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetTypeSystemForLanguage(), ParseFunction(), and ParseType().
GetTypeUnitSupportFiles()
const SupportFileList * SymbolFileDWARF::GetTypeUnitSupportFiles (DWARFTypeUnit & tu) protected
Definition at line 1123 of file SymbolFileDWARF.cpp.
References lldb_private::DebugInfo, DW_INVALID_OFFSET, elapsed(), error(), lldb_private::plugin::dwarf::DWARFUnit::GetLineTableOffset(), lldb_private::GetLog(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::plugin::dwarf::DWARFUnit::GetPathStyle(), LLDB_LOG_ERROR, m_context, m_parse_time, m_type_unit_support_files, and ParseSupportFilesFromPrologue().
Referenced by GetFile().
GetUniqueDWARFASTTypeMap()
UniqueDWARFASTTypeMap & SymbolFileDWARF::GetUniqueDWARFASTTypeMap () virtual
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 509 of file SymbolFileDWARF.cpp.
References GetDebugMapSymfile(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetUniqueDWARFASTTypeMap(), m_unique_ast_type_map, and SymbolFileDWARFDebugMap.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetUniqueDWARFASTTypeMap().
GetVendorDWARFOpcodeSize()
virtual lldb::offset_t lldb_private::plugin::dwarf::SymbolFileDWARF::GetVendorDWARFOpcodeSize (const DataExtractor & data, const lldb::offset_t data_offset, const uint8_t op) const inline virtual
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo, and lldb_private::plugin::dwarf::SymbolFileWasm.
Definition at line 327 of file SymbolFileDWARF.h.
References LLDB_INVALID_OFFSET.
Referenced by lldb_private::plugin::dwarf::DWARFUnit::GetVendorDWARFOpcodeSize(), and lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetVendorDWARFOpcodeSize().
HasForwardDeclForCompilerType()
bool SymbolFileDWARF::HasForwardDeclForCompilerType (const CompilerType & compiler_type)
Definition at line 1548 of file SymbolFileDWARF.cpp.
References GetForwardDeclCompilerTypeToDIE(), lldb_private::CompilerType::GetOpaqueQualType(), lldb_private::CompilerType::GetTypeSystem(), and lldb_private::ClangUtil::RemoveFastQualifiers().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompleteType().
Initialize()
void SymbolFileDWARF::Initialize () static
Definition at line 310 of file SymbolFileDWARF.cpp.
References CreateInstance(), DebuggerInitialize(), GetPluginDescriptionStatic(), GetPluginNameStatic(), lldb_private::LogChannelDWARF::Initialize(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::Initialize(), and lldb_private::PluginManager::RegisterPlugin().
InitializeFirstCodeAddress()
void SymbolFileDWARF::InitializeFirstCodeAddress () protected
Definition at line 571 of file SymbolFileDWARF.cpp.
References InitializeFirstCodeAddressRecursive(), LLDB_INVALID_ADDRESS, m_first_code_address, and lldb_private::SymbolFileCommon::m_objfile_sp.
Referenced by InitializeObject().
InitializeFirstCodeAddressRecursive()
void SymbolFileDWARF::InitializeFirstCodeAddressRecursive (const SectionList & section_list) protected
Definition at line 578 of file SymbolFileDWARF.cpp.
References lldb::eSectionTypeCode, InitializeFirstCodeAddressRecursive(), and m_first_code_address.
Referenced by InitializeFirstCodeAddress(), and InitializeFirstCodeAddressRecursive().
InitializeObject()
void SymbolFileDWARF::InitializeObject () override virtual
Initialize the SymbolFile object.
The SymbolFile object with the best set of abilities (detected in "uint32_t SymbolFile::GetAbilities()) will have this function called if it is chosen to parse an object file. More complete initialization can happen in this function which will get called prior to any other functions in the SymbolFile protocol.
Reimplemented from lldb_private::SymbolFile.
Definition at line 525 of file SymbolFileDWARF.cpp.
References lldb_private::Stream::AsRawOstream(), lldb_private::plugin::dwarf::AppleDWARFIndex::Create(), lldb_private::plugin::dwarf::DebugNamesDWARFIndex::Create(), lldb_private::DebugInfo, lldb::eDescriptionLevelBrief, lldb::eSectionTypeDWARFAppleNames, lldb::eSectionTypeDWARFAppleNamespaces, lldb::eSectionTypeDWARFAppleObjC, lldb::eSectionTypeDWARFAppleTypes, lldb::eSectionTypeDWARFDebugNames, lldb_private::DataExtractor::GetByteSize(), lldb_private::StreamString::GetData(), GetGlobalPluginProperties(), lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), lldb_private::SymbolFileCommon::GetObjectFile(), InitializeFirstCodeAddress(), LLDB_LOG_ERROR, LoadSectionData(), m_context, and m_index.
isA()
bool lldb_private::plugin::dwarf::SymbolFileDWARF::isA (const void * ClassID) const inline override virtual
LLVM RTTI support.
Reimplemented from lldb_private::SymbolFileCommon.
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 73 of file SymbolFileDWARF.h.
References ID, and lldb_private::SymbolFileCommon::isA().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDwo::isA().
LanguageTypeFromDWARF()
LanguageType SymbolFileDWARF::LanguageTypeFromDWARF (uint64_t val) static
Definition at line 4532 of file SymbolFileDWARF.cpp.
References lldb::eLanguageTypeLastStandardLanguage, lldb::eLanguageTypeMipsAssembler, and lldb::eLanguageTypeUnknown.
Referenced by GetLanguage(), GetLanguageFamily(), and ParseCompileUnit().
LoadSectionData()
void SymbolFileDWARF::LoadSectionData (lldb::SectionType sect_type, DWARFDataExtractor & data) protected virtual
Definition at line 693 of file SymbolFileDWARF.cpp.
References lldb_private::DataExtractor::Clear(), lldb_private::SectionList::FindSectionByType(), and lldb_private::SymbolFileCommon::m_objfile_sp.
Referenced by InitializeObject().
MergeBlockAbstractParameters()
DIEArray SymbolFileDWARF::MergeBlockAbstractParameters (const DWARFDIE & block_die, DIEArray && variable_dies) protected
Definition at line 3934 of file SymbolFileDWARF.cpp.
References lldb_private::plugin::dwarf::DWARFDIE::begin(), DWARFDIE, GetDIE(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetDIERef(), lldb_private::plugin::dwarf::DWARFDIE::GetFirstChild(), lldb_private::plugin::dwarf::DWARFDIE::GetReferencedDIE(), lldb_private::plugin::dwarf::DWARFDIE::GetSibling(), lldb_private::plugin::dwarf::DWARFBaseDIE::HasChildren(), and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
Referenced by ParseVariablesInFunctionContextRecursive().
operator=()
const SymbolFileDWARF & lldb_private::plugin::dwarf::SymbolFileDWARF::operator= (const SymbolFileDWARF &) protected delete
References DWARFCompileUnit, and SymbolFileDWARF().
ParseAndAppendGlobalVariable()
void SymbolFileDWARF::ParseAndAppendGlobalVariable (const SymbolContext & sc, const DWARFDIE & die, VariableList & cc_variable_list) protected
Definition at line 3878 of file SymbolFileDWARF.cpp.
References lldb_private::VariableList::AddVariableIfUnique(), lldb_private::SymbolContext::comp_unit, lldb_private::plugin::dwarf::DW_TAG_value_to_name(), DWARFDIE, lldb_private::plugin::dwarf::DWARFDIE::GetDIE(), GetDIEToVariable(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetID(), lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), lldb_private::plugin::dwarf::DWARFDIE::GetName(), lldb_private::SymbolFileCommon::GetObjectFile(), GetParentSymbolContextDIE(), lldb_private::CompileUnit::GetVariableList(), LLDB_LOG, lldb_private::Lookups, ParseVariableDIECached(), and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
Referenced by FindGlobalVariables(), and FindGlobalVariables().
ParseBlocksRecursive() [1/2]
size_t SymbolFileDWARF::ParseBlocksRecursive (CompileUnit & comp_unit, Block * parent_block, DWARFDIE die, lldb::addr_t function_file_addr) protected
Definition at line 1339 of file SymbolFileDWARF.cpp.
References lldb_private::Block::AddRange(), lldb_private::Block::CreateChild(), DWARFDIE, lldb_private::Block::FinalizeRanges(), lldb_private::plugin::dwarf::DWARFDIE::GetDIENamesAndRanges(), lldb_private::SupportFileList::GetFileSpecAtIndex(), lldb_private::plugin::dwarf::DWARFDIE::GetFirstChild(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetID(), lldb_private::plugin::dwarf::DWARFDIE::GetSibling(), lldb_private::CompileUnit::GetSupportFiles(), lldb_private::plugin::dwarf::DWARFBaseDIE::HasChildren(), m_first_code_address, ParseBlocksRecursive(), lldb_private::Block::SetInlinedFunctionInfo(), and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
ParseBlocksRecursive() [2/2]
size_t SymbolFileDWARF::ParseBlocksRecursive (Function & func) override virtual
Implements lldb_private::SymbolFile.
Definition at line 3345 of file SymbolFileDWARF.cpp.
References lldb_private::DebugInfo, lldb_private::plugin::dwarf::DIERef::die_offset(), DWARFDIE, lldb_private::Function::GetBlock(), lldb_private::Function::GetCompileUnit(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), lldb_private::plugin::dwarf::DWARFDIE::GetDIE(), lldb_private::plugin::dwarf::DWARFUnit::GetDIE(), GetDWARFCompileUnit(), lldb_private::plugin::dwarf::DWARFDIE::GetFirstChild(), lldb_private::UserID::GetID(), lldb_private::GetLog(), GetModuleMutex(), lldb_private::plugin::dwarf::DWARFUnit::GetNonSkeletonUnit(), lldb_private::plugin::dwarf::DWARFUnit::GetOffset(), LLDB_INVALID_ADDRESS, LLDB_LOG_ERROR, lldbassert, and ParseBlocksRecursive().
Referenced by ParseBlocksRecursive(), ParseBlocksRecursive(), and lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ParseBlocksRecursive().
ParseCallEdgesInFunction()
std::vector< std::unique_ptr< lldb_private::CallEdge > > SymbolFileDWARF::ParseCallEdgesInFunction (lldb_private::UserID func_id) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 4312 of file SymbolFileDWARF.cpp.
References CollectCallEdges(), DWARFDIE, GetDIE(), lldb_private::UserID::GetID(), lldb_private::SymbolFileCommon::GetObjectFile(), and lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ParseCallEdgesInFunction().
ParseCompileUnit()
lldb::CompUnitSP SymbolFileDWARF::ParseCompileUnit (DWARFCompileUnit & dwarf_cu) protected
Definition at line 779 of file SymbolFileDWARF.cpp.
References BuildCuTranslationTable(), DWARFCompileUnit, lldb::eLanguageTypeUnknown, lldb_private::eLazyBoolCalculate, GetDebugMapSymfile(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetDIE(), lldb_private::plugin::dwarf::DWARFUnit::GetDWARFLanguageType(), GetDWARFUnitIndex(), GetDWOName(), lldb_private::UserID::GetID(), lldb_private::plugin::dwarf::DWARFUnit::GetLLDBCompUnit(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetName(), lldb_private::plugin::dwarf::DWARFCompileUnit::GetNonSkeletonUnit(), lldb_private::plugin::dwarf::DWARFUnit::GetPathStyle(), lldb_private::SupportFileList::GetSize(), lldb_private::SupportFileList::GetSupportFileAtIndex(), lldb_private::plugin::dwarf::DWARFUnit::GetUnitDIEOnly(), lldb_private::plugin::dwarf::DWARFUnit::GetVersion(), LanguageTypeFromDWARF(), m_debug_map_symfile, lldb_private::SymbolFileCommon::m_objfile_sp, MakeAbsoluteAndRemap(), ParseSupportFiles(), lldb_private::SymbolFileCommon::SetCompileUnitAtIndex(), and lldb_private::plugin::dwarf::DWARFUnit::SetLLDBCompUnit().
Referenced by GetCompUnitForDWARFCompUnit(), and ParseCompileUnitAtIndex().
ParseCompileUnitAtIndex()
CompUnitSP SymbolFileDWARF::ParseCompileUnitAtIndex (uint32_t index) override protected virtual
Implements lldb_private::SymbolFileCommon.
Definition at line 892 of file SymbolFileDWARF.cpp.
References ASSERT_MODULE_LOCK, DebugInfo(), GetDWARFUnitIndex(), and ParseCompileUnit().
ParseDebugMacros() [1/2]
bool SymbolFileDWARF::ParseDebugMacros (CompileUnit & comp_unit) override virtual
Implements lldb_private::SymbolFile.
Definition at line 1315 of file SymbolFileDWARF.cpp.
References DW_INVALID_OFFSET, lldb_private::plugin::dwarf::DWARFBaseDIE::GetAttributeValueAsUnsigned(), GetDWARFCompileUnit(), GetModuleMutex(), lldb_private::plugin::dwarf::DWARFUnit::GetUnitDIEOnly(), ParseDebugMacros(), and lldb_private::CompileUnit::SetDebugMacros().
Referenced by ParseDebugMacros(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ParseDebugMacros(), and lldb_private::plugin::dwarf::DWARFDebugMacroEntry::ReadMacroEntries().
ParseDebugMacros() [2/2]
lldb_private::DebugMacrosSP SymbolFileDWARF::ParseDebugMacros (lldb::offset_t * offset)
Definition at line 1293 of file SymbolFileDWARF.cpp.
References elapsed(), lldb_private::DataExtractor::GetByteSize(), m_context, m_debug_macros_map, m_parse_time, lldb_private::plugin::dwarf::DWARFDebugMacroHeader::OffsetIs64Bit(), lldb_private::plugin::dwarf::DWARFDebugMacroHeader::ParseHeader(), and lldb_private::plugin::dwarf::DWARFDebugMacroEntry::ReadMacroEntries().
ParseDeclsForContext()
void SymbolFileDWARF::ParseDeclsForContext (CompilerDeclContext decl_ctx) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 1423 of file SymbolFileDWARF.cpp.
References lldb_private::plugin::dwarf::DWARFASTParser::EnsureAllDIEsInDeclContextHaveBeenParsed(), lldb_private::TypeSystem::GetDWARFParser(), and lldb_private::CompilerDeclContext::GetTypeSystem().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ParseDeclsForContext().
ParseFunction()
Function * SymbolFileDWARF::ParseFunction (CompileUnit & comp_unit, const DWARFDIE & die) protected
Definition at line 902 of file SymbolFileDWARF.cpp.
References ASSERT_MODULE_LOCK, DWARFASTParser, DWARFDIE, FixupAddress(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), lldb_private::plugin::dwarf::DWARFDIE::GetDIE(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetID(), GetLanguage(), lldb_private::GetLog(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetModule(), GetTypeSystemForLanguage(), lldb_private::Address::IsValid(), lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), LLDB_LOG_ERROR, m_first_code_address, lldb_private::plugin::dwarf::DWARFASTParser::ParseFunctionFromDWARF(), and lldb_private::Symbols.
Referenced by GetFunction(), ParseFunctions(), and ResolveFunctionAndBlock().
ParseFunctions()
size_t SymbolFileDWARF::ParseFunctions (CompileUnit & comp_unit) override virtual
Implements lldb_private::SymbolFile.
Definition at line 1025 of file SymbolFileDWARF.cpp.
References lldb_private::plugin::dwarf::DWARFUnit::dies(), DWARFDIE, lldb_private::CompileUnit::FindFunctionByUID(), GetDWARFCompileUnit(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetID(), GetModuleMutex(), lldb_private::plugin::dwarf::DWARFUnit::GetNonSkeletonUnit(), LLDB_SCOPED_TIMER, and ParseFunction().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ParseFunctions().
ParseImportedModules()
bool SymbolFileDWARF::ParseImportedModules (const SymbolContext & sc, std::vector< SourceModule > & imported_modules) override virtual
Implements lldb_private::SymbolFile.
Definition at line 1168 of file SymbolFileDWARF.cpp.
References lldb_private::plugin::dwarf::DWARFDIE::children(), lldb_private::SymbolContext::comp_unit, lldb_private::plugin::dwarf::DWARFUnit::DIE(), DWARFDIE, lldb_private::plugin::dwarf::DWARFBaseDIE::GetAttributeValueAsString(), GetDWARFCompileUnit(), lldb_private::CompileUnit::GetLanguage(), GetModuleMutex(), lldb_private::plugin::dwarf::DWARFDIE::GetParent(), lldb_private::plugin::dwarf::DWARFUnit::GetPathStyle(), lldb_private::ClangModulesDeclVendor::LanguageSupportsClangModules(), lldb_private::SymbolFileCommon::m_objfile_sp, MakeAbsoluteAndRemap(), lldb_private::SourceModule::path, lldb_private::plugin::dwarf::DWARFBaseDIE::Tag(), and UpdateExternalModuleListIfNeeded().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ParseImportedModules().
ParseIsOptimized()
bool SymbolFileDWARF::ParseIsOptimized (CompileUnit & comp_unit) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 1160 of file SymbolFileDWARF.cpp.
References GetDWARFCompileUnit(), lldb_private::plugin::dwarf::DWARFUnit::GetIsOptimized(), GetModuleMutex(), and lldb_private::plugin::dwarf::DWARFUnit::GetNonSkeletonUnit().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ParseIsOptimized().
ParseLanguage()
lldb::LanguageType SymbolFileDWARF::ParseLanguage (CompileUnit & comp_unit) override virtual
Implements lldb_private::SymbolFile.
Definition at line 983 of file SymbolFileDWARF.cpp.
References lldb::eLanguageTypeUnknown, GetDWARFCompileUnit(), GetLanguage(), GetModuleMutex(), and lldb_private::plugin::dwarf::DWARFUnit::GetNonSkeletonUnit().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ParseLanguage().
ParseLineTable()
bool SymbolFileDWARF::ParseLineTable (CompileUnit & comp_unit) override virtual
Implements lldb_private::SymbolFile.
Definition at line 1231 of file SymbolFileDWARF.cpp.
References lldb_private::LineTable::AppendLineEntryToSequence(), DW_INVALID_OFFSET, elapsed(), GetDebugMapSymfile(), GetDWARFCompileUnit(), lldb_private::CompileUnit::GetLineTable(), lldb_private::plugin::dwarf::DWARFUnit::GetLineTableOffset(), GetModuleMutex(), lldb_private::plugin::dwarf::DWARFUnit::GetOffset(), m_context, m_first_code_address, m_parse_time, ParseLLVMLineTable(), lldb_private::CompileUnit::SetLineTable(), and SymbolFileDWARFDebugMap.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ParseLineTable().
ParseSupportFiles() [1/2]
bool SymbolFileDWARF::ParseSupportFiles (CompileUnit & comp_unit, SupportFileList & support_files) override virtual
Implements lldb_private::SymbolFile.
Definition at line 1076 of file SymbolFileDWARF.cpp.
References GetDWARFCompileUnit(), lldb_private::ModuleChild::GetModule(), GetModuleMutex(), and ParseSupportFiles().
Referenced by ParseCompileUnit(), ParseSupportFiles(), and lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ParseSupportFiles().
ParseSupportFiles() [2/2]
bool SymbolFileDWARF::ParseSupportFiles (DWARFUnit & dwarf_cu, const lldb::ModuleSP & module, SupportFileList & support_files) protected
Definition at line 1089 of file SymbolFileDWARF.cpp.
References DW_INVALID_OFFSET, elapsed(), lldb_private::plugin::dwarf::DWARFUnit::GetCompilationDirectory(), lldb_private::plugin::dwarf::DWARFUnit::GetLineTableOffset(), lldb_private::plugin::dwarf::DWARFUnit::GetOffset(), lldb_private::FileSpec::GetPath(), lldb_private::plugin::dwarf::DWARFUnit::GetPathStyle(), m_context, m_parse_time, ParseLLVMLineTablePrologue(), and ParseSupportFilesFromPrologue().
ParseType()
TypeSP SymbolFileDWARF::ParseType (const SymbolContext & sc, const DWARFDIE & die, bool * type_is_new) protected
Definition at line 3272 of file SymbolFileDWARF.cpp.
References lldb_private::ConstString::AsCString(), DWARFASTParser, DWARFDIE, lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), GetDeclContextForUID(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetDIERef(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetID(), GetLanguage(), lldb_private::GetLog(), lldb_private::CompilerDeclContext::GetScopeQualifiedName(), GetTypeSystemForLanguage(), LLDB_LOG_ERROR, m_function_scope_qualified_name_map, lldb_private::plugin::dwarf::DWARFASTParser::ParseTypeFromDWARF(), lldb_private::Symbols, and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
Referenced by GetTypeForDIE(), and ParseTypes().
ParseTypes() [1/2]
size_t SymbolFileDWARF::ParseTypes (CompileUnit & comp_unit) override virtual
Implements lldb_private::SymbolFile.
Definition at line 3380 of file SymbolFileDWARF.cpp.
References lldb_private::SymbolContext::comp_unit, lldb_private::plugin::dwarf::DWARFUnit::DIE(), DWARFDIE, GetDWARFCompileUnit(), lldb_private::plugin::dwarf::DWARFDIE::GetFirstChild(), GetModuleMutex(), lldb_private::plugin::dwarf::DWARFBaseDIE::HasChildren(), and ParseTypes().
Referenced by ParseTypes(), ParseTypes(), and lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ParseTypes().
ParseTypes() [2/2]
size_t SymbolFileDWARF::ParseTypes (const SymbolContext & sc, const DWARFDIE & die, bool parse_siblings, bool parse_children) protected
Definition at line 3307 of file SymbolFileDWARF.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::Clear(), lldb_private::SymbolContext::comp_unit, DWARFDIE, lldb_private::CompileUnit::FindFunctionByUID(), lldb_private::SymbolContext::function, lldb_private::plugin::dwarf::DWARFDIE::GetFirstChild(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetID(), lldb_private::plugin::dwarf::DWARFDIE::GetSibling(), lldb_private::plugin::dwarf::DWARFBaseDIE::HasChildren(), ParseType(), ParseTypes(), and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
ParseVariableDIE()
VariableSP SymbolFileDWARF::ParseVariableDIE (const SymbolContext & sc, const DWARFDIE & die, const lldb::addr_t func_low_pc) protected
Definition at line 3554 of file SymbolFileDWARF.cpp.
References lldb_private::plugin::dwarf::DWARFFormValue::AsCString(), lldb_private::plugin::dwarf::DWARFAttributes::AttributeAtIndex(), lldb_private::plugin::dwarf::DWARFFormValue::Boolean(), lldb_private::SymbolContext::comp_unit, lldb_private::plugin::dwarf::DWARFAttributes::CompileUnitAtIndex(), lldb_private::DWARFExpressionList::ContainsThreadLocalStorage(), lldb_private::plugin::dwarf::DW_TAG_value_to_name(), DWARFDIE, lldb::eDescriptionLevelFull, lldb::eValueTypeInvalid, lldb::eValueTypeVariableArgument, lldb::eValueTypeVariableGlobal, lldb::eValueTypeVariableLocal, lldb::eValueTypeVariableStatic, lldb::eValueTypeVariableThreadLocal, lldb_private::plugin::dwarf::DWARFAttributes::ExtractFormValueAtIndex(), lldb_private::Block::FindBlockByID(), fixupExternalAddrZeroVariable(), lldb_private::plugin::dwarf::DWARFFormValue::Form(), lldb_private::SymbolContext::function, lldb_private::plugin::dwarf::DWARFUnit::GetAddressByteSize(), lldb_private::DWARFExpressionList::GetAlwaysValidExpr(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetAttributes(), lldb_private::Function::GetBlock(), lldb_private::ConstString::GetCString(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), lldb_private::StreamString::GetData(), GetDebugMapSymfile(), GetDeclContextDIEContainingDIE(), lldb_private::plugin::dwarf::DWARFDIE::GetDIE(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetDWARF(), lldb_private::plugin::dwarf::DWARFDIE::GetDWARFDeclContext(), GetExprListFromAtConstValue(), GetExprListFromAtLocation(), lldb_private::plugin::dwarf::DWARFUnit::GetFile(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetID(), GetLanguage(), lldb_private::ModuleChild::GetModule(), lldb_private::DWARFExpressionList::GetMutableExpressionAtAddress(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetOffset(), GetParentSymbolContextDIE(), lldb_private::plugin::dwarf::DWARFDeclContext::GetQualifiedNameAsConstString(), lldb_private::plugin::dwarf::DWARFFormValue::GetUnit(), lldb_private::plugin::dwarf::DWARFFormValue::IsDataForm(), lldb_private::DWARFExpressionList::IsValid(), lldb_private::plugin::dwarf::DWARFFormValue::IsValid(), lldb_private::Language::LanguageIsCPlusPlus(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::LinkOSOFileAddress(), lldb_private::DWARFExpressionList::LinkThreadLocalStorage(), LLDB_INVALID_ADDRESS, ParseVariableDIE(), lldb_private::plugin::dwarf::DWARFFormValue::Reference(), lldb_private::Declaration::SetColumn(), lldb_private::Declaration::SetFile(), lldb_private::Declaration::SetLine(), lldb_private::DWARFExpressionList::SetModule(), lldb_private::plugin::dwarf::DWARFAttributes::Size(), SymbolFileDWARFDebugMap, lldb_private::plugin::dwarf::DWARFBaseDIE::Tag(), lldb_private::plugin::dwarf::DWARFFormValue::Unsigned(), lldb_private::DWARFExpression::Update_DW_OP_addr(), and lldb_private::DWARFExpression::UpdateValue().
Referenced by ParseVariableDIE(), ParseVariableDIECached(), and PopulateBlockVariableList().
ParseVariableDIECached()
VariableSP SymbolFileDWARF::ParseVariableDIECached (const SymbolContext & sc, const DWARFDIE & die) protected
Definition at line 3448 of file SymbolFileDWARF.cpp.
References DWARFDIE, lldb_private::plugin::dwarf::DWARFDIE::GetDIE(), GetDIEToVariable(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetDWARF(), lldb_private::plugin::dwarf::DWARFDIE::GetReferencedDIE(), LLDB_INVALID_ADDRESS, and ParseVariableDIE().
Referenced by ParseAndAppendGlobalVariable(), and ParseVariablesForContext().
ParseVariablesForContext()
size_t SymbolFileDWARF::ParseVariablesForContext (const SymbolContext & sc) override virtual
Implements lldb_private::SymbolFile.
Definition at line 3396 of file SymbolFileDWARF.cpp.
References lldb_private::SymbolContext::comp_unit, lldb_private::Continue, lldb_private::DebugInfo, DebugInfo(), DWARFDIE, lldb_private::SymbolContext::function, lldb_private::Function::GetBlock(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), lldb_private::plugin::dwarf::DWARFDIE::GetDIE(), GetDIE(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetID(), lldb_private::UserID::GetID(), lldb_private::GetLog(), GetModuleMutex(), lldb_private::plugin::dwarf::DWARFDebugInfo::GetUnitAtIndex(), lldb_private::CompileUnit::GetVariableList(), LLDB_INVALID_ADDRESS, LLDB_LOG_ERROR, m_index, ParseVariableDIECached(), ParseVariablesInFunctionContext(), lldb_private::Block::SetDidParseVariables(), and lldb_private::CompileUnit::SetVariableList().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ParseVariablesForContext().
ParseVariablesInFunctionContext()
size_t SymbolFileDWARF::ParseVariablesInFunctionContext (const SymbolContext & sc, const DWARFDIE & die, const lldb::addr_t func_low_pc) protected
Definition at line 4009 of file SymbolFileDWARF.cpp.
References DWARFDIE, lldb_private::SymbolContext::function, and ParseVariablesInFunctionContextRecursive().
Referenced by ParseVariablesForContext().
ParseVariablesInFunctionContextRecursive()
size_t SymbolFileDWARF::ParseVariablesInFunctionContextRecursive (const SymbolContext & sc, const DWARFDIE & die, lldb::addr_t func_low_pc, DIEArray & accumulator) protected
Definition at line 4027 of file SymbolFileDWARF.cpp.
References DWARFDIE, lldb_private::Block::FindBlockByID(), FindBlockContainingSpecification(), lldb_private::SymbolContext::function, lldb_private::Function::GetBlock(), lldb_private::Block::GetBlockVariableList(), GetDIE(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetDIERef(), lldb_private::plugin::dwarf::DWARFDIE::GetFirstChild(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetID(), lldb_private::UserID::GetID(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetOffset(), lldb_private::plugin::dwarf::DWARFDIE::GetSibling(), MergeBlockAbstractParameters(), ParseVariablesInFunctionContextRecursive(), PopulateBlockVariableList(), lldb_private::Block::SetVariableList(), and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
Referenced by ParseVariablesInFunctionContext(), and ParseVariablesInFunctionContextRecursive().
ParseVendorDWARFOpcode()
virtual bool lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVendorDWARFOpcode (uint8_t op, const DataExtractor & opcodes, lldb::offset_t & offset, RegisterContext * reg_ctx, lldb::RegisterKind reg_kind, std::vector< Value > & stack) const inline virtual
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo, and lldb_private::plugin::dwarf::SymbolFileWasm.
Definition at line 333 of file SymbolFileDWARF.h.
Referenced by lldb_private::plugin::dwarf::DWARFUnit::ParseVendorDWARFOpcode(), and lldb_private::plugin::dwarf::SymbolFileDWARFDwo::ParseVendorDWARFOpcode().
ParseXcodeSDK()
XcodeSDK SymbolFileDWARF::ParseXcodeSDK (CompileUnit & comp_unit) override virtual
Return the Xcode SDK comp_unit was compiled against.
Reimplemented from lldb_private::SymbolFile.
Definition at line 992 of file SymbolFileDWARF.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::GetAttributeValueAsString(), GetDWARFCompileUnit(), lldb_private::ModuleChild::GetModule(), GetModuleMutex(), lldb_private::plugin::dwarf::DWARFUnit::GetNonSkeletonUnit(), lldb_private::plugin::dwarf::DWARFUnit::GetUnitDIEOnly(), and lldb_private::SymbolFileCommon::m_objfile_sp.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ParseXcodeSDK().
PopulateBlockVariableList()
size_t SymbolFileDWARF::PopulateBlockVariableList (VariableList & variable_list, const SymbolContext & sc, llvm::ArrayRef< DIERef > variable_dies, lldb::addr_t func_low_pc) protected
Definition at line 4094 of file SymbolFileDWARF.cpp.
References lldb_private::VariableList::AddVariableIfUnique(), GetDIE(), and ParseVariableDIE().
Referenced by ParseVariablesInFunctionContextRecursive().
PreloadSymbols()
void SymbolFileDWARF::PreloadSymbols () override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 2264 of file SymbolFileDWARF.cpp.
References GetModuleMutex(), lldb_private::SymbolFileCommon::GetSymtab(), and m_index.
ResetStatistics()
void SymbolFileDWARF::ResetStatistics () override virtual
Reset the statistics for the symbol file.
Reimplemented from lldb_private::SymbolFile.
Definition at line 4563 of file SymbolFileDWARF.cpp.
References m_index, and m_parse_time.
ResolveFunction()
bool SymbolFileDWARF::ResolveFunction (const DWARFDIE & die, bool include_inlines, SymbolContextList & sc_list) protected
Definition at line 2442 of file SymbolFileDWARF.cpp.
References lldb_private::SymbolContextList::AppendIfUnique(), lldb_private::SymbolContext::block, DWARFDIE, lldb_private::Block::FindBlockByID(), lldb_private::SymbolContext::function, lldb_private::Function::GetBlock(), GetFunction(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetID(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetOffset(), lldb_private::plugin::dwarf::DWARFDIE::GetParent(), and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
Referenced by FindFunctions(), FindFunctions(), and ResolveFunctionCallLabel().
ResolveFunctionAndBlock()
void SymbolFileDWARF::ResolveFunctionAndBlock (lldb::addr_t file_vm_addr, bool lookup_block, SymbolContext & sc) protected
Resolve functions and (possibly) blocks for the given file address and a compile unit.
The compile unit comes from the sc argument and it must be set. The results of the lookup (if any) are written back to the symbol context.
Definition at line 2105 of file SymbolFileDWARF.cpp.
References lldb_private::SymbolContext::block, lldb_private::SymbolContext::comp_unit, DWARFCompileUnit, DWARFDIE, lldb_private::Block::FindBlockByID(), lldb_private::CompileUnit::FindFunctionByUID(), lldb_private::SymbolContext::function, lldb_private::Function::GetBlock(), GetDWARFCompileUnit(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetID(), lldb_private::plugin::dwarf::DWARFCompileUnit::GetNonSkeletonUnit(), lldb_private::plugin::dwarf::DWARFCompileUnit::LookupAddress(), lldb_private::plugin::dwarf::DWARFDIE::LookupDeepestBlock(), and ParseFunction().
ResolveFunctionCallLabel()
llvm::Expected< SymbolContext > SymbolFileDWARF::ResolveFunctionCallLabel (FunctionCallLabel & label) override protected virtual
Resolves the function corresponding to the specified LLDB function call label.
Parameters
[in,out] label The FunctionCallLabel to be resolved.
Returns
An llvm::Error if the specified label couldn't be resolved. Returns the resolved function (as a SymbolContext) otherwise.
Reimplemented from lldb_private::SymbolFile.
Definition at line 2596 of file SymbolFileDWARF.cpp.
References lldb_private::FunctionCallLabel::discriminator, DWARFDIE, FindFunctionDefinition(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetAttributeValueAsUnsigned(), GetDIE(), GetItaniumCtorDtorVariant(), GetModuleMutex(), lldb_private::SymbolContextList::GetSize(), lldb_private::SymbolContextList::IsEmpty(), lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), lldb_private::FunctionCallLabel::lookup_name, ResolveFunction(), lldb_private::CPlusPlusLanguage::SubstituteStructor_ItaniumMangle(), and lldb_private::FunctionCallLabel::symbol_id.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ResolveFunctionCallLabel().
ResolveSymbolContext() [1/2]
uint32_t lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveSymbolContext (const Address & so_addr, lldb::SymbolContextItem resolve_scope, SymbolContext & sc) override virtual
Implements lldb_private::SymbolFile.
ResolveSymbolContext() [2/2]
uint32_t lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveSymbolContext (const SourceLocationSpec & src_location_spec, lldb::SymbolContextItem resolve_scope, SymbolContextList & sc_list) override virtual
Reimplemented from lldb_private::SymbolFile.
ResolveType()
Type * SymbolFileDWARF::ResolveType (const DWARFDIE & die, bool assert_not_being_parsed = true, bool resolve_function_context = false)
Definition at line 1627 of file SymbolFileDWARF.cpp.
References DIE_IS_BEING_PARSED, lldb_private::plugin::dwarf::DW_TAG_value_to_name(), DWARFDIE, lldb_private::ModuleChild::GetModule(), lldb_private::plugin::dwarf::DWARFDIE::GetName(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetOffset(), GetTypeForDIE(), and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
Referenced by FindCompleteObjCDefinitionTypeForDIE(), FindTypes(), DWARFASTParserClang::GetClangDeclContextForDIE(), lldb_private::plugin::dwarf::DWARFDIE::ResolveType(), ResolveTypeUID(), and ResolveTypeUID().
ResolveTypeUID() [1/3]
Type * SymbolFileDWARF::ResolveTypeUID (const DIERef & die_ref)
Definition at line 1500 of file SymbolFileDWARF.cpp.
References GetDIE(), and ResolveType().
ResolveTypeUID() [2/3]
Type * SymbolFileDWARF::ResolveTypeUID (const DWARFDIE & die, bool assert_not_being_parsed)
Definition at line 1504 of file SymbolFileDWARF.cpp.
References lldb_private::DebugInfo, lldb_private::plugin::dwarf::DW_TAG_value_to_name(), DWARFDIE, GetDeclContextDIEContainingDIE(), lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), lldb_private::plugin::dwarf::DWARFDIE::GetName(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetOffset(), ResolveType(), and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
ResolveTypeUID() [3/3]
Type * SymbolFileDWARF::ResolveTypeUID (lldb::user_id_t type_uid) override virtual
Implements lldb_private::SymbolFile.
Definition at line 1480 of file SymbolFileDWARF.cpp.
References DWARFDIE, GetDIE(), and GetModuleMutex().
Referenced by GetTypes(), and lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ResolveTypeUID().
SetDebugMapModule()
void lldb_private::plugin::dwarf::SymbolFileDWARF::SetDebugMapModule (const lldb::ModuleSP & module_sp) inline protected
Definition at line 470 of file SymbolFileDWARF.h.
References m_debug_map_module_wp.
Referenced by lldb_private::plugin::dwarf::DebugMapModule::GetSymbolFile().
SetFileIndex()
void lldb_private::plugin::dwarf::SymbolFileDWARF::SetFileIndex (std::optional< uint64_t > file_index) inline
Definition at line 344 of file SymbolFileDWARF.h.
References m_file_index.
Referenced by lldb_private::plugin::dwarf::DebugMapModule::GetSymbolFile(), and lldb_private::plugin::dwarf::SymbolFileDWARFDwo::SymbolFileDWARFDwo().
SupportedVersion()
bool SymbolFileDWARF::SupportedVersion (uint16_t version) static
Definition at line 590 of file SymbolFileDWARF.cpp.
Terminate()
void SymbolFileDWARF::Terminate () static
Definition at line 328 of file SymbolFileDWARF.cpp.
References CreateInstance(), lldb_private::LogChannelDWARF::Terminate(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::Terminate(), and lldb_private::PluginManager::UnregisterPlugin().
UpdateExternalModuleListIfNeeded()
void SymbolFileDWARF::UpdateExternalModuleListIfNeeded () protected
Definition at line 1951 of file SymbolFileDWARF.cpp.
References lldb_private::FileSpec::AppendPathComponent(), DebugInfo(), error(), lldb_private::ModuleSpec::GetArchitecture(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetAttributeValueAsString(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetDIE(), GetDWOId(), GetDWOName(), lldb_private::ModuleSpec::GetFileSpec(), lldb_private::ModuleChild::GetModule(), lldb_private::SymbolFileCommon::GetNumCompileUnits(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::FileSpec::GetPath(), lldb_private::ModuleList::GetSharedModule(), lldb_private::plugin::dwarf::DWARFDebugInfo::GetUnitAtIndex(), lldb_private::plugin::dwarf::DWARFBaseDIE::HasChildren(), lldb_private::FileSystem::Instance(), lldb_private::FileSpec::IsRelative(), m_external_type_modules, m_fetched_external_modules, lldb_private::SymbolFileCommon::m_objfile_sp, lldb_private::FileSystem::Resolve(), and lldb_private::FileSpec::SetFile().
Referenced by FindTypes(), ForEachExternalModule(), GetExternalModule(), and ParseImportedModules().
Friends And Related Symbol Documentation
DebugMapModule
friend class DebugMapModule friend
Definition at line 81 of file SymbolFileDWARF.h.
References DebugMapModule.
Referenced by DebugMapModule.
DWARFASTParser
friend class DWARFASTParser friend
Definition at line 84 of file SymbolFileDWARF.h.
References DWARFASTParser.
Referenced by CompleteType(), ConstructFunctionDemangledName(), DIEInDeclContext(), DWARFASTParser, FindDefinitionDIE(), FindGlobalVariables(), FindNamespace(), GetContainingDeclContext(), GetDecl(), GetDeclContext(), GetDWARFParser(), ParseFunction(), and ParseType().
DWARFCompileUnit
friend class DWARFCompileUnit friend
Definition at line 82 of file SymbolFileDWARF.h.
References DWARFCompileUnit.
Referenced by CalculateFrameVariableError(), DWARFCompileUnit, FindGlobalVariables(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::FindSingleCompileUnit(), GetCompUnitForDWARFCompUnit(), GetDWARFCompileUnit(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetDWOCompileUnitForHash(), GetDWOId(), GetDwoSymbolFileForCompileUnit(), GetSeparateDebugInfo(), operator=(), ParseCompileUnit(), ResolveFunctionAndBlock(), and lldb_private::plugin::dwarf::SymbolFileDWARFDwo::~SymbolFileDWARFDwo().
DWARFDIE
friend class DWARFDIE friend
Definition at line 83 of file SymbolFileDWARF.h.
References DWARFDIE.
Referenced by ClassContainsSelector(), ClassOrStructIsVirtual(), CollectCallEdges(), CompleteType(), ConstructFunctionDemangledName(), DIEInDeclContext(), DWARFDIE, FindBlockContainingSpecification(), FindCompleteObjCDefinitionTypeForDIE(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::FindCompleteObjCDefinitionTypeForDIE(), FindDefinitionDIE(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::FindDefinitionDIE(), FindFunctionDefinition(), FindFunctions(), FindFunctions(), FindGlobalVariables(), FindGlobalVariables(), FindNamespace(), FindTypes(), GetCompilerContextForUID(), GetContainingDeclContext(), GetDecl(), GetDeclContext(), GetDeclContextContainingUID(), GetDeclContextDIEContainingDIE(), GetDeclContextForUID(), GetDeclForUID(), GetDIE(), GetDynamicArrayInfoForUID(), GetFunction(), GetMangledNamesForFunction(), GetNextUnparsedDWARFCompileUnit(), GetObjCMethods(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetObjCMethods(), GetParentSymbolContextDIE(), GetTypeForDIE(), GetTypes(), MergeBlockAbstractParameters(), ParseAndAppendGlobalVariable(), ParseBlocksRecursive(), ParseBlocksRecursive(), ParseCallEdgesInFunction(), ParseFunction(), ParseFunctions(), ParseImportedModules(), ParseType(), ParseTypes(), ParseTypes(), ParseVariableDIE(), ParseVariableDIECached(), ParseVariablesForContext(), ParseVariablesInFunctionContext(), ParseVariablesInFunctionContextRecursive(), ResolveFunction(), ResolveFunctionAndBlock(), ResolveFunctionCallLabel(), ResolveType(), ResolveTypeUID(), ResolveTypeUID(), ~SymbolFileDWARF(), and lldb_private::plugin::dwarf::SymbolFileDWARFDwo::~SymbolFileDWARFDwo().
SymbolFileDWARFDebugMap
friend class SymbolFileDWARFDebugMap friend
Definition at line 79 of file SymbolFileDWARF.h.
References SymbolFileDWARFDebugMap.
Referenced by CompleteType(), FixupAddress(), FixupAddress(), GetDebugMapSymfile(), GetDIERefSymbolFile(), GetDIEToType(), GetForwardDeclCompilerTypeToDIE(), GetTypeList(), GetTypeSystemForLanguage(), GetUniqueDWARFASTTypeMap(), ParseLineTable(), ParseVariableDIE(), and SymbolFileDWARFDebugMap.
SymbolFileDWARFDwo
friend class SymbolFileDWARFDwo friend
Definition at line 80 of file SymbolFileDWARF.h.
References SymbolFileDWARFDwo.
Referenced by GetDebugInfoSize(), GetMangledNamesForFunction(), and SymbolFileDWARFDwo.
Member Data Documentation
ID
char SymbolFileDWARF::ID static private
LLVM RTTI support.
Definition at line 68 of file SymbolFileDWARF.h.
Referenced by classof(), and isA().
m_abbr
std::unique_ptr<llvm::DWARFDebugAbbrev> lldb_private::plugin::dwarf::SymbolFileDWARF::m_abbr protected
Definition at line 536 of file SymbolFileDWARF.h.
Referenced by DebugAbbrev().
m_context
DWARFContext lldb_private::plugin::dwarf::SymbolFileDWARF::m_context protected
Definition at line 531 of file SymbolFileDWARF.h.
Referenced by DebugAbbrev(), DebugInfo(), GetDWARFContext(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetDWOCompileUnitForHash(), GetTypeUnitSupportFiles(), InitializeObject(), ParseDebugMacros(), ParseLineTable(), ParseSupportFiles(), SymbolFileDWARF(), and lldb_private::plugin::dwarf::SymbolFileDWARFDwo::SymbolFileDWARFDwo().
m_debug_macros_map
DebugMacrosMap lldb_private::plugin::dwarf::SymbolFileDWARF::m_debug_macros_map protected
Definition at line 540 of file SymbolFileDWARF.h.
Referenced by ParseDebugMacros().
m_debug_map_module_wp
lldb::ModuleWP lldb_private::plugin::dwarf::SymbolFileDWARF::m_debug_map_module_wp protected
Definition at line 525 of file SymbolFileDWARF.h.
Referenced by GetDebugMapSymfile(), GetModuleMutex(), SetDebugMapModule(), and SymbolFileDWARF().
m_debug_map_symfile
SymbolFileDWARFDebugMap* lldb_private::plugin::dwarf::SymbolFileDWARF::m_debug_map_symfile protected
Definition at line 526 of file SymbolFileDWARF.h.
Referenced by GetDebugMapSymfile(), ParseCompileUnit(), and SymbolFileDWARF().
m_die_to_type
llvm::DenseMap<const DWARFDebugInfoEntry *, Type *> lldb_private::plugin::dwarf::SymbolFileDWARF::m_die_to_type protected
Definition at line 552 of file SymbolFileDWARF.h.
Referenced by GetDIEToType().
m_die_to_variable_sp
DIEToVariableSP lldb_private::plugin::dwarf::SymbolFileDWARF::m_die_to_variable_sp protected
Definition at line 553 of file SymbolFileDWARF.h.
Referenced by GetDIEToVariable().
m_dwo_warning_issued
std::atomic_flag lldb_private::plugin::dwarf::SymbolFileDWARF::m_dwo_warning_issued = ATOMIC_FLAG_INIT protected
Definition at line 569 of file SymbolFileDWARF.h.
Referenced by GetDwoSymbolFileForCompileUnit().
m_dwp_symfile
std::shared_ptr<SymbolFileDWARFDwo> lldb_private::plugin::dwarf::SymbolFileDWARF::m_dwp_symfile protected
Definition at line 529 of file SymbolFileDWARF.h.
Referenced by GetDwpSymbolFile().
m_dwp_symfile_once_flag
llvm::once_flag lldb_private::plugin::dwarf::SymbolFileDWARF::m_dwp_symfile_once_flag protected
Definition at line 528 of file SymbolFileDWARF.h.
Referenced by GetDwpSymbolFile().
m_external_type_modules
ExternalTypeModuleMap lldb_private::plugin::dwarf::SymbolFileDWARF::m_external_type_modules protected
Definition at line 542 of file SymbolFileDWARF.h.
Referenced by FindTypes(), ForEachExternalModule(), GetExternalModule(), getExternalTypeModules(), and UpdateExternalModuleListIfNeeded().
m_fetched_external_modules
bool lldb_private::plugin::dwarf::SymbolFileDWARF::m_fetched_external_modules protected
Definition at line 544 of file SymbolFileDWARF.h.
Referenced by SymbolFileDWARF(), and UpdateExternalModuleListIfNeeded().
m_file_index
std::optional<uint64_t> lldb_private::plugin::dwarf::SymbolFileDWARF::m_file_index protected
If this DWARF file a .DWO file or a DWARF .o file on mac when no dSYM file is being used, this file index will be set to a valid value that can be used in DIERef objects which will contain an index that identifies the .DWO or .o file.
Definition at line 574 of file SymbolFileDWARF.h.
Referenced by GetFileIndex(), and SetFileIndex().
m_first_code_address
lldb::addr_t lldb_private::plugin::dwarf::SymbolFileDWARF::m_first_code_address = LLDB_INVALID_ADDRESS protected
DWARF does not provide a good way for traditional (concatenating) linkers to invalidate debug info describing dead-stripped code.
These linkers will keep the debug info but resolve any addresses referring to such code as zero (BFD) or a small positive integer (zero + relocation addend – GOLD). Try to filter out this debug info by comparing it to the lowest code address in the module.
Definition at line 567 of file SymbolFileDWARF.h.
Referenced by InitializeFirstCodeAddress(), InitializeFirstCodeAddressRecursive(), ParseBlocksRecursive(), ParseFunction(), and ParseLineTable().
m_forward_decl_compiler_type_to_die
llvm::DenseMap<lldb::opaque_compiler_type_t, DIERef> lldb_private::plugin::dwarf::SymbolFileDWARF::m_forward_decl_compiler_type_to_die protected
Definition at line 557 of file SymbolFileDWARF.h.
Referenced by GetForwardDeclCompilerTypeToDIE().
m_function_scope_qualified_name_map
NameToOffsetMap lldb_private::plugin::dwarf::SymbolFileDWARF::m_function_scope_qualified_name_map protected
Definition at line 548 of file SymbolFileDWARF.h.
Referenced by GetMangledNamesForFunction(), and ParseType().
m_global_aranges_up
std::unique_ptr<GlobalVariableMap> lldb_private::plugin::dwarf::SymbolFileDWARF::m_global_aranges_up protected
Definition at line 537 of file SymbolFileDWARF.h.
Referenced by GetGlobalAranges().
m_index
std::unique_ptr<DWARFIndex> lldb_private::plugin::dwarf::SymbolFileDWARF::m_index protected
Definition at line 543 of file SymbolFileDWARF.h.
Referenced by Dump(), FindCompleteObjCDefinitionTypeForDIE(), FindDefinitionDIE(), FindFunctionDefinition(), FindFunctions(), FindFunctions(), FindGlobalVariables(), FindGlobalVariables(), FindNamespace(), FindTypes(), GetDebugInfoIndexTime(), getIndex(), GetObjCMethods(), InitializeObject(), ParseVariablesForContext(), PreloadSymbols(), and ResetStatistics().
m_info
std::unique_ptr<DWARFDebugInfo> lldb_private::plugin::dwarf::SymbolFileDWARF::m_info protected
Definition at line 534 of file SymbolFileDWARF.h.
Referenced by DebugInfo().
m_info_once_flag
llvm::once_flag lldb_private::plugin::dwarf::SymbolFileDWARF::m_info_once_flag protected
Definition at line 533 of file SymbolFileDWARF.h.
Referenced by DebugInfo().
m_lldb_cu_to_dwarf_unit
std::vector<uint32_t> lldb_private::plugin::dwarf::SymbolFileDWARF::m_lldb_cu_to_dwarf_unit protected
Definition at line 560 of file SymbolFileDWARF.h.
Referenced by BuildCuTranslationTable(), CalculateNumCompileUnits(), and GetDWARFUnitIndex().
m_parse_time
StatsDuration lldb_private::plugin::dwarf::SymbolFileDWARF::m_parse_time protected
Definition at line 568 of file SymbolFileDWARF.h.
Referenced by DebugAbbrev(), GetDebugInfoParseTime(), GetDebugInfoParseTimeRef(), GetTypeUnitSupportFiles(), ParseDebugMacros(), ParseLineTable(), ParseSupportFiles(), and ResetStatistics().
m_type_unit_support_files
llvm::DenseMap<dw_offset_t, std::unique_ptr<SupportFileList> > lldb_private::plugin::dwarf::SymbolFileDWARF::m_type_unit_support_files protected
Definition at line 559 of file SymbolFileDWARF.h.
Referenced by GetTypeUnitSupportFiles().
m_unique_ast_type_map
UniqueDWARFASTTypeMap lldb_private::plugin::dwarf::SymbolFileDWARF::m_unique_ast_type_map protected
Definition at line 549 of file SymbolFileDWARF.h.
Referenced by GetUniqueDWARFASTTypeMap().
The documentation for this class was generated from the following files:
SymbolFileDWARF.h
SymbolFileDWARF.cpp