LLDB: lldb_private::StopInfoMachException Class Reference
lldb_private::StopInfoMachException Class Reference
#include <StopInfoMachException.h>
Public Member Functions
StopInfoMachException (Thread &thread, uint32_t exc_type, uint32_t exc_data_count, uint64_t exc_code, uint64_t exc_subcode, bool not_stepping_but_got_singlestep_exception)
~StopInfoMachException () override=default
lldb::StopReason GetStopReason () const override
const char * GetDescription () override
uint32_t GetStopReasonDataCount () const override
uint64_t GetStopReasonDataAtIndex (uint32_t idx) override
std::optional< lldb::addr_t > GetTagFaultAddress () const
bool WasContinueInterrupted (Thread &thread) override
A Continue operation can result in a false stop event before any execution has happened.
Public Member Functions inherited from lldb_private::StopInfo
StopInfo (Thread &thread, uint64_t value)
virtual ~StopInfo ()=default
bool IsValid () const
void SetThread (const lldb::ThreadSP &thread_sp)
lldb::ThreadSP GetThread () const
uint64_t GetValue () const
virtual bool ShouldStopSynchronous (Event *event_ptr)
void OverrideShouldNotify (bool override_value)
virtual bool ShouldNotify (Event *event_ptr)
virtual void WillResume (lldb::StateType resume_state)
virtual void SetDescription (const char *desc_cstr)
virtual std::optional< uint32_t > GetSuggestedStackFrameIndex (bool inlined_stack)
This gives the StopInfo a chance to suggest a stack frame to select.
virtual bool IsValidForOperatingSystemThread (Thread &thread)
void OverrideShouldStop (bool override_value)
bool GetOverrideShouldStop ()
bool GetOverriddenShouldStopValue ()
StructuredData::ObjectSP GetExtendedInfo ()
virtual bool ShouldShow () const
Returns true if this is a stop reason that should be shown to a user when viewing the thread with this stop info.
virtual bool ShouldSelect () const
Returns true if this is a stop reason that should cause a thread to be selected when stopping.
Static Public Member Functions
static lldb::StopInfoSP CreateStopReasonWithMachException (Thread &thread, uint32_t exc_type, uint32_t exc_data_count, uint64_t exc_code, uint64_t exc_sub_code, uint64_t exc_sub_sub_code, bool pc_already_adjusted=true, bool adjust_pc_if_needed=false)
Static Public Member Functions inherited from lldb_private::StopInfo
static lldb::StopInfoSP CreateStopReasonWithBreakpointSiteID (Thread &thread, lldb::break_id_t break_id)
static lldb::StopInfoSP CreateStopReasonWithBreakpointSiteID (Thread &thread, lldb::break_id_t break_id, bool should_stop)
static lldb::StopInfoSP CreateStopReasonWithWatchpointID (Thread &thread, lldb::break_id_t watch_id, bool silently_continue=false)
static lldb::StopInfoSP CreateStopReasonWithSignal (Thread &thread, int signo, const char *description=nullptr, std::optional< int > code=std::nullopt)
static lldb::StopInfoSP CreateStopReasonWithInterrupt (Thread &thread, int signo, const char *description)
static lldb::StopInfoSP CreateStopReasonToTrace (Thread &thread)
static lldb::StopInfoSP CreateStopReasonWithPlan (lldb::ThreadPlanSP &plan, lldb::ValueObjectSP return_valobj_sp, lldb::ExpressionVariableSP expression_variable_sp)
static lldb::StopInfoSP CreateStopReasonWithException (Thread &thread, const char *description)
static lldb::StopInfoSP CreateStopReasonWithExec (Thread &thread)
static lldb::StopInfoSP CreateStopReasonProcessorTrace (Thread &thread, const char *description)
static lldb::StopInfoSP CreateStopReasonHistoryBoundary (Thread &thread, const char *description)
static lldb::StopInfoSP CreateStopReasonFork (Thread &thread, lldb::pid_t child_pid, lldb::tid_t child_tid)
static lldb::StopInfoSP CreateStopReasonVFork (Thread &thread, lldb::pid_t child_pid, lldb::tid_t child_tid)
static lldb::StopInfoSP CreateStopReasonVForkDone (Thread &thread)
static lldb::ValueObjectSP GetReturnValueObject (lldb::StopInfoSP &stop_info_sp)
static lldb::ExpressionVariableSP GetExpressionVariable (lldb::StopInfoSP &stop_info_sp)
static lldb::ValueObjectSP GetCrashingDereference (lldb::StopInfoSP &stop_info_sp, lldb::addr_t *crashing_address=nullptr)
Protected Attributes
uint32_t m_exc_data_count
uint64_t m_exc_code
uint64_t m_exc_subcode
bool m_not_stepping_but_got_singlestep_exception
Protected Attributes inherited from lldb_private::StopInfo
lldb::ThreadWP m_thread_wp
uint32_t m_stop_id
uint32_t m_resume_id
uint64_t m_value
std::string m_description
LazyBool m_override_should_notify
LazyBool m_override_should_stop
StructuredData::ObjectSP m_extended_info
Private Member Functions
bool DeterminePtrauthFailure (ExecutionContext &exe_ctx)
Determine the pointer-authentication related failure that caused this exception.
bool DetermineTagMismatch ()
Additional Inherited Members
Protected Member Functions inherited from lldb_private::StopInfo
virtual void PerformAction (Event *event_ptr)
virtual bool DoShouldNotify (Event *event_ptr)
virtual bool ShouldStop (Event *event_ptr)
bool HasTargetRunSinceMe ()
void MakeStopInfoValid ()
Detailed Description
Definition at line 25 of file StopInfoMachException.h.
Constructor & Destructor Documentation
StopInfoMachException()
lldb_private::StopInfoMachException::StopInfoMachException (Thread & thread, uint32_t exc_type, uint32_t exc_data_count, uint64_t exc_code, uint64_t exc_subcode, bool not_stepping_but_got_singlestep_exception) inline
Definition at line 35 of file StopInfoMachException.h.
References m_exc_code, m_exc_data_count, m_exc_subcode, m_not_stepping_but_got_singlestep_exception, lldb_private::StopInfo::StopInfo(), and lldb_private::StopInfo::Thread.
~StopInfoMachException()
lldb_private::StopInfoMachException::~StopInfoMachException () override default
Member Function Documentation
CreateStopReasonWithMachException()
StopInfoSP StopInfoMachException::CreateStopReasonWithMachException (Thread & thread, uint32_t exc_type, uint32_t exc_data_count, uint64_t exc_code, uint64_t exc_sub_code, uint64_t exc_sub_sub_code, bool pc_already_adjusted = true, bool adjust_pc_if_needed = false) static
Definition at line 608 of file StopInfoMachException.cpp.
References lldb_private::StopInfo::CreateStopReasonToTrace(), lldb_private::StopInfo::CreateStopReasonWithBreakpointSiteID(), lldb_private::StopInfo::CreateStopReasonWithExec(), lldb_private::StopInfo::CreateStopReasonWithSignal(), lldb_private::StopInfo::CreateStopReasonWithWatchpointID(), lldb::eStateStepping, lldb_private::Target::GetArchitecture(), lldb_private::ArchSpec::GetMachine(), lldb_private::Target::GetProcessSP(), lldb_private::ExecutionContext::GetTargetPtr(), pc, lldb_private::DynamicLoader::ProcessDidExec(), and lldb_private::StopInfo::Thread.
Referenced by lldb_private::ScriptedThread::CalculateStopInfo(), lldb_private::minidump::ProcessMinidump::RefreshStateAfterStop(), ThreadKDP::SetStopInfoFrom_KDP_EXCEPTION(), and lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo().
DeterminePtrauthFailure()
bool StopInfoMachException::DeterminePtrauthFailure (ExecutionContext & exe_ctx) private
Determine the pointer-authentication related failure that caused this exception.
Returns true and fills out the failure description if there is auth-related failure, and returns false otherwise.
Definition at line 118 of file StopInfoMachException.cpp.
References DescribeAddressBriefly(), lldb_private::ArchSpec::eCore_arm_arm64e, lldb_private::Process::GetABI(), lldb_private::Target::GetArchitecture(), lldb_private::RegisterValue::GetAsUInt64(), lldb_private::ArchSpec::GetCore(), lldb_private::Address::GetLoadAddress(), lldb_private::ExecutionContext::GetProcessPtr(), GetPtrauthInstructionInfo(), lldb_private::ExecutionContext::GetRegisterContext(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::StreamString::GetString(), lldb_private::ExecutionContext::GetTargetPtr(), lldb_private::ExecutionContext::GetThreadPtr(), lldb_private::ExecutionContext::HasProcessScope(), lldb_private::ExecutionContext::HasTargetScope(), lldb_private::ExecutionContext::HasThreadScope(), lldb_private::StopInfo::m_description, m_exc_code, m_exc_data_count, m_exc_subcode, lldb_private::StopInfo::m_value, lldb_private::Stream::Printf(), lldb_private::RegisterContext::ReadRegister(), lldb_private::Target::ResolveLoadAddress(), and lldb_private::StopInfo::Thread.
Referenced by GetDescription().
DetermineTagMismatch()
bool StopInfoMachException::DetermineTagMismatch () private
Definition at line 96 of file StopInfoMachException.cpp.
References g_mte_tag_mask, g_mte_tag_shift, lldb_private::StreamString::GetString(), GetTagFaultAddress(), lldb_private::StopInfo::m_description, m_exc_code, and lldb_private::Stream::Printf().
Referenced by GetDescription().
GetDescription()
const char * StopInfoMachException::GetDescription () override virtual
Reimplemented from lldb_private::StopInfo.
Definition at line 255 of file StopInfoMachException.cpp.
References DeterminePtrauthFailure(), DetermineTagMismatch(), lldb::eStopReasonInvalid, lldb_private::Target::GetArchitecture(), lldb_private::ArchSpec::GetMachine(), lldb_private::StreamString::GetString(), lldb_private::ExecutionContext::GetTargetPtr(), lldb_private::StopInfo::GetValue(), lldb_private::StopInfo::m_description, m_exc_code, m_exc_data_count, m_exc_subcode, lldb_private::StopInfo::m_thread_wp, lldb_private::StopInfo::m_value, lldb_private::Stream::Printf(), lldb_private::Stream::PutChar(), and lldb_private::Stream::PutCString().
GetStopReason()
lldb::StopReason lldb_private::StopInfoMachException::GetStopReason () const inline override virtual
Implements lldb_private::StopInfo.
Definition at line 46 of file StopInfoMachException.h.
References lldb::eStopReasonException.
GetStopReasonDataAtIndex()
uint64_t lldb_private::StopInfoMachException::GetStopReasonDataAtIndex (uint32_t idx) inline override virtual
Reimplemented from lldb_private::StopInfo.
Definition at line 61 of file StopInfoMachException.h.
References GetStopReasonDataCount(), lldb_private::StopInfo::GetValue(), m_exc_code, and m_exc_subcode.
GetStopReasonDataCount()
uint32_t lldb_private::StopInfoMachException::GetStopReasonDataCount () const inline override virtual
Reimplemented from lldb_private::StopInfo.
Definition at line 52 of file StopInfoMachException.h.
References m_exc_data_count.
Referenced by GetStopReasonDataAtIndex().
GetTagFaultAddress()
std::optional< addr_t > StopInfoMachException::GetTagFaultAddress () const
Definition at line 80 of file StopInfoMachException.cpp.
References m_exc_code, m_exc_data_count, m_exc_subcode, and lldb_private::StopInfo::m_value.
Referenced by DetermineTagMismatch().
WasContinueInterrupted()
bool StopInfoMachException::WasContinueInterrupted (Thread & thread) override virtual
A Continue operation can result in a false stop event before any execution has happened.
We need to detect this and silently continue again one more time.
Reimplemented from lldb_private::StopInfo.
Definition at line 839 of file StopInfoMachException.cpp.
References lldb_private::GetLog(), LLDB_LOGF, m_not_stepping_but_got_singlestep_exception, lldb_private::Step, and lldb_private::StopInfo::Thread.
Member Data Documentation
m_exc_code
uint64_t lldb_private::StopInfoMachException::m_exc_code protected
Definition at line 101 of file StopInfoMachException.h.
Referenced by DeterminePtrauthFailure(), DetermineTagMismatch(), GetDescription(), GetStopReasonDataAtIndex(), GetTagFaultAddress(), and StopInfoMachException().
m_exc_data_count
uint32_t lldb_private::StopInfoMachException::m_exc_data_count protected
Definition at line 100 of file StopInfoMachException.h.
Referenced by DeterminePtrauthFailure(), GetDescription(), GetStopReasonDataCount(), GetTagFaultAddress(), and StopInfoMachException().
m_exc_subcode
uint64_t lldb_private::StopInfoMachException::m_exc_subcode protected
Definition at line 102 of file StopInfoMachException.h.
Referenced by DeterminePtrauthFailure(), GetDescription(), GetStopReasonDataAtIndex(), GetTagFaultAddress(), and StopInfoMachException().
m_not_stepping_but_got_singlestep_exception
bool lldb_private::StopInfoMachException::m_not_stepping_but_got_singlestep_exception protected
Definition at line 104 of file StopInfoMachException.h.
Referenced by StopInfoMachException(), and WasContinueInterrupted().
The documentation for this class was generated from the following files:
StopInfoMachException.h
StopInfoMachException.cpp