LLDB: lldb::SBAddressRange Class Reference
lldb::SBAddressRange Class Reference
#include <SBAddressRange.h>
Public Member Functions
SBAddressRange ()
SBAddressRange (const lldb::SBAddressRange &rhs)
SBAddressRange (lldb::SBAddress addr, lldb::addr_t byte_size)
~SBAddressRange ()
const lldb::SBAddressRange & operator= (const lldb::SBAddressRange &rhs)
void Clear ()
bool IsValid () const
Check the address range refers to a valid base address and has a byte size greater than zero.
lldb::SBAddress GetBaseAddress () const
Get the base address of the range.
lldb::addr_t GetByteSize () const
Get the byte size of this range.
bool operator== (const SBAddressRange &rhs)
bool operator!= (const SBAddressRange &rhs)
bool GetDescription (lldb::SBStream &description, const SBTarget target)
Private Member Functions
lldb_private::AddressRange & ref () const
Private Attributes
AddressRangeUP m_opaque_up
Friends
class SBAddressRangeList
class SBBlock
class SBFunction
class SBProcess
Detailed Description
Definition at line 20 of file SBAddressRange.h.
Constructor & Destructor Documentation
SBAddressRange() [1/3]
SBAddressRange::SBAddressRange ()
Definition at line 24 of file SBAddressRange.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by operator!=(), operator=(), operator==(), SBAddressRange(), and ~SBAddressRange().
SBAddressRange() [2/3]
SBAddressRange::SBAddressRange (const lldb::SBAddressRange & rhs)
Definition at line 29 of file SBAddressRange.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBAddressRange().
SBAddressRange() [3/3]
SBAddressRange::SBAddressRange (lldb::SBAddress addr, lldb::addr_t byte_size)
Definition at line 35 of file SBAddressRange.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and ref().
~SBAddressRange()
SBAddressRange::~SBAddressRange () default
References Clear(), GetBaseAddress(), GetByteSize(), GetDescription(), IsValid(), operator!=(), operator=(), operator==(), and SBAddressRange().
Member Function Documentation
Clear()
void SBAddressRange::Clear ()
Definition at line 62 of file SBAddressRange.cpp.
References lldb_private::AddressRange::Clear(), LLDB_INSTRUMENT_VA, and ref().
Referenced by ~SBAddressRange().
GetBaseAddress()
lldb::SBAddress SBAddressRange::GetBaseAddress () const
Get the base address of the range.
Returns
Base address object.
Definition at line 74 of file SBAddressRange.cpp.
References GetBaseAddress(), LLDB_INSTRUMENT_VA, ref(), and lldb::SBAddress.
Referenced by GetBaseAddress(), and ~SBAddressRange().
GetByteSize()
lldb::addr_t SBAddressRange::GetByteSize () const
Get the byte size of this range.
Returns
The size in bytes of this address range.
Definition at line 80 of file SBAddressRange.cpp.
References lldb_private::AddressRange::GetByteSize(), LLDB_INSTRUMENT_VA, and ref().
Referenced by ~SBAddressRange().
GetDescription()
bool SBAddressRange::GetDescription (lldb::SBStream & description, const SBTarget target)
Definition at line 86 of file SBAddressRange.cpp.
References lldb_private::AddressRange::GetDescription(), lldb::SBTarget::GetSP(), LLDB_INSTRUMENT_VA, ref(), and lldb::SBStream::ref().
Referenced by lldb::SBAddressRangeList::GetDescription(), and ~SBAddressRange().
IsValid()
bool SBAddressRange::IsValid () const
Check the address range refers to a valid base address and has a byte size greater than zero.
Returns
True if the address range is valid, false otherwise.
Definition at line 68 of file SBAddressRange.cpp.
References lldb_private::AddressRange::IsValid(), LLDB_INSTRUMENT_VA, and ref().
Referenced by ~SBAddressRange().
operator!=()
bool SBAddressRange::operator!= (const SBAddressRange & rhs)
Definition at line 56 of file SBAddressRange.cpp.
References LLDB_INSTRUMENT_VA, and SBAddressRange().
Referenced by ~SBAddressRange().
operator=()
const SBAddressRange & SBAddressRange::operator= (const lldb::SBAddressRange & rhs)
Definition at line 42 of file SBAddressRange.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBAddressRange().
Referenced by ~SBAddressRange().
operator==()
bool SBAddressRange::operator== (const SBAddressRange & rhs)
Definition at line 50 of file SBAddressRange.cpp.
References LLDB_INSTRUMENT_VA, ref(), and SBAddressRange().
Referenced by ~SBAddressRange().
ref()
lldb_private::AddressRange & SBAddressRange::ref () const private
Definition at line 93 of file SBAddressRange.cpp.
References m_opaque_up.
Referenced by Clear(), lldb::SBProcess::FindInMemory(), GetBaseAddress(), GetByteSize(), GetDescription(), IsValid(), operator==(), SBAddressRange(), and SBProcess.
Friends And Related Symbol Documentation
SBAddressRangeList
friend class SBAddressRangeList friend
Definition at line 60 of file SBAddressRange.h.
References SBAddressRangeList.
Referenced by SBAddressRangeList.
SBBlock
friend class SBBlock friend
Definition at line 61 of file SBAddressRange.h.
References SBBlock.
Referenced by SBBlock.
SBFunction
friend class SBFunction friend
Definition at line 62 of file SBAddressRange.h.
References SBFunction.
Referenced by SBFunction.
SBProcess
friend class SBProcess friend
Definition at line 63 of file SBAddressRange.h.
References ref(), and SBProcess.
Referenced by SBProcess.
Member Data Documentation
m_opaque_up
AddressRangeUP lldb::SBAddressRange::m_opaque_up private
Definition at line 67 of file SBAddressRange.h.
Referenced by lldb::SBAddressRangeList::Append(), lldb::SBAddressRangeList::GetAddressRangeAtIndex(), operator=(), ref(), SBAddressRange(), SBAddressRange(), and SBAddressRange().
The documentation for this class was generated from the following files:
SBAddressRange.h
SBAddressRange.cpp