LLDB: lldb_private::TypeFormatImpl::Flags Class Reference
lldb_private::TypeFormatImpl::Flags Class Reference
#include <TypeFormat.h>
Public Member Functions
Flags ()
Flags (const Flags &other)
Flags (uint32_t value)
Flags & operator= (const Flags &rhs)
Flags & operator= (const uint32_t &rhs)
Flags & Clear ()
bool GetCascades () const
Flags & SetCascades (bool value=true)
bool GetSkipPointers () const
Flags & SetSkipPointers (bool value=true)
bool GetSkipReferences () const
Flags & SetSkipReferences (bool value=true)
bool GetNonCacheable () const
Flags & SetNonCacheable (bool value=true)
uint32_t GetValue ()
void SetValue (uint32_t value)
Private Attributes
uint32_t m_flags = lldb::eTypeOptionCascade
Detailed Description
Definition at line 26 of file TypeFormat.h.
Constructor & Destructor Documentation
Flags() [1/3]
lldb_private::TypeFormatImpl::Flags::Flags () inline
Definition at line 28 of file TypeFormat.h.
Referenced by Clear(), Flags(), operator=(), operator=(), SetCascades(), SetNonCacheable(), SetSkipPointers(), and SetSkipReferences().
Flags() [2/3]
lldb_private::TypeFormatImpl::Flags::Flags (const Flags & other) inline
Definition at line 30 of file TypeFormat.h.
References Flags(), and m_flags.
Flags() [3/3]
lldb_private::TypeFormatImpl::Flags::Flags (uint32_t value) inline
Definition at line 32 of file TypeFormat.h.
References m_flags.
Member Function Documentation
Clear()
Flags & lldb_private::TypeFormatImpl::Flags::Clear () inline
Definition at line 46 of file TypeFormat.h.
References Flags(), and m_flags.
GetCascades()
bool lldb_private::TypeFormatImpl::Flags::GetCascades () const inline
Definition at line 51 of file TypeFormat.h.
References m_flags.
GetNonCacheable()
bool lldb_private::TypeFormatImpl::Flags::GetNonCacheable () const inline
Definition at line 89 of file TypeFormat.h.
References m_flags.
GetSkipPointers()
bool lldb_private::TypeFormatImpl::Flags::GetSkipPointers () const inline
Definition at line 63 of file TypeFormat.h.
References m_flags.
GetSkipReferences()
bool lldb_private::TypeFormatImpl::Flags::GetSkipReferences () const inline
Definition at line 76 of file TypeFormat.h.
References m_flags.
GetValue()
uint32_t lldb_private::TypeFormatImpl::Flags::GetValue () inline
Definition at line 102 of file TypeFormat.h.
References m_flags.
operator=() [1/2]
Flags & lldb_private::TypeFormatImpl::Flags::operator= (const Flags & rhs) inline
Definition at line 34 of file TypeFormat.h.
References Flags(), and m_flags.
operator=() [2/2]
Flags & lldb_private::TypeFormatImpl::Flags::operator= (const uint32_t & rhs) inline
Definition at line 41 of file TypeFormat.h.
References Flags(), and m_flags.
SetCascades()
Flags & lldb_private::TypeFormatImpl::Flags::SetCascades (bool value = true) inline
Definition at line 55 of file TypeFormat.h.
References Flags(), and m_flags.
Referenced by lldb_private::FormatManager::LoadSystemFormatters().
SetNonCacheable()
Flags & lldb_private::TypeFormatImpl::Flags::SetNonCacheable (bool value = true) inline
Definition at line 94 of file TypeFormat.h.
References Flags(), and m_flags.
SetSkipPointers()
Flags & lldb_private::TypeFormatImpl::Flags::SetSkipPointers (bool value = true) inline
Definition at line 68 of file TypeFormat.h.
References Flags(), and m_flags.
Referenced by lldb_private::FormatManager::LoadSystemFormatters().
SetSkipReferences()
Flags & lldb_private::TypeFormatImpl::Flags::SetSkipReferences (bool value = true) inline
Definition at line 81 of file TypeFormat.h.
References Flags(), and m_flags.
Referenced by lldb_private::FormatManager::LoadSystemFormatters().
SetValue()
void lldb_private::TypeFormatImpl::Flags::SetValue (uint32_t value) inline
Definition at line 104 of file TypeFormat.h.
References m_flags.
Member Data Documentation
m_flags
uint32_t lldb_private::TypeFormatImpl::Flags::m_flags = lldb::eTypeOptionCascade private
Definition at line 107 of file TypeFormat.h.
Referenced by Clear(), Flags(), Flags(), GetCascades(), GetNonCacheable(), GetSkipPointers(), GetSkipReferences(), GetValue(), operator=(), operator=(), SetCascades(), SetNonCacheable(), SetSkipPointers(), SetSkipReferences(), and SetValue().
The documentation for this class was generated from the following file:
TypeFormat.h