LLDB: lldb_private::TypeAndOrName Class Reference
lldb_private::TypeAndOrName Class Reference
Sometimes you can find the name of the type corresponding to an object, but we don't have debug information for it.
#include <Type.h>
Public Member Functions
TypeAndOrName ()=default
TypeAndOrName (lldb::TypeSP &type_sp)
TypeAndOrName (const CompilerType &compiler_type)
TypeAndOrName (const char *type_str)
TypeAndOrName (ConstString &type_const_string)
bool operator== (const TypeAndOrName &other) const
bool operator!= (const TypeAndOrName &other) const
ConstString GetName () const
CompilerType GetCompilerType () const
void SetName (ConstString type_name)
void SetName (const char *type_name_cstr)
void SetName (llvm::StringRef name)
void SetTypeSP (lldb::TypeSP type_sp)
void SetCompilerType (CompilerType compiler_type)
bool IsEmpty () const
bool HasName () const
bool HasCompilerType () const
bool HasType () const
void Clear ()
operator bool ()
Private Attributes
CompilerType m_compiler_type
ConstString m_type_name
Detailed Description
Sometimes you can find the name of the type corresponding to an object, but we don't have debug information for it.
If that is the case, you can return one of these objects, and then if it has a full type, you can use that, but if not at least you can print the name for informational purposes.
Definition at line 779 of file Type.h.
Constructor & Destructor Documentation
TypeAndOrName() [1/5]
lldb_private::TypeAndOrName::TypeAndOrName () default
Referenced by operator!=(), operator==(), and TypeAndOrName().
TypeAndOrName() [2/5]
TypeAndOrName::TypeAndOrName (lldb::TypeSP & type_sp)
Definition at line 869 of file Type.cpp.
References m_compiler_type, and m_type_name.
TypeAndOrName() [3/5]
lldb_private::TypeAndOrName::TypeAndOrName (const CompilerType & compiler_type)
References TypeAndOrName().
TypeAndOrName() [4/5]
TypeAndOrName::TypeAndOrName (const char * type_str)
Definition at line 876 of file Type.cpp.
References m_type_name.
TypeAndOrName() [5/5]
TypeAndOrName::TypeAndOrName (ConstString & type_const_string)
Definition at line 879 of file Type.cpp.
References m_type_name.
Member Function Documentation
Clear()
void TypeAndOrName::Clear ()
Definition at line 932 of file Type.cpp.
References m_compiler_type, and m_type_name.
Referenced by lldb_private::AppleObjCRuntimeV1::GetDynamicTypeAndAddress(), lldb_private::AppleObjCRuntimeV2::GetDynamicTypeAndAddress(), lldb_private::ItaniumABILanguageRuntime::GetDynamicTypeAndAddress(), and SetTypeSP().
GetCompilerType()
CompilerType lldb_private::TypeAndOrName::GetCompilerType () const inline
Definition at line 793 of file Type.h.
References m_compiler_type.
Referenced by lldb_private::AppleObjCRuntime::FixUpDynamicType(), lldb_private::GNUstepObjCRuntime::FixUpDynamicType(), lldb_private::ItaniumABILanguageRuntime::FixUpDynamicType(), lldb_private::ItaniumABILanguageRuntime::GetDynamicTypeAndAddress(), and lldb_private::ValueObjectDynamicValue::UpdateValue().
GetName()
ConstString TypeAndOrName::GetName () const
Definition at line 894 of file Type.cpp.
References m_compiler_type, and m_type_name.
Referenced by lldb_private::AppleObjCRuntime::FixUpDynamicType(), lldb_private::GNUstepObjCRuntime::FixUpDynamicType(), and lldb_private::ItaniumABILanguageRuntime::FixUpDynamicType().
HasCompilerType()
bool TypeAndOrName::HasCompilerType () const
Definition at line 939 of file Type.cpp.
References m_compiler_type.
Referenced by HasType().
HasName()
bool TypeAndOrName::HasName () const
Definition at line 937 of file Type.cpp.
References m_type_name.
HasType()
bool lldb_private::TypeAndOrName::HasType () const inline
Definition at line 811 of file Type.h.
References HasCompilerType().
Referenced by lldb_private::AppleObjCRuntime::FixUpDynamicType(), lldb_private::GNUstepObjCRuntime::FixUpDynamicType(), lldb_private::ItaniumABILanguageRuntime::FixUpDynamicType(), and lldb_private::ValueObjectDynamicValue::UpdateValue().
IsEmpty()
bool TypeAndOrName::IsEmpty () const
Definition at line 928 of file Type.cpp.
References m_compiler_type, and m_type_name.
Referenced by lldb_private::AppleObjCRuntimeV1::GetDynamicTypeAndAddress(), lldb_private::AppleObjCRuntimeV2::GetDynamicTypeAndAddress(), and operator bool().
operator bool()
lldb_private::TypeAndOrName::operator bool () inline explicit
Definition at line 815 of file Type.h.
References IsEmpty().
operator!=()
bool TypeAndOrName::operator!= (const TypeAndOrName & other) const
Definition at line 890 of file Type.cpp.
References TypeAndOrName().
operator==()
bool TypeAndOrName::operator== (const TypeAndOrName & other) const
Definition at line 882 of file Type.cpp.
References m_compiler_type, m_type_name, and TypeAndOrName().
SetCompilerType()
void TypeAndOrName::SetCompilerType (CompilerType compiler_type)
Definition at line 922 of file Type.cpp.
References m_compiler_type, and m_type_name.
Referenced by lldb_private::AppleObjCRuntime::FixUpDynamicType(), lldb_private::GNUstepObjCRuntime::FixUpDynamicType(), lldb_private::ItaniumABILanguageRuntime::FixUpDynamicType(), and lldb_private::AppleObjCRuntimeV2::GetDynamicTypeAndAddress().
SetName() [1/3]
void TypeAndOrName::SetName (const char * type_name_cstr)
Definition at line 906 of file Type.cpp.
References m_type_name.
SetName() [2/3]
void TypeAndOrName::SetName (ConstString type_name)
Definition at line 902 of file Type.cpp.
References m_type_name.
Referenced by lldb_private::AppleObjCRuntime::FixUpDynamicType(), lldb_private::GNUstepObjCRuntime::FixUpDynamicType(), lldb_private::ItaniumABILanguageRuntime::FixUpDynamicType(), lldb_private::AppleObjCRuntimeV1::GetDynamicTypeAndAddress(), lldb_private::AppleObjCRuntimeV2::GetDynamicTypeAndAddress(), and lldb_private::ItaniumABILanguageRuntime::GetTypeInfo().
SetName() [3/3]
void TypeAndOrName::SetName (llvm::StringRef name)
Definition at line 910 of file Type.cpp.
References m_type_name.
SetTypeSP()
void TypeAndOrName::SetTypeSP (lldb::TypeSP type_sp)
Definition at line 914 of file Type.cpp.
References Clear(), m_compiler_type, and m_type_name.
Referenced by lldb_private::AppleObjCRuntimeV2::GetDynamicTypeAndAddress(), and lldb_private::ItaniumABILanguageRuntime::GetTypeInfo().
Member Data Documentation
m_compiler_type
CompilerType lldb_private::TypeAndOrName::m_compiler_type private
Definition at line 818 of file Type.h.
Referenced by Clear(), GetCompilerType(), GetName(), HasCompilerType(), IsEmpty(), operator==(), SetCompilerType(), SetTypeSP(), and TypeAndOrName().
m_type_name
ConstString lldb_private::TypeAndOrName::m_type_name private
Definition at line 819 of file Type.h.
Referenced by Clear(), GetName(), HasName(), IsEmpty(), operator==(), SetCompilerType(), SetName(), SetName(), SetName(), SetTypeSP(), TypeAndOrName(), TypeAndOrName(), and TypeAndOrName().
The documentation for this class was generated from the following files:
Type.h
Type.cpp