LLDB: lldb_private::VerboseTrapFrameRecognizer Class Reference
lldb_private::VerboseTrapFrameRecognizer Class Reference
When a thread stops, it checks the current frame contains a Verbose Trap diagnostic.
#include <VerboseTrapFrameRecognizer.h>
Public Member Functions
std::string GetName () override
lldb::RecognizedStackFrameSP RecognizeFrame (lldb::StackFrameSP frame) override
Public Member Functions inherited from lldb_private::StackFrameRecognizer
virtual ~StackFrameRecognizer ()=default
Detailed Description
When a thread stops, it checks the current frame contains a Verbose Trap diagnostic.
If so, it returns a VerboseTrapRecognizedStackFrame holding the diagnostic a stop reason description with and the parent frame as the most relavant frame.
Definition at line 35 of file VerboseTrapFrameRecognizer.h.
Member Function Documentation
GetName()
std::string lldb_private::VerboseTrapFrameRecognizer::GetName () inline override virtual
Reimplemented from lldb_private::StackFrameRecognizer.
Definition at line 37 of file VerboseTrapFrameRecognizer.h.
RecognizeFrame()
lldb::RecognizedStackFrameSP VerboseTrapFrameRecognizer::RecognizeFrame (lldb::StackFrameSP frame) override virtual
Reimplemented from lldb_private::StackFrameRecognizer.
Definition at line 59 of file VerboseTrapFrameRecognizer.cpp.
References lldb_private::SymbolContext::block, FindMostRelevantFrame(), lldb_private::Block::GetContainingInlinedBlock(), lldb_private::Block::GetInlinedFunctionInfo(), lldb_private::GetLog(), lldb_private::InlineFunctionInfo::GetName(), lldb_private::ConstString::GetStringRef(), LLDB_LOG, LLDB_LOGF, and lldb_private::Unwind.
The documentation for this class was generated from the following files:
VerboseTrapFrameRecognizer.h
VerboseTrapFrameRecognizer.cpp