LLDB: lldb_private::DiagnosticError Class Reference
lldb_private::DiagnosticError Class Reference abstract
#include <DiagnosticsRendering.h>
Public Member Functions
DiagnosticError (std::error_code ec)
lldb::ErrorType GetErrorType () const override
virtual llvm::ArrayRef< DiagnosticDetail > GetDetails () const =0
StructuredData::ObjectSP GetAsStructuredData () const override
Static Public Attributes
static char ID
Detailed Description
Definition at line 84 of file DiagnosticsRendering.h.
Constructor & Destructor Documentation
DiagnosticError()
lldb_private::DiagnosticError::DiagnosticError (std::error_code ec) inline
Definition at line 88 of file DiagnosticsRendering.h.
Member Function Documentation
GetAsStructuredData()
StructuredData::ObjectSP lldb_private::DiagnosticError::GetAsStructuredData () const inline override
Definition at line 91 of file DiagnosticsRendering.h.
References GetDetails(), and lldb_private::Serialize().
GetDetails()
virtual llvm::ArrayRef< DiagnosticDetail > lldb_private::DiagnosticError::GetDetails () const pure virtual
Referenced by GetAsStructuredData().
GetErrorType()
lldb::ErrorType lldb_private::DiagnosticError::GetErrorType () const override
Definition at line 21 of file DiagnosticsRendering.cpp.
References lldb::eErrorTypeExpression.
Member Data Documentation
ID
char lldb_private::DiagnosticError::ID static
Definition at line 94 of file DiagnosticsRendering.h.
The documentation for this class was generated from the following files:
DiagnosticsRendering.h
DiagnosticsRendering.cpp