LLDB: lldb_private::ModuleListProperties Class Reference
lldb_private::ModuleListProperties Class Reference
#include <ModuleList.h>
Public Member Functions
ModuleListProperties ()
FileSpec GetClangModulesCachePath () const
bool SetClangModulesCachePath (const FileSpec &path)
bool GetEnableExternalLookup () const
bool SetEnableExternalLookup (bool new_value)
lldb::SymbolSharedCacheUse GetSharedCacheBinaryLoading () const
bool GetEnableLLDBIndexCache () const
bool SetEnableLLDBIndexCache (bool new_value)
uint64_t GetLLDBIndexCacheMaxByteSize ()
uint64_t GetLLDBIndexCacheMaxPercent ()
uint64_t GetLLDBIndexCacheExpirationDays ()
FileSpec GetLLDBIndexCachePath () const
bool SetLLDBIndexCachePath (const FileSpec &path)
bool GetLoadSymbolOnDemand () const
lldb::SymbolDownload GetSymbolAutoDownload () const
PathMappingList GetSymlinkMappings () const
Public Member Functions inherited from lldb_private::Properties
Properties ()
Properties (const lldb::OptionValuePropertiesSP &collection_sp)
virtual ~Properties ()
lldb::OptionValuePropertiesSP GetValueProperties () const
virtual lldb::OptionValueSP GetPropertyValue (const ExecutionContext *exe_ctx, llvm::StringRef property_path, Status &error) const
virtual Status SetPropertyValue (const ExecutionContext *exe_ctx, VarSetOperationType op, llvm::StringRef property_path, llvm::StringRef value)
virtual Status DumpPropertyValue (const ExecutionContext *exe_ctx, Stream &strm, llvm::StringRef property_path, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllPropertyValues (const ExecutionContext *exe_ctx, Stream &strm, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllDescriptions (CommandInterpreter &interpreter, Stream &strm) const
size_t Apropos (llvm::StringRef keyword, std::vector< const Property * > &matching_properties) const
template<typename T>
T GetPropertyAtIndexAs (uint32_t idx, T default_value, const ExecutionContext *exe_ctx=nullptr) const
template<typename T, typename U = typename std::remove_pointer<T>::type, std::enable_if_t< std::is_pointer_v< T >, bool > = true>
const U * GetPropertyAtIndexAs (uint32_t idx, const ExecutionContext *exe_ctx=nullptr) const
template<typename T>
bool SetPropertyAtIndex (uint32_t idx, T t, const ExecutionContext *exe_ctx=nullptr) const
Private Member Functions
void UpdateSymlinkMappings ()
Private Attributes
llvm::sys::RWMutex m_symlink_paths_mutex
PathMappingList m_symlink_paths
Additional Inherited Members
Static Public Member Functions inherited from lldb_private::Properties
static llvm::StringRef GetExperimentalSettingsName ()
static bool IsSettingExperimental (llvm::StringRef setting)
Protected Attributes inherited from lldb_private::Properties
lldb::OptionValuePropertiesSP m_collection_sp
Detailed Description
Definition at line 94 of file ModuleList.h.
Constructor & Destructor Documentation
ModuleListProperties()
ModuleListProperties::ModuleListProperties ()
Definition at line 81 of file ModuleList.cpp.
References lldbassert, lldb_private::Properties::m_collection_sp, SetClangModulesCachePath(), SetLLDBIndexCachePath(), and UpdateSymlinkMappings().
Member Function Documentation
GetClangModulesCachePath()
FileSpec ModuleListProperties::GetClangModulesCachePath () const
Definition at line 128 of file ModuleList.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetEnableExternalLookup()
bool ModuleListProperties::GetEnableExternalLookup () const
Definition at line 100 of file ModuleList.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetEnableLLDBIndexCache()
bool ModuleListProperties::GetEnableLLDBIndexCache () const
Definition at line 148 of file ModuleList.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetLLDBIndexCacheExpirationDays()
uint64_t ModuleListProperties::GetLLDBIndexCacheExpirationDays ()
Definition at line 170 of file ModuleList.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::DataFileCache::GetLLDBIndexCachePolicy().
GetLLDBIndexCacheMaxByteSize()
uint64_t ModuleListProperties::GetLLDBIndexCacheMaxByteSize ()
Definition at line 158 of file ModuleList.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::DataFileCache::GetLLDBIndexCachePolicy().
GetLLDBIndexCacheMaxPercent()
uint64_t ModuleListProperties::GetLLDBIndexCacheMaxPercent ()
Definition at line 164 of file ModuleList.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::DataFileCache::GetLLDBIndexCachePolicy().
GetLLDBIndexCachePath()
FileSpec ModuleListProperties::GetLLDBIndexCachePath () const
Definition at line 138 of file ModuleList.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetLoadSymbolOnDemand()
bool ModuleListProperties::GetLoadSymbolOnDemand () const
Definition at line 195 of file ModuleList.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetSharedCacheBinaryLoading()
SymbolSharedCacheUse ModuleListProperties::GetSharedCacheBinaryLoading () const
Definition at line 121 of file ModuleList.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::DynamicLoaderDarwin::FindTargetModuleForImageInfo(), lldb_private::PlatformDarwin::GetModuleFromSharedCaches(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetSharedCacheInfo(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableObjectFile(), and LocateMacOSXFilesUsingDebugSymbols().
GetSymbolAutoDownload()
SymbolDownload ModuleListProperties::GetSymbolAutoDownload () const
Definition at line 110 of file ModuleList.cpp.
References lldb::eSymbolDownloadBackground, and lldb_private::Properties::GetPropertyAtIndexAs().
GetSymlinkMappings()
PathMappingList ModuleListProperties::GetSymlinkMappings () const
Definition at line 190 of file ModuleList.cpp.
References m_symlink_paths, and m_symlink_paths_mutex.
SetClangModulesCachePath()
bool ModuleListProperties::SetClangModulesCachePath (const FileSpec & path)
Definition at line 133 of file ModuleList.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
Referenced by ModuleListProperties().
SetEnableExternalLookup()
bool ModuleListProperties::SetEnableExternalLookup (bool new_value)
Definition at line 106 of file ModuleList.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
SetEnableLLDBIndexCache()
bool ModuleListProperties::SetEnableLLDBIndexCache (bool new_value)
Definition at line 154 of file ModuleList.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
SetLLDBIndexCachePath()
bool ModuleListProperties::SetLLDBIndexCachePath (const FileSpec & path)
Definition at line 143 of file ModuleList.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
Referenced by ModuleListProperties().
UpdateSymlinkMappings()
void ModuleListProperties::UpdateSymlinkMappings () private
Definition at line 176 of file ModuleList.cpp.
References lldb_private::FileSpec::GetPath(), lldb_private::Properties::GetPropertyAtIndexAs(), lldb_private::FileSystem::Instance(), m_symlink_paths, m_symlink_paths_mutex, lldb_private::FileSystem::Readlink(), and lldb_private::Status::Success().
Referenced by ModuleListProperties().
Member Data Documentation
m_symlink_paths
PathMappingList lldb_private::ModuleListProperties::m_symlink_paths private
Definition at line 96 of file ModuleList.h.
Referenced by GetSymlinkMappings(), and UpdateSymlinkMappings().
m_symlink_paths_mutex
llvm::sys::RWMutex lldb_private::ModuleListProperties::m_symlink_paths_mutex mutable private
Definition at line 95 of file ModuleList.h.
Referenced by GetSymlinkMappings(), and UpdateSymlinkMappings().
The documentation for this class was generated from the following files:
ModuleList.h
ModuleList.cpp