LLDB: lldb::SBListener Class Reference
lldb::SBListener Class Reference
#include <SBListener.h>
Public Member Functions
SBListener ()
SBListener (const char *name)
SBListener (const SBListener &rhs)
~SBListener ()
const lldb::SBListener & operator= (const lldb::SBListener &rhs)
void AddEvent (const lldb::SBEvent &event)
void Clear ()
operator bool () const
bool IsValid () const
uint32_t StartListeningForEventClass (SBDebugger &debugger, const char *broadcaster_class, uint32_t event_mask)
bool StopListeningForEventClass (SBDebugger &debugger, const char *broadcaster_class, uint32_t event_mask)
uint32_t StartListeningForEvents (const lldb::SBBroadcaster &broadcaster, uint32_t event_mask)
bool StopListeningForEvents (const lldb::SBBroadcaster &broadcaster, uint32_t event_mask)
bool WaitForEvent (uint32_t num_seconds, lldb::SBEvent &event)
bool WaitForEventForBroadcaster (uint32_t num_seconds, const lldb::SBBroadcaster &broadcaster, lldb::SBEvent &sb_event)
bool WaitForEventForBroadcasterWithType (uint32_t num_seconds, const lldb::SBBroadcaster &broadcaster, uint32_t event_type_mask, lldb::SBEvent &sb_event)
bool PeekAtNextEvent (lldb::SBEvent &sb_event)
bool PeekAtNextEventForBroadcaster (const lldb::SBBroadcaster &broadcaster, lldb::SBEvent &sb_event)
bool PeekAtNextEventForBroadcasterWithType (const lldb::SBBroadcaster &broadcaster, uint32_t event_type_mask, lldb::SBEvent &sb_event)
bool GetNextEvent (lldb::SBEvent &sb_event)
bool GetNextEventForBroadcaster (const lldb::SBBroadcaster &broadcaster, lldb::SBEvent &sb_event)
bool GetNextEventForBroadcasterWithType (const lldb::SBBroadcaster &broadcaster, uint32_t event_type_mask, lldb::SBEvent &sb_event)
bool HandleBroadcastEvent (const lldb::SBEvent &event)
Protected Member Functions
SBListener (const lldb::ListenerSP &listener_sp)
lldb::ListenerSP GetSP ()
Private Member Functions
lldb_private::Listener * operator-> () const
lldb_private::Listener * get () const
void reset (lldb::ListenerSP listener_sp)
Private Attributes
lldb::ListenerSP m_opaque_sp
lldb_private::Listener * m_unused_ptr = nullptr
Friends
class SBAttachInfo
class SBBroadcaster
class SBCommandInterpreter
class SBDebugger
class SBLaunchInfo
class SBTarget
Detailed Description
Definition at line 16 of file SBListener.h.
Constructor & Destructor Documentation
SBListener() [1/4]
SBListener::SBListener ()
Definition at line 23 of file SBListener.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by SBListener(), and SBTarget.
SBListener() [2/4]
SBListener::SBListener (const char * name)
Definition at line 25 of file SBListener.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
SBListener() [3/4]
SBListener::SBListener (const SBListener & rhs)
Definition at line 30 of file SBListener.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBListener().
~SBListener()
SBListener::~SBListener () default
References AddEvent(), Clear(), GetNextEvent(), GetNextEventForBroadcaster(), GetNextEventForBroadcasterWithType(), HandleBroadcastEvent(), IsValid(), operator=(), PeekAtNextEvent(), PeekAtNextEventForBroadcaster(), PeekAtNextEventForBroadcasterWithType(), SBDebugger, StartListeningForEventClass(), StartListeningForEvents(), StopListeningForEventClass(), StopListeningForEvents(), WaitForEvent(), WaitForEventForBroadcaster(), and WaitForEventForBroadcasterWithType().
SBListener() [4/4]
SBListener::SBListener (const lldb::ListenerSP & listener_sp) protected
Definition at line 44 of file SBListener.cpp.
References m_opaque_sp.
Member Function Documentation
AddEvent()
void SBListener::AddEvent (const lldb::SBEvent & event)
Definition at line 59 of file SBListener.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBListener().
Clear()
void SBListener::Clear ()
Definition at line 67 of file SBListener.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBListener().
get()
Listener * SBListener::get () const private
Definition at line 290 of file SBListener.cpp.
References m_opaque_sp.
Referenced by SBTarget.
GetNextEvent()
bool SBListener::GetNextEvent (lldb::SBEvent & sb_event)
Definition at line 230 of file SBListener.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBListener().
GetNextEventForBroadcaster()
bool SBListener::GetNextEventForBroadcaster (const lldb::SBBroadcaster & broadcaster, lldb::SBEvent & sb_event)
Definition at line 244 of file SBListener.cpp.
References lldb::SBBroadcaster::get(), lldb::SBBroadcaster::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBBroadcaster.
Referenced by ~SBListener().
GetNextEventForBroadcasterWithType()
bool SBListener::GetNextEventForBroadcasterWithType (const lldb::SBBroadcaster & broadcaster, uint32_t event_type_mask, lldb::SBEvent & sb_event)
Definition at line 260 of file SBListener.cpp.
References lldb::SBBroadcaster::get(), lldb::SBBroadcaster::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBBroadcaster.
Referenced by ~SBListener().
GetSP()
lldb::ListenerSP SBListener::GetSP () protected
Definition at line 286 of file SBListener.cpp.
References m_opaque_sp.
Referenced by lldb::SBTarget::AttachToProcessWithID(), lldb::SBTarget::AttachToProcessWithName(), lldb::SBTarget::Launch(), SBTarget, lldb::SBAttachInfo::SetListener(), lldb::SBLaunchInfo::SetListener(), lldb::SBAttachInfo::SetShadowListener(), and lldb::SBLaunchInfo::SetShadowListener().
HandleBroadcastEvent()
bool SBListener::HandleBroadcastEvent (const lldb::SBEvent & event)
Definition at line 278 of file SBListener.cpp.
References lldb::SBEvent::GetSP(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBListener().
IsValid()
bool SBListener::IsValid () const
Definition at line 49 of file SBListener.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBTarget::AttachToProcessWithID(), lldb::SBTarget::AttachToProcessWithName(), lldb::SBTarget::ConnectRemote(), lldb::SBTarget::Launch(), and ~SBListener().
operator bool()
SBListener::operator bool () const explicit
Definition at line 53 of file SBListener.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator->()
Listener * SBListener::operator-> () const private
Definition at line 288 of file SBListener.cpp.
References m_opaque_sp.
Referenced by SBTarget.
operator=()
const lldb::SBListener & SBListener::operator= (const lldb::SBListener & rhs)
Definition at line 34 of file SBListener.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and m_unused_ptr.
Referenced by ~SBListener().
PeekAtNextEvent()
bool SBListener::PeekAtNextEvent (lldb::SBEvent & sb_event)
Definition at line 193 of file SBListener.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBListener().
PeekAtNextEventForBroadcaster()
bool SBListener::PeekAtNextEventForBroadcaster (const lldb::SBBroadcaster & broadcaster, lldb::SBEvent & sb_event)
Definition at line 204 of file SBListener.cpp.
References lldb::SBBroadcaster::get(), lldb::SBBroadcaster::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBBroadcaster.
Referenced by ~SBListener().
PeekAtNextEventForBroadcasterWithType()
bool SBListener::PeekAtNextEventForBroadcasterWithType (const lldb::SBBroadcaster & broadcaster, uint32_t event_type_mask, lldb::SBEvent & sb_event)
Definition at line 216 of file SBListener.cpp.
References lldb::SBBroadcaster::get(), lldb::SBBroadcaster::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBBroadcaster.
Referenced by ~SBListener().
reset()
void SBListener::reset (lldb::ListenerSP listener_sp) private
Definition at line 292 of file SBListener.cpp.
References m_opaque_sp, and m_unused_ptr.
Referenced by lldb::SBDebugger::GetListener(), and SBTarget.
StartListeningForEventClass()
uint32_t SBListener::StartListeningForEventClass (SBDebugger & debugger, const char * broadcaster_class, uint32_t event_mask)
Definition at line 74 of file SBListener.cpp.
References lldb::SBDebugger::get(), lldb_private::Debugger::GetBroadcasterManager(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBDebugger.
Referenced by ~SBListener().
StartListeningForEvents()
uint32_t SBListener::StartListeningForEvents (const lldb::SBBroadcaster & broadcaster, uint32_t event_mask)
Definition at line 106 of file SBListener.cpp.
References lldb::SBBroadcaster::get(), lldb::SBBroadcaster::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBBroadcaster.
Referenced by ~SBListener().
StopListeningForEventClass()
bool SBListener::StopListeningForEventClass (SBDebugger & debugger, const char * broadcaster_class, uint32_t event_mask)
Definition at line 90 of file SBListener.cpp.
References lldb::SBDebugger::get(), lldb_private::Debugger::GetBroadcasterManager(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBDebugger.
Referenced by ~SBListener().
StopListeningForEvents()
bool SBListener::StopListeningForEvents (const lldb::SBBroadcaster & broadcaster, uint32_t event_mask)
Definition at line 119 of file SBListener.cpp.
References lldb::SBBroadcaster::get(), lldb::SBBroadcaster::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBBroadcaster.
Referenced by ~SBListener().
WaitForEvent()
bool SBListener::WaitForEvent (uint32_t num_seconds, lldb::SBEvent & event)
Definition at line 129 of file SBListener.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and UINT32_MAX.
Referenced by ~SBListener().
WaitForEventForBroadcaster()
bool SBListener::WaitForEventForBroadcaster (uint32_t num_seconds, const lldb::SBBroadcaster & broadcaster, lldb::SBEvent & sb_event)
Definition at line 153 of file SBListener.cpp.
References lldb::SBBroadcaster::get(), lldb::SBBroadcaster::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, SBBroadcaster, and UINT32_MAX.
Referenced by ~SBListener().
WaitForEventForBroadcasterWithType()
bool SBListener::WaitForEventForBroadcasterWithType (uint32_t num_seconds, const lldb::SBBroadcaster & broadcaster, uint32_t event_type_mask, lldb::SBEvent & sb_event)
Definition at line 173 of file SBListener.cpp.
References lldb::SBBroadcaster::get(), lldb::SBBroadcaster::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, SBBroadcaster, and UINT32_MAX.
Referenced by ~SBListener().
Friends And Related Symbol Documentation
SBAttachInfo
friend class SBAttachInfo friend
Definition at line 84 of file SBListener.h.
References SBAttachInfo.
Referenced by SBAttachInfo.
SBBroadcaster
friend class SBBroadcaster friend
Definition at line 85 of file SBListener.h.
References SBBroadcaster.
Referenced by GetNextEventForBroadcaster(), GetNextEventForBroadcasterWithType(), PeekAtNextEventForBroadcaster(), PeekAtNextEventForBroadcasterWithType(), SBBroadcaster, StartListeningForEvents(), StopListeningForEvents(), WaitForEventForBroadcaster(), and WaitForEventForBroadcasterWithType().
SBCommandInterpreter
friend class SBCommandInterpreter friend
Definition at line 86 of file SBListener.h.
References SBCommandInterpreter.
Referenced by SBCommandInterpreter.
SBDebugger
friend class SBDebugger friend
Definition at line 87 of file SBListener.h.
References SBDebugger.
Referenced by SBDebugger, StartListeningForEventClass(), StopListeningForEventClass(), and ~SBListener().
SBLaunchInfo
friend class SBLaunchInfo friend
Definition at line 88 of file SBListener.h.
References SBLaunchInfo.
Referenced by SBLaunchInfo.
SBTarget
friend class SBTarget friend
Definition at line 89 of file SBListener.h.
References get(), GetSP(), operator->(), reset(), SBListener(), and SBTarget.
Referenced by SBTarget.
Member Data Documentation
m_opaque_sp
lldb::ListenerSP lldb::SBListener::m_opaque_sp private
Definition at line 102 of file SBListener.h.
Referenced by AddEvent(), lldb::SBBroadcaster::AddInitialEventsToListener(), lldb::SBBroadcaster::AddListener(), Clear(), lldb::SBTarget::ConnectRemote(), get(), GetNextEvent(), GetNextEventForBroadcaster(), GetNextEventForBroadcasterWithType(), GetSP(), HandleBroadcastEvent(), operator bool(), operator->(), operator=(), PeekAtNextEvent(), PeekAtNextEventForBroadcaster(), PeekAtNextEventForBroadcasterWithType(), lldb::SBBroadcaster::RemoveListener(), reset(), SBListener(), SBListener(), SBListener(), StartListeningForEventClass(), StartListeningForEvents(), StopListeningForEventClass(), StopListeningForEvents(), WaitForEvent(), WaitForEventForBroadcaster(), and WaitForEventForBroadcasterWithType().
m_unused_ptr
lldb_private::Listener* lldb::SBListener::m_unused_ptr = nullptr private
Definition at line 103 of file SBListener.h.
Referenced by operator=(), and reset().
The documentation for this class was generated from the following files:
SBListener.h
SBListener.cpp