LLDB: lldb_private::postfix::RegisterNode Class Reference
lldb_private::postfix::RegisterNode Class Reference
A node representing the value of a register with the given register number.
#include <PostfixExpression.h>
Public Member Functions
RegisterNode (uint32_t reg_num)
uint32_t GetRegNum () const
Public Member Functions inherited from lldb_private::postfix::Node
Kind GetKind () const
Static Public Member Functions
static bool classof (const Node *node)
Private Attributes
uint32_t m_reg_num
Additional Inherited Members
Public Types inherited from lldb_private::postfix::Node
enum Kind {
BinaryOp , InitialValue , Integer , Register ,
Symbol , UnaryOp
}
Protected Member Functions inherited from lldb_private::postfix::Node
Node (Kind kind)
Detailed Description
A node representing the value of a register with the given register number.
The register kind (RegisterKind enum) used for the specifying the register number is implicit and assumed to be the same for all Register nodes in a given tree.
Definition at line 105 of file PostfixExpression.h.
Constructor & Destructor Documentation
RegisterNode()
lldb_private::postfix::RegisterNode::RegisterNode (uint32_t reg_num) inline
Definition at line 107 of file PostfixExpression.h.
References m_reg_num, lldb_private::postfix::Node::Node(), and lldb_private::postfix::Node::Register.
Member Function Documentation
classof()
bool lldb_private::postfix::RegisterNode::classof (const Node * node) inline static
Definition at line 111 of file PostfixExpression.h.
References lldb_private::postfix::Node::GetKind(), lldb_private::postfix::Node::Node(), and lldb_private::postfix::Node::Register.
GetRegNum()
uint32_t lldb_private::postfix::RegisterNode::GetRegNum () const inline
Definition at line 109 of file PostfixExpression.h.
References m_reg_num.
Member Data Documentation
m_reg_num
uint32_t lldb_private::postfix::RegisterNode::m_reg_num private
Definition at line 114 of file PostfixExpression.h.
Referenced by GetRegNum(), and RegisterNode().
The documentation for this class was generated from the following file:
PostfixExpression.h