LLDB: SymbolFilePDB Class Reference
SymbolFilePDB Class Reference
#include <SymbolFilePDB.h>
Classes
struct SecContribInfo
Public Member Functions
SymbolFilePDB (lldb::ObjectFileSP objfile_sp)
~SymbolFilePDB () override
uint32_t CalculateAbilities () override
void InitializeObject () override
Initialize the SymbolFile object.
lldb::LanguageType ParseLanguage (lldb_private::CompileUnit &comp_unit) override
size_t ParseFunctions (lldb_private::CompileUnit &comp_unit) override
bool ParseLineTable (lldb_private::CompileUnit &comp_unit) override
bool ParseDebugMacros (lldb_private::CompileUnit &comp_unit) override
bool ParseSupportFiles (lldb_private::CompileUnit &comp_unit, lldb_private::SupportFileList &support_files) override
size_t ParseTypes (lldb_private::CompileUnit &comp_unit) override
bool ParseImportedModules (const lldb_private::SymbolContext &sc, std::vector< lldb_private::SourceModule > &imported_modules) override
size_t ParseBlocksRecursive (lldb_private::Function &func) override
size_t ParseVariablesForContext (const lldb_private::SymbolContext &sc) override
lldb_private::Type * ResolveTypeUID (lldb::user_id_t type_uid) override
std::optional< ArrayInfo > GetDynamicArrayInfoForUID (lldb::user_id_t type_uid, const lldb_private::ExecutionContext *exe_ctx) override
If type_uid points to an array type, return its characteristics.
bool CompleteType (lldb_private::CompilerType &compiler_type) override
lldb_private::CompilerDecl GetDeclForUID (lldb::user_id_t uid) override
lldb_private::CompilerDeclContext GetDeclContextForUID (lldb::user_id_t uid) override
lldb_private::CompilerDeclContext GetDeclContextContainingUID (lldb::user_id_t uid) override
void ParseDeclsForContext (lldb_private::CompilerDeclContext decl_ctx) override
uint32_t ResolveSymbolContext (const lldb_private::Address &so_addr, lldb::SymbolContextItem resolve_scope, lldb_private::SymbolContext &sc) override
uint32_t ResolveSymbolContext (const lldb_private::SourceLocationSpec &src_location_spec, lldb::SymbolContextItem resolve_scope, lldb_private::SymbolContextList &sc_list) override
void FindGlobalVariables (lldb_private::ConstString name, const lldb_private::CompilerDeclContext &parent_decl_ctx, uint32_t max_matches, lldb_private::VariableList &variables) override
void FindGlobalVariables (const lldb_private::RegularExpression &regex, uint32_t max_matches, lldb_private::VariableList &variables) override
void FindFunctions (const lldb_private::Module::LookupInfo &lookup_info, const lldb_private::CompilerDeclContext &parent_decl_ctx, bool include_inlines, lldb_private::SymbolContextList &sc_list) override
void FindFunctions (const lldb_private::RegularExpression &regex, bool include_inlines, lldb_private::SymbolContextList &sc_list) override
void GetMangledNamesForFunction (const std::string &scope_qualified_name, std::vector< lldb_private::ConstString > &mangled_names) override
void AddSymbols (lldb_private::Symtab &symtab) override
void FindTypes (const lldb_private::TypeQuery &match, lldb_private::TypeResults &results) override
Find types using a type-matching object that contains all search parameters.
void FindTypesByRegex (const lldb_private::RegularExpression &regex, uint32_t max_matches, lldb_private::TypeMap &types)
void GetTypes (lldb_private::SymbolContextScope *sc_scope, lldb::TypeClass type_mask, lldb_private::TypeList &type_list) override
llvm::Expected< lldb::TypeSystemSP > GetTypeSystemForLanguage (lldb::LanguageType language) override
lldb_private::CompilerDeclContext FindNamespace (lldb_private::ConstString name, const lldb_private::CompilerDeclContext &parent_decl_ctx, bool only_root_namespaces) override
Finds a namespace of name name and whose parent context is parent_decl_ctx.
llvm::StringRef GetPluginName () override
llvm::pdb::IPDBSession & GetPDBSession ()
const llvm::pdb::IPDBSession & GetPDBSession () const
void DumpClangAST (lldb_private::Stream &s, llvm::StringRef filter, bool show_color) override
Public Member Functions inherited from lldb_private::SymbolFileCommon
SymbolFileCommon (lldb::ObjectFileSP objfile_sp)
~SymbolFileCommon () override=default
uint32_t GetAbilities () override
Get a mask of what this symbol file supports for the object file that it was constructed with.
Symtab * GetSymtab (bool can_create=true) override
ObjectFile * GetObjectFile () override
const ObjectFile * GetObjectFile () const override
ObjectFile * GetMainObjectFile () override
void SectionFileAddressesChanged () override
Notify the SymbolFile that the file addresses in the Sections for this module have been changed.
uint32_t GetNumCompileUnits () override
lldb::CompUnitSP GetCompileUnitAtIndex (uint32_t idx) override
void Dump (Stream &s) override
uint64_t GetDebugInfoSize (bool load_all_debug_info=false) override
Metrics gathering functions.
bool GetDebugInfoIndexWasLoadedFromCache () const override
Accessors for the bool that indicates if the debug info index was loaded from, or saved to the module index cache.
void SetDebugInfoIndexWasLoadedFromCache () override
bool GetDebugInfoIndexWasSavedToCache () const override
void SetDebugInfoIndexWasSavedToCache () override
bool GetDebugInfoHadFrameVariableErrors () const override
Accessors for the bool that indicates if there was debug info, but errors stopped variables from being able to be displayed correctly.
void SetDebugInfoHadFrameVariableErrors () override
lldb::TypeSP MakeType (lldb::user_id_t uid, ConstString name, std::optional< uint64_t > byte_size, SymbolContextScope *context, lldb::user_id_t encoding_uid, Type::EncodingDataType encoding_uid_type, const Declaration &decl, const CompilerType &compiler_qual_type, Type::ResolveState compiler_type_resolve_state, uint32_t opaque_payload=0) override
This function is used to create types that belong to a SymbolFile.
lldb::TypeSP CopyType (const lldb::TypeSP &other_type) override
Public Member Functions inherited from lldb_private::SymbolFile
SymbolFile ()=default
~SymbolFile () override=default
virtual SymbolFile * GetBackingSymbolFile ()
SymbolFileOnDemand class overrides this to return the underlying backing SymbolFile implementation that loads on-demand.
virtual std::recursive_mutex & GetModuleMutex () const
Symbols file subclasses should override this to return the Module that owns the TypeSystem that this symbol file modifies type information in.
virtual bool GetLoadDebugInfoEnabled ()
Whether debug info will be loaded or not.
virtual void SetLoadDebugInfoEnabled ()
Specify debug info should be loaded.
virtual XcodeSDK ParseXcodeSDK (CompileUnit &comp_unit)
Return the Xcode SDK comp_unit was compiled against.
virtual llvm::SmallSet< lldb::LanguageType, 4 > ParseAllLanguages (CompileUnit &comp_unit)
This function exists because SymbolFileDWARFDebugMap may extra compile units which aren't exposed as "real" compile units.
virtual bool ForEachExternalModule (lldb_private::CompileUnit &comp_unit, llvm::DenseSet< lldb_private::SymbolFile * > &visited_symbol_files, llvm::function_ref< bool(Module &)> lambda)
Apply a lambda to each external lldb::Module referenced by this comp_unit.
virtual bool ParseIsOptimized (CompileUnit &comp_unit)
virtual std::vector< CompilerContext > GetCompilerContextForUID (lldb::user_id_t uid)
Status GetFrameVariableError (StackFrame &frame)
Get an error that describes why variables might be missing for a given symbol context.
virtual Status CalculateFrameVariableError (StackFrame &frame)
Subclasses will override this function to for GetFrameVariableError().
virtual void FindFunctions (llvm::ArrayRef< Module::LookupInfo > lookup_infos, const CompilerDeclContext &parent_decl_ctx, bool include_inlines, SymbolContextList &sc_list)
virtual llvm::Expected< SymbolContext > ResolveFunctionCallLabel (FunctionCallLabel &label)
Resolves the function corresponding to the specified LLDB function call label.
virtual void PreloadSymbols ()
virtual std::vector< std::unique_ptr< CallEdge > > ParseCallEdgesInFunction (UserID func_id)
virtual lldb::UnwindPlanSP GetUnwindPlan (const Address &address, const RegisterInfoResolver &resolver)
virtual llvm::Expected< lldb::addr_t > GetParameterStackSize (const Symbol &symbol)
Return the number of stack bytes taken up by the parameters to this function.
virtual StatsDuration::Duration GetDebugInfoParseTime ()
Return the time taken to parse the debug information.
virtual StatsDuration::Duration GetDebugInfoIndexTime ()
Return the time it took to index the debug information in the object file.
virtual void ResetStatistics ()
Reset the statistics for the symbol file.
virtual ModuleList GetDebugInfoModules ()
Get the additional modules that this symbol file uses to parse debug info.
virtual bool GetSeparateDebugInfo (StructuredData::Dictionary &d, bool errors_only, bool load_all_debug_info=false)
Return true if separate debug info files are supported and this function succeeded, false otherwise.
virtual DWOStats GetDwoStats ()
Retrieves statistics about DWO files associated with this symbol file.
std::unordered_map< lldb::CompUnitSP, Args > GetCompileOptions ()
Returns a map of compilation unit to the compile option arguments associated with that compilation unit.
std::string GetObjectName () const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static void DebuggerInitialize (lldb_private::Debugger &debugger)
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static lldb_private::SymbolFile * CreateInstance (lldb::ObjectFileSP objfile_sp)
static bool UseNativePDB ()
static bool classof (const SymbolFileCommon *obj)
Static Public Member Functions inherited from lldb_private::SymbolFile
static SymbolFile * FindPlugin (lldb::ObjectFileSP objfile_sp)
static bool classof (const SymbolFile *obj)
Private Types
using SecContribsMap = std::map<uint32_t, std::vector<SecContribInfo>>
typedef std::vector< lldb_private::Type * > TypeCollection
Private Member Functions
uint32_t CalculateNumCompileUnits () override
lldb::CompUnitSP ParseCompileUnitAtIndex (uint32_t index) override
lldb::CompUnitSP ParseCompileUnitForUID (uint32_t id, uint32_t index=UINT32_MAX)
bool ParseCompileUnitLineTable (lldb_private::CompileUnit &comp_unit, uint32_t match_line)
void BuildSupportFileIdToSupportFileIndexMap (const llvm::pdb::PDBSymbolCompiland &pdb_compiland, llvm::DenseMap< uint32_t, uint32_t > &index_map) const
void FindTypesByName (llvm::StringRef name, const lldb_private::CompilerDeclContext &parent_decl_ctx, uint32_t max_matches, lldb_private::TypeMap &types)
std::string GetMangledForPDBData (const llvm::pdb::PDBSymbolData &pdb_data)
lldb::VariableSP ParseVariableForPDBData (const lldb_private::SymbolContext &sc, const llvm::pdb::PDBSymbolData &pdb_data)
size_t ParseVariables (const lldb_private::SymbolContext &sc, const llvm::pdb::PDBSymbol &pdb_data, lldb_private::VariableList *variable_list=nullptr)
lldb::CompUnitSP GetCompileUnitContainsAddress (const lldb_private::Address &so_addr)
void GetTypesForPDBSymbol (const llvm::pdb::PDBSymbol &pdb_symbol, uint32_t type_mask, TypeCollection &type_collection)
lldb_private::Function * ParseCompileUnitFunctionForPDBFunc (const llvm::pdb::PDBSymbolFunc &pdb_func, lldb_private::CompileUnit &comp_unit)
void GetCompileUnitIndex (const llvm::pdb::PDBSymbolCompiland &pdb_compiland, uint32_t &index)
PDBASTParser * GetPDBAstParser ()
std::unique_ptr< llvm::pdb::PDBSymbolCompiland > GetPDBCompilandByUID (uint32_t uid)
lldb_private::Mangled GetMangledForPDBFunc (const llvm::pdb::PDBSymbolFunc &pdb_func)
bool ResolveFunction (const llvm::pdb::PDBSymbolFunc &pdb_func, bool include_inlines, lldb_private::SymbolContextList &sc_list)
bool ResolveFunction (uint32_t uid, bool include_inlines, lldb_private::SymbolContextList &sc_list)
void CacheFunctionNames ()
bool DeclContextMatchesThisSymbolFile (const lldb_private::CompilerDeclContext &decl_ctx)
uint32_t GetCompilandId (const llvm::pdb::PDBSymbolData &data)
Private Attributes
llvm::DenseMap< uint32_t, lldb::CompUnitSP > m_comp_units
llvm::DenseMap< uint32_t, lldb::TypeSP > m_types
llvm::DenseMap< uint32_t, lldb::VariableSP > m_variables
llvm::DenseMap< uint64_t, std::string > m_public_names
SecContribsMap m_sec_contribs
std::vector< lldb::TypeSP > m_builtin_types
std::unique_ptr< llvm::pdb::IPDBSession > m_session_up
std::unique_ptr< llvm::pdb::PDBSymbolExe > m_global_scope_up
lldb_private::UniqueCStringMap< uint32_t > m_func_full_names
lldb_private::UniqueCStringMap< uint32_t > m_func_base_names
lldb_private::UniqueCStringMap< uint32_t > m_func_method_names
Static Private Attributes
static char ID
LLVM RTTI support.
bool isA (const void *ClassID) const override
LLVM RTTI support.
static bool classof (const SymbolFile *obj)
Additional Inherited Members
Public Types inherited from lldb_private::SymbolFile
enum Abilities {
CompileUnits = (1u << 0) , LineTables = (1u << 1) , Functions = (1u << 2) , Blocks = (1u << 3) ,
GlobalVariables = (1u << 4) , LocalVariables = (1u << 5) , VariableTypes = (1u << 6) , kAllAbilities = ((1u << 7) - 1u)
}
Protected Member Functions inherited from lldb_private::SymbolFileCommon
virtual TypeList & GetTypeList ()
void SetCompileUnitAtIndex (uint32_t idx, const lldb::CompUnitSP &cu_sp)
Protected Member Functions inherited from lldb_private::SymbolFile
void AssertModuleLock ()
virtual void GetCompileOptions (std::unordered_map< lldb::CompUnitSP, lldb_private::Args > &args)
Protected Attributes inherited from lldb_private::SymbolFileCommon
lldb::ObjectFileSP m_objfile_sp
std::optional< std::vector< lldb::CompUnitSP > > m_compile_units
TypeList m_type_list
uint32_t m_abilities = 0
bool m_calculated_abilities = false
bool m_index_was_loaded_from_cache = false
bool m_index_was_saved_to_cache = false
bool m_debug_info_had_variable_errors = false
Set to true if any variable feteching errors have been found when calling GetFrameVariableError().
Detailed Description
Definition at line 25 of file SymbolFilePDB.h.
Member Typedef Documentation
SecContribsMap
using SymbolFilePDB::SecContribsMap = std::map<uint32_t, std::vector<SecContribInfo>> private
Definition at line 171 of file SymbolFilePDB.h.
TypeCollection
typedef std::vector<lldb_private::Type *> SymbolFilePDB::TypeCollection private
Definition at line 204 of file SymbolFilePDB.h.
Constructor & Destructor Documentation
SymbolFilePDB()
SymbolFilePDB::SymbolFilePDB (lldb::ObjectFileSP objfile_sp)
Definition at line 230 of file SymbolFilePDB.cpp.
References m_global_scope_up, m_session_up, and lldb_private::SymbolFileCommon::SymbolFileCommon().
Referenced by CreateInstance().
~SymbolFilePDB()
SymbolFilePDB::~SymbolFilePDB () override default
Member Function Documentation
AddSymbols()
void SymbolFilePDB::AddSymbols (lldb_private::Symtab & symtab) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 1475 of file SymbolFilePDB.cpp.
References lldb_private::Symtab::AddSymbol(), lldb::eSymbolTypeCode, lldb::eSymbolTypeData, lldb_private::Symtab::Finalize(), lldb_private::Symbol::GetFileAddress(), lldb_private::Symtab::GetNumSymbols(), m_global_scope_up, lldb_private::SymbolFileCommon::m_objfile_sp, and lldb_private::Symtab::SymbolAtIndex().
BuildSupportFileIdToSupportFileIndexMap()
void SymbolFilePDB::BuildSupportFileIdToSupportFileIndexMap (const llvm::pdb::PDBSymbolCompiland & pdb_compiland, llvm::DenseMap< uint32_t, uint32_t > & index_map) const private
Definition at line 1938 of file SymbolFilePDB.cpp.
References m_session_up.
Referenced by ParseCompileUnitLineTable().
CacheFunctionNames()
void SymbolFilePDB::CacheFunctionNames () private
Definition at line 1296 of file SymbolFilePDB.cpp.
References MSVCUndecoratedNameParser::DropScope(), lldb_private::Mangled::IsMangledName(), m_func_base_names, m_func_full_names, m_func_method_names, and m_global_scope_up.
Referenced by FindFunctions(), and FindFunctions().
CalculateAbilities()
uint32_t SymbolFilePDB::CalculateAbilities () override virtual
Implements lldb_private::SymbolFile.
Definition at line 235 of file SymbolFilePDB.cpp.
References lldb_private::SymbolFile::Blocks, lldb_private::SymbolFile::CompileUnits, error(), lldb_private::SymbolFile::Functions, lldb_private::FileSpec::GetPath(), lldb_private::SymbolFile::GlobalVariables, lldb_private::SymbolFile::LineTables, lldb_private::SymbolFile::LocalVariables, lldb_private::SymbolFileCommon::m_objfile_sp, m_session_up, and lldb_private::SymbolFile::VariableTypes.
CalculateNumCompileUnits()
uint32_t SymbolFilePDB::CalculateNumCompileUnits () override private virtual
Implements lldb_private::SymbolFileCommon.
Definition at line 301 of file SymbolFilePDB.cpp.
References lldbassert, and m_global_scope_up.
classof()
bool SymbolFilePDB::classof (const SymbolFile * obj) inline static
Definition at line 35 of file SymbolFilePDB.h.
References ID, and lldb_private::SymbolFile::SymbolFile().
CompleteType()
bool SymbolFilePDB::CompleteType (lldb_private::CompilerType & compiler_type) override virtual
Implements lldb_private::SymbolFile.
Definition at line 677 of file SymbolFilePDB.cpp.
References lldb::eLanguageTypeC_plus_plus, lldb_private::GetLog(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::TypeSystemClang::GetPDBParser(), GetTypeSystemForLanguage(), LLDB_LOG_ERROR, and lldb_private::Symbols.
CreateInstance()
lldb_private::SymbolFile * SymbolFilePDB::CreateInstance (lldb::ObjectFileSP objfile_sp) static
Definition at line 223 of file SymbolFilePDB.cpp.
References SymbolFilePDB(), and UseNativePDB().
Referenced by Initialize(), and Terminate().
DebuggerInitialize()
void SymbolFilePDB::DebuggerInitialize (lldb_private::Debugger & debugger) static
Definition at line 209 of file SymbolFilePDB.cpp.
References lldb_private::PluginManager::CreateSettingForSymbolFilePlugin(), GetGlobalPluginProperties(), and lldb_private::PluginManager::GetSettingForSymbolFilePlugin().
Referenced by Initialize().
DeclContextMatchesThisSymbolFile()
bool SymbolFilePDB::DeclContextMatchesThisSymbolFile (const lldb_private::CompilerDeclContext & decl_ctx) private
Definition at line 2043 of file SymbolFilePDB.cpp.
References lldb_private::GetLog(), lldb_private::TypeSystem::GetMinimumLanguage(), lldb_private::CompilerDeclContext::GetTypeSystem(), GetTypeSystemForLanguage(), lldb_private::CompilerDeclContext::IsValid(), LLDB_LOG_ERROR, and lldb_private::Symbols.
Referenced by FindFunctions(), and FindGlobalVariables().
DumpClangAST()
void SymbolFilePDB::DumpClangAST (lldb_private::Stream & s, llvm::StringRef filter, bool show_color) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 1524 of file SymbolFilePDB.cpp.
References lldb_private::Stream::AsRawOstream(), lldb_private::TypeSystemClang::Dump(), lldb::eLanguageTypeC_plus_plus, lldb_private::GetLog(), GetTypeSystemForLanguage(), LLDB_LOG_ERROR, and lldb_private::Symbols.
FindFunctions() [1/2]
void SymbolFilePDB::FindFunctions (const lldb_private::Module::LookupInfo & lookup_info, const lldb_private::CompilerDeclContext & parent_decl_ctx, bool include_inlines, lldb_private::SymbolContextList & sc_list) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 1390 of file SymbolFilePDB.cpp.
References CacheFunctionNames(), DeclContextMatchesThisSymbolFile(), GetDeclContextContainingUID(), lldb_private::Module::LookupInfo::GetLookupName(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::Module::LookupInfo::GetName(), lldb_private::Module::LookupInfo::GetNameTypeMask(), lldb_private::ConstString::IsEmpty(), lldbassert, m_func_base_names, m_func_full_names, m_func_method_names, and ResolveFunction().
FindFunctions() [2/2]
void SymbolFilePDB::FindFunctions (const lldb_private::RegularExpression & regex, bool include_inlines, lldb_private::SymbolContextList & sc_list) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 1446 of file SymbolFilePDB.cpp.
References CacheFunctionNames(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::RegularExpression::IsValid(), m_func_base_names, m_func_full_names, and ResolveFunction().
FindGlobalVariables() [1/2]
void SymbolFilePDB::FindGlobalVariables (const lldb_private::RegularExpression & regex, uint32_t max_matches, lldb_private::VariableList & variables) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 1237 of file SymbolFilePDB.cpp.
References lldb_private::SymbolContext::comp_unit, lldb_private::RegularExpression::Execute(), GetCompilandId(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::VariableList::GetSize(), lldb_private::RegularExpression::IsValid(), lldbassert, m_global_scope_up, lldb_private::SymbolFileCommon::m_objfile_sp, lldb_private::SymbolContext::module_sp, ParseCompileUnitForUID(), and ParseVariables().
FindGlobalVariables() [2/2]
void SymbolFilePDB::FindGlobalVariables (lldb_private::ConstString name, const lldb_private::CompilerDeclContext & parent_decl_ctx, uint32_t max_matches, lldb_private::VariableList & variables) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 1195 of file SymbolFilePDB.cpp.
References lldb_private::SymbolContext::comp_unit, DeclContextMatchesThisSymbolFile(), MSVCUndecoratedNameParser::DropScope(), GetCompilandId(), GetDeclContextContainingUID(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::VariableList::GetSize(), lldb_private::ConstString::GetStringRef(), lldb_private::ConstString::IsEmpty(), lldb_private::CompilerDeclContext::IsValid(), lldbassert, m_global_scope_up, lldb_private::SymbolFileCommon::m_objfile_sp, lldb_private::SymbolContext::module_sp, ParseCompileUnitForUID(), and ParseVariables().
FindNamespace()
lldb_private::CompilerDeclContext SymbolFilePDB::FindNamespace (lldb_private::ConstString name, const lldb_private::CompilerDeclContext & parent_decl_ctx, bool only_root_namespaces) override virtual
Finds a namespace of name name and whose parent context is parent_decl_ctx.
If
!parent_decl_ctx.IsValid()
then this function will consider all namespaces that match the name. If only_root_namespaces is true, only consider in the search those DIEs that represent top-level namespaces.
Reimplemented from lldb_private::SymbolFile.
Definition at line 1756 of file SymbolFilePDB.cpp.
References lldb_private::ConstString::AsCString(), lldb::eLanguageTypeC_plus_plus, lldb_private::GetLog(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::CompilerDeclContext::GetOpaqueDeclContext(), lldb_private::ConstString::GetStringRef(), GetTypeSystemForLanguage(), LLDB_LOG_ERROR, and lldb_private::Symbols.
FindTypes()
void SymbolFilePDB::FindTypes (const lldb_private::TypeQuery & query, lldb_private::TypeResults & results) override virtual
Find types using a type-matching object that contains all search parameters.
See also
lldb_private::TypeQuery
Parameters
[in] query A type matching object that contains all of the details of the type search.
[in] results Any matching types will be populated into the results object using TypeMap::InsertUnique(...).
Reimplemented from lldb_private::SymbolFile.
Definition at line 1597 of file SymbolFilePDB.cpp.
References lldb_private::TypeResults::AlreadySearched(), lldb_private::TypeQuery::ContextMatches(), lldb_private::TypeResults::Done(), MSVCUndecoratedNameParser::DropScope(), lldb_private::TypeQuery::GetContextRef(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::ConstString::GetStringRef(), lldb_private::TypeQuery::GetTypeBasename(), lldb_private::TypeResults::InsertUnique(), m_global_scope_up, m_types, and ResolveTypeUID().
FindTypesByName()
void SymbolFilePDB::FindTypesByName (llvm::StringRef name, const lldb_private::CompilerDeclContext & parent_decl_ctx, uint32_t max_matches, lldb_private::TypeMap & types) private
FindTypesByRegex()
void SymbolFilePDB::FindTypesByRegex (const lldb_private::RegularExpression & regex, uint32_t max_matches, lldb_private::TypeMap & types)
Definition at line 1542 of file SymbolFilePDB.cpp.
References lldb_private::RegularExpression::Execute(), lldb_private::TypeMap::Insert(), m_global_scope_up, m_types, and ResolveTypeUID().
GetCompilandId()
uint32_t SymbolFilePDB::GetCompilandId (const llvm::pdb::PDBSymbolData & data) private
Definition at line 2066 of file SymbolFilePDB.cpp.
References m_sec_contribs, and m_session_up.
Referenced by FindGlobalVariables(), FindGlobalVariables(), and ParseVariablesForContext().
GetCompileUnitContainsAddress()
lldb::CompUnitSP SymbolFilePDB::GetCompileUnitContainsAddress (const lldb_private::Address & so_addr) private
Definition at line 1957 of file SymbolFilePDB.cpp.
References lldb_private::Address::GetFileAddress(), LLDB_INVALID_ADDRESS, m_session_up, and ParseCompileUnitForUID().
GetCompileUnitIndex()
void SymbolFilePDB::GetCompileUnitIndex (const llvm::pdb::PDBSymbolCompiland & pdb_compiland, uint32_t & index) private
Definition at line 327 of file SymbolFilePDB.cpp.
References lldb_private::SymbolFileCommon::GetNumCompileUnits(), m_global_scope_up, and UINT32_MAX.
Referenced by ParseCompileUnitForUID().
GetDeclContextContainingUID()
lldb_private::CompilerDeclContext SymbolFilePDB::GetDeclContextContainingUID (lldb::user_id_t uid) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 763 of file SymbolFilePDB.cpp.
References lldb_private::TypeSystemClang::CreateDeclContext(), lldb::eLanguageTypeC_plus_plus, lldb_private::GetLog(), lldb_private::TypeSystemClang::GetPDBParser(), GetTypeSystemForLanguage(), LLDB_LOG_ERROR, m_session_up, and lldb_private::Symbols.
Referenced by FindFunctions(), FindGlobalVariables(), and GetDeclContextForUID().
GetDeclContextForUID()
lldb_private::CompilerDeclContext SymbolFilePDB::GetDeclContextForUID (lldb::user_id_t uid) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 732 of file SymbolFilePDB.cpp.
References lldb_private::TypeSystemClang::CreateDeclContext(), lldb::eLanguageTypeC_plus_plus, GetDeclContextContainingUID(), lldb_private::GetLog(), lldb_private::TypeSystemClang::GetPDBParser(), GetTypeSystemForLanguage(), LLDB_LOG_ERROR, m_session_up, and lldb_private::Symbols.
GetDeclForUID()
lldb_private::CompilerDecl SymbolFilePDB::GetDeclForUID (lldb::user_id_t uid) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 702 of file SymbolFilePDB.cpp.
References lldb::eLanguageTypeC_plus_plus, lldb_private::TypeSystemClang::GetCompilerDecl(), lldb_private::GetLog(), lldb_private::TypeSystemClang::GetPDBParser(), GetTypeSystemForLanguage(), LLDB_LOG_ERROR, m_session_up, and lldb_private::Symbols.
GetDynamicArrayInfoForUID()
std::optional< SymbolFile::ArrayInfo > SymbolFilePDB::GetDynamicArrayInfoForUID (lldb::user_id_t type_uid, const lldb_private::ExecutionContext * exe_ctx) override virtual
If type_uid points to an array type, return its characteristics.
To support variable-length array types, this function takes an optional ExecutionContext. If exe_ctx is non-null, the dynamic characteristics for that context are returned.
Implements lldb_private::SymbolFile.
Definition at line 672 of file SymbolFilePDB.cpp.
GetMangledForPDBData()
std::string SymbolFilePDB::GetMangledForPDBData (const llvm::pdb::PDBSymbolData & pdb_data) private
Definition at line 992 of file SymbolFilePDB.cpp.
References m_global_scope_up, and m_public_names.
Referenced by ParseVariableForPDBData().
GetMangledForPDBFunc()
Mangled SymbolFilePDB::GetMangledForPDBFunc (const llvm::pdb::PDBSymbolFunc & pdb_func) private
Definition at line 1982 of file SymbolFilePDB.cpp.
References lldb_private::Mangled::GetDemangledName(), lldb_private::ConstString::IsEmpty(), lldbassert, m_global_scope_up, lldb_private::Mangled::SetDemangledName(), lldb_private::Mangled::SetMangledName(), and lldb_private::Mangled::SetValue().
Referenced by ParseCompileUnitFunctionForPDBFunc().
GetMangledNamesForFunction()
void SymbolFilePDB::GetMangledNamesForFunction (const std::string & scope_qualified_name, std::vector< lldb_private::ConstString > & mangled_names) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 1471 of file SymbolFilePDB.cpp.
GetPDBAstParser()
PDBASTParser * SymbolFilePDB::GetPDBAstParser () private
Definition at line 1737 of file SymbolFilePDB.cpp.
References lldb::eLanguageTypeC_plus_plus, lldb_private::GetLog(), GetTypeSystemForLanguage(), LLDB_LOG_ERROR, and lldb_private::Symbols.
Referenced by ParseVariables().
GetPDBCompilandByUID()
std::unique_ptr< llvm::pdb::PDBSymbolCompiland > SymbolFilePDB::GetPDBCompilandByUID (uint32_t uid) private
Definition at line 346 of file SymbolFilePDB.cpp.
References m_session_up.
Referenced by GetTypes(), ParseCompileUnitForUID(), ParseCompileUnitLineTable(), ParseFunctions(), ParseLanguage(), ParseSupportFiles(), ParseTypes(), and ParseVariablesForContext().
GetPDBSession() [1/2]
IPDBSession & SymbolFilePDB::GetPDBSession ()
Definition at line 1789 of file SymbolFilePDB.cpp.
References m_session_up.
Referenced by PDBASTParser::CompleteTypeFromPDB(), and PDBASTParser::ParseDeclsForDeclContext().
GetPDBSession() [2/2]
const IPDBSession & SymbolFilePDB::GetPDBSession () const
Definition at line 1791 of file SymbolFilePDB.cpp.
References m_session_up.
GetPluginDescriptionStatic()
llvm::StringRef SymbolFilePDB::GetPluginDescriptionStatic () static
Definition at line 218 of file SymbolFilePDB.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef SymbolFilePDB::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 156 of file SymbolFilePDB.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef SymbolFilePDB::GetPluginNameStatic () inline static
Definition at line 45 of file SymbolFilePDB.h.
Referenced by GetPluginName(), and Initialize().
GetTypes()
void SymbolFilePDB::GetTypes (lldb_private::SymbolContextScope * sc_scope, lldb::TypeClass type_mask, lldb_private::TypeList & type_list) override virtual
Implements lldb_private::SymbolFile.
Definition at line 1698 of file SymbolFilePDB.cpp.
References lldb_private::SymbolContextScope::CalculateSymbolContextCompileUnit(), lldb_private::UserID::GetID(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::SymbolFileCommon::GetNumCompileUnits(), GetPDBCompilandByUID(), GetTypesForPDBSymbol(), lldb_private::TypeList::Insert(), and ParseCompileUnitAtIndex().
GetTypesForPDBSymbol()
void SymbolFilePDB::GetTypesForPDBSymbol (const llvm::pdb::PDBSymbol & pdb_symbol, uint32_t type_mask, TypeCollection & type_collection) private
Definition at line 1650 of file SymbolFilePDB.cpp.
References GetTypesForPDBSymbol(), and ResolveTypeUID().
Referenced by GetTypes(), and GetTypesForPDBSymbol().
GetTypeSystemForLanguage()
llvm::Expected< lldb::TypeSystemSP > SymbolFilePDB::GetTypeSystemForLanguage (lldb::LanguageType language) override virtual
Reimplemented from lldb_private::SymbolFileCommon.
Definition at line 1727 of file SymbolFilePDB.cpp.
References lldb_private::SymbolFileCommon::m_objfile_sp.
Referenced by CompleteType(), DeclContextMatchesThisSymbolFile(), DumpClangAST(), FindNamespace(), GetDeclContextContainingUID(), GetDeclContextForUID(), GetDeclForUID(), GetPDBAstParser(), ParseCompileUnitFunctionForPDBFunc(), ParseDeclsForContext(), and ResolveTypeUID().
Initialize()
void SymbolFilePDB::Initialize () static
Definition at line 190 of file SymbolFilePDB.cpp.
References CreateInstance(), DebuggerInitialize(), GetPluginDescriptionStatic(), GetPluginNameStatic(), lldb_private::npdb::SymbolFileNativePDB::Initialize(), and lldb_private::PluginManager::RegisterPlugin().
InitializeObject()
void SymbolFilePDB::InitializeObject () override virtual
Initialize the SymbolFile object.
The SymbolFile object with the best set of abilities (detected in "uint32_t SymbolFile::GetAbilities()) will have this function called if it is chosen to parse an object file. More complete initialization can happen in this function which will get called prior to any other functions in the SymbolFile protocol.
Reimplemented from lldb_private::SymbolFile.
Definition at line 289 of file SymbolFilePDB.cpp.
References LLDB_INVALID_ADDRESS, lldbassert, m_global_scope_up, lldb_private::SymbolFileCommon::m_objfile_sp, and m_session_up.
isA()
bool SymbolFilePDB::isA (const void * ClassID) const inline override virtual
LLVM RTTI support.
Reimplemented from lldb_private::SymbolFileCommon.
Definition at line 32 of file SymbolFilePDB.h.
References ID.
ParseBlocksRecursive()
size_t SymbolFilePDB::ParseBlocksRecursive (lldb_private::Function & func) override virtual
Implements lldb_private::SymbolFile.
Definition at line 523 of file SymbolFilePDB.cpp.
References lldb_private::Function::GetBlock(), lldb_private::UserID::GetID(), lldb_private::SymbolFile::GetModuleMutex(), m_session_up, and ParseFunctionBlocksForPDBSymbol().
ParseCompileUnitAtIndex()
lldb::CompUnitSP SymbolFilePDB::ParseCompileUnitAtIndex (uint32_t index) override private virtual
Implements lldb_private::SymbolFileCommon.
Definition at line 350 of file SymbolFilePDB.cpp.
References lldb_private::SymbolFileCommon::GetNumCompileUnits(), m_global_scope_up, and ParseCompileUnitForUID().
Referenced by GetTypes().
ParseCompileUnitForUID()
lldb::CompUnitSP SymbolFilePDB::ParseCompileUnitForUID (uint32_t id, uint32_t index = UINT32_MAX) private
Definition at line 1795 of file SymbolFilePDB.cpp.
References lldb::eLanguageTypeC_plus_plus, lldb::eLanguageTypeUnknown, lldb_private::eLazyBoolNo, GetCompileUnitIndex(), GetPDBCompilandByUID(), lldbassert, m_comp_units, lldb_private::SymbolFileCommon::m_objfile_sp, lldb_private::SymbolFileCommon::SetCompileUnitAtIndex(), TranslateLanguage(), and UINT32_MAX.
Referenced by FindGlobalVariables(), FindGlobalVariables(), GetCompileUnitContainsAddress(), ParseCompileUnitAtIndex(), and ResolveFunction().
ParseCompileUnitFunctionForPDBFunc()
lldb_private::Function * SymbolFilePDB::ParseCompileUnitFunctionForPDBFunc (const llvm::pdb::PDBSymbolFunc & pdb_func, lldb_private::CompileUnit & comp_unit) private
Definition at line 378 of file SymbolFilePDB.cpp.
References lldb_private::CompileUnit::AddFunction(), lldb_private::CompileUnit::FindFunctionByUID(), PDBASTParser::GetDeclForSymbol(), lldb_private::GetLog(), GetMangledForPDBFunc(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::TypeSystemClang::GetPDBParser(), GetTypeSystemForLanguage(), lldb_private::Address::IsValid(), LLDB_INVALID_ADDRESS, LLDB_LOG_ERROR, ParseLanguage(), ResolveTypeUID(), and lldb_private::Symbols.
Referenced by ParseFunctions(), and ResolveFunction().
ParseCompileUnitLineTable()
bool SymbolFilePDB::ParseCompileUnitLineTable (lldb_private::CompileUnit & comp_unit, uint32_t match_line) private
Definition at line 1836 of file SymbolFilePDB.cpp.
References BuildSupportFileIdToSupportFileIndexMap(), lldb_private::UserID::GetID(), GetPDBCompilandByUID(), m_session_up, and lldb_private::CompileUnit::SetLineTable().
Referenced by ParseLineTable().
ParseDebugMacros()
bool SymbolFilePDB::ParseDebugMacros (lldb_private::CompileUnit & comp_unit) override virtual
Implements lldb_private::SymbolFile.
Definition at line 451 of file SymbolFilePDB.cpp.
ParseDeclsForContext()
void SymbolFilePDB::ParseDeclsForContext (lldb_private::CompilerDeclContext decl_ctx) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 792 of file SymbolFilePDB.cpp.
References lldb::eLanguageTypeC_plus_plus, lldb_private::GetLog(), lldb_private::CompilerDeclContext::GetOpaqueDeclContext(), lldb_private::TypeSystemClang::GetPDBParser(), GetTypeSystemForLanguage(), LLDB_LOG_ERROR, and lldb_private::Symbols.
ParseFunctions()
size_t SymbolFilePDB::ParseFunctions (lldb_private::CompileUnit & comp_unit) override virtual
Implements lldb_private::SymbolFile.
Definition at line 425 of file SymbolFilePDB.cpp.
References lldb_private::CompileUnit::FindFunctionByUID(), lldb_private::UserID::GetID(), lldb_private::SymbolFile::GetModuleMutex(), GetPDBCompilandByUID(), and ParseCompileUnitFunctionForPDBFunc().
ParseImportedModules()
bool SymbolFilePDB::ParseImportedModules (const lldb_private::SymbolContext & sc, std::vector< lldb_private::SourceModule > & imported_modules) override virtual
Implements lldb_private::SymbolFile.
Definition at line 480 of file SymbolFilePDB.cpp.
ParseLanguage()
lldb::LanguageType SymbolFilePDB::ParseLanguage (lldb_private::CompileUnit & comp_unit) override virtual
Implements lldb_private::SymbolFile.
Definition at line 366 of file SymbolFilePDB.cpp.
References lldb::eLanguageTypeUnknown, lldb_private::UserID::GetID(), lldb_private::SymbolFile::GetModuleMutex(), GetPDBCompilandByUID(), and TranslateLanguage().
Referenced by ParseCompileUnitFunctionForPDBFunc().
ParseLineTable()
bool SymbolFilePDB::ParseLineTable (lldb_private::CompileUnit & comp_unit) override virtual
Implements lldb_private::SymbolFile.
Definition at line 444 of file SymbolFilePDB.cpp.
References lldb_private::CompileUnit::GetLineTable(), lldb_private::SymbolFile::GetModuleMutex(), and ParseCompileUnitLineTable().
ParseSupportFiles()
bool SymbolFilePDB::ParseSupportFiles (lldb_private::CompileUnit & comp_unit, lldb_private::SupportFileList & support_files) override virtual
Implements lldb_private::SymbolFile.
Definition at line 456 of file SymbolFilePDB.cpp.
References lldb_private::SupportFileList::AppendIfUnique(), lldb_private::UserID::GetID(), lldb_private::SymbolFile::GetModuleMutex(), GetPDBCompilandByUID(), and m_session_up.
ParseTypes()
size_t SymbolFilePDB::ParseTypes (lldb_private::CompileUnit & comp_unit) override virtual
Implements lldb_private::SymbolFile.
Definition at line 536 of file SymbolFilePDB.cpp.
References lldb_private::UserID::GetID(), lldb_private::SymbolFile::GetModuleMutex(), GetPDBCompilandByUID(), m_global_scope_up, and ResolveTypeUID().
ParseVariableForPDBData()
VariableSP SymbolFilePDB::ParseVariableForPDBData (const lldb_private::SymbolContext & sc, const llvm::pdb::PDBSymbolData & pdb_data) private
Definition at line 1005 of file SymbolFilePDB.cpp.
References lldb_private::RangeVector< B, S, N >::Append(), lldb_private::SymbolContext::comp_unit, ConvertPDBLocationToDWARFExpression(), lldb::eValueTypeConstResult, lldb::eValueTypeInvalid, lldb::eValueTypeVariableArgument, lldb::eValueTypeVariableGlobal, lldb::eValueTypeVariableLocal, lldb::eValueTypeVariableStatic, lldb::eValueTypeVariableThreadLocal, lldb_private::Block::FindBlockByID(), lldb_private::SymbolContext::function, lldb_private::AddressRange::GetBaseAddress(), lldb_private::Function::GetBlock(), lldb_private::AddressRange::GetByteSize(), lldb_private::Address::GetFileAddress(), GetMangledForPDBData(), lldb_private::ModuleChild::GetModule(), lldb_private::Block::GetNumRanges(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::Block::GetRangeAtIndex(), m_session_up, m_variables, lldb_private::Declaration::SetColumn(), lldb_private::Declaration::SetFile(), and lldb_private::Declaration::SetLine().
Referenced by ParseVariables().
ParseVariables()
size_t SymbolFilePDB::ParseVariables (const lldb_private::SymbolContext & sc, const llvm::pdb::PDBSymbol & pdb_data, lldb_private::VariableList * variable_list = nullptr) private
Definition at line 1126 of file SymbolFilePDB.cpp.
References lldb_private::VariableList::AddVariableIfUnique(), lldb_private::SymbolContext::comp_unit, lldb_private::Block::FindBlockByID(), lldb_private::SymbolContext::function, lldb_private::Function::GetBlock(), lldb_private::Block::GetBlockVariableList(), PDBASTParser::GetDeclForSymbol(), GetPDBAstParser(), lldb_private::CompileUnit::GetVariableList(), m_variables, ParseVariableForPDBData(), ParseVariables(), lldb_private::Block::SetVariableList(), and lldb_private::CompileUnit::SetVariableList().
Referenced by FindGlobalVariables(), FindGlobalVariables(), ParseVariables(), and ParseVariablesForContext().
ParseVariablesForContext()
size_t SymbolFilePDB::ParseVariablesForContext (const lldb_private::SymbolContext & sc) override virtual
Implements lldb_private::SymbolFile.
Definition at line 589 of file SymbolFilePDB.cpp.
References lldb_private::SymbolContext::comp_unit, lldb_private::SymbolContext::function, lldb_private::Function::GetBlock(), GetCompilandId(), lldb_private::UserID::GetID(), lldb_private::SymbolFile::GetModuleMutex(), GetPDBCompilandByUID(), lldb_private::CompileUnit::GetVariableList(), m_global_scope_up, m_session_up, ParseVariables(), and lldb_private::Block::SetDidParseVariables().
ResolveFunction() [1/2]
bool SymbolFilePDB::ResolveFunction (const llvm::pdb::PDBSymbolFunc & pdb_func, bool include_inlines, lldb_private::SymbolContextList & sc_list) private
Definition at line 1272 of file SymbolFilePDB.cpp.
References lldb_private::SymbolContextList::Append(), lldb_private::SymbolContext::comp_unit, lldb_private::SymbolContext::function, lldb_private::ModuleChild::GetModule(), lldb_private::SymbolContext::module_sp, ParseCompileUnitForUID(), and ParseCompileUnitFunctionForPDBFunc().
Referenced by FindFunctions(), FindFunctions(), and ResolveFunction().
ResolveFunction() [2/2]
bool SymbolFilePDB::ResolveFunction (uint32_t uid, bool include_inlines, lldb_private::SymbolContextList & sc_list) private
Definition at line 1288 of file SymbolFilePDB.cpp.
References m_session_up, and ResolveFunction().
ResolveSymbolContext() [1/2]
uint32_t SymbolFilePDB::ResolveSymbolContext (const lldb_private::Address & so_addr, lldb::SymbolContextItem resolve_scope, lldb_private::SymbolContext & sc) override virtual
Implements lldb_private::SymbolFile.
ResolveSymbolContext() [2/2]
uint32_t SymbolFilePDB::ResolveSymbolContext (const lldb_private::SourceLocationSpec & src_location_spec, lldb::SymbolContextItem resolve_scope, lldb_private::SymbolContextList & sc_list) override virtual
Reimplemented from lldb_private::SymbolFile.
ResolveTypeUID()
lldb_private::Type * SymbolFilePDB::ResolveTypeUID (lldb::user_id_t type_uid) override virtual
Implements lldb_private::SymbolFile.
Definition at line 638 of file SymbolFilePDB.cpp.
References lldb::eLanguageTypeC_plus_plus, lldb_private::GetLog(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::TypeSystemClang::GetPDBParser(), GetTypeSystemForLanguage(), LLDB_LOG_ERROR, m_session_up, m_types, and lldb_private::Symbols.
Referenced by FindTypes(), FindTypesByRegex(), PDBASTParser::GetDeclContextForSymbol(), GetTypesForPDBSymbol(), ParseCompileUnitFunctionForPDBFunc(), and ParseTypes().
Terminate()
void SymbolFilePDB::Terminate () static
Definition at line 199 of file SymbolFilePDB.cpp.
References CreateInstance(), lldb_private::npdb::SymbolFileNativePDB::Terminate(), and lldb_private::PluginManager::UnregisterPlugin().
UseNativePDB()
bool SymbolFilePDB::UseNativePDB () static
Definition at line 205 of file SymbolFilePDB.cpp.
References GetGlobalPluginProperties().
Referenced by lldb_private::npdb::SymbolFileNativePDB::CreateInstance(), and CreateInstance().
Member Data Documentation
ID
char SymbolFilePDB::ID static private
LLVM RTTI support.
Definition at line 27 of file SymbolFilePDB.h.
Referenced by classof(), and isA().
m_builtin_types
std::vector<lldb::TypeSP> SymbolFilePDB::m_builtin_types private
Definition at line 246 of file SymbolFilePDB.h.
m_comp_units
llvm::DenseMap<uint32_t, lldb::CompUnitSP> SymbolFilePDB::m_comp_units private
Definition at line 239 of file SymbolFilePDB.h.
Referenced by ParseCompileUnitForUID().
m_func_base_names
lldb_private::UniqueCStringMap<uint32_t> SymbolFilePDB::m_func_base_names private
Definition at line 251 of file SymbolFilePDB.h.
Referenced by CacheFunctionNames(), FindFunctions(), and FindFunctions().
m_func_full_names
lldb_private::UniqueCStringMap<uint32_t> SymbolFilePDB::m_func_full_names private
Definition at line 250 of file SymbolFilePDB.h.
Referenced by CacheFunctionNames(), FindFunctions(), and FindFunctions().
m_func_method_names
lldb_private::UniqueCStringMap<uint32_t> SymbolFilePDB::m_func_method_names private
Definition at line 252 of file SymbolFilePDB.h.
Referenced by CacheFunctionNames(), and FindFunctions().
m_global_scope_up
std::unique_ptr<llvm::pdb::PDBSymbolExe> SymbolFilePDB::m_global_scope_up private
Definition at line 248 of file SymbolFilePDB.h.
Referenced by AddSymbols(), CacheFunctionNames(), CalculateNumCompileUnits(), FindGlobalVariables(), FindGlobalVariables(), FindTypes(), FindTypesByRegex(), GetCompileUnitIndex(), GetMangledForPDBData(), GetMangledForPDBFunc(), InitializeObject(), ParseCompileUnitAtIndex(), ParseTypes(), ParseVariablesForContext(), and SymbolFilePDB().
m_public_names
llvm::DenseMap<uint64_t, std::string> SymbolFilePDB::m_public_names private
Definition at line 242 of file SymbolFilePDB.h.
Referenced by GetMangledForPDBData().
m_sec_contribs
SecContribsMap SymbolFilePDB::m_sec_contribs private
Definition at line 244 of file SymbolFilePDB.h.
Referenced by GetCompilandId().
m_session_up
std::unique_ptr<llvm::pdb::IPDBSession> SymbolFilePDB::m_session_up private
Definition at line 247 of file SymbolFilePDB.h.
Referenced by BuildSupportFileIdToSupportFileIndexMap(), CalculateAbilities(), GetCompilandId(), GetCompileUnitContainsAddress(), GetDeclContextContainingUID(), GetDeclContextForUID(), GetDeclForUID(), GetPDBCompilandByUID(), GetPDBSession(), GetPDBSession(), InitializeObject(), ParseBlocksRecursive(), ParseCompileUnitLineTable(), ParseSupportFiles(), ParseVariableForPDBData(), ParseVariablesForContext(), ResolveFunction(), ResolveTypeUID(), and SymbolFilePDB().
m_types
llvm::DenseMap<uint32_t, lldb::TypeSP> SymbolFilePDB::m_types private
Definition at line 240 of file SymbolFilePDB.h.
Referenced by FindTypes(), FindTypesByRegex(), and ResolveTypeUID().
m_variables
llvm::DenseMap<uint32_t, lldb::VariableSP> SymbolFilePDB::m_variables private
Definition at line 241 of file SymbolFilePDB.h.
Referenced by ParseVariableForPDBData(), and ParseVariables().
The documentation for this class was generated from the following files:
SymbolFilePDB.h
SymbolFilePDB.cpp