LLDB: lldb::SBFile Class Reference
lldb::SBFile Class Reference
#include <SBFile.h>
Public Member Functions
SBFile ()
SBFile (FileSP file_sp)
SBFile (const SBFile &rhs)
LLDB_DEPRECATED_FIXME ("Use the constructor that specifies mode instead", "SBFile(FILE*, const char*, bool)") SBFile(FILE *file
SBFile (FILE *file, const char *mode, bool transfer_ownership)
SBFile (int fd, const char *mode, bool transfer_ownership)
~SBFile ()
SBFile & operator= (const SBFile &rhs)
SBError Read (uint8_t *buf, size_t num_bytes, size_t *OUTPUT)
SBError Write (const uint8_t *buf, size_t num_bytes, size_t *OUTPUT)
SBError Flush ()
bool IsValid () const
SBError Close ()
operator bool () const
bool operator! () const
FileSP GetFile () const
Public Attributes
bool transfer_ownership
Private Attributes
FileSP m_opaque_sp
Friends
class SBInstruction
class SBInstructionList
class SBDebugger
class SBCommandReturnObject
class SBProcess
Detailed Description
Definition at line 18 of file SBFile.h.
Constructor & Destructor Documentation
SBFile() [1/5]
SBFile::SBFile ()
Definition at line 37 of file SBFile.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by operator=(), SBFile(), SBProcess, and ~SBFile().
SBFile() [2/5]
SBFile::SBFile (FileSP file_sp)
Definition at line 19 of file SBFile.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
SBFile() [3/5]
SBFile::SBFile (const SBFile & rhs)
Definition at line 25 of file SBFile.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBFile().
SBFile() [4/5]
SBFile::SBFile (FILE * file, const char * mode, bool transfer_ownership)
Definition at line 47 of file SBFile.cpp.
References lldb_private::File::GetOptionsFromMode(), LLDB_INSTRUMENT_VA, m_opaque_sp, and transfer_ownership.
SBFile() [5/5]
SBFile::SBFile (int fd, const char * mode, bool transfer_ownership)
Definition at line 60 of file SBFile.cpp.
References lldb_private::File::GetOptionsFromMode(), LLDB_INSTRUMENT_VA, m_opaque_sp, and transfer_ownership.
~SBFile()
SBFile::~SBFile () default
References Close(), Flush(), GetFile(), IsValid(), operator!(), operator=(), Read(), SBFile(), and Write().
Member Function Documentation
Close()
SBError SBFile::Close ()
Definition at line 118 of file SBFile.cpp.
References error(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBFile().
Flush()
SBError SBFile::Flush ()
Definition at line 101 of file SBFile.cpp.
References error(), lldb_private::Status::FromErrorString(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBFile().
GetFile()
FileSP SBFile::GetFile () const
Definition at line 136 of file SBFile.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by lldb::SBStream::RedirectToFile(), and ~SBFile().
IsValid()
bool SBFile::IsValid () const
Definition at line 113 of file SBFile.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by operator bool(), operator!(), lldb::SBInstructionList::Print(), and ~SBFile().
LLDB_DEPRECATED_FIXME()
lldb::SBFile::LLDB_DEPRECATED_FIXME ("Use the constructor that specifies mode instead" , "SBFile(FILE*, const char*, bool)")
operator bool()
SBFile::operator bool () const
Definition at line 126 of file SBFile.cpp.
References IsValid(), and LLDB_INSTRUMENT_VA.
operator!()
bool SBFile::operator! () const
Definition at line 131 of file SBFile.cpp.
References IsValid(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBFile().
operator=()
SBFile & SBFile::operator= (const SBFile & rhs)
Definition at line 29 of file SBFile.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBFile().
Referenced by ~SBFile().
Read()
SBError SBFile::Read (uint8_t * buf, size_t num_bytes, size_t * OUTPUT)
Definition at line 72 of file SBFile.cpp.
References error(), lldb_private::Status::FromErrorString(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBFile().
Write()
SBError SBFile::Write (const uint8_t * buf, size_t num_bytes, size_t * OUTPUT)
Definition at line 86 of file SBFile.cpp.
References error(), lldb_private::Status::FromErrorString(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBFile().
Friends And Related Symbol Documentation
SBCommandReturnObject
friend class SBCommandReturnObject friend
Definition at line 22 of file SBFile.h.
References SBCommandReturnObject.
Referenced by SBCommandReturnObject.
SBDebugger
friend class SBDebugger friend
Definition at line 21 of file SBFile.h.
References SBDebugger.
Referenced by SBDebugger.
SBInstruction
friend class SBInstruction friend
Definition at line 19 of file SBFile.h.
References SBInstruction.
Referenced by SBInstruction.
SBInstructionList
friend class SBInstructionList friend
Definition at line 20 of file SBFile.h.
References SBInstructionList.
Referenced by SBInstructionList.
SBProcess
friend class SBProcess friend
Definition at line 23 of file SBFile.h.
References SBFile(), and SBProcess.
Referenced by SBProcess.
Member Data Documentation
m_opaque_sp
FileSP lldb::SBFile::m_opaque_sp private
Definition at line 54 of file SBFile.h.
Referenced by Close(), Flush(), GetFile(), IsValid(), operator=(), lldb::SBInstruction::Print(), lldb::SBInstructionList::Print(), lldb::SBCommandReturnObject::PutError(), lldb::SBCommandReturnObject::PutOutput(), Read(), lldb::SBProcess::ReportEventState(), SBFile(), SBFile(), SBFile(), SBFile(), lldb::SBDebugger::SetErrorFile(), lldb::SBCommandReturnObject::SetImmediateErrorFile(), lldb::SBCommandReturnObject::SetImmediateOutputFile(), lldb::SBDebugger::SetInputFile(), lldb::SBDebugger::SetOutputFile(), and Write().
transfer_ownership
bool lldb::SBFile::transfer_ownership
Definition at line 32 of file SBFile.h.
Referenced by SBFile(), and SBFile().
The documentation for this class was generated from the following files:
SBFile.h
SBFile.cpp