LLDB: lldb::SBFileSpecList Class Reference
lldb::SBFileSpecList Class Reference
#include <SBFileSpecList.h>
Public Member Functions
SBFileSpecList ()
SBFileSpecList (const lldb::SBFileSpecList &rhs)
~SBFileSpecList ()
const SBFileSpecList & operator= (const lldb::SBFileSpecList &rhs)
uint32_t GetSize () const
bool GetDescription (SBStream &description) const
void Append (const SBFileSpec &sb_file)
bool AppendIfUnique (const SBFileSpec &sb_file)
void Clear ()
uint32_t FindFileIndex (uint32_t idx, const SBFileSpec &sb_file, bool full)
const SBFileSpec GetFileSpecAtIndex (uint32_t idx) const
Private Member Functions
const lldb_private::FileSpecList * operator-> () const
const lldb_private::FileSpecList * get () const
const lldb_private::FileSpecList & operator* () const
const lldb_private::FileSpecList & ref () const
Private Attributes
std::unique_ptr< lldb_private::FileSpecList > m_opaque_up
Friends
class SBTarget
Detailed Description
Definition at line 17 of file SBFileSpecList.h.
Constructor & Destructor Documentation
SBFileSpecList() [1/2]
SBFileSpecList::SBFileSpecList ()
Definition at line 24 of file SBFileSpecList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by operator=(), SBFileSpecList(), and ~SBFileSpecList().
SBFileSpecList() [2/2]
SBFileSpecList::SBFileSpecList (const lldb::SBFileSpecList & rhs)
Definition at line 28 of file SBFileSpecList.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBFileSpecList().
~SBFileSpecList()
SBFileSpecList::~SBFileSpecList () default
References Append(), AppendIfUnique(), Clear(), GetDescription(), GetFileSpecAtIndex(), GetSize(), operator=(), and SBFileSpecList().
Member Function Documentation
Append()
void SBFileSpecList::Append (const SBFileSpec & sb_file)
Definition at line 50 of file SBFileSpecList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBFileSpec::ref().
Referenced by lldb::SBTarget::BreakpointCreateByRegex(), lldb::SBTarget::BreakpointCreateBySourceRegex(), and ~SBFileSpecList().
AppendIfUnique()
bool SBFileSpecList::AppendIfUnique (const SBFileSpec & sb_file)
Definition at line 56 of file SBFileSpecList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBFileSpec::ref().
Referenced by ~SBFileSpecList().
Clear()
void SBFileSpecList::Clear ()
Definition at line 62 of file SBFileSpecList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBFileSpecList().
FindFileIndex()
uint32_t SBFileSpecList::FindFileIndex (uint32_t idx, const SBFileSpec & sb_file, bool full)
Definition at line 68 of file SBFileSpecList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBFileSpec::ref().
get()
const lldb_private::FileSpecList * SBFileSpecList::get () const private
Definition at line 87 of file SBFileSpecList.cpp.
References m_opaque_up.
Referenced by lldb::SBTarget::BreakpointCreateByLocation(), lldb::SBTarget::BreakpointCreateByLocation(), lldb::SBTarget::BreakpointCreateByName(), lldb::SBTarget::BreakpointCreateByNames(), lldb::SBTarget::BreakpointCreateByRegex(), lldb::SBTarget::BreakpointCreateBySourceRegex(), lldb::SBTarget::BreakpointCreateFromScript(), and SBTarget.
GetDescription()
bool SBFileSpecList::GetDescription (SBStream & description) const
Definition at line 99 of file SBFileSpecList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, PATH_MAX, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
Referenced by ~SBFileSpecList().
GetFileSpecAtIndex()
const SBFileSpec SBFileSpecList::GetFileSpecAtIndex (uint32_t idx) const
Definition at line 75 of file SBFileSpecList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBFileSpec::SetFileSpec().
Referenced by ~SBFileSpecList().
GetSize()
uint32_t SBFileSpecList::GetSize () const
Definition at line 44 of file SBFileSpecList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBTarget::BreakpointCreateByLocation(), lldb::SBTarget::BreakpointCreateByLocation(), and ~SBFileSpecList().
operator*()
const lldb_private::FileSpecList & SBFileSpecList::operator* () const private
Definition at line 91 of file SBFileSpecList.cpp.
References m_opaque_up.
Referenced by SBTarget.
operator->()
const lldb_private::FileSpecList * SBFileSpecList::operator-> () const private
Definition at line 83 of file SBFileSpecList.cpp.
References m_opaque_up.
Referenced by SBTarget.
operator=()
const SBFileSpecList & SBFileSpecList::operator= (const lldb::SBFileSpecList & rhs)
Definition at line 36 of file SBFileSpecList.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBFileSpecList().
Referenced by ~SBFileSpecList().
ref()
const lldb_private::FileSpecList & SBFileSpecList::ref () const private
Definition at line 95 of file SBFileSpecList.cpp.
References m_opaque_up.
Referenced by SBTarget.
Friends And Related Symbol Documentation
SBTarget
friend class SBTarget friend
Definition at line 42 of file SBFileSpecList.h.
References get(), operator*(), operator->(), ref(), and SBTarget.
Referenced by SBTarget.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::FileSpecList> lldb::SBFileSpecList::m_opaque_up private
Definition at line 52 of file SBFileSpecList.h.
Referenced by Append(), AppendIfUnique(), Clear(), FindFileIndex(), get(), GetDescription(), GetFileSpecAtIndex(), GetSize(), operator*(), operator->(), operator=(), ref(), SBFileSpecList(), and SBFileSpecList().
The documentation for this class was generated from the following files:
SBFileSpecList.h
SBFileSpecList.cpp