LLDB: lldb_private::TypeFilterImpl::FrontEnd Class Reference
lldb_private::TypeFilterImpl::FrontEnd Class Reference
#include <TypeSynthetic.h>
Public Types
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Public Member Functions
FrontEnd (TypeFilterImpl *flt, ValueObject &backend)
~FrontEnd () override=default
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
bool MightHaveChildren () override
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Member Functions
FrontEnd (const FrontEnd &)=delete
const FrontEnd & operator= (const FrontEnd &)=delete
Private Attributes
TypeFilterImpl * filter
Additional Inherited Members
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
Definition at line 323 of file TypeSynthetic.h.
Member Typedef Documentation
SharedPointer
typedef std::shared_ptr<SyntheticChildrenFrontEnd> lldb_private::TypeFilterImpl::FrontEnd::SharedPointer
Definition at line 349 of file TypeSynthetic.h.
Constructor & Destructor Documentation
FrontEnd() [1/2]
lldb_private::TypeFilterImpl::FrontEnd::FrontEnd (TypeFilterImpl * flt, ValueObject & backend) inline
Definition at line 325 of file TypeSynthetic.h.
References filter, lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd(), and lldb_private::TypeFilterImpl::TypeFilterImpl().
Referenced by FrontEnd(), and operator=().
~FrontEnd()
lldb_private::TypeFilterImpl::FrontEnd::~FrontEnd () override default
FrontEnd() [2/2]
lldb_private::TypeFilterImpl::FrontEnd::FrontEnd (const FrontEnd &) private delete
References FrontEnd().
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > lldb_private::TypeFilterImpl::FrontEnd::CalculateNumChildren () inline override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 330 of file TypeSynthetic.h.
References filter.
GetChildAtIndex()
lldb::ValueObjectSP lldb_private::TypeFilterImpl::FrontEnd::GetChildAtIndex (uint32_t idx) inline override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 334 of file TypeSynthetic.h.
References filter, and lldb_private::SyntheticChildrenFrontEnd::m_backend.
GetIndexOfChildWithName()
llvm::Expected< size_t > TypeFilterImpl::FrontEnd::GetIndexOfChildWithName (ConstString name) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 56 of file TypeSynthetic.cpp.
References lldb_private::ConstString::AsCString(), filter, and lldb_private::ConstString::GetCString().
MightHaveChildren()
bool lldb_private::TypeFilterImpl::FrontEnd::MightHaveChildren () inline override virtual
Reimplemented from lldb_private::SyntheticChildrenFrontEnd.
Definition at line 345 of file TypeSynthetic.h.
References filter.
operator=()
const FrontEnd & lldb_private::TypeFilterImpl::FrontEnd::operator= (const FrontEnd &) private delete
References FrontEnd().
Update()
lldb::ChildCacheState lldb_private::TypeFilterImpl::FrontEnd::Update () inline override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 341 of file TypeSynthetic.h.
References lldb::eRefetch.
Member Data Documentation
filter
TypeFilterImpl* lldb_private::TypeFilterImpl::FrontEnd::filter private
Definition at line 352 of file TypeSynthetic.h.
Referenced by CalculateNumChildren(), FrontEnd(), GetChildAtIndex(), GetIndexOfChildWithName(), and MightHaveChildren().
The documentation for this class was generated from the following files:
TypeSynthetic.h
TypeSynthetic.cpp