LLDB: lldb_private::StopCondition Class Reference
lldb_private::StopCondition Class Reference
#include <StopCondition.h>
Public Member Functions
StopCondition ()=default
StopCondition (std::string text, lldb::LanguageType language=lldb::eLanguageTypeUnknown)
operator bool () const
llvm::StringRef GetText () const
void SetText (std::string text)
size_t GetHash () const
lldb::LanguageType GetLanguage () const
void SetLanguage (lldb::LanguageType language)
Private Attributes
std::string m_text
The condition to test.
size_t m_hash = 0
Its hash, so that locations know when the condition is updated.
lldb::LanguageType m_language = lldb::eLanguageTypeUnknown
The language for this condition.
Detailed Description
Definition at line 17 of file StopCondition.h.
Constructor & Destructor Documentation
StopCondition() [1/2]
lldb_private::StopCondition::StopCondition () default
StopCondition() [2/2]
lldb_private::StopCondition::StopCondition (std::string text, lldb::LanguageType language = lldb::eLanguageTypeUnknown) inline
Definition at line 20 of file StopCondition.h.
References lldb::eLanguageTypeUnknown, m_language, and SetText().
Member Function Documentation
GetHash()
size_t lldb_private::StopCondition::GetHash () const inline
Definition at line 36 of file StopCondition.h.
References m_hash.
Referenced by lldb_private::BreakpointLocation::ConditionSaysStop().
GetLanguage()
lldb::LanguageType lldb_private::StopCondition::GetLanguage () const inline
Definition at line 38 of file StopCondition.h.
References m_language.
Referenced by lldb_private::BreakpointLocation::ConditionSaysStop().
GetText()
llvm::StringRef lldb_private::StopCondition::GetText () const inline
Definition at line 28 of file StopCondition.h.
References m_text.
Referenced by lldb_private::BreakpointLocation::ConditionSaysStop(), lldb::SBBreakpoint::GetCondition(), lldb::SBBreakpointLocation::GetCondition(), and lldb::SBBreakpointName::GetCondition().
operator bool()
lldb_private::StopCondition::operator bool () const inline explicit
Definition at line 26 of file StopCondition.h.
References m_text.
SetLanguage()
void lldb_private::StopCondition::SetLanguage (lldb::LanguageType language) inline
Definition at line 40 of file StopCondition.h.
References m_language.
SetText()
void lldb_private::StopCondition::SetText (std::string text) inline
Definition at line 30 of file StopCondition.h.
References m_hash, and m_text.
Referenced by StopCondition().
Member Data Documentation
m_hash
size_t lldb_private::StopCondition::m_hash = 0 private
Its hash, so that locations know when the condition is updated.
Definition at line 47 of file StopCondition.h.
Referenced by GetHash(), and SetText().
m_language
lldb::LanguageType lldb_private::StopCondition::m_language = lldb::eLanguageTypeUnknown private
The language for this condition.
Definition at line 50 of file StopCondition.h.
Referenced by GetLanguage(), SetLanguage(), and StopCondition().
m_text
std::string lldb_private::StopCondition::m_text private
The condition to test.
Definition at line 44 of file StopCondition.h.
Referenced by GetText(), operator bool(), and SetText().
The documentation for this class was generated from the following file:
StopCondition.h