LLDB: lldb_private::dil::IntegerLiteralNode Class Reference
lldb_private::dil::IntegerLiteralNode Class Reference
#include <DILAST.h>
Public Member Functions
IntegerLiteralNode (uint32_t location, llvm::APInt value, uint32_t radix, bool is_unsigned, IntegerTypeSuffix type)
llvm::Expected< lldb::ValueObjectSP > Accept (Visitor *v) const override
const llvm::APInt & GetValue () const
uint32_t GetRadix () const
bool IsUnsigned () const
IntegerTypeSuffix GetTypeSuffix () const
Public Member Functions inherited from lldb_private::dil::ASTNode
ASTNode (uint32_t location, NodeKind kind)
virtual ~ASTNode ()=default
uint32_t GetLocation () const
NodeKind GetKind () const
Static Public Member Functions
static bool classof (const ASTNode &node)
Private Attributes
llvm::APInt m_value
uint32_t m_radix
bool m_is_unsigned
IntegerTypeSuffix m_type
Detailed Description
Definition at line 197 of file DILAST.h.
Constructor & Destructor Documentation
IntegerLiteralNode()
lldb_private::dil::IntegerLiteralNode::IntegerLiteralNode (uint32_t location, llvm::APInt value, uint32_t radix, bool is_unsigned, IntegerTypeSuffix type) inline
Definition at line 199 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), lldb_private::dil::eIntegerLiteralNode, m_is_unsigned, m_radix, m_type, and m_value.
Member Function Documentation
Accept()
llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::IntegerLiteralNode::Accept (Visitor * v) const override virtual
Implements lldb_private::dil::ASTNode.
Definition at line 41 of file DILAST.cpp.
References lldb_private::dil::Visitor::Visit().
classof()
bool lldb_private::dil::IntegerLiteralNode::classof (const ASTNode & node) inline static
Definition at line 212 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), lldb_private::dil::eIntegerLiteralNode, and lldb_private::dil::ASTNode::GetKind().
GetRadix()
uint32_t lldb_private::dil::IntegerLiteralNode::GetRadix () const inline
Definition at line 208 of file DILAST.h.
References m_radix.
Referenced by lldb_private::dil::Interpreter::PickIntegerType().
GetTypeSuffix()
IntegerTypeSuffix lldb_private::dil::IntegerLiteralNode::GetTypeSuffix () const inline
Definition at line 210 of file DILAST.h.
References m_type.
Referenced by lldb_private::dil::Interpreter::PickIntegerType().
GetValue()
const llvm::APInt & lldb_private::dil::IntegerLiteralNode::GetValue () const inline
Definition at line 207 of file DILAST.h.
References m_value.
Referenced by lldb_private::dil::Interpreter::PickIntegerType(), and lldb_private::dil::Interpreter::Visit().
IsUnsigned()
bool lldb_private::dil::IntegerLiteralNode::IsUnsigned () const inline
Definition at line 209 of file DILAST.h.
References m_is_unsigned.
Referenced by lldb_private::dil::Interpreter::PickIntegerType().
Member Data Documentation
m_is_unsigned
bool lldb_private::dil::IntegerLiteralNode::m_is_unsigned private
Definition at line 219 of file DILAST.h.
Referenced by IntegerLiteralNode(), and IsUnsigned().
m_radix
uint32_t lldb_private::dil::IntegerLiteralNode::m_radix private
Definition at line 218 of file DILAST.h.
Referenced by GetRadix(), and IntegerLiteralNode().
m_type
IntegerTypeSuffix lldb_private::dil::IntegerLiteralNode::m_type private
Definition at line 220 of file DILAST.h.
Referenced by GetTypeSuffix(), and IntegerLiteralNode().
m_value
llvm::APInt lldb_private::dil::IntegerLiteralNode::m_value private
Definition at line 217 of file DILAST.h.
Referenced by GetValue(), and IntegerLiteralNode().
The documentation for this class was generated from the following files:
DILAST.h
DILAST.cpp