LLDB: lldb_private::python::PythonDictionary Class Reference
lldb_private::python::PythonDictionary Class Reference
#include <PythonDataObjects.h>
Public Member Functions
PythonDictionary ()
PythonDictionary (PyInitialValue value)
bool HasKey (const llvm::Twine &key) const
uint32_t GetSize () const
PythonList GetKeys () const
PythonObject GetItemForKey (const PythonObject &key) const
void SetItemForKey (const PythonObject &key, const PythonObject &value)
llvm::Expected< PythonObject > GetItem (const PythonObject &key) const
llvm::Expected< PythonObject > GetItem (const llvm::Twine &key) const
llvm::Error SetItem (const PythonObject &key, const PythonObject &value) const
llvm::Error SetItem (const llvm::Twine &key, const PythonObject &value) const
StructuredData::DictionarySP CreateStructuredDictionary () const
TypedPythonObject (PyRefType type, PyObject *py_obj)
TypedPythonObject ()=default
Public Member Functions inherited from lldb_private::python::TypedPythonObject< PythonDictionary >
TypedPythonObject (PyRefType type, PyObject *py_obj)
Public Member Functions inherited from lldb_private::python::PythonObject
PythonObject ()=default
PythonObject (PyRefType type, PyObject *py_obj)
PythonObject (const PythonObject &rhs)
PythonObject (PythonObject &&rhs)
~PythonObject ()
void Reset ()
void Dump (Stream &strm) const
PyObject * get () const
PyObject * release ()
PythonObject & operator= (PythonObject other)
PyObjectType GetObjectType () const
PythonString Repr () const
PythonString Str () const
PythonObject ResolveName (llvm::StringRef name) const
template<typename T>
T ResolveName (llvm::StringRef name) const
bool HasAttribute (llvm::StringRef attribute) const
PythonObject GetAttributeValue (llvm::StringRef attribute) const
bool IsNone () const
bool IsValid () const
bool IsAllocated () const
operator bool () const
template<typename T>
T AsType () const
StructuredData::ObjectSP CreateStructuredObject () const
template<typename... T>
llvm::Expected< PythonObject > CallMethod (const char *name, const T &... t) const
template<typename... T>
llvm::Expected< PythonObject > Call (const T &... t) const
llvm::Expected< PythonObject > GetAttribute (const llvm::Twine &name) const
llvm::Expected< PythonObject > GetType () const
llvm::Expected< bool > IsTrue ()
llvm::Expected< long long > AsLongLong () const
llvm::Expected< unsigned long long > AsUnsignedLongLong () const
llvm::Expected< unsigned long long > AsModuloUnsignedLongLong () const
llvm::Expected< bool > IsInstance (const PythonObject &cls)
Static Public Member Functions
static bool Check (PyObject *py_obj)
Static Public Member Functions inherited from lldb_private::python::PythonObject
static PythonObject ResolveNameWithDictionary (llvm::StringRef name, const PythonDictionary &dict)
template<typename T>
static T ResolveNameWithDictionary (llvm::StringRef name, const PythonDictionary &dict)
Additional Inherited Members
Protected Attributes inherited from lldb_private::python::PythonObject
PyObject * m_py_obj = nullptr
Detailed Description
Definition at line 545 of file PythonDataObjects.h.
Constructor & Destructor Documentation
PythonDictionary() [1/2]
lldb_private::python::PythonDictionary::PythonDictionary () inline
Definition at line 549 of file PythonDataObjects.h.
References TypedPythonObject().
PythonDictionary() [2/2]
PythonDictionary::PythonDictionary (PyInitialValue value) explicit
Definition at line 651 of file PythonDataObjects.cpp.
References lldb_private::python::Empty, and lldb_private::python::Take().
Member Function Documentation
Check()
bool PythonDictionary::Check (PyObject * py_obj) static
Definition at line 656 of file PythonDataObjects.cpp.
Referenced by lldb_private::python::PythonObject::GetObjectType().
CreateStructuredDictionary()
StructuredData::DictionarySP PythonDictionary::CreateStructuredDictionary () const
Definition at line 749 of file PythonDataObjects.cpp.
References lldb_private::python::PythonObject::CreateStructuredObject(), lldb_private::python::PythonList::GetItemAtIndex(), GetItemForKey(), GetKeys(), lldb_private::python::PythonList::GetSize(), lldb_private::python::PythonString::GetString(), and lldb_private::python::PythonObject::Str().
Referenced by lldb_private::python::PythonObject::CreateStructuredObject(), and ScriptedPythonInterface::ExtractValueFromPythonObject< StructuredData::DictionarySP >().
GetItem() [1/2]
llvm::Expected< PythonObject > lldb_private::python::PythonDictionary::GetItem (const llvm::Twine & key) const
GetItem() [2/2]
Expected< PythonObject > PythonDictionary::GetItem (const PythonObject & key) const
Definition at line 699 of file PythonDataObjects.cpp.
References lldb_private::python::exception(), lldb_private::python::PythonObject::get(), lldb_private::python::PythonObject::IsValid(), lldb_private::python::keyError(), lldb_private::python::PythonObject::m_py_obj, lldb_private::python::nullDeref(), and lldb_private::python::Retain().
Referenced by lldb_private::ScriptedPythonInterface::CheckAbstractMethodImplementation(), GetItemForKey(), and lldb_private::python::PythonScript::Init().
GetItemForKey()
PythonObject PythonDictionary::GetItemForKey (const PythonObject & key) const
Definition at line 689 of file PythonDataObjects.cpp.
References GetItem(), and lldb_private::python::PythonObject::PythonObject().
Referenced by CreateStructuredDictionary(), and lldb_private::python::PythonObject::ResolveNameWithDictionary().
GetKeys()
PythonList PythonDictionary::GetKeys () const
Definition at line 683 of file PythonDataObjects.cpp.
References lldb_private::python::Invalid, lldb_private::python::PythonObject::IsValid(), lldb_private::python::PythonObject::m_py_obj, and lldb_private::python::Owned.
Referenced by CreateStructuredDictionary().
GetSize()
uint32_t PythonDictionary::GetSize () const
Definition at line 677 of file PythonDataObjects.cpp.
References lldb_private::python::PythonObject::IsValid(), and lldb_private::python::PythonObject::m_py_obj.
HasKey()
bool PythonDictionary::HasKey (const llvm::Twine & key) const
Definition at line 663 of file PythonDataObjects.cpp.
References lldb_private::python::PythonObject::get(), lldb_private::python::PythonObject::IsValid(), and lldb_private::python::PythonObject::m_py_obj.
Referenced by lldb_private::ScriptedPythonInterface::CheckAbstractMethodImplementation().
SetItem() [1/2]
llvm::Error lldb_private::python::PythonDictionary::SetItem (const llvm::Twine & key, const PythonObject & value) const
SetItem() [2/2]
Error PythonDictionary::SetItem (const PythonObject & key, const PythonObject & value) const
Definition at line 721 of file PythonDataObjects.cpp.
References lldb_private::python::exception(), lldb_private::python::PythonObject::get(), lldb_private::python::PythonObject::IsValid(), lldb_private::python::PythonObject::m_py_obj, and lldb_private::python::nullDeref().
Referenced by lldb_private::python::PythonScript::Init(), and SetItemForKey().
SetItemForKey()
void PythonDictionary::SetItemForKey (const PythonObject & key, const PythonObject & value)
Definition at line 741 of file PythonDataObjects.cpp.
References error(), and SetItem().
TypedPythonObject() [1/2]
lldb_private::python::TypedPythonObject< T >::TypedPythonObject () default
TypedPythonObject() [2/2]
lldb_private::python::TypedPythonObject< T >::TypedPythonObject (PyRefType type, PyObject * py_obj) inline
Definition at line 400 of file PythonDataObjects.h.
Referenced by PythonDictionary().
The documentation for this class was generated from the following files:
PythonDataObjects.h
PythonDataObjects.cpp