LLDB: lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd Class Reference
lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd Class Reference
Public Member Functions
LibcxxStdValarraySyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
~LibcxxStdValarraySyntheticFrontEnd () override
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Attributes
ValueObject * m_start = nullptr
A non-owning pointer to valarray's __begin_ member.
ValueObject * m_finish = nullptr
A non-owning pointer to valarray's __end_ member.
CompilerType m_element_type
The type of valarray's template argument T.
uint32_t m_element_size = 0
The sizeof valarray's template argument T.
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
Definition at line 21 of file LibCxxValarray.cpp.
Constructor & Destructor Documentation
LibcxxStdValarraySyntheticFrontEnd()
lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd::LibcxxStdValarraySyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
Definition at line 49 of file LibCxxValarray.cpp.
References m_element_type, lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd(), and Update().
~LibcxxStdValarraySyntheticFrontEnd()
lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd::~LibcxxStdValarraySyntheticFrontEnd () override
Definition at line 56 of file LibCxxValarray.cpp.
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd::CalculateNumChildren () override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 64 of file LibCxxValarray.cpp.
References m_element_size, m_finish, and m_start.
GetChildAtIndex()
lldb::ValueObjectSP lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd::GetChildAtIndex (uint32_t idx) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 84 of file LibCxxValarray.cpp.
References lldb_private::SyntheticChildrenFrontEnd::CreateValueObjectFromAddress(), lldb_private::StreamString::GetString(), lldb_private::SyntheticChildrenFrontEnd::m_backend, m_element_size, m_element_type, m_finish, m_start, and lldb_private::Stream::Printf().
GetIndexOfChildWithName()
llvm::Expected< size_t > lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd::GetIndexOfChildWithName (ConstString name) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 127 of file LibCxxValarray.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::formatters::ExtractIndexFromString(), lldb_private::ConstString::GetCString(), m_finish, and m_start.
Update()
lldb::ChildCacheState lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd::Update () override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 99 of file LibCxxValarray.cpp.
References lldb::eRefetch, lldb_private::CompilerType::GetNumTemplateArguments(), lldb_private::CompilerType::GetTypeTemplateArgument(), lldb_private::SyntheticChildrenFrontEnd::m_backend, m_element_size, m_element_type, m_finish, and m_start.
Referenced by LibcxxStdValarraySyntheticFrontEnd().
Member Data Documentation
m_element_size
uint32_t lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd::m_element_size = 0 private
The sizeof valarray's template argument T.
Definition at line 43 of file LibCxxValarray.cpp.
Referenced by CalculateNumChildren(), GetChildAtIndex(), and Update().
m_element_type
CompilerType lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd::m_element_type private
The type of valarray's template argument T.
Definition at line 41 of file LibCxxValarray.cpp.
Referenced by GetChildAtIndex(), LibcxxStdValarraySyntheticFrontEnd(), and Update().
m_finish
ValueObject* lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd::m_finish = nullptr private
A non-owning pointer to valarray's __end_ member.
Definition at line 39 of file LibCxxValarray.cpp.
Referenced by CalculateNumChildren(), GetChildAtIndex(), GetIndexOfChildWithName(), and Update().
m_start
ValueObject* lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd::m_start = nullptr private
A non-owning pointer to valarray's __begin_ member.
Definition at line 37 of file LibCxxValarray.cpp.
Referenced by CalculateNumChildren(), GetChildAtIndex(), GetIndexOfChildWithName(), and Update().
The documentation for this class was generated from the following file:
LibCxxValarray.cpp