LLDB: lldb_private::NativeRegisterContext Class Reference
lldb_private::NativeRegisterContext Class Reference abstract
#include <NativeRegisterContext.h>
Public Member Functions
NativeRegisterContext (NativeThreadProtocol &thread)
virtual ~NativeRegisterContext ()
virtual uint32_t GetRegisterCount () const =0
virtual uint32_t GetUserRegisterCount () const =0
virtual const RegisterInfo * GetRegisterInfoAtIndex (uint32_t reg) const =0
const char * GetRegisterSetNameForRegisterAtIndex (uint32_t reg_index) const
virtual uint32_t GetRegisterSetCount () const =0
virtual const RegisterSet * GetRegisterSet (uint32_t set_index) const =0
virtual Status ReadRegister (const RegisterInfo *reg_info, RegisterValue &reg_value)=0
virtual Status WriteRegister (const RegisterInfo *reg_info, const RegisterValue &reg_value)=0
virtual Status ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp)=0
virtual Status WriteAllRegisterValues (const lldb::DataBufferSP &data_sp)=0
uint32_t ConvertRegisterKindToRegisterNumber (uint32_t kind, uint32_t num) const
virtual uint32_t NumSupportedHardwareBreakpoints ()
virtual uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual bool ClearHardwareBreakpoint (uint32_t hw_idx)
virtual Status ClearAllHardwareBreakpoints ()
virtual Status GetHardwareBreakHitIndex (uint32_t &bp_index, lldb::addr_t trap_addr)
virtual uint32_t NumSupportedHardwareWatchpoints ()
virtual uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, uint32_t watch_flags)
virtual bool ClearHardwareWatchpoint (uint32_t hw_index)
virtual Status ClearWatchpointHit (uint32_t hw_index)
virtual Status ClearAllHardwareWatchpoints ()
virtual Status IsWatchpointHit (uint32_t wp_index, bool &is_hit)
virtual Status GetWatchpointHitIndex (uint32_t &wp_index, lldb::addr_t trap_addr)
virtual Status IsWatchpointVacant (uint32_t wp_index, bool &is_vacant)
virtual lldb::addr_t GetWatchpointAddress (uint32_t wp_index)
virtual lldb::addr_t GetWatchpointHitAddress (uint32_t wp_index)
virtual bool HardwareSingleStep (bool enable)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, size_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, size_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual NativeThreadProtocol & GetThread ()
virtual std::vector< uint32_t > GetExpeditedRegisters (ExpeditedRegs expType) const
virtual bool RegisterOffsetIsDynamic () const
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (uint32_t reg_kind, uint32_t reg_num)
lldb::addr_t GetPC (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
virtual lldb::addr_t GetPCfromBreakpointLocation (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
Status SetPC (lldb::addr_t pc)
lldb::addr_t GetSP (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
Status SetSP (lldb::addr_t sp)
lldb::addr_t GetFP (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
Status SetFP (lldb::addr_t fp)
const char * GetRegisterName (uint32_t reg)
lldb::addr_t GetReturnAddress (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
lldb::addr_t GetFlags (lldb::addr_t fail_value=0)
lldb::addr_t ReadRegisterAsUnsigned (uint32_t reg, lldb::addr_t fail_value)
lldb::addr_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, lldb::addr_t fail_value)
Status WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
Status WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
Protected Attributes
NativeThreadProtocol & m_thread
Private Member Functions
NativeRegisterContext (const NativeRegisterContext &)=delete
const NativeRegisterContext & operator= (const NativeRegisterContext &)=delete
Detailed Description
Definition at line 21 of file NativeRegisterContext.h.
Constructor & Destructor Documentation
NativeRegisterContext() [1/2]
NativeRegisterContext::NativeRegisterContext (NativeThreadProtocol & thread)
Definition at line 20 of file NativeRegisterContext.cpp.
References m_thread.
Referenced by NativeRegisterContext(), lldb_private::NativeRegisterContextRegisterInfo::NativeRegisterContextRegisterInfo(), and operator=().
~NativeRegisterContext()
NativeRegisterContext::~NativeRegisterContext () virtual default
NativeRegisterContext() [2/2]
lldb_private::NativeRegisterContext::NativeRegisterContext (const NativeRegisterContext &) private delete
References NativeRegisterContext().
Member Function Documentation
ClearAllHardwareBreakpoints()
Status NativeRegisterContext::ClearAllHardwareBreakpoints () virtual
Reimplemented in lldb_private::NativeRegisterContextDBReg.
Definition at line 248 of file NativeRegisterContext.cpp.
References lldb_private::Status::FromErrorString().
ClearAllHardwareWatchpoints()
Status NativeRegisterContext::ClearAllHardwareWatchpoints () virtual
Reimplemented in lldb_private::NativeRegisterContextDBReg, and lldb_private::NativeRegisterContextDBReg_x86.
Definition at line 278 of file NativeRegisterContext.cpp.
References lldb_private::Status::FromErrorString().
ClearHardwareBreakpoint()
bool NativeRegisterContext::ClearHardwareBreakpoint (uint32_t hw_idx) virtual
Reimplemented in lldb_private::NativeRegisterContextDBReg.
Definition at line 252 of file NativeRegisterContext.cpp.
ClearHardwareWatchpoint()
bool NativeRegisterContext::ClearHardwareWatchpoint (uint32_t hw_index) virtual
Reimplemented in lldb_private::NativeRegisterContextDBReg, and lldb_private::NativeRegisterContextDBReg_x86.
Definition at line 270 of file NativeRegisterContext.cpp.
ClearWatchpointHit()
Status NativeRegisterContext::ClearWatchpointHit (uint32_t hw_index) virtual
Reimplemented in lldb_private::NativeRegisterContextDBReg_x86.
Definition at line 274 of file NativeRegisterContext.cpp.
References lldb_private::Status::FromErrorString().
ConvertRegisterKindToRegisterNumber()
uint32_t NativeRegisterContext::ConvertRegisterKindToRegisterNumber (uint32_t kind, uint32_t num) const
Definition at line 416 of file NativeRegisterContext.cpp.
References GetRegisterCount(), GetRegisterInfoAtIndex(), lldb_private::RegisterInfo::kinds, lldb::kNumRegisterKinds, and LLDB_INVALID_REGNUM.
Referenced by lldb_private::NativeThreadWindows::DoResume(), GetExpeditedRegisters(), GetFlags(), GetFP(), GetPC(), GetRegisterInfo(), GetReturnAddress(), GetSP(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread(), SetFP(), SetPC(), and SetSP().
GetExpeditedRegisters()
std::vector< uint32_t > NativeRegisterContext::GetExpeditedRegisters (ExpeditedRegs expType) const virtual
Definition at line 432 of file NativeRegisterContext.cpp.
References ConvertRegisterKindToRegisterNumber(), lldb::eRegisterKindGeneric, lldb_private::Full, GetRegisterSet(), GetRegisterSetCount(), LLDB_INVALID_REGNUM, LLDB_REGNUM_GENERIC_FP, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_RA, LLDB_REGNUM_GENERIC_SP, and lldb_private::Minimal.
Referenced by GetRegistersAsJSON(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread().
GetFlags()
lldb::addr_t NativeRegisterContext::GetFlags (lldb::addr_t fail_value = 0)
Definition at line 179 of file NativeRegisterContext.cpp.
References ConvertRegisterKindToRegisterNumber(), lldb::eRegisterKindGeneric, LLDB_REGNUM_GENERIC_FLAGS, and ReadRegisterAsUnsigned().
GetFP()
lldb::addr_t NativeRegisterContext::GetFP (lldb::addr_t fail_value = LLDB_INVALID_ADDRESS)
Definition at line 161 of file NativeRegisterContext.cpp.
References ConvertRegisterKindToRegisterNumber(), lldb::eRegisterKindGeneric, LLDB_REGNUM_GENERIC_FP, and ReadRegisterAsUnsigned().
GetHardwareBreakHitIndex()
Status NativeRegisterContext::GetHardwareBreakHitIndex (uint32_t & bp_index, lldb::addr_t trap_addr) virtual
Reimplemented in lldb_private::NativeRegisterContextDBReg.
Definition at line 256 of file NativeRegisterContext.cpp.
References lldb_private::Status::FromErrorString(), and LLDB_INVALID_INDEX32.
GetPC()
lldb::addr_t NativeRegisterContext::GetPC (lldb::addr_t fail_value = LLDB_INVALID_ADDRESS)
Definition at line 123 of file NativeRegisterContext.cpp.
References ConvertRegisterKindToRegisterNumber(), lldb::eRegisterKindGeneric, lldb_private::GetLog(), LLDB_LOGF, LLDB_REGNUM_GENERIC_PC, ReadRegisterAsUnsigned(), and lldb_private::Thread.
Referenced by GetPCfromBreakpointLocation(), and lldb_private::process_linux::NativeProcessLinux::MonitorBreakpoint().
GetPCfromBreakpointLocation()
lldb::addr_t NativeRegisterContext::GetPCfromBreakpointLocation (lldb::addr_t fail_value = LLDB_INVALID_ADDRESS) virtual
Definition at line 139 of file NativeRegisterContext.cpp.
References GetPC().
Referenced by lldb_private::NativeProcessProtocol::FixupBreakpointPCAsNeeded().
GetRegisterCount()
virtual uint32_t lldb_private::NativeRegisterContext::GetRegisterCount () const pure virtual
Implemented in lldb_private::NativeRegisterContextRegisterInfo.
Referenced by ConvertRegisterKindToRegisterNumber(), and GetRegisterInfoByName().
GetRegisterInfo()
const RegisterInfo * NativeRegisterContext::GetRegisterInfo (uint32_t reg_kind, uint32_t reg_num)
Definition at line 81 of file NativeRegisterContext.cpp.
References ConvertRegisterKindToRegisterNumber(), GetRegisterInfoAtIndex(), and LLDB_INVALID_REGNUM.
Referenced by GetRegisterInfoByName(), and ReadRegisterCallback().
GetRegisterInfoAtIndex()
virtual const RegisterInfo * lldb_private::NativeRegisterContext::GetRegisterInfoAtIndex (uint32_t reg) const pure virtual
Implemented in lldb_private::NativeRegisterContextRegisterInfo.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::BuildTargetXml(), ConvertRegisterKindToRegisterNumber(), GetRegisterInfo(), GetRegisterInfoByName(), GetRegisterName(), GetRegistersAsJSON(), GetRegisterSetNameForRegisterAtIndex(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_g(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_P(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_p(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qRegisterInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread(), ReadRegisterAsUnsigned(), and WriteRegisterFromUnsigned().
GetRegisterInfoByName()
const RegisterInfo * NativeRegisterContext::GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx = 0)
Definition at line 53 of file NativeRegisterContext.cpp.
References lldb_private::RegisterInfo::alt_name, lldb::eRegisterKindGeneric, GetRegisterCount(), GetRegisterInfo(), GetRegisterInfoAtIndex(), LLDB_INVALID_REGNUM, lldb_private::RegisterInfo::name, and lldb_private::Args::StringToGenericRegister().
GetRegisterName()
const char * NativeRegisterContext::GetRegisterName (uint32_t reg)
Definition at line 89 of file NativeRegisterContext.cpp.
References GetRegisterInfoAtIndex(), and lldb_private::RegisterInfo::name.
GetRegisterSet()
virtual const RegisterSet * lldb_private::NativeRegisterContext::GetRegisterSet (uint32_t set_index) const pure virtual
Referenced by GetExpeditedRegisters(), and GetRegisterSetNameForRegisterAtIndex().
GetRegisterSetCount()
virtual uint32_t lldb_private::NativeRegisterContext::GetRegisterSetCount () const pure virtual
Referenced by GetExpeditedRegisters(), and GetRegisterSetNameForRegisterAtIndex().
GetRegisterSetNameForRegisterAtIndex()
const char * NativeRegisterContext::GetRegisterSetNameForRegisterAtIndex (uint32_t reg_index) const
Definition at line 96 of file NativeRegisterContext.cpp.
References lldb::eRegisterKindLLDB, GetRegisterInfoAtIndex(), GetRegisterSet(), GetRegisterSetCount(), lldb_private::RegisterInfo::kinds, lldb_private::RegisterSet::name, lldb_private::RegisterSet::num_registers, and lldb_private::RegisterSet::registers.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::BuildTargetXml(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qRegisterInfo().
GetReturnAddress()
lldb::addr_t NativeRegisterContext::GetReturnAddress (lldb::addr_t fail_value = LLDB_INVALID_ADDRESS)
Definition at line 173 of file NativeRegisterContext.cpp.
References ConvertRegisterKindToRegisterNumber(), lldb::eRegisterKindGeneric, LLDB_REGNUM_GENERIC_RA, and ReadRegisterAsUnsigned().
GetSP()
lldb::addr_t NativeRegisterContext::GetSP (lldb::addr_t fail_value = LLDB_INVALID_ADDRESS)
Definition at line 149 of file NativeRegisterContext.cpp.
References ConvertRegisterKindToRegisterNumber(), lldb::eRegisterKindGeneric, LLDB_REGNUM_GENERIC_SP, and ReadRegisterAsUnsigned().
GetThread()
virtual NativeThreadProtocol & lldb_private::NativeRegisterContext::GetThread () inline virtual
Definition at line 119 of file NativeRegisterContext.h.
References m_thread.
GetThreadID()
lldb::tid_t NativeRegisterContext::GetThreadID () const virtual
Definition at line 237 of file NativeRegisterContext.cpp.
References m_thread.
GetUserRegisterCount()
virtual uint32_t lldb_private::NativeRegisterContext::GetUserRegisterCount () const pure virtual
Implemented in lldb_private::NativeRegisterContextRegisterInfo.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::BuildTargetXml(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_g(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_P(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_p(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qRegisterInfo().
GetWatchpointAddress()
lldb::addr_t NativeRegisterContext::GetWatchpointAddress (uint32_t wp_index) virtual
Reimplemented in lldb_private::NativeRegisterContextDBReg, and lldb_private::NativeRegisterContextDBReg_x86.
Definition at line 299 of file NativeRegisterContext.cpp.
References LLDB_INVALID_ADDRESS.
Referenced by lldb_private::NativeProcessWindows::OnDebugException(), lldb_private::process_freebsd::NativeThreadFreeBSD::SetStoppedByWatchpoint(), and lldb_private::process_netbsd::NativeThreadNetBSD::SetStoppedByWatchpoint().
GetWatchpointHitAddress()
lldb::addr_t NativeRegisterContext::GetWatchpointHitAddress (uint32_t wp_index) virtual
Reimplemented in lldb_private::NativeRegisterContextDBReg.
Definition at line 303 of file NativeRegisterContext.cpp.
References LLDB_INVALID_ADDRESS.
Referenced by lldb_private::NativeProcessWindows::OnDebugException(), lldb_private::process_freebsd::NativeThreadFreeBSD::SetStoppedByWatchpoint(), and lldb_private::process_netbsd::NativeThreadNetBSD::SetStoppedByWatchpoint().
GetWatchpointHitIndex()
Status NativeRegisterContext::GetWatchpointHitIndex (uint32_t & wp_index, lldb::addr_t trap_addr) virtual
Reimplemented in lldb_private::NativeRegisterContextDBReg, and lldb_private::NativeRegisterContextDBReg_x86.
Definition at line 287 of file NativeRegisterContext.cpp.
References lldb_private::Status::FromErrorString(), and LLDB_INVALID_INDEX32.
Referenced by lldb_private::NativeProcessWindows::OnDebugException().
HardwareSingleStep()
bool NativeRegisterContext::HardwareSingleStep (bool enable) virtual
Definition at line 307 of file NativeRegisterContext.cpp.
IsWatchpointHit()
Status NativeRegisterContext::IsWatchpointHit (uint32_t wp_index, bool & is_hit) virtual
Reimplemented in lldb_private::NativeRegisterContextDBReg_x86.
Definition at line 282 of file NativeRegisterContext.cpp.
References lldb_private::Status::FromErrorString().
IsWatchpointVacant()
Status NativeRegisterContext::IsWatchpointVacant (uint32_t wp_index, bool & is_vacant) virtual
Reimplemented in lldb_private::NativeRegisterContextDBReg_x86.
Definition at line 293 of file NativeRegisterContext.cpp.
References lldb_private::Status::FromErrorString().
NumSupportedHardwareBreakpoints()
uint32_t NativeRegisterContext::NumSupportedHardwareBreakpoints () virtual
Reimplemented in lldb_private::NativeRegisterContextDBReg.
Definition at line 241 of file NativeRegisterContext.cpp.
Referenced by lldb_private::NativeProcessProtocol::GetHardwareDebugSupportInfo().
NumSupportedHardwareWatchpoints()
uint32_t NativeRegisterContext::NumSupportedHardwareWatchpoints () virtual
Reimplemented in lldb_private::NativeRegisterContextDBReg, and lldb_private::NativeRegisterContextDBReg_x86.
Definition at line 262 of file NativeRegisterContext.cpp.
Referenced by lldb_private::NativeProcessProtocol::GetHardwareDebugSupportInfo().
operator=()
const NativeRegisterContext & lldb_private::NativeRegisterContext::operator= (const NativeRegisterContext &) private delete
References NativeRegisterContext().
ReadAllRegisterValues()
virtual Status lldb_private::NativeRegisterContext::ReadAllRegisterValues (lldb::WritableDataBufferSP & data_sp) pure virtual
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_QSaveRegisterState(), and lldb_private::process_linux::NativeProcessLinux::Syscall().
ReadRegister()
virtual Status lldb_private::NativeRegisterContext::ReadRegister (const RegisterInfo * reg_info, RegisterValue & reg_value) pure virtual
Referenced by lldb_private::NativeRegisterContextDBReg_x86::ClearAllHardwareWatchpoints(), lldb_private::NativeRegisterContextDBReg_x86::ClearHardwareWatchpoint(), lldb_private::NativeRegisterContextDBReg_x86::ClearWatchpointHit(), GetRegistersAsJSON(), lldb_private::NativeRegisterContextDBReg_x86::GetWatchpointAddress(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_g(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_p(), lldb_private::NativeRegisterContextDBReg_x86::IsWatchpointHit(), lldb_private::NativeRegisterContextDBReg_x86::IsWatchpointVacant(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread(), ReadRegisterAsUnsigned(), ReadRegisterCallback(), lldb_private::NativeRegisterContextDBReg_x86::SetHardwareWatchpointWithIndex(), lldb_private::process_linux::NativeRegisterContextLinux::WriteRegisterRaw(), and WriteRegisterValueInHexFixedWidth().
ReadRegisterAsUnsigned() [1/2]
uint64_t NativeRegisterContext::ReadRegisterAsUnsigned (const RegisterInfo * reg_info, lldb::addr_t fail_value)
Definition at line 194 of file NativeRegisterContext.cpp.
References error(), lldb_private::RegisterValue::GetAsUInt64(), lldb_private::GetLog(), LLDB_LOGF, ReadRegister(), and lldb_private::Thread.
ReadRegisterAsUnsigned() [2/2]
lldb::addr_t NativeRegisterContext::ReadRegisterAsUnsigned (uint32_t reg, lldb::addr_t fail_value)
Definition at line 186 of file NativeRegisterContext.cpp.
References GetRegisterInfoAtIndex(), LLDB_INVALID_REGNUM, and ReadRegisterAsUnsigned().
Referenced by lldb_private::NativeThreadWindows::DoResume(), GetFlags(), GetFP(), GetPC(), GetReturnAddress(), GetSP(), ReadRegisterAsUnsigned(), and lldb_private::process_linux::NativeProcessLinux::Syscall().
ReadRegisterValueFromMemory()
Status NativeRegisterContext::ReadRegisterValueFromMemory (const lldb_private::RegisterInfo * reg_info, lldb::addr_t src_addr, size_t src_len, RegisterValue & reg_value) virtual
Definition at line 309 of file NativeRegisterContext.cpp.
References lldb_private::RegisterInfo::byte_size, lldb_private::RegisterInfo::data(), error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::NativeProcessProtocol::GetByteOrder(), m_thread, lldb_private::RegisterInfo::name, lldb_private::NativeProcessProtocol::ReadMemory(), and lldb_private::RegisterValue::SetFromMemoryData().
RegisterOffsetIsDynamic()
virtual bool lldb_private::NativeRegisterContext::RegisterOffsetIsDynamic () const inline virtual
Definition at line 124 of file NativeRegisterContext.h.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::BuildTargetXml(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qRegisterInfo().
SetFP()
Status NativeRegisterContext::SetFP (lldb::addr_t fp)
Definition at line 167 of file NativeRegisterContext.cpp.
References ConvertRegisterKindToRegisterNumber(), lldb::eRegisterKindGeneric, fp, LLDB_REGNUM_GENERIC_FP, and WriteRegisterFromUnsigned().
SetHardwareBreakpoint()
uint32_t NativeRegisterContext::SetHardwareBreakpoint (lldb::addr_t addr, size_t size) virtual
Reimplemented in lldb_private::NativeRegisterContextDBReg.
Definition at line 243 of file NativeRegisterContext.cpp.
References LLDB_INVALID_INDEX32.
Referenced by lldb_private::process_freebsd::NativeThreadFreeBSD::SetHardwareBreakpoint(), and lldb_private::process_netbsd::NativeThreadNetBSD::SetHardwareBreakpoint().
SetHardwareWatchpoint()
uint32_t NativeRegisterContext::SetHardwareWatchpoint (lldb::addr_t addr, size_t size, uint32_t watch_flags) virtual
Reimplemented in lldb_private::NativeRegisterContextDBReg, and lldb_private::NativeRegisterContextDBReg_x86.
Definition at line 264 of file NativeRegisterContext.cpp.
References LLDB_INVALID_INDEX32.
Referenced by lldb_private::process_freebsd::NativeThreadFreeBSD::SetWatchpoint(), and lldb_private::process_netbsd::NativeThreadNetBSD::SetWatchpoint().
SetPC()
Status NativeRegisterContext::SetPC (lldb::addr_t pc)
Definition at line 143 of file NativeRegisterContext.cpp.
References ConvertRegisterKindToRegisterNumber(), lldb::eRegisterKindGeneric, LLDB_REGNUM_GENERIC_PC, pc, and WriteRegisterFromUnsigned().
Referenced by lldb_private::NativeProcessProtocol::FixupBreakpointPCAsNeeded(), and lldb_private::process_linux::NativeProcessLinux::Syscall().
SetSP()
Status NativeRegisterContext::SetSP (lldb::addr_t sp)
Definition at line 155 of file NativeRegisterContext.cpp.
References ConvertRegisterKindToRegisterNumber(), lldb::eRegisterKindGeneric, LLDB_REGNUM_GENERIC_SP, sp, and WriteRegisterFromUnsigned().
WriteAllRegisterValues()
virtual Status lldb_private::NativeRegisterContext::WriteAllRegisterValues (const lldb::DataBufferSP & data_sp) pure virtual
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_QRestoreRegisterState(), and lldb_private::process_linux::NativeProcessLinux::Syscall().
WriteRegister()
virtual Status lldb_private::NativeRegisterContext::WriteRegister (const RegisterInfo * reg_info, const RegisterValue & reg_value) pure virtual
Referenced by lldb_private::NativeRegisterContextDBReg_x86::ClearAllHardwareWatchpoints(), lldb_private::NativeRegisterContextDBReg_x86::ClearHardwareWatchpoint(), lldb_private::NativeRegisterContextDBReg_x86::ClearWatchpointHit(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_P(), lldb_private::NativeRegisterContextDBReg_x86::SetHardwareWatchpointWithIndex(), and WriteRegisterFromUnsigned().
WriteRegisterFromUnsigned() [1/2]
Status NativeRegisterContext::WriteRegisterFromUnsigned (const RegisterInfo * reg_info, uint64_t uval)
Definition at line 224 of file NativeRegisterContext.cpp.
References lldb_private::RegisterInfo::byte_size, lldb_private::Status::FromErrorString(), lldb_private::RegisterValue::SetUInt(), and WriteRegister().
WriteRegisterFromUnsigned() [2/2]
Status NativeRegisterContext::WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
Definition at line 216 of file NativeRegisterContext.cpp.
References lldb_private::Status::FromErrorString(), GetRegisterInfoAtIndex(), LLDB_INVALID_REGNUM, and WriteRegisterFromUnsigned().
Referenced by lldb_private::NativeThreadWindows::DoResume(), SetFP(), SetPC(), SetSP(), and WriteRegisterFromUnsigned().
WriteRegisterValueToMemory()
Status NativeRegisterContext::WriteRegisterValueToMemory (const lldb_private::RegisterInfo * reg_info, lldb::addr_t dst_addr, size_t dst_len, const RegisterValue & reg_value) virtual
Definition at line 374 of file NativeRegisterContext.cpp.
References lldb_private::RegisterInfo::data(), error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::RegisterValue::GetAsMemoryData(), lldb_private::NativeProcessProtocol::GetByteOrder(), m_thread, and lldb_private::NativeProcessProtocol::WriteMemory().
Member Data Documentation
m_thread
NativeThreadProtocol& lldb_private::NativeRegisterContext::m_thread protected
Definition at line 176 of file NativeRegisterContext.h.
Referenced by lldb_private::process_linux::NativeRegisterContextLinux::DoReadRegisterValue(), lldb_private::process_netbsd::NativeRegisterContextNetBSD::DoRegisterSet(), lldb_private::process_linux::NativeRegisterContextLinux::DoWriteRegisterValue(), lldb_private::process_linux::NativeRegisterContextLinux::GetByteOrder(), lldb_private::process_freebsd::NativeRegisterContextFreeBSD::GetProcess(), lldb_private::process_netbsd::NativeRegisterContextNetBSD::GetProcess(), GetThread(), lldb_private::NativeRegisterContextWindows::GetThreadHandle(), GetThreadID(), NativeRegisterContext(), lldb_private::process_linux::NativeRegisterContextLinux::ReadFPR(), lldb_private::process_linux::NativeRegisterContextLinux::ReadGPR(), lldb_private::process_linux::NativeRegisterContextLinux::ReadRegisterSet(), ReadRegisterValueFromMemory(), lldb_private::process_linux::NativeRegisterContextLinux::WriteFPR(), lldb_private::process_linux::NativeRegisterContextLinux::WriteGPR(), lldb_private::process_linux::NativeRegisterContextLinux::WriteRegisterSet(), and WriteRegisterValueToMemory().
The documentation for this class was generated from the following files:
NativeRegisterContext.h
NativeRegisterContext.cpp