LLDB: DynamicLoaderMacOS Class Reference
DynamicLoaderMacOS Class Reference
#include <DynamicLoaderMacOS.h>
Public Member Functions
DynamicLoaderMacOS (lldb_private::Process *process)
~DynamicLoaderMacOS () override
bool ProcessDidExec () override
Called after attaching a process.
lldb_private::Status CanLoadImage () override
Ask if it is ok to try and load or unload an shared library (image).
bool GetSharedCacheInformation (lldb::addr_t &base_address, lldb_private::UUID &uuid, lldb_private::LazyBool &using_shared_cache, lldb_private::LazyBool &private_shared_cache, lldb_private::FileSpec &shared_cache_path) override
Get information about the shared cache for a process, if possible.
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::DynamicLoaderDarwin
DynamicLoaderDarwin (lldb_private::Process *process)
~DynamicLoaderDarwin () override
void DidAttach () override
Called after attaching a process.
void DidLaunch () override
Called after attaching a process.
lldb::ThreadPlanSP GetStepThroughTrampolinePlan (lldb_private::Thread &thread, bool stop_others) override
Provides a plan to step through the dynamic loader trampoline for the current state of thread.
void FindEquivalentSymbols (const lldb_private::Symbol *original_symbol, lldb_private::ModuleList &module_list, lldb_private::SymbolContextList &equivalent_symbols) override
Some dynamic loaders provide features where there are a group of symbols "equivalent to" a given symbol one of which will be chosen when the symbol is bound.
lldb::addr_t GetThreadLocalData (const lldb::ModuleSP module, const lldb::ThreadSP thread, lldb::addr_t tls_file_addr) override
Retrieves the per-module TLS block for a given thread.
bool AlwaysRelyOnEHUnwindInfo (lldb_private::SymbolContext &sym_ctx) override
Ask if the eh_frame information for the given SymbolContext should be relied on even when it's the first frame in a stack unwind.
std::optional< lldb_private::Address > GetStartAddress () override
Return the start address in the dynamic loader module.
Public Member Functions inherited from lldb_private::DynamicLoader
DynamicLoader (Process *process)
Construct with a process.
bool GetStopWhenImagesChange () const
Get whether the process should stop when images change.
void SetStopWhenImagesChange (bool stop)
Set whether the process should stop when images change.
virtual lldb::ModuleSP LoadModuleAtAddress (const lldb_private::FileSpec &file, lldb::addr_t link_map_addr, lldb::addr_t base_addr, bool base_addr_is_offset)
Locates or creates a module given by file and updates/loads the resulting module at the virtual base address base_addr.
virtual void CalculateDynamicSaveCoreRanges (lldb_private::Process &process, std::vector< lldb_private::MemoryRegionInfo > &ranges, llvm::function_ref< bool(const lldb_private::Thread &)> save_thread_predicate)
Returns a list of memory ranges that should be saved in the core file, specific for this dynamic loader.
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static lldb_private::DynamicLoader * CreateInstance (lldb_private::Process *process, bool force)
Static Public Member Functions inherited from lldb_private::DynamicLoader
static DynamicLoader * FindPlugin (Process *process, llvm::StringRef plugin_name)
Find a dynamic loader plugin for a given process.
static lldb::ModuleSP LoadBinaryWithUUIDAndAddress (Process *process, llvm::StringRef name, UUID uuid, lldb::addr_t value, bool value_is_offset, bool force_symbol_search, bool notify, bool set_address_in_target, bool allow_memory_image_last_resort)
Find/load a binary into lldb given a UUID and the address where it is loaded in memory, or a slide to be applied to the file address.
Protected Member Functions
void PutToLog (lldb_private::Log *log) const
void DoInitialImageFetch () override
bool NeedToDoInitialImageFetch () override
bool DidSetNotificationBreakpoint () override
bool SetDYLDHandoverBreakpoint (lldb::addr_t notification_address)
void ClearDYLDHandoverBreakpoint ()
void AddBinaries (const std::vector< lldb::addr_t > &load_addresses)
void DoClear () override
bool IsFullyInitialized () override
Return whether the dynamic loader is fully initialized and it's safe to call its APIs.
lldb::addr_t GetNotificationFuncAddrFromImageInfos ()
bool SetNotificationBreakpoint () override
void ClearNotificationBreakpoint () override
void UpdateImageInfosHeaderAndLoadCommands (ImageInfo::collection &image_infos, uint32_t infos_count, bool update_executable)
lldb::addr_t GetDyldLockVariableAddressFromModule (lldb_private::Module *module)
Protected Member Functions inherited from lldb_private::DynamicLoaderDarwin
void PrivateInitialize (lldb_private::Process *process)
void PrivateProcessStateChanged (lldb_private::Process *process, lldb::StateType state)
void Clear (bool clear_process)
void SetDYLDModule (lldb::ModuleSP &dyld_module_sp)
lldb::ModuleSP GetDYLDModule ()
void ClearDYLDModule ()
bool UpdateImageLoadAddress (lldb_private::Module *module, ImageInfo &info)
bool UnloadModuleSections (lldb_private::Module *module, ImageInfo &info)
lldb::ModuleSP FindTargetModuleForImageInfo (const ImageInfo &image_info, bool can_create, bool *did_create_ptr)
void UnloadImages (const std::vector< lldb::addr_t > &solib_addresses)
void UnloadAllImages ()
std::recursive_mutex & GetMutex () const
lldb::ModuleSP GetPThreadLibraryModule ()
lldb_private::Address GetPthreadSetSpecificAddress ()
bool JSONImageInformationIntoImageInfo (lldb_private::StructuredData::ObjectSP image_details, ImageInfo::collection &image_infos)
std::vector< std::pair< ImageInfo, lldb::ModuleSP > > PreloadModulesFromImageInfos (const ImageInfo::collection &image_infos)
void UpdateSpecialBinariesFromPreloadedModules (std::vector< std::pair< ImageInfo, lldb::ModuleSP > > &images)
bool UpdateDYLDImageInfoFromNewImageInfo (ImageInfo &image_info)
void AddExecutableModuleIfInImageInfos (ImageInfo::collection &image_infos)
bool AddModulesUsingImageInfos (ImageInfo::collection &image_infos)
bool AddModulesUsingPreloadedModules (std::vector< std::pair< ImageInfo, lldb::ModuleSP > > &images)
Protected Member Functions inherited from lldb_private::DynamicLoader
lldb::ModuleSP FindModuleViaTarget (const FileSpec &file)
Find a module in the target that matches the given file.
lldb::ModuleSP GetTargetExecutable ()
Checks to see if the target module has changed, updates the target accordingly and returns the target executable module.
virtual void UpdateLoadedSections (lldb::ModuleSP module, lldb::addr_t link_map_addr, lldb::addr_t base_addr, bool base_addr_is_offset)
Updates the load address of every allocatable section in module.
void UpdateLoadedSectionsCommon (lldb::ModuleSP module, lldb::addr_t base_addr, bool base_addr_is_offset)
virtual void UnloadSections (const lldb::ModuleSP module)
Removes the loaded sections from the target in module.
void UnloadSectionsCommon (const lldb::ModuleSP module)
const lldb_private::SectionList * GetSectionListFromModule (const lldb::ModuleSP module) const
int64_t ReadUnsignedIntWithSizeInBytes (lldb::addr_t addr, int size_in_bytes)
lldb::addr_t ReadPointer (lldb::addr_t addr)
void LoadOperatingSystemPlugin (bool flush)
Static Protected Member Functions
static bool NotifyBreakpointHit (void *baton, lldb_private::StoppointCallbackContext *context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id)
Static Protected Member Functions inherited from lldb_private::DynamicLoaderDarwin
static bool UseDYLDSPI (lldb_private::Process *process)
Protected Attributes
uint32_t m_image_infos_stop_id
lldb::user_id_t m_break_id
lldb::user_id_t m_dyld_handover_break_id
std::recursive_mutex m_mutex
lldb::addr_t m_maybe_image_infos_address
bool m_libsystem_fully_initalized
Protected Attributes inherited from lldb_private::DynamicLoaderDarwin
lldb::ModuleWP m_dyld_module_wp
lldb::ModuleWP m_libpthread_module_wp
lldb_private::Address m_pthread_getspecific_addr
ThreadIDToTLSMap m_tid_to_tls_map
ImageInfo::collection m_dyld_image_infos
uint32_t m_dyld_image_infos_stop_id
ImageInfo m_dyld
std::recursive_mutex m_mutex
Protected Attributes inherited from lldb_private::DynamicLoader
Process * m_process
The process that this dynamic loader plug-in is tracking.
Additional Inherited Members
Protected Types inherited from lldb_private::DynamicLoaderDarwin
typedef std::map< uint64_t, lldb::addr_t > PthreadKeyToTLSMap
typedef std::map< lldb::user_id_t, PthreadKeyToTLSMap > ThreadIDToTLSMap
Detailed Description
Definition at line 31 of file DynamicLoaderMacOS.h.
Constructor & Destructor Documentation
DynamicLoaderMacOS()
DynamicLoaderMacOS::DynamicLoaderMacOS (lldb_private::Process * process)
Definition at line 80 of file DynamicLoaderMacOS.cpp.
References lldb_private::DynamicLoaderDarwin::DynamicLoaderDarwin(), LLDB_INVALID_ADDRESS, LLDB_INVALID_BREAK_ID, m_break_id, m_dyld_handover_break_id, m_image_infos_stop_id, m_libsystem_fully_initalized, m_maybe_image_infos_address, m_mutex, and UINT32_MAX.
Referenced by CreateInstance(), and NotifyBreakpointHit().
~DynamicLoaderMacOS()
DynamicLoaderMacOS::~DynamicLoaderMacOS () override
Definition at line 88 of file DynamicLoaderMacOS.cpp.
References LLDB_BREAK_ID_IS_VALID, m_break_id, m_dyld_handover_break_id, and lldb_private::DynamicLoader::m_process.
Member Function Documentation
AddBinaries()
void DynamicLoaderMacOS::AddBinaries (const std::vector< lldb::addr_t > & load_addresses) protected
Definition at line 411 of file DynamicLoaderMacOS.cpp.
References lldb_private::DynamicLoaderDarwin::AddModulesUsingPreloadedModules(), lldb_private::DynamicLoader, lldb_private::GetLog(), lldb_private::DynamicLoaderDarwin::JSONImageInformationIntoImageInfo(), LLDB_LOGF, lldb_private::DynamicLoaderDarwin::m_dyld_image_infos_stop_id, lldb_private::DynamicLoader::m_process, lldb_private::DynamicLoaderDarwin::PreloadModulesFromImageInfos(), and lldb_private::DynamicLoaderDarwin::UpdateSpecialBinariesFromPreloadedModules().
Referenced by NotifyBreakpointHit().
CanLoadImage()
Status DynamicLoaderMacOS::CanLoadImage () override virtual
Ask if it is ok to try and load or unload an shared library (image).
The dynamic loader often knows when it would be ok to try and load or unload a shared library. This function call allows the dynamic loader plug-ins to check any current dyld state to make sure it is an ok time to load a shared library.
Returns
true if it is currently ok to try and load a shared library into the process, false otherwise.
Implements lldb_private::DynamicLoader.
Definition at line 635 of file DynamicLoaderMacOS.cpp.
References error(), lldb_private::Status::FromErrorString(), GetDyldLockVariableAddressFromModule(), lldb_private::Target::GetImages(), lldb_private::ModuleList::GetMutex(), lldb_private::ModuleList::GetSize(), LLDB_INVALID_ADDRESS, lldb_private::DynamicLoader::m_process, lldb_private::ModuleList::Modules(), and lldb_private::ModuleList::ModulesNoLocking().
ClearDYLDHandoverBreakpoint()
void DynamicLoaderMacOS::ClearDYLDHandoverBreakpoint () protected
Definition at line 602 of file DynamicLoaderMacOS.cpp.
References LLDB_BREAK_ID_IS_VALID, LLDB_INVALID_BREAK_ID, m_dyld_handover_break_id, and lldb_private::DynamicLoader::m_process.
Referenced by NotifyBreakpointHit().
ClearNotificationBreakpoint()
void DynamicLoaderMacOS::ClearNotificationBreakpoint () override protected virtual
Implements lldb_private::DynamicLoaderDarwin.
Definition at line 185 of file DynamicLoaderMacOS.cpp.
References LLDB_BREAK_ID_IS_VALID, LLDB_INVALID_BREAK_ID, m_break_id, and lldb_private::DynamicLoader::m_process.
Referenced by NotifyBreakpointHit().
CreateInstance()
DynamicLoader * DynamicLoaderMacOS::CreateInstance (lldb_private::Process * process, bool force) static
Definition at line 36 of file DynamicLoaderMacOS.cpp.
References lldb_private::DynamicLoader::DynamicLoader(), DynamicLoaderMacOS(), lldb_private::ObjectFile::eStrataUser, lldb_private::Target::GetArchitecture(), lldb_private::Target::GetExecutableModulePointer(), lldb_private::Module::GetObjectFile(), lldb_private::ObjectFile::GetStrata(), lldb_private::Process::GetTarget(), lldb_private::ArchSpec::GetTriple(), and lldb_private::DynamicLoaderDarwin::UseDYLDSPI().
Referenced by Initialize(), and Terminate().
DidSetNotificationBreakpoint()
bool DynamicLoaderMacOS::DidSetNotificationBreakpoint () override protected virtual
Implements lldb_private::DynamicLoaderDarwin.
Definition at line 181 of file DynamicLoaderMacOS.cpp.
References LLDB_BREAK_ID_IS_VALID, and m_break_id.
DoClear()
void DynamicLoaderMacOS::DoClear () override protected virtual
Implements lldb_private::DynamicLoaderDarwin.
Definition at line 141 of file DynamicLoaderMacOS.cpp.
References LLDB_BREAK_ID_IS_VALID, LLDB_INVALID_BREAK_ID, m_break_id, m_dyld_handover_break_id, m_libsystem_fully_initalized, m_mutex, and lldb_private::DynamicLoader::m_process.
DoInitialImageFetch()
void DynamicLoaderMacOS::DoInitialImageFetch () override protected virtual
Implements lldb_private::DynamicLoaderDarwin.
Definition at line 196 of file DynamicLoaderMacOS.cpp.
References lldb_private::DynamicLoaderDarwin::AddModulesUsingPreloadedModules(), lldb_private::DynamicLoader, lldb_private::GetLog(), lldb_private::DynamicLoaderDarwin::JSONImageInformationIntoImageInfo(), LLDB_LOGF, lldb_private::DynamicLoaderDarwin::m_dyld_image_infos_stop_id, m_maybe_image_infos_address, lldb_private::DynamicLoader::m_process, lldb_private::DynamicLoaderDarwin::PreloadModulesFromImageInfos(), lldb_private::DynamicLoaderDarwin::UnloadAllImages(), and lldb_private::DynamicLoaderDarwin::UpdateSpecialBinariesFromPreloadedModules().
Referenced by NotifyBreakpointHit().
GetDyldLockVariableAddressFromModule()
addr_t DynamicLoaderMacOS::GetDyldLockVariableAddressFromModule (lldb_private::Module * module) protected
Definition at line 609 of file DynamicLoaderMacOS.cpp.
References lldb_private::Symbol::GetAddressRef(), lldb_private::Address::GetOpcodeLoadAddress(), lldb_private::Module::GetSymtab(), lldb_private::Address::IsValid(), LLDB_INVALID_ADDRESS, lldb_private::DynamicLoader::m_process, and lldb_private::Symbol::ValueIsAddress().
Referenced by CanLoadImage().
GetNotificationFuncAddrFromImageInfos()
addr_t DynamicLoaderMacOS::GetNotificationFuncAddrFromImageInfos () protected
Definition at line 457 of file DynamicLoaderMacOS.cpp.
References error(), LLDB_INVALID_ADDRESS, and lldb_private::DynamicLoader::m_process.
Referenced by SetNotificationBreakpoint().
GetPluginDescriptionStatic()
llvm::StringRef DynamicLoaderMacOS::GetPluginDescriptionStatic () static
Definition at line 750 of file DynamicLoaderMacOS.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef DynamicLoaderMacOS::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 65 of file DynamicLoaderMacOS.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef DynamicLoaderMacOS::GetPluginNameStatic () inline static
Definition at line 42 of file DynamicLoaderMacOS.h.
Referenced by GetPluginName(), and Initialize().
GetSharedCacheInformation()
bool DynamicLoaderMacOS::GetSharedCacheInformation (lldb::addr_t & base_address, lldb_private::UUID & uuid, lldb_private::LazyBool & using_shared_cache, lldb_private::LazyBool & private_shared_cache, lldb_private::FileSpec & shared_cache_path) override virtual
Get information about the shared cache for a process, if possible.
On some systems (e.g. Darwin based systems), a set of libraries that are common to most processes may be put in a single region of memory and mapped into every process, this is called the shared cache, as a performance optimization.
Many targets will not have the concept of a shared cache.
Depending on how the DynamicLoader gathers information about the shared cache, it may be able to only return basic information - like the UUID of the cache - or it may be able to return additional information about the cache.
Parameters
[out] base_address The base address (load address) of the shared cache. LLDB_INVALID_ADDRESS if it cannot be determined.
[out] uuid The UUID of the shared cache, if it can be determined. If the UUID cannot be fetched, IsValid() will be false.
[out] using_shared_cache If this process is using a shared cache. If unknown, eLazyBoolCalculate is returned.
[out] private_shared_cache A LazyBool indicating whether this process is using a private shared cache. If this information cannot be fetched, eLazyBoolCalculate.
[out] shared_cache_path A FileSpec representing the shared cache path being run in the inferior process.
Returns
Returns false if this DynamicLoader cannot gather information about the shared cache / has no concept of a shared cache.
Reimplemented from lldb_private::DynamicLoader.
Definition at line 692 of file DynamicLoaderMacOS.cpp.
References lldb_private::UUID::Clear(), lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb_private::StructuredData::Dictionary::GetValueForKey(), lldb_private::StructuredData::Dictionary::HasKey(), LLDB_INVALID_ADDRESS, lldb_private::DynamicLoader::m_process, lldb_private::UUID::SetFromStringRef(), and lldb_private::FileSpec::SetPath().
Initialize()
void DynamicLoaderMacOS::Initialize () static
Definition at line 741 of file DynamicLoaderMacOS.cpp.
References CreateInstance(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Referenced by DynamicLoaderMacOSXDYLD::Initialize().
IsFullyInitialized()
bool DynamicLoaderMacOS::IsFullyInitialized () override protected virtual
Return whether the dynamic loader is fully initialized and it's safe to call its APIs.
On some systems (e.g. Darwin based systems), lldb will get notified by the dynamic loader before it itself finished initializing and it's not safe to call certain APIs or SPIs.
Reimplemented from lldb_private::DynamicLoader.
Definition at line 154 of file DynamicLoaderMacOS.cpp.
References m_libsystem_fully_initalized, and lldb_private::DynamicLoader::m_process.
NeedToDoInitialImageFetch()
bool DynamicLoaderMacOS::NeedToDoInitialImageFetch () override protected virtual
Implements lldb_private::DynamicLoaderDarwin.
Definition at line 229 of file DynamicLoaderMacOS.cpp.
NotifyBreakpointHit()
bool DynamicLoaderMacOS::NotifyBreakpointHit (void * baton, lldb_private::StoppointCallbackContext * context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id) static protected
Definition at line 235 of file DynamicLoaderMacOS.cpp.
References AddBinaries(), lldb_private::ModuleList::Clear(), ClearDYLDHandoverBreakpoint(), lldb_private::DynamicLoaderDarwin::ClearDYLDModule(), ClearNotificationBreakpoint(), lldb_private::Target::ClearSectionLoadList(), DoInitialImageFetch(), DynamicLoaderMacOS(), lldb::eBasicTypeVoid, lldb::eEncodingUint, error(), lldb_private::StoppointCallbackContext::exe_ctx_ref, lldb_private::Process::FixCodeAddress(), lldb_private::Process::GetABI(), lldb_private::ArchSpec::GetAddressByteSize(), lldb_private::Target::GetArchitecture(), lldb_private::Target::GetDebugger(), lldb_private::ScratchTypeSystemClang::GetForTarget(), lldb_private::UserID::GetID(), lldb_private::Process::GetImageInfoAddress(), lldb_private::Target::GetImages(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::Value::GetScalar(), lldb_private::ModuleList::GetSize(), lldb_private::Process::GetStopID(), lldb_private::DynamicLoader::GetStopWhenImagesChange(), lldb_private::Process::GetTarget(), lldb_private::ExecutionContext::GetThreadRef(), lldb_private::ArchSpec::GetTriple(), lldb_private::ValueList::GetValueAtIndex(), m_image_infos_stop_id, lldb_private::DynamicLoader::m_process, lldb_private::ValueList::PushValue(), lldb_private::Process::ReadPointerFromMemory(), lldb_private::Debugger::ReportWarning(), lldb_private::Value::Scalar, lldb_private::Value::SetCompilerType(), SetDYLDHandoverBreakpoint(), SetNotificationBreakpoint(), lldb_private::Value::SetValueType(), lldb_private::Scalar::UInt(), UINT32_MAX, lldb_private::Scalar::ULongLong(), lldb_private::DynamicLoaderDarwin::UnloadAllImages(), and lldb_private::DynamicLoaderDarwin::UnloadImages().
Referenced by SetDYLDHandoverBreakpoint(), and SetNotificationBreakpoint().
ProcessDidExec()
bool DynamicLoaderMacOS::ProcessDidExec () override virtual
Called after attaching a process.
Allow DynamicLoader plug-ins to execute some code after attaching to a process.
Reimplemented from lldb_private::DynamicLoader.
Definition at line 95 of file DynamicLoaderMacOS.cpp.
References lldb_private::DynamicLoaderDarwin::GetMutex(), lldb_private::Symbol::GetName(), LLDB_INVALID_ADDRESS, lldb_private::DynamicLoaderDarwin::m_libpthread_module_wp, m_libsystem_fully_initalized, m_maybe_image_infos_address, lldb_private::DynamicLoader::m_process, and lldb_private::DynamicLoaderDarwin::m_pthread_getspecific_addr.
PutToLog()
void DynamicLoaderMacOS::PutToLog (lldb_private::Log * log) const protected
Definition at line 440 of file DynamicLoaderMacOS.cpp.
SetDYLDHandoverBreakpoint()
bool DynamicLoaderMacOS::SetDYLDHandoverBreakpoint (lldb::addr_t notification_address) protected
Definition at line 588 of file DynamicLoaderMacOS.cpp.
References LLDB_INVALID_BREAK_ID, m_dyld_handover_break_id, lldb_private::DynamicLoader::m_process, and NotifyBreakpointHit().
Referenced by NotifyBreakpointHit().
SetNotificationBreakpoint()
bool DynamicLoaderMacOS::SetNotificationBreakpoint () override protected virtual
Implements lldb_private::DynamicLoaderDarwin.
Definition at line 516 of file DynamicLoaderMacOS.cpp.
References lldb_private::FileSpecList::Append(), lldb::eLanguageTypeUnknown, lldb_private::eLazyBoolNo, lldb_private::DynamicLoaderDarwin::GetDYLDModule(), lldb_private::Stoppoint::GetID(), GetNotificationFuncAddrFromImageInfos(), lldb_private::Breakpoint::HasResolvedLocations(), LLDB_INVALID_ADDRESS, LLDB_INVALID_BREAK_ID, m_break_id, lldb_private::DynamicLoader::m_process, NotifyBreakpointHit(), lldb_private::Breakpoint::SetBreakpointKind(), lldb_private::Breakpoint::SetCallback(), and lldb_private::Address::SetRawAddress().
Referenced by NotifyBreakpointHit().
Terminate()
void DynamicLoaderMacOS::Terminate () static
Definition at line 746 of file DynamicLoaderMacOS.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Referenced by DynamicLoaderMacOSXDYLD::Terminate().
UpdateImageInfosHeaderAndLoadCommands()
void DynamicLoaderMacOS::UpdateImageInfosHeaderAndLoadCommands (ImageInfo::collection & image_infos, uint32_t infos_count, bool update_executable) protected
Member Data Documentation
m_break_id
lldb::user_id_t DynamicLoaderMacOS::m_break_id protected
Definition at line 106 of file DynamicLoaderMacOS.h.
Referenced by ClearNotificationBreakpoint(), DidSetNotificationBreakpoint(), DoClear(), DynamicLoaderMacOS(), SetNotificationBreakpoint(), and ~DynamicLoaderMacOS().
m_dyld_handover_break_id
lldb::user_id_t DynamicLoaderMacOS::m_dyld_handover_break_id protected
Definition at line 107 of file DynamicLoaderMacOS.h.
Referenced by ClearDYLDHandoverBreakpoint(), DoClear(), DynamicLoaderMacOS(), SetDYLDHandoverBreakpoint(), and ~DynamicLoaderMacOS().
m_image_infos_stop_id
uint32_t DynamicLoaderMacOS::m_image_infos_stop_id protected
Definition at line 104 of file DynamicLoaderMacOS.h.
Referenced by DynamicLoaderMacOS(), and NotifyBreakpointHit().
m_libsystem_fully_initalized
bool DynamicLoaderMacOS::m_libsystem_fully_initalized protected
Definition at line 115 of file DynamicLoaderMacOS.h.
Referenced by DoClear(), DynamicLoaderMacOS(), IsFullyInitialized(), and ProcessDidExec().
m_maybe_image_infos_address
lldb::addr_t DynamicLoaderMacOS::m_maybe_image_infos_address protected
Definition at line 109 of file DynamicLoaderMacOS.h.
Referenced by DoInitialImageFetch(), DynamicLoaderMacOS(), and ProcessDidExec().
m_mutex
std::recursive_mutex DynamicLoaderMacOS::m_mutex mutable protected
Definition at line 108 of file DynamicLoaderMacOS.h.
Referenced by DoClear(), and DynamicLoaderMacOS().
The documentation for this class was generated from the following files:
DynamicLoaderMacOS.h
DynamicLoaderMacOS.cpp