LLDB: lldb_private::ExceptionRecord Class Reference
lldb_private::ExceptionRecord Class Reference
#include <ExceptionRecord.h>
Public Member Functions
ExceptionRecord (const EXCEPTION_RECORD &record, lldb::tid_t thread_id)
ExceptionRecord (const MINIDUMP_EXCEPTION &record, lldb::tid_t thread_id)
virtual ~ExceptionRecord ()
DWORD GetExceptionCode () const
bool IsContinuable () const
lldb::addr_t GetExceptionAddress () const
lldb::tid_t GetThreadID () const
const std::vector< ULONG_PTR > & GetExceptionArguments () const
Private Attributes
DWORD m_code
bool m_continuable
lldb::addr_t m_exception_addr
lldb::tid_t m_thread_id
std::vector< ULONG_PTR > m_arguments
Detailed Description
Definition at line 25 of file ExceptionRecord.h.
Constructor & Destructor Documentation
ExceptionRecord() [1/2]
lldb_private::ExceptionRecord::ExceptionRecord (const EXCEPTION_RECORD & record, lldb::tid_t thread_id) inline
Definition at line 27 of file ExceptionRecord.h.
References m_arguments, m_code, m_continuable, m_exception_addr, and m_thread_id.
ExceptionRecord() [2/2]
lldb_private::ExceptionRecord::ExceptionRecord (const MINIDUMP_EXCEPTION & record, lldb::tid_t thread_id) inline
Definition at line 46 of file ExceptionRecord.h.
References m_arguments, m_code, m_continuable, m_exception_addr, and m_thread_id.
~ExceptionRecord()
virtual lldb_private::ExceptionRecord::~ExceptionRecord () inline virtual
Definition at line 53 of file ExceptionRecord.h.
Member Function Documentation
GetExceptionAddress()
lldb::addr_t lldb_private::ExceptionRecord::GetExceptionAddress () const inline
Definition at line 58 of file ExceptionRecord.h.
References m_exception_addr.
Referenced by lldb_private::NativeProcessWindows::OnDebugException(), lldb_private::ProcessDebugger::OnDebugException(), and lldb_private::ProcessWindows::OnDebugException().
GetExceptionArguments()
const std::vector< ULONG_PTR > & lldb_private::ExceptionRecord::GetExceptionArguments () const inline
Definition at line 62 of file ExceptionRecord.h.
References m_arguments.
Referenced by lldb_private::NativeProcessWindows::OnDebugException().
GetExceptionCode()
DWORD lldb_private::ExceptionRecord::GetExceptionCode () const inline
Definition at line 56 of file ExceptionRecord.h.
References m_code.
Referenced by lldb_private::NativeProcessWindows::OnDebugException(), lldb_private::ProcessDebugger::OnDebugException(), and lldb_private::ProcessWindows::OnDebugException().
GetThreadID()
lldb::tid_t lldb_private::ExceptionRecord::GetThreadID () const inline
Definition at line 60 of file ExceptionRecord.h.
References m_thread_id.
Referenced by lldb_private::NativeProcessWindows::OnDebugException().
IsContinuable()
bool lldb_private::ExceptionRecord::IsContinuable () const inline
Definition at line 57 of file ExceptionRecord.h.
References m_continuable.
Member Data Documentation
m_arguments
std::vector<ULONG_PTR> lldb_private::ExceptionRecord::m_arguments private
Definition at line 69 of file ExceptionRecord.h.
Referenced by ExceptionRecord(), ExceptionRecord(), and GetExceptionArguments().
m_code
DWORD lldb_private::ExceptionRecord::m_code private
Definition at line 65 of file ExceptionRecord.h.
Referenced by ExceptionRecord(), ExceptionRecord(), and GetExceptionCode().
m_continuable
bool lldb_private::ExceptionRecord::m_continuable private
Definition at line 66 of file ExceptionRecord.h.
Referenced by ExceptionRecord(), ExceptionRecord(), and IsContinuable().
m_exception_addr
lldb::addr_t lldb_private::ExceptionRecord::m_exception_addr private
Definition at line 67 of file ExceptionRecord.h.
Referenced by ExceptionRecord(), ExceptionRecord(), and GetExceptionAddress().
m_thread_id
lldb::tid_t lldb_private::ExceptionRecord::m_thread_id private
Definition at line 68 of file ExceptionRecord.h.
Referenced by ExceptionRecord(), ExceptionRecord(), and GetThreadID().
The documentation for this class was generated from the following file:
ExceptionRecord.h