LLDB: lldb_private::SectionLoadHistory Class Reference
lldb_private::SectionLoadHistory Class Reference
#include <SectionLoadHistory.h>
Public Types
enum : unsigned { eStopIDNow = UINT32_MAX }
Public Member Functions
SectionLoadHistory ()=default
~SectionLoadHistory ()
SectionLoadList & GetCurrentSectionLoadList ()
bool IsEmpty () const
void Clear ()
uint32_t GetLastStopID () const
lldb::addr_t GetSectionLoadAddress (uint32_t stop_id, const lldb::SectionSP &section_sp)
bool ResolveLoadAddress (uint32_t stop_id, lldb::addr_t load_addr, Address &so_addr, bool allow_section_end=false)
bool SetSectionLoadAddress (uint32_t stop_id, const lldb::SectionSP &section_sp, lldb::addr_t load_addr, bool warn_multiple=false)
bool SetSectionUnloaded (uint32_t stop_id, const lldb::SectionSP &section_sp, lldb::addr_t load_addr)
size_t SetSectionUnloaded (uint32_t stop_id, const lldb::SectionSP &section_sp)
void Dump (Stream &s, Target *target)
Protected Types
typedef std::map< uint32_t, lldb::SectionLoadListSP > StopIDToSectionLoadList
Protected Member Functions
SectionLoadList * GetSectionLoadListForStopID (uint32_t stop_id, bool read_only)
Protected Attributes
StopIDToSectionLoadList m_stop_id_to_section_load_list
std::recursive_mutex m_mutex
Private Member Functions
SectionLoadHistory (const SectionLoadHistory &)=delete
const SectionLoadHistory & operator= (const SectionLoadHistory &)=delete
Detailed Description
Definition at line 19 of file SectionLoadHistory.h.
Member Typedef Documentation
StopIDToSectionLoadList
typedef std::map<uint32_t, lldb::SectionLoadListSP> lldb_private::SectionLoadHistory::StopIDToSectionLoadList protected
Definition at line 73 of file SectionLoadHistory.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : unsigned
Enumerator
eStopIDNow
Definition at line 21 of file SectionLoadHistory.h.
Constructor & Destructor Documentation
SectionLoadHistory() [1/2]
lldb_private::SectionLoadHistory::SectionLoadHistory () default
Referenced by operator=(), and SectionLoadHistory().
~SectionLoadHistory()
lldb_private::SectionLoadHistory::~SectionLoadHistory () inline
Definition at line 29 of file SectionLoadHistory.h.
References Clear().
SectionLoadHistory() [2/2]
lldb_private::SectionLoadHistory::SectionLoadHistory (const SectionLoadHistory &) private delete
References SectionLoadHistory().
Member Function Documentation
Clear()
void SectionLoadHistory::Clear ()
Definition at line 22 of file SectionLoadHistory.cpp.
References m_mutex, and m_stop_id_to_section_load_list.
Referenced by ~SectionLoadHistory().
Dump()
void SectionLoadHistory::Dump (Stream & s, Target * target)
Definition at line 157 of file SectionLoadHistory.cpp.
References lldb_private::Stream::EOL(), m_mutex, m_stop_id_to_section_load_list, and lldb_private::Stream::Printf().
GetCurrentSectionLoadList()
SectionLoadList & SectionLoadHistory::GetCurrentSectionLoadList ()
Definition at line 95 of file SectionLoadHistory.cpp.
References eStopIDNow, GetSectionLoadListForStopID(), and m_mutex.
GetLastStopID()
uint32_t SectionLoadHistory::GetLastStopID () const
Definition at line 27 of file SectionLoadHistory.cpp.
References m_mutex, and m_stop_id_to_section_load_list.
GetSectionLoadAddress()
addr_t SectionLoadHistory::GetSectionLoadAddress (uint32_t stop_id, const lldb::SectionSP & section_sp)
Definition at line 105 of file SectionLoadHistory.cpp.
References lldb_private::SectionLoadList::GetSectionLoadAddress(), GetSectionLoadListForStopID(), and m_mutex.
GetSectionLoadListForStopID()
SectionLoadList * SectionLoadHistory::GetSectionLoadListForStopID (uint32_t stop_id, bool read_only) protected
Definition at line 36 of file SectionLoadHistory.cpp.
References eStopIDNow, and m_stop_id_to_section_load_list.
Referenced by GetCurrentSectionLoadList(), GetSectionLoadAddress(), ResolveLoadAddress(), SetSectionLoadAddress(), SetSectionUnloaded(), and SetSectionUnloaded().
IsEmpty()
bool SectionLoadHistory::IsEmpty () const
Definition at line 17 of file SectionLoadHistory.cpp.
References m_mutex, and m_stop_id_to_section_load_list.
operator=()
const SectionLoadHistory & lldb_private::SectionLoadHistory::operator= (const SectionLoadHistory &) private delete
References SectionLoadHistory().
ResolveLoadAddress()
bool SectionLoadHistory::ResolveLoadAddress (uint32_t stop_id, lldb::addr_t load_addr, Address & so_addr, bool allow_section_end = false)
Definition at line 114 of file SectionLoadHistory.cpp.
References GetSectionLoadListForStopID(), m_mutex, and lldb_private::SectionLoadList::ResolveLoadAddress().
SetSectionLoadAddress()
bool SectionLoadHistory::SetSectionLoadAddress (uint32_t stop_id, const lldb::SectionSP & section_sp, lldb::addr_t load_addr, bool warn_multiple = false)
Definition at line 126 of file SectionLoadHistory.cpp.
References GetSectionLoadListForStopID(), m_mutex, and lldb_private::SectionLoadList::SetSectionLoadAddress().
SetSectionUnloaded() [1/2]
size_t SectionLoadHistory::SetSectionUnloaded (uint32_t stop_id, const lldb::SectionSP & section_sp)
Definition at line 138 of file SectionLoadHistory.cpp.
References GetSectionLoadListForStopID(), m_mutex, and lldb_private::SectionLoadList::SetSectionUnloaded().
SetSectionUnloaded() [2/2]
bool SectionLoadHistory::SetSectionUnloaded (uint32_t stop_id, const lldb::SectionSP & section_sp, lldb::addr_t load_addr)
Definition at line 147 of file SectionLoadHistory.cpp.
References GetSectionLoadListForStopID(), m_mutex, and lldb_private::SectionLoadList::SetSectionUnloaded().
Member Data Documentation
m_mutex
std::recursive_mutex lldb_private::SectionLoadHistory::m_mutex mutable protected
Definition at line 75 of file SectionLoadHistory.h.
Referenced by Clear(), Dump(), GetCurrentSectionLoadList(), GetLastStopID(), GetSectionLoadAddress(), IsEmpty(), ResolveLoadAddress(), SetSectionLoadAddress(), SetSectionUnloaded(), and SetSectionUnloaded().
m_stop_id_to_section_load_list
StopIDToSectionLoadList lldb_private::SectionLoadHistory::m_stop_id_to_section_load_list protected
Definition at line 74 of file SectionLoadHistory.h.
Referenced by Clear(), Dump(), GetLastStopID(), GetSectionLoadListForStopID(), and IsEmpty().
The documentation for this class was generated from the following files:
SectionLoadHistory.h
SectionLoadHistory.cpp