LLDB: lldb_private::DynamicLoaderDarwin Class Reference
lldb_private::DynamicLoaderDarwin Class Reference abstract
#include <DynamicLoaderDarwin.h>
Classes
struct ImageInfo
class Segment
Public Member Functions
DynamicLoaderDarwin (lldb_private::Process *process)
~DynamicLoaderDarwin () override
void DidAttach () override
Called after attaching a process.
void DidLaunch () override
Called after attaching a process.
lldb::ThreadPlanSP GetStepThroughTrampolinePlan (lldb_private::Thread &thread, bool stop_others) override
Provides a plan to step through the dynamic loader trampoline for the current state of thread.
void FindEquivalentSymbols (const lldb_private::Symbol *original_symbol, lldb_private::ModuleList &module_list, lldb_private::SymbolContextList &equivalent_symbols) override
Some dynamic loaders provide features where there are a group of symbols "equivalent to" a given symbol one of which will be chosen when the symbol is bound.
lldb::addr_t GetThreadLocalData (const lldb::ModuleSP module, const lldb::ThreadSP thread, lldb::addr_t tls_file_addr) override
Retrieves the per-module TLS block for a given thread.
bool AlwaysRelyOnEHUnwindInfo (lldb_private::SymbolContext &sym_ctx) override
Ask if the eh_frame information for the given SymbolContext should be relied on even when it's the first frame in a stack unwind.
virtual void DoInitialImageFetch ()=0
virtual bool NeedToDoInitialImageFetch ()=0
std::optional< lldb_private::Address > GetStartAddress () override
Return the start address in the dynamic loader module.
Public Member Functions inherited from lldb_private::DynamicLoader
DynamicLoader (Process *process)
Construct with a process.
virtual bool ProcessDidExec ()
Helper function that can be used to detect when a process has called exec and is now a new and different process.
bool GetStopWhenImagesChange () const
Get whether the process should stop when images change.
void SetStopWhenImagesChange (bool stop)
Set whether the process should stop when images change.
virtual Status CanLoadImage ()=0
Ask if it is ok to try and load or unload an shared library (image).
virtual lldb::ModuleSP LoadModuleAtAddress (const lldb_private::FileSpec &file, lldb::addr_t link_map_addr, lldb::addr_t base_addr, bool base_addr_is_offset)
Locates or creates a module given by file and updates/loads the resulting module at the virtual base address base_addr.
virtual bool GetSharedCacheInformation (lldb::addr_t &base_address, UUID &uuid, LazyBool &using_shared_cache, LazyBool &private_shared_cache, lldb_private::FileSpec &shared_cache_path)
Get information about the shared cache for a process, if possible.
virtual bool IsFullyInitialized ()
Return whether the dynamic loader is fully initialized and it's safe to call its APIs.
virtual void CalculateDynamicSaveCoreRanges (lldb_private::Process &process, std::vector< lldb_private::MemoryRegionInfo > &ranges, llvm::function_ref< bool(const lldb_private::Thread &)> save_thread_predicate)
Returns a list of memory ranges that should be saved in the core file, specific for this dynamic loader.
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
virtual llvm::StringRef GetPluginName ()=0
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Protected Types
typedef std::map< uint64_t, lldb::addr_t > PthreadKeyToTLSMap
typedef std::map< lldb::user_id_t, PthreadKeyToTLSMap > ThreadIDToTLSMap
Protected Member Functions
void PrivateInitialize (lldb_private::Process *process)
void PrivateProcessStateChanged (lldb_private::Process *process, lldb::StateType state)
void Clear (bool clear_process)
virtual void DoClear ()=0
void SetDYLDModule (lldb::ModuleSP &dyld_module_sp)
lldb::ModuleSP GetDYLDModule ()
void ClearDYLDModule ()
bool UpdateImageLoadAddress (lldb_private::Module *module, ImageInfo &info)
bool UnloadModuleSections (lldb_private::Module *module, ImageInfo &info)
lldb::ModuleSP FindTargetModuleForImageInfo (const ImageInfo &image_info, bool can_create, bool *did_create_ptr)
void UnloadImages (const std::vector< lldb::addr_t > &solib_addresses)
void UnloadAllImages ()
virtual bool SetNotificationBreakpoint ()=0
virtual void ClearNotificationBreakpoint ()=0
virtual bool DidSetNotificationBreakpoint ()=0
std::recursive_mutex & GetMutex () const
lldb::ModuleSP GetPThreadLibraryModule ()
lldb_private::Address GetPthreadSetSpecificAddress ()
bool JSONImageInformationIntoImageInfo (lldb_private::StructuredData::ObjectSP image_details, ImageInfo::collection &image_infos)
std::vector< std::pair< ImageInfo, lldb::ModuleSP > > PreloadModulesFromImageInfos (const ImageInfo::collection &image_infos)
void UpdateSpecialBinariesFromPreloadedModules (std::vector< std::pair< ImageInfo, lldb::ModuleSP > > &images)
bool UpdateDYLDImageInfoFromNewImageInfo (ImageInfo &image_info)
void AddExecutableModuleIfInImageInfos (ImageInfo::collection &image_infos)
bool AddModulesUsingImageInfos (ImageInfo::collection &image_infos)
bool AddModulesUsingPreloadedModules (std::vector< std::pair< ImageInfo, lldb::ModuleSP > > &images)
Protected Member Functions inherited from lldb_private::DynamicLoader
lldb::ModuleSP FindModuleViaTarget (const FileSpec &file)
Find a module in the target that matches the given file.
lldb::ModuleSP GetTargetExecutable ()
Checks to see if the target module has changed, updates the target accordingly and returns the target executable module.
virtual void UpdateLoadedSections (lldb::ModuleSP module, lldb::addr_t link_map_addr, lldb::addr_t base_addr, bool base_addr_is_offset)
Updates the load address of every allocatable section in module.
void UpdateLoadedSectionsCommon (lldb::ModuleSP module, lldb::addr_t base_addr, bool base_addr_is_offset)
virtual void UnloadSections (const lldb::ModuleSP module)
Removes the loaded sections from the target in module.
void UnloadSectionsCommon (const lldb::ModuleSP module)
const lldb_private::SectionList * GetSectionListFromModule (const lldb::ModuleSP module) const
int64_t ReadUnsignedIntWithSizeInBytes (lldb::addr_t addr, int size_in_bytes)
lldb::addr_t ReadPointer (lldb::addr_t addr)
void LoadOperatingSystemPlugin (bool flush)
Static Protected Member Functions
static bool UseDYLDSPI (lldb_private::Process *process)
Protected Attributes
lldb::ModuleWP m_dyld_module_wp
lldb::ModuleWP m_libpthread_module_wp
lldb_private::Address m_pthread_getspecific_addr
ThreadIDToTLSMap m_tid_to_tls_map
ImageInfo::collection m_dyld_image_infos
uint32_t m_dyld_image_infos_stop_id
ImageInfo m_dyld
std::recursive_mutex m_mutex
Protected Attributes inherited from lldb_private::DynamicLoader
Process * m_process
The process that this dynamic loader plug-in is tracking.
Private Member Functions
DynamicLoaderDarwin (const DynamicLoaderDarwin &)=delete
const DynamicLoaderDarwin & operator= (const DynamicLoaderDarwin &)=delete
Additional Inherited Members
Static Public Member Functions inherited from lldb_private::DynamicLoader
static DynamicLoader * FindPlugin (Process *process, llvm::StringRef plugin_name)
Find a dynamic loader plugin for a given process.
static lldb::ModuleSP LoadBinaryWithUUIDAndAddress (Process *process, llvm::StringRef name, UUID uuid, lldb::addr_t value, bool value_is_offset, bool force_symbol_search, bool notify, bool set_address_in_target, bool allow_memory_image_last_resort)
Find/load a binary into lldb given a UUID and the address where it is loaded in memory, or a slide to be applied to the file address.
Detailed Description
Definition at line 27 of file DynamicLoaderDarwin.h.
Member Typedef Documentation
PthreadKeyToTLSMap
typedef std::map<uint64_t, lldb::addr_t> lldb_private::DynamicLoaderDarwin::PthreadKeyToTLSMap protected
Definition at line 191 of file DynamicLoaderDarwin.h.
ThreadIDToTLSMap
typedef std::map<lldb::user_id_t, PthreadKeyToTLSMap> lldb_private::DynamicLoaderDarwin::ThreadIDToTLSMap protected
Definition at line 192 of file DynamicLoaderDarwin.h.
Constructor & Destructor Documentation
DynamicLoaderDarwin() [1/2]
DynamicLoaderDarwin::DynamicLoaderDarwin (lldb_private::Process * process)
Definition at line 54 of file DynamicLoaderDarwin.cpp.
References lldb_private::DynamicLoader::DynamicLoader(), m_dyld, m_dyld_image_infos, m_dyld_image_infos_stop_id, m_dyld_module_wp, m_libpthread_module_wp, m_mutex, m_pthread_getspecific_addr, m_tid_to_tls_map, and UINT32_MAX.
Referenced by DynamicLoaderDarwin(), DynamicLoaderMacOS::DynamicLoaderMacOS(), DynamicLoaderMacOSXDYLD::DynamicLoaderMacOSXDYLD(), and operator=().
~DynamicLoaderDarwin()
DynamicLoaderDarwin::~DynamicLoaderDarwin () override default
DynamicLoaderDarwin() [2/2]
lldb_private::DynamicLoaderDarwin::DynamicLoaderDarwin (const DynamicLoaderDarwin &) private delete
References DynamicLoaderDarwin().
Member Function Documentation
AddExecutableModuleIfInImageInfos()
void lldb_private::DynamicLoaderDarwin::AddExecutableModuleIfInImageInfos (ImageInfo::collection & image_infos) protected
AddModulesUsingImageInfos()
bool DynamicLoaderDarwin::AddModulesUsingImageInfos (ImageInfo::collection & image_infos) protected
Definition at line 711 of file DynamicLoaderDarwin.cpp.
References AddModulesUsingPreloadedModules(), m_mutex, and PreloadModulesFromImageInfos().
Referenced by DynamicLoaderMacOSXDYLD::AddModulesUsingImageInfosAddress().
AddModulesUsingPreloadedModules()
bool DynamicLoaderDarwin::AddModulesUsingPreloadedModules (std::vector< std::pair< ImageInfo, lldb::ModuleSP > > & images) protected
Definition at line 718 of file DynamicLoaderDarwin.cpp.
References lldb_private::ModuleList::Append(), lldb_private::ModuleList::AppendIfNeeded(), lldb_private::DynamicLoader, lldb_private::ModuleList::FindFirstModule(), lldb_private::SectionList::FindSectionByName(), lldb_private::ObjectFile::GetByteSize(), lldb_private::ObjectFile::GetFileOffset(), lldb_private::Section::GetFileOffset(), lldb_private::ObjectFile::GetFileSpec(), lldb_private::Target::GetImages(), lldb_private::GetLog(), lldb_private::ModuleSpec::GetObjectName(), lldb_private::Target::GetOrCreateModule(), lldb_private::ObjectFile::GetSectionList(), lldb_private::ModuleList::GetSize(), lldb_private::ArchSpec::GetTriple(), LLDB_LOG_ERROR, LLDB_LOGF, lldb_private::ModuleList::LogUUIDAndPaths(), m_dyld_image_infos, m_mutex, lldb_private::DynamicLoader::m_process, lldb_private::ModuleSpec::SetObjectOffset(), lldb_private::ModuleSpec::SetObjectSize(), and UpdateImageLoadAddress().
Referenced by DynamicLoaderMacOS::AddBinaries(), AddModulesUsingImageInfos(), DynamicLoaderMacOSXDYLD::AddModulesUsingImageInfosAddress(), and DynamicLoaderMacOS::DoInitialImageFetch().
AlwaysRelyOnEHUnwindInfo()
bool DynamicLoaderDarwin::AlwaysRelyOnEHUnwindInfo (lldb_private::SymbolContext & sym_ctx) override virtual
Ask if the eh_frame information for the given SymbolContext should be relied on even when it's the first frame in a stack unwind.
The CFI instructions from the eh_frame section are normally only valid at call sites – places where a program could throw an exception and need to unwind out. But some Modules may be known to the system as having reliable eh_frame information at all call sites. This would be the case if the Module's contents are largely hand-written assembly with hand-written eh_frame information. Normally when unwinding from a function at the beginning of a stack unwind lldb will examine the assembly instructions to understand how the stack frame is set up and where saved registers are stored. But with hand-written assembly this is not reliable enough – we need to consult those function's hand-written eh_frame information.
Returns
True if the symbol context should use eh_frame instructions unconditionally when unwinding from this frame. Else false, the normal lldb unwind behavior of only using eh_frame when the function appears in the middle of the stack.
Reimplemented from lldb_private::DynamicLoader.
Definition at line 831 of file DynamicLoaderDarwin.cpp.
References lldb_private::SymbolContext::function, lldb_private::ObjCLanguageRuntime::Get(), lldb_private::Function::GetAddress(), lldb_private::Symbol::GetAddressRef(), lldb_private::Address::GetModule(), lldb_private::ObjCLanguageRuntime::IsModuleObjCLibrary(), lldb_private::DynamicLoader::m_process, and lldb_private::SymbolContext::symbol.
Clear()
void DynamicLoaderDarwin::Clear (bool clear_process) protected
Definition at line 83 of file DynamicLoaderDarwin.cpp.
References m_dyld, m_dyld_image_infos, m_dyld_image_infos_stop_id, m_mutex, lldb_private::DynamicLoader::m_process, and UINT32_MAX.
Referenced by PrivateInitialize(), and PrivateProcessStateChanged().
ClearDYLDModule()
void DynamicLoaderDarwin::ClearDYLDModule () protected
Definition at line 683 of file DynamicLoaderDarwin.cpp.
References m_dyld_module_wp.
Referenced by DynamicLoaderMacOS::NotifyBreakpointHit().
ClearNotificationBreakpoint()
virtual void lldb_private::DynamicLoaderDarwin::ClearNotificationBreakpoint () protected pure virtual
Implemented in DynamicLoaderMacOS, and DynamicLoaderMacOSXDYLD.
DidAttach()
void DynamicLoaderDarwin::DidAttach () override virtual
Called after attaching a process.
Allow DynamicLoader plug-ins to execute some code after attaching to a process.
Implements lldb_private::DynamicLoader.
Definition at line 66 of file DynamicLoaderDarwin.cpp.
References DoInitialImageFetch(), lldb_private::DynamicLoader::m_process, PrivateInitialize(), and SetNotificationBreakpoint().
DidLaunch()
void DynamicLoaderDarwin::DidLaunch () override virtual
Called after attaching a process.
Allow DynamicLoader plug-ins to execute some code after attaching to a process.
Implements lldb_private::DynamicLoader.
Definition at line 76 of file DynamicLoaderDarwin.cpp.
References DoInitialImageFetch(), lldb_private::DynamicLoader::m_process, PrivateInitialize(), and SetNotificationBreakpoint().
DidSetNotificationBreakpoint()
virtual bool lldb_private::DynamicLoaderDarwin::DidSetNotificationBreakpoint () protected pure virtual
Implemented in DynamicLoaderMacOS, and DynamicLoaderMacOSXDYLD.
Referenced by PrivateProcessStateChanged().
DoClear()
virtual void lldb_private::DynamicLoaderDarwin::DoClear () protected pure virtual
Implemented in DynamicLoaderMacOS, and DynamicLoaderMacOSXDYLD.
DoInitialImageFetch()
virtual void lldb_private::DynamicLoaderDarwin::DoInitialImageFetch () pure virtual
Implemented in DynamicLoaderMacOS, and DynamicLoaderMacOSXDYLD.
Referenced by DidAttach(), DidLaunch(), and PrivateProcessStateChanged().
FindEquivalentSymbols()
void DynamicLoaderDarwin::FindEquivalentSymbols (const lldb_private::Symbol * original_symbol, lldb_private::ModuleList & module_list, lldb_private::SymbolContextList & equivalent_symbols) override virtual
Some dynamic loaders provide features where there are a group of symbols "equivalent to" a given symbol one of which will be chosen when the symbol is bound.
If you want to set a breakpoint on one of these symbols, you really need to set it on all the equivalent symbols.
Parameters
[in] original_symbol The symbol for which we are finding equivalences.
[in] module_list The set of modules in which to search.
[out] equivalent_symbols The equivalent symbol list - any equivalent symbols found are appended to this list.
Reimplemented from lldb_private::DynamicLoader.
Definition at line 1096 of file DynamicLoaderDarwin.cpp.
References lldb_private::Mangled::ePreferMangled, lldb::eSymbolTypeCode, lldb_private::ModuleList::FindSymbolsMatchingRegExAndType(), lldb_private::ConstString::GetCString(), lldb_private::Symbol::GetMangled(), and lldb_private::Mangled::GetName().
FindTargetModuleForImageInfo()
ModuleSP DynamicLoaderDarwin::FindTargetModuleForImageInfo (const ImageInfo & image_info, bool can_create, bool * did_create_ptr) protected
Definition at line 92 of file DynamicLoaderDarwin.cpp.
References lldb_private::DynamicLoaderDarwin::ImageInfo::address, lldb_private::DynamicLoader, lldb_private::DynamicLoaderDarwin::ImageInfo::file_spec, lldb_private::ModuleList::FindFirstModule(), lldb_private::ModuleSpec::GetArchitecture(), lldb_private::Target::GetArchitecture(), lldb_private::SharedCacheImageInfo::GetExtractor(), lldb_private::ModuleSpec::GetFileSpec(), lldb_private::ModuleList::GetGlobalModuleListProperties(), lldb_private::Target::GetImages(), lldb_private::GetLog(), lldb_private::Target::GetOrCreateModule(), lldb_private::FileSpec::GetPathAsConstString(), lldb_private::ModuleListProperties::GetSharedCacheBinaryLoading(), lldb_private::DynamicLoader::GetSharedCacheInformation(), lldb_private::ArchSpec::GetTriple(), lldb_private::ModuleSpec::GetUUID(), lldb_private::SharedCacheImageInfo::GetUUID(), lldb_private::FileSystem::Instance(), lldb_private::UUID::IsValid(), LLDB_LOG_ERROR, lldb_private::DynamicLoader::m_process, and lldb_private::DynamicLoaderDarwin::ImageInfo::uuid.
Referenced by PreloadModulesFromImageInfos(), DynamicLoaderMacOSXDYLD::RemoveModulesUsingImageInfosAddress(), UpdateDYLDImageInfoFromNewImageInfo(), and DynamicLoaderMacOSXDYLD::UpdateImageInfosHeaderAndLoadCommands().
GetDYLDModule()
ModuleSP DynamicLoaderDarwin::GetDYLDModule () protected
Definition at line 678 of file DynamicLoaderDarwin.cpp.
References m_dyld_module_wp.
Referenced by GetStartAddress(), DynamicLoaderMacOSXDYLD::ReadDYLDInfoFromMemoryAndSetNotificationCallback(), DynamicLoaderMacOS::SetNotificationBreakpoint(), DynamicLoaderMacOSXDYLD::SetNotificationBreakpoint(), UnloadAllImages(), and DynamicLoaderMacOSXDYLD::UpdateImageInfosHeaderAndLoadCommands().
GetMutex()
std::recursive_mutex & lldb_private::DynamicLoaderDarwin::GetMutex () const inline protected
Definition at line 194 of file DynamicLoaderDarwin.h.
References m_mutex.
Referenced by DynamicLoaderMacOSXDYLD::AddModulesUsingImageInfosAddress(), DynamicLoaderMacOSXDYLD::AddrByteSize(), DynamicLoaderMacOSXDYLD::InitializeFromAllImageInfos(), DynamicLoaderMacOS::ProcessDidExec(), DynamicLoaderMacOSXDYLD::ProcessDidExec(), DynamicLoaderMacOSXDYLD::PutToLog(), DynamicLoaderMacOSXDYLD::ReadDYLDInfoFromMemoryAndSetNotificationCallback(), DynamicLoaderMacOSXDYLD::ReadImageInfos(), DynamicLoaderMacOSXDYLD::RemoveModulesUsingImageInfosAddress(), DynamicLoaderMacOSXDYLD::SetNotificationBreakpoint(), and DynamicLoaderMacOSXDYLD::UpdateImageInfosHeaderAndLoadCommands().
GetPThreadLibraryModule()
lldb::ModuleSP DynamicLoaderDarwin::GetPThreadLibraryModule () protected
Definition at line 1115 of file DynamicLoaderDarwin.cpp.
References lldb_private::ModuleSpec::GetFileSpec(), lldb_private::ModuleList::GetModuleAtIndex(), lldb_private::ModuleList::GetSize(), lldb_private::ModuleList::IsEmpty(), m_libpthread_module_wp, lldb_private::DynamicLoader::m_process, and lldb_private::FileSpec::SetFilename().
Referenced by GetPthreadSetSpecificAddress().
GetPthreadSetSpecificAddress()
Address DynamicLoaderDarwin::GetPthreadSetSpecificAddress () protected
Definition at line 1134 of file DynamicLoaderDarwin.cpp.
References lldb::eSymbolTypeCode, lldb_private::Symbol::GetAddress(), lldb_private::SymbolContextList::GetContextAtIndex(), GetPThreadLibraryModule(), m_pthread_getspecific_addr, and lldb_private::SymbolContext::symbol.
Referenced by GetThreadLocalData().
GetStartAddress()
std::optional< lldb_private::Address > DynamicLoaderDarwin::GetStartAddress () override virtual
Return the start address in the dynamic loader module.
This is the address the process will begin executing with process launch --stop-at-entry.
Reimplemented from lldb_private::DynamicLoader.
Definition at line 654 of file DynamicLoaderDarwin.cpp.
References lldb_private::DynamicLoader, lldb_private::Symbol::GetAddress(), GetDYLDModule(), lldb_private::GetLog(), and LLDB_LOGV.
GetStepThroughTrampolinePlan()
ThreadPlanSP DynamicLoaderDarwin::GetStepThroughTrampolinePlan (lldb_private::Thread & thread, bool stop_others) override virtual
Provides a plan to step through the dynamic loader trampoline for the current state of thread.
Parameters
[in] stop_others Whether the plan should be set to stop other threads.
Returns
A pointer to the plan (caller owned) or NULL if we are not at such a trampoline.
Implements lldb_private::DynamicLoader.
Definition at line 954 of file DynamicLoaderDarwin.cpp.
References lldb_private::Symbol::CalculateSymbolContextSymbol(), lldb_private::Mangled::ePreferMangled, error(), lldb::eSymbolTypeCode, lldb::eSymbolTypeReExported, lldb::eSymbolTypeResolver, lldb_private::eVoteNoOpinion, lldb_private::RegularExpression::Execute(), lldb_private::ModuleList::FindSymbolsWithNameAndType(), lldb_private::Symbol::GetAddress(), lldb_private::ConstString::GetCString(), lldb_private::Address::GetLoadAddress(), lldb_private::GetLog(), lldb_private::Symbol::GetMangled(), lldb_private::Mangled::GetName(), lldb_private::Symbol::GetName(), lldb_private::StackFrame::GetSymbolContext(), lldb_private::Symbol::GetType(), lldb_private::Symbol::IsIndirect(), lldb_private::Symbol::IsTrampoline(), lldb_private::Address::IsValid(), LLDB_LOG, LLDB_LOGF, lldb_private::Symbol::ResolveReExportedSymbol(), lldb_private::Step, and lldb_private::SymbolContext::symbol.
GetThreadLocalData()
lldb::addr_t DynamicLoaderDarwin::GetThreadLocalData (const lldb::ModuleSP module, const lldb::ThreadSP thread, lldb::addr_t tls_file_addr) override virtual
Retrieves the per-module TLS block for a given thread.
Parameters
[in] module The module to query TLS data for.
[in] thread The specific thread to query TLS data for.
Returns
If the given thread has TLS data allocated for the module, the address of the TLS block. Otherwise LLDB_INVALID_ADDRESS is returned.
Reimplemented from lldb_private::DynamicLoader.
Definition at line 1152 of file DynamicLoaderDarwin.cpp.
References lldb::eBasicTypeVoid, lldb::eExpressionCompleted, error(), lldb_private::DataExtractor::GetAddress(), lldb_private::ScratchTypeSystemClang::GetForTarget(), lldb_private::Address::GetLoadAddress(), GetPthreadSetSpecificAddress(), lldb_private::Address::IsValid(), LLDB_INVALID_ADDRESS, m_mutex, lldb_private::DynamicLoader::m_process, m_tid_to_tls_map, lldb_private::Target::ReadMemory(), and lldb_private::Target::ResolveLoadAddress().
JSONImageInformationIntoImageInfo()
bool DynamicLoaderDarwin::JSONImageInformationIntoImageInfo (lldb_private::StructuredData::ObjectSP image_details, ImageInfo::collection & image_infos) protected
Definition at line 386 of file DynamicLoaderDarwin.cpp.
References lldb_private::StructuredData::Array::GetItemAtIndex(), lldb_private::StructuredData::Array::GetSize(), lldb_private::StructuredData::Dictionary::GetValueForKey(), lldb_private::StructuredData::Dictionary::HasKey(), segment::name, segment::vmaddr, and segment::vmsize.
Referenced by DynamicLoaderMacOS::AddBinaries(), DynamicLoaderMacOSXDYLD::AddModulesUsingImageInfosAddress(), and DynamicLoaderMacOS::DoInitialImageFetch().
NeedToDoInitialImageFetch()
virtual bool lldb_private::DynamicLoaderDarwin::NeedToDoInitialImageFetch () pure virtual
Implemented in DynamicLoaderMacOS, and DynamicLoaderMacOSXDYLD.
Referenced by PrivateProcessStateChanged().
operator=()
const DynamicLoaderDarwin & lldb_private::DynamicLoaderDarwin::operator= (const DynamicLoaderDarwin &) private delete
References DynamicLoaderDarwin().
PreloadModulesFromImageInfos()
std::vector< std::pair< DynamicLoaderDarwin::ImageInfo, ModuleSP > > DynamicLoaderDarwin::PreloadModulesFromImageInfos (const ImageInfo::collection & image_infos) protected
Definition at line 686 of file DynamicLoaderDarwin.cpp.
References FindTargetModuleForImageInfo(), lldb_private::Debugger::GetThreadPool(), and lldb_private::DynamicLoader::m_process.
Referenced by DynamicLoaderMacOS::AddBinaries(), AddModulesUsingImageInfos(), DynamicLoaderMacOSXDYLD::AddModulesUsingImageInfosAddress(), and DynamicLoaderMacOS::DoInitialImageFetch().
PrivateInitialize()
void DynamicLoaderDarwin::PrivateInitialize (lldb_private::Process * process) protected
Definition at line 911 of file DynamicLoaderDarwin.cpp.
References Clear(), DEBUG_PRINTF, lldb_private::DynamicLoader::m_process, and lldb_private::StateAsCString().
Referenced by DidAttach(), and DidLaunch().
PrivateProcessStateChanged()
void DynamicLoaderDarwin::PrivateProcessStateChanged (lldb_private::Process * process, lldb::StateType state) protected
Definition at line 919 of file DynamicLoaderDarwin.cpp.
References Clear(), DEBUG_PRINTF, DidSetNotificationBreakpoint(), DoInitialImageFetch(), lldb::eStateAttaching, lldb::eStateConnected, lldb::eStateCrashed, lldb::eStateDetached, lldb::eStateExited, lldb::eStateInvalid, lldb::eStateLaunching, lldb::eStateRunning, lldb::eStateStepping, lldb::eStateStopped, lldb::eStateSuspended, lldb::eStateUnloaded, lldb_private::DynamicLoader::m_process, NeedToDoInitialImageFetch(), SetNotificationBreakpoint(), and lldb_private::StateAsCString().
SetDYLDModule()
void DynamicLoaderDarwin::SetDYLDModule (lldb::ModuleSP & dyld_module_sp) protected
Definition at line 674 of file DynamicLoaderDarwin.cpp.
References m_dyld_module_wp.
Referenced by DynamicLoaderMacOSXDYLD::ReadDYLDInfoFromMemoryAndSetNotificationCallback(), UpdateDYLDImageInfoFromNewImageInfo(), and UpdateSpecialBinariesFromPreloadedModules().
SetNotificationBreakpoint()
virtual bool lldb_private::DynamicLoaderDarwin::SetNotificationBreakpoint () protected pure virtual
Implemented in DynamicLoaderMacOS, and DynamicLoaderMacOSXDYLD.
Referenced by DidAttach(), DidLaunch(), and PrivateProcessStateChanged().
UnloadAllImages()
void DynamicLoaderDarwin::UnloadAllImages () protected
Definition at line 242 of file DynamicLoaderDarwin.cpp.
References lldb_private::ModuleList::Append(), lldb_private::DynamicLoader, GetDYLDModule(), lldb_private::Target::GetImages(), lldb_private::GetLog(), lldb_private::ModuleList::GetMutex(), lldb_private::ModuleList::GetSize(), lldb_private::ModuleList::LogUUIDAndPaths(), m_dyld_image_infos, m_dyld_image_infos_stop_id, lldb_private::DynamicLoader::m_process, lldb_private::ModuleList::Modules(), lldb_private::Log::PutCString(), lldb_private::ModuleList::Remove(), and lldb_private::DynamicLoader::UnloadSections().
Referenced by DynamicLoaderMacOS::DoInitialImageFetch(), and DynamicLoaderMacOS::NotifyBreakpointHit().
UnloadImages()
void DynamicLoaderDarwin::UnloadImages (const std::vector< lldb::addr_t > & solib_addresses) protected
Definition at line 194 of file DynamicLoaderDarwin.cpp.
References lldb_private::ModuleList::AppendIfNeeded(), lldb_private::DynamicLoader, lldb_private::GetLog(), lldb_private::Address::GetModule(), lldb_private::Address::GetOffset(), lldb_private::ModuleList::GetSize(), LLDB_LOGF, lldb_private::ModuleList::LogUUIDAndPaths(), m_dyld_image_infos, m_dyld_image_infos_stop_id, m_mutex, lldb_private::DynamicLoader::m_process, lldb_private::Log::PutCString(), lldb_private::Address::SetLoadAddress(), and lldb_private::DynamicLoader::UnloadSections().
Referenced by DynamicLoaderMacOS::NotifyBreakpointHit().
UnloadModuleSections()
bool DynamicLoaderDarwin::UnloadModuleSections (lldb_private::Module * module, ImageInfo & info) protected
Definition at line 351 of file DynamicLoaderDarwin.cpp.
References lldb_private::SectionList::FindSectionByName(), lldb_private::ObjectFile::GetFileSpec(), lldb_private::FileSpec::GetPath(), lldb_private::ObjectFile::GetSectionList(), lldb_private::DynamicLoader::m_process, lldb_private::Debugger::ReportWarning(), lldb_private::DynamicLoaderDarwin::ImageInfo::segments, and lldb_private::DynamicLoaderDarwin::ImageInfo::slide.
Referenced by DynamicLoaderMacOSXDYLD::RemoveModulesUsingImageInfosAddress().
UpdateDYLDImageInfoFromNewImageInfo()
bool DynamicLoaderDarwin::UpdateDYLDImageInfoFromNewImageInfo (ImageInfo & image_info) protected
Definition at line 637 of file DynamicLoaderDarwin.cpp.
References lldb_private::ModuleList::AppendIfNeeded(), FindTargetModuleForImageInfo(), lldb_private::Target::GetImages(), lldb_private::DynamicLoaderDarwin::ImageInfo::header, lldb_private::DynamicLoader::m_process, SetDYLDModule(), and UpdateImageLoadAddress().
Referenced by DynamicLoaderMacOSXDYLD::ReadDYLDInfoFromMemoryAndSetNotificationCallback().
UpdateImageLoadAddress()
bool DynamicLoaderDarwin::UpdateImageLoadAddress (lldb_private::Module * module, ImageInfo & info) protected
Definition at line 274 of file DynamicLoaderDarwin.cpp.
References lldb_private::SectionList::FindSectionByName(), lldb_private::ObjectFile::GetSectionList(), lldb_private::DynamicLoaderDarwin::ImageInfo::load_stop_id, lldb_private::DynamicLoader::m_process, lldb_private::DynamicLoaderDarwin::ImageInfo::segments, and lldb_private::DynamicLoaderDarwin::ImageInfo::slide.
Referenced by AddModulesUsingPreloadedModules(), DynamicLoaderMacOSXDYLD::SetNotificationBreakpoint(), UpdateDYLDImageInfoFromNewImageInfo(), DynamicLoaderMacOSXDYLD::UpdateImageInfosHeaderAndLoadCommands(), and UpdateSpecialBinariesFromPreloadedModules().
UpdateSpecialBinariesFromPreloadedModules()
void DynamicLoaderDarwin::UpdateSpecialBinariesFromPreloadedModules (std::vector< std::pair< ImageInfo, lldb::ModuleSP > > & images) protected
Definition at line 563 of file DynamicLoaderDarwin.cpp.
References lldb_private::ModuleList::AppendIfNeeded(), lldb_private::DynamicLoader, lldb_private::eLoadDependentsNo, lldb_private::Target::GetArchitecture(), lldb_private::Target::GetExecutableModule(), lldb_private::Target::GetExecutableModulePointer(), lldb_private::Target::GetImages(), lldb_private::GetLog(), lldb_private::ArchSpec::GetTriple(), LLDB_LOGF, lldb_private::DynamicLoader::m_process, lldb_private::Target::SetArchitecture(), SetDYLDModule(), lldb_private::Target::SetExecutableModule(), lldb_private::ArchSpec::SetTriple(), UINT32_MAX, and UpdateImageLoadAddress().
Referenced by DynamicLoaderMacOS::AddBinaries(), DynamicLoaderMacOSXDYLD::AddModulesUsingImageInfosAddress(), and DynamicLoaderMacOS::DoInitialImageFetch().
UseDYLDSPI()
bool DynamicLoaderDarwin::UseDYLDSPI (lldb_private::Process * process) static protected
Definition at line 1261 of file DynamicLoaderDarwin.cpp.
References lldb_private::DynamicLoader, lldb_private::Target::GetArchitecture(), lldb_private::Process::GetHostOSVersion(), lldb_private::GetLog(), lldb_private::Process::GetTarget(), lldb_private::ArchSpec::GetTriple(), lldb_private::Process::IsLiveDebugSession(), and LLDB_LOGF.
Referenced by DynamicLoaderMacOS::CreateInstance(), and DynamicLoaderMacOSXDYLD::CreateInstance().
Member Data Documentation
m_dyld
ImageInfo lldb_private::DynamicLoaderDarwin::m_dyld protected
Definition at line 244 of file DynamicLoaderDarwin.h.
Referenced by DynamicLoaderMacOSXDYLD::AddrByteSize(), Clear(), DynamicLoaderDarwin(), DynamicLoaderMacOSXDYLD::ProcessDidExec(), DynamicLoaderMacOSXDYLD::ReadDYLDInfoFromMemoryAndSetNotificationCallback(), DynamicLoaderMacOSXDYLD::ReadImageInfos(), DynamicLoaderMacOSXDYLD::SetNotificationBreakpoint(), and DynamicLoaderMacOSXDYLD::UpdateImageInfosHeaderAndLoadCommands().
m_dyld_image_infos
ImageInfo::collection lldb_private::DynamicLoaderDarwin::m_dyld_image_infos protected
Definition at line 241 of file DynamicLoaderDarwin.h.
Referenced by AddModulesUsingPreloadedModules(), Clear(), DynamicLoaderDarwin(), DynamicLoaderMacOSXDYLD::InitializeFromAllImageInfos(), DynamicLoaderMacOSXDYLD::PutToLog(), DynamicLoaderMacOSXDYLD::RemoveModulesUsingImageInfosAddress(), UnloadAllImages(), and UnloadImages().
m_dyld_image_infos_stop_id
uint32_t lldb_private::DynamicLoaderDarwin::m_dyld_image_infos_stop_id protected
Definition at line 242 of file DynamicLoaderDarwin.h.
Referenced by DynamicLoaderMacOS::AddBinaries(), DynamicLoaderMacOSXDYLD::AddModulesUsingImageInfosAddress(), Clear(), DynamicLoaderMacOS::DoInitialImageFetch(), DynamicLoaderDarwin(), DynamicLoaderMacOSXDYLD::InitializeFromAllImageInfos(), DynamicLoaderMacOSXDYLD::RemoveModulesUsingImageInfosAddress(), UnloadAllImages(), and UnloadImages().
m_dyld_module_wp
lldb::ModuleWP lldb_private::DynamicLoaderDarwin::m_dyld_module_wp protected
Definition at line 235 of file DynamicLoaderDarwin.h.
Referenced by ClearDYLDModule(), DynamicLoaderDarwin(), GetDYLDModule(), and SetDYLDModule().
m_libpthread_module_wp
lldb::ModuleWP lldb_private::DynamicLoaderDarwin::m_libpthread_module_wp protected
Definition at line 237 of file DynamicLoaderDarwin.h.
Referenced by DynamicLoaderDarwin(), GetPThreadLibraryModule(), DynamicLoaderMacOS::ProcessDidExec(), and DynamicLoaderMacOSXDYLD::ProcessDidExec().
m_mutex
std::recursive_mutex lldb_private::DynamicLoaderDarwin::m_mutex mutable protected
Definition at line 245 of file DynamicLoaderDarwin.h.
Referenced by AddModulesUsingImageInfos(), AddModulesUsingPreloadedModules(), Clear(), DynamicLoaderDarwin(), GetMutex(), GetThreadLocalData(), and UnloadImages().
m_pthread_getspecific_addr
lldb_private::Address lldb_private::DynamicLoaderDarwin::m_pthread_getspecific_addr protected
Definition at line 238 of file DynamicLoaderDarwin.h.
Referenced by DynamicLoaderDarwin(), GetPthreadSetSpecificAddress(), DynamicLoaderMacOS::ProcessDidExec(), and DynamicLoaderMacOSXDYLD::ProcessDidExec().
m_tid_to_tls_map
ThreadIDToTLSMap lldb_private::DynamicLoaderDarwin::m_tid_to_tls_map protected
Definition at line 239 of file DynamicLoaderDarwin.h.
Referenced by DynamicLoaderDarwin(), and GetThreadLocalData().
The documentation for this class was generated from the following files:
DynamicLoaderDarwin.h
DynamicLoaderDarwin.cpp