LLDB: lldb_private::LocalDebugDelegate Class Reference
lldb_private::LocalDebugDelegate Class Reference
#include <LocalDebugDelegate.h>
Public Member Functions
LocalDebugDelegate (lldb::ProcessWP process)
void OnExitProcess (uint32_t exit_code) override
void OnDebuggerConnected (lldb::addr_t image_base) override
ExceptionResult OnDebugException (bool first_chance, const ExceptionRecord &record) override
void OnCreateThread (const HostThread &thread) override
void OnExitThread (lldb::tid_t thread_id, uint32_t exit_code) override
void OnLoadDll (const lldb_private::ModuleSpec &module_spec, lldb::addr_t module_addr) override
void OnUnloadDll (lldb::addr_t module_addr) override
void OnDebugString (const std::string &message) override
void OnDebuggerError (const Status &error, uint32_t type) override
Public Member Functions inherited from lldb_private::IDebugDelegate
virtual ~IDebugDelegate ()
Private Member Functions
ProcessWindowsSP GetProcessPointer ()
Private Attributes
lldb::ProcessWP m_process
Detailed Description
Definition at line 41 of file LocalDebugDelegate.h.
Constructor & Destructor Documentation
LocalDebugDelegate()
LocalDebugDelegate::LocalDebugDelegate (lldb::ProcessWP process) explicit
Definition at line 15 of file LocalDebugDelegate.cpp.
References m_process.
Member Function Documentation
GetProcessPointer()
ProcessWindowsSP LocalDebugDelegate::GetProcessPointer () private
Definition at line 69 of file LocalDebugDelegate.cpp.
References m_process.
Referenced by OnCreateThread(), OnDebugException(), OnDebuggerConnected(), OnDebuggerError(), OnDebugString(), OnExitProcess(), OnExitThread(), OnLoadDll(), and OnUnloadDll().
OnCreateThread()
void LocalDebugDelegate::OnCreateThread (const HostThread & thread) override virtual
Implements lldb_private::IDebugDelegate.
Definition at line 37 of file LocalDebugDelegate.cpp.
References GetProcessPointer().
OnDebugException()
ExceptionResult LocalDebugDelegate::OnDebugException (bool first_chance, const ExceptionRecord & record) override virtual
Implements lldb_private::IDebugDelegate.
Definition at line 29 of file LocalDebugDelegate.cpp.
References GetProcessPointer(), and MaskException.
OnDebuggerConnected()
void LocalDebugDelegate::OnDebuggerConnected (lldb::addr_t image_base) override virtual
Implements lldb_private::IDebugDelegate.
Definition at line 23 of file LocalDebugDelegate.cpp.
References GetProcessPointer().
OnDebuggerError()
void LocalDebugDelegate::OnDebuggerError (const Status & error, uint32_t type) override virtual
Implements lldb_private::IDebugDelegate.
Definition at line 64 of file LocalDebugDelegate.cpp.
References error(), and GetProcessPointer().
OnDebugString()
void LocalDebugDelegate::OnDebugString (const std::string & message) override virtual
Implements lldb_private::IDebugDelegate.
Definition at line 59 of file LocalDebugDelegate.cpp.
References GetProcessPointer().
OnExitProcess()
void LocalDebugDelegate::OnExitProcess (uint32_t exit_code) override virtual
Implements lldb_private::IDebugDelegate.
Definition at line 18 of file LocalDebugDelegate.cpp.
References GetProcessPointer().
OnExitThread()
void LocalDebugDelegate::OnExitThread (lldb::tid_t thread_id, uint32_t exit_code) override virtual
Implements lldb_private::IDebugDelegate.
Definition at line 42 of file LocalDebugDelegate.cpp.
References GetProcessPointer().
OnLoadDll()
void LocalDebugDelegate::OnLoadDll (const lldb_private::ModuleSpec & module_spec, lldb::addr_t module_addr) override virtual
Implements lldb_private::IDebugDelegate.
Definition at line 48 of file LocalDebugDelegate.cpp.
References GetProcessPointer().
OnUnloadDll()
void LocalDebugDelegate::OnUnloadDll (lldb::addr_t module_addr) override virtual
Implements lldb_private::IDebugDelegate.
Definition at line 54 of file LocalDebugDelegate.cpp.
References GetProcessPointer().
Member Data Documentation
m_process
lldb::ProcessWP lldb_private::LocalDebugDelegate::m_process private
Definition at line 60 of file LocalDebugDelegate.h.
Referenced by GetProcessPointer(), and LocalDebugDelegate().
The documentation for this class was generated from the following files:
LocalDebugDelegate.h
LocalDebugDelegate.cpp