LLDB: lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorExtended Class Reference
lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorExtended Class Reference
Public Member Functions
ObjCLanguageRuntime::ClassDescriptorSP GetClassDescriptor (lldb::addr_t ptr) override
Public Member Functions inherited from lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted
bool IsPossibleTaggedPointer (lldb::addr_t ptr) override
ObjCLanguageRuntime::ClassDescriptorSP GetClassDescriptor (lldb::addr_t ptr) override
Public Member Functions inherited from lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2
~TaggedPointerVendorV2 () override=default
Public Member Functions inherited from lldb_private::ObjCLanguageRuntime::TaggedPointerVendor
virtual ~TaggedPointerVendor ()=default
Protected Types
typedef std::map< uint8_t, ObjCLanguageRuntime::ClassDescriptorSP > Cache
typedef Cache::iterator CacheIterator
Protected Types inherited from lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted
typedef std::map< uint8_t, ObjCLanguageRuntime::ClassDescriptorSP > Cache
typedef Cache::iterator CacheIterator
Protected Member Functions
TaggedPointerVendorExtended (AppleObjCRuntimeV2 &runtime, uint64_t objc_debug_taggedpointer_mask, uint64_t objc_debug_taggedpointer_ext_mask, uint32_t objc_debug_taggedpointer_slot_shift, uint32_t objc_debug_taggedpointer_ext_slot_shift, uint32_t objc_debug_taggedpointer_slot_mask, uint32_t objc_debug_taggedpointer_ext_slot_mask, uint32_t objc_debug_taggedpointer_payload_lshift, uint32_t objc_debug_taggedpointer_payload_rshift, uint32_t objc_debug_taggedpointer_ext_payload_lshift, uint32_t objc_debug_taggedpointer_ext_payload_rshift, lldb::addr_t objc_debug_taggedpointer_classes, lldb::addr_t objc_debug_taggedpointer_ext_classes)
bool IsPossibleExtendedTaggedPointer (lldb::addr_t ptr)
TaggedPointerVendorExtended (const TaggedPointerVendorExtended &)=delete
const TaggedPointerVendorExtended & operator= (const TaggedPointerVendorExtended &)=delete
Protected Member Functions inherited from lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted
TaggedPointerVendorRuntimeAssisted (AppleObjCRuntimeV2 &runtime, uint64_t objc_debug_taggedpointer_mask, uint32_t objc_debug_taggedpointer_slot_shift, uint32_t objc_debug_taggedpointer_slot_mask, uint32_t objc_debug_taggedpointer_payload_lshift, uint32_t objc_debug_taggedpointer_payload_rshift, lldb::addr_t objc_debug_taggedpointer_classes)
TaggedPointerVendorRuntimeAssisted (const TaggedPointerVendorRuntimeAssisted &)=delete
const TaggedPointerVendorRuntimeAssisted & operator= (const TaggedPointerVendorRuntimeAssisted &)=delete
Protected Member Functions inherited from lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2
TaggedPointerVendorV2 (AppleObjCRuntimeV2 &runtime)
Protected Member Functions inherited from lldb_private::ObjCLanguageRuntime::TaggedPointerVendor
TaggedPointerVendor ()=default
Protected Attributes
Cache m_ext_cache
uint64_t m_objc_debug_taggedpointer_ext_mask
uint32_t m_objc_debug_taggedpointer_ext_slot_shift
uint32_t m_objc_debug_taggedpointer_ext_slot_mask
uint32_t m_objc_debug_taggedpointer_ext_payload_lshift
uint32_t m_objc_debug_taggedpointer_ext_payload_rshift
lldb::addr_t m_objc_debug_taggedpointer_ext_classes
Protected Attributes inherited from lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted
Cache m_cache
uint64_t m_objc_debug_taggedpointer_mask
uint32_t m_objc_debug_taggedpointer_slot_shift
uint32_t m_objc_debug_taggedpointer_slot_mask
uint32_t m_objc_debug_taggedpointer_payload_lshift
uint32_t m_objc_debug_taggedpointer_payload_rshift
lldb::addr_t m_objc_debug_taggedpointer_classes
Protected Attributes inherited from lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2
AppleObjCRuntimeV2 & m_runtime
Friends
class AppleObjCRuntimeV2::TaggedPointerVendorV2
Additional Inherited Members
Static Public Member Functions inherited from lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2
static TaggedPointerVendorV2 * CreateInstance (AppleObjCRuntimeV2 &runtime, const lldb::ModuleSP &objc_module_sp)
Detailed Description
Definition at line 231 of file AppleObjCRuntimeV2.h.
Member Typedef Documentation
Cache
typedef std::map<uint8_t, ObjCLanguageRuntime::ClassDescriptorSP> lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorExtended::Cache protected
Definition at line 254 of file AppleObjCRuntimeV2.h.
CacheIterator
typedef Cache::iterator lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorExtended::CacheIterator protected
Definition at line 255 of file AppleObjCRuntimeV2.h.
Constructor & Destructor Documentation
TaggedPointerVendorExtended() [1/2]
AppleObjCRuntimeV2::TaggedPointerVendorExtended::TaggedPointerVendorExtended (AppleObjCRuntimeV2 & runtime, uint64_t objc_debug_taggedpointer_mask, uint64_t objc_debug_taggedpointer_ext_mask, uint32_t objc_debug_taggedpointer_slot_shift, uint32_t objc_debug_taggedpointer_ext_slot_shift, uint32_t objc_debug_taggedpointer_slot_mask, uint32_t objc_debug_taggedpointer_ext_slot_mask, uint32_t objc_debug_taggedpointer_payload_lshift, uint32_t objc_debug_taggedpointer_payload_rshift, uint32_t objc_debug_taggedpointer_ext_payload_lshift, uint32_t objc_debug_taggedpointer_ext_payload_rshift, lldb::addr_t objc_debug_taggedpointer_classes, lldb::addr_t objc_debug_taggedpointer_ext_classes) protected
Definition at line 3116 of file AppleObjCRuntimeV2.cpp.
Referenced by operator=(), and TaggedPointerVendorExtended().
TaggedPointerVendorExtended() [2/2]
lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorExtended::TaggedPointerVendorExtended (const TaggedPointerVendorExtended &) protected delete
References TaggedPointerVendorExtended().
Member Function Documentation
GetClassDescriptor()
ObjCLanguageRuntime::ClassDescriptorSP AppleObjCRuntimeV2::TaggedPointerVendorExtended::GetClassDescriptor (lldb::addr_t ptr) override virtual
Implements lldb_private::ObjCLanguageRuntime::TaggedPointerVendor.
Definition at line 3162 of file AppleObjCRuntimeV2.cpp.
References m_ext_cache, m_objc_debug_taggedpointer_ext_classes, m_objc_debug_taggedpointer_ext_mask, m_objc_debug_taggedpointer_ext_payload_lshift, m_objc_debug_taggedpointer_ext_payload_rshift, m_objc_debug_taggedpointer_ext_slot_mask, m_objc_debug_taggedpointer_ext_slot_shift, and lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted::TaggedPointerVendorRuntimeAssisted().
IsPossibleExtendedTaggedPointer()
bool AppleObjCRuntimeV2::TaggedPointerVendorExtended::IsPossibleExtendedTaggedPointer (lldb::addr_t ptr) protected
Definition at line 3149 of file AppleObjCRuntimeV2.cpp.
References lldb_private::AppleObjCRuntimeV2::AppleObjCRuntimeV2().
operator=()
const TaggedPointerVendorExtended & lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorExtended::operator= (const TaggedPointerVendorExtended &) protected delete
References TaggedPointerVendorExtended().
Friends And Related Symbol Documentation
AppleObjCRuntimeV2::TaggedPointerVendorV2
friend class AppleObjCRuntimeV2::TaggedPointerVendorV2 friend
Definition at line 264 of file AppleObjCRuntimeV2.h.
Member Data Documentation
m_ext_cache
Cache lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorExtended::m_ext_cache protected
Definition at line 256 of file AppleObjCRuntimeV2.h.
Referenced by GetClassDescriptor().
m_objc_debug_taggedpointer_ext_classes
lldb::addr_t lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorExtended::m_objc_debug_taggedpointer_ext_classes protected
Definition at line 262 of file AppleObjCRuntimeV2.h.
Referenced by GetClassDescriptor().
m_objc_debug_taggedpointer_ext_mask
uint64_t lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorExtended::m_objc_debug_taggedpointer_ext_mask protected
Definition at line 257 of file AppleObjCRuntimeV2.h.
Referenced by GetClassDescriptor().
m_objc_debug_taggedpointer_ext_payload_lshift
uint32_t lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorExtended::m_objc_debug_taggedpointer_ext_payload_lshift protected
Definition at line 260 of file AppleObjCRuntimeV2.h.
Referenced by GetClassDescriptor().
m_objc_debug_taggedpointer_ext_payload_rshift
uint32_t lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorExtended::m_objc_debug_taggedpointer_ext_payload_rshift protected
Definition at line 261 of file AppleObjCRuntimeV2.h.
Referenced by GetClassDescriptor().
m_objc_debug_taggedpointer_ext_slot_mask
uint32_t lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorExtended::m_objc_debug_taggedpointer_ext_slot_mask protected
Definition at line 259 of file AppleObjCRuntimeV2.h.
Referenced by GetClassDescriptor().
m_objc_debug_taggedpointer_ext_slot_shift
uint32_t lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorExtended::m_objc_debug_taggedpointer_ext_slot_shift protected
Definition at line 258 of file AppleObjCRuntimeV2.h.
Referenced by GetClassDescriptor().
The documentation for this class was generated from the following files:
AppleObjCRuntimeV2.h
AppleObjCRuntimeV2.cpp