LLDB: lldb_private::CPlusPlusNameParser::Bookmark Class Reference
lldb_private::CPlusPlusNameParser::Bookmark Class Reference
Public Member Functions
Bookmark (size_t &position)
Bookmark (const Bookmark &)=delete
Bookmark (Bookmark &&b)
Bookmark & operator= (Bookmark &&)=delete
Bookmark & operator= (const Bookmark &)=delete
void Remove ()
size_t GetSavedPosition ()
~Bookmark ()
Private Attributes
size_t & m_position
size_t m_position_value
bool m_restore = true
Detailed Description
Definition at line 90 of file CPlusPlusNameParser.h.
Constructor & Destructor Documentation
Bookmark() [1/3]
lldb_private::CPlusPlusNameParser::Bookmark::Bookmark (size_t & position) inline
Definition at line 92 of file CPlusPlusNameParser.h.
References m_position, and m_position_value.
Referenced by Bookmark(), Bookmark(), operator=(), and operator=().
Bookmark() [2/3]
lldb_private::CPlusPlusNameParser::Bookmark::Bookmark (const Bookmark &) delete
References Bookmark().
Bookmark() [3/3]
lldb_private::CPlusPlusNameParser::Bookmark::Bookmark (Bookmark && b) inline
Definition at line 95 of file CPlusPlusNameParser.h.
References Bookmark(), m_position, m_position_value, and m_restore.
~Bookmark()
lldb_private::CPlusPlusNameParser::Bookmark::~Bookmark () inline
Definition at line 105 of file CPlusPlusNameParser.h.
References m_position, m_position_value, and m_restore.
Member Function Documentation
GetSavedPosition()
size_t lldb_private::CPlusPlusNameParser::Bookmark::GetSavedPosition () inline
Definition at line 104 of file CPlusPlusNameParser.h.
References m_position_value.
Referenced by lldb_private::CPlusPlusNameParser::ParseFullNameImpl().
operator=() [1/2]
Bookmark & lldb_private::CPlusPlusNameParser::Bookmark::operator= (Bookmark &&) delete
References Bookmark().
operator=() [2/2]
Bookmark & lldb_private::CPlusPlusNameParser::Bookmark::operator= (const Bookmark &) delete
References Bookmark().
Remove()
void lldb_private::CPlusPlusNameParser::Bookmark::Remove () inline
Definition at line 103 of file CPlusPlusNameParser.h.
References m_restore.
Referenced by lldb_private::CPlusPlusNameParser::ConsumeAbiTag(), lldb_private::CPlusPlusNameParser::ConsumeAnonymousNamespace(), lldb_private::CPlusPlusNameParser::ConsumeBrackets(), lldb_private::CPlusPlusNameParser::ConsumeDecltype(), lldb_private::CPlusPlusNameParser::ConsumeLambda(), lldb_private::CPlusPlusNameParser::ConsumeOperator(), lldb_private::CPlusPlusNameParser::ConsumeTemplateArgs(), lldb_private::CPlusPlusNameParser::ConsumeTypename(), lldb_private::CPlusPlusNameParser::ParseFullNameImpl(), lldb_private::CPlusPlusNameParser::ParseFuncPtr(), and lldb_private::CPlusPlusNameParser::ParseFunctionImpl().
Member Data Documentation
m_position
size_t& lldb_private::CPlusPlusNameParser::Bookmark::m_position private
Definition at line 112 of file CPlusPlusNameParser.h.
Referenced by Bookmark(), Bookmark(), and ~Bookmark().
m_position_value
size_t lldb_private::CPlusPlusNameParser::Bookmark::m_position_value private
Definition at line 113 of file CPlusPlusNameParser.h.
Referenced by Bookmark(), Bookmark(), GetSavedPosition(), and ~Bookmark().
m_restore
bool lldb_private::CPlusPlusNameParser::Bookmark::m_restore = true private
Definition at line 114 of file CPlusPlusNameParser.h.
Referenced by Bookmark(), Remove(), and ~Bookmark().
The documentation for this class was generated from the following file:
CPlusPlusNameParser.h