LLDB: lldb::SBDeclaration Class Reference
lldb::SBDeclaration Class Reference
#include <SBDeclaration.h>
Public Member Functions
SBDeclaration ()
SBDeclaration (const lldb::SBDeclaration &rhs)
~SBDeclaration ()
const lldb::SBDeclaration & operator= (const lldb::SBDeclaration &rhs)
operator bool () const
bool IsValid () const
lldb::SBFileSpec GetFileSpec () const
uint32_t GetLine () const
uint32_t GetColumn () const
void SetFileSpec (lldb::SBFileSpec filespec)
void SetLine (uint32_t line)
void SetColumn (uint32_t column)
bool operator== (const lldb::SBDeclaration &rhs) const
bool operator!= (const lldb::SBDeclaration &rhs) const
bool GetDescription (lldb::SBStream &description)
Protected Member Functions
lldb_private::Declaration * get ()
Private Member Functions
const lldb_private::Declaration * operator-> () const
lldb_private::Declaration & ref ()
const lldb_private::Declaration & ref () const
SBDeclaration (const lldb_private::Declaration *lldb_object_ptr)
void SetDeclaration (const lldb_private::Declaration &lldb_object_ref)
Private Attributes
std::unique_ptr< lldb_private::Declaration > m_opaque_up
Friends
class SBValue
Detailed Description
Definition at line 18 of file SBDeclaration.h.
Constructor & Destructor Documentation
SBDeclaration() [1/3]
SBDeclaration::SBDeclaration ()
Definition at line 22 of file SBDeclaration.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by operator!=(), operator=(), operator==(), SBDeclaration(), and SBValue.
SBDeclaration() [2/3]
SBDeclaration::SBDeclaration (const lldb::SBDeclaration & rhs)
Definition at line 24 of file SBDeclaration.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBDeclaration().
~SBDeclaration()
SBDeclaration::~SBDeclaration () default
References get(), GetColumn(), GetDescription(), GetFileSpec(), GetLine(), IsValid(), operator!=(), operator=(), operator==(), SetColumn(), SetFileSpec(), and SetLine().
SBDeclaration() [3/3]
SBDeclaration::SBDeclaration (const lldb_private::Declaration * lldb_object_ptr) private
Definition at line 30 of file SBDeclaration.cpp.
References m_opaque_up.
Member Function Documentation
get()
lldb_private::Declaration * SBDeclaration::get () protected
Definition at line 164 of file SBDeclaration.cpp.
References m_opaque_up.
Referenced by ~SBDeclaration().
GetColumn()
uint32_t SBDeclaration::GetColumn () const
Definition at line 81 of file SBDeclaration.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by GetDescription(), and ~SBDeclaration().
GetDescription()
bool SBDeclaration::GetDescription (lldb::SBStream & description)
Definition at line 147 of file SBDeclaration.cpp.
References GetColumn(), GetLine(), LLDB_INSTRUMENT_VA, m_opaque_up, PATH_MAX, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
Referenced by ~SBDeclaration().
GetFileSpec()
SBFileSpec SBDeclaration::GetFileSpec () const
Definition at line 60 of file SBDeclaration.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBFileSpec::SetFileSpec().
Referenced by ~SBDeclaration().
GetLine()
uint32_t SBDeclaration::GetLine () const
Definition at line 70 of file SBDeclaration.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by GetDescription(), and ~SBDeclaration().
IsValid()
bool SBDeclaration::IsValid () const
Definition at line 50 of file SBDeclaration.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBDeclaration().
operator bool()
SBDeclaration::operator bool () const explicit
Definition at line 54 of file SBDeclaration.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
operator!=()
bool SBDeclaration::operator!= (const lldb::SBDeclaration & rhs) const
Definition at line 121 of file SBDeclaration.cpp.
References lldb_private::Declaration::Compare(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBDeclaration().
Referenced by ~SBDeclaration().
operator->()
const lldb_private::Declaration * SBDeclaration::operator-> () const private
Definition at line 133 of file SBDeclaration.cpp.
References m_opaque_up.
Referenced by SBValue.
operator=()
const SBDeclaration & SBDeclaration::operator= (const lldb::SBDeclaration & rhs)
Definition at line 35 of file SBDeclaration.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBDeclaration().
Referenced by ~SBDeclaration().
operator==()
bool SBDeclaration::operator== (const lldb::SBDeclaration & rhs) const
Definition at line 109 of file SBDeclaration.cpp.
References lldb_private::Declaration::Compare(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBDeclaration().
Referenced by ~SBDeclaration().
ref() [1/2]
lldb_private::Declaration & SBDeclaration::ref () private
Definition at line 137 of file SBDeclaration.cpp.
References m_opaque_up.
Referenced by SBValue, SetColumn(), SetDeclaration(), SetFileSpec(), and SetLine().
ref() [2/2]
const lldb_private::Declaration & SBDeclaration::ref () const private
Definition at line 143 of file SBDeclaration.cpp.
References m_opaque_up.
SetColumn()
void SBDeclaration::SetColumn (uint32_t column)
Definition at line 103 of file SBDeclaration.cpp.
References LLDB_INSTRUMENT_VA, ref(), and lldb_private::Declaration::SetColumn().
Referenced by ~SBDeclaration().
SetDeclaration()
void SBDeclaration::SetDeclaration (const lldb_private::Declaration & lldb_object_ref) private
Definition at line 43 of file SBDeclaration.cpp.
References ref().
Referenced by lldb::SBValue::GetDeclaration(), and SBValue.
SetFileSpec()
void SBDeclaration::SetFileSpec (lldb::SBFileSpec filespec)
Definition at line 89 of file SBDeclaration.cpp.
References lldb::SBFileSpec::IsValid(), LLDB_INSTRUMENT_VA, ref(), lldb::SBFileSpec::ref(), and lldb_private::Declaration::SetFile().
Referenced by ~SBDeclaration().
SetLine()
void SBDeclaration::SetLine (uint32_t line)
Definition at line 97 of file SBDeclaration.cpp.
References LLDB_INSTRUMENT_VA, ref(), and lldb_private::Declaration::SetLine().
Referenced by ~SBDeclaration().
Friends And Related Symbol Documentation
SBValue
friend class SBValue friend
Definition at line 54 of file SBDeclaration.h.
References operator->(), ref(), SBDeclaration(), SBValue, and SetDeclaration().
Referenced by SBValue.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::Declaration> lldb::SBDeclaration::m_opaque_up private
Definition at line 66 of file SBDeclaration.h.
Referenced by get(), GetColumn(), GetDescription(), GetFileSpec(), GetLine(), operator bool(), operator!=(), operator->(), operator=(), operator==(), ref(), ref(), SBDeclaration(), and SBDeclaration().
The documentation for this class was generated from the following files:
SBDeclaration.h
SBDeclaration.cpp