LLDB: lldb_private::ThreadPlanShouldStopHere Class Reference
lldb_private::ThreadPlanShouldStopHere Class Reference abstract
#include <ThreadPlanShouldStopHere.h>
Classes
struct ThreadPlanShouldStopHereCallbacks
Public Types
enum {
eNone = 0 , eAvoidInlines = (1 << 0) , eStepInAvoidNoDebug = (1 << 1) , eStepOutAvoidNoDebug = (1 << 2) ,
eStepOutPastThunks = (1 << 3)
}
Public Member Functions
ThreadPlanShouldStopHere (ThreadPlan *owner)
ThreadPlanShouldStopHere (ThreadPlan *owner, const ThreadPlanShouldStopHereCallbacks *callbacks, void *baton=nullptr)
virtual ~ThreadPlanShouldStopHere ()
void SetShouldStopHereCallbacks (const ThreadPlanShouldStopHereCallbacks *callbacks, void *baton)
void ClearShouldStopHereCallbacks ()
bool InvokeShouldStopHereCallback (lldb::FrameComparison operation, Status &status)
lldb::ThreadPlanSP CheckShouldStopHereAndQueueStepOut (lldb::FrameComparison operation, Status &status)
lldb_private::Flags & GetFlags ()
const lldb_private::Flags & GetFlags () const
Protected Member Functions
virtual lldb::ThreadPlanSP QueueStepOutFromHerePlan (Flags &flags, lldb::FrameComparison operation, Status &status)
virtual void SetFlagsToDefault ()=0
Static Protected Member Functions
static bool DefaultShouldStopHereCallback (ThreadPlan *current_plan, Flags &flags, lldb::FrameComparison operation, Status &status, void *baton)
static lldb::ThreadPlanSP DefaultStepFromHereCallback (ThreadPlan *current_plan, Flags &flags, lldb::FrameComparison operation, Status &status, void *baton)
Protected Attributes
ThreadPlanShouldStopHereCallbacks m_callbacks
void * m_baton
ThreadPlan * m_owner
lldb_private::Flags m_flags
Private Member Functions
ThreadPlanShouldStopHere (const ThreadPlanShouldStopHere &)=delete
const ThreadPlanShouldStopHere & operator= (const ThreadPlanShouldStopHere &)=delete
Detailed Description
Definition at line 34 of file ThreadPlanShouldStopHere.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
eNone
eAvoidInlines
eStepInAvoidNoDebug
eStepOutAvoidNoDebug
eStepOutPastThunks
Definition at line 58 of file ThreadPlanShouldStopHere.h.
Constructor & Destructor Documentation
ThreadPlanShouldStopHere() [1/3]
ThreadPlanShouldStopHere::ThreadPlanShouldStopHere (ThreadPlan * owner)
Definition at line 22 of file ThreadPlanShouldStopHere.cpp.
References DefaultShouldStopHereCallback(), DefaultStepFromHereCallback(), eNone, m_baton, m_callbacks, m_flags, m_owner, and ThreadPlanShouldStopHere().
Referenced by operator=(), ThreadPlanShouldStopHere(), ThreadPlanShouldStopHere(), ThreadPlanShouldStopHere(), lldb_private::ThreadPlanStepInRange::ThreadPlanStepInRange(), lldb_private::ThreadPlanStepOut::ThreadPlanStepOut(), lldb_private::ThreadPlanStepOut::ThreadPlanStepOut(), and lldb_private::ThreadPlanStepOverRange::ThreadPlanStepOverRange().
ThreadPlanShouldStopHere() [2/3]
ThreadPlanShouldStopHere::ThreadPlanShouldStopHere (ThreadPlan * owner, const ThreadPlanShouldStopHereCallbacks * callbacks, void * baton = nullptr)
Definition at line 31 of file ThreadPlanShouldStopHere.cpp.
References eNone, m_baton, m_callbacks, m_flags, m_owner, SetShouldStopHereCallbacks(), and ThreadPlanShouldStopHere().
~ThreadPlanShouldStopHere()
ThreadPlanShouldStopHere::~ThreadPlanShouldStopHere () virtual default
ThreadPlanShouldStopHere() [3/3]
lldb_private::ThreadPlanShouldStopHere::ThreadPlanShouldStopHere (const ThreadPlanShouldStopHere &) private delete
References ThreadPlanShouldStopHere().
Member Function Documentation
CheckShouldStopHereAndQueueStepOut()
lldb::ThreadPlanSP ThreadPlanShouldStopHere::CheckShouldStopHereAndQueueStepOut (lldb::FrameComparison operation, Status & status)
Definition at line 196 of file ThreadPlanShouldStopHere.cpp.
References InvokeShouldStopHereCallback(), m_flags, and QueueStepOutFromHerePlan().
Referenced by lldb_private::ThreadPlanStepInRange::ShouldStop(), and lldb_private::ThreadPlanStepOverRange::ShouldStop().
ClearShouldStopHereCallbacks()
void lldb_private::ThreadPlanShouldStopHere::ClearShouldStopHereCallbacks () inline
Definition at line 96 of file ThreadPlanShouldStopHere.h.
References m_callbacks.
Referenced by lldb_private::Thread::QueueThreadPlanForStepOutNoShouldStop(), and SetShouldStopHereCallbacks().
DefaultShouldStopHereCallback()
bool ThreadPlanShouldStopHere::DefaultShouldStopHereCallback (ThreadPlan * current_plan, Flags & flags, lldb::FrameComparison operation, Status & status, void * baton) static protected
Definition at line 60 of file ThreadPlanShouldStopHere.cpp.
References lldb::eFrameCompareOlder, lldb::eFrameCompareSameParent, lldb::eFrameCompareYounger, eStepInAvoidNoDebug, eStepOutAvoidNoDebug, eStepOutPastThunks, lldb_private::StackFrame::GetFunctionName(), lldb_private::GetLog(), lldb_private::Language::GetNameForLanguageType(), lldb_private::Thread::GetProcess(), lldb_private::Thread::GetStackFrameAtIndex(), lldb_private::StackFrame::GetSymbolContext(), lldb_private::ThreadPlan::GetThread(), lldb_private::StackFrame::HasDebugInformation(), lldb_private::LineEntry::line, lldb_private::SymbolContext::line_entry, LLDB_LOGF, lldb_private::Step, lldb_private::SymbolContext::symbol, and lldb_private::Flags::Test().
Referenced by lldb_private::ThreadPlanStepInRange::DefaultShouldStopHereCallback(), SetShouldStopHereCallbacks(), and ThreadPlanShouldStopHere().
DefaultStepFromHereCallback()
ThreadPlanSP ThreadPlanShouldStopHere::DefaultStepFromHereCallback (ThreadPlan * current_plan, Flags & flags, lldb::FrameComparison operation, Status & status, void * baton) static protected
Definition at line 115 of file ThreadPlanShouldStopHere.cpp.
References lldb_private::AddressRange::ContainsFileAddress(), lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb::eOnlyDuringStepping, eStepOutPastThunks, lldb_private::eVoteNo, lldb_private::eVoteNoOpinion, lldb_private::Symbol::GetAddress(), lldb_private::Symbol::GetByteSize(), lldb_private::StackFrame::GetFunctionName(), lldb_private::GetLog(), lldb_private::Language::GetNameForLanguageType(), lldb_private::Thread::GetProcess(), lldb_private::Thread::GetStackFrameAtIndex(), lldb_private::StackFrame::GetSymbolContext(), lldb_private::ThreadPlan::GetThread(), lldb_private::LineEntry::line, lldb_private::SymbolContext::line_entry, LLDB_LOGF, lldb_private::Thread::QueueThreadPlanForStepInRange(), lldb_private::Thread::QueueThreadPlanForStepOutNoShouldStop(), lldb_private::LineEntry::range, lldb_private::Address::Slide(), lldb_private::Step, lldb_private::SymbolContext::symbol, lldb_private::Flags::Test(), and lldb_private::Symbol::ValueIsAddress().
Referenced by SetShouldStopHereCallbacks(), and ThreadPlanShouldStopHere().
GetFlags() [1/2]
lldb_private::Flags & lldb_private::ThreadPlanShouldStopHere::GetFlags () inline
Definition at line 105 of file ThreadPlanShouldStopHere.h.
References m_flags.
Referenced by lldb_private::AppleThreadPlanStepThroughDirectDispatch::AppleThreadPlanStepThroughDirectDispatch(), lldb_private::AppleThreadPlanStepThroughDirectDispatch::SetFlagsToDefault(), lldb_private::ThreadPlanStepInRange::SetFlagsToDefault(), lldb_private::ThreadPlanStepOut::SetFlagsToDefault(), lldb_private::ThreadPlanStepOverRange::SetFlagsToDefault(), lldb_private::ThreadPlanStepInRange::SetupAvoidNoDebug(), lldb_private::ThreadPlanStepOut::SetupAvoidNoDebug(), and lldb_private::ThreadPlanStepOverRange::SetupAvoidNoDebug().
GetFlags() [2/2]
const lldb_private::Flags & lldb_private::ThreadPlanShouldStopHere::GetFlags () const inline
Definition at line 107 of file ThreadPlanShouldStopHere.h.
References m_flags.
InvokeShouldStopHereCallback()
bool ThreadPlanShouldStopHere::InvokeShouldStopHereCallback (lldb::FrameComparison operation, Status & status)
Definition at line 41 of file ThreadPlanShouldStopHere.cpp.
References lldb_private::GetLog(), LLDB_LOGF, m_baton, m_callbacks, m_flags, m_owner, and lldb_private::Step.
Referenced by CheckShouldStopHereAndQueueStepOut(), lldb_private::ThreadPlanStepOut::DoPlanExplainsStop(), lldb_private::AppleThreadPlanStepThroughDirectDispatch::ShouldStop(), and lldb_private::ThreadPlanStepOut::ShouldStop().
operator=()
const ThreadPlanShouldStopHere & lldb_private::ThreadPlanShouldStopHere::operator= (const ThreadPlanShouldStopHere &) private delete
References ThreadPlanShouldStopHere().
QueueStepOutFromHerePlan()
ThreadPlanSP ThreadPlanShouldStopHere::QueueStepOutFromHerePlan (lldb_private::Flags & flags, lldb::FrameComparison operation, Status & status) protected virtual
Definition at line 185 of file ThreadPlanShouldStopHere.cpp.
References m_baton, m_callbacks, and m_owner.
Referenced by CheckShouldStopHereAndQueueStepOut(), and lldb_private::ThreadPlanStepOut::ShouldStop().
SetFlagsToDefault()
virtual void lldb_private::ThreadPlanShouldStopHere::SetFlagsToDefault () protected pure virtual
Implemented in lldb_private::AppleThreadPlanStepThroughDirectDispatch, lldb_private::ThreadPlanStepInRange, lldb_private::ThreadPlanStepOut, and lldb_private::ThreadPlanStepOverRange.
SetShouldStopHereCallbacks()
void lldb_private::ThreadPlanShouldStopHere::SetShouldStopHereCallbacks (const ThreadPlanShouldStopHereCallbacks * callbacks, void * baton) inline
Definition at line 80 of file ThreadPlanShouldStopHere.h.
References ClearShouldStopHereCallbacks(), DefaultShouldStopHereCallback(), DefaultStepFromHereCallback(), m_baton, and m_callbacks.
Referenced by lldb_private::ThreadPlanStepInRange::SetCallbacks(), and ThreadPlanShouldStopHere().
Member Data Documentation
m_baton
void* lldb_private::ThreadPlanShouldStopHere::m_baton protected
Definition at line 129 of file ThreadPlanShouldStopHere.h.
Referenced by InvokeShouldStopHereCallback(), QueueStepOutFromHerePlan(), SetShouldStopHereCallbacks(), ThreadPlanShouldStopHere(), and ThreadPlanShouldStopHere().
m_callbacks
ThreadPlanShouldStopHereCallbacks lldb_private::ThreadPlanShouldStopHere::m_callbacks protected
Definition at line 128 of file ThreadPlanShouldStopHere.h.
Referenced by ClearShouldStopHereCallbacks(), InvokeShouldStopHereCallback(), QueueStepOutFromHerePlan(), SetShouldStopHereCallbacks(), ThreadPlanShouldStopHere(), and ThreadPlanShouldStopHere().
m_flags
lldb_private::Flags lldb_private::ThreadPlanShouldStopHere::m_flags protected
Definition at line 131 of file ThreadPlanShouldStopHere.h.
Referenced by CheckShouldStopHereAndQueueStepOut(), GetFlags(), GetFlags(), InvokeShouldStopHereCallback(), lldb_private::ThreadPlanStepOut::ShouldStop(), ThreadPlanShouldStopHere(), and ThreadPlanShouldStopHere().
m_owner
ThreadPlan* lldb_private::ThreadPlanShouldStopHere::m_owner protected
Definition at line 130 of file ThreadPlanShouldStopHere.h.
Referenced by InvokeShouldStopHereCallback(), QueueStepOutFromHerePlan(), ThreadPlanShouldStopHere(), and ThreadPlanShouldStopHere().
The documentation for this class was generated from the following files:
ThreadPlanShouldStopHere.h
ThreadPlanShouldStopHere.cpp