LLDB: lldb_private::formatters::StringPrinter Class Reference
lldb_private::formatters::StringPrinter Class Reference
#include <StringPrinter.h>
Classes
class DumpToStreamOptions
class ReadBufferAndDumpToStreamOptions
class ReadStringAndDumpToStreamOptions
Public Types
enum class StringElementType { ASCII , UTF8 , UTF16 , UTF32 }
enum class GetPrintableElementType { ASCII , UTF8 }
enum class EscapeStyle { CXX , Swift }
Static Public Member Functions
template<StringElementType element_type>
static bool ReadStringAndDumpToStream (const ReadStringAndDumpToStreamOptions &options)
template<StringElementType element_type>
static bool ReadBufferAndDumpToStream (const ReadBufferAndDumpToStreamOptions &options)
Detailed Description
Definition at line 21 of file StringPrinter.h.
Member Enumeration Documentation
EscapeStyle
enum class lldb_private::formatters::StringPrinter::EscapeStyle strong
Enumerator
CXX
Swift
Definition at line 27 of file StringPrinter.h.
GetPrintableElementType
enum class lldb_private::formatters::StringPrinter::GetPrintableElementType strong
Enumerator
ASCII
UTF8
Definition at line 25 of file StringPrinter.h.
StringElementType
enum class lldb_private::formatters::StringPrinter::StringElementType strong
Enumerator
ASCII
UTF8
UTF16
UTF32
Definition at line 23 of file StringPrinter.h.
Member Function Documentation
ReadBufferAndDumpToStream()
template<StringElementType element_type> bool lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream (const ReadBufferAndDumpToStreamOptions & options) static
Referenced by CharSummaryProvider(), lldb_private::ValueObject::DumpPrintableRepresentation(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream< StringElementType::ASCII >(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream< StringElementType::UTF16 >(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream< StringElementType::UTF32 >(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream< StringElementType::UTF8 >(), and lldb_private::formatters::WCharSummaryProvider().
ReadStringAndDumpToStream()
template<StringElementType element_type> bool lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream (const ReadStringAndDumpToStreamOptions & options) static
Referenced by CharStringSummaryProvider(), lldb_private::formatters::NSStringSummaryProvider(), lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream< StringElementType::ASCII >(), lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream< StringElementType::UTF16 >(), lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream< StringElementType::UTF32 >(), lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream< StringElementType::UTF8 >(), and lldb_private::formatters::WCharStringSummaryProvider().
The documentation for this class was generated from the following file:
StringPrinter.h