LLDB: lldb_private::Process::AttachCompletionHandler Class Reference
lldb_private::Process::AttachCompletionHandler Class Reference
#include <Process.h>
Public Member Functions
AttachCompletionHandler (Process *process, uint32_t exec_count)
~AttachCompletionHandler () override=default
EventActionResult PerformAction (lldb::EventSP &event_sp) override
EventActionResult HandleBeingInterrupted () override
const char * GetExitString () override
Public Member Functions inherited from lldb_private::Process::NextEventAction
NextEventAction (Process *process)
virtual ~NextEventAction ()=default
virtual void HandleBeingUnshipped ()
void RequestResume ()
Private Attributes
uint32_t m_exec_count
std::string m_exit_string
Additional Inherited Members
Public Types inherited from lldb_private::Process::NextEventAction
enum EventActionResult { eEventActionSuccess , eEventActionRetry , eEventActionExit }
Protected Attributes inherited from lldb_private::Process::NextEventAction
Process * m_process
Detailed Description
Definition at line 3056 of file Process.h.
Constructor & Destructor Documentation
AttachCompletionHandler()
Process::AttachCompletionHandler::AttachCompletionHandler (Process * process, uint32_t exec_count)
Definition at line 2976 of file Process.cpp.
References lldb_private::GetLog(), LLDB_LOGF, m_exec_count, lldb_private::Process::NextEventAction::NextEventAction(), lldb_private::Process, and lldb_private::Process::Process().
~AttachCompletionHandler()
lldb_private::Process::AttachCompletionHandler::~AttachCompletionHandler () override default
Member Function Documentation
GetExitString()
const char * Process::AttachCompletionHandler::GetExitString () override virtual
Implements lldb_private::Process::NextEventAction.
Definition at line 3048 of file Process.cpp.
References m_exit_string.
HandleBeingInterrupted()
Process::NextEventAction::EventActionResult Process::AttachCompletionHandler::HandleBeingInterrupted () override virtual
Implements lldb_private::Process::NextEventAction.
Definition at line 3044 of file Process.cpp.
References lldb_private::Process::NextEventAction::eEventActionSuccess.
PerformAction()
Process::NextEventAction::EventActionResult Process::AttachCompletionHandler::PerformAction (lldb::EventSP & event_sp) override virtual
Implements lldb_private::Process::NextEventAction.
Definition at line 2987 of file Process.cpp.
References lldb_private::Process::NextEventAction::eEventActionExit, lldb_private::Process::NextEventAction::eEventActionRetry, lldb_private::Process::NextEventAction::eEventActionSuccess, lldb::eStateAttaching, lldb::eStateConnected, lldb::eStateCrashed, lldb::eStateExited, lldb::eStateInvalid, lldb::eStateRunning, lldb::eStateStopped, lldb_private::eVoteNo, lldb_private::GetLog(), lldb_private::Process::ProcessEventData::GetStateFromEvent(), LLDB_INVALID_PROCESS_ID, LLDB_LOGF, m_exec_count, m_exit_string, lldb_private::Process::NextEventAction::m_process, lldb_private::Process, lldb_private::Process::NextEventAction::RequestResume(), and lldb_private::StateAsCString().
Member Data Documentation
m_exec_count
uint32_t lldb_private::Process::AttachCompletionHandler::m_exec_count private
Definition at line 3067 of file Process.h.
Referenced by AttachCompletionHandler(), and PerformAction().
m_exit_string
std::string lldb_private::Process::AttachCompletionHandler::m_exit_string private
Definition at line 3068 of file Process.h.
Referenced by GetExitString(), and PerformAction().
The documentation for this class was generated from the following files:
Process.h
Process.cpp