LLDB: lldb_private::Target::StopHook Class Reference
lldb_private::Target::StopHook Class Reference abstract
#include <Target.h>
Public Types
enum class StopHookKind : uint32_t { CommandBased = 0 , ScriptBased , CodeBased }
enum class StopHookResult : uint32_t { KeepStopped = 0 , RequestContinue , NoPreference , AlreadyContinued }
Public Member Functions
StopHook (const StopHook &rhs)
virtual ~StopHook ()=default
lldb::TargetSP & GetTarget ()
void SetSpecifier (SymbolContextSpecifier *specifier)
SymbolContextSpecifier * GetSpecifier ()
bool ExecutionContextPasses (const ExecutionContext &exe_ctx)
virtual StopHookResult HandleStop (ExecutionContext &exe_ctx, lldb::StreamSP output)=0
void SetThreadSpecifier (ThreadSpec *specifier)
ThreadSpec * GetThreadSpecifier ()
bool IsActive ()
void SetIsActive (bool is_active)
void SetAutoContinue (bool auto_continue)
bool GetAutoContinue () const
void SetRunAtInitialStop (bool at_initial_stop)
bool GetRunAtInitialStop () const
void SetSuppressOutput (bool suppress_output)
bool GetSuppressOutput () const
void GetDescription (Stream &s, lldb::DescriptionLevel level) const
virtual void GetSubclassDescription (Stream &s, lldb::DescriptionLevel level) const =0
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Protected Member Functions
StopHook (lldb::TargetSP target_sp, lldb::user_id_t uid)
Protected Attributes
lldb::TargetSP m_target_sp
lldb::SymbolContextSpecifierSP m_specifier_sp
std::unique_ptr< ThreadSpec > m_thread_spec_up
bool m_active = true
bool m_auto_continue = false
bool m_at_initial_stop = true
bool m_suppress_output = false
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Detailed Description
Definition at line 1477 of file Target.h.
Member Enumeration Documentation
StopHookKind
enum class lldb_private::Target::StopHook::StopHookKind : uint32_t strong
Enumerator
CommandBased
ScriptBased
CodeBased
Definition at line 1482 of file Target.h.
StopHookResult
enum class lldb_private::Target::StopHook::StopHookResult : uint32_t strong
Enumerator
KeepStopped
RequestContinue
NoPreference
AlreadyContinued
Definition at line 1487 of file Target.h.
Constructor & Destructor Documentation
StopHook() [1/2]
Target::StopHook::StopHook (const StopHook & rhs)
Definition at line 4000 of file Target.cpp.
References lldb_private::UserID::GetID(), m_active, m_auto_continue, m_specifier_sp, m_target_sp, m_thread_spec_up, StopHook(), and lldb_private::UserID::UserID().
Referenced by StopHook(), lldb_private::Target::StopHookCoded::StopHookCoded(), lldb_private::Target::StopHookCommandLine::StopHookCommandLine(), and lldb_private::Target::StopHookScripted::StopHookScripted().
~StopHook()
virtual lldb_private::Target::StopHook::~StopHook () virtual default
StopHook() [2/2]
Target::StopHook::StopHook (lldb::TargetSP target_sp, lldb::user_id_t uid) protected
Definition at line 3996 of file Target.cpp.
References m_specifier_sp, m_target_sp, m_thread_spec_up, and lldb_private::UserID::UserID().
Member Function Documentation
ExecutionContextPasses()
bool Target::StopHook::ExecutionContextPasses (const ExecutionContext & exe_ctx)
Definition at line 4016 of file Target.cpp.
References lldb_private::ExecutionContext::GetFramePtr(), GetSpecifier(), lldb_private::StackFrame::GetSymbolContext(), lldb_private::ExecutionContext::GetThreadRef(), and GetThreadSpecifier().
GetAutoContinue()
bool lldb_private::Target::StopHook::GetAutoContinue () const inline
Definition at line 1525 of file Target.h.
References m_auto_continue.
GetDescription()
void Target::StopHook::GetDescription (Stream & s, lldb::DescriptionLevel level) const
Definition at line 4032 of file Target.cpp.
References lldb::eDescriptionLevelBrief, lldb_private::UserID::GetID(), lldb_private::StreamString::GetString(), GetSubclassDescription(), lldb_private::Stream::Indent(), m_active, m_auto_continue, m_specifier_sp, m_thread_spec_up, lldb_private::Stream::MakeIndentScope(), lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
GetRunAtInitialStop()
bool lldb_private::Target::StopHook::GetRunAtInitialStop () const inline
Definition at line 1531 of file Target.h.
References m_at_initial_stop.
GetSpecifier()
SymbolContextSpecifier * lldb_private::Target::StopHook::GetSpecifier () inline
Definition at line 1500 of file Target.h.
References m_specifier_sp.
Referenced by ExecutionContextPasses().
GetSubclassDescription()
virtual void lldb_private::Target::StopHook::GetSubclassDescription (Stream & s, lldb::DescriptionLevel level) const pure virtual
Implemented in lldb_private::Target::StopHookCoded, lldb_private::Target::StopHookCommandLine, and lldb_private::Target::StopHookScripted.
Referenced by GetDescription().
GetSuppressOutput()
bool lldb_private::Target::StopHook::GetSuppressOutput () const inline
Definition at line 1537 of file Target.h.
References m_suppress_output.
GetTarget()
lldb::TargetSP & lldb_private::Target::StopHook::GetTarget () inline
Definition at line 1494 of file Target.h.
References m_target_sp.
Referenced by lldb_private::Target::StopHookScripted::SetScriptCallback().
GetThreadSpecifier()
ThreadSpec * lldb_private::Target::StopHook::GetThreadSpecifier () inline
Definition at line 1515 of file Target.h.
References m_thread_spec_up.
Referenced by ExecutionContextPasses().
HandleStop()
virtual StopHookResult lldb_private::Target::StopHook::HandleStop (ExecutionContext & exe_ctx, lldb::StreamSP output) pure virtual
Implemented in lldb_private::Target::StopHookCoded, lldb_private::Target::StopHookCommandLine, and lldb_private::Target::StopHookScripted.
IsActive()
bool lldb_private::Target::StopHook::IsActive () inline
Definition at line 1517 of file Target.h.
References m_active.
SetAutoContinue()
void lldb_private::Target::StopHook::SetAutoContinue (bool auto_continue) inline
Definition at line 1521 of file Target.h.
References m_auto_continue.
SetIsActive()
void lldb_private::Target::StopHook::SetIsActive (bool is_active) inline
Definition at line 1519 of file Target.h.
References m_active.
SetRunAtInitialStop()
void lldb_private::Target::StopHook::SetRunAtInitialStop (bool at_initial_stop) inline
Definition at line 1527 of file Target.h.
References m_at_initial_stop.
SetSpecifier()
void Target::StopHook::SetSpecifier (SymbolContextSpecifier * specifier)
Definition at line 4008 of file Target.cpp.
References m_specifier_sp.
SetSuppressOutput()
void lldb_private::Target::StopHook::SetSuppressOutput (bool suppress_output) inline
Definition at line 1533 of file Target.h.
References m_suppress_output.
SetThreadSpecifier()
void Target::StopHook::SetThreadSpecifier (ThreadSpec * specifier)
Definition at line 4012 of file Target.cpp.
References m_thread_spec_up.
Member Data Documentation
m_active
bool lldb_private::Target::StopHook::m_active = true protected
Definition at line 1547 of file Target.h.
Referenced by GetDescription(), IsActive(), SetIsActive(), and StopHook().
m_at_initial_stop
bool lldb_private::Target::StopHook::m_at_initial_stop = true protected
Definition at line 1549 of file Target.h.
Referenced by GetRunAtInitialStop(), and SetRunAtInitialStop().
m_auto_continue
bool lldb_private::Target::StopHook::m_auto_continue = false protected
Definition at line 1548 of file Target.h.
Referenced by GetAutoContinue(), GetDescription(), SetAutoContinue(), and StopHook().
m_specifier_sp
lldb::SymbolContextSpecifierSP lldb_private::Target::StopHook::m_specifier_sp protected
Definition at line 1545 of file Target.h.
Referenced by GetDescription(), GetSpecifier(), SetSpecifier(), StopHook(), and StopHook().
m_suppress_output
bool lldb_private::Target::StopHook::m_suppress_output = false protected
Definition at line 1550 of file Target.h.
Referenced by GetSuppressOutput(), and SetSuppressOutput().
m_target_sp
lldb::TargetSP lldb_private::Target::StopHook::m_target_sp protected
Definition at line 1544 of file Target.h.
Referenced by GetTarget(), StopHook(), and StopHook().
m_thread_spec_up
std::unique_ptr<ThreadSpec> lldb_private::Target::StopHook::m_thread_spec_up protected
Definition at line 1546 of file Target.h.
Referenced by GetDescription(), GetThreadSpecifier(), SetThreadSpecifier(), StopHook(), and StopHook().
The documentation for this class was generated from the following files:
Target.h
Target.cpp