LLDB: lldb_private::Process::NextEventAction Class Reference
lldb_private::Process::NextEventAction Class Reference abstract
#include <Process.h>
Public Types
enum EventActionResult { eEventActionSuccess , eEventActionRetry , eEventActionExit }
Public Member Functions
NextEventAction (Process *process)
virtual ~NextEventAction ()=default
virtual EventActionResult PerformAction (lldb::EventSP &event_sp)=0
virtual void HandleBeingUnshipped ()
virtual EventActionResult HandleBeingInterrupted ()=0
virtual const char * GetExitString ()=0
void RequestResume ()
Protected Attributes
Process * m_process
Detailed Description
Definition at line 3026 of file Process.h.
Member Enumeration Documentation
EventActionResult
enum lldb_private::Process::NextEventAction::EventActionResult
Enumerator
eEventActionSuccess
eEventActionRetry
eEventActionExit
Definition at line 3028 of file Process.h.
Constructor & Destructor Documentation
NextEventAction()
lldb_private::Process::NextEventAction::NextEventAction (Process * process) inline
Definition at line 3034 of file Process.h.
References m_process, and lldb_private::Process::Process().
Referenced by lldb_private::Process::AttachCompletionHandler::AttachCompletionHandler().
~NextEventAction()
virtual lldb_private::Process::NextEventAction::~NextEventAction () virtual default
Member Function Documentation
GetExitString()
virtual const char * lldb_private::Process::NextEventAction::GetExitString () pure virtual
Implemented in lldb_private::Process::AttachCompletionHandler.
HandleBeingInterrupted()
virtual EventActionResult lldb_private::Process::NextEventAction::HandleBeingInterrupted () pure virtual
Implemented in lldb_private::Process::AttachCompletionHandler.
HandleBeingUnshipped()
virtual void lldb_private::Process::NextEventAction::HandleBeingUnshipped () inline virtual
Definition at line 3039 of file Process.h.
PerformAction()
virtual EventActionResult lldb_private::Process::NextEventAction::PerformAction (lldb::EventSP & event_sp) pure virtual
Implemented in lldb_private::Process::AttachCompletionHandler.
RequestResume()
void lldb_private::Process::NextEventAction::RequestResume () inline
Definition at line 3042 of file Process.h.
References m_process.
Referenced by lldb_private::Process::AttachCompletionHandler::PerformAction().
Member Data Documentation
m_process
Process* lldb_private::Process::NextEventAction::m_process protected
Definition at line 3045 of file Process.h.
Referenced by NextEventAction(), lldb_private::Process::AttachCompletionHandler::PerformAction(), and RequestResume().
The documentation for this class was generated from the following file:
Process.h