LLDB: lldb_private::TypeFilterImpl Class Reference
lldb_private::TypeFilterImpl Class Reference
#include <TypeSynthetic.h>
Classes
class FrontEnd
Public Types
typedef std::shared_ptr< TypeFilterImpl > SharedPointer
Public Types inherited from lldb_private::SyntheticChildren
typedef std::shared_ptr< SyntheticChildren > SharedPointer
Public Member Functions
TypeFilterImpl (const SyntheticChildren::Flags &flags)
TypeFilterImpl (const SyntheticChildren::Flags &flags, const std::initializer_list< const char * > items)
void AddExpressionPath (const char *path)
void Clear ()
size_t GetCount () const
const char * GetExpressionPathAtIndex (size_t i) const
bool SetExpressionPathAtIndex (size_t i, const char *path)
void AddExpressionPath (const std::string &path)
bool SetExpressionPathAtIndex (size_t i, const std::string &path)
bool IsScripted () override
std::string GetDescription () override
SyntheticChildrenFrontEnd::UniquePointer GetFrontEnd (ValueObject &backend) override
Public Member Functions inherited from lldb_private::SyntheticChildren
SyntheticChildren (const Flags &flags)
virtual ~SyntheticChildren ()
bool Cascades () const
bool SkipsPointers () const
bool SkipsReferences () const
bool NonCacheable () const
bool WantsDereference () const
void SetCascades (bool value)
void SetSkipsPointers (bool value)
void SetSkipsReferences (bool value)
void SetNonCacheable (bool value)
uint32_t GetOptions ()
void SetOptions (uint32_t value)
uint32_t & GetRevision ()
uint32_t GetPtrMatchDepth ()
void SetPtrMatchDepth (uint32_t value)
Private Member Functions
TypeFilterImpl (const TypeFilterImpl &)=delete
const TypeFilterImpl & operator= (const TypeFilterImpl &)=delete
Private Attributes
std::vector< std::string > m_expression_paths
Additional Inherited Members
Protected Attributes inherited from lldb_private::SyntheticChildren
uint32_t m_my_revision = 0
Flags m_flags
uint32_t m_ptr_match_depth = 1
Detailed Description
Definition at line 285 of file TypeSynthetic.h.
Member Typedef Documentation
SharedPointer
typedef std::shared_ptr<TypeFilterImpl> lldb_private::TypeFilterImpl::SharedPointer
Definition at line 364 of file TypeSynthetic.h.
Constructor & Destructor Documentation
TypeFilterImpl() [1/3]
lldb_private::TypeFilterImpl::TypeFilterImpl (const SyntheticChildren::Flags & flags) inline
Definition at line 289 of file TypeSynthetic.h.
References lldb_private::SyntheticChildren::SyntheticChildren().
Referenced by lldb_private::TypeFilterImpl::FrontEnd::FrontEnd(), operator=(), and TypeFilterImpl().
TypeFilterImpl() [2/3]
lldb_private::TypeFilterImpl::TypeFilterImpl (const SyntheticChildren::Flags & flags, const std::initializer_list< const char * > items) inline
Definition at line 292 of file TypeSynthetic.h.
References AddExpressionPath(), and lldb_private::SyntheticChildren::SyntheticChildren().
TypeFilterImpl() [3/3]
lldb_private::TypeFilterImpl::TypeFilterImpl (const TypeFilterImpl &) private delete
References TypeFilterImpl().
Member Function Documentation
AddExpressionPath() [1/2]
void lldb_private::TypeFilterImpl::AddExpressionPath (const char * path) inline
Definition at line 299 of file TypeSynthetic.h.
References AddExpressionPath().
Referenced by AddExpressionPath(), and TypeFilterImpl().
AddExpressionPath() [2/2]
void TypeFilterImpl::AddExpressionPath (const std::string & path)
Definition at line 29 of file TypeSynthetic.cpp.
References m_expression_paths.
Clear()
void lldb_private::TypeFilterImpl::Clear () inline
Definition at line 303 of file TypeSynthetic.h.
References m_expression_paths.
GetCount()
size_t lldb_private::TypeFilterImpl::GetCount () const inline
Definition at line 305 of file TypeSynthetic.h.
References m_expression_paths.
Referenced by GetDescription(), and SetExpressionPathAtIndex().
GetDescription()
std::string TypeFilterImpl::GetDescription () override virtual
Implements lldb_private::SyntheticChildren.
Definition at line 77 of file TypeSynthetic.cpp.
References lldb_private::SyntheticChildren::Cascades(), GetCount(), GetExpressionPathAtIndex(), lldb_private::StreamString::GetString(), lldb_private::Stream::Printf(), lldb_private::SyntheticChildren::SkipsPointers(), and lldb_private::SyntheticChildren::SkipsReferences().
GetExpressionPathAtIndex()
const char * lldb_private::TypeFilterImpl::GetExpressionPathAtIndex (size_t i) const inline
Definition at line 307 of file TypeSynthetic.h.
References m_expression_paths.
Referenced by GetDescription().
GetFrontEnd()
SyntheticChildrenFrontEnd::UniquePointer lldb_private::TypeFilterImpl::GetFrontEnd (ValueObject & backend) inline override virtual
Implements lldb_private::SyntheticChildren.
Definition at line 359 of file TypeSynthetic.h.
IsScripted()
bool lldb_private::TypeFilterImpl::IsScripted () inline override virtual
Implements lldb_private::SyntheticChildren.
Definition at line 319 of file TypeSynthetic.h.
operator=()
const TypeFilterImpl & lldb_private::TypeFilterImpl::operator= (const TypeFilterImpl &) private delete
References TypeFilterImpl().
SetExpressionPathAtIndex() [1/2]
bool lldb_private::TypeFilterImpl::SetExpressionPathAtIndex (size_t i, const char * path) inline
Definition at line 311 of file TypeSynthetic.h.
References SetExpressionPathAtIndex().
Referenced by SetExpressionPathAtIndex().
SetExpressionPathAtIndex() [2/2]
bool TypeFilterImpl::SetExpressionPathAtIndex (size_t i, const std::string & path)
Definition at line 40 of file TypeSynthetic.cpp.
References GetCount(), and m_expression_paths.
Member Data Documentation
m_expression_paths
std::vector<std::string> lldb_private::TypeFilterImpl::m_expression_paths private
Definition at line 286 of file TypeSynthetic.h.
Referenced by AddExpressionPath(), Clear(), GetCount(), GetExpressionPathAtIndex(), and SetExpressionPathAtIndex().
The documentation for this class was generated from the following files:
TypeSynthetic.h
TypeSynthetic.cpp