LLDB: lldb_private::RegisterContextLinux_x86 Class Reference
lldb_private::RegisterContextLinux_x86 Class Reference
#include <RegisterContextLinux_x86.h>
Public Member Functions
RegisterContextLinux_x86 (const ArchSpec &target_arch, RegisterInfo orig_ax_info)
const RegisterInfo & GetOrigAxInfo () const
Public Member Functions inherited from lldb_private::RegisterInfoInterface
RegisterInfoInterface (const lldb_private::ArchSpec &target_arch)
virtual ~RegisterInfoInterface ()=default
virtual size_t GetGPRSize () const =0
virtual const lldb_private::RegisterInfo * GetRegisterInfo () const =0
virtual uint32_t GetRegisterCount () const =0
virtual uint32_t GetUserRegisterCount () const
const lldb_private::ArchSpec & GetTargetArchitecture () const
Private Attributes
lldb_private::RegisterInfo m_orig_ax_info
Detailed Description
Definition at line 16 of file RegisterContextLinux_x86.h.
Constructor & Destructor Documentation
RegisterContextLinux_x86()
lldb_private::RegisterContextLinux_x86::RegisterContextLinux_x86 (const ArchSpec & target_arch, RegisterInfo orig_ax_info) inline
Definition at line 18 of file RegisterContextLinux_x86.h.
References m_orig_ax_info, and lldb_private::RegisterInfoInterface::RegisterInfoInterface().
Referenced by RegisterContextLinux_i386::RegisterContextLinux_i386(), and RegisterContextLinux_x86_64::RegisterContextLinux_x86_64().
Member Function Documentation
GetOrigAxInfo()
const RegisterInfo & lldb_private::RegisterContextLinux_x86::GetOrigAxInfo () const inline
Definition at line 22 of file RegisterContextLinux_x86.h.
References m_orig_ax_info.
Member Data Documentation
m_orig_ax_info
lldb_private::RegisterInfo lldb_private::RegisterContextLinux_x86::m_orig_ax_info private
Definition at line 25 of file RegisterContextLinux_x86.h.
Referenced by GetOrigAxInfo(), and RegisterContextLinux_x86().
The documentation for this class was generated from the following file:
RegisterContextLinux_x86.h