LLDB: lldb_private::NativeThreadWindows Class Reference
lldb_private::NativeThreadWindows Class Reference
#include <NativeThreadWindows.h>
Public Member Functions
NativeThreadWindows (NativeProcessWindows &process, const HostThread &thread)
~NativeThreadWindows ()
Status DoStop ()
Status DoResume (lldb::StateType resume_state)
std::string GetName () override
lldb::StateType GetState () override
NativeRegisterContextWindows & GetRegisterContext () override
bool GetStopReason (ThreadStopInfo &stop_info, std::string &description) override
Status SetWatchpoint (lldb::addr_t addr, size_t size, uint32_t watch_flags, bool hardware) override
Status RemoveWatchpoint (lldb::addr_t addr) override
Status SetHardwareBreakpoint (lldb::addr_t addr, size_t size) override
Status RemoveHardwareBreakpoint (lldb::addr_t addr) override
void SetStopReason (ThreadStopInfo stop_info, std::string description)
const HostThread & GetHostThread ()
Public Member Functions inherited from lldb_private::NativeThreadProtocol
NativeThreadProtocol (NativeProcessProtocol &process, lldb::tid_t tid)
virtual ~NativeThreadProtocol ()=default
lldb::tid_t GetID () const
NativeProcessProtocol & GetProcess ()
virtual llvm::Expected< std::unique_ptr< llvm::MemoryBuffer > > GetSiginfo () const
Protected Types
using IndexMap = std::map<lldb::addr_t, uint32_t>
Protected Attributes
lldb::StateType m_state = lldb::StateType::eStateInvalid
std::string m_name
ThreadStopInfo m_stop_info
std::string m_stop_description
std::unique_ptr< NativeRegisterContextWindows > m_reg_context_up
IndexMap m_watchpoint_index_map
IndexMap m_hw_breakpoint_index_map
HostThread m_host_thread
Protected Attributes inherited from lldb_private::NativeThreadProtocol
NativeProcessProtocol & m_process
lldb::tid_t m_tid
Detailed Description
Definition at line 22 of file NativeThreadWindows.h.
Member Typedef Documentation
IndexMap
using lldb_private::NativeThreadWindows::IndexMap = std::map<lldb::addr_t, uint32_t> protected
Definition at line 63 of file NativeThreadWindows.h.
Constructor & Destructor Documentation
NativeThreadWindows()
NativeThreadWindows::NativeThreadWindows (NativeProcessWindows & process, const HostThread & thread)
Definition at line 25 of file NativeThreadWindows.cpp.
References lldb_private::NativeRegisterContextWindows::CreateHostNativeRegisterContextWindows(), lldb_private::NativeProcessWindows::GetArchitecture(), m_host_thread, m_reg_context_up, m_stop_description, m_stop_info, and lldb_private::NativeThreadProtocol::NativeThreadProtocol().
~NativeThreadWindows()
lldb_private::NativeThreadWindows::~NativeThreadWindows () inline
Definition at line 26 of file NativeThreadWindows.h.
Member Function Documentation
DoResume()
Status NativeThreadWindows::DoResume (lldb::StateType resume_state)
Definition at line 46 of file NativeThreadWindows.cpp.
References lldb_private::NativeRegisterContext::ConvertRegisterKindToRegisterNumber(), lldb::eErrorTypeWin32, lldb::eRegisterKindGeneric, lldb::eStateRunning, lldb::eStateStepping, lldb_private::NativeProcessProtocol::GetArchitecture(), lldb_private::GetLog(), lldb_private::ArchSpec::GetMachine(), lldb_private::NativeThreadProtocol::GetProcess(), GetRegisterContext(), GetState(), LLDB_LOG, LLDB_REGNUM_GENERIC_FLAGS, m_host_thread, m_state, lldb_private::NativeRegisterContext::ReadRegisterAsUnsigned(), lldb_private::Status, lldb_private::Thread, and lldb_private::NativeRegisterContext::WriteRegisterFromUnsigned().
DoStop()
Status NativeThreadWindows::DoStop ()
Definition at line 34 of file NativeThreadWindows.cpp.
References lldb::eErrorTypeWin32, lldb::eStateStopped, m_host_thread, m_state, and lldb_private::Status.
GetHostThread()
const HostThread & lldb_private::NativeThreadWindows::GetHostThread () inline
Definition at line 53 of file NativeThreadWindows.h.
References m_host_thread.
Referenced by lldb_private::NativeRegisterContextWindows::GetThreadHandle().
GetName()
std::string NativeThreadWindows::GetName () override virtual
Implements lldb_private::NativeThreadProtocol.
Definition at line 98 of file NativeThreadWindows.cpp.
References lldb_private::NativeProcessProtocol::GetID(), lldb_private::ProcessInfo::GetName(), lldb_private::NativeThreadProtocol::GetProcess(), lldb_private::Host::GetProcessInfo(), and m_name.
GetRegisterContext()
NativeRegisterContextWindows & lldb_private::NativeThreadWindows::GetRegisterContext () inline override virtual
Implements lldb_private::NativeThreadProtocol.
Definition at line 35 of file NativeThreadWindows.h.
References m_reg_context_up.
Referenced by DoResume().
GetState()
lldb::StateType lldb_private::NativeThreadWindows::GetState () inline override virtual
Implements lldb_private::NativeThreadProtocol.
Definition at line 33 of file NativeThreadWindows.h.
References m_state.
Referenced by DoResume().
GetStopReason()
bool NativeThreadWindows::GetStopReason (ThreadStopInfo & stop_info, std::string & description) override virtual
Implements lldb_private::NativeThreadProtocol.
Definition at line 120 of file NativeThreadWindows.cpp.
References lldb::eStateAttaching, lldb::eStateConnected, lldb::eStateCrashed, lldb::eStateDetached, lldb::eStateExited, lldb::eStateInvalid, lldb::eStateLaunching, lldb::eStateRunning, lldb::eStateStepping, lldb::eStateStopped, lldb::eStateSuspended, lldb::eStateUnloaded, lldb_private::NativeThreadProtocol::GetID(), lldb_private::GetLog(), m_state, m_stop_description, m_stop_info, lldb_private::Log::Printf(), lldb_private::StateAsCString(), and lldb_private::Thread.
RemoveHardwareBreakpoint()
Status NativeThreadWindows::RemoveHardwareBreakpoint (lldb::addr_t addr) override virtual
Implements lldb_private::NativeThreadProtocol.
Definition at line 184 of file NativeThreadWindows.cpp.
References lldb_private::Status::FromErrorString().
RemoveWatchpoint()
Status NativeThreadWindows::RemoveWatchpoint (lldb::addr_t addr) override virtual
Implements lldb_private::NativeThreadProtocol.
Definition at line 168 of file NativeThreadWindows.cpp.
References lldb_private::Status::FromErrorString(), m_reg_context_up, m_watchpoint_index_map, and lldb_private::Status.
Referenced by SetWatchpoint().
SetHardwareBreakpoint()
Status NativeThreadWindows::SetHardwareBreakpoint (lldb::addr_t addr, size_t size) override virtual
Implements lldb_private::NativeThreadProtocol.
Definition at line 179 of file NativeThreadWindows.cpp.
References lldb_private::Status::FromErrorString().
SetStopReason()
void NativeThreadWindows::SetStopReason (ThreadStopInfo stop_info, std::string description)
Definition at line 113 of file NativeThreadWindows.cpp.
References lldb::eStateStopped, m_state, m_stop_description, and m_stop_info.
SetWatchpoint()
Status NativeThreadWindows::SetWatchpoint (lldb::addr_t addr, size_t size, uint32_t watch_flags, bool hardware) override virtual
Implements lldb_private::NativeThreadProtocol.
Definition at line 151 of file NativeThreadWindows.cpp.
References error(), lldb::eStateLaunching, lldb_private::Status::FromErrorString(), LLDB_INVALID_INDEX32, m_reg_context_up, m_state, m_watchpoint_index_map, RemoveWatchpoint(), and lldb_private::Status.
Member Data Documentation
m_host_thread
HostThread lldb_private::NativeThreadWindows::m_host_thread protected
Definition at line 66 of file NativeThreadWindows.h.
Referenced by DoResume(), DoStop(), GetHostThread(), and NativeThreadWindows().
m_hw_breakpoint_index_map
IndexMap lldb_private::NativeThreadWindows::m_hw_breakpoint_index_map protected
Definition at line 65 of file NativeThreadWindows.h.
m_name
std::string lldb_private::NativeThreadWindows::m_name protected
Definition at line 57 of file NativeThreadWindows.h.
Referenced by GetName().
m_reg_context_up
std::unique_ptr<NativeRegisterContextWindows> lldb_private::NativeThreadWindows::m_reg_context_up protected
Definition at line 60 of file NativeThreadWindows.h.
Referenced by GetRegisterContext(), NativeThreadWindows(), RemoveWatchpoint(), and SetWatchpoint().
m_state
lldb::StateType lldb_private::NativeThreadWindows::m_state = lldb::StateType::eStateInvalid protected
Definition at line 56 of file NativeThreadWindows.h.
Referenced by DoResume(), DoStop(), GetState(), GetStopReason(), SetStopReason(), and SetWatchpoint().
m_stop_description
std::string lldb_private::NativeThreadWindows::m_stop_description protected
Definition at line 59 of file NativeThreadWindows.h.
Referenced by GetStopReason(), NativeThreadWindows(), and SetStopReason().
m_stop_info
ThreadStopInfo lldb_private::NativeThreadWindows::m_stop_info protected
Definition at line 58 of file NativeThreadWindows.h.
Referenced by GetStopReason(), NativeThreadWindows(), and SetStopReason().
m_watchpoint_index_map
IndexMap lldb_private::NativeThreadWindows::m_watchpoint_index_map protected
Definition at line 64 of file NativeThreadWindows.h.
Referenced by RemoveWatchpoint(), and SetWatchpoint().
The documentation for this class was generated from the following files:
NativeThreadWindows.h
NativeThreadWindows.cpp