LLDB: lldb_private::InstrumentationRuntimeMainThreadChecker Class Reference
lldb_private::InstrumentationRuntimeMainThreadChecker Class Reference
#include <InstrumentationRuntimeMainThreadChecker.h>
Public Member Functions
~InstrumentationRuntimeMainThreadChecker () override
llvm::StringRef GetPluginName () override
virtual lldb::InstrumentationRuntimeType GetType ()
lldb::ThreadCollectionSP GetBacktracesFromExtendedStopInfo (StructuredData::ObjectSP info) override
Public Member Functions inherited from lldb_private::InstrumentationRuntime
void ModulesDidLoad (lldb_private::ModuleList &module_list)
Look for the instrumentation runtime in module_list.
bool IsActive () const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static lldb::InstrumentationRuntimeSP CreateInstance (const lldb::ProcessSP &process_sp)
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static lldb::InstrumentationRuntimeType GetTypeStatic ()
Static Public Member Functions inherited from lldb_private::InstrumentationRuntime
static void ModulesDidLoad (lldb_private::ModuleList &module_list, Process *process, InstrumentationRuntimeCollection &runtimes)
Private Member Functions
InstrumentationRuntimeMainThreadChecker (const lldb::ProcessSP &process_sp)
const RegularExpression & GetPatternForRuntimeLibrary () override
Return a regular expression which can be used to identify a valid version of the runtime library.
bool CheckIfRuntimeIsValid (const lldb::ModuleSP module_sp) override
Check whether module_sp corresponds to a valid runtime library.
void Activate () override
Register a breakpoint in the runtime library and perform any other necessary initialization.
void Deactivate ()
StructuredData::ObjectSP RetrieveReportData (ExecutionContextRef exe_ctx_ref)
Static Private Member Functions
static bool NotifyBreakpointHit (void *baton, StoppointCallbackContext *context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id)
Additional Inherited Members
Protected Member Functions inherited from lldb_private::InstrumentationRuntime
InstrumentationRuntime (const lldb::ProcessSP &process_sp)
lldb::ProcessSP GetProcessSP ()
lldb::ModuleSP GetRuntimeModuleSP ()
void SetRuntimeModuleSP (lldb::ModuleSP module_sp)
lldb::user_id_t GetBreakpointID () const
void SetBreakpointID (lldb::user_id_t ID)
void SetActive (bool IsActive)
virtual bool MatchAllModules ()
Detailed Description
Definition at line 19 of file InstrumentationRuntimeMainThreadChecker.h.
Constructor & Destructor Documentation
~InstrumentationRuntimeMainThreadChecker()
InstrumentationRuntimeMainThreadChecker::~InstrumentationRuntimeMainThreadChecker () override
Definition at line 34 of file InstrumentationRuntimeMainThreadChecker.cpp.
References Deactivate(), and InstrumentationRuntimeMainThreadChecker().
InstrumentationRuntimeMainThreadChecker()
lldb_private::InstrumentationRuntimeMainThreadChecker::InstrumentationRuntimeMainThreadChecker (const lldb::ProcessSP & process_sp) inline private
Definition at line 43 of file InstrumentationRuntimeMainThreadChecker.h.
References lldb_private::InstrumentationRuntime::InstrumentationRuntime().
Referenced by CreateInstance(), NotifyBreakpointHit(), and ~InstrumentationRuntimeMainThreadChecker().
Member Function Documentation
Activate()
void InstrumentationRuntimeMainThreadChecker::Activate () override private virtual
Register a breakpoint in the runtime library and perform any other necessary initialization.
The runtime library is guaranteed to be loaded.
Implements lldb_private::InstrumentationRuntime.
Definition at line 187 of file InstrumentationRuntimeMainThreadChecker.cpp.
References lldb::eSymbolTypeCode, lldb_private::Symbol::GetAddressRef(), lldb_private::Stoppoint::GetID(), lldb_private::Address::GetOpcodeLoadAddress(), lldb_private::InstrumentationRuntime::GetProcessSP(), lldb_private::InstrumentationRuntime::GetRuntimeModuleSP(), lldb_private::InstrumentationRuntime::IsActive(), lldb_private::Address::IsValid(), LLDB_INVALID_ADDRESS, NotifyBreakpointHit(), lldb_private::InstrumentationRuntime::SetActive(), lldb_private::InstrumentationRuntime::SetBreakpointID(), lldb_private::Breakpoint::SetBreakpointKind(), lldb_private::Breakpoint::SetCallback(), and lldb_private::Symbol::ValueIsAddress().
CheckIfRuntimeIsValid()
bool InstrumentationRuntimeMainThreadChecker::CheckIfRuntimeIsValid (const lldb::ModuleSP module_sp) override private virtual
Check whether module_sp corresponds to a valid runtime library.
Implements lldb_private::InstrumentationRuntime.
Definition at line 68 of file InstrumentationRuntimeMainThreadChecker.cpp.
References lldb::eSymbolTypeAny.
CreateInstance()
lldb::InstrumentationRuntimeSP InstrumentationRuntimeMainThreadChecker::CreateInstance (const lldb::ProcessSP & process_sp) static
Definition at line 40 of file InstrumentationRuntimeMainThreadChecker.cpp.
References InstrumentationRuntimeMainThreadChecker().
Referenced by Initialize(), and Terminate().
Deactivate()
void InstrumentationRuntimeMainThreadChecker::Deactivate () private
Definition at line 227 of file InstrumentationRuntimeMainThreadChecker.cpp.
References lldb_private::InstrumentationRuntime::GetBreakpointID(), lldb_private::InstrumentationRuntime::GetProcessSP(), LLDB_INVALID_BREAK_ID, lldb_private::InstrumentationRuntime::SetActive(), and lldb_private::InstrumentationRuntime::SetBreakpointID().
Referenced by ~InstrumentationRuntimeMainThreadChecker().
GetBacktracesFromExtendedStopInfo()
lldb::ThreadCollectionSP InstrumentationRuntimeMainThreadChecker::GetBacktracesFromExtendedStopInfo (StructuredData::ObjectSP info) override virtual
Reimplemented from lldb_private::InstrumentationRuntime.
Definition at line 241 of file InstrumentationRuntimeMainThreadChecker.cpp.
References lldb_private::Calls, lldb_private::InstrumentationRuntime::GetProcessSP(), and lldb_private::StructuredData::Object::GetUnsignedIntegerValue().
GetPatternForRuntimeLibrary()
const RegularExpression & InstrumentationRuntimeMainThreadChecker::GetPatternForRuntimeLibrary () override private virtual
Return a regular expression which can be used to identify a valid version of the runtime library.
Implements lldb_private::InstrumentationRuntime.
Definition at line 63 of file InstrumentationRuntimeMainThreadChecker.cpp.
GetPluginName()
llvm::StringRef lldb_private::InstrumentationRuntimeMainThreadChecker::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 35 of file InstrumentationRuntimeMainThreadChecker.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::InstrumentationRuntimeMainThreadChecker::GetPluginNameStatic () inline static
Definition at line 31 of file InstrumentationRuntimeMainThreadChecker.h.
Referenced by GetPluginName(), and Initialize().
GetType()
virtual lldb::InstrumentationRuntimeType lldb_private::InstrumentationRuntimeMainThreadChecker::GetType () inline virtual
Definition at line 37 of file InstrumentationRuntimeMainThreadChecker.h.
References GetTypeStatic().
GetTypeStatic()
lldb::InstrumentationRuntimeType InstrumentationRuntimeMainThreadChecker::GetTypeStatic () static
Definition at line 58 of file InstrumentationRuntimeMainThreadChecker.cpp.
References lldb::eInstrumentationRuntimeTypeMainThreadChecker.
Referenced by GetType(), and Initialize().
Initialize()
void InstrumentationRuntimeMainThreadChecker::Initialize () static
Definition at line 46 of file InstrumentationRuntimeMainThreadChecker.cpp.
References CreateInstance(), GetPluginNameStatic(), GetTypeStatic(), and lldb_private::PluginManager::RegisterPlugin().
NotifyBreakpointHit()
bool InstrumentationRuntimeMainThreadChecker::NotifyBreakpointHit (void * baton, StoppointCallbackContext * context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id) static private
< false => resume execution.
Definition at line 151 of file InstrumentationRuntimeMainThreadChecker.cpp.
References lldb_private::InstrumentationRuntimeStopInfo::CreateStopReasonWithInstrumentationData(), lldb_private::StoppointCallbackContext::exe_ctx_ref, lldb_private::ExecutionContextRef::GetProcessSP(), lldb_private::InstrumentationRuntime::GetProcessSP(), lldb_private::ExecutionContextRef::GetThreadSP(), InstrumentationRuntimeMainThreadChecker(), and RetrieveReportData().
Referenced by Activate().
RetrieveReportData()
StructuredData::ObjectSP InstrumentationRuntimeMainThreadChecker::RetrieveReportData (ExecutionContextRef exe_ctx_ref) private
Definition at line 77 of file InstrumentationRuntimeMainThreadChecker.cpp.
References lldb_private::StructuredData::Array::AddIntegerItem(), DoNoSelectMostRelevantFrame, lldb_private::Status::Fail(), lldb_private::Address::GetLoadAddress(), lldb_private::Address::GetModule(), lldb_private::InstrumentationRuntime::GetProcessSP(), lldb_private::InstrumentationRuntime::GetRuntimeModuleSP(), lldb_private::ExecutionContextRef::GetThreadSP(), and lldb_private::Target::ReadCStringFromMemory().
Referenced by NotifyBreakpointHit().
Terminate()
void InstrumentationRuntimeMainThreadChecker::Terminate () static
Definition at line 53 of file InstrumentationRuntimeMainThreadChecker.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
The documentation for this class was generated from the following files:
InstrumentationRuntimeMainThreadChecker.h
InstrumentationRuntimeMainThreadChecker.cpp