LLDB: lldb_private::TypeList Class Reference
lldb_private::TypeList Class Reference
#include <TypeList.h>
Public Types
typedef std::vector< lldb::TypeSP > collection
typedef llvm::iterator_range< collection::const_iterator > TypeIterable
Public Member Functions
TypeList ()
virtual ~TypeList ()
void Clear ()
void Dump (Stream *s, bool show_context)
TypeList FindTypes (ConstString name)
void Insert (const lldb::TypeSP &type)
uint32_t GetSize () const
bool Empty () const
lldb::TypeSP GetTypeAtIndex (uint32_t idx)
TypeIterable Types ()
void ForEach (std::function< bool(const lldb::TypeSP &type_sp)> const &callback) const
void ForEach (std::function< bool(lldb::TypeSP &type_sp)> const &callback)
Private Types
typedef collection::iterator iterator
typedef collection::const_iterator const_iterator
Private Member Functions
TypeList (const TypeList &)=delete
const TypeList & operator= (const TypeList &)=delete
Private Attributes
collection m_types
Detailed Description
Definition at line 20 of file TypeList.h.
Member Typedef Documentation
collection
typedef std::vector<lldb::TypeSP> lldb_private::TypeList::collection
Definition at line 41 of file TypeList.h.
const_iterator
typedef collection::const_iterator lldb_private::TypeList::const_iterator private
Definition at line 53 of file TypeList.h.
iterator
typedef collection::iterator lldb_private::TypeList::iterator private
Definition at line 52 of file TypeList.h.
TypeIterable
typedef llvm::iterator_range<collection::const_iterator> lldb_private::TypeList::TypeIterable
Definition at line 42 of file TypeList.h.
Constructor & Destructor Documentation
TypeList() [1/2]
TypeList::TypeList ()
Definition at line 22 of file TypeList.cpp.
References m_types.
Referenced by FindTypes(), operator=(), and TypeList().
~TypeList()
TypeList::~TypeList () virtual default
TypeList() [2/2]
lldb_private::TypeList::TypeList (const TypeList &) private delete
References TypeList().
Member Function Documentation
Clear()
void TypeList::Clear ()
Definition at line 58 of file TypeList.cpp.
References m_types.
Dump()
void TypeList::Dump (Stream * s, bool show_context)
Definition at line 94 of file TypeList.cpp.
References m_types.
Empty()
bool lldb_private::TypeList::Empty () const inline
Definition at line 37 of file TypeList.h.
References GetSize().
Referenced by lldb_private::ItaniumABILanguageRuntime::GetTypeInfo(), LookupTypeHere(), and LookupTypeInModule().
FindTypes()
TypeList lldb_private::TypeList::FindTypes (ConstString name)
References TypeList().
ForEach() [1/2]
void TypeList::ForEach (std::function< bool(const lldb::TypeSP &type_sp)> const & callback) const
Definition at line 78 of file TypeList.cpp.
References m_types.
Referenced by lldb_private::TypeListImpl::Append(), and lldb_private::SymbolContext::SortTypeList().
ForEach() [2/2]
void TypeList::ForEach (std::function< bool(lldb::TypeSP &type_sp)> const & callback)
Definition at line 86 of file TypeList.cpp.
References m_types.
GetSize()
uint32_t TypeList::GetSize () const
Definition at line 60 of file TypeList.cpp.
References m_types.
Referenced by lldb_private::TypeSystemClang::DumpFromSymbolFile(), Empty(), GetTypeAtIndex(), lldb_private::ItaniumABILanguageRuntime::GetTypeInfo(), LookupTypeHere(), LookupTypeInModule(), lldb_private::npdb::SymbolFileNativePDB::ParseTypes(), and lldb_private::SymbolContext::SortTypeList().
GetTypeAtIndex()
TypeSP TypeList::GetTypeAtIndex (uint32_t idx)
Definition at line 66 of file TypeList.cpp.
References GetSize(), and m_types.
Referenced by lldb_private::TypeSystemClang::DumpFromSymbolFile(), lldb_private::ItaniumABILanguageRuntime::GetTypeInfo(), LookupTypeHere(), and lldb_private::SymbolContext::SortTypeList().
Insert()
void TypeList::Insert (const lldb::TypeSP & type)
Definition at line 27 of file TypeList.cpp.
References m_types.
Referenced by lldb_private::npdb::SymbolFileNativePDB::GetOrCreateType(), lldb_private::ItaniumABILanguageRuntime::GetTypeInfo(), SymbolFilePDB::GetTypes(), and lldb_private::SymbolContext::SortTypeList().
operator=()
const TypeList & lldb_private::TypeList::operator= (const TypeList &) private delete
References TypeList().
Types()
TypeIterable lldb_private::TypeList::Types () inline
Definition at line 44 of file TypeList.h.
References m_types.
Referenced by LookupTypeInModule().
Member Data Documentation
m_types
collection lldb_private::TypeList::m_types private
Definition at line 55 of file TypeList.h.
Referenced by Clear(), Dump(), ForEach(), ForEach(), GetSize(), GetTypeAtIndex(), Insert(), TypeList(), and Types().
The documentation for this class was generated from the following files:
TypeList.h
TypeList.cpp