LLDB: lldb_private::FileSpec Class Reference
lldb_private::FileSpec Class Reference
A file utility class.
#include "lldb/Utility/FileSpec.h"
Public Types
using Style = llvm::sys::path::Style
Public Member Functions
FileSpec ()
FileSpec (llvm::StringRef path, Style style=Style::native)
Constructor with path.
FileSpec (llvm::StringRef path, const llvm::Triple &triple)
bool DirectoryEquals (const FileSpec &other) const
bool FileEquals (const FileSpec &other) const
bool operator== (const FileSpec &rhs) const
Equal to operator.
bool operator!= (const FileSpec &rhs) const
Not equal to operator.
bool operator< (const FileSpec &rhs) const
Less than to operator.
operator bool () const
Convert to pointer operator.
bool operator! () const
Logical NOT operator.
void Clear ()
Clears the object state.
bool IsCaseSensitive () const
Case sensitivity of path.
void Dump (llvm::raw_ostream &s) const
Dump this object to a Stream.
llvm::json::Value ToJSON () const
Convert the filespec object to a json value.
Style GetPathStyle () const
const ConstString & GetDirectory () const
Directory string const get accessor.
void SetDirectory (ConstString directory)
Directory string set accessor.
void SetDirectory (llvm::StringRef directory)
void ClearDirectory ()
Clear the directory in this object.
const ConstString & GetFilename () const
Filename string const get accessor.
void SetFilename (ConstString filename)
Filename string set accessor.
void SetFilename (llvm::StringRef filename)
void ClearFilename ()
Clear the filename in this object.
bool IsSourceImplementationFile () const
Returns true if the filespec represents an implementation source file (files with a ".c", ".cpp", ".m", ".mm" (many more) extension).
bool IsRelative () const
Returns true if the filespec represents a relative path.
bool IsAbsolute () const
Returns true if the filespec represents an absolute path.
void MakeAbsolute (const FileSpec &dir)
Make the FileSpec absolute by treating it relative to dir.
void SetPath (llvm::StringRef p)
Temporary helper for FileSystem change.
size_t GetPath (char *path, size_t max_path_length, bool denormalize=true) const
Extract the full path to the file.
std::string GetPath (bool denormalize=true) const
Extract the full path to the file.
ConstString GetPathAsConstString (bool denormalize=true) const
Get the full path as a ConstString.
void GetPath (llvm::SmallVectorImpl< char > &path, bool denormalize=true) const
Extract the full path to the file.
llvm::StringRef GetFileNameExtension () const
Extract the extension of the file.
ConstString GetFileNameStrippingExtension () const
Return the filename without the extension part.
size_t MemorySize () const
Get the memory cost of this object.
void SetFile (llvm::StringRef path, Style style)
Change the file specified with a new path.
void SetFile (llvm::StringRef path, const llvm::Triple &triple)
Change the file specified with a new path.
FileSpec CopyByAppendingPathComponent (llvm::StringRef component) const
FileSpec CopyByRemovingLastPathComponent () const
void PrependPathComponent (llvm::StringRef component)
void PrependPathComponent (const FileSpec &new_path)
void AppendPathComponent (llvm::StringRef component)
void AppendPathComponent (const FileSpec &new_path)
bool RemoveLastPathComponent ()
Removes the last path component by replacing the current path with its parent.
std::vector< llvm::StringRef > GetComponents () const
Gets the components of the FileSpec's path.
Static Public Member Functions
static int Compare (const FileSpec &lhs, const FileSpec &rhs, bool full)
Compare two FileSpec objects.
static bool Equal (const FileSpec &a, const FileSpec &b, bool full)
static bool Match (const FileSpec &pattern, const FileSpec &file)
Match FileSpec pattern against FileSpec file.
static std::optional< Style > GuessPathStyle (llvm::StringRef absolute_path)
Attempt to guess path style for a given path string.
Protected Types
enum class Absolute : uint8_t { Calculate , Yes , No }
Protected Member Functions
void SetFile (llvm::StringRef path)
void PathWasModified ()
Called anytime m_directory or m_filename is changed to clear any cached state in this object.
Protected Attributes
ConstString m_directory
The unique'd directory path.
ConstString m_filename
The unique'd filename path.
Absolute m_absolute = Absolute::Calculate
Cache whether this path is absolute.
Style m_style
The syntax that this path uses. (e.g. Windows / Posix)
Detailed Description
A file utility class.
A file specification class that divides paths up into a directory and basename. These string values of the paths are put into uniqued string pools for fast comparisons and efficient memory usage.
Another reason the paths are split into the directory and basename is to allow efficient debugger searching. Often in a debugger the user types in the basename of the file, for example setting a breakpoint by file and line, or specifying a module (shared library) to limit the scope in which to execute a command. The user rarely types in a full path. When the paths are already split up, it makes it easy for us to compare only the basenames of a lot of file specifications without having to split up the file path each time to get to the basename.
Definition at line 57 of file FileSpec.h.
Member Typedef Documentation
Style
using lldb_private::FileSpec::Style = llvm::sys::path::Style
Definition at line 59 of file FileSpec.h.
Member Enumeration Documentation
Absolute
enum class lldb_private::FileSpec::Absolute : uint8_t strong protected
Enumerator
Calculate
Yes
No
Definition at line 426 of file FileSpec.h.
Constructor & Destructor Documentation
FileSpec() [1/3]
FileSpec::FileSpec ()
Definition at line 68 of file FileSpec.cpp.
References FileSpec(), and m_style.
Referenced by AppendPathComponent(), Compare(), CopyByAppendingPathComponent(), CopyByRemovingLastPathComponent(), DirectoryEquals(), Equal(), FileEquals(), FileSpec(), FileSpec(), MakeAbsolute(), Match(), operator!=(), operator<(), operator==(), and PrependPathComponent().
FileSpec() [2/3]
FileSpec::FileSpec (llvm::StringRef path, Style style = Style::native) explicit
Constructor with path.
Takes a path to a file which can be just a filename, or a full path. If path is not nullptr or empty, this function will call FileSpec::SetFile (const char *path).
Parameters
[in] path The full or partial path to a file.
[in] style The style of the path
See also
FileSpec::SetFile (const char *path)
Definition at line 71 of file FileSpec.cpp.
References m_style, and SetFile().
FileSpec() [3/3]
FileSpec::FileSpec (llvm::StringRef path, const llvm::Triple & triple) explicit
Definition at line 75 of file FileSpec.cpp.
References FileSpec().
Member Function Documentation
AppendPathComponent() [1/2]
void FileSpec::AppendPathComponent (const FileSpec & new_path)
Definition at line 461 of file FileSpec.cpp.
References AppendPathComponent(), FileSpec(), and GetPath().
AppendPathComponent() [2/2]
void FileSpec::AppendPathComponent (llvm::StringRef component)
Definition at line 454 of file FileSpec.cpp.
References GetPath(), m_style, and SetFile().
Referenced by AppendPathComponent(), AppendPathComponents(), BuildCpusSection(), BuildModulesSection(), BuildThreadsSection(), lldb_private::HostInfoBase::ComputeGlobalTempFileDirectory(), lldb_private::HostInfoBase::ComputeProcessTempFileDirectory(), lldb_private::HostInfoBase::ComputeUserLLDBHomeDirectory(), lldb_private::HostInfoMacOSX::ComputeUserPluginsDirectory(), CopyByAppendingPathComponent(), lldb_private::PipePosix::CreateWithUniqueName(), lldb_private::PlatformDarwin::FindBundleBinaryInExecSearchPaths(), lldb_private::DataFileCache::GetCacheFilePath(), GetCommandLineToolsLibraryPath(), GetDebugserverPath(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::GetDomainSocketPath(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwoSymbolFileForCompileUnit(), lldb_private::PlatformRemoteDarwinDevice::GetFileInSDK(), lldb_private::Platform::GetModuleCacheRoot(), lldb_private::PlatformDarwin::GetSDKDirectoryForModules(), lldb_private::PlatformDarwinDevice::GetSharedModuleWithLocalCache(), lldb_private::REPL::GetSourcePath(), lldb_private::Platform::Install(), lldb_private::Platform::LoadImage(), lldb_private::PlatformDarwin::LocateExecutable(), LookForDsymNextToExecutablePath(), lldb_private::HostInfoAndroid::ResolveLibraryPath(), SaveTraceBundleDescription(), lldb_private::CommandInterpreter::SaveTranscript(), lldb_private::ScriptInterpreterPython::SharedLibraryDirectoryHelper(), lldb_private::CommandInterpreter::SourceInitFileGlobal(), lldb_private::plugin::dwarf::SymbolFileDWARF::UpdateExternalModuleListIfNeeded(), lldb_private::PlatformDarwinDevice::UpdateSDKDirectoryInfosIfNeeded(), WriteContextSwitchTrace(), and WriteIntelPTTrace().
Clear()
void FileSpec::Clear ()
Clears the object state.
Clear this object by releasing both the directory and filename string values and reverting them to empty strings.
Definition at line 259 of file FileSpec.cpp.
References m_directory, m_filename, and PathWasModified().
Referenced by lldb_private::Platform::CallLocateModuleCallbackIfSet(), lldb_private::HostInfoBase::ComputeGlobalTempFileDirectory(), lldb_private::PlatformWindows::DoLoadImage(), lldb_private::Host::GetBundleDirectory(), GetDebugserverPath(), lldb_private::PlatformRemoteDarwinDevice::GetFileInSDK(), lldb_private::File::GetFileSpec(), lldb_private::NativeFile::GetFileSpec(), lldb_private::process_freebsd::NativeProcessFreeBSD::GetLoadedModuleFileSpec(), lldb_private::process_linux::NativeProcessLinux::GetLoadedModuleFileSpec(), lldb_private::process_netbsd::NativeProcessNetBSD::GetLoadedModuleFileSpec(), lldb_private::DynamicLoader::GetSharedCacheInformation(), LocateDSYMInVincinityOfExecutable(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableObjectFile(), LocateMacOSXFilesUsingDebugSymbols(), and SetFile().
ClearDirectory()
void FileSpec::ClearDirectory ()
Clear the directory in this object.
Definition at line 367 of file FileSpec.cpp.
References m_directory, and PathWasModified().
Referenced by lldb_private::SymbolContext::FindBestGlobalDataSymbol(), lldb_private::ClangExpressionDeclMap::GetSymbolAddress(), ObjectFileMachO::ParseSymtab(), lldb_private::minidump::ProcessMinidump::ReadModuleList(), and lldb_private::Symbol::ResolveReExportedSymbolInModuleSpec().
ClearFilename()
void FileSpec::ClearFilename ()
Clear the filename in this object.
Definition at line 362 of file FileSpec.cpp.
References m_filename, and PathWasModified().
Referenced by lldb::SBFileSpec::GetDirectory().
Compare()
int FileSpec::Compare (const FileSpec & lhs, const FileSpec & rhs, bool full) static
Compare two FileSpec objects.
If full is true, then both the directory and the filename must match. If full is false, then the directory names for lhs and rhs are only compared if they are both not empty. This allows a FileSpec object to only contain a filename and it can match FileSpec objects that have matching filenames with different paths.
Parameters
[in] lhs A const reference to the Left Hand Side object to compare.
[in] rhs A const reference to the Right Hand Side object to compare.
[in] full If true, then both the directory and filenames will have to match for a compare to return zero (equal to). If false and either directory from lhs or rhs is empty, then only the filename will be compared, else a full comparison is done.
Returns
-1 if lhs is less than rhs, 0 if lhs is equal to rhs, 1 if lhs is greater than rhs
Definition at line 273 of file FileSpec.cpp.
References lldb_private::ConstString::Compare(), FileSpec(), IsCaseSensitive(), m_directory, and m_filename.
Referenced by lldb_private::Declaration::Compare(), lldb_private::LineEntry::Compare(), lldb_private::Declaration::FileAndLineEqual(), and operator<().
CopyByAppendingPathComponent()
FileSpec FileSpec::CopyByAppendingPathComponent (llvm::StringRef component) const
Definition at line 425 of file FileSpec.cpp.
References AppendPathComponent(), and FileSpec().
Referenced by lldb_private::HostInfoMacOSX::ComputeSupportExeDirectory(), lldb_private::Debugger::Debugger(), lldb_private::Diagnostics::DumpDiangosticsLog(), findMatchingPDBFilePath(), ObjectFileMachO::GetDependentModules(), lldb_private::platform_android::PlatformAndroid::GetFile(), ObjectFileELF::GetGnuDebugDataObjectFile(), lldb_private::line_editor::EditlineHistory::GetHistoryFilePath(), GetHomeREPLInitFile(), lldb_private::IRExecutionUnit::GetRunnableInfo(), lldb_private::platform_android::PlatformAndroid::PutFile(), and lldb_protocol::mcp::ServerInfo::Write().
CopyByRemovingLastPathComponent()
FileSpec FileSpec::CopyByRemovingLastPathComponent () const
Definition at line 431 of file FileSpec.cpp.
References FileSpec(), GetPath(), and m_style.
Referenced by findMatchingPDBFilePath(), ObjectFileMachO::GetDependentModules(), lldb_private::CommandInterpreter::HandleCommandsFromFile(), and MakeCacheFolderForFile().
DirectoryEquals()
bool FileSpec::DirectoryEquals (const FileSpec & other) const
Definition at line 228 of file FileSpec.cpp.
References lldb_private::ConstString::Equals(), FileSpec(), IsCaseSensitive(), and m_directory.
Referenced by operator==().
Dump()
void FileSpec::Dump (llvm::raw_ostream & s) const
Dump this object to a Stream.
Dump the object to the supplied stream s. If the object contains a valid directory name, it will be displayed followed by a directory delimiter, and the filename.
Parameters
[in] s The stream to which to dump the object description.
Definition at line 325 of file FileSpec.cpp.
References GetPath(), m_filename, and m_style.
Referenced by DumpFullpath(), lldb_private::LineEntry::DumpStopContext(), lldb_private::FormatEntity::FormatFileSpec(), lldb_private::Module::LoadScriptingResourceInTarget(), lldb_private::operator<<(), ToJSON(), and UUIDsMatch().
Equal()
bool FileSpec::Equal (const FileSpec & a, const FileSpec & b, bool full) static
Definition at line 294 of file FileSpec.cpp.
References FileEquals(), FileSpec(), and GetDirectory().
Referenced by lldb_private::BreakpointResolverFileLine::DeduceSourceMapping(), FindFileIndex(), and IsCompatible().
FileEquals()
bool FileSpec::FileEquals (const FileSpec & other) const
Definition at line 233 of file FileSpec.cpp.
References lldb_private::ConstString::Equals(), FileSpec(), IsCaseSensitive(), and m_filename.
Referenced by Equal(), IsCompatible(), Match(), and operator==().
GetComponents()
std::vector< llvm::StringRef > FileSpec::GetComponents () const
Gets the components of the FileSpec's path.
For example, given the path: /System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
This function returns: {"System", "Library", "PrivateFrameworks", "UIFoundation.framework", "UIFoundation"}
Returns
A std::vector of llvm::StringRefs for each path component. The lifetime of the StringRefs is tied to the lifetime of the FileSpec.
Definition at line 475 of file FileSpec.cpp.
References m_directory, m_filename, and m_style.
Referenced by lldb_private::PlatformDarwin::FindBundleBinaryInExecSearchPaths().
GetDirectory()
const ConstString & lldb_private::FileSpec::GetDirectory () const inline
Directory string const get accessor.
Returns
A const reference to the directory string object.
Definition at line 234 of file FileSpec.h.
References m_directory.
Referenced by lldb_private::CppModuleConfiguration::analyzeFile(), BuildModulesSection(), lldb_private::SourceManager::File::CommonInitializerImpl(), lldb_private::HostInfoBase::ComputePathRelativeToLibrary(), lldb_private::HostInfoBase::ComputeSharedLibraryDirectory(), lldb_private::HostInfoMacOSX::ComputeSupportExeDirectory(), lldb_private::HostInfoPosix::ComputeSupportExeDirectory(), lldb_private::BreakpointResolverFileLine::DeduceSourceMapping(), CommandObjectTargetCreate::DoExecute(), DumpDirectory(), DumpFile(), CommandObjectSourceInfo::DumpFileLinesInCompUnit(), Equal(), FindFileIndex(), GetChildFileSpecificationsFromThin(), ObjectFileMachO::GetDependentModules(), llvm::DenseMapInfo< lldb_private::FileSpec >::getHashValue(), lldb_private::Target::GetOrCreateModule(), lldb_private::PlatformDarwinDevice::GetSharedModuleWithLocalCache(), lldb_private::Platform::Install(), IsCompatible(), lldb_private::Trace::LoadPostMortemTraceFromFile(), LocateExecutableScriptingResourcesFromDSYM(), lldb_private::SymbolLocatorDefault::LocateExecutableSymbolFile(), Match(), CommandObjectSourceList::SourceInfo::operator<(), resolve_tilde(), and lldb_private::FileSystem::ResolveExecutableLocation().
GetFilename()
const ConstString & lldb_private::FileSpec::GetFilename () const inline
Filename string const get accessor.
Returns
A const reference to the filename string object.
Definition at line 250 of file FileSpec.h.
References m_filename.
Referenced by CommandObjectTargetSymbolsAdd::AddModuleSymbols(), lldb_private::VariableAnnotator::AnnotateStructured(), lldb_private::AppleObjCRuntime::AppleIsModuleObjCLibrary(), CanModuleBeGNUstepObjCLibrary(), lldb_private::SourceManager::File::CommonInitializerImpl(), ObjectFileCOFF::CreateInstance(), lldb_private::SymbolLocatorDebugSymbols::DownloadObjectAndSymbolFile(), lldb_private::Target::Dump(), DumpBasename(), ObjectFileELF::DumpDependentModules(), DumpFile(), CommandObjectSourceInfo::DumpFileLinesInCompUnit(), lldb_private::Section::DumpName(), lldb_private::LineEntry::DumpStopContext(), FindFileIndex(), findMatchingPDBFilePath(), lldb_private::FormatEntity::FormatFileSpec(), lldb_private::ModuleCache::Get(), GetCoffUUID(), lldb_private::PlatformRemoteDarwinDevice::GetConnectedSDKIndex(), lldb::SBProcess::GetDescription(), lldb_private::Address::GetDescription(), lldb_private::BreakpointLocation::GetDescription(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwoSymbolFileForCompileUnit(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwpSymbolFile(), lldb_private::Target::GetEntryPointAddress(), getFileName(), GetFreeBSDProcessArgs(), llvm::DenseMapInfo< lldb_private::FileSpec >::getHashValue(), lldb_private::ScriptedProcess::GetLoadedDynamicLibrariesInfos(), lldb_private::process_freebsd::NativeProcessFreeBSD::GetLoadedModuleFileSpec(), lldb_private::process_linux::NativeProcessLinux::GetLoadedModuleFileSpec(), lldb_private::process_netbsd::NativeProcessNetBSD::GetLoadedModuleFileSpec(), GetMacOSXProcessArgs(), lldb_private::Breakpoint::GetMatchingFileLine(), ObjectFileCOFF::GetModuleSpecifications(), ObjectFileELF::GetModuleSpecifications(), ObjectFilePECOFF::GetModuleSpecifications(), GetNetBSDProcessArgs(), lldb_private::ObjectFile::GetObjectName(), GetOpenBSDProcessArgs(), lldb_private::Target::GetOrCreateModule(), lldb_private::PlatformDarwin::GetSDKPathFromDebugInfo(), lldb_private::ModuleList::GetSharedModule(), lldb_private::PlatformDarwinDevice::GetSharedModuleWithLocalCache(), lldb_private::Args::GetShellSafeArgument(), lldb_private::SymbolFileOnDemand::GetSymbolFileName(), lldb_private::CommandInterpreter::HandleCommandsFromFile(), lldb_private::Platform::Install(), lldb_private::Thread::JumpToLine(), lldb_private::formatters::LibcxxFunctionSummaryProvider(), lldb_private::Platform::LoadImage(), lldb_private::Platform::LoadImageUsingPaths(), LoadPluginCallback(), LocateDSYMInVincinityOfExecutable(), lldb_private::SymbolLocatorDefault::LocateExecutableObjectFile(), LocateExecutableScriptingResourcesFromDSYM(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableSymbolFile(), lldb_private::SymbolLocatorDefault::LocateExecutableSymbolFile(), LookForDsymNextToExecutablePath(), Match(), lldb_private::InstrumentationRuntime::ModulesDidLoad(), CommandObjectSourceList::SourceInfo::operator<(), ObjectFileMachO::ParseSymtab(), lldb_private::ModuleCache::Put(), lldb_private::Process::ReadModuleFromMemory(), RecurseCopy_Callback(), lldb_private::RegisterAssertFrameRecognizer(), lldb_private::Module::ReportWarningOptimization(), lldb_private::FileSystem::Resolve(), lldb_private::FileSystem::ResolveExecutableLocation(), and lldb_private::XcodeSDK::SDKSupportsModules().
GetFileNameExtension()
llvm::StringRef FileSpec::GetFileNameExtension () const
Extract the extension of the file.
Returns a ConstString that represents the extension of the filename for this FileSpec object. If this object does not represent a file, or the filename has no extension, ConstString(nullptr) is returned. The dot ('.') character is the first character in the returned string.
Returns
Returns the extension of the file as a StringRef.
Definition at line 410 of file FileSpec.cpp.
References m_filename, and m_style.
Referenced by CommandObjectTargetModulesDumpClangPCMInfo::DoExecute(), IsSourceImplementationFile(), lldb_private::Lua::LoadModule(), LoadPluginCallback(), LoadPluginCallback(), and lldb_private::ScriptInterpreterPython::SharedLibraryDirectoryHelper().
GetFileNameStrippingExtension()
ConstString FileSpec::GetFileNameStrippingExtension () const
Return the filename without the extension part.
Returns a ConstString that represents the filename of this object without the extension part (e.g. for a file named "foo.bar", "foo" is returned)
Returns
Returns the filename without extension as a ConstString object.
Definition at line 414 of file FileSpec.cpp.
References m_filename, and m_style.
Referenced by CommandObjectTargetSymbolsAdd::AddModuleSymbols(), PluginInfo::Create(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwpSymbolFile(), lldb_private::Lua::LoadModule(), and LocateExecutableScriptingResourcesFromDSYM().
GetPath() [1/3]
std::string FileSpec::GetPath (bool denormalize = true) const
Extract the full path to the file.
Extract the directory and path into a std::string, which is returned.
Returns
Returns a std::string with the directory and filename concatenated.
Definition at line 384 of file FileSpec.cpp.
References GetPath().
GetPath() [2/3]
size_t FileSpec::GetPath (char * path, size_t max_path_length, bool denormalize = true) const
Extract the full path to the file.
Extract the directory and path into a fixed buffer. This is needed as the directory and path are stored in separate string values.
Parameters
[out] path The buffer in which to place the extracted full path.
[in] max_path_length The maximum length of path.
Returns
Returns the number of characters that would be needed to properly copy the full path into path. If the returned number is less than max_path_length, then the path is properly copied and terminated. If the return value is >= max_path_length, then the path was truncated (but is still NULL terminated).
Definition at line 374 of file FileSpec.cpp.
References GetPath().
Referenced by lldb_private::PlatformDarwin::AddClangModuleCompilationOptionsForSDKType(), CommandObjectTargetSymbolsAdd::AddModuleSymbols(), AddPosixSpawnFileAction(), lldb_private::Block::AddRange(), lldb_private::CppModuleConfiguration::analyzeFile(), AppendPathComponent(), AppendPathComponent(), lldb_private::Process::Attach(), BuildCpusSection(), lldb_private::process_gdb_remote::ProcessGDBRemote::BuildDynamicRegisterInfo(), BuildModulesSection(), BuildThreadsSection(), SymbolFilePDB::CalculateAbilities(), lldb_private::Platform::CalculateMD5(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::CalculateMD5(), lldb_private::Platform::CallLocateModuleCallbackIfSet(), lldb_private::TargetProperties::CheckJITObjectsDir(), lldb_private::ComputeClangResourceDirectory(), lldb_private::HostInfoBase::ComputeGlobalTempFileDirectory(), lldb_private::HostInfoMacOSX::ComputeHeaderDirectory(), lldb_private::HostInfoPosix::ComputeHeaderDirectory(), lldb_private::HostInfoBase::ComputePathRelativeToLibrary(), lldb_private::HostInfoBase::ComputeProcessTempFileDirectory(), lldb_private::HostInfoMacOSX::ComputeSupportExeDirectory(), lldb_private::HostInfoMacOSX::ComputeSystemPluginsDirectory(), lldb_private::HostInfoPosix::ComputeSystemPluginsDirectory(), lldb_private::ProcessLaunchInfo::ConvertArgumentsForLaunchingInShell(), CopyByRemovingLastPathComponent(), lldb_private::ClangModulesDeclVendor::Create(), PluginInfo::Create(), lldb_private::Target::CreateBreakpointsFromFile(), lldb_private::FileSystem::CreateDataBuffer(), lldb_private::minidump::ProcessMinidump::CreateInstance(), lldb_private::wasm::ObjectFileWasm::CreateInstance(), ObjectFileCOFF::CreateInstance(), ProcessElfCore::CreateInstance(), ProcessFreeBSDKernelCore::CreateInstance(), ProcessMachCore::CreateInstance(), SymbolVendorMacOSX::CreateInstance(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::CreateSymlink(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::CreateSymlink(), lldb_private::PipePosix::CreateWithUniqueName(), lldb_private::FileSystem::CreateWritableDataBuffer(), lldb_private::Debugger::Debugger(), lldb_private::DebuggerThread::DebuggerThreadLaunchRoutine(), lldb_private::DebuggerThread::DebugLaunch(), lldb_private::PlatformQemuUser::DebugProcess(), lldb_private::PlatformWasm::DebugProcess(), DefaultComputeClangResourceDirectory(), lldb_private::FileSystem::DirBegin(), CommandObjectMemoryRead::DoExecute(), CommandObjectProcessSaveCore::DoExecute(), CommandObjectSettingsWrite::DoExecute(), CommandObjectTargetCreate::DoExecute(), CommandObjectTargetModulesAdd::DoExecute(), CommandObjectTargetModulesLoad::DoExecute(), CommandObjectTargetSymbolsAdd::DoExecute(), CommandObjectTargetVariable::DoExecute(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoLaunch(), lldb_private::PlatformWindows::DoLoadImage(), lldb_private::Platform::DownloadModuleSlice(), lldb_private::platform_android::PlatformAndroid::DownloadModuleSlice(), lldb_private::SymbolLocatorDebugSymbols::DownloadObjectAndSymbolFile(), lldb_private::Diagnostics::Dump(), Dump(), lldb_private::Symtab::Dump(), lldb_private::Diagnostics::DumpDiangosticsLog(), DumpFullpath(), DumpTargetInfo(), lldb_private::FileSystem::Exists(), lldb_private::PlatformDarwin::FindBundleBinaryInExecSearchPaths(), lldb_private::PathMappingList::FindFile(), findMatchingPDBFilePath(), lldb_private::DynamicLoader::FindModuleViaTarget(), lldb_private::ObjectFile::FindPlugin(), lldb_private::PlatformDarwin::FindSDKInXcodeForModules(), lldb_private::SymbolLocatorDebugSymbols::FindSymbolFileInBundle(), lldb_private::FileSystem::GetByteSize(), lldb_private::GetClangResourceDir(), lldb_private::PlatformDarwinDevice::GetDeviceSupportDirectoryForOSVersion(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::GetDomainSocketPath(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwoSymbolFileForCompileUnit(), GetEnvDeveloperDir(), lldb_private::platform_android::PlatformAndroid::GetFile(), PlatformPOSIX::GetFile(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetFileExists(), lldb_private::NativeProcessWindows::GetFileLoadAddress(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetFileLoadAddress(), lldb_private::Platform::GetFilePermissions(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::GetFilePermissions(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetFilePermissions(), lldb_private::Platform::GetFileSize(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetFileSize(), lldb_private::line_editor::EditlineHistory::GetHistoryFilePath(), lldb_private::ScriptInterpreterPython::GetInterpreterInfo(), lldb_private::NativeProcessWindows::GetLoadedModuleFileSpec(), lldb_private::InstrumentationRuntimeTSan::GetLocationDescription(), lldb_private::FileSystem::GetModificationTime(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetModuleByCompUnitInfo(), lldb_private::PlatformDarwin::GetModuleFromSharedCaches(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetModuleInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::GetModuleInfo(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::GetModuleSpec(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetModuleSpec(), lldb_private::ObjectFile::GetModuleSpecifications(), lldb_private::ObjectFilePDB::GetModuleSpecifications(), ObjectFileELF::GetModuleSpecifications(), GetModuleSpecInfoFromUUIDDictionary(), lldb_private::Target::GetOrCreateModule(), lldb_private::SymbolContext::GetParentOfInlinedScope(), GetPath(), GetPath(), GetPathAsConstString(), lldb_private::FileSystem::GetPermissions(), lldb_private::FileSystem::GetPermissions(), lldb_private::ScriptInterpreterPython::GetPythonDir(), GetRelativePath(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::GetRemoteWorkingDirectory(), lldb_private::platform_linux::PlatformLinux::GetResumeCountForLaunchInfo(), lldb_private::platform_netbsd::PlatformNetBSD::GetResumeCountForLaunchInfo(), lldb_private::PlatformDarwin::GetResumeCountForLaunchInfo(), lldb_private::IRExecutionUnit::GetRunnableInfo(), lldb_private::PlatformMacOSX::GetSDKDirectory(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetSeparateDebugInfo(), lldb_private::ModuleList::GetSharedModule(), lldb_private::PlatformDarwin::GetSharedModule(), lldb_private::PlatformRemoteDarwinDevice::GetSharedModule(), lldb_private::PlatformDarwinDevice::GetSharedModuleWithLocalCache(), lldb_private::REPL::GetSourcePath(), lldb_private::FileSystem::GetStatus(), lldb_private::PlatformRemoteDarwinDevice::GetStatus(), lldb_private::ProcessLauncherWindows::GetStdioHandle(), lldb_private::PlatformAppleSimulator::GetSymbolFile(), lldb_private::PlatformRemoteDarwinDevice::GetSymbolFile(), lldb_private::Value::GetValueAsData(), lldb_private::HostInfoMacOSX::GetXcodeContentsDirectory(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_jModulesInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qGetWorkingDir(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qModuleInfo(), lldb_private::CommandInterpreter::HandleCommandsFromFile(), HandleFileAction(), HexagonDYLDRendezvous::HexagonDYLDRendezvous(), lldb::SBPlatform::Install(), lldb_private::Platform::Install(), IsAbsolute(), lldb_private::FileSystem::IsDirectory(), lldb_private::FileSystem::IsLocal(), lldb_private::Target::Launch(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::LaunchGDBServer(), lldb_private::Process::LaunchPrivate(), lldb_private::Platform::LaunchProcess(), lldb_private::ProcessDebugger::LaunchProcess(), lldb_private::ProcessLauncherWindows::LaunchProcess(), LaunchProcessPosixSpawn(), LaunchProcessXPC(), lldb_private::Trace::LoadPostMortemTraceFromFile(), lldb_private::Module::LoadScriptingResourceInTarget(), LocateDSYMInVincinityOfExecutable(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableObjectFile(), lldb_private::PlatformDarwin::LocateExecutableScriptingResources(), LocateExecutableScriptingResourcesFromDSYM(), lldb_private::SymbolLocatorDefault::LocateExecutableSymbolFile(), LocateMacOSXFilesUsingDebugSymbols(), lldb_private::ModuleList::LogUUIDAndPaths(), lldb_private::FileSystem::MakeAbsolute(), MakeAbsoluteAndRemap(), MakeCacheFolderForFile(), lldb_private::Platform::MakeDirectory(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::MakeDirectory(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::MakeDirectory(), lldb_private::ObjectFile::MapFileData(), ObjectFileELF::MapFileDataWritable(), ObjectFileXCOFF::MapFileDataWritable(), lldb_private::Module::Module(), lldb_private::Trace::OnDataFileRead(), lldb_private::FileSystem::Open(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::OpenFile(), ObjectFilePECOFF::ParseDependentModules(), lldb_private::StructuredData::ParseJSONFromFile(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseSupportFiles(), PrependPathComponent(), PrependPathComponent(), lldb_private::platform_android::AdbSyncService::PullFileImpl(), lldb_private::platform_android::AdbSyncService::PushFileImpl(), lldb::SBPlatform::Put(), lldb_private::ModuleCache::Put(), lldb_private::Platform::PutFile(), lldb_private::platform_android::PlatformAndroid::PutFile(), PlatformPOSIX::PutFile(), lldb_private::FileSystem::Readable(), lldb_private::FileSystem::Readlink(), lldb_private::Process::ReadModuleFromMemory(), RecurseCopy_Callback(), lldb_private::FileSystem::RemoveFile(), RemoveLastPathComponent(), lldb_private::DebuggerStats::ReportStatistics(), lldb_private::FileSystem::Resolve(), lldb_private::RemoteAwarePlatform::ResolveExecutable(), DynamicLoaderPOSIXDYLD::ResolveExecutableModule(), lldb_private::ZipFileResolver::ResolveSharedLibraryPath(), lldb_private::Module::ResolveSymbolContextsForFileSpec(), lldb_private::FileSystem::ResolveSymbolicLink(), lldb_private::RealpathPrefixes::ResolveSymlinks(), lldb_private::PathMappingList::ReverseRemapPath(), lldb_private::Host::RunShellCommand(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::RunShellCommand(), ObjectFileMachO::SaveCore(), lldb_private::trace_intel_pt::TraceIntelPTBundleSaver::SaveToDisk(), SaveTraceBundleDescription(), lldb_private::CommandInterpreter::SaveTranscript(), lldb_private::Target::SerializeBreakpointsToFile(), lldb_private::SearchFilter::SerializeFileSpecList(), lldb_private::BreakpointResolverAddress::SerializeToStructuredData(), lldb_private::ProcessInfo::SetExecutableFile(), lldb_private::Platform::SetFilePermissions(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::SetFilePermissions(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetFilePermissions(), ObjectFileMachO::SetLoadAddress(), CommandObjectSourceList::CommandOptions::SetOptionValue(), lldb_private::TargetProperties::SetProcessLaunchInfo(), lldb_private::Symbol::SetReExportedSymbolSharedLibrary(), lldb_private::Platform::SetRemoteWorkingDirectory(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::SetRemoteWorkingDirectory(), lldb_private::SectionLoadList::SetSectionUnloaded(), lldb_private::SectionLoadList::SetSectionUnloaded(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetSTDERR(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetSTDIN(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetSTDOUT(), lldb_private::Module::SetSymbolFileFileSpec(), SetupModuleHeaderPaths(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetWorkingDir(), lldb_private::Platform::SetWorkingDirectory(), lldb_private::HostInfoMacOSX::SharedCacheIndexFiles(), lldb_private::platform_android::AdbClient::ShellToFile(), lldb_private::CommandInterpreter::SourceInitFileCwd(), lldb_private::CommandInterpreter::SourceInitFileHome(), lldb_private::platform_android::AdbSyncService::StatImpl(), lldb::SBThread::StepOverUntil(), lldb_private::FileSystem::Symlink(), lldb_private::Platform::Unlink(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::Unlink(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::Unlink(), lldb_private::DynamicLoaderDarwin::UnloadModuleSections(), lldb_private::plugin::dwarf::SymbolFileDWARF::UpdateExternalModuleListIfNeeded(), lldb_private::PlatformDarwinDevice::UpdateSDKDirectoryInfosIfNeeded(), lldb_private::ModuleListProperties::UpdateSymlinkMappings(), lldb_protocol::mcp::ServerInfo::Write(), and WriteBytesToDisk().
GetPath() [3/3]
void FileSpec::GetPath (llvm::SmallVectorImpl< char > & path, bool denormalize = true) const
Extract the full path to the file.
Extract the directory and path into an llvm::SmallVectorImpl<>
Definition at line 394 of file FileSpec.cpp.
References m_directory, m_filename, and m_style.
GetPathAsConstString()
ConstString FileSpec::GetPathAsConstString (bool denormalize = true) const
Get the full path as a ConstString.
This method should only be used when you need a ConstString or the const char * from a ConstString to ensure permanent lifetime of C string. Anyone needing the path temporarily should use the GetPath() method that returns a std:string.
Definition at line 390 of file FileSpec.cpp.
References GetPath().
Referenced by lldb_private::HostInfoBase::ComputeGlobalTempFileDirectory(), lldb_private::HostInfoBase::ComputeProcessTempFileDirectory(), lldb_private::HostInfoBase::ComputeUserHomeDirectory(), lldb_private::HostInfoBase::ComputeUserLLDBHomeDirectory(), lldb_private::HostInfoMacOSX::ComputeUserPluginsDirectory(), lldb_private::DynamicLoaderDarwin::FindTargetModuleForImageInfo(), lldb::SBFileSpec::GetDirectory(), lldb_private::platform_android::PlatformAndroid::GetFile(), lldb_private::PlatformDarwin::GetModuleFromSharedCaches(), lldb_private::Platform::Install(), lldb_private::PlatformDarwin::LocateExecutable(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableObjectFile(), LocateMacOSXFilesUsingDebugSymbols(), and RecurseCopy_Callback().
GetPathStyle()
FileSpec::Style FileSpec::GetPathStyle () const
Definition at line 340 of file FileSpec.cpp.
References m_style.
Referenced by llvm::DenseMapInfo< lldb_private::FileSpec >::getHashValue(), lldb_private::Platform::LoadImageUsingPaths(), lldb_private::FileSystem::MakeAbsolute(), and lldb_private::RealpathPrefixes::ResolveSymlinks().
GuessPathStyle()
std::optional< FileSpec::Style > FileSpec::GuessPathStyle (llvm::StringRef absolute_path) static
Attempt to guess path style for a given path string.
It returns a style, if it was able to make a reasonable guess, or std::nullopt if it wasn't. The guess will be correct if the input path was a valid absolute path on the system which produced it. On other paths the result of this function is unreliable (e.g. "c:\foo.txt" is a valid relative posix path).
Definition at line 310 of file FileSpec.cpp.
Referenced by lldb_private::plugin::dwarf::DWARFUnit::ComputeCompDirAndGuessPathStyle(), findMatchingPDBFilePath(), lldb_private::breakpad::SymbolFileBreakpad::ParseFileRecords(), lldb_private::PathMappingList::RemapPath(), and lldb_private::PathMappingList::ReverseRemapPath().
IsAbsolute()
bool FileSpec::IsAbsolute () const
Returns true if the filespec represents an absolute path.
Returns
true if the filespec represents an absolute path, false otherwise.
Definition at line 518 of file FileSpec.cpp.
References Calculate, GetPath(), m_absolute, m_style, No, and Yes.
Referenced by lldb_private::HostInfoPosix::ComputeSupportExeDirectory(), IsRelative(), lldb_private::Platform::LoadImageUsingPaths(), and lldb_private::SymbolLocatorDefault::LocateExecutableSymbolFile().
IsCaseSensitive()
bool lldb_private::FileSpec::IsCaseSensitive () const inline
Case sensitivity of path.
Returns
true if the file path is case sensitive (POSIX), false if case insensitive (Windows).
Definition at line 206 of file FileSpec.h.
References m_style.
Referenced by Compare(), lldb_private::BreakpointResolverFileLine::DeduceSourceMapping(), DirectoryEquals(), FileEquals(), FindFileIndex(), IsCompatible(), and lldb_private::RealpathPrefixes::ResolveSymlinks().
IsRelative()
bool FileSpec::IsRelative () const
Returns true if the filespec represents a relative path.
Returns
true if the filespec represents a relative path, false otherwise.
Definition at line 514 of file FileSpec.cpp.
References IsAbsolute().
Referenced by lldb_private::ProcessLaunchInfo::ConvertArgumentsForLaunchingInShell(), lldb_private::BreakpointResolverFileLine::DeduceSourceMapping(), CommandObjectCommandsSource::DoExecute(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwoSymbolFileForCompileUnit(), lldb_private::platform_android::PlatformAndroid::GetFile(), IsCompatible(), MakeAbsolute(), lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::NormalizePath(), lldb_private::platform_android::PlatformAndroid::PutFile(), lldb_private::PathMappingList::RemapPath(), and lldb_private::plugin::dwarf::SymbolFileDWARF::UpdateExternalModuleListIfNeeded().
IsSourceImplementationFile()
bool FileSpec::IsSourceImplementationFile () const
Returns true if the filespec represents an implementation source file (files with a ".c", ".cpp", ".m", ".mm" (many more) extension).
Returns
true if the FileSpec represents an implementation source file, false otherwise.
true if the filespec represents an implementation source file, false otherwise.
Definition at line 501 of file FileSpec.cpp.
References lldb_private::RegularExpression::Execute(), and GetFileNameExtension().
Referenced by lldb_private::Target::CreateBreakpoint(), and CommandObjectSourceList::DoExecute().
MakeAbsolute()
void FileSpec::MakeAbsolute (const FileSpec & dir)
Make the FileSpec absolute by treating it relative to dir.
Absolute FileSpecs are never changed by this function.
Definition at line 537 of file FileSpec.cpp.
References FileSpec(), IsRelative(), and PrependPathComponent().
Referenced by CommandObjectCommandsSource::DoExecute(), MakeAbsoluteAndRemap(), and lldb_private::CommandInterpreter::SourceInitFileGlobal().
Match()
bool FileSpec::Match (const FileSpec & pattern, const FileSpec & file) static
Match FileSpec pattern against FileSpec file.
If pattern has a directory component, then the file must have the same directory component. Otherwise, just it matches just the filename. An empty pattern matches everything.
Definition at line 301 of file FileSpec.cpp.
References FileEquals(), FileSpec(), GetDirectory(), and GetFilename().
Referenced by CommandObjectSourceInfo::DumpLinesInSymbolContexts(), lldb_private::Module::FindCompileUnits(), lldb_private::TargetList::FindTargetWithExecutableAndArchitecture(), lldb_private::ThreadPlanStepInRange::FrameMatchesAvoidCriteria(), lldb_private::ModuleSpec::Matches(), lldb_private::Module::MatchesModuleSpec(), lldb_private::SearchFilterByModule::ModulePasses(), lldb_private::SearchFilterByModule::ModulePasses(), lldb_private::CompileUnit::ResolveSymbolContext(), lldb_private::npdb::SymbolFileNativePDB::ResolveSymbolContext(), lldb_private::SearchFilterByModule::Search(), and lldb_private::SymbolContextSpecifier::SymbolContextMatches().
MemorySize()
size_t FileSpec::MemorySize () const
Get the memory cost of this object.
Return the size in bytes that this object takes in memory. This returns the size in bytes of this object, not any shared string values it may refer to.
Returns
The number of bytes that this object occupies in memory.
Definition at line 420 of file FileSpec.cpp.
References m_directory, and m_filename.
Referenced by lldb_private::ScriptedProcess::GetLoadedDynamicLibrariesInfos().
operator bool()
FileSpec::operator bool () const explicit
Convert to pointer operator.
This allows code to check a FileSpec object to see if it contains anything valid using code such as:
FileSpec file_spec(...);
if (file_spec)
{ ...
Returns
A pointer to this object if either the directory or filename is valid, nullptr otherwise.
Definition at line 219 of file FileSpec.cpp.
References m_directory, and m_filename.
operator!()
bool FileSpec::operator! () const
Logical NOT operator.
This allows code to check a FileSpec object to see if it is invalid using code such as:
FileSpec file_spec(...);
if (!file_spec)
{ ...
Returns
Returns true if the object has an empty directory and filename, false otherwise.
Definition at line 226 of file FileSpec.cpp.
References m_directory, and m_filename.
operator!=()
bool FileSpec::operator!= (const FileSpec & rhs) const
Not equal to operator.
Tests if this object is not equal to rhs.
Parameters
[in] rhs A const FileSpec object reference to compare this object to.
Returns
true if this object is equal to rhs, false otherwise.
Definition at line 244 of file FileSpec.cpp.
References FileSpec().
operator<()
bool FileSpec::operator< (const FileSpec & rhs) const
Less than to operator.
Tests if this object is less than rhs.
Parameters
[in] rhs A const FileSpec object reference to compare this object to.
Returns
true if this object is less than rhs, false otherwise.
Definition at line 247 of file FileSpec.cpp.
References Compare(), and FileSpec().
operator==()
bool FileSpec::operator== (const FileSpec & rhs) const
Equal to operator.
Tests if this object is equal to rhs.
Parameters
[in] rhs A const FileSpec object reference to compare this object to.
Returns
true if this object is equal to rhs, false otherwise.
Definition at line 239 of file FileSpec.cpp.
References DirectoryEquals(), FileEquals(), and FileSpec().
PathWasModified()
void lldb_private::FileSpec::PathWasModified () inline protected
Called anytime m_directory or m_filename is changed to clear any cached state in this object.
Definition at line 424 of file FileSpec.h.
References Calculate, and m_absolute.
Referenced by Clear(), ClearDirectory(), ClearFilename(), SetDirectory(), SetDirectory(), SetFilename(), and SetFilename().
PrependPathComponent() [1/2]
void FileSpec::PrependPathComponent (const FileSpec & new_path)
Definition at line 450 of file FileSpec.cpp.
References FileSpec(), GetPath(), and PrependPathComponent().
PrependPathComponent() [2/2]
void FileSpec::PrependPathComponent (llvm::StringRef component)
Definition at line 440 of file FileSpec.cpp.
References GetPath(), m_style, and SetFile().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwoSymbolFileForCompileUnit(), lldb_private::Platform::GetSharedModule(), lldb_private::SymbolLocatorDefault::LocateExecutableSymbolFile(), MakeAbsolute(), lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::NormalizePath(), and PrependPathComponent().
RemoveLastPathComponent()
bool FileSpec::RemoveLastPathComponent ()
Removes the last path component by replacing the current path with its parent.
When the current path has no parent, this is a no-op.
Returns
A boolean value indicating whether the path was updated.
Definition at line 465 of file FileSpec.cpp.
References GetPath(), m_style, and SetFile().
Referenced by SymbolVendorMacOSX::CreateInstance(), GetModuleSpecInfoFromUUIDDictionary(), LocateDSYMInVincinityOfExecutable(), LookForDsymNextToExecutablePath(), and lldb_private::ScriptInterpreterPython::SharedLibraryDirectoryHelper().
SetDirectory() [1/2]
void FileSpec::SetDirectory (ConstString directory)
Directory string set accessor.
Parameters
[in] directory The value to replace the directory with.
Definition at line 342 of file FileSpec.cpp.
References m_directory, and PathWasModified().
Referenced by lldb_private::ComputeClangResourceDirectory(), lldb_private::HostInfoBase::ComputeGlobalTempFileDirectory(), lldb_private::HostInfoMacOSX::ComputeHeaderDirectory(), lldb_private::HostInfoPosix::ComputeHeaderDirectory(), lldb_private::HostInfoBase::ComputePathRelativeToLibrary(), lldb_private::HostInfoBase::ComputeProcessTempFileDirectory(), lldb_private::HostInfoBase::ComputeSharedLibraryDirectory(), lldb_private::HostInfoMacOSX::ComputeSupportExeDirectory(), lldb_private::HostInfoPosix::ComputeSupportExeDirectory(), lldb_private::HostInfoMacOSX::ComputeSystemPluginsDirectory(), lldb_private::HostInfoPosix::ComputeSystemPluginsDirectory(), lldb_private::HostInfoBase::ComputeUserHomeDirectory(), lldb_private::HostInfoBase::ComputeUserLLDBHomeDirectory(), lldb_private::HostInfoMacOSX::ComputeUserPluginsDirectory(), lldb_private::HostInfoPosix::ComputeUserPluginsDirectory(), DefaultComputeClangResourceDirectory(), CommandObjectTargetCreate::DoExecute(), lldb_private::Target::GetOrCreateModule(), lldb_private::ScriptInterpreterPython::GetPythonDir(), lldb_private::Platform::Install(), lldb_private::PlatformDarwin::LocateExecutable(), ObjectFilePECOFF::ParseDependentModules(), RecurseCopy_Callback(), and lldb_private::FileSystem::Resolve().
SetDirectory() [2/2]
void FileSpec::SetDirectory (llvm::StringRef directory)
Definition at line 347 of file FileSpec.cpp.
References m_directory, and PathWasModified().
SetFile() [1/3]
void FileSpec::SetFile (llvm::StringRef path) protected
Definition at line 169 of file FileSpec.cpp.
References m_style, and SetFile().
SetFile() [2/3]
void FileSpec::SetFile (llvm::StringRef path, const llvm::Triple & triple)
Change the file specified with a new path.
Update the contents of this object with a new path. The path will be split up into a directory and filename and stored as uniqued string values for quick comparison and efficient memory usage.
Parameters
[in] path A full, partial, or relative path to a file.
[in] triple The triple which is used to set the Path style.
Definition at line 210 of file FileSpec.cpp.
References SetFile().
SetFile() [3/3]
void FileSpec::SetFile (llvm::StringRef path, Style style)
Change the file specified with a new path.
Update the contents of this object with a new path. The path will be split up into a directory and filename and stored as uniqued string values for quick comparison and efficient memory usage.
Parameters
[in] path A full, partial, or relative path to a file.
[in] style The style for the given path.
Definition at line 174 of file FileSpec.cpp.
References Clear(), m_directory, m_filename, and m_style.
Referenced by lldb::SBTarget::AddModule(), AppendPathComponent(), lldb::SBTarget::AttachToProcessWithName(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::AttachWaitProcess(), lldb_private::BreakpointResolverAddress::CreateFromStructuredData(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::DecodeProcessInfoResponse(), CommandObjectTargetCreate::DoExecute(), CommandObjectTargetSymbolsAdd::DoExecute(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoLaunch(), ProcessElfCore::DoLoadCore(), lldb_private::PlatformWindows::DoLoadImage(), FileSpec(), DYLDRendezvous::FillSOEntryFromModuleInfo(), GetDebugserverPath(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwoSymbolFileForCompileUnit(), GetExePathAndArch(), GetExePathAndIds(), lldb_private::PlatformRemoteDarwinDevice::GetFileInSDK(), lldb_private::NativeFile::GetFileSpec(), GetFreeBSDProcessArgs(), GetMacOSXProcessArgs(), lldb_private::Host::GetModuleFileSpecForHostAddress(), GetModuleSpecInfoFromUUIDDictionary(), GetNetBSDProcessArgs(), GetOpenBSDProcessArgs(), lldb_private::HostInfoAIX::GetProgramFileSpec(), lldb_private::HostInfoFreeBSD::GetProgramFileSpec(), lldb_private::HostInfoLinux::GetProgramFileSpec(), lldb_private::HostInfoMacOSX::GetProgramFileSpec(), lldb_private::HostInfoNetBSD::GetProgramFileSpec(), lldb_private::PlatformAppleSimulator::GetSymbolFile(), lldb_private::PlatformRemoteDarwinDevice::GetSymbolFile(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetWorkingDir(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qfProcessInfo(), MakeAbsoluteAndRemap(), DynamicLoaderMacOSXDYLD::ParseLoadCommands(), ObjectFileMachO::ParseSymtab(), PrependPathComponent(), lldb_private::FileSystem::Readlink(), DYLDRendezvous::ReadSOEntryFromMemory(), RemoveLastPathComponent(), lldb_private::RemoteAwarePlatform::ResolveExecutable(), lldb_private::PathMappingList::ReverseRemapPath(), SetFile(), SetFile(), SetPath(), lldb_private::ObjectFile::SplitArchivePathWithObject(), lldb_private::plugin::dwarf::SymbolFileDWARF::UpdateExternalModuleListIfNeeded(), and DYLDRendezvous::UpdateFileSpecIfNecessary().
SetFilename() [1/2]
void FileSpec::SetFilename (ConstString filename)
Filename string set accessor.
Parameters
[in] filename The const string to replace the directory with.
Definition at line 352 of file FileSpec.cpp.
References m_filename, and PathWasModified().
Referenced by CommandObjectTargetSymbolsAdd::AddModuleSymbols(), lldb_private::Target::Attach(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwpSymbolFile(), lldb_private::Target::GetOrCreateModule(), lldb_private::DynamicLoaderDarwin::GetPThreadLibraryModule(), lldb_private::REPL::GetSourcePath(), lldb_private::ClangUtilityFunction::Install(), lldb_private::Platform::Install(), lldb_private::PlatformDarwin::LocateExecutable(), LocateExecutableScriptingResourcesFromDSYM(), lldb_private::ClangUserExpression::Parse(), RecurseCopy_Callback(), and lldb_private::FunctionCaller::WriteFunctionWrapper().
SetFilename() [2/2]
void FileSpec::SetFilename (llvm::StringRef filename)
Definition at line 357 of file FileSpec.cpp.
References m_filename, and PathWasModified().
SetPath()
void lldb_private::FileSpec::SetPath (llvm::StringRef p) inline
Temporary helper for FileSystem change.
Definition at line 289 of file FileSpec.h.
References SetFile().
Referenced by lldb_private::PlatformQemuUser::DebugProcess(), lldb_private::FileSystem::GetHomeDirectory(), lldb_private::ScriptedProcess::GetLoadedDynamicLibrariesInfos(), lldb_private::Target::GetOrCreateModule(), DynamicLoaderMacOS::GetSharedCacheInformation(), lldb_private::FileSystem::Resolve(), and lldb_private::Host::RunShellCommand().
ToJSON()
llvm::json::Value FileSpec::ToJSON () const
Convert the filespec object to a json value.
Convert the filespec object to a json value. If the object contains a valid directory name, it will be displayed followed by a directory delimiter, and the filename.
Returns
A json value representation of a filespec.
Definition at line 333 of file FileSpec.cpp.
References Dump().
Member Data Documentation
m_absolute
Absolute lldb_private::FileSpec::m_absolute = Absolute::Calculate mutable protected
Cache whether this path is absolute.
Definition at line 435 of file FileSpec.h.
Referenced by IsAbsolute(), and PathWasModified().
m_directory
ConstString lldb_private::FileSpec::m_directory protected
The unique'd directory path.
Definition at line 429 of file FileSpec.h.
Referenced by Clear(), ClearDirectory(), Compare(), DirectoryEquals(), GetComponents(), GetDirectory(), GetPath(), MemorySize(), operator bool(), operator!(), SetDirectory(), SetDirectory(), and SetFile().
m_filename
ConstString lldb_private::FileSpec::m_filename protected
The unique'd filename path.
Definition at line 432 of file FileSpec.h.
Referenced by Clear(), ClearFilename(), Compare(), Dump(), FileEquals(), GetComponents(), GetFilename(), GetFileNameExtension(), GetFileNameStrippingExtension(), GetPath(), MemorySize(), operator bool(), operator!(), SetFile(), SetFilename(), and SetFilename().
m_style
Style lldb_private::FileSpec::m_style protected
The syntax that this path uses. (e.g. Windows / Posix)
Definition at line 438 of file FileSpec.h.
Referenced by AppendPathComponent(), CopyByRemovingLastPathComponent(), Dump(), FileSpec(), FileSpec(), GetComponents(), GetFileNameExtension(), GetFileNameStrippingExtension(), GetPath(), GetPathStyle(), IsAbsolute(), IsCaseSensitive(), PrependPathComponent(), RemoveLastPathComponent(), SetFile(), and SetFile().
The documentation for this class was generated from the following files:
FileSpec.h
FileSpec.cpp