LLDB: lldb_private::formatters::VectorTypeSyntheticFrontEnd Class Reference
lldb_private::formatters::VectorTypeSyntheticFrontEnd Class Reference
Public Member Functions
VectorTypeSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
~VectorTypeSyntheticFrontEnd () override=default
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Attributes
lldb::Format m_parent_format = eFormatInvalid
lldb::Format m_item_format = eFormatInvalid
CompilerType m_child_type
size_t m_num_children = 0
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
Definition at line 223 of file VectorType.cpp.
Constructor & Destructor Documentation
VectorTypeSyntheticFrontEnd()
lldb_private::formatters::VectorTypeSyntheticFrontEnd::VectorTypeSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp) inline
Definition at line 225 of file VectorType.cpp.
References m_child_type, and lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd().
~VectorTypeSyntheticFrontEnd()
lldb_private::formatters::VectorTypeSyntheticFrontEnd::~VectorTypeSyntheticFrontEnd () override default
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > lldb_private::formatters::VectorTypeSyntheticFrontEnd::CalculateNumChildren () inline override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 230 of file VectorType.cpp.
References m_num_children.
Referenced by GetChildAtIndex(), and Update().
GetChildAtIndex()
lldb::ValueObjectSP lldb_private::formatters::VectorTypeSyntheticFrontEnd::GetChildAtIndex (uint32_t idx) inline override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 234 of file VectorType.cpp.
References CalculateNumChildren(), lldb_private::ValueObjectConstResult::Create(), lldb_private::Status::FromError(), lldb_private::StreamString::GetString(), lldb_private::SyntheticChildrenFrontEnd::m_backend, m_child_type, m_item_format, and lldb_private::Stream::Printf().
GetIndexOfChildWithName()
llvm::Expected< size_t > lldb_private::formatters::VectorTypeSyntheticFrontEnd::GetIndexOfChildWithName (ConstString name) inline override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 274 of file VectorType.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::SyntheticChildrenFrontEnd::CalculateNumChildrenIgnoringErrors(), and lldb_private::formatters::ExtractIndexFromString().
Update()
lldb::ChildCacheState lldb_private::formatters::VectorTypeSyntheticFrontEnd::Update () inline override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 258 of file VectorType.cpp.
References CalculateNumChildren(), lldb::eRefetch, GetCompilerTypeForFormat(), GetItemFormatForFormat(), lldb_private::CompilerType::TypeSystemSPWrapper::GetSharedPointer(), lldb_private::CompilerType::GetTypeSystem(), lldb_private::CompilerType::IsVectorType(), lldb_private::SyntheticChildrenFrontEnd::m_backend, m_child_type, m_item_format, m_num_children, and m_parent_format.
Member Data Documentation
m_child_type
CompilerType lldb_private::formatters::VectorTypeSyntheticFrontEnd::m_child_type private
Definition at line 290 of file VectorType.cpp.
Referenced by GetChildAtIndex(), Update(), and VectorTypeSyntheticFrontEnd().
m_item_format
lldb::Format lldb_private::formatters::VectorTypeSyntheticFrontEnd::m_item_format = eFormatInvalid private
Definition at line 289 of file VectorType.cpp.
Referenced by GetChildAtIndex(), and Update().
m_num_children
size_t lldb_private::formatters::VectorTypeSyntheticFrontEnd::m_num_children = 0 private
Definition at line 291 of file VectorType.cpp.
Referenced by CalculateNumChildren(), and Update().
m_parent_format
lldb::Format lldb_private::formatters::VectorTypeSyntheticFrontEnd::m_parent_format = eFormatInvalid private
Definition at line 288 of file VectorType.cpp.
Referenced by Update().
The documentation for this class was generated from the following file:
VectorType.cpp