LLDB: RegisterContextPOSIX_arm Class Reference
RegisterContextPOSIX_arm Class Reference abstract
#include <RegisterContextPOSIX_arm.h>
Public Member Functions
RegisterContextPOSIX_arm (lldb_private::Thread &thread, std::unique_ptr< RegisterInfoPOSIX_arm > register_info)
~RegisterContextPOSIX_arm () override
void Invalidate ()
void InvalidateAllRegisters () override
size_t GetRegisterCount () override
virtual size_t GetGPRSize ()
virtual unsigned GetRegisterSize (unsigned reg)
virtual unsigned GetRegisterOffset (unsigned reg)
const lldb_private::RegisterInfo * GetRegisterInfoAtIndex (size_t reg) override
size_t GetRegisterSetCount () override
const lldb_private::RegisterSet * GetRegisterSet (size_t set) override
const char * GetRegisterName (unsigned reg)
Public Member Functions inherited from lldb_private::RegisterContext
RegisterContext (Thread &thread, uint32_t concrete_frame_idx)
~RegisterContext () override
void InvalidateIfNeeded (bool force)
virtual lldb::ByteOrder GetByteOrder ()
virtual bool ReadRegister (const RegisterInfo *reg_info, RegisterValue &reg_value)=0
virtual bool WriteRegister (const RegisterInfo *reg_info, const RegisterValue &reg_value)=0
virtual bool ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp)
virtual bool WriteAllRegisterValues (const lldb::DataBufferSP &data_sp)
virtual bool RegisterWriteCausesReconfigure (const llvm::StringRef name)
virtual bool ReconfigureRegisterInfo ()
virtual bool ReadAllRegisterValues (lldb_private::RegisterCheckpoint &reg_checkpoint)
virtual bool WriteAllRegisterValues (const lldb_private::RegisterCheckpoint &reg_checkpoint)
bool CopyFromRegisterContext (lldb::RegisterContextSP context)
virtual uint32_t ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num)
Convert from a given register numbering scheme to the lldb register numbering scheme.
virtual uint32_t NumSupportedHardwareBreakpoints ()
virtual uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual bool ClearHardwareBreakpoint (uint32_t hw_idx)
virtual uint32_t NumSupportedHardwareWatchpoints ()
virtual uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, bool read, bool write)
virtual bool ClearHardwareWatchpoint (uint32_t hw_index)
virtual bool HardwareSingleStep (bool enable)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, uint32_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, uint32_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual Thread & GetThread ()
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num)
uint64_t GetPC (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetThreadPointer (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool GetPCForSymbolication (Address &address)
Get an address suitable for symbolication.
bool SetPC (uint64_t pc)
bool SetPC (Address addr)
uint64_t GetSP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetSP (uint64_t sp)
uint64_t GetFP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetFP (uint64_t fp)
const char * GetRegisterName (uint32_t reg)
uint64_t GetReturnAddress (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetFlags (uint64_t fail_value=0)
uint64_t ReadRegisterAsUnsigned (uint32_t reg, uint64_t fail_value)
uint64_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, uint64_t fail_value)
bool WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
bool WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
bool ConvertBetweenRegisterKinds (lldb::RegisterKind source_rk, uint32_t source_regnum, lldb::RegisterKind target_rk, uint32_t &target_regnum)
lldb::TargetSP CalculateTarget () override
lldb::ProcessSP CalculateProcess () override
lldb::ThreadSP CalculateThread () override
lldb::StackFrameSP CalculateStackFrame () override
void CalculateExecutionContext (ExecutionContext &exe_ctx) override
Reconstruct the object's execution context into sc.
uint32_t GetStopID () const
void SetStopID (uint32_t stop_id)
Public Member Functions inherited from lldb_private::ExecutionContextScope
virtual ~ExecutionContextScope ()=default
Protected Member Functions
virtual const lldb_private::RegisterInfo * GetRegisterInfo ()
bool IsGPR (unsigned reg)
bool IsFPR (unsigned reg)
size_t GetFPUSize ()
virtual bool ReadGPR ()=0
virtual bool ReadFPR ()=0
virtual bool WriteGPR ()=0
virtual bool WriteFPR ()=0
Protected Member Functions inherited from lldb_private::RegisterContext
virtual bool BehavesLikeZerothFrame () const
Indicates that this frame is currently executing code, that the PC value is not a return-pc but an actual executing instruction.
Protected Attributes
std::unique_ptr< RegisterInfoPOSIX_arm > m_register_info_up
Protected Attributes inherited from lldb_private::RegisterContext
Thread & m_thread
uint32_t m_concrete_frame_idx
uint32_t m_stop_id
Detailed Description
Definition at line 17 of file RegisterContextPOSIX_arm.h.
Constructor & Destructor Documentation
RegisterContextPOSIX_arm()
RegisterContextPOSIX_arm::RegisterContextPOSIX_arm (lldb_private::Thread & thread, std::unique_ptr< RegisterInfoPOSIX_arm > register_info)
Definition at line 42 of file RegisterContextPOSIX_arm.cpp.
References m_register_info_up, and lldb_private::RegisterContext::RegisterContext().
Referenced by RegisterContextCorePOSIX_arm::RegisterContextCorePOSIX_arm().
~RegisterContextPOSIX_arm()
RegisterContextPOSIX_arm::~RegisterContextPOSIX_arm () override default
Member Function Documentation
GetFPUSize()
size_t RegisterContextPOSIX_arm::GetFPUSize () inline protected
Definition at line 54 of file RegisterContextPOSIX_arm.h.
GetGPRSize()
size_t RegisterContextPOSIX_arm::GetGPRSize () virtual
Definition at line 66 of file RegisterContextPOSIX_arm.cpp.
References m_register_info_up.
Referenced by RegisterContextCorePOSIX_arm::ReadRegister().
GetRegisterCount()
size_t RegisterContextPOSIX_arm::GetRegisterCount () override virtual
Implements lldb_private::RegisterContext.
Definition at line 62 of file RegisterContextPOSIX_arm.cpp.
References m_register_info_up.
Referenced by GetRegisterInfoAtIndex(), and GetRegisterName().
GetRegisterInfo()
const lldb_private::RegisterInfo * RegisterContextPOSIX_arm::GetRegisterInfo () protected virtual
Definition at line 70 of file RegisterContextPOSIX_arm.cpp.
References m_register_info_up.
Referenced by GetRegisterInfoAtIndex(), and GetRegisterName().
GetRegisterInfoAtIndex()
const lldb_private::RegisterInfo * RegisterContextPOSIX_arm::GetRegisterInfoAtIndex (size_t reg) override virtual
Implements lldb_private::RegisterContext.
Definition at line 78 of file RegisterContextPOSIX_arm.cpp.
References GetRegisterCount(), and GetRegisterInfo().
GetRegisterName()
const char * RegisterContextPOSIX_arm::GetRegisterName (unsigned reg)
Definition at line 94 of file RegisterContextPOSIX_arm.cpp.
References GetRegisterCount(), GetRegisterInfo(), and lldb_private::RegisterInfo::name.
GetRegisterOffset()
unsigned RegisterContextPOSIX_arm::GetRegisterOffset (unsigned reg) virtual
Definition at line 54 of file RegisterContextPOSIX_arm.cpp.
References m_register_info_up.
GetRegisterSet()
const lldb_private::RegisterSet * RegisterContextPOSIX_arm::GetRegisterSet (size_t set) override virtual
Implements lldb_private::RegisterContext.
Definition at line 90 of file RegisterContextPOSIX_arm.cpp.
References m_register_info_up.
GetRegisterSetCount()
size_t RegisterContextPOSIX_arm::GetRegisterSetCount () override virtual
Implements lldb_private::RegisterContext.
Definition at line 85 of file RegisterContextPOSIX_arm.cpp.
References m_register_info_up.
GetRegisterSize()
unsigned RegisterContextPOSIX_arm::GetRegisterSize (unsigned reg) virtual
Definition at line 58 of file RegisterContextPOSIX_arm.cpp.
References m_register_info_up.
Invalidate()
void RegisterContextPOSIX_arm::Invalidate ()
Definition at line 50 of file RegisterContextPOSIX_arm.cpp.
InvalidateAllRegisters()
void RegisterContextPOSIX_arm::InvalidateAllRegisters () override virtual
Implements lldb_private::RegisterContext.
Definition at line 52 of file RegisterContextPOSIX_arm.cpp.
IsFPR()
bool RegisterContextPOSIX_arm::IsFPR (unsigned reg) protected
Definition at line 35 of file RegisterContextPOSIX_arm.cpp.
References RegisterInfoPOSIX_arm::FPRegSet, and m_register_info_up.
Referenced by RegisterContextCorePOSIX_arm::ReadRegister().
IsGPR()
bool RegisterContextPOSIX_arm::IsGPR (unsigned reg) protected
Definition at line 28 of file RegisterContextPOSIX_arm.cpp.
References RegisterInfoPOSIX_arm::GPRegSet, and m_register_info_up.
Referenced by RegisterContextCorePOSIX_arm::ReadRegister().
ReadFPR()
virtual bool RegisterContextPOSIX_arm::ReadFPR () protected pure virtual
Implemented in RegisterContextCorePOSIX_arm.
ReadGPR()
virtual bool RegisterContextPOSIX_arm::ReadGPR () protected pure virtual
Implemented in RegisterContextCorePOSIX_arm.
WriteFPR()
virtual bool RegisterContextPOSIX_arm::WriteFPR () protected pure virtual
Implemented in RegisterContextCorePOSIX_arm.
WriteGPR()
virtual bool RegisterContextPOSIX_arm::WriteGPR () protected pure virtual
Implemented in RegisterContextCorePOSIX_arm.
Member Data Documentation
m_register_info_up
std::unique_ptr<RegisterInfoPOSIX_arm> RegisterContextPOSIX_arm::m_register_info_up protected
Definition at line 46 of file RegisterContextPOSIX_arm.h.
Referenced by GetGPRSize(), GetRegisterCount(), GetRegisterInfo(), GetRegisterOffset(), GetRegisterSet(), GetRegisterSetCount(), GetRegisterSize(), IsFPR(), IsGPR(), RegisterContextCorePOSIX_arm::RegisterContextCorePOSIX_arm(), and RegisterContextPOSIX_arm().
The documentation for this class was generated from the following files:
RegisterContextPOSIX_arm.h
RegisterContextPOSIX_arm.cpp