LLDB: lldb::SBCompileUnit Class Reference
lldb::SBCompileUnit Class Reference
#include <SBCompileUnit.h>
Public Member Functions
SBCompileUnit ()
SBCompileUnit (const lldb::SBCompileUnit &rhs)
~SBCompileUnit ()
const lldb::SBCompileUnit & operator= (const lldb::SBCompileUnit &rhs)
operator bool () const
bool IsValid () const
lldb::SBFileSpec GetFileSpec () const
uint32_t GetNumLineEntries () const
lldb::SBLineEntry GetLineEntryAtIndex (uint32_t idx) const
uint32_t FindLineEntryIndex (lldb::SBLineEntry &line_entry, bool exact=false) const
uint32_t FindLineEntryIndex (uint32_t start_idx, uint32_t line, lldb::SBFileSpec *inline_file_spec) const
uint32_t FindLineEntryIndex (uint32_t start_idx, uint32_t line, lldb::SBFileSpec *inline_file_spec, bool exact) const
SBFileSpec GetSupportFileAtIndex (uint32_t idx) const
uint32_t GetNumSupportFiles () const
uint32_t FindSupportFileIndex (uint32_t start_idx, const SBFileSpec &sb_file, bool full)
lldb::SBTypeList GetTypes (uint32_t type_mask=lldb::eTypeClassAny)
Get all types matching type_mask from debug info in this compile unit.
lldb::LanguageType GetLanguage ()
bool operator== (const lldb::SBCompileUnit &rhs) const
bool operator!= (const lldb::SBCompileUnit &rhs) const
bool GetDescription (lldb::SBStream &description)
Private Member Functions
SBCompileUnit (lldb_private::CompileUnit *lldb_object_ptr)
const lldb_private::CompileUnit * operator-> () const
const lldb_private::CompileUnit & operator* () const
lldb_private::CompileUnit * get ()
void reset (lldb_private::CompileUnit *lldb_object_ptr)
Private Attributes
lldb_private::CompileUnit * m_opaque_ptr = nullptr
Friends
class SBAddress
class SBFrame
class SBSymbolContext
class SBModule
Detailed Description
Definition at line 17 of file SBCompileUnit.h.
Constructor & Destructor Documentation
SBCompileUnit() [1/3]
SBCompileUnit::SBCompileUnit ()
Definition at line 24 of file SBCompileUnit.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by operator!=(), operator=(), operator==(), SBCompileUnit(), and SBModule.
SBCompileUnit() [2/3]
SBCompileUnit::SBCompileUnit (const lldb::SBCompileUnit & rhs)
Definition at line 29 of file SBCompileUnit.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBCompileUnit().
~SBCompileUnit()
SBCompileUnit::~SBCompileUnit ()
Definition at line 41 of file SBCompileUnit.cpp.
References m_opaque_ptr.
SBCompileUnit() [3/3]
SBCompileUnit::SBCompileUnit (lldb_private::CompileUnit * lldb_object_ptr) private
Definition at line 26 of file SBCompileUnit.cpp.
References m_opaque_ptr.
Member Function Documentation
FindLineEntryIndex() [1/3]
uint32_t SBCompileUnit::FindLineEntryIndex (lldb::SBLineEntry & line_entry, bool exact = false) const
Definition at line 80 of file SBCompileUnit.cpp.
References lldb::SBFileSpec::get(), lldb::SBLineEntry::GetFileSpec(), lldb::SBLineEntry::GetLine(), lldb::SBLineEntry::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_ptr, lldb::SBLineEntry::ref(), and UINT32_MAX.
Referenced by FindLineEntryIndex().
FindLineEntryIndex() [2/3]
uint32_t SBCompileUnit::FindLineEntryIndex (uint32_t start_idx, uint32_t line, lldb::SBFileSpec * inline_file_spec) const
Definition at line 94 of file SBCompileUnit.cpp.
References FindLineEntryIndex(), and LLDB_INSTRUMENT_VA.
FindLineEntryIndex() [3/3]
uint32_t SBCompileUnit::FindLineEntryIndex (uint32_t start_idx, uint32_t line, lldb::SBFileSpec * inline_file_spec, bool exact) const
Definition at line 102 of file SBCompileUnit.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and UINT32_MAX.
FindSupportFileIndex()
uint32_t SBCompileUnit::FindSupportFileIndex (uint32_t start_idx, const SBFileSpec & sb_file, bool full)
Definition at line 168 of file SBCompileUnit.cpp.
References lldb_private::SupportFileList::FindFileIndex(), LLDB_INSTRUMENT_VA, m_opaque_ptr, and lldb::SBFileSpec::ref().
get()
lldb_private::CompileUnit * SBCompileUnit::get () private
Definition at line 218 of file SBCompileUnit.cpp.
References m_opaque_ptr.
Referenced by SBModule, and lldb::SBSymbolContext::SetCompileUnit().
GetDescription()
bool SBCompileUnit::GetDescription (lldb::SBStream & description)
Definition at line 224 of file SBCompileUnit.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
GetFileSpec()
SBFileSpec SBCompileUnit::GetFileSpec () const
Definition at line 43 of file SBCompileUnit.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and lldb::SBFileSpec::SetFileSpec().
GetLanguage()
lldb::LanguageType SBCompileUnit::GetLanguage ()
Definition at line 180 of file SBCompileUnit.cpp.
References lldb::eLanguageTypeUnknown, LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetLineEntryAtIndex()
SBLineEntry SBCompileUnit::GetLineEntryAtIndex (uint32_t idx) const
Definition at line 64 of file SBCompileUnit.cpp.
References lldb_private::LineTable::GetLineEntryAtIndex(), LLDB_INSTRUMENT_VA, m_opaque_ptr, and lldb::SBLineEntry::SetLineEntry().
GetNumLineEntries()
uint32_t SBCompileUnit::GetNumLineEntries () const
Definition at line 52 of file SBCompileUnit.cpp.
References lldb_private::LineTable::GetSize(), LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetNumSupportFiles()
uint32_t SBCompileUnit::GetNumSupportFiles () const
Definition at line 124 of file SBCompileUnit.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetSupportFileAtIndex()
SBFileSpec SBCompileUnit::GetSupportFileAtIndex (uint32_t idx) const
Definition at line 156 of file SBCompileUnit.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and lldb::SBFileSpec::SetFileSpec().
GetTypes()
lldb::SBTypeList SBCompileUnit::GetTypes (uint32_t type_mask = lldb::eTypeClassAny)
Get all types matching type_mask from debug info in this compile unit.
Parameters
[in] type_mask A bitfield that consists of one or more bits logically OR'ed together from the lldb::TypeClass enumeration. This allows you to request only structure types, or only class, struct and union types. Passing in lldb::eTypeClassAny will return all types found in the debug information for this compile unit.
Returns
A list of types in this compile unit that match type_mask
Definition at line 133 of file SBCompileUnit.cpp.
References lldb_private::SymbolFile::GetTypes(), LLDB_INSTRUMENT_VA, m_opaque_ptr, and lldb::SBTypeList::m_opaque_up.
IsValid()
bool SBCompileUnit::IsValid () const
Definition at line 188 of file SBCompileUnit.cpp.
References LLDB_INSTRUMENT_VA.
operator bool()
SBCompileUnit::operator bool () const explicit
Definition at line 192 of file SBCompileUnit.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
operator!=()
bool SBCompileUnit::operator!= (const lldb::SBCompileUnit & rhs) const
Definition at line 204 of file SBCompileUnit.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBCompileUnit().
operator*()
const lldb_private::CompileUnit & SBCompileUnit::operator* () const private
Definition at line 214 of file SBCompileUnit.cpp.
References m_opaque_ptr.
Referenced by SBModule.
operator->()
const lldb_private::CompileUnit * SBCompileUnit::operator-> () const private
Definition at line 210 of file SBCompileUnit.cpp.
References m_opaque_ptr.
Referenced by SBModule.
operator=()
const SBCompileUnit & SBCompileUnit::operator= (const lldb::SBCompileUnit & rhs)
Definition at line 34 of file SBCompileUnit.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBCompileUnit().
operator==()
bool SBCompileUnit::operator== (const lldb::SBCompileUnit & rhs) const
Definition at line 198 of file SBCompileUnit.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBCompileUnit().
reset()
void SBCompileUnit::reset (lldb_private::CompileUnit * lldb_object_ptr) private
Definition at line 220 of file SBCompileUnit.cpp.
References m_opaque_ptr.
Referenced by lldb::SBAddress::GetCompileUnit(), lldb::SBModule::GetCompileUnitAtIndex(), and SBModule.
Friends And Related Symbol Documentation
SBAddress
friend class SBAddress friend
Definition at line 78 of file SBCompileUnit.h.
References SBAddress.
Referenced by SBAddress.
SBFrame
friend class SBFrame friend
Definition at line 79 of file SBCompileUnit.h.
References SBFrame.
Referenced by SBFrame.
SBModule
friend class SBModule friend
Definition at line 81 of file SBCompileUnit.h.
References get(), operator*(), operator->(), reset(), SBCompileUnit(), and SBModule.
Referenced by SBModule.
SBSymbolContext
friend class SBSymbolContext friend
Definition at line 80 of file SBCompileUnit.h.
References SBSymbolContext.
Referenced by SBSymbolContext.
Member Data Documentation
m_opaque_ptr
lldb_private::CompileUnit* lldb::SBCompileUnit::m_opaque_ptr = nullptr private
Definition at line 93 of file SBCompileUnit.h.
Referenced by FindLineEntryIndex(), FindLineEntryIndex(), FindSupportFileIndex(), get(), GetDescription(), GetFileSpec(), GetLanguage(), GetLineEntryAtIndex(), GetNumLineEntries(), GetNumSupportFiles(), GetSupportFileAtIndex(), GetTypes(), operator bool(), operator!=(), operator*(), operator->(), operator=(), operator==(), reset(), SBCompileUnit(), SBCompileUnit(), and ~SBCompileUnit().
The documentation for this class was generated from the following files:
SBCompileUnit.h
SBCompileUnit.cpp