LLDB: lldb_private::MainLoopPosix::SignalHandle Class Reference
lldb_private::MainLoopPosix::SignalHandle Class Reference
Public Member Functions
~SignalHandle ()
Private Member Functions
SignalHandle (MainLoopPosix &mainloop, int signo, std::list< Callback >::iterator callback_it)
SignalHandle (const SignalHandle &)=delete
const SignalHandle & operator= (const SignalHandle &)=delete
Private Attributes
MainLoopPosix & m_mainloop
int m_signo
std::list< Callback >::iterator m_callback_it
Friends
class MainLoopPosix
Detailed Description
Definition at line 64 of file MainLoopPosix.h.
Constructor & Destructor Documentation
~SignalHandle()
lldb_private::MainLoopPosix::SignalHandle::~SignalHandle () inline
Definition at line 66 of file MainLoopPosix.h.
References m_callback_it, m_mainloop, and m_signo.
SignalHandle() [1/2]
lldb_private::MainLoopPosix::SignalHandle::SignalHandle (MainLoopPosix & mainloop, int signo, std::list< Callback >::iterator callback_it) inline private
Definition at line 69 of file MainLoopPosix.h.
References m_callback_it, m_mainloop, m_signo, and MainLoopPosix.
Referenced by operator=(), and SignalHandle().
SignalHandle() [2/2]
lldb_private::MainLoopPosix::SignalHandle::SignalHandle (const SignalHandle &) private delete
References SignalHandle().
Member Function Documentation
operator=()
const SignalHandle & lldb_private::MainLoopPosix::SignalHandle::operator= (const SignalHandle &) private delete
References SignalHandle().
Friends And Related Symbol Documentation
MainLoopPosix
friend class MainLoopPosix friend
Definition at line 77 of file MainLoopPosix.h.
References MainLoopPosix.
Referenced by MainLoopPosix, and SignalHandle().
Member Data Documentation
m_callback_it
std::list<Callback>::iterator lldb_private::MainLoopPosix::SignalHandle::m_callback_it private
Definition at line 75 of file MainLoopPosix.h.
Referenced by SignalHandle(), and ~SignalHandle().
m_mainloop
MainLoopPosix& lldb_private::MainLoopPosix::SignalHandle::m_mainloop private
Definition at line 73 of file MainLoopPosix.h.
Referenced by SignalHandle(), and ~SignalHandle().
m_signo
int lldb_private::MainLoopPosix::SignalHandle::m_signo private
Definition at line 74 of file MainLoopPosix.h.
Referenced by SignalHandle(), and ~SignalHandle().
The documentation for this class was generated from the following file:
MainLoopPosix.h