LLDB: lldb_private::ThreadSafeDenseMap< _KeyType, _ValueType > Class Template Reference
lldb_private::ThreadSafeDenseMap< _KeyType, _ValueType > Class Template Reference
#include <ThreadSafeDenseMap.h>
Public Types
typedef llvm::DenseMap< _KeyType, _ValueType > LLVMMapType
Public Member Functions
ThreadSafeDenseMap (unsigned map_initial_capacity=0)
void Insert (_KeyType k, _ValueType v)
void Erase (_KeyType k)
_ValueType Lookup (_KeyType k)
bool Lookup (_KeyType k, _ValueType &v)
void Clear ()
Protected Attributes
LLVMMapType m_map
std::mutex m_mutex
Detailed Description
template<typename _KeyType, typename _ValueType>
class lldb_private::ThreadSafeDenseMap< _KeyType, _ValueType >
Definition at line 18 of file ThreadSafeDenseMap.h.
Member Typedef Documentation
LLVMMapType
template<typename _KeyType, typename _ValueType> typedef llvm::DenseMap<_KeyType, _ValueType> lldb_private::ThreadSafeDenseMap< _KeyType, _ValueType >::LLVMMapType
Definition at line 20 of file ThreadSafeDenseMap.h.
Constructor & Destructor Documentation
ThreadSafeDenseMap()
template<typename _KeyType, typename _ValueType> lldb_private::ThreadSafeDenseMap< _KeyType, _ValueType >::ThreadSafeDenseMap (unsigned map_initial_capacity = 0) inline
Definition at line 22 of file ThreadSafeDenseMap.h.
Member Function Documentation
Clear()
template<typename _KeyType, typename _ValueType> void lldb_private::ThreadSafeDenseMap< _KeyType, _ValueType >::Clear () inline
Definition at line 49 of file ThreadSafeDenseMap.h.
Erase()
template<typename _KeyType, typename _ValueType> void lldb_private::ThreadSafeDenseMap< _KeyType, _ValueType >::Erase (_KeyType k) inline
Definition at line 30 of file ThreadSafeDenseMap.h.
Referenced by lldb_private::TypeSystemClang::Finalize().
Insert()
template<typename _KeyType, typename _ValueType> void lldb_private::ThreadSafeDenseMap< _KeyType, _ValueType >::Insert (_KeyType k, _ValueType v) inline
Definition at line 25 of file ThreadSafeDenseMap.h.
Referenced by lldb_private::TypeSystemClang::CreateASTContext().
Lookup() [1/2]
template<typename _KeyType, typename _ValueType> _ValueType lldb_private::ThreadSafeDenseMap< _KeyType, _ValueType >::Lookup (_KeyType k) inline
Definition at line 35 of file ThreadSafeDenseMap.h.
Referenced by lldb_private::TypeSystemClang::GetASTContext().
Lookup() [2/2]
template<typename _KeyType, typename _ValueType> bool lldb_private::ThreadSafeDenseMap< _KeyType, _ValueType >::Lookup (_KeyType k, _ValueType & v) inline
Definition at line 40 of file ThreadSafeDenseMap.h.
Member Data Documentation
m_map
template<typename _KeyType, typename _ValueType> LLVMMapType lldb_private::ThreadSafeDenseMap< _KeyType, _ValueType >::m_map protected
Definition at line 55 of file ThreadSafeDenseMap.h.
m_mutex
template<typename _KeyType, typename _ValueType> std::mutex lldb_private::ThreadSafeDenseMap< _KeyType, _ValueType >::m_mutex protected
Definition at line 56 of file ThreadSafeDenseMap.h.
The documentation for this class was generated from the following file:
ThreadSafeDenseMap.h