LLDB: lldb_private::ScriptInterpreterPython Class Reference
lldb_private::ScriptInterpreterPython Class Reference
Abstract interface for the Python script interpreter.
#include <ScriptInterpreterPython.h>
Classes
class CommandDataPython
Public Member Functions
ScriptInterpreterPython (Debugger &debugger)
StructuredData::DictionarySP GetInterpreterInfo () override
Public Member Functions inherited from lldb_private::ScriptInterpreter
ScriptInterpreter (Debugger &debugger, lldb::ScriptLanguage script_lang)
~ScriptInterpreter () override=default
virtual bool Interrupt ()
virtual bool ExecuteOneLine (llvm::StringRef command, CommandReturnObject *result, const ExecuteScriptOptions &options=ExecuteScriptOptions())=0
virtual void ExecuteInterpreterLoop ()=0
virtual bool ExecuteOneLineWithReturn (llvm::StringRef in_string, ScriptReturnType return_type, void *ret_value, const ExecuteScriptOptions &options=ExecuteScriptOptions())
virtual Status ExecuteMultipleLines (const char *in_string, const ExecuteScriptOptions &options=ExecuteScriptOptions())
virtual Status ExportFunctionDefinitionToInterpreter (StringList &function_def)
virtual Status GenerateBreakpointCommandCallbackData (StringList &input, std::string &output, bool has_extra_args, bool is_callback)
virtual bool GenerateWatchpointCommandCallbackData (StringList &input, std::string &output, bool is_callback)
virtual bool GenerateTypeScriptFunction (const char *oneliner, std::string &output, const void *name_token=nullptr)
virtual bool GenerateTypeScriptFunction (StringList &input, std::string &output, const void *name_token=nullptr)
virtual bool GenerateScriptAliasFunction (StringList &input, std::string &output)
virtual bool GenerateTypeSynthClass (StringList &input, std::string &output, const void *name_token=nullptr)
virtual bool GenerateTypeSynthClass (const char *oneliner, std::string &output, const void *name_token=nullptr)
virtual StructuredData::ObjectSP CreateSyntheticScriptedProvider (const char *class_name, lldb::ValueObjectSP valobj)
virtual StructuredData::GenericSP CreateScriptCommandObject (const char *class_name)
virtual StructuredData::GenericSP CreateFrameRecognizer (const char *class_name)
virtual lldb::ValueObjectListSP GetRecognizedArguments (const StructuredData::ObjectSP &implementor, lldb::StackFrameSP frame_sp)
virtual bool ShouldHide (const StructuredData::ObjectSP &implementor, lldb::StackFrameSP frame_sp)
virtual StructuredData::ObjectSP LoadPluginModule (const FileSpec &file_spec, lldb_private::Status &error)
virtual StructuredData::DictionarySP GetDynamicSettings (StructuredData::ObjectSP plugin_module_sp, Target *target, const char *setting_name, lldb_private::Status &error)
virtual Status GenerateFunction (const char *signature, const StringList &input, bool is_callback)
virtual void CollectDataForBreakpointCommandCallback (std::vector< std::reference_wrapper< BreakpointOptions > > &options, CommandReturnObject &result)
virtual void CollectDataForWatchpointCommandCallback (WatchpointOptions *wp_options, CommandReturnObject &result)
Status SetBreakpointCommandCallback (std::vector< std::reference_wrapper< BreakpointOptions > > &bp_options_vec, const char *callback_text)
Set the specified text as the callback for the breakpoint.
virtual Status SetBreakpointCommandCallback (BreakpointOptions &bp_options, const char *callback_text, bool is_callback)
virtual Status SetBreakpointCommandCallback (BreakpointOptions &bp_options, std::unique_ptr< BreakpointOptions::CommandData > &data_up)
This one is for deserialization:
Status SetBreakpointCommandCallbackFunction (std::vector< std::reference_wrapper< BreakpointOptions > > &bp_options_vec, const char *function_name, StructuredData::ObjectSP extra_args_sp)
virtual Status SetBreakpointCommandCallbackFunction (BreakpointOptions &bp_options, const char *function_name, StructuredData::ObjectSP extra_args_sp)
Set a script function as the callback for the breakpoint.
virtual void SetWatchpointCommandCallback (WatchpointOptions *wp_options, const char *user_input, bool is_callback)
Set a one-liner as the callback for the watchpoint.
virtual bool GetScriptedSummary (const char *function_name, lldb::ValueObjectSP valobj, StructuredData::ObjectSP &callee_wrapper_sp, const TypeSummaryOptions &options, std::string &retval)
virtual bool FormatterCallbackFunction (const char *function_name, lldb::TypeImplSP type_impl_sp)
virtual void Clear ()
virtual size_t CalculateNumChildren (const StructuredData::ObjectSP &implementor, uint32_t max)
virtual lldb::ValueObjectSP GetChildAtIndex (const StructuredData::ObjectSP &implementor, uint32_t idx)
virtual llvm::Expected< uint32_t > GetIndexOfChildWithName (const StructuredData::ObjectSP &implementor, const char *child_name)
virtual bool UpdateSynthProviderInstance (const StructuredData::ObjectSP &implementor)
virtual bool MightHaveChildrenSynthProviderInstance (const StructuredData::ObjectSP &implementor)
virtual lldb::ValueObjectSP GetSyntheticValue (const StructuredData::ObjectSP &implementor)
virtual ConstString GetSyntheticTypeName (const StructuredData::ObjectSP &implementor)
virtual bool RunScriptBasedCommand (const char *impl_function, llvm::StringRef args, ScriptedCommandSynchronicity synchronicity, lldb_private::CommandReturnObject &cmd_retobj, Status &error, const lldb_private::ExecutionContext &exe_ctx)
virtual bool RunScriptBasedCommand (StructuredData::GenericSP impl_obj_sp, llvm::StringRef args, ScriptedCommandSynchronicity synchronicity, lldb_private::CommandReturnObject &cmd_retobj, Status &error, const lldb_private::ExecutionContext &exe_ctx)
virtual bool RunScriptBasedParsedCommand (StructuredData::GenericSP impl_obj_sp, Args &args, ScriptedCommandSynchronicity synchronicity, lldb_private::CommandReturnObject &cmd_retobj, Status &error, const lldb_private::ExecutionContext &exe_ctx)
virtual std::optional< std::string > GetRepeatCommandForScriptedCommand (StructuredData::GenericSP impl_obj_sp, Args &args)
virtual StructuredData::DictionarySP HandleArgumentCompletionForScriptedCommand (StructuredData::GenericSP impl_obj_sp, std::vector< llvm::StringRef > &args, size_t args_pos, size_t char_in_arg)
virtual StructuredData::DictionarySP HandleOptionArgumentCompletionForScriptedCommand (StructuredData::GenericSP impl_obj_sp, llvm::StringRef &long_name, size_t char_in_arg)
virtual bool RunScriptFormatKeyword (const char *impl_function, Process *process, std::string &output, Status &error)
virtual bool RunScriptFormatKeyword (const char *impl_function, Thread *thread, std::string &output, Status &error)
virtual bool RunScriptFormatKeyword (const char *impl_function, Target *target, std::string &output, Status &error)
virtual bool RunScriptFormatKeyword (const char *impl_function, StackFrame *frame, std::string &output, Status &error)
virtual bool RunScriptFormatKeyword (const char *impl_function, ValueObject *value, std::string &output, Status &error)
virtual bool GetDocumentationForItem (const char *item, std::string &dest)
virtual bool GetShortHelpForCommandObject (StructuredData::GenericSP cmd_obj_sp, std::string &dest)
virtual StructuredData::ObjectSP GetOptionsForCommandObject (StructuredData::GenericSP cmd_obj_sp)
virtual StructuredData::ObjectSP GetArgumentsForCommandObject (StructuredData::GenericSP cmd_obj_sp)
virtual bool SetOptionValueForCommandObject (StructuredData::GenericSP cmd_obj_sp, ExecutionContext *exe_ctx, llvm::StringRef long_option, llvm::StringRef value)
virtual void OptionParsingStartedForCommandObject (StructuredData::GenericSP cmd_obj_sp)
virtual uint32_t GetFlagsForCommandObject (StructuredData::GenericSP cmd_obj_sp)
virtual bool GetLongHelpForCommandObject (StructuredData::GenericSP cmd_obj_sp, std::string &dest)
virtual bool CheckObjectExists (const char *name)
virtual bool LoadScriptingModule (const char *filename, const LoadScriptOptions &options, lldb_private::Status &error, StructuredData::ObjectSP *module_sp=nullptr, FileSpec extra_search_dir={}, lldb::TargetSP loaded_into_target_sp={})
virtual bool IsReservedWord (const char *word)
virtual std::unique_ptr< ScriptInterpreterLocker > AcquireInterpreterLock ()
const char * GetScriptInterpreterPtyName ()
virtual llvm::Expected< unsigned > GetMaxPositionalArgumentsForCallable (const llvm::StringRef &callable_name)
lldb::ScriptLanguage GetLanguage ()
virtual lldb::ScriptedProcessInterfaceUP CreateScriptedProcessInterface ()
virtual lldb::ScriptedThreadInterfaceSP CreateScriptedThreadInterface ()
virtual lldb::ScriptedFrameInterfaceSP CreateScriptedFrameInterface ()
virtual lldb::ScriptedFrameProviderInterfaceSP CreateScriptedFrameProviderInterface ()
virtual lldb::ScriptedThreadPlanInterfaceSP CreateScriptedThreadPlanInterface ()
virtual lldb::OperatingSystemInterfaceSP CreateOperatingSystemInterface ()
virtual lldb::ScriptedPlatformInterfaceUP GetScriptedPlatformInterface ()
virtual lldb::ScriptedStopHookInterfaceSP CreateScriptedStopHookInterface ()
virtual lldb::ScriptedBreakpointInterfaceSP CreateScriptedBreakpointInterface ()
virtual StructuredData::ObjectSP CreateStructuredDataFromScriptObject (ScriptObject obj)
lldb::DataExtractorSP GetDataExtractorFromSBData (const lldb::SBData &data) const
Status GetStatusFromSBError (const lldb::SBError &error) const
Event * GetOpaqueTypeFromSBEvent (const lldb::SBEvent &event) const
lldb::StreamSP GetOpaqueTypeFromSBStream (const lldb::SBStream &stream) const
lldb::ThreadSP GetOpaqueTypeFromSBThread (const lldb::SBThread &exe_ctx) const
lldb::StackFrameSP GetOpaqueTypeFromSBFrame (const lldb::SBFrame &frame) const
SymbolContext GetOpaqueTypeFromSBSymbolContext (const lldb::SBSymbolContext &sym_ctx) const
lldb::BreakpointSP GetOpaqueTypeFromSBBreakpoint (const lldb::SBBreakpoint &breakpoint) const
lldb::BreakpointLocationSP GetOpaqueTypeFromSBBreakpointLocation (const lldb::SBBreakpointLocation &break_loc) const
lldb::ProcessAttachInfoSP GetOpaqueTypeFromSBAttachInfo (const lldb::SBAttachInfo &attach_info) const
lldb::ProcessLaunchInfoSP GetOpaqueTypeFromSBLaunchInfo (const lldb::SBLaunchInfo &launch_info) const
std::optional< MemoryRegionInfo > GetOpaqueTypeFromSBMemoryRegionInfo (const lldb::SBMemoryRegionInfo &mem_region) const
lldb::ExecutionContextRefSP GetOpaqueTypeFromSBExecutionContext (const lldb::SBExecutionContext &exe_ctx) const
lldb::StackFrameListSP GetOpaqueTypeFromSBFrameList (const lldb::SBFrameList &exe_ctx) const
lldb::ValueObjectSP GetOpaqueTypeFromSBValue (const lldb::SBValue &value) const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
virtual llvm::StringRef GetPluginName ()=0
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Public Member Functions inherited from lldb_private::IOHandlerDelegateMultiline
IOHandlerDelegateMultiline (llvm::StringRef end_line, Completion completion=Completion::None)
~IOHandlerDelegateMultiline () override=default
llvm::StringRef IOHandlerGetControlSequence (char ch) override
bool IOHandlerIsInputComplete (IOHandler &io_handler, StringList &lines) override
Called to determine whether typing enter after the last line in lines should end input.
Public Member Functions inherited from lldb_private::IOHandlerDelegate
IOHandlerDelegate (Completion completion=Completion::None)
virtual ~IOHandlerDelegate ()=default
virtual void IOHandlerActivated (IOHandler &io_handler, bool interactive)
virtual void IOHandlerDeactivated (IOHandler &io_handler)
virtual std::optional< std::string > IOHandlerSuggestion (IOHandler &io_handler, llvm::StringRef line)
virtual void IOHandlerComplete (IOHandler &io_handler, CompletionRequest &request)
virtual const char * IOHandlerGetFixIndentationCharacters ()
virtual int IOHandlerFixIndentation (IOHandler &io_handler, const StringList &lines, int cursor_position)
Called when a new line is created or one of an identified set of indentation characters is typed.
virtual void IOHandlerInputComplete (IOHandler &io_handler, std::string &data)=0
Called when a line or lines have been retrieved.
virtual void IOHandlerInputInterrupted (IOHandler &io_handler, std::string &data)
virtual const char * IOHandlerGetCommandPrefix ()
virtual const char * IOHandlerGetHelpPrologue ()
virtual bool IOHandlerInterrupt (IOHandler &io_handler)
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static FileSpec GetPythonDir ()
static void SharedLibraryDirectoryHelper (FileSpec &this_file)
Static Public Member Functions inherited from lldb_private::ScriptInterpreter
static std::string LanguageToString (lldb::ScriptLanguage language)
static lldb::ScriptLanguage StringToLanguage (const llvm::StringRef &string)
Static Protected Member Functions
static void ComputePythonDirForApple (llvm::SmallVectorImpl< char > &path)
static void ComputePythonDir (llvm::SmallVectorImpl< char > &path)
Additional Inherited Members
Public Types inherited from lldb_private::ScriptInterpreter
enum ScriptReturnType {
eScriptReturnTypeCharPtr , eScriptReturnTypeBool , eScriptReturnTypeShortInt , eScriptReturnTypeShortIntUnsigned ,
eScriptReturnTypeInt , eScriptReturnTypeIntUnsigned , eScriptReturnTypeLongInt , eScriptReturnTypeLongIntUnsigned ,
eScriptReturnTypeLongLong , eScriptReturnTypeLongLongUnsigned , eScriptReturnTypeFloat , eScriptReturnTypeDouble ,
eScriptReturnTypeChar , eScriptReturnTypeCharStrOrNone , eScriptReturnTypeOpaqueObject
}
Public Types inherited from lldb_private::IOHandlerDelegate
enum class Completion { None , LLDBCommand , Expression }
Protected Attributes inherited from lldb_private::ScriptInterpreter
Debugger & m_debugger
lldb::ScriptLanguage m_script_lang
Protected Attributes inherited from lldb_private::IOHandlerDelegateMultiline
const std::string m_end_line
Protected Attributes inherited from lldb_private::IOHandlerDelegate
Completion m_completion
Detailed Description
Abstract interface for the Python script interpreter.
Definition at line 24 of file ScriptInterpreterPython.h.
Constructor & Destructor Documentation
ScriptInterpreterPython()
lldb_private::ScriptInterpreterPython::ScriptInterpreterPython (Debugger & debugger) inline
Definition at line 40 of file ScriptInterpreterPython.h.
References lldb_private::IOHandlerDelegateMultiline::IOHandlerDelegateMultiline(), and lldb_private::ScriptInterpreter::ScriptInterpreter().
Referenced by lldb_private::ScriptInterpreterPythonImpl::ScriptInterpreterPythonImpl().
Member Function Documentation
ComputePythonDir()
void ScriptInterpreterPython::ComputePythonDir (llvm::SmallVectorImpl< char > & path) static protected
Definition at line 197 of file ScriptInterpreterPython.cpp.
Referenced by ComputePythonDirForApple(), and GetPythonDir().
ComputePythonDirForApple()
void ScriptInterpreterPython::ComputePythonDirForApple (llvm::SmallVectorImpl< char > & path) static protected
Definition at line 181 of file ScriptInterpreterPython.cpp.
References ComputePythonDir().
Referenced by GetPythonDir().
GetInterpreterInfo()
StructuredData::DictionarySP ScriptInterpreterPython::GetInterpreterInfo () override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 247 of file ScriptInterpreterPython.cpp.
References lldb_private::python::As(), GetInterpreterInfoScript, lldb_private::FileSpec::GetPath(), GetPythonDir(), python_exe_relative_path, and lldb_private::python::unwrapIgnoringErrors().
GetPluginDescriptionStatic()
llvm::StringRef ScriptInterpreterPython::GetPluginDescriptionStatic () static
Definition at line 288 of file ScriptInterpreterPython.cpp.
Referenced by Initialize().
GetPluginNameStatic()
llvm::StringRef lldb_private::ScriptInterpreterPython::GetPluginNameStatic () inline static
Definition at line 47 of file ScriptInterpreterPython.h.
Referenced by lldb_private::ScriptInterpreterPythonImpl::GetPluginName(), and Initialize().
GetPythonDir()
FileSpec ScriptInterpreterPython::GetPythonDir () static
Definition at line 212 of file ScriptInterpreterPython.cpp.
References ComputePythonDir(), ComputePythonDirForApple(), lldb_private::FileSpec::GetPath(), and lldb_private::FileSpec::SetDirectory().
Referenced by GetInterpreterInfo(), and Initialize().
Initialize()
void ScriptInterpreterPython::Initialize () static
Definition at line 292 of file ScriptInterpreterPython.cpp.
References lldb_private::ScriptInterpreterPythonImpl::CreateInstance(), lldb::eScriptLanguagePython, GetPluginDescriptionStatic(), GetPluginNameStatic(), GetPythonDir(), lldb_private::ScriptInterpreterPythonImpl::Initialize(), lldb_private::ScriptInterpreterPythonInterfaces::Initialize(), and lldb_private::PluginManager::RegisterPlugin().
SharedLibraryDirectoryHelper()
void ScriptInterpreterPython::SharedLibraryDirectoryHelper (FileSpec & this_file) static
Definition at line 261 of file ScriptInterpreterPython.cpp.
References lldb_private::FileSpec::AppendPathComponent(), lldb_private::FileSpec::GetFileNameExtension(), lldb_private::FileSystem::Instance(), lldb_private::FileSpec::RemoveLastPathComponent(), and lldb_private::FileSystem::ResolveSymbolicLink().
Terminate()
void ScriptInterpreterPython::Terminate () static
Definition at line 305 of file ScriptInterpreterPython.cpp.
References lldb_private::ScriptInterpreterPythonInterfaces::Terminate().
The documentation for this class was generated from the following files:
ScriptInterpreterPython.h
ScriptInterpreterPython.cpp