LLDB: lldb::SBBreakpointNameImpl Class Reference
lldb::SBBreakpointNameImpl Class Reference
Public Member Functions
SBBreakpointNameImpl (TargetSP target_sp, const char *name)
SBBreakpointNameImpl (SBTarget &sb_target, const char *name)
bool operator== (const SBBreakpointNameImpl &rhs)
bool operator!= (const SBBreakpointNameImpl &rhs)
TargetSP GetTarget () const
const char * GetName () const
bool IsValid () const
lldb_private::BreakpointName * GetBreakpointName () const
Private Attributes
TargetWP m_target_wp
std::string m_name
Detailed Description
Definition at line 35 of file SBBreakpointName.cpp.
Constructor & Destructor Documentation
SBBreakpointNameImpl() [1/2]
lldb::SBBreakpointNameImpl::SBBreakpointNameImpl (TargetSP target_sp, const char * name) inline
Definition at line 37 of file SBBreakpointName.cpp.
References m_name, and m_target_wp.
Referenced by operator!=(), and operator==().
SBBreakpointNameImpl() [2/2]
lldb::SBBreakpointNameImpl::SBBreakpointNameImpl (SBTarget & sb_target, const char * name)
Definition at line 74 of file SBBreakpointName.cpp.
References lldb::SBTarget::GetSP(), lldb::SBTarget::IsValid(), m_name, and m_target_wp.
Member Function Documentation
GetBreakpointName()
lldb_private::BreakpointName * lldb::SBBreakpointNameImpl::GetBreakpointName () const
Definition at line 98 of file SBBreakpointName.cpp.
References error(), GetTarget(), IsValid(), and m_name.
GetName()
const char * lldb::SBBreakpointNameImpl::GetName () const inline
Definition at line 59 of file SBBreakpointName.cpp.
References m_name.
GetTarget()
TargetSP lldb::SBBreakpointNameImpl::GetTarget () const inline
Definition at line 55 of file SBBreakpointName.cpp.
References m_target_wp.
Referenced by GetBreakpointName().
IsValid()
bool lldb::SBBreakpointNameImpl::IsValid () const inline
Definition at line 63 of file SBBreakpointName.cpp.
References m_name, and m_target_wp.
Referenced by GetBreakpointName().
operator!=()
bool lldb::SBBreakpointNameImpl::operator!= (const SBBreakpointNameImpl & rhs)
Definition at line 94 of file SBBreakpointName.cpp.
References m_name, m_target_wp, and SBBreakpointNameImpl().
operator==()
bool lldb::SBBreakpointNameImpl::operator== (const SBBreakpointNameImpl & rhs)
Definition at line 90 of file SBBreakpointName.cpp.
References m_name, m_target_wp, and SBBreakpointNameImpl().
Member Data Documentation
m_name
std::string lldb::SBBreakpointNameImpl::m_name private
Definition at line 71 of file SBBreakpointName.cpp.
Referenced by GetBreakpointName(), GetName(), IsValid(), operator!=(), operator==(), SBBreakpointNameImpl(), and SBBreakpointNameImpl().
m_target_wp
TargetWP lldb::SBBreakpointNameImpl::m_target_wp private
Definition at line 70 of file SBBreakpointName.cpp.
Referenced by GetTarget(), IsValid(), operator!=(), operator==(), SBBreakpointNameImpl(), and SBBreakpointNameImpl().
The documentation for this class was generated from the following file:
SBBreakpointName.cpp