LLDB: sddarwinlog_private::StructuredDataDarwinLogProperties Class Reference
sddarwinlog_private::StructuredDataDarwinLogProperties Class Reference
Public Member Functions
StructuredDataDarwinLogProperties ()
~StructuredDataDarwinLogProperties () override=default
bool GetEnableOnStartup () const
llvm::StringRef GetAutoEnableOptions () const
const char * GetLoggingModuleName () const
Public Member Functions inherited from lldb_private::Properties
Properties ()
Properties (const lldb::OptionValuePropertiesSP &collection_sp)
virtual ~Properties ()
lldb::OptionValuePropertiesSP GetValueProperties () const
virtual lldb::OptionValueSP GetPropertyValue (const ExecutionContext *exe_ctx, llvm::StringRef property_path, Status &error) const
virtual Status SetPropertyValue (const ExecutionContext *exe_ctx, VarSetOperationType op, llvm::StringRef property_path, llvm::StringRef value)
virtual Status DumpPropertyValue (const ExecutionContext *exe_ctx, Stream &strm, llvm::StringRef property_path, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllPropertyValues (const ExecutionContext *exe_ctx, Stream &strm, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllDescriptions (CommandInterpreter &interpreter, Stream &strm) const
size_t Apropos (llvm::StringRef keyword, std::vector< const Property * > &matching_properties) const
template<typename T>
T GetPropertyAtIndexAs (uint32_t idx, T default_value, const ExecutionContext *exe_ctx=nullptr) const
template<typename T, typename U = typename std::remove_pointer<T>::type, std::enable_if_t< std::is_pointer_v< T >, bool > = true>
const U * GetPropertyAtIndexAs (uint32_t idx, const ExecutionContext *exe_ctx=nullptr) const
template<typename T>
bool SetPropertyAtIndex (uint32_t idx, T t, const ExecutionContext *exe_ctx=nullptr) const
Static Public Member Functions
static llvm::StringRef GetSettingName ()
Static Public Member Functions inherited from lldb_private::Properties
static llvm::StringRef GetExperimentalSettingsName ()
static bool IsSettingExperimental (llvm::StringRef setting)
Additional Inherited Members
Protected Attributes inherited from lldb_private::Properties
lldb::OptionValuePropertiesSP m_collection_sp
Detailed Description
Definition at line 120 of file StructuredDataDarwinLog.cpp.
Constructor & Destructor Documentation
StructuredDataDarwinLogProperties()
sddarwinlog_private::StructuredDataDarwinLogProperties::StructuredDataDarwinLogProperties () inline
Definition at line 127 of file StructuredDataDarwinLog.cpp.
References GetSettingName(), lldb_private::Properties::m_collection_sp, and lldb_private::Properties::Properties().
~StructuredDataDarwinLogProperties()
sddarwinlog_private::StructuredDataDarwinLogProperties::~StructuredDataDarwinLogProperties () override default
Member Function Documentation
GetAutoEnableOptions()
llvm::StringRef sddarwinlog_private::StructuredDataDarwinLogProperties::GetAutoEnableOptions () const inline
Definition at line 140 of file StructuredDataDarwinLog.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by sddarwinlog_private::RunEnableCommand().
GetEnableOnStartup()
bool sddarwinlog_private::StructuredDataDarwinLogProperties::GetEnableOnStartup () const inline
Definition at line 134 of file StructuredDataDarwinLog.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetLoggingModuleName()
const char * sddarwinlog_private::StructuredDataDarwinLogProperties::GetLoggingModuleName () const inline
Definition at line 146 of file StructuredDataDarwinLog.cpp.
GetSettingName()
llvm::StringRef sddarwinlog_private::StructuredDataDarwinLogProperties::GetSettingName () inline static
Definition at line 122 of file StructuredDataDarwinLog.cpp.
Referenced by lldb_private::StructuredDataDarwinLog::DebuggerInitialize(), and StructuredDataDarwinLogProperties().
The documentation for this class was generated from the following file:
StructuredDataDarwinLog.cpp