LLDB: lldb_private::process_freebsd::NativeProcessFreeBSD Class Reference
lldb_private::process_freebsd::NativeProcessFreeBSD Class Reference
Manages communication with the inferior (debugee) process.
#include <NativeProcessFreeBSD.h>
Classes
class Manager
Public Member Functions
Status Resume (const ResumeActionList &resume_actions) override
Status Halt () override
Status Detach () override
Status Signal (int signo) override
Sends a process a UNIX signal signal.
Status Interrupt () override
Tells a process to interrupt all operations as if by a Ctrl-C.
Status Kill () override
Status GetMemoryRegionInfo (lldb::addr_t load_addr, MemoryRegionInfo &range_info) override
Status ReadMemory (lldb::addr_t addr, void *buf, size_t size, size_t &bytes_read) override
Status WriteMemory (lldb::addr_t addr, const void *buf, size_t size, size_t &bytes_written) override
size_t UpdateThreads () override
const ArchSpec & GetArchitecture () const override
Status SetBreakpoint (lldb::addr_t addr, uint32_t size, bool hardware) override
Status GetLoadedModuleFileSpec (const char *module_path, FileSpec &file_spec) override
Status GetFileLoadAddress (const llvm::StringRef &file_name, lldb::addr_t &load_addr) override
llvm::ErrorOr< std::unique_ptr< llvm::MemoryBuffer > > GetAuxvData () const override
llvm::Expected< std::string > SaveCore (llvm::StringRef path_hint) override
Write a core dump (without crashing the program).
Public Member Functions inherited from lldb_private::NativeProcessELF
std::optional< uint64_t > GetAuxValue (enum AuxVector::EntryType type)
Public Member Functions inherited from lldb_private::NativeProcessProtocol
virtual ~NativeProcessProtocol ()=default
virtual Status IgnoreSignals (llvm::ArrayRef< int > signals)
Status ReadMemoryWithoutTrap (lldb::addr_t addr, void *buf, size_t size, size_t &bytes_read)
virtual Status ReadMemoryTags (int32_t type, lldb::addr_t addr, size_t len, std::vector< uint8_t > &tags)
virtual Status WriteMemoryTags (int32_t type, lldb::addr_t addr, size_t len, const std::vector< uint8_t > &tags)
llvm::Expected< llvm::StringRef > ReadCStringFromMemory (lldb::addr_t addr, char *buffer, size_t max_size, size_t &total_bytes_read)
Reads a null terminated string from memory.
virtual llvm::Expected< lldb::addr_t > AllocateMemory (size_t size, uint32_t permissions)
virtual llvm::Error DeallocateMemory (lldb::addr_t addr)
virtual bool IsAlive () const
virtual Status RemoveBreakpoint (lldb::addr_t addr, bool hardware=false)
virtual const HardwareBreakpointMap & GetHardwareBreakpointMap () const
virtual Status SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual Status RemoveHardwareBreakpoint (lldb::addr_t addr)
virtual const NativeWatchpointList::WatchpointMap & GetWatchpointMap () const
virtual std::optional< std::pair< uint32_t, uint32_t > > GetHardwareDebugSupportInfo () const
virtual Status SetWatchpoint (lldb::addr_t addr, size_t size, uint32_t watch_flags, bool hardware)
virtual Status RemoveWatchpoint (lldb::addr_t addr)
lldb::pid_t GetID () const
lldb::StateType GetState () const
bool IsRunning () const
bool IsStepping () const
bool CanResume () const
lldb::ByteOrder GetByteOrder () const
uint32_t GetAddressByteSize () const
virtual std::optional< WaitStatus > GetExitStatus ()
virtual bool SetExitStatus (WaitStatus status, bool bNotifyStateChange)
NativeThreadProtocol * GetThreadAtIndex (uint32_t idx)
NativeThreadProtocol * GetThreadByID (lldb::tid_t tid)
void SetCurrentThreadID (lldb::tid_t tid)
lldb::tid_t GetCurrentThreadID () const
NativeThreadProtocol * GetCurrentThread ()
ThreadIterable Threads () const
virtual int GetTerminalFileDescriptor ()
uint32_t GetStopID () const
virtual void NotifyTracersProcessWillResume ()
Notify tracers that the target process will resume.
virtual void NotifyTracersProcessDidStop ()
Notify tracers that the target process just stopped.
virtual llvm::Error TraceStart (llvm::StringRef json_params, llvm::StringRef type)
Start tracing a process or its threads.
virtual llvm::Error TraceStop (const TraceStopRequest &request)
Stop tracing a live process or its threads.
virtual llvm::Expected< llvm::json::Value > TraceGetState (llvm::StringRef type)
Get the current tracing state of the process and its threads.
virtual llvm::Expected< std::vector< uint8_t > > TraceGetBinaryData (const TraceGetBinaryDataRequest &request)
Get binary data given a trace technology and a data identifier.
virtual llvm::Expected< TraceSupportedResponse > TraceSupported ()
Get the processor tracing type supported for this process.
virtual void SetEnabledExtensions (Extension flags)
Method called in order to propagate the bitmap of protocol extensions supported by the client.
virtual std::vector< std::string > GetStructuredDataPlugins ()
Get the list of structured data plugins supported by this process.
Static Public Member Functions
static Status PtraceWrapper (int req, lldb::pid_t pid, void *addr=nullptr, int data=0, int *result=nullptr)
Protected Member Functions
llvm::Expected< llvm::ArrayRef< uint8_t > > GetSoftwareBreakpointTrapOpcode (size_t size_hint) override
Protected Member Functions inherited from lldb_private::NativeProcessELF
lldb::addr_t GetSharedLibraryInfoAddress () override
template<typename ELF_EHDR, typename ELF_PHDR, typename ELF_DYN>
lldb::addr_t GetELFImageInfoAddress ()
llvm::Expected< std::vector< SVR4LibraryInfo > > GetLoadedSVR4Libraries () override
template<typename T>
llvm::Expected< SVR4LibraryInfo > ReadSVR4LibraryInfo (lldb::addr_t link_map_addr)
void NotifyDidExec () override
Notify the delegate that an exec occurred.
Protected Member Functions inherited from lldb_private::NativeProcessProtocol
NativeProcessProtocol (lldb::pid_t pid, int terminal_fd, NativeDelegate &delegate)
void SetID (lldb::pid_t pid)
void SetState (lldb::StateType state, bool notify_delegates=true)
virtual void DoStopIDBumped (uint32_t newBumpId)
Status SetSoftwareBreakpoint (lldb::addr_t addr, uint32_t size_hint)
Status RemoveSoftwareBreakpoint (lldb::addr_t addr)
virtual size_t GetSoftwareBreakpointPCOffset ()
Return the offset of the PC relative to the software breakpoint that was hit.
void FixupBreakpointPCAsNeeded (NativeThreadProtocol &thread)
NativeThreadProtocol * GetThreadByIDUnlocked (lldb::tid_t tid)
Private Member Functions
NativeProcessFreeBSD (::pid_t pid, int terminal_fd, NativeDelegate &delegate, const ArchSpec &arch, MainLoop &mainloop)
bool HasThreadNoLock (lldb::tid_t thread_id)
NativeThreadFreeBSD & AddThread (lldb::tid_t thread_id)
void RemoveThread (lldb::tid_t thread_id)
void MonitorCallback (lldb::pid_t pid, int signal)
void MonitorExited (lldb::pid_t pid, WaitStatus status)
void MonitorSIGSTOP (lldb::pid_t pid)
void MonitorSIGTRAP (lldb::pid_t pid)
void MonitorSignal (lldb::pid_t pid, int signal)
void MonitorClone (::pid_t child_pid, bool is_vfork, NativeThreadFreeBSD &parent_thread)
Status PopulateMemoryRegionCache ()
void SigchldHandler ()
Status Attach ()
Status SetupTrace ()
Status ReinitializeThreads ()
Private Member Functions inherited from lldb_private::NativeProcessSoftwareSingleStep
Status SetupSoftwareSingleStepping (NativeThreadProtocol &thread)
Private Attributes
MainLoop::SignalHandleUP m_sigchld_handle
ArchSpec m_arch
MainLoop & m_main_loop
LazyBool m_supports_mem_region = eLazyBoolCalculate
std::vector< std::pair< MemoryRegionInfo, FileSpec > > m_mem_region_cache
Private Attributes inherited from lldb_private::NativeProcessSoftwareSingleStep
std::map< lldb::tid_t, std::vector< lldb::addr_t > > m_threads_stepping_with_breakpoint
Additional Inherited Members
Public Types inherited from lldb_private::NativeProcessProtocol
enum class Extension {
multiprocess = (1u << 0) , fork = (1u << 1) , vfork = (1u << 2) , pass_signals = (1u << 3) ,
auxv = (1u << 4) , libraries_svr4 = (1u << 5) , memory_tagging = (1u << 6) , savecore = (1u << 7) ,
siginfo_read = (1u << 8)
}
Extension flag constants, returned by Manager::GetSupportedExtensions() and passed to SetEnabledExtension()
typedef std::vector< std::unique_ptr< NativeThreadProtocol > > thread_collection
typedef LockingAdaptedIterable< std::recursive_mutex, thread_collection, llvm::pointee_iterator< thread_collection::const_iterator > > ThreadIterable
Protected Attributes inherited from lldb_private::NativeProcessELF
std::unique_ptr< AuxVector > m_aux_vector
std::optional< lldb::addr_t > m_shared_library_info_addr
Protected Attributes inherited from lldb_private::NativeProcessProtocol
std::unordered_map< lldb::addr_t, SoftwareBreakpoint > m_software_breakpoints
lldb::pid_t m_pid
std::vector< std::unique_ptr< NativeThreadProtocol > > m_threads
lldb::tid_t m_current_thread_id = LLDB_INVALID_THREAD_ID
std::recursive_mutex m_threads_mutex
lldb::StateType m_state = lldb::eStateInvalid
std::recursive_mutex m_state_mutex
std::optional< WaitStatus > m_exit_status
NativeDelegate & m_delegate
NativeWatchpointList m_watchpoint_list
HardwareBreakpointMap m_hw_breakpoints_map
int m_terminal_fd
uint32_t m_stop_id = 0
llvm::DenseSet< int > m_signals_to_ignore
Extension m_enabled_extensions
Detailed Description
Manages communication with the inferior (debugee) process.
Upon construction, this class prepares and launches an inferior process for debugging.
Changes in the inferior process state are broadcasted.
Definition at line 30 of file NativeProcessFreeBSD.h.
Constructor & Destructor Documentation
NativeProcessFreeBSD()
NativeProcessFreeBSD::NativeProcessFreeBSD (::pid_t pid, int terminal_fd, NativeDelegate & delegate, const ArchSpec & arch, MainLoop & mainloop) private
Definition at line 161 of file NativeProcessFreeBSD.cpp.
References EnsureFDFlags(), m_arch, m_main_loop, m_sigchld_handle, lldb_private::NativeProcessProtocol::m_terminal_fd, O_NONBLOCK, lldb_private::MainLoopPosix::RegisterSignal(), SigchldHandler(), and lldb_private::Status::Success().
Referenced by lldb_private::process_freebsd::NativeProcessFreeBSD::Manager::Attach(), lldb_private::process_freebsd::NativeProcessFreeBSD::Manager::Launch(), and MonitorClone().
Member Function Documentation
AddThread()
NativeThreadFreeBSD & NativeProcessFreeBSD::AddThread (lldb::tid_t thread_id) private
Definition at line 828 of file NativeProcessFreeBSD.cpp.
References lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), HasThreadNoLock(), LLDB_LOG, lldb_private::NativeProcessProtocol::m_threads, lldb_private::NativeProcessProtocol::SetCurrentThreadID(), and lldb_private::Thread.
Referenced by MonitorSIGTRAP(), and ReinitializeThreads().
Attach()
Status NativeProcessFreeBSD::Attach () private
Definition at line 863 of file NativeProcessFreeBSD.cpp.
References lldb::eErrorTypePOSIX, lldb::eStateStopped, lldb_private::Status::Fail(), lldb_private::NativeProcessProtocol::m_pid, lldb_private::NativeProcessProtocol::m_threads, PtraceWrapper(), lldb_private::NativeProcessProtocol::SetCurrentThreadID(), lldb_private::NativeProcessProtocol::SetState(), lldb_private::process_freebsd::NativeThreadFreeBSD::SetStoppedBySignal(), SetupTrace(), SIGSTOP, and lldb_private::Status.
Detach()
Status NativeProcessFreeBSD::Detach () override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 535 of file NativeProcessFreeBSD.cpp.
References error(), lldb_private::NativeProcessProtocol::GetID(), LLDB_INVALID_PROCESS_ID, m_sigchld_handle, and PtraceWrapper().
GetArchitecture()
const ArchSpec & lldb_private::process_freebsd::NativeProcessFreeBSD::GetArchitecture () const inline override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 71 of file NativeProcessFreeBSD.h.
References m_arch.
Referenced by GetSoftwareBreakpointTrapOpcode().
GetAuxvData()
llvm::ErrorOr< std::unique_ptr< llvm::MemoryBuffer > > NativeProcessFreeBSD::GetAuxvData () const override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 949 of file NativeProcessFreeBSD.cpp.
References lldb_private::NativeProcessProtocol::GetID().
GetFileLoadAddress()
Status NativeProcessFreeBSD::GetFileLoadAddress (const llvm::StringRef & file_name, lldb::addr_t & load_addr) override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 761 of file NativeProcessFreeBSD.cpp.
References CanTrace(), error(), lldb_private::Status::FromErrorStringWithFormat(), LLDB_INVALID_ADDRESS, m_mem_region_cache, PopulateMemoryRegionCache(), and lldb_private::Status.
GetLoadedModuleFileSpec()
Status NativeProcessFreeBSD::GetLoadedModuleFileSpec (const char * module_path, FileSpec & file_spec) override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 735 of file NativeProcessFreeBSD.cpp.
References lldb_private::ConstString::AsCString(), CanTrace(), lldb_private::FileSpec::Clear(), error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::FileSpec::GetFilename(), lldb_private::FileSystem::Instance(), m_mem_region_cache, PopulateMemoryRegionCache(), lldb_private::FileSystem::Resolve(), and lldb_private::Status.
GetMemoryRegionInfo()
Status NativeProcessFreeBSD::GetMemoryRegionInfo (lldb::addr_t load_addr, MemoryRegionInfo & range_info) override virtual
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 590 of file NativeProcessFreeBSD.cpp.
References lldb_private::Range< B, S >::Contains(), lldb_private::eLazyBoolNo, lldb_private::MemoryRegionInfo::eNo, error(), lldb_private::Status::FromErrorString(), lldb_private::MemoryRegionInfo::GetRange(), lldb_private::Range< B, S >::GetRangeBase(), LLDB_INVALID_ADDRESS, m_mem_region_cache, m_supports_mem_region, PopulateMemoryRegionCache(), lldb_private::Range< B, S >::SetByteSize(), lldb_private::MemoryRegionInfo::SetExecutable(), lldb_private::MemoryRegionInfo::SetMapped(), lldb_private::Range< B, S >::SetRangeBase(), lldb_private::Range< B, S >::SetRangeEnd(), lldb_private::MemoryRegionInfo::SetReadable(), lldb_private::MemoryRegionInfo::SetWritable(), and UNUSED_IF_ASSERT_DISABLED.
GetSoftwareBreakpointTrapOpcode()
llvm::Expected< llvm::ArrayRef< uint8_t > > NativeProcessFreeBSD::GetSoftwareBreakpointTrapOpcode (size_t size_hint) override protected virtual
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 437 of file NativeProcessFreeBSD.cpp.
References GetArchitecture(), and lldb_private::NativeProcessProtocol::GetSoftwareBreakpointTrapOpcode().
Halt()
Status NativeProcessFreeBSD::Halt () override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 523 of file NativeProcessFreeBSD.cpp.
References error(), lldb_private::Status::FromErrno(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::NativeProcessProtocol::m_state, SIGSTOP, and lldb_private::StateIsStoppedState().
Referenced by Interrupt().
HasThreadNoLock()
bool NativeProcessFreeBSD::HasThreadNoLock (lldb::tid_t thread_id) private
Definition at line 815 of file NativeProcessFreeBSD.cpp.
References lldb_private::NativeProcessProtocol::m_threads.
Referenced by AddThread(), and RemoveThread().
Interrupt()
Status NativeProcessFreeBSD::Interrupt () override virtual
Tells a process to interrupt all operations as if by a Ctrl-C.
The default implementation will send a local host's equivalent of a SIGSTOP to the process via the NativeProcessProtocol::Signal() operation.
Returns
Returns an error object.
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 557 of file NativeProcessFreeBSD.cpp.
References Halt().
Kill()
Status NativeProcessFreeBSD::Kill () override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 559 of file NativeProcessFreeBSD.cpp.
References error(), lldb::eStateAttaching, lldb::eStateConnected, lldb::eStateCrashed, lldb::eStateDetached, lldb::eStateExited, lldb::eStateInvalid, lldb::eStateLaunching, lldb::eStateRunning, lldb::eStateStepping, lldb::eStateStopped, lldb::eStateSuspended, lldb::eStateUnloaded, lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), LLDB_LOG, lldb_private::NativeProcessProtocol::m_pid, lldb_private::NativeProcessProtocol::m_state, lldb_private::Process, PtraceWrapper(), and lldb_private::StateAsCString().
MonitorCallback()
void NativeProcessFreeBSD::MonitorCallback (lldb::pid_t pid, int signal) private
Definition at line 179 of file NativeProcessFreeBSD.cpp.
References MonitorSignal(), MonitorSIGSTOP(), MonitorSIGTRAP(), SIGSTOP, and SIGTRAP.
Referenced by SigchldHandler().
MonitorClone()
void NativeProcessFreeBSD::MonitorClone (::pid_t child_pid, bool is_vfork, NativeThreadFreeBSD & parent_thread) private
Definition at line 999 of file NativeProcessFreeBSD.cpp.
References lldb::eStateInvalid, lldb::eStateStopped, lldb_private::Status::Fail(), lldb_private::NativeProcessProtocol::fork, lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), LLDB_LOG, LLDB_LOG_ERROR, m_arch, lldb_private::NativeProcessProtocol::m_delegate, lldb_private::NativeProcessProtocol::m_enabled_extensions, m_main_loop, lldb_private::NativeProcessProtocol::m_software_breakpoints, lldb_private::NativeProcessProtocol::m_terminal_fd, NativeProcessFreeBSD(), lldb_private::Process, PtraceWrapper(), lldb_private::NativeProcessProtocol::SetState(), lldb_private::process_freebsd::NativeThreadFreeBSD::SetStoppedByFork(), lldb_private::process_freebsd::NativeThreadFreeBSD::SetStoppedBySignal(), lldb_private::process_freebsd::NativeThreadFreeBSD::SetStoppedByVFork(), SIGSTOP, lldb_private::Status::ToError(), and lldb_private::NativeProcessProtocol::vfork.
Referenced by MonitorSIGTRAP().
MonitorExited()
void NativeProcessFreeBSD::MonitorExited (lldb::pid_t pid, WaitStatus status) private
Definition at line 190 of file NativeProcessFreeBSD.cpp.
References lldb::eStateExited, lldb_private::GetLog(), LLDB_LOG, lldb_private::NativeProcessProtocol::m_threads, lldb_private::Process, lldb_private::NativeProcessProtocol::SetExitStatus(), and lldb_private::NativeProcessProtocol::SetState().
Referenced by SigchldHandler().
MonitorSignal()
void NativeProcessFreeBSD::MonitorSignal (lldb::pid_t pid, int signal) private
Definition at line 381 of file NativeProcessFreeBSD.cpp.
References lldb::eStateStopped, lldb_private::GetLog(), LLDB_LOG, lldb_private::NativeProcessProtocol::m_threads, lldb_private::Process, PtraceWrapper(), lldb_private::NativeProcessProtocol::SetCurrentThreadID(), and lldb_private::NativeProcessProtocol::SetState().
Referenced by MonitorCallback(), and MonitorSIGTRAP().
MonitorSIGSTOP()
void NativeProcessFreeBSD::MonitorSIGSTOP (lldb::pid_t pid) private
Definition at line 204 of file NativeProcessFreeBSD.cpp.
References lldb::eStateStopped, lldb_private::NativeProcessProtocol::m_threads, lldb_private::NativeProcessProtocol::SetState(), lldb_private::process_freebsd::NativeThreadFreeBSD::SetStoppedBySignal(), and SIGSTOP.
Referenced by MonitorCallback().
MonitorSIGTRAP()
void NativeProcessFreeBSD::MonitorSIGTRAP (lldb::pid_t pid) private
Definition at line 213 of file NativeProcessFreeBSD.cpp.
References AddThread(), lldb_private::process_freebsd::NativeThreadFreeBSD::CopyWatchpointsFrom(), error(), lldb::eStateInvalid, lldb::eStateStopped, lldb_private::Status::Fail(), lldb_private::NativeProcessProtocol::FixupBreakpointPCAsNeeded(), lldb_private::NativeProcessProtocol::GetCurrentThread(), lldb_private::GetLog(), LLDB_INVALID_INDEX32, LLDB_LOG, LLDB_LOG_ERROR, lldb_private::NativeProcessProtocol::m_enabled_extensions, lldb_private::NativeProcessProtocol::m_threads, lldb_private::NativeProcessSoftwareSingleStep::m_threads_stepping_with_breakpoint, MonitorClone(), MonitorSignal(), lldb_private::NativeProcessELF::NotifyDidExec(), lldb_private::Process, PtraceWrapper(), ReinitializeThreads(), lldb_private::NativeProcessProtocol::RemoveBreakpoint(), RemoveThread(), lldb_private::NativeProcessProtocol::SetCurrentThreadID(), lldb_private::NativeProcessProtocol::SetState(), lldb_private::process_freebsd::NativeThreadFreeBSD::SetStoppedByExec(), lldb_private::process_freebsd::NativeThreadFreeBSD::SetStoppedWithNoReason(), SIGTRAP, and lldb_private::NativeProcessProtocol::vfork.
Referenced by MonitorCallback().
PopulateMemoryRegionCache()
Status NativeProcessFreeBSD::PopulateMemoryRegionCache () private
Definition at line 646 of file NativeProcessFreeBSD.cpp.
References lldb_private::MemoryRegionInfo::Clear(), lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb_private::MemoryRegionInfo::eNo, lldb_private::MemoryRegionInfo::eYes, lldb_private::Status::FromErrorString(), lldb_private::ConstString::GetCString(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), lldb_private::MemoryRegionInfo::GetName(), lldb_private::MemoryRegionInfo::GetRange(), LLDB_LOG, m_mem_region_cache, lldb_private::NativeProcessProtocol::m_pid, m_supports_mem_region, lldb_private::Process, lldb_private::MemoryRegionInfo::SetExecutable(), lldb_private::MemoryRegionInfo::SetMapped(), lldb_private::MemoryRegionInfo::SetName(), lldb_private::Range< B, S >::SetRangeBase(), lldb_private::Range< B, S >::SetRangeEnd(), lldb_private::MemoryRegionInfo::SetReadable(), lldb_private::MemoryRegionInfo::SetWritable(), and lldb_private::Status.
Referenced by GetFileLoadAddress(), GetLoadedModuleFileSpec(), and GetMemoryRegionInfo().
PtraceWrapper()
Status NativeProcessFreeBSD::PtraceWrapper (int req, lldb::pid_t pid, void * addr = nullptr, int data = 0, int * result = nullptr) static
Definition at line 409 of file NativeProcessFreeBSD.cpp.
References CanTrace(), error(), lldb_private::Status::FromErrno(), lldb_private::GetLog(), LLDB_LOG, and lldb_private::Ptrace.
Referenced by Attach(), Detach(), lldb_private::process_freebsd::NativeThreadFreeBSD::GetSiginfo(), Kill(), MonitorClone(), MonitorSignal(), MonitorSIGTRAP(), ReadMemory(), ReinitializeThreads(), Resume(), lldb_private::process_freebsd::NativeThreadFreeBSD::Resume(), SaveCore(), SetupTrace(), lldb_private::process_freebsd::NativeThreadFreeBSD::SingleStep(), lldb_private::process_freebsd::NativeThreadFreeBSD::Suspend(), and WriteMemory().
ReadMemory()
Status NativeProcessFreeBSD::ReadMemory (lldb::addr_t addr, void * buf, size_t size, size_t & bytes_read) override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 892 of file NativeProcessFreeBSD.cpp.
References error(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), LLDB_LOG, lldb_private::Memory, PtraceWrapper(), and lldb_private::Status.
ReinitializeThreads()
Status NativeProcessFreeBSD::ReinitializeThreads () private
Definition at line 976 of file NativeProcessFreeBSD.cpp.
References AddThread(), error(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::NativeProcessProtocol::m_threads, and PtraceWrapper().
Referenced by MonitorSIGTRAP(), and SetupTrace().
RemoveThread()
void NativeProcessFreeBSD::RemoveThread (lldb::tid_t thread_id) private
Definition at line 844 of file NativeProcessFreeBSD.cpp.
References lldb_private::NativeProcessProtocol::GetCurrentThreadID(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), HasThreadNoLock(), LLDB_LOG, lldb_private::NativeProcessProtocol::m_threads, lldb_private::NativeProcessProtocol::SetCurrentThreadID(), and lldb_private::Thread.
Referenced by MonitorSIGTRAP().
Resume()
Status NativeProcessFreeBSD::Resume (const ResumeActionList & resume_actions) override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 457 of file NativeProcessFreeBSD.cpp.
References lldb::eStateRunning, lldb::eStateStepping, lldb::eStateStopped, lldb::eStateSuspended, lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::ResumeActionList::GetActionForThread(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), LLDB_INVALID_SIGNAL_NUMBER, LLDB_LOG, lldb_private::NativeProcessProtocol::m_threads, lldb_private::Process, PtraceWrapper(), lldb_private::NativeProcessProtocol::SetState(), lldb_private::ResumeAction::signal, lldb_private::ResumeAction::state, lldb_private::StateAsCString(), and lldb_private::Status::Success().
SaveCore()
llvm::Expected< std::string > NativeProcessFreeBSD::SaveCore (llvm::StringRef path_hint) override virtual
Write a core dump (without crashing the program).
Parameters
[in] path_hint Suggested core dump path (optional, can be empty).
Returns
Path to the core dump if successfully written, an error otherwise.
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 1064 of file NativeProcessFreeBSD.cpp.
References error(), lldb_private::NativeProcessProtocol::GetID(), pc, and PtraceWrapper().
SetBreakpoint()
Status NativeProcessFreeBSD::SetBreakpoint (lldb::addr_t addr, uint32_t size, bool hardware) override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 728 of file NativeProcessFreeBSD.cpp.
References lldb_private::NativeProcessProtocol::SetHardwareBreakpoint(), and lldb_private::NativeProcessProtocol::SetSoftwareBreakpoint().
SetupTrace()
Status NativeProcessFreeBSD::SetupTrace () private
Definition at line 961 of file NativeProcessFreeBSD.cpp.
References lldb_private::Status::Fail(), lldb_private::NativeProcessProtocol::GetID(), PtraceWrapper(), and ReinitializeThreads().
Referenced by Attach().
SigchldHandler()
void NativeProcessFreeBSD::SigchldHandler () private
Definition at line 783 of file NativeProcessFreeBSD.cpp.
References lldb_private::WaitStatus::Decode(), lldb::eErrorTypePOSIX, error(), lldb_private::WaitStatus::Exit, lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), LLDB_LOG, MonitorCallback(), MonitorExited(), lldb_private::Process, lldb_private::WaitStatus::Signal, lldb_private::WaitStatus::status, lldb_private::WaitStatus::Stop, and lldb_private::WaitStatus::type.
Referenced by NativeProcessFreeBSD().
Signal()
Status NativeProcessFreeBSD::Signal (int signo) override virtual
Sends a process a UNIX signal signal.
Returns
Returns an error object.
Implements lldb_private::NativeProcessProtocol.
Definition at line 548 of file NativeProcessFreeBSD.cpp.
References error(), lldb_private::Status::FromErrno(), and lldb_private::NativeProcessProtocol::GetID().
UpdateThreads()
size_t NativeProcessFreeBSD::UpdateThreads () override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 726 of file NativeProcessFreeBSD.cpp.
References lldb_private::NativeProcessProtocol::m_threads.
WriteMemory()
Status NativeProcessFreeBSD::WriteMemory (lldb::addr_t addr, const void * buf, size_t size, size_t & bytes_written) override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 919 of file NativeProcessFreeBSD.cpp.
References error(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), LLDB_LOG, lldb_private::Memory, and PtraceWrapper().
Member Data Documentation
m_arch
ArchSpec lldb_private::process_freebsd::NativeProcessFreeBSD::m_arch private
Definition at line 101 of file NativeProcessFreeBSD.h.
Referenced by GetArchitecture(), MonitorClone(), and NativeProcessFreeBSD().
m_main_loop
MainLoop& lldb_private::process_freebsd::NativeProcessFreeBSD::m_main_loop private
Definition at line 102 of file NativeProcessFreeBSD.h.
Referenced by MonitorClone(), and NativeProcessFreeBSD().
m_mem_region_cache
std::vector<std::pair<MemoryRegionInfo, FileSpec> > lldb_private::process_freebsd::NativeProcessFreeBSD::m_mem_region_cache private
Definition at line 104 of file NativeProcessFreeBSD.h.
Referenced by GetFileLoadAddress(), GetLoadedModuleFileSpec(), GetMemoryRegionInfo(), and PopulateMemoryRegionCache().
m_sigchld_handle
MainLoop::SignalHandleUP lldb_private::process_freebsd::NativeProcessFreeBSD::m_sigchld_handle private
Definition at line 100 of file NativeProcessFreeBSD.h.
Referenced by Detach(), and NativeProcessFreeBSD().
m_supports_mem_region
LazyBool lldb_private::process_freebsd::NativeProcessFreeBSD::m_supports_mem_region = eLazyBoolCalculate private
Definition at line 103 of file NativeProcessFreeBSD.h.
Referenced by GetMemoryRegionInfo(), and PopulateMemoryRegionCache().
The documentation for this class was generated from the following files:
NativeProcessFreeBSD.h
NativeProcessFreeBSD.cpp