LLDB: lldb_private::TargetStats Class Reference
lldb_private::TargetStats Class Reference
A class that represents statistics for a since lldb_private::Target.
#include <Statistics.h>
Public Member Functions
llvm::json::Value ToJSON (Target &target, const lldb_private::StatisticsOptions &options)
void SetLaunchOrAttachTime ()
void SetFirstPrivateStopTime ()
void SetFirstPublicStopTime ()
void IncreaseSourceMapDeduceCount ()
void IncreaseSourceRealpathAttemptCount (uint32_t count)
void IncreaseSourceRealpathCompatibleCount (uint32_t count)
StatsDuration & GetCreateTime ()
StatsDuration & GetLoadCoreTime ()
StatsSuccessFail & GetExpressionStats ()
StatsSuccessFail & GetFrameVariableStats ()
void Reset (Target &target)
Protected Member Functions
void CollectStats (Target &target)
Protected Attributes
StatsDuration m_create_time
StatsDuration m_load_core_time
std::optional< StatsTimepoint > m_launch_or_attach_time
std::optional< StatsTimepoint > m_first_private_stop_time
std::optional< StatsTimepoint > m_first_public_stop_time
StatsSuccessFail m_expr_eval {"expressionEvaluation"}
StatsSuccessFail m_frame_var {"frameVariable"}
std::vector< intptr_t > m_module_identifiers
uint32_t m_source_map_deduce_count = 0
uint32_t m_source_realpath_attempt_count = 0
uint32_t m_source_realpath_compatible_count = 0
Detailed Description
A class that represents statistics for a since lldb_private::Target.
Definition at line 312 of file Statistics.h.
Member Function Documentation
CollectStats()
void TargetStats::CollectStats (Target & target) protected
Definition at line 46 of file Statistics.cpp.
References lldb_private::Target::GetImages(), m_module_identifiers, and lldb_private::ModuleList::Modules().
Referenced by ToJSON().
GetCreateTime()
StatsDuration & lldb_private::TargetStats::GetCreateTime () inline
Definition at line 324 of file Statistics.h.
References m_create_time.
GetExpressionStats()
StatsSuccessFail & lldb_private::TargetStats::GetExpressionStats () inline
Definition at line 326 of file Statistics.h.
References m_expr_eval.
GetFrameVariableStats()
StatsSuccessFail & lldb_private::TargetStats::GetFrameVariableStats () inline
Definition at line 327 of file Statistics.h.
References m_frame_var.
GetLoadCoreTime()
StatsDuration & lldb_private::TargetStats::GetLoadCoreTime () inline
Definition at line 325 of file Statistics.h.
References m_load_core_time.
IncreaseSourceMapDeduceCount()
void TargetStats::IncreaseSourceMapDeduceCount ()
Definition at line 265 of file Statistics.cpp.
References m_source_map_deduce_count.
Referenced by lldb_private::BreakpointResolverFileLine::DeduceSourceMapping().
IncreaseSourceRealpathAttemptCount()
void TargetStats::IncreaseSourceRealpathAttemptCount (uint32_t count)
Definition at line 269 of file Statistics.cpp.
References m_source_realpath_attempt_count.
Referenced by lldb_private::BreakpointResolverFileLine::SearchCallback().
IncreaseSourceRealpathCompatibleCount()
void TargetStats::IncreaseSourceRealpathCompatibleCount (uint32_t count)
Definition at line 273 of file Statistics.cpp.
References m_source_realpath_compatible_count.
Referenced by lldb_private::BreakpointResolverFileLine::SearchCallback().
Reset()
void TargetStats::Reset (Target & target)
Definition at line 226 of file Statistics.cpp.
References lldb_private::BreakpointList::GetBreakpointAtIndex(), lldb_private::Target::GetBreakpointList(), lldb_private::BreakpointList::GetListMutex(), lldb_private::BreakpointList::GetSize(), lldb_private::Target::GetSummaryStatisticsCache(), m_first_private_stop_time, m_first_public_stop_time, m_launch_or_attach_time, lldb_private::SummaryStatisticsCache::Reset(), and lldb_private::Breakpoint::ResetStatistics().
SetFirstPrivateStopTime()
void TargetStats::SetFirstPrivateStopTime ()
Definition at line 249 of file Statistics.cpp.
References m_first_private_stop_time.
Referenced by lldb_private::Process::SetPrivateState().
SetFirstPublicStopTime()
void TargetStats::SetFirstPublicStopTime ()
Definition at line 257 of file Statistics.cpp.
References m_first_public_stop_time.
Referenced by lldb_private::Process::SetPublicState().
SetLaunchOrAttachTime()
void TargetStats::SetLaunchOrAttachTime ()
Definition at line 244 of file Statistics.cpp.
References m_first_private_stop_time, and m_launch_or_attach_time.
ToJSON()
json::Value TargetStats::ToJSON (Target & target, const lldb_private::StatisticsOptions & options)
Definition at line 119 of file Statistics.cpp.
References CollectStats(), elapsed(), lldb_private::BreakpointList::GetBreakpointAtIndex(), lldb_private::Breakpoint::GetBreakpointKind(), lldb_private::Target::GetBreakpointList(), lldb_private::Breakpoint::GetHitCount(), lldb_private::StatisticsOptions::GetIncludeModules(), lldb_private::BreakpointList::GetListMutex(), lldb_private::Target::GetProcessSP(), lldb_private::Breakpoint::GetResolveTime(), lldb_private::BreakpointList::GetSize(), lldb_private::Breakpoint::GetStatistics(), lldb_private::StatisticsOptions::GetSummaryOnly(), lldb_private::Target::GetSummaryStatisticsCache(), m_create_time, m_expr_eval, m_first_private_stop_time, m_first_public_stop_time, m_frame_var, m_launch_or_attach_time, m_load_core_time, m_module_identifiers, m_source_map_deduce_count, m_source_realpath_attempt_count, m_source_realpath_compatible_count, and lldb_private::SummaryStatisticsCache::ToJSON().
Member Data Documentation
m_create_time
StatsDuration lldb_private::TargetStats::m_create_time protected
Definition at line 331 of file Statistics.h.
Referenced by GetCreateTime(), and ToJSON().
m_expr_eval
StatsSuccessFail lldb_private::TargetStats::m_expr_eval {"expressionEvaluation"} protected
Definition at line 336 of file Statistics.h.
Referenced by GetExpressionStats(), and ToJSON().
m_first_private_stop_time
std::optional<StatsTimepoint> lldb_private::TargetStats::m_first_private_stop_time protected
Definition at line 334 of file Statistics.h.
Referenced by Reset(), SetFirstPrivateStopTime(), SetLaunchOrAttachTime(), and ToJSON().
m_first_public_stop_time
std::optional<StatsTimepoint> lldb_private::TargetStats::m_first_public_stop_time protected
Definition at line 335 of file Statistics.h.
Referenced by Reset(), SetFirstPublicStopTime(), and ToJSON().
m_frame_var
StatsSuccessFail lldb_private::TargetStats::m_frame_var {"frameVariable"} protected
Definition at line 337 of file Statistics.h.
Referenced by GetFrameVariableStats(), and ToJSON().
m_launch_or_attach_time
std::optional<StatsTimepoint> lldb_private::TargetStats::m_launch_or_attach_time protected
Definition at line 333 of file Statistics.h.
Referenced by Reset(), SetLaunchOrAttachTime(), and ToJSON().
m_load_core_time
StatsDuration lldb_private::TargetStats::m_load_core_time protected
Definition at line 332 of file Statistics.h.
Referenced by GetLoadCoreTime(), and ToJSON().
m_module_identifiers
std::vector<intptr_t> lldb_private::TargetStats::m_module_identifiers protected
Definition at line 338 of file Statistics.h.
Referenced by CollectStats(), and ToJSON().
m_source_map_deduce_count
uint32_t lldb_private::TargetStats::m_source_map_deduce_count = 0 protected
Definition at line 339 of file Statistics.h.
Referenced by IncreaseSourceMapDeduceCount(), and ToJSON().
m_source_realpath_attempt_count
uint32_t lldb_private::TargetStats::m_source_realpath_attempt_count = 0 protected
Definition at line 340 of file Statistics.h.
Referenced by IncreaseSourceRealpathAttemptCount(), and ToJSON().
m_source_realpath_compatible_count
uint32_t lldb_private::TargetStats::m_source_realpath_compatible_count = 0 protected
Definition at line 341 of file Statistics.h.
Referenced by IncreaseSourceRealpathCompatibleCount(), and ToJSON().
The documentation for this class was generated from the following files:
Statistics.h
Statistics.cpp