LLDB: lldb_private::mcp::ProtocolServerMCP Class Reference
lldb_private::mcp::ProtocolServerMCP Class Reference
#include <ProtocolServerMCP.h>
Public Member Functions
ProtocolServerMCP ()
~ProtocolServerMCP () override
llvm::Error Start (ProtocolServer::Connection connection) override
llvm::Error Stop () override
llvm::StringRef GetPluginName () override
Socket * GetSocket () const override
Public Member Functions inherited from lldb_private::ProtocolServer
ProtocolServer ()=default
virtual ~ProtocolServer ()=default
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static lldb::ProtocolServerUP CreateInstance ()
Static Public Member Functions inherited from lldb_private::ProtocolServer
static ProtocolServer * GetOrCreate (llvm::StringRef name)
static llvm::Error Terminate ()
static std::vector< llvm::StringRef > GetSupportedProtocols ()
Protected Member Functions
virtual void Extend (lldb_protocol::mcp::Server &server) const
Private Types
using ServerUP = std::unique_ptr<lldb_protocol::mcp::Server>
using ReadHandleUP = MainLoop::ReadHandleUP
Private Member Functions
void AcceptCallback (std::unique_ptr< Socket > socket)
Private Attributes
bool m_running = false
lldb_private::MainLoop m_loop
std::thread m_loop_thread
std::mutex m_mutex
size_t m_client_count = 0
std::unique_ptr< Socket > m_listener
std::vector< ReadHandleUP > m_accept_handles
ServerUP m_server
lldb_protocol::mcp::ServerInfoHandle m_server_info_handle
Detailed Description
Definition at line 26 of file ProtocolServerMCP.h.
Member Typedef Documentation
ReadHandleUP
using lldb_private::mcp::ProtocolServerMCP::ReadHandleUP = MainLoop::ReadHandleUP private
Definition at line 30 of file ProtocolServerMCP.h.
ServerUP
using lldb_private::mcp::ProtocolServerMCP::ServerUP = std::unique_ptr<lldb_protocol::mcp::Server> private
Definition at line 28 of file ProtocolServerMCP.h.
Constructor & Destructor Documentation
ProtocolServerMCP()
ProtocolServerMCP::ProtocolServerMCP ()
Definition at line 31 of file ProtocolServerMCP.cpp.
References lldb_private::ProtocolServer::ProtocolServer(), and ProtocolServerMCP().
Referenced by ProtocolServerMCP().
~ProtocolServerMCP()
ProtocolServerMCP::~ProtocolServerMCP () override
Definition at line 33 of file ProtocolServerMCP.cpp.
References Stop().
Member Function Documentation
AcceptCallback()
void ProtocolServerMCP::AcceptCallback (std::unique_ptr< Socket > socket) private
Definition at line 62 of file ProtocolServerMCP.cpp.
References error(), lldb_private::GetLog(), lldb_private::Host, LLDB_LOG, LLDB_LOG_ERROR, m_client_count, m_loop, and m_server.
Referenced by Start().
CreateInstance()
lldb::ProtocolServerUP ProtocolServerMCP::CreateInstance () static
Definition at line 46 of file ProtocolServerMCP.cpp.
Referenced by Initialize(), and Terminate().
Extend()
void ProtocolServerMCP::Extend (lldb_protocol::mcp::Server & server) const protected virtual
Definition at line 54 of file ProtocolServerMCP.cpp.
References lldb_protocol::mcp::Server::AddResourceProvider(), and lldb_protocol::mcp::Server::AddTool().
Referenced by Start().
GetPluginDescriptionStatic()
llvm::StringRef ProtocolServerMCP::GetPluginDescriptionStatic () static
Definition at line 50 of file ProtocolServerMCP.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef lldb_private::mcp::ProtocolServerMCP::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 47 of file ProtocolServerMCP.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::mcp::ProtocolServerMCP::GetPluginNameStatic () inline static
Definition at line 42 of file ProtocolServerMCP.h.
Referenced by GetPluginName(), and Initialize().
GetSocket()
Socket * lldb_private::mcp::ProtocolServerMCP::GetSocket () const inline override virtual
Implements lldb_private::ProtocolServer.
Definition at line 49 of file ProtocolServerMCP.h.
References m_listener.
Initialize()
void ProtocolServerMCP::Initialize () static
Definition at line 35 of file ProtocolServerMCP.cpp.
References CreateInstance(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Start()
llvm::Error ProtocolServerMCP::Start (ProtocolServer::Connection connection) override virtual
Implements lldb_private::ProtocolServer.
Definition at line 77 of file ProtocolServerMCP.cpp.
References AcceptCallback(), lldb_private::Socket::Create(), createStringError(), error(), Extend(), lldb_private::Status::Fail(), lldb_private::GetLog(), lldb_private::Host, kName, kVersion, LLDB_LOG, m_accept_handles, m_client_count, m_listener, m_loop, m_loop_thread, m_mutex, m_running, m_server, m_server_info_handle, lldb_private::ProtocolServer::Connection::name, lldb_private::ProtocolServer::Connection::protocol, lldb_private::Status::takeError(), and lldb_protocol::mcp::ServerInfo::Write().
Stop()
llvm::Error ProtocolServerMCP::Stop () override virtual
Implements lldb_private::ProtocolServer.
Definition at line 127 of file ProtocolServerMCP.cpp.
References createStringError(), m_accept_handles, m_listener, m_loop, m_loop_thread, m_mutex, m_running, m_server, m_server_info_handle, and lldb_private::MainLoopBase::RequestTermination().
Referenced by ~ProtocolServerMCP().
Terminate()
void ProtocolServerMCP::Terminate () static
Definition at line 40 of file ProtocolServerMCP.cpp.
References CreateInstance(), error(), lldb_private::GetLog(), lldb_private::Host, LLDB_LOG_ERROR, lldb_private::ProtocolServer::Terminate(), and lldb_private::PluginManager::UnregisterPlugin().
Member Data Documentation
m_accept_handles
std::vector<ReadHandleUP> lldb_private::mcp::ProtocolServerMCP::m_accept_handles private
Definition at line 67 of file ProtocolServerMCP.h.
Referenced by Start(), and Stop().
m_client_count
size_t lldb_private::mcp::ProtocolServerMCP::m_client_count = 0 private
Definition at line 64 of file ProtocolServerMCP.h.
Referenced by AcceptCallback(), and Start().
m_listener
std::unique_ptr<Socket> lldb_private::mcp::ProtocolServerMCP::m_listener private
Definition at line 66 of file ProtocolServerMCP.h.
Referenced by GetSocket(), Start(), and Stop().
m_loop
lldb_private::MainLoop lldb_private::mcp::ProtocolServerMCP::m_loop private
Definition at line 61 of file ProtocolServerMCP.h.
Referenced by AcceptCallback(), Start(), and Stop().
m_loop_thread
std::thread lldb_private::mcp::ProtocolServerMCP::m_loop_thread private
Definition at line 62 of file ProtocolServerMCP.h.
Referenced by Start(), and Stop().
m_mutex
std::mutex lldb_private::mcp::ProtocolServerMCP::m_mutex private
Definition at line 63 of file ProtocolServerMCP.h.
Referenced by Start(), and Stop().
m_running
bool lldb_private::mcp::ProtocolServerMCP::m_running = false private
Definition at line 59 of file ProtocolServerMCP.h.
Referenced by Start(), and Stop().
m_server
ServerUP lldb_private::mcp::ProtocolServerMCP::m_server private
Definition at line 69 of file ProtocolServerMCP.h.
Referenced by AcceptCallback(), Start(), and Stop().
m_server_info_handle
lldb_protocol::mcp::ServerInfoHandle lldb_private::mcp::ProtocolServerMCP::m_server_info_handle private
Definition at line 70 of file ProtocolServerMCP.h.
Referenced by Start(), and Stop().
The documentation for this class was generated from the following files:
ProtocolServerMCP.h
ProtocolServerMCP.cpp