LLDB: lldb_private::breakpad::Record Class Reference
lldb_private::breakpad::Record Class Reference
#include <BreakpadRecords.h>
Public Types
enum Kind {
Module , Info , File , Func ,
Inline , InlineOrigin , Line , Public ,
StackCFI , StackWin
}
Public Member Functions
Kind getKind ()
Static Public Member Functions
static std::optional< Kind > classify (llvm::StringRef Line)
Attempt to guess the kind of the record present in the argument without doing a full parse.
Protected Member Functions
Record (Kind K)
~Record ()=default
Private Attributes
Kind TheKind
Detailed Description
Definition at line 22 of file BreakpadRecords.h.
Member Enumeration Documentation
Kind
enum lldb_private::breakpad::Record::Kind
Enumerator
Module
Info
File
Func
Inline
InlineOrigin
Line
Public
StackCFI
StackWin
Definition at line 24 of file BreakpadRecords.h.
Constructor & Destructor Documentation
Record()
lldb_private::breakpad::Record::Record (Kind K) inline protected
Definition at line 43 of file BreakpadRecords.h.
References TheKind.
Referenced by lldb_private::breakpad::FileRecord::FileRecord(), lldb_private::breakpad::FuncRecord::FuncRecord(), lldb_private::breakpad::InfoRecord::InfoRecord(), lldb_private::breakpad::InlineOriginRecord::InlineOriginRecord(), lldb_private::breakpad::InlineRecord::InlineRecord(), lldb_private::breakpad::LineRecord::LineRecord(), lldb_private::breakpad::ModuleRecord::ModuleRecord(), lldb_private::breakpad::InlineRecord::parse(), lldb_private::breakpad::PublicRecord::PublicRecord(), lldb_private::breakpad::StackCFIRecord::StackCFIRecord(), and lldb_private::breakpad::StackWinRecord::StackWinRecord().
~Record()
lldb_private::breakpad::Record::~Record () protected default
Member Function Documentation
classify()
std::optional< Record::Kind > Record::classify (llvm::StringRef Line) static
Attempt to guess the kind of the record present in the argument without doing a full parse.
The returned kind will always be correct for valid records, but the full parse can still fail in case of corrupted input.
Definition at line 132 of file BreakpadRecords.cpp.
References consume(), File, Func, Info, Inline, InlineOrigin, Line, Module, Public, StackCFI, and StackWin.
Referenced by lldb_private::breakpad::ObjectFileBreakpad::CreateSections(), lldb_private::breakpad::SymbolFileBreakpad::GetOrCreateFunction(), lldb_private::breakpad::SymbolFileBreakpad::ParseBlocksRecursive(), lldb_private::breakpad::SymbolFileBreakpad::ParseCompileUnitAtIndex(), and lldb_private::breakpad::SymbolFileBreakpad::ParseLineTableAndSupportFiles().
getKind()
Kind lldb_private::breakpad::Record::getKind () inline
Definition at line 48 of file BreakpadRecords.h.
References TheKind.
Member Data Documentation
TheKind
Kind lldb_private::breakpad::Record::TheKind private
Definition at line 51 of file BreakpadRecords.h.
Referenced by getKind(), and Record().
The documentation for this class was generated from the following files:
BreakpadRecords.h
BreakpadRecords.cpp