LLDB: lldb_private::dil::DILLexer Class Reference
lldb_private::dil::DILLexer Class Reference
Class for doing the simple lexing required by DIL.
#include <DILLexer.h>
Public Member Functions
const Token & GetCurrentToken ()
Return the current token to be handled by the DIL parser.
void Advance (uint32_t N=1)
Advance the current token position by N.
const Token & LookAhead (uint32_t N)
Return the lexed token N positions ahead of the 'current' token being handled by the DIL parser.
uint32_t GetCurrentTokenIdx ()
Return the index for the 'current' token being handled by the DIL parser.
void ResetTokenIdx (uint32_t new_value)
Set the index for the 'current' token (to be handled by the parser) to a particular position.
uint32_t NumLexedTokens ()
Static Public Member Functions
static llvm::Expected< DILLexer > Create (llvm::StringRef expr, lldb::DILMode mode=lldb::eDILModeFull)
Lexes all the tokens in expr and calls the private constructor with the lexed tokens.
Private Member Functions
DILLexer (llvm::StringRef dil_expr, std::vector< Token > lexed_tokens)
Static Private Member Functions
static llvm::Expected< Token > Lex (llvm::StringRef expr, llvm::StringRef &remainder)
Private Attributes
llvm::StringRef m_expr
std::vector< Token > m_lexed_tokens
uint32_t m_tokens_idx
Detailed Description
Class for doing the simple lexing required by DIL.
Definition at line 74 of file DILLexer.h.
Constructor & Destructor Documentation
DILLexer()
lldb_private::dil::DILLexer::DILLexer (llvm::StringRef dil_expr, std::vector< Token > lexed_tokens) inline private
Definition at line 117 of file DILLexer.h.
References m_expr, m_lexed_tokens, and m_tokens_idx.
Referenced by Create().
Member Function Documentation
Advance()
void lldb_private::dil::DILLexer::Advance (uint32_t N = 1) inline
Advance the current token position by N.
Definition at line 85 of file DILLexer.h.
References m_lexed_tokens, and m_tokens_idx.
Create()
llvm::Expected< DILLexer > lldb_private::dil::DILLexer::Create (llvm::StringRef expr, lldb::DILMode mode = lldb::eDILModeFull) static
Lexes all the tokens in expr and calls the private constructor with the lexed tokens.
Definition at line 139 of file DILLexer.cpp.
References DILLexer(), lldb_private::dil::Token::eof, error(), lldb_private::dil::IsNotAllowedByMode(), and Lex().
Referenced by lldb_private::StackFrame::DILGetValueForVariableExpressionPath().
GetCurrentToken()
const Token & lldb_private::dil::DILLexer::GetCurrentToken () inline
Return the current token to be handled by the DIL parser.
Definition at line 82 of file DILLexer.h.
References m_lexed_tokens, and m_tokens_idx.
GetCurrentTokenIdx()
uint32_t lldb_private::dil::DILLexer::GetCurrentTokenIdx () inline
Return the index for the 'current' token being handled by the DIL parser.
Definition at line 104 of file DILLexer.h.
References m_tokens_idx.
Lex()
llvm::Expected< Token > lldb_private::dil::DILLexer::Lex (llvm::StringRef expr, llvm::StringRef & remainder) static private
Definition at line 156 of file DILLexer.cpp.
References lldb_private::dil::Token::amp, lldb_private::dil::Token::arrow, lldb_private::dil::Token::colon, lldb_private::dil::Token::coloncolon, lldb_private::dil::Token::eof, lldb_private::dil::Token::float_constant, lldb_private::dil::Token::identifier, lldb_private::dil::Token::integer_constant, lldb_private::dil::IsNumber(), lldb_private::dil::IsWord(), lldb_private::dil::Token::kw_false, lldb_private::dil::Token::kw_true, lldb_private::dil::Token::l_paren, lldb_private::dil::Token::l_square, lldb_private::dil::Token::minus, lldb_private::dil::Token::period, lldb_private::dil::Token::plus, lldb_private::dil::Token::r_paren, lldb_private::dil::Token::r_square, and lldb_private::dil::Token::star.
Referenced by Create().
LookAhead()
const Token & lldb_private::dil::DILLexer::LookAhead (uint32_t N) inline
Return the lexed token N positions ahead of the 'current' token being handled by the DIL parser.
Definition at line 95 of file DILLexer.h.
References m_lexed_tokens, and m_tokens_idx.
NumLexedTokens()
uint32_t lldb_private::dil::DILLexer::NumLexedTokens () inline
Definition at line 114 of file DILLexer.h.
References m_lexed_tokens.
ResetTokenIdx()
void lldb_private::dil::DILLexer::ResetTokenIdx (uint32_t new_value) inline
Set the index for the 'current' token (to be handled by the parser) to a particular position.
Used for either committing 'look ahead' parsing or rolling back tentative parsing.
Definition at line 109 of file DILLexer.h.
References m_lexed_tokens, and m_tokens_idx.
Member Data Documentation
m_expr
llvm::StringRef lldb_private::dil::DILLexer::m_expr private
Definition at line 125 of file DILLexer.h.
Referenced by DILLexer().
m_lexed_tokens
std::vector<Token> lldb_private::dil::DILLexer::m_lexed_tokens private
Definition at line 128 of file DILLexer.h.
Referenced by Advance(), DILLexer(), GetCurrentToken(), LookAhead(), NumLexedTokens(), and ResetTokenIdx().
m_tokens_idx
uint32_t lldb_private::dil::DILLexer::m_tokens_idx private
Definition at line 132 of file DILLexer.h.
Referenced by Advance(), DILLexer(), GetCurrentToken(), GetCurrentTokenIdx(), LookAhead(), and ResetTokenIdx().
The documentation for this class was generated from the following files:
DILLexer.h
DILLexer.cpp