LLDB: lldb_private::plugin::dwarf::DWARFDebugMacroEntry Class Reference
lldb_private::plugin::dwarf::DWARFDebugMacroEntry Class Reference
#include <DWARFDebugMacro.h>
Static Public Member Functions
static void ReadMacroEntries (const DWARFDataExtractor &debug_macro_data, const DWARFDataExtractor &debug_str_data, const bool offset_is_64_bit, lldb::offset_t *sect_offset, SymbolFileDWARF *sym_file_dwarf, DebugMacrosSP &debug_macros_sp)
Detailed Description
Definition at line 50 of file DWARFDebugMacro.h.
Member Function Documentation
ReadMacroEntries()
void DWARFDebugMacroEntry::ReadMacroEntries (const DWARFDataExtractor & debug_macro_data, const DWARFDataExtractor & debug_str_data, const bool offset_is_64_bit, lldb::offset_t * sect_offset, SymbolFileDWARF * sym_file_dwarf, DebugMacrosSP & debug_macros_sp) static
Definition at line 61 of file DWARFDebugMacro.cpp.
References lldb_private::DebugMacroEntry::CreateDefineEntry(), lldb_private::DebugMacroEntry::CreateEndFileEntry(), lldb_private::DebugMacroEntry::CreateIndirectEntry(), lldb_private::DebugMacroEntry::CreateStartFileEntry(), lldb_private::DebugMacroEntry::CreateUndefEntry(), lldb_private::DataExtractor::GetCStr(), lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU64(), lldb_private::DataExtractor::GetU8(), lldb_private::DataExtractor::GetULEB128(), and lldb_private::plugin::dwarf::SymbolFileDWARF::ParseDebugMacros().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::ParseDebugMacros().
The documentation for this class was generated from the following files:
DWARFDebugMacro.h
DWARFDebugMacro.cpp