LLDB: LoadAddressResolver Class Reference
LoadAddressResolver Class Reference
Public Member Functions
LoadAddressResolver (Target &target, bool &symbol_was_missing_weak)
std::optional< lldb::addr_t > Resolve (SymbolContextList &sc_list)
lldb::addr_t GetBestInternalLoadAddress () const
Private Attributes
Target & m_target
bool & m_symbol_was_missing_weak
lldb::addr_t m_best_internal_load_address = LLDB_INVALID_ADDRESS
Detailed Description
Definition at line 649 of file IRExecutionUnit.cpp.
Constructor & Destructor Documentation
LoadAddressResolver()
LoadAddressResolver::LoadAddressResolver (Target & target, bool & symbol_was_missing_weak) inline
Definition at line 651 of file IRExecutionUnit.cpp.
References m_symbol_was_missing_weak, and m_target.
Member Function Documentation
GetBestInternalLoadAddress()
lldb::addr_t LoadAddressResolver::GetBestInternalLoadAddress () const inline
Definition at line 713 of file IRExecutionUnit.cpp.
References m_best_internal_load_address.
Referenced by lldb_private::IRExecutionUnit::FindInSymbols().
Resolve()
std::optional< lldb::addr_t > LoadAddressResolver::Resolve (SymbolContextList & sc_list) inline
Definition at line 654 of file IRExecutionUnit.cpp.
References lldb::eSymbolTypeUndefined, lldb_private::Address::GetCallableLoadAddress(), lldb_private::Address::GetFileAddress(), lldb_private::Address::GetLoadAddress(), lldb_private::SymbolContextList::IsEmpty(), LLDB_INVALID_ADDRESS, m_best_internal_load_address, m_symbol_was_missing_weak, m_target, and lldb_private::SymbolContextList::SymbolContexts().
Referenced by lldb_private::IRExecutionUnit::FindInSymbols(), and ResolveFunctionCallLabel().
Member Data Documentation
m_best_internal_load_address
lldb::addr_t LoadAddressResolver::m_best_internal_load_address = LLDB_INVALID_ADDRESS private
Definition at line 720 of file IRExecutionUnit.cpp.
Referenced by GetBestInternalLoadAddress(), and Resolve().
m_symbol_was_missing_weak
bool& LoadAddressResolver::m_symbol_was_missing_weak private
Definition at line 719 of file IRExecutionUnit.cpp.
Referenced by LoadAddressResolver(), and Resolve().
m_target
Target& LoadAddressResolver::m_target private
Definition at line 718 of file IRExecutionUnit.cpp.
Referenced by LoadAddressResolver(), and Resolve().
The documentation for this class was generated from the following file:
IRExecutionUnit.cpp