LLDB: lldb_private::postfix::BinaryOpNode Class Reference
lldb_private::postfix::BinaryOpNode Class Reference
A node representing a binary expression.
#include <PostfixExpression.h>
Public Types
enum OpType { Align , Minus , Plus }
Public Types inherited from lldb_private::postfix::Node
enum Kind {
BinaryOp , InitialValue , Integer , Register ,
Symbol , UnaryOp
}
Public Member Functions
BinaryOpNode (OpType op_type, Node &left, Node &right)
OpType GetOpType () const
const Node * Left () const
Node *& Left ()
const Node * Right () const
Node *& Right ()
Public Member Functions inherited from lldb_private::postfix::Node
Kind GetKind () const
Static Public Member Functions
static bool classof (const Node *node)
Private Attributes
OpType m_op_type
Node * m_left
Node * m_right
Additional Inherited Members
Protected Member Functions inherited from lldb_private::postfix::Node
Node (Kind kind)
Detailed Description
A node representing a binary expression.
Definition at line 51 of file PostfixExpression.h.
Member Enumeration Documentation
OpType
enum lldb_private::postfix::BinaryOpNode::OpType
Enumerator
Align
Minus
Plus
Definition at line 53 of file PostfixExpression.h.
Constructor & Destructor Documentation
BinaryOpNode()
lldb_private::postfix::BinaryOpNode::BinaryOpNode (OpType op_type, Node & left, Node & right) inline
Definition at line 59 of file PostfixExpression.h.
References lldb_private::postfix::Node::BinaryOp, m_left, m_op_type, m_right, and lldb_private::postfix::Node::Node().
Member Function Documentation
classof()
bool lldb_private::postfix::BinaryOpNode::classof (const Node * node) inline static
Definition at line 70 of file PostfixExpression.h.
References lldb_private::postfix::Node::BinaryOp, lldb_private::postfix::Node::GetKind(), and lldb_private::postfix::Node::Node().
GetOpType()
OpType lldb_private::postfix::BinaryOpNode::GetOpType () const inline
Definition at line 62 of file PostfixExpression.h.
References m_op_type.
Left() [1/2]
Node *& lldb_private::postfix::BinaryOpNode::Left () inline
Definition at line 65 of file PostfixExpression.h.
References m_left, and lldb_private::postfix::Node::Node().
Left() [2/2]
const Node * lldb_private::postfix::BinaryOpNode::Left () const inline
Definition at line 64 of file PostfixExpression.h.
References m_left, and lldb_private::postfix::Node::Node().
Right() [1/2]
Node *& lldb_private::postfix::BinaryOpNode::Right () inline
Definition at line 68 of file PostfixExpression.h.
References m_right, and lldb_private::postfix::Node::Node().
Right() [2/2]
const Node * lldb_private::postfix::BinaryOpNode::Right () const inline
Definition at line 67 of file PostfixExpression.h.
References m_right, and lldb_private::postfix::Node::Node().
Member Data Documentation
m_left
Node* lldb_private::postfix::BinaryOpNode::m_left private
Definition at line 74 of file PostfixExpression.h.
Referenced by BinaryOpNode(), Left(), and Left().
m_op_type
OpType lldb_private::postfix::BinaryOpNode::m_op_type private
Definition at line 73 of file PostfixExpression.h.
Referenced by BinaryOpNode(), and GetOpType().
m_right
Node* lldb_private::postfix::BinaryOpNode::m_right private
Definition at line 75 of file PostfixExpression.h.
Referenced by BinaryOpNode(), Right(), and Right().
The documentation for this class was generated from the following file:
PostfixExpression.h