LLDB: lldb_private::ThreadPlanStepThrough Class Reference
lldb_private::ThreadPlanStepThrough Class Reference
#include <ThreadPlanStepThrough.h>
Public Member Functions
~ThreadPlanStepThrough () override
void GetDescription (Stream *s, lldb::DescriptionLevel level) override
Print a description of this thread to the stream s.
bool ValidatePlan (Stream *error) override
Returns whether this plan could be successfully created.
bool ShouldStop (Event *event_ptr) override
bool StopOthers () override
lldb::StateType GetPlanRunState () override
bool WillStop () override
bool MischiefManaged () override
void DidPush () override
Public Member Functions inherited from lldb_private::ThreadPlan
virtual ~ThreadPlan ()
const char * GetName () const
Returns the name of this thread plan.
Thread & GetThread ()
Returns the Thread that is using this thread plan.
Target & GetTarget ()
const Target & GetTarget () const
void ClearThreadCache ()
Clear the Thread* cache.
bool TracerExplainsStop ()
lldb::StateType RunState ()
bool PlanExplainsStop (Event *event_ptr)
virtual bool ShouldAutoContinue (Event *event_ptr)
Returns whether this thread plan overrides the ShouldStop of subsequently processed plans.
virtual Vote ShouldReportStop (Event *event_ptr)
Vote ShouldReportRun (Event *event_ptr)
virtual void SetStopOthers (bool new_value)
virtual bool SupportsResumeOthers ()
virtual bool ShouldRunBeforePublicStop ()
bool WillResume (lldb::StateType resume_state, bool current_plan)
bool IsControllingPlan ()
virtual bool IsLeafPlan ()
bool SetIsControllingPlan (bool value)
virtual bool OkayToDiscard ()
void SetOkayToDiscard (bool value)
virtual void ThreadDestroyed ()
bool GetPrivate ()
void SetPrivate (bool input)
virtual void DidPop ()
ThreadPlanKind GetKind () const
bool IsPlanComplete ()
void SetPlanComplete (bool success=true)
virtual bool IsPlanStale ()
bool PlanSucceeded ()
virtual bool IsBasePlan ()
lldb::ThreadPlanTracerSP & GetThreadPlanTracer ()
void SetThreadPlanTracer (lldb::ThreadPlanTracerSP new_tracer_sp)
void DoTraceLog ()
virtual lldb::ValueObjectSP GetReturnValueObject ()
virtual lldb::ExpressionVariableSP GetExpressionVariable ()
virtual void RestoreThreadState ()
virtual bool IsVirtualStep ()
bool SetIterationCount (size_t count)
virtual lldb::RunDirection GetDirection () const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Protected Member Functions
bool DoPlanExplainsStop (Event *event_ptr) override
bool DoWillResume (lldb::StateType resume_state, bool current_plan) override
ThreadPlanStepThrough (Thread &thread, StackID &return_stack_id, bool stop_others)
void LookForPlanToStepThroughFromCurrentPC ()
bool HitOurBackstopBreakpoint ()
Protected Member Functions inherited from lldb_private::ThreadPlan
ThreadPlan (ThreadPlanKind kind, const char *name, Thread &thread, Vote report_stop_vote, Vote report_run_vote)
void PushPlan (lldb::ThreadPlanSP &thread_plan_sp)
ThreadPlan * GetPreviousPlan ()
lldb::StopInfoSP GetPrivateStopInfo ()
void SetStopInfo (lldb::StopInfoSP stop_reason_sp)
bool IsUsuallyUnexplainedStopReason (lldb::StopReason)
Private Member Functions
void ClearBackstopBreakpoint ()
ThreadPlanStepThrough (const ThreadPlanStepThrough &)=delete
const ThreadPlanStepThrough & operator= (const ThreadPlanStepThrough &)=delete
Private Attributes
lldb::ThreadPlanSP m_sub_plan_sp
lldb::addr_t m_start_address
lldb::break_id_t m_backstop_bkpt_id
lldb::addr_t m_backstop_addr
StackID m_return_stack_id
bool m_stop_others
Friends
lldb::ThreadPlanSP Thread::QueueThreadPlanForStepThrough (StackID &return_stack_id, bool abort_other_plans, bool stop_others, Status &status)
Additional Inherited Members
Public Types inherited from lldb_private::ThreadPlan
enum ThreadPlanKind {
eKindGeneric , eKindNull , eKindBase , eKindCallFunction ,
eKindPython , eKindStepInstruction , eKindStepOut , eKindStepOverBreakpoint ,
eKindStepOverRange , eKindStepInRange , eKindRunToAddress , eKindStepThrough ,
eKindStepUntil , eKindSingleThreadTimeout
}
Protected Attributes inherited from lldb_private::ThreadPlan
Status m_status
Process & m_process
lldb::tid_t m_tid
Vote m_report_stop_vote
Vote m_report_run_vote
bool m_takes_iteration_count
bool m_could_not_resolve_hw_bp
int32_t m_iteration_count = 1
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Detailed Description
Definition at line 17 of file ThreadPlanStepThrough.h.
Constructor & Destructor Documentation
~ThreadPlanStepThrough()
ThreadPlanStepThrough::~ThreadPlanStepThrough () override
Definition at line 73 of file ThreadPlanStepThrough.cpp.
References ClearBackstopBreakpoint().
ThreadPlanStepThrough() [1/2]
ThreadPlanStepThrough::ThreadPlanStepThrough (Thread & thread, StackID & return_stack_id, bool stop_others) protected
Definition at line 27 of file ThreadPlanStepThrough.cpp.
References lldb_private::ThreadPlan::eKindStepThrough, lldb_private::eVoteNoOpinion, lldb_private::Stoppoint::GetID(), lldb_private::GetLog(), lldb_private::Thread::GetRegisterContext(), lldb_private::ThreadPlan::GetThread(), lldb_private::Breakpoint::HasResolvedLocations(), lldb_private::Breakpoint::IsHardware(), LLDB_INVALID_ADDRESS, LLDB_INVALID_BREAK_ID, LLDB_LOGF, LookForPlanToStepThroughFromCurrentPC(), m_backstop_addr, m_backstop_bkpt_id, lldb_private::ThreadPlan::m_could_not_resolve_hw_bp, lldb_private::ThreadPlan::m_process, m_return_stack_id, m_start_address, m_stop_others, m_sub_plan_sp, lldb_private::ThreadPlan::m_tid, lldb_private::Breakpoint::SetBreakpointKind(), lldb_private::Breakpoint::SetThreadID(), lldb_private::Step, and lldb_private::ThreadPlan::ThreadPlan().
Referenced by operator=(), and ThreadPlanStepThrough().
ThreadPlanStepThrough() [2/2]
lldb_private::ThreadPlanStepThrough::ThreadPlanStepThrough (const ThreadPlanStepThrough &) private delete
References ThreadPlanStepThrough().
Member Function Documentation
ClearBackstopBreakpoint()
void ThreadPlanStepThrough::ClearBackstopBreakpoint () private
Definition at line 222 of file ThreadPlanStepThrough.cpp.
References LLDB_INVALID_BREAK_ID, m_backstop_bkpt_id, lldb_private::ThreadPlan::m_could_not_resolve_hw_bp, and lldb_private::ThreadPlan::m_process.
Referenced by MischiefManaged(), and ~ThreadPlanStepThrough().
DidPush()
void ThreadPlanStepThrough::DidPush () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 75 of file ThreadPlanStepThrough.cpp.
References m_sub_plan_sp, and lldb_private::ThreadPlan::PushPlan().
DoPlanExplainsStop()
bool ThreadPlanStepThrough::DoPlanExplainsStop (Event * event_ptr) override protected virtual
Implements lldb_private::ThreadPlan.
Definition at line 153 of file ThreadPlanStepThrough.cpp.
References HitOurBackstopBreakpoint().
DoWillResume()
bool ThreadPlanStepThrough::DoWillResume (lldb::StateType resume_state, bool current_plan) override protected virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 215 of file ThreadPlanStepThrough.cpp.
GetDescription()
void ThreadPlanStepThrough::GetDescription (Stream * s, lldb::DescriptionLevel level) override virtual
Print a description of this thread to the stream s.
thread. Don't expect that the result of GetThread is valid in the description method. This might get called when the underlying Thread has not been reported, so we only know the TID and not the thread.
Parameters
[in] s The stream to which to print the description.
[in] level The level of description desired. Note that eDescriptionLevelBrief will be used in the stop message printed when the plan is complete.
Implements lldb_private::ThreadPlan.
Definition at line 114 of file ThreadPlanStepThrough.cpp.
References lldb_private::Stream::AsRawOstream(), lldb_private::DumpAddress(), lldb::eDescriptionLevelBrief, LLDB_INVALID_BREAK_ID, m_backstop_addr, m_backstop_bkpt_id, m_start_address, lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
GetPlanRunState()
StateType ThreadPlanStepThrough::GetPlanRunState () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 213 of file ThreadPlanStepThrough.cpp.
References lldb::eStateRunning.
HitOurBackstopBreakpoint()
bool ThreadPlanStepThrough::HitOurBackstopBreakpoint () protected
Definition at line 244 of file ThreadPlanStepThrough.cpp.
References lldb::eStopReasonBreakpoint, lldb_private::GetLog(), lldb_private::ThreadPlan::GetThread(), m_backstop_bkpt_id, lldb_private::ThreadPlan::m_process, m_return_stack_id, lldb_private::Log::PutCString(), and lldb_private::Step.
Referenced by DoPlanExplainsStop(), and ShouldStop().
LookForPlanToStepThroughFromCurrentPC()
void ThreadPlanStepThrough::LookForPlanToStepThroughFromCurrentPC () protected
Definition at line 80 of file ThreadPlanStepThrough.cpp.
References lldb::eDescriptionLevelFull, lldb_private::StreamString::GetData(), lldb_private::GetLog(), lldb_private::Thread::GetRegisterContext(), lldb_private::DynamicLoader::GetStepThroughTrampolinePlan(), lldb_private::ThreadPlan::GetThread(), LLDB_LOGF, lldb_private::ThreadPlan::m_process, m_stop_others, m_sub_plan_sp, and lldb_private::Step.
Referenced by ShouldStop(), and ThreadPlanStepThrough().
MischiefManaged()
bool ThreadPlanStepThrough::MischiefManaged () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 230 of file ThreadPlanStepThrough.cpp.
References ClearBackstopBreakpoint(), lldb_private::GetLog(), lldb_private::ThreadPlan::IsPlanComplete(), LLDB_LOGF, lldb_private::ThreadPlan::MischiefManaged(), and lldb_private::Step.
operator=()
const ThreadPlanStepThrough & lldb_private::ThreadPlanStepThrough::operator= (const ThreadPlanStepThrough &) private delete
References ThreadPlanStepThrough().
ShouldStop()
bool ThreadPlanStepThrough::ShouldStop (Event * event_ptr) override virtual
Implements lldb_private::ThreadPlan.
Definition at line 161 of file ThreadPlanStepThrough.cpp.
References HitOurBackstopBreakpoint(), lldb_private::ThreadPlan::IsPlanComplete(), LLDB_INVALID_BREAK_ID, LookForPlanToStepThroughFromCurrentPC(), m_backstop_bkpt_id, m_sub_plan_sp, lldb_private::ThreadPlan::PushPlan(), and lldb_private::ThreadPlan::SetPlanComplete().
StopOthers()
bool ThreadPlanStepThrough::StopOthers () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 211 of file ThreadPlanStepThrough.cpp.
References m_stop_others.
ValidatePlan()
bool ThreadPlanStepThrough::ValidatePlan (Stream * error) override virtual
Returns whether this plan could be successfully created.
Parameters
[in] error A stream to which to print some reason why the plan could not be created. Can be NULL.
Returns
true if the plan should be queued, false otherwise.
Implements lldb_private::ThreadPlan.
Definition at line 130 of file ThreadPlanStepThrough.cpp.
References error(), LLDB_INVALID_BREAK_ID, m_backstop_bkpt_id, lldb_private::ThreadPlan::m_could_not_resolve_hw_bp, and m_sub_plan_sp.
WillStop()
bool ThreadPlanStepThrough::WillStop () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 220 of file ThreadPlanStepThrough.cpp.
Friends And Related Symbol Documentation
Thread::QueueThreadPlanForStepThrough
lldb::ThreadPlanSP Thread::QueueThreadPlanForStepThrough (StackID & return_stack_id, bool abort_other_plans, bool stop_others, Status & status) friend
Member Data Documentation
m_backstop_addr
lldb::addr_t lldb_private::ThreadPlanStepThrough::m_backstop_addr private
Definition at line 52 of file ThreadPlanStepThrough.h.
Referenced by GetDescription(), and ThreadPlanStepThrough().
m_backstop_bkpt_id
lldb::break_id_t lldb_private::ThreadPlanStepThrough::m_backstop_bkpt_id private
Definition at line 51 of file ThreadPlanStepThrough.h.
Referenced by ClearBackstopBreakpoint(), GetDescription(), HitOurBackstopBreakpoint(), ShouldStop(), ThreadPlanStepThrough(), and ValidatePlan().
m_return_stack_id
StackID lldb_private::ThreadPlanStepThrough::m_return_stack_id private
Definition at line 53 of file ThreadPlanStepThrough.h.
Referenced by HitOurBackstopBreakpoint(), and ThreadPlanStepThrough().
m_start_address
lldb::addr_t lldb_private::ThreadPlanStepThrough::m_start_address private
Definition at line 50 of file ThreadPlanStepThrough.h.
Referenced by GetDescription(), and ThreadPlanStepThrough().
m_stop_others
bool lldb_private::ThreadPlanStepThrough::m_stop_others private
Definition at line 54 of file ThreadPlanStepThrough.h.
Referenced by LookForPlanToStepThroughFromCurrentPC(), StopOthers(), and ThreadPlanStepThrough().
m_sub_plan_sp
lldb::ThreadPlanSP lldb_private::ThreadPlanStepThrough::m_sub_plan_sp private
Definition at line 49 of file ThreadPlanStepThrough.h.
Referenced by DidPush(), LookForPlanToStepThroughFromCurrentPC(), ShouldStop(), ThreadPlanStepThrough(), and ValidatePlan().
The documentation for this class was generated from the following files:
ThreadPlanStepThrough.h
ThreadPlanStepThrough.cpp