LLDB: lldb_private::ScriptInterpreterPythonInterfaces Class Reference
lldb_private::ScriptInterpreterPythonInterfaces Class Reference
#include <ScriptInterpreterPythonInterfaces.h>
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
Additional Inherited Members
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
virtual llvm::StringRef GetPluginName ()=0
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Detailed Description
Definition at line 25 of file ScriptInterpreterPythonInterfaces.h.
Member Function Documentation
GetPluginDescriptionStatic()
llvm::StringRef ScriptInterpreterPythonInterfaces::GetPluginDescriptionStatic () static
Definition at line 18 of file ScriptInterpreterPythonInterfaces.cpp.
GetPluginNameStatic()
llvm::StringRef lldb_private::ScriptInterpreterPythonInterfaces::GetPluginNameStatic () inline static
Definition at line 29 of file ScriptInterpreterPythonInterfaces.h.
Initialize()
void ScriptInterpreterPythonInterfaces::Initialize () static
Definition at line 22 of file ScriptInterpreterPythonInterfaces.cpp.
References lldb_private::OperatingSystemPythonInterface::Initialize(), lldb_private::ScriptedBreakpointPythonInterface::Initialize(), lldb_private::ScriptedFrameProviderPythonInterface::Initialize(), lldb_private::ScriptedPlatformPythonInterface::Initialize(), lldb_private::ScriptedProcessPythonInterface::Initialize(), lldb_private::ScriptedStopHookPythonInterface::Initialize(), and lldb_private::ScriptedThreadPlanPythonInterface::Initialize().
Referenced by lldb_private::ScriptInterpreterPython::Initialize().
Terminate()
void ScriptInterpreterPythonInterfaces::Terminate () static
Definition at line 32 of file ScriptInterpreterPythonInterfaces.cpp.
References lldb_private::OperatingSystemPythonInterface::Terminate(), lldb_private::ScriptedBreakpointPythonInterface::Terminate(), lldb_private::ScriptedFrameProviderPythonInterface::Terminate(), lldb_private::ScriptedPlatformPythonInterface::Terminate(), lldb_private::ScriptedProcessPythonInterface::Terminate(), lldb_private::ScriptedStopHookPythonInterface::Terminate(), and lldb_private::ScriptedThreadPlanPythonInterface::Terminate().
Referenced by lldb_private::ScriptInterpreterPython::Terminate().
The documentation for this class was generated from the following files:
ScriptInterpreterPythonInterfaces.h
ScriptInterpreterPythonInterfaces.cpp