LLDB: lldb_private::Socket Class Reference
lldb_private::Socket Class Reference abstract
#include <Socket.h>
Classes
struct HostAndPort
Public Types
enum SocketProtocol { ProtocolTcp , ProtocolUdp , ProtocolUnixDomain , ProtocolUnixAbstract }
enum SocketMode { ModeAccept , ModeConnect }
using ProtocolModePair = std::pair<SocketProtocol, SocketMode>
using Pair = std::pair<std::unique_ptr<Socket>, std::unique_ptr<Socket>>
Public Types inherited from lldb_private::IOObject
enum FDType { eFDTypeFile , eFDTypeSocket }
using WaitableHandle = lldb::file_t
Public Member Functions
~Socket () override
virtual Status Connect (llvm::StringRef name)=0
virtual Status Listen (llvm::StringRef name, int backlog)=0
virtual llvm::Expected< std::vector< MainLoopBase::ReadHandleUP > > Accept (MainLoopBase &loop, std::function< void(std::unique_ptr< Socket > socket)> sock_cb)=0
virtual Status Accept (const Timeout< std::micro > &timeout, Socket *&socket)
int GetOption (int level, int option_name, int &option_value)
int SetOption (int level, int option_name, int option_value)
NativeSocket GetNativeSocket () const
SocketProtocol GetSocketProtocol () const
Status Read (void *buf, size_t &num_bytes) override
Status Write (const void *buf, size_t &num_bytes) override
Status Close () override
bool IsValid () const override
WaitableHandle GetWaitableHandle () override
virtual std::string GetRemoteConnectionURI () const
virtual std::vector< std::string > GetListeningConnectionURI () const
Public Member Functions inherited from lldb_private::IOObject
IOObject (FDType type)
virtual ~IOObject ()
FDType GetFdType () const
Static Public Member Functions
static std::optional< ProtocolModePair > GetProtocolAndMode (llvm::StringRef scheme)
static const char * FindSchemeByProtocol (const SocketProtocol protocol)
static bool FindProtocolByScheme (const char *scheme, SocketProtocol &protocol)
static llvm::Error Initialize ()
static void Terminate ()
static std::unique_ptr< Socket > Create (const SocketProtocol protocol, Status &error)
static llvm::Expected< Pair > CreatePair (std::optional< SocketProtocol > protocol=std::nullopt)
static llvm::Expected< std::unique_ptr< TCPSocket > > TcpListen (llvm::StringRef host_and_port, int backlog=5)
static llvm::Expected< std::unique_ptr< Socket > > TcpConnect (llvm::StringRef host_and_port)
static llvm::Expected< std::unique_ptr< UDPSocket > > UdpConnect (llvm::StringRef host_and_port)
static int GetOption (NativeSocket sockfd, int level, int option_name, int &option_value)
static int SetOption (NativeSocket sockfd, int level, int option_name, int option_value)
static llvm::Expected< HostAndPort > DecodeHostAndPort (llvm::StringRef host_and_port)
Static Public Attributes
static const NativeSocket kInvalidSocketValue = -1
Static Public Attributes inherited from lldb_private::IOObject
static const WaitableHandle kInvalidHandleValue = -1
Protected Member Functions
Socket (SocketProtocol protocol, bool should_close)
virtual size_t Send (const void *buf, const size_t num_bytes)
Static Protected Member Functions
static int CloseSocket (NativeSocket sockfd)
static Status GetLastError ()
static void SetLastError (Status &error)
static NativeSocket CreateSocket (const int domain, const int type, const int protocol, Status &error)
static NativeSocket AcceptSocket (NativeSocket sockfd, struct sockaddr *addr, socklen_t *addrlen, Status &error)
Protected Attributes
SocketProtocol m_protocol
NativeSocket m_socket
bool m_should_close_fd
Protected Attributes inherited from lldb_private::IOObject
FDType m_fd_type
Detailed Description
Definition at line 68 of file Socket.h.
Member Typedef Documentation
Pair
using lldb_private::Socket::Pair = std::pair<std::unique_ptr<Socket>, std::unique_ptr<Socket>>
Definition at line 109 of file Socket.h.
ProtocolModePair
using lldb_private::Socket::ProtocolModePair = std::pair<SocketProtocol, SocketMode>
Definition at line 91 of file Socket.h.
Member Enumeration Documentation
SocketMode
enum lldb_private::Socket::SocketMode
Enumerator
ModeAccept
ModeConnect
Definition at line 77 of file Socket.h.
SocketProtocol
enum lldb_private::Socket::SocketProtocol
Enumerator
ProtocolTcp
ProtocolUdp
ProtocolUnixDomain
ProtocolUnixAbstract
Definition at line 70 of file Socket.h.
Constructor & Destructor Documentation
~Socket()
Socket::~Socket () override
Definition at line 174 of file Socket.cpp.
References Close().
Socket()
Socket::Socket (SocketProtocol protocol, bool should_close) protected
Definition at line 170 of file Socket.cpp.
References lldb_private::IOObject::eFDTypeSocket, lldb_private::IOObject::IOObject(), kInvalidSocketValue, m_protocol, m_should_close_fd, and m_socket.
Referenced by Accept(), Accept(), lldb_private::TCPSocket::CreatePair(), lldb_private::DomainSocket::DomainSocket(), lldb_private::DomainSocket::DomainSocket(), lldb_private::DomainSocket::DomainSocket(), lldb_private::DomainSocket::DomainSocket(), lldb_private::TCPSocket::TCPSocket(), lldb_private::TCPSocket::TCPSocket(), lldb_private::TCPSocket::TCPSocket(), lldb_private::UDPSocket::UDPSocket(), and lldb_private::UDPSocket::UDPSocket().
Member Function Documentation
Accept() [1/2]
Status Socket::Accept (const Timeout< std::micro > & timeout, Socket *& socket) virtual
Reimplemented in lldb_private::DomainSocket, and lldb_private::TCPSocket.
Definition at line 454 of file Socket.cpp.
References Accept(), lldb_private::MainLoopBase::AddCallback(), lldb_private::Status::Fail(), lldb_private::Status::FromError(), lldb_private::MainLoopBase::RequestTermination(), lldb_private::MainLoopPosix::Run(), Socket(), and lldb_private::Status.
Accept() [2/2]
virtual llvm::Expected< std::vector< MainLoopBase::ReadHandleUP > > lldb_private::Socket::Accept (MainLoopBase & loop, std::function< void(std::unique_ptr< Socket > socket)> sock_cb) pure virtual
Implemented in lldb_private::DomainSocket, lldb_private::TCPSocket, and lldb_private::UDPSocket.
References Socket().
Referenced by Accept().
AcceptSocket()
NativeSocket Socket::AcceptSocket (NativeSocket sockfd, struct sockaddr * addr, socklen_t * addrlen, Status & error) static protected
Definition at line 476 of file Socket.cpp.
References error(), kInvalidSocketValue, and SetLastError().
Referenced by lldb_private::DomainSocket::Accept(), and lldb_private::TCPSocket::Accept().
Close()
Status Socket::Close () override virtual
Implements lldb_private::IOObject.
Definition at line 374 of file Socket.cpp.
References CloseSocket(), lldb_private::Connection, error(), lldb_private::GetLog(), IsValid(), kInvalidSocketValue, LLDB_LOGF, m_should_close_fd, m_socket, and SetLastError().
Referenced by lldb_private::TCPSocket::Connect(), lldb_private::TCPSocket::CreateSocket(), and ~Socket().
CloseSocket()
int Socket::CloseSocket (NativeSocket sockfd) static protected
Definition at line 432 of file Socket.cpp.
Referenced by lldb_private::TCPSocket::Accept(), Close(), lldb_private::TCPSocket::CloseListenSockets(), and lldb_private::TCPSocket::Listen().
Connect()
virtual Status lldb_private::Socket::Connect (llvm::StringRef name) pure virtual
Implemented in lldb_private::DomainSocket, lldb_private::TCPSocket, and lldb_private::UDPSocket.
Create()
std::unique_ptr< Socket > Socket::Create (const SocketProtocol protocol, Status & error) static
Definition at line 200 of file Socket.cpp.
References error(), lldb_private::Status::FromErrorString(), ProtocolTcp, ProtocolUdp, ProtocolUnixAbstract, and ProtocolUnixDomain.
Referenced by lldb_private::ConnectionFileDescriptor::AcceptSocket(), lldb_private::ConnectionFileDescriptor::ConnectSocket(), lldb_private::mcp::ProtocolServerMCP::Start(), and TcpConnect().
CreatePair()
llvm::Expected< Socket::Pair > Socket::CreatePair (std::optional< SocketProtocol > protocol = std::nullopt) static
Definition at line 238 of file Socket.cpp.
References lldb_private::DomainSocket::CreatePair(), lldb_private::TCPSocket::CreatePair(), ProtocolTcp, ProtocolUnixAbstract, and ProtocolUnixDomain.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::LaunchAndConnectToDebugserver().
CreateSocket()
NativeSocket Socket::CreateSocket (const int domain, const int type, const int protocol, Status & error) static protected
Definition at line 440 of file Socket.cpp.
References error(), kInvalidSocketValue, and SetLastError().
Referenced by lldb_private::DomainSocket::Connect(), lldb_private::UDPSocket::CreateConnected(), lldb_private::TCPSocket::CreateSocket(), lldb_private::DomainSocket::Listen(), and lldb_private::TCPSocket::Listen().
DecodeHostAndPort()
llvm::Expected< Socket::HostAndPort > Socket::DecodeHostAndPort (llvm::StringRef host_and_port) static
Definition at line 292 of file Socket.cpp.
References lldb_private::Socket::HostAndPort::hostname, and lldb_private::Socket::HostAndPort::port.
Referenced by lldb_private::TCPSocket::Connect(), lldb_private::UDPSocket::CreateConnected(), lldb_private::TCPSocket::Listen(), and lldb_private::process_gdb_remote::LLGSArgToURL().
FindProtocolByScheme()
bool Socket::FindProtocolByScheme (const char * scheme, Socket::SocketProtocol & protocol) static
Definition at line 159 of file Socket.cpp.
References socket_schemes.
FindSchemeByProtocol()
const char * Socket::FindSchemeByProtocol (const SocketProtocol protocol) static
Definition at line 151 of file Socket.cpp.
References socket_schemes.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::LaunchGDBServer().
GetLastError()
Status Socket::GetLastError () static protected
Definition at line 422 of file Socket.cpp.
Referenced by lldb_private::TCPSocket::Listen().
GetListeningConnectionURI()
virtual std::vector< std::string > lldb_private::Socket::GetListeningConnectionURI () const inline virtual
Reimplemented in lldb_private::DomainSocket, and lldb_private::TCPSocket.
Definition at line 169 of file Socket.h.
Referenced by CommandObjectProtocolServerGet::DoExecute().
GetNativeSocket()
NativeSocket lldb_private::Socket::GetNativeSocket () const inline
Definition at line 151 of file Socket.h.
References m_socket.
Referenced by lldb_private::DomainSocket::Accept(), lldb_private::DomainSocket::Connect(), lldb_private::TCPSocket::Connect(), lldb_private::DomainSocket::Listen(), and lldb_private::SharedSocket::SharedSocket().
GetOption() [1/2]
int lldb_private::Socket::GetOption (int level, int option_name, int & option_value) inline
Definition at line 141 of file Socket.h.
References GetOption(), and m_socket.
GetOption() [2/2]
int Socket::GetOption (NativeSocket sockfd, int level, int option_name, int & option_value) static
Definition at line 393 of file Socket.cpp.
Referenced by GetOption().
GetProtocolAndMode()
std::optional< Socket::ProtocolModePair > Socket::GetProtocolAndMode (llvm::StringRef scheme) static
Definition at line 498 of file Socket.cpp.
References ModeAccept, ModeConnect, ProtocolTcp, ProtocolUnixAbstract, and ProtocolUnixDomain.
Referenced by CommandObjectProtocolServerStart::DoExecute().
GetRemoteConnectionURI()
virtual std::string lldb_private::Socket::GetRemoteConnectionURI () const inline virtual
Reimplemented in lldb_private::DomainSocket, lldb_private::TCPSocket, and lldb_private::UDPSocket.
Definition at line 166 of file Socket.h.
GetSocketProtocol()
SocketProtocol lldb_private::Socket::GetSocketProtocol () const inline
Definition at line 152 of file Socket.h.
References m_protocol.
GetWaitableHandle()
IOObject::WaitableHandle Socket::GetWaitableHandle () override virtual
Implements lldb_private::IOObject.
Definition at line 315 of file Socket.cpp.
References m_socket.
Initialize()
llvm::Error Socket::Initialize () static
Definition at line 176 of file Socket.cpp.
Referenced by lldb_private::SystemInitializerCommon::Initialize().
IsValid()
bool lldb_private::Socket::IsValid () const inline override virtual
Implements lldb_private::IOObject.
Reimplemented in lldb_private::TCPSocket.
Definition at line 159 of file Socket.h.
References kInvalidSocketValue, and m_socket.
Referenced by Close().
Listen()
virtual Status lldb_private::Socket::Listen (llvm::StringRef name, int backlog) pure virtual
Implemented in lldb_private::DomainSocket, lldb_private::TCPSocket, and lldb_private::UDPSocket.
Read()
Status Socket::Read (void * buf, size_t & num_bytes) override virtual
Implements lldb_private::IOObject.
Definition at line 319 of file Socket.cpp.
References lldb_private::Communication, error(), lldb_private::GetLog(), IsInterrupted(), LLDB_LOGF, m_socket, and SetLastError().
Send()
size_t Socket::Send (const void * buf, const size_t num_bytes) protected virtual
Reimplemented in lldb_private::UDPSocket.
Definition at line 410 of file Socket.cpp.
References m_socket.
Referenced by Write().
SetLastError()
void Socket::SetLastError (Status & error) static protected
Definition at line 414 of file Socket.cpp.
References lldb::eErrorTypeWin32, error(), lldb_private::Status::FromErrno(), and lldb_private::Status.
Referenced by AcceptSocket(), Close(), lldb_private::DomainSocket::Connect(), CreateSocket(), lldb_private::DomainSocket::Listen(), Read(), and Write().
SetOption() [1/2]
int lldb_private::Socket::SetOption (int level, int option_name, int option_value) inline
Definition at line 147 of file Socket.h.
References m_socket, and SetOption().
SetOption() [2/2]
int Socket::SetOption (NativeSocket sockfd, int level, int option_name, int option_value) static
Definition at line 402 of file Socket.cpp.
Referenced by lldb_private::TCPSocket::Listen(), SetOption(), lldb_private::TCPSocket::SetOptionNoDelay(), and lldb_private::TCPSocket::SetOptionReuseAddress().
TcpConnect()
llvm::Expected< std::unique_ptr< Socket > > Socket::TcpConnect (llvm::StringRef host_and_port) static
Definition at line 255 of file Socket.cpp.
References lldb_private::Connection, Create(), error(), lldb_private::GetLog(), LLDB_LOG, and ProtocolTcp.
TcpListen()
llvm::Expected< std::unique_ptr< TCPSocket > > Socket::TcpListen (llvm::StringRef host_and_port, int backlog = 5) static
Definition at line 272 of file Socket.cpp.
References lldb_private::Connection, error(), lldb_private::GetLog(), and LLDB_LOG.
Terminate()
void Socket::Terminate () static
Definition at line 194 of file Socket.cpp.
Referenced by lldb_private::SystemInitializerCommon::Terminate().
UdpConnect()
llvm::Expected< std::unique_ptr< UDPSocket > > Socket::UdpConnect (llvm::StringRef host_and_port) static
Definition at line 287 of file Socket.cpp.
References lldb_private::UDPSocket::CreateConnected().
Referenced by lldb_private::ConnectionFileDescriptor::ConnectUDP().
Write()
Status Socket::Write (const void * buf, size_t & num_bytes) override virtual
Implements lldb_private::IOObject.
Definition at line 346 of file Socket.cpp.
References lldb_private::Communication, error(), lldb_private::GetLog(), IsInterrupted(), LLDB_LOGF, m_socket, Send(), and SetLastError().
Member Data Documentation
kInvalidSocketValue
const NativeSocket Socket::kInvalidSocketValue = -1 static
Definition at line 95 of file Socket.h.
Referenced by AcceptSocket(), Close(), CreateSocket(), lldb_private::DomainSocket::DomainSocket(), lldb_private::DomainSocket::GetListeningConnectionURI(), lldb_private::TCPSocket::GetLocalIPAddress(), lldb_private::TCPSocket::GetLocalPortNumber(), lldb_private::SharedSocket::GetNativeSocket(), lldb_private::TCPSocket::GetRemoteConnectionURI(), lldb_private::UDPSocket::GetRemoteConnectionURI(), lldb_private::TCPSocket::GetRemoteIPAddress(), lldb_private::TCPSocket::GetRemotePortNumber(), lldb_private::DomainSocket::GetSocketName(), IsValid(), lldb_private::TCPSocket::IsValid(), and Socket().
m_protocol
SocketProtocol lldb_private::Socket::m_protocol protected
Definition at line 186 of file Socket.h.
Referenced by GetSocketProtocol(), and Socket().
m_should_close_fd
bool lldb_private::Socket::m_should_close_fd protected
Definition at line 188 of file Socket.h.
Referenced by Close(), lldb_private::DomainSocket::DomainSocket(), Socket(), and lldb_private::TCPSocket::TCPSocket().
m_socket
NativeSocket lldb_private::Socket::m_socket protected
Definition at line 187 of file Socket.h.
Referenced by Close(), lldb_private::DomainSocket::Connect(), lldb_private::TCPSocket::CreateSocket(), lldb_private::DomainSocket::DomainSocket(), lldb_private::DomainSocket::DomainSocket(), lldb_private::DomainSocket::DomainSocket(), lldb_private::DomainSocket::GetListeningConnectionURI(), lldb_private::TCPSocket::GetLocalIPAddress(), lldb_private::TCPSocket::GetLocalPortNumber(), GetNativeSocket(), GetOption(), lldb_private::TCPSocket::GetRemoteConnectionURI(), lldb_private::UDPSocket::GetRemoteConnectionURI(), lldb_private::TCPSocket::GetRemoteIPAddress(), lldb_private::TCPSocket::GetRemotePortNumber(), lldb_private::DomainSocket::GetSocketName(), GetWaitableHandle(), IsValid(), lldb_private::TCPSocket::IsValid(), lldb_private::DomainSocket::Listen(), Read(), Send(), lldb_private::UDPSocket::Send(), SetOption(), Socket(), lldb_private::TCPSocket::TCPSocket(), lldb_private::TCPSocket::TCPSocket(), lldb_private::UDPSocket::UDPSocket(), and Write().
The documentation for this class was generated from the following files:
Socket.h
Socket.cpp