LLDB: lldb_private::Thread::ThreadEventData Class Reference
lldb_private::Thread::ThreadEventData Class Reference
#include <Thread.h>
Public Member Functions
ThreadEventData (const lldb::ThreadSP thread_sp)
ThreadEventData (const lldb::ThreadSP thread_sp, const StackID &stack_id)
ThreadEventData ()
~ThreadEventData () override
llvm::StringRef GetFlavor () const override
void Dump (Stream *s) const override
lldb::ThreadSP GetThread () const
StackID GetStackID () const
Public Member Functions inherited from lldb_private::EventData
EventData ()
virtual ~EventData ()
virtual Log * GetLogChannel ()
Static Public Member Functions
static llvm::StringRef GetFlavorString ()
static const ThreadEventData * GetEventDataFromEvent (const Event *event_ptr)
static lldb::ThreadSP GetThreadFromEvent (const Event *event_ptr)
static StackID GetStackIDFromEvent (const Event *event_ptr)
static lldb::StackFrameSP GetStackFrameFromEvent (const Event *event_ptr)
Private Member Functions
ThreadEventData (const ThreadEventData &)=delete
const ThreadEventData & operator= (const ThreadEventData &)=delete
Private Attributes
lldb::ThreadSP m_thread_sp
StackID m_stack_id
Detailed Description
Definition at line 88 of file Thread.h.
Constructor & Destructor Documentation
ThreadEventData() [1/4]
Thread::ThreadEventData::ThreadEventData (const lldb::ThreadSP thread_sp)
Definition at line 164 of file Thread.cpp.
References m_stack_id, and m_thread_sp.
Referenced by GetEventDataFromEvent(), GetStackFrameFromEvent(), GetStackIDFromEvent(), GetThreadFromEvent(), operator=(), and ThreadEventData().
ThreadEventData() [2/4]
Thread::ThreadEventData::ThreadEventData (const lldb::ThreadSP thread_sp, const StackID & stack_id)
Definition at line 167 of file Thread.cpp.
References m_stack_id, and m_thread_sp.
ThreadEventData() [3/4]
Thread::ThreadEventData::ThreadEventData ()
Definition at line 171 of file Thread.cpp.
References m_stack_id, and m_thread_sp.
~ThreadEventData()
Thread::ThreadEventData::~ThreadEventData () override default
ThreadEventData() [4/4]
lldb_private::Thread::ThreadEventData::ThreadEventData (const ThreadEventData &) private delete
References ThreadEventData().
Member Function Documentation
Dump()
void Thread::ThreadEventData::Dump (Stream * s) const override virtual
Reimplemented from lldb_private::EventData.
Definition at line 175 of file Thread.cpp.
GetEventDataFromEvent()
const Thread::ThreadEventData * Thread::ThreadEventData::GetEventDataFromEvent (const Event * event_ptr) static
Definition at line 178 of file Thread.cpp.
References lldb_private::EventData::Event, lldb_private::EventData::EventData(), lldb_private::Event::GetData(), lldb_private::EventData::GetFlavor(), GetFlavorString(), and ThreadEventData().
Referenced by lldb::SBThread::EventIsThreadEvent(), GetStackFrameFromEvent(), GetStackIDFromEvent(), and GetThreadFromEvent().
GetFlavor()
llvm::StringRef lldb_private::Thread::ThreadEventData::GetFlavor () const inline override virtual
Implements lldb_private::EventData.
Definition at line 100 of file Thread.h.
References GetFlavorString().
GetFlavorString()
llvm::StringRef Thread::ThreadEventData::GetFlavorString () static
Definition at line 160 of file Thread.cpp.
Referenced by GetEventDataFromEvent(), and GetFlavor().
GetStackFrameFromEvent()
StackFrameSP Thread::ThreadEventData::GetStackFrameFromEvent (const Event * event_ptr) static
Definition at line 205 of file Thread.cpp.
References lldb_private::EventData::Event, GetEventDataFromEvent(), GetStackID(), GetThread(), and ThreadEventData().
Referenced by lldb::SBThread::GetStackFrameFromEvent().
GetStackID()
StackID lldb_private::Thread::ThreadEventData::GetStackID () const inline
Definition at line 116 of file Thread.h.
References m_stack_id.
Referenced by GetStackFrameFromEvent(), and GetStackIDFromEvent().
GetStackIDFromEvent()
StackID Thread::ThreadEventData::GetStackIDFromEvent (const Event * event_ptr) static
Definition at line 196 of file Thread.cpp.
References lldb_private::EventData::Event, GetEventDataFromEvent(), GetStackID(), and ThreadEventData().
GetThread()
lldb::ThreadSP lldb_private::Thread::ThreadEventData::GetThread () const inline
Definition at line 114 of file Thread.h.
References m_thread_sp.
Referenced by GetStackFrameFromEvent(), and GetThreadFromEvent().
GetThreadFromEvent()
ThreadSP Thread::ThreadEventData::GetThreadFromEvent (const Event * event_ptr) static
Definition at line 188 of file Thread.cpp.
References lldb_private::EventData::Event, GetEventDataFromEvent(), GetThread(), and ThreadEventData().
Referenced by lldb::SBThread::GetThreadFromEvent(), and lldb_private::Debugger::HandleThreadEvent().
operator=()
const ThreadEventData & lldb_private::Thread::ThreadEventData::operator= (const ThreadEventData &) private delete
References ThreadEventData().
Member Data Documentation
m_stack_id
StackID lldb_private::Thread::ThreadEventData::m_stack_id private
Definition at line 120 of file Thread.h.
Referenced by GetStackID(), ThreadEventData(), ThreadEventData(), and ThreadEventData().
m_thread_sp
lldb::ThreadSP lldb_private::Thread::ThreadEventData::m_thread_sp private
Definition at line 119 of file Thread.h.
Referenced by GetThread(), ThreadEventData(), ThreadEventData(), and ThreadEventData().
The documentation for this class was generated from the following files:
Thread.h
Thread.cpp