LLDB: lldb::SBError Class Reference
lldb::SBError Class Reference
#include <SBError.h>
Public Member Functions
SBError ()
SBError (const lldb::SBError &rhs)
SBError (const char *message)
~SBError ()
const SBError & operator= (const lldb::SBError &rhs)
const char * GetCString () const
Get the error string as a NULL terminated UTF8 c-string.
void Clear ()
bool Fail () const
bool Success () const
uint32_t GetError () const
Get the error code.
SBStructuredData GetErrorData () const
Get the error in machine-readable form.
lldb::ErrorType GetType () const
void SetError (uint32_t err, lldb::ErrorType type)
void SetErrorToErrno ()
void SetErrorToGenericError ()
void SetErrorString (const char *err_str)
__attribute__ ((format(printf, 2, 3))) int SetErrorStringWithFormat(const char *format
operator bool () const
bool IsValid () const
Returns true if this object contains an underlying Status object.
bool GetDescription (lldb::SBStream &description)
Protected Member Functions
SBError (lldb_private::Status &&error)
lldb_private::Status * get ()
lldb_private::Status * operator-> ()
const lldb_private::Status & operator* () const
lldb_private::Status & ref ()
void SetError (lldb_private::Status &&lldb_error)
Private Member Functions
void CreateIfNeeded ()
Private Attributes
std::unique_ptr< lldb_private::Status > m_opaque_up
Friends
class SBBreakpoint
class SBBreakpointLocation
class SBBreakpointName
class SBCommandReturnObject
class SBCommunication
class SBSaveCoreOptions
class SBData
class SBDebugger
class SBFile
class SBFormat
class SBFrame
class SBHostOS
class SBPlatform
class SBProcess
class SBReproducer
class SBStructuredData
class SBTarget
class SBThread
class SBTrace
class SBValue
class SBValueList
class SBWatchpoint
class lldb_private::ScriptInterpreter
class lldb_private::python::SWIGBridge
Detailed Description
Definition at line 23 of file SBError.h.
Constructor & Destructor Documentation
SBError() [1/4]
SBError::SBError ()
Definition at line 23 of file SBError.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb_private::python::SWIGBridge, operator=(), SBError(), and ~SBError().
SBError() [2/4]
SBError::SBError (const lldb::SBError & rhs)
Definition at line 25 of file SBError.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and SBError().
SBError() [3/4]
SBError::SBError (const char * message)
Definition at line 32 of file SBError.cpp.
References LLDB_INSTRUMENT_VA, and SetErrorString().
~SBError()
SBError::~SBError () default
References Clear(), Fail(), GetCString(), GetError(), GetErrorData(), GetType(), operator=(), SBError(), SBStructuredData, SetError(), SetErrorString(), SetErrorToErrno(), SetErrorToGenericError(), and Success().
SBError() [4/4]
SBError::SBError (lldb_private::Status && error) protected
Definition at line 38 of file SBError.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Member Function Documentation
__attribute__()
lldb::SBError::__attribute__ ((format(printf, 2, 3))) const
References GetDescription(), and IsValid().
Clear()
void SBError::Clear ()
Definition at line 63 of file SBError.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBDebugger::CreateTarget(), and ~SBError().
CreateIfNeeded()
void SBError::CreateIfNeeded () private
Definition at line 182 of file SBError.cpp.
References m_opaque_up.
Referenced by ref(), SetError(), SetError(), SetErrorString(), SetErrorToErrno(), and SetErrorToGenericError().
Fail()
bool SBError::Fail () const
Definition at line 70 of file SBError.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBTarget::BreakpointsCreateFromFile(), lldb::SBBreakpointName::SetScriptCallbackBody(), and ~SBError().
get()
lldb_private::Status * SBError::get () protected
Definition at line 189 of file SBError.cpp.
References m_opaque_up.
Referenced by lldb_private::python::SWIGBridge.
GetCString()
const char * SBError::GetCString () const
Get the error string as a NULL terminated UTF8 c-string.
This SBError object owns the returned string and this object must be kept around long enough to use the returned string.
Definition at line 55 of file SBError.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBDebugger::CreateTarget(), GetDescription(), and ~SBError().
GetDescription()
bool SBError::GetDescription (lldb::SBStream & description)
Definition at line 201 of file SBError.cpp.
References GetCString(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by __attribute__().
GetError()
uint32_t SBError::GetError () const
Get the error code.
Definition at line 91 of file SBError.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBError().
GetErrorData()
SBStructuredData SBError::GetErrorData () const
Get the error in machine-readable form.
Particularly useful for compiler diagnostics.
Definition at line 102 of file SBError.cpp.
References LLDB_INSTRUMENT_VA, lldb::SBStructuredData::m_impl_up, m_opaque_up, and SBStructuredData.
Referenced by ~SBError().
GetType()
ErrorType SBError::GetType () const
Definition at line 114 of file SBError.cpp.
References lldb::eErrorTypeInvalid, LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBError().
IsValid()
bool SBError::IsValid () const
Returns true if this object contains an underlying Status object.
That object may represent a success or a failure. When IsValid returns false, it may be the case that the SBError represents a success but does not contain a Status representing that success.
It is safe to call Success or Fail in the case where IsValid returns false.
Definition at line 172 of file SBError.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by __attribute__().
operator bool()
SBError::operator bool () const explicit
Definition at line 176 of file SBError.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
operator*()
const lldb_private::Status & SBError::operator* () const protected
Definition at line 196 of file SBError.cpp.
References m_opaque_up.
Referenced by lldb_private::python::SWIGBridge.
operator->()
lldb_private::Status * SBError::operator-> () protected
Definition at line 187 of file SBError.cpp.
References m_opaque_up.
Referenced by lldb_private::python::SWIGBridge.
operator=()
const SBError & SBError::operator= (const lldb::SBError & rhs)
Definition at line 45 of file SBError.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and SBError().
Referenced by ~SBError().
ref()
lldb_private::Status & SBError::ref () protected
Definition at line 191 of file SBError.cpp.
References CreateIfNeeded(), and m_opaque_up.
Referenced by lldb::SBProcess::AllocateMemory(), lldb::SBTarget::BreakpointsCreateFromFile(), lldb::SBTarget::BreakpointsWriteToFile(), lldb::SBPlatform::ConnectRemote(), lldb::SBProcess::Continue(), lldb::SBDebugger::CreateTarget(), lldb::SBPlatform::ExecuteConnected(), lldb::SBPlatform::Get(), lldb::SBProcess::GetMemoryRegionInfo(), lldb::SBTarget::Install(), lldb_private::python::SWIGBridge, lldb::SBProcess::LoadImage(), lldb::SBPlatform::MakeDirectory(), lldb::SBProcess::ReadCStringFromMemory(), lldb::SBProcess::ReadMemory(), lldb::SBProcess::ReadPointerFromMemory(), lldb::SBProcess::ReadUnsignedFromMemory(), lldb::SBDebugger::SetCurrentPlatform(), lldb::SBPlatform::SetFilePermissions(), and lldb::SBProcess::WriteMemory().
SetError() [1/2]
void SBError::SetError (lldb_private::Status && lldb_error) protected
Definition at line 131 of file SBError.cpp.
References CreateIfNeeded(), and m_opaque_up.
SetError() [2/2]
void SBError::SetError (uint32_t err, lldb::ErrorType type)
Definition at line 124 of file SBError.cpp.
References CreateIfNeeded(), LLDB_INSTRUMENT_VA, m_opaque_up, and lldb_private::Status.
Referenced by lldb::SBBreakpoint::AddNameWithErrorHandling(), lldb::SBProcess::DeallocateMemory(), lldb::SBProcess::Destroy(), lldb::SBProcess::Detach(), lldb::SBStructuredData::GetDescription(), lldb::SBValue::GetError(), lldb::SBValueList::GetError(), lldb::SBWatchpoint::GetError(), lldb::SBThread::JumpToLine(), lldb::SBProcess::Kill(), lldb_private::python::SWIGBridge, lldb::SBThread::ReturnFromFrame(), lldb::SBProcess::SendEventData(), lldb::SBDebugger::SetInputString(), lldb::SBDebugger::SetInternalVariable(), lldb::SBBreakpoint::SetScriptCallbackBody(), lldb::SBBreakpointLocation::SetScriptCallbackBody(), lldb::SBBreakpointName::SetScriptCallbackBody(), lldb::SBBreakpoint::SetScriptCallbackFunction(), lldb::SBBreakpointLocation::SetScriptCallbackFunction(), lldb::SBBreakpointName::SetScriptCallbackFunction(), lldb::SBProcess::Signal(), lldb::SBProcess::Stop(), lldb::SBProcess::UnloadImage(), lldb::SBThread::UnwindInnermostExpression(), and ~SBError().
SetErrorString()
void SBError::SetErrorString (const char * err_str)
Definition at line 150 of file SBError.cpp.
References CreateIfNeeded(), lldb_private::Status::FromErrorString(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBTarget::BreakpointsCreateFromFile(), lldb::SBTarget::BreakpointsWriteToFile(), lldb::SBTarget::BreakpointsWriteToFile(), SBError(), lldb::SBTarget::SetSectionLoadAddress(), and ~SBError().
SetErrorToErrno()
void SBError::SetErrorToErrno ()
Definition at line 136 of file SBError.cpp.
References CreateIfNeeded(), lldb_private::Status::FromErrno(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBError().
SetErrorToGenericError()
void SBError::SetErrorToGenericError ()
Definition at line 143 of file SBError.cpp.
References CreateIfNeeded(), LLDB_INSTRUMENT_VA, m_opaque_up, and lldb_private::Status.
Referenced by ~SBError().
Success()
bool SBError::Success () const
Definition at line 81 of file SBError.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBDebugger::CreateTarget(), lldb::SBThread::UnwindInnermostExpression(), and ~SBError().
Friends And Related Symbol Documentation
lldb_private::python::SWIGBridge
friend class lldb_private::python::SWIGBridge friend
Definition at line 113 of file SBError.h.
References error(), get(), operator*(), operator->(), ref(), SBError(), and SetError().
lldb_private::ScriptInterpreter
friend class lldb_private::ScriptInterpreter friend
Definition at line 112 of file SBError.h.
SBBreakpoint
friend class SBBreakpoint friend
Definition at line 89 of file SBError.h.
References SBBreakpoint.
Referenced by SBBreakpoint.
SBBreakpointLocation
friend class SBBreakpointLocation friend
Definition at line 90 of file SBError.h.
References SBBreakpointLocation.
Referenced by SBBreakpointLocation.
SBBreakpointName
friend class SBBreakpointName friend
Definition at line 91 of file SBError.h.
References SBBreakpointName.
Referenced by SBBreakpointName.
SBCommandReturnObject
friend class SBCommandReturnObject friend
Definition at line 92 of file SBError.h.
References SBCommandReturnObject.
Referenced by SBCommandReturnObject.
SBCommunication
friend class SBCommunication friend
Definition at line 93 of file SBError.h.
References SBCommunication.
Referenced by SBCommunication.
SBData
friend class SBData friend
Definition at line 95 of file SBError.h.
References SBData.
Referenced by SBData.
SBDebugger
friend class SBDebugger friend
Definition at line 96 of file SBError.h.
References SBDebugger.
Referenced by SBDebugger.
SBFile
friend class SBFile friend
Definition at line 97 of file SBError.h.
References SBFile.
Referenced by SBFile.
SBFormat
friend class SBFormat friend
Definition at line 98 of file SBError.h.
References SBFormat.
Referenced by SBFormat.
SBFrame
friend class SBFrame friend
Definition at line 99 of file SBError.h.
References SBFrame.
Referenced by SBFrame.
SBHostOS
friend class SBHostOS friend
Definition at line 100 of file SBError.h.
References SBHostOS.
Referenced by SBHostOS.
SBPlatform
friend class SBPlatform friend
Definition at line 101 of file SBError.h.
References SBPlatform.
Referenced by SBPlatform.
SBProcess
friend class SBProcess friend
Definition at line 102 of file SBError.h.
References SBProcess.
Referenced by SBProcess.
SBReproducer
friend class SBReproducer friend
Definition at line 103 of file SBError.h.
References SBReproducer.
Referenced by SBReproducer.
SBSaveCoreOptions
friend class SBSaveCoreOptions friend
Definition at line 94 of file SBError.h.
References SBSaveCoreOptions.
Referenced by SBSaveCoreOptions.
SBStructuredData
friend class SBStructuredData friend
Definition at line 104 of file SBError.h.
References SBStructuredData.
Referenced by GetErrorData(), SBStructuredData, and ~SBError().
SBTarget
friend class SBTarget friend
Definition at line 105 of file SBError.h.
References SBTarget.
Referenced by SBTarget.
SBThread
friend class SBThread friend
Definition at line 106 of file SBError.h.
References SBThread.
Referenced by SBThread.
SBTrace
friend class SBTrace friend
Definition at line 107 of file SBError.h.
References SBTrace.
Referenced by SBTrace.
SBValue
friend class SBValue friend
Definition at line 108 of file SBError.h.
References SBValue.
Referenced by SBValue.
SBValueList
friend class SBValueList friend
Definition at line 109 of file SBError.h.
References SBValueList.
Referenced by SBValueList.
SBWatchpoint
friend class SBWatchpoint friend
Definition at line 110 of file SBError.h.
References SBWatchpoint.
Referenced by SBWatchpoint.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::Status> lldb::SBError::m_opaque_up private
Definition at line 128 of file SBError.h.
Referenced by Clear(), CreateIfNeeded(), Fail(), get(), GetCString(), GetDescription(), GetError(), GetErrorData(), GetType(), operator bool(), operator*(), operator->(), operator=(), ref(), SBError(), SBError(), SetError(), SetError(), SetErrorString(), SetErrorToErrno(), SetErrorToGenericError(), and Success().
The documentation for this class was generated from the following files:
SBError.h
SBError.cpp