LLDB: lldb_private::FuncUnwinders Class Reference
lldb_private::FuncUnwinders Class Reference
#include <FuncUnwinders.h>
Public Member Functions
FuncUnwinders (lldb_private::UnwindTable &unwind_table, Address addr, AddressRanges ranges)
~FuncUnwinders ()
destructor
std::shared_ptr< const UnwindPlan > GetUnwindPlanAtCallSite (Target &target, Thread &thread)
std::shared_ptr< const UnwindPlan > GetUnwindPlanAtNonCallSite (Target &target, lldb_private::Thread &thread)
std::shared_ptr< const UnwindPlan > GetUnwindPlanFastUnwind (Target &target, lldb_private::Thread &thread)
std::shared_ptr< const UnwindPlan > GetUnwindPlanArchitectureDefault (lldb_private::Thread &thread)
std::shared_ptr< const UnwindPlan > GetUnwindPlanArchitectureDefaultAtFunctionEntry (lldb_private::Thread &thread)
const Address & GetFunctionStartAddress () const
bool ContainsAddress (const Address &addr) const
std::shared_ptr< const UnwindPlan > GetAssemblyUnwindPlan (Target &target, Thread &thread)
std::shared_ptr< const UnwindPlan > GetObjectFileUnwindPlan (Target &target)
std::shared_ptr< const UnwindPlan > GetObjectFileAugmentedUnwindPlan (Target &target, Thread &thread)
std::shared_ptr< const UnwindPlan > GetEHFrameUnwindPlan (Target &target)
std::shared_ptr< const UnwindPlan > GetEHFrameAugmentedUnwindPlan (Target &target, Thread &thread)
std::shared_ptr< const UnwindPlan > GetDebugFrameUnwindPlan (Target &target)
std::shared_ptr< const UnwindPlan > GetDebugFrameAugmentedUnwindPlan (Target &target, Thread &thread)
std::shared_ptr< const UnwindPlan > GetCompactUnwindUnwindPlan (Target &target)
std::shared_ptr< const UnwindPlan > GetArmUnwindUnwindPlan (Target &target)
std::shared_ptr< const UnwindPlan > GetSymbolFileUnwindPlan (Thread &thread)
std::shared_ptr< const UnwindPlan > GetArchDefaultUnwindPlan (Thread &thread)
std::shared_ptr< const UnwindPlan > GetArchDefaultAtFuncEntryUnwindPlan (Thread &thread)
Private Member Functions
lldb::UnwindAssemblySP GetUnwindAssemblyProfiler (Target &target)
lldb_private::LazyBool CompareUnwindPlansForIdenticalInitialPCLocation (Thread &thread, const std::shared_ptr< const UnwindPlan > &a, const std::shared_ptr< const UnwindPlan > &b)
FuncUnwinders (const FuncUnwinders &)=delete
const FuncUnwinders & operator= (const FuncUnwinders &)=delete
Private Attributes
UnwindTable & m_unwind_table
Address m_addr
Start address of the function described by this object.
AddressRanges m_ranges
The address ranges of the function.
std::recursive_mutex m_mutex
std::shared_ptr< const UnwindPlan > m_unwind_plan_assembly_sp
std::shared_ptr< const UnwindPlan > m_unwind_plan_object_file_sp
std::shared_ptr< const UnwindPlan > m_unwind_plan_eh_frame_sp
std::shared_ptr< const UnwindPlan > m_unwind_plan_debug_frame_sp
std::shared_ptr< const UnwindPlan > m_unwind_plan_object_file_augmented_sp
std::shared_ptr< const UnwindPlan > m_unwind_plan_eh_frame_augmented_sp
std::shared_ptr< const UnwindPlan > m_unwind_plan_debug_frame_augmented_sp
std::vector< std::shared_ptr< const UnwindPlan > > m_unwind_plan_compact_unwind
std::shared_ptr< const UnwindPlan > m_unwind_plan_arm_unwind_sp
std::shared_ptr< const UnwindPlan > m_unwind_plan_symbol_file_sp
std::shared_ptr< const UnwindPlan > m_unwind_plan_fast_sp
std::shared_ptr< const UnwindPlan > m_unwind_plan_arch_default_sp
std::shared_ptr< const UnwindPlan > m_unwind_plan_arch_default_at_func_entry_sp
bool m_tried_unwind_plan_assembly: 1
bool m_tried_unwind_plan_eh_frame: 1
bool m_tried_unwind_plan_object_file: 1
bool m_tried_unwind_plan_debug_frame: 1
bool m_tried_unwind_plan_object_file_augmented: 1
bool m_tried_unwind_plan_eh_frame_augmented: 1
bool m_tried_unwind_plan_debug_frame_augmented: 1
bool m_tried_unwind_plan_compact_unwind: 1
bool m_tried_unwind_plan_arm_unwind: 1
bool m_tried_unwind_plan_symbol_file: 1
bool m_tried_unwind_fast: 1
bool m_tried_unwind_arch_default: 1
bool m_tried_unwind_arch_default_at_func_entry: 1
Address m_first_non_prologue_insn
Detailed Description
Definition at line 13 of file FuncUnwinders.h.
Constructor & Destructor Documentation
FuncUnwinders() [1/2]
FuncUnwinders::FuncUnwinders (lldb_private::UnwindTable & unwind_table, Address addr, AddressRanges ranges)
Definition at line 34 of file FuncUnwinders.cpp.
References m_addr, m_first_non_prologue_insn, m_ranges, m_tried_unwind_arch_default, m_tried_unwind_arch_default_at_func_entry, m_tried_unwind_fast, m_tried_unwind_plan_arm_unwind, m_tried_unwind_plan_assembly, m_tried_unwind_plan_compact_unwind, m_tried_unwind_plan_debug_frame, m_tried_unwind_plan_debug_frame_augmented, m_tried_unwind_plan_eh_frame, m_tried_unwind_plan_eh_frame_augmented, m_tried_unwind_plan_object_file, m_tried_unwind_plan_object_file_augmented, m_tried_unwind_plan_symbol_file, and m_unwind_table.
Referenced by FuncUnwinders(), and operator=().
~FuncUnwinders()
FuncUnwinders::~FuncUnwinders () default
destructor
FuncUnwinders() [2/2]
lldb_private::FuncUnwinders::FuncUnwinders (const FuncUnwinders &) private delete
References FuncUnwinders().
Member Function Documentation
CompareUnwindPlansForIdenticalInitialPCLocation()
LazyBool FuncUnwinders::CompareUnwindPlansForIdenticalInitialPCLocation (Thread & thread, const std::shared_ptr< const UnwindPlan > & a, const std::shared_ptr< const UnwindPlan > & b) private
Definition at line 349 of file FuncUnwinders.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb::eRegisterKindGeneric, RegisterNumber::GetAsKind(), lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::GetRegisterInfo(), and LLDB_REGNUM_GENERIC_PC.
Referenced by GetUnwindPlanAtNonCallSite().
ContainsAddress()
bool lldb_private::FuncUnwinders::ContainsAddress (const Address & addr) const inline
Definition at line 56 of file FuncUnwinders.h.
References lldb_private::AddressRange::ContainsFileAddress(), and m_ranges.
GetArchDefaultAtFuncEntryUnwindPlan()
std::shared_ptr< const UnwindPlan > lldb_private::FuncUnwinders::GetArchDefaultAtFuncEntryUnwindPlan (Thread & thread)
GetArchDefaultUnwindPlan()
std::shared_ptr< const UnwindPlan > lldb_private::FuncUnwinders::GetArchDefaultUnwindPlan (Thread & thread)
GetArmUnwindUnwindPlan()
std::shared_ptr< const UnwindPlan > FuncUnwinders::GetArmUnwindUnwindPlan (Target & target)
Definition at line 153 of file FuncUnwinders.cpp.
References lldb::eRegisterKindGeneric, lldb_private::ArmUnwindInfo::GetUnwindPlan(), m_mutex, m_ranges, m_tried_unwind_plan_arm_unwind, m_unwind_plan_arm_unwind_sp, and m_unwind_table.
Referenced by GetUnwindPlanAtCallSite().
GetAssemblyUnwindPlan()
std::shared_ptr< const UnwindPlan > FuncUnwinders::GetAssemblyUnwindPlan (Target & target, Thread & thread)
Definition at line 316 of file FuncUnwinders.cpp.
References lldb::eRegisterKindGeneric, lldb_private::AddressRange::GetByteSize(), GetUnwindAssemblyProfiler(), m_mutex, m_ranges, m_tried_unwind_plan_assembly, m_unwind_plan_assembly_sp, m_unwind_table, and lldb_private::AddressRange::SetByteSize().
Referenced by GetUnwindPlanAtNonCallSite().
GetCompactUnwindUnwindPlan()
std::shared_ptr< const UnwindPlan > FuncUnwinders::GetCompactUnwindUnwindPlan (Target & target)
Definition at line 81 of file FuncUnwinders.cpp.
References lldb::eRegisterKindGeneric, lldb_private::CompactUnwindInfo::GetUnwindPlan(), m_mutex, m_ranges, m_tried_unwind_plan_compact_unwind, m_unwind_plan_compact_unwind, and m_unwind_table.
Referenced by GetUnwindPlanAtCallSite().
GetDebugFrameAugmentedUnwindPlan()
std::shared_ptr< const UnwindPlan > FuncUnwinders::GetDebugFrameAugmentedUnwindPlan (Target & target, Thread & thread)
Definition at line 275 of file FuncUnwinders.cpp.
References lldb_private::ArchSpec::eCore_x86_32_i386, lldb_private::ArchSpec::eCore_x86_64_x86_64, lldb_private::ArchSpec::eCore_x86_64_x86_64h, lldb_private::Target::GetArchitecture(), lldb_private::ArchSpec::GetCore(), GetDebugFrameUnwindPlan(), GetUnwindAssemblyProfiler(), m_mutex, m_ranges, m_tried_unwind_plan_debug_frame_augmented, and m_unwind_plan_debug_frame_augmented_sp.
Referenced by GetUnwindPlanAtNonCallSite().
GetDebugFrameUnwindPlan()
std::shared_ptr< const UnwindPlan > FuncUnwinders::GetDebugFrameUnwindPlan (Target & target)
Definition at line 138 of file FuncUnwinders.cpp.
References m_addr, m_mutex, m_ranges, m_tried_unwind_plan_debug_frame, m_unwind_plan_debug_frame_sp, and m_unwind_table.
Referenced by GetDebugFrameAugmentedUnwindPlan(), GetUnwindPlanAtCallSite(), and GetUnwindPlanAtNonCallSite().
GetEHFrameAugmentedUnwindPlan()
std::shared_ptr< const UnwindPlan > FuncUnwinders::GetEHFrameAugmentedUnwindPlan (Target & target, Thread & thread)
Definition at line 237 of file FuncUnwinders.cpp.
References lldb_private::ArchSpec::eCore_x86_32_i386, lldb_private::ArchSpec::eCore_x86_64_x86_64, lldb_private::ArchSpec::eCore_x86_64_x86_64h, lldb_private::Target::GetArchitecture(), lldb_private::ArchSpec::GetCore(), GetEHFrameUnwindPlan(), GetUnwindAssemblyProfiler(), m_mutex, m_ranges, m_tried_unwind_plan_eh_frame_augmented, and m_unwind_plan_eh_frame_augmented_sp.
Referenced by GetUnwindPlanAtNonCallSite().
GetEHFrameUnwindPlan()
std::shared_ptr< const UnwindPlan > FuncUnwinders::GetEHFrameUnwindPlan (Target & target)
Definition at line 124 of file FuncUnwinders.cpp.
References m_addr, m_mutex, m_ranges, m_tried_unwind_plan_eh_frame, m_unwind_plan_eh_frame_sp, and m_unwind_table.
Referenced by GetEHFrameAugmentedUnwindPlan(), GetUnwindPlanAtCallSite(), and GetUnwindPlanAtNonCallSite().
GetFunctionStartAddress()
const Address & FuncUnwinders::GetFunctionStartAddress () const
Definition at line 490 of file FuncUnwinders.cpp.
References m_addr.
GetObjectFileAugmentedUnwindPlan()
std::shared_ptr< const UnwindPlan > FuncUnwinders::GetObjectFileAugmentedUnwindPlan (Target & target, Thread & thread)
Definition at line 207 of file FuncUnwinders.cpp.
References GetObjectFileUnwindPlan(), GetUnwindAssemblyProfiler(), m_mutex, m_ranges, m_tried_unwind_plan_object_file_augmented, and m_unwind_plan_object_file_augmented_sp.
Referenced by GetUnwindPlanAtNonCallSite().
GetObjectFileUnwindPlan()
std::shared_ptr< const UnwindPlan > FuncUnwinders::GetObjectFileUnwindPlan (Target & target)
Definition at line 109 of file FuncUnwinders.cpp.
References m_addr, m_mutex, m_ranges, m_tried_unwind_plan_object_file, m_unwind_plan_object_file_sp, and m_unwind_table.
Referenced by GetObjectFileAugmentedUnwindPlan(), GetUnwindPlanAtCallSite(), and GetUnwindPlanAtNonCallSite().
GetSymbolFileUnwindPlan()
std::shared_ptr< const UnwindPlan > FuncUnwinders::GetSymbolFileUnwindPlan (Thread & thread)
Definition at line 191 of file FuncUnwinders.cpp.
References m_mutex, m_ranges, m_tried_unwind_plan_symbol_file, m_unwind_plan_symbol_file_sp, and m_unwind_table.
Referenced by GetUnwindPlanAtCallSite(), and GetUnwindPlanAtNonCallSite().
GetUnwindAssemblyProfiler()
lldb::UnwindAssemblySP FuncUnwinders::GetUnwindAssemblyProfiler (Target & target) private
Definition at line 493 of file FuncUnwinders.cpp.
References lldb_private::UnwindAssembly::FindPlugin(), lldb_private::Target::GetArchitecture(), and m_unwind_table.
Referenced by GetAssemblyUnwindPlan(), GetDebugFrameAugmentedUnwindPlan(), GetEHFrameAugmentedUnwindPlan(), GetObjectFileAugmentedUnwindPlan(), and GetUnwindPlanFastUnwind().
GetUnwindPlanArchitectureDefault()
std::shared_ptr< const UnwindPlan > FuncUnwinders::GetUnwindPlanArchitectureDefault (lldb_private::Thread & thread)
Definition at line 453 of file FuncUnwinders.cpp.
References m_mutex, m_tried_unwind_arch_default, and m_unwind_plan_arch_default_sp.
Referenced by GetUnwindPlanAtNonCallSite().
GetUnwindPlanArchitectureDefaultAtFunctionEntry()
std::shared_ptr< const UnwindPlan > FuncUnwinders::GetUnwindPlanArchitectureDefaultAtFunctionEntry (lldb_private::Thread & thread)
Definition at line 470 of file FuncUnwinders.cpp.
References m_mutex, m_tried_unwind_arch_default_at_func_entry, and m_unwind_plan_arch_default_at_func_entry_sp.
Referenced by GetUnwindPlanAtNonCallSite().
GetUnwindPlanAtCallSite()
std::shared_ptr< const UnwindPlan > FuncUnwinders::GetUnwindPlanAtCallSite (Target & target, Thread & thread)
Definition at line 56 of file FuncUnwinders.cpp.
References GetArmUnwindUnwindPlan(), GetCompactUnwindUnwindPlan(), GetDebugFrameUnwindPlan(), GetEHFrameUnwindPlan(), GetObjectFileUnwindPlan(), GetSymbolFileUnwindPlan(), and m_mutex.
GetUnwindPlanAtNonCallSite()
std::shared_ptr< const UnwindPlan > FuncUnwinders::GetUnwindPlanAtNonCallSite (Target & target, lldb_private::Thread & thread)
Definition at line 379 of file FuncUnwinders.cpp.
References CompareUnwindPlansForIdenticalInitialPCLocation(), lldb_private::eLazyBoolNo, GetAssemblyUnwindPlan(), GetDebugFrameAugmentedUnwindPlan(), GetDebugFrameUnwindPlan(), GetEHFrameAugmentedUnwindPlan(), GetEHFrameUnwindPlan(), GetObjectFileAugmentedUnwindPlan(), GetObjectFileUnwindPlan(), GetSymbolFileUnwindPlan(), GetUnwindPlanArchitectureDefault(), and GetUnwindPlanArchitectureDefaultAtFunctionEntry().
GetUnwindPlanFastUnwind()
std::shared_ptr< const UnwindPlan > FuncUnwinders::GetUnwindPlanFastUnwind (Target & target, lldb_private::Thread & thread)
Definition at line 436 of file FuncUnwinders.cpp.
References lldb::eRegisterKindGeneric, GetUnwindAssemblyProfiler(), m_mutex, m_ranges, m_tried_unwind_fast, and m_unwind_plan_fast_sp.
operator=()
const FuncUnwinders & lldb_private::FuncUnwinders::operator= (const FuncUnwinders &) private delete
References FuncUnwinders().
Member Data Documentation
m_addr
Address lldb_private::FuncUnwinders::m_addr private
Start address of the function described by this object.
Definition at line 110 of file FuncUnwinders.h.
Referenced by FuncUnwinders(), GetDebugFrameUnwindPlan(), GetEHFrameUnwindPlan(), GetFunctionStartAddress(), and GetObjectFileUnwindPlan().
m_first_non_prologue_insn
Address lldb_private::FuncUnwinders::m_first_non_prologue_insn private
Definition at line 147 of file FuncUnwinders.h.
Referenced by FuncUnwinders().
m_mutex
std::recursive_mutex lldb_private::FuncUnwinders::m_mutex private
Definition at line 115 of file FuncUnwinders.h.
Referenced by GetArmUnwindUnwindPlan(), GetAssemblyUnwindPlan(), GetCompactUnwindUnwindPlan(), GetDebugFrameAugmentedUnwindPlan(), GetDebugFrameUnwindPlan(), GetEHFrameAugmentedUnwindPlan(), GetEHFrameUnwindPlan(), GetObjectFileAugmentedUnwindPlan(), GetObjectFileUnwindPlan(), GetSymbolFileUnwindPlan(), GetUnwindPlanArchitectureDefault(), GetUnwindPlanArchitectureDefaultAtFunctionEntry(), GetUnwindPlanAtCallSite(), and GetUnwindPlanFastUnwind().
m_ranges
AddressRanges lldb_private::FuncUnwinders::m_ranges private
The address ranges of the function.
Definition at line 113 of file FuncUnwinders.h.
Referenced by ContainsAddress(), FuncUnwinders(), GetArmUnwindUnwindPlan(), GetAssemblyUnwindPlan(), GetCompactUnwindUnwindPlan(), GetDebugFrameAugmentedUnwindPlan(), GetDebugFrameUnwindPlan(), GetEHFrameAugmentedUnwindPlan(), GetEHFrameUnwindPlan(), GetObjectFileAugmentedUnwindPlan(), GetObjectFileUnwindPlan(), GetSymbolFileUnwindPlan(), and GetUnwindPlanFastUnwind().
m_tried_unwind_arch_default
bool lldb_private::FuncUnwinders::m_tried_unwind_arch_default private
Definition at line 144 of file FuncUnwinders.h.
Referenced by FuncUnwinders(), and GetUnwindPlanArchitectureDefault().
m_tried_unwind_arch_default_at_func_entry
bool lldb_private::FuncUnwinders::m_tried_unwind_arch_default_at_func_entry private
Definition at line 145 of file FuncUnwinders.h.
Referenced by FuncUnwinders(), and GetUnwindPlanArchitectureDefaultAtFunctionEntry().
m_tried_unwind_fast
bool lldb_private::FuncUnwinders::m_tried_unwind_fast private
Definition at line 144 of file FuncUnwinders.h.
Referenced by FuncUnwinders(), and GetUnwindPlanFastUnwind().
m_tried_unwind_plan_arm_unwind
bool lldb_private::FuncUnwinders::m_tried_unwind_plan_arm_unwind private
Definition at line 143 of file FuncUnwinders.h.
Referenced by FuncUnwinders(), and GetArmUnwindUnwindPlan().
m_tried_unwind_plan_assembly
bool lldb_private::FuncUnwinders::m_tried_unwind_plan_assembly private
Definition at line 136 of file FuncUnwinders.h.
Referenced by FuncUnwinders(), and GetAssemblyUnwindPlan().
m_tried_unwind_plan_compact_unwind
bool lldb_private::FuncUnwinders::m_tried_unwind_plan_compact_unwind private
Definition at line 142 of file FuncUnwinders.h.
Referenced by FuncUnwinders(), and GetCompactUnwindUnwindPlan().
m_tried_unwind_plan_debug_frame
bool lldb_private::FuncUnwinders::m_tried_unwind_plan_debug_frame private
Definition at line 138 of file FuncUnwinders.h.
Referenced by FuncUnwinders(), and GetDebugFrameUnwindPlan().
m_tried_unwind_plan_debug_frame_augmented
bool lldb_private::FuncUnwinders::m_tried_unwind_plan_debug_frame_augmented private
Definition at line 141 of file FuncUnwinders.h.
Referenced by FuncUnwinders(), and GetDebugFrameAugmentedUnwindPlan().
m_tried_unwind_plan_eh_frame
bool lldb_private::FuncUnwinders::m_tried_unwind_plan_eh_frame private
Definition at line 136 of file FuncUnwinders.h.
Referenced by FuncUnwinders(), and GetEHFrameUnwindPlan().
m_tried_unwind_plan_eh_frame_augmented
bool lldb_private::FuncUnwinders::m_tried_unwind_plan_eh_frame_augmented private
Definition at line 140 of file FuncUnwinders.h.
Referenced by FuncUnwinders(), and GetEHFrameAugmentedUnwindPlan().
m_tried_unwind_plan_object_file
bool lldb_private::FuncUnwinders::m_tried_unwind_plan_object_file private
Definition at line 137 of file FuncUnwinders.h.
Referenced by FuncUnwinders(), and GetObjectFileUnwindPlan().
m_tried_unwind_plan_object_file_augmented
bool lldb_private::FuncUnwinders::m_tried_unwind_plan_object_file_augmented private
Definition at line 139 of file FuncUnwinders.h.
Referenced by FuncUnwinders(), and GetObjectFileAugmentedUnwindPlan().
m_tried_unwind_plan_symbol_file
bool lldb_private::FuncUnwinders::m_tried_unwind_plan_symbol_file private
Definition at line 143 of file FuncUnwinders.h.
Referenced by FuncUnwinders(), and GetSymbolFileUnwindPlan().
m_unwind_plan_arch_default_at_func_entry_sp
std::shared_ptr<const UnwindPlan> lldb_private::FuncUnwinders::m_unwind_plan_arch_default_at_func_entry_sp private
Definition at line 132 of file FuncUnwinders.h.
Referenced by GetUnwindPlanArchitectureDefaultAtFunctionEntry().
m_unwind_plan_arch_default_sp
std::shared_ptr<const UnwindPlan> lldb_private::FuncUnwinders::m_unwind_plan_arch_default_sp private
Definition at line 131 of file FuncUnwinders.h.
Referenced by GetUnwindPlanArchitectureDefault().
m_unwind_plan_arm_unwind_sp
std::shared_ptr<const UnwindPlan> lldb_private::FuncUnwinders::m_unwind_plan_arm_unwind_sp private
Definition at line 128 of file FuncUnwinders.h.
Referenced by GetArmUnwindUnwindPlan().
m_unwind_plan_assembly_sp
std::shared_ptr<const UnwindPlan> lldb_private::FuncUnwinders::m_unwind_plan_assembly_sp private
Definition at line 117 of file FuncUnwinders.h.
Referenced by GetAssemblyUnwindPlan().
m_unwind_plan_compact_unwind
std::vector<std::shared_ptr<const UnwindPlan> > lldb_private::FuncUnwinders::m_unwind_plan_compact_unwind private
Definition at line 127 of file FuncUnwinders.h.
Referenced by GetCompactUnwindUnwindPlan().
m_unwind_plan_debug_frame_augmented_sp
std::shared_ptr<const UnwindPlan> lldb_private::FuncUnwinders::m_unwind_plan_debug_frame_augmented_sp private
Definition at line 125 of file FuncUnwinders.h.
Referenced by GetDebugFrameAugmentedUnwindPlan().
m_unwind_plan_debug_frame_sp
std::shared_ptr<const UnwindPlan> lldb_private::FuncUnwinders::m_unwind_plan_debug_frame_sp private
Definition at line 120 of file FuncUnwinders.h.
Referenced by GetDebugFrameUnwindPlan().
m_unwind_plan_eh_frame_augmented_sp
std::shared_ptr<const UnwindPlan> lldb_private::FuncUnwinders::m_unwind_plan_eh_frame_augmented_sp private
Definition at line 124 of file FuncUnwinders.h.
Referenced by GetEHFrameAugmentedUnwindPlan().
m_unwind_plan_eh_frame_sp
std::shared_ptr<const UnwindPlan> lldb_private::FuncUnwinders::m_unwind_plan_eh_frame_sp private
Definition at line 119 of file FuncUnwinders.h.
Referenced by GetEHFrameUnwindPlan().
m_unwind_plan_fast_sp
std::shared_ptr<const UnwindPlan> lldb_private::FuncUnwinders::m_unwind_plan_fast_sp private
Definition at line 130 of file FuncUnwinders.h.
Referenced by GetUnwindPlanFastUnwind().
m_unwind_plan_object_file_augmented_sp
std::shared_ptr<const UnwindPlan> lldb_private::FuncUnwinders::m_unwind_plan_object_file_augmented_sp private
Definition at line 123 of file FuncUnwinders.h.
Referenced by GetObjectFileAugmentedUnwindPlan().
m_unwind_plan_object_file_sp
std::shared_ptr<const UnwindPlan> lldb_private::FuncUnwinders::m_unwind_plan_object_file_sp private
Definition at line 118 of file FuncUnwinders.h.
Referenced by GetObjectFileUnwindPlan().
m_unwind_plan_symbol_file_sp
std::shared_ptr<const UnwindPlan> lldb_private::FuncUnwinders::m_unwind_plan_symbol_file_sp private
Definition at line 129 of file FuncUnwinders.h.
Referenced by GetSymbolFileUnwindPlan().
m_unwind_table
UnwindTable& lldb_private::FuncUnwinders::m_unwind_table private
Definition at line 107 of file FuncUnwinders.h.
Referenced by FuncUnwinders(), GetArmUnwindUnwindPlan(), GetAssemblyUnwindPlan(), GetCompactUnwindUnwindPlan(), GetDebugFrameUnwindPlan(), GetEHFrameUnwindPlan(), GetObjectFileUnwindPlan(), GetSymbolFileUnwindPlan(), and GetUnwindAssemblyProfiler().
The documentation for this class was generated from the following files:
FuncUnwinders.h
FuncUnwinders.cpp