LLDB: lldb_private::OptionGroupPlatform Class Reference
lldb_private::OptionGroupPlatform Class Reference
#include <OptionGroupPlatform.h>
Public Member Functions
OptionGroupPlatform (bool include_platform_option)
~OptionGroupPlatform () override=default
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext *execution_context) override
Status SetOptionValue (uint32_t, const char *, ExecutionContext *)=delete
void OptionParsingStarting (ExecutionContext *execution_context) override
lldb::PlatformSP CreatePlatformWithOptions (CommandInterpreter &interpreter, const ArchSpec &arch, bool make_selected, Status &error, ArchSpec &platform_arch) const
bool PlatformWasSpecified () const
void SetPlatformName (const char *platform_name)
const std::string & GetSDKRootDirectory () const
void SetSDKRootDirectory (std::string sdk_root_directory)
const std::string & GetSDKBuild () const
void SetSDKBuild (std::string sdk_build)
bool PlatformMatches (const lldb::PlatformSP &platform_sp) const
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Protected Attributes
std::string m_platform_name
std::string m_sdk_sysroot
std::string m_sdk_build
llvm::VersionTuple m_os_version
bool m_include_platform_option
Detailed Description
Definition at line 21 of file OptionGroupPlatform.h.
Constructor & Destructor Documentation
OptionGroupPlatform()
lldb_private::OptionGroupPlatform::OptionGroupPlatform (bool include_platform_option) inline
Definition at line 23 of file OptionGroupPlatform.h.
References m_include_platform_option.
~OptionGroupPlatform()
lldb_private::OptionGroupPlatform::~OptionGroupPlatform () override default
Member Function Documentation
CreatePlatformWithOptions()
PlatformSP OptionGroupPlatform::CreatePlatformWithOptions (CommandInterpreter & interpreter, const ArchSpec & arch, bool make_selected, Status & error, ArchSpec & platform_arch) const
Definition at line 18 of file OptionGroupPlatform.cpp.
References lldb_private::ArchSpec::CompatibleMatch, lldb_private::PlatformList::Create(), error(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::CommandInterpreter::GetDebugger(), lldb_private::PlatformList::GetOrCreate(), lldb_private::Debugger::GetPlatformList(), lldb_private::ArchSpec::GetTriple(), lldb_private::ArchSpec::IsValid(), m_os_version, m_platform_name, m_sdk_build, m_sdk_sysroot, and lldb_private::PlatformList::SetSelectedPlatform().
GetDefinitions()
llvm::ArrayRef< OptionDefinition > OptionGroupPlatform::GetDefinitions () override virtual
Implements lldb_private::OptionGroup.
Definition at line 87 of file OptionGroupPlatform.cpp.
References g_option_table, and m_include_platform_option.
GetSDKBuild()
const std::string & lldb_private::OptionGroupPlatform::GetSDKBuild () const inline
Definition at line 56 of file OptionGroupPlatform.h.
References m_sdk_build.
GetSDKRootDirectory()
const std::string & lldb_private::OptionGroupPlatform::GetSDKRootDirectory () const inline
Definition at line 50 of file OptionGroupPlatform.h.
References m_sdk_sysroot.
OptionParsingStarting()
void OptionGroupPlatform::OptionParsingStarting (ExecutionContext * execution_context) override virtual
Implements lldb_private::OptionGroup.
Definition at line 63 of file OptionGroupPlatform.cpp.
References m_os_version, m_platform_name, m_sdk_build, and m_sdk_sysroot.
PlatformMatches()
bool OptionGroupPlatform::PlatformMatches (const lldb::PlatformSP & platform_sp) const
Definition at line 129 of file OptionGroupPlatform.cpp.
References m_os_version, m_platform_name, m_sdk_build, and m_sdk_sysroot.
PlatformWasSpecified()
bool lldb_private::OptionGroupPlatform::PlatformWasSpecified () const inline
Definition at line 41 of file OptionGroupPlatform.h.
References m_platform_name.
SetOptionValue() [1/2]
Status OptionGroupPlatform::SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext * execution_context) override virtual
Implements lldb_private::OptionGroup.
Definition at line 95 of file OptionGroupPlatform.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormatv(), g_option_table, m_include_platform_option, m_os_version, m_platform_name, m_sdk_build, and m_sdk_sysroot.
SetOptionValue() [2/2]
Status lldb_private::OptionGroupPlatform::SetOptionValue (uint32_t , const char * , ExecutionContext *) delete
References error().
SetPlatformName()
void lldb_private::OptionGroupPlatform::SetPlatformName (const char * platform_name) inline
Definition at line 43 of file OptionGroupPlatform.h.
References m_platform_name.
Referenced by lldb::SBDebugger::CreateTarget().
SetSDKBuild()
void lldb_private::OptionGroupPlatform::SetSDKBuild (std::string sdk_build) inline
Definition at line 58 of file OptionGroupPlatform.h.
References m_sdk_build.
SetSDKRootDirectory()
void lldb_private::OptionGroupPlatform::SetSDKRootDirectory (std::string sdk_root_directory) inline
Definition at line 52 of file OptionGroupPlatform.h.
References m_sdk_sysroot.
Member Data Documentation
m_include_platform_option
bool lldb_private::OptionGroupPlatform::m_include_platform_option protected
Definition at line 69 of file OptionGroupPlatform.h.
Referenced by GetDefinitions(), OptionGroupPlatform(), and SetOptionValue().
m_os_version
llvm::VersionTuple lldb_private::OptionGroupPlatform::m_os_version protected
Definition at line 68 of file OptionGroupPlatform.h.
Referenced by CreatePlatformWithOptions(), OptionParsingStarting(), PlatformMatches(), and SetOptionValue().
m_platform_name
std::string lldb_private::OptionGroupPlatform::m_platform_name protected
Definition at line 65 of file OptionGroupPlatform.h.
Referenced by CreatePlatformWithOptions(), OptionParsingStarting(), PlatformMatches(), PlatformWasSpecified(), SetOptionValue(), and SetPlatformName().
m_sdk_build
std::string lldb_private::OptionGroupPlatform::m_sdk_build protected
Definition at line 67 of file OptionGroupPlatform.h.
Referenced by CreatePlatformWithOptions(), GetSDKBuild(), OptionParsingStarting(), PlatformMatches(), SetOptionValue(), and SetSDKBuild().
m_sdk_sysroot
std::string lldb_private::OptionGroupPlatform::m_sdk_sysroot protected
Definition at line 66 of file OptionGroupPlatform.h.
Referenced by CreatePlatformWithOptions(), GetSDKRootDirectory(), OptionParsingStarting(), PlatformMatches(), SetOptionValue(), and SetSDKRootDirectory().
The documentation for this class was generated from the following files:
OptionGroupPlatform.h
OptionGroupPlatform.cpp