LLDB: lldb_private::Stoppoint Class Reference
lldb_private::Stoppoint Class Reference abstract
#include <Stoppoint.h>
Public Member Functions
Stoppoint ()
virtual ~Stoppoint ()
virtual void Dump (Stream *)=0
virtual bool IsEnabled ()=0
virtual void SetEnabled (bool enable)=0
lldb::break_id_t GetID () const
void SetID (lldb::break_id_t bid)
Protected Attributes
lldb::break_id_t m_bid = LLDB_INVALID_BREAK_ID
Private Member Functions
Stoppoint (const Stoppoint &)=delete
const Stoppoint & operator= (const Stoppoint &)=delete
Detailed Description
Definition at line 17 of file Stoppoint.h.
Constructor & Destructor Documentation
Stoppoint() [1/2]
Stoppoint::Stoppoint () default
Referenced by operator=(), and Stoppoint().
~Stoppoint()
Stoppoint::~Stoppoint () virtual default
Stoppoint() [2/2]
lldb_private::Stoppoint::Stoppoint (const Stoppoint &) private delete
References Stoppoint().
Member Function Documentation
Dump()
virtual void lldb_private::Stoppoint::Dump (Stream *) pure virtual
Implemented in lldb_private::Breakpoint.
GetID()
break_id_t Stoppoint::GetID () const
Definition at line 22 of file Stoppoint.cpp.
References m_bid.
Referenced by InstrumentationRuntimeASanLibsanitizers::Activate(), lldb_private::InstrumentationRuntimeASan::Activate(), lldb_private::InstrumentationRuntimeMainThreadChecker::Activate(), lldb_private::InstrumentationRuntimeTSan::Activate(), lldb_private::InstrumentationRuntimeUBSan::Activate(), lldb_private::BreakpointLocationCollection::Add(), CommandObjectBreakpointClear::DoExecute(), lldb_private::ThreadPlanCallFunction::DoPlanExplainsStop(), lldb_private::BreakpointIDList::FindAndReplaceIDRanges(), lldb_private::Breakpoint::GetDescriptionForType(), lldb_private::Breakpoint::GetStatistics(), lldb_private::Breakpoint::InvokeCallback(), lldb_private::Breakpoint::ModuleReplaced(), lldb_private::Breakpoint::ModulesChanged(), lldb_private::ThreadPlanRunToAddress::SetInitialBreakpoints(), JITLoaderGDB::SetJITBreakpoint(), DynamicLoaderMacOS::SetNotificationBreakpoint(), DynamicLoaderMacOSXDYLD::SetNotificationBreakpoint(), DynamicLoaderDarwinKernel::SetNotificationBreakpointIfNeeded(), DynamicLoaderHexagonDYLD::SetRendezvousBreakpoint(), lldb_private::ThreadPlanStepOut::SetupReturnAddress(), lldb_private::StopInfoBreakpoint::StoreBPInfo(), lldb_private::ThreadPlanStepThrough::ThreadPlanStepThrough(), and lldb_private::ThreadPlanStepUntil::ThreadPlanStepUntil().
IsEnabled()
virtual bool lldb_private::Stoppoint::IsEnabled () pure virtual
Implemented in lldb_private::Breakpoint.
operator=()
const Stoppoint & lldb_private::Stoppoint::operator= (const Stoppoint &) private delete
References Stoppoint().
SetEnabled()
virtual void lldb_private::Stoppoint::SetEnabled (bool enable) pure virtual
Implemented in lldb_private::Breakpoint.
SetID()
void Stoppoint::SetID (lldb::break_id_t bid)
Definition at line 24 of file Stoppoint.cpp.
References m_bid.
Member Data Documentation
m_bid
lldb::break_id_t lldb_private::Stoppoint::m_bid = LLDB_INVALID_BREAK_ID protected
Definition at line 36 of file Stoppoint.h.
Referenced by GetID(), lldb_private::Breakpoint::IsInternal(), and SetID().
The documentation for this class was generated from the following files:
Stoppoint.h
Stoppoint.cpp