LLDB: lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorLegacy Class Reference
lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorLegacy Class Reference
Public Member Functions
bool IsPossibleTaggedPointer (lldb::addr_t ptr) override
ObjCLanguageRuntime::ClassDescriptorSP GetClassDescriptor (lldb::addr_t ptr) override
Public Member Functions inherited from lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2
~TaggedPointerVendorV2 () override=default
Public Member Functions inherited from lldb_private::ObjCLanguageRuntime::TaggedPointerVendor
virtual ~TaggedPointerVendor ()=default
Protected Member Functions
TaggedPointerVendorLegacy (AppleObjCRuntimeV2 &runtime)
TaggedPointerVendorLegacy (const TaggedPointerVendorLegacy &)=delete
const TaggedPointerVendorLegacy & operator= (const TaggedPointerVendorLegacy &)=delete
Protected Member Functions inherited from lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2
TaggedPointerVendorV2 (AppleObjCRuntimeV2 &runtime)
Protected Member Functions inherited from lldb_private::ObjCLanguageRuntime::TaggedPointerVendor
TaggedPointerVendor ()=default
Friends
class AppleObjCRuntimeV2::TaggedPointerVendorV2
Additional Inherited Members
Static Public Member Functions inherited from lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2
static TaggedPointerVendorV2 * CreateInstance (AppleObjCRuntimeV2 &runtime, const lldb::ModuleSP &objc_module_sp)
Protected Attributes inherited from lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2
AppleObjCRuntimeV2 & m_runtime
Detailed Description
Definition at line 271 of file AppleObjCRuntimeV2.h.
Constructor & Destructor Documentation
TaggedPointerVendorLegacy() [1/2]
lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorLegacy::TaggedPointerVendorLegacy (AppleObjCRuntimeV2 & runtime) inline protected
Definition at line 279 of file AppleObjCRuntimeV2.h.
References lldb_private::AppleObjCRuntimeV2::AppleObjCRuntimeV2(), and AppleObjCRuntimeV2::TaggedPointerVendorV2.
Referenced by operator=(), and TaggedPointerVendorLegacy().
TaggedPointerVendorLegacy() [2/2]
lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorLegacy::TaggedPointerVendorLegacy (const TaggedPointerVendorLegacy &) protected delete
References TaggedPointerVendorLegacy().
Member Function Documentation
GetClassDescriptor()
ObjCLanguageRuntime::ClassDescriptorSP AppleObjCRuntimeV2::TaggedPointerVendorLegacy::GetClassDescriptor (lldb::addr_t ptr) override virtual
Implements lldb_private::ObjCLanguageRuntime::TaggedPointerVendor.
Definition at line 2982 of file AppleObjCRuntimeV2.cpp.
References error().
IsPossibleTaggedPointer()
bool AppleObjCRuntimeV2::TaggedPointerVendorLegacy::IsPossibleTaggedPointer (lldb::addr_t ptr) override virtual
Implements lldb_private::ObjCLanguageRuntime::TaggedPointerVendor.
Definition at line 2976 of file AppleObjCRuntimeV2.cpp.
References error().
operator=()
const TaggedPointerVendorLegacy & lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorLegacy::operator= (const TaggedPointerVendorLegacy &) protected delete
References TaggedPointerVendorLegacy().
Friends And Related Symbol Documentation
AppleObjCRuntimeV2::TaggedPointerVendorV2
friend class AppleObjCRuntimeV2::TaggedPointerVendorV2 friend
Definition at line 282 of file AppleObjCRuntimeV2.h.
Referenced by TaggedPointerVendorLegacy().
The documentation for this class was generated from the following files:
AppleObjCRuntimeV2.h
AppleObjCRuntimeV2.cpp