LLDB: lldb::SBAddressRangeList Class Reference
lldb::SBAddressRangeList Class Reference
#include <SBAddressRangeList.h>
Public Member Functions
SBAddressRangeList ()
SBAddressRangeList (const lldb::SBAddressRangeList &rhs)
~SBAddressRangeList ()
const lldb::SBAddressRangeList & operator= (const lldb::SBAddressRangeList &rhs)
uint32_t GetSize () const
void Clear ()
SBAddressRange GetAddressRangeAtIndex (uint64_t idx)
void Append (const lldb::SBAddressRange &addr_range)
void Append (const lldb::SBAddressRangeList &addr_range_list)
bool GetDescription (lldb::SBStream &description, const SBTarget &target)
Private Member Functions
lldb_private::AddressRangeListImpl & ref () const
Private Attributes
std::unique_ptr< lldb_private::AddressRangeListImpl > m_opaque_up
Friends
class SBBlock
class SBProcess
class SBFunction
Detailed Description
Definition at line 22 of file SBAddressRangeList.h.
Constructor & Destructor Documentation
SBAddressRangeList() [1/2]
SBAddressRangeList::SBAddressRangeList ()
Definition at line 23 of file SBAddressRangeList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by Append(), operator=(), and SBAddressRangeList().
SBAddressRangeList() [2/2]
SBAddressRangeList::SBAddressRangeList (const lldb::SBAddressRangeList & rhs)
Definition at line 28 of file SBAddressRangeList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and SBAddressRangeList().
~SBAddressRangeList()
SBAddressRangeList::~SBAddressRangeList () default
References Append(), Clear(), GetAddressRangeAtIndex(), GetDescription(), GetSize(), and operator=().
Member Function Documentation
Append() [1/2]
void SBAddressRangeList::Append (const lldb::SBAddressRange & addr_range)
Definition at line 64 of file SBAddressRangeList.cpp.
References lldb_private::AddressRangeListImpl::Append(), LLDB_INSTRUMENT_VA, lldb::SBAddressRange::m_opaque_up, and ref().
Referenced by ~SBAddressRangeList().
Append() [2/2]
void SBAddressRangeList::Append (const lldb::SBAddressRangeList & addr_range_list)
Definition at line 70 of file SBAddressRangeList.cpp.
References lldb_private::AddressRangeListImpl::Append(), LLDB_INSTRUMENT_VA, m_opaque_up, ref(), and SBAddressRangeList().
Clear()
void SBAddressRangeList::Clear ()
Definition at line 58 of file SBAddressRangeList.cpp.
References lldb_private::AddressRangeListImpl::Clear(), LLDB_INSTRUMENT_VA, and ref().
Referenced by ~SBAddressRangeList().
GetAddressRangeAtIndex()
SBAddressRange SBAddressRangeList::GetAddressRangeAtIndex (uint64_t idx)
Definition at line 50 of file SBAddressRangeList.cpp.
References lldb_private::AddressRangeListImpl::GetAddressRangeAtIndex(), LLDB_INSTRUMENT_VA, lldb::SBAddressRange::m_opaque_up, and ref().
Referenced by GetDescription(), and ~SBAddressRangeList().
GetDescription()
bool SBAddressRangeList::GetDescription (lldb::SBStream & description, const SBTarget & target)
Definition at line 76 of file SBAddressRangeList.cpp.
References GetAddressRangeAtIndex(), lldb::SBAddressRange::GetDescription(), GetSize(), LLDB_INSTRUMENT_VA, lldb_private::Stream::Printf(), and lldb::SBStream::ref().
Referenced by ~SBAddressRangeList().
GetSize()
uint32_t SBAddressRangeList::GetSize () const
Definition at line 44 of file SBAddressRangeList.cpp.
References lldb_private::AddressRangeListImpl::GetSize(), LLDB_INSTRUMENT_VA, and ref().
Referenced by GetDescription(), and ~SBAddressRangeList().
operator=()
const SBAddressRangeList & SBAddressRangeList::operator= (const lldb::SBAddressRangeList & rhs)
Definition at line 36 of file SBAddressRangeList.cpp.
References LLDB_INSTRUMENT_VA, ref(), and SBAddressRangeList().
Referenced by ~SBAddressRangeList().
ref()
lldb_private::AddressRangeListImpl & SBAddressRangeList::ref () const private
Definition at line 96 of file SBAddressRangeList.cpp.
References m_opaque_up.
Referenced by Append(), Append(), Clear(), lldb::SBProcess::FindRangesInMemory(), GetAddressRangeAtIndex(), lldb::SBFunction::GetRanges(), GetSize(), operator=(), and SBFunction.
Friends And Related Symbol Documentation
SBBlock
friend class SBBlock friend
Definition at line 46 of file SBAddressRangeList.h.
References SBBlock.
Referenced by SBBlock.
SBFunction
friend class SBFunction friend
Definition at line 48 of file SBAddressRangeList.h.
References ref(), and SBFunction.
Referenced by SBFunction.
SBProcess
friend class SBProcess friend
Definition at line 47 of file SBAddressRangeList.h.
References SBProcess.
Referenced by SBProcess.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::AddressRangeListImpl> lldb::SBAddressRangeList::m_opaque_up private
Definition at line 52 of file SBAddressRangeList.h.
Referenced by Append(), lldb::SBProcess::FindRangesInMemory(), lldb::SBBlock::GetRanges(), ref(), SBAddressRangeList(), and SBAddressRangeList().
The documentation for this class was generated from the following files:
SBAddressRangeList.h
SBAddressRangeList.cpp