LLDB: lldb_private::ResumeActionList Class Reference
lldb_private::ResumeActionList Class Reference
#include <Debug.h>
Public Member Functions
ResumeActionList ()=default
ResumeActionList (lldb::StateType default_action, int signal)
ResumeActionList (const ResumeAction *actions, size_t num_actions)
~ResumeActionList ()=default
bool IsEmpty () const
void Append (const ResumeAction &action)
void AppendAction (lldb::tid_t tid, lldb::StateType state, int signal=0)
void AppendResumeAll ()
void AppendSuspendAll ()
void AppendStepAll ()
const ResumeAction * GetActionForThread (lldb::tid_t tid, bool default_ok) const
size_t NumActionsWithState (lldb::StateType state) const
bool SetDefaultThreadActionIfNeeded (lldb::StateType action, int signal)
void SetSignalHandledForThread (lldb::tid_t tid) const
const ResumeAction * GetFirst () const
size_t GetSize () const
void Clear ()
Protected Attributes
std::vector< ResumeAction > m_actions
std::vector< bool > m_signal_handled
Detailed Description
Definition at line 33 of file Debug.h.
Constructor & Destructor Documentation
ResumeActionList() [1/3]
lldb_private::ResumeActionList::ResumeActionList () default
ResumeActionList() [2/3]
lldb_private::ResumeActionList::ResumeActionList (lldb::StateType default_action, int signal) inline
Definition at line 37 of file Debug.h.
References SetDefaultThreadActionIfNeeded().
ResumeActionList() [3/3]
lldb_private::ResumeActionList::ResumeActionList (const ResumeAction * actions, size_t num_actions) inline
Definition at line 41 of file Debug.h.
References m_actions, and m_signal_handled.
~ResumeActionList()
lldb_private::ResumeActionList::~ResumeActionList () default
Member Function Documentation
Append()
void lldb_private::ResumeActionList::Append (const ResumeAction & action) inline
Definition at line 52 of file Debug.h.
References m_actions, and m_signal_handled.
Referenced by AppendAction(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_C(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_s().
AppendAction()
void lldb_private::ResumeActionList::AppendAction (lldb::tid_t tid, lldb::StateType state, int signal = 0) inline
Definition at line 57 of file Debug.h.
References Append().
Referenced by AppendResumeAll(), AppendStepAll(), and AppendSuspendAll().
AppendResumeAll()
void lldb_private::ResumeActionList::AppendResumeAll () inline
Definition at line 62 of file Debug.h.
References AppendAction(), lldb::eStateRunning, and LLDB_INVALID_THREAD_ID.
AppendStepAll()
void lldb_private::ResumeActionList::AppendStepAll () inline
Definition at line 70 of file Debug.h.
References AppendAction(), lldb::eStateStepping, and LLDB_INVALID_THREAD_ID.
AppendSuspendAll()
void lldb_private::ResumeActionList::AppendSuspendAll () inline
Definition at line 66 of file Debug.h.
References AppendAction(), lldb::eStateStopped, and LLDB_INVALID_THREAD_ID.
Clear()
void lldb_private::ResumeActionList::Clear () inline
Definition at line 121 of file Debug.h.
References m_actions, and m_signal_handled.
GetActionForThread()
const ResumeAction * lldb_private::ResumeActionList::GetActionForThread (lldb::tid_t tid, bool default_ok) const inline
Definition at line 74 of file Debug.h.
References GetActionForThread(), LLDB_INVALID_THREAD_ID, and m_actions.
Referenced by ComputeSignalInfo(), GetActionForThread(), lldb_private::NativeProcessWindows::Resume(), lldb_private::process_freebsd::NativeProcessFreeBSD::Resume(), lldb_private::process_linux::NativeProcessLinux::Resume(), lldb_private::process_netbsd::NativeProcessNetBSD::Resume(), ResumeActionListStopsAllThreads(), and SetDefaultThreadActionIfNeeded().
GetFirst()
const ResumeAction * lldb_private::ResumeActionList::GetFirst () const inline
Definition at line 117 of file Debug.h.
References m_actions.
GetSize()
size_t lldb_private::ResumeActionList::GetSize () const inline
Definition at line 119 of file Debug.h.
References m_actions.
Referenced by ResumeActionListStopsAllThreads().
IsEmpty()
bool lldb_private::ResumeActionList::IsEmpty () const inline
Definition at line 50 of file Debug.h.
References m_actions.
NumActionsWithState()
size_t lldb_private::ResumeActionList::NumActionsWithState (lldb::StateType state) const inline
Definition at line 86 of file Debug.h.
References m_actions.
SetDefaultThreadActionIfNeeded()
bool lldb_private::ResumeActionList::SetDefaultThreadActionIfNeeded (lldb::StateType action, int signal) inline
Definition at line 96 of file Debug.h.
References GetActionForThread(), LLDB_INVALID_THREAD_ID, m_actions, and m_signal_handled.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_s(), and ResumeActionList().
SetSignalHandledForThread()
void lldb_private::ResumeActionList::SetSignalHandledForThread (lldb::tid_t tid) const inline
Definition at line 107 of file Debug.h.
References LLDB_INVALID_THREAD_ID, m_actions, and m_signal_handled.
Member Data Documentation
m_actions
std::vector<ResumeAction> lldb_private::ResumeActionList::m_actions protected
Definition at line 127 of file Debug.h.
Referenced by Append(), Clear(), GetActionForThread(), GetFirst(), GetSize(), IsEmpty(), NumActionsWithState(), ResumeActionList(), SetDefaultThreadActionIfNeeded(), and SetSignalHandledForThread().
m_signal_handled
std::vector<bool> lldb_private::ResumeActionList::m_signal_handled mutable protected
Definition at line 128 of file Debug.h.
Referenced by Append(), Clear(), ResumeActionList(), SetDefaultThreadActionIfNeeded(), and SetSignalHandledForThread().
The documentation for this class was generated from the following file:
Debug.h