LLDB: lldb_private::LineTable::Sequence Class Reference
lldb_private::LineTable::Sequence Class Reference
#include <LineTable.h>
Public Member Functions
Sequence ()=default
Sequence (Sequence &&rhs)
Sequence & operator= (Sequence &&rhs)
Sequence (const Sequence &)=delete
Sequence & operator= (const Sequence &)=delete
Private Attributes
std::vector< Entry > m_entries
Friends
class LineTable
Detailed Description
Definition at line 290 of file LineTable.h.
Constructor & Destructor Documentation
Sequence() [1/3]
lldb_private::LineTable::Sequence::Sequence () default
Referenced by operator=(), operator=(), Sequence(), and Sequence().
Sequence() [2/3]
lldb_private::LineTable::Sequence::Sequence (Sequence && rhs) inline
Definition at line 296 of file LineTable.h.
References m_entries, and Sequence().
Sequence() [3/3]
lldb_private::LineTable::Sequence::Sequence (const Sequence &) delete
References Sequence().
Member Function Documentation
operator=() [1/2]
Sequence & lldb_private::LineTable::Sequence::operator= (const Sequence &) delete
References Sequence().
operator=() [2/2]
Sequence & lldb_private::LineTable::Sequence::operator= (Sequence && rhs) inline
Definition at line 297 of file LineTable.h.
References m_entries, and Sequence().
Friends And Related Symbol Documentation
LineTable
friend class LineTable friend
Definition at line 306 of file LineTable.h.
References LineTable.
Referenced by LineTable.
Member Data Documentation
m_entries
std::vector<Entry> lldb_private::LineTable::Sequence::m_entries private
Definition at line 305 of file LineTable.h.
Referenced by lldb_private::LineTable::AppendLineEntryToSequence(), lldb_private::LineTable::InsertSequence(), lldb_private::LineTable::LinkLineTable(), lldb_private::LineTable::LessThanBinaryPredicate::operator()(), operator=(), and Sequence().
The documentation for this class was generated from the following file:
LineTable.h