LLDB: lldb_private::ThreadLauncher Class Reference
lldb_private::ThreadLauncher Class Reference
#include <ThreadLauncher.h>
Classes
struct HostThreadCreateInfo
Static Public Member Functions
static llvm::Expected< HostThread > LaunchThread (llvm::StringRef name, std::function< lldb::thread_result_t()> thread_function, size_t min_stack_byte_size=0)
Detailed Description
Definition at line 20 of file ThreadLauncher.h.
Member Function Documentation
LaunchThread()
llvm::Expected< HostThread > ThreadLauncher::LaunchThread (llvm::StringRef name, std::function< lldb::thread_result_t()> thread_function, size_t min_stack_byte_size = 0) static
Definition at line 25 of file ThreadLauncher.cpp.
References LLDB_INVALID_HOST_THREAD, and lldb_private::HostNativeThreadBase::ThreadCreateTrampoline().
Referenced by lldb_private::DebuggerThread::DebugAttach(), lldb_private::DebuggerThread::DebugLaunch(), lldb_private::process_gdb_remote::ProcessGDBRemote::StartAsyncThread(), ProcessKDP::StartAsyncThread(), lldb_private::Debugger::StartEventHandlerThread(), lldb_private::Debugger::StartIOHandlerThread(), lldb_private::HostProcessWindows::StartMonitoring(), lldb_private::Host::StartMonitoringChildProcess(), lldb_private::ThreadedCommunication::StartReadThread(), and lldb_private::Process::PrivateStateThread::StartupThread().
The documentation for this class was generated from the following files:
ThreadLauncher.h
ThreadLauncher.cpp