LLDB: lldb_private::ScriptedPlatformInterface Class Reference
lldb_private::ScriptedPlatformInterface Class Reference abstract
#include <ScriptedPlatformInterface.h>
Public Member Functions
virtual llvm::Expected< StructuredData::GenericSP > CreatePluginObject (llvm::StringRef class_name, ExecutionContext &exe_ctx, StructuredData::DictionarySP args_sp, StructuredData::Generic *script_obj=nullptr)=0
virtual StructuredData::DictionarySP ListProcesses ()
virtual StructuredData::DictionarySP GetProcessInfo (lldb::pid_t)
virtual Status AttachToProcess (lldb::ProcessAttachInfoSP attach_info)
virtual Status LaunchProcess (lldb::ProcessLaunchInfoSP launch_info)
virtual Status KillProcess (lldb::pid_t pid)
Public Member Functions inherited from lldb_private::ScriptedInterface
ScriptedInterface ()=default
virtual ~ScriptedInterface ()=default
StructuredData::GenericSP GetScriptObjectInstance ()
virtual llvm::SmallVector< AbstractMethodRequirement > GetAbstractMethodRequirements () const =0
virtual llvm::Expected< FileSpec > GetScriptedModulePath ()
llvm::SmallVector< llvm::StringLiteral > const GetAbstractMethods () const
Additional Inherited Members
Static Public Member Functions inherited from lldb_private::ScriptedInterface
template<typename Ret>
static Ret ErrorWithMessage (llvm::StringRef caller_name, llvm::StringRef error_msg, Status &error, LLDBLog log_category=LLDBLog::Process)
template<typename T = StructuredData::ObjectSP>
static bool CheckStructuredDataObject (llvm::StringRef caller, T obj, Status &error)
static bool CreateInstance (lldb::ScriptLanguage language, ScriptedInterfaceUsages usages)
Protected Attributes inherited from lldb_private::ScriptedInterface
StructuredData::GenericSP m_object_instance_sp
Detailed Description
Definition at line 20 of file ScriptedPlatformInterface.h.
Member Function Documentation
AttachToProcess()
virtual Status lldb_private::ScriptedPlatformInterface::AttachToProcess (lldb::ProcessAttachInfoSP attach_info) inline virtual
Reimplemented in lldb_private::ScriptedPlatformPythonInterface.
Definition at line 33 of file ScriptedPlatformInterface.h.
References lldb_private::Status::FromErrorString().
CreatePluginObject()
virtual llvm::Expected< StructuredData::GenericSP > lldb_private::ScriptedPlatformInterface::CreatePluginObject (llvm::StringRef class_name, ExecutionContext & exe_ctx, StructuredData::DictionarySP args_sp, StructuredData::Generic * script_obj = nullptr) pure virtual
Implemented in lldb_private::ScriptedPlatformPythonInterface.
GetProcessInfo()
virtual StructuredData::DictionarySP lldb_private::ScriptedPlatformInterface::GetProcessInfo (lldb::pid_t) inline virtual
Reimplemented in lldb_private::ScriptedPlatformPythonInterface.
Definition at line 29 of file ScriptedPlatformInterface.h.
KillProcess()
virtual Status lldb_private::ScriptedPlatformInterface::KillProcess (lldb::pid_t pid) inline virtual
Reimplemented in lldb_private::ScriptedPlatformPythonInterface.
Definition at line 43 of file ScriptedPlatformInterface.h.
References lldb_private::Status::FromErrorString().
LaunchProcess()
virtual Status lldb_private::ScriptedPlatformInterface::LaunchProcess (lldb::ProcessLaunchInfoSP launch_info) inline virtual
Reimplemented in lldb_private::ScriptedPlatformPythonInterface.
Definition at line 38 of file ScriptedPlatformInterface.h.
References lldb_private::Status::FromErrorString().
ListProcesses()
virtual StructuredData::DictionarySP lldb_private::ScriptedPlatformInterface::ListProcesses () inline virtual
Reimplemented in lldb_private::ScriptedPlatformPythonInterface.
Definition at line 27 of file ScriptedPlatformInterface.h.
The documentation for this class was generated from the following file:
ScriptedPlatformInterface.h