LLDB: ABISysV_mips Class Reference
ABISysV_mips Class Reference
#include <ABISysV_mips.h>
Public Member Functions
~ABISysV_mips () override=default
size_t GetRedZoneSize () const override
bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override
bool GetArgumentValues (lldb_private::Thread &thread, lldb_private::ValueList &values) const override
lldb_private::Status SetReturnValueObject (lldb::StackFrameSP &frame_sp, lldb::ValueObjectSP &new_value) override
lldb::ValueObjectSP GetReturnValueObjectImpl (lldb_private::Thread &thread, lldb_private::CompilerType &type) const override
lldb::UnwindPlanSP CreateFunctionEntryUnwindPlan () override
lldb::UnwindPlanSP CreateDefaultUnwindPlan () override
bool RegisterIsVolatile (const lldb_private::RegisterInfo *reg_info) override
bool IsSoftFloat (uint32_t fp_flag) const
bool CallFrameAddressIsValid (lldb::addr_t cfa) override
bool CodeAddressIsValid (lldb::addr_t pc) override
const lldb_private::RegisterInfo * GetRegisterInfoArray (uint32_t &count) override
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::RegInfoBasedABI
void AugmentRegisterInfo (std::vector< DynamicRegisterInfo::Register > &regs) override
Public Member Functions inherited from lldb_private::ABI
~ABI () override
virtual bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::Type &prototype, llvm::ArrayRef< CallArgument > args) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, CompilerType &type, bool persistent=true) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, llvm::Type &type, bool persistent=true) const
virtual bool GetFallbackRegisterLocation (const RegisterInfo *reg_info, UnwindPlan::Row::AbstractRegisterLocation &unwind_regloc)
virtual lldb::addr_t FixAnyAddress (lldb::addr_t pc)
Use this method when you do not know, or do not care what kind of address you are fixing.
llvm::MCRegisterInfo & GetMCRegisterInfo ()
virtual bool GetPointerReturnRegister (const char *&name)
virtual uint64_t GetStackFrameSize ()
virtual lldb::addr_t FixCodeAddress (lldb::addr_t pc)
Some targets might use bits in a code address to indicate a mode switch.
virtual lldb::addr_t FixDataAddress (lldb::addr_t pc)
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static lldb::ABISP CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec &arch)
static llvm::StringRef GetPluginNameStatic ()
Static Public Member Functions inherited from lldb_private::ABI
static lldb::ABISP FindPlugin (lldb::ProcessSP process_sp, const ArchSpec &arch)
Protected Member Functions
void CreateRegisterMapIfNeeded ()
lldb::ValueObjectSP GetReturnValueObjectSimple (lldb_private::Thread &thread, lldb_private::CompilerType &ast_type) const
bool RegisterIsCalleeSaved (const lldb_private::RegisterInfo *reg_info)
Protected Member Functions inherited from lldb_private::RegInfoBasedABI
bool GetRegisterInfoByName (llvm::StringRef name, RegisterInfo &info)
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Protected Member Functions inherited from lldb_private::ABI
virtual lldb::ValueObjectSP GetReturnValueObjectImpl (Thread &thread, llvm::Type &ir_type) const
lldb::ProcessSP GetProcessSP () const
Request to get a Process shared pointer.
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Additional Inherited Members
Static Protected Member Functions inherited from lldb_private::ABI
static std::unique_ptr< llvm::MCRegisterInfo > MakeMCRegisterInfo (const ArchSpec &arch)
Utility function to construct a MCRegisterInfo using the ArchSpec triple.
Protected Attributes inherited from lldb_private::ABI
lldb::ProcessWP m_process_wp
std::unique_ptr< llvm::MCRegisterInfo > m_mc_register_info_up
Detailed Description
Definition at line 15 of file ABISysV_mips.h.
Constructor & Destructor Documentation
~ABISysV_mips()
ABISysV_mips::~ABISysV_mips () override default
References sp.
Member Function Documentation
CallFrameAddressIsValid()
bool ABISysV_mips::CallFrameAddressIsValid (lldb::addr_t cfa) inline override virtual
Implements lldb_private::ABI.
Definition at line 45 of file ABISysV_mips.h.
CodeAddressIsValid()
bool ABISysV_mips::CodeAddressIsValid (lldb::addr_t pc) inline override virtual
Implements lldb_private::ABI.
Definition at line 54 of file ABISysV_mips.h.
References pc, and UINT32_MAX.
CreateDefaultUnwindPlan()
UnwindPlanSP ABISysV_mips::CreateDefaultUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 957 of file ABISysV_mips.cpp.
References dwarf_pc, dwarf_r29, dwarf_r31, lldb_private::eLazyBoolNo, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), lldb_private::UnwindPlan::Row::SetRegisterLocationToRegister(), and lldb_private::UnwindPlan::Row::SetUnspecifiedRegistersAreUndefined().
CreateFunctionEntryUnwindPlan()
UnwindPlanSP ABISysV_mips::CreateFunctionEntryUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 940 of file ABISysV_mips.cpp.
References dwarf_pc, dwarf_r29, dwarf_r31, lldb_private::eLazyBoolNo, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), and lldb_private::UnwindPlan::Row::SetRegisterLocationToRegister().
CreateInstance()
ABISP ABISysV_mips::CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec & arch) static
Definition at line 552 of file ABISysV_mips.cpp.
References lldb_private::ArchSpec::GetTriple(), and lldb_private::ABI::MakeMCRegisterInfo().
Referenced by Initialize(), and Terminate().
CreateRegisterMapIfNeeded()
void ABISysV_mips::CreateRegisterMapIfNeeded () protected
GetArgumentValues()
bool ABISysV_mips::GetArgumentValues (lldb_private::Thread & thread, lldb_private::ValueList & values) const override virtual
Implements lldb_private::ABI.
Definition at line 690 of file ABISysV_mips.cpp.
GetPluginName()
llvm::StringRef ABISysV_mips::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 75 of file ABISysV_mips.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef ABISysV_mips::GetPluginNameStatic () inline static
Definition at line 71 of file ABISysV_mips.h.
Referenced by GetPluginName(), and Initialize().
GetRedZoneSize()
size_t ABISysV_mips::GetRedZoneSize () const override virtual
Implements lldb_private::ABI.
Definition at line 547 of file ABISysV_mips.cpp.
GetRegisterInfoArray()
const lldb_private::RegisterInfo * ABISysV_mips::GetRegisterInfoArray (uint32_t & count) override virtual
Implements lldb_private::RegInfoBasedABI.
Definition at line 542 of file ABISysV_mips.cpp.
References g_register_infos, and k_num_register_infos.
GetReturnValueObjectImpl()
ValueObjectSP ABISysV_mips::GetReturnValueObjectImpl (lldb_private::Thread & thread, lldb_private::CompilerType & type) const override virtual
Implements lldb_private::ABI.
Definition at line 766 of file ABISysV_mips.cpp.
References lldb_private::DataExtractor::CopyByteOrderedData(), lldb_private::ValueObjectConstResult::Create(), lldb_private::ValueObjectMemory::Create(), lldb::eByteOrderLittle, lldb_private::ArchSpec::eMIPS_ABI_FP_mask, lldb_private::ArchSpec::GetAddressByteSize(), lldb_private::Target::GetArchitecture(), lldb_private::CompilerType::GetBitSize(), lldb_private::ArchSpec::GetByteOrder(), lldb_private::RegisterValue::GetData(), lldb_private::DataExtractor::GetDouble(), lldb_private::ArchSpec::GetFlags(), lldb_private::DataExtractor::GetFloat(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::Value::GetScalar(), lldb_private::ExecutionContext::GetTargetPtr(), lldb_private::CompilerType::IsAggregateType(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), lldb_private::CompilerType::IsPointerType(), lldb_private::CompilerType::IsRealFloatingPointType(), IsSoftFloat(), lldb_private::RegisterContext::ReadRegister(), lldb_private::RegisterContext::ReadRegisterAsUnsigned(), lldb_private::Value::SetCompilerType(), and UINT32_MAX.
GetReturnValueObjectSimple()
ValueObjectSP ABISysV_mips::GetReturnValueObjectSimple (lldb_private::Thread & thread, lldb_private::CompilerType & ast_type) const protected
Definition at line 760 of file ABISysV_mips.cpp.
Initialize()
void ABISysV_mips::Initialize () static
Definition at line 1020 of file ABISysV_mips.cpp.
References CreateInstance(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Referenced by ABIMips::Initialize().
IsSoftFloat()
bool ABISysV_mips::IsSoftFloat (uint32_t fp_flag) const
Definition at line 978 of file ABISysV_mips.cpp.
References lldb_private::ArchSpec::eMIPS_ABI_FP_SOFT.
Referenced by GetReturnValueObjectImpl().
PrepareTrivialCall()
bool ABISysV_mips::PrepareTrivialCall (lldb_private::Thread & thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override virtual
Implements lldb_private::ABI.
Definition at line 562 of file ABISysV_mips.cpp.
References lldb_private::RegisterInfo::byte_size, lldb::eRegisterKindGeneric, error(), lldb_private::Expressions, lldb_private::GetLog(), lldb_private::RegisterContext::GetRegisterInfo(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::StreamString::GetString(), LLDB_LOGF, LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_RA, LLDB_REGNUM_GENERIC_SP, lldb_private::RegisterInfo::name, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), lldb_private::Log::PutString(), lldb_private::RegisterValue::SetUInt32(), sp, and lldb_private::RegisterContext::WriteRegisterFromUnsigned().
RegisterIsCalleeSaved()
bool ABISysV_mips::RegisterIsCalleeSaved (const lldb_private::RegisterInfo * reg_info) protected
Definition at line 982 of file ABISysV_mips.cpp.
References lldb_private::RegisterInfo::name.
Referenced by RegisterIsVolatile().
RegisterIsVolatile()
bool ABISysV_mips::RegisterIsVolatile (const lldb_private::RegisterInfo * reg_info) override virtual
Implements lldb_private::ABI.
Definition at line 974 of file ABISysV_mips.cpp.
References RegisterIsCalleeSaved().
SetReturnValueObject()
Status ABISysV_mips::SetReturnValueObject (lldb::StackFrameSP & frame_sp, lldb::ValueObjectSP & new_value) override virtual
Implements lldb_private::ABI.
Definition at line 694 of file ABISysV_mips.cpp.
References lldb_private::Status::AsCString(), error(), lldb_private::Status::Fail(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataExtractor::GetMaxU32(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), lldb_private::CompilerType::IsPointerType(), and lldb_private::RegisterContext::WriteRegisterFromUnsigned().
Terminate()
void ABISysV_mips::Terminate () static
Definition at line 1025 of file ABISysV_mips.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Referenced by ABIMips::Terminate().
The documentation for this class was generated from the following files:
ABISysV_mips.h
ABISysV_mips.cpp