LLDB: lldb_private::DebugMacros Class Reference
lldb_private::DebugMacros Class Reference
#include <DebugMacros.h>
Public Member Functions
DebugMacros ()=default
~DebugMacros ()=default
void AddMacroEntry (const DebugMacroEntry &entry)
size_t GetNumMacroEntries () const
DebugMacroEntry GetMacroEntryAtIndex (const size_t index) const
Private Member Functions
DebugMacros (const DebugMacros &)=delete
const DebugMacros & operator= (const DebugMacros &)=delete
Private Attributes
std::vector< DebugMacroEntry > m_macro_entries
Detailed Description
Definition at line 71 of file DebugMacros.h.
Constructor & Destructor Documentation
DebugMacros() [1/2]
lldb_private::DebugMacros::DebugMacros () default
Referenced by DebugMacros(), and operator=().
~DebugMacros()
lldb_private::DebugMacros::~DebugMacros () default
DebugMacros() [2/2]
lldb_private::DebugMacros::DebugMacros (const DebugMacros &) private delete
References DebugMacros().
Member Function Documentation
AddMacroEntry()
void lldb_private::DebugMacros::AddMacroEntry (const DebugMacroEntry & entry) inline
Definition at line 77 of file DebugMacros.h.
References m_macro_entries.
GetMacroEntryAtIndex()
DebugMacroEntry lldb_private::DebugMacros::GetMacroEntryAtIndex (const size_t index) const inline
Definition at line 83 of file DebugMacros.h.
References m_macro_entries.
Referenced by AddMacros().
GetNumMacroEntries()
size_t lldb_private::DebugMacros::GetNumMacroEntries () const inline
Definition at line 81 of file DebugMacros.h.
References m_macro_entries.
Referenced by AddMacros().
operator=()
const DebugMacros & lldb_private::DebugMacros::operator= (const DebugMacros &) private delete
References DebugMacros().
Member Data Documentation
m_macro_entries
std::vector<DebugMacroEntry> lldb_private::DebugMacros::m_macro_entries private
Definition at line 94 of file DebugMacros.h.
Referenced by AddMacroEntry(), GetMacroEntryAtIndex(), and GetNumMacroEntries().
The documentation for this class was generated from the following file:
DebugMacros.h