LLDB: lldb_private::plugin::dwarf::DWARFDeclContext Class Reference
lldb_private::plugin::dwarf::DWARFDeclContext Class Reference
#include <DWARFDeclContext.h>
Classes
struct Entry
Public Member Functions
DWARFDeclContext ()
DWARFDeclContext (llvm::ArrayRef< Entry > entries)
void AppendDeclContext (dw_tag_t tag, const char *name)
bool operator== (const DWARFDeclContext &rhs) const
bool operator!= (const DWARFDeclContext &rhs) const
uint32_t GetSize () const
Entry & operator[] (uint32_t idx)
const Entry & operator[] (uint32_t idx) const
const char * GetQualifiedName () const
ConstString GetQualifiedNameAsConstString () const
void Clear ()
Protected Types
typedef std::vector< Entry > collection
Protected Attributes
collection m_entries
std::string m_qualified_name
Friends
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const DWARFDeclContext &ctx)
Detailed Description
Definition at line 28 of file DWARFDeclContext.h.
Member Typedef Documentation
collection
typedef std::vector<Entry> lldb_private::plugin::dwarf::DWARFDeclContext::collection protected
Definition at line 103 of file DWARFDeclContext.h.
Constructor & Destructor Documentation
DWARFDeclContext() [1/2]
lldb_private::plugin::dwarf::DWARFDeclContext::DWARFDeclContext () inline
Definition at line 53 of file DWARFDeclContext.h.
References m_entries.
Referenced by operator!=(), operator<<, and operator==().
DWARFDeclContext() [2/2]
lldb_private::plugin::dwarf::DWARFDeclContext::DWARFDeclContext (llvm::ArrayRef< Entry > entries) inline
Definition at line 55 of file DWARFDeclContext.h.
References m_entries.
Member Function Documentation
AppendDeclContext()
void lldb_private::plugin::dwarf::DWARFDeclContext::AppendDeclContext (dw_tag_t tag, const char * name) inline
Definition at line 59 of file DWARFDeclContext.h.
References m_entries.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::FindDefinitionDIE(), and GetDWARFDeclContextImpl().
Clear()
void lldb_private::plugin::dwarf::DWARFDeclContext::Clear () inline
Definition at line 86 of file DWARFDeclContext.h.
References m_entries, and m_qualified_name.
GetQualifiedName()
const char * DWARFDeclContext::GetQualifiedName () const
Definition at line 29 of file DWARFDeclContext.cpp.
References m_entries, and m_qualified_name.
Referenced by DWARFASTParserClang::ConstructDemangledNameFromDWARF(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindDefinitionDIE(), GetQualifiedNameAsConstString(), and lldb_private::plugin::dwarf::AppleDWARFIndex::GetTypes().
GetQualifiedNameAsConstString()
ConstString lldb_private::plugin::dwarf::DWARFDeclContext::GetQualifiedNameAsConstString () const inline
Definition at line 82 of file DWARFDeclContext.h.
References GetQualifiedName().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE().
GetSize()
uint32_t lldb_private::plugin::dwarf::DWARFDeclContext::GetSize () const inline
Definition at line 66 of file DWARFDeclContext.h.
References m_entries.
Referenced by lldb_private::plugin::dwarf::DebugNamesDWARFIndex::GetFullyQualifiedType(), and lldb_private::plugin::dwarf::AppleDWARFIndex::GetTypes().
operator!=()
bool lldb_private::plugin::dwarf::DWARFDeclContext::operator!= (const DWARFDeclContext & rhs) const inline
Definition at line 64 of file DWARFDeclContext.h.
References DWARFDeclContext().
operator==()
bool DWARFDeclContext::operator== (const DWARFDeclContext & rhs) const
Definition at line 56 of file DWARFDeclContext.cpp.
References DWARFDeclContext(), and m_entries.
operator[]() [1/2]
Entry & lldb_private::plugin::dwarf::DWARFDeclContext::operator[] (uint32_t idx) inline
Definition at line 68 of file DWARFDeclContext.h.
References m_entries.
operator[]() [2/2]
const Entry & lldb_private::plugin::dwarf::DWARFDeclContext::operator[] (uint32_t idx) const inline
Definition at line 73 of file DWARFDeclContext.h.
References m_entries.
Friends And Related Symbol Documentation
operator<<
llvm::raw_ostream & operator<< (llvm::raw_ostream & OS, const DWARFDeclContext & ctx) friend
Definition at line 91 of file DWARFDeclContext.h.
References lldb_private::plugin::dwarf::DW_TAG_value_to_name(), DWARFDeclContext(), lldb_private::plugin::dwarf::DWARFDeclContext::Entry::GetName(), m_entries, lldb_private::OS, and lldb_private::plugin::dwarf::DWARFDeclContext::Entry::tag.
Member Data Documentation
m_entries
collection lldb_private::plugin::dwarf::DWARFDeclContext::m_entries protected
Definition at line 104 of file DWARFDeclContext.h.
Referenced by AppendDeclContext(), Clear(), DWARFDeclContext(), DWARFDeclContext(), GetQualifiedName(), GetSize(), operator<<, operator==(), operator[](), and operator[]().
m_qualified_name
std::string lldb_private::plugin::dwarf::DWARFDeclContext::m_qualified_name mutable protected
Definition at line 105 of file DWARFDeclContext.h.
Referenced by Clear(), and GetQualifiedName().
The documentation for this class was generated from the following files:
DWARFDeclContext.h
DWARFDeclContext.cpp