LLDB: lldb_private::MemoryMonitor Class Reference
lldb_private::MemoryMonitor Class Reference abstract
#include <MemoryMonitor.h>
Public Types
using Callback = std::function<void()>
Public Member Functions
MemoryMonitor (Callback callback)
virtual ~MemoryMonitor ()=default
virtual void Start ()=0
virtual void Stop ()=0
MemoryMonitor (const MemoryMonitor &)=delete
MemoryMonitor is not copyable.
MemoryMonitor & operator= (const MemoryMonitor &)=delete
Static Public Member Functions
static std::unique_ptr< MemoryMonitor > Create (Callback callback)
Protected Attributes
Callback m_callback
Detailed Description
Definition at line 18 of file MemoryMonitor.h.
Member Typedef Documentation
Callback
using lldb_private::MemoryMonitor::Callback = std::function<void()>
Definition at line 20 of file MemoryMonitor.h.
Constructor & Destructor Documentation
MemoryMonitor() [1/2]
lldb_private::MemoryMonitor::MemoryMonitor (Callback callback) inline
Definition at line 22 of file MemoryMonitor.h.
References m_callback.
Referenced by MemoryMonitor(), and operator=().
~MemoryMonitor()
virtual lldb_private::MemoryMonitor::~MemoryMonitor () virtual default
MemoryMonitor() [2/2]
lldb_private::MemoryMonitor::MemoryMonitor (const MemoryMonitor &) delete
MemoryMonitor is not copyable.
References MemoryMonitor().
Member Function Documentation
Create()
std::unique_ptr< MemoryMonitor > MemoryMonitor::Create (Callback callback) static
Definition at line 216 of file MemoryMonitor.cpp.
operator=()
MemoryMonitor & lldb_private::MemoryMonitor::operator= (const MemoryMonitor &) delete
References MemoryMonitor().
Start()
virtual void lldb_private::MemoryMonitor::Start () pure virtual
Implemented in MemoryMonitorMacOSX.
Stop()
virtual void lldb_private::MemoryMonitor::Stop () pure virtual
Implemented in MemoryMonitorMacOSX.
Member Data Documentation
m_callback
Callback lldb_private::MemoryMonitor::m_callback protected
Definition at line 37 of file MemoryMonitor.h.
Referenced by MemoryMonitor(), and MemoryMonitorMacOSX::Start().
The documentation for this class was generated from the following files:
MemoryMonitor.h
MemoryMonitor.cpp
MemoryMonitorMacOSX.mm