LLDB: lldb_private::Target::StopHookCommandLine Class Reference
lldb_private::Target::StopHookCommandLine Class Reference
#include <Target.h>
Public Member Functions
~StopHookCommandLine () override=default
StringList & GetCommands ()
void SetActionFromString (const std::string &strings)
void SetActionFromStrings (const std::vector< std::string > &strings)
StopHookResult HandleStop (ExecutionContext &exc_ctx, lldb::StreamSP output_sp) override
void GetSubclassDescription (Stream &s, lldb::DescriptionLevel level) const override
Public Member Functions inherited from lldb_private::Target::StopHook
StopHook (const StopHook &rhs)
virtual ~StopHook ()=default
lldb::TargetSP & GetTarget ()
void SetSpecifier (SymbolContextSpecifier *specifier)
SymbolContextSpecifier * GetSpecifier ()
bool ExecutionContextPasses (const ExecutionContext &exe_ctx)
void SetThreadSpecifier (ThreadSpec *specifier)
ThreadSpec * GetThreadSpecifier ()
bool IsActive ()
void SetIsActive (bool is_active)
void SetAutoContinue (bool auto_continue)
bool GetAutoContinue () const
void SetRunAtInitialStop (bool at_initial_stop)
bool GetRunAtInitialStop () const
void SetSuppressOutput (bool suppress_output)
bool GetSuppressOutput () const
void GetDescription (Stream &s, lldb::DescriptionLevel level) const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Private Member Functions
StopHookCommandLine (lldb::TargetSP target_sp, lldb::user_id_t uid)
Private Attributes
StringList m_commands
Friends
class Target
Additional Inherited Members
Public Types inherited from lldb_private::Target::StopHook
enum class StopHookKind : uint32_t { CommandBased = 0 , ScriptBased , CodeBased }
enum class StopHookResult : uint32_t { KeepStopped = 0 , RequestContinue , NoPreference , AlreadyContinued }
Protected Member Functions inherited from lldb_private::Target::StopHook
StopHook (lldb::TargetSP target_sp, lldb::user_id_t uid)
Protected Attributes inherited from lldb_private::Target::StopHook
lldb::TargetSP m_target_sp
lldb::SymbolContextSpecifierSP m_specifier_sp
std::unique_ptr< ThreadSpec > m_thread_spec_up
bool m_active = true
bool m_auto_continue = false
bool m_at_initial_stop = true
bool m_suppress_output = false
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Detailed Description
Definition at line 1555 of file Target.h.
Constructor & Destructor Documentation
~StopHookCommandLine()
lldb_private::Target::StopHookCommandLine::~StopHookCommandLine () override default
StopHookCommandLine()
lldb_private::Target::StopHookCommandLine::StopHookCommandLine (lldb::TargetSP target_sp, lldb::user_id_t uid) inline private
Definition at line 1573 of file Target.h.
References lldb_private::Target::StopHook::StopHook().
Member Function Documentation
GetCommands()
StringList & lldb_private::Target::StopHookCommandLine::GetCommands () inline
Definition at line 1559 of file Target.h.
References m_commands.
Referenced by HandleStop(), SetActionFromString(), and SetActionFromStrings().
GetSubclassDescription()
void Target::StopHookCommandLine::GetSubclassDescription (Stream & s, lldb::DescriptionLevel level) const override virtual
Implements lldb_private::Target::StopHook.
Definition at line 4070 of file Target.cpp.
References lldb::eDescriptionLevelBrief, lldb_private::Stream::Indent(), m_commands, lldb_private::Stream::MakeIndentScope(), and lldb_private::Stream::PutCString().
HandleStop()
Target::StopHook::StopHookResult Target::StopHookCommandLine::HandleStop (ExecutionContext & exc_ctx, lldb::StreamSP output_sp) override virtual
Implements lldb_private::Target::StopHook.
Definition at line 4099 of file Target.cpp.
References lldb_private::Target::StopHook::AlreadyContinued, lldb_private::Target::Debugger, lldb::eReturnStatusSuccessContinuingNoResult, lldb::eReturnStatusSuccessContinuingResult, lldb_private::Debugger::GetAsyncExecution(), lldb_private::Debugger::GetCommandInterpreter(), GetCommands(), lldb_private::Target::GetDebugger(), lldb_private::CommandReturnObject::GetStatus(), lldb_private::ExecutionContext::GetTargetPtr(), lldb_private::CommandInterpreter::HandleCommands(), lldb_private::Target::StopHook::KeepStopped, m_commands, lldb_private::CommandInterpreterRunOptions::SetAddToHistory(), lldb_private::Debugger::SetAsyncExecution(), lldb_private::CommandInterpreterRunOptions::SetEchoCommands(), lldb_private::CommandReturnObject::SetImmediateOutputStream(), lldb_private::CommandReturnObject::SetInteractive(), lldb_private::CommandInterpreterRunOptions::SetPrintErrors(), lldb_private::CommandInterpreterRunOptions::SetPrintResults(), lldb_private::CommandInterpreterRunOptions::SetStopOnContinue(), and lldb_private::CommandInterpreterRunOptions::SetStopOnError().
SetActionFromString()
void Target::StopHookCommandLine::SetActionFromString (const std::string & strings)
Definition at line 4088 of file Target.cpp.
References GetCommands().
SetActionFromStrings()
void Target::StopHookCommandLine::SetActionFromStrings (const std::vector< std::string > & strings)
Definition at line 4092 of file Target.cpp.
References GetCommands().
Friends And Related Symbol Documentation
Target
friend class Target friend
Definition at line 1575 of file Target.h.
References Target.
Referenced by Target.
Member Data Documentation
m_commands
StringList lldb_private::Target::StopHookCommandLine::m_commands private
Definition at line 1569 of file Target.h.
Referenced by GetCommands(), GetSubclassDescription(), and HandleStop().
The documentation for this class was generated from the following files:
Target.h
Target.cpp