LLDB: lldb_private::StopInfoWatchpoint::ThreadPlanStepOverWatchpoint Class Reference
lldb_private::StopInfoWatchpoint::ThreadPlanStepOverWatchpoint Class Reference
Public Member Functions
ThreadPlanStepOverWatchpoint (Thread &thread, StopInfoWatchpointSP stop_info_sp, WatchpointSP watch_sp)
bool DoWillResume (lldb::StateType resume_state, bool current_plan) override
bool DoPlanExplainsStop (Event *event_ptr) override
void DidPop () override
bool ShouldStop (Event *event_ptr) override
bool ShouldRunBeforePublicStop () override
Public Member Functions inherited from lldb_private::ThreadPlanStepInstruction
ThreadPlanStepInstruction (Thread &thread, bool step_over, bool stop_others, Vote report_stop_vote, Vote report_run_vote)
~ThreadPlanStepInstruction () override
void GetDescription (Stream *s, lldb::DescriptionLevel level) override
Print a description of this thread to the stream s.
bool ValidatePlan (Stream *error) override
Returns whether this plan could be successfully created.
bool StopOthers () override
lldb::StateType GetPlanRunState () override
bool WillStop () override
bool MischiefManaged () override
bool IsPlanStale () override
Public Member Functions inherited from lldb_private::ThreadPlan
virtual ~ThreadPlan ()
const char * GetName () const
Returns the name of this thread plan.
Thread & GetThread ()
Returns the Thread that is using this thread plan.
Target & GetTarget ()
const Target & GetTarget () const
void ClearThreadCache ()
Clear the Thread* cache.
bool TracerExplainsStop ()
lldb::StateType RunState ()
bool PlanExplainsStop (Event *event_ptr)
virtual bool ShouldAutoContinue (Event *event_ptr)
Returns whether this thread plan overrides the ShouldStop of subsequently processed plans.
virtual Vote ShouldReportStop (Event *event_ptr)
Vote ShouldReportRun (Event *event_ptr)
virtual void SetStopOthers (bool new_value)
virtual bool SupportsResumeOthers ()
bool WillResume (lldb::StateType resume_state, bool current_plan)
bool IsControllingPlan ()
virtual bool IsLeafPlan ()
bool SetIsControllingPlan (bool value)
virtual bool OkayToDiscard ()
void SetOkayToDiscard (bool value)
virtual void ThreadDestroyed ()
bool GetPrivate ()
void SetPrivate (bool input)
virtual void DidPush ()
ThreadPlanKind GetKind () const
bool IsPlanComplete ()
void SetPlanComplete (bool success=true)
bool PlanSucceeded ()
virtual bool IsBasePlan ()
lldb::ThreadPlanTracerSP & GetThreadPlanTracer ()
void SetThreadPlanTracer (lldb::ThreadPlanTracerSP new_tracer_sp)
void DoTraceLog ()
virtual lldb::ValueObjectSP GetReturnValueObject ()
virtual lldb::ExpressionVariableSP GetExpressionVariable ()
virtual void RestoreThreadState ()
virtual bool IsVirtualStep ()
bool SetIterationCount (size_t count)
virtual lldb::RunDirection GetDirection () const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Protected Member Functions
void ResetWatchpoint ()
Protected Member Functions inherited from lldb_private::ThreadPlanStepInstruction
void SetUpState ()
Protected Member Functions inherited from lldb_private::ThreadPlan
ThreadPlan (ThreadPlanKind kind, const char *name, Thread &thread, Vote report_stop_vote, Vote report_run_vote)
void PushPlan (lldb::ThreadPlanSP &thread_plan_sp)
ThreadPlan * GetPreviousPlan ()
lldb::StopInfoSP GetPrivateStopInfo ()
void SetStopInfo (lldb::StopInfoSP stop_reason_sp)
bool IsUsuallyUnexplainedStopReason (lldb::StopReason)
Private Attributes
StopInfoWatchpointSP m_stop_info_sp
WatchpointSP m_watch_sp
bool m_did_disable_wp = false
Additional Inherited Members
Public Types inherited from lldb_private::ThreadPlan
enum ThreadPlanKind {
eKindGeneric , eKindNull , eKindBase , eKindCallFunction ,
eKindPython , eKindStepInstruction , eKindStepOut , eKindStepOverBreakpoint ,
eKindStepOverRange , eKindStepInRange , eKindRunToAddress , eKindStepThrough ,
eKindStepUntil , eKindSingleThreadTimeout
}
Protected Attributes inherited from lldb_private::ThreadPlan
Status m_status
Process & m_process
lldb::tid_t m_tid
Vote m_report_stop_vote
Vote m_report_run_vote
bool m_takes_iteration_count
bool m_could_not_resolve_hw_bp
int32_t m_iteration_count = 1
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Detailed Description
Definition at line 793 of file StopInfo.cpp.
Constructor & Destructor Documentation
ThreadPlanStepOverWatchpoint()
lldb_private::StopInfoWatchpoint::ThreadPlanStepOverWatchpoint::ThreadPlanStepOverWatchpoint (Thread & thread, StopInfoWatchpointSP stop_info_sp, WatchpointSP watch_sp) inline
Definition at line 795 of file StopInfo.cpp.
References lldb_private::eVoteNoOpinion, m_stop_info_sp, m_watch_sp, lldb_private::StopInfo::Thread, and lldb_private::ThreadPlanStepInstruction::ThreadPlanStepInstruction().
Member Function Documentation
DidPop()
void lldb_private::StopInfoWatchpoint::ThreadPlanStepOverWatchpoint::DidPop () inline override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 829 of file StopInfo.cpp.
References m_watch_sp.
DoPlanExplainsStop()
bool lldb_private::StopInfoWatchpoint::ThreadPlanStepOverWatchpoint::DoPlanExplainsStop (Event * event_ptr) inline override virtual
Reimplemented from lldb_private::ThreadPlanStepInstruction.
Definition at line 816 of file StopInfo.cpp.
References lldb_private::ThreadPlanStepInstruction::DoPlanExplainsStop(), lldb::eStopReasonWatchpoint, lldb_private::Thread::GetPrivateStopInfo(), and lldb_private::ThreadPlan::GetThread().
DoWillResume()
bool lldb_private::StopInfoWatchpoint::ThreadPlanStepOverWatchpoint::DoWillResume (lldb::StateType resume_state, bool current_plan) inline override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 804 of file StopInfo.cpp.
References lldb::eStateSuspended, lldb_private::Thread::GetProcess(), lldb_private::ThreadPlan::GetThread(), m_did_disable_wp, and m_watch_sp.
ResetWatchpoint()
void lldb_private::StopInfoWatchpoint::ThreadPlanStepOverWatchpoint::ResetWatchpoint () inline protected
Definition at line 850 of file StopInfo.cpp.
References lldb_private::Thread::GetProcess(), lldb_private::ThreadPlan::GetThread(), m_did_disable_wp, and m_watch_sp.
Referenced by ShouldStop().
ShouldRunBeforePublicStop()
bool lldb_private::StopInfoWatchpoint::ThreadPlanStepOverWatchpoint::ShouldRunBeforePublicStop () inline override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 845 of file StopInfo.cpp.
ShouldStop()
bool lldb_private::StopInfoWatchpoint::ThreadPlanStepOverWatchpoint::ShouldStop (Event * event_ptr) inline override virtual
Reimplemented from lldb_private::ThreadPlanStepInstruction.
Definition at line 834 of file StopInfo.cpp.
References lldb_private::ThreadPlan::GetThread(), m_stop_info_sp, lldb_private::ThreadPlanStepInstruction::MischiefManaged(), ResetWatchpoint(), lldb_private::Thread::SetStopInfo(), and lldb_private::ThreadPlanStepInstruction::ShouldStop().
Member Data Documentation
m_did_disable_wp
bool lldb_private::StopInfoWatchpoint::ThreadPlanStepOverWatchpoint::m_did_disable_wp = false private
Definition at line 860 of file StopInfo.cpp.
Referenced by DoWillResume(), and ResetWatchpoint().
m_stop_info_sp
StopInfoWatchpointSP lldb_private::StopInfoWatchpoint::ThreadPlanStepOverWatchpoint::m_stop_info_sp private
Definition at line 858 of file StopInfo.cpp.
Referenced by ShouldStop(), and ThreadPlanStepOverWatchpoint().
m_watch_sp
WatchpointSP lldb_private::StopInfoWatchpoint::ThreadPlanStepOverWatchpoint::m_watch_sp private
Definition at line 859 of file StopInfo.cpp.
Referenced by DidPop(), DoWillResume(), ResetWatchpoint(), and ThreadPlanStepOverWatchpoint().
The documentation for this class was generated from the following file:
StopInfo.cpp