LLDB: CFCData Class Reference
CFCData Class Reference
#include <CFCData.h>
Public Member Functions
CFCData (CFDataRef data=NULL)
CFCData (const CFCData &rhs)
CFCData & operator= (const CFCData &rhs)
~CFCData () override
CFDataRef Serialize (CFPropertyListRef plist, CFPropertyListFormat format)
const uint8_t * GetBytePtr () const
CFIndex GetLength () const
Public Member Functions inherited from CFCReleaser< CFDataRef >
CFCReleaser (CFDataRef ptr=NULL)
virtual ~CFCReleaser ()
CFCReleaser & operator= (const CFCReleaser< CFDataRef > &rhs)
CFDataRef * ptr_address (bool enforce_null=true)
CFDataRef get ()
void reset (CFDataRef ptr=NULL)
CFDataRef release ()
Detailed Description
Definition at line 14 of file CFCData.h.
Constructor & Destructor Documentation
CFCData() [1/2]
CFCData::CFCData (CFDataRef data = NULL)
Definition at line 12 of file CFCData.cpp.
References CFCReleaser< CFDataRef >::CFCReleaser().
Referenced by CFCData(), and operator=().
CFCData() [2/2]
CFCData::CFCData (const CFCData & rhs) default
References CFCData().
~CFCData()
CFCData::~CFCData () override default
Member Function Documentation
GetBytePtr()
const uint8_t * CFCData::GetBytePtr () const
Definition at line 36 of file CFCData.cpp.
References CFCReleaser< CFDataRef >::get().
GetLength()
CFIndex CFCData::GetLength () const
Definition at line 29 of file CFCData.cpp.
References CFCReleaser< CFDataRef >::get().
operator=()
CFCData & CFCData::operator= (const CFCData & rhs)
Definition at line 18 of file CFCData.cpp.
References CFCData().
Serialize()
CFDataRef CFCData::Serialize (CFPropertyListRef plist, CFPropertyListFormat format)
Definition at line 43 of file CFCData.cpp.
References CFCReleaser< CFDataRef >::CFCReleaser(), CFCReleaser< T >::get(), CFCReleaser< CFDataRef >::get(), and CFCReleaser< CFDataRef >::reset().
The documentation for this class was generated from the following files:
CFCData.h
CFCData.cpp