LLDB: lldb_private::OptionValue::DefaultValueFormat Class Reference
lldb_private::OptionValue::DefaultValueFormat Class Reference
#include <OptionValue.h>
Public Member Functions
DefaultValueFormat (Stream &stream)
~DefaultValueFormat ()
DefaultValueFormat (const DefaultValueFormat &)=delete
DefaultValueFormat & operator= (const DefaultValueFormat &)=delete
Private Attributes
Stream & stream
Detailed Description
Definition at line 343 of file OptionValue.h.
Constructor & Destructor Documentation
DefaultValueFormat() [1/2]
lldb_private::OptionValue::DefaultValueFormat::DefaultValueFormat (Stream & stream) inline
Definition at line 345 of file OptionValue.h.
References stream.
Referenced by DefaultValueFormat(), and operator=().
~DefaultValueFormat()
lldb_private::OptionValue::DefaultValueFormat::~DefaultValueFormat () inline
Definition at line 348 of file OptionValue.h.
References stream.
DefaultValueFormat() [2/2]
lldb_private::OptionValue::DefaultValueFormat::DefaultValueFormat (const DefaultValueFormat &) delete
References DefaultValueFormat().
Member Function Documentation
operator=()
DefaultValueFormat & lldb_private::OptionValue::DefaultValueFormat::operator= (const DefaultValueFormat &) delete
References DefaultValueFormat().
Member Data Documentation
stream
Stream& lldb_private::OptionValue::DefaultValueFormat::stream private
Definition at line 354 of file OptionValue.h.
Referenced by DefaultValueFormat(), and ~DefaultValueFormat().
The documentation for this class was generated from the following file:
OptionValue.h