LLDB: lldb_private::OptionValueUInt64 Class Reference
lldb_private::OptionValueUInt64 Class Reference
#include <OptionValueUInt64.h>
Public Member Functions
OptionValueUInt64 ()=default
OptionValueUInt64 (uint64_t value)
OptionValueUInt64 (uint64_t current_value, uint64_t default_value)
~OptionValueUInt64 () override=default
OptionValue::Type GetType () const override
void DumpValue (const ExecutionContext *exe_ctx, Stream &strm, uint32_t dump_mask) override
llvm::json::Value ToJSON (const ExecutionContext *exe_ctx) const override
Status SetValueFromString (llvm::StringRef value, VarSetOperationType op=eVarSetOperationAssign) override
void Clear () override
const uint64_t & operator= (uint64_t value)
operator uint64_t () const
uint64_t GetCurrentValue () const
uint64_t GetDefaultValue () const
bool SetCurrentValue (uint64_t value)
bool SetDefaultValue (uint64_t value)
void SetMinimumValue (uint64_t v)
uint64_t GetMinimumValue () const
void SetMaximumValue (uint64_t v)
uint64_t GetMaximumValue () const
Public Member Functions inherited from lldb_private::Cloneable< OptionValueUInt64, OptionValue >
std::shared_ptr< typename OptionValue::TopmostBase > Clone () const override
Public Member Functions inherited from lldb_private::OptionValue
OptionValue ()=default
virtual ~OptionValue ()=default
OptionValue (const OptionValue &other)
OptionValue & operator= (const OptionValue &other)
virtual bool ValueIsTransparent () const
virtual const char * GetTypeAsCString () const
virtual lldb::OptionValueSP DeepCopy (const lldb::OptionValueSP &new_parent) const
virtual void AutoComplete (CommandInterpreter &interpreter, CompletionRequest &request)
virtual lldb::OptionValueSP GetSubValue (const ExecutionContext *exe_ctx, llvm::StringRef name, Status &error) const
virtual Status SetSubValue (const ExecutionContext *exe_ctx, VarSetOperationType op, llvm::StringRef name, llvm::StringRef value)
virtual bool IsAggregateValue () const
virtual llvm::StringRef GetName () const
virtual bool DumpQualifiedName (Stream &strm) const
uint32_t GetTypeAsMask ()
OptionValueArch * GetAsArch ()
const OptionValueArch * GetAsArch () const
OptionValueArray * GetAsArray ()
const OptionValueArray * GetAsArray () const
OptionValueArgs * GetAsArgs ()
const OptionValueArgs * GetAsArgs () const
OptionValueBoolean * GetAsBoolean ()
const OptionValueBoolean * GetAsBoolean () const
OptionValueChar * GetAsChar ()
const OptionValueChar * GetAsChar () const
OptionValueDictionary * GetAsDictionary ()
const OptionValueDictionary * GetAsDictionary () const
OptionValueEnumeration * GetAsEnumeration ()
const OptionValueEnumeration * GetAsEnumeration () const
OptionValueFileSpec * GetAsFileSpec ()
const OptionValueFileSpec * GetAsFileSpec () const
OptionValueFileSpecList * GetAsFileSpecList ()
const OptionValueFileSpecList * GetAsFileSpecList () const
OptionValueFormat * GetAsFormat ()
const OptionValueFormat * GetAsFormat () const
OptionValueLanguage * GetAsLanguage ()
const OptionValueLanguage * GetAsLanguage () const
OptionValuePathMappings * GetAsPathMappings ()
const OptionValuePathMappings * GetAsPathMappings () const
OptionValueProperties * GetAsProperties ()
const OptionValueProperties * GetAsProperties () const
OptionValueRegex * GetAsRegex ()
const OptionValueRegex * GetAsRegex () const
OptionValueSInt64 * GetAsSInt64 ()
const OptionValueSInt64 * GetAsSInt64 () const
OptionValueString * GetAsString ()
const OptionValueString * GetAsString () const
OptionValueUInt64 * GetAsUInt64 ()
const OptionValueUInt64 * GetAsUInt64 () const
OptionValueUUID * GetAsUUID ()
const OptionValueUUID * GetAsUUID () const
OptionValueFormatEntity * GetAsFormatEntity ()
const OptionValueFormatEntity * GetAsFormatEntity () const
bool AppendFileSpecValue (FileSpec file_spec)
bool OptionWasSet () const
void SetOptionWasSet ()
void SetParent (const lldb::OptionValueSP &parent_sp)
lldb::OptionValueSP GetParent () const
void SetValueChangedCallback (std::function< void()> callback)
void NotifyValueChanged ()
template<typename T, std::enable_if_t<!std::is_pointer_v< T >, bool > = true>
std::optional< T > GetValueAs () const
template<typename T, typename U = typename std::remove_const< typename std::remove_pointer<T>::type>::type, std::enable_if_t< std::is_pointer_v< T >, bool > = true>
T GetValueAs () const
bool SetValueAs (bool v)
bool SetValueAs (char v)
bool SetValueAs (uint64_t v)
bool SetValueAs (int64_t v)
bool SetValueAs (UUID v)
bool SetValueAs (llvm::StringRef v)
bool SetValueAs (lldb::LanguageType v)
bool SetValueAs (lldb::Format v)
bool SetValueAs (FileSpec v)
bool SetValueAs (ArchSpec v)
bool SetValueAs (const FormatEntity::Entry &v)
template<typename T, std::enable_if_t< std::is_enum_v< T >, bool > = true>
bool SetValueAs (T t)
Static Public Member Functions
static lldb::OptionValueSP Create (llvm::StringRef value_str, Status &error)
Static Public Member Functions inherited from lldb_private::OptionValue
static const char * GetBuiltinTypeAsCString (Type t)
static uint32_t ConvertTypeToMask (OptionValue::Type type)
static OptionValue::Type ConvertTypeMaskToType (uint32_t type_mask)
static lldb::OptionValueSP CreateValueFromCStringForTypeMask (const char *value_cstr, uint32_t type_mask, Status &error)
Protected Attributes
uint64_t m_current_value = 0
uint64_t m_default_value = 0
uint64_t m_min_value = std::numeric_limits<uint64_t>::min()
uint64_t m_max_value = std::numeric_limits<uint64_t>::max()
Protected Attributes inherited from lldb_private::OptionValue
lldb::OptionValueWP m_parent_wp
std::function< void()> m_callback
bool m_value_was_set = false
Additional Inherited Members
Public Types inherited from lldb_private::OptionValue
enum Type {
eTypeInvalid = 0 , eTypeArch , eTypeArgs , eTypeArray ,
eTypeBoolean , eTypeChar , eTypeDictionary , eTypeEnum ,
eTypeFileLineColumn , eTypeFileSpec , eTypeFileSpecList , eTypeFormat ,
eTypeLanguage , eTypePathMap , eTypeProperties , eTypeRegex ,
eTypeSInt64 , eTypeString , eTypeUInt64 , eTypeUUID ,
eTypeFormatEntity
}
enum {
eDumpOptionName = (1u << 0) , eDumpOptionType = (1u << 1) , eDumpOptionValue = (1u << 2) , eDumpOptionDescription = (1u << 3) ,
eDumpOptionRaw = (1u << 4) , eDumpOptionCommand = (1u << 5) , eDumpOptionDefaultValue = (1u << 6) , eDumpGroupValue = (eDumpOptionName | eDumpOptionType | eDumpOptionValue) ,
eDumpGroupHelp , eDumpGroupExport = (eDumpOptionCommand | eDumpOptionName | eDumpOptionValue)
}
Protected Types inherited from lldb_private::OptionValue
using TopmostBase = OptionValue
Detailed Description
Definition at line 17 of file OptionValueUInt64.h.
Constructor & Destructor Documentation
OptionValueUInt64() [1/3]
lldb_private::OptionValueUInt64::OptionValueUInt64 () default
Referenced by Create().
OptionValueUInt64() [2/3]
lldb_private::OptionValueUInt64::OptionValueUInt64 (uint64_t value) inline
Definition at line 21 of file OptionValueUInt64.h.
References m_current_value, and m_default_value.
OptionValueUInt64() [3/3]
lldb_private::OptionValueUInt64::OptionValueUInt64 (uint64_t current_value, uint64_t default_value) inline
Definition at line 24 of file OptionValueUInt64.h.
References m_current_value, and m_default_value.
~OptionValueUInt64()
lldb_private::OptionValueUInt64::~OptionValueUInt64 () override default
References error().
Member Function Documentation
Clear()
void lldb_private::OptionValueUInt64::Clear () inline override virtual
Implements lldb_private::OptionValue.
Definition at line 49 of file OptionValueUInt64.h.
References m_current_value, m_default_value, and lldb_private::OptionValue::m_value_was_set.
Referenced by SetValueFromString().
Create()
lldb::OptionValueSP OptionValueUInt64::Create (llvm::StringRef value_str, Status & error) static
Definition at line 17 of file OptionValueUInt64.cpp.
References error(), and OptionValueUInt64().
Referenced by CommandObjectRegisterRead::CommandOptions::SetOptionValue().
DumpValue()
void OptionValueUInt64::DumpValue (const ExecutionContext * exe_ctx, Stream & strm, uint32_t dump_mask) override virtual
Implements lldb_private::OptionValue.
Definition at line 26 of file OptionValueUInt64.cpp.
References lldb_private::OptionValue::eDumpOptionDefaultValue, lldb_private::OptionValue::eDumpOptionType, lldb_private::OptionValue::eDumpOptionValue, lldb_private::OptionValue::GetTypeAsCString(), m_current_value, m_default_value, lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
GetCurrentValue()
uint64_t lldb_private::OptionValueUInt64::GetCurrentValue () const inline
Definition at line 63 of file OptionValueUInt64.h.
References m_current_value.
Referenced by CommandObjectMemoryWrite::DoExecute(), and OptionGroupReadMemory::FinalizeSettings().
GetDefaultValue()
uint64_t lldb_private::OptionValueUInt64::GetDefaultValue () const inline
Definition at line 65 of file OptionValueUInt64.h.
References m_default_value.
GetMaximumValue()
uint64_t lldb_private::OptionValueUInt64::GetMaximumValue () const inline
Definition at line 88 of file OptionValueUInt64.h.
References m_max_value.
GetMinimumValue()
uint64_t lldb_private::OptionValueUInt64::GetMinimumValue () const inline
Definition at line 84 of file OptionValueUInt64.h.
References m_min_value.
GetType()
OptionValue::Type lldb_private::OptionValueUInt64::GetType () const inline override virtual
Implements lldb_private::OptionValue.
Definition at line 36 of file OptionValueUInt64.h.
References lldb_private::OptionValue::eTypeUInt64.
operator uint64_t()
lldb_private::OptionValueUInt64::operator uint64_t () const inline
Definition at line 61 of file OptionValueUInt64.h.
References m_current_value.
operator=()
const uint64_t & lldb_private::OptionValueUInt64::operator= (uint64_t value) inline
Definition at line 56 of file OptionValueUInt64.h.
References m_current_value.
SetCurrentValue()
bool lldb_private::OptionValueUInt64::SetCurrentValue (uint64_t value) inline
Definition at line 67 of file OptionValueUInt64.h.
References m_current_value, m_max_value, and m_min_value.
SetDefaultValue()
bool lldb_private::OptionValueUInt64::SetDefaultValue (uint64_t value) inline
Definition at line 75 of file OptionValueUInt64.h.
References m_default_value, m_max_value, and m_min_value.
SetMaximumValue()
void lldb_private::OptionValueUInt64::SetMaximumValue (uint64_t v) inline
Definition at line 86 of file OptionValueUInt64.h.
References m_max_value.
SetMinimumValue()
void lldb_private::OptionValueUInt64::SetMinimumValue (uint64_t v) inline
Definition at line 82 of file OptionValueUInt64.h.
References m_min_value.
Referenced by lldb_private::Debugger::Debugger().
SetValueFromString()
Status OptionValueUInt64::SetValueFromString (llvm::StringRef value, VarSetOperationType op = eVarSetOperationAssign) override virtual
Reimplemented from lldb_private::OptionValue.
Definition at line 42 of file OptionValueUInt64.cpp.
References Clear(), error(), lldb_private::eVarSetOperationAppend, lldb_private::eVarSetOperationAssign, lldb_private::eVarSetOperationClear, lldb_private::eVarSetOperationInsertAfter, lldb_private::eVarSetOperationInsertBefore, lldb_private::eVarSetOperationInvalid, lldb_private::eVarSetOperationRemove, lldb_private::eVarSetOperationReplace, lldb_private::Status::FromErrorStringWithFormat(), m_current_value, m_max_value, m_min_value, lldb_private::OptionValue::m_value_was_set, lldb_private::OptionValue::NotifyValueChanged(), and lldb_private::OptionValue::SetValueFromString().
ToJSON()
llvm::json::Value lldb_private::OptionValueUInt64::ToJSON (const ExecutionContext * exe_ctx) const inline override virtual
Implements lldb_private::OptionValue.
Definition at line 41 of file OptionValueUInt64.h.
References m_current_value.
Member Data Documentation
m_current_value
uint64_t lldb_private::OptionValueUInt64::m_current_value = 0 protected
Definition at line 91 of file OptionValueUInt64.h.
Referenced by Clear(), DumpValue(), GetCurrentValue(), operator uint64_t(), operator=(), OptionValueUInt64(), OptionValueUInt64(), SetCurrentValue(), SetValueFromString(), and ToJSON().
m_default_value
uint64_t lldb_private::OptionValueUInt64::m_default_value = 0 protected
Definition at line 92 of file OptionValueUInt64.h.
Referenced by Clear(), DumpValue(), GetDefaultValue(), OptionValueUInt64(), OptionValueUInt64(), and SetDefaultValue().
m_max_value
uint64_t lldb_private::OptionValueUInt64::m_max_value = std::numeric_limits<uint64_t>::max() protected
Definition at line 94 of file OptionValueUInt64.h.
Referenced by GetMaximumValue(), SetCurrentValue(), SetDefaultValue(), SetMaximumValue(), and SetValueFromString().
m_min_value
uint64_t lldb_private::OptionValueUInt64::m_min_value = std::numeric_limits<uint64_t>::min() protected
Definition at line 93 of file OptionValueUInt64.h.
Referenced by GetMinimumValue(), SetCurrentValue(), SetDefaultValue(), SetMinimumValue(), and SetValueFromString().
The documentation for this class was generated from the following files:
OptionValueUInt64.h
OptionValueUInt64.cpp