LLDB: lldb_private::AutoHandle Class Reference
lldb_private::AutoHandle Class Reference
#include <AutoHandle.h>
Public Member Functions
AutoHandle (HANDLE handle, HANDLE invalid_value=INVALID_HANDLE_VALUE)
~AutoHandle ()
bool IsValid () const
HANDLE get () const
Private Attributes
HANDLE m_handle
HANDLE m_invalid_value
Detailed Description
Definition at line 16 of file AutoHandle.h.
Constructor & Destructor Documentation
AutoHandle()
lldb_private::AutoHandle::AutoHandle (HANDLE handle, HANDLE invalid_value = INVALID_HANDLE_VALUE) inline
Definition at line 18 of file AutoHandle.h.
References m_handle, and m_invalid_value.
~AutoHandle()
lldb_private::AutoHandle::~AutoHandle () inline
Definition at line 21 of file AutoHandle.h.
References m_handle, and m_invalid_value.
Member Function Documentation
get()
HANDLE lldb_private::AutoHandle::get () const inline
Definition at line 28 of file AutoHandle.h.
References m_handle.
Referenced by lldb_private::NativeProcessWindows::CacheLoadedModules(), GetExecutableForProcess(), and GetFileNameFromHandleFallback().
IsValid()
bool lldb_private::AutoHandle::IsValid () const inline
Definition at line 26 of file AutoHandle.h.
References m_handle, and m_invalid_value.
Referenced by lldb_private::NativeProcessWindows::CacheLoadedModules(), and GetFileNameFromHandleFallback().
Member Data Documentation
m_handle
HANDLE lldb_private::AutoHandle::m_handle private
Definition at line 31 of file AutoHandle.h.
Referenced by AutoHandle(), get(), IsValid(), and ~AutoHandle().
m_invalid_value
HANDLE lldb_private::AutoHandle::m_invalid_value private
Definition at line 32 of file AutoHandle.h.
Referenced by AutoHandle(), IsValid(), and ~AutoHandle().
The documentation for this class was generated from the following file:
AutoHandle.h