LLDB: lldb_private::dil::UnaryOpNode Class Reference
lldb_private::dil::UnaryOpNode Class Reference
#include <DILAST.h>
Public Member Functions
UnaryOpNode (uint32_t location, UnaryOpKind kind, ASTNodeUP operand)
llvm::Expected< lldb::ValueObjectSP > Accept (Visitor *v) const override
UnaryOpKind GetKind () const
ASTNode & GetOperand () const
Public Member Functions inherited from lldb_private::dil::ASTNode
ASTNode (uint32_t location, NodeKind kind)
virtual ~ASTNode ()=default
uint32_t GetLocation () const
NodeKind GetKind () const
Static Public Member Functions
static bool classof (const ASTNode &node)
Private Attributes
UnaryOpKind m_kind
ASTNodeUP m_operand
Detailed Description
Definition at line 131 of file DILAST.h.
Constructor & Destructor Documentation
UnaryOpNode()
lldb_private::dil::UnaryOpNode::UnaryOpNode (uint32_t location, UnaryOpKind kind, ASTNodeUP operand) inline
Definition at line 133 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), lldb_private::dil::eUnaryOpNode, m_kind, and m_operand.
Member Function Documentation
Accept()
llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::UnaryOpNode::Accept (Visitor * v) const override virtual
Implements lldb_private::dil::ASTNode.
Definition at line 26 of file DILAST.cpp.
References lldb_private::dil::Visitor::Visit().
classof()
bool lldb_private::dil::UnaryOpNode::classof (const ASTNode & node) inline static
Definition at line 142 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), lldb_private::dil::eUnaryOpNode, and lldb_private::dil::ASTNode::GetKind().
GetKind()
UnaryOpKind lldb_private::dil::UnaryOpNode::GetKind () const inline
Definition at line 139 of file DILAST.h.
References m_kind.
Referenced by lldb_private::dil::Interpreter::Visit().
GetOperand()
ASTNode & lldb_private::dil::UnaryOpNode::GetOperand () const inline
Definition at line 140 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), and m_operand.
Referenced by lldb_private::dil::Interpreter::Visit().
Member Data Documentation
m_kind
UnaryOpKind lldb_private::dil::UnaryOpNode::m_kind private
Definition at line 147 of file DILAST.h.
Referenced by GetKind(), and UnaryOpNode().
m_operand
ASTNodeUP lldb_private::dil::UnaryOpNode::m_operand private
Definition at line 148 of file DILAST.h.
Referenced by GetOperand(), and UnaryOpNode().
The documentation for this class was generated from the following files:
DILAST.h
DILAST.cpp