LLDB: lldb_private::Environment Class Reference
lldb_private::Environment Class Reference
#include <Environment.h>
Classes
class Envp
Public Member Functions
Environment ()
Environment (const Environment &RHS)
Environment (Environment &&RHS)
Environment (char *const *Env)
Environment (const char *const *Env)
Environment & operator= (Environment RHS)
std::pair< iterator, bool > insert (llvm::StringRef KeyEqValue)
void insert (iterator first, iterator last)
Envp getEnvp () const
Static Public Member Functions
static std::string compose (const value_type &KeyValue)
Private Types
using Base = llvm::StringMap<std::string>
Detailed Description
Definition at line 18 of file Environment.h.
Member Typedef Documentation
Base
using lldb_private::Environment::Base = llvm::StringMap<std::string> private
Definition at line 19 of file Environment.h.
Constructor & Destructor Documentation
Environment() [1/5]
lldb_private::Environment::Environment () inline
Definition at line 59 of file Environment.h.
Referenced by Environment(), Environment(), Environment(), and operator=().
Environment() [2/5]
lldb_private::Environment::Environment (const Environment & RHS) inline
Definition at line 60 of file Environment.h.
References Environment().
Environment() [3/5]
lldb_private::Environment::Environment (Environment && RHS) inline
Definition at line 61 of file Environment.h.
References Environment().
Environment() [4/5]
lldb_private::Environment::Environment (char *const * Env) inline
Definition at line 62 of file Environment.h.
References Environment().
Environment() [5/5]
Environment::Environment (const char *const * Env)
Definition at line 37 of file Environment.cpp.
References insert().
Member Function Documentation
compose()
std::string lldb_private::Environment::compose (const value_type & KeyValue) inline static
Definition at line 80 of file Environment.h.
Referenced by ComputeLaunchEnvironment(), CreateEnvironmentBufferW(), and lldb::SBEnvironment::GetEntries().
getEnvp()
Envp lldb_private::Environment::getEnvp () const inline
Definition at line 78 of file Environment.h.
Referenced by lldb_private::Args::Args(), LaunchProcessPosixSpawn(), and lldb_private::SBLaunchInfoImpl::RegenerateEnvp().
insert() [1/2]
void Environment::insert (iterator first, iterator last)
Definition at line 44 of file Environment.cpp.
insert() [2/2]
std::pair< iterator, bool > lldb_private::Environment::insert (llvm::StringRef KeyEqValue) inline
Definition at line 71 of file Environment.h.
References insert().
Referenced by Environment(), GetMacOSXProcessArgs(), GetProcessEnviron(), and insert().
operator=()
Environment & lldb_private::Environment::operator= (Environment RHS) inline
Definition at line 66 of file Environment.h.
References Environment().
The documentation for this class was generated from the following files:
Environment.h
Environment.cpp