LLDB: lldb_private::ThreadPlanCallOnFunctionExit Class Reference
lldb_private::ThreadPlanCallOnFunctionExit Class Reference
This thread plan calls a function object when the current function exits.
#include <ThreadPlanCallOnFunctionExit.h>
Public Types
using Callback = std::function<void()>
Definition for the callback made when the currently executing thread finishes executing its function.
Public Types inherited from lldb_private::ThreadPlan
enum ThreadPlanKind {
eKindGeneric , eKindNull , eKindBase , eKindCallFunction ,
eKindPython , eKindStepInstruction , eKindStepOut , eKindStepOverBreakpoint ,
eKindStepOverRange , eKindStepInRange , eKindRunToAddress , eKindStepThrough ,
eKindStepUntil , eKindSingleThreadTimeout
}
Public Member Functions
ThreadPlanCallOnFunctionExit (Thread &thread, const Callback &callback)
void DidPush () override
void GetDescription (Stream *s, lldb::DescriptionLevel level) override
Print a description of this thread to the stream s.
bool ValidatePlan (Stream *error) override
Returns whether this plan could be successfully created.
bool ShouldStop (Event *event_ptr) override
bool WillStop () override
Public Member Functions inherited from lldb_private::ThreadPlan
virtual ~ThreadPlan ()
const char * GetName () const
Returns the name of this thread plan.
Thread & GetThread ()
Returns the Thread that is using this thread plan.
Target & GetTarget ()
const Target & GetTarget () const
void ClearThreadCache ()
Clear the Thread* cache.
bool TracerExplainsStop ()
lldb::StateType RunState ()
bool PlanExplainsStop (Event *event_ptr)
virtual bool ShouldAutoContinue (Event *event_ptr)
Returns whether this thread plan overrides the ShouldStop of subsequently processed plans.
virtual Vote ShouldReportStop (Event *event_ptr)
Vote ShouldReportRun (Event *event_ptr)
virtual void SetStopOthers (bool new_value)
virtual bool StopOthers ()
virtual bool SupportsResumeOthers ()
virtual bool ShouldRunBeforePublicStop ()
bool WillResume (lldb::StateType resume_state, bool current_plan)
bool IsControllingPlan ()
virtual bool IsLeafPlan ()
bool SetIsControllingPlan (bool value)
virtual bool OkayToDiscard ()
void SetOkayToDiscard (bool value)
virtual bool MischiefManaged ()
virtual void ThreadDestroyed ()
bool GetPrivate ()
void SetPrivate (bool input)
virtual void DidPop ()
ThreadPlanKind GetKind () const
bool IsPlanComplete ()
void SetPlanComplete (bool success=true)
virtual bool IsPlanStale ()
bool PlanSucceeded ()
virtual bool IsBasePlan ()
lldb::ThreadPlanTracerSP & GetThreadPlanTracer ()
void SetThreadPlanTracer (lldb::ThreadPlanTracerSP new_tracer_sp)
void DoTraceLog ()
virtual lldb::ValueObjectSP GetReturnValueObject ()
virtual lldb::ExpressionVariableSP GetExpressionVariable ()
virtual void RestoreThreadState ()
virtual bool IsVirtualStep ()
bool SetIterationCount (size_t count)
virtual lldb::RunDirection GetDirection () const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Protected Member Functions
bool DoPlanExplainsStop (Event *event_ptr) override
lldb::StateType GetPlanRunState () override
Protected Member Functions inherited from lldb_private::ThreadPlan
ThreadPlan (ThreadPlanKind kind, const char *name, Thread &thread, Vote report_stop_vote, Vote report_run_vote)
virtual bool DoWillResume (lldb::StateType resume_state, bool current_plan)
void PushPlan (lldb::ThreadPlanSP &thread_plan_sp)
ThreadPlan * GetPreviousPlan ()
lldb::StopInfoSP GetPrivateStopInfo ()
void SetStopInfo (lldb::StopInfoSP stop_reason_sp)
bool IsUsuallyUnexplainedStopReason (lldb::StopReason)
Private Attributes
Callback m_callback
lldb::ThreadPlanSP m_step_out_threadplan_sp
Additional Inherited Members
Protected Attributes inherited from lldb_private::ThreadPlan
Status m_status
Process & m_process
lldb::tid_t m_tid
Vote m_report_stop_vote
Vote m_report_run_vote
bool m_takes_iteration_count
bool m_could_not_resolve_hw_bp
int32_t m_iteration_count = 1
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Detailed Description
This thread plan calls a function object when the current function exits.
Definition at line 22 of file ThreadPlanCallOnFunctionExit.h.
Member Typedef Documentation
Callback
using lldb_private::ThreadPlanCallOnFunctionExit::Callback = std::function<void()>
Definition for the callback made when the currently executing thread finishes executing its function.
Definition at line 26 of file ThreadPlanCallOnFunctionExit.h.
Constructor & Destructor Documentation
ThreadPlanCallOnFunctionExit()
ThreadPlanCallOnFunctionExit::ThreadPlanCallOnFunctionExit (Thread & thread, const Callback & callback)
Definition at line 14 of file ThreadPlanCallOnFunctionExit.cpp.
References lldb_private::ThreadPlan::eKindGeneric, lldb_private::eVoteNoOpinion, m_callback, lldb_private::ThreadPlan::SetIsControllingPlan(), and lldb_private::ThreadPlan::ThreadPlan().
Member Function Documentation
DidPush()
void ThreadPlanCallOnFunctionExit::DidPush () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 24 of file ThreadPlanCallOnFunctionExit.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eVoteNo, lldb_private::eVoteNoOpinion, lldb_private::ThreadPlan::GetThread(), m_step_out_threadplan_sp, and lldb_private::Thread::QueueThreadPlanForStepOut().
DoPlanExplainsStop()
bool ThreadPlanCallOnFunctionExit::DoPlanExplainsStop (Event * event_ptr) override protected virtual
Implements lldb_private::ThreadPlan.
Definition at line 86 of file ThreadPlanCallOnFunctionExit.cpp.
GetDescription()
void ThreadPlanCallOnFunctionExit::GetDescription (Stream * s, lldb::DescriptionLevel level) override virtual
Print a description of this thread to the stream s.
thread. Don't expect that the result of GetThread is valid in the description method. This might get called when the underlying Thread has not been reported, so we only know the TID and not the thread.
Parameters
[in] s The stream to which to print the description.
[in] level The level of description desired. Note that eDescriptionLevelBrief will be used in the stop message printed when the plan is complete.
Implements lldb_private::ThreadPlan.
Definition at line 45 of file ThreadPlanCallOnFunctionExit.cpp.
References lldb_private::Stream::Printf().
GetPlanRunState()
lldb::StateType ThreadPlanCallOnFunctionExit::GetPlanRunState () override protected virtual
Implements lldb_private::ThreadPlan.
Definition at line 93 of file ThreadPlanCallOnFunctionExit.cpp.
References lldb::eStateRunning.
ShouldStop()
bool ThreadPlanCallOnFunctionExit::ShouldStop (Event * event_ptr) override virtual
Implements lldb_private::ThreadPlan.
Definition at line 59 of file ThreadPlanCallOnFunctionExit.cpp.
References m_callback, m_step_out_threadplan_sp, and lldb_private::ThreadPlan::SetPlanComplete().
ValidatePlan()
bool ThreadPlanCallOnFunctionExit::ValidatePlan (Stream * error) override virtual
Returns whether this plan could be successfully created.
Parameters
[in] error A stream to which to print some reason why the plan could not be created. Can be NULL.
Returns
true if the plan should be queued, false otherwise.
Implements lldb_private::ThreadPlan.
Definition at line 53 of file ThreadPlanCallOnFunctionExit.cpp.
References error().
WillStop()
bool ThreadPlanCallOnFunctionExit::WillStop () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 79 of file ThreadPlanCallOnFunctionExit.cpp.
Member Data Documentation
m_callback
Callback lldb_private::ThreadPlanCallOnFunctionExit::m_callback private
Definition at line 48 of file ThreadPlanCallOnFunctionExit.h.
Referenced by ShouldStop(), and ThreadPlanCallOnFunctionExit().
m_step_out_threadplan_sp
lldb::ThreadPlanSP lldb_private::ThreadPlanCallOnFunctionExit::m_step_out_threadplan_sp private
Definition at line 49 of file ThreadPlanCallOnFunctionExit.h.
Referenced by DidPush(), and ShouldStop().
The documentation for this class was generated from the following files:
ThreadPlanCallOnFunctionExit.h
ThreadPlanCallOnFunctionExit.cpp