LLDB: lldb_private::OptionGroupArchitecture Class Reference
lldb_private::OptionGroupArchitecture Class Reference
#include <OptionGroupArchitecture.h>
Public Member Functions
OptionGroupArchitecture ()=default
~OptionGroupArchitecture () override=default
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext *execution_context) override
void OptionParsingStarting (ExecutionContext *execution_context) override
bool GetArchitecture (Platform *platform, ArchSpec &arch)
bool ArchitectureWasSpecified () const
llvm::StringRef GetArchitectureName () const
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Protected Attributes
std::string m_arch_str
Detailed Description
Definition at line 19 of file OptionGroupArchitecture.h.
Constructor & Destructor Documentation
OptionGroupArchitecture()
lldb_private::OptionGroupArchitecture::OptionGroupArchitecture () default
~OptionGroupArchitecture()
lldb_private::OptionGroupArchitecture::~OptionGroupArchitecture () override default
Member Function Documentation
ArchitectureWasSpecified()
bool lldb_private::OptionGroupArchitecture::ArchitectureWasSpecified () const inline
Definition at line 34 of file OptionGroupArchitecture.h.
References m_arch_str.
GetArchitecture()
bool OptionGroupArchitecture::GetArchitecture (Platform * platform, ArchSpec & arch)
Definition at line 26 of file OptionGroupArchitecture.cpp.
References lldb_private::Platform::GetAugmentedArchSpec(), lldb_private::ArchSpec::IsValid(), and m_arch_str.
GetArchitectureName()
llvm::StringRef lldb_private::OptionGroupArchitecture::GetArchitectureName () const inline
Definition at line 36 of file OptionGroupArchitecture.h.
References m_arch_str.
GetDefinitions()
llvm::ArrayRef< OptionDefinition > OptionGroupArchitecture::GetDefinitions () override virtual
Implements lldb_private::OptionGroup.
Definition at line 22 of file OptionGroupArchitecture.cpp.
References g_option_table.
OptionParsingStarting()
void OptionGroupArchitecture::OptionParsingStarting (ExecutionContext * execution_context) override virtual
Implements lldb_private::OptionGroup.
Definition at line 51 of file OptionGroupArchitecture.cpp.
References m_arch_str.
SetOptionValue()
Status OptionGroupArchitecture::SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext * execution_context) override virtual
Implements lldb_private::OptionGroup.
Definition at line 33 of file OptionGroupArchitecture.cpp.
References error(), g_option_table, and m_arch_str.
Member Data Documentation
m_arch_str
std::string lldb_private::OptionGroupArchitecture::m_arch_str protected
Definition at line 39 of file OptionGroupArchitecture.h.
Referenced by ArchitectureWasSpecified(), GetArchitecture(), GetArchitectureName(), OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following files:
OptionGroupArchitecture.h
OptionGroupArchitecture.cpp