LLDB: lldb_private::ProcessLauncherWindows Class Reference
lldb_private::ProcessLauncherWindows Class Reference
#include <ProcessLauncherWindows.h>
Public Member Functions
HostProcess LaunchProcess (const ProcessLaunchInfo &launch_info, Status &error) override
Public Member Functions inherited from lldb_private::ProcessLauncher
virtual ~ProcessLauncher ()=default
Protected Member Functions
HANDLE GetStdioHandle (const ProcessLaunchInfo &launch_info, int fd)
llvm::ErrorOr< std::vector< HANDLE > > GetInheritedHandles (const ProcessLaunchInfo &launch_info, STARTUPINFOEXW &startupinfoex, HANDLE stdout_handle=NULL, HANDLE stderr_handle=NULL, HANDLE stdin_handle=NULL)
Get the list of Windows handles that should be inherited by the child process and update STARTUPINFOEXW with the handle list.
Detailed Description
Definition at line 73 of file ProcessLauncherWindows.h.
Member Function Documentation
GetInheritedHandles()
llvm::ErrorOr< std::vector< HANDLE > > ProcessLauncherWindows::GetInheritedHandles (const ProcessLaunchInfo & launch_info, STARTUPINFOEXW & startupinfoex, HANDLE stdout_handle = NULL, HANDLE stderr_handle = NULL, HANDLE stdin_handle = NULL) protected
Get the list of Windows handles that should be inherited by the child process and update STARTUPINFOEXW with the handle list.
If no handles need to be inherited, an empty vector is returned.
Otherwise, the function populates the PROC_THREAD_ATTRIBUTE_HANDLE_LIST attribute in startupinfoex with the collected handles using UpdateProcThreadAttribute. On success, the vector of inherited handles is returned.
Parameters
launch_info The process launch configuration.
startupinfoex The extended STARTUPINFO structure for the process being created.
stdout_handle
stderr_handle
stdin_handle Optional explicit standard stream handles to use for the child process.
Returns
std::vector<HANDLE> containing all handles that the child must inherit.
Definition at line 230 of file ProcessLauncherWindows.cpp.
References lldb_private::FileAction::eFileActionDuplicate, lldb_private::FileAction::GetAction(), lldb_private::FileAction::GetActionArgument(), lldb_private::FileAction::GetFD(), lldb_private::ProcessLaunchInfo::GetFileActionAtIndex(), and lldb_private::ProcessLaunchInfo::GetNumFileActions().
Referenced by LaunchProcess().
GetStdioHandle()
HANDLE ProcessLauncherWindows::GetStdioHandle (const ProcessLaunchInfo & launch_info, int fd) protected
Definition at line 270 of file ProcessLauncherWindows.cpp.
References lldb_private::ProcessLaunchInfo::GetFileActionForFD(), lldb_private::FileAction::GetFileSpec(), and lldb_private::FileSpec::GetPath().
Referenced by LaunchProcess().
LaunchProcess()
HostProcess ProcessLauncherWindows::LaunchProcess (const ProcessLaunchInfo & launch_info, Status & error) override virtual
Implements lldb_private::ProcessLauncher.
Definition at line 119 of file ProcessLauncherWindows.cpp.
References lldb_private::ProcThreadAttributeList::Create(), CreateEnvironmentBufferW(), lldb::eErrorTypeWin32, error(), lldb_private::Status::FromError(), lldb_private::ProcessInfo::GetArguments(), lldb_private::ProcessInfo::GetEnvironment(), lldb_private::ProcessInfo::GetExecutableFile(), lldb_private::ProcessLaunchInfo::GetFlags(), GetFlattenedWindowsCommandStringW(), GetInheritedHandles(), lldb_private::FileSpec::GetPath(), lldb_private::ProcessLaunchInfo::GetPTY(), GetStdioHandle(), lldb_private::ProcessLaunchInfo::GetWorkingDirectory(), lldb_private::ProcThreadAttributeList::SetupPseudoConsole(), lldb_private::ProcessLaunchInfo::ShouldUsePTY(), lldb_private::Status, and lldb_private::Flags::Test().
Referenced by lldb_private::DebuggerThread::DebuggerThreadLaunchRoutine().
The documentation for this class was generated from the following files:
ProcessLauncherWindows.h
ProcessLauncherWindows.cpp