LLDB: lldb_private::formatters::StringPrinter::DumpToStreamOptions Class Reference
lldb_private::formatters::StringPrinter::DumpToStreamOptions Class Reference
#include <StringPrinter.h>
Public Member Functions
DumpToStreamOptions ()=default
void SetStream (Stream *s)
Stream * GetStream () const
void SetPrefixToken (const std::string &p)
void SetPrefixToken (std::nullptr_t)
const char * GetPrefixToken () const
void SetSuffixToken (const std::string &p)
void SetSuffixToken (std::nullptr_t)
const char * GetSuffixToken () const
void SetQuote (char q)
char GetQuote () const
void SetSourceSize (uint32_t s)
uint32_t GetSourceSize () const
void SetNeedsZeroTermination (bool z)
bool GetNeedsZeroTermination () const
void SetBinaryZeroIsTerminator (bool e)
bool GetBinaryZeroIsTerminator () const
void SetEscapeNonPrintables (bool e)
bool GetEscapeNonPrintables () const
void SetIgnoreMaxLength (bool e)
bool GetIgnoreMaxLength () const
void SetEscapeStyle (EscapeStyle style)
EscapeStyle GetEscapeStyle () const
Private Attributes
Stream * m_stream = nullptr
The used output stream.
std::string m_prefix_token
String that should be printed before the heading quote character.
std::string m_suffix_token
String that should be printed after the trailing quote character.
char m_quote = '"'
The quote character that should surround the string.
uint32_t m_source_size = 0
The length of the memory region that should be dumped in bytes.
bool m_needs_zero_termination = true
bool m_escape_non_printables = true
True iff non-printable characters should be escaped when dumping them to the stream.
bool m_ignore_max_length = false
True iff the max-string-summary-length setting of the target should be ignored.
bool m_zero_is_terminator = true
True iff a zero bytes ('\0') should terminate the memory region that is being dumped.
EscapeStyle m_escape_style = EscapeStyle::CXX
The language-specific style for escaping special characters.
Detailed Description
Definition at line 29 of file StringPrinter.h.
Constructor & Destructor Documentation
DumpToStreamOptions()
lldb_private::formatters::StringPrinter::DumpToStreamOptions::DumpToStreamOptions () default
Member Function Documentation
GetBinaryZeroIsTerminator()
bool lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetBinaryZeroIsTerminator () const inline
Definition at line 63 of file StringPrinter.h.
References m_zero_is_terminator.
Referenced by DumpEncodedBufferToStream(), and lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::ReadBufferAndDumpToStreamOptions().
GetEscapeNonPrintables()
bool lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetEscapeNonPrintables () const inline
Definition at line 67 of file StringPrinter.h.
References m_escape_non_printables.
Referenced by DumpEncodedBufferToStream(), and lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::ReadBufferAndDumpToStreamOptions().
GetEscapeStyle()
EscapeStyle lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetEscapeStyle () const inline
Definition at line 75 of file StringPrinter.h.
References m_escape_style.
Referenced by DumpEncodedBufferToStream(), and lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::ReadBufferAndDumpToStreamOptions().
GetIgnoreMaxLength()
bool lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetIgnoreMaxLength () const inline
Definition at line 71 of file StringPrinter.h.
References m_ignore_max_length.
Referenced by lldb_private::formatters::ReadEncodedBufferAndDumpToStream().
GetNeedsZeroTermination()
bool lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetNeedsZeroTermination () const inline
Definition at line 59 of file StringPrinter.h.
References m_needs_zero_termination.
Referenced by lldb_private::formatters::ReadEncodedBufferAndDumpToStream().
GetPrefixToken()
const char * lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetPrefixToken () const inline
Definition at line 41 of file StringPrinter.h.
References m_prefix_token.
Referenced by DumpEncodedBufferToStream(), and lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::ReadBufferAndDumpToStreamOptions().
GetQuote()
char lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetQuote () const inline
Definition at line 51 of file StringPrinter.h.
References m_quote.
Referenced by DumpEncodedBufferToStream(), and lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::ReadBufferAndDumpToStreamOptions().
GetSourceSize()
uint32_t lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetSourceSize () const inline
Definition at line 55 of file StringPrinter.h.
References m_source_size.
Referenced by DumpEncodedBufferToStream(), and lldb_private::formatters::ReadEncodedBufferAndDumpToStream().
GetStream()
Stream * lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetStream () const inline
Definition at line 35 of file StringPrinter.h.
References m_stream.
Referenced by DumpEncodedBufferToStream(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::ReadBufferAndDumpToStreamOptions(), and lldb_private::formatters::ReadEncodedBufferAndDumpToStream().
GetSuffixToken()
const char * lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetSuffixToken () const inline
Definition at line 47 of file StringPrinter.h.
References m_suffix_token.
Referenced by DumpEncodedBufferToStream(), and lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::ReadBufferAndDumpToStreamOptions().
SetBinaryZeroIsTerminator()
void lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetBinaryZeroIsTerminator (bool e) inline
Definition at line 61 of file StringPrinter.h.
References m_zero_is_terminator.
Referenced by CharSummaryProvider(), lldb_private::formatters::NSStringSummaryProvider(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::ReadBufferAndDumpToStreamOptions(), lldb_private::formatters::ReadEncodedBufferAndDumpToStream(), and lldb_private::formatters::WCharSummaryProvider().
SetEscapeNonPrintables()
void lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetEscapeNonPrintables (bool e) inline
Definition at line 65 of file StringPrinter.h.
References m_escape_non_printables.
Referenced by lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::ReadBufferAndDumpToStreamOptions(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::ReadBufferAndDumpToStreamOptions(), and lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::ReadStringAndDumpToStreamOptions().
SetEscapeStyle()
void lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetEscapeStyle (EscapeStyle style) inline
Definition at line 73 of file StringPrinter.h.
References m_escape_style.
Referenced by lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::ReadBufferAndDumpToStreamOptions().
SetIgnoreMaxLength()
void lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetIgnoreMaxLength (bool e) inline
Definition at line 69 of file StringPrinter.h.
References m_ignore_max_length.
Referenced by lldb_private::formatters::NSStringSummaryProvider().
SetNeedsZeroTermination()
void lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetNeedsZeroTermination (bool z) inline
Definition at line 57 of file StringPrinter.h.
References m_needs_zero_termination.
Referenced by lldb_private::formatters::NSStringSummaryProvider(), and lldb_private::formatters::ReadEncodedBufferAndDumpToStream().
SetPrefixToken() [1/2]
void lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetPrefixToken (const std::string & p) inline
Definition at line 37 of file StringPrinter.h.
References m_prefix_token.
Referenced by CharStringSummaryProvider(), CharSummaryProvider(), lldb_private::formatters::NSStringSummaryProvider(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::ReadBufferAndDumpToStreamOptions(), lldb_private::formatters::WCharStringSummaryProvider(), and lldb_private::formatters::WCharSummaryProvider().
SetPrefixToken() [2/2]
void lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetPrefixToken (std::nullptr_t) inline
Definition at line 39 of file StringPrinter.h.
References m_prefix_token.
SetQuote()
void lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetQuote (char q) inline
Definition at line 49 of file StringPrinter.h.
References m_quote.
Referenced by CharSummaryProvider(), lldb_private::formatters::NSStringSummaryProvider(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::ReadBufferAndDumpToStreamOptions(), and lldb_private::formatters::WCharSummaryProvider().
SetSourceSize()
void lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetSourceSize (uint32_t s) inline
Definition at line 53 of file StringPrinter.h.
References m_source_size.
Referenced by CharSummaryProvider(), lldb_private::formatters::NSStringSummaryProvider(), lldb_private::formatters::ReadEncodedBufferAndDumpToStream(), and lldb_private::formatters::WCharSummaryProvider().
SetStream()
void lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetStream (Stream * s) inline
Definition at line 33 of file StringPrinter.h.
References m_stream.
Referenced by CharStringSummaryProvider(), CharSummaryProvider(), lldb_private::formatters::NSStringSummaryProvider(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::ReadBufferAndDumpToStreamOptions(), lldb_private::formatters::WCharStringSummaryProvider(), and lldb_private::formatters::WCharSummaryProvider().
SetSuffixToken() [1/2]
void lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetSuffixToken (const std::string & p) inline
Definition at line 43 of file StringPrinter.h.
References m_suffix_token.
Referenced by lldb_private::formatters::NSStringSummaryProvider(), and lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::ReadBufferAndDumpToStreamOptions().
SetSuffixToken() [2/2]
void lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetSuffixToken (std::nullptr_t) inline
Definition at line 45 of file StringPrinter.h.
References m_suffix_token.
Member Data Documentation
m_escape_non_printables
bool lldb_private::formatters::StringPrinter::DumpToStreamOptions::m_escape_non_printables = true private
True iff non-printable characters should be escaped when dumping them to the stream.
Definition at line 91 of file StringPrinter.h.
Referenced by GetEscapeNonPrintables(), and SetEscapeNonPrintables().
m_escape_style
EscapeStyle lldb_private::formatters::StringPrinter::DumpToStreamOptions::m_escape_style = EscapeStyle::CXX private
The language-specific style for escaping special characters.
Definition at line 99 of file StringPrinter.h.
Referenced by GetEscapeStyle(), and SetEscapeStyle().
m_ignore_max_length
bool lldb_private::formatters::StringPrinter::DumpToStreamOptions::m_ignore_max_length = false private
True iff the max-string-summary-length setting of the target should be ignored.
Definition at line 94 of file StringPrinter.h.
Referenced by GetIgnoreMaxLength(), and SetIgnoreMaxLength().
m_needs_zero_termination
bool lldb_private::formatters::StringPrinter::DumpToStreamOptions::m_needs_zero_termination = true private
Definition at line 88 of file StringPrinter.h.
Referenced by GetNeedsZeroTermination(), and SetNeedsZeroTermination().
m_prefix_token
std::string lldb_private::formatters::StringPrinter::DumpToStreamOptions::m_prefix_token private
String that should be printed before the heading quote character.
Definition at line 81 of file StringPrinter.h.
Referenced by GetPrefixToken(), SetPrefixToken(), and SetPrefixToken().
m_quote
char lldb_private::formatters::StringPrinter::DumpToStreamOptions::m_quote = '"' private
The quote character that should surround the string.
Definition at line 85 of file StringPrinter.h.
Referenced by GetQuote(), and SetQuote().
m_source_size
uint32_t lldb_private::formatters::StringPrinter::DumpToStreamOptions::m_source_size = 0 private
The length of the memory region that should be dumped in bytes.
Definition at line 87 of file StringPrinter.h.
Referenced by GetSourceSize(), and SetSourceSize().
m_stream
Stream* lldb_private::formatters::StringPrinter::DumpToStreamOptions::m_stream = nullptr private
The used output stream.
Definition at line 79 of file StringPrinter.h.
Referenced by GetStream(), and SetStream().
m_suffix_token
std::string lldb_private::formatters::StringPrinter::DumpToStreamOptions::m_suffix_token private
String that should be printed after the trailing quote character.
Definition at line 83 of file StringPrinter.h.
Referenced by GetSuffixToken(), SetSuffixToken(), and SetSuffixToken().
m_zero_is_terminator
bool lldb_private::formatters::StringPrinter::DumpToStreamOptions::m_zero_is_terminator = true private
True iff a zero bytes ('\0') should terminate the memory region that is being dumped.
Definition at line 97 of file StringPrinter.h.
Referenced by GetBinaryZeroIsTerminator(), and SetBinaryZeroIsTerminator().
The documentation for this class was generated from the following file:
StringPrinter.h