LLDB: lldb_private::ThreadPlanSingleThreadTimeout Class Reference
lldb_private::ThreadPlanSingleThreadTimeout Class Reference
#include <ThreadPlanSingleThreadTimeout.h>
Classes
struct TimeoutInfo
Public Types
using TimeoutInfoSP
Public Types inherited from lldb_private::ThreadPlan
enum ThreadPlanKind {
eKindGeneric , eKindNull , eKindBase , eKindCallFunction ,
eKindPython , eKindStepInstruction , eKindStepOut , eKindStepOverBreakpoint ,
eKindStepOverRange , eKindStepInRange , eKindRunToAddress , eKindStepThrough ,
eKindStepUntil , eKindSingleThreadTimeout
}
Public Member Functions
~ThreadPlanSingleThreadTimeout () override
void GetDescription (Stream *s, lldb::DescriptionLevel level) override
Print a description of this thread to the stream s.
bool ValidatePlan (Stream *error) override
Returns whether this plan could be successfully created.
bool WillStop () override
void DidPop () override
bool IsLeafPlan () override
bool DoPlanExplainsStop (Event *event_ptr) override
lldb::StateType GetPlanRunState () override
bool MischiefManaged () override
bool ShouldStop (Event *event_ptr) override
void SetStopOthers (bool new_value) override
bool StopOthers () override
Public Member Functions inherited from lldb_private::ThreadPlan
virtual ~ThreadPlan ()
const char * GetName () const
Returns the name of this thread plan.
Thread & GetThread ()
Returns the Thread that is using this thread plan.
Target & GetTarget ()
const Target & GetTarget () const
void ClearThreadCache ()
Clear the Thread* cache.
bool TracerExplainsStop ()
lldb::StateType RunState ()
bool PlanExplainsStop (Event *event_ptr)
virtual bool ShouldAutoContinue (Event *event_ptr)
Returns whether this thread plan overrides the ShouldStop of subsequently processed plans.
virtual Vote ShouldReportStop (Event *event_ptr)
Vote ShouldReportRun (Event *event_ptr)
virtual bool SupportsResumeOthers ()
virtual bool ShouldRunBeforePublicStop ()
bool WillResume (lldb::StateType resume_state, bool current_plan)
bool IsControllingPlan ()
bool SetIsControllingPlan (bool value)
virtual bool OkayToDiscard ()
void SetOkayToDiscard (bool value)
virtual void ThreadDestroyed ()
bool GetPrivate ()
void SetPrivate (bool input)
virtual void DidPush ()
ThreadPlanKind GetKind () const
bool IsPlanComplete ()
void SetPlanComplete (bool success=true)
virtual bool IsPlanStale ()
bool PlanSucceeded ()
virtual bool IsBasePlan ()
lldb::ThreadPlanTracerSP & GetThreadPlanTracer ()
void SetThreadPlanTracer (lldb::ThreadPlanTracerSP new_tracer_sp)
void DoTraceLog ()
virtual lldb::ValueObjectSP GetReturnValueObject ()
virtual lldb::ExpressionVariableSP GetExpressionVariable ()
virtual void RestoreThreadState ()
virtual bool IsVirtualStep ()
bool SetIterationCount (size_t count)
virtual lldb::RunDirection GetDirection () const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Static Public Member Functions
static void PushNewWithTimeout (Thread &thread, TimeoutInfoSP &info)
static void ResumeFromPrevState (Thread &thread, TimeoutInfoSP &info)
static void TimeoutThreadFunc (ThreadPlanSingleThreadTimeout *self)
Private Types
enum class State { WaitTimeout , AsyncInterrupt , Done }
Private Member Functions
ThreadPlanSingleThreadTimeout (Thread &thread, TimeoutInfoSP &info)
bool IsTimeoutAsyncInterrupt (Event *event_ptr)
bool HandleEvent (Event *event_ptr)
void HandleTimeout ()
uint64_t GetRemainingTimeoutMilliSeconds ()
ThreadPlanSingleThreadTimeout (const ThreadPlanSingleThreadTimeout &)=delete
const ThreadPlanSingleThreadTimeout & operator= (const ThreadPlanSingleThreadTimeout &)=delete
Static Private Member Functions
static std::string StateToString (State state)
Private Attributes
TimeoutInfoSP m_info
State m_state
std::mutex m_mutex
std::condition_variable m_wakeup_cv
std::thread m_timer_thread
std::chrono::steady_clock::time_point m_timeout_start
Additional Inherited Members
Protected Member Functions inherited from lldb_private::ThreadPlan
ThreadPlan (ThreadPlanKind kind, const char *name, Thread &thread, Vote report_stop_vote, Vote report_run_vote)
virtual bool DoWillResume (lldb::StateType resume_state, bool current_plan)
void PushPlan (lldb::ThreadPlanSP &thread_plan_sp)
ThreadPlan * GetPreviousPlan ()
lldb::StopInfoSP GetPrivateStopInfo ()
void SetStopInfo (lldb::StopInfoSP stop_reason_sp)
bool IsUsuallyUnexplainedStopReason (lldb::StopReason)
Protected Attributes inherited from lldb_private::ThreadPlan
Status m_status
Process & m_process
lldb::tid_t m_tid
Vote m_report_stop_vote
Vote m_report_run_vote
bool m_takes_iteration_count
bool m_could_not_resolve_hw_bp
int32_t m_iteration_count = 1
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Detailed Description
Definition at line 36 of file ThreadPlanSingleThreadTimeout.h.
Member Typedef Documentation
TimeoutInfoSP
using lldb_private::ThreadPlanSingleThreadTimeout::TimeoutInfoSP
Initial value:
      std::shared_ptr<ThreadPlanSingleThreadTimeout::TimeoutInfo>
Definition at line 50 of file ThreadPlanSingleThreadTimeout.h.
Member Enumeration Documentation
State
enum class lldb_private::ThreadPlanSingleThreadTimeout::State strong private
Enumerator
WaitTimeout
AsyncInterrupt
Done
Definition at line 37 of file ThreadPlanSingleThreadTimeout.h.
Constructor & Destructor Documentation
~ThreadPlanSingleThreadTimeout()
ThreadPlanSingleThreadTimeout::~ThreadPlanSingleThreadTimeout () override
Definition at line 38 of file ThreadPlanSingleThreadTimeout.cpp.
References m_info.
ThreadPlanSingleThreadTimeout() [1/2]
ThreadPlanSingleThreadTimeout::ThreadPlanSingleThreadTimeout (Thread & thread, TimeoutInfoSP & info) private
Definition at line 27 of file ThreadPlanSingleThreadTimeout.cpp.
References lldb_private::ThreadPlan::eKindSingleThreadTimeout, lldb_private::eVoteNo, lldb_private::eVoteNoOpinion, m_info, m_state, m_timer_thread, lldb_private::ThreadPlan::ThreadPlan(), TimeoutThreadFunc(), and WaitTimeout.
Referenced by operator=(), PushNewWithTimeout(), ResumeFromPrevState(), ThreadPlanSingleThreadTimeout(), and TimeoutThreadFunc().
ThreadPlanSingleThreadTimeout() [2/2]
lldb_private::ThreadPlanSingleThreadTimeout::ThreadPlanSingleThreadTimeout (const ThreadPlanSingleThreadTimeout &) private delete
References ThreadPlanSingleThreadTimeout().
Member Function Documentation
DidPop()
void ThreadPlanSingleThreadTimeout::DidPop () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 132 of file ThreadPlanSingleThreadTimeout.cpp.
References lldb_private::GetLog(), LLDB_LOGF, m_info, m_mutex, m_timer_thread, m_wakeup_cv, and lldb_private::Step.
DoPlanExplainsStop()
bool ThreadPlanSingleThreadTimeout::DoPlanExplainsStop (Event * event_ptr) override virtual
Implements lldb_private::ThreadPlan.
Definition at line 145 of file ThreadPlanSingleThreadTimeout.cpp.
References lldb_private::GetLog(), GetRemainingTimeoutMilliSeconds(), IsTimeoutAsyncInterrupt(), LLDB_LOGF, and lldb_private::Step.
GetDescription()
void ThreadPlanSingleThreadTimeout::GetDescription (Stream * s, lldb::DescriptionLevel level) override virtual
Print a description of this thread to the stream s.
thread. Don't expect that the result of GetThread is valid in the description method. This might get called when the underlying Thread has not been reported, so we only know the TID and not the thread.
Parameters
[in] s The stream to which to print the description.
[in] level The level of description desired. Note that eDescriptionLevelBrief will be used in the stop message printed when the plan is complete.
Implements lldb_private::ThreadPlan.
Definition at line 51 of file ThreadPlanSingleThreadTimeout.cpp.
References GetRemainingTimeoutMilliSeconds(), m_state, lldb_private::Stream::Printf(), and StateToString().
GetPlanRunState()
lldb::StateType ThreadPlanSingleThreadTimeout::GetPlanRunState () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 155 of file ThreadPlanSingleThreadTimeout.cpp.
References lldb_private::ThreadPlan::GetPlanRunState(), and lldb_private::ThreadPlan::GetPreviousPlan().
GetRemainingTimeoutMilliSeconds()
uint64_t ThreadPlanSingleThreadTimeout::GetRemainingTimeoutMilliSeconds () private
Definition at line 42 of file ThreadPlanSingleThreadTimeout.cpp.
References lldb_private::ThreadProperties::GetSingleThreadPlanTimeout(), lldb_private::ThreadPlan::GetThread(), and m_timeout_start.
Referenced by DoPlanExplainsStop(), and GetDescription().
HandleEvent()
bool ThreadPlanSingleThreadTimeout::HandleEvent (Event * event_ptr) private
Definition at line 223 of file ThreadPlanSingleThreadTimeout.cpp.
References Done, lldb_private::Thread::GetCurrentPlan(), lldb_private::GetLog(), lldb_private::ThreadPlan::GetPreviousPlan(), lldb_private::Process::ProcessEventData::GetRestartedFromEvent(), lldb_private::ThreadPlan::GetThread(), IsTimeoutAsyncInterrupt(), LLDB_LOGF, m_state, lldb_private::ThreadPlan::SetStopOthers(), and lldb_private::Step.
Referenced by ShouldStop().
HandleTimeout()
void ThreadPlanSingleThreadTimeout::HandleTimeout () private
Definition at line 247 of file ThreadPlanSingleThreadTimeout.cpp.
References AsyncInterrupt, lldb_private::GetLog(), lldb_private::ThreadPlan::GetThread(), LLDB_LOGF, lldb_private::ThreadPlan::m_process, m_state, and lldb_private::Step.
Referenced by TimeoutThreadFunc().
IsLeafPlan()
bool lldb_private::ThreadPlanSingleThreadTimeout::IsLeafPlan () inline override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 71 of file ThreadPlanSingleThreadTimeout.h.
IsTimeoutAsyncInterrupt()
bool ThreadPlanSingleThreadTimeout::IsTimeoutAsyncInterrupt (Event * event_ptr) private
Definition at line 208 of file ThreadPlanSingleThreadTimeout.cpp.
References AsyncInterrupt, lldb::eStateStopped, lldb::eStopReasonInterrupt, lldb_private::GetLog(), lldb_private::Process::ProcessEventData::GetStateFromEvent(), lldb_private::Thread::GetStopInfo(), lldb_private::ThreadPlan::GetThread(), LLDB_LOGF, m_state, lldb_private::StateAsCString(), and lldb_private::Step.
Referenced by DoPlanExplainsStop(), and HandleEvent().
MischiefManaged()
bool ThreadPlanSingleThreadTimeout::MischiefManaged () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 184 of file ThreadPlanSingleThreadTimeout.cpp.
References lldb_private::GetLog(), LLDB_LOGF, and lldb_private::Step.
operator=()
const ThreadPlanSingleThreadTimeout & lldb_private::ThreadPlanSingleThreadTimeout::operator= (const ThreadPlanSingleThreadTimeout &) private delete
References ThreadPlanSingleThreadTimeout().
PushNewWithTimeout()
void ThreadPlanSingleThreadTimeout::PushNewWithTimeout (Thread & thread, TimeoutInfoSP & info) static
Definition at line 69 of file ThreadPlanSingleThreadTimeout.cpp.
References lldb_private::GetLog(), LLDB_LOGF, lldb_private::Step, and ThreadPlanSingleThreadTimeout().
Referenced by lldb_private::TimeoutResumeAll::PushNewTimeout().
ResumeFromPrevState()
void ThreadPlanSingleThreadTimeout::ResumeFromPrevState (Thread & thread, TimeoutInfoSP & info) static
Definition at line 94 of file ThreadPlanSingleThreadTimeout.cpp.
References lldb_private::GetLog(), LLDB_LOGF, lldb_private::Step, and ThreadPlanSingleThreadTimeout().
Referenced by lldb_private::TimeoutResumeAll::ResumeWithTimeout().
SetStopOthers()
void ThreadPlanSingleThreadTimeout::SetStopOthers (bool new_value) override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 195 of file ThreadPlanSingleThreadTimeout.cpp.
References lldb_private::ThreadPlan::GetPreviousPlan(), and lldb_private::ThreadPlan::SetStopOthers().
ShouldStop()
bool ThreadPlanSingleThreadTimeout::ShouldStop (Event * event_ptr) override virtual
Implements lldb_private::ThreadPlan.
Definition at line 191 of file ThreadPlanSingleThreadTimeout.cpp.
References HandleEvent().
StateToString()
std::string ThreadPlanSingleThreadTimeout::StateToString (State state) static private
Definition at line 57 of file ThreadPlanSingleThreadTimeout.cpp.
References AsyncInterrupt, Done, and WaitTimeout.
Referenced by GetDescription().
StopOthers()
bool ThreadPlanSingleThreadTimeout::StopOthers () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 201 of file ThreadPlanSingleThreadTimeout.cpp.
References Done, lldb_private::ThreadPlan::GetPreviousPlan(), m_state, and lldb_private::ThreadPlan::StopOthers().
TimeoutThreadFunc()
void ThreadPlanSingleThreadTimeout::TimeoutThreadFunc (ThreadPlanSingleThreadTimeout * self) static
Definition at line 159 of file ThreadPlanSingleThreadTimeout.cpp.
References lldb_private::GetLog(), lldb_private::ThreadProperties::GetSingleThreadPlanTimeout(), lldb_private::ThreadPlan::GetThread(), HandleTimeout(), LLDB_LOGF, m_info, m_mutex, m_timeout_start, m_wakeup_cv, lldb_private::Step, and ThreadPlanSingleThreadTimeout().
Referenced by ThreadPlanSingleThreadTimeout().
ValidatePlan()
bool lldb_private::ThreadPlanSingleThreadTimeout::ValidatePlan (Stream * error) inline override virtual
Returns whether this plan could be successfully created.
Parameters
[in] error A stream to which to print some reason why the plan could not be created. Can be NULL.
Returns
true if the plan should be queued, false otherwise.
Implements lldb_private::ThreadPlan.
Definition at line 67 of file ThreadPlanSingleThreadTimeout.h.
References error().
WillStop()
bool ThreadPlanSingleThreadTimeout::WillStop () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 123 of file ThreadPlanSingleThreadTimeout.cpp.
References lldb_private::GetLog(), LLDB_LOGF, m_info, lldb_private::Step, and WaitTimeout.
Member Data Documentation
m_info
TimeoutInfoSP lldb_private::ThreadPlanSingleThreadTimeout::m_info private
Definition at line 97 of file ThreadPlanSingleThreadTimeout.h.
Referenced by DidPop(), ThreadPlanSingleThreadTimeout(), TimeoutThreadFunc(), WillStop(), and ~ThreadPlanSingleThreadTimeout().
m_mutex
std::mutex lldb_private::ThreadPlanSingleThreadTimeout::m_mutex private
Definition at line 102 of file ThreadPlanSingleThreadTimeout.h.
Referenced by DidPop(), and TimeoutThreadFunc().
m_state
State lldb_private::ThreadPlanSingleThreadTimeout::m_state private
Definition at line 98 of file ThreadPlanSingleThreadTimeout.h.
Referenced by GetDescription(), HandleEvent(), HandleTimeout(), IsTimeoutAsyncInterrupt(), StopOthers(), and ThreadPlanSingleThreadTimeout().
m_timeout_start
std::chrono::steady_clock::time_point lldb_private::ThreadPlanSingleThreadTimeout::m_timeout_start private
Definition at line 105 of file ThreadPlanSingleThreadTimeout.h.
Referenced by GetRemainingTimeoutMilliSeconds(), and TimeoutThreadFunc().
m_timer_thread
std::thread lldb_private::ThreadPlanSingleThreadTimeout::m_timer_thread private
Definition at line 104 of file ThreadPlanSingleThreadTimeout.h.
Referenced by DidPop(), and ThreadPlanSingleThreadTimeout().
m_wakeup_cv
std::condition_variable lldb_private::ThreadPlanSingleThreadTimeout::m_wakeup_cv private
Definition at line 103 of file ThreadPlanSingleThreadTimeout.h.
Referenced by DidPop(), and TimeoutThreadFunc().
The documentation for this class was generated from the following files:
ThreadPlanSingleThreadTimeout.h
ThreadPlanSingleThreadTimeout.cpp