LLDB: lldb_private::process_gdb_remote::ProcessGDBRemote Class Reference
lldb_private::process_gdb_remote::ProcessGDBRemote Class Reference
#include <ProcessGDBRemote.h>
Classes
struct ModuleCacheInfo
Public Member Functions
~ProcessGDBRemote () override
ArchSpec GetSystemArchitecture () override
Get the system architecture for this process.
bool CanDebug (lldb::TargetSP target_sp, bool plugin_specified_by_name) override
Check if a plug-in instance can debug the file in module.
CommandObject * GetPluginCommandObject () override
Return a multi-word command object that can be used to expose plug-in specific commands.
void DumpPluginHistory (Stream &s) override
The underlying plugin might store the low-level communication history for this session.
Status DoWillLaunch (Module *module) override
Called before launching to a process.
Status DoLaunch (Module *exe_module, ProcessLaunchInfo &launch_info) override
Launch a new process.
void DidLaunch () override
Called after launching a process.
Status DoWillAttachToProcessWithID (lldb::pid_t pid) override
Called before attaching to a process.
Status DoWillAttachToProcessWithName (const char *process_name, bool wait_for_launch) override
Called before attaching to a process.
Status DoConnectRemote (llvm::StringRef remote_url) override
Attach to a remote system via a URL.
Status WillLaunchOrAttach ()
Status DoAttachToProcessWithID (lldb::pid_t pid, const ProcessAttachInfo &attach_info) override
Attach to an existing process using a process ID.
Status DoAttachToProcessWithName (const char *process_name, const ProcessAttachInfo &attach_info) override
Attach to an existing process using a partial process name.
void DidAttach (ArchSpec &process_arch) override
Called after attaching a process.
llvm::StringRef GetPluginName () override
Status WillResume () override
Called before resuming to a process.
bool SupportsReverseDirection () override
Reports whether this process supports reverse execution.
Status DoResume (lldb::RunDirection direction) override
Resumes all of a process's threads as configured using the Thread run control functions.
Status DoHalt (bool &caused_stop) override
Halts a running process.
Status DoDetach (bool keep_stopped) override
Detaches from a running or stopped process.
bool DetachRequiresHalt () override
Status DoSignal (int signal) override
Sends a process a UNIX signal signal.
Status DoDestroy () override
void RefreshStateAfterStop () override
Currently called as part of ShouldStop.
void SetUnixSignals (const lldb::UnixSignalsSP &signals_sp)
bool IsAlive () override
Check if a process is still alive.
lldb::addr_t GetImageInfoAddress () override
Get the image information address for the current process.
void WillPublicStop () override
Called when the process is about to broadcast a public stop.
size_t DoReadMemory (lldb::addr_t addr, void *buf, size_t size, Status &error) override
Actually do the reading of memory from a process.
llvm::SmallVector< llvm::MutableArrayRef< uint8_t > > ReadMemoryRanges (llvm::ArrayRef< Range< lldb::addr_t, size_t > > ranges, llvm::MutableArrayRef< uint8_t > buf) override
Override of ReadMemoryRanges that uses MultiMemRead to optimize this operation.
Status WriteObjectFile (std::vector< ObjectFile::LoadableData > entries) override
size_t DoWriteMemory (lldb::addr_t addr, const void *buf, size_t size, Status &error) override
Actually do the writing of memory to a process.
lldb::addr_t DoAllocateMemory (size_t size, uint32_t permissions, Status &error) override
Actually allocate memory in the process.
Status DoDeallocateMemory (lldb::addr_t ptr) override
Actually deallocate memory in the process.
size_t PutSTDIN (const char *buf, size_t buf_size, Status &error) override
Puts data into this process's STDIN.
Status EnableBreakpointSite (BreakpointSite *bp_site) override
Status DisableBreakpointSite (BreakpointSite *bp_site) override
Status EnableWatchpoint (lldb::WatchpointSP wp_sp, bool notify=true) override
Status DisableWatchpoint (lldb::WatchpointSP wp_sp, bool notify=true) override
std::optional< uint32_t > GetWatchpointSlotCount () override
Get the number of watchpoints supported by this target.
llvm::Expected< TraceSupportedResponse > TraceSupported () override
Get the processor tracing type supported for this process.
llvm::Error TraceStop (const TraceStopRequest &request) override
Stop tracing a live process or its threads.
llvm::Error TraceStart (const llvm::json::Value &request) override
Start tracing a process or its threads.
llvm::Expected< std::string > TraceGetState (llvm::StringRef type) override
Get the current tracing state of the process and its threads.
llvm::Expected< std::vector< uint8_t > > TraceGetBinaryData (const TraceGetBinaryDataRequest &request) override
Get binary data given a trace technology and a data identifier.
std::optional< bool > DoGetWatchpointReportedAfter () override
Provide an override value in the subclass for lldb's CPU-based logic for whether watchpoint exceptions are received before or after an instruction executes.
bool StartNoticingNewThreads () override
Call this to set the lldb in the mode where it breaks on new thread creations, and then auto-restarts.
bool StopNoticingNewThreads () override
Call this to turn off the stop & notice new threads mode.
GDBRemoteCommunicationClient & GetGDBRemote ()
Status SendEventData (const char *data) override
void DidExit () override
void SetUserSpecifiedMaxMemoryTransferSize (uint64_t user_specified_max)
bool GetModuleSpec (const FileSpec &module_file_spec, const ArchSpec &arch, ModuleSpec &module_spec) override
Try to fetch the module specification for a module with the given file name and architecture.
void PrefetchModuleSpecs (llvm::ArrayRef< FileSpec > module_file_specs, const llvm::Triple &triple) override
llvm::VersionTuple GetHostOSVersion () override
Sometimes the connection to a process can detect the host OS version that the process is running on.
llvm::VersionTuple GetHostMacCatalystVersion () override
llvm::Error LoadModules () override
Sometimes processes know how to retrieve and load shared libraries.
llvm::Expected< LoadedModuleInfoList > GetLoadedModuleList () override
Query remote GDBServer for a detailed loaded library list.
Status GetFileLoadAddress (const FileSpec &file, bool &is_loaded, lldb::addr_t &load_addr) override
Try to find the load address of a file.
void ModulesDidLoad (ModuleList &module_list) override
StructuredData::ObjectSP GetLoadedDynamicLibrariesInfos (lldb::addr_t image_list_address, lldb::addr_t image_count) override
Retrieve the list of shared libraries that are loaded for this process This method is used on pre-macOS 10.12, pre-iOS 10, pre-tvOS 10, pre- watchOS 3 systems.
Status ConfigureStructuredData (llvm::StringRef type_name, const StructuredData::ObjectSP &config_sp) override
Configure asynchronous structured data feature.
StructuredData::ObjectSP GetLoadedDynamicLibrariesInfos () override
StructuredData::ObjectSP GetLoadedDynamicLibrariesInfos (const std::vector< lldb::addr_t > &load_addresses) override
StructuredData::ObjectSP GetLoadedDynamicLibrariesInfos_sender (StructuredData::ObjectSP args)
StructuredData::ObjectSP GetSharedCacheInfo () override
StructuredData::ObjectSP GetDynamicLoaderProcessState () override
std::string HarmonizeThreadIdsForProfileData (StringExtractorGDBRemote &inputStringExtractor)
void DidFork (lldb::pid_t child_pid, lldb::tid_t child_tid) override
Called after a reported fork.
void DidVFork (lldb::pid_t child_pid, lldb::tid_t child_tid) override
Called after a reported vfork.
void DidVForkDone () override
Called after reported vfork completion.
void DidExec () override
Called after a process re-execs itself.
llvm::Expected< bool > SaveCore (llvm::StringRef outfile) override
Save core dump into the specified file.
Public Member Functions inherited from lldb_private::Process
llvm::StringRef GetBroadcasterClass () const override
This needs to be filled in if you are going to register the broadcaster with the broadcaster manager and do broadcaster class matching.
~Process () override
Destructor.
lldb::ByteOrder GetByteOrder () const
uint32_t GetAddressByteSize () const
lldb::pid_t GetID () const
Returns the pid of the process or LLDB_INVALID_PROCESS_ID if there is no known pid.
void SetID (lldb::pid_t new_pid)
Sets the stored pid.
uint32_t GetUniqueID () const
virtual void Finalize (bool destructing)
This object is about to be destroyed, do any necessary cleanup.
bool IsValid () const
Return whether this object is valid (i.e.
virtual Status Launch (ProcessLaunchInfo &launch_info)
Launch a new process.
virtual Status LoadCore ()
virtual Status DoLoadCore ()
void SetShadowListener (lldb::ListenerSP shadow_listener_sp)
The "ShadowListener" for a process is just an ordinary Listener that listens for all the Process event bits.
UtilityFunction * GetLoadImageUtilityFunction (Platform *platform, llvm::function_ref< std::unique_ptr< UtilityFunction >()> factory)
Get the cached UtilityFunction that assists in loading binary images into the process.
void SetDynamicLoader (lldb::DynamicLoaderUP dyld)
Status CalculateCoreFileSaveRanges (const SaveCoreOptions &core_options, CoreFileMemoryRanges &ranges)
Helper function for Process::SaveCore(...) that calculates the address ranges that should be saved.
std::vector< lldb::ThreadSP > CalculateCoreFileThreadList (const SaveCoreOptions &core_options)
Helper function for Process::SaveCore(...) that calculates the thread list based upon options set within a given core_options object.
virtual SystemRuntime * GetSystemRuntime ()
Get the system runtime plug-in for this process.
virtual Status Attach (ProcessAttachInfo &attach_info)
Attach to an existing process using the process attach info.
virtual Status ConnectRemote (llvm::StringRef remote_url)
Attach to a remote system via a URL.
bool GetShouldDetach () const
void SetShouldDetach (bool b)
const std::vector< lldb::addr_t > & GetImageTokens ()
Get the image vector for the current process.
void RegisterNotificationCallbacks (const Process::Notifications &callbacks)
Register for process and thread notifications.
bool UnregisterNotificationCallbacks (const Process::Notifications &callbacks)
Unregister for process and thread notifications.
Status Resume ()
Resumes all of a process's threads as configured using the Thread run control functions.
Status ResumeSynchronous (Stream *stream)
Resume a process, and wait for it to stop.
Status Halt (bool clear_thread_plans=false, bool use_run_lock=true)
Halts a running process.
Status Detach (bool keep_stopped)
Detaches from a running or stopped process.
Status Destroy (bool force_kill)
Kills the process and shuts down all threads that were spawned to track and monitor the process.
Status Signal (int signal)
Sends a process a UNIX signal signal.
void SetUnixSignals (lldb::UnixSignalsSP &&signals_sp)
const lldb::UnixSignalsSP & GetUnixSignals ()
Status WillAttachToProcessWithID (lldb::pid_t pid)
Called before attaching to a process.
Status WillAttachToProcessWithName (const char *process_name, bool wait_for_launch)
Called before attaching to a process.
virtual void DoDidExec ()
Subclasses of Process should implement this function if they need to do anything after a process exec's itself.
Status WillLaunch (Module *module)
Called before launching to a process.
virtual void DidResume ()
Called after resuming a process.
virtual Status WillHalt ()
Called before halting to a process.
virtual void DidHalt ()
Called after halting a process.
virtual Status WillDetach ()
Called before detaching from a process.
virtual void DidDetach ()
Called after detaching from a process.
virtual Status WillSignal ()
Called before sending a signal to a process.
virtual Status WillDestroy ()
virtual void DidDestroy ()
virtual bool DestroyRequiresHalt ()
virtual void DidSignal ()
Called after sending a signal to a process.
Target & GetTarget ()
Get the target object pointer for this module.
const Target & GetTarget () const
Get the const target object pointer for this module.
void Flush ()
Flush all data in the process.
lldb::StateType GetState ()
Get accessor for the current process state.
lldb::ExpressionResults RunThreadPlan (ExecutionContext &exe_ctx, lldb::ThreadPlanSP &thread_plan_sp, const EvaluateExpressionOptions &options, DiagnosticManager &diagnostic_manager)
void GetStatus (Stream &ostrm)
size_t GetThreadStatus (Stream &ostrm, bool only_threads_with_stop_reason, uint32_t start_frame, uint32_t num_frames, uint32_t num_frames_with_source, bool stop_format)
void SendAsyncInterrupt (Thread *thread=nullptr)
Send an async interrupt request.
void PrintWarningOptimization (const SymbolContext &sc)
Print a user-visible warning about a module being built with optimization.
void PrintWarningUnsupportedLanguage (const SymbolContext &sc)
Print a user-visible warning about a function written in a language that this version of LLDB doesn't support.
virtual bool GetProcessInfo (ProcessInstanceInfo &info)
virtual lldb_private::UUID FindModuleUUID (const llvm::StringRef path)
int GetExitStatus ()
Get the exit status for a process.
const char * GetExitDescription ()
Get a textual description of what the process exited.
lldb::addr_t GetCodeAddressMask ()
Get the current address mask in the Process.
lldb::addr_t GetDataAddressMask ()
lldb::addr_t GetHighmemCodeAddressMask ()
The highmem masks are for targets where we may have different masks for low memory versus high memory addresses, and they will be left as LLDB_INVALID_ADDRESS_MASK normally, meaning the base masks should be applied to all addresses.
lldb::addr_t GetHighmemDataAddressMask ()
void SetCodeAddressMask (lldb::addr_t code_address_mask)
void SetDataAddressMask (lldb::addr_t data_address_mask)
void SetHighmemCodeAddressMask (lldb::addr_t code_address_mask)
void SetHighmemDataAddressMask (lldb::addr_t data_address_mask)
lldb::addr_t FixCodeAddress (lldb::addr_t pc)
Some targets might use bits in a code address to indicate a mode switch, ARM uses bit zero to signify a code address is thumb, so any ARM ABI plug-ins would strip those bits.
lldb::addr_t FixDataAddress (lldb::addr_t pc)
lldb::addr_t FixAnyAddress (lldb::addr_t pc)
Use this method when you do not know, or do not care what kind of address you are fixing.
ProcessModID GetModID () const
Get the Modification ID of the process.
const ProcessModID & GetModIDRef () const
uint32_t GetStopID () const
uint32_t GetResumeID () const
uint32_t GetLastUserExpressionResumeID () const
uint32_t GetLastNaturalStopID () const
lldb::EventSP GetStopEventForStopID (uint32_t stop_id) const
virtual bool SetExitStatus (int exit_status, llvm::StringRef exit_string)
Set accessor for the process exit status (return code).
virtual bool IsLiveDebugSession () const
Check if a process is a live debug session, or a corefile/post-mortem.
virtual FileSpec GetCoreFile () const
Provide a way to retrieve the core dump file that is loaded for debugging.
virtual bool WarnBeforeDetach () const
Before lldb detaches from a process, it warns the user that they are about to lose their debug session.
virtual size_t ReadMemory (lldb::addr_t vm_addr, void *buf, size_t size, Status &error)
Read of memory from a process.
size_t ReadMemoryFromInferior (lldb::addr_t vm_addr, void *buf, size_t size, Status &error)
Read of memory from a process.
lldb::offset_t ReadMemoryInChunks (lldb::addr_t vm_addr, void *buf, lldb::addr_t chunk_size, lldb::offset_t total_size, ReadMemoryChunkCallback callback)
Read of memory from a process in discrete chunks, terminating either when all bytes are read, or the supplied callback returns IterationAction::Stop.
size_t ReadCStringFromMemory (lldb::addr_t vm_addr, char *cstr, size_t cstr_max_len, Status &error)
Read a NULL terminated C string from memory.
size_t ReadCStringFromMemory (lldb::addr_t vm_addr, std::string &out_str, Status &error)
llvm::SmallVector< std::optional< std::string > > ReadCStringsFromMemory (llvm::ArrayRef< lldb::addr_t > addresses)
uint64_t ReadUnsignedIntegerFromMemory (lldb::addr_t load_addr, size_t byte_size, uint64_t fail_value, Status &error)
Reads an unsigned integer of the specified byte size from process memory.
int64_t ReadSignedIntegerFromMemory (lldb::addr_t load_addr, size_t byte_size, int64_t fail_value, Status &error)
lldb::addr_t ReadPointerFromMemory (lldb::addr_t vm_addr, Status &error)
bool WritePointerToMemory (lldb::addr_t vm_addr, lldb::addr_t ptr_value, Status &error)
size_t WriteScalarToMemory (lldb::addr_t vm_addr, const Scalar &scalar, size_t size, Status &error)
Write all or part of a scalar value to memory.
size_t ReadScalarIntegerFromMemory (lldb::addr_t addr, uint32_t byte_size, bool is_signed, Scalar &scalar, Status &error)
size_t WriteMemory (lldb::addr_t vm_addr, const void *buf, size_t size, Status &error)
Write memory to a process.
lldb::addr_t AllocateMemory (size_t size, uint32_t permissions, Status &error)
The public interface to allocating memory in the process.
lldb::addr_t CallocateMemory (size_t size, uint32_t permissions, Status &error)
The public interface to allocating memory in the process, this also clears the allocated memory.
llvm::Expected< const MemoryTagManager * > GetMemoryTagManager ()
If this architecture and process supports memory tagging, return a tag manager that can be used to maniupulate those memory tags.
virtual llvm::Expected< std::vector< lldb::addr_t > > ReadMemoryTags (lldb::addr_t addr, size_t len)
Read memory tags for the range addr to addr+len.
Status WriteMemoryTags (lldb::addr_t addr, size_t len, const std::vector< lldb::addr_t > &tags)
Write memory tags for a range of memory.
virtual lldb::addr_t ResolveIndirectFunction (const Address *address, Status &error)
Resolve dynamically loaded indirect functions.
Status GetMemoryRegionInfo (lldb::addr_t load_addr, MemoryRegionInfo &range_info)
Locate the memory region that contains load_addr.
virtual Status GetMemoryRegions (lldb_private::MemoryRegionInfos &region_list)
Obtain all the mapped memory regions within this process.
bool GetWatchpointReportedAfter ()
Whether lldb will be notified about watchpoints after the instruction has completed executing, or if the instruction is rolled back and it is notified before it executes.
llvm::Expected< lldb::ModuleSP > ReadModuleFromMemory (const FileSpec &file_spec, lldb::addr_t header_addr, size_t size_to_read=512)
Creates and populates a module using an in-memory object file.
virtual bool GetLoadAddressPermissions (lldb::addr_t load_addr, uint32_t &permissions)
Attempt to get the attributes for a region of memory in the process.
bool CanJIT ()
Determines whether executing JIT-compiled code in this process is possible.
void SetCanJIT (bool can_jit)
Sets whether executing JIT-compiled code in this process is possible.
bool CanInterpretFunctionCalls ()
Determines whether executing function calls using the interpreter is possible for this process.
void SetCanInterpretFunctionCalls (bool can_interpret_function_calls)
Sets whether executing function calls using the interpreter is possible for this process.
void SetCanRunCode (bool can_run_code)
Sets whether executing code in this process is possible.
Status DeallocateMemory (lldb::addr_t ptr)
The public interface to deallocating memory in the process.
virtual size_t GetSTDOUT (char *buf, size_t buf_size, Status &error)
Get any available STDOUT.
virtual size_t GetSTDERR (char *buf, size_t buf_size, Status &error)
Get any available STDERR.
virtual size_t GetAsyncProfileData (char *buf, size_t buf_size, Status &error)
Get any available profile data.
size_t GetSoftwareBreakpointTrapOpcode (BreakpointSite *bp_site)
virtual Status EnableSoftwareBreakpoint (BreakpointSite *bp_site)
virtual Status DisableSoftwareBreakpoint (BreakpointSite *bp_site)
StopPointSiteList< lldb_private::BreakpointSite > & GetBreakpointSiteList ()
const StopPointSiteList< lldb_private::BreakpointSite > & GetBreakpointSiteList () const
void DisableAllBreakpointSites ()
Status ClearBreakpointSiteByID (lldb::user_id_t break_id)
lldb::break_id_t CreateBreakpointSite (const lldb::BreakpointLocationSP &owner, bool use_hardware)
Status DisableBreakpointSiteByID (lldb::user_id_t break_id)
Status EnableBreakpointSiteByID (lldb::user_id_t break_id)
void RemoveConstituentFromBreakpointSite (lldb::user_id_t site_id, lldb::user_id_t constituent_id, lldb::BreakpointSiteSP &bp_site_sp)
bool UpdateThreadList (ThreadList &old_thread_list, ThreadList &new_thread_list)
Update the thread list.
void UpdateThreadListIfNeeded ()
ThreadList & GetThreadList ()
StopPointSiteList< lldb_private::WatchpointResource > & GetWatchpointResourceList ()
ThreadList & GetExtendedThreadList ()
ThreadList::ThreadIterable Threads ()
uint32_t GetNextThreadIndexID (uint64_t thread_id)
lldb::ThreadSP CreateOSPluginThread (lldb::tid_t tid, lldb::addr_t context)
bool HasAssignedIndexIDToThread (uint64_t sb_thread_id)
uint32_t AssignIndexIDToThread (uint64_t thread_id)
virtual void UpdateQueueListIfNeeded ()
QueueList & GetQueueList ()
QueueList::QueueIterable Queues ()
lldb::StateType GetNextEvent (lldb::EventSP &event_sp)
lldb::StateType WaitForProcessToStop (const Timeout< std::micro > &timeout, lldb::EventSP *event_sp_ptr=nullptr, bool wait_always=true, lldb::ListenerSP hijack_listener=lldb::ListenerSP(), Stream *stream=nullptr, bool use_run_lock=true, SelectMostRelevant select_most_relevant=DoNoSelectMostRelevantFrame)
uint32_t GetIOHandlerID () const
void SyncIOHandler (uint32_t iohandler_id, const Timeout< std::micro > &timeout)
Waits for the process state to be running within a given msec timeout.
lldb::StateType GetStateChangedEvents (lldb::EventSP &event_sp, const Timeout< std::micro > &timeout, lldb::ListenerSP hijack_listener)
Event * PeekAtStateChangedEvents ()
bool HijackProcessEvents (lldb::ListenerSP listener_sp)
If you need to ensure that you and only you will hear about some public event, then make a new listener, set to listen to process events, and then call this with that listener.
void RestoreProcessEvents ()
Restores the process event broadcasting to its normal state.
bool StateChangedIsHijackedForSynchronousResume ()
bool StateChangedIsExternallyHijacked ()
const lldb::ABISP & GetABI ()
OperatingSystem * GetOperatingSystem ()
std::vector< LanguageRuntime * > GetLanguageRuntimes ()
LanguageRuntime * GetLanguageRuntime (lldb::LanguageType language)
bool IsPossibleDynamicValue (ValueObject &in_value)
bool IsRunning () const
DynamicCheckerFunctions * GetDynamicCheckers ()
void SetDynamicCheckers (DynamicCheckerFunctions *dynamic_checkers)
bool PruneThreadPlansForTID (lldb::tid_t tid)
Prune ThreadPlanStacks for unreported threads.
void PruneThreadPlans ()
Prune ThreadPlanStacks for all unreported threads.
ThreadPlanStack * FindThreadPlans (lldb::tid_t tid)
Find the thread plan stack associated with thread with tid.
bool DumpThreadPlansForTID (Stream &strm, lldb::tid_t tid, lldb::DescriptionLevel desc_level, bool internal, bool condense_trivial, bool skip_unreported_plans)
Dump the thread plans associated with thread with tid.
void DumpThreadPlans (Stream &strm, lldb::DescriptionLevel desc_level, bool internal, bool condense_trivial, bool skip_unreported_plans)
Dump all the thread plans for this process.
void SetRunningUserExpression (bool on)
void SetRunningUtilityFunction (bool on)
lldb::TargetSP CalculateTarget () override
lldb::ProcessSP CalculateProcess () override
lldb::ThreadSP CalculateThread () override
lldb::StackFrameSP CalculateStackFrame () override
void CalculateExecutionContext (ExecutionContext &exe_ctx) override
Reconstruct the object's execution context into sc.
void SetSTDIOFileDescriptor (int file_descriptor)
Associates a file descriptor with the process' STDIO handling and configures an asynchronous reading of that descriptor.
void AddInvalidMemoryRegion (const LoadRange &region)
bool RemoveInvalidMemoryRange (const LoadRange &region)
void AddPreResumeAction (PreResumeActionCallback callback, void *baton)
bool RunPreResumeActions ()
void ClearPreResumeActions ()
void ClearPreResumeAction (PreResumeActionCallback callback, void *baton)
ProcessRunLock & GetRunLock ()
bool CurrentThreadIsPrivateStateThread ()
bool CurrentThreadPosesAsPrivateStateThread ()
lldb::ThreadCollectionSP GetHistoryThreads (lldb::addr_t addr)
lldb::InstrumentationRuntimeSP GetInstrumentationRuntime (lldb::InstrumentationRuntimeType type)
virtual StructuredData::DictionarySP GetMetadata ()
Fetch process defined metadata.
StructuredData::DictionarySP GetExtendedCrashInfoDict ()
Fetch extended crash information held by the process.
void ResetExtendedCrashInfoDict ()
size_t AddImageToken (lldb::addr_t image_ptr)
lldb::addr_t GetImagePtrFromToken (size_t token) const
void ResetImageToken (size_t token)
Address AdvanceAddressToNextBranchInstruction (Address default_stop_addr, AddressRange range_bounds)
Find the next branch instruction to set a breakpoint on.
void BroadcastStructuredData (const StructuredData::ObjectSP &object_sp, const lldb::StructuredDataPluginSP &plugin_sp)
Broadcasts the given structured data object from the given plugin.
lldb::StructuredDataPluginSP GetStructuredDataPlugin (llvm::StringRef type_name) const
Returns the StructuredDataPlugin associated with a given type name, if there is one.
virtual void * GetImplementation ()
virtual void ForceScriptedState (lldb::StateType state)
SourceManager::SourceFileCache & GetSourceFileCache ()
lldb::addr_t FindInMemory (lldb::addr_t low, lldb::addr_t high, const uint8_t *buf, size_t size)
Find a pattern within a memory region.
AddressRanges FindRangesInMemory (const uint8_t *buf, uint64_t size, const AddressRanges &ranges, size_t alignment, size_t max_matches, Status &error)
lldb::addr_t FindInMemory (const uint8_t *buf, uint64_t size, const AddressRange &range, size_t alignment, Status &error)
lldb::RunDirection GetBaseDirection () const
Get the base run direction for the process.
void SetBaseDirection (lldb::RunDirection direction)
Set the base run direction for the process.
Public Member Functions inherited from lldb_private::ProcessProperties
ProcessProperties (lldb_private::Process *process)
~ProcessProperties () override
bool GetDisableMemoryCache () const
uint64_t GetMemoryCacheLineSize () const
Args GetExtraStartupCommands () const
void SetExtraStartupCommands (const Args &args)
FileSpec GetPythonOSPluginPath () const
uint32_t GetVirtualAddressableBits () const
void SetVirtualAddressableBits (uint32_t bits)
uint32_t GetHighmemVirtualAddressableBits () const
void SetHighmemVirtualAddressableBits (uint32_t bits)
void SetPythonOSPluginPath (const FileSpec &file)
bool GetIgnoreBreakpointsInExpressions () const
void SetIgnoreBreakpointsInExpressions (bool ignore)
bool GetUnwindOnErrorInExpressions () const
void SetUnwindOnErrorInExpressions (bool ignore)
bool GetStopOnSharedLibraryEvents () const
void SetStopOnSharedLibraryEvents (bool stop)
bool GetDisableLangRuntimeUnwindPlans () const
void SetDisableLangRuntimeUnwindPlans (bool disable)
void DisableLanguageRuntimeUnwindPlansCallback ()
bool GetDetachKeepsStopped () const
void SetDetachKeepsStopped (bool keep_stopped)
bool GetWarningsOptimization () const
bool GetWarningsUnsupportedLanguage () const
bool GetStopOnExec () const
std::chrono::seconds GetUtilityExpressionTimeout () const
std::chrono::seconds GetInterruptTimeout () const
bool GetOSPluginReportsAllThreads () const
void SetOSPluginReportsAllThreads (bool does_report)
bool GetSteppingRunsAllThreads () const
FollowForkMode GetFollowForkMode () const
bool TrackMemoryCacheChanges () const
Public Member Functions inherited from lldb_private::Properties
Properties ()
Properties (const lldb::OptionValuePropertiesSP &collection_sp)
virtual ~Properties ()
lldb::OptionValuePropertiesSP GetValueProperties () const
virtual lldb::OptionValueSP GetPropertyValue (const ExecutionContext *exe_ctx, llvm::StringRef property_path, Status &error) const
virtual Status SetPropertyValue (const ExecutionContext *exe_ctx, VarSetOperationType op, llvm::StringRef property_path, llvm::StringRef value)
virtual Status DumpPropertyValue (const ExecutionContext *exe_ctx, Stream &strm, llvm::StringRef property_path, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllPropertyValues (const ExecutionContext *exe_ctx, Stream &strm, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllDescriptions (CommandInterpreter &interpreter, Stream &strm) const
size_t Apropos (llvm::StringRef keyword, std::vector< const Property * > &matching_properties) const
template<typename T>
T GetPropertyAtIndexAs (uint32_t idx, T default_value, const ExecutionContext *exe_ctx=nullptr) const
template<typename T, typename U = typename std::remove_pointer<T>::type, std::enable_if_t< std::is_pointer_v< T >, bool > = true>
const U * GetPropertyAtIndexAs (uint32_t idx, const ExecutionContext *exe_ctx=nullptr) const
template<typename T>
bool SetPropertyAtIndex (uint32_t idx, T t, const ExecutionContext *exe_ctx=nullptr) const
Public Member Functions inherited from lldb_private::Broadcaster
Broadcaster (lldb::BroadcasterManagerSP manager_sp, std::string name)
Construct with a broadcaster with a name.
virtual ~Broadcaster ()
Destructor.
void CheckInWithManager ()
void BroadcastEvent (lldb::EventSP &event_sp)
Broadcast an event which has no associated data.
void BroadcastEventIfUnique (lldb::EventSP &event_sp)
void BroadcastEvent (uint32_t event_type, const lldb::EventDataSP &event_data_sp)
void BroadcastEvent (uint32_t event_type)
void BroadcastEventIfUnique (uint32_t event_type)
void Clear ()
virtual void AddInitialEventsToListener (const lldb::ListenerSP &listener_sp, uint32_t requested_events)
uint32_t AddListener (const lldb::ListenerSP &listener_sp, uint32_t event_mask)
Listen for any events specified by event_mask.
const std::string & GetBroadcasterName ()
Get this broadcaster's name.
bool GetEventNames (Stream &s, const uint32_t event_mask, bool prefix_with_broadcaster_name) const
Get the event name(s) for one or more event bits.
void SetEventName (uint32_t event_mask, const char *name)
Set the name for an event bit.
const char * GetEventName (uint32_t event_mask) const
bool EventTypeHasListeners (uint32_t event_type)
bool RemoveListener (const lldb::ListenerSP &listener_sp, uint32_t event_mask=UINT32_MAX)
Removes a Listener from this broadcasters list and frees the event bits specified by event_mask that were previously acquired by listener (assuming listener was listening to this object) for other listener objects to use.
bool HijackBroadcaster (const lldb::ListenerSP &listener_sp, uint32_t event_mask=UINT32_MAX)
Provides a simple mechanism to temporarily redirect events from broadcaster.
bool IsHijackedForEvent (uint32_t event_mask)
void RestoreBroadcaster ()
Restore the state of the Broadcaster from a previous hijack attempt.
lldb::BroadcasterManagerSP GetManager ()
void SetPrimaryListener (lldb::ListenerSP listener_sp)
lldb::ListenerSP GetPrimaryListener ()
Public Member Functions inherited from lldb_private::ExecutionContextScope
virtual ~ExecutionContextScope ()=default
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static lldb::ProcessSP CreateInstance (lldb::TargetSP target_sp, lldb::ListenerSP listener_sp, const FileSpec *crash_file_path, bool can_connect)
static void Initialize ()
static void DebuggerInitialize (Debugger &debugger)
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static std::chrono::seconds GetPacketTimeout ()
Static Public Member Functions inherited from lldb_private::Process
static llvm::StringRef GetStaticBroadcasterClass ()
static void SettingsInitialize ()
static void SettingsTerminate ()
static ProcessProperties & GetGlobalProperties ()
static lldb::ProcessSP FindPlugin (lldb::TargetSP target_sp, llvm::StringRef plugin_name, lldb::ListenerSP listener_sp, const FileSpec *crash_file_path, bool can_connect)
Find a Process plug-in that can debug module using the currently selected architecture.
static bool SetProcessExitStatus (lldb::pid_t pid, bool exited, int signo, int status)
Static function that can be used with the host function Host::StartMonitoringChildProcess ().
static bool HandleProcessStateChangedEvent (const lldb::EventSP &event_sp, Stream *stream, SelectMostRelevant select_most_relevant, bool &pop_process_io_handler)
Centralize the code that handles and prints descriptions for process state changes.
Static Public Member Functions inherited from lldb_private::Properties
static llvm::StringRef GetExperimentalSettingsName ()
static bool IsSettingExperimental (llvm::StringRef setting)
Protected Types
enum { eBroadcastBitAsyncContinue = (1 << 0) , eBroadcastBitAsyncThreadShouldExit = (1 << 1) , eBroadcastBitAsyncThreadDidExit = (1 << 2) }
Broadcaster event bits definitions.
typedef std::vector< lldb::tid_t > tid_collection
typedef std::vector< std::pair< lldb::tid_t, int > > tid_sig_collection
typedef std::map< lldb::addr_t, lldb::addr_t > MMapMap
typedef std::map< uint32_t, std::string > ExpeditedRegisterMap
using FlashRangeVector = lldb_private::RangeVector<lldb::addr_t, size_t>
using FlashRange = FlashRangeVector::Entry
Protected Types inherited from lldb_private::Process
enum { eCanJITDontKnow = 0 , eCanJITYes , eCanJITNo }
typedef std::map< lldb::LanguageType, lldb::LanguageRuntimeSP > LanguageRuntimeCollection
Protected Types inherited from lldb_private::Broadcaster
typedef std::shared_ptr< BroadcasterImpl > BroadcasterImplSP
typedef std::weak_ptr< BroadcasterImpl > BroadcasterImplWP
Protected Member Functions
ProcessGDBRemote (lldb::TargetSP target_sp, lldb::ListenerSP listener_sp)
virtual std::shared_ptr< ThreadGDBRemote > CreateThread (lldb::tid_t tid)
bool SupportsMemoryTagging () override
Check whether the process supports memory tagging.
bool IsRunning (lldb::StateType state)
bool IsStepping (lldb::StateType state)
bool CanResume (lldb::StateType state)
bool HasExited (lldb::StateType state)
void Clear ()
bool DoUpdateThreadList (ThreadList &old_thread_list, ThreadList &new_thread_list) override
Update the thread list following process plug-in's specific logic.
Status EstablishConnectionIfNeeded (const ProcessInfo &process_info)
Status LaunchAndConnectToDebugserver (const ProcessInfo &process_info)
void KillDebugserverProcess ()
void BuildDynamicRegisterInfo (bool force)
void SetLastStopPacket (const StringExtractorGDBRemote &response)
bool ParsePythonTargetDefinition (const FileSpec &target_definition_fspec)
DataExtractor GetAuxvData () override
StructuredData::ObjectSP GetExtendedInfoForThread (lldb::tid_t tid)
void GetMaxMemorySize ()
bool CalculateThreadStopInfo (ThreadGDBRemote *thread)
size_t UpdateThreadPCsFromStopReplyThreadsValue (llvm::StringRef value)
size_t UpdateThreadIDsFromStopReplyThreadsValue (llvm::StringRef value)
bool StartAsyncThread ()
void StopAsyncThread ()
lldb::thread_result_t AsyncThread ()
lldb::StateType SetThreadStopInfo (StringExtractor &stop_packet)
bool GetThreadStopInfoFromJSON (ThreadGDBRemote *thread, const StructuredData::ObjectSP &thread_infos_sp)
lldb::ThreadSP SetThreadStopInfo (StructuredData::Dictionary *thread_dict)
lldb::ThreadSP SetThreadStopInfo (lldb::tid_t tid, ExpeditedRegisterMap &expedited_register_map, uint8_t signo, const std::string &thread_name, const std::string &reason, const std::string &description, uint32_t exc_type, const std::vector< lldb::addr_t > &exc_data, lldb::addr_t thread_dispatch_qaddr, bool queue_vars_valid, lldb_private::LazyBool associated_with_libdispatch_queue, lldb::addr_t dispatch_queue_t, std::string &queue_name, lldb::QueueKind queue_kind, uint64_t queue_serial)
void ClearThreadIDList ()
bool UpdateThreadIDList ()
void DidLaunchOrAttach (ArchSpec &process_arch)
void LoadStubBinaries ()
void MaybeLoadExecutableModule ()
Status ConnectToDebugserver (llvm::StringRef host_port)
const char * GetDispatchQueueNameForThread (lldb::addr_t thread_dispatch_qaddr, std::string &dispatch_queue_name)
DynamicLoader * GetDynamicLoader () override
Get the dynamic loader plug-in for this process.
bool GetGDBServerRegisterInfoXMLAndProcess (ArchSpec &arch_to_use, std::string xml_filename, std::vector< DynamicRegisterInfo::Register > &registers)
void AddRemoteRegisters (std::vector< DynamicRegisterInfo::Register > &registers, const ArchSpec &arch_to_use)
llvm::Error GetGDBServerRegisterInfo (ArchSpec &arch)
lldb::ModuleSP LoadModuleAtAddress (const FileSpec &file, lldb::addr_t link_map, lldb::addr_t base_addr, bool value_is_offset)
Status UpdateAutomaticSignalFiltering () override
Status FlashErase (lldb::addr_t addr, size_t size)
Status FlashDone ()
bool HasErased (FlashRange range)
llvm::Expected< std::vector< uint8_t > > DoReadMemoryTags (lldb::addr_t addr, size_t len, int32_t type) override
Does the final operation to read memory tags.
Status DoWriteMemoryTags (lldb::addr_t addr, size_t len, int32_t type, const std::vector< uint8_t > &tags) override
Does the final operation to write memory tags.
Status DoGetMemoryRegionInfo (lldb::addr_t load_addr, MemoryRegionInfo &region_info) override
DoGetMemoryRegionInfo is called by GetMemoryRegionInfo after it has removed non address bits from load_addr.
Protected Member Functions inherited from lldb_private::Process
virtual JITLoaderList & GetJITLoaders ()
Process (lldb::TargetSP target_sp, lldb::ListenerSP listener_sp)
Construct with a shared pointer to a target, and the Process listener.
Process (lldb::TargetSP target_sp, lldb::ListenerSP listener_sp, const lldb::UnixSignalsSP &unix_signals_sp)
Construct with a shared pointer to a target, the Process listener, and the appropriate UnixSignalsSP for the process.
bool CallVoidArgVoidPtrReturn (const Address *address, lldb::addr_t &returned_func, bool trap_exceptions=false)
virtual void DoFindInMemory (lldb::addr_t start_addr, lldb::addr_t end_addr, const uint8_t *buf, size_t size, AddressRanges &matches, size_t alignment, size_t max_matches)
Status PrivateResume ()
The "private" side of resuming a process.
void CompleteAttach ()
void SetNextEventAction (Process::NextEventAction *next_event_action)
bool PrivateStateThreadIsRunning () const
void ForceNextEventDelivery ()
void MapSupportedStructuredDataPlugins (const StructuredData::Array &supported_type_names)
Loads any plugins associated with asynchronous structured data and maps the relevant supported type name to the plugin.
bool RouteAsyncStructuredData (const StructuredData::ObjectSP object_sp)
Route the incoming structured data dictionary to the right plugin.
bool SetPrivateRunLockToStopped ()
bool SetPrivateRunLockToRunning ()
bool SetPublicRunLockToStopped ()
bool SetPublicRunLockToRunning ()
std::recursive_mutex & GetPrivateStateMutex ()
lldb::StateType GetPublicState () const
lldb::StateType GetPrivateState () const
lldb::StateType GetPrivateStateNoLock () const
void SetPrivateStateNoLock (lldb::StateType new_state)
size_t RemoveBreakpointOpcodesFromBuffer (lldb::addr_t addr, size_t size, uint8_t *buf) const
void SynchronouslyNotifyStateChanged (lldb::StateType state)
void SetPublicState (lldb::StateType new_state, bool restarted)
void SetPrivateState (lldb::StateType state)
bool StartPrivateStateThread (lldb::StateType state, bool run_lock_is_running, bool is_secondary_thread=false)
void StopPrivateStateThread ()
void PausePrivateStateThread ()
void ResumePrivateStateThread ()
void HandlePrivateEvent (lldb::EventSP &event_sp)
Status HaltPrivate ()
lldb::StateType WaitForProcessStopPrivate (lldb::EventSP &event_sp, const Timeout< std::micro > &timeout)
bool GetEventsPrivate (lldb::EventSP &event_sp, const Timeout< std::micro > &timeout, bool control_only)
lldb::StateType GetStateChangedEventsPrivate (lldb::EventSP &event_sp, const Timeout< std::micro > &timeout)
size_t WriteMemoryPrivate (lldb::addr_t addr, const void *buf, size_t size, Status &error)
void AppendSTDOUT (const char *s, size_t len)
void AppendSTDERR (const char *s, size_t len)
void BroadcastAsyncProfileData (const std::string &one_profile_data)
bool PushProcessIOHandler ()
bool PopProcessIOHandler ()
bool ProcessIOHandlerIsActive ()
bool ProcessIOHandlerExists () const
Status StopForDestroyOrDetach (lldb::EventSP &exit_event_sp)
void LoadOperatingSystemPlugin (bool flush)
void SetAddressableBitMasks (AddressableBits bit_masks)
Protected Member Functions inherited from lldb_private::Broadcaster
BroadcasterImplSP GetBroadcasterImpl ()
const char * GetHijackingListenerName ()
Static Protected Member Functions
static void MonitorDebugserverProcess (std::weak_ptr< ProcessGDBRemote > process_wp, lldb::pid_t pid, int signo, int exit_status)
Static Protected Member Functions inherited from lldb_private::Process
static void STDIOReadThreadBytesReceived (void *baton, const void *src, size_t src_len)
Protected Attributes
GDBRemoteCommunicationClient m_gdb_comm
std::atomic< lldb::pid_t > m_debugserver_pid
std::optional< StringExtractorGDBRemote > m_last_stop_packet
std::recursive_mutex m_last_stop_packet_mutex
GDBRemoteDynamicRegisterInfoSP m_register_info_sp
Broadcaster m_async_broadcaster
lldb::ListenerSP m_async_listener_sp
HostThread m_async_thread
std::recursive_mutex m_async_thread_state_mutex
tid_collection m_thread_ids
std::vector< lldb::addr_t > m_thread_pcs
StructuredData::ObjectSP m_jstopinfo_sp
StructuredData::ObjectSP m_jthreadsinfo_sp
StructuredData::ObjectSP m_shared_cache_info_sp
std::mutex m_shared_cache_info_mutex
tid_collection m_continue_c_tids
tid_sig_collection m_continue_C_tids
tid_collection m_continue_s_tids
tid_sig_collection m_continue_S_tids
uint64_t m_max_memory_size
uint64_t m_remote_stub_max_memory_size
MMapMap m_addr_to_mmap_size
lldb::BreakpointSP m_thread_create_bp_sp
bool m_waiting_for_attach
lldb::CommandObjectSP m_command_sp
int64_t m_breakpoint_pc_offset
lldb::tid_t m_initial_tid
bool m_use_g_packet_for_reading
bool m_allow_flash_writes
FlashRangeVector m_erased_flash_ranges
uint32_t m_vfork_in_progress_count
Protected Attributes inherited from lldb_private::Process
std::weak_ptr< Target > m_target_wp
The target that owns this process.
lldb::pid_t m_pid = LLDB_INVALID_PROCESS_ID
Broadcaster m_private_state_broadcaster
Broadcaster m_private_state_control_broadcaster
lldb::ListenerSP m_private_state_listener_sp
PrivateStateThread * m_current_private_state_thread
< This is filled on construction with the "main" private state which will be exposed to clients of this process.
ProcessModID m_mod_id
Tracks the state of the process over stops and other alterations.
uint32_t m_process_unique_id
Each lldb_private::Process class that is created gets a unique integer ID that increments with each new instance.
uint32_t m_thread_index_id
Each thread is created with a 1 based index that won't get re-used.
std::map< uint64_t, uint32_t > m_thread_id_to_index_id_map
int m_exit_status
The exit status of the process, or -1 if not set.
std::string m_exit_string
A textual description of why a process exited.
std::mutex m_exit_status_mutex
Mutex so m_exit_status m_exit_string can be safely accessed from multiple threads.
std::recursive_mutex m_thread_mutex
ThreadList m_thread_list_real
The threads for this process as are known to the protocol we are debugging with.
ThreadList m_thread_list
The threads for this process as the user will see them.
ThreadPlanStackMap m_thread_plans
This is the list of thread plans for threads in m_thread_list, as well as threads we knew existed, but haven't determined that they have died yet.
ThreadList m_extended_thread_list
Constituent for extended threads that may be generated, cleared on natural stops.
lldb::RunDirection m_base_direction
ThreadPlanBase run direction.
uint32_t m_extended_thread_stop_id
The natural stop id when extended_thread_list was last updated.
QueueList m_queue_list
The list of libdispatch queues at a given stop point.
uint32_t m_queue_list_stop_id
The natural stop id when queue list was last fetched.
StopPointSiteList< lldb_private::WatchpointResource > m_watchpoint_resource_list
Watchpoint resources currently in use.
std::vector< Notifications > m_notifications
The list of notifications that this process can deliver.
std::vector< lldb::addr_t > m_image_tokens
StopPointSiteList< lldb_private::BreakpointSite > m_breakpoint_site_list
This is the list of breakpoint locations we intend to insert in the target.
lldb::DynamicLoaderUP m_dyld_up
lldb::JITLoaderListUP m_jit_loaders_up
lldb::DynamicCheckerFunctionsUP m_dynamic_checkers_up
The functions used by the expression parser to validate data that expressions use.
lldb::OperatingSystemUP m_os_up
lldb::SystemRuntimeUP m_system_runtime_up
lldb::UnixSignalsSP m_unix_signals_sp
lldb::ABISP m_abi_sp
This is the current signal set for this process.
lldb::IOHandlerSP m_process_input_reader
std::mutex m_process_input_reader_mutex
ThreadedCommunication m_stdio_communication
std::recursive_mutex m_stdio_communication_mutex
bool m_stdin_forward
std::string m_stdout_data
Remember if stdin must be forwarded to remote debug server.
std::string m_stderr_data
std::recursive_mutex m_profile_data_comm_mutex
std::vector< std::string > m_profile_data
Predicate< uint32_t > m_iohandler_sync
MemoryCache m_memory_cache
AllocatedMemoryCache m_allocated_memory_cache
bool m_should_detach
LanguageRuntimeCollection m_language_runtimes
Should we detach if the process object goes away with an explicit call to Kill or Detach?
std::recursive_mutex m_language_runtimes_mutex
InstrumentationRuntimeCollection m_instrumentation_runtimes
std::unique_ptr< NextEventAction > m_next_event_action_up
std::vector< PreResumeCallbackAndBaton > m_pre_resume_actions
bool m_currently_handling_do_on_removals
bool m_resume_requested
lldb::tid_t m_interrupt_tid
std::atomic< bool > m_finalizing
The tid of the thread that issued the async interrupt, used by thread plan timeout.
std::atomic< bool > m_destructing
bool m_clear_thread_plans_on_stop
bool m_force_next_event_delivery
lldb::StateType m_last_broadcast_state
std::map< lldb::addr_t, lldb::addr_t > m_resolved_indirect_addresses
This helps with the Public event coalescing in ShouldBroadcastEvent.
bool m_destroy_in_process
bool m_can_interpret_function_calls
std::mutex m_run_thread_plan_lock
llvm::StringMap< lldb::StructuredDataPluginSP > m_structured_data_plugin_map
enum lldb_private::Process:: { ... } m_can_jit
std::unique_ptr< UtilityFunction > m_dlopen_utility_func_up
llvm::once_flag m_dlopen_utility_func_flag_once
SourceManager::SourceFileCache m_source_file_cache
Per process source file cache.
StructuredData::DictionarySP m_crash_info_dict_sp
A repository for extra crash information, consulted in GetExtendedCrashInformation.
lldb::addr_t m_code_address_mask = LLDB_INVALID_ADDRESS_MASK
Mask for code an data addresses.
lldb::addr_t m_data_address_mask = LLDB_INVALID_ADDRESS_MASK
lldb::addr_t m_highmem_code_address_mask = LLDB_INVALID_ADDRESS_MASK
lldb::addr_t m_highmem_data_address_mask = LLDB_INVALID_ADDRESS_MASK
Protected Attributes inherited from lldb_private::ProcessProperties
Process * m_process
std::unique_ptr< ProcessExperimentalProperties > m_experimental_properties_up
Protected Attributes inherited from lldb_private::Properties
lldb::OptionValuePropertiesSP m_collection_sp
Private Types
using ModuleCacheKey = std::pair<std::string, std::string>
Private Member Functions
llvm::Expected< StringExtractorGDBRemote > SendMultiMemReadPacket (llvm::ArrayRef< Range< lldb::addr_t, size_t > > ranges)
llvm::Error ParseMultiMemReadPacket (llvm::StringRef response_str, llvm::MutableArrayRef< uint8_t > buffer, unsigned expected_num_ranges, llvm::SmallVectorImpl< llvm::MutableArrayRef< uint8_t > > &memory_regions)
void RemoveNewThreadBreakpoints ()
Remove the breakpoints associated with thread creation from the Target.
void HandleAsyncStdout (llvm::StringRef out) override
void HandleAsyncMisc (llvm::StringRef data) override
void HandleStopReply () override
void HandleAsyncStructuredDataPacket (llvm::StringRef data) override
Process asynchronously-received structured data.
lldb::ThreadSP HandleThreadAsyncInterrupt (uint8_t signo, const std::string &description) override
Handle thread specific async interrupt and return the original thread that requested the async interrupt.
void SetThreadPc (const lldb::ThreadSP &thread_sp, uint64_t index)
ProcessGDBRemote (const ProcessGDBRemote &)=delete
const ProcessGDBRemote & operator= (const ProcessGDBRemote &)=delete
void DidForkSwitchSoftwareBreakpoints (bool enable)
void DidForkSwitchHardwareTraps (bool enable)
void ParseExpeditedRegisters (ExpeditedRegisterMap &expedited_register_map, lldb::ThreadSP thread_sp)
Private Member Functions inherited from lldb_private::process_gdb_remote::GDBRemoteClientBase::ContinueDelegate
virtual ~ContinueDelegate ()
Static Private Member Functions
static bool NewThreadNotifyBreakpointHit (void *baton, StoppointCallbackContext *context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id)
Private Attributes
std::string m_partial_profile_data
std::map< uint64_t, uint32_t > m_thread_id_to_used_usec_map
uint64_t m_last_signals_version = 0
llvm::DenseMap< ModuleCacheKey, ModuleSpec, ModuleCacheInfo > m_cached_module_specs
llvm::StringMap< std::unique_ptr< RegisterFlags > > m_registers_flags_types
llvm::StringMap< std::unique_ptr< FieldEnum > > m_registers_enum_types
Friends
class ThreadGDBRemote
class GDBRemoteCommunicationClient
class GDBRemoteRegisterContext
Additional Inherited Members
Public Types inherited from lldb_private::Process
enum {
eBroadcastBitStateChanged = (1 << 0) , eBroadcastBitInterrupt = (1 << 1) , eBroadcastBitSTDOUT = (1 << 2) , eBroadcastBitSTDERR = (1 << 3) ,
eBroadcastBitProfileData = (1 << 4) , eBroadcastBitStructuredData = (1 << 5)
}
Broadcaster event bits definitions.
enum { eBroadcastInternalStateControlStop = (1 << 0) , eBroadcastInternalStateControlPause = (1 << 1) , eBroadcastInternalStateControlResume = (1 << 2) }
typedef Range< lldb::addr_t, lldb::addr_t > LoadRange
typedef ProcessRunLock::ProcessRunLocker StopLocker
typedef std::function< IterationAction(lldb_private::Status &error, lldb::addr_t bytes_addr, const void *bytes, lldb::offset_t bytes_size)> ReadMemoryChunkCallback
typedef bool PreResumeActionCallback(void *)
Static Public Attributes inherited from lldb_private::Process
static constexpr int g_all_event_bits
static constexpr llvm::StringRef AttachSynchronousHijackListenerName
static constexpr llvm::StringRef LaunchSynchronousHijackListenerName
static constexpr llvm::StringRef ResumeSynchronousHijackListenerName
Detailed Description
Definition at line 48 of file ProcessGDBRemote.h.
Member Typedef Documentation
ExpeditedRegisterMap
typedef std::map<uint32_t, std::string> lldb_private::process_gdb_remote::ProcessGDBRemote::ExpeditedRegisterMap protected
Definition at line 290 of file ProcessGDBRemote.h.
FlashRange
using lldb_private::process_gdb_remote::ProcessGDBRemote::FlashRange = FlashRangeVector::Entry protected
Definition at line 320 of file ProcessGDBRemote.h.
FlashRangeVector
using lldb_private::process_gdb_remote::ProcessGDBRemote::FlashRangeVector = lldb_private::RangeVector<lldb::addr_t, size_t> protected
Definition at line 319 of file ProcessGDBRemote.h.
MMapMap
typedef std::map<lldb::addr_t, lldb::addr_t> lldb_private::process_gdb_remote::ProcessGDBRemote::MMapMap protected
Definition at line 289 of file ProcessGDBRemote.h.
ModuleCacheKey
using lldb_private::process_gdb_remote::ProcessGDBRemote::ModuleCacheKey = std::pair<std::string, std::string> private
Definition at line 470 of file ProcessGDBRemote.h.
tid_collection
typedef std::vector<lldb::tid_t> lldb_private::process_gdb_remote::ProcessGDBRemote::tid_collection protected
Definition at line 287 of file ProcessGDBRemote.h.
tid_sig_collection
typedef std::vector<std::pair<lldb::tid_t, int> > lldb_private::process_gdb_remote::ProcessGDBRemote::tid_sig_collection protected
Definition at line 288 of file ProcessGDBRemote.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Broadcaster event bits definitions.
Enumerator
eBroadcastBitAsyncContinue
eBroadcastBitAsyncThreadShouldExit
eBroadcastBitAsyncThreadDidExit
Definition at line 270 of file ProcessGDBRemote.h.
Constructor & Destructor Documentation
~ProcessGDBRemote()
ProcessGDBRemote::~ProcessGDBRemote () override
Definition at line 310 of file ProcessGDBRemote.cpp.
References Clear(), lldb_private::Process::Finalize(), KillDebugserverProcess(), and StopAsyncThread().
ProcessGDBRemote() [1/2]
ProcessGDBRemote::ProcessGDBRemote (lldb::TargetSP target_sp, lldb::ListenerSP listener_sp) protected
Definition at line 264 of file ProcessGDBRemote.cpp.
References lldb_private::process_gdb_remote::Async, eBroadcastBitAsyncContinue, eBroadcastBitAsyncThreadDidExit, eBroadcastBitAsyncThreadShouldExit, GetGlobalPluginProperties(), lldb_private::GetLog(), lldb_private::Broadcaster::Listener, LLDB_INVALID_PROCESS_ID, LLDB_INVALID_THREAD_ID, LLDB_LOGF, m_addr_to_mmap_size, m_allow_flash_writes, m_async_broadcaster, m_async_listener_sp, m_async_thread_state_mutex, m_breakpoint_pc_offset, m_command_sp, m_continue_C_tids, m_continue_c_tids, m_continue_S_tids, m_continue_s_tids, m_debugserver_pid, m_erased_flash_ranges, m_gdb_comm, m_initial_tid, m_jstopinfo_sp, m_jthreadsinfo_sp, m_max_memory_size, m_register_info_sp, m_remote_stub_max_memory_size, m_shared_cache_info_mutex, m_shared_cache_info_sp, m_thread_create_bp_sp, m_thread_ids, m_thread_pcs, m_use_g_packet_for_reading, m_vfork_in_progress_count, m_waiting_for_attach, and lldb_private::Process::Process().
Referenced by CreateInstance(), operator=(), ProcessGDBRemote(), and lldb_private::wasm::ProcessWasm::ProcessWasm().
ProcessGDBRemote() [2/2]
lldb_private::process_gdb_remote::ProcessGDBRemote::ProcessGDBRemote (const ProcessGDBRemote &) private delete
References ProcessGDBRemote().
Member Function Documentation
AddRemoteRegisters()
void ProcessGDBRemote::AddRemoteRegisters (std::vector< DynamicRegisterInfo::Register > & registers, const ArchSpec & arch_to_use) protected
Definition at line 5183 of file ProcessGDBRemote.cpp.
References lldb_private::ABI::FindPlugin(), LLDB_INVALID_REGNUM, m_register_info_sp, and lldb_private::DynamicRegisterInfo::Register::regnum_remote.
Referenced by BuildDynamicRegisterInfo(), and GetGDBServerRegisterInfo().
AsyncThread()
thread_result_t ProcessGDBRemote::AsyncThread () protected
Definition at line 3914 of file ProcessGDBRemote.cpp.
References lldb_private::Status::AsCString(), ClearThreadIDList(), eBroadcastBitAsyncContinue, eBroadcastBitAsyncThreadShouldExit, lldb::eStateCrashed, lldb::eStateExited, lldb::eStateInvalid, lldb::eStateRunning, lldb::eStateStopped, lldb::eStateSuspended, lldb_private::Status::Fail(), lldb_private::EventDataBytes::GetBytes(), lldb_private::EventDataBytes::GetByteSize(), StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), StringExtractorGDBRemote::GetError(), lldb_private::EventDataBytes::GetEventDataFromEvent(), GetGDBRemote(), StringExtractor::GetHexByteString(), StringExtractor::GetHexU8(), lldb_private::Process::GetID(), lldb_private::ProcessProperties::GetInterruptTimeout(), lldb_private::GetLog(), StringExtractor::GetNameColonValue(), lldb_private::Process::GetPrivateState(), StringExtractorGDBRemote::GetStatus(), lldb_private::Process::GetUnixSignals(), LLDB_LOGF, m_async_broadcaster, m_async_listener_sp, lldb_private::process_gdb_remote::Process, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendContinuePacketAndWaitForResponse(), lldb_private::Process::SetExitStatus(), StringExtractor::SetFilePos(), SetLastStopPacket(), and lldb_private::Process::SetPrivateState().
Referenced by StartAsyncThread().
BuildDynamicRegisterInfo()
void ProcessGDBRemote::BuildDynamicRegisterInfo (bool force) protected
Definition at line 391 of file ProcessGDBRemote.cpp.
References AddRemoteRegisters(), lldb_private::DynamicRegisterInfo::Register::alt_name, lldb_private::DynamicRegisterInfo::Register::byte_offset, lldb_private::DynamicRegisterInfo::Register::byte_size, lldb::eEncodingInvalid, lldb::eFormatAddressInfo, lldb::eFormatBinary, lldb::eFormatBoolean, lldb::eFormatBytes, lldb::eFormatBytesWithASCII, lldb::eFormatChar, lldb::eFormatCharArray, lldb::eFormatCharPrintable, lldb::eFormatComplex, lldb::eFormatComplexInteger, lldb::eFormatCString, lldb::eFormatDecimal, lldb::eFormatEnum, lldb::eFormatFloat, lldb::eFormatFloat128, lldb::eFormatHex, lldb::eFormatHexFloat, lldb::eFormatHexUppercase, lldb::eFormatInstruction, lldb::eFormatInvalid, lldb::eFormatOctal, lldb::eFormatOSType, lldb::eFormatPointer, lldb::eFormatUnicode16, lldb::eFormatUnicode32, lldb::eFormatUnicode8, lldb::eFormatUnsigned, lldb::eFormatVectorOfChar, lldb::eFormatVectorOfFloat16, lldb::eFormatVectorOfFloat32, lldb::eFormatVectorOfFloat64, lldb::eFormatVectorOfSInt16, lldb::eFormatVectorOfSInt32, lldb::eFormatVectorOfSInt64, lldb::eFormatVectorOfSInt8, lldb::eFormatVectorOfUInt128, lldb::eFormatVectorOfUInt16, lldb::eFormatVectorOfUInt32, lldb::eFormatVectorOfUInt64, lldb::eFormatVectorOfUInt8, lldb::eFormatVoid, lldb_private::DynamicRegisterInfo::Register::encoding, StringExtractorGDBRemote::eResponse, StringExtractorGDBRemote::eUnsupported, lldb_private::DynamicRegisterInfo::Register::format, lldb_private::Target::GetArchitecture(), lldb_private::process_gdb_remote::GetFallbackRegisters(), GetGDBServerRegisterInfo(), GetGlobalPluginProperties(), lldb_private::Process::GetID(), lldb_private::GetLog(), StringExtractor::GetNameColonValue(), lldb_private::FileSpec::GetPath(), StringExtractorGDBRemote::GetResponseType(), lldb_private::Process::GetTarget(), lldb_private::FileSystem::Instance(), lldb_private::DynamicRegisterInfo::Register::invalidate_regs, lldb_private::ArchSpec::IsValid(), LLDB_LOG, LLDB_LOG_ERROR, m_gdb_comm, m_register_info_sp, lldb_private::DynamicRegisterInfo::Register::name, ParsePythonTargetDefinition(), lldb_private::process_gdb_remote::Process, lldb_private::DynamicRegisterInfo::Register::regnum_dwarf, lldb_private::DynamicRegisterInfo::Register::regnum_ehframe, lldb_private::DynamicRegisterInfo::Register::regnum_generic, lldb_private::Debugger::ReportError(), lldb_private::Debugger::ReportWarning(), lldb_private::FileSystem::Resolve(), lldb_private::DynamicRegisterInfo::Register::set_name, lldb_private::ConstString::SetString(), SplitCommaSeparatedRegisterNumberString(), lldb_private::Args::StringToEncoding(), lldb_private::Args::StringToGenericRegister(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, lldb_private::OptionArgParser::ToFormat(), UNUSED_IF_ASSERT_DISABLED, lldb_private::DynamicRegisterInfo::Register::value_regs, and lldb_private::XMLDocument::XMLEnabled().
Referenced by DidLaunchOrAttach(), HandleStopReply(), SetLastStopPacket(), and SetThreadStopInfo().
CalculateThreadStopInfo()
bool ProcessGDBRemote::CalculateThreadStopInfo (ThreadGDBRemote * thread) protected
Definition at line 1728 of file ProcessGDBRemote.cpp.
References lldb::eStateStopped, GetGDBRemote(), GetThreadStopInfoFromJSON(), m_jstopinfo_sp, m_jthreadsinfo_sp, SetThreadStopInfo(), and ThreadGDBRemote.
CanDebug()
bool ProcessGDBRemote::CanDebug (lldb::TargetSP target, bool plugin_specified_by_name) override virtual
Check if a plug-in instance can debug the file in module.
Each plug-in is given a chance to say whether it can debug the file in module. If the Process plug-in instance can debug a file on the current system, it should return true.
Returns
Returns true if this Process plug-in instance can debug the executable, false otherwise.
Implements lldb_private::Process.
Reimplemented in lldb_private::wasm::ProcessWasm.
Definition at line 232 of file ProcessGDBRemote.cpp.
References lldb_private::ObjectFile::eTypeCoreFile, lldb_private::ObjectFile::eTypeDebugInfo, lldb_private::ObjectFile::eTypeDynamicLinker, lldb_private::ObjectFile::eTypeExecutable, lldb_private::ObjectFile::eTypeInvalid, lldb_private::ObjectFile::eTypeJIT, lldb_private::ObjectFile::eTypeObjectFile, lldb_private::ObjectFile::eTypeSharedLibrary, lldb_private::ObjectFile::eTypeStubLibrary, lldb_private::ObjectFile::eTypeUnknown, lldb_private::FileSystem::Exists(), lldb_private::Module::GetFileSpec(), lldb_private::Module::GetObjectFile(), lldb_private::ObjectFile::GetType(), and lldb_private::FileSystem::Instance().
CanResume()
bool lldb_private::process_gdb_remote::ProcessGDBRemote::CanResume (lldb::StateType state) inline protected
Definition at line 335 of file ProcessGDBRemote.h.
References lldb::eStateStopped.
Clear()
void ProcessGDBRemote::Clear () protected
Definition at line 3620 of file ProcessGDBRemote.cpp.
References lldb_private::Process::m_thread_list, and lldb_private::Process::m_thread_list_real.
Referenced by DoAttachToProcessWithID(), DoAttachToProcessWithName(), and ~ProcessGDBRemote().
ClearThreadIDList()
void ProcessGDBRemote::ClearThreadIDList () protected
Definition at line 1538 of file ProcessGDBRemote.cpp.
References m_thread_ids, lldb_private::Process::m_thread_list_real, and m_thread_pcs.
Referenced by AsyncThread(), and DoDestroy().
ConfigureStructuredData()
Status ProcessGDBRemote::ConfigureStructuredData (llvm::StringRef type_name, const StructuredData::ObjectSP & config_sp) override virtual
Configure asynchronous structured data feature.
Each Process type that supports using an asynchronous StructuredData feature should implement this to enable/disable/configure the feature. The default implementation here will always return an error indiciating the feature is unsupported.
StructuredDataPlugin implementations will call this to configure a feature that has been reported as being supported.
Parameters
[in] type_name The StructuredData type name as previously discovered by the Process-derived instance.
[in] config_sp Configuration data for the feature being enabled. This config data, which may be null, will be passed along to the feature to process. The feature will dictate whether this is a dictionary, an array or some other object. If the feature needs to be set up properly before it can be enabled, then the config should also take an enable/disable flag.
Returns
Returns the result of attempting to configure the feature.
Reimplemented from lldb_private::Process.
Definition at line 4395 of file ProcessGDBRemote.cpp.
References m_gdb_comm.
ConnectToDebugserver()
Status ProcessGDBRemote::ConnectToDebugserver (llvm::StringRef host_port) protected
Definition at line 878 of file ProcessGDBRemote.cpp.
References lldb::eConnectionStatusSuccess, error(), lldb_private::Status::FromErrorString(), lldb_private::ProcessProperties::GetExtraStartupCommands(), lldb_private::GetLog(), lldb_private::Target::GetPlatform(), lldb_private::Process::GetTarget(), LLDB_LOGF, m_gdb_comm, and lldb_private::process_gdb_remote::Process.
Referenced by DoConnectRemote(), and LaunchAndConnectToDebugserver().
CreateInstance()
lldb::ProcessSP ProcessGDBRemote::CreateInstance (lldb::TargetSP target_sp, lldb::ListenerSP listener_sp, const FileSpec * crash_file_path, bool can_connect) static
Definition at line 211 of file ProcessGDBRemote.cpp.
References ProcessGDBRemote().
Referenced by Initialize(), and Terminate().
CreateThread()
std::shared_ptr< ThreadGDBRemote > ProcessGDBRemote::CreateThread (lldb::tid_t tid) protected virtual
Reimplemented in lldb_private::wasm::ProcessWasm.
Definition at line 328 of file ProcessGDBRemote.cpp.
Referenced by DoUpdateThreadList(), and SetThreadStopInfo().
DebuggerInitialize()
void ProcessGDBRemote::DebuggerInitialize (Debugger & debugger) static
Definition at line 3853 of file ProcessGDBRemote.cpp.
References lldb_private::PluginManager::CreateSettingForProcessPlugin(), lldb_private::Process::Debugger, GetGlobalPluginProperties(), lldb_private::PluginManager::GetSettingForProcessPlugin(), and lldb_private::Properties::GetValueProperties().
Referenced by lldb_private::wasm::ProcessWasm::DebuggerInitialize(), and Initialize().
DetachRequiresHalt()
bool lldb_private::process_gdb_remote::ProcessGDBRemote::DetachRequiresHalt () inline override virtual
Reimplemented from lldb_private::Process.
Definition at line 119 of file ProcessGDBRemote.h.
DidAttach()
void ProcessGDBRemote::DidAttach (ArchSpec & process_arch) override virtual
Called after attaching a process.
Parameters
[in] process_arch If you can figure out the process architecture after attach, fill it in here.
Allow Process plug-ins to execute some code after attaching to a process.
Reimplemented from lldb_private::Process.
Definition at line 1239 of file ProcessGDBRemote.cpp.
References lldb_private::ArchSpec::Clear(), and DidLaunchOrAttach().
DidExec()
void ProcessGDBRemote::DidExec () override virtual
Called after a process re-execs itself.
Allow Process plug-ins to execute some code after a process has exec'ed itself. Subclasses typically should override DoDidExec() as the lldb_private::Process class needs to remove its dynamic loader, runtime, ABI and other plug-ins, as well as unload all shared libraries.
Reimplemented from lldb_private::Process.
Definition at line 6236 of file ProcessGDBRemote.cpp.
References lldb_private::Process::DidExec(), lldb_private::eFollowChild, lldb_private::ProcessProperties::GetFollowForkMode(), and m_vfork_in_progress_count.
DidExit()
void ProcessGDBRemote::DidExit () override virtual
Reimplemented from lldb_private::Process.
Definition at line 1234 of file ProcessGDBRemote.cpp.
References m_gdb_comm.
DidFork()
void ProcessGDBRemote::DidFork (lldb::pid_t child_pid, lldb::tid_t child_tid) override virtual
Called after a reported fork.
Reimplemented from lldb_private::Process.
Definition at line 6102 of file ProcessGDBRemote.cpp.
References DidForkSwitchHardwareTraps(), DidForkSwitchSoftwareBreakpoints(), lldb_private::process_gdb_remote::eBreakpointSoftware, lldb_private::eFollowChild, lldb_private::eFollowParent, error(), lldb_private::ProcessProperties::GetFollowForkMode(), lldb_private::GetLog(), LLDB_LOG, m_gdb_comm, m_thread_ids, lldb_private::process_gdb_remote::Process, and lldb_private::Process::SetID().
DidForkSwitchHardwareTraps()
void ProcessGDBRemote::DidForkSwitchHardwareTraps (bool enable) private
Definition at line 6081 of file ProcessGDBRemote.cpp.
References lldb_private::process_gdb_remote::eBreakpointHardware, lldb_private::BreakpointSite::eHardware, lldb_private::StopPointSiteList< StopPointSite >::ForEach(), lldb_private::Process::GetBreakpointSiteList(), GetGDBStoppointType(), lldb_private::ProcessProperties::GetInterruptTimeout(), lldb_private::StoppointSite::GetLoadAddress(), lldb_private::Process::GetSoftwareBreakpointTrapOpcode(), lldb_private::BreakpointSite::GetType(), lldb_private::BreakpointSite::IsEnabled(), m_gdb_comm, and lldb_private::Process::m_watchpoint_resource_list.
Referenced by DidFork(), and DidVFork().
DidForkSwitchSoftwareBreakpoints()
void ProcessGDBRemote::DidForkSwitchSoftwareBreakpoints (bool enable) private
Definition at line 6069 of file ProcessGDBRemote.cpp.
References lldb_private::process_gdb_remote::eBreakpointSoftware, lldb_private::BreakpointSite::eExternal, lldb_private::BreakpointSite::eSoftware, lldb_private::StopPointSiteList< StopPointSite >::ForEach(), lldb_private::Process::GetBreakpointSiteList(), lldb_private::ProcessProperties::GetInterruptTimeout(), lldb_private::StoppointSite::GetLoadAddress(), lldb_private::Process::GetSoftwareBreakpointTrapOpcode(), lldb_private::BreakpointSite::GetType(), lldb_private::BreakpointSite::IsEnabled(), and m_gdb_comm.
Referenced by DidFork(), DidVFork(), and DidVForkDone().
DidLaunch()
void ProcessGDBRemote::DidLaunch () override virtual
Called after launching a process.
Allow Process plug-ins to execute some code after launching a process.
Reimplemented from lldb_private::Process.
Definition at line 1141 of file ProcessGDBRemote.cpp.
References DidLaunchOrAttach().
DidLaunchOrAttach()
void ProcessGDBRemote::DidLaunchOrAttach (ArchSpec & process_arch) protected
Definition at line 952 of file ProcessGDBRemote.cpp.
References BuildDynamicRegisterInfo(), lldb_private::UnixSignals::Create(), lldb_private::Target::GetArchitecture(), lldb_private::ArchSpec::GetArchitectureName(), lldb_private::GetLog(), lldb_private::ArchSpec::GetMachine(), lldb_private::Target::GetPlatform(), lldb_private::Process::GetTarget(), lldb_private::ArchSpec::GetTriple(), lldb_private::ArchSpec::IsValid(), LLDB_LOG, LoadStubBinaries(), m_gdb_comm, lldb_private::Process::MapSupportedStructuredDataPlugins(), MaybeLoadExecutableModule(), lldb_private::process_gdb_remote::Process, lldb_private::Process::SetAddressableBitMasks(), lldb_private::Target::SetArchitecture(), lldb_private::ArchSpec::SetTriple(), and SetUnixSignals().
Referenced by DidAttach(), and DidLaunch().
DidVFork()
void ProcessGDBRemote::DidVFork (lldb::pid_t child_pid, lldb::tid_t child_tid) override virtual
Called after a reported vfork.
Reimplemented from lldb_private::Process.
Definition at line 6167 of file ProcessGDBRemote.cpp.
References DidForkSwitchHardwareTraps(), DidForkSwitchSoftwareBreakpoints(), lldb_private::process_gdb_remote::eBreakpointSoftware, lldb_private::eFollowChild, lldb_private::eFollowParent, error(), lldb_private::ProcessProperties::GetFollowForkMode(), lldb_private::GetLog(), LLDB_LOG, m_gdb_comm, m_thread_ids, m_vfork_in_progress_count, lldb_private::process_gdb_remote::Process, and lldb_private::Process::SetID().
DidVForkDone()
void ProcessGDBRemote::DidVForkDone () override virtual
Called after reported vfork completion.
Reimplemented from lldb_private::Process.
Definition at line 6227 of file ProcessGDBRemote.cpp.
References DidForkSwitchSoftwareBreakpoints(), lldb_private::process_gdb_remote::eBreakpointSoftware, m_gdb_comm, and m_vfork_in_progress_count.
DisableBreakpointSite()
Status ProcessGDBRemote::DisableBreakpointSite (BreakpointSite * bp_site) override virtual
Reimplemented from lldb_private::Process.
Definition at line 3399 of file ProcessGDBRemote.cpp.
References lldb_private::process_gdb_remote::Breakpoints, lldb_private::Process::DisableSoftwareBreakpoint(), lldb_private::process_gdb_remote::eBreakpointHardware, lldb_private::process_gdb_remote::eBreakpointSoftware, lldb_private::BreakpointSite::eExternal, lldb_private::BreakpointSite::eHardware, error(), lldb_private::BreakpointSite::eSoftware, lldb_private::Status::FromErrorString(), lldb_private::StoppointSite::GetID(), lldb_private::ProcessProperties::GetInterruptTimeout(), lldb_private::StoppointSite::GetLoadAddress(), lldb_private::GetLog(), lldb_private::Process::GetSoftwareBreakpointTrapOpcode(), lldb_private::BreakpointSite::GetType(), lldb_private::BreakpointSite::IsEnabled(), LLDB_LOGF, m_gdb_comm, and lldb_private::BreakpointSite::SetEnabled().
DisableWatchpoint()
Status ProcessGDBRemote::DisableWatchpoint (lldb::WatchpointSP wp_sp, bool notify = true) override virtual
Reimplemented from lldb_private::Process.
Definition at line 3560 of file ProcessGDBRemote.cpp.
References error(), lldb_private::Status::FromErrorString(), GetGDBStoppointType(), lldb_private::ProcessProperties::GetInterruptTimeout(), lldb_private::GetLog(), LLDB_LOGF, m_gdb_comm, lldb_private::Process::m_watchpoint_resource_list, and lldb_private::process_gdb_remote::Watchpoints.
DoAllocateMemory()
lldb::addr_t ProcessGDBRemote::DoAllocateMemory (size_t size, uint32_t permissions, Status & error) override virtual
Actually allocate memory in the process.
This function will allocate memory in the process's address space. This can't rely on the generic function calling mechanism, since that requires this function.
Parameters
[in] size The size of the allocation requested.
Returns
The address of the allocated buffer in the process, or LLDB_INVALID_ADDRESS if the allocation failed.
Reimplemented from lldb_private::Process.
Definition at line 3167 of file ProcessGDBRemote.cpp.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb_private::eMmapFlagsAnon, lldb_private::eMmapFlagsPrivate, lldb_private::eMmapProtExec, lldb_private::eMmapProtRead, lldb_private::eMmapProtWrite, error(), lldb_private::Expressions, lldb_private::Status::FromErrorStringWithFormat(), lldb_private::GetLog(), lldb_private::GetPermissionsAsCString(), lldb_private::InferiorCallMmap(), LLDB_INVALID_ADDRESS, LLDB_LOGF, m_addr_to_mmap_size, m_gdb_comm, and lldb_private::Process.
DoAttachToProcessWithID()
Status ProcessGDBRemote::DoAttachToProcessWithID (lldb::pid_t pid, const ProcessAttachInfo & attach_info) override virtual
Attach to an existing process using a process ID.
Parameters
[in] pid The process ID that we should attempt to attach to.
[in] attach_info Information on how to do the attach. For example, GetUserID() will return the uid to attach as.
Returns
Returns a successful Status attaching was successful, or an appropriate (possibly platform-specific) error code if attaching fails. hanming : need flag
Reimplemented from lldb_private::Process.
Definition at line 1146 of file ProcessGDBRemote.cpp.
References Clear(), eBroadcastBitAsyncContinue, error(), EstablishConnectionIfNeeded(), lldb_private::ProcessAttachInfo::GetDetachOnError(), lldb_private::GetLog(), LLDB_INVALID_PROCESS_ID, LLDB_LOGF, m_async_broadcaster, m_gdb_comm, lldb_private::process_gdb_remote::Process, lldb_private::Process::SetExitStatus(), and lldb_private::Process::SetID().
DoAttachToProcessWithName()
Status ProcessGDBRemote::DoAttachToProcessWithName (const char * process_name, const ProcessAttachInfo & attach_info) override virtual
Attach to an existing process using a partial process name.
Parameters
[in] process_name The name of the process to attach to.
[in] attach_info Information on how to do the attach. For example, GetUserID() will return the uid to attach as.
Returns
Returns a successful Status attaching was successful, or an appropriate (possibly platform-specific) error code if attaching fails.
Reimplemented from lldb_private::Process.
Definition at line 1174 of file ProcessGDBRemote.cpp.
References Clear(), eBroadcastBitAsyncContinue, error(), EstablishConnectionIfNeeded(), lldb_private::ProcessAttachInfo::GetDetachOnError(), lldb_private::ProcessAttachInfo::GetIgnoreExisting(), lldb_private::StreamString::GetString(), lldb_private::ProcessAttachInfo::GetWaitForLaunch(), lldb_private::endian::InlHostByteOrder(), m_async_broadcaster, m_gdb_comm, lldb_private::Stream::PutBytesAsRawHex8(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), and lldb_private::Process::SetExitStatus().
DoConnectRemote()
Status ProcessGDBRemote::DoConnectRemote (llvm::StringRef remote_url) override virtual
Attach to a remote system via a URL.
Parameters
[in] remote_url The URL format that we are connecting to.
Returns
Returns an error object.
Reimplemented from lldb_private::Process.
Definition at line 599 of file ProcessGDBRemote.cpp.
References ConnectToDebugserver(), error(), lldb::eStateConnected, lldb::eStateInvalid, lldb_private::Status::FromErrorStringWithFormat(), lldb_private::Target::GetArchitecture(), lldb_private::Process::GetID(), lldb_private::GetLog(), lldb_private::Process::GetTarget(), lldb_private::Process::GetThreadList(), lldb_private::ArchSpec::IsValid(), lldb_private::Process::IsValid(), LLDB_INVALID_PROCESS_ID, LLDB_LOGF, m_gdb_comm, lldb_private::process_gdb_remote::Process, lldb_private::Target::SetArchitecture(), lldb_private::Process::SetID(), SetLastStopPacket(), lldb_private::Process::SetPrivateState(), SetThreadStopInfo(), StartAsyncThread(), lldb_private::StateAsCString(), lldb_private::Process::Target, and WillLaunchOrAttach().
DoDeallocateMemory()
Status ProcessGDBRemote::DoDeallocateMemory (lldb::addr_t ptr) override virtual
Actually deallocate memory in the process.
This function will deallocate memory in the process's address space that was allocated with AllocateMemory.
Parameters
[in] ptr A return value from AllocateMemory, pointing to the memory you want to deallocate.
Returns
true if the memory was deallocated, false otherwise.
Reimplemented from lldb_private::Process.
Definition at line 3227 of file ProcessGDBRemote.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::InferiorCallMunmap(), m_addr_to_mmap_size, and m_gdb_comm.
DoDestroy()
Status ProcessGDBRemote::DoDestroy () override virtual
Implements lldb_private::Process.
Definition at line 2591 of file ProcessGDBRemote.cpp.
References ClearThreadIDList(), lldb::eStateAttaching, lldb_private::Process::GetID(), lldb_private::GetLog(), lldb_private::Process::GetPublicState(), lldb_private::Process::GetTarget(), KillDebugserverProcess(), LLDB_LOGF, m_gdb_comm, lldb_private::process_gdb_remote::Process, RemoveNewThreadBreakpoints(), lldb_private::Process::SetExitStatus(), lldb_private::Status, and StopAsyncThread().
DoDetach()
Status ProcessGDBRemote::DoDetach (bool keep_stopped) override virtual
Detaches from a running or stopped process.
Returns
Returns true if the process successfully detaches, false otherwise.
Reimplemented from lldb_private::Process.
Definition at line 2562 of file ProcessGDBRemote.cpp.
References error(), lldb::eStateDetached, lldb_private::GetLog(), LLDB_LOGF, m_gdb_comm, lldb_private::process_gdb_remote::Process, lldb_private::Log::PutCString(), lldb_private::Process::ResumePrivateStateThread(), lldb_private::Process::SetPrivateState(), and StopAsyncThread().
DoGetMemoryRegionInfo()
Status ProcessGDBRemote::DoGetMemoryRegionInfo (lldb::addr_t load_addr, MemoryRegionInfo & range_info) override protected virtual
DoGetMemoryRegionInfo is called by GetMemoryRegionInfo after it has removed non address bits from load_addr.
Override this method in subclasses of Process.
See GetMemoryRegionInfo for details of the logic.
Parameters
[in] load_addr The load address to query the range_info for. (non address bits removed)
[out] range_info An range_info value containing the details of the range.
Returns
An error value.
Reimplemented from lldb_private::Process.
Definition at line 3212 of file ProcessGDBRemote.cpp.
References error(), and m_gdb_comm.
DoGetWatchpointReportedAfter()
std::optional< bool > ProcessGDBRemote::DoGetWatchpointReportedAfter () override virtual
Provide an override value in the subclass for lldb's CPU-based logic for whether watchpoint exceptions are received before or after an instruction executes.
If a Process subclass needs to override this architecture-based result, it may do so by overriding this method.
Returns
No boolean returned means there is no override of the default architecture-based behavior. true is returned for targets where watchpoints are reported after the instruction has completed. false is returned for targets where watchpoints are reported before the instruction executes.
Reimplemented from lldb_private::Process.
Definition at line 3223 of file ProcessGDBRemote.cpp.
References m_gdb_comm.
DoHalt()
Status ProcessGDBRemote::DoHalt (bool & caused_stop) override virtual
Halts a running process.
DoHalt must produce one and only one stop StateChanged event if it actually stops the process. If the stop happens through some natural event (for instance a SIGSTOP), then forwarding that event will do. Otherwise, you must generate the event manually. This function is called from the context of the private state thread.
Parameters
[out] caused_stop If true, then this Halt caused the stop, otherwise, the process was already stopped.
Returns
Returns true if the process successfully halts, false otherwise.
Reimplemented from lldb_private::Process.
Definition at line 2548 of file ProcessGDBRemote.cpp.
References error(), lldb::eStateAttaching, lldb_private::ProcessProperties::GetInterruptTimeout(), lldb_private::Process::GetPublicState(), and m_gdb_comm.
DoLaunch()
Status ProcessGDBRemote::DoLaunch (lldb_private::Module * exe_module, ProcessLaunchInfo & launch_info) override virtual
Launch a new process.
Launch a new process by spawning a new process using exe_module's file as the file to launch. Launch details are provided in launch_info.
Parameters
[in] exe_module The module from which to extract the file specification and launch.
[in] launch_info Details (e.g. arguments, stdio redirection, etc.) for the requested launch.
Returns
An Status instance indicating success or failure of the operation.
Reimplemented from lldb_private::Process.
Definition at line 687 of file ProcessGDBRemote.cpp.
References lldb_private::FileSystem::DEV_NULL, lldb_private::FileAction::eFileActionOpen, error(), EstablishConnectionIfNeeded(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::Flags::Get(), lldb_private::FileAction::GetAction(), lldb_private::Args::GetArgumentAtIndex(), lldb_private::ProcessInfo::GetArguments(), lldb_private::ProcessInfo::GetEnvironment(), lldb_private::ProcessInfo::GetExecutableFile(), lldb_private::ProcessLaunchInfo::GetFileActionForFD(), lldb_private::FileAction::GetFileSpec(), lldb_private::ProcessLaunchInfo::GetFlags(), lldb_private::Process::GetID(), lldb_private::ProcessLaunchInfo::GetLaunchEventData(), lldb_private::GetLog(), lldb_private::FileSpec::GetPath(), lldb_private::PseudoTerminal::GetPrimaryFileDescriptor(), lldb_private::PseudoTerminal::GetSecondaryName(), lldb_private::Process::GetTarget(), lldb_private::ProcessLaunchInfo::GetWorkingDirectory(), lldb_private::PseudoTerminal::invalid_fd, lldb_private::ArchSpec::IsValid(), KillDebugserverProcess(), LLDB_INVALID_PROCESS_ID, LLDB_LOGF, m_gdb_comm, lldb_private::Process::m_stdin_forward, lldb_private::Target::MergeArchitecture(), O_NOCTTY, lldb_private::PseudoTerminal::OpenFirstAvailablePrimary(), lldb_private::process_gdb_remote::Process, lldb_private::PseudoTerminal::ReleasePrimaryFileDescriptor(), lldb_private::Args::ReplaceArgumentAtIndex(), lldb_private::FileSpec::SetFile(), lldb_private::Process::SetID(), SetLastStopPacket(), lldb_private::Process::SetPrivateState(), lldb_private::Process::SetSTDIOFileDescriptor(), and SetThreadStopInfo().
DoReadMemory()
size_t ProcessGDBRemote::DoReadMemory (lldb::addr_t vm_addr, void * buf, size_t size, Status & error) override virtual
Actually do the reading of memory from a process.
Subclasses must override this function and can return fewer bytes than requested when memory requests are too large. This class will break up the memory requests and keep advancing the arguments along as needed.
Parameters
[in] vm_addr A virtual load address that indicates where to start reading memory from.
[in] size The number of bytes to read.
[out] buf A byte buffer that is at least size bytes long that will receive the memory bytes.
[out] error An error that indicates the success or failure of this operation. If error indicates success (error.Success()), then the value returned can be trusted, otherwise zero will be returned.
Returns
The number of bytes that were actually read into buf. Zero is returned in the case of an error.
Implements lldb_private::Process.
Definition at line 2725 of file ProcessGDBRemote.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::Status::FromErrorStringWithFormatv(), StringExtractor::GetHexBytes(), lldb_private::ProcessProperties::GetInterruptTimeout(), GetMaxMemorySize(), StringExtractor::GetStringRef(), StringExtractorGDBRemote::IsErrorResponse(), StringExtractorGDBRemote::IsNormalResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), m_gdb_comm, m_max_memory_size, lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UNUSED_IF_ASSERT_DISABLED.
DoReadMemoryTags()
llvm::Expected< std::vector< uint8_t > > ProcessGDBRemote::DoReadMemoryTags (lldb::addr_t addr, size_t len, int32_t type) override protected virtual
Does the final operation to read memory tags.
E.g. sending a GDB packet. It assumes that ReadMemoryTags has checked that memory tagging is enabled and has expanded the memory range as needed.
Parameters
[in] addr Start of address range to read memory tags for.
[in] len Length of the memory range to read tags for (in bytes).
[in] type Type of tags to read (get this from a MemoryTagManager)
Returns
The packed tag data received from the remote or an error if the read failed.
Reimplemented from lldb_private::Process.
Definition at line 2934 of file ProcessGDBRemote.cpp.
References m_gdb_comm.
DoResume()
Status ProcessGDBRemote::DoResume (lldb::RunDirection direction) override virtual
Resumes all of a process's threads as configured using the Thread run control functions.
Threads for a process should be updated with one of the run control actions (resume, step, or suspend) that they should take when the process is resumed. If no run control action is given to a thread it will be resumed by default.
Returns
Returns true if the process successfully resumes using the thread run control actions, false otherwise.
See also
Thread:Resume()
Thread:Step()
Thread:Suspend()
Reimplemented from lldb_private::Process.
Definition at line 1261 of file ProcessGDBRemote.cpp.
References lldb_private::StreamString::Clear(), eBroadcastBitAsyncContinue, eBroadcastBitAsyncThreadDidExit, lldb_private::process_gdb_remote::GDBRemoteClientBase::eBroadcastBitRunPacketSent, error(), lldb::eRunForward, lldb::eRunReverse, lldb_private::Stream::Format(), lldb_private::Status::FromErrorString(), lldb_private::Process::GetID(), lldb_private::GetLog(), lldb_private::ThreadList::GetSize(), lldb_private::StreamString::GetString(), lldb_private::Process::GetThreadList(), LLDB_LOGF, m_async_broadcaster, m_async_thread, m_continue_C_tids, m_continue_c_tids, m_continue_S_tids, m_continue_s_tids, m_gdb_comm, lldb_private::Listener::MakeListener(), lldb_private::Stream::Printf(), lldb_private::process_gdb_remote::Process, lldb_private::Stream::PutChar(), and lldb_private::Stream::PutCString().
DoSignal()
Status ProcessGDBRemote::DoSignal (int signal) override virtual
Sends a process a UNIX signal signal.
Returns
Returns an error object.
Reimplemented from lldb_private::Process.
Definition at line 3625 of file ProcessGDBRemote.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::ProcessProperties::GetInterruptTimeout(), lldb_private::GetLog(), LLDB_LOGF, m_gdb_comm, and lldb_private::process_gdb_remote::Process.
DoUpdateThreadList()
bool ProcessGDBRemote::DoUpdateThreadList (ThreadList & old_thread_list, ThreadList & new_thread_list) override protected virtual
Update the thread list following process plug-in's specific logic.
This method should only be invoked by UpdateThreadList.
Returns
true if the new thread list could be generated, false otherwise.
Implements lldb_private::Process.
Definition at line 1638 of file ProcessGDBRemote.cpp.
References lldb_private::ThreadCollection::AddThreadSortedByIndexID(), CreateThread(), lldb_private::Process::GetID(), lldb_private::GetLog(), lldb_private::ThreadList::GetSize(), lldb_private::ThreadList::GetThreadAtIndex(), LLDB_LOGV, lldb_private::Process::m_thread_id_to_index_id_map, m_thread_ids, lldb_private::ThreadList::RemoveThreadByProtocolID(), SetThreadPc(), lldb_private::process_gdb_remote::Thread, lldb_private::Process::ThreadList, and UpdateThreadIDList().
DoWillAttachToProcessWithID()
Status ProcessGDBRemote::DoWillAttachToProcessWithID (lldb::pid_t pid) override virtual
Called before attaching to a process.
Allow Process plug-ins to execute some code before attaching a process.
Returns
Returns an error object.
Reimplemented from lldb_private::Process.
Definition at line 590 of file ProcessGDBRemote.cpp.
References WillLaunchOrAttach().
DoWillAttachToProcessWithName()
Status ProcessGDBRemote::DoWillAttachToProcessWithName (const char * process_name, bool wait_for_launch) override virtual
Called before attaching to a process.
Allow Process plug-ins to execute some code before attaching a process.
Returns
Returns an error object.
Reimplemented from lldb_private::Process.
Definition at line 594 of file ProcessGDBRemote.cpp.
References WillLaunchOrAttach().
DoWillLaunch()
Status ProcessGDBRemote::DoWillLaunch (lldb_private::Module * module) override virtual
Called before launching to a process.
Allow Process plug-ins to execute some code before launching a process.
Returns
Returns an error object.
Reimplemented from lldb_private::Process.
Definition at line 586 of file ProcessGDBRemote.cpp.
References WillLaunchOrAttach().
DoWriteMemory()
size_t ProcessGDBRemote::DoWriteMemory (lldb::addr_t vm_addr, const void * buf, size_t size, Status & error) override virtual
Actually do the writing of memory to a process.
Parameters
[in] vm_addr A virtual load address that indicates where to start writing memory to.
[in] buf A byte buffer that is at least size bytes long that contains the data to write.
[in] size The number of bytes to write.
[out] error An error value in case the memory write fails.
Returns
The number of bytes that were actually written.
Reimplemented from lldb_private::Process.
Definition at line 3104 of file ProcessGDBRemote.cpp.
References error(), lldb_private::MemoryRegionInfo::eYes, FlashErase(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::StreamString::GetData(), lldb_private::MemoryRegionInfo::GetFlash(), lldb_private::ProcessProperties::GetInterruptTimeout(), GetMaxMemorySize(), lldb_private::Process::GetMemoryRegionInfo(), lldb_private::MemoryRegionInfo::GetRange(), lldb_private::Range< B, S >::GetRangeEnd(), lldb_private::StreamString::GetString(), StringExtractor::GetStringRef(), lldb_private::endian::InlHostByteOrder(), StringExtractorGDBRemote::IsErrorResponse(), StringExtractorGDBRemote::IsOKResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), m_allow_flash_writes, m_gdb_comm, m_max_memory_size, lldb_private::Stream::Printf(), lldb_private::Stream::PutBytesAsRawHex8(), lldb_private::StreamGDBRemote::PutEscapedBytes(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and lldb_private::Status::Success().
DoWriteMemoryTags()
Status ProcessGDBRemote::DoWriteMemoryTags (lldb::addr_t addr, size_t len, int32_t type, const std::vector< uint8_t > & tags) override protected virtual
Does the final operation to write memory tags.
E.g. sending a GDB packet. It assumes that WriteMemoryTags has checked that memory tagging is enabled and has packed the tag data.
Parameters
[in] addr Start of address range to write memory tags for.
[in] len Length of the memory range to write tags for (in bytes).
[in] type Type of tags to read (get this from a MemoryTagManager)
[in] tags Packed tags to be written.
Returns
Status telling you whether the write succeeded.
Reimplemented from lldb_private::Process.
Definition at line 2952 of file ProcessGDBRemote.cpp.
References m_gdb_comm.
DumpPluginHistory()
void ProcessGDBRemote::DumpPluginHistory (Stream & s) override virtual
The underlying plugin might store the low-level communication history for this session.
Dump it into the provided stream.
Reimplemented from lldb_private::Process.
Definition at line 219 of file ProcessGDBRemote.cpp.
References lldb_private::process_gdb_remote::GDBRemoteCommunication::DumpHistory(), GDBRemoteCommunicationClient, and GetGDBRemote().
Referenced by CommandObjectProcessGDBRemotePacketHistory::DoExecute().
EnableBreakpointSite()
Status ProcessGDBRemote::EnableBreakpointSite (BreakpointSite * bp_site) override virtual
Reimplemented from lldb_private::Process.
Definition at line 3274 of file ProcessGDBRemote.cpp.
References lldb_private::process_gdb_remote::Breakpoints, lldb_private::process_gdb_remote::eBreakpointHardware, lldb_private::process_gdb_remote::eBreakpointSoftware, lldb_private::BreakpointSite::eExternal, lldb_private::BreakpointSite::eHardware, lldb_private::Process::EnableSoftwareBreakpoint(), error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::StoppointSite::GetID(), lldb_private::ProcessProperties::GetInterruptTimeout(), lldb_private::StoppointSite::GetLoadAddress(), lldb_private::GetLog(), lldb_private::Process::GetSoftwareBreakpointTrapOpcode(), lldb_private::StoppointSite::HardwareRequired(), lldb_private::BreakpointSite::IsEnabled(), LLDB_LOGF, m_gdb_comm, lldb_private::BreakpointSite::SetEnabled(), and lldb_private::BreakpointSite::SetType().
EnableWatchpoint()
Status ProcessGDBRemote::EnableWatchpoint (lldb::WatchpointSP wp_sp, bool notify = true) override virtual
Reimplemented from lldb_private::Process.
Definition at line 3465 of file ProcessGDBRemote.cpp.
References lldb_private::WatchpointAlgorithms::AtomizeWatchpointRequest(), error(), lldb_private::Status::FromErrorString(), lldb_private::Target::GetArchitecture(), GetGDBStoppointType(), lldb_private::ProcessProperties::GetInterruptTimeout(), lldb_private::GetLog(), lldb_private::Process::GetTarget(), LLDB_LOGF, m_gdb_comm, lldb_private::Process::m_watchpoint_resource_list, and lldb_private::process_gdb_remote::Watchpoints.
EstablishConnectionIfNeeded()
Status ProcessGDBRemote::EstablishConnectionIfNeeded (const ProcessInfo & process_info) protected
Definition at line 3637 of file ProcessGDBRemote.cpp.
References DEBUGSERVER_BASENAME, error(), lldb_private::Status::FromErrorString(), lldb_private::Process::GetTarget(), LaunchAndConnectToDebugserver(), m_gdb_comm, and lldb_private::Status.
Referenced by DoAttachToProcessWithID(), DoAttachToProcessWithName(), and DoLaunch().
FlashDone()
Status ProcessGDBRemote::FlashDone () protected
Definition at line 3074 of file ProcessGDBRemote.cpp.
References lldb_private::Status::FromErrorStringWithFormat(), lldb_private::ProcessProperties::GetInterruptTimeout(), StringExtractor::GetStringRef(), StringExtractorGDBRemote::IsErrorResponse(), StringExtractorGDBRemote::IsOKResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), m_erased_flash_ranges, m_gdb_comm, and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by WriteObjectFile().
FlashErase()
Status ProcessGDBRemote::FlashErase (lldb::addr_t addr, size_t size) protected
Definition at line 2991 of file ProcessGDBRemote.cpp.
References lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::MemoryRegionInfo::GetBlocksize(), lldb_private::Range< B, S >::GetByteSize(), lldb_private::StreamString::GetData(), lldb_private::ProcessProperties::GetInterruptTimeout(), lldb_private::Process::GetMemoryRegionInfo(), lldb_private::MemoryRegionInfo::GetRange(), lldb_private::Range< B, S >::GetRangeBase(), lldb_private::Range< B, S >::GetRangeEnd(), lldb_private::StreamString::GetString(), StringExtractor::GetStringRef(), HasErased(), StringExtractorGDBRemote::IsErrorResponse(), StringExtractorGDBRemote::IsOKResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), m_erased_flash_ranges, m_gdb_comm, lldb_private::Stream::Printf(), lldb_private::Range< B, S >::SetByteSize(), lldb_private::Range< B, S >::SetRangeBase(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and lldb_private::Status::Success().
Referenced by DoWriteMemory().
GetAuxvData()
DataExtractor ProcessGDBRemote::GetAuxvData () override protected virtual
Reimplemented from lldb_private::Process.
Definition at line 4196 of file ProcessGDBRemote.cpp.
References lldb_private::Process::GetAddressByteSize(), lldb_private::Process::GetByteOrder(), lldb_private::GetLog(), LLDB_LOG_ERROR, m_gdb_comm, and lldb_private::process_gdb_remote::Process.
GetDispatchQueueNameForThread()
const char * lldb_private::process_gdb_remote::ProcessGDBRemote::GetDispatchQueueNameForThread (lldb::addr_t thread_dispatch_qaddr, std::string & dispatch_queue_name) protected
References lldb_private::Process::DynamicLoader.
GetDynamicLoader()
DynamicLoader * ProcessGDBRemote::GetDynamicLoader () override protected virtual
Get the dynamic loader plug-in for this process.
The default action is to let the DynamicLoader plug-ins check the main executable and the DynamicLoader will select itself automatically. Subclasses can override this if inspecting the executable is not desired, or if Process subclasses can only use a specific DynamicLoader plug-in.
Reimplemented from lldb_private::Process.
Definition at line 4172 of file ProcessGDBRemote.cpp.
References lldb_private::Process::DynamicLoader, lldb_private::DynamicLoader::FindPlugin(), and lldb_private::Process::m_dyld_up.
Referenced by LoadModuleAtAddress().
GetDynamicLoaderProcessState()
StructuredData::ObjectSP ProcessGDBRemote::GetDynamicLoaderProcessState () override virtual
Reimplemented from lldb_private::Process.
Definition at line 4317 of file ProcessGDBRemote.cpp.
References StringExtractor::Empty(), StringExtractorGDBRemote::eResponse, StringExtractorGDBRemote::GetResponseType(), StringExtractor::GetStringRef(), m_gdb_comm, lldb_private::StructuredData::ParseJSON(), StringExtractorGDBRemote::SetResponseValidatorToJSON(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetExtendedInfoForThread()
StructuredData::ObjectSP ProcessGDBRemote::GetExtendedInfoForThread (lldb::tid_t tid) protected
Definition at line 4210 of file ProcessGDBRemote.cpp.
References lldb_private::SystemRuntime::AddThreadExtendedInfoPacketHints(), StringExtractor::Empty(), StringExtractorGDBRemote::eResponse, StringExtractorGDBRemote::GetResponseType(), lldb_private::StreamString::GetString(), StringExtractor::GetStringRef(), lldb_private::Process::GetSystemRuntime(), m_gdb_comm, lldb_private::StructuredData::ParseJSON(), StringExtractorGDBRemote::SetResponseValidatorToJSON(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by lldb_private::process_gdb_remote::ThreadGDBRemote::FetchThreadExtendedInfo().
GetFileLoadAddress()
Status ProcessGDBRemote::GetFileLoadAddress (const FileSpec & file, bool & is_loaded, lldb::addr_t & load_addr) override virtual
Try to find the load address of a file.
The load address is defined as the address of the first memory region what contains data mapped from the specified file.
Parameters
[in] file The name of the file whose load address we are looking for
[out] is_loaded True if the file is loaded into the memory and false otherwise.
[out] load_addr The load address of the file if it is loaded into the processes address space, LLDB_INVALID_ADDRESS otherwise.
Reimplemented from lldb_private::Process.
Definition at line 5519 of file ProcessGDBRemote.cpp.
References lldb_private::Status::FromErrorString(), StringExtractorGDBRemote::GetError(), StringExtractor::GetHexMaxU64(), lldb_private::FileSpec::GetPath(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsErrorResponse(), StringExtractorGDBRemote::IsNormalResponse(), LLDB_INVALID_ADDRESS, m_gdb_comm, lldb_private::Stream::PutCString(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::Status, and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetGDBRemote()
GDBRemoteCommunicationClient & lldb_private::process_gdb_remote::ProcessGDBRemote::GetGDBRemote () inline
Definition at line 201 of file ProcessGDBRemote.h.
References GDBRemoteCommunicationClient, and m_gdb_comm.
Referenced by AsyncThread(), CalculateThreadStopInfo(), lldb_private::process_gdb_remote::ThreadGDBRemote::CreateRegisterContextForFrame(), CommandObjectProcessGDBRemotePacketMonitor::DoExecute(), CommandObjectProcessGDBRemotePacketSend::DoExecute(), CommandObjectProcessGDBRemoteSpeedTest::DoExecute(), and DumpPluginHistory().
GetGDBServerRegisterInfo()
llvm::Error ProcessGDBRemote::GetGDBServerRegisterInfo (ArchSpec & arch) protected
Definition at line 5225 of file ProcessGDBRemote.cpp.
References AddRemoteRegisters(), GetGDBServerRegisterInfoXMLAndProcess(), m_gdb_comm, m_register_info_sp, m_registers_enum_types, m_registers_flags_types, and lldb_private::XMLDocument::XMLEnabled().
Referenced by BuildDynamicRegisterInfo().
GetGDBServerRegisterInfoXMLAndProcess()
bool ProcessGDBRemote::GetGDBServerRegisterInfoXMLAndProcess (ArchSpec & arch_to_use, std::string xml_filename, std::vector< DynamicRegisterInfo::Register > & registers) protected
Definition at line 5070 of file ProcessGDBRemote.cpp.
References lldb_private::XMLNode::ForEachAttribute(), lldb_private::XMLNode::ForEachChildElement(), lldb_private::XMLNode::ForEachChildElementWithName(), lldb_private::XMLNode::GetAttributeValue(), lldb_private::XMLNode::GetElementText(), GetGDBServerRegisterInfoXMLAndProcess(), lldb_private::XMLNode::GetName(), lldb_private::XMLDocument::GetRootElement(), lldb_private::Process::GetTarget(), lldb_private::ArchSpec::IsValid(), m_gdb_comm, m_registers_enum_types, m_registers_flags_types, lldb_private::Target::MergeArchitecture(), lldb_private::XMLDocument::ParseMemory(), lldb_private::ArchSpec::SetTriple(), and UINT32_MAX.
Referenced by GetGDBServerRegisterInfo(), and GetGDBServerRegisterInfoXMLAndProcess().
GetHostMacCatalystVersion()
llvm::VersionTuple ProcessGDBRemote::GetHostMacCatalystVersion () override virtual
Returns
the macCatalyst version of the host OS.
Reimplemented from lldb_private::Process.
Definition at line 4516 of file ProcessGDBRemote.cpp.
References m_gdb_comm.
GetHostOSVersion()
llvm::VersionTuple ProcessGDBRemote::GetHostOSVersion () override virtual
Sometimes the connection to a process can detect the host OS version that the process is running on.
The current platform should be checked first in case the platform is connected, but clients can fall back onto this function if the platform fails to identify the host OS version. The platform should be checked first in case you are running a simulator platform that might itself be running natively, but have different heuristics for figuring out which OS is emulating.
Returns
Returns the version tuple of the host OS. In case of failure an empty VersionTuple is returner.
Reimplemented from lldb_private::Process.
Definition at line 4512 of file ProcessGDBRemote.cpp.
References m_gdb_comm.
GetImageInfoAddress()
addr_t ProcessGDBRemote::GetImageInfoAddress () override virtual
Get the image information address for the current process.
Some runtimes have system functions that can help dynamic loaders locate the dynamic loader information needed to observe shared libraries being loaded or unloaded. This function is in the Process interface (as opposed to the DynamicLoader interface) to ensure that remote debugging can take advantage of this functionality.
Returns
The address of the dynamic loader information, or LLDB_INVALID_ADDRESS if this is not supported by this interface.
Reimplemented from lldb_private::Process.
Definition at line 2682 of file ProcessGDBRemote.cpp.
References GetLoadedModuleList(), lldb_private::GetLog(), LLDB_INVALID_ADDRESS, LLDB_LOG_ERROR, m_gdb_comm, and lldb_private::process_gdb_remote::Process.
GetLoadedDynamicLibrariesInfos() [1/3]
StructuredData::ObjectSP ProcessGDBRemote::GetLoadedDynamicLibrariesInfos () override virtual
Reimplemented from lldb_private::Process.
Definition at line 4259 of file ProcessGDBRemote.cpp.
References GetLoadedDynamicLibrariesInfos_sender().
GetLoadedDynamicLibrariesInfos() [2/3]
StructuredData::ObjectSP ProcessGDBRemote::GetLoadedDynamicLibrariesInfos (const std::vector< lldb::addr_t > & load_addresses) override virtual
Reimplemented from lldb_private::Process.
Definition at line 4267 of file ProcessGDBRemote.cpp.
References GetLoadedDynamicLibrariesInfos_sender().
GetLoadedDynamicLibrariesInfos() [3/3]
StructuredData::ObjectSP ProcessGDBRemote::GetLoadedDynamicLibrariesInfos (lldb::addr_t image_list_address, lldb::addr_t image_count) override virtual
Retrieve the list of shared libraries that are loaded for this process This method is used on pre-macOS 10.12, pre-iOS 10, pre-tvOS 10, pre- watchOS 3 systems.
The following two methods are for newer versions of those OSes.
For certain platforms, the time it takes for the DynamicLoader plugin to read all of the shared libraries out of memory over a slow communication channel may be too long. In that instance, the gdb-remote stub may be able to retrieve the necessary information about the solibs out of memory and return a concise summary sufficient for the DynamicLoader plugin.
Parameters
[in] image_list_address The address where the table of shared libraries is stored in memory, if that is appropriate for this platform. Else this may be passed as LLDB_INVALID_ADDRESS.
[in] image_count The number of shared libraries that are present in this process, if that is appropriate for this platofrm Else this may be passed as LLDB_INVALID_ADDRESS.
Returns
A StructuredDataSP object which, if non-empty, will contain the information the DynamicLoader needs to get the initial scan of solibs resolved.
Reimplemented from lldb_private::Process.
Definition at line 4248 of file ProcessGDBRemote.cpp.
References GetLoadedDynamicLibrariesInfos_sender().
GetLoadedDynamicLibrariesInfos_sender()
StructuredData::ObjectSP ProcessGDBRemote::GetLoadedDynamicLibrariesInfos_sender (StructuredData::ObjectSP args)
Definition at line 4281 of file ProcessGDBRemote.cpp.
References StringExtractor::Empty(), StringExtractorGDBRemote::eResponse, StringExtractorGDBRemote::GetResponseType(), lldb_private::StreamString::GetString(), StringExtractor::GetStringRef(), m_gdb_comm, lldb_private::StructuredData::ParseJSON(), StringExtractorGDBRemote::SetResponseValidatorToJSON(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by GetLoadedDynamicLibrariesInfos(), GetLoadedDynamicLibrariesInfos(), and GetLoadedDynamicLibrariesInfos().
GetLoadedModuleList()
llvm::Expected< LoadedModuleInfoList > ProcessGDBRemote::GetLoadedModuleList () override virtual
Query remote GDBServer for a detailed loaded library list.
Returns
The list of modules currently loaded by the process, or an error.
Reimplemented from lldb_private::Process.
Definition at line 5261 of file ProcessGDBRemote.cpp.
References lldb_private::LoadedModuleInfoList::add(), lldb_private::XMLNode::FindFirstChildElementWithName(), lldb_private::XMLNode::ForEachAttribute(), lldb_private::XMLNode::ForEachChildElementWithName(), GDBRemoteCommunicationClient, lldb_private::XMLNode::GetAttributeValue(), GetGlobalPluginProperties(), lldb_private::GetLog(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetQXferLibrariesReadSupported(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetQXferLibrariesSVR4ReadSupported(), lldb_private::XMLDocument::GetRootElement(), LLDB_INVALID_ADDRESS, LLDB_LOGF, m_gdb_comm, lldb_private::LoadedModuleInfoList::m_link_map, lldb_private::LoadedModuleInfoList::m_list, lldb_private::XMLDocument::ParseMemory(), lldb_private::Process, lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ReadExtFeature(), and lldb_private::XMLDocument::XMLEnabled().
Referenced by GetImageInfoAddress(), and LoadModules().
GetMaxMemorySize()
void ProcessGDBRemote::GetMaxMemorySize () protected
Definition at line 4409 of file ProcessGDBRemote.cpp.
References lldb_private::process_gdb_remote::Comm, lldb_private::GetLog(), m_gdb_comm, m_max_memory_size, m_remote_stub_max_memory_size, lldb_private::process_gdb_remote::Memory, UINT64_MAX, and lldb_private::Log::Warning().
Referenced by DoReadMemory(), DoWriteMemory(), and SetUserSpecifiedMaxMemoryTransferSize().
GetModuleSpec()
bool ProcessGDBRemote::GetModuleSpec (const FileSpec & module_file_spec, const ArchSpec & arch, ModuleSpec & module_spec) override virtual
Try to fetch the module specification for a module with the given file name and architecture.
Process sub-classes have to override this method if they support platforms where the Platform object can't get the module spec for all module.
Parameters
[in] module_file_spec The file name of the module to get specification for.
[in] arch The architecture of the module to get specification for.
[out] module_spec The fetched module specification if the return value is true, unchanged otherwise.
Returns
Returns true if the module spec fetched successfully, false otherwise.
Reimplemented from lldb_private::Process.
Definition at line 4467 of file ProcessGDBRemote.cpp.
References lldb_private::ModuleSpec::Dump(), lldb_private::StreamString::GetData(), lldb_private::GetLog(), lldb_private::FileSpec::GetPath(), lldb_private::ArchSpec::GetTriple(), LLDB_LOGF, m_cached_module_specs, m_gdb_comm, and lldb_private::Platform.
GetPacketTimeout()
std::chrono::seconds ProcessGDBRemote::GetPacketTimeout () static
Definition at line 224 of file ProcessGDBRemote.cpp.
References GetGlobalPluginProperties(), and GetPacketTimeout().
Referenced by lldb_private::platform_gdb_server::PlatformRemoteGDBServer::ConnectRemote(), and GetPacketTimeout().
GetPluginCommandObject()
CommandObject * ProcessGDBRemote::GetPluginCommandObject () override virtual
Return a multi-word command object that can be used to expose plug-in specific commands.
This object will be used to resolve plug-in commands and can be triggered by a call to:
(lldb) process command <args>
Returns
A CommandObject which can be one of the concrete subclasses of CommandObject like CommandObjectRaw, CommandObjectParsed, or CommandObjectMultiword.
Reimplemented from lldb_private::Process.
Definition at line 6062 of file ProcessGDBRemote.cpp.
References lldb_private::Process::GetTarget(), and m_command_sp.
GetPluginDescriptionStatic()
llvm::StringRef ProcessGDBRemote::GetPluginDescriptionStatic () static
Definition at line 203 of file ProcessGDBRemote.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef lldb_private::process_gdb_remote::ProcessGDBRemote::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Reimplemented in lldb_private::wasm::ProcessWasm.
Definition at line 106 of file ProcessGDBRemote.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::process_gdb_remote::ProcessGDBRemote::GetPluginNameStatic () inline static
Definition at line 64 of file ProcessGDBRemote.h.
Referenced by lldb_private::PlatformQemuUser::DebugProcess(), GetPluginName(), and Initialize().
GetSharedCacheInfo()
StructuredData::ObjectSP ProcessGDBRemote::GetSharedCacheInfo () override virtual
Reimplemented from lldb_private::Process.
Definition at line 4339 of file ProcessGDBRemote.cpp.
References StringExtractor::Empty(), StringExtractorGDBRemote::eResponse, lldb::eSymbolSharedCacheUseHostAndInferiorSharedCache, lldb::eSymbolSharedCacheUseInferiorSharedCacheOnly, lldb_private::ModuleList::GetGlobalModuleListProperties(), StringExtractorGDBRemote::GetResponseType(), lldb_private::ModuleListProperties::GetSharedCacheBinaryLoading(), lldb_private::StreamString::GetString(), StringExtractor::GetStringRef(), lldb_private::StructuredData::Dictionary::GetValueForKey(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsString(), lldb_private::StructuredData::Dictionary::HasKey(), m_gdb_comm, m_shared_cache_info_mutex, m_shared_cache_info_sp, lldb_private::StructuredData::ParseJSON(), lldb_private::UUID::SetFromStringRef(), StringExtractorGDBRemote::SetResponseValidatorToJSON(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetSystemArchitecture()
ArchSpec ProcessGDBRemote::GetSystemArchitecture () override virtual
Get the system architecture for this process.
Reimplemented from lldb_private::Process.
Definition at line 228 of file ProcessGDBRemote.cpp.
References m_gdb_comm.
GetThreadStopInfoFromJSON()
bool ProcessGDBRemote::GetThreadStopInfoFromJSON (ThreadGDBRemote * thread, const StructuredData::ObjectSP & thread_infos_sp) protected
Definition at line 1703 of file ProcessGDBRemote.cpp.
References lldb_private::StructuredData::Array::GetItemAtIndex(), lldb_private::StructuredData::Array::GetSize(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsInteger(), LLDB_INVALID_THREAD_ID, SetThreadStopInfo(), and ThreadGDBRemote.
Referenced by CalculateThreadStopInfo().
GetWatchpointSlotCount()
std::optional< uint32_t > ProcessGDBRemote::GetWatchpointSlotCount () override virtual
Get the number of watchpoints supported by this target.
We may be able to determine the number of watchpoints available on this target; retrieve this value if possible.
This number may be less than the number of watchpoints a user can specify. This is because a single user watchpoint may require multiple watchpoint slots to implement. Due to the size and/or alignment of objects.
Returns
Returns the number of watchpoints, if available.
Reimplemented from lldb_private::Process.
Definition at line 3219 of file ProcessGDBRemote.cpp.
References m_gdb_comm.
HandleAsyncMisc()
void ProcessGDBRemote::HandleAsyncMisc (llvm::StringRef data) override private virtual
Implements lldb_private::process_gdb_remote::GDBRemoteClientBase::ContinueDelegate.
Definition at line 5577 of file ProcessGDBRemote.cpp.
References lldb_private::Process::BroadcastAsyncProfileData(), end_delimiter, end_delimiter_len, HarmonizeThreadIdsForProfileData(), and m_partial_profile_data.
HandleAsyncStdout()
void ProcessGDBRemote::HandleAsyncStdout (llvm::StringRef out) override private virtual
Implements lldb_private::process_gdb_remote::GDBRemoteClientBase::ContinueDelegate.
Definition at line 5570 of file ProcessGDBRemote.cpp.
References lldb_private::Process::AppendSTDOUT().
HandleAsyncStructuredDataPacket()
void ProcessGDBRemote::HandleAsyncStructuredDataPacket (llvm::StringRef data) override private virtual
Process asynchronously-received structured data.
Parameters
[in] data The complete data packet, expected to start with JSON-async.
Implements lldb_private::process_gdb_remote::GDBRemoteClientBase::ContinueDelegate.
Definition at line 5779 of file ProcessGDBRemote.cpp.
References ParseStructuredDataPacket(), and lldb_private::Process::RouteAsyncStructuredData().
HandleStopReply()
void ProcessGDBRemote::HandleStopReply () override private virtual
Implements lldb_private::process_gdb_remote::GDBRemoteClientBase::ContinueDelegate.
Definition at line 5677 of file ProcessGDBRemote.cpp.
References BuildDynamicRegisterInfo(), lldb_private::Process::GetID(), lldb_private::Process::GetStopID(), LLDB_INVALID_PROCESS_ID, m_gdb_comm, and lldb_private::Process::SetID().
HandleThreadAsyncInterrupt()
ThreadSP ProcessGDBRemote::HandleThreadAsyncInterrupt (uint8_t signo, const std::string & description) override private virtual
Handle thread specific async interrupt and return the original thread that requested the async interrupt.
It can be null if original thread has exited.
Parameters
[in] description Returns the stop reason description of the async interrupt.
Reimplemented from lldb_private::Process.
Definition at line 2090 of file ProcessGDBRemote.cpp.
References lldb_private::StopInfo::CreateStopReasonWithInterrupt(), LLDB_INVALID_THREAD_ID, lldb_private::Process::m_interrupt_tid, and lldb_private::Process::m_thread_list_real.
Referenced by SetThreadStopInfo().
HarmonizeThreadIdsForProfileData()
std::string ProcessGDBRemote::HarmonizeThreadIdsForProfileData (StringExtractorGDBRemote & inputStringExtractor)
Definition at line 5602 of file ProcessGDBRemote.cpp.
References lldb_private::Process::AssignIndexIDToThread(), end_delimiter, StringExtractor::GetFilePos(), StringExtractor::GetHexMaxU64(), StringExtractor::GetNameColonValue(), lldb_private::Process::HasAssignedIndexIDToThread(), m_thread_id_to_used_usec_map, and StringExtractor::SetFilePos().
Referenced by CommandObjectProcessGDBRemotePacketSend::DoExecute(), and HandleAsyncMisc().
HasErased()
bool ProcessGDBRemote::HasErased (FlashRange range) protected
Definition at line 2983 of file ProcessGDBRemote.cpp.
References m_erased_flash_ranges.
Referenced by FlashErase().
HasExited()
bool lldb_private::process_gdb_remote::ProcessGDBRemote::HasExited (lldb::StateType state) inline protected
Definition at line 337 of file ProcessGDBRemote.h.
References lldb::eStateExited.
Initialize()
void ProcessGDBRemote::Initialize () static
Definition at line 3843 of file ProcessGDBRemote.cpp.
References CreateInstance(), DebuggerInitialize(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
IsAlive()
bool ProcessGDBRemote::IsAlive () override virtual
Check if a process is still alive.
Returns
Returns true if the process is still valid, false otherwise.
Reimplemented from lldb_private::Process.
Definition at line 2678 of file ProcessGDBRemote.cpp.
References lldb_private::Process::IsAlive(), and m_gdb_comm.
IsRunning()
bool lldb_private::process_gdb_remote::ProcessGDBRemote::IsRunning (lldb::StateType state) inline protected
Definition at line 327 of file ProcessGDBRemote.h.
References lldb::eStateRunning, and IsStepping().
IsStepping()
bool lldb_private::process_gdb_remote::ProcessGDBRemote::IsStepping (lldb::StateType state) inline protected
Definition at line 331 of file ProcessGDBRemote.h.
References lldb::eStateStepping.
Referenced by IsRunning().
KillDebugserverProcess()
void ProcessGDBRemote::KillDebugserverProcess () protected
Definition at line 3835 of file ProcessGDBRemote.cpp.
References lldb_private::Host::Kill(), LLDB_INVALID_PROCESS_ID, m_debugserver_pid, and m_gdb_comm.
Referenced by DoDestroy(), DoLaunch(), and ~ProcessGDBRemote().
LaunchAndConnectToDebugserver()
Status ProcessGDBRemote::LaunchAndConnectToDebugserver (const ProcessInfo & process_info) protected
Definition at line 3700 of file ProcessGDBRemote.cpp.
References lldb_private::SharedSocket::CompleteSending(), ConnectToDebugserver(), lldb_private::Socket::CreatePair(), DEBUGSERVER_BASENAME, error(), lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), GetDebugserverPath(), lldb_private::GetLog(), lldb_private::ProcessInfo::GetProcessID(), lldb_private::SharedSocket::GetSendableFD(), lldb_private::Process::GetTarget(), lldb_private::ProcessInfo::GetUserID(), lldb_private::FileSystem::Instance(), LLDB_INVALID_PROCESS_ID, LLDB_LOGF, m_debugserver_pid, m_gdb_comm, MonitorDebugserverProcess(), lldb_private::process_gdb_remote::Process, lldb_private::ProcessInfo::SetExecutableFile(), lldb_private::ProcessLaunchInfo::SetLaunchInSeparateProcessGroup(), lldb_private::ProcessLaunchInfo::SetMonitorProcessCallback(), lldb_private::ProcessInfo::SetUserID(), StartAsyncThread(), and lldb_private::Status.
Referenced by EstablishConnectionIfNeeded().
LoadModuleAtAddress()
lldb::ModuleSP ProcessGDBRemote::LoadModuleAtAddress (const FileSpec & file, lldb::addr_t link_map, lldb::addr_t base_addr, bool value_is_offset) protected
Definition at line 5426 of file ProcessGDBRemote.cpp.
References lldb_private::Process::DynamicLoader, GetDynamicLoader(), and lldb_private::DynamicLoader::LoadModuleAtAddress().
Referenced by LoadModules().
LoadModules()
llvm::Error ProcessGDBRemote::LoadModules () override virtual
Sometimes processes know how to retrieve and load shared libraries.
This is normally done by DynamicLoader plug-ins, but sometimes the connection to the process allows retrieving this information. The dynamic loader plug-ins can use this function if they can't determine the current shared library load state.
Returns
A status object indicating if the operation was sucessful or not.
Reimplemented from lldb_private::Process.
Definition at line 5438 of file ProcessGDBRemote.cpp.
References lldb_private::ModuleList::Append(), lldb_private::ModuleList::AppendIfNeeded(), lldb_private::Continue, lldb_private::eLoadDependentsNo, lldb_private::ObjectFile::eTypeExecutable, lldb_private::ModuleList::ForEach(), lldb_private::LoadedModuleInfoList::LoadedModuleInfo::get_base(), lldb_private::LoadedModuleInfoList::LoadedModuleInfo::get_base_is_offset(), lldb_private::LoadedModuleInfoList::LoadedModuleInfo::get_link_map(), lldb_private::LoadedModuleInfoList::LoadedModuleInfo::get_name(), lldb_private::Target::GetExecutableModulePointer(), GetLoadedModuleList(), lldb_private::ModuleList::GetModuleAtIndex(), lldb_private::ModuleList::GetSize(), lldb_private::Process::GetTarget(), lldb_private::ObjectFile::GetType(), lldb_private::FileSystem::Instance(), LLDB_INVALID_ADDRESS, LoadModuleAtAddress(), lldb_private::ProcessProperties::m_process, lldb_private::ModuleList::Remove(), lldb_private::FileSystem::Resolve(), lldb_private::Target::SetExecutableModule(), lldb_private::Stop, and lldb_private::Process::Target.
Referenced by SetThreadStopInfo().
LoadStubBinaries()
void ProcessGDBRemote::LoadStubBinaries () protected
Definition at line 1057 of file ProcessGDBRemote.cpp.
References lldb_private::Process::GetTarget(), lldb_private::UUID::IsValid(), lldb_private::DynamicLoader::LoadBinaryWithUUIDAndAddress(), and m_gdb_comm.
Referenced by DidLaunchOrAttach().
MaybeLoadExecutableModule()
void ProcessGDBRemote::MaybeLoadExecutableModule () protected
Definition at line 1116 of file ProcessGDBRemote.cpp.
References lldb_private::ModuleList::Append(), lldb_private::Target::GetExecutableModule(), lldb_private::Process::GetTarget(), m_gdb_comm, and lldb_private::ProcessProperties::m_process.
Referenced by DidLaunchOrAttach().
ModulesDidLoad()
void ProcessGDBRemote::ModulesDidLoad (ModuleList & module_list) override virtual
Reimplemented from lldb_private::Process.
Definition at line 5560 of file ProcessGDBRemote.cpp.
References m_gdb_comm, and lldb_private::Process::ModulesDidLoad().
MonitorDebugserverProcess()
void ProcessGDBRemote::MonitorDebugserverProcess (std::weak_ptr< ProcessGDBRemote > process_wp, lldb::pid_t pid, int signo, int exit_status) static protected
Definition at line 3784 of file ProcessGDBRemote.cpp.
References DEBUGSERVER_BASENAME, lldb::eStateDetached, lldb::eStateExited, lldb::eStateInvalid, lldb::eStateUnloaded, lldb_private::Stream::Format(), lldb_private::GetLog(), lldb_private::StreamString::GetString(), LLDB_INVALID_PROCESS_ID, LLDB_LOGF, and lldb_private::process_gdb_remote::Process.
Referenced by LaunchAndConnectToDebugserver().
NewThreadNotifyBreakpointHit()
bool ProcessGDBRemote::NewThreadNotifyBreakpointHit (void * baton, StoppointCallbackContext * context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id) static private
Definition at line 4087 of file ProcessGDBRemote.cpp.
References lldb_private::GetLog(), LLDB_LOGF, and lldb_private::Step.
Referenced by StartNoticingNewThreads().
operator=()
const ProcessGDBRemote & lldb_private::process_gdb_remote::ProcessGDBRemote::operator= (const ProcessGDBRemote &) private delete
References ProcessGDBRemote().
ParseExpeditedRegisters()
void ProcessGDBRemote::ParseExpeditedRegisters (ExpeditedRegisterMap & expedited_register_map, lldb::ThreadSP thread_sp) private
Definition at line 1752 of file ProcessGDBRemote.cpp.
References lldb::eRegisterKindProcessPlugin, StringExtractor::GetHexBytes(), lldb_private::process_gdb_remote::ThreadGDBRemote::GetRegisterContext(), StringExtractor::GetStringRef(), lldb_private::process_gdb_remote::ThreadGDBRemote::PrivateSetRegisterValue(), and ThreadGDBRemote.
Referenced by SetThreadStopInfo().
ParseMultiMemReadPacket()
llvm::Error ProcessGDBRemote::ParseMultiMemReadPacket (llvm::StringRef response_str, llvm::MutableArrayRef< uint8_t > buffer, unsigned expected_num_ranges, llvm::SmallVectorImpl< llvm::MutableArrayRef< uint8_t > > & memory_regions) private
Definition at line 2891 of file ProcessGDBRemote.cpp.
Referenced by ReadMemoryRanges().
ParsePythonTargetDefinition()
bool ProcessGDBRemote::ParsePythonTargetDefinition (const FileSpec & target_definition_fspec) protected
Definition at line 332 of file ProcessGDBRemote.cpp.
References error(), lldb_private::Target::GetDebugger(), lldb_private::ScriptInterpreter::GetDynamicSettings(), lldb_private::Debugger::GetScriptInterpreter(), lldb_private::Process::GetTarget(), lldb_private::ArchSpec::IsCompatibleMatch(), lldb_private::ScriptInterpreter::LoadPluginModule(), m_breakpoint_pc_offset, m_register_info_sp, and lldb_private::Target::SetArchitecture().
Referenced by BuildDynamicRegisterInfo().
PrefetchModuleSpecs()
void ProcessGDBRemote::PrefetchModuleSpecs (llvm::ArrayRef< FileSpec > module_file_specs, const llvm::Triple & triple) override virtual
Reimplemented from lldb_private::Process.
Definition at line 4499 of file ProcessGDBRemote.cpp.
References m_cached_module_specs, and m_gdb_comm.
PutSTDIN()
size_t ProcessGDBRemote::PutSTDIN (const char * buf, size_t buf_size, Status & error) override virtual
Puts data into this process's STDIN.
Calling this method is a valid operation only if all of the following conditions are true: 1) The process was launched, and not attached to. 2) The process was not launched with eLaunchFlagDisableSTDIO. 3) The process was launched without supplying a valid file path for STDIN.
Parameters
[in] buf A buffer that contains the data to write to the process's STDIN.
[in] buf_size The size in bytes for the buffer buf.
Returns
The number of bytes written into buf. If this value is less than buf_size, another call to this function should be made to write the rest of the data.
Reimplemented from lldb_private::Process.
Definition at line 3263 of file ProcessGDBRemote.cpp.
References error(), m_gdb_comm, lldb_private::Process::m_stdin_forward, and lldb_private::Process::m_stdio_communication.
ReadMemoryRanges()
llvm::SmallVector< llvm::MutableArrayRef< uint8_t > > ProcessGDBRemote::ReadMemoryRanges (llvm::ArrayRef< Range< lldb::addr_t, size_t > > ranges, llvm::MutableArrayRef< uint8_t > buf) override virtual
Override of ReadMemoryRanges that uses MultiMemRead to optimize this operation.
Reimplemented from lldb_private::Process.
Definition at line 2820 of file ProcessGDBRemote.cpp.
References ComputeNumRangesMultiMemRead(), error(), lldb_private::GetLog(), LLDB_LOG_ERROR, m_gdb_comm, m_max_memory_size, ParseMultiMemReadPacket(), lldb_private::process_gdb_remote::Process, lldb_private::Process::ReadMemoryRanges(), and SendMultiMemReadPacket().
RefreshStateAfterStop()
void ProcessGDBRemote::RefreshStateAfterStop () override virtual
Currently called as part of ShouldStop.
FIXME: Should really happen when the target stops before the event is taken from the queue...
This callback is called as the event is about to be queued up to allow Process plug-ins to execute some code prior to clients being notified that a process was stopped. Common operations include updating the thread list, invalidating any thread state (registers, stack, etc) prior to letting the notification go out.
Implements lldb_private::Process.
Definition at line 2514 of file ProcessGDBRemote.cpp.
References LLDB_INVALID_THREAD_ID, m_initial_tid, m_last_stop_packet, m_thread_ids, lldb_private::Process::m_thread_list, lldb_private::Process::m_thread_list_real, m_thread_pcs, SetThreadStopInfo(), UpdateThreadIDList(), and lldb_private::Process::UpdateThreadListIfNeeded().
RemoveNewThreadBreakpoints()
void ProcessGDBRemote::RemoveNewThreadBreakpoints () private
Remove the breakpoints associated with thread creation from the Target.
Definition at line 2647 of file ProcessGDBRemote.cpp.
References lldb_private::Process::m_target_wp, and m_thread_create_bp_sp.
Referenced by DoDestroy().
SaveCore()
llvm::Expected< bool > ProcessGDBRemote::SaveCore (llvm::StringRef outfile) override virtual
Save core dump into the specified file.
Parameters
[in] outfile Path to store core dump in.
Returns
true if saved successfully, false if saving the core dump is not supported by the plugin, error otherwise.
Reimplemented from lldb_private::Process.
Definition at line 5689 of file ProcessGDBRemote.cpp.
References error(), lldb_private::Platform::GetFile(), StringExtractor::GetHexByteString(), lldb_private::Target::GetPlatform(), lldb_private::StreamString::GetString(), StringExtractor::GetStringRef(), lldb_private::Process::GetTarget(), StringExtractorGDBRemote::IsErrorResponse(), lldb_private::Platform::IsRemote(), m_gdb_comm, lldb_private::Stream::PutCString(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and lldb_private::Platform::Unlink().
SendEventData()
Status ProcessGDBRemote::SendEventData (const char * data) override virtual
Reimplemented from lldb_private::Process.
Definition at line 4178 of file ProcessGDBRemote.cpp.
References error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), and m_gdb_comm.
SendMultiMemReadPacket()
llvm::Expected< StringExtractorGDBRemote > ProcessGDBRemote::SendMultiMemReadPacket (llvm::ArrayRef< Range< lldb::addr_t, size_t > > ranges) private
Definition at line 2859 of file ProcessGDBRemote.cpp.
References lldb_private::ProcessProperties::GetInterruptTimeout(), StringExtractor::GetStringRef(), StringExtractorGDBRemote::IsErrorResponse(), StringExtractorGDBRemote::IsNormalResponse(), m_gdb_comm, and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by ReadMemoryRanges().
SetLastStopPacket()
void ProcessGDBRemote::SetLastStopPacket (const StringExtractorGDBRemote & response) protected
Definition at line 2655 of file ProcessGDBRemote.cpp.
References BuildDynamicRegisterInfo(), lldb_private::GetLog(), StringExtractor::GetStringRef(), LLDB_LOGF, m_gdb_comm, m_last_stop_packet, lldb_private::Process::m_thread_list, lldb_private::Process::m_thread_list_real, and lldb_private::process_gdb_remote::Process.
Referenced by AsyncThread(), DoConnectRemote(), and DoLaunch().
SetThreadPc()
void ProcessGDBRemote::SetThreadPc (const lldb::ThreadSP & thread_sp, uint64_t index) private
Definition at line 1687 of file ProcessGDBRemote.cpp.
References lldb::eByteOrderInvalid, lldb::eRegisterKindGeneric, lldb_private::Process::GetByteOrder(), LLDB_INVALID_REGNUM, LLDB_REGNUM_GENERIC_PC, m_thread_ids, m_thread_pcs, lldb_private::process_gdb_remote::ThreadGDBRemote::PrivateSetRegisterValue(), and ThreadGDBRemote.
Referenced by DoUpdateThreadList(), and SetThreadStopInfo().
SetThreadStopInfo() [1/3]
ThreadSP ProcessGDBRemote::SetThreadStopInfo (lldb::tid_t tid, ExpeditedRegisterMap & expedited_register_map, uint8_t signo, const std::string & thread_name, const std::string & reason, const std::string & description, uint32_t exc_type, const std::vector< lldb::addr_t > & exc_data, lldb::addr_t thread_dispatch_qaddr, bool queue_vars_valid, lldb_private::LazyBool associated_with_libdispatch_queue, lldb::addr_t dispatch_queue_t, std::string & queue_name, lldb::QueueKind queue_kind, uint64_t queue_serial) protected
Definition at line 1768 of file ProcessGDBRemote.cpp.
References lldb_private::process_gdb_remote::ThreadGDBRemote::ClearQueueInfo(), lldb_private::StopInfo::CreateStopReasonFork(), lldb_private::StopInfo::CreateStopReasonHistoryBoundary(), lldb_private::StopInfo::CreateStopReasonProcessorTrace(), lldb_private::StopInfo::CreateStopReasonToTrace(), lldb_private::StopInfo::CreateStopReasonVFork(), lldb_private::StopInfo::CreateStopReasonVForkDone(), lldb_private::StopInfo::CreateStopReasonWithBreakpointSiteID(), lldb_private::StopInfo::CreateStopReasonWithException(), lldb_private::StopInfo::CreateStopReasonWithExec(), lldb_private::StopInfoMachException::CreateStopReasonWithMachException(), lldb_private::StopInfo::CreateStopReasonWithSignal(), lldb_private::StopInfo::CreateStopReasonWithWatchpointID(), CreateThread(), lldb::eStateStepping, lldb::eStateSuspended, lldb_private::Target::GetArchitecture(), lldb_private::ArchSpec::GetCore(), lldb_private::GetLog(), lldb_private::process_gdb_remote::ThreadGDBRemote::GetRegisterContext(), lldb_private::Process::GetTarget(), StringExtractor::GetU64(), HandleThreadAsyncInterrupt(), lldb_private::ArchSpec::kCore_mips_first, lldb_private::ArchSpec::kCore_mips_last, LLDB_INVALID_ADDRESS, LLDB_INVALID_PROCESS_ID, LLDB_INVALID_SITE_ID, LLDB_INVALID_THREAD_ID, LLDB_INVALID_WATCH_ID, LLDB_LOGF, m_breakpoint_pc_offset, lldb_private::Process::m_interrupt_tid, m_thread_ids, lldb_private::Process::m_thread_list_real, lldb_private::Process::m_watchpoint_resource_list, ParseExpeditedRegisters(), pc, lldb_private::process_gdb_remote::ThreadGDBRemote::SetAssociatedWithLibdispatchQueue(), lldb_private::process_gdb_remote::ThreadGDBRemote::SetQueueInfo(), lldb_private::process_gdb_remote::ThreadGDBRemote::SetQueueLibdispatchQueueAddress(), lldb_private::process_gdb_remote::ThreadGDBRemote::SetThreadDispatchQAddr(), SetThreadPc(), SIGTRAP, ThreadGDBRemote, and lldb_private::process_gdb_remote::Watchpoints.
SetThreadStopInfo() [2/3]
StateType ProcessGDBRemote::SetThreadStopInfo (StringExtractor & stop_packet) protected
Definition at line 2263 of file ProcessGDBRemote.cpp.
References BuildDynamicRegisterInfo(), lldb_private::eLazyBoolCalculate, lldb::eQueueKindConcurrent, lldb::eQueueKindSerial, lldb::eQueueKindUnknown, error(), lldb::eStateExited, lldb::eStateInvalid, lldb::eStateStopped, StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), StringExtractor::GetHexBytes(), StringExtractor::GetHexByteString(), StringExtractor::GetHexU8(), lldb_private::Process::GetID(), lldb_private::GetLog(), StringExtractor::GetNameColonValue(), StringExtractorGDBRemote::GetPidTid(), lldb_private::Process::GetStopID(), lldb_private::StreamString::GetString(), LLDB_INVALID_ADDRESS, LLDB_INVALID_PROCESS_ID, LLDB_INVALID_THREAD_ID, LLDB_LOG, LLDB_LOG_ERROR, LoadModules(), m_gdb_comm, m_jstopinfo_sp, lldb_private::Process::m_memory_cache, m_thread_ids, lldb_private::Process::m_thread_list_real, m_thread_pcs, lldb_private::Process::m_watchpoint_resource_list, lldb_private::StructuredData::ParseJSON(), pc, lldb_private::Stream::Printf(), lldb_private::process_gdb_remote::Process, lldb_private::Process::SetAddressableBitMasks(), lldb_private::AddressableBits::SetAddressableBits(), StringExtractor::SetFilePos(), lldb_private::AddressableBits::SetHighmemAddressableBits(), lldb_private::Process::SetID(), lldb_private::AddressableBits::SetLowmemAddressableBits(), SetThreadStopInfo(), UINT32_MAX, UpdateThreadIDList(), and UpdateThreadIDsFromStopReplyThreadsValue().
Referenced by CalculateThreadStopInfo(), DoConnectRemote(), DoLaunch(), GetThreadStopInfoFromJSON(), RefreshStateAfterStop(), SetThreadStopInfo(), SetThreadStopInfo(), UpdateThreadIDList(), and WillPublicStop().
SetThreadStopInfo() [3/3]
lldb::ThreadSP ProcessGDBRemote::SetThreadStopInfo (StructuredData::Dictionary * thread_dict) protected
Definition at line 2108 of file ProcessGDBRemote.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb::eQueueKindConcurrent, lldb::eQueueKindSerial, lldb::eQueueKindUnknown, lldb_private::StructuredData::Array::ForEach(), lldb_private::StructuredData::Dictionary::ForEach(), lldb_private::StructuredData::Object::GetAsArray(), lldb_private::StructuredData::Object::GetAsDictionary(), StringExtractor::GetHexBytes(), StringExtractor::GetStringRef(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsInteger(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsString(), LLDB_INVALID_ADDRESS, LLDB_INVALID_SIGNAL_NUMBER, LLDB_INVALID_THREAD_ID, lldb_private::Process::m_memory_cache, StringExtractor::SetFilePos(), and SetThreadStopInfo().
SetUnixSignals()
void ProcessGDBRemote::SetUnixSignals (const lldb::UnixSignalsSP & signals_sp)
Definition at line 2672 of file ProcessGDBRemote.cpp.
References lldb_private::Process::SetUnixSignals().
Referenced by DidLaunchOrAttach().
SetUserSpecifiedMaxMemoryTransferSize()
void ProcessGDBRemote::SetUserSpecifiedMaxMemoryTransferSize (uint64_t user_specified_max)
Definition at line 4446 of file ProcessGDBRemote.cpp.
References GetMaxMemorySize(), m_max_memory_size, and m_remote_stub_max_memory_size.
Referenced by CommandObjectProcessGDBRemotePacketXferSize::DoExecute().
StartAsyncThread()
bool ProcessGDBRemote::StartAsyncThread () protected
Definition at line 3863 of file ProcessGDBRemote.cpp.
References AsyncThread(), lldb_private::GetLog(), lldb_private::Host, lldb_private::ThreadLauncher::LaunchThread(), LLDB_LOG_ERROR, LLDB_LOGF, m_async_thread, m_async_thread_state_mutex, and lldb_private::process_gdb_remote::Process.
Referenced by DoConnectRemote(), and LaunchAndConnectToDebugserver().
StartNoticingNewThreads()
bool ProcessGDBRemote::StartNoticingNewThreads () override virtual
Call this to set the lldb in the mode where it breaks on new thread creations, and then auto-restarts.
This is useful when you are trying to run only one thread, but either that thread or the kernel is creating new threads in the process. If you stop when the thread is created, you can immediately suspend it, and keep executing only the one thread you intend.
Returns
Returns true if we were able to start up the notification false otherwise.
Reimplemented from lldb_private::Process.
Definition at line 4135 of file ProcessGDBRemote.cpp.
References lldb_private::GetLog(), lldb_private::Process::GetTarget(), lldb_private::Log::GetVerbose(), LLDB_LOGF, m_thread_create_bp_sp, NewThreadNotifyBreakpointHit(), and lldb_private::Step.
StopAsyncThread()
void ProcessGDBRemote::StopAsyncThread () protected
Definition at line 3892 of file ProcessGDBRemote.cpp.
References eBroadcastBitAsyncThreadShouldExit, lldb_private::GetLog(), LLDB_LOGF, m_async_broadcaster, m_async_thread, m_async_thread_state_mutex, m_gdb_comm, and lldb_private::process_gdb_remote::Process.
Referenced by DoDestroy(), DoDetach(), and ~ProcessGDBRemote().
StopNoticingNewThreads()
bool ProcessGDBRemote::StopNoticingNewThreads () override virtual
Call this to turn off the stop & notice new threads mode.
Returns
Returns true if we were able to start up the notification false otherwise.
Reimplemented from lldb_private::Process.
Definition at line 4161 of file ProcessGDBRemote.cpp.
References lldb_private::GetLog(), lldb_private::Log::GetVerbose(), LLDB_LOGF, m_thread_create_bp_sp, and lldb_private::Step.
SupportsMemoryTagging()
bool ProcessGDBRemote::SupportsMemoryTagging () override protected virtual
Check whether the process supports memory tagging.
Returns
true if the process supports memory tagging, false otherwise.
Reimplemented from lldb_private::Process.
Definition at line 2929 of file ProcessGDBRemote.cpp.
References m_gdb_comm.
SupportsReverseDirection()
bool ProcessGDBRemote::SupportsReverseDirection () override virtual
Reports whether this process supports reverse execution.
Returns
Returns true if the process supports reverse execution (at least under some circumstances).
Reimplemented from lldb_private::Process.
Definition at line 1256 of file ProcessGDBRemote.cpp.
References m_gdb_comm.
Terminate()
void ProcessGDBRemote::Terminate () static
Definition at line 207 of file ProcessGDBRemote.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
TraceGetBinaryData()
llvm::Expected< std::vector< uint8_t > > ProcessGDBRemote::TraceGetBinaryData (const TraceGetBinaryDataRequest & request) override virtual
Get binary data given a trace technology and a data identifier.
Parameters
[in] request Object with the params of the requested data.
Returns
A vector of bytes with the requested data, or an llvm::Error in case of failures.
Reimplemented from lldb_private::Process.
Definition at line 1230 of file ProcessGDBRemote.cpp.
References lldb_private::ProcessProperties::GetInterruptTimeout(), and m_gdb_comm.
TraceGetState()
llvm::Expected< std::string > ProcessGDBRemote::TraceGetState (llvm::StringRef type) override virtual
Get the current tracing state of the process and its threads.
Parameters
[in] type Tracing technology type to consider.
Returns
A JSON object string with custom data depending on the trace technology, or an llvm::Error in case of errors.
Reimplemented from lldb_private::Process.
Definition at line 1225 of file ProcessGDBRemote.cpp.
References lldb_private::ProcessProperties::GetInterruptTimeout(), and m_gdb_comm.
TraceStart()
llvm::Error ProcessGDBRemote::TraceStart (const llvm::json::Value & request) override virtual
Start tracing a process or its threads.
Parameters
[in] request JSON object with the information necessary to start tracing. In the case of gdb-remote processes, this JSON object should conform to the jLLDBTraceStart packet.
Returns
llvm::Error::success if the operation was successful, or llvm::Error otherwise.
Reimplemented from lldb_private::Process.
Definition at line 1220 of file ProcessGDBRemote.cpp.
References lldb_private::ProcessProperties::GetInterruptTimeout(), and m_gdb_comm.
TraceStop()
llvm::Error ProcessGDBRemote::TraceStop (const TraceStopRequest & request) override virtual
Stop tracing a live process or its threads.
Parameters
[in] request The information determining which threads or process to stop tracing.
Returns
llvm::Error::success if the operation was successful, or llvm::Error otherwise.
Reimplemented from lldb_private::Process.
Definition at line 1216 of file ProcessGDBRemote.cpp.
References lldb_private::ProcessProperties::GetInterruptTimeout(), and m_gdb_comm.
TraceSupported()
llvm::Expected< TraceSupportedResponse > ProcessGDBRemote::TraceSupported () override virtual
Get the processor tracing type supported for this process.
Responses might be different depending on the architecture and capabilities of the underlying OS.
Returns
The supported trace type or an llvm::Error if tracing is not supported for the inferior.
Reimplemented from lldb_private::Process.
Definition at line 1212 of file ProcessGDBRemote.cpp.
References lldb_private::ProcessProperties::GetInterruptTimeout(), and m_gdb_comm.
UpdateAutomaticSignalFiltering()
Status ProcessGDBRemote::UpdateAutomaticSignalFiltering () override protected virtual
Reimplemented from lldb_private::Process.
Definition at line 4098 of file ProcessGDBRemote.cpp.
References error(), lldb_private::GetLog(), LLDB_LOG, m_gdb_comm, m_last_signals_version, lldb_private::Process::m_unix_signals_sp, lldb_private::process_gdb_remote::Process, and lldb_private::Status.
UpdateThreadIDList()
bool ProcessGDBRemote::UpdateThreadIDList () protected
Definition at line 1574 of file ProcessGDBRemote.cpp.
References lldb_private::StructuredData::Array::ForEach(), lldb_private::StructuredData::Object::GetAsDictionary(), lldb_private::StructuredData::Array::GetSize(), StringExtractor::GetStringRef(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsInteger(), LLDB_INVALID_THREAD_ID, m_gdb_comm, m_jthreadsinfo_sp, m_last_stop_packet, m_thread_ids, lldb_private::Process::m_thread_list_real, m_thread_pcs, SetThreadStopInfo(), UpdateThreadIDsFromStopReplyThreadsValue(), and UpdateThreadPCsFromStopReplyThreadsValue().
Referenced by DoUpdateThreadList(), RefreshStateAfterStop(), and SetThreadStopInfo().
UpdateThreadIDsFromStopReplyThreadsValue()
size_t ProcessGDBRemote::UpdateThreadIDsFromStopReplyThreadsValue (llvm::StringRef value) protected
Definition at line 1544 of file ProcessGDBRemote.cpp.
References StringExtractorGDBRemote::AllProcesses, StringExtractor::GetChar(), StringExtractorGDBRemote::GetPidTid(), LLDB_INVALID_THREAD_ID, m_gdb_comm, and m_thread_ids.
Referenced by SetThreadStopInfo(), and UpdateThreadIDList().
UpdateThreadPCsFromStopReplyThreadsValue()
size_t ProcessGDBRemote::UpdateThreadPCsFromStopReplyThreadsValue (llvm::StringRef value) protected
Definition at line 1563 of file ProcessGDBRemote.cpp.
References m_thread_pcs, and pc.
Referenced by UpdateThreadIDList().
WillLaunchOrAttach()
Status ProcessGDBRemote::WillLaunchOrAttach ()
Definition at line 680 of file ProcessGDBRemote.cpp.
References error(), and lldb_private::Process::m_stdio_communication.
Referenced by DoConnectRemote(), DoWillAttachToProcessWithID(), DoWillAttachToProcessWithName(), and DoWillLaunch().
WillPublicStop()
void ProcessGDBRemote::WillPublicStop () override virtual
Called when the process is about to broadcast a public stop.
There are public and private stops. Private stops are when the process is doing things like stepping and the client doesn't need to know about starts and stop that implement a thread plan. Single stepping over a source line in code might end up being implemented by one or more process starts and stops. Public stops are when clients will be notified that the process is stopped. These events typically trigger UI updates (thread stack frames to be displayed, variables to be displayed, and more). This function can be overriden and allows process subclasses to do something before the eBroadcastBitStateChanged event is sent to public clients.
Reimplemented from lldb_private::Process.
Definition at line 2700 of file ProcessGDBRemote.cpp.
References lldb_private::StructuredData::Array::GetItemAtIndex(), lldb_private::StructuredData::Array::GetSize(), m_gdb_comm, m_jthreadsinfo_sp, and SetThreadStopInfo().
WillResume()
Status ProcessGDBRemote::WillResume () override virtual
Called before resuming to a process.
Allow Process plug-ins to execute some code before resuming a process.
Returns
Returns an error object.
Reimplemented from lldb_private::Process.
Definition at line 1245 of file ProcessGDBRemote.cpp.
References m_continue_C_tids, m_continue_c_tids, m_continue_S_tids, m_continue_s_tids, m_jstopinfo_sp, m_jthreadsinfo_sp, m_shared_cache_info_sp, and lldb_private::Status.
WriteObjectFile()
Status ProcessGDBRemote::WriteObjectFile (std::vector< ObjectFile::LoadableData > entries) override virtual
Reimplemented from lldb_private::Process.
Definition at line 2960 of file ProcessGDBRemote.cpp.
References lldb_private::ObjectFile::LoadableData::Dest, error(), FlashDone(), m_allow_flash_writes, and lldb_private::Process::WriteObjectFile().
Friends And Related Symbol Documentation
GDBRemoteCommunicationClient
friend class GDBRemoteCommunicationClient friend
Definition at line 260 of file ProcessGDBRemote.h.
References GDBRemoteCommunicationClient.
Referenced by DumpPluginHistory(), GDBRemoteCommunicationClient, GetGDBRemote(), and GetLoadedModuleList().
GDBRemoteRegisterContext
friend class GDBRemoteRegisterContext friend
Definition at line 261 of file ProcessGDBRemote.h.
References GDBRemoteRegisterContext.
Referenced by GDBRemoteRegisterContext.
ThreadGDBRemote
friend class ThreadGDBRemote friend
Definition at line 259 of file ProcessGDBRemote.h.
References ThreadGDBRemote.
Referenced by CalculateThreadStopInfo(), GetThreadStopInfoFromJSON(), ParseExpeditedRegisters(), SetThreadPc(), SetThreadStopInfo(), and ThreadGDBRemote.
Member Data Documentation
m_addr_to_mmap_size
MMapMap lldb_private::process_gdb_remote::ProcessGDBRemote::m_addr_to_mmap_size protected
Definition at line 310 of file ProcessGDBRemote.h.
Referenced by DoAllocateMemory(), DoDeallocateMemory(), and ProcessGDBRemote().
m_allow_flash_writes
bool lldb_private::process_gdb_remote::ProcessGDBRemote::m_allow_flash_writes protected
Definition at line 318 of file ProcessGDBRemote.h.
Referenced by DoWriteMemory(), ProcessGDBRemote(), and WriteObjectFile().
m_async_broadcaster
Broadcaster lldb_private::process_gdb_remote::ProcessGDBRemote::m_async_broadcaster protected
Definition at line 283 of file ProcessGDBRemote.h.
Referenced by AsyncThread(), DoAttachToProcessWithID(), DoAttachToProcessWithName(), DoResume(), ProcessGDBRemote(), and StopAsyncThread().
m_async_listener_sp
lldb::ListenerSP lldb_private::process_gdb_remote::ProcessGDBRemote::m_async_listener_sp protected
Definition at line 284 of file ProcessGDBRemote.h.
Referenced by AsyncThread(), and ProcessGDBRemote().
m_async_thread
HostThread lldb_private::process_gdb_remote::ProcessGDBRemote::m_async_thread protected
Definition at line 285 of file ProcessGDBRemote.h.
Referenced by DoResume(), StartAsyncThread(), and StopAsyncThread().
m_async_thread_state_mutex
std::recursive_mutex lldb_private::process_gdb_remote::ProcessGDBRemote::m_async_thread_state_mutex protected
Definition at line 286 of file ProcessGDBRemote.h.
Referenced by ProcessGDBRemote(), StartAsyncThread(), and StopAsyncThread().
m_breakpoint_pc_offset
int64_t lldb_private::process_gdb_remote::ProcessGDBRemote::m_breakpoint_pc_offset protected
Definition at line 314 of file ProcessGDBRemote.h.
Referenced by ParsePythonTargetDefinition(), ProcessGDBRemote(), and SetThreadStopInfo().
m_cached_module_specs
llvm::DenseMap<ModuleCacheKey, ModuleSpec, ModuleCacheInfo> lldb_private::process_gdb_remote::ProcessGDBRemote::m_cached_module_specs private
Definition at line 493 of file ProcessGDBRemote.h.
Referenced by GetModuleSpec(), and PrefetchModuleSpecs().
m_command_sp
lldb::CommandObjectSP lldb_private::process_gdb_remote::ProcessGDBRemote::m_command_sp protected
Definition at line 313 of file ProcessGDBRemote.h.
Referenced by GetPluginCommandObject(), and ProcessGDBRemote().
m_continue_C_tids
tid_sig_collection lldb_private::process_gdb_remote::ProcessGDBRemote::m_continue_C_tids protected
Definition at line 303 of file ProcessGDBRemote.h.
Referenced by DoResume(), ProcessGDBRemote(), WillResume(), and lldb_private::process_gdb_remote::ThreadGDBRemote::WillResume().
m_continue_c_tids
tid_collection lldb_private::process_gdb_remote::ProcessGDBRemote::m_continue_c_tids protected
Definition at line 302 of file ProcessGDBRemote.h.
Referenced by DoResume(), ProcessGDBRemote(), WillResume(), and lldb_private::process_gdb_remote::ThreadGDBRemote::WillResume().
m_continue_S_tids
tid_sig_collection lldb_private::process_gdb_remote::ProcessGDBRemote::m_continue_S_tids protected
Definition at line 305 of file ProcessGDBRemote.h.
Referenced by DoResume(), ProcessGDBRemote(), WillResume(), and lldb_private::process_gdb_remote::ThreadGDBRemote::WillResume().
m_continue_s_tids
tid_collection lldb_private::process_gdb_remote::ProcessGDBRemote::m_continue_s_tids protected
Definition at line 304 of file ProcessGDBRemote.h.
Referenced by DoResume(), ProcessGDBRemote(), WillResume(), and lldb_private::process_gdb_remote::ThreadGDBRemote::WillResume().
m_debugserver_pid
std::atomic<lldb::pid_t> lldb_private::process_gdb_remote::ProcessGDBRemote::m_debugserver_pid protected
Definition at line 277 of file ProcessGDBRemote.h.
Referenced by KillDebugserverProcess(), LaunchAndConnectToDebugserver(), and ProcessGDBRemote().
m_erased_flash_ranges
FlashRangeVector lldb_private::process_gdb_remote::ProcessGDBRemote::m_erased_flash_ranges protected
Definition at line 321 of file ProcessGDBRemote.h.
Referenced by FlashDone(), FlashErase(), HasErased(), and ProcessGDBRemote().
m_gdb_comm
GDBRemoteCommunicationClient lldb_private::process_gdb_remote::ProcessGDBRemote::m_gdb_comm protected
Definition at line 276 of file ProcessGDBRemote.h.
Referenced by BuildDynamicRegisterInfo(), ConfigureStructuredData(), ConnectToDebugserver(), DidExit(), DidFork(), DidForkSwitchHardwareTraps(), DidForkSwitchSoftwareBreakpoints(), DidLaunchOrAttach(), DidVFork(), DidVForkDone(), DisableBreakpointSite(), DisableWatchpoint(), DoAllocateMemory(), DoAttachToProcessWithID(), DoAttachToProcessWithName(), DoConnectRemote(), DoDeallocateMemory(), DoDestroy(), DoDetach(), DoGetMemoryRegionInfo(), DoGetWatchpointReportedAfter(), DoHalt(), DoLaunch(), DoReadMemory(), DoReadMemoryTags(), DoResume(), DoSignal(), DoWriteMemory(), DoWriteMemoryTags(), EnableBreakpointSite(), EnableWatchpoint(), EstablishConnectionIfNeeded(), FlashDone(), FlashErase(), GetAuxvData(), GetDynamicLoaderProcessState(), GetExtendedInfoForThread(), GetFileLoadAddress(), GetGDBRemote(), GetGDBServerRegisterInfo(), GetGDBServerRegisterInfoXMLAndProcess(), GetHostMacCatalystVersion(), GetHostOSVersion(), GetImageInfoAddress(), GetLoadedDynamicLibrariesInfos_sender(), GetLoadedModuleList(), GetMaxMemorySize(), GetModuleSpec(), GetSharedCacheInfo(), lldb_private::process_gdb_remote::ThreadGDBRemote::GetSiginfo(), GetSystemArchitecture(), lldb_private::wasm::ProcessWasm::GetWasmCallStack(), lldb_private::wasm::ProcessWasm::GetWasmVariable(), GetWatchpointSlotCount(), HandleStopReply(), IsAlive(), KillDebugserverProcess(), LaunchAndConnectToDebugserver(), LoadStubBinaries(), MaybeLoadExecutableModule(), ModulesDidLoad(), PrefetchModuleSpecs(), ProcessGDBRemote(), PutSTDIN(), ReadMemoryRanges(), SaveCore(), SendEventData(), SendMultiMemReadPacket(), SetLastStopPacket(), SetThreadStopInfo(), StopAsyncThread(), SupportsMemoryTagging(), SupportsReverseDirection(), TraceGetBinaryData(), TraceGetState(), TraceStart(), TraceStop(), TraceSupported(), UpdateAutomaticSignalFiltering(), UpdateThreadIDList(), UpdateThreadIDsFromStopReplyThreadsValue(), and WillPublicStop().
m_initial_tid
lldb::tid_t lldb_private::process_gdb_remote::ProcessGDBRemote::m_initial_tid protected
Definition at line 315 of file ProcessGDBRemote.h.
Referenced by ProcessGDBRemote(), and RefreshStateAfterStop().
m_jstopinfo_sp
StructuredData::ObjectSP lldb_private::process_gdb_remote::ProcessGDBRemote::m_jstopinfo_sp protected
Definition at line 294 of file ProcessGDBRemote.h.
Referenced by CalculateThreadStopInfo(), ProcessGDBRemote(), SetThreadStopInfo(), and WillResume().
m_jthreadsinfo_sp
StructuredData::ObjectSP lldb_private::process_gdb_remote::ProcessGDBRemote::m_jthreadsinfo_sp protected
Definition at line 296 of file ProcessGDBRemote.h.
Referenced by CalculateThreadStopInfo(), ProcessGDBRemote(), UpdateThreadIDList(), WillPublicStop(), and WillResume().
m_last_signals_version
uint64_t lldb_private::process_gdb_remote::ProcessGDBRemote::m_last_signals_version = 0 private
Definition at line 449 of file ProcessGDBRemote.h.
Referenced by UpdateAutomaticSignalFiltering().
m_last_stop_packet
std::optional<StringExtractorGDBRemote> lldb_private::process_gdb_remote::ProcessGDBRemote::m_last_stop_packet protected
Definition at line 279 of file ProcessGDBRemote.h.
Referenced by RefreshStateAfterStop(), SetLastStopPacket(), and UpdateThreadIDList().
m_last_stop_packet_mutex
std::recursive_mutex lldb_private::process_gdb_remote::ProcessGDBRemote::m_last_stop_packet_mutex protected
Definition at line 280 of file ProcessGDBRemote.h.
m_max_memory_size
uint64_t lldb_private::process_gdb_remote::ProcessGDBRemote::m_max_memory_size protected
Definition at line 306 of file ProcessGDBRemote.h.
Referenced by DoReadMemory(), DoWriteMemory(), GetMaxMemorySize(), ProcessGDBRemote(), ReadMemoryRanges(), and SetUserSpecifiedMaxMemoryTransferSize().
m_partial_profile_data
std::string lldb_private::process_gdb_remote::ProcessGDBRemote::m_partial_profile_data private
Definition at line 447 of file ProcessGDBRemote.h.
Referenced by HandleAsyncMisc().
m_register_info_sp
GDBRemoteDynamicRegisterInfoSP lldb_private::process_gdb_remote::ProcessGDBRemote::m_register_info_sp protected
Definition at line 282 of file ProcessGDBRemote.h.
Referenced by AddRemoteRegisters(), BuildDynamicRegisterInfo(), GetGDBServerRegisterInfo(), lldb_private::wasm::ProcessWasm::GetRegisterInfo(), ParsePythonTargetDefinition(), and ProcessGDBRemote().
m_registers_enum_types
llvm::StringMap<std::unique_ptr<FieldEnum> > lldb_private::process_gdb_remote::ProcessGDBRemote::m_registers_enum_types private
Definition at line 517 of file ProcessGDBRemote.h.
Referenced by GetGDBServerRegisterInfo(), and GetGDBServerRegisterInfoXMLAndProcess().
m_registers_flags_types
llvm::StringMap<std::unique_ptr<RegisterFlags> > lldb_private::process_gdb_remote::ProcessGDBRemote::m_registers_flags_types private
Definition at line 512 of file ProcessGDBRemote.h.
Referenced by GetGDBServerRegisterInfo(), and GetGDBServerRegisterInfoXMLAndProcess().
m_remote_stub_max_memory_size
uint64_t lldb_private::process_gdb_remote::ProcessGDBRemote::m_remote_stub_max_memory_size protected
Definition at line 308 of file ProcessGDBRemote.h.
Referenced by GetMaxMemorySize(), ProcessGDBRemote(), and SetUserSpecifiedMaxMemoryTransferSize().
m_shared_cache_info_mutex
std::mutex lldb_private::process_gdb_remote::ProcessGDBRemote::m_shared_cache_info_mutex protected
Definition at line 301 of file ProcessGDBRemote.h.
Referenced by GetSharedCacheInfo(), and ProcessGDBRemote().
m_shared_cache_info_sp
StructuredData::ObjectSP lldb_private::process_gdb_remote::ProcessGDBRemote::m_shared_cache_info_sp protected
Definition at line 300 of file ProcessGDBRemote.h.
Referenced by GetSharedCacheInfo(), ProcessGDBRemote(), and WillResume().
m_thread_create_bp_sp
lldb::BreakpointSP lldb_private::process_gdb_remote::ProcessGDBRemote::m_thread_create_bp_sp protected
Definition at line 311 of file ProcessGDBRemote.h.
Referenced by ProcessGDBRemote(), RemoveNewThreadBreakpoints(), StartNoticingNewThreads(), and StopNoticingNewThreads().
m_thread_id_to_used_usec_map
std::map<uint64_t, uint32_t> lldb_private::process_gdb_remote::ProcessGDBRemote::m_thread_id_to_used_usec_map private
Definition at line 448 of file ProcessGDBRemote.h.
Referenced by HarmonizeThreadIdsForProfileData().
m_thread_ids
tid_collection lldb_private::process_gdb_remote::ProcessGDBRemote::m_thread_ids protected
Definition at line 291 of file ProcessGDBRemote.h.
Referenced by ClearThreadIDList(), DidFork(), DidVFork(), DoUpdateThreadList(), ProcessGDBRemote(), RefreshStateAfterStop(), SetThreadPc(), SetThreadStopInfo(), SetThreadStopInfo(), UpdateThreadIDList(), and UpdateThreadIDsFromStopReplyThreadsValue().
m_thread_pcs
std::vector<lldb::addr_t> lldb_private::process_gdb_remote::ProcessGDBRemote::m_thread_pcs protected
Definition at line 293 of file ProcessGDBRemote.h.
Referenced by ClearThreadIDList(), ProcessGDBRemote(), RefreshStateAfterStop(), SetThreadPc(), SetThreadStopInfo(), UpdateThreadIDList(), and UpdateThreadPCsFromStopReplyThreadsValue().
m_use_g_packet_for_reading
bool lldb_private::process_gdb_remote::ProcessGDBRemote::m_use_g_packet_for_reading protected
Definition at line 316 of file ProcessGDBRemote.h.
Referenced by lldb_private::process_gdb_remote::ThreadGDBRemote::CreateRegisterContextForFrame(), and ProcessGDBRemote().
m_vfork_in_progress_count
uint32_t lldb_private::process_gdb_remote::ProcessGDBRemote::m_vfork_in_progress_count protected
Definition at line 324 of file ProcessGDBRemote.h.
Referenced by DidExec(), DidVFork(), DidVForkDone(), and ProcessGDBRemote().
m_waiting_for_attach
bool lldb_private::process_gdb_remote::ProcessGDBRemote::m_waiting_for_attach protected
Definition at line 312 of file ProcessGDBRemote.h.
Referenced by ProcessGDBRemote().
The documentation for this class was generated from the following files:
ProcessGDBRemote.h
ProcessGDBRemote.cpp