LLDB: CoreSimulatorSupport::OSVersion Class Reference
CoreSimulatorSupport::OSVersion Class Reference
#include <PlatformiOSSimulatorCoreSimulatorSupport.h>
Public Member Functions
OSVersion (const std::string &ver, const std::string &build)
OSVersion ()
operator bool () const
size_t GetNumVersions () const
unsigned int GetVersionAtIndex (size_t idx) const
const char * GetBuild () const
Private Attributes
std::vector< unsigned int > m_versions
std::string m_build
Detailed Description
Definition at line 101 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
Constructor & Destructor Documentation
OSVersion() [1/2]
CoreSimulatorSupport::OSVersion::OSVersion (const std::string & ver, const std::string & build)
Definition at line 145 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References m_build, and m_versions.
Referenced by OSVersion().
OSVersion() [2/2]
CoreSimulatorSupport::OSVersion::OSVersion ()
Definition at line 166 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References OSVersion().
Member Function Documentation
GetBuild()
const char * CoreSimulatorSupport::OSVersion::GetBuild () const inline
Definition at line 113 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
References m_build.
GetNumVersions()
size_t CoreSimulatorSupport::OSVersion::GetNumVersions () const inline
Definition at line 109 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
References m_versions.
Referenced by CoreSimulatorSupport::operator!=(), CoreSimulatorSupport::operator<(), CoreSimulatorSupport::operator==(), and CoreSimulatorSupport::operator>().
GetVersionAtIndex()
unsigned int CoreSimulatorSupport::OSVersion::GetVersionAtIndex (size_t idx) const inline
Definition at line 111 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
References m_versions.
Referenced by CoreSimulatorSupport::operator!=(), CoreSimulatorSupport::operator<(), CoreSimulatorSupport::operator==(), and CoreSimulatorSupport::operator>().
operator bool()
CoreSimulatorSupport::OSVersion::operator bool () const inline explicit
Definition at line 107 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
References m_versions.
Member Data Documentation
m_build
std::string CoreSimulatorSupport::OSVersion::m_build private
Definition at line 117 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
Referenced by GetBuild(), and OSVersion().
m_versions
std::vector<unsigned int> CoreSimulatorSupport::OSVersion::m_versions private
Definition at line 116 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
Referenced by GetNumVersions(), GetVersionAtIndex(), operator bool(), and OSVersion().
The documentation for this class was generated from the following files:
PlatformiOSSimulatorCoreSimulatorSupport.h
PlatformiOSSimulatorCoreSimulatorSupport.mm