LLDB: lldb_private::ScriptInterpreterIORedirect Class Reference
lldb_private::ScriptInterpreterIORedirect Class Reference
#include <ScriptInterpreter.h>
Public Member Functions
~ScriptInterpreterIORedirect ()
lldb::FileSP GetInputFile () const
lldb::FileSP GetOutputFile () const
lldb::FileSP GetErrorFile () const
void Flush ()
Flush our output and error file handles.
Static Public Member Functions
static llvm::Expected< std::unique_ptr< ScriptInterpreterIORedirect > > Create (bool enable_io, Debugger &debugger, CommandReturnObject *result)
Create an IO redirect.
Private Member Functions
ScriptInterpreterIORedirect (std::unique_ptr< File > input, std::unique_ptr< File > output)
ScriptInterpreterIORedirect (Debugger &debugger, CommandReturnObject *result)
Private Attributes
lldb::FileSP m_input_file_sp
lldb::LockableStreamFileSP m_output_file_sp
lldb::LockableStreamFileSP m_error_file_sp
LockableStreamFile::Mutex m_output_mutex
ThreadedCommunication m_communication
bool m_disconnect
Detailed Description
Definition at line 115 of file ScriptInterpreter.h.
Constructor & Destructor Documentation
~ScriptInterpreterIORedirect()
ScriptInterpreterIORedirect::~ScriptInterpreterIORedirect ()
Definition at line 309 of file ScriptInterpreter.cpp.
References m_communication, m_disconnect, m_error_file_sp, and m_output_file_sp.
ScriptInterpreterIORedirect() [1/2]
ScriptInterpreterIORedirect::ScriptInterpreterIORedirect (std::unique_ptr< File > input, std::unique_ptr< File > output) private
Definition at line 247 of file ScriptInterpreter.cpp.
References m_communication, m_disconnect, m_error_file_sp, m_input_file_sp, m_output_file_sp, and m_output_mutex.
Referenced by Create().
ScriptInterpreterIORedirect() [2/2]
ScriptInterpreterIORedirect::ScriptInterpreterIORedirect (Debugger & debugger, CommandReturnObject * result) private
Definition at line 256 of file ScriptInterpreter.cpp.
References lldb_private::Debugger::AdoptTopIOHandlerFilesIfInvalid(), lldb_private::PipePosix::CreateNew(), lldb_private::Debugger::GetErrorFileSP(), lldb_private::Debugger::GetInputFileSP(), lldb_private::Debugger::GetOutputFileSP(), lldb_private::CommandReturnObject::GetOutputStream(), m_communication, m_disconnect, m_error_file_sp, m_input_file_sp, m_output_file_sp, m_output_mutex, lldb_private::NativeFile::Owned, ReadThreadBytesReceived(), lldb_private::PipePosix::ReleaseReadFileDescriptor(), lldb_private::PipePosix::ReleaseWriteFileDescriptor(), lldb_private::CommandReturnObject::SetImmediateErrorFile(), and lldb_private::CommandReturnObject::SetImmediateOutputFile().
Member Function Documentation
Create()
llvm::Expected< std::unique_ptr< ScriptInterpreterIORedirect > > ScriptInterpreterIORedirect::Create (bool enable_io, Debugger & debugger, CommandReturnObject * result) static
Create an IO redirect.
If IO is enabled, this will redirects the output to the command return object if set or to the debugger otherwise. If IO is disabled, it will redirect all IO to /dev/null.
Definition at line 227 of file ScriptInterpreter.cpp.
References lldb_private::FileSystem::DEV_NULL, lldb_private::File::eOpenOptionReadOnly, lldb_private::File::eOpenOptionWriteOnly, lldb_private::FileSystem::Instance(), lldb_private::FileSystem::Open(), and ScriptInterpreterIORedirect().
Referenced by lldb_private::ScriptInterpreterLua::ExecuteOneLine().
Flush()
void ScriptInterpreterIORedirect::Flush ()
Flush our output and error file handles.
Definition at line 302 of file ScriptInterpreter.cpp.
References m_error_file_sp, and m_output_file_sp.
Referenced by lldb_private::ScriptInterpreterLua::ExecuteOneLine().
GetErrorFile()
lldb::FileSP lldb_private::ScriptInterpreterIORedirect::GetErrorFile () const inline
Definition at line 129 of file ScriptInterpreter.h.
References m_error_file_sp.
Referenced by lldb_private::ScriptInterpreterLua::ExecuteOneLine().
GetInputFile()
lldb::FileSP lldb_private::ScriptInterpreterIORedirect::GetInputFile () const inline
Definition at line 125 of file ScriptInterpreter.h.
References m_input_file_sp.
GetOutputFile()
lldb::FileSP lldb_private::ScriptInterpreterIORedirect::GetOutputFile () const inline
Definition at line 126 of file ScriptInterpreter.h.
References m_output_file_sp.
Referenced by lldb_private::ScriptInterpreterLua::ExecuteOneLine().
Member Data Documentation
m_communication
ThreadedCommunication lldb_private::ScriptInterpreterIORedirect::m_communication private
Definition at line 145 of file ScriptInterpreter.h.
Referenced by ScriptInterpreterIORedirect(), ScriptInterpreterIORedirect(), and ~ScriptInterpreterIORedirect().
m_disconnect
bool lldb_private::ScriptInterpreterIORedirect::m_disconnect private
Definition at line 146 of file ScriptInterpreter.h.
Referenced by ScriptInterpreterIORedirect(), ScriptInterpreterIORedirect(), and ~ScriptInterpreterIORedirect().
m_error_file_sp
lldb::LockableStreamFileSP lldb_private::ScriptInterpreterIORedirect::m_error_file_sp private
Definition at line 143 of file ScriptInterpreter.h.
Referenced by Flush(), GetErrorFile(), ScriptInterpreterIORedirect(), ScriptInterpreterIORedirect(), and ~ScriptInterpreterIORedirect().
m_input_file_sp
lldb::FileSP lldb_private::ScriptInterpreterIORedirect::m_input_file_sp private
Definition at line 141 of file ScriptInterpreter.h.
Referenced by GetInputFile(), ScriptInterpreterIORedirect(), and ScriptInterpreterIORedirect().
m_output_file_sp
lldb::LockableStreamFileSP lldb_private::ScriptInterpreterIORedirect::m_output_file_sp private
Definition at line 142 of file ScriptInterpreter.h.
Referenced by Flush(), GetOutputFile(), ScriptInterpreterIORedirect(), ScriptInterpreterIORedirect(), and ~ScriptInterpreterIORedirect().
m_output_mutex
LockableStreamFile::Mutex lldb_private::ScriptInterpreterIORedirect::m_output_mutex private
Definition at line 144 of file ScriptInterpreter.h.
Referenced by ScriptInterpreterIORedirect(), and ScriptInterpreterIORedirect().
The documentation for this class was generated from the following files:
ScriptInterpreter.h
ScriptInterpreter.cpp