LLDB: SymbolVendorPECOFF Class Reference
SymbolVendorPECOFF Class Reference
#include <SymbolVendorPECOFF.h>
Public Member Functions
SymbolVendorPECOFF (const lldb::ModuleSP &module_sp)
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::SymbolVendor
SymbolVendor (const lldb::ModuleSP &module_sp)
void AddSymbolFileRepresentation (const lldb::ObjectFileSP &objfile_sp)
SymbolFile * GetSymbolFile ()
Public Member Functions inherited from lldb_private::ModuleChild
ModuleChild (const lldb::ModuleSP &module_sp)
Construct with owning module.
~ModuleChild ()
Destructor.
const ModuleChild & operator= (const ModuleChild &rhs)
Assignment operator.
lldb::ModuleSP GetModule () const
Get const accessor for the module pointer.
void SetModule (const lldb::ModuleSP &module_sp)
Set accessor for the module pointer.
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static lldb_private::SymbolVendor * CreateInstance (const lldb::ModuleSP &module_sp, lldb_private::Stream *feedback_strm)
Static Public Member Functions inherited from lldb_private::SymbolVendor
static SymbolVendor * FindPlugin (const lldb::ModuleSP &module_sp, Stream *feedback_strm)
Additional Inherited Members
Protected Attributes inherited from lldb_private::SymbolVendor
std::unique_ptr< SymbolFile > m_sym_file_up
Protected Attributes inherited from lldb_private::ModuleChild
lldb::ModuleWP m_module_wp
The Module that owns the object that inherits from this class.
Detailed Description
Definition at line 15 of file SymbolVendorPECOFF.h.
Constructor & Destructor Documentation
SymbolVendorPECOFF()
SymbolVendorPECOFF::SymbolVendorPECOFF (const lldb::ModuleSP & module_sp)
Definition at line 30 of file SymbolVendorPECOFF.cpp.
References lldb_private::SymbolVendor::SymbolVendor(), and SymbolVendorPECOFF().
Referenced by CreateInstance(), and SymbolVendorPECOFF().
Member Function Documentation
CreateInstance()
SymbolVendor * SymbolVendorPECOFF::CreateInstance (const lldb::ModuleSP & module_sp, lldb_private::Stream * feedback_strm) static
Definition at line 53 of file SymbolVendorPECOFF.cpp.
References lldb_private::SectionList::AddSection(), lldb_private::SymbolVendor::AddSymbolFileRepresentation(), lldb::eSectionTypeDWARFDebugAbbrev, lldb::eSectionTypeDWARFDebugAranges, lldb::eSectionTypeDWARFDebugFrame, lldb::eSectionTypeDWARFDebugInfo, lldb::eSectionTypeDWARFDebugLine, lldb::eSectionTypeDWARFDebugLoc, lldb::eSectionTypeDWARFDebugLocLists, lldb::eSectionTypeDWARFDebugMacInfo, lldb::eSectionTypeDWARFDebugNames, lldb::eSectionTypeDWARFDebugPubNames, lldb::eSectionTypeDWARFDebugPubTypes, lldb::eSectionTypeDWARFDebugRanges, lldb::eSectionTypeDWARFDebugStr, lldb::eSectionTypeDWARFDebugTypes, lldb_private::ObjectFile::eTypeDebugInfo, lldb_private::ObjectFile::FindPlugin(), lldb_private::SectionList::FindSectionByType(), ObjectFilePECOFF::GetDebugLink(), lldb_private::Target::GetDefaultDebugFileSearchPaths(), lldb_private::ModuleSpec::GetFileSpec(), lldb_private::ObjectFile::GetFileSpec(), lldb_private::ObjectFile::GetSectionList(), lldb_private::ModuleSpec::GetSymbolFileSpec(), lldb_private::ModuleSpec::GetUUID(), ObjectFilePECOFF::GetUUID(), lldb_private::FileSystem::Instance(), LLDB_SCOPED_TIMERF, lldb_private::PluginManager::LocateExecutableSymbolFile(), lldb_private::SectionList::ReplaceSection(), lldb_private::FileSystem::Resolve(), and SymbolVendorPECOFF().
Referenced by Initialize(), and Terminate().
GetPluginDescriptionStatic()
llvm::StringRef SymbolVendorPECOFF::GetPluginDescriptionStatic () static
Definition at line 42 of file SymbolVendorPECOFF.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef SymbolVendorPECOFF::GetPluginName () inline override virtual
Reimplemented from lldb_private::SymbolVendor.
Definition at line 34 of file SymbolVendorPECOFF.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef SymbolVendorPECOFF::GetPluginNameStatic () inline static
Definition at line 25 of file SymbolVendorPECOFF.h.
Referenced by GetPluginName(), and Initialize().
Initialize()
void SymbolVendorPECOFF::Initialize () static
Definition at line 33 of file SymbolVendorPECOFF.cpp.
References CreateInstance(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Terminate()
void SymbolVendorPECOFF::Terminate () static
Definition at line 38 of file SymbolVendorPECOFF.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
The documentation for this class was generated from the following files:
SymbolVendorPECOFF.h
SymbolVendorPECOFF.cpp