LLDB: lldb_private::ValueObjectConstResultImpl Class Reference
lldb_private::ValueObjectConstResultImpl Class Reference
A class wrapping common implementation details for operations in ValueObjectConstResult (& Child) that may need to jump from the host memory space into the target's memory space.
#include <ValueObjectConstResultImpl.h>
Public Member Functions
ValueObjectConstResultImpl (ValueObject *valobj, lldb::addr_t live_address=LLDB_INVALID_ADDRESS)
virtual ~ValueObjectConstResultImpl ()=default
lldb::ValueObjectSP Dereference (Status &error)
ValueObject * CreateChildAtIndex (size_t idx)
ValueObject * CreateSyntheticArrayMember (size_t idx)
lldb::ValueObjectSP GetSyntheticChildAtOffset (uint32_t offset, const CompilerType &type, bool can_create, ConstString name_const_str=ConstString())
lldb::ValueObjectSP AddressOf (Status &error)
lldb::addr_t GetLiveAddress ()
lldb::ValueObjectSP Cast (const CompilerType &compiler_type)
void SetLiveAddress (lldb::addr_t addr=LLDB_INVALID_ADDRESS, AddressType address_type=eAddressTypeLoad)
virtual ValueObject::AddrAndType GetAddressOf (bool scalar_is_load_address=true)
virtual size_t GetPointeeData (DataExtractor &data, uint32_t item_idx=0, uint32_t item_count=1)
Private Member Functions
ValueObjectConstResultImpl (const ValueObjectConstResultImpl &)=delete
const ValueObjectConstResultImpl & operator= (const ValueObjectConstResultImpl &)=delete
Private Attributes
ValueObject * m_impl_backend
lldb::addr_t m_live_address
The memory address in the inferior process that this ValueObject tracks.
AddressType m_live_address_type
lldb::ValueObjectSP m_address_of_backend
Detailed Description
A class wrapping common implementation details for operations in ValueObjectConstResult (& Child) that may need to jump from the host memory space into the target's memory space.
Definition at line 32 of file ValueObjectConstResultImpl.h.
Constructor & Destructor Documentation
ValueObjectConstResultImpl() [1/2]
ValueObjectConstResultImpl::ValueObjectConstResultImpl (ValueObject * valobj, lldb::addr_t live_address = LLDB_INVALID_ADDRESS)
Definition at line 36 of file ValueObjectConstResultImpl.cpp.
References lldb_private::eAddressTypeLoad, m_address_of_backend, m_impl_backend, m_live_address, and m_live_address_type.
Referenced by operator=(), and ValueObjectConstResultImpl().
~ValueObjectConstResultImpl()
virtual lldb_private::ValueObjectConstResultImpl::~ValueObjectConstResultImpl () virtual default
References error().
ValueObjectConstResultImpl() [2/2]
lldb_private::ValueObjectConstResultImpl::ValueObjectConstResultImpl (const ValueObjectConstResultImpl &) private delete
References ValueObjectConstResultImpl().
Member Function Documentation
AddressOf()
lldb::ValueObjectSP ValueObjectConstResultImpl::AddressOf (Status & error)
Definition at line 170 of file ValueObjectConstResultImpl.cpp.
References lldb_private::ValueObjectConstResult::Create(), error(), lldb_private::ExecutionContext::GetAddressByteSize(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::CompilerType::GetPointerType(), lldb_private::endian::InlHostByteOrder(), LLDB_INVALID_ADDRESS, m_address_of_backend, m_impl_backend, m_live_address, and lldb_private::Value::Scalar.
Cast()
lldb::ValueObjectSP ValueObjectConstResultImpl::Cast (const CompilerType & compiler_type)
Definition at line 199 of file ValueObjectConstResultImpl.cpp.
References lldb_private::ValueObject::GetSP(), m_impl_backend, and m_live_address.
CreateChildAtIndex()
ValueObject * ValueObjectConstResultImpl::CreateChildAtIndex (size_t idx)
Definition at line 48 of file ValueObjectConstResultImpl.cpp.
References lldb_private::CompilerType::GetChildCompilerTypeAtIndex(), lldb_private::GetLog(), lldb_private::CompilerType::IsPointerType(), LLDB_INVALID_ADDRESS, LLDB_LOG_ERROR, m_impl_backend, m_live_address, and lldb_private::Types.
CreateSyntheticArrayMember()
ValueObject * ValueObjectConstResultImpl::CreateSyntheticArrayMember (size_t idx)
Definition at line 104 of file ValueObjectConstResultImpl.cpp.
References lldb_private::CompilerType::GetChildCompilerTypeAtIndex(), lldb_private::GetLog(), lldb_private::CompilerType::IsPointerType(), LLDB_INVALID_ADDRESS, LLDB_LOG_ERROR, m_impl_backend, m_live_address, and lldb_private::Types.
Dereference()
lldb::ValueObjectSP ValueObjectConstResultImpl::Dereference (Status & error)
Definition at line 41 of file ValueObjectConstResultImpl.cpp.
References error(), and m_impl_backend.
GetAddressOf()
ValueObject::AddrAndType ValueObjectConstResultImpl::GetAddressOf (bool scalar_is_load_address = true) virtual
Definition at line 210 of file ValueObjectConstResultImpl.cpp.
References lldb_private::eAddressTypeInvalid, LLDB_INVALID_ADDRESS, m_impl_backend, m_live_address, and m_live_address_type.
GetLiveAddress()
lldb::addr_t lldb_private::ValueObjectConstResultImpl::GetLiveAddress () inline
Definition at line 51 of file ValueObjectConstResultImpl.h.
References m_live_address.
GetPointeeData()
size_t ValueObjectConstResultImpl::GetPointeeData (DataExtractor & data, uint32_t item_idx = 0, uint32_t item_count = 1) virtual
Definition at line 221 of file ValueObjectConstResultImpl.cpp.
References m_impl_backend.
GetSyntheticChildAtOffset()
lldb::ValueObjectSP ValueObjectConstResultImpl::GetSyntheticChildAtOffset (uint32_t offset, const CompilerType & type, bool can_create, ConstString name_const_str = ConstString())
Definition at line 160 of file ValueObjectConstResultImpl.cpp.
References m_impl_backend.
operator=()
const ValueObjectConstResultImpl & lldb_private::ValueObjectConstResultImpl::operator= (const ValueObjectConstResultImpl &) private delete
References ValueObjectConstResultImpl().
SetLiveAddress()
void lldb_private::ValueObjectConstResultImpl::SetLiveAddress (lldb::addr_t addr = LLDB_INVALID_ADDRESS, AddressType address_type = eAddressTypeLoad) inline
Definition at line 55 of file ValueObjectConstResultImpl.h.
References lldb_private::eAddressTypeLoad, LLDB_INVALID_ADDRESS, m_live_address, and m_live_address_type.
Member Data Documentation
m_address_of_backend
lldb::ValueObjectSP lldb_private::ValueObjectConstResultImpl::m_address_of_backend private
Definition at line 75 of file ValueObjectConstResultImpl.h.
Referenced by AddressOf(), and ValueObjectConstResultImpl().
m_impl_backend
ValueObject* lldb_private::ValueObjectConstResultImpl::m_impl_backend private
Definition at line 68 of file ValueObjectConstResultImpl.h.
Referenced by AddressOf(), Cast(), CreateChildAtIndex(), CreateSyntheticArrayMember(), Dereference(), GetAddressOf(), GetPointeeData(), GetSyntheticChildAtOffset(), and ValueObjectConstResultImpl().
m_live_address
lldb::addr_t lldb_private::ValueObjectConstResultImpl::m_live_address private
The memory address in the inferior process that this ValueObject tracks.
This address is used to request additional memory when the actual data size exceeds the initial local buffer size, such as when a dynamic type resolution results in a type larger than its statically determined type.
Definition at line 73 of file ValueObjectConstResultImpl.h.
Referenced by AddressOf(), Cast(), CreateChildAtIndex(), CreateSyntheticArrayMember(), GetAddressOf(), GetLiveAddress(), SetLiveAddress(), and ValueObjectConstResultImpl().
m_live_address_type
AddressType lldb_private::ValueObjectConstResultImpl::m_live_address_type private
Definition at line 74 of file ValueObjectConstResultImpl.h.
Referenced by GetAddressOf(), SetLiveAddress(), and ValueObjectConstResultImpl().
The documentation for this class was generated from the following files:
ValueObjectConstResultImpl.h
ValueObjectConstResultImpl.cpp