LLDB: lldb_private::TypeCategoryMap Class Reference
lldb_private::TypeCategoryMap Class Reference
#include <TypeCategoryMap.h>
Classes
class delete_matching_categories
Public Types
typedef ConstString KeyType
typedef std::map< KeyType, lldb::TypeCategoryImplSP > MapType
typedef MapType::iterator MapIterator
typedef std::function< bool(const lldb::TypeCategoryImplSP &)> ForEachCallback
typedef uint32_t Position
Public Member Functions
TypeCategoryMap (IFormatChangeListener *lst)
void Add (KeyType name, const lldb::TypeCategoryImplSP &entry)
bool Delete (KeyType name)
bool Enable (KeyType category_name, Position pos=Default)
bool Disable (KeyType category_name)
bool Enable (lldb::TypeCategoryImplSP category, Position pos=Default)
bool Disable (lldb::TypeCategoryImplSP category)
void EnableAllCategories ()
void DisableAllCategories ()
void Clear ()
bool Get (KeyType name, lldb::TypeCategoryImplSP &entry)
void ForEach (ForEachCallback callback)
lldb::TypeCategoryImplSP GetAtIndex (uint32_t)
bool AnyMatches (const FormattersMatchCandidate &candidate_type, TypeCategoryImpl::FormatCategoryItems items=TypeCategoryImpl::ALL_ITEM_TYPES, bool only_enabled=true, const char **matching_category=nullptr, TypeCategoryImpl::FormatCategoryItems *matching_type=nullptr)
uint32_t GetCount ()
template<typename ImplSP>
void Get (FormattersMatchData &, ImplSP &)
Static Public Attributes
static const Position First = 0
static const Position Default = 1
static const Position Last = UINT32_MAX
Private Types
typedef std::list< lldb::TypeCategoryImplSP > ActiveCategoriesList
typedef ActiveCategoriesList::iterator ActiveCategoriesIterator
Private Attributes
std::recursive_mutex m_map_mutex
IFormatChangeListener * listener
MapType m_map
ActiveCategoriesList m_active_categories
Detailed Description
Definition at line 25 of file TypeCategoryMap.h.
Member Typedef Documentation
ActiveCategoriesIterator
typedef ActiveCategoriesList::iterator lldb_private::TypeCategoryMap::ActiveCategoriesIterator private
Definition at line 28 of file TypeCategoryMap.h.
ActiveCategoriesList
typedef std::list<lldb::TypeCategoryImplSP> lldb_private::TypeCategoryMap::ActiveCategoriesList private
Definition at line 27 of file TypeCategoryMap.h.
ForEachCallback
typedef std::function<bool(const lldb::TypeCategoryImplSP &)> lldb_private::TypeCategoryMap::ForEachCallback
Definition at line 34 of file TypeCategoryMap.h.
KeyType
typedef ConstString lldb_private::TypeCategoryMap::KeyType
Definition at line 31 of file TypeCategoryMap.h.
MapIterator
typedef MapType::iterator lldb_private::TypeCategoryMap::MapIterator
Definition at line 33 of file TypeCategoryMap.h.
MapType
typedef std::map<KeyType, lldb::TypeCategoryImplSP> lldb_private::TypeCategoryMap::MapType
Definition at line 32 of file TypeCategoryMap.h.
Position
typedef uint32_t lldb_private::TypeCategoryMap::Position
Definition at line 36 of file TypeCategoryMap.h.
Constructor & Destructor Documentation
TypeCategoryMap()
TypeCategoryMap::TypeCategoryMap (IFormatChangeListener * lst)
Definition at line 18 of file TypeCategoryMap.cpp.
References Add(), Enable(), First, listener, m_active_categories, m_map, and m_map_mutex.
Member Function Documentation
Add()
void TypeCategoryMap::Add (KeyType name, const lldb::TypeCategoryImplSP & entry)
Definition at line 27 of file TypeCategoryMap.cpp.
References listener, m_map, and m_map_mutex.
Referenced by TypeCategoryMap().
AnyMatches()
bool TypeCategoryMap::AnyMatches (const FormattersMatchCandidate & candidate_type, TypeCategoryImpl::FormatCategoryItems items = TypeCategoryImpl::ALL_ITEM_TYPES, bool only_enabled = true, const char ** matching_category = nullptr, TypeCategoryImpl::FormatCategoryItems * matching_type = nullptr)
Definition at line 161 of file TypeCategoryMap.cpp.
References m_map, and m_map_mutex.
Clear()
void TypeCategoryMap::Clear ()
Definition at line 138 of file TypeCategoryMap.cpp.
References listener, m_active_categories, m_map, and m_map_mutex.
Delete()
bool TypeCategoryMap::Delete (KeyType name)
Definition at line 40 of file TypeCategoryMap.cpp.
References Disable(), listener, m_map, and m_map_mutex.
Disable() [1/2]
bool TypeCategoryMap::Disable (KeyType category_name)
Definition at line 66 of file TypeCategoryMap.cpp.
References Disable(), Get(), and m_map_mutex.
Referenced by Delete(), Disable(), and DisableAllCategories().
Disable() [2/2]
bool TypeCategoryMap::Disable (lldb::TypeCategoryImplSP category)
Definition at line 96 of file TypeCategoryMap.cpp.
References m_active_categories, and m_map_mutex.
DisableAllCategories()
void TypeCategoryMap::DisableAllCategories ()
Definition at line 130 of file TypeCategoryMap.cpp.
References Disable(), First, m_active_categories, and m_map_mutex.
Enable() [1/2]
bool TypeCategoryMap::Enable (KeyType category_name, Position pos = Default)
Definition at line 58 of file TypeCategoryMap.cpp.
References Enable(), Get(), and m_map_mutex.
Referenced by Enable(), EnableAllCategories(), and TypeCategoryMap().
Enable() [2/2]
bool TypeCategoryMap::Enable (lldb::TypeCategoryImplSP category, Position pos = Default)
Definition at line 74 of file TypeCategoryMap.cpp.
References First, Last, m_active_categories, and m_map_mutex.
EnableAllCategories()
void TypeCategoryMap::EnableAllCategories ()
Definition at line 106 of file TypeCategoryMap.cpp.
References Enable(), Last, m_map, m_map_mutex, and sp.
ForEach()
void TypeCategoryMap::ForEach (ForEachCallback callback)
Definition at line 225 of file TypeCategoryMap.cpp.
References m_active_categories, m_map, and m_map_mutex.
Get() [1/2]
template<typename ImplSP> void TypeCategoryMap::Get (FormattersMatchData & match_data, ImplSP & retval)
Definition at line 178 of file TypeCategoryMap.cpp.
References lldb_private::DataFormatters, lldb_private::GetLog(), lldb_private::FormattersMatchData::GetMatchesVector(), lldb_private::ValueObject::GetObjectRuntimeLanguage(), lldb_private::FormattersMatchData::GetValueObject(), LLDB_LOGF, m_active_categories, and m_map_mutex.
Get() [2/2]
bool TypeCategoryMap::Get (KeyType name, lldb::TypeCategoryImplSP & entry)
Definition at line 152 of file TypeCategoryMap.cpp.
References m_map, and m_map_mutex.
Referenced by Disable(), Enable(), TypeCategoryMap::Get< lldb::SyntheticChildrenSP >(), TypeCategoryMap::Get< lldb::TypeFormatImplSP >(), and TypeCategoryMap::Get< lldb::TypeSummaryImplSP >().
GetAtIndex()
TypeCategoryImplSP TypeCategoryMap::GetAtIndex (uint32_t index)
Definition at line 252 of file TypeCategoryMap.cpp.
References m_map, and m_map_mutex.
GetCount()
uint32_t lldb_private::TypeCategoryMap::GetCount () inline
Definition at line 75 of file TypeCategoryMap.h.
References m_map.
Member Data Documentation
Default
const Position lldb_private::TypeCategoryMap::Default = 1 static
Definition at line 39 of file TypeCategoryMap.h.
Referenced by lldb_private::LanguageCategory::Enable(), lldb_private::FormatManager::EnableCategory(), lldb_private::FormatManager::EnableCategory(), and CommandObjectTypeCategoryEnable::~CommandObjectTypeCategoryEnable().
First
const Position lldb_private::TypeCategoryMap::First = 0 static
Definition at line 38 of file TypeCategoryMap.h.
Referenced by DisableAllCategories(), Enable(), and TypeCategoryMap().
Last
const Position lldb_private::TypeCategoryMap::Last = UINT32_MAX static
Definition at line 40 of file TypeCategoryMap.h.
Referenced by Enable(), EnableAllCategories(), and lldb_private::FormatManager::FormatManager().
listener
IFormatChangeListener* lldb_private::TypeCategoryMap::listener private
Definition at line 93 of file TypeCategoryMap.h.
Referenced by Add(), Clear(), Delete(), and TypeCategoryMap().
m_active_categories
ActiveCategoriesList lldb_private::TypeCategoryMap::m_active_categories private
Definition at line 96 of file TypeCategoryMap.h.
Referenced by Clear(), Disable(), DisableAllCategories(), Enable(), ForEach(), Get(), and TypeCategoryMap().
m_map
MapType lldb_private::TypeCategoryMap::m_map private
Definition at line 95 of file TypeCategoryMap.h.
Referenced by Add(), AnyMatches(), Clear(), Delete(), EnableAllCategories(), ForEach(), Get(), GetAtIndex(), GetCount(), and TypeCategoryMap().
m_map_mutex
std::recursive_mutex lldb_private::TypeCategoryMap::m_map_mutex private
Definition at line 92 of file TypeCategoryMap.h.
Referenced by Add(), AnyMatches(), Clear(), Delete(), Disable(), Disable(), DisableAllCategories(), Enable(), Enable(), EnableAllCategories(), ForEach(), Get(), Get(), GetAtIndex(), and TypeCategoryMap().
The documentation for this class was generated from the following files:
TypeCategoryMap.h
TypeCategoryMap.cpp