LLDB: lldb_private::StatsDuration Class Reference
lldb_private::StatsDuration Class Reference
#include <Statistics.h>
Public Types
using Duration = std::chrono::duration<double>
Public Member Functions
Duration get () const
operator Duration () const
void reset ()
StatsDuration & operator+= (Duration dur)
Private Types
using InternalDuration = std::chrono::duration<uint64_t, std::micro>
Private Attributes
std::atomic< uint64_t > value {0}
Detailed Description
Definition at line 35 of file Statistics.h.
Member Typedef Documentation
Duration
using lldb_private::StatsDuration::Duration = std::chrono::duration<double>
Definition at line 37 of file Statistics.h.
InternalDuration
using lldb_private::StatsDuration::InternalDuration = std::chrono::duration<uint64_t, std::micro> private
Definition at line 53 of file Statistics.h.
Member Function Documentation
get()
Duration lldb_private::StatsDuration::get () const inline
Definition at line 39 of file Statistics.h.
References value.
Referenced by lldb_private::CommandInterpreter::HandleCommand(), lldb_private::PluginManager::LocateExecutableObjectFile(), lldb_private::PluginManager::LocateExecutableSymbolFile(), and operator Duration().
operator Duration()
lldb_private::StatsDuration::operator Duration () const inline
Definition at line 42 of file Statistics.h.
References get().
operator+=()
StatsDuration & lldb_private::StatsDuration::operator+= (Duration dur) inline
Definition at line 46 of file Statistics.h.
References value.
reset()
void lldb_private::StatsDuration::reset () inline
Definition at line 44 of file Statistics.h.
References value.
Member Data Documentation
value
std::atomic<uint64_t> lldb_private::StatsDuration::value {0} private
Definition at line 54 of file Statistics.h.
Referenced by get(), operator+=(), and reset().
The documentation for this class was generated from the following file:
Statistics.h