LLDB: lldb_private::CommandInterpreterRunOptions Class Reference
lldb_private::CommandInterpreterRunOptions Class Reference
#include <CommandInterpreter.h>
Public Member Functions
CommandInterpreterRunOptions (LazyBool stop_on_continue, LazyBool stop_on_error, LazyBool stop_on_crash, LazyBool echo_commands, LazyBool echo_comments, LazyBool print_results, LazyBool print_errors, LazyBool add_to_history, LazyBool handle_repeats)
Construct a CommandInterpreterRunOptions object.
CommandInterpreterRunOptions ()=default
void SetSilent (bool silent)
bool GetStopOnContinue () const
void SetStopOnContinue (bool stop_on_continue)
bool GetStopOnError () const
void SetStopOnError (bool stop_on_error)
bool GetStopOnCrash () const
void SetStopOnCrash (bool stop_on_crash)
bool GetEchoCommands () const
void SetEchoCommands (bool echo_commands)
bool GetEchoCommentCommands () const
void SetEchoCommentCommands (bool echo_comments)
bool GetPrintResults () const
void SetPrintResults (bool print_results)
bool GetPrintErrors () const
void SetPrintErrors (bool print_errors)
bool GetAddToHistory () const
void SetAddToHistory (bool add_to_history)
bool GetAutoHandleEvents () const
void SetAutoHandleEvents (bool auto_handle_events)
bool GetSpawnThread () const
void SetSpawnThread (bool spawn_thread)
bool GetAllowRepeats () const
void SetAllowRepeats (bool allow_repeats)
Public Attributes
LazyBool m_stop_on_continue = eLazyBoolCalculate
LazyBool m_stop_on_error = eLazyBoolCalculate
LazyBool m_stop_on_crash = eLazyBoolCalculate
LazyBool m_echo_commands = eLazyBoolCalculate
LazyBool m_echo_comment_commands = eLazyBoolCalculate
LazyBool m_print_results = eLazyBoolCalculate
LazyBool m_print_errors = eLazyBoolCalculate
LazyBool m_add_to_history = eLazyBoolCalculate
LazyBool m_auto_handle_events
LazyBool m_spawn_thread
LazyBool m_allow_repeats = eLazyBoolCalculate
Static Private Member Functions
static bool DefaultToYes (LazyBool flag)
static bool DefaultToNo (LazyBool flag)
Detailed Description
Definition at line 63 of file CommandInterpreter.h.
Constructor & Destructor Documentation
CommandInterpreterRunOptions() [1/2]
lldb_private::CommandInterpreterRunOptions::CommandInterpreterRunOptions (LazyBool stop_on_continue, LazyBool stop_on_error, LazyBool stop_on_crash, LazyBool echo_commands, LazyBool echo_comments, LazyBool print_results, LazyBool print_errors, LazyBool add_to_history, LazyBool handle_repeats) inline
Construct a CommandInterpreterRunOptions object.
This class is used to control all the instances where we run multiple commands, e.g. HandleCommands, HandleCommandsFromFile, RunCommandInterpreter.
The meanings of the options in this object are:
Parameters
[in] stop_on_continue If true, execution will end on the first command that causes the process in the execution context to continue. If false, we won't check the execution status.
[in] stop_on_error If true, execution will end on the first command that causes an error.
[in] stop_on_crash If true, when a command causes the target to run, and the end of the run is a signal or exception, stop executing the commands.
[in] echo_commands If true, echo the command before executing it. If false, execute silently.
[in] echo_comments If true, echo command even if it is a pure comment line. If false, print no ouput in this case. This setting has an effect only if echo_commands is true.
[in] print_results If true and the command succeeds, print the results of the command after executing it. If false, execute silently.
[in] print_errors If true and the command fails, print the results of the command after executing it. If false, execute silently.
[in] add_to_history If true add the commands to the command history. If false, don't add them.
[in] handle_repeats If true then treat empty lines as repeat commands even if the interpreter is non-interactive.
Definition at line 100 of file CommandInterpreter.h.
References m_add_to_history, m_allow_repeats, m_echo_commands, m_echo_comment_commands, m_print_errors, m_print_results, m_stop_on_continue, m_stop_on_crash, and m_stop_on_error.
CommandInterpreterRunOptions() [2/2]
lldb_private::CommandInterpreterRunOptions::CommandInterpreterRunOptions () default
Member Function Documentation
DefaultToNo()
bool lldb_private::CommandInterpreterRunOptions::DefaultToNo (LazyBool flag) inline static private
Definition at line 219 of file CommandInterpreter.h.
References lldb_private::eLazyBoolYes.
Referenced by GetAllowRepeats(), GetSpawnThread(), GetStopOnContinue(), GetStopOnCrash(), and GetStopOnError().
DefaultToYes()
bool lldb_private::CommandInterpreterRunOptions::DefaultToYes (LazyBool flag) inline static private
Definition at line 210 of file CommandInterpreter.h.
References lldb_private::eLazyBoolNo.
Referenced by GetAddToHistory(), GetAutoHandleEvents(), GetEchoCommands(), GetEchoCommentCommands(), GetPrintErrors(), and GetPrintResults().
GetAddToHistory()
bool lldb_private::CommandInterpreterRunOptions::GetAddToHistory () const inline
Definition at line 171 of file CommandInterpreter.h.
References DefaultToYes(), and m_add_to_history.
Referenced by lldb_private::CommandInterpreter::HandleCommands().
GetAllowRepeats()
bool lldb_private::CommandInterpreterRunOptions::GetAllowRepeats () const inline
Definition at line 191 of file CommandInterpreter.h.
References DefaultToNo(), and m_allow_repeats.
GetAutoHandleEvents()
bool lldb_private::CommandInterpreterRunOptions::GetAutoHandleEvents () const inline
Definition at line 177 of file CommandInterpreter.h.
References DefaultToYes(), and m_auto_handle_events.
Referenced by lldb_private::CommandInterpreter::RunCommandInterpreter().
GetEchoCommands()
bool lldb_private::CommandInterpreterRunOptions::GetEchoCommands () const inline
Definition at line 145 of file CommandInterpreter.h.
References DefaultToYes(), and m_echo_commands.
Referenced by lldb_private::CommandInterpreter::HandleCommands().
GetEchoCommentCommands()
bool lldb_private::CommandInterpreterRunOptions::GetEchoCommentCommands () const inline
Definition at line 151 of file CommandInterpreter.h.
References DefaultToYes(), and m_echo_comment_commands.
GetPrintErrors()
bool lldb_private::CommandInterpreterRunOptions::GetPrintErrors () const inline
Definition at line 165 of file CommandInterpreter.h.
References DefaultToYes(), and m_print_errors.
GetPrintResults()
bool lldb_private::CommandInterpreterRunOptions::GetPrintResults () const inline
Definition at line 159 of file CommandInterpreter.h.
References DefaultToYes(), and m_print_results.
Referenced by lldb_private::CommandInterpreter::HandleCommands().
GetSpawnThread()
bool lldb_private::CommandInterpreterRunOptions::GetSpawnThread () const inline
Definition at line 185 of file CommandInterpreter.h.
References DefaultToNo(), and m_spawn_thread.
Referenced by lldb_private::CommandInterpreter::RunCommandInterpreter().
GetStopOnContinue()
bool lldb_private::CommandInterpreterRunOptions::GetStopOnContinue () const inline
Definition at line 127 of file CommandInterpreter.h.
References DefaultToNo(), and m_stop_on_continue.
Referenced by lldb_private::CommandInterpreter::HandleCommands().
GetStopOnCrash()
bool lldb_private::CommandInterpreterRunOptions::GetStopOnCrash () const inline
Definition at line 139 of file CommandInterpreter.h.
References DefaultToNo(), and m_stop_on_crash.
Referenced by lldb_private::CommandInterpreter::HandleCommands(), and lldb_private::CommandInterpreter::HandleCommandsFromFile().
GetStopOnError()
bool lldb_private::CommandInterpreterRunOptions::GetStopOnError () const inline
Definition at line 133 of file CommandInterpreter.h.
References DefaultToNo(), and m_stop_on_error.
Referenced by lldb_private::CommandInterpreter::HandleCommands().
SetAddToHistory()
void lldb_private::CommandInterpreterRunOptions::SetAddToHistory (bool add_to_history) inline
Definition at line 173 of file CommandInterpreter.h.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, and m_add_to_history.
Referenced by lldb_private::BreakpointOptions::BreakpointOptionsCallbackFunction(), CommandObjectSettingsRead::DoExecute(), and lldb_private::Target::StopHookCommandLine::HandleStop().
SetAllowRepeats()
void lldb_private::CommandInterpreterRunOptions::SetAllowRepeats (bool allow_repeats) inline
Definition at line 193 of file CommandInterpreter.h.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, and m_allow_repeats.
SetAutoHandleEvents()
void lldb_private::CommandInterpreterRunOptions::SetAutoHandleEvents (bool auto_handle_events) inline
Definition at line 181 of file CommandInterpreter.h.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, and m_auto_handle_events.
Referenced by lldb::SBDebugger::RunCommandInterpreter().
SetEchoCommands()
void lldb_private::CommandInterpreterRunOptions::SetEchoCommands (bool echo_commands) inline
Definition at line 147 of file CommandInterpreter.h.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, and m_echo_commands.
Referenced by lldb_private::BreakpointOptions::BreakpointOptionsCallbackFunction(), CommandObjectCommandsSource::DoExecute(), CommandObjectSettingsRead::DoExecute(), and lldb_private::Target::StopHookCommandLine::HandleStop().
SetEchoCommentCommands()
void lldb_private::CommandInterpreterRunOptions::SetEchoCommentCommands (bool echo_comments) inline
Definition at line 155 of file CommandInterpreter.h.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, and m_echo_comment_commands.
Referenced by CommandObjectCommandsSource::DoExecute().
SetPrintErrors()
void lldb_private::CommandInterpreterRunOptions::SetPrintErrors (bool print_errors) inline
Definition at line 167 of file CommandInterpreter.h.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, and m_print_errors.
Referenced by lldb_private::BreakpointOptions::BreakpointOptionsCallbackFunction(), CommandObjectCommandsSource::DoExecute(), CommandObjectSettingsRead::DoExecute(), lldb_private::Target::StopHookCommandLine::HandleStop(), and lldb_private::CommandInterpreter::SourceInitFile().
SetPrintResults()
void lldb_private::CommandInterpreterRunOptions::SetPrintResults (bool print_results) inline
Definition at line 161 of file CommandInterpreter.h.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, and m_print_results.
Referenced by lldb_private::BreakpointOptions::BreakpointOptionsCallbackFunction(), CommandObjectCommandsSource::DoExecute(), CommandObjectSettingsRead::DoExecute(), and lldb_private::Target::StopHookCommandLine::HandleStop().
SetSilent()
void lldb_private::CommandInterpreterRunOptions::SetSilent (bool silent) inline
Definition at line 113 of file CommandInterpreter.h.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, m_add_to_history, m_echo_commands, m_echo_comment_commands, m_print_errors, and m_print_results.
Referenced by CommandObjectCommandsSource::DoExecute(), and lldb_private::CommandInterpreter::SourceInitFile().
SetSpawnThread()
void lldb_private::CommandInterpreterRunOptions::SetSpawnThread (bool spawn_thread) inline
Definition at line 187 of file CommandInterpreter.h.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, and m_spawn_thread.
Referenced by lldb::SBDebugger::RunCommandInterpreter().
SetStopOnContinue()
void lldb_private::CommandInterpreterRunOptions::SetStopOnContinue (bool stop_on_continue) inline
Definition at line 129 of file CommandInterpreter.h.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, and m_stop_on_continue.
Referenced by lldb_private::BreakpointOptions::BreakpointOptionsCallbackFunction(), CommandObjectCommandsSource::DoExecute(), lldb_private::Target::StopHookCommandLine::HandleStop(), and lldb_private::CommandInterpreter::SourceInitFile().
SetStopOnCrash()
void lldb_private::CommandInterpreterRunOptions::SetStopOnCrash (bool stop_on_crash) inline
Definition at line 141 of file CommandInterpreter.h.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, and m_stop_on_crash.
SetStopOnError()
void lldb_private::CommandInterpreterRunOptions::SetStopOnError (bool stop_on_error) inline
Definition at line 135 of file CommandInterpreter.h.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, and m_stop_on_error.
Referenced by lldb_private::BreakpointOptions::BreakpointOptionsCallbackFunction(), CommandObjectCommandsSource::DoExecute(), CommandObjectSettingsRead::DoExecute(), lldb_private::Target::StopHookCommandLine::HandleStop(), and lldb_private::CommandInterpreter::SourceInitFile().
Member Data Documentation
m_add_to_history
LazyBool lldb_private::CommandInterpreterRunOptions::m_add_to_history = eLazyBoolCalculate
Definition at line 204 of file CommandInterpreter.h.
Referenced by CommandInterpreterRunOptions(), GetAddToHistory(), lldb_private::CommandInterpreter::HandleCommands(), SetAddToHistory(), and SetSilent().
m_allow_repeats
LazyBool lldb_private::CommandInterpreterRunOptions::m_allow_repeats = eLazyBoolCalculate
Definition at line 207 of file CommandInterpreter.h.
Referenced by CommandInterpreterRunOptions(), GetAllowRepeats(), lldb_private::CommandInterpreter::GetIOHandler(), and SetAllowRepeats().
m_auto_handle_events
LazyBool lldb_private::CommandInterpreterRunOptions::m_auto_handle_events
Definition at line 205 of file CommandInterpreter.h.
Referenced by GetAutoHandleEvents(), and SetAutoHandleEvents().
m_echo_commands
LazyBool lldb_private::CommandInterpreterRunOptions::m_echo_commands = eLazyBoolCalculate
Definition at line 200 of file CommandInterpreter.h.
Referenced by CommandInterpreterRunOptions(), GetEchoCommands(), lldb_private::CommandInterpreter::GetIOHandler(), lldb_private::CommandInterpreter::HandleCommandsFromFile(), SetEchoCommands(), and SetSilent().
m_echo_comment_commands
LazyBool lldb_private::CommandInterpreterRunOptions::m_echo_comment_commands = eLazyBoolCalculate
Definition at line 201 of file CommandInterpreter.h.
Referenced by CommandInterpreterRunOptions(), GetEchoCommentCommands(), lldb_private::CommandInterpreter::GetIOHandler(), lldb_private::CommandInterpreter::HandleCommandsFromFile(), SetEchoCommentCommands(), and SetSilent().
m_print_errors
LazyBool lldb_private::CommandInterpreterRunOptions::m_print_errors = eLazyBoolCalculate
Definition at line 203 of file CommandInterpreter.h.
Referenced by CommandInterpreterRunOptions(), lldb_private::CommandInterpreter::GetIOHandler(), GetPrintErrors(), lldb_private::CommandInterpreter::HandleCommandsFromFile(), SetPrintErrors(), and SetSilent().
m_print_results
LazyBool lldb_private::CommandInterpreterRunOptions::m_print_results = eLazyBoolCalculate
Definition at line 202 of file CommandInterpreter.h.
Referenced by CommandInterpreterRunOptions(), lldb_private::CommandInterpreter::GetIOHandler(), GetPrintResults(), lldb_private::CommandInterpreter::HandleCommandsFromFile(), SetPrintResults(), and SetSilent().
m_spawn_thread
LazyBool lldb_private::CommandInterpreterRunOptions::m_spawn_thread
Definition at line 206 of file CommandInterpreter.h.
Referenced by GetSpawnThread(), and SetSpawnThread().
m_stop_on_continue
LazyBool lldb_private::CommandInterpreterRunOptions::m_stop_on_continue = eLazyBoolCalculate
Definition at line 197 of file CommandInterpreter.h.
Referenced by CommandInterpreterRunOptions(), lldb_private::CommandInterpreter::GetIOHandler(), GetStopOnContinue(), lldb_private::CommandInterpreter::HandleCommandsFromFile(), and SetStopOnContinue().
m_stop_on_crash
LazyBool lldb_private::CommandInterpreterRunOptions::m_stop_on_crash = eLazyBoolCalculate
Definition at line 199 of file CommandInterpreter.h.
Referenced by CommandInterpreterRunOptions(), lldb_private::CommandInterpreter::GetIOHandler(), GetStopOnCrash(), and SetStopOnCrash().
m_stop_on_error
LazyBool lldb_private::CommandInterpreterRunOptions::m_stop_on_error = eLazyBoolCalculate
Definition at line 198 of file CommandInterpreter.h.
Referenced by CommandInterpreterRunOptions(), lldb_private::CommandInterpreter::GetIOHandler(), GetStopOnError(), lldb_private::CommandInterpreter::HandleCommandsFromFile(), and SetStopOnError().
The documentation for this class was generated from the following file:
CommandInterpreter.h