LLDB: lldb_private::ClangDynamicCheckerFunctions Class Reference
lldb_private::ClangDynamicCheckerFunctions Class Reference
#include <IRDynamicChecks.h>
Public Member Functions
ClangDynamicCheckerFunctions ()
Constructor.
~ClangDynamicCheckerFunctions () override
Destructor.
llvm::Error Install (DiagnosticManager &diagnostic_manager, ExecutionContext &exe_ctx) override
Install the utility functions into a process.
bool DoCheckersExplainStop (lldb::addr_t addr, Stream &message) override
Public Member Functions inherited from lldb_private::DynamicCheckerFunctions
DynamicCheckerFunctions (DynamicCheckerFunctionsKind kind)
virtual ~DynamicCheckerFunctions ()=default
DynamicCheckerFunctionsKind GetKind () const
Static Public Member Functions
static bool classof (const DynamicCheckerFunctions *checker_funcs)
Public Attributes
std::shared_ptr< UtilityFunction > m_objc_object_check
Additional Inherited Members
Public Types inherited from lldb_private::DynamicCheckerFunctions
enum DynamicCheckerFunctionsKind { DCF_Clang }
Detailed Description
Definition at line 26 of file IRDynamicChecks.h.
Constructor & Destructor Documentation
ClangDynamicCheckerFunctions()
ClangDynamicCheckerFunctions::ClangDynamicCheckerFunctions ()
Constructor.
Definition at line 38 of file IRDynamicChecks.cpp.
References lldb_private::DynamicCheckerFunctions::DCF_Clang, and lldb_private::DynamicCheckerFunctions::DynamicCheckerFunctions().
~ClangDynamicCheckerFunctions()
ClangDynamicCheckerFunctions::~ClangDynamicCheckerFunctions () override default
Destructor.
Member Function Documentation
classof()
bool lldb_private::ClangDynamicCheckerFunctions::classof (const DynamicCheckerFunctions * checker_funcs) inline static
Definition at line 35 of file IRDynamicChecks.h.
References lldb_private::DynamicCheckerFunctions::DCF_Clang, lldb_private::DynamicCheckerFunctions::DynamicCheckerFunctions(), and lldb_private::DynamicCheckerFunctions::GetKind().
DoCheckersExplainStop()
bool ClangDynamicCheckerFunctions::DoCheckersExplainStop (lldb::addr_t addr, Stream & message) override virtual
Implements lldb_private::DynamicCheckerFunctions.
Definition at line 68 of file IRDynamicChecks.cpp.
References m_objc_object_check, and lldb_private::Stream::Printf().
Install()
llvm::Error ClangDynamicCheckerFunctions::Install (DiagnosticManager & diagnostic_manager, ExecutionContext & exe_ctx) override virtual
Install the utility functions into a process.
This binds the instance of DynamicCheckerFunctions to that process.
Parameters
[in] diagnostic_manager A diagnostic manager to report errors to.
[in] exe_ctx The execution context to install the functions into.
Returns
Either llvm::ErrorSuccess or Error with llvm::ErrorInfo
Implements lldb_private::DynamicCheckerFunctions.
Definition at line 44 of file IRDynamicChecks.cpp.
References lldb_private::SourceLanguage::AsLanguageType(), lldb_private::ObjCLanguageRuntime::CreateObjectChecker(), lldb_private::ObjCLanguageRuntime::Get(), lldb_private::ExecutionContext::GetFramePtr(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::Language::LanguageIsObjC(), m_objc_object_check, and VALID_OBJC_OBJECT_CHECK_NAME.
Referenced by lldb_private::ClangExpressionParser::DoPrepareForExecution().
Member Data Documentation
m_objc_object_check
std::shared_ptr<UtilityFunction> lldb_private::ClangDynamicCheckerFunctions::m_objc_object_check
Definition at line 56 of file IRDynamicChecks.h.
Referenced by DoCheckersExplainStop(), and Install().
The documentation for this class was generated from the following files:
IRDynamicChecks.h
IRDynamicChecks.cpp