LLDB: lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS Class Reference
lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS Class Reference
#include <GDBRemoteCommunicationServerLLGS.h>
Classes
struct DebuggedProcess
Public Member Functions
GDBRemoteCommunicationServerLLGS (MainLoop &mainloop, NativeProcessProtocol::Manager &process_manager)
void SetLaunchInfo (const ProcessLaunchInfo &info)
Status LaunchProcess () override
Launch a process with the current launch settings.
Status AttachToProcess (lldb::pid_t pid)
Attach to a process.
Status AttachWaitProcess (llvm::StringRef process_name, bool include_existing)
Wait to attach to a process with a given name.
void InitializeDelegate (NativeProcessProtocol *process) override
void ProcessStateChanged (NativeProcessProtocol *process, lldb::StateType state) override
void DidExec (NativeProcessProtocol *process) override
void NewSubprocess (NativeProcessProtocol *parent_process, std::unique_ptr< NativeProcessProtocol > child_process) override
Status InitializeConnection (std::unique_ptr< Connection > connection)
GDBRemoteCommunication::PacketResult SendStructuredDataPacket (const llvm::json::Value &value)
Public Member Functions inherited from lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon
GDBRemoteCommunicationServerCommon ()
~GDBRemoteCommunicationServerCommon () override
Public Member Functions inherited from lldb_private::process_gdb_remote::GDBRemoteCommunicationServer
GDBRemoteCommunicationServer ()
~GDBRemoteCommunicationServer () override
void RegisterPacketHandler (StringExtractorGDBRemote::ServerPacketType packet_type, PacketHandler handler)
PacketResult GetPacketAndSendResponse (Timeout< std::micro > timeout, Status &error, bool &interrupt, bool &quit)
Public Member Functions inherited from lldb_private::process_gdb_remote::GDBRemoteCommunication
GDBRemoteCommunication ()
~GDBRemoteCommunication () override
PacketResult GetAck ()
size_t SendAck ()
size_t SendNack ()
char CalculcateChecksum (llvm::StringRef payload)
PacketType CheckForPacket (const uint8_t *src, size_t src_len, StringExtractorGDBRemote &packet)
bool GetSendAcks ()
std::chrono::seconds SetPacketTimeout (std::chrono::seconds packet_timeout)
std::chrono::seconds GetPacketTimeout () const
void DumpHistory (Stream &strm)
Public Member Functions inherited from lldb_private::Communication
Communication ()
Construct the Communication object.
virtual ~Communication ()
Destructor.
virtual void Clear ()
lldb::ConnectionStatus Connect (const char *url, Status *error_ptr)
Connect using the current connection by passing url to its connect function.
virtual lldb::ConnectionStatus Disconnect (Status *error_ptr=nullptr)
Disconnect the communications connection if one is currently connected.
bool IsConnected () const
Check if the connection is valid.
bool HasConnection () const
lldb_private::Connection * GetConnection ()
virtual size_t Read (void *dst, size_t dst_len, const Timeout< std::micro > &timeout, lldb::ConnectionStatus &status, Status *error_ptr)
Read bytes from the current connection.
size_t Write (const void *src, size_t src_len, lldb::ConnectionStatus &status, Status *error_ptr)
The actual write function that attempts to write to the communications protocol.
size_t WriteAll (const void *src, size_t src_len, lldb::ConnectionStatus &status, Status *error_ptr)
Repeatedly attempt writing until either src_len bytes are written or a permanent failure occurs.
virtual void SetConnection (std::unique_ptr< Connection > connection)
Sets the connection that it to be used by this class.
bool GetCloseOnEOF () const
void SetCloseOnEOF (bool b)
Public Member Functions inherited from lldb_private::NativeProcessProtocol::NativeDelegate
virtual ~NativeDelegate ()=default
Protected Member Functions
PacketResult SendONotification (const char *buffer, uint32_t len)
PacketResult SendWResponse (NativeProcessProtocol *process)
StreamString PrepareStopReplyPacketForThread (NativeThreadProtocol &thread)
PacketResult SendStopReplyPacketForThread (NativeProcessProtocol &process, lldb::tid_t tid, bool force_synchronous)
PacketResult SendStopReasonForState (NativeProcessProtocol &process, lldb::StateType process_state, bool force_synchronous)
void EnqueueStopReplyPackets (lldb::tid_t thread_to_skip)
PacketResult Handle_k (StringExtractorGDBRemote &packet)
PacketResult Handle_vKill (StringExtractorGDBRemote &packet)
PacketResult Handle_qProcessInfo (StringExtractorGDBRemote &packet)
PacketResult Handle_qC (StringExtractorGDBRemote &packet)
PacketResult Handle_QSetDisableASLR (StringExtractorGDBRemote &packet)
PacketResult Handle_QSetWorkingDir (StringExtractorGDBRemote &packet)
PacketResult Handle_qGetWorkingDir (StringExtractorGDBRemote &packet)
PacketResult Handle_QThreadSuffixSupported (StringExtractorGDBRemote &packet)
PacketResult Handle_QListThreadsInStopReply (StringExtractorGDBRemote &packet)
PacketResult ResumeProcess (NativeProcessProtocol &process, const ResumeActionList &actions)
PacketResult Handle_C (StringExtractorGDBRemote &packet)
PacketResult Handle_c (StringExtractorGDBRemote &packet)
PacketResult Handle_vCont (StringExtractorGDBRemote &packet)
PacketResult Handle_vCont_actions (StringExtractorGDBRemote &packet)
PacketResult Handle_stop_reason (StringExtractorGDBRemote &packet)
PacketResult Handle_qRegisterInfo (StringExtractorGDBRemote &packet)
void AddProcessThreads (StreamGDBRemote &response, NativeProcessProtocol &process, bool &had_any)
PacketResult Handle_qfThreadInfo (StringExtractorGDBRemote &packet)
PacketResult Handle_qsThreadInfo (StringExtractorGDBRemote &packet)
PacketResult Handle_qStructuredDataPlugins (StringExtractorGDBRemote &packet)
PacketResult Handle_p (StringExtractorGDBRemote &packet)
PacketResult Handle_P (StringExtractorGDBRemote &packet)
PacketResult Handle_H (StringExtractorGDBRemote &packet)
PacketResult Handle_I (StringExtractorGDBRemote &packet)
PacketResult Handle_interrupt (StringExtractorGDBRemote &packet)
PacketResult Handle_memory_read (StringExtractorGDBRemote &packet)
PacketResult Handle_M (StringExtractorGDBRemote &packet)
PacketResult Handle__M (StringExtractorGDBRemote &packet)
PacketResult Handle__m (StringExtractorGDBRemote &packet)
PacketResult Handle_qMemoryRegionInfoSupported (StringExtractorGDBRemote &packet)
PacketResult Handle_qMemoryRegionInfo (StringExtractorGDBRemote &packet)
PacketResult Handle_Z (StringExtractorGDBRemote &packet)
PacketResult Handle_z (StringExtractorGDBRemote &packet)
PacketResult Handle_s (StringExtractorGDBRemote &packet)
PacketResult Handle_qXfer (StringExtractorGDBRemote &packet)
PacketResult Handle_QSaveRegisterState (StringExtractorGDBRemote &packet)
PacketResult Handle_jLLDBTraceSupported (StringExtractorGDBRemote &packet)
PacketResult Handle_jLLDBTraceStart (StringExtractorGDBRemote &packet)
PacketResult Handle_jLLDBTraceStop (StringExtractorGDBRemote &packet)
PacketResult Handle_jLLDBTraceGetState (StringExtractorGDBRemote &packet)
PacketResult Handle_jLLDBTraceGetBinaryData (StringExtractorGDBRemote &packet)
PacketResult Handle_QRestoreRegisterState (StringExtractorGDBRemote &packet)
PacketResult Handle_vAttach (StringExtractorGDBRemote &packet)
PacketResult Handle_vAttachWait (StringExtractorGDBRemote &packet)
PacketResult Handle_qVAttachOrWaitSupported (StringExtractorGDBRemote &packet)
PacketResult Handle_vAttachOrWait (StringExtractorGDBRemote &packet)
PacketResult Handle_vRun (StringExtractorGDBRemote &packet)
PacketResult Handle_D (StringExtractorGDBRemote &packet)
PacketResult Handle_qThreadStopInfo (StringExtractorGDBRemote &packet)
PacketResult Handle_jThreadsInfo (StringExtractorGDBRemote &packet)
PacketResult Handle_qWatchpointSupportInfo (StringExtractorGDBRemote &packet)
PacketResult Handle_qFileLoadAddress (StringExtractorGDBRemote &packet)
PacketResult Handle_QPassSignals (StringExtractorGDBRemote &packet)
PacketResult Handle_qSaveCore (StringExtractorGDBRemote &packet)
PacketResult Handle_QNonStop (StringExtractorGDBRemote &packet)
PacketResult HandleNotificationAck (std::deque< std::string > &queue)
PacketResult Handle_vStdio (StringExtractorGDBRemote &packet)
PacketResult Handle_vStopped (StringExtractorGDBRemote &packet)
PacketResult Handle_vCtrlC (StringExtractorGDBRemote &packet)
PacketResult Handle_g (StringExtractorGDBRemote &packet)
PacketResult Handle_qMemTags (StringExtractorGDBRemote &packet)
PacketResult Handle_QMemTags (StringExtractorGDBRemote &packet)
PacketResult Handle_T (StringExtractorGDBRemote &packet)
void SetCurrentThreadID (lldb::tid_t tid)
lldb::tid_t GetCurrentThreadID () const
void SetContinueThreadID (lldb::tid_t tid)
lldb::tid_t GetContinueThreadID () const
Status SetSTDIOFileDescriptor (int fd)
FileSpec FindModuleFile (const std::string &module_path, const ArchSpec &arch) override
llvm::Expected< std::unique_ptr< llvm::MemoryBuffer > > ReadXferObject (llvm::StringRef object, llvm::StringRef annex)
std::vector< std::string > HandleFeatures (const llvm::ArrayRef< llvm::StringRef > client_features) override
PacketResult SendContinueSuccessResponse ()
void AppendThreadIDToResponse (Stream &response, lldb::pid_t pid, lldb::tid_t tid)
Protected Member Functions inherited from lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon
PacketResult Handle_A (StringExtractorGDBRemote &packet)
PacketResult Handle_qHostInfo (StringExtractorGDBRemote &packet)
PacketResult Handle_qProcessInfoPID (StringExtractorGDBRemote &packet)
PacketResult Handle_qfProcessInfo (StringExtractorGDBRemote &packet)
PacketResult Handle_qsProcessInfo (StringExtractorGDBRemote &packet)
PacketResult Handle_qUserName (StringExtractorGDBRemote &packet)
PacketResult Handle_qGroupName (StringExtractorGDBRemote &packet)
PacketResult Handle_qSpeedTest (StringExtractorGDBRemote &packet)
PacketResult Handle_vFile_Open (StringExtractorGDBRemote &packet)
PacketResult Handle_vFile_Close (StringExtractorGDBRemote &packet)
PacketResult Handle_vFile_pRead (StringExtractorGDBRemote &packet)
PacketResult Handle_vFile_pWrite (StringExtractorGDBRemote &packet)
PacketResult Handle_vFile_Size (StringExtractorGDBRemote &packet)
PacketResult Handle_vFile_Mode (StringExtractorGDBRemote &packet)
PacketResult Handle_vFile_Exists (StringExtractorGDBRemote &packet)
PacketResult Handle_vFile_symlink (StringExtractorGDBRemote &packet)
PacketResult Handle_vFile_unlink (StringExtractorGDBRemote &packet)
PacketResult Handle_vFile_FStat (StringExtractorGDBRemote &packet)
PacketResult Handle_vFile_Stat (StringExtractorGDBRemote &packet)
PacketResult Handle_vFile_MD5 (StringExtractorGDBRemote &packet)
PacketResult Handle_qEcho (StringExtractorGDBRemote &packet)
PacketResult Handle_qModuleInfo (StringExtractorGDBRemote &packet)
PacketResult Handle_jModulesInfo (StringExtractorGDBRemote &packet)
PacketResult Handle_qPlatform_shell (StringExtractorGDBRemote &packet)
PacketResult Handle_qPlatform_mkdir (StringExtractorGDBRemote &packet)
PacketResult Handle_qPlatform_chmod (StringExtractorGDBRemote &packet)
PacketResult Handle_qSupported (StringExtractorGDBRemote &packet)
PacketResult Handle_QSetDetachOnError (StringExtractorGDBRemote &packet)
PacketResult Handle_QStartNoAckMode (StringExtractorGDBRemote &packet)
PacketResult Handle_QSetSTDIN (StringExtractorGDBRemote &packet)
PacketResult Handle_QSetSTDOUT (StringExtractorGDBRemote &packet)
PacketResult Handle_QSetSTDERR (StringExtractorGDBRemote &packet)
PacketResult Handle_qLaunchSuccess (StringExtractorGDBRemote &packet)
PacketResult Handle_QEnvironment (StringExtractorGDBRemote &packet)
PacketResult Handle_QEnvironmentHexEncoded (StringExtractorGDBRemote &packet)
PacketResult Handle_QLaunchArch (StringExtractorGDBRemote &packet)
template<typename T>
void RegisterMemberFunctionHandler (StringExtractorGDBRemote::ServerPacketType packet_type, PacketResult(T::*handler)(StringExtractorGDBRemote &packet))
Protected Member Functions inherited from lldb_private::process_gdb_remote::GDBRemoteCommunicationServer
PacketResult Handle_QErrorStringEnable (StringExtractorGDBRemote &packet)
PacketResult SendErrorResponse (const Status &error)
PacketResult SendErrorResponse (llvm::Error error)
PacketResult SendUnimplementedResponse (const char *packet)
PacketResult SendErrorResponse (uint8_t error)
PacketResult SendIllFormedResponse (const StringExtractorGDBRemote &packet, const char *error_message)
PacketResult SendOKResponse ()
PacketResult SendJSONResponse (const llvm::json::Value &value)
Serialize and send a JSON object response.
PacketResult SendJSONResponse (llvm::Expected< llvm::json::Value > value)
Serialize and send a JSON object response, or respond with an error if the input object is an llvm::Error.
Protected Member Functions inherited from lldb_private::process_gdb_remote::GDBRemoteCommunication
PacketResult SendPacketNoLock (llvm::StringRef payload)
PacketResult SendNotificationPacketNoLock (llvm::StringRef notify_type, std::deque< std::string > &queue, llvm::StringRef payload)
PacketResult SendRawPacketNoLock (llvm::StringRef payload, bool skip_ack=false)
PacketResult ReadPacket (StringExtractorGDBRemote &response, Timeout< std::micro > timeout, bool sync_on_timeout)
PacketResult WaitForPacketNoLock (StringExtractorGDBRemote &response, Timeout< std::micro > timeout, bool sync_on_timeout)
bool CompressionIsEnabled ()
bool DecompressPacket ()
Protected Member Functions inherited from lldb_private::Communication
size_t ReadFromConnection (void *dst, size_t dst_len, const Timeout< std::micro > &timeout, lldb::ConnectionStatus &status, Status *error_ptr)
Static Protected Member Functions
static std::string XMLEncodeAttributeValue (llvm::StringRef value)
Static Protected Member Functions inherited from lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon
static void CreateProcessInfoResponse (const ProcessInstanceInfo &proc_info, StreamString &response)
static void CreateProcessInfoResponse_DebugServerStyle (const ProcessInstanceInfo &proc_info, StreamString &response)
Protected Attributes
MainLoop & m_mainloop
MainLoop::ReadHandleUP m_network_handle_up
NativeProcessProtocol::Manager & m_process_manager
lldb::tid_t m_current_tid = LLDB_INVALID_THREAD_ID
lldb::tid_t m_continue_tid = LLDB_INVALID_THREAD_ID
NativeProcessProtocol * m_current_process
NativeProcessProtocol * m_continue_process
std::recursive_mutex m_debugged_process_mutex
std::unordered_map< lldb::pid_t, DebuggedProcess > m_debugged_processes
Communication m_stdio_communication
MainLoop::ReadHandleUP m_stdio_handle_up
llvm::StringMap< std::unique_ptr< llvm::MemoryBuffer > > m_xfer_buffer_map
std::mutex m_saved_registers_mutex
std::unordered_map< uint32_t, lldb::DataBufferSP > m_saved_registers_map
uint32_t m_next_saved_registers_id = 1
bool m_thread_suffix_supported = false
bool m_list_threads_in_stop_reply = false
bool m_non_stop = false
bool m_disabling_non_stop = false
std::deque< std::string > m_stdio_notification_queue
std::deque< std::string > m_stop_notification_queue
NativeProcessProtocol::Extension m_extensions_supported = {}
uint8_t m_reg_bytes [RegisterValue::kMaxRegisterByteSize]
Protected Attributes inherited from lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon
ProcessLaunchInfo m_process_launch_info
Status m_process_launch_error
ProcessInstanceInfoList m_proc_infos
uint32_t m_proc_infos_index
Protected Attributes inherited from lldb_private::process_gdb_remote::GDBRemoteCommunicationServer
std::map< StringExtractorGDBRemote::ServerPacketType, PacketHandler > m_packet_handlers
bool m_exit_now
bool m_send_error_strings = false
Protected Attributes inherited from lldb_private::process_gdb_remote::GDBRemoteCommunication
std::chrono::seconds m_packet_timeout
uint32_t m_echo_number
LazyBool m_supports_qEcho
GDBRemoteCommunicationHistory m_history
bool m_send_acks
bool m_is_platform
std::string m_bytes
std::recursive_mutex m_bytes_mutex
CompressionType m_compression_type
Protected Attributes inherited from lldb_private::Communication
lldb::ConnectionSP m_connection_sp
The connection that is current in use by this communications class.
std::mutex m_write_mutex
Don't let multiple threads write at the same time...
bool m_close_on_eof
Private Member Functions
llvm::Expected< std::unique_ptr< llvm::MemoryBuffer > > BuildTargetXml ()
void HandleInferiorState_Exited (NativeProcessProtocol *process)
void HandleInferiorState_Stopped (NativeProcessProtocol *process)
NativeThreadProtocol * GetThreadFromSuffix (StringExtractorGDBRemote &packet)
uint32_t GetNextSavedRegistersID ()
void MaybeCloseInferiorTerminalConnection ()
void ClearProcessSpecificData ()
void RegisterPacketHandlers ()
void DataAvailableCallback ()
void SendProcessOutput ()
void StartSTDIOForwarding ()
void StopSTDIOForwarding ()
void SetEnabledExtensions (NativeProcessProtocol &process)
GDBRemoteCommunicationServerLLGS (const GDBRemoteCommunicationServerLLGS &)=delete
const GDBRemoteCommunicationServerLLGS & operator= (const GDBRemoteCommunicationServerLLGS &)=delete
Additional Inherited Members
Public Types inherited from lldb_private::process_gdb_remote::GDBRemoteCommunicationServer
using PacketHandler
Public Types inherited from lldb_private::process_gdb_remote::GDBRemoteCommunication
enum class PacketType { Invalid = 0 , Standard , Notify }
enum class PacketResult {
Success = 0 , ErrorSendFailed , ErrorSendAck , ErrorReplyFailed ,
ErrorReplyTimeout , ErrorReplyInvalid , ErrorReplyAck , ErrorDisconnected ,
ErrorNoSequenceLock
}
Static Public Member Functions inherited from lldb_private::process_gdb_remote::GDBRemoteCommunication
static Status StartDebugserverProcess (std::variant< llvm::StringRef, shared_fd_t > comm, ProcessLaunchInfo &launch_info, const Args *inferior_args)
static std::optional< std::string > ExpandRLE (std::string)
Expand GDB run-length encoding.
Static Public Member Functions inherited from lldb_private::Communication
static std::string ConnectionStatusAsString (lldb::ConnectionStatus status)
Detailed Description
Definition at line 32 of file GDBRemoteCommunicationServerLLGS.h.
Constructor & Destructor Documentation
GDBRemoteCommunicationServerLLGS() [1/2]
GDBRemoteCommunicationServerLLGS::GDBRemoteCommunicationServerLLGS (MainLoop & mainloop, NativeProcessProtocol::Manager & process_manager)
Definition at line 71 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::GDBRemoteCommunicationServerCommon(), m_continue_process, m_current_process, m_mainloop, m_process_manager, m_stdio_communication, and RegisterPacketHandlers().
Referenced by GDBRemoteCommunicationServerLLGS(), and operator=().
GDBRemoteCommunicationServerLLGS() [2/2]
lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::GDBRemoteCommunicationServerLLGS (const GDBRemoteCommunicationServerLLGS &) private delete
References GDBRemoteCommunicationServerLLGS().
Member Function Documentation
AddProcessThreads()
void GDBRemoteCommunicationServerLLGS::AddProcessThreads (StreamGDBRemote & response, NativeProcessProtocol & process, bool & had_any) protected
Definition at line 2162 of file GDBRemoteCommunicationServerLLGS.cpp.
References AppendThreadIDToResponse(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), LLDB_INVALID_PROCESS_ID, LLDB_LOG, lldb_private::Stream::PutChar(), lldb_private::Thread, and lldb_private::NativeProcessProtocol::Threads().
Referenced by Handle_qfThreadInfo().
AppendThreadIDToResponse()
void GDBRemoteCommunicationServerLLGS::AppendThreadIDToResponse (Stream & response, lldb::pid_t pid, lldb::tid_t tid) protected
Definition at line 4378 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::Stream::Format(), m_extensions_supported, and lldb_private::NativeProcessProtocol::multiprocess.
Referenced by AddProcessThreads(), Handle_qC(), and PrepareStopReplyPacketForThread().
AttachToProcess()
Status GDBRemoteCommunicationServerLLGS::AttachToProcess (lldb::pid_t pid)
Attach to a process.
This method supports attaching llgs to a process accessible via the configured Platform.
Returns
An Status object indicating the success or failure of the attach operation.
Definition at line 347 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::Status::FromError(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::GetLog(), LLDB_LOGF, m_continue_process, m_current_process, m_debugged_processes, m_process_manager, and lldb_private::Process.
Referenced by AttachWaitProcess(), and Handle_vAttach().
AttachWaitProcess()
Status GDBRemoteCommunicationServerLLGS::AttachWaitProcess (llvm::StringRef process_name, bool include_existing)
Wait to attach to a process with a given name.
This method supports waiting for the next instance of a process with a given name and attaching llgs to that via the configured Platform.
Returns
An Status object indicating the success or failure of the attach operation.
Definition at line 395 of file GDBRemoteCommunicationServerLLGS.cpp.
References AttachToProcess(), lldb_private::Equals, error(), lldb_private::Host::FindProcesses(), lldb_private::Stream::Format(), lldb_private::ProcessInfo::GetExecutableFile(), lldb_private::GetLog(), lldb_private::ProcessInstanceInfoMatch::GetProcessInfo(), lldb_private::StreamString::GetString(), LLDB_LOG, lldb_private::Process, lldb_private::FileSpec::SetFile(), lldb_private::ProcessInstanceInfoMatch::SetNameMatchType(), and lldb_private::Status.
Referenced by Handle_vAttachOrWait(), and Handle_vAttachWait().
BuildTargetXml()
llvm::Expected< std::unique_ptr< llvm::MemoryBuffer > > GDBRemoteCommunicationServerLLGS::BuildTargetXml () private
Definition at line 3144 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::RegisterInfo::alt_name, lldb_private::RegisterInfo::byte_offset, lldb_private::RegisterInfo::byte_size, CollectRegNums(), lldb_private::RegisterFlags::EnumsToXML(), lldb::eRegisterKindDWARF, lldb::eRegisterKindEHFrame, lldb_private::RegisterInfo::flags_type, GetEncodingNameOrEmpty(), GetFormatNameOrEmpty(), lldb_private::RegisterFlags::GetID(), GetKindGenericOrEmpty(), lldb_private::GetLog(), lldb_private::NativeRegisterContext::GetRegisterInfoAtIndex(), lldb_private::NativeRegisterContext::GetRegisterSetNameForRegisterAtIndex(), lldb_private::StreamString::GetString(), lldb_private::NativeRegisterContext::GetUserRegisterCount(), lldb_private::Stream::Indent(), lldb_private::Stream::IndentLess(), lldb_private::Stream::IndentMore(), lldb_private::RegisterInfo::invalidate_regs, lldb_private::RegisterInfo::kinds, LLDB_INVALID_REGNUM, LLDB_LOGF, m_current_process, lldb_private::RegisterInfo::name, lldb_private::Stream::Printf(), lldb_private::Process, lldb_private::Stream::PutCString(), lldb_private::NativeRegisterContext::RegisterOffsetIsDynamic(), lldb_private::Thread, lldb_private::RegisterFlags::ToXML(), and lldb_private::RegisterInfo::value_regs.
Referenced by ReadXferObject().
ClearProcessSpecificData()
void GDBRemoteCommunicationServerLLGS::ClearProcessSpecificData () private
Definition at line 4255 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::GetLog(), LLDB_LOG, m_xfer_buffer_map, and lldb_private::Process.
Referenced by DidExec().
DataAvailableCallback()
void GDBRemoteCommunicationServerLLGS::DataAvailableCallback () private
Definition at line 1216 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::process_gdb_remote::Comm, error(), lldb_private::process_gdb_remote::GDBRemoteCommunication::ErrorReplyTimeout, lldb_private::GetLog(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::GetPacketAndSendResponse(), LLDB_LOGF, m_mainloop, and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by InitializeConnection().
DidExec()
void GDBRemoteCommunicationServerLLGS::DidExec (NativeProcessProtocol * process) override virtual
Implements lldb_private::NativeProcessProtocol::NativeDelegate.
Definition at line 1201 of file GDBRemoteCommunicationServerLLGS.cpp.
References ClearProcessSpecificData().
EnqueueStopReplyPackets()
void GDBRemoteCommunicationServerLLGS::EnqueueStopReplyPackets (lldb::tid_t thread_to_skip) protected
Definition at line 1083 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::StreamString::Empty(), lldb_private::StreamString::GetString(), m_current_process, m_non_stop, m_stop_notification_queue, and PrepareStopReplyPacketForThread().
Referenced by Handle_stop_reason(), and SendStopReplyPacketForThread().
FindModuleFile()
FileSpec GDBRemoteCommunicationServerLLGS::FindModuleFile (const std::string & module_path, const ArchSpec & arch) override protected virtual
Reimplemented from lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon.
Definition at line 4263 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::FindModuleFile(), lldb_private::FileSystem::Instance(), and m_current_process.
GetContinueThreadID()
lldb::tid_t lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::GetContinueThreadID () const inline protected
Definition at line 285 of file GDBRemoteCommunicationServerLLGS.h.
References m_continue_tid.
Referenced by Handle_C(), and Handle_s().
GetCurrentThreadID()
lldb::tid_t GDBRemoteCommunicationServerLLGS::GetCurrentThreadID () const protected
Definition at line 4237 of file GDBRemoteCommunicationServerLLGS.cpp.
References LLDB_INVALID_THREAD_ID, m_current_process, and m_current_tid.
Referenced by GetThreadFromSuffix(), and Handle_s().
GetNextSavedRegistersID()
uint32_t GDBRemoteCommunicationServerLLGS::GetNextSavedRegistersID () private
Definition at line 4250 of file GDBRemoteCommunicationServerLLGS.cpp.
References m_next_saved_registers_id, and m_saved_registers_mutex.
Referenced by Handle_QSaveRegisterState().
GetThreadFromSuffix()
NativeThreadProtocol * GDBRemoteCommunicationServerLLGS::GetThreadFromSuffix (StringExtractorGDBRemote & packet) private
Definition at line 4185 of file GDBRemoteCommunicationServerLLGS.cpp.
References StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), GetCurrentThreadID(), StringExtractor::GetFilePos(), StringExtractor::GetHexMaxU64(), lldb_private::GetLog(), StringExtractor::GetStringRef(), LLDB_INVALID_PROCESS_ID, LLDB_INVALID_THREAD_ID, LLDB_LOGF, m_current_process, m_thread_suffix_supported, StringExtractor::Peek(), StringExtractor::SetFilePos(), and lldb_private::Thread.
Referenced by Handle_g(), Handle_P(), Handle_p(), Handle_QRestoreRegisterState(), and Handle_QSaveRegisterState().
Handle__M()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle__M (StringExtractorGDBRemote & packet) protected
Definition at line 2640 of file GDBRemoteCommunicationServerLLGS.cpp.
References StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), StringExtractor::GetHexMaxU64(), lldb_private::GetLog(), lldb_private::StreamString::GetString(), LLDB_INVALID_ADDRESS, LLDB_INVALID_PROCESS_ID, LLDB_LOGF, m_current_process, lldb_private::Process, lldb_private::Stream::PutHex64(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), and StringExtractor::SetFilePos().
Referenced by RegisterPacketHandlers().
Handle__m()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle__m (StringExtractorGDBRemote & packet) protected
Definition at line 2689 of file GDBRemoteCommunicationServerLLGS.cpp.
References StringExtractor::GetBytesLeft(), StringExtractor::GetHexMaxU64(), lldb_private::GetLog(), LLDB_INVALID_ADDRESS, LLDB_INVALID_PROCESS_ID, LLDB_LOGF, m_current_process, lldb_private::Process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), and StringExtractor::SetFilePos().
Referenced by RegisterPacketHandlers().
Handle_C()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_C (StringExtractorGDBRemote & packet) protected
Definition at line 1642 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::ResumeActionList::Append(), error(), lldb::eStateRunning, StringExtractor::GetBytesLeft(), GetContinueThreadID(), StringExtractor::GetHexMaxU32(), lldb_private::GetLog(), StringExtractor::GetStringRef(), LLDB_INVALID_SIGNAL_NUMBER, LLDB_INVALID_THREAD_ID, LLDB_LOG, LLDB_LOGF, m_continue_process, StringExtractor::Peek(), lldb_private::Process, ResumeProcess(), SendContinueSuccessResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendUnimplementedResponse(), StringExtractor::SetFilePos(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and lldb_private::Thread.
Referenced by RegisterPacketHandlers().
Handle_c()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_c (StringExtractorGDBRemote & packet) protected
Definition at line 1729 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb::eStateRunning, StringExtractor::GetBytesLeft(), StringExtractor::GetFilePos(), lldb_private::GetLog(), StringExtractor::GetStringRef(), LLDB_INVALID_SIGNAL_NUMBER, LLDB_LOG, LLDB_LOGF, m_continue_process, StringExtractor::Peek(), lldb_private::Process, ResumeProcess(), SendContinueSuccessResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendUnimplementedResponse(), StringExtractor::SetFilePos(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and lldb_private::Thread.
Referenced by RegisterPacketHandlers().
Handle_D()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_D (StringExtractorGDBRemote & packet) protected
Definition at line 3642 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::Status::FromErrorStringWithFormat(), StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), lldb_private::GetLog(), StringExtractor::GetU32(), LLDB_INVALID_PROCESS_ID, LLDB_LOGF, m_continue_process, m_current_process, m_debugged_processes, m_non_stop, lldb_private::Process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), StringExtractor::SetFilePos(), and StopSTDIOForwarding().
Referenced by RegisterPacketHandlers().
Handle_g()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_g (StringExtractorGDBRemote & packet) protected
Definition at line 2206 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::RegisterInfo::byte_offset, lldb_private::RegisterInfo::byte_size, error(), lldb_private::RegisterValue::GetBytes(), lldb_private::GetLog(), lldb_private::NativeRegisterContext::GetRegisterInfoAtIndex(), lldb_private::StreamString::GetString(), GetThreadFromSuffix(), lldb_private::NativeRegisterContext::GetUserRegisterCount(), LLDB_LOG, lldb_private::Stream::PutBytesAsRawHex8(), lldb_private::NativeRegisterContext::ReadRegister(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), StringExtractor::SetFilePos(), lldb_private::Thread, and lldb_private::RegisterInfo::value_regs.
Referenced by RegisterPacketHandlers().
Handle_H()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_H (StringExtractorGDBRemote & packet) protected
Definition at line 2416 of file GDBRemoteCommunicationServerLLGS.cpp.
References StringExtractorGDBRemote::AllProcesses, StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), StringExtractorGDBRemote::GetPidTid(), LLDB_INVALID_PROCESS_ID, LLDB_INVALID_THREAD_ID, LLDB_LOGF, m_continue_process, m_current_process, m_debugged_processes, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendUnimplementedResponse(), SetContinueThreadID(), SetCurrentThreadID(), StringExtractor::SetFilePos(), and lldb_private::Thread.
Referenced by RegisterPacketHandlers().
Handle_I()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_I (StringExtractorGDBRemote & packet) protected
Definition at line 2508 of file GDBRemoteCommunicationServerLLGS.cpp.
References error(), StringExtractor::GetHexBytesAvail(), lldb_private::GetLog(), LLDB_INVALID_PROCESS_ID, LLDB_LOGF, m_current_process, m_stdio_communication, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), StringExtractor::SetFilePos(), and lldb_private::Thread.
Referenced by RegisterPacketHandlers().
Handle_interrupt()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_interrupt (StringExtractorGDBRemote & packet) protected
Definition at line 2543 of file GDBRemoteCommunicationServerLLGS.cpp.
References error(), lldb_private::GetLog(), LLDB_INVALID_PROCESS_ID, LLDB_LOG, m_current_process, lldb_private::Process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and lldb_private::Thread.
Referenced by Handle_vCtrlC(), and RegisterPacketHandlers().
Handle_jLLDBTraceGetBinaryData()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_jLLDBTraceGetBinaryData (StringExtractorGDBRemote & packet) protected
Definition at line 1431 of file GDBRemoteCommunicationServerLLGS.cpp.
References StringExtractor::ConsumeFront(), lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), lldb_private::StreamString::GetString(), LLDB_INVALID_PROCESS_ID, m_current_process, StringExtractor::Peek(), lldb_private::StreamGDBRemote::PutEscapedBytes(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock().
Referenced by RegisterPacketHandlers().
Handle_jLLDBTraceGetState()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_jLLDBTraceGetState (StringExtractorGDBRemote & packet) protected
Definition at line 1413 of file GDBRemoteCommunicationServerLLGS.cpp.
References StringExtractor::ConsumeFront(), lldb_private::Status::FromErrorString(), LLDB_INVALID_PROCESS_ID, m_current_process, StringExtractor::Peek(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendJSONResponse().
Referenced by RegisterPacketHandlers().
Handle_jLLDBTraceStart()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_jLLDBTraceStart (StringExtractorGDBRemote & packet) protected
Definition at line 1392 of file GDBRemoteCommunicationServerLLGS.cpp.
References StringExtractor::ConsumeFront(), lldb_private::Status::FromErrorString(), LLDB_INVALID_PROCESS_ID, m_current_process, StringExtractor::Peek(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse().
Referenced by RegisterPacketHandlers().
Handle_jLLDBTraceStop()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_jLLDBTraceStop (StringExtractorGDBRemote & packet) protected
Definition at line 1372 of file GDBRemoteCommunicationServerLLGS.cpp.
References StringExtractor::ConsumeFront(), lldb_private::Status::FromErrorString(), LLDB_INVALID_PROCESS_ID, m_current_process, StringExtractor::Peek(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse().
Referenced by RegisterPacketHandlers().
Handle_jLLDBTraceSupported()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_jLLDBTraceSupported (StringExtractorGDBRemote & packet) protected
Definition at line 1360 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::Status::FromErrorString(), LLDB_INVALID_PROCESS_ID, m_current_process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendJSONResponse().
Referenced by RegisterPacketHandlers().
Handle_jThreadsInfo()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_jThreadsInfo (StringExtractorGDBRemote & packet) protected
Definition at line 3717 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::Stream::AsRawOstream(), lldb_private::StreamString::GetData(), GetJSONThreadsInfo(), lldb_private::GetLog(), lldb_private::StreamString::GetSize(), lldb_private::StreamString::GetString(), LLDB_INVALID_PROCESS_ID, LLDB_LOG, LLDB_LOG_ERROR, m_current_process, lldb_private::Process, lldb_private::StreamGDBRemote::PutEscapedBytes(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), and lldb_private::Thread.
Referenced by RegisterPacketHandlers().
Handle_k()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_k (StringExtractorGDBRemote & packet) protected
Definition at line 1517 of file GDBRemoteCommunicationServerLLGS.cpp.
References error(), lldb_private::GetLog(), LLDB_LOG, m_debugged_processes, m_non_stop, lldb_private::Process, SendContinueSuccessResponse(), StopSTDIOForwarding(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by RegisterPacketHandlers().
Handle_M()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_M (StringExtractorGDBRemote & packet) protected
Definition at line 2717 of file GDBRemoteCommunicationServerLLGS.cpp.
References error(), StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), StringExtractor::GetHexBytes(), StringExtractor::GetHexMaxU64(), lldb_private::GetLog(), LLDB_INVALID_PROCESS_ID, LLDB_LOG, LLDB_LOGF, m_current_process, lldb_private::Process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), StringExtractor::SetFilePos(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by RegisterPacketHandlers().
Handle_memory_read()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_memory_read (StringExtractorGDBRemote & packet) protected
Definition at line 2569 of file GDBRemoteCommunicationServerLLGS.cpp.
References error(), StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), StringExtractor::GetHexMaxU64(), lldb_private::GetLog(), lldb_private::StreamString::GetString(), LLDB_INVALID_PROCESS_ID, LLDB_LOG, LLDB_LOGF, m_current_process, lldb_private::Process, lldb_private::StreamGDBRemote::PutEscapedBytes(), lldb_private::Stream::PutHex8(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), and StringExtractor::SetFilePos().
Referenced by RegisterPacketHandlers().
Handle_P()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_P (StringExtractorGDBRemote & packet) protected
Definition at line 2337 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::RegisterInfo::byte_size, error(), StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), StringExtractor::GetHexBytesAvail(), StringExtractor::GetHexMaxU32(), lldb_private::GetLog(), lldb_private::NativeRegisterContext::GetRegisterInfoAtIndex(), StringExtractor::GetStringRef(), GetThreadFromSuffix(), lldb_private::NativeRegisterContext::GetUserRegisterCount(), LLDB_LOGF, m_current_process, m_reg_bytes, lldb_private::RegisterInfo::name, reg_size, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), StringExtractor::SetFilePos(), lldb_private::Thread, and lldb_private::NativeRegisterContext::WriteRegister().
Referenced by RegisterPacketHandlers().
Handle_p()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_p (StringExtractorGDBRemote & packet) protected
Definition at line 2261 of file GDBRemoteCommunicationServerLLGS.cpp.
References error(), lldb_private::RegisterValue::GetBytes(), lldb_private::RegisterValue::GetByteSize(), StringExtractor::GetHexMaxU32(), lldb_private::GetLog(), lldb_private::NativeRegisterContext::GetRegisterInfoAtIndex(), lldb_private::StreamString::GetString(), StringExtractor::GetStringRef(), GetThreadFromSuffix(), lldb_private::NativeRegisterContext::GetUserRegisterCount(), LLDB_LOG, LLDB_LOGF, lldb_private::RegisterInfo::name, lldb_private::Stream::PutHex8(), lldb_private::NativeRegisterContext::ReadRegister(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), StringExtractor::SetFilePos(), and lldb_private::Thread.
Referenced by RegisterPacketHandlers().
Handle_qC()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_qC (StringExtractorGDBRemote & packet) protected
Definition at line 1493 of file GDBRemoteCommunicationServerLLGS.cpp.
References AppendThreadIDToResponse(), lldb_private::StreamString::GetString(), LLDB_INVALID_PROCESS_ID, m_current_process, lldb_private::Stream::PutCString(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), and SetCurrentThreadID().
Referenced by RegisterPacketHandlers().
Handle_qFileLoadAddress()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_qFileLoadAddress (StringExtractorGDBRemote & packet) protected
Definition at line 3770 of file GDBRemoteCommunicationServerLLGS.cpp.
References error(), StringExtractor::GetBytesLeft(), StringExtractor::GetHexByteString(), lldb_private::StreamString::GetString(), LLDB_INVALID_ADDRESS, LLDB_INVALID_PROCESS_ID, m_current_process, lldb_private::Stream::PutHex64(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), and StringExtractor::SetFilePos().
Referenced by RegisterPacketHandlers().
Handle_qfThreadInfo()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_qfThreadInfo (StringExtractorGDBRemote & packet) protected
Definition at line 2180 of file GDBRemoteCommunicationServerLLGS.cpp.
References AddProcessThreads(), lldb_private::StreamString::GetString(), m_debugged_processes, m_extensions_supported, lldb_private::NativeProcessProtocol::multiprocess, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock().
Referenced by RegisterPacketHandlers().
Handle_qGetWorkingDir()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_qGetWorkingDir (StringExtractorGDBRemote & packet) protected
Definition at line 1591 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::FileSpec::GetPath(), lldb_private::StreamString::GetString(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::m_process_launch_info, lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock().
Referenced by RegisterPacketHandlers().
Handle_QListThreadsInStopReply()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_QListThreadsInStopReply (StringExtractorGDBRemote & packet) protected
Definition at line 1611 of file GDBRemoteCommunicationServerLLGS.cpp.
References m_list_threads_in_stop_reply, and lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse().
Referenced by RegisterPacketHandlers().
Handle_qMemoryRegionInfo()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_qMemoryRegionInfo (StringExtractorGDBRemote & packet) protected
Definition at line 2829 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::MemoryRegionInfo::eDontKnow, error(), lldb_private::MemoryRegionInfo::eYes, lldb_private::Range< B, S >::GetByteSize(), StringExtractor::GetBytesLeft(), lldb_private::MemoryRegionInfo::GetExecutable(), StringExtractor::GetHexMaxU64(), lldb_private::GetLog(), lldb_private::MemoryRegionInfo::GetMemoryTagged(), lldb_private::MemoryRegionInfo::GetName(), lldb_private::MemoryRegionInfo::GetRange(), lldb_private::Range< B, S >::GetRangeBase(), lldb_private::MemoryRegionInfo::GetReadable(), lldb_private::StreamString::GetString(), lldb_private::ConstString::GetStringRef(), lldb_private::MemoryRegionInfo::GetWritable(), lldb_private::MemoryRegionInfo::IsShadowStack(), LLDB_INVALID_PROCESS_ID, LLDB_LOGF, m_current_process, lldb_private::Stream::Printf(), lldb_private::Process, lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), and StringExtractor::SetFilePos().
Referenced by RegisterPacketHandlers().
Handle_qMemoryRegionInfoSupported()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_qMemoryRegionInfoSupported (StringExtractorGDBRemote & packet) protected
Definition at line 2796 of file GDBRemoteCommunicationServerLLGS.cpp.
References error(), lldb_private::GetLog(), LLDB_INVALID_PROCESS_ID, LLDB_LOGF, m_current_process, lldb_private::Process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendUnimplementedResponse().
Referenced by RegisterPacketHandlers().
Handle_QMemTags()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_QMemTags (StringExtractorGDBRemote & packet) protected
Definition at line 3914 of file GDBRemoteCommunicationServerLLGS.cpp.
References StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), StringExtractor::GetHexBytes(), StringExtractor::GetHexMaxU64(), lldb_private::GetLog(), StringExtractor::GetU64(), LLDB_INVALID_PROCESS_ID, LLDB_LOGF, m_current_process, StringExtractor::Peek(), lldb_private::Process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), StringExtractor::SetFilePos(), and lldb_private::Status::Success().
Referenced by RegisterPacketHandlers().
Handle_qMemTags()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_qMemTags (StringExtractorGDBRemote & packet) protected
Definition at line 3833 of file GDBRemoteCommunicationServerLLGS.cpp.
References error(), StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), StringExtractor::GetHexMaxU64(), lldb_private::GetLog(), lldb_private::StreamString::GetString(), StringExtractor::GetU64(), LLDB_INVALID_PROCESS_ID, LLDB_LOGF, m_current_process, StringExtractor::Peek(), lldb_private::Process, lldb_private::Stream::PutBytesAsRawHex8(), lldb_private::Stream::PutChar(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), and StringExtractor::SetFilePos().
Referenced by RegisterPacketHandlers().
Handle_QNonStop()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_QNonStop (StringExtractorGDBRemote & packet) protected
Definition at line 4038 of file GDBRemoteCommunicationServerLLGS.cpp.
References error(), lldb_private::Status::FromErrorString(), lldb_private::GetLog(), StringExtractor::GetStringRef(), LLDB_LOG, m_debugged_processes, m_disabling_non_stop, m_non_stop, m_stdio_notification_queue, m_stop_notification_queue, lldb_private::Process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), StartSTDIOForwarding(), StopSTDIOForwarding(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by RegisterPacketHandlers().
Handle_QPassSignals()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_QPassSignals (StringExtractorGDBRemote & packet) protected
Definition at line 3799 of file GDBRemoteCommunicationServerLLGS.cpp.
References error(), StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), StringExtractor::GetS32(), m_current_process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), StringExtractor::SetFilePos(), and StringExtractor::SkipSpaces().
Referenced by RegisterPacketHandlers().
Handle_qProcessInfo()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_qProcessInfo (StringExtractorGDBRemote & packet) protected
Definition at line 1471 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse_DebugServerStyle(), lldb_private::Host::GetProcessInfo(), lldb_private::StreamString::GetString(), LLDB_INVALID_PROCESS_ID, m_current_process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock().
Referenced by RegisterPacketHandlers().
Handle_qRegisterInfo()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_qRegisterInfo (StringExtractorGDBRemote & packet) protected
Definition at line 2072 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::RegisterInfo::alt_name, lldb_private::RegisterInfo::byte_offset, lldb_private::RegisterInfo::byte_size, CollectRegNums(), lldb::eRegisterKindDWARF, lldb::eRegisterKindEHFrame, GetEncodingNameOrEmpty(), GetFormatNameOrEmpty(), StringExtractor::GetHexMaxU32(), GetKindGenericOrEmpty(), lldb_private::NativeRegisterContext::GetRegisterInfoAtIndex(), lldb_private::NativeRegisterContext::GetRegisterSetNameForRegisterAtIndex(), lldb_private::StreamString::GetString(), lldb_private::NativeRegisterContext::GetUserRegisterCount(), lldb_private::RegisterInfo::invalidate_regs, lldb_private::RegisterInfo::kinds, LLDB_INVALID_PROCESS_ID, LLDB_INVALID_REGNUM, m_current_process, lldb_private::RegisterInfo::name, lldb_private::Stream::Printf(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), lldb_private::NativeRegisterContext::RegisterOffsetIsDynamic(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), StringExtractor::SetFilePos(), and lldb_private::RegisterInfo::value_regs.
Referenced by RegisterPacketHandlers().
Handle_QRestoreRegisterState()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_QRestoreRegisterState (StringExtractorGDBRemote & packet) protected
Definition at line 3436 of file GDBRemoteCommunicationServerLLGS.cpp.
References error(), StringExtractor::GetBytesLeft(), lldb_private::GetLog(), GetThreadFromSuffix(), StringExtractor::GetU32(), LLDB_LOG, m_current_process, m_saved_registers_map, m_saved_registers_mutex, m_thread_suffix_supported, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), StringExtractor::SetFilePos(), lldb_private::Thread, and lldb_private::NativeRegisterContext::WriteAllRegisterValues().
Referenced by RegisterPacketHandlers().
Handle_qSaveCore()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_qSaveCore (StringExtractorGDBRemote & packet) protected
Definition at line 4006 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::Status::FromErrorString(), StringExtractor::GetHexByteString(), lldb_private::StreamString::GetString(), StringExtractor::GetStringRef(), LLDB_INVALID_PROCESS_ID, m_current_process, lldb_private::Stream::PutCString(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock().
Referenced by RegisterPacketHandlers().
Handle_QSaveRegisterState()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_QSaveRegisterState (StringExtractorGDBRemote & packet) protected
Definition at line 3388 of file GDBRemoteCommunicationServerLLGS.cpp.
References error(), lldb_private::GetLog(), GetNextSavedRegistersID(), lldb_private::StreamString::GetString(), GetThreadFromSuffix(), LLDB_LOG, m_current_process, m_saved_registers_map, m_saved_registers_mutex, m_thread_suffix_supported, lldb_private::Stream::Printf(), lldb_private::NativeRegisterContext::ReadAllRegisterValues(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), StringExtractor::SetFilePos(), and lldb_private::Thread.
Referenced by RegisterPacketHandlers().
Handle_QSetDisableASLR()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_QSetDisableASLR (StringExtractorGDBRemote & packet) protected
Definition at line 1570 of file GDBRemoteCommunicationServerLLGS.cpp.
References StringExtractor::GetU32(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::m_process_launch_info, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), and StringExtractor::SetFilePos().
Referenced by RegisterPacketHandlers().
Handle_QSetWorkingDir()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_QSetWorkingDir (StringExtractorGDBRemote & packet) protected
Definition at line 1581 of file GDBRemoteCommunicationServerLLGS.cpp.
References StringExtractor::GetHexByteString(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::m_process_launch_info, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), and StringExtractor::SetFilePos().
Referenced by RegisterPacketHandlers().
Handle_qsThreadInfo()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_qsThreadInfo (StringExtractorGDBRemote & packet) protected
Definition at line 2198 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock().
Referenced by RegisterPacketHandlers().
Handle_qStructuredDataPlugins()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_qStructuredDataPlugins (StringExtractorGDBRemote & packet) protected
Definition at line 1456 of file GDBRemoteCommunicationServerLLGS.cpp.
References LLDB_INVALID_PROCESS_ID, m_current_process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendJSONResponse().
Referenced by RegisterPacketHandlers().
Handle_qThreadStopInfo()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_qThreadStopInfo (StringExtractorGDBRemote & packet) protected
Definition at line 3695 of file GDBRemoteCommunicationServerLLGS.cpp.
References StringExtractor::GetHexMaxU64(), lldb_private::GetLog(), StringExtractor::GetStringRef(), LLDB_INVALID_PROCESS_ID, LLDB_INVALID_THREAD_ID, LLDB_LOGF, m_current_process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), SendStopReplyPacketForThread(), StringExtractor::SetFilePos(), and lldb_private::Thread.
Referenced by RegisterPacketHandlers().
Handle_QThreadSuffixSupported()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_QThreadSuffixSupported (StringExtractorGDBRemote & packet) protected
Definition at line 1604 of file GDBRemoteCommunicationServerLLGS.cpp.
References m_thread_suffix_supported, and lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse().
Referenced by RegisterPacketHandlers().
Handle_qVAttachOrWaitSupported()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_qVAttachOrWaitSupported (StringExtractorGDBRemote & packet) protected
Definition at line 3569 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse().
Referenced by RegisterPacketHandlers().
Handle_qWatchpointSupportInfo()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_qWatchpointSupportInfo (StringExtractorGDBRemote & packet) protected
Definition at line 3745 of file GDBRemoteCommunicationServerLLGS.cpp.
References StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), lldb_private::StreamString::GetString(), LLDB_INVALID_PROCESS_ID, m_current_process, lldb_private::Stream::Printf(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), and StringExtractor::SetFilePos().
Referenced by RegisterPacketHandlers().
Handle_qXfer()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_qXfer (StringExtractorGDBRemote & packet) protected
Definition at line 3315 of file GDBRemoteCommunicationServerLLGS.cpp.
References StringExtractor::GetChar(), StringExtractor::GetHexMaxU64(), lldb_private::StreamString::GetString(), StringExtractor::GetStringRef(), m_xfer_buffer_map, lldb_private::Stream::PutChar(), lldb_private::StreamGDBRemote::PutEscapedBytes(), ReadXferObject(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendUnimplementedResponse().
Referenced by RegisterPacketHandlers().
Handle_s()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_s (StringExtractorGDBRemote & packet) protected
Definition at line 3097 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::ResumeActionList::Append(), lldb::eStateStepping, lldb::eStateStopped, GetContinueThreadID(), GetCurrentThreadID(), lldb_private::GetLog(), LLDB_INVALID_PROCESS_ID, LLDB_INVALID_SIGNAL_NUMBER, LLDB_INVALID_THREAD_ID, LLDB_LOGF, m_continue_process, lldb_private::Process, ResumeProcess(), SendContinueSuccessResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::ResumeActionList::SetDefaultThreadActionIfNeeded(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and lldb_private::Thread.
Referenced by Handle_vCont(), and RegisterPacketHandlers().
Handle_stop_reason()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_stop_reason (StringExtractorGDBRemote & packet) protected
Definition at line 1975 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::StreamString::Empty(), EnqueueStopReplyPackets(), lldb_private::StreamString::GetString(), LLDB_INVALID_THREAD_ID, m_current_process, m_non_stop, m_stop_notification_queue, PrepareStopReplyPacketForThread(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), and SendStopReasonForState().
Referenced by RegisterPacketHandlers().
Handle_T()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_T (StringExtractorGDBRemote & packet) protected
Definition at line 4131 of file GDBRemoteCommunicationServerLLGS.cpp.
References StringExtractorGDBRemote::GetPidTid(), LLDB_INVALID_PROCESS_ID, m_current_process, m_debugged_processes, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), and StringExtractor::SetFilePos().
Referenced by RegisterPacketHandlers().
Handle_vAttach()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_vAttach (StringExtractorGDBRemote & packet) protected
Definition at line 3497 of file GDBRemoteCommunicationServerLLGS.cpp.
References AttachToProcess(), error(), StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), lldb_private::GetLog(), StringExtractor::GetU32(), LLDB_INVALID_PROCESS_ID, LLDB_LOGF, m_current_process, lldb_private::Process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), SendStopReasonForState(), and StringExtractor::SetFilePos().
Referenced by RegisterPacketHandlers().
Handle_vAttachOrWait()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_vAttachOrWait (StringExtractorGDBRemote & packet) protected
Definition at line 3575 of file GDBRemoteCommunicationServerLLGS.cpp.
References AttachWaitProcess(), error(), StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), StringExtractor::GetHexByteString(), lldb_private::GetLog(), LLDB_LOG, m_current_process, lldb_private::Process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), SendStopReasonForState(), and StringExtractor::SetFilePos().
Referenced by RegisterPacketHandlers().
Handle_vAttachWait()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_vAttachWait (StringExtractorGDBRemote & packet) protected
Definition at line 3536 of file GDBRemoteCommunicationServerLLGS.cpp.
References AttachWaitProcess(), error(), StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), StringExtractor::GetHexByteString(), lldb_private::GetLog(), LLDB_LOG, m_current_process, lldb_private::Process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), SendStopReasonForState(), and StringExtractor::SetFilePos().
Referenced by RegisterPacketHandlers().
Handle_vCont()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_vCont (StringExtractorGDBRemote & packet) protected
Definition at line 1785 of file GDBRemoteCommunicationServerLLGS.cpp.
References StringExtractorGDBRemote::AllProcesses, StringExtractorGDBRemote::AllThreads, error(), lldb::eStateInvalid, lldb::eStateRunning, lldb::eStateStepping, lldb::eStateSuspended, StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), StringExtractor::GetFilePos(), StringExtractor::GetHexMaxU32(), lldb_private::GetLog(), StringExtractorGDBRemote::GetPidTid(), Handle_s(), LLDB_INVALID_PROCESS_ID, LLDB_INVALID_SIGNAL_NUMBER, LLDB_INVALID_THREAD_ID, LLDB_LOG, LLDB_LOGF, m_continue_process, m_debugged_processes, m_non_stop, StringExtractor::Peek(), lldb_private::Process, ResumeActionListStopsAllThreads(), ResumeProcess(), SendContinueSuccessResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), StringExtractor::SetFilePos(), lldb_private::ResumeAction::signal, lldb_private::ResumeAction::state, lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and lldb_private::ResumeAction::tid.
Referenced by RegisterPacketHandlers().
Handle_vCont_actions()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_vCont_actions (StringExtractorGDBRemote & packet) protected
Definition at line 1764 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::StreamString::GetString(), lldb_private::Stream::Printf(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock().
Referenced by RegisterPacketHandlers().
Handle_vCtrlC()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_vCtrlC (StringExtractorGDBRemote & packet) protected
Definition at line 4116 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::Status::FromErrorString(), Handle_interrupt(), m_non_stop, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by RegisterPacketHandlers().
Handle_vKill()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_vKill (StringExtractorGDBRemote & packet) protected
Definition at line 1545 of file GDBRemoteCommunicationServerLLGS.cpp.
References error(), StringExtractor::GetU32(), LLDB_INVALID_PROCESS_ID, m_debugged_processes, m_non_stop, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), StringExtractor::SetFilePos(), StopSTDIOForwarding(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::DebuggedProcess::vkilled.
Referenced by RegisterPacketHandlers().
Handle_vRun()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_vRun (StringExtractorGDBRemote & packet) protected
Definition at line 3608 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::Status::FromErrorString(), StringExtractor::GetHexByteString(), lldb_private::GetLog(), StringExtractor::GetStringRef(), LaunchProcess(), LLDB_LOGF, m_current_process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::m_process_launch_error, lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::m_process_launch_info, lldb_private::Process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), and SendStopReasonForState().
Referenced by RegisterPacketHandlers().
Handle_vStdio()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_vStdio (StringExtractorGDBRemote & packet) protected
Definition at line 4097 of file GDBRemoteCommunicationServerLLGS.cpp.
References HandleNotificationAck(), and m_stdio_notification_queue.
Referenced by RegisterPacketHandlers().
Handle_vStopped()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_vStopped (StringExtractorGDBRemote & packet) protected
Definition at line 4103 of file GDBRemoteCommunicationServerLLGS.cpp.
References HandleNotificationAck(), m_debugged_processes, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::m_exit_now, m_mainloop, and m_stop_notification_queue.
Referenced by RegisterPacketHandlers().
Handle_Z()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_Z (StringExtractorGDBRemote & packet) protected
Definition at line 2916 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::Breakpoints, lldb_private::process_gdb_remote::eBreakpointHardware, lldb_private::process_gdb_remote::eBreakpointSoftware, error(), lldb_private::process_gdb_remote::eStoppointInvalid, lldb_private::process_gdb_remote::eWatchpointRead, lldb_private::process_gdb_remote::eWatchpointReadWrite, lldb_private::process_gdb_remote::eWatchpointWrite, StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), StringExtractor::GetHexMaxU32(), StringExtractor::GetHexMaxU64(), lldb_private::GetLog(), StringExtractor::GetS32(), LLDB_INVALID_PROCESS_ID, LLDB_LOG, m_current_process, lldb_private::Process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), StringExtractor::SetFilePos(), and lldb_private::Watchpoints.
Referenced by RegisterPacketHandlers().
Handle_z()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::Handle_z (StringExtractorGDBRemote & packet) protected
Definition at line 3010 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::Breakpoints, lldb_private::process_gdb_remote::eBreakpointHardware, lldb_private::process_gdb_remote::eBreakpointSoftware, error(), lldb_private::process_gdb_remote::eStoppointInvalid, lldb_private::process_gdb_remote::eWatchpointRead, lldb_private::process_gdb_remote::eWatchpointReadWrite, lldb_private::process_gdb_remote::eWatchpointWrite, StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), StringExtractor::GetHexMaxU64(), lldb_private::GetLog(), StringExtractor::GetS32(), LLDB_INVALID_PROCESS_ID, LLDB_LOG, m_current_process, lldb_private::Process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), StringExtractor::SetFilePos(), and lldb_private::Watchpoints.
Referenced by RegisterPacketHandlers().
HandleFeatures()
std::vector< std::string > GDBRemoteCommunicationServerLLGS::HandleFeatures (const llvm::ArrayRef< llvm::StringRef > client_features) override protected virtual
Reimplemented from lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon.
Definition at line 4303 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::HandleFeatures(), m_debugged_processes, m_extensions_supported, m_process_manager, and SetEnabledExtensions().
HandleInferiorState_Exited()
void GDBRemoteCommunicationServerLLGS::HandleInferiorState_Exited (NativeProcessProtocol * process) private
Definition at line 1097 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb::eStateExited, lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), LLDB_LOGF, m_continue_process, m_current_process, m_debugged_processes, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::m_exit_now, m_mainloop, m_non_stop, MaybeCloseInferiorTerminalConnection(), lldb_private::Process, lldb_private::MainLoopBase::RequestTermination(), SendStopReasonForState(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::DebuggedProcess::vkilled.
Referenced by ProcessStateChanged().
HandleInferiorState_Stopped()
void GDBRemoteCommunicationServerLLGS::HandleInferiorState_Stopped (NativeProcessProtocol * process) private
Definition at line 1139 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb::eStateStopped, lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), LLDB_LOGF, lldb_private::Process, SendStopReasonForState(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by ProcessStateChanged().
HandleNotificationAck()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::HandleNotificationAck (std::deque< std::string > & queue) protected
Definition at line 4080 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::Status::FromErrorString(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock().
Referenced by Handle_vStdio(), and Handle_vStopped().
InitializeConnection()
Status GDBRemoteCommunicationServerLLGS::InitializeConnection (std::unique_ptr< Connection > connection)
Definition at line 1239 of file GDBRemoteCommunicationServerLLGS.cpp.
References DataAvailableCallback(), error(), m_mainloop, m_network_handle_up, and lldb_private::Communication::SetConnection().
InitializeDelegate()
void GDBRemoteCommunicationServerLLGS::InitializeDelegate (NativeProcessProtocol * process) override virtual
Implements lldb_private::NativeProcessProtocol::NativeDelegate.
Definition at line 464 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), lldb_private::NativeProcessProtocol::GetState(), LLDB_LOGF, lldb_private::Process, and lldb_private::StateAsCString().
LaunchProcess()
Status GDBRemoteCommunicationServerLLGS::LaunchProcess () override virtual
Launch a process with the current launch settings.
This method supports running an lldb-gdbserver or similar server in a situation where the startup code has been provided with all the information for a child process to be launched.
Returns
An Status object indicating the success or failure of the launch.
Implements lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon.
Definition at line 264 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::Status::FromError(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::GetLog(), m_continue_process, m_current_process, m_debugged_process_mutex, m_debugged_processes, lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::m_process_launch_info, m_process_manager, and lldb_private::Process.
Referenced by Handle_vRun().
MaybeCloseInferiorTerminalConnection()
void GDBRemoteCommunicationServerLLGS::MaybeCloseInferiorTerminalConnection () private
Definition at line 4160 of file GDBRemoteCommunicationServerLLGS.cpp.
References error(), lldb_private::GetLog(), LLDB_LOGF, m_stdio_communication, and lldb_private::Process.
Referenced by HandleInferiorState_Exited().
NewSubprocess()
void GDBRemoteCommunicationServerLLGS::NewSubprocess (NativeProcessProtocol * parent_process, std::unique_ptr< NativeProcessProtocol > child_process) override virtual
Implements lldb_private::NativeProcessProtocol::NativeDelegate.
Definition at line 1205 of file GDBRemoteCommunicationServerLLGS.cpp.
References LLDB_INVALID_PROCESS_ID, and m_debugged_processes.
operator=()
const GDBRemoteCommunicationServerLLGS & lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::operator= (const GDBRemoteCommunicationServerLLGS &) private delete
References GDBRemoteCommunicationServerLLGS().
PrepareStopReplyPacketForThread()
StreamString GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread (NativeThreadProtocol & thread) protected
Definition at line 858 of file GDBRemoteCommunicationServerLLGS.cpp.
References AppendThreadIDToResponse(), lldb_private::Stream::AsRawOstream(), lldb_private::ThreadStopInfo::child_pid, lldb_private::ThreadStopInfo::child_tid, lldb_private::NativeRegisterContext::ConvertRegisterKindToRegisterNumber(), lldb_private::ThreadStopInfo::data, lldb_private::ThreadStopInfo::data_count, lldb_private::ThreadStopInfo::details, lldb::eByteOrderBig, lldb::eRegisterKindGeneric, error(), lldb::eStopReasonException, lldb::eStopReasonFork, lldb::eStopReasonVFork, lldb_private::ThreadStopInfo::exception, lldb_private::NativeProcessProtocol::fork, lldb_private::ThreadStopInfo::fork, lldb_private::Full, lldb_private::StreamString::GetData(), lldb_private::NativeRegisterContext::GetExpeditedRegisters(), lldb_private::NativeProcessProtocol::GetID(), GetJSONThreadsInfo(), lldb_private::GetLog(), lldb_private::NativeRegisterContext::GetRegisterInfoAtIndex(), GetStopReasonString(), lldb_private::endian::InlHostByteOrder(), LLDB_LOG, LLDB_LOG_ERROR, LLDB_LOGF, LLDB_REGNUM_GENERIC_PC, m_current_process, m_extensions_supported, m_list_threads_in_stop_reply, lldb_private::NativeProcessProtocol::multiprocess, lldb_private::RegisterInfo::name, lldb_private::Stream::Printf(), lldb_private::Process, lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), lldb_private::Stream::PutHex32(), lldb_private::Stream::PutHex64(), lldb_private::Stream::PutHex8(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::NativeRegisterContext::ReadRegister(), lldb_private::ThreadStopInfo::reason, lldb_private::ThreadStopInfo::signo, lldb_private::Thread, lldb_private::NativeProcessProtocol::Threads(), lldb_private::ThreadStopInfo::type, lldb_private::RegisterInfo::value_regs, lldb_private::NativeProcessProtocol::vfork, and WriteRegisterValueInHexFixedWidth().
Referenced by EnqueueStopReplyPackets(), Handle_stop_reason(), and SendStopReplyPacketForThread().
ProcessStateChanged()
void GDBRemoteCommunicationServerLLGS::ProcessStateChanged (NativeProcessProtocol * process, lldb::StateType state) override virtual
Implements lldb_private::NativeProcessProtocol::NativeDelegate.
Definition at line 1156 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb::eStateExited, lldb::eStateRunning, lldb::eStateStopped, lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), HandleInferiorState_Exited(), HandleInferiorState_Stopped(), LLDB_LOGF, m_non_stop, lldb_private::Process, SendProcessOutput(), lldb_private::StateAsCString(), and StopSTDIOForwarding().
ReadXferObject()
llvm::Expected< std::unique_ptr< llvm::MemoryBuffer > > GDBRemoteCommunicationServerLLGS::ReadXferObject (llvm::StringRef object, llvm::StringRef annex) protected
Definition at line 3261 of file GDBRemoteCommunicationServerLLGS.cpp.
References BuildTargetXml(), lldb_private::StreamString::GetString(), LLDB_INVALID_PROCESS_ID, m_current_process, lldb_private::Stream::Printf(), and XMLEncodeAttributeValue().
Referenced by Handle_qXfer().
RegisterPacketHandlers()
void GDBRemoteCommunicationServerLLGS::RegisterPacketHandlers () private
Definition at line 79 of file GDBRemoteCommunicationServerLLGS.cpp.
References error(), StringExtractorGDBRemote::eServerPacketType__M, StringExtractorGDBRemote::eServerPacketType__m, StringExtractorGDBRemote::eServerPacketType_C, StringExtractorGDBRemote::eServerPacketType_c, StringExtractorGDBRemote::eServerPacketType_D, StringExtractorGDBRemote::eServerPacketType_g, StringExtractorGDBRemote::eServerPacketType_H, StringExtractorGDBRemote::eServerPacketType_I, StringExtractorGDBRemote::eServerPacketType_interrupt, StringExtractorGDBRemote::eServerPacketType_jLLDBTraceGetBinaryData, StringExtractorGDBRemote::eServerPacketType_jLLDBTraceGetState, StringExtractorGDBRemote::eServerPacketType_jLLDBTraceStart, StringExtractorGDBRemote::eServerPacketType_jLLDBTraceStop, StringExtractorGDBRemote::eServerPacketType_jLLDBTraceSupported, StringExtractorGDBRemote::eServerPacketType_jThreadsInfo, StringExtractorGDBRemote::eServerPacketType_k, StringExtractorGDBRemote::eServerPacketType_M, StringExtractorGDBRemote::eServerPacketType_m, StringExtractorGDBRemote::eServerPacketType_P, StringExtractorGDBRemote::eServerPacketType_p, StringExtractorGDBRemote::eServerPacketType_qC, StringExtractorGDBRemote::eServerPacketType_qFileLoadAddress, StringExtractorGDBRemote::eServerPacketType_qfThreadInfo, StringExtractorGDBRemote::eServerPacketType_qGetWorkingDir, StringExtractorGDBRemote::eServerPacketType_QListThreadsInStopReply, StringExtractorGDBRemote::eServerPacketType_qLLDBSaveCore, StringExtractorGDBRemote::eServerPacketType_qMemoryRegionInfo, StringExtractorGDBRemote::eServerPacketType_qMemoryRegionInfoSupported, StringExtractorGDBRemote::eServerPacketType_QMemTags, StringExtractorGDBRemote::eServerPacketType_qMemTags, StringExtractorGDBRemote::eServerPacketType_QNonStop, StringExtractorGDBRemote::eServerPacketType_QPassSignals, StringExtractorGDBRemote::eServerPacketType_qProcessInfo, StringExtractorGDBRemote::eServerPacketType_qRegisterInfo, StringExtractorGDBRemote::eServerPacketType_QRestoreRegisterState, StringExtractorGDBRemote::eServerPacketType_QSaveRegisterState, StringExtractorGDBRemote::eServerPacketType_QSetDisableASLR, StringExtractorGDBRemote::eServerPacketType_QSetWorkingDir, StringExtractorGDBRemote::eServerPacketType_qsThreadInfo, StringExtractorGDBRemote::eServerPacketType_qStructuredDataPlugins, StringExtractorGDBRemote::eServerPacketType_qThreadStopInfo, StringExtractorGDBRemote::eServerPacketType_QThreadSuffixSupported, StringExtractorGDBRemote::eServerPacketType_qVAttachOrWaitSupported, StringExtractorGDBRemote::eServerPacketType_qWatchpointSupportInfo, StringExtractorGDBRemote::eServerPacketType_qXfer, StringExtractorGDBRemote::eServerPacketType_s, StringExtractorGDBRemote::eServerPacketType_stop_reason, StringExtractorGDBRemote::eServerPacketType_T, StringExtractorGDBRemote::eServerPacketType_vAttach, StringExtractorGDBRemote::eServerPacketType_vAttachOrWait, StringExtractorGDBRemote::eServerPacketType_vAttachWait, StringExtractorGDBRemote::eServerPacketType_vCont, StringExtractorGDBRemote::eServerPacketType_vCont_actions, StringExtractorGDBRemote::eServerPacketType_vCtrlC, StringExtractorGDBRemote::eServerPacketType_vKill, StringExtractorGDBRemote::eServerPacketType_vRun, StringExtractorGDBRemote::eServerPacketType_vStdio, StringExtractorGDBRemote::eServerPacketType_vStopped, StringExtractorGDBRemote::eServerPacketType_x, StringExtractorGDBRemote::eServerPacketType_Z, StringExtractorGDBRemote::eServerPacketType_z, Handle__M(), Handle__m(), Handle_C(), Handle_c(), Handle_D(), Handle_g(), Handle_H(), Handle_I(), Handle_interrupt(), Handle_jLLDBTraceGetBinaryData(), Handle_jLLDBTraceGetState(), Handle_jLLDBTraceStart(), Handle_jLLDBTraceStop(), Handle_jLLDBTraceSupported(), Handle_jThreadsInfo(), Handle_k(), Handle_M(), Handle_memory_read(), Handle_P(), Handle_p(), Handle_qC(), Handle_qFileLoadAddress(), Handle_qfThreadInfo(), Handle_qGetWorkingDir(), Handle_QListThreadsInStopReply(), Handle_qMemoryRegionInfo(), Handle_qMemoryRegionInfoSupported(), Handle_QMemTags(), Handle_qMemTags(), Handle_QNonStop(), Handle_QPassSignals(), Handle_qProcessInfo(), Handle_qRegisterInfo(), Handle_QRestoreRegisterState(), Handle_qSaveCore(), Handle_QSaveRegisterState(), Handle_QSetDisableASLR(), Handle_QSetWorkingDir(), Handle_qsThreadInfo(), Handle_qStructuredDataPlugins(), Handle_qThreadStopInfo(), Handle_QThreadSuffixSupported(), Handle_qVAttachOrWaitSupported(), Handle_qWatchpointSupportInfo(), Handle_qXfer(), Handle_s(), Handle_stop_reason(), Handle_T(), Handle_vAttach(), Handle_vAttachOrWait(), Handle_vAttachWait(), Handle_vCont(), Handle_vCont_actions(), Handle_vCtrlC(), Handle_vKill(), Handle_vRun(), Handle_vStdio(), Handle_vStopped(), Handle_Z(), Handle_z(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::RegisterMemberFunctionHandler(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::RegisterPacketHandler().
Referenced by GDBRemoteCommunicationServerLLGS().
ResumeProcess()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::ResumeProcess (NativeProcessProtocol & process, const ResumeActionList & actions) protected
Definition at line 1618 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::NativeProcessProtocol::CanResume(), error(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), lldb_private::NativeProcessProtocol::GetState(), LLDB_LOG, lldb_private::Process, lldb_private::NativeProcessProtocol::Resume(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and lldb_private::Thread.
Referenced by Handle_C(), Handle_c(), Handle_s(), and Handle_vCont().
SendContinueSuccessResponse()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::SendContinueSuccessResponse () protected
Definition at line 4371 of file GDBRemoteCommunicationServerLLGS.cpp.
References m_non_stop, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), StartSTDIOForwarding(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by Handle_C(), Handle_c(), Handle_k(), Handle_s(), and Handle_vCont().
SendONotification()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::SendONotification (const char * buffer, uint32_t len) protected
Definition at line 1265 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::StreamString::GetString(), m_non_stop, m_stdio_notification_queue, lldb_private::Stream::PutBytesAsRawHex8(), lldb_private::Stream::PutChar(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendNotificationPacketNoLock(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by SendProcessOutput().
SendProcessOutput()
void GDBRemoteCommunicationServerLLGS::SendProcessOutput () private
Definition at line 1328 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb::eConnectionStatusEndOfFile, lldb::eConnectionStatusError, lldb::eConnectionStatusInterrupted, lldb::eConnectionStatusLostConnection, lldb::eConnectionStatusNoConnection, lldb::eConnectionStatusSuccess, lldb::eConnectionStatusTimedOut, error(), lldb_private::GetLog(), LLDB_LOGF, m_stdio_communication, m_stdio_handle_up, lldb_private::Process, and SendONotification().
Referenced by ProcessStateChanged().
SendStopReasonForState()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::SendStopReasonForState (NativeProcessProtocol & process, lldb::StateType process_state, bool force_synchronous) protected
Definition at line 2018 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb::eStateAttaching, lldb::eStateCrashed, lldb::eStateDetached, lldb::eStateExited, lldb::eStateInvalid, lldb::eStateLaunching, lldb::eStateRunning, lldb::eStateStepping, lldb::eStateStopped, lldb::eStateSuspended, lldb::eStateUnloaded, lldb_private::NativeProcessProtocol::GetCurrentThreadID(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), LLDB_LOG, m_debugged_processes, m_disabling_non_stop, lldb_private::Process, lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), SendStopReplyPacketForThread(), SendWResponse(), SetCurrentThreadID(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by Handle_stop_reason(), Handle_vAttach(), Handle_vAttachOrWait(), Handle_vAttachWait(), Handle_vRun(), HandleInferiorState_Exited(), and HandleInferiorState_Stopped().
SendStopReplyPacketForThread()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::SendStopReplyPacketForThread (NativeProcessProtocol & process, lldb::tid_t tid, bool force_synchronous) protected
Definition at line 1061 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::StreamString::Empty(), EnqueueStopReplyPackets(), lldb_private::StreamString::GetString(), lldb_private::NativeProcessProtocol::GetThreadByID(), m_non_stop, m_stop_notification_queue, PrepareStopReplyPacketForThread(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendNotificationPacketNoLock(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock().
Referenced by Handle_qThreadStopInfo(), and SendStopReasonForState().
SendStructuredDataPacket()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::SendStructuredDataPacket (const llvm::json::Value & value)
Definition at line 1252 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::StreamString::GetString(), lldb_private::Stream::PutCString(), lldb_private::StreamGDBRemote::PutEscapedBytes(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock().
SendWResponse()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationServerLLGS::SendWResponse (NativeProcessProtocol * process) protected
Definition at line 478 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::Stream::Format(), lldb_private::NativeProcessProtocol::GetExitStatus(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), lldb_private::StreamString::GetString(), LLDB_LOG, m_debugged_processes, m_extensions_supported, m_non_stop, m_stop_notification_queue, lldb_private::NativeProcessProtocol::multiprocess, lldb_private::Process, lldb_private::Stream::PutChar(), lldb_private::Stream::PutHex8(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendNotificationPacketNoLock(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendOKResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::DebuggedProcess::vkilled.
Referenced by SendStopReasonForState().
SetContinueThreadID()
void GDBRemoteCommunicationServerLLGS::SetContinueThreadID (lldb::tid_t tid) protected
Definition at line 1967 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::GetLog(), LLDB_LOG, m_continue_tid, and lldb_private::Thread.
Referenced by Handle_H().
SetCurrentThreadID()
void GDBRemoteCommunicationServerLLGS::SetCurrentThreadID (lldb::tid_t tid) protected
Definition at line 1958 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::GetLog(), LLDB_LOG, m_current_process, m_current_tid, and lldb_private::Thread.
Referenced by Handle_H(), Handle_qC(), and SendStopReasonForState().
SetEnabledExtensions()
void GDBRemoteCommunicationServerLLGS::SetEnabledExtensions (NativeProcessProtocol & process) private
Definition at line 4363 of file GDBRemoteCommunicationServerLLGS.cpp.
References m_extensions_supported, m_process_manager, and lldb_private::NativeProcessProtocol::SetEnabledExtensions().
Referenced by HandleFeatures().
SetLaunchInfo()
void GDBRemoteCommunicationServerLLGS::SetLaunchInfo (const ProcessLaunchInfo & info)
Definition at line 260 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::m_process_launch_info.
SetSTDIOFileDescriptor()
Status GDBRemoteCommunicationServerLLGS::SetSTDIOFileDescriptor (int fd) protected
Definition at line 1282 of file GDBRemoteCommunicationServerLLGS.cpp.
References error(), lldb_private::Status::FromErrorString(), m_stdio_communication, and lldb_private::Status.
StartSTDIOForwarding()
void GDBRemoteCommunicationServerLLGS::StartSTDIOForwarding () private
Definition at line 1305 of file GDBRemoteCommunicationServerLLGS.cpp.
References error(), lldb_private::GetLog(), LLDB_LOG, m_mainloop, m_stdio_communication, m_stdio_handle_up, and lldb_private::Process.
Referenced by Handle_QNonStop(), and SendContinueSuccessResponse().
StopSTDIOForwarding()
void GDBRemoteCommunicationServerLLGS::StopSTDIOForwarding () private
Definition at line 1324 of file GDBRemoteCommunicationServerLLGS.cpp.
References m_stdio_handle_up.
Referenced by Handle_D(), Handle_k(), Handle_QNonStop(), Handle_vKill(), and ProcessStateChanged().
XMLEncodeAttributeValue()
std::string GDBRemoteCommunicationServerLLGS::XMLEncodeAttributeValue (llvm::StringRef value) static protected
Definition at line 4278 of file GDBRemoteCommunicationServerLLGS.cpp.
Referenced by ReadXferObject().
Member Data Documentation
m_continue_process
NativeProcessProtocol* lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_continue_process protected
Definition at line 110 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by AttachToProcess(), GDBRemoteCommunicationServerLLGS(), Handle_C(), Handle_c(), Handle_D(), Handle_H(), Handle_s(), Handle_vCont(), HandleInferiorState_Exited(), and LaunchProcess().
m_continue_tid
lldb::tid_t lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_continue_tid = LLDB_INVALID_THREAD_ID protected
Definition at line 108 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by GetContinueThreadID(), and SetContinueThreadID().
m_current_process
NativeProcessProtocol* lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_current_process protected
Definition at line 109 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by AttachToProcess(), BuildTargetXml(), EnqueueStopReplyPackets(), FindModuleFile(), GDBRemoteCommunicationServerLLGS(), GetCurrentThreadID(), GetThreadFromSuffix(), Handle__M(), Handle__m(), Handle_D(), Handle_H(), Handle_I(), Handle_interrupt(), Handle_jLLDBTraceGetBinaryData(), Handle_jLLDBTraceGetState(), Handle_jLLDBTraceStart(), Handle_jLLDBTraceStop(), Handle_jLLDBTraceSupported(), Handle_jThreadsInfo(), Handle_M(), Handle_memory_read(), Handle_P(), Handle_qC(), Handle_qFileLoadAddress(), Handle_qMemoryRegionInfo(), Handle_qMemoryRegionInfoSupported(), Handle_QMemTags(), Handle_qMemTags(), Handle_QPassSignals(), Handle_qProcessInfo(), Handle_qRegisterInfo(), Handle_QRestoreRegisterState(), Handle_qSaveCore(), Handle_QSaveRegisterState(), Handle_qStructuredDataPlugins(), Handle_qThreadStopInfo(), Handle_qWatchpointSupportInfo(), Handle_stop_reason(), Handle_T(), Handle_vAttach(), Handle_vAttachOrWait(), Handle_vAttachWait(), Handle_vRun(), Handle_Z(), Handle_z(), HandleInferiorState_Exited(), LaunchProcess(), PrepareStopReplyPacketForThread(), ReadXferObject(), and SetCurrentThreadID().
m_current_tid
lldb::tid_t lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_current_tid = LLDB_INVALID_THREAD_ID protected
Definition at line 107 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by GetCurrentThreadID(), and SetCurrentThreadID().
m_debugged_process_mutex
std::recursive_mutex lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_debugged_process_mutex protected
Definition at line 111 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by LaunchProcess().
m_debugged_processes
std::unordered_map<lldb::pid_t, DebuggedProcess> lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_debugged_processes protected
Definition at line 112 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by AttachToProcess(), Handle_D(), Handle_H(), Handle_k(), Handle_qfThreadInfo(), Handle_QNonStop(), Handle_T(), Handle_vCont(), Handle_vKill(), Handle_vStopped(), HandleFeatures(), HandleInferiorState_Exited(), LaunchProcess(), NewSubprocess(), SendStopReasonForState(), and SendWResponse().
m_disabling_non_stop
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_disabling_non_stop = false protected
Definition at line 124 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by Handle_QNonStop(), and SendStopReasonForState().
m_extensions_supported
NativeProcessProtocol::Extension lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_extensions_supported = {} protected
Definition at line 128 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by AppendThreadIDToResponse(), Handle_qfThreadInfo(), HandleFeatures(), PrepareStopReplyPacketForThread(), SendWResponse(), and SetEnabledExtensions().
m_list_threads_in_stop_reply
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_list_threads_in_stop_reply = false protected
Definition at line 122 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by Handle_QListThreadsInStopReply(), and PrepareStopReplyPacketForThread().
m_mainloop
MainLoop& lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_mainloop protected
Definition at line 104 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by DataAvailableCallback(), GDBRemoteCommunicationServerLLGS(), Handle_vStopped(), HandleInferiorState_Exited(), InitializeConnection(), and StartSTDIOForwarding().
m_network_handle_up
MainLoop::ReadHandleUP lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_network_handle_up protected
Definition at line 105 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by InitializeConnection().
m_next_saved_registers_id
uint32_t lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_next_saved_registers_id = 1 protected
Definition at line 120 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by GetNextSavedRegistersID().
m_non_stop
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_non_stop = false protected
Definition at line 123 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by EnqueueStopReplyPackets(), Handle_D(), Handle_k(), Handle_QNonStop(), Handle_stop_reason(), Handle_vCont(), Handle_vCtrlC(), Handle_vKill(), HandleInferiorState_Exited(), ProcessStateChanged(), SendContinueSuccessResponse(), SendONotification(), SendStopReplyPacketForThread(), and SendWResponse().
m_process_manager
NativeProcessProtocol::Manager& lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_process_manager protected
Definition at line 106 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by AttachToProcess(), GDBRemoteCommunicationServerLLGS(), HandleFeatures(), LaunchProcess(), and SetEnabledExtensions().
m_reg_bytes
uint8_t lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_reg_bytes[RegisterValue::kMaxRegisterByteSize] protected
Definition at line 133 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by Handle_P().
m_saved_registers_map
std::unordered_map<uint32_t, lldb::DataBufferSP> lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_saved_registers_map protected
Definition at line 119 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by Handle_QRestoreRegisterState(), and Handle_QSaveRegisterState().
m_saved_registers_mutex
std::mutex lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_saved_registers_mutex protected
Definition at line 118 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by GetNextSavedRegistersID(), Handle_QRestoreRegisterState(), and Handle_QSaveRegisterState().
m_stdio_communication
Communication lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_stdio_communication protected
Definition at line 114 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by GDBRemoteCommunicationServerLLGS(), Handle_I(), MaybeCloseInferiorTerminalConnection(), SendProcessOutput(), SetSTDIOFileDescriptor(), and StartSTDIOForwarding().
m_stdio_handle_up
MainLoop::ReadHandleUP lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_stdio_handle_up protected
Definition at line 115 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by SendProcessOutput(), StartSTDIOForwarding(), and StopSTDIOForwarding().
m_stdio_notification_queue
std::deque<std::string> lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_stdio_notification_queue protected
Definition at line 125 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by Handle_QNonStop(), Handle_vStdio(), and SendONotification().
m_stop_notification_queue
std::deque<std::string> lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_stop_notification_queue protected
Definition at line 126 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by EnqueueStopReplyPackets(), Handle_QNonStop(), Handle_stop_reason(), Handle_vStopped(), SendStopReplyPacketForThread(), and SendWResponse().
m_thread_suffix_supported
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_thread_suffix_supported = false protected
Definition at line 121 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by GetThreadFromSuffix(), Handle_QRestoreRegisterState(), Handle_QSaveRegisterState(), and Handle_QThreadSuffixSupported().
m_xfer_buffer_map
llvm::StringMap<std::unique_ptr<llvm::MemoryBuffer> > lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::m_xfer_buffer_map protected
Definition at line 117 of file GDBRemoteCommunicationServerLLGS.h.
Referenced by ClearProcessSpecificData(), and Handle_qXfer().
The documentation for this class was generated from the following files:
GDBRemoteCommunicationServerLLGS.h
GDBRemoteCommunicationServerLLGS.cpp