LLDB: lldb_private::ExpressionVariableList Class Reference
lldb_private::ExpressionVariableList Class Reference
"lldb/Expression/ExpressionVariable.h" A list of variable references.
#include <ExpressionVariable.h>
Public Member Functions
size_t GetSize ()
Implementation of methods in ExpressionVariableListBase.
lldb::ExpressionVariableSP GetVariableAtIndex (size_t index)
size_t AddVariable (const lldb::ExpressionVariableSP &var_sp)
lldb::ExpressionVariableSP AddNewlyConstructedVariable (ExpressionVariable *var)
bool ContainsVariable (const lldb::ExpressionVariableSP &var_sp)
lldb::ExpressionVariableSP GetVariable (ConstString name)
Finds a variable by name in the list.
lldb::ExpressionVariableSP GetVariable (llvm::StringRef name)
void RemoveVariable (lldb::ExpressionVariableSP var_sp)
void Clear ()
Private Attributes
std::vector< lldb::ExpressionVariableSP > m_variables
Detailed Description
"lldb/Expression/ExpressionVariable.h" A list of variable references.
This class stores variables internally, acting as the permanent store.
Definition at line 129 of file ExpressionVariable.h.
Member Function Documentation
AddNewlyConstructedVariable()
lldb::ExpressionVariableSP lldb_private::ExpressionVariableList::AddNewlyConstructedVariable (ExpressionVariable * var) inline
Definition at line 147 of file ExpressionVariable.h.
References m_variables.
AddVariable()
size_t lldb_private::ExpressionVariableList::AddVariable (const lldb::ExpressionVariableSP & var_sp) inline
Definition at line 141 of file ExpressionVariable.h.
References m_variables.
Clear()
void lldb_private::ExpressionVariableList::Clear () inline
Definition at line 206 of file ExpressionVariable.h.
References m_variables.
ContainsVariable()
bool lldb_private::ExpressionVariableList::ContainsVariable (const lldb::ExpressionVariableSP & var_sp) inline
Definition at line 153 of file ExpressionVariable.h.
References m_variables.
GetSize()
size_t lldb_private::ExpressionVariableList::GetSize () inline
Implementation of methods in ExpressionVariableListBase.
Definition at line 132 of file ExpressionVariable.h.
References m_variables.
Referenced by lldb_private::ClangExpressionVariable::FindVariableInList(), GetVariable(), GetVariable(), and lldb_private::REPL::IOHandlerInputComplete().
GetVariable() [1/2]
lldb::ExpressionVariableSP lldb_private::ExpressionVariableList::GetVariable (ConstString name) inline
Finds a variable by name in the list.
Parameters
[in] name The name of the requested variable.
Returns
The variable requested, or nullptr if that variable is not in the list.
Definition at line 170 of file ExpressionVariable.h.
References GetSize(), and GetVariableAtIndex().
GetVariable() [2/2]
lldb::ExpressionVariableSP lldb_private::ExpressionVariableList::GetVariable (llvm::StringRef name) inline
Definition at line 181 of file ExpressionVariable.h.
References GetSize(), and GetVariableAtIndex().
GetVariableAtIndex()
lldb::ExpressionVariableSP lldb_private::ExpressionVariableList::GetVariableAtIndex (size_t index) inline
Definition at line 134 of file ExpressionVariable.h.
References m_variables.
Referenced by lldb_private::ClangExpressionVariable::FindVariableInList(), GetVariable(), GetVariable(), and lldb_private::REPL::IOHandlerInputComplete().
RemoveVariable()
void lldb_private::ExpressionVariableList::RemoveVariable (lldb::ExpressionVariableSP var_sp) inline
Definition at line 194 of file ExpressionVariable.h.
References m_variables.
Member Data Documentation
m_variables
std::vector<lldb::ExpressionVariableSP> lldb_private::ExpressionVariableList::m_variables private
Definition at line 209 of file ExpressionVariable.h.
Referenced by AddNewlyConstructedVariable(), AddVariable(), Clear(), ContainsVariable(), GetSize(), GetVariableAtIndex(), and RemoveVariable().
The documentation for this class was generated from the following file:
ExpressionVariable.h