LLDB: lldb_private::SymbolLocator Class Reference
lldb_private::SymbolLocator Class Reference
#include <SymbolLocator.h>
Public Member Functions
SymbolLocator ()=default
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
virtual llvm::StringRef GetPluginName ()=0
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void DownloadSymbolFileAsync (const UUID &uuid)
Locate the symbol file for the given UUID on a background thread.
Detailed Description
Definition at line 17 of file SymbolLocator.h.
Constructor & Destructor Documentation
SymbolLocator()
lldb_private::SymbolLocator::SymbolLocator () default
Referenced by lldb_private::SymbolLocatorDebuginfod::CreateInstance(), lldb_private::SymbolLocatorDebugSymbols::CreateInstance(), lldb_private::SymbolLocatorDefault::CreateInstance(), lldb_private::SymbolLocatorDebuginfod::SymbolLocatorDebuginfod(), lldb_private::SymbolLocatorDebugSymbols::SymbolLocatorDebugSymbols(), and lldb_private::SymbolLocatorDefault::SymbolLocatorDefault().
Member Function Documentation
DownloadSymbolFileAsync()
void SymbolLocator::DownloadSymbolFileAsync (const UUID & uuid) static
Locate the symbol file for the given UUID on a background thread.
This function returns immediately. Under the hood it uses the debugger's thread pool to call DownloadObjectAndSymbolFile. If a symbol file is found, this will notify all target which contain the module with the given UUID.
Definition at line 21 of file SymbolLocator.cpp.
References lldb_private::PluginManager::DownloadObjectAndSymbolFile(), error(), lldb::eSymbolDownloadBackground, lldb::eSymbolDownloadForeground, lldb::eSymbolDownloadOff, lldb_private::ModuleList::GetGlobalModuleListProperties(), lldb_private::Debugger::GetThreadPool(), lldb_private::ModuleSpec::GetUUID(), and lldb_private::Debugger::ReportSymbolChange().
Referenced by lldb_private::Module::GetUnwindTable().
The documentation for this class was generated from the following files:
SymbolLocator.h
SymbolLocator.cpp