LLDB: ObjectFileMinidump Class Reference
ObjectFileMinidump Class Reference
#include <ObjectFileMinidump.h>
Public Member Functions
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static const char * GetPluginDescriptionStatic ()
static lldb_private::ObjectFile * CreateInstance (const lldb::ModuleSP &module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const lldb_private::FileSpec *file, lldb::offset_t offset, lldb::offset_t length)
static lldb_private::ObjectFile * CreateMemoryInstance (const lldb::ModuleSP &module_sp, lldb::WritableDataBufferSP data_sp, const lldb::ProcessSP &process_sp, lldb::addr_t header_addr)
static size_t GetModuleSpecifications (const lldb_private::FileSpec &file, lldb::DataExtractorSP &extractor_sp, lldb::offset_t data_offset, lldb::offset_t file_offset, lldb::offset_t length, lldb_private::ModuleSpecList &specs)
static bool SaveCore (const lldb::ProcessSP &process_sp, lldb_private::SaveCoreOptions &options, lldb_private::Status &error)
Private Member Functions
ObjectFileMinidump ()=default
Detailed Description
Definition at line 27 of file ObjectFileMinidump.h.
Constructor & Destructor Documentation
ObjectFileMinidump()
ObjectFileMinidump::ObjectFileMinidump () private default
Referenced by Initialize().
Member Function Documentation
CreateInstance()
ObjectFile * ObjectFileMinidump::CreateInstance (const lldb::ModuleSP & module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const lldb_private::FileSpec * file, lldb::offset_t offset, lldb::offset_t length) static
Definition at line 37 of file ObjectFileMinidump.cpp.
Referenced by Initialize(), and Terminate().
CreateMemoryInstance()
ObjectFile * ObjectFileMinidump::CreateMemoryInstance (const lldb::ModuleSP & module_sp, lldb::WritableDataBufferSP data_sp, const lldb::ProcessSP & process_sp, lldb::addr_t header_addr) static
Definition at line 44 of file ObjectFileMinidump.cpp.
Referenced by Initialize().
GetModuleSpecifications()
size_t ObjectFileMinidump::GetModuleSpecifications (const lldb_private::FileSpec & file, lldb::DataExtractorSP & extractor_sp, lldb::offset_t data_offset, lldb::offset_t file_offset, lldb::offset_t length, lldb_private::ModuleSpecList & specs) static
Definition at line 50 of file ObjectFileMinidump.cpp.
References lldb_private::ModuleSpecList::Clear().
Referenced by Initialize().
GetPluginDescriptionStatic()
const char * ObjectFileMinidump::GetPluginDescriptionStatic () inline static
Definition at line 34 of file ObjectFileMinidump.h.
Referenced by Initialize().
GetPluginName()
llvm::StringRef ObjectFileMinidump::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 39 of file ObjectFileMinidump.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef ObjectFileMinidump::GetPluginNameStatic () inline static
Definition at line 33 of file ObjectFileMinidump.h.
Referenced by GetPluginName(), and Initialize().
Initialize()
void ObjectFileMinidump::Initialize () static
Definition at line 27 of file ObjectFileMinidump.cpp.
References CreateInstance(), CreateMemoryInstance(), GetModuleSpecifications(), GetPluginDescriptionStatic(), GetPluginNameStatic(), Initialize(), ObjectFileMinidump(), lldb_private::PluginManager::RegisterPlugin(), and SaveCore().
Referenced by Initialize().
SaveCore()
bool ObjectFileMinidump::SaveCore (const lldb::ProcessSP & process_sp, lldb_private::SaveCoreOptions & options, lldb_private::Status & error) static
Definition at line 73 of file ObjectFileMinidump.cpp.
References MinidumpFileBuilder::AddExceptions(), MinidumpFileBuilder::AddHeaderAndCalculateDirectories(), MinidumpFileBuilder::AddLinuxFileStreams(), MinidumpFileBuilder::AddMemoryList(), MinidumpFileBuilder::AddMiscInfo(), MinidumpFileBuilder::AddModuleList(), MinidumpFileBuilder::AddSystemInfo(), MinidumpFileBuilder::AddThreadList(), MinidumpFileBuilder::DumpFile(), lldb_private::File::eOpenOptionCanCreate, lldb_private::File::eOpenOptionWriteOnly, error(), lldb::eSaveCoreStackOnly, lldb::eSaveCoreUnspecified, lldb_private::Status::FromError(), lldb_private::GetLog(), lldb_private::SaveCoreOptions::GetOutputFile(), lldb_private::SaveCoreOptions::GetStyle(), lldb_private::FileSystem::Instance(), LLDB_LOGF, lldb_private::Object, lldb_private::FileSystem::Open(), lldb_private::SaveCoreOptions::SetStyle(), and DumpFailRemoveHolder::SetSuccess().
Referenced by Initialize().
Terminate()
void ObjectFileMinidump::Terminate () static
Definition at line 33 of file ObjectFileMinidump.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
The documentation for this class was generated from the following files:
ObjectFileMinidump.h
ObjectFileMinidump.cpp