LLDB: RegisterContextLinux_x86_64 Class Reference
RegisterContextLinux_x86_64 Class Reference
#include <RegisterContextLinux_x86_64.h>
Public Member Functions
RegisterContextLinux_x86_64 (const lldb_private::ArchSpec &target_arch)
size_t GetGPRSize () const override
const lldb_private::RegisterInfo * GetRegisterInfo () const override
uint32_t GetRegisterCount () const override
uint32_t GetUserRegisterCount () const override
Public Member Functions inherited from lldb_private::RegisterContextLinux_x86
RegisterContextLinux_x86 (const ArchSpec &target_arch, RegisterInfo orig_ax_info)
const RegisterInfo & GetOrigAxInfo () const
Public Member Functions inherited from lldb_private::RegisterInfoInterface
RegisterInfoInterface (const lldb_private::ArchSpec &target_arch)
virtual ~RegisterInfoInterface ()=default
const lldb_private::ArchSpec & GetTargetArchitecture () const
Static Public Member Functions
static size_t GetGPRSizeStatic ()
Private Attributes
const lldb_private::RegisterInfo * m_register_info_p
uint32_t m_register_info_count
uint32_t m_user_register_count
Detailed Description
Definition at line 14 of file RegisterContextLinux_x86_64.h.
Constructor & Destructor Documentation
RegisterContextLinux_x86_64()
RegisterContextLinux_x86_64::RegisterContextLinux_x86_64 (const lldb_private::ArchSpec & target_arch)
Definition at line 153 of file RegisterContextLinux_x86_64.cpp.
References lldb::eEncodingUint, lldb::eFormatHex, LLDB_INVALID_REGNUM, and lldb_private::RegisterContextLinux_x86::RegisterContextLinux_x86().
Member Function Documentation
GetGPRSize()
size_t RegisterContextLinux_x86_64::GetGPRSize () const inline override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 20 of file RegisterContextLinux_x86_64.h.
References GetGPRSizeStatic().
GetGPRSizeStatic()
size_t RegisterContextLinux_x86_64::GetGPRSizeStatic () static
Definition at line 172 of file RegisterContextLinux_x86_64.cpp.
Referenced by GetGPRSize().
GetRegisterCount()
uint32_t RegisterContextLinux_x86_64::GetRegisterCount () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 178 of file RegisterContextLinux_x86_64.cpp.
References m_register_info_count.
GetRegisterInfo()
const RegisterInfo * RegisterContextLinux_x86_64::GetRegisterInfo () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 174 of file RegisterContextLinux_x86_64.cpp.
References m_register_info_p.
GetUserRegisterCount()
uint32_t RegisterContextLinux_x86_64::GetUserRegisterCount () const override virtual
Reimplemented from lldb_private::RegisterInfoInterface.
Definition at line 182 of file RegisterContextLinux_x86_64.cpp.
References m_user_register_count.
Member Data Documentation
m_register_info_count
uint32_t RegisterContextLinux_x86_64::m_register_info_count private
Definition at line 30 of file RegisterContextLinux_x86_64.h.
Referenced by GetRegisterCount().
m_register_info_p
const lldb_private::RegisterInfo* RegisterContextLinux_x86_64::m_register_info_p private
Definition at line 29 of file RegisterContextLinux_x86_64.h.
Referenced by GetRegisterInfo().
m_user_register_count
uint32_t RegisterContextLinux_x86_64::m_user_register_count private
Definition at line 31 of file RegisterContextLinux_x86_64.h.
Referenced by GetUserRegisterCount().
The documentation for this class was generated from the following files:
RegisterContextLinux_x86_64.h
RegisterContextLinux_x86_64.cpp