LLDB: sddarwinlog_private::FilterRule Class Reference
sddarwinlog_private::FilterRule Class Reference abstract
Public Types
using OperationCreationFunc
Public Member Functions
virtual ~FilterRule ()=default
StructuredData::ObjectSP Serialize () const
virtual void Dump (Stream &stream) const =0
llvm::StringRef GetOperationType () const
Static Public Member Functions
static void RegisterOperation (llvm::StringRef operation, const OperationCreationFunc &creation_func)
static FilterRuleSP CreateRule (bool match_accepts, size_t attribute, llvm::StringRef operation, const std::string &op_arg, Status &error)
Protected Member Functions
FilterRule (bool accept, size_t attribute_index, llvm::StringRef operation)
virtual void DoSerialization (StructuredData::Dictionary &dict) const =0
bool GetMatchAccepts () const
const char * GetFilterAttribute () const
Private Types
using CreationFuncMap = llvm::StringMap<OperationCreationFunc>
Static Private Member Functions
static CreationFuncMap & GetCreationFuncMap ()
Private Attributes
const bool m_accept
const size_t m_attribute_index
const llvm::StringRef m_operation
Detailed Description
Definition at line 180 of file StructuredDataDarwinLog.cpp.
Member Typedef Documentation
CreationFuncMap
using sddarwinlog_private::FilterRule::CreationFuncMap = llvm::StringMap<OperationCreationFunc> private
Definition at line 247 of file StructuredDataDarwinLog.cpp.
OperationCreationFunc
using sddarwinlog_private::FilterRule::OperationCreationFunc
Initial value:
      std::function<FilterRuleSP(bool accept, size_t attribute_index,
                                 const std::string &op_arg, Status &error)>
Definition at line 184 of file StructuredDataDarwinLog.cpp.
Constructor & Destructor Documentation
~FilterRule()
virtual sddarwinlog_private::FilterRule::~FilterRule () virtual default
FilterRule()
sddarwinlog_private::FilterRule::FilterRule (bool accept, size_t attribute_index, llvm::StringRef operation) inline protected
Definition at line 234 of file StructuredDataDarwinLog.cpp.
References m_accept, m_attribute_index, and m_operation.
Referenced by sddarwinlog_private::ExactMatchFilterRule::ExactMatchFilterRule(), and sddarwinlog_private::RegexFilterRule::RegexFilterRule().
Member Function Documentation
CreateRule()
FilterRuleSP sddarwinlog_private::FilterRule::CreateRule (bool match_accepts, size_t attribute, llvm::StringRef operation, const std::string & op_arg, Status & error) inline static
Definition at line 193 of file StructuredDataDarwinLog.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormatv(), and GetCreationFuncMap().
Referenced by sddarwinlog_private::EnableOptions::ParseFilterRule().
DoSerialization()
virtual void sddarwinlog_private::FilterRule::DoSerialization (StructuredData::Dictionary & dict) const protected pure virtual
Implemented in sddarwinlog_private::ExactMatchFilterRule, and sddarwinlog_private::RegexFilterRule.
Referenced by Serialize().
Dump()
virtual void sddarwinlog_private::FilterRule::Dump (Stream & stream) const pure virtual
Implemented in sddarwinlog_private::ExactMatchFilterRule, and sddarwinlog_private::RegexFilterRule.
GetCreationFuncMap()
CreationFuncMap & sddarwinlog_private::FilterRule::GetCreationFuncMap () inline static private
Definition at line 249 of file StructuredDataDarwinLog.cpp.
Referenced by CreateRule(), and RegisterOperation().
GetFilterAttribute()
const char * sddarwinlog_private::FilterRule::GetFilterAttribute () const inline protected
Definition at line 242 of file StructuredDataDarwinLog.cpp.
References m_attribute_index, and sddarwinlog_private::s_filter_attributes.
Referenced by sddarwinlog_private::ExactMatchFilterRule::Dump(), and sddarwinlog_private::RegexFilterRule::Dump().
GetMatchAccepts()
bool sddarwinlog_private::FilterRule::GetMatchAccepts () const inline protected
Definition at line 240 of file StructuredDataDarwinLog.cpp.
References m_accept.
Referenced by sddarwinlog_private::ExactMatchFilterRule::Dump(), and sddarwinlog_private::RegexFilterRule::Dump().
GetOperationType()
llvm::StringRef sddarwinlog_private::FilterRule::GetOperationType () const inline
Definition at line 231 of file StructuredDataDarwinLog.cpp.
References m_operation.
Referenced by Serialize().
RegisterOperation()
void sddarwinlog_private::FilterRule::RegisterOperation (llvm::StringRef operation, const OperationCreationFunc & creation_func) inline static
Definition at line 188 of file StructuredDataDarwinLog.cpp.
References GetCreationFuncMap().
Referenced by sddarwinlog_private::ExactMatchFilterRule::RegisterOperation(), and sddarwinlog_private::RegexFilterRule::RegisterOperation().
Serialize()
StructuredData::ObjectSP sddarwinlog_private::FilterRule::Serialize () const inline
Definition at line 208 of file StructuredDataDarwinLog.cpp.
References lldb_private::StructuredData::Dictionary::AddBooleanItem(), lldb_private::StructuredData::Dictionary::AddStringItem(), DoSerialization(), GetOperationType(), m_accept, m_attribute_index, and sddarwinlog_private::s_filter_attributes.
Member Data Documentation
m_accept
const bool sddarwinlog_private::FilterRule::m_accept private
Definition at line 254 of file StructuredDataDarwinLog.cpp.
Referenced by FilterRule(), GetMatchAccepts(), and Serialize().
m_attribute_index
const size_t sddarwinlog_private::FilterRule::m_attribute_index private
Definition at line 255 of file StructuredDataDarwinLog.cpp.
Referenced by FilterRule(), GetFilterAttribute(), and Serialize().
m_operation
const llvm::StringRef sddarwinlog_private::FilterRule::m_operation private
Definition at line 257 of file StructuredDataDarwinLog.cpp.
Referenced by FilterRule(), and GetOperationType().
The documentation for this class was generated from the following file:
StructuredDataDarwinLog.cpp