LLDB: lldb_private::plugin::dwarf::DWARFIndex Class Reference
lldb_private::plugin::dwarf::DWARFIndex Class Reference abstract
#include <DWARFIndex.h>
Classes
class DIERefCallbackImpl
Public Member Functions
DWARFIndex (Module &module)
virtual ~DWARFIndex ()
virtual void Preload ()=0
virtual void GetGlobalVariables (ConstString basename, llvm::function_ref< IterationAction(DWARFDIE die)> callback)=0
Finds global variables with the given base name.
virtual void GetGlobalVariables (const RegularExpression &regex, llvm::function_ref< IterationAction(DWARFDIE die)> callback)=0
virtual void GetGlobalVariables (DWARFUnit &cu, llvm::function_ref< IterationAction(DWARFDIE die)> callback)=0
cu must be the skeleton unit if possible, not GetNonSkeletonUnit().
virtual void GetObjCMethods (ConstString class_name, llvm::function_ref< IterationAction(DWARFDIE die)> callback)=0
virtual void GetCompleteObjCClass (ConstString class_name, bool must_be_implementation, llvm::function_ref< IterationAction(DWARFDIE die)> callback)=0
virtual void GetTypes (ConstString name, llvm::function_ref< IterationAction(DWARFDIE die)> callback)=0
virtual void GetTypes (const DWARFDeclContext &context, llvm::function_ref< IterationAction(DWARFDIE die)> callback)=0
virtual void GetFullyQualifiedType (const DWARFDeclContext &context, llvm::function_ref< IterationAction(DWARFDIE die)> callback)
Finds all DIEs whose fully qualified name matches context.
virtual void GetNamespaces (ConstString name, llvm::function_ref< IterationAction(DWARFDIE die)> callback)=0
virtual void GetTypesWithQuery (TypeQuery &query, llvm::function_ref< IterationAction(DWARFDIE die)> callback)
Get type DIEs meeting requires of query.
virtual void GetNamespacesWithParents (ConstString name, const CompilerDeclContext &parent_decl_ctx, llvm::function_ref< IterationAction(DWARFDIE die)> callback)
Get namespace DIEs whose base name match.
virtual void GetFunctions (const Module::LookupInfo &lookup_info, SymbolFileDWARF &dwarf, const CompilerDeclContext &parent_decl_ctx, llvm::function_ref< IterationAction(DWARFDIE die)> callback)=0
virtual void GetFunctions (const std::vector< Module::LookupInfo > &lookup_infos, SymbolFileDWARF &dwarf, const CompilerDeclContext &parent_decl_ctx, llvm::function_ref< IterationAction(DWARFDIE die)> callback)
virtual void GetFunctions (const RegularExpression &regex, llvm::function_ref< IterationAction(DWARFDIE die)> callback)=0
virtual void Dump (Stream &s)=0
StatsDuration::Duration GetIndexTime ()
void ResetStatistics ()
Protected Member Functions
IterationAction ProcessFunctionDIE (const Module::LookupInfo &lookup_info, DWARFDIE die, const CompilerDeclContext &parent_decl_ctx, llvm::function_ref< IterationAction(DWARFDIE die)> callback)
Helper function implementing common logic for processing function dies.
DIERefCallbackImpl DIERefCallback (llvm::function_ref< IterationAction(DWARFDIE die)> callback, llvm::StringRef name={}) const
void ReportInvalidDIERef (DIERef ref, llvm::StringRef name) const
IterationAction GetFullyQualifiedTypeImpl (const DWARFDeclContext &context, DWARFDIE die, llvm::function_ref< IterationAction(DWARFDIE die)> callback)
Implementation of GetFullyQualifiedType to check a single entry, shareable with derived classes.
IterationAction ProcessTypeDIEMatchQuery (TypeQuery &query, DWARFDIE die, llvm::function_ref< IterationAction(DWARFDIE die)> callback)
Check if the type die can meet the requirements of query.
IterationAction ProcessNamespaceDieMatchParents (const CompilerDeclContext &parent_decl_ctx, DWARFDIE die, llvm::function_ref< IterationAction(DWARFDIE die)> callback)
Protected Attributes
Module & m_module
StatsDuration m_index_time
Detailed Description
Definition at line 26 of file DWARFIndex.h.
Constructor & Destructor Documentation
DWARFIndex()
lldb_private::plugin::dwarf::DWARFIndex::DWARFIndex (Module & module) inline
Definition at line 28 of file DWARFIndex.h.
References m_module.
Referenced by lldb_private::plugin::dwarf::AppleDWARFIndex::AppleDWARFIndex(), lldb_private::plugin::dwarf::DebugNamesDWARFIndex::DebugNamesDWARFIndex(), and lldb_private::plugin::dwarf::DWARFIndex::DIERefCallbackImpl::DIERefCallbackImpl().
~DWARFIndex()
DWARFIndex::~DWARFIndex () virtual default
Member Function Documentation
DIERefCallback()
DIERefCallbackImpl lldb_private::plugin::dwarf::DWARFIndex::DIERefCallback (llvm::function_ref< IterationAction(DWARFDIE die)> callback, llvm::StringRef name = {}) const inline protected
Definition at line 133 of file DWARFIndex.h.
Referenced by lldb_private::plugin::dwarf::AppleDWARFIndex::GetCompleteObjCClass(), lldb_private::plugin::dwarf::ManualDWARFIndex::GetCompleteObjCClass(), lldb_private::plugin::dwarf::ManualDWARFIndex::GetFunctions(), lldb_private::plugin::dwarf::ManualDWARFIndex::GetFunctions(), lldb_private::plugin::dwarf::AppleDWARFIndex::GetGlobalVariables(), lldb_private::plugin::dwarf::AppleDWARFIndex::GetGlobalVariables(), lldb_private::plugin::dwarf::ManualDWARFIndex::GetGlobalVariables(), lldb_private::plugin::dwarf::ManualDWARFIndex::GetGlobalVariables(), lldb_private::plugin::dwarf::ManualDWARFIndex::GetGlobalVariables(), lldb_private::plugin::dwarf::ManualDWARFIndex::GetNamespaces(), lldb_private::plugin::dwarf::ManualDWARFIndex::GetObjCMethods(), lldb_private::plugin::dwarf::ManualDWARFIndex::GetTypes(), lldb_private::plugin::dwarf::ManualDWARFIndex::GetTypes(), and lldb_private::plugin::dwarf::AppleDWARFIndex::SearchFor().
Dump()
virtual void lldb_private::plugin::dwarf::DWARFIndex::Dump (Stream & s) pure virtual
Implemented in lldb_private::plugin::dwarf::AppleDWARFIndex, lldb_private::plugin::dwarf::DebugNamesDWARFIndex, and lldb_private::plugin::dwarf::ManualDWARFIndex.
GetCompleteObjCClass()
virtual void lldb_private::plugin::dwarf::DWARFIndex::GetCompleteObjCClass (ConstString class_name, bool must_be_implementation, llvm::function_ref< IterationAction(DWARFDIE die)> callback) pure virtual
Implemented in lldb_private::plugin::dwarf::AppleDWARFIndex, lldb_private::plugin::dwarf::DebugNamesDWARFIndex, and lldb_private::plugin::dwarf::ManualDWARFIndex.
GetFullyQualifiedType()
void DWARFIndex::GetFullyQualifiedType (const DWARFDeclContext & context, llvm::function_ref< IterationAction(DWARFDIE die)> callback) virtual
Finds all DIEs whose fully qualified name matches context.
A base implementation is provided, and it uses the entire CU to check the DIE parent hierarchy. Specializations should override this if they are able to provide a faster implementation.
Reimplemented in lldb_private::plugin::dwarf::DebugNamesDWARFIndex.
Definition at line 115 of file DWARFIndex.cpp.
References GetFullyQualifiedTypeImpl(), and GetTypes().
GetFullyQualifiedTypeImpl()
IterationAction DWARFIndex::GetFullyQualifiedTypeImpl (const DWARFDeclContext & context, DWARFDIE die, llvm::function_ref< IterationAction(DWARFDIE die)> callback) protected
Implementation of GetFullyQualifiedType to check a single entry, shareable with derived classes.
Definition at line 123 of file DWARFIndex.cpp.
References lldb_private::Continue, and lldb_private::plugin::dwarf::DWARFDIE::GetDWARFDeclContext().
Referenced by lldb_private::plugin::dwarf::DebugNamesDWARFIndex::GetFullyQualifiedType(), and GetFullyQualifiedType().
GetFunctions() [1/3]
virtual void lldb_private::plugin::dwarf::DWARFIndex::GetFunctions (const Module::LookupInfo & lookup_info, SymbolFileDWARF & dwarf, const CompilerDeclContext & parent_decl_ctx, llvm::function_ref< IterationAction(DWARFDIE die)> callback) pure virtual
Implemented in lldb_private::plugin::dwarf::AppleDWARFIndex, lldb_private::plugin::dwarf::DebugNamesDWARFIndex, and lldb_private::plugin::dwarf::ManualDWARFIndex.
Referenced by GetFunctions().
GetFunctions() [2/3]
virtual void lldb_private::plugin::dwarf::DWARFIndex::GetFunctions (const RegularExpression & regex, llvm::function_ref< IterationAction(DWARFDIE die)> callback) pure virtual
Implemented in lldb_private::plugin::dwarf::AppleDWARFIndex, lldb_private::plugin::dwarf::DebugNamesDWARFIndex, and lldb_private::plugin::dwarf::ManualDWARFIndex.
GetFunctions() [3/3]
void DWARFIndex::GetFunctions (const std::vector< Module::LookupInfo > & lookup_infos, SymbolFileDWARF & dwarf, const CompilerDeclContext & parent_decl_ctx, llvm::function_ref< IterationAction(DWARFDIE die)> callback) virtual
Definition at line 176 of file DWARFIndex.cpp.
References GetFunctions().
GetGlobalVariables() [1/3]
virtual void lldb_private::plugin::dwarf::DWARFIndex::GetGlobalVariables (const RegularExpression & regex, llvm::function_ref< IterationAction(DWARFDIE die)> callback) pure virtual
Implemented in lldb_private::plugin::dwarf::AppleDWARFIndex, lldb_private::plugin::dwarf::DebugNamesDWARFIndex, and lldb_private::plugin::dwarf::ManualDWARFIndex.
GetGlobalVariables() [2/3]
virtual void lldb_private::plugin::dwarf::DWARFIndex::GetGlobalVariables (ConstString basename, llvm::function_ref< IterationAction(DWARFDIE die)> callback) pure virtual
Finds global variables with the given base name.
Any additional filtering (e.g., to only retrieve variables from a given context) should be done by the consumer.
Implemented in lldb_private::plugin::dwarf::AppleDWARFIndex, lldb_private::plugin::dwarf::DebugNamesDWARFIndex, and lldb_private::plugin::dwarf::ManualDWARFIndex.
GetGlobalVariables() [3/3]
virtual void lldb_private::plugin::dwarf::DWARFIndex::GetGlobalVariables (DWARFUnit & cu, llvm::function_ref< IterationAction(DWARFDIE die)> callback) pure virtual
cu must be the skeleton unit if possible, not GetNonSkeletonUnit().
Implemented in lldb_private::plugin::dwarf::AppleDWARFIndex, lldb_private::plugin::dwarf::DebugNamesDWARFIndex, and lldb_private::plugin::dwarf::ManualDWARFIndex.
GetIndexTime()
StatsDuration::Duration lldb_private::plugin::dwarf::DWARFIndex::GetIndexTime () inline
Definition at line 99 of file DWARFIndex.h.
References m_index_time.
GetNamespaces()
virtual void lldb_private::plugin::dwarf::DWARFIndex::GetNamespaces (ConstString name, llvm::function_ref< IterationAction(DWARFDIE die)> callback) pure virtual
Implemented in lldb_private::plugin::dwarf::AppleDWARFIndex, lldb_private::plugin::dwarf::DebugNamesDWARFIndex, and lldb_private::plugin::dwarf::ManualDWARFIndex.
Referenced by GetNamespacesWithParents().
GetNamespacesWithParents()
void DWARFIndex::GetNamespacesWithParents (ConstString name, const CompilerDeclContext & parent_decl_ctx, llvm::function_ref< IterationAction(DWARFDIE die)> callback) virtual
Get namespace DIEs whose base name match.
Parameters
name with
parent_decl_ctx in its decl parent chain. A base implementation is provided. Specializations should override this if they are able to provide a faster implementation.
Reimplemented in lldb_private::plugin::dwarf::DebugNamesDWARFIndex.
Definition at line 168 of file DWARFIndex.cpp.
References GetNamespaces(), and ProcessNamespaceDieMatchParents().
GetObjCMethods()
virtual void lldb_private::plugin::dwarf::DWARFIndex::GetObjCMethods (ConstString class_name, llvm::function_ref< IterationAction(DWARFDIE die)> callback) pure virtual
Implemented in lldb_private::plugin::dwarf::AppleDWARFIndex, lldb_private::plugin::dwarf::DebugNamesDWARFIndex, and lldb_private::plugin::dwarf::ManualDWARFIndex.
GetTypes() [1/2]
virtual void lldb_private::plugin::dwarf::DWARFIndex::GetTypes (const DWARFDeclContext & context, llvm::function_ref< IterationAction(DWARFDIE die)> callback) pure virtual
Implemented in lldb_private::plugin::dwarf::AppleDWARFIndex, lldb_private::plugin::dwarf::DebugNamesDWARFIndex, and lldb_private::plugin::dwarf::ManualDWARFIndex.
GetTypes() [2/2]
virtual void lldb_private::plugin::dwarf::DWARFIndex::GetTypes (ConstString name, llvm::function_ref< IterationAction(DWARFDIE die)> callback) pure virtual
Implemented in lldb_private::plugin::dwarf::AppleDWARFIndex, lldb_private::plugin::dwarf::DebugNamesDWARFIndex, and lldb_private::plugin::dwarf::ManualDWARFIndex.
Referenced by GetFullyQualifiedType(), and GetTypesWithQuery().
GetTypesWithQuery()
void DWARFIndex::GetTypesWithQuery (TypeQuery & query, llvm::function_ref< IterationAction(DWARFDIE die)> callback) virtual
Get type DIEs meeting requires of query.
in its decl parent chain as subset. A base implementation is provided, Specializations should override this if they are able to provide a faster implementation.
Reimplemented in lldb_private::plugin::dwarf::DebugNamesDWARFIndex.
Definition at line 132 of file DWARFIndex.cpp.
References lldb_private::TypeQuery::GetTypeBasename(), and GetTypes().
Preload()
virtual void lldb_private::plugin::dwarf::DWARFIndex::Preload () pure virtual
Implemented in lldb_private::plugin::dwarf::AppleDWARFIndex, lldb_private::plugin::dwarf::DebugNamesDWARFIndex, and lldb_private::plugin::dwarf::ManualDWARFIndex.
ProcessFunctionDIE()
IterationAction DWARFIndex::ProcessFunctionDIE (const Module::LookupInfo & lookup_info, DWARFDIE die, const CompilerDeclContext & parent_decl_ctx, llvm::function_ref< IterationAction(DWARFDIE die)> callback) protected
Helper function implementing common logic for processing function dies.
If the function given by "die" matches search criteria given by "parent_decl_ctx" and "name_type_mask", it calls the callback with the given die.
Definition at line 27 of file DWARFIndex.cpp.
References lldb_private::plugin::dwarf::SymbolFileDWARF::ConstructFunctionDemangledName(), lldb_private::Continue, lldb_private::plugin::dwarf::SymbolFileDWARF::DIEInDeclContext(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetDWARF(), lldb_private::Module::LookupInfo::GetLanguageType(), lldb_private::Module::LookupInfo::GetLookupName(), lldb_private::plugin::dwarf::DWARFDIE::GetMangledName(), lldb_private::plugin::dwarf::DWARFDIE::GetName(), lldb_private::Module::LookupInfo::GetNameTypeMask(), lldb_private::ConstString::GetStringRef(), lldb_private::plugin::dwarf::DWARFDIE::IsMethod(), lldb_private::ObjCLanguage::IsPossibleObjCMethodName(), lldb_private::CompilerDeclContext::IsValid(), and lldb_private::Module::LookupInfo::NameMatchesLookupInfo().
Referenced by lldb_private::plugin::dwarf::AppleDWARFIndex::GetFunctions(), and lldb_private::plugin::dwarf::DebugNamesDWARFIndex::GetFunctions().
ProcessNamespaceDieMatchParents()
IterationAction DWARFIndex::ProcessNamespaceDieMatchParents (const CompilerDeclContext & parent_decl_ctx, DWARFDIE die, llvm::function_ref< IterationAction(DWARFDIE die)> callback) protected
Definition at line 184 of file DWARFIndex.cpp.
References lldb_private::Continue, and lldb_private::plugin::dwarf::SymbolFileDWARF::DIEInDeclContext().
Referenced by lldb_private::plugin::dwarf::DebugNamesDWARFIndex::GetNamespacesWithParents(), and GetNamespacesWithParents().
ProcessTypeDIEMatchQuery()
IterationAction DWARFIndex::ProcessTypeDIEMatchQuery (TypeQuery & query, DWARFDIE die, llvm::function_ref< IterationAction(DWARFDIE die)> callback) protected
Check if the type die can meet the requirements of query.
Definition at line 140 of file DWARFIndex.cpp.
References lldb_private::TypeQuery::ContextMatches(), lldb_private::Continue, lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), lldb_private::plugin::dwarf::DWARFDIE::GetDeclContext(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetLanguageFamily(), lldb_private::plugin::dwarf::DWARFDIE::GetMangledName(), lldb_private::TypeQuery::GetModuleSearch(), lldb_private::TypeQuery::GetSearchByMangledName(), lldb_private::ConstString::GetStringRef(), lldb_private::TypeQuery::GetTypeBasename(), lldb_private::plugin::dwarf::DWARFDIE::GetTypeLookupContext(), lldb_private::TypeQuery::HasLanguage(), and lldb_private::TypeQuery::LanguageMatches().
Referenced by lldb_private::plugin::dwarf::DebugNamesDWARFIndex::GetTypesWithQuery().
ReportInvalidDIERef()
void DWARFIndex::ReportInvalidDIERef (DIERef ref, llvm::StringRef name) const protected
Definition at line 108 of file DWARFIndex.cpp.
References lldb_private::plugin::dwarf::DIERef::die_offset(), and m_module.
Referenced by lldb_private::plugin::dwarf::AppleDWARFIndex::GetFunctions().
ResetStatistics()
void lldb_private::plugin::dwarf::DWARFIndex::ResetStatistics () inline
Definition at line 101 of file DWARFIndex.h.
References m_index_time.
Member Data Documentation
m_index_time
StatsDuration lldb_private::plugin::dwarf::DWARFIndex::m_index_time protected
Definition at line 105 of file DWARFIndex.h.
Referenced by GetIndexTime(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexImpl(), and ResetStatistics().
m_module
Module& lldb_private::plugin::dwarf::DWARFIndex::m_module protected
Definition at line 104 of file DWARFIndex.h.
Referenced by lldb_private::plugin::dwarf::DWARFIndex::DIERefCallbackImpl::DIERefCallbackImpl(), lldb_private::plugin::dwarf::ManualDWARFIndex::Dump(), DWARFIndex(), lldb_private::plugin::dwarf::DebugNamesDWARFIndex::GetDIE(), lldb_private::plugin::dwarf::AppleDWARFIndex::GetTypes(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexImpl(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexUnit(), and ReportInvalidDIERef().
The documentation for this class was generated from the following files:
DWARFIndex.h
DWARFIndex.cpp