LLDB: lldb::SBMemoryRegionInfoList Class Reference
lldb::SBMemoryRegionInfoList Class Reference
#include <SBMemoryRegionInfoList.h>
Public Member Functions
SBMemoryRegionInfoList ()
SBMemoryRegionInfoList (const lldb::SBMemoryRegionInfoList &rhs)
const SBMemoryRegionInfoList & operator= (const SBMemoryRegionInfoList &rhs)
~SBMemoryRegionInfoList ()
uint32_t GetSize () const
bool GetMemoryRegionContainingAddress (lldb::addr_t addr, SBMemoryRegionInfo &region_info)
bool GetMemoryRegionAtIndex (uint32_t idx, SBMemoryRegionInfo &region_info)
void Append (lldb::SBMemoryRegionInfo &region)
void Append (lldb::SBMemoryRegionInfoList &region_list)
void Clear ()
Protected Member Functions
const MemoryRegionInfoListImpl * operator-> () const
const MemoryRegionInfoListImpl & operator* () const
Private Member Functions
lldb_private::MemoryRegionInfos & ref ()
const lldb_private::MemoryRegionInfos & ref () const
Private Attributes
std::unique_ptr< MemoryRegionInfoListImpl > m_opaque_up
Friends
class SBProcess
class SBSaveCoreOptions
Detailed Description
Definition at line 18 of file SBMemoryRegionInfoList.h.
Constructor & Destructor Documentation
SBMemoryRegionInfoList() [1/2]
SBMemoryRegionInfoList::SBMemoryRegionInfoList ()
Definition at line 83 of file SBMemoryRegionInfoList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by Append(), operator=(), and SBMemoryRegionInfoList().
SBMemoryRegionInfoList() [2/2]
SBMemoryRegionInfoList::SBMemoryRegionInfoList (const lldb::SBMemoryRegionInfoList & rhs)
Definition at line 88 of file SBMemoryRegionInfoList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and SBMemoryRegionInfoList().
~SBMemoryRegionInfoList()
SBMemoryRegionInfoList::~SBMemoryRegionInfoList () default
References Append(), Clear(), GetMemoryRegionAtIndex(), GetMemoryRegionContainingAddress(), GetSize(), operator*(), and operator->().
Member Function Documentation
Append() [1/2]
void SBMemoryRegionInfoList::Append (lldb::SBMemoryRegionInfo & region)
Definition at line 132 of file SBMemoryRegionInfoList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBMemoryRegionInfo::ref().
Referenced by lldb::SBSaveCoreOptions::GetMemoryRegionsToSave(), and ~SBMemoryRegionInfoList().
Append() [2/2]
void SBMemoryRegionInfoList::Append (lldb::SBMemoryRegionInfoList & region_list)
Definition at line 138 of file SBMemoryRegionInfoList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and SBMemoryRegionInfoList().
Clear()
void SBMemoryRegionInfoList::Clear ()
Definition at line 126 of file SBMemoryRegionInfoList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBMemoryRegionInfoList().
GetMemoryRegionAtIndex()
bool SBMemoryRegionInfoList::GetMemoryRegionAtIndex (uint32_t idx, SBMemoryRegionInfo & region_info)
Definition at line 119 of file SBMemoryRegionInfoList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBMemoryRegionInfo::ref().
Referenced by ~SBMemoryRegionInfoList().
GetMemoryRegionContainingAddress()
bool SBMemoryRegionInfoList::GetMemoryRegionContainingAddress (lldb::addr_t addr, SBMemoryRegionInfo & region_info)
Definition at line 112 of file SBMemoryRegionInfoList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBMemoryRegionInfo::ref().
Referenced by ~SBMemoryRegionInfoList().
GetSize()
uint32_t SBMemoryRegionInfoList::GetSize () const
Definition at line 106 of file SBMemoryRegionInfoList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBMemoryRegionInfoList().
operator*()
const MemoryRegionInfoListImpl & SBMemoryRegionInfoList::operator* () const protected
Definition at line 148 of file SBMemoryRegionInfoList.cpp.
References m_opaque_up.
Referenced by ~SBMemoryRegionInfoList().
operator->()
const MemoryRegionInfoListImpl * SBMemoryRegionInfoList::operator-> () const protected
Definition at line 144 of file SBMemoryRegionInfoList.cpp.
References m_opaque_up.
Referenced by ~SBMemoryRegionInfoList().
operator=()
const SBMemoryRegionInfoList & SBMemoryRegionInfoList::operator= (const SBMemoryRegionInfoList & rhs)
Definition at line 96 of file SBMemoryRegionInfoList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and SBMemoryRegionInfoList().
ref() [1/2]
MemoryRegionInfos & SBMemoryRegionInfoList::ref () private
Definition at line 77 of file SBMemoryRegionInfoList.cpp.
References m_opaque_up.
Referenced by lldb::SBProcess::GetMemoryRegions(), and SBSaveCoreOptions.
ref() [2/2]
const MemoryRegionInfos & SBMemoryRegionInfoList::ref () const private
Definition at line 79 of file SBMemoryRegionInfoList.cpp.
References m_opaque_up.
Friends And Related Symbol Documentation
SBProcess
friend class SBProcess friend
Definition at line 47 of file SBMemoryRegionInfoList.h.
References SBProcess.
Referenced by SBProcess.
SBSaveCoreOptions
friend class SBSaveCoreOptions friend
Definition at line 48 of file SBMemoryRegionInfoList.h.
References ref(), and SBSaveCoreOptions.
Referenced by SBSaveCoreOptions.
Member Data Documentation
m_opaque_up
std::unique_ptr<MemoryRegionInfoListImpl> lldb::SBMemoryRegionInfoList::m_opaque_up private
Definition at line 54 of file SBMemoryRegionInfoList.h.
Referenced by Append(), Append(), Clear(), GetMemoryRegionAtIndex(), GetMemoryRegionContainingAddress(), GetSize(), operator*(), operator->(), operator=(), ref(), ref(), SBMemoryRegionInfoList(), and SBMemoryRegionInfoList().
The documentation for this class was generated from the following files:
SBMemoryRegionInfoList.h
SBMemoryRegionInfoList.cpp