LLDB: lldb_private::ValueList Class Reference
lldb_private::ValueList Class Reference
#include <Value.h>
Public Member Functions
ValueList ()=default
~ValueList ()=default
ValueList (const ValueList &rhs)=default
ValueList & operator= (const ValueList &rhs)=default
void PushValue (const Value &value)
size_t GetSize ()
Value * GetValueAtIndex (size_t idx)
void Clear ()
Private Types
typedef std::vector< Value > collection
Private Attributes
collection m_values
Detailed Description
Definition at line 187 of file Value.h.
Member Typedef Documentation
collection
typedef std::vector<Value> lldb_private::ValueList::collection private
Definition at line 203 of file Value.h.
Constructor & Destructor Documentation
ValueList() [1/2]
lldb_private::ValueList::ValueList () default
Referenced by operator=(), and ValueList().
~ValueList()
lldb_private::ValueList::~ValueList () default
ValueList() [2/2]
lldb_private::ValueList::ValueList (const ValueList & rhs) default
References ValueList().
Member Function Documentation
Clear()
void ValueList::Clear ()
Definition at line 705 of file Value.cpp.
References m_values.
GetSize()
size_t ValueList::GetSize ()
Definition at line 696 of file Value.cpp.
References m_values.
Referenced by ABIMacOSX_arm64::GetArgumentValues(), ABIMacOSX_arm::GetArgumentValues(), ABIMacOSX_i386::GetArgumentValues(), ABISysV_arm64::GetArgumentValues(), ABISysV_arm::GetArgumentValues(), ABISysV_i386::GetArgumentValues(), ABISysV_ppc64::GetArgumentValues(), ABISysV_ppc::GetArgumentValues(), ABISysV_s390x::GetArgumentValues(), ABISysV_x86_64::GetArgumentValues(), ABIWindows_x86_64::GetArgumentValues(), GetValueAtIndex(), and lldb_private::FunctionCaller::WriteFunctionArguments().
GetValueAtIndex()
Value * ValueList::GetValueAtIndex (size_t idx)
Definition at line 698 of file Value.cpp.
References GetSize(), and m_values.
Referenced by lldb_private::PlatformWindows::DoLoadImage(), ABIMacOSX_arm64::GetArgumentValues(), ABIMacOSX_arm::GetArgumentValues(), ABIMacOSX_i386::GetArgumentValues(), ABISysV_arm64::GetArgumentValues(), ABISysV_arm::GetArgumentValues(), ABISysV_i386::GetArgumentValues(), ABISysV_ppc64::GetArgumentValues(), ABISysV_ppc::GetArgumentValues(), ABISysV_s390x::GetArgumentValues(), ABISysV_x86_64::GetArgumentValues(), ABIWindows_x86_64::GetArgumentValues(), lldb_private::AppleObjCTrampolineHandler::GetStepThroughDispatchPlan(), lldb_private::ThreadPlanAssemblyTracer::Log(), DynamicLoaderMacOS::NotifyBreakpointHit(), DynamicLoaderMacOSXDYLD::NotifyBreakpointHit(), lldb_private::AbortWithPayloadFrameRecognizer::RecognizeFrame(), lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::RefreshTrampolines(), and lldb_private::FunctionCaller::WriteFunctionArguments().
operator=()
ValueList & lldb_private::ValueList::operator= (const ValueList & rhs) default
References ValueList().
PushValue()
void ValueList::PushValue (const Value & value)
Definition at line 694 of file Value.cpp.
References m_values.
Referenced by lldb_private::AppleObjCRuntimeV2::DynamicClassInfoExtractor::GetClassInfoUtilityFunction(), lldb_private::AppleGetQueuesHandler::GetCurrentQueues(), lldb_private::AppleGetItemInfoHandler::GetItemInfo(), lldb_private::AppleObjCRuntime::GetObjectDescription(), lldb_private::AppleGetPendingItemsHandler::GetPendingItems(), lldb_private::AppleObjCTrampolineHandler::GetStepThroughDispatchPlan(), lldb_private::AppleGetThreadItemInfoHandler::GetThreadItemInfo(), lldb_private::ThreadPlanAssemblyTracer::Log(), DynamicLoaderMacOS::NotifyBreakpointHit(), DynamicLoaderMacOSXDYLD::NotifyBreakpointHit(), lldb_private::AbortWithPayloadFrameRecognizer::RecognizeFrame(), and lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::RefreshTrampolines().
Member Data Documentation
m_values
collection lldb_private::ValueList::m_values private
Definition at line 205 of file Value.h.
Referenced by Clear(), GetSize(), GetValueAtIndex(), and PushValue().
The documentation for this class was generated from the following files:
Value.h
Value.cpp