LLDB: lldb_private::AppleObjCDeclVendor Class Reference
lldb_private::AppleObjCDeclVendor Class Reference
#include <AppleObjCDeclVendor.h>
Public Member Functions
AppleObjCDeclVendor (ObjCLanguageRuntime &runtime)
uint32_t FindDecls (ConstString name, bool append, uint32_t max_matches, std::vector< CompilerDecl > &decls) override
Look up the set of Decls that the DeclVendor currently knows about matching a given name.
Public Member Functions inherited from lldb_private::DeclVendor
DeclVendor (DeclVendorKind kind)
virtual ~DeclVendor ()=default
DeclVendorKind GetKind () const
std::vector< CompilerType > FindTypes (ConstString name, uint32_t max_matches)
Look up the types that the DeclVendor currently knows about matching a given name.
Static Public Member Functions
static bool classof (const DeclVendor *vendor)
Private Types
typedef llvm::DenseMap< ObjCLanguageRuntime::ObjCISA, clang::ObjCInterfaceDecl * > ISAToInterfaceMap
Private Member Functions
clang::ObjCInterfaceDecl * GetDeclForISA (ObjCLanguageRuntime::ObjCISA isa)
bool FinishDecl (clang::ObjCInterfaceDecl *decl)
Private Attributes
ObjCLanguageRuntime & m_runtime
std::shared_ptr< TypeSystemClang > m_ast_ctx
ObjCLanguageRuntime::EncodingToTypeSP m_type_realizer_sp
AppleObjCExternalASTSource * m_external_source
ISAToInterfaceMap m_isa_to_interface
Friends
class AppleObjCExternalASTSource
Additional Inherited Members
Public Types inherited from lldb_private::DeclVendor
enum DeclVendorKind { eClangModuleDeclVendor , eAppleObjCDeclVendor , eLastClangDeclVendor }
Detailed Description
Definition at line 22 of file AppleObjCDeclVendor.h.
Member Typedef Documentation
ISAToInterfaceMap
typedef llvm::DenseMap<ObjCLanguageRuntime::ObjCISA, clang::ObjCInterfaceDecl *> lldb_private::AppleObjCDeclVendor::ISAToInterfaceMap private
Definition at line 46 of file AppleObjCDeclVendor.h.
Constructor & Destructor Documentation
AppleObjCDeclVendor()
AppleObjCDeclVendor::AppleObjCDeclVendor (ObjCLanguageRuntime & runtime)
Definition at line 133 of file AppleObjCDeclVendor.cpp.
References lldb_private::DeclVendor::DeclVendor(), lldb_private::DeclVendor::eAppleObjCDeclVendor, lldb_private::Target::GetArchitecture(), lldb_private::Runtime::GetProcess(), lldb_private::Process::GetTarget(), lldb_private::ArchSpec::GetTriple(), m_ast_ctx, m_external_source, m_runtime, and m_type_realizer_sp.
Member Function Documentation
classof()
bool lldb_private::AppleObjCDeclVendor::classof (const DeclVendor * vendor) inline static
Definition at line 26 of file AppleObjCDeclVendor.h.
References lldb_private::DeclVendor::DeclVendor(), lldb_private::DeclVendor::eAppleObjCDeclVendor, and lldb_private::DeclVendor::GetKind().
FindDecls()
uint32_t AppleObjCDeclVendor::FindDecls (ConstString name, bool append, uint32_t max_matches, std::vector< CompilerDecl > & decls) override virtual
Look up the set of Decls that the DeclVendor currently knows about matching a given name.
Parameters
[in] name The name to look for.
[in] append If true, FindDecls will clear "decls" when it starts.
[in] max_matches The maximum number of Decls to return. UINT32_MAX means "as many as possible."
Returns
The number of Decls added to decls; will not exceed max_matches.
Implements lldb_private::DeclVendor.
Definition at line 526 of file AppleObjCDeclVendor.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::Expressions, GetDeclForISA(), lldb_private::GetLog(), lldb_private::ConstString::GetStringRef(), LLDB_INVALID_ADDRESS, LLDB_LOG, LLDB_LOGF, m_ast_ctx, and m_runtime.
FinishDecl()
bool AppleObjCDeclVendor::FinishDecl (clang::ObjCInterfaceDecl * decl) private
Definition at line 398 of file AppleObjCDeclVendor.cpp.
References ObjCRuntimeMethodType::BuildMethod(), lldb_private::ClangUtil::DumpDecl(), lldb_private::Expressions, FinishDecl(), GetDeclForISA(), lldb_private::GetLog(), lldb_private::ClangUtil::GetQualType(), lldb_private::CompilerType::IsValid(), LLDB_LOG, LLDB_LOGF, m_ast_ctx, m_runtime, and m_type_realizer_sp.
Referenced by FinishDecl().
GetDeclForISA()
clang::ObjCInterfaceDecl * AppleObjCDeclVendor::GetDeclForISA (ObjCLanguageRuntime::ObjCISA isa) private
Definition at line 146 of file AppleObjCDeclVendor.cpp.
References lldb_private::ConstString::GetStringRef(), m_ast_ctx, m_isa_to_interface, m_runtime, and lldb_private::ClangASTMetadata::SetISAPtr().
Referenced by FindDecls(), and FinishDecl().
Friends And Related Symbol Documentation
AppleObjCExternalASTSource
friend class AppleObjCExternalASTSource friend
Definition at line 33 of file AppleObjCDeclVendor.h.
References AppleObjCExternalASTSource.
Referenced by AppleObjCExternalASTSource.
Member Data Documentation
m_ast_ctx
std::shared_ptr<TypeSystemClang> lldb_private::AppleObjCDeclVendor::m_ast_ctx private
Definition at line 40 of file AppleObjCDeclVendor.h.
Referenced by AppleObjCDeclVendor(), FindDecls(), FinishDecl(), and GetDeclForISA().
m_external_source
AppleObjCExternalASTSource* lldb_private::AppleObjCDeclVendor::m_external_source private
Definition at line 42 of file AppleObjCDeclVendor.h.
Referenced by AppleObjCDeclVendor().
m_isa_to_interface
ISAToInterfaceMap lldb_private::AppleObjCDeclVendor::m_isa_to_interface private
Definition at line 48 of file AppleObjCDeclVendor.h.
Referenced by GetDeclForISA().
m_runtime
ObjCLanguageRuntime& lldb_private::AppleObjCDeclVendor::m_runtime private
Definition at line 39 of file AppleObjCDeclVendor.h.
Referenced by AppleObjCDeclVendor(), FindDecls(), FinishDecl(), and GetDeclForISA().
m_type_realizer_sp
ObjCLanguageRuntime::EncodingToTypeSP lldb_private::AppleObjCDeclVendor::m_type_realizer_sp private
Definition at line 41 of file AppleObjCDeclVendor.h.
Referenced by AppleObjCDeclVendor(), and FinishDecl().
The documentation for this class was generated from the following files:
AppleObjCDeclVendor.h
AppleObjCDeclVendor.cpp