LLDB: ABIARM Class Reference
ABIARM Class Reference
#include <ABIARM.h>
Static Public Member Functions
static void Initialize ()
static void Terminate ()
Detailed Description
Definition at line 12 of file ABIARM.h.
Member Function Documentation
Initialize()
void ABIARM::Initialize () static
Definition at line 16 of file ABIARM.cpp.
References Initialize(), ABIMacOSX_arm::Initialize(), and ABISysV_arm::Initialize().
Referenced by Initialize().
Terminate()
void ABIARM::Terminate () static
Definition at line 21 of file ABIARM.cpp.
References ABIMacOSX_arm::Terminate(), and ABISysV_arm::Terminate().
The documentation for this class was generated from the following files:
ABIARM.h
ABIARM.cpp