LLDB: lldb_private::StopInfoWatchpoint::WatchpointSentry Class Reference
lldb_private::StopInfoWatchpoint::WatchpointSentry Class Reference
Public Member Functions
WatchpointSentry (ProcessSP p_sp, WatchpointSP w_sp)
void DoReenable ()
~WatchpointSentry ()
Static Public Member Functions
static bool SentryPreResumeAction (void *sentry_void)
Private Attributes
ProcessSP process_sp
WatchpointSP watchpoint_sp
Detailed Description
Definition at line 720 of file StopInfo.cpp.
Constructor & Destructor Documentation
WatchpointSentry()
lldb_private::StopInfoWatchpoint::WatchpointSentry::WatchpointSentry (ProcessSP p_sp, WatchpointSP w_sp) inline
Definition at line 722 of file StopInfo.cpp.
References process_sp, SentryPreResumeAction(), and watchpoint_sp.
Referenced by SentryPreResumeAction().
~WatchpointSentry()
lldb_private::StopInfoWatchpoint::WatchpointSentry::~WatchpointSentry () inline
Definition at line 745 of file StopInfo.cpp.
References DoReenable(), process_sp, and SentryPreResumeAction().
Member Function Documentation
DoReenable()
void lldb_private::StopInfoWatchpoint::WatchpointSentry::DoReenable () inline
Definition at line 732 of file StopInfo.cpp.
References process_sp, and watchpoint_sp.
Referenced by SentryPreResumeAction(), and ~WatchpointSentry().
SentryPreResumeAction()
bool lldb_private::StopInfoWatchpoint::WatchpointSentry::SentryPreResumeAction (void * sentry_void) inline static
Definition at line 751 of file StopInfo.cpp.
References DoReenable(), and WatchpointSentry().
Referenced by WatchpointSentry(), and ~WatchpointSentry().
Member Data Documentation
process_sp
ProcessSP lldb_private::StopInfoWatchpoint::WatchpointSentry::process_sp private
Definition at line 758 of file StopInfo.cpp.
Referenced by DoReenable(), WatchpointSentry(), and ~WatchpointSentry().
watchpoint_sp
WatchpointSP lldb_private::StopInfoWatchpoint::WatchpointSentry::watchpoint_sp private
Definition at line 759 of file StopInfo.cpp.
Referenced by DoReenable(), and WatchpointSentry().
The documentation for this class was generated from the following file:
StopInfo.cpp