LLDB: RegisterInfoPOSIX_loongarch64 Class Reference
RegisterInfoPOSIX_loongarch64 Class Reference
#include <RegisterInfoPOSIX_loongarch64.h>
Classes
struct FPR
struct GPR
struct LASX
struct LSX
Public Types
enum RegSetKind { GPRegSet , FPRegSet , LSXRegSet , LASXRegSet }
Public Member Functions
RegisterInfoPOSIX_loongarch64 (const lldb_private::ArchSpec &target_arch, lldb_private::Flags flags)
size_t GetGPRSize () const override
size_t GetFPRSize () const override
const lldb_private::RegisterInfo * GetRegisterInfo () const override
uint32_t GetRegisterCount () const override
const lldb_private::RegisterSet * GetRegisterSet (size_t reg_set) const override
size_t GetRegisterSetCount () const override
size_t GetRegisterSetFromRegisterIndex (uint32_t reg_index) const override
Public Member Functions inherited from lldb_private::RegisterInfoAndSetInterface
RegisterInfoAndSetInterface (const lldb_private::ArchSpec &target_arch)
Public Member Functions inherited from lldb_private::RegisterInfoInterface
RegisterInfoInterface (const lldb_private::ArchSpec &target_arch)
virtual ~RegisterInfoInterface ()=default
virtual uint32_t GetUserRegisterCount () const
const lldb_private::ArchSpec & GetTargetArchitecture () const
Static Public Member Functions
static const lldb_private::RegisterInfo * GetRegisterInfoPtr (const lldb_private::ArchSpec &target_arch)
static uint32_t GetRegisterInfoCount (const lldb_private::ArchSpec &target_arch)
Private Attributes
const lldb_private::RegisterInfo * m_register_info_p
uint32_t m_register_info_count
Detailed Description
Definition at line 17 of file RegisterInfoPOSIX_loongarch64.h.
Member Enumeration Documentation
RegSetKind
enum RegisterInfoPOSIX_loongarch64::RegSetKind
Enumerator
GPRegSet
FPRegSet
LSXRegSet
LASXRegSet
Definition at line 26 of file RegisterInfoPOSIX_loongarch64.h.
Constructor & Destructor Documentation
RegisterInfoPOSIX_loongarch64()
RegisterInfoPOSIX_loongarch64::RegisterInfoPOSIX_loongarch64 (const lldb_private::ArchSpec & target_arch, lldb_private::Flags flags)
Definition at line 169 of file RegisterInfoPOSIX_loongarch64.cpp.
References GetRegisterInfoCount(), GetRegisterInfoPtr(), m_register_info_count, m_register_info_p, and lldb_private::RegisterInfoAndSetInterface::RegisterInfoAndSetInterface().
Member Function Documentation
GetFPRSize()
size_t RegisterInfoPOSIX_loongarch64::GetFPRSize () const override virtual
Implements lldb_private::RegisterInfoAndSetInterface.
Definition at line 183 of file RegisterInfoPOSIX_loongarch64.cpp.
GetGPRSize()
size_t RegisterInfoPOSIX_loongarch64::GetGPRSize () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 179 of file RegisterInfoPOSIX_loongarch64.cpp.
GetRegisterCount()
uint32_t RegisterInfoPOSIX_loongarch64::GetRegisterCount () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 175 of file RegisterInfoPOSIX_loongarch64.cpp.
References m_register_info_count.
GetRegisterInfo()
const lldb_private::RegisterInfo * RegisterInfoPOSIX_loongarch64::GetRegisterInfo () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 188 of file RegisterInfoPOSIX_loongarch64.cpp.
References m_register_info_p.
GetRegisterInfoCount()
uint32_t RegisterInfoPOSIX_loongarch64::GetRegisterInfoCount (const lldb_private::ArchSpec & target_arch) static
Definition at line 52 of file RegisterInfoPOSIX_loongarch64.cpp.
References lldb_private::ArchSpec::GetMachine().
Referenced by lldb_private::EmulateInstructionLoongArch::GetRegisterInfo(), and RegisterInfoPOSIX_loongarch64().
GetRegisterInfoPtr()
const lldb_private::RegisterInfo * RegisterInfoPOSIX_loongarch64::GetRegisterInfoPtr (const lldb_private::ArchSpec & target_arch) static
Definition at line 41 of file RegisterInfoPOSIX_loongarch64.cpp.
References lldb_private::ArchSpec::GetMachine().
Referenced by lldb_private::EmulateInstructionLoongArch::GetRegisterInfo(), and RegisterInfoPOSIX_loongarch64().
GetRegisterSet()
const lldb_private::RegisterSet * RegisterInfoPOSIX_loongarch64::GetRegisterSet (size_t reg_set) const override virtual
Implements lldb_private::RegisterInfoAndSetInterface.
Definition at line 211 of file RegisterInfoPOSIX_loongarch64.cpp.
References g_reg_sets_loongarch64, and GetRegisterSetCount().
GetRegisterSetCount()
size_t RegisterInfoPOSIX_loongarch64::GetRegisterSetCount () const override virtual
Implements lldb_private::RegisterInfoAndSetInterface.
Definition at line 192 of file RegisterInfoPOSIX_loongarch64.cpp.
References k_num_register_sets.
Referenced by GetRegisterSet().
GetRegisterSetFromRegisterIndex()
size_t RegisterInfoPOSIX_loongarch64::GetRegisterSetFromRegisterIndex (uint32_t reg_index) const override virtual
Implements lldb_private::RegisterInfoAndSetInterface.
Definition at line 196 of file RegisterInfoPOSIX_loongarch64.cpp.
References fpr_first_loongarch, fpr_last_loongarch, FPRegSet, gpr_first_loongarch, gpr_last_loongarch, GPRegSet, lasx_first_loongarch, lasx_last_loongarch, LASXRegSet, LLDB_INVALID_REGNUM, lsx_first_loongarch, lsx_last_loongarch, and LSXRegSet.
Member Data Documentation
m_register_info_count
uint32_t RegisterInfoPOSIX_loongarch64::m_register_info_count private
Definition at line 78 of file RegisterInfoPOSIX_loongarch64.h.
Referenced by GetRegisterCount(), and RegisterInfoPOSIX_loongarch64().
m_register_info_p
const lldb_private::RegisterInfo* RegisterInfoPOSIX_loongarch64::m_register_info_p private
Definition at line 77 of file RegisterInfoPOSIX_loongarch64.h.
Referenced by GetRegisterInfo(), and RegisterInfoPOSIX_loongarch64().
The documentation for this class was generated from the following files:
RegisterInfoPOSIX_loongarch64.h
RegisterInfoPOSIX_loongarch64.cpp