LLDB: lldb_private::ArchitectureAArch64 Class Reference
lldb_private::ArchitectureAArch64 Class Reference
#include <ArchitectureAArch64.h>
Public Member Functions
llvm::StringRef GetPluginName () override
void OverrideStopInfo (Thread &thread) const override
This is currently intended to handle cases where a program stops at an instruction that won't get executed and it allows the stop reason, like "breakpoint hit", to be replaced with a different stop reason like "no stop reason".
const MemoryTagManager * GetMemoryTagManager () const override
bool RegisterWriteCausesReconfigure (const llvm::StringRef name) const override
bool ReconfigureRegisterInfo (DynamicRegisterInfo &reg_info, DataExtractor &reg_data, RegisterContext &reg_context) const override
Public Member Functions inherited from lldb_private::Architecture
virtual size_t GetBytesToSkip (Symbol &func, const Address &curr_addr) const
This method is used to get the number of bytes that should be skipped, from function start address, to reach the first instruction after the prologue.
virtual void AdjustBreakpointAddress (const Symbol &func, Address &addr) const
Adjust function breakpoint address, if needed.
virtual lldb::addr_t GetCallableLoadAddress (lldb::addr_t addr, AddressClass addr_class=AddressClass::eInvalid) const
Get load_addr as a callable code load address for this target.
virtual lldb::addr_t GetOpcodeLoadAddress (lldb::addr_t addr, AddressClass addr_class=AddressClass::eInvalid) const
Get load_addr as an opcode for this target.
virtual lldb::addr_t GetBreakableLoadAddress (lldb::addr_t addr, Target &target) const
virtual lldb::UnwindPlanSP GetArchitectureUnwindPlan (lldb_private::Thread &thread, lldb_private::RegisterContextUnwind *regctx, std::shared_ptr< const UnwindPlan > current_unwindplan)
Return an UnwindPlan that allows architecture-defined rules for finding saved registers, given a particular set of register values.
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static llvm::StringRef GetPluginNameStatic ()
static void Initialize ()
static void Terminate ()
Private Member Functions
ArchitectureAArch64 ()=default
Static Private Member Functions
static std::unique_ptr< Architecture > Create (const ArchSpec &arch)
Private Attributes
MemoryTagManagerAArch64MTE m_memory_tag_manager
Detailed Description
Definition at line 17 of file ArchitectureAArch64.h.
Constructor & Destructor Documentation
ArchitectureAArch64()
lldb_private::ArchitectureAArch64::ArchitectureAArch64 () private default
Referenced by Create(), and Initialize().
Member Function Documentation
Create()
std::unique_ptr< Architecture > ArchitectureAArch64::Create (const ArchSpec & arch) static private
Definition at line 32 of file ArchitectureAArch64.cpp.
References ArchitectureAArch64(), and lldb_private::ArchSpec::GetMachine().
Referenced by Initialize(), and Terminate().
GetMemoryTagManager()
const MemoryTagManager * lldb_private::ArchitectureAArch64::GetMemoryTagManager () const inline override virtual
Reimplemented from lldb_private::Architecture.
Definition at line 27 of file ArchitectureAArch64.h.
References m_memory_tag_manager.
GetPluginName()
llvm::StringRef lldb_private::ArchitectureAArch64::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 23 of file ArchitectureAArch64.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::ArchitectureAArch64::GetPluginNameStatic () inline static
Definition at line 19 of file ArchitectureAArch64.h.
Referenced by GetPluginName(), and Initialize().
Initialize()
void ArchitectureAArch64::Initialize () static
Definition at line 21 of file ArchitectureAArch64.cpp.
References ArchitectureAArch64(), Create(), GetPluginNameStatic(), Initialize(), and lldb_private::PluginManager::RegisterPlugin().
Referenced by Initialize().
OverrideStopInfo()
void lldb_private::ArchitectureAArch64::OverrideStopInfo (Thread & thread) const inline override virtual
This is currently intended to handle cases where a program stops at an instruction that won't get executed and it allows the stop reason, like "breakpoint hit", to be replaced with a different stop reason like "no stop reason".
This is specifically used for ARM in Thumb code when we stop in an IT instruction (if/then/else) where the instruction won't get executed and therefore it wouldn't be correct to show the program stopped at the current PC. The code is generic and applies to all ARM CPUs.
Implements lldb_private::Architecture.
Definition at line 25 of file ArchitectureAArch64.h.
ReconfigureRegisterInfo()
bool ArchitectureAArch64::ReconfigureRegisterInfo (DynamicRegisterInfo & reg_info, DataExtractor & reg_data, RegisterContext & reg_context) const override virtual
Reimplemented from lldb_private::Architecture.
Definition at line 75 of file ArchitectureAArch64.cpp.
References lldb_private::DynamicRegisterInfo::ConfigureOffsets(), lldb::eRegisterKindLLDB, lldb_private::RegisterContext::GetByteOrder(), lldb_private::DynamicRegisterInfo::GetRegisterDataByteSize(), lldb_private::DynamicRegisterInfo::GetRegisterInfo(), lldb_private::RegisterInfo::kinds, LLDB_INVALID_ADDRESS, lldb_private::RegisterContext::ReadRegisterAsUnsigned(), lldb_private::DynamicRegisterInfo::registers(), lldb_private::DataExtractor::SetByteOrder(), lldb_private::DataExtractor::SetData(), UpdateARM64SMERegistersInfos(), and UpdateARM64SVERegistersInfos().
RegisterWriteCausesReconfigure()
bool lldb_private::ArchitectureAArch64::RegisterWriteCausesReconfigure (const llvm::StringRef name) const inline override virtual
Reimplemented from lldb_private::Architecture.
Definition at line 32 of file ArchitectureAArch64.h.
Terminate()
void ArchitectureAArch64::Terminate () static
Definition at line 27 of file ArchitectureAArch64.cpp.
References Create(), and lldb_private::PluginManager::UnregisterPlugin().
Member Data Documentation
m_memory_tag_manager
MemoryTagManagerAArch64MTE lldb_private::ArchitectureAArch64::m_memory_tag_manager private
Definition at line 45 of file ArchitectureAArch64.h.
Referenced by GetMemoryTagManager().
The documentation for this class was generated from the following files:
ArchitectureAArch64.h
ArchitectureAArch64.cpp