LLDB: lldb_private::PseudoConsole Class Reference
lldb_private::PseudoConsole Class Reference
#include <PseudoConsole.h>
Public Member Functions
PseudoConsole ()=default
~PseudoConsole ()
PseudoConsole (const PseudoConsole &)=delete
PseudoConsole (PseudoConsole &&)=delete
PseudoConsole & operator= (const PseudoConsole &)=delete
PseudoConsole & operator= (PseudoConsole &&)=delete
llvm::Error OpenPseudoConsole ()
Creates and opens a new ConPTY instance with a default console size of 80x25.
void Close ()
Closes the ConPTY and invalidates its handle, without closing the STDIN and STDOUT pipes.
void ClosePipes ()
Closes the STDIN and STDOUT pipe handles and invalidates them.
bool IsConnected () const
Returns whether the ConPTY and its pipes are currently open and valid.
HPCON GetPseudoTerminalHandle ()
The ConPTY HPCON handle accessor.
HANDLE GetSTDOUTHandle () const
The STDOUT read HANDLE accessor.
HANDLE GetSTDINHandle () const
The STDIN write HANDLE accessor.
llvm::Error DrainInitSequences ()
Drains initialization sequences from the ConPTY output pipe.
std::mutex & GetMutex ()
Returns a reference to the mutex used to synchronize access to the ConPTY state.
std::condition_variable & GetCV ()
Returns a reference to the condition variable used to signal state changes to threads waiting on the ConPTY (e.g.
bool IsStopping () const
Returns whether the ConPTY is in the process of shutting down.
void SetStopping (bool value)
Sets the stopping flag to value, signalling to threads waiting on the ConPTY that they should stop.
Protected Attributes
HANDLE m_conpty_handle = ((HANDLE)(long long)-1)
HANDLE m_conpty_output = ((HANDLE)(long long)-1)
HANDLE m_conpty_input = ((HANDLE)(long long)-1)
std::mutex m_mutex {}
std::condition_variable m_cv {}
std::atomic< bool > m_stopping = false
Detailed Description
Definition at line 22 of file PseudoConsole.h.
Constructor & Destructor Documentation
PseudoConsole() [1/3]
lldb_private::PseudoConsole::PseudoConsole () default
Referenced by operator=(), operator=(), PseudoConsole(), and PseudoConsole().
~PseudoConsole()
PseudoConsole::~PseudoConsole ()
Definition at line 68 of file PseudoConsole.cpp.
References Close(), and ClosePipes().
PseudoConsole() [2/3]
lldb_private::PseudoConsole::PseudoConsole (const PseudoConsole &) delete
References PseudoConsole().
PseudoConsole() [3/3]
lldb_private::PseudoConsole::PseudoConsole (PseudoConsole &&) delete
References PseudoConsole().
Member Function Documentation
Close()
void PseudoConsole::Close ()
Closes the ConPTY and invalidates its handle, without closing the STDIN and STDOUT pipes.
Closing the ConPTY signals EOF to any process currently attached to it.
Definition at line 140 of file PseudoConsole.cpp.
References kernel32, m_conpty_handle, m_cv, m_mutex, and SetStopping().
Referenced by ~PseudoConsole().
ClosePipes()
void PseudoConsole::ClosePipes ()
Closes the STDIN and STDOUT pipe handles and invalidates them.
Definition at line 150 of file PseudoConsole.cpp.
References m_conpty_input, and m_conpty_output.
Referenced by ~PseudoConsole().
DrainInitSequences()
llvm::Error PseudoConsole::DrainInitSequences ()
Drains initialization sequences from the ConPTY output pipe.
When a process first attaches to a ConPTY, Windows emits VT100/ANSI escape sequences (ESC[2J for clear screen, ESC[H for cursor home and more) as part of the PseudoConsole initialization. To prevent these sequences from appearing in the debugger output (and flushing lldb's shell for instance) we launch a short-lived dummy process that triggers the initialization, then drain all output before launching the actual debuggee.
Definition at line 160 of file PseudoConsole.cpp.
References lldb_private::ProcThreadAttributeList::Create(), error(), m_conpty_handle, m_conpty_output, and lldb_private::ProcThreadAttributeList::SetupPseudoConsole().
Referenced by OpenPseudoConsole().
GetCV()
std::condition_variable & lldb_private::PseudoConsole::GetCV () inline
Returns a reference to the condition variable used to signal state changes to threads waiting on the ConPTY (e.g.
waiting for output or shutdown).
Definition at line 97 of file PseudoConsole.h.
References m_cv.
GetMutex()
std::mutex & lldb_private::PseudoConsole::GetMutex () inline
Returns a reference to the mutex used to synchronize access to the ConPTY state.
Definition at line 93 of file PseudoConsole.h.
References m_mutex.
GetPseudoTerminalHandle()
HPCON lldb_private::PseudoConsole::GetPseudoTerminalHandle () inline
The ConPTY HPCON handle accessor.
This object retains ownership of the HPCON when this accessor is used.
Returns
The ConPTY HPCON handle, or INVALID_HANDLE_VALUE if it is currently invalid.
Definition at line 61 of file PseudoConsole.h.
References m_conpty_handle.
GetSTDINHandle()
HANDLE lldb_private::PseudoConsole::GetSTDINHandle () const inline
The STDIN write HANDLE accessor.
This object retains ownership of the HANDLE when this accessor is used.
Returns
The STDIN write HANDLE, or INVALID_HANDLE_VALUE if it is currently invalid.
Definition at line 79 of file PseudoConsole.h.
References m_conpty_input.
GetSTDOUTHandle()
HANDLE lldb_private::PseudoConsole::GetSTDOUTHandle () const inline
The STDOUT read HANDLE accessor.
This object retains ownership of the HANDLE when this accessor is used.
Returns
The STDOUT read HANDLE, or INVALID_HANDLE_VALUE if it is currently invalid.
Definition at line 70 of file PseudoConsole.h.
References m_conpty_output.
IsConnected()
bool PseudoConsole::IsConnected () const
Returns whether the ConPTY and its pipes are currently open and valid.
Definition at line 134 of file PseudoConsole.cpp.
References m_conpty_handle, m_conpty_input, and m_conpty_output.
IsStopping()
bool lldb_private::PseudoConsole::IsStopping () const inline
Returns whether the ConPTY is in the process of shutting down.
Returns
A reference to the atomic bool that is set to true when the ConPTY is stopping. Callers should check this in their read/write loops to exit gracefully.
Definition at line 105 of file PseudoConsole.h.
References m_stopping.
OpenPseudoConsole()
llvm::Error PseudoConsole::OpenPseudoConsole ()
Creates and opens a new ConPTY instance with a default console size of 80x25.
Also sets up the associated STDIN/STDOUT pipes and drains any initialization sequences emitted by Windows.
Returns
An llvm::Error if the ConPTY could not be created, or if ConPTY is not available on this version of Windows, llvm::Error::success() otherwise.
Definition at line 73 of file PseudoConsole.cpp.
References DrainInitSequences(), error(), lldb_private::GetLog(), lldb_private::Host, kernel32, LLDB_LOG_ERROR, m_conpty_handle, m_conpty_input, and m_conpty_output.
operator=() [1/2]
PseudoConsole & lldb_private::PseudoConsole::operator= (const PseudoConsole &) delete
References PseudoConsole().
operator=() [2/2]
PseudoConsole & lldb_private::PseudoConsole::operator= (PseudoConsole &&) delete
References PseudoConsole().
SetStopping()
void lldb_private::PseudoConsole::SetStopping (bool value) inline
Sets the stopping flag to value, signalling to threads waiting on the ConPTY that they should stop.
Definition at line 109 of file PseudoConsole.h.
References m_stopping.
Referenced by Close().
Member Data Documentation
m_conpty_handle
HANDLE lldb_private::PseudoConsole::m_conpty_handle = ((HANDLE)(long long)-1) protected
Definition at line 112 of file PseudoConsole.h.
Referenced by Close(), DrainInitSequences(), GetPseudoTerminalHandle(), IsConnected(), and OpenPseudoConsole().
m_conpty_input
HANDLE lldb_private::PseudoConsole::m_conpty_input = ((HANDLE)(long long)-1) protected
Definition at line 114 of file PseudoConsole.h.
Referenced by ClosePipes(), GetSTDINHandle(), IsConnected(), and OpenPseudoConsole().
m_conpty_output
HANDLE lldb_private::PseudoConsole::m_conpty_output = ((HANDLE)(long long)-1) protected
Definition at line 113 of file PseudoConsole.h.
Referenced by ClosePipes(), DrainInitSequences(), GetSTDOUTHandle(), IsConnected(), and OpenPseudoConsole().
m_cv
std::condition_variable lldb_private::PseudoConsole::m_cv {} protected
Definition at line 116 of file PseudoConsole.h.
Referenced by Close(), and GetCV().
m_mutex
std::mutex lldb_private::PseudoConsole::m_mutex {} protected
Definition at line 115 of file PseudoConsole.h.
Referenced by Close(), and GetMutex().
m_stopping
std::atomic<bool> lldb_private::PseudoConsole::m_stopping = false protected
Definition at line 117 of file PseudoConsole.h.
Referenced by IsStopping(), and SetStopping().
The documentation for this class was generated from the following files:
PseudoConsole.h
PseudoConsole.cpp