LLDB: lldb_private::TypeNameSpecifierImpl Class Reference
lldb_private::TypeNameSpecifierImpl Class Reference
#include <FormatClasses.h>
Classes
struct TypeOrName
Public Member Functions
TypeNameSpecifierImpl ()=default
TypeNameSpecifierImpl (llvm::StringRef name, lldb::FormatterMatchType match_type)
TypeNameSpecifierImpl (lldb::TypeSP type)
TypeNameSpecifierImpl (CompilerType type)
const char * GetName ()
CompilerType GetCompilerType ()
lldb::FormatterMatchType GetMatchType ()
bool IsRegex ()
Private Member Functions
TypeNameSpecifierImpl (const TypeNameSpecifierImpl &)=delete
const TypeNameSpecifierImpl & operator= (const TypeNameSpecifierImpl &)=delete
Private Attributes
lldb::FormatterMatchType m_match_type = lldb::eFormatterMatchExact
TypeOrName m_type
Detailed Description
Definition at line 152 of file FormatClasses.h.
Constructor & Destructor Documentation
TypeNameSpecifierImpl() [1/5]
lldb_private::TypeNameSpecifierImpl::TypeNameSpecifierImpl () default
Referenced by operator=(), and TypeNameSpecifierImpl().
TypeNameSpecifierImpl() [2/5]
lldb_private::TypeNameSpecifierImpl::TypeNameSpecifierImpl (llvm::StringRef name, lldb::FormatterMatchType match_type) inline
Definition at line 156 of file FormatClasses.h.
References m_match_type, and m_type.
TypeNameSpecifierImpl() [3/5]
lldb_private::TypeNameSpecifierImpl::TypeNameSpecifierImpl (lldb::TypeSP type) inline
Definition at line 163 of file FormatClasses.h.
References m_match_type, and m_type.
TypeNameSpecifierImpl() [4/5]
lldb_private::TypeNameSpecifierImpl::TypeNameSpecifierImpl (CompilerType type) inline
Definition at line 171 of file FormatClasses.h.
References lldb_private::CompilerType::IsValid(), and m_match_type.
TypeNameSpecifierImpl() [5/5]
lldb_private::TypeNameSpecifierImpl::TypeNameSpecifierImpl (const TypeNameSpecifierImpl &) private delete
References TypeNameSpecifierImpl().
Member Function Documentation
GetCompilerType()
CompilerType lldb_private::TypeNameSpecifierImpl::GetCompilerType () inline
Definition at line 185 of file FormatClasses.h.
References m_type.
GetMatchType()
lldb::FormatterMatchType lldb_private::TypeNameSpecifierImpl::GetMatchType () inline
Definition at line 191 of file FormatClasses.h.
References m_match_type.
GetName()
const char * lldb_private::TypeNameSpecifierImpl::GetName () inline
Definition at line 179 of file FormatClasses.h.
References m_type.
IsRegex()
bool lldb_private::TypeNameSpecifierImpl::IsRegex () inline
Definition at line 193 of file FormatClasses.h.
References lldb::eFormatterMatchRegex, and m_match_type.
operator=()
const TypeNameSpecifierImpl & lldb_private::TypeNameSpecifierImpl::operator= (const TypeNameSpecifierImpl &) private delete
References TypeNameSpecifierImpl().
Member Data Documentation
m_match_type
lldb::FormatterMatchType lldb_private::TypeNameSpecifierImpl::m_match_type = lldb::eFormatterMatchExact private
Definition at line 196 of file FormatClasses.h.
Referenced by GetMatchType(), IsRegex(), TypeNameSpecifierImpl(), TypeNameSpecifierImpl(), and TypeNameSpecifierImpl().
m_type
TypeOrName lldb_private::TypeNameSpecifierImpl::m_type private
Definition at line 202 of file FormatClasses.h.
Referenced by GetCompilerType(), GetName(), TypeNameSpecifierImpl(), and TypeNameSpecifierImpl().
The documentation for this class was generated from the following file:
FormatClasses.h