LLDB: lldb::SBThreadCollection Class Reference
lldb::SBThreadCollection Class Reference
#include <SBThreadCollection.h>
Public Member Functions
SBThreadCollection ()
SBThreadCollection (const SBThreadCollection &rhs)
const SBThreadCollection & operator= (const SBThreadCollection &rhs)
~SBThreadCollection ()
operator bool () const
bool IsValid () const
size_t GetSize ()
lldb::SBThread GetThreadAtIndex (size_t idx)
Protected Member Functions
lldb_private::ThreadCollection * get () const
lldb_private::ThreadCollection * operator-> () const
lldb::ThreadCollectionSP & operator* ()
const lldb::ThreadCollectionSP & operator* () const
SBThreadCollection (const lldb::ThreadCollectionSP &threads)
void SetOpaque (const lldb::ThreadCollectionSP &threads)
Private Attributes
lldb::ThreadCollectionSP m_opaque_sp
Friends
class SBTarget
class SBProcess
class SBThread
class SBSaveCoreOptions
Detailed Description
Definition at line 16 of file SBThreadCollection.h.
Constructor & Destructor Documentation
SBThreadCollection() [1/3]
SBThreadCollection::SBThreadCollection ()
Definition at line 17 of file SBThreadCollection.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by operator=(), SBThreadCollection(), and ~SBThreadCollection().
SBThreadCollection() [2/3]
SBThreadCollection::SBThreadCollection (const SBThreadCollection & rhs)
Definition at line 19 of file SBThreadCollection.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBThreadCollection().
~SBThreadCollection()
SBThreadCollection::~SBThreadCollection () default
References get(), GetSize(), GetThreadAtIndex(), IsValid(), operator*(), operator->(), SBThreadCollection(), and SetOpaque().
SBThreadCollection() [3/3]
SBThreadCollection::SBThreadCollection (const lldb::ThreadCollectionSP & threads) protected
Definition at line 33 of file SBThreadCollection.cpp.
References m_opaque_sp.
Member Function Documentation
get()
lldb_private::ThreadCollection * SBThreadCollection::get () const protected
Definition at line 42 of file SBThreadCollection.cpp.
References m_opaque_sp.
Referenced by ~SBThreadCollection().
GetSize()
size_t SBThreadCollection::GetSize ()
Definition at line 68 of file SBThreadCollection.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by GetThreadAtIndex(), and ~SBThreadCollection().
GetThreadAtIndex()
SBThread SBThreadCollection::GetThreadAtIndex (size_t idx)
Definition at line 76 of file SBThreadCollection.cpp.
References GetSize(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBThread.
Referenced by ~SBThreadCollection().
IsValid()
bool SBThreadCollection::IsValid () const
Definition at line 58 of file SBThreadCollection.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBThreadCollection().
operator bool()
SBThreadCollection::operator bool () const explicit
Definition at line 62 of file SBThreadCollection.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator*() [1/2]
lldb::ThreadCollectionSP & SBThreadCollection::operator* () protected
Definition at line 50 of file SBThreadCollection.cpp.
References m_opaque_sp.
Referenced by ~SBThreadCollection().
operator*() [2/2]
const lldb::ThreadCollectionSP & SBThreadCollection::operator* () const protected
Definition at line 54 of file SBThreadCollection.cpp.
References m_opaque_sp.
operator->()
lldb_private::ThreadCollection * SBThreadCollection::operator-> () const protected
Definition at line 46 of file SBThreadCollection.cpp.
References m_opaque_sp.
Referenced by ~SBThreadCollection().
operator=()
const SBThreadCollection & SBThreadCollection::operator= (const SBThreadCollection & rhs)
Definition at line 24 of file SBThreadCollection.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBThreadCollection().
SetOpaque()
void SBThreadCollection::SetOpaque (const lldb::ThreadCollectionSP & threads) protected
Definition at line 38 of file SBThreadCollection.cpp.
References m_opaque_sp.
Referenced by ~SBThreadCollection().
Friends And Related Symbol Documentation
SBProcess
friend class SBProcess friend
Definition at line 50 of file SBThreadCollection.h.
References SBProcess.
Referenced by SBProcess.
SBSaveCoreOptions
friend class SBSaveCoreOptions friend
Definition at line 52 of file SBThreadCollection.h.
References SBSaveCoreOptions.
Referenced by SBSaveCoreOptions.
SBTarget
friend class SBTarget friend
Definition at line 49 of file SBThreadCollection.h.
References SBTarget.
Referenced by SBTarget.
SBThread
friend class SBThread friend
Definition at line 51 of file SBThreadCollection.h.
References SBThread.
Referenced by GetThreadAtIndex(), and SBThread.
Member Data Documentation
m_opaque_sp
lldb::ThreadCollectionSP lldb::SBThreadCollection::m_opaque_sp private
Definition at line 53 of file SBThreadCollection.h.
Referenced by get(), GetSize(), GetThreadAtIndex(), operator bool(), operator*(), operator*(), operator->(), operator=(), SBThreadCollection(), SBThreadCollection(), and SetOpaque().
The documentation for this class was generated from the following files:
SBThreadCollection.h
SBThreadCollection.cpp