LLDB: lldb_private::Section Class Reference
lldb_private::Section Class Reference
#include <Section.h>
Public Member Functions
Section (const lldb::ModuleSP &module_sp, ObjectFile *obj_file, lldb::user_id_t sect_id, ConstString name, lldb::SectionType sect_type, lldb::addr_t file_vm_addr, lldb::addr_t vm_size, lldb::offset_t file_offset, lldb::offset_t file_size, uint32_t log2align, uint32_t flags)
Section (const lldb::SectionSP &parent_section_sp, const lldb::ModuleSP &module_sp, ObjectFile *obj_file, lldb::user_id_t sect_id, ConstString name, lldb::SectionType sect_type, lldb::addr_t file_vm_addr, lldb::addr_t vm_size, lldb::offset_t file_offset, lldb::offset_t file_size, uint32_t log2align, uint32_t flags)
~Section ()
bool ContainsFileAddress (lldb::addr_t vm_addr) const
SectionList & GetChildren ()
const SectionList & GetChildren () const
void Dump (llvm::raw_ostream &s, unsigned indent, Target *target, uint32_t depth) const
void DumpName (llvm::raw_ostream &s) const
lldb::addr_t GetLoadBaseAddress (Target *target) const
bool ResolveContainedAddress (lldb::addr_t offset, Address &so_addr, bool allow_section_end=false) const
lldb::offset_t GetFileOffset () const
void SetFileOffset (lldb::offset_t file_offset)
lldb::offset_t GetFileSize () const
void SetFileSize (lldb::offset_t file_size)
lldb::addr_t GetFileAddress () const
bool SetFileAddress (lldb::addr_t file_addr)
lldb::addr_t GetOffset () const
lldb::addr_t GetByteSize () const
void SetByteSize (lldb::addr_t byte_size)
bool IsFake () const
void SetIsFake (bool fake)
bool IsEncrypted () const
void SetIsEncrypted (bool b)
bool IsDescendant (const Section *section)
ConstString GetName () const
bool Slide (lldb::addr_t slide_amount, bool slide_children)
lldb::SectionType GetType () const
const char * GetTypeAsCString () const
lldb::SectionSP GetParent () const
bool IsThreadSpecific () const
void SetIsThreadSpecific (bool b)
uint32_t GetPermissions () const
Get the permissions as OR'ed bits from lldb::Permissions.
void SetPermissions (uint32_t permissions)
Set the permissions using bits OR'ed from lldb::Permissions.
ObjectFile * GetObjectFile ()
const ObjectFile * GetObjectFile () const
lldb::offset_t GetSectionData (void *dst, lldb::offset_t dst_len, lldb::offset_t offset=0)
Read the section data from the object file that the section resides in.
lldb::offset_t GetSectionData (DataExtractor &data)
Get the shared reference to the section data from the object file that the section resides in.
uint32_t GetLog2Align ()
void SetLog2Align (uint32_t align)
bool IsRelocated () const
void SetIsRelocated (bool b)
bool ContainsOnlyDebugInfo () const
Returns true if this section contains debug information.
bool IsGOTSection () const
Returns true if this is a global offset table section.
Public Member Functions inherited from lldb_private::ModuleChild
ModuleChild (const lldb::ModuleSP &module_sp)
Construct with owning module.
~ModuleChild ()
Destructor.
const ModuleChild & operator= (const ModuleChild &rhs)
Assignment operator.
lldb::ModuleSP GetModule () const
Get const accessor for the module pointer.
void SetModule (const lldb::ModuleSP &module_sp)
Set accessor for the module pointer.
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Public Member Functions inherited from lldb_private::Flags
Flags (ValueType flags=0)
Construct with initial flag bit values.
ValueType Get () const
Get accessor for all flags.
size_t GetBitSize () const
Return the number of flags that can be represented in this object.
void Reset (ValueType flags)
Set accessor for all flags.
ValueType Clear (ValueType mask=~static_cast< ValueType >(0))
Clear one or more flags.
ValueType Set (ValueType mask)
Set one or more flags by logical OR'ing mask with the current flags.
bool AllSet (ValueType mask) const
Test if all bits in mask are 1 in the current flags.
bool AnySet (ValueType mask) const
Test one or more flags.
bool Test (ValueType bit) const
Test a single flag bit.
bool AllClear (ValueType mask) const
Test if all bits in mask are clear.
bool AnyClear (ValueType mask) const
bool IsClear (ValueType bit) const
Test a single flag bit to see if it is clear (zero).
Static Public Member Functions
static int Compare (const Section &a, const Section &b)
Protected Attributes
ObjectFile * m_obj_file
lldb::SectionType m_type
lldb::SectionWP m_parent_wp
ConstString m_name
lldb::addr_t m_file_addr
lldb::addr_t m_byte_size
lldb::offset_t m_file_offset
lldb::offset_t m_file_size
uint32_t m_log2align
SectionList m_children
bool m_fake: 1
bool m_encrypted: 1
bool m_thread_specific: 1
bool m_readable: 1
bool m_writable: 1
bool m_executable: 1
bool m_relocated: 1
Protected Attributes inherited from lldb_private::ModuleChild
lldb::ModuleWP m_module_wp
The Module that owns the object that inherits from this class.
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Protected Attributes inherited from lldb_private::Flags
ValueType m_flags
The flags.
Private Member Functions
Section (const Section &)=delete
const Section & operator= (const Section &)=delete
Additional Inherited Members
Public Types inherited from lldb_private::Flags
typedef uint32_t ValueType
The value type for flags is a 32 bit unsigned integer type.
Detailed Description
Definition at line 139 of file Section.h.
Constructor & Destructor Documentation
Section() [1/3]
Section::Section (const lldb::ModuleSP & module_sp, ObjectFile * obj_file, lldb::user_id_t sect_id, ConstString name, lldb::SectionType sect_type, lldb::addr_t file_vm_addr, lldb::addr_t vm_size, lldb::offset_t file_offset, lldb::offset_t file_size, uint32_t log2align, uint32_t flags)
Definition at line 164 of file Section.cpp.
References lldb_private::Flags::Flags(), m_byte_size, m_children, m_encrypted, m_executable, m_fake, m_file_addr, m_file_offset, m_file_size, m_log2align, m_name, m_obj_file, m_parent_wp, m_readable, m_relocated, m_thread_specific, m_type, m_writable, lldb_private::ModuleChild::ModuleChild(), and lldb_private::UserID::UserID().
Referenced by Compare(), GetLoadBaseAddress(), IsDescendant(), operator=(), ResolveContainedAddress(), and Section().
Section() [2/3]
Section::Section (const lldb::SectionSP & parent_section_sp, const lldb::ModuleSP & module_sp, ObjectFile * obj_file, lldb::user_id_t sect_id, ConstString name, lldb::SectionType sect_type, lldb::addr_t file_vm_addr, lldb::addr_t vm_size, lldb::offset_t file_offset, lldb::offset_t file_size, uint32_t log2align, uint32_t flags)
Definition at line 176 of file Section.cpp.
References lldb_private::Flags::Flags(), m_byte_size, m_children, m_encrypted, m_executable, m_fake, m_file_addr, m_file_offset, m_file_size, m_log2align, m_name, m_obj_file, m_parent_wp, m_readable, m_relocated, m_thread_specific, m_type, m_writable, lldb_private::ModuleChild::ModuleChild(), and lldb_private::UserID::UserID().
~Section()
Section::~Section () default
Section() [3/3]
lldb_private::Section::Section (const Section &) private delete
References Section().
Member Function Documentation
Compare()
int lldb_private::Section::Compare (const Section & a, const Section & b) static
References Section().
ContainsFileAddress()
bool Section::ContainsFileAddress (lldb::addr_t vm_addr) const
Definition at line 265 of file Section.cpp.
References GetByteSize(), GetFileAddress(), IsThreadSpecific(), and LLDB_INVALID_ADDRESS.
Referenced by lldb_private::SectionList::FindSectionContainingFileAddress().
ContainsOnlyDebugInfo()
bool Section::ContainsOnlyDebugInfo () const
Returns true if this section contains debug information.
Symbol tables are not considered debug information since some symbols might contain debug information (STABS, COFF) but not all symbols do, so to keep this fast and simple only sections that contains only debug information should return true.
Definition at line 390 of file Section.cpp.
References lldb::eSectionTypeAbsoluteAddress, lldb::eSectionTypeARMexidx, lldb::eSectionTypeARMextab, lldb::eSectionTypeCode, lldb::eSectionTypeCompactUnwind, lldb::eSectionTypeContainer, lldb::eSectionTypeCTF, lldb::eSectionTypeData, lldb::eSectionTypeData16, lldb::eSectionTypeData4, lldb::eSectionTypeData8, lldb::eSectionTypeDataCString, lldb::eSectionTypeDataCStringPointers, lldb::eSectionTypeDataObjCCFStrings, lldb::eSectionTypeDataObjCMessageRefs, lldb::eSectionTypeDataPointers, lldb::eSectionTypeDataSymbolAddress, lldb::eSectionTypeDebug, lldb::eSectionTypeDWARFAppleNames, lldb::eSectionTypeDWARFAppleNamespaces, lldb::eSectionTypeDWARFAppleObjC, lldb::eSectionTypeDWARFAppleTypes, lldb::eSectionTypeDWARFDebugAbbrev, lldb::eSectionTypeDWARFDebugAbbrevDwo, lldb::eSectionTypeDWARFDebugAddr, lldb::eSectionTypeDWARFDebugAranges, lldb::eSectionTypeDWARFDebugCuIndex, lldb::eSectionTypeDWARFDebugFrame, lldb::eSectionTypeDWARFDebugInfo, lldb::eSectionTypeDWARFDebugInfoDwo, lldb::eSectionTypeDWARFDebugLine, lldb::eSectionTypeDWARFDebugLineStr, lldb::eSectionTypeDWARFDebugLoc, lldb::eSectionTypeDWARFDebugLocDwo, lldb::eSectionTypeDWARFDebugLocLists, lldb::eSectionTypeDWARFDebugLocListsDwo, lldb::eSectionTypeDWARFDebugMacInfo, lldb::eSectionTypeDWARFDebugMacro, lldb::eSectionTypeDWARFDebugNames, lldb::eSectionTypeDWARFDebugPubNames, lldb::eSectionTypeDWARFDebugPubTypes, lldb::eSectionTypeDWARFDebugRanges, lldb::eSectionTypeDWARFDebugRngLists, lldb::eSectionTypeDWARFDebugRngListsDwo, lldb::eSectionTypeDWARFDebugStr, lldb::eSectionTypeDWARFDebugStrDwo, lldb::eSectionTypeDWARFDebugStrOffsets, lldb::eSectionTypeDWARFDebugStrOffsetsDwo, lldb::eSectionTypeDWARFDebugTuIndex, lldb::eSectionTypeDWARFDebugTypes, lldb::eSectionTypeDWARFDebugTypesDwo, lldb::eSectionTypeDWARFGNUDebugAltLink, lldb::eSectionTypeEHFrame, lldb::eSectionTypeELFDynamicLinkInfo, lldb::eSectionTypeELFDynamicSymbols, lldb::eSectionTypeELFRelocationEntries, lldb::eSectionTypeELFSymbolTable, lldb::eSectionTypeGoSymtab, lldb::eSectionTypeInvalid, lldb::eSectionTypeLLDBFormatters, lldb::eSectionTypeLLDBTypeSummaries, lldb::eSectionTypeOther, lldb::eSectionTypeSwiftModules, lldb::eSectionTypeWasmName, lldb::eSectionTypeZeroFill, and m_type.
Dump()
void Section::Dump (llvm::raw_ostream & s, unsigned indent, Target * target, uint32_t depth) const
Definition at line 276 of file Section.cpp.
References lldb_private::VMRange::Dump(), DumpName(), lldb_private::Flags::Get(), GetByteSize(), GetFileAddress(), lldb_private::UserID::GetID(), GetLoadBaseAddress(), GetTypeAsCString(), LLDB_INVALID_ADDRESS, m_byte_size, m_children, m_executable, m_file_offset, m_file_size, m_readable, and m_writable.
DumpName()
void Section::DumpName (llvm::raw_ostream & s) const
Definition at line 312 of file Section.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::FileSpec::GetFilename(), lldb_private::ModuleChild::GetModule(), GetParent(), m_name, and m_obj_file.
Referenced by Dump().
GetByteSize()
lldb::addr_t lldb_private::Section::GetByteSize () const inline
Definition at line 197 of file Section.h.
References m_byte_size.
Referenced by ContainsFileAddress(), ProcessMachCore::CreateMemoryRegions(), Dump(), ObjectFilePECOFF::GetSectionDataSize(), lldb_private::ObjectFile::ReadSectionData(), lldb_private::ObjectFile::ReadSectionData(), and ResolveContainedAddress().
GetChildren() [1/2]
SectionList & lldb_private::Section::GetChildren () inline
Definition at line 167 of file Section.h.
References m_children.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::CalculateAbilities(), lldb_private::SectionList::FindSectionByName(), and lldb_private::SectionList::FindSectionContainingFileAddress().
GetChildren() [2/2]
const SectionList & lldb_private::Section::GetChildren () const inline
Definition at line 169 of file Section.h.
References m_children.
GetFileAddress()
addr_t Section::GetFileAddress () const
Definition at line 194 of file Section.cpp.
References GetParent(), and m_file_addr.
Referenced by ObjectFileMachO::CalculateSectionLoadAddressForMemoryImage(), ContainsFileAddress(), ProcessMachCore::CreateMemoryRegions(), Dump(), DynamicLoaderDarwinKernel::KextImageInfo::LoadImageUsingMemoryModule(), and DynamicLoaderFreeBSDKernel::KModImageInfo::LoadImageUsingMemoryModule().
GetFileOffset()
lldb::offset_t lldb_private::Section::GetFileOffset () const inline
Definition at line 181 of file Section.h.
References m_file_offset.
Referenced by lldb_private::DynamicLoaderDarwin::AddModulesUsingPreloadedModules(), ApplyELF32ABS32RelRelocation(), ApplyELF64ABS32Relocation(), ApplyELF64ABS64Relocation(), ObjectFileELF::ApplyRelocations(), ProcessMachCore::CreateMemoryRegions(), ObjectFileMachO::GetMachHeaderSection(), lldb_private::ObjectFile::ReadSectionData(), lldb_private::ObjectFile::ReadSectionData(), lldb_private::ObjectFileJIT::ReadSectionData(), lldb_private::ObjectFileJIT::ReadSectionData(), and ObjectFileELF::RelocateDebugSections().
GetFileSize()
lldb::offset_t lldb_private::Section::GetFileSize () const inline
Definition at line 187 of file Section.h.
References m_file_size.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::CalculateAbilities(), ProcessMachCore::CreateMemoryRegions(), lldb_private::ObjectFile::GetSectionDataSize(), ObjectFilePECOFF::GetSectionDataSize(), lldb_private::ObjectFile::ReadSectionData(), lldb_private::ObjectFileJIT::ReadSectionData(), lldb_private::ObjectFileJIT::ReadSectionData(), and ObjectFileELF::RelocateDebugSections().
GetLoadBaseAddress()
addr_t Section::GetLoadBaseAddress (Target * target) const
Definition at line 229 of file Section.cpp.
References GetOffset(), GetParent(), lldb_private::Target::GetSectionLoadAddress(), LLDB_INVALID_ADDRESS, and Section().
Referenced by Dump(), lldb_private::ObjectFile::ReadSectionData(), and lldb_private::ObjectFile::ReadSectionData().
GetLog2Align()
uint32_t lldb_private::Section::GetLog2Align () inline
Definition at line 269 of file Section.h.
References m_log2align.
GetName()
ConstString lldb_private::Section::GetName () const inline
Definition at line 211 of file Section.h.
References m_name.
Referenced by ObjectFileELF::ApplyRelocations(), lldb_private::SectionList::FindSectionByName(), ObjectFileMachO::IsGOTSection(), lldb_private::breakpad::SymbolFileBreakpad::LineIterator::LineIterator(), lldb_private::breakpad::SymbolFileBreakpad::LineIterator::operator++(), ObjectFileELF::ReadSectionData(), ObjectFileELF::RelocateSection(), elf::ELFSymbol::sectionIndexToCString(), and ObjectFileMachO::SectionIsLoadable().
GetObjectFile() [1/2]
ObjectFile * lldb_private::Section::GetObjectFile () inline
Definition at line 231 of file Section.h.
References m_obj_file.
Referenced by lldb_private::ObjectFile::IsGOTSection(), IsGOTSection(), ObjectFileMachO::IsGOTSection(), ObjectFileELF::ParseSymbolTable(), lldb_private::ObjectFile::ReadSectionData(), lldb_private::ObjectFile::ReadSectionData(), ObjectFileELF::ReadSectionData(), and ObjectFileELF::ReadSectionData().
GetObjectFile() [2/2]
const ObjectFile * lldb_private::Section::GetObjectFile () const inline
Definition at line 232 of file Section.h.
References m_obj_file.
GetOffset()
lldb::addr_t Section::GetOffset () const
Definition at line 219 of file Section.cpp.
References GetParent(), and m_file_addr.
Referenced by GetLoadBaseAddress(), and ResolveContainedAddress().
GetParent()
lldb::SectionSP lldb_private::Section::GetParent () const inline
Definition at line 219 of file Section.h.
References m_parent_wp.
Referenced by DumpName(), GetFileAddress(), GetLoadBaseAddress(), GetOffset(), IsDescendant(), ObjectFileMachO::IsGOTSection(), and SetFileAddress().
GetPermissions()
uint32_t Section::GetPermissions () const
Get the permissions as OR'ed bits from lldb::Permissions.
Definition at line 359 of file Section.cpp.
References m_executable, m_readable, and m_writable.
Referenced by ProcessMachCore::CreateMemoryRegions().
GetSectionData() [1/2]
lldb::offset_t Section::GetSectionData (DataExtractor & data)
Get the shared reference to the section data from the object file that the section resides in.
No copies of the data will be make unless the object file has been read from memory. If the object file is on disk, it will shared the mmap data for the entire object file.
Parameters
[in] data Where to place the data, address byte size, and byte order
Returns
The number of bytes read from the section, or zero if the section has no data or offset is not a valid offset in this section.
Definition at line 384 of file Section.cpp.
References m_obj_file.
GetSectionData() [2/2]
lldb::offset_t Section::GetSectionData (void * dst, lldb::offset_t dst_len, lldb::offset_t offset = 0)
Read the section data from the object file that the section resides in.
Parameters
[in] dst Where to place the data
[in] dst_len How many bytes of section data to read
[in] offset The offset in bytes within this section's data at which to start copying data from.
Returns
The number of bytes read from the section, or zero if the section has no data or offset is not a valid offset in this section.
Definition at line 377 of file Section.cpp.
References m_obj_file.
GetType()
lldb::SectionType lldb_private::Section::GetType () const inline
Definition at line 215 of file Section.h.
References m_type.
Referenced by lldb_private::ObjectFile::ReadSectionData().
GetTypeAsCString()
const char * Section::GetTypeAsCString () const
Definition at line 28 of file Section.cpp.
References lldb::eSectionTypeAbsoluteAddress, lldb::eSectionTypeARMexidx, lldb::eSectionTypeARMextab, lldb::eSectionTypeCode, lldb::eSectionTypeCompactUnwind, lldb::eSectionTypeContainer, lldb::eSectionTypeCTF, lldb::eSectionTypeData, lldb::eSectionTypeData16, lldb::eSectionTypeData4, lldb::eSectionTypeData8, lldb::eSectionTypeDataCString, lldb::eSectionTypeDataCStringPointers, lldb::eSectionTypeDataObjCCFStrings, lldb::eSectionTypeDataObjCMessageRefs, lldb::eSectionTypeDataPointers, lldb::eSectionTypeDataSymbolAddress, lldb::eSectionTypeDebug, lldb::eSectionTypeDWARFAppleNames, lldb::eSectionTypeDWARFAppleNamespaces, lldb::eSectionTypeDWARFAppleObjC, lldb::eSectionTypeDWARFAppleTypes, lldb::eSectionTypeDWARFDebugAbbrev, lldb::eSectionTypeDWARFDebugAbbrevDwo, lldb::eSectionTypeDWARFDebugAddr, lldb::eSectionTypeDWARFDebugAranges, lldb::eSectionTypeDWARFDebugCuIndex, lldb::eSectionTypeDWARFDebugFrame, lldb::eSectionTypeDWARFDebugInfo, lldb::eSectionTypeDWARFDebugInfoDwo, lldb::eSectionTypeDWARFDebugLine, lldb::eSectionTypeDWARFDebugLineStr, lldb::eSectionTypeDWARFDebugLoc, lldb::eSectionTypeDWARFDebugLocDwo, lldb::eSectionTypeDWARFDebugLocLists, lldb::eSectionTypeDWARFDebugLocListsDwo, lldb::eSectionTypeDWARFDebugMacInfo, lldb::eSectionTypeDWARFDebugMacro, lldb::eSectionTypeDWARFDebugNames, lldb::eSectionTypeDWARFDebugPubNames, lldb::eSectionTypeDWARFDebugPubTypes, lldb::eSectionTypeDWARFDebugRanges, lldb::eSectionTypeDWARFDebugRngLists, lldb::eSectionTypeDWARFDebugRngListsDwo, lldb::eSectionTypeDWARFDebugStr, lldb::eSectionTypeDWARFDebugStrDwo, lldb::eSectionTypeDWARFDebugStrOffsets, lldb::eSectionTypeDWARFDebugStrOffsetsDwo, lldb::eSectionTypeDWARFDebugTuIndex, lldb::eSectionTypeDWARFDebugTypes, lldb::eSectionTypeDWARFDebugTypesDwo, lldb::eSectionTypeDWARFGNUDebugAltLink, lldb::eSectionTypeEHFrame, lldb::eSectionTypeELFDynamicLinkInfo, lldb::eSectionTypeELFDynamicSymbols, lldb::eSectionTypeELFRelocationEntries, lldb::eSectionTypeELFSymbolTable, lldb::eSectionTypeGoSymtab, lldb::eSectionTypeInvalid, lldb::eSectionTypeLLDBFormatters, lldb::eSectionTypeLLDBTypeSummaries, lldb::eSectionTypeOther, lldb::eSectionTypeSwiftModules, lldb::eSectionTypeWasmName, lldb::eSectionTypeZeroFill, and m_type.
Referenced by Dump().
IsDescendant()
bool Section::IsDescendant (const Section * section)
Definition at line 334 of file Section.cpp.
References GetParent(), and Section().
IsEncrypted()
bool lldb_private::Section::IsEncrypted () const inline
Definition at line 205 of file Section.h.
References m_encrypted.
IsFake()
bool lldb_private::Section::IsFake () const inline
Definition at line 201 of file Section.h.
References m_fake.
Referenced by lldb_private::SectionList::FindSectionContainingFileAddress().
IsGOTSection()
bool Section::IsGOTSection () const
Returns true if this is a global offset table section.
Definition at line 470 of file Section.cpp.
References GetObjectFile(), and lldb_private::ObjectFile::IsGOTSection().
IsRelocated()
bool lldb_private::Section::IsRelocated () const inline
Definition at line 273 of file Section.h.
References m_relocated.
Referenced by lldb_private::ObjectFile::ReadSectionData(), and lldb_private::ObjectFile::ReadSectionData().
IsThreadSpecific()
bool lldb_private::Section::IsThreadSpecific () const inline
Definition at line 221 of file Section.h.
References m_thread_specific.
Referenced by ContainsFileAddress(), and ObjectFileMachO::SectionIsLoadable().
operator=()
const Section & lldb_private::Section::operator= (const Section &) private delete
References Section().
ResolveContainedAddress()
bool Section::ResolveContainedAddress (lldb::addr_t offset, Address & so_addr, bool allow_section_end = false) const
Definition at line 244 of file Section.cpp.
References GetByteSize(), lldb_private::ModuleChild::GetModule(), GetOffset(), m_children, ResolveContainedAddress(), Section(), lldb_private::Address::SetOffset(), and lldb_private::Address::SetSection().
Referenced by ResolveContainedAddress().
SetByteSize()
void lldb_private::Section::SetByteSize (lldb::addr_t byte_size) inline
Definition at line 199 of file Section.h.
References m_byte_size.
SetFileAddress()
bool Section::SetFileAddress (lldb::addr_t file_addr)
Definition at line 206 of file Section.cpp.
References GetParent(), and m_file_addr.
SetFileOffset()
void lldb_private::Section::SetFileOffset (lldb::offset_t file_offset) inline
Definition at line 183 of file Section.h.
References m_file_offset.
SetFileSize()
void lldb_private::Section::SetFileSize (lldb::offset_t file_size) inline
Definition at line 189 of file Section.h.
References m_file_size.
SetIsEncrypted()
void lldb_private::Section::SetIsEncrypted (bool b) inline
Definition at line 207 of file Section.h.
References m_encrypted.
SetIsFake()
void lldb_private::Section::SetIsFake (bool fake) inline
Definition at line 203 of file Section.h.
References m_fake.
SetIsRelocated()
void lldb_private::Section::SetIsRelocated (bool b) inline
Definition at line 275 of file Section.h.
References m_relocated.
Referenced by ObjectFileELF::RelocateSection().
SetIsThreadSpecific()
void lldb_private::Section::SetIsThreadSpecific (bool b) inline
Definition at line 223 of file Section.h.
References m_thread_specific.
SetLog2Align()
void lldb_private::Section::SetLog2Align (uint32_t align) inline
Definition at line 271 of file Section.h.
References m_log2align.
SetPermissions()
void Section::SetPermissions (uint32_t permissions)
Set the permissions using bits OR'ed from lldb::Permissions.
Definition at line 371 of file Section.cpp.
References m_executable, m_readable, and m_writable.
Slide()
bool Section::Slide (lldb::addr_t slide_amount, bool slide_children)
Definition at line 343 of file Section.cpp.
References LLDB_INVALID_ADDRESS, m_children, and m_file_addr.
Member Data Documentation
m_byte_size
lldb::addr_t lldb_private::Section::m_byte_size protected
Definition at line 296 of file Section.h.
Referenced by Dump(), GetByteSize(), Section(), Section(), and SetByteSize().
m_children
SectionList lldb_private::Section::m_children protected
Definition at line 303 of file Section.h.
Referenced by Dump(), GetChildren(), GetChildren(), ResolveContainedAddress(), Section(), Section(), and Slide().
m_encrypted
bool lldb_private::Section::m_encrypted protected
Definition at line 309 of file Section.h.
Referenced by IsEncrypted(), Section(), Section(), and SetIsEncrypted().
m_executable
bool lldb_private::Section::m_executable protected
Definition at line 313 of file Section.h.
Referenced by Dump(), GetPermissions(), Section(), Section(), and SetPermissions().
m_fake
bool lldb_private::Section::m_fake protected
Definition at line 304 of file Section.h.
Referenced by IsFake(), Section(), Section(), and SetIsFake().
m_file_addr
lldb::addr_t lldb_private::Section::m_file_addr protected
Definition at line 293 of file Section.h.
Referenced by GetFileAddress(), GetOffset(), Section(), Section(), SetFileAddress(), and Slide().
m_file_offset
lldb::offset_t lldb_private::Section::m_file_offset protected
Definition at line 298 of file Section.h.
Referenced by Dump(), GetFileOffset(), Section(), Section(), and SetFileOffset().
m_file_size
lldb::offset_t lldb_private::Section::m_file_size protected
Definition at line 299 of file Section.h.
Referenced by Dump(), GetFileSize(), Section(), Section(), and SetFileSize().
m_log2align
uint32_t lldb_private::Section::m_log2align protected
Definition at line 301 of file Section.h.
Referenced by GetLog2Align(), Section(), Section(), and SetLog2Align().
m_name
ConstString lldb_private::Section::m_name protected
Definition at line 292 of file Section.h.
Referenced by DumpName(), GetName(), Section(), and Section().
m_obj_file
ObjectFile* lldb_private::Section::m_obj_file protected
Definition at line 288 of file Section.h.
Referenced by DumpName(), GetObjectFile(), GetObjectFile(), GetSectionData(), GetSectionData(), Section(), and Section().
m_parent_wp
lldb::SectionWP lldb_private::Section::m_parent_wp protected
Definition at line 291 of file Section.h.
Referenced by GetParent(), Section(), and Section().
m_readable
bool lldb_private::Section::m_readable protected
Definition at line 311 of file Section.h.
Referenced by Dump(), GetPermissions(), Section(), Section(), and SetPermissions().
m_relocated
bool lldb_private::Section::m_relocated protected
Definition at line 314 of file Section.h.
Referenced by IsRelocated(), Section(), Section(), and SetIsRelocated().
m_thread_specific
bool lldb_private::Section::m_thread_specific protected
Definition at line 310 of file Section.h.
Referenced by IsThreadSpecific(), Section(), Section(), and SetIsThreadSpecific().
m_type
lldb::SectionType lldb_private::Section::m_type protected
Definition at line 290 of file Section.h.
Referenced by ContainsOnlyDebugInfo(), GetType(), GetTypeAsCString(), Section(), and Section().
m_writable
bool lldb_private::Section::m_writable protected
Definition at line 312 of file Section.h.
Referenced by Dump(), GetPermissions(), Section(), Section(), and SetPermissions().
The documentation for this class was generated from the following files:
Section.h
Section.cpp