LLDB: RegisterContextOpenBSD_x86_64 Class Reference
RegisterContextOpenBSD_x86_64 Class Reference
#include <RegisterContextOpenBSD_x86_64.h>
Public Member Functions
RegisterContextOpenBSD_x86_64 (const lldb_private::ArchSpec &target_arch)
size_t GetGPRSize () const override
const lldb_private::RegisterInfo * GetRegisterInfo () const override
uint32_t GetRegisterCount () const override
Public Member Functions inherited from lldb_private::RegisterInfoInterface
RegisterInfoInterface (const lldb_private::ArchSpec &target_arch)
virtual ~RegisterInfoInterface ()=default
virtual uint32_t GetUserRegisterCount () const
const lldb_private::ArchSpec & GetTargetArchitecture () const
Private Attributes
const lldb_private::RegisterInfo * m_register_info_p
const uint32_t m_register_count
Detailed Description
Definition at line 14 of file RegisterContextOpenBSD_x86_64.h.
Constructor & Destructor Documentation
RegisterContextOpenBSD_x86_64()
RegisterContextOpenBSD_x86_64::RegisterContextOpenBSD_x86_64 (const lldb_private::ArchSpec & target_arch)
Definition at line 90 of file RegisterContextOpenBSD_x86_64.cpp.
References m_register_count, m_register_info_p, PrivateGetRegisterCount(), PrivateGetRegisterInfoPtr(), and lldb_private::RegisterInfoInterface::RegisterInfoInterface().
Member Function Documentation
GetGPRSize()
size_t RegisterContextOpenBSD_x86_64::GetGPRSize () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 96 of file RegisterContextOpenBSD_x86_64.cpp.
GetRegisterCount()
uint32_t RegisterContextOpenBSD_x86_64::GetRegisterCount () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 102 of file RegisterContextOpenBSD_x86_64.cpp.
References m_register_count.
GetRegisterInfo()
const RegisterInfo * RegisterContextOpenBSD_x86_64::GetRegisterInfo () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 98 of file RegisterContextOpenBSD_x86_64.cpp.
References m_register_info_p.
Member Data Documentation
m_register_count
const uint32_t RegisterContextOpenBSD_x86_64::m_register_count private
Definition at line 27 of file RegisterContextOpenBSD_x86_64.h.
Referenced by GetRegisterCount(), and RegisterContextOpenBSD_x86_64().
m_register_info_p
const lldb_private::RegisterInfo* RegisterContextOpenBSD_x86_64::m_register_info_p private
Definition at line 26 of file RegisterContextOpenBSD_x86_64.h.
Referenced by GetRegisterInfo(), and RegisterContextOpenBSD_x86_64().
The documentation for this class was generated from the following files:
RegisterContextOpenBSD_x86_64.h
RegisterContextOpenBSD_x86_64.cpp