LLDB: UnwindAssemblyInstEmulation Class Reference
UnwindAssemblyInstEmulation Class Reference
#include <UnwindAssemblyInstEmulation.h>
Classes
struct UnwindState
Public Member Functions
~UnwindAssemblyInstEmulation () override=default
bool GetNonCallSiteUnwindPlanFromAssembly (lldb_private::AddressRange &func, lldb_private::Thread &thread, lldb_private::UnwindPlan &unwind_plan) override
bool GetNonCallSiteUnwindPlanFromAssembly (lldb_private::AddressRange &func, uint8_t *opcode_data, size_t opcode_size, lldb_private::UnwindPlan &unwind_plan)
bool AugmentUnwindPlanFromCallSite (lldb_private::AddressRange &func, lldb_private::Thread &thread, lldb_private::UnwindPlan &unwind_plan) override
bool GetFastUnwindPlan (lldb_private::AddressRange &func, lldb_private::Thread &thread, lldb_private::UnwindPlan &unwind_plan) override
bool FirstNonPrologueInsn (lldb_private::AddressRange &func, const lldb_private::ExecutionContext &exe_ctx, lldb_private::Address &first_non_prologue_insn) override
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static lldb_private::UnwindAssembly * CreateInstance (const lldb_private::ArchSpec &arch)
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
Static Public Member Functions inherited from lldb_private::UnwindAssembly
static lldb::UnwindAssemblySP FindPlugin (const ArchSpec &arch)
Private Types
typedef std::map< uint64_t, lldb_private::RegisterValue > RegisterValueMap
typedef std::map< uint64_t, uint64_t > PushedRegisterToAddrMap
Private Member Functions
UnwindAssemblyInstEmulation (const lldb_private::ArchSpec &arch, lldb_private::EmulateInstruction *inst_emulator)
size_t WriteMemory (lldb_private::EmulateInstruction *instruction, const lldb_private::EmulateInstruction::Context &context, lldb::addr_t addr, const void *dst, size_t length)
bool ReadRegister (lldb_private::EmulateInstruction *instruction, const lldb_private::RegisterInfo *reg_info, lldb_private::RegisterValue &reg_value)
bool WriteRegister (lldb_private::EmulateInstruction *instruction, const lldb_private::EmulateInstruction::Context &context, const lldb_private::RegisterInfo *reg_info, const lldb_private::RegisterValue &reg_value)
void SetRegisterValue (const lldb_private::RegisterInfo &reg_info, const lldb_private::RegisterValue &reg_value)
bool GetRegisterValue (const lldb_private::RegisterInfo &reg_info, lldb_private::RegisterValue &reg_value)
Static Private Member Functions
static size_t ReadMemory (lldb_private::EmulateInstruction *instruction, void *baton, const lldb_private::EmulateInstruction::Context &context, lldb::addr_t addr, void *dst, size_t length)
static size_t WriteMemory (lldb_private::EmulateInstruction *instruction, void *baton, const lldb_private::EmulateInstruction::Context &context, lldb::addr_t addr, const void *dst, size_t length)
static bool ReadRegister (lldb_private::EmulateInstruction *instruction, void *baton, const lldb_private::RegisterInfo *reg_info, lldb_private::RegisterValue &reg_value)
static bool WriteRegister (lldb_private::EmulateInstruction *instruction, void *baton, const lldb_private::EmulateInstruction::Context &context, const lldb_private::RegisterInfo *reg_info, const lldb_private::RegisterValue &reg_value)
static uint64_t MakeRegisterKindValuePair (const lldb_private::RegisterInfo &reg_info)
Private Attributes
std::unique_ptr< lldb_private::EmulateInstruction > m_inst_emulator_up
lldb_private::AddressRange * m_range_ptr
lldb_private::UnwindPlan * m_unwind_plan_ptr
UnwindState m_state
uint64_t m_initial_cfa
PushedRegisterToAddrMap m_pushed_regs
bool m_curr_row_modified
int64_t m_branch_offset = 0
Additional Inherited Members
Protected Member Functions inherited from lldb_private::UnwindAssembly
UnwindAssembly (const ArchSpec &arch)
Protected Attributes inherited from lldb_private::UnwindAssembly
ArchSpec m_arch
Detailed Description
Definition at line 18 of file UnwindAssemblyInstEmulation.h.
Member Typedef Documentation
PushedRegisterToAddrMap
typedef std::map<uint64_t, uint64_t> UnwindAssemblyInstEmulation::PushedRegisterToAddrMap private
Definition at line 142 of file UnwindAssemblyInstEmulation.h.
RegisterValueMap
typedef std::map<uint64_t, lldb_private::RegisterValue> UnwindAssemblyInstEmulation::RegisterValueMap private
Definition at line 129 of file UnwindAssemblyInstEmulation.h.
Constructor & Destructor Documentation
~UnwindAssemblyInstEmulation()
UnwindAssemblyInstEmulation::~UnwindAssemblyInstEmulation () override default
UnwindAssemblyInstEmulation()
UnwindAssemblyInstEmulation::UnwindAssemblyInstEmulation (const lldb_private::ArchSpec & arch, lldb_private::EmulateInstruction * inst_emulator) inline private
Definition at line 63 of file UnwindAssemblyInstEmulation.h.
References lldb_private::UnwindAssembly::m_arch, m_curr_row_modified, m_initial_cfa, m_inst_emulator_up, m_range_ptr, m_unwind_plan_ptr, ReadMemory(), ReadRegister(), lldb_private::UnwindAssembly::UnwindAssembly(), WriteMemory(), and WriteRegister().
Referenced by CreateInstance(), GetNonCallSiteUnwindPlanFromAssembly(), ReadRegister(), WriteMemory(), and WriteRegister().
Member Function Documentation
AugmentUnwindPlanFromCallSite()
bool UnwindAssemblyInstEmulation::AugmentUnwindPlanFromCallSite (lldb_private::AddressRange & func, lldb_private::Thread & thread, lldb_private::UnwindPlan & unwind_plan) override virtual
Implements lldb_private::UnwindAssembly.
Definition at line 260 of file UnwindAssemblyInstEmulation.cpp.
CreateInstance()
UnwindAssembly * UnwindAssemblyInstEmulation::CreateInstance (const lldb_private::ArchSpec & arch) static
Definition at line 278 of file UnwindAssemblyInstEmulation.cpp.
References lldb_private::eInstructionTypePrologueEpilogue, lldb_private::EmulateInstruction::FindPlugin(), and UnwindAssemblyInstEmulation().
Referenced by Initialize(), and Terminate().
FirstNonPrologueInsn()
bool UnwindAssemblyInstEmulation::FirstNonPrologueInsn (lldb_private::AddressRange & func, const lldb_private::ExecutionContext & exe_ctx, lldb_private::Address & first_non_prologue_insn) override virtual
Implements lldb_private::UnwindAssembly.
Definition at line 271 of file UnwindAssemblyInstEmulation.cpp.
GetFastUnwindPlan()
bool UnwindAssemblyInstEmulation::GetFastUnwindPlan (lldb_private::AddressRange & func, lldb_private::Thread & thread, lldb_private::UnwindPlan & unwind_plan) override virtual
Implements lldb_private::UnwindAssembly.
Definition at line 265 of file UnwindAssemblyInstEmulation.cpp.
GetNonCallSiteUnwindPlanFromAssembly() [1/2]
bool UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly (lldb_private::AddressRange & func, lldb_private::Thread & thread, lldb_private::UnwindPlan & unwind_plan) override virtual
Implements lldb_private::UnwindAssembly.
Definition at line 38 of file UnwindAssemblyInstEmulation.cpp.
References error(), GetNonCallSiteUnwindPlanFromAssembly(), and UnwindAssemblyInstEmulation().
Referenced by GetNonCallSiteUnwindPlanFromAssembly().
GetNonCallSiteUnwindPlanFromAssembly() [2/2]
bool UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly (lldb_private::AddressRange & func, uint8_t * opcode_data, size_t opcode_size, lldb_private::UnwindPlan & unwind_plan)
Definition at line 82 of file UnwindAssemblyInstEmulation.cpp.
References lldb_private::AddressRange::ContainsFileAddress(), lldb_private::Disassembler::DisassembleBytes(), DumpInstToLog(), DumpUnwindRowsToLog(), lldb_private::Instruction::GetAddress(), lldb_private::AddressRange::GetBaseAddress(), lldb_private::AddressRange::GetByteSize(), lldb_private::Opcode::GetByteSize(), lldb_private::Address::GetFileAddress(), lldb_private::InstructionList::GetIndexOfInstructionAtAddress(), lldb_private::UnwindPlan::GetInitialCFARegister(), lldb_private::InstructionList::GetInstructionAtIndex(), lldb_private::UnwindPlan::GetLastRow(), lldb_private::GetLog(), lldb_private::Instruction::GetOpcode(), lldb_private::UnwindPlan::GetRegisterKind(), lldb_private::UnwindPlan::GetRowCount(), lldb_private::InstructionList::GetSize(), lldb_private::UnwindPlan::InsertRow(), lldb_private::Instruction::IsBarrier(), lldb_private::Address::IsValid(), lldb_private::UnwindAssembly::m_arch, m_branch_offset, m_curr_row_modified, m_initial_cfa, m_inst_emulator_up, m_pushed_regs, m_range_ptr, m_state, m_unwind_plan_ptr, SetRegisterValue(), lldb_private::RegisterValue::SetUInt(), lldb_private::Address::Slide(), lldb_private::EmulateInstruction::UnconditionalCondition, and lldb_private::Unwind.
GetPluginDescriptionStatic()
llvm::StringRef UnwindAssemblyInstEmulation::GetPluginDescriptionStatic () static
Definition at line 297 of file UnwindAssemblyInstEmulation.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef UnwindAssemblyInstEmulation::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 59 of file UnwindAssemblyInstEmulation.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef UnwindAssemblyInstEmulation::GetPluginNameStatic () inline static
Definition at line 55 of file UnwindAssemblyInstEmulation.h.
Referenced by GetPluginName(), and Initialize().
GetRegisterValue()
bool UnwindAssemblyInstEmulation::GetRegisterValue (const lldb_private::RegisterInfo & reg_info, lldb_private::RegisterValue & reg_value) private
Definition at line 316 of file UnwindAssemblyInstEmulation.cpp.
References lldb_private::RegisterInfo::byte_size, m_state, MakeRegisterKindValuePair(), and lldb_private::RegisterValue::SetUInt().
Referenced by ReadRegister(), and WriteRegister().
Initialize()
void UnwindAssemblyInstEmulation::Initialize () static
Definition at line 288 of file UnwindAssemblyInstEmulation.cpp.
References CreateInstance(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
MakeRegisterKindValuePair()
uint64_t UnwindAssemblyInstEmulation::MakeRegisterKindValuePair (const lldb_private::RegisterInfo & reg_info) static private
Definition at line 301 of file UnwindAssemblyInstEmulation.cpp.
References lldb_private::EmulateInstruction::GetBestRegisterKindAndNumber().
Referenced by GetRegisterValue(), and SetRegisterValue().
ReadMemory()
size_t UnwindAssemblyInstEmulation::ReadMemory (lldb_private::EmulateInstruction * instruction, void * baton, const lldb_private::EmulateInstruction::Context & context, lldb::addr_t addr, void * dst, size_t length) static private
Definition at line 330 of file UnwindAssemblyInstEmulation.cpp.
References lldb_private::EmulateInstruction::Context::Dump(), lldb_private::GetLog(), lldb_private::StreamString::GetString(), lldb_private::Log::GetVerbose(), lldb_private::Stream::Printf(), lldb_private::Log::PutString(), and lldb_private::Unwind.
Referenced by UnwindAssemblyInstEmulation().
ReadRegister() [1/2]
bool UnwindAssemblyInstEmulation::ReadRegister (lldb_private::EmulateInstruction * instruction, const lldb_private::RegisterInfo * reg_info, lldb_private::RegisterValue & reg_value) private
Definition at line 439 of file UnwindAssemblyInstEmulation.cpp.
References lldb_private::DumpRegisterValue(), lldb::eFormatDefault, lldb_private::GetLog(), GetRegisterValue(), lldb_private::StreamString::GetString(), lldb_private::Log::GetVerbose(), lldb_private::RegisterInfo::name, lldb_private::Stream::Printf(), lldb_private::Log::PutString(), and lldb_private::Unwind.
ReadRegister() [2/2]
bool UnwindAssemblyInstEmulation::ReadRegister (lldb_private::EmulateInstruction * instruction, void * baton, const lldb_private::RegisterInfo * reg_info, lldb_private::RegisterValue & reg_value) static private
Definition at line 429 of file UnwindAssemblyInstEmulation.cpp.
References UnwindAssemblyInstEmulation().
Referenced by UnwindAssemblyInstEmulation().
SetRegisterValue()
void UnwindAssemblyInstEmulation::SetRegisterValue (const lldb_private::RegisterInfo & reg_info, const lldb_private::RegisterValue & reg_value) private
Definition at line 311 of file UnwindAssemblyInstEmulation.cpp.
References m_state, and MakeRegisterKindValuePair().
Referenced by GetNonCallSiteUnwindPlanFromAssembly(), and WriteRegister().
Terminate()
void UnwindAssemblyInstEmulation::Terminate () static
Definition at line 293 of file UnwindAssemblyInstEmulation.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
WriteMemory() [1/2]
size_t UnwindAssemblyInstEmulation::WriteMemory (lldb_private::EmulateInstruction * instruction, const lldb_private::EmulateInstruction::Context & context, lldb::addr_t addr, const void * dst, size_t length) private
Definition at line 359 of file UnwindAssemblyInstEmulation.cpp.
References lldb_private::EmulateInstruction::Context::ContextInfo::RegisterToRegisterPlusOffset::data_reg, lldb_private::EmulateInstruction::Context::Dump(), lldb_private::DumpDataExtractor(), lldb_private::EmulateInstruction::eContextAbsoluteBranchRegister, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextAdjustPC, lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb_private::EmulateInstruction::eContextAdvancePC, lldb_private::EmulateInstruction::eContextArithmetic, lldb_private::EmulateInstruction::eContextImmediate, lldb_private::EmulateInstruction::eContextInvalid, lldb_private::EmulateInstruction::eContextPopRegisterOffStack, lldb_private::EmulateInstruction::eContextPushRegisterOnStack, lldb_private::EmulateInstruction::eContextReadOpcode, lldb_private::EmulateInstruction::eContextRegisterLoad, lldb_private::EmulateInstruction::eContextRegisterPlusOffset, lldb_private::EmulateInstruction::eContextRegisterStore, lldb_private::EmulateInstruction::eContextRelativeBranchImmediate, lldb_private::EmulateInstruction::eContextReturnFromException, lldb_private::EmulateInstruction::eContextSupervisorCall, lldb_private::EmulateInstruction::eContextTableBranchReadMemory, lldb_private::EmulateInstruction::eContextWriteMemoryRandomBits, lldb_private::EmulateInstruction::eContextWriteRegisterRandomBits, lldb::eFormatBytes, lldb_private::EmulateInstruction::eInfoTypeRegisterToRegisterPlusOffset, lldb::eRegisterKindGeneric, lldb_private::ArchSpec::GetAddressByteSize(), lldb_private::EmulateInstruction::GetArchitecture(), lldb_private::ArchSpec::GetByteOrder(), lldb_private::EmulateInstruction::Context::GetInfoType(), lldb_private::GetLog(), lldb_private::StreamString::GetString(), lldb_private::Log::GetVerbose(), lldb_private::EmulateInstruction::Context::info, lldb_private::RegisterInfo::kinds, LLDB_INVALID_REGNUM, LLDB_REGNUM_GENERIC_SP, m_curr_row_modified, m_initial_cfa, m_pushed_regs, m_state, m_unwind_plan_ptr, lldb_private::Stream::PutCString(), lldb_private::Log::PutString(), lldb_private::EmulateInstruction::Context::ContextInfo::RegisterToRegisterPlusOffset, lldb_private::EmulateInstruction::Context::type, UINT32_MAX, and lldb_private::Unwind.
WriteMemory() [2/2]
size_t UnwindAssemblyInstEmulation::WriteMemory (lldb_private::EmulateInstruction * instruction, void * baton, const lldb_private::EmulateInstruction::Context & context, lldb::addr_t addr, const void * dst, size_t length) static private
Definition at line 349 of file UnwindAssemblyInstEmulation.cpp.
References UnwindAssemblyInstEmulation().
Referenced by UnwindAssemblyInstEmulation().
WriteRegister() [1/2]
bool UnwindAssemblyInstEmulation::WriteRegister (lldb_private::EmulateInstruction * instruction, const lldb_private::EmulateInstruction::Context & context, const lldb_private::RegisterInfo * reg_info, const lldb_private::RegisterValue & reg_value) private
Definition at line 467 of file UnwindAssemblyInstEmulation.cpp.
References lldb_private::EmulateInstruction::Context::ContextInfo::address, lldb_private::EmulateInstruction::Context::Dump(), lldb_private::DumpRegisterValue(), lldb_private::EmulateInstruction::eContextAbsoluteBranchRegister, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextAdjustPC, lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb_private::EmulateInstruction::eContextAdvancePC, lldb_private::EmulateInstruction::eContextArithmetic, lldb_private::EmulateInstruction::eContextImmediate, lldb_private::EmulateInstruction::eContextInvalid, lldb_private::EmulateInstruction::eContextPopRegisterOffStack, lldb_private::EmulateInstruction::eContextPushRegisterOnStack, lldb_private::EmulateInstruction::eContextReadOpcode, lldb_private::EmulateInstruction::eContextRegisterLoad, lldb_private::EmulateInstruction::eContextRegisterPlusOffset, lldb_private::EmulateInstruction::eContextRegisterStore, lldb_private::EmulateInstruction::eContextRelativeBranchImmediate, lldb_private::EmulateInstruction::eContextRestoreStackPointer, lldb_private::EmulateInstruction::eContextReturnFromException, lldb_private::EmulateInstruction::eContextSetFramePointer, lldb_private::EmulateInstruction::eContextSupervisorCall, lldb_private::EmulateInstruction::eContextTableBranchReadMemory, lldb_private::EmulateInstruction::eContextWriteMemoryRandomBits, lldb_private::EmulateInstruction::eContextWriteRegisterRandomBits, lldb::eFormatDefault, lldb_private::EmulateInstruction::eInfoTypeAddress, lldb_private::EmulateInstruction::eInfoTypeImmediate, lldb_private::EmulateInstruction::eInfoTypeImmediateSigned, lldb_private::EmulateInstruction::eInfoTypeISA, lldb_private::EmulateInstruction::eInfoTypeISAAndImmediate, lldb_private::EmulateInstruction::eInfoTypeISAAndImmediateSigned, lldb_private::EmulateInstruction::eInfoTypeRegisterPlusOffset, lldb::eRegisterKindGeneric, lldb_private::RegisterValue::GetAsUInt64(), lldb_private::EmulateInstruction::Context::GetInfoType(), lldb_private::GetLog(), GetRegisterValue(), lldb_private::StreamString::GetString(), lldb_private::Log::GetVerbose(), lldb_private::EmulateInstruction::Context::info, lldb_private::EmulateInstruction::Context::ContextInfo::ISAAndImmediate, lldb_private::EmulateInstruction::Context::ContextInfo::ISAAndImmediateSigned, lldb_private::RegisterInfo::kinds, LLDB_INVALID_REGNUM, LLDB_REGNUM_GENERIC_FLAGS, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_SP, m_branch_offset, m_curr_row_modified, m_initial_cfa, m_inst_emulator_up, m_pushed_regs, m_state, m_unwind_plan_ptr, lldb_private::RegisterInfo::name, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), lldb_private::Log::PutString(), lldb_private::EmulateInstruction::Context::ContextInfo::RegisterPlusOffset::reg, lldb_private::EmulateInstruction::Context::ContextInfo::RegisterPlusOffset, SetRegisterValue(), lldb_private::EmulateInstruction::Context::ContextInfo::ISAAndImmediateSigned::signed_data32, lldb_private::EmulateInstruction::Context::ContextInfo::signed_immediate, lldb_private::EmulateInstruction::Context::ContextInfo::RegisterPlusOffset::signed_offset, lldb_private::EmulateInstruction::Context::type, lldb_private::EmulateInstruction::Context::ContextInfo::ISAAndImmediate::unsigned_data32, lldb_private::EmulateInstruction::Context::ContextInfo::unsigned_immediate, and lldb_private::Unwind.
WriteRegister() [2/2]
bool UnwindAssemblyInstEmulation::WriteRegister (lldb_private::EmulateInstruction * instruction, void * baton, const lldb_private::EmulateInstruction::Context & context, const lldb_private::RegisterInfo * reg_info, const lldb_private::RegisterValue & reg_value) static private
Definition at line 458 of file UnwindAssemblyInstEmulation.cpp.
References UnwindAssemblyInstEmulation().
Referenced by UnwindAssemblyInstEmulation().
Member Data Documentation
m_branch_offset
int64_t UnwindAssemblyInstEmulation::m_branch_offset = 0 private
Definition at line 155 of file UnwindAssemblyInstEmulation.h.
Referenced by GetNonCallSiteUnwindPlanFromAssembly(), and WriteRegister().
m_curr_row_modified
bool UnwindAssemblyInstEmulation::m_curr_row_modified private
Definition at line 152 of file UnwindAssemblyInstEmulation.h.
Referenced by GetNonCallSiteUnwindPlanFromAssembly(), UnwindAssemblyInstEmulation(), WriteMemory(), and WriteRegister().
m_initial_cfa
uint64_t UnwindAssemblyInstEmulation::m_initial_cfa private
Definition at line 141 of file UnwindAssemblyInstEmulation.h.
Referenced by GetNonCallSiteUnwindPlanFromAssembly(), UnwindAssemblyInstEmulation(), WriteMemory(), and WriteRegister().
m_inst_emulator_up
std::unique_ptr<lldb_private::EmulateInstruction> UnwindAssemblyInstEmulation::m_inst_emulator_up private
Definition at line 137 of file UnwindAssemblyInstEmulation.h.
Referenced by GetNonCallSiteUnwindPlanFromAssembly(), UnwindAssemblyInstEmulation(), and WriteRegister().
m_pushed_regs
PushedRegisterToAddrMap UnwindAssemblyInstEmulation::m_pushed_regs private
Definition at line 143 of file UnwindAssemblyInstEmulation.h.
Referenced by GetNonCallSiteUnwindPlanFromAssembly(), WriteMemory(), and WriteRegister().
m_range_ptr
lldb_private::AddressRange* UnwindAssemblyInstEmulation::m_range_ptr private
Definition at line 138 of file UnwindAssemblyInstEmulation.h.
Referenced by GetNonCallSiteUnwindPlanFromAssembly(), and UnwindAssemblyInstEmulation().
m_state
UnwindState UnwindAssemblyInstEmulation::m_state private
Definition at line 140 of file UnwindAssemblyInstEmulation.h.
Referenced by GetNonCallSiteUnwindPlanFromAssembly(), GetRegisterValue(), SetRegisterValue(), WriteMemory(), and WriteRegister().
m_unwind_plan_ptr
lldb_private::UnwindPlan* UnwindAssemblyInstEmulation::m_unwind_plan_ptr private
Definition at line 139 of file UnwindAssemblyInstEmulation.h.
Referenced by GetNonCallSiteUnwindPlanFromAssembly(), UnwindAssemblyInstEmulation(), WriteMemory(), and WriteRegister().
The documentation for this class was generated from the following files:
UnwindAssemblyInstEmulation.h
UnwindAssemblyInstEmulation.cpp