LLDB: lldb_private::Target::TargetEventData Class Reference
lldb_private::Target::TargetEventData Class Reference
#include <Target.h>
Public Member Functions
TargetEventData (const lldb::TargetSP &target_sp)
TargetEventData (const lldb::TargetSP &target_sp, const ModuleList &module_list)
TargetEventData (const lldb::TargetSP &target_sp, const lldb::TargetSP &created_target_sp)
~TargetEventData () override
llvm::StringRef GetFlavor () const override
void Dump (Stream *s) const override
const lldb::TargetSP & GetTarget () const
const lldb::TargetSP & GetCreatedTarget () const
const ModuleList & GetModuleList () const
Public Member Functions inherited from lldb_private::EventData
EventData ()
virtual ~EventData ()
virtual Log * GetLogChannel ()
Static Public Member Functions
static llvm::StringRef GetFlavorString ()
static const TargetEventData * GetEventDataFromEvent (const Event *event_ptr)
static lldb::TargetSP GetTargetFromEvent (const Event *event_ptr)
static lldb::TargetSP GetCreatedTargetFromEvent (const Event *event_ptr)
static ModuleList GetModuleListFromEvent (const Event *event_ptr)
Private Member Functions
TargetEventData (const TargetEventData &)=delete
const TargetEventData & operator= (const TargetEventData &)=delete
Private Attributes
lldb::TargetSP m_target_sp
lldb::TargetSP m_created_target_sp
ModuleList m_module_list
Detailed Description
Definition at line 578 of file Target.h.
Constructor & Destructor Documentation
TargetEventData() [1/4]
Target::TargetEventData::TargetEventData (const lldb::TargetSP & target_sp)
Definition at line 5268 of file Target.cpp.
References lldb_private::EventData::EventData(), m_module_list, and m_target_sp.
Referenced by GetCreatedTargetFromEvent(), GetEventDataFromEvent(), GetModuleListFromEvent(), GetTargetFromEvent(), operator=(), and TargetEventData().
TargetEventData() [2/4]
Target::TargetEventData::TargetEventData (const lldb::TargetSP & target_sp, const ModuleList & module_list)
Definition at line 5271 of file Target.cpp.
References lldb_private::EventData::EventData(), m_module_list, and m_target_sp.
TargetEventData() [3/4]
Target::TargetEventData::TargetEventData (const lldb::TargetSP & target_sp, const lldb::TargetSP & created_target_sp)
Definition at line 5275 of file Target.cpp.
References lldb_private::EventData::EventData(), m_created_target_sp, m_module_list, and m_target_sp.
~TargetEventData()
Target::TargetEventData::~TargetEventData () override default
TargetEventData() [4/4]
lldb_private::Target::TargetEventData::TargetEventData (const TargetEventData &) private delete
References TargetEventData().
Member Function Documentation
Dump()
void Target::TargetEventData::Dump (Stream * s) const override virtual
Reimplemented from lldb_private::EventData.
Definition at line 5286 of file Target.cpp.
References lldb_private::Stream::AsRawOstream(), lldb::eDescriptionLevelBrief, and m_module_list.
GetCreatedTarget()
const lldb::TargetSP & lldb_private::Target::TargetEventData::GetCreatedTarget () const inline
Definition at line 614 of file Target.h.
References m_created_target_sp.
GetCreatedTargetFromEvent()
TargetSP Target::TargetEventData::GetCreatedTargetFromEvent (const Event * event_ptr) static
Definition at line 5315 of file Target.cpp.
References lldb_private::EventData::Event, GetEventDataFromEvent(), m_created_target_sp, and TargetEventData().
Referenced by lldb::SBTarget::GetCreatedTargetFromEvent().
GetEventDataFromEvent()
const Target::TargetEventData * Target::TargetEventData::GetEventDataFromEvent (const Event * event_ptr) static
Definition at line 5296 of file Target.cpp.
References lldb_private::EventData::Event, lldb_private::EventData::EventData(), lldb_private::Event::GetData(), lldb_private::EventData::GetFlavor(), GetFlavorString(), and TargetEventData().
Referenced by lldb::SBTarget::EventIsTargetEvent(), GetCreatedTargetFromEvent(), GetModuleListFromEvent(), and GetTargetFromEvent().
GetFlavor()
llvm::StringRef lldb_private::Target::TargetEventData::GetFlavor () const inline override virtual
Implements lldb_private::EventData.
Definition at line 596 of file Target.h.
References GetFlavorString().
GetFlavorString()
llvm::StringRef Target::TargetEventData::GetFlavorString () static
Definition at line 5282 of file Target.cpp.
Referenced by GetEventDataFromEvent(), and GetFlavor().
GetModuleList()
const ModuleList & lldb_private::Target::TargetEventData::GetModuleList () const inline
Definition at line 618 of file Target.h.
References m_module_list.
GetModuleListFromEvent()
ModuleList Target::TargetEventData::GetModuleListFromEvent (const Event * event_ptr) static
Definition at line 5324 of file Target.cpp.
References lldb_private::EventData::Event, GetEventDataFromEvent(), m_module_list, and TargetEventData().
Referenced by lldb::SBTarget::GetModuleAtIndexFromEvent(), and lldb::SBTarget::GetNumModulesFromEvent().
GetTarget()
const lldb::TargetSP & lldb_private::Target::TargetEventData::GetTarget () const inline
Definition at line 612 of file Target.h.
References m_target_sp.
GetTargetFromEvent()
TargetSP Target::TargetEventData::GetTargetFromEvent (const Event * event_ptr) static
Definition at line 5306 of file Target.cpp.
References lldb_private::EventData::Event, GetEventDataFromEvent(), m_target_sp, and TargetEventData().
Referenced by lldb::SBTarget::GetTargetFromEvent().
operator=()
const TargetEventData & lldb_private::Target::TargetEventData::operator= (const TargetEventData &) private delete
References TargetEventData().
Member Data Documentation
m_created_target_sp
lldb::TargetSP lldb_private::Target::TargetEventData::m_created_target_sp private
Definition at line 622 of file Target.h.
Referenced by GetCreatedTarget(), GetCreatedTargetFromEvent(), and TargetEventData().
m_module_list
ModuleList lldb_private::Target::TargetEventData::m_module_list private
Definition at line 623 of file Target.h.
Referenced by Dump(), GetModuleList(), GetModuleListFromEvent(), TargetEventData(), TargetEventData(), and TargetEventData().
m_target_sp
lldb::TargetSP lldb_private::Target::TargetEventData::m_target_sp private
Definition at line 621 of file Target.h.
Referenced by GetTarget(), GetTargetFromEvent(), TargetEventData(), TargetEventData(), and TargetEventData().
The documentation for this class was generated from the following files:
Target.h
Target.cpp