LLDB: lldb_private::ScriptedFrameInterface Class Reference
lldb_private::ScriptedFrameInterface Class Reference abstract
#include <ScriptedFrameInterface.h>
Public Member Functions
virtual llvm::Expected< StructuredData::GenericSP > CreatePluginObject (llvm::StringRef class_name, ExecutionContext &exe_ctx, StructuredData::DictionarySP args_sp, StructuredData::Generic *script_obj=nullptr)=0
virtual lldb::user_id_t GetID ()
virtual lldb::addr_t GetPC ()
virtual std::optional< SymbolContext > GetSymbolContext ()
virtual std::optional< std::string > GetFunctionName ()
virtual std::optional< std::string > GetDisplayFunctionName ()
virtual bool IsInlined ()
virtual bool IsArtificial ()
virtual bool IsHidden ()
virtual StructuredData::DictionarySP GetRegisterInfo ()
virtual std::optional< std::string > GetRegisterContext ()
virtual lldb::ValueObjectListSP GetVariables ()
virtual lldb::ValueObjectSP GetValueObjectForVariableExpression (llvm::StringRef expr, uint32_t options, Status &error)
Public Member Functions inherited from lldb_private::ScriptedInterface
ScriptedInterface ()=default
virtual ~ScriptedInterface ()=default
StructuredData::GenericSP GetScriptObjectInstance ()
virtual llvm::SmallVector< AbstractMethodRequirement > GetAbstractMethodRequirements () const =0
virtual llvm::Expected< FileSpec > GetScriptedModulePath ()
llvm::SmallVector< llvm::StringLiteral > const GetAbstractMethods () const
Additional Inherited Members
Static Public Member Functions inherited from lldb_private::ScriptedInterface
template<typename Ret>
static Ret ErrorWithMessage (llvm::StringRef caller_name, llvm::StringRef error_msg, Status &error, LLDBLog log_category=LLDBLog::Process)
template<typename T = StructuredData::ObjectSP>
static bool CheckStructuredDataObject (llvm::StringRef caller, T obj, Status &error)
static bool CreateInstance (lldb::ScriptLanguage language, ScriptedInterfaceUsages usages)
Protected Attributes inherited from lldb_private::ScriptedInterface
StructuredData::GenericSP m_object_instance_sp
Detailed Description
Definition at line 21 of file ScriptedFrameInterface.h.
Member Function Documentation
CreatePluginObject()
virtual llvm::Expected< StructuredData::GenericSP > lldb_private::ScriptedFrameInterface::CreatePluginObject (llvm::StringRef class_name, ExecutionContext & exe_ctx, StructuredData::DictionarySP args_sp, StructuredData::Generic * script_obj = nullptr) pure virtual
Implemented in lldb_private::ScriptedFramePythonInterface.
GetDisplayFunctionName()
virtual std::optional< std::string > lldb_private::ScriptedFrameInterface::GetDisplayFunctionName () inline virtual
Reimplemented in lldb_private::ScriptedFramePythonInterface.
Definition at line 38 of file ScriptedFrameInterface.h.
GetFunctionName()
virtual std::optional< std::string > lldb_private::ScriptedFrameInterface::GetFunctionName () inline virtual
Reimplemented in lldb_private::ScriptedFramePythonInterface.
Definition at line 36 of file ScriptedFrameInterface.h.
GetID()
virtual lldb::user_id_t lldb_private::ScriptedFrameInterface::GetID () inline virtual
Reimplemented in lldb_private::ScriptedFramePythonInterface.
Definition at line 28 of file ScriptedFrameInterface.h.
References LLDB_INVALID_FRAME_ID.
GetPC()
virtual lldb::addr_t lldb_private::ScriptedFrameInterface::GetPC () inline virtual
Reimplemented in lldb_private::ScriptedFramePythonInterface.
Definition at line 30 of file ScriptedFrameInterface.h.
References LLDB_INVALID_ADDRESS.
GetRegisterContext()
virtual std::optional< std::string > lldb_private::ScriptedFrameInterface::GetRegisterContext () inline virtual
Reimplemented in lldb_private::ScriptedFramePythonInterface.
Definition at line 50 of file ScriptedFrameInterface.h.
Referenced by lldb_private::ScriptedFrame::CreateRegisterContext().
GetRegisterInfo()
virtual StructuredData::DictionarySP lldb_private::ScriptedFrameInterface::GetRegisterInfo () inline virtual
Reimplemented in lldb_private::ScriptedFramePythonInterface.
Definition at line 48 of file ScriptedFrameInterface.h.
Referenced by lldb_private::ScriptedFrame::CreateRegisterContext().
GetSymbolContext()
virtual std::optional< SymbolContext > lldb_private::ScriptedFrameInterface::GetSymbolContext () inline virtual
Reimplemented in lldb_private::ScriptedFramePythonInterface.
Definition at line 32 of file ScriptedFrameInterface.h.
GetValueObjectForVariableExpression()
virtual lldb::ValueObjectSP lldb_private::ScriptedFrameInterface::GetValueObjectForVariableExpression (llvm::StringRef expr, uint32_t options, Status & error) inline virtual
Reimplemented in lldb_private::ScriptedFramePythonInterface.
Definition at line 57 of file ScriptedFrameInterface.h.
References error().
GetVariables()
virtual lldb::ValueObjectListSP lldb_private::ScriptedFrameInterface::GetVariables () inline virtual
Reimplemented in lldb_private::ScriptedFramePythonInterface.
Definition at line 54 of file ScriptedFrameInterface.h.
IsArtificial()
virtual bool lldb_private::ScriptedFrameInterface::IsArtificial () inline virtual
Reimplemented in lldb_private::ScriptedFramePythonInterface.
Definition at line 44 of file ScriptedFrameInterface.h.
IsHidden()
virtual bool lldb_private::ScriptedFrameInterface::IsHidden () inline virtual
Reimplemented in lldb_private::ScriptedFramePythonInterface.
Definition at line 46 of file ScriptedFrameInterface.h.
IsInlined()
virtual bool lldb_private::ScriptedFrameInterface::IsInlined () inline virtual
Reimplemented in lldb_private::ScriptedFramePythonInterface.
Definition at line 42 of file ScriptedFrameInterface.h.
The documentation for this class was generated from the following file:
ScriptedFrameInterface.h