LLDB: DynamicLoaderFreeBSDKernel::KModImageInfo Class Reference
DynamicLoaderFreeBSDKernel::KModImageInfo Class Reference
#include <DynamicLoaderFreeBSDKernel.h>
Public Types
using collection_type = std::vector<KModImageInfo>
Public Member Functions
KModImageInfo ()
void Clear ()
void SetLoadAddress (lldb::addr_t load_address)
lldb::addr_t GetLoadAddress () const
void SetUUID (const lldb_private::UUID uuid)
lldb_private::UUID GetUUID () const
void SetName (const char *name)
std::string GetName () const
void SetPath (const char *path)
std::string GetPath () const
void SetModule (lldb::ModuleSP module)
lldb::ModuleSP GetModule ()
void SetIsKernel (bool is_kernel)
bool IsKernel () const
void SetStopID (uint32_t stop_id)
uint32_t GetStopID ()
bool IsLoaded () const
bool ReadMemoryModule (lldb_private::Process *process)
bool LoadImageUsingMemoryModule (lldb_private::Process *process)
bool LoadImageUsingFileAddress (lldb_private::Process *process)
Private Attributes
lldb::ModuleSP m_module_sp
lldb::ModuleSP m_memory_module_sp
lldb::addr_t m_load_address = LLDB_INVALID_ADDRESS
lldb_private::UUID m_uuid
bool m_is_kernel = false
std::string m_name
std::string m_path
uint32_t m_stop_id = UINT32_MAX
Detailed Description
Definition at line 59 of file DynamicLoaderFreeBSDKernel.h.
Member Typedef Documentation
collection_type
using DynamicLoaderFreeBSDKernel::KModImageInfo::collection_type = std::vector<KModImageInfo>
Definition at line 112 of file DynamicLoaderFreeBSDKernel.h.
Constructor & Destructor Documentation
KModImageInfo()
DynamicLoaderFreeBSDKernel::KModImageInfo::KModImageInfo () inline
Definition at line 61 of file DynamicLoaderFreeBSDKernel.h.
References m_memory_module_sp, m_module_sp, m_name, m_path, and m_uuid.
Member Function Documentation
Clear()
void DynamicLoaderFreeBSDKernel::KModImageInfo::Clear () inline
Definition at line 64 of file DynamicLoaderFreeBSDKernel.h.
References LLDB_INVALID_ADDRESS, m_load_address, m_memory_module_sp, m_module_sp, m_name, m_path, m_stop_id, m_uuid, and UINT32_MAX.
GetLoadAddress()
lldb::addr_t DynamicLoaderFreeBSDKernel::KModImageInfo::GetLoadAddress () const inline
Definition at line 78 of file DynamicLoaderFreeBSDKernel.h.
References m_load_address.
GetModule()
lldb::ModuleSP DynamicLoaderFreeBSDKernel::KModImageInfo::GetModule () inline
Definition at line 94 of file DynamicLoaderFreeBSDKernel.h.
References m_module_sp.
GetName()
std::string DynamicLoaderFreeBSDKernel::KModImageInfo::GetName () const inline
Definition at line 86 of file DynamicLoaderFreeBSDKernel.h.
References m_name.
Referenced by DynamicLoaderFreeBSDKernel::ReadAllKmods().
GetPath()
std::string DynamicLoaderFreeBSDKernel::KModImageInfo::GetPath () const inline
Definition at line 90 of file DynamicLoaderFreeBSDKernel.h.
References m_path.
Referenced by LoadImageUsingMemoryModule().
GetStopID()
uint32_t DynamicLoaderFreeBSDKernel::KModImageInfo::GetStopID () inline
Definition at line 102 of file DynamicLoaderFreeBSDKernel.h.
References m_stop_id.
GetUUID()
lldb_private::UUID DynamicLoaderFreeBSDKernel::KModImageInfo::GetUUID () const inline
Definition at line 82 of file DynamicLoaderFreeBSDKernel.h.
References m_uuid.
IsKernel()
bool DynamicLoaderFreeBSDKernel::KModImageInfo::IsKernel () const inline
Definition at line 98 of file DynamicLoaderFreeBSDKernel.h.
References m_is_kernel.
Referenced by LoadImageUsingMemoryModule().
IsLoaded()
bool DynamicLoaderFreeBSDKernel::KModImageInfo::IsLoaded () const inline
Definition at line 104 of file DynamicLoaderFreeBSDKernel.h.
References m_stop_id, and UINT32_MAX.
Referenced by LoadImageUsingFileAddress(), and LoadImageUsingMemoryModule().
LoadImageUsingFileAddress()
bool DynamicLoaderFreeBSDKernel::KModImageInfo::LoadImageUsingFileAddress (lldb_private::Process * process)
Definition at line 502 of file DynamicLoaderFreeBSDKernel.cpp.
References lldb_private::Process::GetStopID(), lldb_private::Process::GetTarget(), IsLoaded(), m_module_sp, and m_stop_id.
LoadImageUsingMemoryModule()
bool DynamicLoaderFreeBSDKernel::KModImageInfo::LoadImageUsingMemoryModule (lldb_private::Process * process)
Definition at line 335 of file DynamicLoaderFreeBSDKernel.cpp.
References lldb_private::ModuleList::AppendIfNeeded(), lldb_private::PluginManager::DownloadObjectAndSymbolFile(), lldb_private::DynamicLoader, error(), lldb_private::ModuleList::FindModule(), lldb_private::SectionList::FindSectionByName(), lldb_private::Target::GetArchitecture(), lldb_private::Debugger::GetAsyncOutputStream(), lldb_private::ObjectFile::GetBaseAddress(), lldb_private::Target::GetDebugger(), lldb_private::Address::GetFileAddress(), lldb_private::Section::GetFileAddress(), lldb_private::ModuleSpec::GetFileSpec(), lldb_private::Target::GetImages(), lldb_private::GetLog(), lldb_private::Target::GetOrCreateModule(), GetPath(), lldb_private::SectionList::GetSectionAtIndex(), lldb_private::ObjectFile::GetSectionList(), lldb_private::SectionList::GetSize(), lldb_private::Process::GetStopID(), lldb_private::Process::GetTarget(), lldb_private::FileSystem::Instance(), is_kmod(), is_reloc(), IsKernel(), IsLoaded(), LLDB_INVALID_ADDRESS, LLDB_LOGF, m_load_address, m_memory_module_sp, m_module_sp, m_name, m_stop_id, m_uuid, ReadMemoryModule(), and lldb_private::Target::SetSectionLoadAddress().
ReadMemoryModule()
bool DynamicLoaderFreeBSDKernel::KModImageInfo::ReadMemoryModule (lldb_private::Process * process)
Definition at line 272 of file DynamicLoaderFreeBSDKernel.cpp.
References lldb_private::DynamicLoader, error(), lldb_private::GetLog(), lldb_private::Process::GetTarget(), is_kernel(), LLDB_INVALID_ADDRESS, LLDB_LOG_ERROR, LLDB_LOGF, m_is_kernel, m_load_address, m_memory_module_sp, m_name, m_uuid, DynamicLoaderFreeBSDKernel::ReadELFHeader(), lldb_private::Process::ReadMemory(), lldb_private::Process::ReadModuleFromMemory(), and lldb_private::Target::SetArchitecture().
Referenced by LoadImageUsingMemoryModule().
SetIsKernel()
void DynamicLoaderFreeBSDKernel::KModImageInfo::SetIsKernel (bool is_kernel) inline
Definition at line 96 of file DynamicLoaderFreeBSDKernel.h.
References is_kernel(), and m_is_kernel.
SetLoadAddress()
void DynamicLoaderFreeBSDKernel::KModImageInfo::SetLoadAddress (lldb::addr_t load_address) inline
Definition at line 74 of file DynamicLoaderFreeBSDKernel.h.
References m_load_address.
Referenced by DynamicLoaderFreeBSDKernel::ReadAllKmods().
SetModule()
void DynamicLoaderFreeBSDKernel::KModImageInfo::SetModule (lldb::ModuleSP module) inline
Definition at line 92 of file DynamicLoaderFreeBSDKernel.h.
References m_module_sp.
SetName()
void DynamicLoaderFreeBSDKernel::KModImageInfo::SetName (const char * name) inline
Definition at line 84 of file DynamicLoaderFreeBSDKernel.h.
References m_name.
Referenced by DynamicLoaderFreeBSDKernel::ReadAllKmods().
SetPath()
void DynamicLoaderFreeBSDKernel::KModImageInfo::SetPath (const char * path) inline
Definition at line 88 of file DynamicLoaderFreeBSDKernel.h.
References m_path.
Referenced by DynamicLoaderFreeBSDKernel::ReadAllKmods().
SetStopID()
void DynamicLoaderFreeBSDKernel::KModImageInfo::SetStopID (uint32_t stop_id) inline
Definition at line 100 of file DynamicLoaderFreeBSDKernel.h.
References m_stop_id.
SetUUID()
void DynamicLoaderFreeBSDKernel::KModImageInfo::SetUUID (const lldb_private::UUID uuid) inline
Definition at line 80 of file DynamicLoaderFreeBSDKernel.h.
References m_uuid.
Member Data Documentation
m_is_kernel
bool DynamicLoaderFreeBSDKernel::KModImageInfo::m_is_kernel = false private
Definition at line 119 of file DynamicLoaderFreeBSDKernel.h.
Referenced by IsKernel(), ReadMemoryModule(), and SetIsKernel().
m_load_address
lldb::addr_t DynamicLoaderFreeBSDKernel::KModImageInfo::m_load_address = LLDB_INVALID_ADDRESS private
Definition at line 117 of file DynamicLoaderFreeBSDKernel.h.
Referenced by Clear(), GetLoadAddress(), LoadImageUsingMemoryModule(), ReadMemoryModule(), and SetLoadAddress().
m_memory_module_sp
lldb::ModuleSP DynamicLoaderFreeBSDKernel::KModImageInfo::m_memory_module_sp private
Definition at line 116 of file DynamicLoaderFreeBSDKernel.h.
Referenced by Clear(), KModImageInfo(), LoadImageUsingMemoryModule(), and ReadMemoryModule().
m_module_sp
lldb::ModuleSP DynamicLoaderFreeBSDKernel::KModImageInfo::m_module_sp private
Definition at line 115 of file DynamicLoaderFreeBSDKernel.h.
Referenced by Clear(), GetModule(), KModImageInfo(), LoadImageUsingFileAddress(), LoadImageUsingMemoryModule(), and SetModule().
m_name
std::string DynamicLoaderFreeBSDKernel::KModImageInfo::m_name private
Definition at line 120 of file DynamicLoaderFreeBSDKernel.h.
Referenced by Clear(), GetName(), KModImageInfo(), LoadImageUsingMemoryModule(), ReadMemoryModule(), and SetName().
m_path
std::string DynamicLoaderFreeBSDKernel::KModImageInfo::m_path private
Definition at line 121 of file DynamicLoaderFreeBSDKernel.h.
Referenced by Clear(), GetPath(), KModImageInfo(), and SetPath().
m_stop_id
uint32_t DynamicLoaderFreeBSDKernel::KModImageInfo::m_stop_id = UINT32_MAX private
Definition at line 122 of file DynamicLoaderFreeBSDKernel.h.
Referenced by Clear(), GetStopID(), IsLoaded(), LoadImageUsingFileAddress(), LoadImageUsingMemoryModule(), and SetStopID().
m_uuid
lldb_private::UUID DynamicLoaderFreeBSDKernel::KModImageInfo::m_uuid private
Definition at line 118 of file DynamicLoaderFreeBSDKernel.h.
Referenced by Clear(), GetUUID(), KModImageInfo(), LoadImageUsingMemoryModule(), ReadMemoryModule(), and SetUUID().
The documentation for this class was generated from the following files:
DynamicLoaderFreeBSDKernel.h
DynamicLoaderFreeBSDKernel.cpp