LLDB: lldb_private::SyntheticChildrenFrontEnd Class Reference
lldb_private::SyntheticChildrenFrontEnd Class Reference abstract
#include <TypeSynthetic.h>
Inherited by lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< IDD32, IDD64, true >, lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< IDD32, IDD64, false >, lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< ConstantArray32, ConstantArray64, false >, lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< DataDescriptor_32, DataDescriptor_64 >, lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< DataDescriptor_32, DataDescriptor_64 >, DummySyntheticFrontEnd, NSErrorSyntheticFrontEnd, NSExceptionSyntheticFrontEnd, NSIndexPathSyntheticFrontEnd, ObjCClassSyntheticChildrenFrontEnd, lldb_private::BytecodeSyntheticChildren::FrontEnd, lldb_private::ScriptedSyntheticChildren::FrontEnd, lldb_private::SyntheticValueProviderFrontEnd, lldb_private::TypeFilterImpl::FrontEnd, lldb_private::formatters::BlockPointerSyntheticFrontEnd, lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd, lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >, lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >, lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< D32, D64 >, lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >, lldb_private::formatters::LibCxxMapIteratorSyntheticFrontEnd, lldb_private::formatters::LibCxxUnorderedMapIteratorSyntheticFrontEnd, lldb_private::formatters::LibStdcppSpanSyntheticFrontEnd, lldb_private::formatters::LibcxxSharedPtrSyntheticFrontEnd, lldb_private::formatters::LibcxxStdAtomicSyntheticFrontEnd, lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd, lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd, lldb_private::formatters::LibcxxStdRangesRefViewSyntheticFrontEnd, lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd, lldb_private::formatters::LibcxxStdSpanSyntheticFrontEnd, lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd, lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd, lldb_private::formatters::LibcxxStdVectorSyntheticFrontEnd, lldb_private::formatters::LibcxxUniquePtrSyntheticFrontEnd, lldb_private::formatters::LibcxxVectorBoolSyntheticFrontEnd, lldb_private::formatters::MsvcStlAtomicSyntheticFrontEnd, lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd, lldb_private::formatters::MsvcStlSmartPointerSyntheticFrontEnd, lldb_private::formatters::MsvcStlSpanSyntheticFrontEnd, lldb_private::formatters::MsvcStlTreeIterSyntheticFrontEnd, lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd, lldb_private::formatters::MsvcStlUniquePtrSyntheticFrontEnd, lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd, lldb_private::formatters::MsvcStlVectorSyntheticFrontEnd, lldb_private::formatters::NSArray0SyntheticFrontEnd, lldb_private::formatters::NSArray1SyntheticFrontEnd, lldb_private::formatters::NSArrayMSyntheticFrontEndBase, lldb_private::formatters::NSCFDictionarySyntheticFrontEnd, lldb_private::formatters::NSCFSetSyntheticFrontEnd, lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd, lldb_private::formatters::NSDictionary1SyntheticFrontEnd, lldb_private::formatters::NSDictionaryISyntheticFrontEnd, lldb_private::formatters::NSSetISyntheticFrontEnd, lldb_private::formatters::StdlibCoroutineHandleSyntheticFrontEnd, lldb_private::formatters::VectorIteratorSyntheticFrontEnd, and lldb_private::formatters::VectorTypeSyntheticFrontEnd.
Public Types
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Public Member Functions
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren ()=0
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual lldb::ValueObjectSP GetChildAtIndex (uint32_t idx)=0
virtual llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name)=0
virtual lldb::ChildCacheState Update ()=0
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Protected Member Functions
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes
ValueObject & m_backend
Private Member Functions
SyntheticChildrenFrontEnd (const SyntheticChildrenFrontEnd &)=delete
const SyntheticChildrenFrontEnd & operator= (const SyntheticChildrenFrontEnd &)=delete
Detailed Description
Definition at line 28 of file TypeSynthetic.h.
Member Typedef Documentation
SharedPointer
typedef std::shared_ptr<SyntheticChildrenFrontEnd> lldb_private::SyntheticChildrenFrontEnd::SharedPointer
Definition at line 79 of file TypeSynthetic.h.
UniquePointer
typedef std::unique_ptr<SyntheticChildrenFrontEnd> lldb_private::SyntheticChildrenFrontEnd::UniquePointer
Definition at line 80 of file TypeSynthetic.h.
Constructor & Destructor Documentation
SyntheticChildrenFrontEnd() [1/2]
lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd (ValueObject & backend) inline
Definition at line 33 of file TypeSynthetic.h.
References m_backend.
Referenced by lldb_private::formatters::BlockPointerSyntheticFrontEnd::BlockPointerSyntheticFrontEnd(), DummySyntheticFrontEnd::DummySyntheticFrontEnd(), lldb_private::BytecodeSyntheticChildren::FrontEnd::FrontEnd(), lldb_private::ScriptedSyntheticChildren::FrontEnd::FrontEnd(), lldb_private::TypeFilterImpl::FrontEnd::FrontEnd(), lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >::GenericInitializerListSyntheticFrontEnd(), lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::GenericNSArrayISyntheticFrontEnd(), lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< D32, D64 >::GenericNSDictionaryMSyntheticFrontEnd(), lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::GenericNSSetMSyntheticFrontEnd(), lldb_private::formatters::LibCxxMapIteratorSyntheticFrontEnd::LibCxxMapIteratorSyntheticFrontEnd(), lldb_private::formatters::LibcxxSharedPtrSyntheticFrontEnd::LibcxxSharedPtrSyntheticFrontEnd(), lldb_private::formatters::LibcxxStdAtomicSyntheticFrontEnd::LibcxxStdAtomicSyntheticFrontEnd(), lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::LibcxxStdMapSyntheticFrontEnd(), lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::LibcxxStdProxyArraySyntheticFrontEnd(), lldb_private::formatters::LibcxxStdRangesRefViewSyntheticFrontEnd::LibcxxStdRangesRefViewSyntheticFrontEnd(), lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd::LibcxxStdSliceArraySyntheticFrontEnd(), lldb_private::formatters::LibcxxStdSpanSyntheticFrontEnd::LibcxxStdSpanSyntheticFrontEnd(), lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::LibcxxStdUnorderedMapSyntheticFrontEnd(), lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd::LibcxxStdValarraySyntheticFrontEnd(), lldb_private::formatters::LibcxxStdVectorSyntheticFrontEnd::LibcxxStdVectorSyntheticFrontEnd(), lldb_private::formatters::LibcxxUniquePtrSyntheticFrontEnd::LibcxxUniquePtrSyntheticFrontEnd(), lldb_private::formatters::LibCxxUnorderedMapIteratorSyntheticFrontEnd::LibCxxUnorderedMapIteratorSyntheticFrontEnd(), lldb_private::formatters::LibcxxVectorBoolSyntheticFrontEnd::LibcxxVectorBoolSyntheticFrontEnd(), lldb_private::formatters::LibStdcppSpanSyntheticFrontEnd::LibStdcppSpanSyntheticFrontEnd(), lldb_private::formatters::MsvcStlAtomicSyntheticFrontEnd::MsvcStlAtomicSyntheticFrontEnd(), lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::MsvcStlDequeSyntheticFrontEnd(), lldb_private::formatters::MsvcStlSmartPointerSyntheticFrontEnd::MsvcStlSmartPointerSyntheticFrontEnd(), lldb_private::formatters::MsvcStlSpanSyntheticFrontEnd::MsvcStlSpanSyntheticFrontEnd(), lldb_private::formatters::MsvcStlTreeIterSyntheticFrontEnd::MsvcStlTreeIterSyntheticFrontEnd(), lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd::MsvcStlTreeSyntheticFrontEnd(), lldb_private::formatters::MsvcStlUniquePtrSyntheticFrontEnd::MsvcStlUniquePtrSyntheticFrontEnd(), lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd::MsvcStlVectorBoolSyntheticFrontEnd(), lldb_private::formatters::MsvcStlVectorSyntheticFrontEnd::MsvcStlVectorSyntheticFrontEnd(), lldb_private::formatters::NSArray0SyntheticFrontEnd::NSArray0SyntheticFrontEnd(), lldb_private::formatters::NSArray1SyntheticFrontEnd::NSArray1SyntheticFrontEnd(), lldb_private::formatters::NSArrayMSyntheticFrontEndBase::NSArrayMSyntheticFrontEndBase(), lldb_private::formatters::NSCFDictionarySyntheticFrontEnd::NSCFDictionarySyntheticFrontEnd(), lldb_private::formatters::NSCFSetSyntheticFrontEnd::NSCFSetSyntheticFrontEnd(), lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::NSConstantDictionarySyntheticFrontEnd(), lldb_private::formatters::NSDictionary1SyntheticFrontEnd::NSDictionary1SyntheticFrontEnd(), lldb_private::formatters::NSDictionaryISyntheticFrontEnd::NSDictionaryISyntheticFrontEnd(), lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd::NSDictionaryMSyntheticFrontEnd(), NSErrorSyntheticFrontEnd::NSErrorSyntheticFrontEnd(), NSExceptionSyntheticFrontEnd::NSExceptionSyntheticFrontEnd(), NSIndexPathSyntheticFrontEnd::NSIndexPathSyntheticFrontEnd(), lldb_private::formatters::NSSetISyntheticFrontEnd::NSSetISyntheticFrontEnd(), ObjCClassSyntheticChildrenFrontEnd::ObjCClassSyntheticChildrenFrontEnd(), operator=(), lldb_private::formatters::StdlibCoroutineHandleSyntheticFrontEnd::StdlibCoroutineHandleSyntheticFrontEnd(), SyntheticChildrenFrontEnd(), lldb_private::SyntheticValueProviderFrontEnd::SyntheticValueProviderFrontEnd(), lldb_private::formatters::VectorIteratorSyntheticFrontEnd::VectorIteratorSyntheticFrontEnd(), and lldb_private::formatters::VectorTypeSyntheticFrontEnd::VectorTypeSyntheticFrontEnd().
~SyntheticChildrenFrontEnd()
virtual lldb_private::SyntheticChildrenFrontEnd::~SyntheticChildrenFrontEnd () virtual default
SyntheticChildrenFrontEnd() [2/2]
lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd (const SyntheticChildrenFrontEnd &) private delete
References SyntheticChildrenFrontEnd().
Member Function Documentation
CalculateNumChildren() [1/2]
virtual llvm::Expected< uint32_t > lldb_private::SyntheticChildrenFrontEnd::CalculateNumChildren () pure virtual
Implemented in DummySyntheticFrontEnd, lldb_private::BytecodeSyntheticChildren::FrontEnd, lldb_private::formatters::BlockPointerSyntheticFrontEnd, lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd, lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >, lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >, lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< ConstantArray32, ConstantArray64, false >, lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< IDD32, IDD64, false >, lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< IDD32, IDD64, true >, lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< D32, D64 >, lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< DataDescriptor_32, DataDescriptor_64 >, lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >, lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< DataDescriptor_32, DataDescriptor_64 >, lldb_private::formatters::LibCxxMapIteratorSyntheticFrontEnd, lldb_private::formatters::LibcxxSharedPtrSyntheticFrontEnd, lldb_private::formatters::LibcxxStdAtomicSyntheticFrontEnd, lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd, lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd, lldb_private::formatters::LibcxxStdRangesRefViewSyntheticFrontEnd, lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd, lldb_private::formatters::LibcxxStdSpanSyntheticFrontEnd, lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd, lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd, lldb_private::formatters::LibcxxStdVectorSyntheticFrontEnd, lldb_private::formatters::LibcxxUniquePtrSyntheticFrontEnd, lldb_private::formatters::LibCxxUnorderedMapIteratorSyntheticFrontEnd, lldb_private::formatters::LibcxxVectorBoolSyntheticFrontEnd, lldb_private::formatters::LibStdcppSpanSyntheticFrontEnd, lldb_private::formatters::MsvcStlAtomicSyntheticFrontEnd, lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd, lldb_private::formatters::MsvcStlSmartPointerSyntheticFrontEnd, lldb_private::formatters::MsvcStlSpanSyntheticFrontEnd, lldb_private::formatters::MsvcStlTreeIterSyntheticFrontEnd, lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd, lldb_private::formatters::MsvcStlUniquePtrSyntheticFrontEnd, lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd, lldb_private::formatters::MsvcStlVectorSyntheticFrontEnd, lldb_private::formatters::NSArray0SyntheticFrontEnd, lldb_private::formatters::NSArray1SyntheticFrontEnd, lldb_private::formatters::NSArrayMSyntheticFrontEndBase, lldb_private::formatters::NSCFDictionarySyntheticFrontEnd, lldb_private::formatters::NSCFSetSyntheticFrontEnd, lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd, lldb_private::formatters::NSDictionary1SyntheticFrontEnd, lldb_private::formatters::NSDictionaryISyntheticFrontEnd, lldb_private::formatters::NSSetISyntheticFrontEnd, lldb_private::formatters::StdlibCoroutineHandleSyntheticFrontEnd, lldb_private::formatters::VectorIteratorSyntheticFrontEnd, lldb_private::formatters::VectorTypeSyntheticFrontEnd, lldb_private::ScriptedSyntheticChildren::FrontEnd, lldb_private::SyntheticValueProviderFrontEnd, lldb_private::TypeFilterImpl::FrontEnd, NSErrorSyntheticFrontEnd, NSExceptionSyntheticFrontEnd, NSIndexPathSyntheticFrontEnd, and ObjCClassSyntheticChildrenFrontEnd.
Referenced by CalculateNumChildren(), and CalculateNumChildrenIgnoringErrors().
CalculateNumChildren() [2/2]
virtual llvm::Expected< uint32_t > lldb_private::SyntheticChildrenFrontEnd::CalculateNumChildren (uint32_t max) inline virtual
Reimplemented in lldb_private::ScriptedSyntheticChildren::FrontEnd.
Definition at line 39 of file TypeSynthetic.h.
References CalculateNumChildren().
CalculateNumChildrenIgnoringErrors()
uint32_t SyntheticChildrenFrontEnd::CalculateNumChildrenIgnoringErrors (uint32_t max = UINT32_MAX)
Definition at line 123 of file TypeSynthetic.cpp.
References CalculateNumChildren(), lldb_private::DataFormatters, lldb_private::GetLog(), and LLDB_LOG_ERRORV.
Referenced by lldb_private::formatters::BlockPointerSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::GetChildAtIndex(), lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< D32, D64 >::GetChildAtIndex(), lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::GetChildAtIndex(), lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSArrayMSyntheticFrontEndBase::GetChildAtIndex(), lldb_private::formatters::NSCFDictionarySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSCFSetSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSDictionaryISyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSSetISyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::GetIndexOfChildWithName(), lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< D32, D64 >::GetIndexOfChildWithName(), lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::GetIndexOfChildWithName(), lldb_private::formatters::LibcxxVectorBoolSyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::NSArrayMSyntheticFrontEndBase::GetIndexOfChildWithName(), lldb_private::formatters::NSCFDictionarySyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::NSCFSetSyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::NSDictionaryISyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::NSSetISyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::VectorTypeSyntheticFrontEnd::GetIndexOfChildWithName(), and NSIndexPathSyntheticFrontEnd::GetIndexOfChildWithName().
CreateValueObjectFromAddress()
lldb::ValueObjectSP SyntheticChildrenFrontEnd::CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext & exe_ctx, CompilerType type, bool do_deref = true) protected
Definition at line 142 of file TypeSynthetic.cpp.
References lldb_private::ValueObject::CreateValueObjectFromAddress().
Referenced by lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >::GetChildAtIndex(), lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::GetChildAtIndex(), lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdSpanSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdVectorSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibStdcppSpanSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlSpanSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlVectorSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSArrayMSyntheticFrontEndBase::GetChildAtIndex(), lldb_private::formatters::StdlibCoroutineHandleSyntheticFrontEnd::Update(), and lldb_private::formatters::VectorIteratorSyntheticFrontEnd::Update().
CreateValueObjectFromData()
lldb::ValueObjectSP SyntheticChildrenFrontEnd::CreateValueObjectFromData (llvm::StringRef name, const DataExtractor & data, const ExecutionContext & exe_ctx, CompilerType type) protected
Definition at line 152 of file TypeSynthetic.cpp.
References lldb_private::ValueObject::CreateValueObjectFromData().
Referenced by lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< D32, D64 >::GetChildAtIndex(), lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::GetChildAtIndex(), lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxVectorBoolSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSCFDictionarySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSCFSetSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSDictionary1SyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSDictionaryISyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSSetISyntheticFrontEnd::GetChildAtIndex(), and NSErrorSyntheticFrontEnd::Update().
CreateValueObjectFromExpression()
lldb::ValueObjectSP SyntheticChildrenFrontEnd::CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext & exe_ctx) protected
Definition at line 132 of file TypeSynthetic.cpp.
References lldb_private::ValueObject::CreateValueObjectFromExpression().
GetChildAtIndex()
virtual lldb::ValueObjectSP lldb_private::SyntheticChildrenFrontEnd::GetChildAtIndex (uint32_t idx) pure virtual
Implemented in DummySyntheticFrontEnd, lldb_private::BytecodeSyntheticChildren::FrontEnd, lldb_private::formatters::BlockPointerSyntheticFrontEnd, lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd, lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >, lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >, lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< ConstantArray32, ConstantArray64, false >, lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< IDD32, IDD64, false >, lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< IDD32, IDD64, true >, lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< D32, D64 >, lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< DataDescriptor_32, DataDescriptor_64 >, lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >, lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< DataDescriptor_32, DataDescriptor_64 >, lldb_private::formatters::LibCxxMapIteratorSyntheticFrontEnd, lldb_private::formatters::LibcxxSharedPtrSyntheticFrontEnd, lldb_private::formatters::LibcxxStdAtomicSyntheticFrontEnd, lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd, lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd, lldb_private::formatters::LibcxxStdRangesRefViewSyntheticFrontEnd, lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd, lldb_private::formatters::LibcxxStdSpanSyntheticFrontEnd, lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd, lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd, lldb_private::formatters::LibcxxStdVectorSyntheticFrontEnd, lldb_private::formatters::LibcxxUniquePtrSyntheticFrontEnd, lldb_private::formatters::LibCxxUnorderedMapIteratorSyntheticFrontEnd, lldb_private::formatters::LibcxxVectorBoolSyntheticFrontEnd, lldb_private::formatters::LibStdcppSpanSyntheticFrontEnd, lldb_private::formatters::MsvcStlAtomicSyntheticFrontEnd, lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd, lldb_private::formatters::MsvcStlSmartPointerSyntheticFrontEnd, lldb_private::formatters::MsvcStlSpanSyntheticFrontEnd, lldb_private::formatters::MsvcStlTreeIterSyntheticFrontEnd, lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd, lldb_private::formatters::MsvcStlUniquePtrSyntheticFrontEnd, lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd, lldb_private::formatters::MsvcStlVectorSyntheticFrontEnd, lldb_private::formatters::NSArray0SyntheticFrontEnd, lldb_private::formatters::NSArray1SyntheticFrontEnd, lldb_private::formatters::NSArrayMSyntheticFrontEndBase, lldb_private::formatters::NSCFDictionarySyntheticFrontEnd, lldb_private::formatters::NSCFSetSyntheticFrontEnd, lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd, lldb_private::formatters::NSDictionary1SyntheticFrontEnd, lldb_private::formatters::NSDictionaryISyntheticFrontEnd, lldb_private::formatters::NSSetISyntheticFrontEnd, lldb_private::formatters::StdlibCoroutineHandleSyntheticFrontEnd, lldb_private::formatters::VectorIteratorSyntheticFrontEnd, lldb_private::formatters::VectorTypeSyntheticFrontEnd, lldb_private::ScriptedSyntheticChildren::FrontEnd, lldb_private::SyntheticValueProviderFrontEnd, lldb_private::TypeFilterImpl::FrontEnd, NSErrorSyntheticFrontEnd, NSExceptionSyntheticFrontEnd, NSIndexPathSyntheticFrontEnd, and ObjCClassSyntheticChildrenFrontEnd.
Referenced by lldb_private::formatters::BlockPointerSummaryProvider().
GetIndexOfChildWithName()
virtual llvm::Expected< size_t > lldb_private::SyntheticChildrenFrontEnd::GetIndexOfChildWithName (ConstString name) pure virtual
Implemented in DummySyntheticFrontEnd, lldb_private::BytecodeSyntheticChildren::FrontEnd, lldb_private::formatters::BlockPointerSyntheticFrontEnd, lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd, lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >, lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >, lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< ConstantArray32, ConstantArray64, false >, lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< IDD32, IDD64, false >, lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< IDD32, IDD64, true >, lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< D32, D64 >, lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< DataDescriptor_32, DataDescriptor_64 >, lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >, lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< DataDescriptor_32, DataDescriptor_64 >, lldb_private::formatters::LibCxxMapIteratorSyntheticFrontEnd, lldb_private::formatters::LibcxxSharedPtrSyntheticFrontEnd, lldb_private::formatters::LibcxxStdAtomicSyntheticFrontEnd, lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd, lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd, lldb_private::formatters::LibcxxStdRangesRefViewSyntheticFrontEnd, lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd, lldb_private::formatters::LibcxxStdSpanSyntheticFrontEnd, lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd, lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd, lldb_private::formatters::LibcxxStdVectorSyntheticFrontEnd, lldb_private::formatters::LibcxxUniquePtrSyntheticFrontEnd, lldb_private::formatters::LibCxxUnorderedMapIteratorSyntheticFrontEnd, lldb_private::formatters::LibcxxVectorBoolSyntheticFrontEnd, lldb_private::formatters::LibStdcppSpanSyntheticFrontEnd, lldb_private::formatters::MsvcStlAtomicSyntheticFrontEnd, lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd, lldb_private::formatters::MsvcStlSmartPointerSyntheticFrontEnd, lldb_private::formatters::MsvcStlSpanSyntheticFrontEnd, lldb_private::formatters::MsvcStlTreeIterSyntheticFrontEnd, lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd, lldb_private::formatters::MsvcStlUniquePtrSyntheticFrontEnd, lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd, lldb_private::formatters::MsvcStlVectorSyntheticFrontEnd, lldb_private::formatters::NSArray0SyntheticFrontEnd, lldb_private::formatters::NSArray1SyntheticFrontEnd, lldb_private::formatters::NSArrayMSyntheticFrontEndBase, lldb_private::formatters::NSCFDictionarySyntheticFrontEnd, lldb_private::formatters::NSCFSetSyntheticFrontEnd, lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd, lldb_private::formatters::NSDictionary1SyntheticFrontEnd, lldb_private::formatters::NSDictionaryISyntheticFrontEnd, lldb_private::formatters::NSSetISyntheticFrontEnd, lldb_private::formatters::StdlibCoroutineHandleSyntheticFrontEnd, lldb_private::formatters::VectorIteratorSyntheticFrontEnd, lldb_private::formatters::VectorTypeSyntheticFrontEnd, lldb_private::ScriptedSyntheticChildren::FrontEnd, lldb_private::SyntheticValueProviderFrontEnd, lldb_private::TypeFilterImpl::FrontEnd, NSErrorSyntheticFrontEnd, NSExceptionSyntheticFrontEnd, NSIndexPathSyntheticFrontEnd, and ObjCClassSyntheticChildrenFrontEnd.
Referenced by lldb_private::formatters::BlockPointerSummaryProvider().
GetSyntheticTypeName()
virtual ConstString lldb_private::SyntheticChildrenFrontEnd::GetSyntheticTypeName () inline virtual
Reimplemented in lldb_private::ScriptedSyntheticChildren::FrontEnd.
Definition at line 77 of file TypeSynthetic.h.
GetSyntheticValue()
virtual lldb::ValueObjectSP lldb_private::SyntheticChildrenFrontEnd::GetSyntheticValue () inline virtual
Reimplemented in lldb_private::formatters::MsvcStlTreeIterSyntheticFrontEnd, lldb_private::ScriptedSyntheticChildren::FrontEnd, lldb_private::SyntheticValueProviderFrontEnd, and NSIndexPathSyntheticFrontEnd.
Definition at line 72 of file TypeSynthetic.h.
MightHaveChildren()
virtual bool lldb_private::SyntheticChildrenFrontEnd::MightHaveChildren () inline virtual
Reimplemented in DummySyntheticFrontEnd, lldb_private::formatters::NSArray0SyntheticFrontEnd, lldb_private::ScriptedSyntheticChildren::FrontEnd, lldb_private::SyntheticValueProviderFrontEnd, lldb_private::TypeFilterImpl::FrontEnd, NSIndexPathSyntheticFrontEnd, and ObjCClassSyntheticChildrenFrontEnd.
Definition at line 67 of file TypeSynthetic.h.
operator=()
const SyntheticChildrenFrontEnd & lldb_private::SyntheticChildrenFrontEnd::operator= (const SyntheticChildrenFrontEnd &) private delete
References SyntheticChildrenFrontEnd().
Update()
virtual lldb::ChildCacheState lldb_private::SyntheticChildrenFrontEnd::Update () pure virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implemented in DummySyntheticFrontEnd, lldb_private::BytecodeSyntheticChildren::FrontEnd, lldb_private::formatters::BlockPointerSyntheticFrontEnd, lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd, lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >, lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >, lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< ConstantArray32, ConstantArray64, false >, lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< IDD32, IDD64, false >, lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< IDD32, IDD64, true >, lldb_private::formatters::GenericNSArrayMSyntheticFrontEnd< D32, D64 >, lldb_private::formatters::GenericNSArrayMSyntheticFrontEnd< DataDescriptor< uint32_t >, DataDescriptor< uint64_t > >, lldb_private::formatters::GenericNSArrayMSyntheticFrontEnd< DataDescriptor_32, DataDescriptor_64 >, lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< D32, D64 >, lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< DataDescriptor_32, DataDescriptor_64 >, lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >, lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< DataDescriptor_32, DataDescriptor_64 >, lldb_private::formatters::LibCxxMapIteratorSyntheticFrontEnd, lldb_private::formatters::LibcxxSharedPtrSyntheticFrontEnd, lldb_private::formatters::LibcxxStdAtomicSyntheticFrontEnd, lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd, lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd, lldb_private::formatters::LibcxxStdRangesRefViewSyntheticFrontEnd, lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd, lldb_private::formatters::LibcxxStdSpanSyntheticFrontEnd, lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd, lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd, lldb_private::formatters::LibcxxStdVectorSyntheticFrontEnd, lldb_private::formatters::LibcxxUniquePtrSyntheticFrontEnd, lldb_private::formatters::LibCxxUnorderedMapIteratorSyntheticFrontEnd, lldb_private::formatters::LibcxxVectorBoolSyntheticFrontEnd, lldb_private::formatters::LibStdcppSpanSyntheticFrontEnd, lldb_private::formatters::MsvcStlAtomicSyntheticFrontEnd, lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd, lldb_private::formatters::MsvcStlSmartPointerSyntheticFrontEnd, lldb_private::formatters::MsvcStlSpanSyntheticFrontEnd, lldb_private::formatters::MsvcStlTreeIterSyntheticFrontEnd, lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd, lldb_private::formatters::MsvcStlUniquePtrSyntheticFrontEnd, lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd, lldb_private::formatters::MsvcStlVectorSyntheticFrontEnd, lldb_private::formatters::NSArray0SyntheticFrontEnd, lldb_private::formatters::NSArray1SyntheticFrontEnd, lldb_private::formatters::NSArrayMSyntheticFrontEndBase, lldb_private::formatters::NSCFDictionarySyntheticFrontEnd, lldb_private::formatters::NSCFSetSyntheticFrontEnd, lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd, lldb_private::formatters::NSDictionary1SyntheticFrontEnd, lldb_private::formatters::NSDictionaryISyntheticFrontEnd, lldb_private::formatters::NSSetISyntheticFrontEnd, lldb_private::formatters::StdlibCoroutineHandleSyntheticFrontEnd, lldb_private::formatters::VectorIteratorSyntheticFrontEnd, lldb_private::formatters::VectorTypeSyntheticFrontEnd, lldb_private::ScriptedSyntheticChildren::FrontEnd, lldb_private::SyntheticValueProviderFrontEnd, lldb_private::TypeFilterImpl::FrontEnd, NSErrorSyntheticFrontEnd, NSExceptionSyntheticFrontEnd, NSIndexPathSyntheticFrontEnd, and ObjCClassSyntheticChildrenFrontEnd.
Referenced by lldb_private::formatters::BlockPointerSummaryProvider().
Member Data Documentation
m_backend
ValueObject& lldb_private::SyntheticChildrenFrontEnd::m_backend protected
Definition at line 30 of file TypeSynthetic.h.
Referenced by lldb_private::formatters::BlockPointerSyntheticFrontEnd::BlockPointerSyntheticFrontEnd(), DummySyntheticFrontEnd::CalculateNumChildren(), lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >::CalculateNumChildren(), DummySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::BlockPointerSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >::GetChildAtIndex(), lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::GetChildAtIndex(), lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< D32, D64 >::GetChildAtIndex(), lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::GetChildAtIndex(), lldb_private::formatters::LibcxxSharedPtrSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdSpanSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdVectorSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibStdcppSpanSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlSmartPointerSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlSpanSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlVectorSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSArray1SyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSCFDictionarySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSCFSetSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSDictionary1SyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSDictionaryISyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSSetISyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::VectorTypeSyntheticFrontEnd::GetChildAtIndex(), lldb_private::TypeFilterImpl::FrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::GetElementType(), DummySyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::GetNodeType(), DummySyntheticFrontEnd::MightHaveChildren(), NSIndexPathSyntheticFrontEnd::NSIndexPathSyntheticFrontEnd(), SyntheticChildrenFrontEnd(), lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd::Update(), lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >::Update(), lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::Update(), lldb_private::formatters::GenericNSArrayMSyntheticFrontEnd< D32, D64 >::Update(), lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< D32, D64 >::Update(), lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::Update(), lldb_private::formatters::LibCxxMapIteratorSyntheticFrontEnd::Update(), lldb_private::formatters::LibcxxSharedPtrSyntheticFrontEnd::Update(), lldb_private::formatters::LibcxxStdAtomicSyntheticFrontEnd::Update(), lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::Update(), lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::Update(), lldb_private::formatters::LibcxxStdRangesRefViewSyntheticFrontEnd::Update(), lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd::Update(), lldb_private::formatters::LibcxxStdSpanSyntheticFrontEnd::Update(), lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::Update(), lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd::Update(), lldb_private::formatters::LibcxxStdVectorSyntheticFrontEnd::Update(), lldb_private::formatters::LibcxxUniquePtrSyntheticFrontEnd::Update(), lldb_private::formatters::LibCxxUnorderedMapIteratorSyntheticFrontEnd::Update(), lldb_private::formatters::LibcxxVectorBoolSyntheticFrontEnd::Update(), lldb_private::formatters::LibStdcppSpanSyntheticFrontEnd::Update(), lldb_private::formatters::MsvcStlAtomicSyntheticFrontEnd::Update(), lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::Update(), lldb_private::formatters::MsvcStlSmartPointerSyntheticFrontEnd::Update(), lldb_private::formatters::MsvcStlSpanSyntheticFrontEnd::Update(), lldb_private::formatters::MsvcStlTreeIterSyntheticFrontEnd::Update(), lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd::Update(), lldb_private::formatters::MsvcStlUniquePtrSyntheticFrontEnd::Update(), lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd::Update(), lldb_private::formatters::MsvcStlVectorSyntheticFrontEnd::Update(), lldb_private::formatters::NSCFDictionarySyntheticFrontEnd::Update(), lldb_private::formatters::NSCFSetSyntheticFrontEnd::Update(), lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::Update(), lldb_private::formatters::NSDictionaryISyntheticFrontEnd::Update(), lldb_private::formatters::NSSetISyntheticFrontEnd::Update(), lldb_private::formatters::StdlibCoroutineHandleSyntheticFrontEnd::Update(), lldb_private::formatters::VectorIteratorSyntheticFrontEnd::Update(), lldb_private::formatters::VectorTypeSyntheticFrontEnd::Update(), NSErrorSyntheticFrontEnd::Update(), NSExceptionSyntheticFrontEnd::Update(), and NSIndexPathSyntheticFrontEnd::Update().
The documentation for this class was generated from the following files:
TypeSynthetic.h
TypeSynthetic.cpp