LLDB: lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2 Class Reference
lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2 Class Reference
Public Member Functions
~TaggedPointerVendorV2 () override=default
Public Member Functions inherited from lldb_private::ObjCLanguageRuntime::TaggedPointerVendor
virtual ~TaggedPointerVendor ()=default
virtual bool IsPossibleTaggedPointer (lldb::addr_t ptr)=0
virtual ObjCLanguageRuntime::ClassDescriptorSP GetClassDescriptor (lldb::addr_t ptr)=0
Static Public Member Functions
static TaggedPointerVendorV2 * CreateInstance (AppleObjCRuntimeV2 &runtime, const lldb::ModuleSP &objc_module_sp)
Protected Member Functions
TaggedPointerVendorV2 (AppleObjCRuntimeV2 &runtime)
Protected Member Functions inherited from lldb_private::ObjCLanguageRuntime::TaggedPointerVendor
TaggedPointerVendor ()=default
Protected Attributes
AppleObjCRuntimeV2 & m_runtime
Private Member Functions
TaggedPointerVendorV2 (const TaggedPointerVendorV2 &)=delete
const TaggedPointerVendorV2 & operator= (const TaggedPointerVendorV2 &)=delete
Detailed Description
Definition at line 176 of file AppleObjCRuntimeV2.h.
Constructor & Destructor Documentation
~TaggedPointerVendorV2()
lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2::~TaggedPointerVendorV2 () override default
References lldb_private::AppleObjCRuntimeV2::AppleObjCRuntimeV2(), and TaggedPointerVendorV2().
TaggedPointerVendorV2() [1/2]
lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2::TaggedPointerVendorV2 (AppleObjCRuntimeV2 & runtime) inline protected
Definition at line 188 of file AppleObjCRuntimeV2.h.
References lldb_private::AppleObjCRuntimeV2::AppleObjCRuntimeV2(), m_runtime, and lldb_private::ObjCLanguageRuntime::TaggedPointerVendor::TaggedPointerVendor().
Referenced by operator=(), TaggedPointerVendorV2(), and ~TaggedPointerVendorV2().
TaggedPointerVendorV2() [2/2]
lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2::TaggedPointerVendorV2 (const TaggedPointerVendorV2 &) private delete
References TaggedPointerVendorV2().
Member Function Documentation
CreateInstance()
AppleObjCRuntimeV2::TaggedPointerVendorV2 * AppleObjCRuntimeV2::TaggedPointerVendorV2::CreateInstance (AppleObjCRuntimeV2 & runtime, const lldb::ModuleSP & objc_module_sp) static
Definition at line 2869 of file AppleObjCRuntimeV2.cpp.
References error().
operator=()
const TaggedPointerVendorV2 & lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2::operator= (const TaggedPointerVendorV2 &) private delete
References TaggedPointerVendorV2().
Member Data Documentation
m_runtime
AppleObjCRuntimeV2& lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2::m_runtime protected
Definition at line 186 of file AppleObjCRuntimeV2.h.
Referenced by TaggedPointerVendorV2().
The documentation for this class was generated from the following files:
AppleObjCRuntimeV2.h
AppleObjCRuntimeV2.cpp