LLDB: lldb_private::SearchFilterForUnconstrainedSearches Class Reference
lldb_private::SearchFilterForUnconstrainedSearches Class Reference
"lldb/Core/SearchFilter.h" This is a SearchFilter that searches through all modules.
#include <SearchFilter.h>
Public Member Functions
SearchFilterForUnconstrainedSearches (const lldb::TargetSP &target_sp)
~SearchFilterForUnconstrainedSearches () override=default
bool ModulePasses (const FileSpec &module_spec) override
Call this method with a file spec to see if that spec passes the filter.
bool ModulePasses (const lldb::ModuleSP &module_sp) override
Call this method with a Module to see if that module passes the filter.
StructuredData::ObjectSP SerializeToStructuredData () override
Public Member Functions inherited from lldb_private::SearchFilter
SearchFilter (const lldb::TargetSP &target_sp)
The basic constructor takes a Target, which gives the space to search.
SearchFilter (const lldb::TargetSP &target_sp, unsigned char filterType)
virtual ~SearchFilter ()
virtual bool AddressPasses (Address &addr)
Call this method with a Address to see if address passes the filter.
virtual bool CompUnitPasses (FileSpec &fileSpec)
Call this method with a FileSpec to see if file spec passes the filter as the name of a compilation unit.
virtual bool CompUnitPasses (CompileUnit &compUnit)
Call this method with a CompileUnit to see if comp unit passes the filter.
virtual bool FunctionPasses (Function &function)
Call this method with a Function to see if function passes the filter.
virtual void Search (Searcher &searcher)
Call this method to do the search using the Searcher.
virtual void SearchInModuleList (Searcher &searcher, ModuleList &modules)
Call this method to do the search using the Searcher in the module list modules.
virtual uint32_t GetFilterRequiredItems ()
This determines which items are REQUIRED for the filter to pass.
virtual void GetDescription (Stream *s)
Prints a canonical description for the search filter to the stream s.
virtual void Dump (Stream *s) const
Standard "Dump" method. At present it does nothing.
lldb::SearchFilterSP CreateCopy (lldb::TargetSP &target_sp)
enum FilterTy GetFilterTy ()
const char * GetFilterName ()
Static Public Member Functions
static lldb::SearchFilterSP CreateFromStructuredData (const lldb::TargetSP &target_sp, const StructuredData::Dictionary &data_dict, Status &error)
Static Public Member Functions inherited from lldb_private::SearchFilter
static lldb::SearchFilterSP CreateFromStructuredData (const lldb::TargetSP &target_sp, const StructuredData::Dictionary &data_dict, Status &error)
static const char * GetSerializationKey ()
static const char * GetSerializationSubclassKey ()
static const char * GetSerializationSubclassOptionsKey ()
static const char * FilterTyToName (enum FilterTy)
static FilterTy NameToFilterTy (llvm::StringRef name)
Protected Member Functions
lldb::SearchFilterSP DoCreateCopy () override
Protected Member Functions inherited from lldb_private::SearchFilter
StructuredData::DictionarySP WrapOptionsDict (StructuredData::DictionarySP options_dict_sp)
void SerializeFileSpecList (StructuredData::DictionarySP &options_dict_sp, OptionNames name, FileSpecList &file_list)
Searcher::CallbackReturn DoModuleIteration (const SymbolContext &context, Searcher &searcher)
Searcher::CallbackReturn DoModuleIteration (const lldb::ModuleSP &module_sp, Searcher &searcher)
Searcher::CallbackReturn DoCUIteration (const lldb::ModuleSP &module_sp, const SymbolContext &context, Searcher &searcher)
Searcher::CallbackReturn DoFunctionIteration (Function *function, const SymbolContext &context, Searcher &searcher)
void SetTarget (lldb::TargetSP &target_sp)
Additional Inherited Members
Public Types inherited from lldb_private::SearchFilter
enum FilterTy {
Unconstrained = 0 , Exception , ByModule , ByModules ,
ByModulesAndCU , LastKnownFilterType = ByModulesAndCU , UnknownFilter
}
Static Public Attributes inherited from lldb_private::SearchFilter
static const char * g_ty_to_name [LastKnownFilterType+2]
Protected Types inherited from lldb_private::SearchFilter
enum OptionNames { ModList = 0 , CUList , LanguageName , LastOptionName }
Static Protected Member Functions inherited from lldb_private::SearchFilter
static const char * GetKey (enum OptionNames enum_value)
Protected Attributes inherited from lldb_private::SearchFilter
lldb::TargetSP m_target_sp
Static Protected Attributes inherited from lldb_private::SearchFilter
static const char * g_option_names [LastOptionName]
Detailed Description
"lldb/Core/SearchFilter.h" This is a SearchFilter that searches through all modules.
It also consults the Target::ModuleIsExcludedForUnconstrainedSearches.
Definition at line 289 of file SearchFilter.h.
Constructor & Destructor Documentation
SearchFilterForUnconstrainedSearches()
lldb_private::SearchFilterForUnconstrainedSearches::SearchFilterForUnconstrainedSearches (const lldb::TargetSP & target_sp) inline
Definition at line 291 of file SearchFilter.h.
References lldb_private::SearchFilter::SearchFilter(), and lldb_private::SearchFilter::Unconstrained.
~SearchFilterForUnconstrainedSearches()
lldb_private::SearchFilterForUnconstrainedSearches::~SearchFilterForUnconstrainedSearches () override default
References error().
Member Function Documentation
CreateFromStructuredData()
SearchFilterSP SearchFilterForUnconstrainedSearches::CreateFromStructuredData (const lldb::TargetSP & target_sp, const StructuredData::Dictionary & data_dict, Status & error) static
Definition at line 359 of file SearchFilter.cpp.
References error().
Referenced by lldb_private::SearchFilter::CreateFromStructuredData().
DoCreateCopy()
SearchFilterSP SearchFilterForUnconstrainedSearches::DoCreateCopy () override protected virtual
Implements lldb_private::SearchFilter.
Definition at line 388 of file SearchFilter.cpp.
ModulePasses() [1/2]
bool SearchFilterForUnconstrainedSearches::ModulePasses (const FileSpec & spec) override virtual
Call this method with a file spec to see if that spec passes the filter.
Parameters
[in] spec The file spec to check against the filter.
Returns
true if spec passes, and false otherwise.
Note
the default implementation always returns true.
Reimplemented from lldb_private::SearchFilter.
Definition at line 374 of file SearchFilter.cpp.
References lldb_private::SearchFilter::m_target_sp.
ModulePasses() [2/2]
bool SearchFilterForUnconstrainedSearches::ModulePasses (const lldb::ModuleSP & module_sp) override virtual
Call this method with a Module to see if that module passes the filter.
Parameters
[in] module_sp The Module to check against the filter.
Returns
true if module passes, and false otherwise.
Note
the default implementation always returns true.
Reimplemented from lldb_private::SearchFilter.
Definition at line 379 of file SearchFilter.cpp.
References lldb_private::SearchFilter::m_target_sp.
SerializeToStructuredData()
StructuredData::ObjectSP SearchFilterForUnconstrainedSearches::SerializeToStructuredData () override virtual
Reimplemented from lldb_private::SearchFilter.
Definition at line 368 of file SearchFilter.cpp.
References lldb_private::SearchFilter::WrapOptionsDict().
The documentation for this class was generated from the following files:
SearchFilter.h
SearchFilter.cpp