LLDB: CommandObjectThreadSelect::OptionGroupThreadSelect Class Reference
CommandObjectThreadSelect::OptionGroupThreadSelect Class Reference
Public Member Functions
OptionGroupThreadSelect ()
~OptionGroupThreadSelect () override=default
void OptionParsingStarting (ExecutionContext *execution_context) override
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext *execution_context) override
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Public Attributes
lldb::tid_t m_thread_id
Detailed Description
Definition at line 1096 of file CommandObjectThread.cpp.
Constructor & Destructor Documentation
OptionGroupThreadSelect()
CommandObjectThreadSelect::OptionGroupThreadSelect::OptionGroupThreadSelect () inline
Definition at line 1098 of file CommandObjectThread.cpp.
References OptionParsingStarting().
~OptionGroupThreadSelect()
CommandObjectThreadSelect::OptionGroupThreadSelect::~OptionGroupThreadSelect () override default
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > CommandObjectThreadSelect::OptionGroupThreadSelect::GetDefinitions () inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 1126 of file CommandObjectThread.cpp.
OptionParsingStarting()
void CommandObjectThreadSelect::OptionGroupThreadSelect::OptionParsingStarting (ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 1102 of file CommandObjectThread.cpp.
References LLDB_INVALID_THREAD_ID, and m_thread_id.
Referenced by OptionGroupThreadSelect().
SetOptionValue()
Status CommandObjectThreadSelect::OptionGroupThreadSelect::SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 1106 of file CommandObjectThread.cpp.
References lldb_private::Status::FromErrorStringWithFormat(), LLDB_INVALID_THREAD_ID, and m_thread_id.
Member Data Documentation
m_thread_id
lldb::tid_t CommandObjectThreadSelect::OptionGroupThreadSelect::m_thread_id
Definition at line 1130 of file CommandObjectThread.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following file:
CommandObjectThread.cpp