LLDB: lldb_private::ScriptInterpreterLocker Class Reference
lldb_private::ScriptInterpreterLocker Class Reference
#include <ScriptInterpreter.h>
Public Member Functions
ScriptInterpreterLocker ()=default
virtual ~ScriptInterpreterLocker ()=default
Private Member Functions
ScriptInterpreterLocker (const ScriptInterpreterLocker &)=delete
const ScriptInterpreterLocker & operator= (const ScriptInterpreterLocker &)=delete
Detailed Description
Definition at line 47 of file ScriptInterpreter.h.
Constructor & Destructor Documentation
ScriptInterpreterLocker() [1/2]
lldb_private::ScriptInterpreterLocker::ScriptInterpreterLocker () default
Referenced by lldb_private::ScriptInterpreterPythonImpl::Locker::Locker(), operator=(), and ScriptInterpreterLocker().
~ScriptInterpreterLocker()
virtual lldb_private::ScriptInterpreterLocker::~ScriptInterpreterLocker () virtual default
ScriptInterpreterLocker() [2/2]
lldb_private::ScriptInterpreterLocker::ScriptInterpreterLocker (const ScriptInterpreterLocker &) private delete
References ScriptInterpreterLocker().
Member Function Documentation
operator=()
const ScriptInterpreterLocker & lldb_private::ScriptInterpreterLocker::operator= (const ScriptInterpreterLocker &) private delete
References ScriptInterpreterLocker().
The documentation for this class was generated from the following file:
ScriptInterpreter.h