LLDB: lldb_private::PluginManager Class Reference
lldb_private::PluginManager Class Reference
#include <PluginManager.h>
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::ArrayRef< PluginNamespace > GetPluginNamespaces ()
static llvm::json::Object GetJSON (llvm::StringRef pattern="")
static bool MatchPluginName (llvm::StringRef pattern, const PluginNamespace &plugin_ns, const RegisteredPluginInfo &plugin)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, ABICreateInstance create_callback)
static bool UnregisterPlugin (ABICreateInstance create_callback)
static ABICreateInstance GetABICreateCallbackAtIndex (uint32_t idx)
static void RegisterPlugin (llvm::StringRef name, llvm::StringRef description, ArchitectureCreateInstance create_callback)
static void UnregisterPlugin (ArchitectureCreateInstance create_callback)
static std::unique_ptr< Architecture > CreateArchitectureInstance (const ArchSpec &arch)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, DisassemblerCreateInstance create_callback)
static bool UnregisterPlugin (DisassemblerCreateInstance create_callback)
static DisassemblerCreateInstance GetDisassemblerCreateCallbackAtIndex (uint32_t idx)
static DisassemblerCreateInstance GetDisassemblerCreateCallbackForPluginName (llvm::StringRef name)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, DynamicLoaderCreateInstance create_callback, DebuggerInitializeCallback debugger_init_callback=nullptr)
static bool UnregisterPlugin (DynamicLoaderCreateInstance create_callback)
static DynamicLoaderCreateInstance GetDynamicLoaderCreateCallbackAtIndex (uint32_t idx)
static DynamicLoaderCreateInstance GetDynamicLoaderCreateCallbackForPluginName (llvm::StringRef name)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, JITLoaderCreateInstance create_callback, DebuggerInitializeCallback debugger_init_callback=nullptr)
static bool UnregisterPlugin (JITLoaderCreateInstance create_callback)
static JITLoaderCreateInstance GetJITLoaderCreateCallbackAtIndex (uint32_t idx)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, EmulateInstructionCreateInstance create_callback)
static bool UnregisterPlugin (EmulateInstructionCreateInstance create_callback)
static EmulateInstructionCreateInstance GetEmulateInstructionCreateCallbackAtIndex (uint32_t idx)
static EmulateInstructionCreateInstance GetEmulateInstructionCreateCallbackForPluginName (llvm::StringRef name)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, OperatingSystemCreateInstance create_callback, DebuggerInitializeCallback debugger_init_callback)
static bool UnregisterPlugin (OperatingSystemCreateInstance create_callback)
static OperatingSystemCreateInstance GetOperatingSystemCreateCallbackAtIndex (uint32_t idx)
static OperatingSystemCreateInstance GetOperatingSystemCreateCallbackForPluginName (llvm::StringRef name)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, LanguageCreateInstance create_callback, DebuggerInitializeCallback debugger_init_callback=nullptr)
static bool UnregisterPlugin (LanguageCreateInstance create_callback)
static LanguageCreateInstance GetLanguageCreateCallbackAtIndex (uint32_t idx)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, LanguageRuntimeCreateInstance create_callback, LanguageRuntimeGetCommandObject command_callback=nullptr, LanguageRuntimeGetExceptionPrecondition precondition_callback=nullptr)
static bool UnregisterPlugin (LanguageRuntimeCreateInstance create_callback)
static LanguageRuntimeCreateInstance GetLanguageRuntimeCreateCallbackAtIndex (uint32_t idx)
static LanguageRuntimeGetCommandObject GetLanguageRuntimeGetCommandObjectAtIndex (uint32_t idx)
static LanguageRuntimeGetExceptionPrecondition GetLanguageRuntimeGetExceptionPreconditionAtIndex (uint32_t idx)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, SystemRuntimeCreateInstance create_callback)
static bool UnregisterPlugin (SystemRuntimeCreateInstance create_callback)
static SystemRuntimeCreateInstance GetSystemRuntimeCreateCallbackAtIndex (uint32_t idx)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, ObjectFileCreateInstance create_callback, ObjectFileCreateMemoryInstance create_memory_callback, ObjectFileGetModuleSpecifications get_module_specifications, ObjectFileSaveCore save_core=nullptr, DebuggerInitializeCallback debugger_init_callback=nullptr)
static bool UnregisterPlugin (ObjectFileCreateInstance create_callback)
static bool IsRegisteredObjectFilePluginName (llvm::StringRef name)
static ObjectFileCreateInstance GetObjectFileCreateCallbackAtIndex (uint32_t idx)
static ObjectFileCreateMemoryInstance GetObjectFileCreateMemoryCallbackAtIndex (uint32_t idx)
static ObjectFileGetModuleSpecifications GetObjectFileGetModuleSpecificationsCallbackAtIndex (uint32_t idx)
static ObjectFileCreateMemoryInstance GetObjectFileCreateMemoryCallbackForPluginName (llvm::StringRef name)
static Status SaveCore (lldb_private::SaveCoreOptions &core_options)
static std::vector< llvm::StringRef > GetSaveCorePluginNames ()
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, ObjectContainerCreateInstance create_callback, ObjectFileGetModuleSpecifications get_module_specifications, ObjectContainerCreateMemoryInstance create_memory_callback=nullptr)
static bool UnregisterPlugin (ObjectContainerCreateInstance create_callback)
static ObjectContainerCreateInstance GetObjectContainerCreateCallbackAtIndex (uint32_t idx)
static ObjectContainerCreateMemoryInstance GetObjectContainerCreateMemoryCallbackAtIndex (uint32_t idx)
static ObjectFileGetModuleSpecifications GetObjectContainerGetModuleSpecificationsCallbackAtIndex (uint32_t idx)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, PlatformCreateInstance create_callback, DebuggerInitializeCallback debugger_init_callback=nullptr)
static bool UnregisterPlugin (PlatformCreateInstance create_callback)
static PlatformCreateInstance GetPlatformCreateCallbackAtIndex (uint32_t idx)
static PlatformCreateInstance GetPlatformCreateCallbackForPluginName (llvm::StringRef name)
static llvm::StringRef GetPlatformPluginNameAtIndex (uint32_t idx)
static llvm::StringRef GetPlatformPluginDescriptionAtIndex (uint32_t idx)
static void AutoCompletePlatformName (llvm::StringRef partial_name, CompletionRequest &request)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, ProcessCreateInstance create_callback, DebuggerInitializeCallback debugger_init_callback=nullptr)
static bool UnregisterPlugin (ProcessCreateInstance create_callback)
static ProcessCreateInstance GetProcessCreateCallbackAtIndex (uint32_t idx)
static ProcessCreateInstance GetProcessCreateCallbackForPluginName (llvm::StringRef name)
static llvm::StringRef GetProcessPluginNameAtIndex (uint32_t idx)
static llvm::StringRef GetProcessPluginDescriptionAtIndex (uint32_t idx)
static void AutoCompleteProcessName (llvm::StringRef partial_name, CompletionRequest &request)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, ProtocolServerCreateInstance create_callback)
static bool UnregisterPlugin (ProtocolServerCreateInstance create_callback)
static llvm::StringRef GetProtocolServerPluginNameAtIndex (uint32_t idx)
static ProtocolServerCreateInstance GetProtocolCreateCallbackForPluginName (llvm::StringRef name)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, RegisterTypeBuilderCreateInstance create_callback)
static bool UnregisterPlugin (RegisterTypeBuilderCreateInstance create_callback)
static lldb::RegisterTypeBuilderSP GetRegisterTypeBuilder (Target &target)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, lldb::ScriptLanguage script_lang, ScriptInterpreterCreateInstance create_callback, ScriptInterpreterGetPath get_path_callback=nullptr)
static bool UnregisterPlugin (ScriptInterpreterCreateInstance create_callback)
static ScriptInterpreterCreateInstance GetScriptInterpreterCreateCallbackAtIndex (uint32_t idx)
static lldb::ScriptInterpreterSP GetScriptInterpreterForLanguage (lldb::ScriptLanguage script_lang, Debugger &debugger)
static FileSpec GetScriptInterpreterLibraryPath (lldb::ScriptLanguage script_lang)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, SyntheticFrameProviderCreateInstance create_native_callback, ScriptedFrameProviderCreateInstance create_scripted_callback)
static bool UnregisterPlugin (SyntheticFrameProviderCreateInstance create_callback)
static bool UnregisterPlugin (ScriptedFrameProviderCreateInstance create_callback)
static SyntheticFrameProviderCreateInstance GetSyntheticFrameProviderCreateCallbackForPluginName (llvm::StringRef name)
static ScriptedFrameProviderCreateInstance GetScriptedFrameProviderCreateCallbackAtIndex (uint32_t idx)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, StructuredDataPluginCreateInstance create_callback, DebuggerInitializeCallback debugger_init_callback=nullptr, StructuredDataFilterLaunchInfo filter_callback=nullptr)
Register a StructuredDataPlugin class along with optional callbacks for debugger initialization and Process launch info filtering and manipulation.
static bool UnregisterPlugin (StructuredDataPluginCreateInstance create_callback)
static StructuredDataPluginCreateInstance GetStructuredDataPluginCreateCallbackAtIndex (uint32_t idx)
static StructuredDataFilterLaunchInfo GetStructuredDataFilterCallbackAtIndex (uint32_t idx, bool &iteration_complete)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, SymbolFileCreateInstance create_callback, DebuggerInitializeCallback debugger_init_callback=nullptr)
static bool UnregisterPlugin (SymbolFileCreateInstance create_callback)
static SymbolFileCreateInstance GetSymbolFileCreateCallbackAtIndex (uint32_t idx)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, SymbolVendorCreateInstance create_callback)
static bool UnregisterPlugin (SymbolVendorCreateInstance create_callback)
static SymbolVendorCreateInstance GetSymbolVendorCreateCallbackAtIndex (uint32_t idx)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, SymbolLocatorCreateInstance create_callback, SymbolLocatorLocateExecutableObjectFile locate_executable_object_file=nullptr, SymbolLocatorLocateExecutableSymbolFile locate_executable_symbol_file=nullptr, SymbolLocatorDownloadObjectAndSymbolFile download_object_symbol_file=nullptr, SymbolLocatorFindSymbolFileInBundle find_symbol_file_in_bundle=nullptr, DebuggerInitializeCallback debugger_init_callback=nullptr)
static bool UnregisterPlugin (SymbolLocatorCreateInstance create_callback)
static SymbolLocatorCreateInstance GetSymbolLocatorCreateCallbackAtIndex (uint32_t idx)
static ModuleSpec LocateExecutableObjectFile (const ModuleSpec &module_spec, StatisticsMap &map)
static FileSpec LocateExecutableSymbolFile (const ModuleSpec &module_spec, const FileSpecList &default_search_paths, StatisticsMap &map)
static bool DownloadObjectAndSymbolFile (ModuleSpec &module_spec, Status &error, bool force_lookup=true, bool copy_executable=true)
static FileSpec FindSymbolFileInBundle (const FileSpec &dsym_bundle_fspec, const UUID *uuid, const ArchSpec *arch)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, TraceCreateInstanceFromBundle create_callback_from_bundle, TraceCreateInstanceForLiveProcess create_callback_for_live_process, llvm::StringRef schema, DebuggerInitializeCallback debugger_init_callback)
static bool UnregisterPlugin (TraceCreateInstanceFromBundle create_callback)
static TraceCreateInstanceFromBundle GetTraceCreateCallback (llvm::StringRef plugin_name)
static TraceCreateInstanceForLiveProcess GetTraceCreateCallbackForLiveProcess (llvm::StringRef plugin_name)
static llvm::StringRef GetTraceSchema (llvm::StringRef plugin_name)
Get the JSON schema for a trace bundle description file corresponding to the given plugin.
static llvm::StringRef GetTraceSchema (size_t index)
Get the JSON schema for a trace bundle description file corresponding to the plugin given by its index.
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, TraceExporterCreateInstance create_callback, ThreadTraceExportCommandCreator create_thread_trace_export_command)
static TraceExporterCreateInstance GetTraceExporterCreateCallback (llvm::StringRef plugin_name)
static bool UnregisterPlugin (TraceExporterCreateInstance create_callback)
static llvm::StringRef GetTraceExporterPluginNameAtIndex (uint32_t index)
static ThreadTraceExportCommandCreator GetThreadTraceExportCommandCreatorAtIndex (uint32_t index)
Return the callback used to create the CommandObject that will be listed under "thread trace export".
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, UnwindAssemblyCreateInstance create_callback)
static bool UnregisterPlugin (UnwindAssemblyCreateInstance create_callback)
static UnwindAssemblyCreateInstance GetUnwindAssemblyCreateCallbackAtIndex (uint32_t idx)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, MemoryHistoryCreateInstance create_callback)
static bool UnregisterPlugin (MemoryHistoryCreateInstance create_callback)
static MemoryHistoryCreateInstance GetMemoryHistoryCreateCallbackAtIndex (uint32_t idx)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, InstrumentationRuntimeCreateInstance create_callback, InstrumentationRuntimeGetType get_type_callback)
static bool UnregisterPlugin (InstrumentationRuntimeCreateInstance create_callback)
static InstrumentationRuntimeGetType GetInstrumentationRuntimeGetTypeCallbackAtIndex (uint32_t idx)
static InstrumentationRuntimeCreateInstance GetInstrumentationRuntimeCreateCallbackAtIndex (uint32_t idx)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, TypeSystemCreateInstance create_callback, LanguageSet supported_languages_for_types, LanguageSet supported_languages_for_expressions)
static bool UnregisterPlugin (TypeSystemCreateInstance create_callback)
static TypeSystemCreateInstance GetTypeSystemCreateCallbackAtIndex (uint32_t idx)
static LanguageSet GetAllTypeSystemSupportedLanguagesForTypes ()
static LanguageSet GetAllTypeSystemSupportedLanguagesForExpressions ()
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, ScriptedInterfaceCreateInstance create_callback, lldb::ScriptLanguage language, ScriptedInterfaceUsages usages)
static bool UnregisterPlugin (ScriptedInterfaceCreateInstance create_callback)
static uint32_t GetNumScriptedInterfaces ()
static llvm::StringRef GetScriptedInterfaceNameAtIndex (uint32_t idx)
static llvm::StringRef GetScriptedInterfaceDescriptionAtIndex (uint32_t idx)
static lldb::ScriptLanguage GetScriptedInterfaceLanguageAtIndex (uint32_t idx)
static ScriptedInterfaceUsages GetScriptedInterfaceUsagesAtIndex (uint32_t idx)
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, REPLCreateInstance create_callback, LanguageSet supported_languages)
static bool UnregisterPlugin (REPLCreateInstance create_callback)
static REPLCreateInstance GetREPLCreateCallbackAtIndex (uint32_t idx)
static LanguageSet GetREPLSupportedLanguagesAtIndex (uint32_t idx)
static LanguageSet GetREPLAllTypeSystemSupportedLanguages ()
static bool RegisterPlugin (llvm::StringRef name, llvm::StringRef description, HighlighterCreateInstance create_callback)
static bool UnregisterPlugin (HighlighterCreateInstance create_callback)
static HighlighterCreateInstance GetHighlighterCreateCallbackAtIndex (uint32_t idx)
static void DebuggerInitialize (Debugger &debugger)
static lldb::OptionValuePropertiesSP GetSettingForDynamicLoaderPlugin (Debugger &debugger, llvm::StringRef setting_name)
static bool CreateSettingForDynamicLoaderPlugin (Debugger &debugger, const lldb::OptionValuePropertiesSP &properties_sp, llvm::StringRef description, bool is_global_property)
static lldb::OptionValuePropertiesSP GetSettingForPlatformPlugin (Debugger &debugger, llvm::StringRef setting_name)
static bool CreateSettingForPlatformPlugin (Debugger &debugger, const lldb::OptionValuePropertiesSP &properties_sp, llvm::StringRef description, bool is_global_property)
static lldb::OptionValuePropertiesSP GetSettingForProcessPlugin (Debugger &debugger, llvm::StringRef setting_name)
static bool CreateSettingForProcessPlugin (Debugger &debugger, const lldb::OptionValuePropertiesSP &properties_sp, llvm::StringRef description, bool is_global_property)
static lldb::OptionValuePropertiesSP GetSettingForSymbolLocatorPlugin (Debugger &debugger, llvm::StringRef setting_name)
static bool CreateSettingForSymbolLocatorPlugin (Debugger &debugger, const lldb::OptionValuePropertiesSP &properties_sp, llvm::StringRef description, bool is_global_property)
static bool CreateSettingForTracePlugin (Debugger &debugger, const lldb::OptionValuePropertiesSP &properties_sp, llvm::StringRef description, bool is_global_property)
static lldb::OptionValuePropertiesSP GetSettingForObjectFilePlugin (Debugger &debugger, llvm::StringRef setting_name)
static bool CreateSettingForObjectFilePlugin (Debugger &debugger, const lldb::OptionValuePropertiesSP &properties_sp, llvm::StringRef description, bool is_global_property)
static lldb::OptionValuePropertiesSP GetSettingForSymbolFilePlugin (Debugger &debugger, llvm::StringRef setting_name)
static bool CreateSettingForSymbolFilePlugin (Debugger &debugger, const lldb::OptionValuePropertiesSP &properties_sp, llvm::StringRef description, bool is_global_property)
static lldb::OptionValuePropertiesSP GetSettingForJITLoaderPlugin (Debugger &debugger, llvm::StringRef setting_name)
static bool CreateSettingForJITLoaderPlugin (Debugger &debugger, const lldb::OptionValuePropertiesSP &properties_sp, llvm::StringRef description, bool is_global_property)
static lldb::OptionValuePropertiesSP GetSettingForOperatingSystemPlugin (Debugger &debugger, llvm::StringRef setting_name)
static bool CreateSettingForOperatingSystemPlugin (Debugger &debugger, const lldb::OptionValuePropertiesSP &properties_sp, llvm::StringRef description, bool is_global_property)
static lldb::OptionValuePropertiesSP GetSettingForStructuredDataPlugin (Debugger &debugger, llvm::StringRef setting_name)
static bool CreateSettingForStructuredDataPlugin (Debugger &debugger, const lldb::OptionValuePropertiesSP &properties_sp, llvm::StringRef description, bool is_global_property)
static lldb::OptionValuePropertiesSP GetSettingForCPlusPlusLanguagePlugin (Debugger &debugger, llvm::StringRef setting_name)
static bool CreateSettingForCPlusPlusLanguagePlugin (Debugger &debugger, const lldb::OptionValuePropertiesSP &properties_sp, llvm::StringRef description, bool is_global_property)
static std::vector< RegisteredPluginInfo > GetABIPluginInfo ()
static bool SetABIPluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetArchitecturePluginInfo ()
static bool SetArchitecturePluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetDisassemblerPluginInfo ()
static bool SetDisassemblerPluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetDynamicLoaderPluginInfo ()
static bool SetDynamicLoaderPluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetEmulateInstructionPluginInfo ()
static bool SetEmulateInstructionPluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetInstrumentationRuntimePluginInfo ()
static bool SetInstrumentationRuntimePluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetJITLoaderPluginInfo ()
static bool SetJITLoaderPluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetLanguagePluginInfo ()
static bool SetLanguagePluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetLanguageRuntimePluginInfo ()
static bool SetLanguageRuntimePluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetMemoryHistoryPluginInfo ()
static bool SetMemoryHistoryPluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetObjectContainerPluginInfo ()
static bool SetObjectContainerPluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetObjectFilePluginInfo ()
static bool SetObjectFilePluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetOperatingSystemPluginInfo ()
static bool SetOperatingSystemPluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetPlatformPluginInfo ()
static bool SetPlatformPluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetProcessPluginInfo ()
static bool SetProcessPluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetREPLPluginInfo ()
static bool SetREPLPluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetRegisterTypeBuilderPluginInfo ()
static bool SetRegisterTypeBuilderPluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetScriptInterpreterPluginInfo ()
static bool SetScriptInterpreterPluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetScriptedInterfacePluginInfo ()
static bool SetScriptedInterfacePluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetStructuredDataPluginInfo ()
static bool SetStructuredDataPluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetSymbolFilePluginInfo ()
static bool SetSymbolFilePluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetSymbolLocatorPluginInfo ()
static bool SetSymbolLocatorPluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetSymbolVendorPluginInfo ()
static bool SetSymbolVendorPluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetSystemRuntimePluginInfo ()
static bool SetSystemRuntimePluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetTracePluginInfo ()
static bool SetTracePluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetTraceExporterPluginInfo ()
static bool SetTraceExporterPluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetTypeSystemPluginInfo ()
static bool SetTypeSystemPluginEnabled (llvm::StringRef name, bool enable)
static std::vector< RegisteredPluginInfo > GetUnwindAssemblyPluginInfo ()
static bool SetUnwindAssemblyPluginEnabled (llvm::StringRef name, bool enable)
static void AutoCompletePluginName (llvm::StringRef partial_name, CompletionRequest &request)
Detailed Description
Definition at line 85 of file PluginManager.h.
Member Function Documentation
AutoCompletePlatformName()
void PluginManager::AutoCompletePlatformName (llvm::StringRef partial_name, CompletionRequest & request) static
Definition at line 1189 of file PluginManager.cpp.
References lldb_private::CompletionRequest::AddCompletion(), and GetPlatformInstances().
Referenced by lldb_private::CommandCompletions::PlatformPluginNames().
AutoCompletePluginName()
void PluginManager::AutoCompletePluginName (llvm::StringRef partial_name, CompletionRequest & request) static
Definition at line 2657 of file PluginManager.cpp.
References lldb_private::CompletionRequest::AddCompletion(), GetPluginNamespaces(), and lldb_private::Partial.
Referenced by lldb_private::CommandCompletions::ManagedPlugins().
AutoCompleteProcessName()
void PluginManager::AutoCompleteProcessName (llvm::StringRef partial_name, CompletionRequest & request) static
Definition at line 1238 of file PluginManager.cpp.
References lldb_private::CompletionRequest::AddCompletion(), and GetProcessInstances().
Referenced by lldb_private::CommandCompletions::ProcessPluginNames().
CreateArchitectureInstance()
std::unique_ptr< Architecture > PluginManager::CreateArchitectureInstance (const ArchSpec & arch) static
Definition at line 663 of file PluginManager.cpp.
References GetArchitectureInstances().
Referenced by lldb_private::Target::Arch::operator=().
CreateSettingForCPlusPlusLanguagePlugin()
bool PluginManager::CreateSettingForCPlusPlusLanguagePlugin (Debugger & debugger, const lldb::OptionValuePropertiesSP & properties_sp, llvm::StringRef description, bool is_global_property) static
Definition at line 2418 of file PluginManager.cpp.
References CreateSettingForPlugin(), and kCPlusPlusLanguagePlugin().
Referenced by lldb_private::CPlusPlusLanguage::DebuggerInitialize().
CreateSettingForDynamicLoaderPlugin()
bool PluginManager::CreateSettingForDynamicLoaderPlugin (Debugger & debugger, const lldb::OptionValuePropertiesSP & properties_sp, llvm::StringRef description, bool is_global_property) static
Definition at line 2262 of file PluginManager.cpp.
References CreateSettingForPlugin(), and kDynamicLoaderPluginName().
Referenced by DynamicLoaderDarwinKernel::DebuggerInitialize().
CreateSettingForJITLoaderPlugin()
bool PluginManager::CreateSettingForJITLoaderPlugin (Debugger & debugger, const lldb::OptionValuePropertiesSP & properties_sp, llvm::StringRef description, bool is_global_property) static
Definition at line 2356 of file PluginManager.cpp.
References CreateSettingForPlugin(), and kJITLoaderPluginName().
Referenced by JITLoaderGDB::DebuggerInitialize().
CreateSettingForObjectFilePlugin()
bool PluginManager::CreateSettingForObjectFilePlugin (Debugger & debugger, const lldb::OptionValuePropertiesSP & properties_sp, llvm::StringRef description, bool is_global_property) static
Definition at line 2328 of file PluginManager.cpp.
References CreateSettingForPlugin(), and kObjectFilePluginName().
Referenced by ObjectFilePECOFF::DebuggerInitialize().
CreateSettingForOperatingSystemPlugin()
bool PluginManager::CreateSettingForOperatingSystemPlugin (Debugger & debugger, const lldb::OptionValuePropertiesSP & properties_sp, llvm::StringRef description, bool is_global_property) static
Definition at line 2380 of file PluginManager.cpp.
References GetDebuggerPropertyForPlugins(), and kOperatingSystemPluginName().
CreateSettingForPlatformPlugin()
bool PluginManager::CreateSettingForPlatformPlugin (Debugger & debugger, const lldb::OptionValuePropertiesSP & properties_sp, llvm::StringRef description, bool is_global_property) static
Definition at line 2277 of file PluginManager.cpp.
References CreateSettingForPlugin(), GetDebuggerPropertyForPluginsOldStyle(), and kPlatformPluginName().
Referenced by lldb_private::platform_android::PlatformAndroid::DebuggerInitialize(), lldb_private::PlatformDarwin::DebuggerInitialize(), lldb_private::PlatformQemuUser::DebuggerInitialize(), and lldb_private::PlatformWasm::DebuggerInitialize().
CreateSettingForProcessPlugin()
bool PluginManager::CreateSettingForProcessPlugin (Debugger & debugger, const lldb::OptionValuePropertiesSP & properties_sp, llvm::StringRef description, bool is_global_property) static
Definition at line 2292 of file PluginManager.cpp.
References CreateSettingForPlugin(), and kProcessPluginName().
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::DebuggerInitialize(), and ProcessKDP::DebuggerInitialize().
CreateSettingForStructuredDataPlugin()
bool PluginManager::CreateSettingForStructuredDataPlugin (Debugger & debugger, const lldb::OptionValuePropertiesSP & properties_sp, llvm::StringRef description, bool is_global_property) static
Definition at line 2404 of file PluginManager.cpp.
References CreateSettingForPlugin(), and kStructuredDataPluginName().
Referenced by lldb_private::StructuredDataDarwinLog::DebuggerInitialize().
CreateSettingForSymbolFilePlugin()
bool PluginManager::CreateSettingForSymbolFilePlugin (Debugger & debugger, const lldb::OptionValuePropertiesSP & properties_sp, llvm::StringRef description, bool is_global_property) static
Definition at line 2342 of file PluginManager.cpp.
References CreateSettingForPlugin(), and kSymbolFilePluginName().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::DebuggerInitialize(), and SymbolFilePDB::DebuggerInitialize().
CreateSettingForSymbolLocatorPlugin()
bool PluginManager::CreateSettingForSymbolLocatorPlugin (Debugger & debugger, const lldb::OptionValuePropertiesSP & properties_sp, llvm::StringRef description, bool is_global_property) static
Definition at line 2306 of file PluginManager.cpp.
References CreateSettingForPlugin(), and kSymbolLocatorPluginName().
Referenced by lldb_private::SymbolLocatorDebuginfod::DebuggerInitialize().
CreateSettingForTracePlugin()
bool PluginManager::CreateSettingForTracePlugin (Debugger & debugger, const lldb::OptionValuePropertiesSP & properties_sp, llvm::StringRef description, bool is_global_property) static
Definition at line 2314 of file PluginManager.cpp.
References CreateSettingForPlugin(), and kTracePluginName().
Referenced by lldb_private::trace_intel_pt::TraceIntelPT::DebuggerInitialize().
DebuggerInitialize()
void PluginManager::DebuggerInitialize (Debugger & debugger) static
Definition at line 2108 of file PluginManager.cpp.
References GetDynamicLoaderInstances(), GetJITLoaderInstances(), GetLanguageInstances(), GetObjectFileInstances(), GetOperatingSystemInstances(), GetPlatformInstances(), GetProcessInstances(), GetScriptedInterfaceInstances(), GetStructuredDataPluginInstances(), GetSymbolFileInstances(), GetSymbolLocatorInstances(), GetTracePluginInstances(), and PluginInstances< Instance >::PerformDebuggerCallback().
Referenced by lldb_private::Debugger::InstanceInitialize().
DownloadObjectAndSymbolFile()
bool PluginManager::DownloadObjectAndSymbolFile (ModuleSpec & module_spec, Status & error, bool force_lookup = true, bool copy_executable = true) static
Definition at line 1648 of file PluginManager.cpp.
References error(), PluginInstances< Instance >::GetSnapshot(), and GetSymbolLocatorInstances().
Referenced by lldb::SBTarget::AddModule(), ProcessKDP::DoConnectRemote(), CommandObjectTargetModulesAdd::DoExecute(), CommandObjectTargetSymbolsAdd::DownloadObjectAndSymbolFile(), lldb_private::SymbolLocator::DownloadSymbolFileAsync(), lldb_private::DynamicLoader::LoadBinaryWithUUIDAndAddress(), DynamicLoaderDarwinKernel::KextImageInfo::LoadImageUsingMemoryModule(), DynamicLoaderFreeBSDKernel::KModImageInfo::LoadImageUsingMemoryModule(), and LookForDsymNextToExecutablePath().
FindSymbolFileInBundle()
FileSpec PluginManager::FindSymbolFileInBundle (const FileSpec & dsym_bundle_fspec, const UUID * uuid, const ArchSpec * arch) static
Definition at line 1663 of file PluginManager.cpp.
References PluginInstances< Instance >::GetSnapshot(), and GetSymbolLocatorInstances().
Referenced by lldb_private::SymbolLocatorDebugSymbols::LocateExecutableObjectFile(), LocateMacOSXFilesUsingDebugSymbols(), and lldb_private::PlatformDarwin::ResolveSymbolFile().
GetABICreateCallbackAtIndex()
ABICreateInstance PluginManager::GetABICreateCallbackAtIndex (uint32_t idx) static
Definition at line 636 of file PluginManager.cpp.
References GetABIInstances(), and PluginInstances< Instance >::GetCallbackAtIndex().
Referenced by lldb_private::ABI::FindPlugin().
GetABIPluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetABIPluginInfo () static
Definition at line 2429 of file PluginManager.cpp.
References GetABIInstances(), and PluginInstances< Instance >::GetPluginInfoForAllInstances().
Referenced by GetPluginNamespaces().
GetAllTypeSystemSupportedLanguagesForExpressions()
LanguageSet PluginManager::GetAllTypeSystemSupportedLanguagesForExpressions () static
Definition at line 1954 of file PluginManager.cpp.
References lldb_private::LanguageSet::bitvector, PluginInstances< Instance >::GetSnapshot(), and GetTypeSystemInstances().
Referenced by lldb_private::Language::GetLanguagesSupportingTypeSystemsForExpressions().
GetAllTypeSystemSupportedLanguagesForTypes()
LanguageSet PluginManager::GetAllTypeSystemSupportedLanguagesForTypes () static
Definition at line 1946 of file PluginManager.cpp.
References lldb_private::LanguageSet::bitvector, PluginInstances< Instance >::GetSnapshot(), and GetTypeSystemInstances().
Referenced by lldb_private::Language::GetLanguagesSupportingTypeSystems(), lldb_private::Process::PrintWarningUnsupportedLanguage(), and lldb_private::TypeSystem::SupportsLanguageStatic().
GetArchitecturePluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetArchitecturePluginInfo () static
Definition at line 2436 of file PluginManager.cpp.
References GetArchitectureInstances(), and PluginInstances< Instance >::GetPluginInfoForAllInstances().
Referenced by GetPluginNamespaces().
GetDisassemblerCreateCallbackAtIndex()
DisassemblerCreateInstance PluginManager::GetDisassemblerCreateCallbackAtIndex (uint32_t idx) static
Definition at line 694 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetDisassemblerInstances().
Referenced by lldb_private::Disassembler::FindPlugin().
GetDisassemblerCreateCallbackForPluginName()
DisassemblerCreateInstance PluginManager::GetDisassemblerCreateCallbackForPluginName (llvm::StringRef name) static
Definition at line 699 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackForName(), and GetDisassemblerInstances().
Referenced by lldb_private::Disassembler::FindPlugin().
GetDisassemblerPluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetDisassemblerPluginInfo () static
Definition at line 2444 of file PluginManager.cpp.
References GetDisassemblerInstances(), and PluginInstances< Instance >::GetPluginInfoForAllInstances().
Referenced by GetPluginNamespaces().
GetDynamicLoaderCreateCallbackAtIndex()
DynamicLoaderCreateInstance PluginManager::GetDynamicLoaderCreateCallbackAtIndex (uint32_t idx) static
Definition at line 728 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetDynamicLoaderInstances().
Referenced by lldb_private::DynamicLoader::FindPlugin().
GetDynamicLoaderCreateCallbackForPluginName()
DynamicLoaderCreateInstance PluginManager::GetDynamicLoaderCreateCallbackForPluginName (llvm::StringRef name) static
Definition at line 733 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackForName(), and GetDynamicLoaderInstances().
Referenced by lldb_private::DynamicLoader::FindPlugin().
GetDynamicLoaderPluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetDynamicLoaderPluginInfo () static
Definition at line 2452 of file PluginManager.cpp.
References GetDynamicLoaderInstances(), and PluginInstances< Instance >::GetPluginInfoForAllInstances().
Referenced by GetPluginNamespaces().
GetEmulateInstructionCreateCallbackAtIndex()
EmulateInstructionCreateInstance PluginManager::GetEmulateInstructionCreateCallbackAtIndex (uint32_t idx) static
Definition at line 789 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetEmulateInstructionInstances().
Referenced by lldb_private::EmulateInstruction::FindPlugin().
GetEmulateInstructionCreateCallbackForPluginName()
EmulateInstructionCreateInstance PluginManager::GetEmulateInstructionCreateCallbackForPluginName (llvm::StringRef name) static
Definition at line 794 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackForName(), and GetEmulateInstructionInstances().
Referenced by lldb_private::EmulateInstruction::FindPlugin().
GetEmulateInstructionPluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetEmulateInstructionPluginInfo () static
Definition at line 2461 of file PluginManager.cpp.
References GetEmulateInstructionInstances(), and PluginInstances< Instance >::GetPluginInfoForAllInstances().
Referenced by GetPluginNamespaces().
GetHighlighterCreateCallbackAtIndex()
HighlighterCreateInstance PluginManager::GetHighlighterCreateCallbackAtIndex (uint32_t idx) static
Definition at line 2102 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetHighlighterInstances().
Referenced by lldb_private::HighlighterManager::getHighlighterFor().
GetInstrumentationRuntimeCreateCallbackAtIndex()
InstrumentationRuntimeCreateInstance PluginManager::GetInstrumentationRuntimeCreateCallbackAtIndex (uint32_t idx) static
Definition at line 1899 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetInstrumentationRuntimeInstances().
Referenced by lldb_private::InstrumentationRuntime::ModulesDidLoad().
GetInstrumentationRuntimeGetTypeCallbackAtIndex()
InstrumentationRuntimeGetType PluginManager::GetInstrumentationRuntimeGetTypeCallbackAtIndex (uint32_t idx) static
Definition at line 1891 of file PluginManager.cpp.
References GetInstrumentationRuntimeInstances().
Referenced by lldb_private::InstrumentationRuntime::ModulesDidLoad().
GetInstrumentationRuntimePluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetInstrumentationRuntimePluginInfo () static
Definition at line 2470 of file PluginManager.cpp.
References GetInstrumentationRuntimeInstances(), and PluginInstances< Instance >::GetPluginInfoForAllInstances().
Referenced by GetPluginNamespaces().
GetJITLoaderCreateCallbackAtIndex()
JITLoaderCreateInstance PluginManager::GetJITLoaderCreateCallbackAtIndex (uint32_t idx) static
Definition at line 761 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetJITLoaderInstances().
Referenced by lldb_private::JITLoader::LoadPlugins().
GetJITLoaderPluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetJITLoaderPluginInfo () static
Definition at line 2478 of file PluginManager.cpp.
References GetJITLoaderInstances(), and PluginInstances< Instance >::GetPluginInfoForAllInstances().
Referenced by GetPluginNamespaces().
GetJSON()
llvm::json::Object PluginManager::GetJSON (llvm::StringRef pattern = "") static
Definition at line 430 of file PluginManager.cpp.
References GetPluginNamespaces(), and MatchPluginName().
GetLanguageCreateCallbackAtIndex()
LanguageCreateInstance PluginManager::GetLanguageCreateCallbackAtIndex (uint32_t idx) static
Definition at line 856 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetLanguageInstances().
Referenced by lldb_private::Language::FindPlugin().
GetLanguagePluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetLanguagePluginInfo () static
Definition at line 2486 of file PluginManager.cpp.
References GetLanguageInstances(), and PluginInstances< Instance >::GetPluginInfoForAllInstances().
Referenced by GetPluginNamespaces().
GetLanguageRuntimeCreateCallbackAtIndex()
LanguageRuntimeCreateInstance PluginManager::GetLanguageRuntimeCreateCallbackAtIndex (uint32_t idx) static
Definition at line 902 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetLanguageRuntimeInstances().
Referenced by lldb_private::LanguageRuntime::FindPlugin(), lldb_private::LanguageRuntime::GetExceptionPrecondition(), and lldb_private::LanguageRuntime::InitializeCommands().
GetLanguageRuntimeGetCommandObjectAtIndex()
LanguageRuntimeGetCommandObject PluginManager::GetLanguageRuntimeGetCommandObjectAtIndex (uint32_t idx) static
Definition at line 907 of file PluginManager.cpp.
References GetLanguageRuntimeInstances().
Referenced by lldb_private::LanguageRuntime::InitializeCommands().
GetLanguageRuntimeGetExceptionPreconditionAtIndex()
LanguageRuntimeGetExceptionPrecondition PluginManager::GetLanguageRuntimeGetExceptionPreconditionAtIndex (uint32_t idx) static
Definition at line 914 of file PluginManager.cpp.
References GetLanguageRuntimeInstances().
Referenced by lldb_private::LanguageRuntime::GetExceptionPrecondition().
GetLanguageRuntimePluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetLanguageRuntimePluginInfo () static
Definition at line 2495 of file PluginManager.cpp.
References GetLanguageRuntimeInstances(), and PluginInstances< Instance >::GetPluginInfoForAllInstances().
Referenced by GetPluginNamespaces().
GetMemoryHistoryCreateCallbackAtIndex()
MemoryHistoryCreateInstance PluginManager::GetMemoryHistoryCreateCallbackAtIndex (uint32_t idx) static
Definition at line 1850 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetMemoryHistoryInstances().
Referenced by lldb_private::MemoryHistory::FindPlugin().
GetMemoryHistoryPluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetMemoryHistoryPluginInfo () static
Definition at line 2503 of file PluginManager.cpp.
References GetMemoryHistoryInstances(), and PluginInstances< Instance >::GetPluginInfoForAllInstances().
Referenced by GetPluginNamespaces().
GetNumScriptedInterfaces()
uint32_t PluginManager::GetNumScriptedInterfaces () static
Definition at line 1998 of file PluginManager.cpp.
References GetScriptedInterfaceInstances(), and PluginInstances< Instance >::GetSnapshot().
Referenced by CommandObjectScriptingExtensionList::DoExecute().
GetObjectContainerCreateCallbackAtIndex()
ObjectContainerCreateInstance PluginManager::GetObjectContainerCreateCallbackAtIndex (uint32_t idx) static
Definition at line 1129 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetObjectContainerInstances().
Referenced by CreateObjectFromContainer().
GetObjectContainerCreateMemoryCallbackAtIndex()
ObjectContainerCreateMemoryInstance PluginManager::GetObjectContainerCreateMemoryCallbackAtIndex (uint32_t idx) static
Definition at line 1134 of file PluginManager.cpp.
References GetObjectContainerInstances().
Referenced by lldb_private::ObjectContainer::FindPlugin().
GetObjectContainerGetModuleSpecificationsCallbackAtIndex()
ObjectFileGetModuleSpecifications PluginManager::GetObjectContainerGetModuleSpecificationsCallbackAtIndex (uint32_t idx) static
Definition at line 1141 of file PluginManager.cpp.
References GetObjectContainerInstances().
Referenced by lldb_private::ObjectFile::GetModuleSpecifications().
GetObjectContainerPluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetObjectContainerPluginInfo () static
Definition at line 2512 of file PluginManager.cpp.
References GetObjectContainerInstances(), and PluginInstances< Instance >::GetPluginInfoForAllInstances().
Referenced by GetPluginNamespaces().
GetObjectFileCreateCallbackAtIndex()
ObjectFileCreateInstance PluginManager::GetObjectFileCreateCallbackAtIndex (uint32_t idx) static
Definition at line 998 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetObjectFileInstances().
Referenced by lldb_private::ObjectFile::FindPlugin().
GetObjectFileCreateMemoryCallbackAtIndex()
ObjectFileCreateMemoryInstance PluginManager::GetObjectFileCreateMemoryCallbackAtIndex (uint32_t idx) static
Definition at line 1003 of file PluginManager.cpp.
References GetObjectFileInstances().
Referenced by lldb_private::ObjectFile::FindPlugin().
GetObjectFileCreateMemoryCallbackForPluginName()
ObjectFileCreateMemoryInstance PluginManager::GetObjectFileCreateMemoryCallbackForPluginName (llvm::StringRef name) static
Definition at line 1018 of file PluginManager.cpp.
References GetObjectFileInstances().
GetObjectFileGetModuleSpecificationsCallbackAtIndex()
ObjectFileGetModuleSpecifications PluginManager::GetObjectFileGetModuleSpecificationsCallbackAtIndex (uint32_t idx) static
Definition at line 1010 of file PluginManager.cpp.
References GetObjectFileInstances().
Referenced by lldb_private::ObjectFile::GetModuleSpecifications().
GetObjectFilePluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetObjectFilePluginInfo () static
Definition at line 2520 of file PluginManager.cpp.
References GetObjectFileInstances(), and PluginInstances< Instance >::GetPluginInfoForAllInstances().
Referenced by GetPluginNamespaces().
GetOperatingSystemCreateCallbackAtIndex()
OperatingSystemCreateInstance PluginManager::GetOperatingSystemCreateCallbackAtIndex (uint32_t idx) static
Definition at line 823 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetOperatingSystemInstances().
Referenced by lldb_private::OperatingSystem::FindPlugin().
GetOperatingSystemCreateCallbackForPluginName()
OperatingSystemCreateInstance PluginManager::GetOperatingSystemCreateCallbackForPluginName (llvm::StringRef name) static
Definition at line 828 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackForName(), and GetOperatingSystemInstances().
Referenced by lldb_private::OperatingSystem::FindPlugin().
GetOperatingSystemPluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetOperatingSystemPluginInfo () static
Definition at line 2529 of file PluginManager.cpp.
References GetOperatingSystemInstances(), and PluginInstances< Instance >::GetPluginInfoForAllInstances().
Referenced by GetPluginNamespaces().
GetPlatformCreateCallbackAtIndex()
PlatformCreateInstance PluginManager::GetPlatformCreateCallbackAtIndex (uint32_t idx) static
Definition at line 1180 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetPlatformInstances().
Referenced by lldb_private::PlatformList::GetOrCreate(), and lldb_private::PlatformList::LoadPlatformBinaryAndSetup().
GetPlatformCreateCallbackForPluginName()
PlatformCreateInstance PluginManager::GetPlatformCreateCallbackForPluginName (llvm::StringRef name) static
Definition at line 1185 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackForName(), and GetPlatformInstances().
Referenced by lldb_private::Platform::Create().
GetPlatformPluginDescriptionAtIndex()
llvm::StringRef PluginManager::GetPlatformPluginDescriptionAtIndex (uint32_t idx) static
Definition at line 1175 of file PluginManager.cpp.
References PluginInstances< Instance >::GetDescriptionAtIndex(), and GetPlatformInstances().
Referenced by CommandObjectPlatformList::DoExecute(), and lldb::SBDebugger::GetAvailablePlatformInfoAtIndex().
GetPlatformPluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetPlatformPluginInfo () static
Definition at line 2537 of file PluginManager.cpp.
References GetPlatformInstances(), and PluginInstances< Instance >::GetPluginInfoForAllInstances().
Referenced by GetPluginNamespaces().
GetPlatformPluginNameAtIndex()
llvm::StringRef PluginManager::GetPlatformPluginNameAtIndex (uint32_t idx) static
Definition at line 1170 of file PluginManager.cpp.
References PluginInstances< Instance >::GetNameAtIndex(), and GetPlatformInstances().
Referenced by CommandObjectPlatformList::DoExecute(), lldb::SBDebugger::GetAvailablePlatformInfoAtIndex(), and lldb::SBDebugger::GetNumAvailablePlatforms().
GetPluginNamespaces()
llvm::ArrayRef< PluginNamespace > PluginManager::GetPluginNamespaces () static
Definition at line 255 of file PluginManager.cpp.
References GetABIPluginInfo(), GetArchitecturePluginInfo(), GetDisassemblerPluginInfo(), GetDynamicLoaderPluginInfo(), GetEmulateInstructionPluginInfo(), GetInstrumentationRuntimePluginInfo(), GetJITLoaderPluginInfo(), GetLanguagePluginInfo(), GetLanguageRuntimePluginInfo(), GetMemoryHistoryPluginInfo(), GetObjectContainerPluginInfo(), GetObjectFilePluginInfo(), GetOperatingSystemPluginInfo(), GetPlatformPluginInfo(), GetProcessPluginInfo(), GetRegisterTypeBuilderPluginInfo(), GetREPLPluginInfo(), GetScriptedInterfacePluginInfo(), GetScriptInterpreterPluginInfo(), GetStructuredDataPluginInfo(), GetSymbolFilePluginInfo(), GetSymbolLocatorPluginInfo(), GetSymbolVendorPluginInfo(), GetSystemRuntimePluginInfo(), GetTraceExporterPluginInfo(), GetTracePluginInfo(), GetTypeSystemPluginInfo(), GetUnwindAssemblyPluginInfo(), SetABIPluginEnabled(), SetArchitecturePluginEnabled(), SetDisassemblerPluginEnabled(), SetDynamicLoaderPluginEnabled(), SetEmulateInstructionPluginEnabled(), SetInstrumentationRuntimePluginEnabled(), SetJITLoaderPluginEnabled(), SetLanguagePluginEnabled(), SetLanguageRuntimePluginEnabled(), SetMemoryHistoryPluginEnabled(), SetObjectContainerPluginEnabled(), SetObjectFilePluginEnabled(), SetOperatingSystemPluginEnabled(), SetPlatformPluginEnabled(), SetProcessPluginEnabled(), SetRegisterTypeBuilderPluginEnabled(), SetREPLPluginEnabled(), SetScriptedInterfacePluginEnabled(), SetScriptInterpreterPluginEnabled(), SetStructuredDataPluginEnabled(), SetSymbolFilePluginEnabled(), SetSymbolLocatorPluginEnabled(), SetSymbolVendorPluginEnabled(), SetSystemRuntimePluginEnabled(), SetTraceExporterPluginEnabled(), SetTracePluginEnabled(), SetTypeSystemPluginEnabled(), and SetUnwindAssemblyPluginEnabled().
Referenced by AutoCompletePluginName(), and GetJSON().
GetProcessCreateCallbackAtIndex()
ProcessCreateInstance PluginManager::GetProcessCreateCallbackAtIndex (uint32_t idx) static
Definition at line 1229 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetProcessInstances().
Referenced by lldb_private::Process::FindPlugin().
GetProcessCreateCallbackForPluginName()
ProcessCreateInstance PluginManager::GetProcessCreateCallbackForPluginName (llvm::StringRef name) static
Definition at line 1234 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackForName(), and GetProcessInstances().
Referenced by lldb_private::Process::FindPlugin().
GetProcessPluginDescriptionAtIndex()
llvm::StringRef PluginManager::GetProcessPluginDescriptionAtIndex (uint32_t idx) static
Definition at line 1224 of file PluginManager.cpp.
References PluginInstances< Instance >::GetDescriptionAtIndex(), and GetProcessInstances().
GetProcessPluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetProcessPluginInfo () static
Definition at line 2545 of file PluginManager.cpp.
References PluginInstances< Instance >::GetPluginInfoForAllInstances(), and GetProcessInstances().
Referenced by GetPluginNamespaces().
GetProcessPluginNameAtIndex()
llvm::StringRef PluginManager::GetProcessPluginNameAtIndex (uint32_t idx) static
Definition at line 1219 of file PluginManager.cpp.
References PluginInstances< Instance >::GetNameAtIndex(), and GetProcessInstances().
GetProtocolCreateCallbackForPluginName()
ProtocolServerCreateInstance PluginManager::GetProtocolCreateCallbackForPluginName (llvm::StringRef name) static
Definition at line 1274 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackForName(), and GetProtocolServerInstances().
Referenced by lldb_private::ProtocolServer::GetOrCreate().
GetProtocolServerPluginNameAtIndex()
llvm::StringRef PluginManager::GetProtocolServerPluginNameAtIndex (uint32_t idx) static
Definition at line 1269 of file PluginManager.cpp.
References PluginInstances< Instance >::GetNameAtIndex(), and GetProtocolServerInstances().
Referenced by lldb_private::ProtocolServer::GetSupportedProtocols().
GetRegisterTypeBuilder()
lldb::RegisterTypeBuilderSP PluginManager::GetRegisterTypeBuilder (Target & target) static
Definition at line 1309 of file PluginManager.cpp.
References PluginInstances< Instance >::GetInstanceAtIndex(), and GetRegisterTypeBuilderInstances().
Referenced by lldb_private::Target::GetRegisterType().
GetRegisterTypeBuilderPluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetRegisterTypeBuilderPluginInfo () static
Definition at line 2560 of file PluginManager.cpp.
References PluginInstances< Instance >::GetPluginInfoForAllInstances(), and GetRegisterTypeBuilderInstances().
Referenced by GetPluginNamespaces().
GetREPLAllTypeSystemSupportedLanguages()
LanguageSet PluginManager::GetREPLAllTypeSystemSupportedLanguages () static
Definition at line 2065 of file PluginManager.cpp.
References lldb_private::LanguageSet::bitvector, GetREPLInstances(), and PluginInstances< Instance >::GetSnapshot().
Referenced by lldb_private::Language::GetLanguagesSupportingREPLs().
GetREPLCreateCallbackAtIndex()
REPLCreateInstance PluginManager::GetREPLCreateCallbackAtIndex (uint32_t idx) static
Definition at line 2055 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetREPLInstances().
Referenced by lldb_private::REPL::Create().
GetREPLPluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetREPLPluginInfo () static
Definition at line 2552 of file PluginManager.cpp.
References PluginInstances< Instance >::GetPluginInfoForAllInstances(), and GetREPLInstances().
Referenced by GetPluginNamespaces().
GetREPLSupportedLanguagesAtIndex()
LanguageSet PluginManager::GetREPLSupportedLanguagesAtIndex (uint32_t idx) static
Definition at line 2059 of file PluginManager.cpp.
References GetREPLInstances().
Referenced by lldb_private::REPL::Create().
GetSaveCorePluginNames()
std::vector< llvm::StringRef > PluginManager::GetSaveCorePluginNames () static
Definition at line 1079 of file PluginManager.cpp.
References GetObjectFileInstances(), and PluginInstances< Instance >::GetSnapshot().
Referenced by CommandObjectProcessSaveCore::CommandOptions::GetDefinitions(), and lldb_private::SaveCoreOptions::SetPluginName().
GetScriptedFrameProviderCreateCallbackAtIndex()
ScriptedFrameProviderCreateInstance PluginManager::GetScriptedFrameProviderCreateCallbackAtIndex (uint32_t idx) static
Definition at line 1438 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetScriptedFrameProviderInstances().
Referenced by lldb_private::SyntheticFrameProvider::CreateInstance().
GetScriptedInterfaceDescriptionAtIndex()
llvm::StringRef PluginManager::GetScriptedInterfaceDescriptionAtIndex (uint32_t idx) static
Definition at line 2007 of file PluginManager.cpp.
References PluginInstances< Instance >::GetDescriptionAtIndex(), and GetScriptedInterfaceInstances().
Referenced by CommandObjectScriptingExtensionList::DoExecute().
GetScriptedInterfaceLanguageAtIndex()
lldb::ScriptLanguage PluginManager::GetScriptedInterfaceLanguageAtIndex (uint32_t idx) static
Definition at line 2012 of file PluginManager.cpp.
References lldb::eScriptLanguageNone, and GetScriptedInterfaceInstances().
Referenced by CommandObjectScriptingExtensionList::DoExecute().
GetScriptedInterfaceNameAtIndex()
llvm::StringRef PluginManager::GetScriptedInterfaceNameAtIndex (uint32_t idx) static
Definition at line 2002 of file PluginManager.cpp.
References PluginInstances< Instance >::GetNameAtIndex(), and GetScriptedInterfaceInstances().
Referenced by CommandObjectScriptingExtensionList::DoExecute().
GetScriptedInterfacePluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetScriptedInterfacePluginInfo () static
Definition at line 2578 of file PluginManager.cpp.
References PluginInstances< Instance >::GetPluginInfoForAllInstances(), and GetScriptedInterfaceInstances().
Referenced by GetPluginNamespaces().
GetScriptedInterfaceUsagesAtIndex()
ScriptedInterfaceUsages PluginManager::GetScriptedInterfaceUsagesAtIndex (uint32_t idx) static
Definition at line 2019 of file PluginManager.cpp.
References GetScriptedInterfaceInstances().
Referenced by CommandObjectScriptingExtensionList::DoExecute().
GetScriptInterpreterCreateCallbackAtIndex()
ScriptInterpreterCreateInstance PluginManager::GetScriptInterpreterCreateCallbackAtIndex (uint32_t idx) static
Definition at line 1355 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetScriptInterpreterInstances().
GetScriptInterpreterForLanguage()
lldb::ScriptInterpreterSP PluginManager::GetScriptInterpreterForLanguage (lldb::ScriptLanguage script_lang, Debugger & debugger) static
Definition at line 1360 of file PluginManager.cpp.
References lldb::eScriptLanguageNone, GetScriptInterpreterInstances(), and PluginInstances< Instance >::GetSnapshot().
Referenced by lldb_private::Debugger::GetScriptInterpreter().
GetScriptInterpreterLibraryPath()
FileSpec PluginManager::GetScriptInterpreterLibraryPath (lldb::ScriptLanguage script_lang) static
Definition at line 1377 of file PluginManager.cpp.
References GetScriptInterpreterInstances(), and PluginInstances< Instance >::GetSnapshot().
Referenced by lldb::SBHostOS::GetLLDBPath(), and lldb::SBHostOS::GetScriptPath().
GetScriptInterpreterPluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetScriptInterpreterPluginInfo () static
Definition at line 2569 of file PluginManager.cpp.
References PluginInstances< Instance >::GetPluginInfoForAllInstances(), and GetScriptInterpreterInstances().
Referenced by GetPluginNamespaces().
GetSettingForCPlusPlusLanguagePlugin()
lldb::OptionValuePropertiesSP PluginManager::GetSettingForCPlusPlusLanguagePlugin (Debugger & debugger, llvm::StringRef setting_name) static
Definition at line 2413 of file PluginManager.cpp.
References GetSettingForPlugin(), and kCPlusPlusLanguagePlugin().
Referenced by lldb_private::CPlusPlusLanguage::DebuggerInitialize().
GetSettingForDynamicLoaderPlugin()
lldb::OptionValuePropertiesSP PluginManager::GetSettingForDynamicLoaderPlugin (Debugger & debugger, llvm::StringRef setting_name) static
Definition at line 2257 of file PluginManager.cpp.
References GetSettingForPlugin(), and kDynamicLoaderPluginName().
Referenced by DynamicLoaderDarwinKernel::DebuggerInitialize().
GetSettingForJITLoaderPlugin()
lldb::OptionValuePropertiesSP PluginManager::GetSettingForJITLoaderPlugin (Debugger & debugger, llvm::StringRef setting_name) static
Definition at line 2351 of file PluginManager.cpp.
References GetSettingForPlugin(), and kJITLoaderPluginName().
Referenced by JITLoaderGDB::DebuggerInitialize().
GetSettingForObjectFilePlugin()
lldb::OptionValuePropertiesSP PluginManager::GetSettingForObjectFilePlugin (Debugger & debugger, llvm::StringRef setting_name) static
Definition at line 2323 of file PluginManager.cpp.
References GetSettingForPlugin(), and kObjectFilePluginName().
Referenced by ObjectFilePECOFF::DebuggerInitialize().
GetSettingForOperatingSystemPlugin()
lldb::OptionValuePropertiesSP PluginManager::GetSettingForOperatingSystemPlugin (Debugger & debugger, llvm::StringRef setting_name) static
Definition at line 2366 of file PluginManager.cpp.
References GetDebuggerPropertyForPlugins(), and kOperatingSystemPluginName().
GetSettingForPlatformPlugin()
lldb::OptionValuePropertiesSP PluginManager::GetSettingForPlatformPlugin (Debugger & debugger, llvm::StringRef setting_name) static
Definition at line 2271 of file PluginManager.cpp.
References GetDebuggerPropertyForPluginsOldStyle(), GetSettingForPlugin(), and kPlatformPluginName().
Referenced by lldb_private::platform_android::PlatformAndroid::DebuggerInitialize(), lldb_private::PlatformDarwin::DebuggerInitialize(), lldb_private::PlatformQemuUser::DebuggerInitialize(), lldb_private::PlatformWasm::DebuggerInitialize(), and lldb_private::StructuredDataDarwinLog::DebuggerInitialize().
GetSettingForProcessPlugin()
lldb::OptionValuePropertiesSP PluginManager::GetSettingForProcessPlugin (Debugger & debugger, llvm::StringRef setting_name) static
Definition at line 2287 of file PluginManager.cpp.
References GetSettingForPlugin(), and kProcessPluginName().
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::DebuggerInitialize(), lldb_private::trace_intel_pt::TraceIntelPT::DebuggerInitialize(), and ProcessKDP::DebuggerInitialize().
GetSettingForStructuredDataPlugin()
lldb::OptionValuePropertiesSP PluginManager::GetSettingForStructuredDataPlugin (Debugger & debugger, llvm::StringRef setting_name) static
Definition at line 2399 of file PluginManager.cpp.
References GetSettingForPlugin(), and kStructuredDataPluginName().
GetSettingForSymbolFilePlugin()
lldb::OptionValuePropertiesSP PluginManager::GetSettingForSymbolFilePlugin (Debugger & debugger, llvm::StringRef setting_name) static
Definition at line 2337 of file PluginManager.cpp.
References GetSettingForPlugin(), and kSymbolFilePluginName().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::DebuggerInitialize(), and SymbolFilePDB::DebuggerInitialize().
GetSettingForSymbolLocatorPlugin()
lldb::OptionValuePropertiesSP PluginManager::GetSettingForSymbolLocatorPlugin (Debugger & debugger, llvm::StringRef setting_name) static
Definition at line 2301 of file PluginManager.cpp.
References GetSettingForPlugin(), and kSymbolLocatorPluginName().
Referenced by lldb_private::SymbolLocatorDebuginfod::DebuggerInitialize().
GetStructuredDataFilterCallbackAtIndex()
StructuredDataFilterLaunchInfo PluginManager::GetStructuredDataFilterCallbackAtIndex (uint32_t idx, bool & iteration_complete) static
Definition at line 1487 of file PluginManager.cpp.
References GetStructuredDataPluginInstances().
Referenced by lldb_private::Platform::DebugProcess().
GetStructuredDataPluginCreateCallbackAtIndex()
StructuredDataPluginCreateInstance PluginManager::GetStructuredDataPluginCreateCallbackAtIndex (uint32_t idx) static
Definition at line 1482 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetStructuredDataPluginInstances().
Referenced by lldb_private::Process::MapSupportedStructuredDataPlugins().
GetStructuredDataPluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetStructuredDataPluginInfo () static
Definition at line 2586 of file PluginManager.cpp.
References PluginInstances< Instance >::GetPluginInfoForAllInstances(), and GetStructuredDataPluginInstances().
Referenced by GetPluginNamespaces().
GetSymbolFileCreateCallbackAtIndex()
SymbolFileCreateInstance PluginManager::GetSymbolFileCreateCallbackAtIndex (uint32_t idx) static
Definition at line 1521 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetSymbolFileInstances().
Referenced by lldb_private::SymbolFile::FindPlugin().
GetSymbolFilePluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetSymbolFilePluginInfo () static
Definition at line 2594 of file PluginManager.cpp.
References PluginInstances< Instance >::GetPluginInfoForAllInstances(), and GetSymbolFileInstances().
Referenced by GetPluginNamespaces().
GetSymbolLocatorCreateCallbackAtIndex()
SymbolLocatorCreateInstance PluginManager::GetSymbolLocatorCreateCallbackAtIndex (uint32_t idx) static
Definition at line 1603 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetSymbolLocatorInstances().
GetSymbolLocatorPluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetSymbolLocatorPluginInfo () static
Definition at line 2602 of file PluginManager.cpp.
References PluginInstances< Instance >::GetPluginInfoForAllInstances(), and GetSymbolLocatorInstances().
Referenced by GetPluginNamespaces().
GetSymbolVendorCreateCallbackAtIndex()
SymbolVendorCreateInstance PluginManager::GetSymbolVendorCreateCallbackAtIndex (uint32_t idx) static
Definition at line 1548 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetSymbolVendorInstances().
Referenced by lldb_private::SymbolVendor::FindPlugin().
GetSymbolVendorPluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetSymbolVendorPluginInfo () static
Definition at line 2610 of file PluginManager.cpp.
References PluginInstances< Instance >::GetPluginInfoForAllInstances(), and GetSymbolVendorInstances().
Referenced by GetPluginNamespaces().
GetSyntheticFrameProviderCreateCallbackForPluginName()
SyntheticFrameProviderCreateInstance PluginManager::GetSyntheticFrameProviderCreateCallbackForPluginName (llvm::StringRef name) static
Definition at line 1432 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackForName(), and GetSyntheticFrameProviderInstances().
Referenced by lldb_private::SyntheticFrameProvider::CreateInstance().
GetSystemRuntimeCreateCallbackAtIndex()
SystemRuntimeCreateInstance PluginManager::GetSystemRuntimeCreateCallbackAtIndex (uint32_t idx) static
Definition at line 943 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetSystemRuntimeInstances().
Referenced by lldb_private::SystemRuntime::FindPlugin().
GetSystemRuntimePluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetSystemRuntimePluginInfo () static
Definition at line 2618 of file PluginManager.cpp.
References PluginInstances< Instance >::GetPluginInfoForAllInstances(), and GetSystemRuntimeInstances().
Referenced by GetPluginNamespaces().
GetThreadTraceExportCommandCreatorAtIndex()
ThreadTraceExportCommandCreator PluginManager::GetThreadTraceExportCommandCreatorAtIndex (uint32_t index) static
Return the callback used to create the CommandObject that will be listed under "thread trace export".
Can be null.
Definition at line 1788 of file PluginManager.cpp.
References GetTraceExporterInstances().
Referenced by CommandObjectTraceExport::CommandObjectTraceExport().
GetTraceCreateCallback()
TraceCreateInstanceFromBundle PluginManager::GetTraceCreateCallback (llvm::StringRef plugin_name) static
Definition at line 1720 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackForName(), and GetTracePluginInstances().
Referenced by lldb_private::Trace::FindPluginForPostMortemProcess().
GetTraceCreateCallbackForLiveProcess()
TraceCreateInstanceForLiveProcess PluginManager::GetTraceCreateCallbackForLiveProcess (llvm::StringRef plugin_name) static
Definition at line 1725 of file PluginManager.cpp.
References GetTracePluginInstances().
Referenced by lldb_private::Trace::FindPluginForLiveProcess().
GetTraceExporterCreateCallback()
TraceExporterCreateInstance PluginManager::GetTraceExporterCreateCallback (llvm::StringRef plugin_name) static
Definition at line 1778 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackForName(), and GetTraceExporterInstances().
Referenced by lldb_private::TraceExporter::FindPlugin().
GetTraceExporterPluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetTraceExporterPluginInfo () static
Definition at line 2633 of file PluginManager.cpp.
References PluginInstances< Instance >::GetPluginInfoForAllInstances(), and GetTraceExporterInstances().
Referenced by GetPluginNamespaces().
GetTraceExporterPluginNameAtIndex()
llvm::StringRef PluginManager::GetTraceExporterPluginNameAtIndex (uint32_t index) static
Definition at line 1796 of file PluginManager.cpp.
References PluginInstances< Instance >::GetNameAtIndex(), and GetTraceExporterInstances().
Referenced by CommandObjectTraceExport::CommandObjectTraceExport().
GetTracePluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetTracePluginInfo () static
Definition at line 2626 of file PluginManager.cpp.
References PluginInstances< Instance >::GetPluginInfoForAllInstances(), and GetTracePluginInstances().
Referenced by GetPluginNamespaces().
GetTraceSchema() [1/2]
llvm::StringRef PluginManager::GetTraceSchema (llvm::StringRef plugin_name) static
Get the JSON schema for a trace bundle description file corresponding to the given plugin.
Parameters
[in] plugin_name The name of the plugin.
Returns
An empty StringRef if no plugin was found with that plugin name, otherwise the actual schema is returned.
Definition at line 1733 of file PluginManager.cpp.
References GetTracePluginInstances().
Referenced by CommandObjectTraceSchema::DoExecute(), and lldb_private::Trace::FindPluginSchema().
GetTraceSchema() [2/2]
llvm::StringRef PluginManager::GetTraceSchema (size_t index) static
Get the JSON schema for a trace bundle description file corresponding to the plugin given by its index.
Parameters
[in] index The index of the plugin to get the schema of.
Returns
An empty StringRef if the index is greater than or equal to the number plugins, otherwise the actual schema is returned.
Definition at line 1739 of file PluginManager.cpp.
References GetTracePluginInstances().
GetTypeSystemCreateCallbackAtIndex()
TypeSystemCreateInstance PluginManager::GetTypeSystemCreateCallbackAtIndex (uint32_t idx) static
Definition at line 1942 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetTypeSystemInstances().
Referenced by CreateInstanceHelper().
GetTypeSystemPluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetTypeSystemPluginInfo () static
Definition at line 2641 of file PluginManager.cpp.
References PluginInstances< Instance >::GetPluginInfoForAllInstances(), and GetTypeSystemInstances().
Referenced by GetPluginNamespaces().
GetUnwindAssemblyCreateCallbackAtIndex()
UnwindAssemblyCreateInstance PluginManager::GetUnwindAssemblyCreateCallbackAtIndex (uint32_t idx) static
Definition at line 1823 of file PluginManager.cpp.
References PluginInstances< Instance >::GetCallbackAtIndex(), and GetUnwindAssemblyInstances().
Referenced by lldb_private::UnwindAssembly::FindPlugin().
GetUnwindAssemblyPluginInfo()
std::vector< RegisteredPluginInfo > PluginManager::GetUnwindAssemblyPluginInfo () static
Definition at line 2649 of file PluginManager.cpp.
References PluginInstances< Instance >::GetPluginInfoForAllInstances(), and GetUnwindAssemblyInstances().
Referenced by GetPluginNamespaces().
Initialize()
void PluginManager::Initialize () static
Definition at line 227 of file PluginManager.cpp.
References lldb_private::FileSystem::EnumerateDirectory(), lldb_private::FileSystem::Instance(), PluginDir::LoadAnyDylib, PluginDir::LoadOnlyWithLLDBPrefix, and LoadPluginCallback().
Referenced by lldb_private::SystemInitializerFull::Initialize().
IsRegisteredObjectFilePluginName()
bool PluginManager::IsRegisteredObjectFilePluginName (llvm::StringRef name) static
Definition at line 974 of file PluginManager.cpp.
References PluginInstances< Instance >::GetInstanceForName(), and GetObjectFileInstances().
LocateExecutableObjectFile()
ModuleSpec PluginManager::LocateExecutableObjectFile (const ModuleSpec & module_spec, StatisticsMap & map) static
Definition at line 1608 of file PluginManager.cpp.
References lldb_private::StatisticsMap::add(), elapsed(), lldb_private::StatsDuration::get(), PluginInstances< Instance >::GetSnapshot(), and GetSymbolLocatorInstances().
Referenced by SymbolVendorELF::CreateInstance(), ProcessKDP::DoConnectRemote(), lldb_private::ModuleList::GetSharedModule(), and lldb_private::DynamicLoader::LoadBinaryWithUUIDAndAddress().
LocateExecutableSymbolFile()
FileSpec PluginManager::LocateExecutableSymbolFile (const ModuleSpec & module_spec, const FileSpecList & default_search_paths, StatisticsMap & map) static
Definition at line 1627 of file PluginManager.cpp.
References lldb_private::StatisticsMap::add(), elapsed(), lldb_private::StatsDuration::get(), PluginInstances< Instance >::GetSnapshot(), and GetSymbolLocatorInstances().
Referenced by lldb_private::wasm::SymbolVendorWasm::CreateInstance(), SymbolVendorELF::CreateInstance(), SymbolVendorMacOSX::CreateInstance(), SymbolVendorPECOFF::CreateInstance(), ProcessKDP::DoConnectRemote(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwpSymbolFile(), and lldb_private::DynamicLoader::LoadBinaryWithUUIDAndAddress().
MatchPluginName()
bool PluginManager::MatchPluginName (llvm::StringRef pattern, const PluginNamespace & plugin_ns, const RegisteredPluginInfo & plugin) static
Definition at line 451 of file PluginManager.cpp.
References lldb_private::PluginNamespace::name, and lldb_private::RegisteredPluginInfo::name.
Referenced by GetJSON().
RegisterPlugin() [1/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, ABICreateInstance create_callback) static
Definition at line 626 of file PluginManager.cpp.
References GetABIInstances(), and PluginInstances< Instance >::RegisterPlugin().
Referenced by ABIMacOSX_arm64::Initialize(), ABIMacOSX_arm::Initialize(), ABIMacOSX_i386::Initialize(), ABISysV_arc::Initialize(), ABISysV_arm64::Initialize(), ABISysV_arm::Initialize(), ABISysV_hexagon::Initialize(), ABISysV_i386::Initialize(), ABISysV_loongarch::Initialize(), ABISysV_mips64::Initialize(), ABISysV_mips::Initialize(), ABISysV_msp430::Initialize(), ABISysV_ppc64::Initialize(), ABISysV_ppc::Initialize(), ABISysV_riscv::Initialize(), ABISysV_s390x::Initialize(), ABISysV_x86_64::Initialize(), ABIWindows_x86_64::Initialize(), DisassemblerLLVMC::Initialize(), DynamicLoaderDarwinKernel::Initialize(), DynamicLoaderFreeBSDKernel::Initialize(), DynamicLoaderHexagonDYLD::Initialize(), DynamicLoaderMacOS::Initialize(), DynamicLoaderMacOSXDYLD::Initialize(), DynamicLoaderPOSIXDYLD::Initialize(), DynamicLoaderStatic::Initialize(), EmulateInstructionARM64::Initialize(), EmulateInstructionMIPS64::Initialize(), EmulateInstructionMIPS::Initialize(), InstrumentationRuntimeASanLibsanitizers::Initialize(), JITLoaderGDB::Initialize(), lldb_private::AppleObjCRuntimeV1::Initialize(), lldb_private::AppleObjCRuntimeV2::Initialize(), lldb_private::ArchitectureAArch64::Initialize(), lldb_private::ArchitectureArm::Initialize(), lldb_private::ArchitectureMips::Initialize(), lldb_private::ArchitecturePPC64::Initialize(), lldb_private::breakpad::ObjectFileBreakpad::Initialize(), lldb_private::breakpad::SymbolFileBreakpad::Initialize(), lldb_private::ClangHighlighter::Initialize(), lldb_private::ClangREPL::Initialize(), lldb_private::CPlusPlusLanguage::Initialize(), lldb_private::ctf::TraceExporterCTF::Initialize(), lldb_private::DefaultHighlighter::Initialize(), lldb_private::DynamicLoaderWindowsDYLD::Initialize(), lldb_private::EmulateInstructionARM::Initialize(), lldb_private::EmulateInstructionLoongArch::Initialize(), lldb_private::EmulateInstructionPPC64::Initialize(), lldb_private::EmulateInstructionRISCV::Initialize(), lldb_private::GNUstepObjCRuntime::Initialize(), lldb_private::InstrumentationRuntimeASan::Initialize(), lldb_private::InstrumentationRuntimeBoundsSafety::Initialize(), lldb_private::InstrumentationRuntimeMainThreadChecker::Initialize(), lldb_private::InstrumentationRuntimeTSan::Initialize(), lldb_private::InstrumentationRuntimeUBSan::Initialize(), lldb_private::ItaniumABILanguageRuntime::Initialize(), lldb_private::mcp::ProtocolServerMCP::Initialize(), lldb_private::MemoryHistoryASan::Initialize(), lldb_private::minidump::ProcessMinidump::Initialize(), lldb_private::npdb::SymbolFileNativePDB::Initialize(), lldb_private::ObjCLanguage::Initialize(), lldb_private::ObjCPlusPlusLanguage::Initialize(), lldb_private::ObjectContainerMachOFileset::Initialize(), lldb_private::ObjectFileJIT::Initialize(), lldb_private::ObjectFileJSON::Initialize(), lldb_private::ObjectFilePDB::Initialize(), lldb_private::OperatingSystemPythonInterface::Initialize(), lldb_private::platform_aix::PlatformAIX::Initialize(), lldb_private::platform_android::PlatformAndroid::Initialize(), lldb_private::platform_freebsd::PlatformFreeBSD::Initialize(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::Initialize(), lldb_private::platform_linux::PlatformLinux::Initialize(), lldb_private::platform_netbsd::PlatformNetBSD::Initialize(), lldb_private::platform_openbsd::PlatformOpenBSD::Initialize(), lldb_private::PlatformDarwin::Initialize(), lldb_private::PlatformMacOSX::Initialize(), lldb_private::PlatformQemuUser::Initialize(), lldb_private::PlatformRemoteAppleBridge::Initialize(), lldb_private::PlatformRemoteAppleTV::Initialize(), lldb_private::PlatformRemoteAppleWatch::Initialize(), lldb_private::PlatformRemoteAppleXR::Initialize(), lldb_private::PlatformRemoteiOS::Initialize(), lldb_private::PlatformRemoteMacOSX::Initialize(), lldb_private::PlatformWasm::Initialize(), lldb_private::PlatformWindows::Initialize(), lldb_private::plugin::dwarf::SymbolFileDWARF::Initialize(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::Initialize(), lldb_private::process_gdb_remote::ProcessGDBRemote::Initialize(), lldb_private::ProcessTrace::Initialize(), lldb_private::ProcessWindows::Initialize(), lldb_private::RegisterTypeBuilderClang::Initialize(), lldb_private::RustTreeSitterHighlighter::Initialize(), lldb_private::ScriptedBreakpointPythonInterface::Initialize(), lldb_private::ScriptedFrameProvider::Initialize(), lldb_private::ScriptedFrameProviderPythonInterface::Initialize(), lldb_private::ScriptedPlatformPythonInterface::Initialize(), lldb_private::ScriptedProcess::Initialize(), lldb_private::ScriptedProcessPythonInterface::Initialize(), lldb_private::ScriptedStopHookPythonInterface::Initialize(), lldb_private::ScriptedThreadPlanPythonInterface::Initialize(), lldb_private::ScriptInterpreterLua::Initialize(), lldb_private::ScriptInterpreterNone::Initialize(), lldb_private::ScriptInterpreterPython::Initialize(), lldb_private::StructuredDataDarwinLog::Initialize(), lldb_private::SwiftTreeSitterHighlighter::Initialize(), lldb_private::SymbolFileCTF::Initialize(), lldb_private::SymbolFileJSON::Initialize(), lldb_private::SymbolLocatorDebuginfod::Initialize(), lldb_private::SymbolLocatorDebugSymbols::Initialize(), lldb_private::SymbolLocatorDefault::Initialize(), lldb_private::trace_intel_pt::TraceIntelPT::Initialize(), lldb_private::TypeSystemClang::Initialize(), lldb_private::wasm::DynamicLoaderWasmDYLD::Initialize(), lldb_private::wasm::ObjectFileWasm::Initialize(), lldb_private::wasm::ProcessWasm::Initialize(), lldb_private::wasm::SymbolVendorWasm::Initialize(), ObjectContainerBigArchive::Initialize(), ObjectContainerBSDArchive::Initialize(), ObjectFileCOFF::Initialize(), ObjectFileELF::Initialize(), ObjectFileMachO::Initialize(), ObjectFileMinidump::Initialize(), ObjectFilePECOFF::Initialize(), ObjectFileXCOFF::Initialize(), PlatformAppleTVSimulator::Initialize(), PlatformAppleWatchSimulator::Initialize(), PlatformiOSSimulator::Initialize(), PlatformXRSimulator::Initialize(), ProcessElfCore::Initialize(), ProcessFreeBSDKernelCore::Initialize(), ProcessKDP::Initialize(), ProcessMachCore::Initialize(), SymbolFilePDB::Initialize(), SymbolFileSymtab::Initialize(), SymbolVendorELF::Initialize(), SymbolVendorMacOSX::Initialize(), SymbolVendorPECOFF::Initialize(), SystemRuntimeMacOSX::Initialize(), UnwindAssembly_x86::Initialize(), UnwindAssemblyInstEmulation::Initialize(), and LLDB_PLUGIN_DEFINE_ADV().
RegisterPlugin() [2/31]
void PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, ArchitectureCreateInstance create_callback) static
Definition at line 650 of file PluginManager.cpp.
References GetArchitectureInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [3/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, DisassemblerCreateInstance create_callback) static
Definition at line 681 of file PluginManager.cpp.
References GetDisassemblerInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [4/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, DynamicLoaderCreateInstance create_callback, DebuggerInitializeCallback debugger_init_callback = nullptr) static
Definition at line 714 of file PluginManager.cpp.
References GetDynamicLoaderInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [5/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, EmulateInstructionCreateInstance create_callback) static
Definition at line 776 of file PluginManager.cpp.
References GetEmulateInstructionInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [6/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, HighlighterCreateInstance create_callback) static
Definition at line 2089 of file PluginManager.cpp.
References GetHighlighterInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [7/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, InstrumentationRuntimeCreateInstance create_callback, InstrumentationRuntimeGetType get_type_callback) static
Definition at line 1877 of file PluginManager.cpp.
References GetInstrumentationRuntimeInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [8/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, JITLoaderCreateInstance create_callback, DebuggerInitializeCallback debugger_init_callback = nullptr) static
Definition at line 748 of file PluginManager.cpp.
References GetJITLoaderInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [9/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, LanguageCreateInstance create_callback, DebuggerInitializeCallback debugger_init_callback = nullptr) static
Definition at line 843 of file PluginManager.cpp.
References GetLanguageInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [10/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, LanguageRuntimeCreateInstance create_callback, LanguageRuntimeGetCommandObject command_callback = nullptr, LanguageRuntimeGetExceptionPrecondition precondition_callback = nullptr) static
Definition at line 886 of file PluginManager.cpp.
References GetLanguageRuntimeInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [11/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, lldb::ScriptLanguage script_lang, ScriptInterpreterCreateInstance create_callback, ScriptInterpreterGetPath get_path_callback = nullptr) static
Definition at line 1340 of file PluginManager.cpp.
References GetScriptInterpreterInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [12/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, MemoryHistoryCreateInstance create_callback) static
Definition at line 1837 of file PluginManager.cpp.
References GetMemoryHistoryInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [13/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, ObjectContainerCreateInstance create_callback, ObjectFileGetModuleSpecifications get_module_specifications, ObjectContainerCreateMemoryInstance create_memory_callback = nullptr) static
Definition at line 1113 of file PluginManager.cpp.
References GetObjectContainerInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [14/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, ObjectFileCreateInstance create_callback, ObjectFileCreateMemoryInstance create_memory_callback, ObjectFileGetModuleSpecifications get_module_specifications, ObjectFileSaveCore save_core = nullptr, DebuggerInitializeCallback debugger_init_callback = nullptr) static
Definition at line 981 of file PluginManager.cpp.
References GetObjectFileInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [15/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, OperatingSystemCreateInstance create_callback, DebuggerInitializeCallback debugger_init_callback) static
Definition at line 809 of file PluginManager.cpp.
References GetOperatingSystemInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [16/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, PlatformCreateInstance create_callback, DebuggerInitializeCallback debugger_init_callback = nullptr) static
Definition at line 1158 of file PluginManager.cpp.
References GetPlatformInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [17/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, ProcessCreateInstance create_callback, DebuggerInitializeCallback debugger_init_callback = nullptr) static
Definition at line 1207 of file PluginManager.cpp.
References GetProcessInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [18/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, ProtocolServerCreateInstance create_callback) static
Definition at line 1256 of file PluginManager.cpp.
References GetProtocolServerInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [19/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, RegisterTypeBuilderCreateInstance create_callback) static
Definition at line 1296 of file PluginManager.cpp.
References GetRegisterTypeBuilderInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [20/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, REPLCreateInstance create_callback, LanguageSet supported_languages) static
Definition at line 2043 of file PluginManager.cpp.
References GetREPLInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [21/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, ScriptedInterfaceCreateInstance create_callback, lldb::ScriptLanguage language, ScriptedInterfaceUsages usages) static
Definition at line 1985 of file PluginManager.cpp.
References GetScriptedInterfaceInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [22/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, StructuredDataPluginCreateInstance create_callback, DebuggerInitializeCallback debugger_init_callback = nullptr, StructuredDataFilterLaunchInfo filter_callback = nullptr) static
Register a StructuredDataPlugin class along with optional callbacks for debugger initialization and Process launch info filtering and manipulation.
Parameters
[in] name The name of the plugin.
[in] description A description string for the plugin.
[in] create_callback The callback that will be invoked to create an instance of the callback. This may not be nullptr.
[in] debugger_init_callback An optional callback that will be made when a Debugger instance is initialized.
[in] filter_callback An optional callback that will be invoked before LLDB launches a process for debugging. The callback must do the following:
Only do something if the plugin's behavior is enabled.
Only make changes for processes that are relevant to the plugin. The callback gets a pointer to the Target, which can be inspected as needed. The ProcessLaunchInfo is provided in read-write mode, and may be modified by the plugin if, for instance, additional environment variables are needed to support the feature when enabled.
Returns
Returns true upon success; otherwise, false.
Definition at line 1466 of file PluginManager.cpp.
References GetStructuredDataPluginInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [23/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, SymbolFileCreateInstance create_callback, DebuggerInitializeCallback debugger_init_callback = nullptr) static
Definition at line 1508 of file PluginManager.cpp.
References GetSymbolFileInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [24/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, SymbolLocatorCreateInstance create_callback, SymbolLocatorLocateExecutableObjectFile locate_executable_object_file = nullptr, SymbolLocatorLocateExecutableSymbolFile locate_executable_symbol_file = nullptr, SymbolLocatorDownloadObjectAndSymbolFile download_object_symbol_file = nullptr, SymbolLocatorFindSymbolFileInBundle find_symbol_file_in_bundle = nullptr, DebuggerInitializeCallback debugger_init_callback = nullptr) static
Definition at line 1583 of file PluginManager.cpp.
References GetSymbolLocatorInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [25/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, SymbolVendorCreateInstance create_callback) static
Definition at line 1535 of file PluginManager.cpp.
References GetSymbolVendorInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [26/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, SyntheticFrameProviderCreateInstance create_native_callback, ScriptedFrameProviderCreateInstance create_scripted_callback) static
Definition at line 1408 of file PluginManager.cpp.
References GetScriptedFrameProviderInstances(), GetSyntheticFrameProviderInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [27/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, SystemRuntimeCreateInstance create_callback) static
Definition at line 930 of file PluginManager.cpp.
References GetSystemRuntimeInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [28/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, TraceCreateInstanceFromBundle create_callback_from_bundle, TraceCreateInstanceForLiveProcess create_callback_for_live_process, llvm::StringRef schema, DebuggerInitializeCallback debugger_init_callback) static
Definition at line 1703 of file PluginManager.cpp.
References GetTracePluginInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [29/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, TraceExporterCreateInstance create_callback, ThreadTraceExportCommandCreator create_thread_trace_export_command) static
Parameters
[in] create_thread_trace_export_command This callback is used to create a CommandObject that will be listed under "thread trace export". Can be null.
Definition at line 1769 of file PluginManager.cpp.
References GetTraceExporterInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [30/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, TypeSystemCreateInstance create_callback, LanguageSet supported_languages_for_types, LanguageSet supported_languages_for_expressions) static
Definition at line 1927 of file PluginManager.cpp.
References GetTypeSystemInstances(), and PluginInstances< Instance >::RegisterPlugin().
RegisterPlugin() [31/31]
bool PluginManager::RegisterPlugin (llvm::StringRef name, llvm::StringRef description, UnwindAssemblyCreateInstance create_callback) static
Definition at line 1810 of file PluginManager.cpp.
References GetUnwindAssemblyInstances(), and PluginInstances< Instance >::RegisterPlugin().
SaveCore()
Status PluginManager::SaveCore (lldb_private::SaveCoreOptions & core_options) static
Definition at line 1025 of file PluginManager.cpp.
References lldb_private::SaveCoreOptions::EnsureValidConfiguration(), error(), lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormatv(), GetObjectFileInstances(), lldb_private::SaveCoreOptions::GetOutputFile(), lldb_private::SaveCoreOptions::GetPluginName(), lldb_private::SaveCoreOptions::GetProcess(), PluginInstances< Instance >::GetSnapshot(), and lldb_private::Status.
Referenced by CommandObjectProcessSaveCore::DoExecute(), and lldb::SBProcess::SaveCore().
SetABIPluginEnabled()
bool PluginManager::SetABIPluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2432 of file PluginManager.cpp.
References GetABIInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetArchitecturePluginEnabled()
bool PluginManager::SetArchitecturePluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2439 of file PluginManager.cpp.
References GetArchitectureInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetDisassemblerPluginEnabled()
bool PluginManager::SetDisassemblerPluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2447 of file PluginManager.cpp.
References GetDisassemblerInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetDynamicLoaderPluginEnabled()
bool PluginManager::SetDynamicLoaderPluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2455 of file PluginManager.cpp.
References GetDynamicLoaderInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetEmulateInstructionPluginEnabled()
bool PluginManager::SetEmulateInstructionPluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2464 of file PluginManager.cpp.
References GetEmulateInstructionInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetInstrumentationRuntimePluginEnabled()
bool PluginManager::SetInstrumentationRuntimePluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2473 of file PluginManager.cpp.
References GetInstrumentationRuntimeInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetJITLoaderPluginEnabled()
bool PluginManager::SetJITLoaderPluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2481 of file PluginManager.cpp.
References GetJITLoaderInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetLanguagePluginEnabled()
bool PluginManager::SetLanguagePluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2489 of file PluginManager.cpp.
References GetLanguageInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetLanguageRuntimePluginEnabled()
bool PluginManager::SetLanguageRuntimePluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2498 of file PluginManager.cpp.
References GetLanguageRuntimeInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetMemoryHistoryPluginEnabled()
bool PluginManager::SetMemoryHistoryPluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2506 of file PluginManager.cpp.
References GetMemoryHistoryInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetObjectContainerPluginEnabled()
bool PluginManager::SetObjectContainerPluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2515 of file PluginManager.cpp.
References GetObjectContainerInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetObjectFilePluginEnabled()
bool PluginManager::SetObjectFilePluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2523 of file PluginManager.cpp.
References GetObjectFileInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetOperatingSystemPluginEnabled()
bool PluginManager::SetOperatingSystemPluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2532 of file PluginManager.cpp.
References GetOperatingSystemInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetPlatformPluginEnabled()
bool PluginManager::SetPlatformPluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2540 of file PluginManager.cpp.
References GetPlatformInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetProcessPluginEnabled()
bool PluginManager::SetProcessPluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2548 of file PluginManager.cpp.
References GetProcessInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetRegisterTypeBuilderPluginEnabled()
bool PluginManager::SetRegisterTypeBuilderPluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2563 of file PluginManager.cpp.
References GetRegisterTypeBuilderInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetREPLPluginEnabled()
bool PluginManager::SetREPLPluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2555 of file PluginManager.cpp.
References GetREPLInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetScriptedInterfacePluginEnabled()
bool PluginManager::SetScriptedInterfacePluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2581 of file PluginManager.cpp.
References GetScriptedInterfaceInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetScriptInterpreterPluginEnabled()
bool PluginManager::SetScriptInterpreterPluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2572 of file PluginManager.cpp.
References GetScriptInterpreterInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetStructuredDataPluginEnabled()
bool PluginManager::SetStructuredDataPluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2589 of file PluginManager.cpp.
References GetStructuredDataPluginInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetSymbolFilePluginEnabled()
bool PluginManager::SetSymbolFilePluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2597 of file PluginManager.cpp.
References GetSymbolFileInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetSymbolLocatorPluginEnabled()
bool PluginManager::SetSymbolLocatorPluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2605 of file PluginManager.cpp.
References GetSymbolLocatorInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetSymbolVendorPluginEnabled()
bool PluginManager::SetSymbolVendorPluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2613 of file PluginManager.cpp.
References GetSymbolVendorInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetSystemRuntimePluginEnabled()
bool PluginManager::SetSystemRuntimePluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2621 of file PluginManager.cpp.
References GetSystemRuntimeInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetTraceExporterPluginEnabled()
bool PluginManager::SetTraceExporterPluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2636 of file PluginManager.cpp.
References GetTraceExporterInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetTracePluginEnabled()
bool PluginManager::SetTracePluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2629 of file PluginManager.cpp.
References GetTracePluginInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetTypeSystemPluginEnabled()
bool PluginManager::SetTypeSystemPluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2644 of file PluginManager.cpp.
References GetTypeSystemInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
SetUnwindAssemblyPluginEnabled()
bool PluginManager::SetUnwindAssemblyPluginEnabled (llvm::StringRef name, bool enable) static
Definition at line 2652 of file PluginManager.cpp.
References GetUnwindAssemblyInstances(), and PluginInstances< Instance >::SetInstanceEnabled().
Referenced by GetPluginNamespaces().
Terminate()
void PluginManager::Terminate () static
Definition at line 250 of file PluginManager.cpp.
References GetPluginMap(), and GetPluginMapMutex().
Referenced by lldb_private::SystemInitializerFull::Terminate().
UnregisterPlugin() [1/32]
bool PluginManager::UnregisterPlugin (ABICreateInstance create_callback) static
Definition at line 632 of file PluginManager.cpp.
References GetABIInstances(), and PluginInstances< Instance >::UnregisterPlugin().
Referenced by ABIMacOSX_arm64::Terminate(), ABIMacOSX_arm::Terminate(), ABIMacOSX_i386::Terminate(), ABISysV_arc::Terminate(), ABISysV_arm64::Terminate(), ABISysV_arm::Terminate(), ABISysV_hexagon::Terminate(), ABISysV_i386::Terminate(), ABISysV_loongarch::Terminate(), ABISysV_mips64::Terminate(), ABISysV_mips::Terminate(), ABISysV_msp430::Terminate(), ABISysV_ppc64::Terminate(), ABISysV_ppc::Terminate(), ABISysV_riscv::Terminate(), ABISysV_s390x::Terminate(), ABISysV_x86_64::Terminate(), ABIWindows_x86_64::Terminate(), DisassemblerLLVMC::Terminate(), DynamicLoaderDarwinKernel::Terminate(), DynamicLoaderFreeBSDKernel::Terminate(), DynamicLoaderMacOS::Terminate(), DynamicLoaderMacOSXDYLD::Terminate(), DynamicLoaderStatic::Terminate(), EmulateInstructionARM64::Terminate(), EmulateInstructionMIPS64::Terminate(), EmulateInstructionMIPS::Terminate(), InstrumentationRuntimeASanLibsanitizers::Terminate(), JITLoaderGDB::Terminate(), lldb_private::AppleObjCRuntimeV1::Terminate(), lldb_private::AppleObjCRuntimeV2::Terminate(), lldb_private::ArchitectureAArch64::Terminate(), lldb_private::ArchitectureArm::Terminate(), lldb_private::ArchitectureMips::Terminate(), lldb_private::ArchitecturePPC64::Terminate(), lldb_private::breakpad::ObjectFileBreakpad::Terminate(), lldb_private::breakpad::SymbolFileBreakpad::Terminate(), lldb_private::ClangHighlighter::Terminate(), lldb_private::ClangREPL::Terminate(), lldb_private::CPlusPlusLanguage::Terminate(), lldb_private::ctf::TraceExporterCTF::Terminate(), lldb_private::DefaultHighlighter::Terminate(), lldb_private::EmulateInstructionARM::Terminate(), lldb_private::EmulateInstructionLoongArch::Terminate(), lldb_private::EmulateInstructionPPC64::Terminate(), lldb_private::EmulateInstructionRISCV::Terminate(), lldb_private::GNUstepObjCRuntime::Terminate(), lldb_private::InstrumentationRuntimeASan::Terminate(), lldb_private::InstrumentationRuntimeBoundsSafety::Terminate(), lldb_private::InstrumentationRuntimeMainThreadChecker::Terminate(), lldb_private::InstrumentationRuntimeTSan::Terminate(), lldb_private::InstrumentationRuntimeUBSan::Terminate(), lldb_private::ItaniumABILanguageRuntime::Terminate(), lldb_private::mcp::ProtocolServerMCP::Terminate(), lldb_private::MemoryHistoryASan::Terminate(), lldb_private::minidump::ProcessMinidump::Terminate(), lldb_private::npdb::SymbolFileNativePDB::Terminate(), lldb_private::ObjCLanguage::Terminate(), lldb_private::ObjCPlusPlusLanguage::Terminate(), lldb_private::ObjectContainerMachOFileset::Terminate(), lldb_private::ObjectFileJIT::Terminate(), lldb_private::ObjectFileJSON::Terminate(), lldb_private::ObjectFilePDB::Terminate(), lldb_private::OperatingSystemPythonInterface::Terminate(), lldb_private::platform_aix::PlatformAIX::Terminate(), lldb_private::platform_android::PlatformAndroid::Terminate(), lldb_private::platform_freebsd::PlatformFreeBSD::Terminate(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::Terminate(), lldb_private::platform_linux::PlatformLinux::Terminate(), lldb_private::platform_netbsd::PlatformNetBSD::Terminate(), lldb_private::platform_openbsd::PlatformOpenBSD::Terminate(), lldb_private::PlatformDarwin::Terminate(), lldb_private::PlatformMacOSX::Terminate(), lldb_private::PlatformQemuUser::Terminate(), lldb_private::PlatformRemoteAppleBridge::Terminate(), lldb_private::PlatformRemoteAppleTV::Terminate(), lldb_private::PlatformRemoteAppleWatch::Terminate(), lldb_private::PlatformRemoteAppleXR::Terminate(), lldb_private::PlatformRemoteiOS::Terminate(), lldb_private::PlatformRemoteMacOSX::Terminate(), lldb_private::PlatformWasm::Terminate(), lldb_private::PlatformWindows::Terminate(), lldb_private::plugin::dwarf::SymbolFileDWARF::Terminate(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::Terminate(), lldb_private::process_gdb_remote::ProcessGDBRemote::Terminate(), lldb_private::ProcessTrace::Terminate(), lldb_private::RustTreeSitterHighlighter::Terminate(), lldb_private::ScriptedBreakpointPythonInterface::Terminate(), lldb_private::ScriptedFrameProvider::Terminate(), lldb_private::ScriptedFrameProviderPythonInterface::Terminate(), lldb_private::ScriptedPlatformPythonInterface::Terminate(), lldb_private::ScriptedProcess::Terminate(), lldb_private::ScriptedProcessPythonInterface::Terminate(), lldb_private::ScriptedStopHookPythonInterface::Terminate(), lldb_private::ScriptedThreadPlanPythonInterface::Terminate(), lldb_private::StructuredDataDarwinLog::Terminate(), lldb_private::SwiftTreeSitterHighlighter::Terminate(), lldb_private::SymbolFileCTF::Terminate(), lldb_private::SymbolFileJSON::Terminate(), lldb_private::SymbolLocatorDebuginfod::Terminate(), lldb_private::SymbolLocatorDebugSymbols::Terminate(), lldb_private::SymbolLocatorDefault::Terminate(), lldb_private::trace_intel_pt::TraceIntelPT::Terminate(), lldb_private::TypeSystemClang::Terminate(), lldb_private::wasm::ObjectFileWasm::Terminate(), lldb_private::wasm::ProcessWasm::Terminate(), lldb_private::wasm::SymbolVendorWasm::Terminate(), ObjectContainerBigArchive::Terminate(), ObjectContainerBSDArchive::Terminate(), ObjectContainerUniversalMachO::Terminate(), ObjectFileCOFF::Terminate(), ObjectFileELF::Terminate(), ObjectFileMachO::Terminate(), ObjectFileMinidump::Terminate(), ObjectFilePECOFF::Terminate(), ObjectFileXCOFF::Terminate(), PlatformAppleTVSimulator::Terminate(), PlatformAppleWatchSimulator::Terminate(), PlatformiOSSimulator::Terminate(), PlatformXRSimulator::Terminate(), ProcessElfCore::Terminate(), ProcessFreeBSDKernelCore::Terminate(), ProcessKDP::Terminate(), ProcessMachCore::Terminate(), SymbolFilePDB::Terminate(), SymbolFileSymtab::Terminate(), SymbolVendorELF::Terminate(), SymbolVendorMacOSX::Terminate(), SymbolVendorPECOFF::Terminate(), SystemRuntimeMacOSX::Terminate(), UnwindAssembly_x86::Terminate(), and UnwindAssemblyInstEmulation::Terminate().
UnregisterPlugin() [2/32]
void PluginManager::UnregisterPlugin (ArchitectureCreateInstance create_callback) static
Definition at line 656 of file PluginManager.cpp.
References GetArchitectureInstances().
UnregisterPlugin() [3/32]
bool PluginManager::UnregisterPlugin (DisassemblerCreateInstance create_callback) static
Definition at line 688 of file PluginManager.cpp.
References GetDisassemblerInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [4/32]
bool PluginManager::UnregisterPlugin (DynamicLoaderCreateInstance create_callback) static
Definition at line 722 of file PluginManager.cpp.
References GetDynamicLoaderInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [5/32]
bool PluginManager::UnregisterPlugin (EmulateInstructionCreateInstance create_callback) static
Definition at line 783 of file PluginManager.cpp.
References GetEmulateInstructionInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [6/32]
bool PluginManager::UnregisterPlugin (HighlighterCreateInstance create_callback) static
Definition at line 2096 of file PluginManager.cpp.
References GetHighlighterInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [7/32]
bool PluginManager::UnregisterPlugin (InstrumentationRuntimeCreateInstance create_callback) static
Definition at line 1885 of file PluginManager.cpp.
References GetInstrumentationRuntimeInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [8/32]
bool PluginManager::UnregisterPlugin (JITLoaderCreateInstance create_callback) static
Definition at line 756 of file PluginManager.cpp.
References GetJITLoaderInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [9/32]
bool PluginManager::UnregisterPlugin (LanguageCreateInstance create_callback) static
Definition at line 851 of file PluginManager.cpp.
References GetLanguageInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [10/32]
bool PluginManager::UnregisterPlugin (LanguageRuntimeCreateInstance create_callback) static
Definition at line 896 of file PluginManager.cpp.
References GetLanguageRuntimeInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [11/32]
bool PluginManager::UnregisterPlugin (MemoryHistoryCreateInstance create_callback) static
Definition at line 1844 of file PluginManager.cpp.
References GetMemoryHistoryInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [12/32]
bool PluginManager::UnregisterPlugin (ObjectContainerCreateInstance create_callback) static
Definition at line 1123 of file PluginManager.cpp.
References GetObjectContainerInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [13/32]
bool PluginManager::UnregisterPlugin (ObjectFileCreateInstance create_callback) static
Definition at line 993 of file PluginManager.cpp.
References GetObjectFileInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [14/32]
bool PluginManager::UnregisterPlugin (OperatingSystemCreateInstance create_callback) static
Definition at line 817 of file PluginManager.cpp.
References GetOperatingSystemInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [15/32]
bool PluginManager::UnregisterPlugin (PlatformCreateInstance create_callback) static
Definition at line 1166 of file PluginManager.cpp.
References GetPlatformInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [16/32]
bool PluginManager::UnregisterPlugin (ProcessCreateInstance create_callback) static
Definition at line 1215 of file PluginManager.cpp.
References GetProcessInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [17/32]
bool PluginManager::UnregisterPlugin (ProtocolServerCreateInstance create_callback) static
Definition at line 1263 of file PluginManager.cpp.
References GetProtocolServerInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [18/32]
bool PluginManager::UnregisterPlugin (RegisterTypeBuilderCreateInstance create_callback) static
Definition at line 1303 of file PluginManager.cpp.
References GetRegisterTypeBuilderInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [19/32]
bool PluginManager::UnregisterPlugin (REPLCreateInstance create_callback) static
Definition at line 2051 of file PluginManager.cpp.
References GetREPLInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [20/32]
bool PluginManager::UnregisterPlugin (ScriptedFrameProviderCreateInstance create_callback) static
Definition at line 1426 of file PluginManager.cpp.
References GetScriptedFrameProviderInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [21/32]
bool PluginManager::UnregisterPlugin (ScriptedInterfaceCreateInstance create_callback) static
Definition at line 1993 of file PluginManager.cpp.
References GetScriptedInterfaceInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [22/32]
bool PluginManager::UnregisterPlugin (ScriptInterpreterCreateInstance create_callback) static
Definition at line 1349 of file PluginManager.cpp.
References GetScriptInterpreterInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [23/32]
bool PluginManager::UnregisterPlugin (StructuredDataPluginCreateInstance create_callback) static
Definition at line 1476 of file PluginManager.cpp.
References GetStructuredDataPluginInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [24/32]
bool PluginManager::UnregisterPlugin (SymbolFileCreateInstance create_callback) static
Definition at line 1516 of file PluginManager.cpp.
References GetSymbolFileInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [25/32]
bool PluginManager::UnregisterPlugin (SymbolLocatorCreateInstance create_callback) static
Definition at line 1597 of file PluginManager.cpp.
References GetSymbolLocatorInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [26/32]
bool PluginManager::UnregisterPlugin (SymbolVendorCreateInstance create_callback) static
Definition at line 1542 of file PluginManager.cpp.
References GetSymbolVendorInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [27/32]
bool PluginManager::UnregisterPlugin (SyntheticFrameProviderCreateInstance create_callback) static
Definition at line 1421 of file PluginManager.cpp.
References GetSyntheticFrameProviderInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [28/32]
bool PluginManager::UnregisterPlugin (SystemRuntimeCreateInstance create_callback) static
Definition at line 937 of file PluginManager.cpp.
References GetSystemRuntimeInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [29/32]
bool PluginManager::UnregisterPlugin (TraceCreateInstanceFromBundle create_callback) static
Definition at line 1713 of file PluginManager.cpp.
References GetTracePluginInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [30/32]
bool PluginManager::UnregisterPlugin (TraceExporterCreateInstance create_callback) static
Definition at line 1782 of file PluginManager.cpp.
References GetTraceExporterInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [31/32]
bool PluginManager::UnregisterPlugin (TypeSystemCreateInstance create_callback) static
Definition at line 1937 of file PluginManager.cpp.
References GetTypeSystemInstances(), and PluginInstances< Instance >::UnregisterPlugin().
UnregisterPlugin() [32/32]
bool PluginManager::UnregisterPlugin (UnwindAssemblyCreateInstance create_callback) static
Definition at line 1817 of file PluginManager.cpp.
References GetUnwindAssemblyInstances(), and PluginInstances< Instance >::UnregisterPlugin().
The documentation for this class was generated from the following files:
PluginManager.h
PluginManager.cpp