LLDB: lldb_private::OptionGroup Class Reference
lldb_private::OptionGroup Class Reference abstract
#include <Options.h>
Public Member Functions
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual llvm::ArrayRef< OptionDefinition > GetDefinitions ()=0
virtual Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext *execution_context)=0
virtual void OptionParsingStarting (ExecutionContext *execution_context)=0
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Detailed Description
Definition at line 234 of file Options.h.
Constructor & Destructor Documentation
OptionGroup()
lldb_private::OptionGroup::OptionGroup () default
~OptionGroup()
virtual lldb_private::OptionGroup::~OptionGroup () virtual default
Member Function Documentation
GetDefinitions()
virtual llvm::ArrayRef< OptionDefinition > lldb_private::OptionGroup::GetDefinitions () pure virtual
Implemented in BreakpointAccessOptionGroup, BreakpointDummyOptionGroup, BreakpointNameOptionGroup, BreakpointNamesOptionGroup, CommandObjectBreakpointAddAddress::CommandOptions, CommandObjectBreakpointAddException::CommandOptions, CommandObjectBreakpointAddFile::CommandOptions, CommandObjectBreakpointAddName::CommandOptions, CommandObjectBreakpointAddPattern::CommandOptions, CommandObjectBreakpointAddScripted::CommandOptions, CommandObjectBreakpointCommandAdd::CommandOptions, CommandObjectBreakpointSet::CommandOptions, CommandObjectCommandsAlias::CommandOptions, CommandObjectMemoryFind::OptionGroupFindMemory, CommandObjectMemoryRegion::OptionGroupMemoryRegion, CommandObjectMemoryTagWrite::OptionGroupTagWrite, CommandObjectMemoryWrite::OptionGroupWriteMemory, CommandObjectRegisterRead::CommandOptions, CommandObjectTargetStopHookAdd::CommandOptions, CommandObjectThreadSelect::OptionGroupThreadSelect, CommandObjectTypeFormatAdd::CommandOptions, CommandObjectTypeLookup::CommandOptions, lldb_private::BreakpointOptionGroup, lldb_private::CommandObjectExpression::CommandOptions, lldb_private::CommandOptionsProcessAttach, lldb_private::CommandOptionsProcessLaunch, lldb_private::OptionGroupArchitecture, lldb_private::OptionGroupBoolean, lldb_private::OptionGroupFile, lldb_private::OptionGroupFileList, lldb_private::OptionGroupFormat, lldb_private::OptionGroupMemoryTag, lldb_private::OptionGroupOutputFile, lldb_private::OptionGroupPlatform, lldb_private::OptionGroupPlatformCaching, lldb_private::OptionGroupPlatformRSync, lldb_private::OptionGroupPlatformSSH, lldb_private::OptionGroupPythonClassWithDict, lldb_private::OptionGroupString, lldb_private::OptionGroupUInt64, lldb_private::OptionGroupUUID, lldb_private::OptionGroupValueObjectDisplay, lldb_private::OptionGroupVariable, lldb_private::OptionGroupWatchpoint, OptionGroupDependents, OptionGroupReadMemory, OptionPermissions, and ThreadStepScopeOptionGroup.
Referenced by lldb_private::OptionGroupOptions::Append(), lldb_private::OptionGroupOptions::Append(), and lldb_private::OptionGroupOptions::Append().
OptionParsingFinished()
virtual Status lldb_private::OptionGroup::OptionParsingFinished (ExecutionContext * execution_context) inline virtual
Reimplemented in CommandObjectBreakpointAddFile::CommandOptions, lldb_private::BreakpointOptionGroup, and lldb_private::OptionGroupPythonClassWithDict.
Definition at line 248 of file Options.h.
References error().
Referenced by lldb_private::OptionGroupOptions::OptionParsingFinished().
OptionParsingStarting()
virtual void lldb_private::OptionGroup::OptionParsingStarting (ExecutionContext * execution_context) pure virtual
Implemented in BreakpointAccessOptionGroup, BreakpointDummyOptionGroup, BreakpointNameOptionGroup, BreakpointNamesOptionGroup, CommandObjectBreakpointAddAddress::CommandOptions, CommandObjectBreakpointAddException::CommandOptions, CommandObjectBreakpointAddFile::CommandOptions, CommandObjectBreakpointAddName::CommandOptions, CommandObjectBreakpointAddPattern::CommandOptions, CommandObjectBreakpointAddScripted::CommandOptions, CommandObjectBreakpointCommandAdd::CommandOptions, CommandObjectBreakpointSet::CommandOptions, CommandObjectCommandsAlias::CommandOptions, CommandObjectMemoryFind::OptionGroupFindMemory, CommandObjectMemoryRegion::OptionGroupMemoryRegion, CommandObjectMemoryTagWrite::OptionGroupTagWrite, CommandObjectMemoryWrite::OptionGroupWriteMemory, CommandObjectRegisterRead::CommandOptions, CommandObjectTargetStopHookAdd::CommandOptions, CommandObjectThreadSelect::OptionGroupThreadSelect, CommandObjectTypeFormatAdd::CommandOptions, CommandObjectTypeLookup::CommandOptions, lldb_private::BreakpointOptionGroup, lldb_private::CommandObjectExpression::CommandOptions, lldb_private::CommandOptionsProcessAttach, lldb_private::CommandOptionsProcessLaunch, lldb_private::OptionGroupArchitecture, lldb_private::OptionGroupBoolean, lldb_private::OptionGroupFile, lldb_private::OptionGroupFileList, lldb_private::OptionGroupFormat, lldb_private::OptionGroupMemoryTag, lldb_private::OptionGroupOutputFile, lldb_private::OptionGroupPlatform, lldb_private::OptionGroupPlatformCaching, lldb_private::OptionGroupPlatformRSync, lldb_private::OptionGroupPlatformSSH, lldb_private::OptionGroupPythonClassWithDict, lldb_private::OptionGroupString, lldb_private::OptionGroupUInt64, lldb_private::OptionGroupUUID, lldb_private::OptionGroupValueObjectDisplay, lldb_private::OptionGroupVariable, lldb_private::OptionGroupWatchpoint, OptionGroupDependents, OptionGroupReadMemory, OptionPermissions, and ThreadStepScopeOptionGroup.
Referenced by lldb_private::OptionGroupOptions::OptionParsingStarting().
SetOptionValue()
virtual Status lldb_private::OptionGroup::SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext * execution_context) pure virtual
Implemented in BreakpointAccessOptionGroup, BreakpointDummyOptionGroup, BreakpointNameOptionGroup, BreakpointNamesOptionGroup, CommandObjectBreakpointAddAddress::CommandOptions, CommandObjectBreakpointAddException::CommandOptions, CommandObjectBreakpointAddFile::CommandOptions, CommandObjectBreakpointAddName::CommandOptions, CommandObjectBreakpointAddPattern::CommandOptions, CommandObjectBreakpointAddScripted::CommandOptions, CommandObjectBreakpointCommandAdd::CommandOptions, CommandObjectBreakpointSet::CommandOptions, CommandObjectCommandsAlias::CommandOptions, CommandObjectMemoryFind::OptionGroupFindMemory, CommandObjectMemoryRegion::OptionGroupMemoryRegion, CommandObjectMemoryTagWrite::OptionGroupTagWrite, CommandObjectMemoryWrite::OptionGroupWriteMemory, CommandObjectRegisterRead::CommandOptions, CommandObjectTargetStopHookAdd::CommandOptions, CommandObjectThreadSelect::OptionGroupThreadSelect, CommandObjectTypeFormatAdd::CommandOptions, CommandObjectTypeLookup::CommandOptions, lldb_private::BreakpointOptionGroup, lldb_private::CommandObjectExpression::CommandOptions, lldb_private::CommandOptionsProcessAttach, lldb_private::CommandOptionsProcessLaunch, lldb_private::OptionGroupArchitecture, lldb_private::OptionGroupBoolean, lldb_private::OptionGroupFile, lldb_private::OptionGroupFileList, lldb_private::OptionGroupFormat, lldb_private::OptionGroupMemoryTag, lldb_private::OptionGroupOutputFile, lldb_private::OptionGroupPlatform, lldb_private::OptionGroupPlatformCaching, lldb_private::OptionGroupPlatformRSync, lldb_private::OptionGroupPlatformSSH, lldb_private::OptionGroupPythonClassWithDict, lldb_private::OptionGroupString, lldb_private::OptionGroupUInt64, lldb_private::OptionGroupUUID, lldb_private::OptionGroupValueObjectDisplay, lldb_private::OptionGroupVariable, lldb_private::OptionGroupWatchpoint, OptionGroupDependents, OptionGroupReadMemory, OptionPermissions, and ThreadStepScopeOptionGroup.
The documentation for this class was generated from the following file:
Options.h