LLDB: lldb_private::DataVisualization Class Reference
lldb_private::DataVisualization Class Reference
#include <DataVisualization.h>
Classes
class Categories
class NamedSummaryFormats
Static Public Member Functions
static void ForceUpdate ()
static uint32_t GetCurrentRevision ()
static bool ShouldPrintAsOneLiner (ValueObject &valobj)
static lldb::TypeFormatImplSP GetFormat (ValueObject &valobj, lldb::DynamicValueType use_dynamic)
static lldb::TypeFormatImplSP GetFormatForType (lldb::TypeNameSpecifierImplSP type_sp)
static lldb::TypeSummaryImplSP GetSummaryFormat (ValueObject &valobj, lldb::DynamicValueType use_dynamic)
static lldb::TypeSummaryImplSP GetSummaryForType (lldb::TypeNameSpecifierImplSP type_sp)
static lldb::TypeFilterImplSP GetFilterForType (lldb::TypeNameSpecifierImplSP type_sp)
static lldb::ScriptedSyntheticChildrenSP GetSyntheticForType (lldb::TypeNameSpecifierImplSP type_sp)
static lldb::SyntheticChildrenSP GetSyntheticChildren (ValueObject &valobj, lldb::DynamicValueType use_dynamic)
static bool AnyMatches (const FormattersMatchCandidate &candidate_type, TypeCategoryImpl::FormatCategoryItems items=TypeCategoryImpl::ALL_ITEM_TYPES, bool only_enabled=true, const char **matching_category=nullptr, TypeCategoryImpl::FormatCategoryItems *matching_type=nullptr)
Detailed Description
Definition at line 22 of file DataVisualization.h.
Member Function Documentation
AnyMatches()
bool DataVisualization::AnyMatches (const FormattersMatchCandidate & candidate_type, TypeCategoryImpl::FormatCategoryItems items = TypeCategoryImpl::ALL_ITEM_TYPES, bool only_enabled = true, const char ** matching_category = nullptr, TypeCategoryImpl::FormatCategoryItems * matching_type = nullptr) static
Definition at line 68 of file DataVisualization.cpp.
References lldb_private::FormatManager::AnyMatches(), and GetFormatManager().
ForceUpdate()
void DataVisualization::ForceUpdate () static
Definition at line 20 of file DataVisualization.cpp.
References lldb_private::FormatManager::Changed(), and GetFormatManager().
Referenced by CommandObjectScriptingRun::DoExecute(), and lldb_private::Debugger::SetPropertyValue().
GetCurrentRevision()
uint32_t DataVisualization::GetCurrentRevision () static
Definition at line 22 of file DataVisualization.cpp.
References lldb_private::FormatManager::GetCurrentRevision(), and GetFormatManager().
Referenced by lldb_private::ValueObject::UpdateFormatsIfNeeded().
GetFilterForType()
lldb::TypeFilterImplSP DataVisualization::GetFilterForType (lldb::TypeNameSpecifierImplSP type_sp) static
Definition at line 59 of file DataVisualization.cpp.
References lldb_private::FormatManager::GetFilterForType(), and GetFormatManager().
Referenced by lldb::SBDebugger::GetFilterForType().
GetFormat()
lldb::TypeFormatImplSP DataVisualization::GetFormat (ValueObject & valobj, lldb::DynamicValueType use_dynamic) static
Definition at line 31 of file DataVisualization.cpp.
References lldb_private::FormatManager::GetFormat(), and GetFormatManager().
Referenced by lldb_private::ValueObject::UpdateFormatsIfNeeded().
GetFormatForType()
lldb::TypeFormatImplSP DataVisualization::GetFormatForType (lldb::TypeNameSpecifierImplSP type_sp) static
Definition at line 37 of file DataVisualization.cpp.
References lldb_private::FormatManager::GetFormatForType(), and GetFormatManager().
GetSummaryFormat()
lldb::TypeSummaryImplSP DataVisualization::GetSummaryFormat (ValueObject & valobj, lldb::DynamicValueType use_dynamic) static
Definition at line 42 of file DataVisualization.cpp.
References GetFormatManager(), and lldb_private::FormatManager::GetSummaryFormat().
Referenced by lldb_private::ValueObject::UpdateFormatsIfNeeded().
GetSummaryForType()
lldb::TypeSummaryImplSP DataVisualization::GetSummaryForType (lldb::TypeNameSpecifierImplSP type_sp) static
Definition at line 48 of file DataVisualization.cpp.
References GetFormatManager(), and lldb_private::FormatManager::GetSummaryForType().
Referenced by lldb_private::FormatEntity::Formatter::DumpValue(), and lldb::SBDebugger::GetSummaryForType().
GetSyntheticChildren()
lldb::SyntheticChildrenSP DataVisualization::GetSyntheticChildren (ValueObject & valobj, lldb::DynamicValueType use_dynamic) static
Definition at line 53 of file DataVisualization.cpp.
References GetFormatManager(), and lldb_private::FormatManager::GetSyntheticChildren().
Referenced by lldb_private::ValueObject::UpdateFormatsIfNeeded().
GetSyntheticForType()
lldb::ScriptedSyntheticChildrenSP DataVisualization::GetSyntheticForType (lldb::TypeNameSpecifierImplSP type_sp) static
Definition at line 64 of file DataVisualization.cpp.
References GetFormatManager(), and lldb_private::FormatManager::GetSyntheticForType().
Referenced by lldb::SBDebugger::GetSyntheticForType().
ShouldPrintAsOneLiner()
bool DataVisualization::ShouldPrintAsOneLiner (ValueObject & valobj) static
Definition at line 26 of file DataVisualization.cpp.
References GetFormatManager(), and lldb_private::FormatManager::ShouldPrintAsOneLiner().
Referenced by lldb_private::FormatEntity::PrettyPrintFunctionArguments(), and lldb_private::ValueObjectPrinter::PrintChildrenIfNeeded().
The documentation for this class was generated from the following files:
DataVisualization.h
DataVisualization.cpp