LLDB: lldb_private::Lua Class Reference
lldb_private::Lua Class Reference
#include <Lua.h>
Public Member Functions
Lua ()
~Lua ()
llvm::Error Run (llvm::StringRef buffer)
llvm::Error RegisterBreakpointCallback (void *baton, const char *body)
llvm::Expected< bool > CallBreakpointCallback (void *baton, lldb::StackFrameSP stop_frame_sp, lldb::BreakpointLocationSP bp_loc_sp, StructuredData::ObjectSP extra_args_sp)
llvm::Error RegisterWatchpointCallback (void *baton, const char *body)
llvm::Expected< bool > CallWatchpointCallback (void *baton, lldb::StackFrameSP stop_frame_sp, lldb::WatchpointSP wp_sp)
llvm::Error LoadModule (llvm::StringRef filename)
llvm::Error CheckSyntax (llvm::StringRef buffer)
llvm::Error ChangeIO (FILE *out, FILE *err)
Private Attributes
lua_State * m_lua_state
Detailed Description
Definition at line 29 of file Lua.h.
Constructor & Destructor Documentation
Lua()
Lua::Lua ()
Definition at line 34 of file Lua.cpp.
References lldb_print(), lldb_private::luaopen_lldb(), and m_lua_state.
~Lua()
Lua::~Lua ()
Definition at line 42 of file Lua.cpp.
References m_lua_state.
Member Function Documentation
CallBreakpointCallback()
llvm::Expected< bool > Lua::CallBreakpointCallback (void * baton, lldb::StackFrameSP stop_frame_sp, lldb::BreakpointLocationSP bp_loc_sp, StructuredData::ObjectSP extra_args_sp)
Definition at line 79 of file Lua.cpp.
References lldb_private::lua::SWIGBridge::LLDBSwigLuaBreakpointCallbackFunction(), and m_lua_state.
CallWatchpointCallback()
llvm::Expected< bool > Lua::CallWatchpointCallback (void * baton, lldb::StackFrameSP stop_frame_sp, lldb::WatchpointSP wp_sp)
Definition at line 107 of file Lua.cpp.
References lldb_private::lua::SWIGBridge::LLDBSwigLuaWatchpointCallbackFunction(), and m_lua_state.
ChangeIO()
llvm::Error Lua::ChangeIO (FILE * out, FILE * err)
Definition at line 161 of file Lua.cpp.
References m_lua_state.
CheckSyntax()
llvm::Error Lua::CheckSyntax (llvm::StringRef buffer)
Definition at line 116 of file Lua.cpp.
References error(), and m_lua_state.
LoadModule()
llvm::Error Lua::LoadModule (llvm::StringRef filename)
Definition at line 133 of file Lua.cpp.
References error(), lldb_private::ConstString::GetCString(), lldb_private::FileSpec::GetFileNameExtension(), lldb_private::FileSpec::GetFileNameStrippingExtension(), lldb_private::FileSystem::Instance(), and m_lua_state.
RegisterBreakpointCallback()
llvm::Error Lua::RegisterBreakpointCallback (void * baton, const char * body)
Definition at line 62 of file Lua.cpp.
References m_lua_state.
RegisterWatchpointCallback()
llvm::Error Lua::RegisterWatchpointCallback (void * baton, const char * body)
Definition at line 90 of file Lua.cpp.
References m_lua_state.
Run()
llvm::Error Lua::Run (llvm::StringRef buffer)
Definition at line 47 of file Lua.cpp.
References error(), and m_lua_state.
Member Data Documentation
m_lua_state
lua_State* lldb_private::Lua::m_lua_state private
Definition at line 49 of file Lua.h.
Referenced by CallBreakpointCallback(), CallWatchpointCallback(), ChangeIO(), CheckSyntax(), LoadModule(), Lua(), RegisterBreakpointCallback(), RegisterWatchpointCallback(), Run(), and ~Lua().
The documentation for this class was generated from the following files:
Lua.h
Lua.cpp