LLDB: lldb_private::HostProcess Class Reference
lldb_private::HostProcess Class Reference
#include <HostProcess.h>
Public Member Functions
HostProcess ()
HostProcess (lldb::process_t process)
~HostProcess ()
Status Terminate ()
lldb::pid_t GetProcessId () const
bool IsRunning () const
llvm::Expected< HostThread > StartMonitoring (const Host::MonitorChildProcessCallback &callback)
HostNativeProcessBase & GetNativeProcess ()
const HostNativeProcessBase & GetNativeProcess () const
Private Attributes
std::shared_ptr< HostNativeProcessBase > m_native_process
Detailed Description
Definition at line 33 of file HostProcess.h.
Constructor & Destructor Documentation
HostProcess() [1/2]
HostProcess::HostProcess ()
Definition at line 16 of file HostProcess.cpp.
References m_native_process.
HostProcess() [2/2]
HostProcess::HostProcess (lldb::process_t process)
Definition at line 18 of file HostProcess.cpp.
References m_native_process.
~HostProcess()
HostProcess::~HostProcess () default
Member Function Documentation
GetNativeProcess() [1/2]
HostNativeProcessBase & HostProcess::GetNativeProcess ()
Definition at line 36 of file HostProcess.cpp.
References m_native_process.
Referenced by lldb_private::ProcessDebugger::AllocateMemory(), lldb_private::ProcessDebugger::DeallocateMemory(), lldb_private::ProcessDebugger::GetMemoryRegionInfo(), and lldb_private::ProcessDebugger::WriteMemory().
GetNativeProcess() [2/2]
const HostNativeProcessBase & HostProcess::GetNativeProcess () const
Definition at line 40 of file HostProcess.cpp.
References m_native_process.
GetProcessId()
lldb::pid_t HostProcess::GetProcessId () const
Definition at line 25 of file HostProcess.cpp.
References m_native_process.
Referenced by lldb_private::process_aix::NativeProcessAIX::Manager::Launch(), lldb_private::process_freebsd::NativeProcessFreeBSD::Manager::Launch(), lldb_private::process_linux::NativeProcessLinux::Manager::Launch(), lldb_private::process_netbsd::NativeProcessNetBSD::Manager::Launch(), lldb_private::Host::LaunchProcess(), lldb_private::MonitoringProcessLauncher::LaunchProcess(), lldb_private::ProcessDebugger::LaunchProcess(), and lldb_private::DebuggerThread::StopDebugging().
IsRunning()
bool HostProcess::IsRunning () const
Definition at line 29 of file HostProcess.cpp.
References m_native_process.
StartMonitoring()
llvm::Expected< HostThread > HostProcess::StartMonitoring (const Host::MonitorChildProcessCallback & callback)
Definition at line 31 of file HostProcess.cpp.
References m_native_process.
Referenced by lldb_private::MonitoringProcessLauncher::LaunchProcess().
Terminate()
Status HostProcess::Terminate ()
Definition at line 23 of file HostProcess.cpp.
References m_native_process.
Member Data Documentation
m_native_process
std::shared_ptr<HostNativeProcessBase> lldb_private::HostProcess::m_native_process private
Definition at line 51 of file HostProcess.h.
Referenced by GetNativeProcess(), GetNativeProcess(), GetProcessId(), HostProcess(), HostProcess(), IsRunning(), StartMonitoring(), and Terminate().
The documentation for this class was generated from the following files:
HostProcess.h
HostProcess.cpp