LLDB: NSErrorSyntheticFrontEnd Class Reference
NSErrorSyntheticFrontEnd Class Reference
Public Member Functions
NSErrorSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
~NSErrorSyntheticFrontEnd () override=default
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Attributes
ValueObject * m_child_ptr = nullptr
ValueObjectSP m_child_sp
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
Definition at line 110 of file NSError.cpp.
Constructor & Destructor Documentation
NSErrorSyntheticFrontEnd()
NSErrorSyntheticFrontEnd::NSErrorSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp) inline
Definition at line 112 of file NSError.cpp.
References lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd().
~NSErrorSyntheticFrontEnd()
NSErrorSyntheticFrontEnd::~NSErrorSyntheticFrontEnd () override default
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > NSErrorSyntheticFrontEnd::CalculateNumChildren () inline override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 119 of file NSError.cpp.
References m_child_ptr, and m_child_sp.
GetChildAtIndex()
lldb::ValueObjectSP NSErrorSyntheticFrontEnd::GetChildAtIndex (uint32_t idx) inline override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 127 of file NSError.cpp.
References m_child_ptr, and m_child_sp.
GetIndexOfChildWithName()
llvm::Expected< size_t > NSErrorSyntheticFrontEnd::GetIndexOfChildWithName (ConstString name) inline override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 168 of file NSError.cpp.
References lldb_private::ConstString::AsCString().
Update()
lldb::ChildCacheState NSErrorSyntheticFrontEnd::Update () inline override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 136 of file NSError.cpp.
References lldb_private::SyntheticChildrenFrontEnd::CreateValueObjectFromData(), DerefToNSErrorPointer(), lldb::eBasicTypeObjCID, lldb::eRefetch, error(), lldb_private::formatters::InferiorSizedWord::GetAsData(), lldb_private::ScratchTypeSystemClang::GetForTarget(), LLDB_INVALID_ADDRESS, lldb_private::SyntheticChildrenFrontEnd::m_backend, m_child_ptr, and m_child_sp.
Member Data Documentation
m_child_ptr
ValueObject* NSErrorSyntheticFrontEnd::m_child_ptr = nullptr private
Definition at line 183 of file NSError.cpp.
Referenced by CalculateNumChildren(), GetChildAtIndex(), and Update().
m_child_sp
ValueObjectSP NSErrorSyntheticFrontEnd::m_child_sp private
Definition at line 184 of file NSError.cpp.
Referenced by CalculateNumChildren(), GetChildAtIndex(), and Update().
The documentation for this class was generated from the following file:
NSError.cpp