LLDB: lldb_private::BreakpointResolverAddress Class Reference
lldb_private::BreakpointResolverAddress Class Reference
"lldb/Breakpoint/BreakpointResolverAddress.h" This class sets breakpoints on a given Address.
#include <BreakpointResolverAddress.h>
Public Member Functions
BreakpointResolverAddress (const lldb::BreakpointSP &bkpt, const Address &addr)
BreakpointResolverAddress (const lldb::BreakpointSP &bkpt, const Address &addr, const FileSpec &module_spec)
~BreakpointResolverAddress () override=default
StructuredData::ObjectSP SerializeToStructuredData () override
void ResolveBreakpoint (SearchFilter &filter) override
In response to this method the resolver scans all the modules in the breakpoint's target, and adds any new locations it finds.
void ResolveBreakpointInModules (SearchFilter &filter, ModuleList &modules) override
In response to this method the resolver scans the modules in the module list modules, and adds any new locations it finds.
Searcher::CallbackReturn SearchCallback (SearchFilter &filter, SymbolContext &context, Address *addr) override
lldb::SearchDepth GetDepth () override
void GetDescription (Stream *s) override
Prints a canonical description for the breakpoint to the stream s.
void Dump (Stream *s) const override
Standard "Dump" method. At present it does nothing.
lldb::BreakpointResolverSP CopyForBreakpoint (lldb::BreakpointSP &breakpoint) override
Public Member Functions inherited from lldb_private::BreakpointResolver
BreakpointResolver (const lldb::BreakpointSP &bkpt, unsigned char resolverType, lldb::addr_t offset=0, bool offset_is_insn_count=false)
The breakpoint resolver need to have a breakpoint for "ResolveBreakpoint to make sense.
~BreakpointResolver () override
The Destructor is virtual, all significant breakpoint resolvers derive from this class.
void SetBreakpoint (const lldb::BreakpointSP &bkpt)
This sets the breakpoint for this resolver.
lldb::BreakpointSP GetBreakpoint () const
This gets the breakpoint for this resolver.
void SetOffset (lldb::addr_t offset)
This updates the offset for this breakpoint.
lldb::addr_t GetOffset () const
lldb::addr_t GetOffsetIsInsnCount () const
StructuredData::DictionarySP WrapOptionsDict (StructuredData::DictionarySP options_dict_sp)
unsigned getResolverID () const
getResolverID - Return an ID for the concrete type of this object.
enum ResolverTy GetResolverTy ()
const char * GetResolverName ()
Public Member Functions inherited from lldb_private::Searcher
Searcher ()
virtual ~Searcher ()
Static Public Member Functions
static lldb::BreakpointResolverSP CreateFromStructuredData (const StructuredData::Dictionary &options_dict, Status &error)
static bool classof (const BreakpointResolverAddress *)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const BreakpointResolver *V)
Static Public Member Functions inherited from lldb_private::BreakpointResolver
static lldb::BreakpointResolverSP CreateFromStructuredData (const StructuredData::Dictionary &resolver_dict, Status &error)
This section handles serializing and deserializing from StructuredData objects.
static const char * GetSerializationKey ()
static const char * GetSerializationSubclassKey ()
static const char * GetSerializationSubclassOptionsKey ()
static const char * ResolverTyToName (enum ResolverTy)
static ResolverTy NameToResolverTy (llvm::StringRef name)
static const char * GetKey (OptionNames enum_value)
Protected Attributes
Address m_addr
lldb::addr_t m_resolved_addr
FileSpec m_module_filespec
Private Member Functions
BreakpointResolverAddress (const BreakpointResolverAddress &)=delete
const BreakpointResolverAddress & operator= (const BreakpointResolverAddress &)=delete
Additional Inherited Members
Public Types inherited from lldb_private::BreakpointResolver
enum ResolverTy {
FileLineResolver = 0 , AddressResolver , NameResolver , FileRegexResolver ,
PythonResolver , ExceptionResolver , LastKnownResolverType = ExceptionResolver , UnknownResolver
}
An enumeration for keeping track of the concrete subclass that is actually instantiated.
Public Types inherited from lldb_private::Searcher
enum CallbackReturn { eCallbackReturnStop = 0 , eCallbackReturnContinue , eCallbackReturnPop }
Static Public Attributes inherited from lldb_private::BreakpointResolver
static const char * g_ty_to_name [LastKnownResolverType+2]
Protected Types inherited from lldb_private::BreakpointResolver
enum class OptionNames : uint32_t {
AddressOffset = 0 , ExactMatch , FileName , Inlines ,
LanguageName , LineNumber , Column , ModuleName ,
NameMaskArray , Offset , PythonClassName , RegexString ,
ScriptArgs , SectionName , SearchDepth , SkipPrologue ,
SymbolNameArray , LastOptionName
}
Protected Member Functions inherited from lldb_private::BreakpointResolver
virtual void NotifyBreakpointSet ()
void SetSCMatchesByLine (SearchFilter &filter, SymbolContextList &sc_list, bool skip_prologue, llvm::StringRef log_ident, uint32_t line=0, std::optional< uint16_t > column=std::nullopt)
Takes a symbol context list of matches which supposedly represent the same file and line number in a CU, and find the nearest actual line number that matches, and then filter down the matching addresses to unique entries, and skip the prologue if asked to do so, and then set breakpoint locations in this breakpoint for all the resultant addresses.
void SetSCMatchesByLine (SearchFilter &, SymbolContextList &, bool, const char *)=delete
lldb::BreakpointLocationSP AddLocation (Address loc_addr, bool *new_location=nullptr)
Static Protected Attributes inherited from lldb_private::BreakpointResolver
static const char * g_option_names [static_cast< uint32_t >(OptionNames::LastOptionName)]
Detailed Description
"lldb/Breakpoint/BreakpointResolverAddress.h" This class sets breakpoints on a given Address.
This breakpoint only takes once, and then it won't attempt to reset itself.
Definition at line 22 of file BreakpointResolverAddress.h.
Constructor & Destructor Documentation
BreakpointResolverAddress() [1/3]
BreakpointResolverAddress::BreakpointResolverAddress (const lldb::BreakpointSP & bkpt, const Address & addr)
Definition at line 28 of file BreakpointResolverAddress.cpp.
References lldb_private::BreakpointResolver::AddressResolver, lldb_private::BreakpointResolver::BreakpointResolver(), LLDB_INVALID_ADDRESS, m_addr, and m_resolved_addr.
Referenced by BreakpointResolverAddress(), classof(), CopyForBreakpoint(), and operator=().
BreakpointResolverAddress() [2/3]
BreakpointResolverAddress::BreakpointResolverAddress (const lldb::BreakpointSP & bkpt, const Address & addr, const FileSpec & module_spec)
Definition at line 22 of file BreakpointResolverAddress.cpp.
References lldb_private::BreakpointResolver::AddressResolver, lldb_private::BreakpointResolver::BreakpointResolver(), LLDB_INVALID_ADDRESS, m_addr, m_module_filespec, and m_resolved_addr.
~BreakpointResolverAddress()
lldb_private::BreakpointResolverAddress::~BreakpointResolverAddress () override default
References error().
BreakpointResolverAddress() [3/3]
lldb_private::BreakpointResolverAddress::BreakpointResolverAddress (const BreakpointResolverAddress &) private delete
References BreakpointResolverAddress().
Member Function Documentation
classof() [1/2]
bool lldb_private::BreakpointResolverAddress::classof (const BreakpointResolver * V) inline static
Definition at line 56 of file BreakpointResolverAddress.h.
References lldb_private::BreakpointResolver::AddressResolver, lldb_private::BreakpointResolver::BreakpointResolver(), and lldb_private::BreakpointResolver::getResolverID().
classof() [2/2]
bool lldb_private::BreakpointResolverAddress::classof (const BreakpointResolverAddress *) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 55 of file BreakpointResolverAddress.h.
References BreakpointResolverAddress().
CopyForBreakpoint()
lldb::BreakpointResolverSP BreakpointResolverAddress::CopyForBreakpoint (lldb::BreakpointSP & breakpoint) override virtual
Implements lldb_private::BreakpointResolver.
Definition at line 181 of file BreakpointResolverAddress.cpp.
References BreakpointResolverAddress(), and m_addr.
CreateFromStructuredData()
BreakpointResolverSP BreakpointResolverAddress::CreateFromStructuredData (const StructuredData::Dictionary & options_dict, Status & error) static
Definition at line 33 of file BreakpointResolverAddress.cpp.
References lldb_private::BreakpointResolver::AddressOffset, error(), lldb_private::Status::FromErrorString(), lldb_private::BreakpointResolver::GetKey(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsInteger(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsString(), lldb_private::StructuredData::Dictionary::HasKey(), lldb_private::BreakpointResolver::ModuleName, and lldb_private::FileSpec::SetFile().
Referenced by lldb_private::BreakpointResolver::CreateFromStructuredData().
Dump()
void BreakpointResolverAddress::Dump (Stream * s) const override virtual
Standard "Dump" method. At present it does nothing.
Implements lldb_private::BreakpointResolver.
Definition at line 178 of file BreakpointResolverAddress.cpp.
GetDepth()
lldb::SearchDepth BreakpointResolverAddress::GetDepth () override virtual
Implements lldb_private::Searcher.
Definition at line 167 of file BreakpointResolverAddress.cpp.
References lldb::eSearchDepthTarget.
GetDescription()
void BreakpointResolverAddress::GetDescription (Stream * s) override virtual
Prints a canonical description for the breakpoint to the stream s.
Parameters
[in] s Stream to which the output is copied.
Implements lldb_private::BreakpointResolver.
Definition at line 171 of file BreakpointResolverAddress.cpp.
References lldb_private::Address::DumpStyleLoadAddress, lldb_private::Address::DumpStyleModuleWithFileAddress, lldb_private::BreakpointResolver::GetBreakpoint(), m_addr, and lldb_private::Stream::PutCString().
operator=()
const BreakpointResolverAddress & lldb_private::BreakpointResolverAddress::operator= (const BreakpointResolverAddress &) private delete
References BreakpointResolverAddress().
ResolveBreakpoint()
void BreakpointResolverAddress::ResolveBreakpoint (SearchFilter & filter) override virtual
In response to this method the resolver scans all the modules in the breakpoint's target, and adds any new locations it finds.
Parameters
[in] filter The filter that will manage the search for this resolver.
Reimplemented from lldb_private::BreakpointResolver.
Definition at line 89 of file BreakpointResolverAddress.cpp.
References lldb_private::BreakpointResolver::GetBreakpoint(), m_addr, m_module_filespec, and lldb_private::BreakpointResolver::ResolveBreakpoint().
ResolveBreakpointInModules()
void BreakpointResolverAddress::ResolveBreakpointInModules (SearchFilter & filter, ModuleList & modules) override virtual
In response to this method the resolver scans the modules in the module list modules, and adds any new locations it finds.
Parameters
[in] filter The filter that will manage the search for this resolver.
Reimplemented from lldb_private::BreakpointResolver.
Definition at line 104 of file BreakpointResolverAddress.cpp.
References lldb_private::BreakpointResolver::GetBreakpoint(), m_addr, and lldb_private::BreakpointResolver::ResolveBreakpointInModules().
SearchCallback()
Searcher::CallbackReturn BreakpointResolverAddress::SearchCallback (SearchFilter & filter, SymbolContext & context, Address * addr) override virtual
Implements lldb_private::Searcher.
Definition at line 117 of file BreakpointResolverAddress.cpp.
References lldb_private::BreakpointResolver::AddLocation(), lldb_private::SearchFilter::AddressPasses(), lldb_private::BreakpointResolver::Breakpoint, lldb_private::Breakpoints, lldb_private::Searcher::eCallbackReturnStop, lldb::eDescriptionLevelVerbose, error(), lldb_private::ModuleList::FindFirstModule(), lldb_private::BreakpointResolver::GetBreakpoint(), lldb_private::StreamString::GetData(), lldb_private::Target::GetImages(), lldb_private::Breakpoint::GetLocationAtIndex(), lldb_private::GetLog(), lldb_private::Breakpoint::GetNumLocations(), lldb_private::Breakpoint::GetTarget(), lldb_private::Breakpoint::IsInternal(), LLDB_LOG_ERROR, LLDB_LOGF, m_addr, m_module_filespec, and m_resolved_addr.
SerializeToStructuredData()
StructuredData::ObjectSP BreakpointResolverAddress::SerializeToStructuredData () override virtual
Reimplemented from lldb_private::BreakpointResolver.
Definition at line 65 of file BreakpointResolverAddress.cpp.
References lldb_private::BreakpointResolver::AddressOffset, lldb_private::BreakpointResolver::GetKey(), lldb_private::FileSpec::GetPath(), m_addr, m_module_filespec, lldb_private::BreakpointResolver::ModuleName, and lldb_private::BreakpointResolver::WrapOptionsDict().
Member Data Documentation
m_addr
Address lldb_private::BreakpointResolverAddress::m_addr protected
Definition at line 64 of file BreakpointResolverAddress.h.
Referenced by BreakpointResolverAddress(), BreakpointResolverAddress(), CopyForBreakpoint(), GetDescription(), ResolveBreakpoint(), ResolveBreakpointInModules(), SearchCallback(), and SerializeToStructuredData().
m_module_filespec
FileSpec lldb_private::BreakpointResolverAddress::m_module_filespec protected
Definition at line 68 of file BreakpointResolverAddress.h.
Referenced by BreakpointResolverAddress(), ResolveBreakpoint(), SearchCallback(), and SerializeToStructuredData().
m_resolved_addr
lldb::addr_t lldb_private::BreakpointResolverAddress::m_resolved_addr protected
Definition at line 66 of file BreakpointResolverAddress.h.
Referenced by BreakpointResolverAddress(), BreakpointResolverAddress(), and SearchCallback().
The documentation for this class was generated from the following files:
BreakpointResolverAddress.h
BreakpointResolverAddress.cpp