LLDB: lldb_private::FieldEnum Class Reference
lldb_private::FieldEnum Class Reference
#include <RegisterFlags.h>
Classes
struct Enumerator
Public Types
typedef std::vector< Enumerator > Enumerators
Public Member Functions
FieldEnum (std::string id, const Enumerators &enumerators)
const Enumerators & GetEnumerators () const
const std::string & GetID () const
void ToXML (Stream &strm, unsigned size) const
void DumpToLog (Log *log) const
Private Attributes
std::string m_id
Enumerators m_enumerators
Detailed Description
Definition at line 23 of file RegisterFlags.h.
Member Typedef Documentation
Enumerators
typedef std::vector<Enumerator> lldb_private::FieldEnum::Enumerators
Definition at line 39 of file RegisterFlags.h.
Constructor & Destructor Documentation
FieldEnum()
FieldEnum::FieldEnum (std::string id, const Enumerators & enumerators)
Definition at line 423 of file RegisterFlags.cpp.
References m_enumerators, m_id, and UNUSED_IF_ASSERT_DISABLED.
Member Function Documentation
DumpToLog()
void FieldEnum::DumpToLog (Log * log) const
Definition at line 373 of file RegisterFlags.cpp.
References GetEnumerators(), LLDB_LOG, and m_id.
GetEnumerators()
const Enumerators & lldb_private::FieldEnum::GetEnumerators () const inline
Definition at line 46 of file RegisterFlags.h.
References m_enumerators.
Referenced by lldb_private::RegisterFlags::DumpEnums(), DumpToLog(), and ToXML().
GetID()
const std::string & lldb_private::FieldEnum::GetID () const inline
Definition at line 48 of file RegisterFlags.h.
References m_id.
ToXML()
void FieldEnum::ToXML (Stream & strm, unsigned size) const
Definition at line 330 of file RegisterFlags.cpp.
References GetEnumerators(), lldb_private::RegisterFlags::GetID(), lldb_private::Stream::Indent(), lldb_private::Stream::IndentLess(), lldb_private::Stream::IndentMore(), lldb_private::Stream::Printf(), and lldb_private::Stream::PutChar().
Member Data Documentation
m_enumerators
Enumerators lldb_private::FieldEnum::m_enumerators private
Definition at line 56 of file RegisterFlags.h.
Referenced by FieldEnum(), and GetEnumerators().
m_id
std::string lldb_private::FieldEnum::m_id private
Definition at line 55 of file RegisterFlags.h.
Referenced by DumpToLog(), FieldEnum(), and GetID().
The documentation for this class was generated from the following files:
RegisterFlags.h
RegisterFlags.cpp