LLDB: lldb_private::SystemInitializerFull Class Reference
lldb_private::SystemInitializerFull Class Reference
Initializes lldb.
#include <SystemInitializerFull.h>
Public Member Functions
SystemInitializerFull ()
~SystemInitializerFull () override
llvm::Error Initialize () override
void Terminate () override
Public Member Functions inherited from lldb_private::SystemInitializerCommon
SystemInitializerCommon (HostInfo::SharedLibraryDirectoryHelper *helper)
~SystemInitializerCommon () override
Public Member Functions inherited from lldb_private::SystemInitializer
SystemInitializer ()
virtual ~SystemInitializer ()
Detailed Description
Initializes lldb.
This class is responsible for initializing all of lldb system services needed to use the full LLDB application. This class is not intended to be used externally, but is instead used internally by SBDebugger to initialize the system.
Definition at line 21 of file SystemInitializerFull.h.
Constructor & Destructor Documentation
SystemInitializerFull()
SystemInitializerFull::SystemInitializerFull ()
Definition at line 49 of file SystemInitializerFull.cpp.
References g_shlib_dir_helper, and lldb_private::SystemInitializerCommon::SystemInitializerCommon().
~SystemInitializerFull()
SystemInitializerFull::~SystemInitializerFull () override default
Member Function Documentation
Initialize()
llvm::Error SystemInitializerFull::Initialize () override virtual
Reimplemented from lldb_private::SystemInitializerCommon.
Definition at line 53 of file SystemInitializerFull.cpp.
References lldb_private::Debugger::AssertCallback(), error(), lldb_private::Status::FromErrorString(), lldb_private::GetLog(), lldb_private::GetVersion(), lldb_private::Debugger::Initialize(), lldb_private::PluginManager::Initialize(), lldb_private::SystemInitializerCommon::Initialize(), lldb_private::FileSystem::Instance(), LLDB_LOG, lldb_private::SetLLDBAssertCallback(), lldb_private::SetLLDBErrorLog(), lldb_private::Debugger::SettingsInitialize(), and lldb_private::System.
Terminate()
void SystemInitializerFull::Terminate () override virtual
Reimplemented from lldb_private::SystemInitializerCommon.
Definition at line 134 of file SystemInitializerFull.cpp.
References lldb_private::Debugger::SettingsTerminate(), lldb_private::Debugger::Terminate(), lldb_private::PluginManager::Terminate(), lldb_private::ProcessTrace::Terminate(), and lldb_private::SystemInitializerCommon::Terminate().
The documentation for this class was generated from the following files:
SystemInitializerFull.h
SystemInitializerFull.cpp