LLDB: lldb_private::HostNativeThreadBase Class Reference
lldb_private::HostNativeThreadBase Class Reference abstract
#include <HostNativeThreadBase.h>
Public Member Functions
HostNativeThreadBase ()=default
HostNativeThreadBase (lldb::thread_t thread)
virtual ~HostNativeThreadBase ()=default
virtual Status Join (lldb::thread_result_t *result)=0
virtual Status Cancel ()=0
virtual bool IsJoinable () const
virtual void Reset ()
virtual bool EqualsThread (lldb::thread_t thread) const
lldb::thread_t Release ()
lldb::thread_t GetSystemHandle () const
lldb::thread_result_t GetResult () const
Static Protected Member Functions
static lldb::thread_result_t THREAD_ROUTINE ThreadCreateTrampoline (lldb::thread_arg_t arg)
Protected Attributes
lldb::thread_t m_thread = LLDB_INVALID_HOST_THREAD
lldb::thread_result_t m_result = 0
Private Member Functions
HostNativeThreadBase (const HostNativeThreadBase &)=delete
const HostNativeThreadBase & operator= (const HostNativeThreadBase &)=delete
Friends
class ThreadLauncher
Detailed Description
Definition at line 24 of file HostNativeThreadBase.h.
Constructor & Destructor Documentation
HostNativeThreadBase() [1/3]
lldb_private::HostNativeThreadBase::HostNativeThreadBase (const HostNativeThreadBase &) private delete
References HostNativeThreadBase().
Referenced by HostNativeThreadBase(), lldb_private::HostThreadPosix::HostThreadPosix(), lldb_private::HostThreadWindows::HostThreadWindows(), lldb_private::HostThreadWindows::HostThreadWindows(), and operator=().
HostNativeThreadBase() [2/3]
lldb_private::HostNativeThreadBase::HostNativeThreadBase () default
HostNativeThreadBase() [3/3]
HostNativeThreadBase::HostNativeThreadBase (lldb::thread_t thread) explicit
Definition at line 21 of file HostNativeThreadBase.cpp.
References m_thread.
~HostNativeThreadBase()
virtual lldb_private::HostNativeThreadBase::~HostNativeThreadBase () virtual default
Member Function Documentation
Cancel()
virtual Status lldb_private::HostNativeThreadBase::Cancel () pure virtual
Implemented in lldb_private::HostThreadPosix, and lldb_private::HostThreadWindows.
References THREAD_ROUTINE.
EqualsThread()
bool HostNativeThreadBase::EqualsThread (lldb::thread_t thread) const virtual
Reimplemented in lldb_private::HostThreadWindows.
Definition at line 41 of file HostNativeThreadBase.cpp.
References m_thread.
GetResult()
lldb::thread_result_t HostNativeThreadBase::GetResult () const
Definition at line 28 of file HostNativeThreadBase.cpp.
References m_result.
GetSystemHandle()
lldb::thread_t HostNativeThreadBase::GetSystemHandle () const
Definition at line 24 of file HostNativeThreadBase.cpp.
References m_thread.
Referenced by lldb_private::RegisterContextWindows::ApplyAllRegisterValues(), lldb_private::RegisterContextWindows::CacheAllRegisterValues(), and lldb_private::NativeRegisterContextWindows::GetThreadHandle().
IsJoinable()
bool HostNativeThreadBase::IsJoinable () const virtual
Definition at line 32 of file HostNativeThreadBase.cpp.
References LLDB_INVALID_HOST_THREAD, and m_thread.
Referenced by lldb_private::HostThreadPosix::Cancel(), lldb_private::HostThreadPosix::Join(), lldb_private::HostThreadWindows::Join(), and lldb_private::HostThreadPosix::Reset().
Join()
virtual Status lldb_private::HostNativeThreadBase::Join (lldb::thread_result_t * result) pure virtual
Implemented in lldb_private::HostThreadPosix, and lldb_private::HostThreadWindows.
operator=()
const HostNativeThreadBase & lldb_private::HostNativeThreadBase::operator= (const HostNativeThreadBase &) private delete
References HostNativeThreadBase().
Release()
lldb::thread_t HostNativeThreadBase::Release ()
Definition at line 45 of file HostNativeThreadBase.cpp.
References LLDB_INVALID_HOST_THREAD, m_result, and m_thread.
Reset()
void HostNativeThreadBase::Reset () virtual
Reimplemented in lldb_private::HostThreadPosix, and lldb_private::HostThreadWindows.
Definition at line 36 of file HostNativeThreadBase.cpp.
References LLDB_INVALID_HOST_THREAD, m_result, and m_thread.
Referenced by lldb_private::HostThreadPosix::Reset(), and lldb_private::HostThreadWindows::Reset().
ThreadCreateTrampoline()
lldb::thread_result_t HostNativeThreadBase::ThreadCreateTrampoline (lldb::thread_arg_t arg) static protected
Definition at line 54 of file HostNativeThreadBase.cpp.
References lldb_private::GetLog(), LLDB_LOGF, and lldb_private::Thread.
Referenced by lldb_private::ThreadLauncher::LaunchThread(), and lldb_private::HostThreadMacOSX::ThreadCreateTrampoline().
Friends And Related Symbol Documentation
ThreadLauncher
friend class ThreadLauncher friend
Definition at line 25 of file HostNativeThreadBase.h.
References ThreadLauncher.
Referenced by ThreadLauncher.
Member Data Documentation
m_result
lldb::thread_result_t lldb_private::HostNativeThreadBase::m_result = 0 protected
Definition at line 49 of file HostNativeThreadBase.h.
Referenced by GetResult(), Release(), and Reset().
m_thread
lldb::thread_t lldb_private::HostNativeThreadBase::m_thread = LLDB_INVALID_HOST_THREAD protected
Definition at line 48 of file HostNativeThreadBase.h.
Referenced by lldb_private::HostThreadPosix::Cancel(), lldb_private::HostThreadWindows::Cancel(), EqualsThread(), GetSystemHandle(), lldb_private::HostThreadWindows::GetThreadId(), HostNativeThreadBase(), IsJoinable(), lldb_private::HostThreadPosix::Join(), lldb_private::HostThreadWindows::Join(), Release(), Reset(), lldb_private::HostThreadPosix::Reset(), and lldb_private::HostThreadWindows::Reset().
The documentation for this class was generated from the following files:
HostNativeThreadBase.h
HostNativeThreadBase.cpp