LLDB: lldb_private::formatters::LibcxxStdAtomicSyntheticFrontEnd Class Reference
lldb_private::formatters::LibcxxStdAtomicSyntheticFrontEnd Class Reference
Public Member Functions
LibcxxStdAtomicSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
~LibcxxStdAtomicSyntheticFrontEnd () override=default
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Attributes
ValueObject * m_real_child = nullptr
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
Definition at line 87 of file LibCxxAtomic.cpp.
Constructor & Destructor Documentation
LibcxxStdAtomicSyntheticFrontEnd()
lldb_private::formatters::LibcxxStdAtomicSyntheticFrontEnd::LibcxxStdAtomicSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
Definition at line 107 of file LibCxxAtomic.cpp.
References lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd().
~LibcxxStdAtomicSyntheticFrontEnd()
lldb_private::formatters::LibcxxStdAtomicSyntheticFrontEnd::~LibcxxStdAtomicSyntheticFrontEnd () override default
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > lldb_private::formatters::LibcxxStdAtomicSyntheticFrontEnd::CalculateNumChildren () override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 120 of file LibCxxAtomic.cpp.
References m_real_child.
GetChildAtIndex()
lldb::ValueObjectSP lldb_private::formatters::LibcxxStdAtomicSyntheticFrontEnd::GetChildAtIndex (uint32_t idx) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 126 of file LibCxxAtomic.cpp.
References m_real_child.
GetIndexOfChildWithName()
llvm::Expected< size_t > lldb_private::formatters::LibcxxStdAtomicSyntheticFrontEnd::GetIndexOfChildWithName (ConstString name) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 134 of file LibCxxAtomic.cpp.
References lldb_private::ConstString::AsCString().
Update()
lldb::ChildCacheState lldb_private::formatters::LibcxxStdAtomicSyntheticFrontEnd::Update () override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 112 of file LibCxxAtomic.cpp.
References lldb::eRefetch, lldb_private::formatters::GetLibCxxAtomicValue(), lldb_private::SyntheticChildrenFrontEnd::m_backend, and m_real_child.
Member Data Documentation
m_real_child
ValueObject* lldb_private::formatters::LibcxxStdAtomicSyntheticFrontEnd::m_real_child = nullptr private
Definition at line 102 of file LibCxxAtomic.cpp.
Referenced by CalculateNumChildren(), GetChildAtIndex(), and Update().
The documentation for this class was generated from the following file:
LibCxxAtomic.cpp