LLDB: lldb::SBPlatformShellCommand Class Reference
lldb::SBPlatformShellCommand Class Reference
#include <SBPlatform.h>
Public Member Functions
SBPlatformShellCommand (const char *shell, const char *shell_command)
SBPlatformShellCommand (const char *shell_command)
SBPlatformShellCommand (const SBPlatformShellCommand &rhs)
SBPlatformShellCommand & operator= (const SBPlatformShellCommand &rhs)
~SBPlatformShellCommand ()
void Clear ()
const char * GetShell ()
void SetShell (const char *shell)
const char * GetCommand ()
void SetCommand (const char *shell_command)
const char * GetWorkingDirectory ()
void SetWorkingDirectory (const char *path)
uint32_t GetTimeoutSeconds ()
void SetTimeoutSeconds (uint32_t sec)
int GetSignal ()
int GetStatus ()
const char * GetOutput ()
Protected Attributes
PlatformShellCommand * m_opaque_ptr
Friends
class SBPlatform
Detailed Description
Definition at line 56 of file SBPlatform.h.
Constructor & Destructor Documentation
SBPlatformShellCommand() [1/3]
SBPlatformShellCommand::SBPlatformShellCommand (const char * shell, const char * shell_command)
Definition at line 166 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
Referenced by operator=(), and SBPlatformShellCommand().
SBPlatformShellCommand() [2/3]
SBPlatformShellCommand::SBPlatformShellCommand (const char * shell_command)
Definition at line 172 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
SBPlatformShellCommand() [3/3]
SBPlatformShellCommand::SBPlatformShellCommand (const SBPlatformShellCommand & rhs)
Definition at line 177 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBPlatformShellCommand().
~SBPlatformShellCommand()
SBPlatformShellCommand::~SBPlatformShellCommand ()
Definition at line 194 of file SBPlatform.cpp.
References m_opaque_ptr.
Member Function Documentation
Clear()
void SBPlatformShellCommand::Clear ()
Definition at line 196 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetCommand()
const char * SBPlatformShellCommand::GetCommand ()
Definition at line 221 of file SBPlatform.cpp.
References lldb_private::ConstString::GetCString(), LLDB_INSTRUMENT_VA, and m_opaque_ptr.
Referenced by lldb::SBPlatform::Run().
GetOutput()
const char * SBPlatformShellCommand::GetOutput ()
Definition at line 284 of file SBPlatform.cpp.
References lldb_private::ConstString::GetCString(), LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetShell()
const char * SBPlatformShellCommand::GetShell ()
Definition at line 204 of file SBPlatform.cpp.
References lldb_private::ConstString::GetCString(), LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetSignal()
int SBPlatformShellCommand::GetSignal ()
Definition at line 272 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetStatus()
int SBPlatformShellCommand::GetStatus ()
Definition at line 278 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetTimeoutSeconds()
uint32_t SBPlatformShellCommand::GetTimeoutSeconds ()
Definition at line 255 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and UINT32_MAX.
GetWorkingDirectory()
const char * SBPlatformShellCommand::GetWorkingDirectory ()
Definition at line 238 of file SBPlatform.cpp.
References lldb_private::ConstString::GetCString(), LLDB_INSTRUMENT_VA, and m_opaque_ptr.
Referenced by lldb::SBPlatform::Run().
operator=()
SBPlatformShellCommand & SBPlatformShellCommand::operator= (const SBPlatformShellCommand & rhs)
Definition at line 186 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBPlatformShellCommand().
SetCommand()
void SBPlatformShellCommand::SetCommand (const char * shell_command)
Definition at line 229 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
SetShell()
void SBPlatformShellCommand::SetShell (const char * shell)
Definition at line 212 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
SetTimeoutSeconds()
void SBPlatformShellCommand::SetTimeoutSeconds (uint32_t sec)
Definition at line 263 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and UINT32_MAX.
SetWorkingDirectory()
void SBPlatformShellCommand::SetWorkingDirectory (const char * path)
Definition at line 246 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
Referenced by lldb::SBPlatform::Run().
Friends And Related Symbol Documentation
SBPlatform
friend class SBPlatform friend
Definition at line 92 of file SBPlatform.h.
References SBPlatform.
Referenced by SBPlatform.
Member Data Documentation
m_opaque_ptr
PlatformShellCommand* lldb::SBPlatformShellCommand::m_opaque_ptr protected
Definition at line 94 of file SBPlatform.h.
Referenced by Clear(), GetCommand(), GetOutput(), GetShell(), GetSignal(), GetStatus(), GetTimeoutSeconds(), GetWorkingDirectory(), operator=(), lldb::SBPlatform::Run(), SBPlatformShellCommand(), SBPlatformShellCommand(), SBPlatformShellCommand(), SetCommand(), SetShell(), SetTimeoutSeconds(), SetWorkingDirectory(), and ~SBPlatformShellCommand().
The documentation for this class was generated from the following files:
SBPlatform.h
SBPlatform.cpp