LLDB: lldb_private::plugin::dwarf::DWARFIndex::DIERefCallbackImpl Class Reference
lldb_private::plugin::dwarf::DWARFIndex::DIERefCallbackImpl Class Reference
#include <DWARFIndex.h>
Public Member Functions
DIERefCallbackImpl (const DWARFIndex &index, llvm::function_ref< IterationAction(DWARFDIE die)> callback, llvm::StringRef name)
IterationAction operator() (DIERef ref) const
IterationAction operator() (const llvm::AppleAcceleratorTable::Entry &entry) const
Private Attributes
const DWARFIndex & m_index
SymbolFileDWARF & m_dwarf
const llvm::function_ref< IterationAction(DWARFDIE die)> m_callback
const llvm::StringRef m_name
Detailed Description
Definition at line 116 of file DWARFIndex.h.
Constructor & Destructor Documentation
DIERefCallbackImpl()
DWARFIndex::DIERefCallbackImpl::DIERefCallbackImpl (const DWARFIndex & index, llvm::function_ref< IterationAction(DWARFDIE die)> callback, llvm::StringRef name)
Definition at line 86 of file DWARFIndex.cpp.
References lldb_private::plugin::dwarf::DWARFIndex::DWARFIndex(), m_callback, m_dwarf, m_index, lldb_private::plugin::dwarf::DWARFIndex::m_module, and m_name.
Member Function Documentation
operator()() [1/2]
IterationAction DWARFIndex::DIERefCallbackImpl::operator() (const llvm::AppleAcceleratorTable::Entry & entry) const
Definition at line 102 of file DWARFIndex.cpp.
References lldb_private::plugin::dwarf::DIERef::DebugInfo, and operator()().
operator()() [2/2]
IterationAction DWARFIndex::DIERefCallbackImpl::operator() (DIERef ref) const
Definition at line 95 of file DWARFIndex.cpp.
References lldb_private::Continue, m_callback, m_dwarf, m_index, and m_name.
Referenced by operator()().
Member Data Documentation
m_callback
const llvm::function_ref<IterationAction(DWARFDIE die)> lldb_private::plugin::dwarf::DWARFIndex::DIERefCallbackImpl::m_callback private
Definition at line 129 of file DWARFIndex.h.
Referenced by DIERefCallbackImpl(), and operator()().
m_dwarf
SymbolFileDWARF& lldb_private::plugin::dwarf::DWARFIndex::DIERefCallbackImpl::m_dwarf private
Definition at line 128 of file DWARFIndex.h.
Referenced by DIERefCallbackImpl(), and operator()().
m_index
const DWARFIndex& lldb_private::plugin::dwarf::DWARFIndex::DIERefCallbackImpl::m_index private
Definition at line 127 of file DWARFIndex.h.
Referenced by DIERefCallbackImpl(), and operator()().
m_name
const llvm::StringRef lldb_private::plugin::dwarf::DWARFIndex::DIERefCallbackImpl::m_name private
Definition at line 130 of file DWARFIndex.h.
Referenced by DIERefCallbackImpl(), and operator()().
The documentation for this class was generated from the following files:
DWARFIndex.h
DWARFIndex.cpp