LLDB: Instrumenter Class Reference
Instrumenter Class Reference abstract
Finds and instruments individual LLVM IR instructions.
#include <IRDynamicChecks.cpp>
Public Member Functions
Instrumenter (llvm::Module &module, std::shared_ptr< UtilityFunction > checker_function)
Constructor.
virtual ~Instrumenter ()=default
bool Inspect (llvm::Function &function)
Inspect a function to find instructions to instrument.
bool Instrument ()
Instrument all the instructions found by Inspect()
Protected Types
typedef std::vector< llvm::Instruction * > InstVector
typedef InstVector::iterator InstIterator
Protected Member Functions
virtual bool InstrumentInstruction (llvm::Instruction *inst)=0
Add instrumentation to a single instruction.
void RegisterInstruction (llvm::Instruction &inst)
Register a single instruction to be instrumented.
virtual bool InspectInstruction (llvm::Instruction &i)
Determine whether a single instruction is interesting to instrument, and, if so, call RegisterInstruction.
virtual bool InspectBasicBlock (llvm::BasicBlock &bb)
Scan a basic block to see if any instructions are interesting.
virtual bool InspectFunction (llvm::Function &f)
Scan a function to see if any instructions are interesting.
llvm::FunctionCallee BuildObjectCheckerFunc (lldb::addr_t start_address)
Build a function pointer for a function with signature void (*)(uint8_t*, uint8_t*) with a given address.
PointerType * GetI8PtrTy ()
IntegerType * GetIntptrTy ()
Protected Attributes
InstVector m_to_instrument
List of instructions the inspector found.
llvm::Module & m_module
The module which is being instrumented.
std::shared_ptr< UtilityFunction > m_checker_function
The dynamic checker function for the process.
Private Attributes
PointerType * m_i8ptr_ty = nullptr
IntegerType * m_intptr_ty = nullptr
Detailed Description
Finds and instruments individual LLVM IR instructions.
When instrumenting LLVM IR, it is frequently desirable to first search for instructions, and then later modify them. This way iterators remain intact, and multiple passes can look at the same code base without treading on each other's toes.
The Instrumenter class implements this functionality. A client first calls Inspect on a function, which populates a list of instructions to be instrumented. Then, later, when all passes' Inspect functions have been called, the client calls Instrument, which adds the desired instrumentation.
A subclass of Instrumenter must override InstrumentInstruction, which is responsible for adding whatever instrumentation is necessary.
A subclass of Instrumenter may override:
InspectInstruction [default: does nothing]
InspectBasicBlock [default: iterates through the instructions in a basic block calling InspectInstruction]
InspectFunction [default: iterates through the basic blocks in a function calling InspectBasicBlock]
Definition at line 116 of file IRDynamicChecks.cpp.
Member Typedef Documentation
InstIterator
typedef InstVector::iterator Instrumenter::InstIterator protected
Definition at line 256 of file IRDynamicChecks.cpp.
InstVector
typedef std::vector<llvm::Instruction *> Instrumenter::InstVector protected
Definition at line 255 of file IRDynamicChecks.cpp.
Constructor & Destructor Documentation
Instrumenter()
Instrumenter::Instrumenter (llvm::Module & module, std::shared_ptr< UtilityFunction > checker_function) inline
Constructor.
Parameters
[in] module The module being instrumented.
Definition at line 122 of file IRDynamicChecks.cpp.
References m_checker_function, and m_module.
Referenced by ObjcObjectChecker::ObjcObjectChecker().
~Instrumenter()
virtual Instrumenter::~Instrumenter () virtual default
Member Function Documentation
BuildObjectCheckerFunc()
llvm::FunctionCallee Instrumenter::BuildObjectCheckerFunc (lldb::addr_t start_address) inline protected
Build a function pointer for a function with signature void (*)(uint8_t*, uint8_t*) with a given address.
Parameters
[in] start_address The address of the function.
Returns
The function pointer, for use in a CallInst.
Definition at line 222 of file IRDynamicChecks.cpp.
References GetI8PtrTy(), GetIntptrTy(), and m_module.
Referenced by ObjcObjectChecker::InstrumentInstruction().
GetI8PtrTy()
PointerType * Instrumenter::GetI8PtrTy () inline protected
Definition at line 238 of file IRDynamicChecks.cpp.
References m_i8ptr_ty, and m_module.
Referenced by BuildObjectCheckerFunc().
GetIntptrTy()
IntegerType * Instrumenter::GetIntptrTy () inline protected
Definition at line 245 of file IRDynamicChecks.cpp.
References m_intptr_ty, and m_module.
Referenced by BuildObjectCheckerFunc().
Inspect()
bool Instrumenter::Inspect (llvm::Function & function) inline
Inspect a function to find instructions to instrument.
Parameters
[in] function The function to inspect.
Returns
True on success; false on error.
Definition at line 135 of file IRDynamicChecks.cpp.
References InspectFunction().
Referenced by lldb_private::IRDynamicChecks::runOnModule().
InspectBasicBlock()
virtual bool Instrumenter::InspectBasicBlock (llvm::BasicBlock & bb) inline protected virtual
Scan a basic block to see if any instructions are interesting.
Parameters
[in] bb The basic block to be inspected.
Returns
False if there was an error scanning; true otherwise.
Definition at line 187 of file IRDynamicChecks.cpp.
References InspectInstruction().
Referenced by InspectFunction().
InspectFunction()
virtual bool Instrumenter::InspectFunction (llvm::Function & f) inline protected virtual
Scan a function to see if any instructions are interesting.
Parameters
[in] f The function to be inspected.
Returns
False if there was an error scanning; true otherwise.
Definition at line 204 of file IRDynamicChecks.cpp.
References InspectBasicBlock().
Referenced by Inspect().
InspectInstruction()
virtual bool Instrumenter::InspectInstruction (llvm::Instruction & i) inline protected virtual
Determine whether a single instruction is interesting to instrument, and, if so, call RegisterInstruction.
Parameters
[in] i The instruction to be inspected.
Returns
False if there was an error scanning; true otherwise.
Reimplemented in ObjcObjectChecker.
Definition at line 178 of file IRDynamicChecks.cpp.
Referenced by InspectBasicBlock().
Instrument()
bool Instrumenter::Instrument () inline
Instrument all the instructions found by Inspect()
Returns
True on success; false on error.
Definition at line 141 of file IRDynamicChecks.cpp.
References InstrumentInstruction(), and m_to_instrument.
Referenced by lldb_private::IRDynamicChecks::runOnModule().
InstrumentInstruction()
virtual bool Instrumenter::InstrumentInstruction (llvm::Instruction * inst) protected pure virtual
Add instrumentation to a single instruction.
Parameters
[in] inst The instruction to be instrumented.
Returns
True on success; false otherwise.
Implemented in ObjcObjectChecker.
Referenced by Instrument().
RegisterInstruction()
void Instrumenter::RegisterInstruction (llvm::Instruction & inst) inline protected
Register a single instruction to be instrumented.
Parameters
[in] inst The instruction to be instrumented.
Definition at line 166 of file IRDynamicChecks.cpp.
References m_to_instrument.
Referenced by ObjcObjectChecker::InspectInstruction().
Member Data Documentation
m_checker_function
std::shared_ptr<UtilityFunction> Instrumenter::m_checker_function protected
The dynamic checker function for the process.
Definition at line 261 of file IRDynamicChecks.cpp.
Referenced by Instrumenter(), and ObjcObjectChecker::InstrumentInstruction().
m_i8ptr_ty
PointerType* Instrumenter::m_i8ptr_ty = nullptr private
Definition at line 264 of file IRDynamicChecks.cpp.
Referenced by GetI8PtrTy().
m_intptr_ty
IntegerType* Instrumenter::m_intptr_ty = nullptr private
Definition at line 265 of file IRDynamicChecks.cpp.
Referenced by GetIntptrTy().
m_module
llvm::Module& Instrumenter::m_module protected
The module which is being instrumented.
Definition at line 259 of file IRDynamicChecks.cpp.
Referenced by BuildObjectCheckerFunc(), GetI8PtrTy(), GetIntptrTy(), and Instrumenter().
m_to_instrument
InstVector Instrumenter::m_to_instrument protected
List of instructions the inspector found.
Definition at line 258 of file IRDynamicChecks.cpp.
Referenced by Instrument(), and RegisterInstruction().
The documentation for this class was generated from the following file:
IRDynamicChecks.cpp