LLDB: lldb_private::AddressableBits Class Reference
lldb_private::AddressableBits Class Reference
A class which holds the metadata from a remote stub/corefile note about how many bits are used for addressing on this target.
#include "lldb/Core/AddressableBits.h"
Public Member Functions
AddressableBits ()
void SetAddressableBits (uint32_t addressing_bits)
When a single value is available for the number of bits.
void SetAddressableBits (uint32_t lowmem_addressing_bits, uint32_t highmem_addressing_bits)
When we have separate values for low memory addresses and high memory addresses.
void SetLowmemAddressableBits (uint32_t lowmem_addressing_bits)
uint32_t GetLowmemAddressableBits () const
void SetHighmemAddressableBits (uint32_t highmem_addressing_bits)
uint32_t GetHighmemAddressableBits () const
Static Public Member Functions
static lldb::addr_t AddressableBitToMask (uint32_t addressable_bits)
Private Attributes
uint32_t m_low_memory_addr_bits
uint32_t m_high_memory_addr_bits
Detailed Description
A class which holds the metadata from a remote stub/corefile note about how many bits are used for addressing on this target.
Definition at line 23 of file AddressableBits.h.
Constructor & Destructor Documentation
AddressableBits()
lldb_private::AddressableBits::AddressableBits () inline
Definition at line 25 of file AddressableBits.h.
References m_high_memory_addr_bits, and m_low_memory_addr_bits.
Member Function Documentation
AddressableBitToMask()
addr_t AddressableBits::AddressableBitToMask (uint32_t addressable_bits) static
Definition at line 45 of file AddressableBits.cpp.
Referenced by lldb_private::Process::GetCodeAddressMask(), lldb_private::Process::GetDataAddressMask(), lldb_private::Process::GetHighmemCodeAddressMask(), lldb_private::Process::GetHighmemDataAddressMask(), DynamicLoaderDarwinKernel::LoadKernelModuleIfNeeded(), lldb_private::Process::SetAddressableBitMasks(), and lldb::SBProcess::SetAddressableBits().
GetHighmemAddressableBits()
uint32_t AddressableBits::GetHighmemAddressableBits () const
Definition at line 41 of file AddressableBits.cpp.
References m_high_memory_addr_bits.
Referenced by lldb_private::Process::SetAddressableBitMasks().
GetLowmemAddressableBits()
uint32_t AddressableBits::GetLowmemAddressableBits () const
Definition at line 32 of file AddressableBits.cpp.
References m_low_memory_addr_bits.
Referenced by lldb_private::Process::SetAddressableBitMasks().
SetAddressableBits() [1/2]
void AddressableBits::SetAddressableBits (uint32_t addressing_bits)
When a single value is available for the number of bits.
Definition at line 17 of file AddressableBits.cpp.
References m_high_memory_addr_bits, and m_low_memory_addr_bits.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetAddressableBits(), ObjectFileMachO::GetAddressableBits(), and lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo().
SetAddressableBits() [2/2]
void AddressableBits::SetAddressableBits (uint32_t lowmem_addressing_bits, uint32_t highmem_addressing_bits)
When we have separate values for low memory addresses and high memory addresses.
Definition at line 21 of file AddressableBits.cpp.
References m_high_memory_addr_bits, and m_low_memory_addr_bits.
SetHighmemAddressableBits()
void AddressableBits::SetHighmemAddressableBits (uint32_t highmem_addressing_bits)
Definition at line 36 of file AddressableBits.cpp.
References m_high_memory_addr_bits.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo().
SetLowmemAddressableBits()
void AddressableBits::SetLowmemAddressableBits (uint32_t lowmem_addressing_bits)
Definition at line 27 of file AddressableBits.cpp.
References m_low_memory_addr_bits.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo().
Member Data Documentation
m_high_memory_addr_bits
uint32_t lldb_private::AddressableBits::m_high_memory_addr_bits private
Definition at line 47 of file AddressableBits.h.
Referenced by AddressableBits(), GetHighmemAddressableBits(), SetAddressableBits(), SetAddressableBits(), and SetHighmemAddressableBits().
m_low_memory_addr_bits
uint32_t lldb_private::AddressableBits::m_low_memory_addr_bits private
Definition at line 46 of file AddressableBits.h.
Referenced by AddressableBits(), GetLowmemAddressableBits(), SetAddressableBits(), SetAddressableBits(), and SetLowmemAddressableBits().
The documentation for this class was generated from the following files:
AddressableBits.h
AddressableBits.cpp