LLDB: lldb::SBPlatformConnectOptions Class Reference
lldb::SBPlatformConnectOptions Class Reference
#include <SBPlatform.h>
Public Member Functions
SBPlatformConnectOptions (const char *url)
SBPlatformConnectOptions (const SBPlatformConnectOptions &rhs)
~SBPlatformConnectOptions ()
SBPlatformConnectOptions & operator= (const SBPlatformConnectOptions &rhs)
const char * GetURL ()
void SetURL (const char *url)
bool GetRsyncEnabled ()
void EnableRsync (const char *options, const char *remote_path_prefix, bool omit_remote_hostname)
void DisableRsync ()
const char * GetLocalCacheDirectory ()
void SetLocalCacheDirectory (const char *path)
Protected Attributes
PlatformConnectOptions * m_opaque_ptr
Detailed Description
Definition at line 27 of file SBPlatform.h.
Constructor & Destructor Documentation
SBPlatformConnectOptions() [1/2]
SBPlatformConnectOptions::SBPlatformConnectOptions (const char * url)
Definition at line 78 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
Referenced by operator=(), and SBPlatformConnectOptions().
SBPlatformConnectOptions() [2/2]
SBPlatformConnectOptions::SBPlatformConnectOptions (const SBPlatformConnectOptions & rhs)
Definition at line 83 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBPlatformConnectOptions().
~SBPlatformConnectOptions()
SBPlatformConnectOptions::~SBPlatformConnectOptions ()
Definition at line 91 of file SBPlatform.cpp.
References m_opaque_ptr.
Member Function Documentation
DisableRsync()
void SBPlatformConnectOptions::DisableRsync ()
Definition at line 144 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
EnableRsync()
void SBPlatformConnectOptions::EnableRsync (const char * options, const char * remote_path_prefix, bool omit_remote_hostname)
Definition at line 124 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetLocalCacheDirectory()
const char * SBPlatformConnectOptions::GetLocalCacheDirectory ()
Definition at line 150 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetRsyncEnabled()
bool SBPlatformConnectOptions::GetRsyncEnabled ()
Definition at line 118 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetURL()
const char * SBPlatformConnectOptions::GetURL ()
Definition at line 101 of file SBPlatform.cpp.
References lldb_private::ConstString::GetCString(), LLDB_INSTRUMENT_VA, and m_opaque_ptr.
Referenced by lldb::SBPlatform::ConnectRemote().
operator=()
SBPlatformConnectOptions & SBPlatformConnectOptions::operator= (const SBPlatformConnectOptions & rhs)
Definition at line 94 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBPlatformConnectOptions().
SetLocalCacheDirectory()
void SBPlatformConnectOptions::SetLocalCacheDirectory (const char * path)
Definition at line 156 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
SetURL()
void SBPlatformConnectOptions::SetURL (const char * url)
Definition at line 109 of file SBPlatform.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
Member Data Documentation
m_opaque_ptr
PlatformConnectOptions* lldb::SBPlatformConnectOptions::m_opaque_ptr protected
Definition at line 53 of file SBPlatform.h.
Referenced by DisableRsync(), EnableRsync(), GetLocalCacheDirectory(), GetRsyncEnabled(), GetURL(), operator=(), SBPlatformConnectOptions(), SBPlatformConnectOptions(), SetLocalCacheDirectory(), SetURL(), and ~SBPlatformConnectOptions().
The documentation for this class was generated from the following files:
SBPlatform.h
SBPlatform.cpp