LLDB: lldb_private::TypeSummaryImpl::Flags Class Reference
lldb_private::TypeSummaryImpl::Flags Class Reference
#include <TypeSummary.h>
Public Member Functions
Flags ()=default
Flags (const Flags &other)
Flags (uint32_t value)
Flags & operator= (const Flags &rhs)
Flags & operator= (const uint32_t &rhs)
Flags & Clear ()
bool GetCascades () const
Flags & SetCascades (bool value=true)
bool GetSkipPointers () const
Flags & SetSkipPointers (bool value=true)
bool GetSkipReferences () const
Flags & SetSkipReferences (bool value=true)
bool GetDontShowChildren () const
Flags & SetDontShowChildren (bool value=true)
bool GetHideEmptyAggregates () const
Flags & SetHideEmptyAggregates (bool value=true)
bool GetDontShowValue () const
Flags & SetDontShowValue (bool value=true)
bool GetShowMembersOneLiner () const
Flags & SetShowMembersOneLiner (bool value=true)
bool GetHideItemNames () const
Flags & SetHideItemNames (bool value=true)
bool GetNonCacheable () const
Flags & SetNonCacheable (bool value=true)
uint32_t GetValue ()
void SetValue (uint32_t value)
Private Attributes
uint32_t m_flags = lldb::eTypeOptionCascade
Detailed Description
Definition at line 57 of file TypeSummary.h.
Constructor & Destructor Documentation
Flags() [1/3]
lldb_private::TypeSummaryImpl::Flags::Flags () default
Referenced by Clear(), Flags(), operator=(), operator=(), SetCascades(), SetDontShowChildren(), SetDontShowValue(), SetHideEmptyAggregates(), SetHideItemNames(), SetNonCacheable(), SetShowMembersOneLiner(), SetSkipPointers(), and SetSkipReferences().
Flags() [2/3]
lldb_private::TypeSummaryImpl::Flags::Flags (const Flags & other) inline
Definition at line 61 of file TypeSummary.h.
References Flags(), and m_flags.
Flags() [3/3]
lldb_private::TypeSummaryImpl::Flags::Flags (uint32_t value) inline
Definition at line 63 of file TypeSummary.h.
References m_flags.
Member Function Documentation
Clear()
Flags & lldb_private::TypeSummaryImpl::Flags::Clear () inline
Definition at line 77 of file TypeSummary.h.
References Flags(), and m_flags.
GetCascades()
bool lldb_private::TypeSummaryImpl::Flags::GetCascades () const inline
Definition at line 82 of file TypeSummary.h.
References m_flags.
GetDontShowChildren()
bool lldb_private::TypeSummaryImpl::Flags::GetDontShowChildren () const inline
Definition at line 120 of file TypeSummary.h.
References m_flags.
GetDontShowValue()
bool lldb_private::TypeSummaryImpl::Flags::GetDontShowValue () const inline
Definition at line 146 of file TypeSummary.h.
References m_flags.
GetHideEmptyAggregates()
bool lldb_private::TypeSummaryImpl::Flags::GetHideEmptyAggregates () const inline
Definition at line 133 of file TypeSummary.h.
References m_flags.
GetHideItemNames()
bool lldb_private::TypeSummaryImpl::Flags::GetHideItemNames () const inline
Definition at line 172 of file TypeSummary.h.
References m_flags.
GetNonCacheable()
bool lldb_private::TypeSummaryImpl::Flags::GetNonCacheable () const inline
Definition at line 185 of file TypeSummary.h.
References m_flags.
GetShowMembersOneLiner()
bool lldb_private::TypeSummaryImpl::Flags::GetShowMembersOneLiner () const inline
Definition at line 159 of file TypeSummary.h.
References m_flags.
GetSkipPointers()
bool lldb_private::TypeSummaryImpl::Flags::GetSkipPointers () const inline
Definition at line 94 of file TypeSummary.h.
References m_flags.
GetSkipReferences()
bool lldb_private::TypeSummaryImpl::Flags::GetSkipReferences () const inline
Definition at line 107 of file TypeSummary.h.
References m_flags.
GetValue()
uint32_t lldb_private::TypeSummaryImpl::Flags::GetValue () inline
Definition at line 198 of file TypeSummary.h.
References m_flags.
operator=() [1/2]
Flags & lldb_private::TypeSummaryImpl::Flags::operator= (const Flags & rhs) inline
Definition at line 65 of file TypeSummary.h.
References Flags(), and m_flags.
operator=() [2/2]
Flags & lldb_private::TypeSummaryImpl::Flags::operator= (const uint32_t & rhs) inline
Definition at line 72 of file TypeSummary.h.
References Flags(), and m_flags.
SetCascades()
Flags & lldb_private::TypeSummaryImpl::Flags::SetCascades (bool value = true) inline
Definition at line 86 of file TypeSummary.h.
References Flags(), and m_flags.
Referenced by LoadCommonStlFormatters(), LoadCoreMediaFormatters(), LoadLibCxxFormatters(), LoadLibStdcppFormatters(), LoadMsvcStlFormatters(), LoadObjCFormatters(), lldb_private::FormatManager::LoadSystemFormatters(), LoadSystemFormatters(), and lldb_private::FormatManager::LoadVectorFormatters().
SetDontShowChildren()
Flags & lldb_private::TypeSummaryImpl::Flags::SetDontShowChildren (bool value = true) inline
Definition at line 125 of file TypeSummary.h.
References Flags(), and m_flags.
Referenced by LoadCommonStlFormatters(), LoadCoreMediaFormatters(), LoadLibCxxFormatters(), LoadLibStdcppFormatters(), LoadMsvcStlFormatters(), LoadObjCFormatters(), lldb_private::FormatManager::LoadSystemFormatters(), LoadSystemFormatters(), and lldb_private::FormatManager::LoadVectorFormatters().
SetDontShowValue()
Flags & lldb_private::TypeSummaryImpl::Flags::SetDontShowValue (bool value = true) inline
Definition at line 151 of file TypeSummary.h.
References Flags(), and m_flags.
Referenced by LoadCommonStlFormatters(), LoadCoreMediaFormatters(), LoadLibCxxFormatters(), LoadLibStdcppFormatters(), LoadMsvcStlFormatters(), LoadObjCFormatters(), lldb_private::FormatManager::LoadSystemFormatters(), LoadSystemFormatters(), and lldb_private::FormatManager::LoadVectorFormatters().
SetHideEmptyAggregates()
Flags & lldb_private::TypeSummaryImpl::Flags::SetHideEmptyAggregates (bool value = true) inline
Definition at line 138 of file TypeSummary.h.
References Flags(), and m_flags.
SetHideItemNames()
Flags & lldb_private::TypeSummaryImpl::Flags::SetHideItemNames (bool value = true) inline
Definition at line 177 of file TypeSummary.h.
References Flags(), and m_flags.
Referenced by LoadCommonStlFormatters(), LoadCoreMediaFormatters(), LoadLibCxxFormatters(), LoadLibStdcppFormatters(), LoadMsvcStlFormatters(), LoadObjCFormatters(), lldb_private::FormatManager::LoadSystemFormatters(), LoadSystemFormatters(), and lldb_private::FormatManager::LoadVectorFormatters().
SetNonCacheable()
Flags & lldb_private::TypeSummaryImpl::Flags::SetNonCacheable (bool value = true) inline
Definition at line 190 of file TypeSummary.h.
References Flags(), and m_flags.
SetShowMembersOneLiner()
Flags & lldb_private::TypeSummaryImpl::Flags::SetShowMembersOneLiner (bool value = true) inline
Definition at line 164 of file TypeSummary.h.
References Flags(), and m_flags.
Referenced by lldb_private::formatters::AddOneLineSummary(), LoadCommonStlFormatters(), LoadCoreMediaFormatters(), LoadLibCxxFormatters(), LoadLibStdcppFormatters(), LoadMsvcStlFormatters(), LoadObjCFormatters(), lldb_private::FormatManager::LoadSystemFormatters(), LoadSystemFormatters(), and lldb_private::FormatManager::LoadVectorFormatters().
SetSkipPointers()
Flags & lldb_private::TypeSummaryImpl::Flags::SetSkipPointers (bool value = true) inline
Definition at line 99 of file TypeSummary.h.
References Flags(), and m_flags.
Referenced by LoadCommonStlFormatters(), LoadCoreMediaFormatters(), LoadLibCxxFormatters(), LoadLibStdcppFormatters(), LoadMsvcStlFormatters(), LoadObjCFormatters(), lldb_private::FormatManager::LoadSystemFormatters(), LoadSystemFormatters(), and lldb_private::FormatManager::LoadVectorFormatters().
SetSkipReferences()
Flags & lldb_private::TypeSummaryImpl::Flags::SetSkipReferences (bool value = true) inline
Definition at line 112 of file TypeSummary.h.
References Flags(), and m_flags.
Referenced by LoadCommonStlFormatters(), LoadCoreMediaFormatters(), LoadLibCxxFormatters(), LoadLibStdcppFormatters(), LoadMsvcStlFormatters(), LoadObjCFormatters(), lldb_private::FormatManager::LoadSystemFormatters(), LoadSystemFormatters(), and lldb_private::FormatManager::LoadVectorFormatters().
SetValue()
void lldb_private::TypeSummaryImpl::Flags::SetValue (uint32_t value) inline
Definition at line 200 of file TypeSummary.h.
References m_flags.
Member Data Documentation
m_flags
uint32_t lldb_private::TypeSummaryImpl::Flags::m_flags = lldb::eTypeOptionCascade private
Definition at line 203 of file TypeSummary.h.
Referenced by Clear(), Flags(), Flags(), GetCascades(), GetDontShowChildren(), GetDontShowValue(), GetHideEmptyAggregates(), GetHideItemNames(), GetNonCacheable(), GetShowMembersOneLiner(), GetSkipPointers(), GetSkipReferences(), GetValue(), operator=(), operator=(), SetCascades(), SetDontShowChildren(), SetDontShowValue(), SetHideEmptyAggregates(), SetHideItemNames(), SetNonCacheable(), SetShowMembersOneLiner(), SetSkipPointers(), SetSkipReferences(), and SetValue().
The documentation for this class was generated from the following file:
TypeSummary.h