LLDB: CFCBundle Class Reference
CFCBundle Class Reference
#include <CFCBundle.h>
Public Member Functions
CFCBundle (const char *path=NULL)
CFCBundle (CFURLRef url)
~CFCBundle () override
CFURLRef CopyExecutableURL () const
CFStringRef GetIdentifier () const
CFTypeRef GetValueForInfoDictionaryKey (CFStringRef key) const
bool GetPath (char *dst, size_t dst_len)
bool SetPath (const char *path)
Public Member Functions inherited from CFCReleaser< CFBundleRef >
CFCReleaser (CFBundleRef ptr=NULL)
virtual ~CFCReleaser ()
CFCReleaser & operator= (const CFCReleaser< CFBundleRef > &rhs)
CFBundleRef * ptr_address (bool enforce_null=true)
CFBundleRef get ()
void reset (CFBundleRef ptr=NULL)
CFBundleRef release ()
Private Member Functions
CFCBundle (const CFCBundle &)=delete
const CFCBundle & operator= (const CFCBundle &)=delete
Detailed Description
Definition at line 14 of file CFCBundle.h.
Constructor & Destructor Documentation
CFCBundle() [1/3]
CFCBundle::CFCBundle (const char * path = NULL)
Definition at line 13 of file CFCBundle.cpp.
References CFCReleaser< CFBundleRef >::CFCReleaser(), and SetPath().
Referenced by CFCBundle(), and operator=().
CFCBundle() [2/3]
CFCBundle::CFCBundle (CFURLRef url)
Definition at line 18 of file CFCBundle.cpp.
References CFCReleaser< CFBundleRef >::CFCReleaser().
~CFCBundle()
CFCBundle::~CFCBundle () override default
CFCBundle() [3/3]
CFCBundle::CFCBundle (const CFCBundle &) private delete
References CFCBundle().
Member Function Documentation
CopyExecutableURL()
CFURLRef CFCBundle::CopyExecutableURL () const
Definition at line 71 of file CFCBundle.cpp.
References CFCReleaser< CFBundleRef >::get().
Referenced by lldb_private::SymbolLocatorDebugSymbols::LocateExecutableObjectFile(), and LocateMacOSXFilesUsingDebugSymbols().
GetIdentifier()
CFStringRef CFCBundle::GetIdentifier () const
Definition at line 57 of file CFCBundle.cpp.
References CFCReleaser< CFBundleRef >::get().
GetPath()
bool CFCBundle::GetPath (char * dst, size_t dst_len)
Definition at line 43 of file CFCBundle.cpp.
References CFCReleaser< CFBundleRef >::CFCReleaser(), CFCReleaser< T >::get(), and CFCReleaser< CFBundleRef >::get().
GetValueForInfoDictionaryKey()
CFTypeRef CFCBundle::GetValueForInfoDictionaryKey (CFStringRef key) const
Definition at line 64 of file CFCBundle.cpp.
References CFCReleaser< CFBundleRef >::get().
operator=()
const CFCBundle & CFCBundle::operator= (const CFCBundle &) private delete
References CFCBundle().
SetPath()
bool CFCBundle::SetPath (const char * path)
Definition at line 25 of file CFCBundle.cpp.
References CFCReleaser< CFBundleRef >::CFCReleaser(), CFCReleaser< T >::get(), CFCReleaser< CFBundleRef >::get(), CFCReleaser< CFBundleRef >::reset(), and CFCString::SetFileSystemRepresentation().
Referenced by CFCBundle().
The documentation for this class was generated from the following files:
CFCBundle.h
CFCBundle.cpp