LLDB: CommandObjectThreadUntil::CommandOptions Class Reference
CommandObjectThreadUntil::CommandOptions Class Reference
Public Member Functions
CommandOptions ()
~CommandOptions () override=default
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext *execution_context) override
Set the value of an option.
void OptionParsingStarting (ExecutionContext *execution_context) override
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Public Member Functions inherited from lldb_private::Options
Options ()
virtual ~Options ()
void BuildGetoptTable ()
void BuildValidOptionSets ()
uint32_t NumCommandOptions ()
Option * GetLongOptions ()
Get the option definitions to use when parsing Args options.
void OptionSeen (int short_option)
llvm::Error VerifyOptions ()
llvm::Error VerifyPartialOptions ()
void OutputFormattedUsageText (Stream &strm, const OptionDefinition &option_def, uint32_t output_max_columns, bool use_color)
void GenerateOptionUsage (Stream &strm, CommandObject &cmd, uint32_t screen_width, bool use_color)
bool SupportsLongOption (const char *long_option)
void NotifyOptionParsingStarting (ExecutionContext *execution_context)
llvm::Expected< Args > Parse (const Args &args, ExecutionContext *execution_context, lldb::PlatformSP platform_sp, bool require_validation)
Parse the provided arguments.
llvm::Expected< Args > ParseAlias (const Args &args, OptionArgVector *option_arg_vector, std::string &input_line)
OptionElementVector ParseForCompletion (const Args &args, uint32_t cursor_index)
Status NotifyOptionParsingFinished (ExecutionContext *execution_context)
bool HandleOptionCompletion (lldb_private::CompletionRequest &request, OptionElementVector &option_map, CommandInterpreter &interpreter)
Handles the generic bits of figuring out whether we are in an option, and if so completing it.
virtual void HandleOptionArgumentCompletion (lldb_private::CompletionRequest &request, OptionElementVector &opt_element_vector, int opt_element_index, CommandInterpreter &interpreter)
Handles the generic bits of figuring out whether we are in an option, and if so completing it.
Public Attributes
uint32_t m_thread_idx = LLDB_INVALID_THREAD_ID
uint32_t m_frame_idx = LLDB_INVALID_FRAME_ID
uint32_t m_step_thread_idx = LLDB_INVALID_THREAD_ID
bool m_stop_others = false
std::vector< lldb::addr_t > m_until_addrs
Additional Inherited Members
Protected Types inherited from lldb_private::Options
typedef std::set< int > OptionSet
typedef std::vector< OptionSet > OptionSetVector
Protected Member Functions inherited from lldb_private::Options
OptionSetVector & GetRequiredOptions ()
OptionSetVector & GetOptionalOptions ()
bool IsASubset (const OptionSet &set_a, const OptionSet &set_b)
size_t OptionsSetDiff (const OptionSet &set_a, const OptionSet &set_b, OptionSet &diffs)
void OptionsSetUnion (const OptionSet &set_a, const OptionSet &set_b, OptionSet &union_set)
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Protected Attributes inherited from lldb_private::Options
std::vector< Option > m_getopt_table
OptionSet m_seen_options
OptionSetVector m_required_options
OptionSetVector m_optional_options
Detailed Description
Definition at line 792 of file CommandObjectThread.cpp.
Constructor & Destructor Documentation
CommandOptions()
CommandObjectThreadUntil::CommandOptions::CommandOptions () inline
Definition at line 797 of file CommandObjectThread.cpp.
References OptionParsingStarting().
~CommandOptions()
CommandObjectThreadUntil::CommandOptions::~CommandOptions () override default
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > CommandObjectThreadUntil::CommandOptions::GetDefinitions () inline override virtual
Reimplemented from lldb_private::Options.
Definition at line 856 of file CommandObjectThread.cpp.
Referenced by SetOptionValue().
OptionParsingStarting()
void CommandObjectThreadUntil::CommandOptions::OptionParsingStarting (ExecutionContext * execution_context) inline override virtual
Implements lldb_private::Options.
Definition at line 849 of file CommandObjectThread.cpp.
References LLDB_INVALID_THREAD_ID, m_frame_idx, m_stop_others, m_thread_idx, and m_until_addrs.
Referenced by CommandOptions().
SetOptionValue()
Status CommandObjectThreadUntil::CommandOptions::SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext * execution_context) inline override virtual
Set the value of an option.
Parameters
[in] option_idx The index into the "struct option" array that was returned by Options::GetLongOptions().
[in] option_arg The argument value for the option that the user entered, or nullptr if there is no argument for the current option.
[in] execution_context The execution context to use for evaluating the option. May be nullptr if the option is to be evaluated outside any particular context.
See also
Args::ParseOptions (Options&)
man getopt_long_only
Implements lldb_private::Options.
Definition at line 805 of file CommandObjectThread.cpp.
References lldb::eAllThreads, lldb::eOnlyDuringStepping, error(), lldb_private::Status::FromErrorStringWithFormat(), GetDefinitions(), LLDB_INVALID_ADDRESS, LLDB_INVALID_FRAME_ID, LLDB_INVALID_INDEX32, m_frame_idx, lldb_private::Options::m_getopt_table, m_stop_others, m_thread_idx, m_until_addrs, lldb_private::OptionArgParser::ToAddress(), and lldb_private::OptionArgParser::ToOptionEnum().
Member Data Documentation
m_frame_idx
uint32_t CommandObjectThreadUntil::CommandOptions::m_frame_idx = LLDB_INVALID_FRAME_ID
Definition at line 795 of file CommandObjectThread.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_step_thread_idx
uint32_t CommandObjectThreadUntil::CommandOptions::m_step_thread_idx = LLDB_INVALID_THREAD_ID
Definition at line 860 of file CommandObjectThread.cpp.
m_stop_others
bool CommandObjectThreadUntil::CommandOptions::m_stop_others = false
Definition at line 861 of file CommandObjectThread.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_thread_idx
uint32_t CommandObjectThreadUntil::CommandOptions::m_thread_idx = LLDB_INVALID_THREAD_ID
Definition at line 794 of file CommandObjectThread.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_until_addrs
std::vector<lldb::addr_t> CommandObjectThreadUntil::CommandOptions::m_until_addrs
Definition at line 862 of file CommandObjectThread.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following file:
CommandObjectThread.cpp