LLDB: lldb_private::process_netbsd::NativeThreadNetBSD Class Reference
lldb_private::process_netbsd::NativeThreadNetBSD Class Reference
#include <NativeThreadNetBSD.h>
Public Member Functions
NativeThreadNetBSD (NativeProcessNetBSD &process, lldb::tid_t tid)
std::string GetName () override
lldb::StateType GetState () override
bool GetStopReason (ThreadStopInfo &stop_info, std::string &description) override
NativeRegisterContextNetBSD & GetRegisterContext () override
Status SetWatchpoint (lldb::addr_t addr, size_t size, uint32_t watch_flags, bool hardware) override
Status RemoveWatchpoint (lldb::addr_t addr) override
Status SetHardwareBreakpoint (lldb::addr_t addr, size_t size) override
Status RemoveHardwareBreakpoint (lldb::addr_t addr) override
Public Member Functions inherited from lldb_private::NativeThreadProtocol
NativeThreadProtocol (NativeProcessProtocol &process, lldb::tid_t tid)
virtual ~NativeThreadProtocol ()=default
lldb::tid_t GetID () const
NativeProcessProtocol & GetProcess ()
virtual llvm::Expected< std::unique_ptr< llvm::MemoryBuffer > > GetSiginfo () const
Private Types
using WatchpointIndexMap = std::map<lldb::addr_t, uint32_t>
Private Member Functions
Status Resume ()
Status SingleStep ()
Status Suspend ()
void SetStoppedBySignal (uint32_t signo, const siginfo_t *info=nullptr)
void SetStoppedByBreakpoint ()
void SetStoppedByTrace ()
void SetStoppedByExec ()
void SetStoppedByWatchpoint (uint32_t wp_index)
void SetStoppedByFork (lldb::pid_t child_pid, lldb::tid_t child_tid)
void SetStoppedByVFork (lldb::pid_t child_pid, lldb::tid_t child_tid)
void SetStoppedByVForkDone ()
void SetStoppedWithNoReason ()
void SetStopped ()
void SetRunning ()
void SetStepping ()
llvm::Error CopyWatchpointsFrom (NativeThreadNetBSD &source)
Private Attributes
lldb::StateType m_state
ThreadStopInfo m_stop_info
std::unique_ptr< NativeRegisterContextNetBSD > m_reg_context_up
std::string m_stop_description
WatchpointIndexMap m_watchpoint_index_map
WatchpointIndexMap m_hw_break_index_map
Friends
class NativeProcessNetBSD
Additional Inherited Members
Protected Attributes inherited from lldb_private::NativeThreadProtocol
NativeProcessProtocol & m_process
lldb::tid_t m_tid
Detailed Description
Definition at line 25 of file NativeThreadNetBSD.h.
Member Typedef Documentation
WatchpointIndexMap
using lldb_private::process_netbsd::NativeThreadNetBSD::WatchpointIndexMap = std::map<lldb::addr_t, uint32_t> private
Definition at line 77 of file NativeThreadNetBSD.h.
Constructor & Destructor Documentation
NativeThreadNetBSD()
NativeThreadNetBSD::NativeThreadNetBSD (NativeProcessNetBSD & process, lldb::tid_t tid)
Definition at line 36 of file NativeThreadNetBSD.cpp.
References lldb::eStateInvalid, m_reg_context_up, m_state, m_stop_description, m_stop_info, NativeProcessNetBSD, and lldb_private::NativeThreadProtocol::NativeThreadProtocol().
Referenced by CopyWatchpointsFrom(), and NativeProcessNetBSD.
Member Function Documentation
CopyWatchpointsFrom()
llvm::Error NativeThreadNetBSD::CopyWatchpointsFrom (NativeThreadNetBSD & source) private
Definition at line 320 of file NativeThreadNetBSD.cpp.
References lldb_private::process_netbsd::NativeRegisterContextNetBSD::CopyHardwareWatchpointsFrom(), GetRegisterContext(), m_hw_break_index_map, m_watchpoint_index_map, and NativeThreadNetBSD().
Referenced by lldb_private::process_netbsd::NativeProcessNetBSD::MonitorSIGTRAP().
GetName()
std::string NativeThreadNetBSD::GetName () override virtual
Implements lldb_private::NativeThreadProtocol.
Definition at line 181 of file NativeThreadNetBSD.cpp.
References error(), lldb_private::GetLog(), LLDB_LOG, lldb_private::NativeThreadProtocol::m_process, lldb_private::NativeThreadProtocol::m_tid, lldb_private::process_netbsd::NativeProcessNetBSD::PtraceWrapper(), and lldb_private::Thread.
GetRegisterContext()
NativeRegisterContextNetBSD & NativeThreadNetBSD::GetRegisterContext () override virtual
Implements lldb_private::NativeThreadProtocol.
Definition at line 257 of file NativeThreadNetBSD.cpp.
References m_reg_context_up.
Referenced by CopyWatchpointsFrom(), RemoveHardwareBreakpoint(), RemoveWatchpoint(), SetHardwareBreakpoint(), SetStoppedByWatchpoint(), and SetWatchpoint().
GetState()
lldb::StateType NativeThreadNetBSD::GetState () override virtual
Implements lldb_private::NativeThreadProtocol.
Definition at line 225 of file NativeThreadNetBSD.cpp.
References m_state.
GetStopReason()
bool NativeThreadNetBSD::GetStopReason (ThreadStopInfo & stop_info, std::string & description) override virtual
Implements lldb_private::NativeThreadProtocol.
Definition at line 227 of file NativeThreadNetBSD.cpp.
References lldb::eStateAttaching, lldb::eStateConnected, lldb::eStateCrashed, lldb::eStateDetached, lldb::eStateExited, lldb::eStateInvalid, lldb::eStateLaunching, lldb::eStateRunning, lldb::eStateStepping, lldb::eStateStopped, lldb::eStateSuspended, lldb::eStateUnloaded, lldb_private::NativeThreadProtocol::GetID(), lldb_private::GetLog(), LLDB_LOG, m_state, m_stop_description, m_stop_info, lldb_private::StateAsCString(), and lldb_private::Thread.
RemoveHardwareBreakpoint()
Status NativeThreadNetBSD::RemoveHardwareBreakpoint (lldb::addr_t addr) override virtual
Implements lldb_private::NativeThreadProtocol.
Definition at line 305 of file NativeThreadNetBSD.cpp.
References lldb_private::Status::FromErrorString(), GetRegisterContext(), m_hw_break_index_map, and lldb_private::Status.
Referenced by SetHardwareBreakpoint().
RemoveWatchpoint()
Status NativeThreadNetBSD::RemoveWatchpoint (lldb::addr_t addr) override virtual
Implements lldb_private::NativeThreadProtocol.
Definition at line 278 of file NativeThreadNetBSD.cpp.
References lldb_private::Status::FromErrorString(), GetRegisterContext(), m_watchpoint_index_map, and lldb_private::Status.
Referenced by SetWatchpoint().
Resume()
Status NativeThreadNetBSD::Resume () private
Definition at line 43 of file NativeThreadNetBSD.cpp.
References lldb_private::NativeThreadProtocol::GetID(), lldb_private::NativeThreadProtocol::m_process, lldb_private::process_netbsd::NativeProcessNetBSD::PtraceWrapper(), SetRunning(), and lldb_private::Status::Success().
SetHardwareBreakpoint()
Status NativeThreadNetBSD::SetHardwareBreakpoint (lldb::addr_t addr, size_t size) override virtual
Implements lldb_private::NativeThreadProtocol.
Definition at line 289 of file NativeThreadNetBSD.cpp.
References error(), lldb::eStateStopped, lldb_private::Status::FromErrorString(), GetRegisterContext(), LLDB_INVALID_INDEX32, m_hw_break_index_map, m_state, RemoveHardwareBreakpoint(), lldb_private::NativeRegisterContext::SetHardwareBreakpoint(), and lldb_private::Status.
SetRunning()
void NativeThreadNetBSD::SetRunning () private
Definition at line 171 of file NativeThreadNetBSD.cpp.
References lldb::eStateRunning, lldb::eStopReasonNone, m_state, and m_stop_info.
Referenced by Resume().
SetStepping()
void NativeThreadNetBSD::SetStepping () private
Definition at line 176 of file NativeThreadNetBSD.cpp.
References lldb::eStateStepping, lldb::eStopReasonNone, m_state, and m_stop_info.
Referenced by SingleStep().
SetStopped()
void NativeThreadNetBSD::SetStopped () private
Definition at line 165 of file NativeThreadNetBSD.cpp.
References lldb::eStateStopped, m_state, and m_stop_description.
Referenced by SetStoppedByBreakpoint(), SetStoppedByExec(), SetStoppedByFork(), SetStoppedBySignal(), SetStoppedByTrace(), SetStoppedByVFork(), SetStoppedByVForkDone(), SetStoppedByWatchpoint(), SetStoppedWithNoReason(), and Suspend().
SetStoppedByBreakpoint()
void NativeThreadNetBSD::SetStoppedByBreakpoint () private
Definition at line 98 of file NativeThreadNetBSD.cpp.
References lldb::eStopReasonBreakpoint, m_stop_info, SetStopped(), and SIGTRAP.
SetStoppedByExec()
void NativeThreadNetBSD::SetStoppedByExec () private
Definition at line 110 of file NativeThreadNetBSD.cpp.
References lldb::eStopReasonExec, m_stop_info, SetStopped(), and SIGTRAP.
Referenced by lldb_private::process_netbsd::NativeProcessNetBSD::MonitorSIGTRAP().
SetStoppedByFork()
void NativeThreadNetBSD::SetStoppedByFork (lldb::pid_t child_pid, lldb::tid_t child_tid) private
Definition at line 131 of file NativeThreadNetBSD.cpp.
References lldb::eStopReasonFork, m_stop_info, SetStopped(), and SIGTRAP.
Referenced by lldb_private::process_netbsd::NativeProcessNetBSD::MonitorClone().
SetStoppedBySignal()
void NativeThreadNetBSD::SetStoppedBySignal (uint32_t signo, const siginfo_t * info = nullptr) private
Definition at line 75 of file NativeThreadNetBSD.cpp.
References lldb::eStopReasonSignal, GetCrashReasonString(), lldb_private::NativeThreadProtocol::GetID(), lldb_private::GetLog(), LLDB_LOG, m_stop_description, m_stop_info, SetStopped(), SIGBUS, SIGFPE, SIGILL, SIGSEGV, and lldb_private::Thread.
Referenced by lldb_private::process_netbsd::NativeProcessNetBSD::Attach(), lldb_private::process_netbsd::NativeProcessNetBSD::Manager::Launch(), lldb_private::process_netbsd::NativeProcessNetBSD::MonitorClone(), and lldb_private::process_netbsd::NativeProcessNetBSD::MonitorSIGSTOP().
SetStoppedByTrace()
void NativeThreadNetBSD::SetStoppedByTrace () private
Definition at line 104 of file NativeThreadNetBSD.cpp.
References lldb::eStopReasonTrace, m_stop_info, SetStopped(), and SIGTRAP.
SetStoppedByVFork()
void NativeThreadNetBSD::SetStoppedByVFork (lldb::pid_t child_pid, lldb::tid_t child_tid) private
Definition at line 141 of file NativeThreadNetBSD.cpp.
References lldb::eStopReasonVFork, m_stop_info, SetStopped(), and SIGTRAP.
Referenced by lldb_private::process_netbsd::NativeProcessNetBSD::MonitorClone().
SetStoppedByVForkDone()
void NativeThreadNetBSD::SetStoppedByVForkDone () private
Definition at line 151 of file NativeThreadNetBSD.cpp.
References lldb::eStopReasonVForkDone, m_stop_info, SetStopped(), and SIGTRAP.
SetStoppedByWatchpoint()
void NativeThreadNetBSD::SetStoppedByWatchpoint (uint32_t wp_index) private
Definition at line 116 of file NativeThreadNetBSD.cpp.
References lldb::eStopReasonWatchpoint, GetRegisterContext(), lldb_private::NativeRegisterContext::GetWatchpointAddress(), lldb_private::NativeRegisterContext::GetWatchpointHitAddress(), LLDB_INVALID_INDEX32, lldbassert, m_stop_description, m_stop_info, SetStopped(), and SIGTRAP.
SetStoppedWithNoReason()
void NativeThreadNetBSD::SetStoppedWithNoReason () private
Definition at line 158 of file NativeThreadNetBSD.cpp.
References lldb::eStopReasonNone, m_stop_info, and SetStopped().
Referenced by lldb_private::process_netbsd::NativeProcessNetBSD::MonitorSIGTRAP().
SetWatchpoint()
Status NativeThreadNetBSD::SetWatchpoint (lldb::addr_t addr, size_t size, uint32_t watch_flags, bool hardware) override virtual
Implements lldb_private::NativeThreadProtocol.
Definition at line 262 of file NativeThreadNetBSD.cpp.
References error(), lldb::eStateStopped, lldb_private::Status::FromErrorString(), GetRegisterContext(), LLDB_INVALID_INDEX32, m_state, m_watchpoint_index_map, RemoveWatchpoint(), lldb_private::NativeRegisterContext::SetHardwareWatchpoint(), and lldb_private::Status.
SingleStep()
Status NativeThreadNetBSD::SingleStep () private
Definition at line 55 of file NativeThreadNetBSD.cpp.
References lldb_private::NativeThreadProtocol::GetID(), lldb_private::NativeThreadProtocol::m_process, lldb_private::process_netbsd::NativeProcessNetBSD::PtraceWrapper(), SetStepping(), and lldb_private::Status::Success().
Suspend()
Status NativeThreadNetBSD::Suspend () private
Definition at line 67 of file NativeThreadNetBSD.cpp.
References lldb_private::NativeThreadProtocol::GetID(), lldb_private::NativeThreadProtocol::m_process, lldb_private::process_netbsd::NativeProcessNetBSD::PtraceWrapper(), SetStopped(), and lldb_private::Status::Success().
Friends And Related Symbol Documentation
NativeProcessNetBSD
friend class NativeProcessNetBSD friend
Definition at line 26 of file NativeThreadNetBSD.h.
References NativeProcessNetBSD, and NativeThreadNetBSD().
Referenced by NativeProcessNetBSD, and NativeThreadNetBSD().
Member Data Documentation
m_hw_break_index_map
WatchpointIndexMap lldb_private::process_netbsd::NativeThreadNetBSD::m_hw_break_index_map private
Definition at line 79 of file NativeThreadNetBSD.h.
Referenced by CopyWatchpointsFrom(), RemoveHardwareBreakpoint(), and SetHardwareBreakpoint().
m_reg_context_up
std::unique_ptr<NativeRegisterContextNetBSD> lldb_private::process_netbsd::NativeThreadNetBSD::m_reg_context_up private
Definition at line 75 of file NativeThreadNetBSD.h.
Referenced by GetRegisterContext(), and NativeThreadNetBSD().
m_state
lldb::StateType lldb_private::process_netbsd::NativeThreadNetBSD::m_state private
Definition at line 73 of file NativeThreadNetBSD.h.
Referenced by GetState(), GetStopReason(), NativeThreadNetBSD(), SetHardwareBreakpoint(), SetRunning(), SetStepping(), SetStopped(), and SetWatchpoint().
m_stop_description
std::string lldb_private::process_netbsd::NativeThreadNetBSD::m_stop_description private
Definition at line 76 of file NativeThreadNetBSD.h.
Referenced by GetStopReason(), NativeThreadNetBSD(), SetStopped(), SetStoppedBySignal(), and SetStoppedByWatchpoint().
m_stop_info
ThreadStopInfo lldb_private::process_netbsd::NativeThreadNetBSD::m_stop_info private
Definition at line 74 of file NativeThreadNetBSD.h.
Referenced by GetStopReason(), NativeThreadNetBSD(), SetRunning(), SetStepping(), SetStoppedByBreakpoint(), SetStoppedByExec(), SetStoppedByFork(), SetStoppedBySignal(), SetStoppedByTrace(), SetStoppedByVFork(), SetStoppedByVForkDone(), SetStoppedByWatchpoint(), and SetStoppedWithNoReason().
m_watchpoint_index_map
WatchpointIndexMap lldb_private::process_netbsd::NativeThreadNetBSD::m_watchpoint_index_map private
Definition at line 78 of file NativeThreadNetBSD.h.
Referenced by CopyWatchpointsFrom(), RemoveWatchpoint(), and SetWatchpoint().
The documentation for this class was generated from the following files:
NativeThreadNetBSD.h
NativeThreadNetBSD.cpp