LLDB: lldb_private::CommandObjectProxy Class Reference
lldb_private::CommandObjectProxy Class Reference abstract
#include <CommandObjectMultiword.h>
Public Member Functions
CommandObjectProxy (CommandInterpreter &interpreter, const char *name, const char *help=nullptr, const char *syntax=nullptr, uint32_t flags=0)
~CommandObjectProxy () override
virtual CommandObject * GetProxyCommandObject ()=0
llvm::StringRef GetSyntax () override
llvm::StringRef GetHelp () override
llvm::StringRef GetHelpLong () override
bool IsRemovable () const override
bool IsMultiwordObject () override
CommandObjectMultiword * GetAsMultiwordCommand () override
void GenerateHelpText (Stream &result) override
lldb::CommandObjectSP GetSubcommandSP (llvm::StringRef sub_cmd, StringList *matches=nullptr) override
CommandObject * GetSubcommandObject (llvm::StringRef sub_cmd, StringList *matches=nullptr) override
bool LoadSubCommand (llvm::StringRef cmd_name, const lldb::CommandObjectSP &command_obj) override
bool WantsRawCommandString () override
bool WantsCompletion () override
Options * GetOptions () override
void HandleCompletion (CompletionRequest &request) override
This default version handles calling option argument completions and then calls HandleArgumentCompletion if the cursor is on an argument, not an option.
void HandleArgumentCompletion (CompletionRequest &request, OptionElementVector &opt_element_vector) override
The default version handles argument definitions that have only one argument type, and use one of the argument types that have an entry in the CommonCompletions.
std::optional< std::string > GetRepeatCommand (Args &current_command_args, uint32_t index) override
Get the command that appropriate for a "repeat" of the current command.
virtual llvm::StringRef GetUnsupportedError ()
void Execute (const char *args_string, CommandReturnObject &result) override
Public Member Functions inherited from lldb_private::CommandObject
CommandObject (CommandInterpreter &interpreter, llvm::StringRef name, llvm::StringRef help="", llvm::StringRef syntax="", uint32_t flags=0)
virtual ~CommandObject ()=default
CommandInterpreter & GetCommandInterpreter ()
Debugger & GetDebugger ()
llvm::StringRef GetCommandName () const
virtual void SetHelp (llvm::StringRef str)
virtual void SetHelpLong (llvm::StringRef str)
void SetSyntax (llvm::StringRef str)
bool IsUserCommand ()
void SetIsUserCommand (bool is_user)
virtual bool IsAlias ()
virtual bool IsDashDashCommand ()
virtual lldb::CommandObjectSP GetSubcommandSPExact (llvm::StringRef sub_cmd)
void FormatLongHelpText (Stream &output_strm, llvm::StringRef long_help)
void GenerateHelpText (CommandReturnObject &result)
virtual llvm::Error LoadUserSubcommand (llvm::StringRef cmd_name, const lldb::CommandObjectSP &command_obj, bool can_replace)
void AddSimpleArgumentList (lldb::CommandArgumentType arg_type, ArgumentRepetitionType repetition_type=eArgRepeatPlain)
void AddIDsArgumentData (IDType type)
int GetNumArgumentEntries ()
CommandArgumentEntry * GetArgumentEntryAtIndex (int idx)
void GetFormattedCommandArguments (Stream &str, uint32_t opt_set_mask=LLDB_OPT_SET_ALL)
bool ParseOptions (Args &args, CommandReturnObject &result)
void SetCommandName (llvm::StringRef name)
bool HelpTextContainsWord (llvm::StringRef search_word, bool search_short_help=true, bool search_long_help=true, bool search_syntax=true, bool search_options=true)
Flags & GetFlags ()
The flags accessor.
const Flags & GetFlags () const
The flags const accessor.
bool HasOverrideCallback () const
void SetOverrideCallback (lldb::CommandOverrideCallback callback, void *baton)
void SetOverrideCallback (lldb_private::CommandOverrideCallbackWithResult callback, void *baton)
bool InvokeOverrideCallback (const char **argv, CommandReturnObject &result)
void SetOriginalCommandString (std::string s)
Set the command input as it appeared in the terminal.
Friends
class CommandInterpreter
class CommandObjectSyntax
Additional Inherited Members
Public Types inherited from lldb_private::CommandObject
enum IDType { eBreakpointArgs = 0 , eWatchpointArgs = 1 }
typedef llvm::StringRef ArgumentHelpCallbackFunction()
typedef std::vector< CommandArgumentData > CommandArgumentEntry
typedef std::map< std::string, lldb::CommandObjectSP, std::less<> > CommandMap
Static Public Member Functions inherited from lldb_private::CommandObject
static const char * GetArgumentTypeAsCString (const lldb::CommandArgumentType arg_type)
static const char * GetArgumentDescriptionAsCString (const lldb::CommandArgumentType arg_type)
static lldb::CommandArgumentType LookupArgumentName (llvm::StringRef arg_name)
static const ArgumentTableEntry * FindArgumentDataByType (lldb::CommandArgumentType arg_type)
static void GetArgumentHelp (Stream &str, lldb::CommandArgumentType arg_type, CommandInterpreter &interpreter)
static const char * GetArgumentName (lldb::CommandArgumentType arg_type)
static bool IsPairType (ArgumentRepetitionType arg_repeat_type)
static std::optional< ArgumentRepetitionType > ArgRepetitionFromString (llvm::StringRef string)
Protected Member Functions inherited from lldb_private::CommandObject
bool ParseOptionsAndNotify (Args &args, CommandReturnObject &result, OptionGroupOptions &group_options, ExecutionContext &exe_ctx)
virtual const char * GetInvalidTargetDescription ()
virtual const char * GetInvalidProcessDescription ()
virtual const char * GetInvalidThreadDescription ()
virtual const char * GetInvalidFrameDescription ()
virtual const char * GetInvalidRegContextDescription ()
Target & GetDummyTarget ()
Target & GetTarget ()
Thread * GetDefaultThread ()
bool CheckRequirements (CommandReturnObject &result)
Check the command to make sure anything required by this command is available.
void Cleanup ()
Protected Attributes inherited from lldb_private::CommandObject
CommandInterpreter & m_interpreter
ExecutionContext m_exe_ctx
std::unique_lock< std::recursive_mutex > m_api_locker
std::string m_cmd_name
std::string m_cmd_help_short
std::string m_cmd_help_long
std::string m_cmd_syntax
std::string m_original_command
Flags m_flags
std::vector< CommandArgumentEntry > m_arguments
lldb::CommandOverrideCallback m_deprecated_command_override_callback
lldb_private::CommandOverrideCallbackWithResult m_command_override_callback
void * m_command_override_baton
bool m_is_user_command = false
Detailed Description
Definition at line 79 of file CommandObjectMultiword.h.
Constructor & Destructor Documentation
CommandObjectProxy()
CommandObjectProxy::CommandObjectProxy (CommandInterpreter & interpreter, const char * name, const char * help = nullptr, const char * syntax = nullptr, uint32_t flags = 0)
Definition at line 315 of file CommandObjectMultiword.cpp.
References CommandInterpreter, and lldb_private::CommandObject::CommandObject().
Referenced by CommandObjectProcessPlugin::CommandObjectProcessPlugin(), lldb_private::CommandObjectTraceProxy::CommandObjectTraceProxy(), and IsRemovable().
~CommandObjectProxy()
CommandObjectProxy::~CommandObjectProxy () override default
Member Function Documentation
Execute()
void CommandObjectProxy::Execute (const char * args_string, CommandReturnObject & result) override virtual
Parameters
offset_in_command is on what column args_string appears, if applicable. This enables diagnostics that refer back to the user input.
Implements lldb_private::CommandObject.
Definition at line 445 of file CommandObjectMultiword.cpp.
References lldb_private::CommandReturnObject::AppendError(), lldb_private::CommandObject::CommandObject(), GetProxyCommandObject(), and GetUnsupportedError().
GenerateHelpText()
void CommandObjectProxy::GenerateHelpText (Stream & result) override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 372 of file CommandObjectMultiword.cpp.
References lldb_private::CommandObject::CommandObject(), lldb_private::CommandObject::GenerateHelpText(), and GetProxyCommandObject().
GetAsMultiwordCommand()
CommandObjectMultiword * CommandObjectProxy::GetAsMultiwordCommand () override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 365 of file CommandObjectMultiword.cpp.
References lldb_private::CommandObject::CommandObject(), lldb_private::CommandObject::GetAsMultiwordCommand(), and GetProxyCommandObject().
GetHelp()
llvm::StringRef CommandObjectProxy::GetHelp () override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 329 of file CommandObjectMultiword.cpp.
References lldb_private::CommandObject::CommandObject(), lldb_private::CommandObject::GetHelp(), and GetProxyCommandObject().
GetHelpLong()
llvm::StringRef CommandObjectProxy::GetHelpLong () override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 343 of file CommandObjectMultiword.cpp.
References lldb_private::CommandObject::CommandObject(), lldb_private::CommandObject::GetHelpLong(), and GetProxyCommandObject().
GetOptions()
Options * CommandObjectProxy::GetOptions () override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 322 of file CommandObjectMultiword.cpp.
References lldb_private::CommandObject::CommandObject(), lldb_private::CommandObject::GetOptions(), and GetProxyCommandObject().
GetProxyCommandObject()
virtual CommandObject * lldb_private::CommandObjectProxy::GetProxyCommandObject () pure virtual
Implemented in CommandObjectProcessPlugin, and lldb_private::CommandObjectTraceProxy.
References lldb_private::CommandObject::CommandObject().
Referenced by Execute(), GenerateHelpText(), GetAsMultiwordCommand(), GetHelp(), GetHelpLong(), GetOptions(), GetRepeatCommand(), GetSubcommandObject(), GetSubcommandSP(), GetSyntax(), HandleArgumentCompletion(), HandleCompletion(), IsMultiwordObject(), IsRemovable(), LoadSubCommand(), WantsCompletion(), and WantsRawCommandString().
GetRepeatCommand()
std::optional< std::string > CommandObjectProxy::GetRepeatCommand (Args & current_command_args, uint32_t index) override virtual
Get the command that appropriate for a "repeat" of the current command.
Parameters
[in] current_command_args The command arguments.
[in] index This is for internal use - it is how the completion request is tracked in CommandObjectMultiword, and should otherwise be ignored.
Returns
std::nullopt if there is no special repeat command - it will use the current command line. Otherwise a std::string containing the command to be repeated. If the string is empty, the command won't be allow repeating.
Reimplemented from lldb_private::CommandObject.
Definition at line 433 of file CommandObjectMultiword.cpp.
References lldb_private::CommandObject::CommandObject(), GetProxyCommandObject(), and lldb_private::CommandObject::GetRepeatCommand().
GetSubcommandObject()
CommandObject * CommandObjectProxy::GetSubcommandObject (llvm::StringRef sub_cmd, StringList * matches = nullptr) override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 389 of file CommandObjectMultiword.cpp.
References lldb_private::CommandObject::CommandObject(), GetProxyCommandObject(), and lldb_private::CommandObject::GetSubcommandObject().
GetSubcommandSP()
lldb::CommandObjectSP CommandObjectProxy::GetSubcommandSP (llvm::StringRef sub_cmd, StringList * matches = nullptr) override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 381 of file CommandObjectMultiword.cpp.
References lldb_private::CommandObject::CommandObject(), GetProxyCommandObject(), and lldb_private::CommandObject::GetSubcommandSP().
GetSyntax()
llvm::StringRef CommandObjectProxy::GetSyntax () override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 336 of file CommandObjectMultiword.cpp.
References lldb_private::CommandObject::CommandObject(), GetProxyCommandObject(), and lldb_private::CommandObject::GetSyntax().
GetUnsupportedError()
llvm::StringRef CommandObjectProxy::GetUnsupportedError () virtual
Returns
An error message to be displayed when the command is executed (i.e. Execute is called) and GetProxyCommandObject returned null.
Reimplemented in lldb_private::CommandObjectTraceProxy.
Definition at line 441 of file CommandObjectMultiword.cpp.
Referenced by Execute().
HandleArgumentCompletion()
void CommandObjectProxy::HandleArgumentCompletion (CompletionRequest & request, OptionElementVector & opt_element_vector) override virtual
The default version handles argument definitions that have only one argument type, and use one of the argument types that have an entry in the CommonCompletions.
Override this if you have a more complex argument setup. FIXME: we should be able to extend this to more complex argument definitions provided we have completers for all the argument types.
The input array contains a parsed version of the line.
We've constructed the map of options and their arguments as well if that is helpful for the completion.
Parameters
[in,out] request The completion request that needs to be answered.
Reimplemented from lldb_private::CommandObject.
Definition at line 425 of file CommandObjectMultiword.cpp.
References lldb_private::CommandObject::CommandObject(), GetProxyCommandObject(), and lldb_private::CommandObject::HandleArgumentCompletion().
HandleCompletion()
void CommandObjectProxy::HandleCompletion (CompletionRequest & request) override virtual
This default version handles calling option argument completions and then calls HandleArgumentCompletion if the cursor is on an argument, not an option.
Don't override this method, override HandleArgumentCompletion instead unless you have special reasons.
Parameters
[in,out] request The completion request that needs to be answered.
Reimplemented from lldb_private::CommandObject.
Definition at line 419 of file CommandObjectMultiword.cpp.
References lldb_private::CommandObject::CommandObject(), GetProxyCommandObject(), and lldb_private::CommandObject::HandleCompletion().
IsMultiwordObject()
bool CommandObjectProxy::IsMultiwordObject () override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 358 of file CommandObjectMultiword.cpp.
References lldb_private::CommandObject::CommandObject(), GetProxyCommandObject(), and lldb_private::CommandObject::IsMultiwordObject().
IsRemovable()
bool CommandObjectProxy::IsRemovable () const override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 350 of file CommandObjectMultiword.cpp.
References lldb_private::CommandObject::CommandObject(), CommandObjectProxy(), GetProxyCommandObject(), and lldb_private::CommandObject::IsRemovable().
LoadSubCommand()
bool CommandObjectProxy::LoadSubCommand (llvm::StringRef cmd_name, const lldb::CommandObjectSP & command_obj) override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 397 of file CommandObjectMultiword.cpp.
References lldb_private::CommandObject::CommandObject(), GetProxyCommandObject(), and lldb_private::CommandObject::LoadSubCommand().
WantsCompletion()
bool CommandObjectProxy::WantsCompletion () override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 412 of file CommandObjectMultiword.cpp.
References lldb_private::CommandObject::CommandObject(), GetProxyCommandObject(), and lldb_private::CommandObject::WantsCompletion().
WantsRawCommandString()
bool CommandObjectProxy::WantsRawCommandString () override virtual
Implements lldb_private::CommandObject.
Definition at line 405 of file CommandObjectMultiword.cpp.
References lldb_private::CommandObject::CommandObject(), GetProxyCommandObject(), and lldb_private::CommandObject::WantsRawCommandString().
Friends And Related Symbol Documentation
CommandInterpreter
friend class CommandInterpreter friend
Definition at line 138 of file CommandObjectMultiword.h.
References CommandInterpreter.
Referenced by CommandInterpreter, CommandObjectProcessPlugin::CommandObjectProcessPlugin(), CommandObjectProxy(), and lldb_private::CommandObjectTraceProxy::CommandObjectTraceProxy().
CommandObjectSyntax
friend class CommandObjectSyntax friend
Definition at line 139 of file CommandObjectMultiword.h.
References CommandObjectSyntax.
Referenced by CommandObjectSyntax.
The documentation for this class was generated from the following files:
CommandObjectMultiword.h
CommandObjectMultiword.cpp