LLDB: lldb_private::LuaState Class Reference
lldb_private::LuaState Class Reference
#include <LuaState.h>
Public Member Functions
LuaState ()
~LuaState ()
llvm::Error Run (llvm::StringRef buffer)
llvm::Error RegisterBreakpointCallback (void *baton, const char *body)
llvm::Expected< bool > CallBreakpointCallback (void *baton, lldb::StackFrameSP stop_frame_sp, lldb::BreakpointLocationSP bp_loc_sp, StructuredData::ObjectSP extra_args_sp)
llvm::Error RegisterWatchpointCallback (void *baton, const char *body)
llvm::Expected< bool > CallWatchpointCallback (void *baton, lldb::StackFrameSP stop_frame_sp, lldb::WatchpointSP wp_sp)
llvm::Error LoadModule (llvm::StringRef filename)
llvm::Error CheckSyntax (llvm::StringRef buffer)
llvm::Error ChangeIO (FILE *out, FILE *err)
Private Attributes
lua_State * m_lua_state
Detailed Description
Definition at line 25 of file LuaState.h.
Constructor & Destructor Documentation
LuaState()
LuaState::LuaState ()
Definition at line 34 of file LuaState.cpp.
References lldb_print(), lldb_private::luaopen_lldb(), and m_lua_state.
~LuaState()
LuaState::~LuaState ()
Definition at line 42 of file LuaState.cpp.
References m_lua_state.
Member Function Documentation
CallBreakpointCallback()
llvm::Expected< bool > LuaState::CallBreakpointCallback (void * baton, lldb::StackFrameSP stop_frame_sp, lldb::BreakpointLocationSP bp_loc_sp, StructuredData::ObjectSP extra_args_sp)
Definition at line 80 of file LuaState.cpp.
References lldb_private::lua::SWIGBridge::LLDBSwigLuaBreakpointCallbackFunction(), and m_lua_state.
Referenced by lldb_private::ScriptInterpreterLua::BreakpointCallbackFunction().
CallWatchpointCallback()
llvm::Expected< bool > LuaState::CallWatchpointCallback (void * baton, lldb::StackFrameSP stop_frame_sp, lldb::WatchpointSP wp_sp)
Definition at line 109 of file LuaState.cpp.
References lldb_private::lua::SWIGBridge::LLDBSwigLuaWatchpointCallbackFunction(), and m_lua_state.
Referenced by lldb_private::ScriptInterpreterLua::WatchpointCallbackFunction().
ChangeIO()
llvm::Error LuaState::ChangeIO (FILE * out, FILE * err)
Definition at line 163 of file LuaState.cpp.
References m_lua_state.
CheckSyntax()
llvm::Error LuaState::CheckSyntax (llvm::StringRef buffer)
Definition at line 118 of file LuaState.cpp.
References error(), and m_lua_state.
LoadModule()
llvm::Error LuaState::LoadModule (llvm::StringRef filename)
Definition at line 135 of file LuaState.cpp.
References error(), lldb_private::ConstString::GetCString(), lldb_private::FileSpec::GetFileNameExtension(), lldb_private::FileSpec::GetFileNameStrippingExtension(), lldb_private::FileSystem::Instance(), and m_lua_state.
RegisterBreakpointCallback()
llvm::Error LuaState::RegisterBreakpointCallback (void * baton, const char * body)
Definition at line 62 of file LuaState.cpp.
References m_lua_state.
RegisterWatchpointCallback()
llvm::Error LuaState::RegisterWatchpointCallback (void * baton, const char * body)
Definition at line 91 of file LuaState.cpp.
References m_lua_state.
Run()
llvm::Error LuaState::Run (llvm::StringRef buffer)
Definition at line 47 of file LuaState.cpp.
References error(), and m_lua_state.
Member Data Documentation
m_lua_state
lua_State* lldb_private::LuaState::m_lua_state private
Definition at line 45 of file LuaState.h.
Referenced by CallBreakpointCallback(), CallWatchpointCallback(), ChangeIO(), CheckSyntax(), LoadModule(), LuaState(), RegisterBreakpointCallback(), RegisterWatchpointCallback(), Run(), and ~LuaState().
The documentation for this class was generated from the following files:
LuaState.h
LuaState.cpp