LLDB: lldb::SBData Class Reference
lldb::SBData Class Reference
#include <SBData.h>
Public Member Functions
SBData ()
SBData (const SBData &rhs)
const SBData & operator= (const SBData &rhs)
~SBData ()
uint8_t GetAddressByteSize ()
void SetAddressByteSize (uint8_t addr_byte_size)
void Clear ()
operator bool () const
bool IsValid ()
size_t GetByteSize ()
lldb::ByteOrder GetByteOrder ()
void SetByteOrder (lldb::ByteOrder endian)
float GetFloat (lldb::SBError &error, lldb::offset_t offset)
double GetDouble (lldb::SBError &error, lldb::offset_t offset)
long double GetLongDouble (lldb::SBError &error, lldb::offset_t offset)
lldb::addr_t GetAddress (lldb::SBError &error, lldb::offset_t offset)
uint8_t GetUnsignedInt8 (lldb::SBError &error, lldb::offset_t offset)
uint16_t GetUnsignedInt16 (lldb::SBError &error, lldb::offset_t offset)
uint32_t GetUnsignedInt32 (lldb::SBError &error, lldb::offset_t offset)
uint64_t GetUnsignedInt64 (lldb::SBError &error, lldb::offset_t offset)
int8_t GetSignedInt8 (lldb::SBError &error, lldb::offset_t offset)
int16_t GetSignedInt16 (lldb::SBError &error, lldb::offset_t offset)
int32_t GetSignedInt32 (lldb::SBError &error, lldb::offset_t offset)
int64_t GetSignedInt64 (lldb::SBError &error, lldb::offset_t offset)
const char * GetString (lldb::SBError &error, lldb::offset_t offset)
size_t ReadRawData (lldb::SBError &error, lldb::offset_t offset, void *buf, size_t size)
bool GetDescription (lldb::SBStream &description, lldb::addr_t base_addr=LLDB_INVALID_ADDRESS)
void SetData (lldb::SBError &error, const void *buf, size_t size, lldb::ByteOrder endian, uint8_t addr_size)
void SetDataWithOwnership (lldb::SBError &error, const void *buf, size_t size, lldb::ByteOrder endian, uint8_t addr_size)
bool Append (const SBData &rhs)
bool SetDataFromCString (const char *data)
bool SetDataFromUInt64Array (uint64_t *array, size_t array_len)
bool SetDataFromUInt32Array (uint32_t *array, size_t array_len)
bool SetDataFromSInt64Array (int64_t *array, size_t array_len)
bool SetDataFromSInt32Array (int32_t *array, size_t array_len)
bool SetDataFromDoubleArray (double *array, size_t array_len)
Static Public Member Functions
static lldb::SBData CreateDataFromCString (lldb::ByteOrder endian, uint32_t addr_byte_size, const char *data)
static lldb::SBData CreateDataFromUInt64Array (lldb::ByteOrder endian, uint32_t addr_byte_size, uint64_t *array, size_t array_len)
static lldb::SBData CreateDataFromUInt32Array (lldb::ByteOrder endian, uint32_t addr_byte_size, uint32_t *array, size_t array_len)
static lldb::SBData CreateDataFromSInt64Array (lldb::ByteOrder endian, uint32_t addr_byte_size, int64_t *array, size_t array_len)
static lldb::SBData CreateDataFromSInt32Array (lldb::ByteOrder endian, uint32_t addr_byte_size, int32_t *array, size_t array_len)
static lldb::SBData CreateDataFromDoubleArray (lldb::ByteOrder endian, uint32_t addr_byte_size, double *array, size_t array_len)
Protected Member Functions
lldb_private::DataExtractor * get () const
lldb_private::DataExtractor * operator-> () const
lldb::DataExtractorSP & operator* ()
const lldb::DataExtractorSP & operator* () const
SBData (const lldb::DataExtractorSP &data_sp)
void SetOpaque (const lldb::DataExtractorSP &data_sp)
Private Attributes
lldb::DataExtractorSP m_opaque_sp
Friends
class SBInstruction
class SBProcess
class SBSection
class SBTarget
class SBValue
class lldb_private::ScriptInterpreter
Detailed Description
Definition at line 20 of file SBData.h.
Constructor & Destructor Documentation
SBData() [1/3]
SBData::SBData ()
Definition at line 25 of file SBData.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by Append(), CreateDataFromCString(), CreateDataFromDoubleArray(), CreateDataFromSInt32Array(), CreateDataFromSInt64Array(), CreateDataFromUInt32Array(), CreateDataFromUInt64Array(), operator=(), SBData(), and ~SBData().
SBData() [2/3]
SBData::SBData (const SBData & rhs)
Definition at line 31 of file SBData.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBData().
~SBData()
SBData::~SBData () default
References Append(), Clear(), CreateDataFromCString(), CreateDataFromDoubleArray(), CreateDataFromSInt32Array(), CreateDataFromSInt64Array(), CreateDataFromUInt32Array(), CreateDataFromUInt64Array(), error(), get(), GetAddress(), GetAddressByteSize(), GetByteOrder(), GetByteSize(), GetDescription(), GetDouble(), GetFloat(), GetLongDouble(), GetSignedInt16(), GetSignedInt32(), GetSignedInt64(), GetSignedInt8(), GetString(), GetUnsignedInt16(), GetUnsignedInt32(), GetUnsignedInt64(), GetUnsignedInt8(), IsValid(), LLDB_INVALID_ADDRESS, operator*(), operator->(), ReadRawData(), SBData(), SetAddressByteSize(), SetByteOrder(), SetData(), SetDataFromCString(), SetDataFromDoubleArray(), SetDataFromSInt32Array(), SetDataFromSInt64Array(), SetDataFromUInt32Array(), SetDataFromUInt64Array(), SetDataWithOwnership(), and SetOpaque().
SBData() [3/3]
SBData::SBData (const lldb::DataExtractorSP & data_sp) protected
Definition at line 29 of file SBData.cpp.
References m_opaque_sp.
Member Function Documentation
Append()
bool SBData::Append (const SBData & rhs)
Definition at line 375 of file SBData.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBData().
Referenced by ~SBData().
Clear()
void SBData::Clear ()
Definition at line 85 of file SBData.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
CreateDataFromCString()
lldb::SBData SBData::CreateDataFromCString (lldb::ByteOrder endian, uint32_t addr_byte_size, const char * data) static
Definition at line 384 of file SBData.cpp.
References LLDB_INSTRUMENT_VA, and SBData().
Referenced by ~SBData().
CreateDataFromDoubleArray()
lldb::SBData SBData::CreateDataFromDoubleArray (lldb::ByteOrder endian, uint32_t addr_byte_size, double * array, size_t array_len) static
Definition at line 483 of file SBData.cpp.
References LLDB_INSTRUMENT_VA, and SBData().
Referenced by ~SBData().
CreateDataFromSInt32Array()
lldb::SBData SBData::CreateDataFromSInt32Array (lldb::ByteOrder endian, uint32_t addr_byte_size, int32_t * array, size_t array_len) static
Definition at line 463 of file SBData.cpp.
References LLDB_INSTRUMENT_VA, and SBData().
Referenced by ~SBData().
CreateDataFromSInt64Array()
lldb::SBData SBData::CreateDataFromSInt64Array (lldb::ByteOrder endian, uint32_t addr_byte_size, int64_t * array, size_t array_len) static
Definition at line 443 of file SBData.cpp.
References LLDB_INSTRUMENT_VA, and SBData().
Referenced by ~SBData().
CreateDataFromUInt32Array()
lldb::SBData SBData::CreateDataFromUInt32Array (lldb::ByteOrder endian, uint32_t addr_byte_size, uint32_t * array, size_t array_len) static
Definition at line 423 of file SBData.cpp.
References LLDB_INSTRUMENT_VA, and SBData().
Referenced by ~SBData().
CreateDataFromUInt64Array()
lldb::SBData SBData::CreateDataFromUInt64Array (lldb::ByteOrder endian, uint32_t addr_byte_size, uint64_t * array, size_t array_len) static
Definition at line 403 of file SBData.cpp.
References LLDB_INSTRUMENT_VA, and SBData().
Referenced by ~SBData().
get()
lldb_private::DataExtractor * SBData::get () const protected
Definition at line 49 of file SBData.cpp.
References m_opaque_sp.
Referenced by lldb::SBValue::SetData(), and ~SBData().
GetAddress()
lldb::addr_t SBData::GetAddress (lldb::SBError & error, lldb::offset_t offset)
Definition at line 162 of file SBData.cpp.
References error(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
GetAddressByteSize()
uint8_t SBData::GetAddressByteSize ()
Definition at line 69 of file SBData.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by SetDataFromCString(), SetDataFromDoubleArray(), SetDataFromSInt32Array(), SetDataFromSInt64Array(), SetDataFromUInt32Array(), SetDataFromUInt64Array(), and ~SBData().
GetByteOrder()
lldb::ByteOrder SBData::GetByteOrder ()
Definition at line 101 of file SBData.cpp.
References lldb::eByteOrderInvalid, LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by SetDataFromCString(), SetDataFromDoubleArray(), SetDataFromSInt32Array(), SetDataFromSInt64Array(), SetDataFromUInt32Array(), SetDataFromUInt64Array(), and ~SBData().
GetByteSize()
size_t SBData::GetByteSize ()
Definition at line 92 of file SBData.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
GetDescription()
bool SBData::GetDescription (lldb::SBStream & description, lldb::addr_t base_addr = LLDB_INVALID_ADDRESS)
Definition at line 315 of file SBData.cpp.
References lldb_private::DumpDataExtractor(), lldb::eFormatBytesWithASCII, LLDB_INSTRUMENT_VA, m_opaque_sp, lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
Referenced by ~SBData().
GetDouble()
double SBData::GetDouble (lldb::SBError & error, lldb::offset_t offset)
Definition at line 132 of file SBData.cpp.
References error(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
GetFloat()
float SBData::GetFloat (lldb::SBError & error, lldb::offset_t offset)
Definition at line 117 of file SBData.cpp.
References error(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
GetLongDouble()
long double SBData::GetLongDouble (lldb::SBError & error, lldb::offset_t offset)
Definition at line 147 of file SBData.cpp.
References error(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
GetSignedInt16()
int16_t SBData::GetSignedInt16 (lldb::SBError & error, lldb::offset_t offset)
Definition at line 252 of file SBData.cpp.
References error(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
GetSignedInt32()
int32_t SBData::GetSignedInt32 (lldb::SBError & error, lldb::offset_t offset)
Definition at line 267 of file SBData.cpp.
References error(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
GetSignedInt64()
int64_t SBData::GetSignedInt64 (lldb::SBError & error, lldb::offset_t offset)
Definition at line 282 of file SBData.cpp.
References error(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
GetSignedInt8()
int8_t SBData::GetSignedInt8 (lldb::SBError & error, lldb::offset_t offset)
Definition at line 237 of file SBData.cpp.
References error(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
GetString()
const char * SBData::GetString (lldb::SBError & error, lldb::offset_t offset)
Definition at line 297 of file SBData.cpp.
References error(), lldb_private::ConstString::GetCString(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
GetUnsignedInt16()
uint16_t SBData::GetUnsignedInt16 (lldb::SBError & error, lldb::offset_t offset)
Definition at line 192 of file SBData.cpp.
References error(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
GetUnsignedInt32()
uint32_t SBData::GetUnsignedInt32 (lldb::SBError & error, lldb::offset_t offset)
Definition at line 207 of file SBData.cpp.
References error(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
GetUnsignedInt64()
uint64_t SBData::GetUnsignedInt64 (lldb::SBError & error, lldb::offset_t offset)
Definition at line 222 of file SBData.cpp.
References error(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
GetUnsignedInt8()
uint8_t SBData::GetUnsignedInt8 (lldb::SBError & error, lldb::offset_t offset)
Definition at line 177 of file SBData.cpp.
References error(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
IsValid()
bool SBData::IsValid ()
Definition at line 59 of file SBData.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBTarget::CreateValueFromData(), and ~SBData().
operator bool()
SBData::operator bool () const explicit
Definition at line 63 of file SBData.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator*() [1/2]
lldb::DataExtractorSP & SBData::operator* () protected
Definition at line 55 of file SBData.cpp.
References m_opaque_sp.
Referenced by ~SBData().
operator*() [2/2]
const lldb::DataExtractorSP & SBData::operator* () const protected
Definition at line 57 of file SBData.cpp.
References m_opaque_sp.
operator->()
lldb_private::DataExtractor * SBData::operator-> () const protected
Definition at line 51 of file SBData.cpp.
References m_opaque_sp.
Referenced by ~SBData().
operator=()
const SBData & SBData::operator= (const SBData & rhs)
Definition at line 35 of file SBData.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBData().
ReadRawData()
size_t SBData::ReadRawData (lldb::SBError & error, lldb::offset_t offset, void * buf, size_t size)
Definition at line 330 of file SBData.cpp.
References error(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
SetAddressByteSize()
void SBData::SetAddressByteSize (uint8_t addr_byte_size)
Definition at line 78 of file SBData.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
SetByteOrder()
void SBData::SetByteOrder (lldb::ByteOrder endian)
Definition at line 110 of file SBData.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
SetData()
void SBData::SetData (lldb::SBError & error, const void * buf, size_t size, lldb::ByteOrder endian, uint8_t addr_size)
Definition at line 346 of file SBData.cpp.
References error(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
SetDataFromCString()
bool SBData::SetDataFromCString (const char * data)
Definition at line 503 of file SBData.cpp.
References GetAddressByteSize(), GetByteOrder(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
SetDataFromDoubleArray()
bool SBData::SetDataFromDoubleArray (double * array, size_t array_len)
Definition at line 605 of file SBData.cpp.
References GetAddressByteSize(), GetByteOrder(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
SetDataFromSInt32Array()
bool SBData::SetDataFromSInt32Array (int32_t * array, size_t array_len)
Definition at line 585 of file SBData.cpp.
References GetAddressByteSize(), GetByteOrder(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
SetDataFromSInt64Array()
bool SBData::SetDataFromSInt64Array (int64_t * array, size_t array_len)
Definition at line 565 of file SBData.cpp.
References GetAddressByteSize(), GetByteOrder(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
SetDataFromUInt32Array()
bool SBData::SetDataFromUInt32Array (uint32_t * array, size_t array_len)
Definition at line 545 of file SBData.cpp.
References GetAddressByteSize(), GetByteOrder(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
SetDataFromUInt64Array()
bool SBData::SetDataFromUInt64Array (uint64_t * array, size_t array_len)
Definition at line 524 of file SBData.cpp.
References GetAddressByteSize(), GetByteOrder(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
SetDataWithOwnership()
void SBData::SetDataWithOwnership (lldb::SBError & error, const void * buf, size_t size, lldb::ByteOrder endian, uint8_t addr_size)
Definition at line 359 of file SBData.cpp.
References error(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBData().
SetOpaque()
void SBData::SetOpaque (const lldb::DataExtractorSP & data_sp) protected
Definition at line 45 of file SBData.cpp.
References m_opaque_sp.
Referenced by lldb::SBInstruction::GetData(), lldb::SBSection::GetSectionData(), and ~SBData().
Friends And Related Symbol Documentation
lldb_private::ScriptInterpreter
friend class lldb_private::ScriptInterpreter friend
Definition at line 157 of file SBData.h.
SBInstruction
friend class SBInstruction friend
Definition at line 151 of file SBData.h.
References SBInstruction.
Referenced by SBInstruction.
SBProcess
friend class SBProcess friend
Definition at line 152 of file SBData.h.
References SBProcess.
Referenced by SBProcess.
SBSection
friend class SBSection friend
Definition at line 153 of file SBData.h.
References SBSection.
Referenced by SBSection.
SBTarget
friend class SBTarget friend
Definition at line 154 of file SBData.h.
References SBTarget.
Referenced by SBTarget.
SBValue
friend class SBValue friend
Definition at line 155 of file SBData.h.
References SBValue.
Referenced by SBValue.
Member Data Documentation
m_opaque_sp
lldb::DataExtractorSP lldb::SBData::m_opaque_sp private
Definition at line 159 of file SBData.h.
Referenced by Append(), Clear(), get(), GetAddress(), GetAddressByteSize(), GetByteOrder(), GetByteSize(), lldb_private::ScriptInterpreter::GetDataExtractorFromSBData(), GetDescription(), GetDouble(), GetFloat(), GetLongDouble(), GetSignedInt16(), GetSignedInt32(), GetSignedInt64(), GetSignedInt8(), GetString(), GetUnsignedInt16(), GetUnsignedInt32(), GetUnsignedInt64(), GetUnsignedInt8(), operator bool(), operator*(), operator*(), operator->(), operator=(), ReadRawData(), SBData(), SBData(), SBData(), SetAddressByteSize(), SetByteOrder(), SetData(), SetDataFromCString(), SetDataFromDoubleArray(), SetDataFromSInt32Array(), SetDataFromSInt64Array(), SetDataFromUInt32Array(), SetDataFromUInt64Array(), SetDataWithOwnership(), and SetOpaque().
The documentation for this class was generated from the following files:
SBData.h
SBData.cpp