LLDB: lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd Class Reference
lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd Class Reference
Data formatter for libc++'s std::"proxy_array".
Public Member Functions
LibcxxStdProxyArraySyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
~LibcxxStdProxyArraySyntheticFrontEnd () override
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Attributes
ValueObject * m_base = nullptr
A non-owning pointer to the array's __vp_.
CompilerType m_element_type
The type of the array's template argument T.
uint32_t m_element_size = 0
The sizeof the array's template argument T.
ValueObject * m_start = nullptr
A non-owning pointer to the array's __1d_.__begin_.
ValueObject * m_finish = nullptr
A non-owning pointer to the array's __1d_.__end_.
CompilerType m_element_type_size_t
The type of the __1d_ array's template argument T (size_t).
uint32_t m_element_size_size_t = 0
The sizeof the __1d_ array's template argument T (size_t)
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
Data formatter for libc++'s std::"proxy_array".
A proxy_array's are created by using: std::gslice_array operator[](const std::gslice& gslicearr); std::mask_array operator[](const std::valarray<bool>& boolarr); std::indirect_array operator[](const std::valarray<std::size_t>& indarr);
These arrays have the following members:
__vp_ points to std::valarray::__begin_
__1d_ an array of offsets of the elements from __vp_
Definition at line 32 of file LibCxxProxyArray.cpp.
Constructor & Destructor Documentation
LibcxxStdProxyArraySyntheticFrontEnd()
lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::LibcxxStdProxyArraySyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
Definition at line 67 of file LibCxxProxyArray.cpp.
References m_element_type, lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd(), and Update().
~LibcxxStdProxyArraySyntheticFrontEnd()
lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::~LibcxxStdProxyArraySyntheticFrontEnd () override
Definition at line 74 of file LibCxxProxyArray.cpp.
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::CalculateNumChildren () override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 81 of file LibCxxProxyArray.cpp.
References m_element_size_size_t, m_finish, and m_start.
GetChildAtIndex()
lldb::ValueObjectSP lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::GetChildAtIndex (uint32_t idx) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 102 of file LibCxxProxyArray.cpp.
References lldb_private::SyntheticChildrenFrontEnd::CreateValueObjectFromAddress(), lldb_private::StreamString::GetString(), lldb_private::SyntheticChildrenFrontEnd::m_backend, m_base, m_element_size, m_element_size_size_t, m_element_type, m_element_type_size_t, m_start, and lldb_private::Stream::Printf().
GetIndexOfChildWithName()
llvm::Expected< size_t > lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::GetIndexOfChildWithName (ConstString name) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 177 of file LibCxxProxyArray.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::formatters::ExtractIndexFromString(), lldb_private::ConstString::GetCString(), and m_base.
Update()
lldb::ChildCacheState lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::Update () override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 130 of file LibCxxProxyArray.cpp.
References lldb::eRefetch, lldb_private::CompilerType::GetNumTemplateArguments(), lldb_private::CompilerType::GetTypeTemplateArgument(), lldb_private::SyntheticChildrenFrontEnd::m_backend, m_base, m_element_size, m_element_size_size_t, m_element_type, m_element_type_size_t, m_finish, and m_start.
Referenced by LibcxxStdProxyArraySyntheticFrontEnd().
Member Data Documentation
m_base
ValueObject* lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::m_base = nullptr private
A non-owning pointer to the array's __vp_.
Definition at line 48 of file LibCxxProxyArray.cpp.
Referenced by GetChildAtIndex(), GetIndexOfChildWithName(), and Update().
m_element_size
uint32_t lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::m_element_size = 0 private
The sizeof the array's template argument T.
Definition at line 52 of file LibCxxProxyArray.cpp.
Referenced by GetChildAtIndex(), and Update().
m_element_size_size_t
uint32_t lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::m_element_size_size_t = 0 private
The sizeof the __1d_ array's template argument T (size_t)
Definition at line 61 of file LibCxxProxyArray.cpp.
Referenced by CalculateNumChildren(), GetChildAtIndex(), and Update().
m_element_type
CompilerType lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::m_element_type private
The type of the array's template argument T.
Definition at line 50 of file LibCxxProxyArray.cpp.
Referenced by GetChildAtIndex(), LibcxxStdProxyArraySyntheticFrontEnd(), and Update().
m_element_type_size_t
CompilerType lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::m_element_type_size_t private
The type of the __1d_ array's template argument T (size_t).
Definition at line 59 of file LibCxxProxyArray.cpp.
Referenced by GetChildAtIndex(), and Update().
m_finish
ValueObject* lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::m_finish = nullptr private
A non-owning pointer to the array's __1d_.__end_.
Definition at line 57 of file LibCxxProxyArray.cpp.
Referenced by CalculateNumChildren(), and Update().
m_start
ValueObject* lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::m_start = nullptr private
A non-owning pointer to the array's __1d_.__begin_.
Definition at line 55 of file LibCxxProxyArray.cpp.
Referenced by CalculateNumChildren(), GetChildAtIndex(), and Update().
The documentation for this class was generated from the following file:
LibCxxProxyArray.cpp