LLDB: lldb_private::wasm::ObjectFileWasm Class Reference
lldb_private::wasm::ObjectFileWasm Class Reference
Generic Wasm object file reader.
#include <ObjectFileWasm.h>
Classes
struct section_info
Public Member Functions
std::optional< FileSpec > GetExternalDebugInfoFileSpec ()
A Wasm module that has external DWARF debug information should contain a custom section named "external_debug_info", whose payload is an UTF-8 encoded string that points to a Wasm module that contains the debug information for this module.
llvm::StringRef GetPluginName () override
PluginInterface protocol.
bool ParseHeader () override
ObjectFile Protocol.
lldb::ByteOrder GetByteOrder () const override
Gets whether endian swapping should occur when extracting data from this object file.
bool IsExecutable () const override
Tells whether this object file is capable of being the main executable for a process.
uint32_t GetAddressByteSize () const override
Gets the address size in bytes for the current object file.
AddressClass GetAddressClass (lldb::addr_t file_addr) override
Get the address type given a file address in an object file.
void ParseSymtab (lldb_private::Symtab &symtab) override
Parse the symbol table into the provides symbol table object.
bool IsStripped () override
Detect if this object file has been stripped of local symbols.
void CreateSections (SectionList &unified_section_list) override
void Dump (Stream *s) override
Dump a description of this object to a Stream.
ArchSpec GetArchitecture () override
Get the ArchSpec for this object file.
UUID GetUUID () override
Gets the UUID for this object file.
uint32_t GetDependentModules (FileSpecList &files) override
Extract the dependent modules from an object file.
Type CalculateType () override
The object file should be able to calculate its type by looking at its file header and possibly the sections or other data in the object file.
Strata CalculateStrata () override
The object file should be able to calculate the strata of the object file.
bool SetLoadAddress (lldb_private::Target &target, lldb::addr_t value, bool value_is_offset) override
Sets the load address for an entire module, assuming a rigid slide of sections, if possible in the implementation.
lldb_private::Address GetBaseAddress () override
Returns base address of this object file.
Public Member Functions inherited from lldb_private::ObjectFile
ObjectFile (const lldb::ModuleSP &module_sp, const FileSpec *file_spec_ptr, lldb::offset_t file_offset, lldb::offset_t length, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset)
Construct with a parent module, offset, and header data.
ObjectFile (const lldb::ModuleSP &module_sp, const lldb::ProcessSP &process_sp, lldb::addr_t header_addr, lldb::DataExtractorSP extractor_sp)
~ObjectFile () override
Destructor.
virtual lldb::addr_t GetFileOffset () const
Returns the offset into a file at which this object resides.
virtual lldb::addr_t GetByteSize () const
virtual FileSpec & GetFileSpec ()
Get accessor to the object file specification.
virtual const FileSpec & GetFileSpec () const
Get const accessor to the object file specification.
virtual SectionList * GetSectionList (bool update_module_section_list=true)
Gets the section list for the currently selected architecture (and object for archives).
virtual void SectionFileAddressesChanged ()
Notify the ObjectFile that the file addresses in the Sections for this module have been changed.
Symtab * GetSymtab (bool can_create=true)
Gets the symbol table for the currently selected architecture (and object for archives).
virtual void RelocateSection (lldb_private::Section *section)
Perform relocations on the section if necessary.
virtual void ClearSymtab ()
Frees the symbol table.
virtual lldb_private::FileSpecList GetReExportedLibraries ()
Gets the file spec list of libraries re-exported by this object file.
virtual bool AllowAssemblyEmulationUnwindPlans ()
Returns if the function bounds for symbols in this symbol file are likely accurate.
virtual lldb_private::Address GetImageInfoAddress (Target *target)
Similar to Process::GetImageInfoAddress().
virtual lldb_private::Address GetEntryPointAddress ()
Returns the address of the Entry Point in this object file - if the object file doesn't have an entry point (because it is not an executable file) then an invalid address is returned.
virtual uint32_t GetNumThreadContexts ()
virtual std::string GetIdentifierString ()
Some object files may have an identifier string embedded in them, e.g.
virtual lldb_private::AddressableBits GetAddressableBits ()
Some object files may have the number of bits used for addressing embedded in them, e.g.
virtual bool GetCorefileMainBinaryInfo (lldb::addr_t &value, bool &value_is_offset, UUID &uuid, ObjectFile::BinaryType &type)
When the ObjectFile is a core file, lldb needs to locate the "binary" in the core file.
virtual bool GetCorefileThreadExtraInfos (std::vector< lldb::tid_t > &tids)
Get metadata about thread ids from the corefile.
virtual StructuredData::ObjectSP GetCorefileProcessMetadata ()
Get process metadata from the corefile in a StructuredData dictionary.
virtual lldb::RegisterContextSP GetThreadContextAtIndex (uint32_t idx, lldb_private::Thread &thread)
virtual void SetType (Type type)
In cases where the type can't be calculated (elf files), this routine allows someone to explicitly set it.
virtual llvm::VersionTuple GetVersion ()
Get the object file version numbers.
virtual llvm::VersionTuple GetMinimumOSVersion ()
Get the minimum OS version this object file can run on.
virtual llvm::VersionTuple GetSDKVersion ()
Get the SDK OS version this object file was built with.
virtual bool GetIsDynamicLinkEditor ()
Return true if this file is a dynamic link editor (dyld)
Type GetType ()
Strata GetStrata ()
size_t GetData (lldb::offset_t offset, size_t length, lldb::DataExtractorSP &data_sp) const
size_t CopyData (lldb::offset_t offset, size_t length, void *dst) const
virtual size_t ReadSectionData (Section *section, lldb::offset_t section_offset, void *dst, size_t dst_len)
virtual size_t ReadSectionData (Section *section, DataExtractor &section_data)
virtual size_t GetSectionDataSize (Section *section)
bool IsInMemory () const
Returns true if the object file exists only in memory.
virtual llvm::StringRef StripLinkerSymbolAnnotations (llvm::StringRef symbol_name) const
virtual bool CanTrustAddressRanges ()
Can we trust the address ranges accelerator associated with this object file to be complete.
virtual std::vector< LoadableData > GetLoadableData (Target &target)
Loads this objfile to memory.
virtual std::unique_ptr< CallFrameInfo > CreateCallFrameInfo ()
Creates a plugin-specific call frame info.
virtual bool LoadCoreFileImages (lldb_private::Process &process)
Load binaries listed in a corefile.
virtual bool IsGOTSection (const lldb_private::Section &section) const
Returns true if the section is a global offset table section.
uint32_t GetCacheHash ()
Get a hash that can be used for caching object file releated information.
std::string GetObjectName () const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Public Member Functions inherited from lldb_private::ModuleChild
ModuleChild (const lldb::ModuleSP &module_sp)
Construct with owning module.
~ModuleChild ()
Destructor.
const ModuleChild & operator= (const ModuleChild &rhs)
Assignment operator.
lldb::ModuleSP GetModule () const
Get const accessor for the module pointer.
void SetModule (const lldb::ModuleSP &module_sp)
Set accessor for the module pointer.
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static const char * GetPluginDescriptionStatic ()
static ObjectFile * CreateInstance (const lldb::ModuleSP &module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const FileSpec *file, lldb::offset_t file_offset, lldb::offset_t length)
static ObjectFile * CreateMemoryInstance (const lldb::ModuleSP &module_sp, lldb::WritableDataBufferSP data_sp, const lldb::ProcessSP &process_sp, lldb::addr_t header_addr)
static size_t GetModuleSpecifications (const FileSpec &file, lldb::DataExtractorSP &extractor_sp, lldb::offset_t data_offset, lldb::offset_t file_offset, lldb::offset_t length, ModuleSpecList &specs)
Static Public Member Functions inherited from lldb_private::ObjectFile
static lldb::ObjectFileSP FindPlugin (const lldb::ModuleSP &module_sp, const FileSpec *file_spec, lldb::offset_t file_offset, lldb::offset_t file_size, lldb::DataExtractorSP extractor_sp, lldb::offset_t &data_offset)
Find a ObjectFile plug-in that can parse file_spec.
static lldb::ObjectFileSP FindPlugin (const lldb::ModuleSP &module_sp, const lldb::ProcessSP &process_sp, lldb::addr_t header_addr, lldb::WritableDataBufferSP file_data_sp)
Find a ObjectFile plug-in that can parse a file in memory.
static size_t GetModuleSpecifications (const FileSpec &file, lldb::offset_t file_offset, lldb::offset_t file_size, ModuleSpecList &specs, lldb::DataExtractorSP=lldb::DataExtractorSP())
static size_t GetModuleSpecifications (const lldb_private::FileSpec &file, lldb::DataExtractorSP &extractor_sp, lldb::offset_t data_offset, lldb::offset_t file_offset, lldb::offset_t file_size, lldb_private::ModuleSpecList &specs)
static bool IsObjectFile (lldb_private::FileSpec file_spec)
static bool SplitArchivePathWithObject (llvm::StringRef path_with_object, lldb_private::FileSpec &archive_file, lldb_private::ConstString &archive_object, bool must_exist)
Split a path into a file path with object name.
static lldb::WritableDataBufferSP ReadMemory (const lldb::ProcessSP &process_sp, lldb::addr_t addr, size_t byte_size)
static lldb::SymbolType GetSymbolTypeFromName (llvm::StringRef name, lldb::SymbolType symbol_type_hint=lldb::eSymbolTypeUndefined)
static lldb::SectionType GetDWARFSectionTypeFromName (llvm::StringRef name)
Parses the section type from a section name for DWARF sections.
static lldb::DataBufferSP MapFileData (const FileSpec &file, uint64_t Size, uint64_t Offset)
Private Member Functions
ObjectFileWasm (const lldb::ModuleSP &module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const FileSpec *file, lldb::offset_t offset, lldb::offset_t length)
ObjectFileWasm (const lldb::ModuleSP &module_sp, lldb::WritableDataBufferSP header_data_sp, const lldb::ProcessSP &process_sp, lldb::addr_t header_addr)
DataExtractor ReadImageData (lldb::offset_t offset, uint32_t size)
Read a range of bytes from the Wasm module.
std::optional< section_info > GetSectionInfo (uint32_t section_id)
std::optional< section_info > GetSectionInfo (llvm::StringRef section_name)
bool DecodeNextSection (lldb::offset_t *offset_ptr)
Wasm section decoding routines.
bool DecodeSections ()
void DumpSectionHeader (llvm::raw_ostream &ostream, const section_info &sh)
Wasm section header dump routines.
void DumpSectionHeaders (llvm::raw_ostream &ostream)
Private Attributes
std::vector< section_info > m_sect_infos
uint32_t m_num_imported_functions = 0
std::vector< Symbol > m_symbols
ArchSpec m_arch
UUID m_uuid
static char ID
LLVM RTTI support.
static bool classof (const ObjectFile *obj)
bool isA (const void *ClassID) const override
Additional Inherited Members
Public Types inherited from lldb_private::ObjectFile
enum Type {
eTypeInvalid = 0 , eTypeCoreFile , eTypeExecutable , eTypeDebugInfo ,
eTypeDynamicLinker , eTypeObjectFile , eTypeSharedLibrary , eTypeStubLibrary ,
eTypeJIT , eTypeUnknown
}
enum Strata {
eStrataInvalid = 0 , eStrataUnknown , eStrataUser , eStrataKernel ,
eStrataRawImage , eStrataJIT
}
enum BinaryType {
eBinaryTypeInvalid = 0 , eBinaryTypeUnknown , eBinaryTypeKernel , eBinaryTypeUser ,
eBinaryTypeUserAllImageInfos , eBinaryTypeStandalone
}
If we have a corefile binary hint, this enum specifies the binary type which we can use to select the correct DynamicLoader plugin.
Static Public Attributes inherited from lldb_private::ObjectFile
static char ID
Protected Types inherited from lldb_private::ObjectFile
typedef NonNullSharedPtr< lldb_private::DataExtractor > DataExtractorNSP
Protected Member Functions inherited from lldb_private::ObjectFile
bool SetModulesArchitecture (const ArchSpec &new_arch)
Sets the architecture for a module.
Protected Attributes inherited from lldb_private::ObjectFile
FileSpec m_file
Type m_type
Strata m_strata
lldb::addr_t m_file_offset
The offset in bytes into the file, or the address in memory.
lldb::addr_t m_length
The length of this object file if it is known (can be zero if length is unknown or can't be determined).
DataExtractorNSP m_data_nsp
The data for this object file so things can be parsed lazily.
lldb::ProcessWP m_process_wp
const lldb::addr_t m_memory_addr
Set if the object file only exists in memory.
std::unique_ptr< lldb_private::SectionList > m_sections_up
std::unique_ptr< lldb_private::Symtab > m_symtab_up
std::unique_ptr< llvm::once_flag > m_symtab_once_up
We need a llvm::once_flag that we can use to avoid locking the module lock and deadlocking LLDB.
std::optional< uint32_t > m_cache_hash
Protected Attributes inherited from lldb_private::ModuleChild
lldb::ModuleWP m_module_wp
The Module that owns the object that inherits from this class.
Static Protected Attributes inherited from lldb_private::ObjectFile
static size_t g_initial_bytes_to_read = 512
The number of bytes to read when going through the plugins.
Detailed Description
Generic Wasm object file reader.
This class provides a generic wasm32 reader plugin implementing the ObjectFile protocol.
Definition at line 23 of file ObjectFileWasm.h.
Constructor & Destructor Documentation
ObjectFileWasm() [1/2]
ObjectFileWasm::ObjectFileWasm (const lldb::ModuleSP & module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const FileSpec * file, lldb::offset_t offset, lldb::offset_t length) private
Definition at line 288 of file ObjectFileWasm.cpp.
References m_arch, lldb_private::ObjectFile::m_data_nsp, and lldb_private::ObjectFile::ObjectFile().
Referenced by CreateInstance(), and CreateMemoryInstance().
ObjectFileWasm() [2/2]
ObjectFileWasm::ObjectFileWasm (const lldb::ModuleSP & module_sp, lldb::WritableDataBufferSP header_data_sp, const lldb::ProcessSP & process_sp, lldb::addr_t header_addr) private
Definition at line 297 of file ObjectFileWasm.cpp.
References m_arch, and lldb_private::ObjectFile::ObjectFile().
Member Function Documentation
CalculateStrata()
Strata lldb_private::wasm::ObjectFileWasm::CalculateStrata () inline override virtual
The object file should be able to calculate the strata of the object file.
Many object files for platforms might be for either user space debugging or for kernel debugging. If your object file subclass can figure this out, it will help with debugger plug-in selection when it comes time to debug.
Returns
The calculated object file strata for the current object file.
Implements lldb_private::ObjectFile.
Definition at line 100 of file ObjectFileWasm.h.
References lldb_private::ObjectFile::eStrataUser.
CalculateType()
Type lldb_private::wasm::ObjectFileWasm::CalculateType () inline override virtual
The object file should be able to calculate its type by looking at its file header and possibly the sections or other data in the object file.
The file type is used in the debugger to help select the correct plug- ins for the job at hand, so this is important to get right. If any eTypeXXX definitions do not match up with the type of file you are loading, please feel free to add a new enumeration value.
Returns
The calculated file type for the current object file.
Implements lldb_private::ObjectFile.
Definition at line 98 of file ObjectFileWasm.h.
References lldb_private::ObjectFile::eTypeSharedLibrary.
classof()
bool lldb_private::wasm::ObjectFileWasm::classof (const ObjectFile * obj) inline static
Definition at line 63 of file ObjectFileWasm.h.
References ID, lldb_private::ObjectFile::isA(), and lldb_private::ObjectFile::ObjectFile().
CreateInstance()
ObjectFile * ObjectFileWasm::CreateInstance (const lldb::ModuleSP & module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const FileSpec * file, lldb::offset_t file_offset, lldb::offset_t length) static
Definition at line 141 of file ObjectFileWasm.cpp.
References lldb_private::GetLog(), lldb_private::FileSpec::GetPath(), LLDB_LOGF, lldb_private::ObjectFile::MapFileData(), lldb_private::Object, lldb_private::ObjectFile::ObjectFile(), ObjectFileWasm(), and ValidateModuleHeader().
Referenced by Initialize(), and Terminate().
CreateMemoryInstance()
ObjectFile * ObjectFileWasm::CreateMemoryInstance (const lldb::ModuleSP & module_sp, lldb::WritableDataBufferSP data_sp, const lldb::ProcessSP & process_sp, lldb::addr_t header_addr) static
Definition at line 198 of file ObjectFileWasm.cpp.
References lldb_private::ObjectFile::ObjectFile(), ObjectFileWasm(), and ValidateModuleHeader().
Referenced by Initialize().
CreateSections()
void ObjectFileWasm::CreateSections (SectionList & unified_section_list) override virtual
Implements lldb_private::ObjectFile.
Definition at line 578 of file ObjectFileWasm.cpp.
References WasmSegment::Active, lldb_private::SectionList::AddSection(), DecodeSections(), lldb::eSectionTypeCode, lldb::eSectionTypeData, lldb::eSectionTypeOther, lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), GetSectionInfo(), GetSectionTypeFromName(), lldb_private::ObjectFile::IsInMemory(), LLDB_INVALID_OFFSET, LLDB_LOG, LLDB_LOG_ERROR, m_num_imported_functions, m_sect_infos, lldb_private::ObjectFile::m_sections_up, m_symbols, segment::name, lldb_private::Object, ParseData(), ParseFunctions(), ParseImports(), ParseNames(), ReadImageData(), and segment::size.
DecodeNextSection()
bool ObjectFileWasm::DecodeNextSection (lldb::offset_t * offset_ptr) private
Wasm section decoding routines.
Definition at line 213 of file ObjectFileWasm.cpp.
References lldb_private::DataExtractor::GetAsLLVM(), lldb_private::GetLog(), GetWasmString(), LLDB_LOG_ERROR, m_sect_infos, lldb_private::Object, and ReadImageData().
Referenced by DecodeSections().
DecodeSections()
bool ObjectFileWasm::DecodeSections () private
Definition at line 265 of file ObjectFileWasm.cpp.
References DecodeNextSection(), lldb_private::ObjectFile::IsInMemory(), kWasmHeaderSize, and lldb_private::ObjectFile::m_memory_addr.
Referenced by CreateSections(), and SetLoadAddress().
Dump()
void ObjectFileWasm::Dump (Stream * s) override virtual
Dump a description of this object to a Stream.
Dump a description of the current contents of this object to the supplied stream s. The dumping should include the section list if it has been parsed, and the symbol table if it has been parsed.
Parameters
[in] s The stream to which to dump the object description.
Implements lldb_private::ObjectFile.
Definition at line 829 of file ObjectFileWasm.cpp.
References lldb_private::Stream::AsRawOstream(), lldb_private::SectionList::Dump(), DumpSectionHeaders(), GetArchitecture(), lldb_private::ArchSpec::GetArchitectureName(), lldb_private::Stream::GetIndentLevel(), lldb_private::ModuleChild::GetModule(), lldb_private::ObjectFile::GetSectionList(), lldb_private::Stream::Indent(), lldb_private::ObjectFile::m_file, and UINT32_MAX.
DumpSectionHeader()
void ObjectFileWasm::DumpSectionHeader (llvm::raw_ostream & ostream, const section_info & sh) private
Wasm section header dump routines.
Definition at line 854 of file ObjectFileWasm.cpp.
References lldb_private::ConstString::GetStringRef(), lldb_private::wasm::ObjectFileWasm::section_info::id, lldb_private::wasm::ObjectFileWasm::section_info::name, lldb_private::wasm::ObjectFileWasm::section_info::offset, and lldb_private::wasm::ObjectFileWasm::section_info::size.
Referenced by DumpSectionHeaders().
DumpSectionHeaders()
void ObjectFileWasm::DumpSectionHeaders (llvm::raw_ostream & ostream) private
Definition at line 862 of file ObjectFileWasm.cpp.
References DumpSectionHeader(), and m_sect_infos.
Referenced by Dump().
GetAddressByteSize()
uint32_t lldb_private::wasm::ObjectFileWasm::GetAddressByteSize () const inline override virtual
Gets the address size in bytes for the current object file.
Returns
The size of an address in bytes for the currently selected architecture (and object for archives). Returns zero if no architecture or object has been selected.
Implements lldb_private::ObjectFile.
Definition at line 76 of file ObjectFileWasm.h.
References m_arch.
Referenced by ReadImageData().
GetAddressClass()
AddressClass lldb_private::wasm::ObjectFileWasm::GetAddressClass (lldb::addr_t file_addr) inline override virtual
Get the address type given a file address in an object file.
Many binary file formats know what kinds This is primarily for ARM binaries, though it can be applied to any executable file format that supports different opcode types within the same binary. ARM binaries support having both ARM and Thumb within the same executable container. We need to be able to get
Returns
The size of an address in bytes for the currently selected architecture (and object for archives). Returns zero if no architecture or object has been selected.
Reimplemented from lldb_private::ObjectFile.
Definition at line 80 of file ObjectFileWasm.h.
References lldb_private::eInvalid.
GetArchitecture()
ArchSpec lldb_private::wasm::ObjectFileWasm::GetArchitecture () inline override virtual
Get the ArchSpec for this object file.
Returns
The ArchSpec of this object file. In case of error, an invalid ArchSpec object is returned.
Implements lldb_private::ObjectFile.
Definition at line 92 of file ObjectFileWasm.h.
References m_arch.
Referenced by Dump().
GetBaseAddress()
lldb_private::Address lldb_private::wasm::ObjectFileWasm::GetBaseAddress () inline override virtual
Returns base address of this object file.
This also sometimes referred to as the "preferred load address" or the "image base address". Addresses within object files are often expressed relative to this base. If this address corresponds to a specific section (usually the first byte of the first section) then the returned address will have this section set. Otherwise, the address will just have the offset member filled in, indicating that this represents a file address.
Reimplemented from lldb_private::ObjectFile.
Definition at line 105 of file ObjectFileWasm.h.
References lldb_private::ObjectFile::IsInMemory(), and lldb_private::ObjectFile::m_memory_addr.
GetByteOrder()
lldb::ByteOrder lldb_private::wasm::ObjectFileWasm::GetByteOrder () const inline override virtual
Gets whether endian swapping should occur when extracting data from this object file.
Returns
Returns true if endian swapping is needed, false otherwise.
Implements lldb_private::ObjectFile.
Definition at line 70 of file ObjectFileWasm.h.
References m_arch.
Referenced by ReadImageData().
GetDependentModules()
uint32_t lldb_private::wasm::ObjectFileWasm::GetDependentModules (FileSpecList & file_list) inline override virtual
Extract the dependent modules from an object file.
If an object file has information about which other images it depends on (such as shared libraries), this function will provide the list. Since many executables or shared libraries may depend on the same files, FileSpecList::AppendIfUnique(const FileSpec &) should be used to make sure any files that are added are not already in the list.
Parameters
[out] file_list A list of file specification objects that gets dependent files appended to.
Returns
The number of new files that were appended to file_list.
See also
FileSpecList::AppendIfUnique(const FileSpec &)
Implements lldb_private::ObjectFile.
Definition at line 96 of file ObjectFileWasm.h.
GetExternalDebugInfoFileSpec()
std::optional< FileSpec > ObjectFileWasm::GetExternalDebugInfoFileSpec ()
A Wasm module that has external DWARF debug information should contain a custom section named "external_debug_info", whose payload is an UTF-8 encoded string that points to a Wasm module that contains the debug information for this module.
Definition at line 807 of file ObjectFileWasm.cpp.
References lldb_private::DataExtractor::GetAsLLVM(), GetWasmString(), m_sect_infos, and ReadImageData().
Referenced by lldb_private::wasm::SymbolVendorWasm::CreateInstance(), and IsStripped().
GetModuleSpecifications()
size_t ObjectFileWasm::GetModuleSpecifications (const FileSpec & file, lldb::DataExtractorSP & extractor_sp, lldb::offset_t data_offset, lldb::offset_t file_offset, lldb::offset_t length, ModuleSpecList & specs) static
Definition at line 276 of file ObjectFileWasm.cpp.
References lldb_private::ModuleSpecList::Append(), and ValidateModuleHeader().
Referenced by Initialize().
GetPluginDescriptionStatic()
const char * lldb_private::wasm::ObjectFileWasm::GetPluginDescriptionStatic () inline static
Definition at line 29 of file ObjectFileWasm.h.
Referenced by Initialize().
GetPluginName()
llvm::StringRef lldb_private::wasm::ObjectFileWasm::GetPluginName () inline override virtual
PluginInterface protocol.
Implements lldb_private::PluginInterface.
Definition at line 54 of file ObjectFileWasm.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::wasm::ObjectFileWasm::GetPluginNameStatic () inline static
Definition at line 28 of file ObjectFileWasm.h.
Referenced by GetPluginName(), and Initialize().
GetSectionInfo() [1/2]
std::optional< ObjectFileWasm::section_info > ObjectFileWasm::GetSectionInfo (llvm::StringRef section_name) private
Definition at line 570 of file ObjectFileWasm.cpp.
References m_sect_infos.
GetSectionInfo() [2/2]
std::optional< ObjectFileWasm::section_info > ObjectFileWasm::GetSectionInfo (uint32_t section_id) private
Definition at line 561 of file ObjectFileWasm.cpp.
References m_sect_infos.
Referenced by CreateSections().
GetUUID()
UUID lldb_private::wasm::ObjectFileWasm::GetUUID () inline override virtual
Gets the UUID for this object file.
If the object file format contains a UUID, the value should be returned. Else ObjectFile instances should return the MD5 checksum of all of the bytes for the object file (or memory for memory based object files).
Returns
The object file's UUID. In case of an error, an empty UUID is returned.
Implements lldb_private::ObjectFile.
Definition at line 94 of file ObjectFileWasm.h.
References m_uuid.
Referenced by lldb_private::wasm::SymbolVendorWasm::CreateInstance().
Initialize()
void ObjectFileWasm::Initialize () static
Definition at line 131 of file ObjectFileWasm.cpp.
References CreateInstance(), CreateMemoryInstance(), GetModuleSpecifications(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
isA()
bool lldb_private::wasm::ObjectFileWasm::isA (const void * ClassID) const inline override virtual
Reimplemented from lldb_private::ObjectFile.
Definition at line 60 of file ObjectFileWasm.h.
References ID, and lldb_private::ObjectFile::isA().
IsExecutable()
bool lldb_private::wasm::ObjectFileWasm::IsExecutable () const inline override virtual
Tells whether this object file is capable of being the main executable for a process.
Returns
true if it is, false otherwise.
Implements lldb_private::ObjectFile.
Definition at line 74 of file ObjectFileWasm.h.
IsStripped()
bool lldb_private::wasm::ObjectFileWasm::IsStripped () inline override virtual
Detect if this object file has been stripped of local symbols.
Detect if this object file has been stripped of local symbols.
Returns
Return true if the object file has been stripped of local symbols.
Implements lldb_private::ObjectFile.
Definition at line 86 of file ObjectFileWasm.h.
References GetExternalDebugInfoFileSpec().
ParseHeader()
bool ObjectFileWasm::ParseHeader () override virtual
ObjectFile Protocol.
Implements lldb_private::ObjectFile.
Definition at line 305 of file ObjectFileWasm.cpp.
ParseSymtab()
void ObjectFileWasm::ParseSymtab (lldb_private::Symtab & symtab) override virtual
Parse the symbol table into the provides symbol table object.
Symbol table parsing will be done once when this function is called by each object file plugin. All of the necessary locks will already be acquired before this function is called and the symbol table object to populate is supplied as an argument and doesn't need to be created by each plug-in.
Parameters
The symbol table to populate.
Implements lldb_private::ObjectFile.
Definition at line 544 of file ObjectFileWasm.cpp.
References lldb_private::Symtab::AddSymbol(), lldb_private::Symtab::Finalize(), and m_symbols.
ReadImageData()
DataExtractor ObjectFileWasm::ReadImageData (lldb::offset_t offset, uint32_t size) private
Read a range of bytes from the Wasm module.
Definition at line 777 of file ObjectFileWasm.cpp.
References GetAddressByteSize(), GetByteOrder(), lldb_private::ObjectFile::GetByteSize(), lldb_private::ObjectFile::m_data_nsp, lldb_private::ObjectFile::m_file, lldb_private::ObjectFile::m_process_wp, lldb_private::ObjectFile::MapFileData(), lldb_private::DataExtractor::SetByteOrder(), and lldb_private::DataExtractor::SetData().
Referenced by CreateSections(), DecodeNextSection(), and GetExternalDebugInfoFileSpec().
SetLoadAddress()
bool ObjectFileWasm::SetLoadAddress (lldb_private::Target & target, lldb::addr_t value, bool value_is_offset) override virtual
Sets the load address for an entire module, assuming a rigid slide of sections, if possible in the implementation.
Returns
Returns true iff any section's load address changed.
In WebAssembly, linear memory is disjointed from code space. The VM can load multiple instances of a module, which logically share the same code. We represent a wasm32 code address with 64-bits, like: 63 32 31 0 +------------—+------------—+
module_id | offset | +------------—+------------—+ where the lower 32 bits represent a module offset (relative to the module start not to the beginning of the code section) and the higher 32 bits uniquely identify the module in the WebAssembly VM. In other words, we assume that each WebAssembly module is loaded by the engine at a 64-bit address that starts at the boundary of 4GB pages, like 0x0000000400000000 for module_id == 4. These 64-bit addresses will be used to request code ranges for a specific module from the WebAssembly engine.
Reimplemented from lldb_private::ObjectFile.
Definition at line 733 of file ObjectFileWasm.cpp.
References DecodeSections(), lldb_private::ModuleChild::GetModule(), lldb_private::SectionList::GetSectionAtIndex(), lldb_private::ObjectFile::GetSectionList(), lldb_private::SectionList::GetSize(), LLDB_INVALID_ADDRESS, lldb_private::ObjectFile::m_memory_addr, and lldb_private::Target::SetSectionLoadAddress().
Terminate()
void ObjectFileWasm::Terminate () static
Definition at line 137 of file ObjectFileWasm.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Member Data Documentation
ID
char ObjectFileWasm::ID static
LLVM RTTI support.
Definition at line 59 of file ObjectFileWasm.h.
Referenced by classof(), and isA().
m_arch
ArchSpec lldb_private::wasm::ObjectFileWasm::m_arch private
Definition at line 154 of file ObjectFileWasm.h.
Referenced by GetAddressByteSize(), GetArchitecture(), GetByteOrder(), ObjectFileWasm(), and ObjectFileWasm().
m_num_imported_functions
uint32_t lldb_private::wasm::ObjectFileWasm::m_num_imported_functions = 0 private
Definition at line 152 of file ObjectFileWasm.h.
Referenced by CreateSections().
m_sect_infos
std::vector<section_info> lldb_private::wasm::ObjectFileWasm::m_sect_infos private
Definition at line 151 of file ObjectFileWasm.h.
Referenced by CreateSections(), DecodeNextSection(), DumpSectionHeaders(), GetExternalDebugInfoFileSpec(), GetSectionInfo(), and GetSectionInfo().
m_symbols
std::vector<Symbol> lldb_private::wasm::ObjectFileWasm::m_symbols private
Definition at line 153 of file ObjectFileWasm.h.
Referenced by CreateSections(), and ParseSymtab().
m_uuid
UUID lldb_private::wasm::ObjectFileWasm::m_uuid private
Definition at line 155 of file ObjectFileWasm.h.
Referenced by GetUUID().
The documentation for this class was generated from the following files:
ObjectFileWasm.h
ObjectFileWasm.cpp