LLDB: lldb_private::DataExtractor Class Reference
lldb_private::DataExtractor Class Reference
An data extractor class.
#include "lldb/Core/DataExtractor.h"
Public Types
enum Type {
TypeUInt8 , TypeChar , TypeUInt16 , TypeUInt32 ,
TypeUInt64 , TypePointer , TypeULEB128 , TypeSLEB128
}
Type enumerations used in the dump routines.
Public Member Functions
DataExtractor ()
Default constructor.
DataExtractor (const void *data, lldb::offset_t data_length, lldb::ByteOrder byte_order, uint32_t addr_size)
Construct with a buffer that is owned by the caller.
DataExtractor (const lldb::DataBufferSP &data_sp, lldb::ByteOrder byte_order, uint32_t addr_size)
Construct with shared data.
DataExtractor (const lldb::DataBufferSP &data_sp)
Construct with shared data, but byte-order & addr-size are unspecified.
DataExtractor (const DataExtractor &data, lldb::offset_t offset, lldb::offset_t length)
Construct with a subset of data.
DataExtractor (const DataExtractor &rhs)
Copy constructor.
const DataExtractor & operator= (const DataExtractor &rhs)
Assignment operator.
DataExtractor (DataExtractor &&rhs)=default
Move constructor and move assignment operators to complete the rule of 5.
DataExtractor & operator= (DataExtractor &&rhs)=default
virtual ~DataExtractor ()
Destructor.
void Clear ()
Clears the object state.
lldb::offset_t PutToLog (Log *log, lldb::offset_t offset, lldb::offset_t length, uint64_t base_addr, uint32_t num_per_line, Type type) const
Dumps the binary data as type objects to stream s (or to Log() if s is nullptr) starting offset bytes into the data and stopping after dumping length bytes.
size_t ExtractBytes (lldb::offset_t offset, lldb::offset_t length, lldb::ByteOrder dst_byte_order, void *dst) const
Extract an arbitrary number of bytes in the specified byte order.
uint64_t GetAddress (lldb::offset_t *offset_ptr) const
Extract an address from *offset_ptr.
uint64_t GetAddress_unchecked (lldb::offset_t *offset_ptr) const
uint32_t GetAddressByteSize () const
Get the current address size.
virtual uint64_t GetByteSize () const
Get the number of bytes contained in this object.
const char * GetCStr (lldb::offset_t *offset_ptr) const
Extract a C string from *offset_ptr.
const char * GetCStr (lldb::offset_t *offset_ptr, lldb::offset_t len) const
Extract a C string from *offset_ptr with field size len.
virtual const void * GetData (lldb::offset_t *offset_ptr, lldb::offset_t length) const
Extract length bytes from *offset_ptr.
lldb::offset_t CopyData (lldb::offset_t offset, lldb::offset_t length, void *dst) const
Copy length bytes from *offset, without swapping bytes.
lldb::offset_t CopyByteOrderedData (lldb::offset_t src_offset, lldb::offset_t src_len, void *dst, lldb::offset_t dst_len, lldb::ByteOrder dst_byte_order) const
Copy dst_len bytes from *offset_ptr and ensure the copied data is treated as a value that can be swapped to match the specified byte order.
const uint8_t * GetDataEnd () const
Get the data end pointer.
size_t GetSharedDataOffset () const
Get the shared data offset.
const uint8_t * GetDataStart () const
Get the data start pointer.
float GetFloat (lldb::offset_t *offset_ptr) const
Extract a float from *offset_ptr.
double GetDouble (lldb::offset_t *offset_ptr) const
long double GetLongDouble (lldb::offset_t *offset_ptr) const
uint32_t GetMaxU32 (lldb::offset_t *offset_ptr, size_t byte_size) const
Extract an integer of size byte_size from *offset_ptr.
uint64_t GetMaxU64 (lldb::offset_t *offset_ptr, size_t byte_size) const
Extract an unsigned integer of size byte_size from *offset_ptr.
uint64_t GetMaxU64_unchecked (lldb::offset_t *offset_ptr, size_t byte_size) const
int64_t GetMaxS64 (lldb::offset_t *offset_ptr, size_t byte_size) const
Extract an signed integer of size byte_size from *offset_ptr.
uint64_t GetMaxU64Bitfield (lldb::offset_t *offset_ptr, size_t size, uint32_t bitfield_bit_size, uint32_t bitfield_bit_offset) const
Extract an unsigned integer of size byte_size from *offset_ptr, then extract the bitfield from this value if bitfield_bit_size is non-zero.
int64_t GetMaxS64Bitfield (lldb::offset_t *offset_ptr, size_t size, uint32_t bitfield_bit_size, uint32_t bitfield_bit_offset) const
Extract an signed integer of size size from *offset_ptr, then extract and sign-extend the bitfield from this value if bitfield_bit_size is non-zero.
lldb::ByteOrder GetByteOrder () const
Get the current byte order value.
uint8_t GetU8 (lldb::offset_t *offset_ptr) const
Extract a uint8_t value from *offset_ptr.
virtual uint8_t GetU8_unchecked (lldb::offset_t *offset_ptr) const
virtual uint16_t GetU16_unchecked (lldb::offset_t *offset_ptr) const
virtual uint32_t GetU32_unchecked (lldb::offset_t *offset_ptr) const
virtual uint64_t GetU64_unchecked (lldb::offset_t *offset_ptr) const
void * GetU8 (lldb::offset_t *offset_ptr, void *dst, uint32_t count) const
Extract count uint8_t values from *offset_ptr.
uint16_t GetU16 (lldb::offset_t *offset_ptr) const
Extract a uint16_t value from *offset_ptr.
void * GetU16 (lldb::offset_t *offset_ptr, void *dst, uint32_t count) const
Extract count uint16_t values from *offset_ptr.
uint32_t GetU32 (lldb::offset_t *offset_ptr) const
Extract a uint32_t value from *offset_ptr.
void * GetU32 (lldb::offset_t *offset_ptr, void *dst, uint32_t count) const
Extract count uint32_t values from *offset_ptr.
uint64_t GetU64 (lldb::offset_t *offset_ptr) const
Extract a uint64_t value from *offset_ptr.
void * GetU64 (lldb::offset_t *offset_ptr, void *dst, uint32_t count) const
Extract count uint64_t values from *offset_ptr.
int64_t GetSLEB128 (lldb::offset_t *offset_ptr) const
Extract a signed LEB128 value from *offset_ptr.
uint64_t GetULEB128 (lldb::offset_t *offset_ptr) const
Extract a unsigned LEB128 value from *offset_ptr.
virtual lldb::DataExtractorSP GetSubsetExtractorSP (lldb::offset_t offset, lldb::offset_t length)
Return a new DataExtractor which represents a subset of an existing data extractor's bytes, copying all other fields from the existing data extractor.
virtual lldb::DataExtractorSP GetSubsetExtractorSP (lldb::offset_t offset)
Return a new DataExtractor which represents a subset of an existing data extractor's bytes, copying all other fields from the existing data extractor.
virtual lldb::DataExtractorSP GetContiguousDataExtractorSP ()
Return a new DataExtractor which represents a subset of an existing data extractor's bytes, copying all other fields from the existing data extractor.
lldb::DataBufferSP GetSharedDataBuffer () const
bool HasData ()
const char * PeekCStr (lldb::offset_t offset) const
Peek at a C string at offset.
virtual const uint8_t * PeekData (lldb::offset_t offset, lldb::offset_t length) const
Peek at a bytes at offset.
void SetAddressByteSize (uint32_t addr_size)
Set the address byte size.
virtual lldb::offset_t SetData (const void *bytes, lldb::offset_t length, lldb::ByteOrder byte_order)
Set data with a buffer that is caller owned.
virtual lldb::offset_t SetData (const DataExtractor &data, lldb::offset_t offset, lldb::offset_t length)
Adopt a subset of data.
virtual lldb::offset_t SetData (const lldb::DataBufferSP &data_sp, lldb::offset_t offset=0, lldb::offset_t length=LLDB_INVALID_OFFSET)
Adopt a subset of shared data in data_sp.
void SetByteOrder (lldb::ByteOrder byte_order)
Set the byte_order value.
uint32_t Skip_LEB128 (lldb::offset_t *offset_ptr) const
Skip an LEB128 number at *offset_ptr.
bool ValidOffset (lldb::offset_t offset) const
Test the validity of offset.
bool ValidOffsetForDataOfSize (lldb::offset_t offset, lldb::offset_t length) const
Test the availability of length bytes of data from offset.
size_t Copy (DataExtractor &dest_data) const
bool Append (DataExtractor &rhs)
bool Append (void *bytes, lldb::offset_t length)
virtual lldb::offset_t BytesLeft (lldb::offset_t offset) const
void Checksum (llvm::SmallVectorImpl< uint8_t > &dest, uint64_t max_data=0)
virtual llvm::ArrayRef< uint8_t > GetData () const
llvm::DWARFDataExtractor GetAsLLVMDWARF () const
llvm::DataExtractor GetAsLLVM () const
Protected Member Functions
template<typename T>
T Get (lldb::offset_t *offset_ptr, T fail_value) const
Protected Attributes
const uint8_t * m_start = nullptr
A pointer to the first byte of data.
const uint8_t * m_end
A pointer to the byte that is past the end of the data.
lldb::ByteOrder m_byte_order
The byte order of the data we are extracting from.
uint32_t m_addr_size
The address size to use when extracting addresses.
lldb::DataBufferSP m_data_sp
The shared pointer to data that can be shared among multiple instances.
Detailed Description
An data extractor class.
DataExtractor is a class that can extract data (swapping if needed) from a data buffer. The data buffer can be caller owned, or can be shared data that can be shared between multiple DataExtractor instances. Multiple DataExtractor objects can share the same data, yet extract values in different address sizes and byte order modes. Each object can have a unique position in the shared data and extract data from different offsets.
See also
DataBuffer
Definition at line 50 of file DataExtractor.h.
Member Enumeration Documentation
Type
enum lldb_private::DataExtractor::Type
Type enumerations used in the dump routines.
Enumerator
TypeUInt8
Format output as unsigned 8 bit integers.
TypeChar
Format output as characters.
TypeUInt16
Format output as unsigned 16 bit integers.
TypeUInt32
Format output as unsigned 32 bit integers.
TypeUInt64
Format output as unsigned 64 bit integers.
TypePointer
Format output as pointers.
TypeULEB128
Format output as ULEB128 numbers.
TypeSLEB128
Format output as SLEB128 numbers.
Definition at line 54 of file DataExtractor.h.
Constructor & Destructor Documentation
DataExtractor() [1/7]
DataExtractor::DataExtractor ()
Default constructor.
Initialize all members to a default empty state.
Definition at line 123 of file DataExtractor.cpp.
References m_addr_size, m_byte_order, and m_data_sp.
Referenced by Append(), Copy(), DataExtractor(), DataExtractor(), DataExtractor(), lldb_private::DWARFDataExtractor::DWARFDataExtractor(), operator=(), operator=(), SetData(), lldb_private::VirtualDataExtractor::SetData(), lldb_private::VirtualDataExtractor::VirtualDataExtractor(), lldb_private::VirtualDataExtractor::VirtualDataExtractor(), and lldb_private::VirtualDataExtractor::VirtualDataExtractor().
DataExtractor() [2/7]
DataExtractor::DataExtractor (const void * data, lldb::offset_t data_length, lldb::ByteOrder byte_order, uint32_t addr_size)
Construct with a buffer that is owned by the caller.
This constructor allows us to use data that is owned by the caller. The data must stay around as long as this object is valid.
Parameters
[in] data A pointer to caller owned data.
[in] data_length The length in bytes of data.
[in] byte_order A byte order of the data that we are extracting from.
[in] addr_size A new address byte size value.
Definition at line 129 of file DataExtractor.cpp.
References m_addr_size, m_byte_order, m_data_sp, m_end, and m_start.
DataExtractor() [3/7]
DataExtractor::DataExtractor (const lldb::DataBufferSP & data_sp, lldb::ByteOrder byte_order, uint32_t addr_size)
Construct with shared data.
Copies the data shared pointer which adds a reference to the data contained in data_sp. The shared data reference is reference counted to ensure the data lives as long as anyone still has a valid shared pointer to the data in data_sp.
Parameters
[in] data_sp A shared pointer to data.
[in] byte_order A byte order of the data that we are extracting from.
[in] addr_size A new address byte size value.
Definition at line 141 of file DataExtractor.cpp.
References m_addr_size, m_byte_order, m_data_sp, and SetData().
DataExtractor() [4/7]
DataExtractor::DataExtractor (const lldb::DataBufferSP & data_sp) explicit
Construct with shared data, but byte-order & addr-size are unspecified.
Copies the data shared pointer which adds a reference to the data contained in data_sp. The shared data reference is reference counted to ensure the data lives as long as anyone still has a valid shared pointer to the data in data_sp.
Parameters
[in] data_sp A shared pointer to data.
Definition at line 149 of file DataExtractor.cpp.
References m_addr_size, m_byte_order, m_data_sp, and SetData().
DataExtractor() [5/7]
DataExtractor::DataExtractor (const DataExtractor & data, lldb::offset_t offset, lldb::offset_t length)
Construct with a subset of data.
Initialize this object with a subset of the data bytes in data. If data contains shared data, then a reference to the shared data will be added to ensure the shared data stays around as long as any objects have references to the shared data. The byte order value and the address size settings are copied from data. If offset is not a valid offset in data, then no reference to the shared data will be added. If there are not length bytes available in data starting at offset, the length will be truncated to contain as many bytes as possible.
Parameters
[in] data Another DataExtractor object that contains data.
[in] offset The offset into data at which the subset starts.
[in] length The length in bytes of the subset of data.
Definition at line 161 of file DataExtractor.cpp.
References DataExtractor(), GetByteSize(), m_addr_size, m_byte_order, m_data_sp, SetData(), and ValidOffset().
DataExtractor() [6/7]
DataExtractor::DataExtractor (const DataExtractor & rhs) explicit
Copy constructor.
The copy constructor is explicit as otherwise it is easy to make unintended modification of a local copy instead of a caller's instance. Also a needless copy of the m_data_sp shared pointer is/ expensive.
Definition at line 174 of file DataExtractor.cpp.
References DataExtractor(), m_addr_size, m_byte_order, m_data_sp, m_end, and m_start.
DataExtractor() [7/7]
lldb_private::DataExtractor::DataExtractor (DataExtractor && rhs) default
Move constructor and move assignment operators to complete the rule of 5.
They would get deleted as we already defined those of rule of 3.
References DataExtractor().
~DataExtractor()
DataExtractor::~DataExtractor () virtual default
Destructor.
If this object contains a valid shared data reference, the reference count on the data will be decremented, and if zero, the data will be freed.
Member Function Documentation
Append() [1/2]
bool DataExtractor::Append (DataExtractor & rhs)
Definition at line 974 of file DataExtractor.cpp.
References Copy(), DataExtractor(), GetByteOrder(), lldb_private::WritableDataBuffer::GetBytes(), GetByteSize(), GetDataStart(), and SetData().
Append() [2/2]
bool DataExtractor::Append (void * bytes, lldb::offset_t length)
Definition at line 1002 of file DataExtractor.cpp.
References lldb_private::WritableDataBuffer::GetBytes(), GetByteSize(), GetDataStart(), and SetData().
BytesLeft()
virtual lldb::offset_t lldb_private::DataExtractor::BytesLeft (lldb::offset_t offset) const inline virtual
Reimplemented in lldb_private::VirtualDataExtractor.
Definition at line 1018 of file DataExtractor.h.
References GetByteSize().
Referenced by InstructionLLVMC::Decode(), Evaluate_DW_OP_entry_value(), and ValidOffsetForDataOfSize().
Checksum()
void DataExtractor::Checksum (llvm::SmallVectorImpl< uint8_t > & dest, uint64_t max_data = 0)
Definition at line 1029 of file DataExtractor.cpp.
References GetByteSize(), and GetDataStart().
Clear()
void DataExtractor::Clear ()
Clears the object state.
Clears the object contents back to a default invalid state, and release any references to shared data that this object may contain.
Definition at line 196 of file DataExtractor.cpp.
References lldb_private::endian::InlHostByteOrder(), m_addr_size, m_byte_order, m_data_sp, m_end, and m_start.
Referenced by CommunicationKDP::CheckForPacket(), lldb_private::Opcode::GetData(), lldb_private::Scalar::GetData(), lldb_private::Scalar::GetData(), lldb_private::Value::GetValueAsData(), lldb_private::plugin::dwarf::SymbolFileDWARF::LoadSectionData(), lldb_private::ObjectFileJIT::ReadSectionData(), ObjectFileELF::ReadSectionData(), CommunicationKDP::SendRequestAndGetReply(), and CommunicationKDP::WaitForPacketWithTimeoutMicroSecondsNoLock().
Copy()
size_t DataExtractor::Copy (DataExtractor & dest_data) const
Definition at line 962 of file DataExtractor.cpp.
References DataExtractor(), GetByteSize(), m_data_sp, m_start, and SetData().
Referenced by Append().
CopyByteOrderedData()
lldb::offset_t DataExtractor::CopyByteOrderedData (lldb::offset_t src_offset, lldb::offset_t src_len, void * dst, lldb::offset_t dst_len, lldb::ByteOrder dst_byte_order) const
Copy dst_len bytes from *offset_ptr and ensure the copied data is treated as a value that can be swapped to match the specified byte order.
For values that are larger than the supported integer sizes, this function can be used to extract data in a specified byte order. It can also be used to copy a smaller integer value from to a larger value. The extra bytes left over will be padded correctly according to the byte order of this object and the dst_byte_order. This can be very handy when say copying a partial data value into a register.
Parameters
[in] src_offset The offset into this data from which to start copying an endian entity
[in] src_len The length of the endian data to copy from this object into the dst object
[out] dst The buffer where to place the endian data. The data might need to be byte swapped (and appropriately padded with zeroes if src_len != dst_len) if dst_byte_order does not match the byte order in this object.
[in] dst_len The length number of bytes that the endian value will occupy is dst.
[in] dst_byte_order The byte order that the endian value should be in the dst buffer.
Returns
Returns the number of bytes that were copied, or zero if anything goes wrong.
Definition at line 690 of file DataExtractor.cpp.
References lldb::eByteOrderBig, lldb::eByteOrderLittle, m_byte_order, PeekData(), and ValidOffsetForDataOfSize().
Referenced by lldb_private::RegisterValue::GetAsMemoryData(), lldb_private::Scalar::GetAsMemoryData(), GetLongDouble(), ABISysV_mips64::GetReturnValueObjectImpl(), ABISysV_mips::GetReturnValueObjectImpl(), ABISysV_ppc::GetReturnValueObjectImpl(), ABISysV_x86_64::GetReturnValueObjectImpl(), ABIWindows_x86_64::GetReturnValueObjectImpl(), lldb_private::process_gdb_remote::GDBRemoteRegisterContext::PrivateSetRegisterValue(), lldb_private::ValueObject::SetData(), ABISysV_ppc64::SetReturnValueObject(), ABISysV_ppc::SetReturnValueObject(), ABISysV_s390x::SetReturnValueObject(), ABISysV_x86_64::SetReturnValueObject(), ABIWindows_x86_64::SetReturnValueObject(), lldb_private::ValueObject::SetValueFromCString(), lldb_private::RegisterValue::SetValueFromData(), and lldb_private::process_gdb_remote::GDBRemoteRegisterContext::WriteRegisterBytes().
CopyData()
lldb::offset_t DataExtractor::CopyData (lldb::offset_t offset, lldb::offset_t length, void * dst) const
Copy length bytes from *offset, without swapping bytes.
Parameters
[in] offset The offset into this data from which to start copying
[in] length The length of the data to copy from this object
[out] dst The buffer to place the output data.
Returns
Returns the number of bytes that were copied, or zero if anything goes wrong.
Definition at line 678 of file DataExtractor.cpp.
References PeekData().
Referenced by ParseFileset(), and ObjectFileELF::ReadSectionData().
ExtractBytes()
size_t DataExtractor::ExtractBytes (lldb::offset_t offset, lldb::offset_t length, lldb::ByteOrder dst_byte_order, void * dst) const
Extract an arbitrary number of bytes in the specified byte order.
Attemps to extract length bytes starting at offset bytes into this data in the requested byte order (dst_byte_order) and place the results in dst. dst must be at least length bytes long.
Parameters
[in] offset The offset in bytes into the contained data at which to start extracting.
[in] length The number of bytes to extract.
[in] dst_byte_order A byte order of the data that we want when the value in copied to dst.
[out] dst The buffer that will receive the extracted value if there are enough bytes available in the current data.
Returns
The number of bytes that were extracted which will be length when the value is successfully extracted, or zero if there aren't enough bytes at the specified offset.
Definition at line 663 of file DataExtractor.cpp.
References GetByteOrder(), and PeekData().
Referenced by ObjectFileMachO::GetAllArchSpecs(), ELFLinuxPrPsInfo::Parse(), ELFNote::Parse(), RegisterContextCorePOSIX_x86::RegisterContextCorePOSIX_x86(), RegisterContextDarwin_arm64_Mach::SetRegisterDataFrom_LC_THREAD(), RegisterContextDarwin_arm_Mach::SetRegisterDataFrom_LC_THREAD(), and lldb_private::RegisterValue::SetValueFromData().
Get()
template<typename T> T lldb_private::DataExtractor::Get (lldb::offset_t * offset_ptr, T fail_value) const inline protected
Definition at line 1043 of file DataExtractor.h.
References GetData(), lldb_private::endian::InlHostByteOrder(), and m_byte_order.
Referenced by GetDouble(), and GetFloat().
GetAddress()
uint64_t DataExtractor::GetAddress (lldb::offset_t * offset_ptr) const
Extract an address from *offset_ptr.
Extract a single address from the data and update the offset pointed to by offset_ptr. The size of the extracted address comes from the m_addr_size member variable and should be set correctly prior to extracting any address values.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
The extracted address value.
Definition at line 653 of file DataExtractor.cpp.
References GetMaxU64(), and m_addr_size.
Referenced by DerefSizeExtractDataHelper(), CommunicationKDP::DumpPacket(), EntityResultVariable::DumpToLog(), EntityVariableBase::DumpToLog(), lldb_private::DWARFExpression::Evaluate(), SystemRuntimeMacOSX::ExtractItemInfoFromBuffer(), lldb_private::AppleObjCRuntime::GetBacktraceThreadFromException(), GetGNUEHPointer(), SystemRuntimeMacOSX::GetPendingItemRefsForQueue(), lldb_private::DynamicLoaderDarwin::GetThreadLocalData(), GetVTableAddress(), EntityVariableBase::Materialize(), ELFLinuxPrPsInfo::Parse(), ELFLinuxPrStatus::Parse(), AuxVector::ParseAuxv(), SystemRuntimeMacOSX::PopulateQueuesUsingLibBTR(), PutToLog(), DynamicLoaderMacOSXDYLD::ReadAllImageInfosStructure(), DynamicLoaderMacOSXDYLD::ReadImageInfos(), ReadJITEntry(), ObjectFileELF::RefineModuleDetailsFromNote(), lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::RefreshTrampolines(), lldb_private::ValueObjectDynamicValue::SetData(), lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::SetUpRegion(), and lldb_private::AppleObjCRuntimeV1::UpdateISAToDescriptorMapIfNeeded().
GetAddress_unchecked()
uint64_t DataExtractor::GetAddress_unchecked (lldb::offset_t * offset_ptr) const
Definition at line 658 of file DataExtractor.cpp.
References GetMaxU64_unchecked(), and m_addr_size.
Referenced by ParseNList(), lldb_private::ClassDescriptorV2::class_ro_t::Read(), lldb_private::ClassDescriptorV2::class_rw_t::Read(), lldb_private::ClassDescriptorV2::ivar_t::Read(), lldb_private::ClassDescriptorV2::method_t::Read(), and lldb_private::ClassDescriptorV2::objc_class_t::Read().
GetAddressByteSize()
uint32_t lldb_private::DataExtractor::GetAddressByteSize () const inline
Get the current address size.
Return the size in bytes of any address values this object will extract.
Returns
The size in bytes of address values that will be extracted.
Definition at line 265 of file DataExtractor.h.
References m_addr_size.
Referenced by lldb_private::DWARFExpressionList::DumpLocations(), lldb_private::DWARFExpression::Evaluate(), GetAsLLVM(), lldb_private::DWARFDataExtractor::GetAsLLVM(), GetAsLLVMDWARF(), lldb_private::DWARFDataExtractor::GetAsLLVMDWARF(), lldb_private::DWARFExpressionList::GetDescription(), GetGNUEHPointer(), lldb_private::ValueObject::GetLocationAsCStringImpl(), lldb_private::plugin::dwarf::DWARFUnit::GetLocationTable(), GetOpcodeDataSize(), GetSubsetExtractorSP(), lldb_private::VirtualDataExtractor::GetSubsetExtractorSP(), lldb_private::VirtualDataExtractor::GetSubsetExtractorSP(), GetVTableAddress(), elf::ELFDynamic::Parse(), elf::ELFProgramHeader::Parse(), elf::ELFRel::Parse(), elf::ELFRela::Parse(), elf::ELFSectionHeader::Parse(), elf::ELFSymbol::Parse(), ELFLinuxPrPsInfo::Parse(), AuxVector::ParseAuxv(), lldb_private::plugin::dwarf::DWARFUnit::ParseDWARFLocationList(), DynamicLoaderMacOSXDYLD::ReadMachHeader(), ObjectFileELF::RefineModuleDetailsFromNote(), and lldb_private::ValueObject::ValueObject().
GetAsLLVM()
llvm::DataExtractor lldb_private::DataExtractor::GetAsLLVM () const inline
Definition at line 1037 of file DataExtractor.h.
References lldb::eByteOrderLittle, GetAddressByteSize(), GetByteOrder(), and GetData().
Referenced by lldb_private::wasm::ObjectFileWasm::DecodeNextSection(), lldb_private::ForEachFormatterInModule(), lldb_private::wasm::ObjectFileWasm::GetExternalDebugInfoFileSpec(), ParseImports(), and ParseNames().
GetAsLLVMDWARF()
llvm::DWARFDataExtractor lldb_private::DataExtractor::GetAsLLVMDWARF () const inline
Definition at line 1031 of file DataExtractor.h.
References lldb::eByteOrderLittle, GetAddressByteSize(), GetByteOrder(), and GetData().
GetByteOrder()
lldb::ByteOrder lldb_private::DataExtractor::GetByteOrder () const inline
Get the current byte order value.
Returns
The current byte order value from this object's internal state.
Definition at line 596 of file DataExtractor.h.
References m_byte_order.
Referenced by Append(), InstructionLLVMC::CalculateMnemonicOperandsAndComment(), InstructionLLVMC::Decode(), EntityRegister::Dematerialize(), lldb_private::DumpDataExtractor(), ExtractBytes(), ObjectFileMachO::GetAllArchSpecs(), GetAPInt(), GetAsLLVM(), lldb_private::DWARFDataExtractor::GetAsLLVM(), GetAsLLVMDWARF(), lldb_private::DWARFDataExtractor::GetAsLLVMDWARF(), lldb_private::Value::GetData(), lldb_private::plugin::dwarf::DWARFUnit::GetLocationTable(), GetSubsetExtractorSP(), lldb_private::VirtualDataExtractor::GetSubsetExtractorSP(), lldb_private::VirtualDataExtractor::GetSubsetExtractorSP(), ELFLinuxPrPsInfo::Parse(), ELFNote::Parse(), lldb_private::plugin::dwarf::DWARFUnit::ParseDWARFLocationList(), DynamicLoaderMacOSXDYLD::ReadMachHeader(), RegisterContextCorePOSIX_arm::RegisterContextCorePOSIX_arm(), RegisterContextCorePOSIX_arm64::RegisterContextCorePOSIX_arm64(), RegisterContextCorePOSIX_loongarch64::RegisterContextCorePOSIX_loongarch64(), RegisterContextCorePOSIX_powerpc::RegisterContextCorePOSIX_powerpc(), RegisterContextCorePOSIX_ppc64le::RegisterContextCorePOSIX_ppc64le(), RegisterContextCorePOSIX_riscv32::RegisterContextCorePOSIX_riscv32(), RegisterContextCorePOSIX_riscv64::RegisterContextCorePOSIX_riscv64(), RegisterContextCorePOSIX_s390x::RegisterContextCorePOSIX_s390x(), SetData(), ABISysV_ppc64::SetReturnValueObject(), ABISysV_ppc::SetReturnValueObject(), ABISysV_s390x::SetReturnValueObject(), ABISysV_x86_64::SetReturnValueObject(), ABIWindows_x86_64::SetReturnValueObject(), lldb_private::RegisterValue::SetValueFromData(), lldb_private::Scalar::SetValueFromData(), and lldb_private::ValueObject::ValueObject().
GetByteSize()
virtual uint64_t lldb_private::DataExtractor::GetByteSize () const inline virtual
Get the number of bytes contained in this object.
Returns
The total number of bytes of data this object refers to.
Reimplemented in lldb_private::VirtualDataExtractor.
Definition at line 271 of file DataExtractor.h.
References m_end, and m_start.
Referenced by Append(), Append(), BytesLeft(), calc_crc32(), InstructionLLVMC::CalculateMnemonicOperandsAndComment(), Checksum(), Copy(), lldb_private::plugin::dwarf::AppleDWARFIndex::Create(), RegisterContextCorePOSIX_arm64::Create(), RegisterContextCorePOSIX_riscv64::Create(), DataExtractor(), lldb_private::plugin::dwarf::SymbolFileDWARF::DebugAbbrev(), DisassemblerLLVMC::DecodeInstructions(), EntityRegister::Dematerialize(), EntityVariableBase::Dematerialize(), lldb_private::IRExecutionUnit::DisassembleFunction(), CommandObjectProcessKDPPacketSend::DoExecute(), lldb_private::DumpDataExtractor(), CommunicationKDP::DumpPacket(), lldb_private::DWARFExpression::Evaluate(), EmulateInstructionMIPS64::EvaluateInstruction(), EmulateInstructionMIPS::EvaluateInstruction(), lldb_private::TypeFormatImpl_EnumType::FormatObject(), lldb_private::DWARFDataExtractor::GetAsLLVM(), lldb_private::DWARFDataExtractor::GetAsLLVMDWARF(), lldb_private::Scalar::GetAsMemoryData(), GetData(), lldb_private::ValueObject::GetData(), lldb_private::plugin::dwarf::DWARFDebugInfoEntry::GetDIENamesAndRanges(), ObjectFileELF::GetDynamicData(), lldb_private::DWARFExpression::GetExpressionData(), GetExprListFromAtLocation(), ObjectFileELF::GetModuleSpecifications(), ABISysV_mips64::GetReturnValueObjectImpl(), ABISysV_ppc::GetReturnValueObjectImpl(), ABISysV_x86_64::GetReturnValueObjectImpl(), ABIWindows_x86_64::GetReturnValueObjectImpl(), ObjectFileELF::GetSegmentData(), EmulateInstructionMIPS::GetSizeOfInstruction(), GetSubsetExtractorSP(), ObjectFileELF::GetUUID(), lldb_private::ClangExpressionDeclMap::GetVariableValue(), lldb_private::plugin::dwarf::SymbolFileDWARF::InitializeObject(), EntityVariableBase::Materialize(), ELFLinuxPrPsInfo::Parse(), ELFLinuxPrStatus::Parse(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseDebugMacros(), ProcessElfCore::parseFreeBSDNotes(), ParseFreeBSDPrStatus(), lldb_private::ObjectContainerMachOFileset::ParseHeader(), ProcessElfCore::parseLinuxNotes(), ProcessElfCore::parseNetBSDNotes(), ProcessElfCore::parseOpenBSDNotes(), ObjectFileELF::ParseSymbolTable(), lldb_private::Type::ReadFromMemory(), lldb_private::ValueObject::ReadPointedString(), lldb_private::ObjectFile::ReadSectionData(), lldb_private::ObjectFileJIT::ReadSectionData(), RegisterContextCorePOSIX_arm::RegisterContextCorePOSIX_arm(), RegisterContextCorePOSIX_arm64::RegisterContextCorePOSIX_arm64(), RegisterContextCorePOSIX_loongarch64::RegisterContextCorePOSIX_loongarch64(), RegisterContextCorePOSIX_powerpc::RegisterContextCorePOSIX_powerpc(), RegisterContextCorePOSIX_ppc64le::RegisterContextCorePOSIX_ppc64le(), RegisterContextCorePOSIX_riscv32::RegisterContextCorePOSIX_riscv32(), RegisterContextCorePOSIX_riscv64::RegisterContextCorePOSIX_riscv64(), RegisterContextCorePOSIX_s390x::RegisterContextCorePOSIX_s390x(), lldb_private::Value::ResolveValue(), CommunicationKDP::SendRequestReadMemory(), CommunicationKDP::SendRequestReadRegisters(), SetData(), SetData(), SetData(), RegisterContextDarwin_arm64_Mach::SetRegisterDataFrom_LC_THREAD(), RegisterContextDarwin_arm_Mach::SetRegisterDataFrom_LC_THREAD(), RegisterContextDarwin_riscv32_Mach::SetRegisterDataFrom_LC_THREAD(), RegisterContextDarwin_x86_64_Mach::SetRegisterDataFrom_LC_THREAD(), lldb_private::RegisterValue::SetValueFromData(), lldb_private::Scalar::SetValueFromData(), ValidOffset(), InstructionLLVMC::VisitInstruction(), CommunicationKDP::WaitForPacketWithTimeoutMicroSecondsNoLock(), lldb_private::Watchpoint::WatchedValueReportable(), lldb_private::process_gdb_remote::GDBRemoteRegisterContext::WriteAllRegisterValues(), and lldb_private::process_gdb_remote::GDBRemoteRegisterContext::WriteRegister().
GetContiguousDataExtractorSP()
virtual lldb::DataExtractorSP lldb_private::DataExtractor::GetContiguousDataExtractorSP () inline virtual
Return a new DataExtractor which represents a subset of an existing data extractor's bytes, copying all other fields from the existing data extractor.
The length will be the largest contiguous region that can be provided starting the beginning of this extractor; it is safe to read any bytes within the returned subset Extractor.
Returns
A shared pointer to a new DataExtractor.
Definition at line 844 of file DataExtractor.h.
References GetSubsetExtractorSP().
GetCStr() [1/2]
const char * DataExtractor::GetCStr (lldb::offset_t * offset_ptr) const
Extract a C string from *offset_ptr.
Returns a pointer to a C String from the data at the offset pointed to by offset_ptr. A variable length NULL terminated C string will be extracted and the offset_ptr will be updated with the offset of the byte that follows the NULL terminator byte.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
A pointer to the C string value in the data. If the offset pointed to by offset_ptr is out of bounds, or if the offset plus the length of the C string is out of bounds, nullptr will be returned.
Definition at line 784 of file DataExtractor.cpp.
References m_end, and PeekData().
Referenced by lldb_private::DumpDataExtractor(), CommunicationKDP::DumpPacket(), SystemRuntimeMacOSX::ExtractItemInfoFromBuffer(), lldb_private::plugin::dwarf::DWARFFormValue::ExtractValue(), FindSubSectionOffsetByName(), FindSubSubSectionOffsetByTag(), GetAttributeValueByTag(), GetDebugLinkContents(), GetFreeBSDProcessArgs(), GetMacOSXProcessArgs(), GetNetBSDProcessArgs(), GetOpenBSDProcessArgs(), ObjectFileELF::GetSectionHeaderInfo(), ELFNote::Parse(), ObjectFileELF::ParseARMAttributes(), ParseFileset(), ParseTrieEntries(), SystemRuntimeMacOSX::PopulateQueuesUsingLibBTR(), lldb_private::plugin::dwarf::DWARFDebugMacroEntry::ReadMacroEntries(), ObjectFileELF::RefineModuleDetailsFromNote(), and lldb_private::plugin::dwarf::DWARFFormValue::SkipValue().
GetCStr() [2/2]
const char * DataExtractor::GetCStr (lldb::offset_t * offset_ptr, lldb::offset_t len) const
Extract a C string from *offset_ptr with field size len.
Returns a pointer to a C String from the data at the offset pointed to by offset_ptr, with a field length of len. A NULL terminated C string will be extracted and the offset_ptr will be updated with the offset of the byte that follows the fixed length field.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
A pointer to the C string value in the data. If the offset pointed to by offset_ptr is out of bounds, or if the offset plus the length of the field is out of bounds, or if the field does not contain a NULL terminator byte, nullptr will be returned.
Definition at line 814 of file DataExtractor.cpp.
References PeekData().
GetData() [1/2]
virtual llvm::ArrayRef< uint8_t > lldb_private::DataExtractor::GetData () const inline virtual
Reimplemented in lldb_private::VirtualDataExtractor.
Definition at line 1027 of file DataExtractor.h.
References GetByteSize(), and GetDataStart().
Referenced by Get(), GetAsLLVM(), GetAsLLVMDWARF(), GetMaxU64(), GetU16(), GetU16(), GetU32(), GetU32(), GetU64(), GetU64(), GetU8(), and GetU8().
GetData() [2/2]
virtual const void * lldb_private::DataExtractor::GetData (lldb::offset_t * offset_ptr, lldb::offset_t length) const inline virtual
Extract length bytes from *offset_ptr.
Returns a pointer to a bytes in this object's data at the offset pointed to by offset_ptr. If length is zero or too large, then the offset pointed to by offset_ptr will not be updated and nullptr will be returned.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
[in] length The optional length of a string to extract. If the value is zero, a NULL terminated C string will be extracted.
Returns
A pointer to the bytes in this object's data if the offset and length are valid, or nullptr otherwise.
Reimplemented in lldb_private::VirtualDataExtractor.
Definition at line 338 of file DataExtractor.h.
References PeekData().
Referenced by lldb_private::CacheSignature::Decode(), lldb_private::plugin::dwarf::NameToDIE::Decode(), lldb_private::StringTableReader::Decode(), lldb_private::Symtab::Decode(), DecodeCStrMap(), lldb_private::plugin::dwarf::DecodeIndexSet(), EntityRegister::Dematerialize(), lldb_private::DumpDataExtractor(), CommunicationKDP::DumpPacket(), lldb_private::DWARFExpression::Evaluate(), Evaluate_DW_OP_entry_value(), GetAttributes(), ObjectFileELF::GetGnuDebugDataObjectFile(), lldb_private::ObjectFile::GetLoadableData(), lldb_private::plugin::dwarf::DWARFUnit::GetLocationTable(), lldb_private::breakpad::SymbolFileBreakpad::LineIterator::LineIterator(), lldb_private::breakpad::SymbolFileBreakpad::LineIterator::operator++(), DynamicLoaderMacOSXDYLD::ParseLoadCommands(), DynamicLoaderDarwinKernel::ReadKextSummaries(), lldb_private::minidump::RegisterContextMinidump_ARM64::RegisterContextMinidump_ARM64(), CommunicationKDP::SendRequestReadMemory(), CommunicationKDP::SendRequestReadRegisters(), lldb_private::platform_android::AdbSyncService::StatImpl(), and TypedRead().
GetDataEnd()
const uint8_t * lldb_private::DataExtractor::GetDataEnd () const inline
Get the data end pointer.
Returns
Returns a pointer to the next byte contained in this object's data, or nullptr of there is no data in this object.
Definition at line 408 of file DataExtractor.h.
References m_end.
GetDataStart()
const uint8_t * lldb_private::DataExtractor::GetDataStart () const inline
Get the data start pointer.
Returns
Returns a pointer to the first byte contained in this object's data, or nullptr of there is no data in this object.
Definition at line 424 of file DataExtractor.h.
References m_start.
Referenced by Append(), Append(), calc_crc32(), InstructionLLVMC::CalculateMnemonicOperandsAndComment(), Checksum(), EntityRegister::Dematerialize(), EntityVariableBase::Dematerialize(), CommandObjectProcessKDPPacketSend::DoExecute(), EmulateInstructionMIPS64::EvaluateInstruction(), EmulateInstructionMIPS::EvaluateInstruction(), ExtractDataMemberLocation(), lldb_private::DWARFDataExtractor::GetAsLLVM(), lldb_private::DWARFDataExtractor::GetAsLLVMDWARF(), GetData(), lldb_private::plugin::dwarf::DWARFDebugInfoEntry::GetDIENamesAndRanges(), GetExprListFromAtConstValue(), GetExprListFromAtLocation(), EmulateInstructionMIPS::GetSizeOfInstruction(), lldb_private::ClangExpressionDeclMap::GetVariableValue(), EntityVariableBase::Materialize(), RegisterContextCorePOSIX_arm::RegisterContextCorePOSIX_arm(), RegisterContextCorePOSIX_arm64::RegisterContextCorePOSIX_arm64(), RegisterContextCorePOSIX_loongarch64::RegisterContextCorePOSIX_loongarch64(), RegisterContextCorePOSIX_powerpc::RegisterContextCorePOSIX_powerpc(), RegisterContextCorePOSIX_ppc64le::RegisterContextCorePOSIX_ppc64le(), RegisterContextCorePOSIX_riscv32::RegisterContextCorePOSIX_riscv32(), RegisterContextCorePOSIX_riscv64::RegisterContextCorePOSIX_riscv64(), RegisterContextCorePOSIX_s390x::RegisterContextCorePOSIX_s390x(), SetData(), lldb_private::ValueObject::SetData(), lldb_private::Scalar::SetValueFromData(), InstructionLLVMC::VisitInstruction(), and lldb_private::Watchpoint::WatchedValueReportable().
GetDouble()
double DataExtractor::GetDouble (lldb::offset_t * offset_ptr) const
Definition at line 630 of file DataExtractor.cpp.
References Get().
Referenced by lldb_private::DumpDataExtractor(), InterpreterStackFrame::EvaluateValue(), ABIMacOSX_arm64::GetReturnValueObjectImpl(), ABISysV_arm64::GetReturnValueObjectImpl(), ABISysV_mips64::GetReturnValueObjectImpl(), ABISysV_mips::GetReturnValueObjectImpl(), ABISysV_ppc::GetReturnValueObjectSimple(), ABISysV_s390x::GetReturnValueObjectSimple(), ABISysV_x86_64::GetReturnValueObjectSimple(), ABIWindows_x86_64::GetReturnValueObjectSimple(), RegisterContextDarwin_arm64::ReadRegister(), ABISysV_i386::SetReturnValueObject(), lldb_private::RegisterValue::SetValueFromData(), and lldb_private::Scalar::SetValueFromData().
GetFloat()
float DataExtractor::GetFloat (lldb::offset_t * offset_ptr) const
Extract a float from *offset_ptr.
Extract a single float value.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
The floating value that was extracted, or zero on failure.
Definition at line 626 of file DataExtractor.cpp.
References Get().
Referenced by lldb_private::DumpDataExtractor(), InterpreterStackFrame::EvaluateValue(), ABIMacOSX_arm64::GetReturnValueObjectImpl(), ABISysV_arm64::GetReturnValueObjectImpl(), ABISysV_mips64::GetReturnValueObjectImpl(), ABISysV_mips::GetReturnValueObjectImpl(), ABISysV_ppc::GetReturnValueObjectSimple(), ABISysV_s390x::GetReturnValueObjectSimple(), ABISysV_x86_64::GetReturnValueObjectSimple(), ABIWindows_x86_64::GetReturnValueObjectSimple(), GetWasmOffsetFromInitExpr(), RegisterContextDarwin_arm64::ReadRegister(), ABISysV_i386::SetReturnValueObject(), lldb_private::RegisterValue::SetValueFromData(), and lldb_private::Scalar::SetValueFromData().
GetLongDouble()
long double DataExtractor::GetLongDouble (lldb::offset_t * offset_ptr) const
Definition at line 634 of file DataExtractor.cpp.
References CopyByteOrderedData(), and lldb_private::endian::InlHostByteOrder().
Referenced by lldb_private::DumpDataExtractor(), ABIMacOSX_arm64::GetReturnValueObjectImpl(), ABISysV_arm64::GetReturnValueObjectImpl(), ABISysV_i386::GetReturnValueObjectSimple(), ABISysV_i386::SetReturnValueObject(), lldb_private::RegisterValue::SetValueFromData(), and lldb_private::Scalar::SetValueFromData().
GetMaxS64()
int64_t DataExtractor::GetMaxS64 (lldb::offset_t * offset_ptr, size_t byte_size) const
Extract an signed integer of size byte_size from *offset_ptr.
Extract a single signed integer value (sign extending if required) and update the offset pointed to by offset_ptr. The size of the extracted integer is specified by the byte_size argument. byte_size must have a value greater than or equal to one and less than or equal to eight since the return value is 64 bits wide.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
[in] byte_size The size in byte of the integer to extract.
Returns
The sign extended signed integer value that was extracted, or zero on failure.
Definition at line 572 of file DataExtractor.cpp.
References GetMaxU64().
Referenced by GetMaxS64(), GetMaxS64Bitfield(), and lldb_private::CompilerType::GetValueAsScalar().
GetMaxS64Bitfield()
int64_t DataExtractor::GetMaxS64Bitfield (lldb::offset_t * offset_ptr, size_t size, uint32_t bitfield_bit_size, uint32_t bitfield_bit_offset) const
Extract an signed integer of size size from *offset_ptr, then extract and sign-extend the bitfield from this value if bitfield_bit_size is non-zero.
Extract a single signed integer value (sign-extending if required) and update the offset pointed to by offset_ptr. The size of the extracted integer is specified by the size argument. size must have a value greater than or equal to one and less than or equal to eight since the return value is 64 bits wide.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
[in] size The size in bytes of the integer to extract.
[in] bitfield_bit_size The size in bits of the bitfield value to extract, or zero to just extract the entire integer value.
[in] bitfield_bit_offset The bit offset of the bitfield value in the extracted integer. For little-endian data, this is the offset of the LSB of the bitfield from the LSB of the integer. For big-endian data, this is the offset of the MSB of the bitfield from the MSB of the integer.
Returns
The signed bitfield integer value that was extracted, or zero on failure.
Definition at line 605 of file DataExtractor.cpp.
References lldb::eByteOrderBig, GetMaxS64(), and m_byte_order.
Referenced by lldb_private::DumpDataExtractor(), and DumpEnumValue().
GetMaxU32()
uint32_t DataExtractor::GetMaxU32 (lldb::offset_t * offset_ptr, size_t byte_size) const
Extract an integer of size byte_size from *offset_ptr.
Extract a single integer value and update the offset pointed to by offset_ptr. The size of the extracted integer is specified by the byte_size argument. byte_size must have a value >= 1 and <= 4 since the return value is only 32 bits wide.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
[in] byte_size The size in byte of the integer to extract.
Returns
The integer value that was extracted, or zero on failure.
Definition at line 522 of file DataExtractor.cpp.
References GetMaxU64(), and lldbassert.
Referenced by lldb_private::Process::ReadScalarIntegerFromMemory(), lldb_private::Target::ReadScalarIntegerFromMemory(), ABIMacOSX_arm::SetReturnValueObject(), ABIMacOSX_i386::SetReturnValueObject(), ABISysV_arm::SetReturnValueObject(), ABISysV_i386::SetReturnValueObject(), ABISysV_mips::SetReturnValueObject(), and lldb_private::RegisterValue::SetValueFromData().
GetMaxU64()
uint64_t DataExtractor::GetMaxU64 (lldb::offset_t * offset_ptr, size_t byte_size) const
Extract an unsigned integer of size byte_size from *offset_ptr.
Extract a single unsigned integer value and update the offset pointed to by offset_ptr. The size of the extracted integer is specified by the byte_size argument. byte_size must have a value greater than or equal to one and less than or equal to eight since the return value is 64 bits wide.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
[in] byte_size The size in byte of the integer to extract.
Returns
The unsigned integer value that was extracted, or zero on failure.
Definition at line 528 of file DataExtractor.cpp.
References GetData(), GetU16(), GetU32(), GetU64(), GetU8(), lldbassert, m_byte_order, and ReadMaxInt64().
Referenced by lldb_private::plugin::dwarf::DWARFFormValue::Address(), DerefSizeExtractDataHelper(), InterpreterStackFrame::EvaluateValue(), lldb_private::plugin::dwarf::DWARFFormValue::ExtractValue(), GetAddress(), GetAPInt(), GetMaxS64(), GetMaxU32(), GetMaxU64(), GetMaxU64Bitfield(), lldb_private::CompilerType::GetValueAsScalar(), ELFLinuxPrPsInfo::Parse(), lldb_private::EmulateInstruction::ReadMemoryUnsigned(), RegisterContextDarwin_arm64::ReadRegister(), lldb_private::Process::ReadScalarIntegerFromMemory(), lldb_private::Target::ReadScalarIntegerFromMemory(), ABIMacOSX_arm64::SetReturnValueObject(), ABIMacOSX_arm::SetReturnValueObject(), ABISysV_arc::SetReturnValueObject(), ABISysV_arm64::SetReturnValueObject(), ABISysV_loongarch::SetReturnValueObject(), ABISysV_mips64::SetReturnValueObject(), ABISysV_ppc64::SetReturnValueObject(), ABISysV_ppc::SetReturnValueObject(), ABISysV_riscv::SetReturnValueObject(), ABISysV_s390x::SetReturnValueObject(), ABISysV_x86_64::SetReturnValueObject(), ABIWindows_x86_64::SetReturnValueObject(), and lldb_private::RegisterValue::SetValueFromData().
GetMaxU64_unchecked()
uint64_t DataExtractor::GetMaxU64_unchecked (lldb::offset_t * offset_ptr, size_t byte_size) const
Definition at line 552 of file DataExtractor.cpp.
References GetU16_unchecked(), GetU32_unchecked(), GetU64_unchecked(), GetU8_unchecked(), m_byte_order, m_start, and ReadMaxInt64().
Referenced by GetAddress_unchecked().
GetMaxU64Bitfield()
uint64_t DataExtractor::GetMaxU64Bitfield (lldb::offset_t * offset_ptr, size_t size, uint32_t bitfield_bit_size, uint32_t bitfield_bit_offset) const
Extract an unsigned integer of size byte_size from *offset_ptr, then extract the bitfield from this value if bitfield_bit_size is non-zero.
Extract a single unsigned integer value and update the offset pointed to by offset_ptr. The size of the extracted integer is specified by the byte_size argument. byte_size must have a value greater than or equal to one and less than or equal to 8 since the return value is 64 bits wide.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
[in] size The size in byte of the integer to extract.
[in] bitfield_bit_size The size in bits of the bitfield value to extract, or zero to just extract the entire integer value.
[in] bitfield_bit_offset The bit offset of the bitfield value in the extracted integer. For little-endian data, this is the offset of the LSB of the bitfield from the LSB of the integer. For big-endian data, this is the offset of the MSB of the bitfield from the MSB of the integer.
Returns
The unsigned bitfield integer value that was extracted, or zero on failure.
Definition at line 577 of file DataExtractor.cpp.
References lldb::eByteOrderBig, GetMaxU64(), and m_byte_order.
Referenced by lldb_private::DumpDataExtractor(), and DumpEnumValue().
GetSharedDataBuffer()
lldb::DataBufferSP lldb_private::DataExtractor::GetSharedDataBuffer () const inline
Definition at line 848 of file DataExtractor.h.
References m_data_sp.
Referenced by ApplyELF32ABS32RelRelocation(), ApplyELF64ABS32Relocation(), ApplyELF64ABS64Relocation(), ObjectFileELF::ApplyRelocations(), lldb_private::plugin::dwarf::AppleDWARFIndex::Create(), GetSubsetExtractorSP(), lldb_private::VirtualDataExtractor::GetSubsetExtractorSP(), lldb_private::VirtualDataExtractor::GetSubsetExtractorSP(), and lldb_private::VirtualDataExtractor::SetData().
GetSharedDataOffset()
size_t DataExtractor::GetSharedDataOffset () const
Get the shared data offset.
Get the offset of the first byte of data in the shared data (if any).
Returns
If this object contains shared data, this function returns the offset in bytes into that shared data, zero otherwise.
Definition at line 206 of file DataExtractor.cpp.
References lldb_private::DataBuffer::GetBytes(), m_data_sp, and m_start.
Referenced by GetSubsetExtractorSP(), and SetData().
GetSLEB128()
int64_t DataExtractor::GetSLEB128 (lldb::offset_t * offset_ptr) const
Extract a signed LEB128 value from *offset_ptr.
Extracts an signed LEB128 number from this object's data starting at the offset pointed to by offset_ptr. The offset pointed to by offset_ptr will be updated with the offset of the byte following the last extracted byte.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
The extracted signed integer value.
Definition at line 859 of file DataExtractor.cpp.
References m_end, and PeekData().
Referenced by lldb_private::DWARFExpression::Evaluate(), lldb_private::plugin::dwarf::DWARFFormValue::ExtractValue(), GetGNUEHPointer(), GetWasmOffsetFromInitExpr(), lldb_private::DWARFExpression::MatchesOperand(), and PutToLog().
GetSubsetExtractorSP() [1/2]
DataExtractorSP DataExtractor::GetSubsetExtractorSP (lldb::offset_t offset) virtual
Return a new DataExtractor which represents a subset of an existing data extractor's bytes, copying all other fields from the existing data extractor.
The length will be the largest contiguous region that can be provided starting at offset; it is safe to read any bytes within the returned subset Extractor.
Parameters
[in] offset The starting byte offset into the shared data buffer.
Returns
A shared pointer to a new DataExtractor.
Reimplemented in lldb_private::VirtualDataExtractor.
Definition at line 1057 of file DataExtractor.cpp.
References GetByteSize(), and GetSubsetExtractorSP().
GetSubsetExtractorSP() [2/2]
DataExtractorSP DataExtractor::GetSubsetExtractorSP (lldb::offset_t offset, lldb::offset_t length) virtual
Return a new DataExtractor which represents a subset of an existing data extractor's bytes, copying all other fields from the existing data extractor.
Parameters
[in] offset The starting byte offset into the shared data buffer.
[in] length The length of bytes that the new extractor can operate on.
Returns
A shared pointer to a new DataExtractor.
Reimplemented in lldb_private::VirtualDataExtractor.
Definition at line 1048 of file DataExtractor.cpp.
References GetAddressByteSize(), GetByteOrder(), GetSharedDataBuffer(), and GetSharedDataOffset().
Referenced by GetContiguousDataExtractorSP(), and GetSubsetExtractorSP().
GetU16() [1/2]
uint16_t DataExtractor::GetU16 (lldb::offset_t * offset_ptr) const
Extract a uint16_t value from *offset_ptr.
Extract a single uint16_t from the binary data at the offset pointed to by offset_ptr, and update the offset on success.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
The extracted uint16_t value.
Definition at line 351 of file DataExtractor.cpp.
References GetData(), lldb_private::endian::InlHostByteOrder(), m_byte_order, ReadInt16(), and ReadSwapInt16().
Referenced by InstructionLLVMC::CalculateMnemonicOperandsAndComment(), CommunicationKDP::CheckForPacket(), InstructionLLVMC::Decode(), lldb_private::Symbol::Decode(), lldb_private::DumpDataExtractor(), CommunicationKDP::DumpPacket(), lldb_private::DWARFExpression::Evaluate(), lldb_private::plugin::dwarf::DWARFFormValue::ExtractValue(), GetGNUEHPointer(), GetMaxU64(), elf::ELFHeader::Parse(), elf::ELFSymbol::Parse(), ELFLinuxPrStatus::Parse(), ObjectFilePECOFF::ParseCOFFHeader(), ObjectFilePECOFF::ParseDOSHeader(), lldb_private::plugin::dwarf::DWARFDebugMacroHeader::ParseHeader(), PutToLog(), lldb_private::RegisterContextUnifiedCore::ReadRegister(), lldb_private::IRMemoryMap::ReadScalarFromMemory(), lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::SetUpRegion(), and lldb_private::plugin::dwarf::DWARFFormValue::SkipValue().
GetU16() [2/2]
void * DataExtractor::GetU16 (lldb::offset_t * offset_ptr, void * dst, uint32_t count) const
Extract count uint16_t values from *offset_ptr.
Extract count uint16_t values from the binary data at the offset pointed to by offset_ptr, and advance the offset on success. The extracted values are copied into dst.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
[out] dst A buffer to copy count uint16_t values into. dst must be large enough to hold all requested data.
[in] count The number of uint16_t values to extract.
Returns
dst if all values were properly extracted and copied, nullptr otherwise.
Definition at line 400 of file DataExtractor.cpp.
References GetData(), lldb_private::endian::InlHostByteOrder(), m_byte_order, and ReadSwapInt16().
GetU16_unchecked()
uint16_t DataExtractor::GetU16_unchecked (lldb::offset_t * offset_ptr) const virtual
Reimplemented in lldb_private::VirtualDataExtractor.
Definition at line 364 of file DataExtractor.cpp.
References lldb_private::endian::InlHostByteOrder(), m_byte_order, m_start, ReadInt16(), and ReadSwapInt16().
Referenced by GetMaxU64_unchecked(), lldb_private::VirtualDataExtractor::GetU16_unchecked(), and ParseNList().
GetU32() [1/2]
uint32_t DataExtractor::GetU32 (lldb::offset_t * offset_ptr) const
Extract a uint32_t value from *offset_ptr.
Extract a single uint32_t from the binary data at the offset pointed to by offset_ptr, and update the offset on success.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
The extracted uint32_t value.
Definition at line 429 of file DataExtractor.cpp.
References GetData(), lldb_private::endian::InlHostByteOrder(), m_byte_order, and ReadSwapInt32().
Referenced by InstructionLLVMC::CalculateMnemonicOperandsAndComment(), CommunicationKDP::CheckForPacket(), InstructionLLVMC::Decode(), lldb_private::CacheSignature::Decode(), lldb_private::Mangled::Decode(), lldb_private::plugin::dwarf::NameToDIE::Decode(), lldb_private::StringTableReader::Decode(), lldb_private::Symbol::Decode(), lldb_private::Symtab::Decode(), DecodeCStrMap(), lldb_private::plugin::dwarf::DecodeIndexSet(), CommandObjectProcessMinidumpDump::DoExecute(), DynamicLoaderMacOSXDYLD::DoInitialImageFetch(), lldb_private::DumpDataExtractor(), CommunicationKDP::DumpPacket(), lldb_private::DWARFExpression::Evaluate(), SystemRuntimeMacOSX::ExtractItemInfoFromBuffer(), lldb_private::plugin::dwarf::DWARFFormValue::ExtractValue(), FindMinimumVersionInfo(), FindSubSectionOffsetByName(), FindSubSubSectionOffsetByTag(), ObjectFileMachO::GetAllArchSpecs(), GetAttributeValueByTag(), GetDebugLinkContents(), GetGNUEHPointer(), GetMacOSXProcessArgs(), GetMaxU64(), ObjectFileELF::GetNumSymbolsFromDynamicGnuHash(), ObjectFileELF::GetNumSymbolsFromDynamicHash(), SystemRuntimeMacOSX::GetPendingItemRefsForQueue(), ObjectFileELF::GetSectionHeaderInfo(), ObjectFileMachO::GetUUID(), lldb_private::CompilerType::GetValueAsScalar(), lldb_private::plugin::dwarf::SymbolFileWasm::GetVendorDWARFOpcodeSize(), lldb_private::ObjectContainerMachOFileset::MagicBytesMatch(), ObjectContainerUniversalMachO::MagicBytesMatch(), elf::ELFHeader::Parse(), elf::ELFProgramHeader::Parse(), elf::ELFSectionHeader::Parse(), elf::ELFSymbol::Parse(), ELFLinuxPrPsInfo::Parse(), ELFLinuxPrStatus::Parse(), ELFNote::Parse(), ObjectFileELF::ParseARMAttributes(), ObjectFilePECOFF::ParseCOFFHeader(), ObjectFilePECOFF::ParseDOSHeader(), ParseFileset(), ParseFreeBSDPrPsInfo(), ParseFreeBSDPrStatus(), lldb_private::plugin::dwarf::DWARFDebugMacroHeader::ParseHeader(), ObjectContainerUniversalMachO::ParseHeader(), DynamicLoaderMacOSXDYLD::ParseLoadCommands(), ParseMachOHeader(), ParseNetBSDProcInfo(), ParseOpenBSDProcInfo(), lldb_private::plugin::dwarf::SymbolFileWasm::ParseVendorDWARFOpcode(), SystemRuntimeMacOSX::PopulateQueuesUsingLibBTR(), PutToLog(), DynamicLoaderMacOSXDYLD::ReadAllImageInfosStructure(), DynamicLoaderDarwinKernel::ReadKextSummaryHeader(), DynamicLoaderMacOSXDYLD::ReadMachHeader(), lldb_private::plugin::dwarf::DWARFDebugMacroEntry::ReadMacroEntries(), lldb_private::RegisterContextUnifiedCore::ReadRegister(), lldb_private::IRMemoryMap::ReadScalarFromMemory(), lldb_private::platform_android::AdbSyncService::ReadSyncHeader(), ObjectFileELF::RefineModuleDetailsFromNote(), lldb_private::minidump::RegisterContextMinidump_ARM::RegisterContextMinidump_ARM(), lldb_private::minidump::RegisterContextMinidump_ARM64::RegisterContextMinidump_ARM64(), DynamicLoaderDarwinKernel::SearchForKernelWithDebugHints(), CommunicationKDP::SendRawRequest(), CommunicationKDP::SendRequestBreakpoint(), CommunicationKDP::SendRequestHostInfo(), CommunicationKDP::SendRequestReadMemory(), CommunicationKDP::SendRequestReadRegisters(), CommunicationKDP::SendRequestReattach(), CommunicationKDP::SendRequestVersion(), CommunicationKDP::SendRequestWriteMemory(), CommunicationKDP::SendRequestWriteRegisters(), RegisterContextDarwin_arm64_Mach::SetRegisterDataFrom_LC_THREAD(), RegisterContextDarwin_arm_Mach::SetRegisterDataFrom_LC_THREAD(), RegisterContextDarwin_riscv32_Mach::SetRegisterDataFrom_LC_THREAD(), RegisterContextDarwin_x86_64_Mach::SetRegisterDataFrom_LC_THREAD(), ThreadKDP::SetStopInfoFrom_KDP_EXCEPTION(), lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::SetUpRegion(), lldb_private::plugin::dwarf::DWARFFormValue::SkipValue(), lldb_private::platform_android::AdbSyncService::StatImpl(), and lldb_private::AppleObjCRuntimeV1::UpdateISAToDescriptorMapIfNeeded().
GetU32() [2/2]
void * DataExtractor::GetU32 (lldb::offset_t * offset_ptr, void * dst, uint32_t count) const
Extract count uint32_t values from *offset_ptr.
Extract count uint32_t values from the binary data at the offset pointed to by offset_ptr, and advance the offset on success. The extracted values are copied into dst.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
[out] dst A buffer to copy count uint32_t values into. dst must be large enough to hold all requested data.
[in] count The number of uint32_t values to extract.
Returns
dst if all values were properly extracted and copied, nullptr otherwise.
Definition at line 449 of file DataExtractor.cpp.
References GetData(), lldb_private::endian::InlHostByteOrder(), m_byte_order, and ReadSwapInt32().
GetU32_unchecked()
uint32_t DataExtractor::GetU32_unchecked (lldb::offset_t * offset_ptr) const virtual
Reimplemented in lldb_private::VirtualDataExtractor.
Definition at line 374 of file DataExtractor.cpp.
References lldb_private::endian::InlHostByteOrder(), m_byte_order, m_start, ReadInt32(), and ReadSwapInt32().
Referenced by GetMaxU64_unchecked(), lldb_private::VirtualDataExtractor::GetU32_unchecked(), lldb_private::AppleObjCRuntimeV2::SharedCacheImageHeaders::GetVersion(), ParseNList(), lldb_private::ClassDescriptorV2::class_ro_t::Read(), lldb_private::ClassDescriptorV2::class_rw_t::Read(), lldb_private::ClassDescriptorV2::ivar_list_t::Read(), lldb_private::ClassDescriptorV2::ivar_t::Read(), lldb_private::ClassDescriptorV2::method_list_t::Read(), lldb_private::ClassDescriptorV2::method_t::Read(), and lldb_private::ClassDescriptorV2::relative_list_list_t::Read().
GetU64() [1/2]
uint64_t DataExtractor::GetU64 (lldb::offset_t * offset_ptr) const
Extract a uint64_t value from *offset_ptr.
Extract a single uint64_t from the binary data at the offset pointed to by offset_ptr, and update the offset on success.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
The extracted uint64_t value.
Definition at line 478 of file DataExtractor.cpp.
References GetData(), lldb_private::endian::InlHostByteOrder(), m_byte_order, and ReadSwapInt64().
Referenced by InstructionLLVMC::CalculateMnemonicOperandsAndComment(), InstructionLLVMC::Decode(), lldb_private::plugin::dwarf::DIERef::Decode(), lldb_private::Symbol::Decode(), CommunicationKDP::DumpPacket(), lldb_private::DWARFExpression::Evaluate(), SystemRuntimeMacOSX::ExtractItemInfoFromBuffer(), lldb_private::plugin::dwarf::DWARFFormValue::ExtractValue(), GetAPInt(), GetGNUEHPointer(), GetMaxU64(), ABISysV_mips64::GetReturnValueObjectImpl(), lldb_private::CompilerType::GetValueAsScalar(), lldb_private::wasm::ProcessWasm::GetWasmCallStack(), elf::ELFSymbol::Parse(), lldb_private::plugin::dwarf::DWARFDebugMacroHeader::ParseHeader(), ObjectContainerUniversalMachO::ParseHeader(), DynamicLoaderMacOSXDYLD::ParseLoadCommands(), SystemRuntimeMacOSX::PopulateQueuesUsingLibBTR(), PutToLog(), ReadJITEntry(), DynamicLoaderDarwinKernel::ReadKextSummaries(), lldb_private::plugin::dwarf::DWARFDebugMacroEntry::ReadMacroEntries(), lldb_private::RegisterContextUnifiedCore::ReadRegister(), lldb_private::IRMemoryMap::ReadScalarFromMemory(), ReadUIntMax64(), lldb_private::minidump::RegisterContextMinidump_ARM::RegisterContextMinidump_ARM(), lldb_private::minidump::RegisterContextMinidump_ARM64::RegisterContextMinidump_ARM64(), DynamicLoaderDarwinKernel::SearchForKernelWithDebugHints(), RegisterContextDarwin_arm64_Mach::SetRegisterDataFrom_LC_THREAD(), and RegisterContextDarwin_x86_64_Mach::SetRegisterDataFrom_LC_THREAD().
GetU64() [2/2]
void * DataExtractor::GetU64 (lldb::offset_t * offset_ptr, void * dst, uint32_t count) const
Extract count uint64_t values from *offset_ptr.
Extract count uint64_t values from the binary data at the offset pointed to by offset_ptr, and advance the offset on success. The extracted values are copied into dst.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
[out] dst A buffer to copy count uint64_t values into. dst must be large enough to hold all requested data.
[in] count The number of uint64_t values to extract.
Returns
dst if all values were properly extracted and copied, nullptr otherwise.
Definition at line 497 of file DataExtractor.cpp.
References GetData(), lldb_private::endian::InlHostByteOrder(), m_byte_order, and ReadSwapInt64().
GetU64_unchecked()
uint64_t DataExtractor::GetU64_unchecked (lldb::offset_t * offset_ptr) const virtual
Reimplemented in lldb_private::VirtualDataExtractor.
Definition at line 384 of file DataExtractor.cpp.
References lldb_private::endian::InlHostByteOrder(), m_byte_order, m_start, ReadInt64(), and ReadSwapInt64().
Referenced by GetMaxU64_unchecked(), lldb_private::VirtualDataExtractor::GetU64_unchecked(), and lldb_private::ClassDescriptorV2::relative_list_entry_t::Read().
GetU8() [1/2]
uint8_t DataExtractor::GetU8 (lldb::offset_t * offset_ptr) const
Extract a uint8_t value from *offset_ptr.
Extract a single uint8_t from the binary data at the offset pointed to by offset_ptr, and advance the offset on success.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
The extracted uint8_t value.
Definition at line 320 of file DataExtractor.cpp.
References GetData().
Referenced by InstructionLLVMC::CalculateMnemonicOperandsAndComment(), CommunicationKDP::CheckForPacket(), InstructionLLVMC::Decode(), lldb_private::CacheSignature::Decode(), lldb_private::Mangled::Decode(), lldb_private::Symbol::Decode(), lldb_private::Symtab::Decode(), lldb_private::plugin::dwarf::DecodeIndexSet(), lldb_private::DumpDataExtractor(), CommunicationKDP::DumpPacket(), lldb_private::DWARFExpression::Evaluate(), lldb_private::plugin::dwarf::DWARFFormValue::ExtractValue(), GetMaxU64(), GetOpcodeDataSize(), ObjectFileELF::GetSectionHeaderInfo(), lldb_private::plugin::dwarf::SymbolFileWasm::GetVendorDWARFOpcodeSize(), GetWasmOffsetFromInitExpr(), lldb_private::DWARFExpression::MatchesOperand(), elf::ELFHeader::Parse(), elf::ELFSymbol::Parse(), ELFLinuxPrPsInfo::Parse(), ObjectFileELF::ParseARMAttributes(), lldb_private::plugin::dwarf::DWARFDebugMacroHeader::ParseHeader(), ObjectFileELF::ParseRISCVAttributes(), ParseTrieEntries(), lldb_private::plugin::dwarf::SymbolFileWasm::ParseVendorDWARFOpcode(), PutToLog(), DynamicLoaderMacOSXDYLD::ReadAllImageInfosStructure(), lldb_private::plugin::dwarf::DWARFDebugMacroEntry::ReadMacroEntries(), lldb_private::IRMemoryMap::ReadScalarFromMemory(), CommunicationKDP::SendRequestAndGetReply(), ThreadKDP::SetStopInfoFrom_KDP_EXCEPTION(), lldb_private::plugin::dwarf::DWARFDebugMacroHeader::SkipOperandTable(), and lldb_private::plugin::dwarf::DWARFFormValue::SkipValue().
GetU8() [2/2]
void * DataExtractor::GetU8 (lldb::offset_t * offset_ptr, void * dst, uint32_t count) const
Extract count uint8_t values from *offset_ptr.
Extract count uint8_t values from the binary data at the offset pointed to by offset_ptr, and advance the offset on success. The extracted values are copied into dst.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
[out] dst A buffer to copy count uint8_t values into. dst must be large enough to hold all requested data.
[in] count The number of uint8_t values to extract.
Returns
dst if all values were properly extracted and copied, nullptr otherwise.
Definition at line 333 of file DataExtractor.cpp.
References GetData().
GetU8_unchecked()
virtual uint8_t lldb_private::DataExtractor::GetU8_unchecked (lldb::offset_t * offset_ptr) const inline virtual
Reimplemented in lldb_private::VirtualDataExtractor.
Definition at line 614 of file DataExtractor.h.
References m_start.
Referenced by GetMaxU64_unchecked(), lldb_private::VirtualDataExtractor::GetU8_unchecked(), and ParseNList().
GetULEB128()
uint64_t DataExtractor::GetULEB128 (lldb::offset_t * offset_ptr) const
Extract a unsigned LEB128 value from *offset_ptr.
Extracts an unsigned LEB128 number from this object's data starting at the offset pointed to by offset_ptr. The offset pointed to by offset_ptr will be updated with the offset of the byte following the last extracted byte.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
The extracted unsigned integer value.
Definition at line 842 of file DataExtractor.cpp.
References m_end, and PeekData().
Referenced by lldb_private::DWARFExpression::Evaluate(), Evaluate_DW_OP_entry_value(), lldb_private::plugin::dwarf::DWARFDebugInfoEntry::Extract(), lldb_private::plugin::dwarf::DWARFFormValue::ExtractValue(), FindSubSubSectionOffsetByTag(), GetAttributeValueByTag(), GetGNUEHPointer(), GetOpcodeDataSize(), lldb_private::plugin::dwarf::SymbolFileWasm::GetVendorDWARFOpcodeSize(), GetWasmOffsetFromInitExpr(), lldb_private::DWARFExpression::MatchesOperand(), ObjectFileELF::ParseARMAttributes(), ParseTrieEntries(), lldb_private::plugin::dwarf::SymbolFileWasm::ParseVendorDWARFOpcode(), PutToLog(), lldb_private::plugin::dwarf::DWARFDebugMacroEntry::ReadMacroEntries(), lldb_private::plugin::dwarf::DWARFDebugMacroHeader::SkipOperandTable(), and lldb_private::plugin::dwarf::DWARFFormValue::SkipValue().
HasData()
bool lldb_private::DataExtractor::HasData () inline
Definition at line 850 of file DataExtractor.h.
References m_end, and m_start.
operator=() [1/2]
const DataExtractor & DataExtractor::operator= (const DataExtractor & rhs)
Assignment operator.
Copies all data, byte order and address size settings from rhs into this object. If rhs contains shared data, a reference to that shared data will be added.
Parameters
[in] rhs Another DataExtractor object to copy.
Returns
A const reference to this object.
Definition at line 181 of file DataExtractor.cpp.
References DataExtractor(), m_addr_size, m_byte_order, m_data_sp, m_end, and m_start.
operator=() [2/2]
DataExtractor & lldb_private::DataExtractor::operator= (DataExtractor && rhs) default
References DataExtractor().
PeekCStr()
const char * DataExtractor::PeekCStr (lldb::offset_t offset) const
Peek at a C string at offset.
Peeks at a string in the contained data. No verification is done to make sure the entire string lies within the bounds of this object's data, only offset is verified to be a valid offset.
Parameters
[in] offset An offset into the data.
Returns
A non-nullptr C string pointer if offset is a valid offset, nullptr otherwise.
Definition at line 832 of file DataExtractor.cpp.
References PeekData().
Referenced by lldb_private::plugin::dwarf::DWARFFormValue::AsCString(), elf::ELFSymbol::Dump(), CommunicationKDP::DumpPacket(), ObjectFileELF::GetSectionHeaderInfo(), DynamicLoaderMacOSXDYLD::ParseLoadCommands(), ParsePLTRelocations(), ObjectFileELF::ParseSymbols(), lldb_private::ValueObject::ReadPointedString(), and CommunicationKDP::SendRequestKernelVersion().
PeekData()
virtual const uint8_t * lldb_private::DataExtractor::PeekData (lldb::offset_t offset, lldb::offset_t length) const inline virtual
Peek at a bytes at offset.
Returns a pointer to length bytes at offset as long as there are length bytes available starting at offset.
Returns
A non-nullptr data pointer if offset is a valid offset and there are length bytes available at that offset, nullptr otherwise.
Reimplemented in lldb_private::VirtualDataExtractor.
Definition at line 875 of file DataExtractor.h.
References m_start, and ValidOffsetForDataOfSize().
Referenced by InstructionLLVMC::CalculateMnemonicOperandsAndComment(), CopyByteOrderedData(), CopyData(), InstructionLLVMC::Decode(), ExtractBytes(), lldb_private::plugin::dwarf::DWARFFormValue::ExtractValue(), GetCStr(), GetCStr(), GetData(), lldb_private::VirtualDataExtractor::GetData(), GetFreeBSDProcessArgs(), GetMacOSXProcessArgs(), GetNetBSDProcessArgs(), GetOpenBSDProcessArgs(), GetSLEB128(), GetULEB128(), ObjectFileMachO::GetUUID(), lldb_private::Value::GetValueAsData(), ObjectContainerBSDArchive::MagicBytesMatch(), PeekCStr(), lldb_private::VirtualDataExtractor::PeekData(), lldb_private::Type::ReadFromMemory(), lldb_private::ValueObject::ReadPointedString(), ObjectFileELF::RefineModuleDetailsFromNote(), Skip_LEB128(), and lldb_private::process_gdb_remote::GDBRemoteRegisterContext::WriteAllRegisterValues().
PutToLog()
lldb::offset_t DataExtractor::PutToLog (Log * log, lldb::offset_t offset, lldb::offset_t length, uint64_t base_addr, uint32_t num_per_line, DataExtractor::Type type) const
Dumps the binary data as type objects to stream s (or to Log() if s is nullptr) starting offset bytes into the data and stopping after dumping length bytes.
The offset into the data is displayed at the beginning of each line and can be offset by base address base_addr. num_per_line objects will be displayed on each line.
Parameters
[in] log The log to dump the output to.
[in] offset The offset into the data at which to start dumping.
[in] length The number of bytes to dump.
[in] base_addr The base address that gets added to the offset displayed on each line.
[in] num_per_line The number of type objects to display on each line.
[in] type The type of objects to use when dumping data from this object. See DataExtractor::Type.
Returns
The offset at which dumping ended.
Definition at line 902 of file DataExtractor.cpp.
References lldb_private::StreamString::Clear(), lldb_private::StreamString::Empty(), GetAddress(), lldb_private::StreamString::GetSize(), GetSLEB128(), lldb_private::StreamString::GetString(), GetU16(), GetU32(), GetU64(), GetU8(), GetULEB128(), LLDB_INVALID_ADDRESS, lldb_private::Stream::Printf(), lldb_private::Log::PutString(), TypeChar, TypePointer, TypeSLEB128, TypeUInt16, TypeUInt32, TypeUInt64, TypeUInt8, TypeULEB128, and ValidOffset().
Referenced by lldb_private::IRExecutionUnit::DisassembleFunction(), lldb_private::IRExecutionUnit::GetRunnableInfo(), and lldb_private::IRExecutionUnit::WriteNow().
SetAddressByteSize()
void lldb_private::DataExtractor::SetAddressByteSize (uint32_t addr_size) inline
Set the address byte size.
Set the size in bytes that will be used when extracting any address and pointer values from data contained in this object.
Parameters
[in] addr_size The size in bytes to use when extracting addresses.
Definition at line 889 of file DataExtractor.h.
References m_addr_size.
Referenced by lldb_private::ValueObject::CreateConstantValue(), lldb_private::AppleObjCRuntime::GetBacktraceThreadFromException(), lldb_private::ValueObject::GetData(), ABISysV_arm::GetReturnValueObjectImpl(), lldb_private::Value::GetValueAsData(), LoadValueFromConsecutiveGPRRegisters(), LoadValueFromConsecutiveGPRRegisters(), elf::ELFHeader::Parse(), ObjectContainerUniversalMachO::ParseHeader(), ParseMachOHeader(), DynamicLoaderMacOSXDYLD::ReadMachHeader(), lldb_private::ObjectFile::ReadSectionData(), and lldb_private::ObjectFileJIT::ReadSectionData().
SetByteOrder()
void lldb_private::DataExtractor::SetByteOrder (lldb::ByteOrder byte_order) inline
Set the byte_order value.
Sets the byte order of the data to extract. Extracted values will be swapped if necessary when decoding.
Parameters
[in] byte_order The byte order value to use when extracting data.
Definition at line 973 of file DataExtractor.h.
References m_byte_order.
Referenced by lldb_private::ValueObject::CreateConstantValue(), lldb_private::Opcode::GetData(), lldb_private::Scalar::GetData(), lldb_private::Scalar::GetData(), lldb_private::ValueObject::GetData(), ABISysV_arm::GetReturnValueObjectImpl(), lldb_private::Value::GetValueAsData(), LoadValueFromConsecutiveGPRRegisters(), LoadValueFromConsecutiveGPRRegisters(), elf::ELFHeader::Parse(), ObjectContainerUniversalMachO::ParseHeader(), ParseMachOHeader(), DynamicLoaderMacOSXDYLD::ReadAllImageInfosStructure(), lldb_private::wasm::ObjectFileWasm::ReadImageData(), DynamicLoaderMacOSXDYLD::ReadMachHeader(), lldb_private::ObjectFile::ReadSectionData(), lldb_private::ObjectFileJIT::ReadSectionData(), lldb_private::ArchitectureAArch64::ReconfigureRegisterInfo(), and lldb_private::ValueObject::SetValueFromCString().
SetData() [1/3]
lldb::offset_t DataExtractor::SetData (const DataExtractor & data, lldb::offset_t offset, lldb::offset_t length) virtual
Adopt a subset of data.
Set this object's data to be a subset of the data bytes in data. If data contains shared data, then a reference to the shared data will be added to ensure the shared data stays around as long as any objects have references to the shared data. The byte order and the address size settings are copied from data. If offset is not a valid offset in data, then no reference to the shared data will be added. If there are not length bytes available in data starting at offset, the length will be truncated to contains as many bytes as possible.
Parameters
[in] data Another DataExtractor object that contains data.
[in] offset The offset into data at which the subset starts.
[in] length The length in bytes of the subset of data.
Returns
The number of bytes that this object now contains.
Reimplemented in lldb_private::VirtualDataExtractor.
Definition at line 251 of file DataExtractor.cpp.
References DataExtractor(), GetByteOrder(), GetByteSize(), GetDataStart(), GetSharedDataOffset(), m_addr_size, m_byte_order, m_data_sp, SetData(), and ValidOffset().
SetData() [2/3]
lldb::offset_t DataExtractor::SetData (const lldb::DataBufferSP & data_sp, lldb::offset_t offset = 0, lldb::offset_t length = LLDB_INVALID_OFFSET) virtual
Adopt a subset of shared data in data_sp.
Copies the data shared pointer which adds a reference to the contained in data_sp. The shared data reference is reference counted to ensure the data lives as long as anyone still has a valid shared pointer to the data in data_sp. The byte order and address byte size settings remain the same. If offset is not a valid offset in data_sp, then no reference to the shared data will be added. If there are not length bytes available in data starting at offset, the length will be truncated to contains as many bytes as possible.
Parameters
[in] data_sp A shared pointer to data.
[in] offset The offset into data_sp at which the subset starts.
[in] length The length in bytes of the subset of data_sp.
Returns
The number of bytes that this object now contains.
Reimplemented in lldb_private::VirtualDataExtractor.
Definition at line 284 of file DataExtractor.cpp.
References GetByteSize(), m_data_sp, m_end, and m_start.
SetData() [3/3]
lldb::offset_t DataExtractor::SetData (const void * bytes, lldb::offset_t length, lldb::ByteOrder byte_order) virtual
Set data with a buffer that is caller owned.
Use data that is owned by the caller when extracting values. The data must stay around as long as this object, or any object that copies a subset of this object's data, is valid. If bytes is nullptr, or length is zero, this object will contain no data.
Parameters
[in] bytes A pointer to caller owned data.
[in] length The length in bytes of bytes.
[in] byte_order A byte order of the data that we are extracting from.
Returns
The number of bytes that this object now contains.
Reimplemented in lldb_private::VirtualDataExtractor.
Definition at line 227 of file DataExtractor.cpp.
References GetByteSize(), m_byte_order, m_data_sp, m_end, and m_start.
Referenced by Append(), Append(), ObjectFileELF::CalculateELFNotesSegmentsCRC32(), CommunicationKDP::CheckForPacket(), Copy(), lldb_private::ObjectContainerMachOFileset::CreateInstance(), ObjectContainerBSDArchive::CreateInstance(), ObjectContainerUniversalMachO::CreateInstance(), ObjectFileELF::CreateMemoryInstance(), DataExtractor(), DataExtractor(), DataExtractor(), lldb_private::TypeFormatImpl_Format::FormatObject(), ObjectFileELF::GetArchitecture(), lldb_private::Opcode::GetData(), lldb_private::RegisterValue::GetData(), lldb_private::Scalar::GetData(), lldb_private::Scalar::GetData(), lldb_private::Value::GetData(), ObjectFileELF::GetModuleSpecifications(), lldb_private::ValueObject::GetPointeeData(), ObjectFileELF::GetProgramHeaderInfo(), ABISysV_arm::GetReturnValueObjectImpl(), ABISysV_mips64::GetReturnValueObjectImpl(), ObjectFileELF::GetSectionHeaderInfo(), lldb_private::Value::GetValueAsData(), LoadValueFromConsecutiveGPRRegisters(), LoadValueFromConsecutiveGPRRegisters(), lldb_private::ObjectContainerMachOFileset::MagicBytesMatch(), lldb_private::ObjectContainerMachOFileset::ParseHeader(), lldb_private::process_gdb_remote::GDBRemoteRegisterContext::PrivateSetRegisterValue(), lldb_private::Type::ReadFromMemory(), lldb_private::wasm::ObjectFileWasm::ReadImageData(), ObjectFilePECOFF::ReadImageData(), DynamicLoaderMacOSXDYLD::ReadMachHeader(), lldb_private::ObjectFile::ReadSectionData(), lldb_private::ObjectFileJIT::ReadSectionData(), ObjectFileELF::ReadSectionData(), lldb_private::ArchitectureAArch64::ReconfigureRegisterInfo(), SetData(), lldb_private::VirtualDataExtractor::SetData(), lldb_private::VirtualDataExtractor::SetData(), lldb_private::VirtualDataExtractor::SetData(), and lldb_private::AppleObjCRuntimeV1::UpdateISAToDescriptorMapIfNeeded().
Skip_LEB128()
uint32_t DataExtractor::Skip_LEB128 (lldb::offset_t * offset_ptr) const
Skip an LEB128 number at *offset_ptr.
Skips a LEB128 number (signed or unsigned) from this object's data starting at the offset pointed to by offset_ptr. The offset pointed to by offset_ptr will be updated with the offset of the byte following the last extracted byte.
Parameters
[in,out] offset_ptr A pointer to an offset within the data that will be advanced by the appropriate number of bytes if the value is extracted correctly. If the offset is out of bounds or there are not enough bytes to extract this value, the offset will be left unmodified.
Returns
The number of bytes consumed during the extraction.
Definition at line 876 of file DataExtractor.cpp.
References m_end, and PeekData().
Referenced by GetOpcodeDataSize(), and lldb_private::plugin::dwarf::DWARFFormValue::SkipValue().
ValidOffset()
bool lldb_private::DataExtractor::ValidOffset (lldb::offset_t offset) const inline
Test the validity of offset.
Returns
true if offset is a valid offset into the data in this object, false otherwise.
Definition at line 998 of file DataExtractor.h.
References GetByteSize().
Referenced by DataExtractor(), lldb_private::DumpDataExtractor(), lldb_private::DWARFExpression::Evaluate(), lldb_private::plugin::dwarf::DWARFUnit::extract(), lldb_private::plugin::dwarf::DWARFDebugInfoEntry::GetDIENamesAndRanges(), GetExprListFromAtLocation(), ParseTrieEntries(), lldb_private::plugin::dwarf::DWARFDebugInfo::ParseUnitsFor(), PutToLog(), DynamicLoaderMacOSXDYLD::ReadImageInfos(), and SetData().
ValidOffsetForDataOfSize()
bool lldb_private::DataExtractor::ValidOffsetForDataOfSize (lldb::offset_t offset, lldb::offset_t length) const inline
Test the availability of length bytes of data from offset.
Returns
true if offset is a valid offset and there are length bytes available at that offset, false otherwise.
Definition at line 1007 of file DataExtractor.h.
References BytesLeft().
Referenced by CopyByteOrderedData(), InstructionLLVMC::Decode(), lldb_private::Symbol::Decode(), lldb_private::Value::GetValueAsData(), AuxVector::ParseAuxv(), ObjectFilePECOFF::ParseCOFFHeader(), ObjectFilePECOFF::ParseDOSHeader(), ObjectContainerUniversalMachO::ParseHeader(), DynamicLoaderMacOSXDYLD::ParseLoadCommands(), ParseNList(), PeekData(), DynamicLoaderDarwinKernel::ReadKextSummaries(), and lldb_private::VirtualDataExtractor::ValidateVirtualRead().
Member Data Documentation
m_addr_size
uint32_t lldb_private::DataExtractor::m_addr_size protected
The address size to use when extracting addresses.
Definition at line 1064 of file DataExtractor.h.
Referenced by Clear(), DataExtractor(), DataExtractor(), DataExtractor(), DataExtractor(), DataExtractor(), DataExtractor(), GetAddress(), GetAddress_unchecked(), GetAddressByteSize(), operator=(), SetAddressByteSize(), and SetData().
m_byte_order
lldb::ByteOrder lldb_private::DataExtractor::m_byte_order protected
The byte order of the data we are extracting from.
Definition at line 1063 of file DataExtractor.h.
Referenced by Clear(), CopyByteOrderedData(), DataExtractor(), DataExtractor(), DataExtractor(), DataExtractor(), DataExtractor(), DataExtractor(), Get(), GetByteOrder(), GetMaxS64Bitfield(), GetMaxU64(), GetMaxU64_unchecked(), GetMaxU64Bitfield(), GetU16(), GetU16(), GetU16_unchecked(), GetU32(), GetU32(), GetU32_unchecked(), GetU64(), GetU64(), GetU64_unchecked(), operator=(), SetByteOrder(), SetData(), and SetData().
m_data_sp
lldb::DataBufferSP lldb_private::DataExtractor::m_data_sp protected
The shared pointer to data that can be shared among multiple instances.
Definition at line 1066 of file DataExtractor.h.
Referenced by Clear(), Copy(), DataExtractor(), DataExtractor(), DataExtractor(), DataExtractor(), DataExtractor(), DataExtractor(), GetSharedDataBuffer(), GetSharedDataOffset(), operator=(), SetData(), SetData(), SetData(), lldb_private::VirtualDataExtractor::SetData(), lldb_private::VirtualDataExtractor::SetData(), and lldb_private::VirtualDataExtractor::SetData().
m_end
const uint8_t* lldb_private::DataExtractor::m_end protected
Initial value:
=
      nullptr
A pointer to the byte that is past the end of the data.
Definition at line 1060 of file DataExtractor.h.
Referenced by Clear(), DataExtractor(), DataExtractor(), GetByteSize(), GetCStr(), GetDataEnd(), lldb_private::VirtualDataExtractor::GetPhysicalByteSize(), GetSLEB128(), GetULEB128(), HasData(), operator=(), lldb_private::VirtualDataExtractor::PhysicalBytesLeft(), SetData(), SetData(), and Skip_LEB128().
m_start
const uint8_t* lldb_private::DataExtractor::m_start = nullptr protected
A pointer to the first byte of data.
Definition at line 1059 of file DataExtractor.h.
Referenced by Clear(), Copy(), DataExtractor(), DataExtractor(), GetByteSize(), lldb_private::VirtualDataExtractor::GetData(), GetDataStart(), GetMaxU64_unchecked(), lldb_private::VirtualDataExtractor::GetPhysicalByteSize(), GetSharedDataOffset(), GetU16_unchecked(), GetU32_unchecked(), GetU64_unchecked(), GetU8_unchecked(), HasData(), operator=(), PeekData(), lldb_private::VirtualDataExtractor::PhysicalBytesLeft(), SetData(), SetData(), lldb_private::VirtualDataExtractor::SetData(), lldb_private::VirtualDataExtractor::SetData(), and lldb_private::VirtualDataExtractor::SetData().
The documentation for this class was generated from the following files:
DataExtractor.h
DataExtractor.cpp