LLDB: lldb_private::ProcessModID Class Reference
lldb_private::ProcessModID Class Reference
#include <Process.h>
Public Member Functions
ProcessModID ()=default
ProcessModID (const ProcessModID &rhs)
const ProcessModID & operator= (const ProcessModID &rhs)
~ProcessModID ()=default
uint32_t BumpStopID ()
void BumpMemoryID ()
void BumpResumeID ()
bool IsRunningUtilityFunction () const
uint32_t GetStopID () const
uint32_t GetLastNaturalStopID () const
uint32_t GetMemoryID () const
uint32_t GetResumeID () const
uint32_t GetLastUserExpressionResumeID () const
bool MemoryIDEqual (const ProcessModID &compare) const
bool StopIDEqual (const ProcessModID &compare) const
void SetInvalid ()
bool IsValid () const
bool IsLastResumeForUserExpression () const
bool IsRunningExpression () const
void SetRunningUserExpression (bool on)
void SetRunningUtilityFunction (bool on)
void SetStopEventForLastNaturalStopID (lldb::EventSP event_sp)
lldb::EventSP GetStopEventForStopID (uint32_t stop_id) const
void Dump (Stream &stream) const
Private Attributes
uint32_t m_stop_id = 0
uint32_t m_last_natural_stop_id = 0
uint32_t m_resume_id = 0
uint32_t m_memory_id = 0
uint32_t m_last_user_expression_resume = 0
uint32_t m_running_user_expression = false
uint32_t m_running_utility_function = 0
lldb::EventSP m_last_natural_stop_event
Friends
bool operator== (const ProcessModID &lhs, const ProcessModID &rhs)
Detailed Description
Definition at line 212 of file Process.h.
Constructor & Destructor Documentation
ProcessModID() [1/2]
lldb_private::ProcessModID::ProcessModID () default
Referenced by MemoryIDEqual(), operator=(), operator==, ProcessModID(), and StopIDEqual().
ProcessModID() [2/2]
lldb_private::ProcessModID::ProcessModID (const ProcessModID & rhs) inline
Definition at line 218 of file Process.h.
References m_memory_id, m_stop_id, and ProcessModID().
~ProcessModID()
lldb_private::ProcessModID::~ProcessModID () default
Member Function Documentation
BumpMemoryID()
void lldb_private::ProcessModID::BumpMemoryID () inline
Definition at line 238 of file Process.h.
References m_memory_id.
BumpResumeID()
void lldb_private::ProcessModID::BumpResumeID () inline
Definition at line 240 of file Process.h.
References m_last_user_expression_resume, m_resume_id, and m_running_user_expression.
BumpStopID()
uint32_t lldb_private::ProcessModID::BumpStopID () inline
Definition at line 231 of file Process.h.
References IsLastResumeForUserExpression(), m_last_natural_stop_id, and m_stop_id.
Dump()
void lldb_private::ProcessModID::Dump (Stream & stream) const inline
Definition at line 314 of file Process.h.
References lldb_private::Stream::Format(), m_last_natural_stop_id, m_last_user_expression_resume, m_memory_id, m_resume_id, m_running_user_expression, m_running_utility_function, and m_stop_id.
Referenced by CommandObjectProcessStatus::DoExecute().
GetLastNaturalStopID()
uint32_t lldb_private::ProcessModID::GetLastNaturalStopID () const inline
Definition at line 251 of file Process.h.
References m_last_natural_stop_id.
GetLastUserExpressionResumeID()
uint32_t lldb_private::ProcessModID::GetLastUserExpressionResumeID () const inline
Definition at line 254 of file Process.h.
References m_last_user_expression_resume.
GetMemoryID()
uint32_t lldb_private::ProcessModID::GetMemoryID () const inline
Definition at line 252 of file Process.h.
References m_memory_id.
GetResumeID()
uint32_t lldb_private::ProcessModID::GetResumeID () const inline
Definition at line 253 of file Process.h.
References m_resume_id.
GetStopEventForStopID()
lldb::EventSP lldb_private::ProcessModID::GetStopEventForStopID (uint32_t stop_id) const inline
Definition at line 308 of file Process.h.
References m_last_natural_stop_event, and m_last_natural_stop_id.
GetStopID()
uint32_t lldb_private::ProcessModID::GetStopID () const inline
Definition at line 250 of file Process.h.
References m_stop_id.
Referenced by lldb_private::ValueObject::EvaluationPoint::SyncWithProcessState().
IsLastResumeForUserExpression()
bool lldb_private::ProcessModID::IsLastResumeForUserExpression () const inline
Definition at line 270 of file Process.h.
References m_last_user_expression_resume, and m_resume_id.
Referenced by BumpStopID().
IsRunningExpression()
bool lldb_private::ProcessModID::IsRunningExpression () const inline
Definition at line 279 of file Process.h.
References m_running_user_expression, and m_running_utility_function.
Referenced by lldb_private::StopInfoBreakpoint::PerformAction().
IsRunningUtilityFunction()
bool lldb_private::ProcessModID::IsRunningUtilityFunction () const inline
Definition at line 246 of file Process.h.
References m_running_utility_function.
IsValid()
bool lldb_private::ProcessModID::IsValid () const inline
Definition at line 268 of file Process.h.
References m_stop_id, and UINT32_MAX.
MemoryIDEqual()
bool lldb_private::ProcessModID::MemoryIDEqual (const ProcessModID & compare) const inline
Definition at line 258 of file Process.h.
References lldb_private::compare(), m_memory_id, and ProcessModID().
Referenced by lldb_private::operator!=(), and operator==.
operator=()
const ProcessModID & lldb_private::ProcessModID::operator= (const ProcessModID & rhs) inline
Definition at line 221 of file Process.h.
References m_memory_id, m_stop_id, and ProcessModID().
SetInvalid()
void lldb_private::ProcessModID::SetInvalid () inline
Definition at line 266 of file Process.h.
References m_stop_id, and UINT32_MAX.
SetRunningUserExpression()
void lldb_private::ProcessModID::SetRunningUserExpression (bool on) inline
Definition at line 286 of file Process.h.
References m_running_user_expression.
SetRunningUtilityFunction()
void lldb_private::ProcessModID::SetRunningUtilityFunction (bool on) inline
Definition at line 293 of file Process.h.
References m_running_utility_function.
SetStopEventForLastNaturalStopID()
void lldb_private::ProcessModID::SetStopEventForLastNaturalStopID (lldb::EventSP event_sp) inline
Definition at line 304 of file Process.h.
References m_last_natural_stop_event.
StopIDEqual()
bool lldb_private::ProcessModID::StopIDEqual (const ProcessModID & compare) const inline
Definition at line 262 of file Process.h.
References lldb_private::compare(), m_stop_id, and ProcessModID().
Referenced by lldb_private::operator!=(), and operator==.
Friends And Related Symbol Documentation
operator==
bool operator== (const ProcessModID & lhs, const ProcessModID & rhs) friend
Definition at line 337 of file Process.h.
References MemoryIDEqual(), ProcessModID(), and StopIDEqual().
Member Data Documentation
m_last_natural_stop_event
lldb::EventSP lldb_private::ProcessModID::m_last_natural_stop_event private
Definition at line 334 of file Process.h.
Referenced by GetStopEventForStopID(), and SetStopEventForLastNaturalStopID().
m_last_natural_stop_id
uint32_t lldb_private::ProcessModID::m_last_natural_stop_id = 0 private
Definition at line 328 of file Process.h.
Referenced by BumpStopID(), Dump(), GetLastNaturalStopID(), and GetStopEventForStopID().
m_last_user_expression_resume
uint32_t lldb_private::ProcessModID::m_last_user_expression_resume = 0 private
Definition at line 331 of file Process.h.
Referenced by BumpResumeID(), Dump(), GetLastUserExpressionResumeID(), and IsLastResumeForUserExpression().
m_memory_id
uint32_t lldb_private::ProcessModID::m_memory_id = 0 private
Definition at line 330 of file Process.h.
Referenced by BumpMemoryID(), Dump(), GetMemoryID(), MemoryIDEqual(), operator=(), and ProcessModID().
m_resume_id
uint32_t lldb_private::ProcessModID::m_resume_id = 0 private
Definition at line 329 of file Process.h.
Referenced by BumpResumeID(), Dump(), GetResumeID(), and IsLastResumeForUserExpression().
m_running_user_expression
uint32_t lldb_private::ProcessModID::m_running_user_expression = false private
Definition at line 332 of file Process.h.
Referenced by BumpResumeID(), Dump(), IsRunningExpression(), and SetRunningUserExpression().
m_running_utility_function
uint32_t lldb_private::ProcessModID::m_running_utility_function = 0 private
Definition at line 333 of file Process.h.
Referenced by Dump(), IsRunningExpression(), IsRunningUtilityFunction(), and SetRunningUtilityFunction().
m_stop_id
uint32_t lldb_private::ProcessModID::m_stop_id = 0 private
Definition at line 327 of file Process.h.
Referenced by BumpStopID(), Dump(), GetStopID(), IsValid(), operator=(), ProcessModID(), SetInvalid(), and StopIDEqual().
The documentation for this class was generated from the following file:
Process.h