LLDB: lldb::SBTypeNameSpecifier Class Reference
lldb::SBTypeNameSpecifier Class Reference
#include <SBTypeNameSpecifier.h>
Public Member Functions
SBTypeNameSpecifier ()
SBTypeNameSpecifier (const char *name, bool is_regex=false)
SBTypeNameSpecifier (const char *name, lldb::FormatterMatchType match_type)
SBTypeNameSpecifier (SBType type)
SBTypeNameSpecifier (const lldb::SBTypeNameSpecifier &rhs)
~SBTypeNameSpecifier ()
operator bool () const
bool IsValid () const
const char * GetName ()
SBType GetType ()
lldb::FormatterMatchType GetMatchType ()
bool IsRegex ()
bool GetDescription (lldb::SBStream &description, lldb::DescriptionLevel description_level)
lldb::SBTypeNameSpecifier & operator= (const lldb::SBTypeNameSpecifier &rhs)
bool IsEqualTo (lldb::SBTypeNameSpecifier &rhs)
bool operator== (lldb::SBTypeNameSpecifier &rhs)
bool operator!= (lldb::SBTypeNameSpecifier &rhs)
Protected Member Functions
lldb::TypeNameSpecifierImplSP GetSP ()
void SetSP (const lldb::TypeNameSpecifierImplSP &type_namespec_sp)
SBTypeNameSpecifier (const lldb::TypeNameSpecifierImplSP &)
Protected Attributes
lldb::TypeNameSpecifierImplSP m_opaque_sp
Friends
class SBDebugger
class SBTypeCategory
Detailed Description
Definition at line 17 of file SBTypeNameSpecifier.h.
Constructor & Destructor Documentation
SBTypeNameSpecifier() [1/6]
SBTypeNameSpecifier::SBTypeNameSpecifier ()
Definition at line 20 of file SBTypeNameSpecifier.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by SBTypeNameSpecifier().
SBTypeNameSpecifier() [2/6]
SBTypeNameSpecifier::SBTypeNameSpecifier (const char * name, bool is_regex = false)
Definition at line 22 of file SBTypeNameSpecifier.cpp.
References lldb::eFormatterMatchExact, lldb::eFormatterMatchRegex, LLDB_INSTRUMENT_VA, and SBTypeNameSpecifier().
SBTypeNameSpecifier() [3/6]
SBTypeNameSpecifier::SBTypeNameSpecifier (const char * name, lldb::FormatterMatchType match_type)
Definition at line 28 of file SBTypeNameSpecifier.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
SBTypeNameSpecifier() [4/6]
SBTypeNameSpecifier::SBTypeNameSpecifier (SBType type)
Definition at line 37 of file SBTypeNameSpecifier.cpp.
References lldb::SBType::IsValid(), LLDB_INSTRUMENT_VA, lldb::SBType::m_opaque_sp, and m_opaque_sp.
SBTypeNameSpecifier() [5/6]
SBTypeNameSpecifier::SBTypeNameSpecifier (const lldb::SBTypeNameSpecifier & rhs)
Definition at line 45 of file SBTypeNameSpecifier.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
~SBTypeNameSpecifier()
SBTypeNameSpecifier::~SBTypeNameSpecifier () default
References GetDescription(), GetMatchType(), GetType(), IsEqualTo(), IsRegex(), IsValid(), operator!=(), operator=(), and operator==().
SBTypeNameSpecifier() [6/6]
SBTypeNameSpecifier::SBTypeNameSpecifier (const lldb::TypeNameSpecifierImplSP & type_namespec_sp) protected
Definition at line 162 of file SBTypeNameSpecifier.cpp.
References m_opaque_sp.
Member Function Documentation
GetDescription()
bool SBTypeNameSpecifier::GetDescription (lldb::SBStream & description, lldb::DescriptionLevel description_level)
Definition at line 98 of file SBTypeNameSpecifier.cpp.
References lldb::eFormatterMatchExact, lldb::eFormatterMatchRegex, GetMatchType(), GetName(), IsValid(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTypeNameSpecifier().
GetMatchType()
FormatterMatchType SBTypeNameSpecifier::GetMatchType ()
Definition at line 82 of file SBTypeNameSpecifier.cpp.
References lldb::eFormatterMatchExact, IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by GetDescription(), IsEqualTo(), and ~SBTypeNameSpecifier().
GetName()
const char * SBTypeNameSpecifier::GetName ()
Definition at line 62 of file SBTypeNameSpecifier.cpp.
References lldb_private::ConstString::GetCString(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by lldb::SBTypeCategory::AddTypeSummary(), lldb::SBTypeCategory::AddTypeSynthetic(), GetDescription(), and IsEqualTo().
GetSP()
lldb::TypeNameSpecifierImplSP SBTypeNameSpecifier::GetSP () protected
Definition at line 153 of file SBTypeNameSpecifier.cpp.
References m_opaque_sp.
Referenced by lldb::SBTypeCategory::AddTypeFilter(), lldb::SBTypeCategory::AddTypeFormat(), lldb::SBTypeCategory::AddTypeSummary(), lldb::SBTypeCategory::AddTypeSynthetic(), lldb::SBTypeCategory::DeleteTypeFilter(), lldb::SBTypeCategory::DeleteTypeFormat(), lldb::SBTypeCategory::DeleteTypeSummary(), lldb::SBTypeCategory::DeleteTypeSynthetic(), lldb::SBDebugger::GetFilterForType(), lldb::SBTypeCategory::GetFilterForType(), lldb::SBTypeCategory::GetFormatForType(), lldb::SBDebugger::GetSummaryForType(), lldb::SBTypeCategory::GetSummaryForType(), lldb::SBDebugger::GetSyntheticForType(), lldb::SBTypeCategory::GetSyntheticForType(), and SBTypeCategory.
GetType()
SBType SBTypeNameSpecifier::GetType ()
Definition at line 71 of file SBTypeNameSpecifier.cpp.
References IsValid(), lldb_private::CompilerType::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBType.
Referenced by ~SBTypeNameSpecifier().
IsEqualTo()
bool SBTypeNameSpecifier::IsEqualTo (lldb::SBTypeNameSpecifier & rhs)
Definition at line 131 of file SBTypeNameSpecifier.cpp.
References GetMatchType(), GetName(), IsValid(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTypeNameSpecifier().
IsRegex()
bool SBTypeNameSpecifier::IsRegex ()
Definition at line 89 of file SBTypeNameSpecifier.cpp.
References lldb::eFormatterMatchRegex, IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeNameSpecifier().
IsValid()
bool SBTypeNameSpecifier::IsValid () const
Definition at line 52 of file SBTypeNameSpecifier.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBTypeCategory::AddTypeFilter(), lldb::SBTypeCategory::AddTypeFormat(), lldb::SBTypeCategory::AddTypeSummary(), lldb::SBTypeCategory::AddTypeSynthetic(), lldb::SBTypeCategory::DeleteTypeFilter(), lldb::SBTypeCategory::DeleteTypeFormat(), lldb::SBTypeCategory::DeleteTypeSummary(), lldb::SBTypeCategory::DeleteTypeSynthetic(), GetDescription(), lldb::SBDebugger::GetFilterForType(), lldb::SBTypeCategory::GetFilterForType(), lldb::SBTypeCategory::GetFormatForType(), GetMatchType(), GetName(), lldb::SBDebugger::GetSummaryForType(), lldb::SBTypeCategory::GetSummaryForType(), lldb::SBDebugger::GetSyntheticForType(), lldb::SBTypeCategory::GetSyntheticForType(), GetType(), IsEqualTo(), IsRegex(), operator!=(), operator==(), and ~SBTypeNameSpecifier().
operator bool()
SBTypeNameSpecifier::operator bool () const explicit
Definition at line 56 of file SBTypeNameSpecifier.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator!=()
bool SBTypeNameSpecifier::operator!= (lldb::SBTypeNameSpecifier & rhs)
Definition at line 145 of file SBTypeNameSpecifier.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeNameSpecifier().
operator=()
lldb::SBTypeNameSpecifier & SBTypeNameSpecifier::operator= (const lldb::SBTypeNameSpecifier & rhs)
Definition at line 113 of file SBTypeNameSpecifier.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeNameSpecifier().
operator==()
bool SBTypeNameSpecifier::operator== (lldb::SBTypeNameSpecifier & rhs)
Definition at line 123 of file SBTypeNameSpecifier.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeNameSpecifier().
SetSP()
void SBTypeNameSpecifier::SetSP (const lldb::TypeNameSpecifierImplSP & type_namespec_sp) protected
Definition at line 157 of file SBTypeNameSpecifier.cpp.
References m_opaque_sp.
Referenced by SBTypeCategory.
Friends And Related Symbol Documentation
SBDebugger
friend class SBDebugger friend
Definition at line 56 of file SBTypeNameSpecifier.h.
References SBDebugger.
Referenced by SBDebugger.
SBTypeCategory
friend class SBTypeCategory friend
Definition at line 57 of file SBTypeNameSpecifier.h.
References GetSP(), SBTypeCategory, and SetSP().
Referenced by SBTypeCategory.
Member Data Documentation
m_opaque_sp
lldb::TypeNameSpecifierImplSP lldb::SBTypeNameSpecifier::m_opaque_sp protected
Definition at line 63 of file SBTypeNameSpecifier.h.
Referenced by GetMatchType(), GetName(), GetSP(), GetType(), IsRegex(), operator bool(), operator!=(), operator=(), operator==(), SBTypeNameSpecifier(), SBTypeNameSpecifier(), SBTypeNameSpecifier(), SBTypeNameSpecifier(), and SetSP().
The documentation for this class was generated from the following files:
SBTypeNameSpecifier.h
SBTypeNameSpecifier.cpp