LLDB: InstructionLLVMC Class Reference
InstructionLLVMC Class Reference
Classes
class DisassemblerScope
Grants exclusive access to the disassembler and initializes it with the given InstructionLLVMC and an optional ExecutionContext.
Public Member Functions
InstructionLLVMC (DisassemblerLLVMC &disasm, const lldb_private::Address &address, AddressClass addr_class)
~InstructionLLVMC () override=default
bool DoesBranch () override
bool HasDelaySlot () override
bool IsLoad () override
bool IsBarrier () override
bool IsAuthenticated () override
DisassemblerLLVMC::MCDisasmInstance * GetDisasmToUse (bool &is_alternate_isa)
size_t Decode (const lldb_private::Disassembler &disassembler, const lldb_private::DataExtractor &data, lldb::offset_t data_offset) override
void AppendComment (std::string &description)
lldb::InstructionControlFlowKind GetControlFlowKind (const lldb_private::ExecutionContext *exe_ctx) override
void CalculateMnemonicOperandsAndComment (const lldb_private::ExecutionContext *exe_ctx) override
bool IsValid () const
bool UsingFileAddress () const
size_t GetByteSize () const
bool ParseOperands (llvm::SmallVectorImpl< Instruction::Operand > &operands) override
bool IsCall () override
Public Member Functions inherited from lldb_private::Instruction
Instruction (const Address &address, AddressClass addr_class=AddressClass::eInvalid)
virtual ~Instruction ()
const Address & GetAddress () const
const char * GetMnemonic (const ExecutionContext *exe_ctx, bool markup=false)
const char * GetOperands (const ExecutionContext *exe_ctx, bool markup=false)
const char * GetComment (const ExecutionContext *exe_ctx)
AddressClass GetAddressClass ()
void SetAddress (const Address &addr)
virtual void Dump (Stream *s, uint32_t max_opcode_byte_size, bool show_address, bool show_bytes, bool show_control_flow_kind, const ExecutionContext *exe_ctx, const SymbolContext *sym_ctx, const SymbolContext *prev_sym_ctx, const FormatEntity::Entry *disassembly_addr_format, size_t max_address_text_size)
Dump the text representation of this Instruction to a Stream.
bool CanSetBreakpoint ()
virtual void SetDescription (llvm::StringRef)
lldb::OptionValueSP ReadArray (FILE *in_file, Stream &out_stream, OptionValue::Type data_type)
lldb::OptionValueSP ReadDictionary (FILE *in_file, Stream &out_stream)
bool DumpEmulation (const ArchSpec &arch)
virtual bool TestEmulation (Stream &stream, const char *test_file_name)
bool Emulate (const ArchSpec &arch, uint32_t evaluate_options, void *baton, EmulateInstruction::ReadMemoryCallback read_mem_callback, EmulateInstruction::WriteMemoryCallback write_mem_calback, EmulateInstruction::ReadRegisterCallback read_reg_callback, EmulateInstruction::WriteRegisterCallback write_reg_callback)
const Opcode & GetOpcode () const
uint32_t GetData (DataExtractor &data)
StructuredData::ArraySP GetVariableAnnotations ()
Get variable annotations for this instruction as structured data.
Static Public Member Functions
static llvm::StringRef::const_iterator ConsumeWhitespace (llvm::StringRef::const_iterator osi, llvm::StringRef::const_iterator ose)
static std::pair< bool, llvm::StringRef::const_iterator > ConsumeChar (llvm::StringRef::const_iterator osi, const char c, llvm::StringRef::const_iterator ose)
static std::pair< Operand, llvm::StringRef::const_iterator > ParseRegisterName (llvm::StringRef::const_iterator osi, llvm::StringRef::const_iterator ose)
static std::pair< Operand, llvm::StringRef::const_iterator > ParseImmediate (llvm::StringRef::const_iterator osi, llvm::StringRef::const_iterator ose)
static std::pair< Operand, llvm::StringRef::const_iterator > ParseIntelIndexedAccess (llvm::StringRef::const_iterator osi, llvm::StringRef::const_iterator ose)
static std::pair< Operand, llvm::StringRef::const_iterator > ParseIntelDerefAccess (llvm::StringRef::const_iterator osi, llvm::StringRef::const_iterator ose)
static std::pair< Operand, llvm::StringRef::const_iterator > ParseARMOffsetAccess (llvm::StringRef::const_iterator osi, llvm::StringRef::const_iterator ose)
static std::pair< Operand, llvm::StringRef::const_iterator > ParseARMDerefAccess (llvm::StringRef::const_iterator osi, llvm::StringRef::const_iterator ose)
static void DumpOperand (const Operand &op, Stream &s)
Static Public Member Functions inherited from lldb_private::Instruction
static const char * GetNameForInstructionControlFlowKind (lldb::InstructionControlFlowKind instruction_control_flow_kind)
Protected Member Functions
void VisitInstruction ()
Protected Member Functions inherited from lldb_private::Instruction
void CalculateMnemonicOperandsAndCommentIfNeeded (const ExecutionContext *exe_ctx)
Protected Attributes
std::weak_ptr< DisassemblerLLVMC > m_disasm_wp
bool m_is_valid = false
bool m_using_file_addr = false
bool m_has_visited_instruction = false
bool m_does_branch = true
bool m_has_delay_slot = false
bool m_is_call = false
bool m_is_load = false
bool m_is_authenticated = false
bool m_is_barrier = false
Protected Attributes inherited from lldb_private::Instruction
Address m_address
Opcode m_opcode
std::string m_opcode_name
std::string m_markup_opcode_name
std::string m_mnemonics
std::string m_markup_mnemonics
std::string m_comment
bool m_calculated_strings
Private Member Functions
DisassemblerLLVMC::MCDisasmInstance * GetDisasmToUse (bool &is_alternate_isa, DisassemblerScope &disasm)
Detailed Description
Definition at line 416 of file DisassemblerLLVMC.cpp.
Constructor & Destructor Documentation
InstructionLLVMC()
InstructionLLVMC::InstructionLLVMC (DisassemblerLLVMC & disasm, const lldb_private::Address & address, AddressClass addr_class) inline
Definition at line 418 of file DisassemblerLLVMC.cpp.
References lldb_private::Instruction::Instruction(), and m_disasm_wp.
Referenced by InstructionLLVMC::DisassemblerScope::DisassemblerScope().
~InstructionLLVMC()
InstructionLLVMC::~InstructionLLVMC () override default
Member Function Documentation
AppendComment()
void InstructionLLVMC::AppendComment (std::string & description) inline
Definition at line 558 of file DisassemblerLLVMC.cpp.
References lldb_private::Instruction::m_comment.
Referenced by CalculateMnemonicOperandsAndComment().
CalculateMnemonicOperandsAndComment()
void InstructionLLVMC::CalculateMnemonicOperandsAndComment (const lldb_private::ExecutionContext * exe_ctx) inline override virtual
Implements lldb_private::Instruction.
Definition at line 580 of file DisassemblerLLVMC.cpp.
References AppendComment(), lldb_private::eCodeAlternateISA, lldb_private::Disassembler::eHexStyleC, lldb_private::RegularExpression::Execute(), lldb_private::Instruction::GetAddressClass(), lldb_private::DataExtractor::GetByteOrder(), lldb_private::DataExtractor::GetByteSize(), lldb_private::DataExtractor::GetDataStart(), lldb_private::TargetProperties::GetHexImmediateStyle(), DisassemblerLLVMC::MCDisasmInstance::GetMCInst(), lldb_private::StreamString::GetString(), lldb_private::ExecutionContext::GetTargetPtr(), lldb_private::DataExtractor::GetU16(), lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU64(), lldb_private::DataExtractor::GetU8(), DisassemblerLLVMC::MCDisasmInstance::GetUseColor(), lldb_private::TargetProperties::GetUseHexImmediates(), LLDB_INVALID_ADDRESS, lldb_private::Instruction::m_address, lldb_private::Instruction::m_comment, lldb_private::Instruction::m_markup_mnemonics, lldb_private::Instruction::m_markup_opcode_name, lldb_private::Instruction::m_mnemonics, lldb_private::Instruction::m_opcode, lldb_private::Instruction::m_opcode_name, m_using_file_addr, pc, lldb_private::DataExtractor::PeekData(), lldb_private::Stream::Printf(), DisassemblerLLVMC::MCDisasmInstance::PrintMCInst(), DisassemblerLLVMC::MCDisasmInstance::SetStyle(), and DisassemblerLLVMC::MCDisasmInstance::SetUseColor().
ConsumeChar()
std::pair< bool, llvm::StringRef::const_iterator > InstructionLLVMC::ConsumeChar (llvm::StringRef::const_iterator osi, const char c, llvm::StringRef::const_iterator ose) inline static
Definition at line 755 of file DisassemblerLLVMC.cpp.
References ConsumeWhitespace().
Referenced by ParseARMDerefAccess(), ParseARMOffsetAccess(), ParseIntelDerefAccess(), ParseIntelIndexedAccess(), and ParseOperands().
ConsumeWhitespace()
llvm::StringRef::const_iterator InstructionLLVMC::ConsumeWhitespace (llvm::StringRef::const_iterator osi, llvm::StringRef::const_iterator ose) inline static
Definition at line 738 of file DisassemblerLLVMC.cpp.
Referenced by ConsumeChar(), ParseImmediate(), ParseOperands(), and ParseRegisterName().
Decode()
size_t InstructionLLVMC::Decode (const lldb_private::Disassembler & disassembler, const lldb_private::DataExtractor & data, lldb::offset_t data_offset) inline override virtual
Implements lldb_private::Instruction.
Definition at line 457 of file DisassemblerLLVMC.cpp.
References lldb_private::DataExtractor::BytesLeft(), lldb_private::DataExtractor::GetByteOrder(), GetDisasmToUse(), lldb_private::ArchSpec::GetMachine(), lldb_private::ArchSpec::GetMaximumOpcodeByteSize(), DisassemblerLLVMC::MCDisasmInstance::GetMCInst(), lldb_private::ArchSpec::GetMinimumOpcodeByteSize(), lldb_private::ArchSpec::GetTriple(), lldb_private::DataExtractor::GetU16(), lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU64(), lldb_private::DataExtractor::GetU8(), lldb_private::Instruction::m_address, m_is_valid, lldb_private::Instruction::m_opcode, pc, lldb_private::DataExtractor::PeekData(), and lldb_private::DataExtractor::ValidOffsetForDataOfSize().
DoesBranch()
bool InstructionLLVMC::DoesBranch () inline override virtual
Implements lldb_private::Instruction.
Definition at line 427 of file DisassemblerLLVMC.cpp.
References m_does_branch, and VisitInstruction().
DumpOperand()
void InstructionLLVMC::DumpOperand (const Operand & op, Stream & s) inline static
Definition at line 1070 of file DisassemblerLLVMC.cpp.
References DumpOperand(), lldb_private::ConstString::GetStringRef(), lldb_private::Instruction::Operand::m_children, lldb_private::Instruction::Operand::m_immediate, lldb_private::Instruction::Operand::m_negative, lldb_private::Instruction::Operand::m_register, lldb_private::Instruction::Operand::m_type, and lldb_private::Stream::PutCString().
Referenced by DumpOperand(), and ParseOperands().
GetByteSize()
size_t InstructionLLVMC::GetByteSize () const inline
Definition at line 713 of file DisassemblerLLVMC.cpp.
References lldb_private::Instruction::m_opcode.
GetControlFlowKind()
lldb::InstructionControlFlowKind InstructionLLVMC::GetControlFlowKind (const lldb_private::ExecutionContext * exe_ctx) inline override virtual
Returns
The control flow kind of this instruction, or eInstructionControlFlowKindUnknown if the instruction can't be classified.
Reimplemented from lldb_private::Instruction.
Definition at line 568 of file DisassemblerLLVMC.cpp.
References lldb::eInstructionControlFlowKindUnknown, x86::GetControlFlowKind(), and lldb_private::Instruction::m_opcode.
GetDisasmToUse() [1/2]
DisassemblerLLVMC::MCDisasmInstance * InstructionLLVMC::GetDisasmToUse (bool & is_alternate_isa) inline
Definition at line 452 of file DisassemblerLLVMC.cpp.
References GetDisasmToUse().
Referenced by Decode(), GetDisasmToUse(), and VisitInstruction().
GetDisasmToUse() [2/2]
DisassemblerLLVMC::MCDisasmInstance * InstructionLLVMC::GetDisasmToUse (bool & is_alternate_isa, DisassemblerScope & disasm) inline private
Definition at line 1244 of file DisassemblerLLVMC.cpp.
References lldb_private::eCodeAlternateISA, and lldb_private::Instruction::GetAddressClass().
HasDelaySlot()
bool InstructionLLVMC::HasDelaySlot () inline override virtual
Reimplemented from lldb_private::Instruction.
Definition at line 432 of file DisassemblerLLVMC.cpp.
References m_has_delay_slot, and VisitInstruction().
IsAuthenticated()
bool InstructionLLVMC::IsAuthenticated () inline override virtual
Implements lldb_private::Instruction.
Definition at line 447 of file DisassemblerLLVMC.cpp.
References m_is_authenticated, and VisitInstruction().
IsBarrier()
bool InstructionLLVMC::IsBarrier () inline override virtual
Implements lldb_private::Instruction.
Definition at line 442 of file DisassemblerLLVMC.cpp.
References m_is_barrier, and VisitInstruction().
IsCall()
bool InstructionLLVMC::IsCall () inline override virtual
Reimplemented from lldb_private::Instruction.
Definition at line 1183 of file DisassemblerLLVMC.cpp.
References m_is_call, and VisitInstruction().
IsLoad()
bool InstructionLLVMC::IsLoad () inline override virtual
Implements lldb_private::Instruction.
Definition at line 437 of file DisassemblerLLVMC.cpp.
References m_is_load, and VisitInstruction().
IsValid()
bool InstructionLLVMC::IsValid () const inline
Definition at line 710 of file DisassemblerLLVMC.cpp.
References m_is_valid.
ParseARMDerefAccess()
std::pair< Operand, llvm::StringRef::const_iterator > InstructionLLVMC::ParseARMDerefAccess (llvm::StringRef::const_iterator osi, llvm::StringRef::const_iterator ose) inline static
Definition at line 1043 of file DisassemblerLLVMC.cpp.
References ConsumeChar(), lldb_private::Instruction::Operand::m_children, lldb_private::Instruction::Operand::m_type, and ParseRegisterName().
Referenced by ParseOperands().
ParseARMOffsetAccess()
std::pair< Operand, llvm::StringRef::const_iterator > InstructionLLVMC::ParseARMOffsetAccess (llvm::StringRef::const_iterator osi, llvm::StringRef::const_iterator ose) inline static
Definition at line 998 of file DisassemblerLLVMC.cpp.
References ConsumeChar(), lldb_private::Instruction::Operand::m_children, lldb_private::Instruction::Operand::m_type, ParseImmediate(), and ParseRegisterName().
Referenced by ParseOperands().
ParseImmediate()
std::pair< Operand, llvm::StringRef::const_iterator > InstructionLLVMC::ParseImmediate (llvm::StringRef::const_iterator osi, llvm::StringRef::const_iterator ose) inline static
Definition at line 810 of file DisassemblerLLVMC.cpp.
References ConsumeWhitespace(), lldb_private::Instruction::Operand::m_immediate, lldb_private::Instruction::Operand::m_negative, and lldb_private::Instruction::Operand::m_type.
Referenced by ParseARMOffsetAccess(), ParseIntelDerefAccess(), ParseIntelIndexedAccess(), and ParseOperands().
ParseIntelDerefAccess()
std::pair< Operand, llvm::StringRef::const_iterator > InstructionLLVMC::ParseIntelDerefAccess (llvm::StringRef::const_iterator osi, llvm::StringRef::const_iterator ose) inline static
Definition at line 951 of file DisassemblerLLVMC.cpp.
References ConsumeChar(), lldb_private::Instruction::Operand::m_children, lldb_private::Instruction::Operand::m_type, ParseImmediate(), and ParseRegisterName().
Referenced by ParseOperands().
ParseIntelIndexedAccess()
std::pair< Operand, llvm::StringRef::const_iterator > InstructionLLVMC::ParseIntelIndexedAccess (llvm::StringRef::const_iterator osi, llvm::StringRef::const_iterator ose) inline static
Definition at line 868 of file DisassemblerLLVMC.cpp.
References ConsumeChar(), lldb_private::Instruction::Operand::m_children, lldb_private::Instruction::Operand::m_type, ParseImmediate(), and ParseRegisterName().
Referenced by ParseOperands().
ParseOperands()
bool InstructionLLVMC::ParseOperands (llvm::SmallVectorImpl< Instruction::Operand > & operands) inline override virtual
Reimplemented from lldb_private::Instruction.
Definition at line 1105 of file DisassemblerLLVMC.cpp.
References ConsumeChar(), ConsumeWhitespace(), lldb_private::Disassembler, DumpOperand(), lldb_private::GetLog(), lldb_private::Instruction::GetOperands(), lldb_private::StreamString::GetString(), lldb_private::Instruction::Operand::IsValid(), m_disasm_wp, ParseARMDerefAccess(), ParseARMOffsetAccess(), ParseImmediate(), ParseIntelDerefAccess(), ParseIntelIndexedAccess(), ParseRegisterName(), lldb_private::Stream::Printf(), lldb_private::Process, and lldb_private::Stream::PutCString().
ParseRegisterName()
std::pair< Operand, llvm::StringRef::const_iterator > InstructionLLVMC::ParseRegisterName (llvm::StringRef::const_iterator osi, llvm::StringRef::const_iterator ose) inline static
Definition at line 769 of file DisassemblerLLVMC.cpp.
References ConsumeWhitespace(), lldb_private::Instruction::Operand::m_register, and lldb_private::Instruction::Operand::m_type.
Referenced by ParseARMDerefAccess(), ParseARMOffsetAccess(), ParseIntelDerefAccess(), ParseIntelIndexedAccess(), and ParseOperands().
UsingFileAddress()
bool InstructionLLVMC::UsingFileAddress () const inline
Definition at line 712 of file DisassemblerLLVMC.cpp.
References m_using_file_addr.
VisitInstruction()
void InstructionLLVMC::VisitInstruction () inline protected
Definition at line 1208 of file DisassemblerLLVMC.cpp.
References DisassemblerLLVMC::MCDisasmInstance::CanBranch(), lldb_private::DataExtractor::GetByteSize(), lldb_private::DataExtractor::GetDataStart(), GetDisasmToUse(), DisassemblerLLVMC::MCDisasmInstance::GetMCInst(), DisassemblerLLVMC::MCDisasmInstance::HasDelaySlot(), DisassemblerLLVMC::MCDisasmInstance::IsAuthenticated(), DisassemblerLLVMC::MCDisasmInstance::IsBarrier(), DisassemblerLLVMC::MCDisasmInstance::IsCall(), DisassemblerLLVMC::MCDisasmInstance::IsLoad(), lldb_private::Instruction::m_address, m_does_branch, m_has_delay_slot, m_has_visited_instruction, m_is_authenticated, m_is_barrier, m_is_call, m_is_load, lldb_private::Instruction::m_opcode, and pc.
Referenced by DoesBranch(), HasDelaySlot(), IsAuthenticated(), IsBarrier(), IsCall(), and IsLoad().
Member Data Documentation
m_disasm_wp
std::weak_ptr<DisassemblerLLVMC> InstructionLLVMC::m_disasm_wp protected
Definition at line 1189 of file DisassemblerLLVMC.cpp.
Referenced by InstructionLLVMC::DisassemblerScope::DisassemblerScope(), InstructionLLVMC(), and ParseOperands().
m_does_branch
bool InstructionLLVMC::m_does_branch = true protected
Definition at line 1201 of file DisassemblerLLVMC.cpp.
Referenced by DoesBranch(), and VisitInstruction().
m_has_delay_slot
bool InstructionLLVMC::m_has_delay_slot = false protected
Definition at line 1202 of file DisassemblerLLVMC.cpp.
Referenced by HasDelaySlot(), and VisitInstruction().
m_has_visited_instruction
bool InstructionLLVMC::m_has_visited_instruction = false protected
Definition at line 1193 of file DisassemblerLLVMC.cpp.
Referenced by VisitInstruction().
m_is_authenticated
bool InstructionLLVMC::m_is_authenticated = false protected
Definition at line 1205 of file DisassemblerLLVMC.cpp.
Referenced by IsAuthenticated(), and VisitInstruction().
m_is_barrier
bool InstructionLLVMC::m_is_barrier = false protected
Definition at line 1206 of file DisassemblerLLVMC.cpp.
Referenced by IsBarrier(), and VisitInstruction().
m_is_call
bool InstructionLLVMC::m_is_call = false protected
Definition at line 1203 of file DisassemblerLLVMC.cpp.
Referenced by IsCall(), and VisitInstruction().
m_is_load
bool InstructionLLVMC::m_is_load = false protected
Definition at line 1204 of file DisassemblerLLVMC.cpp.
Referenced by IsLoad(), and VisitInstruction().
m_is_valid
bool InstructionLLVMC::m_is_valid = false protected
Definition at line 1191 of file DisassemblerLLVMC.cpp.
Referenced by Decode(), and IsValid().
m_using_file_addr
bool InstructionLLVMC::m_using_file_addr = false protected
Definition at line 1192 of file DisassemblerLLVMC.cpp.
Referenced by CalculateMnemonicOperandsAndComment(), and UsingFileAddress().
The documentation for this class was generated from the following file:
DisassemblerLLVMC.cpp