LLDB: RegisterContextNetBSD_x86_64 Class Reference
RegisterContextNetBSD_x86_64 Class Reference
#include <RegisterContextNetBSD_x86_64.h>
Public Member Functions
RegisterContextNetBSD_x86_64 (const lldb_private::ArchSpec &target_arch)
size_t GetGPRSize () const override
const lldb_private::RegisterInfo * GetRegisterInfo () const override
uint32_t GetRegisterCount () const override
uint32_t GetUserRegisterCount () const override
Public Member Functions inherited from lldb_private::RegisterInfoInterface
RegisterInfoInterface (const lldb_private::ArchSpec &target_arch)
virtual ~RegisterInfoInterface ()=default
const lldb_private::ArchSpec & GetTargetArchitecture () const
Private Attributes
const lldb_private::RegisterInfo * m_register_info_p
const uint32_t m_register_count
const uint32_t m_user_register_count
Detailed Description
Definition at line 14 of file RegisterContextNetBSD_x86_64.h.
Constructor & Destructor Documentation
RegisterContextNetBSD_x86_64()
RegisterContextNetBSD_x86_64::RegisterContextNetBSD_x86_64 (const lldb_private::ArchSpec & target_arch)
Definition at line 159 of file RegisterContextNetBSD_x86_64.cpp.
References m_register_count, m_register_info_p, m_user_register_count, PrivateGetRegisterCount(), PrivateGetRegisterInfoPtr(), PrivateGetUserRegisterCount(), and lldb_private::RegisterInfoInterface::RegisterInfoInterface().
Member Function Documentation
GetGPRSize()
size_t RegisterContextNetBSD_x86_64::GetGPRSize () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 166 of file RegisterContextNetBSD_x86_64.cpp.
GetRegisterCount()
uint32_t RegisterContextNetBSD_x86_64::GetRegisterCount () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 172 of file RegisterContextNetBSD_x86_64.cpp.
References m_register_count.
GetRegisterInfo()
const RegisterInfo * RegisterContextNetBSD_x86_64::GetRegisterInfo () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 168 of file RegisterContextNetBSD_x86_64.cpp.
References m_register_info_p.
GetUserRegisterCount()
uint32_t RegisterContextNetBSD_x86_64::GetUserRegisterCount () const override virtual
Reimplemented from lldb_private::RegisterInfoInterface.
Definition at line 176 of file RegisterContextNetBSD_x86_64.cpp.
References m_user_register_count.
Member Data Documentation
m_register_count
const uint32_t RegisterContextNetBSD_x86_64::m_register_count private
Definition at line 29 of file RegisterContextNetBSD_x86_64.h.
Referenced by GetRegisterCount(), and RegisterContextNetBSD_x86_64().
m_register_info_p
const lldb_private::RegisterInfo* RegisterContextNetBSD_x86_64::m_register_info_p private
Definition at line 28 of file RegisterContextNetBSD_x86_64.h.
Referenced by GetRegisterInfo(), and RegisterContextNetBSD_x86_64().
m_user_register_count
const uint32_t RegisterContextNetBSD_x86_64::m_user_register_count private
Definition at line 30 of file RegisterContextNetBSD_x86_64.h.
Referenced by GetUserRegisterCount(), and RegisterContextNetBSD_x86_64().
The documentation for this class was generated from the following files:
RegisterContextNetBSD_x86_64.h
RegisterContextNetBSD_x86_64.cpp