LLDB: lldb_private::ClangASTSource Class Reference
lldb_private::ClangASTSource Class Reference
Provider for named objects defined in the debug info for Clang.
#include "lldb/Expression/ClangASTSource.h"
Classes
class ClangASTSourceProxy
"lldb/Expression/ClangASTSource.h" Proxy for ClangASTSource
Public Member Functions
ClangASTSource (const lldb::TargetSP &target, const std::shared_ptr< ClangASTImporter > &importer)
Constructor.
~ClangASTSource () override
Destructor.
clang::Decl * GetExternalDecl (clang::GlobalDeclID) override
Interface stubs.
clang::Stmt * GetExternalDeclStmt (uint64_t) override
clang::Selector GetExternalSelector (uint32_t) override
uint32_t GetNumExternalSelectors () override
clang::CXXBaseSpecifier * GetExternalCXXBaseSpecifiers (uint64_t Offset) override
void MaterializeVisibleDecls (const clang::DeclContext *DC)
void InstallASTContext (TypeSystemClang &ast_context)
bool FindExternalVisibleDeclsByName (const clang::DeclContext *DC, clang::DeclarationName Name, const clang::DeclContext *OriginalDC) override
Look up all Decls that match a particular name.
void FindExternalLexicalDecls (const clang::DeclContext *DC, llvm::function_ref< bool(clang::Decl::Kind)> IsKindWeWant, llvm::SmallVectorImpl< clang::Decl * > &Decls) override
Enumerate all Decls in a given lexical context.
bool layoutRecordType (const clang::RecordDecl *Record, uint64_t &Size, uint64_t &Alignment, llvm::DenseMap< const clang::FieldDecl *, uint64_t > &FieldOffsets, llvm::DenseMap< const clang::CXXRecordDecl *, clang::CharUnits > &BaseOffsets, llvm::DenseMap< const clang::CXXRecordDecl *, clang::CharUnits > &VirtualBaseOffsets) override
Specify the layout of the contents of a RecordDecl.
void CompleteType (clang::TagDecl *Tag) override
Complete a TagDecl.
void CompleteType (clang::ObjCInterfaceDecl *Class) override
Complete an ObjCInterfaceDecl.
void StartTranslationUnit (clang::ASTConsumer *Consumer) override
Called on entering a translation unit.
void CompleteNamespaceMap (ClangASTImporter::NamespaceMapSP &namespace_map, ConstString name, ClangASTImporter::NamespaceMapSP &parent_map) const override
Look up the modules containing a given namespace and put the appropriate entries in the namespace map.
clang::NamespaceDecl * AddNamespace (NameSearchContext &context)
virtual void FindExternalVisibleDecls (NameSearchContext &context)
The worker function for FindExternalVisibleDeclsByName.
clang::Sema * getSema ()
void SetLookupsEnabled (bool lookups_enabled)
bool GetLookupsEnabled ()
llvm::IntrusiveRefCntPtr< clang::ExternalASTSource > CreateProxy ()
bool IgnoreName (const ConstString name, bool ignore_all_dollar_names)
Returns true if a name should be ignored by name lookup.
clang::Decl * CopyDecl (clang::Decl *src_decl)
Copies a single Decl into the parser's AST context.
ClangASTImporter::DeclOrigin GetDeclOrigin (const clang::Decl *decl)
Determined the origin of a single Decl, if it can be found.
TypeSystemClang * GetTypeSystem () const
Returns the TypeSystem that uses this ClangASTSource instance as it's ExternalASTSource.
Public Member Functions inherited from lldb_private::ClangASTImporter::MapCompleter
virtual ~MapCompleter ()
Protected Member Functions
clang::ObjCInterfaceDecl * GetCompleteObjCInterface (const clang::ObjCInterfaceDecl *interface_decl)
Look for the complete version of an Objective-C interface, and return it if found.
void FindExternalVisibleDecls (NameSearchContext &context, lldb::ModuleSP module, CompilerDeclContext &namespace_decl)
Find all entities matching a given name in a given module, using a NameSearchContext to make Decls for them.
void FindObjCMethodDecls (NameSearchContext &context)
Find all Objective-C methods matching a given selector.
void FindObjCPropertyAndIvarDecls (NameSearchContext &context)
Find all Objective-C properties and ivars with a given name.
void LookupInNamespace (NameSearchContext &context)
Performs lookup into a namespace.
CompilerType GuardedCopyType (const CompilerType &src_type)
A wrapper for TypeSystemClang::CopyType that sets a flag that indicates that we should not respond to queries during import.
std::shared_ptr< ClangModulesDeclVendor > GetClangModulesDeclVendor ()
bool FindObjCMethodDeclsWithOrigin (NameSearchContext &context, clang::ObjCInterfaceDecl *original_interface_decl, const char *log_info)
void FindDeclInModules (NameSearchContext &context, ConstString name)
void FindDeclInObjCRuntime (NameSearchContext &context, ConstString name)
void FillNamespaceMap (NameSearchContext &context, lldb::ModuleSP module_sp, const CompilerDeclContext &namespace_decl)
Fills the namespace map of the given NameSearchContext.
clang::TagDecl * FindCompleteType (const clang::TagDecl *decl)
Protected Attributes
bool m_lookups_enabled
const lldb::TargetSP m_target
The target to use in finding variables and types.
clang::ASTContext * m_ast_context
The AST context requests are coming in for.
TypeSystemClang * m_clang_ast_context
The TypeSystemClang for m_ast_context.
clang::FileManager * m_file_manager
The file manager paired with the AST context.
std::shared_ptr< ClangASTImporter > m_ast_importer_sp
The target's AST importer.
std::set< const clang::Decl * > m_active_lexical_decls
std::set< const char * > m_active_lookups
Private Member Functions
bool FindObjCPropertyAndIvarDeclsWithOrigin (NameSearchContext &context, DeclFromUser< const clang::ObjCInterfaceDecl > &origin_iface_decl)
Friends
struct NameSearchContext
Detailed Description
Provider for named objects defined in the debug info for Clang.
As Clang parses an expression, it may encounter names that are not defined inside the expression, including variables, functions, and types. Clang knows the name it is looking for, but nothing else. The ExternalSemaSource class provides Decls (VarDecl, FunDecl, TypeDecl) to Clang for these names, consulting the ClangExpressionDeclMap to do the actual lookups.
Definition at line 33 of file ClangASTSource.h.
Constructor & Destructor Documentation
ClangASTSource()
ClangASTSource::ClangASTSource (const lldb::TargetSP & target, const std::shared_ptr< ClangASTImporter > & importer)
Constructor.
Initializes class variables.
Parameters
[in] target A reference to the target containing debug information to use.
[in] importer The ClangASTImporter to use.
Definition at line 52 of file ClangASTSource.cpp.
References m_active_lexical_decls, m_active_lookups, m_ast_context, m_ast_importer_sp, m_lookups_enabled, and m_target.
Referenced by lldb_private::ClangASTSource::ClangASTSourceProxy::ClangASTSourceProxy(), and lldb_private::ClangExpressionDeclMap::ClangExpressionDeclMap().
~ClangASTSource()
ClangASTSource::~ClangASTSource () override
Destructor.
Definition at line 68 of file ClangASTSource.cpp.
References lldb_private::ScratchTypeSystemClang::DefaultAST, lldb_private::ScratchTypeSystemClang::ForgetSource(), lldb_private::ScratchTypeSystemClang::GetForTarget(), m_ast_context, m_ast_importer_sp, and m_target.
Member Function Documentation
AddNamespace()
NamespaceDecl * ClangASTSource::AddNamespace (NameSearchContext & context)
Definition at line 1434 of file ClangASTSource.cpp.
References CopyDecl(), lldb_private::TypeSystemClang::DeclContextGetAsNamespaceDecl(), lldb_private::TypeSystemClang::DeclContextGetTypeSystemClang(), m_ast_importer_sp, lldb_private::NameSearchContext::m_decls, lldb_private::NameSearchContext::m_namespace_map, and NameSearchContext.
Referenced by FindExternalVisibleDecls().
CompleteNamespaceMap()
void ClangASTSource::CompleteNamespaceMap (ClangASTImporter::NamespaceMapSP & namespace_map, ConstString name, ClangASTImporter::NamespaceMapSP & parent_map) const override virtual
Look up the modules containing a given namespace and put the appropriate entries in the namespace map.
Parameters
[in] namespace_map The map to be completed.
[in] name The name of the namespace to be found.
[in] parent_map The map for the namespace's parent namespace, if there is one.
Implements lldb_private::ClangASTImporter::MapCompleter.
Definition at line 1360 of file ClangASTSource.cpp.
References lldb_private::Expressions, lldb_private::SymbolFile::FindNamespace(), lldb_private::GetLog(), LLDB_LOG, m_ast_context, m_clang_ast_context, and m_target.
CompleteType() [1/2]
void ClangASTSource::CompleteType (clang::ObjCInterfaceDecl * Class) override
Complete an ObjCInterfaceDecl.
Parameters
[in] Class The Decl to be completed in place.
Definition at line 291 of file ClangASTSource.cpp.
References CompleteType(), lldb_private::ClangASTImporter::DeclOrigin::decl, lldb_private::ClangUtil::DumpDecl(), lldb_private::Expressions, GetCompleteObjCInterface(), lldb_private::GetLog(), LLDB_LOG, m_ast_context, m_ast_importer_sp, m_clang_ast_context, and lldb_private::ClangASTImporter::DeclOrigin::Valid().
CompleteType() [2/2]
void lldb_private::ClangASTSource::CompleteType (clang::TagDecl * Tag) override
Complete a TagDecl.
Parameters
[in] Tag The Decl to be completed in place.
References NameSearchContext.
Referenced by lldb_private::ClangExpressionDeclMap::AddExpressionVariable(), and CompleteType().
CopyDecl()
clang::Decl * ClangASTSource::CopyDecl (clang::Decl * src_decl)
Copies a single Decl into the parser's AST context.
Parameters
[in] src_decl The Decl to copy.
Returns
A copy of the Decl in m_ast_context, or NULL if the copy failed.
Definition at line 1469 of file ClangASTSource.cpp.
References m_ast_context, and m_ast_importer_sp.
Referenced by AddNamespace(), lldb_private::ClangExpressionDeclMap::AddOneFunction(), FindDeclInModules(), FindDeclInObjCRuntime(), FindExternalLexicalDecls(), FindObjCMethodDecls(), FindObjCMethodDeclsWithOrigin(), lldb_private::ClangExpressionDeclMap::LookupFunction(), lldb_private::ClangExpressionDeclMap::LookupInModulesDeclVendor(), and lldb_private::ClangExpressionDeclMap::SearchPersistenDecls().
CreateProxy()
llvm::IntrusiveRefCntPtr< clang::ExternalASTSource > lldb_private::ClangASTSource::CreateProxy () inline
Definition at line 254 of file ClangASTSource.h.
Referenced by lldb_private::ClangExpressionParser::ParseInternal().
FillNamespaceMap()
void ClangASTSource::FillNamespaceMap (NameSearchContext & context, lldb::ModuleSP module_sp, const CompilerDeclContext & namespace_decl) protected
Fills the namespace map of the given NameSearchContext.
Parameters
context The NameSearchContext with the namespace map to fill.
module_sp The module to search for namespaces or a nullptr if the current target should be searched.
namespace_decl The DeclContext in which to search for namespaces.
Definition at line 644 of file ClangASTSource.cpp.
References lldb_private::Expressions, lldb_private::SymbolFile::FindNamespace(), lldb_private::GetLog(), IgnoreName(), LLDB_LOG, lldb_private::NameSearchContext::m_decl_context, lldb_private::NameSearchContext::m_decl_name, lldb_private::NameSearchContext::m_namespace_map, m_target, and NameSearchContext.
Referenced by FindExternalVisibleDecls().
FindCompleteType()
TagDecl * ClangASTSource::FindCompleteType (const clang::TagDecl * decl) protected
Definition at line 185 of file ClangASTSource.cpp.
References lldb_private::Expressions, lldb_private::ModuleList::FindTypes(), lldb_private::TypeSystemClang::GetCompleteDecl(), lldb_private::GetLog(), lldb_private::ClangUtil::GetQualType(), lldb_private::TypeResults::GetTypeMap(), lldb_private::ClangUtil::IsClangType(), LLDB_LOG, LLDB_LOGV, m_ast_importer_sp, m_clang_ast_context, m_target, and lldb_private::TypeMap::Types().
FindDeclInModules()
void ClangASTSource::FindDeclInModules (NameSearchContext & context, ConstString name) protected
Definition at line 789 of file ClangASTSource.cpp.
References lldb_private::NameSearchContext::AddNamedDecl(), CopyDecl(), lldb_private::Expressions, GetClangModulesDeclVendor(), lldb_private::ClangUtil::GetDecl(), lldb_private::GetLog(), LLDB_LOG, lldb_private::NameSearchContext::m_found_type, and NameSearchContext.
Referenced by FindExternalVisibleDecls().
FindDeclInObjCRuntime()
void ClangASTSource::FindDeclInObjCRuntime (NameSearchContext & context, ConstString name) protected
Definition at line 830 of file ClangASTSource.cpp.
References lldb_private::NameSearchContext::AddNamedDecl(), CopyDecl(), lldb_private::Expressions, lldb_private::ObjCLanguageRuntime::Get(), lldb_private::ClangUtil::GetDecl(), lldb_private::LanguageRuntime::GetDeclVendor(), lldb_private::GetLog(), LLDB_LOG, m_target, and NameSearchContext.
Referenced by FindExternalVisibleDecls().
FindExternalLexicalDecls()
void ClangASTSource::FindExternalLexicalDecls (const clang::DeclContext * DC, llvm::function_ref< bool(clang::Decl::Kind)> IsKindWeWant, llvm::SmallVectorImpl< clang::Decl * > & Decls) override
Enumerate all Decls in a given lexical context.
Parameters
[in] DC The DeclContext being searched.
[in] IsKindWeWant A callback function that returns true given the DeclKinds of desired Decls, and false otherwise.
[in] Decls A vector that is filled in with matching Decls.
Definition at line 367 of file ClangASTSource.cpp.
References CopyDecl(), lldb_private::ClangASTImporter::DeclOrigin::ctx, lldb_private::ClangASTImporter::DeclOrigin::decl, lldb_private::ClangUtil::DumpDecl(), lldb_private::Expressions, GetCompleteObjCInterface(), lldb_private::GetLog(), LLDB_LOG, m_active_lexical_decls, m_ast_context, m_ast_importer_sp, m_clang_ast_context, and lldb_private::ClangASTImporter::DeclOrigin::Valid().
FindExternalVisibleDecls() [1/2]
void ClangASTSource::FindExternalVisibleDecls (NameSearchContext & context) virtual
The worker function for FindExternalVisibleDeclsByName.
Parameters
[in] context The NameSearchContext to use when filing results.
Reimplemented in lldb_private::ClangExpressionDeclMap.
Definition at line 500 of file ClangASTSource.cpp.
References AddNamespace(), lldb_private::Expressions, FindExternalVisibleDecls(), FindObjCPropertyAndIvarDecls(), lldb_private::GetLog(), lldb_private::Log::GetVerbose(), LLDB_LOG, LookupInNamespace(), m_ast_context, m_clang_ast_context, lldb_private::NameSearchContext::m_decl_context, lldb_private::NameSearchContext::m_decl_name, lldb_private::NameSearchContext::m_namespace_map, and NameSearchContext.
Referenced by FindExternalVisibleDecls(), lldb_private::ClangExpressionDeclMap::FindExternalVisibleDecls(), FindExternalVisibleDeclsByName(), and LookupInNamespace().
FindExternalVisibleDecls() [2/2]
void ClangASTSource::FindExternalVisibleDecls (NameSearchContext & context, lldb::ModuleSP module, CompilerDeclContext & namespace_decl) protected
Find all entities matching a given name in a given module, using a NameSearchContext to make Decls for them.
Parameters
[in] context The NameSearchContext that can construct Decls for this name.
[in] module If non-NULL, the module to query.
[in] namespace_decl If valid and module is non-NULL, the parent namespace.
Definition at line 576 of file ClangASTSource.cpp.
References lldb_private::NameSearchContext::AddTypeDecl(), lldb_private::Expressions, FillNamespaceMap(), FindDeclInModules(), FindDeclInObjCRuntime(), lldb_private::TypeResults::GetFirstType(), lldb_private::GetLog(), lldb_private::ConstString::GetStringRef(), GuardedCopyType(), IgnoreName(), LLDB_LOG, m_ast_context, lldb_private::NameSearchContext::m_decl_name, lldb_private::NameSearchContext::m_found_type, m_target, and NameSearchContext.
FindExternalVisibleDeclsByName()
bool ClangASTSource::FindExternalVisibleDeclsByName (const clang::DeclContext * DC, clang::DeclarationName Name, const clang::DeclContext * OriginalDC) override
Look up all Decls that match a particular name.
Only handles Identifiers and DeclContexts that are either NamespaceDecls or TranslationUnitDecls. Calls SetExternalVisibleDeclsForName with the result.
The work for this function is done by void FindExternalVisibleDecls (NameSearchContext &);
Parameters
[in] DC The DeclContext to register the found Decls in.
[in] Name The name to find entries for.
Returns
Whatever SetExternalVisibleDeclsForName returns.
Definition at line 100 of file ClangASTSource.cpp.
References FindExternalVisibleDecls(), FindObjCMethodDecls(), lldb_private::ConstString::GetCString(), GetLookupsEnabled(), m_active_lookups, m_ast_context, m_clang_ast_context, NameSearchContext, and SetLookupsEnabled().
FindObjCMethodDecls()
void ClangASTSource::FindObjCMethodDecls (NameSearchContext & context) protected
Find all Objective-C methods matching a given selector.
Parameters
[in] context The NameSearchContext that can construct Decls for this name. Its m_decl_name contains the selector and its m_decl_context is the containing object.
Definition at line 873 of file ClangASTSource.cpp.
References lldb_private::NameSearchContext::AddNamedDecl(), lldb_private::SymbolContextList::Append(), lldb_private::ConstString::AsCString(), lldb_private::StreamString::Clear(), lldb_private::SymbolContextList::Clear(), CopyDecl(), lldb_private::ClangASTImporter::DeclOrigin::decl, lldb_private::TypeSystemClang::DeclContextGetAsObjCMethodDecl(), lldb_private::ClangUtil::DumpDecl(), lldb_private::Expressions, FindObjCMethodDeclsWithOrigin(), lldb_private::StreamString::Flush(), lldb_private::ObjCLanguageRuntime::Get(), GetClangModulesDeclVendor(), GetCompleteObjCInterface(), lldb_private::ClangUtil::GetDecl(), lldb_private::LanguageRuntime::GetDeclVendor(), lldb_private::GetLog(), lldb_private::SymbolContextList::GetSize(), lldb_private::StreamString::GetString(), lldb_private::ModuleFunctionSearchOptions::include_inlines, lldb_private::ModuleFunctionSearchOptions::include_symbols, LLDB_LOG, m_ast_context, m_ast_importer_sp, m_clang_ast_context, lldb_private::NameSearchContext::m_decl_context, lldb_private::NameSearchContext::m_decl_name, m_target, NameSearchContext, lldb_private::Stream::Printf(), and lldb_private::ClangASTImporter::DeclOrigin::Valid().
Referenced by FindExternalVisibleDeclsByName().
FindObjCMethodDeclsWithOrigin()
bool ClangASTSource::FindObjCMethodDeclsWithOrigin (NameSearchContext & context, clang::ObjCInterfaceDecl * original_interface_decl, const char * log_info) protected
Definition at line 706 of file ClangASTSource.cpp.
References lldb_private::NameSearchContext::AddNamedDecl(), CopyDecl(), lldb_private::ClangUtil::DumpDecl(), lldb_private::Expressions, lldb_private::TypeSystemClang::GetCompleteDecl(), lldb_private::GetLog(), LLDB_LOG, lldb_private::NameSearchContext::m_decl_name, and NameSearchContext.
Referenced by FindObjCMethodDecls().
FindObjCPropertyAndIvarDecls()
void ClangASTSource::FindObjCPropertyAndIvarDecls (NameSearchContext & context) protected
Find all Objective-C properties and ivars with a given name.
Parameters
[in] context The NameSearchContext that can construct Decls for this name. Its m_decl_name contains the name and its m_decl_context is the containing object.
Definition at line 1190 of file ClangASTSource.cpp.
References lldb_private::TaggedASTDecl< D >::decl, lldb_private::Expressions, FindObjCPropertyAndIvarDeclsWithOrigin(), lldb_private::ObjCLanguageRuntime::Get(), GetClangModulesDeclVendor(), GetCompleteObjCInterface(), lldb_private::ClangUtil::GetDecl(), lldb_private::LanguageRuntime::GetDeclVendor(), lldb_private::GetLog(), lldb_private::DeclFromParser< D >::GetOrigin(), lldb_private::TaggedASTDecl< D >::IsValid(), LLDB_LOG, m_ast_context, m_ast_importer_sp, m_clang_ast_context, lldb_private::NameSearchContext::m_decl_context, lldb_private::NameSearchContext::m_decl_name, m_target, and NameSearchContext.
Referenced by FindExternalVisibleDecls().
FindObjCPropertyAndIvarDeclsWithOrigin()
bool ClangASTSource::FindObjCPropertyAndIvarDeclsWithOrigin (NameSearchContext & context, DeclFromUser< const clang::ObjCInterfaceDecl > & origin_iface_decl) private
Definition at line 1141 of file ClangASTSource.cpp.
References lldb_private::NameSearchContext::AddNamedDecl(), lldb_private::TaggedASTDecl< D >::decl, lldb_private::ClangUtil::DumpDecl(), lldb_private::Expressions, lldb_private::GetLog(), lldb_private::DeclFromUser< D >::Import(), lldb_private::TaggedASTDecl< D >::IsInvalid(), lldb_private::TaggedASTDecl< D >::IsValid(), LLDB_LOG, m_ast_context, m_ast_importer_sp, lldb_private::NameSearchContext::m_decl_name, and NameSearchContext.
Referenced by FindObjCPropertyAndIvarDecls().
GetClangModulesDeclVendor()
std::shared_ptr< ClangModulesDeclVendor > ClangASTSource::GetClangModulesDeclVendor () protected
Definition at line 1495 of file ClangASTSource.cpp.
References lldb::eLanguageTypeC, and m_target.
Referenced by FindDeclInModules(), FindObjCMethodDecls(), FindObjCPropertyAndIvarDecls(), lldb_private::ClangExpressionDeclMap::LookupFunction(), and lldb_private::ClangExpressionDeclMap::LookupInModulesDeclVendor().
GetCompleteObjCInterface()
clang::ObjCInterfaceDecl * ClangASTSource::GetCompleteObjCInterface (const clang::ObjCInterfaceDecl * interface_decl) protected
Look for the complete version of an Objective-C interface, and return it if found.
Parameters
[in] interface_decl An ObjCInterfaceDecl that may not be the complete one.
Returns
NULL if the complete interface couldn't be found; the complete interface otherwise.
Definition at line 326 of file ClangASTSource.cpp.
References lldb_private::ObjCLanguageRuntime::Get(), lldb_private::CompilerType::GetOpaqueQualType(), lldb_private::ObjCLanguageRuntime::LookupInCompleteClassCache(), and m_target.
Referenced by CompleteType(), FindExternalLexicalDecls(), FindObjCMethodDecls(), and FindObjCPropertyAndIvarDecls().
GetDeclOrigin()
ClangASTImporter::DeclOrigin ClangASTSource::GetDeclOrigin (const clang::Decl * decl)
Determined the origin of a single Decl, if it can be found.
Parameters
[in] decl The Decl whose origin is to be found.
Returns
True if lookup succeeded; false otherwise.
Definition at line 1473 of file ClangASTSource.cpp.
References m_ast_importer_sp.
GetExternalCXXBaseSpecifiers()
clang::CXXBaseSpecifier * lldb_private::ClangASTSource::GetExternalCXXBaseSpecifiers (uint64_t Offset) inline override
Definition at line 59 of file ClangASTSource.h.
GetExternalDecl()
clang::Decl * lldb_private::ClangASTSource::GetExternalDecl (clang::GlobalDeclID) inline override
Interface stubs.
Definition at line 52 of file ClangASTSource.h.
GetExternalDeclStmt()
clang::Stmt * lldb_private::ClangASTSource::GetExternalDeclStmt (uint64_t) inline override
Definition at line 53 of file ClangASTSource.h.
GetExternalSelector()
clang::Selector lldb_private::ClangASTSource::GetExternalSelector (uint32_t) inline override
Definition at line 54 of file ClangASTSource.h.
GetLookupsEnabled()
bool lldb_private::ClangASTSource::GetLookupsEnabled () inline
Definition at line 203 of file ClangASTSource.h.
References m_lookups_enabled.
Referenced by FindExternalVisibleDeclsByName().
GetNumExternalSelectors()
uint32_t lldb_private::ClangASTSource::GetNumExternalSelectors () inline override
Definition at line 57 of file ClangASTSource.h.
getSema()
clang::Sema * ClangASTSource::getSema ()
Definition at line 555 of file ClangASTSource.cpp.
References m_clang_ast_context.
GetTypeSystem()
TypeSystemClang * lldb_private::ClangASTSource::GetTypeSystem () const inline
Returns the TypeSystem that uses this ClangASTSource instance as it's ExternalASTSource.
Definition at line 354 of file ClangASTSource.h.
References m_clang_ast_context.
GuardedCopyType()
CompilerType ClangASTSource::GuardedCopyType (const CompilerType & src_type) protected
A wrapper for TypeSystemClang::CopyType that sets a flag that indicates that we should not respond to queries during import.
Parameters
[in] src_type The source type.
Returns
The imported type.
Definition at line 1477 of file ClangASTSource.cpp.
References lldb_private::ClangUtil::GetQualType(), lldb_private::CompilerType::GetTypeSystem(), m_ast_importer_sp, and m_clang_ast_context.
Referenced by lldb_private::ClangExpressionDeclMap::AddContextClassType(), lldb_private::ClangExpressionDeclMap::AddOneFunction(), lldb_private::ClangExpressionDeclMap::AddOneType(), lldb_private::ClangExpressionDeclMap::AddOneVariable(), lldb_private::ClangExpressionDeclMap::AddOneVariable(), FindExternalVisibleDecls(), lldb_private::ClangExpressionDeclMap::GetVariableValue(), and lldb_private::ClangExpressionDeclMap::SearchFunctionsInSymbolContexts().
IgnoreName()
bool ClangASTSource::IgnoreName (const ConstString name, bool ignore_all_dollar_names)
Returns true if a name should be ignored by name lookup.
Parameters
[in] name The name to be considered.
[in] ignore_all_dollar_names True if $-names of all sorts should be ignored.
Returns
True if the name is one of a class of names that are ignored by global lookup for performance reasons.
Definition at line 559 of file ClangASTSource.cpp.
References lldb_private::ConstString::GetStringRef(), and m_ast_context.
Referenced by FillNamespaceMap(), FindExternalVisibleDecls(), and lldb_private::ClangExpressionDeclMap::FindExternalVisibleDecls().
InstallASTContext()
void ClangASTSource::InstallASTContext (TypeSystemClang & ast_context)
Definition at line 61 of file ClangASTSource.cpp.
References lldb_private::TypeSystemClang::getASTContext(), m_ast_context, m_ast_importer_sp, m_clang_ast_context, and m_file_manager.
Referenced by lldb_private::ClangExpressionParser::ParseInternal().
layoutRecordType()
bool ClangASTSource::layoutRecordType (const clang::RecordDecl * Record, uint64_t & Size, uint64_t & Alignment, llvm::DenseMap< const clang::FieldDecl *, uint64_t > & FieldOffsets, llvm::DenseMap< const clang::CXXRecordDecl *, clang::CharUnits > & BaseOffsets, llvm::DenseMap< const clang::CXXRecordDecl *, clang::CharUnits > & VirtualBaseOffsets) override
Specify the layout of the contents of a RecordDecl.
Parameters
[in] Record The record (in the parser's AST context) that needs to be laid out.
[out] Size The total size of the record in bits.
[out] Alignment The alignment of the record in bits.
[in] FieldOffsets A map that must be populated with pairs of the record's fields (in the parser's AST context) and their offsets (measured in bits).
[in] BaseOffsets A map that must be populated with pairs of the record's C++ concrete base classes (in the parser's AST context, and only if the record is a CXXRecordDecl and has base classes) and their offsets (measured in bytes).
[in] VirtualBaseOffsets A map that must be populated with pairs of the record's C++ virtual base classes (in the parser's AST context, and only if the record is a CXXRecordDecl and has base classes) and their offsets (measured in bytes).
Returns
True <=> the layout is valid.
Definition at line 1348 of file ClangASTSource.cpp.
References m_ast_importer_sp.
LookupInNamespace()
void ClangASTSource::LookupInNamespace (NameSearchContext & context) protected
Performs lookup into a namespace.
Parameters
context The NameSearchContext for a lookup inside a namespace.
Definition at line 1323 of file ClangASTSource.cpp.
References lldb_private::Expressions, FindExternalVisibleDecls(), lldb_private::GetLog(), LLDB_LOG, LLDB_LOGV, m_ast_importer_sp, lldb_private::NameSearchContext::m_decl_context, and NameSearchContext.
Referenced by FindExternalVisibleDecls().
MaterializeVisibleDecls()
void lldb_private::ClangASTSource::MaterializeVisibleDecls (const clang::DeclContext * DC) inline
Definition at line 62 of file ClangASTSource.h.
SetLookupsEnabled()
void lldb_private::ClangASTSource::SetLookupsEnabled (bool lookups_enabled) inline
Definition at line 200 of file ClangASTSource.h.
References m_lookups_enabled.
Referenced by lldb_private::ClangUserExpression::Complete(), FindExternalVisibleDeclsByName(), and lldb_private::ClangUserExpression::TryParse().
StartTranslationUnit()
void ClangASTSource::StartTranslationUnit (clang::ASTConsumer * Consumer) override
Called on entering a translation unit.
Tells Clang by calling setHasExternalVisibleStorage() and setHasExternalLexicalStorage() that this object has something to say about undefined names.
Parameters
[in] Consumer Unused.
Definition at line 91 of file ClangASTSource.cpp.
References m_ast_context.
Friends And Related Symbol Documentation
NameSearchContext
friend struct NameSearchContext friend
Definition at line 380 of file ClangASTSource.h.
References NameSearchContext.
Referenced by lldb_private::ClangExpressionDeclMap::AddContextClassType(), lldb_private::ClangExpressionDeclMap::AddExpressionVariable(), AddNamespace(), lldb_private::ClangExpressionDeclMap::AddOneFunction(), lldb_private::ClangExpressionDeclMap::AddOneGenericVariable(), lldb_private::ClangExpressionDeclMap::AddOneRegister(), lldb_private::ClangExpressionDeclMap::AddOneType(), lldb_private::ClangExpressionDeclMap::AddOneVariable(), lldb_private::ClangExpressionDeclMap::AddOneVariable(), lldb_private::ClangExpressionDeclMap::AddOneVariable(), CompleteType(), FillNamespaceMap(), FindDeclInModules(), FindDeclInObjCRuntime(), FindExternalVisibleDecls(), FindExternalVisibleDecls(), lldb_private::ClangExpressionDeclMap::FindExternalVisibleDecls(), lldb_private::ClangExpressionDeclMap::FindExternalVisibleDecls(), FindExternalVisibleDeclsByName(), FindObjCMethodDecls(), FindObjCMethodDeclsWithOrigin(), FindObjCPropertyAndIvarDecls(), FindObjCPropertyAndIvarDeclsWithOrigin(), lldb_private::ClangExpressionDeclMap::LookupFunction(), lldb_private::ClangExpressionDeclMap::LookupInModulesDeclVendor(), LookupInNamespace(), lldb_private::ClangExpressionDeclMap::LookUpLldbClass(), lldb_private::ClangExpressionDeclMap::LookUpLldbObjCClass(), lldb_private::ClangExpressionDeclMap::LookupLocalVariable(), lldb_private::ClangExpressionDeclMap::LookupLocalVarNamespace(), NameSearchContext, and lldb_private::ClangExpressionDeclMap::SearchPersistenDecls().
Member Data Documentation
m_active_lexical_decls
std::set<const clang::Decl *> lldb_private::ClangASTSource::m_active_lexical_decls protected
Definition at line 394 of file ClangASTSource.h.
Referenced by ClangASTSource(), and FindExternalLexicalDecls().
m_active_lookups
std::set<const char *> lldb_private::ClangASTSource::m_active_lookups protected
Definition at line 395 of file ClangASTSource.h.
Referenced by ClangASTSource(), and FindExternalVisibleDeclsByName().
m_ast_context
clang::ASTContext* lldb_private::ClangASTSource::m_ast_context protected
The AST context requests are coming in for.
Definition at line 387 of file ClangASTSource.h.
Referenced by lldb_private::ClangExpressionDeclMap::AddContextClassType(), ClangASTSource(), CompleteNamespaceMap(), CompleteType(), CopyDecl(), lldb_private::ClangExpressionDeclMap::DeportType(), FindExternalLexicalDecls(), FindExternalVisibleDecls(), FindExternalVisibleDecls(), lldb_private::ClangExpressionDeclMap::FindExternalVisibleDecls(), lldb_private::ClangExpressionDeclMap::FindExternalVisibleDecls(), FindExternalVisibleDeclsByName(), FindObjCMethodDecls(), FindObjCPropertyAndIvarDecls(), FindObjCPropertyAndIvarDeclsWithOrigin(), lldb_private::ClangExpressionDeclMap::GetScratchContext(), IgnoreName(), InstallASTContext(), lldb_private::ClangExpressionDeclMap::LookUpLldbClass(), StartTranslationUnit(), and ~ClangASTSource().
m_ast_importer_sp
std::shared_ptr<ClangASTImporter> lldb_private::ClangASTSource::m_ast_importer_sp protected
The target's AST importer.
Definition at line 393 of file ClangASTSource.h.
Referenced by AddNamespace(), ClangASTSource(), CompleteType(), CopyDecl(), lldb_private::ClangExpressionDeclMap::DeportType(), FindCompleteType(), FindExternalLexicalDecls(), lldb_private::ClangExpressionDeclMap::FindExternalVisibleDecls(), FindObjCMethodDecls(), FindObjCPropertyAndIvarDecls(), FindObjCPropertyAndIvarDeclsWithOrigin(), GetDeclOrigin(), GuardedCopyType(), InstallASTContext(), layoutRecordType(), LookupInNamespace(), and ~ClangASTSource().
m_clang_ast_context
TypeSystemClang* lldb_private::ClangASTSource::m_clang_ast_context protected
The TypeSystemClang for m_ast_context.
Definition at line 389 of file ClangASTSource.h.
Referenced by lldb_private::ClangExpressionDeclMap::AddContextClassType(), lldb_private::ClangExpressionDeclMap::AddOneGenericVariable(), lldb_private::ClangExpressionDeclMap::AddOneRegister(), CompleteNamespaceMap(), CompleteType(), FindCompleteType(), FindExternalLexicalDecls(), FindExternalVisibleDecls(), lldb_private::ClangExpressionDeclMap::FindExternalVisibleDecls(), FindExternalVisibleDeclsByName(), FindObjCMethodDecls(), FindObjCPropertyAndIvarDecls(), getSema(), GetTypeSystem(), GuardedCopyType(), InstallASTContext(), and lldb_private::ClangExpressionDeclMap::LookupLocalVarNamespace().
m_file_manager
clang::FileManager* lldb_private::ClangASTSource::m_file_manager protected
The file manager paired with the AST context.
Definition at line 391 of file ClangASTSource.h.
Referenced by InstallASTContext().
m_lookups_enabled
bool lldb_private::ClangASTSource::m_lookups_enabled protected
Definition at line 382 of file ClangASTSource.h.
Referenced by ClangASTSource(), GetLookupsEnabled(), and SetLookupsEnabled().
m_target
const lldb::TargetSP lldb_private::ClangASTSource::m_target protected
The target to use in finding variables and types.
Definition at line 385 of file ClangASTSource.h.
Referenced by ClangASTSource(), CompleteNamespaceMap(), FillNamespaceMap(), FindCompleteType(), FindDeclInObjCRuntime(), FindExternalVisibleDecls(), FindObjCMethodDecls(), FindObjCPropertyAndIvarDecls(), GetClangModulesDeclVendor(), GetCompleteObjCInterface(), lldb_private::ClangExpressionDeclMap::LookupInModulesDeclVendor(), and ~ClangASTSource().
The documentation for this class was generated from the following files:
ClangASTSource.h
ClangASTSource.cpp