LLDB: lldb::SBModuleSpec Class Reference
lldb::SBModuleSpec Class Reference
#include <SBModuleSpec.h>
Public Member Functions
SBModuleSpec ()
SBModuleSpec (const SBModuleSpec &rhs)
~SBModuleSpec ()
const SBModuleSpec & operator= (const SBModuleSpec &rhs)
operator bool () const
bool IsValid () const
void Clear ()
lldb::SBFileSpec GetFileSpec ()
Get const accessor for the module file.
void SetFileSpec (const lldb::SBFileSpec &fspec)
lldb::SBFileSpec GetPlatformFileSpec ()
Get accessor for the module platform file.
void SetPlatformFileSpec (const lldb::SBFileSpec &fspec)
lldb::SBFileSpec GetSymbolFileSpec ()
void SetSymbolFileSpec (const lldb::SBFileSpec &fspec)
const char * GetObjectName ()
void SetObjectName (const char *name)
const char * GetTriple ()
void SetTriple (const char *triple)
const uint8_t * GetUUIDBytes ()
size_t GetUUIDLength ()
bool SetUUIDBytes (const uint8_t *uuid, size_t uuid_len)
uint64_t GetObjectOffset ()
void SetObjectOffset (uint64_t object_offset)
uint64_t GetObjectSize ()
void SetObjectSize (uint64_t object_size)
bool GetDescription (lldb::SBStream &description)
lldb::SBTarget GetTarget () const
void SetTarget (lldb::SBTarget target)
Set the target to be used when resolving a module.
Private Member Functions
SBModuleSpec (const lldb_private::ModuleSpec &module_spec)
Private Attributes
std::unique_ptr< lldb_private::ModuleSpec > m_opaque_up
Friends
class SBModuleSpecList
class SBModule
class SBPlatform
class SBTarget
Detailed Description
Definition at line 17 of file SBModuleSpec.h.
Constructor & Destructor Documentation
SBModuleSpec() [1/3]
SBModuleSpec::SBModuleSpec ()
Definition at line 23 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by operator=(), SBModuleSpec(), SBTarget, and ~SBModuleSpec().
SBModuleSpec() [2/3]
SBModuleSpec::SBModuleSpec (const SBModuleSpec & rhs)
Definition at line 27 of file SBModuleSpec.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBModuleSpec().
~SBModuleSpec()
SBModuleSpec::~SBModuleSpec () default
References Clear(), GetDescription(), GetFileSpec(), GetObjectName(), GetObjectOffset(), GetObjectSize(), GetPlatformFileSpec(), GetSymbolFileSpec(), GetTarget(), GetTriple(), GetUUIDBytes(), GetUUIDLength(), IsValid(), operator=(), SBModuleSpec(), SetFileSpec(), SetObjectName(), SetObjectOffset(), SetObjectSize(), SetPlatformFileSpec(), SetSymbolFileSpec(), SetTarget(), SetTriple(), and SetUUIDBytes().
SBModuleSpec() [3/3]
SBModuleSpec::SBModuleSpec (const lldb_private::ModuleSpec & module_spec) private
Definition at line 33 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Member Function Documentation
Clear()
void SBModuleSpec::Clear ()
Definition at line 58 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBModuleSpec().
GetDescription()
bool SBModuleSpec::GetDescription (lldb::SBStream & description)
Definition at line 147 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBStream::ref().
Referenced by ~SBModuleSpec().
GetFileSpec()
SBFileSpec SBModuleSpec::GetFileSpec ()
Get const accessor for the module file.
This function returns the file for the module on the host system that is running LLDB. This can differ from the path on the platform since we might be doing remote debugging.
Returns
A const reference to the file specification object.
Definition at line 64 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBModuleSpec().
GetObjectName()
const char * SBModuleSpec::GetObjectName ()
Definition at line 101 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBModuleSpec().
GetObjectOffset()
uint64_t SBModuleSpec::GetObjectOffset ()
Definition at line 154 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBModuleSpec().
GetObjectSize()
uint64_t SBModuleSpec::GetObjectSize ()
Definition at line 166 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBModuleSpec().
GetPlatformFileSpec()
lldb::SBFileSpec SBModuleSpec::GetPlatformFileSpec ()
Get accessor for the module platform file.
Platform file refers to the path of the module as it is known on the remote system on which it is being debugged. For local debugging this is always the same as Module::GetFileSpec(). But remote debugging might mention a file '/usr/lib/liba.dylib' which might be locally downloaded and cached. In this case the platform file could be something like: '/tmp/lldb/platform-cache/remote.host.computer/usr/lib/liba.dylib' The file could also be cached in a local developer kit directory.
Returns
A const reference to the file specification object.
Definition at line 77 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBFileSpec.
Referenced by ~SBModuleSpec().
GetSymbolFileSpec()
lldb::SBFileSpec SBModuleSpec::GetSymbolFileSpec ()
Definition at line 89 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBFileSpec.
Referenced by ~SBModuleSpec().
GetTarget()
SBTarget SBModuleSpec::GetTarget () const
Definition at line 178 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and SBTarget.
Referenced by ~SBModuleSpec().
GetTriple()
const char * SBModuleSpec::GetTriple ()
Definition at line 113 of file SBModuleSpec.cpp.
References lldb_private::ConstString::GetCString(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBModuleSpec().
GetUUIDBytes()
const uint8_t * SBModuleSpec::GetUUIDBytes ()
Definition at line 130 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBModuleSpec().
GetUUIDLength()
size_t SBModuleSpec::GetUUIDLength ()
Definition at line 135 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBModuleSpec().
IsValid()
bool SBModuleSpec::IsValid () const
Definition at line 48 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBTarget::FindModule(), and ~SBModuleSpec().
operator bool()
SBModuleSpec::operator bool () const explicit
Definition at line 52 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
operator=()
const SBModuleSpec & SBModuleSpec::operator= (const SBModuleSpec & rhs)
Definition at line 38 of file SBModuleSpec.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBModuleSpec().
Referenced by ~SBModuleSpec().
SetFileSpec()
void SBModuleSpec::SetFileSpec (const lldb::SBFileSpec & fspec)
Definition at line 71 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBModuleSpec().
SetObjectName()
void SBModuleSpec::SetObjectName (const char * name)
Definition at line 107 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBModuleSpec().
SetObjectOffset()
void SBModuleSpec::SetObjectOffset (uint64_t object_offset)
Definition at line 160 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBModuleSpec().
SetObjectSize()
void SBModuleSpec::SetObjectSize (uint64_t object_size)
Definition at line 172 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBModuleSpec().
SetPlatformFileSpec()
void SBModuleSpec::SetPlatformFileSpec (const lldb::SBFileSpec & fspec)
Definition at line 83 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBModuleSpec().
SetSymbolFileSpec()
void SBModuleSpec::SetSymbolFileSpec (const lldb::SBFileSpec & fspec)
Definition at line 95 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBModuleSpec().
SetTarget()
void SBModuleSpec::SetTarget (lldb::SBTarget target)
Set the target to be used when resolving a module.
A target can help locate a module specified by a SBModuleSpec. The target settings, like the executable and debug info search paths, can be essential. The target's platform can also be used to locate or download the specified module.
Definition at line 184 of file SBModuleSpec.cpp.
References lldb::SBTarget::GetSP(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBTarget.
Referenced by ~SBModuleSpec().
SetTriple()
void SBModuleSpec::SetTriple (const char * triple)
Definition at line 124 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBModuleSpec().
SetUUIDBytes()
bool SBModuleSpec::SetUUIDBytes (const uint8_t * uuid, size_t uuid_len)
Definition at line 141 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBModuleSpec().
Friends And Related Symbol Documentation
SBModule
friend class SBModule friend
Definition at line 102 of file SBModuleSpec.h.
References SBModule.
Referenced by SBModule.
SBModuleSpecList
friend class SBModuleSpecList friend
Definition at line 101 of file SBModuleSpec.h.
References SBModuleSpecList.
Referenced by SBModuleSpecList.
SBPlatform
friend class SBPlatform friend
Definition at line 103 of file SBModuleSpec.h.
References SBPlatform.
Referenced by SBPlatform.
SBTarget
friend class SBTarget friend
Definition at line 104 of file SBModuleSpec.h.
References SBModuleSpec(), and SBTarget.
Referenced by GetTarget(), SBTarget, and SetTarget().
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::ModuleSpec> lldb::SBModuleSpec::m_opaque_up private
Definition at line 108 of file SBModuleSpec.h.
Referenced by lldb::SBTarget::AddModule(), lldb::SBModuleSpecList::Append(), Clear(), lldb::SBModuleSpecList::FindFirstMatchingSpec(), lldb::SBModuleSpecList::FindMatchingSpecs(), lldb::SBTarget::FindModule(), GetDescription(), GetFileSpec(), GetObjectName(), GetObjectOffset(), GetObjectSize(), GetPlatformFileSpec(), lldb::SBModuleSpecList::GetSpecAtIndex(), GetSymbolFileSpec(), GetTarget(), GetTriple(), GetUUIDBytes(), GetUUIDLength(), operator bool(), operator=(), lldb::SBModule::SBModule(), SBModuleSpec(), SBModuleSpec(), SBModuleSpec(), SetFileSpec(), SetObjectName(), SetObjectOffset(), SetObjectSize(), SetPlatformFileSpec(), SetSymbolFileSpec(), SetTarget(), SetTriple(), and SetUUIDBytes().
The documentation for this class was generated from the following files:
SBModuleSpec.h
SBModuleSpec.cpp