LLDB: RegisterContextDarwin_riscv32 Class Reference
RegisterContextDarwin_riscv32 Class Reference abstract
#include <RegisterContextDarwin_riscv32.h>
Classes
struct CSR
struct EXC
struct FPU
struct GPR
Public Member Functions
RegisterContextDarwin_riscv32 (lldb_private::Thread &thread, uint32_t concrete_frame_idx)
~RegisterContextDarwin_riscv32 () override
void InvalidateAllRegisters () override
size_t GetRegisterCount () override
const lldb_private::RegisterInfo * GetRegisterInfoAtIndex (size_t reg) override
size_t GetRegisterSetCount () override
const lldb_private::RegisterSet * GetRegisterSet (size_t set) override
bool ReadRegister (const lldb_private::RegisterInfo *reg_info, lldb_private::RegisterValue &value) override
bool WriteRegister (const lldb_private::RegisterInfo *reg_info, const lldb_private::RegisterValue &value) override
bool ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp) override
bool WriteAllRegisterValues (const lldb::DataBufferSP &data_sp) override
uint32_t ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num) override
Convert from a given register numbering scheme to the lldb register numbering scheme.
Public Member Functions inherited from lldb_private::RegisterContext
RegisterContext (Thread &thread, uint32_t concrete_frame_idx)
~RegisterContext () override
void InvalidateIfNeeded (bool force)
virtual lldb::ByteOrder GetByteOrder ()
virtual bool RegisterWriteCausesReconfigure (const llvm::StringRef name)
virtual bool ReconfigureRegisterInfo ()
virtual bool ReadAllRegisterValues (lldb_private::RegisterCheckpoint &reg_checkpoint)
virtual bool WriteAllRegisterValues (const lldb_private::RegisterCheckpoint &reg_checkpoint)
bool CopyFromRegisterContext (lldb::RegisterContextSP context)
virtual uint32_t NumSupportedHardwareBreakpoints ()
virtual uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual bool ClearHardwareBreakpoint (uint32_t hw_idx)
virtual uint32_t NumSupportedHardwareWatchpoints ()
virtual uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, bool read, bool write)
virtual bool ClearHardwareWatchpoint (uint32_t hw_index)
virtual bool HardwareSingleStep (bool enable)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, uint32_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, uint32_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual Thread & GetThread ()
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num)
uint64_t GetPC (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetThreadPointer (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool GetPCForSymbolication (Address &address)
Get an address suitable for symbolication.
bool SetPC (uint64_t pc)
bool SetPC (Address addr)
uint64_t GetSP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetSP (uint64_t sp)
uint64_t GetFP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetFP (uint64_t fp)
const char * GetRegisterName (uint32_t reg)
uint64_t GetReturnAddress (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetFlags (uint64_t fail_value=0)
uint64_t ReadRegisterAsUnsigned (uint32_t reg, uint64_t fail_value)
uint64_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, uint64_t fail_value)
bool WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
bool WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
bool ConvertBetweenRegisterKinds (lldb::RegisterKind source_rk, uint32_t source_regnum, lldb::RegisterKind target_rk, uint32_t &target_regnum)
lldb::TargetSP CalculateTarget () override
lldb::ProcessSP CalculateProcess () override
lldb::ThreadSP CalculateThread () override
lldb::StackFrameSP CalculateStackFrame () override
void CalculateExecutionContext (ExecutionContext &exe_ctx) override
Reconstruct the object's execution context into sc.
uint32_t GetStopID () const
void SetStopID (uint32_t stop_id)
Public Member Functions inherited from lldb_private::ExecutionContextScope
virtual ~ExecutionContextScope ()=default
Protected Types
enum {
GPRRegSet = 2 , EXCRegSet = 3 , FPURegSet = 4 , CSRRegSet1 = 6 ,
CSRRegSet2 = 7 , CSRRegSet3 = 8 , CSRRegSet4 = 9 , CSRRegSet = 10
}
enum { GPRWordCount = sizeof(GPR) / sizeof(uint32_t) , FPUWordCount = sizeof(FPU) / sizeof(uint32_t) , EXCWordCount = sizeof(EXC) / sizeof(uint32_t) , CSRWordCount = sizeof(CSR) / sizeof(uint32_t) }
enum { Read = 0 , Write = 1 , kNumErrors = 2 }
Protected Member Functions
void InvalidateAllRegisterStates ()
int GetError (int flavor, uint32_t err_idx) const
bool SetError (int flavor, uint32_t err_idx, int err)
bool RegisterSetIsCached (int set) const
void LogGPR (lldb_private::Log *log, const char *title)
int ReadGPR (bool force)
int ReadFPU (bool force)
int ReadEXC (bool force)
int ReadCSR (bool force)
int WriteGPR ()
int WriteFPU ()
int WriteEXC ()
int WriteCSR ()
virtual int DoReadGPR (lldb::tid_t tid, int flavor, GPR &gpr)=0
virtual int DoReadFPU (lldb::tid_t tid, int flavor, FPU &fpr)=0
virtual int DoReadEXC (lldb::tid_t tid, int flavor, EXC &exc)=0
virtual int DoReadCSR (lldb::tid_t tid, int flavor, CSR &exc)=0
virtual int DoWriteGPR (lldb::tid_t tid, int flavor, const GPR &gpr)=0
virtual int DoWriteFPU (lldb::tid_t tid, int flavor, const FPU &fpr)=0
virtual int DoWriteEXC (lldb::tid_t tid, int flavor, const EXC &exc)=0
virtual int DoWriteCSR (lldb::tid_t tid, int flavor, const CSR &exc)=0
int ReadRegisterSet (uint32_t set, bool force)
int WriteRegisterSet (uint32_t set)
Protected Member Functions inherited from lldb_private::RegisterContext
virtual bool BehavesLikeZerothFrame () const
Indicates that this frame is currently executing code, that the PC value is not a return-pc but an actual executing instruction.
Static Protected Member Functions
static uint32_t GetRegisterNumber (uint32_t reg_kind, uint32_t reg_num)
static int GetSetForNativeRegNum (int reg_num)
static size_t GetRegisterInfosCount ()
static const lldb_private::RegisterInfo * GetRegisterInfos ()
Protected Attributes
GPR gpr
FPU fpr
EXC exc
CSR csr
int gpr_errs [2]
int fpr_errs [2]
int exc_errs [2]
int csr_errs [2]
Protected Attributes inherited from lldb_private::RegisterContext
Thread & m_thread
uint32_t m_concrete_frame_idx
uint32_t m_stop_id
Detailed Description
Definition at line 15 of file RegisterContextDarwin_riscv32.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
GPRRegSet
EXCRegSet
FPURegSet
CSRRegSet1
CSRRegSet2
CSRRegSet3
CSRRegSet4
CSRRegSet
Definition at line 128 of file RegisterContextDarwin_riscv32.h.
anonymous enum
anonymous enum protected
Enumerator
Read
Write
kNumErrors
Definition at line 146 of file RegisterContextDarwin_riscv32.h.
anonymous enum
anonymous enum protected
Enumerator
GPRWordCount
FPUWordCount
EXCWordCount
CSRWordCount
Definition at line 139 of file RegisterContextDarwin_riscv32.h.
Constructor & Destructor Documentation
RegisterContextDarwin_riscv32()
RegisterContextDarwin_riscv32::RegisterContextDarwin_riscv32 (lldb_private::Thread & thread, uint32_t concrete_frame_idx)
Definition at line 718 of file RegisterContextDarwin_riscv32.cpp.
References csr_errs, exc, exc_errs, fpr, fpr_errs, gpr, gpr_errs, kNumErrors, and lldb_private::RegisterContext::RegisterContext().
Referenced by RegisterContextDarwin_riscv32_Mach::RegisterContextDarwin_riscv32_Mach().
~RegisterContextDarwin_riscv32()
RegisterContextDarwin_riscv32::~RegisterContextDarwin_riscv32 () override default
Member Function Documentation
ConvertRegisterKindToRegisterNumber()
uint32_t RegisterContextDarwin_riscv32::ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num) override virtual
Convert from a given register numbering scheme to the lldb register numbering scheme.
There may be multiple ways to enumerate the registers for a given architecture. ABI references will specify one to be used with DWARF, the register numberings from process plugin, there may be a variation used for eh_frame unwind instructions (e.g. on Darwin), and so on. Register 5 by itself is meaningless - RegisterKind enumeration tells you what context that number should be translated as.
Inside lldb, register numbers are in the eRegisterKindLLDB scheme; arguments which take a register number should take one in that scheme.
eRegisterKindGeneric is a special numbering scheme which gives us constant values for the pc, frame register, stack register, etc., for use within lldb. They may not be defined for all architectures but it allows generic code to translate these common registers into the lldb numbering scheme.
This method translates a given register kind + register number into the eRegisterKindLLDB register numbering.
Parameters
[in] kind The register numbering scheme (RegisterKind) that the following register number is in.
[in] num A register number in the 'kind' register numbering scheme.
Returns
The equivalent register number in the eRegisterKindLLDB numbering scheme, if possible, else LLDB_INVALID_REGNUM.
Reimplemented from lldb_private::RegisterContext.
Definition at line 1221 of file RegisterContextDarwin_riscv32.cpp.
References riscv_dwarf::dwarf_fpr_f0, riscv_dwarf::dwarf_fpr_f1, riscv_dwarf::dwarf_fpr_f10, riscv_dwarf::dwarf_fpr_f11, riscv_dwarf::dwarf_fpr_f12, riscv_dwarf::dwarf_fpr_f13, riscv_dwarf::dwarf_fpr_f14, riscv_dwarf::dwarf_fpr_f15, riscv_dwarf::dwarf_fpr_f16, riscv_dwarf::dwarf_fpr_f17, riscv_dwarf::dwarf_fpr_f18, riscv_dwarf::dwarf_fpr_f19, riscv_dwarf::dwarf_fpr_f2, riscv_dwarf::dwarf_fpr_f20, riscv_dwarf::dwarf_fpr_f21, riscv_dwarf::dwarf_fpr_f22, riscv_dwarf::dwarf_fpr_f23, riscv_dwarf::dwarf_fpr_f24, riscv_dwarf::dwarf_fpr_f25, riscv_dwarf::dwarf_fpr_f26, riscv_dwarf::dwarf_fpr_f27, riscv_dwarf::dwarf_fpr_f28, riscv_dwarf::dwarf_fpr_f29, riscv_dwarf::dwarf_fpr_f3, riscv_dwarf::dwarf_fpr_f30, riscv_dwarf::dwarf_fpr_f31, riscv_dwarf::dwarf_fpr_f4, riscv_dwarf::dwarf_fpr_f5, riscv_dwarf::dwarf_fpr_f6, riscv_dwarf::dwarf_fpr_f7, riscv_dwarf::dwarf_fpr_f8, riscv_dwarf::dwarf_fpr_f9, riscv_dwarf::dwarf_gpr_x0, riscv_dwarf::dwarf_gpr_x1, riscv_dwarf::dwarf_gpr_x10, riscv_dwarf::dwarf_gpr_x11, riscv_dwarf::dwarf_gpr_x12, riscv_dwarf::dwarf_gpr_x13, riscv_dwarf::dwarf_gpr_x14, riscv_dwarf::dwarf_gpr_x15, riscv_dwarf::dwarf_gpr_x16, riscv_dwarf::dwarf_gpr_x17, riscv_dwarf::dwarf_gpr_x18, riscv_dwarf::dwarf_gpr_x19, riscv_dwarf::dwarf_gpr_x2, riscv_dwarf::dwarf_gpr_x20, riscv_dwarf::dwarf_gpr_x21, riscv_dwarf::dwarf_gpr_x22, riscv_dwarf::dwarf_gpr_x23, riscv_dwarf::dwarf_gpr_x24, riscv_dwarf::dwarf_gpr_x25, riscv_dwarf::dwarf_gpr_x26, riscv_dwarf::dwarf_gpr_x27, riscv_dwarf::dwarf_gpr_x28, riscv_dwarf::dwarf_gpr_x29, riscv_dwarf::dwarf_gpr_x3, riscv_dwarf::dwarf_gpr_x30, riscv_dwarf::dwarf_gpr_x31, riscv_dwarf::dwarf_gpr_x4, riscv_dwarf::dwarf_gpr_x5, riscv_dwarf::dwarf_gpr_x6, riscv_dwarf::dwarf_gpr_x7, riscv_dwarf::dwarf_gpr_x8, riscv_dwarf::dwarf_gpr_x9, lldb::eRegisterKindDWARF, lldb::eRegisterKindEHFrame, lldb::eRegisterKindGeneric, lldb::eRegisterKindLLDB, fpr_f0, gpr_pc, gpr_x0, gpr_x1, gpr_x2, gpr_x8, LLDB_INVALID_REGNUM, LLDB_REGNUM_GENERIC_FP, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_RA, and LLDB_REGNUM_GENERIC_SP.
DoReadCSR()
virtual int RegisterContextDarwin_riscv32::DoReadCSR (lldb::tid_t tid, int flavor, CSR & exc) protected pure virtual
Implemented in RegisterContextDarwin_riscv32_Mach.
References exc.
Referenced by ReadCSR().
DoReadEXC()
virtual int RegisterContextDarwin_riscv32::DoReadEXC (lldb::tid_t tid, int flavor, EXC & exc) protected pure virtual
Implemented in RegisterContextDarwin_riscv32_Mach.
References exc.
Referenced by ReadEXC().
DoReadFPU()
virtual int RegisterContextDarwin_riscv32::DoReadFPU (lldb::tid_t tid, int flavor, FPU & fpr) protected pure virtual
Implemented in RegisterContextDarwin_riscv32_Mach.
References fpr.
Referenced by ReadFPU().
DoReadGPR()
virtual int RegisterContextDarwin_riscv32::DoReadGPR (lldb::tid_t tid, int flavor, GPR & gpr) protected pure virtual
Implemented in RegisterContextDarwin_riscv32_Mach.
References gpr.
Referenced by ReadGPR().
DoWriteCSR()
virtual int RegisterContextDarwin_riscv32::DoWriteCSR (lldb::tid_t tid, int flavor, const CSR & exc) protected pure virtual
Implemented in RegisterContextDarwin_riscv32_Mach.
References exc.
Referenced by WriteCSR().
DoWriteEXC()
virtual int RegisterContextDarwin_riscv32::DoWriteEXC (lldb::tid_t tid, int flavor, const EXC & exc) protected pure virtual
Implemented in RegisterContextDarwin_riscv32_Mach.
References exc.
Referenced by WriteEXC().
DoWriteFPU()
virtual int RegisterContextDarwin_riscv32::DoWriteFPU (lldb::tid_t tid, int flavor, const FPU & fpr) protected pure virtual
Implemented in RegisterContextDarwin_riscv32_Mach.
References fpr.
Referenced by WriteFPU().
DoWriteGPR()
virtual int RegisterContextDarwin_riscv32::DoWriteGPR (lldb::tid_t tid, int flavor, const GPR & gpr) protected pure virtual
Implemented in RegisterContextDarwin_riscv32_Mach.
References gpr.
Referenced by WriteGPR().
GetError()
int RegisterContextDarwin_riscv32::GetError (int flavor, uint32_t err_idx) const inline protected
Definition at line 164 of file RegisterContextDarwin_riscv32.h.
References csr_errs, CSRRegSet, exc_errs, EXCRegSet, fpr_errs, FPURegSet, gpr_errs, GPRRegSet, and kNumErrors.
Referenced by ReadCSR(), ReadEXC(), ReadFPU(), ReadGPR(), RegisterSetIsCached(), WriteCSR(), WriteEXC(), WriteFPU(), and WriteGPR().
GetRegisterCount()
size_t RegisterContextDarwin_riscv32::GetRegisterCount () override virtual
Implements lldb_private::RegisterContext.
Definition at line 736 of file RegisterContextDarwin_riscv32.cpp.
References k_num_register_infos, and k_num_registers.
GetRegisterInfoAtIndex()
const RegisterInfo * RegisterContextDarwin_riscv32::GetRegisterInfoAtIndex (size_t reg) override virtual
Implements lldb_private::RegisterContext.
Definition at line 742 of file RegisterContextDarwin_riscv32.cpp.
References g_register_infos, k_num_register_infos, and k_num_registers.
GetRegisterInfos()
const RegisterInfo * RegisterContextDarwin_riscv32::GetRegisterInfos () static protected
Definition at line 753 of file RegisterContextDarwin_riscv32.cpp.
References g_register_infos.
GetRegisterInfosCount()
size_t RegisterContextDarwin_riscv32::GetRegisterInfosCount () static protected
Definition at line 749 of file RegisterContextDarwin_riscv32.cpp.
References k_num_register_infos.
GetRegisterNumber()
uint32_t RegisterContextDarwin_riscv32::GetRegisterNumber (uint32_t reg_kind, uint32_t reg_num) static protected
GetRegisterSet()
const RegisterSet * RegisterContextDarwin_riscv32::GetRegisterSet (size_t set) override virtual
Implements lldb_private::RegisterContext.
Definition at line 807 of file RegisterContextDarwin_riscv32.cpp.
References g_reg_sets, and k_num_regsets.
GetRegisterSetCount()
size_t RegisterContextDarwin_riscv32::GetRegisterSetCount () override virtual
Implements lldb_private::RegisterContext.
Definition at line 802 of file RegisterContextDarwin_riscv32.cpp.
References k_num_regsets.
GetSetForNativeRegNum()
int RegisterContextDarwin_riscv32::GetSetForNativeRegNum (int reg_num) static protected
Definition at line 814 of file RegisterContextDarwin_riscv32.cpp.
References csr_bank, CSRRegSet, exc_exception, EXCRegSet, fpr_f0, FPURegSet, GPRRegSet, and k_num_registers.
Referenced by ReadRegister(), and WriteRegister().
InvalidateAllRegisters()
void RegisterContextDarwin_riscv32::InvalidateAllRegisters () override virtual
Implements lldb_private::RegisterContext.
Reimplemented in RegisterContextDarwin_riscv32_Mach.
Definition at line 732 of file RegisterContextDarwin_riscv32.cpp.
References InvalidateAllRegisterStates().
InvalidateAllRegisterStates()
void RegisterContextDarwin_riscv32::InvalidateAllRegisterStates () inline protected
Definition at line 157 of file RegisterContextDarwin_riscv32.h.
References CSRRegSet, EXCRegSet, FPURegSet, GPRRegSet, Read, and SetError().
Referenced by InvalidateAllRegisters().
LogGPR()
void RegisterContextDarwin_riscv32::LogGPR (lldb_private::Log * log, const char * title) protected
Definition at line 826 of file RegisterContextDarwin_riscv32.cpp.
References g_register_infos, gpr, gpr_x0, k_num_gpr_registers, and LLDB_LOGF.
ReadAllRegisterValues()
bool RegisterContextDarwin_riscv32::ReadAllRegisterValues (lldb::WritableDataBufferSP & data_sp) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 1171 of file RegisterContextDarwin_riscv32.cpp.
References csr, exc, fpr, gpr, ReadCSR(), ReadEXC(), ReadFPU(), ReadGPR(), and REG_CONTEXT_SIZE.
ReadCSR()
int RegisterContextDarwin_riscv32::ReadCSR (bool force) protected
Definition at line 862 of file RegisterContextDarwin_riscv32.cpp.
References csr, CSRRegSet, DoReadCSR(), GetError(), lldb_private::RegisterContext::GetThreadID(), Read, RegisterSetIsCached(), and SetError().
Referenced by ReadAllRegisterValues(), and ReadRegisterSet().
ReadEXC()
int RegisterContextDarwin_riscv32::ReadEXC (bool force) protected
Definition at line 854 of file RegisterContextDarwin_riscv32.cpp.
References DoReadEXC(), exc, EXCRegSet, GetError(), lldb_private::RegisterContext::GetThreadID(), Read, RegisterSetIsCached(), and SetError().
Referenced by ReadAllRegisterValues(), and ReadRegisterSet().
ReadFPU()
int RegisterContextDarwin_riscv32::ReadFPU (bool force) protected
Definition at line 846 of file RegisterContextDarwin_riscv32.cpp.
References DoReadFPU(), fpr, FPURegSet, GetError(), lldb_private::RegisterContext::GetThreadID(), Read, RegisterSetIsCached(), and SetError().
Referenced by ReadAllRegisterValues(), and ReadRegisterSet().
ReadGPR()
int RegisterContextDarwin_riscv32::ReadGPR (bool force) protected
Definition at line 838 of file RegisterContextDarwin_riscv32.cpp.
References DoReadGPR(), GetError(), lldb_private::RegisterContext::GetThreadID(), gpr, GPRRegSet, Read, RegisterSetIsCached(), and SetError().
Referenced by ReadAllRegisterValues(), and ReadRegisterSet().
ReadRegister()
bool RegisterContextDarwin_riscv32::ReadRegister (const lldb_private::RegisterInfo * reg_info, lldb_private::RegisterValue & value) override virtual
Implements lldb_private::RegisterContext.
Definition at line 949 of file RegisterContextDarwin_riscv32.cpp.
References csr_bank, lldb::eRegisterKindLLDB, exc, exc_exception, exc_far, exc_fsr, fpr, fpr_f0, fpr_f1, fpr_f10, fpr_f11, fpr_f12, fpr_f13, fpr_f14, fpr_f15, fpr_f16, fpr_f17, fpr_f18, fpr_f19, fpr_f2, fpr_f20, fpr_f21, fpr_f22, fpr_f23, fpr_f24, fpr_f25, fpr_f26, fpr_f27, fpr_f28, fpr_f29, fpr_f3, fpr_f30, fpr_f31, fpr_f4, fpr_f5, fpr_f6, fpr_f7, fpr_f8, fpr_f9, fpr_fcsr, GetSetForNativeRegNum(), gpr, gpr_pc, gpr_x0, gpr_x1, gpr_x10, gpr_x11, gpr_x12, gpr_x13, gpr_x14, gpr_x15, gpr_x16, gpr_x17, gpr_x18, gpr_x19, gpr_x2, gpr_x20, gpr_x21, gpr_x22, gpr_x23, gpr_x24, gpr_x25, gpr_x26, gpr_x27, gpr_x28, gpr_x29, gpr_x3, gpr_x30, gpr_x31, gpr_x4, gpr_x5, gpr_x6, gpr_x7, gpr_x8, gpr_x9, lldb_private::RegisterInfo::kinds, and ReadRegisterSet().
ReadRegisterSet()
int RegisterContextDarwin_riscv32::ReadRegisterSet (uint32_t set, bool force) protected
Definition at line 914 of file RegisterContextDarwin_riscv32.cpp.
References CSRRegSet, EXCRegSet, FPURegSet, GPRRegSet, ReadCSR(), ReadEXC(), ReadFPU(), and ReadGPR().
Referenced by ReadRegister(), and WriteRegister().
RegisterSetIsCached()
bool RegisterContextDarwin_riscv32::RegisterSetIsCached (int set) const inline protected
Definition at line 210 of file RegisterContextDarwin_riscv32.h.
References GetError(), and Read.
Referenced by ReadCSR(), ReadEXC(), ReadFPU(), ReadGPR(), WriteCSR(), WriteEXC(), WriteFPU(), WriteGPR(), and WriteRegisterSet().
SetError()
bool RegisterContextDarwin_riscv32::SetError (int flavor, uint32_t err_idx, int err) inline protected
Definition at line 184 of file RegisterContextDarwin_riscv32.h.
References csr_errs, CSRRegSet, exc_errs, EXCRegSet, fpr_errs, FPURegSet, gpr_errs, GPRRegSet, and kNumErrors.
Referenced by InvalidateAllRegisterStates(), ReadCSR(), ReadEXC(), ReadFPU(), ReadGPR(), RegisterContextDarwin_riscv32_Mach::SetRegisterDataFrom_LC_THREAD(), WriteCSR(), WriteEXC(), WriteFPU(), and WriteGPR().
WriteAllRegisterValues()
bool RegisterContextDarwin_riscv32::WriteAllRegisterValues (const lldb::DataBufferSP & data_sp) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 1192 of file RegisterContextDarwin_riscv32.cpp.
References csr, exc, fpr, gpr, REG_CONTEXT_SIZE, WriteCSR(), WriteEXC(), WriteFPU(), and WriteGPR().
WriteCSR()
int RegisterContextDarwin_riscv32::WriteCSR () protected
Definition at line 903 of file RegisterContextDarwin_riscv32.cpp.
References csr, CSRRegSet, DoWriteCSR(), GetError(), lldb_private::RegisterContext::GetThreadID(), Read, RegisterSetIsCached(), SetError(), and Write.
Referenced by WriteAllRegisterValues(), and WriteRegisterSet().
WriteEXC()
int RegisterContextDarwin_riscv32::WriteEXC () protected
Definition at line 892 of file RegisterContextDarwin_riscv32.cpp.
References DoWriteEXC(), exc, EXCRegSet, GetError(), lldb_private::RegisterContext::GetThreadID(), Read, RegisterSetIsCached(), SetError(), and Write.
Referenced by WriteAllRegisterValues(), and WriteRegisterSet().
WriteFPU()
int RegisterContextDarwin_riscv32::WriteFPU () protected
Definition at line 881 of file RegisterContextDarwin_riscv32.cpp.
References DoWriteFPU(), fpr, FPURegSet, GetError(), lldb_private::RegisterContext::GetThreadID(), Read, RegisterSetIsCached(), SetError(), and Write.
Referenced by WriteAllRegisterValues(), and WriteRegisterSet().
WriteGPR()
int RegisterContextDarwin_riscv32::WriteGPR () protected
Definition at line 870 of file RegisterContextDarwin_riscv32.cpp.
References DoWriteGPR(), GetError(), lldb_private::RegisterContext::GetThreadID(), gpr, GPRRegSet, Read, RegisterSetIsCached(), SetError(), and Write.
Referenced by WriteAllRegisterValues(), and WriteRegisterSet().
WriteRegister()
bool RegisterContextDarwin_riscv32::WriteRegister (const lldb_private::RegisterInfo * reg_info, const lldb_private::RegisterValue & value) override virtual
Implements lldb_private::RegisterContext.
Definition at line 1062 of file RegisterContextDarwin_riscv32.cpp.
References csr_bank, lldb::eRegisterKindLLDB, exc, exc_exception, exc_far, exc_fsr, fpr, fpr_f0, fpr_f1, fpr_f10, fpr_f11, fpr_f12, fpr_f13, fpr_f14, fpr_f15, fpr_f16, fpr_f17, fpr_f18, fpr_f19, fpr_f2, fpr_f20, fpr_f21, fpr_f22, fpr_f23, fpr_f24, fpr_f25, fpr_f26, fpr_f27, fpr_f28, fpr_f29, fpr_f3, fpr_f30, fpr_f31, fpr_f4, fpr_f5, fpr_f6, fpr_f7, fpr_f8, fpr_f9, fpr_fcsr, lldb_private::RegisterValue::GetAsUInt32(), GetSetForNativeRegNum(), gpr, gpr_pc, gpr_x0, gpr_x1, gpr_x10, gpr_x11, gpr_x12, gpr_x13, gpr_x14, gpr_x15, gpr_x16, gpr_x17, gpr_x18, gpr_x19, gpr_x2, gpr_x20, gpr_x21, gpr_x22, gpr_x23, gpr_x24, gpr_x25, gpr_x26, gpr_x27, gpr_x28, gpr_x29, gpr_x3, gpr_x30, gpr_x31, gpr_x4, gpr_x5, gpr_x6, gpr_x7, gpr_x8, gpr_x9, lldb_private::RegisterInfo::kinds, ReadRegisterSet(), and WriteRegisterSet().
WriteRegisterSet()
int RegisterContextDarwin_riscv32::WriteRegisterSet (uint32_t set) protected
Definition at line 930 of file RegisterContextDarwin_riscv32.cpp.
References CSRRegSet, EXCRegSet, FPURegSet, GPRRegSet, RegisterSetIsCached(), WriteCSR(), WriteEXC(), WriteFPU(), and WriteGPR().
Referenced by WriteRegister().
Member Data Documentation
csr
CSR RegisterContextDarwin_riscv32::csr protected
Definition at line 151 of file RegisterContextDarwin_riscv32.h.
Referenced by RegisterContextDarwin_riscv32_Mach::DoReadCSR(), RegisterContextDarwin_riscv32_Mach::DoWriteCSR(), ReadAllRegisterValues(), ReadCSR(), WriteAllRegisterValues(), and WriteCSR().
csr_errs
int RegisterContextDarwin_riscv32::csr_errs[2] protected
Definition at line 155 of file RegisterContextDarwin_riscv32.h.
Referenced by GetError(), RegisterContextDarwin_riscv32(), and SetError().
exc
EXC RegisterContextDarwin_riscv32::exc protected
Definition at line 150 of file RegisterContextDarwin_riscv32.h.
Referenced by DoReadCSR(), DoReadEXC(), RegisterContextDarwin_riscv32_Mach::DoReadEXC(), DoWriteCSR(), DoWriteEXC(), RegisterContextDarwin_riscv32_Mach::DoWriteEXC(), ReadAllRegisterValues(), ReadEXC(), ReadRegister(), RegisterContextDarwin_riscv32(), RegisterContextDarwin_riscv32_Mach::SetRegisterDataFrom_LC_THREAD(), WriteAllRegisterValues(), WriteEXC(), and WriteRegister().
exc_errs
int RegisterContextDarwin_riscv32::exc_errs[2] protected
Definition at line 154 of file RegisterContextDarwin_riscv32.h.
Referenced by GetError(), RegisterContextDarwin_riscv32(), and SetError().
fpr
FPU RegisterContextDarwin_riscv32::fpr protected
Definition at line 149 of file RegisterContextDarwin_riscv32.h.
Referenced by DoReadFPU(), DoWriteFPU(), ReadAllRegisterValues(), ReadFPU(), ReadRegister(), RegisterContextDarwin_riscv32(), RegisterContextDarwin_riscv32_Mach::SetRegisterDataFrom_LC_THREAD(), WriteAllRegisterValues(), WriteFPU(), and WriteRegister().
fpr_errs
int RegisterContextDarwin_riscv32::fpr_errs[2] protected
Definition at line 153 of file RegisterContextDarwin_riscv32.h.
Referenced by GetError(), RegisterContextDarwin_riscv32(), and SetError().
gpr
GPR RegisterContextDarwin_riscv32::gpr protected
Definition at line 148 of file RegisterContextDarwin_riscv32.h.
Referenced by DoReadGPR(), RegisterContextDarwin_riscv32_Mach::DoReadGPR(), DoWriteGPR(), RegisterContextDarwin_riscv32_Mach::DoWriteGPR(), LogGPR(), ReadAllRegisterValues(), ReadGPR(), ReadRegister(), RegisterContextDarwin_riscv32(), RegisterContextDarwin_riscv32_Mach::SetRegisterDataFrom_LC_THREAD(), WriteAllRegisterValues(), WriteGPR(), and WriteRegister().
gpr_errs
int RegisterContextDarwin_riscv32::gpr_errs[2] protected
Definition at line 152 of file RegisterContextDarwin_riscv32.h.
Referenced by GetError(), RegisterContextDarwin_riscv32(), and SetError().
The documentation for this class was generated from the following files:
RegisterContextDarwin_riscv32.h
RegisterContextDarwin_riscv32.cpp