LLDB: lldb::SBThread Class Reference
lldb::SBThread Class Reference
#include <SBThread.h>
Public Types
enum {
eBroadcastBitStackChanged = (1 << 0) , eBroadcastBitThreadSuspended = (1 << 1) , eBroadcastBitThreadResumed = (1 << 2) , eBroadcastBitSelectedFrameChanged = (1 << 3) ,
eBroadcastBitThreadSelected = (1 << 4)
}
Public Member Functions
SBThread ()
SBThread (const lldb::SBThread &thread)
~SBThread ()
lldb::SBQueue GetQueue () const
operator bool () const
bool IsValid () const
void Clear ()
lldb::StopReason GetStopReason ()
size_t GetStopReasonDataCount ()
Get the number of words associated with the stop reason.
uint64_t GetStopReasonDataAtIndex (uint32_t idx)
Get information associated with a stop reason.
bool GetStopReasonExtendedInfoAsJSON (lldb::SBStream &stream)
SBThreadCollection GetStopReasonExtendedBacktraces (InstrumentationRuntimeType type)
bool GetStopDescription (lldb::SBStream &stream) const
Gets a human-readable description of why the thread stopped.
size_t GetStopDescription (char *dst_or_null, size_t dst_len)
SBValue GetStopReturnValue ()
lldb::tid_t GetThreadID () const
uint32_t GetIndexID () const
const char * GetName () const
const char * GetQueueName () const
lldb::queue_id_t GetQueueID () const
bool GetInfoItemByPathAsString (const char *path, SBStream &strm)
void StepOver (lldb::RunMode stop_other_threads=lldb::eOnlyDuringStepping)
void StepOver (lldb::RunMode stop_other_threads, SBError &error)
void StepInto (lldb::RunMode stop_other_threads=lldb::eOnlyDuringStepping)
void StepInto (const char *target_name, lldb::RunMode stop_other_threads=lldb::eOnlyDuringStepping)
void StepInto (const char *target_name, uint32_t end_line, SBError &error, lldb::RunMode stop_other_threads=lldb::eOnlyDuringStepping)
void StepOut ()
void StepOut (SBError &error)
void StepOutOfFrame (SBFrame &frame)
void StepOutOfFrame (SBFrame &frame, SBError &error)
void StepInstruction (bool step_over)
void StepInstruction (bool step_over, SBError &error)
SBError StepOverUntil (lldb::SBFrame &frame, lldb::SBFileSpec &file_spec, uint32_t line)
SBError StepUsingScriptedThreadPlan (const char *script_class_name)
SBError StepUsingScriptedThreadPlan (const char *script_class_name, bool resume_immediately)
SBError StepUsingScriptedThreadPlan (const char *script_class_name, lldb::SBStructuredData &args_data, bool resume_immediately)
SBError JumpToLine (lldb::SBFileSpec &file_spec, uint32_t line)
void RunToAddress (lldb::addr_t addr)
void RunToAddress (lldb::addr_t addr, SBError &error)
SBError ReturnFromFrame (SBFrame &frame, SBValue &return_value)
SBError UnwindInnermostExpression ()
bool Suspend ()
LLDB currently supports process centric debugging which means when any thread in a process stops, all other threads are stopped.
bool Suspend (SBError &error)
bool Resume ()
bool Resume (SBError &error)
bool IsSuspended ()
bool IsStopped ()
uint32_t GetNumFrames ()
lldb::SBFrame GetFrameAtIndex (uint32_t idx)
lldb::SBFrameList GetFrames () const
lldb::SBFrame GetSelectedFrame ()
lldb::SBFrame SetSelectedFrame (uint32_t frame_idx)
lldb::SBProcess GetProcess ()
const lldb::SBThread & operator= (const lldb::SBThread &rhs)
bool operator== (const lldb::SBThread &rhs) const
bool operator!= (const lldb::SBThread &rhs) const
bool GetDescription (lldb::SBStream &description) const
bool GetDescription (lldb::SBStream &description, bool stop_format) const
SBError GetDescriptionWithFormat (const SBFormat &format, SBStream &output)
Similar to GetDescription() but the format of the description can be configured via the format parameter.
bool GetStatus (lldb::SBStream &status) const
SBThread GetExtendedBacktraceThread (const char *type)
uint32_t GetExtendedBacktraceOriginatingIndexID ()
SBValue GetCurrentException ()
SBThread GetCurrentExceptionBacktrace ()
bool SafeToCallFunctions ()
SBValue GetSiginfo ()
Static Public Member Functions
static const char * GetBroadcasterClassName ()
static bool EventIsThreadEvent (const SBEvent &event)
static SBFrame GetStackFrameFromEvent (const SBEvent &event)
static SBThread GetThreadFromEvent (const SBEvent &event)
Private Member Functions
SBThread (const lldb::ThreadSP &lldb_object_sp)
void SetThread (const lldb::ThreadSP &lldb_object_sp)
lldb::ThreadSP GetSP () const
lldb_private::Thread * operator-> ()
lldb_private::Thread * get ()
Private Attributes
lldb::ExecutionContextRefSP m_opaque_sp
Friends
class SBBreakpoint
class SBBreakpointLocation
class SBBreakpointCallbackBaton
class SBSaveCoreOptions
class SBExecutionContext
class SBFrame
class SBFrameList
class SBProcess
class SBDebugger
class SBValue
class lldb_private::QueueImpl
class SBQueueItem
class SBThreadCollection
class SBThreadPlan
class SBTrace
class lldb_private::ScriptInterpreter
class lldb_private::python::SWIGBridge
Detailed Description
Definition at line 26 of file SBThread.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
eBroadcastBitStackChanged
eBroadcastBitThreadSuspended
eBroadcastBitThreadResumed
eBroadcastBitSelectedFrameChanged
eBroadcastBitThreadSelected
Definition at line 28 of file SBThread.h.
Constructor & Destructor Documentation
SBThread() [1/3]
SBThread::SBThread ()
Definition at line 61 of file SBThread.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by GetCurrentExceptionBacktrace(), GetExtendedBacktraceThread(), GetThreadFromEvent(), lldb_private::python::SWIGBridge, operator!=(), operator=(), operator==(), SBThread(), and ~SBThread().
SBThread() [2/3]
SBThread::SBThread (const lldb::SBThread & thread)
Definition at line 70 of file SBThread.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBThread().
~SBThread()
SBThread::~SBThread () default
References Clear(), lldb::eOnlyDuringStepping, error(), EventIsThreadEvent(), GetCurrentException(), GetCurrentExceptionBacktrace(), GetDescription(), GetDescriptionWithFormat(), GetExtendedBacktraceOriginatingIndexID(), GetExtendedBacktraceThread(), GetFrameAtIndex(), GetFrames(), GetIndexID(), GetInfoItemByPathAsString(), GetNumFrames(), GetProcess(), GetQueue(), GetQueueID(), GetQueueName(), GetSelectedFrame(), GetSiginfo(), GetStackFrameFromEvent(), GetStatus(), GetStopDescription(), GetStopReason(), GetStopReasonDataAtIndex(), GetStopReasonDataCount(), GetStopReasonExtendedBacktraces(), GetStopReasonExtendedInfoAsJSON(), GetStopReturnValue(), GetThreadFromEvent(), GetThreadID(), IsStopped(), IsSuspended(), IsValid(), JumpToLine(), operator!=(), operator=(), operator==(), Resume(), ReturnFromFrame(), RunToAddress(), SafeToCallFunctions(), SBFrame, SBThread(), SBThreadCollection, SBValue, SetSelectedFrame(), StepInstruction(), StepInto(), StepOut(), StepOutOfFrame(), StepOver(), StepOverUntil(), StepUsingScriptedThreadPlan(), Suspend(), and UnwindInnermostExpression().
SBThread() [3/3]
SBThread::SBThread (const lldb::ThreadSP & lldb_object_sp) private
Definition at line 65 of file SBThread.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Member Function Documentation
Clear()
void SBThread::Clear ()
Definition at line 130 of file SBThread.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBThread().
EventIsThreadEvent()
bool SBThread::EventIsThreadEvent (const SBEvent & event) static
Definition at line 1184 of file SBThread.cpp.
References lldb::SBEvent::get(), lldb_private::Thread::ThreadEventData::GetEventDataFromEvent(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBThread().
get()
lldb_private::Thread * SBThread::get () private
Definition at line 1401 of file SBThread.cpp.
References m_opaque_sp.
Referenced by operator->(), lldb::SBThreadPlan::SBThreadPlan(), and lldb::SBThreadPlan::SBThreadPlan().
GetBroadcasterClassName()
const char * SBThread::GetBroadcasterClassName () static
Definition at line 54 of file SBThread.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::Thread::GetStaticBroadcasterClass(), and LLDB_INSTRUMENT.
GetCurrentException()
SBValue SBThread::GetCurrentException ()
Definition at line 1345 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and SBValue.
Referenced by ~SBThread().
GetCurrentExceptionBacktrace()
SBThread SBThread::GetCurrentExceptionBacktrace ()
Definition at line 1362 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and SBThread().
Referenced by ~SBThread().
GetDescription() [1/2]
bool SBThread::GetDescription (lldb::SBStream & description) const
Definition at line 1237 of file SBThread.cpp.
References GetDescription(), and LLDB_INSTRUMENT_VA.
Referenced by GetDescription(), and ~SBThread().
GetDescription() [2/2]
bool SBThread::GetDescription (lldb::SBStream & description, bool stop_format) const
Definition at line 1243 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_INVALID_THREAD_ID, LLDB_LOG_ERROR, m_opaque_sp, lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
GetDescriptionWithFormat()
SBError SBThread::GetDescriptionWithFormat (const SBFormat & format, SBStream & output)
Similar to GetDescription() but the format of the description can be configured via the format parameter.
See https://lldb.llvm.org/use/formatting.html for more information on format strings.
Parameters
[in] format The format to use for generating the description.
[out] output The stream where the description will be written to.
Returns
An error object with an error message in case of failures.
Definition at line 1264 of file SBThread.cpp.
References lldb_private::API, error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb::SBFormat::GetFormatEntrySP(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INVALID_THREAD_ID, LLDB_LOG_ERROR, m_opaque_sp, and lldb::SBStream::ref().
Referenced by ~SBThread().
GetExtendedBacktraceOriginatingIndexID()
uint32_t SBThread::GetExtendedBacktraceOriginatingIndexID ()
Definition at line 1329 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_INVALID_INDEX32, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBThread().
GetExtendedBacktraceThread()
SBThread SBThread::GetExtendedBacktraceThread (const char * type)
Definition at line 1295 of file SBThread.cpp.
References lldb_private::ThreadCollection::AddThread(), lldb_private::API, lldb_private::SystemRuntime::GetExtendedBacktraceThread(), lldb_private::Process::GetExtendedThreadList(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), lldb_private::Process::GetSystemRuntime(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, SBThread(), and SetThread().
Referenced by ~SBThread().
GetFrameAtIndex()
SBFrame SBThread::GetFrameAtIndex (uint32_t idx)
Definition at line 1101 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, SBFrame, and lldb::SBFrame::SetFrameSP().
Referenced by ~SBThread().
GetFrames()
lldb::SBFrameList SBThread::GetFrames () const
Definition at line 1120 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, SBFrameList, and lldb::SBFrameList::SetFrameList().
Referenced by ~SBThread().
GetIndexID()
uint32_t SBThread::GetIndexID () const
Definition at line 335 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_INVALID_INDEX32, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBThread().
GetInfoItemByPathAsString()
bool SBThread::GetInfoItemByPathAsString (const char * path, SBStream & strm)
Definition at line 401 of file SBThread.cpp.
References lldb_private::API, lldb::eStructuredDataTypeBoolean, lldb::eStructuredDataTypeFloat, lldb::eStructuredDataTypeInteger, lldb::eStructuredDataTypeNull, lldb::eStructuredDataTypeString, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and lldb::SBStream::ref().
Referenced by ~SBThread().
GetName()
const char * SBThread::GetName () const
Definition at line 351 of file SBThread.cpp.
References lldb_private::API, lldb_private::ConstString::GetCString(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
GetNumFrames()
uint32_t SBThread::GetNumFrames ()
Definition at line 1085 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBThread().
GetProcess()
SBProcess SBThread::GetProcess ()
Definition at line 1065 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, SBProcess, and lldb::SBProcess::SetSP().
Referenced by ~SBThread().
GetQueue()
lldb::SBQueue SBThread::GetQueue () const
Definition at line 89 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, lldb::SBQueue, and lldb::SBQueue::SetQueue().
Referenced by ~SBThread().
GetQueueID()
lldb::queue_id_t SBThread::GetQueueID () const
Definition at line 383 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_INVALID_QUEUE_ID, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBThread().
GetQueueName()
const char * SBThread::GetQueueName () const
Definition at line 367 of file SBThread.cpp.
References lldb_private::API, lldb_private::ConstString::GetCString(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBThread().
GetSelectedFrame()
lldb::SBFrame SBThread::GetSelectedFrame ()
Definition at line 1140 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, SBFrame, SelectMostRelevantFrame, and lldb::SBFrame::SetFrameSP().
Referenced by ~SBThread().
GetSiginfo()
SBValue SBThread::GetSiginfo ()
Definition at line 1405 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and SBValue.
Referenced by ~SBThread().
GetSP()
lldb::ThreadSP SBThread::GetSP () const private
Definition at line 1395 of file SBThread.cpp.
References m_opaque_sp.
Referenced by lldb_private::python::SWIGBridge.
GetStackFrameFromEvent()
SBFrame SBThread::GetStackFrameFromEvent (const SBEvent & event) static
Definition at line 1190 of file SBThread.cpp.
References lldb::SBEvent::get(), lldb_private::Thread::ThreadEventData::GetStackFrameFromEvent(), LLDB_INSTRUMENT_VA, and SBFrame.
Referenced by ~SBThread().
GetStatus()
bool SBThread::GetStatus (lldb::SBStream & status) const
Definition at line 1216 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
Referenced by ~SBThread().
GetStopDescription() [1/2]
size_t SBThread::GetStopDescription (char * dst_or_null, size_t dst_len)
Definition at line 266 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
GetStopDescription() [2/2]
bool SBThread::GetStopDescription (lldb::SBStream & stream) const
Gets a human-readable description of why the thread stopped.
Parameters
stream Output stream to receive the stop description text
Returns
true if obtained and written to the stream,
Definition at line 243 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
Referenced by ~SBThread().
GetStopReason()
StopReason SBThread::GetStopReason ()
Definition at line 136 of file SBThread.cpp.
References lldb_private::API, lldb::eStopReasonInvalid, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBThread().
GetStopReasonDataAtIndex()
uint64_t SBThread::GetStopReasonDataAtIndex (uint32_t idx)
Get information associated with a stop reason.
Breakpoint stop reasons will have data that consists of pairs of breakpoint IDs followed by the breakpoint location IDs (they always come in pairs).
Stop Reason Count Data Type ======================== ===== ========================================= eStopReasonNone 0 eStopReasonTrace 0 eStopReasonBreakpoint N duple: {breakpoint id, location id} eStopReasonWatchpoint 1 watchpoint id eStopReasonSignal 1 unix signal number eStopReasonException N exception data eStopReasonExec 0 eStopReasonFork 1 pid of the child process eStopReasonVFork 1 pid of the child process eStopReasonVForkDone 0 eStopReasonPlanComplete 0
Definition at line 171 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBThread().
GetStopReasonDataCount()
size_t SBThread::GetStopReasonDataCount ()
Get the number of words associated with the stop reason.
See also GetStopReasonDataAtIndex().
Definition at line 153 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBThread().
GetStopReasonExtendedBacktraces()
SBThreadCollection SBThread::GetStopReasonExtendedBacktraces (InstrumentationRuntimeType type)
Definition at line 216 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and SBThreadCollection.
Referenced by ~SBThread().
GetStopReasonExtendedInfoAsJSON()
bool SBThread::GetStopReasonExtendedInfoAsJSON (lldb::SBStream & stream)
Definition at line 190 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and lldb::SBStream::ref().
Referenced by ~SBThread().
GetStopReturnValue()
SBValue SBThread::GetStopReturnValue ()
Definition at line 294 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::StopInfo::GetReturnValueObject(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and SBValue.
Referenced by ~SBThread().
GetThreadFromEvent()
SBThread SBThread::GetThreadFromEvent (const SBEvent & event) static
Definition at line 1196 of file SBThread.cpp.
References lldb::SBEvent::get(), lldb_private::Thread::ThreadEventData::GetThreadFromEvent(), LLDB_INSTRUMENT_VA, and SBThread().
Referenced by ~SBThread().
GetThreadID()
lldb::tid_t SBThread::GetThreadID () const
Definition at line 319 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_INVALID_THREAD_ID, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by StepOutOfFrame(), and ~SBThread().
IsStopped()
bool SBThread::IsStopped ()
Definition at line 1050 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and lldb_private::StateIsStoppedState().
Referenced by ~SBThread().
IsSuspended()
bool SBThread::IsSuspended ()
Definition at line 1035 of file SBThread.cpp.
References lldb_private::API, lldb::eStateSuspended, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBThread().
IsValid()
bool SBThread::IsValid () const
Definition at line 111 of file SBThread.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBThread().
JumpToLine()
SBError SBThread::JumpToLine (lldb::SBFileSpec & file_spec, uint32_t line)
Definition at line 920 of file SBThread.cpp.
References lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, m_opaque_sp, lldb::SBFileSpec::ref(), and lldb::SBError::SetError().
Referenced by ~SBThread().
operator bool()
SBThread::operator bool () const explicit
Definition at line 115 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
operator!=()
bool SBThread::operator!= (const lldb::SBThread & rhs) const
Definition at line 1209 of file SBThread.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBThread().
Referenced by ~SBThread().
operator->()
lldb_private::Thread * SBThread::operator-> () private
Definition at line 1397 of file SBThread.cpp.
References get().
operator=()
const lldb::SBThread & SBThread::operator= (const lldb::SBThread & rhs)
Definition at line 78 of file SBThread.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBThread().
Referenced by ~SBThread().
operator==()
bool SBThread::operator== (const lldb::SBThread & rhs) const
Definition at line 1202 of file SBThread.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBThread().
Referenced by ~SBThread().
Resume() [1/2]
bool SBThread::Resume ()
Definition at line 1007 of file SBThread.cpp.
References error(), LLDB_INSTRUMENT_VA, and Resume().
Referenced by Resume(), and ~SBThread().
Resume() [2/2]
bool SBThread::Resume (SBError & error)
Definition at line 1014 of file SBThread.cpp.
References lldb_private::API, error(), lldb::eStateRunning, lldb_private::Status::FromErrorString(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
ReturnFromFrame()
SBError SBThread::ReturnFromFrame (SBFrame & frame, SBValue & return_value)
Definition at line 942 of file SBThread.cpp.
References lldb_private::Status::FromError(), lldb::SBFrame::GetFrameSP(), lldb::SBValue::GetSP(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, m_opaque_sp, SBFrame, SBValue, and lldb::SBError::SetError().
Referenced by ~SBThread().
RunToAddress() [1/2]
void SBThread::RunToAddress (lldb::addr_t addr)
Definition at line 705 of file SBThread.cpp.
References error(), LLDB_INSTRUMENT_VA, and RunToAddress().
Referenced by RunToAddress(), and ~SBThread().
RunToAddress() [2/2]
void SBThread::RunToAddress (lldb::addr_t addr, SBError & error)
Definition at line 712 of file SBThread.cpp.
References lldb_private::Status::AsCString(), error(), lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, m_opaque_sp, ResumeNewPlan(), and lldb_private::Status::Success().
SafeToCallFunctions()
bool SBThread::SafeToCallFunctions ()
Definition at line 1379 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBThread().
SetSelectedFrame()
lldb::SBFrame SBThread::SetSelectedFrame (uint32_t frame_idx)
Definition at line 1160 of file SBThread.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, SBFrame, and lldb::SBFrame::SetFrameSP().
Referenced by ~SBThread().
SetThread()
void SBThread::SetThread (const lldb::ThreadSP & lldb_object_sp) private
Definition at line 315 of file SBThread.cpp.
References m_opaque_sp.
Referenced by lldb::SBProcess::CreateOSPluginThread(), lldb::SBQueueItem::GetExtendedBacktraceThread(), GetExtendedBacktraceThread(), lldb::SBProcess::GetSelectedThread(), lldb::SBExecutionContext::GetThread(), lldb::SBFrameList::GetThread(), lldb::SBValue::GetThread(), lldb::SBProcess::GetThreadAtIndex(), lldb_private::QueueImpl::GetThreadAtIndex(), lldb::SBProcess::GetThreadByID(), lldb::SBProcess::GetThreadByIndexID(), lldb_private::python::SWIGBridge, and lldb::SBBreakpointCallbackBaton::PrivateBreakpointHitCallback().
StepInstruction() [1/2]
void SBThread::StepInstruction (bool step_over)
Definition at line 672 of file SBThread.cpp.
References error(), LLDB_INSTRUMENT_VA, and StepInstruction().
Referenced by StepInstruction(), and ~SBThread().
StepInstruction() [2/2]
void SBThread::StepInstruction (bool step_over, SBError & error)
Definition at line 679 of file SBThread.cpp.
References lldb_private::Status::AsCString(), error(), lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, m_opaque_sp, ResumeNewPlan(), and lldb_private::Status::Success().
StepInto() [1/3]
void SBThread::StepInto (const char * target_name, lldb::RunMode stop_other_threads = lldb::eOnlyDuringStepping)
Definition at line 522 of file SBThread.cpp.
References error(), LLDB_INSTRUMENT_VA, LLDB_INVALID_LINE_NUMBER, and StepInto().
StepInto() [2/3]
void SBThread::StepInto (const char * target_name, uint32_t end_line, SBError & error, lldb::RunMode stop_other_threads = lldb::eOnlyDuringStepping)
Definition at line 530 of file SBThread.cpp.
References lldb_private::Status::AsCString(), lldb_private::eLazyBoolCalculate, error(), lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), lldb_private::SymbolContext::GetAddressRangeFromHereToEndLine(), lldb_private::GetStoppedExecutionContext(), lldb_private::SymbolContext::line_entry, LLDB_INSTRUMENT_VA, LLDB_INVALID_LINE_NUMBER, m_opaque_sp, lldb_private::LineEntry::range, ResumeNewPlan(), and lldb_private::Status::Success().
StepInto() [3/3]
void SBThread::StepInto (lldb::RunMode stop_other_threads = lldb::eOnlyDuringStepping)
Definition at line 516 of file SBThread.cpp.
References LLDB_INSTRUMENT_VA, and StepInto().
Referenced by StepInto(), StepInto(), and ~SBThread().
StepOut() [1/2]
void SBThread::StepOut ()
Definition at line 585 of file SBThread.cpp.
References error(), LLDB_INSTRUMENT_VA, and StepOut().
Referenced by StepOut(), and ~SBThread().
StepOut() [2/2]
void SBThread::StepOut (SBError & error)
Definition at line 592 of file SBThread.cpp.
References lldb_private::Status::AsCString(), lldb_private::eLazyBoolCalculate, error(), lldb_private::eVoteNoOpinion, lldb_private::eVoteYes, lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, m_opaque_sp, ResumeNewPlan(), and lldb_private::Status::Success().
StepOutOfFrame() [1/2]
void SBThread::StepOutOfFrame (SBFrame & frame)
Definition at line 624 of file SBThread.cpp.
References error(), LLDB_INSTRUMENT_VA, SBFrame, and StepOutOfFrame().
Referenced by StepOutOfFrame(), and ~SBThread().
StepOutOfFrame() [2/2]
void SBThread::StepOutOfFrame (SBFrame & frame, SBError & error)
Definition at line 631 of file SBThread.cpp.
References lldb_private::Status::AsCString(), error(), lldb_private::eVoteNoOpinion, lldb_private::eVoteYes, lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), lldb::SBFrame::GetFrameSP(), lldb_private::GetStoppedExecutionContext(), lldb::SBFrame::GetThread(), GetThreadID(), lldb::SBFrame::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, ResumeNewPlan(), SBFrame, and lldb_private::Status::Success().
StepOver() [1/2]
void SBThread::StepOver (lldb::RunMode stop_other_threads, SBError & error)
Definition at line 480 of file SBThread.cpp.
References lldb_private::eLazyBoolCalculate, error(), lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), lldb_private::GetStoppedExecutionContext(), lldb_private::SymbolContext::line_entry, LLDB_INSTRUMENT_VA, m_opaque_sp, and ResumeNewPlan().
StepOver() [2/2]
void SBThread::StepOver (lldb::RunMode stop_other_threads = lldb::eOnlyDuringStepping)
Definition at line 473 of file SBThread.cpp.
References error(), LLDB_INSTRUMENT_VA, and StepOver().
Referenced by StepOver(), and ~SBThread().
StepOverUntil()
SBError SBThread::StepOverUntil (lldb::SBFrame & frame, lldb::SBFileSpec & file_spec, uint32_t line)
Definition at line 744 of file SBThread.cpp.
References lldb_private::Status::AsCString(), lldb_private::SymbolContext::comp_unit, DoNoSelectMostRelevantFrame, lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::SymbolContext::function, lldb_private::LineEntry::GetFile(), lldb::SBFrame::GetFrameSP(), lldb_private::FileSpec::GetPath(), lldb_private::Function::GetRangeContainingLoadAddress(), lldb_private::GetStoppedExecutionContext(), lldb::SBFileSpec::IsValid(), lldb_private::LineEntry::IsValid(), lldb_private::SymbolContext::line_entry, LLDB_INSTRUMENT_VA, LLDB_INVALID_ADDRESS, m_opaque_sp, PATH_MAX, lldb::SBFileSpec::ref(), lldb_private::CompileUnit::ResolveSymbolContext(), ResumeNewPlan(), and lldb_private::Status::Success().
Referenced by ~SBThread().
StepUsingScriptedThreadPlan() [1/3]
SBError SBThread::StepUsingScriptedThreadPlan (const char * script_class_name)
Definition at line 865 of file SBThread.cpp.
References LLDB_INSTRUMENT_VA, and StepUsingScriptedThreadPlan().
Referenced by StepUsingScriptedThreadPlan(), StepUsingScriptedThreadPlan(), and ~SBThread().
StepUsingScriptedThreadPlan() [2/3]
SBError SBThread::StepUsingScriptedThreadPlan (const char * script_class_name, bool resume_immediately)
Definition at line 871 of file SBThread.cpp.
References LLDB_INSTRUMENT_VA, and StepUsingScriptedThreadPlan().
StepUsingScriptedThreadPlan() [3/3]
SBError SBThread::StepUsingScriptedThreadPlan (const char * script_class_name, lldb::SBStructuredData & args_data, bool resume_immediately)
Definition at line 880 of file SBThread.cpp.
References lldb_private::Status::AsCString(), error(), lldb_private::Status::Fail(), lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, lldb::SBStructuredData::m_impl_up, m_opaque_sp, ResumeNewPlan(), and lldb_private::Status::Success().
Suspend() [1/2]
bool SBThread::Suspend ()
LLDB currently supports process centric debugging which means when any thread in a process stops, all other threads are stopped.
The Suspend() call here tells our process to suspend a thread and not let it run when the other threads in a process are allowed to run. So when SBProcess::Continue() is called, any threads that aren't suspended will be allowed to run. If any of the SBThread functions for stepping are called (StepOver, StepInto, StepOut, StepInstruction, RunToAddress), the thread will not be allowed to run and these functions will simply return.
Eventually we plan to add support for thread centric debugging where each thread is controlled individually and each thread would broadcast its state, but we haven't implemented this yet.
Likewise the SBThread::Resume() call will again allow the thread to run when the process is continued.
Suspend() and Resume() functions are not currently reference counted, if anyone has the need for them to be reference counted, please let us know.
Definition at line 981 of file SBThread.cpp.
References error(), LLDB_INSTRUMENT_VA, and Suspend().
Referenced by Suspend(), and ~SBThread().
Suspend() [2/2]
bool SBThread::Suspend (SBError & error)
Definition at line 988 of file SBThread.cpp.
References error(), lldb::eStateSuspended, lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
UnwindInnermostExpression()
SBError SBThread::UnwindInnermostExpression ()
Definition at line 961 of file SBThread.cpp.
References lldb_private::Status::FromError(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, m_opaque_sp, lldb::SBError::SetError(), and lldb::SBError::Success().
Referenced by ~SBThread().
Friends And Related Symbol Documentation
lldb_private::python::SWIGBridge
friend class lldb_private::python::SWIGBridge friend
Definition at line 260 of file SBThread.h.
References GetSP(), SBThread(), and SetThread().
lldb_private::QueueImpl
friend class lldb_private::QueueImpl friend
Definition at line 253 of file SBThread.h.
lldb_private::ScriptInterpreter
friend class lldb_private::ScriptInterpreter friend
Definition at line 259 of file SBThread.h.
SBBreakpoint
friend class SBBreakpoint friend
Definition at line 243 of file SBThread.h.
References SBBreakpoint.
Referenced by SBBreakpoint.
SBBreakpointCallbackBaton
friend class SBBreakpointCallbackBaton friend
Definition at line 245 of file SBThread.h.
References SBBreakpointCallbackBaton.
Referenced by SBBreakpointCallbackBaton.
SBBreakpointLocation
friend class SBBreakpointLocation friend
Definition at line 244 of file SBThread.h.
References SBBreakpointLocation.
Referenced by SBBreakpointLocation.
SBDebugger
friend class SBDebugger friend
Definition at line 251 of file SBThread.h.
References SBDebugger.
Referenced by SBDebugger.
SBExecutionContext
friend class SBExecutionContext friend
Definition at line 247 of file SBThread.h.
References SBExecutionContext.
Referenced by SBExecutionContext.
SBFrame
friend class SBFrame friend
Definition at line 248 of file SBThread.h.
References SBFrame.
Referenced by GetFrameAtIndex(), GetSelectedFrame(), GetStackFrameFromEvent(), ReturnFromFrame(), SBFrame, SetSelectedFrame(), StepOutOfFrame(), StepOutOfFrame(), and ~SBThread().
SBFrameList
friend class SBFrameList friend
Definition at line 249 of file SBThread.h.
References SBFrameList.
Referenced by GetFrames(), and SBFrameList.
SBProcess
friend class SBProcess friend
Definition at line 250 of file SBThread.h.
References SBProcess.
Referenced by GetProcess(), and SBProcess.
SBQueueItem
friend class SBQueueItem friend
Definition at line 254 of file SBThread.h.
References SBQueueItem.
Referenced by SBQueueItem.
SBSaveCoreOptions
friend class SBSaveCoreOptions friend
Definition at line 246 of file SBThread.h.
References SBSaveCoreOptions.
Referenced by SBSaveCoreOptions.
SBThreadCollection
friend class SBThreadCollection friend
Definition at line 255 of file SBThread.h.
References SBThreadCollection.
Referenced by GetStopReasonExtendedBacktraces(), SBThreadCollection, and ~SBThread().
SBThreadPlan
friend class SBThreadPlan friend
Definition at line 256 of file SBThread.h.
References SBThreadPlan.
Referenced by SBThreadPlan.
SBTrace
friend class SBTrace friend
Definition at line 257 of file SBThread.h.
References SBTrace.
Referenced by SBTrace.
SBValue
friend class SBValue friend
Definition at line 252 of file SBThread.h.
References SBValue.
Referenced by GetCurrentException(), GetSiginfo(), GetStopReturnValue(), ReturnFromFrame(), SBValue, and ~SBThread().
Member Data Documentation
m_opaque_sp
lldb::ExecutionContextRefSP lldb::SBThread::m_opaque_sp private
Definition at line 268 of file SBThread.h.
Referenced by Clear(), get(), GetCurrentException(), GetCurrentExceptionBacktrace(), GetDescription(), GetDescriptionWithFormat(), GetExtendedBacktraceOriginatingIndexID(), GetExtendedBacktraceThread(), GetFrameAtIndex(), GetFrames(), GetIndexID(), GetInfoItemByPathAsString(), GetName(), GetNumFrames(), GetProcess(), GetQueue(), GetQueueID(), GetQueueName(), GetSelectedFrame(), GetSiginfo(), GetSP(), GetStatus(), GetStopDescription(), GetStopDescription(), GetStopReason(), GetStopReasonDataAtIndex(), GetStopReasonDataCount(), GetStopReasonExtendedBacktraces(), GetStopReasonExtendedInfoAsJSON(), GetStopReturnValue(), GetThreadID(), IsStopped(), IsSuspended(), JumpToLine(), operator bool(), operator!=(), operator=(), operator==(), Resume(), ReturnFromFrame(), RunToAddress(), SafeToCallFunctions(), SBThread(), SBThread(), SBThread(), SetSelectedFrame(), SetThread(), StepInstruction(), StepInto(), StepOut(), StepOutOfFrame(), StepOver(), StepOverUntil(), StepUsingScriptedThreadPlan(), Suspend(), and UnwindInnermostExpression().
The documentation for this class was generated from the following files:
SBThread.h
SBThread.cpp