LLDB: lldb_private::TypeImpl Class Reference
lldb_private::TypeImpl Class Reference
#include <Type.h>
Public Member Functions
TypeImpl ()=default
~TypeImpl ()=default
TypeImpl (const lldb::TypeSP &type_sp)
TypeImpl (const CompilerType &compiler_type)
TypeImpl (const lldb::TypeSP &type_sp, const CompilerType &dynamic)
TypeImpl (const CompilerType &compiler_type, const CompilerType &dynamic)
void SetType (const lldb::TypeSP &type_sp)
void SetType (const CompilerType &compiler_type)
void SetType (const lldb::TypeSP &type_sp, const CompilerType &dynamic)
void SetType (const CompilerType &compiler_type, const CompilerType &dynamic)
bool operator== (const TypeImpl &rhs) const
bool operator!= (const TypeImpl &rhs) const
bool IsValid () const
operator bool () const
void Clear ()
lldb::ModuleSP GetModule () const
ConstString GetName () const
ConstString GetDisplayTypeName () const
TypeImpl GetPointerType () const
TypeImpl GetPointeeType () const
TypeImpl GetReferenceType () const
TypeImpl GetTypedefedType () const
TypeImpl GetDereferencedType () const
TypeImpl GetUnqualifiedType () const
TypeImpl GetCanonicalType () const
CompilerType GetCompilerType (bool prefer_dynamic)
CompilerType::TypeSystemSPWrapper GetTypeSystem (bool prefer_dynamic)
bool GetDescription (lldb_private::Stream &strm, lldb::DescriptionLevel description_level)
CompilerType FindDirectNestedType (llvm::StringRef name)
Private Member Functions
bool CheckModule (lldb::ModuleSP &module_sp) const
bool CheckExeModule (lldb::ModuleSP &module_sp) const
bool CheckModuleCommon (const lldb::ModuleWP &input_module_wp, lldb::ModuleSP &module_sp) const
Private Attributes
lldb::ModuleWP m_module_wp
lldb::ModuleWP m_exe_module_wp
CompilerType m_static_type
CompilerType m_dynamic_type
Detailed Description
Definition at line 624 of file Type.h.
Constructor & Destructor Documentation
TypeImpl() [1/5]
lldb_private::TypeImpl::TypeImpl () default
Referenced by GetCanonicalType(), GetDereferencedType(), GetPointeeType(), GetPointerType(), GetReferenceType(), GetTypedefedType(), GetUnqualifiedType(), operator!=(), operator==(), and ~TypeImpl().
~TypeImpl()
lldb_private::TypeImpl::~TypeImpl () default
References TypeImpl().
TypeImpl() [2/5]
TypeImpl::TypeImpl (const lldb::TypeSP & type_sp)
Definition at line 943 of file Type.cpp.
References m_dynamic_type, m_module_wp, m_static_type, and SetType().
TypeImpl() [3/5]
TypeImpl::TypeImpl (const CompilerType & compiler_type)
Definition at line 948 of file Type.cpp.
References m_dynamic_type, m_module_wp, m_static_type, and SetType().
TypeImpl() [4/5]
TypeImpl::TypeImpl (const lldb::TypeSP & type_sp, const CompilerType & dynamic)
Definition at line 953 of file Type.cpp.
References m_dynamic_type, m_module_wp, m_static_type, and SetType().
TypeImpl() [5/5]
TypeImpl::TypeImpl (const CompilerType & compiler_type, const CompilerType & dynamic)
Definition at line 958 of file Type.cpp.
References m_dynamic_type, m_module_wp, m_static_type, and SetType().
Member Function Documentation
CheckExeModule()
bool TypeImpl::CheckExeModule (lldb::ModuleSP & module_sp) const private
Definition at line 997 of file Type.cpp.
References CheckModuleCommon(), and m_exe_module_wp.
Referenced by GetModule().
CheckModule()
bool TypeImpl::CheckModule (lldb::ModuleSP & module_sp) const private
Definition at line 993 of file Type.cpp.
References CheckModuleCommon(), and m_module_wp.
Referenced by GetCanonicalType(), GetCompilerType(), GetDereferencedType(), GetDescription(), GetDisplayTypeName(), GetName(), GetPointeeType(), GetPointerType(), GetReferenceType(), GetTypedefedType(), GetTypeSystem(), GetUnqualifiedType(), and IsValid().
CheckModuleCommon()
bool TypeImpl::CheckModuleCommon (const lldb::ModuleWP & input_module_wp, lldb::ModuleSP & module_sp) const private
Definition at line 1001 of file Type.cpp.
Referenced by CheckExeModule(), and CheckModule().
Clear()
void TypeImpl::Clear ()
Definition at line 1049 of file Type.cpp.
References m_dynamic_type, m_module_wp, and m_static_type.
FindDirectNestedType()
CompilerType TypeImpl::FindDirectNestedType (llvm::StringRef name)
Definition at line 1206 of file Type.cpp.
References GetCompilerType(), and lldb_private::CompilerType::GetDirectNestedTypeWithName().
GetCanonicalType()
TypeImpl TypeImpl::GetCanonicalType () const
Definition at line 1154 of file Type.cpp.
References CheckModule(), m_dynamic_type, m_static_type, and TypeImpl().
GetCompilerType()
CompilerType TypeImpl::GetCompilerType (bool prefer_dynamic)
Definition at line 1166 of file Type.cpp.
References CheckModule(), m_dynamic_type, and m_static_type.
Referenced by FindDirectNestedType().
GetDereferencedType()
TypeImpl TypeImpl::GetDereferencedType () const
Definition at line 1130 of file Type.cpp.
References CheckModule(), m_dynamic_type, m_static_type, and TypeImpl().
GetDescription()
bool TypeImpl::GetDescription (lldb_private::Stream & strm, lldb::DescriptionLevel description_level)
Definition at line 1190 of file Type.cpp.
References CheckModule(), m_dynamic_type, m_static_type, lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
GetDisplayTypeName()
ConstString TypeImpl::GetDisplayTypeName () const
Definition at line 1072 of file Type.cpp.
References CheckModule(), m_dynamic_type, and m_static_type.
GetModule()
ModuleSP TypeImpl::GetModule () const
Definition at line 1055 of file Type.cpp.
References CheckExeModule().
GetName()
ConstString TypeImpl::GetName () const
Definition at line 1062 of file Type.cpp.
References CheckModule(), m_dynamic_type, and m_static_type.
GetPointeeType()
TypeImpl TypeImpl::GetPointeeType () const
Definition at line 1094 of file Type.cpp.
References CheckModule(), m_dynamic_type, m_static_type, and TypeImpl().
GetPointerType()
TypeImpl TypeImpl::GetPointerType () const
Definition at line 1082 of file Type.cpp.
References CheckModule(), m_dynamic_type, m_static_type, and TypeImpl().
GetReferenceType()
TypeImpl TypeImpl::GetReferenceType () const
Definition at line 1106 of file Type.cpp.
References CheckModule(), m_dynamic_type, m_static_type, and TypeImpl().
GetTypedefedType()
TypeImpl TypeImpl::GetTypedefedType () const
Definition at line 1118 of file Type.cpp.
References CheckModule(), m_dynamic_type, m_static_type, and TypeImpl().
GetTypeSystem()
CompilerType::TypeSystemSPWrapper TypeImpl::GetTypeSystem (bool prefer_dynamic)
Definition at line 1178 of file Type.cpp.
References CheckModule(), m_dynamic_type, and m_static_type.
GetUnqualifiedType()
TypeImpl TypeImpl::GetUnqualifiedType () const
Definition at line 1142 of file Type.cpp.
References CheckModule(), m_dynamic_type, m_static_type, and TypeImpl().
IsValid()
bool TypeImpl::IsValid () const
Definition at line 1039 of file Type.cpp.
References CheckModule(), m_dynamic_type, and m_static_type.
Referenced by operator bool().
operator bool()
TypeImpl::operator bool () const explicit
Definition at line 1047 of file Type.cpp.
References IsValid().
operator!=()
bool TypeImpl::operator!= (const TypeImpl & rhs) const
Definition at line 1035 of file Type.cpp.
References TypeImpl().
operator==()
bool TypeImpl::operator== (const TypeImpl & rhs) const
Definition at line 1030 of file Type.cpp.
References m_dynamic_type, m_static_type, and TypeImpl().
SetType() [1/4]
void TypeImpl::SetType (const CompilerType & compiler_type)
Definition at line 975 of file Type.cpp.
References m_module_wp, and m_static_type.
SetType() [2/4]
void TypeImpl::SetType (const CompilerType & compiler_type, const CompilerType & dynamic)
Definition at line 986 of file Type.cpp.
References m_dynamic_type, m_module_wp, and m_static_type.
SetType() [3/4]
void TypeImpl::SetType (const lldb::TypeSP & type_sp)
Definition at line 964 of file Type.cpp.
References m_exe_module_wp, m_module_wp, and m_static_type.
Referenced by lldb::SBFunction::GetType(), SetType(), TypeImpl(), TypeImpl(), TypeImpl(), and TypeImpl().
SetType() [4/4]
void TypeImpl::SetType (const lldb::TypeSP & type_sp, const CompilerType & dynamic)
Definition at line 980 of file Type.cpp.
References m_dynamic_type, and SetType().
Member Data Documentation
m_dynamic_type
CompilerType lldb_private::TypeImpl::m_dynamic_type private
Definition at line 694 of file Type.h.
Referenced by Clear(), GetCanonicalType(), GetCompilerType(), GetDereferencedType(), GetDescription(), GetDisplayTypeName(), GetName(), GetPointeeType(), GetPointerType(), GetReferenceType(), GetTypedefedType(), GetTypeSystem(), GetUnqualifiedType(), IsValid(), operator==(), SetType(), SetType(), TypeImpl(), TypeImpl(), TypeImpl(), and TypeImpl().
m_exe_module_wp
lldb::ModuleWP lldb_private::TypeImpl::m_exe_module_wp private
Definition at line 692 of file Type.h.
Referenced by CheckExeModule(), and SetType().
m_module_wp
lldb::ModuleWP lldb_private::TypeImpl::m_module_wp private
Definition at line 691 of file Type.h.
Referenced by CheckModule(), Clear(), SetType(), SetType(), SetType(), TypeImpl(), TypeImpl(), TypeImpl(), and TypeImpl().
m_static_type
CompilerType lldb_private::TypeImpl::m_static_type private
Definition at line 693 of file Type.h.
Referenced by Clear(), GetCanonicalType(), GetCompilerType(), GetDereferencedType(), GetDescription(), GetDisplayTypeName(), GetName(), GetPointeeType(), GetPointerType(), GetReferenceType(), GetTypedefedType(), GetTypeSystem(), GetUnqualifiedType(), IsValid(), operator==(), SetType(), SetType(), SetType(), TypeImpl(), TypeImpl(), TypeImpl(), and TypeImpl().
The documentation for this class was generated from the following files:
Type.h
Type.cpp