LLDB: lldb_private::BreakpointIDList Class Reference
lldb_private::BreakpointIDList Class Reference
#include <BreakpointIDList.h>
Public Types
typedef std::vector< BreakpointID > BreakpointIDArray
Public Member Functions
BreakpointIDList ()
virtual ~BreakpointIDList ()
size_t GetSize () const
BreakpointID GetBreakpointIDAtIndex (size_t index) const
bool RemoveBreakpointIDAtIndex (size_t index)
void Clear ()
bool AddBreakpointID (BreakpointID bp_id)
bool Contains (BreakpointID bp_id) const
Static Public Member Functions
static std::pair< llvm::StringRef, llvm::StringRef > SplitIDRangeExpression (llvm::StringRef in_string)
static llvm::Error FindAndReplaceIDRanges (Args &old_args, Target *target, bool allow_locations, BreakpointName::Permissions ::PermissionKinds purpose, Args &new_args)
Private Member Functions
BreakpointIDList (const BreakpointIDList &)=delete
const BreakpointIDList & operator= (const BreakpointIDList &)=delete
Private Attributes
BreakpointIDArray m_breakpoint_ids
Detailed Description
Definition at line 26 of file BreakpointIDList.h.
Member Typedef Documentation
BreakpointIDArray
typedef std::vector<BreakpointID> lldb_private::BreakpointIDList::BreakpointIDArray
Definition at line 29 of file BreakpointIDList.h.
Constructor & Destructor Documentation
BreakpointIDList() [1/2]
BreakpointIDList::BreakpointIDList ()
Definition at line 26 of file BreakpointIDList.cpp.
References m_breakpoint_ids.
Referenced by BreakpointIDList(), and operator=().
~BreakpointIDList()
BreakpointIDList::~BreakpointIDList () virtual default
BreakpointIDList() [2/2]
lldb_private::BreakpointIDList::BreakpointIDList (const BreakpointIDList &) private delete
References BreakpointIDList().
Member Function Documentation
AddBreakpointID()
bool BreakpointIDList::AddBreakpointID (BreakpointID bp_id)
Definition at line 47 of file BreakpointIDList.cpp.
References m_breakpoint_ids.
Referenced by SBBreakpointListImpl::CopyToBreakpointIDList(), lldb_private::Target::CreateBreakpointsFromFile(), CommandObjectBreakpointDelete::DoExecute(), CommandObjectProcessContinue::DoExecute(), and lldb_private::CommandObjectMultiwordBreakpoint::VerifyIDs().
Clear()
void BreakpointIDList::Clear ()
Definition at line 45 of file BreakpointIDList.cpp.
References m_breakpoint_ids.
Contains()
bool BreakpointIDList::Contains (BreakpointID bp_id) const
Definition at line 54 of file BreakpointIDList.cpp.
References m_breakpoint_ids.
Referenced by CommandObjectBreakpointDelete::DoExecute(), and CommandObjectProcessContinue::DoExecute().
FindAndReplaceIDRanges()
llvm::Error BreakpointIDList::FindAndReplaceIDRanges (Args & old_args, Target * target, bool allow_locations, BreakpointName::Permissions ::PermissionKinds purpose, Args & new_args) static
Definition at line 71 of file BreakpointIDList.cpp.
References lldb_private::Args::AppendArgument(), lldb_private::BreakpointList::Breakpoints(), lldb_private::Args::Clear(), error(), lldb_private::Target::FindBreakpointName(), lldb_private::BreakpointList::GetBreakpointAtIndex(), lldb_private::Target::GetBreakpointByID(), lldb_private::Target::GetBreakpointList(), lldb_private::BreakpointID::GetCanonicalReference(), lldb_private::BreakpointLocation::GetID(), lldb_private::Stoppoint::GetID(), lldb_private::Breakpoint::GetLocationAtIndex(), lldb_private::Breakpoint::GetNumLocations(), lldb_private::BreakpointName::GetPermission(), lldb_private::BreakpointList::GetSize(), lldb_private::StreamString::GetString(), lldb_private::BreakpointID::IsRangeIdentifier(), lldb_private::BreakpointID::IsValidIDExpression(), LLDB_INVALID_BREAK_ID, lldb_private::BreakpointID::ParseCanonicalReference(), lldb_private::Args::size(), SplitIDRangeExpression(), and lldb_private::BreakpointID::StringIsBreakpointName().
Referenced by lldb_private::CommandObjectMultiwordBreakpoint::VerifyIDs().
GetBreakpointIDAtIndex()
BreakpointID BreakpointIDList::GetBreakpointIDAtIndex (size_t index) const
Definition at line 32 of file BreakpointIDList.cpp.
References m_breakpoint_ids.
Referenced by lldb::SBTarget::BreakpointsCreateFromFile(), CommandObjectBreakpointCommandDelete::DoExecute(), CommandObjectBreakpointCommandList::DoExecute(), CommandObjectBreakpointDelete::DoExecute(), CommandObjectBreakpointEnable::DoExecute(), CommandObjectBreakpointList::DoExecute(), CommandObjectBreakpointModify::DoExecute(), CommandObjectBreakpointNameAdd::DoExecute(), CommandObjectBreakpointNameDelete::DoExecute(), CommandObjectBreakpointRead::DoExecute(), CommandObjectProcessContinue::DoExecute(), lldb_private::Target::SerializeBreakpointsToFile(), and lldb_private::CommandObjectMultiwordBreakpoint::VerifyIDs().
GetSize()
size_t BreakpointIDList::GetSize () const
Definition at line 30 of file BreakpointIDList.cpp.
References m_breakpoint_ids.
Referenced by lldb::SBTarget::BreakpointsCreateFromFile(), CommandObjectBreakpointCommandDelete::DoExecute(), CommandObjectBreakpointCommandList::DoExecute(), CommandObjectBreakpointDelete::DoExecute(), CommandObjectBreakpointEnable::DoExecute(), CommandObjectBreakpointList::DoExecute(), CommandObjectBreakpointModify::DoExecute(), CommandObjectBreakpointNameAdd::DoExecute(), CommandObjectBreakpointNameDelete::DoExecute(), CommandObjectBreakpointRead::DoExecute(), CommandObjectProcessContinue::DoExecute(), lldb_private::Target::SerializeBreakpointsToFile(), and lldb_private::CommandObjectMultiwordBreakpoint::VerifyIDs().
operator=()
const BreakpointIDList & lldb_private::BreakpointIDList::operator= (const BreakpointIDList &) private delete
References BreakpointIDList().
RemoveBreakpointIDAtIndex()
bool BreakpointIDList::RemoveBreakpointIDAtIndex (size_t index)
Definition at line 37 of file BreakpointIDList.cpp.
References m_breakpoint_ids.
SplitIDRangeExpression()
std::pair< llvm::StringRef, llvm::StringRef > BreakpointIDList::SplitIDRangeExpression (llvm::StringRef in_string) static
Definition at line 277 of file BreakpointIDList.cpp.
References lldb_private::BreakpointID::GetRangeSpecifiers(), and lldb_private::BreakpointID::IsValidIDExpression().
Referenced by FindAndReplaceIDRanges().
Member Data Documentation
m_breakpoint_ids
BreakpointIDArray lldb_private::BreakpointIDList::m_breakpoint_ids private
Definition at line 59 of file BreakpointIDList.h.
Referenced by AddBreakpointID(), BreakpointIDList(), Clear(), Contains(), GetBreakpointIDAtIndex(), GetSize(), and RemoveBreakpointIDAtIndex().
The documentation for this class was generated from the following files:
BreakpointIDList.h
BreakpointIDList.cpp