LLDB: lldb_private::Materializer::Dematerializer Class Reference
lldb_private::Materializer::Dematerializer Class Reference
#include <Materializer.h>
Public Member Functions
Dematerializer ()=default
~Dematerializer ()
void Dematerialize (Status &err, lldb::addr_t frame_top, lldb::addr_t frame_bottom)
void Wipe ()
bool IsValid ()
Private Member Functions
Dematerializer (Materializer &materializer, lldb::StackFrameSP &frame_sp, IRMemoryMap &map, lldb::addr_t process_address)
Private Attributes
Materializer * m_materializer = nullptr
lldb::ThreadWP m_thread_wp
StackID m_stack_id
IRMemoryMap * m_map = nullptr
lldb::addr_t m_process_address = LLDB_INVALID_ADDRESS
Friends
class Materializer
Detailed Description
Definition at line 28 of file Materializer.h.
Constructor & Destructor Documentation
Dematerializer() [1/2]
lldb_private::Materializer::Dematerializer::Dematerializer () default
~Dematerializer()
lldb_private::Materializer::Dematerializer::~Dematerializer () inline
Definition at line 32 of file Materializer.h.
References Wipe().
Dematerializer() [2/2]
lldb_private::Materializer::Dematerializer::Dematerializer (Materializer & materializer, lldb::StackFrameSP & frame_sp, IRMemoryMap & map, lldb::addr_t process_address) inline private
Definition at line 47 of file Materializer.h.
References m_map, m_materializer, m_process_address, m_stack_id, m_thread_wp, and Materializer.
Member Function Documentation
Dematerialize()
void Materializer::Dematerializer::Dematerialize (Status & err, lldb::addr_t frame_top, lldb::addr_t frame_bottom)
Definition at line 1565 of file Materializer.cpp.
References error(), lldb_private::Expressions, lldb_private::Status::FromErrorString(), lldb_private::GetLog(), IsValid(), LLDB_LOGF, m_map, m_materializer, m_process_address, m_stack_id, m_thread_wp, and Wipe().
IsValid()
bool lldb_private::Materializer::Dematerializer::IsValid () inline
Definition at line 39 of file Materializer.h.
References LLDB_INVALID_ADDRESS, m_map, m_materializer, and m_process_address.
Referenced by Dematerialize(), and Wipe().
Wipe()
void Materializer::Dematerializer::Wipe ()
Definition at line 1607 of file Materializer.cpp.
References IsValid(), LLDB_INVALID_ADDRESS, m_map, m_materializer, and m_process_address.
Referenced by Dematerialize(), and ~Dematerializer().
Friends And Related Symbol Documentation
Materializer
friend class Materializer friend
Definition at line 45 of file Materializer.h.
References Materializer.
Referenced by Dematerializer(), and Materializer.
Member Data Documentation
m_map
IRMemoryMap* lldb_private::Materializer::Dematerializer::m_map = nullptr private
Definition at line 60 of file Materializer.h.
Referenced by Dematerialize(), Dematerializer(), IsValid(), and Wipe().
m_materializer
Materializer* lldb_private::Materializer::Dematerializer::m_materializer = nullptr private
Definition at line 57 of file Materializer.h.
Referenced by Dematerialize(), Dematerializer(), IsValid(), and Wipe().
m_process_address
lldb::addr_t lldb_private::Materializer::Dematerializer::m_process_address = LLDB_INVALID_ADDRESS private
Definition at line 61 of file Materializer.h.
Referenced by Dematerialize(), Dematerializer(), IsValid(), and Wipe().
m_stack_id
StackID lldb_private::Materializer::Dematerializer::m_stack_id private
Definition at line 59 of file Materializer.h.
Referenced by Dematerialize(), and Dematerializer().
m_thread_wp
lldb::ThreadWP lldb_private::Materializer::Dematerializer::m_thread_wp private
Definition at line 58 of file Materializer.h.
Referenced by Dematerialize(), and Dematerializer().
The documentation for this class was generated from the following files:
Materializer.h
Materializer.cpp