LLDB: lldb_private::BreakpointResolverFileLine Class Reference
lldb_private::BreakpointResolverFileLine Class Reference
"lldb/Breakpoint/BreakpointResolverFileLine.h" This class sets breakpoints by file and line.
#include <BreakpointResolverFileLine.h>
Public Member Functions
BreakpointResolverFileLine (const lldb::BreakpointSP &bkpt, lldb::addr_t offset, bool skip_prologue, const SourceLocationSpec &location_spec, std::optional< llvm::StringRef > removed_prefix_opt=std::nullopt)
StructuredData::ObjectSP SerializeToStructuredData () override
~BreakpointResolverFileLine () override=default
Searcher::CallbackReturn SearchCallback (SearchFilter &filter, SymbolContext &context, Address *addr) override
lldb::SearchDepth GetDepth () override
void GetDescription (Stream *s) override
Prints a canonical description for the breakpoint to the stream s.
void Dump (Stream *s) const override
Standard "Dump" method. At present it does nothing.
lldb::BreakpointResolverSP CopyForBreakpoint (lldb::BreakpointSP &breakpoint) override
Public Member Functions inherited from lldb_private::BreakpointResolver
BreakpointResolver (const lldb::BreakpointSP &bkpt, unsigned char resolverType, lldb::addr_t offset=0, bool offset_is_insn_count=false)
The breakpoint resolver need to have a breakpoint for "ResolveBreakpoint to make sense.
~BreakpointResolver () override
The Destructor is virtual, all significant breakpoint resolvers derive from this class.
void SetBreakpoint (const lldb::BreakpointSP &bkpt)
This sets the breakpoint for this resolver.
lldb::BreakpointSP GetBreakpoint () const
This gets the breakpoint for this resolver.
void SetOffset (lldb::addr_t offset)
This updates the offset for this breakpoint.
lldb::addr_t GetOffset () const
lldb::addr_t GetOffsetIsInsnCount () const
virtual void ResolveBreakpoint (SearchFilter &filter)
In response to this method the resolver scans all the modules in the breakpoint's target, and adds any new locations it finds.
virtual void ResolveBreakpointInModules (SearchFilter &filter, ModuleList &modules)
In response to this method the resolver scans the modules in the module list modules, and adds any new locations it finds.
StructuredData::DictionarySP WrapOptionsDict (StructuredData::DictionarySP options_dict_sp)
unsigned getResolverID () const
getResolverID - Return an ID for the concrete type of this object.
enum ResolverTy GetResolverTy ()
const char * GetResolverName ()
Public Member Functions inherited from lldb_private::Searcher
Searcher ()
virtual ~Searcher ()
Static Public Member Functions
static lldb::BreakpointResolverSP CreateFromStructuredData (const StructuredData::Dictionary &data_dict, Status &error)
static bool classof (const BreakpointResolverFileLine *)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const BreakpointResolver *V)
Static Public Member Functions inherited from lldb_private::BreakpointResolver
static lldb::BreakpointResolverSP CreateFromStructuredData (const StructuredData::Dictionary &resolver_dict, Status &error)
This section handles serializing and deserializing from StructuredData objects.
static const char * GetSerializationKey ()
static const char * GetSerializationSubclassKey ()
static const char * GetSerializationSubclassOptionsKey ()
static const char * ResolverTyToName (enum ResolverTy)
static ResolverTy NameToResolverTy (llvm::StringRef name)
static const char * GetKey (OptionNames enum_value)
Protected Member Functions
void FilterContexts (SymbolContextList &sc_list)
void DeduceSourceMapping (const SymbolContextList &sc_list)
Protected Member Functions inherited from lldb_private::BreakpointResolver
virtual void NotifyBreakpointSet ()
void SetSCMatchesByLine (SearchFilter &filter, SymbolContextList &sc_list, bool skip_prologue, llvm::StringRef log_ident, uint32_t line=0, std::optional< uint16_t > column=std::nullopt)
Takes a symbol context list of matches which supposedly represent the same file and line number in a CU, and find the nearest actual line number that matches, and then filter down the matching addresses to unique entries, and skip the prologue if asked to do so, and then set breakpoint locations in this breakpoint for all the resultant addresses.
void SetSCMatchesByLine (SearchFilter &, SymbolContextList &, bool, const char *)=delete
lldb::BreakpointLocationSP AddLocation (Address loc_addr, bool *new_location=nullptr)
Protected Attributes
SourceLocationSpec m_location_spec
bool m_skip_prologue
std::optional< llvm::StringRef > m_removed_prefix_opt
Private Member Functions
BreakpointResolverFileLine (const BreakpointResolverFileLine &)=delete
const BreakpointResolverFileLine & operator= (const BreakpointResolverFileLine &)=delete
Friends
class Breakpoint
Additional Inherited Members
Public Types inherited from lldb_private::BreakpointResolver
enum ResolverTy {
FileLineResolver = 0 , AddressResolver , NameResolver , FileRegexResolver ,
PythonResolver , ExceptionResolver , LastKnownResolverType = ExceptionResolver , UnknownResolver
}
An enumeration for keeping track of the concrete subclass that is actually instantiated.
Public Types inherited from lldb_private::Searcher
enum CallbackReturn { eCallbackReturnStop = 0 , eCallbackReturnContinue , eCallbackReturnPop }
Static Public Attributes inherited from lldb_private::BreakpointResolver
static const char * g_ty_to_name [LastKnownResolverType+2]
Protected Types inherited from lldb_private::BreakpointResolver
enum class OptionNames : uint32_t {
AddressOffset = 0 , ExactMatch , FileName , Inlines ,
LanguageName , LineNumber , Column , ModuleName ,
NameMaskArray , Offset , PythonClassName , RegexString ,
ScriptArgs , SectionName , SearchDepth , SkipPrologue ,
SymbolNameArray , LastOptionName
}
Static Protected Attributes inherited from lldb_private::BreakpointResolver
static const char * g_option_names [static_cast< uint32_t >(OptionNames::LastOptionName)]
Detailed Description
"lldb/Breakpoint/BreakpointResolverFileLine.h" This class sets breakpoints by file and line.
Optionally, it will look for inlined instances of the file and line specification.
Definition at line 23 of file BreakpointResolverFileLine.h.
Constructor & Destructor Documentation
BreakpointResolverFileLine() [1/2]
BreakpointResolverFileLine::BreakpointResolverFileLine (const lldb::BreakpointSP & bkpt, lldb::addr_t offset, bool skip_prologue, const SourceLocationSpec & location_spec, std::optional< llvm::StringRef > removed_prefix_opt = std::nullopt)
Definition at line 26 of file BreakpointResolverFileLine.cpp.
References lldb_private::BreakpointResolver::BreakpointResolver(), lldb_private::BreakpointResolver::FileLineResolver, m_location_spec, m_removed_prefix_opt, and m_skip_prologue.
Referenced by BreakpointResolverFileLine(), classof(), CopyForBreakpoint(), and operator=().
~BreakpointResolverFileLine()
lldb_private::BreakpointResolverFileLine::~BreakpointResolverFileLine () override default
BreakpointResolverFileLine() [2/2]
lldb_private::BreakpointResolverFileLine::BreakpointResolverFileLine (const BreakpointResolverFileLine &) private delete
References BreakpointResolverFileLine().
Member Function Documentation
classof() [1/2]
bool lldb_private::BreakpointResolverFileLine::classof (const BreakpointResolver * V) inline static
Definition at line 52 of file BreakpointResolverFileLine.h.
References lldb_private::BreakpointResolver::BreakpointResolver(), lldb_private::BreakpointResolver::FileLineResolver, and lldb_private::BreakpointResolver::getResolverID().
classof() [2/2]
bool lldb_private::BreakpointResolverFileLine::classof (const BreakpointResolverFileLine *) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 49 of file BreakpointResolverFileLine.h.
References BreakpointResolverFileLine().
CopyForBreakpoint()
lldb::BreakpointResolverSP BreakpointResolverFileLine::CopyForBreakpoint (lldb::BreakpointSP & breakpoint) override virtual
Implements lldb_private::BreakpointResolver.
Definition at line 353 of file BreakpointResolverFileLine.cpp.
References BreakpointResolverFileLine(), lldb_private::BreakpointResolver::GetOffset(), m_location_spec, and m_skip_prologue.
CreateFromStructuredData()
BreakpointResolverSP BreakpointResolverFileLine::CreateFromStructuredData (const StructuredData::Dictionary & data_dict, Status & error) static
Definition at line 34 of file BreakpointResolverFileLine.cpp.
References lldb_private::BreakpointResolver::Column, error(), lldb_private::BreakpointResolver::ExactMatch, lldb_private::BreakpointResolver::FileName, lldb_private::Status::FromErrorString(), lldb_private::BreakpointResolver::GetKey(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsBoolean(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsInteger(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsString(), lldb_private::BreakpointResolver::Inlines, lldb_private::BreakpointResolver::LineNumber, and lldb_private::BreakpointResolver::SkipPrologue.
Referenced by lldb_private::BreakpointResolver::CreateFromStructuredData().
DeduceSourceMapping()
void BreakpointResolverFileLine::DeduceSourceMapping (const SymbolContextList & sc_list) protected
Definition at line 203 of file BreakpointResolverFileLine.cpp.
References lldb_private::PathMappingList::AppendUnique(), lldb_private::Breakpoints, lldb_private::FileSpec::Equal(), lldb_private::TargetProperties::GetAutoSourceMapRelative(), lldb_private::BreakpointResolver::GetBreakpoint(), lldb_private::FileSpec::GetDirectory(), lldb_private::GetLog(), lldb_private::TargetProperties::GetSourcePathMap(), lldb_private::Target::GetStatistics(), lldb_private::ConstString::GetStringRef(), lldb_private::TargetStats::IncreaseSourceMapDeduceCount(), lldb_private::FileSpec::IsCaseSensitive(), lldb_private::FileSpec::IsRelative(), LLDB_LOG, m_location_spec, and m_removed_prefix_opt.
Referenced by SearchCallback().
Dump()
void BreakpointResolverFileLine::Dump (Stream * s) const override virtual
Standard "Dump" method. At present it does nothing.
Implements lldb_private::BreakpointResolver.
Definition at line 350 of file BreakpointResolverFileLine.cpp.
FilterContexts()
void BreakpointResolverFileLine::FilterContexts (SymbolContextList & sc_list) protected
Definition at line 131 of file BreakpointResolverFileLine.cpp.
References lldb_private::SymbolContext::block, lldb_private::Breakpoints, lldb_private::SupportFile::eEqualFileSpecAndChecksumIfSet, lldb_private::LineEntry::file_sp, lldb_private::SymbolContext::function, lldb_private::Block::GetContainingInlinedBlock(), lldb_private::SymbolContextList::GetContextAtIndex(), lldb_private::FunctionInfo::GetDeclaration(), lldb_private::Declaration::GetFile(), lldb_private::LineEntry::GetFile(), lldb_private::Block::GetInlinedFunctionInfo(), lldb_private::Declaration::GetLine(), lldb_private::GetLog(), lldb_private::SymbolContextList::GetSize(), lldb_private::Function::GetStartLineSourceInfo(), lldb_private::Declaration::IsValid(), lldb_private::LineEntry::line, lldb_private::SymbolContext::line_entry, LLDB_LOG, m_location_spec, and lldb_private::SymbolContextList::RemoveContextAtIndex().
Referenced by SearchCallback().
GetDepth()
lldb::SearchDepth BreakpointResolverFileLine::GetDepth () override virtual
Implements lldb_private::Searcher.
Definition at line 336 of file BreakpointResolverFileLine.cpp.
References lldb::eSearchDepthModule.
GetDescription()
void BreakpointResolverFileLine::GetDescription (Stream * s) override virtual
Prints a canonical description for the breakpoint to the stream s.
Parameters
[in] s Stream to which the output is copied.
Implements lldb_private::BreakpointResolver.
Definition at line 340 of file BreakpointResolverFileLine.cpp.
References m_location_spec, and lldb_private::Stream::Printf().
operator=()
const BreakpointResolverFileLine & lldb_private::BreakpointResolverFileLine::operator= (const BreakpointResolverFileLine &) private delete
References BreakpointResolverFileLine().
SearchCallback()
Searcher::CallbackReturn BreakpointResolverFileLine::SearchCallback (SearchFilter & filter, SymbolContext & context, Address * addr) override virtual
Implements lldb_private::Searcher.
Definition at line 279 of file BreakpointResolverFileLine.cpp.
References lldb_private::SearchFilter::CompUnitPasses(), DeduceSourceMapping(), lldb_private::Searcher::eCallbackReturnContinue, FilterContexts(), lldb_private::BreakpointResolver::GetBreakpoint(), lldb_private::RealpathPrefixes::GetSourceRealpathAttemptCount(), lldb_private::RealpathPrefixes::GetSourceRealpathCompatibleCount(), lldb_private::TargetProperties::GetSourceRealpathPrefixes(), lldb_private::Target::GetStatistics(), lldb_private::StreamString::GetString(), lldb_private::TargetStats::IncreaseSourceRealpathAttemptCount(), lldb_private::TargetStats::IncreaseSourceRealpathCompatibleCount(), m_location_spec, m_skip_prologue, lldb_private::SymbolContext::module_sp, lldb_private::Stream::Printf(), and lldb_private::BreakpointResolver::SetSCMatchesByLine().
SerializeToStructuredData()
StructuredData::ObjectSP BreakpointResolverFileLine::SerializeToStructuredData () override virtual
Reimplemented from lldb_private::BreakpointResolver.
Definition at line 103 of file BreakpointResolverFileLine.cpp.
References lldb_private::BreakpointResolver::Column, lldb_private::BreakpointResolver::ExactMatch, lldb_private::BreakpointResolver::FileName, lldb_private::BreakpointResolver::GetKey(), lldb_private::BreakpointResolver::Inlines, lldb_private::BreakpointResolver::LineNumber, LLDB_INVALID_COLUMN_NUMBER, m_location_spec, m_skip_prologue, lldb_private::BreakpointResolver::SkipPrologue, and lldb_private::BreakpointResolver::WrapOptionsDict().
Friends And Related Symbol Documentation
Breakpoint
friend class Breakpoint friend
Definition at line 63 of file BreakpointResolverFileLine.h.
References Breakpoint.
Referenced by Breakpoint.
Member Data Documentation
m_location_spec
SourceLocationSpec lldb_private::BreakpointResolverFileLine::m_location_spec protected
Definition at line 64 of file BreakpointResolverFileLine.h.
Referenced by BreakpointResolverFileLine(), CopyForBreakpoint(), DeduceSourceMapping(), FilterContexts(), GetDescription(), lldb_private::Breakpoint::GetMatchingFileLine(), SearchCallback(), and SerializeToStructuredData().
m_removed_prefix_opt
std::optional<llvm::StringRef> lldb_private::BreakpointResolverFileLine::m_removed_prefix_opt protected
Definition at line 68 of file BreakpointResolverFileLine.h.
Referenced by BreakpointResolverFileLine(), and DeduceSourceMapping().
m_skip_prologue
bool lldb_private::BreakpointResolverFileLine::m_skip_prologue protected
Definition at line 65 of file BreakpointResolverFileLine.h.
Referenced by BreakpointResolverFileLine(), CopyForBreakpoint(), SearchCallback(), and SerializeToStructuredData().
The documentation for this class was generated from the following files:
BreakpointResolverFileLine.h
BreakpointResolverFileLine.cpp