LLDB: lldb_private::Type Class Reference
lldb_private::Type Class Reference
#include <Type.h>
Classes
struct ParsedName
Public Types
enum EncodingDataType {
eEncodingInvalid , eEncodingIsUID , eEncodingIsConstUID , eEncodingIsRestrictUID ,
eEncodingIsVolatileUID , eEncodingIsTypedefUID , eEncodingIsPointerUID , eEncodingIsLValueReferenceUID ,
eEncodingIsRValueReferenceUID , eEncodingIsAtomicUID , eEncodingIsSyntheticUID , eEncodingIsLLVMPtrAuthUID
}
enum class ResolveState : unsigned char { Unresolved = 0 , Forward = 1 , Layout = 2 , Full = 3 }
typedef uint32_t Payload
Public Member Functions
void Dump (Stream *s, bool show_context, lldb::DescriptionLevel level=lldb::eDescriptionLevelFull)
void DumpTypeName (Stream *s)
lldb::ModuleSP GetModule ()
Since Type instances only keep a "SymbolFile *" internally, other classes like TypeImpl need make sure the module is still around before playing with Type instances.
lldb::ModuleSP GetExeModule ()
GetModule may return module for compile unit's object file.
void GetDescription (Stream *s, lldb::DescriptionLevel level, bool show_name, ExecutionContextScope *exe_scope)
SymbolFile * GetSymbolFile ()
const SymbolFile * GetSymbolFile () const
ConstString GetName ()
ConstString GetBaseName ()
llvm::Expected< uint64_t > GetByteSize (ExecutionContextScope *exe_scope)
llvm::Expected< uint32_t > GetNumChildren (bool omit_empty_base_classes)
bool IsAggregateType ()
bool IsTemplateType ()
bool IsValidType ()
bool IsTypedef ()
lldb::TypeSP GetTypedefType ()
ConstString GetName () const
ConstString GetQualifiedName ()
bool ReadFromMemory (ExecutionContext *exe_ctx, lldb::addr_t address, AddressType address_type, DataExtractor &data)
bool WriteToMemory (ExecutionContext *exe_ctx, lldb::addr_t address, AddressType address_type, DataExtractor &data)
lldb::Format GetFormat ()
lldb::Encoding GetEncoding ()
SymbolContextScope * GetSymbolContextScope ()
const SymbolContextScope * GetSymbolContextScope () const
void SetSymbolContextScope (SymbolContextScope *context)
const lldb_private::Declaration & GetDeclaration () const
CompilerType GetFullCompilerType ()
CompilerType GetLayoutCompilerType ()
CompilerType GetForwardCompilerType ()
void SetEncodingType (Type *encoding_type)
uint32_t GetEncodingMask ()
Payload GetPayload ()
Return the language-specific payload.
void SetPayload (Payload opaque_payload)
Return the language-specific payload.
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Static Public Member Functions
static int Compare (const Type &a, const Type &b)
static std::optional< ParsedName > GetTypeScopeAndBasename (llvm::StringRef name)
Protected Member Functions
Type * GetEncodingType ()
bool ResolveCompilerType (ResolveState compiler_type_resolve_state)
Protected Attributes
ConstString m_name
SymbolFile * m_symbol_file = nullptr
SymbolContextScope * m_context = nullptr
The symbol context in which this type is defined.
Type * m_encoding_type = nullptr
lldb::user_id_t m_encoding_uid = LLDB_INVALID_UID
EncodingDataType m_encoding_uid_type = eEncodingInvalid
uint64_t m_byte_size: 63
uint64_t m_byte_size_has_value: 1
Declaration m_decl
CompilerType m_compiler_type
ResolveState m_compiler_type_resolve_state = ResolveState::Unresolved
Payload m_payload
Language-specific flags.
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Private Member Functions
Type (lldb::user_id_t uid, SymbolFile *symbol_file, ConstString name, std::optional< uint64_t > byte_size, SymbolContextScope *context, lldb::user_id_t encoding_uid, EncodingDataType encoding_uid_type, const Declaration &decl, const CompilerType &compiler_qual_type, ResolveState compiler_type_resolve_state, uint32_t opaque_payload=0)
Type ()
Type (Type &t)=default
Type (Type &&t)=default
Type & operator= (const Type &t)=default
Type & operator= (Type &&t)=default
Friends
class lldb_private::SymbolFileCommon
Only allow Symbol File to create types, as they should own them by keeping them in their TypeList.
Detailed Description
Definition at line 417 of file Type.h.
Member Typedef Documentation
Payload
typedef uint32_t lldb_private::Type::Payload
Definition at line 570 of file Type.h.
Member Enumeration Documentation
EncodingDataType
enum lldb_private::Type::EncodingDataType
Enumerator
eEncodingInvalid
Invalid encoding.
eEncodingIsUID
This type is the type whose UID is m_encoding_uid.
eEncodingIsConstUID
This type is the type whose UID is m_encoding_uid with the const qualifier added.
eEncodingIsRestrictUID
This type is the type whose UID is m_encoding_uid with the restrict qualifier added.
eEncodingIsVolatileUID
This type is the type whose UID is m_encoding_uid with the volatile qualifier added.
eEncodingIsTypedefUID
This type is alias to a type whose UID is m_encoding_uid.
eEncodingIsPointerUID
This type is pointer to a type whose UID is m_encoding_uid.
eEncodingIsLValueReferenceUID
This type is L value reference to a type whose UID is m_encoding_uid.
eEncodingIsRValueReferenceUID
This type is R value reference to a type whose UID is m_encoding_uid.
eEncodingIsAtomicUID
This type is the type whose UID is m_encoding_uid as an atomic type.
eEncodingIsSyntheticUID
This type is the synthetic type whose UID is m_encoding_uid.
eEncodingIsLLVMPtrAuthUID
This type is a signed pointer.
Definition at line 419 of file Type.h.
ResolveState
enum class lldb_private::Type::ResolveState : unsigned char strong
Enumerator
Unresolved
Forward
Layout
Full
Definition at line 449 of file Type.h.
Constructor & Destructor Documentation
Type() [1/4]
Type::Type (lldb::user_id_t uid, SymbolFile * symbol_file, ConstString name, std::optional< uint64_t > byte_size, SymbolContextScope * context, lldb::user_id_t encoding_uid, EncodingDataType encoding_uid_type, const Declaration & decl, const CompilerType & compiler_qual_type, ResolveState compiler_type_resolve_state, uint32_t opaque_payload = 0) private
Definition at line 277 of file Type.cpp.
References m_byte_size, m_byte_size_has_value, m_compiler_type, m_compiler_type_resolve_state, m_context, m_decl, m_encoding_uid, m_encoding_uid_type, m_name, m_payload, m_symbol_file, Type(), Unresolved, and lldb_private::UserID::UserID().
Referenced by Compare(), GetByteSize(), GetEncodingMask(), GetEncodingType(), GetTypedefType(), operator=(), operator=(), ResolveCompilerType(), SetEncodingType(), Type(), Type(), Type(), and Type().
Type() [2/4]
Type::Type () private
Definition at line 298 of file Type.cpp.
References m_byte_size, m_byte_size_has_value, m_name, m_payload, Type(), and lldb_private::UserID::UserID().
Type() [3/4]
lldb_private::Type::Type (Type & t) private default
References Type().
Type() [4/4]
lldb_private::Type::Type (Type && t) private default
References Type().
Member Function Documentation
Compare()
int lldb_private::Type::Compare (const Type & a, const Type & b) static
References Type().
Dump()
void Type::Dump (Stream * s, bool show_context, lldb::DescriptionLevel level = lldb::eDescriptionLevelFull)
Definition at line 373 of file Type.cpp.
References lldb_private::CompilerType::DumpTypeDescription(), eEncodingInvalid, eEncodingIsAtomicUID, eEncodingIsConstUID, eEncodingIsLLVMPtrAuthUID, eEncodingIsLValueReferenceUID, eEncodingIsPointerUID, eEncodingIsRestrictUID, eEncodingIsRValueReferenceUID, eEncodingIsSyntheticUID, eEncodingIsTypedefUID, eEncodingIsUID, eEncodingIsVolatileUID, lldb_private::Stream::EOL(), lldb_private::Stream::Format(), GetForwardCompilerType(), lldb_private::Stream::Indent(), LLDB_INVALID_UID, m_byte_size, m_byte_size_has_value, m_compiler_type, m_context, m_decl, m_encoding_uid, m_encoding_uid_type, m_name, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and lldb_private::UserID::UserID().
DumpTypeName()
void Type::DumpTypeName (Stream * s)
Definition at line 451 of file Type.cpp.
References lldb_private::ConstString::Dump(), and GetName().
Referenced by lldb_private::Variable::Dump().
GetBaseName()
ConstString Type::GetBaseName ()
Definition at line 447 of file Type.cpp.
References GetForwardCompilerType(), and lldb_private::CompilerType::GetTypeName().
GetByteSize()
llvm::Expected< uint64_t > Type::GetByteSize (ExecutionContextScope * exe_scope)
Definition at line 459 of file Type.cpp.
References eEncodingInvalid, eEncodingIsAtomicUID, eEncodingIsConstUID, eEncodingIsLLVMPtrAuthUID, eEncodingIsLValueReferenceUID, eEncodingIsPointerUID, eEncodingIsRestrictUID, eEncodingIsRValueReferenceUID, eEncodingIsSyntheticUID, eEncodingIsTypedefUID, eEncodingIsUID, eEncodingIsVolatileUID, lldb_private::CompilerType::GetByteSize(), GetByteSize(), GetEncodingType(), GetLayoutCompilerType(), m_byte_size, m_byte_size_has_value, m_encoding_uid_type, m_symbol_file, and Type().
Referenced by DWARFASTParserClang::CompleteEnumType(), lldb_private::SymbolFileCTF::CompleteType(), lldb_private::SymbolFileCTF::CreateArray(), GetByteSize(), GetDescription(), DWARFASTParserClang::ParseArrayType(), DWARFASTParserClang::ParseSingleMember(), and ReadFromMemory().
GetDeclaration()
const Declaration & Type::GetDeclaration () const
Definition at line 584 of file Type.cpp.
References m_decl.
Referenced by lldb_private::Block::AddRange().
GetDescription()
void Type::GetDescription (Stream * s, lldb::DescriptionLevel level, bool show_name, ExecutionContextScope * exe_scope)
Definition at line 305 of file Type.cpp.
References lldb_private::CompilerType::DumpTypeDescription(), lldb::eDescriptionLevelVerbose, eEncodingInvalid, eEncodingIsAtomicUID, eEncodingIsConstUID, eEncodingIsLLVMPtrAuthUID, eEncodingIsLValueReferenceUID, eEncodingIsPointerUID, eEncodingIsRestrictUID, eEncodingIsRValueReferenceUID, eEncodingIsSyntheticUID, eEncodingIsTypedefUID, eEncodingIsUID, eEncodingIsVolatileUID, GetByteSize(), GetForwardCompilerType(), GetName(), GetQualifiedName(), LLDB_INVALID_UID, m_byte_size, m_compiler_type, m_decl, m_encoding_uid, m_encoding_uid_type, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and lldb_private::UserID::UserID().
Referenced by lldb_private::SymbolContext::GetDescription().
GetEncoding()
lldb::Encoding Type::GetEncoding ()
Definition at line 534 of file Type.cpp.
References lldb_private::CompilerType::GetEncoding(), and GetForwardCompilerType().
GetEncodingMask()
uint32_t Type::GetEncodingMask ()
Definition at line 763 of file Type.cpp.
References GetEncodingMask(), GetEncodingType(), m_encoding_uid_type, and Type().
Referenced by GetCXXMethodCVQuals(), and GetEncodingMask().
GetEncodingType()
Type * Type::GetEncodingType () protected
Definition at line 453 of file Type.cpp.
References LLDB_INVALID_UID, m_encoding_type, m_encoding_uid, m_symbol_file, and Type().
Referenced by GetByteSize(), GetEncodingMask(), and ResolveCompilerType().
GetExeModule()
ModuleSP Type::GetExeModule ()
GetModule may return module for compile unit's object file.
GetExeModule returns module for executable object file that contains compile unit where type was actually defined. GetModule and GetExeModule may return the same value.
Definition at line 857 of file Type.cpp.
References lldb_private::ModuleChild::GetModule(), lldb_private::SymbolFile::GetObjectFile(), and m_compiler_type.
GetFormat()
lldb::Format Type::GetFormat ()
Definition at line 532 of file Type.cpp.
References lldb_private::CompilerType::GetFormat(), and GetForwardCompilerType().
GetForwardCompilerType()
CompilerType Type::GetForwardCompilerType ()
Definition at line 782 of file Type.cpp.
References Forward, m_compiler_type, and ResolveCompilerType().
Referenced by PDBASTParser::CreateLLDBTypeFromPDBType(), DWARFASTParserClang::CreateStaticMemberVariable(), Dump(), GetBaseName(), DWARFASTParserClang::GetClangDeclForDIE(), lldb_private::Value::GetCompilerType(), lldb_private::ValueObjectVariable::GetCompilerTypeImpl(), PDBASTParser::GetDeclForSymbol(), GetDescription(), lldb_private::ValueObjectVariable::GetDisplayTypeName(), GetEncoding(), GetFormat(), GetName(), GetNumChildren(), GetQualifiedName(), lldb_private::ClangExpressionDeclMap::GetVariableValue(), InferArtificialCoroType(), IsAggregateType(), IsTemplateType(), lldb_private::StackFrame::LegacyGetValueForVariableExpressionPath(), lldb_private::ClangExpressionDeclMap::LookUpLldbClass(), DWARFASTParserClang::ParseArrayType(), DWARFASTParserClang::ParseChildParameters(), DWARFASTParserClang::ParseCXXMethod(), DWARFASTParserClang::ParsePointerToMemberType(), DWARFASTParserClang::ParseSubroutine(), DWARFASTParserClang::ParseTemplateDIE(), PrivateAutoComplete(), ResolveCompilerType(), and lldb_private::ClangUserExpression::ScanContext().
GetFullCompilerType()
CompilerType Type::GetFullCompilerType ()
Definition at line 772 of file Type.cpp.
References Full, m_compiler_type, and ResolveCompilerType().
Referenced by lldb_private::ClangExpressionDeclMap::AddOneFunction(), PDBASTParser::AddRecordBases(), PDBASTParser::AddRecordMethod(), lldb_private::SymbolFileCTF::CompleteType(), DWARFASTParserClang::CopyUniqueClassMethodTypes(), lldb_private::SymbolFileCTF::CreateArray(), lldb_private::SymbolFileCTF::CreateFunction(), PDBASTParser::CreateLLDBTypeFromPDBType(), lldb_private::SymbolFileCTF::CreateModifier(), lldb_private::SymbolFileCTF::CreateTypedef(), lldb_private::Function::GetCompilerType(), lldb_private::ClangExpressionDeclMap::GetVariableValue(), lldb_private::ClangExpressionDeclMap::LookUpLldbObjCClass(), DWARFASTParserClang::ParseEnum(), lldb_private::SymbolFileCTF::ParseFunctions(), DWARFASTParserClang::ParseInheritance(), and lldb_private::ClangExpressionDeclMap::SearchFunctionsInSymbolContexts().
GetLayoutCompilerType()
CompilerType Type::GetLayoutCompilerType ()
Definition at line 777 of file Type.cpp.
References Layout, m_compiler_type, and ResolveCompilerType().
Referenced by PDBASTParser::AddRecordMembers(), GetByteSize(), DWARFASTParserClang::ParseObjCProperty(), and DWARFASTParserClang::ParseSingleMember().
GetModule()
ModuleSP Type::GetModule ()
Since Type instances only keep a "SymbolFile *" internally, other classes like TypeImpl need make sure the module is still around before playing with Type instances.
They can store a weak pointer to the Module;
Definition at line 851 of file Type.cpp.
References m_symbol_file.
GetName() [1/2]
ConstString Type::GetName ()
Definition at line 441 of file Type.cpp.
References GetForwardCompilerType(), lldb_private::CompilerType::GetTypeName(), and m_name.
Referenced by lldb_private::ClangExpressionDeclMap::AddOneFunction(), lldb_private::plugin::dwarf::SymbolFileDWARF::CompleteType(), lldb_private::Address::Dump(), DumpTypeName(), lldb::SBFunction::GetDescription(), GetDescription(), and lldb_private::ValueObjectVariable::GetTypeName().
GetName() [2/2]
ConstString lldb_private::Type::GetName () const inline
Definition at line 498 of file Type.h.
References m_name.
GetNumChildren()
llvm::Expected< uint32_t > Type::GetNumChildren (bool omit_empty_base_classes)
Definition at line 510 of file Type.cpp.
References GetForwardCompilerType(), and lldb_private::CompilerType::GetNumChildren().
GetPayload()
Payload lldb_private::Type::GetPayload () inline
Return the language-specific payload.
Definition at line 572 of file Type.h.
References m_payload.
GetQualifiedName()
ConstString Type::GetQualifiedName ()
Definition at line 787 of file Type.cpp.
References GetForwardCompilerType(), and lldb_private::CompilerType::GetTypeName().
Referenced by GetDescription(), and lldb_private::ValueObjectVariable::GetQualifiedTypeName().
GetSymbolContextScope() [1/2]
SymbolContextScope * lldb_private::Type::GetSymbolContextScope () inline
Definition at line 512 of file Type.h.
References m_context.
GetSymbolContextScope() [2/2]
const SymbolContextScope * lldb_private::Type::GetSymbolContextScope () const inline
Definition at line 513 of file Type.h.
References m_context.
GetSymbolFile() [1/2]
SymbolFile * lldb_private::Type::GetSymbolFile () inline
Definition at line 476 of file Type.h.
References m_symbol_file.
Referenced by lldb_private::Variable::GetDecl(), lldb_private::Variable::GetDeclContext(), and ResolveCompilerType().
GetSymbolFile() [2/2]
const SymbolFile * lldb_private::Type::GetSymbolFile () const inline
Definition at line 477 of file Type.h.
References m_symbol_file.
GetTypedefType()
lldb::TypeSP Type::GetTypedefType ()
Definition at line 522 of file Type.cpp.
References IsTypedef(), m_encoding_uid, m_symbol_file, and Type().
GetTypeScopeAndBasename()
std::optional< Type::ParsedName > Type::GetTypeScopeAndBasename (llvm::StringRef name) static
Definition at line 792 of file Type.cpp.
References lldb_private::Type::ParsedName::basename, lldb_private::Type::ParsedName::scope, and lldb_private::Type::ParsedName::type_class.
Referenced by lldb_private::npdb::SymbolFileNativePDB::GetContextForType(), and lldb_private::TypeQuery::TypeQuery().
IsAggregateType()
bool Type::IsAggregateType ()
Definition at line 514 of file Type.cpp.
References GetForwardCompilerType(), and lldb_private::CompilerType::IsAggregateType().
IsTemplateType()
bool Type::IsTemplateType ()
Definition at line 518 of file Type.cpp.
References GetForwardCompilerType(), and lldb_private::CompilerType::IsTemplateType().
IsTypedef()
bool lldb_private::Type::IsTypedef () inline
Definition at line 494 of file Type.h.
References eEncodingIsTypedefUID, and m_encoding_uid_type.
Referenced by GetTypedefType().
IsValidType()
bool lldb_private::Type::IsValidType () inline
Definition at line 492 of file Type.h.
References eEncodingInvalid, and m_encoding_uid_type.
operator=() [1/2]
Type & lldb_private::Type::operator= (const Type & t) private default
References Type().
operator=() [2/2]
Type & lldb_private::Type::operator= (Type && t) private default
References Type().
ReadFromMemory()
bool Type::ReadFromMemory (ExecutionContext * exe_ctx, lldb::addr_t address, AddressType address_type, DataExtractor & data)
Definition at line 539 of file Type.cpp.
References lldb_private::eAddressTypeFile, lldb_private::eAddressTypeHost, error(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::DataExtractor::GetByteSize(), GetByteSize(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::DataExtractor::PeekData(), lldb_private::Process::ReadMemory(), and lldb_private::DataExtractor::SetData().
ResolveCompilerType()
bool Type::ResolveCompilerType (ResolveState compiler_type_resolve_state) protected
Definition at line 586 of file Type.cpp.
References lldb_private::CompilerType::AddConstModifier(), lldb_private::CompilerType::AddPtrAuthModifier(), lldb_private::CompilerType::AddRestrictModifier(), lldb_private::CompilerType::AddVolatileModifier(), lldb_private::CompilerType::CreateTypedef(), lldb::eBasicTypeVoid, eEncodingIsAtomicUID, eEncodingIsConstUID, eEncodingIsLLVMPtrAuthUID, eEncodingIsLValueReferenceUID, eEncodingIsPointerUID, eEncodingIsRestrictUID, eEncodingIsRValueReferenceUID, eEncodingIsTypedefUID, eEncodingIsUID, eEncodingIsVolatileUID, lldb::eLanguageTypeC, Forward, Full, lldb_private::CompilerType::GetAtomicType(), lldb_private::CompilerType::GetBasicTypeFromAST(), GetEncodingType(), GetForwardCompilerType(), lldb_private::UserID::GetID(), lldb_private::GetLog(), lldb_private::CompilerType::GetLValueReferenceType(), lldb_private::CompilerType::GetPointerType(), lldb_private::CompilerType::GetRValueReferenceType(), GetSymbolFile(), lldb_private::CompilerType::IsValid(), Layout, LLDB_INVALID_UID, LLDB_LOG_ERROR, m_compiler_type, m_compiler_type_resolve_state, m_encoding_uid, m_encoding_uid_type, m_name, m_payload, m_symbol_file, ResolveCompilerType(), lldb_private::Symbols, and Type().
Referenced by GetForwardCompilerType(), GetFullCompilerType(), GetLayoutCompilerType(), and ResolveCompilerType().
SetEncodingType()
void lldb_private::Type::SetEncodingType (Type * encoding_type) inline
Definition at line 566 of file Type.h.
References m_encoding_type, and Type().
SetPayload()
void lldb_private::Type::SetPayload (Payload opaque_payload) inline
Return the language-specific payload.
Definition at line 574 of file Type.h.
References m_payload.
SetSymbolContextScope()
void lldb_private::Type::SetSymbolContextScope (SymbolContextScope * context) inline
Definition at line 514 of file Type.h.
References m_context.
WriteToMemory()
bool Type::WriteToMemory (ExecutionContext * exe_ctx, lldb::addr_t address, AddressType address_type, DataExtractor & data)
Definition at line 579 of file Type.cpp.
Friends And Related Symbol Documentation
lldb_private::SymbolFileCommon
friend class lldb_private::SymbolFileCommon friend
Only allow Symbol File to create types, as they should own them by keeping them in their TypeList.
See also
SymbolFileCommon::MakeType() reference in the header documentation here so users will know what function to use if the get a compile error.
Definition at line 600 of file Type.h.
Member Data Documentation
m_byte_size
uint64_t lldb_private::Type::m_byte_size protected
Definition at line 584 of file Type.h.
Referenced by Dump(), GetByteSize(), GetDescription(), Type(), and Type().
m_byte_size_has_value
uint64_t lldb_private::Type::m_byte_size_has_value protected
Definition at line 585 of file Type.h.
Referenced by Dump(), GetByteSize(), Type(), and Type().
m_compiler_type
CompilerType lldb_private::Type::m_compiler_type protected
Definition at line 587 of file Type.h.
Referenced by Dump(), GetDescription(), GetExeModule(), GetForwardCompilerType(), GetFullCompilerType(), GetLayoutCompilerType(), ResolveCompilerType(), and Type().
m_compiler_type_resolve_state
ResolveState lldb_private::Type::m_compiler_type_resolve_state = ResolveState::Unresolved protected
Definition at line 588 of file Type.h.
Referenced by ResolveCompilerType(), and Type().
m_context
SymbolContextScope* lldb_private::Type::m_context = nullptr protected
The symbol context in which this type is defined.
Definition at line 580 of file Type.h.
Referenced by Dump(), GetSymbolContextScope(), GetSymbolContextScope(), SetSymbolContextScope(), and Type().
m_decl
Declaration lldb_private::Type::m_decl protected
Definition at line 586 of file Type.h.
Referenced by Dump(), GetDeclaration(), GetDescription(), and Type().
m_encoding_type
Type* lldb_private::Type::m_encoding_type = nullptr protected
Definition at line 581 of file Type.h.
Referenced by GetEncodingType(), and SetEncodingType().
m_encoding_uid
lldb::user_id_t lldb_private::Type::m_encoding_uid = LLDB_INVALID_UID protected
Definition at line 582 of file Type.h.
Referenced by Dump(), GetDescription(), GetEncodingType(), GetTypedefType(), ResolveCompilerType(), and Type().
m_encoding_uid_type
EncodingDataType lldb_private::Type::m_encoding_uid_type = eEncodingInvalid protected
Definition at line 583 of file Type.h.
Referenced by Dump(), GetByteSize(), GetDescription(), GetEncodingMask(), IsTypedef(), IsValidType(), ResolveCompilerType(), and Type().
m_name
ConstString lldb_private::Type::m_name protected
Definition at line 577 of file Type.h.
Referenced by Dump(), GetName(), GetName(), ResolveCompilerType(), Type(), and Type().
m_payload
Payload lldb_private::Type::m_payload protected
Language-specific flags.
Definition at line 590 of file Type.h.
Referenced by GetPayload(), ResolveCompilerType(), SetPayload(), Type(), and Type().
m_symbol_file
SymbolFile* lldb_private::Type::m_symbol_file = nullptr protected
Definition at line 578 of file Type.h.
Referenced by GetByteSize(), GetEncodingType(), GetModule(), GetSymbolFile(), GetSymbolFile(), GetTypedefType(), ResolveCompilerType(), and Type().
The documentation for this class was generated from the following files:
Type.h
Type.cpp