LLDB: lldb::SBTypeEnumMember Class Reference
lldb::SBTypeEnumMember Class Reference
#include <SBTypeEnumMember.h>
Public Member Functions
SBTypeEnumMember ()
SBTypeEnumMember (const SBTypeEnumMember &rhs)
~SBTypeEnumMember ()
SBTypeEnumMember & operator= (const SBTypeEnumMember &rhs)
operator bool () const
bool IsValid () const
int64_t GetValueAsSigned ()
uint64_t GetValueAsUnsigned ()
const char * GetName ()
lldb::SBType GetType ()
bool GetDescription (lldb::SBStream &description, lldb::DescriptionLevel description_level)
Protected Member Functions
void reset (lldb_private::TypeEnumMemberImpl *)
lldb_private::TypeEnumMemberImpl & ref ()
const lldb_private::TypeEnumMemberImpl & ref () const
SBTypeEnumMember (const lldb::TypeEnumMemberImplSP &)
Protected Attributes
lldb::TypeEnumMemberImplSP m_opaque_sp
Friends
class SBType
class SBTypeEnumMemberList
Detailed Description
Definition at line 17 of file SBTypeEnumMember.h.
Constructor & Destructor Documentation
SBTypeEnumMember() [1/3]
SBTypeEnumMember::SBTypeEnumMember ()
Definition at line 24 of file SBTypeEnumMember.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by operator=(), SBTypeEnumMember(), and ~SBTypeEnumMember().
SBTypeEnumMember() [2/3]
SBTypeEnumMember::SBTypeEnumMember (const SBTypeEnumMember & rhs)
Definition at line 32 of file SBTypeEnumMember.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBTypeEnumMember().
~SBTypeEnumMember()
SBTypeEnumMember::~SBTypeEnumMember () default
References GetDescription(), GetType(), GetValueAsSigned(), GetValueAsUnsigned(), IsValid(), operator=(), and SBTypeEnumMember().
SBTypeEnumMember() [3/3]
SBTypeEnumMember::SBTypeEnumMember (const lldb::TypeEnumMemberImplSP & enum_member_sp) protected
Definition at line 28 of file SBTypeEnumMember.cpp.
References m_opaque_sp.
Member Function Documentation
GetDescription()
bool SBTypeEnumMember::GetDescription (lldb::SBStream & description, lldb::DescriptionLevel description_level)
Definition at line 168 of file SBTypeEnumMember.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
Referenced by ~SBTypeEnumMember().
GetName()
const char * SBTypeEnumMember::GetName ()
Definition at line 56 of file SBTypeEnumMember.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetType()
SBType SBTypeEnumMember::GetType ()
Definition at line 80 of file SBTypeEnumMember.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, SBType, and lldb::SBType::SetSP().
Referenced by ~SBTypeEnumMember().
GetValueAsSigned()
int64_t SBTypeEnumMember::GetValueAsSigned ()
Definition at line 64 of file SBTypeEnumMember.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeEnumMember().
GetValueAsUnsigned()
uint64_t SBTypeEnumMember::GetValueAsUnsigned ()
Definition at line 72 of file SBTypeEnumMember.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeEnumMember().
IsValid()
bool SBTypeEnumMember::IsValid () const
Definition at line 46 of file SBTypeEnumMember.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBTypeEnumMemberList::Append(), and ~SBTypeEnumMember().
operator bool()
SBTypeEnumMember::operator bool () const explicit
Definition at line 50 of file SBTypeEnumMember.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator=()
SBTypeEnumMember & SBTypeEnumMember::operator= (const SBTypeEnumMember & rhs)
Definition at line 38 of file SBTypeEnumMember.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBTypeEnumMember().
Referenced by ~SBTypeEnumMember().
ref() [1/2]
TypeEnumMemberImpl & SBTypeEnumMember::ref () protected
Definition at line 94 of file SBTypeEnumMember.cpp.
References m_opaque_sp.
Referenced by SBTypeEnumMemberList.
ref() [2/2]
const TypeEnumMemberImpl & SBTypeEnumMember::ref () const protected
Definition at line 100 of file SBTypeEnumMember.cpp.
References m_opaque_sp.
reset()
void SBTypeEnumMember::reset (lldb_private::TypeEnumMemberImpl * type_member_impl) protected
Definition at line 90 of file SBTypeEnumMember.cpp.
References m_opaque_sp.
Referenced by SBTypeEnumMemberList.
Friends And Related Symbol Documentation
SBType
friend class SBType friend
Definition at line 43 of file SBTypeEnumMember.h.
References SBType.
Referenced by GetType(), and SBType.
SBTypeEnumMemberList
friend class SBTypeEnumMemberList friend
Definition at line 44 of file SBTypeEnumMember.h.
References ref(), reset(), and SBTypeEnumMemberList.
Referenced by SBTypeEnumMemberList.
Member Data Documentation
m_opaque_sp
lldb::TypeEnumMemberImplSP lldb::SBTypeEnumMember::m_opaque_sp protected
Definition at line 52 of file SBTypeEnumMember.h.
Referenced by lldb::SBTypeEnumMemberList::Append(), GetDescription(), GetName(), GetType(), GetValueAsSigned(), GetValueAsUnsigned(), operator bool(), operator=(), ref(), ref(), reset(), SBTypeEnumMember(), and SBTypeEnumMember().
The documentation for this class was generated from the following files:
SBTypeEnumMember.h
SBTypeEnumMember.cpp