LLDB: lldb_private::EmulateInstructionPPC64 Class Reference
lldb_private::EmulateInstructionPPC64 Class Reference
#include <EmulateInstructionPPC64.h>
Classes
struct Opcode
Public Member Functions
EmulateInstructionPPC64 (const ArchSpec &arch)
llvm::StringRef GetPluginName () override
bool SetTargetTriple (const ArchSpec &arch) override
bool SupportsEmulatingInstructionsOfType (InstructionType inst_type) override
bool ReadInstruction () override
bool EvaluateInstruction (uint32_t evaluate_options) override
bool TestEmulation (Stream &out_stream, ArchSpec &arch, OptionValueDictionary *test_data) override
std::optional< RegisterInfo > GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num) override
bool CreateFunctionEntryUnwind (UnwindPlan &unwind_plan) override
Public Member Functions inherited from lldb_private::EmulateInstruction
EmulateInstruction (const ArchSpec &arch)
~EmulateInstruction () override=default
virtual std::optional< uint32_t > GetLastInstrSize ()
virtual InstructionCondition GetInstructionCondition ()
virtual bool SetInstruction (const Opcode &insn_opcode, const Address &inst_addr, Target *target)
std::optional< RegisterValue > ReadRegister (const RegisterInfo &reg_info)
uint64_t ReadRegisterUnsigned (const RegisterInfo &reg_info, uint64_t fail_value, bool *success_ptr)
bool WriteRegister (const Context &context, const RegisterInfo &ref_info, const RegisterValue &reg_value)
bool WriteRegisterUnsigned (const Context &context, const RegisterInfo &reg_info, uint64_t reg_value)
bool ReadRegister (lldb::RegisterKind reg_kind, uint32_t reg_num, RegisterValue &reg_value)
bool WriteRegister (const Context &context, lldb::RegisterKind reg_kind, uint32_t reg_num, const RegisterValue &reg_value)
uint64_t ReadRegisterUnsigned (lldb::RegisterKind reg_kind, uint32_t reg_num, uint64_t fail_value, bool *success_ptr)
bool WriteRegisterUnsigned (const Context &context, lldb::RegisterKind reg_kind, uint32_t reg_num, uint64_t reg_value)
size_t ReadMemory (const Context &context, lldb::addr_t addr, void *dst, size_t dst_len)
uint64_t ReadMemoryUnsigned (const Context &context, lldb::addr_t addr, size_t byte_size, uint64_t fail_value, bool *success_ptr)
bool WriteMemory (const Context &context, lldb::addr_t addr, const void *src, size_t src_len)
bool WriteMemoryUnsigned (const Context &context, lldb::addr_t addr, uint64_t uval, size_t uval_byte_size)
uint32_t GetAddressByteSize () const
lldb::ByteOrder GetByteOrder () const
const Opcode & GetOpcode () const
lldb::addr_t GetAddress () const
const ArchSpec & GetArchitecture () const
void SetBaton (void *baton)
void SetCallbacks (ReadMemoryCallback read_mem_callback, WriteMemoryCallback write_mem_callback, ReadRegisterCallback read_reg_callback, WriteRegisterCallback write_reg_callback)
void SetReadMemCallback (ReadMemoryCallback read_mem_callback)
void SetWriteMemCallback (WriteMemoryCallback write_mem_callback)
void SetReadRegCallback (ReadRegisterCallback read_reg_callback)
void SetWriteRegCallback (WriteRegisterCallback write_reg_callback)
std::optional< lldb::addr_t > ReadPC ()
bool WritePC (lldb::addr_t addr)
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static EmulateInstruction * CreateInstance (const ArchSpec &arch, InstructionType inst_type)
static bool SupportsEmulatingInstructionsOfTypeStatic (InstructionType inst_type)
Static Public Member Functions inherited from lldb_private::EmulateInstruction
static EmulateInstruction * FindPlugin (const ArchSpec &arch, InstructionType supported_inst_type, const char *plugin_name)
static const char * TranslateRegister (lldb::RegisterKind reg_kind, uint32_t reg_num, std::string &reg_name)
static size_t ReadMemoryFrame (EmulateInstruction *instruction, void *baton, const Context &context, lldb::addr_t addr, void *dst, size_t length)
static size_t WriteMemoryFrame (EmulateInstruction *instruction, void *baton, const Context &context, lldb::addr_t addr, const void *dst, size_t length)
static bool ReadRegisterFrame (EmulateInstruction *instruction, void *baton, const RegisterInfo *reg_info, RegisterValue &reg_value)
static bool WriteRegisterFrame (EmulateInstruction *instruction, void *baton, const Context &context, const RegisterInfo *reg_info, const RegisterValue &reg_value)
static size_t ReadMemoryDefault (EmulateInstruction *instruction, void *baton, const Context &context, lldb::addr_t addr, void *dst, size_t length)
static size_t WriteMemoryDefault (EmulateInstruction *instruction, void *baton, const Context &context, lldb::addr_t addr, const void *dst, size_t length)
static bool ReadRegisterDefault (EmulateInstruction *instruction, void *baton, const RegisterInfo *reg_info, RegisterValue &reg_value)
static bool WriteRegisterDefault (EmulateInstruction *instruction, void *baton, const Context &context, const RegisterInfo *reg_info, const RegisterValue &reg_value)
static bool GetBestRegisterKindAndNumber (const RegisterInfo *reg_info, lldb::RegisterKind &reg_kind, uint32_t &reg_num)
static uint32_t GetInternalRegisterNumber (RegisterContext *reg_ctx, const RegisterInfo &reg_info)
static std::unique_ptr< SingleStepBreakpointLocationsPredictor > CreateBreakpointLocationPredictor (std::unique_ptr< EmulateInstruction > emulator_up)
Private Member Functions
Opcode * GetOpcodeForInstruction (uint32_t opcode)
bool EmulateMFSPR (uint32_t opcode)
bool EmulateLD (uint32_t opcode)
bool EmulateSTD (uint32_t opcode)
bool EmulateOR (uint32_t opcode)
bool EmulateADDI (uint32_t opcode)
Private Attributes
uint32_t m_fp = LLDB_INVALID_REGNUM
Additional Inherited Members
Public Types inherited from lldb_private::EmulateInstruction
enum ContextType {
eContextInvalid = 0 , eContextReadOpcode , eContextImmediate , eContextPushRegisterOnStack ,
eContextPopRegisterOffStack , eContextAdjustStackPointer , eContextSetFramePointer , eContextRestoreStackPointer ,
eContextAdjustBaseRegister , eContextAdjustPC , eContextRegisterPlusOffset , eContextRegisterStore ,
eContextRegisterLoad , eContextRelativeBranchImmediate , eContextAbsoluteBranchRegister , eContextSupervisorCall ,
eContextTableBranchReadMemory , eContextWriteRegisterRandomBits , eContextWriteMemoryRandomBits , eContextArithmetic ,
eContextAdvancePC , eContextReturnFromException
}
enum InfoType {
eInfoTypeRegisterPlusOffset , eInfoTypeRegisterPlusIndirectOffset , eInfoTypeRegisterToRegisterPlusOffset , eInfoTypeRegisterToRegisterPlusIndirectOffset ,
eInfoTypeRegisterRegisterOperands , eInfoTypeOffset , eInfoTypeRegister , eInfoTypeImmediate ,
eInfoTypeImmediateSigned , eInfoTypeAddress , eInfoTypeISAAndImmediate , eInfoTypeISAAndImmediateSigned ,
eInfoTypeISA , eInfoTypeNoArgs
}
typedef size_t(* ReadMemoryCallback) (EmulateInstruction *instruction, void *baton, const Context &context, lldb::addr_t addr, void *dst, size_t length)
typedef size_t(* WriteMemoryCallback) (EmulateInstruction *instruction, void *baton, const Context &context, lldb::addr_t addr, const void *dst, size_t length)
typedef bool(* ReadRegisterCallback) (EmulateInstruction *instruction, void *baton, const RegisterInfo *reg_info, RegisterValue &reg_value)
typedef bool(* WriteRegisterCallback) (EmulateInstruction *instruction, void *baton, const Context &context, const RegisterInfo *reg_info, const RegisterValue &reg_value)
typedef uint32_t InstructionCondition
Static Public Attributes inherited from lldb_private::EmulateInstruction
static const InstructionCondition UnconditionalCondition = UINT32_MAX
Protected Types inherited from lldb_private::EmulateInstruction
using BreakpointLocationsPredictorCreator
Protected Attributes inherited from lldb_private::EmulateInstruction
ArchSpec m_arch
void * m_baton = nullptr
ReadMemoryCallback m_read_mem_callback = &ReadMemoryDefault
WriteMemoryCallback m_write_mem_callback = &WriteMemoryDefault
ReadRegisterCallback m_read_reg_callback = &ReadRegisterDefault
WriteRegisterCallback m_write_reg_callback = &WriteRegisterDefault
lldb::addr_t m_addr = LLDB_INVALID_ADDRESS
Opcode m_opcode
Detailed Description
Definition at line 19 of file EmulateInstructionPPC64.h.
Constructor & Destructor Documentation
EmulateInstructionPPC64()
EmulateInstructionPPC64::EmulateInstructionPPC64 (const ArchSpec & arch)
Definition at line 31 of file EmulateInstructionPPC64.cpp.
References lldb_private::EmulateInstruction::EmulateInstruction(), and EmulateInstructionPPC64().
Referenced by CreateInstance(), and EmulateInstructionPPC64().
Member Function Documentation
CreateFunctionEntryUnwind()
bool EmulateInstructionPPC64::CreateFunctionEntryUnwind (UnwindPlan & unwind_plan) override virtual
Reimplemented from lldb_private::EmulateInstruction.
Definition at line 116 of file EmulateInstructionPPC64.cpp.
References lldb_private::UnwindPlan::AppendRow(), lldb_private::UnwindPlan::Clear(), lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb::eRegisterKindLLDB, lldb_private::UnwindPlan::Row::GetCFAValue(), gpr_lr_ppc64le, gpr_r1_ppc64le, lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), lldb_private::UnwindPlan::SetRegisterKind(), lldb_private::UnwindPlan::SetReturnAddressRegister(), lldb_private::UnwindPlan::SetSourcedFromCompiler(), lldb_private::UnwindPlan::SetSourceName(), lldb_private::UnwindPlan::SetUnwindPlanForSignalTrap(), and lldb_private::UnwindPlan::SetUnwindPlanValidAtAllInstructions().
CreateInstance()
EmulateInstruction * EmulateInstructionPPC64::CreateInstance (const ArchSpec & arch, InstructionType inst_type) static
Definition at line 48 of file EmulateInstructionPPC64.cpp.
References EmulateInstructionPPC64(), lldb_private::ArchSpec::GetTriple(), and SupportsEmulatingInstructionsOfTypeStatic().
Referenced by Initialize(), and Terminate().
EmulateADDI()
bool EmulateInstructionPPC64::EmulateADDI (uint32_t opcode) private
Definition at line 359 of file EmulateInstructionPPC64.cpp.
References lldb_private::Bits32(), lldb_private::EmulateInstruction::eContextRestoreStackPointer, lldb::eRegisterKindLLDB, lldb_private::GetLog(), GetRegisterInfo(), gpr_r1_ppc64le, LLDB_LOG, lldb_private::EmulateInstruction::m_addr, ra, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, lldb_private::Unwind, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
EmulateLD()
bool EmulateInstructionPPC64::EmulateLD (uint32_t opcode) private
Definition at line 228 of file EmulateInstructionPPC64.cpp.
References lldb_private::Bits32(), lldb_private::EmulateInstruction::eContextRestoreStackPointer, lldb::eRegisterKindLLDB, lldb_private::GetLog(), GetRegisterInfo(), gpr_r1_ppc64le, LLDB_LOG, lldb_private::EmulateInstruction::m_addr, ra, lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, lldb_private::Unwind, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
EmulateMFSPR()
bool EmulateInstructionPPC64::EmulateMFSPR (uint32_t opcode) private
Definition at line 203 of file EmulateInstructionPPC64.cpp.
References lldb_private::Bits32(), lldb_private::EmulateInstruction::eContextWriteRegisterRandomBits, lldb::eRegisterKindLLDB, lldb_private::GetLog(), gpr_lr_ppc64le, gpr_r0_ppc64le, LLDB_LOG, lldb_private::EmulateInstruction::m_addr, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::type, lldb_private::Unwind, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
EmulateOR()
bool EmulateInstructionPPC64::EmulateOR (uint32_t opcode) private
Definition at line 326 of file EmulateInstructionPPC64.cpp.
References lldb_private::Bits32(), lldb_private::EmulateInstruction::eContextSetFramePointer, lldb::eRegisterKindLLDB, lldb_private::GetLog(), GetRegisterInfo(), gpr_r1_ppc64le, gpr_r30_ppc64le, gpr_r31_ppc64le, LLDB_INVALID_REGNUM, LLDB_LOG, lldb_private::EmulateInstruction::m_addr, m_fp, ra, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetRegister(), lldb_private::EmulateInstruction::Context::type, lldb_private::Unwind, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
EmulateSTD()
bool EmulateInstructionPPC64::EmulateSTD (uint32_t opcode) private
Definition at line 258 of file EmulateInstructionPPC64.cpp.
References lldb_private::Bits32(), lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb_private::EmulateInstruction::eContextPushRegisterOnStack, lldb::eRegisterKindLLDB, lldb_private::GetLog(), GetRegisterInfo(), gpr_lr_ppc64le, gpr_r0_ppc64le, gpr_r1_ppc64le, gpr_r30_ppc64le, gpr_r31_ppc64le, LLDB_LOG, lldb_private::EmulateInstruction::m_addr, ra, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, lldb_private::Unwind, lldb_private::EmulateInstruction::WriteMemory(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
EvaluateInstruction()
bool EmulateInstructionPPC64::EvaluateInstruction (uint32_t evaluate_options) override virtual
Implements lldb_private::EmulateInstruction.
Definition at line 159 of file EmulateInstructionPPC64.cpp.
References lldb_private::EmulateInstructionPPC64::Opcode::callback, lldb_private::EmulateInstruction::eContextAdvancePC, lldb::eRegisterKindLLDB, GetOpcodeForInstruction(), gpr_pc_ppc64le, lldb_private::EmulateInstruction::m_opcode, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
GetOpcodeForInstruction()
EmulateInstructionPPC64::Opcode * EmulateInstructionPPC64::GetOpcodeForInstruction (uint32_t opcode) private
Definition at line 136 of file EmulateInstructionPPC64.cpp.
References EmulateADDI(), EmulateLD(), EmulateMFSPR(), EmulateOR(), and EmulateSTD().
Referenced by EvaluateInstruction().
GetPluginDescriptionStatic()
llvm::StringRef EmulateInstructionPPC64::GetPluginDescriptionStatic () static
Definition at line 43 of file EmulateInstructionPPC64.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef lldb_private::EmulateInstructionPPC64::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 48 of file EmulateInstructionPPC64.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::EmulateInstructionPPC64::GetPluginNameStatic () inline static
Definition at line 27 of file EmulateInstructionPPC64.h.
Referenced by GetPluginName(), and Initialize().
GetRegisterInfo()
std::optional< RegisterInfo > EmulateInstructionPPC64::GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num) override virtual
Implements lldb_private::EmulateInstruction.
Definition at line 69 of file EmulateInstructionPPC64.cpp.
References lldb::eRegisterKindGeneric, lldb::eRegisterKindLLDB, gpr_cr_ppc64le, gpr_lr_ppc64le, gpr_pc_ppc64le, gpr_r1_ppc64le, LLDB_REGNUM_GENERIC_FLAGS, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_RA, LLDB_REGNUM_GENERIC_SP, and LLDBTableGetRegisterInfo().
Referenced by EmulateADDI(), EmulateLD(), EmulateOR(), and EmulateSTD().
Initialize()
void EmulateInstructionPPC64::Initialize () static
Definition at line 34 of file EmulateInstructionPPC64.cpp.
References CreateInstance(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
ReadInstruction()
bool EmulateInstructionPPC64::ReadInstruction () override virtual
Implements lldb_private::EmulateInstruction.
Definition at line 100 of file EmulateInstructionPPC64.cpp.
References lldb_private::EmulateInstruction::eContextReadOpcode, lldb::eRegisterKindGeneric, lldb_private::EmulateInstruction::GetByteOrder(), LLDB_INVALID_ADDRESS, LLDB_REGNUM_GENERIC_PC, lldb_private::EmulateInstruction::m_addr, lldb_private::EmulateInstruction::m_opcode, lldb_private::EmulateInstruction::ReadMemoryUnsigned(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetNoArgs(), and lldb_private::EmulateInstruction::Context::type.
SetTargetTriple()
bool EmulateInstructionPPC64::SetTargetTriple (const ArchSpec & arch) override virtual
Implements lldb_private::EmulateInstruction.
Definition at line 58 of file EmulateInstructionPPC64.cpp.
References lldb_private::ArchSpec::GetTriple().
SupportsEmulatingInstructionsOfType()
bool lldb_private::EmulateInstructionPPC64::SupportsEmulatingInstructionsOfType (InstructionType inst_type) inline override virtual
Implements lldb_private::EmulateInstruction.
Definition at line 52 of file EmulateInstructionPPC64.h.
References SupportsEmulatingInstructionsOfTypeStatic().
SupportsEmulatingInstructionsOfTypeStatic()
bool lldb_private::EmulateInstructionPPC64::SupportsEmulatingInstructionsOfTypeStatic (InstructionType inst_type) inline static
Definition at line 35 of file EmulateInstructionPPC64.h.
References lldb_private::eInstructionTypeAll, lldb_private::eInstructionTypeAny, lldb_private::eInstructionTypePCModifying, and lldb_private::eInstructionTypePrologueEpilogue.
Referenced by CreateInstance(), and SupportsEmulatingInstructionsOfType().
Terminate()
void EmulateInstructionPPC64::Terminate () static
Definition at line 39 of file EmulateInstructionPPC64.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
TestEmulation()
bool lldb_private::EmulateInstructionPPC64::TestEmulation (Stream & out_stream, ArchSpec & arch, OptionValueDictionary * test_data) inline override virtual
Implements lldb_private::EmulateInstruction.
Definition at line 60 of file EmulateInstructionPPC64.h.
Member Data Documentation
m_fp
uint32_t lldb_private::EmulateInstructionPPC64::m_fp = LLDB_INVALID_REGNUM private
Definition at line 78 of file EmulateInstructionPPC64.h.
Referenced by EmulateOR().
The documentation for this class was generated from the following files:
EmulateInstructionPPC64.h
EmulateInstructionPPC64.cpp