LLDB: lldb_private::ThreadPlanStepInstruction Class Reference
lldb_private::ThreadPlanStepInstruction Class Reference
#include <ThreadPlanStepInstruction.h>
Public Member Functions
ThreadPlanStepInstruction (Thread &thread, bool step_over, bool stop_others, Vote report_stop_vote, Vote report_run_vote)
~ThreadPlanStepInstruction () override
void GetDescription (Stream *s, lldb::DescriptionLevel level) override
Print a description of this thread to the stream s.
bool ValidatePlan (Stream *error) override
Returns whether this plan could be successfully created.
bool ShouldStop (Event *event_ptr) override
bool StopOthers () override
lldb::StateType GetPlanRunState () override
bool WillStop () override
bool MischiefManaged () override
bool IsPlanStale () override
Public Member Functions inherited from lldb_private::ThreadPlan
virtual ~ThreadPlan ()
const char * GetName () const
Returns the name of this thread plan.
Thread & GetThread ()
Returns the Thread that is using this thread plan.
Target & GetTarget ()
const Target & GetTarget () const
void ClearThreadCache ()
Clear the Thread* cache.
bool TracerExplainsStop ()
lldb::StateType RunState ()
bool PlanExplainsStop (Event *event_ptr)
virtual bool ShouldAutoContinue (Event *event_ptr)
Returns whether this thread plan overrides the ShouldStop of subsequently processed plans.
virtual Vote ShouldReportStop (Event *event_ptr)
Vote ShouldReportRun (Event *event_ptr)
virtual void SetStopOthers (bool new_value)
virtual bool SupportsResumeOthers ()
virtual bool ShouldRunBeforePublicStop ()
bool WillResume (lldb::StateType resume_state, bool current_plan)
bool IsControllingPlan ()
virtual bool IsLeafPlan ()
bool SetIsControllingPlan (bool value)
virtual bool OkayToDiscard ()
void SetOkayToDiscard (bool value)
virtual void ThreadDestroyed ()
bool GetPrivate ()
void SetPrivate (bool input)
virtual void DidPush ()
virtual void DidPop ()
ThreadPlanKind GetKind () const
bool IsPlanComplete ()
void SetPlanComplete (bool success=true)
bool PlanSucceeded ()
virtual bool IsBasePlan ()
lldb::ThreadPlanTracerSP & GetThreadPlanTracer ()
void SetThreadPlanTracer (lldb::ThreadPlanTracerSP new_tracer_sp)
void DoTraceLog ()
virtual lldb::ValueObjectSP GetReturnValueObject ()
virtual lldb::ExpressionVariableSP GetExpressionVariable ()
virtual void RestoreThreadState ()
virtual bool IsVirtualStep ()
bool SetIterationCount (size_t count)
virtual lldb::RunDirection GetDirection () const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Protected Member Functions
bool DoPlanExplainsStop (Event *event_ptr) override
void SetUpState ()
Protected Member Functions inherited from lldb_private::ThreadPlan
ThreadPlan (ThreadPlanKind kind, const char *name, Thread &thread, Vote report_stop_vote, Vote report_run_vote)
virtual bool DoWillResume (lldb::StateType resume_state, bool current_plan)
void PushPlan (lldb::ThreadPlanSP &thread_plan_sp)
ThreadPlan * GetPreviousPlan ()
lldb::StopInfoSP GetPrivateStopInfo ()
void SetStopInfo (lldb::StopInfoSP stop_reason_sp)
bool IsUsuallyUnexplainedStopReason (lldb::StopReason)
Private Member Functions
ThreadPlanStepInstruction (const ThreadPlanStepInstruction &)=delete
const ThreadPlanStepInstruction & operator= (const ThreadPlanStepInstruction &)=delete
Private Attributes
lldb::addr_t m_instruction_addr
bool m_stop_other_threads
bool m_step_over
bool m_start_has_symbol
StackID m_stack_id
StackID m_parent_frame_id
Friends
lldb::ThreadPlanSP Thread::QueueThreadPlanForStepSingleInstruction (bool step_over, bool abort_other_plans, bool stop_other_threads, Status &status)
Additional Inherited Members
Public Types inherited from lldb_private::ThreadPlan
enum ThreadPlanKind {
eKindGeneric , eKindNull , eKindBase , eKindCallFunction ,
eKindPython , eKindStepInstruction , eKindStepOut , eKindStepOverBreakpoint ,
eKindStepOverRange , eKindStepInRange , eKindRunToAddress , eKindStepThrough ,
eKindStepUntil , eKindSingleThreadTimeout
}
Protected Attributes inherited from lldb_private::ThreadPlan
Status m_status
Process & m_process
lldb::tid_t m_tid
Vote m_report_stop_vote
Vote m_report_run_vote
bool m_takes_iteration_count
bool m_could_not_resolve_hw_bp
int32_t m_iteration_count = 1
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Detailed Description
Definition at line 18 of file ThreadPlanStepInstruction.h.
Constructor & Destructor Documentation
ThreadPlanStepInstruction() [1/2]
ThreadPlanStepInstruction::ThreadPlanStepInstruction (Thread & thread, bool step_over, bool stop_others, Vote report_stop_vote, Vote report_run_vote)
Definition at line 23 of file ThreadPlanStepInstruction.cpp.
References lldb_private::ThreadPlan::eKindStepInstruction, m_instruction_addr, m_step_over, m_stop_other_threads, lldb_private::ThreadPlan::m_takes_iteration_count, SetUpState(), and lldb_private::ThreadPlan::ThreadPlan().
Referenced by operator=(), ThreadPlanStepInstruction(), and lldb_private::StopInfoWatchpoint::ThreadPlanStepOverWatchpoint::ThreadPlanStepOverWatchpoint().
~ThreadPlanStepInstruction()
ThreadPlanStepInstruction::~ThreadPlanStepInstruction () override default
References error().
ThreadPlanStepInstruction() [2/2]
lldb_private::ThreadPlanStepInstruction::ThreadPlanStepInstruction (const ThreadPlanStepInstruction &) private delete
References ThreadPlanStepInstruction().
Member Function Documentation
DoPlanExplainsStop()
bool ThreadPlanStepInstruction::DoPlanExplainsStop (Event * event_ptr) override protected virtual
Implements lldb_private::ThreadPlan.
Reimplemented in lldb_private::StopInfoWatchpoint::ThreadPlanStepOverWatchpoint.
Definition at line 89 of file ThreadPlanStepInstruction.cpp.
References lldb::eStopReasonNone, lldb::eStopReasonTrace, and lldb_private::ThreadPlan::GetPrivateStopInfo().
Referenced by lldb_private::StopInfoWatchpoint::ThreadPlanStepOverWatchpoint::DoPlanExplainsStop().
GetDescription()
void ThreadPlanStepInstruction::GetDescription (Stream * s, lldb::DescriptionLevel level) override virtual
Print a description of this thread to the stream s.
thread. Don't expect that the result of GetThread is valid in the description method. This might get called when the underlying Thread has not been reported, so we only know the TID and not the thread.
Parameters
[in] s The stream to which to print the description.
[in] level The level of description desired. Note that eDescriptionLevelBrief will be used in the stop message printed when the plan is complete.
Implements lldb_private::ThreadPlan.
Definition at line 53 of file ThreadPlanStepInstruction.cpp.
References lldb_private::Stream::AsRawOstream(), lldb_private::DumpAddress(), lldb::eDescriptionLevelBrief, m_instruction_addr, m_start_has_symbol, lldb_private::ThreadPlan::m_status, m_step_over, and lldb_private::Stream::Printf().
GetPlanRunState()
StateType ThreadPlanStepInstruction::GetPlanRunState () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 239 of file ThreadPlanStepInstruction.cpp.
References lldb::eStateStepping.
IsPlanStale()
bool ThreadPlanStepInstruction::IsPlanStale () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 98 of file ThreadPlanStepInstruction.cpp.
References lldb_private::Target::GetArchitecture(), lldb_private::GetLog(), lldb_private::ArchSpec::GetMaximumOpcodeByteSize(), lldb_private::ThreadPlan::GetTarget(), lldb_private::ThreadPlan::GetThread(), LLDB_LOGF, m_instruction_addr, m_stack_id, m_step_over, pc, lldb_private::ThreadPlan::SetPlanComplete(), and lldb_private::Step.
MischiefManaged()
bool ThreadPlanStepInstruction::MischiefManaged () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 245 of file ThreadPlanStepInstruction.cpp.
References lldb_private::GetLog(), lldb_private::ThreadPlan::IsPlanComplete(), LLDB_LOGF, lldb_private::ThreadPlan::MischiefManaged(), and lldb_private::Step.
Referenced by lldb_private::StopInfoWatchpoint::ThreadPlanStepOverWatchpoint::ShouldStop().
operator=()
const ThreadPlanStepInstruction & lldb_private::ThreadPlanStepInstruction::operator= (const ThreadPlanStepInstruction &) private delete
References ThreadPlanStepInstruction().
SetUpState()
void ThreadPlanStepInstruction::SetUpState () protected
Definition at line 39 of file ThreadPlanStepInstruction.cpp.
References lldb_private::ThreadPlan::GetThread(), m_instruction_addr, m_parent_frame_id, m_stack_id, and m_start_has_symbol.
Referenced by ShouldStop(), and ThreadPlanStepInstruction().
ShouldStop()
bool ThreadPlanStepInstruction::ShouldStop (Event * event_ptr) override virtual
Implements lldb_private::ThreadPlan.
Reimplemented in lldb_private::StopInfoWatchpoint::ThreadPlanStepOverWatchpoint.
Definition at line 128 of file ThreadPlanStepInstruction.cpp.
References lldb_private::Stream::AsRawOstream(), lldb_private::DumpAddress(), lldb_private::eVoteNo, lldb_private::eVoteNoOpinion, lldb_private::StreamString::GetData(), lldb_private::GetLog(), lldb_private::StackFrame::GetRegisterContext(), lldb_private::StackFrame::GetStackID(), lldb_private::ThreadPlan::GetTarget(), lldb_private::ThreadPlan::GetThread(), LLDB_LOGF, m_instruction_addr, lldb_private::ThreadPlan::m_iteration_count, m_parent_frame_id, m_stack_id, m_start_has_symbol, lldb_private::ThreadPlan::m_status, m_step_over, lldb_private::Log::PutCString(), lldb_private::Stream::PutCString(), lldb_private::ThreadPlan::SetPlanComplete(), SetUpState(), and lldb_private::Step.
Referenced by lldb_private::StopInfoWatchpoint::ThreadPlanStepOverWatchpoint::ShouldStop().
StopOthers()
bool ThreadPlanStepInstruction::StopOthers () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 237 of file ThreadPlanStepInstruction.cpp.
References m_stop_other_threads.
ValidatePlan()
bool ThreadPlanStepInstruction::ValidatePlan (Stream * error) override virtual
Returns whether this plan could be successfully created.
Parameters
[in] error A stream to which to print some reason why the plan could not be created. Can be NULL.
Returns
true if the plan should be queued, false otherwise.
Implements lldb_private::ThreadPlan.
Definition at line 83 of file ThreadPlanStepInstruction.cpp.
References error().
WillStop()
bool ThreadPlanStepInstruction::WillStop () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 243 of file ThreadPlanStepInstruction.cpp.
Friends And Related Symbol Documentation
Thread::QueueThreadPlanForStepSingleInstruction
lldb::ThreadPlanSP Thread::QueueThreadPlanForStepSingleInstruction (bool step_over, bool abort_other_plans, bool stop_other_threads, Status & status) friend
Member Data Documentation
m_instruction_addr
lldb::addr_t lldb_private::ThreadPlanStepInstruction::m_instruction_addr private
Definition at line 44 of file ThreadPlanStepInstruction.h.
Referenced by GetDescription(), IsPlanStale(), SetUpState(), ShouldStop(), and ThreadPlanStepInstruction().
m_parent_frame_id
StackID lldb_private::ThreadPlanStepInstruction::m_parent_frame_id private
Definition at line 50 of file ThreadPlanStepInstruction.h.
Referenced by SetUpState(), and ShouldStop().
m_stack_id
StackID lldb_private::ThreadPlanStepInstruction::m_stack_id private
Definition at line 49 of file ThreadPlanStepInstruction.h.
Referenced by IsPlanStale(), SetUpState(), and ShouldStop().
m_start_has_symbol
bool lldb_private::ThreadPlanStepInstruction::m_start_has_symbol private
Definition at line 48 of file ThreadPlanStepInstruction.h.
Referenced by GetDescription(), SetUpState(), and ShouldStop().
m_step_over
bool lldb_private::ThreadPlanStepInstruction::m_step_over private
Definition at line 46 of file ThreadPlanStepInstruction.h.
Referenced by GetDescription(), IsPlanStale(), ShouldStop(), and ThreadPlanStepInstruction().
m_stop_other_threads
bool lldb_private::ThreadPlanStepInstruction::m_stop_other_threads private
Definition at line 45 of file ThreadPlanStepInstruction.h.
Referenced by StopOthers(), and ThreadPlanStepInstruction().
The documentation for this class was generated from the following files:
ThreadPlanStepInstruction.h
ThreadPlanStepInstruction.cpp