LLDB: lldb_private::Diagnostic Class Reference
lldb_private::Diagnostic Class Reference
#include <DiagnosticManager.h>
Public Member Functions
DiagnosticOrigin getKind () const
Diagnostic (DiagnosticOrigin origin, uint32_t compiler_id, DiagnosticDetail detail)
virtual ~Diagnostic ()=default
virtual bool HasFixIts () const
lldb::Severity GetSeverity () const
uint32_t GetCompilerID () const
llvm::StringRef GetMessage () const
const DiagnosticDetail & GetDetail () const
void AppendMessage (llvm::StringRef message, bool precede_with_newline=true)
Static Public Member Functions
static bool classof (const Diagnostic *diag)
Protected Attributes
DiagnosticOrigin m_origin
uint32_t m_compiler_id
Compiler-specific diagnostic ID.
DiagnosticDetail m_detail
Friends
class DiagnosticManager
Detailed Description
Definition at line 58 of file DiagnosticManager.h.
Constructor & Destructor Documentation
Diagnostic()
lldb_private::Diagnostic::Diagnostic (DiagnosticOrigin origin, uint32_t compiler_id, DiagnosticDetail detail) inline
Definition at line 77 of file DiagnosticManager.h.
References m_compiler_id, m_detail, and m_origin.
Referenced by lldb_private::ClangDiagnostic::ClangDiagnostic(), lldb_private::ClangDiagnostic::classof(), and classof().
~Diagnostic()
virtual lldb_private::Diagnostic::~Diagnostic () virtual default
Member Function Documentation
AppendMessage()
void Diagnostic::AppendMessage (llvm::StringRef message, bool precede_with_newline = true)
Definition at line 149 of file DiagnosticManager.cpp.
References m_detail.
classof()
bool lldb_private::Diagnostic::classof (const Diagnostic * diag) inline static
Definition at line 64 of file DiagnosticManager.h.
References Diagnostic(), lldb_private::eDiagnosticOriginClang, lldb_private::eDiagnosticOriginLLDB, lldb_private::eDiagnosticOriginLLVM, lldb_private::eDiagnosticOriginSwift, lldb_private::eDiagnosticOriginUnknown, and getKind().
GetCompilerID()
uint32_t lldb_private::Diagnostic::GetCompilerID () const inline
Definition at line 87 of file DiagnosticManager.h.
References m_compiler_id.
GetDetail()
const DiagnosticDetail & lldb_private::Diagnostic::GetDetail () const inline
Definition at line 90 of file DiagnosticManager.h.
References m_detail.
getKind()
DiagnosticOrigin lldb_private::Diagnostic::getKind () const inline
Definition at line 62 of file DiagnosticManager.h.
References m_origin.
Referenced by lldb_private::ClangDiagnostic::classof(), and classof().
GetMessage()
llvm::StringRef lldb_private::Diagnostic::GetMessage () const inline
Definition at line 89 of file DiagnosticManager.h.
References m_detail.
GetSeverity()
lldb::Severity lldb_private::Diagnostic::GetSeverity () const inline
Definition at line 85 of file DiagnosticManager.h.
References m_detail.
HasFixIts()
virtual bool lldb_private::Diagnostic::HasFixIts () const inline virtual
Reimplemented in lldb_private::ClangDiagnostic.
Definition at line 83 of file DiagnosticManager.h.
Friends And Related Symbol Documentation
DiagnosticManager
friend class DiagnosticManager friend
Definition at line 59 of file DiagnosticManager.h.
References DiagnosticManager.
Referenced by DiagnosticManager.
Member Data Documentation
m_compiler_id
uint32_t lldb_private::Diagnostic::m_compiler_id protected
Compiler-specific diagnostic ID.
Definition at line 97 of file DiagnosticManager.h.
Referenced by Diagnostic(), and GetCompilerID().
m_detail
DiagnosticDetail lldb_private::Diagnostic::m_detail protected
Definition at line 98 of file DiagnosticManager.h.
Referenced by AppendMessage(), Diagnostic(), GetDetail(), GetMessage(), and GetSeverity().
m_origin
DiagnosticOrigin lldb_private::Diagnostic::m_origin protected
Definition at line 95 of file DiagnosticManager.h.
Referenced by Diagnostic(), and getKind().
The documentation for this class was generated from the following files:
DiagnosticManager.h
DiagnosticManager.cpp