LLDB: lldb_private::UnwindAssembly Class Reference
lldb_private::UnwindAssembly Class Reference abstract
#include <UnwindAssembly.h>
Public Member Functions
virtual bool GetNonCallSiteUnwindPlanFromAssembly (AddressRange &func, Thread &thread, UnwindPlan &unwind_plan)=0
virtual bool AugmentUnwindPlanFromCallSite (AddressRange &func, Thread &thread, UnwindPlan &unwind_plan)=0
virtual bool GetFastUnwindPlan (AddressRange &func, Thread &thread, UnwindPlan &unwind_plan)=0
virtual bool FirstNonPrologueInsn (AddressRange &func, const lldb_private::ExecutionContext &exe_ctx, Address &first_non_prologue_insn)=0
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
virtual llvm::StringRef GetPluginName ()=0
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static lldb::UnwindAssemblySP FindPlugin (const ArchSpec &arch)
Protected Member Functions
UnwindAssembly (const ArchSpec &arch)
Protected Attributes
ArchSpec m_arch
Detailed Description
Definition at line 18 of file UnwindAssembly.h.
Constructor & Destructor Documentation
UnwindAssembly()
UnwindAssembly::UnwindAssembly (const ArchSpec & arch) protected
Definition at line 31 of file UnwindAssembly.cpp.
References m_arch.
Referenced by UnwindAssembly_x86::CreateInstance(), UnwindAssembly_x86::UnwindAssembly_x86(), and UnwindAssemblyInstEmulation::UnwindAssemblyInstEmulation().
Member Function Documentation
AugmentUnwindPlanFromCallSite()
virtual bool lldb_private::UnwindAssembly::AugmentUnwindPlanFromCallSite (AddressRange & func, Thread & thread, UnwindPlan & unwind_plan) pure virtual
Implemented in UnwindAssembly_x86, and UnwindAssemblyInstEmulation.
FindPlugin()
UnwindAssemblySP UnwindAssembly::FindPlugin (const ArchSpec & arch) static
Definition at line 17 of file UnwindAssembly.cpp.
References lldb_private::PluginManager::GetUnwindAssemblyCreateCallbackAtIndex().
Referenced by lldb_private::FuncUnwinders::GetUnwindAssemblyProfiler().
FirstNonPrologueInsn()
virtual bool lldb_private::UnwindAssembly::FirstNonPrologueInsn (AddressRange & func, const lldb_private::ExecutionContext & exe_ctx, Address & first_non_prologue_insn) pure virtual
Implemented in UnwindAssembly_x86, and UnwindAssemblyInstEmulation.
GetFastUnwindPlan()
virtual bool lldb_private::UnwindAssembly::GetFastUnwindPlan (AddressRange & func, Thread & thread, UnwindPlan & unwind_plan) pure virtual
Implemented in UnwindAssembly_x86, and UnwindAssemblyInstEmulation.
GetNonCallSiteUnwindPlanFromAssembly()
virtual bool lldb_private::UnwindAssembly::GetNonCallSiteUnwindPlanFromAssembly (AddressRange & func, Thread & thread, UnwindPlan & unwind_plan) pure virtual
Implemented in UnwindAssembly_x86, and UnwindAssemblyInstEmulation.
Member Data Documentation
m_arch
ArchSpec lldb_private::UnwindAssembly::m_arch protected
Definition at line 42 of file UnwindAssembly.h.
Referenced by UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly(), UnwindAssembly(), and UnwindAssemblyInstEmulation::UnwindAssemblyInstEmulation().
The documentation for this class was generated from the following files:
UnwindAssembly.h
UnwindAssembly.cpp