LLDB: lldb_private::Stream Class Reference
lldb_private::Stream Class Reference abstract
A stream class that can stream formatted output to a file.
#include "lldb/Utility/Stream.h"
Classes
class ByteDelta
struct HighlightSettings
Struct to store information for color highlighting in the stream.
struct IndentScope
class RawOstreamForward
This is a wrapper class that exposes a raw_ostream interface that just forwards to an LLDB stream, allowing to reuse LLVM algorithms that take a raw_ostream within the LLDB code base.
Public Types
enum { eBinary = (1 << 0) }
m_flags bit values.
Public Member Functions
Stream (uint32_t flags, uint32_t addr_size, lldb::ByteOrder byte_order, bool colors=false)
Construct with flags and address size and byte order.
Stream (bool colors=false)
Construct a default Stream, not binary, host byte order and host addr size.
Stream (const Stream &other)
Stream & operator= (const Stream &rhs)
virtual ~Stream ()
Destructor.
virtual void Flush ()=0
Flush the stream.
size_t Write (const void *src, size_t src_len)
Output character bytes to the stream.
size_t GetWrittenBytes () const
size_t PutChar (char ch)
lldb::ByteOrder SetByteOrder (lldb::ByteOrder byte_order)
Set the byte_order value.
size_t PrintfAsRawHex8 (const char *format,...) __attribute__((__format__(__printf__
Format a C string from a printf style format and variable arguments and encode and append the resulting C string as hex bytes.
size_t size_t PutHex8 (uint8_t uvalue)
Append an uint8_t value in the hexadecimal format to the stream.
size_t PutNHex8 (size_t n, uint8_t uvalue)
size_t PutHex16 (uint16_t uvalue, lldb::ByteOrder byte_order=lldb::eByteOrderInvalid)
size_t PutHex32 (uint32_t uvalue, lldb::ByteOrder byte_order=lldb::eByteOrderInvalid)
size_t PutHex64 (uint64_t uvalue, lldb::ByteOrder byte_order=lldb::eByteOrderInvalid)
size_t PutMaxHex64 (uint64_t uvalue, size_t byte_size, lldb::ByteOrder byte_order=lldb::eByteOrderInvalid)
size_t PutFloat (float f, lldb::ByteOrder byte_order=lldb::eByteOrderInvalid)
size_t PutDouble (double d, lldb::ByteOrder byte_order=lldb::eByteOrderInvalid)
size_t PutLongDouble (long double ld, lldb::ByteOrder byte_order=lldb::eByteOrderInvalid)
size_t PutPointer (void *ptr)
size_t PutBytesAsRawHex8 (const void *src, size_t src_len, lldb::ByteOrder src_byte_order=lldb::eByteOrderInvalid, lldb::ByteOrder dst_byte_order=lldb::eByteOrderInvalid)
size_t PutRawBytes (const void *s, size_t src_len, lldb::ByteOrder src_byte_order=lldb::eByteOrderInvalid, lldb::ByteOrder dst_byte_order=lldb::eByteOrderInvalid)
size_t PutStringAsRawHex8 (llvm::StringRef s)
Stream & operator<< (const char *cstr)
Output a NULL terminated C string cstr to the stream s.
Stream & operator<< (llvm::StringRef str)
Stream & operator<< (const void *p)
Output a pointer value p to the stream s.
Stream & operator<< (char ch)
Output a character ch to the stream s.
Stream & operator<< (uint8_t uval)=delete
Stream & operator<< (uint16_t uval)=delete
Stream & operator<< (uint32_t uval)=delete
Stream & operator<< (uint64_t uval)=delete
Stream & operator<< (int8_t sval)=delete
Stream & operator<< (int16_t sval)=delete
Stream & operator<< (int32_t sval)=delete
Stream & operator<< (int64_t sval)=delete
size_t PutCString (llvm::StringRef cstr)
Output a C string to the stream.
void PutCStringColorHighlighted (llvm::StringRef text, std::optional< HighlightSettings > settings=std::nullopt)
Output a C string to the stream with color highlighting.
size_t EOL ()
Output and End of Line character to the stream.
uint32_t GetAddressByteSize () const
Get the address size in bytes.
Flags & GetFlags ()
The flags accessor.
const Flags & GetFlags () const
The flags const accessor.
lldb::ByteOrder GetByteOrder () const
unsigned GetIndentLevel () const
Get the current indentation level.
void SetIndentLevel (unsigned level)
Set the current indentation level.
size_t Indent (llvm::StringRef s="")
Indent the current line in the stream.
void IndentLess (unsigned amount=2)
Decrement the current indentation level.
void IndentMore (unsigned amount=2)
Increment the current indentation level.
IndentScope MakeIndentScope (unsigned indent_amount=2)
Create an indentation scope that restores the original indent level when the object goes out of scope (RAII).
void Offset (uint32_t offset, const char *format="0x%8.8x: ")
Output an offset value.
size_t Printf (const char *format,...) __attribute__((format(printf
Output printf formatted output to the stream.
size_t size_t PrintfVarArg (const char *format, va_list args)
template<typename... Args>
void Format (const char *format, Args &&... args)
void QuotedCString (const char *cstr, const char *format="\"%s\"")
Output a quoted C string value to the stream.
void SetAddressByteSize (uint32_t addr_size)
Set the address size in bytes.
size_t PutSLEB128 (int64_t uval)
Output a SLEB128 number to the stream.
size_t PutULEB128 (uint64_t uval)
Output a ULEB128 number to the stream.
llvm::raw_ostream & AsRawOstream ()
Returns a raw_ostream that forwards the data to this Stream object.
Protected Member Functions
void _PutHex8 (uint8_t uvalue, bool add_prefix)
virtual size_t WriteImpl (const void *src, size_t src_len)=0
Output character bytes to the stream.
Protected Attributes
Flags m_flags
Dump flags.
uint32_t m_addr_size = 4
Size of an address in bytes.
lldb::ByteOrder m_byte_order
Byte order to use when encoding scalar types.
unsigned m_indent_level = 0
Indention level.
std::size_t m_bytes_written = 0
Number of bytes written so far.
RawOstreamForward m_forwarder
Detailed Description
A stream class that can stream formatted output to a file.
Definition at line 28 of file Stream.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
m_flags bit values.
Enumerator
eBinary
Get and put data as binary instead of as the default string mode.
Definition at line 31 of file Stream.h.
Constructor & Destructor Documentation
Stream() [1/3]
Stream::Stream (uint32_t flags, uint32_t addr_size, lldb::ByteOrder byte_order, bool colors = false)
Construct with flags and address size and byte order.
Construct with dump flags flags and the default address size. flags can be any of the above enumeration logical OR'ed together.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 27 of file Stream.cpp.
References m_addr_size, m_byte_order, m_flags, m_forwarder, and Stream().
Referenced by lldb_private::Stream::ByteDelta::ByteDelta(), lldb_private::StreamTee::Flush(), lldb_private::Stream::IndentScope::IndentScope(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator=(), lldb_private::Stream::RawOstreamForward::RawOstreamForward(), Stream(), Stream(), lldb_private::StreamAsynchronousIO::StreamAsynchronousIO(), lldb_private::StreamBuffer< 4096 >::StreamBuffer(), lldb_private::StreamBuffer< 4096 >::StreamBuffer(), lldb_private::StreamFile::StreamFile(), lldb_private::StreamFile::StreamFile(), lldb_private::StreamFile::StreamFile(), lldb_private::StreamFile::StreamFile(), lldb_private::StreamString::StreamString(), lldb_private::StreamString::StreamString(), lldb_private::StreamTee::StreamTee(), lldb_private::StreamTee::StreamTee(), and lldb_private::StreamTee::WriteImpl().
Stream() [2/3]
Stream::Stream (bool colors = false)
Construct a default Stream, not binary, host byte order and host addr size.
Definition at line 32 of file Stream.cpp.
References m_byte_order, m_flags, and m_forwarder.
Stream() [3/3]
lldb_private::Stream::Stream (const Stream & other) inline
Definition at line 79 of file Stream.h.
References m_forwarder, and Stream().
~Stream()
Stream::~Stream () virtual default
Destructor.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Member Function Documentation
_PutHex8()
void Stream::_PutHex8 (uint8_t uvalue, bool add_prefix) protected
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 252 of file Stream.cpp.
References eBinary, m_flags, PutCString(), and Write().
Referenced by PrintfAsRawHex8(), PutBytesAsRawHex8(), PutHex16(), PutHex32(), PutHex64(), PutHex8(), PutNHex8(), PutRawBytes(), and PutStringAsRawHex8().
AsRawOstream()
llvm::raw_ostream & lldb_private::Stream::AsRawOstream () inline
Returns a raw_ostream that forwards the data to this Stream object.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 406 of file Stream.h.
References m_forwarder.
Referenced by CommandObjectBreakpointCommandList::DoExecute(), CommandObjectTargetDumpTypesystem::DoExecute(), CommandObjectTargetModulesDumpClangPCMInfo::DoExecute(), CommandObjectWatchpointCommandList::DoExecute(), lldb_private::Address::Dump(), lldb_private::AddressRange::Dump(), lldb_private::Block::Dump(), lldb_private::DiagnosticEventData::Dump(), lldb_private::FileSpecList::Dump(), lldb_private::ModuleSpec::Dump(), lldb_private::npdb::PdbAstBuilderClang::Dump(), lldb_private::ObjectFileJIT::Dump(), lldb_private::plugin::dwarf::DWARFFormValue::Dump(), lldb_private::ProcessInfo::Dump(), lldb_private::ProcessInstanceInfo::Dump(), lldb_private::SectionLoadList::Dump(), lldb_private::StructuredData::Object::Dump(), lldb_private::Target::TargetEventData::Dump(), lldb_private::Variable::Dump(), lldb_private::wasm::ObjectFileWasm::Dump(), ObjectFileCOFF::Dump(), ObjectFileELF::Dump(), ObjectFileMachO::Dump(), ObjectFilePECOFF::Dump(), lldb_private::Block::DumpAddressRanges(), lldb_private::ProcessInstanceInfo::DumpAsTableRow(), lldb_private::plugin::dwarf::SymbolFileDWARF::DumpClangAST(), SymbolFilePDB::DumpClangAST(), lldb_private::DumpDataExtractor(), DumpDWARFExpr(), lldb_private::TypeSystemClang::DumpFromSymbolFile(), DumpFullpath(), lldb_private::DWARFExpression::DumpLocation(), lldb_private::DWARFExpressionList::DumpLocations(), DumpModuleSections(), lldb_private::LineEntry::DumpStopContext(), DumpTargetInfo(), lldb_private::trace_intel_pt::TraceIntelPT::DumpTraceInfoAsJson(), lldb_private::OptionValueFileSpecList::DumpValue(), error(), lldb_private::FormatEntity::FormatFileSpec(), lldb_private::StructuredDataImpl::GetAsJSON(), lldb_private::WatchpointOptions::GetCallbackDescription(), lldb::SBModule::GetDescription(), lldb::SBSection::GetDescription(), lldb_private::Block::GetDescription(), lldb_private::Breakpoint::GetDescription(), lldb_private::BreakpointLocation::GetDescription(), lldb_private::BreakpointOptions::GetDescription(), lldb_private::DWARFExpressionList::GetDescription(), lldb_private::Function::GetDescription(), lldb_private::SymbolContext::GetDescription(), lldb_private::ThreadPlanRunToAddress::GetDescription(), lldb_private::ThreadPlanStepInstruction::GetDescription(), lldb_private::ThreadPlanStepThrough::GetDescription(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetModulesInfo(), lldb_private::Target::GetOrCreateModule(), lldb_private::Platform::GetStatus(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_jModulesInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_jThreadsInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qQueryGDBServer(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexImpl(), DynamicLoaderMacOSXDYLD::InitializeFromAllImageInfos(), lldb_private::plugin::dwarf::SymbolFileDWARF::InitializeObject(), lldb_private::Module::LoadScriptingResourceInTarget(), lldb_private::Module::LogMessage(), lldb_private::Module::LogMessageVerboseBacktrace(), note(), lldb_private::operator<<(), lldb_private::SymbolFileCTF::ParseHeader(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread(), lldb_private::PrintSeverity(), lldb_private::Module::ReportError(), lldb_private::Module::ReportErrorIfModifyDetected(), lldb_private::Module::ReportWarning(), lldb_private::ThreadPlanStepInRange::ShouldStop(), lldb_private::ThreadPlanStepInstruction::ShouldStop(), lldb_private::ThreadPlanStepOverRange::ShouldStop(), UUIDsMatch(), and warning().
EOL()
size_t Stream::EOL ()
Output and End of Line character to the stream.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 155 of file Stream.cpp.
References PutChar().
Referenced by AddBreakpointDescription(), AddWatchpointDescription(), lldb_private::SourceManager::File::DisplaySourceLines(), CommandObjectBreakpointClear::DoExecute(), CommandObjectBreakpointNameList::DoExecute(), CommandObjectFrameRecognizerInfo::DoExecute(), CommandObjectFrameRecognizerList::DoExecute(), CommandObjectMemoryFind::DoExecute(), CommandObjectMemoryRead::DoExecute(), CommandObjectPlatformProcessInfo::DoExecute(), CommandObjectProcessStatus::DoExecute(), CommandObjectScriptingExtensionList::DoExecute(), CommandObjectSettingsShow::DoExecute(), CommandObjectSourceList::DoExecute(), CommandObjectTargetModulesDumpSeparateDebugInfoFiles::DoExecute(), CommandObjectTargetModulesDumpSymtab::DoExecute(), CommandObjectTargetModulesLookup::DoExecute(), lldb_private::CommandObjectIterateOverThreads::DoExecute(), lldb_private::Address::Dump(), lldb_private::Args::Dump(), lldb_private::Block::Dump(), lldb_private::ClangASTMetadata::Dump(), lldb_private::CompileUnit::Dump(), lldb_private::DynamicRegisterInfo::Dump(), lldb_private::FormatEntity::Entry::Dump(), lldb_private::Function::Dump(), lldb_private::InstructionList::Dump(), lldb_private::LineTable::Dump(), lldb_private::ModuleSpecList::Dump(), lldb_private::ObjectFileJIT::Dump(), lldb_private::ProcessInstanceInfo::Dump(), lldb_private::Property::Dump(), lldb_private::SectionLoadHistory::Dump(), lldb_private::StackFrameList::Dump(), lldb_private::SymbolContextList::Dump(), lldb_private::Type::Dump(), lldb_private::UnwindPlan::Dump(), lldb_private::UnwindTable::Dump(), lldb_private::Variable::Dump(), ObjectFileELF::Dump(), ObjectFilePECOFF::Dump(), DumpAddress(), lldb_private::ProcessInstanceInfo::DumpAsTableRow(), lldb_private::DumpDataExtractor(), lldb_private::Property::DumpDescription(), DumpDwoFilesTable(), ObjectFileELF::DumpELFDynamic(), ObjectFileELF::DumpELFProgramHeaders(), DumpList(), DumpModuleObjfileHeaders(), DumpOsoFilesTable(), CommandObjectRegisterRead::DumpRegister(), CommandObjectRegisterRead::DumpRegisterSet(), lldb_private::DumpRegisterValue(), lldb_private::SymbolContext::DumpStopContext(), DumpStringToStreamWithNewline(), DumpSymbolContextList(), DumpTargetInfo(), lldb_private::Language::ImageListTypeScavenger::Result::DumpToStream(), lldb_private::StackFrame::DumpUsingSettingsFormat(), lldb_private::OptionValueArray::DumpValue(), lldb_private::OptionValueDictionary::DumpValue(), lldb_private::OptionValueProperties::DumpValue(), lldb_private::XMLDocument::ErrorCallback(), lldb_private::StackFrameList::FetchFramesUpTo(), lldb_private::Options::GenerateOptionUsage(), lldb_private::CommandObject::GetArgumentHelp(), lldb_private::WatchpointOptions::GetCallbackDescription(), lldb::SBBreakpointLocation::GetDescription(), lldb::SBInstructionList::GetDescription(), lldb::SBWatchpoint::GetDescription(), lldb_private::BreakpointLocation::GetDescription(), lldb_private::BreakpointOptions::GetDescription(), lldb_private::LineEntry::GetDescription(), lldb_private::LineTable::GetDescription(), lldb_private::StructuredData::Array::GetDescription(), lldb_private::StructuredData::Dictionary::GetDescription(), lldb_private::SymbolContext::GetDescription(), lldb_private::WatchpointOptions::GetDescription(), lldb_private::Breakpoint::GetDescriptionForType(), lldb_private::Platform::GetStatus(), lldb_private::ObjCLanguage::GetTypeScavenger(), LookupSymbolInModule(), LookupTypeHere(), LookupTypeInModule(), operator<<(), lldb_private::CommandInterpreter::OutputFormattedHelpText(), lldb_private::CommandInterpreter::OutputHelpText(), lldb_private::ansi::OutputWordWrappedLines(), lldb_private::Disassembler::PrintInstructions(), CommandObjectTargetModulesList::PrintModule(), PrintPlanElement(), lldb_private::EmulateInstruction::ReadMemoryDefault(), lldb_private::ThreadPlanCallFunction::ReportRegisterState(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::TestPacketSpeed(), lldb_private::OptionArgParser::ToFormat(), UUIDsMatch(), lldb_private::EmulateInstruction::WriteMemoryDefault(), and lldb_private::EmulateInstruction::WriteRegisterDefault().
Flush()
virtual void lldb_private::Stream::Flush () pure virtual
Flush the stream.
Subclasses should flush the stream to make any output appear if the stream has any buffering.
Implemented in lldb_private::StreamAsynchronousIO, lldb_private::StreamBuffer< N >, lldb_private::StreamBuffer< 4096 >, lldb_private::StreamFile, lldb_private::StreamString, and lldb_private::StreamTee.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Referenced by CommandObjectFrameRecognizerList::DoExecute(), lldb_private::DiagnosticEventData::Dump(), lldb_private::StreamTee::Flush(), lldb_private::Debugger::FlushProcessOutput(), lldb_private::StructuredDataDarwinLog::GetDescription(), ReadThreadBytesReceived(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::TestPacketSpeed().
Format()
template<typename... Args> void lldb_private::Stream::Format (const char * format, Args &&... args) inline
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 364 of file Stream.h.
References Format(), and PutCString().
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::AppendThreadIDToResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::AttachWaitProcess(), CommandObjectMultiwordObjC_TaggedPointer_Info::DoExecute(), CommandObjectPlatformDisconnect::DoExecute(), CommandObjectPlatformList::DoExecute(), CommandObjectTargetModulesDumpClangAST::DoExecute(), CommandObjectTargetModulesDumpSections::DoExecute(), CommandObjectTargetModulesDumpSymfile::DoExecute(), CommandObjectTargetModulesDumpSymtab::DoExecute(), CommandObjectTargetShowLaunchEnvironment::DoExecute(), lldb_private::CommandObjectIterateOverThreads::DoExecute(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoResume(), lldb_private::StopInfoUnixSignal::DoShouldNotify(), lldb_private::AddressRange::Dump(), lldb_private::Args::Dump(), lldb_private::Breakpoint::BreakpointEventData::Dump(), lldb_private::EventDataBytes::Dump(), lldb_private::ModuleSpec::Dump(), lldb_private::plugin::dwarf::DWARFCompileUnit::Dump(), lldb_private::plugin::dwarf::DWARFTypeUnit::Dump(), lldb_private::plugin::dwarf::ManualDWARFIndex::Dump(), lldb_private::plugin::dwarf::NameToDIE::Dump(), lldb_private::ProcessInfo::Dump(), lldb_private::ProcessInstanceInfo::Dump(), lldb_private::ProcessModID::Dump(), lldb_private::ScriptedFrameProviderDescriptor::Dump(), lldb_private::SourceManager::SourceFileCache::Dump(), lldb_private::SymbolFileCommon::Dump(), lldb_private::Type::Dump(), lldb_private::UnwindPlan::Dump(), lldb_private::UnwindTable::Dump(), lldb_private::Variable::Dump(), ObjectFilePlaceholder::Dump(), lldb_private::ProcessInstanceInfo::DumpAsTableRow(), lldb_private::DumpDataExtractor(), ObjectFileELF::DumpELFProgramHeaders(), CommandObjectTargetVariable::DumpGlobalVariableList(), DumpModuleObjfileHeaders(), lldb_private::ThreadPlanStackMap::DumpPlansForTID(), lldb_private::SymbolContext::DumpStopContext(), DumpTargetInfo(), lldb_private::trace_intel_pt::TraceIntelPT::DumpTraceInfo(), lldb_private::FormatEntity::Formatter::Format(), Format(), FormatThreadExtendedInfoRecurse(), lldb_private::ObjectFile::GetCacheHash(), lldb_private::StructuredData::Dictionary::GetDescription(), lldb_private::Thread::GetDescription(), lldb_private::Platform::GetStatus(), lldb_private::Target::StopHookScripted::GetSubclassDescription(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qHostInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::LaunchProcess(), lldb_private::process_gdb_remote::ProcessGDBRemote::MonitorDebugserverProcess(), lldb_private::formatters::NSIndirectTaggedString_SummaryProvider(), CommandObjectTargetModulesList::PrintModule(), CommandObjectProcessHandle::PrintSignal(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::SendWResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::TestPacketSpeed().
GetAddressByteSize()
uint32_t Stream::GetAddressByteSize () const
Get the address size in bytes.
Returns
The size of an address in bytes that is used when outputting address and pointer values to the stream.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 214 of file Stream.cpp.
References m_addr_size.
Referenced by CommandObjectMemoryWrite::DoExecute(), lldb_private::DumpDataExtractor(), lldb_private::npdb::MakeGlobalLocationExpression(), and operator<<().
GetByteOrder()
lldb::ByteOrder Stream::GetByteOrder () const
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 227 of file Stream.cpp.
References m_byte_order.
Referenced by lldb_private::npdb::MakeGlobalLocationExpression(), and operator<<().
GetFlags() [1/2]
Flags & Stream::GetFlags ()
The flags accessor.
Returns
A reference to the Flags member variable.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 220 of file Stream.cpp.
References m_flags.
Referenced by operator<<().
GetFlags() [2/2]
const Flags & Stream::GetFlags () const
The flags const accessor.
Returns
A const reference to the Flags member variable.
Definition at line 223 of file Stream.cpp.
References m_flags.
GetIndentLevel()
unsigned Stream::GetIndentLevel () const
Get the current indentation level.
Returns
The current indentation level.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 187 of file Stream.cpp.
References m_indent_level.
Referenced by CommandObjectBreakpointCommandList::DoExecute(), CommandObjectWatchpointCommandList::DoExecute(), lldb_private::ObjectFileJIT::Dump(), lldb_private::SectionLoadList::Dump(), lldb_private::wasm::ObjectFileWasm::Dump(), ObjectFileCOFF::Dump(), ObjectFileELF::Dump(), ObjectFileMachO::Dump(), ObjectFilePECOFF::Dump(), DumpAddress(), DumpModuleSections(), lldb_private::TypeSystemClang::DumpTypeDescription(), lldb_private::Options::GenerateOptionUsage(), lldb_private::WatchpointOptions::GetCallbackDescription(), lldb_private::BreakpointOptions::GetDescription(), lldb_private::DWARFExpressionList::GetDescription(), lldb_private::StructuredData::Array::GetDescription(), lldb_private::StructuredData::Dictionary::GetDescription(), lldb_private::Stream::IndentScope::IndentScope(), operator<<(), and lldb_private::ansi::OutputWordWrappedLines().
GetWrittenBytes()
size_t lldb_private::Stream::GetWrittenBytes () const inline
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 118 of file Stream.h.
References m_bytes_written.
Referenced by lldb_private::Stream::ByteDelta::ByteDelta(), lldb_private::SourceManager::File::DisplaySourceLines(), and lldb_private::Opcode::Dump().
Indent()
size_t Stream::Indent (llvm::StringRef s = "")
Indent the current line in the stream.
Indent the current line using the current indentation level and print an optional string following the indentation spaces.
Parameters
[in] s A string to print following the indentation.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 157 of file Stream.cpp.
References m_indent_level, and PutCString().
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::BuildTargetXml(), CommandObjectScriptingExtensionList::DoExecute(), lldb_private::Address::Dump(), lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::Dump(), lldb_private::Args::Dump(), lldb_private::Block::Dump(), lldb_private::BreakpointList::Dump(), lldb_private::CommandHistory::Dump(), lldb_private::CompileUnit::Dump(), lldb_private::Function::Dump(), lldb_private::Module::Dump(), lldb_private::ObjectFileJIT::Dump(), lldb_private::ScriptedInterfaceUsages::Dump(), lldb_private::SymbolContextList::Dump(), lldb_private::Symtab::Dump(), lldb_private::Symtab::Dump(), lldb_private::Target::Dump(), lldb_private::Type::Dump(), lldb_private::Variable::Dump(), lldb_private::wasm::ObjectFileWasm::Dump(), ObjectFileCOFF::Dump(), ObjectFileELF::Dump(), ObjectFileMachO::Dump(), ObjectFilePECOFF::Dump(), DumpAddress(), lldb_private::ThreadPlanStackMap::DumpPlans(), lldb_private::ThreadPlanStackMap::DumpPlansForTID(), CommandObjectRegisterRead::DumpRegister(), CommandObjectRegisterRead::DumpRegisterSet(), lldb_private::Watchpoint::DumpSnapshots(), lldb_private::InlineFunctionInfo::DumpStopContext(), lldb_private::SymbolContext::DumpStopContext(), lldb_private::Symtab::DumpSymbolHeader(), lldb_private::OptionValueArray::DumpValue(), lldb_private::OptionValueDictionary::DumpValue(), lldb_private::OptionValueFileSpecList::DumpValue(), lldb_private::Options::GenerateOptionUsage(), lldb_private::CommandObject::GetArgumentHelp(), lldb_private::BreakpointLocation::GetDescription(), lldb_private::BreakpointName::GetDescription(), lldb_private::BreakpointName::Permissions::GetDescription(), lldb_private::BreakpointOptions::GetDescription(), lldb_private::StructuredData::Array::GetDescription(), lldb_private::StructuredData::Dictionary::GetDescription(), lldb_private::SymbolContext::GetDescription(), lldb_private::SymbolContextSpecifier::GetDescription(), lldb_private::Target::StopHook::GetDescription(), lldb_private::ThreadPlanRunToAddress::GetDescription(), lldb_private::WatchpointOptions::GetDescription(), lldb_private::Breakpoint::GetDescriptionForType(), lldb_private::StackFrame::GetStatus(), lldb_private::Thread::GetStatus(), lldb_private::Target::StopHookCoded::GetSubclassDescription(), lldb_private::Target::StopHookCommandLine::GetSubclassDescription(), lldb_private::Target::StopHookScripted::GetSubclassDescription(), lldb_private::StringList::LogDump(), LookupFileAndLineInModule(), LookupFunctionInModule(), LookupSymbolInModule(), LookupTypeHere(), LookupTypeInModule(), operator<<(), lldb_private::CommandInterpreter::OutputFormattedHelpText(), lldb_private::CommandInterpreter::OutputHelpText(), lldb_private::ansi::OutputWordWrappedLines(), lldb_private::ThreadPlanStack::PrintOneStackNoLock(), PrintPlanElement(), lldb_private::FieldEnum::ToXML(), lldb_private::RegisterFlags::Field::ToXML(), and lldb_private::RegisterFlags::ToXML().
IndentLess()
void Stream::IndentLess (unsigned amount = 2)
Decrement the current indentation level.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 198 of file Stream.cpp.
References m_indent_level.
Referenced by AddBreakpointDescription(), AddWatchpointDescription(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::BuildTargetXml(), CommandObjectScriptingExtensionList::DoExecute(), lldb_private::Block::Dump(), lldb_private::BreakpointList::Dump(), lldb_private::BreakpointLocationList::Dump(), lldb_private::CompileUnit::Dump(), lldb_private::Module::Dump(), lldb_private::ScriptedInterfaceUsages::Dump(), lldb_private::StopPointSiteList< StopPointSite >::Dump(), lldb_private::SymbolContextList::Dump(), lldb_private::Symtab::Dump(), lldb_private::Target::Dump(), DumpAddress(), DumpModuleObjfileHeaders(), lldb_private::ThreadPlanStackMap::DumpPlans(), lldb_private::ThreadPlanStackMap::DumpPlansForTID(), CommandObjectRegisterRead::DumpRegisterSet(), DumpSymbolContextList(), lldb_private::ThreadPlanStack::DumpThreadPlans(), lldb_private::OptionValueArray::DumpValue(), lldb_private::OptionValueDictionary::DumpValue(), lldb_private::OptionValueFileSpecList::DumpValue(), lldb_private::WatchpointList::DumpWithLevel(), lldb_private::Options::GenerateOptionUsage(), lldb_private::CommandObject::GetArgumentHelp(), lldb_private::BreakpointLocation::GetDescription(), lldb_private::BreakpointName::GetDescription(), lldb_private::BreakpointName::Permissions::GetDescription(), lldb_private::BreakpointOptions::GetDescription(), lldb_private::StructuredData::Array::GetDescription(), lldb_private::StructuredData::Dictionary::GetDescription(), lldb_private::StructuredData::Object::GetDescription(), lldb_private::WatchpointOptions::GetDescription(), lldb_private::Breakpoint::GetDescriptionForType(), lldb_private::StackFrameList::GetStatus(), lldb_private::Thread::GetStatus(), LookupSymbolInModule(), operator<<(), lldb_private::CommandInterpreter::OutputFormattedHelpText(), lldb_private::CommandInterpreter::OutputHelpText(), PrintPlanElement(), lldb_private::FieldEnum::ToXML(), and lldb_private::RegisterFlags::ToXML().
IndentMore()
void Stream::IndentMore (unsigned amount = 2)
Increment the current indentation level.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 195 of file Stream.cpp.
References m_indent_level.
Referenced by AddBreakpointDescription(), AddWatchpointDescription(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::BuildTargetXml(), CommandObjectScriptingExtensionList::DoExecute(), lldb_private::Block::Dump(), lldb_private::BreakpointList::Dump(), lldb_private::BreakpointLocationList::Dump(), lldb_private::CompileUnit::Dump(), lldb_private::Module::Dump(), lldb_private::ScriptedInterfaceUsages::Dump(), lldb_private::StopPointSiteList< StopPointSite >::Dump(), lldb_private::SymbolContextList::Dump(), lldb_private::Symtab::Dump(), lldb_private::Target::Dump(), DumpAddress(), DumpModuleObjfileHeaders(), lldb_private::ThreadPlanStackMap::DumpPlans(), lldb_private::ThreadPlanStackMap::DumpPlansForTID(), CommandObjectRegisterRead::DumpRegisterSet(), DumpSymbolContextList(), lldb_private::ThreadPlanStack::DumpThreadPlans(), lldb_private::OptionValueArray::DumpValue(), lldb_private::OptionValueDictionary::DumpValue(), lldb_private::OptionValueFileSpecList::DumpValue(), lldb_private::WatchpointList::DumpWithLevel(), lldb_private::Options::GenerateOptionUsage(), lldb_private::CommandObject::GetArgumentHelp(), lldb_private::BreakpointLocation::GetDescription(), lldb_private::BreakpointName::GetDescription(), lldb_private::BreakpointName::Permissions::GetDescription(), lldb_private::BreakpointOptions::GetDescription(), lldb_private::StructuredData::Array::GetDescription(), lldb_private::StructuredData::Dictionary::GetDescription(), lldb_private::StructuredData::Object::GetDescription(), lldb_private::WatchpointOptions::GetDescription(), lldb_private::Breakpoint::GetDescriptionForType(), lldb_private::Thread::GetStatus(), LookupSymbolInModule(), MakeIndentScope(), operator<<(), lldb_private::CommandInterpreter::OutputFormattedHelpText(), lldb_private::CommandInterpreter::OutputHelpText(), PrintPlanElement(), lldb_private::Thread::ShouldStop(), lldb_private::FieldEnum::ToXML(), and lldb_private::RegisterFlags::ToXML().
MakeIndentScope()
Stream::IndentScope Stream::MakeIndentScope (unsigned indent_amount = 2)
Create an indentation scope that restores the original indent level when the object goes out of scope (RAII).
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 207 of file Stream.cpp.
References IndentMore().
Referenced by lldb_private::Target::StopHook::GetDescription(), lldb_private::Target::StopHookCommandLine::GetSubclassDescription(), and lldb_private::Target::StopHookScripted::GetSubclassDescription().
Offset()
void Stream::Offset (uint32_t offset, const char * format = "0x%8.8x: ")
Output an offset value.
Put an offset uval out to the stream using the printf format in format.
Parameters
[in] offset The offset value.
[in] format The printf style format to use when outputting the offset.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 46 of file Stream.cpp.
References Printf().
operator<<() [1/12]
Stream & Stream::operator<< (char ch)
Output a character ch to the stream s.
Parameters
[in] ch A printable character value.
Returns
A reference to this class so multiple things can be streamed in one statement.
Definition at line 164 of file Stream.cpp.
References PutChar(), and Stream().
operator<<() [2/12]
Stream & Stream::operator<< (const char * cstr)
Output a NULL terminated C string cstr to the stream s.
Parameters
[in] cstr A NULL terminated C string.
Returns
A reference to this class so multiple things can be streamed in one statement.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 170 of file Stream.cpp.
References Printf(), and Stream().
operator<<() [3/12]
Stream & Stream::operator<< (const void * p)
Output a pointer value p to the stream s.
Parameters
[in] p A void pointer.
Returns
A reference to this class so multiple things can be streamed in one statement.
Definition at line 181 of file Stream.cpp.
References Printf(), and Stream().
operator<<() [4/12]
Stream & lldb_private::Stream::operator<< (int16_t sval) delete
References Stream().
operator<<() [5/12]
Stream & lldb_private::Stream::operator<< (int32_t sval) delete
References Stream().
operator<<() [6/12]
Stream & lldb_private::Stream::operator<< (int64_t sval) delete
References EOL(), GetAddressByteSize(), GetByteOrder(), GetFlags(), GetIndentLevel(), Indent(), IndentLess(), IndentMore(), PutCString(), PutCStringColorHighlighted(), SetIndentLevel(), and Stream().
operator<<() [7/12]
Stream & lldb_private::Stream::operator<< (int8_t sval) delete
References Stream().
operator<<() [8/12]
Stream & Stream::operator<< (llvm::StringRef str)
Definition at line 175 of file Stream.cpp.
References Stream(), and Write().
operator<<() [9/12]
Stream & lldb_private::Stream::operator<< (uint16_t uval) delete
References Stream().
operator<<() [10/12]
Stream & lldb_private::Stream::operator<< (uint32_t uval) delete
References Stream().
operator<<() [11/12]
Stream & lldb_private::Stream::operator<< (uint64_t uval) delete
References Stream().
operator<<() [12/12]
Stream & lldb_private::Stream::operator<< (uint8_t uval) delete
References Stream().
operator=()
Stream & lldb_private::Stream::operator= (const Stream & rhs) inline
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 81 of file Stream.h.
References m_addr_size, m_byte_order, m_flags, m_indent_level, and Stream().
Referenced by lldb_private::StreamTee::operator=().
Printf()
size_t Stream::Printf (const char * format, ...)
Output printf formatted output to the stream.
Print some formatted output to the stream.
Parameters
[in] format A printf style format string.
[in] ... Variable arguments that are needed for the printf style format string format.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 134 of file Stream.cpp.
References PrintfVarArg().
Referenced by lldb_private::ClangExpressionSourceCode::AddLocalVariableDecls(), AddMacros(), lldb_private::Disassembler::AppendInstructions(), sddarwinlog_private::EnableCommand::AppendStrictSourcesWarning(), lldb_private::plugin::dwarf::DWARFDIE::AppendTypeName(), lldb_private::arch_helper(), lldb_private::RegisterFlags::AsTable(), lldb_private::formatters::BlockPointerSummaryProvider(), lldb_private::AppleObjCTypeEncodingParser::BuildAggregate(), lldb_private::CommandInterpreter::BuildAliasResult(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::BuildTargetXml(), InstructionLLVMC::CalculateMnemonicOperandsAndComment(), ThreadMachCore::CalculateStopInfo(), lldb_private::formatters::CFAbsoluteTimeSummaryProvider(), lldb_private::formatters::CFBagSummaryProvider(), lldb_private::formatters::CFBinaryHeapSummaryProvider(), lldb_private::formatters::CFBitVectorSummaryProvider(), CharStringSummaryProvider(), CharSummaryProvider(), lldb_private::process_gdb_remote::GDBRemoteCommunication::CheckForPacket(), chown_file(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::CloseFile(), lldb_private::formatters::CMTimeSummaryProvider(), CollectRegNums(), lldb_private::CommandAlias::CommandAlias(), CommandObjectPythonFunction::CommandObjectPythonFunction(), CommandObjectScriptingObjectRaw::CommandObjectScriptingObjectRaw(), CommandObjectTypeCategoryDefine::CommandObjectTypeCategoryDefine(), CommandObjectTypeFormat::CommandObjectTypeFormat(), CommandObjectTypeFormatterDelete::CommandObjectTypeFormatterDelete(), EmulationStateARM::CompareState(), lldb_private::ProcessLaunchInfo::ConvertArgumentsForLaunchingInShell(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse_DebugServerStyle(), lldb_private::formatters::CXXFunctionPointerSummaryProvider(), DescribeAddressBriefly(), lldb_private::StopInfoMachException::DeterminePtrauthFailure(), lldb_private::StopInfoMachException::DetermineTagMismatch(), DisplayBytes(), lldb_private::SourceManager::DisplaySourceLinesWithLineNumbersUsingLastFile(), lldb_private::ClangDynamicCheckerFunctions::DoCheckersExplainStop(), CommandObjectBreakpointAddException::DoExecute(), CommandObjectBreakpointAddFile::DoExecute(), CommandObjectBreakpointAddName::DoExecute(), CommandObjectBreakpointAddPattern::DoExecute(), CommandObjectBreakpointAddScripted::DoExecute(), CommandObjectBreakpointClear::DoExecute(), CommandObjectBreakpointCommandList::DoExecute(), CommandObjectBreakpointSet::DoExecute(), CommandObjectFormatterInfo< FormatterType >::DoExecute(), CommandObjectFrameRecognizerInfo::DoExecute(), CommandObjectMemoryRead::DoExecute(), CommandObjectMemoryWrite::DoExecute(), CommandObjectPlatformDisconnect::DoExecute(), CommandObjectPlatformList::DoExecute(), CommandObjectPlatformProcessInfo::DoExecute(), CommandObjectPlatformShell::DoExecute(), CommandObjectProcessGDBRemotePacketMonitor::DoExecute(), CommandObjectProcessGDBRemotePacketSend::DoExecute(), CommandObjectProcessMinidumpDump::DoExecute(), CommandObjectRegisterRead::DoExecute(), CommandObjectScriptingExtensionList::DoExecute(), CommandObjectTargetDelete::DoExecute(), CommandObjectTargetModulesList::DoExecute(), CommandObjectTargetModulesSearchPathsQuery::DoExecute(), CommandObjectTargetModulesShowUnwind::DoExecute(), CommandObjectTargetVariable::DoExecute(), CommandObjectTypeFormatterList< FormatterType >::DoExecute(), CommandObjectWatchpointCommandList::DoExecute(), lldb_private::CommandObjectHelp::DoExecute(), lldb_private::CommandObjectQuit::DoExecute(), lldb_private::CommandObjectRegexCommand::DoExecute(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoResume(), lldb_private::ThreadPlanStepOverRange::DoWillResume(), lldb_private::platform_android::PlatformAndroid::DownloadSymbolFile(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoWriteMemory(), lldb_private::Statusline::Draw(), elf::ELFSymbol::Dump(), lldb_private::Address::Dump(), lldb_private::AddressRange::Dump(), lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::Dump(), lldb_private::Block::Dump(), lldb_private::BreakpointList::Dump(), lldb_private::BreakpointLocation::Dump(), lldb_private::BreakpointLocationList::Dump(), lldb_private::BreakpointSite::Dump(), lldb_private::ClangASTMetadata::Dump(), lldb_private::CommandHistory::Dump(), lldb_private::CompileUnit::Dump(), lldb_private::Declaration::Dump(), lldb_private::DynamicRegisterInfo::Dump(), lldb_private::EmulateInstruction::Context::Dump(), lldb_private::Event::Dump(), lldb_private::FileAction::Dump(), lldb_private::FormatEntity::Entry::Dump(), lldb_private::Function::Dump(), lldb_private::GDBRemotePacket::Dump(), lldb_private::Instruction::Dump(), lldb_private::LineEntry::Dump(), lldb_private::Mangled::Dump(), lldb_private::Module::Dump(), lldb_private::ModuleSpec::Dump(), lldb_private::ModuleSpecList::Dump(), lldb_private::ObjectFileJIT::Dump(), lldb_private::Opcode::Dump(), lldb_private::PathMappingList::Dump(), lldb_private::plugin::dwarf::DWARFFormValue::Dump(), lldb_private::plugin::dwarf::ManualDWARFIndex::Dump(), lldb_private::Process::ProcessEventData::Dump(), lldb_private::process_gdb_remote::GDBRemoteCommunicationHistory::Dump(), lldb_private::ProcessInstanceInfo::Dump(), lldb_private::ProgressEventData::Dump(), lldb_private::ScriptedFrameProviderDescriptor::Dump(), lldb_private::SectionLoadHistory::Dump(), lldb_private::SectionLoadList::Dump(), lldb_private::StackFrame::Dump(), lldb_private::StackFrameList::Dump(), lldb_private::StackID::Dump(), lldb_private::StopPointSiteList< StopPointSite >::Dump(), lldb_private::Symbol::Dump(), lldb_private::Symtab::Dump(), lldb_private::Symtab::Dump(), lldb_private::Type::Dump(), lldb_private::UnwindPlan::Dump(), lldb_private::UnwindPlan::Row::AbstractRegisterLocation::Dump(), lldb_private::UnwindPlan::Row::Dump(), lldb_private::UnwindPlan::Row::FAValue::Dump(), lldb_private::UnwindTable::Dump(), lldb_private::Value::Dump(), lldb_private::Variable::Dump(), lldb_private::WatchpointResource::Dump(), ObjectFileCOFF::Dump(), ObjectFileELF::Dump(), ObjectFileMachO::Dump(), ObjectFilePECOFF::Dump(), sddarwinlog_private::ExactMatchFilterRule::Dump(), sddarwinlog_private::RegexFilterRule::Dump(), DumpAddressAndContent(), DumpAddressOffsetFromFunction(), lldb_private::Properties::DumpAllPropertyValues(), lldb_private::ProcessInstanceInfo::DumpAsTableRow(), DumpBasename(), lldb_private::Timer::DumpCategoryTimes(), DumpCharacter(), ObjectFilePECOFF::DumpCOFFHeader(), DumpCommaSeparatedChildEntryNames(), lldb_private::formatters::DumpCxxSmartPtrPointerSummary(), lldb_private::DumpDataExtractor(), lldb_private::AddressRange::DumpDebug(), lldb_private::ConstString::DumpDebug(), lldb_private::Mangled::DumpDebug(), ObjectFileELF::DumpDependentModules(), ObjectFilePECOFF::DumpDependentModules(), lldb_private::Property::DumpDescription(), DumpDirectory(), ObjectFilePECOFF::DumpDOSHeader(), DumpDwoFilesTable(), ObjectFileELF::DumpELFDynamic(), ObjectFileELF::DumpELFHeader(), ObjectFileELF::DumpELFProgramHeader(), ObjectFileELF::DumpELFProgramHeader_p_type(), ObjectFileELF::DumpELFSectionHeader(), ObjectFileELF::DumpELFSectionHeader_sh_type(), ObjectFileELF::DumpELFSectionHeaders(), DumpEncodedBufferToStream(), lldb_private::OptionValueEnumeration::DumpEnum(), DumpEnumerators(), DumpEnumValue(), DumpFullpath(), CommandObjectTargetVariable::DumpGlobalVariableList(), DumpInstructions(), DumpModuleArchitecture(), DumpModuleSections(), ObjectFilePECOFF::DumpOptCOFFHeader(), DumpOsoFilesTable(), CommunicationKDP::DumpPacket(), lldb_private::ThreadPlanStackMap::DumpPlans(), lldb_private::ThreadPlanStackMap::DumpPlansForTID(), lldb_private::ValueObject::DumpPrintableRepresentation(), lldb_private::OptionValueProperties::DumpPropertyValue(), lldb_private::ThreadPlanStepRange::DumpRanges(), DumpRegisterName(), CommandObjectRegisterRead::DumpRegisterSet(), lldb_private::DumpRegisterValue(), ObjectFilePECOFF::DumpSectionHeader(), ObjectFilePECOFF::DumpSectionHeaders(), lldb_private::Watchpoint::DumpSnapshots(), lldb_private::Declaration::DumpStopContext(), lldb_private::LineEntry::DumpStopContext(), lldb_private::SymbolContext::DumpStopContext(), lldb_private::Block::DumpSymbolContext(), lldb_private::CompileUnit::DumpSymbolContext(), lldb_private::Function::DumpSymbolContext(), lldb_private::Module::DumpSymbolContext(), lldb_private::Symbol::DumpSymbolContext(), lldb_private::ProcessInstanceInfo::DumpTableHeader(), DumpTargetInfo(), lldb_private::StructuredDataDarwinLog::DumpTimestamp(), EntityPersistentVariable::DumpToLog(), EntityRegister::DumpToLog(), EntityResultVariable::DumpToLog(), EntitySymbol::DumpToLog(), EntityVariableBase::DumpToLog(), DumpUnwindRowsToLog(), lldb_private::FormatEntity::Formatter::DumpValue(), lldb_private::OptionValueArch::DumpValue(), lldb_private::OptionValueArray::DumpValue(), lldb_private::OptionValueBoolean::DumpValue(), lldb_private::OptionValueChar::DumpValue(), lldb_private::OptionValueDictionary::DumpValue(), lldb_private::OptionValueEnumeration::DumpValue(), lldb_private::OptionValueFileColonLine::DumpValue(), lldb_private::OptionValueFileSpec::DumpValue(), lldb_private::OptionValueFileSpecList::DumpValue(), lldb_private::OptionValueFormat::DumpValue(), lldb_private::OptionValueFormatEntity::DumpValue(), lldb_private::OptionValueLanguage::DumpValue(), lldb_private::OptionValuePathMappings::DumpValue(), lldb_private::OptionValueRegex::DumpValue(), lldb_private::OptionValueSInt64::DumpValue(), lldb_private::OptionValueString::DumpValue(), lldb_private::OptionValueUInt64::DumpValue(), lldb_private::OptionValueUUID::DumpValue(), lldb_private::Watchpoint::DumpWithLevel(), lldb_private::WatchpointList::DumpWithLevel(), lldb_private::DWARFExpression::Evaluate(), lldb_private::StackFrameList::FetchFramesUpTo(), lldb_private::SymbolContext::FindBestGlobalDataSymbol(), lldb_private::ClangASTSource::FindObjCMethodDecls(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), lldb_private::process_gdb_remote::ProcessGDBRemote::FlashErase(), lldb_private::FormatEntity::Formatter::Format(), FormatCell(), lldb_private::FormatHelpTextCallback(), FormatThreadExtendedInfoRecurse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FStat(), lldb_private::CommandObjectHelp::GenerateAdditionalHelpAvenuesMessage(), lldb_private::Options::GenerateOptionUsage(), lldb_private::formatters::GenericOptionalSummaryProvider(), lldb_private::CommandAlias::GetAliasExpansion(), lldb_private::OptionValueDictionary::GetArgs(), lldb_private::CommandObject::GetArgumentHelp(), lldb_private::BreakpointID::GetCanonicalReference(), lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >::GetChildAtIndex(), lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::GetChildAtIndex(), lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< D32, D64 >::GetChildAtIndex(), lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::GetChildAtIndex(), lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdSpanSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdVectorSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxVectorBoolSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlSpanSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlVectorSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSArrayMSyntheticFrontEndBase::GetChildAtIndex(), lldb_private::formatters::NSCFDictionarySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSCFSetSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSDictionaryISyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSSetISyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::VectorTypeSyntheticFrontEnd::GetChildAtIndex(), ObjectFileMachO::GetCorefileThreadExtraInfos(), lldb_private::Language::GetDefaultExceptionResolverDescription(), ExceptionBreakpointResolver::GetDescription(), lldb::SBAddressRangeList::GetDescription(), lldb::SBBlock::GetDescription(), lldb::SBCommandReturnObject::GetDescription(), lldb::SBDebugger::GetDescription(), lldb::SBDeclaration::GetDescription(), lldb::SBFileSpecList::GetDescription(), lldb::SBLineEntry::GetDescription(), lldb::SBMemoryRegionInfo::GetDescription(), lldb::SBProcess::GetDescription(), lldb::SBSection::GetDescription(), lldb::SBTypeEnumMember::GetDescription(), lldb::SBTypeMember::GetDescription(), lldb_private::Address::GetDescription(), lldb_private::AddressRange::GetDescription(), lldb_private::AddressResolverFileLine::GetDescription(), lldb_private::AppleThreadPlanStepThroughDirectDispatch::GetDescription(), lldb_private::AppleThreadPlanStepThroughObjCTrampoline::GetDescription(), lldb_private::Block::GetDescription(), lldb_private::Breakpoint::GetDescription(), lldb_private::BreakpointID::GetDescription(), lldb_private::BreakpointLocation::GetDescription(), lldb_private::BreakpointLocationList::GetDescription(), lldb_private::BreakpointName::GetDescription(), lldb_private::BreakpointName::Permissions::GetDescription(), lldb_private::BreakpointOptions::GetDescription(), lldb_private::BreakpointResolverFileLine::GetDescription(), lldb_private::BreakpointResolverFileRegex::GetDescription(), lldb_private::BreakpointResolverName::GetDescription(), lldb_private::BreakpointResolverScripted::GetDescription(), lldb_private::BreakpointSite::GetDescription(), lldb_private::BytecodeSummaryFormat::GetDescription(), lldb_private::BytecodeSyntheticChildren::GetDescription(), lldb_private::CXXFunctionSummaryFormat::GetDescription(), lldb_private::CXXSyntheticChildren::GetDescription(), lldb_private::FileLineResolver::GetDescription(), lldb_private::LineEntry::GetDescription(), lldb_private::ScriptedSyntheticChildren::GetDescription(), lldb_private::ScriptedThreadPlan::GetDescription(), lldb_private::ScriptSummaryFormat::GetDescription(), lldb_private::SearchFilterByModuleList::GetDescription(), lldb_private::SearchFilterByModuleListAndCU::GetDescription(), lldb_private::StopInfoBreakpoint::GetDescription(), lldb_private::StopInfoMachException::GetDescription(), lldb_private::StopInfoUnixSignal::GetDescription(), lldb_private::StopInfoWatchpoint::GetDescription(), lldb_private::StringSummaryFormat::GetDescription(), lldb_private::StructuredData::Array::GetDescription(), lldb_private::StructuredData::Boolean::GetDescription(), lldb_private::StructuredData::Float::GetDescription(), lldb_private::StructuredData::Generic::GetDescription(), lldb_private::StructuredData::Integer< uint64_t >::GetDescription(), lldb_private::StructuredData::Null::GetDescription(), lldb_private::StructuredData::String::GetDescription(), lldb_private::Symbol::GetDescription(), lldb_private::SymbolContext::GetDescription(), lldb_private::SymbolContextSpecifier::GetDescription(), lldb_private::Target::StopHook::GetDescription(), lldb_private::Thread::GetDescription(), lldb_private::ThreadPlanBase::GetDescription(), lldb_private::ThreadPlanCallFunction::GetDescription(), lldb_private::ThreadPlanCallFunctionUsingABI::GetDescription(), lldb_private::ThreadPlanCallOnFunctionExit::GetDescription(), lldb_private::ThreadPlanCallUserExpression::GetDescription(), lldb_private::ThreadPlanRunToAddress::GetDescription(), lldb_private::ThreadPlanSingleThreadTimeout::GetDescription(), lldb_private::ThreadPlanStepInRange::GetDescription(), lldb_private::ThreadPlanStepInstruction::GetDescription(), lldb_private::ThreadPlanStepOut::GetDescription(), lldb_private::ThreadPlanStepOverBreakpoint::GetDescription(), lldb_private::ThreadPlanStepOverRange::GetDescription(), lldb_private::ThreadPlanStepThrough::GetDescription(), lldb_private::ThreadPlanStepUntil::GetDescription(), lldb_private::ThreadSpec::GetDescription(), lldb_private::Type::GetDescription(), lldb_private::TypeCategoryImpl::GetDescription(), lldb_private::TypeFilterImpl::GetDescription(), lldb_private::TypeFormatImpl_EnumType::GetDescription(), lldb_private::TypeFormatImpl_Format::GetDescription(), lldb_private::TypeImpl::GetDescription(), lldb_private::TypeMemberFunctionImpl::GetDescription(), lldb_private::WatchpointList::GetDescription(), lldb_private::Breakpoint::GetDescriptionForType(), lldb_private::ValueObject::GetExpressionPath(), lldb_private::ValueObjectRegister::GetExpressionPath(), PlatformPOSIX::GetFile(), lldb_private::CommandObject::GetFormattedCommandArguments(), lldb_private::PlatformDarwin::GetFullNameForDylib(), lldb_private::PlatformWindows::GetFullNameForDylib(), lldb_private::MemoryHistoryASan::GetHistoryThreads(), NSIndexPathSyntheticFrontEnd::Impl::InlinedIndexes::GetIndexAtIndex(), lldb_private::IOHandlerEditline::GetLine(), lldb_private::IOHandlerEditline::GetLines(), lldb_private::ValueObject::GetLocationAsCStringImpl(), lldb_private::Module::GetMemoryObjectFile(), lldb_private::ObjCLanguage::GetMethodNameVariants(), CommandObjectTypeCategoryDefine::GetOptions(), PlatformPOSIX::GetPlatformSpecificConnectionInformation(), lldb_private::FormatManager::GetPossibleMatches(), lldb_private::PlatformMacOSX::GetSDKDirectory(), lldb_private::PlatformDarwin::GetSDKDirectoryForModules(), lldb_private::Platform::GetStatus(), lldb_private::platform_aix::PlatformAIX::GetStatus(), lldb_private::platform_freebsd::PlatformFreeBSD::GetStatus(), lldb_private::platform_linux::PlatformLinux::GetStatus(), lldb_private::platform_netbsd::PlatformNetBSD::GetStatus(), lldb_private::platform_openbsd::PlatformOpenBSD::GetStatus(), lldb_private::PlatformAppleSimulator::GetStatus(), lldb_private::PlatformRemoteDarwinDevice::GetStatus(), lldb_private::Process::GetStatus(), lldb_private::Thread::GetStatus(), lldb_private::Target::StopHookCoded::GetSubclassDescription(), lldb_private::Target::StopHookScripted::GetSubclassDescription(), CommandObjectSourceInfo::GetSymbolContextsForAddress(), lldb_private::ClangExpressionSourceCode::GetText(), lldb_private::Scalar::GetValue(), lldb_private::wasm::ProcessWasm::GetWasmCallStack(), lldb_private::wasm::ProcessWasm::GetWasmVariable(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qC(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qHostInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qLaunchGDBServer(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qMemoryRegionInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qPlatform_chmod(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qPlatform_mkdir(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qRegisterInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_QSaveRegisterState(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qSpeedTest(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qWatchpointSupportInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_vCont_actions(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_Close(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_FStat(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_Mode(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_Open(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_pRead(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_pWrite(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_symlink(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_unlink(), CommandObjectThreadSiginfo::HandleOneThread(), lldb_private::Process::HandleProcessStateChangedEvent(), lldb_private::CommandInterpreter::Initialize(), lldb_private::platform_android::AdbClient::internalShell(), lldb_private::REPL::IOHandlerActivated(), lldb_private::IOHandlerConfirm::IOHandlerConfirm(), CommandObjectCommandsScriptAdd::IOHandlerInputComplete(), CommandObjectTypeSummaryAdd::IOHandlerInputComplete(), CommandObjectTypeSynthAdd::IOHandlerInputComplete(), lldb_private::CommandInterpreter::IOHandlerInputComplete(), lldb_private::Thread::JumpToLine(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::KillSpawnedProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::LaunchGDBServer(), lldb_private::ProcessDebugger::LaunchProcess(), lldb_private::formatters::LibCxxAtomicSummaryProvider(), lldb_private::formatters::LibcxxChronoMonthSummaryProvider(), LibcxxChronoTimepointDaysSummaryProvider(), LibcxxChronoTimePointSecondsSummaryProvider(), lldb_private::formatters::LibcxxChronoWeekdaySummaryProvider(), lldb_private::formatters::LibcxxChronoYearMonthDaySummaryProvider(), lldb_private::formatters::LibcxxFunctionSummaryProvider(), lldb_private::formatters::LibcxxSmartPointerSummaryProvider(), lldb_private::formatters::LibcxxStdSliceArraySummaryProvider(), lldb_private::formatters::LibcxxVariantSummaryProvider(), lldb_private::formatters::LibStdcppSmartPointerSummaryProvider(), lldb_private::formatters::LibStdcppVariantSummaryProvider(), EmulationStateARM::LoadRegistersStateFromDictionary(), lldb_private::Module::LoadScriptingResourceInTarget(), LocateExecutableScriptingResourcesFromDSYM(), lldb_private::StringList::LogDump(), LookupFileAndLineInModule(), LookupFunctionInModule(), LookupSymbolInModule(), LookupTypeHere(), LookupTypeInModule(), MakeSpeedTestPacket(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::MakeUrl(), lldb_private::formatters::MsvcStlSmartPointerSummaryProvider(), lldb_private::formatters::MsvcStlTreeIterSummaryProvider(), lldb_private::formatters::MsvcStlVariantSummaryProvider(), lldb_private::formatters::NSArraySummaryProvider(), lldb_private::formatters::NSBundleSummaryProvider(), lldb_private::formatters::NSDataSummaryProvider(), lldb_private::formatters::NSDateSummaryProvider(), lldb_private::formatters::NSDecimalNumberSummaryProvider(), lldb_private::formatters::NSDictionarySummaryProvider(), lldb_private::formatters::NSError_SummaryProvider(), lldb_private::formatters::NSException_SummaryProvider(), lldb_private::formatters::NSIndexSetSummaryProvider(), lldb_private::formatters::NSMachPortSummaryProvider(), lldb_private::formatters::NSNotificationSummaryProvider(), NSNumber_FormatChar(), NSNumber_FormatDouble(), NSNumber_FormatFloat(), NSNumber_FormatInt(), NSNumber_FormatLong(), NSNumber_FormatShort(), lldb_private::formatters::NSNumberSummaryProvider(), lldb_private::formatters::NSSetSummaryProvider(), lldb_private::formatters::NSStringSummaryProvider(), lldb_private::formatters::NSTaggedString_SummaryProvider(), lldb_private::formatters::NSTimeZoneSummaryProvider(), lldb_private::formatters::ObjCBOOLSummaryProvider(), lldb_private::formatters::ObjCClassSummaryProvider(), lldb_private::formatters::ObjCSELSummaryProvider(), Offset(), lldb_private::operator<<(), operator<<(), operator<<(), lldb_private::CommandInterpreter::OutputFormattedHelpText(), lldb_private::CommandInterpreter::OutputHelpText(), lldb_private::Options::ParseAlias(), ParseEntry(), InstructionLLVMC::ParseOperands(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread(), ABIMacOSX_arm64::PrepareTrivialCall(), ABISysV_arm64::PrepareTrivialCall(), ABISysV_mips64::PrepareTrivialCall(), ABISysV_mips::PrepareTrivialCall(), ABISysV_ppc64::PrepareTrivialCall(), ABISysV_ppc::PrepareTrivialCall(), ABISysV_s390x::PrepareTrivialCall(), ABISysV_x86_64::PrepareTrivialCall(), ABIWindows_x86_64::PrepareTrivialCall(), lldb_private::FormatEntity::PrettyPrintFunctionArguments(), lldb_private::Language::PrintAllLanguages(), lldb_private::CommandInterpreter::PrintCommandOutput(), InterpreterStackFrame::PrintData(), lldb_private::Target::PrintDummySignals(), printMemoryTags(), CommandObjectTargetModulesList::PrintModule(), PrintOption(), PrintPlanElement(), CommandObjectProcessHandle::PrintSignal(), CommandObjectProcessHandle::PrintSignalHeader(), lldb_private::CommandInterpreter::PrintWarningsIfNecessary(), lldb_private::Editline::PromptForIndex(), PutCStringColorHighlighted(), PlatformPOSIX::PutFile(), PutSLEB128(), lldb_private::DataExtractor::PutToLog(), PutULEB128(), QuotedCString(), lldb_private::Instruction::ReadArray(), lldb_private::Instruction::ReadDictionary(), lldb_private::formatters::ReadEncodedBufferAndDumpToStream(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ReadFile(), UnwindAssemblyInstEmulation::ReadMemory(), lldb_private::EmulateInstruction::ReadMemoryDefault(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ReadMemoryTags(), lldb_private::ValueObject::ReadPointedString(), lldb_private::AppleObjCTypeEncodingParser::ReadQuotedString(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ReadRegister(), UnwindAssemblyInstEmulation::ReadRegister(), lldb_private::EmulateInstruction::ReadRegisterDefault(), lldb_private::AppleObjCTypeEncodingParser::ReadStructName(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::ReadXferObject(), lldb::SBProcess::ReportEventState(), lldb_private::CommandInterpreter::ResolveCommandImpl(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::RestoreRegisterState(), lldb_private::IOHandlerPythonInterpreter::Run(), RunScriptFormatKeyword(), lldb_private::Process::RunThreadPlan(), lldb_private::ScriptInterpreterPythonImpl::ScriptInterpreterPythonImpl(), lldb_private::BreakpointResolverFileLine::SearchCallback(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendEnvironmentPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendLaunchArchPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendLaunchEventDataPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendRawPacketNoLock(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendSetCurrentThreadPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendSpeedTestPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ServeSymbolLookups(), lldb_private::CommandObjectExpression::CommandOptions::SetOptionValue(), lldb_private::OptionGroupWatchpoint::SetOptionValue(), lldb_private::SaveCoreOptions::SetPluginName(), lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo(), lldb_private::OptionValueEnumeration::SetValueFromString(), lldb_private::OptionValueLanguage::SetValueFromString(), lldb_private::formatters::StdlibCoroutineHandleSummaryProvider(), InterpreterStackFrame::SummarizeValue(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SyncThreadState(), lldb_private::EmulateInstructionARM::TestEmulation(), lldb_private::Instruction::TestEmulation(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::TestPacketSpeed(), lldb_private::OptionArgParser::ToFormat(), lldb_private::OptionValueFileColonLine::ToJSON(), lldb_private::OptionArgParser::ToOptionEnum(), lldb_private::FieldEnum::Enumerator::ToXML(), lldb_private::FieldEnum::ToXML(), lldb_private::RegisterFlags::Field::ToXML(), lldb_private::RegisterFlags::ToXML(), TryDumpSpecialEscapedChar(), IRForTarget::UnfoldConstant(), lldb_private::PlatformWindows::UnloadImage(), lldb_private::Statusline::UpdateScrollWindow(), lldb_private::formatters::VectorTypeSummaryProvider(), lldb_private::formatters::WCharStringSummaryProvider(), lldb_private::formatters::WCharSummaryProvider(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteFile(), lldb_private::EmulateInstruction::WriteMemoryDefault(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteMemoryTags(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteRegister(), UnwindAssemblyInstEmulation::WriteRegister(), and lldb_private::EmulateInstruction::WriteRegisterDefault().
PrintfAsRawHex8()
size_t Stream::PrintfAsRawHex8 (const char * format, ...)
Format a C string from a printf style format and variable arguments and encode and append the resulting C string as hex bytes.
Parameters
[in] format A printf style format string.
[in] ... Any additional arguments needed for the printf format string.
Returns
The number of bytes that were appended to the stream.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 229 of file Stream.cpp.
References _PutHex8(), and lldb_private::VASprintf().
PrintfVarArg()
size_t Stream::PrintfVarArg (const char * format, va_list args)
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 143 of file Stream.cpp.
References eBinary, m_flags, lldb_private::VASprintf(), and Write().
Referenced by lldb_private::CommandReturnObject::AppendErrorWithFormat(), lldb_private::CommandReturnObject::AppendMessageWithFormat(), lldb_private::CommandReturnObject::AppendNoteWithFormat(), lldb_private::CommandReturnObject::AppendWarningWithFormat(), lldb_private::XMLDocument::ErrorCallback(), lldb_private::DiagnosticManager::Printf(), Printf(), and Sprintf().
PutBytesAsRawHex8()
size_t Stream::PutBytesAsRawHex8 (const void * src, size_t src_len, lldb::ByteOrder src_byte_order = lldb::eByteOrderInvalid, lldb::ByteOrder dst_byte_order = lldb::eByteOrderInvalid)
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 391 of file Stream.cpp.
References _PutHex8(), eBinary, lldb::eByteOrderInvalid, m_byte_order, and m_flags.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::DoAttachToProcessWithName(), CommandObjectProcessGDBRemotePacketMonitor::DoExecute(), CommandObjectProcessKDPPacketSend::DoExecute(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoWriteMemory(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_g(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qGetWorkingDir(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qMemTags(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::RunShellCommand(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendEnvironmentPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::SendONotification(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendStdinNotification(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ServeSymbolLookups(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteAllRegisters(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteMemoryTags(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteRegister().
PutChar()
size_t Stream::PutChar (char ch)
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 131 of file Stream.cpp.
References Write().
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::AddProcessThreads(), lldb_private::plugin::dwarf::DWARFDIE::AppendTypeName(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::AutoCompleteDiskFileOrDirectory(), CommunicationKDP::CheckForPacket(), CollectRegNums(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ConfigureRemoteStructuredData(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse_DebugServerStyle(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::CreateSymlink(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::Detach(), lldb_private::SourceManager::DisplaySourceLinesWithLineNumbersUsingLastFile(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoAttachToProcessWithName(), CommandObjectTargetFrameProviderList::DoExecute(), CommandObjectThreadBacktrace::DoExtendedBacktrace(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoResume(), lldb_private::Address::Dump(), lldb_private::AddressRange::Dump(), lldb_private::Event::Dump(), lldb_private::Opcode::Dump(), lldb_private::Property::Dump(), lldb_private::ScriptedFrameProviderDescriptor::Dump(), lldb_private::Symbol::Dump(), lldb_private::SymbolFileCommon::Dump(), lldb_private::UnwindPlan::Row::AbstractRegisterLocation::Dump(), lldb_private::UnwindPlan::Row::Dump(), lldb_private::UnwindPlan::Row::FAValue::Dump(), lldb_private::Variable::Dump(), lldb_private::ProcessInstanceInfo::DumpAsTableRow(), DumpChar(), DumpCharacter(), lldb_private::DumpDataExtractor(), lldb_private::Variable::DumpDeclaration(), lldb_private::StructuredDataDarwinLog::DumpHeader(), lldb_private::OptionValueProperties::DumpPropertyValue(), lldb_private::OptionValue::DumpQualifiedName(), lldb_private::Property::DumpQualifiedName(), lldb_private::DumpRegisterValue(), lldb_private::LineEntry::DumpStopContext(), lldb_private::SymbolContext::DumpStopContext(), EntityPersistentVariable::DumpToLog(), EntityRegister::DumpToLog(), EntityResultVariable::DumpToLog(), EntitySymbol::DumpToLog(), EntityVariableBase::DumpToLog(), lldb_private::FormatEntity::Formatter::DumpValue(), lldb_private::OptionValueDictionary::DumpValue(), EOL(), lldb_private::SymbolContext::FindBestGlobalDataSymbol(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), lldb_private::FormatHelpTextCallback(), lldb_private::Options::GenerateOptionUsage(), lldb_private::BreakpointLocationCollection::GetDescription(), lldb_private::StopInfoMachException::GetDescription(), lldb_private::StructuredData::Array::GetDescription(), lldb_private::StructuredData::Dictionary::GetDescription(), lldb_private::ThreadPlanStepInRange::GetDescription(), lldb_private::ThreadPlanStepOverRange::GetDescription(), lldb_private::TypeCategoryImpl::GetDescription(), lldb_private::Broadcaster::BroadcasterImpl::GetEventNames(), lldb_private::ValueObject::GetExpressionPath(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qHostInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qLaunchGDBServer(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qLaunchSuccess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qMemoryRegionInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qMemTags(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qModuleInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qPathComplete(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qPlatform_shell(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qRegisterInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qXfer(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_Close(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_Exists(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_Open(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_pRead(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_pWrite(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_Size(), lldb_private::StructuredDataDarwinLog::HandleDisplayOfEvent(), CommandObjectThreadSiginfo::HandleOneThread(), lldb_private::Debugger::HandleProcessEvent(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::LaunchProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::MakeDirectory(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::OpenFile(), operator<<(), lldb_private::CommandInterpreter::OutputHelpText(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread(), PrettyPrintFunctionNameWithArgs(), PrettyPrintFunctionNameWithArgs(), CommandObjectTargetModulesList::PrintModule(), PrintOption(), PutCString(), lldb_private::StreamGDBRemote::PutEscapedBytes(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ReadAllRegisters(), ReadCStringFromMemory(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::RunShellCommand(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendNotificationPacketNoLock(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::SendONotification(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendSetCurrentThreadPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::SendWResponse(), lldb_private::Target::SerializeBreakpointsToFile(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetFilePermissions(), lldb_private::SaveCoreOptions::SetPluginName(), lldb_private::FieldEnum::ToXML(), lldb_private::RegisterFlags::ToXML(), UUIDsMatch(), lldb_private::formatters::VectorTypeSummaryProvider(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteAllRegisters().
PutCString()
size_t Stream::PutCString (llvm::StringRef cstr)
Output a C string to the stream.
Print a C string cstr to the stream.
Parameters
[in] cstr The string to be output to the stream.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 65 of file Stream.cpp.
References eBinary, m_flags, PutChar(), and Write().
Referenced by _PutHex8(), CommandObjectTargetSymbolsAdd::AddSymbolsForFile(), CommandObjectTargetSymbolsAdd::AddSymbolsForUUID(), lldb_private::plugin::dwarf::DWARFDIE::AppendTypeName(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::AutoCompleteDiskFileOrDirectory(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::BuildTargetXml(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::CalculateMD5(), chown_file(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ConfigureRemoteStructuredData(), lldb_private::ProcessLaunchInfo::ConvertArgumentsForLaunchingInShell(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse_DebugServerStyle(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::CreateSymlink(), lldb_private::formatters::CXXFunctionPointerSummaryProvider(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoAttachToProcessWithName(), CommandObjectFrameRecognizerList::DoExecute(), CommandObjectPlatformShell::DoExecute(), CommandObjectProcessGDBRemotePacketMonitor::DoExecute(), CommandObjectProcessGDBRemotePacketSend::DoExecute(), CommandObjectProcessStatus::DoExecute(), CommandObjectTargetList::DoExecute(), CommandObjectTargetStopHookAdd::DoExecute(), CommandObjectTargetStopHookList::DoExecute(), CommandObjectTypeFormatterList< FormatterType >::DoExecute(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoResume(), lldb_private::Address::Dump(), lldb_private::ConstString::Dump(), lldb_private::EmulateInstruction::Context::Dump(), lldb_private::EventData::Dump(), lldb_private::FileAction::Dump(), lldb_private::FileSpecList::Dump(), lldb_private::Instruction::Dump(), lldb_private::ModuleSpec::Dump(), lldb_private::ObjectFileJIT::Dump(), lldb_private::Opcode::Dump(), lldb_private::plugin::dwarf::AppleDWARFIndex::Dump(), lldb_private::plugin::dwarf::DebugNamesDWARFIndex::Dump(), lldb_private::plugin::dwarf::DWARFFormValue::Dump(), lldb_private::Process::ProcessEventData::Dump(), lldb_private::ProcessInstanceInfo::Dump(), lldb_private::ProgressEventData::Dump(), lldb_private::ScriptedFrameProviderDescriptor::Dump(), lldb_private::StackID::Dump(), lldb_private::SymbolContextList::Dump(), lldb_private::SymbolFileCommon::Dump(), lldb_private::Symtab::Dump(), lldb_private::Target::Dump(), lldb_private::Type::Dump(), lldb_private::UnwindPlan::Dump(), lldb_private::UnwindPlan::Row::AbstractRegisterLocation::Dump(), lldb_private::UnwindPlan::Row::FAValue::Dump(), lldb_private::UUID::Dump(), lldb_private::Variable::Dump(), ObjectFileCOFF::Dump(), ObjectFileELF::Dump(), ObjectFileMachO::Dump(), ObjectFilePECOFF::Dump(), DumpAddress(), lldb_private::Properties::DumpAllDescriptions(), lldb_private::ProcessInstanceInfo::DumpAsTableRow(), DumpChar(), ObjectFilePECOFF::DumpCOFFHeader(), DumpCommaSeparatedChildEntryNames(), lldb_private::DumpDataExtractor(), ObjectFileELF::DumpDependentModules(), ObjectFilePECOFF::DumpDependentModules(), ObjectFilePECOFF::DumpDOSHeader(), DumpDWARFExpr(), DumpDwoFilesTable(), ObjectFileELF::DumpELFDynamic(), ObjectFileELF::DumpELFHeader(), ObjectFileELF::DumpELFProgramHeaders(), ObjectFileELF::DumpELFSectionHeaders(), lldb_private::OptionValueEnumeration::DumpEnum(), DumpEnumValue(), lldb_private::StructuredDataDarwinLog::DumpHeader(), DumpModuleArchitecture(), DumpModuleUUID(), InstructionLLVMC::DumpOperand(), ObjectFilePECOFF::DumpOptCOFFHeader(), DumpOsoFilesTable(), CommunicationKDP::DumpPacket(), lldb_private::ValueObject::DumpPrintableRepresentation(), lldb_private::OptionValueProperties::DumpPropertyValue(), CommandObjectRegisterRead::DumpRegister(), DumpRegisterName(), lldb_private::DumpRegisterValue(), ObjectFilePECOFF::DumpSectionHeaders(), lldb_private::InlineFunctionInfo::DumpStopContext(), lldb_private::SymbolContext::DumpStopContext(), DumpString(), lldb_private::Symbol::DumpSymbolContext(), lldb_private::ProcessInstanceInfo::DumpTableHeader(), DumpTargetInfo(), DumpTargetList(), lldb_private::TypeSystemClang::DumpTypeDescription(), lldb_private::StackFrame::DumpUsingFormat(), lldb_private::FormatEntity::Formatter::DumpValue(), lldb_private::OptionValueArch::DumpValue(), lldb_private::OptionValueArray::DumpValue(), lldb_private::OptionValueBoolean::DumpValue(), lldb_private::OptionValueChar::DumpValue(), lldb_private::OptionValueDictionary::DumpValue(), lldb_private::OptionValueEnumeration::DumpValue(), lldb_private::OptionValueFileColonLine::DumpValue(), lldb_private::OptionValueFileSpec::DumpValue(), lldb_private::OptionValueFileSpecList::DumpValue(), lldb_private::OptionValueFormat::DumpValue(), lldb_private::OptionValueFormatEntity::DumpValue(), lldb_private::OptionValueLanguage::DumpValue(), lldb_private::OptionValuePathMappings::DumpValue(), lldb_private::OptionValueRegex::DumpValue(), lldb_private::OptionValueSInt64::DumpValue(), lldb_private::OptionValueString::DumpValue(), lldb_private::OptionValueUInt64::DumpValue(), lldb_private::OptionValueUUID::DumpValue(), CommandObjectTargetVariable::DumpValueObject(), lldb_private::StackFrameList::FetchFramesUpTo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), lldb_private::FormatEntity::Formatter::Format(), Format(), lldb_private::FormatEntity::FormatFileSpec(), lldb_private::CommandObjectMultiword::GenerateHelpText(), lldb_private::Options::GenerateOptionUsage(), lldb_private::BreakpointID::GetCanonicalReference(), lldb::SBAddress::GetDescription(), lldb::SBBlock::GetDescription(), lldb::SBBreakpointLocation::GetDescription(), lldb::SBCommandReturnObject::GetDescription(), lldb::SBCompileUnit::GetDescription(), lldb::SBData::GetDescription(), lldb::SBDebugger::GetDescription(), lldb::SBDeclaration::GetDescription(), lldb::SBEvent::GetDescription(), lldb::SBEvent::GetDescription(), lldb::SBFileSpec::GetDescription(), lldb::SBFileSpecList::GetDescription(), lldb::SBFrame::GetDescription(), lldb::SBLineEntry::GetDescription(), lldb::SBModule::GetDescription(), lldb::SBProcess::GetDescription(), lldb::SBSection::GetDescription(), lldb::SBSymbol::GetDescription(), lldb::SBSymbolContext::GetDescription(), lldb::SBTarget::GetDescription(), lldb::SBThread::GetDescription(), lldb::SBType::GetDescription(), lldb::SBTypeEnumMember::GetDescription(), lldb::SBTypeMember::GetDescription(), lldb::SBValue::GetDescription(), lldb::SBWatchpoint::GetDescription(), lldb_private::AppleThreadPlanStepThroughDirectDispatch::GetDescription(), lldb_private::Breakpoint::GetDescription(), lldb_private::BreakpointID::GetDescription(), lldb_private::BreakpointLocation::GetDescription(), lldb_private::BreakpointName::GetDescription(), lldb_private::BreakpointOptions::GetDescription(), lldb_private::BreakpointResolverAddress::GetDescription(), lldb_private::BreakpointResolverScripted::GetDescription(), lldb_private::ScriptedThreadPlan::GetDescription(), lldb_private::ScriptSummaryFormat::GetDescription(), lldb_private::SearchFilterByModule::GetDescription(), lldb_private::SearchFilterByModuleList::GetDescription(), lldb_private::SearchFilterByModuleListAndCU::GetDescription(), lldb_private::StopInfoMachException::GetDescription(), lldb_private::Symbol::GetDescription(), lldb_private::SymbolContext::GetDescription(), lldb_private::SymbolContextSpecifier::GetDescription(), lldb_private::Target::StopHook::GetDescription(), lldb_private::ThreadPlanNull::GetDescription(), lldb_private::ThreadPlanStepThrough::GetDescription(), lldb_private::ThreadSpec::GetDescription(), lldb_private::Type::GetDescription(), lldb_private::TypeCategoryImpl::GetDescription(), lldb_private::TypeImpl::GetDescription(), lldb_private::WatchpointOptions::GetDescription(), lldb_private::Broadcaster::BroadcasterImpl::GetEventNames(), lldb_private::ValueObject::GetExpressionPath(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetFileExists(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetFileLoadAddress(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetFilePermissions(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetFileSize(), lldb_private::CPlusPlusLanguage::GetFunctionDisplayName(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetModuleInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetModulesInfo(), lldb_private::plugin::dwarf::DWARFDIE::GetName(), PlatformPOSIX::GetPlatformSpecificConnectionInformation(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetRemoteQSupported(), lldb_private::IRExecutionUnit::GetRunnableInfo(), lldb::SBThread::GetStatus(), lldb_private::PlatformRemoteDarwinDevice::GetStatus(), lldb::SBThread::GetStopDescription(), lldb_private::Target::StopHookCommandLine::GetSubclassDescription(), lldb_private::Target::StopHookScripted::GetSubclassDescription(), lldb_private::CommandObject::GetSyntax(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetThreadPacketSupported(), lldb_private::Scalar::GetValue(), lldb_private::wasm::ProcessWasm::GetWasmVariable(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qC(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qHostInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qLaunchGDBServer(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qLaunchSuccess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qMemoryRegionInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qModuleInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qPlatform_shell(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qRegisterInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qSaveCore(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qSpeedTest(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_MD5(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_Open(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_pRead(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_pWrite(), lldb_private::StructuredDataDarwinLog::HandleArrivalOfStructuredData(), HandleFunctionNameWithArgs(), lldb_private::Process::HandleProcessStateChangedEvent(), Indent(), CommandObjectCommandsScriptAdd::IOHandlerActivated(), CommandObjectTypeSummaryAdd::IOHandlerActivated(), CommandObjectTypeSynthAdd::IOHandlerActivated(), lldb_private::ScriptInterpreterPythonImpl::IOHandlerActivated(), lldb_private::IOHandlerConfirm::IOHandlerConfirm(), CommandObjectCommandsAddRegex::IOHandlerInputComplete(), lldb_private::StringList::Join(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::LaunchGDBServer(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::LaunchProcess(), lldb_private::Module::LogMessage(), lldb_private::Module::LogMessageVerboseBacktrace(), LookupFileAndLineInModule(), LookupFunctionInModule(), LookupSymbolInModule(), LookupTypeHere(), LookupTypeInModule(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::MakeDirectory(), MakeSpeedTestPacket(), lldb_private::formatters::NSIndirectTaggedString_SummaryProvider(), NSNumber_FormatInt128(), lldb_private::formatters::ObjCBooleanSummaryProvider(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::OpenFile(), operator<<(), lldb_private::CommandInterpreter::OutputFormattedHelpText(), InstructionLLVMC::ParseOperands(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread(), ABIMacOSX_arm64::PrepareTrivialCall(), ABISysV_arm64::PrepareTrivialCall(), ABISysV_mips64::PrepareTrivialCall(), ABISysV_mips::PrepareTrivialCall(), ABISysV_ppc64::PrepareTrivialCall(), ABISysV_ppc::PrepareTrivialCall(), ABISysV_s390x::PrepareTrivialCall(), ABISysV_x86_64::PrepareTrivialCall(), ABIWindows_x86_64::PrepareTrivialCall(), lldb_private::FormatEntity::PrettyPrintFunctionArguments(), PrettyPrintFunctionNameWithArgs(), PrettyPrintFunctionNameWithArgs(), PrintFunctionNameWithArgs(), PrintFunctionNameWithArgs(), lldb_private::Disassembler::PrintInstructions(), printMemoryTags(), CommandObjectTargetModulesList::PrintModule(), PrintOption(), CommandObjectProcessHandle::PrintSignal(), PutCStringColorHighlighted(), lldb_private::Module::ReportErrorIfModifyDetected(), lldb_private::CommandInterpreter::ResolveCommandImpl(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::RunShellCommand(), lldb_private::Process::RunThreadPlan(), lldb_private::process_gdb_remote::ProcessGDBRemote::SaveCore(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SaveRegisterState(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendEnvironmentPacket(), CommunicationKDP::SendRequestConnect(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendSetCurrentThreadPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendSpeedTestPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendStdinNotification(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::SendStructuredDataPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceGetBinaryData(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceGetState(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceStart(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceStop(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceSupported(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ServeSymbolLookups(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetFilePermissions(), lldb_private::SaveCoreOptions::SetPluginName(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetSTDERR(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetSTDIN(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetSTDOUT(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetWorkingDir(), lldb_private::ThreadPlanStepInstruction::ShouldStop(), lldb_private::OptionArgParser::ToFormat(), lldb_private::OptionArgParser::ToOptionEnum(), IRForTarget::UnfoldConstant(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::Unlink(), UUIDsMatch(), UnwindAssemblyInstEmulation::WriteMemory(), UnwindAssemblyInstEmulation::WriteRegister(), and lldb_private::EmulateInstruction::WriteRegisterDefault().
PutCStringColorHighlighted()
void Stream::PutCStringColorHighlighted (llvm::StringRef text, std::optional< HighlightSettings > settings = std::nullopt)
Output a C string to the stream with color highlighting.
Print a C string text to the stream, applying color highlighting to the portions of the string that match the regex pattern pattern. The pattern is matched as many times as possible throughout the string. If pattern is nullptr, then no highlighting is applied.
The highlighting is applied by enclosing the matching text in ANSI color codes. The prefix parameter specifies the ANSI code to start the color (the standard value is assumed to be 'ansi.fg.red', representing red foreground), and the suffix parameter specifies the ANSI code to end the color (the standard value is assumed to be 'ansi.normal', resetting to default text style). These constants should be defined appropriately in your environment.
Parameters
[in] text The string to be output to the stream.
[in] settings Optional print hilight settings.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 75 of file Stream.cpp.
References lldb_private::ansi::FormatAnsiTerminalCodes(), Printf(), and PutCString().
Referenced by lldb_private::Address::Dump(), lldb_private::SymbolContext::DumpStopContext(), lldb_private::Symbol::GetDescription(), LookupSymbolInModule(), and operator<<().
PutDouble()
size_t Stream::PutDouble (double d, lldb::ByteOrder byte_order = lldb::eByteOrderInvalid)
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 350 of file Stream.cpp.
References lldb::eByteOrderInvalid, lldb_private::endian::InlHostByteOrder(), m_byte_order, and PutRawBytes().
PutFloat()
size_t Stream::PutFloat (float f, lldb::ByteOrder byte_order = lldb::eByteOrderInvalid)
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 343 of file Stream.cpp.
References lldb::eByteOrderInvalid, lldb_private::endian::InlHostByteOrder(), m_byte_order, and PutRawBytes().
PutHex16()
size_t Stream::PutHex16 (uint16_t uvalue, lldb::ByteOrder byte_order = lldb::eByteOrderInvalid)
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 275 of file Stream.cpp.
References _PutHex8(), lldb::eByteOrderInvalid, lldb::eByteOrderLittle, and m_byte_order.
Referenced by CommunicationKDP::CheckForPacket(), lldb_private::plugin::dwarf::DWARFFormValue::Dump(), CommunicationKDP::MakeRequestPacketHeader(), PutMaxHex64(), CommunicationKDP::SendRequestConnect(), and CommunicationKDP::SendRequestReattach().
PutHex32()
size_t Stream::PutHex32 (uint32_t uvalue, lldb::ByteOrder byte_order = lldb::eByteOrderInvalid)
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 291 of file Stream.cpp.
References _PutHex8(), lldb::eByteOrderInvalid, lldb::eByteOrderLittle, and m_byte_order.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::AutoCompleteDiskFileOrDirectory(), CommunicationKDP::CheckForPacket(), RegisterContextDarwin_arm64_Mach::Create_LC_THREAD(), RegisterContextDarwin_arm_Mach::Create_LC_THREAD(), RegisterContextDarwin_riscv32_Mach::Create_LC_THREAD(), RegisterContextDarwin_x86_64_Mach::Create_LC_THREAD(), CreateAllImageInfosPayload(), lldb_private::plugin::dwarf::DWARFFormValue::Dump(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qPlatform_shell(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::MakeDirectory(), CommunicationKDP::MakeRequestPacketHeader(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::OpenFile(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread(), PutMaxHex64(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::RunShellCommand(), ObjectFileMachO::SaveCore(), CommunicationKDP::SendRequestReadMemory(), CommunicationKDP::SendRequestReadRegisters(), CommunicationKDP::SendRequestResume(), CommunicationKDP::SendRequestWriteMemory(), CommunicationKDP::SendRequestWriteRegisters(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetFilePermissions().
PutHex64()
size_t Stream::PutHex64 (uint64_t uvalue, lldb::ByteOrder byte_order = lldb::eByteOrderInvalid)
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 307 of file Stream.cpp.
References _PutHex8(), lldb::eByteOrderInvalid, lldb::eByteOrderLittle, and m_byte_order.
Referenced by CreateAllImageInfosPayload(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::Detach(), lldb_private::CoreFileMemoryRange::Dump(), lldb_private::plugin::dwarf::DWARFFormValue::Dump(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle__M(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qFileLoadAddress(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qModuleInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_MD5(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_Size(), lldb_private::DynamicLoader::LoadBinaryWithUUIDAndAddress(), DynamicLoaderDarwinKernel::KextImageInfo::LoadImageUsingMemoryModule(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread(), PutMaxHex64(), and ObjectFileMachO::SaveCore().
PutHex8()
size_t Stream::PutHex8 (uint8_t uvalue)
Append an uint8_t value in the hexadecimal format to the stream.
Parameters
[in] uvalue The value to append.
Returns
The number of bytes that were appended to the stream.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 269 of file Stream.cpp.
References _PutHex8().
Referenced by AppendHexValue(), CommunicationKDP::CheckForPacket(), ConvertPDBLocationToDWARFExpression(), CreateDWARFExpression(), lldb_private::plugin::dwarf::DWARFFormValue::Dump(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_memory_read(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_p(), lldb_private::npdb::MakeEnregisteredLocationExpressionForComposite(), lldb_private::npdb::MakeGlobalLocationExpression(), MakeRegisterBasedLocationExpressionInternal(), CommunicationKDP::MakeRequestPacketHeader(), lldb_private::npdb::MakeVFrameRelLocationExpression(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread(), PutMaxHex64(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendNotificationPacketNoLock(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::SendWResponse().
PutLongDouble()
size_t Stream::PutLongDouble (long double ld, lldb::ByteOrder byte_order = lldb::eByteOrderInvalid)
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 357 of file Stream.cpp.
References lldb::eByteOrderInvalid, lldb_private::endian::InlHostByteOrder(), m_byte_order, and PutRawBytes().
PutMaxHex64()
size_t Stream::PutMaxHex64 (uint64_t uvalue, size_t byte_size, lldb::ByteOrder byte_order = lldb::eByteOrderInvalid)
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 323 of file Stream.cpp.
References PutHex16(), PutHex32(), PutHex64(), and PutHex8().
Referenced by ConvertPDBLocationToDWARFExpression(), CreateDWARFExpression(), CommandObjectMemoryWrite::DoExecute(), lldb_private::npdb::MakeGlobalLocationExpression(), CommunicationKDP::SendRequestBreakpoint(), CommunicationKDP::SendRequestReadMemory(), CommunicationKDP::SendRequestWriteMemory(), and lldb_private::EmulateInstruction::WriteMemoryUnsigned().
PutNHex8()
size_t Stream::PutNHex8 (size_t n, uint8_t uvalue)
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 245 of file Stream.cpp.
References _PutHex8().
PutPointer()
size_t Stream::PutPointer (void * ptr)
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 338 of file Stream.cpp.
References lldb_private::endian::InlHostByteOrder(), and PutRawBytes().
PutRawBytes()
size_t Stream::PutRawBytes (const void * s, size_t src_len, lldb::ByteOrder src_byte_order = lldb::eByteOrderInvalid, lldb::ByteOrder dst_byte_order = lldb::eByteOrderInvalid)
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 364 of file Stream.cpp.
References _PutHex8(), eBinary, lldb::eByteOrderInvalid, m_byte_order, and m_flags.
Referenced by ConvertPDBLocationToDWARFExpression(), CreateAllImageInfosPayload(), PutDouble(), PutFloat(), PutLongDouble(), PutPointer(), ObjectFileMachO::SaveCore(), CommunicationKDP::SendRawRequest(), and CommunicationKDP::SendRequestWriteMemory().
PutSLEB128()
size_t Stream::PutSLEB128 (int64_t uval)
Output a SLEB128 number to the stream.
Put an SLEB128 uval out to the stream using the printf format in format.
Parameters
[in] uval A uint64_t value that was extracted as a SLEB128 value.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 49 of file Stream.cpp.
References eBinary, m_flags, m_forwarder, and Printf().
Referenced by ConvertPDBLocationToDWARFExpression(), lldb_private::plugin::dwarf::DWARFFormValue::Dump(), MakeRegisterBasedLocationExpressionInternal(), and lldb_private::npdb::MakeVFrameRelLocationExpression().
PutStringAsRawHex8()
size_t Stream::PutStringAsRawHex8 (llvm::StringRef s)
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 418 of file Stream.cpp.
References _PutHex8(), eBinary, and m_flags.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::AutoCompleteDiskFileOrDirectory(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::CalculateMD5(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse_DebugServerStyle(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::CreateSymlink(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetFileExists(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetFileLoadAddress(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetFilePermissions(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetFileSize(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetModuleInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qGetWorkingDir(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qGroupName(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qHostInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qLaunchGDBServer(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qMemoryRegionInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qModuleInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qPathComplete(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qSaveCore(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qUserName(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::LaunchProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::MakeDirectory(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::OpenFile(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::RunShellCommand(), lldb_private::process_gdb_remote::ProcessGDBRemote::SaveCore(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetFilePermissions(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetSTDERR(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetSTDIN(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetSTDOUT(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetWorkingDir(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::Unlink().
PutULEB128()
size_t Stream::PutULEB128 (uint64_t uval)
Output a ULEB128 number to the stream.
Put an ULEB128 uval out to the stream using the printf format in format.
Parameters
[in] uval A uint64_t value that was extracted as a ULEB128 value.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 57 of file Stream.cpp.
References eBinary, m_flags, m_forwarder, and Printf().
Referenced by ConvertPDBLocationToDWARFExpression(), lldb_private::plugin::dwarf::DWARFFormValue::Dump(), lldb_private::npdb::MakeEnregisteredLocationExpressionForComposite(), and MakeRegisterBasedLocationExpressionInternal().
QuotedCString()
void Stream::QuotedCString (const char * cstr, const char * format = "\"%s\"")
Output a quoted C string value to the stream.
Print a double quoted NULL terminated C string to the stream using the printf format in format.
Parameters
[in] cstr A NULL terminated C string value.
[in] format The optional C string format that can be overridden.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 102 of file Stream.cpp.
References Printf().
Referenced by lldb_private::plugin::dwarf::DWARFFormValue::Dump(), and DumpString().
SetAddressByteSize()
void Stream::SetAddressByteSize (uint32_t addr_size)
Set the address size in bytes.
Parameters
[in] addr_size The new size in bytes of an address to use when outputting address and pointer values.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 217 of file Stream.cpp.
References m_addr_size.
Referenced by CommandObjectSourceInfo::DoExecute(), CommandObjectTargetModulesDumpLineTable::DoExecute(), CommandObjectTargetModulesDumpObjfile::DoExecute(), CommandObjectTargetModulesDumpSections::DoExecute(), CommandObjectTargetModulesDumpSeparateDebugInfoFiles::DoExecute(), CommandObjectTargetModulesDumpSymfile::DoExecute(), CommandObjectTargetModulesDumpSymtab::DoExecute(), CommandObjectTargetModulesList::DoExecute(), and CommandObjectTargetModulesLookup::DoExecute().
SetByteOrder()
ByteOrder Stream::SetByteOrder (lldb::ByteOrder byte_order)
Set the byte_order value.
Sets the byte order of the data to extract. Extracted values will be swapped if necessary when decoding.
Parameters
[in] byte_order The byte order value to use when extracting data.
Returns
The old byte order value.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 39 of file Stream.cpp.
References m_byte_order.
Referenced by CommunicationKDP::SendRequestConnect(), and CommunicationKDP::SendRequestReattach().
SetIndentLevel()
void Stream::SetIndentLevel (unsigned level)
Set the current indentation level.
Parameters
[in] level The new indentation level.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 190 of file Stream.cpp.
References m_indent_level.
Referenced by DumpAddress(), lldb_private::Options::GenerateOptionUsage(), lldb_private::StructuredData::Array::GetDescription(), lldb_private::StructuredData::Dictionary::GetDescription(), operator<<(), and lldb_private::CommandCompletions::StopHookIDs().
Write()
size_t lldb_private::Stream::Write (const void * src, size_t src_len) inline
Output character bytes to the stream.
Appends src_len characters from the buffer src to the stream.
Parameters
[in] src A buffer containing at least src_len bytes of data.
[in] src_len A number of bytes to append to the stream.
Returns
The number of bytes that were appended to the stream.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 112 of file Stream.h.
References m_bytes_written, and WriteImpl().
Referenced by _PutHex8(), lldb::SBTypeSummary::CreateWithCallback(), lldb_private::Address::Dump(), DumpAPInt(), DumpStringToStreamWithNewline(), lldb_private::TypeSystemClang::DumpTypeDescription(), DumpValueWithLLVMFormat(), lldb_private::Debugger::FlushProcessOutput(), lldb_private::FormatEntity::Formatter::Format(), lldb_private::AppleObjCRuntime::GetObjectDescription(), lldb_private::StructuredDataDarwinLog::HandleDisplayOfEvent(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::MakeUrl(), operator<<(), PrettyPrintFunctionNameWithArgs(), lldb_private::Debugger::PrintAsync(), lldb_private::Editline::PrintAsync(), lldb_private::IOHandler::PrintAsync(), lldb_private::CommandInterpreter::PrintCommandOutput(), PrintfVarArg(), PutChar(), PutCString(), ReadThreadBytesReceived(), ObjectFileMachO::SaveCore(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendNotificationPacketNoLock(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), CommunicationKDP::SendRequestWriteRegisters(), and lldb_private::StreamTee::WriteImpl().
WriteImpl()
virtual size_t lldb_private::Stream::WriteImpl (const void * src, size_t src_len) protected pure virtual
Output character bytes to the stream.
Appends src_len characters from the buffer src to the stream.
Parameters
[in] src A buffer containing at least src_len bytes of data.
[in] src_len A number of bytes to append to the stream.
Returns
The number of bytes that were appended to the stream.
Implemented in lldb_private::StreamAsynchronousIO, lldb_private::StreamBuffer< N >, lldb_private::StreamBuffer< 4096 >, lldb_private::StreamFile, lldb_private::StreamString, and lldb_private::StreamTee.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Referenced by Write().
Member Data Documentation
m_addr_size
uint32_t lldb_private::Stream::m_addr_size = 4 protected
Size of an address in bytes.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 413 of file Stream.h.
Referenced by GetAddressByteSize(), operator=(), SetAddressByteSize(), and Stream().
m_byte_order
lldb::ByteOrder lldb_private::Stream::m_byte_order protected
Byte order to use when encoding scalar types.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 415 of file Stream.h.
Referenced by GetByteOrder(), operator=(), PutBytesAsRawHex8(), PutDouble(), PutFloat(), PutHex16(), PutHex32(), PutHex64(), PutLongDouble(), PutRawBytes(), SetByteOrder(), Stream(), and Stream().
m_bytes_written
std::size_t lldb_private::Stream::m_bytes_written = 0 protected
Number of bytes written so far.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 417 of file Stream.h.
Referenced by lldb_private::StreamString::Clear(), GetWrittenBytes(), and Write().
m_flags
Flags lldb_private::Stream::m_flags protected
Dump flags.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 412 of file Stream.h.
Referenced by _PutHex8(), GetFlags(), GetFlags(), operator=(), PrintfVarArg(), PutBytesAsRawHex8(), PutCString(), lldb_private::StreamGDBRemote::PutEscapedBytes(), PutRawBytes(), PutSLEB128(), PutStringAsRawHex8(), PutULEB128(), Stream(), and Stream().
m_forwarder
RawOstreamForward lldb_private::Stream::m_forwarder protected
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 461 of file Stream.h.
Referenced by AsRawOstream(), PutSLEB128(), PutULEB128(), Stream(), Stream(), and Stream().
m_indent_level
unsigned lldb_private::Stream::m_indent_level = 0 protected
Indention level.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 416 of file Stream.h.
Referenced by GetIndentLevel(), Indent(), IndentLess(), IndentMore(), operator=(), and SetIndentLevel().
The documentation for this class was generated from the following files:
Stream.h
Stream.cpp