LLDB: lldb_private::UniqueCStringMap< T > Class Template Reference
lldb_private::UniqueCStringMap< T > Class Template Reference
#include <UniqueCStringMap.h>
Classes
struct Compare
struct Entry
Public Types
typedef std::vector< Entry > collection
typedef collection::iterator iterator
typedef collection::const_iterator const_iterator
Public Member Functions
void Append (ConstString unique_cstr, const T &value)
void Append (const Entry &e)
void Clear ()
bool GetValueAtIndex (uint32_t idx, T &value) const
ConstString GetCStringAtIndexUnchecked (uint32_t idx) const
T GetValueAtIndexUnchecked (uint32_t idx) const
const T & GetValueRefAtIndexUnchecked (uint32_t idx) const
ConstString GetCStringAtIndex (uint32_t idx) const
T Find (ConstString unique_cstr, T fail_value) const
const Entry * FindFirstValueForName (ConstString unique_cstr) const
const Entry * FindNextValueForName (const Entry *entry_ptr) const
size_t GetValues (ConstString unique_cstr, std::vector< T > &values) const
size_t GetValues (const RegularExpression &regex, std::vector< T > &values) const
size_t GetSize () const
bool IsEmpty () const
void Reserve (size_t n)
void Sort ()
template<typename TCompare>
void Sort (TCompare tc)
Sort contents of this map using the provided comparator to break ties for entries with the same string value.
void SizeToFit ()
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
llvm::iterator_range< const_iterator > equal_range (ConstString unique_cstr) const
Protected Attributes
collection m_map
Detailed Description
template<typename T>
class lldb_private::UniqueCStringMap< T >
Definition at line 26 of file UniqueCStringMap.h.
Member Typedef Documentation
collection
template<typename T> typedef std::vector<Entry> lldb_private::UniqueCStringMap< T >::collection
Definition at line 35 of file UniqueCStringMap.h.
const_iterator
template<typename T> typedef collection::const_iterator lldb_private::UniqueCStringMap< T >::const_iterator
Definition at line 37 of file UniqueCStringMap.h.
iterator
template<typename T> typedef collection::iterator lldb_private::UniqueCStringMap< T >::iterator
Definition at line 36 of file UniqueCStringMap.h.
Member Function Documentation
Append() [1/2]
template<typename T> void lldb_private::UniqueCStringMap< T >::Append (const Entry & e) inline
Definition at line 46 of file UniqueCStringMap.h.
Append() [2/2]
template<typename T> void lldb_private::UniqueCStringMap< T >::Append (ConstString unique_cstr, const T & value) inline
Definition at line 42 of file UniqueCStringMap.h.
Referenced by lldb_private::Symtab::AppendSymbolNamesToMap(), and DecodeCStrMap().
begin() [1/2]
template<typename T> iterator lldb_private::UniqueCStringMap< T >::begin () inline
Definition at line 196 of file UniqueCStringMap.h.
begin() [2/2]
template<typename T> const_iterator lldb_private::UniqueCStringMap< T >::begin () const inline
Definition at line 198 of file UniqueCStringMap.h.
Clear()
template<typename T> void lldb_private::UniqueCStringMap< T >::Clear () inline
Definition at line 48 of file UniqueCStringMap.h.
end() [1/2]
template<typename T> iterator lldb_private::UniqueCStringMap< T >::end () inline
Definition at line 197 of file UniqueCStringMap.h.
end() [2/2]
template<typename T> const_iterator lldb_private::UniqueCStringMap< T >::end () const inline
Definition at line 199 of file UniqueCStringMap.h.
equal_range()
template<typename T> llvm::iterator_range< const_iterator > lldb_private::UniqueCStringMap< T >::equal_range (ConstString unique_cstr) const inline
Definition at line 203 of file UniqueCStringMap.h.
Find()
template<typename T> T lldb_private::UniqueCStringMap< T >::Find (ConstString unique_cstr, T fail_value) const inline
Definition at line 86 of file UniqueCStringMap.h.
Referenced by DWARFASTParserClang::CopyUniqueClassMethodTypes().
FindFirstValueForName()
template<typename T> const Entry * lldb_private::UniqueCStringMap< T >::FindFirstValueForName (ConstString unique_cstr) const inline
Definition at line 98 of file UniqueCStringMap.h.
FindNextValueForName()
template<typename T> const Entry * lldb_private::UniqueCStringMap< T >::FindNextValueForName (const Entry * entry_ptr) const inline
Definition at line 111 of file UniqueCStringMap.h.
GetCStringAtIndex()
template<typename T> ConstString lldb_private::UniqueCStringMap< T >::GetCStringAtIndex (uint32_t idx) const inline
Definition at line 76 of file UniqueCStringMap.h.
Referenced by DWARFASTParserClang::CopyUniqueClassMethodTypes().
GetCStringAtIndexUnchecked()
template<typename T> ConstString lldb_private::UniqueCStringMap< T >::GetCStringAtIndexUnchecked (uint32_t idx) const inline
Definition at line 62 of file UniqueCStringMap.h.
GetSize()
template<typename T> size_t lldb_private::UniqueCStringMap< T >::GetSize () const inline
Definition at line 148 of file UniqueCStringMap.h.
Referenced by DWARFASTParserClang::CopyUniqueClassMethodTypes(), and EncodeCStrMap().
GetValueAtIndex()
template<typename T> bool lldb_private::UniqueCStringMap< T >::GetValueAtIndex (uint32_t idx, T & value) const inline
Definition at line 54 of file UniqueCStringMap.h.
GetValueAtIndexUnchecked()
template<typename T> T lldb_private::UniqueCStringMap< T >::GetValueAtIndexUnchecked (uint32_t idx) const inline
Definition at line 68 of file UniqueCStringMap.h.
Referenced by DWARFASTParserClang::CopyUniqueClassMethodTypes().
GetValueRefAtIndexUnchecked()
template<typename T> const T & lldb_private::UniqueCStringMap< T >::GetValueRefAtIndexUnchecked (uint32_t idx) const inline
Definition at line 72 of file UniqueCStringMap.h.
GetValues() [1/2]
template<typename T> size_t lldb_private::UniqueCStringMap< T >::GetValues (const RegularExpression & regex, std::vector< T > & values) const inline
Definition at line 134 of file UniqueCStringMap.h.
GetValues() [2/2]
template<typename T> size_t lldb_private::UniqueCStringMap< T >::GetValues (ConstString unique_cstr, std::vector< T > & values) const inline
Definition at line 124 of file UniqueCStringMap.h.
IsEmpty()
template<typename T> bool lldb_private::UniqueCStringMap< T >::IsEmpty () const inline
Definition at line 151 of file UniqueCStringMap.h.
Referenced by DWARFASTParserClang::CopyUniqueClassMethodTypes().
Reserve()
template<typename T> void lldb_private::UniqueCStringMap< T >::Reserve (size_t n) inline
Definition at line 157 of file UniqueCStringMap.h.
Referenced by DecodeCStrMap().
SizeToFit()
template<typename T> void lldb_private::UniqueCStringMap< T >::SizeToFit () inline
Definition at line 189 of file UniqueCStringMap.h.
Sort() [1/2]
template<typename T> void lldb_private::UniqueCStringMap< T >::Sort () inline
Definition at line 168 of file UniqueCStringMap.h.
Referenced by DWARFASTParserClang::CopyUniqueClassMethodTypes(), DecodeCStrMap(), and lldb_private::UniqueCStringMap< EnumeratorInfo >::Sort().
Sort() [2/2]
template<typename T> template<typename TCompare> void lldb_private::UniqueCStringMap< T >::Sort (TCompare tc) inline
Sort contents of this map using the provided comparator to break ties for entries with the same string value.
Definition at line 174 of file UniqueCStringMap.h.
Member Data Documentation
m_map
template<typename T> collection lldb_private::UniqueCStringMap< T >::m_map protected
Definition at line 240 of file UniqueCStringMap.h.
The documentation for this class was generated from the following file:
UniqueCStringMap.h