LLDB: lldb_private::EventDataStructuredData Class Reference
lldb_private::EventDataStructuredData Class Reference
This class handles one or more StructuredData::Dictionary entries that are raised for structured data events.
#include <Event.h>
Public Member Functions
EventDataStructuredData ()
EventDataStructuredData (const lldb::ProcessSP &process_sp, const StructuredData::ObjectSP &object_sp, const lldb::StructuredDataPluginSP &plugin_sp)
~EventDataStructuredData () override
llvm::StringRef GetFlavor () const override
void Dump (Stream *s) const override
const lldb::ProcessSP & GetProcess () const
const StructuredData::ObjectSP & GetObject () const
const lldb::StructuredDataPluginSP & GetStructuredDataPlugin () const
void SetProcess (const lldb::ProcessSP &process_sp)
void SetObject (const StructuredData::ObjectSP &object_sp)
void SetStructuredDataPlugin (const lldb::StructuredDataPluginSP &plugin_sp)
Public Member Functions inherited from lldb_private::EventData
EventData ()
virtual ~EventData ()
virtual Log * GetLogChannel ()
Static Public Member Functions
static const EventDataStructuredData * GetEventDataFromEvent (const Event *event_ptr)
static lldb::ProcessSP GetProcessFromEvent (const Event *event_ptr)
static StructuredData::ObjectSP GetObjectFromEvent (const Event *event_ptr)
static lldb::StructuredDataPluginSP GetPluginFromEvent (const Event *event_ptr)
static llvm::StringRef GetFlavorString ()
Private Member Functions
EventDataStructuredData (const EventDataStructuredData &)=delete
const EventDataStructuredData & operator= (const EventDataStructuredData &)=delete
Private Attributes
lldb::ProcessSP m_process_sp
StructuredData::ObjectSP m_object_sp
lldb::StructuredDataPluginSP m_plugin_sp
Detailed Description
This class handles one or more StructuredData::Dictionary entries that are raised for structured data events.
Definition at line 127 of file Event.h.
Constructor & Destructor Documentation
EventDataStructuredData() [1/3]
EventDataStructuredData::EventDataStructuredData ()
Definition at line 180 of file Event.cpp.
References lldb_private::EventData::EventData(), m_object_sp, m_plugin_sp, and m_process_sp.
Referenced by EventDataStructuredData(), GetEventDataFromEvent(), operator=(), and ~EventDataStructuredData().
EventDataStructuredData() [2/3]
EventDataStructuredData::EventDataStructuredData (const lldb::ProcessSP & process_sp, const StructuredData::ObjectSP & object_sp, const lldb::StructuredDataPluginSP & plugin_sp)
Definition at line 183 of file Event.cpp.
References lldb_private::EventData::EventData(), m_object_sp, m_plugin_sp, and m_process_sp.
~EventDataStructuredData()
EventDataStructuredData::~EventDataStructuredData () override default
References lldb_private::EventData::Event, and EventDataStructuredData().
EventDataStructuredData() [3/3]
lldb_private::EventDataStructuredData::EventDataStructuredData (const EventDataStructuredData &) private delete
References EventDataStructuredData().
Member Function Documentation
Dump()
void EventDataStructuredData::Dump (Stream * s) const override virtual
Reimplemented from lldb_private::EventData.
Definition at line 197 of file Event.cpp.
References m_object_sp.
GetEventDataFromEvent()
const EventDataStructuredData * EventDataStructuredData::GetEventDataFromEvent (const Event * event_ptr) static
Definition at line 235 of file Event.cpp.
References lldb_private::EventData::Event, lldb_private::EventData::EventData(), EventDataStructuredData(), lldb_private::Event::GetData(), lldb_private::EventData::GetFlavor(), and GetFlavorString().
Referenced by GetObjectFromEvent(), GetPluginFromEvent(), and GetProcessFromEvent().
GetFlavor()
llvm::StringRef EventDataStructuredData::GetFlavor () const override virtual
Implements lldb_private::EventData.
Definition at line 193 of file Event.cpp.
References GetFlavorString().
GetFlavorString()
llvm::StringRef EventDataStructuredData::GetFlavorString () static
Definition at line 273 of file Event.cpp.
Referenced by lldb::SBProcess::EventIsStructuredDataEvent(), GetEventDataFromEvent(), and GetFlavor().
GetObject()
const StructuredData::ObjectSP & EventDataStructuredData::GetObject () const
Definition at line 209 of file Event.cpp.
References m_object_sp.
GetObjectFromEvent()
StructuredData::ObjectSP EventDataStructuredData::GetObjectFromEvent (const Event * event_ptr) static
Definition at line 256 of file Event.cpp.
References lldb_private::EventData::Event, and GetEventDataFromEvent().
Referenced by lldb_private::Debugger::HandleProcessEvent().
GetPluginFromEvent()
lldb::StructuredDataPluginSP EventDataStructuredData::GetPluginFromEvent (const Event * event_ptr) static
Definition at line 265 of file Event.cpp.
References lldb_private::EventData::Event, and GetEventDataFromEvent().
Referenced by lldb_private::Debugger::HandleProcessEvent().
GetProcess()
const ProcessSP & EventDataStructuredData::GetProcess () const
Definition at line 205 of file Event.cpp.
References m_process_sp.
GetProcessFromEvent()
ProcessSP EventDataStructuredData::GetProcessFromEvent (const Event * event_ptr) static
Definition at line 247 of file Event.cpp.
References lldb_private::EventData::Event, and GetEventDataFromEvent().
Referenced by lldb::SBProcess::GetProcessFromEvent(), and lldb_private::Debugger::HandleProcessEvent().
GetStructuredDataPlugin()
const lldb::StructuredDataPluginSP & EventDataStructuredData::GetStructuredDataPlugin () const
Definition at line 214 of file Event.cpp.
References m_plugin_sp.
operator=()
const EventDataStructuredData & lldb_private::EventDataStructuredData::operator= (const EventDataStructuredData &) private delete
References EventDataStructuredData().
SetObject()
void EventDataStructuredData::SetObject (const StructuredData::ObjectSP & object_sp)
Definition at line 222 of file Event.cpp.
References m_object_sp.
SetProcess()
void EventDataStructuredData::SetProcess (const lldb::ProcessSP & process_sp)
Definition at line 218 of file Event.cpp.
References m_process_sp.
SetStructuredDataPlugin()
void EventDataStructuredData::SetStructuredDataPlugin (const lldb::StructuredDataPluginSP & plugin_sp)
Definition at line 227 of file Event.cpp.
References m_plugin_sp.
Member Data Documentation
m_object_sp
StructuredData::ObjectSP lldb_private::EventDataStructuredData::m_object_sp private
Definition at line 170 of file Event.h.
Referenced by Dump(), EventDataStructuredData(), EventDataStructuredData(), GetObject(), and SetObject().
m_plugin_sp
lldb::StructuredDataPluginSP lldb_private::EventDataStructuredData::m_plugin_sp private
Definition at line 171 of file Event.h.
Referenced by EventDataStructuredData(), EventDataStructuredData(), GetStructuredDataPlugin(), and SetStructuredDataPlugin().
m_process_sp
lldb::ProcessSP lldb_private::EventDataStructuredData::m_process_sp private
Definition at line 169 of file Event.h.
Referenced by EventDataStructuredData(), EventDataStructuredData(), GetProcess(), and SetProcess().
The documentation for this class was generated from the following files:
Event.h
Event.cpp