LLDB: lldb_private::ScriptedProcessInterface Class Reference
lldb_private::ScriptedProcessInterface Class Reference abstract
#include <ScriptedProcessInterface.h>
Public Member Functions
virtual llvm::Expected< StructuredData::GenericSP > CreatePluginObject (llvm::StringRef class_name, ExecutionContext &exe_ctx, StructuredData::DictionarySP args_sp, StructuredData::Generic *script_obj=nullptr)=0
virtual StructuredData::DictionarySP GetCapabilities ()
virtual Status Attach (const ProcessAttachInfo &attach_info)
virtual Status Launch ()
virtual Status Resume ()
virtual std::optional< MemoryRegionInfo > GetMemoryRegionContainingAddress (lldb::addr_t address, Status &error)
virtual StructuredData::DictionarySP GetThreadsInfo ()
virtual bool CreateBreakpoint (lldb::addr_t addr, Status &error)
virtual lldb::DataExtractorSP ReadMemoryAtAddress (lldb::addr_t address, size_t size, Status &error)
virtual lldb::offset_t WriteMemoryAtAddress (lldb::addr_t addr, lldb::DataExtractorSP data_sp, Status &error)
virtual StructuredData::ArraySP GetLoadedImages ()
virtual lldb::pid_t GetProcessID ()
virtual bool IsAlive ()
virtual std::optional< std::string > GetScriptedThreadPluginName ()
virtual StructuredData::DictionarySP GetMetadata ()
Public Member Functions inherited from lldb_private::ScriptedInterface
ScriptedInterface ()=default
virtual ~ScriptedInterface ()=default
StructuredData::GenericSP GetScriptObjectInstance ()
virtual llvm::SmallVector< AbstractMethodRequirement > GetAbstractMethodRequirements () const =0
virtual llvm::Expected< FileSpec > GetScriptedModulePath ()
llvm::SmallVector< llvm::StringLiteral > const GetAbstractMethods () const
Protected Member Functions
virtual lldb::ScriptedThreadInterfaceSP CreateScriptedThreadInterface ()
Friends
class ScriptedThread
Additional Inherited Members
Static Public Member Functions inherited from lldb_private::ScriptedInterface
template<typename Ret>
static Ret ErrorWithMessage (llvm::StringRef caller_name, llvm::StringRef error_msg, Status &error, LLDBLog log_category=LLDBLog::Process)
template<typename T = StructuredData::ObjectSP>
static bool CheckStructuredDataObject (llvm::StringRef caller, T obj, Status &error)
static bool CreateInstance (lldb::ScriptLanguage language, ScriptedInterfaceUsages usages)
Protected Attributes inherited from lldb_private::ScriptedInterface
StructuredData::GenericSP m_object_instance_sp
Detailed Description
Definition at line 22 of file ScriptedProcessInterface.h.
Member Function Documentation
Attach()
virtual Status lldb_private::ScriptedProcessInterface::Attach (const ProcessAttachInfo & attach_info) inline virtual
Reimplemented in lldb_private::ScriptedProcessPythonInterface.
Definition at line 31 of file ScriptedProcessInterface.h.
References lldb_private::Status::FromErrorString().
Referenced by lldb_private::ScriptedProcess::DoAttach().
CreateBreakpoint()
virtual bool lldb_private::ScriptedProcessInterface::CreateBreakpoint (lldb::addr_t addr, Status & error) inline virtual
Reimplemented in lldb_private::ScriptedProcessPythonInterface.
Definition at line 51 of file ScriptedProcessInterface.h.
References error(), and lldb_private::Status::FromErrorString().
Referenced by lldb_private::ScriptedProcess::EnableBreakpointSite().
CreatePluginObject()
virtual llvm::Expected< StructuredData::GenericSP > lldb_private::ScriptedProcessInterface::CreatePluginObject (llvm::StringRef class_name, ExecutionContext & exe_ctx, StructuredData::DictionarySP args_sp, StructuredData::Generic * script_obj = nullptr) pure virtual
Implemented in lldb_private::ScriptedProcessPythonInterface.
Referenced by lldb_private::ScriptedProcess::ScriptedProcess().
CreateScriptedThreadInterface()
virtual lldb::ScriptedThreadInterfaceSP lldb_private::ScriptedProcessInterface::CreateScriptedThreadInterface () inline protected virtual
Reimplemented in lldb_private::ScriptedProcessPythonInterface.
Definition at line 82 of file ScriptedProcessInterface.h.
Referenced by lldb_private::ScriptedThread::Create().
GetCapabilities()
virtual StructuredData::DictionarySP lldb_private::ScriptedProcessInterface::GetCapabilities () inline virtual
Reimplemented in lldb_private::ScriptedProcessPythonInterface.
Definition at line 29 of file ScriptedProcessInterface.h.
GetLoadedImages()
virtual StructuredData::ArraySP lldb_private::ScriptedProcessInterface::GetLoadedImages () inline virtual
Reimplemented in lldb_private::ScriptedProcessPythonInterface.
Definition at line 68 of file ScriptedProcessInterface.h.
Referenced by lldb_private::ScriptedProcess::GetLoadedDynamicLibrariesInfos().
GetMemoryRegionContainingAddress()
virtual std::optional< MemoryRegionInfo > lldb_private::ScriptedProcessInterface::GetMemoryRegionContainingAddress (lldb::addr_t address, Status & error) inline virtual
Reimplemented in lldb_private::ScriptedProcessPythonInterface.
Definition at line 44 of file ScriptedProcessInterface.h.
References error(), and lldb_private::Status::FromErrorString().
GetMetadata()
virtual StructuredData::DictionarySP lldb_private::ScriptedProcessInterface::GetMetadata () inline virtual
Reimplemented in lldb_private::ScriptedProcessPythonInterface.
Definition at line 78 of file ScriptedProcessInterface.h.
Referenced by lldb_private::ScriptedProcess::GetMetadata().
GetProcessID()
virtual lldb::pid_t lldb_private::ScriptedProcessInterface::GetProcessID () inline virtual
Reimplemented in lldb_private::ScriptedProcessPythonInterface.
Definition at line 70 of file ScriptedProcessInterface.h.
References LLDB_INVALID_PROCESS_ID.
Referenced by lldb_private::ScriptedProcess::DidLaunch(), and lldb_private::ScriptedProcess::DidResume().
GetScriptedThreadPluginName()
virtual std::optional< std::string > lldb_private::ScriptedProcessInterface::GetScriptedThreadPluginName () inline virtual
Reimplemented in lldb_private::ScriptedProcessPythonInterface.
Definition at line 74 of file ScriptedProcessInterface.h.
Referenced by lldb_private::ScriptedThread::Create().
GetThreadsInfo()
virtual StructuredData::DictionarySP lldb_private::ScriptedProcessInterface::GetThreadsInfo () inline virtual
Reimplemented in lldb_private::ScriptedProcessPythonInterface.
Definition at line 49 of file ScriptedProcessInterface.h.
Referenced by lldb_private::ScriptedProcess::DoUpdateThreadList().
IsAlive()
virtual bool lldb_private::ScriptedProcessInterface::IsAlive () inline virtual
Reimplemented in lldb_private::ScriptedProcessPythonInterface.
Definition at line 72 of file ScriptedProcessInterface.h.
Referenced by lldb_private::ScriptedProcess::IsAlive().
Launch()
virtual Status lldb_private::ScriptedProcessInterface::Launch () inline virtual
Reimplemented in lldb_private::ScriptedProcessPythonInterface.
Definition at line 35 of file ScriptedProcessInterface.h.
References lldb_private::Status::FromErrorString().
Referenced by lldb_private::ScriptedProcess::DoLaunch().
ReadMemoryAtAddress()
virtual lldb::DataExtractorSP lldb_private::ScriptedProcessInterface::ReadMemoryAtAddress (lldb::addr_t address, size_t size, Status & error) inline virtual
Reimplemented in lldb_private::ScriptedProcessPythonInterface.
Definition at line 58 of file ScriptedProcessInterface.h.
References error().
Referenced by lldb_private::ScriptedProcess::DoReadMemory().
Resume()
virtual Status lldb_private::ScriptedProcessInterface::Resume () inline virtual
Reimplemented in lldb_private::ScriptedProcessPythonInterface.
Definition at line 39 of file ScriptedProcessInterface.h.
References lldb_private::Status::FromErrorString().
Referenced by lldb_private::ScriptedProcess::DoResume().
WriteMemoryAtAddress()
virtual lldb::offset_t lldb_private::ScriptedProcessInterface::WriteMemoryAtAddress (lldb::addr_t addr, lldb::DataExtractorSP data_sp, Status & error) inline virtual
Reimplemented in lldb_private::ScriptedProcessPythonInterface.
Definition at line 62 of file ScriptedProcessInterface.h.
References error(), and LLDB_INVALID_OFFSET.
Referenced by lldb_private::ScriptedProcess::DoWriteMemory().
Friends And Related Symbol Documentation
ScriptedThread
friend class ScriptedThread friend
Definition at line 81 of file ScriptedProcessInterface.h.
References ScriptedThread.
Referenced by ScriptedThread.
The documentation for this class was generated from the following file:
ScriptedProcessInterface.h