LLDB: lldb_private::ScriptedStackFrameRecognizer Class Reference
lldb_private::ScriptedStackFrameRecognizer Class Reference
Python implementation for frame recognizers.
#include <StackFrameRecognizer.h>
Public Member Functions
ScriptedStackFrameRecognizer (lldb_private::ScriptInterpreter *interpreter, const char *pclass)
~ScriptedStackFrameRecognizer () override=default
std::string GetName () override
const char * GetPythonClassName ()
lldb::RecognizedStackFrameSP RecognizeFrame (lldb::StackFrameSP frame) override
Public Member Functions inherited from lldb_private::StackFrameRecognizer
virtual ~StackFrameRecognizer ()=default
Private Member Functions
ScriptedStackFrameRecognizer (const ScriptedStackFrameRecognizer &)=delete
const ScriptedStackFrameRecognizer & operator= (const ScriptedStackFrameRecognizer &)=delete
Private Attributes
lldb_private::ScriptInterpreter * m_interpreter
lldb_private::StructuredData::ObjectSP m_python_object_sp
std::string m_python_class
Detailed Description
Python implementation for frame recognizers.
An instance of this class tracks a particular Python classobject, which will be asked to recognize stack frames.
Definition at line 79 of file StackFrameRecognizer.h.
Constructor & Destructor Documentation
ScriptedStackFrameRecognizer() [1/2]
ScriptedStackFrameRecognizer::ScriptedStackFrameRecognizer (lldb_private::ScriptInterpreter * interpreter, const char * pclass)
Definition at line 30 of file StackFrameRecognizer.cpp.
References m_interpreter, m_python_class, and m_python_object_sp.
Referenced by operator=(), and ScriptedStackFrameRecognizer().
~ScriptedStackFrameRecognizer()
lldb_private::ScriptedStackFrameRecognizer::~ScriptedStackFrameRecognizer () override default
ScriptedStackFrameRecognizer() [2/2]
lldb_private::ScriptedStackFrameRecognizer::ScriptedStackFrameRecognizer (const ScriptedStackFrameRecognizer &) private delete
References ScriptedStackFrameRecognizer().
Member Function Documentation
GetName()
std::string lldb_private::ScriptedStackFrameRecognizer::GetName () inline override virtual
Reimplemented from lldb_private::StackFrameRecognizer.
Definition at line 90 of file StackFrameRecognizer.h.
References GetPythonClassName().
GetPythonClassName()
const char * lldb_private::ScriptedStackFrameRecognizer::GetPythonClassName () inline
Definition at line 94 of file StackFrameRecognizer.h.
References m_python_class.
Referenced by GetName().
operator=()
const ScriptedStackFrameRecognizer & lldb_private::ScriptedStackFrameRecognizer::operator= (const ScriptedStackFrameRecognizer &) private delete
References ScriptedStackFrameRecognizer().
RecognizeFrame()
RecognizedStackFrameSP ScriptedStackFrameRecognizer::RecognizeFrame (lldb::StackFrameSP frame) override virtual
Reimplemented from lldb_private::StackFrameRecognizer.
Definition at line 38 of file StackFrameRecognizer.cpp.
References lldb_private::ValueObjectRecognizerSynthesizedValue::Create(), lldb::eValueTypeVariableArgument, m_interpreter, and m_python_object_sp.
Member Data Documentation
m_interpreter
lldb_private::ScriptInterpreter* lldb_private::ScriptedStackFrameRecognizer::m_interpreter private
Definition at line 80 of file StackFrameRecognizer.h.
Referenced by RecognizeFrame(), and ScriptedStackFrameRecognizer().
m_python_class
std::string lldb_private::ScriptedStackFrameRecognizer::m_python_class private
Definition at line 83 of file StackFrameRecognizer.h.
Referenced by GetPythonClassName(), and ScriptedStackFrameRecognizer().
m_python_object_sp
lldb_private::StructuredData::ObjectSP lldb_private::ScriptedStackFrameRecognizer::m_python_object_sp private
Definition at line 81 of file StackFrameRecognizer.h.
Referenced by RecognizeFrame(), and ScriptedStackFrameRecognizer().
The documentation for this class was generated from the following files:
StackFrameRecognizer.h
StackFrameRecognizer.cpp