LLDB: lldb_private::IOHandler Class Reference
lldb_private::IOHandler Class Reference abstract
#include <IOHandler.h>
Public Types
enum class Type {
CommandInterpreter , CommandList , Confirm , Curses ,
Expression , REPL , ProcessIO , PythonInterpreter ,
LuaInterpreter , PythonCode , Other
}
Public Member Functions
IOHandler (Debugger &debugger, IOHandler::Type type)
IOHandler (Debugger &debugger, IOHandler::Type type, const lldb::FileSP &input_sp, const lldb::LockableStreamFileSP &output_sp, const lldb::LockableStreamFileSP &error_sp, uint32_t flags)
virtual ~IOHandler ()
virtual void Run ()=0
virtual void Cancel ()=0
virtual bool Interrupt ()=0
virtual void GotEOF ()=0
bool IsActive ()
void SetIsDone (bool b)
bool GetIsDone ()
Type GetType () const
virtual void Activate ()
virtual void Deactivate ()
virtual void TerminalSizeChanged ()
virtual void Refresh ()
virtual const char * GetPrompt ()
virtual bool SetPrompt (llvm::StringRef prompt)
virtual bool SetUseColor (bool use_color)
bool SetPrompt (const char *)=delete
virtual llvm::StringRef GetControlSequence (char ch)
virtual const char * GetCommandPrefix ()
virtual const char * GetHelpPrologue ()
int GetInputFD ()
int GetOutputFD ()
int GetErrorFD ()
lldb::FileSP GetInputFileSP ()
lldb::LockableStreamFileSP GetOutputStreamFileSP ()
lldb::LockableStreamFileSP GetErrorStreamFileSP ()
Debugger & GetDebugger ()
void * GetUserData ()
void SetUserData (void *user_data)
Flags & GetFlags ()
const Flags & GetFlags () const
bool GetIsInteractive ()
Check if the input is being supplied interactively by a user.
bool GetIsRealTerminal ()
Check if the input is coming from a real terminal.
void SetPopped (bool b)
void WaitForPop ()
virtual void PrintAsync (const char *s, size_t len, bool is_stdout)
Protected Attributes
Debugger & m_debugger
lldb::FileSP m_input_sp
lldb::LockableStreamFileSP m_output_sp
lldb::LockableStreamFileSP m_error_sp
Predicate< bool > m_popped
Flags m_flags
Type m_type
void * m_user_data
bool m_done
bool m_active
Private Member Functions
IOHandler (const IOHandler &)=delete
const IOHandler & operator= (const IOHandler &)=delete
Detailed Description
Definition at line 37 of file IOHandler.h.
Member Enumeration Documentation
Type
enum class lldb_private::IOHandler::Type strong
Enumerator
CommandInterpreter
CommandList
Confirm
Curses
Expression
REPL
ProcessIO
PythonInterpreter
LuaInterpreter
PythonCode
Other
Definition at line 39 of file IOHandler.h.
Constructor & Destructor Documentation
IOHandler() [1/3]
IOHandler::IOHandler (Debugger & debugger, IOHandler::Type type)
Definition at line 55 of file IOHandler.cpp.
References IOHandler().
Referenced by IOHandler(), IOHandler(), lldb_private::IOHandlerEditline::IOHandlerEditline(), IOHandlerProcessSTDIO::IOHandlerProcessSTDIO(), lldb_private::IOHandlerProcessSTDIOWindows::IOHandlerProcessSTDIOWindows(), lldb_private::IOHandlerPythonInterpreter::IOHandlerPythonInterpreter(), and operator=().
IOHandler() [2/3]
IOHandler::IOHandler (Debugger & debugger, IOHandler::Type type, const lldb::FileSP & input_sp, const lldb::LockableStreamFileSP & output_sp, const lldb::LockableStreamFileSP & error_sp, uint32_t flags)
Definition at line 64 of file IOHandler.cpp.
References lldb_private::Debugger::AdoptTopIOHandlerFilesIfInvalid(), m_active, m_debugger, m_done, m_error_sp, m_flags, m_input_sp, m_output_sp, m_popped, m_type, and m_user_data.
~IOHandler()
IOHandler::~IOHandler () virtual default
IOHandler() [3/3]
lldb_private::IOHandler::IOHandler (const IOHandler &) private delete
References IOHandler().
Member Function Documentation
Activate()
virtual void lldb_private::IOHandler::Activate () inline virtual
Reimplemented in lldb_private::IOHandlerCursesGUI, and lldb_private::IOHandlerEditline.
Definition at line 87 of file IOHandler.h.
References m_active.
Referenced by lldb_private::IOHandlerEditline::Activate().
Cancel()
virtual void lldb_private::IOHandler::Cancel () pure virtual
Implemented in IOHandlerProcessSTDIO, lldb_private::IOHandlerCursesGUI, lldb_private::IOHandlerEditline, lldb_private::IOHandlerProcessSTDIOWindows, and lldb_private::IOHandlerPythonInterpreter.
Deactivate()
virtual void lldb_private::IOHandler::Deactivate () inline virtual
Reimplemented in lldb_private::IOHandlerCursesGUI, and lldb_private::IOHandlerEditline.
Definition at line 89 of file IOHandler.h.
References m_active.
Referenced by lldb_private::IOHandlerEditline::Deactivate().
GetCommandPrefix()
virtual const char * lldb_private::IOHandler::GetCommandPrefix () inline virtual
Reimplemented in lldb_private::IOHandlerEditline.
Definition at line 114 of file IOHandler.h.
GetControlSequence()
virtual llvm::StringRef lldb_private::IOHandler::GetControlSequence (char ch) inline virtual
Reimplemented in lldb_private::IOHandlerEditline, and lldb_private::IOHandlerPythonInterpreter.
Definition at line 112 of file IOHandler.h.
GetDebugger()
Debugger & lldb_private::IOHandler::GetDebugger () inline
Definition at line 130 of file IOHandler.h.
References m_debugger.
Referenced by lldb_private::IOHandlerDelegate::IOHandlerComplete(), lldb_private::REPL::IOHandlerFixIndentation(), IOHandlerProcessSTDIO::IOHandlerProcessSTDIO(), lldb_private::IOHandlerProcessSTDIOWindows::IOHandlerProcessSTDIOWindows(), and lldb_private::IOHandlerDelegate::IOHandlerSuggestion().
GetErrorFD()
int IOHandler::GetErrorFD ()
Definition at line 87 of file IOHandler.cpp.
References m_error_sp.
GetErrorStreamFileSP()
LockableStreamFileSP IOHandler::GetErrorStreamFileSP ()
Definition at line 95 of file IOHandler.cpp.
References m_error_sp.
Referenced by lldb_private::REPL::IOHandlerActivated(), CommandObjectCommandsScriptAdd::IOHandlerInputComplete(), CommandObjectTypeSummaryAdd::IOHandlerInputComplete(), CommandObjectTypeSynthAdd::IOHandlerInputComplete(), IOHandlerLuaInterpreter::IOHandlerInputComplete(), lldb_private::REPL::IOHandlerInputComplete(), and lldb_private::CommandInterpreter::PrintCommandOutput().
GetFlags() [1/2]
Flags & lldb_private::IOHandler::GetFlags () inline
Definition at line 136 of file IOHandler.h.
References m_flags.
Referenced by lldb_private::CommandInterpreter::IOHandlerInputComplete().
GetFlags() [2/2]
const Flags & lldb_private::IOHandler::GetFlags () const inline
Definition at line 138 of file IOHandler.h.
References m_flags.
GetHelpPrologue()
virtual const char * lldb_private::IOHandler::GetHelpPrologue () inline virtual
Reimplemented in lldb_private::IOHandlerEditline.
Definition at line 116 of file IOHandler.h.
GetInputFD()
int IOHandler::GetInputFD ()
Definition at line 79 of file IOHandler.cpp.
References m_input_sp.
Referenced by IOHandlerProcessSTDIO::IOHandlerProcessSTDIO(), lldb_private::IOHandlerProcessSTDIOWindows::IOHandlerProcessSTDIOWindows(), and lldb_private::IOHandlerPythonInterpreter::Run().
GetInputFileSP()
FileSP IOHandler::GetInputFileSP ()
Definition at line 91 of file IOHandler.cpp.
References m_input_sp.
Referenced by GetIsInteractive(), and GetIsRealTerminal().
GetIsDone()
bool lldb_private::IOHandler::GetIsDone () inline
Definition at line 83 of file IOHandler.h.
References m_done.
Referenced by IOHandlerProcessSTDIO::Run(), and lldb_private::IOHandlerProcessSTDIOWindows::Run().
GetIsInteractive()
bool IOHandler::GetIsInteractive ()
Check if the input is being supplied interactively by a user.
This will return true if the input stream is a terminal (tty or pty) and can cause IO handlers to do different things (like for a confirmation when deleting all breakpoints).
Definition at line 97 of file IOHandler.cpp.
References GetInputFileSP().
Referenced by lldb_private::IOHandlerEditline::Activate(), lldb_private::IOHandlerEditline::GetLine(), lldb_private::IOHandlerEditline::GetLines(), and lldb_private::CommandInterpreter::IOHandlerInputComplete().
GetIsRealTerminal()
bool IOHandler::GetIsRealTerminal ()
Check if the input is coming from a real terminal.
A real terminal has a valid size with a certain number of rows and columns. If this function returns true, then terminal escape sequences are expected to work (cursor movement escape sequences, clearing lines, etc).
Definition at line 101 of file IOHandler.cpp.
References GetInputFileSP().
GetOutputFD()
int IOHandler::GetOutputFD ()
Definition at line 83 of file IOHandler.cpp.
References m_output_sp.
GetOutputStreamFileSP()
LockableStreamFileSP IOHandler::GetOutputStreamFileSP ()
Definition at line 93 of file IOHandler.cpp.
References m_output_sp.
Referenced by CommandObjectTargetStopHookAdd::DoExecute(), CommandObjectCommandsScriptAdd::IOHandlerActivated(), CommandObjectTypeSummaryAdd::IOHandlerActivated(), CommandObjectTypeSynthAdd::IOHandlerActivated(), IOHandlerLuaInterpreter::IOHandlerActivated(), lldb_private::ScriptInterpreterPythonImpl::IOHandlerActivated(), CommandObjectCommandsAddRegex::IOHandlerInputComplete(), lldb_private::CommandInterpreter::IOHandlerInputComplete(), lldb_private::REPL::IOHandlerInputComplete(), and lldb_private::CommandInterpreter::PrintCommandOutput().
GetPrompt()
virtual const char * lldb_private::IOHandler::GetPrompt () inline virtual
Reimplemented in lldb_private::IOHandlerEditline.
Definition at line 95 of file IOHandler.h.
Referenced by lldb_private::CommandInterpreter::IOHandlerInputComplete().
GetType()
Type lldb_private::IOHandler::GetType () const inline
Definition at line 85 of file IOHandler.h.
References m_type.
GetUserData()
void * lldb_private::IOHandler::GetUserData () inline
Definition at line 132 of file IOHandler.h.
References m_user_data.
Referenced by CommandObjectTypeSummaryAdd::IOHandlerInputComplete(), CommandObjectTypeSynthAdd::IOHandlerInputComplete(), and IOHandlerLuaInterpreter::IOHandlerInputComplete().
GotEOF()
virtual void lldb_private::IOHandler::GotEOF () pure virtual
Implemented in IOHandlerProcessSTDIO, lldb_private::IOHandlerCursesGUI, lldb_private::IOHandlerEditline, lldb_private::IOHandlerProcessSTDIOWindows, and lldb_private::IOHandlerPythonInterpreter.
Interrupt()
virtual bool lldb_private::IOHandler::Interrupt () pure virtual
Implemented in IOHandlerProcessSTDIO, lldb_private::IOHandlerCursesGUI, lldb_private::IOHandlerEditline, lldb_private::IOHandlerProcessSTDIOWindows, and lldb_private::IOHandlerPythonInterpreter.
IsActive()
bool lldb_private::IOHandler::IsActive () inline
Definition at line 79 of file IOHandler.h.
References m_active, and m_done.
Referenced by lldb_private::IOHandlerEditline::Run().
operator=()
const IOHandler & lldb_private::IOHandler::operator= (const IOHandler &) private delete
References IOHandler().
PrintAsync()
void IOHandler::PrintAsync (const char * s, size_t len, bool is_stdout) virtual
Reimplemented in lldb_private::IOHandlerEditline.
Definition at line 109 of file IOHandler.cpp.
References m_error_sp, m_output_sp, and lldb_private::Stream::Write().
Referenced by lldb_private::IOHandlerEditline::PrintAsync().
Refresh()
virtual void lldb_private::IOHandler::Refresh () inline virtual
Reimplemented in lldb_private::IOHandlerEditline.
Definition at line 93 of file IOHandler.h.
Run()
virtual void lldb_private::IOHandler::Run () pure virtual
Implemented in IOHandlerProcessSTDIO, lldb_private::IOHandlerCursesGUI, lldb_private::IOHandlerEditline, lldb_private::IOHandlerProcessSTDIOWindows, and lldb_private::IOHandlerPythonInterpreter.
SetIsDone()
void lldb_private::IOHandler::SetIsDone (bool b) inline
Definition at line 81 of file IOHandler.h.
References m_done.
Referenced by IOHandlerProcessSTDIO::Cancel(), lldb_private::IOHandlerProcessSTDIOWindows::Cancel(), lldb_private::IOHandlerEditline::GetLine(), lldb_private::REPL::IOHandlerActivated(), CommandObjectCommandsScriptAdd::IOHandlerInputComplete(), CommandObjectTypeSummaryAdd::IOHandlerInputComplete(), CommandObjectTypeSynthAdd::IOHandlerInputComplete(), IOHandlerLuaInterpreter::IOHandlerInputComplete(), lldb_private::CommandInterpreter::IOHandlerInputComplete(), lldb_private::IOHandlerConfirm::IOHandlerInputComplete(), lldb_private::REPL::IOHandlerInputComplete(), IOHandlerProcessSTDIO::Run(), lldb_private::IOHandlerProcessSTDIOWindows::Run(), lldb_private::IOHandlerPythonInterpreter::Run(), IOHandlerProcessSTDIO::SetIsRunning(), and lldb_private::IOHandlerProcessSTDIOWindows::SetIsRunning().
SetPopped()
void IOHandler::SetPopped (bool b)
Definition at line 105 of file IOHandler.cpp.
References lldb_private::eBroadcastOnChange, and m_popped.
SetPrompt() [1/2]
bool lldb_private::IOHandler::SetPrompt (const char *) delete
SetPrompt() [2/2]
virtual bool lldb_private::IOHandler::SetPrompt (llvm::StringRef prompt) inline virtual
Reimplemented in lldb_private::IOHandlerEditline.
Definition at line 100 of file IOHandler.h.
SetUseColor()
virtual bool lldb_private::IOHandler::SetUseColor (bool use_color) inline virtual
Reimplemented in lldb_private::IOHandlerEditline.
Definition at line 105 of file IOHandler.h.
SetUserData()
void lldb_private::IOHandler::SetUserData (void * user_data) inline
Definition at line 134 of file IOHandler.h.
References m_user_data.
TerminalSizeChanged()
virtual void lldb_private::IOHandler::TerminalSizeChanged () inline virtual
Reimplemented in lldb_private::IOHandlerCursesGUI, and lldb_private::IOHandlerEditline.
Definition at line 91 of file IOHandler.h.
WaitForPop()
void IOHandler::WaitForPop ()
Definition at line 107 of file IOHandler.cpp.
References m_popped.
Member Data Documentation
m_active
bool lldb_private::IOHandler::m_active protected
Definition at line 171 of file IOHandler.h.
Referenced by Activate(), Deactivate(), IOHandlerProcessSTDIO::Interrupt(), lldb_private::IOHandlerProcessSTDIOWindows::Interrupt(), IOHandler(), and IsActive().
m_debugger
Debugger& lldb_private::IOHandler::m_debugger protected
Definition at line 162 of file IOHandler.h.
Referenced by GetDebugger(), IOHandler(), lldb_private::IOHandlerEditline::SetPrompt(), and lldb_private::IOHandlerEditline::SetUseColor().
m_done
bool lldb_private::IOHandler::m_done protected
Definition at line 170 of file IOHandler.h.
Referenced by GetIsDone(), IOHandler(), IsActive(), lldb_private::IOHandlerEditline::Run(), and SetIsDone().
m_error_sp
lldb::LockableStreamFileSP lldb_private::IOHandler::m_error_sp protected
Definition at line 165 of file IOHandler.h.
Referenced by GetErrorFD(), GetErrorStreamFileSP(), IOHandler(), lldb_private::IOHandlerEditline::IOHandlerEditline(), PrintAsync(), and lldb_private::IOHandlerEditline::PrintAsync().
m_flags
Flags lldb_private::IOHandler::m_flags protected
Definition at line 167 of file IOHandler.h.
Referenced by GetFlags(), GetFlags(), and IOHandler().
m_input_sp
lldb::FileSP lldb_private::IOHandler::m_input_sp protected
Definition at line 163 of file IOHandler.h.
Referenced by GetInputFD(), GetInputFileSP(), lldb_private::IOHandlerEditline::GetLine(), IOHandler(), and lldb_private::IOHandlerEditline::IOHandlerEditline().
m_output_sp
lldb::LockableStreamFileSP lldb_private::IOHandler::m_output_sp protected
Definition at line 164 of file IOHandler.h.
Referenced by lldb_private::IOHandlerEditline::GetLine(), lldb_private::IOHandlerEditline::GetLines(), GetOutputFD(), GetOutputStreamFileSP(), IOHandler(), lldb_private::IOHandlerEditline::IOHandlerEditline(), PrintAsync(), and lldb_private::IOHandlerEditline::PrintAsync().
m_popped
Predicate<bool> lldb_private::IOHandler::m_popped protected
Definition at line 166 of file IOHandler.h.
Referenced by IOHandler(), SetPopped(), and WaitForPop().
m_type
Type lldb_private::IOHandler::m_type protected
Definition at line 168 of file IOHandler.h.
Referenced by GetType(), and IOHandler().
m_user_data
void* lldb_private::IOHandler::m_user_data protected
Definition at line 169 of file IOHandler.h.
Referenced by GetUserData(), IOHandler(), and SetUserData().
The documentation for this class was generated from the following files:
IOHandler.h
IOHandler.cpp