LLDB: lldb_private::ModuleList::Notifier Class Reference
lldb_private::ModuleList::Notifier Class Reference abstract
#include <ModuleList.h>
Public Member Functions
virtual ~Notifier ()=default
virtual void NotifyModuleAdded (const ModuleList &module_list, const lldb::ModuleSP &module_sp)=0
virtual void NotifyModuleRemoved (const ModuleList &module_list, const lldb::ModuleSP &module_sp)=0
virtual void NotifyModuleUpdated (const ModuleList &module_list, const lldb::ModuleSP &old_module_sp, const lldb::ModuleSP &new_module_sp)=0
virtual void NotifyWillClearList (const ModuleList &module_list)=0
virtual void NotifyModulesRemoved (lldb_private::ModuleList &module_list)=0
Detailed Description
Definition at line 127 of file ModuleList.h.
Constructor & Destructor Documentation
~Notifier()
virtual lldb_private::ModuleList::Notifier::~Notifier () virtual default
Member Function Documentation
NotifyModuleAdded()
virtual void lldb_private::ModuleList::Notifier::NotifyModuleAdded (const ModuleList & module_list, const lldb::ModuleSP & module_sp) pure virtual
Implemented in lldb_private::Target.
References lldb_private::ModuleList::ModuleList().
NotifyModuleRemoved()
virtual void lldb_private::ModuleList::Notifier::NotifyModuleRemoved (const ModuleList & module_list, const lldb::ModuleSP & module_sp) pure virtual
Implemented in lldb_private::Target.
References lldb_private::ModuleList::ModuleList().
NotifyModulesRemoved()
virtual void lldb_private::ModuleList::Notifier::NotifyModulesRemoved (lldb_private::ModuleList & module_list) pure virtual
Implemented in lldb_private::Target.
NotifyModuleUpdated()
virtual void lldb_private::ModuleList::Notifier::NotifyModuleUpdated (const ModuleList & module_list, const lldb::ModuleSP & old_module_sp, const lldb::ModuleSP & new_module_sp) pure virtual
Implemented in lldb_private::Target.
References lldb_private::ModuleList::ModuleList().
NotifyWillClearList()
virtual void lldb_private::ModuleList::Notifier::NotifyWillClearList (const ModuleList & module_list) pure virtual
Implemented in lldb_private::Target.
References lldb_private::ModuleList::ModuleList().
The documentation for this class was generated from the following file:
ModuleList.h