LLDB: lldb_private::ClassDescriptorV2::iVarsStorage Class Reference
lldb_private::ClassDescriptorV2::iVarsStorage Class Reference
Public Member Functions
iVarsStorage ()
size_t size ()
iVarDescriptor & operator[] (size_t idx)
void fill (AppleObjCRuntimeV2 &runtime, ClassDescriptorV2 &descriptor)
Private Attributes
bool m_filled = false
std::vector< iVarDescriptor > m_ivars
std::recursive_mutex m_mutex
Detailed Description
Definition at line 233 of file AppleObjCClassDescriptorV2.h.
Constructor & Destructor Documentation
iVarsStorage()
ClassDescriptorV2::iVarsStorage::iVarsStorage ()
Definition at line 735 of file AppleObjCClassDescriptorV2.cpp.
References m_ivars, and m_mutex.
Member Function Documentation
fill()
void ClassDescriptorV2::iVarsStorage::fill (AppleObjCRuntimeV2 & runtime, ClassDescriptorV2 & descriptor)
Definition at line 744 of file AppleObjCClassDescriptorV2.cpp.
References lldb_private::ClassDescriptorV2::ClassDescriptorV2(), lldb_private::ClassDescriptorV2::Describe(), error(), lldb_private::CompilerType::GetByteSize(), lldb_private::ClassDescriptorV2::GetClassName(), lldb_private::AppleObjCRuntimeV2::GetEncodingToType(), lldb_private::GetLog(), lldb_private::Runtime::GetProcess(), LLDB_LOGV, lldb_private::ClassDescriptorV2::lldb_private::AppleObjCRuntimeV2, m_filled, m_ivars, m_mutex, lldb_private::Process::ReadScalarIntegerFromMemory(), lldb_private::Scalar::SInt(), size(), and lldb_private::Types.
operator[]()
ClassDescriptorV2::iVarDescriptor & ClassDescriptorV2::iVarsStorage::operator[] (size_t idx)
Definition at line 739 of file AppleObjCClassDescriptorV2.cpp.
References m_ivars.
size()
size_t ClassDescriptorV2::iVarsStorage::size ()
Definition at line 737 of file AppleObjCClassDescriptorV2.cpp.
References m_ivars.
Referenced by fill().
Member Data Documentation
m_filled
bool lldb_private::ClassDescriptorV2::iVarsStorage::m_filled = false private
Definition at line 244 of file AppleObjCClassDescriptorV2.h.
Referenced by fill().
m_ivars
std::vector<iVarDescriptor> lldb_private::ClassDescriptorV2::iVarsStorage::m_ivars private
Definition at line 245 of file AppleObjCClassDescriptorV2.h.
Referenced by fill(), iVarsStorage(), operator[](), and size().
m_mutex
std::recursive_mutex lldb_private::ClassDescriptorV2::iVarsStorage::m_mutex private
Definition at line 246 of file AppleObjCClassDescriptorV2.h.
Referenced by fill(), and iVarsStorage().
The documentation for this class was generated from the following files:
AppleObjCClassDescriptorV2.h
AppleObjCClassDescriptorV2.cpp