LLDB: lldb_private::OptionGroupPlatformCaching Class Reference
lldb_private::OptionGroupPlatformCaching Class Reference
#include <Platform.h>
Public Member Functions
OptionGroupPlatformCaching ()=default
~OptionGroupPlatformCaching () override=default
lldb_private::Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext *execution_context) override
void OptionParsingStarting (ExecutionContext *execution_context) override
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Public Attributes
std::string m_cache_dir
Private Member Functions
OptionGroupPlatformCaching (const OptionGroupPlatformCaching &)=delete
const OptionGroupPlatformCaching & operator= (const OptionGroupPlatformCaching &)=delete
Detailed Description
Definition at line 1241 of file Platform.h.
Constructor & Destructor Documentation
OptionGroupPlatformCaching() [1/2]
lldb_private::OptionGroupPlatformCaching::OptionGroupPlatformCaching () default
Referenced by operator=(), and OptionGroupPlatformCaching().
~OptionGroupPlatformCaching()
lldb_private::OptionGroupPlatformCaching::~OptionGroupPlatformCaching () override default
OptionGroupPlatformCaching() [2/2]
lldb_private::OptionGroupPlatformCaching::OptionGroupPlatformCaching (const OptionGroupPlatformCaching &) private delete
References OptionGroupPlatformCaching().
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > OptionGroupPlatformCaching::GetDefinitions () override virtual
Implements lldb_private::OptionGroup.
Definition at line 1402 of file Platform.cpp.
References g_caching_option_table.
Referenced by SetOptionValue().
operator=()
const OptionGroupPlatformCaching & lldb_private::OptionGroupPlatformCaching::operator= (const OptionGroupPlatformCaching &) private delete
References OptionGroupPlatformCaching().
OptionParsingStarting()
void OptionGroupPlatformCaching::OptionParsingStarting (ExecutionContext * execution_context) override virtual
Implements lldb_private::OptionGroup.
Definition at line 1406 of file Platform.cpp.
References m_cache_dir.
SetOptionValue()
lldb_private::Status OptionGroupPlatformCaching::SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext * execution_context) override virtual
Implements lldb_private::OptionGroup.
Definition at line 1411 of file Platform.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormat(), GetDefinitions(), and m_cache_dir.
Member Data Documentation
m_cache_dir
std::string lldb_private::OptionGroupPlatformCaching::m_cache_dir
Definition at line 1257 of file Platform.h.
Referenced by OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following files:
Platform.h
Platform.cpp