LLDB: lldb::SBCommandInterpreterRunOptions Class Reference
lldb::SBCommandInterpreterRunOptions Class Reference
#include <SBCommandInterpreterRunOptions.h>
Public Member Functions
SBCommandInterpreterRunOptions ()
SBCommandInterpreterRunOptions (const SBCommandInterpreterRunOptions &rhs)
~SBCommandInterpreterRunOptions ()
SBCommandInterpreterRunOptions & operator= (const SBCommandInterpreterRunOptions &rhs)
bool GetStopOnContinue () const
void SetStopOnContinue (bool)
bool GetStopOnError () const
void SetStopOnError (bool)
bool GetStopOnCrash () const
void SetStopOnCrash (bool)
bool GetEchoCommands () const
void SetEchoCommands (bool)
bool GetEchoCommentCommands () const
void SetEchoCommentCommands (bool echo)
bool GetPrintResults () const
void SetPrintResults (bool)
bool GetPrintErrors () const
void SetPrintErrors (bool)
bool GetAddToHistory () const
void SetAddToHistory (bool)
bool GetAutoHandleEvents () const
void SetAutoHandleEvents (bool)
bool GetSpawnThread () const
void SetSpawnThread (bool)
bool GetAllowRepeats () const
void SetAllowRepeats (bool)
By default, RunCommandInterpreter will discard repeats if the IOHandler being used is not interactive.
Private Member Functions
lldb_private::CommandInterpreterRunOptions * get () const
lldb_private::CommandInterpreterRunOptions & ref () const
Private Attributes
std::unique_ptr< lldb_private::CommandInterpreterRunOptions > m_opaque_up
Friends
class SBDebugger
class SBCommandInterpreter
Detailed Description
Definition at line 23 of file SBCommandInterpreterRunOptions.h.
Constructor & Destructor Documentation
SBCommandInterpreterRunOptions() [1/2]
SBCommandInterpreterRunOptions::SBCommandInterpreterRunOptions ()
Definition at line 21 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by operator=(), SBCommandInterpreter, SBCommandInterpreterRunOptions(), and ~SBCommandInterpreterRunOptions().
SBCommandInterpreterRunOptions() [2/2]
SBCommandInterpreterRunOptions::SBCommandInterpreterRunOptions (const SBCommandInterpreterRunOptions & rhs)
Definition at line 27 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, ref(), and SBCommandInterpreterRunOptions().
~SBCommandInterpreterRunOptions()
SBCommandInterpreterRunOptions::~SBCommandInterpreterRunOptions () default
References get(), GetAddToHistory(), GetAllowRepeats(), GetAutoHandleEvents(), GetEchoCommands(), GetEchoCommentCommands(), GetPrintErrors(), GetPrintResults(), GetSpawnThread(), GetStopOnContinue(), GetStopOnCrash(), GetStopOnError(), operator=(), ref(), SBCommandInterpreterRunOptions(), SetAddToHistory(), SetAllowRepeats(), SetAutoHandleEvents(), SetEchoCommands(), SetEchoCommentCommands(), SetPrintErrors(), SetPrintResults(), SetSpawnThread(), SetStopOnContinue(), SetStopOnCrash(), and SetStopOnError().
Member Function Documentation
get()
lldb_private::CommandInterpreterRunOptions * SBCommandInterpreterRunOptions::get () const private
Definition at line 180 of file SBCommandInterpreterRunOptions.cpp.
References m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
GetAddToHistory()
bool SBCommandInterpreterRunOptions::GetAddToHistory () const
Definition at line 130 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
GetAllowRepeats()
bool SBCommandInterpreterRunOptions::GetAllowRepeats () const
Definition at line 167 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
GetAutoHandleEvents()
bool SBCommandInterpreterRunOptions::GetAutoHandleEvents () const
Definition at line 142 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
GetEchoCommands()
bool SBCommandInterpreterRunOptions::GetEchoCommands () const
Definition at line 82 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
GetEchoCommentCommands()
bool SBCommandInterpreterRunOptions::GetEchoCommentCommands () const
Definition at line 94 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
GetPrintErrors()
bool SBCommandInterpreterRunOptions::GetPrintErrors () const
Definition at line 118 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
GetPrintResults()
bool SBCommandInterpreterRunOptions::GetPrintResults () const
Definition at line 106 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
GetSpawnThread()
bool SBCommandInterpreterRunOptions::GetSpawnThread () const
Definition at line 155 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
GetStopOnContinue()
bool SBCommandInterpreterRunOptions::GetStopOnContinue () const
Definition at line 46 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
GetStopOnCrash()
bool SBCommandInterpreterRunOptions::GetStopOnCrash () const
Definition at line 70 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
GetStopOnError()
bool SBCommandInterpreterRunOptions::GetStopOnError () const
Definition at line 58 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
operator=()
SBCommandInterpreterRunOptions & SBCommandInterpreterRunOptions::operator= (const SBCommandInterpreterRunOptions & rhs)
Definition at line 36 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and SBCommandInterpreterRunOptions().
Referenced by ~SBCommandInterpreterRunOptions().
ref()
lldb_private::CommandInterpreterRunOptions & SBCommandInterpreterRunOptions::ref () const private
Definition at line 185 of file SBCommandInterpreterRunOptions.cpp.
References m_opaque_up.
Referenced by lldb::SBCommandInterpreter::HandleCommandsFromFile(), lldb::SBDebugger::RunCommandInterpreter(), lldb::SBDebugger::RunCommandInterpreter(), SBCommandInterpreterRunOptions(), and ~SBCommandInterpreterRunOptions().
SetAddToHistory()
void SBCommandInterpreterRunOptions::SetAddToHistory (bool add_to_history)
Definition at line 136 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
SetAllowRepeats()
void SBCommandInterpreterRunOptions::SetAllowRepeats (bool allow_repeats)
By default, RunCommandInterpreter will discard repeats if the IOHandler being used is not interactive.
Setting AllowRepeats to true will override this behavior and always process empty lines in the input as a repeat command.
Definition at line 173 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
SetAutoHandleEvents()
void SBCommandInterpreterRunOptions::SetAutoHandleEvents (bool auto_handle_events)
Definition at line 148 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBDebugger::RunCommandInterpreter(), and ~SBCommandInterpreterRunOptions().
SetEchoCommands()
void SBCommandInterpreterRunOptions::SetEchoCommands (bool echo_commands)
Definition at line 88 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
SetEchoCommentCommands()
void SBCommandInterpreterRunOptions::SetEchoCommentCommands (bool echo)
Definition at line 100 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
SetPrintErrors()
void SBCommandInterpreterRunOptions::SetPrintErrors (bool print_errors)
Definition at line 124 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
SetPrintResults()
void SBCommandInterpreterRunOptions::SetPrintResults (bool print_results)
Definition at line 112 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
SetSpawnThread()
void SBCommandInterpreterRunOptions::SetSpawnThread (bool spawn_thread)
Definition at line 161 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBDebugger::RunCommandInterpreter(), and ~SBCommandInterpreterRunOptions().
SetStopOnContinue()
void SBCommandInterpreterRunOptions::SetStopOnContinue (bool stop_on_continue)
Definition at line 52 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
SetStopOnCrash()
void SBCommandInterpreterRunOptions::SetStopOnCrash (bool stop_on_crash)
Definition at line 76 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
SetStopOnError()
void SBCommandInterpreterRunOptions::SetStopOnError (bool stop_on_error)
Definition at line 64 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunOptions().
Friends And Related Symbol Documentation
SBCommandInterpreter
friend class SBCommandInterpreter friend
Definition at line 25 of file SBCommandInterpreterRunOptions.h.
References SBCommandInterpreter, and SBCommandInterpreterRunOptions().
Referenced by SBCommandInterpreter.
SBDebugger
friend class SBDebugger friend
Definition at line 24 of file SBCommandInterpreterRunOptions.h.
References SBDebugger.
Referenced by SBDebugger.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::CommandInterpreterRunOptions> lldb::SBCommandInterpreterRunOptions::m_opaque_up mutable private
Definition at line 90 of file SBCommandInterpreterRunOptions.h.
Referenced by get(), GetAddToHistory(), GetAllowRepeats(), GetAutoHandleEvents(), GetEchoCommands(), GetEchoCommentCommands(), GetPrintErrors(), GetPrintResults(), GetSpawnThread(), GetStopOnContinue(), GetStopOnCrash(), GetStopOnError(), operator=(), ref(), SBCommandInterpreterRunOptions(), SBCommandInterpreterRunOptions(), SetAddToHistory(), SetAllowRepeats(), SetAutoHandleEvents(), SetEchoCommands(), SetEchoCommentCommands(), SetPrintErrors(), SetPrintResults(), SetSpawnThread(), SetStopOnContinue(), SetStopOnCrash(), and SetStopOnError().
The documentation for this class was generated from the following files:
SBCommandInterpreterRunOptions.h
SBCommandInterpreterRunOptions.cpp