LLDB: lldb_private::NativeProcessSoftwareSingleStep Class Reference
lldb_private::NativeProcessSoftwareSingleStep Class Reference
#include <NativeProcessSoftwareSingleStep.h>
Public Member Functions
Status SetupSoftwareSingleStepping (NativeThreadProtocol &thread)
Protected Attributes
std::map< lldb::tid_t, std::vector< lldb::addr_t > > m_threads_stepping_with_breakpoint
Detailed Description
Definition at line 19 of file NativeProcessSoftwareSingleStep.h.
Member Function Documentation
SetupSoftwareSingleStepping()
Status NativeProcessSoftwareSingleStep::SetupSoftwareSingleStepping (NativeThreadProtocol & thread)
Definition at line 105 of file NativeProcessSoftwareSingleStep.cpp.
References lldb_private::EmulateInstruction::CreateBreakpointLocationPredictor(), lldb_private::eInstructionTypePCModifying, error(), lldb_private::EmulateInstruction::FindPlugin(), lldb_private::Status::FromErrorString(), lldb_private::NativeProcessProtocol::GetArchitecture(), m_threads_stepping_with_breakpoint, ReadMemoryCallback(), ReadRegisterCallback(), SetSoftwareBreakpoint(), lldb_private::Status, lldb_private::toString(), WriteMemoryCallback(), and WriteRegisterCallback().
Referenced by lldb_private::process_linux::NativeProcessLinux::Resume().
Member Data Documentation
m_threads_stepping_with_breakpoint
std::map<lldb::tid_t, std::vector<lldb::addr_t> > lldb_private::NativeProcessSoftwareSingleStep::m_threads_stepping_with_breakpoint protected
Definition at line 27 of file NativeProcessSoftwareSingleStep.h.
Referenced by lldb_private::process_linux::NativeProcessLinux::MonitorBreakpoint(), lldb_private::process_freebsd::NativeProcessFreeBSD::MonitorSIGTRAP(), SetupSoftwareSingleStepping(), and lldb_private::process_linux::NativeProcessLinux::SignalIfAllThreadsStopped().
The documentation for this class was generated from the following files:
NativeProcessSoftwareSingleStep.h
NativeProcessSoftwareSingleStep.cpp