LLDB: lldb::SBTypeMember Class Reference
lldb::SBTypeMember Class Reference
#include <SBType.h>
Public Member Functions
SBTypeMember ()
SBTypeMember (const lldb::SBTypeMember &rhs)
~SBTypeMember ()
lldb::SBTypeMember & operator= (const lldb::SBTypeMember &rhs)
operator bool () const
bool IsValid () const
const char * GetName ()
lldb::SBType GetType ()
uint64_t GetOffsetInBytes ()
uint64_t GetOffsetInBits ()
bool IsBitfield ()
uint32_t GetBitfieldSizeInBits ()
bool GetDescription (lldb::SBStream &description, lldb::DescriptionLevel description_level)
Protected Member Functions
void reset (lldb_private::TypeMemberImpl *)
lldb_private::TypeMemberImpl & ref ()
const lldb_private::TypeMemberImpl & ref () const
Protected Attributes
std::unique_ptr< lldb_private::TypeMemberImpl > m_opaque_up
Friends
class SBType
Detailed Description
Definition at line 24 of file SBType.h.
Constructor & Destructor Documentation
SBTypeMember() [1/2]
SBTypeMember::SBTypeMember ()
Definition at line 791 of file SBType.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by SBTypeMember().
SBTypeMember() [2/2]
SBTypeMember::SBTypeMember (const lldb::SBTypeMember & rhs)
Definition at line 795 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_up, ref(), and SBTypeMember().
~SBTypeMember()
SBTypeMember::~SBTypeMember () default
References GetBitfieldSizeInBits(), GetDescription(), GetOffsetInBits(), GetOffsetInBytes(), GetType(), IsBitfield(), IsValid(), and operator=().
Member Function Documentation
GetBitfieldSizeInBits()
uint32_t SBTypeMember::GetBitfieldSizeInBits ()
Definition at line 866 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBTypeMember().
GetDescription()
bool SBTypeMember::GetDescription (lldb::SBStream & description, lldb::DescriptionLevel description_level)
Definition at line 874 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
Referenced by ~SBTypeMember().
GetName()
const char * SBTypeMember::GetName ()
Definition at line 824 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
GetOffsetInBits()
uint64_t SBTypeMember::GetOffsetInBits ()
Definition at line 850 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBTypeMember().
GetOffsetInBytes()
uint64_t SBTypeMember::GetOffsetInBytes ()
Definition at line 842 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBTypeMember().
GetType()
SBType SBTypeMember::GetType ()
Definition at line 832 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, SBType, and lldb::SBType::SetSP().
Referenced by ~SBTypeMember().
IsBitfield()
bool SBTypeMember::IsBitfield ()
Definition at line 858 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBTypeMember().
IsValid()
bool SBTypeMember::IsValid () const
Definition at line 814 of file SBType.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by operator=(), SBTypeMember(), and ~SBTypeMember().
operator bool()
SBTypeMember::operator bool () const explicit
Definition at line 818 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
operator=()
lldb::SBTypeMember & SBTypeMember::operator= (const lldb::SBTypeMember & rhs)
Definition at line 804 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_up, and ref().
Referenced by ~SBTypeMember().
ref() [1/2]
TypeMemberImpl & SBTypeMember::ref () protected
Definition at line 909 of file SBType.cpp.
References m_opaque_up.
Referenced by operator=(), SBType, and SBTypeMember().
ref() [2/2]
const TypeMemberImpl & SBTypeMember::ref () const protected
Definition at line 915 of file SBType.cpp.
References m_opaque_up.
reset()
void SBTypeMember::reset (lldb_private::TypeMemberImpl * type_member_impl) protected
Definition at line 905 of file SBType.cpp.
References m_opaque_up.
Referenced by lldb::SBType::GetDirectBaseClassAtIndex(), lldb::SBType::GetFieldAtIndex(), lldb::SBType::GetVirtualBaseClassAtIndex(), and SBType.
Friends And Related Symbol Documentation
SBType
friend class SBType friend
Definition at line 54 of file SBType.h.
References ref(), reset(), and SBType.
Referenced by GetType(), and SBType.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::TypeMemberImpl> lldb::SBTypeMember::m_opaque_up protected
Definition at line 62 of file SBType.h.
Referenced by GetBitfieldSizeInBits(), GetDescription(), GetName(), GetOffsetInBits(), GetOffsetInBytes(), GetType(), IsBitfield(), operator bool(), operator=(), ref(), ref(), reset(), and SBTypeMember().
The documentation for this class was generated from the following files:
SBType.h
SBType.cpp