LLDB: lldb_private::dil::MemberOfNode Class Reference
lldb_private::dil::MemberOfNode Class Reference
#include <DILAST.h>
Public Member Functions
MemberOfNode (uint32_t location, ASTNodeUP base, bool is_arrow, std::string name)
llvm::Expected< lldb::ValueObjectSP > Accept (Visitor *v) const override
ASTNode & GetBase () const
bool GetIsArrow () const
llvm::StringRef GetFieldName () const
Public Member Functions inherited from lldb_private::dil::ASTNode
ASTNode (uint32_t location, NodeKind kind)
virtual ~ASTNode ()=default
uint32_t GetLocation () const
NodeKind GetKind () const
Static Public Member Functions
static bool classof (const ASTNode &node)
Private Attributes
ASTNodeUP m_base
bool m_is_arrow
std::string m_field_name
Detailed Description
Definition at line 108 of file DILAST.h.
Constructor & Destructor Documentation
MemberOfNode()
lldb_private::dil::MemberOfNode::MemberOfNode (uint32_t location, ASTNodeUP base, bool is_arrow, std::string name) inline
Definition at line 110 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), lldb_private::dil::eMemberOfNode, m_base, m_field_name, and m_is_arrow.
Member Function Documentation
Accept()
llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::MemberOfNode::Accept (Visitor * v) const override virtual
Implements lldb_private::dil::ASTNode.
Definition at line 22 of file DILAST.cpp.
References lldb_private::dil::Visitor::Visit().
classof()
bool lldb_private::dil::MemberOfNode::classof (const ASTNode & node) inline static
Definition at line 121 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), lldb_private::dil::eMemberOfNode, and lldb_private::dil::ASTNode::GetKind().
GetBase()
ASTNode & lldb_private::dil::MemberOfNode::GetBase () const inline
Definition at line 117 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), and m_base.
Referenced by lldb_private::dil::Interpreter::Visit().
GetFieldName()
llvm::StringRef lldb_private::dil::MemberOfNode::GetFieldName () const inline
Definition at line 119 of file DILAST.h.
References m_field_name.
Referenced by lldb_private::dil::Interpreter::Visit().
GetIsArrow()
bool lldb_private::dil::MemberOfNode::GetIsArrow () const inline
Definition at line 118 of file DILAST.h.
References m_is_arrow.
Referenced by lldb_private::dil::Interpreter::Visit().
Member Data Documentation
m_base
ASTNodeUP lldb_private::dil::MemberOfNode::m_base private
Definition at line 126 of file DILAST.h.
Referenced by GetBase(), and MemberOfNode().
m_field_name
std::string lldb_private::dil::MemberOfNode::m_field_name private
Definition at line 128 of file DILAST.h.
Referenced by GetFieldName(), and MemberOfNode().
m_is_arrow
bool lldb_private::dil::MemberOfNode::m_is_arrow private
Definition at line 127 of file DILAST.h.
Referenced by GetIsArrow(), and MemberOfNode().
The documentation for this class was generated from the following files:
DILAST.h
DILAST.cpp