LLDB: lldb_private::TraceDumper::FunctionCall::UntracedPrefixSegment Class Reference
lldb_private::TraceDumper::FunctionCall::UntracedPrefixSegment Class Reference
#include <TraceDumper.h>
Public Member Functions
UntracedPrefixSegment (FunctionCallUP &&nested_call)
Note: Untraced segments can only exist if have also seen a traced segment of the same function call.
const FunctionCall & GetNestedCall () const
Private Member Functions
UntracedPrefixSegment (const UntracedPrefixSegment &)=delete
UntracedPrefixSegment & operator= (UntracedPrefixSegment const &)
Private Attributes
FunctionCallUP m_nested_call
Detailed Description
Definition at line 293 of file TraceDumper.h.
Constructor & Destructor Documentation
UntracedPrefixSegment() [1/2]
lldb_private::TraceDumper::FunctionCall::UntracedPrefixSegment::UntracedPrefixSegment (FunctionCallUP && nested_call) inline
Note: Untraced segments can only exist if have also seen a traced segment of the same function call.
Thus, we can use those traced segments if we want symbol information and such.
Definition at line 299 of file TraceDumper.h.
References m_nested_call.
Referenced by operator=(), and UntracedPrefixSegment().
UntracedPrefixSegment() [2/2]
lldb_private::TraceDumper::FunctionCall::UntracedPrefixSegment::UntracedPrefixSegment (const UntracedPrefixSegment &) private delete
References UntracedPrefixSegment().
Member Function Documentation
GetNestedCall()
const TraceDumper::FunctionCall & TraceDumper::FunctionCall::UntracedPrefixSegment::GetNestedCall () const
Definition at line 639 of file TraceDumper.cpp.
References m_nested_call.
operator=()
UntracedPrefixSegment & lldb_private::TraceDumper::FunctionCall::UntracedPrefixSegment::operator= (UntracedPrefixSegment const &) private
References UntracedPrefixSegment().
Member Data Documentation
m_nested_call
FunctionCallUP lldb_private::TraceDumper::FunctionCall::UntracedPrefixSegment::m_nested_call private
Definition at line 307 of file TraceDumper.h.
Referenced by GetNestedCall(), and UntracedPrefixSegment().
The documentation for this class was generated from the following files:
TraceDumper.h
TraceDumper.cpp