LLDB: lldb_private::CXXSyntheticChildren Class Reference
lldb_private::CXXSyntheticChildren Class Reference
#include <TypeSynthetic.h>
Public Types
typedef std::function< SyntheticChildrenFrontEnd *(CXXSyntheticChildren *, lldb::ValueObjectSP)> CreateFrontEndCallback
Public Types inherited from lldb_private::SyntheticChildren
typedef std::shared_ptr< SyntheticChildren > SharedPointer
Public Member Functions
CXXSyntheticChildren (const SyntheticChildren::Flags &flags, const char *description, CreateFrontEndCallback callback)
virtual ~CXXSyntheticChildren ()
bool IsScripted () override
std::string GetDescription () override
SyntheticChildrenFrontEnd::UniquePointer GetFrontEnd (ValueObject &backend) override
Public Member Functions inherited from lldb_private::SyntheticChildren
SyntheticChildren (const Flags &flags)
virtual ~SyntheticChildren ()
bool Cascades () const
bool SkipsPointers () const
bool SkipsReferences () const
bool NonCacheable () const
bool WantsDereference () const
void SetCascades (bool value)
void SetSkipsPointers (bool value)
void SetSkipsReferences (bool value)
void SetNonCacheable (bool value)
uint32_t GetOptions ()
void SetOptions (uint32_t value)
uint32_t & GetRevision ()
uint32_t GetPtrMatchDepth ()
void SetPtrMatchDepth (uint32_t value)
Protected Attributes
CreateFrontEndCallback m_create_callback
std::string m_description
Protected Attributes inherited from lldb_private::SyntheticChildren
uint32_t m_my_revision = 0
Flags m_flags
uint32_t m_ptr_match_depth = 1
Private Member Functions
CXXSyntheticChildren (const CXXSyntheticChildren &)=delete
const CXXSyntheticChildren & operator= (const CXXSyntheticChildren &)=delete
Detailed Description
Definition at line 371 of file TypeSynthetic.h.
Member Typedef Documentation
CreateFrontEndCallback
typedef std::function<SyntheticChildrenFrontEnd *(CXXSyntheticChildren *, lldb::ValueObjectSP)> lldb_private::CXXSyntheticChildren::CreateFrontEndCallback
Definition at line 375 of file TypeSynthetic.h.
Constructor & Destructor Documentation
CXXSyntheticChildren() [1/2]
CXXSyntheticChildren::CXXSyntheticChildren (const SyntheticChildren::Flags & flags, const char * description, CreateFrontEndCallback callback)
Definition at line 95 of file TypeSynthetic.cpp.
References m_create_callback, m_description, and lldb_private::SyntheticChildren::SyntheticChildren().
Referenced by CXXSyntheticChildren(), and operator=().
~CXXSyntheticChildren()
CXXSyntheticChildren::~CXXSyntheticChildren () virtual default
CXXSyntheticChildren() [2/2]
lldb_private::CXXSyntheticChildren::CXXSyntheticChildren (const CXXSyntheticChildren &) private delete
References CXXSyntheticChildren().
Member Function Documentation
GetDescription()
std::string CXXSyntheticChildren::GetDescription () override virtual
Implements lldb_private::SyntheticChildren.
Definition at line 112 of file TypeSynthetic.cpp.
References lldb_private::SyntheticChildren::Cascades(), lldb_private::StreamString::GetString(), m_description, lldb_private::Stream::Printf(), lldb_private::SyntheticChildren::SkipsPointers(), and lldb_private::SyntheticChildren::SkipsReferences().
GetFrontEnd()
SyntheticChildrenFrontEnd::UniquePointer lldb_private::CXXSyntheticChildren::GetFrontEnd (ValueObject & backend) inline override virtual
Implements lldb_private::SyntheticChildren.
Definition at line 386 of file TypeSynthetic.h.
References lldb_private::ValueObject::GetSP(), and m_create_callback.
IsScripted()
bool lldb_private::CXXSyntheticChildren::IsScripted () inline override virtual
Implements lldb_private::SyntheticChildren.
Definition at line 381 of file TypeSynthetic.h.
operator=()
const CXXSyntheticChildren & lldb_private::CXXSyntheticChildren::operator= (const CXXSyntheticChildren &) private delete
References CXXSyntheticChildren().
Member Data Documentation
m_create_callback
CreateFrontEndCallback lldb_private::CXXSyntheticChildren::m_create_callback protected
Definition at line 392 of file TypeSynthetic.h.
Referenced by CXXSyntheticChildren(), and GetFrontEnd().
m_description
std::string lldb_private::CXXSyntheticChildren::m_description protected
Definition at line 393 of file TypeSynthetic.h.
Referenced by CXXSyntheticChildren(), and GetDescription().
The documentation for this class was generated from the following files:
TypeSynthetic.h
TypeSynthetic.cpp