LLDB: RegisterContextKDP_arm Class Reference
RegisterContextKDP_arm Class Reference
#include <RegisterContextKDP_arm.h>
Public Member Functions
RegisterContextKDP_arm (ThreadKDP &thread, uint32_t concrete_frame_idx)
~RegisterContextKDP_arm () override
Public Member Functions inherited from RegisterContextDarwin_arm
RegisterContextDarwin_arm (lldb_private::Thread &thread, uint32_t concrete_frame_idx)
~RegisterContextDarwin_arm () override
void InvalidateAllRegisters () override
size_t GetRegisterCount () override
const lldb_private::RegisterInfo * GetRegisterInfoAtIndex (size_t reg) override
size_t GetRegisterSetCount () override
const lldb_private::RegisterSet * GetRegisterSet (size_t set) override
bool ReadRegister (const lldb_private::RegisterInfo *reg_info, lldb_private::RegisterValue &reg_value) override
bool WriteRegister (const lldb_private::RegisterInfo *reg_info, const lldb_private::RegisterValue &reg_value) override
bool ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp) override
bool WriteAllRegisterValues (const lldb::DataBufferSP &data_sp) override
uint32_t ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num) override
Convert from a given register numbering scheme to the lldb register numbering scheme.
uint32_t NumSupportedHardwareBreakpoints () override
uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size) override
bool ClearHardwareBreakpoint (uint32_t hw_idx) override
uint32_t NumSupportedHardwareWatchpoints () override
uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, bool read, bool write) override
bool ClearHardwareWatchpoint (uint32_t hw_index) override
Public Member Functions inherited from lldb_private::RegisterContext
RegisterContext (Thread &thread, uint32_t concrete_frame_idx)
~RegisterContext () override
void InvalidateIfNeeded (bool force)
virtual lldb::ByteOrder GetByteOrder ()
virtual bool RegisterWriteCausesReconfigure (const llvm::StringRef name)
virtual bool ReconfigureRegisterInfo ()
virtual bool ReadAllRegisterValues (lldb_private::RegisterCheckpoint &reg_checkpoint)
virtual bool WriteAllRegisterValues (const lldb_private::RegisterCheckpoint &reg_checkpoint)
bool CopyFromRegisterContext (lldb::RegisterContextSP context)
virtual bool HardwareSingleStep (bool enable)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, uint32_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, uint32_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual Thread & GetThread ()
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num)
uint64_t GetPC (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetThreadPointer (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool GetPCForSymbolication (Address &address)
Get an address suitable for symbolication.
bool SetPC (uint64_t pc)
bool SetPC (Address addr)
uint64_t GetSP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetSP (uint64_t sp)
uint64_t GetFP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetFP (uint64_t fp)
const char * GetRegisterName (uint32_t reg)
uint64_t GetReturnAddress (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetFlags (uint64_t fail_value=0)
uint64_t ReadRegisterAsUnsigned (uint32_t reg, uint64_t fail_value)
uint64_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, uint64_t fail_value)
bool WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
bool WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
bool ConvertBetweenRegisterKinds (lldb::RegisterKind source_rk, uint32_t source_regnum, lldb::RegisterKind target_rk, uint32_t &target_regnum)
lldb::TargetSP CalculateTarget () override
lldb::ProcessSP CalculateProcess () override
lldb::ThreadSP CalculateThread () override
lldb::StackFrameSP CalculateStackFrame () override
void CalculateExecutionContext (ExecutionContext &exe_ctx) override
Reconstruct the object's execution context into sc.
uint32_t GetStopID () const
void SetStopID (uint32_t stop_id)
Public Member Functions inherited from lldb_private::ExecutionContextScope
virtual ~ExecutionContextScope ()=default
Protected Member Functions
int DoReadGPR (lldb::tid_t tid, int flavor, GPR &gpr) override
int DoReadFPU (lldb::tid_t tid, int flavor, FPU &fpu) override
int DoReadEXC (lldb::tid_t tid, int flavor, EXC &exc) override
int DoReadDBG (lldb::tid_t tid, int flavor, DBG &dbg) override
int DoWriteGPR (lldb::tid_t tid, int flavor, const GPR &gpr) override
int DoWriteFPU (lldb::tid_t tid, int flavor, const FPU &fpu) override
int DoWriteEXC (lldb::tid_t tid, int flavor, const EXC &exc) override
int DoWriteDBG (lldb::tid_t tid, int flavor, const DBG &dbg) override
Protected Member Functions inherited from RegisterContextDarwin_arm
void InvalidateAllRegisterStates ()
int GetError (int flavor, uint32_t err_idx) const
bool SetError (int flavor, uint32_t err_idx, int err)
bool RegisterSetIsCached (int set) const
int ReadGPR (bool force)
int ReadFPU (bool force)
int ReadEXC (bool force)
int ReadDBG (bool force)
int WriteGPR ()
int WriteFPU ()
int WriteEXC ()
int WriteDBG ()
int ReadRegisterSet (uint32_t set, bool force)
int WriteRegisterSet (uint32_t set)
Protected Member Functions inherited from lldb_private::RegisterContext
virtual bool BehavesLikeZerothFrame () const
Indicates that this frame is currently executing code, that the PC value is not a return-pc but an actual executing instruction.
Protected Attributes
ThreadKDP & m_kdp_thread
Protected Attributes inherited from RegisterContextDarwin_arm
GPR gpr
FPU fpu
EXC exc
DBG dbg
int gpr_errs [2]
int fpu_errs [2]
int exc_errs [2]
int dbg_errs [2]
Protected Attributes inherited from lldb_private::RegisterContext
Thread & m_thread
uint32_t m_concrete_frame_idx
uint32_t m_stop_id
Additional Inherited Members
Static Public Member Functions inherited from RegisterContextDarwin_arm
static void LogDBGRegisters (lldb_private::Log *log, const DBG &dbg)
Protected Types inherited from RegisterContextDarwin_arm
enum {
GPRRegSet = 1 , GPRAltRegSet = 9 , FPURegSet = 2 , EXCRegSet = 3 ,
DBGRegSet = 4
}
enum { GPRWordCount = sizeof(GPR) / sizeof(uint32_t) , FPUWordCount = sizeof(FPU) / sizeof(uint32_t) , EXCWordCount = sizeof(EXC) / sizeof(uint32_t) , DBGWordCount = sizeof(DBG) / sizeof(uint32_t) }
enum { Read = 0 , Write = 1 , kNumErrors = 2 }
Static Protected Member Functions inherited from RegisterContextDarwin_arm
static uint32_t GetRegisterNumber (uint32_t reg_kind, uint32_t reg_num)
static int GetSetForNativeRegNum (int reg_num)
static size_t GetRegisterInfosCount ()
static const lldb_private::RegisterInfo * GetRegisterInfos ()
Detailed Description
Definition at line 16 of file RegisterContextKDP_arm.h.
Constructor & Destructor Documentation
RegisterContextKDP_arm()
RegisterContextKDP_arm::RegisterContextKDP_arm (ThreadKDP & thread, uint32_t concrete_frame_idx)
Definition at line 17 of file RegisterContextKDP_arm.cpp.
References m_kdp_thread, and RegisterContextDarwin_arm::RegisterContextDarwin_arm().
~RegisterContextKDP_arm()
RegisterContextKDP_arm::~RegisterContextKDP_arm () override default
References RegisterContextDarwin_arm::dbg, RegisterContextDarwin_arm::exc, RegisterContextDarwin_arm::fpu, and RegisterContextDarwin_arm::gpr.
Member Function Documentation
DoReadDBG()
int RegisterContextKDP_arm::DoReadDBG (lldb::tid_t tid, int flavor, DBG & dbg) override protected virtual
Implements RegisterContextDarwin_arm.
Definition at line 69 of file RegisterContextKDP_arm.cpp.
References lldb_private::RegisterContext::CalculateProcess(), RegisterContextDarwin_arm::dbg, RegisterContextDarwin_arm::DBGRegSet, error(), ProcessKDP::GetCommunication(), and CommunicationKDP::SendRequestReadRegisters().
DoReadEXC()
int RegisterContextKDP_arm::DoReadEXC (lldb::tid_t tid, int flavor, EXC & exc) override protected virtual
Implements RegisterContextDarwin_arm.
Definition at line 54 of file RegisterContextKDP_arm.cpp.
References lldb_private::RegisterContext::CalculateProcess(), error(), RegisterContextDarwin_arm::exc, RegisterContextDarwin_arm::EXCRegSet, ProcessKDP::GetCommunication(), and CommunicationKDP::SendRequestReadRegisters().
DoReadFPU()
int RegisterContextKDP_arm::DoReadFPU (lldb::tid_t tid, int flavor, FPU & fpu) override protected virtual
Implements RegisterContextDarwin_arm.
Definition at line 39 of file RegisterContextKDP_arm.cpp.
References lldb_private::RegisterContext::CalculateProcess(), error(), RegisterContextDarwin_arm::fpu, RegisterContextDarwin_arm::FPURegSet, ProcessKDP::GetCommunication(), and CommunicationKDP::SendRequestReadRegisters().
DoReadGPR()
int RegisterContextKDP_arm::DoReadGPR (lldb::tid_t tid, int flavor, GPR & gpr) override protected virtual
Reimplemented from RegisterContextDarwin_arm.
Definition at line 24 of file RegisterContextKDP_arm.cpp.
References lldb_private::RegisterContext::CalculateProcess(), error(), ProcessKDP::GetCommunication(), RegisterContextDarwin_arm::gpr, RegisterContextDarwin_arm::GPRRegSet, and CommunicationKDP::SendRequestReadRegisters().
DoWriteDBG()
int RegisterContextKDP_arm::DoWriteDBG (lldb::tid_t tid, int flavor, const DBG & dbg) override protected virtual
Implements RegisterContextDarwin_arm.
Definition at line 132 of file RegisterContextKDP_arm.cpp.
References lldb_private::RegisterContext::CalculateProcess(), RegisterContextDarwin_arm::dbg, RegisterContextDarwin_arm::DBGRegSet, error(), ProcessKDP::GetCommunication(), and CommunicationKDP::SendRequestWriteRegisters().
DoWriteEXC()
int RegisterContextKDP_arm::DoWriteEXC (lldb::tid_t tid, int flavor, const EXC & exc) override protected virtual
Implements RegisterContextDarwin_arm.
Definition at line 116 of file RegisterContextKDP_arm.cpp.
References lldb_private::RegisterContext::CalculateProcess(), error(), RegisterContextDarwin_arm::exc, RegisterContextDarwin_arm::EXCRegSet, ProcessKDP::GetCommunication(), and CommunicationKDP::SendRequestWriteRegisters().
DoWriteFPU()
int RegisterContextKDP_arm::DoWriteFPU (lldb::tid_t tid, int flavor, const FPU & fpu) override protected virtual
Implements RegisterContextDarwin_arm.
Definition at line 100 of file RegisterContextKDP_arm.cpp.
References lldb_private::RegisterContext::CalculateProcess(), error(), RegisterContextDarwin_arm::fpu, RegisterContextDarwin_arm::FPURegSet, ProcessKDP::GetCommunication(), and CommunicationKDP::SendRequestWriteRegisters().
DoWriteGPR()
int RegisterContextKDP_arm::DoWriteGPR (lldb::tid_t tid, int flavor, const GPR & gpr) override protected virtual
Implements RegisterContextDarwin_arm.
Definition at line 84 of file RegisterContextKDP_arm.cpp.
References lldb_private::RegisterContext::CalculateProcess(), error(), ProcessKDP::GetCommunication(), RegisterContextDarwin_arm::gpr, RegisterContextDarwin_arm::GPRRegSet, and CommunicationKDP::SendRequestWriteRegisters().
Member Data Documentation
m_kdp_thread
ThreadKDP& RegisterContextKDP_arm::m_kdp_thread protected
Definition at line 39 of file RegisterContextKDP_arm.h.
Referenced by RegisterContextKDP_arm().
The documentation for this class was generated from the following files:
RegisterContextKDP_arm.h
RegisterContextKDP_arm.cpp