LLDB: lldb_private::PlatformProperties Class Reference
lldb_private::PlatformProperties Class Reference
#include <Platform.h>
Public Member Functions
PlatformProperties ()
bool GetUseModuleCache () const
bool SetUseModuleCache (bool use_module_cache)
FileSpec GetModuleCacheDirectory () const
bool SetModuleCacheDirectory (const FileSpec &dir_spec)
Public Member Functions inherited from lldb_private::Properties
Properties ()
Properties (const lldb::OptionValuePropertiesSP &collection_sp)
virtual ~Properties ()
lldb::OptionValuePropertiesSP GetValueProperties () const
virtual lldb::OptionValueSP GetPropertyValue (const ExecutionContext *exe_ctx, llvm::StringRef property_path, Status &error) const
virtual Status SetPropertyValue (const ExecutionContext *exe_ctx, VarSetOperationType op, llvm::StringRef property_path, llvm::StringRef value)
virtual Status DumpPropertyValue (const ExecutionContext *exe_ctx, Stream &strm, llvm::StringRef property_path, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllPropertyValues (const ExecutionContext *exe_ctx, Stream &strm, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllDescriptions (CommandInterpreter &interpreter, Stream &strm) const
size_t Apropos (llvm::StringRef keyword, std::vector< const Property * > &matching_properties) const
template<typename T>
T GetPropertyAtIndexAs (uint32_t idx, T default_value, const ExecutionContext *exe_ctx=nullptr) const
template<typename T, typename U = typename std::remove_pointer<T>::type, std::enable_if_t< std::is_pointer_v< T >, bool > = true>
const U * GetPropertyAtIndexAs (uint32_t idx, const ExecutionContext *exe_ctx=nullptr) const
template<typename T>
bool SetPropertyAtIndex (uint32_t idx, T t, const ExecutionContext *exe_ctx=nullptr) const
Static Public Member Functions
static llvm::StringRef GetSettingName ()
Static Public Member Functions inherited from lldb_private::Properties
static llvm::StringRef GetExperimentalSettingsName ()
static bool IsSettingExperimental (llvm::StringRef setting)
Private Member Functions
void SetDefaultModuleCacheDirectory (const FileSpec &dir_spec)
Additional Inherited Members
Protected Attributes inherited from lldb_private::Properties
lldb::OptionValuePropertiesSP m_collection_sp
Detailed Description
Definition at line 48 of file Platform.h.
Constructor & Destructor Documentation
PlatformProperties()
PlatformProperties::PlatformProperties ()
Definition at line 80 of file Platform.cpp.
Member Function Documentation
GetModuleCacheDirectory()
FileSpec PlatformProperties::GetModuleCacheDirectory () const
Definition at line 109 of file Platform.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Platform::GetModuleCacheRoot(), and lldb_private::RemoteAwarePlatform::Platform().
GetSettingName()
llvm::StringRef PlatformProperties::GetSettingName () static
Definition at line 75 of file Platform.cpp.
Referenced by lldb_private::RemoteAwarePlatform::Platform().
GetUseModuleCache()
bool PlatformProperties::GetUseModuleCache () const
Definition at line 99 of file Platform.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
SetDefaultModuleCacheDirectory()
void PlatformProperties::SetDefaultModuleCacheDirectory (const FileSpec & dir_spec) private
Definition at line 118 of file Platform.cpp.
References lldb_private::Properties::m_collection_sp.
Referenced by lldb_private::RemoteAwarePlatform::Platform().
SetModuleCacheDirectory()
bool PlatformProperties::SetModuleCacheDirectory (const FileSpec & dir_spec)
Definition at line 113 of file Platform.cpp.
References lldb_private::Properties::m_collection_sp.
Referenced by lldb_private::RemoteAwarePlatform::Platform().
SetUseModuleCache()
bool PlatformProperties::SetUseModuleCache (bool use_module_cache)
Definition at line 105 of file Platform.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
The documentation for this class was generated from the following files:
Platform.h
Platform.cpp