LLDB: lldb_private::plugin::dwarf::DWARFAttributes Class Reference
lldb_private::plugin::dwarf::DWARFAttributes Class Reference
#include <DWARFAttribute.h>
Classes
struct AttributeValue
Public Member Functions
DWARFAttributes ()
~DWARFAttributes ()
void Append (const DWARFFormValue &form_value, dw_offset_t attr_die_offset, dw_attr_t attr)
DWARFUnit * CompileUnitAtIndex (uint32_t i) const
dw_offset_t DIEOffsetAtIndex (uint32_t i) const
dw_attr_t AttributeAtIndex (uint32_t i) const
dw_form_t FormAtIndex (uint32_t i) const
DWARFFormValue::ValueType ValueAtIndex (uint32_t i) const
bool ExtractFormValueAtIndex (uint32_t i, DWARFFormValue &form_value) const
DWARFDIE FormValueAsReferenceAtIndex (uint32_t i) const
DWARFDIE FormValueAsReference (dw_attr_t attr) const
uint32_t FindAttributeIndex (dw_attr_t attr) const
void Clear ()
size_t Size () const
Protected Types
typedef llvm::SmallVector< AttributeValue, 8 > collection
Protected Attributes
collection m_infos
Detailed Description
Definition at line 43 of file DWARFAttribute.h.
Member Typedef Documentation
collection
typedef llvm::SmallVector<AttributeValue, 8> lldb_private::plugin::dwarf::DWARFAttributes::collection protected
Definition at line 75 of file DWARFAttribute.h.
Constructor & Destructor Documentation
DWARFAttributes()
DWARFAttributes::DWARFAttributes ()
Definition at line 16 of file DWARFAttribute.cpp.
References m_infos.
~DWARFAttributes()
DWARFAttributes::~DWARFAttributes () default
Member Function Documentation
Append()
void DWARFAttributes::Append (const DWARFFormValue & form_value, dw_offset_t attr_die_offset, dw_attr_t attr)
Definition at line 31 of file DWARFAttribute.cpp.
References lldb_private::plugin::dwarf::DWARFFormValue::Form(), lldb_private::plugin::dwarf::DWARFFormValue::GetUnit(), m_infos, and lldb_private::plugin::dwarf::DWARFFormValue::Value().
Referenced by GetAttributes().
AttributeAtIndex()
dw_attr_t lldb_private::plugin::dwarf::DWARFAttributes::AttributeAtIndex (uint32_t i) const inline
Definition at line 54 of file DWARFAttribute.h.
References m_infos.
Referenced by lldb_private::plugin::dwarf::DWARFUnit::AddUnitDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::CollectCallEdges(), CollectCallSiteParameters(), lldb_private::plugin::dwarf::DWARFASTParser::GetTypeForDIE(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexUnitImpl(), DWARFASTParserClang::MemberAttributes::MemberAttributes(), lldb_private::plugin::dwarf::DWARFASTParser::ParseChildArrayInfo(), DWARFASTParserClang::ParseChildEnumerators(), ParsedDWARFTypeAttributes::ParsedDWARFTypeAttributes(), DWARFASTParserClang::ParseInheritance(), DWARFASTParserClang::ParseTemplateDIE(), and lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE().
Clear()
void lldb_private::plugin::dwarf::DWARFAttributes::Clear () inline
Definition at line 65 of file DWARFAttribute.h.
References m_infos.
Referenced by lldb_private::plugin::dwarf::DWARFDebugInfoEntry::GetAttributes().
CompileUnitAtIndex()
DWARFUnit * lldb_private::plugin::dwarf::DWARFAttributes::CompileUnitAtIndex (uint32_t i) const inline
Definition at line 50 of file DWARFAttribute.h.
References m_infos.
Referenced by ExtractFormValueAtIndex(), DWARFASTParserClang::ParseChildEnumerators(), ParsedDWARFTypeAttributes::ParsedDWARFTypeAttributes(), and lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE().
DIEOffsetAtIndex()
dw_offset_t lldb_private::plugin::dwarf::DWARFAttributes::DIEOffsetAtIndex (uint32_t i) const inline
Definition at line 51 of file DWARFAttribute.h.
References m_infos.
Referenced by ExtractFormValueAtIndex().
ExtractFormValueAtIndex()
bool DWARFAttributes::ExtractFormValueAtIndex (uint32_t i, DWARFFormValue & form_value) const
Definition at line 39 of file DWARFAttribute.cpp.
References CompileUnitAtIndex(), DIEOffsetAtIndex(), lldb_private::plugin::dwarf::DWARFFormValue::ExtractValue(), lldb_private::plugin::dwarf::DWARFFormValue::Form(), FormAtIndex(), lldb_private::plugin::dwarf::DWARFUnit::GetData(), lldb_private::plugin::dwarf::DWARFFormValue::SetForm(), lldb_private::plugin::dwarf::DWARFFormValue::SetUnit(), lldb_private::plugin::dwarf::DWARFFormValue::SetValue(), and ValueAtIndex().
Referenced by lldb_private::plugin::dwarf::DWARFUnit::AddUnitDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::CollectCallEdges(), CollectCallSiteParameters(), FormValueAsReferenceAtIndex(), lldb_private::plugin::dwarf::DWARFASTParser::GetTypeForDIE(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexUnitImpl(), DWARFASTParserClang::MemberAttributes::MemberAttributes(), lldb_private::plugin::dwarf::DWARFASTParser::ParseChildArrayInfo(), DWARFASTParserClang::ParseChildEnumerators(), ParsedDWARFTypeAttributes::ParsedDWARFTypeAttributes(), DWARFASTParserClang::ParseInheritance(), DWARFASTParserClang::ParseTemplateDIE(), and lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE().
FindAttributeIndex()
uint32_t DWARFAttributes::FindAttributeIndex (dw_attr_t attr) const
Definition at line 20 of file DWARFAttribute.cpp.
References m_infos, and UINT32_MAX.
Referenced by FormValueAsReference().
FormAtIndex()
dw_form_t lldb_private::plugin::dwarf::DWARFAttributes::FormAtIndex (uint32_t i) const inline
Definition at line 57 of file DWARFAttribute.h.
References m_infos.
Referenced by ExtractFormValueAtIndex().
FormValueAsReference()
DWARFDIE DWARFAttributes::FormValueAsReference (dw_attr_t attr) const
Definition at line 53 of file DWARFAttribute.cpp.
References FindAttributeIndex(), FormValueAsReferenceAtIndex(), and UINT32_MAX.
FormValueAsReferenceAtIndex()
DWARFDIE DWARFAttributes::FormValueAsReferenceAtIndex (uint32_t i) const
Definition at line 61 of file DWARFAttribute.cpp.
References ExtractFormValueAtIndex(), and lldb_private::plugin::dwarf::DWARFFormValue::Reference().
Referenced by FormValueAsReference().
Size()
size_t lldb_private::plugin::dwarf::DWARFAttributes::Size () const inline
Definition at line 66 of file DWARFAttribute.h.
References m_infos.
Referenced by lldb_private::plugin::dwarf::DWARFUnit::AddUnitDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::CollectCallEdges(), CollectCallSiteParameters(), lldb_private::plugin::dwarf::DWARFASTParser::GetTypeForDIE(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexUnitImpl(), DWARFASTParserClang::MemberAttributes::MemberAttributes(), lldb_private::plugin::dwarf::DWARFASTParser::ParseChildArrayInfo(), DWARFASTParserClang::ParseChildEnumerators(), ParsedDWARFTypeAttributes::ParsedDWARFTypeAttributes(), DWARFASTParserClang::ParseInheritance(), DWARFASTParserClang::ParseTemplateDIE(), and lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE().
ValueAtIndex()
DWARFFormValue::ValueType lldb_private::plugin::dwarf::DWARFAttributes::ValueAtIndex (uint32_t i) const inline
Definition at line 58 of file DWARFAttribute.h.
References m_infos.
Referenced by ExtractFormValueAtIndex().
Member Data Documentation
m_infos
collection lldb_private::plugin::dwarf::DWARFAttributes::m_infos protected
Definition at line 76 of file DWARFAttribute.h.
Referenced by Append(), AttributeAtIndex(), Clear(), CompileUnitAtIndex(), DIEOffsetAtIndex(), DWARFAttributes(), FindAttributeIndex(), FormAtIndex(), Size(), and ValueAtIndex().
The documentation for this class was generated from the following files:
DWARFAttribute.h
DWARFAttribute.cpp