LLDB: lldb_private::BreakpointResolverScripted Class Reference
lldb_private::BreakpointResolverScripted Class Reference
"lldb/Breakpoint/BreakpointResolverScripted.h" This class sets breakpoints on a given Address.
#include <BreakpointResolverScripted.h>
Public Member Functions
BreakpointResolverScripted (const lldb::BreakpointSP &bkpt, const llvm::StringRef class_name, lldb::SearchDepth depth, const StructuredDataImpl &args_data)
~BreakpointResolverScripted () override=default
StructuredData::ObjectSP SerializeToStructuredData () override
Searcher::CallbackReturn SearchCallback (SearchFilter &filter, SymbolContext &context, Address *addr) override
lldb::SearchDepth GetDepth () override
void GetDescription (Stream *s) override
Prints a canonical description for the breakpoint to the stream s.
lldb::BreakpointLocationSP WasHit (lldb::StackFrameSP frame_sp, lldb::BreakpointLocationSP bp_loc_sp)
std::optional< std::string > GetLocationDescription (lldb::BreakpointLocationSP bp_loc_sp, lldb::DescriptionLevel level)
void Dump (Stream *s) const override
Standard "Dump" method. At present it does nothing.
lldb::BreakpointResolverSP CopyForBreakpoint (lldb::BreakpointSP &breakpoint) override
Public Member Functions inherited from lldb_private::BreakpointResolver
BreakpointResolver (const lldb::BreakpointSP &bkpt, unsigned char resolverType, lldb::addr_t offset=0, bool offset_is_insn_count=false)
The breakpoint resolver need to have a breakpoint for "ResolveBreakpoint to make sense.
~BreakpointResolver () override
The Destructor is virtual, all significant breakpoint resolvers derive from this class.
void SetBreakpoint (const lldb::BreakpointSP &bkpt)
This sets the breakpoint for this resolver.
lldb::BreakpointSP GetBreakpoint () const
This gets the breakpoint for this resolver.
void SetOffset (lldb::addr_t offset)
This updates the offset for this breakpoint.
lldb::addr_t GetOffset () const
lldb::addr_t GetOffsetIsInsnCount () const
virtual void ResolveBreakpoint (SearchFilter &filter)
In response to this method the resolver scans all the modules in the breakpoint's target, and adds any new locations it finds.
virtual void ResolveBreakpointInModules (SearchFilter &filter, ModuleList &modules)
In response to this method the resolver scans the modules in the module list modules, and adds any new locations it finds.
StructuredData::DictionarySP WrapOptionsDict (StructuredData::DictionarySP options_dict_sp)
unsigned getResolverID () const
getResolverID - Return an ID for the concrete type of this object.
enum ResolverTy GetResolverTy ()
const char * GetResolverName ()
Public Member Functions inherited from lldb_private::Searcher
Searcher ()
virtual ~Searcher ()
Static Public Member Functions
static lldb::BreakpointResolverSP CreateFromStructuredData (const StructuredData::Dictionary &options_dict, Status &error)
static bool classof (const BreakpointResolverScripted *)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const BreakpointResolver *V)
Static Public Member Functions inherited from lldb_private::BreakpointResolver
static lldb::BreakpointResolverSP CreateFromStructuredData (const StructuredData::Dictionary &resolver_dict, Status &error)
This section handles serializing and deserializing from StructuredData objects.
static const char * GetSerializationKey ()
static const char * GetSerializationSubclassKey ()
static const char * GetSerializationSubclassOptionsKey ()
static const char * ResolverTyToName (enum ResolverTy)
static ResolverTy NameToResolverTy (llvm::StringRef name)
static const char * GetKey (OptionNames enum_value)
Protected Member Functions
void NotifyBreakpointSet () override
Protected Member Functions inherited from lldb_private::BreakpointResolver
void SetSCMatchesByLine (SearchFilter &filter, SymbolContextList &sc_list, bool skip_prologue, llvm::StringRef log_ident, uint32_t line=0, std::optional< uint16_t > column=std::nullopt)
Takes a symbol context list of matches which supposedly represent the same file and line number in a CU, and find the nearest actual line number that matches, and then filter down the matching addresses to unique entries, and skip the prologue if asked to do so, and then set breakpoint locations in this breakpoint for all the resultant addresses.
void SetSCMatchesByLine (SearchFilter &, SymbolContextList &, bool, const char *)=delete
lldb::BreakpointLocationSP AddLocation (Address loc_addr, bool *new_location=nullptr)
Private Member Functions
void CreateImplementationIfNeeded (lldb::BreakpointSP bkpt)
ScriptInterpreter * GetScriptInterpreter ()
BreakpointResolverScripted (const BreakpointResolverScripted &)=delete
const BreakpointResolverScripted & operator= (const BreakpointResolverScripted &)=delete
Private Attributes
std::string m_class_name
lldb::SearchDepth m_depth
StructuredDataImpl m_args
Status m_error
lldb::ScriptedBreakpointInterfaceSP m_interface_sp
Additional Inherited Members
Public Types inherited from lldb_private::BreakpointResolver
enum ResolverTy {
FileLineResolver = 0 , AddressResolver , NameResolver , FileRegexResolver ,
PythonResolver , ExceptionResolver , LastKnownResolverType = ExceptionResolver , UnknownResolver
}
An enumeration for keeping track of the concrete subclass that is actually instantiated.
Public Types inherited from lldb_private::Searcher
enum CallbackReturn { eCallbackReturnStop = 0 , eCallbackReturnContinue , eCallbackReturnPop }
Static Public Attributes inherited from lldb_private::BreakpointResolver
static const char * g_ty_to_name [LastKnownResolverType+2]
Protected Types inherited from lldb_private::BreakpointResolver
enum class OptionNames : uint32_t {
AddressOffset = 0 , ExactMatch , FileName , Inlines ,
LanguageName , LineNumber , Column , ModuleName ,
NameMaskArray , Offset , PythonClassName , RegexString ,
ScriptArgs , SectionName , SearchDepth , SkipPrologue ,
SymbolNameArray , LastOptionName
}
Static Protected Attributes inherited from lldb_private::BreakpointResolver
static const char * g_option_names [static_cast< uint32_t >(OptionNames::LastOptionName)]
Detailed Description
"lldb/Breakpoint/BreakpointResolverScripted.h" This class sets breakpoints on a given Address.
This breakpoint only takes once, and then it won't attempt to reset itself.
Definition at line 25 of file BreakpointResolverScripted.h.
Constructor & Destructor Documentation
BreakpointResolverScripted() [1/2]
BreakpointResolverScripted::BreakpointResolverScripted (const lldb::BreakpointSP & bkpt, const llvm::StringRef class_name, lldb::SearchDepth depth, const StructuredDataImpl & args_data)
Definition at line 28 of file BreakpointResolverScripted.cpp.
References lldb_private::BreakpointResolver::BreakpointResolver(), CreateImplementationIfNeeded(), m_args, m_class_name, m_depth, and lldb_private::BreakpointResolver::PythonResolver.
Referenced by BreakpointResolverScripted(), classof(), and operator=().
~BreakpointResolverScripted()
lldb_private::BreakpointResolverScripted::~BreakpointResolverScripted () override default
References error().
BreakpointResolverScripted() [2/2]
lldb_private::BreakpointResolverScripted::BreakpointResolverScripted (const BreakpointResolverScripted &) private delete
References BreakpointResolverScripted().
Member Function Documentation
classof() [1/2]
bool lldb_private::BreakpointResolverScripted::classof (const BreakpointResolver * V) inline static
Definition at line 59 of file BreakpointResolverScripted.h.
References lldb_private::BreakpointResolver::BreakpointResolver(), lldb_private::BreakpointResolver::getResolverID(), and lldb_private::BreakpointResolver::PythonResolver.
classof() [2/2]
bool lldb_private::BreakpointResolverScripted::classof (const BreakpointResolverScripted *) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 58 of file BreakpointResolverScripted.h.
References BreakpointResolverScripted().
CopyForBreakpoint()
lldb::BreakpointResolverSP BreakpointResolverScripted::CopyForBreakpoint (lldb::BreakpointSP & breakpoint) override virtual
Implements lldb_private::BreakpointResolver.
Definition at line 182 of file BreakpointResolverScripted.cpp.
References m_args, m_class_name, and m_depth.
CreateFromStructuredData()
BreakpointResolverSP BreakpointResolverScripted::CreateFromStructuredData (const StructuredData::Dictionary & options_dict, Status & error) static
Definition at line 83 of file BreakpointResolverScripted.cpp.
References error(), lldb::eSearchDepthTarget, lldb_private::Status::FromErrorString(), lldb_private::BreakpointResolver::GetKey(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsDictionary(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsString(), lldb_private::BreakpointResolver::PythonClassName, lldb_private::BreakpointResolver::ScriptArgs, and lldb_private::StructuredDataImpl::SetObjectSP().
Referenced by lldb_private::BreakpointResolver::CreateFromStructuredData().
CreateImplementationIfNeeded()
void BreakpointResolverScripted::CreateImplementationIfNeeded (lldb::BreakpointSP bkpt) private
Definition at line 36 of file BreakpointResolverScripted.cpp.
References lldb_private::ScriptInterpreter::CreateScriptedBreakpointInterface(), lldb_private::Status::FromError(), lldb_private::Status::FromErrorStringWithFormat(), m_args, m_class_name, m_error, and m_interface_sp.
Referenced by BreakpointResolverScripted(), GetDescription(), GetLocationDescription(), and NotifyBreakpointSet().
Dump()
void BreakpointResolverScripted::Dump (Stream * s) const override virtual
Standard "Dump" method. At present it does nothing.
Implements lldb_private::BreakpointResolver.
Definition at line 179 of file BreakpointResolverScripted.cpp.
GetDepth()
lldb::SearchDepth BreakpointResolverScripted::GetDepth () override virtual
Implements lldb_private::Searcher.
Definition at line 140 of file BreakpointResolverScripted.cpp.
References lldb::eSearchDepthModule, and m_interface_sp.
GetDescription()
void BreakpointResolverScripted::GetDescription (Stream * s) override virtual
Prints a canonical description for the breakpoint to the stream s.
Parameters
[in] s Stream to which the output is copied.
Implements lldb_private::BreakpointResolver.
Definition at line 148 of file BreakpointResolverScripted.cpp.
References CreateImplementationIfNeeded(), lldb_private::BreakpointResolver::GetBreakpoint(), m_class_name, m_interface_sp, lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
GetLocationDescription()
std::optional< std::string > BreakpointResolverScripted::GetLocationDescription (lldb::BreakpointLocationSP bp_loc_sp, lldb::DescriptionLevel level)
Definition at line 163 of file BreakpointResolverScripted.cpp.
References CreateImplementationIfNeeded(), lldb_private::BreakpointResolver::GetBreakpoint(), and m_interface_sp.
Referenced by lldb_private::BreakpointLocation::GetDescription().
GetScriptInterpreter()
ScriptInterpreter * BreakpointResolverScripted::GetScriptInterpreter () private
Definition at line 122 of file BreakpointResolverScripted.cpp.
References lldb_private::BreakpointResolver::GetBreakpoint().
NotifyBreakpointSet()
void BreakpointResolverScripted::NotifyBreakpointSet () override protected virtual
Reimplemented from lldb_private::BreakpointResolver.
Definition at line 79 of file BreakpointResolverScripted.cpp.
References CreateImplementationIfNeeded(), and lldb_private::BreakpointResolver::GetBreakpoint().
operator=()
const BreakpointResolverScripted & lldb_private::BreakpointResolverScripted::operator= (const BreakpointResolverScripted &) private delete
References BreakpointResolverScripted().
SearchCallback()
Searcher::CallbackReturn BreakpointResolverScripted::SearchCallback (SearchFilter & filter, SymbolContext & context, Address * addr) override virtual
Implements lldb_private::Searcher.
Definition at line 126 of file BreakpointResolverScripted.cpp.
References lldb_private::Searcher::eCallbackReturnContinue, lldb_private::Searcher::eCallbackReturnStop, and m_interface_sp.
SerializeToStructuredData()
StructuredData::ObjectSP BreakpointResolverScripted::SerializeToStructuredData () override virtual
Reimplemented from lldb_private::BreakpointResolver.
Definition at line 109 of file BreakpointResolverScripted.cpp.
References lldb_private::BreakpointResolver::GetKey(), m_args, m_class_name, lldb_private::BreakpointResolver::PythonClassName, lldb_private::BreakpointResolver::ScriptArgs, and lldb_private::BreakpointResolver::WrapOptionsDict().
WasHit()
lldb::BreakpointLocationSP BreakpointResolverScripted::WasHit (lldb::StackFrameSP frame_sp, lldb::BreakpointLocationSP bp_loc_sp)
Definition at line 172 of file BreakpointResolverScripted.cpp.
References m_interface_sp.
Referenced by lldb_private::BreakpointLocation::WasHit().
Member Data Documentation
m_args
StructuredDataImpl lldb_private::BreakpointResolverScripted::m_args private
Definition at line 74 of file BreakpointResolverScripted.h.
Referenced by BreakpointResolverScripted(), CopyForBreakpoint(), CreateImplementationIfNeeded(), and SerializeToStructuredData().
m_class_name
std::string lldb_private::BreakpointResolverScripted::m_class_name private
Definition at line 72 of file BreakpointResolverScripted.h.
Referenced by BreakpointResolverScripted(), CopyForBreakpoint(), CreateImplementationIfNeeded(), GetDescription(), and SerializeToStructuredData().
m_depth
lldb::SearchDepth lldb_private::BreakpointResolverScripted::m_depth private
Definition at line 73 of file BreakpointResolverScripted.h.
Referenced by BreakpointResolverScripted(), and CopyForBreakpoint().
m_error
Status lldb_private::BreakpointResolverScripted::m_error private
Definition at line 75 of file BreakpointResolverScripted.h.
Referenced by CreateImplementationIfNeeded().
m_interface_sp
lldb::ScriptedBreakpointInterfaceSP lldb_private::BreakpointResolverScripted::m_interface_sp private
Definition at line 76 of file BreakpointResolverScripted.h.
Referenced by CreateImplementationIfNeeded(), GetDepth(), GetDescription(), GetLocationDescription(), SearchCallback(), and WasHit().
The documentation for this class was generated from the following files:
BreakpointResolverScripted.h
BreakpointResolverScripted.cpp