LLDB: lldb_private::MainLoopBase::ReadHandle Class Reference
lldb_private::MainLoopBase::ReadHandle Class Reference
Public Member Functions
~ReadHandle ()
Private Member Functions
ReadHandle (MainLoopBase &mainloop, IOObject::WaitableHandle handle)
ReadHandle (const ReadHandle &)=delete
const ReadHandle & operator= (const ReadHandle &)=delete
Private Attributes
MainLoopBase & m_mainloop
IOObject::WaitableHandle m_handle
Friends
class MainLoopBase
Detailed Description
Definition at line 109 of file MainLoopBase.h.
Constructor & Destructor Documentation
~ReadHandle()
lldb_private::MainLoopBase::ReadHandle::~ReadHandle () inline
Definition at line 111 of file MainLoopBase.h.
References m_handle, and m_mainloop.
ReadHandle() [1/2]
lldb_private::MainLoopBase::ReadHandle::ReadHandle (MainLoopBase & mainloop, IOObject::WaitableHandle handle) inline private
Definition at line 114 of file MainLoopBase.h.
References m_handle, m_mainloop, and MainLoopBase.
Referenced by operator=(), and ReadHandle().
ReadHandle() [2/2]
lldb_private::MainLoopBase::ReadHandle::ReadHandle (const ReadHandle &) private delete
References ReadHandle().
Member Function Documentation
operator=()
const ReadHandle & lldb_private::MainLoopBase::ReadHandle::operator= (const ReadHandle &) private delete
References ReadHandle().
Friends And Related Symbol Documentation
MainLoopBase
friend class MainLoopBase friend
Definition at line 120 of file MainLoopBase.h.
References MainLoopBase.
Referenced by MainLoopBase, and ReadHandle().
Member Data Documentation
m_handle
IOObject::WaitableHandle lldb_private::MainLoopBase::ReadHandle::m_handle private
Definition at line 118 of file MainLoopBase.h.
Referenced by ReadHandle(), and ~ReadHandle().
m_mainloop
MainLoopBase& lldb_private::MainLoopBase::ReadHandle::m_mainloop private
Definition at line 117 of file MainLoopBase.h.
Referenced by ReadHandle(), and ~ReadHandle().
The documentation for this class was generated from the following file:
MainLoopBase.h