LLDB: ABIMips Class Reference
ABIMips Class Reference
#include <ABIMips.h>
Static Public Member Functions
static void Initialize ()
static void Terminate ()
Detailed Description
Definition at line 12 of file ABIMips.h.
Member Function Documentation
Initialize()
void ABIMips::Initialize () static
Definition at line 16 of file ABIMips.cpp.
References Initialize(), ABISysV_mips64::Initialize(), and ABISysV_mips::Initialize().
Referenced by Initialize().
Terminate()
void ABIMips::Terminate () static
Definition at line 21 of file ABIMips.cpp.
References ABISysV_mips64::Terminate(), and ABISysV_mips::Terminate().
The documentation for this class was generated from the following files:
ABIMips.h
ABIMips.cpp