LLDB: lldb::SBProcessInfo Class Reference
lldb::SBProcessInfo Class Reference
#include <SBProcessInfo.h>
Public Member Functions
SBProcessInfo ()
SBProcessInfo (const SBProcessInfo &rhs)
~SBProcessInfo ()
SBProcessInfo & operator= (const SBProcessInfo &rhs)
operator bool () const
bool IsValid () const
const char * GetName ()
SBFileSpec GetExecutableFile ()
lldb::pid_t GetProcessID ()
uint32_t GetUserID ()
uint32_t GetGroupID ()
bool UserIDIsValid ()
bool GroupIDIsValid ()
uint32_t GetEffectiveUserID ()
uint32_t GetEffectiveGroupID ()
bool EffectiveUserIDIsValid ()
bool EffectiveGroupIDIsValid ()
lldb::pid_t GetParentProcessID ()
const char * GetTriple ()
Return the target triple (arch-vendor-os) for the described process.
Private Member Functions
lldb_private::ProcessInstanceInfo & ref ()
void SetProcessInfo (const lldb_private::ProcessInstanceInfo &proc_info_ref)
Private Attributes
std::unique_ptr< lldb_private::ProcessInstanceInfo > m_opaque_up
Friends
class SBProcess
class SBProcessInfoList
Detailed Description
Definition at line 16 of file SBProcessInfo.h.
Constructor & Destructor Documentation
SBProcessInfo() [1/2]
SBProcessInfo::SBProcessInfo ()
Definition at line 18 of file SBProcessInfo.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by operator=(), SBProcessInfo(), and ~SBProcessInfo().
SBProcessInfo() [2/2]
SBProcessInfo::SBProcessInfo (const SBProcessInfo & rhs)
Definition at line 20 of file SBProcessInfo.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBProcessInfo().
~SBProcessInfo()
SBProcessInfo::~SBProcessInfo () default
References EffectiveGroupIDIsValid(), EffectiveUserIDIsValid(), GetEffectiveGroupID(), GetEffectiveUserID(), GetExecutableFile(), GetGroupID(), GetParentProcessID(), GetProcessID(), GetTriple(), GetUserID(), GroupIDIsValid(), IsValid(), operator=(), SBProcessInfo(), and UserIDIsValid().
Member Function Documentation
EffectiveGroupIDIsValid()
bool SBProcessInfo::EffectiveGroupIDIsValid ()
Definition at line 156 of file SBProcessInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBProcessInfo().
EffectiveUserIDIsValid()
bool SBProcessInfo::EffectiveUserIDIsValid ()
Definition at line 146 of file SBProcessInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBProcessInfo().
GetEffectiveGroupID()
uint32_t SBProcessInfo::GetEffectiveGroupID ()
Definition at line 136 of file SBProcessInfo.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and UINT32_MAX.
Referenced by ~SBProcessInfo().
GetEffectiveUserID()
uint32_t SBProcessInfo::GetEffectiveUserID ()
Definition at line 126 of file SBProcessInfo.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and UINT32_MAX.
Referenced by ~SBProcessInfo().
GetExecutableFile()
SBFileSpec SBProcessInfo::GetExecutableFile ()
Definition at line 66 of file SBProcessInfo.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBFileSpec::SetFileSpec().
Referenced by ~SBProcessInfo().
GetGroupID()
uint32_t SBProcessInfo::GetGroupID ()
Definition at line 96 of file SBProcessInfo.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and UINT32_MAX.
Referenced by ~SBProcessInfo().
GetName()
const char * SBProcessInfo::GetName ()
Definition at line 57 of file SBProcessInfo.cpp.
References lldb_private::ConstString::GetCString(), LLDB_INSTRUMENT_VA, and m_opaque_up.
GetParentProcessID()
lldb::pid_t SBProcessInfo::GetParentProcessID ()
Definition at line 166 of file SBProcessInfo.cpp.
References LLDB_INSTRUMENT_VA, LLDB_INVALID_PROCESS_ID, and m_opaque_up.
Referenced by ~SBProcessInfo().
GetProcessID()
lldb::pid_t SBProcessInfo::GetProcessID ()
Definition at line 76 of file SBProcessInfo.cpp.
References LLDB_INSTRUMENT_VA, LLDB_INVALID_PROCESS_ID, and m_opaque_up.
Referenced by ~SBProcessInfo().
GetTriple()
const char * SBProcessInfo::GetTriple ()
Return the target triple (arch-vendor-os) for the described process.
Definition at line 176 of file SBProcessInfo.cpp.
References lldb_private::ConstString::GetCString(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBProcessInfo().
GetUserID()
uint32_t SBProcessInfo::GetUserID ()
Definition at line 86 of file SBProcessInfo.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and UINT32_MAX.
Referenced by ~SBProcessInfo().
GroupIDIsValid()
bool SBProcessInfo::GroupIDIsValid ()
Definition at line 116 of file SBProcessInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBProcessInfo().
IsValid()
bool SBProcessInfo::IsValid () const
Definition at line 47 of file SBProcessInfo.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBProcessInfo().
operator bool()
SBProcessInfo::operator bool () const explicit
Definition at line 51 of file SBProcessInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
operator=()
SBProcessInfo & SBProcessInfo::operator= (const SBProcessInfo & rhs)
Definition at line 28 of file SBProcessInfo.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBProcessInfo().
Referenced by ~SBProcessInfo().
ref()
ProcessInstanceInfo & SBProcessInfo::ref () private
Definition at line 36 of file SBProcessInfo.cpp.
References m_opaque_up.
Referenced by SBProcessInfoList, and SetProcessInfo().
SetProcessInfo()
void SBProcessInfo::SetProcessInfo (const lldb_private::ProcessInstanceInfo & proc_info_ref) private
Definition at line 43 of file SBProcessInfo.cpp.
References ref().
Referenced by lldb::SBProcess::GetProcessInfo(), lldb::SBProcessInfoList::GetProcessInfoAtIndex(), and SBProcessInfoList.
UserIDIsValid()
bool SBProcessInfo::UserIDIsValid ()
Definition at line 106 of file SBProcessInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBProcessInfo().
Friends And Related Symbol Documentation
SBProcess
friend class SBProcess friend
Definition at line 57 of file SBProcessInfo.h.
References SBProcess.
Referenced by SBProcess.
SBProcessInfoList
friend class SBProcessInfoList friend
Definition at line 58 of file SBProcessInfo.h.
References ref(), SBProcessInfoList, and SetProcessInfo().
Referenced by SBProcessInfoList.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::ProcessInstanceInfo> lldb::SBProcessInfo::m_opaque_up private
Definition at line 64 of file SBProcessInfo.h.
Referenced by EffectiveGroupIDIsValid(), EffectiveUserIDIsValid(), GetEffectiveGroupID(), GetEffectiveUserID(), GetExecutableFile(), GetGroupID(), GetName(), GetParentProcessID(), GetProcessID(), GetTriple(), GetUserID(), GroupIDIsValid(), operator bool(), operator=(), ref(), SBProcessInfo(), and UserIDIsValid().
The documentation for this class was generated from the following files:
SBProcessInfo.h
SBProcessInfo.cpp