LLDB: ValueListImpl Class Reference
ValueListImpl Class Reference
Public Member Functions
ValueListImpl ()=default
ValueListImpl (const ValueListImpl &rhs)
ValueListImpl & operator= (const ValueListImpl &rhs)
uint32_t GetSize ()
void Append (const lldb::SBValue &sb_value)
void Append (const ValueListImpl &list)
lldb::SBValue GetValueAtIndex (uint32_t index)
lldb::SBValue FindValueByUID (lldb::user_id_t uid)
lldb::SBValue GetFirstValueByName (const char *name) const
const Status & GetError () const
void SetError (Status &&error)
Private Attributes
std::vector< lldb::SBValue > m_values
Status m_error
Detailed Description
Definition at line 21 of file SBValueList.cpp.
Constructor & Destructor Documentation
ValueListImpl() [1/2]
ValueListImpl::ValueListImpl () default
Referenced by Append(), operator=(), and ValueListImpl().
ValueListImpl() [2/2]
ValueListImpl::ValueListImpl (const ValueListImpl & rhs) inline
Definition at line 25 of file SBValueList.cpp.
References m_error, m_values, and ValueListImpl().
Member Function Documentation
Append() [1/2]
void ValueListImpl::Append (const lldb::SBValue & sb_value) inline
Definition at line 38 of file SBValueList.cpp.
References m_values.
Referenced by Append().
Append() [2/2]
void ValueListImpl::Append (const ValueListImpl & list) inline
Definition at line 40 of file SBValueList.cpp.
References Append(), m_values, and ValueListImpl().
FindValueByUID()
lldb::SBValue ValueListImpl::FindValueByUID (lldb::user_id_t uid) inline
Definition at line 51 of file SBValueList.cpp.
References m_values, and lldb::SBValue.
GetError()
const Status & ValueListImpl::GetError () const inline
Definition at line 69 of file SBValueList.cpp.
References m_error.
GetFirstValueByName()
lldb::SBValue ValueListImpl::GetFirstValueByName (const char * name) const inline
Definition at line 59 of file SBValueList.cpp.
References m_values, and lldb::SBValue.
GetSize()
uint32_t ValueListImpl::GetSize () inline
Definition at line 36 of file SBValueList.cpp.
References m_values.
Referenced by GetValueAtIndex(), and ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectListSP >().
GetValueAtIndex()
lldb::SBValue ValueListImpl::GetValueAtIndex (uint32_t index) inline
Definition at line 45 of file SBValueList.cpp.
References GetSize(), m_values, and lldb::SBValue.
Referenced by ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectListSP >().
operator=()
ValueListImpl & ValueListImpl::operator= (const ValueListImpl & rhs) inline
Definition at line 28 of file SBValueList.cpp.
References lldb_private::Status::Clone(), m_error, m_values, and ValueListImpl().
SetError()
void ValueListImpl::SetError (Status && error) inline
Definition at line 71 of file SBValueList.cpp.
References error(), and m_error.
Referenced by lldb::SBValueList::SetError().
Member Data Documentation
m_error
Status ValueListImpl::m_error private
Definition at line 75 of file SBValueList.cpp.
Referenced by GetError(), operator=(), SetError(), and ValueListImpl().
m_values
std::vector<lldb::SBValue> ValueListImpl::m_values private
Definition at line 74 of file SBValueList.cpp.
Referenced by Append(), Append(), FindValueByUID(), GetFirstValueByName(), GetSize(), GetValueAtIndex(), operator=(), and ValueListImpl().
The documentation for this class was generated from the following file:
SBValueList.cpp