LLDB: lldb_private::DebuggerStats Class Reference
lldb_private::DebuggerStats Class Reference
#include <Statistics.h>
Static Public Member Functions
static void SetCollectingStats (bool enable)
static bool GetCollectingStats ()
static llvm::json::Value ReportStatistics (Debugger &debugger, Target *target, const lldb_private::StatisticsOptions &options)
Get metrics associated with one or all targets in a debugger in JSON format.
static void ResetStatistics (Debugger &debugger, Target *target)
Reset metrics associated with one or all targets in a debugger.
Static Protected Attributes
static bool g_collecting_stats = false
Detailed Description
Definition at line 345 of file Statistics.h.
Member Function Documentation
GetCollectingStats()
bool lldb_private::DebuggerStats::GetCollectingStats () inline static
Definition at line 348 of file Statistics.h.
References g_collecting_stats.
Referenced by CommandObjectStatsDisable::DoExecute(), CommandObjectStatsEnable::DoExecute(), and lldb::SBTarget::GetCollectingStats().
ReportStatistics()
llvm::json::Value DebuggerStats::ReportStatistics (Debugger & debugger, Target * target, const lldb_private::StatisticsOptions & options) static
Get metrics associated with one or all targets in a debugger in JSON format.
Parameters
debugger The debugger to get the target list from if target is NULL.
target The single target to emit statistics for if non NULL, otherwise dump statistics only for the specified target.
summary_only If true, only report high level summary statistics without targets/modules/breakpoints etc.. details.
Returns
Returns a JSON value that contains all target metrics.
Definition at line 301 of file Statistics.cpp.
References lldb_private::ModuleStats::debug_index_time, lldb_private::ModuleStats::debug_info_enabled, lldb_private::ModuleStats::debug_info_had_incomplete_types, lldb_private::ModuleStats::debug_info_had_variable_errors, lldb_private::ModuleStats::debug_info_index_loaded_from_cache, lldb_private::ModuleStats::debug_info_index_saved_to_cache, lldb_private::ModuleStats::debug_info_size, lldb_private::ModuleStats::debug_parse_time, lldb_private::ModuleStats::dwo_stats, lldb_private::Module::GetAllocatedModuleAtIndex(), lldb_private::Module::GetAllocationModuleCollectionMutex(), lldb_private::SymbolFile::GetDebugInfoHadFrameVariableErrors(), lldb_private::SymbolFile::GetDebugInfoIndexTime(), lldb_private::SymbolFile::GetDebugInfoIndexWasLoadedFromCache(), lldb_private::SymbolFile::GetDebugInfoIndexWasSavedToCache(), lldb_private::SymbolFile::GetDebugInfoModules(), lldb_private::SymbolFile::GetDebugInfoParseTime(), lldb_private::SymbolFile::GetDebugInfoSize(), lldb_private::SymbolFile::GetDwoStats(), lldb_private::ObjectFile::GetFileSpec(), lldb_private::Target::GetImages(), lldb_private::StatisticsOptions::GetIncludeModules(), lldb_private::StatisticsOptions::GetIncludePlugins(), lldb_private::StatisticsOptions::GetIncludeTargets(), lldb_private::StatisticsOptions::GetIncludeTranscript(), lldb_private::StatisticsOptions::GetLoadAllDebugInfo(), lldb_private::SymbolFile::GetLoadDebugInfoEnabled(), lldb_private::ModuleList::GetModuleAtIndex(), lldb_private::Module::GetNumberAllocatedModules(), lldb_private::Symtab::GetNumSymbols(), lldb_private::Module::GetObjectFile(), lldb_private::SymbolFile::GetObjectFile(), lldb_private::FileSpec::GetPath(), lldb_private::ModuleList::GetSize(), lldb_private::StatisticsOptions::GetSummaryOnly(), lldb_private::Symtab::GetWasLoadedFromCache(), lldb_private::Symtab::GetWasSavedToCache(), lldb_private::StatisticsMap::merge(), lldb_private::ModuleList::Modules(), lldb_private::ModuleStats::symbol_locator_time, lldb_private::ModuleStats::symfile_modules, lldb_private::ModuleStats::symfile_path, lldb_private::ModuleStats::symtab_index_time, lldb_private::ModuleStats::symtab_loaded_from_cache, lldb_private::ModuleStats::symtab_parse_time, lldb_private::ModuleStats::symtab_saved_to_cache, lldb_private::ModuleStats::symtab_stripped, and lldb_private::ModuleStats::symtab_symbol_count.
Referenced by CommandObjectStatsDump::DoExecute(), and lldb::SBTarget::GetStatistics().
ResetStatistics()
void DebuggerStats::ResetStatistics (Debugger & debugger, Target * target) static
Reset metrics associated with one or all targets in a debugger.
Parameters
debugger The debugger to reset the target list from if target is NULL.
target The target to reset statistics for, or if null, reset statistics for all targets
Definition at line 279 of file Statistics.cpp.
References lldb_private::Module::GetAllocatedModuleAtIndex(), lldb_private::Module::GetAllocationModuleCollectionMutex(), lldb_private::Target::GetImages(), lldb_private::ModuleList::GetModuleAtIndex(), lldb_private::Module::GetNumberAllocatedModules(), lldb_private::ModuleList::GetSize(), lldb_private::Debugger::GetTargetList(), lldb_private::Target::ResetStatistics(), and lldb_private::TargetList::Targets().
Referenced by lldb::SBDebugger::ResetStatistics(), and lldb::SBTarget::ResetStatistics().
SetCollectingStats()
void lldb_private::DebuggerStats::SetCollectingStats (bool enable) inline static
Definition at line 347 of file Statistics.h.
References g_collecting_stats.
Referenced by CommandObjectStatsDisable::DoExecute(), CommandObjectStatsEnable::DoExecute(), and lldb::SBTarget::SetCollectingStats().
Member Data Documentation
g_collecting_stats
bool DebuggerStats::g_collecting_stats = false static protected
Definition at line 385 of file Statistics.h.
Referenced by GetCollectingStats(), and SetCollectingStats().
The documentation for this class was generated from the following files:
Statistics.h
Statistics.cpp