LLDB: ABISysV_riscv Class Reference
ABISysV_riscv Class Reference
#include <ABISysV_riscv.h>
Public Member Functions
~ABISysV_riscv () override=default
size_t GetRedZoneSize () const override
bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override
bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::Type &prototype, llvm::ArrayRef< ABI::CallArgument > args) const override
bool GetArgumentValues (lldb_private::Thread &thread, lldb_private::ValueList &values) const override
lldb_private::Status SetReturnValueObject (lldb::StackFrameSP &frame_sp, lldb::ValueObjectSP &new_value) override
lldb::ValueObjectSP GetReturnValueObjectImpl (lldb_private::Thread &thread, lldb_private::CompilerType &type) const override
lldb::ValueObjectSP GetReturnValueObjectImpl (lldb_private::Thread &thread, llvm::Type &type) const override
lldb::UnwindPlanSP CreateFunctionEntryUnwindPlan () override
lldb::UnwindPlanSP CreateDefaultUnwindPlan () override
bool RegisterIsVolatile (const lldb_private::RegisterInfo *reg_info) override
bool CallFrameAddressIsValid (lldb::addr_t cfa) override
void SetIsRV64 (bool is_rv64)
bool CodeAddressIsValid (lldb::addr_t pc) override
const lldb_private::RegisterInfo * GetRegisterInfoArray (uint32_t &count) override
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::RegInfoBasedABI
void AugmentRegisterInfo (std::vector< DynamicRegisterInfo::Register > &regs) override
Public Member Functions inherited from lldb_private::ABI
~ABI () override
virtual bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::Type &prototype, llvm::ArrayRef< CallArgument > args) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, CompilerType &type, bool persistent=true) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, llvm::Type &type, bool persistent=true) const
virtual bool GetFallbackRegisterLocation (const RegisterInfo *reg_info, UnwindPlan::Row::AbstractRegisterLocation &unwind_regloc)
virtual lldb::addr_t FixAnyAddress (lldb::addr_t pc)
Use this method when you do not know, or do not care what kind of address you are fixing.
llvm::MCRegisterInfo & GetMCRegisterInfo ()
virtual bool GetPointerReturnRegister (const char *&name)
virtual uint64_t GetStackFrameSize ()
virtual lldb::addr_t FixCodeAddress (lldb::addr_t pc)
Some targets might use bits in a code address to indicate a mode switch.
virtual lldb::addr_t FixDataAddress (lldb::addr_t pc)
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static lldb::ABISP CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec &arch)
static llvm::StringRef GetPluginNameStatic ()
Static Public Member Functions inherited from lldb_private::ABI
static lldb::ABISP FindPlugin (lldb::ProcessSP process_sp, const ArchSpec &arch)
Protected Member Functions
void AugmentRegisterInfo (std::vector< lldb_private::DynamicRegisterInfo::Register > &regs) override
bool RegisterIsCalleeSaved (const lldb_private::RegisterInfo *reg_info)
Protected Member Functions inherited from lldb_private::RegInfoBasedABI
bool GetRegisterInfoByName (llvm::StringRef name, RegisterInfo &info)
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Protected Member Functions inherited from lldb_private::ABI
lldb::ProcessSP GetProcessSP () const
Request to get a Process shared pointer.
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Private Member Functions
lldb::ValueObjectSP GetReturnValueObjectSimple (lldb_private::Thread &thread, lldb_private::CompilerType &ast_type) const
Private Attributes
bool m_is_rv64
Additional Inherited Members
Static Protected Member Functions inherited from lldb_private::ABI
static std::unique_ptr< llvm::MCRegisterInfo > MakeMCRegisterInfo (const ArchSpec &arch)
Utility function to construct a MCRegisterInfo using the ArchSpec triple.
Protected Attributes inherited from lldb_private::ABI
lldb::ProcessWP m_process_wp
std::unique_ptr< llvm::MCRegisterInfo > m_mc_register_info_up
Detailed Description
Definition at line 21 of file ABISysV_riscv.h.
Constructor & Destructor Documentation
~ABISysV_riscv()
ABISysV_riscv::~ABISysV_riscv () override default
Member Function Documentation
AugmentRegisterInfo()
void ABISysV_riscv::AugmentRegisterInfo (std::vector< lldb_private::DynamicRegisterInfo::Register > & regs) override protected virtual
Implements lldb_private::ABI.
Definition at line 834 of file ABISysV_riscv.cpp.
References lldb_private::RegInfoBasedABI::AugmentRegisterInfo(), and GetGenericNum().
CallFrameAddressIsValid()
bool ABISysV_riscv::CallFrameAddressIsValid (lldb::addr_t cfa) inline override virtual
Implements lldb_private::ABI.
Definition at line 60 of file ABISysV_riscv.h.
References lldb_private::ArchSpec::eRISCV_rve, lldb_private::ArchSpec::GetFlags(), lldb_private::ABI::GetProcessSP(), and lldb_private::Flags::Test().
CodeAddressIsValid()
bool ABISysV_riscv::CodeAddressIsValid (lldb::addr_t pc) inline override virtual
Implements lldb_private::ABI.
Definition at line 71 of file ABISysV_riscv.h.
References lldb_private::ArchSpec::eRISCV_rvc, lldb_private::ArchSpec::GetFlags(), lldb_private::ArchSpec::GetMachine(), lldb_private::ABI::GetProcessSP(), pc, lldb_private::Flags::Test(), and UINT32_MAX.
CreateDefaultUnwindPlan()
UnwindPlanSP ABISysV_riscv::CreateDefaultUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 739 of file ABISysV_riscv.cpp.
References lldb_private::eLazyBoolNo, lldb::eRegisterKindGeneric, lldb_private::UnwindPlan::Row::GetCFAValue(), LLDB_REGNUM_GENERIC_FP, LLDB_REGNUM_GENERIC_PC, m_is_rv64, reg_size, lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), and lldb_private::UnwindPlan::Row::SetRegisterLocationToAtCFAPlusOffset().
CreateFunctionEntryUnwindPlan()
UnwindPlanSP ABISysV_riscv::CreateFunctionEntryUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 717 of file ABISysV_riscv.cpp.
References riscv_dwarf::dwarf_gpr_pc, riscv_dwarf::dwarf_gpr_ra, riscv_dwarf::dwarf_gpr_sp, lldb_private::eLazyBoolNo, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), and lldb_private::UnwindPlan::Row::SetRegisterLocationToRegister().
CreateInstance()
ABISP ABISysV_riscv::CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec & arch) static
Definition at line 140 of file ABISysV_riscv.cpp.
References lldb_private::ArchSpec::GetTriple(), lldb_private::ABI::MakeMCRegisterInfo(), and SetIsRV64().
Referenced by Initialize(), and Terminate().
GetArgumentValues()
bool ABISysV_riscv::GetArgumentValues (lldb_private::Thread & thread, lldb_private::ValueList & values) const override virtual
Implements lldb_private::ABI.
Definition at line 362 of file ABISysV_riscv.cpp.
GetPluginName()
llvm::StringRef ABISysV_riscv::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 110 of file ABISysV_riscv.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef ABISysV_riscv::GetPluginNameStatic () inline static
Definition at line 104 of file ABISysV_riscv.h.
Referenced by GetPluginName(), and Initialize().
GetRedZoneSize()
size_t ABISysV_riscv::GetRedZoneSize () const inline override virtual
Implements lldb_private::ABI.
Definition at line 25 of file ABISysV_riscv.h.
GetRegisterInfoArray()
const RegisterInfo * ABISysV_riscv::GetRegisterInfoArray (uint32_t & count) override virtual
Implements lldb_private::RegInfoBasedABI.
Definition at line 130 of file ABISysV_riscv.cpp.
GetReturnValueObjectImpl() [1/2]
ValueObjectSP ABISysV_riscv::GetReturnValueObjectImpl (lldb_private::Thread & thread, lldb_private::CompilerType & type) const override virtual
Implements lldb_private::ABI.
Definition at line 706 of file ABISysV_riscv.cpp.
References GetReturnValueObjectSimple().
GetReturnValueObjectImpl() [2/2]
ValueObjectSP ABISysV_riscv::GetReturnValueObjectImpl (lldb_private::Thread & thread, llvm::Type & type) const override virtual
Reimplemented from lldb_private::ABI.
Definition at line 658 of file ABISysV_riscv.cpp.
References lldb_private::ValueObjectConstResult::Create(), lldb::eRegisterKindGeneric, lldb_private::ArchSpec::eRISCV_float_abi_mask, lldb_private::ArchSpec::GetFlags(), lldb_private::ArchSpec::GetMachine(), lldb_private::Value::GetScalar(), GetValObjFromFPRegs(), GetValObjFromIntRegs(), LLDB_REGNUM_GENERIC_ARG1, lldb_private::Value::Scalar, and lldb_private::Value::SetValueType().
GetReturnValueObjectSimple()
ValueObjectSP ABISysV_riscv::GetReturnValueObjectSimple (lldb_private::Thread & thread, lldb_private::CompilerType & ast_type) const private
Definition at line 609 of file ABISysV_riscv.cpp.
References lldb_private::ValueObjectConstResult::Create(), lldb::eRegisterKindGeneric, lldb_private::ArchSpec::eRISCV_float_abi_mask, lldb_private::CompilerType::GetByteSize(), lldb_private::ArchSpec::GetFlags(), lldb_private::ArchSpec::GetMachine(), lldb_private::Value::GetScalar(), lldb_private::CompilerType::GetTypeInfo(), GetValObjFromFPRegs(), GetValObjFromIntRegs(), lldb_private::CompilerType::IsRealFloatingPointType(), LLDB_REGNUM_GENERIC_ARG1, lldb_private::Value::Scalar, lldb_private::Value::SetCompilerType(), and lldb_private::Value::SetValueType().
Referenced by GetReturnValueObjectImpl().
Initialize()
void ABISysV_riscv::Initialize () static
Definition at line 808 of file ABISysV_riscv.cpp.
References CreateInstance(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
PrepareTrivialCall() [1/2]
bool ABISysV_riscv::PrepareTrivialCall (lldb_private::Thread & thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override virtual
Implements lldb_private::ABI.
References sp.
PrepareTrivialCall() [2/2]
bool ABISysV_riscv::PrepareTrivialCall (lldb_private::Thread & thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::Type & prototype, llvm::ArrayRef< ABI::CallArgument > args) const override
References sp.
RegisterIsCalleeSaved()
bool ABISysV_riscv::RegisterIsCalleeSaved (const lldb_private::RegisterInfo * reg_info) protected
Definition at line 771 of file ABISysV_riscv.cpp.
References lldb_private::ArchSpec::eRISCV_float_abi_mask, lldb_private::ArchSpec::GetFlags(), lldb_private::ABI::GetProcessSP(), and lldb_private::RegisterInfo::name.
Referenced by RegisterIsVolatile().
RegisterIsVolatile()
bool ABISysV_riscv::RegisterIsVolatile (const lldb_private::RegisterInfo * reg_info) override virtual
Implements lldb_private::ABI.
Definition at line 767 of file ABISysV_riscv.cpp.
References RegisterIsCalleeSaved().
SetIsRV64()
void ABISysV_riscv::SetIsRV64 (bool is_rv64) inline
Definition at line 69 of file ABISysV_riscv.h.
References m_is_rv64.
Referenced by CreateInstance().
SetReturnValueObject()
Status ABISysV_riscv::SetReturnValueObject (lldb::StackFrameSP & frame_sp, lldb::ValueObjectSP & new_value) override virtual
Implements lldb_private::ABI.
Definition at line 367 of file ABISysV_riscv.cpp.
References lldb_private::Status::AsCString(), lldb::eRegisterKindGeneric, lldb_private::Status::Fail(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataExtractor::GetMaxU64(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), lldb_private::CompilerType::IsPointerType(), LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_ARG2, m_is_rv64, lldb_private::RegisterInfo::name, and reg_size.
Terminate()
void ABISysV_riscv::Terminate () static
Definition at line 813 of file ABISysV_riscv.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Member Data Documentation
m_is_rv64
bool ABISysV_riscv::m_is_rv64 private
Definition at line 125 of file ABISysV_riscv.h.
Referenced by CreateDefaultUnwindPlan(), SetIsRV64(), and SetReturnValueObject().
The documentation for this class was generated from the following files:
ABISysV_riscv.h
ABISysV_riscv.cpp