LLDB: lldb_private::telemetry::NoOpTelemetryManager Class Reference
lldb_private::telemetry::NoOpTelemetryManager Class Reference
Public Member Functions
llvm::Error preDispatch (llvm::telemetry::TelemetryInfo *entry) override
NoOpTelemetryManager ()
virtual llvm::StringRef GetInstanceName () const override
void DispatchClientTelemetry (const lldb_private::StructuredDataImpl &entry, Debugger *debugger) override
llvm::Error dispatch (llvm::telemetry::TelemetryInfo *entry) override
Public Member Functions inherited from lldb_private::telemetry::TelemetryManager
llvm::Error preDispatch (llvm::telemetry::TelemetryInfo *entry) override
const LLDBConfig * GetConfig ()
Static Public Member Functions
static NoOpTelemetryManager * GetInstance ()
Static Public Member Functions inherited from lldb_private::telemetry::TelemetryManager
static TelemetryManager * GetInstance ()
Additional Inherited Members
Protected Member Functions inherited from lldb_private::telemetry::TelemetryManager
TelemetryManager (std::unique_ptr< LLDBConfig > config)
const std::string & GetSessionId () const
Static Protected Member Functions inherited from lldb_private::telemetry::TelemetryManager
static void SetInstance (std::unique_ptr< TelemetryManager > manger)
Detailed Description
Definition at line 181 of file Telemetry.cpp.
Constructor & Destructor Documentation
NoOpTelemetryManager()
lldb_private::telemetry::NoOpTelemetryManager::NoOpTelemetryManager () inline explicit
Definition at line 188 of file Telemetry.cpp.
References lldb_private::telemetry::TelemetryManager::TelemetryManager().
Referenced by GetInstance().
Member Function Documentation
dispatch()
llvm::Error lldb_private::telemetry::NoOpTelemetryManager::dispatch (llvm::telemetry::TelemetryInfo * entry) inline override
Definition at line 202 of file Telemetry.cpp.
DispatchClientTelemetry()
void lldb_private::telemetry::NoOpTelemetryManager::DispatchClientTelemetry (const lldb_private::StructuredDataImpl & entry, Debugger * debugger) inline override virtual
Reimplemented from lldb_private::telemetry::TelemetryManager.
Definition at line 197 of file Telemetry.cpp.
GetInstance()
NoOpTelemetryManager * lldb_private::telemetry::NoOpTelemetryManager::GetInstance () inline static
Definition at line 207 of file Telemetry.cpp.
References NoOpTelemetryManager().
Referenced by lldb_private::telemetry::TelemetryManager::GetInstance().
GetInstanceName()
virtual llvm::StringRef lldb_private::telemetry::NoOpTelemetryManager::GetInstanceName () const inline override virtual
Implements lldb_private::telemetry::TelemetryManager.
Definition at line 193 of file Telemetry.cpp.
preDispatch()
llvm::Error lldb_private::telemetry::NoOpTelemetryManager::preDispatch (llvm::telemetry::TelemetryInfo * entry) inline override
Definition at line 183 of file Telemetry.cpp.
The documentation for this class was generated from the following file:
Telemetry.cpp