LLDB: CoreSimulatorSupport::ModelIdentifier Class Reference
CoreSimulatorSupport::ModelIdentifier Class Reference
#include <PlatformiOSSimulatorCoreSimulatorSupport.h>
Public Member Functions
ModelIdentifier (const std::string &mi)
ModelIdentifier ()
operator bool () const
size_t GetNumVersions () const
unsigned int GetVersionAtIndex (size_t idx) const
std::string GetFamily () const
Private Attributes
std::string m_family
std::vector< unsigned int > m_versions
Detailed Description
Definition at line 52 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
Constructor & Destructor Documentation
ModelIdentifier() [1/2]
CoreSimulatorSupport::ModelIdentifier::ModelIdentifier (const std::string & mi)
Definition at line 111 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References m_family, and m_versions.
Referenced by ModelIdentifier().
ModelIdentifier() [2/2]
CoreSimulatorSupport::ModelIdentifier::ModelIdentifier ()
Definition at line 142 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References ModelIdentifier().
Member Function Documentation
GetFamily()
std::string CoreSimulatorSupport::ModelIdentifier::GetFamily () const inline
Definition at line 63 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
References m_family.
Referenced by CoreSimulatorSupport::operator!=(), CoreSimulatorSupport::operator<(), CoreSimulatorSupport::operator==(), and CoreSimulatorSupport::operator>().
GetNumVersions()
size_t CoreSimulatorSupport::ModelIdentifier::GetNumVersions () const inline
Definition at line 59 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
References m_versions.
Referenced by CoreSimulatorSupport::operator!=(), CoreSimulatorSupport::operator<(), CoreSimulatorSupport::operator==(), and CoreSimulatorSupport::operator>().
GetVersionAtIndex()
unsigned int CoreSimulatorSupport::ModelIdentifier::GetVersionAtIndex (size_t idx) const inline
Definition at line 61 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
References m_versions.
Referenced by CoreSimulatorSupport::operator!=(), CoreSimulatorSupport::operator<(), CoreSimulatorSupport::operator==(), and CoreSimulatorSupport::operator>().
operator bool()
CoreSimulatorSupport::ModelIdentifier::operator bool () const inline explicit
Definition at line 57 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
References m_versions.
Member Data Documentation
m_family
std::string CoreSimulatorSupport::ModelIdentifier::m_family private
Definition at line 66 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
Referenced by GetFamily(), and ModelIdentifier().
m_versions
std::vector<unsigned int> CoreSimulatorSupport::ModelIdentifier::m_versions private
Definition at line 67 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
Referenced by GetNumVersions(), GetVersionAtIndex(), ModelIdentifier(), and operator bool().
The documentation for this class was generated from the following files:
PlatformiOSSimulatorCoreSimulatorSupport.h
PlatformiOSSimulatorCoreSimulatorSupport.mm