LLDB: lldb_private::FormatManager Class Reference
lldb_private::FormatManager Class Reference
#include <FormatManager.h>
Public Types
typedef std::map< lldb::LanguageType, LanguageCategory::UniquePointer > LanguageCategories
Public Member Functions
FormatManager ()
~FormatManager () override=default
NamedSummariesMap & GetNamedSummaryContainer ()
void EnableCategory (ConstString category_name, TypeCategoryMap::Position pos=TypeCategoryMap::Default)
void EnableCategory (ConstString category_name, TypeCategoryMap::Position pos, lldb::LanguageType lang)
void DisableCategory (ConstString category_name)
void EnableCategory (const lldb::TypeCategoryImplSP &category, TypeCategoryMap::Position pos=TypeCategoryMap::Default)
void DisableCategory (const lldb::TypeCategoryImplSP &category)
void EnableAllCategories ()
void DisableAllCategories ()
bool DeleteCategory (ConstString category_name)
void ClearCategories ()
uint32_t GetCategoriesCount ()
lldb::TypeCategoryImplSP GetCategoryAtIndex (size_t index)
void ForEachCategory (TypeCategoryMap::ForEachCallback callback)
lldb::TypeCategoryImplSP GetCategory (const char *category_name=nullptr, bool can_create=true)
lldb::TypeCategoryImplSP GetCategory (ConstString category_name, bool can_create=true)
lldb::TypeFormatImplSP GetFormatForType (lldb::TypeNameSpecifierImplSP type_sp)
lldb::TypeSummaryImplSP GetSummaryForType (lldb::TypeNameSpecifierImplSP type_sp)
lldb::TypeFilterImplSP GetFilterForType (lldb::TypeNameSpecifierImplSP type_sp)
lldb::ScriptedSyntheticChildrenSP GetSyntheticForType (lldb::TypeNameSpecifierImplSP type_sp)
lldb::TypeFormatImplSP GetFormat (ValueObject &valobj, lldb::DynamicValueType use_dynamic)
lldb::TypeSummaryImplSP GetSummaryFormat (ValueObject &valobj, lldb::DynamicValueType use_dynamic)
lldb::SyntheticChildrenSP GetSyntheticChildren (ValueObject &valobj, lldb::DynamicValueType use_dynamic)
bool AnyMatches (const FormattersMatchCandidate &candidate_type, TypeCategoryImpl::FormatCategoryItems items=TypeCategoryImpl::ALL_ITEM_TYPES, bool only_enabled=true, const char **matching_category=nullptr, TypeCategoryImpl::FormatCategoryItems *matching_type=nullptr)
bool ShouldPrintAsOneLiner (ValueObject &valobj)
void Changed () override
uint32_t GetCurrentRevision () override
LanguageCategory * GetCategoryForLanguage (lldb::LanguageType lang_type)
Public Member Functions inherited from lldb_private::IFormatChangeListener
virtual ~IFormatChangeListener ()=default
Static Public Member Functions
static bool GetFormatFromCString (const char *format_cstr, lldb::Format &format)
static char GetFormatAsFormatChar (lldb::Format format)
static const char * GetFormatAsCString (lldb::Format format)
static lldb::Format GetSingleItemFormat (lldb::Format vector_format)
static FormattersMatchVector GetPossibleMatches (ValueObject &valobj, lldb::DynamicValueType use_dynamic)
static ConstString GetTypeForCache (ValueObject &, lldb::DynamicValueType)
static std::vector< lldb::LanguageType > GetCandidateLanguages (lldb::LanguageType lang_type)
Private Types
typedef FormattersContainer< TypeSummaryImpl > NamedSummariesMap
typedef TypeCategoryMap::MapType::iterator CategoryMapIterator
Private Member Functions
template<typename ImplSP>
ImplSP Get (ValueObject &valobj, lldb::DynamicValueType use_dynamic)
template<typename ImplSP>
ImplSP GetCached (FormattersMatchData &match_data)
template<typename ImplSP>
ImplSP GetHardcoded (FormattersMatchData &)
TypeCategoryMap & GetCategories ()
void LoadSystemFormatters ()
void LoadVectorFormatters ()
Static Private Member Functions
static void GetPossibleMatches (ValueObject &valobj, CompilerType compiler_type, lldb::DynamicValueType use_dynamic, FormattersMatchVector &entries, FormattersMatchCandidate::Flags current_flags, bool root_level=false, uint32_t ptr_stripped_depth=0)
Private Attributes
std::atomic< uint32_t > m_last_revision
FormatCache m_format_cache
std::recursive_mutex m_language_categories_mutex
LanguageCategories m_language_categories_map
NamedSummariesMap m_named_summaries_map
TypeCategoryMap m_categories_map
ConstString m_default_category_name
ConstString m_system_category_name
ConstString m_vectortypes_category_name
Friends
class FormattersMatchData
Detailed Description
Definition at line 36 of file FormatManager.h.
Member Typedef Documentation
CategoryMapIterator
typedef TypeCategoryMap::MapType::iterator lldb_private::FormatManager::CategoryMapIterator private
Definition at line 38 of file FormatManager.h.
LanguageCategories
typedef std::map<lldb::LanguageType, LanguageCategory::UniquePointer> lldb_private::FormatManager::LanguageCategories
Definition at line 42 of file FormatManager.h.
NamedSummariesMap
typedef FormattersContainer<TypeSummaryImpl> lldb_private::FormatManager::NamedSummariesMap private
Definition at line 37 of file FormatManager.h.
Constructor & Destructor Documentation
FormatManager()
FormatManager::FormatManager ()
Definition at line 704 of file FormatManager.cpp.
References lldb::eLanguageTypeObjC_plus_plus, EnableCategory(), lldb_private::TypeCategoryMap::Last, LoadSystemFormatters(), LoadVectorFormatters(), m_categories_map, m_default_category_name, m_format_cache, m_language_categories_map, m_language_categories_mutex, m_last_revision, m_named_summaries_map, m_system_category_name, and m_vectortypes_category_name.
~FormatManager()
lldb_private::FormatManager::~FormatManager () override default
Member Function Documentation
AnyMatches()
bool lldb_private::FormatManager::AnyMatches (const FormattersMatchCandidate & candidate_type, TypeCategoryImpl::FormatCategoryItems items = TypeCategoryImpl::ALL_ITEM_TYPES, bool only_enabled = true, const char ** matching_category = nullptr, TypeCategoryImpl::FormatCategoryItems * matching_type = nullptr) inline
Definition at line 131 of file FormatManager.h.
References lldb_private::TypeCategoryImpl::ALL_ITEM_TYPES, and m_categories_map.
Referenced by lldb_private::DataVisualization::AnyMatches().
Changed()
void FormatManager::Changed () override virtual
Implements lldb_private::IFormatChangeListener.
Definition at line 116 of file FormatManager.cpp.
References m_format_cache, m_language_categories_map, m_language_categories_mutex, and m_last_revision.
Referenced by lldb_private::DataVisualization::ForceUpdate().
ClearCategories()
void lldb_private::FormatManager::ClearCategories () inline
Definition at line 89 of file FormatManager.h.
References m_categories_map.
Referenced by lldb_private::DataVisualization::Categories::Clear().
DeleteCategory()
bool lldb_private::FormatManager::DeleteCategory (ConstString category_name) inline
Definition at line 85 of file FormatManager.h.
References m_categories_map.
Referenced by lldb_private::DataVisualization::Categories::Delete().
DisableAllCategories()
void FormatManager::DisableAllCategories ()
Definition at line 166 of file FormatManager.cpp.
References m_categories_map, m_language_categories_map, and m_language_categories_mutex.
Referenced by lldb_private::DataVisualization::Categories::DisableStar().
DisableCategory() [1/2]
void lldb_private::FormatManager::DisableCategory (const lldb::TypeCategoryImplSP & category) inline
Definition at line 77 of file FormatManager.h.
References m_categories_map.
DisableCategory() [2/2]
void lldb_private::FormatManager::DisableCategory (ConstString category_name) inline
Definition at line 67 of file FormatManager.h.
References m_categories_map.
Referenced by lldb_private::DataVisualization::Categories::Delete(), lldb_private::DataVisualization::Categories::Disable(), lldb_private::DataVisualization::Categories::Disable(), lldb_private::DataVisualization::Categories::Enable(), and lldb_private::DataVisualization::Categories::Enable().
EnableAllCategories()
void FormatManager::EnableAllCategories ()
Definition at line 157 of file FormatManager.cpp.
References m_categories_map, m_language_categories_map, and m_language_categories_mutex.
Referenced by lldb_private::DataVisualization::Categories::EnableStar().
EnableCategory() [1/3]
void lldb_private::FormatManager::EnableCategory (const lldb::TypeCategoryImplSP & category, TypeCategoryMap::Position pos = TypeCategoryMap::Default) inline
Definition at line 72 of file FormatManager.h.
References lldb_private::TypeCategoryMap::Default, and m_categories_map.
EnableCategory() [2/3]
void lldb_private::FormatManager::EnableCategory (ConstString category_name, TypeCategoryMap::Position pos, lldb::LanguageType lang) inline
Definition at line 58 of file FormatManager.h.
References m_categories_map.
EnableCategory() [3/3]
void lldb_private::FormatManager::EnableCategory (ConstString category_name, TypeCategoryMap::Position pos = TypeCategoryMap::Default) inline
Definition at line 53 of file FormatManager.h.
References lldb_private::TypeCategoryMap::Default, and EnableCategory().
Referenced by lldb_private::DataVisualization::Categories::Enable(), lldb_private::DataVisualization::Categories::Enable(), EnableCategory(), and FormatManager().
ForEachCategory()
void FormatManager::ForEachCategory (TypeCategoryMap::ForEachCallback callback)
Definition at line 404 of file FormatManager.cpp.
References m_categories_map, m_language_categories_map, and m_language_categories_mutex.
Referenced by lldb_private::DataVisualization::Categories::ForEach().
Get()
template<typename ImplSP> ImplSP FormatManager::Get (ValueObject & valobj, lldb::DynamicValueType use_dynamic) private
Definition at line 629 of file FormatManager.cpp.
References lldb_private::DataFormatters, FORMAT_LOG, FormattersMatchData, GetCached(), lldb_private::FormattersMatchData::GetCandidateLanguages(), GetCategoryForLanguage(), GetHardcoded(), lldb_private::GetLog(), and LLDB_LOGF.
GetCached()
template<typename ImplSP> ImplSP FormatManager::GetCached (FormattersMatchData & match_data) private
Definition at line 654 of file FormatManager.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::DataFormatters, FORMAT_LOG, FormattersMatchData, lldb_private::GetLog(), lldb_private::FormattersMatchData::GetTypeForCache(), LLDB_LOGF, LLDB_LOGV, m_categories_map, and m_format_cache.
Referenced by Get().
GetCandidateLanguages()
std::vector< lldb::LanguageType > FormatManager::GetCandidateLanguages (lldb::LanguageType lang_type) static
Definition at line 577 of file FormatManager.cpp.
References lldb::eLanguageTypeC, lldb::eLanguageTypeC11, lldb::eLanguageTypeC89, lldb::eLanguageTypeC99, lldb::eLanguageTypeC_plus_plus, lldb::eLanguageTypeC_plus_plus_03, lldb::eLanguageTypeC_plus_plus_11, lldb::eLanguageTypeC_plus_plus_14, and lldb::eLanguageTypeObjC.
Referenced by GetPossibleMatches().
GetCategories()
TypeCategoryMap & lldb_private::FormatManager::GetCategories () inline private
Definition at line 202 of file FormatManager.h.
References m_categories_map.
GetCategoriesCount()
uint32_t lldb_private::FormatManager::GetCategoriesCount () inline
Definition at line 91 of file FormatManager.h.
References m_categories_map.
Referenced by lldb_private::DataVisualization::Categories::GetCount().
GetCategory() [1/2]
lldb::TypeCategoryImplSP lldb_private::FormatManager::GetCategory (const char * category_name = nullptr, bool can_create = true) inline
Definition at line 99 of file FormatManager.h.
References GetCategory(), and m_default_category_name.
Referenced by lldb_private::DataVisualization::Categories::Add(), lldb_private::DataVisualization::Categories::Clear(), lldb_private::DataVisualization::Categories::GetCategory(), GetCategory(), GetCategory(), lldb_private::CPlusPlusLanguage::GetHardcodedSummaries(), lldb_private::CPlusPlusLanguage::GetHardcodedSynthetics(), LoadSystemFormatters(), and LoadVectorFormatters().
GetCategory() [2/2]
lldb::TypeCategoryImplSP FormatManager::GetCategory (ConstString category_name, bool can_create = true)
Definition at line 416 of file FormatManager.cpp.
References GetCategory(), m_categories_map, and m_default_category_name.
GetCategoryAtIndex()
lldb::TypeCategoryImplSP lldb_private::FormatManager::GetCategoryAtIndex (size_t index) inline
Definition at line 93 of file FormatManager.h.
References m_categories_map.
Referenced by lldb_private::DataVisualization::Categories::GetCategoryAtIndex(), GetFilterForType(), GetFormatForType(), GetSummaryForType(), and GetSyntheticForType().
GetCategoryForLanguage()
LanguageCategory * FormatManager::GetCategoryForLanguage (lldb::LanguageType lang_type)
Definition at line 595 of file FormatManager.cpp.
References m_language_categories_map, and m_language_categories_mutex.
Referenced by Get(), and GetHardcoded().
GetCurrentRevision()
uint32_t lldb_private::FormatManager::GetCurrentRevision () inline override virtual
Implements lldb_private::IFormatChangeListener.
Definition at line 160 of file FormatManager.h.
References m_last_revision.
Referenced by lldb_private::DataVisualization::GetCurrentRevision().
GetFilterForType()
lldb::TypeFilterImplSP FormatManager::GetFilterForType (lldb::TypeNameSpecifierImplSP type_sp)
Definition at line 356 of file FormatManager.cpp.
References GetCategoryAtIndex(), m_categories_map, and UINT32_MAX.
Referenced by lldb_private::DataVisualization::GetFilterForType().
GetFormat()
lldb::TypeFormatImplSP FormatManager::GetFormat (ValueObject & valobj, lldb::DynamicValueType use_dynamic)
Definition at line 687 of file FormatManager.cpp.
References lldb_private::LanguageCategory::Get< lldb::TypeFormatImplSP >().
Referenced by lldb_private::DataVisualization::GetFormat().
GetFormatAsCString()
const char * FormatManager::GetFormatAsCString (lldb::Format format) static
Definition at line 151 of file FormatManager.cpp.
References lldb::eFormatDefault, g_format_infos, and lldb::kNumFormats.
Referenced by lldb_private::DynamicRegisterInfo::Dump(), lldb_private::FormatEntity::Entry::Dump(), lldb_private::FormatEntity::Formatter::DumpValue(), lldb_private::OptionValueFormat::DumpValue(), lldb_private::FormatHelpTextCallback(), lldb_private::TypeFormatImpl_Format::GetDescription(), lldb_private::OptionArgParser::ToFormat(), and lldb_private::OptionValueFormat::ToJSON().
GetFormatAsFormatChar()
char FormatManager::GetFormatAsFormatChar (lldb::Format format) static
Definition at line 143 of file FormatManager.cpp.
References g_format_infos, and g_num_format_infos.
Referenced by lldb_private::FormatEntity::Formatter::DumpValue(), lldb_private::FormatHelpTextCallback(), and lldb_private::OptionArgParser::ToFormat().
GetFormatForType()
lldb::TypeFormatImplSP FormatManager::GetFormatForType (lldb::TypeNameSpecifierImplSP type_sp)
Definition at line 308 of file FormatManager.cpp.
References GetCategoryAtIndex(), m_categories_map, and UINT32_MAX.
Referenced by lldb_private::DataVisualization::GetFormatForType().
GetFormatFromCString()
bool FormatManager::GetFormatFromCString (const char * format_cstr, lldb::Format & format) static
Definition at line 126 of file FormatManager.cpp.
References lldb::eFormatInvalid, GetFormatFromFormatChar(), and GetFormatFromFormatName().
Referenced by ParseInternal(), and lldb_private::OptionArgParser::ToFormat().
GetHardcoded()
template<typename ImplSP> ImplSP FormatManager::GetHardcoded (FormattersMatchData & match_data) private
Definition at line 608 of file FormatManager.cpp.
References FormattersMatchData, lldb_private::FormattersMatchData::GetCandidateLanguages(), and GetCategoryForLanguage().
Referenced by Get().
GetNamedSummaryContainer()
NamedSummariesMap & lldb_private::FormatManager::GetNamedSummaryContainer () inline
Definition at line 48 of file FormatManager.h.
References m_named_summaries_map.
Referenced by lldb_private::DataVisualization::NamedSummaryFormats::Add(), lldb_private::DataVisualization::NamedSummaryFormats::Clear(), lldb_private::DataVisualization::NamedSummaryFormats::Delete(), lldb_private::DataVisualization::NamedSummaryFormats::ForEach(), lldb_private::DataVisualization::NamedSummaryFormats::GetCount(), and lldb_private::DataVisualization::NamedSummaryFormats::GetSummaryFormat().
GetPossibleMatches() [1/2]
void FormatManager::GetPossibleMatches (ValueObject & valobj, CompilerType compiler_type, lldb::DynamicValueType use_dynamic, FormattersMatchVector & entries, FormattersMatchCandidate::Flags current_flags, bool root_level = false, uint32_t ptr_stripped_depth = 0) static private
Definition at line 175 of file FormatManager.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::Language::FindPlugin(), lldb_private::CompilerType::GetArrayElementType(), lldb_private::CompilerType::GetArrayType(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::ValueObject::GetBitfieldBitSize(), GetCandidateLanguages(), lldb_private::ValueObject::GetExecutionContextRef(), lldb_private::CompilerType::GetFullyUnqualifiedType(), lldb_private::CompilerType::GetLValueReferenceType(), lldb_private::CompilerType::GetNonReferenceType(), lldb_private::ValueObject::GetObjectRuntimeLanguage(), lldb_private::CompilerType::GetOpaqueQualType(), lldb_private::CompilerType::GetPointeeType(), lldb_private::CompilerType::GetPointerType(), GetPossibleMatches(), lldb_private::CompilerType::GetRValueReferenceType(), lldb_private::ValueObject::GetStaticValue(), lldb_private::StreamString::GetString(), lldb_private::ValueObject::GetTargetSP(), lldb_private::CompilerType::GetTypedefedType(), lldb_private::CompilerType::GetTypeForFormatters(), lldb_private::CompilerType::GetTypeName(), lldb_private::CompilerType::IsArrayType(), lldb_private::ValueObject::IsDynamic(), lldb_private::CompilerType::IsMeaninglessWithoutDynamicResolution(), lldb_private::CompilerType::IsPointerType(), lldb_private::CompilerType::IsReferenceType(), lldb_private::CompilerType::IsTypedefType(), lldb_private::CompilerType::IsValid(), lldb_private::Stream::Printf(), lldb_private::FormattersMatchCandidate::Flags::WithStrippedPointer(), lldb_private::FormattersMatchCandidate::Flags::WithStrippedReference(), and lldb_private::FormattersMatchCandidate::Flags::WithStrippedTypedef().
GetPossibleMatches() [2/2]
FormattersMatchVector lldb_private::FormatManager::GetPossibleMatches (ValueObject & valobj, lldb::DynamicValueType use_dynamic) inline static
Definition at line 163 of file FormatManager.h.
References lldb_private::ValueObject::GetCompilerType(), and GetPossibleMatches().
Referenced by lldb_private::FormattersMatchData::GetMatchesVector(), GetPossibleMatches(), and GetPossibleMatches().
GetSingleItemFormat()
lldb::Format FormatManager::GetSingleItemFormat (lldb::Format vector_format) static
Definition at line 431 of file FormatManager.cpp.
References lldb::eFormatCharArray, lldb::eFormatDecimal, lldb::eFormatFloat, lldb::eFormatHex, lldb::eFormatInvalid, lldb::eFormatVectorOfChar, lldb::eFormatVectorOfFloat16, lldb::eFormatVectorOfFloat32, lldb::eFormatVectorOfFloat64, lldb::eFormatVectorOfSInt16, lldb::eFormatVectorOfSInt32, lldb::eFormatVectorOfSInt64, lldb::eFormatVectorOfSInt8, lldb::eFormatVectorOfUInt128, lldb::eFormatVectorOfUInt16, lldb::eFormatVectorOfUInt32, lldb::eFormatVectorOfUInt64, and lldb::eFormatVectorOfUInt8.
Referenced by lldb_private::ValueObject::DumpPrintableRepresentation().
GetSummaryFormat()
lldb::TypeSummaryImplSP FormatManager::GetSummaryFormat (ValueObject & valobj, lldb::DynamicValueType use_dynamic)
Definition at line 693 of file FormatManager.cpp.
References lldb_private::LanguageCategory::Get< lldb::TypeSummaryImplSP >().
Referenced by lldb_private::DataVisualization::GetSummaryFormat().
GetSummaryForType()
lldb::TypeSummaryImplSP FormatManager::GetSummaryForType (lldb::TypeNameSpecifierImplSP type_sp)
Definition at line 332 of file FormatManager.cpp.
References GetCategoryAtIndex(), m_categories_map, and UINT32_MAX.
Referenced by lldb_private::DataVisualization::GetSummaryForType().
GetSyntheticChildren()
lldb::SyntheticChildrenSP FormatManager::GetSyntheticChildren (ValueObject & valobj, lldb::DynamicValueType use_dynamic)
Definition at line 699 of file FormatManager.cpp.
References lldb_private::LanguageCategory::Get< lldb::SyntheticChildrenSP >().
Referenced by lldb_private::DataVisualization::GetSyntheticChildren().
GetSyntheticForType()
lldb::ScriptedSyntheticChildrenSP FormatManager::GetSyntheticForType (lldb::TypeNameSpecifierImplSP type_sp)
Definition at line 380 of file FormatManager.cpp.
References GetCategoryAtIndex(), m_categories_map, and UINT32_MAX.
Referenced by lldb_private::DataVisualization::GetSyntheticForType().
GetTypeForCache()
ConstString FormatManager::GetTypeForCache (ValueObject & valobj, lldb::DynamicValueType use_dynamic) static
Definition at line 565 of file FormatManager.cpp.
References lldb_private::ValueObject::GetQualifiedRepresentationIfAvailable(), and lldb_private::ValueObject::IsSynthetic().
LoadSystemFormatters()
void FormatManager::LoadSystemFormatters () private
Definition at line 719 of file FormatManager.cpp.
References lldb_private::formatters::AddFormat(), lldb::eFormatOSType, lldb::eFormatterMatchExact, lldb::eFormatterMatchRegex, GetCategory(), m_system_category_name, lldb_private::TypeFormatImpl::Flags::SetCascades(), lldb_private::TypeSummaryImpl::Flags::SetCascades(), lldb_private::TypeSummaryImpl::Flags::SetDontShowChildren(), lldb_private::TypeSummaryImpl::Flags::SetDontShowValue(), lldb_private::TypeSummaryImpl::Flags::SetHideItemNames(), lldb_private::TypeSummaryImpl::Flags::SetShowMembersOneLiner(), lldb_private::TypeFormatImpl::Flags::SetSkipPointers(), lldb_private::TypeSummaryImpl::Flags::SetSkipPointers(), lldb_private::TypeFormatImpl::Flags::SetSkipReferences(), and lldb_private::TypeSummaryImpl::Flags::SetSkipReferences().
Referenced by FormatManager().
LoadVectorFormatters()
void FormatManager::LoadVectorFormatters () private
Definition at line 775 of file FormatManager.cpp.
References lldb_private::formatters::AddStringSummary(), GetCategory(), m_vectortypes_category_name, lldb_private::TypeSummaryImpl::Flags::SetCascades(), lldb_private::TypeSummaryImpl::Flags::SetDontShowChildren(), lldb_private::TypeSummaryImpl::Flags::SetDontShowValue(), lldb_private::TypeSummaryImpl::Flags::SetHideItemNames(), lldb_private::TypeSummaryImpl::Flags::SetShowMembersOneLiner(), lldb_private::TypeSummaryImpl::Flags::SetSkipPointers(), and lldb_private::TypeSummaryImpl::Flags::SetSkipReferences().
Referenced by FormatManager().
ShouldPrintAsOneLiner()
bool FormatManager::ShouldPrintAsOneLiner (ValueObject & valobj)
Definition at line 459 of file FormatManager.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb_private::ValueObject::GetChildAtIndex(), lldb_private::ValueObject::GetCompilerType(), lldb_private::Target::GetGlobalProperties(), lldb_private::ValueObject::GetNumChildren(), lldb_private::ValueObject::GetSummaryFormat(), lldb_private::ValueObject::GetTargetSP(), lldb_private::CompilerType::IsValid(), and lldb_private::CompilerType::ShouldPrintAsOneLiner().
Referenced by lldb_private::DataVisualization::ShouldPrintAsOneLiner().
Friends And Related Symbol Documentation
FormattersMatchData
friend class FormattersMatchData friend
Definition at line 214 of file FormatManager.h.
References FormattersMatchData.
Referenced by FormattersMatchData, Get(), GetCached(), and GetHardcoded().
Member Data Documentation
m_categories_map
TypeCategoryMap lldb_private::FormatManager::m_categories_map private
Definition at line 191 of file FormatManager.h.
Referenced by AnyMatches(), ClearCategories(), DeleteCategory(), DisableAllCategories(), DisableCategory(), DisableCategory(), EnableAllCategories(), EnableCategory(), EnableCategory(), ForEachCategory(), FormatManager(), GetCached(), GetCategories(), GetCategoriesCount(), GetCategory(), GetCategoryAtIndex(), GetFilterForType(), GetFormatForType(), GetSummaryForType(), and GetSyntheticForType().
m_default_category_name
ConstString lldb_private::FormatManager::m_default_category_name private
Definition at line 193 of file FormatManager.h.
Referenced by FormatManager(), GetCategory(), and GetCategory().
m_format_cache
FormatCache lldb_private::FormatManager::m_format_cache private
Definition at line 187 of file FormatManager.h.
Referenced by Changed(), FormatManager(), and GetCached().
m_language_categories_map
LanguageCategories lldb_private::FormatManager::m_language_categories_map private
Definition at line 189 of file FormatManager.h.
Referenced by Changed(), DisableAllCategories(), EnableAllCategories(), ForEachCategory(), FormatManager(), and GetCategoryForLanguage().
m_language_categories_mutex
std::recursive_mutex lldb_private::FormatManager::m_language_categories_mutex private
Definition at line 188 of file FormatManager.h.
Referenced by Changed(), DisableAllCategories(), EnableAllCategories(), ForEachCategory(), FormatManager(), and GetCategoryForLanguage().
m_last_revision
std::atomic<uint32_t> lldb_private::FormatManager::m_last_revision private
Definition at line 186 of file FormatManager.h.
Referenced by Changed(), FormatManager(), and GetCurrentRevision().
m_named_summaries_map
NamedSummariesMap lldb_private::FormatManager::m_named_summaries_map private
Definition at line 190 of file FormatManager.h.
Referenced by FormatManager(), and GetNamedSummaryContainer().
m_system_category_name
ConstString lldb_private::FormatManager::m_system_category_name private
Definition at line 194 of file FormatManager.h.
Referenced by FormatManager(), and LoadSystemFormatters().
m_vectortypes_category_name
ConstString lldb_private::FormatManager::m_vectortypes_category_name private
Definition at line 195 of file FormatManager.h.
Referenced by FormatManager(), and LoadVectorFormatters().
The documentation for this class was generated from the following files:
FormatManager.h
FormatManager.cpp