LLDB: lldb_private::StructuredData::Array Class Reference
lldb_private::StructuredData::Array Class Reference
#include <StructuredData.h>
Public Member Functions
Array ()
~Array () override=default
bool ForEach (std::function< bool(Object *object)> const &foreach_callback) const
size_t GetSize () const
ObjectSP operator[] (size_t idx)
ObjectSP GetItemAtIndex (size_t idx) const
template<class IntType>
std::optional< IntType > GetItemAtIndexAsInteger (size_t idx) const
std::optional< llvm::StringRef > GetItemAtIndexAsString (size_t idx) const
std::optional< Dictionary * > GetItemAtIndexAsDictionary (size_t idx) const
Retrieves the element at index idx from a StructuredData::Array if it is a Dictionary.
void Push (const ObjectSP &item)
void AddItem (const ObjectSP &item)
template<typename T>
void AddIntegerItem (T value)
void AddFloatItem (double value)
void AddStringItem (llvm::StringRef value)
void AddBooleanItem (bool value)
void Serialize (llvm::json::OStream &s) const override
void GetDescription (lldb_private::Stream &s) const override
Public Member Functions inherited from lldb_private::StructuredData::Object
Object (lldb::StructuredDataType t=lldb::eStructuredDataTypeInvalid)
virtual ~Object ()=default
virtual bool IsValid () const
virtual void Clear ()
lldb::StructuredDataType GetType () const
void SetType (lldb::StructuredDataType t)
Array * GetAsArray ()
Dictionary * GetAsDictionary ()
UnsignedInteger * GetAsUnsignedInteger ()
SignedInteger * GetAsSignedInteger ()
uint64_t GetUnsignedIntegerValue (uint64_t fail_value=0)
int64_t GetSignedIntegerValue (int64_t fail_value=0)
Float * GetAsFloat ()
double GetFloatValue (double fail_value=0.0)
Boolean * GetAsBoolean ()
bool GetBooleanValue (bool fail_value=false)
String * GetAsString ()
llvm::StringRef GetStringValue (const char *fail_value=nullptr)
Generic * GetAsGeneric ()
ObjectSP GetObjectForDotSeparatedPath (llvm::StringRef path)
void DumpToStdout (bool pretty_print=true) const
void Dump (lldb_private::Stream &s, bool pretty_print=true) const
Protected Types
typedef std::vector< ObjectSP > collection
Protected Attributes
collection m_items
Detailed Description
Definition at line 193 of file StructuredData.h.
Member Typedef Documentation
collection
typedef std::vector<ObjectSP> lldb_private::StructuredData::Array::collection protected
Definition at line 294 of file StructuredData.h.
Constructor & Destructor Documentation
Array()
lldb_private::StructuredData::Array::Array () inline
Definition at line 195 of file StructuredData.h.
References lldb_private::StructuredData::Object::Object().
~Array()
lldb_private::StructuredData::Array::~Array () override default
Member Function Documentation
AddBooleanItem()
void lldb_private::StructuredData::Array::AddBooleanItem (bool value) inline
Definition at line 285 of file StructuredData.h.
References AddItem().
AddFloatItem()
void lldb_private::StructuredData::Array::AddFloatItem (double value) inline
Definition at line 279 of file StructuredData.h.
References AddItem().
AddIntegerItem()
template<typename T> void lldb_private::StructuredData::Array::AddIntegerItem (T value) inline
Definition at line 269 of file StructuredData.h.
References AddItem().
Referenced by lldb_private::InstrumentationRuntimeMainThreadChecker::RetrieveReportData(), and lldb_private::InstrumentationRuntimeUBSan::RetrieveReportData().
AddItem()
void lldb_private::StructuredData::Array::AddItem (const ObjectSP & item) inline
Definition at line 267 of file StructuredData.h.
References m_items.
Referenced by AddBooleanItem(), AddFloatItem(), AddIntegerItem(), AddStringItem(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetSeparateDebugInfo(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetSeparateDebugInfo(), GetSeparateDebugInfoList(), and lldb_private::Target::SerializeBreakpointsToFile().
AddStringItem()
void lldb_private::StructuredData::Array::AddStringItem (llvm::StringRef value) inline
Definition at line 281 of file StructuredData.h.
References AddItem().
ForEach()
bool lldb_private::StructuredData::Array::ForEach (std::function< bool(Object *object)> const & foreach_callback) const inline
Definition at line 200 of file StructuredData.h.
References m_items, and lldb_private::StructuredData::Object::Object().
Referenced by lldb_private::ScriptedThread::CalculateStopInfo(), CommandObjectScriptingObjectParsed::CommandObjectScriptingObjectParsed(), CommandObjectTargetModulesDumpSeparateDebugInfoFiles::DoExecute(), dump(), DumpDwoFilesTable(), DumpOsoFilesTable(), lldb_private::StructuredDataDarwinLog::GetDescription(), SystemRuntimeMacOSX::GetExtendedBacktraceThread(), lldb::SBStructuredData::GetKeys(), lldb_private::Process::MapSupportedStructuredDataPlugins(), CommandObjectScriptingObjectParsed::CommandOptions::ParseUsageMaskFromArray(), lldb_private::RegisterContextUnifiedCore::RegisterContextUnifiedCore(), CommandObjectScriptingObjectParsed::CommandOptions::SetOptionsFromArray(), lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo(), and lldb_private::process_gdb_remote::ProcessGDBRemote::UpdateThreadIDList().
GetDescription()
void StructuredData::Array::GetDescription (lldb_private::Stream & s) const override virtual
Reimplemented from lldb_private::StructuredData::Object.
Definition at line 203 of file StructuredData.cpp.
References lldb_private::Stream::EOL(), lldb_private::Stream::GetIndentLevel(), lldb_private::Stream::Indent(), lldb_private::Stream::IndentLess(), lldb_private::Stream::IndentMore(), lldb_private::StructuredData::IsRecordType(), m_items, lldb_private::Stream::Printf(), lldb_private::Stream::PutChar(), and lldb_private::Stream::SetIndentLevel().
GetItemAtIndex()
ObjectSP lldb_private::StructuredData::Array::GetItemAtIndex (size_t idx) const inline
Definition at line 216 of file StructuredData.h.
References GetSize(), and m_items.
Referenced by lldb_private::Target::CreateBreakpointsFromFile(), ThreadMachCore::CreateRegisterContextForFrame(), lldb_private::PlatformDarwin::ExtractAppSpecificInfo(), lldb_private::Thread::GetDescription(), GetItemAtIndexAsDictionary(), GetItemAtIndexAsInteger(), GetItemAtIndexAsString(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetModulesInfo(), lldb_private::StructuredData::Object::GetObjectForDotSeparatedPath(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetThreadStopInfoFromJSON(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_jModulesInfo(), CommandObjectBreakpointRead::CommandOptions::HandleOptionArgumentCompletion(), lldb_private::DynamicLoaderDarwin::JSONImageInformationIntoImageInfo(), CommandObjectScriptingObjectParsed::CommandOptions::ParseUsageMaskFromArray(), CommandObjectScriptingObjectParsed::CommandOptions::SetOptionsFromArray(), and lldb_private::process_gdb_remote::ProcessGDBRemote::WillPublicStop().
GetItemAtIndexAsDictionary()
std::optional< Dictionary * > lldb_private::StructuredData::Array::GetItemAtIndexAsDictionary (size_t idx) const inline
Retrieves the element at index idx from a StructuredData::Array if it is a Dictionary.
Parameters
[in] idx The index of the element to retrieve.
Returns
If the element at index idx is a Dictionary, this method returns a valid pointer to the Dictionary wrapped in a std::optional. If the element is not a Dictionary or the index is invalid, this returns std::nullopt. Note that the underlying Dictionary pointer is never nullptr.
Definition at line 257 of file StructuredData.h.
References GetItemAtIndex().
Referenced by ObjectFileMachO::GetCorefileThreadExtraInfos(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::QueryGDBServer(), and lldb_private::DynamicRegisterInfo::SetRegisterInfo().
GetItemAtIndexAsInteger()
template<class IntType> std::optional< IntType > lldb_private::StructuredData::Array::GetItemAtIndexAsInteger (size_t idx) const inline
Definition at line 224 of file StructuredData.h.
References GetItemAtIndex().
Referenced by lldb_private::BreakpointResolverName::CreateFromStructuredData(), lldb_private::InstrumentationRuntimeTSan::GetFirstNonInternalFramePc(), and lldb_private::DynamicRegisterInfo::SetRegisterInfo().
GetItemAtIndexAsString()
std::optional< llvm::StringRef > lldb_private::StructuredData::Array::GetItemAtIndexAsString (size_t idx) const inline
Definition at line 237 of file StructuredData.h.
References GetItemAtIndex().
Referenced by lldb_private::DynamicRegisterInfo::ByteOffsetFromComposite(), lldb_private::Breakpoint::CreateFromStructuredData(), lldb_private::BreakpointResolverFileRegex::CreateFromStructuredData(), lldb_private::BreakpointResolverName::CreateFromStructuredData(), lldb_private::SearchFilterByModule::CreateFromStructuredData(), lldb_private::SearchFilterByModuleList::CreateFromStructuredData(), lldb_private::SearchFilterByModuleListAndCU::CreateFromStructuredData(), CommandObjectBreakpointRead::CommandOptions::HandleOptionArgumentCompletion(), CommandObjectScriptingObjectParsed::CommandOptions::ProcessCompletionDict(), lldb_private::Breakpoint::SerializedBreakpointMatchesNames(), and lldb_private::DynamicRegisterInfo::SetRegisterInfo().
GetSize()
size_t lldb_private::StructuredData::Array::GetSize () const inline
Definition at line 208 of file StructuredData.h.
References m_items.
Referenced by lldb_private::DynamicRegisterInfo::ByteOffsetFromComposite(), lldb_private::Target::CreateBreakpointsFromFile(), lldb_private::Breakpoint::CreateFromStructuredData(), lldb_private::BreakpointResolverFileRegex::CreateFromStructuredData(), lldb_private::BreakpointResolverName::CreateFromStructuredData(), lldb_private::SearchFilterByModule::CreateFromStructuredData(), lldb_private::SearchFilterByModuleList::CreateFromStructuredData(), lldb_private::SearchFilterByModuleListAndCU::CreateFromStructuredData(), ThreadMachCore::CreateRegisterContextForFrame(), lldb_private::PlatformDarwin::ExtractAppSpecificInfo(), ObjectFileMachO::GetCorefileThreadExtraInfos(), lldb_private::Thread::GetDescription(), SystemRuntimeMacOSX::GetExtendedBacktraceThread(), lldb_private::InstrumentationRuntimeTSan::GetFirstNonInternalFramePc(), GetItemAtIndex(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetModulesInfo(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetThreadStopInfoFromJSON(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_jModulesInfo(), CommandObjectBreakpointRead::CommandOptions::HandleOptionArgumentCompletion(), lldb_private::DynamicLoaderDarwin::JSONImageInformationIntoImageInfo(), lldb_private::Process::MapSupportedStructuredDataPlugins(), CommandObjectScriptingObjectParsed::CommandOptions::ParseUsageMaskFromArray(), CommandObjectScriptingObjectParsed::CommandOptions::ProcessCompletionDict(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::QueryGDBServer(), lldb_private::Breakpoint::SerializedBreakpointMatchesNames(), CommandObjectScriptingObjectParsed::CommandOptions::SetOptionsFromArray(), lldb_private::DynamicRegisterInfo::SetRegisterInfo(), lldb_private::process_gdb_remote::ProcessGDBRemote::UpdateThreadIDList(), and lldb_private::process_gdb_remote::ProcessGDBRemote::WillPublicStop().
operator[]()
ObjectSP lldb_private::StructuredData::Array::operator[] (size_t idx) inline
Definition at line 210 of file StructuredData.h.
References m_items.
Push()
void lldb_private::StructuredData::Array::Push (const ObjectSP & item) inline
Definition at line 265 of file StructuredData.h.
References m_items.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_jSignalsInfo().
Serialize()
void StructuredData::Array::Serialize (llvm::json::OStream & s) const override virtual
Implements lldb_private::StructuredData::Object.
Definition at line 143 of file StructuredData.cpp.
References m_items.
Member Data Documentation
m_items
collection lldb_private::StructuredData::Array::m_items protected
Definition at line 295 of file StructuredData.h.
Referenced by AddItem(), ForEach(), GetDescription(), GetItemAtIndex(), GetSize(), operator[](), Push(), and Serialize().
The documentation for this class was generated from the following files:
StructuredData.h
StructuredData.cpp