LLDB: BreakpointAccessOptionGroup Class Reference
BreakpointAccessOptionGroup Class Reference
Public Member Functions
BreakpointAccessOptionGroup ()=default
~BreakpointAccessOptionGroup () override=default
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext *execution_context) override
void OptionParsingStarting (ExecutionContext *execution_context) override
const BreakpointName::Permissions & GetPermissions () const
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Public Attributes
BreakpointName::Permissions m_permissions
Detailed Description
Definition at line 2818 of file CommandObjectBreakpoint.cpp.
Constructor & Destructor Documentation
BreakpointAccessOptionGroup()
BreakpointAccessOptionGroup::BreakpointAccessOptionGroup () default
~BreakpointAccessOptionGroup()
BreakpointAccessOptionGroup::~BreakpointAccessOptionGroup () override default
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > BreakpointAccessOptionGroup::GetDefinitions () inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 2824 of file CommandObjectBreakpoint.cpp.
GetPermissions()
const BreakpointName::Permissions & BreakpointAccessOptionGroup::GetPermissions () const inline
Definition at line 2875 of file CommandObjectBreakpoint.cpp.
References m_permissions.
OptionParsingStarting()
void BreakpointAccessOptionGroup::OptionParsingStarting (ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 2873 of file CommandObjectBreakpoint.cpp.
SetOptionValue()
Status BreakpointAccessOptionGroup::SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 2827 of file CommandObjectBreakpoint.cpp.
References lldb_private::CreateOptionParsingError(), error(), lldb_private::Status::FromError(), lldb_private::g_bool_parsing_error_message, m_permissions, and lldb_private::OptionArgParser::ToBoolean().
Member Data Documentation
m_permissions
BreakpointName::Permissions BreakpointAccessOptionGroup::m_permissions
Definition at line 2878 of file CommandObjectBreakpoint.cpp.
Referenced by GetPermissions(), and SetOptionValue().
The documentation for this class was generated from the following file:
CommandObjectBreakpoint.cpp