LLDB: lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd Class Reference
lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd Class Reference
Public Member Functions
MsvcStlVectorBoolSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Attributes
CompilerType m_bool_type
ExecutionContextRef m_exe_ctx_ref
uint64_t m_count = 0
uint64_t m_element_bit_size = 0
lldb::addr_t m_base_data_address = 0
std::map< size_t, lldb::ValueObjectSP > m_children
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
Definition at line 38 of file MsvcStlVector.cpp.
Constructor & Destructor Documentation
MsvcStlVectorBoolSyntheticFrontEnd()
lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd::MsvcStlVectorBoolSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
Definition at line 151 of file MsvcStlVector.cpp.
References lldb::eBasicTypeBool, m_bool_type, m_children, m_exe_ctx_ref, lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd(), and Update().
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd::CalculateNumChildren () override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 162 of file MsvcStlVector.cpp.
References m_count.
GetChildAtIndex()
lldb::ValueObjectSP lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd::GetChildAtIndex (uint32_t idx) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 168 of file MsvcStlVector.cpp.
References lldb_private::SyntheticChildrenFrontEnd::CreateValueObjectFromData(), lldb_private::Status::Fail(), lldb_private::Scalar::GetAPSInt(), lldb_private::StreamString::GetString(), lldb_private::Scalar::IsValid(), m_base_data_address, m_bool_type, m_children, m_count, m_element_bit_size, m_exe_ctx_ref, and lldb_private::Stream::Printf().
GetIndexOfChildWithName()
llvm::Expected< size_t > lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd::GetIndexOfChildWithName (ConstString name) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 267 of file MsvcStlVector.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::SyntheticChildrenFrontEnd::CalculateNumChildrenIgnoringErrors(), lldb_private::formatters::ExtractIndexFromString(), m_base_data_address, and m_count.
Update()
lldb::ChildCacheState lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd::Update () override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 223 of file MsvcStlVector.cpp.
References lldb::eRefetch, lldb::eReuse, lldb_private::CompilerType::GetBitSize(), lldb_private::CompilerType::IsValid(), lldb_private::SyntheticChildrenFrontEnd::m_backend, m_base_data_address, m_children, m_count, m_element_bit_size, and m_exe_ctx_ref.
Referenced by MsvcStlVectorBoolSyntheticFrontEnd().
Member Data Documentation
m_base_data_address
lldb::addr_t lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd::m_base_data_address = 0 private
Definition at line 55 of file MsvcStlVector.cpp.
Referenced by GetChildAtIndex(), GetIndexOfChildWithName(), and Update().
m_bool_type
CompilerType lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd::m_bool_type private
Definition at line 51 of file MsvcStlVector.cpp.
Referenced by GetChildAtIndex(), and MsvcStlVectorBoolSyntheticFrontEnd().
m_children
std::map<size_t, lldb::ValueObjectSP> lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd::m_children private
Definition at line 56 of file MsvcStlVector.cpp.
Referenced by GetChildAtIndex(), MsvcStlVectorBoolSyntheticFrontEnd(), and Update().
m_count
uint64_t lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd::m_count = 0 private
Definition at line 53 of file MsvcStlVector.cpp.
Referenced by CalculateNumChildren(), GetChildAtIndex(), GetIndexOfChildWithName(), and Update().
m_element_bit_size
uint64_t lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd::m_element_bit_size = 0 private
Definition at line 54 of file MsvcStlVector.cpp.
Referenced by GetChildAtIndex(), and Update().
m_exe_ctx_ref
ExecutionContextRef lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd::m_exe_ctx_ref private
Definition at line 52 of file MsvcStlVector.cpp.
Referenced by GetChildAtIndex(), MsvcStlVectorBoolSyntheticFrontEnd(), and Update().
The documentation for this class was generated from the following file:
MsvcStlVector.cpp