LLDB: lldb_private::plugin::dwarf::DWARFUnit::ScopedExtractDIEs Class Reference
lldb_private::plugin::dwarf::DWARFUnit::ScopedExtractDIEs Class Reference
#include <DWARFUnit.h>
Public Member Functions
ScopedExtractDIEs (DWARFUnit &cu)
~ScopedExtractDIEs ()
ScopedExtractDIEs (const ScopedExtractDIEs &)=delete
const ScopedExtractDIEs & operator= (const ScopedExtractDIEs &)=delete
ScopedExtractDIEs (ScopedExtractDIEs &&rhs)
ScopedExtractDIEs & operator= (ScopedExtractDIEs &&rhs)
Public Attributes
bool m_clear_dies = false
Private Attributes
DWARFUnit * m_cu
Detailed Description
Definition at line 67 of file DWARFUnit.h.
Constructor & Destructor Documentation
ScopedExtractDIEs() [1/3]
DWARFUnit::ScopedExtractDIEs::ScopedExtractDIEs (DWARFUnit & cu)
Definition at line 193 of file DWARFUnit.cpp.
References lldb_private::plugin::dwarf::DWARFUnit::DWARFUnit(), and m_cu.
Referenced by operator=(), ScopedExtractDIEs(), and ScopedExtractDIEs().
~ScopedExtractDIEs()
DWARFUnit::ScopedExtractDIEs::~ScopedExtractDIEs ()
Definition at line 198 of file DWARFUnit.cpp.
References m_clear_dies, and m_cu.
ScopedExtractDIEs() [2/3]
lldb_private::plugin::dwarf::DWARFUnit::ScopedExtractDIEs::ScopedExtractDIEs (const ScopedExtractDIEs &) delete
References ScopedExtractDIEs().
ScopedExtractDIEs() [3/3]
DWARFUnit::ScopedExtractDIEs::ScopedExtractDIEs (ScopedExtractDIEs && rhs)
Definition at line 210 of file DWARFUnit.cpp.
References m_clear_dies, m_cu, and ScopedExtractDIEs().
Member Function Documentation
operator=() [1/2]
const ScopedExtractDIEs & lldb_private::plugin::dwarf::DWARFUnit::ScopedExtractDIEs::operator= (const ScopedExtractDIEs &) delete
References ScopedExtractDIEs().
operator=() [2/2]
DWARFUnit::ScopedExtractDIEs & DWARFUnit::ScopedExtractDIEs::operator= (DWARFUnit::ScopedExtractDIEs && rhs)
Definition at line 216 of file DWARFUnit.cpp.
References m_clear_dies, and m_cu.
Member Data Documentation
m_clear_dies
bool lldb_private::plugin::dwarf::DWARFUnit::ScopedExtractDIEs::m_clear_dies = false
Definition at line 71 of file DWARFUnit.h.
Referenced by lldb_private::plugin::dwarf::DWARFUnit::ExtractDIEsScoped(), operator=(), ScopedExtractDIEs(), and ~ScopedExtractDIEs().
m_cu
DWARFUnit* lldb_private::plugin::dwarf::DWARFUnit::ScopedExtractDIEs::m_cu private
Definition at line 68 of file DWARFUnit.h.
Referenced by operator=(), ScopedExtractDIEs(), ScopedExtractDIEs(), and ~ScopedExtractDIEs().
The documentation for this class was generated from the following files:
DWARFUnit.h
DWARFUnit.cpp