LLDB: lldb_private::BytecodeSyntheticChildren Class Reference
lldb_private::BytecodeSyntheticChildren Class Reference
A synthetic formatter that is defined in LLDB formmater bytecode.
#include <TypeSynthetic.h>
Classes
class FrontEnd
struct SyntheticBytecodeImplementation
Public Member Functions
BytecodeSyntheticChildren (SyntheticBytecodeImplementation &&impl)
bool IsScripted () override
std::string GetDescription () override
SyntheticChildrenFrontEnd::UniquePointer GetFrontEnd (ValueObject &backend) override
Public Member Functions inherited from lldb_private::SyntheticChildren
SyntheticChildren (const Flags &flags)
virtual ~SyntheticChildren ()
bool Cascades () const
bool SkipsPointers () const
bool SkipsReferences () const
bool NonCacheable () const
bool WantsDereference () const
void SetCascades (bool value)
void SetSkipsPointers (bool value)
void SetSkipsReferences (bool value)
void SetNonCacheable (bool value)
uint32_t GetOptions ()
void SetOptions (uint32_t value)
uint32_t & GetRevision ()
uint32_t GetPtrMatchDepth ()
void SetPtrMatchDepth (uint32_t value)
Private Attributes
SyntheticBytecodeImplementation m_impl
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildren
typedef std::shared_ptr< SyntheticChildren > SharedPointer
Protected Attributes inherited from lldb_private::SyntheticChildren
uint32_t m_my_revision = 0
Flags m_flags
uint32_t m_ptr_match_depth = 1
Detailed Description
A synthetic formatter that is defined in LLDB formmater bytecode.
See BytecodeSummaryFormat for the corresponding summary formatter.
Formatter bytecode documentation can be found in lldb/docs/resources/formatterbytecode.rst
Definition at line 485 of file TypeSynthetic.h.
Constructor & Destructor Documentation
BytecodeSyntheticChildren()
lldb_private::BytecodeSyntheticChildren::BytecodeSyntheticChildren (SyntheticBytecodeImplementation && impl) inline
Definition at line 511 of file TypeSynthetic.h.
References lldb_private::SyntheticChildren::SyntheticChildren().
Member Function Documentation
GetDescription()
std::string BytecodeSyntheticChildren::GetDescription () override virtual
Implements lldb_private::SyntheticChildren.
Definition at line 394 of file TypeSynthetic.cpp.
References lldb_private::SyntheticChildren::Cascades(), lldb_private::StreamString::GetString(), lldb_private::Stream::Printf(), lldb_private::SyntheticChildren::SkipsPointers(), and lldb_private::SyntheticChildren::SkipsReferences().
GetFrontEnd()
SyntheticChildrenFrontEnd::UniquePointer lldb_private::BytecodeSyntheticChildren::GetFrontEnd (ValueObject & backend) inline override virtual
Implements lldb_private::SyntheticChildren.
Definition at line 519 of file TypeSynthetic.h.
References m_impl.
IsScripted()
bool lldb_private::BytecodeSyntheticChildren::IsScripted () inline override virtual
Implements lldb_private::SyntheticChildren.
Definition at line 514 of file TypeSynthetic.h.
Member Data Documentation
m_impl
SyntheticBytecodeImplementation lldb_private::BytecodeSyntheticChildren::m_impl private
Definition at line 525 of file TypeSynthetic.h.
Referenced by GetFrontEnd().
The documentation for this class was generated from the following files:
TypeSynthetic.h
TypeSynthetic.cpp