LLDB: lldb::SBModuleSpecList Class Reference
lldb::SBModuleSpecList Class Reference
#include <SBModuleSpec.h>
Public Member Functions
SBModuleSpecList ()
SBModuleSpecList (const SBModuleSpecList &rhs)
~SBModuleSpecList ()
SBModuleSpecList & operator= (const SBModuleSpecList &rhs)
void Append (const SBModuleSpec &spec)
void Append (const SBModuleSpecList &spec_list)
SBModuleSpec FindFirstMatchingSpec (const SBModuleSpec &match_spec)
SBModuleSpecList FindMatchingSpecs (const SBModuleSpec &match_spec)
size_t GetSize ()
SBModuleSpec GetSpecAtIndex (size_t i)
bool GetDescription (lldb::SBStream &description)
Static Public Member Functions
static SBModuleSpecList GetModuleSpecifications (const char *path)
Private Attributes
std::unique_ptr< lldb_private::ModuleSpecList > m_opaque_up
Detailed Description
Definition at line 111 of file SBModuleSpec.h.
Constructor & Destructor Documentation
SBModuleSpecList() [1/2]
SBModuleSpecList::SBModuleSpecList ()
Definition at line 190 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by Append(), FindMatchingSpecs(), GetModuleSpecifications(), operator=(), SBModuleSpecList(), and ~SBModuleSpecList().
SBModuleSpecList() [2/2]
SBModuleSpecList::SBModuleSpecList (const SBModuleSpecList & rhs)
Definition at line 194 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and SBModuleSpecList().
~SBModuleSpecList()
SBModuleSpecList::~SBModuleSpecList () default
References SBModuleSpecList().
Member Function Documentation
Append() [1/2]
void SBModuleSpecList::Append (const SBModuleSpec & spec)
Definition at line 220 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, lldb::SBModuleSpec::m_opaque_up, and m_opaque_up.
Append() [2/2]
void SBModuleSpecList::Append (const SBModuleSpecList & spec_list)
Definition at line 226 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and SBModuleSpecList().
FindFirstMatchingSpec()
SBModuleSpec SBModuleSpecList::FindFirstMatchingSpec (const SBModuleSpec & match_spec)
Definition at line 247 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, lldb::SBModuleSpec::m_opaque_up, and m_opaque_up.
FindMatchingSpecs()
SBModuleSpecList SBModuleSpecList::FindMatchingSpecs (const SBModuleSpec & match_spec)
Definition at line 257 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, lldb::SBModuleSpec::m_opaque_up, m_opaque_up, and SBModuleSpecList().
GetDescription()
bool SBModuleSpecList::GetDescription (lldb::SBStream & description)
Definition at line 266 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBStream::ref().
GetModuleSpecifications()
SBModuleSpecList SBModuleSpecList::GetModuleSpecifications (const char * path) static
Definition at line 209 of file SBModuleSpec.cpp.
References lldb_private::ObjectFile::GetModuleSpecifications(), lldb_private::FileSystem::Instance(), LLDB_INSTRUMENT_VA, m_opaque_up, lldb_private::FileSystem::Resolve(), lldb_private::Host::ResolveExecutableInBundle(), and SBModuleSpecList().
GetSize()
size_t SBModuleSpecList::GetSize ()
Definition at line 232 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
GetSpecAtIndex()
SBModuleSpec SBModuleSpecList::GetSpecAtIndex (size_t i)
Definition at line 238 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, lldb::SBModuleSpec::m_opaque_up, and m_opaque_up.
operator=()
SBModuleSpecList & SBModuleSpecList::operator= (const SBModuleSpecList & rhs)
Definition at line 199 of file SBModuleSpec.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and SBModuleSpecList().
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::ModuleSpecList> lldb::SBModuleSpecList::m_opaque_up private
Definition at line 138 of file SBModuleSpec.h.
Referenced by Append(), Append(), FindFirstMatchingSpec(), FindMatchingSpecs(), GetDescription(), GetModuleSpecifications(), GetSize(), GetSpecAtIndex(), operator=(), SBModuleSpecList(), and SBModuleSpecList().
The documentation for this class was generated from the following files:
SBModuleSpec.h
SBModuleSpec.cpp