LLDB: lldb_private::StoppointSite Class Reference
lldb_private::StoppointSite Class Reference abstract
#include <StoppointSite.h>
Public Member Functions
StoppointSite (lldb::break_id_t bid, lldb::addr_t m_addr, bool hardware)
StoppointSite (lldb::break_id_t bid, lldb::addr_t m_addr, uint32_t byte_size, bool hardware)
virtual ~StoppointSite ()=default
virtual lldb::addr_t GetLoadAddress () const
virtual void SetLoadAddress (lldb::addr_t addr)
uint32_t GetByteSize () const
uint32_t GetHitCount () const
void ResetHitCount ()
bool HardwareRequired () const
virtual bool IsHardware () const =0
virtual bool ShouldStop (StoppointCallbackContext *context)
virtual bool ShouldStop (StoppointCallbackContext *context, BreakpointLocationCollection &stopping_bp_locs)
virtual void Dump (Stream *stream) const =0
lldb::break_id_t GetID () const
Protected Attributes
lldb::break_id_t m_id
Stoppoint site ID.
lldb::addr_t m_addr
The load address of this stop point.
bool m_is_hardware_required
True if this point is required to use hardware (which may fail due to the lack of resources).
uint32_t m_byte_size
The size in bytes of stoppoint, e.g.
StoppointHitCounter m_hit_counter
Number of times this breakpoint/watchpoint has been hit.
Private Member Functions
StoppointSite (const StoppointSite &)=delete
const StoppointSite & operator= (const StoppointSite &)=delete
StoppointSite ()=delete
Detailed Description
Definition at line 18 of file StoppointSite.h.
Constructor & Destructor Documentation
StoppointSite() [1/4]
lldb_private::StoppointSite::StoppointSite (lldb::break_id_t bid, lldb::addr_t m_addr, bool hardware)
References m_addr.
Referenced by lldb_private::BreakpointSite::BreakpointSite(), operator=(), StoppointSite(), and lldb_private::Watchpoint::Watchpoint().
StoppointSite() [2/4]
lldb_private::StoppointSite::StoppointSite (lldb::break_id_t bid, lldb::addr_t m_addr, uint32_t byte_size, bool hardware)
References m_addr.
~StoppointSite()
virtual lldb_private::StoppointSite::~StoppointSite () virtual default
StoppointSite() [3/4]
lldb_private::StoppointSite::StoppointSite (const StoppointSite &) private delete
References StoppointSite().
StoppointSite() [4/4]
lldb_private::StoppointSite::StoppointSite () private delete
Member Function Documentation
Dump()
virtual void lldb_private::StoppointSite::Dump (Stream * stream) const pure virtual
Implemented in lldb_private::BreakpointSite, and lldb_private::Watchpoint.
GetByteSize()
uint32_t lldb_private::StoppointSite::GetByteSize () const inline
Definition at line 31 of file StoppointSite.h.
References m_byte_size.
Referenced by lldb_private::Process::DisableSoftwareBreakpoint().
GetHitCount()
uint32_t lldb_private::StoppointSite::GetHitCount () const inline
Definition at line 33 of file StoppointSite.h.
References m_hit_counter.
Referenced by lldb_private::BreakpointSite::Dump(), and lldb_private::Watchpoint::DumpWithLevel().
GetID()
lldb::break_id_t lldb_private::StoppointSite::GetID () const inline
Definition at line 50 of file StoppointSite.h.
References m_id.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::DisableBreakpointSite(), lldb_private::ProcessWindows::DisableBreakpointSite(), lldb_private::Process::DisableSoftwareBreakpoint(), lldb_private::BreakpointSite::Dump(), lldb_private::Watchpoint::DumpSnapshots(), lldb_private::Watchpoint::DumpWithLevel(), lldb_private::process_gdb_remote::ProcessGDBRemote::EnableBreakpointSite(), lldb_private::ProcessWindows::EnableBreakpointSite(), lldb_private::Process::EnableSoftwareBreakpoint(), lldb_private::BreakpointSite::GetDescription(), lldb_private::Watchpoint::InvokeCallback(), and lldb_private::Watchpoint::SetupVariableWatchpointDisabler().
GetLoadAddress()
virtual lldb::addr_t lldb_private::StoppointSite::GetLoadAddress () const inline virtual
Definition at line 27 of file StoppointSite.h.
References m_addr.
Referenced by lldb_private::Watchpoint::CaptureWatchedValue(), lldb_private::process_gdb_remote::ProcessGDBRemote::DidForkSwitchHardwareTraps(), lldb_private::process_gdb_remote::ProcessGDBRemote::DidForkSwitchSoftwareBreakpoints(), lldb_private::process_gdb_remote::ProcessGDBRemote::DisableBreakpointSite(), lldb_private::ProcessWindows::DisableBreakpointSite(), ProcessKDP::DisableBreakpointSite(), lldb_private::Process::DisableSoftwareBreakpoint(), lldb_private::Watchpoint::DumpWithLevel(), lldb_private::process_gdb_remote::ProcessGDBRemote::EnableBreakpointSite(), lldb_private::ProcessWindows::EnableBreakpointSite(), lldb_private::ScriptedProcess::EnableBreakpointSite(), ProcessKDP::EnableBreakpointSite(), lldb_private::Process::EnableSoftwareBreakpoint(), lldb_private::BreakpointSite::GetDescription(), and lldb_private::Watchpoint::WatchedValueReportable().
HardwareRequired()
bool lldb_private::StoppointSite::HardwareRequired () const inline
Definition at line 37 of file StoppointSite.h.
References m_is_hardware_required.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::EnableBreakpointSite(), lldb_private::ProcessWindows::EnableBreakpointSite(), lldb_private::ScriptedProcess::EnableBreakpointSite(), ProcessKDP::EnableBreakpointSite(), lldb_private::BreakpointSite::IsHardware(), and lldb_private::Watchpoint::IsHardware().
IsHardware()
virtual bool lldb_private::StoppointSite::IsHardware () const pure virtual
Implemented in lldb_private::BreakpointSite, and lldb_private::Watchpoint.
operator=()
const StoppointSite & lldb_private::StoppointSite::operator= (const StoppointSite &) private delete
References StoppointSite().
ResetHitCount()
void lldb_private::StoppointSite::ResetHitCount () inline
Definition at line 35 of file StoppointSite.h.
References m_hit_counter.
SetLoadAddress()
virtual void lldb_private::StoppointSite::SetLoadAddress (lldb::addr_t addr) inline virtual
Definition at line 29 of file StoppointSite.h.
References m_addr.
ShouldStop() [1/2]
virtual bool lldb_private::StoppointSite::ShouldStop (StoppointCallbackContext * context) inline virtual
Reimplemented in lldb_private::Watchpoint.
Definition at line 41 of file StoppointSite.h.
ShouldStop() [2/2]
virtual bool lldb_private::StoppointSite::ShouldStop (StoppointCallbackContext * context, BreakpointLocationCollection & stopping_bp_locs) inline virtual
Reimplemented in lldb_private::BreakpointSite.
Definition at line 43 of file StoppointSite.h.
Member Data Documentation
m_addr
lldb::addr_t lldb_private::StoppointSite::m_addr protected
The load address of this stop point.
Definition at line 57 of file StoppointSite.h.
Referenced by lldb_private::BreakpointSite::Dump(), GetLoadAddress(), lldb_private::BreakpointSite::IntersectsRange(), SetLoadAddress(), StoppointSite(), and StoppointSite().
m_byte_size
uint32_t lldb_private::StoppointSite::m_byte_size protected
The size in bytes of stoppoint, e.g.
the length of the trap opcode for software breakpoints, or the optional length in bytes for hardware breakpoints, or the length of the watchpoint.
Definition at line 66 of file StoppointSite.h.
Referenced by lldb_private::Watchpoint::DumpWithLevel(), GetByteSize(), lldb_private::BreakpointSite::IntersectsRange(), and lldb_private::BreakpointSite::SetTrapOpcode().
m_hit_counter
StoppointHitCounter lldb_private::StoppointSite::m_hit_counter protected
Number of times this breakpoint/watchpoint has been hit.
Definition at line 69 of file StoppointSite.h.
Referenced by GetHitCount(), ResetHitCount(), lldb_private::BreakpointSite::ShouldStop(), lldb_private::Watchpoint::ShouldStop(), and lldb_private::Watchpoint::UndoHitCount().
m_id
lldb::break_id_t lldb_private::StoppointSite::m_id protected
Stoppoint site ID.
Definition at line 54 of file StoppointSite.h.
Referenced by GetID(), and lldb_private::Watchpoint::SetID().
m_is_hardware_required
bool lldb_private::StoppointSite::m_is_hardware_required protected
True if this point is required to use hardware (which may fail due to the lack of resources).
Definition at line 61 of file StoppointSite.h.
Referenced by HardwareRequired().
The documentation for this class was generated from the following file:
StoppointSite.h