LLDB: lldb::SBSourceManager Class Reference
lldb::SBSourceManager Class Reference
#include <SBSourceManager.h>
Public Member Functions
SBSourceManager (const SBDebugger &debugger)
SBSourceManager (const SBTarget &target)
SBSourceManager (const SBSourceManager &rhs)
~SBSourceManager ()
const lldb::SBSourceManager & operator= (const lldb::SBSourceManager &rhs)
size_t DisplaySourceLinesWithLineNumbers (const lldb::SBFileSpec &file, uint32_t line, uint32_t context_before, uint32_t context_after, const char *current_line_cstr, lldb::SBStream &s)
size_t DisplaySourceLinesWithLineNumbersAndColumn (const lldb::SBFileSpec &file, uint32_t line, uint32_t column, uint32_t context_before, uint32_t context_after, const char *current_line_cstr, lldb::SBStream &s)
Private Attributes
std::unique_ptr< lldb_private::SourceManagerImpl > m_opaque_up
Friends
class SBCommandInterpreter
class SBDebugger
Detailed Description
Definition at line 18 of file SBSourceManager.h.
Constructor & Destructor Documentation
SBSourceManager() [1/3]
SBSourceManager::SBSourceManager (const SBDebugger & debugger)
Definition at line 72 of file SBSourceManager.cpp.
References lldb::SBDebugger::get_sp(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBDebugger.
Referenced by SBSourceManager().
SBSourceManager() [2/3]
SBSourceManager::SBSourceManager (const SBTarget & target)
Definition at line 78 of file SBSourceManager.cpp.
References lldb::SBTarget::GetSP(), LLDB_INSTRUMENT_VA, and m_opaque_up.
SBSourceManager() [3/3]
SBSourceManager::SBSourceManager (const SBSourceManager & rhs)
Definition at line 84 of file SBSourceManager.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and SBSourceManager().
~SBSourceManager()
SBSourceManager::~SBSourceManager () default
References DisplaySourceLinesWithLineNumbers(), DisplaySourceLinesWithLineNumbersAndColumn(), and operator=().
Member Function Documentation
DisplaySourceLinesWithLineNumbers()
size_t SBSourceManager::DisplaySourceLinesWithLineNumbers (const lldb::SBFileSpec & file, uint32_t line, uint32_t context_before, uint32_t context_after, const char * current_line_cstr, lldb::SBStream & s)
Definition at line 103 of file SBSourceManager.cpp.
References DisplaySourceLinesWithLineNumbersAndColumn(), LLDB_INSTRUMENT_VA, and lldb::SBFileSpec::ref().
Referenced by ~SBSourceManager().
DisplaySourceLinesWithLineNumbersAndColumn()
size_t SBSourceManager::DisplaySourceLinesWithLineNumbersAndColumn (const lldb::SBFileSpec & file, uint32_t line, uint32_t column, uint32_t context_before, uint32_t context_after, const char * current_line_cstr, lldb::SBStream & s)
Definition at line 115 of file SBSourceManager.cpp.
References lldb::SBStream::get(), LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBFileSpec::ref().
Referenced by DisplaySourceLinesWithLineNumbers(), and ~SBSourceManager().
operator=()
const lldb::SBSourceManager & SBSourceManager::operator= (const lldb::SBSourceManager & rhs)
Definition at line 93 of file SBSourceManager.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBSourceManager().
Friends And Related Symbol Documentation
SBCommandInterpreter
friend class SBCommandInterpreter friend
Definition at line 38 of file SBSourceManager.h.
References SBCommandInterpreter.
Referenced by SBCommandInterpreter.
SBDebugger
friend class SBDebugger friend
Definition at line 39 of file SBSourceManager.h.
References SBDebugger.
Referenced by SBDebugger, and SBSourceManager().
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::SourceManagerImpl> lldb::SBSourceManager::m_opaque_up private
Definition at line 42 of file SBSourceManager.h.
Referenced by DisplaySourceLinesWithLineNumbersAndColumn(), operator=(), SBSourceManager(), SBSourceManager(), and SBSourceManager().
The documentation for this class was generated from the following files:
SBSourceManager.h
SBSourceManager.cpp