LLDB: lldb_private::ExpressionError Class Reference
lldb_private::ExpressionError Class Reference
An llvm::Error used to communicate diagnostics in Status.
#include <DiagnosticManager.h>
Public Member Functions
ExpressionError (lldb::ExpressionResults result, std::string msg, std::vector< DiagnosticDetail > details={})
std::string message () const override
llvm::ArrayRef< DiagnosticDetail > GetDetails () const override
std::error_code convertToErrorCode () const override
void log (llvm::raw_ostream &OS) const override
std::unique_ptr< CloneableError > Clone () const override
Static Public Attributes
static char ID
Private Attributes
std::string m_message
std::vector< DiagnosticDetail > m_details
Detailed Description
An llvm::Error used to communicate diagnostics in Status.
Multiple diagnostics may be chained in an llvm::ErrorList.
Definition at line 29 of file DiagnosticManager.h.
Constructor & Destructor Documentation
ExpressionError()
ExpressionError::ExpressionError (lldb::ExpressionResults result, std::string msg, std::vector< DiagnosticDetail > details = {})
Definition at line 34 of file DiagnosticManager.cpp.
References expression_category(), m_details, and m_message.
Member Function Documentation
Clone()
std::unique_ptr< CloneableError > ExpressionError::Clone () const override
Definition at line 71 of file DiagnosticManager.cpp.
References convertToErrorCode(), m_details, and m_message.
convertToErrorCode()
std::error_code ExpressionError::convertToErrorCode () const override
Definition at line 65 of file DiagnosticManager.cpp.
Referenced by Clone().
GetDetails()
llvm::ArrayRef< DiagnosticDetail > lldb_private::ExpressionError::GetDetails () const inline override
Definition at line 40 of file DiagnosticManager.h.
References m_details.
log()
void ExpressionError::log (llvm::raw_ostream & OS) const override
Definition at line 69 of file DiagnosticManager.cpp.
References message(), and lldb_private::OS.
message()
std::string ExpressionError::message () const override
Definition at line 53 of file DiagnosticManager.cpp.
References m_details, m_message, and StringForSeverity().
Referenced by log().
Member Data Documentation
ID
char ExpressionError::ID static
Definition at line 35 of file DiagnosticManager.h.
m_details
std::vector<DiagnosticDetail> lldb_private::ExpressionError::m_details private
Definition at line 32 of file DiagnosticManager.h.
Referenced by Clone(), ExpressionError(), GetDetails(), and message().
m_message
std::string lldb_private::ExpressionError::m_message private
Definition at line 31 of file DiagnosticManager.h.
Referenced by Clone(), ExpressionError(), and message().
The documentation for this class was generated from the following files:
DiagnosticManager.h
DiagnosticManager.cpp