LLDB: CommandObjectRegisterWrite Class Reference
CommandObjectRegisterWrite Class Reference
Public Member Functions
CommandObjectRegisterWrite (CommandInterpreter &interpreter)
~CommandObjectRegisterWrite () override=default
void HandleArgumentCompletion (CompletionRequest &request, OptionElementVector &opt_element_vector) override
The default version handles argument definitions that have only one argument type, and use one of the argument types that have an entry in the CommonCompletions.
Public Member Functions inherited from lldb_private::CommandObjectParsed
CommandObjectParsed (CommandInterpreter &interpreter, const char *name, const char *help=nullptr, const char *syntax=nullptr, uint32_t flags=0)
~CommandObjectParsed () override=default
void Execute (const char *args_string, CommandReturnObject &result) override
Public Member Functions inherited from lldb_private::CommandObject
CommandObject (CommandInterpreter &interpreter, llvm::StringRef name, llvm::StringRef help="", llvm::StringRef syntax="", uint32_t flags=0)
virtual ~CommandObject ()=default
CommandInterpreter & GetCommandInterpreter ()
Debugger & GetDebugger ()
virtual llvm::StringRef GetHelp ()
virtual llvm::StringRef GetHelpLong ()
virtual llvm::StringRef GetSyntax ()
llvm::StringRef GetCommandName () const
virtual void SetHelp (llvm::StringRef str)
virtual void SetHelpLong (llvm::StringRef str)
void SetSyntax (llvm::StringRef str)
virtual bool IsRemovable () const
virtual bool IsMultiwordObject ()
bool IsUserCommand ()
void SetIsUserCommand (bool is_user)
virtual CommandObjectMultiword * GetAsMultiwordCommand ()
virtual bool IsAlias ()
virtual bool IsDashDashCommand ()
virtual lldb::CommandObjectSP GetSubcommandSP (llvm::StringRef sub_cmd, StringList *matches=nullptr)
virtual lldb::CommandObjectSP GetSubcommandSPExact (llvm::StringRef sub_cmd)
virtual CommandObject * GetSubcommandObject (llvm::StringRef sub_cmd, StringList *matches=nullptr)
void FormatLongHelpText (Stream &output_strm, llvm::StringRef long_help)
void GenerateHelpText (CommandReturnObject &result)
virtual void GenerateHelpText (Stream &result)
virtual bool LoadSubCommand (llvm::StringRef cmd_name, const lldb::CommandObjectSP &command_obj)
virtual llvm::Error LoadUserSubcommand (llvm::StringRef cmd_name, const lldb::CommandObjectSP &command_obj, bool can_replace)
virtual bool WantsCompletion ()
virtual Options * GetOptions ()
void AddSimpleArgumentList (lldb::CommandArgumentType arg_type, ArgumentRepetitionType repetition_type=eArgRepeatPlain)
void AddIDsArgumentData (IDType type)
int GetNumArgumentEntries ()
CommandArgumentEntry * GetArgumentEntryAtIndex (int idx)
void GetFormattedCommandArguments (Stream &str, uint32_t opt_set_mask=LLDB_OPT_SET_ALL)
bool ParseOptions (Args &args, CommandReturnObject &result)
void SetCommandName (llvm::StringRef name)
virtual void HandleCompletion (CompletionRequest &request)
This default version handles calling option argument completions and then calls HandleArgumentCompletion if the cursor is on an argument, not an option.
bool HelpTextContainsWord (llvm::StringRef search_word, bool search_short_help=true, bool search_long_help=true, bool search_syntax=true, bool search_options=true)
Flags & GetFlags ()
The flags accessor.
const Flags & GetFlags () const
The flags const accessor.
virtual std::optional< std::string > GetRepeatCommand (Args &current_command_args, uint32_t index)
Get the command that appropriate for a "repeat" of the current command.
bool HasOverrideCallback () const
void SetOverrideCallback (lldb::CommandOverrideCallback callback, void *baton)
void SetOverrideCallback (lldb_private::CommandOverrideCallbackWithResult callback, void *baton)
bool InvokeOverrideCallback (const char **argv, CommandReturnObject &result)
void SetOriginalCommandString (std::string s)
Set the command input as it appeared in the terminal.
Protected Member Functions
void DoExecute (Args &command, CommandReturnObject &result) override
Protected Member Functions inherited from lldb_private::CommandObjectParsed
bool WantsRawCommandString () override
Protected Member Functions inherited from lldb_private::CommandObject
bool ParseOptionsAndNotify (Args &args, CommandReturnObject &result, OptionGroupOptions &group_options, ExecutionContext &exe_ctx)
virtual const char * GetInvalidTargetDescription ()
virtual const char * GetInvalidProcessDescription ()
virtual const char * GetInvalidThreadDescription ()
virtual const char * GetInvalidFrameDescription ()
virtual const char * GetInvalidRegContextDescription ()
Target & GetDummyTarget ()
Target & GetTarget ()
Thread * GetDefaultThread ()
bool CheckRequirements (CommandReturnObject &result)
Check the command to make sure anything required by this command is available.
void Cleanup ()
Additional Inherited Members
Public Types inherited from lldb_private::CommandObject
enum IDType { eBreakpointArgs = 0 , eWatchpointArgs = 1 }
typedef llvm::StringRef ArgumentHelpCallbackFunction()
typedef std::vector< CommandArgumentData > CommandArgumentEntry
typedef std::map< std::string, lldb::CommandObjectSP, std::less<> > CommandMap
Static Public Member Functions inherited from lldb_private::CommandObject
static const char * GetArgumentTypeAsCString (const lldb::CommandArgumentType arg_type)
static const char * GetArgumentDescriptionAsCString (const lldb::CommandArgumentType arg_type)
static lldb::CommandArgumentType LookupArgumentName (llvm::StringRef arg_name)
static const ArgumentTableEntry * FindArgumentDataByType (lldb::CommandArgumentType arg_type)
static void GetArgumentHelp (Stream &str, lldb::CommandArgumentType arg_type, CommandInterpreter &interpreter)
static const char * GetArgumentName (lldb::CommandArgumentType arg_type)
static bool IsPairType (ArgumentRepetitionType arg_repeat_type)
static std::optional< ArgumentRepetitionType > ArgRepetitionFromString (llvm::StringRef string)
Protected Attributes inherited from lldb_private::CommandObject
CommandInterpreter & m_interpreter
ExecutionContext m_exe_ctx
std::unique_lock< std::recursive_mutex > m_api_locker
std::string m_cmd_name
std::string m_cmd_help_short
std::string m_cmd_help_long
std::string m_cmd_syntax
std::string m_original_command
Flags m_flags
std::vector< CommandArgumentEntry > m_arguments
lldb::CommandOverrideCallback m_deprecated_command_override_callback
lldb_private::CommandOverrideCallbackWithResult m_command_override_callback
void * m_command_override_baton
bool m_is_user_command = false
Detailed Description
Definition at line 289 of file CommandObjectRegister.cpp.
Constructor & Destructor Documentation
CommandObjectRegisterWrite()
CommandObjectRegisterWrite::CommandObjectRegisterWrite (CommandInterpreter & interpreter) inline
Definition at line 291 of file CommandObjectRegister.cpp.
References lldb_private::CommandObject::CommandArgumentData::arg_repetition, lldb_private::CommandObject::CommandArgumentData::arg_type, lldb_private::CommandObjectParsed::CommandObjectParsed(), lldb_private::eArgRepeatPlain, lldb::eArgTypeRegisterName, lldb::eArgTypeValue, and lldb_private::CommandObject::m_arguments.
~CommandObjectRegisterWrite()
CommandObjectRegisterWrite::~CommandObjectRegisterWrite () override default
Member Function Documentation
DoExecute()
void CommandObjectRegisterWrite::DoExecute (Args & command, CommandReturnObject & result) inline override protected virtual
Implements lldb_private::CommandObjectParsed.
Definition at line 336 of file CommandObjectRegister.cpp.
References lldb_private::CommandReturnObject::AppendError(), lldb_private::CommandReturnObject::AppendErrorWithFormat(), lldb::eReturnStatusSuccessFinishNoResult, error(), lldb_private::Args::GetArgumentCount(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::CommandObject::m_exe_ctx, lldb_private::CommandReturnObject::SetStatus(), lldb_private::RegisterValue::SetValueFromString(), and lldb_private::RegisterContext::WriteRegister().
HandleArgumentCompletion()
void CommandObjectRegisterWrite::HandleArgumentCompletion (CompletionRequest & request, OptionElementVector & opt_element_vector) inline override virtual
The default version handles argument definitions that have only one argument type, and use one of the argument types that have an entry in the CommonCompletions.
Override this if you have a more complex argument setup. FIXME: we should be able to extend this to more complex argument definitions provided we have completers for all the argument types.
The input array contains a parsed version of the line.
We've constructed the map of options and their arguments as well if that is helpful for the completion.
Parameters
[in,out] request The completion request that needs to be answered.
Reimplemented from lldb_private::CommandObject.
Definition at line 326 of file CommandObjectRegister.cpp.
References lldb::eRegisterCompletion, lldb_private::CommandObject::GetCommandInterpreter(), lldb_private::CompletionRequest::GetCursorIndex(), lldb_private::CommandCompletions::InvokeCommonCompletionCallbacks(), and lldb_private::CommandObject::m_exe_ctx.
The documentation for this class was generated from the following file:
CommandObjectRegister.cpp