LLDB: lldb_private::ModuleSpec Class Reference
lldb_private::ModuleSpec Class Reference
#include <ModuleSpec.h>
Public Member Functions
ModuleSpec ()=default
ModuleSpec (const FileSpec &file_spec, const UUID &uuid=UUID(), lldb::DataExtractorSP extractor_sp=lldb::DataExtractorSP())
If the extractor_sp argument is passed, its contents will be used as the module contents instead of trying to read them from file_spec .
ModuleSpec (const FileSpec &file_spec, const ArchSpec &arch)
FileSpec * GetFileSpecPtr ()
const FileSpec * GetFileSpecPtr () const
FileSpec & GetFileSpec ()
const FileSpec & GetFileSpec () const
FileSpec * GetPlatformFileSpecPtr ()
const FileSpec * GetPlatformFileSpecPtr () const
FileSpec & GetPlatformFileSpec ()
const FileSpec & GetPlatformFileSpec () const
FileSpec * GetSymbolFileSpecPtr ()
const FileSpec * GetSymbolFileSpecPtr () const
FileSpec & GetSymbolFileSpec ()
const FileSpec & GetSymbolFileSpec () const
ArchSpec * GetArchitecturePtr ()
const ArchSpec * GetArchitecturePtr () const
ArchSpec & GetArchitecture ()
const ArchSpec & GetArchitecture () const
UUID * GetUUIDPtr ()
const UUID * GetUUIDPtr () const
UUID & GetUUID ()
const UUID & GetUUID () const
ConstString & GetObjectName ()
ConstString GetObjectName () const
uint64_t GetObjectOffset () const
void SetObjectOffset (uint64_t object_offset)
uint64_t GetObjectSize () const
void SetObjectSize (uint64_t object_size)
llvm::sys::TimePoint & GetObjectModificationTime ()
const llvm::sys::TimePoint & GetObjectModificationTime () const
PathMappingList & GetSourceMappingList () const
lldb::DataExtractorSP GetExtractor () const
lldb::TargetSP GetTargetSP () const
void SetTarget (lldb::TargetSP target)
Set the target to be used when resolving a module.
lldb::PlatformSP GetPlatformSP () const
void SetPlatform (lldb::PlatformSP platform)
Set the platform to be used when resolving a module.
void Clear ()
operator bool () const
void Dump (Stream &strm) const
bool Matches (const ModuleSpec &match_module_spec, bool exact_arch_match) const
Protected Attributes
FileSpec m_file
FileSpec m_platform_file
FileSpec m_symbol_file
ArchSpec m_arch
UUID m_uuid
ConstString m_object_name
std::weak_ptr< Target > m_target_wp
The target used when resolving a module.
std::weak_ptr< Platform > m_platform_wp
The platform used when resolving a module.
uint64_t m_object_offset = 0
uint64_t m_object_size = 0
llvm::sys::TimePoint m_object_mod_time
PathMappingList m_source_mappings
lldb::DataExtractorSP m_extractor_sp = {}
Detailed Description
Definition at line 30 of file ModuleSpec.h.
Constructor & Destructor Documentation
ModuleSpec() [1/3]
lldb_private::ModuleSpec::ModuleSpec () default
Referenced by Matches().
ModuleSpec() [2/3]
lldb_private::ModuleSpec::ModuleSpec (const FileSpec & file_spec, const UUID & uuid = UUID(), lldb::DataExtractorSP extractor_sp = lldb::DataExtractorSP()) inline
If the extractor_sp argument is passed, its contents will be used as the module contents instead of trying to read them from file_spec .
Definition at line 37 of file ModuleSpec.h.
References lldb_private::FileSystem::Instance(), m_extractor_sp, m_file, m_object_offset, m_object_size, and m_uuid.
ModuleSpec() [3/3]
lldb_private::ModuleSpec::ModuleSpec (const FileSpec & file_spec, const ArchSpec & arch) inline
Definition at line 47 of file ModuleSpec.h.
References m_arch, m_file, m_object_offset, and m_object_size.
Member Function Documentation
Clear()
void lldb_private::ModuleSpec::Clear () inline
Definition at line 152 of file ModuleSpec.h.
References m_arch, m_file, m_object_mod_time, m_object_name, m_object_offset, m_object_size, m_platform_file, m_platform_wp, m_source_mappings, m_symbol_file, m_target_wp, and m_uuid.
Referenced by lldb_private::ModuleSpecList::FindMatchingModuleSpec(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetModuleInfo(), lldb_private::Process::GetModuleSpec(), and lldb_private::ModuleSpecList::GetModuleSpecAtIndex().
Dump()
void lldb_private::ModuleSpec::Dump (Stream & strm) const inline
Definition at line 187 of file ModuleSpec.h.
References lldb_private::Stream::AsRawOstream(), lldb_private::Stream::Format(), m_arch, m_file, m_object_mod_time, m_object_name, m_object_offset, m_object_size, m_platform_file, m_symbol_file, m_uuid, lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
Referenced by lldb_private::platform_gdb_server::PlatformRemoteGDBServer::GetModuleSpec(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetModuleSpec(), and DynamicLoaderPOSIXDYLD::ResolveExecutableModule().
GetArchitecture() [1/2]
ArchSpec & lldb_private::ModuleSpec::GetArchitecture () inline
Definition at line 93 of file ModuleSpec.h.
References m_arch.
Referenced by lldb::SBTarget::AddModule(), CommandObjectTargetSymbolsAdd::AddModuleSymbols(), CommandObjectTargetSymbolsAdd::AddSymbolsForFile(), CommandObjectTargetSymbolsAdd::AddSymbolsForFrame(), CommandObjectTargetSymbolsAdd::AddSymbolsForStack(), ProcessKDP::DoConnectRemote(), CommandObjectTargetModulesAdd::DoExecute(), ProcessElfCore::DoLoadCore(), lldb_private::SymbolLocatorDebugSymbols::DownloadObjectAndSymbolFile(), ObjectFileMachO::Dump(), FileAtPathContainsArchAndUUID(), FindModulesByName(), lldb_private::SymbolLocatorDebugSymbols::FindSymbolFileInBundle(), lldb_private::DynamicLoaderDarwin::FindTargetModuleForImageInfo(), ObjectFileMachO::GetAllArchSpecs(), ObjectFileMachO::GetArchitecture(), lldb_private::ScriptedProcess::GetLoadedDynamicLibrariesInfos(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetModuleInfo(), lldb_private::ObjectFilePDB::GetModuleSpecifications(), ObjectContainerBSDArchive::GetModuleSpecifications(), ObjectFileELF::GetModuleSpecifications(), ObjectFilePECOFF::GetModuleSpecifications(), ObjectFileXCOFF::GetModuleSpecifications(), lldb_private::Platform::GetRemoteSharedModule(), lldb_private::ModuleList::GetSharedModule(), lldb_private::PlatformMacOSX::GetSharedModule(), lldb_private::PlatformDarwinDevice::GetSharedModuleWithLocalCache(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_jModulesInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qModuleInfo(), DynamicLoaderDarwinKernel::KextImageInfo::LoadImageUsingMemoryModule(), lldb_private::SymbolLocatorDefault::LocateExecutableSymbolFile(), Matches(), lldb_private::Module::MatchesModuleSpec(), lldb_private::Module::Module(), ObjectFileMachO::ParseHeader(), ParseModuleSpec(), lldb_private::minidump::ProcessMinidump::ReadModuleList(), lldb_private::Platform::ResolveExecutable(), and lldb_private::plugin::dwarf::SymbolFileDWARF::UpdateExternalModuleListIfNeeded().
GetArchitecture() [2/2]
const ArchSpec & lldb_private::ModuleSpec::GetArchitecture () const inline
Definition at line 95 of file ModuleSpec.h.
References m_arch.
GetArchitecturePtr() [1/2]
ArchSpec * lldb_private::ModuleSpec::GetArchitecturePtr () inline
Definition at line 85 of file ModuleSpec.h.
References m_arch.
Referenced by FileAtPathContainsArchAndUUID(), lldb_private::ModuleSpecList::FindMatchingModuleSpec(), lldb_private::ModuleSpecList::FindMatchingModuleSpecs(), lldb_private::SymbolLocatorDebugSymbols::FindSymbolFileInBundle(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableObjectFile(), lldb_private::SymbolLocatorDefault::LocateExecutableObjectFile(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableSymbolFile(), LocateMacOSXFilesUsingDebugSymbols(), LookForDsymNextToExecutablePath(), Matches(), and lldb_private::PlatformDarwin::ResolveSymbolFile().
GetArchitecturePtr() [2/2]
const ArchSpec * lldb_private::ModuleSpec::GetArchitecturePtr () const inline
Definition at line 89 of file ModuleSpec.h.
References m_arch.
GetExtractor()
lldb::DataExtractorSP lldb_private::ModuleSpec::GetExtractor () const inline
Definition at line 131 of file ModuleSpec.h.
References m_extractor_sp.
Referenced by lldb_private::Module::Module().
GetFileSpec() [1/2]
FileSpec & lldb_private::ModuleSpec::GetFileSpec () inline
Definition at line 57 of file ModuleSpec.h.
References m_file.
Referenced by lldb::SBTarget::AddModule(), CommandObjectTargetSymbolsAdd::AddModuleSymbols(), CommandObjectTargetSymbolsAdd::AddSymbolsForFile(), CommandObjectTargetSymbolsAdd::AddSymbolsForFrame(), CommandObjectTargetSymbolsAdd::AddSymbolsForStack(), BringInRemoteFile(), lldb_private::Platform::CallLocateModuleCallbackIfSet(), lldb_private::wasm::SymbolVendorWasm::CreateInstance(), SymbolVendorELF::CreateInstance(), SymbolVendorPECOFF::CreateInstance(), ProcessKDP::DoConnectRemote(), CommandObjectTargetModulesAdd::DoExecute(), CommandObjectTargetModulesLoad::DoExecute(), CommandObjectTargetSymbolsAdd::DoExecute(), ProcessElfCore::DoLoadCore(), lldb_private::PlatformDarwin::FindBundleBinaryInExecSearchPaths(), lldb_private::DynamicLoaderDarwin::FindTargetModuleForImageInfo(), lldb_private::ModuleCache::Get(), lldb_private::ModuleCache::GetAndPut(), lldb_private::Platform::GetCachedExecutable(), lldb_private::Platform::GetCachedSharedModule(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwpSymbolFile(), getFileName(), lldb_private::ScriptedProcess::GetLoadedDynamicLibrariesInfos(), lldb_private::PlatformDarwin::GetModuleFromSharedCaches(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetModuleInfo(), ObjectFileMachO::GetModuleSpecifications(), GetModuleSpecInfoFromUUIDDictionary(), lldb_private::Target::GetOrCreateModule(), lldb_private::DynamicLoaderDarwin::GetPThreadLibraryModule(), lldb_private::Platform::GetRemoteSharedModule(), lldb_private::ModuleList::GetSharedModule(), lldb_private::Platform::GetSharedModule(), lldb_private::PlatformAppleSimulator::GetSharedModule(), lldb_private::PlatformDarwin::GetSharedModule(), lldb_private::PlatformRemoteDarwinDevice::GetSharedModule(), lldb_private::PlatformDarwinDevice::GetSharedModuleWithLocalCache(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_jModulesInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qModuleInfo(), lldb_private::DynamicLoader::LoadBinaryWithUUIDAndAddress(), DynamicLoaderDarwinKernel::KextImageInfo::LoadImageUsingMemoryModule(), DynamicLoaderFreeBSDKernel::KModImageInfo::LoadImageUsingMemoryModule(), LocateDSYMInVincinityOfExecutable(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableObjectFile(), lldb_private::SymbolLocatorDefault::LocateExecutableObjectFile(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableSymbolFile(), lldb_private::SymbolLocatorDefault::LocateExecutableSymbolFile(), LocateMacOSXFilesUsingDebugSymbols(), Matches(), lldb_private::Module::MatchesModuleSpec(), lldb_private::Module::Module(), lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::ParseKernel(), lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::ParseModule(), ParseModuleSpec(), lldb_private::minidump::ProcessMinidump::ReadModuleList(), lldb_private::Platform::ResolveExecutable(), lldb_private::RemoteAwarePlatform::ResolveExecutable(), lldb_private::Symbol::ResolveReExportedSymbol(), lldb_private::Symbol::ResolveReExportedSymbolInModuleSpec(), and lldb_private::plugin::dwarf::SymbolFileDWARF::UpdateExternalModuleListIfNeeded().
GetFileSpec() [2/2]
const FileSpec & lldb_private::ModuleSpec::GetFileSpec () const inline
Definition at line 59 of file ModuleSpec.h.
References m_file.
GetFileSpecPtr() [1/2]
FileSpec * lldb_private::ModuleSpec::GetFileSpecPtr () inline
Definition at line 51 of file ModuleSpec.h.
References m_file.
Referenced by CommandObjectTargetModulesLoad::DoExecute(), lldb_private::SymbolLocatorDebugSymbols::DownloadObjectAndSymbolFile(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::GetModuleInfo(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableObjectFile(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableSymbolFile(), and LocateMacOSXFilesUsingDebugSymbols().
GetFileSpecPtr() [2/2]
const FileSpec * lldb_private::ModuleSpec::GetFileSpecPtr () const inline
Definition at line 53 of file ModuleSpec.h.
References m_file.
GetObjectModificationTime() [1/2]
llvm::sys::TimePoint & lldb_private::ModuleSpec::GetObjectModificationTime () inline
Definition at line 121 of file ModuleSpec.h.
References m_object_mod_time.
Referenced by ObjectContainerBSDArchive::GetModuleSpecifications(), and lldb_private::Module::Module().
GetObjectModificationTime() [2/2]
const llvm::sys::TimePoint & lldb_private::ModuleSpec::GetObjectModificationTime () const inline
Definition at line 125 of file ModuleSpec.h.
References m_object_mod_time.
GetObjectName() [1/2]
ConstString & lldb_private::ModuleSpec::GetObjectName () inline
Definition at line 107 of file ModuleSpec.h.
References m_object_name.
Referenced by lldb_private::DynamicLoaderDarwin::AddModulesUsingPreloadedModules(), lldb_private::ObjectContainerMachOFileset::GetModuleSpecifications(), ObjectContainerBSDArchive::GetModuleSpecifications(), Matches(), lldb_private::Module::MatchesModuleSpec(), and lldb_private::Module::Module().
GetObjectName() [2/2]
ConstString lldb_private::ModuleSpec::GetObjectName () const inline
Definition at line 109 of file ModuleSpec.h.
References m_object_name.
GetObjectOffset()
uint64_t lldb_private::ModuleSpec::GetObjectOffset () const inline
Definition at line 111 of file ModuleSpec.h.
References m_object_offset.
Referenced by lldb_private::Platform::GetCachedSharedModule(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_jModulesInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qModuleInfo(), and lldb_private::Module::Module().
GetObjectSize()
uint64_t lldb_private::ModuleSpec::GetObjectSize () const inline
Definition at line 117 of file ModuleSpec.h.
References m_object_size.
Referenced by lldb_private::ModuleCache::Get(), lldb_private::Platform::GetCachedSharedModule(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_jModulesInfo(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qModuleInfo().
GetPlatformFileSpec() [1/2]
FileSpec & lldb_private::ModuleSpec::GetPlatformFileSpec () inline
Definition at line 69 of file ModuleSpec.h.
References m_platform_file.
Referenced by CommandObjectTargetSymbolsAdd::AddModuleSymbols(), CommandObjectTargetSymbolsAdd::AddSymbolsForFile(), lldb_private::SymbolContext::FindBestGlobalDataSymbol(), lldb_private::Platform::GetCachedExecutable(), lldb_private::ModuleList::GetSharedModule(), lldb_private::PlatformDarwinDevice::GetSharedModuleWithLocalCache(), lldb_private::ClangExpressionDeclMap::GetSymbolAddress(), Matches(), lldb_private::Module::MatchesModuleSpec(), lldb_private::Module::Module(), lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::ParseModule(), and lldb_private::ModuleList::ReplaceEquivalent().
GetPlatformFileSpec() [2/2]
const FileSpec & lldb_private::ModuleSpec::GetPlatformFileSpec () const inline
Definition at line 71 of file ModuleSpec.h.
References m_platform_file.
GetPlatformFileSpecPtr() [1/2]
FileSpec * lldb_private::ModuleSpec::GetPlatformFileSpecPtr () inline
Definition at line 61 of file ModuleSpec.h.
References m_platform_file.
GetPlatformFileSpecPtr() [2/2]
const FileSpec * lldb_private::ModuleSpec::GetPlatformFileSpecPtr () const inline
Definition at line 65 of file ModuleSpec.h.
References m_platform_file.
GetPlatformSP()
lldb::PlatformSP lldb_private::ModuleSpec::GetPlatformSP () const inline
Definition at line 143 of file ModuleSpec.h.
References m_platform_wp.
Referenced by lldb_private::ModuleList::GetSharedModule().
GetSourceMappingList()
PathMappingList & lldb_private::ModuleSpec::GetSourceMappingList () const inline
Definition at line 129 of file ModuleSpec.h.
References m_source_mappings.
Referenced by SymbolVendorMacOSX::CreateInstance(), and GetModuleSpecInfoFromUUIDDictionary().
GetSymbolFileSpec() [1/2]
FileSpec & lldb_private::ModuleSpec::GetSymbolFileSpec () inline
Definition at line 81 of file ModuleSpec.h.
References m_symbol_file.
Referenced by lldb::SBTarget::AddModule(), CommandObjectTargetSymbolsAdd::AddModuleSymbols(), lldb_private::wasm::SymbolVendorWasm::CreateInstance(), SymbolVendorELF::CreateInstance(), SymbolVendorPECOFF::CreateInstance(), ProcessKDP::DoConnectRemote(), CommandObjectTargetModulesAdd::DoExecute(), CommandObjectTargetSymbolsAdd::DoExecute(), CommandObjectTargetSymbolsAdd::DownloadObjectAndSymbolFile(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwpSymbolFile(), getFileName(), GetModuleSpecInfoFromUUIDDictionary(), lldb_private::ModuleList::GetSharedModule(), lldb_private::PlatformDarwinDevice::GetSharedModuleWithLocalCache(), lldb_private::DynamicLoader::LoadBinaryWithUUIDAndAddress(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableObjectFile(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableSymbolFile(), lldb_private::SymbolLocatorDefault::LocateExecutableSymbolFile(), LocateMacOSXFilesUsingDebugSymbols(), LookForDsymNextToExecutablePath(), Matches(), lldb_private::Module::Module(), lldb_private::Platform::ResolveSymbolFile(), and lldb_private::PlatformDarwin::ResolveSymbolFile().
GetSymbolFileSpec() [2/2]
const FileSpec & lldb_private::ModuleSpec::GetSymbolFileSpec () const inline
Definition at line 83 of file ModuleSpec.h.
References m_symbol_file.
GetSymbolFileSpecPtr() [1/2]
FileSpec * lldb_private::ModuleSpec::GetSymbolFileSpecPtr () inline
Definition at line 73 of file ModuleSpec.h.
References m_symbol_file.
GetSymbolFileSpecPtr() [2/2]
const FileSpec * lldb_private::ModuleSpec::GetSymbolFileSpecPtr () const inline
Definition at line 77 of file ModuleSpec.h.
References m_symbol_file.
GetTargetSP()
lldb::TargetSP lldb_private::ModuleSpec::GetTargetSP () const inline
Definition at line 133 of file ModuleSpec.h.
References m_target_wp.
Referenced by lldb_private::PlatformDarwin::FindBundleBinaryInExecSearchPaths(), lldb_private::ModuleList::GetSharedModule(), and lldb_private::PlatformDarwin::GetSharedModule().
GetUUID() [1/2]
UUID & lldb_private::ModuleSpec::GetUUID () inline
Definition at line 103 of file ModuleSpec.h.
References m_uuid.
Referenced by lldb::SBTarget::AddModule(), CommandObjectTargetSymbolsAdd::AddModuleSymbols(), CommandObjectTargetSymbolsAdd::AddSymbolsForFile(), CommandObjectTargetSymbolsAdd::AddSymbolsForFrame(), CommandObjectTargetSymbolsAdd::AddSymbolsForStack(), CommandObjectTargetSymbolsAdd::AddSymbolsForUUID(), lldb_private::wasm::SymbolVendorWasm::CreateInstance(), SymbolVendorELF::CreateInstance(), SymbolVendorMacOSX::CreateInstance(), SymbolVendorPECOFF::CreateInstance(), ProcessKDP::DoConnectRemote(), CommandObjectTargetModulesAdd::DoExecute(), CommandObjectTargetModulesLoad::DoExecute(), ProcessElfCore::DoLoadCore(), lldb_private::SymbolLocator::DownloadSymbolFileAsync(), FileAtPathContainsArchAndUUID(), lldb_private::DynamicLoader::FindModuleViaTarget(), lldb_private::SymbolLocatorDebugSymbols::FindSymbolFileInBundle(), lldb_private::DynamicLoaderDarwin::FindTargetModuleForImageInfo(), lldb_private::ModuleCache::Get(), lldb_private::ModuleCache::GetAndPut(), lldb_private::Platform::GetCachedSharedModule(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwpSymbolFile(), GetFileForModule(), lldb_private::ScriptedProcess::GetLoadedDynamicLibrariesInfos(), lldb_private::PlatformDarwin::GetModuleFromSharedCaches(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetModuleInfo(), lldb_private::breakpad::ObjectFileBreakpad::GetModuleSpecifications(), lldb_private::ObjectFileJSON::GetModuleSpecifications(), lldb_private::ObjectFilePDB::GetModuleSpecifications(), ObjectFileELF::GetModuleSpecifications(), ObjectFilePECOFF::GetModuleSpecifications(), lldb_private::Target::GetOrCreateModule(), lldb_private::Platform::GetRemoteSharedModule(), lldb_private::PlatformDarwinDevice::GetSharedModuleWithLocalCache(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_jModulesInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qModuleInfo(), DynamicLoaderPOSIXDYLD::LoadAllCurrentModules(), lldb_private::DynamicLoader::LoadBinaryWithUUIDAndAddress(), DynamicLoaderDarwinKernel::KextImageInfo::LoadImageUsingMemoryModule(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableObjectFile(), lldb_private::SymbolLocatorDefault::LocateExecutableSymbolFile(), LocateMacOSXFilesUsingDebugSymbols(), Matches(), lldb_private::Module::MatchesModuleSpec(), lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::ParseModule(), ParseModuleSpec(), lldb_private::ModuleCache::Put(), lldb_private::minidump::ProcessMinidump::ReadModuleList(), and lldb_private::Platform::ResolveExecutable().
GetUUID() [2/2]
const UUID & lldb_private::ModuleSpec::GetUUID () const inline
Definition at line 105 of file ModuleSpec.h.
References m_uuid.
GetUUIDPtr() [1/2]
UUID * lldb_private::ModuleSpec::GetUUIDPtr () inline
Definition at line 97 of file ModuleSpec.h.
References m_uuid.
Referenced by CommandObjectTargetModulesLoad::DoExecute(), lldb_private::SymbolLocatorDebugSymbols::DownloadObjectAndSymbolFile(), FileAtPathContainsArchAndUUID(), lldb_private::SymbolLocatorDebugSymbols::FindSymbolFileInBundle(), lldb_private::ModuleList::GetSharedModule(), lldb_private::PlatformAppleSimulator::GetSharedModule(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableObjectFile(), lldb_private::SymbolLocatorDefault::LocateExecutableObjectFile(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableSymbolFile(), LocateMacOSXFilesUsingDebugSymbols(), LookForDsymNextToExecutablePath(), Matches(), and lldb_private::PlatformDarwin::ResolveSymbolFile().
GetUUIDPtr() [2/2]
const UUID * lldb_private::ModuleSpec::GetUUIDPtr () const inline
Definition at line 99 of file ModuleSpec.h.
References m_uuid.
Matches()
bool lldb_private::ModuleSpec::Matches (const ModuleSpec & match_module_spec, bool exact_arch_match) const inline
Definition at line 251 of file ModuleSpec.h.
References GetArchitecture(), GetArchitecturePtr(), GetFileSpec(), GetObjectName(), GetPlatformFileSpec(), GetSymbolFileSpec(), GetUUID(), GetUUIDPtr(), lldb_private::FileSpec::Match(), and ModuleSpec().
operator bool()
lldb_private::ModuleSpec::operator bool () const inline explicit
Definition at line 167 of file ModuleSpec.h.
References m_arch, m_file, m_object_mod_time, m_object_name, m_object_size, m_platform_file, m_symbol_file, and m_uuid.
SetObjectOffset()
void lldb_private::ModuleSpec::SetObjectOffset (uint64_t object_offset) inline
Definition at line 113 of file ModuleSpec.h.
References m_object_offset.
Referenced by lldb_private::DynamicLoaderDarwin::AddModulesUsingPreloadedModules(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetModuleInfo(), ObjectContainerBSDArchive::GetModuleSpecifications(), ObjectFileELF::GetModuleSpecifications(), ObjectFileMachO::GetModuleSpecifications(), and ParseModuleSpec().
SetObjectSize()
void lldb_private::ModuleSpec::SetObjectSize (uint64_t object_size) inline
Definition at line 119 of file ModuleSpec.h.
References m_object_size.
Referenced by lldb_private::DynamicLoaderDarwin::AddModulesUsingPreloadedModules(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetModuleInfo(), ObjectContainerBSDArchive::GetModuleSpecifications(), ObjectFileELF::GetModuleSpecifications(), ObjectFileMachO::GetModuleSpecifications(), and ParseModuleSpec().
SetPlatform()
void lldb_private::ModuleSpec::SetPlatform (lldb::PlatformSP platform) inline
Set the platform to be used when resolving a module.
This is useful when a Target is not yet available (e.g., during target creation) but a Platform is. The platform can be used to invoke locate module callbacks and other platform-specific module resolution logic.
Definition at line 150 of file ModuleSpec.h.
References m_platform_wp.
SetTarget()
void lldb_private::ModuleSpec::SetTarget (lldb::TargetSP target) inline
Set the target to be used when resolving a module.
A target can help locate a module specified by a ModuleSpec. The target settings, like the executable and debug info search paths, can be essential. The target's platform can also be used to locate or download the specified module.
Definition at line 141 of file ModuleSpec.h.
References m_target_wp.
Referenced by ProcessElfCore::CanDebug(), ProcessMachCore::CanDebug(), lldb_private::Target::GetOrCreateModule(), lldb_private::DynamicLoader::LoadBinaryWithUUIDAndAddress(), DynamicLoaderDarwinKernel::KextImageInfo::LoadImageUsingMemoryModule(), DynamicLoaderPOSIXDYLD::ResolveExecutableModule(), and lldb_private::Target::SetArchitecture().
Member Data Documentation
m_arch
ArchSpec lldb_private::ModuleSpec::m_arch protected
Definition at line 290 of file ModuleSpec.h.
Referenced by Clear(), Dump(), GetArchitecture(), GetArchitecture(), GetArchitecturePtr(), GetArchitecturePtr(), ModuleSpec(), and operator bool().
m_extractor_sp
lldb::DataExtractorSP lldb_private::ModuleSpec::m_extractor_sp = {} protected
Definition at line 305 of file ModuleSpec.h.
Referenced by GetExtractor(), and ModuleSpec().
m_file
FileSpec lldb_private::ModuleSpec::m_file protected
Definition at line 287 of file ModuleSpec.h.
Referenced by Clear(), Dump(), GetFileSpec(), GetFileSpec(), GetFileSpecPtr(), GetFileSpecPtr(), ModuleSpec(), ModuleSpec(), and operator bool().
m_object_mod_time
llvm::sys::TimePoint lldb_private::ModuleSpec::m_object_mod_time protected
Definition at line 303 of file ModuleSpec.h.
Referenced by Clear(), Dump(), GetObjectModificationTime(), GetObjectModificationTime(), and operator bool().
m_object_name
ConstString lldb_private::ModuleSpec::m_object_name protected
Definition at line 292 of file ModuleSpec.h.
Referenced by Clear(), Dump(), GetObjectName(), GetObjectName(), and operator bool().
m_object_offset
uint64_t lldb_private::ModuleSpec::m_object_offset = 0 protected
Definition at line 301 of file ModuleSpec.h.
Referenced by Clear(), Dump(), GetObjectOffset(), ModuleSpec(), ModuleSpec(), and SetObjectOffset().
m_object_size
uint64_t lldb_private::ModuleSpec::m_object_size = 0 protected
Definition at line 302 of file ModuleSpec.h.
Referenced by Clear(), Dump(), GetObjectSize(), ModuleSpec(), ModuleSpec(), operator bool(), and SetObjectSize().
m_platform_file
FileSpec lldb_private::ModuleSpec::m_platform_file protected
Definition at line 288 of file ModuleSpec.h.
Referenced by Clear(), Dump(), GetPlatformFileSpec(), GetPlatformFileSpec(), GetPlatformFileSpecPtr(), GetPlatformFileSpecPtr(), and operator bool().
m_platform_wp
std::weak_ptr<Platform> lldb_private::ModuleSpec::m_platform_wp protected
The platform used when resolving a module.
This is useful when a Target is not yet available (e.g., during target creation) but a Platform is.
Definition at line 300 of file ModuleSpec.h.
Referenced by Clear(), GetPlatformSP(), and SetPlatform().
m_source_mappings
PathMappingList lldb_private::ModuleSpec::m_source_mappings mutable protected
Definition at line 304 of file ModuleSpec.h.
Referenced by Clear(), and GetSourceMappingList().
m_symbol_file
FileSpec lldb_private::ModuleSpec::m_symbol_file protected
Definition at line 289 of file ModuleSpec.h.
Referenced by Clear(), Dump(), GetSymbolFileSpec(), GetSymbolFileSpec(), GetSymbolFileSpecPtr(), GetSymbolFileSpecPtr(), and operator bool().
m_target_wp
std::weak_ptr<Target> lldb_private::ModuleSpec::m_target_wp protected
The target used when resolving a module.
A target can help locate a module specified by a ModuleSpec. The target settings, like the executable and debug info search paths, can be essential. The target's platform can also be used to locate or download the specified module.
Definition at line 297 of file ModuleSpec.h.
Referenced by Clear(), GetTargetSP(), and SetTarget().
m_uuid
UUID lldb_private::ModuleSpec::m_uuid protected
Definition at line 291 of file ModuleSpec.h.
Referenced by Clear(), Dump(), GetUUID(), GetUUID(), GetUUIDPtr(), GetUUIDPtr(), ModuleSpec(), and operator bool().
The documentation for this class was generated from the following file:
ModuleSpec.h