LLDB: CommandObjectBreakpointAddFile::CommandOptions Class Reference
CommandObjectBreakpointAddFile::CommandOptions Class Reference
Public Member Functions
CommandOptions ()=default
~CommandOptions () override=default
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext *execution_context) override
void OptionParsingStarting (ExecutionContext *execution_context) override
Status OptionParsingFinished (ExecutionContext *execution_context) override
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
Public Attributes
bool m_hardware = false
std::vector< OptionValueFileColonLine > m_line_specs
LazyBool m_skip_prologue = eLazyBoolCalculate
OptionValueFileColonLine m_cur_value
FileSpecList m_modules
LazyBool m_move_to_nearest_code = eLazyBoolCalculate
lldb::addr_t m_offset_addr = 0
Detailed Description
Definition at line 721 of file CommandObjectBreakpoint.cpp.
Constructor & Destructor Documentation
CommandOptions()
CommandObjectBreakpointAddFile::CommandOptions::CommandOptions () default
~CommandOptions()
CommandObjectBreakpointAddFile::CommandOptions::~CommandOptions () override default
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > CommandObjectBreakpointAddFile::CommandOptions::GetDefinitions () inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 851 of file CommandObjectBreakpoint.cpp.
Referenced by SetOptionValue().
OptionParsingFinished()
Status CommandObjectBreakpointAddFile::CommandOptions::OptionParsingFinished (ExecutionContext * execution_context) inline override virtual
Reimplemented from lldb_private::OptionGroup.
Definition at line 838 of file CommandObjectBreakpoint.cpp.
References CompleteLineEntry(), error(), LLDB_INVALID_LINE_NUMBER, m_cur_value, and m_line_specs.
OptionParsingStarting()
void CommandObjectBreakpointAddFile::CommandOptions::OptionParsingStarting (ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 828 of file CommandObjectBreakpoint.cpp.
References lldb_private::eLazyBoolCalculate, m_cur_value, m_hardware, m_line_specs, m_modules, m_move_to_nearest_code, m_offset_addr, and m_skip_prologue.
SetOptionValue()
Status CommandObjectBreakpointAddFile::CommandOptions::SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 727 of file CommandObjectBreakpoint.cpp.
References CompleteLineEntry(), lldb_private::CreateOptionParsingError(), lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, error(), lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), lldb_private::g_bool_parsing_error_message, lldb_private::g_int_parsing_error_message, GetDefinitions(), LLDB_INVALID_LINE_NUMBER, m_cur_value, m_hardware, m_line_specs, m_modules, m_move_to_nearest_code, m_offset_addr, m_skip_prologue, lldb_private::OptionArgParser::ToAddress(), and lldb_private::OptionArgParser::ToBoolean().
Member Data Documentation
m_cur_value
OptionValueFileColonLine CommandObjectBreakpointAddFile::CommandOptions::m_cur_value
Definition at line 859 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingFinished(), OptionParsingStarting(), and SetOptionValue().
m_hardware
bool CommandObjectBreakpointAddFile::CommandOptions::m_hardware = false
Definition at line 856 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_line_specs
std::vector<OptionValueFileColonLine> CommandObjectBreakpointAddFile::CommandOptions::m_line_specs
Definition at line 857 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingFinished(), OptionParsingStarting(), and SetOptionValue().
m_modules
FileSpecList CommandObjectBreakpointAddFile::CommandOptions::m_modules
Definition at line 860 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_move_to_nearest_code
LazyBool CommandObjectBreakpointAddFile::CommandOptions::m_move_to_nearest_code = eLazyBoolCalculate
Definition at line 861 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_offset_addr
lldb::addr_t CommandObjectBreakpointAddFile::CommandOptions::m_offset_addr = 0
Definition at line 862 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_skip_prologue
LazyBool CommandObjectBreakpointAddFile::CommandOptions::m_skip_prologue = eLazyBoolCalculate
Definition at line 858 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following file:
CommandObjectBreakpoint.cpp