LLDB: lldb_private::ITSession Class Reference
lldb_private::ITSession Class Reference
#include <EmulateInstructionARM.h>
Public Member Functions
ITSession ()=default
~ITSession ()=default
bool InitIT (uint32_t bits7_0)
void ITAdvance ()
bool InITBlock ()
bool LastInITBlock ()
uint32_t GetCond ()
Private Attributes
uint32_t ITCounter = 0
uint32_t ITState = 0
Detailed Description
Definition at line 30 of file EmulateInstructionARM.h.
Constructor & Destructor Documentation
ITSession()
lldb_private::ITSession::ITSession () default
~ITSession()
lldb_private::ITSession::~ITSession () default
Member Function Documentation
GetCond()
uint32_t ITSession::GetCond ()
Definition at line 652 of file EmulateInstructionARM.cpp.
References lldb_private::Bits32(), COND_AL, InITBlock(), and ITState.
InITBlock()
bool ITSession::InITBlock ()
Definition at line 646 of file EmulateInstructionARM.cpp.
References ITCounter.
Referenced by GetCond().
InitIT()
bool ITSession::InitIT (uint32_t bits7_0)
Definition at line 615 of file EmulateInstructionARM.cpp.
References lldb_private::Bits32(), CountITSize(), ITCounter, and ITState.
ITAdvance()
void ITSession::ITAdvance ()
Definition at line 634 of file EmulateInstructionARM.cpp.
References lldb_private::Bits32(), ITCounter, ITState, and lldb_private::SetBits32().
LastInITBlock()
bool ITSession::LastInITBlock ()
Definition at line 649 of file EmulateInstructionARM.cpp.
References ITCounter.
Member Data Documentation
ITCounter
uint32_t lldb_private::ITSession::ITCounter = 0 private
Definition at line 52 of file EmulateInstructionARM.h.
Referenced by InITBlock(), InitIT(), ITAdvance(), and LastInITBlock().
ITState
uint32_t lldb_private::ITSession::ITState = 0 private
Definition at line 53 of file EmulateInstructionARM.h.
Referenced by GetCond(), InitIT(), and ITAdvance().
The documentation for this class was generated from the following files:
EmulateInstructionARM.h
EmulateInstructionARM.cpp