LLDB: lldb_private::ThreadPlanStepRange Class Reference
lldb_private::ThreadPlanStepRange Class Reference abstract
#include <ThreadPlanStepRange.h>
Public Member Functions
ThreadPlanStepRange (ThreadPlanKind kind, const char *name, Thread &thread, const AddressRange &range, const SymbolContext &addr_context, lldb::RunMode stop_others, bool given_ranges_only=false)
~ThreadPlanStepRange () override
void GetDescription (Stream *s, lldb::DescriptionLevel level) override=0
Print a description of this thread to the stream s.
bool ValidatePlan (Stream *error) override
Returns whether this plan could be successfully created.
bool ShouldStop (Event *event_ptr) override=0
Vote ShouldReportStop (Event *event_ptr) override
bool StopOthers () override
lldb::StateType GetPlanRunState () override
bool WillStop () override
bool MischiefManaged () override
void DidPush () override
bool IsPlanStale () override
void AddRange (const AddressRange &new_range)
Public Member Functions inherited from lldb_private::ThreadPlan
virtual ~ThreadPlan ()
const char * GetName () const
Returns the name of this thread plan.
Thread & GetThread ()
Returns the Thread that is using this thread plan.
Target & GetTarget ()
const Target & GetTarget () const
void ClearThreadCache ()
Clear the Thread* cache.
bool TracerExplainsStop ()
lldb::StateType RunState ()
bool PlanExplainsStop (Event *event_ptr)
virtual bool ShouldAutoContinue (Event *event_ptr)
Returns whether this thread plan overrides the ShouldStop of subsequently processed plans.
Vote ShouldReportRun (Event *event_ptr)
virtual void SetStopOthers (bool new_value)
virtual bool SupportsResumeOthers ()
virtual bool ShouldRunBeforePublicStop ()
bool WillResume (lldb::StateType resume_state, bool current_plan)
bool IsControllingPlan ()
virtual bool IsLeafPlan ()
bool SetIsControllingPlan (bool value)
virtual bool OkayToDiscard ()
void SetOkayToDiscard (bool value)
virtual void ThreadDestroyed ()
bool GetPrivate ()
void SetPrivate (bool input)
virtual void DidPop ()
ThreadPlanKind GetKind () const
bool IsPlanComplete ()
void SetPlanComplete (bool success=true)
bool PlanSucceeded ()
virtual bool IsBasePlan ()
lldb::ThreadPlanTracerSP & GetThreadPlanTracer ()
void SetThreadPlanTracer (lldb::ThreadPlanTracerSP new_tracer_sp)
void DoTraceLog ()
virtual lldb::ValueObjectSP GetReturnValueObject ()
virtual lldb::ExpressionVariableSP GetExpressionVariable ()
virtual void RestoreThreadState ()
virtual bool IsVirtualStep ()
bool SetIterationCount (size_t count)
virtual lldb::RunDirection GetDirection () const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Protected Member Functions
bool InRange ()
lldb::FrameComparison CompareCurrentFrameToStartFrame ()
bool InSymbol ()
void DumpRanges (Stream *s)
Disassembler * GetDisassembler ()
InstructionList * GetInstructionsForAddress (lldb::addr_t addr, size_t &range_index, size_t &insn_offset)
bool SetNextBranchBreakpoint ()
bool IsNextBranchBreakpointStop (lldb::StopInfoSP stop_info_sp)
void ClearNextBranchBreakpoint ()
void ClearNextBranchBreakpointExplainedStop ()
bool NextRangeBreakpointExplainsStop (lldb::StopInfoSP stop_info_sp)
Protected Member Functions inherited from lldb_private::ThreadPlan
ThreadPlan (ThreadPlanKind kind, const char *name, Thread &thread, Vote report_stop_vote, Vote report_run_vote)
virtual bool DoWillResume (lldb::StateType resume_state, bool current_plan)
virtual bool DoPlanExplainsStop (Event *event_ptr)=0
void PushPlan (lldb::ThreadPlanSP &thread_plan_sp)
ThreadPlan * GetPreviousPlan ()
lldb::StopInfoSP GetPrivateStopInfo ()
void SetStopInfo (lldb::StopInfoSP stop_reason_sp)
bool IsUsuallyUnexplainedStopReason (lldb::StopReason)
Protected Attributes
SymbolContext m_addr_context
std::vector< AddressRange > m_address_ranges
lldb::RunMode m_stop_others
StackID m_stack_id
StackID m_parent_stack_id
bool m_no_more_plans
bool m_first_run_event
lldb::BreakpointSP m_next_branch_bp_sp
bool m_use_fast_step
bool m_given_ranges_only
bool m_found_calls = false
Protected Attributes inherited from lldb_private::ThreadPlan
Status m_status
Process & m_process
lldb::tid_t m_tid
Vote m_report_stop_vote
Vote m_report_run_vote
bool m_takes_iteration_count
bool m_could_not_resolve_hw_bp
int32_t m_iteration_count = 1
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Private Member Functions
ThreadPlanStepRange (const ThreadPlanStepRange &)=delete
const ThreadPlanStepRange & operator= (const ThreadPlanStepRange &)=delete
Private Attributes
std::vector< lldb::DisassemblerSP > m_instruction_ranges
Additional Inherited Members
Public Types inherited from lldb_private::ThreadPlan
enum ThreadPlanKind {
eKindGeneric , eKindNull , eKindBase , eKindCallFunction ,
eKindPython , eKindStepInstruction , eKindStepOut , eKindStepOverBreakpoint ,
eKindStepOverRange , eKindStepInRange , eKindRunToAddress , eKindStepThrough ,
eKindStepUntil , eKindSingleThreadTimeout
}
Detailed Description
Definition at line 20 of file ThreadPlanStepRange.h.
Constructor & Destructor Documentation
ThreadPlanStepRange() [1/2]
ThreadPlanStepRange::ThreadPlanStepRange (ThreadPlanKind kind, const char * name, Thread & thread, const AddressRange & range, const SymbolContext & addr_context, lldb::RunMode stop_others, bool given_ranges_only = false)
Definition at line 32 of file ThreadPlanStepRange.cpp.
References AddRange(), lldb_private::eVoteNoOpinion, lldb_private::ThreadPlan::GetTarget(), lldb_private::TargetProperties::GetUseFastStepping(), m_addr_context, m_address_ranges, m_first_run_event, m_given_ranges_only, m_no_more_plans, m_parent_stack_id, m_stack_id, m_stop_others, m_use_fast_step, and lldb_private::ThreadPlan::ThreadPlan().
Referenced by operator=(), lldb_private::ThreadPlanStepInRange::ThreadPlanStepInRange(), lldb_private::ThreadPlanStepOverRange::ThreadPlanStepOverRange(), and ThreadPlanStepRange().
~ThreadPlanStepRange()
ThreadPlanStepRange::~ThreadPlanStepRange () override
Definition at line 51 of file ThreadPlanStepRange.cpp.
References ClearNextBranchBreakpoint().
ThreadPlanStepRange() [2/2]
lldb_private::ThreadPlanStepRange::ThreadPlanStepRange (const ThreadPlanStepRange &) private delete
References ThreadPlanStepRange().
Member Function Documentation
AddRange()
void ThreadPlanStepRange::AddRange (const AddressRange & new_range)
Definition at line 77 of file ThreadPlanStepRange.cpp.
References m_address_ranges, and m_instruction_ranges.
Referenced by InRange(), lldb_private::ThreadPlanStepOut::QueueInlinedStepPlan(), and ThreadPlanStepRange().
ClearNextBranchBreakpoint()
void ThreadPlanStepRange::ClearNextBranchBreakpoint () protected
Definition at line 314 of file ThreadPlanStepRange.cpp.
References lldb_private::GetLog(), lldb_private::ThreadPlan::GetTarget(), LLDB_LOGF, lldb_private::ThreadPlan::m_could_not_resolve_hw_bp, m_found_calls, m_next_branch_bp_sp, lldb_private::Target::RemoveBreakpointByID(), and lldb_private::Step.
Referenced by ClearNextBranchBreakpointExplainedStop(), MischiefManaged(), lldb_private::ThreadPlanStepInRange::ShouldStop(), lldb_private::ThreadPlanStepOverRange::ShouldStop(), and ~ThreadPlanStepRange().
ClearNextBranchBreakpointExplainedStop()
void ThreadPlanStepRange::ClearNextBranchBreakpointExplainedStop () protected
Definition at line 326 of file ThreadPlanStepRange.cpp.
References ClearNextBranchBreakpoint(), lldb_private::ThreadPlan::GetPrivateStopInfo(), and IsNextBranchBreakpointStop().
Referenced by lldb_private::ThreadPlanStepInRange::ShouldStop(), and lldb_private::ThreadPlanStepOverRange::ShouldStop().
CompareCurrentFrameToStartFrame()
lldb::FrameComparison ThreadPlanStepRange::CompareCurrentFrameToStartFrame () protected
Definition at line 219 of file ThreadPlanStepRange.cpp.
References lldb::eFrameCompareEqual, lldb::eFrameCompareOlder, lldb::eFrameCompareSameParent, lldb::eFrameCompareYounger, lldb_private::ThreadPlan::GetThread(), lldb_private::StackID::IsValid(), m_parent_stack_id, and m_stack_id.
Referenced by IsPlanStale(), MischiefManaged(), lldb_private::ThreadPlanStepInRange::ShouldStop(), and lldb_private::ThreadPlanStepOverRange::ShouldStop().
DidPush()
void ThreadPlanStepRange::DidPush () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 53 of file ThreadPlanStepRange.cpp.
References SetNextBranchBreakpoint().
Referenced by lldb_private::ThreadPlanStepOverRange::DidPush().
DumpRanges()
void ThreadPlanStepRange::DumpRanges (Stream * s) protected
Definition at line 89 of file ThreadPlanStepRange.cpp.
References lldb_private::Address::DumpStyleLoadAddress, lldb_private::ThreadPlan::GetTarget(), m_address_ranges, and lldb_private::Stream::Printf().
Referenced by lldb_private::ThreadPlanStepOverRange::DoWillResume(), lldb_private::ThreadPlanStepInRange::GetDescription(), and lldb_private::ThreadPlanStepOverRange::GetDescription().
GetDescription()
void lldb_private::ThreadPlanStepRange::GetDescription (Stream * s, lldb::DescriptionLevel level) override pure virtual
Print a description of this thread to the stream s.
thread. Don't expect that the result of GetThread is valid in the description method. This might get called when the underlying Thread has not been reported, so we only know the TID and not the thread.
Parameters
[in] s The stream to which to print the description.
[in] level The level of description desired. Note that eDescriptionLevelBrief will be used in the stop message printed when the plan is complete.
Implements lldb_private::ThreadPlan.
Implemented in lldb_private::ThreadPlanStepInRange, and lldb_private::ThreadPlanStepOverRange.
References error().
GetDisassembler()
Disassembler * lldb_private::ThreadPlanStepRange::GetDisassembler () protected
GetInstructionsForAddress()
InstructionList * ThreadPlanStepRange::GetInstructionsForAddress (lldb::addr_t addr, size_t & range_index, size_t & insn_offset) protected
Definition at line 258 of file ThreadPlanStepRange.cpp.
References lldb_private::Disassembler::DisassembleRange(), lldb_private::ThreadPlan::GetTarget(), m_address_ranges, m_instruction_ranges, and UINT32_MAX.
Referenced by SetNextBranchBreakpoint().
GetPlanRunState()
StateType ThreadPlanStepRange::GetPlanRunState () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 495 of file ThreadPlanStepRange.cpp.
References lldb::eStateRunning, lldb::eStateStepping, and m_next_branch_bp_sp.
InRange()
bool ThreadPlanStepRange::InRange () protected
Definition at line 101 of file ThreadPlanStepRange.cpp.
References AddRange(), lldb_private::Address::DumpStyleLoadAddress, lldb_private::SupportFile::eEqualFileSpecAndChecksumIfSet, lldb_private::ThreadPlan::eKindStepOverRange, lldb_private::AddressRange::GetBaseAddress(), lldb_private::StreamString::GetData(), lldb_private::ThreadPlan::GetKind(), lldb_private::Address::GetLoadAddress(), lldb_private::GetLog(), lldb_private::StackFrame::GetSymbolContext(), lldb_private::ThreadPlan::GetTarget(), lldb_private::ThreadPlan::GetThread(), lldb_private::LineEntry::IsValid(), lldb_private::LineEntry::line, lldb_private::SymbolContext::line_entry, LLDB_LOGF, m_addr_context, m_address_ranges, m_given_ranges_only, lldb_private::LineEntry::original_file_sp, lldb_private::LineEntry::range, and lldb_private::Step.
Referenced by IsPlanStale(), MischiefManaged(), lldb_private::ThreadPlanStepInRange::ShouldStop(), and lldb_private::ThreadPlanStepOverRange::ShouldStop().
InSymbol()
bool ThreadPlanStepRange::InSymbol () protected
Definition at line 197 of file ThreadPlanStepRange.cpp.
References lldb_private::AddressRange::ContainsLoadAddress(), lldb_private::Thread::GetRegisterContext(), lldb_private::ThreadPlan::GetTarget(), lldb_private::ThreadPlan::GetThread(), and m_addr_context.
Referenced by IsPlanStale(), lldb_private::ThreadPlanStepInRange::ShouldStop(), and lldb_private::ThreadPlanStepOverRange::ShouldStop().
IsNextBranchBreakpointStop()
bool ThreadPlanStepRange::IsNextBranchBreakpointStop (lldb::StopInfoSP stop_info_sp) protected
Definition at line 300 of file ThreadPlanStepRange.cpp.
References m_next_branch_bp_sp, and lldb_private::ThreadPlan::m_process.
Referenced by ClearNextBranchBreakpointExplainedStop(), and NextRangeBreakpointExplainsStop().
IsPlanStale()
bool ThreadPlanStepRange::IsPlanStale () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 535 of file ThreadPlanStepRange.cpp.
References CompareCurrentFrameToStartFrame(), lldb::eFrameCompareEqual, lldb::eFrameCompareOlder, lldb_private::GetLog(), lldb_private::Thread::GetRegisterContext(), lldb_private::ThreadPlan::GetTarget(), lldb_private::ThreadPlan::GetThread(), InRange(), InSymbol(), LLDB_LOGF, m_address_ranges, lldb_private::ThreadPlan::SetPlanComplete(), and lldb_private::Step.
MischiefManaged()
bool ThreadPlanStepRange::MischiefManaged () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 502 of file ThreadPlanStepRange.cpp.
References ClearNextBranchBreakpoint(), CompareCurrentFrameToStartFrame(), lldb::eFrameCompareOlder, lldb_private::GetLog(), InRange(), lldb_private::ThreadPlan::IsPlanComplete(), LLDB_LOGF, m_no_more_plans, lldb_private::ThreadPlan::MischiefManaged(), and lldb_private::Step.
NextRangeBreakpointExplainsStop()
bool ThreadPlanStepRange::NextRangeBreakpointExplainsStop (lldb::StopInfoSP stop_info_sp) protected
Definition at line 460 of file ThreadPlanStepRange.cpp.
References lldb_private::GetLog(), IsNextBranchBreakpointStop(), LLDB_LOGF, lldb_private::ThreadPlan::m_process, and lldb_private::Step.
Referenced by lldb_private::ThreadPlanStepInRange::DoPlanExplainsStop(), and lldb_private::ThreadPlanStepOverRange::DoPlanExplainsStop().
operator=()
const ThreadPlanStepRange & lldb_private::ThreadPlanStepRange::operator= (const ThreadPlanStepRange &) private delete
References ThreadPlanStepRange().
SetNextBranchBreakpoint()
bool ThreadPlanStepRange::SetNextBranchBreakpoint () protected
Definition at line 331 of file ThreadPlanStepRange.cpp.
References lldb_private::LineEntry::ApplyFileMappings(), lldb_private::Address::CalculateSymbolContextBlock(), lldb_private::LineEntry::column, lldb_private::Target::CreateBreakpoint(), lldb_private::ThreadPlan::eKindStepOverRange, lldb_private::LineEntry::file_sp, lldb_private::AddressRange::GetBaseAddress(), lldb_private::InlineFunctionInfo::GetCallSite(), lldb_private::Declaration::GetColumn(), lldb_private::Block::GetContainingInlinedBlock(), lldb_private::Declaration::GetFile(), lldb_private::LineEntry::GetFile(), lldb_private::Address::GetFileAddress(), lldb_private::InstructionList::GetIndexOfNextBranchInstruction(), lldb_private::Block::GetInlinedParent(), lldb_private::InstructionList::GetInstructionAtIndex(), GetInstructionsForAddress(), lldb_private::ThreadPlan::GetKind(), lldb_private::Declaration::GetLine(), lldb_private::Address::GetLoadAddress(), lldb_private::GetLog(), lldb_private::Thread::GetRegisterContext(), lldb_private::InstructionList::GetSize(), lldb_private::ThreadPlan::GetTarget(), lldb_private::ThreadPlan::GetThread(), lldb_private::Address::IsValid(), lldb_private::LineEntry::IsValid(), lldb_private::LineEntry::line, LLDB_INVALID_BREAK_ID, LLDB_LOG, LLDB_LOGF, lldb_private::ThreadPlan::m_could_not_resolve_hw_bp, m_found_calls, m_next_branch_bp_sp, lldb_private::ThreadPlan::m_process, lldb_private::ThreadPlan::m_tid, m_use_fast_step, lldb_private::LineEntry::original_file_sp, lldb_private::LineEntry::range, lldb_private::Address::Slide(), lldb_private::Step, and UINT32_MAX.
Referenced by DidPush(), lldb_private::ThreadPlanStepInRange::ShouldStop(), and lldb_private::ThreadPlanStepOverRange::ShouldStop().
ShouldReportStop()
Vote ThreadPlanStepRange::ShouldReportStop (Event * event_ptr) override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 68 of file ThreadPlanStepRange.cpp.
References lldb_private::eVoteNo, lldb_private::eVoteYes, lldb_private::GetLog(), lldb_private::ThreadPlan::IsPlanComplete(), LLDB_LOGF, and lldb_private::Step.
ShouldStop()
bool lldb_private::ThreadPlanStepRange::ShouldStop (Event * event_ptr) override pure virtual
Implements lldb_private::ThreadPlan.
Implemented in lldb_private::ThreadPlanStepInRange, and lldb_private::ThreadPlanStepOverRange.
StopOthers()
bool ThreadPlanStepRange::StopOthers () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 242 of file ThreadPlanStepRange.cpp.
References lldb::eAllThreads, lldb::eOnlyDuringStepping, lldb::eOnlyThisThread, m_found_calls, and m_stop_others.
ValidatePlan()
bool ThreadPlanStepRange::ValidatePlan (Stream * error) override virtual
Returns whether this plan could be successfully created.
Parameters
[in] error A stream to which to print some reason why the plan could not be created. Can be NULL.
Returns
true if the plan should be queued, false otherwise.
Implements lldb_private::ThreadPlan.
Definition at line 58 of file ThreadPlanStepRange.cpp.
References error(), and lldb_private::ThreadPlan::m_could_not_resolve_hw_bp.
Referenced by lldb_private::ThreadPlanStepOut::QueueInlinedStepPlan().
WillStop()
bool ThreadPlanStepRange::WillStop () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 493 of file ThreadPlanStepRange.cpp.
Member Data Documentation
m_addr_context
SymbolContext lldb_private::ThreadPlanStepRange::m_addr_context protected
Definition at line 72 of file ThreadPlanStepRange.h.
Referenced by lldb_private::ThreadPlanStepInRange::GetDescription(), lldb_private::ThreadPlanStepOverRange::GetDescription(), InRange(), InSymbol(), lldb_private::ThreadPlanStepOverRange::IsEquivalentContext(), lldb_private::ThreadPlanStepOverRange::ShouldStop(), and ThreadPlanStepRange().
m_address_ranges
std::vector<AddressRange> lldb_private::ThreadPlanStepRange::m_address_ranges protected
Definition at line 73 of file ThreadPlanStepRange.h.
Referenced by AddRange(), lldb_private::ThreadPlanStepOverRange::DoWillResume(), DumpRanges(), GetInstructionsForAddress(), InRange(), IsPlanStale(), and ThreadPlanStepRange().
m_first_run_event
bool lldb_private::ThreadPlanStepRange::m_first_run_event protected
Definition at line 81 of file ThreadPlanStepRange.h.
Referenced by ThreadPlanStepRange().
m_found_calls
bool lldb_private::ThreadPlanStepRange::m_found_calls = false protected
Definition at line 86 of file ThreadPlanStepRange.h.
Referenced by ClearNextBranchBreakpoint(), SetNextBranchBreakpoint(), and StopOthers().
m_given_ranges_only
bool lldb_private::ThreadPlanStepRange::m_given_ranges_only protected
Definition at line 85 of file ThreadPlanStepRange.h.
Referenced by InRange(), and ThreadPlanStepRange().
m_instruction_ranges
std::vector<lldb::DisassemblerSP> lldb_private::ThreadPlanStepRange::m_instruction_ranges private
Definition at line 94 of file ThreadPlanStepRange.h.
Referenced by AddRange(), and GetInstructionsForAddress().
m_next_branch_bp_sp
lldb::BreakpointSP lldb_private::ThreadPlanStepRange::m_next_branch_bp_sp protected
Definition at line 83 of file ThreadPlanStepRange.h.
Referenced by ClearNextBranchBreakpoint(), GetPlanRunState(), IsNextBranchBreakpointStop(), SetNextBranchBreakpoint(), and lldb_private::ThreadPlanStepOverRange::ShouldStop().
m_no_more_plans
bool lldb_private::ThreadPlanStepRange::m_no_more_plans protected
Definition at line 78 of file ThreadPlanStepRange.h.
Referenced by MischiefManaged(), lldb_private::ThreadPlanStepInRange::ShouldStop(), lldb_private::ThreadPlanStepOverRange::ShouldStop(), and ThreadPlanStepRange().
m_parent_stack_id
StackID lldb_private::ThreadPlanStepRange::m_parent_stack_id protected
Definition at line 76 of file ThreadPlanStepRange.h.
Referenced by CompareCurrentFrameToStartFrame(), and ThreadPlanStepRange().
m_stack_id
StackID lldb_private::ThreadPlanStepRange::m_stack_id protected
Definition at line 75 of file ThreadPlanStepRange.h.
Referenced by CompareCurrentFrameToStartFrame(), lldb_private::ThreadPlanStepInRange::ShouldStop(), lldb_private::ThreadPlanStepOverRange::ShouldStop(), and ThreadPlanStepRange().
m_stop_others
lldb::RunMode lldb_private::ThreadPlanStepRange::m_stop_others protected
Definition at line 74 of file ThreadPlanStepRange.h.
Referenced by lldb_private::ThreadPlanStepOverRange::SetStopOthers(), lldb_private::ThreadPlanStepInRange::ShouldStop(), lldb_private::ThreadPlanStepOverRange::ShouldStop(), StopOthers(), and ThreadPlanStepRange().
m_use_fast_step
bool lldb_private::ThreadPlanStepRange::m_use_fast_step protected
Definition at line 84 of file ThreadPlanStepRange.h.
Referenced by SetNextBranchBreakpoint(), and ThreadPlanStepRange().
The documentation for this class was generated from the following files:
ThreadPlanStepRange.h
ThreadPlanStepRange.cpp