LLDB: lldb_private::Timer::Category Class Reference
lldb_private::Timer::Category Class Reference
#include <Timer.h>
Public Member Functions
Category (const char *category_name)
llvm::StringRef GetName ()
Private Member Functions
Category (const Category &)=delete
const Category & operator= (const Category &)=delete
Private Attributes
const char * m_name
std::atomic< uint64_t > m_nanos
std::atomic< uint64_t > m_nanos_total
std::atomic< uint64_t > m_count
std::atomic< Category * > m_next
Friends
class Timer
Detailed Description
Definition at line 25 of file Timer.h.
Constructor & Destructor Documentation
Category() [1/2]
Timer::Category::Category (const char * category_name) explicit
Definition at line 48 of file Timer.cpp.
References Category(), g_categories, m_count, m_name, m_nanos, m_nanos_total, and m_next.
Referenced by Category(), Category(), and operator=().
Category() [2/2]
lldb_private::Timer::Category::Category (const Category &) private delete
References Category().
Member Function Documentation
GetName()
llvm::StringRef lldb_private::Timer::Category::GetName () inline
Definition at line 28 of file Timer.h.
References m_name.
operator=()
const Category & lldb_private::Timer::Category::operator= (const Category &) private delete
References Category().
Friends And Related Symbol Documentation
Timer
friend class Timer friend
Definition at line 31 of file Timer.h.
References Timer.
Referenced by Timer.
Member Data Documentation
m_count
std::atomic<uint64_t> lldb_private::Timer::Category::m_count private
Definition at line 35 of file Timer.h.
Referenced by Category().
m_name
const char* lldb_private::Timer::Category::m_name private
Definition at line 32 of file Timer.h.
Referenced by Category(), and GetName().
m_nanos
std::atomic<uint64_t> lldb_private::Timer::Category::m_nanos private
Definition at line 33 of file Timer.h.
Referenced by Category().
m_nanos_total
std::atomic<uint64_t> lldb_private::Timer::Category::m_nanos_total private
Definition at line 34 of file Timer.h.
Referenced by Category().
m_next
std::atomic<Category *> lldb_private::Timer::Category::m_next private
Definition at line 36 of file Timer.h.
Referenced by Category().
The documentation for this class was generated from the following files:
Timer.h
Timer.cpp