LLDB: lldb::SBLineEntry Class Reference
lldb::SBLineEntry Class Reference
#include <SBLineEntry.h>
Public Member Functions
SBLineEntry ()
SBLineEntry (const lldb::SBLineEntry &rhs)
~SBLineEntry ()
const lldb::SBLineEntry & operator= (const lldb::SBLineEntry &rhs)
lldb::SBAddress GetStartAddress () const
lldb::SBAddress GetEndAddress () const
lldb::SBAddress GetSameLineContiguousAddressRangeEnd (bool include_inlined_functions) const
operator bool () const
bool IsValid () const
lldb::SBFileSpec GetFileSpec () const
uint32_t GetLine () const
uint32_t GetColumn () const
void SetFileSpec (lldb::SBFileSpec filespec)
void SetLine (uint32_t line)
void SetColumn (uint32_t column)
bool operator== (const lldb::SBLineEntry &rhs) const
bool operator!= (const lldb::SBLineEntry &rhs) const
bool GetDescription (lldb::SBStream &description)
Protected Member Functions
lldb_private::LineEntry * get ()
Private Member Functions
const lldb_private::LineEntry * operator-> () const
lldb_private::LineEntry & ref ()
const lldb_private::LineEntry & ref () const
SBLineEntry (const lldb_private::LineEntry *lldb_object_ptr)
void SetLineEntry (const lldb_private::LineEntry &lldb_object_ref)
Private Attributes
std::unique_ptr< lldb_private::LineEntry > m_opaque_up
Friends
class SBAddress
class SBCompileUnit
class SBFrame
class SBSymbolContext
Detailed Description
Definition at line 18 of file SBLineEntry.h.
Constructor & Destructor Documentation
SBLineEntry() [1/3]
SBLineEntry::SBLineEntry ()
Definition at line 22 of file SBLineEntry.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by operator!=(), operator=(), operator==(), SBLineEntry(), and SBSymbolContext.
SBLineEntry() [2/3]
SBLineEntry::SBLineEntry (const lldb::SBLineEntry & rhs)
Definition at line 24 of file SBLineEntry.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBLineEntry().
~SBLineEntry()
SBLineEntry::~SBLineEntry () default
References get(), GetColumn(), GetDescription(), GetEndAddress(), GetFileSpec(), GetLine(), GetSameLineContiguousAddressRangeEnd(), GetStartAddress(), IsValid(), operator!=(), operator=(), operator==(), SetColumn(), SetFileSpec(), and SetLine().
SBLineEntry() [3/3]
SBLineEntry::SBLineEntry (const lldb_private::LineEntry * lldb_object_ptr) private
Definition at line 30 of file SBLineEntry.cpp.
References m_opaque_up.
Member Function Documentation
get()
lldb_private::LineEntry * SBLineEntry::get () protected
Definition at line 198 of file SBLineEntry.cpp.
References m_opaque_up.
Referenced by ~SBLineEntry().
GetColumn()
uint32_t SBLineEntry::GetColumn () const
Definition at line 115 of file SBLineEntry.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by GetDescription(), and ~SBLineEntry().
GetDescription()
bool SBLineEntry::GetDescription (lldb::SBStream & description)
Definition at line 181 of file SBLineEntry.cpp.
References GetColumn(), GetLine(), LLDB_INSTRUMENT_VA, m_opaque_up, PATH_MAX, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
Referenced by ~SBLineEntry().
GetEndAddress()
SBAddress SBLineEntry::GetEndAddress () const
Definition at line 59 of file SBLineEntry.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, lldb::SBAddress::OffsetAddress(), SBAddress, and lldb::SBAddress::SetAddress().
Referenced by ~SBLineEntry().
GetFileSpec()
SBFileSpec SBLineEntry::GetFileSpec () const
Definition at line 95 of file SBLineEntry.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBFileSpec::SetFileSpec().
Referenced by lldb::SBCompileUnit::FindLineEntryIndex(), and ~SBLineEntry().
GetLine()
uint32_t SBLineEntry::GetLine () const
Definition at line 105 of file SBLineEntry.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBCompileUnit::FindLineEntryIndex(), GetDescription(), and ~SBLineEntry().
GetSameLineContiguousAddressRangeEnd()
SBAddress SBLineEntry::GetSameLineContiguousAddressRangeEnd (bool include_inlined_functions) const
Definition at line 70 of file SBLineEntry.cpp.
References lldb_private::AddressRange::GetBaseAddress(), lldb_private::AddressRange::GetByteSize(), LLDB_INSTRUMENT_VA, m_opaque_up, lldb::SBAddress::OffsetAddress(), SBAddress, and lldb::SBAddress::SetAddress().
Referenced by ~SBLineEntry().
GetStartAddress()
SBAddress SBLineEntry::GetStartAddress () const
Definition at line 49 of file SBLineEntry.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, SBAddress, and lldb::SBAddress::SetAddress().
Referenced by ~SBLineEntry().
IsValid()
bool SBLineEntry::IsValid () const
Definition at line 85 of file SBLineEntry.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBCompileUnit::FindLineEntryIndex(), lldb::SBSymbolContext::SetLineEntry(), and ~SBLineEntry().
operator bool()
SBLineEntry::operator bool () const explicit
Definition at line 89 of file SBLineEntry.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
operator!=()
bool SBLineEntry::operator!= (const lldb::SBLineEntry & rhs) const
Definition at line 157 of file SBLineEntry.cpp.
References lldb_private::LineEntry::Compare(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBLineEntry().
Referenced by ~SBLineEntry().
operator->()
const lldb_private::LineEntry * SBLineEntry::operator-> () const private
Definition at line 169 of file SBLineEntry.cpp.
References m_opaque_up.
Referenced by SBSymbolContext.
operator=()
const SBLineEntry & SBLineEntry::operator= (const lldb::SBLineEntry & rhs)
Definition at line 35 of file SBLineEntry.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBLineEntry().
Referenced by ~SBLineEntry().
operator==()
bool SBLineEntry::operator== (const lldb::SBLineEntry & rhs) const
Definition at line 145 of file SBLineEntry.cpp.
References lldb_private::LineEntry::Compare(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBLineEntry().
Referenced by ~SBLineEntry().
ref() [1/2]
lldb_private::LineEntry & SBLineEntry::ref () private
Definition at line 173 of file SBLineEntry.cpp.
References m_opaque_up.
Referenced by lldb::SBCompileUnit::FindLineEntryIndex(), SBSymbolContext, SetColumn(), SetFileSpec(), SetLine(), and lldb::SBSymbolContext::SetLineEntry().
ref() [2/2]
const lldb_private::LineEntry & SBLineEntry::ref () const private
Definition at line 179 of file SBLineEntry.cpp.
References m_opaque_up.
SetColumn()
void SBLineEntry::SetColumn (uint32_t column)
Definition at line 139 of file SBLineEntry.cpp.
References lldb_private::LineEntry::column, LLDB_INSTRUMENT_VA, and ref().
Referenced by ~SBLineEntry().
SetFileSpec()
void SBLineEntry::SetFileSpec (lldb::SBFileSpec filespec)
Definition at line 123 of file SBLineEntry.cpp.
References lldb_private::LineEntry::file_sp, lldb::SBFileSpec::IsValid(), LLDB_INSTRUMENT_VA, lldb::SBFileSpec::ref(), and ref().
Referenced by ~SBLineEntry().
SetLine()
void SBLineEntry::SetLine (uint32_t line)
Definition at line 131 of file SBLineEntry.cpp.
References lldb_private::LineEntry::IsValid(), lldb_private::LineEntry::line, LLDB_INSTRUMENT_VA, ref(), and lldb_private::LineEntry::synthetic.
Referenced by ~SBLineEntry().
SetLineEntry()
void SBLineEntry::SetLineEntry (const lldb_private::LineEntry & lldb_object_ref) private
Definition at line 43 of file SBLineEntry.cpp.
References m_opaque_up.
Referenced by lldb::SBAddress::GetLineEntry(), lldb::SBSymbolContext::GetLineEntry(), lldb::SBCompileUnit::GetLineEntryAtIndex(), and SBSymbolContext.
Friends And Related Symbol Documentation
SBAddress
friend class SBAddress friend
Definition at line 61 of file SBLineEntry.h.
References SBAddress.
Referenced by GetEndAddress(), GetSameLineContiguousAddressRangeEnd(), GetStartAddress(), and SBAddress.
SBCompileUnit
friend class SBCompileUnit friend
Definition at line 62 of file SBLineEntry.h.
References SBCompileUnit.
Referenced by SBCompileUnit.
SBFrame
friend class SBFrame friend
Definition at line 63 of file SBLineEntry.h.
References SBFrame.
Referenced by SBFrame.
SBSymbolContext
friend class SBSymbolContext friend
Definition at line 64 of file SBLineEntry.h.
References operator->(), ref(), SBLineEntry(), SBSymbolContext, and SetLineEntry().
Referenced by SBSymbolContext.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::LineEntry> lldb::SBLineEntry::m_opaque_up private
Definition at line 76 of file SBLineEntry.h.
Referenced by get(), GetColumn(), GetDescription(), GetEndAddress(), GetFileSpec(), GetLine(), GetSameLineContiguousAddressRangeEnd(), GetStartAddress(), operator bool(), operator!=(), operator->(), operator=(), operator==(), ref(), ref(), SBLineEntry(), SBLineEntry(), and SetLineEntry().
The documentation for this class was generated from the following files:
SBLineEntry.h
SBLineEntry.cpp