LLDB: lldb::SBBreakpointName Class Reference
lldb::SBBreakpointName Class Reference
#include <SBBreakpointName.h>
Public Member Functions
SBBreakpointName ()
SBBreakpointName (SBTarget &target, const char *name)
SBBreakpointName (SBBreakpoint &bkpt, const char *name)
SBBreakpointName (const lldb::SBBreakpointName &rhs)
~SBBreakpointName ()
const lldb::SBBreakpointName & operator= (const lldb::SBBreakpointName &rhs)
bool operator== (const lldb::SBBreakpointName &rhs)
bool operator!= (const lldb::SBBreakpointName &rhs)
operator bool () const
bool IsValid () const
const char * GetName () const
void SetEnabled (bool enable)
bool IsEnabled ()
void SetOneShot (bool one_shot)
bool IsOneShot () const
void SetIgnoreCount (uint32_t count)
uint32_t GetIgnoreCount () const
void SetCondition (const char *condition)
const char * GetCondition ()
void SetAutoContinue (bool auto_continue)
bool GetAutoContinue ()
void SetThreadID (lldb::tid_t sb_thread_id)
lldb::tid_t GetThreadID ()
void SetThreadIndex (uint32_t index)
uint32_t GetThreadIndex () const
void SetThreadName (const char *thread_name)
const char * GetThreadName () const
void SetQueueName (const char *queue_name)
const char * GetQueueName () const
void SetCallback (SBBreakpointHitCallback callback, void *baton)
void SetScriptCallbackFunction (const char *callback_function_name)
SBError SetScriptCallbackFunction (const char *callback_function_name, SBStructuredData &extra_args)
void SetCommandLineCommands (lldb::SBStringList &commands)
bool GetCommandLineCommands (lldb::SBStringList &commands)
SBError SetScriptCallbackBody (const char *script_body_text)
const char * GetHelpString () const
void SetHelpString (const char *help_string)
bool GetAllowList () const
void SetAllowList (bool value)
bool GetAllowDelete ()
void SetAllowDelete (bool value)
bool GetAllowDisable ()
void SetAllowDisable (bool value)
bool GetDescription (lldb::SBStream &description)
Private Member Functions
lldb_private::BreakpointName * GetBreakpointName () const
void UpdateName (lldb_private::BreakpointName &bp_name)
Private Attributes
std::unique_ptr< SBBreakpointNameImpl > m_impl_up
Friends
class SBTarget
Detailed Description
Definition at line 18 of file SBBreakpointName.h.
Constructor & Destructor Documentation
SBBreakpointName() [1/4]
SBBreakpointName::SBBreakpointName ()
Definition at line 110 of file SBBreakpointName.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by operator=(), and SBBreakpointName().
SBBreakpointName() [2/4]
SBBreakpointName::SBBreakpointName (SBTarget & target, const char * name)
Definition at line 112 of file SBBreakpointName.cpp.
References GetBreakpointName(), LLDB_INSTRUMENT_VA, m_impl_up, and SBTarget.
SBBreakpointName() [3/4]
SBBreakpointName::SBBreakpointName (SBBreakpoint & bkpt, const char * name)
Definition at line 122 of file SBBreakpointName.cpp.
References lldb_private::Target::ConfigureBreakpointName(), GetBreakpointName(), lldb::SBBreakpoint::GetSP(), lldb::SBBreakpoint::IsValid(), LLDB_INSTRUMENT_VA, and m_impl_up.
SBBreakpointName() [4/4]
SBBreakpointName::SBBreakpointName (const lldb::SBBreakpointName & rhs)
Definition at line 147 of file SBBreakpointName.cpp.
References LLDB_INSTRUMENT_VA, m_impl_up, and SBBreakpointName().
~SBBreakpointName()
SBBreakpointName::~SBBreakpointName () default
References GetAllowDelete(), GetAllowDisable(), GetAllowList(), GetAutoContinue(), GetCommandLineCommands(), GetCondition(), GetDescription(), GetHelpString(), GetIgnoreCount(), GetQueueName(), GetThreadID(), GetThreadIndex(), GetThreadName(), IsEnabled(), IsOneShot(), IsValid(), operator!=(), operator=(), operator==(), SetAllowDelete(), SetAllowDisable(), SetAllowList(), SetAutoContinue(), SetCallback(), SetCommandLineCommands(), SetCondition(), SetEnabled(), SetHelpString(), SetIgnoreCount(), SetOneShot(), SetQueueName(), SetScriptCallbackBody(), SetScriptCallbackFunction(), SetThreadID(), SetThreadIndex(), and SetThreadName().
Member Function Documentation
GetAllowDelete()
bool SBBreakpointName::GetAllowDelete ()
Definition at line 629 of file SBBreakpointName.cpp.
References lldb_private::BreakpointName::Permissions::GetAllowDelete(), GetBreakpointName(), lldb_private::BreakpointName::GetPermissions(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointName().
GetAllowDisable()
bool SBBreakpointName::GetAllowDisable ()
Definition at line 647 of file SBBreakpointName.cpp.
References lldb_private::BreakpointName::Permissions::GetAllowDisable(), GetBreakpointName(), lldb_private::BreakpointName::GetPermissions(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointName().
GetAllowList()
bool SBBreakpointName::GetAllowList () const
Definition at line 611 of file SBBreakpointName.cpp.
References lldb_private::BreakpointName::Permissions::GetAllowList(), GetBreakpointName(), lldb_private::BreakpointName::GetPermissions(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointName().
GetAutoContinue()
bool SBBreakpointName::GetAutoContinue ()
Definition at line 339 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::BreakpointName::GetOptions(), lldb_private::BreakpointOptions::IsAutoContinue(), LLDB_INSTRUMENT_VA, and m_impl_up.
Referenced by ~SBBreakpointName().
GetBreakpointName()
lldb_private::BreakpointName * SBBreakpointName::GetBreakpointName () const private
Definition at line 665 of file SBBreakpointName.cpp.
References IsValid(), and m_impl_up.
Referenced by GetAllowDelete(), GetAllowDisable(), GetAllowList(), GetAutoContinue(), GetCommandLineCommands(), GetCondition(), GetDescription(), GetHelpString(), GetIgnoreCount(), GetQueueName(), GetThreadID(), GetThreadIndex(), GetThreadName(), IsEnabled(), IsOneShot(), SBBreakpointName(), SBBreakpointName(), SBTarget, SetAllowDelete(), SetAllowDisable(), SetAllowList(), SetAutoContinue(), SetCallback(), SetCommandLineCommands(), SetCondition(), SetEnabled(), SetHelpString(), SetIgnoreCount(), SetOneShot(), SetQueueName(), SetScriptCallbackBody(), SetScriptCallbackFunction(), SetThreadID(), SetThreadIndex(), and SetThreadName().
GetCommandLineCommands()
bool SBBreakpointName::GetCommandLineCommands (lldb::SBStringList & commands)
Definition at line 481 of file SBBreakpointName.cpp.
References lldb::SBStringList::AppendList(), GetBreakpointName(), lldb_private::BreakpointOptions::GetCommandLineCallbacks(), lldb_private::BreakpointName::GetOptions(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointName().
GetCondition()
const char * SBBreakpointName::GetCondition ()
Definition at line 311 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::BreakpointOptions::GetCondition(), lldb_private::ConstString::GetCString(), lldb_private::BreakpointName::GetOptions(), lldb_private::StopCondition::GetText(), LLDB_INSTRUMENT_VA, and m_impl_up.
Referenced by ~SBBreakpointName().
GetDescription()
bool SBBreakpointName::GetDescription (lldb::SBStream & description)
Definition at line 519 of file SBBreakpointName.cpp.
References lldb::eDescriptionLevelFull, lldb::SBStream::get(), GetBreakpointName(), lldb_private::BreakpointName::GetDescription(), LLDB_INSTRUMENT_VA, and m_impl_up.
Referenced by ~SBBreakpointName().
GetHelpString()
const char * SBBreakpointName::GetHelpString () const
Definition at line 496 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::ConstString::GetCString(), lldb_private::BreakpointName::GetHelp(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointName().
GetIgnoreCount()
uint32_t SBBreakpointName::GetIgnoreCount () const
Definition at line 284 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::BreakpointOptions::GetIgnoreCount(), lldb_private::BreakpointName::GetOptions(), LLDB_INSTRUMENT_VA, and m_impl_up.
Referenced by ~SBBreakpointName().
GetName()
const char * SBBreakpointName::GetName () const
Definition at line 197 of file SBBreakpointName.cpp.
References lldb_private::ConstString::GetCString(), LLDB_INSTRUMENT_VA, and m_impl_up.
GetQueueName()
const char * SBBreakpointName::GetQueueName () const
Definition at line 448 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::ConstString::GetCString(), lldb_private::BreakpointName::GetOptions(), lldb_private::ThreadSpec::GetQueueName(), lldb_private::BreakpointOptions::GetThreadSpec(), LLDB_INSTRUMENT_VA, and m_impl_up.
Referenced by ~SBBreakpointName().
GetThreadID()
lldb::tid_t SBBreakpointName::GetThreadID ()
Definition at line 366 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::BreakpointName::GetOptions(), lldb_private::BreakpointOptions::GetThreadSpec(), lldb_private::ThreadSpec::GetTID(), LLDB_INSTRUMENT_VA, LLDB_INVALID_THREAD_ID, and m_impl_up.
Referenced by ~SBBreakpointName().
GetThreadIndex()
uint32_t SBBreakpointName::GetThreadIndex () const
Definition at line 393 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::ThreadSpec::GetIndex(), lldb_private::BreakpointName::GetOptions(), lldb_private::BreakpointOptions::GetThreadSpec(), LLDB_INSTRUMENT_VA, LLDB_INVALID_THREAD_ID, and m_impl_up.
Referenced by ~SBBreakpointName().
GetThreadName()
const char * SBBreakpointName::GetThreadName () const
Definition at line 420 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::ConstString::GetCString(), lldb_private::ThreadSpec::GetName(), lldb_private::BreakpointName::GetOptions(), lldb_private::BreakpointOptions::GetThreadSpec(), LLDB_INSTRUMENT_VA, and m_impl_up.
Referenced by ~SBBreakpointName().
IsEnabled()
bool SBBreakpointName::IsEnabled ()
Definition at line 230 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::BreakpointName::GetOptions(), lldb_private::BreakpointOptions::IsEnabled(), LLDB_INSTRUMENT_VA, and m_impl_up.
Referenced by ~SBBreakpointName().
IsOneShot()
bool SBBreakpointName::IsOneShot () const
Definition at line 257 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::BreakpointName::GetOptions(), lldb_private::BreakpointOptions::IsOneShot(), LLDB_INSTRUMENT_VA, and m_impl_up.
Referenced by ~SBBreakpointName().
IsValid()
bool SBBreakpointName::IsValid () const
Definition at line 185 of file SBBreakpointName.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by GetBreakpointName(), UpdateName(), and ~SBBreakpointName().
operator bool()
SBBreakpointName::operator bool () const explicit
Definition at line 189 of file SBBreakpointName.cpp.
References LLDB_INSTRUMENT_VA, and m_impl_up.
operator!=()
bool SBBreakpointName::operator!= (const lldb::SBBreakpointName & rhs)
Definition at line 179 of file SBBreakpointName.cpp.
References LLDB_INSTRUMENT_VA, and m_impl_up.
Referenced by ~SBBreakpointName().
operator=()
const SBBreakpointName & SBBreakpointName::operator= (const lldb::SBBreakpointName & rhs)
Definition at line 159 of file SBBreakpointName.cpp.
References LLDB_INSTRUMENT_VA, m_impl_up, and SBBreakpointName().
Referenced by ~SBBreakpointName().
operator==()
bool SBBreakpointName::operator== (const lldb::SBBreakpointName & rhs)
Definition at line 173 of file SBBreakpointName.cpp.
References LLDB_INSTRUMENT_VA, and m_impl_up.
Referenced by ~SBBreakpointName().
SetAllowDelete()
void SBBreakpointName::SetAllowDelete (bool value)
Definition at line 638 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::BreakpointName::GetPermissions(), LLDB_INSTRUMENT_VA, and lldb_private::BreakpointName::Permissions::SetAllowDelete().
Referenced by ~SBBreakpointName().
SetAllowDisable()
void SBBreakpointName::SetAllowDisable (bool value)
Definition at line 656 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::BreakpointName::GetPermissions(), LLDB_INSTRUMENT_VA, and lldb_private::BreakpointName::Permissions::SetAllowDisable().
Referenced by ~SBBreakpointName().
SetAllowList()
void SBBreakpointName::SetAllowList (bool value)
Definition at line 620 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::BreakpointName::GetPermissions(), LLDB_INSTRUMENT_VA, and lldb_private::BreakpointName::Permissions::SetAllowList().
Referenced by ~SBBreakpointName().
SetAutoContinue()
void SBBreakpointName::SetAutoContinue (bool auto_continue)
Definition at line 325 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::BreakpointName::GetOptions(), LLDB_INSTRUMENT_VA, m_impl_up, lldb_private::BreakpointOptions::SetAutoContinue(), and UpdateName().
Referenced by ~SBBreakpointName().
SetCallback()
void SBBreakpointName::SetCallback (SBBreakpointHitCallback callback, void * baton)
Definition at line 535 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::BreakpointName::GetOptions(), LLDB_INSTRUMENT_VA, m_impl_up, lldb_private::BreakpointOptions::SetCallback(), and UpdateName().
Referenced by ~SBBreakpointName().
SetCommandLineCommands()
void SBBreakpointName::SetCommandLineCommands (lldb::SBStringList & commands)
Definition at line 462 of file SBBreakpointName.cpp.
References lldb::eScriptLanguageNone, GetBreakpointName(), lldb_private::BreakpointName::GetOptions(), lldb::SBStringList::GetSize(), LLDB_INSTRUMENT_VA, m_impl_up, lldb_private::BreakpointOptions::SetCommandDataCallback(), and UpdateName().
Referenced by ~SBBreakpointName().
SetCondition()
void SBBreakpointName::SetCondition (const char * condition)
Definition at line 297 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::BreakpointName::GetOptions(), LLDB_INSTRUMENT_VA, m_impl_up, lldb_private::BreakpointOptions::SetCondition(), and UpdateName().
Referenced by ~SBBreakpointName().
SetEnabled()
void SBBreakpointName::SetEnabled (bool enable)
Definition at line 205 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::BreakpointName::GetOptions(), LLDB_INSTRUMENT_VA, m_impl_up, lldb_private::BreakpointOptions::SetEnabled(), and UpdateName().
Referenced by ~SBBreakpointName().
SetHelpString()
void SBBreakpointName::SetHelpString (const char * help_string)
Definition at line 506 of file SBBreakpointName.cpp.
References GetBreakpointName(), LLDB_INSTRUMENT_VA, m_impl_up, and lldb_private::BreakpointName::SetHelp().
Referenced by ~SBBreakpointName().
SetIgnoreCount()
void SBBreakpointName::SetIgnoreCount (uint32_t count)
Definition at line 270 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::BreakpointName::GetOptions(), LLDB_INSTRUMENT_VA, m_impl_up, lldb_private::BreakpointOptions::SetIgnoreCount(), and UpdateName().
Referenced by ~SBBreakpointName().
SetOneShot()
void SBBreakpointName::SetOneShot (bool one_shot)
Definition at line 243 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::BreakpointName::GetOptions(), LLDB_INSTRUMENT_VA, m_impl_up, lldb_private::BreakpointOptions::SetOneShot(), and UpdateName().
Referenced by ~SBBreakpointName().
SetQueueName()
void SBBreakpointName::SetQueueName (const char * queue_name)
Definition at line 434 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::BreakpointName::GetOptions(), lldb_private::BreakpointOptions::GetThreadSpec(), LLDB_INSTRUMENT_VA, m_impl_up, lldb_private::ThreadSpec::SetQueueName(), and UpdateName().
Referenced by ~SBBreakpointName().
SetScriptCallbackBody()
SBError SBBreakpointName::SetScriptCallbackBody (const char * script_body_text)
Definition at line 587 of file SBBreakpointName.cpp.
References error(), lldb::SBError::Fail(), GetBreakpointName(), lldb_private::BreakpointName::GetOptions(), LLDB_INSTRUMENT_VA, m_impl_up, lldb::SBError::SetError(), and UpdateName().
Referenced by ~SBBreakpointName().
SetScriptCallbackFunction() [1/2]
void SBBreakpointName::SetScriptCallbackFunction (const char * callback_function_name)
Definition at line 553 of file SBBreakpointName.cpp.
References LLDB_INSTRUMENT_VA, and SetScriptCallbackFunction().
Referenced by SetScriptCallbackFunction(), and ~SBBreakpointName().
SetScriptCallbackFunction() [2/2]
SBError SBBreakpointName::SetScriptCallbackFunction (const char * callback_function_name, SBStructuredData & extra_args)
Definition at line 560 of file SBBreakpointName.cpp.
References error(), lldb_private::Status::FromErrorString(), GetBreakpointName(), lldb_private::BreakpointName::GetOptions(), LLDB_INSTRUMENT_VA, m_impl_up, lldb::SBStructuredData::m_impl_up, lldb::SBError::SetError(), and UpdateName().
SetThreadID()
void SBBreakpointName::SetThreadID (lldb::tid_t sb_thread_id)
Definition at line 352 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::BreakpointName::GetOptions(), LLDB_INSTRUMENT_VA, m_impl_up, lldb_private::BreakpointOptions::SetThreadID(), and UpdateName().
Referenced by ~SBBreakpointName().
SetThreadIndex()
void SBBreakpointName::SetThreadIndex (uint32_t index)
Definition at line 379 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::BreakpointName::GetOptions(), lldb_private::BreakpointOptions::GetThreadSpec(), LLDB_INSTRUMENT_VA, m_impl_up, lldb_private::ThreadSpec::SetIndex(), and UpdateName().
Referenced by ~SBBreakpointName().
SetThreadName()
void SBBreakpointName::SetThreadName (const char * thread_name)
Definition at line 406 of file SBBreakpointName.cpp.
References GetBreakpointName(), lldb_private::BreakpointName::GetOptions(), lldb_private::BreakpointOptions::GetThreadSpec(), LLDB_INSTRUMENT_VA, m_impl_up, lldb_private::ThreadSpec::SetName(), and UpdateName().
Referenced by ~SBBreakpointName().
UpdateName()
void SBBreakpointName::UpdateName (lldb_private::BreakpointName & bp_name) private
Definition at line 219 of file SBBreakpointName.cpp.
References IsValid(), and m_impl_up.
Referenced by SBTarget, SetAutoContinue(), SetCallback(), SetCommandLineCommands(), SetCondition(), SetEnabled(), SetIgnoreCount(), SetOneShot(), SetQueueName(), SetScriptCallbackBody(), SetScriptCallbackFunction(), SetThreadID(), SetThreadIndex(), and SetThreadName().
Friends And Related Symbol Documentation
SBTarget
friend class SBTarget friend
Definition at line 110 of file SBBreakpointName.h.
References GetBreakpointName(), SBTarget, and UpdateName().
Referenced by SBBreakpointName(), and SBTarget.
Member Data Documentation
m_impl_up
std::unique_ptr<SBBreakpointNameImpl> lldb::SBBreakpointName::m_impl_up private
Definition at line 115 of file SBBreakpointName.h.
Referenced by GetAutoContinue(), GetBreakpointName(), GetCondition(), GetDescription(), GetIgnoreCount(), GetName(), GetQueueName(), GetThreadID(), GetThreadIndex(), GetThreadName(), IsEnabled(), IsOneShot(), operator bool(), operator!=(), operator=(), operator==(), SBBreakpointName(), SBBreakpointName(), SBBreakpointName(), SetAutoContinue(), SetCallback(), SetCommandLineCommands(), SetCondition(), SetEnabled(), SetHelpString(), SetIgnoreCount(), SetOneShot(), SetQueueName(), SetScriptCallbackBody(), SetScriptCallbackFunction(), SetThreadID(), SetThreadIndex(), SetThreadName(), and UpdateName().
The documentation for this class was generated from the following files:
SBBreakpointName.h
SBBreakpointName.cpp