LLDB: lldb_private::CommandCompletions Class Reference
lldb_private::CommandCompletions Class Reference
#include <CommandCompletions.h>
Static Public Member Functions
static bool InvokeCommonCompletionCallbacks (CommandInterpreter &interpreter, uint32_t completion_mask, lldb_private::CompletionRequest &request, SearchFilter *searcher)
static void DiskFiles (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void DiskFiles (const llvm::Twine &partial_file_name, StringList &matches, TildeExpressionResolver &Resolver)
static void DiskDirectories (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void DiskDirectories (const llvm::Twine &partial_file_name, StringList &matches, TildeExpressionResolver &Resolver)
static void RemoteDiskFiles (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void RemoteDiskDirectories (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void SourceFiles (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void Modules (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void ModuleUUIDs (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void Symbols (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void SettingsNames (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void PlatformPluginNames (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void ArchitectureNames (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void VariablePath (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void Registers (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void Breakpoints (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void BreakpointNames (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void ProcessPluginNames (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void ProcessIDs (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void ProcessNames (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void DisassemblyFlavors (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void TypeLanguages (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void FrameIndexes (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void StopHookIDs (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void ThreadIndexes (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void WatchPointIDs (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void TypeCategoryNames (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void ThreadIDs (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void ManagedPlugins (CommandInterpreter &interpreter, CompletionRequest &request, SearchFilter *searcher)
static void CompleteModifiableCmdPathArgs (CommandInterpreter &interpreter, CompletionRequest &request, OptionElementVector &opt_element_vector)
This completer works for commands whose only arguments are a command path.
Detailed Description
Definition at line 25 of file CommandCompletions.h.
Member Function Documentation
ArchitectureNames()
void CommandCompletions::ArchitectureNames (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 620 of file CommandCompletions.cpp.
References lldb_private::ArchSpec::AutoComplete().
Referenced by InvokeCommonCompletionCallbacks().
BreakpointNames()
void CommandCompletions::BreakpointNames (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 683 of file CommandCompletions.cpp.
References lldb_private::CommandInterpreter::GetDebugger(), lldb_private::Debugger::GetSelectedTarget(), and lldb_private::CompletionRequest::TryCompleteCurrentArg().
Referenced by InvokeCommonCompletionCallbacks().
Breakpoints()
void CommandCompletions::Breakpoints (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 652 of file CommandCompletions.cpp.
References lldb::eDescriptionLevelBrief, lldb_private::BreakpointList::GetBreakpointAtIndex(), lldb_private::CommandInterpreter::GetDebugger(), lldb_private::Debugger::GetSelectedTarget(), lldb_private::BreakpointList::GetSize(), lldb_private::StreamString::GetString(), and lldb_private::CompletionRequest::TryCompleteCurrentArg().
Referenced by InvokeCommonCompletionCallbacks().
CompleteModifiableCmdPathArgs()
void CommandCompletions::CompleteModifiableCmdPathArgs (CommandInterpreter & interpreter, CompletionRequest & request, OptionElementVector & opt_element_vector) static
This completer works for commands whose only arguments are a command path.
It isn't tied to an argument type because it completes not on a single argument but on the sequence of arguments, so you have to invoke it by hand.
Definition at line 859 of file CommandCompletions.cpp.
References lldb_private::CompletionRequest::AddCompletions(), lldb_private::Args::DeleteArgumentAtIndex(), error(), lldb_private::Args::GetArgumentAtIndex(), lldb_private::Args::GetArgumentCount(), lldb_private::CompletionRequest::GetParsedLine(), lldb_private::StringList::GetSize(), lldb_private::CommandObjectMultiword::GetSubcommandObject(), lldb_private::CommandInterpreter::GetUserCommandObject(), and lldb_private::CommandInterpreter::VerifyUserMultiwordCmdPath().
Referenced by CommandObjectCommandsContainerAdd::HandleArgumentCompletion(), CommandObjectCommandsContainerDelete::HandleArgumentCompletion(), CommandObjectCommandsScriptAdd::HandleArgumentCompletion(), and CommandObjectCommandsScriptDelete::HandleArgumentCompletion().
DisassemblyFlavors()
void CommandCompletions::DisassemblyFlavors (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 703 of file CommandCompletions.cpp.
References lldb_private::CompletionRequest::TryCompleteCurrentArg().
Referenced by InvokeCommonCompletionCallbacks().
DiskDirectories() [1/2]
void CommandCompletions::DiskDirectories (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 516 of file CommandCompletions.cpp.
References DiskFilesOrDirectories().
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qPathComplete(), and InvokeCommonCompletionCallbacks().
DiskDirectories() [2/2]
void CommandCompletions::DiskDirectories (const llvm::Twine & partial_file_name, StringList & matches, TildeExpressionResolver & Resolver) static
Definition at line 522 of file CommandCompletions.cpp.
References DiskFilesOrDirectories().
DiskFiles() [1/2]
void CommandCompletions::DiskFiles (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 504 of file CommandCompletions.cpp.
References DiskFilesOrDirectories().
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qPathComplete(), and InvokeCommonCompletionCallbacks().
DiskFiles() [2/2]
void CommandCompletions::DiskFiles (const llvm::Twine & partial_file_name, StringList & matches, TildeExpressionResolver & Resolver) static
Definition at line 510 of file CommandCompletions.cpp.
References DiskFilesOrDirectories().
FrameIndexes()
void CommandCompletions::FrameIndexes (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 751 of file CommandCompletions.cpp.
References lldb_private::CommandInterpreter::GetDebugger(), lldb_private::CommandInterpreter::GetExecutionContext(), lldb_private::StreamString::GetString(), lldb_private::ExecutionContext::GetThreadSP(), lldb_private::ExecutionContext::HasProcessScope(), INTERRUPT_REQUESTED, and lldb_private::CompletionRequest::TryCompleteCurrentArg().
Referenced by InvokeCommonCompletionCallbacks().
InvokeCommonCompletionCallbacks()
bool CommandCompletions::InvokeCommonCompletionCallbacks (CommandInterpreter & interpreter, uint32_t completion_mask, lldb_private::CompletionRequest & request, SearchFilter * searcher) static
Definition at line 53 of file CommandCompletions.cpp.
References ArchitectureNames(), BreakpointNames(), Breakpoints(), CommonCompletionElement::callback, DisassemblyFlavors(), DiskDirectories(), DiskFiles(), lldb::eArchitectureCompletion, lldb::eBreakpointCompletion, lldb::eBreakpointNameCompletion, lldb::eDisassemblyFlavorCompletion, lldb::eDiskDirectoryCompletion, lldb::eDiskFileCompletion, lldb::eFrameIndexCompletion, lldb::eManagedPluginCompletion, lldb::eModuleCompletion, lldb::eModuleUUIDCompletion, lldb::eNoCompletion, lldb::ePlatformPluginCompletion, lldb::eProcessIDCompletion, lldb::eProcessNameCompletion, lldb::eProcessPluginCompletion, lldb::eRegisterCompletion, lldb::eRemoteDiskDirectoryCompletion, lldb::eRemoteDiskFileCompletion, lldb::eSettingsNameCompletion, lldb::eSourceFileCompletion, lldb::eStopHookIDCompletion, lldb::eSymbolCompletion, lldb::eTerminatorCompletion, lldb::eThreadIDCompletion, lldb::eThreadIndexCompletion, lldb::eTypeCategoryNameCompletion, lldb::eTypeLanguageCompletion, lldb::eVariablePathCompletion, lldb::eWatchpointIDCompletion, FrameIndexes(), ManagedPlugins(), Modules(), ModuleUUIDs(), PlatformPluginNames(), ProcessIDs(), ProcessNames(), ProcessPluginNames(), Registers(), RemoteDiskDirectories(), RemoteDiskFiles(), SettingsNames(), lldb_private::CompletionRequest::ShouldAddCompletions(), SourceFiles(), StopHookIDs(), Symbols(), ThreadIDs(), ThreadIndexes(), TypeCategoryNames(), TypeLanguages(), VariablePath(), and WatchPointIDs().
Referenced by lldb_private::OptionValueArch::AutoComplete(), lldb_private::OptionValueFileColonLine::AutoComplete(), lldb_private::OptionValueFileSpec::AutoComplete(), CommandObjectBreakpointDelete::HandleArgumentCompletion(), CommandObjectBreakpointEnable::HandleArgumentCompletion(), CommandObjectBreakpointModify::HandleArgumentCompletion(), CommandObjectBreakpointNameAdd::HandleArgumentCompletion(), CommandObjectBreakpointNameDelete::HandleArgumentCompletion(), CommandObjectBreakpointWrite::HandleArgumentCompletion(), CommandObjectPlatformGetFile::HandleArgumentCompletion(), CommandObjectPlatformInstall::HandleArgumentCompletion(), CommandObjectPlatformProcessLaunch::HandleArgumentCompletion(), CommandObjectPluginDisable::HandleArgumentCompletion(), CommandObjectPluginEnable::HandleArgumentCompletion(), CommandObjectPythonFunction::HandleArgumentCompletion(), CommandObjectRegisterWrite::HandleArgumentCompletion(), CommandObjectScriptingObjectRaw::HandleArgumentCompletion(), CommandObjectSettingsAppend::HandleArgumentCompletion(), CommandObjectSettingsClear::HandleArgumentCompletion(), CommandObjectSettingsInsertAfter::HandleArgumentCompletion(), CommandObjectSettingsInsertBefore::HandleArgumentCompletion(), CommandObjectSettingsList::HandleArgumentCompletion(), CommandObjectSettingsRemove::HandleArgumentCompletion(), CommandObjectSettingsReplace::HandleArgumentCompletion(), CommandObjectTargetModulesModuleAutoComplete::HandleArgumentCompletion(), CommandObjectTargetModulesSourceFileAutoComplete::HandleArgumentCompletion(), CommandObjectThreadException::HandleArgumentCompletion(), CommandObjectThreadInfo::HandleArgumentCompletion(), CommandObjectThreadSelect::HandleArgumentCompletion(), CommandObjectThreadSiginfo::HandleArgumentCompletion(), CommandObjectTraceLoad::HandleArgumentCompletion(), CommandObjectTraceSave::HandleArgumentCompletion(), CommandObjectWatchpointDelete::HandleArgumentCompletion(), CommandObjectWatchpointDisable::HandleArgumentCompletion(), CommandObjectWatchpointEnable::HandleArgumentCompletion(), CommandObjectWatchpointIgnore::HandleArgumentCompletion(), CommandObjectWatchpointModify::HandleArgumentCompletion(), lldb_private::CommandObject::HandleArgumentCompletion(), lldb_private::CommandObjectRegexCommand::HandleCompletion(), CommandObjectBreakpointRead::CommandOptions::HandleOptionArgumentCompletion(), lldb_private::Options::HandleOptionArgumentCompletion(), lldb_private::IOHandlerDelegate::IOHandlerComplete(), and CommandObjectPluginList::OutputJsonFormat().
ManagedPlugins()
void CommandCompletions::ManagedPlugins (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 852 of file CommandCompletions.cpp.
References lldb_private::PluginManager::AutoCompletePluginName(), and lldb_private::CompletionRequest::GetCursorArgumentPrefix().
Referenced by InvokeCommonCompletionCallbacks().
Modules()
void CommandCompletions::Modules (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 546 of file CommandCompletions.cpp.
References lldb_private::CommandInterpreter::GetDebugger(), and lldb_private::Debugger::GetSelectedTarget().
Referenced by InvokeCommonCompletionCallbacks().
ModuleUUIDs()
void CommandCompletions::ModuleUUIDs (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 560 of file CommandCompletions.cpp.
References lldb_private::Continue, lldb_private::ModuleList::ForEach(), lldb_private::CommandInterpreter::GetExecutionContext(), lldb_private::Target::GetImages(), lldb_private::StreamString::GetString(), lldb_private::ExecutionContext::GetTargetPtr(), lldb_private::ExecutionContext::HasTargetScope(), and lldb_private::CompletionRequest::TryCompleteCurrentArg().
Referenced by InvokeCommonCompletionCallbacks().
PlatformPluginNames()
void CommandCompletions::PlatformPluginNames (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 613 of file CommandCompletions.cpp.
References lldb_private::PluginManager::AutoCompletePlatformName(), and lldb_private::CompletionRequest::GetCursorArgumentPrefix().
Referenced by CommandObjectPlatformSelect::HandleCompletion(), and InvokeCommonCompletionCallbacks().
ProcessIDs()
void CommandCompletions::ProcessIDs (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 714 of file CommandCompletions.cpp.
References lldb_private::CommandInterpreter::GetPlatform(), and lldb_private::CompletionRequest::TryCompleteCurrentArg().
Referenced by InvokeCommonCompletionCallbacks().
ProcessNames()
void CommandCompletions::ProcessNames (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 728 of file CommandCompletions.cpp.
References lldb_private::CommandInterpreter::GetPlatform(), and lldb_private::CompletionRequest::TryCompleteCurrentArg().
Referenced by InvokeCommonCompletionCallbacks().
ProcessPluginNames()
void CommandCompletions::ProcessPluginNames (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 697 of file CommandCompletions.cpp.
References lldb_private::PluginManager::AutoCompleteProcessName(), and lldb_private::CompletionRequest::GetCursorArgumentPrefix().
Referenced by InvokeCommonCompletionCallbacks().
Registers()
void CommandCompletions::Registers (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 632 of file CommandCompletions.cpp.
References lldb_private::RegisterInfo::alt_name, lldb_private::CompletionRequest::GetCursorArgumentPrefix(), lldb_private::CommandInterpreter::GetExecutionContext(), lldb_private::ExecutionContext::GetRegisterContext(), lldb_private::RegisterContext::GetRegisterCount(), lldb_private::RegisterContext::GetRegisterInfoAtIndex(), lldb_private::RegisterInfo::name, and lldb_private::CompletionRequest::TryCompleteCurrentArg().
Referenced by InvokeCommonCompletionCallbacks().
RemoteDiskDirectories()
void CommandCompletions::RemoteDiskDirectories (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 537 of file CommandCompletions.cpp.
References lldb_private::CommandInterpreter::GetDebugger(), lldb_private::Debugger::GetPlatformList(), and lldb_private::PlatformList::GetSelectedPlatform().
Referenced by InvokeCommonCompletionCallbacks().
RemoteDiskFiles()
void CommandCompletions::RemoteDiskFiles (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 528 of file CommandCompletions.cpp.
References lldb_private::CommandInterpreter::GetDebugger(), lldb_private::Debugger::GetPlatformList(), and lldb_private::PlatformList::GetSelectedPlatform().
Referenced by InvokeCommonCompletionCallbacks().
SettingsNames()
void CommandCompletions::SettingsNames (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 592 of file CommandCompletions.cpp.
References lldb_private::OptionValue::eDumpOptionName, lldb_private::CommandInterpreter::GetDebugger(), lldb_private::StringList::GetSize(), lldb_private::StreamString::GetString(), lldb_private::Properties::GetValueProperties(), lldb_private::StringList::SplitIntoLines(), and lldb_private::CompletionRequest::TryCompleteCurrentArg().
Referenced by InvokeCommonCompletionCallbacks().
SourceFiles()
void CommandCompletions::SourceFiles (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 332 of file CommandCompletions.cpp.
References lldb_private::CommandInterpreter::GetDebugger(), and lldb_private::Debugger::GetSelectedTarget().
Referenced by InvokeCommonCompletionCallbacks().
StopHookIDs()
void CommandCompletions::StopHookIDs (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 772 of file CommandCompletions.cpp.
References lldb::eDescriptionLevelInitial, lldb_private::CommandInterpreter::GetExecutionContext(), lldb_private::StreamString::GetString(), lldb_private::ExecutionContext::GetTargetSP(), lldb_private::Stream::SetIndentLevel(), and lldb_private::CompletionRequest::TryCompleteCurrentArg().
Referenced by InvokeCommonCompletionCallbacks().
Symbols()
void CommandCompletions::Symbols (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 578 of file CommandCompletions.cpp.
References lldb_private::CommandInterpreter::GetDebugger(), and lldb_private::Debugger::GetSelectedTarget().
Referenced by InvokeCommonCompletionCallbacks().
ThreadIDs()
void CommandCompletions::ThreadIDs (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 835 of file CommandCompletions.cpp.
References lldb_private::CommandInterpreter::GetExecutionContext(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::StreamString::GetString(), lldb_private::ThreadList::GetThreadAtIndex(), lldb_private::Process::GetThreadList(), lldb_private::ExecutionContext::HasProcessScope(), and lldb_private::CompletionRequest::TryCompleteCurrentArg().
Referenced by InvokeCommonCompletionCallbacks().
ThreadIndexes()
void CommandCompletions::ThreadIndexes (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 791 of file CommandCompletions.cpp.
References lldb_private::CommandInterpreter::GetExecutionContext(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::StreamString::GetString(), lldb_private::ThreadList::GetThreadAtIndex(), lldb_private::Process::GetThreadList(), lldb_private::ExecutionContext::HasProcessScope(), and lldb_private::CompletionRequest::TryCompleteCurrentArg().
Referenced by InvokeCommonCompletionCallbacks().
TypeCategoryNames()
void CommandCompletions::TypeCategoryNames (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 824 of file CommandCompletions.cpp.
References lldb_private::DataVisualization::Categories::ForEach(), and lldb_private::CompletionRequest::TryCompleteCurrentArg().
Referenced by InvokeCommonCompletionCallbacks().
TypeLanguages()
void CommandCompletions::TypeLanguages (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 741 of file CommandCompletions.cpp.
References lldb_private::bit(), lldb_private::Language::GetLanguagesSupportingTypeSystems(), lldb_private::Language::GetNameForLanguageType(), and lldb_private::CompletionRequest::TryCompleteCurrentArg().
Referenced by InvokeCommonCompletionCallbacks().
VariablePath()
void CommandCompletions::VariablePath (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 626 of file CommandCompletions.cpp.
References lldb_private::Variable::AutoComplete(), and lldb_private::CommandInterpreter::GetExecutionContext().
Referenced by InvokeCommonCompletionCallbacks().
WatchPointIDs()
void CommandCompletions::WatchPointIDs (CommandInterpreter & interpreter, CompletionRequest & request, SearchFilter * searcher) static
Definition at line 808 of file CommandCompletions.cpp.
References lldb_private::CommandInterpreter::GetExecutionContext(), lldb_private::StreamString::GetString(), lldb_private::ExecutionContext::GetTargetPtr(), lldb_private::Target::GetWatchpointList(), lldb_private::ExecutionContext::HasTargetScope(), lldb_private::CompletionRequest::TryCompleteCurrentArg(), and lldb_private::WatchpointList::Watchpoints().
Referenced by InvokeCommonCompletionCallbacks().
The documentation for this class was generated from the following files:
CommandCompletions.h
CommandCompletions.cpp