LLDB: lldb_private::BreakpointName::Permissions Class Reference
lldb_private::BreakpointName::Permissions Class Reference
#include <BreakpointName.h>
Public Types
enum PermissionKinds { listPerm = 0 , disablePerm = 1 , deletePerm = 2 , allPerms = 3 }
Public Member Functions
Permissions (bool in_list, bool in_disable, bool in_delete)
Permissions (const Permissions &rhs)
Permissions ()
const Permissions & operator= (const Permissions &rhs)
void Clear ()
void MergeInto (const Permissions &incoming)
bool GetAllowList () const
bool SetAllowList (bool value)
bool GetAllowDelete () const
bool SetAllowDelete (bool value)
bool GetAllowDisable () const
bool SetAllowDisable (bool value)
bool GetPermission (enum PermissionKinds permission) const
bool GetDescription (Stream *s, lldb::DescriptionLevel level)
bool IsSet (enum PermissionKinds permission) const
bool AnySet ()
Private Member Functions
bool SetPermission (enum PermissionKinds permission, bool value)
void MergePermission (const Permissions &incoming, enum PermissionKinds permission)
Private Attributes
bool m_permissions [allPerms]
Flags m_set_mask
Static Private Attributes
static const Flags::ValueType permissions_mask [allPerms+1]
Detailed Description
Definition at line 32 of file BreakpointName.h.
Member Enumeration Documentation
PermissionKinds
enum lldb_private::BreakpointName::Permissions::PermissionKinds
Enumerator
listPerm
disablePerm
deletePerm
allPerms
Definition at line 35 of file BreakpointName.h.
Constructor & Destructor Documentation
Permissions() [1/3]
lldb_private::BreakpointName::Permissions::Permissions (bool in_list, bool in_disable, bool in_delete) inline
Definition at line 42 of file BreakpointName.h.
References allPerms, deletePerm, disablePerm, listPerm, m_permissions, m_set_mask, and permissions_mask.
Referenced by MergeInto(), MergePermission(), operator=(), and Permissions().
Permissions() [2/3]
lldb_private::BreakpointName::Permissions::Permissions (const Permissions & rhs) inline
Definition at line 49 of file BreakpointName.h.
References deletePerm, disablePerm, listPerm, m_permissions, m_set_mask, and Permissions().
Permissions() [3/3]
lldb_private::BreakpointName::Permissions::Permissions () inline
Definition at line 57 of file BreakpointName.h.
References deletePerm, disablePerm, listPerm, m_permissions, and m_set_mask.
Referenced by Clear().
Member Function Documentation
AnySet()
bool lldb_private::BreakpointName::Permissions::AnySet () inline
Definition at line 111 of file BreakpointName.h.
References allPerms, m_set_mask, and permissions_mask.
Referenced by GetDescription().
Clear()
void lldb_private::BreakpointName::Permissions::Clear () inline
Definition at line 75 of file BreakpointName.h.
References Permissions().
GetAllowDelete()
bool lldb_private::BreakpointName::Permissions::GetAllowDelete () const inline
Definition at line 91 of file BreakpointName.h.
References deletePerm, and GetPermission().
Referenced by lldb_private::Breakpoint::AllowDelete(), lldb::SBBreakpointName::GetAllowDelete(), and GetDescription().
GetAllowDisable()
bool lldb_private::BreakpointName::Permissions::GetAllowDisable () const inline
Definition at line 94 of file BreakpointName.h.
References disablePerm, and GetPermission().
Referenced by lldb_private::Breakpoint::AllowDisable(), lldb::SBBreakpointName::GetAllowDisable(), and GetDescription().
GetAllowList()
bool lldb_private::BreakpointName::Permissions::GetAllowList () const inline
Definition at line 88 of file BreakpointName.h.
References GetPermission(), and listPerm.
Referenced by lldb_private::Breakpoint::AllowList(), lldb::SBBreakpointName::GetAllowList(), and GetDescription().
GetDescription()
bool BreakpointName::Permissions::GetDescription (Stream * s, lldb::DescriptionLevel level)
Definition at line 27 of file BreakpointName.cpp.
References AnySet(), deletePerm, disablePerm, GetAllowDelete(), GetAllowDisable(), GetAllowList(), lldb_private::Stream::Indent(), lldb_private::Stream::IndentLess(), lldb_private::Stream::IndentMore(), IsSet(), listPerm, and lldb_private::Stream::Printf().
Referenced by lldb_private::BreakpointName::GetDescription().
GetPermission()
bool lldb_private::BreakpointName::Permissions::GetPermission (enum PermissionKinds permission) const inline
Definition at line 99 of file BreakpointName.h.
References m_permissions.
Referenced by GetAllowDelete(), GetAllowDisable(), and GetAllowList().
IsSet()
bool lldb_private::BreakpointName::Permissions::IsSet (enum PermissionKinds permission) const inline
Definition at line 106 of file BreakpointName.h.
References m_set_mask, and permissions_mask.
Referenced by GetDescription(), and MergePermission().
MergeInto()
void lldb_private::BreakpointName::Permissions::MergeInto (const Permissions & incoming) inline
Definition at line 81 of file BreakpointName.h.
References deletePerm, disablePerm, listPerm, MergePermission(), and Permissions().
Referenced by lldb_private::Target::ConfigureBreakpointName().
MergePermission()
void lldb_private::BreakpointName::Permissions::MergePermission (const Permissions & incoming, enum PermissionKinds permission) inline private
Definition at line 130 of file BreakpointName.h.
References IsSet(), m_permissions, Permissions(), and SetPermission().
Referenced by MergeInto().
operator=()
const Permissions & lldb_private::BreakpointName::Permissions::operator= (const Permissions & rhs) inline
Definition at line 64 of file BreakpointName.h.
References deletePerm, disablePerm, listPerm, m_permissions, m_set_mask, and Permissions().
SetAllowDelete()
bool lldb_private::BreakpointName::Permissions::SetAllowDelete (bool value) inline
Definition at line 92 of file BreakpointName.h.
References deletePerm, and SetPermission().
Referenced by lldb::SBBreakpointName::SetAllowDelete().
SetAllowDisable()
bool lldb_private::BreakpointName::Permissions::SetAllowDisable (bool value) inline
Definition at line 95 of file BreakpointName.h.
References disablePerm, and SetPermission().
Referenced by lldb::SBBreakpointName::SetAllowDisable().
SetAllowList()
bool lldb_private::BreakpointName::Permissions::SetAllowList (bool value) inline
Definition at line 89 of file BreakpointName.h.
References listPerm, and SetPermission().
Referenced by lldb::SBBreakpointName::SetAllowList().
SetPermission()
bool lldb_private::BreakpointName::Permissions::SetPermission (enum PermissionKinds permission, bool value) inline private
Definition at line 121 of file BreakpointName.h.
References m_permissions, m_set_mask, and permissions_mask.
Referenced by MergePermission(), SetAllowDelete(), SetAllowDisable(), and SetAllowList().
Member Data Documentation
m_permissions
bool lldb_private::BreakpointName::Permissions::m_permissions[allPerms] private
Definition at line 118 of file BreakpointName.h.
Referenced by GetPermission(), MergePermission(), operator=(), Permissions(), Permissions(), Permissions(), and SetPermission().
m_set_mask
Flags lldb_private::BreakpointName::Permissions::m_set_mask private
Definition at line 119 of file BreakpointName.h.
Referenced by AnySet(), IsSet(), operator=(), Permissions(), Permissions(), Permissions(), and SetPermission().
permissions_mask
const Flags::ValueType BreakpointName::Permissions::permissions_mask static private
Initial value:
= {
        (1u << 0), (1u << 1), (1u << 2), (0x5u)}
Definition at line 116 of file BreakpointName.h.
Referenced by AnySet(), IsSet(), Permissions(), and SetPermission().
The documentation for this class was generated from the following files:
BreakpointName.h
BreakpointName.cpp