LLDB: RegisterContextDarwin_arm64 Class Reference
RegisterContextDarwin_arm64 Class Reference abstract
#include <RegisterContextDarwin_arm64.h>
Classes
struct DBG
struct EXC
struct FPU
struct GPR
struct VReg
Public Member Functions
RegisterContextDarwin_arm64 (lldb_private::Thread &thread, uint32_t concrete_frame_idx)
~RegisterContextDarwin_arm64 () override
void InvalidateAllRegisters () override
size_t GetRegisterCount () override
const lldb_private::RegisterInfo * GetRegisterInfoAtIndex (size_t reg) override
size_t GetRegisterSetCount () override
const lldb_private::RegisterSet * GetRegisterSet (size_t set) override
bool ReadRegister (const lldb_private::RegisterInfo *reg_info, lldb_private::RegisterValue &reg_value) override
bool WriteRegister (const lldb_private::RegisterInfo *reg_info, const lldb_private::RegisterValue &reg_value) override
bool ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp) override
bool WriteAllRegisterValues (const lldb::DataBufferSP &data_sp) override
uint32_t ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num) override
Convert from a given register numbering scheme to the lldb register numbering scheme.
uint32_t NumSupportedHardwareWatchpoints () override
uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, bool read, bool write) override
bool ClearHardwareWatchpoint (uint32_t hw_index) override
Public Member Functions inherited from lldb_private::RegisterContext
RegisterContext (Thread &thread, uint32_t concrete_frame_idx)
~RegisterContext () override
void InvalidateIfNeeded (bool force)
virtual lldb::ByteOrder GetByteOrder ()
virtual bool RegisterWriteCausesReconfigure (const llvm::StringRef name)
virtual bool ReconfigureRegisterInfo ()
virtual bool ReadAllRegisterValues (lldb_private::RegisterCheckpoint &reg_checkpoint)
virtual bool WriteAllRegisterValues (const lldb_private::RegisterCheckpoint &reg_checkpoint)
bool CopyFromRegisterContext (lldb::RegisterContextSP context)
virtual uint32_t NumSupportedHardwareBreakpoints ()
virtual uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual bool ClearHardwareBreakpoint (uint32_t hw_idx)
virtual bool HardwareSingleStep (bool enable)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, uint32_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, uint32_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual Thread & GetThread ()
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num)
uint64_t GetPC (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetThreadPointer (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool GetPCForSymbolication (Address &address)
Get an address suitable for symbolication.
bool SetPC (uint64_t pc)
bool SetPC (Address addr)
uint64_t GetSP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetSP (uint64_t sp)
uint64_t GetFP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetFP (uint64_t fp)
const char * GetRegisterName (uint32_t reg)
uint64_t GetReturnAddress (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetFlags (uint64_t fail_value=0)
uint64_t ReadRegisterAsUnsigned (uint32_t reg, uint64_t fail_value)
uint64_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, uint64_t fail_value)
bool WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
bool WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
bool ConvertBetweenRegisterKinds (lldb::RegisterKind source_rk, uint32_t source_regnum, lldb::RegisterKind target_rk, uint32_t &target_regnum)
lldb::TargetSP CalculateTarget () override
lldb::ProcessSP CalculateProcess () override
lldb::ThreadSP CalculateThread () override
lldb::StackFrameSP CalculateStackFrame () override
void CalculateExecutionContext (ExecutionContext &exe_ctx) override
Reconstruct the object's execution context into sc.
uint32_t GetStopID () const
void SetStopID (uint32_t stop_id)
Public Member Functions inherited from lldb_private::ExecutionContextScope
virtual ~ExecutionContextScope ()=default
Static Public Member Functions
static void LogDBGRegisters (lldb_private::Log *log, const DBG &dbg)
Protected Types
enum { GPRRegSet = 6 , FPURegSet = 17 , EXCRegSet = 7 , DBGRegSet = 15 }
enum { GPRWordCount = sizeof(GPR) / sizeof(uint32_t) , FPUWordCount = sizeof(FPU) / sizeof(uint32_t) , EXCWordCount , DBGWordCount = sizeof(DBG) / sizeof(uint32_t) }
enum { Read = 0 , Write = 1 , kNumErrors = 2 }
Protected Member Functions
void InvalidateAllRegisterStates ()
int GetError (int flavor, uint32_t err_idx) const
bool SetError (int flavor, uint32_t err_idx, int err)
bool RegisterSetIsCached (int set) const
int ReadGPR (bool force)
int ReadFPU (bool force)
int ReadEXC (bool force)
int ReadDBG (bool force)
int WriteGPR ()
int WriteFPU ()
int WriteEXC ()
int WriteDBG ()
virtual int DoReadGPR (lldb::tid_t tid, int flavor, GPR &gpr)
virtual int DoReadFPU (lldb::tid_t tid, int flavor, FPU &fpu)=0
virtual int DoReadEXC (lldb::tid_t tid, int flavor, EXC &exc)=0
virtual int DoReadDBG (lldb::tid_t tid, int flavor, DBG &dbg)=0
virtual int DoWriteGPR (lldb::tid_t tid, int flavor, const GPR &gpr)=0
virtual int DoWriteFPU (lldb::tid_t tid, int flavor, const FPU &fpu)=0
virtual int DoWriteEXC (lldb::tid_t tid, int flavor, const EXC &exc)=0
virtual int DoWriteDBG (lldb::tid_t tid, int flavor, const DBG &dbg)=0
int ReadRegisterSet (uint32_t set, bool force)
int WriteRegisterSet (uint32_t set)
Protected Member Functions inherited from lldb_private::RegisterContext
virtual bool BehavesLikeZerothFrame () const
Indicates that this frame is currently executing code, that the PC value is not a return-pc but an actual executing instruction.
Static Protected Member Functions
static uint32_t GetRegisterNumber (uint32_t reg_kind, uint32_t reg_num)
static int GetSetForNativeRegNum (int reg_num)
static size_t GetRegisterInfosCount ()
static const lldb_private::RegisterInfo * GetRegisterInfos ()
Protected Attributes
GPR gpr
FPU fpu
EXC exc
DBG dbg
int gpr_errs [2]
int fpu_errs [2]
int exc_errs [2]
int dbg_errs [2]
Protected Attributes inherited from lldb_private::RegisterContext
Thread & m_thread
uint32_t m_concrete_frame_idx
uint32_t m_stop_id
Detailed Description
Definition at line 28 of file RegisterContextDarwin_arm64.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
GPRRegSet
FPURegSet
EXCRegSet
DBGRegSet
Definition at line 105 of file RegisterContextDarwin_arm64.h.
anonymous enum
anonymous enum protected
Enumerator
Read
Write
kNumErrors
Definition at line 120 of file RegisterContextDarwin_arm64.h.
anonymous enum
anonymous enum protected
Enumerator
GPRWordCount
FPUWordCount
EXCWordCount
DBGWordCount
Definition at line 112 of file RegisterContextDarwin_arm64.h.
Constructor & Destructor Documentation
RegisterContextDarwin_arm64()
RegisterContextDarwin_arm64::RegisterContextDarwin_arm64 (lldb_private::Thread & thread, uint32_t concrete_frame_idx)
Definition at line 95 of file RegisterContextDarwin_arm64.cpp.
References dbg, exc, exc_errs, fpu, fpu_errs, gpr, gpr_errs, kNumErrors, and lldb_private::RegisterContext::RegisterContext().
Referenced by RegisterContextDarwin_arm64_Mach::RegisterContextDarwin_arm64_Mach(), and RegisterContextKDP_arm64::RegisterContextKDP_arm64().
~RegisterContextDarwin_arm64()
RegisterContextDarwin_arm64::~RegisterContextDarwin_arm64 () override default
Member Function Documentation
ClearHardwareWatchpoint()
bool RegisterContextDarwin_arm64::ClearHardwareWatchpoint (uint32_t hw_index) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 1018 of file RegisterContextDarwin_arm64.cpp.
References dbg, KERN_SUCCESS, NumSupportedHardwareWatchpoints(), ReadDBG(), and WriteDBG().
ConvertRegisterKindToRegisterNumber()
uint32_t RegisterContextDarwin_arm64::ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num) override virtual
Convert from a given register numbering scheme to the lldb register numbering scheme.
There may be multiple ways to enumerate the registers for a given architecture. ABI references will specify one to be used with DWARF, the register numberings from process plugin, there may be a variation used for eh_frame unwind instructions (e.g. on Darwin), and so on. Register 5 by itself is meaningless - RegisterKind enumeration tells you what context that number should be translated as.
Inside lldb, register numbers are in the eRegisterKindLLDB scheme; arguments which take a register number should take one in that scheme.
eRegisterKindGeneric is a special numbering scheme which gives us constant values for the pc, frame register, stack register, etc., for use within lldb. They may not be defined for all architectures but it allows generic code to translate these common registers into the lldb numbering scheme.
This method translates a given register kind + register number into the eRegisterKindLLDB register numbering.
Parameters
[in] kind The register numbering scheme (RegisterKind) that the following register number is in.
[in] num A register number in the 'kind' register numbering scheme.
Returns
The equivalent register number in the eRegisterKindLLDB numbering scheme, if possible, else LLDB_INVALID_REGNUM.
Reimplemented from lldb_private::RegisterContext.
Definition at line 685 of file RegisterContextDarwin_arm64.cpp.
References arm64_dwarf::cpsr, arm64_ehframe::cpsr, lldb::eRegisterKindDWARF, lldb::eRegisterKindEHFrame, lldb::eRegisterKindGeneric, lldb::eRegisterKindLLDB, arm64_dwarf::fp, arm64_ehframe::fp, gpr_cpsr, gpr_lr, gpr_pc, gpr_sp, gpr_x0, gpr_x1, gpr_x10, gpr_x11, gpr_x12, gpr_x13, gpr_x14, gpr_x15, gpr_x16, gpr_x17, gpr_x18, gpr_x19, gpr_x2, gpr_x20, gpr_x21, gpr_x22, gpr_x23, gpr_x24, gpr_x25, gpr_x26, gpr_x27, gpr_x28, gpr_x3, gpr_x4, gpr_x5, gpr_x6, gpr_x7, gpr_x8, gpr_x9, LLDB_INVALID_REGNUM, LLDB_REGNUM_GENERIC_FLAGS, LLDB_REGNUM_GENERIC_FP, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_RA, LLDB_REGNUM_GENERIC_SP, arm64_dwarf::lr, arm64_ehframe::lr, arm64_dwarf::pc, arm64_ehframe::pc, arm64_dwarf::sp, arm64_ehframe::sp, arm64_dwarf::v0, arm64_dwarf::v1, arm64_dwarf::v10, arm64_dwarf::v11, arm64_dwarf::v12, arm64_dwarf::v13, arm64_dwarf::v14, arm64_dwarf::v15, arm64_dwarf::v16, arm64_dwarf::v17, arm64_dwarf::v18, arm64_dwarf::v19, arm64_dwarf::v2, arm64_dwarf::v20, arm64_dwarf::v21, arm64_dwarf::v22, arm64_dwarf::v23, arm64_dwarf::v24, arm64_dwarf::v25, arm64_dwarf::v26, arm64_dwarf::v27, arm64_dwarf::v28, arm64_dwarf::v29, arm64_dwarf::v3, arm64_dwarf::v30, arm64_dwarf::v31, arm64_dwarf::v4, arm64_dwarf::v5, arm64_dwarf::v6, arm64_dwarf::v7, arm64_dwarf::v8, arm64_dwarf::v9, arm64_dwarf::x0, arm64_ehframe::x0, arm64_dwarf::x1, arm64_ehframe::x1, arm64_dwarf::x10, arm64_ehframe::x10, arm64_dwarf::x11, arm64_ehframe::x11, arm64_dwarf::x12, arm64_ehframe::x12, arm64_dwarf::x13, arm64_ehframe::x13, arm64_dwarf::x14, arm64_ehframe::x14, arm64_dwarf::x15, arm64_ehframe::x15, arm64_dwarf::x16, arm64_ehframe::x16, arm64_dwarf::x17, arm64_ehframe::x17, arm64_dwarf::x18, arm64_ehframe::x18, arm64_dwarf::x19, arm64_ehframe::x19, arm64_dwarf::x2, arm64_ehframe::x2, arm64_dwarf::x20, arm64_ehframe::x20, arm64_dwarf::x21, arm64_ehframe::x21, arm64_dwarf::x22, arm64_ehframe::x22, arm64_dwarf::x23, arm64_ehframe::x23, arm64_dwarf::x24, arm64_ehframe::x24, arm64_dwarf::x25, arm64_ehframe::x25, arm64_dwarf::x26, arm64_ehframe::x26, arm64_dwarf::x27, arm64_ehframe::x27, arm64_dwarf::x28, arm64_ehframe::x28, arm64_dwarf::x3, arm64_ehframe::x3, arm64_dwarf::x4, arm64_ehframe::x4, arm64_dwarf::x5, arm64_ehframe::x5, arm64_dwarf::x6, arm64_ehframe::x6, arm64_dwarf::x7, arm64_ehframe::x7, arm64_dwarf::x8, arm64_ehframe::x8, arm64_dwarf::x9, and arm64_ehframe::x9.
DoReadDBG()
virtual int RegisterContextDarwin_arm64::DoReadDBG (lldb::tid_t tid, int flavor, DBG & dbg) protected pure virtual
Implemented in RegisterContextDarwin_arm64_Mach, and RegisterContextKDP_arm64.
References dbg.
Referenced by ReadDBG().
DoReadEXC()
virtual int RegisterContextDarwin_arm64::DoReadEXC (lldb::tid_t tid, int flavor, EXC & exc) protected pure virtual
Implemented in RegisterContextDarwin_arm64_Mach, and RegisterContextKDP_arm64.
References exc.
Referenced by ReadEXC().
DoReadFPU()
virtual int RegisterContextDarwin_arm64::DoReadFPU (lldb::tid_t tid, int flavor, FPU & fpu) protected pure virtual
Implemented in RegisterContextDarwin_arm64_Mach, and RegisterContextKDP_arm64.
References fpu.
Referenced by ReadFPU().
DoReadGPR()
virtual int RegisterContextDarwin_arm64::DoReadGPR (lldb::tid_t tid, int flavor, GPR & gpr) inline protected virtual
Reimplemented in RegisterContextDarwin_arm64_Mach, and RegisterContextKDP_arm64.
Definition at line 202 of file RegisterContextDarwin_arm64.h.
References gpr.
Referenced by ReadGPR().
DoWriteDBG()
virtual int RegisterContextDarwin_arm64::DoWriteDBG (lldb::tid_t tid, int flavor, const DBG & dbg) protected pure virtual
Implemented in RegisterContextDarwin_arm64_Mach, and RegisterContextKDP_arm64.
References dbg.
Referenced by WriteDBG().
DoWriteEXC()
virtual int RegisterContextDarwin_arm64::DoWriteEXC (lldb::tid_t tid, int flavor, const EXC & exc) protected pure virtual
Implemented in RegisterContextDarwin_arm64_Mach, and RegisterContextKDP_arm64.
References exc.
Referenced by WriteEXC().
DoWriteFPU()
virtual int RegisterContextDarwin_arm64::DoWriteFPU (lldb::tid_t tid, int flavor, const FPU & fpu) protected pure virtual
Implemented in RegisterContextDarwin_arm64_Mach, and RegisterContextKDP_arm64.
References fpu.
Referenced by WriteFPU().
DoWriteGPR()
virtual int RegisterContextDarwin_arm64::DoWriteGPR (lldb::tid_t tid, int flavor, const GPR & gpr) protected pure virtual
Implemented in RegisterContextDarwin_arm64_Mach, and RegisterContextKDP_arm64.
References gpr.
Referenced by WriteGPR().
GetError()
int RegisterContextDarwin_arm64::GetError (int flavor, uint32_t err_idx) const inline protected
Definition at line 137 of file RegisterContextDarwin_arm64.h.
References dbg_errs, DBGRegSet, exc_errs, EXCRegSet, fpu_errs, FPURegSet, gpr_errs, GPRRegSet, and kNumErrors.
Referenced by ReadDBG(), ReadEXC(), ReadFPU(), ReadGPR(), RegisterSetIsCached(), WriteDBG(), WriteEXC(), WriteFPU(), and WriteGPR().
GetRegisterCount()
size_t RegisterContextDarwin_arm64::GetRegisterCount () override virtual
Implements lldb_private::RegisterContext.
Definition at line 112 of file RegisterContextDarwin_arm64.cpp.
References k_num_register_infos, and k_num_registers.
GetRegisterInfoAtIndex()
const RegisterInfo * RegisterContextDarwin_arm64::GetRegisterInfoAtIndex (size_t reg) override virtual
Implements lldb_private::RegisterContext.
Definition at line 118 of file RegisterContextDarwin_arm64.cpp.
References k_num_register_infos, and k_num_registers.
GetRegisterInfos()
const RegisterInfo * RegisterContextDarwin_arm64::GetRegisterInfos () static protected
Definition at line 129 of file RegisterContextDarwin_arm64.cpp.
GetRegisterInfosCount()
size_t RegisterContextDarwin_arm64::GetRegisterInfosCount () static protected
Definition at line 125 of file RegisterContextDarwin_arm64.cpp.
References k_num_register_infos.
GetRegisterNumber()
uint32_t RegisterContextDarwin_arm64::GetRegisterNumber (uint32_t reg_kind, uint32_t reg_num) static protected
GetRegisterSet()
const RegisterSet * RegisterContextDarwin_arm64::GetRegisterSet (size_t set) override virtual
Implements lldb_private::RegisterContext.
Definition at line 154 of file RegisterContextDarwin_arm64.cpp.
References g_reg_sets, and k_num_regsets.
GetRegisterSetCount()
size_t RegisterContextDarwin_arm64::GetRegisterSetCount () override virtual
Implements lldb_private::RegisterContext.
Definition at line 150 of file RegisterContextDarwin_arm64.cpp.
References k_num_regsets.
GetSetForNativeRegNum()
int RegisterContextDarwin_arm64::GetSetForNativeRegNum (int reg_num) static protected
Definition at line 161 of file RegisterContextDarwin_arm64.cpp.
References exc_far, EXCRegSet, FPURegSet, GPRRegSet, and k_num_registers.
Referenced by ReadRegister(), and WriteRegister().
InvalidateAllRegisters()
void RegisterContextDarwin_arm64::InvalidateAllRegisters () override virtual
Implements lldb_private::RegisterContext.
Reimplemented in RegisterContextDarwin_arm64_Mach.
Definition at line 108 of file RegisterContextDarwin_arm64.cpp.
References InvalidateAllRegisterStates().
InvalidateAllRegisterStates()
void RegisterContextDarwin_arm64::InvalidateAllRegisterStates () inline protected
Definition at line 131 of file RegisterContextDarwin_arm64.h.
References EXCRegSet, FPURegSet, GPRRegSet, Read, and SetError().
Referenced by InvalidateAllRegisters().
LogDBGRegisters()
void RegisterContextDarwin_arm64::LogDBGRegisters (lldb_private::Log * log, const DBG & dbg) static
Definition at line 282 of file RegisterContextDarwin_arm64.cpp.
References dbg, and LLDB_LOGF.
NumSupportedHardwareWatchpoints()
uint32_t RegisterContextDarwin_arm64::NumSupportedHardwareWatchpoints () override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 919 of file RegisterContextDarwin_arm64.cpp.
References UINT32_MAX.
Referenced by ClearHardwareWatchpoint(), and SetHardwareWatchpoint().
ReadAllRegisterValues()
bool RegisterContextDarwin_arm64::ReadAllRegisterValues (lldb::WritableDataBufferSP & data_sp) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 644 of file RegisterContextDarwin_arm64.cpp.
References exc, fpu, gpr, KERN_SUCCESS, ReadEXC(), ReadFPU(), ReadGPR(), and REG_CONTEXT_SIZE.
ReadDBG()
int RegisterContextDarwin_arm64::ReadDBG (bool force) protected
Definition at line 195 of file RegisterContextDarwin_arm64.cpp.
References dbg, DBGRegSet, DoReadDBG(), GetError(), lldb_private::RegisterContext::GetThreadID(), Read, RegisterSetIsCached(), and SetError().
Referenced by ClearHardwareWatchpoint(), ReadRegisterSet(), and SetHardwareWatchpoint().
ReadEXC()
int RegisterContextDarwin_arm64::ReadEXC (bool force) protected
Definition at line 187 of file RegisterContextDarwin_arm64.cpp.
References DoReadEXC(), exc, EXCRegSet, GetError(), lldb_private::RegisterContext::GetThreadID(), Read, RegisterSetIsCached(), and SetError().
Referenced by ReadAllRegisterValues(), and ReadRegisterSet().
ReadFPU()
int RegisterContextDarwin_arm64::ReadFPU (bool force) protected
Definition at line 179 of file RegisterContextDarwin_arm64.cpp.
References DoReadFPU(), fpu, FPURegSet, GetError(), lldb_private::RegisterContext::GetThreadID(), Read, RegisterSetIsCached(), and SetError().
Referenced by ReadAllRegisterValues(), and ReadRegisterSet().
ReadGPR()
int RegisterContextDarwin_arm64::ReadGPR (bool force) protected
Definition at line 171 of file RegisterContextDarwin_arm64.cpp.
References DoReadGPR(), GetError(), lldb_private::RegisterContext::GetThreadID(), gpr, GPRRegSet, Read, RegisterSetIsCached(), and SetError().
Referenced by ReadAllRegisterValues(), and ReadRegisterSet().
ReadRegister()
bool RegisterContextDarwin_arm64::ReadRegister (const lldb_private::RegisterInfo * reg_info, lldb_private::RegisterValue & reg_value) override virtual
Implements lldb_private::RegisterContext.
Definition at line 293 of file RegisterContextDarwin_arm64.cpp.
References lldb_private::RegisterInfo::byte_size, lldb::eRegisterKindLLDB, exc, exc_exception, exc_far, fpu, fpu_s0, fpu_s1, fpu_s10, fpu_s11, fpu_s12, fpu_s13, fpu_s14, fpu_s15, fpu_s16, fpu_s17, fpu_s18, fpu_s19, fpu_s2, fpu_s20, fpu_s21, fpu_s22, fpu_s23, fpu_s24, fpu_s25, fpu_s26, fpu_s27, fpu_s28, fpu_s29, fpu_s3, fpu_s30, fpu_s31, fpu_s4, fpu_s5, fpu_s6, fpu_s7, fpu_s8, fpu_s9, lldb_private::DataExtractor::GetDouble(), lldb_private::DataExtractor::GetFloat(), lldb_private::DataExtractor::GetMaxU64(), GetSetForNativeRegNum(), gpr, gpr_cpsr, gpr_lr, gpr_pc, gpr_sp, gpr_x0, gpr_x1, gpr_x10, gpr_x11, gpr_x12, gpr_x13, gpr_x14, gpr_x15, gpr_x16, gpr_x17, gpr_x18, gpr_x19, gpr_x2, gpr_x20, gpr_x21, gpr_x22, gpr_x23, gpr_x24, gpr_x25, gpr_x26, gpr_x27, gpr_x28, gpr_x3, gpr_x4, gpr_x5, gpr_x6, gpr_x7, gpr_x8, gpr_x9, lldb_private::endian::InlHostByteOrder(), KERN_SUCCESS, lldb_private::RegisterInfo::kinds, lldb_private::RegisterContext::m_thread, ReadRegisterSet(), lldb_private::RegisterValue::SetBytes(), lldb_private::RegisterValue::SetDouble(), lldb_private::RegisterValue::SetFloat(), lldb_private::RegisterValue::SetUInt32(), lldb_private::RegisterValue::SetUInt64(), and lldb_private::RegisterValue::SetValueToInvalid().
ReadRegisterSet()
int RegisterContextDarwin_arm64::ReadRegisterSet (uint32_t set, bool force) protected
Definition at line 247 of file RegisterContextDarwin_arm64.cpp.
References DBGRegSet, EXCRegSet, FPURegSet, GPRRegSet, KERN_INVALID_ARGUMENT, ReadDBG(), ReadEXC(), ReadFPU(), and ReadGPR().
Referenced by ReadRegister(), and WriteRegister().
RegisterSetIsCached()
bool RegisterContextDarwin_arm64::RegisterSetIsCached (int set) const inline protected
Definition at line 183 of file RegisterContextDarwin_arm64.h.
References GetError(), and Read.
Referenced by ReadDBG(), ReadEXC(), ReadFPU(), ReadGPR(), WriteDBG(), WriteEXC(), WriteFPU(), WriteGPR(), and WriteRegisterSet().
SetError()
bool RegisterContextDarwin_arm64::SetError (int flavor, uint32_t err_idx, int err) inline protected
Definition at line 157 of file RegisterContextDarwin_arm64.h.
References DBGRegSet, exc_errs, EXCRegSet, fpu_errs, FPURegSet, gpr_errs, GPRRegSet, and kNumErrors.
Referenced by InvalidateAllRegisterStates(), ReadDBG(), ReadEXC(), ReadFPU(), ReadGPR(), RegisterContextDarwin_arm64_Mach::SetRegisterDataFrom_LC_THREAD(), WriteDBG(), WriteEXC(), WriteFPU(), and WriteGPR().
SetHardwareWatchpoint()
uint32_t RegisterContextDarwin_arm64::SetHardwareWatchpoint (lldb::addr_t addr, size_t size, bool read, bool write) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 938 of file RegisterContextDarwin_arm64.cpp.
References dbg, KERN_SUCCESS, LLDB_INVALID_INDEX32, NumSupportedHardwareWatchpoints(), ReadDBG(), S_USER, WCR_ENABLE, WCR_LOAD, WCR_STORE, and WriteDBG().
WriteAllRegisterValues()
bool RegisterContextDarwin_arm64::WriteAllRegisterValues (const lldb::DataBufferSP & data_sp) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 662 of file RegisterContextDarwin_arm64.cpp.
References exc, fpu, gpr, KERN_SUCCESS, REG_CONTEXT_SIZE, WriteEXC(), WriteFPU(), and WriteGPR().
WriteDBG()
int RegisterContextDarwin_arm64::WriteDBG () protected
Definition at line 236 of file RegisterContextDarwin_arm64.cpp.
References dbg, DBGRegSet, DoWriteDBG(), GetError(), lldb_private::RegisterContext::GetThreadID(), KERN_INVALID_ARGUMENT, Read, RegisterSetIsCached(), SetError(), and Write.
Referenced by ClearHardwareWatchpoint(), SetHardwareWatchpoint(), and WriteRegisterSet().
WriteEXC()
int RegisterContextDarwin_arm64::WriteEXC () protected
Definition at line 225 of file RegisterContextDarwin_arm64.cpp.
References DoWriteEXC(), exc, EXCRegSet, GetError(), lldb_private::RegisterContext::GetThreadID(), KERN_INVALID_ARGUMENT, Read, RegisterSetIsCached(), SetError(), and Write.
Referenced by WriteAllRegisterValues(), and WriteRegisterSet().
WriteFPU()
int RegisterContextDarwin_arm64::WriteFPU () protected
Definition at line 214 of file RegisterContextDarwin_arm64.cpp.
References DoWriteFPU(), fpu, FPURegSet, GetError(), lldb_private::RegisterContext::GetThreadID(), KERN_INVALID_ARGUMENT, Read, RegisterSetIsCached(), SetError(), and Write.
Referenced by WriteAllRegisterValues(), and WriteRegisterSet().
WriteGPR()
int RegisterContextDarwin_arm64::WriteGPR () protected
Definition at line 203 of file RegisterContextDarwin_arm64.cpp.
References DoWriteGPR(), GetError(), lldb_private::RegisterContext::GetThreadID(), gpr, GPRRegSet, KERN_INVALID_ARGUMENT, Read, RegisterSetIsCached(), SetError(), and Write.
Referenced by WriteAllRegisterValues(), and WriteRegisterSet().
WriteRegister()
bool RegisterContextDarwin_arm64::WriteRegister (const lldb_private::RegisterInfo * reg_info, const lldb_private::RegisterValue & reg_value) override virtual
Implements lldb_private::RegisterContext.
Definition at line 535 of file RegisterContextDarwin_arm64.cpp.
References lldb::eRegisterKindLLDB, exc, exc_exception, exc_far, fpu, lldb_private::RegisterValue::GetAsUInt32(), lldb_private::RegisterValue::GetAsUInt64(), lldb_private::RegisterValue::GetBytes(), lldb_private::RegisterValue::GetByteSize(), GetSetForNativeRegNum(), gpr, gpr_cpsr, gpr_lr, gpr_pc, gpr_sp, gpr_x0, gpr_x1, gpr_x10, gpr_x11, gpr_x12, gpr_x13, gpr_x14, gpr_x15, gpr_x16, gpr_x17, gpr_x18, gpr_x19, gpr_x2, gpr_x20, gpr_x21, gpr_x22, gpr_x23, gpr_x24, gpr_x25, gpr_x26, gpr_x27, gpr_x28, gpr_x3, gpr_x4, gpr_x5, gpr_x6, gpr_x7, gpr_x8, gpr_x9, KERN_SUCCESS, lldb_private::RegisterInfo::kinds, ReadRegisterSet(), and WriteRegisterSet().
WriteRegisterSet()
int RegisterContextDarwin_arm64::WriteRegisterSet (uint32_t set) protected
Definition at line 263 of file RegisterContextDarwin_arm64.cpp.
References DBGRegSet, EXCRegSet, FPURegSet, GPRRegSet, KERN_INVALID_ARGUMENT, RegisterSetIsCached(), WriteDBG(), WriteEXC(), WriteFPU(), and WriteGPR().
Referenced by WriteRegister().
Member Data Documentation
dbg
DBG RegisterContextDarwin_arm64::dbg protected
Definition at line 125 of file RegisterContextDarwin_arm64.h.
Referenced by ClearHardwareWatchpoint(), DoReadDBG(), RegisterContextDarwin_arm64_Mach::DoReadDBG(), RegisterContextKDP_arm64::DoReadDBG(), DoWriteDBG(), RegisterContextDarwin_arm64_Mach::DoWriteDBG(), RegisterContextKDP_arm64::DoWriteDBG(), LogDBGRegisters(), ReadDBG(), RegisterContextDarwin_arm64(), SetHardwareWatchpoint(), WriteDBG(), and RegisterContextKDP_arm64::~RegisterContextKDP_arm64().
dbg_errs
int RegisterContextDarwin_arm64::dbg_errs[2] protected
Definition at line 129 of file RegisterContextDarwin_arm64.h.
Referenced by GetError().
exc
EXC RegisterContextDarwin_arm64::exc protected
Definition at line 124 of file RegisterContextDarwin_arm64.h.
Referenced by DoReadEXC(), RegisterContextDarwin_arm64_Mach::DoReadEXC(), RegisterContextKDP_arm64::DoReadEXC(), DoWriteEXC(), RegisterContextDarwin_arm64_Mach::DoWriteEXC(), RegisterContextKDP_arm64::DoWriteEXC(), ReadAllRegisterValues(), ReadEXC(), ReadRegister(), RegisterContextDarwin_arm64(), RegisterContextDarwin_arm64_Mach::SetRegisterDataFrom_LC_THREAD(), WriteAllRegisterValues(), WriteEXC(), WriteRegister(), and RegisterContextKDP_arm64::~RegisterContextKDP_arm64().
exc_errs
int RegisterContextDarwin_arm64::exc_errs[2] protected
Definition at line 128 of file RegisterContextDarwin_arm64.h.
Referenced by GetError(), RegisterContextDarwin_arm64(), and SetError().
fpu
FPU RegisterContextDarwin_arm64::fpu protected
Definition at line 123 of file RegisterContextDarwin_arm64.h.
Referenced by DoReadFPU(), RegisterContextDarwin_arm64_Mach::DoReadFPU(), RegisterContextKDP_arm64::DoReadFPU(), DoWriteFPU(), RegisterContextDarwin_arm64_Mach::DoWriteFPU(), RegisterContextKDP_arm64::DoWriteFPU(), ReadAllRegisterValues(), ReadFPU(), ReadRegister(), RegisterContextDarwin_arm64(), RegisterContextDarwin_arm64_Mach::SetRegisterDataFrom_LC_THREAD(), WriteAllRegisterValues(), WriteFPU(), WriteRegister(), and RegisterContextKDP_arm64::~RegisterContextKDP_arm64().
fpu_errs
int RegisterContextDarwin_arm64::fpu_errs[2] protected
Definition at line 127 of file RegisterContextDarwin_arm64.h.
Referenced by GetError(), RegisterContextDarwin_arm64(), and SetError().
gpr
GPR RegisterContextDarwin_arm64::gpr protected
Definition at line 122 of file RegisterContextDarwin_arm64.h.
Referenced by DoReadGPR(), RegisterContextDarwin_arm64_Mach::DoReadGPR(), RegisterContextKDP_arm64::DoReadGPR(), DoWriteGPR(), RegisterContextDarwin_arm64_Mach::DoWriteGPR(), RegisterContextKDP_arm64::DoWriteGPR(), ReadAllRegisterValues(), ReadGPR(), ReadRegister(), RegisterContextDarwin_arm64(), RegisterContextDarwin_arm64_Mach::SetRegisterDataFrom_LC_THREAD(), WriteAllRegisterValues(), WriteGPR(), WriteRegister(), and RegisterContextKDP_arm64::~RegisterContextKDP_arm64().
gpr_errs
int RegisterContextDarwin_arm64::gpr_errs[2] protected
Definition at line 126 of file RegisterContextDarwin_arm64.h.
Referenced by GetError(), RegisterContextDarwin_arm64(), and SetError().
The documentation for this class was generated from the following files:
RegisterContextDarwin_arm64.h
RegisterContextDarwin_arm64.cpp