LLDB: lldb_private::SectionLoadList Class Reference
lldb_private::SectionLoadList Class Reference
#include <SectionLoadList.h>
Public Member Functions
SectionLoadList ()=default
SectionLoadList (const SectionLoadList &rhs)
~SectionLoadList ()
void operator= (const SectionLoadList &rhs)
bool IsEmpty () const
void Clear ()
lldb::addr_t GetSectionLoadAddress (const lldb::SectionSP &section_sp) const
bool ResolveLoadAddress (lldb::addr_t load_addr, Address &so_addr, bool allow_section_end=false) const
bool SetSectionLoadAddress (const lldb::SectionSP &section_sp, lldb::addr_t load_addr, bool warn_multiple=false)
bool SetSectionUnloaded (const lldb::SectionSP &section_sp, lldb::addr_t load_addr)
size_t SetSectionUnloaded (const lldb::SectionSP &section_sp)
void Dump (Stream &s, Target *target)
Protected Types
typedef std::map< lldb::addr_t, lldb::SectionSP > addr_to_sect_collection
typedef llvm::DenseMap< const Section *, lldb::addr_t > sect_to_addr_collection
Protected Attributes
addr_to_sect_collection m_addr_to_sect
sect_to_addr_collection m_sect_to_addr
std::recursive_mutex m_mutex
Detailed Description
Definition at line 22 of file SectionLoadList.h.
Member Typedef Documentation
addr_to_sect_collection
typedef std::map<lldb::addr_t, lldb::SectionSP> lldb_private::SectionLoadList::addr_to_sect_collection protected
Definition at line 64 of file SectionLoadList.h.
sect_to_addr_collection
typedef llvm::DenseMap<const Section *, lldb::addr_t> lldb_private::SectionLoadList::sect_to_addr_collection protected
Definition at line 65 of file SectionLoadList.h.
Constructor & Destructor Documentation
SectionLoadList() [1/2]
lldb_private::SectionLoadList::SectionLoadList () default
References SectionLoadList().
Referenced by operator=(), SectionLoadList(), and SectionLoadList().
SectionLoadList() [2/2]
SectionLoadList::SectionLoadList (const SectionLoadList & rhs)
Definition at line 23 of file SectionLoadList.cpp.
References m_addr_to_sect, m_mutex, m_sect_to_addr, and SectionLoadList().
~SectionLoadList()
lldb_private::SectionLoadList::~SectionLoadList () inline
Definition at line 29 of file SectionLoadList.h.
References Clear().
Member Function Documentation
Clear()
void SectionLoadList::Clear ()
Definition at line 43 of file SectionLoadList.cpp.
References m_addr_to_sect, m_mutex, and m_sect_to_addr.
Referenced by lldb_private::Target::ClearSectionLoadList(), and ~SectionLoadList().
Dump()
void SectionLoadList::Dump (Stream & s, Target * target)
Definition at line 260 of file SectionLoadList.cpp.
References lldb_private::Stream::AsRawOstream(), lldb_private::Stream::GetIndentLevel(), m_addr_to_sect, m_mutex, and lldb_private::Stream::Printf().
Referenced by lldb_private::Target::DumpSectionLoadList().
GetSectionLoadAddress()
addr_t SectionLoadList::GetSectionLoadAddress (const lldb::SectionSP & section_sp) const
Definition at line 50 of file SectionLoadList.cpp.
References LLDB_INVALID_ADDRESS, m_mutex, and m_sect_to_addr.
Referenced by lldb_private::SectionLoadHistory::GetSectionLoadAddress(), and lldb_private::Target::GetSectionLoadAddress().
IsEmpty()
bool SectionLoadList::IsEmpty () const
Definition at line 38 of file SectionLoadList.cpp.
References m_addr_to_sect, and m_mutex.
Referenced by lldb_private::Target::HasLoadedSections(), lldb_private::Target::ReadMemory(), and lldb_private::Target::ReadPointerFromMemory().
operator=()
void SectionLoadList::operator= (const SectionLoadList & rhs)
Definition at line 30 of file SectionLoadList.cpp.
References m_addr_to_sect, m_mutex, m_sect_to_addr, and SectionLoadList().
ResolveLoadAddress()
bool SectionLoadList::ResolveLoadAddress (lldb::addr_t load_addr, Address & so_addr, bool allow_section_end = false) const
Definition at line 219 of file SectionLoadList.cpp.
References lldb_private::Address::Clear(), m_addr_to_sect, and m_mutex.
Referenced by lldb_private::Target::CreateBreakpoint(), lldb_private::Target::ReadMemory(), lldb_private::Target::ReadPointerFromMemory(), and lldb_private::SectionLoadHistory::ResolveLoadAddress().
SetSectionLoadAddress()
bool SectionLoadList::SetSectionLoadAddress (const lldb::SectionSP & section_sp, lldb::addr_t load_addr, bool warn_multiple = false)
Definition at line 64 of file SectionLoadList.cpp.
References lldb_private::DynamicLoader, lldb_private::GetLog(), LLDB_LOGF, LLDB_LOGV, m_addr_to_sect, m_mutex, and m_sect_to_addr.
Referenced by lldb_private::SectionLoadHistory::SetSectionLoadAddress().
SetSectionUnloaded() [1/2]
size_t SectionLoadList::SetSectionUnloaded (const lldb::SectionSP & section_sp)
Definition at line 146 of file SectionLoadList.cpp.
References lldb_private::DynamicLoader, lldb_private::GetLog(), lldb_private::FileSpec::GetPath(), lldb_private::Log::GetVerbose(), LLDB_LOGF, m_addr_to_sect, m_mutex, and m_sect_to_addr.
SetSectionUnloaded() [2/2]
bool SectionLoadList::SetSectionUnloaded (const lldb::SectionSP & section_sp, lldb::addr_t load_addr)
Definition at line 183 of file SectionLoadList.cpp.
References lldb_private::DynamicLoader, lldb_private::GetLog(), lldb_private::FileSpec::GetPath(), lldb_private::Log::GetVerbose(), LLDB_LOGF, m_addr_to_sect, m_mutex, and m_sect_to_addr.
Referenced by lldb_private::SectionLoadHistory::SetSectionUnloaded(), and lldb_private::SectionLoadHistory::SetSectionUnloaded().
Member Data Documentation
m_addr_to_sect
addr_to_sect_collection lldb_private::SectionLoadList::m_addr_to_sect protected
Definition at line 66 of file SectionLoadList.h.
Referenced by Clear(), Dump(), IsEmpty(), operator=(), ResolveLoadAddress(), SectionLoadList(), SetSectionLoadAddress(), SetSectionUnloaded(), and SetSectionUnloaded().
m_mutex
std::recursive_mutex lldb_private::SectionLoadList::m_mutex mutable protected
Definition at line 68 of file SectionLoadList.h.
Referenced by Clear(), Dump(), GetSectionLoadAddress(), IsEmpty(), operator=(), ResolveLoadAddress(), SectionLoadList(), SetSectionLoadAddress(), SetSectionUnloaded(), and SetSectionUnloaded().
m_sect_to_addr
sect_to_addr_collection lldb_private::SectionLoadList::m_sect_to_addr protected
Definition at line 67 of file SectionLoadList.h.
Referenced by Clear(), GetSectionLoadAddress(), operator=(), SectionLoadList(), SetSectionLoadAddress(), SetSectionUnloaded(), and SetSectionUnloaded().
The documentation for this class was generated from the following files:
SectionLoadList.h
SectionLoadList.cpp