LLDB: lldb_private::Language::TypeScavenger Class Reference
lldb_private::Language::TypeScavenger Class Reference abstract
#include <Language.h>
Classes
class Result
Public Types
typedef std::set< std::unique_ptr< Result > > ResultSet
Public Member Functions
virtual ~TypeScavenger ()=default
size_t Find (ExecutionContextScope *exe_scope, const char *key, ResultSet &results, bool append=true)
Protected Member Functions
TypeScavenger ()=default
virtual bool Find_Impl (ExecutionContextScope *exe_scope, const char *key, ResultSet &results)=0
Detailed Description
Definition at line 41 of file Language.h.
Member Typedef Documentation
ResultSet
typedef std::set<std::unique_ptr<Result> > lldb_private::Language::TypeScavenger::ResultSet
Definition at line 53 of file Language.h.
Constructor & Destructor Documentation
~TypeScavenger()
virtual lldb_private::Language::TypeScavenger::~TypeScavenger () virtual default
TypeScavenger()
lldb_private::Language::TypeScavenger::TypeScavenger () protected default
Referenced by lldb_private::Language::EitherTypeScavenger< ScavengerTypes >::EitherTypeScavenger(), and lldb_private::Language::UnionTypeScavenger< ScavengerTypes >::UnionTypeScavenger().
Member Function Documentation
Find()
size_t Language::TypeScavenger::Find (ExecutionContextScope * exe_scope, const char * key, ResultSet & results, bool append = true)
Definition at line 489 of file Language.cpp.
References lldb_private::ExecutionContextScope::CalculateTarget(), and Find_Impl().
Find_Impl()
virtual bool lldb_private::Language::TypeScavenger::Find_Impl (ExecutionContextScope * exe_scope, const char * key, ResultSet & results) protected pure virtual
Implemented in lldb_private::Language::EitherTypeScavenger< ScavengerTypes >, lldb_private::Language::ImageListTypeScavenger, and lldb_private::Language::UnionTypeScavenger< ScavengerTypes >.
Referenced by Find().
The documentation for this class was generated from the following files:
Language.h
Language.cpp