LLDB: lldb_private::TypeMap Class Reference
lldb_private::TypeMap Class Reference
#include <TypeMap.h>
Public Types
typedef std::multimap< lldb::user_id_t, lldb::TypeSP > collection
typedef llvm::iterator_range< ValueMapIterator< collection::const_iterator > > TypeIterable
Public Member Functions
TypeMap ()
virtual ~TypeMap ()
void Clear ()
void Dump (Stream *s, bool show_context, lldb::DescriptionLevel level=lldb::eDescriptionLevelFull) const
TypeMap FindTypes (ConstString name)
void Insert (const lldb::TypeSP &type)
bool Empty () const
bool InsertUnique (const lldb::TypeSP &type)
uint32_t GetSize () const
lldb::TypeSP GetTypeAtIndex (uint32_t idx)
lldb::TypeSP FirstType () const
TypeIterable Types () const
void ForEach (std::function< bool(const lldb::TypeSP &type_sp)> const &callback) const
void ForEach (std::function< bool(lldb::TypeSP &type_sp)> const &callback)
bool Remove (const lldb::TypeSP &type_sp)
Private Types
typedef collection::iterator iterator
typedef collection::const_iterator const_iterator
Private Member Functions
TypeMap (const TypeMap &)=delete
const TypeMap & operator= (const TypeMap &)=delete
Private Attributes
collection m_types
Detailed Description
Definition at line 20 of file TypeMap.h.
Member Typedef Documentation
collection
typedef std::multimap<lldb::user_id_t, lldb::TypeSP> lldb_private::TypeMap::collection
Definition at line 46 of file TypeMap.h.
const_iterator
typedef collection::const_iterator lldb_private::TypeMap::const_iterator private
Definition at line 61 of file TypeMap.h.
iterator
typedef collection::iterator lldb_private::TypeMap::iterator private
Definition at line 60 of file TypeMap.h.
TypeIterable
typedef llvm::iterator_range<ValueMapIterator<collection::const_iterator> > lldb_private::TypeMap::TypeIterable
Definition at line 48 of file TypeMap.h.
Constructor & Destructor Documentation
TypeMap() [1/2]
TypeMap::TypeMap ()
Definition at line 22 of file TypeMap.cpp.
References m_types.
Referenced by FindTypes(), operator=(), and TypeMap().
~TypeMap()
TypeMap::~TypeMap () virtual default
References lldb::eDescriptionLevelFull.
TypeMap() [2/2]
lldb_private::TypeMap::TypeMap (const TypeMap &) private delete
References TypeMap().
Member Function Documentation
Clear()
void TypeMap::Clear ()
Definition at line 73 of file TypeMap.cpp.
References m_types.
Dump()
void TypeMap::Dump (Stream * s, bool show_context, lldb::DescriptionLevel level = lldb::eDescriptionLevelFull) const
Definition at line 130 of file TypeMap.cpp.
References m_types.
Empty()
bool TypeMap::Empty () const
Definition at line 77 of file TypeMap.cpp.
References m_types.
Referenced by lldb::SBModule::FindTypes(), lldb_private::TypeFormatImpl_EnumType::FormatObject(), and lldb_private::SymbolContext::SortTypeList().
FindTypes()
TypeMap lldb_private::TypeMap::FindTypes (ConstString name)
References TypeMap().
FirstType()
lldb::TypeSP TypeMap::FirstType () const
Definition at line 94 of file TypeMap.cpp.
References m_types.
Referenced by DWARFASTParserClang::ParseTypeFromClangModule().
ForEach() [1/2]
void TypeMap::ForEach (std::function< bool(const lldb::TypeSP &type_sp)> const & callback) const
Definition at line 100 of file TypeMap.cpp.
References m_types.
Referenced by lldb_private::SymbolContext::SortTypeList().
ForEach() [2/2]
void TypeMap::ForEach (std::function< bool(lldb::TypeSP &type_sp)> const & callback)
Definition at line 108 of file TypeMap.cpp.
References m_types.
GetSize()
uint32_t TypeMap::GetSize () const
Definition at line 75 of file TypeMap.cpp.
References m_types.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::FindTypes(), and ProcessFreeBSDKernelCore::PrintUnreadMessage().
GetTypeAtIndex()
TypeSP TypeMap::GetTypeAtIndex (uint32_t idx)
Definition at line 83 of file TypeMap.cpp.
References m_types.
Referenced by ProcessFreeBSDKernelCore::PrintUnreadMessage().
Insert()
void TypeMap::Insert (const lldb::TypeSP & type)
Definition at line 27 of file TypeMap.cpp.
References m_types.
Referenced by lldb_private::npdb::SymbolFileNativePDB::FindTypesByName(), lldb_private::SymbolFileCTF::FindTypesByRegex(), SymbolFilePDB::FindTypesByRegex(), and InsertUnique().
InsertUnique()
bool TypeMap::InsertUnique (const lldb::TypeSP & type)
Definition at line 34 of file TypeMap.cpp.
References Insert(), and m_types.
operator=()
const TypeMap & lldb_private::TypeMap::operator= (const TypeMap &) private delete
References TypeMap().
Remove()
bool TypeMap::Remove (const lldb::TypeSP & type_sp)
Definition at line 116 of file TypeMap.cpp.
References m_types.
Referenced by lldb_private::SymbolContext::SortTypeList().
Types()
TypeIterable lldb_private::TypeMap::Types () const inline
Definition at line 50 of file TypeMap.h.
References m_types.
Referenced by lldb_private::Language::ImageListTypeScavenger::Find_Impl(), lldb_private::ClangASTSource::FindCompleteType(), lldb::SBModule::FindTypes(), lldb::SBTarget::FindTypes(), lldb_private::TypeFormatImpl_EnumType::FormatObject(), lldb_private::ItaniumABILanguageRuntime::GetTypeInfo(), and lldb_private::ObjCLanguageRuntime::LookupInCompleteClassCache().
Member Data Documentation
m_types
collection lldb_private::TypeMap::m_types private
Definition at line 63 of file TypeMap.h.
Referenced by Clear(), Dump(), Empty(), FirstType(), ForEach(), ForEach(), GetSize(), GetTypeAtIndex(), Insert(), InsertUnique(), Remove(), TypeMap(), and Types().
The documentation for this class was generated from the following files:
TypeMap.h
TypeMap.cpp