LLDB: lldb_private::plugin::dwarf::DWARFDebugInfo Class Reference
lldb_private::plugin::dwarf::DWARFDebugInfo Class Reference
#include <DWARFDebugInfo.h>
Public Types
enum { eDumpFlag_Verbose = (1 << 0) , eDumpFlag_ShowForm = (1 << 1) , eDumpFlag_ShowAncestors }
typedef dw_offset_t(* Callback) (SymbolFileDWARF *dwarf2Data, DWARFUnit *cu, DWARFDebugInfoEntry *die, const dw_offset_t next_offset, const uint32_t depth, void *userData)
Public Member Functions
DWARFDebugInfo (SymbolFileDWARF &dwarf, DWARFContext &context)
size_t GetNumUnits ()
DWARFUnit * GetUnitAtIndex (size_t idx)
DWARFUnit * GetUnitAtOffset (DIERef::Section section, dw_offset_t cu_offset, uint32_t *idx_ptr=nullptr)
DWARFUnit * GetUnitContainingDIEOffset (DIERef::Section section, dw_offset_t die_offset)
DWARFUnit * GetSkeletonUnit (DWARFUnit *dwo_unit)
DWARFTypeUnit * GetTypeUnitForHash (uint64_t hash)
bool ContainsTypeUnits ()
DWARFDIE GetDIE (DIERef::Section section, dw_offset_t die_offset)
const DWARFDebugAranges & GetCompileUnitAranges ()
const std::shared_ptr< SymbolFileDWARFDwo > & GetDwpSymbolFile ()
Protected Types
typedef std::vector< DWARFUnitSP > UnitColl
Protected Attributes
SymbolFileDWARF & m_dwarf
DWARFContext & m_context
llvm::once_flag m_units_once_flag
UnitColl m_units
std::unique_ptr< DWARFDebugAranges > m_cu_aranges_up
std::vector< std::pair< uint64_t, uint32_t > > m_type_hash_to_unit_index
llvm::DenseMap< uint64_t, DWARFUnit * > m_dwarf5_dwo_id_to_skeleton_unit
llvm::DenseMap< uint64_t, DWARFUnit * > m_dwarf4_dwo_id_to_skeleton_unit
llvm::once_flag m_dwarf4_dwo_id_to_skeleton_unit_once_flag
Private Member Functions
void ParseUnitHeadersIfNeeded ()
void ParseUnitsFor (DIERef::Section section)
uint32_t FindUnitIndex (DIERef::Section section, dw_offset_t offset)
DWARFDebugInfo (const DWARFDebugInfo &)=delete
const DWARFDebugInfo & operator= (const DWARFDebugInfo &)=delete
Detailed Description
Definition at line 26 of file DWARFDebugInfo.h.
Member Typedef Documentation
Callback
typedef dw_offset_t(* lldb_private::plugin::dwarf::DWARFDebugInfo::Callback) (SymbolFileDWARF *dwarf2Data, DWARFUnit *cu, DWARFDebugInfoEntry *die, const dw_offset_t next_offset, const uint32_t depth, void *userData)
Definition at line 28 of file DWARFDebugInfo.h.
UnitColl
typedef std::vector<DWARFUnitSP> lldb_private::plugin::dwarf::DWARFDebugInfo::UnitColl protected
Definition at line 58 of file DWARFDebugInfo.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
eDumpFlag_Verbose
eDumpFlag_ShowForm
eDumpFlag_ShowAncestors
Definition at line 46 of file DWARFDebugInfo.h.
Constructor & Destructor Documentation
DWARFDebugInfo() [1/2]
DWARFDebugInfo::DWARFDebugInfo (SymbolFileDWARF & dwarf, DWARFContext & context) explicit
Definition at line 34 of file DWARFDebugInfo.cpp.
References m_context, m_cu_aranges_up, m_dwarf, and m_units.
Referenced by DWARFDebugInfo(), and operator=().
DWARFDebugInfo() [2/2]
lldb_private::plugin::dwarf::DWARFDebugInfo::DWARFDebugInfo (const DWARFDebugInfo &) private delete
References DWARFDebugInfo().
Member Function Documentation
ContainsTypeUnits()
bool DWARFDebugInfo::ContainsTypeUnits ()
Definition at line 247 of file DWARFDebugInfo.cpp.
References m_type_hash_to_unit_index, and ParseUnitHeadersIfNeeded().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::BuildCuTranslationTable(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::FindSingleCompileUnit(), and lldb_private::plugin::dwarf::ManualDWARFIndex::IndexImpl().
FindUnitIndex()
uint32_t DWARFDebugInfo::FindUnitIndex (DIERef::Section section, dw_offset_t offset) private
Definition at line 193 of file DWARFDebugInfo.cpp.
References DW_INVALID_INDEX, m_units, and ParseUnitHeadersIfNeeded().
Referenced by GetUnitAtOffset(), and GetUnitContainingDIEOffset().
GetCompileUnitAranges()
const DWARFDebugAranges & DWARFDebugInfo::GetCompileUnitAranges ()
Definition at line 37 of file DWARFDebugInfo.cpp.
References lldb_private::plugin::dwarf::DWARFUnit::BuildAddressRangeTable(), lldb_private::ObjectFile::CanTrustAddressRanges(), DW_INVALID_OFFSET, GetNumUnits(), lldb_private::plugin::dwarf::DWARFUnit::GetOffset(), GetUnitAtIndex(), m_context, m_cu_aranges_up, and m_dwarf.
GetDIE()
DWARFDIE DWARFDebugInfo::GetDIE (DIERef::Section section, dw_offset_t die_offset)
Definition at line 256 of file DWARFDebugInfo.cpp.
References lldb_private::plugin::dwarf::DWARFDIE::GetDIE(), and GetUnitContainingDIEOffset().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::GetDIE(), and lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetDIE().
GetDwpSymbolFile()
const std::shared_ptr< SymbolFileDWARFDwo > & DWARFDebugInfo::GetDwpSymbolFile ()
Definition at line 235 of file DWARFDebugInfo.cpp.
References m_dwarf.
GetNumUnits()
size_t DWARFDebugInfo::GetNumUnits ()
Definition at line 181 of file DWARFDebugInfo.cpp.
References m_units, and ParseUnitHeadersIfNeeded().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::BuildCuTranslationTable(), lldb_private::plugin::dwarf::SymbolFileDWARF::CalculateNumCompileUnits(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::FindSingleCompileUnit(), GetCompileUnitAranges(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDebugInfoSize(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwoStats(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetMangledNamesForFunction(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetSeparateDebugInfo(), GetSkeletonUnit(), GetUnitAtIndex(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexImpl(), and lldb_private::plugin::dwarf::ManualDWARFIndex::IndexUnit().
GetSkeletonUnit()
DWARFUnit * DWARFDebugInfo::GetSkeletonUnit (DWARFUnit * dwo_unit)
Definition at line 124 of file DWARFDebugInfo.cpp.
References lldb_private::plugin::dwarf::DWARFUnit::GetDWOId(), GetNumUnits(), GetUnitAtIndex(), lldb_private::plugin::dwarf::DWARFUnit::GetVersion(), lldb_private::plugin::dwarf::DWARFUnit::IsDWOUnit(), m_dwarf4_dwo_id_to_skeleton_unit, m_dwarf4_dwo_id_to_skeleton_unit_once_flag, m_dwarf5_dwo_id_to_skeleton_unit, and ParseUnitHeadersIfNeeded().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::GetSkeletonUnit().
GetTypeUnitForHash()
DWARFTypeUnit * DWARFDebugInfo::GetTypeUnitForHash (uint64_t hash)
Definition at line 239 of file DWARFDebugInfo.cpp.
References GetUnitAtIndex(), and m_type_hash_to_unit_index.
Referenced by lldb_private::plugin::dwarf::DebugNamesDWARFIndex::GetForeignTypeUnit().
GetUnitAtIndex()
DWARFUnit * DWARFDebugInfo::GetUnitAtIndex (size_t idx)
Definition at line 186 of file DWARFDebugInfo.cpp.
References GetNumUnits(), and m_units.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::BuildCuTranslationTable(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::FindSingleCompileUnit(), GetCompileUnitAranges(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDebugInfoSize(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDIERefSymbolFile(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDWARFCompileUnit(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwoStats(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetMangledNamesForFunction(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetSeparateDebugInfo(), GetSkeletonUnit(), GetTypeUnitForHash(), GetUnitAtOffset(), GetUnitContainingDIEOffset(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexImpl(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexUnit(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariablesForContext(), and lldb_private::plugin::dwarf::SymbolFileDWARF::UpdateExternalModuleListIfNeeded().
GetUnitAtOffset()
DWARFUnit * DWARFDebugInfo::GetUnitAtOffset (DIERef::Section section, dw_offset_t cu_offset, uint32_t * idx_ptr = nullptr)
Definition at line 211 of file DWARFDebugInfo.cpp.
References DW_INVALID_INDEX, FindUnitIndex(), lldb_private::plugin::dwarf::DWARFUnit::GetOffset(), and GetUnitAtIndex().
GetUnitContainingDIEOffset()
DWARFUnit * DWARFDebugInfo::GetUnitContainingDIEOffset (DIERef::Section section, dw_offset_t die_offset)
Definition at line 226 of file DWARFDebugInfo.cpp.
References lldb_private::plugin::dwarf::DWARFUnit::ContainsDIEOffset(), FindUnitIndex(), and GetUnitAtIndex().
Referenced by GetDIE().
operator=()
const DWARFDebugInfo & lldb_private::plugin::dwarf::DWARFDebugInfo::operator= (const DWARFDebugInfo &) private delete
References DWARFDebugInfo().
ParseUnitHeadersIfNeeded()
void DWARFDebugInfo::ParseUnitHeadersIfNeeded () private
Definition at line 173 of file DWARFDebugInfo.cpp.
References lldb_private::plugin::dwarf::DIERef::DebugInfo, lldb_private::plugin::dwarf::DIERef::DebugTypes, m_type_hash_to_unit_index, m_units_once_flag, and ParseUnitsFor().
Referenced by ContainsTypeUnits(), FindUnitIndex(), GetNumUnits(), and GetSkeletonUnit().
ParseUnitsFor()
void DWARFDebugInfo::ParseUnitsFor (DIERef::Section section) private
Definition at line 79 of file DWARFDebugInfo.cpp.
References lldb_private::DebugInfo, lldb_private::plugin::dwarf::DIERef::DebugTypes, lldb_private::plugin::dwarf::DWARFUnit::extract(), lldb_private::GetLog(), LLDB_LOG, m_context, m_dwarf, m_dwarf5_dwo_id_to_skeleton_unit, m_type_hash_to_unit_index, m_units, and lldb_private::DataExtractor::ValidOffset().
Referenced by ParseUnitHeadersIfNeeded().
Member Data Documentation
m_context
DWARFContext& lldb_private::plugin::dwarf::DWARFDebugInfo::m_context protected
Definition at line 61 of file DWARFDebugInfo.h.
Referenced by DWARFDebugInfo(), GetCompileUnitAranges(), and ParseUnitsFor().
m_cu_aranges_up
std::unique_ptr<DWARFDebugAranges> lldb_private::plugin::dwarf::DWARFDebugInfo::m_cu_aranges_up protected
Definition at line 67 of file DWARFDebugInfo.h.
Referenced by DWARFDebugInfo(), and GetCompileUnitAranges().
m_dwarf
SymbolFileDWARF& lldb_private::plugin::dwarf::DWARFDebugInfo::m_dwarf protected
Definition at line 60 of file DWARFDebugInfo.h.
Referenced by DWARFDebugInfo(), GetCompileUnitAranges(), GetDwpSymbolFile(), and ParseUnitsFor().
m_dwarf4_dwo_id_to_skeleton_unit
llvm::DenseMap<uint64_t, DWARFUnit *> lldb_private::plugin::dwarf::DWARFDebugInfo::m_dwarf4_dwo_id_to_skeleton_unit protected
Definition at line 71 of file DWARFDebugInfo.h.
Referenced by GetSkeletonUnit().
m_dwarf4_dwo_id_to_skeleton_unit_once_flag
llvm::once_flag lldb_private::plugin::dwarf::DWARFDebugInfo::m_dwarf4_dwo_id_to_skeleton_unit_once_flag protected
Definition at line 72 of file DWARFDebugInfo.h.
Referenced by GetSkeletonUnit().
m_dwarf5_dwo_id_to_skeleton_unit
llvm::DenseMap<uint64_t, DWARFUnit *> lldb_private::plugin::dwarf::DWARFDebugInfo::m_dwarf5_dwo_id_to_skeleton_unit protected
Definition at line 70 of file DWARFDebugInfo.h.
Referenced by GetSkeletonUnit(), and ParseUnitsFor().
m_type_hash_to_unit_index
std::vector<std::pair<uint64_t, uint32_t> > lldb_private::plugin::dwarf::DWARFDebugInfo::m_type_hash_to_unit_index protected
Definition at line 69 of file DWARFDebugInfo.h.
Referenced by ContainsTypeUnits(), GetTypeUnitForHash(), ParseUnitHeadersIfNeeded(), and ParseUnitsFor().
m_units
UnitColl lldb_private::plugin::dwarf::DWARFDebugInfo::m_units protected
Definition at line 64 of file DWARFDebugInfo.h.
Referenced by DWARFDebugInfo(), FindUnitIndex(), GetNumUnits(), GetUnitAtIndex(), and ParseUnitsFor().
m_units_once_flag
llvm::once_flag lldb_private::plugin::dwarf::DWARFDebugInfo::m_units_once_flag protected
Definition at line 63 of file DWARFDebugInfo.h.
Referenced by ParseUnitHeadersIfNeeded().
The documentation for this class was generated from the following files:
DWARFDebugInfo.h
DWARFDebugInfo.cpp