LLDB: lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd Class Reference
lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd Class Reference
Data formatter for libc++'s std::slice_array.
Public Member Functions
LibcxxStdSliceArraySyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
~LibcxxStdSliceArraySyntheticFrontEnd () override
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Attributes
ValueObject * m_start = nullptr
A non-owning pointer to slice_array.__vp_.
size_t m_size = 0
slice_array.__size_.
size_t m_stride = 0
slice_array.__stride_.
CompilerType m_element_type
The type of slice_array's template argument T.
uint32_t m_element_size = 0
The sizeof slice_array's template argument T.
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
Data formatter for libc++'s std::slice_array.
A slice_array is created by using: operator[](std::slice slicearr); and std::slice is created by: slice(std::size_t start, std::size_t size, std::size_t stride); The std::slice_array has the following members:
__vp_ points to std::valarray::__begin_ + start
__size_ is size
__stride_is stride
Definition at line 53 of file LibCxxSliceArray.cpp.
Constructor & Destructor Documentation
LibcxxStdSliceArraySyntheticFrontEnd()
lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd::LibcxxStdSliceArraySyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
Definition at line 83 of file LibCxxSliceArray.cpp.
References m_element_type, lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd(), and Update().
~LibcxxStdSliceArraySyntheticFrontEnd()
lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd::~LibcxxStdSliceArraySyntheticFrontEnd () override
Definition at line 90 of file LibCxxSliceArray.cpp.
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd::CalculateNumChildren () override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 97 of file LibCxxSliceArray.cpp.
References m_size.
GetChildAtIndex()
lldb::ValueObjectSP lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd::GetChildAtIndex (uint32_t idx) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 103 of file LibCxxSliceArray.cpp.
References lldb_private::SyntheticChildrenFrontEnd::CreateValueObjectFromAddress(), lldb_private::StreamString::GetString(), lldb_private::SyntheticChildrenFrontEnd::m_backend, m_element_size, m_element_type, m_start, m_stride, and lldb_private::Stream::Printf().
GetIndexOfChildWithName()
llvm::Expected< size_t > lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd::GetIndexOfChildWithName (ConstString name) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 148 of file LibCxxSliceArray.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::formatters::ExtractIndexFromString(), lldb_private::ConstString::GetCString(), and m_start.
Update()
lldb::ChildCacheState lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd::Update () override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 118 of file LibCxxSliceArray.cpp.
References lldb::eRefetch, lldb_private::CompilerType::GetNumTemplateArguments(), lldb_private::CompilerType::GetTypeTemplateArgument(), lldb_private::SyntheticChildrenFrontEnd::m_backend, m_element_size, m_element_type, m_size, m_start, and m_stride.
Referenced by LibcxxStdSliceArraySyntheticFrontEnd().
Member Data Documentation
m_element_size
uint32_t lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd::m_element_size = 0 private
The sizeof slice_array's template argument T.
Definition at line 77 of file LibCxxSliceArray.cpp.
Referenced by GetChildAtIndex(), and Update().
m_element_type
CompilerType lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd::m_element_type private
The type of slice_array's template argument T.
Definition at line 75 of file LibCxxSliceArray.cpp.
Referenced by GetChildAtIndex(), LibcxxStdSliceArraySyntheticFrontEnd(), and Update().
m_size
size_t lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd::m_size = 0 private
slice_array.__size_.
Definition at line 71 of file LibCxxSliceArray.cpp.
Referenced by CalculateNumChildren(), and Update().
m_start
ValueObject* lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd::m_start = nullptr private
A non-owning pointer to slice_array.__vp_.
Definition at line 69 of file LibCxxSliceArray.cpp.
Referenced by GetChildAtIndex(), GetIndexOfChildWithName(), and Update().
m_stride
size_t lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd::m_stride = 0 private
slice_array.__stride_.
Definition at line 73 of file LibCxxSliceArray.cpp.
Referenced by GetChildAtIndex(), and Update().
The documentation for this class was generated from the following file:
LibCxxSliceArray.cpp