LLDB: lldb_private::ScriptedThreadPlanPythonInterface Class Reference
lldb_private::ScriptedThreadPlanPythonInterface Class Reference
#include <ScriptedThreadPlanPythonInterface.h>
Public Member Functions
ScriptedThreadPlanPythonInterface (ScriptInterpreterPythonImpl &interpreter)
llvm::Expected< StructuredData::GenericSP > CreatePluginObject (const llvm::StringRef class_name, lldb::ThreadPlanSP thread_plan_sp, const StructuredDataImpl &args_sp) override
llvm::SmallVector< AbstractMethodRequirement > GetAbstractMethodRequirements () const override
llvm::Expected< bool > ExplainsStop (Event *event) override
llvm::Expected< bool > ShouldStop (Event *event) override
llvm::Expected< bool > IsStale () override
lldb::StateType GetRunState () override
llvm::Error GetStopDescription (lldb::StreamSP &stream) override
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::ScriptedInterface
ScriptedInterface ()=default
virtual ~ScriptedInterface ()=default
StructuredData::GenericSP GetScriptObjectInstance ()
llvm::SmallVector< llvm::StringLiteral > const GetAbstractMethods () const
Public Member Functions inherited from lldb_private::ScriptedPythonInterface
ScriptedPythonInterface (ScriptInterpreterPythonImpl &interpreter)
~ScriptedPythonInterface () override=default
llvm::Expected< FileSpec > GetScriptedModulePath () override
llvm::Expected< std::map< llvm::StringLiteral, AbstractMethodCheckerPayload > > CheckAbstractMethodImplementation (const python::PythonDictionary &class_dict) const
template<typename... Args>
llvm::Expected< StructuredData::GenericSP > CreatePluginObject (llvm::StringRef class_name, StructuredData::Generic *script_obj, Args... args)
template<typename T = StructuredData::ObjectSP, typename... Args>
T CallStaticMethod (llvm::StringRef class_name, llvm::StringRef method_name, Status &error, Args &&...args)
Call a static method on a Python class without creating an instance.
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
Static Public Member Functions inherited from lldb_private::ScriptedInterface
template<typename Ret>
static Ret ErrorWithMessage (llvm::StringRef caller_name, llvm::StringRef error_msg, Status &error, LLDBLog log_category=LLDBLog::Process)
template<typename T = StructuredData::ObjectSP>
static bool CheckStructuredDataObject (llvm::StringRef caller, T obj, Status &error)
static bool CreateInstance (lldb::ScriptLanguage language, ScriptedInterfaceUsages usages)
Additional Inherited Members
Public Types inherited from lldb_private::ScriptedPythonInterface
enum class AbstractMethodCheckerCases {
eNotImplemented , eNotAllocated , eNotCallable , eUnknownArgumentCount ,
eInvalidArgumentCount , eValid
}
Protected Member Functions inherited from lldb_private::ScriptedPythonInterface
template<typename T = StructuredData::ObjectSP>
T ExtractValueFromPythonObject (python::PythonObject &p, Status &error)
template<typename T = StructuredData::ObjectSP, typename... Args>
T Dispatch (llvm::StringRef method_name, Status &error, Args &&...args)
template<typename... Args>
Status GetStatusFromMethod (llvm::StringRef method_name, Args &&...args)
template<typename T>
T Transform (T object)
python::PythonObject Transform (bool arg)
python::PythonObject Transform (const Status &arg)
python::PythonObject Transform (Status &&arg)
python::PythonObject Transform (const StructuredDataImpl &arg)
python::PythonObject Transform (lldb::ExecutionContextRefSP arg)
python::PythonObject Transform (lldb::TargetSP arg)
python::PythonObject Transform (lldb::BreakpointSP arg)
python::PythonObject Transform (lldb::BreakpointLocationSP arg)
python::PythonObject Transform (lldb::ProcessSP arg)
python::PythonObject Transform (lldb::ThreadSP arg)
python::PythonObject Transform (lldb::StackFrameListSP arg)
python::PythonObject Transform (lldb::ThreadPlanSP arg)
python::PythonObject Transform (lldb::ProcessAttachInfoSP arg)
python::PythonObject Transform (lldb::ProcessLaunchInfoSP arg)
python::PythonObject Transform (Event *arg)
python::PythonObject Transform (const SymbolContext &arg)
python::PythonObject Transform (lldb::StreamSP arg)
python::PythonObject Transform (lldb::StackFrameSP arg)
python::PythonObject Transform (lldb::DataExtractorSP arg)
python::PythonObject Transform (lldb::DescriptionLevel arg)
python::PythonObject Transform (lldb::ValueObjectSP arg)
template<typename T, typename U>
void ReverseTransform (T &original_arg, U transformed_arg, Status &error)
template<typename T>
void ReverseTransform (T &original_arg, python::PythonObject transformed_arg, Status &error)
void ReverseTransform (bool &original_arg, python::PythonObject transformed_arg, Status &error)
template<std::size_t... I, typename... Args>
auto TransformTuple (const std::tuple< Args... > &args, std::index_sequence< I... >)
template<typename... Args>
auto TransformArgs (const std::tuple< Args... > &args)
template<typename T, typename U>
void TransformBack (T &original_arg, U transformed_arg, Status &error)
template<std::size_t... I, typename... Ts, typename... Us>
bool ReassignPtrsOrRefsArgs (std::tuple< Ts... > &original_args, std::tuple< Us... > &transformed_args, std::index_sequence< I... >)
template<typename... Ts, typename... Us>
bool ReassignPtrsOrRefsArgs (std::tuple< Ts... > &original_args, std::tuple< Us... > &transformed_args)
template<typename T, typename... Args>
void FormatArgs (std::string &fmt, T arg, Args... args) const
template<typename T>
void FormatArgs (std::string &fmt, T arg) const
void FormatArgs (std::string &fmt) const
template<>
Status ExtractValueFromPythonObject (python::PythonObject &p, Status &error)
template<>
Event * ExtractValueFromPythonObject (python::PythonObject &p, Status &error)
template<>
SymbolContext ExtractValueFromPythonObject (python::PythonObject &p, Status &error)
template<>
Status ExtractValueFromPythonObject (python::PythonObject &p, Status &error)
template<>
Event * ExtractValueFromPythonObject (python::PythonObject &p, Status &error)
template<>
SymbolContext ExtractValueFromPythonObject (python::PythonObject &p, Status &error)
Protected Attributes inherited from lldb_private::ScriptedInterface
StructuredData::GenericSP m_object_instance_sp
Protected Attributes inherited from lldb_private::ScriptedPythonInterface
ScriptInterpreterPythonImpl & m_interpreter
Detailed Description
Definition at line 19 of file ScriptedThreadPlanPythonInterface.h.
Constructor & Destructor Documentation
ScriptedThreadPlanPythonInterface()
ScriptedThreadPlanPythonInterface::ScriptedThreadPlanPythonInterface (ScriptInterpreterPythonImpl & interpreter)
Definition at line 26 of file ScriptedThreadPlanPythonInterface.cpp.
References lldb_private::ScriptedPythonInterface::ScriptedPythonInterface().
Member Function Documentation
CreatePluginObject()
llvm::Expected< StructuredData::GenericSP > ScriptedThreadPlanPythonInterface::CreatePluginObject (const llvm::StringRef class_name, lldb::ThreadPlanSP thread_plan_sp, const StructuredDataImpl & args_sp) override virtual
Implements lldb_private::ScriptedThreadPlanInterface.
Definition at line 31 of file ScriptedThreadPlanPythonInterface.cpp.
References lldb_private::ScriptedPythonInterface::CreatePluginObject().
ExplainsStop()
llvm::Expected< bool > ScriptedThreadPlanPythonInterface::ExplainsStop (Event * event) override virtual
Reimplemented from lldb_private::ScriptedThreadPlanInterface.
Definition at line 39 of file ScriptedThreadPlanPythonInterface.cpp.
References lldb_private::ScriptedInterface::CheckStructuredDataObject(), lldb_private::ScriptedPythonInterface::Dispatch(), and error().
GetAbstractMethodRequirements()
llvm::SmallVector< AbstractMethodRequirement > lldb_private::ScriptedThreadPlanPythonInterface::GetAbstractMethodRequirements () const inline override virtual
Implements lldb_private::ScriptedInterface.
Definition at line 31 of file ScriptedThreadPlanPythonInterface.h.
GetPluginName()
llvm::StringRef lldb_private::ScriptedThreadPlanPythonInterface::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 53 of file ScriptedThreadPlanPythonInterface.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::ScriptedThreadPlanPythonInterface::GetPluginNameStatic () inline static
Definition at line 49 of file ScriptedThreadPlanPythonInterface.h.
Referenced by GetPluginName(), and Initialize().
GetRunState()
lldb::StateType ScriptedThreadPlanPythonInterface::GetRunState () override virtual
Reimplemented from lldb_private::ScriptedThreadPlanInterface.
Definition at line 82 of file ScriptedThreadPlanPythonInterface.cpp.
References lldb_private::ScriptedInterface::CheckStructuredDataObject(), lldb_private::ScriptedPythonInterface::Dispatch(), error(), and lldb::eStateStepping.
GetStopDescription()
llvm::Error ScriptedThreadPlanPythonInterface::GetStopDescription (lldb::StreamSP & stream) override virtual
Reimplemented from lldb_private::ScriptedThreadPlanInterface.
Definition at line 95 of file ScriptedThreadPlanPythonInterface.cpp.
References lldb_private::ScriptedPythonInterface::Dispatch(), and error().
Initialize()
void ScriptedThreadPlanPythonInterface::Initialize () static
Definition at line 105 of file ScriptedThreadPlanPythonInterface.cpp.
References lldb_private::ScriptedInterface::CreateInstance(), lldb::eScriptLanguagePython, GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Referenced by lldb_private::ScriptInterpreterPythonInterfaces::Initialize().
IsStale()
llvm::Expected< bool > ScriptedThreadPlanPythonInterface::IsStale () override virtual
Reimplemented from lldb_private::ScriptedThreadPlanInterface.
Definition at line 68 of file ScriptedThreadPlanPythonInterface.cpp.
References lldb_private::ScriptedInterface::CheckStructuredDataObject(), lldb_private::ScriptedPythonInterface::Dispatch(), and error().
ShouldStop()
llvm::Expected< bool > ScriptedThreadPlanPythonInterface::ShouldStop (Event * event) override virtual
Reimplemented from lldb_private::ScriptedThreadPlanInterface.
Definition at line 54 of file ScriptedThreadPlanPythonInterface.cpp.
References lldb_private::ScriptedInterface::CheckStructuredDataObject(), lldb_private::ScriptedPythonInterface::Dispatch(), and error().
Terminate()
void ScriptedThreadPlanPythonInterface::Terminate () static
Definition at line 116 of file ScriptedThreadPlanPythonInterface.cpp.
References lldb_private::ScriptedInterface::CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Referenced by lldb_private::ScriptInterpreterPythonInterfaces::Terminate().
The documentation for this class was generated from the following files:
ScriptedThreadPlanPythonInterface.h
ScriptedThreadPlanPythonInterface.cpp