LLDB: RegisterContextDarwin_riscv32_Mach Class Reference
RegisterContextDarwin_riscv32_Mach Class Reference
Public Member Functions
RegisterContextDarwin_riscv32_Mach (lldb_private::Thread &thread, const DataExtractor &data)
void InvalidateAllRegisters () override
void SetRegisterDataFrom_LC_THREAD (const DataExtractor &data)
Public Member Functions inherited from RegisterContextDarwin_riscv32
RegisterContextDarwin_riscv32 (lldb_private::Thread &thread, uint32_t concrete_frame_idx)
~RegisterContextDarwin_riscv32 () override
size_t GetRegisterCount () override
const lldb_private::RegisterInfo * GetRegisterInfoAtIndex (size_t reg) override
size_t GetRegisterSetCount () override
const lldb_private::RegisterSet * GetRegisterSet (size_t set) override
bool ReadRegister (const lldb_private::RegisterInfo *reg_info, lldb_private::RegisterValue &value) override
bool WriteRegister (const lldb_private::RegisterInfo *reg_info, const lldb_private::RegisterValue &value) override
bool ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp) override
bool WriteAllRegisterValues (const lldb::DataBufferSP &data_sp) override
uint32_t ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num) override
Convert from a given register numbering scheme to the lldb register numbering scheme.
Public Member Functions inherited from lldb_private::RegisterContext
RegisterContext (Thread &thread, uint32_t concrete_frame_idx)
~RegisterContext () override
void InvalidateIfNeeded (bool force)
virtual lldb::ByteOrder GetByteOrder ()
virtual bool RegisterWriteCausesReconfigure (const llvm::StringRef name)
virtual bool ReconfigureRegisterInfo ()
virtual bool ReadAllRegisterValues (lldb_private::RegisterCheckpoint &reg_checkpoint)
virtual bool WriteAllRegisterValues (const lldb_private::RegisterCheckpoint &reg_checkpoint)
bool CopyFromRegisterContext (lldb::RegisterContextSP context)
virtual uint32_t NumSupportedHardwareBreakpoints ()
virtual uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual bool ClearHardwareBreakpoint (uint32_t hw_idx)
virtual uint32_t NumSupportedHardwareWatchpoints ()
virtual uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, bool read, bool write)
virtual bool ClearHardwareWatchpoint (uint32_t hw_index)
virtual bool HardwareSingleStep (bool enable)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, uint32_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, uint32_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual Thread & GetThread ()
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num)
uint64_t GetPC (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetThreadPointer (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool GetPCForSymbolication (Address &address)
Get an address suitable for symbolication.
bool SetPC (uint64_t pc)
bool SetPC (Address addr)
uint64_t GetSP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetSP (uint64_t sp)
uint64_t GetFP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetFP (uint64_t fp)
const char * GetRegisterName (uint32_t reg)
uint64_t GetReturnAddress (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetFlags (uint64_t fail_value=0)
uint64_t ReadRegisterAsUnsigned (uint32_t reg, uint64_t fail_value)
uint64_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, uint64_t fail_value)
bool WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
bool WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
bool ConvertBetweenRegisterKinds (lldb::RegisterKind source_rk, uint32_t source_regnum, lldb::RegisterKind target_rk, uint32_t &target_regnum)
lldb::TargetSP CalculateTarget () override
lldb::ProcessSP CalculateProcess () override
lldb::ThreadSP CalculateThread () override
lldb::StackFrameSP CalculateStackFrame () override
void CalculateExecutionContext (ExecutionContext &exe_ctx) override
Reconstruct the object's execution context into sc.
uint32_t GetStopID () const
void SetStopID (uint32_t stop_id)
Public Member Functions inherited from lldb_private::ExecutionContextScope
virtual ~ExecutionContextScope ()=default
Static Public Member Functions
static bool Create_LC_THREAD (Thread *thread, Stream &data)
Protected Member Functions
int DoReadGPR (lldb::tid_t tid, int flavor, GPR &gpr) override
int DoReadFPU (lldb::tid_t tid, int flavor, FPU &fpu) override
int DoReadEXC (lldb::tid_t tid, int flavor, EXC &exc) override
int DoReadCSR (lldb::tid_t tid, int flavor, CSR &csr) override
int DoWriteGPR (lldb::tid_t tid, int flavor, const GPR &gpr) override
int DoWriteFPU (lldb::tid_t tid, int flavor, const FPU &fpu) override
int DoWriteEXC (lldb::tid_t tid, int flavor, const EXC &exc) override
int DoWriteCSR (lldb::tid_t tid, int flavor, const CSR &csr) override
Protected Member Functions inherited from RegisterContextDarwin_riscv32
void InvalidateAllRegisterStates ()
int GetError (int flavor, uint32_t err_idx) const
bool SetError (int flavor, uint32_t err_idx, int err)
bool RegisterSetIsCached (int set) const
void LogGPR (lldb_private::Log *log, const char *title)
int ReadGPR (bool force)
int ReadFPU (bool force)
int ReadEXC (bool force)
int ReadCSR (bool force)
int WriteGPR ()
int WriteFPU ()
int WriteEXC ()
int WriteCSR ()
int ReadRegisterSet (uint32_t set, bool force)
int WriteRegisterSet (uint32_t set)
Protected Member Functions inherited from lldb_private::RegisterContext
virtual bool BehavesLikeZerothFrame () const
Indicates that this frame is currently executing code, that the PC value is not a return-pc but an actual executing instruction.
Additional Inherited Members
Protected Types inherited from RegisterContextDarwin_riscv32
enum {
GPRRegSet = 2 , EXCRegSet = 3 , FPURegSet = 4 , CSRRegSet1 = 6 ,
CSRRegSet2 = 7 , CSRRegSet3 = 8 , CSRRegSet4 = 9 , CSRRegSet = 10
}
enum { GPRWordCount = sizeof(GPR) / sizeof(uint32_t) , FPUWordCount = sizeof(FPU) / sizeof(uint32_t) , EXCWordCount = sizeof(EXC) / sizeof(uint32_t) , CSRWordCount = sizeof(CSR) / sizeof(uint32_t) }
enum { Read = 0 , Write = 1 , kNumErrors = 2 }
Static Protected Member Functions inherited from RegisterContextDarwin_riscv32
static uint32_t GetRegisterNumber (uint32_t reg_kind, uint32_t reg_num)
static int GetSetForNativeRegNum (int reg_num)
static size_t GetRegisterInfosCount ()
static const lldb_private::RegisterInfo * GetRegisterInfos ()
Protected Attributes inherited from RegisterContextDarwin_riscv32
GPR gpr
FPU fpr
EXC exc
CSR csr
int gpr_errs [2]
int fpr_errs [2]
int exc_errs [2]
int csr_errs [2]
Protected Attributes inherited from lldb_private::RegisterContext
Thread & m_thread
uint32_t m_concrete_frame_idx
uint32_t m_stop_id
Detailed Description
Definition at line 618 of file ObjectFileMachO.cpp.
Constructor & Destructor Documentation
RegisterContextDarwin_riscv32_Mach()
RegisterContextDarwin_riscv32_Mach::RegisterContextDarwin_riscv32_Mach (lldb_private::Thread & thread, const DataExtractor & data) inline
Definition at line 621 of file ObjectFileMachO.cpp.
References RegisterContextDarwin_riscv32::RegisterContextDarwin_riscv32(), and SetRegisterDataFrom_LC_THREAD().
Member Function Documentation
Create_LC_THREAD()
bool RegisterContextDarwin_riscv32_Mach::Create_LC_THREAD (Thread * thread, Stream & data) inline static
Definition at line 673 of file ObjectFileMachO.cpp.
References RegisterContextDarwin_riscv32::EXCRegSet, RegisterContextDarwin_riscv32::EXCWordCount, RegisterContextDarwin_riscv32::GPRRegSet, RegisterContextDarwin_riscv32::GPRWordCount, PrintRegisterValue(), and lldb_private::Stream::PutHex32().
Referenced by ObjectFileMachO::SaveCore().
DoReadCSR()
int RegisterContextDarwin_riscv32_Mach::DoReadCSR (lldb::tid_t tid, int flavor, CSR & csr) inline override protected virtual
Implements RegisterContextDarwin_riscv32.
Definition at line 733 of file ObjectFileMachO.cpp.
References RegisterContextDarwin_riscv32::csr.
DoReadEXC()
int RegisterContextDarwin_riscv32_Mach::DoReadEXC (lldb::tid_t tid, int flavor, EXC & exc) inline override protected virtual
Implements RegisterContextDarwin_riscv32.
Definition at line 731 of file ObjectFileMachO.cpp.
References RegisterContextDarwin_riscv32::exc.
DoReadFPU()
int RegisterContextDarwin_riscv32_Mach::DoReadFPU (lldb::tid_t tid, int flavor, FPU & fpu) inline override protected virtual
Implements RegisterContextDarwin_riscv32.
Definition at line 729 of file ObjectFileMachO.cpp.
DoReadGPR()
int RegisterContextDarwin_riscv32_Mach::DoReadGPR (lldb::tid_t tid, int flavor, GPR & gpr) inline override protected virtual
Implements RegisterContextDarwin_riscv32.
Definition at line 727 of file ObjectFileMachO.cpp.
References RegisterContextDarwin_riscv32::gpr.
DoWriteCSR()
int RegisterContextDarwin_riscv32_Mach::DoWriteCSR (lldb::tid_t tid, int flavor, const CSR & csr) inline override protected virtual
Implements RegisterContextDarwin_riscv32.
Definition at line 747 of file ObjectFileMachO.cpp.
References RegisterContextDarwin_riscv32::csr.
DoWriteEXC()
int RegisterContextDarwin_riscv32_Mach::DoWriteEXC (lldb::tid_t tid, int flavor, const EXC & exc) inline override protected virtual
Implements RegisterContextDarwin_riscv32.
Definition at line 743 of file ObjectFileMachO.cpp.
References RegisterContextDarwin_riscv32::exc.
DoWriteFPU()
int RegisterContextDarwin_riscv32_Mach::DoWriteFPU (lldb::tid_t tid, int flavor, const FPU & fpu) inline override protected virtual
Implements RegisterContextDarwin_riscv32.
Definition at line 739 of file ObjectFileMachO.cpp.
DoWriteGPR()
int RegisterContextDarwin_riscv32_Mach::DoWriteGPR (lldb::tid_t tid, int flavor, const GPR & gpr) inline override protected virtual
Implements RegisterContextDarwin_riscv32.
Definition at line 735 of file ObjectFileMachO.cpp.
References RegisterContextDarwin_riscv32::gpr.
InvalidateAllRegisters()
void RegisterContextDarwin_riscv32_Mach::InvalidateAllRegisters () inline override virtual
Reimplemented from RegisterContextDarwin_riscv32.
Definition at line 627 of file ObjectFileMachO.cpp.
SetRegisterDataFrom_LC_THREAD()
void RegisterContextDarwin_riscv32_Mach::SetRegisterDataFrom_LC_THREAD (const DataExtractor & data) inline
Definition at line 631 of file ObjectFileMachO.cpp.
References RegisterContextDarwin_riscv32::CSRRegSet, RegisterContextDarwin_riscv32::exc, RegisterContextDarwin_riscv32::EXCRegSet, RegisterContextDarwin_riscv32::fpr, RegisterContextDarwin_riscv32::FPURegSet, lldb_private::DataExtractor::GetByteSize(), lldb_private::DataExtractor::GetU32(), RegisterContextDarwin_riscv32::gpr, RegisterContextDarwin_riscv32::GPRRegSet, RegisterContextDarwin_riscv32::Read, and RegisterContextDarwin_riscv32::SetError().
Referenced by RegisterContextDarwin_riscv32_Mach().
The documentation for this class was generated from the following file:
ObjectFileMachO.cpp