LLDB: lldb_private::DataVisualization::NamedSummaryFormats Class Reference
lldb_private::DataVisualization::NamedSummaryFormats Class Reference
#include <DataVisualization.h>
Static Public Member Functions
static bool GetSummaryFormat (ConstString type, lldb::TypeSummaryImplSP &entry)
static void Add (ConstString type, const lldb::TypeSummaryImplSP &entry)
static bool Delete (ConstString type)
static void Clear ()
static void ForEach (std::function< bool(const TypeMatcher &, const lldb::TypeSummaryImplSP &)> callback)
static uint32_t GetCount ()
Detailed Description
Definition at line 60 of file DataVisualization.h.
Member Function Documentation
Add()
void DataVisualization::NamedSummaryFormats::Add (ConstString type, const lldb::TypeSummaryImplSP & entry) static
Definition at line 175 of file DataVisualization.cpp.
References lldb_private::FormattersContainer< ValueType >::Add(), GetFormatManager(), and lldb_private::FormatManager::GetNamedSummaryContainer().
Clear()
void DataVisualization::NamedSummaryFormats::Clear () static
Definition at line 184 of file DataVisualization.cpp.
References lldb_private::FormattersContainer< ValueType >::Clear(), GetFormatManager(), and lldb_private::FormatManager::GetNamedSummaryContainer().
Referenced by CommandObjectTypeCategoryDefine::CommandOptions::OptionParsingStarting().
Delete()
bool DataVisualization::NamedSummaryFormats::Delete (ConstString type) static
Definition at line 180 of file DataVisualization.cpp.
References lldb_private::FormattersContainer< ValueType >::Delete(), GetFormatManager(), and lldb_private::FormatManager::GetNamedSummaryContainer().
ForEach()
void DataVisualization::NamedSummaryFormats::ForEach (std::function< bool(const TypeMatcher &, const lldb::TypeSummaryImplSP &)> callback) static
Definition at line 188 of file DataVisualization.cpp.
References lldb_private::FormattersContainer< ValueType >::ForEach(), GetFormatManager(), and lldb_private::FormatManager::GetNamedSummaryContainer().
Referenced by CommandObjectTypeCategoryDefine::GetOptions().
GetCount()
uint32_t DataVisualization::NamedSummaryFormats::GetCount () static
Definition at line 194 of file DataVisualization.cpp.
References lldb_private::FormattersContainer< ValueType >::GetCount(), GetFormatManager(), and lldb_private::FormatManager::GetNamedSummaryContainer().
Referenced by CommandObjectTypeCategoryDefine::GetOptions().
GetSummaryFormat()
bool DataVisualization::NamedSummaryFormats::GetSummaryFormat (ConstString type, lldb::TypeSummaryImplSP & entry) static
Definition at line 170 of file DataVisualization.cpp.
References lldb_private::FormattersContainer< ValueType >::GetExact(), GetFormatManager(), and lldb_private::FormatManager::GetNamedSummaryContainer().
Referenced by ValidateNamedSummary().
The documentation for this class was generated from the following files:
DataVisualization.h
DataVisualization.cpp