LLDB: lldb::SBTypeFormat Class Reference
lldb::SBTypeFormat Class Reference
#include <SBTypeFormat.h>
Public Member Functions
SBTypeFormat ()
SBTypeFormat (lldb::Format format, uint32_t options=0)
SBTypeFormat (const char *type, uint32_t options=0)
SBTypeFormat (const lldb::SBTypeFormat &rhs)
~SBTypeFormat ()
operator bool () const
bool IsValid () const
lldb::Format GetFormat ()
const char * GetTypeName ()
uint32_t GetOptions ()
void SetFormat (lldb::Format)
void SetTypeName (const char *)
void SetOptions (uint32_t)
bool GetDescription (lldb::SBStream &description, lldb::DescriptionLevel description_level)
lldb::SBTypeFormat & operator= (const lldb::SBTypeFormat &rhs)
bool IsEqualTo (lldb::SBTypeFormat &rhs)
bool operator== (lldb::SBTypeFormat &rhs)
bool operator!= (lldb::SBTypeFormat &rhs)
Protected Types
enum class Type { eTypeKeepSame , eTypeFormat , eTypeEnum }
Protected Member Functions
lldb::TypeFormatImplSP GetSP ()
void SetSP (const lldb::TypeFormatImplSP &typeformat_impl_sp)
SBTypeFormat (const lldb::TypeFormatImplSP &)
bool CopyOnWrite_Impl (Type)
Protected Attributes
lldb::TypeFormatImplSP m_opaque_sp
Friends
class SBDebugger
class SBTypeCategory
class SBValue
Detailed Description
Definition at line 17 of file SBTypeFormat.h.
Member Enumeration Documentation
Type
enum class lldb::SBTypeFormat::Type strong protected
Enumerator
eTypeKeepSame
eTypeFormat
eTypeEnum
Definition at line 71 of file SBTypeFormat.h.
Constructor & Destructor Documentation
SBTypeFormat() [1/5]
SBTypeFormat::SBTypeFormat ()
Definition at line 19 of file SBTypeFormat.cpp.
References LLDB_INSTRUMENT_VA.
SBTypeFormat() [2/5]
SBTypeFormat::SBTypeFormat (lldb::Format format, uint32_t options = 0)
Definition at line 21 of file SBTypeFormat.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
SBTypeFormat() [3/5]
SBTypeFormat::SBTypeFormat (const char * type, uint32_t options = 0)
Definition at line 27 of file SBTypeFormat.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
SBTypeFormat() [4/5]
SBTypeFormat::SBTypeFormat (const lldb::SBTypeFormat & rhs)
Definition at line 33 of file SBTypeFormat.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
~SBTypeFormat()
SBTypeFormat::~SBTypeFormat () default
References GetDescription(), GetFormat(), GetOptions(), GetTypeName(), IsEqualTo(), IsValid(), operator!=(), operator=(), operator==(), SetFormat(), SetOptions(), and SetTypeName().
SBTypeFormat() [5/5]
SBTypeFormat::SBTypeFormat (const lldb::TypeFormatImplSP & typeformat_impl_sp) protected
Definition at line 153 of file SBTypeFormat.cpp.
References m_opaque_sp.
Member Function Documentation
CopyOnWrite_Impl()
bool SBTypeFormat::CopyOnWrite_Impl (Type type) protected
Definition at line 156 of file SBTypeFormat.cpp.
References eTypeEnum, lldb_private::TypeFormatImpl::eTypeEnum, eTypeFormat, lldb_private::TypeFormatImpl::eTypeFormat, eTypeKeepSame, GetFormat(), GetOptions(), GetTypeName(), IsValid(), m_opaque_sp, and SetSP().
Referenced by SetFormat(), SetOptions(), and SetTypeName().
GetDescription()
bool SBTypeFormat::GetDescription (lldb::SBStream & description, lldb::DescriptionLevel description_level)
Definition at line 98 of file SBTypeFormat.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeFormat().
GetFormat()
lldb::Format SBTypeFormat::GetFormat ()
Definition at line 50 of file SBTypeFormat.cpp.
References lldb::eFormatInvalid, lldb_private::TypeFormatImpl::eTypeFormat, IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by CopyOnWrite_Impl(), IsEqualTo(), and ~SBTypeFormat().
GetOptions()
uint32_t SBTypeFormat::GetOptions ()
Definition at line 68 of file SBTypeFormat.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by CopyOnWrite_Impl(), IsEqualTo(), and ~SBTypeFormat().
GetSP()
lldb::TypeFormatImplSP SBTypeFormat::GetSP () protected
Definition at line 147 of file SBTypeFormat.cpp.
References m_opaque_sp.
Referenced by lldb::SBTypeCategory::AddTypeFormat(), and SBValue.
GetTypeName()
const char * SBTypeFormat::GetTypeName ()
Definition at line 58 of file SBTypeFormat.cpp.
References lldb_private::TypeFormatImpl::eTypeEnum, IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by CopyOnWrite_Impl(), and ~SBTypeFormat().
IsEqualTo()
bool SBTypeFormat::IsEqualTo (lldb::SBTypeFormat & rhs)
Definition at line 127 of file SBTypeFormat.cpp.
References GetFormat(), GetOptions(), IsValid(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTypeFormat().
IsValid()
bool SBTypeFormat::IsValid () const
Definition at line 40 of file SBTypeFormat.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBTypeCategory::AddTypeFormat(), CopyOnWrite_Impl(), GetDescription(), GetFormat(), GetOptions(), GetTypeName(), IsEqualTo(), operator!=(), operator==(), and ~SBTypeFormat().
operator bool()
SBTypeFormat::operator bool () const explicit
Definition at line 44 of file SBTypeFormat.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator!=()
bool SBTypeFormat::operator!= (lldb::SBTypeFormat & rhs)
Definition at line 139 of file SBTypeFormat.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeFormat().
operator=()
lldb::SBTypeFormat & SBTypeFormat::operator= (const lldb::SBTypeFormat & rhs)
Definition at line 110 of file SBTypeFormat.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeFormat().
operator==()
bool SBTypeFormat::operator== (lldb::SBTypeFormat & rhs)
Definition at line 119 of file SBTypeFormat.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeFormat().
SetFormat()
void SBTypeFormat::SetFormat (lldb::Format fmt)
Definition at line 76 of file SBTypeFormat.cpp.
References CopyOnWrite_Impl(), eTypeFormat, LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeFormat().
SetOptions()
void SBTypeFormat::SetOptions (uint32_t value)
Definition at line 91 of file SBTypeFormat.cpp.
References CopyOnWrite_Impl(), eTypeKeepSame, LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeFormat().
SetSP()
void SBTypeFormat::SetSP (const lldb::TypeFormatImplSP & typeformat_impl_sp) protected
Definition at line 149 of file SBTypeFormat.cpp.
References m_opaque_sp.
Referenced by CopyOnWrite_Impl(), lldb::SBValue::GetTypeFormat(), and SBValue.
SetTypeName()
void SBTypeFormat::SetTypeName (const char * type)
Definition at line 83 of file SBTypeFormat.cpp.
References CopyOnWrite_Impl(), eTypeEnum, LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeFormat().
Friends And Related Symbol Documentation
SBDebugger
friend class SBDebugger friend
Definition at line 59 of file SBTypeFormat.h.
References SBDebugger.
Referenced by SBDebugger.
SBTypeCategory
friend class SBTypeCategory friend
Definition at line 60 of file SBTypeFormat.h.
References SBTypeCategory.
Referenced by SBTypeCategory.
SBValue
friend class SBValue friend
Definition at line 61 of file SBTypeFormat.h.
References GetSP(), SBValue, and SetSP().
Referenced by SBValue.
Member Data Documentation
m_opaque_sp
lldb::TypeFormatImplSP lldb::SBTypeFormat::m_opaque_sp protected
Definition at line 67 of file SBTypeFormat.h.
Referenced by CopyOnWrite_Impl(), GetDescription(), GetFormat(), GetOptions(), GetSP(), GetTypeName(), operator bool(), operator!=(), operator=(), operator==(), SBTypeFormat(), SBTypeFormat(), SBTypeFormat(), SBTypeFormat(), SetFormat(), SetOptions(), SetSP(), and SetTypeName().
The documentation for this class was generated from the following files:
SBTypeFormat.h
SBTypeFormat.cpp