LLDB: lldb_private::BreakpointOptions Class Reference
lldb_private::BreakpointOptions Class Reference
"lldb/Breakpoint/BreakpointOptions.h" Class that manages the options on a breakpoint or breakpoint location.
#include <BreakpointOptions.h>
Classes
class CommandBaton
struct CommandData
Public Types
enum OptionKind {
eCallback = 1 << 0 , eEnabled = 1 << 1 , eOneShot = 1 << 2 , eIgnoreCount = 1 << 3 ,
eThreadSpec = 1 << 4 , eCondition = 1 << 5 , eAutoContinue = 1 << 6 , eAllOptions
}
typedef std::shared_ptr< CommandBaton > CommandBatonSP
Public Member Functions
BreakpointOptions (const char *condition, bool enabled=true, int32_t ignore=0, bool one_shot=false, bool auto_continue=false)
This constructor allows you to specify all the breakpoint options except the callback.
BreakpointOptions (bool all_flags_set)
Breakpoints make options with all flags set.
BreakpointOptions (const BreakpointOptions &rhs)
virtual ~BreakpointOptions ()
virtual StructuredData::ObjectSP SerializeToStructuredData ()
const BreakpointOptions & operator= (const BreakpointOptions &rhs)
void CopyOverSetOptions (const BreakpointOptions &rhs)
Copy over only the options set in the incoming BreakpointOptions.
void SetCallback (BreakpointHitCallback callback, const lldb::BatonSP &baton_sp, bool synchronous=false)
Adds a callback to the breakpoint option set.
void SetCallback (BreakpointHitCallback callback, const BreakpointOptions::CommandBatonSP &command_baton_sp, bool synchronous=false)
bool GetCommandLineCallbacks (StringList &command_list)
Returns the command line commands for the callback on this breakpoint.
void ClearCallback ()
Remove the callback from this option set.
bool InvokeCallback (StoppointCallbackContext *context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id)
Use this function to invoke the callback for a specific stop.
bool IsCallbackSynchronous () const
Used in InvokeCallback to tell whether it is the right time to run this kind of callback.
Baton * GetBaton ()
Fetch the baton from the callback.
const Baton * GetBaton () const
Fetch a const version of the baton from the callback.
void SetCondition (StopCondition condition)
Set the breakpoint stop condition.
const StopCondition & GetCondition () const
Return the breakpoint condition.
StopCondition & GetCondition ()
bool IsEnabled () const
Check the Enable/Disable state.
void SetEnabled (bool enabled)
If enable is true, enable the breakpoint, if false disable it.
bool IsAutoContinue () const
Check the auto-continue state.
void SetAutoContinue (bool auto_continue)
Set the auto-continue state.
bool IsOneShot () const
Check the One-shot state.
void SetOneShot (bool one_shot)
If enable is true, enable the breakpoint, if false disable it.
void SetIgnoreCount (uint32_t n)
Set the breakpoint to ignore the next count breakpoint hits.
uint32_t GetIgnoreCount () const
Return the current Ignore Count.
const ThreadSpec * GetThreadSpecNoCreate () const
Return the current thread spec for this option.
ThreadSpec * GetThreadSpec ()
Returns a pointer to the ThreadSpec for this option, creating it.
void SetThreadID (lldb::tid_t thread_id)
void GetDescription (Stream *s, lldb::DescriptionLevel level) const
bool HasCallback () const
Check if the breakpoint option has a callback set.
void SetCommandDataCallback (std::unique_ptr< CommandData > &cmd_data)
Set a callback based on BreakpointOptions::CommandData.
void Clear ()
bool AnySet () const
Static Public Member Functions
static std::unique_ptr< BreakpointOptions > CreateFromStructuredData (Target &target, const StructuredData::Dictionary &data_dict, Status &error)
static const char * GetSerializationKey ()
static bool NullCallback (void *baton, StoppointCallbackContext *context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id)
This is the default empty callback.
Protected Types
enum class OptionNames {
ConditionText = 0 , IgnoreCount , EnabledState , OneShotState ,
AutoContinue , LastOptionName
}
Protected Member Functions
bool IsOptionSet (OptionKind kind)
void SetThreadSpec (std::unique_ptr< ThreadSpec > &thread_spec_up)
Static Protected Member Functions
static const char * GetKey (OptionNames enum_value)
static bool BreakpointOptionsCallbackFunction (void *baton, StoppointCallbackContext *context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id)
Static Protected Attributes
static const char * g_option_names [(size_t) OptionNames::LastOptionName]
Private Attributes
BreakpointHitCallback m_callback
For BreakpointOptions only.
lldb::BatonSP m_callback_baton_sp
This is the client data for the callback.
bool m_baton_is_command_baton
bool m_callback_is_synchronous
bool m_enabled
bool m_one_shot
If set, the breakpoint delete itself after being hit once.
uint32_t m_ignore_count
Number of times to ignore this breakpoint.
std::unique_ptr< ThreadSpec > m_thread_spec_up
Thread for which this breakpoint will stop.
StopCondition m_condition
The condition to test.
bool m_inject_condition
If set, inject breakpoint condition into process.
bool m_auto_continue
If set, auto-continue from breakpoint.
Flags m_set_flags
Which options are set at this level.
Friends
class BreakpointLocation
class BreakpointName
class lldb_private::BreakpointOptionGroup
class Breakpoint
Detailed Description
"lldb/Breakpoint/BreakpointOptions.h" Class that manages the options on a breakpoint or breakpoint location.
Definition at line 28 of file BreakpointOptions.h.
Member Typedef Documentation
CommandBatonSP
typedef std::shared_ptr<CommandBaton> lldb_private::BreakpointOptions::CommandBatonSP
Definition at line 94 of file BreakpointOptions.h.
Member Enumeration Documentation
OptionKind
enum lldb_private::BreakpointOptions::OptionKind
Enumerator
eCallback
eEnabled
eOneShot
eIgnoreCount
eThreadSpec
eCondition
eAutoContinue
eAllOptions
Definition at line 35 of file BreakpointOptions.h.
OptionNames
enum class lldb_private::BreakpointOptions::OptionNames strong protected
Enumerator
ConditionText
IgnoreCount
EnabledState
OneShotState
AutoContinue
LastOptionName
Definition at line 354 of file BreakpointOptions.h.
Constructor & Destructor Documentation
BreakpointOptions() [1/3]
BreakpointOptions::BreakpointOptions (const char * condition, bool enabled = true, int32_t ignore = 0, bool one_shot = false, bool auto_continue = false)
This constructor allows you to specify all the breakpoint options except the callback.
That one is more complicated, and better to do by hand.
Parameters
[in] condition The expression which if it evaluates to true if we are to stop
[in] enabled Is this breakpoint enabled.
[in] ignore How many breakpoint hits we should ignore before stopping.
[in] one_shot Should this breakpoint delete itself after being hit once.
[in] auto_continue Should this breakpoint auto-continue after running its commands.
Definition at line 115 of file BreakpointOptions.cpp.
References eAutoContinue, eEnabled, eIgnoreCount, eOneShot, m_auto_continue, m_baton_is_command_baton, m_callback, m_callback_is_synchronous, m_condition, m_enabled, m_ignore_count, m_inject_condition, m_one_shot, m_set_flags, and SetCondition().
Referenced by BreakpointOptions(), CopyOverSetOptions(), and operator=().
BreakpointOptions() [2/3]
BreakpointOptions::BreakpointOptions (bool all_flags_set)
Breakpoints make options with all flags set.
Locations and Names make options with no flags set.
Definition at line 106 of file BreakpointOptions.cpp.
References m_auto_continue, m_baton_is_command_baton, m_callback, m_callback_is_synchronous, m_enabled, m_ignore_count, m_inject_condition, m_one_shot, and m_set_flags.
BreakpointOptions() [3/3]
BreakpointOptions::BreakpointOptions (const BreakpointOptions & rhs)
Definition at line 129 of file BreakpointOptions.cpp.
References BreakpointOptions(), m_auto_continue, m_baton_is_command_baton, m_callback, m_callback_baton_sp, m_callback_is_synchronous, m_condition, m_enabled, m_ignore_count, m_inject_condition, m_one_shot, m_set_flags, and m_thread_spec_up.
~BreakpointOptions()
BreakpointOptions::~BreakpointOptions () virtual default
References error().
Member Function Documentation
AnySet()
bool lldb_private::BreakpointOptions::AnySet () const inline
Definition at line 343 of file BreakpointOptions.h.
References eAllOptions, and m_set_flags.
BreakpointOptionsCallbackFunction()
bool BreakpointOptions::BreakpointOptionsCallbackFunction (void * baton, StoppointCallbackContext * context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id) static protected
Definition at line 592 of file BreakpointOptions.cpp.
References lldb_private::StoppointCallbackContext::exe_ctx_ref, lldb_private::Debugger::GetAsyncErrorStream(), lldb_private::Debugger::GetAsyncOutputStream(), lldb_private::Debugger::GetCommandInterpreter(), lldb_private::Target::GetDebugger(), lldb_private::CommandReturnObject::GetImmediateErrorStream(), lldb_private::CommandReturnObject::GetImmediateOutputStream(), lldb_private::StringList::GetSize(), lldb_private::ExecutionContext::GetTargetPtr(), lldb_private::Debugger::GetUseColor(), lldb_private::CommandInterpreter::HandleCommands(), lldb_private::CommandInterpreterRunOptions::SetAddToHistory(), lldb_private::CommandInterpreterRunOptions::SetEchoCommands(), lldb_private::CommandReturnObject::SetImmediateErrorStream(), lldb_private::CommandReturnObject::SetImmediateOutputStream(), lldb_private::CommandInterpreterRunOptions::SetPrintErrors(), lldb_private::CommandInterpreterRunOptions::SetPrintResults(), lldb_private::CommandInterpreterRunOptions::SetStopOnContinue(), lldb_private::CommandInterpreterRunOptions::SetStopOnError(), lldb_private::BreakpointOptions::CommandData::stop_on_error, and lldb_private::BreakpointOptions::CommandData::user_source.
Referenced by SetCommandDataCallback().
Clear()
void BreakpointOptions::Clear ()
Definition at line 631 of file BreakpointOptions.cpp.
References m_auto_continue, m_baton_is_command_baton, m_callback, m_callback_baton_sp, m_callback_is_synchronous, m_condition, m_enabled, m_ignore_count, m_one_shot, m_set_flags, and m_thread_spec_up.
ClearCallback()
void BreakpointOptions::ClearCallback ()
Remove the callback from this option set.
Definition at line 415 of file BreakpointOptions.cpp.
References eCallback, m_baton_is_command_baton, m_callback, m_callback_baton_sp, m_callback_is_synchronous, and m_set_flags.
Referenced by lldb_private::BreakpointLocation::ClearCallback().
CopyOverSetOptions()
void BreakpointOptions::CopyOverSetOptions (const BreakpointOptions & rhs)
Copy over only the options set in the incoming BreakpointOptions.
Definition at line 160 of file BreakpointOptions.cpp.
References BreakpointOptions(), eAutoContinue, eCallback, eCondition, eEnabled, eIgnoreCount, eOneShot, eThreadSpec, m_auto_continue, m_baton_is_command_baton, m_callback, m_callback_baton_sp, m_callback_is_synchronous, m_condition, m_enabled, m_ignore_count, m_one_shot, m_set_flags, m_thread_spec_up, and lldb_private::Flags::Test().
Referenced by lldb_private::Target::ConfigureBreakpointName(), and CommandObjectBreakpointModify::DoExecute().
CreateFromStructuredData()
std::unique_ptr< BreakpointOptions > BreakpointOptions::CreateFromStructuredData (Target & target, const StructuredData::Dictionary & data_dict, Status & error) static
Definition at line 214 of file BreakpointOptions.cpp.
References lldb_private::Status::AsCString(), AutoContinue, ConditionText, lldb_private::BreakpointOptions::CommandData::CreateFromStructuredData(), lldb_private::ThreadSpec::CreateFromStructuredData(), eAutoContinue, eCondition, eEnabled, eIgnoreCount, EnabledState, eOneShot, error(), lldb::eScriptLanguageNone, lldb_private::Status::Fail(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::Target::GetDebugger(), GetKey(), lldb_private::ScriptInterpreter::GetLanguage(), lldb_private::Debugger::GetScriptInterpreter(), lldb_private::BreakpointOptions::CommandData::GetSerializationKey(), lldb_private::ThreadSpec::GetSerializationKey(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsBoolean(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsDictionary(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsInteger(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsString(), lldb_private::StructuredData::Dictionary::HasKey(), IgnoreCount, lldb_private::ScriptInterpreter::LanguageToString(), OneShotState, lldb_private::Flags::Set(), and lldb_private::ScriptInterpreter::SetBreakpointCommandCallback().
Referenced by lldb_private::Breakpoint::CreateFromStructuredData().
GetBaton() [1/2]
Baton * BreakpointOptions::GetBaton ()
Fetch the baton from the callback.
Returns
The baton.
Definition at line 423 of file BreakpointOptions.cpp.
References m_callback_baton_sp.
Referenced by CommandObjectBreakpointCommandList::DoExecute().
GetBaton() [2/2]
const Baton * BreakpointOptions::GetBaton () const
Fetch a const version of the baton from the callback.
Returns
The baton.
Definition at line 425 of file BreakpointOptions.cpp.
References m_callback_baton_sp.
GetCommandLineCallbacks()
bool BreakpointOptions::GetCommandLineCallbacks (StringList & command_list)
Returns the command line commands for the callback on this breakpoint.
Parameters
[out] command_list The commands will be appended to this list.
Returns
true if the command callback is a command-line callback, false otherwise.
Definition at line 449 of file BreakpointOptions.cpp.
References HasCallback(), m_baton_is_command_baton, m_callback_baton_sp, and lldb_private::BreakpointOptions::CommandData::user_source.
Referenced by lldb::SBBreakpointName::GetCommandLineCommands().
GetCondition() [1/2]
StopCondition & BreakpointOptions::GetCondition ()
Definition at line 476 of file BreakpointOptions.cpp.
References m_condition.
GetCondition() [2/2]
const StopCondition & BreakpointOptions::GetCondition () const
Return the breakpoint condition.
Definition at line 472 of file BreakpointOptions.cpp.
References m_condition.
Referenced by lldb::SBBreakpointName::GetCondition(), and lldb_private::BreakpointLocation::GetCondition().
GetDescription()
void BreakpointOptions::GetDescription (Stream * s, lldb::DescriptionLevel level) const
Definition at line 502 of file BreakpointOptions.cpp.
References lldb_private::Stream::AsRawOstream(), lldb::eDescriptionLevelBrief, lldb::eDescriptionLevelFull, lldb::eDescriptionLevelVerbose, lldb_private::Stream::EOL(), lldb_private::Stream::GetIndentLevel(), GetThreadSpecNoCreate(), lldb_private::Stream::Indent(), lldb_private::Stream::IndentLess(), lldb_private::Stream::IndentMore(), m_auto_continue, m_callback_baton_sp, m_condition, m_enabled, m_ignore_count, m_one_shot, m_thread_spec_up, lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
Referenced by lldb_private::BreakpointName::GetDescription().
GetIgnoreCount()
uint32_t lldb_private::BreakpointOptions::GetIgnoreCount () const inline
Return the current Ignore Count.
Returns
The number of breakpoint hits to be ignored.
Definition at line 305 of file BreakpointOptions.h.
References m_ignore_count.
Referenced by lldb::SBBreakpointName::GetIgnoreCount(), and lldb_private::BreakpointLocation::GetIgnoreCount().
GetKey()
const char * lldb_private::BreakpointOptions::GetKey (OptionNames enum_value) inline static protected
Definition at line 364 of file BreakpointOptions.h.
References g_option_names.
Referenced by lldb_private::BreakpointOptions::CommandData::CreateFromStructuredData(), CreateFromStructuredData(), and SerializeToStructuredData().
GetSerializationKey()
const char * lldb_private::BreakpointOptions::GetSerializationKey () inline static
Definition at line 134 of file BreakpointOptions.h.
Referenced by lldb_private::Breakpoint::CreateFromStructuredData(), and lldb_private::Breakpoint::SerializeToStructuredData().
GetThreadSpec()
ThreadSpec * BreakpointOptions::GetThreadSpec ()
Returns a pointer to the ThreadSpec for this option, creating it.
if it hasn't been created already. This API is used for setting the ThreadSpec items for this option.
Definition at line 482 of file BreakpointOptions.cpp.
References eThreadSpec, m_set_flags, and m_thread_spec_up.
Referenced by lldb::SBBreakpointName::GetQueueName(), lldb::SBBreakpointName::GetThreadID(), lldb::SBBreakpointName::GetThreadIndex(), lldb::SBBreakpointName::GetThreadName(), lldb::SBBreakpointName::SetQueueName(), lldb_private::BreakpointLocation::SetQueueName(), SetThreadID(), lldb::SBBreakpointName::SetThreadIndex(), lldb_private::BreakpointLocation::SetThreadIndex(), lldb::SBBreakpointName::SetThreadName(), and lldb_private::BreakpointLocation::SetThreadName().
GetThreadSpecNoCreate()
const ThreadSpec * BreakpointOptions::GetThreadSpecNoCreate () const
Return the current thread spec for this option.
This will return nullptr if the no thread specifications have been set for this Option yet.
Returns
The thread specification pointer for this option, or nullptr if none has been set yet.
Definition at line 478 of file BreakpointOptions.cpp.
References m_thread_spec_up.
Referenced by lldb_private::BreakpointLocation::Dump(), GetDescription(), lldb_private::BreakpointLocation::GetQueueName(), lldb_private::BreakpointLocation::GetThreadID(), lldb_private::BreakpointLocation::GetThreadIndex(), and lldb_private::BreakpointLocation::GetThreadName().
HasCallback()
bool BreakpointOptions::HasCallback () const
Check if the breakpoint option has a callback set.
Returns
If the breakpoint option has a callback, true otherwise false.
Definition at line 445 of file BreakpointOptions.cpp.
References m_callback.
Referenced by GetCommandLineCallbacks().
InvokeCallback()
bool BreakpointOptions::InvokeCallback (StoppointCallbackContext * context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id)
Use this function to invoke the callback for a specific stop.
Parameters
[in] context The context in which the callback is to be invoked. This includes the stop event, the execution context of the stop (since you might hit the same breakpoint on multiple threads) and whether we are currently executing synchronous or asynchronous callbacks.
[in] break_id The breakpoint ID that owns this option set.
[in] break_loc_id The breakpoint location ID that owns this option set.
Returns
The callback return value.
Definition at line 429 of file BreakpointOptions.cpp.
References lldb_private::StoppointCallbackContext::is_synchronous, IsCallbackSynchronous(), m_callback, and m_callback_baton_sp.
IsAutoContinue()
bool lldb_private::BreakpointOptions::IsAutoContinue () const inline
Check the auto-continue state.
Returns
true if the breakpoint is set to auto-continue, false otherwise.
Definition at line 275 of file BreakpointOptions.h.
References m_auto_continue.
Referenced by lldb::SBBreakpointName::GetAutoContinue().
IsCallbackSynchronous()
bool lldb_private::BreakpointOptions::IsCallbackSynchronous () const inline
Used in InvokeCallback to tell whether it is the right time to run this kind of callback.
Returns
The synchronicity of our callback.
Definition at line 234 of file BreakpointOptions.h.
References m_callback_is_synchronous.
Referenced by InvokeCallback().
IsEnabled()
bool lldb_private::BreakpointOptions::IsEnabled () const inline
Check the Enable/Disable state.
Returns
true if the breakpoint is enabled, false if disabled.
Definition at line 264 of file BreakpointOptions.h.
References m_enabled.
Referenced by lldb::SBBreakpointName::IsEnabled().
IsOneShot()
bool lldb_private::BreakpointOptions::IsOneShot () const inline
Check the One-shot state.
Returns
true if the breakpoint is one-shot, false otherwise.
Definition at line 286 of file BreakpointOptions.h.
References m_one_shot.
Referenced by lldb::SBBreakpointName::IsOneShot().
IsOptionSet()
bool lldb_private::BreakpointOptions::IsOptionSet (OptionKind kind) inline protected
Definition at line 349 of file BreakpointOptions.h.
References m_set_flags.
NullCallback()
bool lldb_private::BreakpointOptions::NullCallback (void * baton, StoppointCallbackContext * context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id) static
This is the default empty callback.
operator=()
const BreakpointOptions & BreakpointOptions::operator= (const BreakpointOptions & rhs)
Definition at line 142 of file BreakpointOptions.cpp.
References BreakpointOptions(), m_auto_continue, m_baton_is_command_baton, m_callback, m_callback_baton_sp, m_callback_is_synchronous, m_condition, m_enabled, m_ignore_count, m_inject_condition, m_one_shot, m_set_flags, and m_thread_spec_up.
SerializeToStructuredData()
StructuredData::ObjectSP BreakpointOptions::SerializeToStructuredData () virtual
Definition at line 345 of file BreakpointOptions.cpp.
References AutoContinue, ConditionText, eAutoContinue, eCallback, eCondition, eEnabled, eIgnoreCount, EnabledState, eOneShot, eThreadSpec, GetKey(), lldb_private::BreakpointOptions::CommandData::GetSerializationKey(), lldb_private::ThreadSpec::GetSerializationKey(), IgnoreCount, m_auto_continue, m_baton_is_command_baton, m_callback_baton_sp, m_condition, m_enabled, m_ignore_count, m_one_shot, m_set_flags, m_thread_spec_up, and OneShotState.
SetAutoContinue()
void lldb_private::BreakpointOptions::SetAutoContinue (bool auto_continue) inline
Set the auto-continue state.
Definition at line 278 of file BreakpointOptions.h.
References eAutoContinue, m_auto_continue, and m_set_flags.
Referenced by lldb::SBBreakpointName::SetAutoContinue(), and lldb_private::BreakpointLocation::SetAutoContinue().
SetCallback() [1/2]
void BreakpointOptions::SetCallback (BreakpointHitCallback callback, const BreakpointOptions::CommandBatonSP & command_baton_sp, bool synchronous = false)
Definition at line 404 of file BreakpointOptions.cpp.
References eCallback, m_baton_is_command_baton, m_callback, m_callback_baton_sp, m_callback_is_synchronous, and m_set_flags.
SetCallback() [2/2]
void BreakpointOptions::SetCallback (BreakpointHitCallback callback, const lldb::BatonSP & baton_sp, bool synchronous = false)
Adds a callback to the breakpoint option set.
Parameters
[in] callback The function to be called when the breakpoint gets hit.
[in] baton_sp A baton which will get passed back to the callback when it is invoked.
[in] synchronous Whether this is a synchronous or asynchronous callback. See discussion above.
Definition at line 384 of file BreakpointOptions.cpp.
References eCallback, m_baton_is_command_baton, m_callback, m_callback_baton_sp, m_callback_is_synchronous, and m_set_flags.
Referenced by lldb_private::ScriptInterpreterLua::RegisterBreakpointCallback(), lldb::SBBreakpointName::SetCallback(), lldb_private::BreakpointLocation::SetCallback(), lldb_private::BreakpointLocation::SetCallback(), and SetCommandDataCallback().
SetCommandDataCallback()
void BreakpointOptions::SetCommandDataCallback (std::unique_ptr< CommandData > & cmd_data)
Set a callback based on BreakpointOptions::CommandData.
Parameters
[in] cmd_data A UP holding the new'ed CommandData object. The breakpoint will take ownership of pointer held by this object.
Definition at line 584 of file BreakpointOptions.cpp.
References BreakpointOptionsCallbackFunction(), eCallback, lldb::eScriptLanguageNone, m_set_flags, and SetCallback().
Referenced by lldb::SBBreakpointName::SetCommandLineCommands().
SetCondition()
void BreakpointOptions::SetCondition (StopCondition condition)
Set the breakpoint stop condition.
Parameters
[in] condition The condition to evaluate when the breakpoint is hit.
Definition at line 463 of file BreakpointOptions.cpp.
References eCondition, m_condition, and m_set_flags.
Referenced by BreakpointOptions(), lldb::SBBreakpointName::SetCondition(), and lldb_private::BreakpointLocation::SetCondition().
SetEnabled()
void lldb_private::BreakpointOptions::SetEnabled (bool enabled) inline
If enable is true, enable the breakpoint, if false disable it.
Definition at line 267 of file BreakpointOptions.h.
References eEnabled, m_enabled, and m_set_flags.
Referenced by lldb::SBBreakpointName::SetEnabled(), and lldb_private::BreakpointLocation::SetEnabled().
SetIgnoreCount()
void lldb_private::BreakpointOptions::SetIgnoreCount (uint32_t n) inline
Set the breakpoint to ignore the next count breakpoint hits.
Parameters
[in] n The number of breakpoint hits to ignore.
Definition at line 297 of file BreakpointOptions.h.
References eIgnoreCount, m_ignore_count, and m_set_flags.
Referenced by lldb::SBBreakpointName::SetIgnoreCount(), and lldb_private::BreakpointLocation::SetIgnoreCount().
SetOneShot()
void lldb_private::BreakpointOptions::SetOneShot (bool one_shot) inline
If enable is true, enable the breakpoint, if false disable it.
Definition at line 289 of file BreakpointOptions.h.
References eOneShot, m_one_shot, and m_set_flags.
Referenced by lldb::SBBreakpointName::SetOneShot().
SetThreadID()
void BreakpointOptions::SetThreadID (lldb::tid_t thread_id)
Definition at line 491 of file BreakpointOptions.cpp.
References eThreadSpec, GetThreadSpec(), m_set_flags, and lldb_private::ThreadSpec::SetTID().
Referenced by lldb::SBBreakpointName::SetThreadID(), and lldb_private::BreakpointLocation::SetThreadIDInternal().
SetThreadSpec()
void BreakpointOptions::SetThreadSpec (std::unique_ptr< ThreadSpec > & thread_spec_up) protected
Definition at line 496 of file BreakpointOptions.cpp.
References eThreadSpec, m_set_flags, and m_thread_spec_up.
Friends And Related Symbol Documentation
Breakpoint
friend class Breakpoint friend
Definition at line 32 of file BreakpointOptions.h.
References Breakpoint.
Referenced by Breakpoint.
BreakpointLocation
friend class BreakpointLocation friend
Definition at line 29 of file BreakpointOptions.h.
References BreakpointLocation.
Referenced by BreakpointLocation.
BreakpointName
friend class BreakpointName friend
Definition at line 30 of file BreakpointOptions.h.
References BreakpointName.
Referenced by BreakpointName.
lldb_private::BreakpointOptionGroup
friend class lldb_private::BreakpointOptionGroup friend
Definition at line 31 of file BreakpointOptions.h.
Member Data Documentation
g_option_names
const char * BreakpointOptions::g_option_names static protected
Initial value:
{
    "ConditionText", "IgnoreCount", "EnabledState", "OneShotState",
    "AutoContinue"}
Definition at line 362 of file BreakpointOptions.h.
Referenced by GetKey().
m_auto_continue
bool lldb_private::BreakpointOptions::m_auto_continue private
If set, auto-continue from breakpoint.
Definition at line 395 of file BreakpointOptions.h.
Referenced by BreakpointOptions(), BreakpointOptions(), BreakpointOptions(), Clear(), CopyOverSetOptions(), GetDescription(), IsAutoContinue(), operator=(), SerializeToStructuredData(), and SetAutoContinue().
m_baton_is_command_baton
bool lldb_private::BreakpointOptions::m_baton_is_command_baton private
Definition at line 381 of file BreakpointOptions.h.
Referenced by BreakpointOptions(), BreakpointOptions(), BreakpointOptions(), Clear(), ClearCallback(), CopyOverSetOptions(), GetCommandLineCallbacks(), operator=(), SerializeToStructuredData(), SetCallback(), and SetCallback().
m_callback
BreakpointHitCallback lldb_private::BreakpointOptions::m_callback private
For BreakpointOptions only.
This is the callback function pointer
Definition at line 378 of file BreakpointOptions.h.
Referenced by BreakpointOptions(), BreakpointOptions(), BreakpointOptions(), Clear(), ClearCallback(), CopyOverSetOptions(), HasCallback(), InvokeCallback(), operator=(), SetCallback(), and SetCallback().
m_callback_baton_sp
lldb::BatonSP lldb_private::BreakpointOptions::m_callback_baton_sp private
This is the client data for the callback.
Definition at line 380 of file BreakpointOptions.h.
Referenced by BreakpointOptions(), Clear(), ClearCallback(), CopyOverSetOptions(), GetBaton(), GetBaton(), GetCommandLineCallbacks(), GetDescription(), InvokeCallback(), operator=(), SerializeToStructuredData(), SetCallback(), and SetCallback().
m_callback_is_synchronous
bool lldb_private::BreakpointOptions::m_callback_is_synchronous private
Definition at line 382 of file BreakpointOptions.h.
Referenced by BreakpointOptions(), BreakpointOptions(), BreakpointOptions(), Clear(), ClearCallback(), CopyOverSetOptions(), IsCallbackSynchronous(), operator=(), SetCallback(), and SetCallback().
m_condition
StopCondition lldb_private::BreakpointOptions::m_condition private
The condition to test.
Definition at line 391 of file BreakpointOptions.h.
Referenced by BreakpointOptions(), BreakpointOptions(), Clear(), CopyOverSetOptions(), GetCondition(), GetCondition(), GetDescription(), operator=(), SerializeToStructuredData(), and SetCondition().
m_enabled
bool lldb_private::BreakpointOptions::m_enabled private
Definition at line 383 of file BreakpointOptions.h.
Referenced by BreakpointOptions(), BreakpointOptions(), BreakpointOptions(), Clear(), CopyOverSetOptions(), GetDescription(), IsEnabled(), operator=(), SerializeToStructuredData(), and SetEnabled().
m_ignore_count
uint32_t lldb_private::BreakpointOptions::m_ignore_count private
Number of times to ignore this breakpoint.
Definition at line 387 of file BreakpointOptions.h.
Referenced by BreakpointOptions(), BreakpointOptions(), BreakpointOptions(), Clear(), CopyOverSetOptions(), GetDescription(), GetIgnoreCount(), operator=(), SerializeToStructuredData(), and SetIgnoreCount().
m_inject_condition
bool lldb_private::BreakpointOptions::m_inject_condition private
If set, inject breakpoint condition into process.
Definition at line 393 of file BreakpointOptions.h.
Referenced by BreakpointOptions(), BreakpointOptions(), BreakpointOptions(), and operator=().
m_one_shot
bool lldb_private::BreakpointOptions::m_one_shot private
If set, the breakpoint delete itself after being hit once.
Definition at line 385 of file BreakpointOptions.h.
Referenced by BreakpointOptions(), BreakpointOptions(), BreakpointOptions(), Clear(), CopyOverSetOptions(), GetDescription(), IsOneShot(), operator=(), SerializeToStructuredData(), and SetOneShot().
m_set_flags
Flags lldb_private::BreakpointOptions::m_set_flags private
Which options are set at this level.
Drawn from BreakpointOptions::SetOptionsFlags.
Definition at line 398 of file BreakpointOptions.h.
Referenced by AnySet(), BreakpointOptions(), BreakpointOptions(), BreakpointOptions(), Clear(), ClearCallback(), CopyOverSetOptions(), GetThreadSpec(), IsOptionSet(), operator=(), SerializeToStructuredData(), SetAutoContinue(), SetCallback(), SetCallback(), SetCommandDataCallback(), SetCondition(), SetEnabled(), SetIgnoreCount(), SetOneShot(), SetThreadID(), and SetThreadSpec().
m_thread_spec_up
std::unique_ptr<ThreadSpec> lldb_private::BreakpointOptions::m_thread_spec_up private
Thread for which this breakpoint will stop.
Definition at line 389 of file BreakpointOptions.h.
Referenced by BreakpointOptions(), Clear(), CopyOverSetOptions(), GetDescription(), GetThreadSpec(), GetThreadSpecNoCreate(), operator=(), SerializeToStructuredData(), and SetThreadSpec().
The documentation for this class was generated from the following files:
BreakpointOptions.h
BreakpointOptions.cpp