LLDB: lldb_private::trace_intel_pt::TraceIntelPTBundleLoader Class Reference
lldb_private::trace_intel_pt::TraceIntelPTBundleLoader Class Reference
#include <TraceIntelPTBundleLoader.h>
Classes
struct ParsedProcess
Helper struct holding the objects created when parsing a process.
Public Member Functions
TraceIntelPTBundleLoader (Debugger &debugger, const llvm::json::Value &bundle_description, llvm::StringRef bundle_dir)
llvm::Expected< lldb::TraceSP > Load ()
Parse the trace bundle description and create the corresponding Target objects.
Static Public Member Functions
static llvm::StringRef GetSchema ()
Private Member Functions
FileSpec NormalizePath (const std::string &path)
Resolve non-absolute paths relative to the bundle folder.
lldb::ThreadPostMortemTraceSP ParseThread (Process &process, const JSONThread &thread)
Create a post-mortem thread associated with the given process using the definition from thread.
llvm::Expected< lldb::TraceSP > CreateTraceIntelPTInstance (JSONTraceBundleDescription &bundle_description, std::vector< ParsedProcess > &parsed_processes)
Given a bundle description and a list of fully parsed processes, create an actual Trace instance that "traces" these processes.
llvm::Expected< ParsedProcess > CreateEmptyProcess (lldb::pid_t pid, llvm::StringRef triple)
Create an empty Process object with given pid and target.
llvm::Expected< ParsedProcess > ParseProcess (const JSONProcess &process)
Create the corresponding Threads and Process objects given the JSON process definition.
llvm::Error ParseModule (Target &target, const JSONModule &module)
Create a module associated with the given target using the definition from module.
llvm::Expected< ParsedProcess > ParseKernel (const JSONTraceBundleDescription &bundle_description)
Create a kernel process and cpu threads given the JSON kernel definition.
llvm::Error CreateJSONError (llvm::json::Path::Root &root, const llvm::json::Value &value)
Create a user-friendly error message upon a JSON-parsing failure using the json::ObjectMapper functionality.
llvm::Expected< std::vector< ParsedProcess > > LoadBundle (const JSONTraceBundleDescription &bundle_description)
Create the corresponding Process, Thread and Module objects given this bundle description.
llvm::Error AugmentThreadsFromContextSwitches (JSONTraceBundleDescription &bundle_description)
When applicable, augment the list of threads in the trace bundle by inspecting the context switch trace.
void NormalizeAllPaths (JSONTraceBundleDescription &bundle_description)
Modifiy the bundle description by normalizing all the paths relative to the session file directory.
Private Attributes
Debugger & m_debugger
const llvm::json::Value & m_bundle_description
const std::string m_bundle_dir
Detailed Description
Definition at line 20 of file TraceIntelPTBundleLoader.h.
Constructor & Destructor Documentation
TraceIntelPTBundleLoader()
lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::TraceIntelPTBundleLoader (Debugger & debugger, const llvm::json::Value & bundle_description, llvm::StringRef bundle_dir) inline
Parameters
[in] debugger The debugger that will own the targets to create.
[in] bundle_description The JSON description of a trace bundle that follows the schema of the intel pt trace plug-in.
[in] bundle_dir The folder where the trace bundle is located.
Definition at line 37 of file TraceIntelPTBundleLoader.h.
References m_bundle_description, m_bundle_dir, and m_debugger.
Member Function Documentation
AugmentThreadsFromContextSwitches()
Error TraceIntelPTBundleLoader::AugmentThreadsFromContextSwitches (JSONTraceBundleDescription & bundle_description) private
When applicable, augment the list of threads in the trace bundle by inspecting the context switch trace.
This only applies for threads of processes already specified in this bundle description.
Returns
An llvm::Error in case if failures, or llvm::Error::success otherwise.
Definition at line 237 of file TraceIntelPTBundleLoader.cpp.
CreateEmptyProcess()
Expected< TraceIntelPTBundleLoader::ParsedProcess > TraceIntelPTBundleLoader::CreateEmptyProcess (lldb::pid_t pid, llvm::StringRef triple) private
Create an empty Process object with given pid and target.
Definition at line 94 of file TraceIntelPTBundleLoader.cpp.
References lldb_private::eLoadDependentsNo, error(), lldb_private::ProcessTrace::Initialize(), m_debugger, and lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::ParsedProcess::target_sp.
Referenced by ParseKernel(), and ParseProcess().
CreateJSONError()
Error TraceIntelPTBundleLoader::CreateJSONError (llvm::json::Path::Root & root, const llvm::json::Value & value) private
Create a user-friendly error message upon a JSON-parsing failure using the json::ObjectMapper functionality.
Parameters
[in] root The llvm::json::Path::Root used to parse the JSON value.
[in] value The json value that failed to parse.
Returns
An llvm::Error containing the user-friendly error message.
Definition at line 68 of file TraceIntelPTBundleLoader.cpp.
References createStringError(), GetSchema(), and lldb_private::toString().
CreateTraceIntelPTInstance()
Expected< TraceSP > TraceIntelPTBundleLoader::CreateTraceIntelPTInstance (JSONTraceBundleDescription & bundle_description, std::vector< ParsedProcess > & parsed_processes) private
Given a bundle description and a list of fully parsed processes, create an actual Trace instance that "traces" these processes.
Definition at line 285 of file TraceIntelPTBundleLoader.cpp.
GetSchema()
StringRef TraceIntelPTBundleLoader::GetSchema () static
Returns
The JSON schema for the bundle description.
Definition at line 229 of file TraceIntelPTBundleLoader.cpp.
Referenced by CreateJSONError(), lldb_private::trace_intel_pt::TraceIntelPT::GetSchema(), and lldb_private::trace_intel_pt::TraceIntelPT::Initialize().
Load()
Expected< TraceSP > TraceIntelPTBundleLoader::Load ()
Parse the trace bundle description and create the corresponding Target objects.
In case of an error, no targets are created.
Returns
A lldb::TraceSP instance created according to the trace bundle information. In case of errors, return a null pointer.
Definition at line 336 of file TraceIntelPTBundleLoader.cpp.
LoadBundle()
Expected< std::vector< TraceIntelPTBundleLoader::ParsedProcess > > TraceIntelPTBundleLoader::LoadBundle (const JSONTraceBundleDescription & bundle_description) private
Create the corresponding Process, Thread and Module objects given this bundle description.
Definition at line 198 of file TraceIntelPTBundleLoader.cpp.
References lldb_private::trace_intel_pt::JSONTraceBundleDescription::kernel, m_debugger, ParseKernel(), ParseProcess(), and lldb_private::trace_intel_pt::JSONTraceBundleDescription::processes.
NormalizeAllPaths()
void TraceIntelPTBundleLoader::NormalizeAllPaths (JSONTraceBundleDescription & bundle_description) private
Modifiy the bundle description by normalizing all the paths relative to the session file directory.
Definition at line 308 of file TraceIntelPTBundleLoader.cpp.
NormalizePath()
FileSpec TraceIntelPTBundleLoader::NormalizePath (const std::string & path) private
Resolve non-absolute paths relative to the bundle folder.
Definition at line 27 of file TraceIntelPTBundleLoader.cpp.
References lldb_private::FileSpec::IsRelative(), m_bundle_dir, and lldb_private::FileSpec::PrependPathComponent().
ParseKernel()
Expected< TraceIntelPTBundleLoader::ParsedProcess > TraceIntelPTBundleLoader::ParseKernel (const JSONTraceBundleDescription & bundle_description) private
Create a kernel process and cpu threads given the JSON kernel definition.
Definition at line 147 of file TraceIntelPTBundleLoader.cpp.
References lldb_private::trace_intel_pt::JSONTraceBundleDescription::cpus, CreateEmptyProcess(), error(), lldb_private::ModuleSpec::GetFileSpec(), lldb_private::trace_intel_pt::JSONCpu::id, lldb_private::trace_intel_pt::JSONCpu::ipt_trace, lldb_private::trace_intel_pt::kDefaultKernelLoadAddress, lldb_private::trace_intel_pt::kDefaultKernelProcessID, and lldb_private::trace_intel_pt::JSONTraceBundleDescription::kernel.
Referenced by LoadBundle().
ParseModule()
Error TraceIntelPTBundleLoader::ParseModule (Target & target, const JSONModule & module) private
Create a module associated with the given target using the definition from module.
Definition at line 34 of file TraceIntelPTBundleLoader.cpp.
References createStringError(), error(), lldb_private::trace_intel_pt::JSONModule::file, lldb_private::ModuleSpec::GetFileSpec(), lldb_private::Target::GetOrCreateModule(), lldb_private::ModuleSpec::GetPlatformFileSpec(), lldb_private::ModuleSpec::GetUUID(), lldb_private::trace_intel_pt::JSONModule::load_address, lldb_private::UUID::SetFromStringRef(), lldb_private::trace_intel_pt::JSONModule::system_path, lldb_private::toString(), lldb_private::trace_intel_pt::JSONModule::uuid, and lldb_private::JSONUINT64::value.
Referenced by ParseProcess().
ParseProcess()
Expected< TraceIntelPTBundleLoader::ParsedProcess > TraceIntelPTBundleLoader::ParseProcess (const JSONProcess & process) private
Create the corresponding Threads and Process objects given the JSON process definition.
Parameters
[in] process The JSON process definition
Definition at line 119 of file TraceIntelPTBundleLoader.cpp.
References CreateEmptyProcess(), lldb_private::trace_intel_pt::JSONProcess::modules, ParseModule(), ParseThread(), lldb_private::trace_intel_pt::JSONProcess::pid, lldb_private::trace_intel_pt::JSONProcess::threads, and lldb_private::trace_intel_pt::JSONProcess::triple.
Referenced by LoadBundle().
ParseThread()
ThreadPostMortemTraceSP TraceIntelPTBundleLoader::ParseThread (Process & process, const JSONThread & thread) private
Create a post-mortem thread associated with the given process using the definition from thread.
Definition at line 79 of file TraceIntelPTBundleLoader.cpp.
References lldb_private::ThreadCollection::AddThread(), and lldb_private::Process::GetThreadList().
Referenced by ParseProcess().
Member Data Documentation
m_bundle_description
const llvm::json::Value& lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::m_bundle_description private
Definition at line 123 of file TraceIntelPTBundleLoader.h.
Referenced by TraceIntelPTBundleLoader().
m_bundle_dir
const std::string lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::m_bundle_dir private
Definition at line 124 of file TraceIntelPTBundleLoader.h.
Referenced by NormalizePath(), and TraceIntelPTBundleLoader().
m_debugger
Debugger& lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::m_debugger private
Definition at line 122 of file TraceIntelPTBundleLoader.h.
Referenced by CreateEmptyProcess(), LoadBundle(), and TraceIntelPTBundleLoader().
The documentation for this class was generated from the following files:
TraceIntelPTBundleLoader.h
TraceIntelPTBundleLoader.cpp