LLDB: lldb_private::process_linux::NativeProcessLinux Class Reference
lldb_private::process_linux::NativeProcessLinux Class Reference
Manages communication with the inferior (debugee) process.
#include <NativeProcessLinux.h>
Classes
class Manager
Public Member Functions
~NativeProcessLinux () override
Status Resume (const ResumeActionList &resume_actions) override
Status Halt () override
Status Detach () override
Status Signal (int signo) override
Sends a process a UNIX signal signal.
Status Interrupt () override
Tells a process to interrupt all operations as if by a Ctrl-C.
Status Kill () override
Status GetMemoryRegionInfo (lldb::addr_t load_addr, MemoryRegionInfo &range_info) override
Status ReadMemory (lldb::addr_t addr, void *buf, size_t size, size_t &bytes_read) override
Status WriteMemory (lldb::addr_t addr, const void *buf, size_t size, size_t &bytes_written) override
llvm::Expected< lldb::addr_t > AllocateMemory (size_t size, uint32_t permissions) override
llvm::Error DeallocateMemory (lldb::addr_t addr) override
Status ReadMemoryTags (int32_t type, lldb::addr_t addr, size_t len, std::vector< uint8_t > &tags) override
Status WriteMemoryTags (int32_t type, lldb::addr_t addr, size_t len, const std::vector< uint8_t > &tags) override
size_t UpdateThreads () override
const ArchSpec & GetArchitecture () const override
Status SetBreakpoint (lldb::addr_t addr, uint32_t size, bool hardware) override
Status RemoveBreakpoint (lldb::addr_t addr, bool hardware=false) override
void DoStopIDBumped (uint32_t newBumpId) override
Status GetLoadedModuleFileSpec (const char *module_path, FileSpec &file_spec) override
Status GetFileLoadAddress (const llvm::StringRef &file_name, lldb::addr_t &load_addr) override
NativeThreadLinux * GetThreadByID (lldb::tid_t id)
NativeThreadLinux * GetCurrentThread ()
llvm::ErrorOr< std::unique_ptr< llvm::MemoryBuffer > > GetAuxvData () const override
Public Member Functions inherited from lldb_private::NativeProcessELF
std::optional< uint64_t > GetAuxValue (enum AuxVector::EntryType type)
Public Member Functions inherited from lldb_private::NativeProcessProtocol
virtual ~NativeProcessProtocol ()=default
virtual Status IgnoreSignals (llvm::ArrayRef< int > signals)
Status ReadMemoryWithoutTrap (lldb::addr_t addr, void *buf, size_t size, size_t &bytes_read)
llvm::Expected< llvm::StringRef > ReadCStringFromMemory (lldb::addr_t addr, char *buffer, size_t max_size, size_t &total_bytes_read)
Reads a null terminated string from memory.
virtual bool IsAlive () const
virtual const HardwareBreakpointMap & GetHardwareBreakpointMap () const
virtual Status SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual Status RemoveHardwareBreakpoint (lldb::addr_t addr)
virtual const NativeWatchpointList::WatchpointMap & GetWatchpointMap () const
virtual std::optional< std::pair< uint32_t, uint32_t > > GetHardwareDebugSupportInfo () const
virtual Status SetWatchpoint (lldb::addr_t addr, size_t size, uint32_t watch_flags, bool hardware)
virtual Status RemoveWatchpoint (lldb::addr_t addr)
lldb::pid_t GetID () const
lldb::StateType GetState () const
bool IsRunning () const
bool IsStepping () const
bool CanResume () const
lldb::ByteOrder GetByteOrder () const
uint32_t GetAddressByteSize () const
virtual std::optional< WaitStatus > GetExitStatus ()
virtual bool SetExitStatus (WaitStatus status, bool bNotifyStateChange)
NativeThreadProtocol * GetThreadAtIndex (uint32_t idx)
NativeThreadProtocol * GetThreadByID (lldb::tid_t tid)
void SetCurrentThreadID (lldb::tid_t tid)
lldb::tid_t GetCurrentThreadID () const
NativeThreadProtocol * GetCurrentThread ()
ThreadIterable Threads () const
virtual int GetTerminalFileDescriptor ()
uint32_t GetStopID () const
virtual void SetEnabledExtensions (Extension flags)
Method called in order to propagate the bitmap of protocol extensions supported by the client.
virtual llvm::Expected< std::string > SaveCore (llvm::StringRef path_hint)
Write a core dump (without crashing the program).
virtual std::vector< std::string > GetStructuredDataPlugins ()
Get the list of structured data plugins supported by this process.
Manager & m_manager
ArchSpec m_arch
LazyBool m_supports_mem_region = eLazyBoolCalculate
std::vector< std::pair< MemoryRegionInfo, FileSpec > > m_mem_region_cache
lldb::tid_t m_pending_notification_tid = LLDB_INVALID_THREAD_ID
llvm::DenseMap< lldb::addr_t, lldb::addr_t > m_allocated_memory
Inferior memory (allocated by us) and its size.
IntelPTCollector m_intel_pt_collector
Manages Intel PT process and thread traces.
llvm::Error TraceStart (llvm::StringRef json_request, llvm::StringRef type) override
Tracing These methods implement the jLLDBTrace packets.
llvm::Error TraceStop (const TraceStopRequest &request) override
Stop tracing a live process or its threads.
llvm::Expected< llvm::json::Value > TraceGetState (llvm::StringRef type) override
Get the current tracing state of the process and its threads.
llvm::Expected< std::vector< uint8_t > > TraceGetBinaryData (const TraceGetBinaryDataRequest &request) override
Get binary data given a trace technology and a data identifier.
llvm::Expected< TraceSupportedResponse > TraceSupported () override
Get the processor tracing type supported for this process.
bool SupportHardwareSingleStepping () const
Status GetSignalInfo (lldb::tid_t tid, void *siginfo) const
Writes a siginfo_t structure corresponding to the given thread ID to the memory region pointed to by siginfo.
static Status PtraceWrapper (int req, lldb::pid_t pid, void *addr=nullptr, void *data=nullptr, size_t data_size=0, long *result=nullptr)
}
llvm::Expected< llvm::ArrayRef< uint8_t > > GetSoftwareBreakpointTrapOpcode (size_t size_hint) override
llvm::Expected< uint64_t > Syscall (llvm::ArrayRef< uint64_t > args)
NativeProcessLinux (::pid_t pid, int terminal_fd, NativeDelegate &delegate, const ArchSpec &arch, Manager &manager, llvm::ArrayRef<::pid_t > tids)
bool TryHandleWaitStatus (lldb::pid_t pid, WaitStatus status)
void MonitorCallback (NativeThreadLinux &thread, WaitStatus status)
void MonitorSIGTRAP (const siginfo_t &info, NativeThreadLinux &thread)
void MonitorTrace (NativeThreadLinux &thread)
void MonitorBreakpoint (NativeThreadLinux &thread)
void MonitorWatchpoint (NativeThreadLinux &thread, uint32_t wp_index)
void MonitorSignal (const siginfo_t &info, NativeThreadLinux &thread)
bool HasThreadNoLock (lldb::tid_t thread_id)
void StopTrackingThread (NativeThreadLinux &thread)
NativeThreadLinux & AddThread (lldb::tid_t thread_id, bool resume)
Create a new thread.
Status NotifyTracersOfNewThread (lldb::tid_t tid)
Start tracing a new thread if process tracing is enabled.
Status NotifyTracersOfThreadDestroyed (lldb::tid_t tid)
Stop tracing threads upon a destroy event.
void NotifyTracersProcessWillResume () override
Notify tracers that the target process will resume.
void NotifyTracersProcessDidStop () override
Notify tracers that the target process just stopped.
Status GetEventMessage (lldb::tid_t tid, unsigned long *message)
Writes the raw event message code (vis-a-vis PTRACE_GETEVENTMSG) corresponding to the given thread ID to the memory pointed to by message.
void NotifyThreadDeath (lldb::tid_t tid)
Status Detach (lldb::tid_t tid)
void StopRunningThreads (lldb::tid_t triggering_tid)
void SignalIfAllThreadsStopped ()
Status ResumeThread (NativeThreadLinux &thread, lldb::StateType state, int signo)
void ThreadWasCreated (NativeThreadLinux &thread)
void SigchldHandler ()
Status PopulateMemoryRegionCache ()
bool MonitorClone (NativeThreadLinux &parent, lldb::pid_t child_pid, int event)
static llvm::Expected< std::vector<::pid_t > > Attach (::pid_t pid)
static Status SetDefaultPtraceOpts (const lldb::pid_t)
Additional Inherited Members
Public Types inherited from lldb_private::NativeProcessProtocol
enum class Extension {
multiprocess = (1u << 0) , fork = (1u << 1) , vfork = (1u << 2) , pass_signals = (1u << 3) ,
auxv = (1u << 4) , libraries_svr4 = (1u << 5) , memory_tagging = (1u << 6) , savecore = (1u << 7) ,
siginfo_read = (1u << 8)
}
Extension flag constants, returned by Manager::GetSupportedExtensions() and passed to SetEnabledExtension()
typedef std::vector< std::unique_ptr< NativeThreadProtocol > > thread_collection
typedef LockingAdaptedIterable< std::recursive_mutex, thread_collection, llvm::pointee_iterator< thread_collection::const_iterator > > ThreadIterable
Protected Member Functions inherited from lldb_private::NativeProcessELF
lldb::addr_t GetSharedLibraryInfoAddress () override
template<typename ELF_EHDR, typename ELF_PHDR, typename ELF_DYN>
lldb::addr_t GetELFImageInfoAddress ()
llvm::Expected< std::vector< SVR4LibraryInfo > > GetLoadedSVR4Libraries () override
template<typename T>
llvm::Expected< SVR4LibraryInfo > ReadSVR4LibraryInfo (lldb::addr_t link_map_addr)
void NotifyDidExec () override
Notify the delegate that an exec occurred.
Protected Member Functions inherited from lldb_private::NativeProcessProtocol
NativeProcessProtocol (lldb::pid_t pid, int terminal_fd, NativeDelegate &delegate)
void SetID (lldb::pid_t pid)
void SetState (lldb::StateType state, bool notify_delegates=true)
Status SetSoftwareBreakpoint (lldb::addr_t addr, uint32_t size_hint)
Status RemoveSoftwareBreakpoint (lldb::addr_t addr)
virtual size_t GetSoftwareBreakpointPCOffset ()
Return the offset of the PC relative to the software breakpoint that was hit.
void FixupBreakpointPCAsNeeded (NativeThreadProtocol &thread)
NativeThreadProtocol * GetThreadByIDUnlocked (lldb::tid_t tid)
Protected Attributes inherited from lldb_private::NativeProcessELF
std::unique_ptr< AuxVector > m_aux_vector
std::optional< lldb::addr_t > m_shared_library_info_addr
Protected Attributes inherited from lldb_private::NativeProcessProtocol
std::unordered_map< lldb::addr_t, SoftwareBreakpoint > m_software_breakpoints
lldb::pid_t m_pid
std::vector< std::unique_ptr< NativeThreadProtocol > > m_threads
lldb::tid_t m_current_thread_id = LLDB_INVALID_THREAD_ID
std::recursive_mutex m_threads_mutex
lldb::StateType m_state = lldb::eStateInvalid
std::recursive_mutex m_state_mutex
std::optional< WaitStatus > m_exit_status
NativeDelegate & m_delegate
NativeWatchpointList m_watchpoint_list
HardwareBreakpointMap m_hw_breakpoints_map
int m_terminal_fd
uint32_t m_stop_id = 0
llvm::DenseSet< int > m_signals_to_ignore
Extension m_enabled_extensions
Private Member Functions inherited from lldb_private::NativeProcessSoftwareSingleStep
Status SetupSoftwareSingleStepping (NativeThreadProtocol &thread)
Private Attributes inherited from lldb_private::NativeProcessSoftwareSingleStep
std::map< lldb::tid_t, std::vector< lldb::addr_t > > m_threads_stepping_with_breakpoint
Detailed Description
Manages communication with the inferior (debugee) process.
Upon construction, this class prepares and launches an inferior process for debugging.
Changes in the inferior process state are broadcasted.
Definition at line 42 of file NativeProcessLinux.h.
Constructor & Destructor Documentation
~NativeProcessLinux()
lldb_private::process_linux::NativeProcessLinux::~NativeProcessLinux () inline override
Definition at line 82 of file NativeProcessLinux.h.
References m_manager.
NativeProcessLinux()
NativeProcessLinux::NativeProcessLinux (::pid_t pid, int terminal_fd, NativeDelegate & delegate, const ArchSpec & arch, Manager & manager, llvm::ArrayRef<::pid_t > tids) private
Definition at line 427 of file NativeProcessLinux.cpp.
References lldb_private::process_linux::NativeProcessLinux::Manager::AddProcess(), AddThread(), EnsureFDFlags(), lldb::eStateStopped, m_arch, m_intel_pt_collector, m_manager, lldb_private::NativeProcessProtocol::m_terminal_fd, O_NONBLOCK, lldb_private::NativeProcessProtocol::SetCurrentThreadID(), lldb_private::NativeProcessProtocol::SetState(), lldb_private::Status::Success(), and ThreadWasCreated().
Referenced by lldb_private::process_linux::NativeProcessLinux::Manager::AddProcess(), lldb_private::process_linux::NativeProcessLinux::Manager::Attach(), lldb_private::process_linux::NativeProcessLinux::Manager::Launch(), MonitorClone(), lldb_private::process_linux::NativeProcessLinux::Manager::RemoveProcess(), and lldb_private::process_linux::NativeProcessLinux::Manager::SigchldHandler().
Member Function Documentation
AddThread()
NativeThreadLinux & NativeProcessLinux::AddThread (lldb::tid_t thread_id, bool resume) private
Create a new thread.
If process tracing is enabled and the thread can't be traced, then the thread is left stopped with a eStopReasonProcessorTrace status, and then the process is stopped.
Parameters
[in] resume If a tracing error didn't happen, then resume the thread after creation if true, or leave it stopped with SIGSTOP if false.
Definition at line 1795 of file NativeProcessLinux.cpp.
References lldb_private::Status::AsCString(), lldb::eStateRunning, lldb_private::Status::Fail(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), HasThreadNoLock(), LLDB_INVALID_SIGNAL_NUMBER, LLDB_LOG, lldb_private::NativeProcessProtocol::m_threads, NotifyTracersOfNewThread(), ResumeThread(), lldb_private::NativeProcessProtocol::SetCurrentThreadID(), SIGSTOP, StopRunningThreads(), and lldb_private::Thread.
Referenced by MonitorClone(), and NativeProcessLinux().
AllocateMemory()
llvm::Expected< addr_t > NativeProcessLinux::AllocateMemory (size_t size, uint32_t permissions) override virtual
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 1411 of file NativeProcessLinux.cpp.
References GetCurrentThread(), lldb_private::process_linux::NativeRegisterContextLinux::GetMmapData(), lldb_private::process_linux::NativeThreadLinux::GetRegisterContext(), m_allocated_memory, MAP_PRIVATE, PROT_EXEC, PROT_NONE, PROT_READ, PROT_WRITE, and Syscall().
Attach()
llvm::Expected< std::vector<::pid_t > > NativeProcessLinux::Attach (::pid_t pid) static private
Definition at line 449 of file NativeProcessLinux.cpp.
References AddPtraceScopeNote(), lldb_private::Host::FindProcessThreads(), lldb_private::Status::GetError(), lldb_private::GetLog(), LLDB_LOG, lldb_private::Process, PtraceWrapper(), SetDefaultPtraceOpts(), and lldb_private::Status::ToError().
Referenced by lldb_private::process_linux::NativeProcessLinux::Manager::Attach().
DeallocateMemory()
llvm::Error NativeProcessLinux::DeallocateMemory (lldb::addr_t addr) override virtual
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 1437 of file NativeProcessLinux.cpp.
References GetCurrentThread(), lldb_private::process_linux::NativeRegisterContextLinux::GetMmapData(), lldb_private::process_linux::NativeThreadLinux::GetRegisterContext(), m_allocated_memory, and Syscall().
Detach() [1/2]
Status NativeProcessLinux::Detach () override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 1071 of file NativeProcessLinux.cpp.
References lldb_private::Status::Clone(), Detach(), error(), lldb_private::Status::Fail(), lldb_private::NativeProcessProtocol::GetID(), LLDB_INVALID_PROCESS_ID, m_intel_pt_collector, and lldb_private::NativeProcessProtocol::m_threads.
Referenced by Detach().
Detach() [2/2]
Status NativeProcessLinux::Detach (lldb::tid_t tid) private
Definition at line 1733 of file NativeProcessLinux.cpp.
References LLDB_INVALID_THREAD_ID, PtraceWrapper(), and lldb_private::Status.
DoStopIDBumped()
void NativeProcessLinux::DoStopIDBumped (uint32_t newBumpId) override virtual
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 1318 of file NativeProcessLinux.cpp.
References lldb_private::GetLog(), LLDB_LOG, m_mem_region_cache, and lldb_private::Process.
GetArchitecture()
const ArchSpec & lldb_private::process_linux::NativeProcessLinux::GetArchitecture () const inline override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 118 of file NativeProcessLinux.h.
References m_arch.
Referenced by GetSoftwareBreakpointTrapOpcode().
GetAuxvData()
llvm::ErrorOr< std::unique_ptr< llvm::MemoryBuffer > > lldb_private::process_linux::NativeProcessLinux::GetAuxvData () const inline override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 137 of file NativeProcessLinux.h.
References lldb_private::NativeProcessProtocol::GetID(), and lldb_private::getProcFile().
GetCurrentThread()
NativeThreadLinux * NativeProcessLinux::GetCurrentThread ()
Definition at line 1866 of file NativeProcessLinux.cpp.
References lldb_private::NativeProcessProtocol::GetCurrentThread().
Referenced by AllocateMemory(), DeallocateMemory(), ReadMemoryTags(), Syscall(), and WriteMemoryTags().
GetEventMessage()
Status NativeProcessLinux::GetEventMessage (lldb::tid_t tid, unsigned long * message) private
Writes the raw event message code (vis-a-vis PTRACE_GETEVENTMSG) corresponding to the given thread ID to the memory pointed to by message.
Definition at line 1728 of file NativeProcessLinux.cpp.
References PtraceWrapper().
Referenced by MonitorSIGTRAP().
GetFileLoadAddress()
Status NativeProcessLinux::GetFileLoadAddress (const llvm::StringRef & file_name, lldb::addr_t & load_addr) override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 1844 of file NativeProcessLinux.cpp.
References error(), lldb_private::Status::FromErrorString(), LLDB_INVALID_ADDRESS, m_mem_region_cache, PopulateMemoryRegionCache(), and lldb_private::Status.
GetLoadedModuleFileSpec()
Status NativeProcessLinux::GetLoadedModuleFileSpec (const char * module_path, FileSpec & file_spec) override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 1823 of file NativeProcessLinux.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::FileSpec::Clear(), error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::FileSpec::GetFilename(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::FileSystem::Instance(), m_mem_region_cache, PopulateMemoryRegionCache(), lldb_private::FileSystem::Resolve(), and lldb_private::Status.
GetMemoryRegionInfo()
Status NativeProcessLinux::GetMemoryRegionInfo (lldb::addr_t load_addr, MemoryRegionInfo & range_info) override virtual
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 1186 of file NativeProcessLinux.cpp.
References lldb_private::Range< B, S >::Contains(), lldb_private::eLazyBoolNo, lldb_private::MemoryRegionInfo::eNo, error(), lldb_private::Status::FromErrorString(), lldb_private::MemoryRegionInfo::GetRange(), lldb_private::Range< B, S >::GetRangeBase(), LLDB_INVALID_ADDRESS, m_mem_region_cache, m_supports_mem_region, PopulateMemoryRegionCache(), lldb_private::Range< B, S >::SetByteSize(), lldb_private::MemoryRegionInfo::SetExecutable(), lldb_private::MemoryRegionInfo::SetMapped(), lldb_private::Range< B, S >::SetRangeBase(), lldb_private::Range< B, S >::SetRangeEnd(), lldb_private::MemoryRegionInfo::SetReadable(), lldb_private::MemoryRegionInfo::SetWritable(), and UNUSED_IF_ASSERT_DISABLED.
GetSignalInfo()
Status NativeProcessLinux::GetSignalInfo (lldb::tid_t tid, void * siginfo) const
Writes a siginfo_t structure corresponding to the given thread ID to the memory region pointed to by siginfo.
Definition at line 1724 of file NativeProcessLinux.cpp.
References PtraceWrapper().
Referenced by lldb_private::process_linux::NativeThreadLinux::GetSiginfo(), and MonitorCallback().
GetSoftwareBreakpointTrapOpcode()
llvm::Expected< llvm::ArrayRef< uint8_t > > NativeProcessLinux::GetSoftwareBreakpointTrapOpcode (size_t size_hint) override protected virtual
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 1605 of file NativeProcessLinux.cpp.
References GetArchitecture(), and lldb_private::NativeProcessProtocol::GetSoftwareBreakpointTrapOpcode().
GetThreadByID()
NativeThreadLinux * NativeProcessLinux::GetThreadByID (lldb::tid_t id)
Definition at line 1861 of file NativeProcessLinux.cpp.
References lldb_private::NativeProcessProtocol::GetThreadByID().
Referenced by TryHandleWaitStatus().
Halt()
Status NativeProcessLinux::Halt () override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 1062 of file NativeProcessLinux.cpp.
References error(), lldb_private::Status::FromErrno(), lldb_private::NativeProcessProtocol::GetID(), and SIGSTOP.
HasThreadNoLock()
bool NativeProcessLinux::HasThreadNoLock (lldb::tid_t thread_id) private
Definition at line 1740 of file NativeProcessLinux.cpp.
References lldb_private::NativeProcessProtocol::m_threads.
Referenced by AddThread().
Interrupt()
Status NativeProcessLinux::Interrupt () override virtual
Tells a process to interrupt all operations as if by a Ctrl-C.
The default implementation will send a local host's equivalent of a SIGSTOP to the process via the NativeProcessProtocol::Signal() operation.
Returns
Returns an error object.
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 1107 of file NativeProcessLinux.cpp.
References error(), lldb::eStateRunning, lldb::eStateStepping, lldb_private::NativeProcessProtocol::GetID(), lldb_private::NativeThreadProtocol::GetID(), lldb_private::GetLog(), LLDB_LOG, lldb_private::NativeProcessProtocol::m_threads, lldb_private::Process, lldb_private::StateIsStoppedState(), lldb_private::Status, and StopRunningThreads().
Kill()
Status NativeProcessLinux::Kill () override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 1150 of file NativeProcessLinux.cpp.
References error(), lldb::eStateAttaching, lldb::eStateConnected, lldb::eStateCrashed, lldb::eStateDetached, lldb::eStateExited, lldb::eStateInvalid, lldb::eStateLaunching, lldb::eStateRunning, lldb::eStateStepping, lldb::eStateStopped, lldb::eStateSuspended, lldb::eStateUnloaded, lldb_private::Status::FromErrno(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), LLDB_LOG, lldb_private::NativeProcessProtocol::m_state, lldb_private::Process, and SIGKILL.
MonitorBreakpoint()
void NativeProcessLinux::MonitorBreakpoint (NativeThreadLinux & thread) private
Definition at line 806 of file NativeProcessLinux.cpp.
References lldb_private::Breakpoints, lldb_private::NativeProcessProtocol::FixupBreakpointPCAsNeeded(), lldb_private::GetLog(), lldb_private::NativeRegisterContext::GetPC(), LLDB_LOG, lldb_private::NativeProcessSoftwareSingleStep::m_threads_stepping_with_breakpoint, lldb_private::Process, and StopRunningThreads().
Referenced by MonitorSIGTRAP().
MonitorCallback()
void NativeProcessLinux::MonitorCallback (NativeThreadLinux & thread, WaitStatus status) private
Definition at line 560 of file NativeProcessLinux.cpp.
References lldb_private::WaitStatus::Exit, lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), GetSignalInfo(), lldb_private::NativeProcessProtocol::GetState(), LLDB_INVALID_SIGNAL_NUMBER, LLDB_LOG, MonitorSignal(), MonitorSIGTRAP(), lldb_private::Process, ResumeThread(), lldb_private::WaitStatus::Signal, SIGTRAP, StopTrackingThread(), and lldb_private::WaitStatus::type.
Referenced by TryHandleWaitStatus().
MonitorClone()
bool NativeProcessLinux::MonitorClone (NativeThreadLinux & parent, lldb::pid_t child_pid, int event) private
Definition at line 926 of file NativeProcessLinux.cpp.
References AddThread(), lldb_private::NativeProcessProtocol::fork, lldb_private::NativeProcessProtocol::GetID(), lldb_private::NativeThreadProtocol::GetID(), lldb_private::GetLog(), lldb_private::getPIDForTID(), lldb_private::process_linux::NativeThreadLinux::GetState(), LLDB_INVALID_SIGNAL_NUMBER, LLDB_LOG, m_arch, lldb_private::NativeProcessProtocol::m_delegate, lldb_private::NativeProcessProtocol::m_enabled_extensions, m_manager, lldb_private::NativeProcessProtocol::m_software_breakpoints, lldb_private::NativeProcessProtocol::m_terminal_fd, NativeProcessLinux(), lldb_private::Process, ResumeThread(), lldb_private::process_linux::NativeThreadLinux::SetStoppedByFork(), StopRunningThreads(), ThreadWasCreated(), and lldb_private::NativeProcessProtocol::vfork.
Referenced by MonitorSIGTRAP().
MonitorSignal()
void NativeProcessLinux::MonitorSignal (const siginfo_t & info, NativeThreadLinux & thread) private
Definition at line 839 of file NativeProcessLinux.cpp.
References error(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), lldb_private::Host::GetSignalAsCString(), LLDB_INVALID_THREAD_ID, LLDB_LOG, m_pending_notification_tid, lldb_private::NativeProcessProtocol::m_signals_to_ignore, lldb_private::Process, ResumeThread(), lldb_private::NativeProcessProtocol::SetCurrentThreadID(), SignalIfAllThreadsStopped(), SIGSTOP, lldb_private::StateIsStoppedState(), and StopRunningThreads().
Referenced by MonitorCallback(), and MonitorSIGTRAP().
MonitorSIGTRAP()
void NativeProcessLinux::MonitorSIGTRAP (const siginfo_t & info, NativeThreadLinux & thread) private
Definition at line 627 of file NativeProcessLinux.cpp.
References error(), lldb::eStateRunning, lldb_private::Status::Fail(), GetEventMessage(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), LLDB_INVALID_INDEX32, LLDB_INVALID_SIGNAL_NUMBER, LLDB_INVALID_THREAD_ID, LLDB_LOG, lldb_private::NativeProcessProtocol::m_enabled_extensions, m_pending_notification_tid, lldb_private::NativeProcessProtocol::m_threads, MonitorBreakpoint(), MonitorClone(), MonitorSignal(), MonitorTrace(), MonitorWatchpoint(), lldb_private::NativeProcessELF::NotifyDidExec(), lldb_private::Process, ResumeThread(), lldb_private::NativeProcessProtocol::SetCurrentThreadID(), SIGTRAP, lldb_private::StateIsRunningState(), StopRunningThreads(), StopTrackingThread(), ThreadWasCreated(), TRAP_HWBKPT, and lldb_private::NativeProcessProtocol::vfork.
Referenced by MonitorCallback().
MonitorTrace()
void NativeProcessLinux::MonitorTrace (NativeThreadLinux & thread) private
Definition at line 796 of file NativeProcessLinux.cpp.
References lldb_private::GetLog(), LLDB_LOG, lldb_private::Process, and StopRunningThreads().
Referenced by MonitorSIGTRAP().
MonitorWatchpoint()
void NativeProcessLinux::MonitorWatchpoint (NativeThreadLinux & thread, uint32_t wp_index) private
Definition at line 824 of file NativeProcessLinux.cpp.
References lldb_private::GetLog(), LLDB_LOG, lldb_private::Process, StopRunningThreads(), and lldb_private::Watchpoints.
Referenced by MonitorSIGTRAP().
NotifyThreadDeath()
void lldb_private::process_linux::NativeProcessLinux::NotifyThreadDeath (lldb::tid_t tid) private
NotifyTracersOfNewThread()
Status NativeProcessLinux::NotifyTracersOfNewThread (lldb::tid_t tid) private
Start tracing a new thread if process tracing is enabled.
Trace mechanisms should modify this method to provide automatic tracing for new threads.
Definition at line 1776 of file NativeProcessLinux.cpp.
References error(), lldb_private::Status::FromError(), lldb_private::GetLog(), LLDB_LOG, m_intel_pt_collector, and lldb_private::Thread.
Referenced by AddThread().
NotifyTracersOfThreadDestroyed()
Status NativeProcessLinux::NotifyTracersOfThreadDestroyed (lldb::tid_t tid) private
Stop tracing threads upon a destroy event.
Trace mechanisms should modify this method to provide automatic trace stopping for threads being destroyed.
Definition at line 1785 of file NativeProcessLinux.cpp.
References error(), lldb_private::Status::FromError(), lldb_private::GetLog(), LLDB_LOG, m_intel_pt_collector, and lldb_private::Thread.
Referenced by StopTrackingThread().
NotifyTracersProcessDidStop()
void NativeProcessLinux::NotifyTracersProcessDidStop () override private virtual
Notify tracers that the target process just stopped.
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 1768 of file NativeProcessLinux.cpp.
References m_intel_pt_collector.
NotifyTracersProcessWillResume()
void NativeProcessLinux::NotifyTracersProcessWillResume () override private virtual
Notify tracers that the target process will resume.
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 1772 of file NativeProcessLinux.cpp.
References m_intel_pt_collector.
Referenced by Resume().
PopulateMemoryRegionCache()
Status NativeProcessLinux::PopulateMemoryRegionCache () private
Definition at line 1255 of file NativeProcessLinux.cpp.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb_private::Status::Fail(), lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), lldb_private::NativeProcessProtocol::GetCurrentThreadID(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), lldb_private::getProcFile(), lldb_private::FileSystem::Instance(), LLDB_LOG, m_mem_region_cache, m_supports_mem_region, lldb_private::ParseLinuxMapRegions(), lldb_private::ParseLinuxSMapRegions(), lldb_private::Process, lldb_private::FileSystem::Resolve(), and lldb_private::Status.
Referenced by GetFileLoadAddress(), GetLoadedModuleFileSpec(), GetMemoryRegionInfo(), and Syscall().
PtraceWrapper()
Status NativeProcessLinux::PtraceWrapper (int req, lldb::pid_t pid, void * addr = nullptr, void * data = nullptr, size_t data_size = 0, long * result = nullptr) static
}
Definition at line 1974 of file NativeProcessLinux.cpp.
References error(), lldb_private::Status::FromErrno(), lldb_private::GetLog(), LLDB_LOG, lldb_private::Ptrace, PTRACE_GETREGSET, PTRACE_SETREGSET, and PtraceDisplayBytes().
Referenced by Attach(), Detach(), lldb_private::process_linux::NativeRegisterContextLinux::DetermineArchitectureViaGPR(), lldb_private::process_linux::NativeRegisterContextLinux::DoReadRegisterValue(), lldb_private::process_linux::NativeRegisterContextLinux::DoWriteRegisterValue(), GetEventMessage(), GetSignalInfo(), lldb_private::process_linux::NativeRegisterContextLinux::ReadFPR(), lldb_private::process_linux::NativeRegisterContextLinux::ReadGPR(), ReadMemory(), ReadMemoryTags(), lldb_private::process_linux::NativeRegisterContextLinux::ReadRegisterSet(), lldb_private::process_linux::NativeThreadLinux::Resume(), SetDefaultPtraceOpts(), lldb_private::process_linux::NativeThreadLinux::SingleStep(), Syscall(), lldb_private::process_linux::NativeRegisterContextLinux::WriteFPR(), lldb_private::process_linux::NativeRegisterContextLinux::WriteGPR(), WriteMemory(), WriteMemoryTags(), and lldb_private::process_linux::NativeRegisterContextLinux::WriteRegisterSet().
ReadMemory()
Status NativeProcessLinux::ReadMemory (lldb::addr_t addr, void * buf, size_t size, size_t & bytes_read) override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 1627 of file NativeProcessLinux.cpp.
References error(), lldb_private::NativeProcessProtocol::GetCurrentThreadID(), lldb_private::GetLog(), k_ptrace_word_size, LLDB_LOG, lldb_private::Memory, process_vm_readv(), ProcessVmReadvSupported(), PtraceWrapper(), and lldb_private::Status.
Referenced by Syscall(), and WriteMemory().
ReadMemoryTags()
Status NativeProcessLinux::ReadMemoryTags (int32_t type, lldb::addr_t addr, size_t len, std::vector< uint8_t > & tags) override virtual
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 1457 of file NativeProcessLinux.cpp.
References error(), lldb_private::Status::FromError(), lldb_private::Range< B, S >::GetByteSize(), GetCurrentThread(), lldb_private::NativeProcessProtocol::GetCurrentThreadID(), lldb_private::process_linux::NativeRegisterContextLinux::GetMemoryTaggingDetails(), lldb_private::Range< B, S >::GetRangeBase(), lldb_private::process_linux::NativeThreadLinux::GetRegisterContext(), PtraceWrapper(), and lldb_private::Status.
Referenced by lldb_private::process_linux::NativeThreadLinux::AnnotateSyncTagCheckFault().
RemoveBreakpoint()
Status NativeProcessLinux::RemoveBreakpoint (lldb::addr_t addr, bool hardware = false) override virtual
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 1597 of file NativeProcessLinux.cpp.
References lldb_private::NativeProcessProtocol::RemoveBreakpoint(), and lldb_private::NativeProcessProtocol::RemoveHardwareBreakpoint().
Referenced by SignalIfAllThreadsStopped().
Resume()
Status NativeProcessLinux::Resume (const ResumeActionList & resume_actions) override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 989 of file NativeProcessLinux.cpp.
References error(), lldb::eStateRunning, lldb::eStateStepping, lldb::eStateStopped, lldb::eStateSuspended, lldb_private::Status::FromErrorStringWithFormat(), lldb_private::ResumeActionList::GetActionForThread(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), LLDB_LOG, lldb_private::NativeProcessProtocol::m_threads, NotifyTracersProcessWillResume(), lldb_private::Process, ResumeThread(), lldb_private::NativeProcessSoftwareSingleStep::SetupSoftwareSingleStepping(), lldb_private::ResumeAction::signal, lldb_private::ResumeAction::state, lldb_private::StateAsCString(), lldb_private::Status, and SupportHardwareSingleStepping().
ResumeThread()
Status NativeProcessLinux::ResumeThread (NativeThreadLinux & thread, lldb::StateType state, int signo) private
Definition at line 1871 of file NativeProcessLinux.cpp.
References lldb::eStateRunning, lldb::eStateStepping, lldb_private::GetLog(), LLDB_INVALID_THREAD_ID, LLDB_LOG, m_pending_notification_tid, lldb_private::NativeProcessProtocol::SetState(), lldb_private::Status::Success(), and lldb_private::Thread.
Referenced by AddThread(), MonitorCallback(), MonitorClone(), MonitorSignal(), MonitorSIGTRAP(), and Resume().
SetBreakpoint()
Status NativeProcessLinux::SetBreakpoint (lldb::addr_t addr, uint32_t size, bool hardware) override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 1589 of file NativeProcessLinux.cpp.
References lldb_private::NativeProcessProtocol::SetHardwareBreakpoint(), and lldb_private::NativeProcessProtocol::SetSoftwareBreakpoint().
SetDefaultPtraceOpts()
Status NativeProcessLinux::SetDefaultPtraceOpts (const lldb::pid_t pid) static private
Definition at line 518 of file NativeProcessLinux.cpp.
References PtraceWrapper().
Referenced by Attach(), and lldb_private::process_linux::NativeProcessLinux::Manager::Launch().
SigchldHandler()
void lldb_private::process_linux::NativeProcessLinux::SigchldHandler () private
Signal()
Status NativeProcessLinux::Signal (int signo) override virtual
Sends a process a UNIX signal signal.
Returns
Returns an error object.
Implements lldb_private::NativeProcessProtocol.
Definition at line 1094 of file NativeProcessLinux.cpp.
References error(), lldb_private::Status::FromErrno(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), lldb_private::Host::GetSignalAsCString(), LLDB_LOG, and lldb_private::Process.
SignalIfAllThreadsStopped()
void NativeProcessLinux::SignalIfAllThreadsStopped () private
Definition at line 1930 of file NativeProcessLinux.cpp.
References lldb_private::Breakpoints, error(), lldb::eStateStopped, lldb_private::GetLog(), LLDB_INVALID_THREAD_ID, LLDB_LOG, m_pending_notification_tid, lldb_private::NativeProcessProtocol::m_threads, lldb_private::NativeProcessSoftwareSingleStep::m_threads_stepping_with_breakpoint, lldb_private::Process, RemoveBreakpoint(), lldb_private::NativeProcessProtocol::SetCurrentThreadID(), lldb_private::NativeProcessProtocol::SetState(), and lldb_private::StateIsRunningState().
Referenced by MonitorSignal(), StopRunningThreads(), and StopTrackingThread().
StopRunningThreads()
void NativeProcessLinux::StopRunningThreads (lldb::tid_t triggering_tid) private
Definition at line 1912 of file NativeProcessLinux.cpp.
References lldb_private::GetLog(), LLDB_LOG, m_pending_notification_tid, lldb_private::NativeProcessProtocol::m_threads, lldb_private::process_linux::NativeThreadLinux::RequestStop(), SignalIfAllThreadsStopped(), lldb_private::StateIsRunningState(), and lldb_private::Thread.
Referenced by AddThread(), Interrupt(), MonitorBreakpoint(), MonitorClone(), MonitorSignal(), MonitorSIGTRAP(), MonitorTrace(), and MonitorWatchpoint().
StopTrackingThread()
void NativeProcessLinux::StopTrackingThread (NativeThreadLinux & thread) private
Definition at line 1753 of file NativeProcessLinux.cpp.
References lldb_private::GetLog(), LLDB_LOG, lldb_private::NativeProcessProtocol::m_threads, NotifyTracersOfThreadDestroyed(), SignalIfAllThreadsStopped(), and lldb_private::Thread.
Referenced by MonitorCallback(), and MonitorSIGTRAP().
SupportHardwareSingleStepping()
bool NativeProcessLinux::SupportHardwareSingleStepping () const
Definition at line 982 of file NativeProcessLinux.cpp.
References m_arch.
Referenced by Resume(), and Syscall().
Syscall()
llvm::Expected< uint64_t > NativeProcessLinux::Syscall (llvm::ArrayRef< uint64_t > args) protected
Definition at line 1327 of file NativeProcessLinux.cpp.
References lldb_private::process_linux::NativeRegisterContextLinux::SyscallData::Args, lldb::eStateStopped, lldb_private::MemoryRegionInfo::eYes, GetCurrentThread(), lldb_private::process_linux::NativeRegisterContextLinux::GetSyscallData(), lldb_private::process_linux::NativeRegisterContextLinux::SyscallData::Insn, m_arch, m_mem_region_cache, PopulateMemoryRegionCache(), PtraceWrapper(), lldb_private::NativeRegisterContext::ReadAllRegisterValues(), ReadMemory(), lldb_private::NativeRegisterContext::ReadRegisterAsUnsigned(), lldb_private::process_linux::NativeRegisterContextLinux::SyscallData::Result, lldb_private::NativeRegisterContext::SetPC(), SupportHardwareSingleStepping(), lldb_private::Status::ToError(), lldb_private::NativeRegisterContext::WriteAllRegisterValues(), and WriteMemory().
Referenced by AllocateMemory(), and DeallocateMemory().
ThreadWasCreated()
void NativeProcessLinux::ThreadWasCreated (NativeThreadLinux & thread) private
Definition at line 1960 of file NativeProcessLinux.cpp.
References lldb_private::GetLog(), LLDB_INVALID_THREAD_ID, LLDB_LOG, m_pending_notification_tid, lldb_private::StateIsRunningState(), and lldb_private::Thread.
Referenced by MonitorClone(), MonitorSIGTRAP(), and NativeProcessLinux().
TraceGetBinaryData()
Expected< std::vector< uint8_t > > NativeProcessLinux::TraceGetBinaryData (const TraceGetBinaryDataRequest & request) override virtual
Get binary data given a trace technology and a data identifier.
Parameters
[in] request Object with the params of the requested data.
Returns
A vector of bytes with the requested data, or an llvm::Error in case of failures.
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 2040 of file NativeProcessLinux.cpp.
References m_intel_pt_collector, lldb_private::NativeProcessProtocol::TraceGetBinaryData(), and lldb_private::TraceGetBinaryDataRequest::type.
TraceGetState()
Expected< json::Value > NativeProcessLinux::TraceGetState (llvm::StringRef type) override virtual
Get the current tracing state of the process and its threads.
Parameters
[in] type Tracing technology type to consider.
Returns
A JSON object string with custom data depending on the trace technology, or an llvm::Error in case of errors.
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 2034 of file NativeProcessLinux.cpp.
References m_intel_pt_collector, and lldb_private::NativeProcessProtocol::TraceGetState().
TraceStart()
Error NativeProcessLinux::TraceStart (llvm::StringRef json_request, llvm::StringRef type) override virtual
Tracing These methods implement the jLLDBTrace packets.
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 2015 of file NativeProcessLinux.cpp.
References m_intel_pt_collector, and lldb_private::NativeProcessProtocol::TraceStart().
TraceStop()
Error NativeProcessLinux::TraceStop (const TraceStopRequest & request) override virtual
Stop tracing a live process or its threads.
Parameters
[in] request The information determining which threads or process to stop tracing.
Returns
llvm::Error::success if the operation was successful, or llvm::Error otherwise.
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 2028 of file NativeProcessLinux.cpp.
References m_intel_pt_collector, lldb_private::NativeProcessProtocol::TraceStop(), and lldb_private::TraceStopRequest::type.
TraceSupported()
llvm::Expected< TraceSupportedResponse > NativeProcessLinux::TraceSupported () override virtual
Get the processor tracing type supported for this process.
Responses might be different depending on the architecture and capabilities of the underlying OS.
Returns
The supported trace type or an llvm::Error if tracing is not supported for the inferior.
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 2009 of file NativeProcessLinux.cpp.
References lldb_private::process_linux::IntelPTCollector::IsSupported(), and lldb_private::NativeProcessProtocol::TraceSupported().
TryHandleWaitStatus()
bool NativeProcessLinux::TryHandleWaitStatus (lldb::pid_t pid, WaitStatus status) private
Definition at line 545 of file NativeProcessLinux.cpp.
References lldb_private::WaitStatus::Exit, lldb_private::NativeProcessProtocol::GetID(), GetThreadByID(), MonitorCallback(), lldb_private::NativeProcessProtocol::SetExitStatus(), lldb_private::WaitStatus::Signal, and lldb_private::WaitStatus::type.
Referenced by lldb_private::process_linux::NativeProcessLinux::Manager::SigchldHandler().
UpdateThreads()
size_t NativeProcessLinux::UpdateThreads () override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 1582 of file NativeProcessLinux.cpp.
References lldb_private::NativeProcessProtocol::m_threads.
WriteMemory()
Status NativeProcessLinux::WriteMemory (lldb::addr_t addr, const void * buf, size_t size, size_t & bytes_written) override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 1678 of file NativeProcessLinux.cpp.
References error(), lldb_private::NativeProcessProtocol::GetCurrentThreadID(), lldb_private::GetLog(), k_ptrace_word_size, LLDB_LOG, lldb_private::Memory, PtraceWrapper(), ReadMemory(), and WriteMemory().
Referenced by Syscall(), and WriteMemory().
WriteMemoryTags()
Status NativeProcessLinux::WriteMemoryTags (int32_t type, lldb::addr_t addr, size_t len, const std::vector< uint8_t > & tags) override virtual
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 1512 of file NativeProcessLinux.cpp.
References error(), lldb_private::Status::FromError(), GetCurrentThread(), lldb_private::NativeProcessProtocol::GetCurrentThreadID(), lldb_private::process_linux::NativeRegisterContextLinux::GetMemoryTaggingDetails(), lldb_private::Range< B, S >::GetRangeBase(), lldb_private::process_linux::NativeThreadLinux::GetRegisterContext(), PtraceWrapper(), and lldb_private::Status.
Member Data Documentation
m_allocated_memory
llvm::DenseMap<lldb::addr_t, lldb::addr_t> lldb_private::process_linux::NativeProcessLinux::m_allocated_memory private
Inferior memory (allocated by us) and its size.
Definition at line 185 of file NativeProcessLinux.h.
Referenced by AllocateMemory(), and DeallocateMemory().
m_arch
ArchSpec lldb_private::process_linux::NativeProcessLinux::m_arch private
Definition at line 177 of file NativeProcessLinux.h.
Referenced by GetArchitecture(), MonitorClone(), NativeProcessLinux(), SupportHardwareSingleStepping(), and Syscall().
m_intel_pt_collector
IntelPTCollector lldb_private::process_linux::NativeProcessLinux::m_intel_pt_collector private
Manages Intel PT process and thread traces.
Definition at line 274 of file NativeProcessLinux.h.
Referenced by Detach(), NativeProcessLinux(), NotifyTracersOfNewThread(), NotifyTracersOfThreadDestroyed(), NotifyTracersProcessDidStop(), NotifyTracersProcessWillResume(), TraceGetBinaryData(), TraceGetState(), TraceStart(), and TraceStop().
m_manager
Manager& lldb_private::process_linux::NativeProcessLinux::m_manager private
Definition at line 176 of file NativeProcessLinux.h.
Referenced by MonitorClone(), NativeProcessLinux(), and ~NativeProcessLinux().
m_mem_region_cache
std::vector<std::pair<MemoryRegionInfo, FileSpec> > lldb_private::process_linux::NativeProcessLinux::m_mem_region_cache private
Definition at line 180 of file NativeProcessLinux.h.
Referenced by DoStopIDBumped(), GetFileLoadAddress(), GetLoadedModuleFileSpec(), GetMemoryRegionInfo(), PopulateMemoryRegionCache(), and Syscall().
m_pending_notification_tid
lldb::tid_t lldb_private::process_linux::NativeProcessLinux::m_pending_notification_tid = LLDB_INVALID_THREAD_ID private
Definition at line 182 of file NativeProcessLinux.h.
Referenced by MonitorSignal(), MonitorSIGTRAP(), ResumeThread(), SignalIfAllThreadsStopped(), StopRunningThreads(), and ThreadWasCreated().
m_supports_mem_region
LazyBool lldb_private::process_linux::NativeProcessLinux::m_supports_mem_region = eLazyBoolCalculate private
Definition at line 179 of file NativeProcessLinux.h.
Referenced by GetMemoryRegionInfo(), and PopulateMemoryRegionCache().
The documentation for this class was generated from the following files:
NativeProcessLinux.h
NativeProcessLinux.cpp