LLDB: CommandObjectMemoryWrite::OptionGroupWriteMemory Class Reference
CommandObjectMemoryWrite::OptionGroupWriteMemory Class Reference
Public Member Functions
OptionGroupWriteMemory ()=default
~OptionGroupWriteMemory () override=default
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext *execution_context) override
void OptionParsingStarting (ExecutionContext *execution_context) override
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Public Attributes
FileSpec m_infile
off_t m_infile_offset
Detailed Description
Definition at line 1152 of file CommandObjectMemory.cpp.
Constructor & Destructor Documentation
OptionGroupWriteMemory()
CommandObjectMemoryWrite::OptionGroupWriteMemory::OptionGroupWriteMemory () default
~OptionGroupWriteMemory()
CommandObjectMemoryWrite::OptionGroupWriteMemory::~OptionGroupWriteMemory () override default
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > CommandObjectMemoryWrite::OptionGroupWriteMemory::GetDefinitions () inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 1158 of file CommandObjectMemory.cpp.
OptionParsingStarting()
void CommandObjectMemoryWrite::OptionGroupWriteMemory::OptionParsingStarting (ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 1192 of file CommandObjectMemory.cpp.
References m_infile, and m_infile_offset.
SetOptionValue()
Status CommandObjectMemoryWrite::OptionGroupWriteMemory::SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 1162 of file CommandObjectMemory.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::FileSystem::Instance(), m_infile, m_infile_offset, and lldb_private::FileSystem::Resolve().
Member Data Documentation
m_infile
FileSpec CommandObjectMemoryWrite::OptionGroupWriteMemory::m_infile
Definition at line 1197 of file CommandObjectMemory.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_infile_offset
off_t CommandObjectMemoryWrite::OptionGroupWriteMemory::m_infile_offset
Definition at line 1198 of file CommandObjectMemory.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following file:
CommandObjectMemory.cpp