LLDB: lldb_private::ThreadPlanCallFunctionUsingABI Class Reference
lldb_private::ThreadPlanCallFunctionUsingABI Class Reference
#include <ThreadPlanCallFunctionUsingABI.h>
Public Member Functions
ThreadPlanCallFunctionUsingABI (Thread &thread, const Address &function_address, llvm::Type &function_prototype, llvm::Type &return_type, llvm::ArrayRef< ABI::CallArgument > args, const EvaluateExpressionOptions &options)
~ThreadPlanCallFunctionUsingABI () override
void GetDescription (Stream *s, lldb::DescriptionLevel level) override
Print a description of this thread to the stream s.
Public Member Functions inherited from lldb_private::ThreadPlanCallFunction
ThreadPlanCallFunction (Thread &thread, const Address &function, const CompilerType &return_type, llvm::ArrayRef< lldb::addr_t > args, const EvaluateExpressionOptions &options)
ThreadPlanCallFunction (Thread &thread, const Address &function, const EvaluateExpressionOptions &options)
~ThreadPlanCallFunction () override
bool ValidatePlan (Stream *error) override
Returns whether this plan could be successfully created.
bool ShouldStop (Event *event_ptr) override
Vote ShouldReportStop (Event *event_ptr) override
bool StopOthers () override
lldb::StateType GetPlanRunState () override
void DidPush () override
bool WillStop () override
bool MischiefManaged () override
lldb::ValueObjectSP GetReturnValueObject () override
lldb::addr_t GetFunctionStackPointer ()
void DidPop () override
virtual lldb::StopInfoSP GetRealStopInfo ()
lldb::addr_t GetStopAddress ()
void RestoreThreadState () override
void ThreadDestroyed () override
void SetStopOthers (bool new_value) override
Public Member Functions inherited from lldb_private::ThreadPlan
virtual ~ThreadPlan ()
const char * GetName () const
Returns the name of this thread plan.
Thread & GetThread ()
Returns the Thread that is using this thread plan.
Target & GetTarget ()
const Target & GetTarget () const
void ClearThreadCache ()
Clear the Thread* cache.
bool TracerExplainsStop ()
lldb::StateType RunState ()
bool PlanExplainsStop (Event *event_ptr)
virtual bool ShouldAutoContinue (Event *event_ptr)
Returns whether this thread plan overrides the ShouldStop of subsequently processed plans.
Vote ShouldReportRun (Event *event_ptr)
virtual bool SupportsResumeOthers ()
virtual bool ShouldRunBeforePublicStop ()
bool WillResume (lldb::StateType resume_state, bool current_plan)
bool IsControllingPlan ()
virtual bool IsLeafPlan ()
bool SetIsControllingPlan (bool value)
virtual bool OkayToDiscard ()
void SetOkayToDiscard (bool value)
bool GetPrivate ()
void SetPrivate (bool input)
ThreadPlanKind GetKind () const
bool IsPlanComplete ()
void SetPlanComplete (bool success=true)
virtual bool IsPlanStale ()
bool PlanSucceeded ()
virtual bool IsBasePlan ()
lldb::ThreadPlanTracerSP & GetThreadPlanTracer ()
void SetThreadPlanTracer (lldb::ThreadPlanTracerSP new_tracer_sp)
void DoTraceLog ()
virtual lldb::ExpressionVariableSP GetExpressionVariable ()
virtual bool IsVirtualStep ()
bool SetIterationCount (size_t count)
virtual lldb::RunDirection GetDirection () const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Protected Member Functions
void SetReturnValue () override
Protected Member Functions inherited from lldb_private::ThreadPlanCallFunction
void ReportRegisterState (const char *message)
bool DoPlanExplainsStop (Event *event_ptr) override
bool ConstructorSetup (Thread &thread, ABI *&abi, lldb::addr_t &start_load_addr, lldb::addr_t &function_load_addr)
virtual void DoTakedown (bool success)
void SetBreakpoints ()
void ClearBreakpoints ()
bool BreakpointsExplainStop ()
Protected Member Functions inherited from lldb_private::ThreadPlan
ThreadPlan (ThreadPlanKind kind, const char *name, Thread &thread, Vote report_stop_vote, Vote report_run_vote)
virtual bool DoWillResume (lldb::StateType resume_state, bool current_plan)
void PushPlan (lldb::ThreadPlanSP &thread_plan_sp)
ThreadPlan * GetPreviousPlan ()
lldb::StopInfoSP GetPrivateStopInfo ()
void SetStopInfo (lldb::StopInfoSP stop_reason_sp)
bool IsUsuallyUnexplainedStopReason (lldb::StopReason)
Private Member Functions
ThreadPlanCallFunctionUsingABI (const ThreadPlanCallFunctionUsingABI &)=delete
const ThreadPlanCallFunctionUsingABI & operator= (const ThreadPlanCallFunctionUsingABI &)=delete
Private Attributes
llvm::Type & m_return_type
Additional Inherited Members
Public Types inherited from lldb_private::ThreadPlan
enum ThreadPlanKind {
eKindGeneric , eKindNull , eKindBase , eKindCallFunction ,
eKindPython , eKindStepInstruction , eKindStepOut , eKindStepOverBreakpoint ,
eKindStepOverRange , eKindStepInRange , eKindRunToAddress , eKindStepThrough ,
eKindStepUntil , eKindSingleThreadTimeout
}
Protected Attributes inherited from lldb_private::ThreadPlanCallFunction
bool m_valid
bool m_stop_other_threads
bool m_unwind_on_error
bool m_ignore_breakpoints
bool m_debug_execution
bool m_trap_exceptions
Address m_function_addr
Address m_start_addr
lldb::addr_t m_function_sp
lldb::ThreadPlanSP m_subplan_sp
LanguageRuntime * m_cxx_language_runtime
LanguageRuntime * m_objc_language_runtime
Thread::ThreadStateCheckpoint m_stored_thread_state
lldb::StopInfoSP m_real_stop_info_sp
StreamString m_constructor_errors
lldb::ValueObjectSP m_return_valobj_sp
bool m_takedown_done
bool m_should_clear_objc_exception_bp
bool m_should_clear_cxx_exception_bp
lldb::addr_t m_stop_address
Protected Attributes inherited from lldb_private::ThreadPlan
Status m_status
Process & m_process
lldb::tid_t m_tid
Vote m_report_stop_vote
Vote m_report_run_vote
bool m_takes_iteration_count
bool m_could_not_resolve_hw_bp
int32_t m_iteration_count = 1
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Detailed Description
Definition at line 23 of file ThreadPlanCallFunctionUsingABI.h.
Constructor & Destructor Documentation
ThreadPlanCallFunctionUsingABI() [1/2]
ThreadPlanCallFunctionUsingABI::ThreadPlanCallFunctionUsingABI (Thread & thread, const Address & function_address, llvm::Type & function_prototype, llvm::Type & return_type, llvm::ArrayRef< ABI::CallArgument > args, const EvaluateExpressionOptions & options)
Definition at line 23 of file ThreadPlanCallFunctionUsingABI.cpp.
References lldb_private::ThreadPlanCallFunction::ConstructorSetup(), LLDB_INVALID_ADDRESS, lldb_private::ThreadPlanCallFunction::m_function_sp, m_return_type, lldb_private::ThreadPlanCallFunction::m_valid, lldb_private::ABI::PrepareTrivialCall(), lldb_private::ThreadPlanCallFunction::ReportRegisterState(), and lldb_private::ThreadPlanCallFunction::ThreadPlanCallFunction().
Referenced by operator=(), and ThreadPlanCallFunctionUsingABI().
~ThreadPlanCallFunctionUsingABI()
ThreadPlanCallFunctionUsingABI::~ThreadPlanCallFunctionUsingABI () override default
ThreadPlanCallFunctionUsingABI() [2/2]
lldb_private::ThreadPlanCallFunctionUsingABI::ThreadPlanCallFunctionUsingABI (const ThreadPlanCallFunctionUsingABI &) private delete
References ThreadPlanCallFunctionUsingABI().
Member Function Documentation
GetDescription()
void ThreadPlanCallFunctionUsingABI::GetDescription (Stream * s, lldb::DescriptionLevel level) override virtual
Print a description of this thread to the stream s.
thread. Don't expect that the result of GetThread is valid in the description method. This might get called when the underlying Thread has not been reported, so we only know the TID and not the thread.
Parameters
[in] s The stream to which to print the description.
[in] level The level of description desired. Note that eDescriptionLevelBrief will be used in the stop message printed when the plan is complete.
Reimplemented from lldb_private::ThreadPlanCallFunction.
Definition at line 47 of file ThreadPlanCallFunctionUsingABI.cpp.
References lldb::eDescriptionLevelBrief, lldb_private::ThreadPlan::GetTarget(), lldb_private::ThreadPlanCallFunction::m_function_addr, and lldb_private::Stream::Printf().
operator=()
const ThreadPlanCallFunctionUsingABI & lldb_private::ThreadPlanCallFunctionUsingABI::operator= (const ThreadPlanCallFunctionUsingABI &) private delete
References ThreadPlanCallFunctionUsingABI().
SetReturnValue()
void ThreadPlanCallFunctionUsingABI::SetReturnValue () override protected virtual
Reimplemented from lldb_private::ThreadPlanCallFunction.
Definition at line 57 of file ThreadPlanCallFunctionUsingABI.cpp.
References lldb_private::ABI::GetReturnValueObject(), lldb_private::ThreadPlan::GetThread(), lldb_private::ThreadPlan::m_process, m_return_type, and lldb_private::ThreadPlanCallFunction::m_return_valobj_sp.
Member Data Documentation
m_return_type
llvm::Type& lldb_private::ThreadPlanCallFunctionUsingABI::m_return_type private
Definition at line 46 of file ThreadPlanCallFunctionUsingABI.h.
Referenced by SetReturnValue(), and ThreadPlanCallFunctionUsingABI().
The documentation for this class was generated from the following files:
ThreadPlanCallFunctionUsingABI.h
ThreadPlanCallFunctionUsingABI.cpp