LLDB: lldb_private::Debugger Class Reference
lldb_private::Debugger Class Reference
A class to manage flag bits.
#include <Debugger.h>
Classes
struct DestroyCallbackInfo
class InterruptionReport
struct ProgressReport
Public Types
using DebuggerList = std::vector<lldb::DebuggerSP>
Public Member Functions
Broadcaster & GetBroadcaster ()
Get the public broadcaster for this debugger.
const Broadcaster & GetBroadcaster () const
~Debugger () override
void Clear ()
void DispatchClientTelemetry (const lldb_private::StructuredDataImpl &entry)
bool GetAsyncExecution ()
void SetAsyncExecution (bool async)
lldb::FileSP GetInputFileSP ()
File & GetInputFile ()
lldb::FileSP GetOutputFileSP ()
lldb::FileSP GetErrorFileSP ()
Status SetInputString (const char *data)
void SetInputFile (lldb::FileSP file)
void SetOutputFile (lldb::FileSP file)
void SetErrorFile (lldb::FileSP file)
void SaveInputTerminalState ()
void RestoreInputTerminalState ()
lldb::StreamUP GetAsyncOutputStream ()
lldb::StreamUP GetAsyncErrorStream ()
CommandInterpreter & GetCommandInterpreter ()
ScriptInterpreter * GetScriptInterpreter (bool can_create=true, std::optional< lldb::ScriptLanguage > language={})
lldb::ListenerSP GetListener ()
SourceManager & GetSourceManager ()
lldb::TargetSP GetSelectedTarget ()
ExecutionContext GetSelectedExecutionContext ()
Get the execution context representing the selected entities in the selected target.
ExecutionContextRef GetSelectedExecutionContextRef ()
Similar to GetSelectedExecutionContext but returns a ExecutionContextRef, and will hold the dummy target if no target is currently selected.
TargetList & GetTargetList ()
Get accessor for the target list.
PlatformList & GetPlatformList ()
void DispatchInputInterrupt ()
void DispatchInputEndOfFile ()
void AdoptTopIOHandlerFilesIfInvalid (lldb::FileSP &in, lldb::LockableStreamFileSP &out, lldb::LockableStreamFileSP &err)
void RunIOHandlerAsync (const lldb::IOHandlerSP &reader_sp, bool cancel_top_handler=true)
Run the given IO handler and return immediately.
void RunIOHandlerSync (const lldb::IOHandlerSP &reader_sp)
Run the given IO handler and block until it's complete.
bool RemoveIOHandler (const lldb::IOHandlerSP &reader_sp)
Remove the given IO handler if it's currently active.
bool IsTopIOHandler (const lldb::IOHandlerSP &reader_sp)
bool CheckTopIOHandlerTypes (IOHandler::Type top_type, IOHandler::Type second_top_type)
void PrintAsync (const char *s, size_t len, bool is_stdout)
llvm::StringRef GetTopIOHandlerControlSequence (char ch)
const char * GetIOHandlerCommandPrefix ()
const char * GetIOHandlerHelpPrologue ()
void RefreshIOHandler ()
void ClearIOHandlers ()
bool EnableLog (llvm::StringRef channel, llvm::ArrayRef< const char * > categories, llvm::StringRef log_file, uint32_t log_options, size_t buffer_size, LogHandlerKind log_handler_kind, llvm::raw_ostream &error_stream)
void SetLoggingCallback (lldb::LogOutputCallback log_callback, void *baton)
Status SetPropertyValue (const ExecutionContext *exe_ctx, VarSetOperationType op, llvm::StringRef property_path, llvm::StringRef value) override
bool GetAutoConfirm () const
FormatEntity::Entry GetDisassemblyFormat () const
FormatEntity::Entry GetFrameFormat () const
FormatEntity::Entry GetFrameFormatUnique () const
uint64_t GetStopDisassemblyMaxSize () const
FormatEntity::Entry GetThreadFormat () const
FormatEntity::Entry GetThreadStopFormat () const
lldb::ScriptLanguage GetScriptLanguage () const
bool SetScriptLanguage (lldb::ScriptLanguage script_lang)
lldb::LanguageType GetREPLLanguage () const
bool SetREPLLanguage (lldb::LanguageType repl_lang)
uint64_t GetTerminalWidth () const
bool SetTerminalWidth (uint64_t term_width)
uint64_t GetTerminalHeight () const
bool SetTerminalHeight (uint64_t term_height)
llvm::StringRef GetPrompt () const
llvm::StringRef GetPromptAnsiPrefix () const
llvm::StringRef GetPromptAnsiSuffix () const
void SetPrompt (llvm::StringRef p)
void SetPrompt (const char *)=delete
bool GetUseExternalEditor () const
bool SetUseExternalEditor (bool use_external_editor_p)
llvm::StringRef GetExternalEditor () const
bool SetExternalEditor (llvm::StringRef editor)
bool GetUseColor () const
bool SetUseColor (bool use_color)
bool GetShowProgress () const
bool SetShowProgress (bool show_progress)
bool GetShowStatusline () const
FormatEntity::Entry GetStatuslineFormat () const
bool SetStatuslineFormat (const FormatEntity::Entry &format)
llvm::StringRef GetSeparator () const
bool SetSeparator (llvm::StringRef s)
llvm::StringRef GetShowProgressAnsiPrefix () const
llvm::StringRef GetShowProgressAnsiSuffix () const
llvm::StringRef GetDisabledAnsiPrefix () const
llvm::StringRef GetDisabledAnsiSuffix () const
bool GetUseAutosuggestion () const
llvm::StringRef GetAutosuggestionAnsiPrefix () const
llvm::StringRef GetAutosuggestionAnsiSuffix () const
llvm::StringRef GetRegexMatchAnsiPrefix () const
llvm::StringRef GetRegexMatchAnsiSuffix () const
bool GetShowDontUsePoHint () const
bool GetUseSourceCache () const
bool SetUseSourceCache (bool use_source_cache)
bool GetMarkHiddenFrames () const
bool GetHighlightSource () const
lldb::StopShowColumn GetStopShowColumn () const
llvm::StringRef GetStopShowColumnAnsiPrefix () const
llvm::StringRef GetStopShowColumnAnsiSuffix () const
uint64_t GetStopSourceLineCount (bool before) const
lldb::StopDisassemblyType GetStopDisassemblyDisplay () const
uint64_t GetDisassemblyLineCount () const
llvm::StringRef GetStopShowLineMarkerAnsiPrefix () const
llvm::StringRef GetStopShowLineMarkerAnsiSuffix () const
bool GetAutoOneLineSummaries () const
bool GetAutoIndent () const
bool SetAutoIndent (bool b)
bool GetPrintDecls () const
bool SetPrintDecls (bool b)
uint64_t GetTabSize () const
bool SetTabSize (uint64_t tab_size)
lldb::DWIMPrintVerbosity GetDWIMPrintVerbosity () const
bool GetEscapeNonPrintables () const
bool GetNotifyVoid () const
const std::string & GetInstanceName () const
bool GetShowInlineDiagnostics () const
bool SetShowInlineDiagnostics (bool)
bool LoadPlugin (const FileSpec &spec, Status &error)
void RunIOHandlers ()
bool IsForwardingEvents ()
void EnableForwardEvents (const lldb::ListenerSP &listener_sp)
void CancelForwardEvents (const lldb::ListenerSP &listener_sp)
bool IsHandlingEvents () const
Status RunREPL (lldb::LanguageType language, const char *repl_options)
void RequestInterrupt ()
Interruption in LLDB:
void CancelInterruptRequest ()
Decrement the "interrupt requested" counter.
void RedrawStatusline (std::optional< ExecutionContextRef > exe_ctx_ref)
Redraw the statusline if enabled.
template<typename... Args>
bool InterruptRequested (const char *cur_func, const char *formatv, Args &&...args)
This is the correct way to query the state of Interruption.
bool InterruptRequested ()
void ReportInterruption (const InterruptionReport &report)
Target & GetSelectedOrDummyTarget (bool prefer_dummy=false)
Target & GetDummyTarget ()
lldb::BroadcasterManagerSP GetBroadcasterManager ()
void SetDestroyCallback (lldb_private::DebuggerDestroyCallback destroy_callback, void *baton)
DEPRECATED: We used to only support one Destroy callback.
lldb::callback_token_t AddDestroyCallback (lldb_private::DebuggerDestroyCallback destroy_callback, void *baton)
Add a callback for when the debugger is destroyed.
bool RemoveDestroyCallback (lldb::callback_token_t token)
Remove the specified callback. Return true if successful.
bool StartEventHandlerThread ()
Manually start the global event handler thread.
void StopEventHandlerThread ()
Manually stop the debugger's default event handler.
void FlushProcessOutput (Process &process, bool flush_stdout, bool flush_stderr)
Force flushing the process's pending stdout and stderr to the debugger's asynchronous stdout and stderr streams.
SourceManager::SourceFileCache & GetSourceFileCache ()
std::optional< ProgressReport > GetCurrentProgressReport () const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Public Member Functions inherited from lldb_private::Properties
Properties ()
Properties (const lldb::OptionValuePropertiesSP &collection_sp)
virtual ~Properties ()
lldb::OptionValuePropertiesSP GetValueProperties () const
virtual lldb::OptionValueSP GetPropertyValue (const ExecutionContext *exe_ctx, llvm::StringRef property_path, Status &error) const
virtual Status DumpPropertyValue (const ExecutionContext *exe_ctx, Stream &strm, llvm::StringRef property_path, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllPropertyValues (const ExecutionContext *exe_ctx, Stream &strm, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllDescriptions (CommandInterpreter &interpreter, Stream &strm) const
size_t Apropos (llvm::StringRef keyword, std::vector< const Property * > &matching_properties) const
template<typename T>
T GetPropertyAtIndexAs (uint32_t idx, T default_value, const ExecutionContext *exe_ctx=nullptr) const
template<typename T, typename U = typename std::remove_pointer<T>::type, std::enable_if_t< std::is_pointer_v< T >, bool > = true>
const U * GetPropertyAtIndexAs (uint32_t idx, const ExecutionContext *exe_ctx=nullptr) const
template<typename T>
bool SetPropertyAtIndex (uint32_t idx, T t, const ExecutionContext *exe_ctx=nullptr) const
Static Public Member Functions
static llvm::StringRef GetStaticBroadcasterClass ()
static lldb::DebuggerSP CreateInstance (lldb::LogOutputCallback log_callback=nullptr, void *baton=nullptr)
static lldb::TargetSP FindTargetWithProcessID (lldb::pid_t pid)
static lldb::TargetSP FindTargetWithProcess (Process *process)
static void Initialize (LoadPluginCallbackType load_plugin_callback)
static void Terminate ()
static void SettingsInitialize ()
static void SettingsTerminate ()
static void Destroy (lldb::DebuggerSP &debugger_sp)
static StructuredData::DictionarySP GetBuildConfiguration ()
Get the build configuration as structured data.
static lldb::DebuggerSP FindDebuggerWithID (lldb::user_id_t id)
static lldb::DebuggerSP FindDebuggerWithInstanceName (llvm::StringRef instance_name)
static size_t GetNumDebuggers ()
static lldb::DebuggerSP GetDebuggerAtIndex (size_t index)
static bool FormatDisassemblerAddress (const FormatEntity::Entry *format, const SymbolContext *sc, const SymbolContext *prev_sc, const ExecutionContext *exe_ctx, const Address *addr, Stream &s)
static void AssertCallback (llvm::StringRef message, llvm::StringRef backtrace, llvm::StringRef prompt)
static DebuggerList DebuggersRequestingInterruption ()
static llvm::ThreadPoolInterface & GetThreadPool ()
Shared thread pool. Use only with ThreadPoolTaskGroup.
static void ReportWarning (std::string message, std::optional< lldb::user_id_t > debugger_id=std::nullopt, std::once_flag *once=nullptr)
Report warning events.
static void ReportError (std::string message, std::optional< lldb::user_id_t > debugger_id=std::nullopt, std::once_flag *once=nullptr)
Report error events.
static void ReportInfo (std::string message, std::optional< lldb::user_id_t > debugger_id=std::nullopt, std::once_flag *once=nullptr)
Report info events.
static void ReportSymbolChange (const ModuleSpec &module_spec)
Static Public Member Functions inherited from lldb_private::Properties
static llvm::StringRef GetExperimentalSettingsName ()
static bool IsSettingExperimental (llvm::StringRef setting)
Protected Types
enum { eBroadcastBitEventThreadIsListening = (1 << 0) }
typedef std::vector< llvm::sys::DynamicLibrary > LoadedPluginsList
Protected Member Functions
void HandleDestroyCallback ()
void PrintProgress (const ProgressEventData &data)
bool IsEscapeCodeCapableTTY ()
bool StatuslineSupported ()
void PushIOHandler (const lldb::IOHandlerSP &reader_sp, bool cancel_top_handler=true)
bool PopIOHandler (const lldb::IOHandlerSP &reader_sp)
bool HasIOHandlerThread () const
bool StartIOHandlerThread ()
void StopIOHandlerThread ()
HostThread SetIOHandlerThread (HostThread &new_thread)
void JoinIOHandlerThread ()
bool IsIOHandlerThreadCurrentThread () const
lldb::thread_result_t IOHandlerThread ()
lldb::thread_result_t DefaultEventHandler ()
void HandleBreakpointEvent (const lldb::EventSP &event_sp)
lldb::ProcessSP HandleProcessEvent (const lldb::EventSP &event_sp)
lldb::ThreadSP HandleThreadEvent (const lldb::EventSP &event_sp)
void HandleProgressEvent (const lldb::EventSP &event_sp)
void HandleDiagnosticEvent (const lldb::EventSP &event_sp)
void InstanceInitialize ()
lldb::LockableStreamFileSP GetOutputStreamSP ()
Except for Debugger and IOHandler, GetOutputStreamSP and GetErrorStreamSP should not be used directly.
lldb::LockableStreamFileSP GetErrorStreamSP ()
Static Protected Member Functions
static void ReportProgress (uint64_t progress_id, std::string title, std::string details, uint64_t completed, uint64_t total, std::optional< lldb::user_id_t > debugger_id, uint32_t progress_category_bit=lldb::eBroadcastBitProgress)
Report progress events.
static void ReportDiagnosticImpl (lldb::Severity severity, std::string message, std::optional< lldb::user_id_t > debugger_id, std::once_flag *once)
Protected Attributes
std::mutex m_output_flush_mutex
lldb::FileSP m_input_file_sp
lldb::LockableStreamFileSP m_output_stream_sp
lldb::LockableStreamFileSP m_error_stream_sp
LockableStreamFile::Mutex m_output_mutex
lldb::BroadcasterManagerSP m_broadcaster_manager_sp
TerminalState m_terminal_state
TargetList m_target_list
PlatformList m_platform_list
lldb::ListenerSP m_listener_sp
std::unique_ptr< SourceManager > m_source_manager_up
SourceManager::SourceFileCache m_source_file_cache
std::unique_ptr< CommandInterpreter > m_command_interpreter_up
std::recursive_mutex m_script_interpreter_mutex
std::array< lldb::ScriptInterpreterSP, lldb::eScriptLanguageUnknown > m_script_interpreters
IOHandlerStack m_io_handler_stack
std::recursive_mutex m_io_handler_synchronous_mutex
std::mutex m_statusline_mutex
Mutex protecting the m_statusline member.
std::optional< Statusline > m_statusline
llvm::StringMap< std::weak_ptr< LogHandler > > m_stream_handlers
std::shared_ptr< CallbackLogHandler > m_callback_handler_sp
const std::string m_instance_name
LoadedPluginsList m_loaded_plugins
HostThread m_event_handler_thread
HostThread m_io_handler_thread
Broadcaster m_sync_broadcaster
Private debugger synchronization.
Broadcaster m_broadcaster
Public Debugger event broadcaster.
lldb::ListenerSP m_forward_listener_sp
llvm::once_flag m_clear_once
lldb::TargetSP m_dummy_target_sp
Diagnostics::CallbackID m_diagnostics_callback_id
std::mutex m_destroy_callback_mutex
lldb::callback_token_t m_destroy_callback_next_token = 0
llvm::SmallVector< DestroyCallbackInfo, 2 > m_destroy_callbacks
uint32_t m_interrupt_requested = 0
Tracks interrupt requests.
std::mutex m_interrupt_mutex
llvm::SmallVector< ProgressReport, 4 > m_progress_reports
Bookkeeping for command line progress events.
std::mutex m_progress_reports_mutex
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Protected Attributes inherited from lldb_private::Properties
lldb::OptionValuePropertiesSP m_collection_sp
Static Protected Attributes
static LoadPluginCallbackType g_load_plugin_callback = nullptr
Private Member Functions
Debugger (lldb::LogOutputCallback m_log_callback, void *baton)
Debugger (const Debugger &)=delete
const Debugger & operator= (const Debugger &)=delete
Friends
class CommandInterpreter
class REPL
class Progress
class ProgressManager
class Statusline
Detailed Description
A class to manage flag bits.
Provides a global root objects for the debugger core.
Definition at line 85 of file Debugger.h.
Member Typedef Documentation
DebuggerList
using lldb_private::Debugger::DebuggerList = std::vector<lldb::DebuggerSP>
Definition at line 89 of file Debugger.h.
LoadedPluginsList
typedef std::vector<llvm::sys::DynamicLibrary> lldb_private::Debugger::LoadedPluginsList protected
Definition at line 781 of file Debugger.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
eBroadcastBitEventThreadIsListening
Definition at line 816 of file Debugger.h.
Constructor & Destructor Documentation
~Debugger()
Debugger::~Debugger () override
Definition at line 1112 of file Debugger.cpp.
References Clear().
Debugger() [1/2]
Debugger::Debugger (lldb::LogOutputCallback m_log_callback, void * baton) private
Definition at line 1002 of file Debugger.cpp.
References lldb_private::Diagnostics::AddCallback(), CommandInterpreter, lldb_private::FileSpec::CopyByAppendingPathComponent(), lldb_private::Diagnostics::Enabled(), g_unique_id, lldb_private::Target::GetDefaultArchitecture(), lldb_private::Language::GetGlobalLanguageProperties(), lldb_private::ModuleList::GetGlobalModuleListProperties(), lldb_private::Platform::GetGlobalPlatformProperties(), lldb_private::Target::GetGlobalProperties(), lldb_private::Platform::GetHostPlatform(), lldb_private::UserID::GetID(), GetOutputFileSP(), lldb_private::FileSpec::GetPath(), lldb_private::LanguageProperties::GetSettingName(), GetStaticBroadcasterClass(), lldb_private::Properties::GetValueProperties(), lldb_private::Diagnostics::Instance(), lldb_private::ArchSpec::IsValid(), m_broadcaster, m_broadcaster_manager_sp, m_callback_handler_sp, m_clear_once, lldb_private::Properties::m_collection_sp, m_command_interpreter_up, m_diagnostics_callback_id, m_dummy_target_sp, m_error_stream_sp, m_event_handler_thread, m_forward_listener_sp, m_input_file_sp, m_instance_name, m_io_handler_stack, m_io_handler_thread, m_listener_sp, m_loaded_plugins, m_output_mutex, m_output_stream_sp, m_platform_list, m_source_file_cache, m_source_manager_up, m_stream_handlers, m_sync_broadcaster, m_target_list, m_terminal_state, lldb_private::Properties::Properties(), lldb_private::OptionValueUInt64::SetMinimumValue(), SetSeparator(), SetUseColor(), lldb_private::Target, and lldb_private::UserID::UserID().
Referenced by CreateInstance(), Debugger(), and operator=().
Debugger() [2/2]
lldb_private::Debugger::Debugger (const Debugger &) private delete
References Debugger().
Member Function Documentation
AddDestroyCallback()
lldb::callback_token_t Debugger::AddDestroyCallback (lldb_private::DebuggerDestroyCallback destroy_callback, void * baton)
Add a callback for when the debugger is destroyed.
Return a token, which can be used to remove said callback. Multiple callbacks can be added by calling this function multiple times, and will be invoked in FIFO order.
Definition at line 1675 of file Debugger.cpp.
References m_destroy_callback_mutex, m_destroy_callback_next_token, and m_destroy_callbacks.
AdoptTopIOHandlerFilesIfInvalid()
void Debugger::AdoptTopIOHandlerFilesIfInvalid (lldb::FileSP & in, lldb::LockableStreamFileSP & out, lldb::LockableStreamFileSP & err)
Definition at line 1402 of file Debugger.cpp.
References lldb_private::File::eOpenOptionReadOnly, GetErrorStreamSP(), GetInputFileSP(), GetOutputStreamSP(), m_io_handler_stack, m_output_mutex, and lldb_private::NativeFile::Unowned.
Referenced by lldb_private::IOHandler::IOHandler(), and lldb_private::ScriptInterpreterIORedirect::ScriptInterpreterIORedirect().
AssertCallback()
void Debugger::AssertCallback (llvm::StringRef message, llvm::StringRef backtrace, llvm::StringRef prompt) static
Definition at line 1650 of file Debugger.cpp.
References lldb_private::GetVersion(), and ReportError().
Referenced by lldb_private::SystemInitializerFull::Initialize().
CancelForwardEvents()
void Debugger::CancelForwardEvents (const lldb::ListenerSP & listener_sp)
Definition at line 2106 of file Debugger.cpp.
References m_forward_listener_sp.
CancelInterruptRequest()
void Debugger::CancelInterruptRequest ()
Decrement the "interrupt requested" counter.
Definition at line 1523 of file Debugger.cpp.
References m_interrupt_mutex, and m_interrupt_requested.
CheckTopIOHandlerTypes()
bool Debugger::CheckTopIOHandlerTypes (IOHandler::Type top_type, IOHandler::Type second_top_type)
Definition at line 1366 of file Debugger.cpp.
References m_io_handler_stack.
Referenced by lldb_private::REPL::IOHandlerInputComplete().
Clear()
void Debugger::Clear ()
Definition at line 1114 of file Debugger.cpp.
References ClearIOHandlers(), lldb_private::File::Close(), lldb_private::telemetry::LLDBBaseTelemetryInfo::debugger, lldb_private::Diagnostics::Enabled(), GetInputFile(), lldb_private::Diagnostics::Instance(), lldb_private::telemetry::DebuggerInfo::is_exit_entry, m_broadcaster_manager_sp, m_clear_once, m_command_interpreter_up, m_diagnostics_callback_id, m_listener_sp, m_target_list, m_terminal_state, lldb_private::Diagnostics::RemoveCallback(), StopEventHandlerThread(), and StopIOHandlerThread().
Referenced by ~Debugger().
ClearIOHandlers()
void Debugger::ClearIOHandlers ()
Definition at line 1295 of file Debugger.cpp.
References m_io_handler_stack, and PopIOHandler().
Referenced by Clear(), and RunIOHandlers().
CreateInstance()
DebuggerSP Debugger::CreateInstance (lldb::LogOutputCallback log_callback = nullptr, void * baton = nullptr) static
Definition at line 878 of file Debugger.cpp.
References Debugger(), g_debugger_list_mutex_ptr, g_debugger_list_ptr, lldb_private::GetVersion(), and lldb_private::telemetry::DebuggerInfo::lldb_version.
Referenced by lldb::SBDebugger::Create().
DebuggersRequestingInterruption()
Debugger::DebuggerList Debugger::DebuggersRequestingInterruption () static
Definition at line 1556 of file Debugger.cpp.
References g_debugger_list_mutex_ptr, and g_debugger_list_ptr.
Referenced by DebuggersOwningModuleRequestingInterruption().
DefaultEventHandler()
lldb::thread_result_t Debugger::DefaultEventHandler () protected
Definition at line 2134 of file Debugger.cpp.
References CommandInterpreter, lldb_private::CommandInterpreter::eBroadcastBitAsynchronousErrorData, lldb_private::CommandInterpreter::eBroadcastBitAsynchronousOutputData, lldb_private::Target::eBroadcastBitBreakpointChanged, lldb::eBroadcastBitError, eBroadcastBitEventThreadIsListening, lldb::eBroadcastBitExternalProgress, lldb::eBroadcastBitProgress, lldb_private::CommandInterpreter::eBroadcastBitQuitCommandReceived, lldb_private::Thread::eBroadcastBitStackChanged, lldb_private::Process::eBroadcastBitStateChanged, lldb_private::Process::eBroadcastBitSTDERR, lldb_private::Process::eBroadcastBitSTDOUT, lldb_private::Process::eBroadcastBitStructuredData, lldb_private::Thread::eBroadcastBitThreadSelected, lldb::eBroadcastBitWarning, lldb::eBroadcastSymbolChange, GetAsyncErrorStream(), GetAsyncOutputStream(), lldb_private::Broadcaster::GetBroadcasterClass(), lldb_private::EventDataBytes::GetBytesFromEvent(), lldb_private::Breakpoint::BreakpointEventData::GetEventDataFromEvent(), GetListener(), GetSelectedExecutionContextRef(), lldb_private::Process::GetStaticBroadcasterClass(), lldb_private::Target::GetStaticBroadcasterClass(), lldb_private::Thread::GetStaticBroadcasterClass(), HandleBreakpointEvent(), HandleDiagnosticEvent(), HandleProcessEvent(), HandleProgressEvent(), HandleThreadEvent(), m_broadcaster, m_broadcaster_manager_sp, m_command_interpreter_up, m_forward_listener_sp, m_statusline, m_statusline_mutex, m_sync_broadcaster, RedrawStatusline(), RequiresFollowChildWorkaround(), and StatuslineSupported().
Referenced by StartEventHandlerThread().
Destroy()
void Debugger::Destroy (lldb::DebuggerSP & debugger_sp) static
Definition at line 922 of file Debugger.cpp.
References CommandInterpreter, g_debugger_list_mutex_ptr, g_debugger_list_ptr, lldb_private::CommandReturnObject::GetErrorString(), lldb_private::CommandReturnObject::GetOutputString(), lldb_private::CommandInterpreter::GetSaveSessionOnQuit(), lldb_private::CommandInterpreter::SaveTranscript(), and lldb_private::CommandReturnObject::Succeeded().
Referenced by lldb::SBDebugger::Destroy().
DispatchClientTelemetry()
void Debugger::DispatchClientTelemetry (const lldb_private::StructuredDataImpl & entry)
Definition at line 896 of file Debugger.cpp.
References lldb_private::telemetry::TelemetryManager::DispatchClientTelemetry(), and lldb_private::telemetry::TelemetryManager::GetInstance().
DispatchInputEndOfFile()
void Debugger::DispatchInputEndOfFile ()
Definition at line 1288 of file Debugger.cpp.
References m_io_handler_stack.
DispatchInputInterrupt()
void Debugger::DispatchInputInterrupt ()
Definition at line 1281 of file Debugger.cpp.
References m_io_handler_stack.
EnableForwardEvents()
void Debugger::EnableForwardEvents (const lldb::ListenerSP & listener_sp)
Definition at line 2102 of file Debugger.cpp.
References m_forward_listener_sp.
EnableLog()
bool Debugger::EnableLog (llvm::StringRef channel, llvm::ArrayRef< const char * > categories, llvm::StringRef log_file, uint32_t log_options, size_t buffer_size, LogHandlerKind log_handler_kind, llvm::raw_ostream & error_stream)
Definition at line 1858 of file Debugger.cpp.
References CreateLogHandler(), lldb_private::Log::EnableLogChannel(), lldb_private::File::eOpenOptionAppend, lldb_private::File::eOpenOptionCanCreate, lldb_private::File::eOpenOptionTruncate, lldb_private::File::eOpenOptionWriteOnly, GetOutputFileSP(), lldb_private::FileSystem::Instance(), LLDB_LOG_OPTION_APPEND, LLDB_LOG_OPTION_PREPEND_THREAD_NAME, LLDB_LOG_OPTION_PREPEND_TIMESTAMP, m_callback_handler_sp, m_stream_handlers, and lldb_private::FileSystem::Open().
Referenced by CommandObjectLogEnable::DoExecute().
FindDebuggerWithID()
DebuggerSP Debugger::FindDebuggerWithID (lldb::user_id_t id) static
Definition at line 1588 of file Debugger.cpp.
References g_debugger_list_mutex_ptr, and g_debugger_list_ptr.
Referenced by lldb_private::mcp::CommandTool::Call(), lldb::SBDebugger::FindDebuggerWithID(), lldb_private::mcp::DebuggerResourceProvider::ReadDebuggerResource(), lldb_private::mcp::DebuggerResourceProvider::ReadTargetResource(), ReportDiagnosticImpl(), and ReportProgress().
FindDebuggerWithInstanceName()
DebuggerSP Debugger::FindDebuggerWithInstanceName (llvm::StringRef instance_name) static
Definition at line 954 of file Debugger.cpp.
References g_debugger_list_mutex_ptr, and g_debugger_list_ptr.
Referenced by lldb::SBDebugger::GetInternalVariableValue(), and lldb::SBDebugger::SetInternalVariable().
FindTargetWithProcess()
TargetSP Debugger::FindTargetWithProcess (Process * process) static
Definition at line 983 of file Debugger.cpp.
References g_debugger_list_mutex_ptr, and g_debugger_list_ptr.
FindTargetWithProcessID()
TargetSP Debugger::FindTargetWithProcessID (lldb::pid_t pid) static
Definition at line 969 of file Debugger.cpp.
References g_debugger_list_mutex_ptr, and g_debugger_list_ptr.
Referenced by lldb_private::Process::SetProcessExitStatus().
FlushProcessOutput()
void Debugger::FlushProcessOutput (Process & process, bool flush_stdout, bool flush_stderr)
Force flushing the process's pending stdout and stderr to the debugger's asynchronous stdout and stderr streams.
Definition at line 1978 of file Debugger.cpp.
References error(), lldb_private::Stream::Flush(), GetAsyncErrorStream(), GetAsyncOutputStream(), lldb_private::Process::GetSTDERR(), lldb_private::Process::GetSTDOUT(), m_output_flush_mutex, and lldb_private::Stream::Write().
Referenced by HandleProcessEvent().
FormatDisassemblerAddress()
bool Debugger::FormatDisassemblerAddress (const FormatEntity::Entry * format, const SymbolContext * sc, const SymbolContext * prev_sc, const ExecutionContext * exe_ctx, const Address * addr, Stream & s) static
Definition at line 1604 of file Debugger.cpp.
References lldb_private::Symbol::Compare(), lldb_private::FormatEntity::Formatter::Format(), lldb_private::SymbolContext::function, lldb_private::Target::GetDebugger(), GetDisassemblyFormat(), lldb_private::Function::GetMangled(), lldb_private::Symbol::GetName(), lldb_private::ExecutionContext::GetTargetRef(), lldb_private::Symbol::GetType(), lldb_private::ExecutionContext::HasTargetScope(), lldb_private::FormatEntity::Parse(), and lldb_private::SymbolContext::symbol.
Referenced by lldb_private::Instruction::Dump(), and lldb_private::Disassembler::PrintInstructions().
GetAsyncErrorStream()
StreamUP Debugger::GetAsyncErrorStream ()
Definition at line 1513 of file Debugger.cpp.
References lldb_private::StreamAsynchronousIO::STDERR.
Referenced by lldb_private::ScriptInterpreterLua::BreakpointCallbackFunction(), lldb_private::BreakpointOptions::BreakpointOptionsCallbackFunction(), lldb_private::Process::CreateBreakpointSite(), DefaultEventHandler(), FlushProcessOutput(), HandleDiagnosticEvent(), HandleProcessEvent(), lldb_private::DynamicLoader::LoadBinaryWithUUIDAndAddress(), DynamicLoaderDarwinKernel::KextImageInfo::LoadImageUsingMemoryModule(), LoadScriptingResourceForModule(), PrivateReportDiagnostic(), SetPropertyValue(), and lldb_private::ScriptInterpreterLua::WatchpointCallbackFunction().
GetAsyncExecution()
bool Debugger::GetAsyncExecution ()
Definition at line 1156 of file Debugger.cpp.
References m_command_interpreter_up.
Referenced by CommandObjectProcessConnect::DoExecute(), CommandObjectProcessContinue::DoExecute(), lldb_private::CommandInterpreter::HandleCommandsFromFile(), lldb_private::Target::StopHookCommandLine::HandleStop(), lldb_private::StopInfoBreakpoint::PerformAction(), lldb_private::StopInfoWatchpoint::PerformAction(), and ResumeNewPlan().
GetAsyncOutputStream()
StreamUP Debugger::GetAsyncOutputStream ()
Definition at line 1508 of file Debugger.cpp.
References lldb_private::StreamAsynchronousIO::STDOUT.
Referenced by lldb_private::ClangUserExpression::AddArguments(), lldb_private::BreakpointOptions::BreakpointOptionsCallbackFunction(), DefaultEventHandler(), ProcessKDP::DoConnectRemote(), FlushProcessOutput(), HandleBreakpointEvent(), HandleProcessEvent(), HandleThreadEvent(), DynamicLoaderDarwinKernel::KextImageInfo::LoadImageUsingMemoryModule(), DynamicLoaderFreeBSDKernel::KModImageInfo::LoadImageUsingMemoryModule(), lldb_private::StopInfoWatchpoint::PerformAction(), ProcessFreeBSDKernelCore::PrintUnreadMessage(), and ObjectFileMachO::SaveCore().
GetAutoConfirm()
bool Debugger::GetAutoConfirm () const
Definition at line 324 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetAutoIndent()
bool Debugger::GetAutoIndent () const
Definition at line 691 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::REPL::GetIOHandler().
GetAutoOneLineSummaries()
bool Debugger::GetAutoOneLineSummaries () const
Definition at line 679 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetAutosuggestionAnsiPrefix()
llvm::StringRef Debugger::GetAutosuggestionAnsiPrefix () const
Definition at line 571 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::IOHandlerEditline::IOHandlerEditline().
GetAutosuggestionAnsiSuffix()
llvm::StringRef Debugger::GetAutosuggestionAnsiSuffix () const
Definition at line 577 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::IOHandlerEditline::IOHandlerEditline().
GetBroadcaster() [1/2]
Broadcaster & lldb_private::Debugger::GetBroadcaster () inline
Get the public broadcaster for this debugger.
Definition at line 94 of file Debugger.h.
References m_broadcaster.
Referenced by PrivateReportDiagnostic(), and PrivateReportProgress().
GetBroadcaster() [2/2]
const Broadcaster & lldb_private::Debugger::GetBroadcaster () const inline
Definition at line 95 of file Debugger.h.
References m_broadcaster.
GetBroadcasterManager()
lldb::BroadcasterManagerSP lldb_private::Debugger::GetBroadcasterManager () inline
Definition at line 522 of file Debugger.h.
References m_broadcaster_manager_sp.
Referenced by lldb::SBListener::StartListeningForEventClass(), and lldb::SBListener::StopListeningForEventClass().
GetBuildConfiguration()
StructuredData::DictionarySP Debugger::GetBuildConfiguration () static
Get the build configuration as structured data.
Definition at line 2504 of file Debugger.cpp.
References AddBoolConfigEntry(), AddLLVMTargets(), and lldb_private::XMLDocument::XMLEnabled().
Referenced by lldb_private::CommandObjectVersion::DoExecute(), and lldb::SBDebugger::GetBuildConfiguration().
GetCommandInterpreter()
CommandInterpreter & lldb_private::Debugger::GetCommandInterpreter () inline
Definition at line 173 of file Debugger.h.
References CommandInterpreter, and m_command_interpreter_up.
Referenced by lldb_private::BreakpointOptions::BreakpointOptionsCallbackFunction(), lldb_private::StructuredDataDarwinLog::DebuggerInitialize(), CommandObjectCommandsScriptAdd::DoExecute(), CommandObjectCommandsScriptImport::DoExecute(), CommandObjectCommandsSource::DoExecute(), CommandObjectPlatformProcessLaunch::DoExecute(), lldb_private::Target::StopHookCommandLine::HandleStop(), lldb_private::StructuredDataPlugin::InitializeBasePluginForDebugger(), InterruptRequested(), lldb_private::IOHandlerDelegate::IOHandlerComplete(), lldb_private::REPL::IOHandlerComplete(), lldb_private::REPL::IOHandlerInputComplete(), lldb_private::IOHandlerDelegate::IOHandlerSuggestion(), lldb_private::Target::Launch(), ProcessFreeBSDKernelCore::PrintUnreadMessage(), lldb_private::REPL::REPL(), lldb_private::REPL::RunLoop(), SetPrompt(), SetPropertyValue(), SetUseColor(), and StopEventHandlerThread().
GetCurrentProgressReport()
std::optional< Debugger::ProgressReport > Debugger::GetCurrentProgressReport () const
Definition at line 2364 of file Debugger.cpp.
References m_progress_reports, and m_progress_reports_mutex.
GetDebuggerAtIndex()
lldb::DebuggerSP Debugger::GetDebuggerAtIndex (size_t index) static
Definition at line 1576 of file Debugger.cpp.
References g_debugger_list_mutex_ptr, and g_debugger_list_ptr.
Referenced by lldb::SBTypeCategory::AddTypeSummary(), lldb::SBTypeCategory::AddTypeSynthetic(), lldb_private::mcp::CommandTool::Call(), lldb_private::mcp::DebuggerListTool::Call(), lldb_private::mcp::DebuggerResourceProvider::GetResources(), and lldb_private::CommandObjectQuit::ShouldAskForConfirmation().
GetDisabledAnsiPrefix()
llvm::StringRef Debugger::GetDisabledAnsiPrefix () const
Definition at line 546 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetDisabledAnsiSuffix()
llvm::StringRef Debugger::GetDisabledAnsiSuffix () const
Definition at line 552 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetDisassemblyFormat()
FormatEntity::Entry Debugger::GetDisassemblyFormat () const
Definition at line 330 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::InstructionList::Dump(), FormatDisassemblerAddress(), and lldb_private::Disassembler::PrintInstructions().
GetDisassemblyLineCount()
uint64_t Debugger::GetDisassemblyLineCount () const
Definition at line 673 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::StackFrame::GetStatus().
GetDummyTarget()
Target & lldb_private::Debugger::GetDummyTarget () inline
Definition at line 520 of file Debugger.h.
References m_dummy_target_sp.
Referenced by CommandObjectTargetFrameProviderList::DoExecute(), CommandObjectTargetFrameProviderRegister::DoExecute(), CommandObjectTargetFrameProviderRemove::DoExecute(), and GetSelectedOrDummyTarget().
GetDWIMPrintVerbosity()
lldb::DWIMPrintVerbosity Debugger::GetDWIMPrintVerbosity () const
Definition at line 724 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::CommandObjectDWIMPrint::DoExecute().
GetErrorFileSP()
lldb::FileSP lldb_private::Debugger::GetErrorFileSP () inline
Definition at line 153 of file Debugger.h.
References m_error_stream_sp.
Referenced by IOHandlerLuaInterpreter::IOHandlerLuaInterpreter(), and lldb_private::ScriptInterpreterIORedirect::ScriptInterpreterIORedirect().
GetErrorStreamSP()
lldb::LockableStreamFileSP lldb_private::Debugger::GetErrorStreamSP () inline protected
Definition at line 694 of file Debugger.h.
References m_error_stream_sp.
Referenced by AdoptTopIOHandlerFilesIfInvalid().
GetEscapeNonPrintables()
bool Debugger::GetEscapeNonPrintables () const
Definition at line 685 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetExternalEditor()
llvm::StringRef Debugger::GetExternalEditor () const
Definition at line 473 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Thread::GetStatus(), and lldb_private::Thread::SetSelectedFrameByIndexNoisily().
GetFrameFormat()
FormatEntity::Entry Debugger::GetFrameFormat () const
Definition at line 335 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::StackFrame::DumpUsingSettingsFormat().
GetFrameFormatUnique()
FormatEntity::Entry Debugger::GetFrameFormatUnique () const
Definition at line 340 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::StackFrame::DumpUsingSettingsFormat().
GetHighlightSource()
bool Debugger::GetHighlightSource () const
Definition at line 622 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetInputFile()
File & lldb_private::Debugger::GetInputFile () inline
Definition at line 147 of file Debugger.h.
References m_input_file_sp.
Referenced by Clear(), SaveInputTerminalState(), and StopIOHandlerThread().
GetInputFileSP()
lldb::FileSP lldb_private::Debugger::GetInputFileSP () inline
Definition at line 146 of file Debugger.h.
References m_input_file_sp.
Referenced by AdoptTopIOHandlerFilesIfInvalid(), lldb_private::CommandObjectGUI::DoExecute(), and lldb_private::ScriptInterpreterIORedirect::ScriptInterpreterIORedirect().
GetInstanceName()
const std::string & lldb_private::Debugger::GetInstanceName () const inline
Definition at line 390 of file Debugger.h.
References m_instance_name.
Referenced by lldb_private::mcp::DebuggerResourceProvider::GetDebuggerResource().
GetIOHandlerCommandPrefix()
const char * Debugger::GetIOHandlerCommandPrefix ()
Definition at line 1385 of file Debugger.cpp.
References m_io_handler_stack.
Referenced by lldb_private::CommandInterpreter::GetCommandPrefix().
GetIOHandlerHelpPrologue()
const char * Debugger::GetIOHandlerHelpPrologue ()
Definition at line 1389 of file Debugger.cpp.
References m_io_handler_stack.
GetListener()
lldb::ListenerSP lldb_private::Debugger::GetListener () inline
Definition at line 182 of file Debugger.h.
References m_listener_sp.
Referenced by lldb_private::Target::CreateProcess(), DefaultEventHandler(), lldb_private::Platform::DoConnectProcess(), and lldb_private::ProcessAttachInfo::GetListenerForProcess().
GetMarkHiddenFrames()
bool Debugger::GetMarkHiddenFrames () const
Definition at line 616 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Thread::GetStackFrameStatus(), and lldb_private::Thread::GetStatus().
GetNotifyVoid()
bool Debugger::GetNotifyVoid () const
Definition at line 351 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::REPL::IOHandlerInputComplete().
GetNumDebuggers()
size_t Debugger::GetNumDebuggers () static
Definition at line 1568 of file Debugger.cpp.
References g_debugger_list_mutex_ptr, and g_debugger_list_ptr.
Referenced by lldb::SBTypeCategory::AddTypeSummary(), lldb::SBTypeCategory::AddTypeSynthetic(), lldb_private::mcp::CommandTool::Call(), lldb_private::mcp::DebuggerListTool::Call(), lldb_private::mcp::DebuggerResourceProvider::GetResources(), and lldb_private::CommandObjectQuit::ShouldAskForConfirmation().
GetOutputFileSP()
lldb::FileSP lldb_private::Debugger::GetOutputFileSP () inline
Definition at line 149 of file Debugger.h.
References m_output_stream_sp.
Referenced by Debugger(), lldb_private::CommandObjectGUI::DoExecute(), EnableLog(), lldb_private::CommandInterpreter::HandleCommandsFromFile(), IOHandlerLuaInterpreter::IOHandlerLuaInterpreter(), and lldb_private::ScriptInterpreterIORedirect::ScriptInterpreterIORedirect().
GetOutputStreamSP()
lldb::LockableStreamFileSP lldb_private::Debugger::GetOutputStreamSP () inline protected
Except for Debugger and IOHandler, GetOutputStreamSP and GetErrorStreamSP should not be used directly.
Use GetAsyncOutputStream and GetAsyncErrorStream instead.
Definition at line 693 of file Debugger.h.
References m_output_stream_sp.
Referenced by AdoptTopIOHandlerFilesIfInvalid(), HandleProgressEvent(), and IsEscapeCodeCapableTTY().
GetPlatformList()
PlatformList & lldb_private::Debugger::GetPlatformList () inline
Definition at line 213 of file Debugger.h.
References m_platform_list.
Referenced by lldb_private::Target::Attach(), lldb_private::Process::CompleteAttach(), lldb_private::OptionGroupPlatform::CreatePlatformWithOptions(), CommandObjectPlatformProcessInfo::DoExecute(), CommandObjectPlatformProcessLaunch::DoExecute(), CommandObjectPlatformProcessList::DoExecute(), CommandObjectPlatformSelect::DoExecute(), CommandObjectPlatformStatus::DoExecute(), ObjectFileMachO::LoadCoreFileImages(), lldb_private::CommandCompletions::RemoteDiskDirectories(), and lldb_private::CommandCompletions::RemoteDiskFiles().
GetPrintDecls()
bool Debugger::GetPrintDecls () const
Definition at line 702 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::REPL::IOHandlerInputComplete().
GetPrompt()
llvm::StringRef Debugger::GetPrompt () const
Definition at line 357 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::CommandInterpreter::HandleCommandsFromFile(), SetPrompt(), SetPropertyValue(), and SetUseColor().
GetPromptAnsiPrefix()
llvm::StringRef Debugger::GetPromptAnsiPrefix () const
Definition at line 363 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetPromptAnsiSuffix()
llvm::StringRef Debugger::GetPromptAnsiSuffix () const
Definition at line 369 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetRegexMatchAnsiPrefix()
llvm::StringRef Debugger::GetRegexMatchAnsiPrefix () const
Definition at line 583 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by LookupSymbolInModule().
GetRegexMatchAnsiSuffix()
llvm::StringRef Debugger::GetRegexMatchAnsiSuffix () const
Definition at line 589 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by LookupSymbolInModule().
GetREPLLanguage()
lldb::LanguageType Debugger::GetREPLLanguage () const
Definition at line 408 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by RunREPL().
GetScriptInterpreter()
ScriptInterpreter * Debugger::GetScriptInterpreter (bool can_create = true, std::optional< lldb::ScriptLanguage > language = {})
Definition at line 1909 of file Debugger.cpp.
References lldb_private::PluginManager::GetScriptInterpreterForLanguage(), GetScriptLanguage(), m_script_interpreter_mutex, and m_script_interpreters.
Referenced by lldb_private::ScriptInterpreterLua::BreakpointCallbackFunction(), CommandObjectScriptingObjectParsed::CommandObjectScriptingObjectParsed(), lldb_private::BreakpointOptions::CreateFromStructuredData(), CommandObjectCommandsScriptAdd::DoExecute(), CommandObjectFrameRecognizerAdd::DoExecute(), CommandObjectPythonFunction::DoExecute(), CommandObjectScriptingObjectParsed::DoExecute(), CommandObjectScriptingObjectRaw::DoExecute(), CommandObjectScriptingRun::DoExecute(), CommandObjectTargetFrameProviderRegister::DoExecute(), CommandObjectScriptingObjectParsed::GetHelp(), CommandObjectScriptingObjectRaw::GetHelp(), CommandObjectPythonFunction::GetHelpLong(), CommandObjectScriptingObjectParsed::GetHelpLong(), CommandObjectScriptingObjectRaw::GetHelpLong(), GetPythonInterpreter(), CommandObjectScriptingObjectParsed::GetRepeatCommand(), CommandObjectScriptingObjectRaw::GetRepeatCommand(), CommandObjectScriptingObjectParsed::HandleArgumentCompletion(), CommandObjectScriptingObjectParsed::CommandOptions::HandleOptionArgumentCompletion(), CommandObjectCommandsScriptAdd::IOHandlerInputComplete(), CommandObjectTypeSummaryAdd::IOHandlerInputComplete(), CommandObjectTypeSynthAdd::IOHandlerInputComplete(), lldb_private::Module::LoadScriptingResourceInTarget(), LocateExecutableScriptingResourcesFromDSYM(), CommandObjectTypeFilterAdd::CommandOptions::OptionParsingStarting(), lldb_private::process_gdb_remote::ProcessGDBRemote::ParsePythonTargetDefinition(), RunScriptFormatKeyword(), and lldb_private::ScriptInterpreterLua::WatchpointCallbackFunction().
GetScriptLanguage()
lldb::ScriptLanguage Debugger::GetScriptLanguage () const
Definition at line 396 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by GetScriptInterpreter(), lldb_private::Module::LoadScriptingResourceInTarget(), and lldb_private::PlatformDarwin::LocateExecutableScriptingResources().
GetSelectedExecutionContext()
ExecutionContext Debugger::GetSelectedExecutionContext ()
Get the execution context representing the selected entities in the selected target.
Definition at line 1268 of file Debugger.cpp.
References GetSelectedTarget().
Referenced by RestoreInputTerminalState().
GetSelectedExecutionContextRef()
ExecutionContextRef Debugger::GetSelectedExecutionContextRef ()
Similar to GetSelectedExecutionContext but returns a ExecutionContextRef, and will hold the dummy target if no target is currently selected.
Definition at line 1274 of file Debugger.cpp.
References GetSelectedTarget(), and m_dummy_target_sp.
Referenced by DefaultEventHandler(), and SetPropertyValue().
GetSelectedOrDummyTarget()
Target & Debugger::GetSelectedOrDummyTarget (bool prefer_dummy = false)
Definition at line 2425 of file Debugger.cpp.
References GetDummyTarget(), and m_target_list.
GetSelectedTarget()
lldb::TargetSP lldb_private::Debugger::GetSelectedTarget () inline
Definition at line 190 of file Debugger.h.
References m_target_list.
Referenced by lldb_private::CommandCompletions::BreakpointNames(), lldb_private::CommandCompletions::Breakpoints(), CommandObjectPlatformProcessInfo::DoExecute(), CommandObjectPlatformProcessLaunch::DoExecute(), CommandObjectPlatformProcessList::DoExecute(), CommandObjectPlatformStatus::DoExecute(), CommandObjectProcessAttach::DoExecute(), CommandObjectProcessConnect::DoExecute(), CommandObjectProcessLaunch::DoExecute(), GetSelectedExecutionContext(), GetSelectedExecutionContextRef(), lldb_private::Options::HandleOptionArgumentCompletion(), lldb_private::CommandCompletions::Modules(), lldb_private::CommandCompletions::SourceFiles(), and lldb_private::CommandCompletions::Symbols().
GetSeparator()
llvm::StringRef Debugger::GetSeparator () const
Definition at line 540 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetShowDontUsePoHint()
bool Debugger::GetShowDontUsePoHint () const
Definition at line 595 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetShowInlineDiagnostics()
bool Debugger::GetShowInlineDiagnostics () const
Definition at line 731 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::CommandInterpreter::IOHandlerInputComplete().
GetShowProgress()
bool Debugger::GetShowProgress () const
Definition at line 499 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by HandleProgressEvent().
GetShowProgressAnsiPrefix()
llvm::StringRef Debugger::GetShowProgressAnsiPrefix () const
Definition at line 510 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetShowProgressAnsiSuffix()
llvm::StringRef Debugger::GetShowProgressAnsiSuffix () const
Definition at line 516 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetShowStatusline()
bool Debugger::GetShowStatusline () const
Definition at line 522 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by StatuslineSupported().
GetSourceFileCache()
SourceManager::SourceFileCache & lldb_private::Debugger::GetSourceFileCache () inline
Definition at line 627 of file Debugger.h.
References m_source_file_cache.
Referenced by CommandObjectSourceCacheClear::DoExecute(), and CommandObjectSourceCacheDump::DoExecute().
GetSourceManager()
SourceManager & Debugger::GetSourceManager ()
Definition at line 1925 of file Debugger.cpp.
References m_source_manager_up.
Referenced by lldb_private::Disassembler::PrintInstructions().
GetStaticBroadcasterClass()
llvm::StringRef Debugger::GetStaticBroadcasterClass () static
Definition at line 997 of file Debugger.cpp.
Referenced by Debugger(), and lldb::SBDebugger::GetBroadcasterClass().
GetStatuslineFormat()
FormatEntity::Entry Debugger::GetStatuslineFormat () const
Definition at line 528 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetStopDisassemblyDisplay()
lldb::StopDisassemblyType Debugger::GetStopDisassemblyDisplay () const
Definition at line 666 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::StackFrame::GetStatus().
GetStopDisassemblyMaxSize()
uint64_t Debugger::GetStopDisassemblyMaxSize () const
Definition at line 345 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetStopShowColumn()
StopShowColumn Debugger::GetStopShowColumn () const
Definition at line 628 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by CommandObjectSourceList::DoExecute().
GetStopShowColumnAnsiPrefix()
llvm::StringRef Debugger::GetStopShowColumnAnsiPrefix () const
Definition at line 635 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetStopShowColumnAnsiSuffix()
llvm::StringRef Debugger::GetStopShowColumnAnsiSuffix () const
Definition at line 641 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetStopShowLineMarkerAnsiPrefix()
llvm::StringRef Debugger::GetStopShowLineMarkerAnsiPrefix () const
Definition at line 647 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetStopShowLineMarkerAnsiSuffix()
llvm::StringRef Debugger::GetStopShowLineMarkerAnsiSuffix () const
Definition at line 653 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetStopSourceLineCount()
uint64_t Debugger::GetStopSourceLineCount (bool before) const
Definition at line 659 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::StackFrame::GetStatus().
GetTabSize()
uint64_t Debugger::GetTabSize () const
Definition at line 713 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::REPL::GetIOHandler(), and lldb_private::REPL::IOHandlerFixIndentation().
GetTargetList()
TargetList & lldb_private::Debugger::GetTargetList () inline
Get accessor for the target list.
The target list is part of the global debugger object. This the single debugger shared instance to control where targets get created and to allow for tracking and searching for targets based on certain criteria.
Returns
A global shared target list.
Definition at line 211 of file Debugger.h.
References m_target_list.
Referenced by lldb_private::platform_gdb_server::PlatformRemoteGDBServer::Attach(), lldb_private::PlatformWindows::Attach(), PlatformPOSIX::Attach(), lldb_private::Platform::DoConnectProcess(), CommandObjectProcessAttach::DoExecute(), CommandObjectTargetCreate::DoExecute(), CommandObjectTargetDelete::DoExecute(), CommandObjectTargetSelect::DoExecute(), lldb_private::Process::HandleProcessStateChangedEvent(), lldb_private::DebuggerStats::ResetStatistics(), and lldb_private::Target::SetLabel().
GetTerminalHeight()
uint64_t Debugger::GetTerminalHeight () const
Definition at line 440 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetTerminalWidth()
uint64_t Debugger::GetTerminalWidth () const
Definition at line 418 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::CommandObjectDisassemble::DoExecute().
GetThreadFormat()
FormatEntity::Entry Debugger::GetThreadFormat () const
Definition at line 386 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Thread::DumpUsingSettingsFormat().
GetThreadPool()
llvm::ThreadPoolInterface & Debugger::GetThreadPool () static
Shared thread pool. Use only with ThreadPoolTaskGroup.
Definition at line 2478 of file Debugger.cpp.
References g_thread_pool.
Referenced by lldb_private::SymbolLocator::DownloadSymbolFileAsync(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexImpl(), DynamicLoaderPOSIXDYLD::LoadAllCurrentModules(), lldb_private::DynamicLoaderDarwin::PreloadModulesFromImageInfos(), lldb_private::ModuleList::PreloadSymbols(), DynamicLoaderPOSIXDYLD::RefreshModules(), and lldb_private::Target::SetExecutableModule().
GetThreadStopFormat()
FormatEntity::Entry Debugger::GetThreadStopFormat () const
Definition at line 391 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Thread::DumpUsingSettingsFormat().
GetTopIOHandlerControlSequence()
llvm::StringRef Debugger::GetTopIOHandlerControlSequence (char ch)
Definition at line 1381 of file Debugger.cpp.
References m_io_handler_stack.
GetUseAutosuggestion()
bool Debugger::GetUseAutosuggestion () const
Definition at line 565 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::IOHandlerEditline::IOHandlerEditline().
GetUseColor()
bool Debugger::GetUseColor () const
Definition at line 484 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::BreakpointOptions::BreakpointOptionsCallbackFunction(), CompleteLineEntry(), lldb_private::CommandObjectDisassemble::DoExecute(), lldb_private::FormatEntity::Formatter::Format(), lldb_private::CommandInterpreter::GetLLDBCommandsFromIOHandler(), lldb_private::CommandInterpreter::GetPythonCommandsFromIOHandler(), lldb_private::CommandInterpreter::HandleCommandsFromFile(), lldb_private::Options::HandleOptionCompletion(), lldb_private::REPL::IOHandlerInputComplete(), LookupSymbolInModule(), sddarwinlog_private::RunEnableCommand(), SetPrompt(), and SetPropertyValue().
GetUseExternalEditor()
bool Debugger::GetUseExternalEditor () const
Definition at line 462 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Thread::GetStatus(), and lldb_private::Thread::SetSelectedFrameByIndexNoisily().
GetUseSourceCache()
bool Debugger::GetUseSourceCache () const
Definition at line 601 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by SetPropertyValue().
HandleBreakpointEvent()
void Debugger::HandleBreakpointEvent (const lldb::EventSP & event_sp) protected
Definition at line 1932 of file Debugger.cpp.
References GetAsyncOutputStream(), lldb_private::Breakpoint::BreakpointEventData::GetBreakpointEventTypeFromEvent(), lldb_private::Breakpoint::BreakpointEventData::GetBreakpointFromEvent(), and lldb_private::Breakpoint::BreakpointEventData::GetNumBreakpointLocationsFromEvent().
Referenced by DefaultEventHandler().
HandleDestroyCallback()
void Debugger::HandleDestroyCallback () protected
Definition at line 902 of file Debugger.cpp.
References lldb_private::Debugger::DestroyCallbackInfo::baton, lldb_private::Debugger::DestroyCallbackInfo::callback, lldb_private::UserID::GetID(), m_destroy_callback_mutex, and m_destroy_callbacks.
HandleDiagnosticEvent()
void Debugger::HandleDiagnosticEvent (const lldb::EventSP & event_sp) protected
Definition at line 2371 of file Debugger.cpp.
References GetAsyncErrorStream(), and lldb_private::DiagnosticEventData::GetEventDataFromEvent().
Referenced by DefaultEventHandler().
HandleProcessEvent()
ProcessSP Debugger::HandleProcessEvent (const lldb::EventSP & event_sp) protected
Definition at line 1998 of file Debugger.cpp.
References lldb_private::Process::eBroadcastBitStateChanged, lldb_private::Process::eBroadcastBitSTDERR, lldb_private::Process::eBroadcastBitSTDOUT, lldb_private::Process::eBroadcastBitStructuredData, error(), lldb_private::StreamString::Flush(), FlushProcessOutput(), GetAsyncErrorStream(), GetAsyncOutputStream(), lldb_private::EventDataStructuredData::GetObjectFromEvent(), lldb_private::EventDataStructuredData::GetPluginFromEvent(), lldb_private::EventDataStructuredData::GetProcessFromEvent(), lldb_private::Process::ProcessEventData::GetProcessFromEvent(), lldb_private::Process::ProcessEventData::GetStateFromEvent(), lldb_private::StreamString::GetString(), lldb_private::Process::HandleProcessStateChangedEvent(), IsForwardingEvents(), lldb_private::Stream::PutChar(), SelectMostRelevantFrame, and lldb_private::StateIsStoppedState().
Referenced by DefaultEventHandler().
HandleProgressEvent()
void Debugger::HandleProgressEvent (const lldb::EventSP & event_sp) protected
Definition at line 2310 of file Debugger.cpp.
References lldb_private::Debugger::ProgressReport::completed, lldb_private::ProgressEventData::GetEventDataFromEvent(), GetOutputStreamSP(), GetShowProgress(), lldb_private::Debugger::ProgressReport::id, IsEscapeCodeCapableTTY(), m_progress_reports, m_progress_reports_mutex, OSC_PROGRESS_INDETERMINATE, OSC_PROGRESS_REMOVE, OSC_PROGRESS_SHOW, lldb_private::Debugger::ProgressReport::total, and UINT64_MAX.
Referenced by DefaultEventHandler().
HandleThreadEvent()
ThreadSP Debugger::HandleThreadEvent (const lldb::EventSP & event_sp) protected
Definition at line 2083 of file Debugger.cpp.
References lldb_private::Thread::eBroadcastBitStackChanged, lldb_private::Thread::eBroadcastBitThreadSelected, GetAsyncOutputStream(), and lldb_private::Thread::ThreadEventData::GetThreadFromEvent().
Referenced by DefaultEventHandler().
HasIOHandlerThread()
bool Debugger::HasIOHandlerThread () const protected
Definition at line 2379 of file Debugger.cpp.
References m_io_handler_thread.
Referenced by IsIOHandlerThreadCurrentThread(), JoinIOHandlerThread(), and lldb_private::REPL::RunLoop().
Initialize()
void Debugger::Initialize (LoadPluginCallbackType load_plugin_callback) static
Definition at line 751 of file Debugger.cpp.
References g_debugger_list_mutex_ptr, g_debugger_list_ptr, g_load_plugin_callback, and g_thread_pool.
Referenced by lldb_private::SystemInitializerFull::Initialize().
InstanceInitialize()
void Debugger::InstanceInitialize () protected
Definition at line 852 of file Debugger.cpp.
References lldb_private::PluginManager::DebuggerInitialize(), lldb_private::FileSystem::EnumerateDirectory(), lldb_private::FileSystem::Instance(), LoadPluginCallback(), and PATH_MAX.
InterruptRequested() [1/2]
bool Debugger::InterruptRequested ()
Definition at line 1529 of file Debugger.cpp.
References GetCommandInterpreter(), IsIOHandlerThreadCurrentThread(), m_interrupt_mutex, m_interrupt_requested, and lldb_private::CommandInterpreter::WasInterrupted().
Referenced by InterruptRequested().
InterruptRequested() [2/2]
template<typename... Args> bool lldb_private::Debugger::InterruptRequested (const char * cur_func, const char * formatv, Args &&... args) inline
This is the correct way to query the state of Interruption.
If you are on the RunCommandInterpreter thread, it will check the command interpreter state, and if it is on another thread it will check the debugger Interrupt Request state.
Parameters
[in] cur_func For reporting if the interruption was requested. Don't provide this by hand, use INTERRUPT_REQUESTED so this gets done consistently.
[in] formatv A formatv string for the interrupt message. If the elements of the message are expensive to compute, you can use the no-argument form of InterruptRequested, then make up the report using REPORT_INTERRUPTION.
Returns
A boolean value, if true an interruptible operation should interrupt itself.
Definition at line 461 of file Debugger.h.
References InterruptRequested(), and ReportInterruption().
IOHandlerThread()
lldb::thread_result_t Debugger::IOHandlerThread () protected
Definition at line 2304 of file Debugger.cpp.
References RunIOHandlers(), and StopEventHandlerThread().
Referenced by StartIOHandlerThread().
IsEscapeCodeCapableTTY()
bool Debugger::IsEscapeCodeCapableTTY () protected
Definition at line 2110 of file Debugger.cpp.
References lldb_private::File::GetIsInteractive(), lldb_private::File::GetIsRealTerminal(), lldb_private::File::GetIsTerminalWithColors(), and GetOutputStreamSP().
Referenced by HandleProgressEvent(), and StatuslineSupported().
IsForwardingEvents()
bool Debugger::IsForwardingEvents ()
Definition at line 2100 of file Debugger.cpp.
References m_forward_listener_sp.
Referenced by HandleProcessEvent().
IsHandlingEvents()
bool lldb_private::Debugger::IsHandlingEvents () const inline
Definition at line 406 of file Debugger.h.
References m_event_handler_thread.
IsIOHandlerThreadCurrentThread()
bool Debugger::IsIOHandlerThreadCurrentThread () const protected
Definition at line 2419 of file Debugger.cpp.
References lldb_private::Host::GetCurrentThread(), HasIOHandlerThread(), and m_io_handler_thread.
Referenced by InterruptRequested().
IsTopIOHandler()
bool Debugger::IsTopIOHandler (const lldb::IOHandlerSP & reader_sp)
Definition at line 1362 of file Debugger.cpp.
References m_io_handler_stack.
Referenced by lldb_private::Process::ProcessIOHandlerIsActive().
JoinIOHandlerThread()
void Debugger::JoinIOHandlerThread () protected
Definition at line 2411 of file Debugger.cpp.
References HasIOHandlerThread(), LLDB_INVALID_HOST_THREAD, and m_io_handler_thread.
Referenced by lldb_private::REPL::RunLoop().
LoadPlugin()
bool Debugger::LoadPlugin (const FileSpec & spec, Status & error)
Definition at line 790 of file Debugger.cpp.
References error(), lldb_private::Status::FromErrorString(), g_load_plugin_callback, and m_loaded_plugins.
Referenced by LoadPluginCallback().
operator=()
const Debugger & lldb_private::Debugger::operator= (const Debugger &) private delete
References Debugger().
PopIOHandler()
bool Debugger::PopIOHandler (const lldb::IOHandlerSP & reader_sp) protected
Definition at line 1474 of file Debugger.cpp.
References m_io_handler_stack.
Referenced by ClearIOHandlers(), RemoveIOHandler(), RunIOHandlers(), and RunIOHandlerSync().
PrintAsync()
void Debugger::PrintAsync (const char * s, size_t len, bool is_stdout)
Definition at line 1371 of file Debugger.cpp.
References m_error_stream_sp, m_io_handler_stack, m_output_stream_sp, and lldb_private::Stream::Write().
PrintProgress()
void lldb_private::Debugger::PrintProgress (const ProgressEventData & data) protected
PushIOHandler()
void Debugger::PushIOHandler (const lldb::IOHandlerSP & reader_sp, bool cancel_top_handler = true) protected
Definition at line 1447 of file Debugger.cpp.
References m_io_handler_stack.
Referenced by RunIOHandlerAsync(), and RunIOHandlerSync().
RedrawStatusline()
void Debugger::RedrawStatusline (std::optional< ExecutionContextRef > exe_ctx_ref)
Redraw the statusline if enabled.
Definition at line 1258 of file Debugger.cpp.
References m_statusline, and m_statusline_mutex.
Referenced by DefaultEventHandler(), SetPropertyValue(), SetSeparator(), and SetStatuslineFormat().
RefreshIOHandler()
void Debugger::RefreshIOHandler ()
Definition at line 1501 of file Debugger.cpp.
References m_io_handler_stack.
RemoveDestroyCallback()
bool Debugger::RemoveDestroyCallback (lldb::callback_token_t token)
Remove the specified callback. Return true if successful.
Definition at line 1683 of file Debugger.cpp.
References m_destroy_callback_mutex, and m_destroy_callbacks.
RemoveIOHandler()
bool Debugger::RemoveIOHandler (const lldb::IOHandlerSP & reader_sp)
Remove the given IO handler if it's currently active.
Definition at line 1393 of file Debugger.cpp.
References PopIOHandler().
Referenced by lldb_private::Process::PopProcessIOHandler().
ReportDiagnosticImpl()
void Debugger::ReportDiagnosticImpl (lldb::Severity severity, std::string message, std::optional< lldb::user_id_t > debugger_id, std::once_flag * once) static protected
Definition at line 1771 of file Debugger.cpp.
References lldb_private::Diagnostics::Enabled(), lldb::eSeverityInfo, FindDebuggerWithID(), g_debugger_list_mutex_ptr, g_debugger_list_ptr, lldb_private::Diagnostics::Instance(), PrivateReportDiagnostic(), lldb_private::Diagnostics::Report(), and lldb_private::Host::SystemLog().
Referenced by ReportError(), ReportInfo(), and ReportWarning().
ReportError()
void Debugger::ReportError (std::string message, std::optional< lldb::user_id_t > debugger_id = std::nullopt, std::once_flag * once = nullptr) static
Report error events.
Error events will be delivered to any debuggers that have listeners for the eBroadcastBitError.
Parameters
[in] message The error message to be reported.
[in] debugger_id If this optional parameter has a value, it indicates the unique debugger identifier that this diagnostic should be delivered to. If this optional parameter does not have a value, the diagnostic event will be delivered to all debuggers.
[in] once If a pointer is passed to a std::once_flag, then it will be used to ensure the given error is only broadcast once.
Definition at line 1818 of file Debugger.cpp.
References lldb::eSeverityError, and ReportDiagnosticImpl().
Referenced by AssertCallback(), lldb_private::process_gdb_remote::ProcessGDBRemote::BuildDynamicRegisterInfo(), lldb_private::TargetProperties::CheckJITObjectsDir(), lldb_private::StructuredDataDarwinLog::EnableNow(), lldb_private::Function::GetBlock(), lldb_private::DWARFCallFrameInfo::GetFDEIndex(), lldb_private::Options::GetLongOptions(), lldb_private::PlatformMacOSX::GetSDKDirectory(), MachSymtabSectionInfo::GetSection(), GetXcodeSDKDir(), lldb_private::DWARFCallFrameInfo::ParseCIE(), ObjectFileMachO::ParseSymtab(), lldb_private::StopInfoBreakpoint::PerformAction(), lldb_private::StopInfoWatchpoint::PerformAction(), lldb_private::Module::RegisterXcodeSDK(), lldb_private::Module::ReportError(), lldb_private::Module::ReportErrorIfModifyDetected(), and lldb_private::CompactUnwindInfo::ScanIndex().
ReportInfo()
void Debugger::ReportInfo (std::string message, std::optional< lldb::user_id_t > debugger_id = std::nullopt, std::once_flag * once = nullptr) static
Report info events.
Unlike warning and error events, info events are not broadcast but are logged for diagnostic purposes.
Parameters
[in] message The info message to be reported.
[in] debugger_id If this optional parameter has a value, it indicates this diagnostic is associated with a unique debugger instance.
[in] once If a pointer is passed to a std::once_flag, then it will be used to ensure the given info is only logged once.
Definition at line 1824 of file Debugger.cpp.
References lldb::eSeverityInfo, and ReportDiagnosticImpl().
ReportInterruption()
void Debugger::ReportInterruption (const InterruptionReport & report)
Definition at line 1550 of file Debugger.cpp.
References lldb_private::GetLog(), lldb_private::Host, LLDB_LOG, and lldb_private::Debugger::InterruptionReport::m_description.
Referenced by InterruptRequested().
ReportProgress()
void Debugger::ReportProgress (uint64_t progress_id, std::string title, std::string details, uint64_t completed, uint64_t total, std::optional< lldb::user_id_t > debugger_id, uint32_t progress_category_bit = lldb::eBroadcastBitProgress) static protected
Report progress events.
Progress events will be delivered to any debuggers that have listeners for the eBroadcastBitProgress. This function is called by the lldb_private::Progress class to deliver the events to any debuggers that qualify.
Parameters
[in] progress_id The unique integer identifier for the progress to report.
[in] message The title of the progress dialog to display in the UI.
[in] completed The amount of work completed. If completed is zero, then this event is a progress started event. If completed is equal to total, then this event is a progress end event. Otherwise completed indicates the current progress compare to the total value.
[in] total The total amount of work units that need to be completed. If this value is UINT64_MAX, then an indeterminate progress indicator should be displayed.
[in] debugger_id If this optional parameter has a value, it indicates the unique debugger identifier that this progress should be delivered to. If this optional parameter does not have a value, the progress will be delivered to all debuggers.
Definition at line 1711 of file Debugger.cpp.
References FindDebuggerWithID(), g_debugger_list_mutex_ptr, g_debugger_list_ptr, and PrivateReportProgress().
Referenced by lldb_private::Progress::ReportProgress().
ReportSymbolChange()
void Debugger::ReportSymbolChange (const ModuleSpec & module_spec) static
Definition at line 1830 of file Debugger.cpp.
References lldb::eBroadcastSymbolChange, g_debugger_list_mutex_ptr, and g_debugger_list_ptr.
Referenced by lldb_private::SymbolLocator::DownloadSymbolFileAsync().
ReportWarning()
void Debugger::ReportWarning (std::string message, std::optional< lldb::user_id_t > debugger_id = std::nullopt, std::once_flag * once = nullptr) static
Report warning events.
Warning events will be delivered to any debuggers that have listeners for the eBroadcastBitWarning.
Parameters
[in] message The warning message to be reported.
[in] debugger_id If this optional parameter has a value, it indicates the unique debugger identifier that this diagnostic should be delivered to. If this optional parameter does not have a value, the diagnostic event will be delivered to all debuggers.
[in] once If a pointer is passed to a std::once_flag, then it will be used to ensure the given warning is only broadcast once.
Definition at line 1812 of file Debugger.cpp.
References lldb::eSeverityWarning, and ReportDiagnosticImpl().
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::BuildDynamicRegisterInfo(), InstrumentationBoundsSafetyStopInfo::ComputeStopReasonAndSuggestedStackFrameWithDebugInfo(), InstrumentationBoundsSafetyStopInfo::ComputeStopReasonAndSuggestedStackFrameWithoutDebugInfo(), lldb_private::TypeSystemClang::CreateASTContext(), lldb_private::SourceManager::DisplaySourceLinesWithLineNumbersUsingLastFile(), lldb_private::minidump::ProcessMinidump::DoLoadCore(), lldb_private::MemoryHistoryASan::GetHistoryThreads(), lldb_private::SymbolContext::GetParentOfInlinedScope(), InstrumentationBoundsSafetyStopInfo::InstrumentationBoundsSafetyStopInfo(), DynamicLoaderMacOS::NotifyBreakpointHit(), DynamicLoaderMacOSXDYLD::NotifyBreakpointHit(), ObjectFileELF::ParseRISCVAttributes(), lldb_private::StopInfoBreakpoint::PerformAction(), lldb_private::Module::ReportWarning(), lldb_private::Module::ReportWarningOptimization(), lldb_private::Module::ReportWarningUnsupportedLanguage(), lldb_private::InstrumentationRuntimeTSan::RetrieveReportData(), lldb_private::InstrumentationRuntimeUBSan::RetrieveReportData(), lldb_private::ReportRetriever::RetrieveReportData(), and lldb_private::DynamicLoaderDarwin::UnloadModuleSections().
RequestInterrupt()
void Debugger::RequestInterrupt ()
Interruption in LLDB:
This is a voluntary interruption mechanism, not preemptive. Parts of lldb that do work that can be safely interrupted call Debugger::InterruptRequested and if that returns true, they should return at a safe point, shortcutting the rest of the work they were to do.
lldb clients can both offer a CommandInterpreter (through RunCommandInterpreter) and use the SB API's for their own purposes, so it is convenient to separate "interrupting the CommandInterpreter execution" and interrupting the work it is doing with the SB API's. So there are two ways to cause an interrupt:
CommandInterpreter::InterruptCommand: Interrupts the command currently running in the command interpreter IOHandler thread
Debugger::RequestInterrupt: Interrupts are active on anything but the CommandInterpreter thread till CancelInterruptRequest is called.
Since the two checks are mutually exclusive, however, it's also convenient to have just one function to check the interrupt state. Bump the "interrupt requested" count on the debugger to support cooperative interruption. If this is non-zero, InterruptRequested will return true. Interruptible operations are expected to query the InterruptRequested API periodically, and interrupt what they were doing if it returns true.
Definition at line 1518 of file Debugger.cpp.
References m_interrupt_mutex, and m_interrupt_requested.
RestoreInputTerminalState()
void Debugger::RestoreInputTerminalState ()
Definition at line 1249 of file Debugger.cpp.
References GetSelectedExecutionContext(), m_statusline, m_statusline_mutex, and m_terminal_state.
RunIOHandlerAsync()
void Debugger::RunIOHandlerAsync (const lldb::IOHandlerSP & reader_sp, bool cancel_top_handler = true)
Run the given IO handler and return immediately.
Definition at line 1397 of file Debugger.cpp.
References PushIOHandler().
Referenced by lldb_private::CommandObjectGUI::DoExecute(), lldb_private::CommandInterpreter::GetLLDBCommandsFromIOHandler(), lldb_private::CommandInterpreter::GetPythonCommandsFromIOHandler(), lldb_private::ScriptInterpreterPythonImpl::Interrupt(), lldb_private::REPL::IOHandlerInputComplete(), lldb_private::Process::PushProcessIOHandler(), and lldb_private::REPL::RunLoop().
RunIOHandlers()
void Debugger::RunIOHandlers ()
Definition at line 1306 of file Debugger.cpp.
References ClearIOHandlers(), m_io_handler_stack, m_io_handler_synchronous_mutex, and PopIOHandler().
Referenced by IOHandlerThread().
RunIOHandlerSync()
void Debugger::RunIOHandlerSync (const lldb::IOHandlerSP & reader_sp)
Run the given IO handler and block until it's complete.
Definition at line 1331 of file Debugger.cpp.
References m_io_handler_stack, m_io_handler_synchronous_mutex, PopIOHandler(), and PushIOHandler().
Referenced by lldb_private::CommandInterpreter::HandleCommandsFromFile().
RunREPL()
Status Debugger::RunREPL (lldb::LanguageType language, const char * repl_options)
Definition at line 2433 of file Debugger.cpp.
References lldb_private::REPL::Create(), lldb::eLanguageTypeUnknown, lldb_private::LanguageSet::Empty(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::Language::GetLanguagesSupportingREPLs(), lldb_private::Language::GetNameForLanguageType(), GetREPLLanguage(), lldb_private::LanguageSet::GetSingularLanguage(), and lldb_private::Status::Success().
SaveInputTerminalState()
void Debugger::SaveInputTerminalState ()
Definition at line 1238 of file Debugger.cpp.
References lldb_private::File::GetDescriptor(), GetInputFile(), lldb_private::File::kInvalidDescriptor, m_statusline, m_statusline_mutex, and m_terminal_state.
Referenced by SetInputFile().
SetAsyncExecution()
void Debugger::SetAsyncExecution (bool async)
Definition at line 1160 of file Debugger.cpp.
References m_command_interpreter_up.
Referenced by CommandObjectProcessContinue::DoExecute(), lldb_private::CommandInterpreter::HandleCommandsFromFile(), lldb_private::Target::StopHookCommandLine::HandleStop(), lldb_private::StopInfoBreakpoint::PerformAction(), and lldb_private::StopInfoWatchpoint::PerformAction().
SetAutoIndent()
bool Debugger::SetAutoIndent (bool b)
Definition at line 697 of file Debugger.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
SetDestroyCallback()
void Debugger::SetDestroyCallback (lldb_private::DebuggerDestroyCallback destroy_callback, void * baton)
DEPRECATED: We used to only support one Destroy callback.
Now that we support Add and Remove, you should only remove callbacks that you added. Use Add and Remove instead.
Clear all previously added callbacks and only add the given one.
Definition at line 1667 of file Debugger.cpp.
References m_destroy_callback_mutex, m_destroy_callback_next_token, and m_destroy_callbacks.
SetErrorFile()
void Debugger::SetErrorFile (lldb::FileSP file)
Definition at line 1232 of file Debugger.cpp.
References m_error_stream_sp, and m_output_mutex.
SetExternalEditor()
bool Debugger::SetExternalEditor (llvm::StringRef editor)
Definition at line 479 of file Debugger.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
SetInputFile()
void Debugger::SetInputFile (lldb::FileSP file)
Definition at line 1218 of file Debugger.cpp.
References m_input_file_sp, and SaveInputTerminalState().
Referenced by SetInputString().
SetInputString()
Status Debugger::SetInputString (const char * data)
Definition at line 1173 of file Debugger.cpp.
References lldb_private::File::eOpenOptionReadOnly, lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), OpenPipe(), READ, SetInputFile(), and WRITE.
SetIOHandlerThread()
HostThread Debugger::SetIOHandlerThread (HostThread & new_thread) protected
Definition at line 2383 of file Debugger.cpp.
References m_io_handler_thread.
SetLoggingCallback()
void Debugger::SetLoggingCallback (lldb::LogOutputCallback log_callback, void * baton)
Definition at line 1658 of file Debugger.cpp.
References m_callback_handler_sp.
SetOutputFile()
void Debugger::SetOutputFile (lldb::FileSP file)
Definition at line 1226 of file Debugger.cpp.
References m_output_mutex, and m_output_stream_sp.
SetPrintDecls()
bool Debugger::SetPrintDecls (bool b)
Definition at line 708 of file Debugger.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
SetPrompt() [1/2]
void lldb_private::Debugger::SetPrompt (const char *) delete
SetPrompt() [2/2]
void Debugger::SetPrompt (llvm::StringRef p)
Definition at line 375 of file Debugger.cpp.
References lldb_private::ansi::FormatAnsiTerminalCodes(), GetCommandInterpreter(), GetPrompt(), GetUseColor(), lldb_private::Properties::SetPropertyAtIndex(), and lldb_private::CommandInterpreter::UpdatePrompt().
Referenced by SetUseColor().
SetPropertyValue()
Status Debugger::SetPropertyValue (const ExecutionContext * exe_ctx, VarSetOperationType op, llvm::StringRef property_path, llvm::StringRef value) override virtual
Reimplemented from lldb_private::Properties.
Definition at line 235 of file Debugger.cpp.
References lldb_private::Broadcaster::BroadcastEvent(), lldb_private::CommandInterpreter::eBroadcastBitResetPrompt, lldb_private::eLoadScriptFromSymFileFalse, lldb_private::eLoadScriptFromSymFileTrue, lldb_private::eLoadScriptFromSymFileWarn, error(), lldb_private::DataVisualization::ForceUpdate(), lldb_private::ansi::FormatAnsiTerminalCodes(), GetAsyncErrorStream(), GetCommandInterpreter(), GetPrompt(), GetSelectedExecutionContextRef(), lldb_private::StreamString::GetSize(), lldb_private::StreamString::GetString(), lldb_private::ExecutionContext::GetTargetSP(), GetUseColor(), GetUseSourceCache(), m_source_file_cache, m_statusline, m_statusline_mutex, RedrawStatusline(), lldb_private::Properties::SetPropertyValue(), SetUseColor(), StatuslineSupported(), and lldb_private::CommandInterpreter::UpdatePrompt().
SetREPLLanguage()
bool Debugger::SetREPLLanguage (lldb::LanguageType repl_lang)
Definition at line 413 of file Debugger.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
SetScriptLanguage()
bool Debugger::SetScriptLanguage (lldb::ScriptLanguage script_lang)
Definition at line 403 of file Debugger.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
SetSeparator()
bool Debugger::SetSeparator (llvm::StringRef s)
Definition at line 558 of file Debugger.cpp.
References RedrawStatusline(), and lldb_private::Properties::SetPropertyAtIndex().
Referenced by Debugger().
SetShowInlineDiagnostics()
bool Debugger::SetShowInlineDiagnostics (bool b)
Definition at line 737 of file Debugger.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
SetShowProgress()
bool Debugger::SetShowProgress (bool show_progress)
Definition at line 505 of file Debugger.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
Referenced by lldb_private::REPL::REPL().
SetStatuslineFormat()
bool Debugger::SetStatuslineFormat (const FormatEntity::Entry & format)
Definition at line 533 of file Debugger.cpp.
References RedrawStatusline(), and lldb_private::Properties::SetPropertyAtIndex().
SetTabSize()
bool Debugger::SetTabSize (uint64_t tab_size)
Definition at line 719 of file Debugger.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
SetTerminalHeight()
bool Debugger::SetTerminalHeight (uint64_t term_height)
Definition at line 446 of file Debugger.cpp.
References m_io_handler_stack, m_statusline, m_statusline_mutex, and lldb_private::Properties::SetPropertyAtIndex().
SetTerminalWidth()
bool Debugger::SetTerminalWidth (uint64_t term_width)
Definition at line 424 of file Debugger.cpp.
References m_io_handler_stack, m_statusline, m_statusline_mutex, and lldb_private::Properties::SetPropertyAtIndex().
SettingsInitialize()
void Debugger::SettingsInitialize () static
Definition at line 786 of file Debugger.cpp.
References lldb_private::Target::SettingsInitialize().
Referenced by lldb_private::SystemInitializerFull::Initialize().
SettingsTerminate()
void Debugger::SettingsTerminate () static
Definition at line 788 of file Debugger.cpp.
References lldb_private::Target::SettingsTerminate().
Referenced by lldb_private::SystemInitializerFull::Terminate().
SetUseColor()
bool Debugger::SetUseColor (bool use_color)
Definition at line 490 of file Debugger.cpp.
References GetCommandInterpreter(), GetPrompt(), SetPrompt(), lldb_private::Properties::SetPropertyAtIndex(), and lldb_private::CommandInterpreter::UpdateUseColor().
Referenced by Debugger(), and SetPropertyValue().
SetUseExternalEditor()
bool Debugger::SetUseExternalEditor (bool use_external_editor_p)
Definition at line 468 of file Debugger.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
SetUseSourceCache()
bool Debugger::SetUseSourceCache (bool use_source_cache)
Definition at line 607 of file Debugger.cpp.
References m_source_file_cache, and lldb_private::Properties::SetPropertyAtIndex().
StartEventHandlerThread()
bool Debugger::StartEventHandlerThread ()
Manually start the global event handler thread.
It is useful to plugins that directly use the lldb_private namespace and want to use the debugger's default event handler thread instead of defining their own.
Definition at line 2256 of file Debugger.cpp.
References lldb_private::ConstString::AsCString(), DefaultEventHandler(), eBroadcastBitEventThreadIsListening, g_debugger_event_thread_stack_bytes, lldb_private::ConstString::GetLength(), lldb_private::GetLog(), lldb_private::ConstString::GetStringRef(), lldb_private::Host, lldb_private::ThreadLauncher::LaunchThread(), LLDB_LOG_ERROR, m_event_handler_thread, m_sync_broadcaster, and lldb_private::Listener::MakeListener().
StartIOHandlerThread()
bool Debugger::StartIOHandlerThread () protected
Definition at line 2389 of file Debugger.cpp.
References lldb_private::GetLog(), lldb_private::Host, IOHandlerThread(), lldb_private::ThreadLauncher::LaunchThread(), LLDB_LOG_ERROR, and m_io_handler_thread.
Referenced by lldb_private::REPL::RunLoop().
StatuslineSupported()
bool Debugger::StatuslineSupported () protected
Definition at line 2119 of file Debugger.cpp.
References GetShowStatusline(), and IsEscapeCodeCapableTTY().
Referenced by DefaultEventHandler(), and SetPropertyValue().
StopEventHandlerThread()
void Debugger::StopEventHandlerThread ()
Manually stop the debugger's default event handler.
Definition at line 2296 of file Debugger.cpp.
References lldb_private::Broadcaster::BroadcastEvent(), lldb_private::CommandInterpreter::eBroadcastBitQuitCommandReceived, GetCommandInterpreter(), and m_event_handler_thread.
Referenced by Clear(), and IOHandlerThread().
StopIOHandlerThread()
void Debugger::StopIOHandlerThread () protected
Definition at line 2404 of file Debugger.cpp.
References lldb_private::File::Close(), GetInputFile(), and m_io_handler_thread.
Referenced by Clear().
Terminate()
void Debugger::Terminate () static
Definition at line 760 of file Debugger.cpp.
References g_debugger_list_mutex_ptr, g_debugger_list_ptr, and g_thread_pool.
Referenced by lldb_private::SystemInitializerFull::Terminate().
Friends And Related Symbol Documentation
CommandInterpreter
friend class CommandInterpreter friend
Definition at line 640 of file Debugger.h.
References CommandInterpreter.
Referenced by CommandInterpreter, Debugger(), DefaultEventHandler(), Destroy(), and GetCommandInterpreter().
Progress
friend class Progress friend
Definition at line 642 of file Debugger.h.
References Progress.
Referenced by Progress.
ProgressManager
friend class ProgressManager friend
Definition at line 643 of file Debugger.h.
References ProgressManager.
Referenced by ProgressManager.
REPL
friend class REPL friend
Definition at line 641 of file Debugger.h.
References REPL.
Referenced by REPL.
Statusline
friend class Statusline friend
Definition at line 644 of file Debugger.h.
References lldb::eBroadcastBitProgress, and Statusline.
Referenced by Statusline.
Member Data Documentation
g_load_plugin_callback
LoadPluginCallbackType Debugger::g_load_plugin_callback = nullptr static protected
Definition at line 780 of file Debugger.h.
Referenced by Initialize(), and LoadPlugin().
m_broadcaster
Broadcaster lldb_private::Debugger::m_broadcaster protected
Public Debugger event broadcaster.
Definition at line 786 of file Debugger.h.
Referenced by Debugger(), DefaultEventHandler(), GetBroadcaster(), and GetBroadcaster().
m_broadcaster_manager_sp
lldb::BroadcasterManagerSP lldb_private::Debugger::m_broadcaster_manager_sp protected
Definition at line 744 of file Debugger.h.
Referenced by Clear(), Debugger(), DefaultEventHandler(), and GetBroadcasterManager().
m_callback_handler_sp
std::shared_ptr<CallbackLogHandler> lldb_private::Debugger::m_callback_handler_sp protected
Definition at line 778 of file Debugger.h.
Referenced by Debugger(), EnableLog(), and SetLoggingCallback().
m_clear_once
llvm::once_flag lldb_private::Debugger::m_clear_once protected
Definition at line 788 of file Debugger.h.
Referenced by Clear(), and Debugger().
m_command_interpreter_up
std::unique_ptr<CommandInterpreter> lldb_private::Debugger::m_command_interpreter_up protected
Definition at line 764 of file Debugger.h.
Referenced by Clear(), Debugger(), DefaultEventHandler(), GetAsyncExecution(), GetCommandInterpreter(), and SetAsyncExecution().
m_destroy_callback_mutex
std::mutex lldb_private::Debugger::m_destroy_callback_mutex protected
Definition at line 798 of file Debugger.h.
Referenced by AddDestroyCallback(), HandleDestroyCallback(), RemoveDestroyCallback(), and SetDestroyCallback().
m_destroy_callback_next_token
lldb::callback_token_t lldb_private::Debugger::m_destroy_callback_next_token = 0 protected
Definition at line 799 of file Debugger.h.
Referenced by AddDestroyCallback(), and SetDestroyCallback().
m_destroy_callbacks
llvm::SmallVector<DestroyCallbackInfo, 2> lldb_private::Debugger::m_destroy_callbacks protected
Definition at line 810 of file Debugger.h.
Referenced by AddDestroyCallback(), HandleDestroyCallback(), RemoveDestroyCallback(), and SetDestroyCallback().
m_diagnostics_callback_id
Diagnostics::CallbackID lldb_private::Debugger::m_diagnostics_callback_id protected
Definition at line 790 of file Debugger.h.
Referenced by Clear(), and Debugger().
m_dummy_target_sp
lldb::TargetSP lldb_private::Debugger::m_dummy_target_sp protected
Definition at line 789 of file Debugger.h.
Referenced by Debugger(), GetDummyTarget(), and GetSelectedExecutionContextRef().
m_error_stream_sp
lldb::LockableStreamFileSP lldb_private::Debugger::m_error_stream_sp protected
Definition at line 741 of file Debugger.h.
Referenced by Debugger(), GetErrorFileSP(), GetErrorStreamSP(), PrintAsync(), and SetErrorFile().
m_event_handler_thread
HostThread lldb_private::Debugger::m_event_handler_thread protected
Definition at line 783 of file Debugger.h.
Referenced by Debugger(), IsHandlingEvents(), StartEventHandlerThread(), and StopEventHandlerThread().
m_forward_listener_sp
lldb::ListenerSP lldb_private::Debugger::m_forward_listener_sp protected
Definition at line 787 of file Debugger.h.
Referenced by CancelForwardEvents(), Debugger(), DefaultEventHandler(), EnableForwardEvents(), and IsForwardingEvents().
m_input_file_sp
lldb::FileSP lldb_private::Debugger::m_input_file_sp protected
Definition at line 739 of file Debugger.h.
Referenced by Debugger(), GetInputFile(), GetInputFileSP(), and SetInputFile().
m_instance_name
const std::string lldb_private::Debugger::m_instance_name protected
Definition at line 779 of file Debugger.h.
Referenced by Debugger(), and GetInstanceName().
m_interrupt_mutex
std::mutex lldb_private::Debugger::m_interrupt_mutex protected
Definition at line 813 of file Debugger.h.
Referenced by CancelInterruptRequest(), InterruptRequested(), and RequestInterrupt().
m_interrupt_requested
uint32_t lldb_private::Debugger::m_interrupt_requested = 0 protected
Tracks interrupt requests.
Definition at line 812 of file Debugger.h.
Referenced by CancelInterruptRequest(), InterruptRequested(), and RequestInterrupt().
m_io_handler_stack
IOHandlerStack lldb_private::Debugger::m_io_handler_stack protected
Definition at line 770 of file Debugger.h.
Referenced by AdoptTopIOHandlerFilesIfInvalid(), CheckTopIOHandlerTypes(), ClearIOHandlers(), Debugger(), DispatchInputEndOfFile(), DispatchInputInterrupt(), GetIOHandlerCommandPrefix(), GetIOHandlerHelpPrologue(), GetTopIOHandlerControlSequence(), IsTopIOHandler(), PopIOHandler(), PrintAsync(), PushIOHandler(), RefreshIOHandler(), RunIOHandlers(), RunIOHandlerSync(), SetTerminalHeight(), and SetTerminalWidth().
m_io_handler_synchronous_mutex
std::recursive_mutex lldb_private::Debugger::m_io_handler_synchronous_mutex protected
Definition at line 771 of file Debugger.h.
Referenced by RunIOHandlers(), and RunIOHandlerSync().
m_io_handler_thread
HostThread lldb_private::Debugger::m_io_handler_thread protected
Definition at line 784 of file Debugger.h.
Referenced by Debugger(), HasIOHandlerThread(), IsIOHandlerThreadCurrentThread(), JoinIOHandlerThread(), SetIOHandlerThread(), StartIOHandlerThread(), and StopIOHandlerThread().
m_listener_sp
lldb::ListenerSP lldb_private::Debugger::m_listener_sp protected
Definition at line 754 of file Debugger.h.
Referenced by Clear(), Debugger(), and GetListener().
m_loaded_plugins
LoadedPluginsList lldb_private::Debugger::m_loaded_plugins protected
Definition at line 782 of file Debugger.h.
Referenced by Debugger(), and LoadPlugin().
m_output_flush_mutex
std::mutex lldb_private::Debugger::m_output_flush_mutex protected
Definition at line 734 of file Debugger.h.
Referenced by FlushProcessOutput().
m_output_mutex
LockableStreamFile::Mutex lldb_private::Debugger::m_output_mutex protected
Definition at line 742 of file Debugger.h.
Referenced by AdoptTopIOHandlerFilesIfInvalid(), Debugger(), SetErrorFile(), and SetOutputFile().
m_output_stream_sp
lldb::LockableStreamFileSP lldb_private::Debugger::m_output_stream_sp protected
Definition at line 740 of file Debugger.h.
Referenced by Debugger(), GetOutputFileSP(), GetOutputStreamSP(), PrintAsync(), and SetOutputFile().
m_platform_list
PlatformList lldb_private::Debugger::m_platform_list protected
Definition at line 753 of file Debugger.h.
Referenced by Debugger(), and GetPlatformList().
m_progress_reports
llvm::SmallVector<ProgressReport, 4> lldb_private::Debugger::m_progress_reports protected
Bookkeeping for command line progress events.
Definition at line 794 of file Debugger.h.
Referenced by GetCurrentProgressReport(), and HandleProgressEvent().
m_progress_reports_mutex
std::mutex lldb_private::Debugger::m_progress_reports_mutex mutable protected
Definition at line 795 of file Debugger.h.
Referenced by GetCurrentProgressReport(), and HandleProgressEvent().
m_script_interpreter_mutex
std::recursive_mutex lldb_private::Debugger::m_script_interpreter_mutex protected
Definition at line 766 of file Debugger.h.
Referenced by GetScriptInterpreter().
m_script_interpreters
std::array<lldb::ScriptInterpreterSP, lldb::eScriptLanguageUnknown> lldb_private::Debugger::m_script_interpreters protected
Definition at line 768 of file Debugger.h.
Referenced by GetScriptInterpreter().
m_source_file_cache
SourceManager::SourceFileCache lldb_private::Debugger::m_source_file_cache protected
Definition at line 759 of file Debugger.h.
Referenced by Debugger(), GetSourceFileCache(), SetPropertyValue(), and SetUseSourceCache().
m_source_manager_up
std::unique_ptr<SourceManager> lldb_private::Debugger::m_source_manager_up protected
Definition at line 755 of file Debugger.h.
Referenced by Debugger(), and GetSourceManager().
m_statusline
std::optional<Statusline> lldb_private::Debugger::m_statusline protected
Definition at line 775 of file Debugger.h.
Referenced by DefaultEventHandler(), RedrawStatusline(), RestoreInputTerminalState(), SaveInputTerminalState(), SetPropertyValue(), SetTerminalHeight(), and SetTerminalWidth().
m_statusline_mutex
std::mutex lldb_private::Debugger::m_statusline_mutex protected
Mutex protecting the m_statusline member.
Definition at line 774 of file Debugger.h.
Referenced by DefaultEventHandler(), RedrawStatusline(), RestoreInputTerminalState(), SaveInputTerminalState(), SetPropertyValue(), SetTerminalHeight(), and SetTerminalWidth().
m_stream_handlers
llvm::StringMap<std::weak_ptr<LogHandler> > lldb_private::Debugger::m_stream_handlers protected
Definition at line 777 of file Debugger.h.
Referenced by Debugger(), and EnableLog().
m_sync_broadcaster
Broadcaster lldb_private::Debugger::m_sync_broadcaster protected
Private debugger synchronization.
Definition at line 785 of file Debugger.h.
Referenced by Debugger(), DefaultEventHandler(), and StartEventHandlerThread().
m_target_list
TargetList lldb_private::Debugger::m_target_list protected
Definition at line 751 of file Debugger.h.
Referenced by Clear(), Debugger(), GetSelectedOrDummyTarget(), GetSelectedTarget(), and GetTargetList().
m_terminal_state
TerminalState lldb_private::Debugger::m_terminal_state protected
Definition at line 750 of file Debugger.h.
Referenced by Clear(), Debugger(), RestoreInputTerminalState(), and SaveInputTerminalState().
The documentation for this class was generated from the following files:
Debugger.h
Debugger.cpp