LLDB: lldb::SBThreadPlan Class Reference
lldb::SBThreadPlan Class Reference
#include <SBThreadPlan.h>
Public Member Functions
SBThreadPlan ()
SBThreadPlan (const lldb::SBThreadPlan &threadPlan)
SBThreadPlan (lldb::SBThread &thread, const char *class_name)
SBThreadPlan (lldb::SBThread &thread, const char *class_name, lldb::SBStructuredData &args_data)
~SBThreadPlan ()
operator bool () const
bool IsValid () const
void Clear ()
lldb::StopReason GetStopReason ()
size_t GetStopReasonDataCount ()
Get the number of words associated with the stop reason.
uint64_t GetStopReasonDataAtIndex (uint32_t idx)
Get information associated with a stop reason.
SBThread GetThread () const
const lldb::SBThreadPlan & operator= (const lldb::SBThreadPlan &rhs)
bool GetDescription (lldb::SBStream &description) const
void SetPlanComplete (bool success)
bool IsPlanComplete ()
bool IsPlanStale ()
bool IsValid ()
bool GetStopOthers ()
void SetStopOthers (bool stop_others)
SBThreadPlan QueueThreadPlanForStepOverRange (SBAddress &start_address, lldb::addr_t range_size)
SBThreadPlan QueueThreadPlanForStepOverRange (SBAddress &start_address, lldb::addr_t range_size, SBError &error)
SBThreadPlan QueueThreadPlanForStepInRange (SBAddress &start_address, lldb::addr_t range_size)
SBThreadPlan QueueThreadPlanForStepInRange (SBAddress &start_address, lldb::addr_t range_size, SBError &error)
SBThreadPlan QueueThreadPlanForStepOut (uint32_t frame_idx_to_step_to, bool first_insn=false)
SBThreadPlan QueueThreadPlanForStepOut (uint32_t frame_idx_to_step_to, bool first_insn, SBError &error)
SBThreadPlan QueueThreadPlanForStepSingleInstruction (bool step_over, SBError &error)
SBThreadPlan QueueThreadPlanForRunToAddress (SBAddress address)
SBThreadPlan QueueThreadPlanForRunToAddress (SBAddress address, SBError &error)
SBThreadPlan QueueThreadPlanForStepScripted (const char *script_class_name)
SBThreadPlan QueueThreadPlanForStepScripted (const char *script_class_name, SBError &error)
SBThreadPlan QueueThreadPlanForStepScripted (const char *script_class_name, lldb::SBStructuredData &args_data, SBError &error)
Protected Member Functions
SBThreadPlan (const lldb::ThreadPlanSP &lldb_object_sp)
Private Member Functions
lldb::ThreadPlanSP GetSP () const
lldb_private::ThreadPlan * get () const
void SetThreadPlan (const lldb::ThreadPlanSP &lldb_object_sp)
Private Attributes
lldb::ThreadPlanWP m_opaque_wp
Friends
class lldb_private::python::SWIGBridge
class SBBreakpoint
class SBBreakpointLocation
class SBFrame
class SBProcess
class SBDebugger
class SBValue
class lldb_private::QueueImpl
class SBQueueItem
Detailed Description
Definition at line 24 of file SBThreadPlan.h.
Constructor & Destructor Documentation
SBThreadPlan() [1/5]
SBThreadPlan::SBThreadPlan ()
Definition at line 52 of file SBThreadPlan.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb_private::python::SWIGBridge, operator=(), QueueThreadPlanForRunToAddress(), QueueThreadPlanForStepInRange(), QueueThreadPlanForStepOut(), QueueThreadPlanForStepOverRange(), QueueThreadPlanForStepScripted(), QueueThreadPlanForStepScripted(), QueueThreadPlanForStepSingleInstruction(), SBThreadPlan(), and ~SBThreadPlan().
SBThreadPlan() [2/5]
SBThreadPlan::SBThreadPlan (const lldb::SBThreadPlan & threadPlan)
Definition at line 59 of file SBThreadPlan.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_wp, and SBThreadPlan().
SBThreadPlan() [3/5]
SBThreadPlan::SBThreadPlan (lldb::SBThread & thread, const char * class_name)
Definition at line 64 of file SBThreadPlan.cpp.
References lldb::SBThread::get(), LLDB_INSTRUMENT_VA, and m_opaque_wp.
SBThreadPlan() [4/5]
SBThreadPlan::SBThreadPlan (lldb::SBThread & thread, const char * class_name, lldb::SBStructuredData & args_data)
Definition at line 73 of file SBThreadPlan.cpp.
References lldb::SBThread::get(), LLDB_INSTRUMENT_VA, lldb::SBStructuredData::m_impl_up, and m_opaque_wp.
~SBThreadPlan()
SBThreadPlan::~SBThreadPlan () default
References Clear(), error(), GetDescription(), GetStopOthers(), GetStopReason(), GetStopReasonDataAtIndex(), GetStopReasonDataCount(), GetThread(), IsPlanComplete(), IsPlanStale(), IsValid(), operator=(), QueueThreadPlanForRunToAddress(), QueueThreadPlanForStepInRange(), QueueThreadPlanForStepOut(), QueueThreadPlanForStepOverRange(), QueueThreadPlanForStepScripted(), QueueThreadPlanForStepSingleInstruction(), SBThreadPlan(), SetPlanComplete(), and SetStopOthers().
SBThreadPlan() [5/5]
SBThreadPlan::SBThreadPlan (const lldb::ThreadPlanSP & lldb_object_sp) protected
Definition at line 54 of file SBThreadPlan.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_wp.
Member Function Documentation
Clear()
void SBThreadPlan::Clear ()
Definition at line 105 of file SBThreadPlan.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_wp.
Referenced by ~SBThreadPlan().
get()
lldb_private::ThreadPlan * lldb::SBThreadPlan::get () const inline private
Definition at line 138 of file SBThreadPlan.h.
References GetSP().
GetDescription()
bool SBThreadPlan::GetDescription (lldb::SBStream & description) const
Definition at line 139 of file SBThreadPlan.cpp.
References lldb::eDescriptionLevelFull, lldb::SBStream::get(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBThreadPlan().
GetSP()
lldb::ThreadPlanSP lldb::SBThreadPlan::GetSP () const inline private
Definition at line 137 of file SBThreadPlan.h.
References m_opaque_wp.
Referenced by get(), GetDescription(), GetStopOthers(), GetThread(), IsPlanComplete(), IsPlanStale(), IsValid(), operator bool(), QueueThreadPlanForRunToAddress(), QueueThreadPlanForStepInRange(), QueueThreadPlanForStepOut(), QueueThreadPlanForStepOverRange(), QueueThreadPlanForStepScripted(), QueueThreadPlanForStepScripted(), QueueThreadPlanForStepSingleInstruction(), SetPlanComplete(), and SetStopOthers().
GetStopOthers()
bool SBThreadPlan::GetStopOthers ()
Definition at line 190 of file SBThreadPlan.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBThreadPlan().
GetStopReason()
lldb::StopReason SBThreadPlan::GetStopReason ()
Definition at line 111 of file SBThreadPlan.cpp.
References lldb::eStopReasonNone, and LLDB_INSTRUMENT_VA.
Referenced by ~SBThreadPlan().
GetStopReasonDataAtIndex()
uint64_t SBThreadPlan::GetStopReasonDataAtIndex (uint32_t idx)
Get information associated with a stop reason.
Breakpoint stop reasons will have data that consists of pairs of breakpoint IDs followed by the breakpoint location IDs (they always come in pairs).
Stop Reason Count Data Type ======================== ===== ========================================= eStopReasonNone 0 eStopReasonTrace 0 eStopReasonBreakpoint N duple: {breakpoint id, location id} eStopReasonWatchpoint 1 watchpoint id eStopReasonSignal 1 unix signal number eStopReasonException N exception data eStopReasonExec 0 eStopReasonFork 1 pid of the child process eStopReasonVFork 1 pid of the child process eStopReasonVForkDone 0 eStopReasonPlanComplete 0
Definition at line 123 of file SBThreadPlan.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBThreadPlan().
GetStopReasonDataCount()
size_t SBThreadPlan::GetStopReasonDataCount ()
Get the number of words associated with the stop reason.
See also GetStopReasonDataAtIndex().
Definition at line 117 of file SBThreadPlan.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBThreadPlan().
GetThread()
SBThread SBThreadPlan::GetThread () const
Definition at line 129 of file SBThreadPlan.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBThread.
Referenced by ~SBThreadPlan().
IsPlanComplete()
bool SBThreadPlan::IsPlanComplete ()
Definition at line 163 of file SBThreadPlan.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBThreadPlan().
IsPlanStale()
bool SBThreadPlan::IsPlanStale ()
Definition at line 172 of file SBThreadPlan.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBThreadPlan().
IsValid() [1/2]
bool SBThreadPlan::IsValid ()
Definition at line 181 of file SBThreadPlan.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
IsValid() [2/2]
bool SBThreadPlan::IsValid () const
Definition at line 95 of file SBThreadPlan.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBThreadPlan().
operator bool()
SBThreadPlan::operator bool () const explicit
Definition at line 99 of file SBThreadPlan.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
operator=()
const lldb::SBThreadPlan & SBThreadPlan::operator= (const lldb::SBThreadPlan & rhs)
Definition at line 85 of file SBThreadPlan.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_wp, and SBThreadPlan().
Referenced by ~SBThreadPlan().
QueueThreadPlanForRunToAddress() [1/2]
SBThreadPlan SBThreadPlan::QueueThreadPlanForRunToAddress (SBAddress address)
Definition at line 352 of file SBThreadPlan.cpp.
References error(), LLDB_INSTRUMENT_VA, and QueueThreadPlanForRunToAddress().
Referenced by QueueThreadPlanForRunToAddress(), and ~SBThreadPlan().
QueueThreadPlanForRunToAddress() [2/2]
SBThreadPlan SBThreadPlan::QueueThreadPlanForRunToAddress (SBAddress address, SBError & error)
Definition at line 359 of file SBThreadPlan.cpp.
References lldb_private::Status::AsCString(), error(), lldb_private::Status::Fail(), lldb::SBAddress::get(), GetSP(), LLDB_INSTRUMENT_VA, and SBThreadPlan().
QueueThreadPlanForStepInRange() [1/2]
SBThreadPlan SBThreadPlan::QueueThreadPlanForStepInRange (SBAddress & start_address, lldb::addr_t range_size)
Definition at line 253 of file SBThreadPlan.cpp.
References error(), LLDB_INSTRUMENT_VA, and QueueThreadPlanForStepInRange().
Referenced by QueueThreadPlanForStepInRange(), and ~SBThreadPlan().
QueueThreadPlanForStepInRange() [2/2]
SBThreadPlan SBThreadPlan::QueueThreadPlanForStepInRange (SBAddress & start_address, lldb::addr_t range_size, SBError & error)
Definition at line 262 of file SBThreadPlan.cpp.
References lldb_private::Status::AsCString(), lldb_private::Address::CalculateSymbolContext(), lldb::eAllThreads, error(), lldb_private::Status::Fail(), lldb::SBAddress::get(), GetSP(), LLDB_INSTRUMENT_VA, and SBThreadPlan().
QueueThreadPlanForStepOut() [1/2]
SBThreadPlan SBThreadPlan::QueueThreadPlanForStepOut (uint32_t frame_idx_to_step_to, bool first_insn, SBError & error)
Definition at line 302 of file SBThreadPlan.cpp.
References lldb_private::Status::AsCString(), error(), lldb_private::eVoteNoOpinion, lldb_private::eVoteYes, lldb_private::Status::Fail(), GetSP(), LLDB_INSTRUMENT_VA, and SBThreadPlan().
QueueThreadPlanForStepOut() [2/2]
SBThreadPlan SBThreadPlan::QueueThreadPlanForStepOut (uint32_t frame_idx_to_step_to, bool first_insn = false)
Definition at line 293 of file SBThreadPlan.cpp.
References error(), LLDB_INSTRUMENT_VA, and QueueThreadPlanForStepOut().
Referenced by QueueThreadPlanForStepOut(), and ~SBThreadPlan().
QueueThreadPlanForStepOverRange() [1/2]
SBThreadPlan SBThreadPlan::QueueThreadPlanForStepOverRange (SBAddress & start_address, lldb::addr_t range_size)
Definition at line 214 of file SBThreadPlan.cpp.
References error(), LLDB_INSTRUMENT_VA, and QueueThreadPlanForStepOverRange().
Referenced by QueueThreadPlanForStepOverRange(), and ~SBThreadPlan().
QueueThreadPlanForStepOverRange() [2/2]
SBThreadPlan SBThreadPlan::QueueThreadPlanForStepOverRange (SBAddress & start_address, lldb::addr_t range_size, SBError & error)
Definition at line 222 of file SBThreadPlan.cpp.
References lldb_private::Status::AsCString(), lldb_private::Address::CalculateSymbolContext(), lldb::eAllThreads, error(), lldb_private::Status::Fail(), lldb::SBAddress::get(), GetSP(), LLDB_INSTRUMENT_VA, and SBThreadPlan().
QueueThreadPlanForStepScripted() [1/3]
SBThreadPlan SBThreadPlan::QueueThreadPlanForStepScripted (const char * script_class_name)
Definition at line 385 of file SBThreadPlan.cpp.
References error(), LLDB_INSTRUMENT_VA, and QueueThreadPlanForStepScripted().
Referenced by QueueThreadPlanForStepScripted(), and ~SBThreadPlan().
QueueThreadPlanForStepScripted() [2/3]
SBThreadPlan SBThreadPlan::QueueThreadPlanForStepScripted (const char * script_class_name, lldb::SBStructuredData & args_data, SBError & error)
Definition at line 416 of file SBThreadPlan.cpp.
References lldb_private::Status::AsCString(), error(), lldb_private::Status::Fail(), GetSP(), LLDB_INSTRUMENT_VA, lldb::SBStructuredData::m_impl_up, and SBThreadPlan().
QueueThreadPlanForStepScripted() [3/3]
SBThreadPlan SBThreadPlan::QueueThreadPlanForStepScripted (const char * script_class_name, SBError & error)
Definition at line 393 of file SBThreadPlan.cpp.
References lldb_private::Status::AsCString(), error(), lldb_private::Status::Fail(), GetSP(), LLDB_INSTRUMENT_VA, and SBThreadPlan().
QueueThreadPlanForStepSingleInstruction()
SBThreadPlan SBThreadPlan::QueueThreadPlanForStepSingleInstruction (bool step_over, SBError & error)
Definition at line 329 of file SBThreadPlan.cpp.
References lldb_private::Status::AsCString(), error(), lldb_private::Status::Fail(), GetSP(), LLDB_INSTRUMENT_VA, and SBThreadPlan().
Referenced by ~SBThreadPlan().
SetPlanComplete()
void SBThreadPlan::SetPlanComplete (bool success)
Definition at line 155 of file SBThreadPlan.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBThreadPlan().
SetStopOthers()
void SBThreadPlan::SetStopOthers (bool stop_others)
Definition at line 199 of file SBThreadPlan.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBThreadPlan().
SetThreadPlan()
void SBThreadPlan::SetThreadPlan (const lldb::ThreadPlanSP & lldb_object_sp) private
Definition at line 151 of file SBThreadPlan.cpp.
References m_opaque_wp.
Friends And Related Symbol Documentation
lldb_private::python::SWIGBridge
friend class lldb_private::python::SWIGBridge friend
Definition at line 123 of file SBThreadPlan.h.
References SBThreadPlan().
lldb_private::QueueImpl
friend class lldb_private::QueueImpl friend
Definition at line 134 of file SBThreadPlan.h.
SBBreakpoint
friend class SBBreakpoint friend
Definition at line 128 of file SBThreadPlan.h.
References SBBreakpoint.
Referenced by SBBreakpoint.
SBBreakpointLocation
friend class SBBreakpointLocation friend
Definition at line 129 of file SBThreadPlan.h.
References SBBreakpointLocation.
Referenced by SBBreakpointLocation.
SBDebugger
friend class SBDebugger friend
Definition at line 132 of file SBThreadPlan.h.
References SBDebugger.
Referenced by SBDebugger.
SBFrame
friend class SBFrame friend
Definition at line 130 of file SBThreadPlan.h.
References SBFrame.
Referenced by SBFrame.
SBProcess
friend class SBProcess friend
Definition at line 131 of file SBThreadPlan.h.
References SBProcess.
Referenced by SBProcess.
SBQueueItem
friend class SBQueueItem friend
Definition at line 135 of file SBThreadPlan.h.
References SBQueueItem.
Referenced by SBQueueItem.
SBValue
friend class SBValue friend
Definition at line 133 of file SBThreadPlan.h.
References SBValue.
Referenced by SBValue.
Member Data Documentation
m_opaque_wp
lldb::ThreadPlanWP lldb::SBThreadPlan::m_opaque_wp private
Definition at line 141 of file SBThreadPlan.h.
Referenced by Clear(), GetSP(), operator=(), SBThreadPlan(), SBThreadPlan(), SBThreadPlan(), SBThreadPlan(), and SetThreadPlan().
The documentation for this class was generated from the following files:
SBThreadPlan.h
SBThreadPlan.cpp