LLDB: lldb::SBTarget Class Reference
lldb::SBTarget Class Reference
#include <SBTarget.h>
Public Types
enum {
eBroadcastBitBreakpointChanged = (1 << 0) , eBroadcastBitModulesLoaded = (1 << 1) , eBroadcastBitModulesUnloaded = (1 << 2) , eBroadcastBitWatchpointChanged = (1 << 3) ,
eBroadcastBitSymbolsLoaded = (1 << 4) , eBroadcastBitSymbolsChanged = (1 << 5) , eBroadcastBitNewTargetCreated = (1 << 6)
}
Public Member Functions
SBTarget ()
SBTarget (const lldb::SBTarget &rhs)
~SBTarget ()
const lldb::SBTarget & operator= (const lldb::SBTarget &rhs)
operator bool () const
bool IsValid () const
lldb::SBProcess GetProcess ()
void SetCollectingStats (bool v)
Sets whether we should collect statistics on lldb or not.
bool GetCollectingStats ()
Returns whether statistics collection are enabled.
lldb::SBStructuredData GetStatistics ()
Returns a dump of the collected statistics.
lldb::SBStructuredData GetStatistics (SBStatisticsOptions options)
Returns a dump of the collected statistics.
void ResetStatistics ()
Reset the statistics collected for this target.
lldb::SBPlatform GetPlatform ()
Return the platform object associated with the target.
SBEnvironment GetEnvironment ()
Return the environment variables that would be used to launch a new process.
SBError Install ()
Install any binaries that need to be installed.
lldb::SBProcess Launch (SBListener &listener, char const **argv, char const **envp, const char *stdin_path, const char *stdout_path, const char *stderr_path, const char *working_directory, uint32_t launch_flags, bool stop_at_entry, lldb::SBError &error)
Launch a new process.
SBProcess LoadCore (const char *core_file)
SBProcess LoadCore (const char *core_file, lldb::SBError &error)
SBProcess LaunchSimple (const char **argv, const char **envp, const char *working_directory)
Launch a new process with sensible defaults.
SBProcess Launch (SBLaunchInfo &launch_info, SBError &error)
SBProcess Attach (SBAttachInfo &attach_info, SBError &error)
lldb::SBProcess AttachToProcessWithID (SBListener &listener, lldb::pid_t pid, lldb::SBError &error)
Attach to process with pid.
lldb::SBProcess AttachToProcessWithName (SBListener &listener, const char *name, bool wait_for, lldb::SBError &error)
Attach to process with name.
lldb::SBProcess ConnectRemote (SBListener &listener, const char *url, const char *plugin_name, SBError &error)
Connect to a remote debug server with url.
lldb::SBFileSpec GetExecutable ()
void AppendImageSearchPath (const char *from, const char *to, lldb::SBError &error)
bool AddModule (lldb::SBModule &module)
lldb::SBModule AddModule (const char *path, const char *triple, const char *uuid)
lldb::SBModule AddModule (const char *path, const char *triple, const char *uuid_cstr, const char *symfile)
lldb::SBModule AddModule (const SBModuleSpec &module_spec)
uint32_t GetNumModules () const
lldb::SBModule GetModuleAtIndex (uint32_t idx)
bool RemoveModule (lldb::SBModule module)
lldb::SBDebugger GetDebugger () const
lldb::SBModule FindModule (const lldb::SBFileSpec &file_spec)
lldb::SBModule FindModule (const lldb::SBModuleSpec &module_spec) const
Find a module with the given module specification.
lldb::SBSymbolContextList FindCompileUnits (const lldb::SBFileSpec &sb_file_spec)
Find compile units related to *this target and passed source file.
lldb::ByteOrder GetByteOrder ()
uint32_t GetAddressByteSize ()
const char * GetTriple ()
const char * GetArchName () const
const char * GetABIName ()
const char * GetLabel () const
lldb::user_id_t GetGloballyUniqueID () const
Get the globally unique ID for this target.
const char * GetTargetSessionName () const
Get the target session name for this target.
SBError SetLabel (const char *label)
uint32_t GetMinimumOpcodeByteSize () const
Architecture opcode byte size width accessor.
uint32_t GetMaximumOpcodeByteSize () const
Architecture opcode byte size width accessor.
uint32_t GetDataByteSize ()
uint32_t GetCodeByteSize ()
uint32_t GetMaximumNumberOfChildrenToDisplay () const
Gets the target.max-children-count value It should be used to limit the number of children of large data structures to be displayed.
lldb::SBError SetSectionLoadAddress (lldb::SBSection section, lldb::addr_t section_base_addr)
Set the base load address for a module section.
lldb::SBError ClearSectionLoadAddress (lldb::SBSection section)
Clear the base load address for a module section.
LLDB_DEPRECATED_FIXME("Use SetModuleLoadAddress(lldb::SBModule, uint64_t)", "SetModuleLoadAddress(lldb::SBModule, uint64_t)") lldb lldb::SBError SetModuleLoadAddress (lldb::SBModule module, uint64_t sections_offset)
Slide all file addresses for all module sections so that module appears to loaded at these slide addresses.
lldb::SBError ClearModuleLoadAddress (lldb::SBModule module)
Clear the section base load addresses for all sections in a module.
lldb::SBSymbolContextList FindFunctions (const char *name, uint32_t name_type_mask=lldb::eFunctionNameTypeAny)
Find functions by name.
lldb::SBValueList FindGlobalVariables (const char *name, uint32_t max_matches)
Find global and static variables by name.
lldb::SBValue FindFirstGlobalVariable (const char *name)
Find the first global (or static) variable by name.
lldb::SBValueList FindGlobalVariables (const char *name, uint32_t max_matches, MatchType matchtype)
Find global and static variables by pattern.
lldb::SBSymbolContextList FindGlobalFunctions (const char *name, uint32_t max_matches, MatchType matchtype)
Find global functions by their name with pattern matching.
void Clear ()
lldb::SBAddress ResolveFileAddress (lldb::addr_t file_addr)
Resolve a current file address into a section offset address.
lldb::SBAddress ResolveLoadAddress (lldb::addr_t vm_addr)
Resolve a current load address into a section offset address.
lldb::SBAddress ResolvePastLoadAddress (uint32_t stop_id, lldb::addr_t vm_addr)
Resolve a current load address into a section offset address using the process stop ID to identify a time in the past.
SBSymbolContext ResolveSymbolContextForAddress (const SBAddress &addr, uint32_t resolve_scope)
size_t ReadMemory (const SBAddress addr, void *buf, size_t size, lldb::SBError &error)
Read target memory.
lldb::SBBreakpoint BreakpointCreateByLocation (const char *file, uint32_t line)
lldb::SBBreakpoint BreakpointCreateByLocation (const lldb::SBFileSpec &file_spec, uint32_t line)
lldb::SBBreakpoint BreakpointCreateByLocation (const lldb::SBFileSpec &file_spec, uint32_t line, lldb::addr_t offset)
lldb::SBBreakpoint BreakpointCreateByLocation (const lldb::SBFileSpec &file_spec, uint32_t line, lldb::addr_t offset, SBFileSpecList &module_list)
lldb::SBBreakpoint BreakpointCreateByLocation (const lldb::SBFileSpec &file_spec, uint32_t line, uint32_t column, lldb::addr_t offset, SBFileSpecList &module_list)
lldb::SBBreakpoint BreakpointCreateByLocation (const lldb::SBFileSpec &file_spec, uint32_t line, uint32_t column, lldb::addr_t offset, SBFileSpecList &module_list, bool move_to_nearest_code)
lldb::SBBreakpoint BreakpointCreateByName (const char *symbol_name, const char *module_name=nullptr)
lldb::SBBreakpoint BreakpointCreateByName (const char *symbol_name, const SBFileSpecList &module_list, const SBFileSpecList &comp_unit_list)
lldb::SBBreakpoint BreakpointCreateByName (const char *symbol_name, uint32_t name_type_mask, const SBFileSpecList &module_list, const SBFileSpecList &comp_unit_list)
lldb::SBBreakpoint BreakpointCreateByName (const char *symbol_name, uint32_t name_type_mask, lldb::LanguageType symbol_language, const SBFileSpecList &module_list, const SBFileSpecList &comp_unit_list)
lldb::SBBreakpoint BreakpointCreateByName (const char *symbol_name, uint32_t name_type_mask, lldb::LanguageType symbol_language, lldb::addr_t offset, bool offset_is_insn_count, const SBFileSpecList &module_list, const SBFileSpecList &comp_unit_list)
lldb::SBBreakpoint BreakpointCreateByNames (const char *symbol_name[], uint32_t num_names, uint32_t name_type_mask, const SBFileSpecList &module_list, const SBFileSpecList &comp_unit_list)
lldb::SBBreakpoint BreakpointCreateByNames (const char *symbol_name[], uint32_t num_names, uint32_t name_type_mask, lldb::LanguageType symbol_language, const SBFileSpecList &module_list, const SBFileSpecList &comp_unit_list)
lldb::SBBreakpoint BreakpointCreateByNames (const char *symbol_name[], uint32_t num_names, uint32_t name_type_mask, lldb::LanguageType symbol_language, lldb::addr_t offset, const SBFileSpecList &module_list, const SBFileSpecList &comp_unit_list)
lldb::SBBreakpoint BreakpointCreateByRegex (const char *symbol_name_regex, const char *module_name=nullptr)
lldb::SBBreakpoint BreakpointCreateByRegex (const char *symbol_name_regex, const SBFileSpecList &module_list, const SBFileSpecList &comp_unit_list)
lldb::SBBreakpoint BreakpointCreateByRegex (const char *symbol_name_regex, lldb::LanguageType symbol_language, const SBFileSpecList &module_list, const SBFileSpecList &comp_unit_list)
lldb::SBBreakpoint BreakpointCreateBySourceRegex (const char *source_regex, const SBFileSpec &source_file, const char *module_name=nullptr)
lldb::SBBreakpoint BreakpointCreateBySourceRegex (const char *source_regex, const SBFileSpecList &module_list, const SBFileSpecList &source_file)
lldb::SBBreakpoint BreakpointCreateBySourceRegex (const char *source_regex, const SBFileSpecList &module_list, const SBFileSpecList &source_file, const SBStringList &func_names)
lldb::SBBreakpoint BreakpointCreateForException (lldb::LanguageType language, bool catch_bp, bool throw_bp)
lldb::SBBreakpoint BreakpointCreateByAddress (addr_t address)
lldb::SBBreakpoint BreakpointCreateBySBAddress (SBAddress &address)
lldb::SBBreakpoint BreakpointCreateFromScript (const char *class_name, SBStructuredData &extra_args, const SBFileSpecList &module_list, const SBFileSpecList &file_list, bool request_hardware=false)
Create a breakpoint using a scripted resolver.
lldb::SBError BreakpointsCreateFromFile (SBFileSpec &source_file, SBBreakpointList &new_bps)
Read breakpoints from source_file and return the newly created breakpoints in bkpt_list.
lldb::SBError BreakpointsCreateFromFile (SBFileSpec &source_file, SBStringList &matching_names, SBBreakpointList &new_bps)
Read breakpoints from source_file and return the newly created breakpoints in bkpt_list.
lldb::SBError BreakpointsWriteToFile (SBFileSpec &dest_file)
Write breakpoints to dest_file.
lldb::SBError BreakpointsWriteToFile (SBFileSpec &dest_file, SBBreakpointList &bkpt_list, bool append=false)
Write breakpoints listed in bkpt_list to dest_file.
uint32_t GetNumBreakpoints () const
lldb::SBBreakpoint GetBreakpointAtIndex (uint32_t idx) const
bool BreakpointDelete (break_id_t break_id)
lldb::SBBreakpoint FindBreakpointByID (break_id_t break_id)
bool FindBreakpointsByName (const char *name, SBBreakpointList &bkpt_list)
void GetBreakpointNames (SBStringList &names)
void DeleteBreakpointName (const char *name)
bool EnableAllBreakpoints ()
bool DisableAllBreakpoints ()
bool DeleteAllBreakpoints ()
uint32_t GetNumWatchpoints () const
lldb::SBWatchpoint GetWatchpointAtIndex (uint32_t idx) const
bool DeleteWatchpoint (lldb::watch_id_t watch_id)
lldb::SBWatchpoint FindWatchpointByID (lldb::watch_id_t watch_id)
lldb::SBWatchpoint WatchAddress (lldb::addr_t addr, size_t size, bool read, bool modify, SBError &error)
lldb::SBWatchpoint WatchpointCreateByAddress (lldb::addr_t addr, size_t size, lldb::SBWatchpointOptions options, SBError &error)
bool EnableAllWatchpoints ()
bool DisableAllWatchpoints ()
bool DeleteAllWatchpoints ()
lldb::SBBroadcaster GetBroadcaster () const
lldb::SBType FindFirstType (const char *type)
lldb::SBTypeList FindTypes (const char *type)
lldb::SBType GetBasicType (lldb::BasicType type)
lldb::SBValue CreateValueFromAddress (const char *name, lldb::SBAddress addr, lldb::SBType type)
lldb::SBValue CreateValueFromData (const char *name, lldb::SBData data, lldb::SBType type)
lldb::SBValue CreateValueFromExpression (const char *name, const char *expr)
SBSourceManager GetSourceManager ()
lldb::SBInstructionList ReadInstructions (lldb::SBAddress base_addr, uint32_t count)
lldb::SBInstructionList ReadInstructions (lldb::SBAddress base_addr, uint32_t count, const char *flavor_string)
lldb::SBInstructionList ReadInstructions (lldb::SBAddress start_addr, lldb::SBAddress end_addr, const char *flavor_string)
lldb::SBInstructionList GetInstructions (lldb::SBAddress base_addr, const void *buf, size_t size)
lldb::SBInstructionList GetInstructionsWithFlavor (lldb::SBAddress base_addr, const char *flavor_string, const void *buf, size_t size)
lldb::SBInstructionList GetInstructions (lldb::addr_t base_addr, const void *buf, size_t size)
lldb::SBInstructionList GetInstructionsWithFlavor (lldb::addr_t base_addr, const char *flavor_string, const void *buf, size_t size)
lldb::SBSymbolContextList FindSymbols (const char *name, lldb::SymbolType type=eSymbolTypeAny)
bool operator== (const lldb::SBTarget &rhs) const
bool operator!= (const lldb::SBTarget &rhs) const
bool GetDescription (lldb::SBStream &description, lldb::DescriptionLevel description_level)
lldb::SBValue EvaluateExpression (const char *expr)
lldb::SBValue EvaluateExpression (const char *expr, const SBExpressionOptions &options)
lldb::addr_t GetStackRedZoneSize ()
bool IsLoaded (const lldb::SBModule &module) const
lldb::SBLaunchInfo GetLaunchInfo () const
void SetLaunchInfo (const lldb::SBLaunchInfo &launch_info)
lldb::SBTrace GetTrace ()
Get a SBTrace object the can manage the processor trace information of this target.
lldb::SBTrace CreateTrace (SBError &error)
Create a Trace object for the current target using the using the default supported tracing technology for this process.
lldb::SBMutex GetAPIMutex () const
uint32_t RegisterScriptedFrameProvider (const char *class_name, lldb::SBStructuredData args_dict, lldb::SBError &error)
Register a scripted frame provider for this target.
lldb::SBError RemoveScriptedFrameProvider (uint32_t provider_id)
Remove a scripted frame provider from this target by name.
Static Public Member Functions
static bool EventIsTargetEvent (const lldb::SBEvent &event)
static lldb::SBTarget GetTargetFromEvent (const lldb::SBEvent &event)
static lldb::SBTarget GetCreatedTargetFromEvent (const lldb::SBEvent &event)
For eBroadcastBitNewTargetCreated events, returns the newly created target.
static uint32_t GetNumModulesFromEvent (const lldb::SBEvent &event)
static lldb::SBModule GetModuleAtIndexFromEvent (const uint32_t idx, const lldb::SBEvent &event)
static const char * GetBroadcasterClassName ()
Protected Member Functions
SBTarget (const lldb::TargetSP &target_sp)
lldb::TargetSP GetSP () const
void SetSP (const lldb::TargetSP &target_sp)
Private Attributes
lldb::TargetSP m_opaque_sp
Friends
class SBAddress
class SBAddressRange
class SBBlock
class SBBreakpoint
class SBBreakpointList
class SBBreakpointNameImpl
class SBDebugger
class SBExecutionContext
class SBFrame
class SBFunction
class SBInstruction
class SBModule
class SBModuleSpec
class SBPlatform
class SBProcess
class SBSection
class SBSourceManager
class SBSymbol
class SBType
class SBTypeStaticField
class SBValue
class SBVariablesOptions
class lldb_private::python::SWIGBridge
Detailed Description
Definition at line 38 of file SBTarget.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
eBroadcastBitBreakpointChanged
eBroadcastBitModulesLoaded
eBroadcastBitModulesUnloaded
eBroadcastBitWatchpointChanged
eBroadcastBitSymbolsLoaded
eBroadcastBitSymbolsChanged
eBroadcastBitNewTargetCreated
Definition at line 41 of file SBTarget.h.
Constructor & Destructor Documentation
SBTarget() [1/3]
SBTarget::SBTarget ()
Definition at line 102 of file SBTarget.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by GetCreatedTargetFromEvent(), GetTargetFromEvent(), lldb_private::python::SWIGBridge, operator!=(), operator=(), operator==(), and SBTarget().
SBTarget() [2/3]
SBTarget::SBTarget (const lldb::SBTarget & rhs)
Definition at line 104 of file SBTarget.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBTarget().
~SBTarget()
SBTarget::~SBTarget () default
References AddModule(), AppendImageSearchPath(), Attach(), AttachToProcessWithID(), AttachToProcessWithName(), BreakpointCreateByAddress(), BreakpointCreateByLocation(), BreakpointCreateByName(), BreakpointCreateByNames(), BreakpointCreateByRegex(), BreakpointCreateBySBAddress(), BreakpointCreateBySourceRegex(), BreakpointCreateForException(), BreakpointCreateFromScript(), BreakpointDelete(), BreakpointsCreateFromFile(), BreakpointsWriteToFile(), Clear(), ClearModuleLoadAddress(), ClearSectionLoadAddress(), ConnectRemote(), CreateTrace(), CreateValueFromAddress(), CreateValueFromData(), CreateValueFromExpression(), DeleteAllBreakpoints(), DeleteAllWatchpoints(), DeleteBreakpointName(), DeleteWatchpoint(), DisableAllBreakpoints(), DisableAllWatchpoints(), EnableAllBreakpoints(), EnableAllWatchpoints(), error(), lldb::eSymbolTypeAny, EventIsTargetEvent(), FindBreakpointByID(), FindBreakpointsByName(), FindCompileUnits(), FindFirstGlobalVariable(), FindFirstType(), FindFunctions(), FindGlobalFunctions(), FindGlobalVariables(), FindModule(), FindSymbols(), FindTypes(), FindWatchpointByID(), GetABIName(), GetAddressByteSize(), GetAPIMutex(), GetArchName(), GetBasicType(), GetBreakpointAtIndex(), GetBreakpointNames(), GetBroadcaster(), GetBroadcasterClassName(), GetByteOrder(), GetCodeByteSize(), GetCollectingStats(), GetCreatedTargetFromEvent(), GetDataByteSize(), GetDebugger(), GetDescription(), GetEnvironment(), GetExecutable(), GetGloballyUniqueID(), GetInstructions(), GetInstructionsWithFlavor(), GetLabel(), GetLaunchInfo(), GetMaximumNumberOfChildrenToDisplay(), GetMaximumOpcodeByteSize(), GetMinimumOpcodeByteSize(), GetModuleAtIndex(), GetModuleAtIndexFromEvent(), GetNumBreakpoints(), GetNumModules(), GetNumModulesFromEvent(), GetNumWatchpoints(), GetPlatform(), GetProcess(), GetSourceManager(), GetStackRedZoneSize(), GetStatistics(), GetTargetFromEvent(), GetTargetSessionName(), GetTrace(), GetTriple(), GetWatchpointAtIndex(), Install(), IsLoaded(), IsValid(), Launch(), LaunchSimple(), LLDB_DEPRECATED, LoadCore(), operator!=(), operator=(), operator==(), ReadInstructions(), ReadMemory(), RegisterScriptedFrameProvider(), RemoveModule(), RemoveScriptedFrameProvider(), ResetStatistics(), ResolveFileAddress(), ResolvePastLoadAddress(), ResolveSymbolContextForAddress(), SBAddress, SBBreakpointList, SBModule, SBModuleSpec, SBProcess, SBSection, SBSourceManager, SBType, SBValue, SetCollectingStats(), SetLabel(), SetLaunchInfo(), SetModuleLoadAddress(), SetSectionLoadAddress(), WatchAddress(), and WatchpointCreateByAddress().
SBTarget() [3/3]
SBTarget::SBTarget (const lldb::TargetSP & target_sp) protected
Definition at line 108 of file SBTarget.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Member Function Documentation
AddModule() [1/4]
lldb::SBModule SBTarget::AddModule (const char * path, const char * triple, const char * uuid)
Definition at line 1480 of file SBTarget.cpp.
References AddModule(), and LLDB_INSTRUMENT_VA.
AddModule() [2/4]
lldb::SBModule SBTarget::AddModule (const char * path, const char * triple, const char * uuid_cstr, const char * symfile)
Definition at line 1487 of file SBTarget.cpp.
References AddModule(), lldb_private::ModuleSpec::GetArchitecture(), lldb_private::Platform::GetAugmentedArchSpec(), lldb_private::ModuleSpec::GetFileSpec(), GetSP(), lldb_private::ModuleSpec::GetSymbolFileSpec(), lldb_private::ModuleSpec::GetUUID(), LLDB_INSTRUMENT_VA, SBModule, SBModuleSpec, lldb_private::FileSpec::SetFile(), and lldb_private::UUID::SetFromStringRef().
AddModule() [3/4]
lldb::SBModule SBTarget::AddModule (const SBModuleSpec & module_spec)
Definition at line 1515 of file SBTarget.cpp.
References lldb_private::PluginManager::DownloadObjectAndSymbolFile(), error(), lldb::SBModule::GetSP(), GetSP(), lldb_private::FileSystem::Instance(), lldb::SBModule::IsValid(), LLDB_INSTRUMENT_VA, lldb::SBModuleSpec::m_opaque_up, SBModuleSpec, and lldb::SBModule::SetSP().
AddModule() [4/4]
bool SBTarget::AddModule (lldb::SBModule & module)
Definition at line 1544 of file SBTarget.cpp.
References lldb::SBModule::GetSP(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by AddModule(), AddModule(), and ~SBTarget().
AppendImageSearchPath()
void SBTarget::AppendImageSearchPath (const char * from, const char * to, lldb::SBError & error)
Definition at line 1463 of file SBTarget.cpp.
References error(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
Attach()
lldb::SBProcess SBTarget::Attach (SBAttachInfo & attach_info, SBError & error)
Definition at line 443 of file SBTarget.cpp.
References AttachToProcess(), error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::ProcessInstanceInfo::GetEffectiveUserID(), lldb_private::ProcessInfo::GetProcessID(), GetSP(), lldb_private::ProcessInfo::IsScriptedProcess(), LLDB_INSTRUMENT_VA, lldb_private::ProcessInfo::ProcessIDIsValid(), lldb::SBAttachInfo::ref(), SBProcess, lldb::SBProcess::SetSP(), lldb_private::ProcessInfo::SetUserID(), and lldb_private::ProcessInfo::UserIDIsValid().
Referenced by ~SBTarget().
AttachToProcessWithID()
lldb::SBProcess SBTarget::AttachToProcessWithID (SBListener & listener, lldb::pid_t pid, lldb::SBError & error)
Attach to process with pid.
Parameters
[in] listener An optional listener that will receive all process events. If listener is valid then listener will listen to all process events. If not valid, then this target's debugger (SBTarget::GetDebugger()) will listen to all process events.
[in] pid The process ID to attach to.
[out] error An error explaining what went wrong if attach fails.
Returns
A process object for the attached process.
Definition at line 475 of file SBTarget.cpp.
References AttachToProcess(), error(), lldb_private::ProcessInstanceInfo::GetEffectiveUserID(), lldb::SBListener::GetSP(), GetSP(), lldb::SBListener::IsValid(), LLDB_INSTRUMENT_VA, SBProcess, lldb_private::ProcessInfo::SetListener(), lldb_private::ProcessInfo::SetProcessID(), lldb::SBProcess::SetSP(), and lldb_private::ProcessInfo::SetUserID().
Referenced by ~SBTarget().
AttachToProcessWithName()
lldb::SBProcess SBTarget::AttachToProcessWithName (SBListener & listener, const char * name, bool wait_for, lldb::SBError & error)
Attach to process with name.
Parameters
[in] listener An optional listener that will receive all process events. If listener is valid then listener will listen to all process events. If not valid, then this target's debugger (SBTarget::GetDebugger()) will listen to all process events.
[in] name Basename of process to attach to.
[in] wait_for If true wait for a new instance of 'name' to be launched.
[out] error An error explaining what went wrong if attach fails.
Returns
A process object for the attached process.
Definition at line 502 of file SBTarget.cpp.
References AttachToProcess(), error(), lldb_private::ProcessInfo::GetExecutableFile(), lldb::SBListener::GetSP(), GetSP(), lldb::SBListener::IsValid(), LLDB_INSTRUMENT_VA, SBProcess, lldb_private::FileSpec::SetFile(), lldb_private::ProcessInfo::SetListener(), lldb::SBProcess::SetSP(), and lldb_private::ProcessAttachInfo::SetWaitForLaunch().
Referenced by ~SBTarget().
BreakpointCreateByAddress()
SBBreakpoint SBTarget::BreakpointCreateByAddress (addr_t address)
Definition at line 948 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and SBBreakpoint.
Referenced by ~SBTarget().
BreakpointCreateByLocation() [1/6]
SBBreakpoint SBTarget::BreakpointCreateByLocation (const char * file, uint32_t line)
Definition at line 679 of file SBTarget.cpp.
References BreakpointCreateByLocation(), LLDB_INSTRUMENT_VA, SBBreakpoint, and lldb::SBFileSpec.
Referenced by BreakpointCreateByLocation(), BreakpointCreateByLocation(), BreakpointCreateByLocation(), BreakpointCreateByLocation(), and ~SBTarget().
BreakpointCreateByLocation() [2/6]
SBBreakpoint SBTarget::BreakpointCreateByLocation (const lldb::SBFileSpec & file_spec, uint32_t line)
Definition at line 688 of file SBTarget.cpp.
References BreakpointCreateByLocation(), and LLDB_INSTRUMENT_VA.
BreakpointCreateByLocation() [3/6]
SBBreakpoint SBTarget::BreakpointCreateByLocation (const lldb::SBFileSpec & file_spec, uint32_t line, lldb::addr_t offset)
Definition at line 696 of file SBTarget.cpp.
References BreakpointCreateByLocation(), and LLDB_INSTRUMENT_VA.
BreakpointCreateByLocation() [4/6]
SBBreakpoint SBTarget::BreakpointCreateByLocation (const lldb::SBFileSpec & file_spec, uint32_t line, lldb::addr_t offset, SBFileSpecList & module_list)
Definition at line 705 of file SBTarget.cpp.
References BreakpointCreateByLocation(), and LLDB_INSTRUMENT_VA.
BreakpointCreateByLocation() [5/6]
SBBreakpoint SBTarget::BreakpointCreateByLocation (const lldb::SBFileSpec & file_spec, uint32_t line, uint32_t column, lldb::addr_t offset, SBFileSpecList & module_list)
Definition at line 714 of file SBTarget.cpp.
References lldb_private::eLazyBoolCalculate, lldb::SBFileSpecList::get(), lldb::SBFileSpecList::GetSize(), GetSP(), LLDB_INSTRUMENT_VA, and SBBreakpoint.
BreakpointCreateByLocation() [6/6]
SBBreakpoint SBTarget::BreakpointCreateByLocation (const lldb::SBFileSpec & file_spec, uint32_t line, uint32_t column, lldb::addr_t offset, SBFileSpecList & module_list, bool move_to_nearest_code)
Definition at line 740 of file SBTarget.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb::SBFileSpecList::get(), lldb::SBFileSpecList::GetSize(), GetSP(), LLDB_INSTRUMENT_VA, and SBBreakpoint.
BreakpointCreateByName() [1/5]
SBBreakpoint SBTarget::BreakpointCreateByName (const char * symbol_name, const char * module_name = nullptr)
Definition at line 768 of file SBTarget.cpp.
References lldb_private::FileSpecList::Append(), lldb::eLanguageTypeUnknown, lldb_private::eLazyBoolCalculate, GetSP(), LLDB_INSTRUMENT_VA, and SBBreakpoint.
Referenced by BreakpointCreateByName(), BreakpointCreateByName(), BreakpointCreateByName(), and ~SBTarget().
BreakpointCreateByName() [2/5]
lldb::SBBreakpoint SBTarget::BreakpointCreateByName (const char * symbol_name, const SBFileSpecList & module_list, const SBFileSpecList & comp_unit_list)
Definition at line 800 of file SBTarget.cpp.
References BreakpointCreateByName(), lldb::eLanguageTypeUnknown, and LLDB_INSTRUMENT_VA.
BreakpointCreateByName() [3/5]
lldb::SBBreakpoint SBTarget::BreakpointCreateByName (const char * symbol_name, uint32_t name_type_mask, const SBFileSpecList & module_list, const SBFileSpecList & comp_unit_list)
Definition at line 811 of file SBTarget.cpp.
References BreakpointCreateByName(), lldb::eLanguageTypeUnknown, and LLDB_INSTRUMENT_VA.
BreakpointCreateByName() [4/5]
lldb::SBBreakpoint SBTarget::BreakpointCreateByName (const char * symbol_name, uint32_t name_type_mask, lldb::LanguageType symbol_language, const SBFileSpecList & module_list, const SBFileSpecList & comp_unit_list)
Definition at line 822 of file SBTarget.cpp.
References BreakpointCreateByName(), and LLDB_INSTRUMENT_VA.
BreakpointCreateByName() [5/5]
lldb::SBBreakpoint SBTarget::BreakpointCreateByName (const char * symbol_name, uint32_t name_type_mask, lldb::LanguageType symbol_language, lldb::addr_t offset, bool offset_is_insn_count, const SBFileSpecList & module_list, const SBFileSpecList & comp_unit_list)
Definition at line 832 of file SBTarget.cpp.
References lldb_private::eLazyBoolCalculate, lldb::SBFileSpecList::get(), GetSP(), LLDB_INSTRUMENT_VA, and SBBreakpoint.
BreakpointCreateByNames() [1/3]
lldb::SBBreakpoint SBTarget::BreakpointCreateByNames (const char * symbol_name[], uint32_t num_names, uint32_t name_type_mask, const SBFileSpecList & module_list, const SBFileSpecList & comp_unit_list)
Definition at line 857 of file SBTarget.cpp.
References BreakpointCreateByNames(), lldb::eLanguageTypeUnknown, and LLDB_INSTRUMENT_VA.
Referenced by BreakpointCreateByNames(), BreakpointCreateByNames(), and ~SBTarget().
BreakpointCreateByNames() [2/3]
lldb::SBBreakpoint SBTarget::BreakpointCreateByNames (const char * symbol_name[], uint32_t num_names, uint32_t name_type_mask, lldb::LanguageType symbol_language, const SBFileSpecList & module_list, const SBFileSpecList & comp_unit_list)
Definition at line 868 of file SBTarget.cpp.
References BreakpointCreateByNames(), lldb::eLanguageTypeUnknown, and LLDB_INSTRUMENT_VA.
BreakpointCreateByNames() [3/3]
lldb::SBBreakpoint SBTarget::BreakpointCreateByNames (const char * symbol_name[], uint32_t num_names, uint32_t name_type_mask, lldb::LanguageType symbol_language, lldb::addr_t offset, const SBFileSpecList & module_list, const SBFileSpecList & comp_unit_list)
Definition at line 880 of file SBTarget.cpp.
References lldb_private::eLazyBoolCalculate, lldb::SBFileSpecList::get(), GetSP(), LLDB_INSTRUMENT_VA, and SBBreakpoint.
BreakpointCreateByRegex() [1/3]
SBBreakpoint SBTarget::BreakpointCreateByRegex (const char * symbol_name_regex, const char * module_name = nullptr)
Definition at line 902 of file SBTarget.cpp.
References lldb::SBFileSpecList::Append(), BreakpointCreateByRegex(), lldb::eLanguageTypeUnknown, LLDB_INSTRUMENT_VA, and SBBreakpoint.
Referenced by BreakpointCreateByRegex(), BreakpointCreateByRegex(), and ~SBTarget().
BreakpointCreateByRegex() [2/3]
lldb::SBBreakpoint SBTarget::BreakpointCreateByRegex (const char * symbol_name_regex, const SBFileSpecList & module_list, const SBFileSpecList & comp_unit_list)
Definition at line 916 of file SBTarget.cpp.
References BreakpointCreateByRegex(), lldb::eLanguageTypeUnknown, and LLDB_INSTRUMENT_VA.
BreakpointCreateByRegex() [3/3]
lldb::SBBreakpoint SBTarget::BreakpointCreateByRegex (const char * symbol_name_regex, lldb::LanguageType symbol_language, const SBFileSpecList & module_list, const SBFileSpecList & comp_unit_list)
Definition at line 925 of file SBTarget.cpp.
References lldb_private::eLazyBoolCalculate, lldb::SBFileSpecList::get(), GetSP(), LLDB_INSTRUMENT_VA, and SBBreakpoint.
BreakpointCreateBySBAddress()
SBBreakpoint SBTarget::BreakpointCreateBySBAddress (SBAddress & address)
Definition at line 961 of file SBTarget.cpp.
References GetSP(), lldb::SBAddress::IsValid(), LLDB_INSTRUMENT_VA, lldb::SBAddress::ref(), SBAddress, and SBBreakpoint.
Referenced by ~SBTarget().
BreakpointCreateBySourceRegex() [1/3]
lldb::SBBreakpoint SBTarget::BreakpointCreateBySourceRegex (const char * source_regex, const SBFileSpec & source_file, const char * module_name = nullptr)
Definition at line 979 of file SBTarget.cpp.
References lldb::SBFileSpecList::Append(), BreakpointCreateBySourceRegex(), lldb::SBFileSpec::IsValid(), and LLDB_INSTRUMENT_VA.
Referenced by BreakpointCreateBySourceRegex(), BreakpointCreateBySourceRegex(), and ~SBTarget().
BreakpointCreateBySourceRegex() [2/3]
lldb::SBBreakpoint SBTarget::BreakpointCreateBySourceRegex (const char * source_regex, const SBFileSpecList & module_list, const SBFileSpecList & source_file)
Definition at line 999 of file SBTarget.cpp.
References BreakpointCreateBySourceRegex(), LLDB_INSTRUMENT_VA, and lldb::SBStringList.
BreakpointCreateBySourceRegex() [3/3]
lldb::SBBreakpoint SBTarget::BreakpointCreateBySourceRegex (const char * source_regex, const SBFileSpecList & module_list, const SBFileSpecList & source_file, const SBStringList & func_names)
Definition at line 1008 of file SBTarget.cpp.
References lldb_private::eLazyBoolCalculate, lldb::SBFileSpecList::get(), lldb::SBStringList::GetSize(), GetSP(), lldb::SBStringList::GetStringAtIndex(), LLDB_INSTRUMENT_VA, and SBBreakpoint.
BreakpointCreateForException()
lldb::SBBreakpoint SBTarget::BreakpointCreateForException (lldb::LanguageType language, bool catch_bp, bool throw_bp)
Definition at line 1036 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and SBBreakpoint.
Referenced by ~SBTarget().
BreakpointCreateFromScript()
lldb::SBBreakpoint SBTarget::BreakpointCreateFromScript (const char * class_name, SBStructuredData & extra_args, const SBFileSpecList & module_list, const SBFileSpecList & file_list, bool request_hardware = false)
Create a breakpoint using a scripted resolver.
Parameters
[in] class_name This is the name of the class that implements a scripted resolver.
[in] extra_args This is an SBStructuredData object that will get passed to the constructor of the class in class_name. You can use this to reuse the same class, parametrizing with entries from this dictionary.
module_list If this is non-empty, this will be used as the module filter in the SearchFilter created for this breakpoint.
file_list If this is non-empty, this will be used as the comp unit filter in the SearchFilter created for this breakpoint.
Returns
An SBBreakpoint that will set locations based on the logic in the resolver's search callback.
Definition at line 1051 of file SBTarget.cpp.
References error(), lldb::SBFileSpecList::get(), GetSP(), LLDB_INSTRUMENT_VA, lldb::SBStructuredData::m_impl_up, and SBBreakpoint.
Referenced by ~SBTarget().
BreakpointDelete()
bool SBTarget::BreakpointDelete (break_id_t break_id)
Definition at line 1098 of file SBTarget.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
BreakpointsCreateFromFile() [1/2]
lldb::SBError SBTarget::BreakpointsCreateFromFile (SBFileSpec & source_file, SBBreakpointList & new_bps)
Read breakpoints from source_file and return the newly created breakpoints in bkpt_list.
Parameters
[in] source_file The file from which to read the breakpoints.
[out] new_bps A list of the newly created breakpoints.
Returns
An SBError detailing any errors in reading in the breakpoints.
Definition at line 1200 of file SBTarget.cpp.
References BreakpointsCreateFromFile(), LLDB_INSTRUMENT_VA, and SBBreakpointList.
Referenced by BreakpointsCreateFromFile(), and ~SBTarget().
BreakpointsCreateFromFile() [2/2]
lldb::SBError SBTarget::BreakpointsCreateFromFile (SBFileSpec & source_file, SBStringList & matching_names, SBBreakpointList & new_bps)
Read breakpoints from source_file and return the newly created breakpoints in bkpt_list.
Parameters
[in] source_file The file from which to read the breakpoints.
[in] matching_names Only read in breakpoints whose names match one of the names in this list.
[out] new_bps A list of the newly created breakpoints.
Returns
An SBError detailing any errors in reading in the breakpoints.
Definition at line 1208 of file SBTarget.cpp.
References lldb::SBBreakpointList::AppendByID(), lldb::SBError::Fail(), lldb_private::BreakpointID::GetBreakpointID(), lldb_private::BreakpointIDList::GetBreakpointIDAtIndex(), lldb::SBStringList::GetSize(), lldb_private::BreakpointIDList::GetSize(), GetSP(), lldb::SBStringList::GetStringAtIndex(), LLDB_INSTRUMENT_VA, lldb::SBError::ref(), lldb::SBFileSpec::ref(), SBBreakpointList, and lldb::SBError::SetErrorString().
BreakpointsWriteToFile() [1/2]
lldb::SBError SBTarget::BreakpointsWriteToFile (SBFileSpec & dest_file)
Write breakpoints to dest_file.
Parameters
[in] dest_file The file to which to write the breakpoints.
Returns
An SBError detailing any errors in writing in the breakpoints.
Definition at line 1241 of file SBTarget.cpp.
References BreakpointsWriteToFile(), GetSP(), LLDB_INSTRUMENT_VA, SBBreakpointList, and lldb::SBError::SetErrorString().
Referenced by BreakpointsWriteToFile(), and ~SBTarget().
BreakpointsWriteToFile() [2/2]
lldb::SBError SBTarget::BreakpointsWriteToFile (SBFileSpec & dest_file, SBBreakpointList & bkpt_list, bool append = false)
Write breakpoints listed in bkpt_list to dest_file.
Parameters
[in] dest_file The file to which to write the breakpoints.
[in] bkpt_list Only write breakpoints from this list.
[in] append If true, append the breakpoints in bkpt_list to the others serialized in dest_file. If dest_file doesn't exist, then a new file will be created and the breakpoints in bkpt_list written to it.
Returns
An SBError detailing any errors in writing in the breakpoints.
Definition at line 1253 of file SBTarget.cpp.
References lldb::SBBreakpointList::CopyToBreakpointIDList(), GetSP(), LLDB_INSTRUMENT_VA, lldb::SBError::ref(), lldb::SBFileSpec::ref(), SBBreakpointList, and lldb::SBError::SetErrorString().
Clear()
void SBTarget::Clear ()
Definition at line 1566 of file SBTarget.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by lldb::SBDebugger::DeleteTarget(), and ~SBTarget().
ClearModuleLoadAddress()
SBError SBTarget::ClearModuleLoadAddress (lldb::SBModule module)
Clear the section base load addresses for all sections in a module.
Parameters
[in] module The module to unload.
Returns
An error to indicate success, fail, and any reason for failure.
Definition at line 2230 of file SBTarget.cpp.
References lldb_private::ModuleList::Append(), lldb_private::SectionList::GetSectionAtIndex(), lldb_private::ObjectFile::GetSectionList(), lldb_private::SectionList::GetSize(), lldb::SBModule::GetSP(), GetSP(), LLDB_INSTRUMENT_VA, and PATH_MAX.
Referenced by ~SBTarget().
ClearSectionLoadAddress()
SBError SBTarget::ClearSectionLoadAddress (lldb::SBSection section)
Clear the base load address for a module section.
Parameters
[in] section The section whose base load address will be cleared within this target.
Returns
An error to indicate success, fail, and any reason for failure.
Definition at line 2152 of file SBTarget.cpp.
References lldb_private::ModuleList::Append(), lldb::SBSection::GetSP(), GetSP(), lldb::SBSection::IsValid(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
ConnectRemote()
lldb::SBProcess SBTarget::ConnectRemote (SBListener & listener, const char * url, const char * plugin_name, SBError & error)
Connect to a remote debug server with url.
Parameters
[in] listener An optional listener that will receive all process events. If listener is valid then listener will listen to all process events. If not valid, then this target's debugger (SBTarget::GetDebugger()) will listen to all process events.
[in] url The url to connect to, e.g., 'connect://localhost:12345'.
[in] plugin_name The plugin name to be used; can be nullptr.
[out] error An error explaining what went wrong if the connect fails.
Returns
A process object for the connected process.
Definition at line 534 of file SBTarget.cpp.
References error(), GetSP(), lldb::SBListener::IsValid(), LLDB_INSTRUMENT_VA, lldb::SBListener::m_opaque_sp, SBProcess, and lldb::SBProcess::SetSP().
Referenced by ~SBTarget().
CreateTrace()
lldb::SBTrace SBTarget::CreateTrace (lldb::SBError & error)
Create a Trace object for the current target using the using the default supported tracing technology for this process.
Parameters
[out] error An error if a Trace already exists or the trace couldn't be created.
Definition at line 2415 of file SBTarget.cpp.
References error(), GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBTrace.
Referenced by ~SBTarget().
CreateValueFromAddress()
SBValue SBTarget::CreateValueFromAddress (const char * name, lldb::SBAddress addr, lldb::SBType type)
Definition at line 1398 of file SBTarget.cpp.
References lldb_private::ValueObject::CreateValueObjectFromAddress(), lldb::SBAddress::GetLoadAddress(), lldb::SBType::GetSP(), lldb::SBAddress::IsValid(), IsValid(), lldb::SBType::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, SBAddress, SBType, SBValue, and lldb::SBValue::SetSP().
Referenced by ~SBTarget().
CreateValueFromData()
lldb::SBValue SBTarget::CreateValueFromData (const char * name, lldb::SBData data, lldb::SBType type)
Definition at line 1416 of file SBTarget.cpp.
References lldb_private::ValueObject::CreateValueObjectFromData(), lldb::SBType::GetSP(), lldb::SBData::IsValid(), IsValid(), lldb::SBType::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, SBValue, and lldb::SBValue::SetSP().
Referenced by ~SBTarget().
CreateValueFromExpression()
lldb::SBValue SBTarget::CreateValueFromExpression (const char * name, const char * expr)
Definition at line 1434 of file SBTarget.cpp.
References lldb_private::ValueObject::CreateValueObjectFromExpression(), IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, SBValue, and lldb::SBValue::SetSP().
Referenced by ~SBTarget().
DeleteAllBreakpoints()
bool SBTarget::DeleteAllBreakpoints ()
Definition at line 1189 of file SBTarget.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
DeleteAllWatchpoints()
bool SBTarget::DeleteAllWatchpoints ()
Definition at line 1450 of file SBTarget.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
DeleteBreakpointName()
void SBTarget::DeleteBreakpointName (const char * name)
Definition at line 1158 of file SBTarget.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
DeleteWatchpoint()
bool SBTarget::DeleteWatchpoint (lldb::watch_id_t watch_id)
Definition at line 1292 of file SBTarget.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
DisableAllBreakpoints()
bool SBTarget::DisableAllBreakpoints ()
Definition at line 1178 of file SBTarget.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
DisableAllWatchpoints()
bool SBTarget::DisableAllWatchpoints ()
Definition at line 1385 of file SBTarget.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
EnableAllBreakpoints()
bool SBTarget::EnableAllBreakpoints ()
Definition at line 1167 of file SBTarget.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
EnableAllWatchpoints()
bool SBTarget::EnableAllWatchpoints ()
Definition at line 1372 of file SBTarget.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
EvaluateExpression() [1/2]
lldb::SBValue SBTarget::EvaluateExpression (const char * expr)
Definition at line 2294 of file SBTarget.cpp.
References EvaluateExpression(), GetSP(), LLDB_INSTRUMENT_VA, SBValue, lldb::SBExpressionOptions::SetFetchDynamicValue(), and lldb::SBExpressionOptions::SetUnwindOnError().
Referenced by EvaluateExpression().
EvaluateExpression() [2/2]
lldb::SBValue SBTarget::EvaluateExpression (const char * expr, const SBExpressionOptions & options)
Definition at line 2308 of file SBTarget.cpp.
References lldb_private::ValueObjectConstResult::Create(), error(), lldb_private::Target::EvaluateExpression(), lldb_private::Expressions, lldb_private::Status::FromErrorString(), lldb::SBExpressionOptions::GetFetchDynamicValue(), lldb_private::ExecutionContext::GetFramePtr(), lldb_private::GetLog(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::Process::GetRunLock(), GetSP(), lldb::SBValue::GetSummary(), lldb_private::ExecutionContext::GetTargetPtr(), lldb::SBValue::GetValue(), LLDB_INSTRUMENT_VA, LLDB_LOGF, m_opaque_sp, lldb::SBExpressionOptions::ref(), SBValue, lldb::SBValue::SetSP(), and lldb_private::ProcessRunLock::ProcessRunLocker::TryLock().
EventIsTargetEvent()
bool SBTarget::EventIsTargetEvent (const lldb::SBEvent & event) static
Definition at line 123 of file SBTarget.cpp.
References lldb::SBEvent::get(), lldb_private::Target::TargetEventData::GetEventDataFromEvent(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
FindBreakpointByID()
SBBreakpoint SBTarget::FindBreakpointByID (break_id_t break_id)
Definition at line 1110 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, LLDB_INVALID_BREAK_ID, and SBBreakpoint.
Referenced by ~SBTarget().
FindBreakpointsByName()
bool SBTarget::FindBreakpointsByName (const char * name, SBBreakpointList & bkpt_list)
Definition at line 1123 of file SBTarget.cpp.
References lldb::SBBreakpointList::AppendByID(), lldb_private::Breakpoints, lldb_private::GetLog(), GetSP(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and SBBreakpointList.
Referenced by ~SBTarget().
FindCompileUnits()
SBSymbolContextList SBTarget::FindCompileUnits (const lldb::SBFileSpec & sb_file_spec)
Find compile units related to *this target and passed source file.
Parameters
[in] sb_file_spec A lldb::SBFileSpec object that contains source file specification.
Returns
A lldb::SBSymbolContextList that gets filled in with all of the symbol contexts for all the matches.
Definition at line 1596 of file SBTarget.cpp.
References GetSP(), lldb::SBFileSpec::IsValid(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
FindFirstGlobalVariable()
lldb::SBValue SBTarget::FindFirstGlobalVariable (const char * name)
Find the first global (or static) variable by name.
Parameters
[in] name The name of the global or static variable we are looking for.
Returns
An SBValue that gets filled in with the found variable (if any).
Definition at line 1989 of file SBTarget.cpp.
References FindGlobalVariables(), lldb::SBValueList::GetSize(), lldb::SBValueList::GetValueAtIndex(), lldb::SBValueList::IsValid(), LLDB_INSTRUMENT_VA, and SBValue.
Referenced by ~SBTarget().
FindFirstType()
lldb::SBType SBTarget::FindFirstType (const char * type)
Definition at line 1835 of file SBTarget.cpp.
References lldb_private::TypeResults::GetFirstType(), GetSP(), lldb_private::ConstString::GetStringRef(), LLDB_INSTRUMENT_VA, and SBType.
Referenced by ~SBTarget().
FindFunctions()
lldb::SBSymbolContextList SBTarget::FindFunctions (const char * name, uint32_t name_type_mask = lldb::eFunctionNameTypeAny)
Find functions by name.
Parameters
[in] name The name of the function we are looking for.
[in] name_type_mask A logical OR of one or more FunctionNameType enum bits that indicate what kind of names should be used when doing the lookup. Bits include fully qualified names, base names, C++ methods, or ObjC selectors. See FunctionNameType for more details.
Returns
A lldb::SBSymbolContextList that gets filled in with all of the symbol contexts for all the matches.
Definition at line 1775 of file SBTarget.cpp.
References GetSP(), lldb_private::ModuleFunctionSearchOptions::include_inlines, lldb_private::ModuleFunctionSearchOptions::include_symbols, and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
FindGlobalFunctions()
lldb::SBSymbolContextList SBTarget::FindGlobalFunctions (const char * name, uint32_t max_matches, MatchType matchtype)
Find global functions by their name with pattern matching.
Parameters
[in] name The pattern to search for global or static variables
[in] max_matches Allow the number of matches to be limited to max_matches.
[in] matchtype The match type to use.
Returns
A list of matched variables in an SBValueList.
Definition at line 1795 of file SBTarget.cpp.
References lldb::eMatchTypeRegex, lldb::eMatchTypeRegexInsensitive, lldb::eMatchTypeStartsWith, GetSP(), lldb_private::ModuleFunctionSearchOptions::include_inlines, lldb_private::ModuleFunctionSearchOptions::include_symbols, LLDB_INSTRUMENT_VA, and lldb_private::RegularExpression.
Referenced by ~SBTarget().
FindGlobalVariables() [1/2]
SBValueList SBTarget::FindGlobalVariables (const char * name, uint32_t max_matches)
Find global and static variables by name.
Parameters
[in] name The name of the global or static variable we are looking for.
[in] max_matches Allow the number of matches to be limited to max_matches.
Returns
A list of matched variables in an SBValueList.
Definition at line 1915 of file SBTarget.cpp.
References lldb::SBValueList::Append(), lldb_private::ValueObjectVariable::Create(), lldb_private::VariableList::Empty(), GetSP(), LLDB_INSTRUMENT_VA, and SBValue.
Referenced by FindFirstGlobalVariable(), and ~SBTarget().
FindGlobalVariables() [2/2]
SBValueList SBTarget::FindGlobalVariables (const char * name, uint32_t max_matches, MatchType matchtype)
Find global and static variables by pattern.
Parameters
[in] name The pattern to search for global or static variables
[in] max_matches Allow the number of matches to be limited to max_matches.
[in] matchtype The match type to use.
Returns
A list of matched variables in an SBValueList.
Definition at line 1941 of file SBTarget.cpp.
References lldb::SBValueList::Append(), lldb_private::ValueObjectVariable::Create(), lldb::eMatchTypeNormal, lldb::eMatchTypeRegex, lldb::eMatchTypeRegexInsensitive, lldb::eMatchTypeStartsWith, lldb_private::VariableList::Empty(), GetSP(), LLDB_INSTRUMENT_VA, lldb_private::RegularExpression, and SBValue.
FindModule() [1/2]
SBModule SBTarget::FindModule (const lldb::SBFileSpec & file_spec)
Definition at line 1572 of file SBTarget.cpp.
References GetSP(), lldb::SBFileSpec::IsValid(), LLDB_INSTRUMENT_VA, SBModule, and lldb::SBModule::SetSP().
Referenced by ~SBTarget().
FindModule() [2/2]
SBModule SBTarget::FindModule (const lldb::SBModuleSpec & module_spec) const
Find a module with the given module specification.
Parameters
[in] module_spec A lldb::SBModuleSpec object that contains module specification.
Returns
A lldb::SBModule object that represents the found module, or an invalid SBModule object if no module was found.
Definition at line 1584 of file SBTarget.cpp.
References GetSP(), lldb::SBModuleSpec::IsValid(), LLDB_INSTRUMENT_VA, lldb::SBModuleSpec::m_opaque_up, SBModule, SBModuleSpec, and lldb::SBModule::SetSP().
FindSymbols()
lldb::SBSymbolContextList SBTarget::FindSymbols (const char * name, lldb::SymbolType type = eSymbolTypeAny)
Definition at line 2280 of file SBTarget.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
FindTypes()
lldb::SBTypeList SBTarget::FindTypes (const char * type)
Definition at line 1878 of file SBTarget.cpp.
References lldb::SBTypeList::Append(), lldb_private::ModuleList::FindTypes(), lldb::SBTypeList::GetSize(), GetSP(), lldb_private::TypeResults::GetTypeMap(), LLDB_INSTRUMENT_VA, SBType, lldb_private::TypeMap::Types(), and UINT32_MAX.
Referenced by ~SBTarget().
FindWatchpointByID()
SBWatchpoint SBTarget::FindWatchpointByID (lldb::watch_id_t watch_id)
Definition at line 1306 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, LLDB_INVALID_WATCH_ID, and lldb::SBWatchpoint::SetSP().
Referenced by ~SBTarget().
GetABIName()
const char * SBTarget::GetABIName ()
Definition at line 1640 of file SBTarget.cpp.
References lldb_private::ConstString::GetCString(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetAddressByteSize()
uint32_t SBTarget::GetAddressByteSize ()
Definition at line 1721 of file SBTarget.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetAPIMutex()
lldb::SBMutex SBTarget::GetAPIMutex () const
Definition at line 2431 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBMutex.
Referenced by ~SBTarget().
GetArchName()
const char * SBTarget::GetArchName () const
Definition at line 1627 of file SBTarget.cpp.
References lldb_private::ConstString::GetCString(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetBasicType()
SBType SBTarget::GetBasicType (lldb::BasicType type)
Definition at line 1867 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and SBType.
Referenced by ~SBTarget().
GetBreakpointAtIndex()
SBBreakpoint SBTarget::GetBreakpointAtIndex (uint32_t idx) const
Definition at line 1087 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and SBBreakpoint.
Referenced by ~SBTarget().
GetBreakpointNames()
void SBTarget::GetBreakpointNames (SBStringList & names)
Definition at line 1143 of file SBTarget.cpp.
References lldb::SBStringList::AppendString(), lldb::SBStringList::Clear(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetBroadcaster()
SBBroadcaster SBTarget::GetBroadcaster () const
Definition at line 1751 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBBroadcaster.
Referenced by ~SBTarget().
GetBroadcasterClassName()
const char * SBTarget::GetBroadcasterClassName () static
Definition at line 158 of file SBTarget.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::Target::GetStaticBroadcasterClass(), and LLDB_INSTRUMENT.
Referenced by ~SBTarget().
GetByteOrder()
lldb::ByteOrder SBTarget::GetByteOrder ()
Definition at line 1605 of file SBTarget.cpp.
References lldb::eByteOrderInvalid, GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetCodeByteSize()
uint32_t SBTarget::GetCodeByteSize ()
Definition at line 1707 of file SBTarget.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetCollectingStats()
bool SBTarget::GetCollectingStats ()
Returns whether statistics collection are enabled.
Returns
true if statistics are currently being collected, false otherwise.
Definition at line 243 of file SBTarget.cpp.
References lldb_private::DebuggerStats::GetCollectingStats(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetCreatedTargetFromEvent()
SBTarget SBTarget::GetCreatedTargetFromEvent (const lldb::SBEvent & event) static
For eBroadcastBitNewTargetCreated events, returns the newly created target.
For other event types, returns an invalid SBTarget.
Definition at line 135 of file SBTarget.cpp.
References lldb::SBEvent::get(), lldb_private::Target::TargetEventData::GetCreatedTargetFromEvent(), LLDB_INSTRUMENT_VA, and SBTarget().
Referenced by ~SBTarget().
GetDataByteSize()
uint32_t SBTarget::GetDataByteSize ()
Definition at line 1701 of file SBTarget.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetDebugger()
SBDebugger SBTarget::GetDebugger () const
Definition at line 198 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, lldb::SBDebugger::reset(), and SBDebugger.
Referenced by ~SBTarget().
GetDescription()
bool SBTarget::GetDescription (lldb::SBStream & description, lldb::DescriptionLevel description_level)
Definition at line 1761 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
Referenced by lldb::SBDebugger::GetSelectedTarget(), lldb::SBDebugger::SetSelectedTarget(), and ~SBTarget().
GetEnvironment()
SBEnvironment SBTarget::GetEnvironment ()
Return the environment variables that would be used to launch a new process.
Returns
An lldb::SBEnvironment object which is a copy of the target's environment.
Definition at line 2397 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBEnvironment.
Referenced by ~SBTarget().
GetExecutable()
SBFileSpec SBTarget::GetExecutable ()
Definition at line 564 of file SBTarget.cpp.
References lldb_private::Module::GetFileSpec(), GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBFileSpec::SetFileSpec().
Referenced by lldb::SBProcess::GetDescription(), and ~SBTarget().
GetGloballyUniqueID()
lldb::user_id_t SBTarget::GetGloballyUniqueID () const
Get the globally unique ID for this target.
This ID is unique across all debugger instances within the same lldb process.
Returns
The globally unique ID for this target, or LLDB_INVALID_GLOBALLY_UNIQUE_TARGET_ID if the target is invalid.
Definition at line 1659 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and LLDB_INVALID_GLOBALLY_UNIQUE_TARGET_ID.
Referenced by ~SBTarget().
GetInstructions() [1/2]
lldb::SBInstructionList SBTarget::GetInstructions (lldb::addr_t base_addr, const void * buf, size_t size)
Definition at line 2097 of file SBTarget.cpp.
References GetInstructionsWithFlavor(), LLDB_INSTRUMENT_VA, and ResolveLoadAddress().
GetInstructions() [2/2]
lldb::SBInstructionList SBTarget::GetInstructions (lldb::SBAddress base_addr, const void * buf, size_t size)
Definition at line 2055 of file SBTarget.cpp.
References GetInstructionsWithFlavor(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetInstructionsWithFlavor() [1/2]
lldb::SBInstructionList SBTarget::GetInstructionsWithFlavor (lldb::addr_t base_addr, const char * flavor_string, const void * buf, size_t size)
Definition at line 2107 of file SBTarget.cpp.
References GetInstructionsWithFlavor(), LLDB_INSTRUMENT_VA, and ResolveLoadAddress().
GetInstructionsWithFlavor() [2/2]
lldb::SBInstructionList SBTarget::GetInstructionsWithFlavor (lldb::SBAddress base_addr, const char * flavor_string, const void * buf, size_t size)
Definition at line 2064 of file SBTarget.cpp.
References lldb_private::Disassembler::DisassembleBytes(), lldb::SBAddress::get(), GetSP(), LLDB_INSTRUMENT_VA, lldb::SBInstructionList::SetDisassembler(), and UINT32_MAX.
Referenced by GetInstructions(), GetInstructions(), GetInstructionsWithFlavor(), and ~SBTarget().
GetLabel()
const char * SBTarget::GetLabel () const
Definition at line 1651 of file SBTarget.cpp.
References lldb_private::ConstString::AsCString(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetLaunchInfo()
lldb::SBLaunchInfo SBTarget::GetLaunchInfo () const
Definition at line 2381 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBLaunchInfo::set_ref().
Referenced by LaunchSimple(), and ~SBTarget().
GetMaximumNumberOfChildrenToDisplay()
uint32_t SBTarget::GetMaximumNumberOfChildrenToDisplay () const
Gets the target.max-children-count value It should be used to limit the number of children of large data structures to be displayed.
Definition at line 1713 of file SBTarget.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetMaximumOpcodeByteSize()
uint32_t SBTarget::GetMaximumOpcodeByteSize () const
Architecture opcode byte size width accessor.
Returns
The maximum size in 8-bit (host) bytes of an opcode.
Definition at line 1691 of file SBTarget.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetMinimumOpcodeByteSize()
uint32_t SBTarget::GetMinimumOpcodeByteSize () const
Architecture opcode byte size width accessor.
Returns
The minimum size in 8-bit (host) bytes of an opcode.
Definition at line 1683 of file SBTarget.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetModuleAtIndex()
SBModule SBTarget::GetModuleAtIndex (uint32_t idx)
Definition at line 1729 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, SBModule, and lldb::SBModule::SetSP().
Referenced by ~SBTarget().
GetModuleAtIndexFromEvent()
SBModule SBTarget::GetModuleAtIndexFromEvent (const uint32_t idx, const lldb::SBEvent & event) static
Definition at line 149 of file SBTarget.cpp.
References lldb::SBEvent::get(), lldb_private::ModuleList::GetModuleAtIndex(), lldb_private::Target::TargetEventData::GetModuleListFromEvent(), LLDB_INSTRUMENT_VA, and SBModule.
Referenced by ~SBTarget().
GetNumBreakpoints()
uint32_t SBTarget::GetNumBreakpoints () const
Definition at line 1077 of file SBTarget.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetNumModules()
uint32_t SBTarget::GetNumModules () const
Definition at line 1554 of file SBTarget.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetNumModulesFromEvent()
uint32_t SBTarget::GetNumModulesFromEvent (const lldb::SBEvent & event) static
Definition at line 141 of file SBTarget.cpp.
References lldb::SBEvent::get(), lldb_private::Target::TargetEventData::GetModuleListFromEvent(), lldb_private::ModuleList::GetSize(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetNumWatchpoints()
uint32_t SBTarget::GetNumWatchpoints () const
Definition at line 1271 of file SBTarget.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetPlatform()
SBPlatform SBTarget::GetPlatform ()
Return the platform object associated with the target.
After return, the platform object should be checked for validity.
Returns
A platform object.
Definition at line 187 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, lldb::SBPlatform::m_opaque_sp, and SBPlatform.
Referenced by ~SBTarget().
GetProcess()
SBProcess SBTarget::GetProcess ()
Definition at line 174 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, SBProcess, and lldb::SBProcess::SetSP().
Referenced by ~SBTarget().
GetSourceManager()
SBSourceManager SBTarget::GetSourceManager ()
Definition at line 1998 of file SBTarget.cpp.
References LLDB_INSTRUMENT_VA, and SBSourceManager.
Referenced by ~SBTarget().
GetSP()
lldb::TargetSP SBTarget::GetSP () const protected
Definition at line 589 of file SBTarget.cpp.
References m_opaque_sp.
Referenced by AddModule(), AddModule(), AddModule(), AppendImageSearchPath(), lldb::SBPlatform::Attach(), Attach(), AttachToProcessWithID(), AttachToProcessWithName(), BreakpointCreateByAddress(), BreakpointCreateByLocation(), BreakpointCreateByLocation(), BreakpointCreateByName(), BreakpointCreateByName(), BreakpointCreateByNames(), BreakpointCreateByRegex(), BreakpointCreateBySBAddress(), BreakpointCreateBySourceRegex(), BreakpointCreateForException(), BreakpointCreateFromScript(), BreakpointDelete(), BreakpointsCreateFromFile(), BreakpointsWriteToFile(), BreakpointsWriteToFile(), ClearModuleLoadAddress(), ClearSectionLoadAddress(), ConnectRemote(), CreateTrace(), DeleteAllBreakpoints(), DeleteAllWatchpoints(), DeleteBreakpointName(), lldb::SBDebugger::DeleteTarget(), DeleteWatchpoint(), DisableAllBreakpoints(), DisableAllWatchpoints(), EnableAllBreakpoints(), EnableAllWatchpoints(), EvaluateExpression(), EvaluateExpression(), FindBreakpointByID(), FindBreakpointsByName(), FindCompileUnits(), FindFirstType(), FindFunctions(), FindGlobalFunctions(), lldb::SBModule::FindGlobalVariables(), FindGlobalVariables(), FindGlobalVariables(), FindModule(), FindModule(), FindSymbols(), FindTypes(), FindWatchpointByID(), GetABIName(), GetAddressByteSize(), GetAPIMutex(), GetArchName(), GetBasicType(), GetBreakpointAtIndex(), GetBreakpointNames(), GetBroadcaster(), GetByteOrder(), GetCollectingStats(), lldb::SBInstruction::GetComment(), lldb::SBTypeStaticField::GetConstantValue(), lldb::SBInstruction::GetControlFlowKind(), GetDebugger(), lldb::SBAddressRange::GetDescription(), GetDescription(), lldb::SBDebugger::GetDummyTarget(), GetEnvironment(), GetExecutable(), GetGloballyUniqueID(), lldb::SBVariablesOptions::GetIncludeRecognizedArguments(), lldb::SBDebugger::GetIndexOfTarget(), lldb::SBFunction::GetInstructions(), lldb::SBSymbol::GetInstructions(), GetInstructionsWithFlavor(), GetLabel(), GetLaunchInfo(), lldb::SBAddress::GetLoadAddress(), lldb::SBSection::GetLoadAddress(), GetMaximumNumberOfChildrenToDisplay(), GetMaximumOpcodeByteSize(), GetMinimumOpcodeByteSize(), lldb::SBInstruction::GetMnemonic(), GetModuleAtIndex(), GetNumBreakpoints(), GetNumModules(), GetNumWatchpoints(), lldb::SBInstruction::GetOperands(), GetPlatform(), GetProcess(), GetStackRedZoneSize(), GetStatistics(), GetTargetSessionName(), lldb::SBType::GetTemplateArgumentValue(), GetTrace(), GetTriple(), lldb::SBBlock::GetVariables(), GetWatchpointAtIndex(), Install(), IsLoaded(), Launch(), Launch(), LaunchSimple(), lldb_private::python::SWIGBridge, LoadCore(), ReadInstructions(), ReadInstructions(), ReadMemory(), RegisterScriptedFrameProvider(), RemoveModule(), RemoveScriptedFrameProvider(), ResetStatistics(), ResolveFileAddress(), ResolveLoadAddress(), ResolvePastLoadAddress(), ResolveSymbolContextForAddress(), lldb::SBBreakpointNameImpl::SBBreakpointNameImpl(), lldb::SBExecutionContext::SBExecutionContext(), lldb::SBSourceManager::SBSourceManager(), SetCollectingStats(), SetLabel(), SetLaunchInfo(), SetSectionLoadAddress(), lldb::SBDebugger::SetSelectedTarget(), lldb::SBModuleSpec::SetTarget(), and WatchpointCreateByAddress().
GetStackRedZoneSize()
lldb::addr_t SBTarget::GetStackRedZoneSize ()
Definition at line 2354 of file SBTarget.cpp.
References lldb_private::ABI::FindPlugin(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetStatistics() [1/2]
SBStructuredData SBTarget::GetStatistics ()
Returns a dump of the collected statistics.
Returns
A SBStructuredData with the statistics collected.
Definition at line 207 of file SBTarget.cpp.
References GetStatistics(), and LLDB_INSTRUMENT_VA.
Referenced by GetStatistics(), and ~SBTarget().
GetStatistics() [2/2]
SBStructuredData SBTarget::GetStatistics (SBStatisticsOptions options)
Returns a dump of the collected statistics.
Parameters
[in] options An objects object that contains all options for the statistics dumping.
Returns
A SBStructuredData with the statistics collected.
Definition at line 213 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, lldb::SBStructuredData::m_impl_up, lldb_private::StructuredData::ParseJSON(), lldb::SBStatisticsOptions::ref(), and lldb_private::DebuggerStats::ReportStatistics().
GetTargetFromEvent()
SBTarget SBTarget::GetTargetFromEvent (const lldb::SBEvent & event) static
Definition at line 129 of file SBTarget.cpp.
References lldb::SBEvent::get(), lldb_private::Target::TargetEventData::GetTargetFromEvent(), LLDB_INSTRUMENT_VA, and SBTarget().
Referenced by ~SBTarget().
GetTargetSessionName()
const char * SBTarget::GetTargetSessionName () const
Get the target session name for this target.
The target session name provides a meaningful name for IDEs or tools to display to help the user identify the origin and purpose of the target.
Returns
The target session name for this target, or nullptr if the target is invalid or has no target session name.
Definition at line 1667 of file SBTarget.cpp.
References lldb_private::ConstString::AsCString(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetTrace()
lldb::SBTrace SBTarget::GetTrace ()
Get a SBTrace object the can manage the processor trace information of this target.
Returns
The trace object. The returned SBTrace object might not be valid, so it should be checked with a call to "bool SBTrace::IsValid()".
Definition at line 2406 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBTrace.
Referenced by ~SBTarget().
GetTriple()
const char * SBTarget::GetTriple ()
Definition at line 1613 of file SBTarget.cpp.
References lldb_private::ConstString::GetCString(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
GetWatchpointAtIndex()
SBWatchpoint SBTarget::GetWatchpointAtIndex (uint32_t idx) const
Definition at line 1281 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBWatchpoint::SetSP().
Referenced by ~SBTarget().
Install()
SBError SBTarget::Install ()
Install any binaries that need to be installed.
This function does nothing when debugging on the host system. When connected to remote platforms, the target's main executable and any modules that have their remote install path set will be installed on the remote platform. If the main executable doesn't have an install location set, it will be installed in the remote platform's working directory.
Returns
An error describing anything that went wrong during installation.
Definition at line 305 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBError::ref().
Referenced by ~SBTarget().
IsLoaded()
bool SBTarget::IsLoaded (const lldb::SBModule & module) const
Definition at line 2370 of file SBTarget.cpp.
References lldb::SBModule::GetSP(), GetSP(), LLDB_INSTRUMENT_VA, and SBModule.
Referenced by ~SBTarget().
IsValid()
bool SBTarget::IsValid () const
Definition at line 164 of file SBTarget.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by CreateValueFromAddress(), CreateValueFromData(), CreateValueFromExpression(), lldb::SBBreakpointNameImpl::SBBreakpointNameImpl(), lldb::SBAddress::SetLoadAddress(), and ~SBTarget().
Launch() [1/2]
SBProcess SBTarget::Launch (SBLaunchInfo & launch_info, SBError & error)
Definition at line 399 of file SBTarget.cpp.
References error(), lldb::eStateAttaching, lldb::eStateConnected, lldb::eStateInvalid, lldb_private::ProcessInfo::GetArchitecture(), lldb_private::ProcessInfo::GetExecutableFile(), lldb_private::Module::GetPlatformFileSpec(), GetSP(), lldb_private::ArchSpec::IsValid(), LLDB_INSTRUMENT_VA, lldb::SBLaunchInfo::ref(), SBProcess, lldb::SBLaunchInfo::set_ref(), lldb_private::ProcessInfo::SetExecutableFile(), and lldb::SBProcess::SetSP().
Launch() [2/2]
SBProcess SBTarget::Launch (SBListener & listener, char const ** argv, char const ** envp, const char * stdin_path, const char * stdout_path, const char * stderr_path, const char * working_directory, uint32_t launch_flags, bool stop_at_entry, lldb::SBError & error)
Launch a new process.
Launch a new process by spawning a new process using the target object's executable module's file as the file to launch. Arguments are given in argv, and the environment variables are in envp. Standard input and output files can be optionally re-directed to stdin_path, stdout_path, and stderr_path.
Parameters
[in] listener An optional listener that will receive all process events. If listener is valid then listener will listen to all process events. If not valid, then this target's debugger (SBTarget::GetDebugger()) will listen to all process events.
[in] argv The argument array.
[in] envp The environment array. If this is null, the default environment values (provided through settings set / target.env-vars) will be used.
  \param[in] stdin_path
      The path to use when re-directing the STDIN of the new
      process. If all stdXX_path arguments are nullptr, a pseudo
      terminal will be used.
  \param[in] stdout_path
      The path to use when re-directing the STDOUT of the new
      process. If all stdXX_path arguments are nullptr, a pseudo
      terminal will be used.
  \param[in] stderr_path
      The path to use when re-directing the STDERR of the new
      process. If all stdXX_path arguments are nullptr, a pseudo
      terminal will be used.
  \param[in] working_directory
      The working directory to have the child process run in
  \param[in] launch_flags
      Some launch options specified by logical OR'ing
      lldb::LaunchFlags enumeration values together.
  \param[in] stop_at_entry
      If false do not stop the inferior at the entry point.
  \param[out] error
      An error object. Contains the reason if there is some failure.
  \return
       A process object for the newly created process.
Definition at line 316 of file SBTarget.cpp.
References lldb_private::Args::AppendArguments(), error(), lldb::eStateAttaching, lldb::eStateConnected, lldb::eStateInvalid, lldb_private::ProcessInfo::GetArguments(), lldb_private::ProcessInfo::GetEnvironment(), lldb_private::Module::GetPlatformFileSpec(), lldb::SBListener::GetSP(), GetSP(), lldb::SBListener::IsValid(), LLDB_INSTRUMENT_VA, SBProcess, lldb_private::ProcessInfo::SetExecutableFile(), lldb_private::ProcessInfo::SetListener(), and lldb::SBProcess::SetSP().
Referenced by LaunchSimple(), and ~SBTarget().
LaunchSimple()
SBProcess SBTarget::LaunchSimple (const char ** argv, const char ** envp, const char * working_directory)
Launch a new process with sensible defaults.
Parameters
[in] argv The argument array.
[in] envp The environment array. If this isn't provided, the default environment values (provided through settings set / target.env-vars) will be used.
  \param[in] working_directory
      The working directory to have the child process run in
  Default: listener
      Set to the target's debugger (SBTarget::GetDebugger())
  Default: launch_flags
      Empty launch flags
  Default: stdin_path
  Default: stdout_path
  Default: stderr_path
      A pseudo terminal will be used.
  \return
       A process object for the newly created process.
Definition at line 281 of file SBTarget.cpp.
References error(), GetLaunchInfo(), GetSP(), Launch(), LLDB_INSTRUMENT_VA, SBProcess, lldb::SBLaunchInfo::SetArguments(), lldb::SBLaunchInfo::SetEnvironmentEntries(), lldb::SBLaunchInfo::SetExecutableFile(), and lldb::SBLaunchInfo::SetWorkingDirectory().
Referenced by ~SBTarget().
LoadCore() [1/2]
SBProcess SBTarget::LoadCore (const char * core_file)
Definition at line 251 of file SBTarget.cpp.
References error(), LLDB_INSTRUMENT_VA, LoadCore(), and SBProcess.
Referenced by LoadCore(), and ~SBTarget().
LoadCore() [2/2]
SBProcess SBTarget::LoadCore (const char * core_file, lldb::SBError & error)
Definition at line 258 of file SBTarget.cpp.
References error(), GetSP(), lldb_private::FileSystem::Instance(), LLDB_INSTRUMENT_VA, lldb_private::FileSystem::Resolve(), SBProcess, and lldb::SBProcess::SetSP().
operator bool()
SBTarget::operator bool () const explicit
Definition at line 168 of file SBTarget.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator!=()
bool SBTarget::operator!= (const lldb::SBTarget & rhs) const
Definition at line 583 of file SBTarget.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBTarget().
Referenced by ~SBTarget().
operator=()
const SBTarget & SBTarget::operator= (const lldb::SBTarget & rhs)
Definition at line 112 of file SBTarget.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBTarget().
Referenced by ~SBTarget().
operator==()
bool SBTarget::operator== (const lldb::SBTarget & rhs) const
Definition at line 577 of file SBTarget.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBTarget().
Referenced by ~SBTarget().
ReadInstructions() [1/3]
lldb::SBInstructionList SBTarget::ReadInstructions (lldb::SBAddress base_addr, uint32_t count)
Definition at line 2005 of file SBTarget.cpp.
References LLDB_INSTRUMENT_VA, and ReadInstructions().
Referenced by ReadInstructions(), and ~SBTarget().
ReadInstructions() [2/3]
lldb::SBInstructionList SBTarget::ReadInstructions (lldb::SBAddress base_addr, uint32_t count, const char * flavor_string)
Definition at line 2012 of file SBTarget.cpp.
References lldb::SBAddress::get(), GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBInstructionList::SetDisassembler().
ReadInstructions() [3/3]
lldb::SBInstructionList SBTarget::ReadInstructions (lldb::SBAddress start_addr, lldb::SBAddress end_addr, const char * flavor_string)
Definition at line 2031 of file SBTarget.cpp.
References lldb_private::Disassembler::DisassembleRange(), lldb::SBAddress::GetLoadAddress(), GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBInstructionList::SetDisassembler().
ReadMemory()
size_t SBTarget::ReadMemory (const SBAddress addr, void * buf, size_t size, lldb::SBError & error)
Read target memory.
If a target process is running then memory is read from here. Otherwise the memory is read from the object files. For a target whose bytes are sized as a multiple of host bytes, the data read back will preserve the target's byte order.
Parameters
[in] addr A target address to read from.
[out] buf The buffer to read memory into.
[in] size The maximum number of host bytes to read in the buffer passed into this call
[out] error Status information is written here if the memory read fails.
Returns
The amount of data read in host bytes.
Definition at line 663 of file SBTarget.cpp.
References error(), GetSP(), LLDB_INSTRUMENT_VA, lldb::SBAddress::ref(), and SBAddress.
Referenced by ~SBTarget().
RegisterScriptedFrameProvider()
uint32_t SBTarget::RegisterScriptedFrameProvider (const char * class_name, lldb::SBStructuredData args_dict, lldb::SBError & error)
Register a scripted frame provider for this target.
If a scripted frame provider with the same name and same argument dictionary is already registered on this target, it will be overwritten.
Parameters
[in] class_name The name of the Python class that implements the frame provider.
[in] args_dict A dictionary of arguments to pass to the frame provider class.
[out] error An error object indicating success or failure.
Returns
A unique identifier for the frame provider descriptor that was registered. 0 if the registration failed.
Definition at line 2440 of file SBTarget.cpp.
References error(), lldb::eStructuredDataTypeDictionary, GetSP(), lldb_private::ScriptedFrameProviderDescriptor::interface_sp, lldb::SBStructuredData::IsValid(), LLDB_INSTRUMENT_VA, and lldb::SBStructuredData::m_impl_up.
Referenced by ~SBTarget().
RemoveModule()
bool SBTarget::RemoveModule (lldb::SBModule module)
Definition at line 1743 of file SBTarget.cpp.
References lldb::SBModule::GetSP(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
RemoveScriptedFrameProvider()
lldb::SBError SBTarget::RemoveScriptedFrameProvider (uint32_t provider_id)
Remove a scripted frame provider from this target by name.
Parameters
[in] provider_id The id of the frame provider class to remove.
Returns
An error object indicating success or failure.
Definition at line 2493 of file SBTarget.cpp.
References error(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
ResetStatistics()
void SBTarget::ResetStatistics ()
Reset the statistics collected for this target.
This includes clearing symbol table and debug info parsing/index time for all modules, breakpoint resolve time and target statistics.
Definition at line 229 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and lldb_private::DebuggerStats::ResetStatistics().
Referenced by ~SBTarget().
ResolveFileAddress()
lldb::SBAddress SBTarget::ResolveFileAddress (lldb::addr_t file_addr)
Resolve a current file address into a section offset address.
Parameters
[in] file_addr The file address to resolve.
Returns
An SBAddress which will be valid if...
Definition at line 612 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, lldb::SBAddress::ref(), and lldb_private::Address::SetRawAddress().
Referenced by ~SBTarget().
ResolveLoadAddress()
lldb::SBAddress SBTarget::ResolveLoadAddress (lldb::addr_t vm_addr)
Resolve a current load address into a section offset address.
Parameters
[in] vm_addr A virtual address from the current process state that is to be translated into a section offset address.
Returns
An SBAddress which will be valid if vm_addr was successfully resolved into a section offset address, or an invalid SBAddress if vm_addr doesn't resolve to a section in a module.
Definition at line 595 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, lldb::SBAddress::ref(), and lldb_private::Address::SetRawAddress().
Referenced by GetInstructions(), GetInstructionsWithFlavor(), and lldb::SBAddress::SetLoadAddress().
ResolvePastLoadAddress()
lldb::SBAddress SBTarget::ResolvePastLoadAddress (uint32_t stop_id, lldb::addr_t vm_addr)
Resolve a current load address into a section offset address using the process stop ID to identify a time in the past.
Parameters
[in] stop_id Each time a process stops, the process stop ID integer gets incremented. These stop IDs are used to identify past times and can be used in history objects as a cheap way to store the time at which the sample was taken. Specifying UINT32_MAX will always resolve the address using the currently loaded sections.
[in] vm_addr A virtual address from the current process state that is to be translated into a section offset address.
Returns
An SBAddress which will be valid if vm_addr was successfully resolved into a section offset address, or an invalid SBAddress if vm_addr doesn't resolve to a section in a module.
Definition at line 627 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, lldb::SBAddress::ref(), and lldb_private::Address::SetRawAddress().
Referenced by ~SBTarget().
ResolveSymbolContextForAddress()
SBSymbolContext SBTarget::ResolveSymbolContextForAddress (const SBAddress & addr, uint32_t resolve_scope)
Definition at line 646 of file SBTarget.cpp.
References GetSP(), lldb::SBAddress::IsValid(), LLDB_INSTRUMENT_VA, lldb::SBAddress::ref(), lldb::SBSymbolContext::ref(), SBAddress, and lldb_private::SymbolContext::target_sp.
Referenced by ~SBTarget().
SetCollectingStats()
void SBTarget::SetCollectingStats (bool v)
Sets whether we should collect statistics on lldb or not.
Parameters
[in] v A boolean to control the collection.
Definition at line 236 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and lldb_private::DebuggerStats::SetCollectingStats().
Referenced by ~SBTarget().
SetLabel()
SBError SBTarget::SetLabel (const char * label)
Definition at line 1675 of file SBTarget.cpp.
References lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTarget().
SetLaunchInfo()
void SBTarget::SetLaunchInfo (const lldb::SBLaunchInfo & launch_info)
Definition at line 2390 of file SBTarget.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBLaunchInfo::ref().
Referenced by ~SBTarget().
SetModuleLoadAddress()
SBError SBTarget::SetModuleLoadAddress (lldb::SBModule module, uint64_t sections_offset)
Slide all file addresses for all module sections so that module appears to loaded at these slide addresses.
When you need all sections within a module to be loaded at a rigid slide from the addresses found in the module object file, this function will allow you to easily and quickly slide all module sections.
Parameters
[in] module The module to load.
[in] sections_offset An offset that will be applied to all section file addresses (the virtual addresses found in the object file itself).
Returns
An error to indicate success, fail, and any reason for failure. Slide all file addresses for all module sections so that module appears to loaded at these slide addresses.
When you need all sections within a module to be loaded at a rigid slide from the addresses found in the module object file, this function will allow you to easily and quickly slide all module sections.
Parameters
[in] module The module to load.
[in] sections_offset An offset that will be applied to all section file addresses (the virtual addresses found in the object file itself).
Returns
An error to indicate success, fail, and any reason for failure.
Definition at line 2185 of file SBTarget.cpp.
References LLDB_INSTRUMENT_VA, and SetModuleLoadAddress().
Referenced by SetModuleLoadAddress(), and ~SBTarget().
SetSectionLoadAddress()
SBError SBTarget::SetSectionLoadAddress (lldb::SBSection section, lldb::addr_t section_base_addr)
Set the base load address for a module section.
Parameters
[in] section The section whose base load address will be set within this target.
[in] section_base_addr The base address for the section.
Returns
An error to indicate success, fail, and any reason for failure.
Definition at line 2116 of file SBTarget.cpp.
References lldb_private::ModuleList::Append(), lldb::SBSection::GetSP(), GetSP(), lldb::SBSection::IsValid(), LLDB_INSTRUMENT_VA, and lldb::SBError::SetErrorString().
Referenced by ~SBTarget().
SetSP()
void SBTarget::SetSP (const lldb::TargetSP & target_sp) protected
Definition at line 591 of file SBTarget.cpp.
References m_opaque_sp.
Referenced by lldb::SBDebugger::CreateTarget(), lldb::SBDebugger::CreateTarget(), lldb::SBDebugger::CreateTargetWithFileAndArch(), lldb::SBDebugger::CreateTargetWithFileAndTargetTriple(), lldb::SBDebugger::FindTargetByGloballyUniqueID(), lldb::SBDebugger::FindTargetWithFileAndArch(), lldb::SBDebugger::FindTargetWithLLDBProcess(), lldb::SBDebugger::FindTargetWithProcessID(), lldb::SBDebugger::GetDummyTarget(), lldb::SBDebugger::GetSelectedTarget(), lldb::SBExecutionContext::GetTarget(), lldb::SBProcess::GetTarget(), lldb::SBValue::GetTarget(), lldb::SBDebugger::GetTargetAtIndex(), and lldb_private::python::SWIGBridge.
WatchAddress()
lldb::SBWatchpoint SBTarget::WatchAddress (lldb::addr_t addr, size_t size, bool read, bool modify, SBError & error)
Definition at line 1323 of file SBTarget.cpp.
References error(), lldb::eWatchpointWriteTypeOnModify, LLDB_INSTRUMENT_VA, lldb::SBWatchpointOptions::SetWatchpointTypeRead(), lldb::SBWatchpointOptions::SetWatchpointTypeWrite(), and WatchpointCreateByAddress().
Referenced by ~SBTarget().
WatchpointCreateByAddress()
lldb::SBWatchpoint SBTarget::WatchpointCreateByAddress (lldb::addr_t addr, size_t size, lldb::SBWatchpointOptions options, SBError & error)
Definition at line 1336 of file SBTarget.cpp.
References error(), lldb::eWatchpointWriteTypeAlways, lldb::eWatchpointWriteTypeOnModify, GetSP(), lldb::SBWatchpointOptions::GetWatchpointTypeRead(), lldb::SBWatchpointOptions::GetWatchpointTypeWrite(), LLDB_INSTRUMENT_VA, LLDB_INVALID_ADDRESS, LLDB_WATCH_TYPE_MODIFY, LLDB_WATCH_TYPE_READ, LLDB_WATCH_TYPE_WRITE, and lldb::SBWatchpoint::SetSP().
Referenced by WatchAddress(), and ~SBTarget().
Friends And Related Symbol Documentation
lldb_private::python::SWIGBridge
friend class lldb_private::python::SWIGBridge friend
Definition at line 1052 of file SBTarget.h.
References GetSP(), SBTarget(), and SetSP().
SBAddress
friend class SBAddress friend
Definition at line 1029 of file SBTarget.h.
References SBAddress.
Referenced by BreakpointCreateBySBAddress(), CreateValueFromAddress(), ReadMemory(), ResolveSymbolContextForAddress(), SBAddress, and ~SBTarget().
SBAddressRange
friend class SBAddressRange friend
Definition at line 1030 of file SBTarget.h.
References SBAddressRange.
Referenced by SBAddressRange.
SBBlock
friend class SBBlock friend
Definition at line 1031 of file SBTarget.h.
References SBBlock.
Referenced by SBBlock.
SBBreakpoint
friend class SBBreakpoint friend
Definition at line 1032 of file SBTarget.h.
References SBBreakpoint.
Referenced by BreakpointCreateByAddress(), BreakpointCreateByLocation(), BreakpointCreateByLocation(), BreakpointCreateByLocation(), BreakpointCreateByName(), BreakpointCreateByName(), BreakpointCreateByNames(), BreakpointCreateByRegex(), BreakpointCreateByRegex(), BreakpointCreateBySBAddress(), BreakpointCreateBySourceRegex(), BreakpointCreateForException(), BreakpointCreateFromScript(), FindBreakpointByID(), GetBreakpointAtIndex(), and SBBreakpoint.
SBBreakpointList
friend class SBBreakpointList friend
Definition at line 1033 of file SBTarget.h.
References SBBreakpointList.
Referenced by BreakpointsCreateFromFile(), BreakpointsCreateFromFile(), BreakpointsWriteToFile(), BreakpointsWriteToFile(), FindBreakpointsByName(), SBBreakpointList, and ~SBTarget().
SBBreakpointNameImpl
friend class SBBreakpointNameImpl friend
Definition at line 1034 of file SBTarget.h.
References SBBreakpointNameImpl.
Referenced by SBBreakpointNameImpl.
SBDebugger
friend class SBDebugger friend
Definition at line 1035 of file SBTarget.h.
References SBDebugger.
Referenced by GetDebugger(), and SBDebugger.
SBExecutionContext
friend class SBExecutionContext friend
Definition at line 1036 of file SBTarget.h.
References SBExecutionContext.
Referenced by SBExecutionContext.
SBFrame
friend class SBFrame friend
Definition at line 1037 of file SBTarget.h.
References SBFrame.
Referenced by SBFrame.
SBFunction
friend class SBFunction friend
Definition at line 1038 of file SBTarget.h.
References SBFunction.
Referenced by SBFunction.
SBInstruction
friend class SBInstruction friend
Definition at line 1039 of file SBTarget.h.
References SBInstruction.
Referenced by SBInstruction.
SBModule
friend class SBModule friend
Definition at line 1040 of file SBTarget.h.
References SBModule.
Referenced by AddModule(), FindModule(), FindModule(), GetModuleAtIndex(), GetModuleAtIndexFromEvent(), IsLoaded(), SBModule, and ~SBTarget().
SBModuleSpec
friend class SBModuleSpec friend
Definition at line 1041 of file SBTarget.h.
References SBModuleSpec.
Referenced by AddModule(), AddModule(), FindModule(), SBModuleSpec, and ~SBTarget().
SBPlatform
friend class SBPlatform friend
Definition at line 1042 of file SBTarget.h.
References SBPlatform.
Referenced by GetPlatform(), and SBPlatform.
SBProcess
friend class SBProcess friend
Definition at line 1043 of file SBTarget.h.
References SBProcess.
Referenced by Attach(), AttachToProcessWithID(), AttachToProcessWithName(), ConnectRemote(), GetProcess(), Launch(), Launch(), LaunchSimple(), LoadCore(), LoadCore(), SBProcess, and ~SBTarget().
SBSection
friend class SBSection friend
Definition at line 1044 of file SBTarget.h.
References SBSection.
Referenced by SBSection, and ~SBTarget().
SBSourceManager
friend class SBSourceManager friend
Definition at line 1045 of file SBTarget.h.
References SBSourceManager.
Referenced by GetSourceManager(), SBSourceManager, and ~SBTarget().
SBSymbol
friend class SBSymbol friend
Definition at line 1046 of file SBTarget.h.
References SBSymbol.
Referenced by SBSymbol.
SBType
friend class SBType friend
Definition at line 1047 of file SBTarget.h.
References SBType.
Referenced by CreateValueFromAddress(), FindFirstType(), FindTypes(), GetBasicType(), SBType, and ~SBTarget().
SBTypeStaticField
friend class SBTypeStaticField friend
Definition at line 1048 of file SBTarget.h.
References SBTypeStaticField.
Referenced by SBTypeStaticField.
SBValue
friend class SBValue friend
Definition at line 1049 of file SBTarget.h.
References SBValue.
Referenced by CreateValueFromAddress(), CreateValueFromData(), CreateValueFromExpression(), EvaluateExpression(), EvaluateExpression(), FindFirstGlobalVariable(), FindGlobalVariables(), FindGlobalVariables(), SBValue, and ~SBTarget().
SBVariablesOptions
friend class SBVariablesOptions friend
Definition at line 1050 of file SBTarget.h.
References SBVariablesOptions.
Referenced by SBVariablesOptions.
Member Data Documentation
m_opaque_sp
lldb::TargetSP lldb::SBTarget::m_opaque_sp private
Definition at line 1064 of file SBTarget.h.
Referenced by Clear(), CreateValueFromAddress(), CreateValueFromData(), CreateValueFromExpression(), lldb::SBDebugger::DeleteTarget(), EvaluateExpression(), GetLaunchInfo(), GetSP(), operator bool(), operator!=(), operator=(), operator==(), SBTarget(), SBTarget(), SetLaunchInfo(), and SetSP().
The documentation for this class was generated from the following files:
SBTarget.h
SBTarget.cpp