LLDB: RegisterInfoPOSIX_arm Class Reference
RegisterInfoPOSIX_arm Class Reference
#include <RegisterInfoPOSIX_arm.h>
Classes
struct DBG
struct EXC
struct FPU
struct GPR
struct QReg
struct TLS
Public Types
enum { GPRegSet = 0 , FPRegSet , TLSRegSet }
Public Member Functions
RegisterInfoPOSIX_arm (const lldb_private::ArchSpec &target_arch, bool has_tls_reg=false)
size_t GetGPRSize () const override
size_t GetFPRSize () const override
const lldb_private::RegisterInfo * GetRegisterInfo () const override
uint32_t GetRegisterCount () const override
const lldb_private::RegisterSet * GetRegisterSet (size_t reg_set) const override
size_t GetRegisterSetCount () const override
size_t GetRegisterSetFromRegisterIndex (uint32_t reg_index) const override
Public Member Functions inherited from lldb_private::RegisterInfoAndSetInterface
RegisterInfoAndSetInterface (const lldb_private::ArchSpec &target_arch)
Public Member Functions inherited from lldb_private::RegisterInfoInterface
RegisterInfoInterface (const lldb_private::ArchSpec &target_arch)
virtual ~RegisterInfoInterface ()=default
virtual uint32_t GetUserRegisterCount () const
const lldb_private::ArchSpec & GetTargetArchitecture () const
Private Attributes
const lldb_private::RegisterInfo * m_register_info_p
uint32_t m_register_info_count
bool m_has_tls_reg
Detailed Description
Definition at line 16 of file RegisterInfoPOSIX_arm.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
GPRegSet
FPRegSet
TLSRegSet
Definition at line 18 of file RegisterInfoPOSIX_arm.h.
Constructor & Destructor Documentation
RegisterInfoPOSIX_arm()
RegisterInfoPOSIX_arm::RegisterInfoPOSIX_arm (const lldb_private::ArchSpec & target_arch, bool has_tls_reg = false)
Definition at line 166 of file RegisterInfoPOSIX_arm.cpp.
References GetRegisterInfoCount(), GetRegisterInfoPtr(), m_has_tls_reg, m_register_info_count, m_register_info_p, and lldb_private::RegisterInfoAndSetInterface::RegisterInfoAndSetInterface().
Member Function Documentation
GetFPRSize()
size_t RegisterInfoPOSIX_arm::GetFPRSize () const override virtual
Implements lldb_private::RegisterInfoAndSetInterface.
Definition at line 177 of file RegisterInfoPOSIX_arm.cpp.
GetGPRSize()
size_t RegisterInfoPOSIX_arm::GetGPRSize () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 173 of file RegisterInfoPOSIX_arm.cpp.
GetRegisterCount()
uint32_t RegisterInfoPOSIX_arm::GetRegisterCount () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 209 of file RegisterInfoPOSIX_arm.cpp.
References m_register_info_count.
GetRegisterInfo()
const lldb_private::RegisterInfo * RegisterInfoPOSIX_arm::GetRegisterInfo () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 182 of file RegisterInfoPOSIX_arm.cpp.
References m_register_info_p.
GetRegisterSet()
const lldb_private::RegisterSet * RegisterInfoPOSIX_arm::GetRegisterSet (size_t reg_set) const override virtual
Implements lldb_private::RegisterInfoAndSetInterface.
Definition at line 203 of file RegisterInfoPOSIX_arm.cpp.
References g_reg_sets_arm, and GetRegisterSetCount().
GetRegisterSetCount()
size_t RegisterInfoPOSIX_arm::GetRegisterSetCount () const override virtual
Implements lldb_private::RegisterInfoAndSetInterface.
Definition at line 186 of file RegisterInfoPOSIX_arm.cpp.
References k_num_register_sets_with_tls, k_num_register_sets_without_tls, and m_has_tls_reg.
Referenced by GetRegisterSet().
GetRegisterSetFromRegisterIndex()
size_t RegisterInfoPOSIX_arm::GetRegisterSetFromRegisterIndex (uint32_t reg_index) const override virtual
Implements lldb_private::RegisterInfoAndSetInterface.
Definition at line 191 of file RegisterInfoPOSIX_arm.cpp.
References FPRegSet, gpr_cpsr, GPRegSet, LLDB_INVALID_REGNUM, m_has_tls_reg, and TLSRegSet.
Member Data Documentation
m_has_tls_reg
bool RegisterInfoPOSIX_arm::m_has_tls_reg private
Definition at line 77 of file RegisterInfoPOSIX_arm.h.
Referenced by GetRegisterSetCount(), GetRegisterSetFromRegisterIndex(), and RegisterInfoPOSIX_arm().
m_register_info_count
uint32_t RegisterInfoPOSIX_arm::m_register_info_count private
Definition at line 74 of file RegisterInfoPOSIX_arm.h.
Referenced by GetRegisterCount(), and RegisterInfoPOSIX_arm().
m_register_info_p
const lldb_private::RegisterInfo* RegisterInfoPOSIX_arm::m_register_info_p private
Definition at line 73 of file RegisterInfoPOSIX_arm.h.
Referenced by GetRegisterInfo(), and RegisterInfoPOSIX_arm().
The documentation for this class was generated from the following files:
RegisterInfoPOSIX_arm.h
RegisterInfoPOSIX_arm.cpp