LLDB: lldb_private::StackFrameList Class Reference
lldb_private::StackFrameList Class Reference
#include <StackFrameList.h>
Public Member Functions
StackFrameList (Thread &thread, const lldb::StackFrameListSP &prev_frames_sp, bool show_inline_frames, lldb::frame_list_id_t provider_id=0)
virtual ~StackFrameList ()
uint32_t GetNumFrames (bool can_create=true)
Get the number of visible frames.
lldb::StackFrameSP GetFrameAtIndex (uint32_t idx)
Get the frame at index idx. Invisible frames cannot be indexed.
lldb::StackFrameSP GetFrameWithConcreteFrameIndex (uint32_t unwind_idx)
Get the first concrete frame with index greater than or equal to idx.
lldb::StackFrameSP GetFrameWithStackID (const StackID &stack_id)
Retrieve the stack frame with the given ID stack_id.
uint32_t SetSelectedFrame (lldb_private::StackFrame *frame)
Mark a stack frame as the currently selected frame and return its index.
void ClearSelectedFrameIndex ()
Resets the selected frame index of this object.
bool IsNextFrameHidden (lldb_private::StackFrame &frame)
Returns true if the next frame is hidden.
bool IsPreviousFrameHidden (lldb_private::StackFrame &frame)
Returns true if the previous frame is hidden.
std::string GetFrameMarker (lldb::StackFrameSP frame_sp, lldb::StackFrameSP selected_frame_sp, bool show_hidden_marker)
Returns the stack frame marker depending on if frame_sp:
uint32_t GetSelectedFrameIndex (SelectMostRelevant select_most_relevant_frame)
Get the currently selected frame index.
bool SetSelectedFrameByIndex (uint32_t idx)
Mark a stack frame as the currently selected frame using the frame index idx.
uint32_t GetVisibleStackFrameIndex (uint32_t idx)
If the current inline depth (i.e the number of invisible frames) is valid, subtract it from idx.
void CalculateCurrentInlinedDepth ()
Calculate and set the current inline depth.
void SetDefaultFileAndLineToSelectedFrame ()
If the currently selected frame comes from the currently selected thread, point the default file and line of the thread's target to the location specified by the frame.
void Clear ()
Clear the cache of frames.
void Dump (Stream *s)
lldb::StackFrameSP GetStackFrameSPForStackFramePtr (StackFrame *stack_frame_ptr)
If stack_frame_ptr is contained in this StackFrameList, return its wrapping shared pointer.
size_t GetStatus (Stream &strm, uint32_t first_frame, uint32_t num_frames, bool show_frame_info, uint32_t num_frames_with_source, bool show_unique=false, bool show_hidden=false, bool show_hidden_marker=true, bool show_selected_frame=false)
bool WereAllFramesFetched () const
Returns whether we have currently fetched all the frames of a stack.
Thread & GetThread () const
Get the thread associated with this frame list.
lldb::frame_list_id_t GetIdentifier () const
Get the unique identifier for this frame list.
Protected Types
typedef std::vector< lldb::StackFrameSP > collection
typedef collection::iterator iterator
typedef collection::const_iterator const_iterator
Protected Member Functions
bool SetFrameAtIndex (uint32_t idx, lldb::StackFrameSP &frame_sp)
Use this API to build a stack frame list (used for scripted threads, for instance.) This API is not meant for StackFrameLists that have unwinders and partake in lazy stack filling (using GetFramesUpTo).
bool GetFramesUpTo (uint32_t end_idx, InterruptionControl allow_interrupt)
Ensures that frames up to (and including) end_idx are realized in the StackFrameList.
bool GetAllFramesFetched () const
void SetAllFramesFetched ()
bool DecrementCurrentInlinedDepth ()
void ResetCurrentInlinedDepth ()
uint32_t GetCurrentInlinedDepth ()
void SetCurrentInlinedDepth (uint32_t new_depth)
void SelectMostRelevantFrame ()
Calls into the stack frame recognizers and stop info to set the most relevant frame.
virtual bool FetchFramesUpTo (uint32_t end_idx, InterruptionControl allow_interrupt)
Returns true if fetching frames was interrupted, false otherwise.
Protected Attributes
Thread & m_thread
The thread this frame list describes.
lldb::StackFrameListSP m_prev_frames_sp
The old stack frame list.
std::shared_mutex m_list_mutex
A mutex for this frame list.
std::mutex m_inlined_depth_mutex
collection m_frames
A cache of frames.
std::optional< uint32_t > m_selected_frame_idx
The currently selected frame.
std::recursive_mutex m_selected_frame_mutex
Protect access to m_selected_frame_idx.
uint32_t m_concrete_frames_fetched
The number of concrete frames fetched while filling the frame list.
uint32_t m_current_inlined_depth
The number of synthetic function activations (invisible frames) expanded from the concrete frame #0 activation.
lldb::addr_t m_current_inlined_pc
The program counter value at the currently selected synthetic activation.
const bool m_show_inlined_frames
Whether or not to show synthetic (inline) frames. Immutable.
lldb::frame_list_id_t m_identifier = 0
Unique identifier for this frame list instance.
Private Member Functions
uint32_t SetSelectedFrameNoLock (lldb_private::StackFrame *frame)
lldb::StackFrameSP GetFrameAtIndexNoLock (uint32_t idx, std::shared_lock< std::shared_mutex > &guard)
void FetchOnlyConcreteFramesUpTo (uint32_t end_idx)
void SynthesizeTailCallFrames (StackFrame &next_frame)
Given that next_frame will be appended to the frame list, synthesize tail call frames between the current end of the list and next_frame.
StackFrameList (const StackFrameList &)=delete
const StackFrameList & operator= (const StackFrameList &)=delete
Friends
class Thread
class ScriptedFrameProvider
class ScriptedThread
Detailed Description
Definition at line 23 of file StackFrameList.h.
Member Typedef Documentation
collection
typedef std::vector<lldb::StackFrameSP> lldb_private::StackFrameList::collection protected
Definition at line 172 of file StackFrameList.h.
const_iterator
typedef collection::const_iterator lldb_private::StackFrameList::const_iterator protected
Definition at line 174 of file StackFrameList.h.
iterator
typedef collection::iterator lldb_private::StackFrameList::iterator protected
Definition at line 173 of file StackFrameList.h.
Constructor & Destructor Documentation
StackFrameList() [1/2]
StackFrameList::StackFrameList (Thread & thread, const lldb::StackFrameListSP & prev_frames_sp, bool show_inline_frames, lldb::frame_list_id_t provider_id = 0)
Definition at line 40 of file StackFrameList.cpp.
References LLDB_INVALID_ADDRESS, m_concrete_frames_fetched, m_current_inlined_depth, m_current_inlined_pc, m_frames, m_identifier, m_prev_frames_sp, m_selected_frame_idx, m_show_inlined_frames, m_thread, Thread, and UINT32_MAX.
Referenced by FetchFramesUpTo(), operator=(), StackFrameList(), and lldb_private::SyntheticStackFrameList::SyntheticStackFrameList().
~StackFrameList()
StackFrameList::~StackFrameList () virtual
Definition at line 55 of file StackFrameList.cpp.
References Clear().
StackFrameList() [2/2]
lldb_private::StackFrameList::StackFrameList (const StackFrameList &) private delete
References StackFrameList().
Member Function Documentation
CalculateCurrentInlinedDepth()
void StackFrameList::CalculateCurrentInlinedDepth ()
Calculate and set the current inline depth.
This may be used to update the StackFrameList's set of inline frames when execution stops, e.g when a breakpoint is hit.
Definition at line 107 of file StackFrameList.cpp.
References GetCurrentInlinedDepth(), ResetCurrentInlinedDepth(), and UINT32_MAX.
Clear()
void StackFrameList::Clear ()
Clear the cache of frames.
Definition at line 910 of file StackFrameList.cpp.
References m_concrete_frames_fetched, m_frames, m_list_mutex, m_selected_frame_idx, and m_selected_frame_mutex.
Referenced by ~StackFrameList().
ClearSelectedFrameIndex()
void StackFrameList::ClearSelectedFrameIndex ()
Resets the selected frame index of this object.
Definition at line 1028 of file StackFrameList.cpp.
References m_selected_frame_idx.
DecrementCurrentInlinedDepth()
bool StackFrameList::DecrementCurrentInlinedDepth () protected
Definition at line 166 of file StackFrameList.cpp.
References GetCurrentInlinedDepth(), m_current_inlined_depth, m_inlined_depth_mutex, m_show_inlined_frames, and UINT32_MAX.
Dump()
void StackFrameList::Dump (Stream * s)
Definition at line 644 of file StackFrameList.cpp.
References lldb_private::StackID::Dump(), lldb_private::StackFrame::DumpUsingSettingsFormat(), lldb_private::Stream::EOL(), lldb_private::StackFrame::GetStackID(), m_frames, m_list_mutex, and lldb_private::Stream::Printf().
Referenced by FetchFramesUpTo(), and GetFramesUpTo().
FetchFramesUpTo()
bool StackFrameList::FetchFramesUpTo (uint32_t end_idx, InterruptionControl allow_interrupt) protected virtual
Returns true if fetching frames was interrupted, false otherwise.
Reimplemented in lldb_private::SyntheticStackFrameList.
Definition at line 448 of file StackFrameList.cpp.
References lldb_private::LineEntry::ApplyFileMappings(), lldb_private::SymbolContext::block, Dump(), lldb_private::Stream::EOL(), GetAllFramesFetched(), GetCurrentInlinedDepth(), lldb_private::Unwind::GetFrameInfoAtIndex(), GetIdentifier(), lldb_private::SymbolContext::GetParentOfInlinedScope(), lldb_private::StackFrame::GetStackID(), INTERRUPT_REQUESTED, lldb_private::SymbolContext::line_entry, LLDB_INVALID_ADDRESS, m_concrete_frames_fetched, m_frames, m_prev_frames_sp, m_thread, pc, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), lldb_private::StackFrame::Regular, SetAllFramesFetched(), StackFrameList(), SynthesizeTailCallFrames(), UINT32_MAX, and lldb_private::StackFrame::UpdatePreviousFrameFromCurrentFrame().
Referenced by lldb_private::SyntheticStackFrameList::FetchFramesUpTo(), and GetFramesUpTo().
FetchOnlyConcreteFramesUpTo()
void StackFrameList::FetchOnlyConcreteFramesUpTo (uint32_t end_idx) private
These two Fetch frames APIs and SynthesizeTailCallFrames are called in GetFramesUpTo, they are the ones that actually add frames. They must be called with the writer end of the list mutex held.
Not currently interruptible so returns void. }@
Definition at line 428 of file StackFrameList.cpp.
References lldb_private::Unwind::GetFramesUpTo(), m_concrete_frames_fetched, m_frames, m_thread, and UINT32_MAX.
Referenced by GetFramesUpTo().
GetAllFramesFetched()
bool lldb_private::StackFrameList::GetAllFramesFetched () const inline protected
Definition at line 152 of file StackFrameList.h.
References m_concrete_frames_fetched, and UINT32_MAX.
Referenced by FetchFramesUpTo(), GetFramesUpTo(), and WereAllFramesFetched().
GetCurrentInlinedDepth()
uint32_t StackFrameList::GetCurrentInlinedDepth () protected
Definition at line 114 of file StackFrameList.cpp.
References lldb_private::GetLog(), lldb_private::Log::GetVerbose(), LLDB_INVALID_ADDRESS, LLDB_LOGF, m_current_inlined_depth, m_current_inlined_pc, m_inlined_depth_mutex, m_show_inlined_frames, m_thread, lldb_private::Step, and UINT32_MAX.
Referenced by CalculateCurrentInlinedDepth(), DecrementCurrentInlinedDepth(), FetchFramesUpTo(), GetFrameAtIndex(), and SetSelectedFrame().
GetFrameAtIndex()
StackFrameSP StackFrameList::GetFrameAtIndex (uint32_t idx)
Get the frame at index idx. Invisible frames cannot be indexed.
Definition at line 664 of file StackFrameList.cpp.
References AllowInterruption, GetCurrentInlinedDepth(), GetFramesUpTo(), lldb_private::GetLog(), LLDB_LOG, m_frames, m_list_mutex, m_thread, ResetCurrentInlinedDepth(), lldb_private::Thread, and UINT32_MAX.
Referenced by GetFrameWithConcreteFrameIndex(), GetFrameWithStackID(), GetStatus(), IsNextFrameHidden(), IsPreviousFrameHidden(), SelectMostRelevantFrame(), SetDefaultFileAndLineToSelectedFrame(), and SetSelectedFrameByIndex().
GetFrameAtIndexNoLock()
lldb::StackFrameSP lldb_private::StackFrameList::GetFrameAtIndexNoLock (uint32_t idx, std::shared_lock< std::shared_mutex > & guard) private
GetFrameMarker()
std::string StackFrameList::GetFrameMarker (lldb::StackFrameSP frame_sp, lldb::StackFrameSP selected_frame_sp, bool show_hidden_marker)
Returns the stack frame marker depending on if frame_sp:
is selected: *
is the first non hidden frame: ﹍
is the last non hidden frame: ﹉
If the terminal does not support Unicode rendering, the hidden frame markers are replaced with whitespaces.
Definition at line 954 of file StackFrameList.cpp.
References IsNextFrameHidden(), IsPreviousFrameHidden(), and lldb_private::Terminal::SupportsUnicode().
Referenced by GetStatus().
GetFramesUpTo()
bool StackFrameList::GetFramesUpTo (uint32_t end_idx, InterruptionControl allow_interrupt) protected
Ensures that frames up to (and including) end_idx are realized in the StackFrameList.
end_idx can be larger than the actual number of frames, in which case all the frames will be fetched. Acquires the writer end of the list mutex. Returns true if the function was interrupted, false otherwise. Callers should first check (under the shared mutex) whether we need to fetch frames or not.
Definition at line 392 of file StackFrameList.cpp.
References Dump(), FetchFramesUpTo(), FetchOnlyConcreteFramesUpTo(), GetAllFramesFetched(), m_concrete_frames_fetched, m_frames, m_list_mutex, m_show_inlined_frames, and m_thread.
Referenced by GetFrameAtIndex(), and GetNumFrames().
GetFrameWithConcreteFrameIndex()
StackFrameSP StackFrameList::GetFrameWithConcreteFrameIndex (uint32_t unwind_idx)
Get the first concrete frame with index greater than or equal to idx.
Unlike GetFrameAtIndex, this cannot return a synthetic frame.
Definition at line 718 of file StackFrameList.cpp.
References GetFrameAtIndex().
GetFrameWithStackID()
StackFrameSP StackFrameList::GetFrameWithStackID (const StackID & stack_id)
Retrieve the stack frame with the given ID stack_id.
Definition at line 740 of file StackFrameList.cpp.
References CompareStackID(), GetFrameAtIndex(), lldb_private::StackID::IsValid(), m_frames, and m_list_mutex.
GetIdentifier()
lldb::frame_list_id_t lldb_private::StackFrameList::GetIdentifier () const inline
Get the unique identifier for this frame list.
Definition at line 127 of file StackFrameList.h.
References m_identifier.
Referenced by FetchFramesUpTo(), lldb_private::SyntheticStackFrameList::FetchFramesUpTo(), and SynthesizeTailCallFrames().
GetNumFrames()
uint32_t StackFrameList::GetNumFrames (bool can_create = true)
Get the number of visible frames.
Frames may be created if can_create is true. Synthetic (inline) frames expanded from the concrete frame #0 (aka invisible frames) are not included in this count.
Definition at line 631 of file StackFrameList.cpp.
References DoNotAllowInterruption, GetFramesUpTo(), GetVisibleStackFrameIndex(), m_frames, m_list_mutex, UINT32_MAX, and WereAllFramesFetched().
GetSelectedFrameIndex()
uint32_t StackFrameList::GetSelectedFrameIndex (SelectMostRelevant select_most_relevant_frame)
Get the currently selected frame index.
We should only call SelectMostRelevantFrame if (a) the user hasn't already selected a frame, and (b) if this really is a user facing "GetSelectedFrame". SMRF runs the frame recognizers which can do arbitrary work that ends up being dangerous to do internally. Also, for most internal uses we don't actually want the frame changed by the SMRF logic. So unless this is in a command or SB API, you should pass false here.
Definition at line 841 of file StackFrameList.cpp.
References m_selected_frame_idx, m_selected_frame_mutex, and SelectMostRelevantFrame().
Referenced by SetDefaultFileAndLineToSelectedFrame().
GetStackFrameSPForStackFramePtr()
lldb::StackFrameSP StackFrameList::GetStackFrameSPForStackFramePtr (StackFrame * stack_frame_ptr)
If stack_frame_ptr is contained in this StackFrameList, return its wrapping shared pointer.
Definition at line 920 of file StackFrameList.cpp.
References m_frames, and m_list_mutex.
GetStatus()
size_t StackFrameList::GetStatus (Stream & strm, uint32_t first_frame, uint32_t num_frames, bool show_frame_info, uint32_t num_frames_with_source, bool show_unique = false, bool show_hidden = false, bool show_hidden_marker = true, bool show_selected_frame = false)
Definition at line 969 of file StackFrameList.cpp.
References DoNoSelectMostRelevantFrame, GetFrameAtIndex(), GetFrameMarker(), lldb_private::Stream::IndentLess(), INTERRUPT_REQUESTED, m_thread, and UINT32_MAX.
GetThread()
Thread & lldb_private::StackFrameList::GetThread () const inline
Get the thread associated with this frame list.
Definition at line 124 of file StackFrameList.h.
References m_thread, and Thread.
Referenced by lldb_private::SyntheticStackFrameList::FetchFramesUpTo().
GetVisibleStackFrameIndex()
uint32_t lldb_private::StackFrameList::GetVisibleStackFrameIndex (uint32_t idx) inline
If the current inline depth (i.e the number of invisible frames) is valid, subtract it from idx.
Otherwise simply return idx.
Definition at line 87 of file StackFrameList.h.
References m_current_inlined_depth, and UINT32_MAX.
Referenced by GetNumFrames().
IsNextFrameHidden()
bool StackFrameList::IsNextFrameHidden (lldb_private::StackFrame & frame)
Returns true if the next frame is hidden.
Definition at line 936 of file StackFrameList.cpp.
References GetFrameAtIndex(), and lldb_private::StackFrame::GetFrameIndex().
Referenced by GetFrameMarker().
IsPreviousFrameHidden()
bool StackFrameList::IsPreviousFrameHidden (lldb_private::StackFrame & frame)
Returns true if the previous frame is hidden.
Definition at line 944 of file StackFrameList.cpp.
References GetFrameAtIndex(), and lldb_private::StackFrame::GetFrameIndex().
Referenced by GetFrameMarker().
operator=()
const StackFrameList & lldb_private::StackFrameList::operator= (const StackFrameList &) private delete
References StackFrameList().
ResetCurrentInlinedDepth()
void StackFrameList::ResetCurrentInlinedDepth () protected
Definition at line 133 of file StackFrameList.cpp.
References lldb_private::GetLog(), lldb_private::Log::GetVerbose(), LLDB_INVALID_ADDRESS, LLDB_LOGF, m_current_inlined_depth, m_current_inlined_pc, m_inlined_depth_mutex, m_show_inlined_frames, m_thread, lldb_private::Step, and UINT32_MAX.
Referenced by CalculateCurrentInlinedDepth(), and GetFrameAtIndex().
SelectMostRelevantFrame()
void StackFrameList::SelectMostRelevantFrame () protected
Calls into the stack frame recognizers and stop info to set the most relevant frame.
This can call out to arbitrary user code so it can't hold the StackFrameList mutex.
Definition at line 778 of file StackFrameList.cpp.
References GetFrameAtIndex(), lldb_private::GetLog(), LLDB_LOG, m_thread, SetSelectedFrame(), and lldb_private::Thread.
Referenced by GetSelectedFrameIndex().
SetAllFramesFetched()
void lldb_private::StackFrameList::SetAllFramesFetched () inline protected
Definition at line 157 of file StackFrameList.h.
References m_concrete_frames_fetched, and UINT32_MAX.
Referenced by FetchFramesUpTo(), and lldb_private::SyntheticStackFrameList::FetchFramesUpTo().
SetCurrentInlinedDepth()
void StackFrameList::SetCurrentInlinedDepth (uint32_t new_depth) protected
Definition at line 180 of file StackFrameList.cpp.
References LLDB_INVALID_ADDRESS, m_current_inlined_depth, m_current_inlined_pc, m_inlined_depth_mutex, m_thread, and UINT32_MAX.
SetDefaultFileAndLineToSelectedFrame()
void StackFrameList::SetDefaultFileAndLineToSelectedFrame ()
If the currently selected frame comes from the currently selected thread, point the default file and line of the thread's target to the location specified by the frame.
Definition at line 889 of file StackFrameList.cpp.
References DoNoSelectMostRelevantFrame, lldb_private::LineEntry::file_sp, lldb_private::LineEntry::GetFile(), GetFrameAtIndex(), GetSelectedFrameIndex(), lldb_private::LineEntry::line, lldb_private::SymbolContext::line_entry, and m_thread.
Referenced by SetSelectedFrame().
SetFrameAtIndex()
bool StackFrameList::SetFrameAtIndex (uint32_t idx, lldb::StackFrameSP & frame_sp) protected
Use this API to build a stack frame list (used for scripted threads, for instance.) This API is not meant for StackFrameLists that have unwinders and partake in lazy stack filling (using GetFramesUpTo).
Rather if you are building StackFrameLists with this API, you should build the entire list before making it available for use.
Definition at line 766 of file StackFrameList.cpp.
References m_frames, and m_list_mutex.
SetSelectedFrame()
uint32_t StackFrameList::SetSelectedFrame (lldb_private::StackFrame * frame)
Mark a stack frame as the currently selected frame and return its index.
Definition at line 857 of file StackFrameList.cpp.
References GetCurrentInlinedDepth(), m_frames, m_list_mutex, m_selected_frame_idx, m_selected_frame_mutex, SetDefaultFileAndLineToSelectedFrame(), and UINT32_MAX.
Referenced by SelectMostRelevantFrame(), and SetSelectedFrameByIndex().
SetSelectedFrameByIndex()
bool StackFrameList::SetSelectedFrameByIndex (uint32_t idx)
Mark a stack frame as the currently selected frame using the frame index idx.
Like GetFrameAtIndex, invisible frames cannot be selected.
Definition at line 880 of file StackFrameList.cpp.
References GetFrameAtIndex(), and SetSelectedFrame().
SetSelectedFrameNoLock()
uint32_t lldb_private::StackFrameList::SetSelectedFrameNoLock (lldb_private::StackFrame * frame) private
SynthesizeTailCallFrames()
void StackFrameList::SynthesizeTailCallFrames (StackFrame & next_frame) private
Given that next_frame will be appended to the frame list, synthesize tail call frames between the current end of the list and next_frame.
If any frames are added, adjust the frame index of next_frame.
| ... | <- Completed frames.
| prev_frame |
| ... | <- Artificial frames inserted here.
| next_frame |
| ... | <- Not-yet-visited frames.
Definition at line 319 of file StackFrameList.cpp.
References lldb_private::Function::CalculateSymbolContext(), lldb_private::StackFrame::CalculateTarget(), lldb_private::CallEdge::Call, FindInterveningFrames(), lldb_private::SymbolContext::function, lldb_private::StackFrame::GetConcreteFrameIndex(), lldb_private::Function::GetDisplayName(), GetIdentifier(), lldb_private::GetLog(), lldb_private::StackFrame::GetRegisterContext(), lldb_private::StackFrame::GetSymbolContext(), LLDB_INVALID_ADDRESS, LLDB_LOG, m_frames, m_thread, pc, lldb_private::StackFrame::Regular, lldb_private::StackFrame::SetFrameIndex(), lldb_private::ExecutionContext::SetFramePtr(), and lldb_private::Step.
Referenced by FetchFramesUpTo().
WereAllFramesFetched()
bool StackFrameList::WereAllFramesFetched () const
Returns whether we have currently fetched all the frames of a stack.
Definition at line 189 of file StackFrameList.cpp.
References GetAllFramesFetched(), and m_list_mutex.
Referenced by GetNumFrames().
Friends And Related Symbol Documentation
ScriptedFrameProvider
friend class ScriptedFrameProvider friend
Definition at line 131 of file StackFrameList.h.
References ScriptedFrameProvider.
Referenced by ScriptedFrameProvider.
ScriptedThread
friend class ScriptedThread friend
Definition at line 132 of file StackFrameList.h.
References ScriptedThread.
Referenced by ScriptedThread.
Thread
friend class Thread friend
Definition at line 130 of file StackFrameList.h.
References Thread.
Referenced by GetThread(), StackFrameList(), lldb_private::SyntheticStackFrameList::SyntheticStackFrameList(), and Thread.
Member Data Documentation
m_concrete_frames_fetched
uint32_t lldb_private::StackFrameList::m_concrete_frames_fetched protected
The number of concrete frames fetched while filling the frame list.
This is only used when synthetic frames are enabled.
Definition at line 222 of file StackFrameList.h.
Referenced by Clear(), FetchFramesUpTo(), FetchOnlyConcreteFramesUpTo(), GetAllFramesFetched(), GetFramesUpTo(), SetAllFramesFetched(), and StackFrameList().
m_current_inlined_depth
uint32_t lldb_private::StackFrameList::m_current_inlined_depth protected
The number of synthetic function activations (invisible frames) expanded from the concrete frame #0 activation.
Definition at line 227 of file StackFrameList.h.
Referenced by DecrementCurrentInlinedDepth(), GetCurrentInlinedDepth(), GetVisibleStackFrameIndex(), ResetCurrentInlinedDepth(), SetCurrentInlinedDepth(), and StackFrameList().
m_current_inlined_pc
lldb::addr_t lldb_private::StackFrameList::m_current_inlined_pc protected
The program counter value at the currently selected synthetic activation.
This is only valid if m_current_inlined_depth is valid.
Definition at line 232 of file StackFrameList.h.
Referenced by GetCurrentInlinedDepth(), ResetCurrentInlinedDepth(), SetCurrentInlinedDepth(), and StackFrameList().
m_frames
collection lldb_private::StackFrameList::m_frames protected
A cache of frames.
This may need to be updated when the program counter changes.
Definition at line 199 of file StackFrameList.h.
Referenced by Clear(), Dump(), FetchFramesUpTo(), lldb_private::SyntheticStackFrameList::FetchFramesUpTo(), FetchOnlyConcreteFramesUpTo(), GetFrameAtIndex(), GetFramesUpTo(), GetFrameWithStackID(), GetNumFrames(), GetStackFrameSPForStackFramePtr(), SetFrameAtIndex(), SetSelectedFrame(), StackFrameList(), and SynthesizeTailCallFrames().
m_identifier
lldb::frame_list_id_t lldb_private::StackFrameList::m_identifier = 0 protected
Unique identifier for this frame list instance.
Definition at line 238 of file StackFrameList.h.
Referenced by GetIdentifier(), and StackFrameList().
m_inlined_depth_mutex
std::mutex lldb_private::StackFrameList::m_inlined_depth_mutex mutable protected
Definition at line 195 of file StackFrameList.h.
Referenced by DecrementCurrentInlinedDepth(), GetCurrentInlinedDepth(), ResetCurrentInlinedDepth(), and SetCurrentInlinedDepth().
m_list_mutex
std::shared_mutex lldb_private::StackFrameList::m_list_mutex mutable protected
A mutex for this frame list.
The only public API that requires the unique lock is Clear. All other clients take the shared lock, though if we need more frames we may swap shared for unique to fulfill that requirement.
Definition at line 190 of file StackFrameList.h.
Referenced by Clear(), Dump(), GetFrameAtIndex(), GetFramesUpTo(), GetFrameWithStackID(), GetNumFrames(), GetStackFrameSPForStackFramePtr(), SetFrameAtIndex(), SetSelectedFrame(), and WereAllFramesFetched().
m_prev_frames_sp
lldb::StackFrameListSP lldb_private::StackFrameList::m_prev_frames_sp protected
The old stack frame list.
Definition at line 184 of file StackFrameList.h.
Referenced by FetchFramesUpTo(), and StackFrameList().
m_selected_frame_idx
std::optional<uint32_t> lldb_private::StackFrameList::m_selected_frame_idx protected
The currently selected frame.
An optional is used to record whether anyone has set the selected frame on this stack yet. We only let recognizers change the frame if this is the first time GetSelectedFrame is called.
Thread-safety: This member is not protected by a mutex. LLDB really only should have an opinion about the selected frame index when a process stops, before control gets handed back to the user. After that, it's up to them to change it whenever they feel like it. If two parts of lldb decided they wanted to be in control of the selected frame index on stop the right way to fix it would need to be some explicit negotiation for who gets to control this.
Definition at line 213 of file StackFrameList.h.
Referenced by Clear(), ClearSelectedFrameIndex(), GetSelectedFrameIndex(), SetSelectedFrame(), and StackFrameList().
m_selected_frame_mutex
std::recursive_mutex lldb_private::StackFrameList::m_selected_frame_mutex protected
Protect access to m_selected_frame_idx.
Always acquire after m_list_mutex to avoid lock inversion. A recursive mutex because GetSelectedFrameIndex may indirectly call SetSelectedFrame.
Definition at line 218 of file StackFrameList.h.
Referenced by Clear(), GetSelectedFrameIndex(), and SetSelectedFrame().
m_show_inlined_frames
const bool lldb_private::StackFrameList::m_show_inlined_frames protected
Whether or not to show synthetic (inline) frames. Immutable.
Definition at line 235 of file StackFrameList.h.
Referenced by DecrementCurrentInlinedDepth(), GetCurrentInlinedDepth(), GetFramesUpTo(), ResetCurrentInlinedDepth(), and StackFrameList().
m_thread
Thread& lldb_private::StackFrameList::m_thread protected
The thread this frame list describes.
Definition at line 177 of file StackFrameList.h.
Referenced by FetchFramesUpTo(), lldb_private::SyntheticStackFrameList::FetchFramesUpTo(), FetchOnlyConcreteFramesUpTo(), GetCurrentInlinedDepth(), GetFrameAtIndex(), GetFramesUpTo(), GetStatus(), GetThread(), ResetCurrentInlinedDepth(), SelectMostRelevantFrame(), SetCurrentInlinedDepth(), SetDefaultFileAndLineToSelectedFrame(), StackFrameList(), and SynthesizeTailCallFrames().
The documentation for this class was generated from the following files:
StackFrameList.h
StackFrameList.cpp