LLDB: lldb::SBReplayOptions Class Reference
lldb::SBReplayOptions Class Reference
#include <SBReproducer.h>
Public Member Functions
SBReplayOptions ()
SBReplayOptions (const SBReplayOptions &rhs)
~SBReplayOptions ()
SBReplayOptions & operator= (const SBReplayOptions &rhs)
void SetVerify (bool verify)
bool GetVerify () const
void SetCheckVersion (bool check)
bool GetCheckVersion () const
Detailed Description
Definition at line 17 of file SBReproducer.h.
Constructor & Destructor Documentation
SBReplayOptions() [1/2]
SBReplayOptions::SBReplayOptions () default
Referenced by operator=(), SBReplayOptions(), and ~SBReplayOptions().
SBReplayOptions() [2/2]
SBReplayOptions::SBReplayOptions (const SBReplayOptions & rhs) default
References SBReplayOptions().
~SBReplayOptions()
SBReplayOptions::~SBReplayOptions () default
References GetCheckVersion(), GetVerify(), operator=(), SBReplayOptions(), SetCheckVersion(), and SetVerify().
Member Function Documentation
GetCheckVersion()
bool SBReplayOptions::GetCheckVersion () const
Definition at line 39 of file SBReproducer.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBReplayOptions().
GetVerify()
bool SBReplayOptions::GetVerify () const
Definition at line 30 of file SBReproducer.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBReplayOptions().
operator=()
SBReplayOptions & SBReplayOptions::operator= (const SBReplayOptions & rhs)
Definition at line 21 of file SBReproducer.cpp.
References LLDB_INSTRUMENT_VA, and SBReplayOptions().
Referenced by ~SBReplayOptions().
SetCheckVersion()
void SBReplayOptions::SetCheckVersion (bool check)
Definition at line 35 of file SBReproducer.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBReplayOptions().
SetVerify()
void SBReplayOptions::SetVerify (bool verify)
Definition at line 26 of file SBReproducer.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBReplayOptions().
The documentation for this class was generated from the following files:
SBReproducer.h
SBReproducer.cpp