LLDB: ABISysV_loongarch Class Reference
ABISysV_loongarch Class Reference
#include <ABISysV_loongarch.h>
Public Member Functions
~ABISysV_loongarch () override=default
size_t GetRedZoneSize () const override
bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override
bool GetArgumentValues (lldb_private::Thread &thread, lldb_private::ValueList &values) const override
lldb_private::Status SetReturnValueObject (lldb::StackFrameSP &frame_sp, lldb::ValueObjectSP &new_value) override
lldb::ValueObjectSP GetReturnValueObjectImpl (lldb_private::Thread &thread, lldb_private::CompilerType &type) const override
lldb::UnwindPlanSP CreateFunctionEntryUnwindPlan () override
lldb::UnwindPlanSP CreateDefaultUnwindPlan () override
bool RegisterIsVolatile (const lldb_private::RegisterInfo *reg_info) override
bool CallFrameAddressIsValid (lldb::addr_t cfa) override
void SetIsLA64 (bool is_la64)
bool CodeAddressIsValid (lldb::addr_t pc) override
const lldb_private::RegisterInfo * GetRegisterInfoArray (uint32_t &count) override
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::RegInfoBasedABI
void AugmentRegisterInfo (std::vector< DynamicRegisterInfo::Register > &regs) override
Public Member Functions inherited from lldb_private::ABI
~ABI () override
virtual bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::Type &prototype, llvm::ArrayRef< CallArgument > args) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, CompilerType &type, bool persistent=true) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, llvm::Type &type, bool persistent=true) const
virtual bool GetFallbackRegisterLocation (const RegisterInfo *reg_info, UnwindPlan::Row::AbstractRegisterLocation &unwind_regloc)
virtual lldb::addr_t FixAnyAddress (lldb::addr_t pc)
Use this method when you do not know, or do not care what kind of address you are fixing.
llvm::MCRegisterInfo & GetMCRegisterInfo ()
virtual bool GetPointerReturnRegister (const char *&name)
virtual uint64_t GetStackFrameSize ()
virtual lldb::addr_t FixCodeAddress (lldb::addr_t pc)
Some targets might use bits in a code address to indicate a mode switch.
virtual lldb::addr_t FixDataAddress (lldb::addr_t pc)
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static lldb::ABISP CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec &arch)
static llvm::StringRef GetPluginNameStatic ()
Static Public Member Functions inherited from lldb_private::ABI
static lldb::ABISP FindPlugin (lldb::ProcessSP process_sp, const ArchSpec &arch)
Protected Member Functions
void AugmentRegisterInfo (std::vector< lldb_private::DynamicRegisterInfo::Register > &regs) override
bool RegisterIsCalleeSaved (const lldb_private::RegisterInfo *reg_info)
Protected Member Functions inherited from lldb_private::RegInfoBasedABI
bool GetRegisterInfoByName (llvm::StringRef name, RegisterInfo &info)
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Protected Member Functions inherited from lldb_private::ABI
virtual lldb::ValueObjectSP GetReturnValueObjectImpl (Thread &thread, llvm::Type &ir_type) const
lldb::ProcessSP GetProcessSP () const
Request to get a Process shared pointer.
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Private Member Functions
lldb::ValueObjectSP GetReturnValueObjectSimple (lldb_private::Thread &thread, lldb_private::CompilerType &ast_type) const
Private Attributes
bool m_is_la64
Additional Inherited Members
Static Protected Member Functions inherited from lldb_private::ABI
static std::unique_ptr< llvm::MCRegisterInfo > MakeMCRegisterInfo (const ArchSpec &arch)
Utility function to construct a MCRegisterInfo using the ArchSpec triple.
Protected Attributes inherited from lldb_private::ABI
lldb::ProcessWP m_process_wp
std::unique_ptr< llvm::MCRegisterInfo > m_mc_register_info_up
Detailed Description
Definition at line 21 of file ABISysV_loongarch.h.
Constructor & Destructor Documentation
~ABISysV_loongarch()
ABISysV_loongarch::~ABISysV_loongarch () override default
Member Function Documentation
AugmentRegisterInfo()
void ABISysV_loongarch::AugmentRegisterInfo (std::vector< lldb_private::DynamicRegisterInfo::Register > & regs) override protected virtual
Implements lldb_private::ABI.
Definition at line 635 of file ABISysV_loongarch.cpp.
References lldb_private::RegInfoBasedABI::AugmentRegisterInfo(), and GetGenericNum().
CallFrameAddressIsValid()
bool ABISysV_loongarch::CallFrameAddressIsValid (lldb::addr_t cfa) inline override virtual
Implements lldb_private::ABI.
Definition at line 49 of file ABISysV_loongarch.h.
CodeAddressIsValid()
bool ABISysV_loongarch::CodeAddressIsValid (lldb::addr_t pc) inline override virtual
Implements lldb_private::ABI.
Definition at line 56 of file ABISysV_loongarch.h.
References pc.
CreateDefaultUnwindPlan()
UnwindPlanSP ABISysV_loongarch::CreateDefaultUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 552 of file ABISysV_loongarch.cpp.
References lldb_private::eLazyBoolNo, lldb::eRegisterKindGeneric, lldb_private::UnwindPlan::Row::GetCFAValue(), LLDB_REGNUM_GENERIC_FP, LLDB_REGNUM_GENERIC_PC, m_is_la64, reg_size, lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), and lldb_private::UnwindPlan::Row::SetRegisterLocationToAtCFAPlusOffset().
CreateFunctionEntryUnwindPlan()
UnwindPlanSP ABISysV_loongarch::CreateFunctionEntryUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 532 of file ABISysV_loongarch.cpp.
References loongarch_dwarf::dwarf_gpr_pc, loongarch_dwarf::dwarf_gpr_ra, loongarch_dwarf::dwarf_gpr_sp, lldb_private::eLazyBoolNo, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), and lldb_private::UnwindPlan::Row::SetRegisterLocationToRegister().
CreateInstance()
ABISP ABISysV_loongarch::CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec & arch) static
Definition at line 149 of file ABISysV_loongarch.cpp.
References lldb_private::ArchSpec::GetTriple(), lldb_private::ABI::MakeMCRegisterInfo(), and SetIsLA64().
Referenced by Initialize(), and Terminate().
GetArgumentValues()
bool ABISysV_loongarch::GetArgumentValues (lldb_private::Thread & thread, lldb_private::ValueList & values) const override virtual
Implements lldb_private::ABI.
Definition at line 240 of file ABISysV_loongarch.cpp.
GetPluginName()
llvm::StringRef ABISysV_loongarch::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 84 of file ABISysV_loongarch.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef ABISysV_loongarch::GetPluginNameStatic () inline static
Definition at line 78 of file ABISysV_loongarch.h.
Referenced by GetPluginName(), and Initialize().
GetRedZoneSize()
size_t ABISysV_loongarch::GetRedZoneSize () const inline override virtual
Implements lldb_private::ABI.
Definition at line 25 of file ABISysV_loongarch.h.
GetRegisterInfoArray()
const RegisterInfo * ABISysV_loongarch::GetRegisterInfoArray (uint32_t & count) override virtual
Implements lldb_private::RegInfoBasedABI.
Definition at line 139 of file ABISysV_loongarch.cpp.
GetReturnValueObjectImpl()
ValueObjectSP ABISysV_loongarch::GetReturnValueObjectImpl (lldb_private::Thread & thread, lldb_private::CompilerType & type) const override virtual
Implements lldb_private::ABI.
Definition at line 521 of file ABISysV_loongarch.cpp.
References GetReturnValueObjectSimple().
GetReturnValueObjectSimple()
ValueObjectSP ABISysV_loongarch::GetReturnValueObjectSimple (lldb_private::Thread & thread, lldb_private::CompilerType & ast_type) const private
Definition at line 479 of file ABISysV_loongarch.cpp.
References lldb_private::ValueObjectConstResult::Create(), lldb::eRegisterKindGeneric, lldb_private::CompilerType::GetByteSize(), lldb_private::ArchSpec::GetMachine(), lldb_private::Value::GetScalar(), lldb_private::CompilerType::GetTypeInfo(), GetValObjFromFPRegs(), GetValObjFromIntRegs(), lldb_private::CompilerType::IsRealFloatingPointType(), LLDB_REGNUM_GENERIC_ARG1, lldb_private::Value::Scalar, lldb_private::Value::SetCompilerType(), and lldb_private::Value::SetValueType().
Referenced by GetReturnValueObjectImpl().
Initialize()
void ABISysV_loongarch::Initialize () static
Definition at line 608 of file ABISysV_loongarch.cpp.
References CreateInstance(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
PrepareTrivialCall()
bool ABISysV_loongarch::PrepareTrivialCall (lldb_private::Thread & thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override virtual
Implements lldb_private::ABI.
Definition at line 193 of file ABISysV_loongarch.cpp.
References lldb::eRegisterKindGeneric, lldb_private::Expressions, g_regs_for_args_count, lldb_private::GetLog(), LLDB_LOG, LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_RA, LLDB_REGNUM_GENERIC_SP, LogInitInfo(), lldb_private::RegisterInfo::name, sp, and UpdateRegister().
RegisterIsCalleeSaved()
bool ABISysV_loongarch::RegisterIsCalleeSaved (const lldb_private::RegisterInfo * reg_info) protected
Definition at line 582 of file ABISysV_loongarch.cpp.
References lldb_private::ArchSpec::eLoongArch_abi_mask, lldb_private::ArchSpec::GetFlags(), lldb_private::ABI::GetProcessSP(), and lldb_private::RegisterInfo::name.
Referenced by RegisterIsVolatile().
RegisterIsVolatile()
bool ABISysV_loongarch::RegisterIsVolatile (const lldb_private::RegisterInfo * reg_info) override virtual
Implements lldb_private::ABI.
Definition at line 578 of file ABISysV_loongarch.cpp.
References RegisterIsCalleeSaved().
SetIsLA64()
void ABISysV_loongarch::SetIsLA64 (bool is_la64) inline
Definition at line 54 of file ABISysV_loongarch.h.
References m_is_la64.
Referenced by CreateInstance().
SetReturnValueObject()
Status ABISysV_loongarch::SetReturnValueObject (lldb::StackFrameSP & frame_sp, lldb::ValueObjectSP & new_value) override virtual
Implements lldb_private::ABI.
Definition at line 246 of file ABISysV_loongarch.cpp.
References lldb_private::Status::AsCString(), lldb::eRegisterKindGeneric, lldb_private::Status::Fail(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataExtractor::GetMaxU64(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), lldb_private::CompilerType::IsPointerType(), LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_ARG2, m_is_la64, and reg_size.
Terminate()
void ABISysV_loongarch::Terminate () static
Definition at line 614 of file ABISysV_loongarch.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Member Data Documentation
m_is_la64
bool ABISysV_loongarch::m_is_la64 private
Definition at line 99 of file ABISysV_loongarch.h.
Referenced by CreateDefaultUnwindPlan(), SetIsLA64(), and SetReturnValueObject().
The documentation for this class was generated from the following files:
ABISysV_loongarch.h
ABISysV_loongarch.cpp