LLDB: ArchThreadContexts Class Reference
ArchThreadContexts Class Reference
Public Member Functions
ArchThreadContexts (llvm::Triple::ArchType arch)
bool prepareRegisterContext (RegisterContext *reg_ctx)
const void * data () const
size_t size () const
Private Attributes
llvm::Triple::ArchType m_arch
union {
lldb_private::minidump::MinidumpContext_x86_64 x86_64
lldb_private::minidump::RegisterContextMinidump_ARM64::Context arm64
};
Detailed Description
Definition at line 552 of file MinidumpFileBuilder.cpp.
Constructor & Destructor Documentation
ArchThreadContexts()
ArchThreadContexts::ArchThreadContexts (llvm::Triple::ArchType arch) inline
Definition at line 560 of file MinidumpFileBuilder.cpp.
References m_arch.
Member Function Documentation
data()
const void * ArchThreadContexts::data () const inline
Definition at line 576 of file MinidumpFileBuilder.cpp.
References x86_64.
Referenced by MinidumpFileBuilder::AddThreadList().
prepareRegisterContext()
bool ArchThreadContexts::prepareRegisterContext (RegisterContext * reg_ctx) inline
Definition at line 562 of file MinidumpFileBuilder.cpp.
References arm64, GetThreadContext_ARM64(), GetThreadContext_x86_64(), m_arch, and x86_64.
Referenced by MinidumpFileBuilder::AddThreadList().
size()
size_t ArchThreadContexts::size () const inline
Definition at line 578 of file MinidumpFileBuilder.cpp.
References arm64, m_arch, and x86_64.
Referenced by MinidumpFileBuilder::AddThreadList().
Member Data Documentation
[union]
union { ... } ArchThreadContexts
arm64
lldb_private::minidump::RegisterContextMinidump_ARM64::Context ArchThreadContexts::arm64
Definition at line 556 of file MinidumpFileBuilder.cpp.
Referenced by prepareRegisterContext(), and size().
m_arch
llvm::Triple::ArchType ArchThreadContexts::m_arch private
Definition at line 553 of file MinidumpFileBuilder.cpp.
Referenced by ArchThreadContexts(), prepareRegisterContext(), and size().
x86_64
lldb_private::minidump::MinidumpContext_x86_64 ArchThreadContexts::x86_64
Definition at line 555 of file MinidumpFileBuilder.cpp.
Referenced by data(), prepareRegisterContext(), and size().
The documentation for this class was generated from the following file:
MinidumpFileBuilder.cpp