LLDB: lldb_private::RustTreeSitterHighlighter Class Reference
lldb_private::RustTreeSitterHighlighter Class Reference
#include <RustTreeSitterHighlighter.h>
Public Member Functions
RustTreeSitterHighlighter ()=default
~RustTreeSitterHighlighter () override=default
llvm::StringRef GetName () const override
Returns a human readable name for the selected highlighter.
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::TreeSitterHighlighter
TreeSitterHighlighter ()=default
~TreeSitterHighlighter () override=default
void Highlight (const HighlightStyle &options, llvm::StringRef line, std::optional< size_t > cursor_pos, llvm::StringRef previous_lines, Stream &s) const override
Highlights a single line of code using tree-sitter parsing.
Public Member Functions inherited from lldb_private::Highlighter
Highlighter ()=default
virtual ~Highlighter ()=default
Highlighter (const Highlighter &)=delete
const Highlighter & operator= (const Highlighter &)=delete
std::string Highlight (const HighlightStyle &options, llvm::StringRef line, std::optional< size_t > cursor_pos, llvm::StringRef previous_lines="") const
Utility method for calling Highlight without a stream.
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static Highlighter * CreateInstance (lldb::LanguageType language)
static void Terminate ()
static void Initialize ()
static llvm::StringRef GetPluginNameStatic ()
Protected Member Functions
const TSLanguage * GetLanguage () const override
Returns the tree-sitter language for this highlighter.
llvm::StringRef GetHighlightQuery () const override
Returns the tree-sitter highlight query for this language.
Detailed Description
Definition at line 17 of file RustTreeSitterHighlighter.h.
Constructor & Destructor Documentation
RustTreeSitterHighlighter()
lldb_private::RustTreeSitterHighlighter::RustTreeSitterHighlighter () default
Referenced by CreateInstance(), and GetLanguage().
~RustTreeSitterHighlighter()
lldb_private::RustTreeSitterHighlighter::~RustTreeSitterHighlighter () override default
Member Function Documentation
CreateInstance()
Highlighter * RustTreeSitterHighlighter::CreateInstance (lldb::LanguageType language) static
Definition at line 30 of file RustTreeSitterHighlighter.cpp.
References lldb::eLanguageTypeRust, and RustTreeSitterHighlighter().
Referenced by Initialize(), and Terminate().
GetHighlightQuery()
llvm::StringRef RustTreeSitterHighlighter::GetHighlightQuery () const override protected virtual
Returns the tree-sitter highlight query for this language.
Implements lldb_private::TreeSitterHighlighter.
Definition at line 25 of file RustTreeSitterHighlighter.cpp.
GetLanguage()
const TSLanguage * RustTreeSitterHighlighter::GetLanguage () const override protected virtual
Returns the tree-sitter language for this highlighter.
Implements lldb_private::TreeSitterHighlighter.
Definition at line 21 of file RustTreeSitterHighlighter.cpp.
References GetLanguage(), RustTreeSitterHighlighter(), and tree_sitter_rust().
Referenced by GetLanguage().
GetName()
llvm::StringRef lldb_private::RustTreeSitterHighlighter::GetName () const inline override virtual
Returns a human readable name for the selected highlighter.
Implements lldb_private::Highlighter.
Definition at line 22 of file RustTreeSitterHighlighter.h.
GetPluginName()
llvm::StringRef lldb_private::RustTreeSitterHighlighter::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 32 of file RustTreeSitterHighlighter.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::RustTreeSitterHighlighter::GetPluginNameStatic () inline static
Definition at line 29 of file RustTreeSitterHighlighter.h.
Referenced by GetPluginName(), and Initialize().
Initialize()
void RustTreeSitterHighlighter::Initialize () static
Definition at line 36 of file RustTreeSitterHighlighter.cpp.
References CreateInstance(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Terminate()
void RustTreeSitterHighlighter::Terminate () static
Definition at line 41 of file RustTreeSitterHighlighter.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
The documentation for this class was generated from the following files:
RustTreeSitterHighlighter.h
RustTreeSitterHighlighter.cpp