LLDB: lldb_private::ValueObject::EvaluationPoint Class Reference
lldb_private::ValueObject::EvaluationPoint Class Reference
#include <ValueObject.h>
Public Member Functions
EvaluationPoint ()
EvaluationPoint (ExecutionContextScope *exe_scope, bool use_selected=false)
EvaluationPoint (const EvaluationPoint &rhs)
~EvaluationPoint ()
const ExecutionContextRef & GetExecutionContextRef () const
void SetIsConstant ()
bool IsConstant () const
ProcessModID GetModID () const
void SetUpdateID (ProcessModID new_id)
void SetNeedsUpdate ()
void SetUpdated ()
bool NeedsUpdating (bool accept_invalid_exe_ctx)
bool IsValid ()
void SetInvalid ()
Private Member Functions
bool SyncWithProcessState (bool accept_invalid_exe_ctx)
Private Attributes
ProcessModID m_mod_id
ExecutionContextRef m_exe_ctx_ref
bool m_needs_update = true
Detailed Description
Definition at line 260 of file ValueObject.h.
Constructor & Destructor Documentation
EvaluationPoint() [1/3]
ValueObject::EvaluationPoint::EvaluationPoint ()
Definition at line 3367 of file ValueObject.cpp.
References m_exe_ctx_ref, and m_mod_id.
EvaluationPoint() [2/3]
ValueObject::EvaluationPoint::EvaluationPoint (ExecutionContextScope * exe_scope, bool use_selected = false)
Definition at line 3369 of file ValueObject.cpp.
References DoNoSelectMostRelevantFrame, lldb_private::ExecutionContext::GetFrameSP(), lldb_private::ExecutionContext::GetProcessSP(), lldb_private::ExecutionContext::GetTargetSP(), lldb_private::ExecutionContext::GetThreadSP(), m_exe_ctx_ref, and m_mod_id.
EvaluationPoint() [3/3]
ValueObject::EvaluationPoint::EvaluationPoint (const EvaluationPoint & rhs)
Definition at line 3406 of file ValueObject.cpp.
References m_exe_ctx_ref, and m_mod_id.
~EvaluationPoint()
ValueObject::EvaluationPoint::~EvaluationPoint () default
Member Function Documentation
GetExecutionContextRef()
const ExecutionContextRef & lldb_private::ValueObject::EvaluationPoint::GetExecutionContextRef () const inline
Definition at line 271 of file ValueObject.h.
References m_exe_ctx_ref.
GetModID()
ProcessModID lldb_private::ValueObject::EvaluationPoint::GetModID () const inline
Definition at line 282 of file ValueObject.h.
References m_mod_id.
IsConstant()
bool lldb_private::ValueObject::EvaluationPoint::IsConstant () const inline
Definition at line 280 of file ValueObject.h.
References m_mod_id.
IsValid()
bool lldb_private::ValueObject::EvaluationPoint::IsValid () inline
Definition at line 295 of file ValueObject.h.
References m_mod_id, and SyncWithProcessState().
NeedsUpdating()
bool lldb_private::ValueObject::EvaluationPoint::NeedsUpdating (bool accept_invalid_exe_ctx) inline
Definition at line 290 of file ValueObject.h.
References m_needs_update, and SyncWithProcessState().
SetInvalid()
void lldb_private::ValueObject::EvaluationPoint::SetInvalid () inline
Definition at line 306 of file ValueObject.h.
References m_mod_id, and m_needs_update.
Referenced by SyncWithProcessState().
SetIsConstant()
void lldb_private::ValueObject::EvaluationPoint::SetIsConstant () inline
Definition at line 275 of file ValueObject.h.
References m_mod_id, and SetUpdated().
SetNeedsUpdate()
void lldb_private::ValueObject::EvaluationPoint::SetNeedsUpdate () inline
Definition at line 286 of file ValueObject.h.
References m_needs_update.
SetUpdated()
void ValueObject::EvaluationPoint::SetUpdated ()
Definition at line 3487 of file ValueObject.cpp.
References m_exe_ctx_ref, m_mod_id, and m_needs_update.
Referenced by SetIsConstant().
SetUpdateID()
void lldb_private::ValueObject::EvaluationPoint::SetUpdateID (ProcessModID new_id) inline
Definition at line 284 of file ValueObject.h.
References m_mod_id.
SyncWithProcessState()
bool ValueObject::EvaluationPoint::SyncWithProcessState (bool accept_invalid_exe_ctx) private
Definition at line 3420 of file ValueObject.cpp.
References lldb_private::Process::GetModID(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::ProcessModID::GetStopID(), lldb_private::ExecutionContext::GetTargetPtr(), m_exe_ctx_ref, m_mod_id, m_needs_update, and SetInvalid().
Referenced by IsValid(), and NeedsUpdating().
Member Data Documentation
m_exe_ctx_ref
ExecutionContextRef lldb_private::ValueObject::EvaluationPoint::m_exe_ctx_ref private
Definition at line 320 of file ValueObject.h.
Referenced by EvaluationPoint(), EvaluationPoint(), EvaluationPoint(), GetExecutionContextRef(), SetUpdated(), and SyncWithProcessState().
m_mod_id
ProcessModID lldb_private::ValueObject::EvaluationPoint::m_mod_id private
Definition at line 318 of file ValueObject.h.
Referenced by EvaluationPoint(), EvaluationPoint(), EvaluationPoint(), GetModID(), IsConstant(), IsValid(), SetInvalid(), SetIsConstant(), SetUpdated(), SetUpdateID(), and SyncWithProcessState().
m_needs_update
bool lldb_private::ValueObject::EvaluationPoint::m_needs_update = true private
Definition at line 321 of file ValueObject.h.
Referenced by NeedsUpdating(), SetInvalid(), SetNeedsUpdate(), SetUpdated(), and SyncWithProcessState().
The documentation for this class was generated from the following files:
ValueObject.h
ValueObject.cpp