LLDB: lldb_private::LoadScriptOptions Class Reference
lldb_private::LoadScriptOptions Class Reference
#include <ScriptInterpreter.h>
Public Member Functions
LoadScriptOptions ()=default
bool GetInitSession () const
bool GetSilent () const
LoadScriptOptions & SetInitSession (bool b)
LoadScriptOptions & SetSilent (bool b)
Private Attributes
bool m_init_session = false
bool m_silent = false
Detailed Description
Definition at line 93 of file ScriptInterpreter.h.
Constructor & Destructor Documentation
LoadScriptOptions()
lldb_private::LoadScriptOptions::LoadScriptOptions () default
Referenced by SetInitSession(), and SetSilent().
Member Function Documentation
GetInitSession()
bool lldb_private::LoadScriptOptions::GetInitSession () const inline
Definition at line 97 of file ScriptInterpreter.h.
References m_init_session.
GetSilent()
bool lldb_private::LoadScriptOptions::GetSilent () const inline
Definition at line 98 of file ScriptInterpreter.h.
References m_silent.
SetInitSession()
LoadScriptOptions & lldb_private::LoadScriptOptions::SetInitSession (bool b) inline
Definition at line 100 of file ScriptInterpreter.h.
References LoadScriptOptions(), and m_init_session.
Referenced by CommandObjectCommandsScriptImport::DoExecute().
SetSilent()
LoadScriptOptions & lldb_private::LoadScriptOptions::SetSilent (bool b) inline
Definition at line 105 of file ScriptInterpreter.h.
References LoadScriptOptions(), and m_silent.
Referenced by CommandObjectCommandsScriptImport::DoExecute().
Member Data Documentation
m_init_session
bool lldb_private::LoadScriptOptions::m_init_session = false private
Definition at line 111 of file ScriptInterpreter.h.
Referenced by GetInitSession(), and SetInitSession().
m_silent
bool lldb_private::LoadScriptOptions::m_silent = false private
Definition at line 112 of file ScriptInterpreter.h.
Referenced by GetSilent(), and SetSilent().
The documentation for this class was generated from the following file:
ScriptInterpreter.h