LLDB: lldb_private::PipeWindows Class Reference
lldb_private::PipeWindows Class Reference
#include <PipeWindows.h>
Public Member Functions
PipeWindows ()
PipeWindows (lldb::pipe_t read, lldb::pipe_t write)
~PipeWindows () override
Status CreateNew () override
Status CreateNew (llvm::StringRef name) override
Status CreateWithUniqueName (llvm::StringRef prefix, llvm::SmallVectorImpl< char > &name) override
Status OpenAsReader (llvm::StringRef name) override
llvm::Error OpenAsWriter (llvm::StringRef name, const Timeout< std::micro > &timeout) override
bool CanRead () const override
bool CanWrite () const override
lldb::pipe_t GetReadPipe () const override
lldb::pipe_t GetWritePipe () const override
int GetReadFileDescriptor () const override
int GetWriteFileDescriptor () const override
int ReleaseReadFileDescriptor () override
int ReleaseWriteFileDescriptor () override
void CloseReadFileDescriptor () override
void CloseWriteFileDescriptor () override
void Close () override
Status Delete (llvm::StringRef name) override
llvm::Expected< size_t > Write (const void *buf, size_t size, const Timeout< std::micro > &timeout=std::nullopt) override
llvm::Expected< size_t > Read (void *buf, size_t size, const Timeout< std::micro > &timeout=std::nullopt) override
HANDLE GetReadNativeHandle ()
HANDLE GetWriteNativeHandle ()
Public Member Functions inherited from lldb_private::PipeBase
virtual ~PipeBase ()
Static Public Attributes
static const int kInvalidDescriptor = -1
Private Member Functions
Status OpenNamedPipe (llvm::StringRef name, bool is_read)
Private Attributes
HANDLE m_read
HANDLE m_write
int m_read_fd
int m_write_fd
OVERLAPPED m_read_overlapped
OVERLAPPED m_write_overlapped
Detailed Description
Definition at line 22 of file PipeWindows.h.
Constructor & Destructor Documentation
PipeWindows() [1/2]
PipeWindows::PipeWindows ()
Definition at line 28 of file PipeWindows.cpp.
References kInvalidDescriptor, m_read, m_read_fd, m_read_overlapped, m_write, m_write_fd, m_write_overlapped, and PipeWindows().
Referenced by PipeWindows(), and PipeWindows().
PipeWindows() [2/2]
PipeWindows::PipeWindows (lldb::pipe_t read, lldb::pipe_t write)
Definition at line 36 of file PipeWindows.cpp.
References kInvalidDescriptor, LLDB_INVALID_PIPE, m_read, m_read_fd, m_read_overlapped, m_write, m_write_fd, m_write_overlapped, and PipeWindows().
~PipeWindows()
PipeWindows::~PipeWindows () override
Definition at line 67 of file PipeWindows.cpp.
References Close().
Member Function Documentation
CanRead()
bool PipeWindows::CanRead () const override virtual
Implements lldb_private::PipeBase.
Definition at line 257 of file PipeWindows.cpp.
References m_read.
Referenced by CloseReadFileDescriptor(), CreateNew(), OpenAsReader(), OpenNamedPipe(), Read(), and ReleaseReadFileDescriptor().
CanWrite()
bool PipeWindows::CanWrite () const override virtual
Implements lldb_private::PipeBase.
Definition at line 259 of file PipeWindows.cpp.
References m_write.
Referenced by CloseWriteFileDescriptor(), CreateNew(), OpenAsWriter(), OpenNamedPipe(), ReleaseWriteFileDescriptor(), and Write().
Close()
void PipeWindows::Close () override virtual
Implements lldb_private::PipeBase.
Definition at line 250 of file PipeWindows.cpp.
References CloseReadFileDescriptor(), and CloseWriteFileDescriptor().
Referenced by ~PipeWindows().
CloseReadFileDescriptor()
void PipeWindows::CloseReadFileDescriptor () override virtual
Implements lldb_private::PipeBase.
Definition at line 224 of file PipeWindows.cpp.
References CanRead(), kInvalidDescriptor, m_read, m_read_fd, and m_read_overlapped.
Referenced by Close(), and CreateNew().
CloseWriteFileDescriptor()
void PipeWindows::CloseWriteFileDescriptor () override virtual
Implements lldb_private::PipeBase.
Definition at line 237 of file PipeWindows.cpp.
References CanWrite(), kInvalidDescriptor, m_write, m_write_fd, and m_write_overlapped.
Referenced by Close().
CreateNew() [1/2]
Status PipeWindows::CreateNew () override virtual
Implements lldb_private::PipeBase.
Definition at line 69 of file PipeWindows.cpp.
References CreateNew(), and g_pipe_serial().
Referenced by CreateNew(), and CreateWithUniqueName().
CreateNew() [2/2]
Status PipeWindows::CreateNew (llvm::StringRef name) override virtual
Implements lldb_private::PipeBase.
Definition at line 80 of file PipeWindows.cpp.
References CanRead(), CanWrite(), CloseReadFileDescriptor(), lldb::eErrorTypeWin32, g_pipe_name_prefix, m_read, m_read_fd, m_read_overlapped, OpenNamedPipe(), lldb_private::Status, and lldb_private::Status::Success().
CreateWithUniqueName()
Status PipeWindows::CreateWithUniqueName (llvm::StringRef prefix, llvm::SmallVectorImpl< char > & name) override virtual
Implements lldb_private::PipeBase.
Definition at line 120 of file PipeWindows.cpp.
References CreateNew(), lldb::eErrorTypeWin32, error(), and lldb_private::Status.
Delete()
Status PipeWindows::Delete (llvm::StringRef name) override virtual
Implements lldb_private::PipeBase.
Definition at line 255 of file PipeWindows.cpp.
References lldb_private::Status.
GetReadFileDescriptor()
int PipeWindows::GetReadFileDescriptor () const override virtual
Implements lldb_private::PipeBase.
Definition at line 196 of file PipeWindows.cpp.
References m_read_fd.
GetReadNativeHandle()
HANDLE PipeWindows::GetReadNativeHandle ()
Definition at line 262 of file PipeWindows.cpp.
References m_read.
GetReadPipe()
lldb::pipe_t lldb_private::PipeWindows::GetReadPipe () const inline override virtual
Implements lldb_private::PipeBase.
Definition at line 45 of file PipeWindows.h.
References m_read.
GetWriteFileDescriptor()
int PipeWindows::GetWriteFileDescriptor () const override virtual
Implements lldb_private::PipeBase.
Definition at line 198 of file PipeWindows.cpp.
References m_write_fd.
GetWriteNativeHandle()
HANDLE PipeWindows::GetWriteNativeHandle ()
Definition at line 265 of file PipeWindows.cpp.
References m_write.
GetWritePipe()
lldb::pipe_t lldb_private::PipeWindows::GetWritePipe () const inline override virtual
Implements lldb_private::PipeBase.
Definition at line 46 of file PipeWindows.h.
References m_write.
OpenAsReader()
Status PipeWindows::OpenAsReader (llvm::StringRef name) override virtual
Implements lldb_private::PipeBase.
Definition at line 143 of file PipeWindows.cpp.
References CanRead(), OpenNamedPipe(), and lldb_private::Status.
OpenAsWriter()
llvm::Error PipeWindows::OpenAsWriter (llvm::StringRef name, const Timeout< std::micro > & timeout) override virtual
Implements lldb_private::PipeBase.
Definition at line 150 of file PipeWindows.cpp.
References CanWrite(), OpenNamedPipe(), and lldb_private::Status::takeError().
OpenNamedPipe()
Status PipeWindows::OpenNamedPipe (llvm::StringRef name, bool is_read) private
Definition at line 158 of file PipeWindows.cpp.
References CanRead(), CanWrite(), lldb::eErrorTypeWin32, g_pipe_name_prefix, m_read, m_read_fd, m_read_overlapped, m_write, m_write_fd, m_write_overlapped, and lldb_private::Status.
Referenced by CreateNew(), OpenAsReader(), and OpenAsWriter().
Read()
llvm::Expected< size_t > PipeWindows::Read (void * buf, size_t size, const Timeout< std::micro > & timeout = std::nullopt) override virtual
Implements lldb_private::PipeBase.
Definition at line 267 of file PipeWindows.cpp.
References CanRead(), lldb::eErrorTypeWin32, m_read, m_read_overlapped, and lldb_private::Status.
ReleaseReadFileDescriptor()
int PipeWindows::ReleaseReadFileDescriptor () override virtual
Implements lldb_private::PipeBase.
Definition at line 200 of file PipeWindows.cpp.
References CanRead(), kInvalidDescriptor, m_read, m_read_fd, and m_read_overlapped.
ReleaseWriteFileDescriptor()
int PipeWindows::ReleaseWriteFileDescriptor () override virtual
Implements lldb_private::PipeBase.
Definition at line 212 of file PipeWindows.cpp.
References CanWrite(), kInvalidDescriptor, m_write, m_write_fd, and m_write_overlapped.
Write()
llvm::Expected< size_t > PipeWindows::Write (const void * buf, size_t size, const Timeout< std::micro > & timeout = std::nullopt) override virtual
Implements lldb_private::PipeBase.
Definition at line 312 of file PipeWindows.cpp.
References CanWrite(), lldb::eErrorTypeWin32, m_write, m_write_overlapped, and lldb_private::Status.
Member Data Documentation
kInvalidDescriptor
const int lldb_private::PipeWindows::kInvalidDescriptor = -1 static
Definition at line 24 of file PipeWindows.h.
Referenced by CloseReadFileDescriptor(), CloseWriteFileDescriptor(), PipeWindows(), PipeWindows(), ReleaseReadFileDescriptor(), and ReleaseWriteFileDescriptor().
m_read
HANDLE lldb_private::PipeWindows::m_read private
Definition at line 75 of file PipeWindows.h.
Referenced by CanRead(), CloseReadFileDescriptor(), CreateNew(), GetReadNativeHandle(), GetReadPipe(), OpenNamedPipe(), PipeWindows(), PipeWindows(), Read(), and ReleaseReadFileDescriptor().
m_read_fd
int lldb_private::PipeWindows::m_read_fd private
Definition at line 78 of file PipeWindows.h.
Referenced by CloseReadFileDescriptor(), CreateNew(), GetReadFileDescriptor(), OpenNamedPipe(), PipeWindows(), PipeWindows(), and ReleaseReadFileDescriptor().
m_read_overlapped
OVERLAPPED lldb_private::PipeWindows::m_read_overlapped private
Definition at line 81 of file PipeWindows.h.
Referenced by CloseReadFileDescriptor(), CreateNew(), OpenNamedPipe(), PipeWindows(), PipeWindows(), Read(), and ReleaseReadFileDescriptor().
m_write
HANDLE lldb_private::PipeWindows::m_write private
Definition at line 76 of file PipeWindows.h.
Referenced by CanWrite(), CloseWriteFileDescriptor(), GetWriteNativeHandle(), GetWritePipe(), OpenNamedPipe(), PipeWindows(), PipeWindows(), ReleaseWriteFileDescriptor(), and Write().
m_write_fd
int lldb_private::PipeWindows::m_write_fd private
Definition at line 79 of file PipeWindows.h.
Referenced by CloseWriteFileDescriptor(), GetWriteFileDescriptor(), OpenNamedPipe(), PipeWindows(), PipeWindows(), and ReleaseWriteFileDescriptor().
m_write_overlapped
OVERLAPPED lldb_private::PipeWindows::m_write_overlapped private
Definition at line 82 of file PipeWindows.h.
Referenced by CloseWriteFileDescriptor(), OpenNamedPipe(), PipeWindows(), PipeWindows(), ReleaseWriteFileDescriptor(), and Write().
The documentation for this class was generated from the following files:
PipeWindows.h
PipeWindows.cpp