LLDB: lldb_private::NativeProcessWindows Class Reference
lldb_private::NativeProcessWindows Class Reference
#include <NativeProcessWindows.h>
Classes
class Manager
Public Member Functions
Status Resume (const ResumeActionList &resume_actions) override
Status Halt () override
Status Detach () override
Status Signal (int signo) override
Sends a process a UNIX signal signal.
Status Interrupt () override
Tells a process to interrupt all operations as if by a Ctrl-C.
Status Kill () override
Status IgnoreSignals (llvm::ArrayRef< int > signals) override
Status GetMemoryRegionInfo (lldb::addr_t load_addr, MemoryRegionInfo &range_info) override
Status ReadMemory (lldb::addr_t addr, void *buf, size_t size, size_t &bytes_read) override
Status WriteMemory (lldb::addr_t addr, const void *buf, size_t size, size_t &bytes_written) override
llvm::Expected< lldb::addr_t > AllocateMemory (size_t size, uint32_t permissions) override
llvm::Error DeallocateMemory (lldb::addr_t addr) override
lldb::addr_t GetSharedLibraryInfoAddress () override
bool IsAlive () const override
size_t UpdateThreads () override
const ArchSpec & GetArchitecture () const override
void SetArchitecture (const ArchSpec &arch_spec)
Status SetBreakpoint (lldb::addr_t addr, uint32_t size, bool hardware) override
Status RemoveBreakpoint (lldb::addr_t addr, bool hardware=false) override
llvm::ErrorOr< std::unique_ptr< llvm::MemoryBuffer > > GetAuxvData () const override
Status GetLoadedModuleFileSpec (const char *module_path, FileSpec &file_spec) override
Status GetFileLoadAddress (const llvm::StringRef &file_name, lldb::addr_t &load_addr) override
void OnExitProcess (uint32_t exit_code) override
void OnDebuggerConnected (lldb::addr_t image_base) override
ExceptionResult OnDebugException (bool first_chance, const ExceptionRecord &record) override
void OnCreateThread (const HostThread &thread) override
void OnExitThread (lldb::tid_t thread_id, uint32_t exit_code) override
void OnLoadDll (const ModuleSpec &module_spec, lldb::addr_t module_addr) override
void OnUnloadDll (lldb::addr_t module_addr) override
Public Member Functions inherited from lldb_private::NativeProcessProtocol
virtual ~NativeProcessProtocol ()=default
Status ReadMemoryWithoutTrap (lldb::addr_t addr, void *buf, size_t size, size_t &bytes_read)
virtual Status ReadMemoryTags (int32_t type, lldb::addr_t addr, size_t len, std::vector< uint8_t > &tags)
virtual Status WriteMemoryTags (int32_t type, lldb::addr_t addr, size_t len, const std::vector< uint8_t > &tags)
llvm::Expected< llvm::StringRef > ReadCStringFromMemory (lldb::addr_t addr, char *buffer, size_t max_size, size_t &total_bytes_read)
Reads a null terminated string from memory.
virtual llvm::Expected< std::vector< SVR4LibraryInfo > > GetLoadedSVR4Libraries ()
virtual const HardwareBreakpointMap & GetHardwareBreakpointMap () const
virtual Status SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual Status RemoveHardwareBreakpoint (lldb::addr_t addr)
virtual const NativeWatchpointList::WatchpointMap & GetWatchpointMap () const
virtual std::optional< std::pair< uint32_t, uint32_t > > GetHardwareDebugSupportInfo () const
virtual Status SetWatchpoint (lldb::addr_t addr, size_t size, uint32_t watch_flags, bool hardware)
virtual Status RemoveWatchpoint (lldb::addr_t addr)
lldb::pid_t GetID () const
lldb::StateType GetState () const
bool IsRunning () const
bool IsStepping () const
bool CanResume () const
lldb::ByteOrder GetByteOrder () const
uint32_t GetAddressByteSize () const
virtual std::optional< WaitStatus > GetExitStatus ()
virtual bool SetExitStatus (WaitStatus status, bool bNotifyStateChange)
NativeThreadProtocol * GetThreadAtIndex (uint32_t idx)
NativeThreadProtocol * GetThreadByID (lldb::tid_t tid)
void SetCurrentThreadID (lldb::tid_t tid)
lldb::tid_t GetCurrentThreadID () const
NativeThreadProtocol * GetCurrentThread ()
ThreadIterable Threads () const
virtual int GetTerminalFileDescriptor ()
uint32_t GetStopID () const
virtual void NotifyTracersProcessWillResume ()
Notify tracers that the target process will resume.
virtual void NotifyTracersProcessDidStop ()
Notify tracers that the target process just stopped.
virtual llvm::Error TraceStart (llvm::StringRef json_params, llvm::StringRef type)
Start tracing a process or its threads.
virtual llvm::Error TraceStop (const TraceStopRequest &request)
Stop tracing a live process or its threads.
virtual llvm::Expected< llvm::json::Value > TraceGetState (llvm::StringRef type)
Get the current tracing state of the process and its threads.
virtual llvm::Expected< std::vector< uint8_t > > TraceGetBinaryData (const TraceGetBinaryDataRequest &request)
Get binary data given a trace technology and a data identifier.
virtual llvm::Expected< TraceSupportedResponse > TraceSupported ()
Get the processor tracing type supported for this process.
virtual void SetEnabledExtensions (Extension flags)
Method called in order to propagate the bitmap of protocol extensions supported by the client.
virtual llvm::Expected< std::string > SaveCore (llvm::StringRef path_hint)
Write a core dump (without crashing the program).
virtual std::vector< std::string > GetStructuredDataPlugins ()
Get the list of structured data plugins supported by this process.
Public Member Functions inherited from lldb_private::ProcessDebugger
virtual ~ProcessDebugger ()
virtual void OnDebugString (const std::string &string)
virtual void OnDebuggerError (const Status &error, uint32_t type)
Protected Member Functions
NativeThreadWindows * GetThreadByID (lldb::tid_t thread_id)
llvm::Expected< llvm::ArrayRef< uint8_t > > GetSoftwareBreakpointTrapOpcode (size_t size_hint) override
size_t GetSoftwareBreakpointPCOffset () override
Return the offset of the PC relative to the software breakpoint that was hit.
bool FindSoftwareBreakpoint (lldb::addr_t addr)
void StopThread (lldb::tid_t thread_id, lldb::StopReason reason, std::string description="")
void SetStopReasonForThread (NativeThreadWindows &thread, lldb::StopReason reason, std::string description="")
Protected Member Functions inherited from lldb_private::NativeProcessProtocol
NativeProcessProtocol (lldb::pid_t pid, int terminal_fd, NativeDelegate &delegate)
void SetID (lldb::pid_t pid)
void SetState (lldb::StateType state, bool notify_delegates=true)
virtual void DoStopIDBumped (uint32_t newBumpId)
Status SetSoftwareBreakpoint (lldb::addr_t addr, uint32_t size_hint)
Status RemoveSoftwareBreakpoint (lldb::addr_t addr)
void FixupBreakpointPCAsNeeded (NativeThreadProtocol &thread)
virtual void NotifyDidExec ()
Notify the delegate that an exec occurred.
NativeThreadProtocol * GetThreadByIDUnlocked (lldb::tid_t tid)
Protected Member Functions inherited from lldb_private::ProcessDebugger
Status DetachProcess ()
Status LaunchProcess (ProcessLaunchInfo &launch_info, DebugDelegateSP delegate)
Status AttachProcess (lldb::pid_t pid, const ProcessAttachInfo &attach_info, DebugDelegateSP delegate)
Status DestroyProcess (lldb::StateType process_state)
Status HaltProcess (bool &caused_stop)
Status GetMemoryRegionInfo (lldb::addr_t load_addr, MemoryRegionInfo &range_info)
Status ReadMemory (lldb::addr_t addr, void *buf, size_t size, size_t &bytes_read)
Status WriteMemory (lldb::addr_t addr, const void *buf, size_t size, size_t &bytes_written)
Status AllocateMemory (size_t size, uint32_t permissions, lldb::addr_t &addr)
Status DeallocateMemory (lldb::addr_t addr)
lldb::pid_t GetDebuggedProcessId () const
Status WaitForDebuggerConnection (DebuggerThreadSP debugger, HostProcess &process)
Private Member Functions
NativeProcessWindows (ProcessLaunchInfo &launch_info, NativeDelegate &delegate, llvm::Error &E)
NativeProcessWindows (lldb::pid_t pid, int terminal_fd, NativeDelegate &delegate, llvm::Error &E)
Status CacheLoadedModules ()
Private Attributes
ArchSpec m_arch
std::map< lldb_private::FileSpec, lldb::addr_t > m_loaded_modules
Additional Inherited Members
Public Types inherited from lldb_private::NativeProcessProtocol
enum class Extension {
multiprocess = (1u << 0) , fork = (1u << 1) , vfork = (1u << 2) , pass_signals = (1u << 3) ,
auxv = (1u << 4) , libraries_svr4 = (1u << 5) , memory_tagging = (1u << 6) , savecore = (1u << 7) ,
siginfo_read = (1u << 8)
}
Extension flag constants, returned by Manager::GetSupportedExtensions() and passed to SetEnabledExtension()
typedef std::vector< std::unique_ptr< NativeThreadProtocol > > thread_collection
typedef LockingAdaptedIterable< std::recursive_mutex, thread_collection, llvm::pointee_iterator< thread_collection::const_iterator > > ThreadIterable
Protected Attributes inherited from lldb_private::NativeProcessProtocol
std::unordered_map< lldb::addr_t, SoftwareBreakpoint > m_software_breakpoints
lldb::pid_t m_pid
std::vector< std::unique_ptr< NativeThreadProtocol > > m_threads
lldb::tid_t m_current_thread_id = LLDB_INVALID_THREAD_ID
std::recursive_mutex m_threads_mutex
lldb::StateType m_state = lldb::eStateInvalid
std::recursive_mutex m_state_mutex
std::optional< WaitStatus > m_exit_status
NativeDelegate & m_delegate
NativeWatchpointList m_watchpoint_list
HardwareBreakpointMap m_hw_breakpoints_map
int m_terminal_fd
uint32_t m_stop_id = 0
llvm::DenseSet< int > m_signals_to_ignore
Extension m_enabled_extensions
Protected Attributes inherited from lldb_private::ProcessDebugger
llvm::sys::Mutex m_mutex
std::unique_ptr< ProcessWindowsData > m_session_data
Detailed Description
Definition at line 30 of file NativeProcessWindows.h.
Constructor & Destructor Documentation
NativeProcessWindows() [1/2]
lldb_private::NativeProcessWindows::NativeProcessWindows (ProcessLaunchInfo & launch_info, NativeDelegate & delegate, llvm::Error & E) private
Definition at line 48 of file NativeProcessWindows.cpp.
References GetArchitecture(), lldb_private::ProcessDebugger::GetDebuggedProcessId(), lldb_private::ProcessDebugger::LaunchProcess(), LLDB_INVALID_PROCESS_ID, m_arch, lldb_private::NativeProcessProtocol::NativeProcessProtocol(), lldb_private::NativeProcessProtocol::SetID(), and lldb_private::Status::ToError().
Referenced by lldb_private::NativeProcessWindows::Manager::Attach(), and lldb_private::NativeProcessWindows::Manager::Launch().
NativeProcessWindows() [2/2]
lldb_private::NativeProcessWindows::NativeProcessWindows (lldb::pid_t pid, int terminal_fd, NativeDelegate & delegate, llvm::Error & E) private
Definition at line 65 of file NativeProcessWindows.cpp.
References lldb_private::ProcessDebugger::AttachProcess(), createStringError(), lldb_private::ProcessInfo::GetArchitecture(), lldb_private::ProcessDebugger::GetDebuggedProcessId(), lldb_private::Host::GetProcessInfo(), m_arch, lldb_private::NativeProcessProtocol::NativeProcessProtocol(), lldb_private::NativeProcessProtocol::SetID(), lldb_private::ProcessInfo::SetProcessID(), and lldb_private::Status::ToError().
Member Function Documentation
AllocateMemory()
llvm::Expected< lldb::addr_t > lldb_private::NativeProcessWindows::AllocateMemory (size_t size, uint32_t permissions) override virtual
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 225 of file NativeProcessWindows.cpp.
References lldb_private::ProcessDebugger::AllocateMemory(), lldb_private::Status::Success(), and lldb_private::Status::ToError().
CacheLoadedModules()
Status lldb_private::NativeProcessWindows::CacheLoadedModules () private
Definition at line 341 of file NativeProcessWindows.cpp.
References lldb::eErrorTypeWin32, error(), lldb_private::AutoHandle::get(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::FileSystem::Instance(), lldb_private::AutoHandle::IsValid(), m_loaded_modules, lldb_private::FileSystem::Resolve(), and lldb_private::Status.
Referenced by GetFileLoadAddress(), and GetLoadedModuleFileSpec().
DeallocateMemory()
llvm::Error lldb_private::NativeProcessWindows::DeallocateMemory (lldb::addr_t addr) override virtual
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 233 of file NativeProcessWindows.cpp.
References lldb_private::ProcessDebugger::DeallocateMemory(), and lldb_private::Status::ToError().
Detach()
Status lldb_private::NativeProcessWindows::Detach () override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 171 of file NativeProcessWindows.cpp.
References lldb_private::ProcessDebugger::DetachProcess(), error(), lldb::eStateDetached, lldb::eStateExited, lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), lldb_private::NativeProcessProtocol::GetState(), LLDB_LOG, lldb_private::Process, and lldb_private::NativeProcessProtocol::SetState().
FindSoftwareBreakpoint()
bool lldb_private::NativeProcessWindows::FindSoftwareBreakpoint (lldb::addr_t addr) protected
Definition at line 320 of file NativeProcessWindows.cpp.
References lldb_private::NativeProcessProtocol::m_software_breakpoints.
Referenced by OnDebugException().
GetArchitecture()
const ArchSpec & lldb_private::NativeProcessWindows::GetArchitecture () const inline override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 80 of file NativeProcessWindows.h.
References m_arch.
Referenced by GetSoftwareBreakpointTrapOpcode(), NativeProcessWindows(), lldb_private::NativeThreadWindows::NativeThreadWindows(), and OnDebuggerConnected().
GetAuxvData()
llvm::ErrorOr< std::unique_ptr< llvm::MemoryBuffer > > lldb_private::NativeProcessWindows::GetAuxvData () const override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 290 of file NativeProcessWindows.cpp.
GetFileLoadAddress()
Status lldb_private::NativeProcessWindows::GetFileLoadAddress (const llvm::StringRef & file_name, lldb::addr_t & load_addr) override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 391 of file NativeProcessWindows.cpp.
References CacheLoadedModules(), error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::FileSpec::GetPath(), lldb_private::FileSystem::Instance(), LLDB_INVALID_ADDRESS, m_loaded_modules, lldb_private::FileSystem::Resolve(), and lldb_private::Status.
GetLoadedModuleFileSpec()
Status lldb_private::NativeProcessWindows::GetLoadedModuleFileSpec (const char * module_path, FileSpec & file_spec) override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 371 of file NativeProcessWindows.cpp.
References CacheLoadedModules(), error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::FileSpec::GetPath(), lldb_private::FileSystem::Instance(), m_loaded_modules, lldb_private::FileSystem::Resolve(), and lldb_private::Status.
GetMemoryRegionInfo()
Status lldb_private::NativeProcessWindows::GetMemoryRegionInfo (lldb::addr_t load_addr, MemoryRegionInfo & range_info) override virtual
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 209 of file NativeProcessWindows.cpp.
References lldb_private::ProcessDebugger::GetMemoryRegionInfo().
GetSharedLibraryInfoAddress()
lldb::addr_t lldb_private::NativeProcessWindows::GetSharedLibraryInfoAddress () override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 237 of file NativeProcessWindows.cpp.
GetSoftwareBreakpointPCOffset()
size_t lldb_private::NativeProcessWindows::GetSoftwareBreakpointPCOffset () override protected virtual
Return the offset of the PC relative to the software breakpoint that was hit.
If an architecture (e.g. arm) reports breakpoint hits before incrementing the PC, this offset will be 0. If an architecture (e.g. intel) reports breakpoints hits after incrementing the PC, this offset will be the size of the breakpoint opcode.
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 314 of file NativeProcessWindows.cpp.
References GetSoftwareBreakpointTrapOpcode().
Referenced by OnDebugException().
GetSoftwareBreakpointTrapOpcode()
llvm::Expected< llvm::ArrayRef< uint8_t > > lldb_private::NativeProcessWindows::GetSoftwareBreakpointTrapOpcode (size_t size_hint) override protected virtual
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 296 of file NativeProcessWindows.cpp.
References GetArchitecture(), and lldb_private::NativeProcessProtocol::GetSoftwareBreakpointTrapOpcode().
Referenced by GetSoftwareBreakpointPCOffset().
GetThreadByID()
NativeThreadWindows * lldb_private::NativeProcessWindows::GetThreadByID (lldb::tid_t thread_id) protected
Definition at line 158 of file NativeProcessWindows.cpp.
References lldb_private::NativeProcessProtocol::GetThreadByID().
Referenced by OnDebugException(), OnExitThread(), and StopThread().
Halt()
Status lldb_private::NativeProcessWindows::Halt () override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 163 of file NativeProcessWindows.cpp.
References lldb::eStateStopped, lldb_private::NativeProcessProtocol::GetState(), lldb_private::ProcessDebugger::HaltProcess(), and lldb_private::Status.
Referenced by Interrupt().
IgnoreSignals()
Status lldb_private::NativeProcessWindows::IgnoreSignals (llvm::ArrayRef< int > signals) override virtual
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 205 of file NativeProcessWindows.cpp.
References lldb_private::Status.
Interrupt()
Status lldb_private::NativeProcessWindows::Interrupt () override virtual
Tells a process to interrupt all operations as if by a Ctrl-C.
The default implementation will send a local host's equivalent of a SIGSTOP to the process via the NativeProcessProtocol::Signal() operation.
Returns
Returns an error object.
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 198 of file NativeProcessWindows.cpp.
References Halt().
IsAlive()
bool lldb_private::NativeProcessWindows::IsAlive () const override virtual
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 239 of file NativeProcessWindows.cpp.
References lldb::eStateCrashed, lldb::eStateDetached, lldb::eStateExited, lldb::eStateInvalid, lldb::eStateUnloaded, and lldb_private::NativeProcessProtocol::GetState().
Kill()
Status lldb_private::NativeProcessWindows::Kill () override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 200 of file NativeProcessWindows.cpp.
References lldb_private::ProcessDebugger::DestroyProcess(), and lldb_private::NativeProcessProtocol::GetState().
OnCreateThread()
void lldb_private::NativeProcessWindows::OnCreateThread (const HostThread & thread) override virtual
Reimplemented from lldb_private::ProcessDebugger.
Definition at line 599 of file NativeProcessWindows.cpp.
References lldb_private::NativeProcessProtocol::GetWatchpointMap(), lldb_private::NativeWatchpoint::m_addr, lldb_private::NativeWatchpoint::m_hardware, lldb_private::ProcessDebugger::m_mutex, lldb_private::NativeWatchpoint::m_size, lldb_private::NativeProcessProtocol::m_threads, and lldb_private::NativeWatchpoint::m_watch_flags.
OnDebugException()
ExceptionResult lldb_private::NativeProcessWindows::OnDebugException (bool first_chance, const ExceptionRecord & record) override virtual
Reimplemented from lldb_private::ProcessDebugger.
Definition at line 452 of file NativeProcessWindows.cpp.
References BreakInDebugger, error(), lldb::eStateStopped, lldb::eStopReasonBreakpoint, lldb::eStopReasonException, lldb::eStopReasonTrace, lldb::eStopReasonWatchpoint, lldb_private::Exception, FindSoftwareBreakpoint(), lldb_private::ExceptionRecord::GetExceptionAddress(), lldb_private::ExceptionRecord::GetExceptionArguments(), lldb_private::ExceptionRecord::GetExceptionCode(), lldb_private::GetLog(), GetSoftwareBreakpointPCOffset(), GetThreadByID(), lldb_private::ExceptionRecord::GetThreadID(), lldb_private::NativeRegisterContext::GetWatchpointAddress(), lldb_private::NativeRegisterContext::GetWatchpointHitAddress(), lldb_private::NativeRegisterContext::GetWatchpointHitIndex(), LLDB_INVALID_INDEX32, LLDB_LOG, lldb_private::ProcessDebugger::m_mutex, MaskException, lldb_private::ProcessDebugger::OnDebugException(), SendToApplication, lldb_private::NativeProcessProtocol::SetState(), SetStopReasonForThread(), STATUS_WX86_BREAKPOINT, and StopThread().
OnDebuggerConnected()
void lldb_private::NativeProcessWindows::OnDebuggerConnected (lldb::addr_t image_base) override virtual
Reimplemented from lldb_private::ProcessDebugger.
Definition at line 425 of file NativeProcessWindows.cpp.
References GetArchitecture(), lldb_private::ProcessInfo::GetArchitecture(), lldb_private::ProcessDebugger::GetDebuggedProcessId(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), lldb_private::Host::GetProcessInfo(), LLDB_INVALID_PROCESS_ID, LLDB_LOG, lldb_private::ProcessDebugger::m_session_data, lldb_private::NativeProcessProtocol::m_threads, lldb_private::Process, SetArchitecture(), and lldb_private::NativeProcessProtocol::SetID().
OnExitProcess()
void lldb_private::NativeProcessWindows::OnExitProcess (uint32_t exit_code) override virtual
Reimplemented from lldb_private::ProcessDebugger.
Definition at line 411 of file NativeProcessWindows.cpp.
References lldb::eStateExited, lldb_private::WaitStatus::Exit, lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), LLDB_LOG, lldb_private::ProcessDebugger::OnExitProcess(), lldb_private::Process, lldb_private::NativeProcessProtocol::SetExitStatus(), and lldb_private::NativeProcessProtocol::SetState().
OnExitThread()
void lldb_private::NativeProcessWindows::OnExitThread (lldb::tid_t thread_id, uint32_t exit_code) override virtual
Reimplemented from lldb_private::ProcessDebugger.
Definition at line 613 of file NativeProcessWindows.cpp.
References GetThreadByID(), lldb_private::ProcessDebugger::m_mutex, and lldb_private::NativeProcessProtocol::m_threads.
OnLoadDll()
void lldb_private::NativeProcessWindows::OnLoadDll (const ModuleSpec & module_spec, lldb::addr_t module_addr) override virtual
Reimplemented from lldb_private::ProcessDebugger.
Definition at line 629 of file NativeProcessWindows.cpp.
References m_loaded_modules.
OnUnloadDll()
void lldb_private::NativeProcessWindows::OnUnloadDll (lldb::addr_t module_addr) override virtual
Reimplemented from lldb_private::ProcessDebugger.
Definition at line 636 of file NativeProcessWindows.cpp.
References m_loaded_modules.
ReadMemory()
Status lldb_private::NativeProcessWindows::ReadMemory (lldb::addr_t addr, void * buf, size_t size, size_t & bytes_read) override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 214 of file NativeProcessWindows.cpp.
References lldb_private::ProcessDebugger::ReadMemory().
RemoveBreakpoint()
Status lldb_private::NativeProcessWindows::RemoveBreakpoint (lldb::addr_t addr, bool hardware = false) override virtual
Reimplemented from lldb_private::NativeProcessProtocol.
Definition at line 334 of file NativeProcessWindows.cpp.
References lldb_private::NativeProcessProtocol::RemoveHardwareBreakpoint(), and lldb_private::NativeProcessProtocol::RemoveSoftwareBreakpoint().
Resume()
Status lldb_private::NativeProcessWindows::Resume (const ResumeActionList & resume_actions) override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 88 of file NativeProcessWindows.cpp.
References error(), lldb::eStateCrashed, lldb::eStateRunning, lldb::eStateStepping, lldb::eStateStopped, lldb::eStateSuspended, lldb_private::Status::Fail(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::ResumeActionList::GetActionForThread(), lldb_private::ProcessDebugger::GetDebuggedProcessId(), lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), lldb_private::NativeProcessProtocol::GetState(), LLDB_LOG, lldb_private::ProcessDebugger::m_mutex, lldb_private::ProcessDebugger::m_session_data, lldb_private::NativeProcessProtocol::m_threads, MaskException, lldb_private::Process, lldb_private::NativeProcessProtocol::SetState(), lldb_private::ResumeAction::state, and lldb_private::StateAsCString().
SetArchitecture()
void lldb_private::NativeProcessWindows::SetArchitecture (const ArchSpec & arch_spec) inline
Definition at line 82 of file NativeProcessWindows.h.
References m_arch.
Referenced by OnDebuggerConnected().
SetBreakpoint()
Status lldb_private::NativeProcessWindows::SetBreakpoint (lldb::addr_t addr, uint32_t size, bool hardware) override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 327 of file NativeProcessWindows.cpp.
References lldb_private::NativeProcessProtocol::SetHardwareBreakpoint(), and lldb_private::NativeProcessProtocol::SetSoftwareBreakpoint().
SetStopReasonForThread()
void lldb_private::NativeProcessWindows::SetStopReasonForThread (NativeThreadWindows & thread, lldb::StopReason reason, std::string description = "") protected
Definition at line 253 of file NativeProcessWindows.cpp.
References lldb_private::ThreadStopInfo::data_count, lldb_private::ThreadStopInfo::details, lldb::eStopReasonException, lldb_private::ThreadStopInfo::exception, lldb_private::ThreadStopInfo::reason, lldb_private::NativeProcessProtocol::SetCurrentThreadID(), lldb_private::ThreadStopInfo::signo, SIGTRAP, and lldb_private::ThreadStopInfo::type.
Referenced by OnDebugException(), and StopThread().
Signal()
Status lldb_private::NativeProcessWindows::Signal (int signo) override virtual
Sends a process a UNIX signal signal.
Returns
Returns an error object.
Implements lldb_private::NativeProcessProtocol.
Definition at line 191 of file NativeProcessWindows.cpp.
References error(), and lldb_private::Status::FromErrorString().
StopThread()
void lldb_private::NativeProcessWindows::StopThread (lldb::tid_t thread_id, lldb::StopReason reason, std::string description = "") protected
Definition at line 271 of file NativeProcessWindows.cpp.
References error(), GetThreadByID(), lldb_private::NativeProcessProtocol::m_threads, and SetStopReasonForThread().
Referenced by OnDebugException().
UpdateThreads()
size_t lldb_private::NativeProcessWindows::UpdateThreads () override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 287 of file NativeProcessWindows.cpp.
References lldb_private::NativeProcessProtocol::m_threads.
WriteMemory()
Status lldb_private::NativeProcessWindows::WriteMemory (lldb::addr_t addr, const void * buf, size_t size, size_t & bytes_written) override virtual
Implements lldb_private::NativeProcessProtocol.
Definition at line 219 of file NativeProcessWindows.cpp.
References lldb_private::ProcessDebugger::WriteMemory().
Member Data Documentation
m_arch
ArchSpec lldb_private::NativeProcessWindows::m_arch private
Definition at line 127 of file NativeProcessWindows.h.
Referenced by GetArchitecture(), NativeProcessWindows(), NativeProcessWindows(), and SetArchitecture().
m_loaded_modules
std::map<lldb_private::FileSpec, lldb::addr_t> lldb_private::NativeProcessWindows::m_loaded_modules private
Definition at line 136 of file NativeProcessWindows.h.
Referenced by CacheLoadedModules(), GetFileLoadAddress(), GetLoadedModuleFileSpec(), OnLoadDll(), and OnUnloadDll().
The documentation for this class was generated from the following files:
NativeProcessWindows.h
NativeProcessWindows.cpp