LLDB: lldb_private::TypeFormatImpl Class Reference
lldb_private::TypeFormatImpl Class Reference abstract
#include <TypeFormat.h>
Classes
class Flags
Public Types
enum class Type { eTypeUnknown , eTypeFormat , eTypeEnum }
typedef std::shared_ptr< TypeFormatImpl > SharedPointer
Public Member Functions
TypeFormatImpl (const Flags &flags=Flags())
virtual ~TypeFormatImpl ()
bool Cascades () const
bool SkipsPointers () const
bool SkipsReferences () const
bool NonCacheable () const
void SetCascades (bool value)
void SetSkipsPointers (bool value)
void SetSkipsReferences (bool value)
void SetNonCacheable (bool value)
uint32_t GetOptions ()
void SetOptions (uint32_t value)
uint32_t GetPtrMatchDepth ()
void SetPtrMatchDepth (uint32_t value)
uint32_t & GetRevision ()
virtual Type GetType ()
virtual bool FormatObject (ValueObject *valobj, std::string &dest) const =0
virtual std::string GetDescription ()=0
Protected Attributes
Flags m_flags
uint32_t m_my_revision = 0
uint32_t m_ptr_match_depth = 1
Private Member Functions
TypeFormatImpl (const TypeFormatImpl &)=delete
const TypeFormatImpl & operator= (const TypeFormatImpl &)=delete
Detailed Description
Definition at line 24 of file TypeFormat.h.
Member Typedef Documentation
SharedPointer
typedef std::shared_ptr<TypeFormatImpl> lldb_private::TypeFormatImpl::SharedPointer
Definition at line 112 of file TypeFormat.h.
Member Enumeration Documentation
Type
enum class lldb_private::TypeFormatImpl::Type strong
Enumerator
eTypeUnknown
eTypeFormat
eTypeEnum
Definition at line 142 of file TypeFormat.h.
Constructor & Destructor Documentation
TypeFormatImpl() [1/2]
TypeFormatImpl::TypeFormatImpl (const Flags & flags = Flags())
Definition at line 31 of file TypeFormat.cpp.
References m_flags.
Referenced by operator=(), TypeFormatImpl(), lldb_private::TypeFormatImpl_EnumType::TypeFormatImpl_EnumType(), and lldb_private::TypeFormatImpl_Format::TypeFormatImpl_Format().
~TypeFormatImpl()
TypeFormatImpl::~TypeFormatImpl () virtual default
TypeFormatImpl() [2/2]
lldb_private::TypeFormatImpl::TypeFormatImpl (const TypeFormatImpl &) private delete
References TypeFormatImpl().
Member Function Documentation
Cascades()
bool lldb_private::TypeFormatImpl::Cascades () const inline
Definition at line 116 of file TypeFormat.h.
References m_flags.
Referenced by lldb_private::TypeFormatImpl_EnumType::GetDescription(), and lldb_private::TypeFormatImpl_Format::GetDescription().
FormatObject()
virtual bool lldb_private::TypeFormatImpl::FormatObject (ValueObject * valobj, std::string & dest) const pure virtual
Implemented in lldb_private::TypeFormatImpl_EnumType, and lldb_private::TypeFormatImpl_Format.
Referenced by lldb_private::ValueObject::GetValueAsCString().
GetDescription()
virtual std::string lldb_private::TypeFormatImpl::GetDescription () pure virtual
Implemented in lldb_private::TypeFormatImpl_EnumType, and lldb_private::TypeFormatImpl_Format.
GetOptions()
uint32_t lldb_private::TypeFormatImpl::GetOptions () inline
Definition at line 132 of file TypeFormat.h.
References m_flags.
GetPtrMatchDepth()
uint32_t lldb_private::TypeFormatImpl::GetPtrMatchDepth () inline
Definition at line 136 of file TypeFormat.h.
References m_ptr_match_depth.
GetRevision()
uint32_t & lldb_private::TypeFormatImpl::GetRevision () inline
Definition at line 140 of file TypeFormat.h.
References m_my_revision.
GetType()
virtual Type lldb_private::TypeFormatImpl::GetType () inline virtual
Reimplemented in lldb_private::TypeFormatImpl_EnumType, and lldb_private::TypeFormatImpl_Format.
Definition at line 144 of file TypeFormat.h.
References eTypeUnknown.
NonCacheable()
bool lldb_private::TypeFormatImpl::NonCacheable () const inline
Definition at line 122 of file TypeFormat.h.
References m_flags.
operator=()
const TypeFormatImpl & lldb_private::TypeFormatImpl::operator= (const TypeFormatImpl &) private delete
References TypeFormatImpl().
SetCascades()
void lldb_private::TypeFormatImpl::SetCascades (bool value) inline
Definition at line 124 of file TypeFormat.h.
References m_flags.
SetNonCacheable()
void lldb_private::TypeFormatImpl::SetNonCacheable (bool value) inline
Definition at line 130 of file TypeFormat.h.
References m_flags.
SetOptions()
void lldb_private::TypeFormatImpl::SetOptions (uint32_t value) inline
Definition at line 134 of file TypeFormat.h.
References m_flags.
SetPtrMatchDepth()
void lldb_private::TypeFormatImpl::SetPtrMatchDepth (uint32_t value) inline
Definition at line 138 of file TypeFormat.h.
References m_ptr_match_depth.
SetSkipsPointers()
void lldb_private::TypeFormatImpl::SetSkipsPointers (bool value) inline
Definition at line 126 of file TypeFormat.h.
References m_flags.
SetSkipsReferences()
void lldb_private::TypeFormatImpl::SetSkipsReferences (bool value) inline
Definition at line 128 of file TypeFormat.h.
References m_flags.
SkipsPointers()
bool lldb_private::TypeFormatImpl::SkipsPointers () const inline
Definition at line 118 of file TypeFormat.h.
References m_flags.
Referenced by lldb_private::TypeFormatImpl_EnumType::GetDescription(), and lldb_private::TypeFormatImpl_Format::GetDescription().
SkipsReferences()
bool lldb_private::TypeFormatImpl::SkipsReferences () const inline
Definition at line 120 of file TypeFormat.h.
References m_flags.
Referenced by lldb_private::TypeFormatImpl_EnumType::GetDescription(), and lldb_private::TypeFormatImpl_Format::GetDescription().
Member Data Documentation
m_flags
Flags lldb_private::TypeFormatImpl::m_flags protected
Definition at line 155 of file TypeFormat.h.
Referenced by Cascades(), GetOptions(), NonCacheable(), SetCascades(), SetNonCacheable(), SetOptions(), SetSkipsPointers(), SetSkipsReferences(), SkipsPointers(), SkipsReferences(), and TypeFormatImpl().
m_my_revision
uint32_t lldb_private::TypeFormatImpl::m_my_revision = 0 protected
Definition at line 156 of file TypeFormat.h.
Referenced by GetRevision().
m_ptr_match_depth
uint32_t lldb_private::TypeFormatImpl::m_ptr_match_depth = 1 protected
Definition at line 157 of file TypeFormat.h.
Referenced by GetPtrMatchDepth(), and SetPtrMatchDepth().
The documentation for this class was generated from the following files:
TypeFormat.h
TypeFormat.cpp