LLDB: lldb_private::AppleObjCRuntimeV1 Class Reference
lldb_private::AppleObjCRuntimeV1 Class Reference
#include <AppleObjCRuntimeV1.h>
Classes
class ClassDescriptorV1
class HashTableSignature
Public Member Functions
~AppleObjCRuntimeV1 () override=default
bool isA (const void *ClassID) const override
lldb::addr_t GetTaggedPointerObfuscator ()
bool GetDynamicTypeAndAddress (ValueObject &in_value, lldb::DynamicValueType use_dynamic, TypeAndOrName &class_type_or_name, Address &address, Value::ValueType &value_type, llvm::ArrayRef< uint8_t > &local_buffer) override
This call should return true if it could set the name and/or the type Sets address to the address of the dynamic type if value_type is set to a file or load address.
llvm::Expected< std::unique_ptr< UtilityFunction > > CreateObjectChecker (std::string, ExecutionContext &exe_ctx) override
llvm::StringRef GetPluginName () override
ObjCRuntimeVersions GetRuntimeVersion () const override
void UpdateISAToDescriptorMapIfNeeded () override
DeclVendor * GetDeclVendor () override
Public Member Functions inherited from lldb_private::AppleObjCRuntime
~AppleObjCRuntime () override
llvm::Error GetObjectDescription (Stream &str, Value &value, ExecutionContextScope *exe_scope) override
llvm::Error GetObjectDescription (Stream &str, ValueObject &object) override
bool CouldHaveDynamicValue (ValueObject &in_value) override
TypeAndOrName FixUpDynamicType (const TypeAndOrName &type_and_or_name, ValueObject &static_value) override
bool IsModuleObjCLibrary (const lldb::ModuleSP &module_sp) override
bool ReadObjCLibrary (const lldb::ModuleSP &module_sp) override
bool HasReadObjCLibrary () override
lldb::ThreadPlanSP GetStepThroughTrampolinePlan (Thread &thread, bool stop_others) override
lldb::ModuleSP GetObjCModule ()
void ModulesDidLoad (const ModuleList &module_list) override
Called when modules have been loaded in the process.
void SetExceptionBreakpoints () override
void ClearExceptionBreakpoints () override
bool ExceptionBreakpointsAreSet () override
bool ExceptionBreakpointsExplainStop (lldb::StopInfoSP stop_reason) override
lldb::SearchFilterSP CreateExceptionSearchFilter () override
lldb::ValueObjectSP GetExceptionObjectForThread (lldb::ThreadSP thread_sp) override
lldb::ThreadSP GetBacktraceThreadFromException (lldb::ValueObjectSP thread_sp) override
uint32_t GetFoundationVersion ()
virtual void GetValuesForGlobalCFBooleans (lldb::addr_t &cf_true, lldb::addr_t &cf_false)
virtual bool IsTaggedPointer (lldb::addr_t addr)
Public Member Functions inherited from lldb_private::ObjCLanguageRuntime
~ObjCLanguageRuntime () override
bool isA (const void *ClassID) const override
virtual TaggedPointerVendor * GetTaggedPointerVendor ()
virtual EncodingToTypeSP GetEncodingToType ()
virtual ClassDescriptorSP GetClassDescriptor (ValueObject &in_value)
ClassDescriptorSP GetNonKVOClassDescriptor (ValueObject &in_value)
virtual ClassDescriptorSP GetClassDescriptorFromClassName (ConstString class_name)
virtual ClassDescriptorSP GetClassDescriptorFromISA (ObjCISA isa)
ClassDescriptorSP GetNonKVOClassDescriptor (ObjCISA isa)
lldb::LanguageType GetLanguageType () const override
lldb::addr_t LookupInMethodCache (lldb::addr_t class_addr, lldb::addr_t sel)
lldb::addr_t LookupInMethodCache (lldb::addr_t class_addr, llvm::StringRef sel_str)
void AddToMethodCache (lldb::addr_t class_addr, lldb::addr_t sel, lldb::addr_t impl_addr)
void AddToMethodCache (lldb::addr_t class_addr, llvm::StringRef sel_str, lldb::addr_t impl_addr)
TypeAndOrName LookupInClassNameCache (lldb::addr_t class_addr)
void AddToClassNameCache (lldb::addr_t class_addr, const char *name, lldb::TypeSP type_sp)
void AddToClassNameCache (lldb::addr_t class_addr, const TypeAndOrName &class_or_type_name)
lldb::TypeSP LookupInCompleteClassCache (ConstString &name)
std::optional< CompilerType > GetRuntimeType (CompilerType base_type) override
bool IsValidISA (ObjCISA isa)
void UpdateISAToDescriptorMap ()
virtual ObjCISA GetISA (ConstString name)
virtual ObjCISA GetParentClass (ObjCISA isa)
virtual size_t GetByteOffsetForIvar (CompilerType &parent_qual_type, const char *ivar_name)
bool HasNewLiteralsAndIndexing ()
void SymbolsDidLoad (const ModuleList &module_list) override
std::optional< uint64_t > GetTypeBitSize (const CompilerType &compiler_type) override
bool IsAllowedRuntimeValue (ConstString name) override
Check whether the name is "self" or "_cmd" and should show up in "frame variable".
Public Member Functions inherited from lldb_private::LanguageRuntime
virtual LanguageRuntime * GetPreferredLanguageRuntime (ValueObject &in_value)
Return the preferred language runtime instance, which in most cases will be the current instance.
virtual llvm::Expected< VTableInfo > GetVTableInfo (ValueObject &in_value, bool check_type)
Get the vtable information for a given value.
virtual CompilerType GetConcreteType (ExecutionContextScope *exe_scope, ConstString abstract_type_name)
void ModulesDidLoad (const ModuleList &module_list) override
Called when modules have been loaded in the process.
virtual bool GetIRPasses (LLVMUserExpression::IRPasses &custom_passes)
virtual bool IsSymbolARuntimeThunk (const Symbol &symbol)
virtual lldb::addr_t LookupRuntimeSymbol (ConstString name)
virtual StructuredData::ObjectSP GetLanguageSpecificData (SymbolContext sc)
Language runtime plugins can use this API to report language-specific runtime information about this compile unit, such as additional language version details or feature flags.
Public Member Functions inherited from lldb_private::Runtime
Runtime (Process *process)
virtual ~Runtime ()=default
Runtime (const Runtime &)=delete
const Runtime & operator= (const Runtime &)=delete
Process * GetProcess ()
Target & GetTargetRef ()
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static lldb_private::LanguageRuntime * CreateInstance (Process *process, lldb::LanguageType language)
static llvm::StringRef GetPluginNameStatic ()
static bool classof (const LanguageRuntime *runtime)
Static Public Member Functions inherited from lldb_private::AppleObjCRuntime
static void Initialize ()
static void Terminate ()
static bool classof (const LanguageRuntime *runtime)
static std::tuple< FileSpec, ConstString > GetExceptionThrowLocation ()
Static Public Member Functions inherited from lldb_private::ObjCLanguageRuntime
static lldb::BreakpointPreconditionSP GetBreakpointExceptionPrecondition (lldb::LanguageType language, bool throw_bp)
static bool classof (const LanguageRuntime *runtime)
static ObjCLanguageRuntime * Get (Process &process)
Static Public Member Functions inherited from lldb_private::LanguageRuntime
static LanguageRuntime * FindPlugin (Process *process, lldb::LanguageType language)
static void InitializeCommands (CommandObject *parent)
static lldb::BreakpointSP CreateExceptionBreakpoint (Target &target, lldb::LanguageType language, bool catch_bp, bool throw_bp, bool is_internal=false)
static lldb::BreakpointPreconditionSP GetExceptionPrecondition (lldb::LanguageType language, bool throw_bp)
static lldb::UnwindPlanSP GetRuntimeUnwindPlan (lldb_private::Thread &thread, lldb_private::RegisterContext *regctx, bool &behaves_like_zeroth_frame)
A language runtime may be able to provide a special UnwindPlan for the frame represented by the register contents regctx when that frame is not following the normal ABI conventions.
Static Public Attributes
static char ID = 0
Static Public Attributes inherited from lldb_private::AppleObjCRuntime
static char ID = 0
Static Public Attributes inherited from lldb_private::ObjCLanguageRuntime
static char ID = 0
Static Public Attributes inherited from lldb_private::LanguageRuntime
static char ID = 0
Protected Member Functions
lldb::BreakpointResolverSP CreateExceptionResolver (const lldb::BreakpointSP &bkpt, bool catch_bp, bool throw_bp) override
lldb::addr_t GetISAHashTablePointer ()
Protected Member Functions inherited from lldb_private::AppleObjCRuntime
AppleObjCRuntime (Process *process)
bool CalculateHasNewLiteralsAndIndexing () override
void ReadObjCLibraryIfNeeded (const ModuleList &module_list)
Address * GetPrintForDebuggerAddr ()
Protected Member Functions inherited from lldb_private::ObjCLanguageRuntime
ObjCLanguageRuntime (Process *process)
bool ISAIsCached (ObjCISA isa) const
bool AddClass (ObjCISA isa, const ClassDescriptorSP &descriptor_sp)
bool AddClass (ObjCISA isa, const ClassDescriptorSP &descriptor_sp, const char *class_name)
bool AddClass (ObjCISA isa, const ClassDescriptorSP &descriptor_sp, uint32_t class_name_hash)
ISAToDescriptorIterator GetDescriptorIterator (ConstString name)
std::pair< ISAToDescriptorIterator, ISAToDescriptorIterator > GetDescriptorIteratorPair (bool update_if_needed=true)
void ReadObjCLibraryIfNeeded (const ModuleList &module_list)
ObjCLanguageRuntime (const ObjCLanguageRuntime &)=delete
const ObjCLanguageRuntime & operator= (const ObjCLanguageRuntime &)=delete
Protected Member Functions inherited from lldb_private::LanguageRuntime
virtual lldb::UnwindPlanSP GetRuntimeUnwindPlan (lldb::ProcessSP process_sp, lldb_private::RegisterContext *regctx, bool &behaves_like_zeroth_frame)
LanguageRuntime (Process *process)
Protected Attributes
HashTableSignature m_hash_signature
lldb::addr_t m_isa_hash_table_ptr
std::unique_ptr< DeclVendor > m_decl_vendor_up
Protected Attributes inherited from lldb_private::AppleObjCRuntime
std::unique_ptr< Address > m_PrintForDebugger_addr
bool m_read_objc_library
std::unique_ptr< lldb_private::AppleObjCTrampolineHandler > m_objc_trampoline_handler_up
lldb::BreakpointSP m_objc_exception_bp_sp
lldb::ModuleWP m_objc_module_wp
std::unique_ptr< FunctionCaller > m_print_object_caller_up
std::optional< uint32_t > m_Foundation_major
Protected Attributes inherited from lldb_private::ObjCLanguageRuntime
uint32_t m_isa_to_descriptor_stop_id
CompleteClassMap m_complete_class_cache
CompleteClassSet m_negative_complete_class_cache
Protected Attributes inherited from lldb_private::Runtime
Process * m_process
Private Member Functions
AppleObjCRuntimeV1 (Process *process)
Additional Inherited Members
Public Types inherited from lldb_private::ObjCLanguageRuntime
enum class ObjCRuntimeVersions { eObjC_VersionUnknown = 0 , eAppleObjC_V1 = 1 , eAppleObjC_V2 = 2 , eGNUstep_libobjc2 = 3 }
typedef lldb::addr_t ObjCISA
typedef std::shared_ptr< ClassDescriptor > ClassDescriptorSP
typedef std::shared_ptr< EncodingToType > EncodingToTypeSP
Protected Types inherited from lldb_private::ObjCLanguageRuntime
typedef std::map< ConstString, lldb::TypeWP > CompleteClassMap
typedef std::unordered_set< ConstString, ConstStringSetHelpers, ConstStringSetHelpers > CompleteClassSet
Static Protected Member Functions inherited from lldb_private::AppleObjCRuntime
static bool AppleIsModuleObjCLibrary (const lldb::ModuleSP &module_sp)
static ObjCRuntimeVersions GetObjCVersion (Process *process, lldb::ModuleSP &objc_module_sp)
Detailed Description
Definition at line 19 of file AppleObjCRuntimeV1.h.
Constructor & Destructor Documentation
~AppleObjCRuntimeV1()
lldb_private::AppleObjCRuntimeV1::~AppleObjCRuntimeV1 () override default
AppleObjCRuntimeV1()
AppleObjCRuntimeV1::AppleObjCRuntimeV1 (Process * process) private
Definition at line 42 of file AppleObjCRuntimeV1.cpp.
References lldb_private::AppleObjCRuntime::AppleObjCRuntime(), LLDB_INVALID_ADDRESS, m_hash_signature, and m_isa_hash_table_ptr.
Referenced by CreateInstance().
Member Function Documentation
classof()
bool lldb_private::AppleObjCRuntimeV1::classof (const LanguageRuntime * runtime) inline static
Definition at line 39 of file AppleObjCRuntimeV1.h.
References ID, and lldb_private::LanguageRuntime::isA().
CreateExceptionResolver()
BreakpointResolverSP AppleObjCRuntimeV1::CreateExceptionResolver (const lldb::BreakpointSP & bkpt, bool catch_bp, bool throw_bp) override protected virtual
Implements lldb_private::LanguageRuntime.
Definition at line 97 of file AppleObjCRuntimeV1.cpp.
References lldb::eLanguageTypeUnknown, lldb_private::eLazyBoolNo, lldb_private::Breakpoint::Exact, and lldb_private::AppleObjCRuntime::GetExceptionThrowLocation().
CreateInstance()
lldb_private::LanguageRuntime * AppleObjCRuntimeV1::CreateInstance (Process * process, lldb::LanguageType language) static
Definition at line 68 of file AppleObjCRuntimeV1.cpp.
References AppleObjCRuntimeV1(), lldb_private::ObjCLanguageRuntime::eAppleObjC_V1, lldb::eLanguageTypeObjC, and lldb_private::AppleObjCRuntime::GetObjCVersion().
Referenced by Initialize(), and Terminate().
CreateObjectChecker()
llvm::Expected< std::unique_ptr< UtilityFunction > > AppleObjCRuntimeV1::CreateObjectChecker (std::string name, ExecutionContext & exe_ctx) override virtual
Implements lldb_private::ObjCLanguageRuntime.
Definition at line 115 of file AppleObjCRuntimeV1.cpp.
References lldb_private::Target::CreateUtilityFunction(), lldb::eLanguageTypeC, lldb_private::Runtime::GetTargetRef(), and UNUSED_IF_ASSERT_DISABLED.
GetDeclVendor()
DeclVendor * AppleObjCRuntimeV1::GetDeclVendor () override virtual
Reimplemented from lldb_private::LanguageRuntime.
Definition at line 429 of file AppleObjCRuntimeV1.cpp.
GetDynamicTypeAndAddress()
bool AppleObjCRuntimeV1::GetDynamicTypeAndAddress (ValueObject & in_value, lldb::DynamicValueType use_dynamic, TypeAndOrName & class_type_or_name, Address & address, Value::ValueType & value_type, llvm::ArrayRef< uint8_t > & local_buffer) override virtual
This call should return true if it could set the name and/or the type Sets address to the address of the dynamic type if value_type is set to a file or load address.
Sets local_buffer to a buffer containing the data of the dynamic type if value_type is set to a host address. Callers should copy local_buffer over into their own buffer if they want to keep the data alive.
Reimplemented from lldb_private::AppleObjCRuntime.
Definition at line 48 of file AppleObjCRuntimeV1.cpp.
References lldb_private::ValueObject::AddrAndType::address, lldb_private::TypeAndOrName::Clear(), lldb_private::AppleObjCRuntime::CouldHaveDynamicValue(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), lldb_private::ValueObject::GetPointerValue(), lldb_private::TypeAndOrName::IsEmpty(), lldb_private::Value::Scalar, lldb_private::TypeAndOrName::SetName(), and lldb_private::Address::SetRawAddress().
GetISAHashTablePointer()
lldb::addr_t AppleObjCRuntimeV1::GetISAHashTablePointer () protected
Definition at line 280 of file AppleObjCRuntimeV1.cpp.
References error(), lldb::eSymbolTypeData, lldb_private::Symbol::GetAddressRef(), lldb_private::Address::GetLoadAddress(), lldb_private::AppleObjCRuntime::GetObjCModule(), lldb_private::Runtime::GetProcess(), lldb_private::Process::GetTarget(), LLDB_INVALID_ADDRESS, m_isa_hash_table_ptr, lldb_private::Process::ReadPointerFromMemory(), and lldb_private::Symbol::ValueIsAddress().
Referenced by UpdateISAToDescriptorMapIfNeeded().
GetPluginName()
llvm::StringRef lldb_private::AppleObjCRuntimeV1::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 110 of file AppleObjCRuntimeV1.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::AppleObjCRuntimeV1::GetPluginNameStatic () inline static
Definition at line 31 of file AppleObjCRuntimeV1.h.
Referenced by GetPluginName(), and Initialize().
GetRuntimeVersion()
ObjCRuntimeVersions lldb_private::AppleObjCRuntimeV1::GetRuntimeVersion () const inline override virtual
Reimplemented from lldb_private::ObjCLanguageRuntime.
Definition at line 112 of file AppleObjCRuntimeV1.h.
References lldb_private::ObjCLanguageRuntime::eAppleObjC_V1.
GetTaggedPointerObfuscator()
lldb::addr_t AppleObjCRuntimeV1::GetTaggedPointerObfuscator ()
Definition at line 276 of file AppleObjCRuntimeV1.cpp.
Initialize()
void AppleObjCRuntimeV1::Initialize () static
Definition at line 85 of file AppleObjCRuntimeV1.cpp.
References CreateInstance(), lldb_private::ObjCLanguageRuntime::GetBreakpointExceptionPrecondition(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Referenced by lldb_private::AppleObjCRuntimeV1::ClassDescriptorV1::ClassDescriptorV1(), lldb_private::AppleObjCRuntimeV1::ClassDescriptorV1::ClassDescriptorV1(), and lldb_private::AppleObjCRuntime::Initialize().
isA()
bool lldb_private::AppleObjCRuntimeV1::isA (const void * ClassID) const inline override virtual
Reimplemented from lldb_private::AppleObjCRuntime.
Definition at line 35 of file AppleObjCRuntimeV1.h.
References ID, and lldb_private::AppleObjCRuntime::isA().
Terminate()
void AppleObjCRuntimeV1::Terminate () static
Definition at line 92 of file AppleObjCRuntimeV1.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Referenced by lldb_private::AppleObjCRuntime::Terminate().
UpdateISAToDescriptorMapIfNeeded()
void AppleObjCRuntimeV1::UpdateISAToDescriptorMapIfNeeded () override virtual
Implements lldb_private::ObjCLanguageRuntime.
Definition at line 313 of file AppleObjCRuntimeV1.cpp.
References lldb_private::ObjCLanguageRuntime::AddClass(), error(), lldb_private::DataExtractor::GetAddress(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::DataBufferHeap::GetByteSize(), GetISAHashTablePointer(), lldb_private::GetLog(), lldb_private::AppleObjCRuntime::GetObjCModule(), lldb_private::Runtime::GetProcess(), lldb_private::Process::GetStopID(), lldb_private::DataExtractor::GetU32(), lldb_private::Log::GetVerbose(), lldb_private::ObjCLanguageRuntime::ISAIsCached(), LLDB_INVALID_ADDRESS, LLDB_LOGF, m_hash_signature, lldb_private::ObjCLanguageRuntime::m_isa_to_descriptor_stop_id, lldb_private::Runtime::m_process, lldb_private::Process, lldb_private::Process::ReadMemory(), lldb_private::DataBufferHeap::SetByteSize(), lldb_private::DataExtractor::SetData(), and UINT32_MAX.
Member Data Documentation
ID
char AppleObjCRuntimeV1::ID = 0 static
Definition at line 33 of file AppleObjCRuntimeV1.h.
Referenced by classof(), and isA().
m_decl_vendor_up
std::unique_ptr<DeclVendor> lldb_private::AppleObjCRuntimeV1::m_decl_vendor_up protected
Definition at line 152 of file AppleObjCRuntimeV1.h.
m_hash_signature
HashTableSignature lldb_private::AppleObjCRuntimeV1::m_hash_signature protected
Definition at line 150 of file AppleObjCRuntimeV1.h.
Referenced by AppleObjCRuntimeV1(), and UpdateISAToDescriptorMapIfNeeded().
m_isa_hash_table_ptr
lldb::addr_t lldb_private::AppleObjCRuntimeV1::m_isa_hash_table_ptr protected
Definition at line 151 of file AppleObjCRuntimeV1.h.
Referenced by AppleObjCRuntimeV1(), and GetISAHashTablePointer().
The documentation for this class was generated from the following files:
AppleObjCRuntimeV1.h
AppleObjCRuntimeV1.cpp