LLDB: lldb_private::SharedSocket Class Reference
lldb_private::SharedSocket Class Reference
#include <Socket.h>
Public Member Functions
SharedSocket (const Socket *socket, Status &error)
shared_fd_t GetSendableFD ()
Status CompleteSending (lldb::pid_t child_pid)
Static Public Member Functions
static Status GetNativeSocket (shared_fd_t fd, NativeSocket &socket)
Static Public Attributes
static const shared_fd_t kInvalidFD = Socket::kInvalidSocketValue
Private Attributes
shared_fd_t m_fd
Detailed Description
Definition at line 48 of file Socket.h.
Constructor & Destructor Documentation
SharedSocket()
SharedSocket::SharedSocket (const Socket * socket, Status & error)
Definition at line 66 of file Socket.cpp.
References error(), lldb_private::Socket::GetNativeSocket(), kInvalidFD, m_fd, and lldb_private::Status.
Member Function Documentation
CompleteSending()
Status SharedSocket::CompleteSending (lldb::pid_t child_pid)
Definition at line 83 of file Socket.cpp.
References lldb_private::Status::FromError(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::Status::FromErrorStringWithFormatv(), and lldb_private::Status.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::LaunchAndConnectToDebugserver().
GetNativeSocket()
Status SharedSocket::GetNativeSocket (shared_fd_t fd, NativeSocket & socket) static
Definition at line 108 of file Socket.cpp.
References lldb_private::Status::FromError(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::Socket::kInvalidSocketValue, LLDB_INVALID_PIPE, and lldb_private::PipePosix::Read().
GetSendableFD()
shared_fd_t lldb_private::SharedSocket::GetSendableFD () inline
Definition at line 54 of file Socket.h.
References m_fd.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::LaunchAndConnectToDebugserver().
Member Data Documentation
kInvalidFD
const shared_fd_t SharedSocket::kInvalidFD = Socket::kInvalidSocketValue static
Definition at line 50 of file Socket.h.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qLaunchGDBServer(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::LaunchGDBServer(), SharedSocket(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess().
m_fd
shared_fd_t lldb_private::SharedSocket::m_fd private
Definition at line 65 of file Socket.h.
Referenced by GetSendableFD(), and SharedSocket().
The documentation for this class was generated from the following files:
Socket.h
Socket.cpp