LLDB: lldb::SBTypeEnumMemberList Class Reference
lldb::SBTypeEnumMemberList Class Reference
#include <SBTypeEnumMember.h>
Public Member Functions
SBTypeEnumMemberList ()
SBTypeEnumMemberList (const SBTypeEnumMemberList &rhs)
~SBTypeEnumMemberList ()
SBTypeEnumMemberList & operator= (const SBTypeEnumMemberList &rhs)
operator bool () const
bool IsValid ()
void Append (SBTypeEnumMember entry)
SBTypeEnumMember GetTypeEnumMemberAtIndex (uint32_t index)
uint32_t GetSize ()
Private Attributes
std::unique_ptr< lldb_private::TypeEnumMemberListImpl > m_opaque_up
Detailed Description
Definition at line 57 of file SBTypeEnumMember.h.
Constructor & Destructor Documentation
SBTypeEnumMemberList() [1/2]
SBTypeEnumMemberList::SBTypeEnumMemberList ()
Definition at line 104 of file SBTypeEnumMember.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by operator=(), SBTypeEnumMemberList(), and ~SBTypeEnumMemberList().
SBTypeEnumMemberList() [2/2]
SBTypeEnumMemberList::SBTypeEnumMemberList (const SBTypeEnumMemberList & rhs)
Definition at line 109 of file SBTypeEnumMember.cpp.
References Append(), GetSize(), GetTypeEnumMemberAtIndex(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBTypeEnumMemberList().
~SBTypeEnumMemberList()
SBTypeEnumMemberList::~SBTypeEnumMemberList () default
References SBTypeEnumMemberList().
Member Function Documentation
Append()
void SBTypeEnumMemberList::Append (SBTypeEnumMember entry)
Definition at line 144 of file SBTypeEnumMember.cpp.
References lldb::SBTypeEnumMember::IsValid(), LLDB_INSTRUMENT_VA, lldb::SBTypeEnumMember::m_opaque_sp, and m_opaque_up.
Referenced by lldb::SBType::GetEnumMembers(), operator=(), and SBTypeEnumMemberList().
GetSize()
uint32_t SBTypeEnumMemberList::GetSize ()
Definition at line 160 of file SBTypeEnumMember.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by operator=(), and SBTypeEnumMemberList().
GetTypeEnumMemberAtIndex()
SBTypeEnumMember SBTypeEnumMemberList::GetTypeEnumMemberAtIndex (uint32_t index)
Definition at line 152 of file SBTypeEnumMember.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBTypeEnumMember.
Referenced by operator=(), and SBTypeEnumMemberList().
IsValid()
bool SBTypeEnumMemberList::IsValid ()
Definition at line 119 of file SBTypeEnumMember.cpp.
References LLDB_INSTRUMENT_VA.
operator bool()
SBTypeEnumMemberList::operator bool () const explicit
Definition at line 123 of file SBTypeEnumMember.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
operator=()
SBTypeEnumMemberList & SBTypeEnumMemberList::operator= (const SBTypeEnumMemberList & rhs)
Definition at line 129 of file SBTypeEnumMember.cpp.
References Append(), GetSize(), GetTypeEnumMemberAtIndex(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBTypeEnumMemberList().
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::TypeEnumMemberListImpl> lldb::SBTypeEnumMemberList::m_opaque_up private
Definition at line 78 of file SBTypeEnumMember.h.
Referenced by Append(), GetSize(), GetTypeEnumMemberAtIndex(), operator bool(), operator=(), SBTypeEnumMemberList(), and SBTypeEnumMemberList().
The documentation for this class was generated from the following files:
SBTypeEnumMember.h
SBTypeEnumMember.cpp