LLDB: lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline > Class Template Reference
lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline > Class Template Reference
Public Member Functions
GenericNSArrayISyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
~GenericNSArrayISyntheticFrontEnd () override
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Attributes
ExecutionContextRef m_exe_ctx_ref
uint8_t m_ptr_size = 8
D32 * m_data_32
D64 * m_data_64
CompilerType m_id_type
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
template<typename D32, typename D64, bool Inline>
class lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >
Definition at line 209 of file NSArray.cpp.
Constructor & Destructor Documentation
GenericNSArrayISyntheticFrontEnd()
template<typename D32, typename D64, bool Inline> lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::GenericNSArrayISyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
Definition at line 593 of file NSArray.cpp.
References lldb_private::ScratchTypeSystemClang::GetForTarget(), m_data_32, m_data_64, m_exe_ctx_ref, m_id_type, and lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd().
~GenericNSArrayISyntheticFrontEnd()
template<typename D32, typename D64, bool Inline> lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::~GenericNSArrayISyntheticFrontEnd () override
Member Function Documentation
CalculateNumChildren()
template<typename D32, typename D64, bool Inline> llvm::Expected< uint32_t > lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::CalculateNumChildren () override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 637 of file NSArray.cpp.
References m_data_32, and m_data_64.
GetChildAtIndex()
template<typename D32, typename D64, bool Inline> lldb::ValueObjectSP lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::GetChildAtIndex (uint32_t idx) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 677 of file NSArray.cpp.
References lldb_private::SyntheticChildrenFrontEnd::CalculateNumChildrenIgnoringErrors(), lldb_private::SyntheticChildrenFrontEnd::CreateValueObjectFromAddress(), error(), lldb_private::StreamString::GetString(), lldb_private::SyntheticChildrenFrontEnd::m_backend, m_data_32, m_data_64, m_exe_ctx_ref, m_id_type, m_ptr_size, and lldb_private::Stream::Printf().
GetIndexOfChildWithName()
template<typename D32, typename D64, bool Inline> llvm::Expected< size_t > lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::GetIndexOfChildWithName (ConstString name) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 621 of file NSArray.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::SyntheticChildrenFrontEnd::CalculateNumChildrenIgnoringErrors(), lldb_private::formatters::ExtractIndexFromString(), and GetIndexOfChildWithName().
Referenced by GetIndexOfChildWithName().
Update()
template<typename D32, typename D64, bool Inline> lldb::ChildCacheState lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::Update () override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 644 of file NSArray.cpp.
References lldb::eRefetch, lldb::eReuse, error(), lldb_private::SyntheticChildrenFrontEnd::m_backend, m_data_32, m_data_64, m_exe_ctx_ref, m_ptr_size, and Update().
Referenced by Update().
Member Data Documentation
m_data_32
template<typename D32, typename D64, bool Inline> D32* lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::m_data_32 private
Definition at line 227 of file NSArray.cpp.
Referenced by CalculateNumChildren(), GenericNSArrayISyntheticFrontEnd(), GetChildAtIndex(), and Update().
m_data_64
template<typename D32, typename D64, bool Inline> D64* lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::m_data_64 private
Definition at line 228 of file NSArray.cpp.
Referenced by CalculateNumChildren(), GenericNSArrayISyntheticFrontEnd(), GetChildAtIndex(), and Update().
m_exe_ctx_ref
template<typename D32, typename D64, bool Inline> ExecutionContextRef lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::m_exe_ctx_ref private
Definition at line 224 of file NSArray.cpp.
Referenced by GenericNSArrayISyntheticFrontEnd(), GetChildAtIndex(), and Update().
m_id_type
template<typename D32, typename D64, bool Inline> CompilerType lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::m_id_type private
Definition at line 229 of file NSArray.cpp.
Referenced by GenericNSArrayISyntheticFrontEnd(), and GetChildAtIndex().
m_ptr_size
template<typename D32, typename D64, bool Inline> uint8_t lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::m_ptr_size = 8 private
Definition at line 225 of file NSArray.cpp.
Referenced by GetChildAtIndex(), and Update().
The documentation for this class was generated from the following file:
NSArray.cpp