LLDB: lldb_private::HostThreadPosix Class Reference
lldb_private::HostThreadPosix Class Reference
#include <HostThreadPosix.h>
Public Member Functions
HostThreadPosix ()
HostThreadPosix (lldb::thread_t thread)
~HostThreadPosix () override
Status Join (lldb::thread_result_t *result) override
Status Cancel () override
void Reset () override
Public Member Functions inherited from lldb_private::HostNativeThreadBase
HostNativeThreadBase ()=default
HostNativeThreadBase (lldb::thread_t thread)
virtual ~HostNativeThreadBase ()=default
virtual bool IsJoinable () const
virtual bool EqualsThread (lldb::thread_t thread) const
lldb::thread_t Release ()
lldb::thread_t GetSystemHandle () const
lldb::thread_result_t GetResult () const
Private Member Functions
HostThreadPosix (const HostThreadPosix &)=delete
const HostThreadPosix & operator= (const HostThreadPosix &)=delete
Additional Inherited Members
Static Protected Member Functions inherited from lldb_private::HostNativeThreadBase
static lldb::thread_result_t THREAD_ROUTINE ThreadCreateTrampoline (lldb::thread_arg_t arg)
Protected Attributes inherited from lldb_private::HostNativeThreadBase
lldb::thread_t m_thread = LLDB_INVALID_HOST_THREAD
lldb::thread_result_t m_result = 0
Detailed Description
Definition at line 16 of file HostThreadPosix.h.
Constructor & Destructor Documentation
HostThreadPosix() [1/3]
lldb_private::HostThreadPosix::HostThreadPosix (const HostThreadPosix &) private delete
References HostThreadPosix().
Referenced by HostThreadPosix(), operator=(), and lldb_private::HostThreadMacOSX::ThreadLauncher.
HostThreadPosix() [2/3]
HostThreadPosix::HostThreadPosix () default
HostThreadPosix() [3/3]
HostThreadPosix::HostThreadPosix (lldb::thread_t thread)
Definition at line 20 of file HostThreadPosix.cpp.
References lldb_private::HostNativeThreadBase::HostNativeThreadBase().
~HostThreadPosix()
HostThreadPosix::~HostThreadPosix () override default
Member Function Documentation
Cancel()
Status HostThreadPosix::Cancel () override virtual
Implements lldb_private::HostNativeThreadBase.
Definition at line 40 of file HostThreadPosix.cpp.
References lldb::eErrorTypePOSIX, error(), lldb_private::HostNativeThreadBase::IsJoinable(), lldb_private::HostNativeThreadBase::m_thread, and lldb_private::Status.
Join()
Status HostThreadPosix::Join (lldb::thread_result_t * result) override virtual
Implements lldb_private::HostNativeThreadBase.
Definition at line 25 of file HostThreadPosix.cpp.
References lldb::eErrorTypePOSIX, error(), lldb_private::HostNativeThreadBase::IsJoinable(), lldb_private::HostNativeThreadBase::m_thread, Reset(), and lldb_private::Status.
operator=()
const HostThreadPosix & lldb_private::HostThreadPosix::operator= (const HostThreadPosix &) private delete
References HostThreadPosix().
Reset()
void HostThreadPosix::Reset () override virtual
Reimplemented from lldb_private::HostNativeThreadBase.
Definition at line 53 of file HostThreadPosix.cpp.
References lldb_private::HostNativeThreadBase::IsJoinable(), lldb_private::HostNativeThreadBase::m_thread, and lldb_private::HostNativeThreadBase::Reset().
Referenced by Join().
The documentation for this class was generated from the following files:
HostThreadPosix.h
HostThreadPosix.cpp