LLDB: CFCString Class Reference
CFCString Class Reference
#include <CFCString.h>
Public Member Functions
CFCString (CFStringRef cf_str=NULL)
CFCString (const char *s, CFStringEncoding encoding=kCFStringEncodingUTF8)
CFCString (const CFCString &rhs)
CFCString & operator= (const CFCString &rhs)
~CFCString () override
const char * GetFileSystemRepresentation (std::string &str)
CFStringRef SetFileSystemRepresentation (const char *path)
CFStringRef SetFileSystemRepresentationFromCFType (CFTypeRef cf_type)
CFStringRef SetFileSystemRepresentationAndExpandTilde (const char *path)
const char * UTF8 (std::string &str)
CFIndex GetLength () const
Public Member Functions inherited from CFCReleaser< CFStringRef >
CFCReleaser (CFStringRef ptr=NULL)
virtual ~CFCReleaser ()
CFCReleaser & operator= (const CFCReleaser< CFStringRef > &rhs)
CFStringRef * ptr_address (bool enforce_null=true)
CFStringRef get ()
void reset (CFStringRef ptr=NULL)
CFStringRef release ()
Static Public Member Functions
static const char * UTF8 (CFStringRef cf_str, std::string &str)
static const char * FileSystemRepresentation (CFStringRef cf_str, std::string &str)
static const char * ExpandTildeInPath (const char *path, std::string &expanded_path)
Detailed Description
Definition at line 16 of file CFCString.h.
Constructor & Destructor Documentation
CFCString() [1/3]
CFCString::CFCString (CFStringRef cf_str = NULL)
Definition at line 14 of file CFCString.cpp.
References CFCReleaser< CFStringRef >::CFCReleaser().
Referenced by CFCString(), and operator=().
CFCString() [2/3]
CFCString::CFCString (const char * s, CFStringEncoding encoding = kCFStringEncodingUTF8)
Definition at line 26 of file CFCString.cpp.
References CFCReleaser< CFStringRef >::CFCReleaser(), and CFCReleaser< CFStringRef >::reset().
CFCString() [3/3]
CFCString::CFCString (const CFCString & rhs) default
References CFCString().
~CFCString()
CFCString::~CFCString () override default
Member Function Documentation
ExpandTildeInPath()
const char * CFCString::ExpandTildeInPath (const char * path, std::string & expanded_path) static
Definition at line 108 of file CFCString.cpp.
Referenced by SetFileSystemRepresentationAndExpandTilde().
FileSystemRepresentation()
const char * CFCString::FileSystemRepresentation (CFStringRef cf_str, std::string & str) static
Definition at line 126 of file CFCString.cpp.
Referenced by GetFileSystemRepresentation(), and GetModuleSpecInfoFromUUIDDictionary().
GetFileSystemRepresentation()
const char * CFCString::GetFileSystemRepresentation (std::string & str)
Definition at line 37 of file CFCString.cpp.
References FileSystemRepresentation(), and CFCReleaser< CFStringRef >::get().
GetLength()
CFIndex CFCString::GetLength () const
Definition at line 146 of file CFCString.cpp.
References CFCReleaser< CFStringRef >::get().
operator=()
CFCString & CFCString::operator= (const CFCString & rhs)
Definition at line 20 of file CFCString.cpp.
References CFCString().
SetFileSystemRepresentation()
CFStringRef CFCString::SetFileSystemRepresentation (const char * path)
Definition at line 41 of file CFCString.cpp.
References CFCReleaser< CFStringRef >::get(), and CFCReleaser< CFStringRef >::reset().
Referenced by CFCMutableArray::AppendFileSystemRepresentationAsCFString(), SetFileSystemRepresentationAndExpandTilde(), and CFCBundle::SetPath().
SetFileSystemRepresentationAndExpandTilde()
CFStringRef CFCString::SetFileSystemRepresentationAndExpandTilde (const char * path)
Definition at line 69 of file CFCString.cpp.
References ExpandTildeInPath(), CFCReleaser< CFStringRef >::get(), CFCReleaser< CFStringRef >::reset(), and SetFileSystemRepresentation().
SetFileSystemRepresentationFromCFType()
CFStringRef CFCString::SetFileSystemRepresentationFromCFType (CFTypeRef cf_type)
Definition at line 51 of file CFCString.cpp.
References CFCReleaser< CFStringRef >::get(), and CFCReleaser< CFStringRef >::reset().
UTF8() [1/2]
const char * CFCString::UTF8 (CFStringRef cf_str, std::string & str) static
Definition at line 89 of file CFCString.cpp.
UTF8() [2/2]
const char * CFCString::UTF8 (std::string & str)
Definition at line 78 of file CFCString.cpp.
References CFCReleaser< CFStringRef >::get(), and UTF8().
Referenced by UTF8().
The documentation for this class was generated from the following files:
CFCString.h
CFCString.cpp