LLDB: lldb_private::SaveCoreOptions Class Reference
lldb_private::SaveCoreOptions Class Reference
#include <SaveCoreOptions.h>
Public Member Functions
SaveCoreOptions ()=default
~SaveCoreOptions ()=default
lldb_private::Status SetPluginName (const char *name)
std::optional< std::string > GetPluginName () const
void SetStyle (lldb::SaveCoreStyle style)
lldb::SaveCoreStyle GetStyle () const
void SetOutputFile (lldb_private::FileSpec file)
const std::optional< lldb_private::FileSpec > GetOutputFile () const
Status SetProcess (lldb::ProcessSP process_sp)
lldb::ProcessSP GetProcess () const
Status AddThread (lldb::ThreadSP thread_sp)
bool RemoveThread (lldb::ThreadSP thread_sp)
bool ShouldThreadBeSaved (lldb::tid_t tid) const
bool HasSpecifiedThreads () const
Status EnsureValidConfiguration () const
const MemoryRanges & GetCoreFileMemoryRanges () const
void AddMemoryRegionToSave (const lldb_private::MemoryRegionInfo &region)
llvm::Expected< lldb_private::CoreFileMemoryRanges > GetMemoryRegionsToSave ()
lldb_private::ThreadCollection::collection GetThreadsToSave () const
llvm::Expected< uint64_t > GetCurrentSizeInBytes ()
void Clear ()
Private Member Functions
void ClearProcessSpecificData ()
Private Attributes
std::optional< std::string > m_plugin_name
std::optional< lldb_private::FileSpec > m_file
std::optional< lldb::SaveCoreStyle > m_style
lldb::ProcessSP m_process_sp
std::unordered_set< lldb::tid_t > m_threads_to_save
MemoryRanges m_regions_to_save
Detailed Description
Definition at line 25 of file SaveCoreOptions.h.
Constructor & Destructor Documentation
SaveCoreOptions()
lldb_private::SaveCoreOptions::SaveCoreOptions () default
~SaveCoreOptions()
lldb_private::SaveCoreOptions::~SaveCoreOptions () default
Member Function Documentation
AddMemoryRegionToSave()
void SaveCoreOptions::AddMemoryRegionToSave (const lldb_private::MemoryRegionInfo & region)
Definition at line 119 of file SaveCoreOptions.cpp.
References lldb_private::MemoryRegionInfo::GetRange(), and m_regions_to_save.
AddThread()
Status SaveCoreOptions::AddThread (lldb::ThreadSP thread_sp)
Definition at line 83 of file SaveCoreOptions.cpp.
References error(), lldb_private::Status::FromErrorString(), m_process_sp, and m_threads_to_save.
Clear()
void SaveCoreOptions::Clear ()
Definition at line 207 of file SaveCoreOptions.cpp.
References m_file, m_plugin_name, m_process_sp, m_regions_to_save, m_style, and m_threads_to_save.
ClearProcessSpecificData()
void SaveCoreOptions::ClearProcessSpecificData () private
Definition at line 201 of file SaveCoreOptions.cpp.
References m_threads_to_save.
Referenced by SetProcess().
EnsureValidConfiguration()
Status SaveCoreOptions::EnsureValidConfiguration () const
Definition at line 127 of file SaveCoreOptions.cpp.
References error(), lldb::eSaveCoreFull, GetStyle(), m_process_sp, m_threads_to_save, and lldb_private::Status.
Referenced by GetCurrentSizeInBytes(), GetMemoryRegionsToSave(), and lldb_private::PluginManager::SaveCore().
GetCoreFileMemoryRanges()
const MemoryRanges & SaveCoreOptions::GetCoreFileMemoryRanges () const
Definition at line 124 of file SaveCoreOptions.cpp.
References m_regions_to_save.
Referenced by GetUserSpecifiedCoreFileSaveRanges().
GetCurrentSizeInBytes()
llvm::Expected< uint64_t > SaveCoreOptions::GetCurrentSizeInBytes ()
Definition at line 174 of file SaveCoreOptions.cpp.
References EnsureValidConfiguration(), error(), lldb_private::Status::FromErrorString(), GetMemoryRegionsToSave(), m_process_sp, and lldb_private::Status::takeError().
GetMemoryRegionsToSave()
llvm::Expected< lldb_private::CoreFileMemoryRanges > SaveCoreOptions::GetMemoryRegionsToSave ()
Definition at line 157 of file SaveCoreOptions.cpp.
References EnsureValidConfiguration(), error(), lldb_private::Status::FromErrorString(), m_process_sp, and lldb_private::Status::takeError().
Referenced by GetCurrentSizeInBytes().
GetOutputFile()
const std::optional< lldb_private::FileSpec > SaveCoreOptions::GetOutputFile () const
Definition at line 57 of file SaveCoreOptions.cpp.
References m_file.
Referenced by lldb_private::PluginManager::SaveCore(), ObjectFileMachO::SaveCore(), ObjectFileMinidump::SaveCore(), ObjectFilePECOFF::SaveCore(), and lldb_private::SaveMiniDump().
GetPluginName()
std::optional< std::string > SaveCoreOptions::GetPluginName () const
Definition at line 48 of file SaveCoreOptions.cpp.
References m_plugin_name.
Referenced by lldb_private::PluginManager::SaveCore().
GetProcess()
lldb::ProcessSP lldb_private::SaveCoreOptions::GetProcess () const inline
Definition at line 40 of file SaveCoreOptions.h.
References m_process_sp.
Referenced by lldb_private::PluginManager::SaveCore().
GetStyle()
lldb::SaveCoreStyle SaveCoreOptions::GetStyle () const
Definition at line 52 of file SaveCoreOptions.cpp.
References lldb::eSaveCoreUnspecified, and m_style.
Referenced by lldb_private::Process::CalculateCoreFileSaveRanges(), CreateAllImageInfosPayload(), EnsureValidConfiguration(), ObjectFileMachO::SaveCore(), and ObjectFileMinidump::SaveCore().
GetThreadsToSave()
lldb_private::ThreadCollection::collection SaveCoreOptions::GetThreadsToSave () const
Definition at line 143 of file SaveCoreOptions.cpp.
References lldb_private::ThreadList::FindThreadByID(), m_process_sp, and m_threads_to_save.
HasSpecifiedThreads()
bool SaveCoreOptions::HasSpecifiedThreads () const
Definition at line 115 of file SaveCoreOptions.cpp.
References m_threads_to_save.
Referenced by lldb_private::Process::CalculateCoreFileSaveRanges().
RemoveThread()
bool SaveCoreOptions::RemoveThread (lldb::ThreadSP thread_sp)
Definition at line 104 of file SaveCoreOptions.cpp.
References m_threads_to_save.
SetOutputFile()
void SaveCoreOptions::SetOutputFile (lldb_private::FileSpec file)
Definition at line 46 of file SaveCoreOptions.cpp.
References m_file.
SetPluginName()
Status SaveCoreOptions::SetPluginName (const char * name)
Definition at line 17 of file SaveCoreOptions.cpp.
References error(), lldb_private::PluginManager::GetSaveCorePluginNames(), lldb_private::StreamString::GetString(), m_plugin_name, lldb_private::Stream::Printf(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), and lldb_private::Status.
SetProcess()
Status SaveCoreOptions::SetProcess (lldb::ProcessSP process_sp)
Definition at line 61 of file SaveCoreOptions.cpp.
References ClearProcessSpecificData(), error(), lldb_private::Status::FromErrorString(), and m_process_sp.
SetStyle()
void SaveCoreOptions::SetStyle (lldb::SaveCoreStyle style)
Definition at line 44 of file SaveCoreOptions.cpp.
References m_style.
Referenced by ObjectFileMachO::SaveCore(), and ObjectFileMinidump::SaveCore().
ShouldThreadBeSaved()
bool SaveCoreOptions::ShouldThreadBeSaved (lldb::tid_t tid) const
Definition at line 108 of file SaveCoreOptions.cpp.
References m_threads_to_save.
Referenced by lldb_private::Process::CalculateCoreFileThreadList(), SaveDynamicLoaderSections(), and SaveOffRegionsWithStackPointers().
Member Data Documentation
m_file
std::optional<lldb_private::FileSpec> lldb_private::SaveCoreOptions::m_file private
Definition at line 63 of file SaveCoreOptions.h.
Referenced by Clear(), GetOutputFile(), and SetOutputFile().
m_plugin_name
std::optional<std::string> lldb_private::SaveCoreOptions::m_plugin_name private
Definition at line 62 of file SaveCoreOptions.h.
Referenced by Clear(), GetPluginName(), and SetPluginName().
m_process_sp
lldb::ProcessSP lldb_private::SaveCoreOptions::m_process_sp private
Definition at line 65 of file SaveCoreOptions.h.
Referenced by AddThread(), Clear(), EnsureValidConfiguration(), GetCurrentSizeInBytes(), GetMemoryRegionsToSave(), GetProcess(), GetThreadsToSave(), and SetProcess().
m_regions_to_save
MemoryRanges lldb_private::SaveCoreOptions::m_regions_to_save private
Definition at line 67 of file SaveCoreOptions.h.
Referenced by AddMemoryRegionToSave(), Clear(), and GetCoreFileMemoryRanges().
m_style
std::optional<lldb::SaveCoreStyle> lldb_private::SaveCoreOptions::m_style private
Definition at line 64 of file SaveCoreOptions.h.
Referenced by Clear(), GetStyle(), and SetStyle().
m_threads_to_save
std::unordered_set<lldb::tid_t> lldb_private::SaveCoreOptions::m_threads_to_save private
Definition at line 66 of file SaveCoreOptions.h.
Referenced by AddThread(), Clear(), ClearProcessSpecificData(), EnsureValidConfiguration(), GetThreadsToSave(), HasSpecifiedThreads(), RemoveThread(), and ShouldThreadBeSaved().
The documentation for this class was generated from the following files:
SaveCoreOptions.h
SaveCoreOptions.cpp