LLDB: lldb_private::ProcessLauncherPosixFork Class Reference
lldb_private::ProcessLauncherPosixFork Class Reference
#include <ProcessLauncherPosixFork.h>
Public Member Functions
HostProcess LaunchProcess (const ProcessLaunchInfo &launch_info, Status &error) override
Public Member Functions inherited from lldb_private::ProcessLauncher
virtual ~ProcessLauncher ()=default
Detailed Description
Definition at line 16 of file ProcessLauncherPosixFork.h.
Member Function Documentation
LaunchProcess()
HostProcess ProcessLauncherPosixFork::LaunchProcess (const ProcessLaunchInfo & launch_info, Status & error) override virtual
Implements lldb_private::ProcessLauncher.
Definition at line 254 of file ProcessLauncherPosixFork.cpp.
References ChildFunc(), lldb_private::PipePosix::CloseReadFileDescriptor(), lldb_private::PipePosix::CloseWriteFileDescriptor(), lldb_private::PipePosix::CreateNew(), error(), fork(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::PipePosix::GetReadFileDescriptor(), LLDB_INVALID_PROCESS_ID, lldb_private::PipePosix::ReleaseWriteFileDescriptor(), and lldb_private::Status.
Referenced by lldb_private::process_aix::NativeProcessAIX::Manager::Launch(), lldb_private::process_freebsd::NativeProcessFreeBSD::Manager::Launch(), lldb_private::process_linux::NativeProcessLinux::Manager::Launch(), and lldb_private::process_netbsd::NativeProcessNetBSD::Manager::Launch().
The documentation for this class was generated from the following files:
ProcessLauncherPosixFork.h
ProcessLauncherPosixFork.cpp