LLDB: lldb::SBInstructionList Class Reference
lldb::SBInstructionList Class Reference
#include <SBInstructionList.h>
Public Member Functions
SBInstructionList ()
SBInstructionList (const SBInstructionList &rhs)
const SBInstructionList & operator= (const SBInstructionList &rhs)
~SBInstructionList ()
operator bool () const
bool IsValid () const
size_t GetSize ()
lldb::SBInstruction GetInstructionAtIndex (uint32_t idx)
size_t GetInstructionsCount (const SBAddress &start, const SBAddress &end, bool canSetBreakpoint=false)
void Clear ()
void AppendInstruction (lldb::SBInstruction inst)
void Print (FILE *out)
void Print (SBFile out)
void Print (FileSP BORROWED)
bool GetDescription (lldb::SBStream &description)
bool GetDescription (lldb::SBStream &description, lldb::SBExecutionContext &exe_ctx)
bool DumpEmulationForAllInstructions (const char *triple)
Protected Member Functions
void SetDisassembler (const lldb::DisassemblerSP &opaque_sp)
bool GetDescription (lldb_private::Stream &description, lldb_private::ExecutionContext *exe_ctx=nullptr)
Private Attributes
lldb::DisassemblerSP m_opaque_sp
Friends
class SBFunction
class SBSymbol
class SBTarget
Detailed Description
Definition at line 18 of file SBInstructionList.h.
Constructor & Destructor Documentation
SBInstructionList() [1/2]
SBInstructionList::SBInstructionList ()
Definition at line 26 of file SBInstructionList.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by operator=(), and SBInstructionList().
SBInstructionList() [2/2]
SBInstructionList::SBInstructionList (const SBInstructionList & rhs)
Definition at line 28 of file SBInstructionList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBInstructionList().
~SBInstructionList()
SBInstructionList::~SBInstructionList () default
References AppendInstruction(), Clear(), DumpEmulationForAllInstructions(), GetDescription(), GetInstructionAtIndex(), GetInstructionsCount(), GetSize(), IsValid(), and Print().
Member Function Documentation
AppendInstruction()
void SBInstructionList::AppendInstruction (lldb::SBInstruction inst)
Definition at line 106 of file SBInstructionList.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBInstructionList().
Clear()
void SBInstructionList::Clear ()
Definition at line 100 of file SBInstructionList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBInstructionList().
DumpEmulationForAllInstructions()
bool SBInstructionList::DumpEmulationForAllInstructions (const char * triple)
Definition at line 197 of file SBInstructionList.cpp.
References GetInstructionAtIndex(), GetSize(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBInstructionList().
GetDescription() [1/3]
bool SBInstructionList::GetDescription (lldb::SBStream & description)
Definition at line 138 of file SBInstructionList.cpp.
References GetDescription(), LLDB_INSTRUMENT_VA, and lldb::SBStream::ref().
Referenced by GetDescription(), GetDescription(), Print(), Print(), Print(), SBTarget, and ~SBInstructionList().
GetDescription() [2/3]
bool SBInstructionList::GetDescription (lldb::SBStream & description, lldb::SBExecutionContext & exe_ctx)
Definition at line 143 of file SBInstructionList.cpp.
References lldb::SBExecutionContext::get(), GetDescription(), LLDB_INSTRUMENT_VA, and lldb::SBStream::ref().
GetDescription() [3/3]
bool SBInstructionList::GetDescription (lldb_private::Stream & description, lldb_private::ExecutionContext * exe_ctx = nullptr) protected
Definition at line 150 of file SBInstructionList.cpp.
References lldb_private::Instruction::Dump(), lldb_private::Stream::EOL(), lldb_private::Instruction::GetAddress(), lldb_private::Opcode::GetByteSize(), lldb_private::Address::GetModule(), lldb_private::Instruction::GetOpcode(), GetSize(), m_opaque_sp, and lldb_private::FormatEntity::Parse().
GetInstructionAtIndex()
SBInstruction SBInstructionList::GetInstructionAtIndex (uint32_t idx)
Definition at line 62 of file SBInstructionList.cpp.
References GetSize(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBInstruction::SetOpaque().
Referenced by DumpEmulationForAllInstructions(), GetInstructionsCount(), and ~SBInstructionList().
GetInstructionsCount()
size_t SBInstructionList::GetInstructionsCount (const SBAddress & start, const SBAddress & end, bool canSetBreakpoint = false)
Definition at line 73 of file SBInstructionList.cpp.
References lldb::SBInstruction::CanSetBreakpoint(), lldb::SBInstruction::GetAddress(), GetInstructionAtIndex(), GetSize(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBInstructionList().
GetSize()
size_t SBInstructionList::GetSize ()
Definition at line 54 of file SBInstructionList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by DumpEmulationForAllInstructions(), GetDescription(), GetInstructionAtIndex(), GetInstructionsCount(), and ~SBInstructionList().
IsValid()
bool SBInstructionList::IsValid () const
Definition at line 44 of file SBInstructionList.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBInstructionList().
operator bool()
SBInstructionList::operator bool () const explicit
Definition at line 48 of file SBInstructionList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator=()
const SBInstructionList & SBInstructionList::operator= (const SBInstructionList & rhs)
Definition at line 33 of file SBInstructionList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBInstructionList().
Print() [1/3]
void SBInstructionList::Print (FILE * out)
Definition at line 114 of file SBInstructionList.cpp.
References GetDescription(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBInstructionList().
Print() [2/3]
void SBInstructionList::Print (FileSP BORROWED)
Definition at line 130 of file SBInstructionList.cpp.
References GetDescription(), and LLDB_INSTRUMENT_VA.
Print() [3/3]
void SBInstructionList::Print (SBFile out)
Definition at line 122 of file SBInstructionList.cpp.
References GetDescription(), lldb::SBFile::IsValid(), LLDB_INSTRUMENT_VA, and lldb::SBFile::m_opaque_sp.
SetDisassembler()
void SBInstructionList::SetDisassembler (const lldb::DisassemblerSP & opaque_sp) protected
Definition at line 110 of file SBInstructionList.cpp.
References m_opaque_sp.
Referenced by lldb::SBFunction::GetInstructions(), lldb::SBSymbol::GetInstructions(), lldb::SBTarget::GetInstructionsWithFlavor(), lldb::SBTarget::ReadInstructions(), lldb::SBTarget::ReadInstructions(), and SBTarget.
Friends And Related Symbol Documentation
SBFunction
friend class SBFunction friend
Definition at line 65 of file SBInstructionList.h.
References SBFunction.
Referenced by SBFunction.
SBSymbol
friend class SBSymbol friend
Definition at line 66 of file SBInstructionList.h.
References SBSymbol.
Referenced by SBSymbol.
SBTarget
friend class SBTarget friend
Definition at line 67 of file SBInstructionList.h.
References GetDescription(), SBTarget, and SetDisassembler().
Referenced by SBTarget.
Member Data Documentation
m_opaque_sp
lldb::DisassemblerSP lldb::SBInstructionList::m_opaque_sp private
Definition at line 74 of file SBInstructionList.h.
Referenced by Clear(), DumpEmulationForAllInstructions(), GetDescription(), GetInstructionAtIndex(), GetSize(), operator bool(), operator=(), SBInstructionList(), and SetDisassembler().
The documentation for this class was generated from the following files:
SBInstructionList.h
SBInstructionList.cpp