LLDB: lldb_private::plugin::dwarf::UniqueDWARFASTTypeList Class Reference
lldb_private::plugin::dwarf::UniqueDWARFASTTypeList Class Reference
#include <UniqueDWARFASTType.h>
Public Member Functions
UniqueDWARFASTTypeList ()
~UniqueDWARFASTTypeList ()=default
uint32_t GetSize ()
void Append (const UniqueDWARFASTType &entry)
UniqueDWARFASTType * Find (const DWARFDIE &die, const Declaration &decl, const int32_t byte_size, bool is_forward_declaration)
Protected Types
typedef std::vector< UniqueDWARFASTType > collection
Protected Attributes
collection m_collection
Detailed Description
Definition at line 57 of file UniqueDWARFASTType.h.
Member Typedef Documentation
collection
typedef std::vector<UniqueDWARFASTType> lldb_private::plugin::dwarf::UniqueDWARFASTTypeList::collection protected
Definition at line 74 of file UniqueDWARFASTType.h.
Constructor & Destructor Documentation
UniqueDWARFASTTypeList()
lldb_private::plugin::dwarf::UniqueDWARFASTTypeList::UniqueDWARFASTTypeList () inline
Definition at line 59 of file UniqueDWARFASTType.h.
References m_collection.
~UniqueDWARFASTTypeList()
lldb_private::plugin::dwarf::UniqueDWARFASTTypeList::~UniqueDWARFASTTypeList () default
Member Function Documentation
Append()
void lldb_private::plugin::dwarf::UniqueDWARFASTTypeList::Append (const UniqueDWARFASTType & entry) inline
Definition at line 65 of file UniqueDWARFASTType.h.
References m_collection.
Find()
UniqueDWARFASTType * UniqueDWARFASTTypeList::Find (const DWARFDIE & die, const Declaration & decl, const int32_t byte_size, bool is_forward_declaration)
Definition at line 50 of file UniqueDWARFASTType.cpp.
References lldb_private::plugin::dwarf::DWARFDIE::GetName(), lldb_private::plugin::dwarf::DWARFDebugInfoEntry::GetParent(), lldb_private::plugin::dwarf::DWARFDIE::GetParent(), IsSizeAndDeclarationMatching(), IsStructOrClassTag(), m_collection, lldb_private::plugin::dwarf::DWARFBaseDIE::m_die, and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
GetSize()
uint32_t lldb_private::plugin::dwarf::UniqueDWARFASTTypeList::GetSize () inline
Definition at line 63 of file UniqueDWARFASTType.h.
References m_collection.
Member Data Documentation
m_collection
collection lldb_private::plugin::dwarf::UniqueDWARFASTTypeList::m_collection protected
Definition at line 75 of file UniqueDWARFASTType.h.
Referenced by Append(), Find(), GetSize(), and UniqueDWARFASTTypeList().
The documentation for this class was generated from the following files:
UniqueDWARFASTType.h
UniqueDWARFASTType.cpp