LLDB: lldb::SBInputReader Class Reference
lldb::SBInputReader Class Reference
#include <SBDebugger.h>
Public Member Functions
SBInputReader ()=default
~SBInputReader ()=default
SBError Initialize (lldb::SBDebugger &sb_debugger, unsigned long(*callback)(void *, lldb::SBInputReader *, lldb::InputReaderAction, char const *, unsigned long), void *a, lldb::InputReaderGranularity b, char const *c, char const *d, bool e)
void SetIsDone (bool)
bool IsActive () const
Detailed Description
Definition at line 29 of file SBDebugger.h.
Constructor & Destructor Documentation
SBInputReader()
lldb::SBInputReader::SBInputReader () default
~SBInputReader()
lldb::SBInputReader::~SBInputReader () default
References Initialize(), IsActive(), and SetIsDone().
Member Function Documentation
Initialize()
SBError SBInputReader::Initialize (lldb::SBDebugger & sb_debugger, unsigned long(* callback)(void *, lldb::SBInputReader *, lldb::InputReaderAction, char const *, unsigned long), void * a, lldb::InputReaderGranularity b, char const * c, char const * d, bool e)
Definition at line 71 of file SBDebugger.cpp.
References LLDB_INSTRUMENT_VA, and lldb::SBError.
Referenced by ~SBInputReader().
IsActive()
bool SBInputReader::IsActive () const
Definition at line 85 of file SBDebugger.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBInputReader().
SetIsDone()
void SBInputReader::SetIsDone (bool b)
Definition at line 83 of file SBDebugger.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBInputReader().
The documentation for this class was generated from the following files:
SBDebugger.h
SBDebugger.cpp