LLDB: lldb_private::ScriptInterpreterPythonImpl::Locker Class Reference
lldb_private::ScriptInterpreterPythonImpl::Locker Class Reference
#include <ScriptInterpreterPythonImpl.h>
Public Types
enum OnEntry { AcquireLock = 0x0001 , InitSession = 0x0002 , InitGlobals = 0x0004 , NoSTDIN = 0x0008 }
enum OnLeave { FreeLock = 0x0001 , FreeAcquiredLock = 0x0002 , TearDownSession = 0x0004 }
Public Member Functions
Locker (ScriptInterpreterPythonImpl *py_interpreter, uint16_t on_entry=AcquireLock|InitSession, uint16_t on_leave=FreeLock|TearDownSession, lldb::FileSP in=nullptr, lldb::FileSP out=nullptr, lldb::FileSP err=nullptr)
~Locker () override
Public Member Functions inherited from lldb_private::ScriptInterpreterLocker
ScriptInterpreterLocker ()=default
virtual ~ScriptInterpreterLocker ()=default
Private Member Functions
bool DoAcquireLock ()
bool DoInitSession (uint16_t on_entry_flags, lldb::FileSP in, lldb::FileSP out, lldb::FileSP err)
bool DoFreeLock ()
bool DoTearDownSession ()
Private Attributes
bool m_teardown_session
ScriptInterpreterPythonImpl * m_python_interpreter
PyGILState_STATE m_GILState
Detailed Description
Definition at line 302 of file ScriptInterpreterPythonImpl.h.
Member Enumeration Documentation
OnEntry
enum lldb_private::ScriptInterpreterPythonImpl::Locker::OnEntry
Enumerator
AcquireLock
InitSession
InitGlobals
NoSTDIN
Definition at line 304 of file ScriptInterpreterPythonImpl.h.
OnLeave
enum lldb_private::ScriptInterpreterPythonImpl::Locker::OnLeave
Enumerator
FreeLock
FreeAcquiredLock
TearDownSession
Definition at line 311 of file ScriptInterpreterPythonImpl.h.
Constructor & Destructor Documentation
Locker()
ScriptInterpreterPythonImpl::Locker::Locker (ScriptInterpreterPythonImpl * py_interpreter, uint16_t on_entry = AcquireLock | InitSession, uint16_t on_leave = FreeLock | TearDownSession, lldb::FileSP in = nullptr, lldb::FileSP out = nullptr, lldb::FileSP err = nullptr)
Definition at line 309 of file ScriptInterpreterPython.cpp.
References DoAcquireLock(), DoInitSession(), InitSession, m_python_interpreter, m_teardown_session, lldb_private::ScriptInterpreterLocker::ScriptInterpreterLocker(), lldb_private::ScriptInterpreterPythonImpl::ScriptInterpreterPythonImpl(), and TearDownSession.
~Locker()
ScriptInterpreterPythonImpl::Locker::~Locker () override
Definition at line 363 of file ScriptInterpreterPython.cpp.
References DoFreeLock(), DoTearDownSession(), and m_teardown_session.
Member Function Documentation
DoAcquireLock()
bool ScriptInterpreterPythonImpl::Locker::DoAcquireLock () private
Definition at line 324 of file ScriptInterpreterPython.cpp.
References lldb_private::GetLog(), LLDB_LOGV, m_GILState, m_python_interpreter, and lldb_private::Script.
Referenced by Locker().
DoFreeLock()
bool ScriptInterpreterPythonImpl::Locker::DoFreeLock () private
Definition at line 347 of file ScriptInterpreterPython.cpp.
References lldb_private::GetLog(), LLDB_LOGV, m_GILState, m_python_interpreter, and lldb_private::Script.
Referenced by ~Locker().
DoInitSession()
bool ScriptInterpreterPythonImpl::Locker::DoInitSession (uint16_t on_entry_flags, lldb::FileSP in, lldb::FileSP out, lldb::FileSP err) private
Definition at line 339 of file ScriptInterpreterPython.cpp.
References m_python_interpreter.
Referenced by Locker().
DoTearDownSession()
bool ScriptInterpreterPythonImpl::Locker::DoTearDownSession () private
Definition at line 356 of file ScriptInterpreterPython.cpp.
References m_python_interpreter.
Referenced by ~Locker().
Member Data Documentation
m_GILState
PyGILState_STATE lldb_private::ScriptInterpreterPythonImpl::Locker::m_GILState private
Definition at line 338 of file ScriptInterpreterPythonImpl.h.
Referenced by DoAcquireLock(), and DoFreeLock().
m_python_interpreter
ScriptInterpreterPythonImpl* lldb_private::ScriptInterpreterPythonImpl::Locker::m_python_interpreter private
Definition at line 337 of file ScriptInterpreterPythonImpl.h.
Referenced by DoAcquireLock(), DoFreeLock(), DoInitSession(), DoTearDownSession(), and Locker().
m_teardown_session
bool lldb_private::ScriptInterpreterPythonImpl::Locker::m_teardown_session private
Definition at line 336 of file ScriptInterpreterPythonImpl.h.
Referenced by Locker(), and ~Locker().
The documentation for this class was generated from the following files:
ScriptInterpreterPythonImpl.h
ScriptInterpreterPython.cpp