LLDB: lldb::SBBreakpointLocation Class Reference
lldb::SBBreakpointLocation Class Reference
#include <SBBreakpointLocation.h>
Public Member Functions
SBBreakpointLocation ()
SBBreakpointLocation (const lldb::SBBreakpointLocation &rhs)
~SBBreakpointLocation ()
const lldb::SBBreakpointLocation & operator= (const lldb::SBBreakpointLocation &rhs)
break_id_t GetID ()
operator bool () const
bool IsValid () const
lldb::SBAddress GetAddress ()
lldb::addr_t GetLoadAddress ()
void SetEnabled (bool enabled)
bool IsEnabled ()
uint32_t GetHitCount ()
uint32_t GetIgnoreCount ()
void SetIgnoreCount (uint32_t n)
void SetCondition (const char *condition)
const char * GetCondition ()
void SetAutoContinue (bool auto_continue)
bool GetAutoContinue ()
void SetCallback (SBBreakpointHitCallback callback, void *baton)
void SetScriptCallbackFunction (const char *callback_function_name)
SBError SetScriptCallbackFunction (const char *callback_function_name, lldb::SBStructuredData &extra_args)
SBError SetScriptCallbackBody (const char *script_body_text)
void SetCommandLineCommands (lldb::SBStringList &commands)
bool GetCommandLineCommands (lldb::SBStringList &commands)
void SetThreadID (lldb::tid_t sb_thread_id)
lldb::tid_t GetThreadID ()
void SetThreadIndex (uint32_t index)
uint32_t GetThreadIndex () const
void SetThreadName (const char *thread_name)
const char * GetThreadName () const
void SetQueueName (const char *queue_name)
const char * GetQueueName () const
bool IsResolved ()
bool GetDescription (lldb::SBStream &description, DescriptionLevel level)
SBBreakpoint GetBreakpoint ()
Protected Member Functions
SBBreakpointLocation (const lldb::BreakpointLocationSP &break_loc_sp)
Private Member Functions
void SetLocation (const lldb::BreakpointLocationSP &break_loc_sp)
BreakpointLocationSP GetSP () const
Private Attributes
lldb::BreakpointLocationWP m_opaque_wp
Friends
class lldb_private::ScriptInterpreter
class lldb_private::python::SWIGBridge
class lldb_private::lua::SWIGBridge
class SBBreakpoint
class SBBreakpointCallbackBaton
Detailed Description
Definition at line 26 of file SBBreakpointLocation.h.
Constructor & Destructor Documentation
SBBreakpointLocation() [1/3]
SBBreakpointLocation::SBBreakpointLocation ()
Definition at line 35 of file SBBreakpointLocation.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb_private::lua::SWIGBridge, lldb_private::ScriptInterpreter, operator=(), and SBBreakpointLocation().
SBBreakpointLocation() [2/3]
SBBreakpointLocation::SBBreakpointLocation (const lldb::SBBreakpointLocation & rhs)
Definition at line 43 of file SBBreakpointLocation.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_wp, and SBBreakpointLocation().
~SBBreakpointLocation()
SBBreakpointLocation::~SBBreakpointLocation () default
References GetAddress(), GetAutoContinue(), GetBreakpoint(), GetCommandLineCommands(), GetCondition(), GetDescription(), GetHitCount(), GetID(), GetIgnoreCount(), GetLoadAddress(), GetQueueName(), GetThreadID(), GetThreadIndex(), GetThreadName(), IsEnabled(), IsResolved(), IsValid(), operator=(), SBBreakpoint, SetAutoContinue(), SetCallback(), SetCommandLineCommands(), SetCondition(), SetEnabled(), SetIgnoreCount(), SetQueueName(), SetScriptCallbackBody(), SetScriptCallbackFunction(), SetThreadID(), SetThreadIndex(), and SetThreadName().
SBBreakpointLocation() [3/3]
SBBreakpointLocation::SBBreakpointLocation (const lldb::BreakpointLocationSP & break_loc_sp) protected
Definition at line 37 of file SBBreakpointLocation.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_wp.
Member Function Documentation
GetAddress()
SBAddress SBBreakpointLocation::GetAddress ()
Definition at line 72 of file SBBreakpointLocation.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBAddress.
Referenced by ~SBBreakpointLocation().
GetAutoContinue()
bool SBBreakpointLocation::GetAutoContinue ()
Definition at line 197 of file SBBreakpointLocation.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
GetBreakpoint()
SBBreakpoint SBBreakpointLocation::GetBreakpoint ()
Definition at line 454 of file SBBreakpointLocation.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and SBBreakpoint.
Referenced by ~SBBreakpointLocation().
GetCommandLineCommands()
bool SBBreakpointLocation::GetCommandLineCommands (lldb::SBStringList & commands)
Definition at line 298 of file SBBreakpointLocation.cpp.
References lldb::SBStringList::AppendList(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
GetCondition()
const char * SBBreakpointLocation::GetCondition ()
Definition at line 171 of file SBBreakpointLocation.cpp.
References lldb_private::ConstString::GetCString(), GetSP(), lldb_private::StopCondition::GetText(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
GetDescription()
bool SBBreakpointLocation::GetDescription (lldb::SBStream & description, DescriptionLevel level)
Definition at line 424 of file SBBreakpointLocation.cpp.
References lldb_private::Stream::EOL(), GetSP(), LLDB_INSTRUMENT_VA, lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
Referenced by ~SBBreakpointLocation().
GetHitCount()
uint32_t SBBreakpointLocation::GetHitCount ()
Definition at line 121 of file SBBreakpointLocation.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
GetID()
break_id_t SBBreakpointLocation::GetID ()
Definition at line 442 of file SBBreakpointLocation.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and LLDB_INVALID_BREAK_ID.
Referenced by ~SBBreakpointLocation().
GetIgnoreCount()
uint32_t SBBreakpointLocation::GetIgnoreCount ()
Definition at line 133 of file SBBreakpointLocation.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
GetLoadAddress()
addr_t SBBreakpointLocation::GetLoadAddress ()
Definition at line 83 of file SBBreakpointLocation.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and LLDB_INVALID_ADDRESS.
Referenced by ~SBBreakpointLocation().
GetQueueName()
const char * SBBreakpointLocation::GetQueueName () const
Definition at line 394 of file SBBreakpointLocation.cpp.
References lldb_private::ConstString::GetCString(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
GetSP()
BreakpointLocationSP SBBreakpointLocation::GetSP () const private
Definition at line 58 of file SBBreakpointLocation.cpp.
References m_opaque_wp.
Referenced by GetAddress(), GetAutoContinue(), GetBreakpoint(), GetCommandLineCommands(), GetCondition(), GetDescription(), GetHitCount(), GetID(), GetIgnoreCount(), GetLoadAddress(), GetQueueName(), GetThreadID(), GetThreadIndex(), GetThreadName(), IsEnabled(), IsResolved(), operator bool(), SBBreakpointCallbackBaton, SetAutoContinue(), SetCallback(), SetCommandLineCommands(), SetCondition(), SetEnabled(), SetIgnoreCount(), SetQueueName(), SetScriptCallbackBody(), SetScriptCallbackFunction(), SetThreadID(), SetThreadIndex(), and SetThreadName().
GetThreadID()
lldb::tid_t SBBreakpointLocation::GetThreadID ()
Definition at line 323 of file SBBreakpointLocation.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and LLDB_INVALID_THREAD_ID.
Referenced by ~SBBreakpointLocation().
GetThreadIndex()
uint32_t SBBreakpointLocation::GetThreadIndex () const
Definition at line 347 of file SBBreakpointLocation.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and UINT32_MAX.
Referenced by ~SBBreakpointLocation().
GetThreadName()
const char * SBBreakpointLocation::GetThreadName () const
Definition at line 371 of file SBBreakpointLocation.cpp.
References lldb_private::ConstString::GetCString(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
IsEnabled()
bool SBBreakpointLocation::IsEnabled ()
Definition at line 109 of file SBBreakpointLocation.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
IsResolved()
bool SBBreakpointLocation::IsResolved ()
Definition at line 406 of file SBBreakpointLocation.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
IsValid()
bool SBBreakpointLocation::IsValid () const
Definition at line 62 of file SBBreakpointLocation.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
operator bool()
SBBreakpointLocation::operator bool () const explicit
Definition at line 66 of file SBBreakpointLocation.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
operator=()
const SBBreakpointLocation & SBBreakpointLocation::operator= (const lldb::SBBreakpointLocation & rhs)
Definition at line 48 of file SBBreakpointLocation.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_wp, and SBBreakpointLocation().
Referenced by ~SBBreakpointLocation().
SetAutoContinue()
void SBBreakpointLocation::SetAutoContinue (bool auto_continue)
Definition at line 186 of file SBBreakpointLocation.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
SetCallback()
void SBBreakpointLocation::SetCallback (SBBreakpointHitCallback callback, void * baton)
Definition at line 209 of file SBBreakpointLocation.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, lldb::SBBreakpointCallbackBaton::PrivateBreakpointHitCallback(), and SBBreakpointCallbackBaton.
Referenced by ~SBBreakpointLocation().
SetCommandLineCommands()
void SBBreakpointLocation::SetCommandLineCommands (lldb::SBStringList & commands)
Definition at line 281 of file SBBreakpointLocation.cpp.
References lldb::eScriptLanguageNone, lldb::SBStringList::GetSize(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
SetCondition()
void SBBreakpointLocation::SetCondition (const char * condition)
Definition at line 156 of file SBBreakpointLocation.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
SetEnabled()
void SBBreakpointLocation::SetEnabled (bool enabled)
Definition at line 98 of file SBBreakpointLocation.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
SetIgnoreCount()
void SBBreakpointLocation::SetIgnoreCount (uint32_t n)
Definition at line 145 of file SBBreakpointLocation.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
SetLocation()
void SBBreakpointLocation::SetLocation (const lldb::BreakpointLocationSP & break_loc_sp) private
Definition at line 418 of file SBBreakpointLocation.cpp.
References m_opaque_wp.
Referenced by lldb::SBBreakpoint::FindLocationByAddress(), lldb::SBBreakpoint::FindLocationByID(), lldb::SBBreakpoint::GetBreakpointLocationAtIndexFromEvent(), lldb::SBBreakpoint::GetLocationAtIndex(), lldb::SBBreakpointCallbackBaton::PrivateBreakpointHitCallback(), and SBBreakpointCallbackBaton.
SetQueueName()
void SBBreakpointLocation::SetQueueName (const char * queue_name)
Definition at line 383 of file SBBreakpointLocation.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
SetScriptCallbackBody()
SBError SBBreakpointLocation::SetScriptCallbackBody (const char * script_body_text)
Definition at line 257 of file SBBreakpointLocation.cpp.
References error(), lldb_private::Status::FromErrorString(), GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBError::SetError().
Referenced by ~SBBreakpointLocation().
SetScriptCallbackFunction() [1/2]
void SBBreakpointLocation::SetScriptCallbackFunction (const char * callback_function_name)
Definition at line 224 of file SBBreakpointLocation.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
SetScriptCallbackFunction() [2/2]
SBError SBBreakpointLocation::SetScriptCallbackFunction (const char * callback_function_name, lldb::SBStructuredData & extra_args)
Definition at line 229 of file SBBreakpointLocation.cpp.
References error(), lldb_private::Status::FromErrorString(), GetSP(), LLDB_INSTRUMENT_VA, lldb::SBStructuredData::m_impl_up, and lldb::SBError::SetError().
SetThreadID()
void SBBreakpointLocation::SetThreadID (lldb::tid_t sb_thread_id)
Definition at line 312 of file SBBreakpointLocation.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
SetThreadIndex()
void SBBreakpointLocation::SetThreadIndex (uint32_t index)
Definition at line 336 of file SBBreakpointLocation.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
SetThreadName()
void SBBreakpointLocation::SetThreadName (const char * thread_name)
Definition at line 360 of file SBBreakpointLocation.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpointLocation().
Friends And Related Symbol Documentation
lldb_private::lua::SWIGBridge
friend class lldb_private::lua::SWIGBridge friend
Definition at line 106 of file SBBreakpointLocation.h.
References SBBreakpointLocation().
lldb_private::python::SWIGBridge
friend class lldb_private::python::SWIGBridge friend
Definition at line 105 of file SBBreakpointLocation.h.
lldb_private::ScriptInterpreter
friend class lldb_private::ScriptInterpreter friend
Definition at line 27 of file SBBreakpointLocation.h.
References SBBreakpointLocation().
SBBreakpoint
friend class SBBreakpoint friend
Definition at line 110 of file SBBreakpointLocation.h.
References SBBreakpoint.
Referenced by GetBreakpoint(), SBBreakpoint, and ~SBBreakpointLocation().
SBBreakpointCallbackBaton
friend class SBBreakpointCallbackBaton friend
Definition at line 111 of file SBBreakpointLocation.h.
References GetSP(), SBBreakpointCallbackBaton, and SetLocation().
Referenced by SBBreakpointCallbackBaton, and SetCallback().
Member Data Documentation
m_opaque_wp
lldb::BreakpointLocationWP lldb::SBBreakpointLocation::m_opaque_wp private
Definition at line 116 of file SBBreakpointLocation.h.
Referenced by lldb_private::ScriptInterpreter::GetOpaqueTypeFromSBBreakpointLocation(), GetSP(), operator=(), SBBreakpointLocation(), SBBreakpointLocation(), and SetLocation().
The documentation for this class was generated from the following files:
SBBreakpointLocation.h
SBBreakpointLocation.cpp