LLDB: RegisterContextDarwin_arm_Mach Class Reference
RegisterContextDarwin_arm_Mach Class Reference
Public Member Functions
RegisterContextDarwin_arm_Mach (lldb_private::Thread &thread, const DataExtractor &data)
void InvalidateAllRegisters () override
void SetRegisterDataFrom_LC_THREAD (const DataExtractor &data)
Public Member Functions inherited from RegisterContextDarwin_arm
RegisterContextDarwin_arm (lldb_private::Thread &thread, uint32_t concrete_frame_idx)
~RegisterContextDarwin_arm () override
size_t GetRegisterCount () override
const lldb_private::RegisterInfo * GetRegisterInfoAtIndex (size_t reg) override
size_t GetRegisterSetCount () override
const lldb_private::RegisterSet * GetRegisterSet (size_t set) override
bool ReadRegister (const lldb_private::RegisterInfo *reg_info, lldb_private::RegisterValue &reg_value) override
bool WriteRegister (const lldb_private::RegisterInfo *reg_info, const lldb_private::RegisterValue &reg_value) override
bool ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp) override
bool WriteAllRegisterValues (const lldb::DataBufferSP &data_sp) override
uint32_t ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num) override
Convert from a given register numbering scheme to the lldb register numbering scheme.
uint32_t NumSupportedHardwareBreakpoints () override
uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size) override
bool ClearHardwareBreakpoint (uint32_t hw_idx) override
uint32_t NumSupportedHardwareWatchpoints () override
uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, bool read, bool write) override
bool ClearHardwareWatchpoint (uint32_t hw_index) override
Public Member Functions inherited from lldb_private::RegisterContext
RegisterContext (Thread &thread, uint32_t concrete_frame_idx)
~RegisterContext () override
void InvalidateIfNeeded (bool force)
virtual lldb::ByteOrder GetByteOrder ()
virtual bool RegisterWriteCausesReconfigure (const llvm::StringRef name)
virtual bool ReconfigureRegisterInfo ()
virtual bool ReadAllRegisterValues (lldb_private::RegisterCheckpoint &reg_checkpoint)
virtual bool WriteAllRegisterValues (const lldb_private::RegisterCheckpoint &reg_checkpoint)
bool CopyFromRegisterContext (lldb::RegisterContextSP context)
virtual bool HardwareSingleStep (bool enable)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, uint32_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, uint32_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual Thread & GetThread ()
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num)
uint64_t GetPC (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetThreadPointer (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool GetPCForSymbolication (Address &address)
Get an address suitable for symbolication.
bool SetPC (uint64_t pc)
bool SetPC (Address addr)
uint64_t GetSP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetSP (uint64_t sp)
uint64_t GetFP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetFP (uint64_t fp)
const char * GetRegisterName (uint32_t reg)
uint64_t GetReturnAddress (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetFlags (uint64_t fail_value=0)
uint64_t ReadRegisterAsUnsigned (uint32_t reg, uint64_t fail_value)
uint64_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, uint64_t fail_value)
bool WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
bool WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
bool ConvertBetweenRegisterKinds (lldb::RegisterKind source_rk, uint32_t source_regnum, lldb::RegisterKind target_rk, uint32_t &target_regnum)
lldb::TargetSP CalculateTarget () override
lldb::ProcessSP CalculateProcess () override
lldb::ThreadSP CalculateThread () override
lldb::StackFrameSP CalculateStackFrame () override
void CalculateExecutionContext (ExecutionContext &exe_ctx) override
Reconstruct the object's execution context into sc.
uint32_t GetStopID () const
void SetStopID (uint32_t stop_id)
Public Member Functions inherited from lldb_private::ExecutionContextScope
virtual ~ExecutionContextScope ()=default
Static Public Member Functions
static bool Create_LC_THREAD (Thread *thread, Stream &data)
Static Public Member Functions inherited from RegisterContextDarwin_arm
static void LogDBGRegisters (lldb_private::Log *log, const DBG &dbg)
Protected Member Functions
int DoReadGPR (lldb::tid_t tid, int flavor, GPR &gpr) override
int DoReadFPU (lldb::tid_t tid, int flavor, FPU &fpu) override
int DoReadEXC (lldb::tid_t tid, int flavor, EXC &exc) override
int DoReadDBG (lldb::tid_t tid, int flavor, DBG &dbg) override
int DoWriteGPR (lldb::tid_t tid, int flavor, const GPR &gpr) override
int DoWriteFPU (lldb::tid_t tid, int flavor, const FPU &fpu) override
int DoWriteEXC (lldb::tid_t tid, int flavor, const EXC &exc) override
int DoWriteDBG (lldb::tid_t tid, int flavor, const DBG &dbg) override
Protected Member Functions inherited from RegisterContextDarwin_arm
void InvalidateAllRegisterStates ()
int GetError (int flavor, uint32_t err_idx) const
bool SetError (int flavor, uint32_t err_idx, int err)
bool RegisterSetIsCached (int set) const
int ReadGPR (bool force)
int ReadFPU (bool force)
int ReadEXC (bool force)
int ReadDBG (bool force)
int WriteGPR ()
int WriteFPU ()
int WriteEXC ()
int WriteDBG ()
int ReadRegisterSet (uint32_t set, bool force)
int WriteRegisterSet (uint32_t set)
Protected Member Functions inherited from lldb_private::RegisterContext
virtual bool BehavesLikeZerothFrame () const
Indicates that this frame is currently executing code, that the PC value is not a return-pc but an actual executing instruction.
Additional Inherited Members
Protected Types inherited from RegisterContextDarwin_arm
enum {
GPRRegSet = 1 , GPRAltRegSet = 9 , FPURegSet = 2 , EXCRegSet = 3 ,
DBGRegSet = 4
}
enum { GPRWordCount = sizeof(GPR) / sizeof(uint32_t) , FPUWordCount = sizeof(FPU) / sizeof(uint32_t) , EXCWordCount = sizeof(EXC) / sizeof(uint32_t) , DBGWordCount = sizeof(DBG) / sizeof(uint32_t) }
enum { Read = 0 , Write = 1 , kNumErrors = 2 }
Static Protected Member Functions inherited from RegisterContextDarwin_arm
static uint32_t GetRegisterNumber (uint32_t reg_kind, uint32_t reg_num)
static int GetSetForNativeRegNum (int reg_num)
static size_t GetRegisterInfosCount ()
static const lldb_private::RegisterInfo * GetRegisterInfos ()
Protected Attributes inherited from RegisterContextDarwin_arm
GPR gpr
FPU fpu
EXC exc
DBG dbg
int gpr_errs [2]
int fpu_errs [2]
int exc_errs [2]
int dbg_errs [2]
Protected Attributes inherited from lldb_private::RegisterContext
Thread & m_thread
uint32_t m_concrete_frame_idx
uint32_t m_stop_id
Detailed Description
Definition at line 357 of file ObjectFileMachO.cpp.
Constructor & Destructor Documentation
RegisterContextDarwin_arm_Mach()
RegisterContextDarwin_arm_Mach::RegisterContextDarwin_arm_Mach (lldb_private::Thread & thread, const DataExtractor & data) inline
Definition at line 359 of file ObjectFileMachO.cpp.
References RegisterContextDarwin_arm::RegisterContextDarwin_arm(), and SetRegisterDataFrom_LC_THREAD().
Member Function Documentation
Create_LC_THREAD()
bool RegisterContextDarwin_arm_Mach::Create_LC_THREAD (Thread * thread, Stream & data) inline static
Definition at line 418 of file ObjectFileMachO.cpp.
References RegisterContextDarwin_arm::GPRRegSet, RegisterContextDarwin_arm::GPRWordCount, PrintRegisterValue(), and lldb_private::Stream::PutHex32().
Referenced by ObjectFileMachO::SaveCore().
DoReadDBG()
int RegisterContextDarwin_arm_Mach::DoReadDBG (lldb::tid_t tid, int flavor, DBG & dbg) inline override protected virtual
Implements RegisterContextDarwin_arm.
Definition at line 461 of file ObjectFileMachO.cpp.
References RegisterContextDarwin_arm::dbg.
DoReadEXC()
int RegisterContextDarwin_arm_Mach::DoReadEXC (lldb::tid_t tid, int flavor, EXC & exc) inline override protected virtual
Implements RegisterContextDarwin_arm.
Definition at line 459 of file ObjectFileMachO.cpp.
References RegisterContextDarwin_arm::exc.
DoReadFPU()
int RegisterContextDarwin_arm_Mach::DoReadFPU (lldb::tid_t tid, int flavor, FPU & fpu) inline override protected virtual
Implements RegisterContextDarwin_arm.
Definition at line 457 of file ObjectFileMachO.cpp.
References RegisterContextDarwin_arm::fpu.
DoReadGPR()
int RegisterContextDarwin_arm_Mach::DoReadGPR (lldb::tid_t tid, int flavor, GPR & gpr) inline override protected virtual
Reimplemented from RegisterContextDarwin_arm.
Definition at line 455 of file ObjectFileMachO.cpp.
References RegisterContextDarwin_arm::gpr.
DoWriteDBG()
int RegisterContextDarwin_arm_Mach::DoWriteDBG (lldb::tid_t tid, int flavor, const DBG & dbg) inline override protected virtual
Implements RegisterContextDarwin_arm.
Definition at line 475 of file ObjectFileMachO.cpp.
References RegisterContextDarwin_arm::dbg.
DoWriteEXC()
int RegisterContextDarwin_arm_Mach::DoWriteEXC (lldb::tid_t tid, int flavor, const EXC & exc) inline override protected virtual
Implements RegisterContextDarwin_arm.
Definition at line 471 of file ObjectFileMachO.cpp.
References RegisterContextDarwin_arm::exc.
DoWriteFPU()
int RegisterContextDarwin_arm_Mach::DoWriteFPU (lldb::tid_t tid, int flavor, const FPU & fpu) inline override protected virtual
Implements RegisterContextDarwin_arm.
Definition at line 467 of file ObjectFileMachO.cpp.
References RegisterContextDarwin_arm::fpu.
DoWriteGPR()
int RegisterContextDarwin_arm_Mach::DoWriteGPR (lldb::tid_t tid, int flavor, const GPR & gpr) inline override protected virtual
Implements RegisterContextDarwin_arm.
Definition at line 463 of file ObjectFileMachO.cpp.
References RegisterContextDarwin_arm::gpr.
InvalidateAllRegisters()
void RegisterContextDarwin_arm_Mach::InvalidateAllRegisters () inline override virtual
Reimplemented from RegisterContextDarwin_arm.
Definition at line 365 of file ObjectFileMachO.cpp.
SetRegisterDataFrom_LC_THREAD()
void RegisterContextDarwin_arm_Mach::SetRegisterDataFrom_LC_THREAD (const DataExtractor & data) inline
Definition at line 369 of file ObjectFileMachO.cpp.
References lldb::eByteOrderLittle, RegisterContextDarwin_arm::exc, RegisterContextDarwin_arm::EXCRegSet, lldb_private::DataExtractor::ExtractBytes(), RegisterContextDarwin_arm::fpu, RegisterContextDarwin_arm::FPURegSet, lldb_private::DataExtractor::GetByteSize(), lldb_private::DataExtractor::GetU32(), RegisterContextDarwin_arm::gpr, RegisterContextDarwin_arm::GPRAltRegSet, RegisterContextDarwin_arm::GPRRegSet, RegisterContextDarwin_arm::Read, and RegisterContextDarwin_arm::SetError().
Referenced by RegisterContextDarwin_arm_Mach().
The documentation for this class was generated from the following file:
ObjectFileMachO.cpp