LLDB: lldb_private::plugin::dwarf::SymbolFileWasm Class Reference
lldb_private::plugin::dwarf::SymbolFileWasm Class Reference
#include <SymbolFileWasm.h>
Public Member Functions
SymbolFileWasm (lldb::ObjectFileSP objfile_sp, SectionList *dwo_section_list)
~SymbolFileWasm () override
lldb::offset_t GetVendorDWARFOpcodeSize (const DataExtractor &data, const lldb::offset_t data_offset, const uint8_t op) const override
bool ParseVendorDWARFOpcode (uint8_t op, const DataExtractor &opcodes, lldb::offset_t &offset, RegisterContext *reg_ctx, lldb::RegisterKind reg_kind, std::vector< Value > &stack) const override
Public Member Functions inherited from lldb_private::plugin::dwarf::SymbolFileDWARF
SymbolFileDWARF (lldb::ObjectFileSP objfile_sp, SectionList *dwo_section_list)
~SymbolFileDWARF () override
uint32_t CalculateAbilities () override
void InitializeObject () override
Initialize the SymbolFile object.
lldb::LanguageType ParseLanguage (CompileUnit &comp_unit) override
XcodeSDK ParseXcodeSDK (CompileUnit &comp_unit) override
Return the Xcode SDK comp_unit was compiled against.
size_t ParseFunctions (CompileUnit &comp_unit) override
bool ParseLineTable (CompileUnit &comp_unit) override
bool ParseDebugMacros (CompileUnit &comp_unit) override
bool ForEachExternalModule (CompileUnit &, llvm::DenseSet< SymbolFile * > &, llvm::function_ref< bool(Module &)>) override
bool ParseSupportFiles (CompileUnit &comp_unit, SupportFileList &support_files) override
bool ParseIsOptimized (CompileUnit &comp_unit) override
size_t ParseTypes (CompileUnit &comp_unit) override
bool ParseImportedModules (const SymbolContext &sc, std::vector< SourceModule > &imported_modules) override
size_t ParseBlocksRecursive (Function &func) override
size_t ParseVariablesForContext (const SymbolContext &sc) override
std::optional< ArrayInfo > GetDynamicArrayInfoForUID (lldb::user_id_t type_uid, const ExecutionContext *exe_ctx) override
If type_uid points to an array type, return its characteristics.
bool CompleteType (CompilerType &compiler_type) override
Type * ResolveType (const DWARFDIE &die, bool assert_not_being_parsed=true, bool resolve_function_context=false)
CompilerDecl GetDeclForUID (lldb::user_id_t uid) override
CompilerDeclContext GetDeclContextForUID (lldb::user_id_t uid) override
CompilerDeclContext GetDeclContextContainingUID (lldb::user_id_t uid) override
std::vector< CompilerContext > GetCompilerContextForUID (lldb::user_id_t uid) override
void ParseDeclsForContext (CompilerDeclContext decl_ctx) override
uint32_t ResolveSymbolContext (const Address &so_addr, lldb::SymbolContextItem resolve_scope, SymbolContext &sc) override
Status CalculateFrameVariableError (StackFrame &frame) override
Subclasses will override this function to for GetFrameVariableError().
uint32_t ResolveSymbolContext (const SourceLocationSpec &src_location_spec, lldb::SymbolContextItem resolve_scope, SymbolContextList &sc_list) override
void FindGlobalVariables (ConstString name, const CompilerDeclContext &parent_decl_ctx, uint32_t max_matches, VariableList &variables) override
void FindGlobalVariables (const RegularExpression &regex, uint32_t max_matches, VariableList &variables) override
void FindFunctions (const Module::LookupInfo &lookup_info, const CompilerDeclContext &parent_decl_ctx, bool include_inlines, SymbolContextList &sc_list) override
void FindFunctions (const RegularExpression &regex, bool include_inlines, SymbolContextList &sc_list) override
void GetMangledNamesForFunction (const std::string &scope_qualified_name, std::vector< ConstString > &mangled_names) override
uint64_t GetDebugInfoSize (bool load_all_debug_info=false) override
Metrics gathering functions.
void FindTypes (const lldb_private::TypeQuery &match, lldb_private::TypeResults &results) override
Find types using a type-matching object that contains all search parameters.
void GetTypes (SymbolContextScope *sc_scope, lldb::TypeClass type_mask, TypeList &type_list) override
llvm::Expected< lldb::TypeSystemSP > GetTypeSystemForLanguage (lldb::LanguageType language) override
CompilerDeclContext FindNamespace (ConstString name, const CompilerDeclContext &parent_decl_ctx, bool only_root_namespaces) override
Finds a namespace of name name and whose parent context is parent_decl_ctx.
void PreloadSymbols () override
std::recursive_mutex & GetModuleMutex () const override
Symbols file subclasses should override this to return the Module that owns the TypeSystem that this symbol file modifies type information in.
llvm::StringRef GetPluginName () override
llvm::DWARFDebugAbbrev * DebugAbbrev ()
DWARFDebugInfo & DebugInfo ()
DWARFDIE GetDeclContextDIEContainingDIE (const DWARFDIE &die)
bool HasForwardDeclForCompilerType (const CompilerType &compiler_type)
CompileUnit * GetCompUnitForDWARFCompUnit (DWARFCompileUnit &dwarf_cu)
virtual void GetObjCMethods (ConstString class_name, llvm::function_ref< IterationAction(DWARFDIE die)> callback)
DebugMacrosSP ParseDebugMacros (lldb::offset_t *offset)
lldb::ModuleSP GetExternalModule (ConstString name)
const ExternalTypeModuleMap & getExternalTypeModules () const
Return the list of Clang modules imported by this SymbolFile.
virtual SymbolFileDWARF * GetDIERefSymbolFile (const DIERef &die_ref)
Given a DIERef, find the correct SymbolFileDWARF.
virtual DWARFDIE GetDIE (const DIERef &die_ref)
DWARFDIE GetDIE (lldb::user_id_t uid)
std::shared_ptr< SymbolFileDWARFDwo > GetDwoSymbolFileForCompileUnit (DWARFUnit &dwarf_cu, const DWARFDebugInfoEntry &cu_die)
std::optional< uint64_t > GetDWOId ()
If this is a DWARF object with a single CU, return its DW_AT_dwo_id.
DWARFUnit * GetSkeletonUnit (DWARFUnit *dwo_unit)
Given a DWO DWARFUnit, find the corresponding skeleton DWARFUnit in the main symbol file.
std::vector< std::unique_ptr< CallEdge > > ParseCallEdgesInFunction (UserID func_id) override
void Dump (Stream &s) override
void DumpClangAST (Stream &s, llvm::StringRef filter, bool show_colors) override
bool GetSeparateDebugInfo (StructuredData::Dictionary &d, bool errors_only, bool load_all_debug_info=false) override
List separate dwo files.
DWOStats GetDwoStats () override
Gets statistics about dwo files associated with this symbol file.
DWARFContext & GetDWARFContext ()
const std::shared_ptr< SymbolFileDWARFDwo > & GetDwpSymbolFile ()
FileSpec GetFile (DWARFUnit &unit, size_t file_idx)
StatsDuration::Duration GetDebugInfoParseTime () override
Return the time taken to parse the debug information.
StatsDuration::Duration GetDebugInfoIndexTime () override
Return the time it took to index the debug information in the object file.
StatsDuration & GetDebugInfoParseTimeRef ()
void ResetStatistics () override
Reset the statistics for the symbol file.
ConstString ConstructFunctionDemangledName (const DWARFDIE &die)
std::optional< uint64_t > GetFileIndex () const
void SetFileIndex (std::optional< uint64_t > file_index)
virtual llvm::DenseMap< const DWARFDebugInfoEntry *, Type * > & GetDIEToType ()
virtual llvm::DenseMap< lldb::opaque_compiler_type_t, DIERef > & GetForwardDeclCompilerTypeToDIE ()
virtual DIEToVariableSP & GetDIEToVariable ()
virtual UniqueDWARFASTTypeMap & GetUniqueDWARFASTTypeMap ()
bool ClassOrStructIsVirtual (const DWARFDIE &die)
SymbolFileDWARFDebugMap * GetDebugMapSymfile ()
virtual DWARFDIE FindDefinitionDIE (const DWARFDIE &die)
virtual lldb::TypeSP FindCompleteObjCDefinitionTypeForDIE (const DWARFDIE &die, ConstString type_name, bool must_be_implementation)
Type * ResolveTypeUID (lldb::user_id_t type_uid) override
Type * ResolveTypeUID (const DWARFDIE &die, bool assert_not_being_parsed)
Type * ResolveTypeUID (const DIERef &die_ref)
DWARFIndex * getIndex ()
Returns the DWARFIndex for this symbol, if it exists.
bool isA (const void *ClassID) const override
LLVM RTTI support.
Public Member Functions inherited from lldb_private::SymbolFileCommon
SymbolFileCommon (lldb::ObjectFileSP objfile_sp)
~SymbolFileCommon () override=default
uint32_t GetAbilities () override
Get a mask of what this symbol file supports for the object file that it was constructed with.
Symtab * GetSymtab (bool can_create=true) override
ObjectFile * GetObjectFile () override
const ObjectFile * GetObjectFile () const override
ObjectFile * GetMainObjectFile () override
void SectionFileAddressesChanged () override
Notify the SymbolFile that the file addresses in the Sections for this module have been changed.
uint32_t GetNumCompileUnits () override
lldb::CompUnitSP GetCompileUnitAtIndex (uint32_t idx) override
bool GetDebugInfoIndexWasLoadedFromCache () const override
Accessors for the bool that indicates if the debug info index was loaded from, or saved to the module index cache.
void SetDebugInfoIndexWasLoadedFromCache () override
bool GetDebugInfoIndexWasSavedToCache () const override
void SetDebugInfoIndexWasSavedToCache () override
bool GetDebugInfoHadFrameVariableErrors () const override
Accessors for the bool that indicates if there was debug info, but errors stopped variables from being able to be displayed correctly.
void SetDebugInfoHadFrameVariableErrors () override
lldb::TypeSP MakeType (lldb::user_id_t uid, ConstString name, std::optional< uint64_t > byte_size, SymbolContextScope *context, lldb::user_id_t encoding_uid, Type::EncodingDataType encoding_uid_type, const Declaration &decl, const CompilerType &compiler_qual_type, Type::ResolveState compiler_type_resolve_state, uint32_t opaque_payload=0) override
This function is used to create types that belong to a SymbolFile.
lldb::TypeSP CopyType (const lldb::TypeSP &other_type) override
Public Member Functions inherited from lldb_private::SymbolFile
SymbolFile ()=default
~SymbolFile () override=default
virtual SymbolFile * GetBackingSymbolFile ()
SymbolFileOnDemand class overrides this to return the underlying backing SymbolFile implementation that loads on-demand.
virtual bool GetLoadDebugInfoEnabled ()
Whether debug info will be loaded or not.
virtual void SetLoadDebugInfoEnabled ()
Specify debug info should be loaded.
virtual llvm::SmallSet< lldb::LanguageType, 4 > ParseAllLanguages (CompileUnit &comp_unit)
This function exists because SymbolFileDWARFDebugMap may extra compile units which aren't exposed as "real" compile units.
virtual bool ForEachExternalModule (lldb_private::CompileUnit &comp_unit, llvm::DenseSet< lldb_private::SymbolFile * > &visited_symbol_files, llvm::function_ref< bool(Module &)> lambda)
Apply a lambda to each external lldb::Module referenced by this comp_unit.
Status GetFrameVariableError (StackFrame &frame)
Get an error that describes why variables might be missing for a given symbol context.
virtual void FindFunctions (llvm::ArrayRef< Module::LookupInfo > lookup_infos, const CompilerDeclContext &parent_decl_ctx, bool include_inlines, SymbolContextList &sc_list)
virtual void AddSymbols (Symtab &symtab)
virtual lldb::UnwindPlanSP GetUnwindPlan (const Address &address, const RegisterInfoResolver &resolver)
virtual llvm::Expected< lldb::addr_t > GetParameterStackSize (const Symbol &symbol)
Return the number of stack bytes taken up by the parameters to this function.
virtual ModuleList GetDebugInfoModules ()
Get the additional modules that this symbol file uses to parse debug info.
std::unordered_map< lldb::CompUnitSP, Args > GetCompileOptions ()
Returns a map of compilation unit to the compile option arguments associated with that compilation unit.
std::string GetObjectName () const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Additional Inherited Members
Public Types inherited from lldb_private::plugin::dwarf::SymbolFileDWARF
typedef std::map< ConstString, lldb::ModuleSP > ExternalTypeModuleMap
typedef llvm::DenseMap< const DWARFDebugInfoEntry *, lldb::VariableSP > DIEToVariableSP
Public Types inherited from lldb_private::SymbolFile
enum Abilities {
CompileUnits = (1u << 0) , LineTables = (1u << 1) , Functions = (1u << 2) , Blocks = (1u << 3) ,
GlobalVariables = (1u << 4) , LocalVariables = (1u << 5) , VariableTypes = (1u << 6) , kAllAbilities = ((1u << 7) - 1u)
}
Static Public Member Functions inherited from lldb_private::plugin::dwarf::SymbolFileDWARF
static void Initialize ()
static void Terminate ()
static void DebuggerInitialize (Debugger &debugger)
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static SymbolFile * CreateInstance (lldb::ObjectFileSP objfile_sp)
static bool SupportedVersion (uint16_t version)
static DWARFDIE GetParentSymbolContextDIE (const DWARFDIE &die)
static bool DIEInDeclContext (const CompilerDeclContext &parent_decl_ctx, const DWARFDIE &die, bool only_root_namespaces=false)
static llvm::Expected< lldb::TypeSystemSP > GetTypeSystem (DWARFUnit &unit)
static DWARFASTParser * GetDWARFParser (DWARFUnit &unit)
static CompilerDecl GetDecl (const DWARFDIE &die)
static CompilerDeclContext GetDeclContext (const DWARFDIE &die)
static CompilerDeclContext GetContainingDeclContext (const DWARFDIE &die)
static lldb::LanguageType LanguageTypeFromDWARF (uint64_t val)
static lldb::LanguageType GetLanguage (DWARFUnit &unit)
static lldb::LanguageType GetLanguageFamily (DWARFUnit &unit)
Same as GetLanguage() but reports all C++ versions as C++ (no version).
static bool classof (const SymbolFile *obj)
static bool classof (const SymbolFileCommon *obj)
Static Public Member Functions inherited from lldb_private::SymbolFile
static SymbolFile * FindPlugin (lldb::ObjectFileSP objfile_sp)
static bool classof (const SymbolFile *obj)
Protected Types inherited from lldb_private::plugin::dwarf::SymbolFileDWARF
typedef llvm::SetVector< Type * > TypeSet
typedef RangeDataVector< lldb::addr_t, lldb::addr_t, Variable * > GlobalVariableMap
typedef std::unordered_map< lldb::offset_t, DebugMacrosSP > DebugMacrosMap
typedef std::set< DIERef > DIERefSet
typedef llvm::StringMap< DIERefSet > NameToOffsetMap
Protected Member Functions inherited from lldb_private::plugin::dwarf::SymbolFileDWARF
SymbolFileDWARF (const SymbolFileDWARF &)=delete
const SymbolFileDWARF & operator= (const SymbolFileDWARF &)=delete
virtual void LoadSectionData (lldb::SectionType sect_type, DWARFDataExtractor &data)
bool DeclContextMatchesThisSymbolFile (const CompilerDeclContext &decl_ctx)
uint32_t CalculateNumCompileUnits () override
lldb::CompUnitSP ParseCompileUnitAtIndex (uint32_t index) override
TypeList & GetTypeList () override
lldb::CompUnitSP ParseCompileUnit (DWARFCompileUnit &dwarf_cu)
virtual DWARFCompileUnit * GetDWARFCompileUnit (CompileUnit *comp_unit)
DWARFUnit * GetNextUnparsedDWARFCompileUnit (DWARFUnit *prev_cu)
bool GetFunction (const DWARFDIE &die, SymbolContext &sc)
Function * ParseFunction (CompileUnit &comp_unit, const DWARFDIE &die)
size_t ParseBlocksRecursive (CompileUnit &comp_unit, Block *parent_block, DWARFDIE die, lldb::addr_t function_file_addr)
size_t ParseTypes (const SymbolContext &sc, const DWARFDIE &die, bool parse_siblings, bool parse_children)
lldb::TypeSP ParseType (const SymbolContext &sc, const DWARFDIE &die, bool *type_is_new)
bool ParseSupportFiles (DWARFUnit &dwarf_cu, const lldb::ModuleSP &module, SupportFileList &support_files)
lldb::VariableSP ParseVariableDIE (const SymbolContext &sc, const DWARFDIE &die, const lldb::addr_t func_low_pc)
lldb::VariableSP ParseVariableDIECached (const SymbolContext &sc, const DWARFDIE &die)
void ParseAndAppendGlobalVariable (const SymbolContext &sc, const DWARFDIE &die, VariableList &cc_variable_list)
size_t ParseVariablesInFunctionContext (const SymbolContext &sc, const DWARFDIE &die, const lldb::addr_t func_low_pc)
size_t ParseVariablesInFunctionContextRecursive (const SymbolContext &sc, const DWARFDIE &die, lldb::addr_t func_low_pc, DIEArray &accumulator)
size_t PopulateBlockVariableList (VariableList &variable_list, const SymbolContext &sc, llvm::ArrayRef< DIERef > variable_dies, lldb::addr_t func_low_pc)
DIEArray MergeBlockAbstractParameters (const DWARFDIE &block_die, DIEArray &&variable_dies)
llvm::Expected< SymbolContext > ResolveFunctionCallLabel (FunctionCallLabel &label) override
Resolves the function corresponding to the specified LLDB function call label.
bool ResolveFunction (const DWARFDIE &die, bool include_inlines, SymbolContextList &sc_list)
void ResolveFunctionAndBlock (lldb::addr_t file_vm_addr, bool lookup_block, SymbolContext &sc)
Resolve functions and (possibly) blocks for the given file address and a compile unit.
Symbol * GetObjCClassSymbol (ConstString objc_class_name)
lldb::TypeSP GetTypeForDIE (const DWARFDIE &die, bool resolve_function_context=false)
void SetDebugMapModule (const lldb::ModuleSP &module_sp)
DWARFDIE FindBlockContainingSpecification (const DIERef &func_die_ref, dw_offset_t spec_block_die_offset)
DWARFDIE FindBlockContainingSpecification (const DWARFDIE &die, dw_offset_t spec_block_die_offset)
bool ClassContainsSelector (const DWARFDIE &class_die, ConstString selector)
std::vector< std::unique_ptr< CallEdge > > CollectCallEdges (lldb::ModuleSP module, DWARFDIE function_die)
Parse call site entries (DW_TAG_call_site), including any nested call site parameters (DW_TAG_call_site_parameter).
lldb::addr_t FixupAddress (lldb::addr_t file_addr)
If this symbol file is linked to by a debug map (see SymbolFileDWARFDebugMap), and file_addr is a file address relative to an object file, adjust file_addr so that it is relative to the main binary.
bool FixupAddress (Address &addr)
void GetTypes (const DWARFDIE &die, dw_offset_t min_die_offset, dw_offset_t max_die_offset, uint32_t type_mask, TypeSet &type_set)
GlobalVariableMap & GetGlobalAranges ()
void UpdateExternalModuleListIfNeeded ()
void BuildCuTranslationTable ()
std::optional< uint32_t > GetDWARFUnitIndex (uint32_t cu_idx)
void FindDwpSymbolFile ()
const SupportFileList * GetTypeUnitSupportFiles (DWARFTypeUnit &tu)
void InitializeFirstCodeAddressRecursive (const SectionList &section_list)
void InitializeFirstCodeAddress ()
void GetCompileOptions (std::unordered_map< lldb::CompUnitSP, Args > &args) override
Protected Member Functions inherited from lldb_private::SymbolFileCommon
void SetCompileUnitAtIndex (uint32_t idx, const lldb::CompUnitSP &cu_sp)
Protected Member Functions inherited from lldb_private::SymbolFile
void AssertModuleLock ()
virtual void GetCompileOptions (std::unordered_map< lldb::CompUnitSP, lldb_private::Args > &args)
Protected Attributes inherited from lldb_private::plugin::dwarf::SymbolFileDWARF
lldb::ModuleWP m_debug_map_module_wp
SymbolFileDWARFDebugMap * m_debug_map_symfile
llvm::once_flag m_dwp_symfile_once_flag
std::shared_ptr< SymbolFileDWARFDwo > m_dwp_symfile
DWARFContext m_context
llvm::once_flag m_info_once_flag
std::unique_ptr< DWARFDebugInfo > m_info
std::unique_ptr< llvm::DWARFDebugAbbrev > m_abbr
std::unique_ptr< GlobalVariableMap > m_global_aranges_up
DebugMacrosMap m_debug_macros_map
ExternalTypeModuleMap m_external_type_modules
std::unique_ptr< DWARFIndex > m_index
bool m_fetched_external_modules: 1
NameToOffsetMap m_function_scope_qualified_name_map
UniqueDWARFASTTypeMap m_unique_ast_type_map
llvm::DenseMap< const DWARFDebugInfoEntry *, Type * > m_die_to_type
DIEToVariableSP m_die_to_variable_sp
llvm::DenseMap< lldb::opaque_compiler_type_t, DIERef > m_forward_decl_compiler_type_to_die
llvm::DenseMap< dw_offset_t, std::unique_ptr< SupportFileList > > m_type_unit_support_files
std::vector< uint32_t > m_lldb_cu_to_dwarf_unit
lldb::addr_t m_first_code_address = LLDB_INVALID_ADDRESS
DWARF does not provide a good way for traditional (concatenating) linkers to invalidate debug info describing dead-stripped code.
StatsDuration m_parse_time
std::atomic_flag m_dwo_warning_issued = ATOMIC_FLAG_INIT
std::optional< uint64_t > m_file_index
If this DWARF file a .DWO file or a DWARF .o file on mac when no dSYM file is being used, this file index will be set to a valid value that can be used in DIERef objects which will contain an index that identifies the .DWO or .o file.
Protected Attributes inherited from lldb_private::SymbolFileCommon
lldb::ObjectFileSP m_objfile_sp
std::optional< std::vector< lldb::CompUnitSP > > m_compile_units
TypeList m_type_list
uint32_t m_abilities = 0
bool m_calculated_abilities = false
bool m_index_was_loaded_from_cache = false
bool m_index_was_saved_to_cache = false
bool m_debug_info_had_variable_errors = false
Set to true if any variable feteching errors have been found when calling GetFrameVariableError().
Detailed Description
Definition at line 16 of file SymbolFileWasm.h.
Constructor & Destructor Documentation
SymbolFileWasm()
SymbolFileWasm::SymbolFileWasm (lldb::ObjectFileSP objfile_sp, SectionList * dwo_section_list)
Definition at line 18 of file SymbolFileWasm.cpp.
References lldb_private::plugin::dwarf::SymbolFileDWARF::SymbolFileDWARF().
~SymbolFileWasm()
SymbolFileWasm::~SymbolFileWasm () override default
Member Function Documentation
GetVendorDWARFOpcodeSize()
lldb::offset_t SymbolFileWasm::GetVendorDWARFOpcodeSize (const DataExtractor & data, const lldb::offset_t data_offset, const uint8_t op) const override virtual
Reimplemented from lldb_private::plugin::dwarf::SymbolFileDWARF.
Definition at line 25 of file SymbolFileWasm.cpp.
References lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU8(), lldb_private::DataExtractor::GetULEB128(), and LLDB_INVALID_OFFSET.
ParseVendorDWARFOpcode()
bool SymbolFileWasm::ParseVendorDWARFOpcode (uint8_t op, const DataExtractor & opcodes, lldb::offset_t & offset, RegisterContext * reg_ctx, lldb::RegisterKind reg_kind, std::vector< Value > & stack) const override virtual
DWARF Location Index WebAssembly Construct
0 Local
1 or 3 Global
2 Operand Stack
Reimplemented from lldb_private::plugin::dwarf::SymbolFileDWARF.
Definition at line 49 of file SymbolFileWasm.cpp.
References lldb_private::DebugInfo, error(), lldb_private::eWasmTagGlobal, lldb_private::eWasmTagLocal, lldb_private::eWasmTagNotAWasmLocation, lldb_private::eWasmTagOperandStack, lldb_private::GetLog(), lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU8(), lldb_private::DataExtractor::GetULEB128(), lldb_private::GetWasmRegister(), LLDB_LOG_ERROR, and lldb_private::DWARFExpression::ReadRegisterValueAsScalar().
The documentation for this class was generated from the following files:
SymbolFileWasm.h
SymbolFileWasm.cpp