LLDB: lldb_private::TypeFormatImpl_EnumType Class Reference
lldb_private::TypeFormatImpl_EnumType Class Reference
#include <TypeFormat.h>
Public Types
typedef std::shared_ptr< TypeFormatImpl_EnumType > SharedPointer
Public Types inherited from lldb_private::TypeFormatImpl
enum class Type { eTypeUnknown , eTypeFormat , eTypeEnum }
typedef std::shared_ptr< TypeFormatImpl > SharedPointer
Public Member Functions
TypeFormatImpl_EnumType (ConstString type_name=ConstString(""), const TypeFormatImpl::Flags &flags=Flags())
~TypeFormatImpl_EnumType () override
ConstString GetTypeName ()
void SetTypeName (ConstString enum_type)
TypeFormatImpl::Type GetType () override
bool FormatObject (ValueObject *valobj, std::string &dest) const override
std::string GetDescription () override
Public Member Functions inherited from lldb_private::TypeFormatImpl
TypeFormatImpl (const Flags &flags=Flags())
virtual ~TypeFormatImpl ()
bool Cascades () const
bool SkipsPointers () const
bool SkipsReferences () const
bool NonCacheable () const
void SetCascades (bool value)
void SetSkipsPointers (bool value)
void SetSkipsReferences (bool value)
void SetNonCacheable (bool value)
uint32_t GetOptions ()
void SetOptions (uint32_t value)
uint32_t GetPtrMatchDepth ()
void SetPtrMatchDepth (uint32_t value)
uint32_t & GetRevision ()
Protected Attributes
ConstString m_enum_type
std::unordered_map< void *, CompilerType > m_types
Protected Attributes inherited from lldb_private::TypeFormatImpl
Flags m_flags
uint32_t m_my_revision = 0
uint32_t m_ptr_match_depth = 1
Private Member Functions
TypeFormatImpl_EnumType (const TypeFormatImpl_EnumType &)=delete
const TypeFormatImpl_EnumType & operator= (const TypeFormatImpl_EnumType &)=delete
Detailed Description
Definition at line 194 of file TypeFormat.h.
Member Typedef Documentation
SharedPointer
typedef std::shared_ptr<TypeFormatImpl_EnumType> lldb_private::TypeFormatImpl_EnumType::SharedPointer
Definition at line 199 of file TypeFormat.h.
Constructor & Destructor Documentation
TypeFormatImpl_EnumType() [1/2]
TypeFormatImpl_EnumType::TypeFormatImpl_EnumType (ConstString type_name = ConstString(""), const TypeFormatImpl::Flags & flags = Flags())
Definition at line 139 of file TypeFormat.cpp.
References m_enum_type, m_types, and lldb_private::TypeFormatImpl::TypeFormatImpl().
Referenced by operator=(), and TypeFormatImpl_EnumType().
~TypeFormatImpl_EnumType()
TypeFormatImpl_EnumType::~TypeFormatImpl_EnumType () override default
TypeFormatImpl_EnumType() [2/2]
lldb_private::TypeFormatImpl_EnumType::TypeFormatImpl_EnumType (const TypeFormatImpl_EnumType &) private delete
References TypeFormatImpl_EnumType().
Member Function Documentation
FormatObject()
bool TypeFormatImpl_EnumType::FormatObject (ValueObject * valobj, std::string & dest) const override virtual
Implements lldb_private::TypeFormatImpl.
Definition at line 145 of file TypeFormat.cpp.
References lldb_private::ValueObject::CanProvideValue(), lldb_private::CompilerType::DumpTypeValue(), lldb::eFormatEnum, lldb_private::TypeMap::Empty(), error(), lldb_private::ModuleList::FindTypes(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::DataExtractor::GetByteSize(), lldb_private::ValueObject::GetData(), lldb_private::ValueObject::GetExecutionContextRef(), lldb_private::ValueObject::GetProcessSP(), lldb_private::StreamString::GetString(), lldb_private::ValueObject::GetTargetSP(), lldb_private::TypeResults::GetTypeMap(), lldb_private::CompilerType::IsValid(), m_enum_type, m_types, and lldb_private::TypeMap::Types().
GetDescription()
std::string TypeFormatImpl_EnumType::GetDescription () override virtual
Implements lldb_private::TypeFormatImpl.
Definition at line 202 of file TypeFormat.cpp.
References lldb_private::TypeFormatImpl::Cascades(), lldb_private::StreamString::GetString(), m_enum_type, lldb_private::Stream::Printf(), lldb_private::TypeFormatImpl::SkipsPointers(), and lldb_private::TypeFormatImpl::SkipsReferences().
GetType()
TypeFormatImpl::Type lldb_private::TypeFormatImpl_EnumType::GetType () inline override virtual
Reimplemented from lldb_private::TypeFormatImpl.
Definition at line 207 of file TypeFormat.h.
References lldb_private::TypeFormatImpl::eTypeEnum.
GetTypeName()
ConstString lldb_private::TypeFormatImpl_EnumType::GetTypeName () inline
Definition at line 203 of file TypeFormat.h.
References m_enum_type.
operator=()
const TypeFormatImpl_EnumType & lldb_private::TypeFormatImpl_EnumType::operator= (const TypeFormatImpl_EnumType &) private delete
References TypeFormatImpl_EnumType().
SetTypeName()
void lldb_private::TypeFormatImpl_EnumType::SetTypeName (ConstString enum_type) inline
Definition at line 205 of file TypeFormat.h.
References m_enum_type.
Member Data Documentation
m_enum_type
ConstString lldb_private::TypeFormatImpl_EnumType::m_enum_type protected
Definition at line 216 of file TypeFormat.h.
Referenced by FormatObject(), GetDescription(), GetTypeName(), SetTypeName(), and TypeFormatImpl_EnumType().
m_types
std::unordered_map<void *, CompilerType> lldb_private::TypeFormatImpl_EnumType::m_types mutable protected
Definition at line 217 of file TypeFormat.h.
Referenced by FormatObject(), and TypeFormatImpl_EnumType().
The documentation for this class was generated from the following files:
TypeFormat.h
TypeFormat.cpp