LLDB: lldb_private::formatters::VectorIteratorSyntheticFrontEnd Class Reference
lldb_private::formatters::VectorIteratorSyntheticFrontEnd Class Reference
#include <VectorIterator.h>
Public Member Functions
VectorIteratorSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp, llvm::ArrayRef< ConstString > item_names)
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Attributes
ExecutionContextRef m_exe_ctx_ref
llvm::SmallVector< ConstString, 2 > m_item_names
lldb::ValueObjectSP m_item_sp
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
Definition at line 22 of file VectorIterator.h.
Constructor & Destructor Documentation
VectorIteratorSyntheticFrontEnd()
lldb_private::formatters::VectorIteratorSyntheticFrontEnd::VectorIteratorSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp, llvm::ArrayRef< ConstString > item_names)
Definition at line 188 of file LibStdcpp.cpp.
References m_exe_ctx_ref, m_item_names, m_item_sp, lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd(), and Update().
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > VectorIteratorSyntheticFrontEnd::CalculateNumChildren () override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 221 of file LibStdcpp.cpp.
GetChildAtIndex()
lldb::ValueObjectSP VectorIteratorSyntheticFrontEnd::GetChildAtIndex (uint32_t idx) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 226 of file LibStdcpp.cpp.
References m_item_sp.
GetIndexOfChildWithName()
llvm::Expected< size_t > VectorIteratorSyntheticFrontEnd::GetIndexOfChildWithName (ConstString name) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 233 of file LibStdcpp.cpp.
References lldb_private::ConstString::AsCString().
Update()
lldb::ChildCacheState VectorIteratorSyntheticFrontEnd::Update () override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 197 of file LibStdcpp.cpp.
References lldb_private::SyntheticChildrenFrontEnd::CreateValueObjectFromAddress(), lldb::eRefetch, lldb_private::Status::Fail(), lldb_private::formatters::GetChildMemberWithName(), lldb_private::SyntheticChildrenFrontEnd::m_backend, m_exe_ctx_ref, m_item_names, and m_item_sp.
Referenced by VectorIteratorSyntheticFrontEnd().
Member Data Documentation
m_exe_ctx_ref
ExecutionContextRef lldb_private::formatters::VectorIteratorSyntheticFrontEnd::m_exe_ctx_ref private
Definition at line 36 of file VectorIterator.h.
Referenced by Update(), and VectorIteratorSyntheticFrontEnd().
m_item_names
llvm::SmallVector<ConstString, 2> lldb_private::formatters::VectorIteratorSyntheticFrontEnd::m_item_names private
Definition at line 37 of file VectorIterator.h.
Referenced by Update(), and VectorIteratorSyntheticFrontEnd().
m_item_sp
lldb::ValueObjectSP lldb_private::formatters::VectorIteratorSyntheticFrontEnd::m_item_sp private
Definition at line 38 of file VectorIterator.h.
Referenced by GetChildAtIndex(), Update(), and VectorIteratorSyntheticFrontEnd().
The documentation for this class was generated from the following files:
VectorIterator.h
LibStdcpp.cpp