LLDB: lldb_private::HostProcessPosix Class Reference
lldb_private::HostProcessPosix Class Reference
#include <HostProcessPosix.h>
Public Member Functions
HostProcessPosix ()
HostProcessPosix (lldb::process_t process)
~HostProcessPosix () override
virtual Status Signal (int signo) const
Status Terminate () override
lldb::pid_t GetProcessId () const override
bool IsRunning () const override
llvm::Expected< HostThread > StartMonitoring (const Host::MonitorChildProcessCallback &callback) override
Public Member Functions inherited from lldb_private::HostNativeProcessBase
HostNativeProcessBase ()
HostNativeProcessBase (lldb::process_t process)
virtual ~HostNativeProcessBase ()=default
lldb::process_t GetSystemHandle () const
Static Public Member Functions
static Status Signal (lldb::process_t process, int signo)
Additional Inherited Members
Protected Attributes inherited from lldb_private::HostNativeProcessBase
lldb::process_t m_process
Detailed Description
Definition at line 20 of file HostProcessPosix.h.
Constructor & Destructor Documentation
HostProcessPosix() [1/2]
HostProcessPosix::HostProcessPosix ()
Definition at line 23 of file HostProcessPosix.cpp.
References lldb_private::HostNativeProcessBase::HostNativeProcessBase(), and kInvalidPosixProcess.
HostProcessPosix() [2/2]
HostProcessPosix::HostProcessPosix (lldb::process_t process)
Definition at line 26 of file HostProcessPosix.cpp.
References lldb_private::HostNativeProcessBase::HostNativeProcessBase().
~HostProcessPosix()
HostProcessPosix::~HostProcessPosix () override default
Member Function Documentation
GetProcessId()
lldb::pid_t HostProcessPosix::GetProcessId () const override virtual
Implements lldb_private::HostNativeProcessBase.
Definition at line 51 of file HostProcessPosix.cpp.
References lldb_private::HostNativeProcessBase::m_process.
IsRunning()
bool HostProcessPosix::IsRunning () const override virtual
Implements lldb_private::HostNativeProcessBase.
Definition at line 53 of file HostProcessPosix.cpp.
References error(), kInvalidPosixProcess, lldb_private::HostNativeProcessBase::m_process, and Signal().
Signal() [1/2]
Status HostProcessPosix::Signal (int signo) const virtual
Definition at line 31 of file HostProcessPosix.cpp.
References lldb_private::Status::FromErrorString(), kInvalidPosixProcess, lldb_private::HostNativeProcessBase::m_process, and Signal().
Referenced by IsRunning(), Signal(), and Terminate().
Signal() [2/2]
Status HostProcessPosix::Signal (lldb::process_t process, int signo) static
Definition at line 40 of file HostProcessPosix.cpp.
References error(), and lldb_private::Status::FromErrno().
StartMonitoring()
llvm::Expected< HostThread > HostProcessPosix::StartMonitoring (const Host::MonitorChildProcessCallback & callback) override virtual
Implements lldb_private::HostNativeProcessBase.
Definition at line 62 of file HostProcessPosix.cpp.
References lldb_private::HostNativeProcessBase::m_process, and lldb_private::Host::StartMonitoringChildProcess().
Terminate()
Status HostProcessPosix::Terminate () override virtual
Implements lldb_private::HostNativeProcessBase.
Definition at line 49 of file HostProcessPosix.cpp.
References SIGKILL, and Signal().
The documentation for this class was generated from the following files:
HostProcessPosix.h
HostProcessPosix.cpp