LLDB: lldb::SBTypeSummaryOptions Class Reference
lldb::SBTypeSummaryOptions Class Reference
#include <SBTypeSummary.h>
Public Member Functions
SBTypeSummaryOptions ()
SBTypeSummaryOptions (const lldb::SBTypeSummaryOptions &rhs)
~SBTypeSummaryOptions ()
operator bool () const
bool IsValid ()
lldb::LanguageType GetLanguage ()
lldb::TypeSummaryCapping GetCapping ()
void SetLanguage (lldb::LanguageType)
void SetCapping (lldb::TypeSummaryCapping)
Protected Member Functions
SBTypeSummaryOptions (const lldb_private::TypeSummaryOptions &lldb_object)
lldb_private::TypeSummaryOptions * operator-> ()
const lldb_private::TypeSummaryOptions * operator-> () const
lldb_private::TypeSummaryOptions * get ()
lldb_private::TypeSummaryOptions & ref ()
const lldb_private::TypeSummaryOptions & ref () const
Private Attributes
std::unique_ptr< lldb_private::TypeSummaryOptions > m_opaque_up
Friends
class SBValue
class SBTypeSummary
class lldb_private::python::SWIGBridge
Detailed Description
Definition at line 22 of file SBTypeSummary.h.
Constructor & Destructor Documentation
SBTypeSummaryOptions() [1/3]
SBTypeSummaryOptions::SBTypeSummaryOptions ()
Definition at line 21 of file SBTypeSummary.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb_private::python::SWIGBridge.
SBTypeSummaryOptions() [2/3]
SBTypeSummaryOptions::SBTypeSummaryOptions (const lldb::SBTypeSummaryOptions & rhs)
Definition at line 27 of file SBTypeSummary.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, and m_opaque_up.
~SBTypeSummaryOptions()
SBTypeSummaryOptions::~SBTypeSummaryOptions () default
References GetCapping(), GetLanguage(), IsValid(), SetCapping(), and SetLanguage().
SBTypeSummaryOptions() [3/3]
SBTypeSummaryOptions::SBTypeSummaryOptions (const lldb_private::TypeSummaryOptions & lldb_object) protected
Definition at line 97 of file SBTypeSummary.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Member Function Documentation
get()
lldb_private::TypeSummaryOptions * SBTypeSummaryOptions::get () protected
Definition at line 85 of file SBTypeSummary.cpp.
References m_opaque_up.
Referenced by lldb_private::python::SWIGBridge.
GetCapping()
lldb::TypeSummaryCapping SBTypeSummaryOptions::GetCapping ()
Definition at line 54 of file SBTypeSummary.cpp.
References lldb::eTypeSummaryCapped, IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBTypeSummaryOptions().
GetLanguage()
lldb::LanguageType SBTypeSummaryOptions::GetLanguage ()
Definition at line 46 of file SBTypeSummary.cpp.
References lldb::eLanguageTypeUnknown, IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBTypeSummaryOptions().
IsValid()
bool SBTypeSummaryOptions::IsValid ()
Definition at line 36 of file SBTypeSummary.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by GetCapping(), GetLanguage(), SetCapping(), SetLanguage(), and ~SBTypeSummaryOptions().
operator bool()
SBTypeSummaryOptions::operator bool () const explicit
Definition at line 40 of file SBTypeSummary.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
operator->() [1/2]
lldb_private::TypeSummaryOptions * SBTypeSummaryOptions::operator-> () protected
Definition at line 76 of file SBTypeSummary.cpp.
References m_opaque_up.
Referenced by lldb_private::python::SWIGBridge.
operator->() [2/2]
const lldb_private::TypeSummaryOptions * SBTypeSummaryOptions::operator-> () const protected
Definition at line 80 of file SBTypeSummary.cpp.
References m_opaque_up.
ref() [1/2]
lldb_private::TypeSummaryOptions & SBTypeSummaryOptions::ref () protected
Definition at line 89 of file SBTypeSummary.cpp.
References m_opaque_up.
Referenced by lldb::SBValue::GetSummary(), and lldb_private::python::SWIGBridge.
ref() [2/2]
const lldb_private::TypeSummaryOptions & SBTypeSummaryOptions::ref () const protected
Definition at line 93 of file SBTypeSummary.cpp.
References m_opaque_up.
SetCapping()
void SBTypeSummaryOptions::SetCapping (lldb::TypeSummaryCapping c)
Definition at line 69 of file SBTypeSummary.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBTypeSummaryOptions().
SetLanguage()
void SBTypeSummaryOptions::SetLanguage (lldb::LanguageType l)
Definition at line 62 of file SBTypeSummary.cpp.
References IsValid(), l, LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBTypeSummaryOptions().
Friends And Related Symbol Documentation
lldb_private::python::SWIGBridge
friend class lldb_private::python::SWIGBridge friend
Definition at line 47 of file SBTypeSummary.h.
References get(), operator->(), ref(), and SBTypeSummaryOptions().
SBTypeSummary
friend class SBTypeSummary friend
Definition at line 45 of file SBTypeSummary.h.
References SBTypeSummary.
Referenced by SBTypeSummary.
SBValue
friend class SBValue friend
Definition at line 44 of file SBTypeSummary.h.
References SBValue.
Referenced by SBValue.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::TypeSummaryOptions> lldb::SBTypeSummaryOptions::m_opaque_up private
Definition at line 62 of file SBTypeSummary.h.
Referenced by get(), GetCapping(), GetLanguage(), operator bool(), operator->(), operator->(), ref(), ref(), SBTypeSummaryOptions(), SBTypeSummaryOptions(), SBTypeSummaryOptions(), SetCapping(), and SetLanguage().
The documentation for this class was generated from the following files:
SBTypeSummary.h
SBTypeSummary.cpp