LLDB: lldb_private::dil::CastNode Class Reference
lldb_private::dil::CastNode Class Reference
#include <DILAST.h>
Public Member Functions
CastNode (uint32_t location, CompilerType type, ASTNodeUP operand, CastKind kind)
llvm::Expected< lldb::ValueObjectSP > Accept (Visitor *v) const override
CompilerType GetType () const
ASTNode & GetOperand () const
CastKind GetCastKind () const
Public Member Functions inherited from lldb_private::dil::ASTNode
ASTNode (uint32_t location, NodeKind kind)
virtual ~ASTNode ()=default
uint32_t GetLocation () const
NodeKind GetKind () const
Static Public Member Functions
static bool classof (const ASTNode &node)
Private Attributes
CompilerType m_type
ASTNodeUP m_operand
CastKind m_cast_kind
Detailed Description
Definition at line 258 of file DILAST.h.
Constructor & Destructor Documentation
CastNode()
lldb_private::dil::CastNode::CastNode (uint32_t location, CompilerType type, ASTNodeUP operand, CastKind kind) inline
Definition at line 260 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), lldb_private::dil::eCastNode, m_cast_kind, m_operand, and m_type.
Member Function Documentation
Accept()
llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::CastNode::Accept (Visitor * v) const override virtual
Implements lldb_private::dil::ASTNode.
Definition at line 54 of file DILAST.cpp.
References lldb_private::dil::Visitor::Visit().
classof()
bool lldb_private::dil::CastNode::classof (const ASTNode & node) inline static
Definition at line 271 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), lldb_private::dil::eCastNode, and lldb_private::dil::ASTNode::GetKind().
GetCastKind()
CastKind lldb_private::dil::CastNode::GetCastKind () const inline
Definition at line 269 of file DILAST.h.
References m_cast_kind.
GetOperand()
ASTNode & lldb_private::dil::CastNode::GetOperand () const inline
Definition at line 268 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), and m_operand.
Referenced by lldb_private::dil::Interpreter::Visit().
GetType()
CompilerType lldb_private::dil::CastNode::GetType () const inline
Definition at line 267 of file DILAST.h.
References m_type.
Referenced by lldb_private::dil::Interpreter::Visit().
Member Data Documentation
m_cast_kind
CastKind lldb_private::dil::CastNode::m_cast_kind private
Definition at line 278 of file DILAST.h.
Referenced by CastNode(), and GetCastKind().
m_operand
ASTNodeUP lldb_private::dil::CastNode::m_operand private
Definition at line 277 of file DILAST.h.
Referenced by CastNode(), and GetOperand().
m_type
CompilerType lldb_private::dil::CastNode::m_type private
Definition at line 276 of file DILAST.h.
Referenced by CastNode(), and GetType().
The documentation for this class was generated from the following files:
DILAST.h
DILAST.cpp