LLDB: lldb_private::ProcessStructReader Class Reference
lldb_private::ProcessStructReader Class Reference
#include <ProcessStructReader.h>
Classes
struct FieldImpl
Public Member Functions
ProcessStructReader (Process *process, lldb::addr_t base_addr, CompilerType struct_type)
template<typename RetType>
RetType GetField (llvm::StringRef name, RetType fail_value=RetType())
Protected Attributes
llvm::StringMap< FieldImpl > m_fields
DataExtractor m_data
lldb::ByteOrder m_byte_order
size_t m_addr_byte_size
Detailed Description
Definition at line 29 of file ProcessStructReader.h.
Constructor & Destructor Documentation
ProcessStructReader()
lldb_private::ProcessStructReader::ProcessStructReader (Process * process, lldb::addr_t base_addr, CompilerType struct_type) inline
Definition at line 43 of file ProcessStructReader.h.
References error(), lldb_private::Process::GetAddressByteSize(), lldb_private::Process::GetByteOrder(), lldb_private::CompilerType::GetByteSize(), lldb_private::CompilerType::GetFieldAtIndex(), lldb_private::GetLog(), lldb_private::CompilerType::GetNumFields(), LLDB_INVALID_ADDRESS, LLDB_LOG_ERROR, m_addr_byte_size, m_byte_order, m_data, m_fields, lldb_private::Process::ReadMemoryFromInferior(), and lldb_private::Target.
Member Function Documentation
GetField()
template<typename RetType> RetType lldb_private::ProcessStructReader::GetField (llvm::StringRef name, RetType fail_value = RetType()) inline
Definition at line 95 of file ProcessStructReader.h.
References m_data, and m_fields.
Referenced by SystemRuntimeMacOSX::ReadLibdispatchTSDIndexes().
Member Data Documentation
m_addr_byte_size
size_t lldb_private::ProcessStructReader::m_addr_byte_size protected
Definition at line 40 of file ProcessStructReader.h.
Referenced by ProcessStructReader().
m_byte_order
lldb::ByteOrder lldb_private::ProcessStructReader::m_byte_order protected
Definition at line 39 of file ProcessStructReader.h.
Referenced by ProcessStructReader().
m_data
DataExtractor lldb_private::ProcessStructReader::m_data protected
Definition at line 38 of file ProcessStructReader.h.
Referenced by GetField(), and ProcessStructReader().
m_fields
llvm::StringMap<FieldImpl> lldb_private::ProcessStructReader::m_fields protected
Definition at line 37 of file ProcessStructReader.h.
Referenced by GetField(), and ProcessStructReader().
The documentation for this class was generated from the following file:
ProcessStructReader.h