LLDB: lldb_private::TimeoutResumeAll Class Reference
lldb_private::TimeoutResumeAll Class Reference
#include <TimeoutResumeAll.h>
Public Member Functions
TimeoutResumeAll (Thread &thread)
void PushNewTimeout ()
void ResumeWithTimeout ()
Private Attributes
Thread & m_thread
ThreadPlanSingleThreadTimeout::TimeoutInfoSP m_timeout_info
Detailed Description
Definition at line 20 of file TimeoutResumeAll.h.
Constructor & Destructor Documentation
TimeoutResumeAll()
lldb_private::TimeoutResumeAll::TimeoutResumeAll (Thread & thread) inline
Definition at line 22 of file TimeoutResumeAll.h.
References m_thread, and m_timeout_info.
Referenced by lldb_private::ThreadPlanStepOverRange::ThreadPlanStepOverRange().
Member Function Documentation
PushNewTimeout()
void lldb_private::TimeoutResumeAll::PushNewTimeout () inline
Definition at line 27 of file TimeoutResumeAll.h.
References m_thread, m_timeout_info, and lldb_private::ThreadPlanSingleThreadTimeout::PushNewWithTimeout().
Referenced by lldb_private::ThreadPlanStepOverRange::DidPush().
ResumeWithTimeout()
void lldb_private::TimeoutResumeAll::ResumeWithTimeout () inline
Definition at line 31 of file TimeoutResumeAll.h.
References m_thread, m_timeout_info, and lldb_private::ThreadPlanSingleThreadTimeout::ResumeFromPrevState().
Referenced by lldb_private::ThreadPlanStepOverRange::DoWillResume().
Member Data Documentation
m_thread
Thread& lldb_private::TimeoutResumeAll::m_thread private
Definition at line 37 of file TimeoutResumeAll.h.
Referenced by PushNewTimeout(), ResumeWithTimeout(), and TimeoutResumeAll().
m_timeout_info
ThreadPlanSingleThreadTimeout::TimeoutInfoSP lldb_private::TimeoutResumeAll::m_timeout_info private
Definition at line 38 of file TimeoutResumeAll.h.
Referenced by PushNewTimeout(), ResumeWithTimeout(), and TimeoutResumeAll().
The documentation for this class was generated from the following file:
TimeoutResumeAll.h