LLDB: lldb_private::StopInfoThreadPlan Class Reference
lldb_private::StopInfoThreadPlan Class Reference
Public Member Functions
StopInfoThreadPlan (ThreadPlanSP &plan_sp, ValueObjectSP &return_valobj_sp, ExpressionVariableSP &expression_variable_sp)
~StopInfoThreadPlan () override=default
StopReason GetStopReason () const override
const char * GetDescription () override
ValueObjectSP GetReturnValueObject ()
ExpressionVariableSP GetExpressionVariable ()
Public Member Functions inherited from lldb_private::StopInfo
StopInfo (Thread &thread, uint64_t value)
virtual ~StopInfo ()=default
bool IsValid () const
void SetThread (const lldb::ThreadSP &thread_sp)
lldb::ThreadSP GetThread () const
uint64_t GetValue () const
virtual bool ShouldStopSynchronous (Event *event_ptr)
void OverrideShouldNotify (bool override_value)
virtual bool ShouldNotify (Event *event_ptr)
virtual void WillResume (lldb::StateType resume_state)
virtual void SetDescription (const char *desc_cstr)
virtual std::optional< uint32_t > GetSuggestedStackFrameIndex (bool inlined_stack)
This gives the StopInfo a chance to suggest a stack frame to select.
virtual bool IsValidForOperatingSystemThread (Thread &thread)
virtual bool WasContinueInterrupted (Thread &thread)
A Continue operation can result in a false stop event before any execution has happened.
virtual uint32_t GetStopReasonDataCount () const
virtual uint64_t GetStopReasonDataAtIndex (uint32_t idx)
void OverrideShouldStop (bool override_value)
bool GetOverrideShouldStop ()
bool GetOverriddenShouldStopValue ()
StructuredData::ObjectSP GetExtendedInfo ()
virtual bool ShouldShow () const
Returns true if this is a stop reason that should be shown to a user when viewing the thread with this stop info.
virtual bool ShouldSelect () const
Returns true if this is a stop reason that should cause a thread to be selected when stopping.
Protected Member Functions
bool ShouldStop (Event *event_ptr) override
Protected Member Functions inherited from lldb_private::StopInfo
virtual void PerformAction (Event *event_ptr)
virtual bool DoShouldNotify (Event *event_ptr)
bool HasTargetRunSinceMe ()
void MakeStopInfoValid ()
Private Attributes
ThreadPlanSP m_plan_sp
ValueObjectSP m_return_valobj_sp
ExpressionVariableSP m_expression_variable_sp
Additional Inherited Members
Static Public Member Functions inherited from lldb_private::StopInfo
static lldb::StopInfoSP CreateStopReasonWithBreakpointSiteID (Thread &thread, lldb::break_id_t break_id)
static lldb::StopInfoSP CreateStopReasonWithBreakpointSiteID (Thread &thread, lldb::break_id_t break_id, bool should_stop)
static lldb::StopInfoSP CreateStopReasonWithWatchpointID (Thread &thread, lldb::break_id_t watch_id, bool silently_continue=false)
static lldb::StopInfoSP CreateStopReasonWithSignal (Thread &thread, int signo, const char *description=nullptr, std::optional< int > code=std::nullopt)
static lldb::StopInfoSP CreateStopReasonWithInterrupt (Thread &thread, int signo, const char *description)
static lldb::StopInfoSP CreateStopReasonToTrace (Thread &thread)
static lldb::StopInfoSP CreateStopReasonWithPlan (lldb::ThreadPlanSP &plan, lldb::ValueObjectSP return_valobj_sp, lldb::ExpressionVariableSP expression_variable_sp)
static lldb::StopInfoSP CreateStopReasonWithException (Thread &thread, const char *description)
static lldb::StopInfoSP CreateStopReasonWithExec (Thread &thread)
static lldb::StopInfoSP CreateStopReasonProcessorTrace (Thread &thread, const char *description)
static lldb::StopInfoSP CreateStopReasonHistoryBoundary (Thread &thread, const char *description)
static lldb::StopInfoSP CreateStopReasonFork (Thread &thread, lldb::pid_t child_pid, lldb::tid_t child_tid)
static lldb::StopInfoSP CreateStopReasonVFork (Thread &thread, lldb::pid_t child_pid, lldb::tid_t child_tid)
static lldb::StopInfoSP CreateStopReasonVForkDone (Thread &thread)
static lldb::ValueObjectSP GetReturnValueObject (lldb::StopInfoSP &stop_info_sp)
static lldb::ExpressionVariableSP GetExpressionVariable (lldb::StopInfoSP &stop_info_sp)
static lldb::ValueObjectSP GetCrashingDereference (lldb::StopInfoSP &stop_info_sp, lldb::addr_t *crashing_address=nullptr)
Protected Attributes inherited from lldb_private::StopInfo
lldb::ThreadWP m_thread_wp
uint32_t m_stop_id
uint32_t m_resume_id
uint64_t m_value
std::string m_description
LazyBool m_override_should_notify
LazyBool m_override_should_stop
StructuredData::ObjectSP m_extended_info
Detailed Description
Definition at line 1399 of file StopInfo.cpp.
Constructor & Destructor Documentation
StopInfoThreadPlan()
lldb_private::StopInfoThreadPlan::StopInfoThreadPlan (ThreadPlanSP & plan_sp, ValueObjectSP & return_valobj_sp, ExpressionVariableSP & expression_variable_sp) inline
Definition at line 1401 of file StopInfo.cpp.
References lldb_private::StopInfo::GetThread(), LLDB_INVALID_UID, m_expression_variable_sp, m_plan_sp, m_return_valobj_sp, and lldb_private::StopInfo::StopInfo().
~StopInfoThreadPlan()
lldb_private::StopInfoThreadPlan::~StopInfoThreadPlan () override default
Member Function Documentation
GetDescription()
const char * lldb_private::StopInfoThreadPlan::GetDescription () inline override virtual
Reimplemented from lldb_private::StopInfo.
Definition at line 1411 of file StopInfo.cpp.
References lldb::eDescriptionLevelBrief, lldb_private::StreamString::GetString(), lldb_private::StopInfo::m_description, and m_plan_sp.
GetExpressionVariable()
ExpressionVariableSP lldb_private::StopInfoThreadPlan::GetExpressionVariable () inline
Definition at line 1422 of file StopInfo.cpp.
References m_expression_variable_sp.
Referenced by lldb_private::StopInfo::GetExpressionVariable().
GetReturnValueObject()
ValueObjectSP lldb_private::StopInfoThreadPlan::GetReturnValueObject () inline
Definition at line 1420 of file StopInfo.cpp.
References m_return_valobj_sp.
Referenced by lldb_private::StopInfo::GetReturnValueObject().
GetStopReason()
StopReason lldb_private::StopInfoThreadPlan::GetStopReason () const inline override virtual
Implements lldb_private::StopInfo.
Definition at line 1409 of file StopInfo.cpp.
References lldb::eStopReasonPlanComplete.
ShouldStop()
bool lldb_private::StopInfoThreadPlan::ShouldStop (Event * event_ptr) inline override protected virtual
Reimplemented from lldb_private::StopInfo.
Definition at line 1427 of file StopInfo.cpp.
References m_plan_sp, and lldb_private::StopInfo::ShouldStop().
Member Data Documentation
m_expression_variable_sp
ExpressionVariableSP lldb_private::StopInfoThreadPlan::m_expression_variable_sp private
Definition at line 1437 of file StopInfo.cpp.
Referenced by GetExpressionVariable(), and StopInfoThreadPlan().
m_plan_sp
ThreadPlanSP lldb_private::StopInfoThreadPlan::m_plan_sp private
Definition at line 1435 of file StopInfo.cpp.
Referenced by GetDescription(), ShouldStop(), and StopInfoThreadPlan().
m_return_valobj_sp
ValueObjectSP lldb_private::StopInfoThreadPlan::m_return_valobj_sp private
Definition at line 1436 of file StopInfo.cpp.
Referenced by GetReturnValueObject(), and StopInfoThreadPlan().
The documentation for this class was generated from the following file:
StopInfo.cpp