LLDB: lldb_private::RegisterCheckpoint Class Reference
lldb_private::RegisterCheckpoint Class Reference
#include <RegisterCheckpoint.h>
Public Types
enum class Reason { eExpression , eDataBackup }
Public Member Functions
RegisterCheckpoint (Reason reason)
~RegisterCheckpoint ()=default
lldb::WritableDataBufferSP & GetData ()
const lldb::WritableDataBufferSP & GetData () const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Protected Member Functions
RegisterCheckpoint (const RegisterCheckpoint &)=delete
const RegisterCheckpoint & operator= (const RegisterCheckpoint &)=delete
Protected Attributes
lldb::WritableDataBufferSP m_data_sp
Reason m_reason
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Detailed Description
Definition at line 21 of file RegisterCheckpoint.h.
Member Enumeration Documentation
Reason
enum class lldb_private::RegisterCheckpoint::Reason strong
Enumerator
eExpression
eDataBackup
Definition at line 23 of file RegisterCheckpoint.h.
Constructor & Destructor Documentation
RegisterCheckpoint() [1/2]
lldb_private::RegisterCheckpoint::RegisterCheckpoint (Reason reason) inline
Definition at line 34 of file RegisterCheckpoint.h.
References m_reason, and lldb_private::UserID::UserID().
Referenced by operator=(), and RegisterCheckpoint().
~RegisterCheckpoint()
lldb_private::RegisterCheckpoint::~RegisterCheckpoint () default
RegisterCheckpoint() [2/2]
lldb_private::RegisterCheckpoint::RegisterCheckpoint (const RegisterCheckpoint &) protected delete
References RegisterCheckpoint().
Member Function Documentation
GetData() [1/2]
lldb::WritableDataBufferSP & lldb_private::RegisterCheckpoint::GetData () inline
Definition at line 38 of file RegisterCheckpoint.h.
References m_data_sp.
Referenced by lldb_private::process_gdb_remote::GDBRemoteRegisterContext::ReadAllRegisterValues(), lldb_private::RegisterContext::ReadAllRegisterValues(), lldb_private::process_gdb_remote::GDBRemoteRegisterContext::WriteAllRegisterValues(), and lldb_private::RegisterContext::WriteAllRegisterValues().
GetData() [2/2]
const lldb::WritableDataBufferSP & lldb_private::RegisterCheckpoint::GetData () const inline
Definition at line 40 of file RegisterCheckpoint.h.
References m_data_sp.
operator=()
const RegisterCheckpoint & lldb_private::RegisterCheckpoint::operator= (const RegisterCheckpoint &) protected delete
References RegisterCheckpoint().
Member Data Documentation
m_data_sp
lldb::WritableDataBufferSP lldb_private::RegisterCheckpoint::m_data_sp protected
Definition at line 43 of file RegisterCheckpoint.h.
Referenced by GetData(), and GetData().
m_reason
Reason lldb_private::RegisterCheckpoint::m_reason protected
Definition at line 44 of file RegisterCheckpoint.h.
Referenced by RegisterCheckpoint().
The documentation for this class was generated from the following file:
RegisterCheckpoint.h