LLDB: lldb_private::DataVisualization::Categories Class Reference
lldb_private::DataVisualization::Categories Class Reference
#include <DataVisualization.h>
Static Public Member Functions
static bool GetCategory (ConstString category, lldb::TypeCategoryImplSP &entry, bool allow_create=true)
static bool GetCategory (lldb::LanguageType language, lldb::TypeCategoryImplSP &entry)
static void Add (ConstString category)
static bool Delete (ConstString category)
static void Clear ()
static void Clear (ConstString category)
static void Enable (ConstString category, TypeCategoryMap::Position=TypeCategoryMap::Default)
static void Enable (lldb::LanguageType lang_type)
static void Disable (ConstString category)
static void Disable (lldb::LanguageType lang_type)
static void Enable (const lldb::TypeCategoryImplSP &category, TypeCategoryMap::Position=TypeCategoryMap::Default)
static void Disable (const lldb::TypeCategoryImplSP &category)
static void EnableStar ()
static void DisableStar ()
static void ForEach (TypeCategoryMap::ForEachCallback callback)
static uint32_t GetCount ()
static lldb::TypeCategoryImplSP GetCategoryAtIndex (size_t)
Detailed Description
Definition at line 79 of file DataVisualization.h.
Member Function Documentation
Add()
void DataVisualization::Categories::Add (ConstString category) static
Definition at line 92 of file DataVisualization.cpp.
References lldb_private::FormatManager::GetCategory(), and GetFormatManager().
Clear() [1/2]
void DataVisualization::Categories::Clear () static
Definition at line 101 of file DataVisualization.cpp.
References lldb_private::FormatManager::ClearCategories(), and GetFormatManager().
Clear() [2/2]
void DataVisualization::Categories::Clear (ConstString category) static
Definition at line 105 of file DataVisualization.cpp.
References lldb_private::eFormatCategoryItemSummary, lldb_private::FormatManager::GetCategory(), and GetFormatManager().
Delete()
bool DataVisualization::Categories::Delete (ConstString category) static
Definition at line 96 of file DataVisualization.cpp.
References lldb_private::FormatManager::DeleteCategory(), lldb_private::FormatManager::DisableCategory(), and GetFormatManager().
Referenced by lldb::SBDebugger::DeleteCategory().
Disable() [1/3]
void DataVisualization::Categories::Disable (const lldb::TypeCategoryImplSP & category) static
Definition at line 142 of file DataVisualization.cpp.
References lldb_private::FormatManager::DisableCategory(), and GetFormatManager().
Disable() [2/3]
void DataVisualization::Categories::Disable (ConstString category) static
Definition at line 122 of file DataVisualization.cpp.
References lldb_private::FormatManager::DisableCategory(), GetCategory(), and GetFormatManager().
Referenced by lldb::SBTypeCategory::SetEnabled().
Disable() [3/3]
void DataVisualization::Categories::Disable (lldb::LanguageType lang_type) static
Definition at line 127 of file DataVisualization.cpp.
References GetFormatManager().
DisableStar()
void DataVisualization::Categories::DisableStar () static
Definition at line 152 of file DataVisualization.cpp.
References lldb_private::FormatManager::DisableAllCategories(), and GetFormatManager().
Enable() [1/3]
void DataVisualization::Categories::Enable (const lldb::TypeCategoryImplSP & category, TypeCategoryMap::Position pos = TypeCategoryMap::Default) static
Definition at line 133 of file DataVisualization.cpp.
References lldb_private::FormatManager::DisableCategory(), lldb_private::FormatManager::EnableCategory(), and GetFormatManager().
Enable() [2/3]
void DataVisualization::Categories::Enable (ConstString category, TypeCategoryMap::Position pos = TypeCategoryMap::Default) static
Definition at line 109 of file DataVisualization.cpp.
References lldb_private::FormatManager::DisableCategory(), lldb_private::FormatManager::EnableCategory(), GetCategory(), and GetFormatManager().
Referenced by CommandObjectTypeCategoryEnable::CommandObjectTypeCategoryEnable(), and lldb::SBTypeCategory::SetEnabled().
Enable() [3/3]
void DataVisualization::Categories::Enable (lldb::LanguageType lang_type) static
Definition at line 116 of file DataVisualization.cpp.
References GetFormatManager().
EnableStar()
void DataVisualization::Categories::EnableStar () static
Definition at line 148 of file DataVisualization.cpp.
References lldb_private::FormatManager::EnableAllCategories(), and GetFormatManager().
ForEach()
void DataVisualization::Categories::ForEach (TypeCategoryMap::ForEachCallback callback) static
Definition at line 156 of file DataVisualization.cpp.
References lldb_private::FormatManager::ForEachCategory(), and GetFormatManager().
Referenced by CommandObjectTypeFormatterClear::DoExecute(), CommandObjectTypeFormatterDelete::DoExecute(), CommandObjectTypeFormatterList< FormatterType >::DoExecute(), CommandObjectTypeFormatterDelete::HandleArgumentCompletion(), and lldb_private::CommandCompletions::TypeCategoryNames().
GetCategory() [1/2]
bool DataVisualization::Categories::GetCategory (ConstString category, lldb::TypeCategoryImplSP & entry, bool allow_create = true) static
Definition at line 77 of file DataVisualization.cpp.
References lldb_private::FormatManager::GetCategory(), and GetFormatManager().
Referenced by CommandObjectTypeCategoryEnable::CommandObjectTypeCategoryEnable(), lldb::SBDebugger::CreateCategory(), Disable(), CommandObjectTypeFormatterClear::DoExecute(), CommandObjectTypeFormatterDelete::DoExecute(), CommandObjectTypeFormatterList< FormatterType >::DoExecute(), Enable(), lldb_private::ForEachFormatterInModule(), CommandObjectTypeSummaryClear::FormatterSpecificDeletion(), lldb::SBDebugger::GetCategory(), lldb::SBDebugger::GetCategory(), lldb_private::CPlusPlusLanguage::GetFormatters(), lldb_private::ObjCLanguage::GetFormatters(), CommandObjectTypeSynthAdd::IOHandlerInputComplete(), lldb_private::LoadFormattersForModule(), lldb_private::LoadTypeSummariesForModule(), and lldb::SBTypeCategory::SBTypeCategory().
GetCategory() [2/2]
bool DataVisualization::Categories::GetCategory (lldb::LanguageType language, lldb::TypeCategoryImplSP & entry) static
Definition at line 84 of file DataVisualization.cpp.
References GetFormatManager().
GetCategoryAtIndex()
lldb::TypeCategoryImplSP DataVisualization::Categories::GetCategoryAtIndex (size_t index) static
Definition at line 166 of file DataVisualization.cpp.
References lldb_private::FormatManager::GetCategoryAtIndex(), and GetFormatManager().
Referenced by lldb::SBDebugger::GetCategoryAtIndex().
GetCount()
uint32_t DataVisualization::Categories::GetCount () static
Definition at line 161 of file DataVisualization.cpp.
References lldb_private::FormatManager::GetCategoriesCount(), and GetFormatManager().
Referenced by lldb::SBDebugger::GetNumCategories().
The documentation for this class was generated from the following files:
DataVisualization.h
DataVisualization.cpp