LLDB: DynamicLoaderHexagonDYLD Class Reference
DynamicLoaderHexagonDYLD Class Reference
#include <DynamicLoaderHexagonDYLD.h>
Public Member Functions
DynamicLoaderHexagonDYLD (lldb_private::Process *process)
~DynamicLoaderHexagonDYLD () override
void DidAttach () override
Called after attaching a process.
void DidLaunch () override
Called after launching a process.
lldb::ThreadPlanSP GetStepThroughTrampolinePlan (lldb_private::Thread &thread, bool stop_others) override
Provides a plan to step through the dynamic loader trampoline for the current state of thread.
lldb_private::Status CanLoadImage () override
Ask if it is ok to try and load or unload an shared library (image).
lldb::addr_t GetThreadLocalData (const lldb::ModuleSP module, const lldb::ThreadSP thread, lldb::addr_t tls_file_addr) override
Retrieves the per-module TLS block for a given thread.
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::DynamicLoader
DynamicLoader (Process *process)
Construct with a process.
virtual bool ProcessDidExec ()
Helper function that can be used to detect when a process has called exec and is now a new and different process.
bool GetStopWhenImagesChange () const
Get whether the process should stop when images change.
void SetStopWhenImagesChange (bool stop)
Set whether the process should stop when images change.
virtual void FindEquivalentSymbols (const Symbol *original_symbol, ModuleList &module_list, SymbolContextList &equivalent_symbols)
Some dynamic loaders provide features where there are a group of symbols "equivalent to" a given symbol one of which will be chosen when the symbol is bound.
virtual bool AlwaysRelyOnEHUnwindInfo (SymbolContext &sym_ctx)
Ask if the eh_frame information for the given SymbolContext should be relied on even when it's the first frame in a stack unwind.
virtual lldb::ModuleSP LoadModuleAtAddress (const lldb_private::FileSpec &file, lldb::addr_t link_map_addr, lldb::addr_t base_addr, bool base_addr_is_offset)
Locates or creates a module given by file and updates/loads the resulting module at the virtual base address base_addr.
virtual bool GetSharedCacheInformation (lldb::addr_t &base_address, UUID &uuid, LazyBool &using_shared_cache, LazyBool &private_shared_cache, lldb_private::FileSpec &shared_cache_path)
Get information about the shared cache for a process, if possible.
virtual bool IsFullyInitialized ()
Return whether the dynamic loader is fully initialized and it's safe to call its APIs.
virtual std::optional< lldb_private::Address > GetStartAddress ()
Return the start address in the dynamic loader module.
virtual void CalculateDynamicSaveCoreRanges (lldb_private::Process &process, std::vector< lldb_private::MemoryRegionInfo > &ranges, llvm::function_ref< bool(const lldb_private::Thread &)> save_thread_predicate)
Returns a list of memory ranges that should be saved in the core file, specific for this dynamic loader.
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static lldb_private::DynamicLoader * CreateInstance (lldb_private::Process *process, bool force)
Static Public Member Functions inherited from lldb_private::DynamicLoader
static DynamicLoader * FindPlugin (Process *process, llvm::StringRef plugin_name)
Find a dynamic loader plugin for a given process.
static lldb::ModuleSP LoadBinaryWithUUIDAndAddress (Process *process, llvm::StringRef name, UUID uuid, lldb::addr_t value, bool value_is_offset, bool force_symbol_search, bool notify, bool set_address_in_target, bool allow_memory_image_last_resort)
Find/load a binary into lldb given a UUID and the address where it is loaded in memory, or a slide to be applied to the file address.
Protected Member Functions
bool SetRendezvousBreakpoint ()
Enables a breakpoint on a function called by the runtime linker each time a module is loaded or unloaded.
void RefreshModules ()
Helper method for RendezvousBreakpointHit.
void UpdateLoadedSections (lldb::ModuleSP module, lldb::addr_t link_map_addr, lldb::addr_t base_addr, bool base_addr_is_offset) override
Updates the load address of every allocatable section in module.
void UnloadSections (const lldb::ModuleSP module) override
Removes the loaded sections from the target in module.
void LoadAllCurrentModules ()
Helper for the entry breakpoint callback.
lldb::addr_t ComputeLoadOffset ()
Computes a value for m_load_offset returning the computed address on success and LLDB_INVALID_ADDRESS on failure.
lldb::addr_t GetEntryPoint ()
Computes a value for m_entry_point returning the computed address on success and LLDB_INVALID_ADDRESS on failure.
lldb::ModuleSP GetTargetExecutable ()
Checks to see if the target module has changed, updates the target accordingly and returns the target executable module.
lldb::addr_t FindRendezvousBreakpointAddress ()
return the address of the Rendezvous breakpoint
Protected Member Functions inherited from lldb_private::DynamicLoader
lldb::ModuleSP FindModuleViaTarget (const FileSpec &file)
Find a module in the target that matches the given file.
lldb::ModuleSP GetTargetExecutable ()
Checks to see if the target module has changed, updates the target accordingly and returns the target executable module.
void UpdateLoadedSectionsCommon (lldb::ModuleSP module, lldb::addr_t base_addr, bool base_addr_is_offset)
void UnloadSectionsCommon (const lldb::ModuleSP module)
const lldb_private::SectionList * GetSectionListFromModule (const lldb::ModuleSP module) const
int64_t ReadUnsignedIntWithSizeInBytes (lldb::addr_t addr, int size_in_bytes)
lldb::addr_t ReadPointer (lldb::addr_t addr)
void LoadOperatingSystemPlugin (bool flush)
Static Protected Member Functions
static bool RendezvousBreakpointHit (void *baton, lldb_private::StoppointCallbackContext *context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id)
Callback routine which updates the current list of loaded modules based on the information supplied by the runtime linker.
static bool EntryBreakpointHit (void *baton, lldb_private::StoppointCallbackContext *context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id)
Callback routine invoked when we hit the breakpoint on process entry.
Protected Attributes
HexagonDYLDRendezvous m_rendezvous
Runtime linker rendezvous structure.
lldb::addr_t m_load_offset
Virtual load address of the inferior process.
lldb::addr_t m_entry_point
Virtual entry address of the inferior process.
lldb::break_id_t m_dyld_bid
Rendezvous breakpoint.
std::map< lldb::ModuleWP, lldb::addr_t, std::owner_less< lldb::ModuleWP > > m_loaded_modules
Loaded module list. (link map for each module)
Protected Attributes inherited from lldb_private::DynamicLoader
Process * m_process
The process that this dynamic loader plug-in is tracking.
Private Member Functions
const lldb_private::SectionList * GetSectionListFromModule (const lldb::ModuleSP module) const
Detailed Description
Definition at line 17 of file DynamicLoaderHexagonDYLD.h.
Constructor & Destructor Documentation
DynamicLoaderHexagonDYLD()
DynamicLoaderHexagonDYLD::DynamicLoaderHexagonDYLD (lldb_private::Process * process)
Definition at line 102 of file DynamicLoaderHexagonDYLD.cpp.
References lldb_private::DynamicLoader::DynamicLoader(), LLDB_INVALID_ADDRESS, LLDB_INVALID_BREAK_ID, m_dyld_bid, m_entry_point, m_load_offset, and m_rendezvous.
Referenced by CreateInstance(), and RendezvousBreakpointHit().
~DynamicLoaderHexagonDYLD()
DynamicLoaderHexagonDYLD::~DynamicLoaderHexagonDYLD () override
Definition at line 107 of file DynamicLoaderHexagonDYLD.cpp.
References LLDB_INVALID_BREAK_ID, m_dyld_bid, and lldb_private::DynamicLoader::m_process.
Member Function Documentation
CanLoadImage()
Status DynamicLoaderHexagonDYLD::CanLoadImage () override virtual
Ask if it is ok to try and load or unload an shared library (image).
The dynamic loader often knows when it would be ok to try and load or unload a shared library. This function call allows the dynamic loader plug-ins to check any current dyld state to make sure it is an ok time to load a shared library.
Returns
true if it is currently ok to try and load a shared library into the process, false otherwise.
Implements lldb_private::DynamicLoader.
Definition at line 205 of file DynamicLoaderHexagonDYLD.cpp.
References lldb_private::Status.
ComputeLoadOffset()
addr_t DynamicLoaderHexagonDYLD::ComputeLoadOffset () protected
Computes a value for m_load_offset returning the computed address on success and LLDB_INVALID_ADDRESS on failure.
Definition at line 489 of file DynamicLoaderHexagonDYLD.cpp.
Referenced by DidAttach().
CreateInstance()
DynamicLoader * DynamicLoaderHexagonDYLD::CreateInstance (lldb_private::Process * process, bool force) static
Definition at line 87 of file DynamicLoaderHexagonDYLD.cpp.
References lldb_private::DynamicLoader::DynamicLoader(), DynamicLoaderHexagonDYLD(), lldb_private::Target::GetArchitecture(), lldb_private::Process::GetTarget(), and lldb_private::ArchSpec::GetTriple().
Referenced by Initialize().
DidAttach()
void DynamicLoaderHexagonDYLD::DidAttach () override virtual
Called after attaching a process.
Allow DynamicLoader plug-ins to execute some code after attaching to a process.
Implements lldb_private::DynamicLoader.
Definition at line 114 of file DynamicLoaderHexagonDYLD.cpp.
References lldb_private::ModuleList::Append(), ComputeLoadOffset(), GetTargetExecutable(), LLDB_INVALID_ADDRESS, LoadAllCurrentModules(), lldb_private::DynamicLoader::m_process, SetRendezvousBreakpoint(), and UpdateLoadedSections().
DidLaunch()
void DynamicLoaderHexagonDYLD::DidLaunch () override virtual
Called after launching a process.
Allow DynamicLoader plug-ins to execute some code after the process has stopped for the first time on launch.
Implements lldb_private::DynamicLoader.
Definition at line 159 of file DynamicLoaderHexagonDYLD.cpp.
EntryBreakpointHit()
bool DynamicLoaderHexagonDYLD::EntryBreakpointHit (void * baton, lldb_private::StoppointCallbackContext * context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id) static protected
Callback routine invoked when we hit the breakpoint on process entry.
This routine is responsible for resolving the load addresses of all dependent modules required by the inferior and setting up the rendezvous breakpoint.
FindRendezvousBreakpointAddress()
lldb::addr_t DynamicLoaderHexagonDYLD::FindRendezvousBreakpointAddress () protected
return the address of the Rendezvous breakpoint
GetEntryPoint()
addr_t DynamicLoaderHexagonDYLD::GetEntryPoint () protected
Computes a value for m_entry_point returning the computed address on success and LLDB_INVALID_ADDRESS on failure.
Definition at line 506 of file DynamicLoaderHexagonDYLD.cpp.
References lldb_private::Address::GetFileAddress(), LLDB_INVALID_ADDRESS, m_entry_point, and lldb_private::DynamicLoader::m_process.
GetPluginDescriptionStatic()
llvm::StringRef DynamicLoaderHexagonDYLD::GetPluginDescriptionStatic () static
Definition at line 82 of file DynamicLoaderHexagonDYLD.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef DynamicLoaderHexagonDYLD::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 50 of file DynamicLoaderHexagonDYLD.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef DynamicLoaderHexagonDYLD::GetPluginNameStatic () inline static
Definition at line 27 of file DynamicLoaderHexagonDYLD.h.
Referenced by GetPluginName(), and Initialize().
GetSectionListFromModule()
const SectionList * DynamicLoaderHexagonDYLD::GetSectionListFromModule (const lldb::ModuleSP module) const private
Definition at line 527 of file DynamicLoaderHexagonDYLD.cpp.
References lldb_private::ObjectFile::GetSectionList().
Referenced by UnloadSections(), and UpdateLoadedSections().
GetStepThroughTrampolinePlan()
ThreadPlanSP DynamicLoaderHexagonDYLD::GetStepThroughTrampolinePlan (lldb_private::Thread & thread, bool stop_others) override virtual
Provides a plan to step through the dynamic loader trampoline for the current state of thread.
Parameters
[in] stop_others Whether the plan should be set to stop other threads.
Returns
A pointer to the plan (caller owned) or NULL if we are not at such a trampoline.
Implements lldb_private::DynamicLoader.
Definition at line 402 of file DynamicLoaderHexagonDYLD.cpp.
References lldb_private::Mangled::ePreferMangled, lldb::eSymbolTypeCode, lldb_private::ModuleList::FindSymbolsWithNameAndType(), lldb_private::SymbolContext::GetFunctionOrSymbolAddress(), lldb_private::Target::GetImages(), lldb_private::Address::GetLoadAddress(), lldb_private::Symbol::GetMangled(), lldb_private::Mangled::GetName(), lldb_private::SymbolContextList::GetSize(), lldb_private::StackFrame::GetSymbolContext(), lldb_private::Symbol::IsTrampoline(), LLDB_INVALID_ADDRESS, and lldb_private::SymbolContext::symbol.
GetTargetExecutable()
ModuleSP DynamicLoaderHexagonDYLD::GetTargetExecutable () protected
Checks to see if the target module has changed, updates the target accordingly and returns the target executable module.
Definition at line 163 of file DynamicLoaderHexagonDYLD.cpp.
References lldb_private::eLoadDependentsNo, lldb_private::Target::GetExecutableModule(), lldb_private::Target::GetExecutableModulePointer(), lldb_private::Target::GetOrCreateModule(), lldb_private::FileSystem::Instance(), lldb_private::DynamicLoader::m_process, lldb_private::Module, and lldb_private::Target::SetExecutableModule().
Referenced by DidAttach(), and LoadAllCurrentModules().
GetThreadLocalData()
lldb::addr_t DynamicLoaderHexagonDYLD::GetThreadLocalData (const lldb::ModuleSP module, const lldb::ThreadSP thread, lldb::addr_t tls_file_addr) override virtual
Retrieves the per-module TLS block for a given thread.
Parameters
[in] module The module to query TLS data for.
[in] thread The specific thread to query TLS data for.
Returns
If the given thread has TLS data allocated for the module, the address of the TLS block. Otherwise LLDB_INVALID_ADDRESS is returned.
Reimplemented from lldb_private::DynamicLoader.
Definition at line 550 of file DynamicLoaderHexagonDYLD.cpp.
References lldb_private::ConstString::AsCString(), HexagonDYLDRendezvous::ThreadInfo::dtv_offset, HexagonDYLDRendezvous::ThreadInfo::dtv_slot_size, lldb_private::DynamicLoader, lldb_private::GetLog(), lldb_private::Module::GetObjectName(), LLDB_INVALID_ADDRESS, LLDB_LOGF, m_loaded_modules, lldb_private::DynamicLoader::m_process, m_rendezvous, HexagonDYLDRendezvous::ThreadInfo::modid_offset, ReadInt(), lldb_private::DynamicLoader::ReadPointer(), HexagonDYLDRendezvous::ThreadInfo::tls_offset, and HexagonDYLDRendezvous::ThreadInfo::valid.
Initialize()
void DynamicLoaderHexagonDYLD::Initialize () static
Definition at line 75 of file DynamicLoaderHexagonDYLD.cpp.
References CreateInstance(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
LoadAllCurrentModules()
void DynamicLoaderHexagonDYLD::LoadAllCurrentModules () protected
Helper for the entry breakpoint callback.
Resolves the load addresses of all dependent modules.
Definition at line 449 of file DynamicLoaderHexagonDYLD.cpp.
References lldb_private::ModuleList::Append(), lldb_private::DynamicLoader, lldb_private::GetLog(), GetTargetExecutable(), LLDB_LOGF, lldb_private::DynamicLoader::LoadModuleAtAddress(), m_loaded_modules, lldb_private::DynamicLoader::m_process, and m_rendezvous.
Referenced by DidAttach().
RefreshModules()
void DynamicLoaderHexagonDYLD::RefreshModules () protected
Helper method for RendezvousBreakpointHit.
Updates LLDB's current set of loaded modules.
Definition at line 340 of file DynamicLoaderHexagonDYLD.cpp.
References lldb_private::ModuleList::Append(), lldb_private::ModuleList::AppendIfNeeded(), lldb_private::DynamicLoader, lldb_private::ModuleList::FindFirstModule(), lldb_private::GetLog(), lldb_private::FileSystem::Instance(), LLDB_LOGF, lldb_private::DynamicLoader::LoadModuleAtAddress(), lldb_private::DynamicLoader::m_process, m_rendezvous, lldb_private::ModuleList::Remove(), lldb_private::FileSystem::Resolve(), and UnloadSections().
Referenced by RendezvousBreakpointHit().
RendezvousBreakpointHit()
bool DynamicLoaderHexagonDYLD::RendezvousBreakpointHit (void * baton, lldb_private::StoppointCallbackContext * context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id) static protected
Callback routine which updates the current list of loaded modules based on the information supplied by the runtime linker.
Definition at line 305 of file DynamicLoaderHexagonDYLD.cpp.
References lldb_private::DynamicLoader, DynamicLoaderHexagonDYLD(), findSymbolAddress(), lldb_private::GetLog(), lldb_private::DynamicLoader::GetStopWhenImagesChange(), HexagonDYLDRendezvous::IsValid(), LLDB_INVALID_ADDRESS, LLDB_LOGF, lldb_private::DynamicLoader::m_process, m_rendezvous, RefreshModules(), and HexagonDYLDRendezvous::SetRendezvousAddress().
Referenced by SetRendezvousBreakpoint().
SetRendezvousBreakpoint()
bool DynamicLoaderHexagonDYLD::SetRendezvousBreakpoint () protected
Enables a breakpoint on a function called by the runtime linker each time a module is loaded or unloaded.
Definition at line 257 of file DynamicLoaderHexagonDYLD.cpp.
References lldb_private::Target::CreateBreakpoint(), lldb_private::DynamicLoader, findSymbolAddress(), lldb_private::Target::GetBreakpointByID(), lldb_private::Stoppoint::GetID(), lldb_private::GetLog(), LLDB_INVALID_ADDRESS, LLDB_INVALID_BREAK_ID, LLDB_LOGF, m_dyld_bid, lldb_private::DynamicLoader::m_process, m_rendezvous, RendezvousBreakpointHit(), lldb_private::Breakpoint::SetBreakpointKind(), and lldb_private::Breakpoint::SetCallback().
Referenced by DidAttach().
Terminate()
void DynamicLoaderHexagonDYLD::Terminate () static
Definition at line 80 of file DynamicLoaderHexagonDYLD.cpp.
UnloadSections()
void DynamicLoaderHexagonDYLD::UnloadSections (const lldb::ModuleSP module) override protected virtual
Removes the loaded sections from the target in module.
Parameters
module The module to traverse.
Reimplemented from lldb_private::DynamicLoader.
Definition at line 241 of file DynamicLoaderHexagonDYLD.cpp.
References lldb_private::SectionList::GetSectionAtIndex(), GetSectionListFromModule(), lldb_private::SectionList::GetSize(), m_loaded_modules, lldb_private::DynamicLoader::m_process, and lldb_private::Target::SetSectionUnloaded().
Referenced by RefreshModules().
UpdateLoadedSections()
void DynamicLoaderHexagonDYLD::UpdateLoadedSections (lldb::ModuleSP module, lldb::addr_t link_map_addr, lldb::addr_t base_addr, bool base_addr_is_offset) override protected virtual
Updates the load address of every allocatable section in module.
Parameters
module The module to traverse.
link_map_addr The virtual address of the link map for the module.
base_addr The virtual base address module is loaded at.
Reimplemented from lldb_private::DynamicLoader.
Definition at line 207 of file DynamicLoaderHexagonDYLD.cpp.
References lldb_private::SectionList::GetSectionAtIndex(), GetSectionListFromModule(), lldb_private::SectionList::GetSize(), m_loaded_modules, lldb_private::DynamicLoader::m_process, and lldb_private::Target::SetSectionLoadAddress().
Referenced by DidAttach().
Member Data Documentation
m_dyld_bid
lldb::break_id_t DynamicLoaderHexagonDYLD::m_dyld_bid protected
Rendezvous breakpoint.
Definition at line 63 of file DynamicLoaderHexagonDYLD.h.
Referenced by DynamicLoaderHexagonDYLD(), SetRendezvousBreakpoint(), and ~DynamicLoaderHexagonDYLD().
m_entry_point
lldb::addr_t DynamicLoaderHexagonDYLD::m_entry_point protected
Virtual entry address of the inferior process.
Definition at line 60 of file DynamicLoaderHexagonDYLD.h.
Referenced by DynamicLoaderHexagonDYLD(), and GetEntryPoint().
m_load_offset
lldb::addr_t DynamicLoaderHexagonDYLD::m_load_offset protected
Virtual load address of the inferior process.
Definition at line 57 of file DynamicLoaderHexagonDYLD.h.
Referenced by DynamicLoaderHexagonDYLD().
m_loaded_modules
std::map<lldb::ModuleWP, lldb::addr_t, std::owner_less<lldb::ModuleWP> > DynamicLoaderHexagonDYLD::m_loaded_modules protected
Loaded module list. (link map for each module)
Definition at line 67 of file DynamicLoaderHexagonDYLD.h.
Referenced by GetThreadLocalData(), LoadAllCurrentModules(), UnloadSections(), and UpdateLoadedSections().
m_rendezvous
HexagonDYLDRendezvous DynamicLoaderHexagonDYLD::m_rendezvous protected
Runtime linker rendezvous structure.
Definition at line 54 of file DynamicLoaderHexagonDYLD.h.
Referenced by DynamicLoaderHexagonDYLD(), GetThreadLocalData(), LoadAllCurrentModules(), RefreshModules(), RendezvousBreakpointHit(), and SetRendezvousBreakpoint().
The documentation for this class was generated from the following files:
DynamicLoaderHexagonDYLD.h
DynamicLoaderHexagonDYLD.cpp