LLDB: lldb_private::RegisterValue Class Reference
lldb_private::RegisterValue Class Reference
#include <RegisterValue.h>
Classes
struct RegisterValueBuffer
Public Types
enum { kTypicalRegisterByteSize = 256u , kMaxRegisterByteSize = 256u * 256u }
enum Type {
eTypeInvalid , eTypeUInt8 , eTypeUInt16 , eTypeUInt32 ,
eTypeUInt64 , eTypeUIntN , eTypeFloat , eTypeDouble ,
eTypeLongDouble , eTypeBytes
}
typedef llvm::SmallVector< uint8_t, kTypicalRegisterByteSize > BytesContainer
Public Member Functions
RegisterValue ()
RegisterValue (uint8_t inst)
RegisterValue (uint16_t inst)
RegisterValue (uint32_t inst)
RegisterValue (uint64_t inst)
RegisterValue (llvm::APInt inst)
RegisterValue (float value)
RegisterValue (double value)
RegisterValue (long double value)
RegisterValue (llvm::ArrayRef< uint8_t > bytes, lldb::ByteOrder byte_order)
RegisterValue::Type GetType () const
bool CopyValue (const RegisterValue &rhs)
void SetType (RegisterValue::Type type)
RegisterValue::Type SetType (const RegisterInfo &reg_info)
bool GetData (DataExtractor &data) const
uint32_t GetAsMemoryData (const RegisterInfo &reg_info, void *dst, uint32_t dst_len, lldb::ByteOrder dst_byte_order, Status &error) const
uint32_t SetFromMemoryData (const RegisterInfo &reg_info, const void *src, uint32_t src_len, lldb::ByteOrder src_byte_order, Status &error)
bool GetScalarValue (Scalar &scalar) const
uint8_t GetAsUInt8 (uint8_t fail_value=UINT8_MAX, bool *success_ptr=nullptr) const
uint16_t GetAsUInt16 (uint16_t fail_value=UINT16_MAX, bool *success_ptr=nullptr) const
uint32_t GetAsUInt32 (uint32_t fail_value=UINT32_MAX, bool *success_ptr=nullptr) const
uint64_t GetAsUInt64 (uint64_t fail_value=UINT64_MAX, bool *success_ptr=nullptr) const
llvm::APInt GetAsUInt128 (const llvm::APInt &fail_value, bool *success_ptr=nullptr) const
float GetAsFloat (float fail_value=0.0f, bool *success_ptr=nullptr) const
double GetAsDouble (double fail_value=0.0, bool *success_ptr=nullptr) const
long double GetAsLongDouble (long double fail_value=0.0, bool *success_ptr=nullptr) const
void SetValueToInvalid ()
bool ClearBit (uint32_t bit)
bool SetBit (uint32_t bit)
bool operator== (const RegisterValue &rhs) const
bool operator!= (const RegisterValue &rhs) const
void operator= (uint8_t uint)
void operator= (uint16_t uint)
void operator= (uint32_t uint)
void operator= (uint64_t uint)
void operator= (llvm::APInt uint)
void operator= (float f)
void operator= (double f)
void operator= (long double f)
void SetUInt8 (uint8_t uint)
void SetUInt16 (uint16_t uint)
void SetUInt32 (uint32_t uint, Type t=eTypeUInt32)
void SetUInt64 (uint64_t uint, Type t=eTypeUInt64)
void SetUIntN (llvm::APInt uint)
bool SetUInt (uint64_t uint, uint32_t byte_size)
void SetFloat (float f)
void SetDouble (double f)
void SetLongDouble (long double f)
void SetBytes (const void *bytes, size_t length, lldb::ByteOrder byte_order)
bool SignExtend (uint32_t sign_bitpos)
Status SetValueFromString (const RegisterInfo *reg_info, llvm::StringRef value_str)
Status SetValueFromString (const RegisterInfo *reg_info, const char *value_str)=delete
Status SetValueFromData (const RegisterInfo &reg_info, DataExtractor &data, lldb::offset_t offset, bool partial_data_ok)
const void * GetBytes () const
lldb::ByteOrder GetByteOrder () const
uint32_t GetByteSize () const
void Clear ()
Protected Attributes
RegisterValue::Type m_type = eTypeInvalid
Scalar m_scalar
struct lldb_private::RegisterValue::RegisterValueBuffer buffer
Detailed Description
Definition at line 29 of file RegisterValue.h.
Member Typedef Documentation
BytesContainer
typedef llvm::SmallVector<uint8_t, kTypicalRegisterByteSize> lldb_private::RegisterValue::BytesContainer
Definition at line 41 of file RegisterValue.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kTypicalRegisterByteSize
kMaxRegisterByteSize
Definition at line 31 of file RegisterValue.h.
Type
enum lldb_private::RegisterValue::Type
Enumerator
eTypeInvalid
eTypeUInt8
eTypeUInt16
eTypeUInt32
eTypeUInt64
eTypeUIntN
eTypeFloat
< This value is used when the (integer) register is larger than 64-bits.
eTypeDouble
eTypeLongDouble
eTypeBytes
Definition at line 43 of file RegisterValue.h.
Constructor & Destructor Documentation
RegisterValue() [1/10]
lldb_private::RegisterValue::RegisterValue () inline
Definition at line 57 of file RegisterValue.h.
References m_scalar.
Referenced by CopyValue(), operator!=(), operator==(), and SetType().
RegisterValue() [2/10]
lldb_private::RegisterValue::RegisterValue (uint8_t inst) inline explicit
Definition at line 59 of file RegisterValue.h.
References eTypeUInt8, m_scalar, and m_type.
RegisterValue() [3/10]
lldb_private::RegisterValue::RegisterValue (uint16_t inst) inline explicit
Definition at line 61 of file RegisterValue.h.
References eTypeUInt16, m_scalar, and m_type.
RegisterValue() [4/10]
lldb_private::RegisterValue::RegisterValue (uint32_t inst) inline explicit
Definition at line 65 of file RegisterValue.h.
References eTypeUInt32, m_scalar, and m_type.
RegisterValue() [5/10]
lldb_private::RegisterValue::RegisterValue (uint64_t inst) inline explicit
Definition at line 69 of file RegisterValue.h.
References eTypeUInt64, m_scalar, and m_type.
RegisterValue() [6/10]
lldb_private::RegisterValue::RegisterValue (llvm::APInt inst) inline explicit
Definition at line 73 of file RegisterValue.h.
References eTypeUIntN, m_scalar, and m_type.
RegisterValue() [7/10]
lldb_private::RegisterValue::RegisterValue (float value) inline explicit
Definition at line 77 of file RegisterValue.h.
References eTypeFloat, m_scalar, and m_type.
RegisterValue() [8/10]
lldb_private::RegisterValue::RegisterValue (double value) inline explicit
Definition at line 79 of file RegisterValue.h.
References eTypeDouble, m_scalar, and m_type.
RegisterValue() [9/10]
lldb_private::RegisterValue::RegisterValue (long double value) inline explicit
Definition at line 83 of file RegisterValue.h.
References eTypeLongDouble, m_scalar, and m_type.
RegisterValue() [10/10]
lldb_private::RegisterValue::RegisterValue (llvm::ArrayRef< uint8_t > bytes, lldb::ByteOrder byte_order) inline explicit
Definition at line 87 of file RegisterValue.h.
References SetBytes().
Member Function Documentation
Clear()
void RegisterValue::Clear ()
Definition at line 140 of file RegisterValue.cpp.
References eTypeInvalid, and m_type.
ClearBit()
bool RegisterValue::ClearBit (uint32_t bit)
Definition at line 762 of file RegisterValue.cpp.
References lldb_private::bit(), buffer, lldb::eByteOrderBig, lldb::eByteOrderLittle, eTypeBytes, eTypeDouble, eTypeFloat, eTypeInvalid, eTypeLongDouble, eTypeUInt16, eTypeUInt32, eTypeUInt64, eTypeUInt8, eTypeUIntN, GetByteSize(), m_scalar, and m_type.
CopyValue()
bool RegisterValue::CopyValue (const RegisterValue & rhs)
Definition at line 450 of file RegisterValue.cpp.
References buffer, lldb_private::RegisterValue::RegisterValueBuffer::byte_order, lldb_private::RegisterValue::RegisterValueBuffer::bytes, eTypeBytes, eTypeDouble, eTypeFloat, eTypeInvalid, eTypeLongDouble, eTypeUInt16, eTypeUInt32, eTypeUInt64, eTypeUInt8, eTypeUIntN, m_scalar, m_type, and RegisterValue().
Referenced by SetType().
GetAsDouble()
double RegisterValue::GetAsDouble (double fail_value = 0.0, bool * success_ptr = nullptr) const
Definition at line 624 of file RegisterValue.cpp.
References eTypeDouble, eTypeFloat, eTypeLongDouble, eTypeUInt32, eTypeUInt64, eTypeUIntN, m_scalar, and m_type.
Referenced by ABISysV_arm::GetReturnValueObjectImpl().
GetAsFloat()
float RegisterValue::GetAsFloat (float fail_value = 0.0f, bool * success_ptr = nullptr) const
Definition at line 605 of file RegisterValue.cpp.
References eTypeDouble, eTypeFloat, eTypeLongDouble, eTypeUInt32, eTypeUInt64, eTypeUIntN, m_scalar, and m_type.
Referenced by ABISysV_arm::GetReturnValueObjectImpl().
GetAsLongDouble()
long double RegisterValue::GetAsLongDouble (long double fail_value = 0.0, bool * success_ptr = nullptr) const
Definition at line 644 of file RegisterValue.cpp.
References eTypeDouble, eTypeFloat, eTypeLongDouble, eTypeUInt32, eTypeUInt64, eTypeUIntN, m_scalar, and m_type.
GetAsMemoryData()
uint32_t RegisterValue::GetAsMemoryData (const RegisterInfo & reg_info, void * dst, uint32_t dst_len, lldb::ByteOrder dst_byte_order, Status & error) const
Definition at line 38 of file RegisterValue.cpp.
References lldb_private::RegisterInfo::byte_size, lldb_private::DataExtractor::CopyByteOrderedData(), error(), eTypeInvalid, lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::Status::FromErrorStringWithFormatv(), GetData(), GetType(), and lldb_private::RegisterInfo::name.
Referenced by ABIMacOSX_arm64::GetReturnValueObjectImpl(), ABIMacOSX_arm::GetReturnValueObjectImpl(), ABISysV_arm64::GetReturnValueObjectImpl(), ABISysV_arm::GetReturnValueObjectImpl(), ABISysV_mips64::GetReturnValueObjectImpl(), ABISysV_i386::GetReturnValueObjectSimple(), ABISysV_ppc::GetReturnValueObjectSimple(), ABISysV_x86_64::GetReturnValueObjectSimple(), ABIWindows_x86_64::GetReturnValueObjectSimple(), GetValObjFromIntRegs(), GetValObjFromIntRegs(), LoadValueFromConsecutiveGPRRegisters(), LoadValueFromConsecutiveGPRRegisters(), EntityRegister::Materialize(), read_register_u128(), lldb_private::process_linux::NativeRegisterContextLinux::WriteRegisterRaw(), lldb_private::NativeRegisterContext::WriteRegisterValueToMemory(), and lldb_private::RegisterContext::WriteRegisterValueToMemory().
GetAsUInt128()
llvm::APInt RegisterValue::GetAsUInt128 (const llvm::APInt & fail_value, bool * success_ptr = nullptr) const
Definition at line 567 of file RegisterValue.cpp.
References BITWIDTH_INT128, buffer, eTypeBytes, eTypeDouble, eTypeFloat, eTypeLongDouble, eTypeUInt16, eTypeUInt32, eTypeUInt64, eTypeUInt8, eTypeUIntN, m_scalar, m_type, and NUM_OF_WORDS_INT128.
Referenced by EmulateInstructionMIPS64::Emulate_MSA_Branch_V(), and EmulateInstructionMIPS::Emulate_MSA_Branch_V().
GetAsUInt16()
uint16_t RegisterValue::GetAsUInt16 (uint16_t fail_value = UINT16_MAX, bool * success_ptr = nullptr) const
Definition at line 476 of file RegisterValue.cpp.
References buffer, eTypeBytes, eTypeUInt16, eTypeUInt8, m_scalar, and m_type.
Referenced by read_register_u16_raw(), and RegisterContextDarwin_x86_64::WriteRegister().
GetAsUInt32()
uint32_t RegisterValue::GetAsUInt32 (uint32_t fail_value = UINT32_MAX, bool * success_ptr = nullptr) const
Definition at line 502 of file RegisterValue.cpp.
References buffer, eTypeBytes, eTypeDouble, eTypeFloat, eTypeLongDouble, eTypeUInt16, eTypeUInt32, eTypeUInt8, m_scalar, and m_type.
Referenced by ThreadMachCore::CalculateStopInfo(), lldb_private::DumpRegisterValue(), lldb_private::ArchitectureArm::GetArchitectureUnwindPlan(), ABISysV_hexagon::GetReturnValueObjectImpl(), read_register_u32_raw(), RegisterContextDarwin_arm64::WriteRegister(), RegisterContextDarwin_arm::WriteRegister(), RegisterContextDarwin_riscv32::WriteRegister(), and RegisterContextDarwin_x86_64::WriteRegister().
GetAsUInt64()
uint64_t RegisterValue::GetAsUInt64 (uint64_t fail_value = UINT64_MAX, bool * success_ptr = nullptr) const
Definition at line 532 of file RegisterValue.cpp.
References buffer, eTypeBytes, eTypeDouble, eTypeFloat, eTypeLongDouble, eTypeUInt16, eTypeUInt32, eTypeUInt64, eTypeUInt8, m_scalar, and m_type.
Referenced by AddThreadLocalMemoryRegions(), ThreadMachCore::CalculateStopInfo(), lldb_private::NativeRegisterContextDBReg_x86::ClearAllHardwareWatchpoints(), lldb_private::NativeRegisterContextDBReg_x86::ClearHardwareWatchpoint(), lldb_private::NativeRegisterContextDBReg_x86::ClearWatchpointHit(), InstrumentationBoundsSafetyStopInfo::ComputeStopReasonAndSuggestedStackFrameWithoutDebugInfo(), lldb_private::StopInfoMachException::DeterminePtrauthFailure(), lldb_private::OptionArgParser::DoToAddress(), lldb_private::process_linux::NativeRegisterContextLinux::DoWriteRegisterValue(), CommandObjectRegisterRead::DumpRegister(), lldb_private::DumpRegisterValue(), lldb_private::NativeRegisterContextDBReg_x86::GetWatchpointAddress(), lldb_private::NativeRegisterContextDBReg_x86::IsWatchpointHit(), lldb_private::NativeRegisterContextDBReg_x86::IsWatchpointVacant(), lldb_private::Rs::Read(), read_register_u64_raw(), lldb_private::Rs::ReadAPFloat(), lldb_private::RegisterContextUnwind::ReadFrameAddress(), lldb_private::RegisterContextUnwind::ReadGPRValue(), lldb_private::RegisterContextUnwind::ReadRegister(), lldb_private::NativeRegisterContext::ReadRegisterAsUnsigned(), lldb_private::RegisterContext::ReadRegisterAsUnsigned(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::RegisterContextUnwind::ReadRegisterValueFromRegisterLocation(), lldb_private::NativeRegisterContextDBReg_x86::SetHardwareWatchpointWithIndex(), lldb_private::RegisterContextUnwind::TryFallbackUnwindPlan(), EmulationStateARM::WritePseudoRegister(), RegisterContextDarwin_arm64::WriteRegister(), RegisterContextDarwin_x86_64::WriteRegister(), and UnwindAssemblyInstEmulation::WriteRegister().
GetAsUInt8()
uint8_t lldb_private::RegisterValue::GetAsUInt8 (uint8_t fail_value = UINT8_MAX, bool * success_ptr = nullptr) const inline
Definition at line 119 of file RegisterValue.h.
References eTypeUInt8, m_scalar, and m_type.
Referenced by RegisterContextDarwin_x86_64::WriteRegister().
GetByteOrder()
lldb::ByteOrder lldb_private::RegisterValue::GetByteOrder () const inline
Definition at line 257 of file RegisterValue.h.
References buffer, eTypeBytes, lldb_private::endian::InlHostByteOrder(), and m_type.
Referenced by GetData().
GetBytes()
const void * RegisterValue::GetBytes () const
Definition at line 665 of file RegisterValue.cpp.
References buffer, eTypeBytes, eTypeDouble, eTypeFloat, eTypeInvalid, eTypeLongDouble, eTypeUInt16, eTypeUInt32, eTypeUInt64, eTypeUInt8, eTypeUIntN, m_scalar, and m_type.
Referenced by EmulateInstructionMIPS64::Emulate_MSA_Branch_DF(), EmulateInstructionMIPS::Emulate_MSA_Branch_DF(), GetData(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_g(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_p(), PrintRegisterValue(), lldb_private::RegisterContextUnifiedCore::RegisterContextUnifiedCore(), RegisterContextDarwin_arm64::WriteRegister(), RegisterContextDarwin_x86_64::WriteRegister(), and WriteRegisterValueInHexFixedWidth().
GetByteSize()
uint32_t RegisterValue::GetByteSize () const
Definition at line 685 of file RegisterValue.cpp.
References buffer, eTypeBytes, eTypeDouble, eTypeFloat, eTypeInvalid, eTypeLongDouble, eTypeUInt16, eTypeUInt32, eTypeUInt64, eTypeUInt8, eTypeUIntN, m_scalar, and m_type.
Referenced by ClearBit(), GetData(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_p(), EntityRegister::Materialize(), lldb_private::RegisterContextUnifiedCore::RegisterContextUnifiedCore(), SetBit(), RegisterContextDarwin_arm64::WriteRegister(), RegisterContextDarwin_x86_64::WriteRegister(), lldb_private::process_linux::NativeRegisterContextLinux::WriteRegisterRaw(), and WriteRegisterValueInHexFixedWidth().
GetData()
bool RegisterValue::GetData (DataExtractor & data) const
Definition at line 34 of file RegisterValue.cpp.
References GetByteOrder(), GetBytes(), GetByteSize(), and lldb_private::DataExtractor::SetData().
Referenced by lldb_private::DumpRegisterValue(), GetAsMemoryData(), ABIMacOSX_arm64::GetReturnValueObjectImpl(), ABISysV_arm64::GetReturnValueObjectImpl(), ABISysV_mips64::GetReturnValueObjectImpl(), ABISysV_mips::GetReturnValueObjectImpl(), ABISysV_ppc::GetReturnValueObjectImpl(), ABISysV_x86_64::GetReturnValueObjectImpl(), ABIWindows_x86_64::GetReturnValueObjectImpl(), ABISysV_i386::GetReturnValueObjectSimple(), ABISysV_ppc::GetReturnValueObjectSimple(), ABISysV_s390x::GetReturnValueObjectSimple(), ABISysV_x86_64::GetReturnValueObjectSimple(), ABIWindows_x86_64::GetReturnValueObjectSimple(), SetType(), and lldb_private::process_gdb_remote::GDBRemoteRegisterContext::WriteRegister().
GetScalarValue()
bool RegisterValue::GetScalarValue (Scalar & scalar) const
Definition at line 115 of file RegisterValue.cpp.
References buffer, lldb::eEncodingUint, eTypeBytes, eTypeDouble, eTypeFloat, eTypeInvalid, eTypeLongDouble, eTypeUInt16, eTypeUInt32, eTypeUInt64, eTypeUInt8, eTypeUIntN, m_scalar, m_type, lldb_private::Scalar::SetValueFromData(), and lldb_private::Status::Success().
Referenced by ABIMacOSX_arm64::GetArgumentValues(), ABIMacOSX_arm::GetArgumentValues(), ABISysV_arm64::GetArgumentValues(), ABISysV_arm::GetArgumentValues(), and lldb_private::DWARFExpression::ReadRegisterValueAsScalar().
GetType()
RegisterValue::Type lldb_private::RegisterValue::GetType () const inline
Definition at line 92 of file RegisterValue.h.
References m_type.
Referenced by lldb_private::OptionArgParser::DoToAddress(), GetAsMemoryData(), lldb_private::ThreadPlanAssemblyTracer::Log(), and lldb_private::RegisterContextUnwind::ReadRegister().
operator!=()
bool RegisterValue::operator!= (const RegisterValue & rhs) const
Definition at line 758 of file RegisterValue.cpp.
References RegisterValue().
operator=() [1/8]
void lldb_private::RegisterValue::operator= (double f) inline
Definition at line 191 of file RegisterValue.h.
References eTypeDouble, m_scalar, and m_type.
operator=() [2/8]
void lldb_private::RegisterValue::operator= (float f) inline
Definition at line 186 of file RegisterValue.h.
References eTypeFloat, m_scalar, and m_type.
operator=() [3/8]
void lldb_private::RegisterValue::operator= (llvm::APInt uint) inline
Definition at line 181 of file RegisterValue.h.
References eTypeUIntN, m_scalar, and m_type.
operator=() [4/8]
void lldb_private::RegisterValue::operator= (long double f) inline
Definition at line 196 of file RegisterValue.h.
References eTypeLongDouble, m_scalar, and m_type.
operator=() [5/8]
void lldb_private::RegisterValue::operator= (uint16_t uint) inline
Definition at line 166 of file RegisterValue.h.
References eTypeUInt16, m_scalar, and m_type.
operator=() [6/8]
void lldb_private::RegisterValue::operator= (uint32_t uint) inline
Definition at line 171 of file RegisterValue.h.
References eTypeUInt32, m_scalar, and m_type.
operator=() [7/8]
void lldb_private::RegisterValue::operator= (uint64_t uint) inline
Definition at line 176 of file RegisterValue.h.
References eTypeUInt64, m_scalar, and m_type.
operator=() [8/8]
void lldb_private::RegisterValue::operator= (uint8_t uint) inline
Definition at line 161 of file RegisterValue.h.
References eTypeUInt8, m_scalar, and m_type.
operator==()
bool RegisterValue::operator== (const RegisterValue & rhs) const
Definition at line 737 of file RegisterValue.cpp.
References buffer, lldb_private::RegisterValue::RegisterValueBuffer::bytes, eTypeBytes, eTypeDouble, eTypeFloat, eTypeInvalid, eTypeLongDouble, eTypeUInt16, eTypeUInt32, eTypeUInt64, eTypeUInt8, eTypeUIntN, m_scalar, m_type, and RegisterValue().
SetBit()
bool RegisterValue::SetBit (uint32_t bit)
Definition at line 802 of file RegisterValue.cpp.
References lldb_private::bit(), buffer, lldb::eByteOrderBig, lldb::eByteOrderLittle, eTypeBytes, eTypeDouble, eTypeFloat, eTypeInvalid, eTypeLongDouble, eTypeUInt16, eTypeUInt32, eTypeUInt64, eTypeUInt8, eTypeUIntN, GetByteSize(), m_scalar, and m_type.
SetBytes()
void RegisterValue::SetBytes (const void * bytes, size_t length, lldb::ByteOrder byte_order)
Definition at line 724 of file RegisterValue.cpp.
References buffer, eTypeBytes, eTypeInvalid, and m_type.
Referenced by ParseVectorEncoding(), RegisterContextCorePOSIX_powerpc::ReadRegister(), RegisterContextCorePOSIX_ppc64le::ReadRegister(), RegisterContextDarwin_arm64::ReadRegister(), RegisterContextDarwin_x86_64::ReadRegister(), RegisterValue(), ABISysV_s390x::SetReturnValueObject(), ABISysV_x86_64::SetReturnValueObject(), ABIWindows_x86_64::SetReturnValueObject(), and lldb_private::process_linux::NativeRegisterContextLinux::WriteRegisterRaw().
SetDouble()
void lldb_private::RegisterValue::SetDouble (double f) inline
Definition at line 233 of file RegisterValue.h.
References eTypeDouble, m_scalar, and m_type.
Referenced by RegisterContextDarwin_arm64::ReadRegister(), and SetValueFromData().
SetFloat()
void lldb_private::RegisterValue::SetFloat (float f) inline
Definition at line 228 of file RegisterValue.h.
References eTypeFloat, m_scalar, and m_type.
Referenced by RegisterContextDarwin_arm64::ReadRegister(), and SetValueFromData().
SetFromMemoryData()
uint32_t RegisterValue::SetFromMemoryData (const RegisterInfo & reg_info, const void * src, uint32_t src_len, lldb::ByteOrder src_byte_order, Status & error)
Definition at line 74 of file RegisterValue.cpp.
References lldb_private::RegisterInfo::byte_size, error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::RegisterInfo::name, and SetValueFromData().
Referenced by EmulateInstructionARM64::EmulateLDPSTP(), EmulateInstructionARM64::EmulateLDRSTRImm(), lldb_private::minidump::RegisterContextMinidump_ARM64::ReadRegister(), lldb_private::minidump::RegisterContextMinidump_ARM::ReadRegister(), lldb_private::process_gdb_remote::GDBRemoteRegisterContext::ReadRegister(), RegisterContextCorePOSIX_arm64::ReadRegister(), RegisterContextCorePOSIX_loongarch64::ReadRegister(), RegisterContextCorePOSIX_riscv32::ReadRegister(), RegisterContextCorePOSIX_riscv64::ReadRegister(), RegisterContextCorePOSIX_x86::ReadRegister(), lldb_private::NativeRegisterContext::ReadRegisterValueFromMemory(), and lldb_private::RegisterContext::ReadRegisterValueFromMemory().
SetLongDouble()
void lldb_private::RegisterValue::SetLongDouble (long double f) inline
Definition at line 238 of file RegisterValue.h.
References eTypeLongDouble, m_scalar, and m_type.
Referenced by ABISysV_i386::SetReturnValueObject(), and SetValueFromData().
SetType() [1/2]
RegisterValue::Type RegisterValue::SetType (const RegisterInfo & reg_info)
Definition at line 142 of file RegisterValue.cpp.
References CopyValue(), error(), GetData(), m_type, RegisterValue(), SetValueFromData(), and UNUSED_IF_ASSERT_DISABLED.
SetType() [2/2]
void lldb_private::RegisterValue::SetType (RegisterValue::Type type) inline
Definition at line 96 of file RegisterValue.h.
References m_type.
Referenced by lldb_private::process_linux::NativeRegisterContextLinux::WriteRegisterRaw().
SetUInt()
bool RegisterValue::SetUInt (uint64_t uint, uint32_t byte_size)
Definition at line 706 of file RegisterValue.cpp.
References SetUInt16(), SetUInt32(), SetUInt64(), SetUInt8(), and SetUIntN().
Referenced by lldb_private::process_linux::NativeRegisterContextLinux::DoReadRegisterValue(), UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly(), UnwindAssemblyInstEmulation::GetRegisterValue(), EmulationStateARM::ReadPseudoRegister(), lldb_private::RegisterContextDummy::ReadRegister(), lldb_private::RegisterContextHistory::ReadRegister(), RegisterContextCorePOSIX_s390x::ReadRegister(), lldb_private::RegisterContextUnwind::ReadRegisterValueFromRegisterLocation(), SetValueFromString(), lldb_private::NativeRegisterContext::WriteRegisterFromUnsigned(), lldb_private::RegisterContext::WriteRegisterFromUnsigned(), lldb_private::EmulateInstruction::WriteRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
SetUInt16()
void lldb_private::RegisterValue::SetUInt16 (uint16_t uint) inline
Definition at line 206 of file RegisterValue.h.
References eTypeUInt16, m_scalar, and m_type.
Referenced by lldb_private::RegisterContextUnifiedCore::ReadRegister(), SetUInt(), and SetValueFromData().
SetUInt32()
void lldb_private::RegisterValue::SetUInt32 (uint32_t uint, Type t = eTypeUInt32) inline
Definition at line 211 of file RegisterValue.h.
References eTypeUInt32, m_scalar, and m_type.
Referenced by ABIMacOSX_arm::PrepareTrivialCall(), ABIMacOSX_i386::PrepareTrivialCall(), ABISysV_arm::PrepareTrivialCall(), ABISysV_i386::PrepareTrivialCall(), ABISysV_mips::PrepareTrivialCall(), lldb_private::RegisterContextUnifiedCore::ReadRegister(), RegisterContextDarwin_arm64::ReadRegister(), RegisterContextDarwin_arm::ReadRegister(), ABISysV_i386::SetReturnValueObject(), SetUInt(), and SetValueFromData().
SetUInt64()
void lldb_private::RegisterValue::SetUInt64 (uint64_t uint, Type t = eTypeUInt64) inline
Definition at line 216 of file RegisterValue.h.
References eTypeUInt64, m_scalar, and m_type.
Referenced by lldb_private::Executor::operator()(), lldb_private::RegisterContextUnifiedCore::ReadRegister(), RegisterContextDarwin_arm64::ReadRegister(), lldb_private::EmulateInstruction::ReadRegisterDefault(), SetUInt(), SetValueFromData(), lldb_private::Rd::Write(), and lldb_private::Rd::WriteAPFloat().
SetUInt8()
void lldb_private::RegisterValue::SetUInt8 (uint8_t uint) inline
Definition at line 201 of file RegisterValue.h.
References eTypeUInt8, m_scalar, and m_type.
Referenced by SetUInt(), and SetValueFromData().
SetUIntN()
void lldb_private::RegisterValue::SetUIntN (llvm::APInt uint) inline
Definition at line 221 of file RegisterValue.h.
References eTypeUIntN, m_scalar, and m_type.
Referenced by SetUInt(), and SetValueFromData().
SetValueFromData()
Status RegisterValue::SetValueFromData (const RegisterInfo & reg_info, DataExtractor & data, lldb::offset_t offset, bool partial_data_ok)
Definition at line 155 of file RegisterValue.cpp.
References buffer, lldb_private::RegisterInfo::byte_size, lldb_private::DataExtractor::CopyByteOrderedData(), lldb::eEncodingIEEE754, lldb::eEncodingInvalid, lldb::eEncodingSint, lldb::eEncodingUint, lldb::eEncodingVector, lldb_private::RegisterInfo::encoding, error(), eTypeBytes, eTypeInvalid, lldb_private::DataExtractor::ExtractBytes(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataExtractor::GetByteOrder(), lldb_private::DataExtractor::GetByteSize(), lldb_private::DataExtractor::GetDouble(), lldb_private::DataExtractor::GetFloat(), lldb_private::DataExtractor::GetLongDouble(), lldb_private::DataExtractor::GetMaxU32(), lldb_private::DataExtractor::GetMaxU64(), lldb_private::endian::InlHostByteOrder(), kMaxRegisterByteSize, m_type, lldb_private::RegisterInfo::name, SetDouble(), SetFloat(), SetLongDouble(), SetUInt16(), SetUInt32(), SetUInt64(), SetUInt8(), and SetUIntN().
Referenced by lldb_private::process_gdb_remote::GDBRemoteRegisterContext::ReadRegister(), lldb_private::wasm::RegisterContextWasm::ReadRegister(), RegisterContextCorePOSIX_arm::ReadRegister(), RegisterContextMemory::ReadRegister(), lldb_private::ValueObjectVariable::SetData(), SetFromMemoryData(), ABIMacOSX_arm64::SetReturnValueObject(), ABISysV_arm64::SetReturnValueObject(), and SetType().
SetValueFromString() [1/2]
Status lldb_private::RegisterValue::SetValueFromString (const RegisterInfo * reg_info, const char * value_str) delete
SetValueFromString() [2/2]
Status RegisterValue::SetValueFromString (const RegisterInfo * reg_info, llvm::StringRef value_str)
Definition at line 307 of file RegisterValue.cpp.
References lldb_private::RegisterInfo::byte_size, lldb::eEncodingIEEE754, lldb::eEncodingInvalid, lldb::eEncodingSint, lldb::eEncodingUint, lldb::eEncodingVector, lldb_private::RegisterInfo::encoding, error(), eTypeDouble, eTypeFloat, eTypeInvalid, eTypeLongDouble, lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::Status::FromErrorStringWithFormatv(), m_scalar, m_type, ParseVectorEncoding(), SetUInt(), SInt64ValueIsValidForByteSize(), and UInt64ValueIsValidForByteSize().
Referenced by CommandObjectRegisterWrite::DoExecute(), and lldb_private::ValueObjectVariable::SetValueFromCString().
SetValueToInvalid()
void lldb_private::RegisterValue::SetValueToInvalid () inline
Definition at line 151 of file RegisterValue.h.
References eTypeInvalid, and m_type.
Referenced by RegisterContextDarwin_arm64::ReadRegister(), and RegisterContextDarwin_arm::ReadRegister().
SignExtend()
bool RegisterValue::SignExtend (uint32_t sign_bitpos)
Definition at line 430 of file RegisterValue.cpp.
References eTypeBytes, eTypeDouble, eTypeFloat, eTypeInvalid, eTypeLongDouble, eTypeUInt16, eTypeUInt32, eTypeUInt64, eTypeUInt8, eTypeUIntN, m_scalar, and m_type.
Referenced by EmulateInstructionARM64::EmulateLDPSTP(), ABIMacOSX_arm64::GetArgumentValues(), ABIMacOSX_arm::GetArgumentValues(), ABISysV_arm64::GetArgumentValues(), and ABISysV_arm::GetArgumentValues().
Member Data Documentation
buffer
struct lldb_private::RegisterValue::RegisterValueBuffer lldb_private::RegisterValue::buffer protected
Referenced by ClearBit(), CopyValue(), GetAsUInt128(), GetAsUInt16(), GetAsUInt32(), GetAsUInt64(), GetByteOrder(), GetBytes(), GetByteSize(), GetScalarValue(), operator==(), SetBit(), SetBytes(), and SetValueFromData().
m_scalar
Scalar lldb_private::RegisterValue::m_scalar protected
Definition at line 269 of file RegisterValue.h.
Referenced by ClearBit(), CopyValue(), GetAsDouble(), GetAsFloat(), GetAsLongDouble(), GetAsUInt128(), GetAsUInt16(), GetAsUInt32(), GetAsUInt64(), GetAsUInt8(), GetBytes(), GetByteSize(), GetScalarValue(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator==(), RegisterValue(), RegisterValue(), RegisterValue(), RegisterValue(), RegisterValue(), RegisterValue(), RegisterValue(), RegisterValue(), RegisterValue(), SetBit(), SetDouble(), SetFloat(), SetLongDouble(), SetUInt16(), SetUInt32(), SetUInt64(), SetUInt8(), SetUIntN(), SetValueFromString(), and SignExtend().
m_type
RegisterValue::Type lldb_private::RegisterValue::m_type = eTypeInvalid protected
Definition at line 268 of file RegisterValue.h.
Referenced by Clear(), ClearBit(), CopyValue(), GetAsDouble(), GetAsFloat(), GetAsLongDouble(), GetAsUInt128(), GetAsUInt16(), GetAsUInt32(), GetAsUInt64(), GetAsUInt8(), GetByteOrder(), GetBytes(), GetByteSize(), GetScalarValue(), GetType(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator==(), RegisterValue(), RegisterValue(), RegisterValue(), RegisterValue(), RegisterValue(), RegisterValue(), RegisterValue(), RegisterValue(), SetBit(), SetBytes(), SetDouble(), SetFloat(), SetLongDouble(), SetType(), SetType(), SetUInt16(), SetUInt32(), SetUInt64(), SetUInt8(), SetUIntN(), SetValueFromData(), SetValueFromString(), SetValueToInvalid(), and SignExtend().
The documentation for this class was generated from the following files:
RegisterValue.h
RegisterValue.cpp