LLDB: PlatformPOSIX Class Reference
PlatformPOSIX Class Reference
#include <PlatformPOSIX.h>
Public Member Functions
PlatformPOSIX (bool is_host)
Default Constructor.
~PlatformPOSIX () override
Destructor.
lldb_private::OptionGroupOptions * GetConnectionOptions (lldb_private::CommandInterpreter &interpreter) override
lldb_private::Status PutFile (const lldb_private::FileSpec &source, const lldb_private::FileSpec &destination, uint32_t uid=UINT32_MAX, uint32_t gid=UINT32_MAX) override
lldb_private::Status GetFile (const lldb_private::FileSpec &source, const lldb_private::FileSpec &destination) override
const lldb::UnixSignalsSP & GetRemoteUnixSignals () override
lldb::ProcessSP Attach (lldb_private::ProcessAttachInfo &attach_info, lldb_private::Debugger &debugger, lldb_private::Target *target, lldb_private::Status &error) override
Attach to an existing process using a process ID.
lldb::ProcessSP DebugProcess (lldb_private::ProcessLaunchInfo &launch_info, lldb_private::Debugger &debugger, lldb_private::Target &target, lldb_private::Status &error) override
Subclasses do not need to implement this function as it uses the Platform::LaunchProcess() followed by Platform::Attach ().
std::string GetPlatformSpecificConnectionInformation () override
void CalculateTrapHandlerSymbolNames () override
Ask the Platform subclass to fill in the list of trap handler names.
lldb_private::Status ConnectRemote (lldb_private::Args &args) override
lldb_private::Status DisconnectRemote () override
uint32_t DoLoadImage (lldb_private::Process *process, const lldb_private::FileSpec &remote_file, const std::vector< std::string > *paths, lldb_private::Status &error, lldb_private::FileSpec *loaded_image) override
lldb_private::Status UnloadImage (lldb_private::Process *process, uint32_t image_token) override
lldb_private::ConstString GetFullNameForDylib (lldb_private::ConstString basename) override
Public Member Functions inherited from lldb_private::RemoteAwarePlatform
virtual Status ResolveExecutable (const ModuleSpec &module_spec, lldb::ModuleSP &exe_module_sp) override
Set the target's executable based off of the existing architecture information in target given a path to an executable exe_file.
bool GetModuleSpec (const FileSpec &module_file_spec, const ArchSpec &arch, ModuleSpec &module_spec) override
lldb::user_id_t OpenFile (const FileSpec &file_spec, File::OpenOptions flags, uint32_t mode, Status &error) override
bool CloseFile (lldb::user_id_t fd, Status &error) override
uint64_t ReadFile (lldb::user_id_t fd, uint64_t offset, void *dst, uint64_t dst_len, Status &error) override
uint64_t WriteFile (lldb::user_id_t fd, uint64_t offset, const void *src, uint64_t src_len, Status &error) override
lldb::user_id_t GetFileSize (const FileSpec &file_spec) override
Status CreateSymlink (const FileSpec &src, const FileSpec &dst) override
bool GetFileExists (const FileSpec &file_spec) override
Status Unlink (const FileSpec &file_spec) override
FileSpec GetRemoteWorkingDirectory () override
bool SetRemoteWorkingDirectory (const FileSpec &working_dir) override
Status MakeDirectory (const FileSpec &file_spec, uint32_t mode) override
Status GetFilePermissions (const FileSpec &file_spec, uint32_t &file_permissions) override
Status SetFilePermissions (const FileSpec &file_spec, uint32_t file_permissions) override
llvm::ErrorOr< llvm::MD5::MD5Result > CalculateMD5 (const FileSpec &file_spec) override
Status GetFileWithUUID (const FileSpec &platform_file, const UUID *uuid, FileSpec &local_file) override
Locate a file for a platform.
bool GetRemoteOSVersion () override
std::optional< std::string > GetRemoteOSBuildString () override
std::optional< std::string > GetRemoteOSKernelDescription () override
ArchSpec GetRemoteSystemArchitecture () override
Status RunShellCommand (llvm::StringRef command, const FileSpec &working_dir, int *status_ptr, int *signo_ptr, std::string *command_output, const Timeout< std::micro > &timeout) override
Status RunShellCommand (llvm::StringRef interpreter, llvm::StringRef command, const FileSpec &working_dir, int *status_ptr, int *signo_ptr, std::string *command_output, const Timeout< std::micro > &timeout) override
const char * GetHostname () override
UserIDResolver & GetUserIDResolver () override
lldb_private::Environment GetEnvironment () override
bool IsConnected () const override
bool GetProcessInfo (lldb::pid_t pid, ProcessInstanceInfo &proc_info) override
uint32_t FindProcesses (const ProcessInstanceInfoMatch &match_info, ProcessInstanceInfoList &process_infos) override
Attach to an existing process by process name.
lldb::ProcessSP ConnectProcess (llvm::StringRef connect_url, llvm::StringRef plugin_name, Debugger &debugger, Target *target, Status &error) override
Status LaunchProcess (ProcessLaunchInfo &launch_info) override
Launch a new process on a platform, not necessarily for debugging, it could be just for running the process.
Status KillProcess (const lldb::pid_t pid) override
Kill process on a platform.
size_t ConnectToWaitingProcesses (Debugger &debugger, Status &error) override
Connect to all processes waiting for a debugger to attach.
Platform (bool is_host_platform)
Default Constructor.
Public Member Functions inherited from lldb_private::Platform
Platform (bool is_host_platform)
Default Constructor.
~Platform () override
The destructor is virtual since this class is designed to be inherited from by the plug-in instance.
virtual Status ResolveSymbolFile (Target &target, const ModuleSpec &sym_spec, FileSpec &sym_file)
Find a symbol file given a symbol file module specification.
virtual bool ResolveRemotePath (const FileSpec &platform_path, FileSpec &resolved_platform_path)
Resolves the FileSpec to a (possibly) remote path.
virtual llvm::VersionTuple GetOSVersion (Process *process=nullptr)
Get the OS version from a connected platform.
bool SetOSVersion (llvm::VersionTuple os_version)
std::optional< std::string > GetOSBuildString ()
std::optional< std::string > GetOSKernelDescription ()
llvm::StringRef GetName ()
virtual llvm::StringRef GetDescription ()=0
virtual void GetStatus (Stream &strm)
Report the current status for this platform.
virtual FileSpecList LocateExecutableScriptingResources (Target *target, Module &module, Stream &feedback_stream)
virtual Status GetSharedModule (const ModuleSpec &module_spec, Process *process, lldb::ModuleSP &module_sp, llvm::SmallVectorImpl< lldb::ModuleSP > *old_modules, bool *did_create_ptr)
void CallLocateModuleCallbackIfSet (const ModuleSpec &module_spec, lldb::ModuleSP &module_sp, FileSpec &symbol_file_spec, bool *did_create_ptr)
virtual std::vector< ArchSpec > GetSupportedArchitectures (const ArchSpec &process_host_arch)=0
Get the platform's supported architectures in the order in which they should be searched.
virtual size_t GetSoftwareBreakpointTrapOpcode (Target &target, BreakpointSite *bp_site)
virtual Status ShellExpandArguments (ProcessLaunchInfo &launch_info)
Perform expansion of the command-line for this launch info This can potentially involve wildcard expansion environment variable replacement, and whatever other argument magic the platform defines as part of its typical user experience.
virtual bool IsCompatibleArchitecture (const ArchSpec &arch, const ArchSpec &process_host_arch, ArchSpec::MatchType match, ArchSpec *compatible_arch_ptr)
Lets a platform answer if it is compatible with a given architecture and the target triple contained within.
virtual bool CanDebugProcess ()
Not all platforms will support debugging a process by spawning somehow halted for a debugger (specified using the "eLaunchFlagDebug" launch flag) and then attaching.
virtual lldb::ProcessSP ConnectProcessSynchronous (llvm::StringRef connect_url, llvm::StringRef plugin_name, Debugger &debugger, Stream &stream, Target *target, Status &error)
ProcessInstanceInfoList GetAllProcesses ()
virtual lldb::BreakpointSP SetThreadCreationBreakpoint (Target &target)
virtual lldb_private::ConstString GetSDKDirectory (lldb_private::Target &target)
virtual llvm::Expected< std::pair< XcodeSDK, bool > > GetSDKPathFromDebugInfo (Module &module)
Search each CU associated with the specified 'module' for the SDK paths the CUs were compiled against.
virtual llvm::Expected< std::string > ResolveSDKPathFromDebugInfo (Module &module)
Returns the full path of the most appropriate SDK for the specified 'module'.
virtual llvm::Expected< XcodeSDK > GetSDKPathFromDebugInfo (CompileUnit &unit)
Search CU for the SDK path the CUs was compiled against.
virtual llvm::Expected< std::string > ResolveSDKPathFromDebugInfo (CompileUnit &unit)
Returns the full path of the most appropriate SDK for the specified compile unit.
bool IsHost () const
bool IsRemote () const
const ArchSpec & GetSystemArchitecture ()
void SetSystemArchitecture (const ArchSpec &arch)
ArchSpec GetAugmentedArchSpec (llvm::StringRef triple)
If the triple contains not specify the vendor, os, and environment parts, we "augment" these using information from the platform and return the resulting ArchSpec object.
size_t GetMaxUserIDNameLength () const
size_t GetMaxGroupIDNameLength () const
const std::string & GetSDKRootDirectory () const
void SetSDKRootDirectory (std::string dir)
const std::string & GetSDKBuild () const
void SetSDKBuild (std::string sdk_build)
virtual bool SupportsModules ()
virtual void AddClangModuleCompilationOptions (Target *target, std::vector< std::string > &options)
FileSpec GetWorkingDirectory ()
bool SetWorkingDirectory (const FileSpec &working_dir)
virtual bool ModuleIsExcludedForUnconstrainedSearches (Target &target, const lldb::ModuleSP &module_sp)
virtual void AutoCompleteDiskFileOrDirectory (CompletionRequest &request, bool only_dir)
virtual Status Install (const FileSpec &src, const FileSpec &dst)
Install a file or directory to the remote system.
virtual MmapArgList GetMmapArgumentList (const ArchSpec &arch, lldb::addr_t addr, lldb::addr_t length, unsigned prot, unsigned flags, lldb::addr_t fd, lldb::addr_t offset)
virtual bool GetSupportsRSync ()
virtual void SetSupportsRSync (bool flag)
virtual const char * GetRSyncOpts ()
virtual void SetRSyncOpts (const char *opts)
virtual const char * GetRSyncPrefix ()
virtual void SetRSyncPrefix (const char *prefix)
virtual bool GetSupportsSSH ()
virtual void SetSupportsSSH (bool flag)
virtual const char * GetSSHOpts ()
virtual void SetSSHOpts (const char *opts)
virtual bool GetIgnoresRemoteHostname ()
virtual void SetIgnoresRemoteHostname (bool flag)
virtual void SetLocalCacheDirectory (const char *local)
virtual const char * GetLocalCacheDirectory ()
virtual uint32_t GetResumeCountForLaunchInfo (ProcessLaunchInfo &launch_info)
lldb::UnixSignalsSP GetUnixSignals ()
virtual std::string GetQueueNameForThreadQAddress (Process *process, lldb::addr_t dispatch_qaddr)
Locate a queue name given a thread's qaddr.
virtual lldb::queue_id_t GetQueueIDForThreadQAddress (Process *process, lldb::addr_t dispatch_qaddr)
Locate a queue ID given a thread's qaddr.
virtual const std::vector< ConstString > & GetTrapHandlerSymbolNames ()
Provide a list of trap handler function names for this platform.
virtual lldb::UnwindPlanSP GetTrapHandlerUnwindPlan (const ArchSpec &arch, ConstString name)
Try to get a specific unwind plan for a named trap handler.
virtual FileSpec LocateExecutable (const char *basename)
Find a support executable that may not live within in the standard locations related to LLDB.
virtual uint32_t GetDefaultMemoryCacheLineSize ()
Allow the platform to set preferred memory cache line size.
uint32_t LoadImage (lldb_private::Process *process, const lldb_private::FileSpec &local_file, const lldb_private::FileSpec &remote_file, lldb_private::Status &error)
Load a shared library into this process.
uint32_t LoadImageUsingPaths (lldb_private::Process *process, const lldb_private::FileSpec &library_name, const std::vector< std::string > &paths, lldb_private::Status &error, lldb_private::FileSpec *loaded_path)
Load a shared library specified by base name into this process, looking by hand along a set of paths.
virtual llvm::Expected< StructuredData::DictionarySP > FetchExtendedCrashInformation (lldb_private::Process &process)
Gather all of crash informations into a structured data dictionary.
virtual bool LoadPlatformBinaryAndSetup (Process *process, lldb::addr_t addr, bool notify)
Detect a binary in memory that will determine which Platform and DynamicLoader should be used in this target/process, and update the Platform/DynamicLoader.
virtual CompilerType GetSiginfoType (const llvm::Triple &triple)
virtual lldb::StopInfoSP GetStopInfoFromSiginfo (Thread &thread)
virtual Args GetExtraStartupCommands ()
void SetLocateModuleCallback (LocateModuleCallback callback)
Set locate module callback.
LocateModuleCallback GetLocateModuleCallback () const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
virtual llvm::StringRef GetPluginName ()=0
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Protected Member Functions
lldb_private::Status EvaluateLibdlExpression (lldb_private::Process *process, const char *expr_cstr, llvm::StringRef expr_prefix, lldb::ValueObjectSP &result_valobj_sp)
std::unique_ptr< lldb_private::UtilityFunction > MakeLoadImageUtilityFunction (lldb_private::ExecutionContext &exe_ctx, lldb_private::Status &error)
virtual llvm::StringRef GetLibdlFunctionDeclarations (lldb_private::Process *process)
Protected Member Functions inherited from lldb_private::Platform
lldb::ProcessSP DoConnectProcess (llvm::StringRef connect_url, llvm::StringRef plugin_name, Debugger &debugger, Stream *stream, Target *target, Status &error)
Private implementation of connecting to a process.
Status GetCachedExecutable (ModuleSpec &module_spec, lldb::ModuleSP &module_sp)
virtual Status DownloadModuleSlice (const FileSpec &src_file_spec, const uint64_t src_offset, const uint64_t src_size, const FileSpec &dst_file_spec)
virtual Status DownloadSymbolFile (const lldb::ModuleSP &module_sp, const FileSpec &dst_file_spec)
virtual const char * GetCacheHostname ()
Protected Attributes
std::unique_ptr< lldb_private::OptionGroupPlatformRSync > m_option_group_platform_rsync
std::unique_ptr< lldb_private::OptionGroupPlatformSSH > m_option_group_platform_ssh
std::unique_ptr< lldb_private::OptionGroupPlatformCaching > m_option_group_platform_caching
std::map< lldb_private::CommandInterpreter *, std::unique_ptr< lldb_private::OptionGroupOptions > > m_options
Protected Attributes inherited from lldb_private::RemoteAwarePlatform
lldb::PlatformSP m_remote_platform_sp
Protected Attributes inherited from lldb_private::Platform
bool m_is_host
bool m_os_version_set_while_connected
bool m_system_arch_set_while_connected
std::string m_sdk_sysroot
std::string m_sdk_build
FileSpec m_working_dir
std::string m_hostname
llvm::VersionTuple m_os_version
ArchSpec m_system_arch
std::mutex m_mutex
size_t m_max_uid_name_len
size_t m_max_gid_name_len
bool m_supports_rsync
std::string m_rsync_opts
std::string m_rsync_prefix
bool m_supports_ssh
std::string m_ssh_opts
bool m_ignores_remote_hostname
std::string m_local_cache_directory
std::vector< ConstString > m_trap_handlers
bool m_calculated_trap_handlers
const std::unique_ptr< ModuleCache > m_module_cache
LocateModuleCallback m_locate_module_callback
Private Member Functions
PlatformPOSIX (const PlatformPOSIX &)=delete
const PlatformPOSIX & operator= (const PlatformPOSIX &)=delete
Additional Inherited Members
Public Types inherited from lldb_private::Platform
typedef std::function< Status(const ModuleSpec &module_spec, FileSpec &module_file_spec, FileSpec &symbol_file_spec)> LocateModuleCallback
Static Public Member Functions inherited from lldb_private::Platform
static void Initialize ()
static void Terminate ()
static PlatformProperties & GetGlobalPlatformProperties ()
static lldb::PlatformSP GetHostPlatform ()
Get the native host platform plug-in.
static const char * GetHostPlatformName ()
static void SetHostPlatform (const lldb::PlatformSP &platform_sp)
static lldb::PlatformSP Create (llvm::StringRef name)
static ArchSpec GetAugmentedArchSpec (Platform *platform, llvm::StringRef triple)
Augments the triple either with information from platform or the host system (if platform is null).
Protected Types inherited from lldb_private::Platform
typedef std::map< uint32_t, ConstString > IDToNameMap
Static Protected Member Functions inherited from lldb_private::Platform
static std::vector< ArchSpec > CreateArchList (llvm::ArrayRef< llvm::Triple::ArchType > archs, llvm::Triple::OSType os)
Create a list of ArchSpecs with the given OS and a architectures.
Detailed Description
Definition at line 18 of file PlatformPOSIX.h.
Constructor & Destructor Documentation
PlatformPOSIX() [1/2]
PlatformPOSIX::PlatformPOSIX (bool is_host)
Default Constructor.
Definition at line 42 of file PlatformPOSIX.cpp.
References m_option_group_platform_caching, m_option_group_platform_rsync, and m_option_group_platform_ssh.
Referenced by operator=(), lldb_private::platform_aix::PlatformAIX::PlatformAIX(), lldb_private::platform_freebsd::PlatformFreeBSD::PlatformFreeBSD(), lldb_private::platform_linux::PlatformLinux::PlatformLinux(), lldb_private::platform_netbsd::PlatformNetBSD::PlatformNetBSD(), lldb_private::platform_openbsd::PlatformOpenBSD::PlatformOpenBSD(), and PlatformPOSIX().
~PlatformPOSIX()
PlatformPOSIX::~PlatformPOSIX () override default
Destructor.
The destructor is virtual since this class is designed to be inherited from by the plug-in instance.
References error(), and UINT32_MAX.
PlatformPOSIX() [2/2]
PlatformPOSIX::PlatformPOSIX (const PlatformPOSIX &) private delete
References PlatformPOSIX().
Member Function Documentation
Attach()
lldb::ProcessSP PlatformPOSIX::Attach (lldb_private::ProcessAttachInfo & attach_info, lldb_private::Debugger & debugger, lldb_private::Target * target, lldb_private::Status & error) override virtual
Attach to an existing process using a process ID.
Each platform subclass needs to implement this function and attempt to attach to the process with the process ID of pid. The platform subclass should return an appropriate ProcessSP subclass that is attached to the process, or an empty shared pointer with an appropriate error.
Returns
An appropriate ProcessSP containing a valid shared pointer to the default Process subclass for the platform that is attached to the process, or an empty shared pointer with an appropriate error fill into the error object.
Implements lldb_private::Platform.
Definition at line 369 of file PlatformPOSIX.cpp.
References lldb_private::Target::CreateProcess(), lldb_private::TargetList::CreateTarget(), lldb_private::eLoadDependentsNo, error(), lldb_private::Status::FromErrorString(), lldb_private::Target::GetExecutableModule(), lldb_private::ProcessInfo::GetHijackListener(), lldb_private::ProcessAttachInfo::GetListenerForProcess(), lldb_private::GetLog(), lldb_private::ProcessInfo::GetShadowListener(), lldb_private::Debugger::GetTargetList(), lldb_private::Platform::IsHost(), LLDB_LOGF, lldb_private::RemoteAwarePlatform::m_remote_platform_sp, lldb_private::Listener::MakeListener(), lldb_private::Platform, and lldb_private::ProcessInfo::SetHijackListener().
Referenced by lldb_private::PlatformAppleSimulator::DebugProcess().
CalculateTrapHandlerSymbolNames()
void PlatformPOSIX::CalculateTrapHandlerSymbolNames () override virtual
Ask the Platform subclass to fill in the list of trap handler names.
For most Unix user process environments, this will be a single function name, _sigtramp. More specialized environments may have additional handler names. The unwinder code needs to know when a trap handler is on the stack because the unwind rules for the frame that caused the trap are different.
The base class Platform ivar m_trap_handlers should be updated by the Platform subclass when this method is called. If there are no predefined trap handlers, this method may be a no-op.
Implements lldb_private::Platform.
Definition at line 508 of file PlatformPOSIX.cpp.
References lldb_private::Platform::m_trap_handlers.
ConnectRemote()
Status PlatformPOSIX::ConnectRemote (lldb_private::Args & args) override virtual
Reimplemented from lldb_private::Platform.
Definition at line 307 of file PlatformPOSIX.cpp.
References lldb_private::platform_gdb_server::PlatformRemoteGDBServer::CreateInstance(), error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::PluginInterface::GetPluginName(), lldb_private::Platform::IsHost(), m_option_group_platform_caching, m_option_group_platform_rsync, m_option_group_platform_ssh, lldb_private::RemoteAwarePlatform::m_remote_platform_sp, lldb_private::Platform::SetIgnoresRemoteHostname(), lldb_private::Platform::SetLocalCacheDirectory(), lldb_private::Platform::SetRSyncOpts(), lldb_private::Platform::SetRSyncPrefix(), lldb_private::Platform::SetSSHOpts(), lldb_private::Platform::SetSupportsRSync(), and lldb_private::Platform::SetSupportsSSH().
DebugProcess()
lldb::ProcessSP PlatformPOSIX::DebugProcess (lldb_private::ProcessLaunchInfo & launch_info, lldb_private::Debugger & debugger, lldb_private::Target & target, lldb_private::Status & error) override virtual
Subclasses do not need to implement this function as it uses the Platform::LaunchProcess() followed by Platform::Attach ().
Remote platforms will want to subclass this function in order to be able to intercept STDIO and possibly launch a separate process that will debug the debuggee.
Reimplemented from lldb_private::Platform.
Definition at line 425 of file PlatformPOSIX.cpp.
References lldb_private::StreamString::Clear(), lldb_private::Target::CreateProcess(), lldb_private::FileAction::Dump(), error(), lldb_private::Status::FromErrorString(), lldb_private::StreamString::GetData(), lldb_private::ProcessLaunchInfo::GetFileActionAtIndex(), lldb_private::ProcessLaunchInfo::GetFlags(), lldb_private::ProcessInfo::GetHijackListener(), lldb_private::ProcessInfo::GetListener(), lldb_private::GetLog(), lldb_private::ProcessLaunchInfo::GetPTY(), lldb_private::ProcessInfo::GetShadowListener(), lldb_private::PseudoTerminal::invalid_fd, lldb_private::Platform::IsHost(), LLDB_LOG, lldb_private::RemoteAwarePlatform::m_remote_platform_sp, lldb_private::Platform, lldb_private::PseudoTerminal::ReleasePrimaryFileDescriptor(), lldb_private::Flags::Set(), and lldb_private::ProcessLaunchInfo::SetLaunchInSeparateProcessGroup().
DisconnectRemote()
Status PlatformPOSIX::DisconnectRemote () override virtual
Reimplemented from lldb_private::Platform.
Definition at line 352 of file PlatformPOSIX.cpp.
References error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::PluginInterface::GetPluginName(), lldb_private::Platform::IsHost(), and lldb_private::RemoteAwarePlatform::m_remote_platform_sp.
DoLoadImage()
uint32_t PlatformPOSIX::DoLoadImage (lldb_private::Process * process, const lldb_private::FileSpec & remote_file, const std::vector< std::string > * paths, lldb_private::Status & error, lldb_private::FileSpec * loaded_image) override virtual
Reimplemented from lldb_private::Platform.
Definition at line 638 of file PlatformPOSIX.cpp.
References lldb::eBasicTypeChar, lldb::eBasicTypeVoid, error(), lldb_private::Status::FromErrorStringWithFormat(), and lldb_private::Value::Scalar.
EvaluateLibdlExpression()
Status PlatformPOSIX::EvaluateLibdlExpression (lldb_private::Process * process, const char * expr_cstr, llvm::StringRef expr_prefix, lldb::ValueObjectSP & result_valobj_sp) protected
Definition at line 512 of file PlatformPOSIX.cpp.
References lldb_private::DynamicLoader::CanLoadImage(), lldb_private::eExecutionPolicyAlways, lldb::eExpressionCompleted, lldb::eLanguageTypeC_plus_plus, error(), lldb_private::UserExpression::Evaluate(), lldb_private::Status::FromErrorString(), lldb_private::Process::GetDynamicLoader(), lldb_private::ThreadList::GetExpressionExecutionThread(), lldb_private::Process::GetThreadList(), lldb_private::ProcessProperties::GetUtilityExpressionTimeout(), lldb_private::EvaluateExpressionOptions::SetExecutionPolicy(), lldb_private::EvaluateExpressionOptions::SetIgnoreBreakpoints(), lldb_private::EvaluateExpressionOptions::SetLanguage(), lldb_private::EvaluateExpressionOptions::SetTimeout(), lldb_private::EvaluateExpressionOptions::SetTrapExceptions(), lldb_private::EvaluateExpressionOptions::SetUnwindOnError(), and lldb_private::Status.
GetConnectionOptions()
lldb_private::OptionGroupOptions * PlatformPOSIX::GetConnectionOptions (lldb_private::CommandInterpreter & interpreter) override virtual
Reimplemented from lldb_private::Platform.
Definition at line 54 of file PlatformPOSIX.cpp.
References m_option_group_platform_caching, m_option_group_platform_rsync, m_option_group_platform_ssh, and m_options.
GetFile()
lldb_private::Status PlatformPOSIX::GetFile (const lldb_private::FileSpec & source, const lldb_private::FileSpec & destination) override virtual
Reimplemented from lldb_private::Platform.
Definition at line 158 of file PlatformPOSIX.cpp.
References lldb_private::RemoteAwarePlatform::CloseFile(), lldb_private::File::eOpenOptionCanCreate, lldb_private::File::eOpenOptionReadOnly, lldb_private::File::eOpenOptionTruncate, lldb_private::File::eOpenOptionWriteOnly, error(), lldb_private::Status::FromErrorString(), lldb_private::StreamString::GetData(), lldb_private::Platform::GetFile(), lldb_private::RemoteAwarePlatform::GetFilePermissions(), lldb_private::Platform::GetIgnoresRemoteHostname(), lldb_private::FileCache::GetInstance(), lldb_private::GetLog(), lldb_private::FileSpec::GetPath(), lldb_private::Platform::GetRSyncOpts(), lldb_private::Platform::GetRSyncPrefix(), lldb_private::Platform::GetSupportsRSync(), lldb_private::Platform::IsHost(), LLDB_LOGF, lldb_private::RemoteAwarePlatform::m_remote_platform_sp, lldb_private::RemoteAwarePlatform::OpenFile(), lldb_private::Platform, lldb_private::Stream::Printf(), lldb_private::RemoteAwarePlatform::ReadFile(), lldb_private::Host::RunShellCommand(), lldb_private::RemoteAwarePlatform::RunShellCommand(), lldb_private::Status, UINT64_MAX, and lldb_private::RemoteAwarePlatform::WriteFile().
GetFullNameForDylib()
ConstString PlatformPOSIX::GetFullNameForDylib (lldb_private::ConstString basename) override virtual
Reimplemented from lldb_private::Platform.
Definition at line 950 of file PlatformPOSIX.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormat(), and LLDB_INVALID_IMAGE_TOKEN.
GetLibdlFunctionDeclarations()
llvm::StringRef PlatformPOSIX::GetLibdlFunctionDeclarations (lldb_private::Process * process) protected virtual
Reimplemented in lldb_private::platform_android::PlatformAndroid.
Definition at line 946 of file PlatformPOSIX.cpp.
References LLDB_INVALID_IMAGE_TOKEN.
Referenced by MakeLoadImageUtilityFunction().
GetPlatformSpecificConnectionInformation()
std::string PlatformPOSIX::GetPlatformSpecificConnectionInformation () override virtual
Reimplemented from lldb_private::Platform.
Definition at line 272 of file PlatformPOSIX.cpp.
References lldb_private::Platform::GetIgnoresRemoteHostname(), lldb_private::Platform::GetLocalCacheDirectory(), lldb_private::Platform::GetRSyncOpts(), lldb_private::Platform::GetRSyncPrefix(), lldb_private::StreamString::GetSize(), lldb_private::Platform::GetSSHOpts(), lldb_private::StreamString::GetString(), lldb_private::Platform::GetSupportsRSync(), lldb_private::Platform::GetSupportsSSH(), lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
GetRemoteUnixSignals()
const lldb::UnixSignalsSP & PlatformPOSIX::GetRemoteUnixSignals () override virtual
Reimplemented from lldb_private::Platform.
Definition at line 301 of file PlatformPOSIX.cpp.
References lldb_private::Platform::GetRemoteUnixSignals(), lldb_private::Platform::IsRemote(), and lldb_private::RemoteAwarePlatform::m_remote_platform_sp.
MakeLoadImageUtilityFunction()
std::unique_ptr< UtilityFunction > PlatformPOSIX::MakeLoadImageUtilityFunction (lldb_private::ExecutionContext & exe_ctx, lldb_private::Status & error) protected
Definition at line 553 of file PlatformPOSIX.cpp.
References lldb_private::Target::CreateUtilityFunction(), lldb::eLanguageTypeC_plus_plus, error(), lldb_private::Status::FromErrorStringWithFormat(), GetLibdlFunctionDeclarations(), lldb_private::ExecutionContext::GetProcessSP(), and lldb_private::Process::GetTarget().
operator=()
const PlatformPOSIX & PlatformPOSIX::operator= (const PlatformPOSIX &) private delete
References PlatformPOSIX().
PutFile()
lldb_private::Status PlatformPOSIX::PutFile (const lldb_private::FileSpec & source, const lldb_private::FileSpec & destination, uint32_t uid = UINT32_MAX, uint32_t gid = UINT32_MAX) override virtual
Reimplemented from lldb_private::Platform.
Definition at line 92 of file PlatformPOSIX.cpp.
References chown_file(), lldb_private::Status::FromErrorString(), lldb_private::StreamString::GetData(), lldb_private::RemoteAwarePlatform::GetHostname(), lldb_private::Platform::GetIgnoresRemoteHostname(), lldb_private::GetLog(), lldb_private::FileSpec::GetPath(), lldb_private::Platform::GetRSyncOpts(), lldb_private::Platform::GetRSyncPrefix(), lldb_private::Platform::GetSupportsRSync(), lldb_private::Platform::IsHost(), LLDB_LOGF, lldb_private::RemoteAwarePlatform::m_remote_platform_sp, lldb_private::Platform, lldb_private::Stream::Printf(), lldb_private::Platform::PutFile(), lldb_private::Host::RunShellCommand(), lldb_private::RemoteAwarePlatform::RunShellCommand(), lldb_private::Status, and UINT32_MAX.
Referenced by lldb_private::PlatformDarwin::PutFile().
UnloadImage()
Status PlatformPOSIX::UnloadImage (lldb_private::Process * process, uint32_t image_token) override virtual
Reimplemented from lldb_private::Platform.
Definition at line 917 of file PlatformPOSIX.cpp.
References lldb_private::Status::AsCString(), error(), lldb_private::Status::FromErrorStringWithFormat(), and LLDB_INVALID_IMAGE_TOKEN.
Member Data Documentation
m_option_group_platform_caching
std::unique_ptr<lldb_private::OptionGroupPlatformCaching> PlatformPOSIX::m_option_group_platform_caching protected
Definition at line 78 of file PlatformPOSIX.h.
Referenced by ConnectRemote(), GetConnectionOptions(), and PlatformPOSIX().
m_option_group_platform_rsync
std::unique_ptr<lldb_private::OptionGroupPlatformRSync> PlatformPOSIX::m_option_group_platform_rsync protected
Definition at line 74 of file PlatformPOSIX.h.
Referenced by ConnectRemote(), GetConnectionOptions(), and PlatformPOSIX().
m_option_group_platform_ssh
std::unique_ptr<lldb_private::OptionGroupPlatformSSH> PlatformPOSIX::m_option_group_platform_ssh protected
Definition at line 76 of file PlatformPOSIX.h.
Referenced by ConnectRemote(), GetConnectionOptions(), and PlatformPOSIX().
m_options
std::map<lldb_private::CommandInterpreter *, std::unique_ptr<lldb_private::OptionGroupOptions> > PlatformPOSIX::m_options protected
Definition at line 82 of file PlatformPOSIX.h.
Referenced by GetConnectionOptions().
The documentation for this class was generated from the following files:
PlatformPOSIX.h
PlatformPOSIX.cpp