LLDB: lldb_private::Symtab::FileRangeToIndexMapCompare Class Reference
lldb_private::Symtab::FileRangeToIndexMapCompare Class Reference
#include <Symtab.h>
Public Member Functions
FileRangeToIndexMapCompare (const Symtab &symtab)
bool operator() (const uint32_t a_data, const uint32_t b_data) const
Private Member Functions
int rank (const uint32_t data) const
Private Attributes
const Symtab & m_symtab
Detailed Description
Definition at line 246 of file Symtab.h.
Constructor & Destructor Documentation
FileRangeToIndexMapCompare()
lldb_private::Symtab::FileRangeToIndexMapCompare::FileRangeToIndexMapCompare (const Symtab & symtab) inline
Definition at line 248 of file Symtab.h.
References m_symtab, and lldb_private::Symtab::Symtab().
Member Function Documentation
operator()()
bool lldb_private::Symtab::FileRangeToIndexMapCompare::operator() (const uint32_t a_data, const uint32_t b_data) const inline
Definition at line 249 of file Symtab.h.
References rank().
rank()
int lldb_private::Symtab::FileRangeToIndexMapCompare::rank (const uint32_t data) const inline private
Definition at line 255 of file Symtab.h.
References lldb_private::Symbol::IsDebug(), lldb_private::Symbol::IsExternal(), lldb_private::Symbol::IsWeak(), and m_symtab.
Referenced by operator()().
Member Data Documentation
m_symtab
const Symtab& lldb_private::Symtab::FileRangeToIndexMapCompare::m_symtab private
Definition at line 265 of file Symtab.h.
Referenced by FileRangeToIndexMapCompare(), and rank().
The documentation for this class was generated from the following file:
Symtab.h