LLDB: lldb_private::AppleObjCRuntimeV2::DynamicClassInfoExtractor Class Reference
lldb_private::AppleObjCRuntimeV2::DynamicClassInfoExtractor Class Reference
We can read the class info from the Objective-C runtime using gdb_objc_realized_classes, objc_copyRealizedClassList or objc_getRealizedClassList_trylock.
Classes
struct UtilityFunctionHelper
Public Member Functions
DynamicClassInfoExtractor (AppleObjCRuntimeV2 &runtime)
DescriptorMapUpdateResult UpdateISAToDescriptorMap (RemoteNXMapTable &hash_table)
Public Member Functions inherited from lldb_private::AppleObjCRuntimeV2::ClassInfoExtractor
ClassInfoExtractor (AppleObjCRuntimeV2 &runtime)
std::mutex & GetMutex ()
Private Types
enum Helper { gdb_objc_realized_classes , objc_copyRealizedClassList , objc_getRealizedClassList_trylock }
Private Member Functions
Helper ComputeHelper (ExecutionContext &exe_ctx) const
Compute which helper to use.
UtilityFunction * GetClassInfoUtilityFunction (ExecutionContext &exe_ctx, Helper helper)
lldb::addr_t & GetClassInfoArgs (Helper helper)
std::unique_ptr< UtilityFunction > GetClassInfoUtilityFunctionImpl (ExecutionContext &exe_ctx, Helper helper, std::string code, std::string name)
Private Attributes
UtilityFunctionHelper m_gdb_objc_realized_classes_helper
UtilityFunctionHelper m_objc_copyRealizedClassList_helper
UtilityFunctionHelper m_objc_getRealizedClassList_trylock_helper
Additional Inherited Members
Protected Attributes inherited from lldb_private::AppleObjCRuntimeV2::ClassInfoExtractor
AppleObjCRuntimeV2 & m_runtime
The lifetime of this object is tied to that of the runtime.
std::mutex m_mutex
Detailed Description
We can read the class info from the Objective-C runtime using gdb_objc_realized_classes, objc_copyRealizedClassList or objc_getRealizedClassList_trylock.
The RealizedClassList variants are preferred because they include lazily named classes, but they are not always available or safe to call.
We potentially need more than one helper for the same process, because we may need to use gdb_objc_realized_classes until dyld is initialized and then switch over to objc_copyRealizedClassList or objc_getRealizedClassList_trylock for lazily named classes.
Definition at line 333 of file AppleObjCRuntimeV2.h.
Member Enumeration Documentation
Helper
enum lldb_private::AppleObjCRuntimeV2::DynamicClassInfoExtractor::Helper private
Enumerator
gdb_objc_realized_classes
objc_copyRealizedClassList
objc_getRealizedClassList_trylock
Definition at line 342 of file AppleObjCRuntimeV2.h.
Constructor & Destructor Documentation
DynamicClassInfoExtractor()
lldb_private::AppleObjCRuntimeV2::DynamicClassInfoExtractor::DynamicClassInfoExtractor (AppleObjCRuntimeV2 & runtime) inline
Definition at line 335 of file AppleObjCRuntimeV2.h.
References lldb_private::AppleObjCRuntimeV2::AppleObjCRuntimeV2(), and lldb_private::AppleObjCRuntimeV2::ClassInfoExtractor::ClassInfoExtractor().
Member Function Documentation
ComputeHelper()
AppleObjCRuntimeV2::DynamicClassInfoExtractor::Helper AppleObjCRuntimeV2::DynamicClassInfoExtractor::ComputeHelper (ExecutionContext & exe_ctx) const private
Compute which helper to use.
If dyld is not yet fully initialized we must use gdb_objc_realized_classes. Otherwise, we prefer objc_getRealizedClassList_trylock and objc_copyRealizedClassList respectively, depending on availability.
Definition at line 1871 of file AppleObjCRuntimeV2.cpp.
References g_get_dynamic_class_info2_body, g_get_dynamic_class_info2_name, GetClassInfoUtilityFunctionImpl(), m_objc_copyRealizedClassList_helper, and objc_copyRealizedClassList.
GetClassInfoArgs()
lldb::addr_t & AppleObjCRuntimeV2::DynamicClassInfoExtractor::GetClassInfoArgs (Helper helper) private
Definition at line 1858 of file AppleObjCRuntimeV2.cpp.
References g_get_dynamic_class_info_body, g_get_dynamic_class_info_name, gdb_objc_realized_classes, GetClassInfoUtilityFunctionImpl(), and m_gdb_objc_realized_classes_helper.
GetClassInfoUtilityFunction()
UtilityFunction * AppleObjCRuntimeV2::DynamicClassInfoExtractor::GetClassInfoUtilityFunction (ExecutionContext & exe_ctx, Helper helper) private
Definition at line 1826 of file AppleObjCRuntimeV2.cpp.
References objc_getRealizedClassList_trylock, lldb_private::ValueList::PushValue(), lldb_private::Value::Scalar, and lldb_private::Value::SetCompilerType().
GetClassInfoUtilityFunctionImpl()
std::unique_ptr< UtilityFunction > AppleObjCRuntimeV2::DynamicClassInfoExtractor::GetClassInfoUtilityFunctionImpl (ExecutionContext & exe_ctx, Helper helper, std::string code, std::string name) private
Definition at line 1761 of file AppleObjCRuntimeV2.cpp.
Referenced by ComputeHelper(), and GetClassInfoArgs().
UpdateISAToDescriptorMap()
AppleObjCRuntimeV2::DescriptorMapUpdateResult AppleObjCRuntimeV2::DynamicClassInfoExtractor::UpdateISAToDescriptorMap (RemoteNXMapTable & hash_table)
Definition at line 2010 of file AppleObjCRuntimeV2.cpp.
References error(), and lldb_private::Value::Scalar.
Member Data Documentation
m_gdb_objc_realized_classes_helper
UtilityFunctionHelper lldb_private::AppleObjCRuntimeV2::DynamicClassInfoExtractor::m_gdb_objc_realized_classes_helper private
Definition at line 367 of file AppleObjCRuntimeV2.h.
Referenced by GetClassInfoArgs().
m_objc_copyRealizedClassList_helper
UtilityFunctionHelper lldb_private::AppleObjCRuntimeV2::DynamicClassInfoExtractor::m_objc_copyRealizedClassList_helper private
Definition at line 368 of file AppleObjCRuntimeV2.h.
Referenced by ComputeHelper().
m_objc_getRealizedClassList_trylock_helper
UtilityFunctionHelper lldb_private::AppleObjCRuntimeV2::DynamicClassInfoExtractor::m_objc_getRealizedClassList_trylock_helper private
Definition at line 369 of file AppleObjCRuntimeV2.h.
The documentation for this class was generated from the following files:
AppleObjCRuntimeV2.h
AppleObjCRuntimeV2.cpp