LLDB: lldb_private::dil::FloatLiteralNode Class Reference
lldb_private::dil::FloatLiteralNode Class Reference
#include <DILAST.h>
Public Member Functions
FloatLiteralNode (uint32_t location, llvm::APFloat value)
llvm::Expected< lldb::ValueObjectSP > Accept (Visitor *v) const override
const llvm::APFloat & GetValue () const
Public Member Functions inherited from lldb_private::dil::ASTNode
ASTNode (uint32_t location, NodeKind kind)
virtual ~ASTNode ()=default
uint32_t GetLocation () const
NodeKind GetKind () const
Static Public Member Functions
static bool classof (const ASTNode &node)
Private Attributes
llvm::APFloat m_value
Detailed Description
Definition at line 223 of file DILAST.h.
Constructor & Destructor Documentation
FloatLiteralNode()
lldb_private::dil::FloatLiteralNode::FloatLiteralNode (uint32_t location, llvm::APFloat value) inline
Definition at line 225 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), lldb_private::dil::eFloatLiteralNode, and m_value.
Member Function Documentation
Accept()
llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::FloatLiteralNode::Accept (Visitor * v) const override virtual
Implements lldb_private::dil::ASTNode.
Definition at line 45 of file DILAST.cpp.
References lldb_private::dil::Visitor::Visit().
classof()
bool lldb_private::dil::FloatLiteralNode::classof (const ASTNode & node) inline static
Definition at line 233 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), lldb_private::dil::eFloatLiteralNode, and lldb_private::dil::ASTNode::GetKind().
GetValue()
const llvm::APFloat & lldb_private::dil::FloatLiteralNode::GetValue () const inline
Definition at line 231 of file DILAST.h.
References m_value.
Referenced by lldb_private::dil::Interpreter::Visit().
Member Data Documentation
m_value
llvm::APFloat lldb_private::dil::FloatLiteralNode::m_value private
Definition at line 238 of file DILAST.h.
Referenced by FloatLiteralNode(), and GetValue().
The documentation for this class was generated from the following files:
DILAST.h
DILAST.cpp