LLDB: lldb_private::plugin::dwarf::DWARFASTParser Class Reference
lldb_private::plugin::dwarf::DWARFASTParser Class Reference abstract
#include <DWARFASTParser.h>
Public Types
enum class Kind { DWARFASTParserClang }
Public Member Functions
DWARFASTParser (Kind kind)
virtual ~DWARFASTParser ()=default
virtual lldb::TypeSP ParseTypeFromDWARF (const SymbolContext &sc, const DWARFDIE &die, bool *type_is_new_ptr)=0
virtual ConstString ConstructDemangledNameFromDWARF (const DWARFDIE &die)=0
virtual Function * ParseFunctionFromDWARF (CompileUnit &comp_unit, const DWARFDIE &die, AddressRanges ranges)=0
virtual bool CompleteTypeFromDWARF (const DWARFDIE &die, Type *type, const CompilerType &compiler_type)=0
virtual CompilerDecl GetDeclForUIDFromDWARF (const DWARFDIE &die)=0
virtual CompilerDeclContext GetDeclContextForUIDFromDWARF (const DWARFDIE &die)=0
virtual CompilerDeclContext GetDeclContextContainingUIDFromDWARF (const DWARFDIE &die)=0
virtual void EnsureAllDIEsInDeclContextHaveBeenParsed (CompilerDeclContext decl_context)=0
virtual std::string GetDIEClassTemplateParams (DWARFDIE die)=0
lldb_private::Type * GetTypeForDIE (const DWARFDIE &die)
Kind GetKind () const
Static Public Member Functions
static std::optional< SymbolFile::ArrayInfo > ParseChildArrayInfo (const DWARFDIE &parent_die, const ExecutionContext *exe_ctx=nullptr)
static lldb::AccessType GetAccessTypeFromDWARF (uint32_t dwarf_accessibility)
Private Attributes
const Kind m_kind
Detailed Description
Definition at line 30 of file DWARFASTParser.h.
Member Enumeration Documentation
Kind
enum class lldb_private::plugin::dwarf::DWARFASTParser::Kind strong
Enumerator
DWARFASTParserClang
Definition at line 32 of file DWARFASTParser.h.
Constructor & Destructor Documentation
DWARFASTParser()
lldb_private::plugin::dwarf::DWARFASTParser::DWARFASTParser (Kind kind) inline
Definition at line 33 of file DWARFASTParser.h.
References m_kind.
Referenced by DWARFASTParserClang::classof(), and DWARFASTParserClang::DWARFASTParserClang().
~DWARFASTParser()
virtual lldb_private::plugin::dwarf::DWARFASTParser::~DWARFASTParser () virtual default
Member Function Documentation
CompleteTypeFromDWARF()
virtual bool lldb_private::plugin::dwarf::DWARFASTParser::CompleteTypeFromDWARF (const DWARFDIE & die, Type * type, const CompilerType & compiler_type) pure virtual
Implemented in DWARFASTParserClang.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::CompleteType().
ConstructDemangledNameFromDWARF()
virtual ConstString lldb_private::plugin::dwarf::DWARFASTParser::ConstructDemangledNameFromDWARF (const DWARFDIE & die) pure virtual
Implemented in DWARFASTParserClang.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::ConstructFunctionDemangledName().
EnsureAllDIEsInDeclContextHaveBeenParsed()
virtual void lldb_private::plugin::dwarf::DWARFASTParser::EnsureAllDIEsInDeclContextHaveBeenParsed (CompilerDeclContext decl_context) pure virtual
Implemented in DWARFASTParserClang.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::ParseDeclsForContext().
GetAccessTypeFromDWARF()
AccessType DWARFASTParser::GetAccessTypeFromDWARF (uint32_t dwarf_accessibility) static
Definition at line 129 of file DWARFASTParser.cpp.
References lldb::eAccessNone, lldb::eAccessPrivate, lldb::eAccessProtected, and lldb::eAccessPublic.
Referenced by DWARFASTParserClang::ParseInheritance().
GetDeclContextContainingUIDFromDWARF()
virtual CompilerDeclContext lldb_private::plugin::dwarf::DWARFASTParser::GetDeclContextContainingUIDFromDWARF (const DWARFDIE & die) pure virtual
Implemented in DWARFASTParserClang.
GetDeclContextForUIDFromDWARF()
virtual CompilerDeclContext lldb_private::plugin::dwarf::DWARFASTParser::GetDeclContextForUIDFromDWARF (const DWARFDIE & die) pure virtual
Implemented in DWARFASTParserClang.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::FindNamespace().
GetDeclForUIDFromDWARF()
virtual CompilerDecl lldb_private::plugin::dwarf::DWARFASTParser::GetDeclForUIDFromDWARF (const DWARFDIE & die) pure virtual
Implemented in DWARFASTParserClang.
GetDIEClassTemplateParams()
virtual std::string lldb_private::plugin::dwarf::DWARFASTParser::GetDIEClassTemplateParams (DWARFDIE die) pure virtual
Implemented in DWARFASTParserClang.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::FindDefinitionDIE().
GetKind()
Kind lldb_private::plugin::dwarf::DWARFASTParser::GetKind () const inline
Definition at line 71 of file DWARFASTParser.h.
References m_kind.
GetTypeForDIE()
Type * DWARFASTParser::GetTypeForDIE (const DWARFDIE & die)
Definition at line 104 of file DWARFASTParser.cpp.
References lldb_private::plugin::dwarf::DWARFAttributes::AttributeAtIndex(), lldb_private::plugin::dwarf::DWARFAttributes::ExtractFormValueAtIndex(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetAttributes(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetDWARF(), lldb_private::plugin::dwarf::DWARFFormValue::Reference(), and lldb_private::plugin::dwarf::DWARFAttributes::Size().
Referenced by DWARFASTParserClang::GetClangDeclForDIE().
ParseChildArrayInfo()
std::optional< SymbolFile::ArrayInfo > DWARFASTParser::ParseChildArrayInfo (const DWARFDIE & parent_die, const ExecutionContext * exe_ctx = nullptr) static
Definition at line 25 of file DWARFASTParser.cpp.
References lldb_private::plugin::dwarf::DWARFAttributes::AttributeAtIndex(), lldb_private::SymbolFile::ArrayInfo::bit_stride, lldb_private::SymbolFile::ArrayInfo::byte_stride, lldb_private::plugin::dwarf::DWARFDIE::children(), lldb_private::SymbolFile::ArrayInfo::element_orders, lldb::eNoDynamicValues, error(), lldb_private::plugin::dwarf::DWARFAttributes::ExtractFormValueAtIndex(), lldb_private::ExecutionContext::GetFrameSP(), lldb_private::plugin::dwarf::DWARFDIE::GetReferencedDIE(), lldb_private::plugin::dwarf::DWARFAttributes::Size(), and lldb_private::plugin::dwarf::DWARFFormValue::Unsigned().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::GetDynamicArrayInfoForUID(), and DWARFASTParserClang::ParseArrayType().
ParseFunctionFromDWARF()
virtual Function * lldb_private::plugin::dwarf::DWARFASTParser::ParseFunctionFromDWARF (CompileUnit & comp_unit, const DWARFDIE & die, AddressRanges ranges) pure virtual
Implemented in DWARFASTParserClang.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::ParseFunction().
ParseTypeFromDWARF()
virtual lldb::TypeSP lldb_private::plugin::dwarf::DWARFASTParser::ParseTypeFromDWARF (const SymbolContext & sc, const DWARFDIE & die, bool * type_is_new_ptr) pure virtual
Implemented in DWARFASTParserClang.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::ParseType().
Member Data Documentation
m_kind
const Kind lldb_private::plugin::dwarf::DWARFASTParser::m_kind private
Definition at line 74 of file DWARFASTParser.h.
Referenced by DWARFASTParser(), and GetKind().
The documentation for this class was generated from the following files:
DWARFASTParser.h
DWARFASTParser.cpp