LLDB: lldb_protocol::mcp::ServerInfoHandle Class Reference
lldb_protocol::mcp::ServerInfoHandle Class Reference
A handle that tracks the server info on disk and cleans up the disk record once it is no longer referenced.
#include <Server.h>
Public Member Functions
ServerInfoHandle (llvm::StringRef filename="")
~ServerInfoHandle ()
ServerInfoHandle (ServerInfoHandle &&other)
ServerInfoHandle & operator= (ServerInfoHandle &&other) noexcept
void Remove ()
Remove the file on disk, if one is tracked.
ServerInfoHandle (const ServerInfoHandle &)=delete
ServerIinfoHandle is not copyable.
ServerInfoHandle & operator= (const ServerInfoHandle &)=delete
Private Attributes
llvm::SmallString< 128 > m_filename
Detailed Description
A handle that tracks the server info on disk and cleans up the disk record once it is no longer referenced.
Definition at line 100 of file Server.h.
Constructor & Destructor Documentation
ServerInfoHandle() [1/3]
lldb_protocol::mcp::ServerInfoHandle::ServerInfoHandle (llvm::StringRef filename = "") explicit
References ServerInfoHandle().
Referenced by operator=(), operator=(), ServerInfoHandle(), ServerInfoHandle(), and ServerInfoHandle().
~ServerInfoHandle()
ServerInfoHandle::~ServerInfoHandle ()
Definition at line 31 of file Server.cpp.
References Remove().
ServerInfoHandle() [2/3]
ServerInfoHandle::ServerInfoHandle (ServerInfoHandle && other)
Definition at line 33 of file Server.cpp.
References ServerInfoHandle().
ServerInfoHandle() [3/3]
lldb_protocol::mcp::ServerInfoHandle::ServerInfoHandle (const ServerInfoHandle &) delete
ServerIinfoHandle is not copyable.
References ServerInfoHandle().
Member Function Documentation
operator=() [1/2]
ServerInfoHandle & lldb_protocol::mcp::ServerInfoHandle::operator= (const ServerInfoHandle &) delete
References ServerInfoHandle().
operator=() [2/2]
ServerInfoHandle & ServerInfoHandle::operator= (ServerInfoHandle && other) noexcept
Definition at line 38 of file Server.cpp.
References m_filename, and ServerInfoHandle().
Remove()
void ServerInfoHandle::Remove ()
Remove the file on disk, if one is tracked.
Definition at line 43 of file Server.cpp.
References m_filename.
Referenced by ~ServerInfoHandle().
Member Data Documentation
m_filename
llvm::SmallString<128> lldb_protocol::mcp::ServerInfoHandle::m_filename private
Definition at line 118 of file Server.h.
Referenced by operator=(), and Remove().
The documentation for this class was generated from the following files:
Server.h
Server.cpp