LLDB: lldb_private::Address Class Reference
lldb_private::Address Class Reference
A section + offset based address class.
#include "lldb/Core/Address.h"
Classes
class ModulePointerAndOffsetLessThanFunctionObject
Public Types
enum DumpStyle {
DumpStyleInvalid , DumpStyleSectionNameOffset , DumpStyleSectionPointerOffset , DumpStyleFileAddress ,
DumpStyleModuleWithFileAddress , DumpStyleLoadAddress , DumpStyleResolvedDescription , DumpStyleResolvedDescriptionNoModule ,
DumpStyleResolvedDescriptionNoFunctionArguments , DumpStyleNoFunctionName , DumpStyleDetailedSymbolContext , DumpStyleResolvedPointerDescription
}
Dump styles allow the Address::Dump(Stream *,DumpStyle) const function to display Address contents in a variety of ways.
Public Member Functions
Address ()=default
Default constructor.
Address (const Address &rhs)
Copy constructor.
Address (const lldb::SectionSP &section_sp, lldb::addr_t offset)
Construct with a section pointer and offset.
Address (lldb::addr_t file_addr, const SectionList *section_list)
Construct with a virtual address and section list.
Address (lldb::addr_t abs_addr)
const Address & operator= (const Address &rhs)
Assignment operator.
void Clear ()
Clear the object's state.
bool GetDescription (Stream &s, Target &target, lldb::DescriptionLevel level) const
Write a description of this object to a Stream.
bool Dump (Stream *s, ExecutionContextScope *exe_scope, DumpStyle style, DumpStyle fallback_style=DumpStyleInvalid, uint32_t addr_byte_size=UINT32_MAX, bool all_ranges=false, std::optional< Stream::HighlightSettings > settings=std::nullopt) const
Dump a description of this object to a Stream.
AddressClass GetAddressClass () const
lldb::addr_t GetFileAddress () const
Get the file address.
lldb::addr_t GetLoadAddress (Target *target) const
Get the load address.
lldb::addr_t GetCallableLoadAddress (Target *target, bool is_indirect=false) const
Get the load address as a callable code load address.
lldb::addr_t GetOpcodeLoadAddress (Target *target, AddressClass addr_class=AddressClass::eInvalid) const
Get the load address as an opcode load address.
lldb::addr_t GetOffset () const
Get the section relative offset value.
bool IsSectionOffset () const
Check if an address is section offset.
bool IsValid () const
Check if the object state is valid.
size_t MemorySize () const
Get the memory cost of this object.
bool ResolveAddressUsingFileSections (lldb::addr_t addr, const SectionList *sections)
Resolve a file virtual address using a section list.
bool ResolveFunctionScope (lldb_private::SymbolContext &sym_ctx)
Resolve this address to its containing function.
bool SetLoadAddress (lldb::addr_t load_addr, Target *target, bool allow_section_end=false)
Set the address to represent load_addr.
bool SetOpcodeLoadAddress (lldb::addr_t load_addr, Target *target, AddressClass addr_class=AddressClass::eInvalid, bool allow_section_end=false)
bool SetCallableLoadAddress (lldb::addr_t load_addr, Target *target)
lldb::ModuleSP GetModule () const
Get accessor for the module for this address.
lldb::SectionSP GetSection () const
Get const accessor for the section.
bool SetOffset (lldb::addr_t offset)
Set accessor for the offset.
void SetRawAddress (lldb::addr_t addr)
bool Slide (int64_t offset)
void SetSection (const lldb::SectionSP &section_sp)
Set accessor for the section.
void ClearSection ()
uint32_t CalculateSymbolContext (SymbolContext *sc, lldb::SymbolContextItem resolve_scope=lldb::eSymbolContextEverything) const
Reconstruct a symbol context from an address.
lldb::ModuleSP CalculateSymbolContextModule () const
CompileUnit * CalculateSymbolContextCompileUnit () const
Function * CalculateSymbolContextFunction () const
Block * CalculateSymbolContextBlock () const
Symbol * CalculateSymbolContextSymbol () const
bool CalculateSymbolContextLineEntry (LineEntry &line_entry) const
bool SectionWasDeleted () const
Static Public Member Functions
static int CompareFileAddress (const Address &lhs, const Address &rhs)
Compare two Address objects.
static int CompareLoadAddress (const Address &lhs, const Address &rhs, Target *target)
static int CompareModulePointerAndOffset (const Address &lhs, const Address &rhs)
Protected Member Functions
bool SectionWasDeletedPrivate () const
Protected Attributes
lldb::SectionWP m_section_wp
The section for the address, can be NULL.
lldb::addr_t m_offset = LLDB_INVALID_ADDRESS
Offset into section if m_section_wp is valid...
Detailed Description
A section + offset based address class.
The Address class allows addresses to be relative to a section that can move during runtime due to images (executables, shared libraries, bundles, frameworks) being loaded at different addresses than the addresses found in the object file that represents them on disk. There are currently two types of addresses for a section:
file addresses
load addresses
File addresses represent the virtual addresses that are in the "on disk" object files. These virtual addresses are converted to be relative to unique sections scoped to the object file so that when/if the addresses slide when the images are loaded/unloaded in memory, we can easily track these changes without having to update every object (compile unit ranges, line tables, function address ranges, lexical block and inlined subroutine address ranges, global and static variables) each time an image is loaded or unloaded.
Load addresses represent the virtual addresses where each section ends up getting loaded at runtime. Before executing a program, it is common for all of the load addresses to be unresolved. When a DynamicLoader plug-in receives notification that shared libraries have been loaded/unloaded, the load addresses of the main executable and any images (shared libraries) will be resolved/unresolved. When this happens, breakpoints that are in one of these sections can be set/cleared.
Definition at line 62 of file Address.h.
Member Enumeration Documentation
DumpStyle
enum lldb_private::Address::DumpStyle
Dump styles allow the Address::Dump(Stream *,DumpStyle) const function to display Address contents in a variety of ways.
Enumerator
DumpStyleInvalid
Invalid dump style.
DumpStyleSectionNameOffset
Display as the section name + offset.
// address for printf in libSystem.B.dylib as a section name + offset
libSystem.B.dylib.__TEXT.__text + 0x0005cfdf
DumpStyleSectionPointerOffset
Display as the section pointer + offset (debug output).
// address for printf in libSystem.B.dylib as a section pointer +
offset (lldb::Section *)0x35cc50 + 0x000000000005cfdf
DumpStyleFileAddress
Display as the file address (if any).
// address for printf in libSystem.B.dylib as a file address
0x000000000005dcff
DumpStyleModuleWithFileAddress
Display as the file address with the module name prepended (if any).
// address for printf in libSystem.B.dylib as a file address
libSystem.B.dylib[0x000000000005dcff]
DumpStyleLoadAddress
Display as the load address (if resolved).
// address for printf in libSystem.B.dylib as a load address
0x00007fff8306bcff
DumpStyleResolvedDescription
Display the details about what an address resolves to.
This can be anything from a symbol context summary (module, function/symbol, and file and line), to information about what the pointer points to if the address is in a section (section of pointers, c strings, etc).
DumpStyleResolvedDescriptionNoModule
DumpStyleResolvedDescriptionNoFunctionArguments
DumpStyleNoFunctionName
Elide the function name; display an offset into the current function.
Used primarily in disassembly symbolication
DumpStyleDetailedSymbolContext
Detailed symbol context information for an address for all symbol context members.
DumpStyleResolvedPointerDescription
Dereference a pointer at the current address and then lookup the dereferenced address using DumpStyleResolvedDescription.
Definition at line 66 of file Address.h.
Constructor & Destructor Documentation
Address() [1/5]
lldb_private::Address::Address () default
Default constructor.
Initialize with a invalid section (NULL) and an invalid offset (LLDB_INVALID_ADDRESS).
Referenced by Address(), CompareFileAddress(), CompareLoadAddress(), CompareModulePointerAndOffset(), Dump(), MemorySize(), lldb_private::Address::ModulePointerAndOffsetLessThanFunctionObject::operator()(), and operator=().
Address() [2/5]
lldb_private::Address::Address (const Address & rhs) inline
Copy constructor.
Makes a copy of the another Address object rhs.
Parameters
[in] rhs A const Address object reference to copy.
Definition at line 130 of file Address.h.
References Address(), m_offset, and m_section_wp.
Address() [3/5]
lldb_private::Address::Address (const lldb::SectionSP & section_sp, lldb::addr_t offset) inline
Construct with a section pointer and offset.
Initialize the address with the supplied section and offset.
Parameters
[in] section_sp A section pointer to a valid lldb::Section, or NULL if the address doesn't have a section or will get resolved later.
[in] offset The offset in bytes into section.
Definition at line 143 of file Address.h.
References m_offset, and m_section_wp.
Address() [4/5]
Address::Address (lldb::addr_t file_addr, const SectionList * section_list)
Construct with a virtual address and section list.
Initialize and resolve the address with the supplied virtual address file_addr.
Parameters
[in] file_addr A virtual file address.
[in] section_list A list of sections, one of which may contain the file_addr.
Definition at line 236 of file Address.cpp.
References m_section_wp, and ResolveAddressUsingFileSections().
Address() [5/5]
Address::Address (lldb::addr_t abs_addr)
Definition at line 234 of file Address.cpp.
References m_offset, and m_section_wp.
Member Function Documentation
CalculateSymbolContext()
uint32_t Address::CalculateSymbolContext (SymbolContext * sc, lldb::SymbolContextItem resolve_scope = lldb::eSymbolContextEverything) const
Reconstruct a symbol context from an address.
This class doesn't inherit from SymbolContextScope because many address objects have short lifespans. Address objects that are section offset can reconstruct their symbol context by looking up the address in the module found in the section.
See also
SymbolContextScope::CalculateSymbolContext(SymbolContext*)
Definition at line 820 of file Address.cpp.
References lldb_private::SymbolContext::Clear(), GetSection(), and lldb_private::SymbolContext::module_sp.
Referenced by lldb_private::SearchFilterByModuleListAndCU::AddressPasses(), CalculateSymbolContext(), lldb_private::ScriptedFrame::Create(), lldb_private::ScriptedFrameProvider::GetFrameAtIndex(), lldb_private::LineEntry::GetSameLineContiguousAddressRange(), lldb_private::ScriptedThread::LoadArtificialStackFrames(), lldb::SBThreadPlan::QueueThreadPlanForStepInRange(), lldb::SBThreadPlan::QueueThreadPlanForStepOverRange(), ResolveFunctionScope(), lldb_private::CompileUnit::ResolveSymbolContext(), lldb_private::ThreadPlanStepOut::SetupReturnAddress(), and lldb_private::ThreadPlanStepOverRange::ShouldStop().
CalculateSymbolContextBlock()
Block * Address::CalculateSymbolContextBlock () const
Definition at line 874 of file Address.cpp.
References lldb_private::SymbolContext::block, GetSection(), and lldb_private::SymbolContext::module_sp.
Referenced by lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint().
CalculateSymbolContextCompileUnit()
CompileUnit * Address::CalculateSymbolContextCompileUnit () const
Definition at line 846 of file Address.cpp.
References lldb_private::SymbolContext::comp_unit, GetSection(), and lldb_private::SymbolContext::module_sp.
Referenced by lldb_private::CPPLanguageRuntime::FindLibCppStdFunctionCallableInfo().
CalculateSymbolContextFunction()
Function * Address::CalculateSymbolContextFunction () const
Definition at line 860 of file Address.cpp.
References lldb_private::SymbolContext::function, GetSection(), and lldb_private::SymbolContext::module_sp.
Referenced by CommandObjectSourceList::DoExecute(), CommandObjectSourceInfo::DumpLinesInFunctions(), ExtractDestroyFunction(), lldb_private::Module::FindAddressesForLine(), lldb_private::IndirectCallEdge::GetCallee(), lldb_private::Symbol::GetPrologueByteSize(), lldb_private::DirectCallEdge::ParseSymbolFileAndResolve(), lldb_private::CompileUnit::ResolveSymbolContext(), lldb_private::ThreadPlanStepOverRange::ShouldStop(), and ValueObjectVTableChild::UpdateValue().
CalculateSymbolContextLineEntry()
bool Address::CalculateSymbolContextLineEntry (LineEntry & line_entry) const
Definition at line 902 of file Address.cpp.
References lldb_private::LineEntry::Clear(), GetSection(), lldb_private::LineEntry::IsValid(), lldb_private::SymbolContext::line_entry, and lldb_private::SymbolContext::module_sp.
Referenced by lldb_private::BreakpointResolver::AddLocation(), GetDescription(), lldb_private::SymbolContext::GetFunctionStartLineEntry(), and line_entry_helper().
CalculateSymbolContextModule()
ModuleSP Address::CalculateSymbolContextModule () const
Definition at line 839 of file Address.cpp.
References GetSection().
CalculateSymbolContextSymbol()
Symbol * Address::CalculateSymbolContextSymbol () const
Definition at line 888 of file Address.cpp.
References GetSection(), lldb_private::SymbolContext::module_sp, and lldb_private::SymbolContext::symbol.
Referenced by lldb_private::BreakpointLocation::GetDescription(), lldb_private::AppleObjCTrampolineHandler::GetStepThroughDispatchPlan(), GetSymbolDeclarationFromAddress(), GetSymbolNameFromAddress(), lldb_private::ItaniumABILanguageRuntime::GetVTableInfo(), and lldb_private::Process::ResolveIndirectFunction().
Clear()
void lldb_private::Address::Clear () inline
Clear the object's state.
Sets the section to an invalid value (NULL) and an invalid offset (LLDB_INVALID_ADDRESS).
Definition at line 181 of file Address.h.
References LLDB_INVALID_ADDRESS, m_offset, and m_section_wp.
Referenced by lldb_private::CompactUnwindInfo::GetCompactUnwindInfoForFunction(), lldb_private::SymbolContext::GetParentOfInlinedScope(), lldb_private::SectionLoadList::ResolveLoadAddress(), and lldb_private::BreakpointResolverName::SearchCallback().
ClearSection()
void lldb_private::Address::ClearSection () inline
Definition at line 470 of file Address.h.
References m_section_wp.
CompareFileAddress()
int Address::CompareFileAddress (const Address & lhs, const Address & rhs) static
Compare two Address objects.
Parameters
[in] lhs The Left Hand Side const Address object reference.
[in] rhs The Right Hand Side const Address object reference.
Returns
-1 if lhs < rhs 0 if lhs == rhs 1 if lhs > rhs
Definition at line 920 of file Address.cpp.
References Address(), and GetFileAddress().
Referenced by lldb_private::LineEntry::Compare().
CompareLoadAddress()
int Address::CompareLoadAddress (const Address & lhs, const Address & rhs, Target * target) static
Definition at line 930 of file Address.cpp.
References Address(), and GetLoadAddress().
Referenced by lldb_private::UserExpression::LockAndCheckContext().
CompareModulePointerAndOffset()
int Address::CompareModulePointerAndOffset (const Address & lhs, const Address & rhs) static
Definition at line 942 of file Address.cpp.
References Address(), GetFileAddress(), and GetModule().
Referenced by lldb_private::Address::ModulePointerAndOffsetLessThanFunctionObject::operator()().
Dump()
bool Address::Dump (Stream * s, ExecutionContextScope * exe_scope, DumpStyle style, DumpStyle fallback_style = DumpStyleInvalid, uint32_t addr_byte_size = UINT32_MAX, bool all_ranges = false, std::optional< Stream::HighlightSettings > settings = std::nullopt) const
Dump a description of this object to a Stream.
Dump a description of the contents of this object to the supplied stream s. There are many ways to display a section offset based address, and style lets the user choose.
Parameters
[in] s The stream to which to dump the object description.
[in] style The display style for the address.
[in] fallback_style The display style for the address.
[in] addr_byte_size The address byte size for the address.
[in] all_ranges If true, dump all valid ranges and value ranges for the variable that contains the address, otherwise dumping the range that contains the address.
[in] pattern An optional regex pattern to match against the description. If specified, parts of the description matching this pattern may be highlighted or processed differently. If this parameter is an empty string or not provided, no highlighting is applied.
Returns
Returns true if the address was able to be displayed. File and load addresses may be unresolved and it may not be possible to display a valid value, false will be returned in such cases.
See also
Address::DumpStyle
Definition at line 396 of file Address.cpp.
References Address(), lldb_private::Block::AppendVariables(), lldb_private::ConstString::AsCString(), lldb_private::Stream::AsRawOstream(), lldb_private::SymbolContext::block, Dump(), lldb_private::DumpAddress(), lldb_private::DumpAddressRange(), lldb_private::SymbolContext::DumpStopContext(), DumpStyleDetailedSymbolContext, DumpStyleFileAddress, DumpStyleInvalid, DumpStyleLoadAddress, DumpStyleModuleWithFileAddress, DumpStyleNoFunctionName, DumpStyleResolvedDescription, DumpStyleResolvedDescriptionNoFunctionArguments, DumpStyleResolvedDescriptionNoModule, DumpStyleResolvedPointerDescription, DumpStyleSectionNameOffset, DumpStyleSectionPointerOffset, DumpUInt(), lldb::eDescriptionLevelBrief, lldb_private::Stream::EOL(), lldb::eSectionTypeData, lldb::eSectionTypeData16, lldb::eSectionTypeData4, lldb::eSectionTypeData8, lldb::eSectionTypeDataCString, lldb::eSectionTypeDataCStringPointers, lldb::eSectionTypeDataObjCCFStrings, lldb::eSectionTypeDataObjCMessageRefs, lldb::eSectionTypeDataPointers, lldb_private::ABI::FindPlugin(), lldb_private::SymbolContext::function, lldb_private::ArchSpec::GetAddressByteSize(), lldb_private::Symbol::GetAddressRef(), lldb_private::Target::GetArchitecture(), GetCallableLoadAddress(), lldb_private::ConstString::GetCString(), lldb_private::SymbolContext::GetDescription(), GetFileAddress(), lldb_private::Target::GetImages(), GetLoadAddress(), lldb_private::ArchSpec::GetMachine(), GetModule(), lldb_private::Symbol::GetName(), lldb_private::Type::GetName(), GetOffset(), lldb_private::ExecutionContext::GetProcessPtr(), GetSection(), lldb_private::StreamString::GetSize(), lldb_private::StreamString::GetString(), lldb_private::ExecutionContext::GetTargetPtr(), lldb_private::Stream::Indent(), IsSectionOffset(), LLDB_INVALID_ADDRESS, lldb_private::Variable::LocationIsValidForAddress(), m_offset, lldb_private::Stream::Printf(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), lldb_private::Stream::PutCStringColorHighlighted(), ReadAddress(), ReadCStringFromMemory(), lldb_private::Process::ReadPointerFromMemory(), lldb_private::ModuleList::ResolveSymbolContextForAddress(), SetLoadAddress(), SetOffset(), lldb_private::SymbolContext::symbol, UINT32_MAX, lldb_private::Symbol::ValueIsAddress(), and lldb_private::Stream::Write().
Referenced by lldb::SBBreakpoint::AddLocation(), lldb_private::ClangExpressionDeclMap::AddOneFunction(), lldb_private::formatters::CXXFunctionPointerSummaryProvider(), CommandObjectSourceList::DoExecute(), Dump(), DumpAddress(), DumpAddressAndContent(), lldb_private::DumpDataExtractor(), CommandObjectRegisterRead::DumpRegister(), lldb_private::SymbolContext::DumpStopContext(), lldb_private::ThreadPlanStepOut::GetDescription(), CommandObjectSourceInfo::GetSymbolContextsForAddress(), lldb_private::CompactUnwindInfo::GetUnwindPlan(), lldb_private::ThreadPlanAssemblyTracer::Log(), lldb_private::UnwindPlan::PlanValidAtAddress(), CommandObjectTargetModulesList::PrintModule(), and DisassemblerLLVMC::SymbolLookup().
GetAddressClass()
AddressClass Address::GetAddressClass () const
Definition at line 1021 of file Address.cpp.
References lldb_private::eUnknown, lldb_private::ObjectFile::GetAddressClass(), GetFileAddress(), and GetModule().
Referenced by DisassemblerLLVMC::DecodeInstructions(), GetCallableLoadAddress(), GetOpcodeLoadAddress(), SetCallableLoadAddress(), EmulateInstructionMIPS::SetInstruction(), lldb_private::EmulateInstructionARM::SetInstruction(), and SetOpcodeLoadAddress().
GetCallableLoadAddress()
addr_t Address::GetCallableLoadAddress (Target * target, bool is_indirect = false) const
Get the load address as a callable code load address.
This function will first resolve its address to a load address. Then, if the address turns out to be in code address, return the load address that would be required to call or return to. The address might have extra bits set (bit zero will be set to Thumb functions for an ARM target) that are required when changing the program counter to setting a return address.
Returns
The valid load virtual address, or LLDB_INVALID_ADDRESS if the address is currently not loaded.
Definition at line 326 of file Address.cpp.
References error(), GetAddressClass(), lldb_private::Target::GetCallableLoadAddress(), GetLoadAddress(), lldb_private::Target::GetProcessSP(), and LLDB_INVALID_ADDRESS.
Referenced by lldb_private::ClangExpressionDeclMap::AddOneFunction(), CommandObjectThreadJump::DoExecute(), Dump(), lldb_private::ClangExpressionDeclMap::GetSymbolAddress(), line_entry_helper(), ABIMacOSX_arm::PrepareTrivialCall(), ABISysV_arm::PrepareTrivialCall(), LoadAddressResolver::Resolve(), lldb_private::Symbol::ResolveCallableAddress(), and lldb_private::RegisterContext::SetPC().
GetDescription()
bool Address::GetDescription (Stream & s, Target & target, lldb::DescriptionLevel level) const
Write a description of this object to a Stream.
Definition at line 383 of file Address.cpp.
References CalculateSymbolContextLineEntry(), lldb_private::LineEntry::column, lldb::eDescriptionLevelBrief, lldb_private::ConstString::GetCString(), lldb_private::LineEntry::GetFile(), lldb_private::FileSpec::GetFilename(), lldb_private::LineEntry::line, and lldb_private::Stream::Printf().
Referenced by DescribeAddressBriefly().
GetFileAddress()
addr_t Address::GetFileAddress () const
Get the file address.
If an address comes from a file on disk that has section relative addresses, then it has a virtual address that is relative to unique section in the object file.
Returns
The valid file virtual address, or LLDB_INVALID_ADDRESS if the address doesn't have a file virtual address (image is from memory only with no representation on disk).
Definition at line 281 of file Address.cpp.
References GetSection(), LLDB_INVALID_ADDRESS, m_offset, and SectionWasDeletedPrivate().
Referenced by lldb_private::BreakpointResolver::AddLocation(), lldb_private::ClangExpressionDeclMap::AddOneFunction(), lldb_private::Block::AddRange(), lldb_private::VariableAnnotator::AnnotateStructured(), ObjectFilePECOFF::AppendFromCOFFSymbolTable(), ApplyELF32ABS32RelRelocation(), ApplyELF64ABS32Relocation(), ApplyELF64ABS64Relocation(), ObjectFileELF::ApplyRelocations(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CalculateFrameVariableError(), CompareFileAddress(), CompareModulePointerAndOffset(), DynamicLoaderPOSIXDYLD::ComputeLoadOffset(), lldb_private::AddressRange::ContainsFileAddress(), lldb_private::AddressRange::ContainsFileAddress(), lldb_private::npdb::SymbolFileNativePDB::CreateBlock(), lldb_private::npdb::SymbolFileNativePDB::CreateLocalVariable(), CommandObjectThreadStepWithTypeAndScope::DoExecute(), Dump(), ObjectFileELF::Dump(), DumpAddressAndContent(), DumpAddressOffsetFromFunction(), CommandObjectSourceInfo::DumpLinesInFunctions(), lldb_private::Variable::DumpLocations(), lldb_private::SymbolContext::DumpStopContext(), DumpUnwindRowsToLog(), lldb_private::AddressRange::Extend(), lldb_private::Module::FindFunctions(), DynamicLoaderFreeBSDKernel::FindKernelAtLoadAddress(), lldb_private::LineTable::FindLineEntryByAddress(), fixupExternalAddrZeroVariable(), GetAddressClass(), lldb_private::DWARFCallFrameInfo::GetAddressRange(), lldb_private::SymbolContext::GetAddressRangeFromHereToEndLine(), lldb_private::ArchitectureMips::GetBreakableLoadAddress(), lldb_private::ArchitecturePPC64::GetBytesToSkip(), lldb_private::CompactUnwindInfo::GetCompactUnwindInfoForFunction(), SymbolFilePDB::GetCompileUnitContainsAddress(), lldb::SBBlock::GetDescription(), lldb_private::Block::GetDescription(), DynamicLoaderHexagonDYLD::GetEntryPoint(), ObjectFileMachO::GetEntryPointAddress(), lldb_private::ArmUnwindInfo::GetExceptionHandlingTableEntry(), lldb_private::Symbol::GetFileAddress(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo::GetFileRangeMap(), lldb_private::DWARFCallFrameInfo::GetFirstFDEEntryInRange(), lldb_private::UnwindTable::GetFuncUnwindersContainingAddress(), llvm::DenseMapInfo< lldb_private::SymbolContext >::getHashValue(), lldb_private::LineTable::GetLineEntryIndexRange(), UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly(), lldb_private::breakpad::SymbolFileBreakpad::GetParameterStackSize(), lldb_private::SymbolContext::GetParentOfInlinedScope(), lldb_private::Function::GetPrologueByteSize(), lldb_private::Block::GetRangeContainingAddress(), lldb_private::Block::GetRangeIndexContainingAddress(), ObjectFilePECOFF::GetRVA(), ObjectFileELF::GetSegmentData(), lldb_private::breakpad::SymbolFileBreakpad::GetUnwindPlan(), lldb_private::DWARFCallFrameInfo::GetUnwindPlan(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::InitOSO(), lldb_private::Variable::IsInScope(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::LinkOSOAddress(), DynamicLoaderDarwinKernel::KextImageInfo::LoadImageUsingMemoryModule(), DynamicLoaderFreeBSDKernel::KModImageInfo::LoadImageUsingMemoryModule(), DynamicLoaderDarwinKernel::LoadKernelModuleIfNeeded(), lldb_private::Variable::LocationIsValidForAddress(), lldb_private::LineTable::lower_bound(), lldb_private::DWARFExpressionList::MatchesOperand(), EntitySymbol::Materialize(), lldb_private::operator<(), lldb_private::operator>(), lldb_private::DWARFCallFrameInfo::ParseFDE(), lldb_private::npdb::SymbolFileNativePDB::ParseInlineSite(), ObjectFileMachO::ParseSymtab(), SymbolFilePDB::ParseVariableForPDBData(), CommandObjectTargetModulesList::PrintModule(), lldb_private::Target::ReadMemory(), LoadAddressResolver::Resolve(), lldb_private::CompileUnit::ResolveSymbolContext(), lldb_private::SymbolFileCTF::ResolveSymbolContext(), lldb_private::SymbolFileJSON::ResolveSymbolContext(), SymbolFileSymtab::ResolveSymbolContext(), lldb_private::Module::ResolveSymbolContextForAddress(), lldb_private::AddressResolverFileLine::SearchCallback(), DynamicLoaderDarwinKernel::SearchForKernelAtSameLoadAddr(), lldb_private::EmulateInstruction::SetInstruction(), ObjectFileELF::SetLoadAddress(), lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint(), lldb_private::BreakpointResolver::SetSCMatchesByLine(), and ToAddressRange().
GetLoadAddress()
addr_t Address::GetLoadAddress (Target * target) const
Get the load address.
If an address comes from a file on disk that has section relative addresses, then it has a virtual address that is relative to unique section in the object file. Sections get resolved at runtime by DynamicLoader plug-ins as images (executables and shared libraries) get loaded/unloaded. If a section is loaded, then the load address can be resolved.
Returns
The valid load virtual address, or LLDB_INVALID_ADDRESS if the address is currently not loaded.
Definition at line 301 of file Address.cpp.
References GetSection(), LLDB_INVALID_ADDRESS, m_offset, and SectionWasDeletedPrivate().
Referenced by AddLinkMapSections(), lldb_private::BreakpointResolver::AddLocation(), lldb_private::ClangExpressionDeclMap::AddOneGenericVariable(), SystemRuntimeMacOSX::BacktraceRecordingHeadersInitialized(), BuildModulesSection(), CompareLoadAddress(), lldb_private::AddressRange::ContainsLoadAddress(), lldb_private::AddressRange::ContainsLoadAddress(), lldb_private::Value::ConvertToLoadAddress(), CreateAllImageInfosPayload(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_i386(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_x86_64(), DescribeAddressBriefly(), lldb_private::StopInfoMachException::DeterminePtrauthFailure(), lldb_private::HistoryUnwind::DoCreateRegisterContextForFrame(), CommandObjectTargetModulesLoad::DoExecute(), CommandObjectTargetModulesShowUnwind::DoExecute(), CommandObjectThreadUntil::DoExecute(), Dump(), DumpAddressAndContent(), DumpAddressOffsetFromFunction(), CommandObjectSourceInfo::DumpLinesInFunctions(), ExtractRuntimeGlobalSymbol(), lldb_private::Process::FindInMemory(), HexagonDYLDRendezvous::FindMetadata(), lldb_private::Process::FindRangesInMemory(), findSymbolAddress(), lldb_private::ArchitectureMips::GetBreakableLoadAddress(), GetCallableLoadAddress(), lldb_private::Block::GetDescription(), lldb_private::ItaniumABILanguageRuntime::GetDynamicTypeAndAddress(), lldb_private::ProcessWindows::GetImageInfoAddress(), ObjectFileELF::GetImageInfoAddress(), ProcessElfCore::GetImageInfoAddress(), lldb_private::AppleObjCRuntimeV1::GetISAHashTablePointer(), lldb_private::CallEdge::GetLoadAddress(), lldb_private::Symbol::GetLoadAddress(), lldb_private::ValueObject::GetLoadAddress(), GetOpcodeLoadAddress(), lldb_private::Target::GetReasonableReadSize(), DynamicLoaderHexagonDYLD::GetStepThroughTrampolinePlan(), DynamicLoaderPOSIXDYLD::GetStepThroughTrampolinePlan(), lldb_private::DynamicLoaderDarwin::GetStepThroughTrampolinePlan(), JITLoaderGDB::GetSymbolAddress(), lldb_private::ClangExpressionDeclMap::GetSymbolAddress(), lldb_private::DynamicLoaderDarwin::GetThreadLocalData(), lldb_private::Value::GetValueAsData(), lldb_private::ClangExpressionDeclMap::GetVariableValue(), lldb_private::ThreadPlanStepRange::InRange(), DynamicLoaderDarwinKernel::LoadKernelModuleIfNeeded(), lldb_private::Variable::LocationIsValidForFrame(), EntitySymbol::Materialize(), CommandObjectTargetModulesList::PrintModule(), DynamicLoaderFreeBSDKernel::ReadAllKmods(), lldb_private::Target::ReadCStringFromMemory(), lldb_private::Target::ReadCStringFromMemory(), DynamicLoaderMacOSXDYLD::ReadDYLDInfoFromMemoryAndSetNotificationCallback(), lldb_private::Target::ReadInstructions(), lldb_private::Target::ReadMemory(), LoadAddressResolver::Resolve(), lldb_private::Process::ResolveIndirectFunction(), ResolveLoadAddress(), DYLDRendezvous::ResolveRendezvousAddress(), lldb_private::InstrumentationRuntimeMainThreadChecker::RetrieveReportData(), lldb_private::InstrumentationRuntimeUBSan::RetrieveReportData(), lldb_private::EmulateInstruction::SetInstruction(), lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint(), lldb_private::ThreadPlanStepOut::SetupReturnAddress(), lldb_private::Watchpoint::SetupVariableWatchpointDisabler(), lldb_private::ThreadPlanStepInRange::ShouldStop(), lldb_private::ThreadPlanStepOverRange::ShouldStop(), and lldb_private::ValueObjectVariable::UpdateValue().
GetModule()
ModuleSP Address::GetModule () const
Get accessor for the module for this address.
Returns
Returns the Module pointer that this address is an offset in, or NULL if this address doesn't belong in a module, or isn't resolved yet.
Definition at line 273 of file Address.cpp.
References GetSection().
Referenced by DynamicLoaderPOSIXDYLD::AlwaysRelyOnEHUnwindInfo(), lldb_private::DynamicLoaderDarwin::AlwaysRelyOnEHUnwindInfo(), lldb_private::VariableAnnotator::AnnotateStructured(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CalculateFrameVariableError(), lldb_private::Symbol::CalculateSymbolContext(), lldb_private::Symbol::CalculateSymbolContextModule(), CompareModulePointerAndOffset(), CommandObjectSourceList::DoExecute(), CommandObjectTargetModulesList::DoExecute(), CommandObjectTargetModulesShowUnwind::DoExecute(), Dump(), DumpAddressOffsetFromFunction(), GetAddressClass(), lldb_private::DWARFCallFrameInfo::GetAddressRange(), lldb_private::ArchitectureMips::GetBreakableLoadAddress(), GetByteOrderAndAddressSize(), lldb::SBInstruction::GetDescription(), lldb::SBInstructionList::GetDescription(), lldb_private::InstrumentationRuntimeTSan::GetFirstNonInternalFramePc(), lldb::SBSymbol::GetInstructions(), lldb_private::Function::GetInstructions(), lldb_private::CallEdge::GetLoadAddress(), lldb_private::Symbol::GetPrologueByteSize(), lldb_private::Block::GetRangeAtIndex(), lldb_private::Block::GetRangeContainingAddress(), lldb_private::Block::GetRangeIndexContainingAddress(), lldb_private::Block::GetRanges(), lldb_private::Block::GetStartAddress(), CommandObjectSourceInfo::GetSymbolContextsForAddress(), lldb_private::DWARFCallFrameInfo::GetUnwindPlan(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::LinkOSOAddress(), lldb_private::Variable::LocationIsValidForAddress(), LookupAddressInModule(), lldb_private::LineTable::lower_bound(), lldb_private::DynamicLoaderWindowsDYLD::OnUnloadModule(), lldb_private::operator<(), lldb_private::operator>(), lldb::SBInstruction::Print(), lldb_private::Disassembler::PrintInstructions(), ReadAddress(), lldb_private::Target::ReadMemory(), lldb_private::BreakpointLocationList::RemoveInvalidLocations(), lldb_private::ModuleList::ResolveSymbolContextForAddress(), lldb_private::InstrumentationRuntimeMainThreadChecker::RetrieveReportData(), lldb_private::InstrumentationRuntimeUBSan::RetrieveReportData(), lldb_private::StackFrame::StackFrame(), DisassemblerLLVMC::SymbolLookup(), ToAddressRange(), and lldb_private::DynamicLoaderDarwin::UnloadImages().
GetOffset()
lldb::addr_t lldb_private::Address::GetOffset () const inline
Get the section relative offset value.
Returns
The current offset, or LLDB_INVALID_ADDRESS if this address doesn't contain a valid offset.
Definition at line 329 of file Address.h.
References m_offset.
Referenced by lldb_private::ArchitecturePPC64::AdjustBreakpointAddress(), lldb_private::AddressRange::ContainsFileAddress(), lldb_private::AddressRange::ContainsLoadAddress(), Dump(), lldb_private::SymbolContext::DumpStopContext(), lldb_private::BreakpointLocationList::FindByAddress(), DYLDRendezvous::FindMetadata(), lldb_private::StackFrame::GetFrameCodeAddressForSymbolication(), lldb_private::operator!=(), lldb_private::operator==(), lldb_private::breakpad::SymbolFileBreakpad::ParseBlocksRecursive(), SymbolFileSymtab::ParseFunctions(), ReadCStringFromMemory(), ObjectFilePECOFF::ReadImageDataByRVA(), lldb_private::Target::ReadMemory(), lldb_private::Target::ReadMemoryFromFileCache(), ResolveAddress(), lldb_private::Module::ResolveSymbolContextForAddress(), lldb_private::BreakpointResolverName::SearchCallback(), lldb_private::ThreadPlanStepOut::SetupReturnAddress(), and lldb_private::DynamicLoaderDarwin::UnloadImages().
GetOpcodeLoadAddress()
addr_t Address::GetOpcodeLoadAddress (Target * target, AddressClass addr_class = AddressClass::eInvalid) const
Get the load address as an opcode load address.
This function will first resolve its address to a load address. Then, if the address turns out to be in code address, return the load address for an opcode. This address object might have extra bits set (bit zero will be set to Thumb functions for an ARM target) that are required for changing the program counter and this function will remove any bits that are intended for these special purposes. The result of this function can be used to safely write a software breakpoint trap to memory.
Returns
The valid load virtual address with extra callable bits removed, or LLDB_INVALID_ADDRESS if the address is currently not loaded.
Definition at line 358 of file Address.cpp.
References lldb_private::eInvalid, GetAddressClass(), GetLoadAddress(), lldb_private::Target::GetOpcodeLoadAddress(), and LLDB_INVALID_ADDRESS.
Referenced by lldb_private::InstrumentationRuntimeMainThreadChecker::Activate(), lldb_private::InstrumentationRuntimeTSan::Activate(), lldb_private::InstrumentationRuntimeUBSan::Activate(), lldb_private::AppleObjCTrampolineHandler::AppleObjCTrampolineHandler(), lldb_private::Process::CreateBreakpointSite(), DynamicLoaderMacOS::GetDyldLockVariableAddressFromModule(), lldb_private::StackFrame::GetFrameCodeAddressForSymbolication(), lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::InitializeVTableSymbols(), and lldb_private::ThreadPlanRunToAddress::ThreadPlanRunToAddress().
GetSection()
lldb::SectionSP lldb_private::Address::GetSection () const inline
Get const accessor for the section.
Returns
Returns the const lldb::Section pointer that this address is an offset in, or NULL if this address is absolute.
Definition at line 432 of file Address.h.
References m_section_wp.
Referenced by ObjectFilePECOFF::AppendFromExportTable(), CalculateSymbolContext(), CalculateSymbolContextBlock(), CalculateSymbolContextCompileUnit(), CalculateSymbolContextFunction(), CalculateSymbolContextLineEntry(), CalculateSymbolContextModule(), CalculateSymbolContextSymbol(), lldb_private::AddressRange::Contains(), lldb_private::AddressRange::ContainsFileAddress(), lldb_private::AddressRange::ContainsLoadAddress(), lldb_private::formatters::CXXFunctionPointerSummaryProvider(), ProcessMachCore::DoGetMemoryRegionInfo(), Dump(), CommandObjectMemoryRegion::DumpRegion(), lldb_private::ObjectFile::GetAddressClass(), ObjectFileMachO::GetAddressClass(), GetFileAddress(), GetLoadAddress(), GetModule(), getModuleFileSize(), IsSectionOffset(), lldb_private::Breakpoint::ModulesChanged(), lldb_private::operator!=(), lldb_private::operator==(), ObjectFileMachO::ParseSymtab(), ObjectFileELF::ReadDataFromDynamic(), ObjectFilePECOFF::ReadImageDataByRVA(), lldb_private::Target::ReadMemory(), lldb_private::Target::ReadMemoryFromFileCache(), RemoveFunctionsWithModuleNotEqualTo(), lldb_private::Module::ResolveSymbolContextForAddress(), SectionWasDeleted(), and DisassemblerLLVMC::SymbolLookup().
IsSectionOffset()
bool lldb_private::Address::IsSectionOffset () const inline
Check if an address is section offset.
When converting a virtual file or load address into a section offset based address, we often need to know if, given a section list, if the address was able to be converted to section offset. This function returns true if the current value contained in this object is section offset based.
Returns
Returns true if the address has a valid section and offset, false otherwise.
Definition at line 342 of file Address.h.
References GetSection(), and IsValid().
Referenced by Dump(), Evaluate_DW_OP_deref_size(), lldb_private::BreakpointLocationList::FindByAddress(), lldb_private::ItaniumABILanguageRuntime::GetTypeInfo(), lldb_private::Value::GetValueAsData(), lldb_private::Variable::LocationIsValidForAddress(), SymbolFileSymtab::ParseFunctions(), lldb_private::Target::ReadMemory(), ResolveAddress(), ResolveLoadAddress(), and lldb_private::Module::ResolveSymbolContextForAddress().
IsValid()
bool lldb_private::Address::IsValid () const inline
Check if the object state is valid.
A valid Address object contains either a section pointer and offset (for section offset based addresses), or just a valid offset (for absolute addresses that have no section).
Returns
Returns true if the offset is valid, false otherwise.
Definition at line 355 of file Address.h.
References LLDB_INVALID_ADDRESS, and m_offset.
Referenced by lldb_private::InstrumentationRuntimeMainThreadChecker::Activate(), lldb_private::InstrumentationRuntimeTSan::Activate(), lldb_private::InstrumentationRuntimeUBSan::Activate(), lldb_private::BreakpointResolver::AddLocation(), lldb_private::Process::AdvanceAddressToNextBranchInstruction(), lldb_private::Disassembler::AppendInstructions(), lldb_private::x86AssemblyInspectionEngine::AugmentUnwindPlanFromCallSite(), UnwindAssembly_x86::AugmentUnwindPlanFromCallSite(), BuildModulesSection(), CharStringSummaryProvider(), DynamicLoaderPOSIXDYLD::ComputeLoadOffset(), CreateAllImageInfosPayload(), lldb_private::Target::CreateBreakpoint(), lldb_private::npdb::SymbolFileNativePDB::CreateFunction(), lldb_private::formatters::CXXFunctionPointerSummaryProvider(), lldb_private::Disassembler::Disassemble(), CommandObjectTargetModulesLoad::DoExecute(), CommandObjectTargetModulesShowUnwind::DoExecute(), CommandObjectThreadStepWithTypeAndScope::DoExecute(), ObjectFileELF::Dump(), DumpAddressOffsetFromFunction(), lldb_private::SymbolContext::DumpStopContext(), lldb_private::SymbolContext::FindBestGlobalDataSymbol(), lldb_private::BreakpointLocationList::FindByAddress(), DynamicLoaderFreeBSDKernel::FindKernelAtLoadAddress(), UnwindAssembly_x86::FirstNonPrologueInsn(), lldb_private::FormatEntity::Formatter::Format(), lldb_private::UnwindTable::GetAddressRanges(), DynamicLoaderMacOS::GetDyldLockVariableAddressFromModule(), lldb_private::Target::GetEntryPointAddress(), ObjectFileMachO::GetEntryPointAddress(), lldb_private::StackFrame::GetFrameCodeAddressForSymbolication(), GetFunctionOrSymbolAddress(), lldb_private::ProcessWindows::GetImageInfoAddress(), ProcessElfCore::GetImageInfoAddress(), UnwindAssembly_x86::GetNonCallSiteUnwindPlanFromAssembly(), UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly(), lldb_private::DynamicLoaderDarwin::GetStepThroughTrampolinePlan(), JITLoaderGDB::GetSymbolAddress(), lldb_private::ClangExpressionDeclMap::GetSymbolAddress(), lldb_private::StackFrame::GetSymbolContext(), lldb_private::DynamicLoaderDarwin::GetThreadLocalData(), lldb_private::Value::GetValueAsData(), lldb_private::InferiorCallMmap(), lldb_private::InferiorCallMunmap(), lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::InitializeVTableSymbols(), IsSectionOffset(), SymbolFilePDB::ParseCompileUnitFunctionForPDBFunc(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseFunction(), lldb_private::DirectCallEdge::ParseSymbolFileAndResolve(), lldb_private::UnwindPlan::PlanValidAtAddress(), CommandObjectTargetModulesList::PrintModule(), lldb_private::Target::ReadMemory(), lldb_private::Target::ReadPointerFromMemory(), ResolveAddress(), lldb_private::Symbol::ResolveCallableAddress(), DYLDRendezvous::ResolveRendezvousAddress(), lldb_private::AddressResolverFileLine::SearchCallback(), lldb_private::BreakpointResolverName::SearchCallback(), DynamicLoaderDarwinKernel::SearchForKernelAtSameLoadAddr(), lldb_private::EmulateInstruction::SetInstruction(), lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint(), lldb_private::ReportRetriever::SetupBreakpoint(), DisassemblerLLVMC::SymbolLookup(), ValueObjectVTableChild::UpdateValue(), and lldb_private::formatters::WCharStringSummaryProvider().
MemorySize()
size_t Address::MemorySize () const
Get the memory cost of this object.
Returns
The number of bytes that this object occupies in memory.
Definition at line 962 of file Address.cpp.
References Address().
operator=()
const Address & Address::operator= (const Address & rhs)
Assignment operator.
Copies the address value from another Address object rhs into this object.
Parameters
[in] rhs A const Address object reference to copy.
Returns
A const Address object reference to this.
Definition at line 241 of file Address.cpp.
References Address(), m_offset, and m_section_wp.
ResolveAddressUsingFileSections()
bool Address::ResolveAddressUsingFileSections (lldb::addr_t addr, const SectionList * sections)
Resolve a file virtual address using a section list.
Given a list of sections, attempt to resolve addr as an offset into one of the file sections.
Returns
Returns true if addr was able to be resolved, false otherwise.
Definition at line 249 of file Address.cpp.
References lldb_private::SectionList::FindSectionContainingFileAddress(), m_offset, and m_section_wp.
Referenced by Address(), lldb_private::CompactUnwindInfo::GetCompactUnwindInfoForFunction(), ObjectFileELF::GetImageInfoAddress(), ObjectFileELF::ReadDataFromDynamic(), and lldb_private::Module::ResolveFileAddress().
ResolveFunctionScope()
bool Address::ResolveFunctionScope (lldb_private::SymbolContext & sym_ctx)
Resolve this address to its containing function.
Parameters
[out] sym_ctx The symbol context describing the function in which this address lies
Returns
Returns false if the function/symbol could not be resolved; returns true otherwise.
Definition at line 266 of file Address.cpp.
References CalculateSymbolContext().
Referenced by lldb_private::RegisterContextUnwind::InitializeNonZerothFrame().
SectionWasDeleted()
bool Address::SectionWasDeleted () const
Definition at line 800 of file Address.cpp.
References GetSection(), and SectionWasDeletedPrivate().
Referenced by lldb_private::Breakpoint::ModulesChanged(), and lldb_private::BreakpointLocationList::RemoveInvalidLocations().
SectionWasDeletedPrivate()
bool Address::SectionWasDeletedPrivate () const protected
Definition at line 806 of file Address.cpp.
References m_section_wp.
Referenced by GetFileAddress(), GetLoadAddress(), and SectionWasDeleted().
SetCallableLoadAddress()
bool Address::SetCallableLoadAddress (lldb::addr_t load_addr, Target * target)
Definition at line 349 of file Address.cpp.
References GetAddressClass(), lldb_private::Target::GetCallableLoadAddress(), m_offset, and SetLoadAddress().
SetLoadAddress()
bool Address::SetLoadAddress (lldb::addr_t load_addr, Target * target, bool allow_section_end = false)
Set the address to represent load_addr.
The address will attempt to find a loaded section within target that contains load_addr. If successful, this address object will have a valid section and offset. Else this address object will have no section (NULL) and the offset will be load_addr.
Parameters
[in] load_addr A load address from a current process.
[in] target The target to use when trying resolve the address into a section + offset. The Target's SectionLoadList object is used to resolve the address.
[in] allow_section_end If true, treat an address pointing to the end of the module as belonging to that module.
Returns
Returns true if the load address was resolved to be section/offset, false otherwise. It is often ok for an address to not resolve to a section in a module, this often happens for JIT'ed code, or any load addresses on the stack or heap.
Definition at line 1035 of file Address.cpp.
References lldb_private::SectionLoadHistory::eStopIDNow, m_offset, m_section_wp, and lldb_private::Target::ResolveLoadAddress().
Referenced by CalculateSymbolInfo(), lldb_private::ScriptedFrame::Create(), lldb_private::formatters::CXXFunctionPointerSummaryProvider(), CommandObjectTargetModulesList::DoExecute(), Dump(), lldb::SBValue::GetAddress(), lldb_private::BreakpointLocation::GetDescription(), lldb_private::ThreadPlanStepOut::GetDescription(), lldb_private::ScriptedFrameProvider::GetFrameAtIndex(), lldb_private::InstructionList::GetIndexOfInstructionAtLoadAddress(), lldb_private::RegisterContext::GetPCForSymbolication(), lldb_private::ValueObject::GetPointeeData(), lldb_private::Block::GetRangeContainingLoadAddress(), lldb_private::RegisterContextUnwind::InitializeNonZerothFrame(), lldb_private::ScriptedThread::LoadArtificialStackFrames(), ABIMacOSX_arm::PrepareTrivialCall(), ABISysV_arm::PrepareTrivialCall(), lldb_private::Target::ReadMemory(), SetCallableLoadAddress(), SetOpcodeLoadAddress(), and lldb_private::DynamicLoaderDarwin::UnloadImages().
SetOffset()
bool lldb_private::Address::SetOffset (lldb::addr_t offset) inline
Set accessor for the offset.
Parameters
[in] offset A new offset value for this object.
Returns
Returns true if the offset changed, false otherwise.
Definition at line 441 of file Address.h.
References m_offset.
Referenced by lldb_private::ArchitecturePPC64::AdjustBreakpointAddress(), lldb_private::Target::CreateBreakpoint(), Dump(), lldb_private::DumpDataExtractor(), DYLDRendezvous::FindMetadata(), ObjectFileMachO::GetBaseAddress(), lldb_private::StackFrame::GetFrameCodeAddressForSymbolication(), ObjectFileELF::GetImageInfoAddress(), lldb_private::RegisterContextUnwind::IsUnwindPlanValidForCurrentPC(), lldb_private::UtilityFunction::MakeFunctionCaller(), ObjectFileELF::ParseSymtab(), ObjectFileMachO::ParseSymtab(), ReadCStringFromMemory(), lldb_private::Target::ReadPointerFromMemory(), lldb_private::Section::ResolveContainedAddress(), lldb_private::BreakpointResolverName::SearchCallback(), and lldb::SBAddress::SetAddress().
SetOpcodeLoadAddress()
bool Address::SetOpcodeLoadAddress (lldb::addr_t load_addr, Target * target, AddressClass addr_class = AddressClass::eInvalid, bool allow_section_end = false)
Definition at line 369 of file Address.cpp.
References lldb_private::eInvalid, GetAddressClass(), lldb_private::Target::GetOpcodeLoadAddress(), m_offset, and SetLoadAddress().
Referenced by lldb_private::StackFrame::GetFrameCodeAddressForSymbolication(), and lldb_private::AppleThreadPlanStepThroughObjCTrampoline::ShouldStop().
SetRawAddress()
void lldb_private::Address::SetRawAddress (lldb::addr_t addr) inline
Definition at line 447 of file Address.h.
References m_offset, and m_section_wp.
Referenced by DumpInstructions(), lldb::SBBreakpoint::FindLocationByAddress(), lldb::SBBreakpoint::FindLocationIDByAddress(), lldb_private::AppleObjCRuntimeV1::GetDynamicTypeAndAddress(), lldb_private::AppleObjCRuntimeV2::GetDynamicTypeAndAddress(), lldb_private::ItaniumABILanguageRuntime::GetDynamicTypeAndAddress(), ReadAddress(), lldb::SBTarget::ResolveFileAddress(), lldb::SBTarget::ResolveLoadAddress(), lldb::SBTarget::ResolvePastLoadAddress(), and DynamicLoaderMacOS::SetNotificationBreakpoint().
SetSection()
void lldb_private::Address::SetSection (const lldb::SectionSP & section_sp) inline
Set accessor for the section.
Parameters
[in] section_sp A new lldb::Section pointer to use as the section base. Can be NULL for absolute addresses that are not relative to any section.
Definition at line 466 of file Address.h.
References m_section_wp.
Referenced by ObjectFileMachO::GetBaseAddress(), ObjectFileMachO::ParseSymtab(), lldb_private::Section::ResolveContainedAddress(), and lldb::SBAddress::SetAddress().
Slide()
bool lldb_private::Address::Slide (int64_t offset) inline
Definition at line 452 of file Address.h.
References LLDB_INVALID_ADDRESS, and m_offset.
Referenced by lldb_private::BreakpointResolver::AddLocation(), lldb_private::BreakpointResolver::AddLocation(), lldb_private::LineTable::ConvertEntryAtIndexToLineEntry(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_i386(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_x86_64(), DisassemblerLLVMC::DecodeInstructions(), lldb_private::ThreadPlanShouldStopHere::DefaultStepFromHereCallback(), UnwindAssembly_x86::FirstNonPrologueInsn(), lldb_private::FormatEntity::Formatter::Format(), lldb::SBSymbol::GetEndAddress(), lldb_private::ArchitectureMips::GetInstructionAtAddress(), UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly(), lldb_private::Symbol::GetPrologueByteSize(), lldb::SBBlock::GetRangeEndAddress(), lldb_private::LineEntry::GetSameLineContiguousAddressRange(), DynamicLoaderDarwinKernel::ReadAllKextSummaries(), lldb_private::Target::ReadStringFromMemory(), lldb_private::Module::ResolveSymbolContextForAddress(), lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint(), lldb_private::ThreadPlanStepOut::SetupReturnAddress(), and lldb_private::ThreadPlanStepInRange::ShouldStop().
Member Data Documentation
m_offset
lldb::addr_t lldb_private::Address::m_offset = LLDB_INVALID_ADDRESS protected
Offset into section if m_section_wp is valid...
Definition at line 506 of file Address.h.
Referenced by Address(), Address(), Address(), Clear(), Dump(), GetFileAddress(), GetLoadAddress(), GetOffset(), IsValid(), operator=(), ResolveAddressUsingFileSections(), SetCallableLoadAddress(), SetLoadAddress(), SetOffset(), SetOpcodeLoadAddress(), SetRawAddress(), and Slide().
m_section_wp
lldb::SectionWP lldb_private::Address::m_section_wp protected
The section for the address, can be NULL.
Definition at line 505 of file Address.h.
Referenced by Address(), Address(), Address(), Address(), Clear(), ClearSection(), GetSection(), operator=(), ResolveAddressUsingFileSections(), SectionWasDeletedPrivate(), SetLoadAddress(), SetRawAddress(), and SetSection().
The documentation for this class was generated from the following files:
Address.h
Address.cpp