LLDB: lldb_private::platform_android::AdbSyncService Class Reference
lldb_private::platform_android::AdbSyncService Class Reference
#include <AdbClient.h>
Public Member Functions
AdbSyncService (const std::string device_id)
virtual ~AdbSyncService ()
Status SetupSyncConnection ()
virtual Status PullFile (const FileSpec &remote_file, const FileSpec &local_file)
virtual Status PushFile (const FileSpec &local_file, const FileSpec &remote_file)
virtual Status Stat (const FileSpec &remote_file, uint32_t &mode, uint32_t &size, uint32_t &mtime)
virtual bool IsConnected () const
llvm::StringRef GetDeviceId () const
Private Member Functions
Status SendSyncRequest (const char *request_id, const uint32_t data_len, const void *data)
Status ReadSyncHeader (std::string &response_id, uint32_t &data_len)
Status PullFileChunk (std::vector< char > &buffer, bool &eof)
Status PullFileImpl (const FileSpec &remote_file, const FileSpec &local_file)
Status PushFileImpl (const FileSpec &local_file, const FileSpec &remote_file)
Status StatImpl (const FileSpec &remote_file, uint32_t &mode, uint32_t &size, uint32_t &mtime)
Status ExecuteCommand (const std::function< Status()> &cmd)
Private Attributes
std::unique_ptr< Connection > m_conn
std::string m_device_id
Detailed Description
Definition at line 83 of file AdbClient.h.
Constructor & Destructor Documentation
AdbSyncService()
AdbSyncService::AdbSyncService (const std::string device_id) explicit
Definition at line 585 of file AdbClient.cpp.
References lldb_private::GetLog(), LLDB_LOGF, m_conn, m_device_id, and lldb_private::Platform.
~AdbSyncService()
AdbSyncService::~AdbSyncService () virtual
Definition at line 600 of file AdbClient.cpp.
References lldb_private::GetLog(), LLDB_LOGF, m_device_id, and lldb_private::Platform.
Member Function Documentation
ExecuteCommand()
Status AdbSyncService::ExecuteCommand (const std::function< Status()> & cmd) private
Definition at line 595 of file AdbClient.cpp.
References error().
Referenced by PullFile(), PushFile(), and Stat().
GetDeviceId()
llvm::StringRef lldb_private::platform_android::AdbSyncService::GetDeviceId () const inline
Definition at line 97 of file AdbClient.h.
References m_device_id.
IsConnected()
bool AdbSyncService::IsConnected () const virtual
Definition at line 581 of file AdbClient.cpp.
References m_conn.
PullFile()
Status AdbSyncService::PullFile (const FileSpec & remote_file, const FileSpec & local_file) virtual
Definition at line 560 of file AdbClient.cpp.
References ExecuteCommand(), and PullFileImpl().
PullFileChunk()
Status AdbSyncService::PullFileChunk (std::vector< char > & buffer, bool & eof) private
Definition at line 641 of file AdbClient.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormat(), kDATA, kDONE, kFAIL, m_conn, ReadAllBytes(), ReadSyncHeader(), and lldb_private::Status.
Referenced by PullFileImpl().
PullFileImpl()
Status AdbSyncService::PullFileImpl (const FileSpec & remote_file, const FileSpec & local_file) private
Definition at line 431 of file AdbClient.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::FileSpec::GetPath(), kRECV, PullFileChunk(), and SendSyncRequest().
Referenced by PullFile().
PushFile()
Status AdbSyncService::PushFile (const FileSpec & local_file, const FileSpec & remote_file) virtual
Definition at line 567 of file AdbClient.cpp.
References ExecuteCommand(), and PushFileImpl().
PushFileImpl()
Status AdbSyncService::PushFileImpl (const FileSpec & local_file, const FileSpec & remote_file) private
Definition at line 466 of file AdbClient.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::FileSpec::GetPath(), lldb_private::FileSystem::Instance(), kDATA, kDefaultMode, kDONE, kFAIL, kMaxPushData, kOKAY, kSEND, m_conn, ReadAllBytes(), ReadSyncHeader(), and SendSyncRequest().
Referenced by PushFile().
ReadSyncHeader()
Status AdbSyncService::ReadSyncHeader (std::string & response_id, uint32_t & data_len) private
Definition at line 626 of file AdbClient.cpp.
References lldb::eByteOrderLittle, error(), lldb_private::DataExtractor::GetU32(), kSyncPacketLen, m_conn, and ReadAllBytes().
Referenced by PullFileChunk(), and PushFileImpl().
SendSyncRequest()
Status AdbSyncService::SendSyncRequest (const char * request_id, const uint32_t data_len, const void * data) private
Definition at line 608 of file AdbClient.cpp.
References lldb_private::DataEncoder::AppendData(), lldb_private::DataEncoder::AppendU32(), lldb::eByteOrderLittle, error(), lldb_private::DataEncoder::GetData(), kSyncPacketLen, and m_conn.
Referenced by PullFileImpl(), PushFileImpl(), and StatImpl().
SetupSyncConnection()
Status AdbSyncService::SetupSyncConnection ()
Definition at line 672 of file AdbClient.cpp.
References ConnectToAdb(), EnterSyncMode(), error(), m_conn, m_device_id, and SelectTargetDevice().
Stat()
Status AdbSyncService::Stat (const FileSpec & remote_file, uint32_t & mode, uint32_t & size, uint32_t & mtime) virtual
Definition at line 574 of file AdbClient.cpp.
References ExecuteCommand(), and StatImpl().
StatImpl()
Status AdbSyncService::StatImpl (const FileSpec & remote_file, uint32_t & mode, uint32_t & size, uint32_t & mtime) private
Definition at line 524 of file AdbClient.cpp.
References lldb::eByteOrderLittle, error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataExtractor::GetData(), lldb_private::FileSpec::GetPath(), lldb_private::DataExtractor::GetU32(), kSTAT, m_conn, ReadAllBytes(), SendSyncRequest(), and lldb_private::Status.
Referenced by Stat().
Member Data Documentation
m_conn
std::unique_ptr<Connection> lldb_private::platform_android::AdbSyncService::m_conn private
Definition at line 110 of file AdbClient.h.
Referenced by AdbSyncService(), IsConnected(), PullFileChunk(), PushFileImpl(), ReadSyncHeader(), SendSyncRequest(), SetupSyncConnection(), and StatImpl().
m_device_id
std::string lldb_private::platform_android::AdbSyncService::m_device_id private
Definition at line 111 of file AdbClient.h.
Referenced by AdbSyncService(), GetDeviceId(), SetupSyncConnection(), and ~AdbSyncService().
The documentation for this class was generated from the following files:
AdbClient.h
AdbClient.cpp