LLDB: lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 > Class Template Reference
lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 > Class Template Reference
Classes
struct SetItemDescriptor
Public Member Functions
GenericNSSetMSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
~GenericNSSetMSyntheticFrontEnd () override
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Attributes
ExecutionContextRef m_exe_ctx_ref
uint8_t m_ptr_size = 8
D32 * m_data_32
D64 * m_data_64
std::vector< SetItemDescriptor > m_children
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
template<typename D32, typename D64>
class lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >
Definition at line 110 of file NSSet.cpp.
Constructor & Destructor Documentation
GenericNSSetMSyntheticFrontEnd()
template<typename D32, typename D64> lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::GenericNSSetMSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
Definition at line 648 of file NSSet.cpp.
References GenericNSSetMSyntheticFrontEnd(), m_data_32, m_data_64, m_exe_ctx_ref, lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd(), and Update().
Referenced by GenericNSSetMSyntheticFrontEnd().
~GenericNSSetMSyntheticFrontEnd()
template<typename D32, typename D64> lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::~GenericNSSetMSyntheticFrontEnd () override
Member Function Documentation
CalculateNumChildren()
template<typename D32, typename D64> llvm::Expected< uint32_t > lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::CalculateNumChildren () override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 682 of file NSSet.cpp.
References m_data_32, and m_data_64.
GetChildAtIndex()
template<typename D32, typename D64> lldb::ValueObjectSP lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::GetChildAtIndex (uint32_t idx) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 725 of file NSSet.cpp.
References lldb_private::SyntheticChildrenFrontEnd::CalculateNumChildrenIgnoringErrors(), lldb_private::SyntheticChildrenFrontEnd::CreateValueObjectFromData(), lldb::eBasicTypeObjCID, error(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::DataBufferHeap::GetByteSize(), lldb_private::StreamString::GetString(), lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::SetItemDescriptor::item_ptr, lldb_private::SyntheticChildrenFrontEnd::m_backend, m_children, m_data_32, m_data_64, m_exe_ctx_ref, m_ptr_size, lldb_private::Stream::Printf(), and lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::SetItemDescriptor::valobj_sp.
GetIndexOfChildWithName()
template<typename D32, typename D64> llvm::Expected< size_t > lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::GetIndexOfChildWithName (ConstString name) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 666 of file NSSet.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::SyntheticChildrenFrontEnd::CalculateNumChildrenIgnoringErrors(), lldb_private::formatters::ExtractIndexFromString(), and GetIndexOfChildWithName().
Referenced by GetIndexOfChildWithName().
Update()
template<typename D32, typename D64> lldb::ChildCacheState lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::Update () override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 690 of file NSSet.cpp.
References lldb::eRefetch, lldb::eReuse, error(), lldb_private::SyntheticChildrenFrontEnd::m_backend, m_children, m_data_32, m_data_64, m_exe_ctx_ref, and m_ptr_size.
Referenced by GenericNSSetMSyntheticFrontEnd().
Member Data Documentation
m_children
template<typename D32, typename D64> std::vector<SetItemDescriptor> lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::m_children private
Definition at line 135 of file NSSet.cpp.
Referenced by GetChildAtIndex(), and Update().
m_data_32
template<typename D32, typename D64> D32* lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::m_data_32 private
Definition at line 133 of file NSSet.cpp.
Referenced by CalculateNumChildren(), GenericNSSetMSyntheticFrontEnd(), GetChildAtIndex(), and Update().
m_data_64
template<typename D32, typename D64> D64* lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::m_data_64 private
Definition at line 134 of file NSSet.cpp.
Referenced by CalculateNumChildren(), GenericNSSetMSyntheticFrontEnd(), GetChildAtIndex(), and Update().
m_exe_ctx_ref
template<typename D32, typename D64> ExecutionContextRef lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::m_exe_ctx_ref private
Definition at line 131 of file NSSet.cpp.
Referenced by GenericNSSetMSyntheticFrontEnd(), GetChildAtIndex(), and Update().
m_ptr_size
template<typename D32, typename D64> uint8_t lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::m_ptr_size = 8 private
Definition at line 132 of file NSSet.cpp.
Referenced by GetChildAtIndex(), and Update().
The documentation for this class was generated from the following file:
NSSet.cpp