LLDB: CFCMutableDictionary Class Reference
CFCMutableDictionary Class Reference
#include <CFCMutableDictionary.h>
Public Member Functions
CFCMutableDictionary (CFMutableDictionaryRef s=NULL)
CFCMutableDictionary (const CFCMutableDictionary &rhs)
~CFCMutableDictionary () override
const CFCMutableDictionary & operator= (const CFCMutableDictionary &rhs)
CFIndex GetCount () const
CFIndex GetCountOfKey (const void *value) const
CFIndex GetCountOfValue (const void *value) const
void GetKeysAndValues (const void **keys, const void **values) const
const void * GetValue (const void *key) const
Boolean GetValueIfPresent (const void *key, const void **value_handle) const
bool AddValue (CFStringRef key, const void *value, bool can_create=false)
bool SetValue (CFStringRef key, const void *value, bool can_create=false)
bool AddValueSInt8 (CFStringRef key, int8_t value, bool can_create=false)
bool SetValueSInt8 (CFStringRef key, int8_t value, bool can_create=false)
bool AddValueSInt16 (CFStringRef key, int16_t value, bool can_create=false)
bool SetValueSInt16 (CFStringRef key, int16_t value, bool can_create=false)
bool AddValueSInt32 (CFStringRef key, int32_t value, bool can_create=false)
bool SetValueSInt32 (CFStringRef key, int32_t value, bool can_create=false)
bool AddValueSInt64 (CFStringRef key, int64_t value, bool can_create=false)
bool SetValueSInt64 (CFStringRef key, int64_t value, bool can_create=false)
bool AddValueUInt8 (CFStringRef key, uint8_t value, bool can_create=false)
bool SetValueUInt8 (CFStringRef key, uint8_t value, bool can_create=false)
bool AddValueUInt16 (CFStringRef key, uint16_t value, bool can_create=false)
bool SetValueUInt16 (CFStringRef key, uint16_t value, bool can_create=false)
bool AddValueUInt32 (CFStringRef key, uint32_t value, bool can_create=false)
bool SetValueUInt32 (CFStringRef key, uint32_t value, bool can_create=false)
bool AddValueUInt64 (CFStringRef key, uint64_t value, bool can_create=false)
bool SetValueUInt64 (CFStringRef key, uint64_t value, bool can_create=false)
bool AddValueDouble (CFStringRef key, double value, bool can_create=false)
bool SetValueDouble (CFStringRef key, double value, bool can_create=false)
bool AddValueCString (CFStringRef key, const char *cstr, bool can_create=false)
bool SetValueCString (CFStringRef key, const char *cstr, bool can_create=false)
void RemoveValue (const void *value)
void ReplaceValue (const void *key, const void *value)
void RemoveAllValues ()
CFMutableDictionaryRef Dictionary (bool can_create)
Public Member Functions inherited from CFCReleaser< CFMutableDictionaryRef >
CFCReleaser (CFMutableDictionaryRef ptr=NULL)
virtual ~CFCReleaser ()
CFCReleaser & operator= (const CFCReleaser< CFMutableDictionaryRef > &rhs)
CFMutableDictionaryRef * ptr_address (bool enforce_null=true)
CFMutableDictionaryRef get ()
void reset (CFMutableDictionaryRef ptr=NULL)
CFMutableDictionaryRef release ()
Detailed Description
Definition at line 14 of file CFCMutableDictionary.h.
Constructor & Destructor Documentation
CFCMutableDictionary() [1/2]
CFCMutableDictionary::CFCMutableDictionary (CFMutableDictionaryRef s = NULL)
Definition at line 12 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::CFCReleaser().
Referenced by CFCMutableDictionary(), operator=(), and ~CFCMutableDictionary().
CFCMutableDictionary() [2/2]
CFCMutableDictionary::CFCMutableDictionary (const CFCMutableDictionary & rhs) default
References CFCMutableDictionary().
~CFCMutableDictionary()
CFCMutableDictionary::~CFCMutableDictionary () override default
References CFCMutableDictionary().
Member Function Documentation
AddValue()
bool CFCMutableDictionary::AddValue (CFStringRef key, const void * value, bool can_create = false)
Definition at line 91 of file CFCMutableDictionary.cpp.
References Dictionary().
AddValueCString()
bool CFCMutableDictionary::AddValueCString (CFStringRef key, const char * cstr, bool can_create = false)
Definition at line 413 of file CFCMutableDictionary.cpp.
References Dictionary(), and CFCReleaser< T >::get().
AddValueDouble()
bool CFCMutableDictionary::AddValueDouble (CFStringRef key, double value, bool can_create = false)
Definition at line 377 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::CFCReleaser(), Dictionary(), and CFCReleaser< T >::get().
AddValueSInt16()
bool CFCMutableDictionary::AddValueSInt16 (CFStringRef key, int16_t value, bool can_create = false)
Definition at line 143 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::CFCReleaser(), Dictionary(), and CFCReleaser< T >::get().
AddValueSInt32()
bool CFCMutableDictionary::AddValueSInt32 (CFStringRef key, int32_t value, bool can_create = false)
Definition at line 173 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::CFCReleaser(), Dictionary(), and CFCReleaser< T >::get().
AddValueSInt64()
bool CFCMutableDictionary::AddValueSInt64 (CFStringRef key, int64_t value, bool can_create = false)
Definition at line 203 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::CFCReleaser(), Dictionary(), and CFCReleaser< T >::get().
AddValueSInt8()
bool CFCMutableDictionary::AddValueSInt8 (CFStringRef key, int8_t value, bool can_create = false)
Definition at line 113 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::CFCReleaser(), Dictionary(), and CFCReleaser< T >::get().
AddValueUInt16()
bool CFCMutableDictionary::AddValueUInt16 (CFStringRef key, uint16_t value, bool can_create = false)
Definition at line 269 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::CFCReleaser(), Dictionary(), and CFCReleaser< T >::get().
AddValueUInt32()
bool CFCMutableDictionary::AddValueUInt32 (CFStringRef key, uint32_t value, bool can_create = false)
Definition at line 305 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::CFCReleaser(), Dictionary(), and CFCReleaser< T >::get().
AddValueUInt64()
bool CFCMutableDictionary::AddValueUInt64 (CFStringRef key, uint64_t value, bool can_create = false)
Definition at line 341 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::CFCReleaser(), Dictionary(), and CFCReleaser< T >::get().
AddValueUInt8()
bool CFCMutableDictionary::AddValueUInt8 (CFStringRef key, uint8_t value, bool can_create = false)
Definition at line 233 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::CFCReleaser(), Dictionary(), and CFCReleaser< T >::get().
Dictionary()
CFMutableDictionaryRef CFCMutableDictionary::Dictionary (bool can_create)
Definition at line 80 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::get(), and CFCReleaser< CFMutableDictionaryRef >::reset().
Referenced by AddValue(), AddValueCString(), AddValueDouble(), AddValueSInt16(), AddValueSInt32(), AddValueSInt64(), AddValueSInt8(), AddValueUInt16(), AddValueUInt32(), AddValueUInt64(), AddValueUInt8(), SetValue(), SetValueCString(), SetValueDouble(), SetValueSInt16(), SetValueSInt32(), SetValueSInt64(), SetValueSInt8(), SetValueUInt16(), SetValueUInt32(), SetValueUInt64(), and SetValueUInt8().
GetCount()
CFIndex CFCMutableDictionary::GetCount () const
Definition at line 30 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::get().
GetCountOfKey()
CFIndex CFCMutableDictionary::GetCountOfKey (const void * value) const
Definition at line 37 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::get().
GetCountOfValue()
CFIndex CFCMutableDictionary::GetCountOfValue (const void * value) const
Definition at line 46 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::get().
GetKeysAndValues()
void CFCMutableDictionary::GetKeysAndValues (const void ** keys, const void ** values) const
Definition at line 55 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::get().
GetValue()
const void * CFCMutableDictionary::GetValue (const void * key) const
Definition at line 62 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::get().
GetValueIfPresent()
Boolean CFCMutableDictionary::GetValueIfPresent (const void * key, const void ** value_handle) const
Definition at line 72 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::get().
operator=()
const CFCMutableDictionary & CFCMutableDictionary::operator= (const CFCMutableDictionary & rhs)
Definition at line 20 of file CFCMutableDictionary.cpp.
References CFCMutableDictionary().
RemoveAllValues()
void CFCMutableDictionary::RemoveAllValues ()
Definition at line 441 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::get().
RemoveValue()
void CFCMutableDictionary::RemoveValue (const void * value)
Definition at line 447 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::get().
ReplaceValue()
void CFCMutableDictionary::ReplaceValue (const void * key, const void * value)
Definition at line 452 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::get().
SetValue()
bool CFCMutableDictionary::SetValue (CFStringRef key, const void * value, bool can_create = false)
Definition at line 102 of file CFCMutableDictionary.cpp.
References Dictionary().
SetValueCString()
bool CFCMutableDictionary::SetValueCString (CFStringRef key, const char * cstr, bool can_create = false)
Definition at line 427 of file CFCMutableDictionary.cpp.
References Dictionary(), and CFCReleaser< T >::get().
SetValueDouble()
bool CFCMutableDictionary::SetValueDouble (CFStringRef key, double value, bool can_create = false)
Definition at line 395 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::CFCReleaser(), Dictionary(), and CFCReleaser< T >::get().
SetValueSInt16()
bool CFCMutableDictionary::SetValueSInt16 (CFStringRef key, int16_t value, bool can_create = false)
Definition at line 158 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::CFCReleaser(), Dictionary(), and CFCReleaser< T >::get().
SetValueSInt32()
bool CFCMutableDictionary::SetValueSInt32 (CFStringRef key, int32_t value, bool can_create = false)
Definition at line 188 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::CFCReleaser(), Dictionary(), and CFCReleaser< T >::get().
SetValueSInt64()
bool CFCMutableDictionary::SetValueSInt64 (CFStringRef key, int64_t value, bool can_create = false)
Definition at line 218 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::CFCReleaser(), Dictionary(), and CFCReleaser< T >::get().
SetValueSInt8()
bool CFCMutableDictionary::SetValueSInt8 (CFStringRef key, int8_t value, bool can_create = false)
Definition at line 128 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::CFCReleaser(), Dictionary(), and CFCReleaser< T >::get().
SetValueUInt16()
bool CFCMutableDictionary::SetValueUInt16 (CFStringRef key, uint16_t value, bool can_create = false)
Definition at line 287 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::CFCReleaser(), Dictionary(), and CFCReleaser< T >::get().
SetValueUInt32()
bool CFCMutableDictionary::SetValueUInt32 (CFStringRef key, uint32_t value, bool can_create = false)
Definition at line 323 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::CFCReleaser(), Dictionary(), and CFCReleaser< T >::get().
SetValueUInt64()
bool CFCMutableDictionary::SetValueUInt64 (CFStringRef key, uint64_t value, bool can_create = false)
Definition at line 359 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::CFCReleaser(), Dictionary(), and CFCReleaser< T >::get().
SetValueUInt8()
bool CFCMutableDictionary::SetValueUInt8 (CFStringRef key, uint8_t value, bool can_create = false)
Definition at line 251 of file CFCMutableDictionary.cpp.
References CFCReleaser< CFMutableDictionaryRef >::CFCReleaser(), Dictionary(), and CFCReleaser< T >::get().
The documentation for this class was generated from the following files:
CFCMutableDictionary.h
CFCMutableDictionary.cpp