LLDB: lldb_private::SummaryStatistics::SummaryInvocation Class Reference
lldb_private::SummaryStatistics::SummaryInvocation Class Reference
Basic RAII class to increment the summary count when the call is complete.
#include <Statistics.h>
Public Member Functions
SummaryInvocation (SummaryStatisticsSP summary_stats)
~SummaryInvocation ()
SummaryInvocation (const SummaryInvocation &)=delete
Delete the copy constructor and assignment operator to prevent accidental double counting.
SummaryInvocation & operator= (const SummaryInvocation &)=delete
Private Attributes
SummaryStatisticsSP m_stats
ElapsedTime m_elapsed_time
Detailed Description
Basic RAII class to increment the summary count when the call is complete.
Definition at line 256 of file Statistics.h.
Constructor & Destructor Documentation
SummaryInvocation() [1/2]
lldb_private::SummaryStatistics::SummaryInvocation::SummaryInvocation (SummaryStatisticsSP summary_stats) inline
Definition at line 258 of file Statistics.h.
References lldb_private::SummaryStatistics::GetDurationReference(), m_elapsed_time, and m_stats.
Referenced by operator=(), and SummaryInvocation().
~SummaryInvocation()
lldb_private::SummaryStatistics::SummaryInvocation::~SummaryInvocation () inline
Definition at line 261 of file Statistics.h.
References m_stats.
SummaryInvocation() [2/2]
lldb_private::SummaryStatistics::SummaryInvocation::SummaryInvocation (const SummaryInvocation &) delete
Delete the copy constructor and assignment operator to prevent accidental double counting.
References SummaryInvocation().
Member Function Documentation
operator=()
SummaryInvocation & lldb_private::SummaryStatistics::SummaryInvocation::operator= (const SummaryInvocation &) delete
References SummaryInvocation().
Member Data Documentation
m_elapsed_time
ElapsedTime lldb_private::SummaryStatistics::SummaryInvocation::m_elapsed_time private
Definition at line 272 of file Statistics.h.
Referenced by SummaryInvocation().
m_stats
SummaryStatisticsSP lldb_private::SummaryStatistics::SummaryInvocation::m_stats private
Definition at line 271 of file Statistics.h.
Referenced by SummaryInvocation(), and ~SummaryInvocation().
The documentation for this class was generated from the following file:
Statistics.h