LLDB: lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion Class Reference
lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion Class Reference
Public Member Functions
VTableRegion ()=default
VTableRegion (AppleObjCVTables *owner, lldb::addr_t header_addr)
void SetUpRegion ()
lldb::addr_t GetNextRegionAddr ()
lldb::addr_t GetCodeStart ()
lldb::addr_t GetCodeEnd ()
uint32_t GetFlagsForVTableAtAddress (lldb::addr_t address)
bool IsValid ()
bool AddressInRegion (lldb::addr_t addr, uint32_t &flags)
void Dump (Stream &s)
Public Attributes
bool m_valid = false
AppleObjCVTables * m_owner = nullptr
lldb::addr_t m_header_addr = LLDB_INVALID_ADDRESS
lldb::addr_t m_code_start_addr = 0
lldb::addr_t m_code_end_addr = 0
std::vector< VTableDescriptor > m_descriptors
lldb::addr_t m_next_region = 0
Detailed Description
Definition at line 87 of file AppleObjCTrampolineHandler.h.
Constructor & Destructor Documentation
VTableRegion() [1/2]
lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::VTableRegion () default
References lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::AppleObjCVTables().
VTableRegion() [2/2]
AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::VTableRegion (AppleObjCVTables * owner, lldb::addr_t header_addr)
Definition at line 181 of file AppleObjCTrampolineHandler.cpp.
References lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::AppleObjCVTables(), m_header_addr, m_owner, m_valid, and SetUpRegion().
Member Function Documentation
AddressInRegion()
bool AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::AddressInRegion (lldb::addr_t addr, uint32_t & flags)
Definition at line 298 of file AppleObjCTrampolineHandler.cpp.
References IsValid(), m_code_end_addr, and m_descriptors.
Dump()
void AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::Dump (Stream & s)
Definition at line 316 of file AppleObjCTrampolineHandler.cpp.
References lldb_private::Stream::Indent(), m_code_end_addr, m_code_start_addr, m_descriptors, m_header_addr, m_next_region, and lldb_private::Stream::Printf().
GetCodeEnd()
lldb::addr_t lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::GetCodeEnd () inline
Definition at line 99 of file AppleObjCTrampolineHandler.h.
References m_code_end_addr.
GetCodeStart()
lldb::addr_t lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::GetCodeStart () inline
Definition at line 97 of file AppleObjCTrampolineHandler.h.
References m_code_start_addr.
GetFlagsForVTableAtAddress()
uint32_t lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::GetFlagsForVTableAtAddress (lldb::addr_t address) inline
Definition at line 101 of file AppleObjCTrampolineHandler.h.
GetNextRegionAddr()
lldb::addr_t lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::GetNextRegionAddr () inline
Definition at line 95 of file AppleObjCTrampolineHandler.h.
References m_next_region.
IsValid()
bool lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::IsValid () inline
Definition at line 103 of file AppleObjCTrampolineHandler.h.
References m_valid.
Referenced by AddressInRegion().
SetUpRegion()
void AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::SetUpRegion ()
Definition at line 189 of file AppleObjCTrampolineHandler.cpp.
References error(), lldb_private::DataExtractor::GetAddress(), lldb_private::DataExtractor::GetU16(), lldb_private::DataExtractor::GetU32(), m_code_end_addr, m_code_start_addr, m_descriptors, m_header_addr, m_next_region, m_owner, and m_valid.
Referenced by VTableRegion().
Member Data Documentation
m_code_end_addr
lldb::addr_t lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::m_code_end_addr = 0
Definition at line 113 of file AppleObjCTrampolineHandler.h.
Referenced by AddressInRegion(), Dump(), GetCodeEnd(), and SetUpRegion().
m_code_start_addr
lldb::addr_t lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::m_code_start_addr = 0
Definition at line 112 of file AppleObjCTrampolineHandler.h.
Referenced by Dump(), GetCodeStart(), and SetUpRegion().
m_descriptors
std::vector<VTableDescriptor> lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::m_descriptors
Definition at line 114 of file AppleObjCTrampolineHandler.h.
Referenced by AddressInRegion(), Dump(), and SetUpRegion().
m_header_addr
lldb::addr_t lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::m_header_addr = LLDB_INVALID_ADDRESS
Definition at line 111 of file AppleObjCTrampolineHandler.h.
Referenced by Dump(), SetUpRegion(), and VTableRegion().
m_next_region
lldb::addr_t lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::m_next_region = 0
Definition at line 115 of file AppleObjCTrampolineHandler.h.
Referenced by Dump(), GetNextRegionAddr(), and SetUpRegion().
m_owner
AppleObjCVTables* lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::m_owner = nullptr
Definition at line 110 of file AppleObjCTrampolineHandler.h.
Referenced by SetUpRegion(), and VTableRegion().
m_valid
bool lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::m_valid = false
Definition at line 109 of file AppleObjCTrampolineHandler.h.
Referenced by IsValid(), SetUpRegion(), and VTableRegion().
The documentation for this class was generated from the following files:
AppleObjCTrampolineHandler.h
AppleObjCTrampolineHandler.cpp