LLDB: lldb_private::EventData Class Reference
lldb_private::EventData Class Reference abstract
#include <Event.h>
Public Member Functions
EventData ()
virtual ~EventData ()
virtual llvm::StringRef GetFlavor () const =0
virtual Log * GetLogChannel ()
virtual void Dump (Stream *s) const
Private Member Functions
virtual bool ForwardEventToPendingListeners (Event *event_ptr)
This will be queried for a Broadcaster with a primary and some secondary listeners after the primary listener pulled the event from the event queue and ran its DoOnRemoval, right before the event is delivered.
virtual void DoOnRemoval (Event *event_ptr)
EventData (const EventData &)=delete
const EventData & operator= (const EventData &)=delete
Friends
class Event
Detailed Description
Definition at line 35 of file Event.h.
Constructor & Destructor Documentation
EventData() [1/2]
EventData::EventData () default
Referenced by EventData(), lldb_private::EventDataStructuredData::EventDataStructuredData(), lldb_private::EventDataStructuredData::EventDataStructuredData(), lldb_private::Breakpoint::BreakpointEventData::GetEventDataFromEvent(), lldb_private::EventDataBytes::GetEventDataFromEvent(), lldb_private::EventDataStructuredData::GetEventDataFromEvent(), lldb_private::Process::ProcessEventData::GetEventDataFromEvent(), lldb_private::Target::TargetEventData::GetEventDataFromEvent(), lldb_private::Thread::ThreadEventData::GetEventDataFromEvent(), lldb_private::Watchpoint::WatchpointEventData::GetEventDataFromEvent(), operator=(), lldb_private::Process::ProcessEventData::ProcessEventData(), lldb_private::Process::ProcessEventData::ProcessEventData(), lldb_private::Target::TargetEventData::TargetEventData(), lldb_private::Target::TargetEventData::TargetEventData(), and lldb_private::Target::TargetEventData::TargetEventData().
~EventData()
EventData::~EventData () virtual default
EventData() [2/2]
lldb_private::EventData::EventData (const EventData &) private delete
References EventData().
Member Function Documentation
DoOnRemoval()
virtual void lldb_private::EventData::DoOnRemoval (Event * event_ptr) inline private virtual
Reimplemented in lldb_private::EventDataReceipt, lldb_private::Process::ProcessEventData, and lldb_private::SymbolChangeEventData.
Definition at line 61 of file Event.h.
References Event.
Dump()
void EventData::Dump (Stream * s) const virtual
Reimplemented in lldb_private::Breakpoint::BreakpointEventData, lldb_private::DiagnosticEventData, lldb_private::EventDataBytes, lldb_private::EventDataStructuredData, lldb_private::Process::ProcessEventData, lldb_private::ProgressEventData, lldb_private::Target::TargetEventData, lldb_private::Thread::ThreadEventData, and lldb_private::Watchpoint::WatchpointEventData.
Definition at line 111 of file Event.cpp.
References lldb_private::Stream::PutCString().
ForwardEventToPendingListeners()
virtual bool lldb_private::EventData::ForwardEventToPendingListeners (Event * event_ptr) inline private virtual
This will be queried for a Broadcaster with a primary and some secondary listeners after the primary listener pulled the event from the event queue and ran its DoOnRemoval, right before the event is delivered.
If it returns true, the event will also be forwarded to the secondary listeners, and if false, event propagation stops at the primary listener. Some broadcasters (particularly the Process broadcaster) fetch events on a private Listener, and then forward the event to the Public Listeners after some processing. The Process broadcaster does not want to forward to the secondary listeners at the private processing stage.
Reimplemented in lldb_private::Process::ProcessEventData.
Definition at line 59 of file Event.h.
References Event.
GetFlavor()
virtual llvm::StringRef lldb_private::EventData::GetFlavor () const pure virtual
Implemented in lldb_private::Breakpoint::BreakpointEventData, lldb_private::DiagnosticEventData, lldb_private::EventDataBytes, lldb_private::EventDataReceipt, lldb_private::EventDataStructuredData, lldb_private::Process::ProcessEventData, lldb_private::ProgressEventData, lldb_private::SymbolChangeEventData, lldb_private::Target::TargetEventData, lldb_private::Thread::ThreadEventData, and lldb_private::Watchpoint::WatchpointEventData.
Referenced by lldb::SBProcess::EventIsStructuredDataEvent(), lldb::SBEvent::GetDataFlavor(), lldb_private::Breakpoint::BreakpointEventData::GetEventDataFromEvent(), lldb_private::EventDataBytes::GetEventDataFromEvent(), lldb_private::EventDataStructuredData::GetEventDataFromEvent(), lldb_private::Process::ProcessEventData::GetEventDataFromEvent(), lldb_private::Target::TargetEventData::GetEventDataFromEvent(), lldb_private::Thread::ThreadEventData::GetEventDataFromEvent(), and lldb_private::Watchpoint::WatchpointEventData::GetEventDataFromEvent().
GetLogChannel()
virtual Log * lldb_private::EventData::GetLogChannel () inline virtual
Reimplemented in lldb_private::Breakpoint::BreakpointEventData.
Definition at line 45 of file Event.h.
operator=()
const EventData & lldb_private::EventData::operator= (const EventData &) private delete
References EventData().
Friends And Related Symbol Documentation
Event
friend class Event friend
Definition at line 36 of file Event.h.
References Event.
Referenced by lldb_private::Process::ProcessEventData::AddRestartedReason(), DoOnRemoval(), lldb_private::EventDataReceipt::DoOnRemoval(), lldb_private::Process::ProcessEventData::DoOnRemoval(), lldb_private::SymbolChangeEventData::DoOnRemoval(), Event, ForwardEventToPendingListeners(), lldb_private::Process::ProcessEventData::ForwardEventToPendingListeners(), lldb_private::DiagnosticEventData::GetAsStructuredData(), lldb_private::ProgressEventData::GetAsStructuredData(), lldb_private::EventDataBytes::GetBytesFromEvent(), lldb_private::EventDataBytes::GetByteSizeFromEvent(), lldb_private::Target::TargetEventData::GetCreatedTargetFromEvent(), lldb_private::Breakpoint::BreakpointEventData::GetEventDataFromEvent(), lldb_private::DiagnosticEventData::GetEventDataFromEvent(), lldb_private::EventDataBytes::GetEventDataFromEvent(), lldb_private::EventDataStructuredData::GetEventDataFromEvent(), lldb_private::Process::ProcessEventData::GetEventDataFromEvent(), lldb_private::ProgressEventData::GetEventDataFromEvent(), lldb_private::SymbolChangeEventData::GetEventDataFromEvent(), lldb_private::Target::TargetEventData::GetEventDataFromEvent(), lldb_private::Thread::ThreadEventData::GetEventDataFromEvent(), lldb_private::Watchpoint::WatchpointEventData::GetEventDataFromEvent(), lldb_private::Process::ProcessEventData::GetInterruptedFromEvent(), lldb_private::Target::TargetEventData::GetModuleListFromEvent(), lldb_private::Process::ProcessEventData::GetNumRestartedReasons(), lldb_private::EventDataStructuredData::GetObjectFromEvent(), lldb_private::EventDataStructuredData::GetPluginFromEvent(), lldb_private::EventDataStructuredData::GetProcessFromEvent(), lldb_private::Process::ProcessEventData::GetProcessFromEvent(), lldb_private::Process::ProcessEventData::GetRestartedFromEvent(), lldb_private::Process::ProcessEventData::GetRestartedReasonAtIndex(), lldb_private::Thread::ThreadEventData::GetStackFrameFromEvent(), lldb_private::Thread::ThreadEventData::GetStackIDFromEvent(), lldb_private::Process::ProcessEventData::GetStateFromEvent(), lldb_private::Target::TargetEventData::GetTargetFromEvent(), lldb_private::Thread::ThreadEventData::GetThreadFromEvent(), lldb_private::Process::ProcessEventData::SetInterruptedInEvent(), lldb_private::Process::ProcessEventData::SetRestartedInEvent(), lldb_private::Process::ProcessEventData::SetUpdateStateOnRemoval(), lldb_private::Process::ProcessEventData::ShouldStop(), lldb_private::EventDataBytes::~EventDataBytes(), lldb_private::EventDataStructuredData::~EventDataStructuredData(), and lldb_private::Watchpoint::WatchpointEventData::~WatchpointEventData().
The documentation for this class was generated from the following files:
Event.h
Event.cpp