LLDB: RegisterContextPOSIX_x86 Class Reference
RegisterContextPOSIX_x86 Class Reference abstract
#include <RegisterContextPOSIX_x86.h>
Public Types
enum FPRType {
eNotValid = 0 , eFSAVE , eFXSAVE , eSOFT ,
eXSAVE
}
Public Member Functions
RegisterContextPOSIX_x86 (lldb_private::Thread &thread, uint32_t concrete_frame_idx, lldb_private::RegisterInfoInterface *register_info)
~RegisterContextPOSIX_x86 () override
void Invalidate ()
void InvalidateAllRegisters () override
size_t GetRegisterCount () override
virtual size_t GetGPRSize ()
virtual size_t GetFXSAVEOffset ()
virtual unsigned GetRegisterSize (unsigned reg)
virtual unsigned GetRegisterOffset (unsigned reg)
const lldb_private::RegisterInfo * GetRegisterInfoAtIndex (size_t reg) override
size_t GetRegisterSetCount () override
const lldb_private::RegisterSet * GetRegisterSet (size_t set) override
const char * GetRegisterName (unsigned reg)
Public Member Functions inherited from lldb_private::RegisterContext
RegisterContext (Thread &thread, uint32_t concrete_frame_idx)
~RegisterContext () override
void InvalidateIfNeeded (bool force)
virtual lldb::ByteOrder GetByteOrder ()
virtual bool ReadRegister (const RegisterInfo *reg_info, RegisterValue &reg_value)=0
virtual bool WriteRegister (const RegisterInfo *reg_info, const RegisterValue &reg_value)=0
virtual bool ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp)
virtual bool WriteAllRegisterValues (const lldb::DataBufferSP &data_sp)
virtual bool RegisterWriteCausesReconfigure (const llvm::StringRef name)
virtual bool ReconfigureRegisterInfo ()
virtual bool ReadAllRegisterValues (lldb_private::RegisterCheckpoint &reg_checkpoint)
virtual bool WriteAllRegisterValues (const lldb_private::RegisterCheckpoint &reg_checkpoint)
bool CopyFromRegisterContext (lldb::RegisterContextSP context)
virtual uint32_t ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num)
Convert from a given register numbering scheme to the lldb register numbering scheme.
virtual uint32_t NumSupportedHardwareBreakpoints ()
virtual uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual bool ClearHardwareBreakpoint (uint32_t hw_idx)
virtual uint32_t NumSupportedHardwareWatchpoints ()
virtual uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, bool read, bool write)
virtual bool ClearHardwareWatchpoint (uint32_t hw_index)
virtual bool HardwareSingleStep (bool enable)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, uint32_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, uint32_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual Thread & GetThread ()
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num)
uint64_t GetPC (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetThreadPointer (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool GetPCForSymbolication (Address &address)
Get an address suitable for symbolication.
bool SetPC (uint64_t pc)
bool SetPC (Address addr)
uint64_t GetSP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetSP (uint64_t sp)
uint64_t GetFP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetFP (uint64_t fp)
const char * GetRegisterName (uint32_t reg)
uint64_t GetReturnAddress (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetFlags (uint64_t fail_value=0)
uint64_t ReadRegisterAsUnsigned (uint32_t reg, uint64_t fail_value)
uint64_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, uint64_t fail_value)
bool WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
bool WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
bool ConvertBetweenRegisterKinds (lldb::RegisterKind source_rk, uint32_t source_regnum, lldb::RegisterKind target_rk, uint32_t &target_regnum)
lldb::TargetSP CalculateTarget () override
lldb::ProcessSP CalculateProcess () override
lldb::ThreadSP CalculateThread () override
lldb::StackFrameSP CalculateStackFrame () override
void CalculateExecutionContext (ExecutionContext &exe_ctx) override
Reconstruct the object's execution context into sc.
uint32_t GetStopID () const
void SetStopID (uint32_t stop_id)
Public Member Functions inherited from lldb_private::ExecutionContextScope
virtual ~ExecutionContextScope ()=default
Static Public Attributes
static uint32_t g_contained_eax []
static uint32_t g_contained_ebx []
static uint32_t g_contained_ecx []
static uint32_t g_contained_edx []
static uint32_t g_contained_edi []
static uint32_t g_contained_esi []
static uint32_t g_contained_ebp []
static uint32_t g_contained_esp []
static uint32_t g_invalidate_eax []
static uint32_t g_invalidate_ebx []
static uint32_t g_invalidate_ecx []
static uint32_t g_invalidate_edx []
static uint32_t g_invalidate_edi []
static uint32_t g_invalidate_esi []
static uint32_t g_invalidate_ebp []
static uint32_t g_invalidate_esp []
static uint32_t g_contained_rax []
static uint32_t g_contained_rbx []
static uint32_t g_contained_rcx []
static uint32_t g_contained_rdx []
static uint32_t g_contained_rdi []
static uint32_t g_contained_rsi []
static uint32_t g_contained_rbp []
static uint32_t g_contained_rsp []
static uint32_t g_contained_r8 []
static uint32_t g_contained_r9 []
static uint32_t g_contained_r10 []
static uint32_t g_contained_r11 []
static uint32_t g_contained_r12 []
static uint32_t g_contained_r13 []
static uint32_t g_contained_r14 []
static uint32_t g_contained_r15 []
static uint32_t g_invalidate_rax []
static uint32_t g_invalidate_rbx []
static uint32_t g_invalidate_rcx []
static uint32_t g_invalidate_rdx []
static uint32_t g_invalidate_rdi []
static uint32_t g_invalidate_rsi []
static uint32_t g_invalidate_rbp []
static uint32_t g_invalidate_rsp []
static uint32_t g_invalidate_r8 []
static uint32_t g_invalidate_r9 []
static uint32_t g_invalidate_r10 []
static uint32_t g_invalidate_r11 []
static uint32_t g_invalidate_r12 []
static uint32_t g_invalidate_r13 []
static uint32_t g_invalidate_r14 []
static uint32_t g_invalidate_r15 []
static uint32_t g_contained_fip []
static uint32_t g_contained_fdp []
static uint32_t g_invalidate_fip []
static uint32_t g_invalidate_fdp []
static uint32_t g_contained_st0_32 []
static uint32_t g_contained_st1_32 []
static uint32_t g_contained_st2_32 []
static uint32_t g_contained_st3_32 []
static uint32_t g_contained_st4_32 []
static uint32_t g_contained_st5_32 []
static uint32_t g_contained_st6_32 []
static uint32_t g_contained_st7_32 []
static uint32_t g_invalidate_st0_32 []
static uint32_t g_invalidate_st1_32 []
static uint32_t g_invalidate_st2_32 []
static uint32_t g_invalidate_st3_32 []
static uint32_t g_invalidate_st4_32 []
static uint32_t g_invalidate_st5_32 []
static uint32_t g_invalidate_st6_32 []
static uint32_t g_invalidate_st7_32 []
static uint32_t g_contained_st0_64 []
static uint32_t g_contained_st1_64 []
static uint32_t g_contained_st2_64 []
static uint32_t g_contained_st3_64 []
static uint32_t g_contained_st4_64 []
static uint32_t g_contained_st5_64 []
static uint32_t g_contained_st6_64 []
static uint32_t g_contained_st7_64 []
static uint32_t g_invalidate_st0_64 []
static uint32_t g_invalidate_st1_64 []
static uint32_t g_invalidate_st2_64 []
static uint32_t g_invalidate_st3_64 []
static uint32_t g_invalidate_st4_64 []
static uint32_t g_invalidate_st5_64 []
static uint32_t g_invalidate_st6_64 []
static uint32_t g_invalidate_st7_64 []
Protected Member Functions
virtual bool IsRegisterSetAvailable (size_t set_index)
virtual const lldb_private::RegisterInfo * GetRegisterInfo ()
bool IsGPR (unsigned reg)
bool IsFPR (unsigned reg)
bool IsAVX (unsigned reg)
bool CopyXSTATEtoYMM (uint32_t reg, lldb::ByteOrder byte_order)
bool CopyYMMtoXSTATE (uint32_t reg, lldb::ByteOrder byte_order)
bool IsFPR (unsigned reg, FPRType fpr_type)
FPRType GetFPRType ()
virtual bool ReadGPR ()=0
virtual bool ReadFPR ()=0
virtual bool WriteGPR ()=0
virtual bool WriteFPR ()=0
virtual lldb_private::RegInfo & GetRegInfo ()
Protected Member Functions inherited from lldb_private::RegisterContext
virtual bool BehavesLikeZerothFrame () const
Indicates that this frame is currently executing code, that the PC value is not a return-pc but an actual executing instruction.
Protected Attributes
FPRType m_fpr_type
lldb_private::FPR m_fpr
lldb_private::YMM m_ymm_set
std::unique_ptr< lldb_private::RegisterInfoInterface > m_register_info_up
Protected Attributes inherited from lldb_private::RegisterContext
Thread & m_thread
uint32_t m_concrete_frame_idx
uint32_t m_stop_id
Detailed Description
Definition at line 19 of file RegisterContextPOSIX_x86.h.
Member Enumeration Documentation
FPRType
enum RegisterContextPOSIX_x86::FPRType
Enumerator
eNotValid
eFSAVE
eFXSAVE
eSOFT
eXSAVE
Definition at line 50 of file RegisterContextPOSIX_x86.h.
Constructor & Destructor Documentation
RegisterContextPOSIX_x86()
RegisterContextPOSIX_x86::RegisterContextPOSIX_x86 (lldb_private::Thread & thread, uint32_t concrete_frame_idx, lldb_private::RegisterInfoInterface * register_info)
Definition at line 396 of file RegisterContextPOSIX_x86.cpp.
References eNotValid, m_fpr, m_fpr_type, m_register_info_up, m_ymm_set, and lldb_private::RegisterContext::RegisterContext().
Referenced by RegisterContextCorePOSIX_x86::RegisterContextCorePOSIX_x86(), RegisterContextFreeBSDKernelCore_i386::RegisterContextFreeBSDKernelCore_i386(), and RegisterContextFreeBSDKernelCore_x86_64::RegisterContextFreeBSDKernelCore_x86_64().
~RegisterContextPOSIX_x86()
RegisterContextPOSIX_x86::~RegisterContextPOSIX_x86 () override default
Member Function Documentation
CopyXSTATEtoYMM()
bool RegisterContextPOSIX_x86::CopyXSTATEtoYMM (uint32_t reg, lldb::ByteOrder byte_order) protected
Definition at line 518 of file RegisterContextPOSIX_x86.cpp.
References lldb::eByteOrderLittle, lldb_private::RegInfo::first_ymm, GetRegInfo(), IsAVX(), m_fpr, m_ymm_set, and lldb_private::XStateToYMM().
CopyYMMtoXSTATE()
bool RegisterContextPOSIX_x86::CopyYMMtoXSTATE (uint32_t reg, lldb::ByteOrder byte_order) protected
Definition at line 502 of file RegisterContextPOSIX_x86.cpp.
References lldb::eByteOrderLittle, lldb_private::RegInfo::first_ymm, GetRegInfo(), IsAVX(), m_fpr, m_ymm_set, and lldb_private::YMMToXState().
GetFPRType()
RegisterContextPOSIX_x86::FPRType RegisterContextPOSIX_x86::GetFPRType () protected
Definition at line 410 of file RegisterContextPOSIX_x86.cpp.
References eFXSAVE, eNotValid, eXSAVE, m_fpr_type, and ReadFPR().
Referenced by GetRegisterCount(), and IsRegisterSetAvailable().
GetFXSAVEOffset()
size_t RegisterContextPOSIX_x86::GetFXSAVEOffset () virtual
Definition at line 452 of file RegisterContextPOSIX_x86.cpp.
References lldb_private::RegisterInfo::byte_offset, lldb_private::RegInfo::first_fpr, GetRegInfo(), and GetRegisterInfo().
Referenced by RegisterContextCorePOSIX_x86::ReadRegister().
GetGPRSize()
size_t RegisterContextPOSIX_x86::GetGPRSize () virtual
Definition at line 448 of file RegisterContextPOSIX_x86.cpp.
References m_register_info_up.
Referenced by RegisterContextCorePOSIX_x86::ReadRegister(), and RegisterContextCorePOSIX_x86::RegisterContextCorePOSIX_x86().
GetRegInfo()
RegInfo & RegisterContextPOSIX_x86::GetRegInfo () protected virtual
Reimplemented in RegisterContextLinuxCore_x86.
Definition at line 429 of file RegisterContextPOSIX_x86.cpp.
References lldb_private::GetRegInfoShared(), and m_register_info_up.
Referenced by CopyXSTATEtoYMM(), CopyYMMtoXSTATE(), GetFXSAVEOffset(), GetRegisterCount(), GetRegisterInfoAtIndex(), GetRegisterName(), GetRegisterOffset(), GetRegisterSize(), IsAVX(), IsFPR(), and IsGPR().
GetRegisterCount()
size_t RegisterContextPOSIX_x86::GetRegisterCount () override virtual
Implements lldb_private::RegisterContext.
Definition at line 440 of file RegisterContextPOSIX_x86.cpp.
References eXSAVE, GetFPRType(), GetRegInfo(), lldb_private::RegInfo::num_avx_registers, lldb_private::RegInfo::num_fpr_registers, and lldb_private::RegInfo::num_gpr_registers.
GetRegisterInfo()
const RegisterInfo * RegisterContextPOSIX_x86::GetRegisterInfo () protected virtual
Definition at line 456 of file RegisterContextPOSIX_x86.cpp.
References m_register_info_up.
Referenced by GetFXSAVEOffset(), GetRegisterInfoAtIndex(), GetRegisterName(), GetRegisterOffset(), and GetRegisterSize().
GetRegisterInfoAtIndex()
const RegisterInfo * RegisterContextPOSIX_x86::GetRegisterInfoAtIndex (size_t reg) override virtual
Implements lldb_private::RegisterContext.
Definition at line 464 of file RegisterContextPOSIX_x86.cpp.
References GetRegInfo(), and GetRegisterInfo().
GetRegisterName()
const char * RegisterContextPOSIX_x86::GetRegisterName (unsigned reg)
Definition at line 496 of file RegisterContextPOSIX_x86.cpp.
References GetRegInfo(), GetRegisterInfo(), and lldb_private::RegisterInfo::name.
GetRegisterOffset()
unsigned RegisterContextPOSIX_x86::GetRegisterOffset (unsigned reg) virtual
Definition at line 424 of file RegisterContextPOSIX_x86.cpp.
References lldb_private::RegisterInfo::byte_offset, GetRegInfo(), and GetRegisterInfo().
GetRegisterSet()
const RegisterSet * RegisterContextPOSIX_x86::GetRegisterSet (size_t set) override virtual
Implements lldb_private::RegisterContext.
Definition at line 481 of file RegisterContextPOSIX_x86.cpp.
References g_reg_sets_i386, g_reg_sets_x86_64, IsRegisterSetAvailable(), and m_register_info_up.
GetRegisterSetCount()
size_t RegisterContextPOSIX_x86::GetRegisterSetCount () override virtual
Implements lldb_private::RegisterContext.
Definition at line 471 of file RegisterContextPOSIX_x86.cpp.
References IsRegisterSetAvailable(), and k_num_register_sets.
GetRegisterSize()
unsigned RegisterContextPOSIX_x86::GetRegisterSize (unsigned reg) virtual
Definition at line 435 of file RegisterContextPOSIX_x86.cpp.
References lldb_private::RegisterInfo::byte_size, GetRegInfo(), and GetRegisterInfo().
Invalidate()
void RegisterContextPOSIX_x86::Invalidate ()
Definition at line 420 of file RegisterContextPOSIX_x86.cpp.
InvalidateAllRegisters()
void RegisterContextPOSIX_x86::InvalidateAllRegisters () override virtual
Implements lldb_private::RegisterContext.
Definition at line 422 of file RegisterContextPOSIX_x86.cpp.
IsAVX()
bool RegisterContextPOSIX_x86::IsAVX (unsigned reg) protected
Definition at line 384 of file RegisterContextPOSIX_x86.cpp.
References GetRegInfo().
Referenced by CopyXSTATEtoYMM(), CopyYMMtoXSTATE(), and IsFPR().
IsFPR() [1/2]
bool RegisterContextPOSIX_x86::IsFPR (unsigned reg) protected
Definition at line 380 of file RegisterContextPOSIX_x86.cpp.
References GetRegInfo().
Referenced by IsFPR().
IsFPR() [2/2]
bool RegisterContextPOSIX_x86::IsFPR (unsigned reg, FPRType fpr_type) protected
Definition at line 388 of file RegisterContextPOSIX_x86.cpp.
References eXSAVE, IsAVX(), and IsFPR().
IsGPR()
bool RegisterContextPOSIX_x86::IsGPR (unsigned reg) protected
Definition at line 376 of file RegisterContextPOSIX_x86.cpp.
References GetRegInfo(), and lldb_private::RegInfo::last_gpr.
IsRegisterSetAvailable()
bool RegisterContextPOSIX_x86::IsRegisterSetAvailable (size_t set_index) protected virtual
Definition at line 533 of file RegisterContextPOSIX_x86.cpp.
References eXSAVE, GetFPRType(), k_num_extended_register_sets, and k_num_register_sets.
Referenced by RegisterContextLinuxCore_x86::GetRegisterSet(), GetRegisterSet(), and GetRegisterSetCount().
ReadFPR()
virtual bool RegisterContextPOSIX_x86::ReadFPR () protected pure virtual
Implemented in RegisterContextCorePOSIX_x86, RegisterContextFreeBSDKernelCore_i386, and RegisterContextFreeBSDKernelCore_x86_64.
Referenced by GetFPRType().
ReadGPR()
virtual bool RegisterContextPOSIX_x86::ReadGPR () protected pure virtual
Implemented in RegisterContextCorePOSIX_x86, RegisterContextFreeBSDKernelCore_i386, and RegisterContextFreeBSDKernelCore_x86_64.
WriteFPR()
virtual bool RegisterContextPOSIX_x86::WriteFPR () protected pure virtual
Implemented in RegisterContextCorePOSIX_x86, RegisterContextFreeBSDKernelCore_i386, and RegisterContextFreeBSDKernelCore_x86_64.
WriteGPR()
virtual bool RegisterContextPOSIX_x86::WriteGPR () protected pure virtual
Implemented in RegisterContextCorePOSIX_x86, RegisterContextFreeBSDKernelCore_i386, and RegisterContextFreeBSDKernelCore_x86_64.
Member Data Documentation
g_contained_eax
uint32_t RegisterContextPOSIX_x86::g_contained_eax static
Initial value:
= {lldb_eax_i386,
                                                        LLDB_INVALID_REGNUM}
Definition at line 159 of file RegisterContextPOSIX_x86.h.
g_contained_ebp
uint32_t RegisterContextPOSIX_x86::g_contained_ebp static
Initial value:
= {lldb_ebp_i386,
                                                        LLDB_INVALID_REGNUM}
Definition at line 171 of file RegisterContextPOSIX_x86.h.
g_contained_ebx
uint32_t RegisterContextPOSIX_x86::g_contained_ebx static
Initial value:
= {lldb_ebx_i386,
                                                        LLDB_INVALID_REGNUM}
Definition at line 161 of file RegisterContextPOSIX_x86.h.
g_contained_ecx
uint32_t RegisterContextPOSIX_x86::g_contained_ecx static
Initial value:
= {lldb_ecx_i386,
                                                        LLDB_INVALID_REGNUM}
Definition at line 163 of file RegisterContextPOSIX_x86.h.
g_contained_edi
uint32_t RegisterContextPOSIX_x86::g_contained_edi static
Initial value:
= {lldb_edi_i386,
                                                        LLDB_INVALID_REGNUM}
Definition at line 167 of file RegisterContextPOSIX_x86.h.
g_contained_edx
uint32_t RegisterContextPOSIX_x86::g_contained_edx static
Initial value:
= {lldb_edx_i386,
                                                        LLDB_INVALID_REGNUM}
Definition at line 165 of file RegisterContextPOSIX_x86.h.
g_contained_esi
uint32_t RegisterContextPOSIX_x86::g_contained_esi static
Initial value:
= {lldb_esi_i386,
                                                        LLDB_INVALID_REGNUM}
Definition at line 169 of file RegisterContextPOSIX_x86.h.
g_contained_esp
uint32_t RegisterContextPOSIX_x86::g_contained_esp static
Initial value:
= {lldb_esp_i386,
                                                        LLDB_INVALID_REGNUM}
Definition at line 173 of file RegisterContextPOSIX_x86.h.
g_contained_fdp
uint32_t RegisterContextPOSIX_x86::g_contained_fdp static
Initial value:
= {lldb_fdp_x86_64,
                                                        LLDB_INVALID_REGNUM}
Definition at line 281 of file RegisterContextPOSIX_x86.h.
g_contained_fip
uint32_t RegisterContextPOSIX_x86::g_contained_fip static
Initial value:
= {lldb_fip_x86_64,
                                                        LLDB_INVALID_REGNUM}
Definition at line 279 of file RegisterContextPOSIX_x86.h.
g_contained_r10
uint32_t RegisterContextPOSIX_x86::g_contained_r10 static
Initial value:
= {lldb_r10_x86_64,
                                                        LLDB_INVALID_REGNUM}
Definition at line 217 of file RegisterContextPOSIX_x86.h.
g_contained_r11
uint32_t RegisterContextPOSIX_x86::g_contained_r11 static
Initial value:
= {lldb_r11_x86_64,
                                                        LLDB_INVALID_REGNUM}
Definition at line 219 of file RegisterContextPOSIX_x86.h.
g_contained_r12
uint32_t RegisterContextPOSIX_x86::g_contained_r12 static
Initial value:
= {lldb_r12_x86_64,
                                                        LLDB_INVALID_REGNUM}
Definition at line 221 of file RegisterContextPOSIX_x86.h.
g_contained_r13
uint32_t RegisterContextPOSIX_x86::g_contained_r13 static
Initial value:
= {lldb_r13_x86_64,
                                                        LLDB_INVALID_REGNUM}
Definition at line 223 of file RegisterContextPOSIX_x86.h.
g_contained_r14
uint32_t RegisterContextPOSIX_x86::g_contained_r14 static
Initial value:
= {lldb_r14_x86_64,
                                                        LLDB_INVALID_REGNUM}
Definition at line 225 of file RegisterContextPOSIX_x86.h.
g_contained_r15
uint32_t RegisterContextPOSIX_x86::g_contained_r15 static
Initial value:
= {lldb_r15_x86_64,
                                                        LLDB_INVALID_REGNUM}
Definition at line 227 of file RegisterContextPOSIX_x86.h.
g_contained_r8
uint32_t RegisterContextPOSIX_x86::g_contained_r8 static
Initial value:
= {lldb_r8_x86_64,
                                                       LLDB_INVALID_REGNUM}
Definition at line 213 of file RegisterContextPOSIX_x86.h.
g_contained_r9
uint32_t RegisterContextPOSIX_x86::g_contained_r9 static
Initial value:
= {lldb_r9_x86_64,
                                                       LLDB_INVALID_REGNUM}
Definition at line 215 of file RegisterContextPOSIX_x86.h.
g_contained_rax
uint32_t RegisterContextPOSIX_x86::g_contained_rax static
Initial value:
= {lldb_rax_x86_64,
                                                        LLDB_INVALID_REGNUM}
Definition at line 197 of file RegisterContextPOSIX_x86.h.
g_contained_rbp
uint32_t RegisterContextPOSIX_x86::g_contained_rbp static
Initial value:
= {lldb_rbp_x86_64,
                                                        LLDB_INVALID_REGNUM}
Definition at line 209 of file RegisterContextPOSIX_x86.h.
g_contained_rbx
uint32_t RegisterContextPOSIX_x86::g_contained_rbx static
Initial value:
= {lldb_rbx_x86_64,
                                                        LLDB_INVALID_REGNUM}
Definition at line 199 of file RegisterContextPOSIX_x86.h.
g_contained_rcx
uint32_t RegisterContextPOSIX_x86::g_contained_rcx static
Initial value:
= {lldb_rcx_x86_64,
                                                        LLDB_INVALID_REGNUM}
Definition at line 201 of file RegisterContextPOSIX_x86.h.
g_contained_rdi
uint32_t RegisterContextPOSIX_x86::g_contained_rdi static
Initial value:
= {lldb_rdi_x86_64,
                                                        LLDB_INVALID_REGNUM}
Definition at line 205 of file RegisterContextPOSIX_x86.h.
g_contained_rdx
uint32_t RegisterContextPOSIX_x86::g_contained_rdx static
Initial value:
= {lldb_rdx_x86_64,
                                                        LLDB_INVALID_REGNUM}
Definition at line 203 of file RegisterContextPOSIX_x86.h.
g_contained_rsi
uint32_t RegisterContextPOSIX_x86::g_contained_rsi static
Initial value:
= {lldb_rsi_x86_64,
                                                        LLDB_INVALID_REGNUM}
Definition at line 207 of file RegisterContextPOSIX_x86.h.
g_contained_rsp
uint32_t RegisterContextPOSIX_x86::g_contained_rsp static
Initial value:
= {lldb_rsp_x86_64,
                                                        LLDB_INVALID_REGNUM}
Definition at line 211 of file RegisterContextPOSIX_x86.h.
g_contained_st0_32
uint32_t RegisterContextPOSIX_x86::g_contained_st0_32 static
Initial value:
= {lldb_st0_i386,
                                                           LLDB_INVALID_REGNUM}
Definition at line 289 of file RegisterContextPOSIX_x86.h.
g_contained_st0_64
uint32_t RegisterContextPOSIX_x86::g_contained_st0_64 static
Initial value:
= {lldb_st0_x86_64,
                                                           LLDB_INVALID_REGNUM}
Definition at line 323 of file RegisterContextPOSIX_x86.h.
g_contained_st1_32
uint32_t RegisterContextPOSIX_x86::g_contained_st1_32 static
Initial value:
= {lldb_st1_i386,
                                                           LLDB_INVALID_REGNUM}
Definition at line 291 of file RegisterContextPOSIX_x86.h.
g_contained_st1_64
uint32_t RegisterContextPOSIX_x86::g_contained_st1_64 static
Initial value:
= {lldb_st1_x86_64,
                                                           LLDB_INVALID_REGNUM}
Definition at line 325 of file RegisterContextPOSIX_x86.h.
g_contained_st2_32
uint32_t RegisterContextPOSIX_x86::g_contained_st2_32 static
Initial value:
= {lldb_st2_i386,
                                                           LLDB_INVALID_REGNUM}
Definition at line 293 of file RegisterContextPOSIX_x86.h.
g_contained_st2_64
uint32_t RegisterContextPOSIX_x86::g_contained_st2_64 static
Initial value:
= {lldb_st2_x86_64,
                                                           LLDB_INVALID_REGNUM}
Definition at line 327 of file RegisterContextPOSIX_x86.h.
g_contained_st3_32
uint32_t RegisterContextPOSIX_x86::g_contained_st3_32 static
Initial value:
= {lldb_st3_i386,
                                                           LLDB_INVALID_REGNUM}
Definition at line 295 of file RegisterContextPOSIX_x86.h.
g_contained_st3_64
uint32_t RegisterContextPOSIX_x86::g_contained_st3_64 static
Initial value:
= {lldb_st3_x86_64,
                                                           LLDB_INVALID_REGNUM}
Definition at line 329 of file RegisterContextPOSIX_x86.h.
g_contained_st4_32
uint32_t RegisterContextPOSIX_x86::g_contained_st4_32 static
Initial value:
= {lldb_st4_i386,
                                                           LLDB_INVALID_REGNUM}
Definition at line 297 of file RegisterContextPOSIX_x86.h.
g_contained_st4_64
uint32_t RegisterContextPOSIX_x86::g_contained_st4_64 static
Initial value:
= {lldb_st4_x86_64,
                                                           LLDB_INVALID_REGNUM}
Definition at line 331 of file RegisterContextPOSIX_x86.h.
g_contained_st5_32
uint32_t RegisterContextPOSIX_x86::g_contained_st5_32 static
Initial value:
= {lldb_st5_i386,
                                                           LLDB_INVALID_REGNUM}
Definition at line 299 of file RegisterContextPOSIX_x86.h.
g_contained_st5_64
uint32_t RegisterContextPOSIX_x86::g_contained_st5_64 static
Initial value:
= {lldb_st5_x86_64,
                                                           LLDB_INVALID_REGNUM}
Definition at line 333 of file RegisterContextPOSIX_x86.h.
g_contained_st6_32
uint32_t RegisterContextPOSIX_x86::g_contained_st6_32 static
Initial value:
= {lldb_st6_i386,
                                                           LLDB_INVALID_REGNUM}
Definition at line 301 of file RegisterContextPOSIX_x86.h.
g_contained_st6_64
uint32_t RegisterContextPOSIX_x86::g_contained_st6_64 static
Initial value:
= {lldb_st6_x86_64,
                                                           LLDB_INVALID_REGNUM}
Definition at line 335 of file RegisterContextPOSIX_x86.h.
g_contained_st7_32
uint32_t RegisterContextPOSIX_x86::g_contained_st7_32 static
Initial value:
= {lldb_st7_i386,
                                                           LLDB_INVALID_REGNUM}
Definition at line 303 of file RegisterContextPOSIX_x86.h.
g_contained_st7_64
uint32_t RegisterContextPOSIX_x86::g_contained_st7_64 static
Initial value:
= {lldb_st7_x86_64,
                                                           LLDB_INVALID_REGNUM}
Definition at line 337 of file RegisterContextPOSIX_x86.h.
g_invalidate_eax
uint32_t RegisterContextPOSIX_x86::g_invalidate_eax static
Initial value:
= {
    lldb_eax_i386, lldb_ax_i386, lldb_ah_i386, lldb_al_i386,
    LLDB_INVALID_REGNUM}
Definition at line 176 of file RegisterContextPOSIX_x86.h.
g_invalidate_ebp
uint32_t RegisterContextPOSIX_x86::g_invalidate_ebp static
Initial value:
= {
    lldb_ebp_i386, lldb_bp_i386, LLDB_INVALID_REGNUM}
Definition at line 192 of file RegisterContextPOSIX_x86.h.
g_invalidate_ebx
uint32_t RegisterContextPOSIX_x86::g_invalidate_ebx static
Initial value:
= {
    lldb_ebx_i386, lldb_bx_i386, lldb_bh_i386, lldb_bl_i386,
    LLDB_INVALID_REGNUM}
Definition at line 179 of file RegisterContextPOSIX_x86.h.
g_invalidate_ecx
uint32_t RegisterContextPOSIX_x86::g_invalidate_ecx static
Initial value:
= {
    lldb_ecx_i386, lldb_cx_i386, lldb_ch_i386, lldb_cl_i386,
    LLDB_INVALID_REGNUM}
Definition at line 182 of file RegisterContextPOSIX_x86.h.
g_invalidate_edi
uint32_t RegisterContextPOSIX_x86::g_invalidate_edi static
Initial value:
= {
    lldb_edi_i386, lldb_di_i386, LLDB_INVALID_REGNUM}
Definition at line 188 of file RegisterContextPOSIX_x86.h.
g_invalidate_edx
uint32_t RegisterContextPOSIX_x86::g_invalidate_edx static
Initial value:
= {
    lldb_edx_i386, lldb_dx_i386, lldb_dh_i386, lldb_dl_i386,
    LLDB_INVALID_REGNUM}
Definition at line 185 of file RegisterContextPOSIX_x86.h.
g_invalidate_esi
uint32_t RegisterContextPOSIX_x86::g_invalidate_esi static
Initial value:
= {
    lldb_esi_i386, lldb_si_i386, LLDB_INVALID_REGNUM}
Definition at line 190 of file RegisterContextPOSIX_x86.h.
g_invalidate_esp
uint32_t RegisterContextPOSIX_x86::g_invalidate_esp static
Initial value:
= {
    lldb_esp_i386, lldb_sp_i386, LLDB_INVALID_REGNUM}
Definition at line 194 of file RegisterContextPOSIX_x86.h.
g_invalidate_fdp
uint32_t RegisterContextPOSIX_x86::g_invalidate_fdp static
Initial value:
= {
    lldb_fdp_x86_64, lldb_fooff_x86_64, lldb_foseg_x86_64, LLDB_INVALID_REGNUM}
Definition at line 286 of file RegisterContextPOSIX_x86.h.
g_invalidate_fip
uint32_t RegisterContextPOSIX_x86::g_invalidate_fip static
Initial value:
= {
    lldb_fip_x86_64, lldb_fioff_x86_64, lldb_fiseg_x86_64, LLDB_INVALID_REGNUM}
Definition at line 284 of file RegisterContextPOSIX_x86.h.
g_invalidate_r10
uint32_t RegisterContextPOSIX_x86::g_invalidate_r10 static
Initial value:
= {
    lldb_r10_x86_64, lldb_r10d_x86_64, lldb_r10w_x86_64, lldb_r10l_x86_64,
    LLDB_INVALID_REGNUM}
Definition at line 260 of file RegisterContextPOSIX_x86.h.
g_invalidate_r11
uint32_t RegisterContextPOSIX_x86::g_invalidate_r11 static
Initial value:
= {
    lldb_r11_x86_64, lldb_r11d_x86_64, lldb_r11w_x86_64, lldb_r11l_x86_64,
    LLDB_INVALID_REGNUM}
Definition at line 263 of file RegisterContextPOSIX_x86.h.
g_invalidate_r12
uint32_t RegisterContextPOSIX_x86::g_invalidate_r12 static
Initial value:
= {
    lldb_r12_x86_64, lldb_r12d_x86_64, lldb_r12w_x86_64, lldb_r12l_x86_64,
    LLDB_INVALID_REGNUM}
Definition at line 266 of file RegisterContextPOSIX_x86.h.
g_invalidate_r13
uint32_t RegisterContextPOSIX_x86::g_invalidate_r13 static
Initial value:
= {
    lldb_r13_x86_64, lldb_r13d_x86_64, lldb_r13w_x86_64, lldb_r13l_x86_64,
    LLDB_INVALID_REGNUM}
Definition at line 269 of file RegisterContextPOSIX_x86.h.
g_invalidate_r14
uint32_t RegisterContextPOSIX_x86::g_invalidate_r14 static
Initial value:
= {
    lldb_r14_x86_64, lldb_r14d_x86_64, lldb_r14w_x86_64, lldb_r14l_x86_64,
    LLDB_INVALID_REGNUM}
Definition at line 272 of file RegisterContextPOSIX_x86.h.
g_invalidate_r15
uint32_t RegisterContextPOSIX_x86::g_invalidate_r15 static
Initial value:
= {
    lldb_r15_x86_64, lldb_r15d_x86_64, lldb_r15w_x86_64, lldb_r15l_x86_64,
    LLDB_INVALID_REGNUM}
Definition at line 275 of file RegisterContextPOSIX_x86.h.
g_invalidate_r8
uint32_t RegisterContextPOSIX_x86::g_invalidate_r8 static
Initial value:
= {
    lldb_r8_x86_64, lldb_r8d_x86_64, lldb_r8w_x86_64, lldb_r8l_x86_64,
    LLDB_INVALID_REGNUM}
Definition at line 254 of file RegisterContextPOSIX_x86.h.
g_invalidate_r9
uint32_t RegisterContextPOSIX_x86::g_invalidate_r9 static
Initial value:
= {
    lldb_r9_x86_64, lldb_r9d_x86_64, lldb_r9w_x86_64, lldb_r9l_x86_64,
    LLDB_INVALID_REGNUM}
Definition at line 257 of file RegisterContextPOSIX_x86.h.
g_invalidate_rax
uint32_t RegisterContextPOSIX_x86::g_invalidate_rax static
Initial value:
= {
    lldb_rax_x86_64, lldb_eax_x86_64, lldb_ax_x86_64,
    lldb_ah_x86_64,  lldb_al_x86_64,  LLDB_INVALID_REGNUM}
Definition at line 230 of file RegisterContextPOSIX_x86.h.
g_invalidate_rbp
uint32_t RegisterContextPOSIX_x86::g_invalidate_rbp static
Initial value:
= {
    lldb_rbp_x86_64, lldb_ebp_x86_64, lldb_bp_x86_64, lldb_bpl_x86_64,
    LLDB_INVALID_REGNUM}
Definition at line 248 of file RegisterContextPOSIX_x86.h.
g_invalidate_rbx
uint32_t RegisterContextPOSIX_x86::g_invalidate_rbx static
Initial value:
= {
    lldb_rbx_x86_64, lldb_ebx_x86_64, lldb_bx_x86_64,
    lldb_bh_x86_64,  lldb_bl_x86_64,  LLDB_INVALID_REGNUM}
Definition at line 233 of file RegisterContextPOSIX_x86.h.
g_invalidate_rcx
uint32_t RegisterContextPOSIX_x86::g_invalidate_rcx static
Initial value:
= {
    lldb_rcx_x86_64, lldb_ecx_x86_64, lldb_cx_x86_64,
    lldb_ch_x86_64,  lldb_cl_x86_64,  LLDB_INVALID_REGNUM}
Definition at line 236 of file RegisterContextPOSIX_x86.h.
g_invalidate_rdi
uint32_t RegisterContextPOSIX_x86::g_invalidate_rdi static
Initial value:
= {
    lldb_rdi_x86_64, lldb_edi_x86_64, lldb_di_x86_64, lldb_dil_x86_64,
    LLDB_INVALID_REGNUM}
Definition at line 242 of file RegisterContextPOSIX_x86.h.
g_invalidate_rdx
uint32_t RegisterContextPOSIX_x86::g_invalidate_rdx static
Initial value:
= {
    lldb_rdx_x86_64, lldb_edx_x86_64, lldb_dx_x86_64,
    lldb_dh_x86_64,  lldb_dl_x86_64,  LLDB_INVALID_REGNUM}
Definition at line 239 of file RegisterContextPOSIX_x86.h.
g_invalidate_rsi
uint32_t RegisterContextPOSIX_x86::g_invalidate_rsi static
Initial value:
= {
    lldb_rsi_x86_64, lldb_esi_x86_64, lldb_si_x86_64, lldb_sil_x86_64,
    LLDB_INVALID_REGNUM}
Definition at line 245 of file RegisterContextPOSIX_x86.h.
g_invalidate_rsp
uint32_t RegisterContextPOSIX_x86::g_invalidate_rsp static
Initial value:
= {
    lldb_rsp_x86_64, lldb_esp_x86_64, lldb_sp_x86_64, lldb_spl_x86_64,
    LLDB_INVALID_REGNUM}
Definition at line 251 of file RegisterContextPOSIX_x86.h.
g_invalidate_st0_32
uint32_t RegisterContextPOSIX_x86::g_invalidate_st0_32 static
Initial value:
= {
    lldb_st0_i386, lldb_mm0_i386, LLDB_INVALID_REGNUM}
Definition at line 306 of file RegisterContextPOSIX_x86.h.
g_invalidate_st0_64
uint32_t RegisterContextPOSIX_x86::g_invalidate_st0_64 static
Initial value:
= {
    lldb_st0_x86_64, lldb_mm0_x86_64, LLDB_INVALID_REGNUM}
Definition at line 340 of file RegisterContextPOSIX_x86.h.
g_invalidate_st1_32
uint32_t RegisterContextPOSIX_x86::g_invalidate_st1_32 static
Initial value:
= {
    lldb_st1_i386, lldb_mm1_i386, LLDB_INVALID_REGNUM}
Definition at line 308 of file RegisterContextPOSIX_x86.h.
g_invalidate_st1_64
uint32_t RegisterContextPOSIX_x86::g_invalidate_st1_64 static
Initial value:
= {
    lldb_st1_x86_64, lldb_mm1_x86_64, LLDB_INVALID_REGNUM}
Definition at line 342 of file RegisterContextPOSIX_x86.h.
g_invalidate_st2_32
uint32_t RegisterContextPOSIX_x86::g_invalidate_st2_32 static
Initial value:
= {
    lldb_st2_i386, lldb_mm2_i386, LLDB_INVALID_REGNUM}
Definition at line 310 of file RegisterContextPOSIX_x86.h.
g_invalidate_st2_64
uint32_t RegisterContextPOSIX_x86::g_invalidate_st2_64 static
Initial value:
= {
    lldb_st2_x86_64, lldb_mm2_x86_64, LLDB_INVALID_REGNUM}
Definition at line 344 of file RegisterContextPOSIX_x86.h.
g_invalidate_st3_32
uint32_t RegisterContextPOSIX_x86::g_invalidate_st3_32 static
Initial value:
= {
    lldb_st3_i386, lldb_mm3_i386, LLDB_INVALID_REGNUM}
Definition at line 312 of file RegisterContextPOSIX_x86.h.
g_invalidate_st3_64
uint32_t RegisterContextPOSIX_x86::g_invalidate_st3_64 static
Initial value:
= {
    lldb_st3_x86_64, lldb_mm3_x86_64, LLDB_INVALID_REGNUM}
Definition at line 346 of file RegisterContextPOSIX_x86.h.
g_invalidate_st4_32
uint32_t RegisterContextPOSIX_x86::g_invalidate_st4_32 static
Initial value:
= {
    lldb_st4_i386, lldb_mm4_i386, LLDB_INVALID_REGNUM}
Definition at line 314 of file RegisterContextPOSIX_x86.h.
g_invalidate_st4_64
uint32_t RegisterContextPOSIX_x86::g_invalidate_st4_64 static
Initial value:
= {
    lldb_st4_x86_64, lldb_mm4_x86_64, LLDB_INVALID_REGNUM}
Definition at line 348 of file RegisterContextPOSIX_x86.h.
g_invalidate_st5_32
uint32_t RegisterContextPOSIX_x86::g_invalidate_st5_32 static
Initial value:
= {
    lldb_st5_i386, lldb_mm5_i386, LLDB_INVALID_REGNUM}
Definition at line 316 of file RegisterContextPOSIX_x86.h.
g_invalidate_st5_64
uint32_t RegisterContextPOSIX_x86::g_invalidate_st5_64 static
Initial value:
= {
    lldb_st5_x86_64, lldb_mm5_x86_64, LLDB_INVALID_REGNUM}
Definition at line 350 of file RegisterContextPOSIX_x86.h.
g_invalidate_st6_32
uint32_t RegisterContextPOSIX_x86::g_invalidate_st6_32 static
Initial value:
= {
    lldb_st6_i386, lldb_mm6_i386, LLDB_INVALID_REGNUM}
Definition at line 318 of file RegisterContextPOSIX_x86.h.
g_invalidate_st6_64
uint32_t RegisterContextPOSIX_x86::g_invalidate_st6_64 static
Initial value:
= {
    lldb_st6_x86_64, lldb_mm6_x86_64, LLDB_INVALID_REGNUM}
Definition at line 352 of file RegisterContextPOSIX_x86.h.
g_invalidate_st7_32
uint32_t RegisterContextPOSIX_x86::g_invalidate_st7_32 static
Initial value:
= {
    lldb_st7_i386, lldb_mm7_i386, LLDB_INVALID_REGNUM}
Definition at line 320 of file RegisterContextPOSIX_x86.h.
g_invalidate_st7_64
uint32_t RegisterContextPOSIX_x86::g_invalidate_st7_64 static
Initial value:
= {
    lldb_st7_x86_64, lldb_mm7_x86_64, LLDB_INVALID_REGNUM}
Definition at line 354 of file RegisterContextPOSIX_x86.h.
m_fpr
lldb_private::FPR RegisterContextPOSIX_x86::m_fpr protected
Definition at line 155 of file RegisterContextPOSIX_x86.h.
Referenced by CopyXSTATEtoYMM(), CopyYMMtoXSTATE(), and RegisterContextPOSIX_x86().
m_fpr_type
FPRType RegisterContextPOSIX_x86::m_fpr_type protected
Definition at line 154 of file RegisterContextPOSIX_x86.h.
Referenced by GetFPRType(), and RegisterContextPOSIX_x86().
m_register_info_up
std::unique_ptr<lldb_private::RegisterInfoInterface> RegisterContextPOSIX_x86::m_register_info_up protected
Definition at line 159 of file RegisterContextPOSIX_x86.h.
Referenced by GetGPRSize(), RegisterContextLinuxCore_x86::GetRegInfo(), GetRegInfo(), GetRegisterInfo(), RegisterContextLinuxCore_x86::GetRegisterSet(), GetRegisterSet(), and RegisterContextPOSIX_x86().
m_ymm_set
lldb_private::YMM RegisterContextPOSIX_x86::m_ymm_set protected
Definition at line 157 of file RegisterContextPOSIX_x86.h.
Referenced by CopyXSTATEtoYMM(), CopyYMMtoXSTATE(), and RegisterContextPOSIX_x86().
The documentation for this class was generated from the following files:
RegisterContextPOSIX_x86.h
RegisterContextPOSIX_x86.cpp