LLDB: lldb_private::HostThread Class Reference
lldb_private::HostThread Class Reference
#include <HostThread.h>
Public Member Functions
HostThread ()
HostThread (lldb::thread_t thread)
Status Join (lldb::thread_result_t *result)
Status Cancel ()
void Reset ()
lldb::thread_t Release ()
bool IsJoinable () const
HostNativeThread & GetNativeThread ()
const HostNativeThread & GetNativeThread () const
lldb::thread_result_t GetResult () const
bool EqualsThread (lldb::thread_t thread) const
bool EqualsThread (const HostThread &thread) const
bool HasThread () const
Private Attributes
std::shared_ptr< HostNativeThreadBase > m_native_thread
Detailed Description
Definition at line 29 of file HostThread.h.
Constructor & Destructor Documentation
HostThread() [1/2]
HostThread::HostThread ()
Definition at line 15 of file HostThread.cpp.
References m_native_thread.
Referenced by EqualsThread().
HostThread() [2/2]
HostThread::HostThread (lldb::thread_t thread)
Definition at line 17 of file HostThread.cpp.
References m_native_thread.
Member Function Documentation
Cancel()
Status HostThread::Cancel ()
Definition at line 24 of file HostThread.cpp.
References m_native_thread.
EqualsThread() [1/2]
bool HostThread::EqualsThread (const HostThread & thread) const
Definition at line 48 of file HostThread.cpp.
References HostThread(), and m_native_thread.
EqualsThread() [2/2]
bool HostThread::EqualsThread (lldb::thread_t thread) const
Definition at line 44 of file HostThread.cpp.
References m_native_thread.
GetNativeThread() [1/2]
HostNativeThread & HostThread::GetNativeThread ()
Definition at line 32 of file HostThread.cpp.
Referenced by lldb_private::RegisterContextWindows::ApplyAllRegisterValues(), lldb_private::RegisterContextWindows::CacheAllRegisterValues(), lldb_private::NativeRegisterContextWindows::GetThreadHandle(), lldb_private::ProcessWindows::OnCreateThread(), and lldb_private::ProcessWindows::OnDebuggerConnected().
GetNativeThread() [2/2]
const HostNativeThread & HostThread::GetNativeThread () const
Definition at line 36 of file HostThread.cpp.
GetResult()
lldb::thread_result_t HostThread::GetResult () const
Definition at line 40 of file HostThread.cpp.
References m_native_thread.
HasThread()
bool HostThread::HasThread () const
Definition at line 53 of file HostThread.cpp.
References LLDB_INVALID_HOST_THREAD, and m_native_thread.
IsJoinable()
bool HostThread::IsJoinable () const
Definition at line 30 of file HostThread.cpp.
References m_native_thread.
Join()
Status HostThread::Join (lldb::thread_result_t * result)
Definition at line 20 of file HostThread.cpp.
References m_native_thread.
Release()
lldb::thread_t HostThread::Release ()
Definition at line 28 of file HostThread.cpp.
References m_native_thread.
Reset()
void HostThread::Reset ()
Definition at line 26 of file HostThread.cpp.
References m_native_thread.
Member Data Documentation
m_native_thread
std::shared_ptr<HostNativeThreadBase> lldb_private::HostThread::m_native_thread private
Definition at line 50 of file HostThread.h.
Referenced by Cancel(), EqualsThread(), EqualsThread(), GetResult(), HasThread(), HostThread(), HostThread(), IsJoinable(), Join(), Release(), and Reset().
The documentation for this class was generated from the following files:
HostThread.h
HostThread.cpp