LLDB: RegisterContextFreeBSD_powerpc Class Reference
RegisterContextFreeBSD_powerpc Class Reference
#include <RegisterContextFreeBSD_powerpc.h>
Public Member Functions
RegisterContextFreeBSD_powerpc (const lldb_private::ArchSpec &target_arch)
~RegisterContextFreeBSD_powerpc () override
size_t GetGPRSize () const override
const lldb_private::RegisterInfo * GetRegisterInfo () const override
uint32_t GetRegisterCount () const override
Public Member Functions inherited from lldb_private::RegisterInfoInterface
RegisterInfoInterface (const lldb_private::ArchSpec &target_arch)
virtual ~RegisterInfoInterface ()=default
virtual uint32_t GetUserRegisterCount () const
const lldb_private::ArchSpec & GetTargetArchitecture () const
Detailed Description
Definition at line 15 of file RegisterContextFreeBSD_powerpc.h.
Constructor & Destructor Documentation
RegisterContextFreeBSD_powerpc()
RegisterContextFreeBSD_powerpc::RegisterContextFreeBSD_powerpc (const lldb_private::ArchSpec & target_arch)
Definition at line 177 of file RegisterContextFreeBSD_powerpc.cpp.
References lldb_private::RegisterInfoInterface::RegisterInfoInterface().
Referenced by RegisterContextFreeBSD_powerpc32::RegisterContextFreeBSD_powerpc32(), and RegisterContextFreeBSD_powerpc64::RegisterContextFreeBSD_powerpc64().
~RegisterContextFreeBSD_powerpc()
RegisterContextFreeBSD_powerpc::~RegisterContextFreeBSD_powerpc () override default
Member Function Documentation
GetGPRSize()
size_t RegisterContextFreeBSD_powerpc::GetGPRSize () const override virtual
Implements lldb_private::RegisterInfoInterface.
Reimplemented in RegisterContextFreeBSD_powerpc32, and RegisterContextFreeBSD_powerpc64.
Definition at line 183 of file RegisterContextFreeBSD_powerpc.cpp.
GetRegisterCount()
uint32_t RegisterContextFreeBSD_powerpc::GetRegisterCount () const override virtual
Implements lldb_private::RegisterInfoInterface.
Reimplemented in RegisterContextFreeBSD_powerpc32, and RegisterContextFreeBSD_powerpc64.
Definition at line 193 of file RegisterContextFreeBSD_powerpc.cpp.
GetRegisterInfo()
const RegisterInfo * RegisterContextFreeBSD_powerpc::GetRegisterInfo () const override virtual
Implements lldb_private::RegisterInfoInterface.
Reimplemented in RegisterContextFreeBSD_powerpc32, and RegisterContextFreeBSD_powerpc64.
Definition at line 188 of file RegisterContextFreeBSD_powerpc.cpp.
The documentation for this class was generated from the following files:
RegisterContextFreeBSD_powerpc.h
RegisterContextFreeBSD_powerpc.cpp