LLDB: lldb::SBWatchpoint Class Reference
lldb::SBWatchpoint Class Reference
#include <SBWatchpoint.h>
Public Member Functions
SBWatchpoint ()
SBWatchpoint (const lldb::SBWatchpoint &rhs)
~SBWatchpoint ()
const lldb::SBWatchpoint & operator= (const lldb::SBWatchpoint &rhs)
operator bool () const
bool operator== (const SBWatchpoint &rhs) const
bool operator!= (const SBWatchpoint &rhs) const
bool IsValid () const
SBError GetError ()
watch_id_t GetID ()
int32_t GetHardwareIndex ()
lldb::addr_t GetWatchAddress ()
size_t GetWatchSize ()
void SetEnabled (bool enabled)
bool IsEnabled ()
uint32_t GetHitCount ()
uint32_t GetIgnoreCount ()
void SetIgnoreCount (uint32_t n)
const char * GetCondition ()
void SetCondition (const char *condition)
bool GetDescription (lldb::SBStream &description, DescriptionLevel level)
void Clear ()
lldb::SBType GetType ()
WatchpointValueKind GetWatchValueKind ()
const char * GetWatchSpec ()
bool IsWatchingReads ()
bool IsWatchingWrites ()
Static Public Member Functions
static bool EventIsWatchpointEvent (const lldb::SBEvent &event)
static lldb::WatchpointEventType GetWatchpointEventTypeFromEvent (const lldb::SBEvent &event)
static lldb::SBWatchpoint GetWatchpointFromEvent (const lldb::SBEvent &event)
Protected Member Functions
SBWatchpoint (const lldb::WatchpointSP &wp_sp)
lldb::WatchpointSP GetSP () const
void SetSP (const lldb::WatchpointSP &sp)
Private Attributes
std::weak_ptr< lldb_private::Watchpoint > m_opaque_wp
Friends
class lldb_private::python::SWIGBridge
class lldb_private::lua::SWIGBridge
class SBTarget
class SBValue
Detailed Description
Definition at line 26 of file SBWatchpoint.h.
Constructor & Destructor Documentation
SBWatchpoint() [1/3]
SBWatchpoint::SBWatchpoint ()
Definition at line 29 of file SBWatchpoint.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by GetWatchpointFromEvent(), lldb_private::lua::SWIGBridge, operator!=(), operator=(), operator==(), SBWatchpoint(), and ~SBWatchpoint().
SBWatchpoint() [2/3]
SBWatchpoint::SBWatchpoint (const lldb::SBWatchpoint & rhs)
Definition at line 36 of file SBWatchpoint.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_wp, and SBWatchpoint().
~SBWatchpoint()
SBWatchpoint::~SBWatchpoint () default
References Clear(), EventIsWatchpointEvent(), GetCondition(), GetDescription(), GetError(), GetHardwareIndex(), GetHitCount(), GetID(), GetIgnoreCount(), GetType(), GetWatchAddress(), GetWatchpointEventTypeFromEvent(), GetWatchpointFromEvent(), GetWatchSize(), GetWatchSpec(), GetWatchValueKind(), IsEnabled(), IsValid(), IsWatchingReads(), IsWatchingWrites(), operator!=(), operator=(), operator==(), SBWatchpoint(), SetCondition(), SetEnabled(), and SetIgnoreCount().
SBWatchpoint() [3/3]
SBWatchpoint::SBWatchpoint (const lldb::WatchpointSP & wp_sp) protected
Definition at line 31 of file SBWatchpoint.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_wp.
Member Function Documentation
Clear()
void SBWatchpoint::Clear ()
Definition at line 244 of file SBWatchpoint.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_wp.
Referenced by ~SBWatchpoint().
EventIsWatchpointEvent()
bool SBWatchpoint::EventIsWatchpointEvent (const lldb::SBEvent & event) static
Definition at line 262 of file SBWatchpoint.cpp.
References lldb::SBEvent::get(), lldb_private::Watchpoint::WatchpointEventData::GetEventDataFromEvent(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBWatchpoint().
GetCondition()
const char * SBWatchpoint::GetCondition ()
Definition at line 203 of file SBWatchpoint.cpp.
References lldb_private::ConstString::GetCString(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBWatchpoint().
GetDescription()
bool SBWatchpoint::GetDescription (lldb::SBStream & description, DescriptionLevel level)
Definition at line 226 of file SBWatchpoint.cpp.
References lldb_private::Stream::EOL(), GetSP(), LLDB_INSTRUMENT_VA, lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
Referenced by ~SBWatchpoint().
GetError()
SBError SBWatchpoint::GetError ()
Definition at line 83 of file SBWatchpoint.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBError::SetError().
Referenced by ~SBWatchpoint().
GetHardwareIndex()
int32_t SBWatchpoint::GetHardwareIndex ()
Definition at line 94 of file SBWatchpoint.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBWatchpoint().
GetHitCount()
uint32_t SBWatchpoint::GetHitCount ()
Definition at line 166 of file SBWatchpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBWatchpoint().
GetID()
watch_id_t SBWatchpoint::GetID ()
Definition at line 50 of file SBWatchpoint.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and LLDB_INVALID_WATCH_ID.
Referenced by ~SBWatchpoint().
GetIgnoreCount()
uint32_t SBWatchpoint::GetIgnoreCount ()
Definition at line 180 of file SBWatchpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBWatchpoint().
GetSP()
lldb::WatchpointSP SBWatchpoint::GetSP () const protected
Definition at line 250 of file SBWatchpoint.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_wp.
Referenced by GetCondition(), GetDescription(), GetError(), GetHitCount(), GetID(), GetIgnoreCount(), GetType(), GetWatchAddress(), GetWatchSize(), GetWatchSpec(), GetWatchValueKind(), IsEnabled(), IsWatchingReads(), IsWatchingWrites(), lldb_private::lua::SWIGBridge, operator==(), SetCondition(), SetEnabled(), and SetIgnoreCount().
GetType()
lldb::SBType SBWatchpoint::GetType ()
Definition at line 289 of file SBWatchpoint.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBType.
Referenced by ~SBWatchpoint().
GetWatchAddress()
addr_t SBWatchpoint::GetWatchAddress ()
Definition at line 104 of file SBWatchpoint.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and LLDB_INVALID_ADDRESS.
Referenced by ~SBWatchpoint().
GetWatchpointEventTypeFromEvent()
WatchpointEventType SBWatchpoint::GetWatchpointEventTypeFromEvent (const lldb::SBEvent & event) static
Definition at line 270 of file SBWatchpoint.cpp.
References lldb::SBEvent::GetSP(), lldb_private::Watchpoint::WatchpointEventData::GetWatchpointEventTypeFromEvent(), lldb::SBEvent::IsValid(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBWatchpoint().
GetWatchpointFromEvent()
SBWatchpoint SBWatchpoint::GetWatchpointFromEvent (const lldb::SBEvent & event) static
Definition at line 279 of file SBWatchpoint.cpp.
References lldb::SBEvent::GetSP(), lldb_private::Watchpoint::WatchpointEventData::GetWatchpointFromEvent(), lldb::SBEvent::IsValid(), LLDB_INSTRUMENT_VA, and SBWatchpoint().
Referenced by ~SBWatchpoint().
GetWatchSize()
size_t SBWatchpoint::GetWatchSize ()
Definition at line 119 of file SBWatchpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBWatchpoint().
GetWatchSpec()
const char * SBWatchpoint::GetWatchSpec ()
Definition at line 316 of file SBWatchpoint.cpp.
References lldb_private::ConstString::AsCString(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBWatchpoint().
GetWatchValueKind()
WatchpointValueKind SBWatchpoint::GetWatchValueKind ()
Definition at line 302 of file SBWatchpoint.cpp.
References lldb::eWatchPointValueKindExpression, lldb::eWatchPointValueKindInvalid, lldb::eWatchPointValueKindVariable, GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBWatchpoint().
IsEnabled()
bool SBWatchpoint::IsEnabled ()
Definition at line 154 of file SBWatchpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBWatchpoint().
IsValid()
bool SBWatchpoint::IsValid () const
Definition at line 61 of file SBWatchpoint.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBWatchpoint().
IsWatchingReads()
bool SBWatchpoint::IsWatchingReads ()
Definition at line 332 of file SBWatchpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBWatchpoint().
IsWatchingWrites()
bool SBWatchpoint::IsWatchingWrites ()
Definition at line 345 of file SBWatchpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBWatchpoint().
operator bool()
SBWatchpoint::operator bool () const explicit
Definition at line 65 of file SBWatchpoint.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_wp.
operator!=()
bool SBWatchpoint::operator!= (const SBWatchpoint & rhs) const
Definition at line 77 of file SBWatchpoint.cpp.
References LLDB_INSTRUMENT_VA, and SBWatchpoint().
Referenced by ~SBWatchpoint().
operator=()
const SBWatchpoint & SBWatchpoint::operator= (const lldb::SBWatchpoint & rhs)
Definition at line 41 of file SBWatchpoint.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_wp, and SBWatchpoint().
Referenced by ~SBWatchpoint().
operator==()
bool SBWatchpoint::operator== (const SBWatchpoint & rhs) const
Definition at line 71 of file SBWatchpoint.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and SBWatchpoint().
Referenced by ~SBWatchpoint().
SetCondition()
void SBWatchpoint::SetCondition (const char * condition)
Definition at line 215 of file SBWatchpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBWatchpoint().
SetEnabled()
void SBWatchpoint::SetEnabled (bool enabled)
Definition at line 134 of file SBWatchpoint.cpp.
References lldb_private::Target::GetAPIMutex(), lldb_private::Target::GetProcessSP(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBWatchpoint().
SetIgnoreCount()
void SBWatchpoint::SetIgnoreCount (uint32_t n)
Definition at line 192 of file SBWatchpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBWatchpoint().
SetSP()
void SBWatchpoint::SetSP (const lldb::WatchpointSP & sp) protected
Definition at line 256 of file SBWatchpoint.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_wp, and sp.
Referenced by lldb::SBTarget::FindWatchpointByID(), lldb::SBTarget::GetWatchpointAtIndex(), lldb_private::lua::SWIGBridge, lldb::SBValue::Watch(), and lldb::SBTarget::WatchpointCreateByAddress().
Friends And Related Symbol Documentation
lldb_private::lua::SWIGBridge
friend class lldb_private::lua::SWIGBridge friend
Definition at line 92 of file SBWatchpoint.h.
References GetSP(), lldb_private::python::SWIGBridge, SBWatchpoint(), SetSP(), and sp.
lldb_private::python::SWIGBridge
friend class lldb_private::python::SWIGBridge friend
Definition at line 91 of file SBWatchpoint.h.
References lldb_private::python::SWIGBridge.
Referenced by lldb_private::lua::SWIGBridge, and lldb_private::python::SWIGBridge.
SBTarget
friend class SBTarget friend
Definition at line 101 of file SBWatchpoint.h.
References SBTarget.
Referenced by SBTarget.
SBValue
friend class SBValue friend
Definition at line 102 of file SBWatchpoint.h.
References SBValue.
Referenced by SBValue.
Member Data Documentation
m_opaque_wp
std::weak_ptr<lldb_private::Watchpoint> lldb::SBWatchpoint::m_opaque_wp private
Definition at line 104 of file SBWatchpoint.h.
Referenced by Clear(), GetSP(), operator bool(), operator=(), SBWatchpoint(), SBWatchpoint(), and SetSP().
The documentation for this class was generated from the following files:
SBWatchpoint.h
SBWatchpoint.cpp