LLDB: lldb_private::ProcessProperties Class Reference
lldb_private::ProcessProperties Class Reference
#include <Process.h>
Public Member Functions
ProcessProperties (lldb_private::Process *process)
~ProcessProperties () override
bool GetDisableMemoryCache () const
uint64_t GetMemoryCacheLineSize () const
Args GetExtraStartupCommands () const
void SetExtraStartupCommands (const Args &args)
FileSpec GetPythonOSPluginPath () const
uint32_t GetVirtualAddressableBits () const
void SetVirtualAddressableBits (uint32_t bits)
uint32_t GetHighmemVirtualAddressableBits () const
void SetHighmemVirtualAddressableBits (uint32_t bits)
void SetPythonOSPluginPath (const FileSpec &file)
bool GetIgnoreBreakpointsInExpressions () const
void SetIgnoreBreakpointsInExpressions (bool ignore)
bool GetUnwindOnErrorInExpressions () const
void SetUnwindOnErrorInExpressions (bool ignore)
bool GetStopOnSharedLibraryEvents () const
void SetStopOnSharedLibraryEvents (bool stop)
bool GetDisableLangRuntimeUnwindPlans () const
void SetDisableLangRuntimeUnwindPlans (bool disable)
void DisableLanguageRuntimeUnwindPlansCallback ()
bool GetDetachKeepsStopped () const
void SetDetachKeepsStopped (bool keep_stopped)
bool GetWarningsOptimization () const
bool GetWarningsUnsupportedLanguage () const
bool GetStopOnExec () const
std::chrono::seconds GetUtilityExpressionTimeout () const
std::chrono::seconds GetInterruptTimeout () const
bool GetOSPluginReportsAllThreads () const
void SetOSPluginReportsAllThreads (bool does_report)
bool GetSteppingRunsAllThreads () const
FollowForkMode GetFollowForkMode () const
bool TrackMemoryCacheChanges () const
Public Member Functions inherited from lldb_private::Properties
Properties ()
Properties (const lldb::OptionValuePropertiesSP &collection_sp)
virtual ~Properties ()
lldb::OptionValuePropertiesSP GetValueProperties () const
virtual lldb::OptionValueSP GetPropertyValue (const ExecutionContext *exe_ctx, llvm::StringRef property_path, Status &error) const
virtual Status SetPropertyValue (const ExecutionContext *exe_ctx, VarSetOperationType op, llvm::StringRef property_path, llvm::StringRef value)
virtual Status DumpPropertyValue (const ExecutionContext *exe_ctx, Stream &strm, llvm::StringRef property_path, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllPropertyValues (const ExecutionContext *exe_ctx, Stream &strm, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllDescriptions (CommandInterpreter &interpreter, Stream &strm) const
size_t Apropos (llvm::StringRef keyword, std::vector< const Property * > &matching_properties) const
template<typename T>
T GetPropertyAtIndexAs (uint32_t idx, T default_value, const ExecutionContext *exe_ctx=nullptr) const
template<typename T, typename U = typename std::remove_pointer<T>::type, std::enable_if_t< std::is_pointer_v< T >, bool > = true>
const U * GetPropertyAtIndexAs (uint32_t idx, const ExecutionContext *exe_ctx=nullptr) const
template<typename T>
bool SetPropertyAtIndex (uint32_t idx, T t, const ExecutionContext *exe_ctx=nullptr) const
Protected Attributes
Process * m_process
std::unique_ptr< ProcessExperimentalProperties > m_experimental_properties_up
Protected Attributes inherited from lldb_private::Properties
lldb::OptionValuePropertiesSP m_collection_sp
Additional Inherited Members
Static Public Member Functions inherited from lldb_private::Properties
static llvm::StringRef GetExperimentalSettingsName ()
static bool IsSettingExperimental (llvm::StringRef setting)
Detailed Description
Definition at line 77 of file Process.h.
Constructor & Destructor Documentation
ProcessProperties()
ProcessProperties::ProcessProperties (lldb_private::Process * process)
Definition at line 153 of file Process.cpp.
References lldb_private::OptionValueProperties::CreateLocalCopy(), DisableLanguageRuntimeUnwindPlansCallback(), lldb_private::Properties::GetExperimentalSettingsName(), lldb_private::Process::GetGlobalProperties(), lldb_private::Thread::GetGlobalProperties(), lldb_private::Properties::GetValueProperties(), lldb_private::Properties::m_collection_sp, m_experimental_properties_up, m_process, and lldb_private::Properties::Properties().
~ProcessProperties()
ProcessProperties::~ProcessProperties () override default
References lldb_private::bits().
Member Function Documentation
DisableLanguageRuntimeUnwindPlansCallback()
void ProcessProperties::DisableLanguageRuntimeUnwindPlansCallback ()
Definition at line 287 of file Process.cpp.
References m_process.
Referenced by ProcessProperties().
GetDetachKeepsStopped()
bool ProcessProperties::GetDetachKeepsStopped () const
Definition at line 296 of file Process.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by CommandObjectProcessDetach::DoExecute().
GetDisableLangRuntimeUnwindPlans()
bool ProcessProperties::GetDisableLangRuntimeUnwindPlans () const
Definition at line 275 of file Process.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetDisableMemoryCache()
bool ProcessProperties::GetDisableMemoryCache () const
Definition at line 186 of file Process.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Process::ReadMemory().
GetExtraStartupCommands()
Args ProcessProperties::GetExtraStartupCommands () const
Definition at line 198 of file Process.cpp.
References lldb_private::Properties::m_collection_sp.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::ConnectToDebugserver().
GetFollowForkMode()
FollowForkMode ProcessProperties::GetFollowForkMode () const
Definition at line 369 of file Process.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::DidExec(), lldb_private::process_gdb_remote::ProcessGDBRemote::DidFork(), lldb_private::process_gdb_remote::ProcessGDBRemote::DidVFork(), and RequiresFollowChildWorkaround().
GetHighmemVirtualAddressableBits()
uint32_t ProcessProperties::GetHighmemVirtualAddressableBits () const
Definition at line 226 of file Process.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Process::GetHighmemCodeAddressMask(), and lldb_private::Process::GetHighmemDataAddressMask().
GetIgnoreBreakpointsInExpressions()
bool ProcessProperties::GetIgnoreBreakpointsInExpressions () const
Definition at line 242 of file Process.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::StopInfoBreakpoint::PerformAction().
GetInterruptTimeout()
std::chrono::seconds ProcessProperties::GetInterruptTimeout () const
Definition at line 332 of file Process.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::AsyncThread(), lldb_private::process_gdb_remote::ProcessGDBRemote::DidForkSwitchHardwareTraps(), lldb_private::process_gdb_remote::ProcessGDBRemote::DidForkSwitchSoftwareBreakpoints(), lldb_private::process_gdb_remote::ProcessGDBRemote::DisableBreakpointSite(), lldb_private::process_gdb_remote::ProcessGDBRemote::DisableWatchpoint(), CommandObjectProcessGDBRemotePacketMonitor::DoExecute(), CommandObjectProcessGDBRemotePacketSend::DoExecute(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoHalt(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoReadMemory(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoSignal(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoWriteMemory(), lldb_private::process_gdb_remote::ProcessGDBRemote::EnableBreakpointSite(), lldb_private::process_gdb_remote::ProcessGDBRemote::EnableWatchpoint(), lldb_private::process_gdb_remote::ProcessGDBRemote::FlashDone(), lldb_private::process_gdb_remote::ProcessGDBRemote::FlashErase(), lldb_private::Process::Halt(), lldb_private::process_gdb_remote::ProcessGDBRemote::SendMultiMemReadPacket(), lldb_private::Process::StopForDestroyOrDetach(), lldb_private::process_gdb_remote::ProcessGDBRemote::TraceGetBinaryData(), lldb_private::process_gdb_remote::ProcessGDBRemote::TraceGetState(), lldb_private::process_gdb_remote::ProcessGDBRemote::TraceStart(), lldb_private::process_gdb_remote::ProcessGDBRemote::TraceStop(), and lldb_private::process_gdb_remote::ProcessGDBRemote::TraceSupported().
GetMemoryCacheLineSize()
uint64_t ProcessProperties::GetMemoryCacheLineSize () const
Definition at line 192 of file Process.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetOSPluginReportsAllThreads()
bool ProcessProperties::GetOSPluginReportsAllThreads () const
Definition at line 345 of file Process.cpp.
References ePropertyExperimental, lldb_private::OptionValueProperties::GetPropertyAtIndexAs(), lldb_private::Property::GetValue(), and lldb_private::Properties::m_collection_sp.
GetPythonOSPluginPath()
FileSpec ProcessProperties::GetPythonOSPluginPath () const
Definition at line 210 of file Process.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetSteppingRunsAllThreads()
bool ProcessProperties::GetSteppingRunsAllThreads () const
Definition at line 339 of file Process.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetStopOnExec()
bool ProcessProperties::GetStopOnExec () const
Definition at line 319 of file Process.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetStopOnSharedLibraryEvents()
bool ProcessProperties::GetStopOnSharedLibraryEvents () const
Definition at line 264 of file Process.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetUnwindOnErrorInExpressions()
bool ProcessProperties::GetUnwindOnErrorInExpressions () const
Definition at line 253 of file Process.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
GetUtilityExpressionTimeout()
std::chrono::seconds ProcessProperties::GetUtilityExpressionTimeout () const
Definition at line 325 of file Process.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Process::CallVoidArgVoidPtrReturn(), lldb_private::Process::ControlPrivateStateThread(), lldb_private::PlatformWindows::DoLoadImage(), PlatformPOSIX::EvaluateLibdlExpression(), lldb_private::AppleObjCRuntime::GetObjectDescription(), lldb_private::InferiorCallMmap(), lldb_private::InferiorCallMunmap(), and lldb_private::Process::RunThreadPlan().
GetVirtualAddressableBits()
uint32_t ProcessProperties::GetVirtualAddressableBits () const
Definition at line 215 of file Process.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Process::GetCodeAddressMask(), and lldb_private::Process::GetDataAddressMask().
GetWarningsOptimization()
bool ProcessProperties::GetWarningsOptimization () const
Definition at line 307 of file Process.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Process::PrintWarningOptimization().
GetWarningsUnsupportedLanguage()
bool ProcessProperties::GetWarningsUnsupportedLanguage () const
Definition at line 313 of file Process.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Process::PrintWarningUnsupportedLanguage().
SetDetachKeepsStopped()
void ProcessProperties::SetDetachKeepsStopped (bool keep_stopped)
Definition at line 302 of file Process.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
SetDisableLangRuntimeUnwindPlans()
void ProcessProperties::SetDisableLangRuntimeUnwindPlans (bool disable)
Definition at line 281 of file Process.cpp.
References m_process, and lldb_private::Properties::SetPropertyAtIndex().
SetExtraStartupCommands()
void ProcessProperties::SetExtraStartupCommands (const Args & args)
Definition at line 205 of file Process.cpp.
References lldb_private::Properties::m_collection_sp.
SetHighmemVirtualAddressableBits()
void ProcessProperties::SetHighmemVirtualAddressableBits (uint32_t bits)
Definition at line 232 of file Process.cpp.
References lldb_private::bits(), and lldb_private::Properties::SetPropertyAtIndex().
SetIgnoreBreakpointsInExpressions()
void ProcessProperties::SetIgnoreBreakpointsInExpressions (bool ignore)
Definition at line 248 of file Process.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
SetOSPluginReportsAllThreads()
void ProcessProperties::SetOSPluginReportsAllThreads (bool does_report)
Definition at line 359 of file Process.cpp.
References ePropertyExperimental, lldb_private::Property::GetValue(), lldb_private::Properties::m_collection_sp, and lldb_private::OptionValueProperties::SetPropertyAtIndex().
SetPythonOSPluginPath()
void ProcessProperties::SetPythonOSPluginPath (const FileSpec & file)
Definition at line 237 of file Process.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
SetStopOnSharedLibraryEvents()
void ProcessProperties::SetStopOnSharedLibraryEvents (bool stop)
Definition at line 270 of file Process.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
SetUnwindOnErrorInExpressions()
void ProcessProperties::SetUnwindOnErrorInExpressions (bool ignore)
Definition at line 259 of file Process.cpp.
References lldb_private::Properties::SetPropertyAtIndex().
SetVirtualAddressableBits()
void ProcessProperties::SetVirtualAddressableBits (uint32_t bits)
Definition at line 221 of file Process.cpp.
References lldb_private::bits(), and lldb_private::Properties::SetPropertyAtIndex().
TrackMemoryCacheChanges()
bool ProcessProperties::TrackMemoryCacheChanges () const
Definition at line 376 of file Process.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by lldb_private::Process::WriteMemory().
Member Data Documentation
m_experimental_properties_up
std::unique_ptr<ProcessExperimentalProperties> lldb_private::ProcessProperties::m_experimental_properties_up protected
Definition at line 119 of file Process.h.
Referenced by ProcessProperties().
m_process
Process* lldb_private::ProcessProperties::m_process protected
Definition at line 118 of file Process.h.
Referenced by DisableLanguageRuntimeUnwindPlansCallback(), lldb_private::process_gdb_remote::ProcessGDBRemote::LoadModules(), lldb_private::process_gdb_remote::ProcessGDBRemote::MaybeLoadExecutableModule(), ProcessProperties(), SetDisableLangRuntimeUnwindPlans(), and lldb_private::ScriptedProcess::UpdateQueueListIfNeeded().
The documentation for this class was generated from the following files:
Process.h
Process.cpp