LLDB: lldb_private::StreamString Class Reference
lldb_private::StreamString Class Reference
#include <StreamString.h>
Public Member Functions
StreamString (bool colors=false)
StreamString (uint32_t flags, uint32_t addr_size, lldb::ByteOrder byte_order)
~StreamString () override
void Flush () override
Flush the stream.
void Clear ()
bool Empty () const
size_t GetSize () const
size_t GetSizeOfLastLine () const
llvm::StringRef GetString () const
const char * GetData () const
void FillLastLineToColumn (uint32_t column, char fill_char)
Public Member Functions inherited from lldb_private::Stream
Stream (uint32_t flags, uint32_t addr_size, lldb::ByteOrder byte_order, bool colors=false)
Construct with flags and address size and byte order.
Stream (bool colors=false)
Construct a default Stream, not binary, host byte order and host addr size.
Stream (const Stream &other)
Stream & operator= (const Stream &rhs)
virtual ~Stream ()
Destructor.
size_t Write (const void *src, size_t src_len)
Output character bytes to the stream.
size_t GetWrittenBytes () const
size_t PutChar (char ch)
lldb::ByteOrder SetByteOrder (lldb::ByteOrder byte_order)
Set the byte_order value.
size_t PrintfAsRawHex8 (const char *format,...) __attribute__((__format__(__printf__
Format a C string from a printf style format and variable arguments and encode and append the resulting C string as hex bytes.
size_t size_t PutHex8 (uint8_t uvalue)
Append an uint8_t value in the hexadecimal format to the stream.
size_t PutNHex8 (size_t n, uint8_t uvalue)
size_t PutHex16 (uint16_t uvalue, lldb::ByteOrder byte_order=lldb::eByteOrderInvalid)
size_t PutHex32 (uint32_t uvalue, lldb::ByteOrder byte_order=lldb::eByteOrderInvalid)
size_t PutHex64 (uint64_t uvalue, lldb::ByteOrder byte_order=lldb::eByteOrderInvalid)
size_t PutMaxHex64 (uint64_t uvalue, size_t byte_size, lldb::ByteOrder byte_order=lldb::eByteOrderInvalid)
size_t PutFloat (float f, lldb::ByteOrder byte_order=lldb::eByteOrderInvalid)
size_t PutDouble (double d, lldb::ByteOrder byte_order=lldb::eByteOrderInvalid)
size_t PutLongDouble (long double ld, lldb::ByteOrder byte_order=lldb::eByteOrderInvalid)
size_t PutPointer (void *ptr)
size_t PutBytesAsRawHex8 (const void *src, size_t src_len, lldb::ByteOrder src_byte_order=lldb::eByteOrderInvalid, lldb::ByteOrder dst_byte_order=lldb::eByteOrderInvalid)
size_t PutRawBytes (const void *s, size_t src_len, lldb::ByteOrder src_byte_order=lldb::eByteOrderInvalid, lldb::ByteOrder dst_byte_order=lldb::eByteOrderInvalid)
size_t PutStringAsRawHex8 (llvm::StringRef s)
Stream & operator<< (const char *cstr)
Output a NULL terminated C string cstr to the stream s.
Stream & operator<< (llvm::StringRef str)
Stream & operator<< (const void *p)
Output a pointer value p to the stream s.
Stream & operator<< (char ch)
Output a character ch to the stream s.
Stream & operator<< (uint8_t uval)=delete
Stream & operator<< (uint16_t uval)=delete
Stream & operator<< (uint32_t uval)=delete
Stream & operator<< (uint64_t uval)=delete
Stream & operator<< (int8_t sval)=delete
Stream & operator<< (int16_t sval)=delete
Stream & operator<< (int32_t sval)=delete
Stream & operator<< (int64_t sval)=delete
size_t PutCString (llvm::StringRef cstr)
Output a C string to the stream.
void PutCStringColorHighlighted (llvm::StringRef text, std::optional< HighlightSettings > settings=std::nullopt)
Output a C string to the stream with color highlighting.
size_t EOL ()
Output and End of Line character to the stream.
uint32_t GetAddressByteSize () const
Get the address size in bytes.
Flags & GetFlags ()
The flags accessor.
const Flags & GetFlags () const
The flags const accessor.
lldb::ByteOrder GetByteOrder () const
unsigned GetIndentLevel () const
Get the current indentation level.
void SetIndentLevel (unsigned level)
Set the current indentation level.
size_t Indent (llvm::StringRef s="")
Indent the current line in the stream.
void IndentLess (unsigned amount=2)
Decrement the current indentation level.
void IndentMore (unsigned amount=2)
Increment the current indentation level.
IndentScope MakeIndentScope (unsigned indent_amount=2)
Create an indentation scope that restores the original indent level when the object goes out of scope (RAII).
void Offset (uint32_t offset, const char *format="0x%8.8x: ")
Output an offset value.
size_t Printf (const char *format,...) __attribute__((format(printf
Output printf formatted output to the stream.
size_t size_t PrintfVarArg (const char *format, va_list args)
template<typename... Args>
void Format (const char *format, Args &&... args)
void QuotedCString (const char *cstr, const char *format="\"%s\"")
Output a quoted C string value to the stream.
void SetAddressByteSize (uint32_t addr_size)
Set the address size in bytes.
size_t PutSLEB128 (int64_t uval)
Output a SLEB128 number to the stream.
size_t PutULEB128 (uint64_t uval)
Output a ULEB128 number to the stream.
llvm::raw_ostream & AsRawOstream ()
Returns a raw_ostream that forwards the data to this Stream object.
Protected Member Functions
size_t WriteImpl (const void *s, size_t length) override
Output character bytes to the stream.
Protected Member Functions inherited from lldb_private::Stream
void _PutHex8 (uint8_t uvalue, bool add_prefix)
Protected Attributes
std::string m_packet
Protected Attributes inherited from lldb_private::Stream
Flags m_flags
Dump flags.
uint32_t m_addr_size = 4
Size of an address in bytes.
lldb::ByteOrder m_byte_order
Byte order to use when encoding scalar types.
unsigned m_indent_level = 0
Indention level.
std::size_t m_bytes_written = 0
Number of bytes written so far.
RawOstreamForward m_forwarder
Friends
class ScriptInterpreter
Additional Inherited Members
Public Types inherited from lldb_private::Stream
enum { eBinary = (1 << 0) }
m_flags bit values.
Detailed Description
Definition at line 25 of file StreamString.h.
Constructor & Destructor Documentation
StreamString() [1/2]
StreamString::StreamString (bool colors = false)
Definition at line 14 of file StreamString.cpp.
References lldb::eByteOrderBig, and lldb_private::Stream::Stream().
Referenced by lldb_private::StreamGDBRemote::StreamGDBRemote(), and lldb_private::StreamGDBRemote::StreamGDBRemote().
StreamString() [2/2]
StreamString::StreamString (uint32_t flags, uint32_t addr_size, lldb::ByteOrder byte_order)
Definition at line 16 of file StreamString.cpp.
References m_packet, and lldb_private::Stream::Stream().
~StreamString()
StreamString::~StreamString () override default
Member Function Documentation
Clear()
void StreamString::Clear ()
Definition at line 31 of file StreamString.cpp.
References lldb_private::Stream::m_bytes_written, and m_packet.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::AutoCompleteDiskFileOrDirectory(), lldb::SBStream::Clear(), lldb_private::CommandReturnObject::Clear(), CommandObjectTypeFormatterDelete::CommandObjectTypeFormatterDelete(), PlatformPOSIX::DebugProcess(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoResume(), lldb_private::ClangASTSource::FindObjCMethodDecls(), lldb_private::FormatEntity::Formatter::Format(), lldb_private::ObjCLanguage::GetMethodNameVariants(), EmulationStateARM::LoadRegistersStateFromDictionary(), MakeSpeedTestPacket(), lldb_private::formatters::NSURLSummaryProvider(), lldb_private::DataExtractor::PutToLog(), lldb_private::CommandInterpreter::ResolveCommandImpl(), lldb_private::ScriptInterpreterPythonImpl::ScriptInterpreterPythonImpl(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ServeSymbolLookups(), and lldb_private::BreakpointLocation::ShouldStop().
Empty()
bool StreamString::Empty () const
Definition at line 36 of file StreamString.cpp.
References GetSize().
Referenced by lldb_private::arch_helper(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::EnqueueStopReplyPackets(), lldb_private::AppleObjCRuntime::GetBacktraceThreadFromException(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_stop_reason(), lldb_private::CommandObject::HelpTextContainsWord(), lldb_private::formatters::NSError_SummaryProvider(), lldb_private::formatters::NSException_SummaryProvider(), lldb_private::formatters::NSURLSummaryProvider(), lldb_private::ValueObjectPrinter::PrintDecl(), lldb_private::DataExtractor::PutToLog(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::SendStopReplyPacketForThread().
FillLastLineToColumn()
void StreamString::FillLastLineToColumn (uint32_t column, char fill_char)
Definition at line 53 of file StreamString.cpp.
References m_packet.
Referenced by lldb_private::Instruction::Dump(), and lldb_private::Disassembler::PrintInstructions().
Flush()
void StreamString::Flush () override virtual
Flush the stream.
Subclasses should flush the stream to make any output appear if the stream has any buffering.
Implements lldb_private::Stream.
Definition at line 22 of file StreamString.cpp.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ConfigureRemoteStructuredData(), lldb_private::ClangASTSource::FindObjCMethodDecls(), lldb_private::FormatHelpTextCallback(), lldb_private::Debugger::HandleProcessEvent(), lldb_private::Highlighter::Highlight(), lldb_private::LanguageTypeHelpTextCallback(), ParseStructuredDataPacket(), and SetErrorWithJSON().
GetData()
const char * lldb_private::StreamString::GetData () const inline
Definition at line 45 of file StreamString.h.
References m_packet.
Referenced by lldb_private::Target::AddBreakpoint(), lldb::SBBreakpoint::AddLocation(), lldb_private::BreakpointResolver::AddLocation(), CommandObjectTargetSymbolsAdd::AddModuleSymbols(), lldb_private::Target::AddNameToBreakpoint(), lldb_private::ClangExpressionDeclMap::AddOneFunction(), lldb_private::ValueObject::AddressOf(), lldb_private::Process::Attach(), chown_file(), lldb_private::CommandAlias::CommandAlias(), CommandObjectTypeFormatterDelete::CommandObjectTypeFormatterDelete(), IRForTarget::CreateResultVariable(), lldb_private::formatters::CXXFunctionPointerSummaryProvider(), PlatformPOSIX::DebugProcess(), lldb_private::ValueObject::Dereference(), CommandObjectBreakpointCommandList::DoExecute(), CommandObjectMemoryRead::DoExecute(), CommandObjectProcessGDBRemotePacketMonitor::DoExecute(), CommandObjectSourceList::DoExecute(), CommandObjectTargetModulesAdd::DoExecute(), lldb_private::CommandObjectHelp::DoExecute(), lldb_private::StopInfoUnixSignal::DoShouldNotify(), lldb_private::SymbolLocatorDebugSymbols::DownloadObjectAndSymbolFile(), lldb_private::platform_android::PlatformAndroid::DownloadSymbolFile(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoWriteMemory(), lldb_private::Event::Dump(), lldb_private::ProcessInstanceInfo::DumpAsTableRow(), lldb_private::Property::DumpDescription(), CommandObjectSourceInfo::DumpLinesForAddress(), CommandObjectSourceInfo::DumpLinesInFunctions(), lldb_private::Watchpoint::DumpSnapshots(), lldb_private::DWARFExpression::Evaluate(), lldb::SBFrame::EvaluateExpression(), lldb_private::SymbolContext::FindBestGlobalDataSymbol(), lldb_private::process_gdb_remote::ProcessGDBRemote::FlashErase(), formatStringImpl(), formatStringImpl(), formatStringViewImpl(), formatStringViewImpl(), lldb_private::RegisterContextUnwind::GetAbstractRegisterLocation(), ObjectFileMachO::GetCorefileThreadExtraInfos(), lldb::SBStream::GetData(), lldb_private::ScriptedThreadPlan::GetDescription(), PlatformPOSIX::GetFile(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetFilePermissions(), lldb_private::ScriptedMetadata::GetID(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::GetModuleSpec(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetModuleSpec(), lldb_private::ThreadPlanCallUserExpression::GetRealStopInfo(), lldb_private::IRExecutionUnit::GetRunnableInfo(), lldb_private::AppleObjCTrampolineHandler::GetStepThroughDispatchPlan(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetSupportedStructuredDataPlugins(), CommandObjectSourceInfo::GetSymbolContextsForAddress(), lldb_private::ClangExpressionSourceCode::GetText(), lldb_private::CompactUnwindInfo::GetUnwindPlan(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_jThreadsInfo(), lldb_private::StructuredDataDarwinLog::HandleArrivalOfStructuredData(), lldb_private::Target::StopHookScripted::HandleStop(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexImpl(), DynamicLoaderMacOSXDYLD::InitializeFromAllImageInfos(), lldb_private::RegisterContextUnwind::InitializeNonZerothFrame(), lldb_private::plugin::dwarf::SymbolFileDWARF::InitializeObject(), lldb_private::RegisterContextUnwind::InitializeZerothFrame(), lldb_private::ThreadPlanStepRange::InRange(), lldb_private::Thread::JumpToLine(), lldb_private::StackFrame::LegacyGetValueForVariableExpressionPath(), LoadScriptingResourceForModule(), lldb_private::Module::LoadScriptingResourceInTarget(), LocateExecutableScriptingResourcesFromDSYM(), lldb_private::StringList::LogDump(), lldb_private::Module::LogMessage(), lldb_private::Module::LogMessageVerboseBacktrace(), lldb_private::ThreadPlanStepThrough::LookForPlanToStepThroughFromCurrentPC(), lldb_private::formatters::NSBundleSummaryProvider(), lldb_private::formatters::NSError_SummaryProvider(), lldb_private::formatters::NSException_SummaryProvider(), lldb_private::formatters::NSNotificationSummaryProvider(), lldb_private::formatters::NSTimeZoneSummaryProvider(), ParseEntry(), lldb_private::SymbolFileCTF::ParseHeader(), ParseStructuredDataPacket(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE(), lldb_private::StopInfoBreakpoint::PerformAction(), lldb_private::UnwindPlan::PlanValidAtAddress(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread(), lldb_private::CommandInterpreter::PreprocessToken(), lldb_private::ValueObjectPrinter::PrintDecl(), lldb_private::Broadcaster::BroadcasterImpl::PrivateBroadcastEvent(), PtraceDisplayBytes(), lldb_private::Thread::PushPlan(), PlatformPOSIX::PutFile(), lldb_private::ThreadPlanStepOut::QueueInlinedStepPlan(), lldb_private::process_gdb_remote::GDBRemoteRegisterContext::ReadAllRegisterValues(), lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::ReadRegions(), lldb_private::Platform::ResolveExecutable(), DynamicLoaderPOSIXDYLD::ResolveExecutableModule(), lldb_private::IOHandlerPythonInterpreter::Run(), sddarwinlog_private::RunEnableCommand(), lldb_private::Target::RunStopHooks(), lldb_private::Process::RunThreadPlan(), ObjectFileMachO::SaveCore(), lldb_private::ScriptInterpreterPythonImpl::ScriptInterpreterPythonImpl(), lldb_private::BreakpointResolverAddress::SearchCallback(), lldb_private::BreakpointResolverName::SearchCallback(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceGetBinaryData(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceGetState(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceStart(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceStop(), SetErrorWithJSON(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetFilePermissions(), ObjectFileMachO::SetLoadAddress(), lldb_private::BreakpointLocation::ShouldStop(), lldb_private::Thread::ShouldStop(), lldb_private::ThreadPlanStepInRange::ShouldStop(), lldb_private::ThreadPlanStepInstruction::ShouldStop(), lldb_private::ThreadPlanStepOverRange::ShouldStop(), lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess(), lldb_private::RegisterContextUnwind::TryAdoptArchitectureUnwindPlan(), lldb_private::PlatformWindows::UnloadImage(), lldb_private::CommandObjectMultiwordBreakpoint::VerifyIDs(), lldb_private::dil::Interpreter::Visit(), lldb_private::process_gdb_remote::GDBRemoteRegisterContext::WriteAllRegisterValues(), and lldb_private::process_gdb_remote::GDBRemoteRegisterContext::WriteRegisterBytes().
GetSize()
size_t StreamString::GetSize () const
Definition at line 38 of file StreamString.cpp.
References m_packet.
Referenced by CommandObjectTargetSymbolsAdd::AddModuleSymbols(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ConfigureRemoteStructuredData(), lldb_private::formatters::CXXFunctionPointerSummaryProvider(), CommandObjectThreadContinue::DoExecute(), CommandObjectThreadStepWithTypeAndScope::DoExecute(), CommandObjectThreadUntil::DoExecute(), lldb_private::Address::Dump(), lldb_private::StructuredDataDarwinLog::DumpHeader(), lldb_private::Watchpoint::DumpSnapshots(), Empty(), lldb_private::Options::GenerateOptionUsage(), lldb_private::CommandObject::GetArgumentHelp(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetModulesInfo(), PlatformPOSIX::GetPlatformSpecificConnectionInformation(), lldb::SBStream::GetSize(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_jModulesInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_jThreadsInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qQueryGDBServer(), LoadScriptingResourceForModule(), lldb_private::formatters::NSBundleSummaryProvider(), lldb_private::formatters::NSNotificationSummaryProvider(), lldb_private::formatters::NSTimeZoneSummaryProvider(), lldb_private::CommandInterpreter::PreprocessToken(), lldb_private::DataExtractor::PutToLog(), lldb_private::Target::RunStopHooks(), ObjectFileMachO::SaveCore(), and lldb_private::Debugger::SetPropertyValue().
GetSizeOfLastLine()
size_t StreamString::GetSizeOfLastLine () const
Definition at line 40 of file StreamString.cpp.
References m_packet.
Referenced by lldb_private::Instruction::Dump(), and lldb_private::Disassembler::PrintInstructions().
GetString()
llvm::StringRef StreamString::GetString () const
Definition at line 51 of file StreamString.cpp.
References m_packet.
Referenced by lldb_private::PlatformDarwin::AddClangModuleCompilationOptionsForSDKType(), CommandObjectTargetSymbolsAdd::AddSymbolsForFile(), CommandObjectTargetSymbolsAdd::AddSymbolsForUUID(), lldb_private::VariableAnnotator::AnnotateStructured(), lldb_private::CommandReturnObject::AppendErrorWithFormat(), lldb_private::CommandReturnObject::AppendMessageWithFormat(), lldb_private::CommandReturnObject::AppendNoteWithFormat(), sddarwinlog_private::EnableCommand::AppendStrictSourcesWarning(), lldb_private::CommandReturnObject::AppendWarningWithFormat(), lldb_private::arch_helper(), lldb_private::RegisterFlags::AsTable(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::AttachWaitProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::AutoCompleteDiskFileOrDirectory(), lldb_private::Thread::AutoCompleteThreadPlans(), lldb_private::CommandCompletions::Breakpoints(), lldb_private::AppleObjCTypeEncodingParser::BuildAggregate(), lldb_private::CommandInterpreter::BuildAliasResult(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::BuildTargetXml(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::CalculateMD5(), InstructionLLVMC::CalculateMnemonicOperandsAndComment(), lldb_private::process_gdb_remote::GDBRemoteCommunication::CheckForPacket(), lldb_private::CommandObjectDisassemble::CheckRangeSize(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::CloseFile(), lldb_private::plugin::dwarf::SymbolFileDWARF::CollectCallEdges(), lldb_private::CommandAlias::CommandAlias(), CommandObjectPythonFunction::CommandObjectPythonFunction(), CommandObjectScriptingObjectRaw::CommandObjectScriptingObjectRaw(), CommandObjectTypeFormat::CommandObjectTypeFormat(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ConfigureRemoteStructuredData(), DWARFASTParserClang::ConstructDemangledNameFromDWARF(), lldb_private::ProcessLaunchInfo::ConvertArgumentsForLaunchingInShell(), lldb_private::StringList::CopyList(), CopyStringDataToBufferSP(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::CreateSymlink(), DescribeAddressBriefly(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::Detach(), lldb_private::StopInfoMachException::DeterminePtrauthFailure(), lldb_private::StopInfoMachException::DetermineTagMismatch(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoAttachToProcessWithName(), CommandObjectBreakpointClear::DoExecute(), CommandObjectBreakpointNameList::DoExecute(), CommandObjectCommandsDelete::DoExecute(), CommandObjectMemoryRead::DoExecute(), CommandObjectMemoryWrite::DoExecute(), CommandObjectProcessAttach::DoExecute(), CommandObjectProcessContinue::DoExecute(), CommandObjectProcessGDBRemotePacketMonitor::DoExecute(), CommandObjectProcessKDPPacketSend::DoExecute(), CommandObjectProcessLaunch::DoExecute(), CommandObjectThreadContinue::DoExecute(), CommandObjectThreadPlanList::DoExecute(), CommandObjectThreadStepWithTypeAndScope::DoExecute(), CommandObjectThreadUntil::DoExecute(), lldb_private::CommandObjectApropos::DoExecute(), lldb_private::CommandObjectDWIMPrint::DoExecute(), lldb_private::CommandObjectHelp::DoExecute(), lldb_private::CommandObjectQuit::DoExecute(), lldb_private::LLVMUserExpression::DoExecute(), lldb_private::ClangExpressionParser::DoPrepareForExecution(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoResume(), lldb_private::ThreadPlanStepOverRange::DoWillResume(), lldb_private::SymbolLocatorDebugSymbols::DownloadObjectAndSymbolFile(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoWriteMemory(), lldb_private::Address::Dump(), lldb_private::CoreFileMemoryRange::Dump(), lldb_private::Instruction::Dump(), lldb_private::Property::DumpDescription(), DumpEnumerators(), lldb_private::RegisterFlags::DumpEnums(), lldb_private::StructuredDataDarwinLog::DumpHeader(), DumpInstToLog(), DumpModuleArchitecture(), lldb_private::ValueObject::DumpPrintableRepresentation(), lldb_private::DumpRegisterValue(), EntityPersistentVariable::DumpToLog(), EntityRegister::DumpToLog(), EntityResultVariable::DumpToLog(), EntitySymbol::DumpToLog(), EntityVariableBase::DumpToLog(), DumpUnwindRowsToLog(), lldb_private::StackFrame::DumpUsingFormat(), lldb_private::FormatEntity::Formatter::DumpValue(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::EnqueueStopReplyPackets(), lldb_private::BreakpointIDList::FindAndReplaceIDRanges(), lldb_private::ClangASTSource::FindObjCMethodDecls(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), lldb_private::process_gdb_remote::ProcessGDBRemote::FlashErase(), lldb_private::FormatEntity::Formatter::Format(), FormatCell(), lldb_private::FormatEntity::Formatter::FormatFunctionNameForLanguage(), lldb_private::FormatHelpTextCallback(), lldb_private::CXXFunctionSummaryFormat::FormatObject(), lldb_private::StringSummaryFormat::FormatObject(), lldb_private::TypeFormatImpl_EnumType::FormatObject(), lldb_private::TypeFormatImpl_Format::FormatObject(), lldb_private::CommandCompletions::FrameIndexes(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FStat(), lldb_private::Options::GenerateOptionUsage(), lldb_private::OptionValueDictionary::GetArgs(), lldb_private::CommandObject::GetArgumentHelp(), lldb_private::AppleObjCRuntime::GetBacktraceThreadFromException(), lldb_private::ObjectFile::GetCacheHash(), lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >::GetChildAtIndex(), lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::GetChildAtIndex(), lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< D32, D64 >::GetChildAtIndex(), lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::GetChildAtIndex(), lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdSpanSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxStdVectorSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxVectorBoolSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlSpanSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlVectorSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSArrayMSyntheticFrontEndBase::GetChildAtIndex(), lldb_private::formatters::NSCFDictionarySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSCFSetSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSDictionaryISyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSSetISyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::VectorTypeSyntheticFrontEnd::GetChildAtIndex(), lldb_private::BytecodeSummaryFormat::GetDescription(), lldb_private::BytecodeSyntheticChildren::GetDescription(), lldb_private::CXXFunctionSummaryFormat::GetDescription(), lldb_private::CXXSyntheticChildren::GetDescription(), lldb_private::ScriptedSyntheticChildren::GetDescription(), lldb_private::ScriptSummaryFormat::GetDescription(), lldb_private::StopInfoBreakpoint::GetDescription(), lldb_private::StopInfoMachException::GetDescription(), lldb_private::StopInfoThreadPlan::GetDescription(), lldb_private::StopInfoUnixSignal::GetDescription(), lldb_private::StopInfoWatchpoint::GetDescription(), lldb_private::StringSummaryFormat::GetDescription(), lldb_private::Target::StopHook::GetDescription(), lldb_private::TypeCategoryImpl::GetDescription(), lldb_private::TypeFilterImpl::GetDescription(), lldb_private::TypeFormatImpl_EnumType::GetDescription(), lldb_private::TypeFormatImpl_Format::GetDescription(), lldb_private::CommandReturnObject::GetErrorString(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetExtendedInfoForThread(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetFileExists(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetFileLoadAddress(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetFilePermissions(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetFileSize(), lldb_private::CommandObject::GetFormattedCommandArguments(), lldb_private::PlatformDarwin::GetFullNameForDylib(), lldb_private::PlatformWindows::GetFullNameForDylib(), lldb_private::MemoryHistoryASan::GetHistoryThreads(), NSIndexPathSyntheticFrontEnd::Impl::InlinedIndexes::GetIndexAtIndex(), lldb_private::CommandReturnObject::GetInlineDiagnosticString(), lldb::SBDebugger::GetInternalVariableValue(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetLoadedDynamicLibrariesInfos_sender(), lldb_private::ValueObject::GetLocationAsCStringImpl(), lldb_private::Module::GetMemoryObjectFile(), lldb_private::ObjCLanguage::GetMethodNameVariants(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetModuleInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetModulesInfo(), lldb_private::TypeSystemClang::GetObjCBitSize(), lldb_private::ValueObject::GetObjectDescription(), lldb_private::Target::GetOrCreateModule(), PlatformPOSIX::GetPlatformSpecificConnectionInformation(), lldb_private::FormatManager::GetPossibleMatches(), GetRegistersAsJSON(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetRemoteQSupported(), lldb_private::IRExecutionUnit::GetRunnableInfo(), lldb_private::PlatformMacOSX::GetSDKDirectory(), lldb_private::PlatformDarwin::GetSDKDirectoryForModules(), lldb::SBDebugger::GetSetting(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetSharedCacheInfo(), lldb_private::SourceLocationSpec::GetString(), lldb_private::CommandObject::GetSyntax(), lldb_private::ClangExpressionSourceCode::GetText(), lldb_private::wasm::ProcessWasm::GetWasmCallStack(), lldb_private::wasm::ProcessWasm::GetWasmVariable(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle__M(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_g(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_jLLDBTraceGetBinaryData(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_jModulesInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_jSignalsInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_jThreadsInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_memory_read(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_p(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qC(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qC(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qFileLoadAddress(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qfThreadInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qGetWorkingDir(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qGetWorkingDir(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qGroupName(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qHostInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qLaunchGDBServer(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qLaunchSuccess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qMemoryRegionInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qMemTags(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qModuleInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qPathComplete(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qPlatform_chmod(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qPlatform_mkdir(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qPlatform_shell(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qProcessInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qProcessInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qProcessInfoPID(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qQueryGDBServer(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qRegisterInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qSaveCore(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_QSaveRegisterState(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qSpeedTest(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qsProcessInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qUserName(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qWatchpointSupportInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qXfer(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_stop_reason(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_vCont_actions(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_Close(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_Exists(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_FStat(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_MD5(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_Mode(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_Open(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_pRead(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_pWrite(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_Size(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_symlink(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_unlink(), CommandObjectTargetModulesSearchPathsInsert::HandleArgumentCompletion(), CommandObjectWithFrameRecognizerArg::HandleArgumentCompletion(), HandleFunctionNameWithArgs(), lldb_private::Debugger::HandleProcessEvent(), lldb_private::CommandObject::HelpTextContainsWord(), lldb_private::ClangHighlighter::Highlight(), lldb_private::Highlighter::Highlight(), lldb_private::TreeSitterHighlighter::HighlightRange(), lldb_private::CommandInterpreter::Initialize(), lldb_private::platform_android::AdbClient::internalShell(), lldb_private::IOHandlerConfirm::IOHandlerConfirm(), IOHandlerLuaInterpreter::IOHandlerIsInputComplete(), lldb_private::Thread::JumpToLine(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::KillSpawnedProcess(), lldb_private::LanguageTypeHelpTextCallback(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::LaunchGDBServer(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::LaunchProcess(), lldb_private::ProcessDebugger::LaunchProcess(), lldb_private::DynamicLoader::LoadBinaryWithUUIDAndAddress(), DynamicLoaderDarwinKernel::KextImageInfo::LoadImageUsingMemoryModule(), EmulationStateARM::LoadRegistersStateFromDictionary(), LocateExecutableScriptingResourcesFromDSYM(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::MakeDirectory(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::MakeUrl(), lldb_private::CommandCompletions::ModuleUUIDs(), lldb_private::process_gdb_remote::ProcessGDBRemote::MonitorDebugserverProcess(), lldb_private::formatters::NSURLSummaryProvider(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::OpenFile(), lldb_private::operator<<(), lldb_private::operator<<(), lldb_private::CommandInterpreter::OutputFormattedHelpText(), lldb_private::CommandInterpreter::OutputHelpText(), lldb_private::Options::ParseAlias(), InstructionLLVMC::ParseOperands(), ObjectFileELF::ParseRISCVAttributes(), lldb_private::StopInfoBreakpoint::PerformAction(), lldb_private::StopInfoWatchpoint::PerformAction(), ABIMacOSX_arm64::PrepareTrivialCall(), ABISysV_arm64::PrepareTrivialCall(), ABISysV_mips64::PrepareTrivialCall(), ABISysV_mips::PrepareTrivialCall(), ABISysV_ppc64::PrepareTrivialCall(), ABISysV_ppc::PrepareTrivialCall(), ABISysV_s390x::PrepareTrivialCall(), ABISysV_x86_64::PrepareTrivialCall(), ABIWindows_x86_64::PrepareTrivialCall(), lldb_private::FormatEntity::PrettyPrintFunctionArguments(), InterpreterStackFrame::PrintData(), lldb_private::ValueObjectPrinter::PrintDecl(), lldb_private::DiagnosticManager::Printf(), lldb_private::Disassembler::PrintInstructions(), lldb_private::Editline::PromptForIndex(), lldb_private::DataExtractor::PutToLog(), lldb_private::Thread::QueueThreadPlan(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ReadFile(), UnwindAssemblyInstEmulation::ReadMemory(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ReadMemoryTags(), lldb_private::AppleObjCTypeEncodingParser::ReadQuotedString(), UnwindAssemblyInstEmulation::ReadRegister(), lldb_private::AppleObjCTypeEncodingParser::ReadStructName(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::ReadXferObject(), lldb::SBStream::RedirectToFile(), lldb::SBStream::RedirectToFile(), lldb::SBStream::RedirectToFileDescriptor(), lldb_private::Statusline::Redraw(), lldb_private::Module::ReportError(), lldb_private::Module::ReportErrorIfModifyDetected(), lldb_private::ThreadPlanCallFunction::ReportRegisterState(), lldb_private::Module::ReportWarning(), lldb_private::Module::ReportWarningOptimization(), lldb_private::Module::ReportWarningUnsupportedLanguage(), lldb_private::CommandInterpreter::ResolveCommandImpl(), lldb_private::SymbolFileCTF::ResolveTypeUID(), lldb_private::InstrumentationRuntimeTSan::RetrieveReportData(), lldb_private::InstrumentationRuntimeUBSan::RetrieveReportData(), lldb_private::ReportRetriever::RetrieveReportData(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::RunShellCommand(), lldb_private::Process::RunThreadPlan(), lldb_private::process_gdb_remote::ProcessGDBRemote::SaveCore(), ObjectFileMachO::SaveCore(), lldb_private::BreakpointResolverFileLine::SearchCallback(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendEnvironmentPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendLaunchArchPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendLaunchEventDataPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendNotificationPacketNoLock(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::SendONotification(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendPacketNoLock(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendRawPacketNoLock(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendSetCurrentThreadPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendSpeedTestPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendStdinNotification(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::SendStopReplyPacketForThread(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::SendStructuredDataPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceGetBinaryData(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceGetState(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceStart(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceStop(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceSupported(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::SendWResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ServeSymbolLookups(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetFilePermissions(), lldb_private::CommandObjectExpression::CommandOptions::SetOptionValue(), lldb_private::OptionGroupWatchpoint::SetOptionValue(), lldb_private::SaveCoreOptions::SetPluginName(), lldb_private::Debugger::SetPropertyValue(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetSTDERR(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetSTDIN(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetSTDOUT(), lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo(), lldb_private::CommandCompletions::SettingsNames(), lldb_private::OptionValueEnumeration::SetValueFromString(), lldb_private::OptionValueLanguage::SetValueFromString(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetWorkingDir(), Sprintf(), lldb_private::CommandCompletions::StopHookIDs(), InterpreterStackFrame::SummarizeValue(), DisassemblerLLVMC::SymbolLookup(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SyncThreadState(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::TestPacketSpeed(), lldb_private::CommandCompletions::ThreadIDs(), lldb_private::CommandCompletions::ThreadIndexes(), lldb_private::OptionArgParser::ToFormat(), lldb_private::OptionValueFileColonLine::ToJSON(), lldb_private::OptionArgParser::ToOptionEnum(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::Unlink(), lldb_private::StackFrame::UpdateCurrentFrameFromPreviousFrame(), lldb::SBValue::Watch(), lldb_private::CommandCompletions::WatchPointIDs(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteFile(), UnwindAssemblyInstEmulation::WriteMemory(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteMemoryTags(), lldb_private::EmulateInstruction::WriteMemoryUnsigned(), and UnwindAssemblyInstEmulation::WriteRegister().
WriteImpl()
size_t StreamString::WriteImpl (const void * src, size_t src_len) override protected virtual
Output character bytes to the stream.
Appends src_len characters from the buffer src to the stream.
Parameters
[in] src A buffer containing at least src_len bytes of data.
[in] src_len A number of bytes to append to the stream.
Returns
The number of bytes that were appended to the stream.
Implements lldb_private::Stream.
Definition at line 26 of file StreamString.cpp.
References m_packet.
Friends And Related Symbol Documentation
ScriptInterpreter
friend class ScriptInterpreter friend
Definition at line 50 of file StreamString.h.
References ScriptInterpreter.
Referenced by ScriptInterpreter.
Member Data Documentation
m_packet
std::string lldb_private::StreamString::m_packet protected
Definition at line 52 of file StreamString.h.
Referenced by Clear(), FillLastLineToColumn(), GetData(), GetSize(), GetSizeOfLastLine(), GetString(), StreamString(), and WriteImpl().
The documentation for this class was generated from the following files:
StreamString.h
StreamString.cpp