LLDB: lldb_private::ScriptedThreadPlan Class Reference
lldb_private::ScriptedThreadPlan Class Reference
#include <ScriptedThreadPlan.h>
Public Member Functions
ScriptedThreadPlan (Thread &thread, const char *class_name, const StructuredDataImpl &args_data)
void GetDescription (Stream *s, lldb::DescriptionLevel level) override
Print a description of this thread to the stream s.
bool ValidatePlan (Stream *error) override
Returns whether this plan could be successfully created.
bool ShouldStop (Event *event_ptr) override
bool MischiefManaged () override
bool WillStop () override
bool StopOthers () override
void SetStopOthers (bool new_value) override
void DidPush () override
bool IsPlanStale () override
bool DoWillResume (lldb::StateType resume_state, bool current_plan) override
Public Member Functions inherited from lldb_private::ThreadPlan
virtual ~ThreadPlan ()
const char * GetName () const
Returns the name of this thread plan.
Thread & GetThread ()
Returns the Thread that is using this thread plan.
Target & GetTarget ()
const Target & GetTarget () const
void ClearThreadCache ()
Clear the Thread* cache.
bool TracerExplainsStop ()
lldb::StateType RunState ()
bool PlanExplainsStop (Event *event_ptr)
virtual bool ShouldAutoContinue (Event *event_ptr)
Returns whether this thread plan overrides the ShouldStop of subsequently processed plans.
virtual Vote ShouldReportStop (Event *event_ptr)
Vote ShouldReportRun (Event *event_ptr)
virtual bool SupportsResumeOthers ()
virtual bool ShouldRunBeforePublicStop ()
bool WillResume (lldb::StateType resume_state, bool current_plan)
bool IsControllingPlan ()
virtual bool IsLeafPlan ()
bool SetIsControllingPlan (bool value)
virtual bool OkayToDiscard ()
void SetOkayToDiscard (bool value)
virtual void ThreadDestroyed ()
bool GetPrivate ()
void SetPrivate (bool input)
virtual void DidPop ()
ThreadPlanKind GetKind () const
bool IsPlanComplete ()
void SetPlanComplete (bool success=true)
bool PlanSucceeded ()
virtual bool IsBasePlan ()
lldb::ThreadPlanTracerSP & GetThreadPlanTracer ()
void SetThreadPlanTracer (lldb::ThreadPlanTracerSP new_tracer_sp)
void DoTraceLog ()
virtual lldb::ValueObjectSP GetReturnValueObject ()
virtual lldb::ExpressionVariableSP GetExpressionVariable ()
virtual void RestoreThreadState ()
virtual bool IsVirtualStep ()
bool SetIterationCount (size_t count)
virtual lldb::RunDirection GetDirection () const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Protected Member Functions
bool DoPlanExplainsStop (Event *event_ptr) override
lldb::StateType GetPlanRunState () override
ScriptInterpreter * GetScriptInterpreter ()
Protected Member Functions inherited from lldb_private::ThreadPlan
ThreadPlan (ThreadPlanKind kind, const char *name, Thread &thread, Vote report_stop_vote, Vote report_run_vote)
void PushPlan (lldb::ThreadPlanSP &thread_plan_sp)
ThreadPlan * GetPreviousPlan ()
lldb::StopInfoSP GetPrivateStopInfo ()
void SetStopInfo (lldb::StopInfoSP stop_reason_sp)
bool IsUsuallyUnexplainedStopReason (lldb::StopReason)
Private Member Functions
ScriptedThreadPlan (const ScriptedThreadPlan &)=delete
const ScriptedThreadPlan & operator= (const ScriptedThreadPlan &)=delete
Private Attributes
std::string m_class_name
StructuredDataImpl m_args_data
std::string m_error_str
StructuredData::ObjectSP m_implementation_sp
StreamString m_stop_description
bool m_did_push
bool m_stop_others
lldb::ScriptedThreadPlanInterfaceSP m_interface
Additional Inherited Members
Public Types inherited from lldb_private::ThreadPlan
enum ThreadPlanKind {
eKindGeneric , eKindNull , eKindBase , eKindCallFunction ,
eKindPython , eKindStepInstruction , eKindStepOut , eKindStepOverBreakpoint ,
eKindStepOverRange , eKindStepInRange , eKindRunToAddress , eKindStepThrough ,
eKindStepUntil , eKindSingleThreadTimeout
}
Protected Attributes inherited from lldb_private::ThreadPlan
Status m_status
Process & m_process
lldb::tid_t m_tid
Vote m_report_stop_vote
Vote m_report_run_vote
bool m_takes_iteration_count
bool m_could_not_resolve_hw_bp
int32_t m_iteration_count = 1
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Detailed Description
Definition at line 29 of file ScriptedThreadPlan.h.
Constructor & Destructor Documentation
ScriptedThreadPlan() [1/2]
ScriptedThreadPlan::ScriptedThreadPlan (Thread & thread, const char * class_name, const StructuredDataImpl & args_data)
Definition at line 27 of file ScriptedThreadPlan.cpp.
References lldb_private::ScriptInterpreter::CreateScriptedThreadPlanInterface(), lldb_private::ThreadPlan::eKindPython, lldb_private::eVoteNoOpinion, GetScriptInterpreter(), m_args_data, m_class_name, m_did_push, m_interface, m_stop_others, lldb_private::ThreadPlan::SetIsControllingPlan(), lldb_private::ThreadPlan::SetOkayToDiscard(), lldb_private::ThreadPlan::SetPlanComplete(), lldb_private::ThreadPlan::SetPrivate(), and lldb_private::ThreadPlan::ThreadPlan().
Referenced by operator=(), and ScriptedThreadPlan().
ScriptedThreadPlan() [2/2]
lldb_private::ScriptedThreadPlan::ScriptedThreadPlan (const ScriptedThreadPlan &) private delete
References ScriptedThreadPlan().
Member Function Documentation
DidPush()
void ScriptedThreadPlan::DidPush () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 77 of file ScriptedThreadPlan.cpp.
References m_args_data, m_class_name, m_did_push, m_error_str, m_implementation_sp, m_interface, and lldb_private::ThreadPlan::SetPlanComplete().
DoPlanExplainsStop()
bool ScriptedThreadPlan::DoPlanExplainsStop (Event * event_ptr) override protected virtual
Implements lldb_private::ThreadPlan.
Definition at line 128 of file ScriptedThreadPlan.cpp.
References lldb_private::GetLog(), LLDB_LOG_ERROR, LLDB_LOGF, m_class_name, m_implementation_sp, m_interface, lldb_private::ThreadPlan::SetPlanComplete(), and lldb_private::Thread.
DoWillResume()
bool ScriptedThreadPlan::DoWillResume (lldb::StateType resume_state, bool current_plan) override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 213 of file ScriptedThreadPlan.cpp.
References m_stop_description.
GetDescription()
void ScriptedThreadPlan::GetDescription (Stream * s, lldb::DescriptionLevel level) override virtual
Print a description of this thread to the stream s.
thread. Don't expect that the result of GetThread is valid in the description method. This might get called when the underlying Thread has not been reported, so we only know the TID and not the thread.
Parameters
[in] s The stream to which to print the description.
[in] level The level of description desired. Note that eDescriptionLevelBrief will be used in the stop message printed when the plan is complete.
Implements lldb_private::ThreadPlan.
Definition at line 175 of file ScriptedThreadPlan.cpp.
References lldb_private::StreamString::GetData(), lldb_private::GetLog(), GetScriptInterpreter(), LLDB_LOG_ERROR, LLDB_LOGF, m_class_name, m_implementation_sp, m_interface, m_stop_description, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and lldb_private::Thread.
Referenced by MischiefManaged().
GetPlanRunState()
lldb::StateType ScriptedThreadPlan::GetPlanRunState () override protected virtual
Implements lldb_private::ThreadPlan.
Definition at line 165 of file ScriptedThreadPlan.cpp.
References lldb::eStateRunning, lldb_private::GetLog(), LLDB_LOGF, m_class_name, m_implementation_sp, m_interface, and lldb_private::Thread.
GetScriptInterpreter()
ScriptInterpreter * ScriptedThreadPlan::GetScriptInterpreter () protected
Definition at line 73 of file ScriptedThreadPlan.cpp.
References lldb_private::ThreadPlan::m_process.
Referenced by GetDescription(), and ScriptedThreadPlan().
IsPlanStale()
bool ScriptedThreadPlan::IsPlanStale () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 110 of file ScriptedThreadPlan.cpp.
References lldb_private::GetLog(), LLDB_LOG_ERROR, LLDB_LOGF, m_class_name, m_implementation_sp, m_interface, lldb_private::ThreadPlan::SetPlanComplete(), and lldb_private::Thread.
MischiefManaged()
bool ScriptedThreadPlan::MischiefManaged () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 147 of file ScriptedThreadPlan.cpp.
References lldb::eDescriptionLevelBrief, GetDescription(), lldb_private::GetLog(), lldb_private::ThreadPlan::IsPlanComplete(), LLDB_LOGF, m_class_name, m_implementation_sp, m_stop_description, and lldb_private::Thread.
operator=()
const ScriptedThreadPlan & lldb_private::ScriptedThreadPlan::operator= (const ScriptedThreadPlan &) private delete
References ScriptedThreadPlan().
SetStopOthers()
void lldb_private::ScriptedThreadPlan::SetStopOthers (bool new_value) inline override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 46 of file ScriptedThreadPlan.h.
References m_stop_others.
ShouldStop()
bool ScriptedThreadPlan::ShouldStop (Event * event_ptr) override virtual
Implements lldb_private::ThreadPlan.
Definition at line 92 of file ScriptedThreadPlan.cpp.
References lldb_private::GetLog(), LLDB_LOG_ERROR, LLDB_LOGF, m_class_name, m_implementation_sp, m_interface, lldb_private::ThreadPlan::SetPlanComplete(), and lldb_private::Thread.
StopOthers()
bool lldb_private::ScriptedThreadPlan::StopOthers () inline override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 44 of file ScriptedThreadPlan.h.
References m_stop_others.
ValidatePlan()
bool ScriptedThreadPlan::ValidatePlan (Stream * error) override virtual
Returns whether this plan could be successfully created.
Parameters
[in] error A stream to which to print some reason why the plan could not be created. Can be NULL.
Returns
true if the plan should be queued, false otherwise.
Implements lldb_private::ThreadPlan.
Definition at line 58 of file ScriptedThreadPlan.cpp.
References error(), m_did_push, m_error_str, and m_implementation_sp.
WillStop()
bool ScriptedThreadPlan::WillStop () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 206 of file ScriptedThreadPlan.cpp.
References lldb_private::GetLog(), LLDB_LOGF, m_class_name, and lldb_private::Thread.
Member Data Documentation
m_args_data
StructuredDataImpl lldb_private::ScriptedThreadPlan::m_args_data private
Definition at line 63 of file ScriptedThreadPlan.h.
Referenced by DidPush(), and ScriptedThreadPlan().
m_class_name
std::string lldb_private::ScriptedThreadPlan::m_class_name private
Definition at line 62 of file ScriptedThreadPlan.h.
Referenced by DidPush(), DoPlanExplainsStop(), GetDescription(), GetPlanRunState(), IsPlanStale(), MischiefManaged(), ScriptedThreadPlan(), ShouldStop(), and WillStop().
m_did_push
bool lldb_private::ScriptedThreadPlan::m_did_push private
Definition at line 67 of file ScriptedThreadPlan.h.
Referenced by DidPush(), ScriptedThreadPlan(), and ValidatePlan().
m_error_str
std::string lldb_private::ScriptedThreadPlan::m_error_str private
Definition at line 64 of file ScriptedThreadPlan.h.
Referenced by DidPush(), and ValidatePlan().
m_implementation_sp
StructuredData::ObjectSP lldb_private::ScriptedThreadPlan::m_implementation_sp private
Definition at line 65 of file ScriptedThreadPlan.h.
Referenced by DidPush(), DoPlanExplainsStop(), GetDescription(), GetPlanRunState(), IsPlanStale(), MischiefManaged(), ShouldStop(), and ValidatePlan().
m_interface
lldb::ScriptedThreadPlanInterfaceSP lldb_private::ScriptedThreadPlan::m_interface private
Definition at line 69 of file ScriptedThreadPlan.h.
Referenced by DidPush(), DoPlanExplainsStop(), GetDescription(), GetPlanRunState(), IsPlanStale(), ScriptedThreadPlan(), and ShouldStop().
m_stop_description
StreamString lldb_private::ScriptedThreadPlan::m_stop_description private
Definition at line 66 of file ScriptedThreadPlan.h.
Referenced by DoWillResume(), GetDescription(), and MischiefManaged().
m_stop_others
bool lldb_private::ScriptedThreadPlan::m_stop_others private
Definition at line 68 of file ScriptedThreadPlan.h.
Referenced by ScriptedThreadPlan(), SetStopOthers(), and StopOthers().
The documentation for this class was generated from the following files:
ScriptedThreadPlan.h
ScriptedThreadPlan.cpp