LLDB: ABISysV_arm Class Reference
ABISysV_arm Class Reference
#include <ABISysV_arm.h>
Public Member Functions
~ABISysV_arm () override=default
size_t GetRedZoneSize () const override
bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t func_addr, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override
bool GetArgumentValues (lldb_private::Thread &thread, lldb_private::ValueList &values) const override
lldb_private::Status SetReturnValueObject (lldb::StackFrameSP &frame_sp, lldb::ValueObjectSP &new_value) override
lldb::UnwindPlanSP CreateFunctionEntryUnwindPlan () override
lldb::UnwindPlanSP CreateDefaultUnwindPlan () override
bool RegisterIsVolatile (const lldb_private::RegisterInfo *reg_info) override
bool CallFrameAddressIsValid (lldb::addr_t cfa) override
bool CodeAddressIsValid (lldb::addr_t pc) override
lldb::addr_t FixCodeAddress (lldb::addr_t pc) override
Some targets might use bits in a code address to indicate a mode switch.
const lldb_private::RegisterInfo * GetRegisterInfoArray (uint32_t &count) override
bool IsArmHardFloat (lldb_private::Thread &thread) const
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::RegInfoBasedABI
void AugmentRegisterInfo (std::vector< DynamicRegisterInfo::Register > &regs) override
Public Member Functions inherited from lldb_private::ABI
~ABI () override
virtual bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::Type &prototype, llvm::ArrayRef< CallArgument > args) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, CompilerType &type, bool persistent=true) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, llvm::Type &type, bool persistent=true) const
virtual bool GetFallbackRegisterLocation (const RegisterInfo *reg_info, UnwindPlan::Row::AbstractRegisterLocation &unwind_regloc)
virtual lldb::addr_t FixAnyAddress (lldb::addr_t pc)
Use this method when you do not know, or do not care what kind of address you are fixing.
llvm::MCRegisterInfo & GetMCRegisterInfo ()
virtual bool GetPointerReturnRegister (const char *&name)
virtual uint64_t GetStackFrameSize ()
virtual lldb::addr_t FixDataAddress (lldb::addr_t pc)
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static lldb::ABISP CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec &arch)
static llvm::StringRef GetPluginNameStatic ()
Static Public Member Functions inherited from lldb_private::ABI
static lldb::ABISP FindPlugin (lldb::ProcessSP process_sp, const ArchSpec &arch)
Protected Member Functions
lldb::ValueObjectSP GetReturnValueObjectImpl (lldb_private::Thread &thread, lldb_private::CompilerType &ast_type) const override
Protected Member Functions inherited from lldb_private::RegInfoBasedABI
bool GetRegisterInfoByName (llvm::StringRef name, RegisterInfo &info)
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Protected Member Functions inherited from lldb_private::ABI
virtual lldb::ValueObjectSP GetReturnValueObjectImpl (Thread &thread, llvm::Type &ir_type) const
lldb::ProcessSP GetProcessSP () const
Request to get a Process shared pointer.
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Additional Inherited Members
Static Protected Member Functions inherited from lldb_private::ABI
static std::unique_ptr< llvm::MCRegisterInfo > MakeMCRegisterInfo (const ArchSpec &arch)
Utility function to construct a MCRegisterInfo using the ArchSpec triple.
Protected Attributes inherited from lldb_private::ABI
lldb::ProcessWP m_process_wp
std::unique_ptr< llvm::MCRegisterInfo > m_mc_register_info_up
Detailed Description
Definition at line 15 of file ABISysV_arm.h.
Constructor & Destructor Documentation
~ABISysV_arm()
ABISysV_arm::~ABISysV_arm () override default
References sp.
Member Function Documentation
CallFrameAddressIsValid()
bool ABISysV_arm::CallFrameAddressIsValid (lldb::addr_t cfa) inline override virtual
Implements lldb_private::ABI.
Definition at line 38 of file ABISysV_arm.h.
CodeAddressIsValid()
bool ABISysV_arm::CodeAddressIsValid (lldb::addr_t pc) inline override virtual
Implements lldb_private::ABI.
Definition at line 47 of file ABISysV_arm.h.
References pc, and UINT32_MAX.
CreateDefaultUnwindPlan()
UnwindPlanSP ABISysV_arm::CreateDefaultUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 1910 of file ABISysV_arm.cpp.
References dwarf_pc, dwarf_r11, lldb_private::eLazyBoolNo, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), lldb_private::UnwindPlan::Row::SetRegisterLocationToAtCFAPlusOffset(), and lldb_private::UnwindPlan::Row::SetUnspecifiedRegistersAreUndefined().
CreateFunctionEntryUnwindPlan()
UnwindPlanSP ABISysV_arm::CreateFunctionEntryUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 1891 of file ABISysV_arm.cpp.
References dwarf_lr, dwarf_pc, dwarf_sp, lldb_private::eLazyBoolNo, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), and lldb_private::UnwindPlan::Row::SetRegisterLocationToRegister().
CreateInstance()
ABISP ABISysV_arm::CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec & arch) static
Definition at line 1304 of file ABISysV_arm.cpp.
References lldb_private::ArchSpec::GetTriple(), and lldb_private::ABI::MakeMCRegisterInfo().
Referenced by Initialize(), and Terminate().
FixCodeAddress()
lldb::addr_t ABISysV_arm::FixCodeAddress (lldb::addr_t pc) inline override virtual
Some targets might use bits in a code address to indicate a mode switch.
ARM uses bit zero to signify a code address is thumb, so any ARM ABI plug-ins would strip those bits.
Reimplemented from lldb_private::ABI.
Definition at line 54 of file ABISysV_arm.h.
References pc.
GetArgumentValues()
bool ABISysV_arm::GetArgumentValues (lldb_private::Thread & thread, lldb_private::ValueList & values) const override virtual
Implements lldb_private::ABI.
Definition at line 1425 of file ABISysV_arm.cpp.
References lldb::eRegisterKindGeneric, error(), lldb_private::Process::GetAddressByteSize(), lldb_private::CompilerType::GetBitSize(), lldb_private::Value::GetCompilerType(), lldb_private::ExecutionContext::GetProcessRef(), lldb_private::RegisterContext::GetRegisterInfo(), lldb_private::Value::GetScalar(), lldb_private::RegisterValue::GetScalarValue(), lldb_private::ValueList::GetSize(), lldb_private::RegisterContext::GetSP(), lldb_private::ValueList::GetValueAtIndex(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), lldb_private::CompilerType::IsPointerOrReferenceType(), LLDB_REGNUM_GENERIC_ARG1, lldb_private::RegisterContext::ReadRegister(), lldb_private::Process::ReadScalarIntegerFromMemory(), lldb_private::RegisterValue::SignExtend(), and sp.
GetPluginName()
llvm::StringRef ABISysV_arm::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 77 of file ABISysV_arm.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef ABISysV_arm::GetPluginNameStatic () inline static
Definition at line 73 of file ABISysV_arm.h.
Referenced by GetPluginName(), and Initialize().
GetRedZoneSize()
size_t ABISysV_arm::GetRedZoneSize () const override virtual
Implements lldb_private::ABI.
Definition at line 1299 of file ABISysV_arm.cpp.
GetRegisterInfoArray()
const lldb_private::RegisterInfo * ABISysV_arm::GetRegisterInfoArray (uint32_t & count) override virtual
Implements lldb_private::RegInfoBasedABI.
Definition at line 1294 of file ABISysV_arm.cpp.
References g_register_infos, and k_num_register_infos.
GetReturnValueObjectImpl()
ValueObjectSP ABISysV_arm::GetReturnValueObjectImpl (lldb_private::Thread & thread, lldb_private::CompilerType & ast_type) const override protected virtual
Implements lldb_private::ABI.
Definition at line 1535 of file ABISysV_arm.cpp.
References lldb_private::ValueObjectConstResult::Create(), dwarf_d0, dwarf_s0, lldb::eRegisterKindDWARF, lldb::eRegisterKindGeneric, error(), lldb_private::RegisterValue::GetAsDouble(), lldb_private::RegisterValue::GetAsFloat(), lldb_private::RegisterValue::GetAsMemoryData(), lldb_private::CompilerType::GetBitSize(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::CompilerType::GetByteSize(), lldb_private::CompilerType::GetFieldAtIndex(), lldb_private::CompilerType::GetNumFields(), lldb_private::RegisterContext::GetRegisterInfo(), lldb_private::RegisterContext::GetRegisterInfoByName(), GetReturnValuePassedInMemory(), lldb_private::Value::GetScalar(), lldb_private::CompilerType::GetTypeInfo(), lldb_private::CompilerType::IsAggregateType(), IsArmHardFloat(), lldb_private::CompilerType::IsCompleteType(), lldb_private::CompilerType::IsComplexType(), lldb_private::CompilerType::IsFloatingPointType(), lldb_private::CompilerType::IsHomogeneousAggregate(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), lldb_private::CompilerType::IsPointerType(), lldb_private::CompilerType::IsVectorType(), LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_ARG2, lldb_private::RegisterContext::ReadRegister(), lldb_private::RegisterContext::ReadRegisterAsUnsigned(), lldb_private::DataExtractor::SetAddressByteSize(), lldb_private::DataExtractor::SetByteOrder(), lldb_private::Value::SetBytes(), lldb_private::Value::SetCompilerType(), lldb_private::DataExtractor::SetData(), and UINT32_MAX.
Initialize()
void ABISysV_arm::Initialize () static
Definition at line 2109 of file ABISysV_arm.cpp.
References CreateInstance(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Referenced by ABIARM::Initialize().
IsArmHardFloat()
bool ABISysV_arm::IsArmHardFloat (lldb_private::Thread & thread) const
Definition at line 1524 of file ABISysV_arm.cpp.
References lldb_private::ArchSpec::eARM_abi_hard_float, and lldb_private::ArchSpec::GetFlags().
Referenced by GetReturnValueObjectImpl().
PrepareTrivialCall()
bool ABISysV_arm::PrepareTrivialCall (lldb_private::Thread & thread, lldb::addr_t sp, lldb::addr_t func_addr, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override virtual
Implements lldb_private::ABI.
Definition at line 1319 of file ABISysV_arm.cpp.
References lldb_private::RegisterInfo::byte_size, lldb_private::RegisterContext::ConvertRegisterKindToRegisterNumber(), lldb::eRegisterKindGeneric, lldb_private::Address::GetCallableLoadAddress(), lldb_private::RegisterContext::GetRegisterInfo(), LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_ARG2, LLDB_REGNUM_GENERIC_ARG3, LLDB_REGNUM_GENERIC_ARG4, LLDB_REGNUM_GENERIC_FLAGS, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_RA, LLDB_REGNUM_GENERIC_SP, MASK_CPSR_IT_MASK, MASK_CPSR_T, lldb_private::RegisterContext::ReadRegisterAsUnsigned(), lldb_private::Address::SetLoadAddress(), lldb_private::RegisterValue::SetUInt32(), sp, lldb_private::RegisterContext::WriteRegister(), and lldb_private::RegisterContext::WriteRegisterFromUnsigned().
RegisterIsVolatile()
bool ABISysV_arm::RegisterIsVolatile (const lldb_private::RegisterInfo * reg_info) override virtual
Implements lldb_private::ABI.
Definition at line 1956 of file ABISysV_arm.cpp.
References lldb_private::RegisterInfo::name.
SetReturnValueObject()
Status ABISysV_arm::SetReturnValueObject (lldb::StackFrameSP & frame_sp, lldb::ValueObjectSP & new_value) override virtual
Implements lldb_private::ABI.
Definition at line 1824 of file ABISysV_arm.cpp.
References lldb_private::Status::AsCString(), lldb::eRegisterKindGeneric, error(), lldb_private::Status::Fail(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataExtractor::GetMaxU32(), lldb_private::RegisterContext::GetRegisterInfo(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), lldb_private::CompilerType::IsPointerType(), LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_ARG2, and lldb_private::RegisterContext::WriteRegisterFromUnsigned().
Terminate()
void ABISysV_arm::Terminate () static
Definition at line 2114 of file ABISysV_arm.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Referenced by ABIARM::Terminate().
The documentation for this class was generated from the following files:
ABISysV_arm.h
ABISysV_arm.cpp