LLDB: lldb_private::FunctionCaller Class Reference
lldb_private::FunctionCaller Class Reference abstract
Encapsulates a function that can be called.
#include "lldb/Expression/FunctionCaller.h"
Public Member Functions
bool isA (const void *ClassID) const override
FunctionCaller (ExecutionContextScope &exe_scope, const CompilerType &return_type, const Address &function_address, const ValueList &arg_value_list, const char *name)
Constructor.
~FunctionCaller () override
Destructor.
virtual unsigned CompileFunction (lldb::ThreadSP thread_to_use_sp, DiagnosticManager &diagnostic_manager)=0
Compile the wrapper function.
bool InsertFunction (ExecutionContext &exe_ctx, lldb::addr_t &args_addr_ref, DiagnosticManager &diagnostic_manager)
Insert the default function wrapper and its default argument struct.
bool WriteFunctionWrapper (ExecutionContext &exe_ctx, DiagnosticManager &diagnostic_manager)
Insert the default function wrapper (using the JIT)
bool WriteFunctionArguments (ExecutionContext &exe_ctx, lldb::addr_t &args_addr_ref, DiagnosticManager &diagnostic_manager)
Insert the default function argument struct.
bool WriteFunctionArguments (ExecutionContext &exe_ctx, lldb::addr_t &args_addr_ref, ValueList &arg_values, DiagnosticManager &diagnostic_manager)
Insert an argument struct with a non-default function address and non- default argument values.
lldb::ExpressionResults ExecuteFunction (ExecutionContext &exe_ctx, lldb::addr_t *args_addr_ptr, const EvaluateExpressionOptions &options, DiagnosticManager &diagnostic_manager, Value &results)
Run the function this FunctionCaller was created with.
lldb::ThreadPlanSP GetThreadPlanToCallFunction (ExecutionContext &exe_ctx, lldb::addr_t args_addr, const EvaluateExpressionOptions &options, DiagnosticManager &diagnostic_manager)
Get a thread plan to run the function this FunctionCaller was created with.
bool FetchFunctionResults (ExecutionContext &exe_ctx, lldb::addr_t args_addr, Value &ret_value)
Get the result of the function from its struct.
void DeallocateFunctionResults (ExecutionContext &exe_ctx, lldb::addr_t args_addr)
Deallocate the arguments structure.
const char * Text () override
Interface for ClangExpression.
const char * FunctionName () override
Return the function name that should be used for executing the expression.
ExpressionVariableList * LocalVariables ()
Return the object that the parser should use when registering local variables.
bool NeedsValidation () override
Return true if validation code should be inserted into the expression.
bool NeedsVariableResolution () override
Return true if external variables in the expression should be resolved.
ValueList GetArgumentValues () const
Public Member Functions inherited from lldb_private::Expression
Expression (Target &target)
Expression (ExecutionContextScope &exe_scope)
virtual ~Expression ()=default
Destructor.
virtual SourceLanguage Language () const
Return the language that should be used when parsing.
virtual Materializer * GetMaterializer ()
Return the Materializer that the parser should use when registering external values.
virtual ResultType DesiredResultType () const
Return the desired result type of the function, or eResultTypeAny if indifferent.
virtual EvaluateExpressionOptions * GetOptions ()
lldb::addr_t StartAddress ()
Return the address of the function's JIT-compiled code, or LLDB_INVALID_ADDRESS if the function is not JIT compiled.
virtual void WillStartExecuting ()
Called to notify the expression that it is about to be executed.
virtual void DidFinishExecuting ()
Called to notify the expression that its execution has finished.
virtual ExpressionTypeSystemHelper * GetTypeSystemHelper ()
Static Public Member Functions
static bool classof (const Expression *obj)
Protected Attributes
std::shared_ptr< IRExecutionUnit > m_execution_unit_sp
std::unique_ptr< ExpressionParser > m_parser
The parser responsible for compiling the function.
lldb::ModuleWP m_jit_module_wp
std::string m_name
The name of this clang function - for debugging purposes.
Function * m_function_ptr
The function we're going to call.
Address m_function_addr
If we don't have the FunctionSP, we at least need the address & return type.
CompilerType m_function_return_type
The opaque clang qual type for the function return type.
std::string m_wrapper_function_name
The name of the wrapper function.
std::string m_wrapper_function_text
The contents of the wrapper function.
std::string m_wrapper_struct_name
The name of the struct that contains the target function address, arguments, and result.
std::list< lldb::addr_t > m_wrapper_args_addrs
The addresses of the arguments to the wrapper function.
bool m_struct_valid
True if the ASTStructExtractor has populated the variables below.
size_t m_struct_size
These values are populated by the ASTStructExtractor.
std::vector< uint64_t > m_member_offsets
The offset of each member in the struct, in bytes.
uint64_t m_return_size
The size of the result variable, in bytes.
uint64_t m_return_offset
The offset of the result variable in the struct, in bytes.
ValueList m_arg_values
The default values of the arguments.
bool m_compiled
True if the wrapper function has already been parsed.
bool m_JITted
True if the wrapper function has already been JIT-compiled.
Protected Attributes inherited from lldb_private::Expression
lldb::TargetWP m_target_wp
lldb::ProcessWP m_jit_process_wp
Expression's always have to have a target...
lldb::addr_t m_jit_start_addr
An expression might have a process, but it doesn't need to (e.g.
lldb::addr_t m_jit_end_addr
The address of the JITted function within the JIT allocation.
Static Private Attributes
static char ID
Additional Inherited Members
Public Types inherited from lldb_private::Expression
enum ResultType { eResultTypeAny , eResultTypeId }
Detailed Description
Encapsulates a function that can be called.
A given FunctionCaller object can handle a single function signature. Once constructed, it can set up any number of concurrent calls to functions with that signature.
It performs the call by synthesizing a structure that contains the pointer to the function and the arguments that should be passed to that function, and producing a special-purpose JIT-compiled function that accepts a void* pointing to this struct as its only argument and calls the function in the struct with the written arguments. This method lets Clang handle the vagaries of function calling conventions.
The simplest use of the FunctionCaller is to construct it with a function representative of the signature you want to use, then call ExecuteFunction(ExecutionContext &, Stream &, Value &).
If you need to reuse the arguments for several calls, you can call InsertFunction() followed by WriteFunctionArguments(), which will return the location of the args struct for the wrapper function in args_addr_ref.
If you need to call the function on the thread plan stack, you can also call InsertFunction() followed by GetThreadPlanToCallFunction().
Any of the methods that take arg_addr_ptr or arg_addr_ref can be passed a pointer set to LLDB_INVALID_ADDRESS and new structure will be allocated and its address returned in that variable.
Any of the methods that take arg_addr_ptr can be passed nullptr, and the argument space will be managed for you.
Definition at line 56 of file FunctionCaller.h.
Constructor & Destructor Documentation
FunctionCaller()
FunctionCaller::FunctionCaller (ExecutionContextScope & exe_scope, const CompilerType & return_type, const Address & function_address, const ValueList & arg_value_list, const char * name)
Constructor.
Parameters
[in] exe_scope An execution context scope that gets us at least a target and process.
[in] return_type An opaque Clang QualType for the function result. Should be defined in ast_context.
[in] function_address The address of the function to call.
[in] arg_value_list The default values to use when calling this function. Can be overridden using WriteFunctionArguments().
Definition at line 37 of file FunctionCaller.cpp.
References lldb_private::ExecutionContextScope::CalculateProcess(), lldb_private::Expression::Expression(), m_arg_values, m_compiled, m_execution_unit_sp, m_function_addr, m_function_ptr, m_function_return_type, m_jit_module_wp, lldb_private::Expression::m_jit_process_wp, m_JITted, m_name, m_parser, m_return_offset, m_return_size, m_struct_size, m_struct_valid, m_wrapper_args_addrs, m_wrapper_function_name, and m_wrapper_struct_name.
Referenced by lldb_private::ClangFunctionCaller::ClangFunctionCaller().
~FunctionCaller()
FunctionCaller::~FunctionCaller () override
Destructor.
Definition at line 57 of file FunctionCaller.cpp.
References m_jit_module_wp, and lldb_private::Expression::m_jit_process_wp.
Member Function Documentation
classof()
bool lldb_private::FunctionCaller::classof (const Expression * obj) inline static
Definition at line 62 of file FunctionCaller.h.
References lldb_private::Expression::Expression(), ID, and lldb_private::Expression::isA().
CompileFunction()
virtual unsigned lldb_private::FunctionCaller::CompileFunction (lldb::ThreadSP thread_to_use_sp, DiagnosticManager & diagnostic_manager) pure virtual
Compile the wrapper function.
Parameters
[in] thread_to_use_sp Compilation might end up calling functions. Pass in the thread you want the compilation to use. If you pass in an empty ThreadSP it will use the currently selected thread.
[in] diagnostic_manager The diagnostic manager to report parser errors to.
Returns
The number of errors.
Implemented in lldb_private::ClangFunctionCaller.
Referenced by ExecuteFunction(), and InsertFunction().
DeallocateFunctionResults()
void FunctionCaller::DeallocateFunctionResults (ExecutionContext & exe_ctx, lldb::addr_t args_addr)
Deallocate the arguments structure.
Parameters
[in] exe_ctx The execution context to insert the function and its arguments into.
[in] args_addr The address of the argument struct.
Definition at line 323 of file FunctionCaller.cpp.
References lldb_private::Process::DeallocateMemory(), lldb_private::ExecutionContext::GetProcessRef(), and m_wrapper_args_addrs.
Referenced by lldb_private::PlatformWindows::DoLoadImage(), and ExecuteFunction().
ExecuteFunction()
lldb::ExpressionResults FunctionCaller::ExecuteFunction (ExecutionContext & exe_ctx, lldb::addr_t * args_addr_ptr, const EvaluateExpressionOptions & options, DiagnosticManager & diagnostic_manager, Value & results)
Run the function this FunctionCaller was created with.
This is the full version.
Parameters
[in] exe_ctx The thread & process in which this function will run.
[in] args_addr_ptr If nullptr, the function will take care of allocating & deallocating the wrapper args structure. Otherwise, if set to LLDB_INVALID_ADDRESS, a new structure will be allocated, filled and the address returned to you. You are responsible for deallocating it. And if passed in with a value other than LLDB_INVALID_ADDRESS, this should point to an already allocated structure with the values already written.
[in] diagnostic_manager The diagnostic manager to report errors to.
[in] options The options for this expression execution.
[out] results The result value will be put here after running the function.
Returns
Returns one of the ExpressionResults enum indicating function call status.
Definition at line 333 of file FunctionCaller.cpp.
References CompileFunction(), DeallocateFunctionResults(), lldb::eExpressionCompleted, lldb::eExpressionSetupError, lldb_private::Expressions, FetchFunctionResults(), FunctionName(), lldb_private::Target::GetDebugger(), lldb_private::TargetProperties::GetDebugUtilityExpression(), lldb_private::GetLog(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::ExecutionContext::GetProcessRef(), lldb_private::ExecutionContext::GetTargetPtr(), GetThreadPlanToCallFunction(), lldb_private::ExecutionContext::GetThreadSP(), InsertFunction(), LLDB_INVALID_ADDRESS, LLDB_LOGF, m_name, lldb_private::Process::RunThreadPlan(), lldb_private::EvaluateExpressionOptions::SetDebug(), lldb_private::EvaluateExpressionOptions::SetGenerateDebugInfo(), lldb_private::EvaluateExpressionOptions::SetIgnoreBreakpoints(), lldb_private::Process::SetRunningUserExpression(), lldb_private::EvaluateExpressionOptions::SetUnwindOnError(), lldb_private::Step, and lldb_private::toString().
Referenced by lldb_private::PlatformWindows::DoLoadImage(), lldb_private::AppleGetQueuesHandler::GetCurrentQueues(), lldb_private::ItaniumABILanguageRuntime::GetExceptionObjectForThread(), lldb_private::AppleGetItemInfoHandler::GetItemInfo(), lldb_private::AppleGetPendingItemsHandler::GetPendingItems(), and lldb_private::AppleGetThreadItemInfoHandler::GetThreadItemInfo().
FetchFunctionResults()
bool FunctionCaller::FetchFunctionResults (ExecutionContext & exe_ctx, lldb::addr_t args_addr, Value & ret_value)
Get the result of the function from its struct.
Parameters
[in] exe_ctx The execution context to retrieve the result from.
[in] args_addr The address of the argument struct.
[out] ret_value The value returned by the function.
Returns
True on success; false otherwise.
Definition at line 284 of file FunctionCaller.cpp.
References error(), lldb_private::Expressions, lldb_private::GetLog(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::Value::GetScalar(), LLDB_LOGF, m_function_return_type, lldb_private::Expression::m_jit_process_wp, m_name, m_return_offset, m_return_size, lldb_private::Process::ReadUnsignedIntegerFromMemory(), lldb_private::Value::Scalar, lldb_private::Value::SetCompilerType(), lldb_private::Value::SetValueType(), and lldb_private::Step.
Referenced by ExecuteFunction().
FunctionName()
const char * lldb_private::FunctionCaller::FunctionName () inline override virtual
Return the function name that should be used for executing the expression.
Text() should contain the definition of this function.
Implements lldb_private::Expression.
Definition at line 272 of file FunctionCaller.h.
References m_wrapper_function_name.
Referenced by ExecuteFunction(), and WriteFunctionWrapper().
GetArgumentValues()
ValueList lldb_private::FunctionCaller::GetArgumentValues () const inline
Definition at line 286 of file FunctionCaller.h.
References m_arg_values.
Referenced by lldb_private::PlatformWindows::DoLoadImage().
GetThreadPlanToCallFunction()
lldb::ThreadPlanSP FunctionCaller::GetThreadPlanToCallFunction (ExecutionContext & exe_ctx, lldb::addr_t args_addr, const EvaluateExpressionOptions & options, DiagnosticManager & diagnostic_manager)
Get a thread plan to run the function this FunctionCaller was created with.
Parameters
[in] exe_ctx The execution context to insert the function and its arguments into.
[in] args_addr The address of the argument struct.
[in] diagnostic_manager The diagnostic manager to report errors to.
Returns
A ThreadPlan shared pointer for executing the function.
Definition at line 252 of file FunctionCaller.cpp.
References lldb::eSeverityError, lldb_private::Expressions, lldb_private::GetLog(), lldb_private::ExecutionContext::GetThreadPtr(), LLDB_LOGF, lldb_private::Expression::m_jit_start_addr, m_name, lldb_private::DiagnosticManager::PutString(), and lldb_private::Step.
Referenced by ExecuteFunction().
InsertFunction()
bool FunctionCaller::InsertFunction (ExecutionContext & exe_ctx, lldb::addr_t & args_addr_ref, DiagnosticManager & diagnostic_manager)
Insert the default function wrapper and its default argument struct.
Parameters
[in] exe_ctx The execution context to insert the function and its arguments into.
[in,out] args_addr_ref The address of the structure to write the arguments into. May be LLDB_INVALID_ADDRESS; if it is, a new structure is allocated and args_addr_ref is pointed to it.
[in] diagnostic_manager The diagnostic manager to report errors to.
Returns
True on success; false otherwise.
Definition at line 224 of file FunctionCaller.cpp.
References CompileFunction(), lldb::eSeverityError, lldb::eStateStopped, lldb_private::GetLog(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::Process::GetState(), lldb_private::ExecutionContext::GetThreadSP(), LLDB_LOGF, lldb_private::Expression::m_jit_start_addr, lldb_private::DiagnosticManager::PutString(), lldb_private::Step, WriteFunctionArguments(), and WriteFunctionWrapper().
Referenced by ExecuteFunction().
isA()
bool lldb_private::FunctionCaller::isA (const void * ClassID) const inline override virtual
Implements lldb_private::Expression.
Definition at line 61 of file FunctionCaller.h.
References ID.
Referenced by lldb_private::ClangFunctionCaller::isA().
LocalVariables()
ExpressionVariableList * lldb_private::FunctionCaller::LocalVariables () inline
Return the object that the parser should use when registering local variables.
May be nullptr if the Expression doesn't care.
Definition at line 278 of file FunctionCaller.h.
NeedsValidation()
bool lldb_private::FunctionCaller::NeedsValidation () inline override virtual
Return true if validation code should be inserted into the expression.
Implements lldb_private::Expression.
Definition at line 281 of file FunctionCaller.h.
NeedsVariableResolution()
bool lldb_private::FunctionCaller::NeedsVariableResolution () inline override virtual
Return true if external variables in the expression should be resolved.
Implements lldb_private::Expression.
Definition at line 284 of file FunctionCaller.h.
Text()
const char * lldb_private::FunctionCaller::Text () inline override virtual
Interface for ClangExpression.
Return the string that the parser should parse. Must be a full translation unit.
Implements lldb_private::Expression.
Definition at line 268 of file FunctionCaller.h.
References m_wrapper_function_text.
WriteFunctionArguments() [1/2]
bool FunctionCaller::WriteFunctionArguments (ExecutionContext & exe_ctx, lldb::addr_t & args_addr_ref, DiagnosticManager & diagnostic_manager)
Insert the default function argument struct.
Parameters
[in] exe_ctx The execution context to insert the function and its arguments into.
[in,out] args_addr_ref The address of the structure to write the arguments into. May be LLDB_INVALID_ADDRESS; if it is, a new structure is allocated and args_addr_ref is pointed to it.
[in] diagnostic_manager The diagnostic manager to report errors to.
Returns
True on success; false otherwise.
Definition at line 130 of file FunctionCaller.cpp.
References m_arg_values, and WriteFunctionArguments().
Referenced by lldb_private::PlatformWindows::DoLoadImage(), InsertFunction(), lldb_private::AppleObjCTrampolineHandler::SetupDispatchFunction(), lldb_private::AppleGetItemInfoHandler::SetupGetItemInfoFunction(), lldb_private::AppleGetPendingItemsHandler::SetupGetPendingItemsFunction(), lldb_private::AppleGetQueuesHandler::SetupGetQueuesFunction(), lldb_private::AppleGetThreadItemInfoHandler::SetupGetThreadItemInfoFunction(), and WriteFunctionArguments().
WriteFunctionArguments() [2/2]
bool FunctionCaller::WriteFunctionArguments (ExecutionContext & exe_ctx, lldb::addr_t & args_addr_ref, ValueList & arg_values, DiagnosticManager & diagnostic_manager)
Insert an argument struct with a non-default function address and non- default argument values.
Parameters
[in] exe_ctx The execution context to insert the function and its arguments into.
[in,out] args_addr_ref The address of the structure to write the arguments into. May be LLDB_INVALID_ADDRESS; if it is, a new structure is allocated and args_addr_ref is pointed at it.
[in] arg_values The values of the function's arguments.
[in] diagnostic_manager The diagnostic manager to report errors to.
Returns
True on success; false otherwise.
Definition at line 140 of file FunctionCaller.cpp.
References lldb_private::Process::AllocateMemory(), lldb::eExpressionSetupError, error(), lldb::eSeverityError, lldb_private::Process::GetAddressByteSize(), lldb_private::Scalar::GetByteSize(), lldb_private::Value::GetCompilerType(), lldb_private::Value::GetContextType(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::ValueList::GetSize(), lldb_private::ExecutionContext::GetTargetPtr(), lldb_private::ValueList::GetValueAtIndex(), lldb_private::Value::GetValueType(), lldb_private::Value::HostAddress, lldb_private::Value::Invalid, lldb_private::CompilerType::IsPointerType(), LLDB_INVALID_ADDRESS, m_arg_values, m_function_addr, lldb_private::Expression::m_jit_process_wp, m_member_offsets, m_struct_size, m_struct_valid, m_wrapper_args_addrs, lldb_private::DiagnosticManager::Printf(), lldb_private::DiagnosticManager::PutString(), lldb_private::Value::ResolveValue(), and lldb_private::Process::WriteScalarToMemory().
WriteFunctionWrapper()
bool FunctionCaller::WriteFunctionWrapper (ExecutionContext & exe_ctx, DiagnosticManager & diagnostic_manager)
Insert the default function wrapper (using the JIT)
Parameters
[in] exe_ctx The execution context to insert the function and its arguments into.
[in] diagnostic_manager The diagnostic manager to report errors to.
Returns
True on success; false otherwise.
Definition at line 66 of file FunctionCaller.cpp.
References lldb_private::ModuleList::Append(), lldb_private::Status::AsCString(), lldb_private::eExecutionPolicyAlways, lldb::eSeverityError, lldb::eStateStopped, FunctionName(), lldb_private::Target::GetImages(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::Process::GetState(), lldb_private::Process::GetTarget(), m_compiled, m_execution_unit_sp, lldb_private::Expression::m_jit_end_addr, m_jit_module_wp, lldb_private::Expression::m_jit_process_wp, lldb_private::Expression::m_jit_start_addr, m_JITted, m_parser, lldb_private::DiagnosticManager::Printf(), lldb_private::FileSpec::SetFilename(), and lldb_private::Status::Success().
Referenced by InsertFunction().
Member Data Documentation
ID
char FunctionCaller::ID static private
Definition at line 58 of file FunctionCaller.h.
Referenced by classof(), and isA().
m_arg_values
ValueList lldb_private::FunctionCaller::m_arg_values protected
The default values of the arguments.
Definition at line 330 of file FunctionCaller.h.
Referenced by lldb_private::ClangFunctionCaller::CompileFunction(), FunctionCaller(), GetArgumentValues(), WriteFunctionArguments(), and WriteFunctionArguments().
m_compiled
bool lldb_private::FunctionCaller::m_compiled protected
True if the wrapper function has already been parsed.
Definition at line 332 of file FunctionCaller.h.
Referenced by lldb_private::ClangFunctionCaller::CompileFunction(), FunctionCaller(), and WriteFunctionWrapper().
m_execution_unit_sp
std::shared_ptr<IRExecutionUnit> lldb_private::FunctionCaller::m_execution_unit_sp protected
Definition at line 291 of file FunctionCaller.h.
Referenced by FunctionCaller(), and WriteFunctionWrapper().
m_function_addr
Address lldb_private::FunctionCaller::m_function_addr protected
If we don't have the FunctionSP, we at least need the address & return type.
Definition at line 304 of file FunctionCaller.h.
Referenced by FunctionCaller(), and WriteFunctionArguments().
m_function_ptr
Function* lldb_private::FunctionCaller::m_function_ptr protected
The function we're going to call.
May be nullptr if we don't have debug info for the function.
Definition at line 301 of file FunctionCaller.h.
Referenced by lldb_private::ClangFunctionCaller::CompileFunction(), and FunctionCaller().
m_function_return_type
CompilerType lldb_private::FunctionCaller::m_function_return_type protected
The opaque clang qual type for the function return type.
Definition at line 306 of file FunctionCaller.h.
Referenced by lldb_private::ClangFunctionCaller::CompileFunction(), FetchFunctionResults(), and FunctionCaller().
m_jit_module_wp
lldb::ModuleWP lldb_private::FunctionCaller::m_jit_module_wp protected
Definition at line 297 of file FunctionCaller.h.
Referenced by FunctionCaller(), WriteFunctionWrapper(), and ~FunctionCaller().
m_JITted
bool lldb_private::FunctionCaller::m_JITted protected
True if the wrapper function has already been JIT-compiled.
Definition at line 334 of file FunctionCaller.h.
Referenced by FunctionCaller(), and WriteFunctionWrapper().
m_member_offsets
std::vector<uint64_t> lldb_private::FunctionCaller::m_member_offsets protected
The offset of each member in the struct, in bytes.
Definition at line 325 of file FunctionCaller.h.
Referenced by WriteFunctionArguments().
m_name
std::string lldb_private::FunctionCaller::m_name protected
The name of this clang function - for debugging purposes.
Definition at line 299 of file FunctionCaller.h.
Referenced by ExecuteFunction(), FetchFunctionResults(), FunctionCaller(), and GetThreadPlanToCallFunction().
m_parser
std::unique_ptr<ExpressionParser> lldb_private::FunctionCaller::m_parser protected
The parser responsible for compiling the function.
This will get made in CompileFunction, so it is safe to access it after that.
Definition at line 293 of file FunctionCaller.h.
Referenced by lldb_private::ClangFunctionCaller::CompileFunction(), FunctionCaller(), and WriteFunctionWrapper().
m_return_offset
uint64_t lldb_private::FunctionCaller::m_return_offset protected
The offset of the result variable in the struct, in bytes.
Definition at line 327 of file FunctionCaller.h.
Referenced by FetchFunctionResults(), and FunctionCaller().
m_return_size
uint64_t lldb_private::FunctionCaller::m_return_size protected
The size of the result variable, in bytes.
Definition at line 326 of file FunctionCaller.h.
Referenced by FetchFunctionResults(), and FunctionCaller().
m_struct_size
size_t lldb_private::FunctionCaller::m_struct_size protected
These values are populated by the ASTStructExtractor.
The size of the argument struct, in bytes.
Definition at line 323 of file FunctionCaller.h.
Referenced by FunctionCaller(), and WriteFunctionArguments().
m_struct_valid
bool lldb_private::FunctionCaller::m_struct_valid protected
True if the ASTStructExtractor has populated the variables below.
Definition at line 319 of file FunctionCaller.h.
Referenced by FunctionCaller(), and WriteFunctionArguments().
m_wrapper_args_addrs
std::list<lldb::addr_t> lldb_private::FunctionCaller::m_wrapper_args_addrs protected
The addresses of the arguments to the wrapper function.
Definition at line 315 of file FunctionCaller.h.
Referenced by DeallocateFunctionResults(), FunctionCaller(), and WriteFunctionArguments().
m_wrapper_function_name
std::string lldb_private::FunctionCaller::m_wrapper_function_name protected
The name of the wrapper function.
Definition at line 309 of file FunctionCaller.h.
Referenced by lldb_private::ClangFunctionCaller::CompileFunction(), FunctionCaller(), and FunctionName().
m_wrapper_function_text
std::string lldb_private::FunctionCaller::m_wrapper_function_text protected
The contents of the wrapper function.
Definition at line 311 of file FunctionCaller.h.
Referenced by lldb_private::ClangFunctionCaller::CompileFunction(), and Text().
m_wrapper_struct_name
std::string lldb_private::FunctionCaller::m_wrapper_struct_name protected
The name of the struct that contains the target function address, arguments, and result.
Definition at line 312 of file FunctionCaller.h.
Referenced by lldb_private::ClangFunctionCaller::CompileFunction(), FunctionCaller(), and lldb_private::ClangFunctionCaller::GetWrapperStructName().
The documentation for this class was generated from the following files:
FunctionCaller.h
FunctionCaller.cpp