LLDB: lldb_private::FileAction Class Reference
lldb_private::FileAction Class Reference
#include <FileAction.h>
Public Types
enum Action { eFileActionNone , eFileActionClose , eFileActionDuplicate , eFileActionOpen }
Public Member Functions
FileAction ()
void Clear ()
bool Close (int fd)
bool Duplicate (int fd, int dup_fd)
bool Open (int fd, const FileSpec &file_spec, bool read, bool write)
int GetFD () const
Action GetAction () const
int GetActionArgument () const
const FileSpec & GetFileSpec () const
void Dump (Stream &stream) const
Protected Attributes
Action m_action = eFileActionNone
int m_fd = -1
int m_arg = -1
FileSpec m_file_spec
Detailed Description
Definition at line 17 of file FileAction.h.
Member Enumeration Documentation
Action
enum lldb_private::FileAction::Action
Enumerator
eFileActionNone
eFileActionClose
eFileActionDuplicate
eFileActionOpen
Definition at line 19 of file FileAction.h.
Constructor & Destructor Documentation
FileAction()
FileAction::FileAction ()
Definition at line 19 of file FileAction.cpp.
References m_file_spec.
Member Function Documentation
Clear()
void FileAction::Clear ()
Definition at line 21 of file FileAction.cpp.
References eFileActionNone, m_action, m_arg, m_fd, and m_file_spec.
Referenced by Close(), Duplicate(), and Open().
Close()
bool FileAction::Close (int fd)
Definition at line 49 of file FileAction.cpp.
References Clear(), eFileActionClose, m_action, and m_fd.
Referenced by lldb_private::ProcessLaunchInfo::AppendCloseFileAction().
Dump()
void FileAction::Dump (Stream & stream) const
Definition at line 68 of file FileAction.cpp.
References eFileActionClose, eFileActionDuplicate, eFileActionNone, eFileActionOpen, m_action, m_arg, m_fd, m_file_spec, lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
Referenced by PlatformPOSIX::DebugProcess().
Duplicate()
bool FileAction::Duplicate (int fd, int dup_fd)
Definition at line 58 of file FileAction.cpp.
References Clear(), eFileActionDuplicate, m_action, m_arg, and m_fd.
Referenced by lldb_private::ProcessLaunchInfo::AppendDuplicateFileAction().
GetAction()
Action lldb_private::FileAction::GetAction () const inline
Definition at line 38 of file FileAction.h.
References m_action.
Referenced by AddPosixSpawnFileAction(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoLaunch(), lldb_private::ProcessLauncherWindows::GetInheritedHandles(), and HandleFileAction().
GetActionArgument()
int lldb_private::FileAction::GetActionArgument () const inline
Definition at line 40 of file FileAction.h.
References m_arg.
Referenced by AddPosixSpawnFileAction(), lldb_private::ProcessLauncherWindows::GetInheritedHandles(), and HandleFileAction().
GetFD()
int lldb_private::FileAction::GetFD () const inline
Definition at line 36 of file FileAction.h.
References m_fd.
Referenced by AddPosixSpawnFileAction(), and lldb_private::ProcessLauncherWindows::GetInheritedHandles().
GetFileSpec()
const FileSpec & FileAction::GetFileSpec () const
Definition at line 28 of file FileAction.cpp.
References m_file_spec.
Referenced by AddPosixSpawnFileAction(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoLaunch(), lldb_private::ProcessLauncherWindows::GetStdioHandle(), HandleFileAction(), LaunchProcessXPC(), and lldb_private::TargetProperties::SetProcessLaunchInfo().
Open()
bool FileAction::Open (int fd, const FileSpec & file_spec, bool read, bool write)
Definition at line 30 of file FileAction.cpp.
References Clear(), eFileActionOpen, m_action, m_arg, m_fd, m_file_spec, and O_NOCTTY.
Referenced by lldb_private::ProcessLaunchInfo::AppendOpenFileAction(), lldb_private::ProcessLaunchInfo::AppendSuppressFileAction(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_QSetSTDERR(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_QSetSTDIN(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_QSetSTDOUT(), lldb_private::ProcessLaunchInfo::ProcessLaunchInfo(), and lldb_private::CommandOptionsProcessLaunch::SetOptionValue().
Member Data Documentation
m_action
Action lldb_private::FileAction::m_action = eFileActionNone protected
Definition at line 47 of file FileAction.h.
Referenced by Clear(), Close(), Dump(), Duplicate(), GetAction(), and Open().
m_arg
int lldb_private::FileAction::m_arg = -1 protected
Definition at line 49 of file FileAction.h.
Referenced by Clear(), Dump(), Duplicate(), GetActionArgument(), and Open().
m_fd
int lldb_private::FileAction::m_fd = -1 protected
Definition at line 48 of file FileAction.h.
Referenced by Clear(), Close(), Dump(), Duplicate(), GetFD(), and Open().
m_file_spec
FileSpec lldb_private::FileAction::m_file_spec protected
Definition at line 51 of file FileAction.h.
Referenced by Clear(), Dump(), FileAction(), GetFileSpec(), and Open().
The documentation for this class was generated from the following files:
FileAction.h
FileAction.cpp