LLDB: lldb_private::OptionValue Class Reference
lldb_private::OptionValue Class Reference abstract
#include <OptionValue.h>
Classes
class DefaultValueFormat
Public Types
enum Type {
eTypeInvalid = 0 , eTypeArch , eTypeArgs , eTypeArray ,
eTypeBoolean , eTypeChar , eTypeDictionary , eTypeEnum ,
eTypeFileLineColumn , eTypeFileSpec , eTypeFileSpecList , eTypeFormat ,
eTypeLanguage , eTypePathMap , eTypeProperties , eTypeRegex ,
eTypeSInt64 , eTypeString , eTypeUInt64 , eTypeUUID ,
eTypeFormatEntity
}
enum {
eDumpOptionName = (1u << 0) , eDumpOptionType = (1u << 1) , eDumpOptionValue = (1u << 2) , eDumpOptionDescription = (1u << 3) ,
eDumpOptionRaw = (1u << 4) , eDumpOptionCommand = (1u << 5) , eDumpOptionDefaultValue = (1u << 6) , eDumpGroupValue = (eDumpOptionName | eDumpOptionType | eDumpOptionValue) ,
eDumpGroupHelp , eDumpGroupExport = (eDumpOptionCommand | eDumpOptionName | eDumpOptionValue)
}
Public Member Functions
OptionValue ()=default
virtual ~OptionValue ()=default
OptionValue (const OptionValue &other)
OptionValue & operator= (const OptionValue &other)
virtual Type GetType () const =0
virtual bool ValueIsTransparent () const
virtual const char * GetTypeAsCString () const
virtual void DumpValue (const ExecutionContext *exe_ctx, Stream &strm, uint32_t dump_mask)=0
virtual llvm::json::Value ToJSON (const ExecutionContext *exe_ctx) const =0
virtual Status SetValueFromString (llvm::StringRef value, VarSetOperationType op=eVarSetOperationAssign)
virtual void Clear ()=0
virtual lldb::OptionValueSP DeepCopy (const lldb::OptionValueSP &new_parent) const
virtual void AutoComplete (CommandInterpreter &interpreter, CompletionRequest &request)
virtual lldb::OptionValueSP GetSubValue (const ExecutionContext *exe_ctx, llvm::StringRef name, Status &error) const
virtual Status SetSubValue (const ExecutionContext *exe_ctx, VarSetOperationType op, llvm::StringRef name, llvm::StringRef value)
virtual bool IsAggregateValue () const
virtual llvm::StringRef GetName () const
virtual bool DumpQualifiedName (Stream &strm) const
uint32_t GetTypeAsMask ()
OptionValueArch * GetAsArch ()
const OptionValueArch * GetAsArch () const
OptionValueArray * GetAsArray ()
const OptionValueArray * GetAsArray () const
OptionValueArgs * GetAsArgs ()
const OptionValueArgs * GetAsArgs () const
OptionValueBoolean * GetAsBoolean ()
const OptionValueBoolean * GetAsBoolean () const
OptionValueChar * GetAsChar ()
const OptionValueChar * GetAsChar () const
OptionValueDictionary * GetAsDictionary ()
const OptionValueDictionary * GetAsDictionary () const
OptionValueEnumeration * GetAsEnumeration ()
const OptionValueEnumeration * GetAsEnumeration () const
OptionValueFileSpec * GetAsFileSpec ()
const OptionValueFileSpec * GetAsFileSpec () const
OptionValueFileSpecList * GetAsFileSpecList ()
const OptionValueFileSpecList * GetAsFileSpecList () const
OptionValueFormat * GetAsFormat ()
const OptionValueFormat * GetAsFormat () const
OptionValueLanguage * GetAsLanguage ()
const OptionValueLanguage * GetAsLanguage () const
OptionValuePathMappings * GetAsPathMappings ()
const OptionValuePathMappings * GetAsPathMappings () const
OptionValueProperties * GetAsProperties ()
const OptionValueProperties * GetAsProperties () const
OptionValueRegex * GetAsRegex ()
const OptionValueRegex * GetAsRegex () const
OptionValueSInt64 * GetAsSInt64 ()
const OptionValueSInt64 * GetAsSInt64 () const
OptionValueString * GetAsString ()
const OptionValueString * GetAsString () const
OptionValueUInt64 * GetAsUInt64 ()
const OptionValueUInt64 * GetAsUInt64 () const
OptionValueUUID * GetAsUUID ()
const OptionValueUUID * GetAsUUID () const
OptionValueFormatEntity * GetAsFormatEntity ()
const OptionValueFormatEntity * GetAsFormatEntity () const
bool AppendFileSpecValue (FileSpec file_spec)
bool OptionWasSet () const
void SetOptionWasSet ()
void SetParent (const lldb::OptionValueSP &parent_sp)
lldb::OptionValueSP GetParent () const
void SetValueChangedCallback (std::function< void()> callback)
void NotifyValueChanged ()
template<typename T, std::enable_if_t<!std::is_pointer_v< T >, bool > = true>
std::optional< T > GetValueAs () const
template<typename T, typename U = typename std::remove_const< typename std::remove_pointer<T>::type>::type, std::enable_if_t< std::is_pointer_v< T >, bool > = true>
T GetValueAs () const
bool SetValueAs (bool v)
bool SetValueAs (char v)
bool SetValueAs (uint64_t v)
bool SetValueAs (int64_t v)
bool SetValueAs (UUID v)
bool SetValueAs (llvm::StringRef v)
bool SetValueAs (lldb::LanguageType v)
bool SetValueAs (lldb::Format v)
bool SetValueAs (FileSpec v)
bool SetValueAs (ArchSpec v)
bool SetValueAs (const FormatEntity::Entry &v)
template<typename T, std::enable_if_t< std::is_enum_v< T >, bool > = true>
bool SetValueAs (T t)
Static Public Member Functions
static const char * GetBuiltinTypeAsCString (Type t)
static uint32_t ConvertTypeToMask (OptionValue::Type type)
static OptionValue::Type ConvertTypeMaskToType (uint32_t type_mask)
static lldb::OptionValueSP CreateValueFromCStringForTypeMask (const char *value_cstr, uint32_t type_mask, Status &error)
Protected Types
using TopmostBase = OptionValue
Protected Member Functions
virtual lldb::OptionValueSP Clone () const =0
Protected Attributes
lldb::OptionValueWP m_parent_wp
std::function< void()> m_callback
bool m_value_was_set = false
Private Member Functions
std::optional< ArchSpec > GetArchSpecValue () const
bool SetArchSpecValue (ArchSpec arch_spec)
std::optional< bool > GetBooleanValue () const
bool SetBooleanValue (bool new_value)
std::optional< char > GetCharValue () const
bool SetCharValue (char new_value)
std::optional< int64_t > GetEnumerationValue () const
bool SetEnumerationValue (int64_t value)
std::optional< FileSpec > GetFileSpecValue () const
bool SetFileSpecValue (FileSpec file_spec)
std::optional< FileSpecList > GetFileSpecListValue () const
std::optional< int64_t > GetSInt64Value () const
bool SetSInt64Value (int64_t new_value)
std::optional< uint64_t > GetUInt64Value () const
bool SetUInt64Value (uint64_t new_value)
std::optional< lldb::Format > GetFormatValue () const
bool SetFormatValue (lldb::Format new_value)
std::optional< lldb::LanguageType > GetLanguageValue () const
bool SetLanguageValue (lldb::LanguageType new_language)
std::optional< llvm::StringRef > GetStringValue () const
bool SetStringValue (llvm::StringRef new_value)
std::optional< UUID > GetUUIDValue () const
bool SetUUIDValue (const UUID &uuid)
FormatEntity::Entry GetFormatEntityValue () const
bool SetFormatEntityValue (const FormatEntity::Entry &entry)
const RegularExpression * GetRegexValue () const
Private Attributes
std::mutex m_mutex
Detailed Description
Definition at line 32 of file OptionValue.h.
Member Typedef Documentation
TopmostBase
using lldb_private::OptionValue::TopmostBase = OptionValue protected
Definition at line 337 of file OptionValue.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
eDumpOptionName
eDumpOptionType
eDumpOptionValue
eDumpOptionDescription
eDumpOptionRaw
eDumpOptionCommand
eDumpOptionDefaultValue
eDumpGroupValue
eDumpGroupHelp
eDumpGroupExport
Definition at line 58 of file OptionValue.h.
Type
enum lldb_private::OptionValue::Type
Enumerator
eTypeInvalid
eTypeArch
eTypeArgs
eTypeArray
eTypeBoolean
eTypeChar
eTypeDictionary
eTypeEnum
eTypeFileLineColumn
eTypeFileSpec
eTypeFileSpecList
eTypeFormat
eTypeLanguage
eTypePathMap
eTypeProperties
eTypeRegex
eTypeSInt64
eTypeString
eTypeUInt64
eTypeUUID
eTypeFormatEntity
Definition at line 34 of file OptionValue.h.
Constructor & Destructor Documentation
OptionValue() [1/2]
lldb_private::OptionValue::OptionValue () default
Referenced by operator=(), OptionValue(), and ~OptionValue().
~OptionValue()
virtual lldb_private::OptionValue::~OptionValue () virtual default
References OptionValue().
OptionValue() [2/2]
OptionValue::OptionValue (const OptionValue & other)
Definition at line 18 of file OptionValue.cpp.
References m_callback, m_mutex, m_parent_wp, m_value_was_set, and OptionValue().
Member Function Documentation
AppendFileSpecValue()
bool OptionValue::AppendFileSpecValue (FileSpec file_spec)
Definition at line 335 of file OptionValue.cpp.
References GetAsFileSpecList(), and m_mutex.
AutoComplete()
void OptionValue::AutoComplete (CommandInterpreter & interpreter, CompletionRequest & request) virtual
Reimplemented in lldb_private::OptionValueArch, lldb_private::OptionValueBoolean, lldb_private::OptionValueEnumeration, lldb_private::OptionValueFileColonLine, lldb_private::OptionValueFileSpec, lldb_private::OptionValueFormatEntity, and lldb_private::OptionValueUUID.
Definition at line 606 of file OptionValue.cpp.
Clear()
virtual void lldb_private::OptionValue::Clear () pure virtual
Implemented in lldb_private::OptionValueArch, lldb_private::OptionValueArray, lldb_private::OptionValueBoolean, lldb_private::OptionValueChar, lldb_private::OptionValueDictionary, lldb_private::OptionValueEnumeration, lldb_private::OptionValueFileColonLine, lldb_private::OptionValueFileSpec, lldb_private::OptionValueFileSpecList, lldb_private::OptionValueFormat, lldb_private::OptionValueFormatEntity, lldb_private::OptionValueLanguage, lldb_private::OptionValuePathMappings, lldb_private::OptionValueProperties, lldb_private::OptionValueRegex, lldb_private::OptionValueSInt64, lldb_private::OptionValueString, lldb_private::OptionValueUInt64, and lldb_private::OptionValueUUID.
Clone()
virtual lldb::OptionValueSP lldb_private::OptionValue::Clone () const protected pure virtual
Implemented in lldb_private::Cloneable< OptionValueArch, OptionValue >, lldb_private::Cloneable< OptionValueArgs, OptionValueArray >, lldb_private::Cloneable< OptionValueArray, OptionValue >, lldb_private::Cloneable< OptionValueBoolean, OptionValue >, lldb_private::Cloneable< OptionValueChar, OptionValue >, lldb_private::Cloneable< OptionValueDictionary, OptionValue >, lldb_private::Cloneable< OptionValueEnumeration, OptionValue >, lldb_private::Cloneable< OptionValueFileColonLine, OptionValue >, lldb_private::Cloneable< OptionValueFileSpec, OptionValue >, lldb_private::Cloneable< OptionValueFileSpecList, OptionValue >, lldb_private::Cloneable< OptionValueFormat, OptionValue >, lldb_private::Cloneable< OptionValueFormatEntity, OptionValue >, lldb_private::Cloneable< OptionValueLanguage, OptionValue >, lldb_private::Cloneable< OptionValuePathMappings, OptionValue >, lldb_private::Cloneable< OptionValueProperties, OptionValue >, lldb_private::Cloneable< OptionValueRegex, OptionValue >, lldb_private::Cloneable< OptionValueSInt64, OptionValue >, lldb_private::Cloneable< OptionValueString, OptionValue >, lldb_private::Cloneable< OptionValueUInt64, OptionValue >, lldb_private::Cloneable< OptionValueUUID, OptionValue >, lldb_private::Cloneable< ProcessExperimentalOptionValueProperties, OptionValueProperties >, lldb_private::Cloneable< ProcessOptionValueProperties, OptionValueProperties >, lldb_private::Cloneable< TargetExperimentalOptionValueProperties, OptionValueProperties >, lldb_private::Cloneable< TargetOptionValueProperties, OptionValueProperties >, lldb_private::Cloneable< ThreadOptionValueProperties, OptionValueProperties >, and lldb_private::OptionValueFileSpecList.
Referenced by DeepCopy().
ConvertTypeMaskToType()
OptionValue::Type lldb_private::OptionValue::ConvertTypeMaskToType (uint32_t type_mask) inline static
Definition at line 139 of file OptionValue.h.
References eTypeArch, eTypeArgs, eTypeArray, eTypeBoolean, eTypeChar, eTypeDictionary, eTypeEnum, eTypeFileLineColumn, eTypeFileSpec, eTypeFileSpecList, eTypeFormat, eTypeInvalid, eTypeLanguage, eTypePathMap, eTypeProperties, eTypeRegex, eTypeSInt64, eTypeString, eTypeUInt64, and eTypeUUID.
Referenced by lldb_private::OptionValueArray::DumpValue(), lldb_private::OptionValueDictionary::DumpValue(), and lldb_private::OptionValueDictionary::IsHomogenous().
ConvertTypeToMask()
uint32_t lldb_private::OptionValue::ConvertTypeToMask (OptionValue::Type type) inline static
Definition at line 135 of file OptionValue.h.
Referenced by lldb_private::OptionValueArgs::OptionValueArgs(), and lldb_private::Property::Property().
CreateValueFromCStringForTypeMask()
lldb::OptionValueSP OptionValue::CreateValueFromCStringForTypeMask (const char * value_cstr, uint32_t type_mask, Status & error) static
Definition at line 534 of file OptionValue.cpp.
References lldb::eFormatInvalid, lldb::eLanguageTypeUnknown, error(), eTypeArch, eTypeBoolean, eTypeChar, eTypeFileSpec, eTypeFormat, eTypeFormatEntity, eTypeLanguage, eTypeSInt64, eTypeString, eTypeUInt64, eTypeUUID, lldb_private::eVarSetOperationAssign, and lldb_private::Status::FromErrorString().
Referenced by lldb_private::OptionValueArray::SetArgs(), and lldb_private::OptionValueDictionary::SetArgs().
DeepCopy()
OptionValueSP OptionValue::DeepCopy (const lldb::OptionValueSP & new_parent) const virtual
Reimplemented in lldb_private::OptionValueArray, and lldb_private::OptionValueProperties.
Definition at line 600 of file OptionValue.cpp.
References Clone(), and lldb_private::clone().
Referenced by lldb_private::OptionValueArray::DeepCopy(), lldb_private::OptionValueDictionary::DeepCopy(), and lldb_private::OptionValueProperties::DeepCopy().
DumpQualifiedName()
bool OptionValue::DumpQualifiedName (Stream & strm) const virtual
Definition at line 582 of file OptionValue.cpp.
References GetName(), m_parent_wp, and lldb_private::Stream::PutChar().
DumpValue()
virtual void lldb_private::OptionValue::DumpValue (const ExecutionContext * exe_ctx, Stream & strm, uint32_t dump_mask) pure virtual
Implemented in lldb_private::OptionValueArch, lldb_private::OptionValueArray, lldb_private::OptionValueBoolean, lldb_private::OptionValueChar, lldb_private::OptionValueDictionary, lldb_private::OptionValueEnumeration, lldb_private::OptionValueFileColonLine, lldb_private::OptionValueFileSpec, lldb_private::OptionValueFileSpecList, lldb_private::OptionValueFormat, lldb_private::OptionValueFormatEntity, lldb_private::OptionValueLanguage, lldb_private::OptionValuePathMappings, lldb_private::OptionValueProperties, lldb_private::OptionValueRegex, lldb_private::OptionValueSInt64, lldb_private::OptionValueString, lldb_private::OptionValueUInt64, and lldb_private::OptionValueUUID.
Referenced by lldb_private::OptionValueDictionary::DumpValue().
GetArchSpecValue()
std::optional< ArchSpec > OptionValue::GetArchSpecValue () const private
Definition at line 461 of file OptionValue.cpp.
References GetAsArch(), and m_mutex.
Referenced by GetValueAs().
GetAsArch() [1/2]
OptionValueArch * OptionValue::GetAsArch ()
Definition at line 91 of file OptionValue.cpp.
References eTypeArch, and GetType().
Referenced by GetArchSpecValue(), and SetArchSpecValue().
GetAsArch() [2/2]
const OptionValueArch * OptionValue::GetAsArch () const
Definition at line 97 of file OptionValue.cpp.
References eTypeArch, and GetType().
GetAsArgs() [1/2]
OptionValueArgs * OptionValue::GetAsArgs ()
Definition at line 115 of file OptionValue.cpp.
References eTypeArgs, and GetType().
Referenced by lldb_private::OptionValueProperties::GetPropertyAtIndexAsArgs(), and lldb_private::OptionValueProperties::SetPropertyAtIndexFromArgs().
GetAsArgs() [2/2]
const OptionValueArgs * OptionValue::GetAsArgs () const
Definition at line 121 of file OptionValue.cpp.
References eTypeArgs, and GetType().
GetAsArray() [1/2]
OptionValueArray * OptionValue::GetAsArray ()
Definition at line 103 of file OptionValue.cpp.
References eTypeArray, and GetType().
Referenced by lldb_private::OptionValueProperties::GetPropertyAtIndexAsArgs(), and lldb_private::OptionValueProperties::SetPropertyAtIndexFromArgs().
GetAsArray() [2/2]
const OptionValueArray * OptionValue::GetAsArray () const
Definition at line 109 of file OptionValue.cpp.
References eTypeArray, and GetType().
GetAsBoolean() [1/2]
OptionValueBoolean * OptionValue::GetAsBoolean ()
Definition at line 43 of file OptionValue.cpp.
References eTypeBoolean, and GetType().
Referenced by GetBooleanValue(), and SetBooleanValue().
GetAsBoolean() [2/2]
const OptionValueBoolean * OptionValue::GetAsBoolean () const
Definition at line 49 of file OptionValue.cpp.
References eTypeBoolean, and GetType().
GetAsChar() [1/2]
OptionValueChar * OptionValue::GetAsChar ()
Definition at line 61 of file OptionValue.cpp.
References eTypeChar, and GetType().
Referenced by GetCharValue(), and SetCharValue().
GetAsChar() [2/2]
const OptionValueChar * OptionValue::GetAsChar () const
Definition at line 55 of file OptionValue.cpp.
References eTypeChar, and GetType().
GetAsDictionary() [1/2]
OptionValueDictionary * OptionValue::GetAsDictionary ()
Definition at line 127 of file OptionValue.cpp.
References eTypeDictionary, and GetType().
Referenced by lldb_private::OptionValueProperties::GetPropertyAtIndexAsArgs(), and lldb_private::OptionValueProperties::SetPropertyAtIndexFromArgs().
GetAsDictionary() [2/2]
const OptionValueDictionary * OptionValue::GetAsDictionary () const
Definition at line 133 of file OptionValue.cpp.
References eTypeDictionary, and GetType().
GetAsEnumeration() [1/2]
OptionValueEnumeration * OptionValue::GetAsEnumeration ()
Definition at line 139 of file OptionValue.cpp.
References eTypeEnum, and GetType().
Referenced by GetEnumerationValue(), and SetEnumerationValue().
GetAsEnumeration() [2/2]
const OptionValueEnumeration * OptionValue::GetAsEnumeration () const
Definition at line 145 of file OptionValue.cpp.
References eTypeEnum, and GetType().
GetAsFileSpec() [1/2]
OptionValueFileSpec * OptionValue::GetAsFileSpec ()
Definition at line 67 of file OptionValue.cpp.
References eTypeFileSpec, and GetType().
Referenced by GetFileSpecValue(), lldb_private::OptionValueProperties::GetPropertyAtIndexAsOptionValueFileSpec(), and SetFileSpecValue().
GetAsFileSpec() [2/2]
const OptionValueFileSpec * OptionValue::GetAsFileSpec () const
Definition at line 73 of file OptionValue.cpp.
References eTypeFileSpec, and GetType().
GetAsFileSpecList() [1/2]
OptionValueFileSpecList * OptionValue::GetAsFileSpecList ()
Definition at line 79 of file OptionValue.cpp.
References eTypeFileSpecList, and GetType().
Referenced by AppendFileSpecValue(), and GetFileSpecListValue().
GetAsFileSpecList() [2/2]
const OptionValueFileSpecList * OptionValue::GetAsFileSpecList () const
Definition at line 85 of file OptionValue.cpp.
References eTypeFileSpecList, and GetType().
GetAsFormat() [1/2]
OptionValueFormat * OptionValue::GetAsFormat ()
Definition at line 151 of file OptionValue.cpp.
References eTypeFormat, and GetType().
Referenced by GetFormatValue(), and SetFormatValue().
GetAsFormat() [2/2]
const OptionValueFormat * OptionValue::GetAsFormat () const
Definition at line 157 of file OptionValue.cpp.
References eTypeFormat, and GetType().
GetAsFormatEntity() [1/2]
OptionValueFormatEntity * OptionValue::GetAsFormatEntity ()
Definition at line 175 of file OptionValue.cpp.
References eTypeFormatEntity, and GetType().
Referenced by GetFormatEntityValue(), and SetFormatEntityValue().
GetAsFormatEntity() [2/2]
const OptionValueFormatEntity * OptionValue::GetAsFormatEntity () const
Definition at line 181 of file OptionValue.cpp.
References eTypeFormatEntity, and GetType().
GetAsLanguage() [1/2]
OptionValueLanguage * OptionValue::GetAsLanguage ()
Definition at line 163 of file OptionValue.cpp.
References eTypeLanguage, and GetType().
Referenced by GetLanguageValue(), and SetLanguageValue().
GetAsLanguage() [2/2]
const OptionValueLanguage * OptionValue::GetAsLanguage () const
Definition at line 169 of file OptionValue.cpp.
References eTypeLanguage, and GetType().
GetAsPathMappings() [1/2]
OptionValuePathMappings * OptionValue::GetAsPathMappings ()
Definition at line 187 of file OptionValue.cpp.
References eTypePathMap, and GetType().
GetAsPathMappings() [2/2]
const OptionValuePathMappings * OptionValue::GetAsPathMappings () const
Definition at line 193 of file OptionValue.cpp.
References eTypePathMap, and GetType().
GetAsProperties() [1/2]
OptionValueProperties * OptionValue::GetAsProperties ()
Definition at line 199 of file OptionValue.cpp.
References eTypeProperties, and GetType().
GetAsProperties() [2/2]
const OptionValueProperties * OptionValue::GetAsProperties () const
Definition at line 205 of file OptionValue.cpp.
References eTypeProperties, and GetType().
GetAsRegex() [1/2]
OptionValueRegex * OptionValue::GetAsRegex ()
Definition at line 211 of file OptionValue.cpp.
References eTypeRegex, and GetType().
Referenced by GetRegexValue().
GetAsRegex() [2/2]
const OptionValueRegex * OptionValue::GetAsRegex () const
Definition at line 217 of file OptionValue.cpp.
References eTypeRegex, and GetType().
GetAsSInt64() [1/2]
OptionValueSInt64 * OptionValue::GetAsSInt64 ()
Definition at line 223 of file OptionValue.cpp.
References eTypeSInt64, and GetType().
Referenced by lldb_private::OptionValueProperties::GetPropertyAtIndexAsOptionValueSInt64(), GetSInt64Value(), and SetSInt64Value().
GetAsSInt64() [2/2]
const OptionValueSInt64 * OptionValue::GetAsSInt64 () const
Definition at line 229 of file OptionValue.cpp.
References eTypeSInt64, and GetType().
GetAsString() [1/2]
OptionValueString * OptionValue::GetAsString ()
Definition at line 235 of file OptionValue.cpp.
References eTypeString, and GetType().
Referenced by GetStringValue(), and SetStringValue().
GetAsString() [2/2]
const OptionValueString * OptionValue::GetAsString () const
Definition at line 241 of file OptionValue.cpp.
References eTypeString, and GetType().
GetAsUInt64() [1/2]
OptionValueUInt64 * OptionValue::GetAsUInt64 ()
Definition at line 247 of file OptionValue.cpp.
References eTypeUInt64, and GetType().
Referenced by lldb_private::OptionValueProperties::GetPropertyAtIndexAsOptionValueUInt64(), GetUInt64Value(), and SetUInt64Value().
GetAsUInt64() [2/2]
const OptionValueUInt64 * OptionValue::GetAsUInt64 () const
Definition at line 253 of file OptionValue.cpp.
References eTypeUInt64, and GetType().
GetAsUUID() [1/2]
OptionValueUUID * OptionValue::GetAsUUID ()
Definition at line 259 of file OptionValue.cpp.
References eTypeUUID, and GetType().
Referenced by GetUUIDValue(), and SetUUIDValue().
GetAsUUID() [2/2]
const OptionValueUUID * OptionValue::GetAsUUID () const
Definition at line 265 of file OptionValue.cpp.
References eTypeUUID, and GetType().
GetBooleanValue()
std::optional< bool > OptionValue::GetBooleanValue () const private
Definition at line 271 of file OptionValue.cpp.
References GetAsBoolean(), and m_mutex.
Referenced by GetValueAs().
GetBuiltinTypeAsCString()
const char * OptionValue::GetBuiltinTypeAsCString (Type t) static
Definition at line 486 of file OptionValue.cpp.
References eTypeArch, eTypeArgs, eTypeArray, eTypeBoolean, eTypeChar, eTypeDictionary, eTypeEnum, eTypeFileLineColumn, eTypeFileSpec, eTypeFileSpecList, eTypeFormat, eTypeFormatEntity, eTypeInvalid, eTypeLanguage, eTypePathMap, eTypeProperties, eTypeRegex, eTypeSInt64, eTypeString, eTypeUInt64, and eTypeUUID.
Referenced by lldb_private::OptionValueArray::DumpValue(), lldb_private::OptionValueDictionary::DumpValue(), and GetTypeAsCString().
GetCharValue()
std::optional< char > OptionValue::GetCharValue () const private
Definition at line 287 of file OptionValue.cpp.
References GetAsChar(), and m_mutex.
Referenced by GetValueAs().
GetEnumerationValue()
std::optional< int64_t > OptionValue::GetEnumerationValue () const private
Definition at line 303 of file OptionValue.cpp.
References GetAsEnumeration(), and m_mutex.
Referenced by GetValueAs().
GetFileSpecListValue()
std::optional< FileSpecList > OptionValue::GetFileSpecListValue () const private
Definition at line 344 of file OptionValue.cpp.
References GetAsFileSpecList(), and m_mutex.
Referenced by GetValueAs().
GetFileSpecValue()
std::optional< FileSpec > OptionValue::GetFileSpecValue () const private
Definition at line 319 of file OptionValue.cpp.
References GetAsFileSpec(), and m_mutex.
Referenced by GetValueAs().
GetFormatEntityValue()
FormatEntity::Entry OptionValue::GetFormatEntityValue () const private
Definition at line 383 of file OptionValue.cpp.
References GetAsFormatEntity(), and m_mutex.
Referenced by GetValueAs().
GetFormatValue()
std::optional< lldb::Format > OptionValue::GetFormatValue () const private
Definition at line 351 of file OptionValue.cpp.
References GetAsFormat(), and m_mutex.
Referenced by GetValueAs().
GetLanguageValue()
std::optional< lldb::LanguageType > OptionValue::GetLanguageValue () const private
Definition at line 367 of file OptionValue.cpp.
References GetAsLanguage(), and m_mutex.
Referenced by GetValueAs().
GetName()
virtual llvm::StringRef lldb_private::OptionValue::GetName () const inline virtual
Reimplemented in lldb_private::OptionValueProperties.
Definition at line 127 of file OptionValue.h.
Referenced by DumpQualifiedName().
GetParent()
lldb::OptionValueSP lldb_private::OptionValue::GetParent () const inline
Definition at line 256 of file OptionValue.h.
References m_parent_wp.
Referenced by lldb_private::OptionValueProperties::VerifyPath().
GetRegexValue()
const RegularExpression * OptionValue::GetRegexValue () const private
Definition at line 390 of file OptionValue.cpp.
References GetAsRegex(), and m_mutex.
Referenced by GetValueAs().
GetSInt64Value()
std::optional< int64_t > OptionValue::GetSInt64Value () const private
Definition at line 397 of file OptionValue.cpp.
References GetAsSInt64(), and m_mutex.
Referenced by GetValueAs().
GetStringValue()
std::optional< llvm::StringRef > OptionValue::GetStringValue () const private
Definition at line 413 of file OptionValue.cpp.
References GetAsString(), and m_mutex.
Referenced by GetValueAs().
GetSubValue()
virtual lldb::OptionValueSP lldb_private::OptionValue::GetSubValue (const ExecutionContext * exe_ctx, llvm::StringRef name, Status & error) const inline virtual
Reimplemented in lldb_private::OptionValueArray, lldb_private::OptionValueDictionary, and lldb_private::OptionValueProperties.
Definition at line 113 of file OptionValue.h.
References error(), and lldb_private::Status::FromErrorStringWithFormatv().
GetType()
virtual Type lldb_private::OptionValue::GetType () const pure virtual
Implemented in lldb_private::OptionValueArch, lldb_private::OptionValueArgs, lldb_private::OptionValueArray, lldb_private::OptionValueBoolean, lldb_private::OptionValueChar, lldb_private::OptionValueDictionary, lldb_private::OptionValueEnumeration, lldb_private::OptionValueFileColonLine, lldb_private::OptionValueFileSpec, lldb_private::OptionValueFileSpecList, lldb_private::OptionValueFormat, lldb_private::OptionValueFormatEntity, lldb_private::OptionValueLanguage, lldb_private::OptionValuePathMappings, lldb_private::OptionValueProperties, lldb_private::OptionValueRegex, lldb_private::OptionValueSInt64, lldb_private::OptionValueString, lldb_private::OptionValueUInt64, and lldb_private::OptionValueUUID.
Referenced by GetAsArch(), GetAsArch(), GetAsArgs(), GetAsArgs(), GetAsArray(), GetAsArray(), GetAsBoolean(), GetAsBoolean(), GetAsChar(), GetAsChar(), GetAsDictionary(), GetAsDictionary(), GetAsEnumeration(), GetAsEnumeration(), GetAsFileSpec(), GetAsFileSpec(), GetAsFileSpecList(), GetAsFileSpecList(), GetAsFormat(), GetAsFormat(), GetAsFormatEntity(), GetAsFormatEntity(), GetAsLanguage(), GetAsLanguage(), GetAsPathMappings(), GetAsPathMappings(), GetAsProperties(), GetAsProperties(), GetAsRegex(), GetAsRegex(), GetAsSInt64(), GetAsSInt64(), GetAsString(), GetAsString(), GetAsUInt64(), GetAsUInt64(), GetAsUUID(), GetAsUUID(), GetTypeAsCString(), GetTypeAsMask(), and ValueIsTransparent().
GetTypeAsCString()
virtual const char * lldb_private::OptionValue::GetTypeAsCString () const inline virtual
Definition at line 89 of file OptionValue.h.
References GetBuiltinTypeAsCString(), and GetType().
Referenced by lldb_private::OptionValueArch::DumpValue(), lldb_private::OptionValueArray::DumpValue(), lldb_private::OptionValueBoolean::DumpValue(), lldb_private::OptionValueChar::DumpValue(), lldb_private::OptionValueDictionary::DumpValue(), lldb_private::OptionValueEnumeration::DumpValue(), lldb_private::OptionValueFileColonLine::DumpValue(), lldb_private::OptionValueFileSpec::DumpValue(), lldb_private::OptionValueFileSpecList::DumpValue(), lldb_private::OptionValueFormat::DumpValue(), lldb_private::OptionValueFormatEntity::DumpValue(), lldb_private::OptionValueLanguage::DumpValue(), lldb_private::OptionValuePathMappings::DumpValue(), lldb_private::OptionValueRegex::DumpValue(), lldb_private::OptionValueSInt64::DumpValue(), lldb_private::OptionValueString::DumpValue(), lldb_private::OptionValueUInt64::DumpValue(), lldb_private::OptionValueUUID::DumpValue(), lldb_private::OptionValueArray::GetSubValue(), lldb_private::OptionValueDictionary::GetSubValue(), and SetValueFromString().
GetTypeAsMask()
uint32_t lldb_private::OptionValue::GetTypeAsMask () inline
Definition at line 133 of file OptionValue.h.
References GetType().
GetUInt64Value()
std::optional< uint64_t > OptionValue::GetUInt64Value () const private
Definition at line 429 of file OptionValue.cpp.
References GetAsUInt64(), and m_mutex.
Referenced by GetValueAs().
GetUUIDValue()
std::optional< UUID > OptionValue::GetUUIDValue () const private
Definition at line 445 of file OptionValue.cpp.
References GetAsUUID(), and m_mutex.
GetValueAs() [1/2]
template<typename T, std::enable_if_t<!std::is_pointer_v< T >, bool > = true> std::optional< T > lldb_private::OptionValue::GetValueAs () const inline
Definition at line 268 of file OptionValue.h.
References GetArchSpecValue(), GetBooleanValue(), GetCharValue(), GetEnumerationValue(), GetFileSpecListValue(), GetFileSpecValue(), GetFormatEntityValue(), GetFormatValue(), GetLanguageValue(), GetSInt64Value(), GetStringValue(), and GetUInt64Value().
GetValueAs() [2/2]
template<typename T, typename U = typename std::remove_const< typename std::remove_pointer<T>::type>::type, std::enable_if_t< std::is_pointer_v< T >, bool > = true> T lldb_private::OptionValue::GetValueAs () const inline
Definition at line 301 of file OptionValue.h.
References GetRegexValue().
IsAggregateValue()
virtual bool lldb_private::OptionValue::IsAggregateValue () const inline virtual
Reimplemented in lldb_private::OptionValueArray, lldb_private::OptionValueDictionary, lldb_private::OptionValueFileSpecList, and lldb_private::OptionValuePathMappings.
Definition at line 125 of file OptionValue.h.
NotifyValueChanged()
void lldb_private::OptionValue::NotifyValueChanged () inline
Definition at line 262 of file OptionValue.h.
References m_callback.
Referenced by lldb_private::OptionValueArch::SetValueFromString(), lldb_private::OptionValueArray::SetValueFromString(), lldb_private::OptionValueBoolean::SetValueFromString(), lldb_private::OptionValueDictionary::SetValueFromString(), lldb_private::OptionValueEnumeration::SetValueFromString(), lldb_private::OptionValueFileColonLine::SetValueFromString(), lldb_private::OptionValueFileSpec::SetValueFromString(), lldb_private::OptionValueFileSpecList::SetValueFromString(), lldb_private::OptionValueFormat::SetValueFromString(), lldb_private::OptionValueFormatEntity::SetValueFromString(), lldb_private::OptionValuePathMappings::SetValueFromString(), lldb_private::OptionValueRegex::SetValueFromString(), lldb_private::OptionValueSInt64::SetValueFromString(), lldb_private::OptionValueString::SetValueFromString(), lldb_private::OptionValueUInt64::SetValueFromString(), and lldb_private::OptionValueUUID::SetValueFromString().
operator=()
OptionValue & OptionValue::operator= (const OptionValue & other)
Definition at line 27 of file OptionValue.cpp.
References m_callback, m_mutex, m_parent_wp, m_value_was_set, and OptionValue().
OptionWasSet()
bool lldb_private::OptionValue::OptionWasSet () const inline
Definition at line 248 of file OptionValue.h.
References m_value_was_set.
Referenced by OptionGroupReadMemory::FinalizeSettings().
SetArchSpecValue()
bool OptionValue::SetArchSpecValue (ArchSpec arch_spec) private
Definition at line 468 of file OptionValue.cpp.
References GetAsArch(), and m_mutex.
Referenced by SetValueAs().
SetBooleanValue()
bool OptionValue::SetBooleanValue (bool new_value) private
Definition at line 278 of file OptionValue.cpp.
References GetAsBoolean(), and m_mutex.
Referenced by SetValueAs().
SetCharValue()
bool OptionValue::SetCharValue (char new_value) private
Definition at line 294 of file OptionValue.cpp.
References GetAsChar(), and m_mutex.
Referenced by SetValueAs().
SetEnumerationValue()
bool OptionValue::SetEnumerationValue (int64_t value) private
Definition at line 310 of file OptionValue.cpp.
References GetAsEnumeration(), and m_mutex.
Referenced by SetValueAs().
SetFileSpecValue()
bool OptionValue::SetFileSpecValue (FileSpec file_spec) private
Definition at line 326 of file OptionValue.cpp.
References GetAsFileSpec(), and m_mutex.
Referenced by SetValueAs().
SetFormatEntityValue()
bool OptionValue::SetFormatEntityValue (const FormatEntity::Entry & entry) private
Definition at line 477 of file OptionValue.cpp.
References GetAsFormatEntity(), and m_mutex.
Referenced by SetValueAs().
SetFormatValue()
bool OptionValue::SetFormatValue (lldb::Format new_value) private
Definition at line 358 of file OptionValue.cpp.
References GetAsFormat(), and m_mutex.
Referenced by SetValueAs().
SetLanguageValue()
bool OptionValue::SetLanguageValue (lldb::LanguageType new_language) private
Definition at line 374 of file OptionValue.cpp.
References GetAsLanguage(), and m_mutex.
Referenced by SetValueAs().
SetOptionWasSet()
void lldb_private::OptionValue::SetOptionWasSet () inline
Definition at line 250 of file OptionValue.h.
References m_value_was_set.
SetParent()
void lldb_private::OptionValue::SetParent (const lldb::OptionValueSP & parent_sp) inline
Definition at line 252 of file OptionValue.h.
References m_parent_wp.
SetSInt64Value()
bool OptionValue::SetSInt64Value (int64_t new_value) private
Definition at line 404 of file OptionValue.cpp.
References GetAsSInt64(), and m_mutex.
Referenced by SetValueAs().
SetStringValue()
bool OptionValue::SetStringValue (llvm::StringRef new_value) private
Definition at line 420 of file OptionValue.cpp.
References GetAsString(), and m_mutex.
Referenced by SetValueAs().
SetSubValue()
Status OptionValue::SetSubValue (const ExecutionContext * exe_ctx, VarSetOperationType op, llvm::StringRef name, llvm::StringRef value) virtual
Reimplemented in lldb_private::OptionValueDictionary, and lldb_private::OptionValueProperties.
Definition at line 37 of file OptionValue.cpp.
References lldb_private::Status::FromErrorString().
SetUInt64Value()
bool OptionValue::SetUInt64Value (uint64_t new_value) private
Definition at line 436 of file OptionValue.cpp.
References GetAsUInt64(), and m_mutex.
Referenced by SetValueAs().
SetUUIDValue()
bool OptionValue::SetUUIDValue (const UUID & uuid) private
Definition at line 452 of file OptionValue.cpp.
References GetAsUUID(), and m_mutex.
Referenced by SetValueAs().
SetValueAs() [1/12]
bool lldb_private::OptionValue::SetValueAs (ArchSpec v) inline
Definition at line 325 of file OptionValue.h.
References SetArchSpecValue().
SetValueAs() [2/12]
bool lldb_private::OptionValue::SetValueAs (bool v) inline
Definition at line 307 of file OptionValue.h.
References SetBooleanValue().
SetValueAs() [3/12]
bool lldb_private::OptionValue::SetValueAs (char v) inline
Definition at line 309 of file OptionValue.h.
References SetCharValue().
SetValueAs() [4/12]
bool lldb_private::OptionValue::SetValueAs (const FormatEntity::Entry & v) inline
Definition at line 327 of file OptionValue.h.
References SetFormatEntityValue().
SetValueAs() [5/12]
bool lldb_private::OptionValue::SetValueAs (FileSpec v) inline
Definition at line 323 of file OptionValue.h.
References SetFileSpecValue().
SetValueAs() [6/12]
bool lldb_private::OptionValue::SetValueAs (int64_t v) inline
Definition at line 313 of file OptionValue.h.
References SetSInt64Value().
SetValueAs() [7/12]
bool lldb_private::OptionValue::SetValueAs (lldb::Format v) inline
Definition at line 321 of file OptionValue.h.
References SetFormatValue().
SetValueAs() [8/12]
bool lldb_private::OptionValue::SetValueAs (lldb::LanguageType v) inline
Definition at line 319 of file OptionValue.h.
References SetLanguageValue().
SetValueAs() [9/12]
bool lldb_private::OptionValue::SetValueAs (llvm::StringRef v) inline
Definition at line 317 of file OptionValue.h.
References SetStringValue().
SetValueAs() [10/12]
template<typename T, std::enable_if_t< std::is_enum_v< T >, bool > = true> bool lldb_private::OptionValue::SetValueAs (T t) inline
Definition at line 332 of file OptionValue.h.
References SetEnumerationValue().
SetValueAs() [11/12]
bool lldb_private::OptionValue::SetValueAs (uint64_t v) inline
Definition at line 311 of file OptionValue.h.
References SetUInt64Value().
SetValueAs() [12/12]
bool lldb_private::OptionValue::SetValueAs (UUID v) inline
Definition at line 315 of file OptionValue.h.
References SetUUIDValue().
SetValueChangedCallback()
void lldb_private::OptionValue::SetValueChangedCallback (std::function< void()> callback) inline
Definition at line 258 of file OptionValue.h.
References m_callback.
SetValueFromString()
Status OptionValue::SetValueFromString (llvm::StringRef value, VarSetOperationType op = eVarSetOperationAssign) virtual
Reimplemented in lldb_private::OptionValueArch, lldb_private::OptionValueArray, lldb_private::OptionValueBoolean, lldb_private::OptionValueChar, lldb_private::OptionValueDictionary, lldb_private::OptionValueEnumeration, lldb_private::OptionValueFileColonLine, lldb_private::OptionValueFileSpec, lldb_private::OptionValueFileSpecList, lldb_private::OptionValueFormat, lldb_private::OptionValueFormatEntity, lldb_private::OptionValueLanguage, lldb_private::OptionValuePathMappings, lldb_private::OptionValueProperties, lldb_private::OptionValueRegex, lldb_private::OptionValueSInt64, lldb_private::OptionValueString, lldb_private::OptionValueUInt64, and lldb_private::OptionValueUUID.
Definition at line 609 of file OptionValue.cpp.
References error(), lldb_private::eVarSetOperationAppend, lldb_private::eVarSetOperationAssign, lldb_private::eVarSetOperationClear, lldb_private::eVarSetOperationInsertAfter, lldb_private::eVarSetOperationInsertBefore, lldb_private::eVarSetOperationInvalid, lldb_private::eVarSetOperationRemove, lldb_private::eVarSetOperationReplace, lldb_private::Status::FromErrorStringWithFormat(), and GetTypeAsCString().
Referenced by lldb_private::OptionValueDictionary::SetArgs(), lldb_private::OptionValueArch::SetValueFromString(), lldb_private::OptionValueBoolean::SetValueFromString(), lldb_private::OptionValueChar::SetValueFromString(), lldb_private::OptionValueEnumeration::SetValueFromString(), lldb_private::OptionValueFileColonLine::SetValueFromString(), lldb_private::OptionValueFileSpec::SetValueFromString(), lldb_private::OptionValueFileSpecList::SetValueFromString(), lldb_private::OptionValueFormat::SetValueFromString(), lldb_private::OptionValueFormatEntity::SetValueFromString(), lldb_private::OptionValueLanguage::SetValueFromString(), lldb_private::OptionValuePathMappings::SetValueFromString(), lldb_private::OptionValueProperties::SetValueFromString(), lldb_private::OptionValueRegex::SetValueFromString(), lldb_private::OptionValueSInt64::SetValueFromString(), lldb_private::OptionValueString::SetValueFromString(), lldb_private::OptionValueUInt64::SetValueFromString(), and lldb_private::OptionValueUUID::SetValueFromString().
ToJSON()
virtual llvm::json::Value lldb_private::OptionValue::ToJSON (const ExecutionContext * exe_ctx) const pure virtual
Implemented in lldb_private::OptionValueArch, lldb_private::OptionValueArray, lldb_private::OptionValueBoolean, lldb_private::OptionValueChar, lldb_private::OptionValueDictionary, lldb_private::OptionValueEnumeration, lldb_private::OptionValueFileColonLine, lldb_private::OptionValueFileSpec, lldb_private::OptionValueFileSpecList, lldb_private::OptionValueFormat, lldb_private::OptionValueFormatEntity, lldb_private::OptionValueLanguage, lldb_private::OptionValuePathMappings, lldb_private::OptionValueProperties, lldb_private::OptionValueRegex, lldb_private::OptionValueSInt64, lldb_private::OptionValueString, lldb_private::OptionValueUInt64, and lldb_private::OptionValueUUID.
References lldb_private::eVarSetOperationAssign.
Referenced by lldb_private::OptionValueProperties::ToJSON().
ValueIsTransparent()
virtual bool lldb_private::OptionValue::ValueIsTransparent () const inline virtual
Definition at line 85 of file OptionValue.h.
References eTypeProperties, and GetType().
Referenced by lldb_private::OptionValueProperties::DumpValue().
Member Data Documentation
m_callback
std::function<void()> lldb_private::OptionValue::m_callback protected
Definition at line 358 of file OptionValue.h.
Referenced by NotifyValueChanged(), operator=(), OptionValue(), and SetValueChangedCallback().
m_mutex
std::mutex lldb_private::OptionValue::m_mutex mutable private
Definition at line 406 of file OptionValue.h.
Referenced by AppendFileSpecValue(), GetArchSpecValue(), GetBooleanValue(), GetCharValue(), GetEnumerationValue(), GetFileSpecListValue(), GetFileSpecValue(), GetFormatEntityValue(), GetFormatValue(), GetLanguageValue(), GetRegexValue(), GetSInt64Value(), GetStringValue(), GetUInt64Value(), GetUUIDValue(), operator=(), OptionValue(), SetArchSpecValue(), SetBooleanValue(), SetCharValue(), SetEnumerationValue(), SetFileSpecValue(), SetFormatEntityValue(), SetFormatValue(), SetLanguageValue(), SetSInt64Value(), SetStringValue(), SetUInt64Value(), and SetUUIDValue().
m_parent_wp
lldb::OptionValueWP lldb_private::OptionValue::m_parent_wp protected
Definition at line 357 of file OptionValue.h.
Referenced by DumpQualifiedName(), GetParent(), operator=(), OptionValue(), and SetParent().
m_value_was_set
bool lldb_private::OptionValue::m_value_was_set = false protected
Definition at line 359 of file OptionValue.h.
Referenced by lldb_private::OptionValueArch::Clear(), lldb_private::OptionValueArray::Clear(), lldb_private::OptionValueBoolean::Clear(), lldb_private::OptionValueChar::Clear(), lldb_private::OptionValueDictionary::Clear(), lldb_private::OptionValueEnumeration::Clear(), lldb_private::OptionValueFileSpec::Clear(), lldb_private::OptionValueFileSpecList::Clear(), lldb_private::OptionValueFormat::Clear(), lldb_private::OptionValueFormatEntity::Clear(), lldb_private::OptionValueLanguage::Clear(), lldb_private::OptionValuePathMappings::Clear(), lldb_private::OptionValueRegex::Clear(), lldb_private::OptionValueSInt64::Clear(), lldb_private::OptionValueString::Clear(), lldb_private::OptionValueUInt64::Clear(), lldb_private::OptionValueUUID::Clear(), lldb_private::OptionValueString::DumpValue(), operator=(), OptionValue(), OptionWasSet(), lldb_private::OptionValueArray::SetArgs(), lldb_private::OptionValueDictionary::SetArgs(), lldb_private::OptionValueArch::SetCurrentValue(), lldb_private::OptionValueFileSpec::SetCurrentValue(), SetOptionWasSet(), lldb_private::OptionValueArch::SetValueFromString(), lldb_private::OptionValueBoolean::SetValueFromString(), lldb_private::OptionValueChar::SetValueFromString(), lldb_private::OptionValueFileColonLine::SetValueFromString(), lldb_private::OptionValueFileSpec::SetValueFromString(), lldb_private::OptionValueFileSpecList::SetValueFromString(), lldb_private::OptionValueFormat::SetValueFromString(), lldb_private::OptionValueFormatEntity::SetValueFromString(), lldb_private::OptionValueLanguage::SetValueFromString(), lldb_private::OptionValuePathMappings::SetValueFromString(), lldb_private::OptionValueRegex::SetValueFromString(), lldb_private::OptionValueSInt64::SetValueFromString(), lldb_private::OptionValueString::SetValueFromString(), lldb_private::OptionValueUInt64::SetValueFromString(), and lldb_private::OptionValueUUID::SetValueFromString().
The documentation for this class was generated from the following files:
OptionValue.h
OptionValue.cpp