LLDB: lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd Class Reference
lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd Class Reference
Public Member Functions
MsvcStlDequeSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Attributes
ValueObject * m_map = nullptr
ExecutionContextRef m_exe_ctx_ref
size_t m_block_size = 0
size_t m_offset = 0
size_t m_map_size = 0
size_t m_element_size = 0
CompilerType m_element_type
uint32_t m_size = 0
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
Definition at line 19 of file MsvcStlDeque.cpp.
Constructor & Destructor Documentation
MsvcStlDequeSyntheticFrontEnd()
lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::MsvcStlDequeSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
Definition at line 48 of file MsvcStlDeque.cpp.
References lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd(), and Update().
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::CalculateNumChildren () override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 55 of file MsvcStlDeque.cpp.
References m_map, and m_size.
GetChildAtIndex()
lldb::ValueObjectSP lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::GetChildAtIndex (uint32_t idx) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 63 of file MsvcStlDeque.cpp.
References lldb_private::SyntheticChildrenFrontEnd::CreateValueObjectFromAddress(), lldb_private::Status::Fail(), lldb_private::StreamString::GetString(), lldb_private::SyntheticChildrenFrontEnd::m_backend, m_block_size, m_element_size, m_element_type, m_exe_ctx_ref, m_map, m_map_size, m_offset, m_size, and lldb_private::Stream::Printf().
GetIndexOfChildWithName()
llvm::Expected< size_t > lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::GetIndexOfChildWithName (ConstString name) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 158 of file MsvcStlDeque.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::formatters::ExtractIndexFromString(), lldb_private::ConstString::GetCString(), and m_map.
Update()
lldb::ChildCacheState lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::Update () override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 94 of file MsvcStlDeque.cpp.
References lldb::eRefetch, lldb_private::CompilerType::GetByteSize(), lldb_private::CompilerDecl::GetConstantValue(), lldb_private::CompilerType::GetStaticFieldWithName(), lldb_private::CompilerType::GetTypeTemplateArgument(), lldb_private::Scalar::IsValid(), lldb_private::SyntheticChildrenFrontEnd::m_backend, m_block_size, m_element_size, m_element_type, m_exe_ctx_ref, m_map, m_map_size, m_offset, m_size, and lldb_private::Scalar::ULongLong().
Referenced by MsvcStlDequeSyntheticFrontEnd().
Member Data Documentation
m_block_size
size_t lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::m_block_size = 0 private
Definition at line 35 of file MsvcStlDeque.cpp.
Referenced by GetChildAtIndex(), and Update().
m_element_size
size_t lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::m_element_size = 0 private
Definition at line 39 of file MsvcStlDeque.cpp.
Referenced by GetChildAtIndex(), and Update().
m_element_type
CompilerType lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::m_element_type private
Definition at line 40 of file MsvcStlDeque.cpp.
Referenced by GetChildAtIndex(), and Update().
m_exe_ctx_ref
ExecutionContextRef lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::m_exe_ctx_ref private
Definition at line 33 of file MsvcStlDeque.cpp.
Referenced by GetChildAtIndex(), and Update().
m_map
ValueObject* lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::m_map = nullptr private
Definition at line 32 of file MsvcStlDeque.cpp.
Referenced by CalculateNumChildren(), GetChildAtIndex(), GetIndexOfChildWithName(), and Update().
m_map_size
size_t lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::m_map_size = 0 private
Definition at line 37 of file MsvcStlDeque.cpp.
Referenced by GetChildAtIndex(), and Update().
m_offset
size_t lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::m_offset = 0 private
Definition at line 36 of file MsvcStlDeque.cpp.
Referenced by GetChildAtIndex(), and Update().
m_size
uint32_t lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::m_size = 0 private
Definition at line 42 of file MsvcStlDeque.cpp.
Referenced by CalculateNumChildren(), GetChildAtIndex(), and Update().
The documentation for this class was generated from the following file:
MsvcStlDeque.cpp