LLDB: lldb_private::Materializer Class Reference
lldb_private::Materializer Class Reference
#include <Materializer.h>
Classes
class Dematerializer
class Entity
class PersistentVariableDelegate
Public Types
typedef std::shared_ptr< Dematerializer > DematerializerSP
typedef std::weak_ptr< Dematerializer > DematerializerWP
Public Member Functions
Materializer ()=default
~Materializer ()
DematerializerSP Materialize (lldb::StackFrameSP &frame_sp, IRMemoryMap &map, lldb::addr_t process_address, Status &err)
uint32_t AddPersistentVariable (lldb::ExpressionVariableSP &persistent_variable_sp, PersistentVariableDelegate *delegate, Status &err)
uint32_t AddVariable (lldb::VariableSP &variable_sp, Status &err)
uint32_t AddValueObject (ConstString name, ValueObjectProviderTy valobj_provider, Status &err)
Create entity from supplied ValueObject and count it as a member of the materialized struct.
uint32_t AddResultVariable (const CompilerType &type, bool is_lvalue, bool keep_in_memory, PersistentVariableDelegate *delegate, Status &err)
uint32_t AddSymbol (const Symbol &symbol_sp, Status &err)
uint32_t AddRegister (const RegisterInfo &register_info, Status &err)
uint32_t GetStructAlignment ()
uint32_t GetStructByteSize ()
Private Types
typedef std::unique_ptr< Entity > EntityUP
typedef std::vector< EntityUP > EntityVector
Private Member Functions
uint32_t AddStructMember (Entity &entity)
Private Attributes
DematerializerWP m_dematerializer_wp
EntityVector m_entities
uint32_t m_current_offset = 0
uint32_t m_struct_alignment = 8
Detailed Description
Definition at line 23 of file Materializer.h.
Member Typedef Documentation
DematerializerSP
typedef std::shared_ptr<Dematerializer> lldb_private::Materializer::DematerializerSP
Definition at line 64 of file Materializer.h.
DematerializerWP
typedef std::weak_ptr<Dematerializer> lldb_private::Materializer::DematerializerWP
Definition at line 65 of file Materializer.h.
EntityUP
typedef std::unique_ptr<Entity> lldb_private::Materializer::EntityUP private
Definition at line 147 of file Materializer.h.
EntityVector
typedef std::vector<EntityUP> lldb_private::Materializer::EntityVector private
Definition at line 148 of file Materializer.h.
Constructor & Destructor Documentation
Materializer()
lldb_private::Materializer::Materializer () default
~Materializer()
Materializer::~Materializer ()
Definition at line 1514 of file Materializer.cpp.
References m_dematerializer_wp.
Member Function Documentation
AddPersistentVariable()
uint32_t Materializer::AddPersistentVariable (lldb::ExpressionVariableSP & persistent_variable_sp, PersistentVariableDelegate * delegate, Status & err)
Definition at line 421 of file Materializer.cpp.
References AddStructMember(), and m_entities.
AddRegister()
uint32_t Materializer::AddRegister (const RegisterInfo & register_info, Status & err)
Definition at line 1505 of file Materializer.cpp.
References AddStructMember(), and m_entities.
AddResultVariable()
uint32_t Materializer::AddResultVariable (const CompilerType & type, bool is_lvalue, bool keep_in_memory, PersistentVariableDelegate * delegate, Status & err)
Definition at line 1210 of file Materializer.cpp.
References AddStructMember(), and m_entities.
AddStructMember()
uint32_t Materializer::AddStructMember (Entity & entity) private
Definition at line 40 of file Materializer.cpp.
References lldb_private::Materializer::Entity::GetAlignment(), lldb_private::Materializer::Entity::GetSize(), m_current_offset, and m_struct_alignment.
Referenced by AddPersistentVariable(), AddRegister(), AddResultVariable(), AddSymbol(), AddValueObject(), and AddVariable().
AddSymbol()
uint32_t Materializer::AddSymbol (const Symbol & symbol_sp, Status & err)
Definition at line 1333 of file Materializer.cpp.
References AddStructMember(), and m_entities.
AddValueObject()
uint32_t Materializer::AddValueObject (ConstString name, ValueObjectProviderTy valobj_provider, Status & err)
Create entity from supplied ValueObject and count it as a member of the materialized struct.
Behaviour is undefined if 'valobj_provider' is empty.
Parameters
[in] name Name of variable to materialize
[in] valobj_provider When materializing values multiple times, this callback gets used to fetch a fresh ValueObject corresponding to the supplied frame. This is mainly used for conditional breakpoints that re-apply an expression whatever the frame happens to be when the breakpoint got hit.
[out] err Error status that gets set on error.
Returns
Offset in bytes of the member we just added to the materialized struct.
Definition at line 908 of file Materializer.cpp.
References AddStructMember(), and m_entities.
AddVariable()
uint32_t Materializer::AddVariable (lldb::VariableSP & variable_sp, Status & err)
Definition at line 900 of file Materializer.cpp.
References AddStructMember(), and m_entities.
GetStructAlignment()
uint32_t lldb_private::Materializer::GetStructAlignment () inline
Definition at line 110 of file Materializer.h.
References m_struct_alignment.
GetStructByteSize()
uint32_t lldb_private::Materializer::GetStructByteSize () inline
Definition at line 112 of file Materializer.h.
References m_current_offset.
Materialize()
Materializer::DematerializerSP Materializer::Materialize (lldb::StackFrameSP & frame_sp, IRMemoryMap & map, lldb::addr_t process_address, Status & err)
Definition at line 1522 of file Materializer.cpp.
References error(), lldb_private::Expressions, lldb_private::Status::FromErrorString(), lldb_private::IRMemoryMap::GetBestExecutionContextScope(), lldb_private::GetLog(), LLDB_LOGF, m_dematerializer_wp, and m_entities.
Member Data Documentation
m_current_offset
uint32_t lldb_private::Materializer::m_current_offset = 0 private
Definition at line 152 of file Materializer.h.
Referenced by AddStructMember(), and GetStructByteSize().
m_dematerializer_wp
DematerializerWP lldb_private::Materializer::m_dematerializer_wp private
Definition at line 150 of file Materializer.h.
Referenced by Materialize(), and ~Materializer().
m_entities
EntityVector lldb_private::Materializer::m_entities private
Definition at line 151 of file Materializer.h.
Referenced by AddPersistentVariable(), AddRegister(), AddResultVariable(), AddSymbol(), AddValueObject(), AddVariable(), and Materialize().
m_struct_alignment
uint32_t lldb_private::Materializer::m_struct_alignment = 8 private
Definition at line 153 of file Materializer.h.
Referenced by AddStructMember(), and GetStructAlignment().
The documentation for this class was generated from the following files:
Materializer.h
Materializer.cpp