LLDB: lldb_private::ThreadPlanStepOverBreakpoint Class Reference
lldb_private::ThreadPlanStepOverBreakpoint Class Reference
#include <ThreadPlanStepOverBreakpoint.h>
Public Member Functions
ThreadPlanStepOverBreakpoint (Thread &thread)
~ThreadPlanStepOverBreakpoint () override
void GetDescription (Stream *s, lldb::DescriptionLevel level) override
Print a description of this thread to the stream s.
bool ValidatePlan (Stream *error) override
Returns whether this plan could be successfully created.
bool ShouldStop (Event *event_ptr) override
bool SupportsResumeOthers () override
bool StopOthers () override
lldb::StateType GetPlanRunState () override
bool WillStop () override
void DidPop () override
bool MischiefManaged () override
void ThreadDestroyed () override
void SetAutoContinue (bool do_it)
bool ShouldAutoContinue (Event *event_ptr) override
Returns whether this thread plan overrides the ShouldStop of subsequently processed plans.
bool IsPlanStale () override
lldb::addr_t GetBreakpointLoadAddress () const
Public Member Functions inherited from lldb_private::ThreadPlan
virtual ~ThreadPlan ()
const char * GetName () const
Returns the name of this thread plan.
Thread & GetThread ()
Returns the Thread that is using this thread plan.
Target & GetTarget ()
const Target & GetTarget () const
void ClearThreadCache ()
Clear the Thread* cache.
bool TracerExplainsStop ()
lldb::StateType RunState ()
bool PlanExplainsStop (Event *event_ptr)
virtual Vote ShouldReportStop (Event *event_ptr)
Vote ShouldReportRun (Event *event_ptr)
virtual void SetStopOthers (bool new_value)
virtual bool ShouldRunBeforePublicStop ()
bool WillResume (lldb::StateType resume_state, bool current_plan)
bool IsControllingPlan ()
virtual bool IsLeafPlan ()
bool SetIsControllingPlan (bool value)
virtual bool OkayToDiscard ()
void SetOkayToDiscard (bool value)
bool GetPrivate ()
void SetPrivate (bool input)
virtual void DidPush ()
ThreadPlanKind GetKind () const
bool IsPlanComplete ()
void SetPlanComplete (bool success=true)
bool PlanSucceeded ()
virtual bool IsBasePlan ()
lldb::ThreadPlanTracerSP & GetThreadPlanTracer ()
void SetThreadPlanTracer (lldb::ThreadPlanTracerSP new_tracer_sp)
void DoTraceLog ()
virtual lldb::ValueObjectSP GetReturnValueObject ()
virtual lldb::ExpressionVariableSP GetExpressionVariable ()
virtual void RestoreThreadState ()
virtual bool IsVirtualStep ()
bool SetIterationCount (size_t count)
virtual lldb::RunDirection GetDirection () const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Protected Member Functions
bool DoPlanExplainsStop (Event *event_ptr) override
bool DoWillResume (lldb::StateType resume_state, bool current_plan) override
void ReenableBreakpointSite ()
Protected Member Functions inherited from lldb_private::ThreadPlan
ThreadPlan (ThreadPlanKind kind, const char *name, Thread &thread, Vote report_stop_vote, Vote report_run_vote)
void PushPlan (lldb::ThreadPlanSP &thread_plan_sp)
ThreadPlan * GetPreviousPlan ()
lldb::StopInfoSP GetPrivateStopInfo ()
void SetStopInfo (lldb::StopInfoSP stop_reason_sp)
bool IsUsuallyUnexplainedStopReason (lldb::StopReason)
Private Member Functions
ThreadPlanStepOverBreakpoint (const ThreadPlanStepOverBreakpoint &)=delete
const ThreadPlanStepOverBreakpoint & operator= (const ThreadPlanStepOverBreakpoint &)=delete
Private Attributes
lldb::addr_t m_breakpoint_addr
lldb::user_id_t m_breakpoint_site_id
bool m_auto_continue
bool m_reenabled_breakpoint_site
Additional Inherited Members
Public Types inherited from lldb_private::ThreadPlan
enum ThreadPlanKind {
eKindGeneric , eKindNull , eKindBase , eKindCallFunction ,
eKindPython , eKindStepInstruction , eKindStepOut , eKindStepOverBreakpoint ,
eKindStepOverRange , eKindStepInRange , eKindRunToAddress , eKindStepThrough ,
eKindStepUntil , eKindSingleThreadTimeout
}
Protected Attributes inherited from lldb_private::ThreadPlan
Status m_status
Process & m_process
lldb::tid_t m_tid
Vote m_report_stop_vote
Vote m_report_run_vote
bool m_takes_iteration_count
bool m_could_not_resolve_hw_bp
int32_t m_iteration_count = 1
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Detailed Description
Definition at line 17 of file ThreadPlanStepOverBreakpoint.h.
Constructor & Destructor Documentation
ThreadPlanStepOverBreakpoint() [1/2]
ThreadPlanStepOverBreakpoint::ThreadPlanStepOverBreakpoint (Thread & thread)
Definition at line 23 of file ThreadPlanStepOverBreakpoint.cpp.
References lldb_private::ThreadPlan::eKindStepOverBreakpoint, lldb_private::eVoteNo, lldb_private::eVoteNoOpinion, LLDB_INVALID_ADDRESS, m_auto_continue, m_breakpoint_addr, m_breakpoint_site_id, m_reenabled_breakpoint_site, and lldb_private::ThreadPlan::ThreadPlan().
Referenced by operator=(), and ThreadPlanStepOverBreakpoint().
~ThreadPlanStepOverBreakpoint()
ThreadPlanStepOverBreakpoint::~ThreadPlanStepOverBreakpoint () override default
References error().
ThreadPlanStepOverBreakpoint() [2/2]
lldb_private::ThreadPlanStepOverBreakpoint::ThreadPlanStepOverBreakpoint (const ThreadPlanStepOverBreakpoint &) private delete
References ThreadPlanStepOverBreakpoint().
Member Function Documentation
DidPop()
void ThreadPlanStepOverBreakpoint::DidPop () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 135 of file ThreadPlanStepOverBreakpoint.cpp.
References ReenableBreakpointSite().
DoPlanExplainsStop()
bool ThreadPlanStepOverBreakpoint::DoPlanExplainsStop (Event * event_ptr) override protected virtual
Implements lldb_private::ThreadPlan.
Definition at line 50 of file ThreadPlanStepOverBreakpoint.cpp.
References lldb::eStopReasonBreakpoint, lldb::eStopReasonNone, lldb::eStopReasonTrace, lldb_private::GetLog(), lldb_private::ThreadPlan::GetPrivateStopInfo(), lldb_private::Thread::GetRegisterContext(), lldb_private::ThreadPlan::GetThread(), LLDB_LOG, LLDB_LOGF, m_breakpoint_addr, SetAutoContinue(), lldb_private::Step, and lldb_private::Thread::StopReasonAsString().
DoWillResume()
bool ThreadPlanStepOverBreakpoint::DoWillResume (lldb::StateType resume_state, bool current_plan) override protected virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 117 of file ThreadPlanStepOverBreakpoint.cpp.
References m_breakpoint_addr, lldb_private::ThreadPlan::m_process, and m_reenabled_breakpoint_site.
GetBreakpointLoadAddress()
lldb::addr_t lldb_private::ThreadPlanStepOverBreakpoint::GetBreakpointLoadAddress () const inline
Definition at line 37 of file ThreadPlanStepOverBreakpoint.h.
References m_breakpoint_addr.
Referenced by lldb_private::Thread::SetupToStepOverBreakpointIfNeeded().
GetDescription()
void ThreadPlanStepOverBreakpoint::GetDescription (Stream * s, lldb::DescriptionLevel level) override virtual
Print a description of this thread to the stream s.
thread. Don't expect that the result of GetThread is valid in the description method. This might get called when the underlying Thread has not been reported, so we only know the TID and not the thread.
Parameters
[in] s The stream to which to print the description.
[in] level The level of description desired. Note that eDescriptionLevelBrief will be used in the stop message printed when the plan is complete.
Implements lldb_private::ThreadPlan.
Definition at line 42 of file ThreadPlanStepOverBreakpoint.cpp.
References m_breakpoint_addr, m_breakpoint_site_id, and lldb_private::Stream::Printf().
GetPlanRunState()
StateType ThreadPlanStepOverBreakpoint::GetPlanRunState () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 113 of file ThreadPlanStepOverBreakpoint.cpp.
References lldb::eStateStepping.
IsPlanStale()
bool ThreadPlanStepOverBreakpoint::IsPlanStale () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 177 of file ThreadPlanStepOverBreakpoint.cpp.
References lldb_private::Thread::GetRegisterContext(), lldb_private::ThreadPlan::GetThread(), and m_breakpoint_addr.
MischiefManaged()
bool ThreadPlanStepOverBreakpoint::MischiefManaged () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 137 of file ThreadPlanStepOverBreakpoint.cpp.
References lldb_private::GetLog(), lldb_private::Thread::GetRegisterContext(), lldb_private::ThreadPlan::GetThread(), LLDB_LOGF, m_breakpoint_addr, lldb_private::ThreadPlan::MischiefManaged(), ReenableBreakpointSite(), and lldb_private::Step.
operator=()
const ThreadPlanStepOverBreakpoint & lldb_private::ThreadPlanStepOverBreakpoint::operator= (const ThreadPlanStepOverBreakpoint &) private delete
References ThreadPlanStepOverBreakpoint().
ReenableBreakpointSite()
void ThreadPlanStepOverBreakpoint::ReenableBreakpointSite () protected
Definition at line 155 of file ThreadPlanStepOverBreakpoint.cpp.
References m_breakpoint_addr, lldb_private::ThreadPlan::m_process, and m_reenabled_breakpoint_site.
Referenced by DidPop(), MischiefManaged(), ThreadDestroyed(), and WillStop().
SetAutoContinue()
void ThreadPlanStepOverBreakpoint::SetAutoContinue (bool do_it)
Definition at line 169 of file ThreadPlanStepOverBreakpoint.cpp.
References m_auto_continue.
Referenced by DoPlanExplainsStop(), and lldb_private::Thread::SetupToStepOverBreakpointIfNeeded().
ShouldAutoContinue()
bool ThreadPlanStepOverBreakpoint::ShouldAutoContinue (Event * event_ptr) override virtual
Returns whether this thread plan overrides the ShouldStop of subsequently processed plans.
When processing the thread plan stack, this function gives plans the ability to continue - even when subsequent plans return true from ShouldStop.
See also
Thread::ShouldStop
Reimplemented from lldb_private::ThreadPlan.
Definition at line 173 of file ThreadPlanStepOverBreakpoint.cpp.
References m_auto_continue.
Referenced by ShouldStop().
ShouldStop()
bool ThreadPlanStepOverBreakpoint::ShouldStop (Event * event_ptr) override virtual
Implements lldb_private::ThreadPlan.
Definition at line 100 of file ThreadPlanStepOverBreakpoint.cpp.
References ShouldAutoContinue().
StopOthers()
bool ThreadPlanStepOverBreakpoint::StopOthers () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 104 of file ThreadPlanStepOverBreakpoint.cpp.
SupportsResumeOthers()
bool ThreadPlanStepOverBreakpoint::SupportsResumeOthers () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 111 of file ThreadPlanStepOverBreakpoint.cpp.
ThreadDestroyed()
void ThreadPlanStepOverBreakpoint::ThreadDestroyed () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 165 of file ThreadPlanStepOverBreakpoint.cpp.
References ReenableBreakpointSite().
ValidatePlan()
bool ThreadPlanStepOverBreakpoint::ValidatePlan (Stream * error) override virtual
Returns whether this plan could be successfully created.
Parameters
[in] error A stream to which to print some reason why the plan could not be created. Can be NULL.
Returns
true if the plan should be queued, false otherwise.
Implements lldb_private::ThreadPlan.
Definition at line 48 of file ThreadPlanStepOverBreakpoint.cpp.
References error().
WillStop()
bool ThreadPlanStepOverBreakpoint::WillStop () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 130 of file ThreadPlanStepOverBreakpoint.cpp.
References ReenableBreakpointSite().
Member Data Documentation
m_auto_continue
bool lldb_private::ThreadPlanStepOverBreakpoint::m_auto_continue private
Definition at line 48 of file ThreadPlanStepOverBreakpoint.h.
Referenced by SetAutoContinue(), ShouldAutoContinue(), and ThreadPlanStepOverBreakpoint().
m_breakpoint_addr
lldb::addr_t lldb_private::ThreadPlanStepOverBreakpoint::m_breakpoint_addr private
Definition at line 46 of file ThreadPlanStepOverBreakpoint.h.
Referenced by DoPlanExplainsStop(), DoWillResume(), GetBreakpointLoadAddress(), GetDescription(), IsPlanStale(), MischiefManaged(), ReenableBreakpointSite(), and ThreadPlanStepOverBreakpoint().
m_breakpoint_site_id
lldb::user_id_t lldb_private::ThreadPlanStepOverBreakpoint::m_breakpoint_site_id private
Definition at line 47 of file ThreadPlanStepOverBreakpoint.h.
Referenced by GetDescription(), and ThreadPlanStepOverBreakpoint().
m_reenabled_breakpoint_site
bool lldb_private::ThreadPlanStepOverBreakpoint::m_reenabled_breakpoint_site private
Definition at line 49 of file ThreadPlanStepOverBreakpoint.h.
Referenced by DoWillResume(), ReenableBreakpointSite(), and ThreadPlanStepOverBreakpoint().
The documentation for this class was generated from the following files:
ThreadPlanStepOverBreakpoint.h
ThreadPlanStepOverBreakpoint.cpp