LLDB: ABISysV_arc Class Reference
ABISysV_arc Class Reference
#include <ABISysV_arc.h>
Public Member Functions
~ABISysV_arc () override=default
size_t GetRedZoneSize () const override
bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override
bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::Type &prototype, llvm::ArrayRef< ABI::CallArgument > args) const override
bool GetArgumentValues (lldb_private::Thread &thread, lldb_private::ValueList &values) const override
lldb_private::Status SetReturnValueObject (lldb::StackFrameSP &frame_sp, lldb::ValueObjectSP &new_value) override
lldb::ValueObjectSP GetReturnValueObjectImpl (lldb_private::Thread &thread, lldb_private::CompilerType &type) const override
lldb::ValueObjectSP GetReturnValueObjectImpl (lldb_private::Thread &thread, llvm::Type &type) const override
lldb::UnwindPlanSP CreateFunctionEntryUnwindPlan () override
lldb::UnwindPlanSP CreateDefaultUnwindPlan () override
bool RegisterIsVolatile (const lldb_private::RegisterInfo *reg_info) override
bool CallFrameAddressIsValid (lldb::addr_t cfa) override
bool CodeAddressIsValid (lldb::addr_t pc) override
const lldb_private::RegisterInfo * GetRegisterInfoArray (uint32_t &count) override
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::RegInfoBasedABI
void AugmentRegisterInfo (std::vector< DynamicRegisterInfo::Register > &regs) override
Public Member Functions inherited from lldb_private::ABI
~ABI () override
virtual bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::Type &prototype, llvm::ArrayRef< CallArgument > args) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, CompilerType &type, bool persistent=true) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, llvm::Type &type, bool persistent=true) const
virtual bool GetFallbackRegisterLocation (const RegisterInfo *reg_info, UnwindPlan::Row::AbstractRegisterLocation &unwind_regloc)
virtual lldb::addr_t FixAnyAddress (lldb::addr_t pc)
Use this method when you do not know, or do not care what kind of address you are fixing.
llvm::MCRegisterInfo & GetMCRegisterInfo ()
virtual bool GetPointerReturnRegister (const char *&name)
virtual uint64_t GetStackFrameSize ()
virtual lldb::addr_t FixCodeAddress (lldb::addr_t pc)
Some targets might use bits in a code address to indicate a mode switch.
virtual lldb::addr_t FixDataAddress (lldb::addr_t pc)
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static lldb::ABISP CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec &arch)
static llvm::StringRef GetPluginNameStatic ()
Static Public Member Functions inherited from lldb_private::ABI
static lldb::ABISP FindPlugin (lldb::ProcessSP process_sp, const ArchSpec &arch)
Private Types
using RegisterFileFlag = std::optional<bool>
Private Member Functions
lldb::ValueObjectSP GetReturnValueObjectSimple (lldb_private::Thread &thread, lldb_private::CompilerType &ast_type) const
bool IsRegisterFileReduced (lldb_private::RegisterContext &reg_ctx) const
Private Attributes
RegisterFileFlag m_is_reg_file_reduced
Additional Inherited Members
Protected Member Functions inherited from lldb_private::RegInfoBasedABI
bool GetRegisterInfoByName (llvm::StringRef name, RegisterInfo &info)
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Protected Member Functions inherited from lldb_private::ABI
lldb::ProcessSP GetProcessSP () const
Request to get a Process shared pointer.
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Static Protected Member Functions inherited from lldb_private::ABI
static std::unique_ptr< llvm::MCRegisterInfo > MakeMCRegisterInfo (const ArchSpec &arch)
Utility function to construct a MCRegisterInfo using the ArchSpec triple.
Protected Attributes inherited from lldb_private::ABI
lldb::ProcessWP m_process_wp
std::unique_ptr< llvm::MCRegisterInfo > m_mc_register_info_up
Detailed Description
Definition at line 19 of file ABISysV_arc.h.
Member Typedef Documentation
RegisterFileFlag
using ABISysV_arc::RegisterFileFlag = std::optional<bool> private
Definition at line 99 of file ABISysV_arc.h.
Constructor & Destructor Documentation
~ABISysV_arc()
ABISysV_arc::~ABISysV_arc () override default
Member Function Documentation
CallFrameAddressIsValid()
bool ABISysV_arc::CallFrameAddressIsValid (lldb::addr_t cfa) inline override virtual
Implements lldb_private::ABI.
Definition at line 58 of file ABISysV_arc.h.
CodeAddressIsValid()
bool ABISysV_arc::CodeAddressIsValid (lldb::addr_t pc) inline override virtual
Implements lldb_private::ABI.
Definition at line 63 of file ABISysV_arc.h.
References pc.
CreateDefaultUnwindPlan()
UnwindPlanSP ABISysV_arc::CreateDefaultUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 572 of file ABISysV_arc.cpp.
CreateFunctionEntryUnwindPlan()
UnwindPlanSP ABISysV_arc::CreateFunctionEntryUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 556 of file ABISysV_arc.cpp.
References lldb_private::eLazyBoolNo, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), and lldb_private::UnwindPlan::Row::SetRegisterLocationToRegister().
CreateInstance()
ABISP ABISysV_arc::CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec & arch) static
Definition at line 164 of file ABISysV_arc.cpp.
References lldb_private::ArchSpec::GetTriple(), and lldb_private::ABI::MakeMCRegisterInfo().
Referenced by Initialize(), and Terminate().
GetArgumentValues()
bool ABISysV_arc::GetArgumentValues (lldb_private::Thread & thread, lldb_private::ValueList & values) const override virtual
Implements lldb_private::ABI.
Definition at line 307 of file ABISysV_arc.cpp.
GetPluginName()
llvm::StringRef ABISysV_arc::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 88 of file ABISysV_arc.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef ABISysV_arc::GetPluginNameStatic () inline static
Definition at line 82 of file ABISysV_arc.h.
Referenced by GetPluginName(), and Initialize().
GetRedZoneSize()
size_t ABISysV_arc::GetRedZoneSize () const override virtual
Implements lldb_private::ABI.
Definition at line 144 of file ABISysV_arc.cpp.
GetRegisterInfoArray()
const RegisterInfo * ABISysV_arc::GetRegisterInfoArray (uint32_t & count) override virtual
Implements lldb_private::RegInfoBasedABI.
Definition at line 139 of file ABISysV_arc.cpp.
GetReturnValueObjectImpl() [1/2]
ValueObjectSP ABISysV_arc::GetReturnValueObjectImpl (lldb_private::Thread & thread, lldb_private::CompilerType & type) const override virtual
Implements lldb_private::ABI.
Definition at line 499 of file ABISysV_arc.cpp.
References GetReturnValueObjectSimple().
GetReturnValueObjectImpl() [2/2]
ValueObjectSP ABISysV_arc::GetReturnValueObjectImpl (lldb_private::Thread & thread, llvm::Type & type) const override virtual
Reimplemented from lldb_private::ABI.
Definition at line 510 of file ABISysV_arc.cpp.
References lldb_private::ValueObjectConstResult::Create(), lldb::eRegisterKindGeneric, lldb_private::Value::GetScalar(), LLDB_REGNUM_GENERIC_ARG1, ReadRawValue(), lldb_private::Value::Scalar, SetSizedFloat(), SetSizedInteger(), and lldb_private::Value::SetValueType().
GetReturnValueObjectSimple()
ValueObjectSP ABISysV_arc::GetReturnValueObjectSimple (lldb_private::Thread & thread, lldb_private::CompilerType & ast_type) const private
Definition at line 447 of file ABISysV_arc.cpp.
References lldb_private::ValueObjectConstResult::Create(), lldb::eRegisterKindGeneric, lldb_private::CompilerType::GetByteSize(), lldb_private::Value::GetScalar(), lldb_private::CompilerType::GetTypeInfo(), lldb_private::CompilerType::IsRealFloatingPointType(), LLDB_REGNUM_GENERIC_ARG1, ReadRawValue(), lldb_private::Value::Scalar, lldb_private::Value::SetCompilerType(), SetSizedFloat(), SetSizedInteger(), and lldb_private::Value::SetValueType().
Referenced by GetReturnValueObjectImpl().
Initialize()
void ABISysV_arc::Initialize () static
Definition at line 587 of file ABISysV_arc.cpp.
References CreateInstance(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
IsRegisterFileReduced()
bool ABISysV_arc::IsRegisterFileReduced (lldb_private::RegisterContext & reg_ctx) const private
Definition at line 146 of file ABISysV_arc.cpp.
References lldb_private::RegisterContext::GetRegisterInfoByName(), m_is_reg_file_reduced, and lldb_private::RegisterContext::ReadRegisterAsUnsigned().
PrepareTrivialCall() [1/2]
bool ABISysV_arc::PrepareTrivialCall (lldb_private::Thread & thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override virtual
Implements lldb_private::ABI.
References sp.
PrepareTrivialCall() [2/2]
bool ABISysV_arc::PrepareTrivialCall (lldb_private::Thread & thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::Type & prototype, llvm::ArrayRef< ABI::CallArgument > args) const override
References sp.
RegisterIsVolatile()
bool ABISysV_arc::RegisterIsVolatile (const lldb_private::RegisterInfo * reg_info) override virtual
Implements lldb_private::ABI.
Definition at line 574 of file ABISysV_arc.cpp.
References lldb::eRegisterKindDWARF, lldb_private::RegisterInfo::kinds, and lldb_private::RegisterInfo::name.
SetReturnValueObject()
Status ABISysV_arc::SetReturnValueObject (lldb::StackFrameSP & frame_sp, lldb::ValueObjectSP & new_value) override virtual
Implements lldb_private::ABI.
Definition at line 311 of file ABISysV_arc.cpp.
References lldb_private::Status::AsCString(), lldb::eRegisterKindGeneric, lldb_private::Status::Fail(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataExtractor::GetMaxU64(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), lldb_private::CompilerType::IsPointerType(), LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_ARG2, and reg_size.
Terminate()
void ABISysV_arc::Terminate () static
Definition at line 592 of file ABISysV_arc.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Member Data Documentation
m_is_reg_file_reduced
RegisterFileFlag ABISysV_arc::m_is_reg_file_reduced mutable private
Definition at line 100 of file ABISysV_arc.h.
Referenced by IsRegisterFileReduced().
The documentation for this class was generated from the following files:
ABISysV_arc.h
ABISysV_arc.cpp