LLDB: lldb_private::AppleGetThreadItemInfoHandler Class Reference
lldb_private::AppleGetThreadItemInfoHandler Class Reference
#include <AppleGetThreadItemInfoHandler.h>
Classes
struct GetThreadItemInfoReturnInfo
Public Member Functions
AppleGetThreadItemInfoHandler (lldb_private::Process *process)
~AppleGetThreadItemInfoHandler ()
GetThreadItemInfoReturnInfo GetThreadItemInfo (Thread &thread, lldb::tid_t thread_id, lldb::addr_t page_to_free, uint64_t page_to_free_size, lldb_private::Status &error)
Get the information about a work item by calling __introspection_dispatch_thread_get_item_info.
void Detach ()
Private Member Functions
lldb::addr_t SetupGetThreadItemInfoFunction (Thread &thread, ValueList &get_thread_item_info_arglist)
Private Attributes
lldb_private::Process * m_process
std::unique_ptr< UtilityFunction > m_get_thread_item_info_impl_code
std::mutex m_get_thread_item_info_function_mutex
lldb::addr_t m_get_thread_item_info_return_buffer_addr
std::mutex m_get_thread_item_info_retbuffer_mutex
Static Private Attributes
static const char * g_get_thread_item_info_function_name
static const char * g_get_thread_item_info_function_code
Detailed Description
Definition at line 43 of file AppleGetThreadItemInfoHandler.h.
Constructor & Destructor Documentation
AppleGetThreadItemInfoHandler()
AppleGetThreadItemInfoHandler::AppleGetThreadItemInfoHandler (lldb_private::Process * process)
Definition at line 105 of file AppleGetThreadItemInfoHandler.cpp.
References LLDB_INVALID_ADDRESS, m_get_thread_item_info_function_mutex, m_get_thread_item_info_impl_code, m_get_thread_item_info_retbuffer_mutex, m_get_thread_item_info_return_buffer_addr, and m_process.
~AppleGetThreadItemInfoHandler()
AppleGetThreadItemInfoHandler::~AppleGetThreadItemInfoHandler () default
Member Function Documentation
Detach()
void AppleGetThreadItemInfoHandler::Detach ()
Definition at line 113 of file AppleGetThreadItemInfoHandler.cpp.
References LLDB_INVALID_ADDRESS, m_get_thread_item_info_retbuffer_mutex, m_get_thread_item_info_return_buffer_addr, and m_process.
GetThreadItemInfo()
AppleGetThreadItemInfoHandler::GetThreadItemInfoReturnInfo AppleGetThreadItemInfoHandler::GetThreadItemInfo (Thread & thread, lldb::tid_t thread_id, lldb::addr_t page_to_free, uint64_t page_to_free_size, lldb_private::Status & error)
Get the information about a work item by calling __introspection_dispatch_thread_get_item_info.
If there's a page of memory that needs to be freed, pass in the address and size and it will be freed before getting the list of queues.
Parameters
[in] thread_id The thread to get the extended backtrace for.
[in] page_to_free An address of an inferior process vm page that needs to be deallocated, LLDB_INVALID_ADDRESS if this is not needed.
[in] page_to_free_size The size of the vm page that needs to be deallocated if an address was passed in to page_to_free.
[out] error This object will be updated with the error status / error string from any failures encountered.
Returns
The result of the inferior function call execution. If there was a failure of any kind while getting the information, the item_buffer_ptr value will be LLDB_INVALID_ADDRESS.
Definition at line 218 of file AppleGetThreadItemInfoHandler.cpp.
References lldb::eBasicTypeInt, lldb::eBasicTypeUnsignedLongLong, lldb::eBasicTypeVoid, lldb::eExpressionCompleted, error(), lldb_private::FunctionCaller::ExecuteFunction(), lldb_private::Status::FromErrorString(), lldb_private::ScratchTypeSystemClang::GetForTarget(), lldb_private::GetLog(), lldb_private::Value::GetScalar(), lldb_private::AppleGetThreadItemInfoHandler::GetThreadItemInfoReturnInfo::item_buffer_ptr, lldb_private::AppleGetThreadItemInfoHandler::GetThreadItemInfoReturnInfo::item_buffer_size, LLDB_INVALID_ADDRESS, LLDB_LOGF, m_get_thread_item_info_impl_code, m_get_thread_item_info_retbuffer_mutex, m_get_thread_item_info_return_buffer_addr, m_process, lldb_private::ValueList::PushValue(), lldb_private::Value::Scalar, lldb_private::Value::SetCompilerType(), lldb_private::EvaluateExpressionOptions::SetIgnoreBreakpoints(), lldb_private::EvaluateExpressionOptions::SetIsForUtilityExpr(), lldb_private::EvaluateExpressionOptions::SetStopOthers(), lldb_private::EvaluateExpressionOptions::SetTimeout(), lldb_private::EvaluateExpressionOptions::SetTryAllThreads(), lldb_private::EvaluateExpressionOptions::SetUnwindOnError(), SetupGetThreadItemInfoFunction(), lldb_private::Value::SetValueType(), and lldb_private::SystemRuntime.
SetupGetThreadItemInfoFunction()
lldb::addr_t AppleGetThreadItemInfoHandler::SetupGetThreadItemInfoFunction (Thread & thread, ValueList & get_thread_item_info_arglist) private
Definition at line 138 of file AppleGetThreadItemInfoHandler.cpp.
References lldb_private::DiagnosticManager::Clear(), lldb_private::Target::CreateUtilityFunction(), lldb_private::DiagnosticManager::Dump(), lldb::eBasicTypeVoid, lldb::eLanguageTypeC, error(), g_get_thread_item_info_function_code, g_get_thread_item_info_function_name, lldb_private::ScratchTypeSystemClang::GetForTarget(), lldb_private::GetLog(), lldb_private::ExecutionContext::GetTargetRef(), LLDB_INVALID_ADDRESS, LLDB_LOG_ERROR, LLDB_LOGF, m_get_thread_item_info_function_mutex, m_get_thread_item_info_impl_code, lldb_private::SystemRuntime, and lldb_private::FunctionCaller::WriteFunctionArguments().
Referenced by GetThreadItemInfo().
Member Data Documentation
g_get_thread_item_info_function_code
const char * AppleGetThreadItemInfoHandler::g_get_thread_item_info_function_code static private
Definition at line 98 of file AppleGetThreadItemInfoHandler.h.
Referenced by SetupGetThreadItemInfoFunction().
g_get_thread_item_info_function_name
const char * AppleGetThreadItemInfoHandler::g_get_thread_item_info_function_name static private
Initial value:
=
        "__lldb_backtrace_recording_get_thread_item_info"
Definition at line 97 of file AppleGetThreadItemInfoHandler.h.
Referenced by SetupGetThreadItemInfoFunction().
m_get_thread_item_info_function_mutex
std::mutex lldb_private::AppleGetThreadItemInfoHandler::m_get_thread_item_info_function_mutex private
Definition at line 102 of file AppleGetThreadItemInfoHandler.h.
Referenced by AppleGetThreadItemInfoHandler(), and SetupGetThreadItemInfoFunction().
m_get_thread_item_info_impl_code
std::unique_ptr<UtilityFunction> lldb_private::AppleGetThreadItemInfoHandler::m_get_thread_item_info_impl_code private
Definition at line 101 of file AppleGetThreadItemInfoHandler.h.
Referenced by AppleGetThreadItemInfoHandler(), GetThreadItemInfo(), and SetupGetThreadItemInfoFunction().
m_get_thread_item_info_retbuffer_mutex
std::mutex lldb_private::AppleGetThreadItemInfoHandler::m_get_thread_item_info_retbuffer_mutex private
Definition at line 105 of file AppleGetThreadItemInfoHandler.h.
Referenced by AppleGetThreadItemInfoHandler(), Detach(), and GetThreadItemInfo().
m_get_thread_item_info_return_buffer_addr
lldb::addr_t lldb_private::AppleGetThreadItemInfoHandler::m_get_thread_item_info_return_buffer_addr private
Definition at line 104 of file AppleGetThreadItemInfoHandler.h.
Referenced by AppleGetThreadItemInfoHandler(), Detach(), and GetThreadItemInfo().
m_process
lldb_private::Process* lldb_private::AppleGetThreadItemInfoHandler::m_process private
Definition at line 100 of file AppleGetThreadItemInfoHandler.h.
Referenced by AppleGetThreadItemInfoHandler(), Detach(), and GetThreadItemInfo().
The documentation for this class was generated from the following files:
AppleGetThreadItemInfoHandler.h
AppleGetThreadItemInfoHandler.cpp