LLDB: lldb_private::HostInfoBase Class Reference
lldb_private::HostInfoBase Class Reference
#include <HostInfoBase.h>
Classes
struct SDKOptions
Public Types
enum ArchitectureKind { eArchKindDefault , eArchKind32 , eArchKind64 }
using SharedLibraryDirectoryHelper = void(FileSpec &this_file)
A helper function for determining the liblldb location.
Static Public Member Functions
static void Initialize (SharedLibraryDirectoryHelper *helper=nullptr)
static void Terminate ()
static llvm::Triple GetTargetTriple ()
Gets the host target triple.
static const ArchSpec & GetArchitecture (ArchitectureKind arch_kind=eArchKindDefault)
static std::optional< ArchitectureKind > ParseArchitectureKind (llvm::StringRef kind)
static FileSpec GetShlibDir ()
Returns the directory containing the lldb shared library.
static FileSpec GetSupportExeDir ()
Returns the directory containing the support executables (debugserver, ...).
static FileSpec GetHeaderDir ()
Returns the directory containing the lldb headers.
static FileSpec GetSystemPluginDir ()
Returns the directory containing the system plugins.
static FileSpec GetUserHomeDir ()
Returns the directory containing the users home (e.g.
static FileSpec GetUserLLDBDir ()
Returns the directory containing the users lldb home (e.g.
static FileSpec GetUserPluginDir ()
Returns the directory containing the user plugins.
static FileSpec GetProcessTempDir ()
Returns the process temporary directory.
static FileSpec GetGlobalTempDir ()
Returns the global temporary directory.
static ArchSpec GetAugmentedArchSpec (llvm::StringRef triple)
If the triple does not specify the vendor, os, and environment parts, we "augment" these using information from the host and return the resulting ArchSpec object.
static bool ComputePathRelativeToLibrary (FileSpec &file_spec, llvm::StringRef dir)
static FileSpec GetXcodeContentsDirectory ()
static FileSpec GetXcodeDeveloperDirectory ()
static FileSpec GetCurrentXcodeToolchainDirectory ()
static FileSpec GetCurrentCommandLineToolsDirectory ()
static llvm::Expected< llvm::StringRef > GetSDKRoot (SDKOptions options)
Return the directory containing something like a SDK (reused for Swift).
static llvm::Expected< llvm::StringRef > FindSDKTool (XcodeSDK sdk, llvm::StringRef tool)
Return the path to a specific tool in the specified Xcode SDK.
static SharedCacheImageInfo GetSharedCacheImageInfo (ConstString filepath, lldb::SymbolSharedCacheUse sc_mode)
Return information about module filepath if it is loaded in the current process's address space.
static SharedCacheImageInfo GetSharedCacheImageInfo (const UUID &uuid, lldb::SymbolSharedCacheUse sc_mode)
Return information about module uuid if it is loaded in the current process's address space.
static SharedCacheImageInfo GetSharedCacheImageInfo (ConstString filepath, const UUID &sc_uuid, lldb::SymbolSharedCacheUse sc_mode)
Return information about module filepath, if it is loaded in the current process's address space using shared cache sc_uuid.
static SharedCacheImageInfo GetSharedCacheImageInfo (const UUID &uuid, const UUID &sc_uuid, lldb::SymbolSharedCacheUse sc_mode)
Return information about module uuid, if it is loaded in the current process's address space using shared cache sc_uuid.
static SharedCacheImageInfo GetSharedCacheImageInfo (llvm::StringRef image_name, const UUID &uuid, lldb::SymbolSharedCacheUse sc_mode)
Return information about module image_name if it is loaded in the current process's address space using shared cache uuid.
static bool SharedCacheIndexFiles (FileSpec &filepath, UUID &uuid, lldb::SymbolSharedCacheUse sc_mode)
Scan the files in a shared cache, if the filepath and uuid match on the debug host.
static llvm::StringRef GetDistributionId ()
Returns the distribution id of the host.
Static Protected Member Functions
static bool ComputeSharedLibraryDirectory (FileSpec &file_spec)
static bool ComputeSupportExeDirectory (FileSpec &file_spec)
static bool ComputeProcessTempFileDirectory (FileSpec &file_spec)
static bool ComputeGlobalTempFileDirectory (FileSpec &file_spec)
static bool ComputeTempFileBaseDirectory (FileSpec &file_spec)
static bool ComputeHeaderDirectory (FileSpec &file_spec)
static bool ComputeSystemPluginsDirectory (FileSpec &file_spec)
static bool ComputeUserHomeDirectory (FileSpec &file_spec)
static bool ComputeUserLLDBHomeDirectory (FileSpec &file_spec)
static bool ComputeUserPluginsDirectory (FileSpec &file_spec)
static void ComputeHostArchitectureSupport (ArchSpec &arch_32, ArchSpec &arch_64)
Private Member Functions
HostInfoBase ()=default
~HostInfoBase ()=default
Detailed Description
Definition at line 87 of file HostInfoBase.h.
Member Typedef Documentation
SharedLibraryDirectoryHelper
using lldb_private::HostInfoBase::SharedLibraryDirectoryHelper = void(FileSpec &this_file)
A helper function for determining the liblldb location.
It receives a FileSpec with the location of file containing this code. It can (optionally) replace it with a file spec pointing to a more canonical copy.
Definition at line 98 of file HostInfoBase.h.
Member Enumeration Documentation
ArchitectureKind
enum lldb_private::HostInfoBase::ArchitectureKind
Enumerator
eArchKindDefault
eArchKind32
eArchKind64
Definition at line 109 of file HostInfoBase.h.
Constructor & Destructor Documentation
HostInfoBase()
lldb_private::HostInfoBase::HostInfoBase () private default
~HostInfoBase()
lldb_private::HostInfoBase::~HostInfoBase () private default
Member Function Documentation
ComputeGlobalTempFileDirectory()
bool HostInfoBase::ComputeGlobalTempFileDirectory (FileSpec & file_spec) static protected
Definition at line 316 of file HostInfoBase.cpp.
References lldb_private::FileSpec::AppendPathComponent(), lldb_private::FileSpec::Clear(), lldb_private::FileSpec::GetPath(), lldb_private::FileSpec::GetPathAsConstString(), and lldb_private::FileSpec::SetDirectory().
ComputeHeaderDirectory()
bool HostInfoBase::ComputeHeaderDirectory (FileSpec & file_spec) static protected
Definition at line 331 of file HostInfoBase.cpp.
ComputeHostArchitectureSupport()
void HostInfoBase::ComputeHostArchitectureSupport (ArchSpec & arch_32, ArchSpec & arch_64) static protected
Definition at line 363 of file HostInfoBase.cpp.
References lldb_private::ArchSpec::Clear(), and lldb_private::ArchSpec::SetTriple().
Referenced by lldb_private::HostInfoLinux::ComputeHostArchitectureSupport().
ComputePathRelativeToLibrary()
bool HostInfoBase::ComputePathRelativeToLibrary (FileSpec & file_spec, llvm::StringRef dir) static
Definition at line 245 of file HostInfoBase.cpp.
References lldb_private::FileSpec::GetDirectory(), lldb_private::GetLog(), lldb_private::FileSpec::GetPath(), GetShlibDir(), lldb_private::Host, LLDB_LOG, and lldb_private::FileSpec::SetDirectory().
Referenced by lldb_private::HostInfoPosix::ComputeSupportExeDirectory().
ComputeProcessTempFileDirectory()
bool HostInfoBase::ComputeProcessTempFileDirectory (FileSpec & file_spec) static protected
Definition at line 294 of file HostInfoBase.cpp.
References lldb_private::FileSpec::AppendPathComponent(), lldb_private::Host::GetCurrentProcessID(), lldb_private::FileSpec::GetPath(), lldb_private::FileSpec::GetPathAsConstString(), and lldb_private::FileSpec::SetDirectory().
ComputeSharedLibraryDirectory()
bool HostInfoBase::ComputeSharedLibraryDirectory (FileSpec & file_spec) static protected
Definition at line 272 of file HostInfoBase.cpp.
References ComputeSharedLibraryDirectory(), g_shlib_dir_helper, lldb_private::FileSpec::GetDirectory(), lldb_private::Host::GetModuleFileSpecForHostAddress(), and lldb_private::FileSpec::SetDirectory().
Referenced by ComputeSharedLibraryDirectory().
ComputeSupportExeDirectory()
bool HostInfoBase::ComputeSupportExeDirectory (FileSpec & file_spec) static protected
Definition at line 289 of file HostInfoBase.cpp.
References GetShlibDir().
ComputeSystemPluginsDirectory()
bool HostInfoBase::ComputeSystemPluginsDirectory (FileSpec & file_spec) static protected
Definition at line 337 of file HostInfoBase.cpp.
ComputeTempFileBaseDirectory()
bool HostInfoBase::ComputeTempFileBaseDirectory (FileSpec & file_spec) static protected
Definition at line 308 of file HostInfoBase.cpp.
References lldb_private::FileSystem::Instance(), and lldb_private::FileSystem::Resolve().
Referenced by lldb_private::HostInfoAndroid::ComputeTempFileBaseDirectory().
ComputeUserHomeDirectory()
bool HostInfoBase::ComputeUserHomeDirectory (FileSpec & file_spec) static protected
Definition at line 343 of file HostInfoBase.cpp.
References lldb_private::FileSpec::GetPathAsConstString(), lldb_private::FileSystem::Instance(), lldb_private::FileSystem::Resolve(), and lldb_private::FileSpec::SetDirectory().
ComputeUserLLDBHomeDirectory()
bool HostInfoBase::ComputeUserLLDBHomeDirectory (FileSpec & file_spec) static protected
Definition at line 350 of file HostInfoBase.cpp.
References lldb_private::FileSpec::AppendPathComponent(), lldb_private::FileSpec::GetPathAsConstString(), GetUserHomeDir(), and lldb_private::FileSpec::SetDirectory().
ComputeUserPluginsDirectory()
bool HostInfoBase::ComputeUserPluginsDirectory (FileSpec & file_spec) static protected
Definition at line 357 of file HostInfoBase.cpp.
FindSDKTool()
llvm::Expected< llvm::StringRef > lldb_private::HostInfoBase::FindSDKTool (XcodeSDK sdk, llvm::StringRef tool) inline static
Return the path to a specific tool in the specified Xcode SDK.
Definition at line 185 of file HostInfoBase.h.
GetArchitecture()
const ArchSpec & HostInfoBase::GetArchitecture (ArchitectureKind arch_kind = eArchKindDefault) static
Definition at line 100 of file HostInfoBase.cpp.
References eArchKind32, eArchKind64, and g_fields.
GetAugmentedArchSpec()
ArchSpec HostInfoBase::GetAugmentedArchSpec (llvm::StringRef triple) static
If the triple does not specify the vendor, os, and environment parts, we "augment" these using information from the host and return the resulting ArchSpec object.
Definition at line 223 of file HostInfoBase.cpp.
References lldb_private::ArchSpec::ContainsOnlyArch().
GetCurrentCommandLineToolsDirectory()
FileSpec lldb_private::HostInfoBase::GetCurrentCommandLineToolsDirectory () inline static
Definition at line 173 of file HostInfoBase.h.
GetCurrentXcodeToolchainDirectory()
FileSpec lldb_private::HostInfoBase::GetCurrentXcodeToolchainDirectory () inline static
Definition at line 172 of file HostInfoBase.h.
GetDistributionId()
llvm::StringRef lldb_private::HostInfoBase::GetDistributionId () inline static
Returns the distribution id of the host.
This will be something like "ubuntu", "fedora", etc. on Linux.
Returns
Returns either std::nullopt or a reference to a const std::string containing the distribution id
Definition at line 273 of file HostInfoBase.h.
GetGlobalTempDir()
FileSpec HostInfoBase::GetGlobalTempDir () static
Returns the global temporary directory.
This directory will not be cleaned up when this process exits. Only the directory member of the FileSpec is filled in.
Definition at line 211 of file HostInfoBase.cpp.
References g_fields.
GetHeaderDir()
FileSpec HostInfoBase::GetHeaderDir () static
Returns the directory containing the lldb headers.
Only the directory member of the FileSpec is filled in.
Definition at line 146 of file HostInfoBase.cpp.
References g_fields.
GetProcessTempDir()
FileSpec HostInfoBase::GetProcessTempDir () static
Returns the process temporary directory.
This directory will be cleaned up when this process exits. Only the directory member of the FileSpec is filled in.
Definition at line 199 of file HostInfoBase.cpp.
References g_fields.
GetSDKRoot()
llvm::Expected< llvm::StringRef > lldb_private::HostInfoBase::GetSDKRoot (SDKOptions options) inline static
Return the directory containing something like a SDK (reused for Swift).
Definition at line 180 of file HostInfoBase.h.
GetSharedCacheImageInfo() [1/5]
SharedCacheImageInfo lldb_private::HostInfoBase::GetSharedCacheImageInfo (const UUID & uuid, const UUID & sc_uuid, lldb::SymbolSharedCacheUse sc_mode) inline static
Return information about module uuid, if it is loaded in the current process's address space using shared cache sc_uuid.
The shared cache must have been previously indexed.
Parameters
[in] sc_mode Flag to control if this method can try to read a shared cache binary blob directly, needed to keep user settings out of Host.
Definition at line 239 of file HostInfoBase.h.
GetSharedCacheImageInfo() [2/5]
SharedCacheImageInfo lldb_private::HostInfoBase::GetSharedCacheImageInfo (const UUID & uuid, lldb::SymbolSharedCacheUse sc_mode) inline static
Return information about module uuid if it is loaded in the current process's address space.
Parameters
[in] sc_mode Flag to control if this method can try to read a shared cache binary blob directly, needed to keep user settings out of Host.
Definition at line 211 of file HostInfoBase.h.
GetSharedCacheImageInfo() [3/5]
SharedCacheImageInfo lldb_private::HostInfoBase::GetSharedCacheImageInfo (ConstString filepath, const UUID & sc_uuid, lldb::SymbolSharedCacheUse sc_mode) inline static
Return information about module filepath, if it is loaded in the current process's address space using shared cache sc_uuid.
The shared cache must have been previously indexed.
Parameters
[in] sc_mode Flag to control if this method can try to read a shared cache binary blob directly, needed to keep user settings out of Host.
Definition at line 225 of file HostInfoBase.h.
GetSharedCacheImageInfo() [4/5]
SharedCacheImageInfo lldb_private::HostInfoBase::GetSharedCacheImageInfo (ConstString filepath, lldb::SymbolSharedCacheUse sc_mode) inline static
Return information about module filepath if it is loaded in the current process's address space.
Parameters
[in] sc_mode Flag to control if this method can try to read a shared cache binary blob directly, needed to keep user settings out of Host.
Definition at line 198 of file HostInfoBase.h.
GetSharedCacheImageInfo() [5/5]
SharedCacheImageInfo lldb_private::HostInfoBase::GetSharedCacheImageInfo (llvm::StringRef image_name, const UUID & uuid, lldb::SymbolSharedCacheUse sc_mode) inline static
Return information about module image_name if it is loaded in the current process's address space using shared cache uuid.
The shared cache UUID must have been previously indexed.
Parameters
[in] use_sc_binary_directly Flag to control if this method can try to read a shared cache binary blob directly, needed to keep user settings out of Host.
Definition at line 253 of file HostInfoBase.h.
GetShlibDir()
FileSpec HostInfoBase::GetShlibDir () static
Returns the directory containing the lldb shared library.
Only the directory member of the FileSpec is filled in.
Definition at line 126 of file HostInfoBase.cpp.
References g_fields.
Referenced by lldb_private::HostInfoMacOSX::ComputeHeaderDirectory(), ComputePathRelativeToLibrary(), ComputeSupportExeDirectory(), lldb_private::HostInfoMacOSX::ComputeSupportExeDirectory(), and lldb_private::HostInfoMacOSX::ComputeSystemPluginsDirectory().
GetSupportExeDir()
FileSpec HostInfoBase::GetSupportExeDir () static
Returns the directory containing the support executables (debugserver, ...).
Only the directory member of the FileSpec is filled in.
Definition at line 136 of file HostInfoBase.cpp.
References g_fields.
GetSystemPluginDir()
FileSpec HostInfoBase::GetSystemPluginDir () static
Returns the directory containing the system plugins.
Only the directory member of the FileSpec is filled in.
Definition at line 156 of file HostInfoBase.cpp.
References g_fields.
GetTargetTriple()
llvm::Triple HostInfoBase::GetTargetTriple () static
Gets the host target triple.
Returns
The host target triple.
Definition at line 93 of file HostInfoBase.cpp.
References g_fields.
GetUserHomeDir()
FileSpec HostInfoBase::GetUserHomeDir () static
Returns the directory containing the users home (e.g.
~/). Only the directory member of the FileSpec is filled in.
Definition at line 168 of file HostInfoBase.cpp.
References g_fields.
Referenced by ComputeUserLLDBHomeDirectory(), and lldb_private::HostInfoMacOSX::ComputeUserPluginsDirectory().
GetUserLLDBDir()
FileSpec HostInfoBase::GetUserLLDBDir () static
Returns the directory containing the users lldb home (e.g.
~/.lldb/). Only the directory member of the FileSpec is filled in.
Definition at line 178 of file HostInfoBase.cpp.
References g_fields.
GetUserPluginDir()
FileSpec HostInfoBase::GetUserPluginDir () static
Returns the directory containing the user plugins.
Only the directory member of the FileSpec is filled in.
Definition at line 188 of file HostInfoBase.cpp.
References g_fields.
GetXcodeContentsDirectory()
FileSpec lldb_private::HostInfoBase::GetXcodeContentsDirectory () inline static
Definition at line 170 of file HostInfoBase.h.
GetXcodeDeveloperDirectory()
FileSpec lldb_private::HostInfoBase::GetXcodeDeveloperDirectory () inline static
Definition at line 171 of file HostInfoBase.h.
Initialize()
void HostInfoBase::Initialize (SharedLibraryDirectoryHelper * helper = nullptr) static
Definition at line 80 of file HostInfoBase.cpp.
References g_fields, g_shlib_dir_helper, and lldb_private::LogChannelSystem::Initialize().
Referenced by lldb_private::HostInfoAIX::Initialize(), lldb_private::HostInfoLinux::Initialize(), and lldb_private::HostInfoWindows::Initialize().
ParseArchitectureKind()
std::optional< HostInfoBase::ArchitectureKind > HostInfoBase::ParseArchitectureKind (llvm::StringRef kind) static
Definition at line 118 of file HostInfoBase.cpp.
References eArchKind32, eArchKind64, eArchKindDefault, LLDB_ARCH_DEFAULT, LLDB_ARCH_DEFAULT_32BIT, and LLDB_ARCH_DEFAULT_64BIT.
SharedCacheIndexFiles()
bool lldb_private::HostInfoBase::SharedCacheIndexFiles (FileSpec & filepath, UUID & uuid, lldb::SymbolSharedCacheUse sc_mode) inline static
Scan the files in a shared cache, if the filepath and uuid match on the debug host.
Returns false if the shared cache filepath did not exist, or uuid did not match.
Definition at line 262 of file HostInfoBase.h.
Terminate()
void HostInfoBase::Terminate () static
Definition at line 86 of file HostInfoBase.cpp.
References g_fields, g_shlib_dir_helper, and lldb_private::LogChannelSystem::Terminate().
Referenced by lldb_private::HostInfoAIX::Terminate(), lldb_private::HostInfoLinux::Terminate(), and lldb_private::HostInfoWindows::Terminate().
The documentation for this class was generated from the following files:
HostInfoBase.h
HostInfoBase.cpp