LLDB: DynamicLoaderMacOSXDYLD Class Reference
DynamicLoaderMacOSXDYLD Class Reference
#include <DynamicLoaderMacOSXDYLD.h>
Classes
struct DYLDAllImageInfos
Public Member Functions
DynamicLoaderMacOSXDYLD (lldb_private::Process *process)
~DynamicLoaderMacOSXDYLD () override
bool ProcessDidExec () override
Called after attaching a process.
lldb_private::Status CanLoadImage () override
Ask if it is ok to try and load or unload an shared library (image).
bool GetSharedCacheInformation (lldb::addr_t &base_address, lldb_private::UUID &uuid, lldb_private::LazyBool &using_shared_cache, lldb_private::LazyBool &private_shared_cache, lldb_private::FileSpec &shared_cache_filepath) override
Get information about the shared cache for a process, if possible.
llvm::StringRef GetPluginName () override
bool IsFullyInitialized () override
Return whether the dynamic loader is fully initialized and it's safe to call its APIs.
Public Member Functions inherited from lldb_private::DynamicLoaderDarwin
DynamicLoaderDarwin (lldb_private::Process *process)
~DynamicLoaderDarwin () override
void DidAttach () override
Called after attaching a process.
void DidLaunch () override
Called after attaching a process.
lldb::ThreadPlanSP GetStepThroughTrampolinePlan (lldb_private::Thread &thread, bool stop_others) override
Provides a plan to step through the dynamic loader trampoline for the current state of thread.
void FindEquivalentSymbols (const lldb_private::Symbol *original_symbol, lldb_private::ModuleList &module_list, lldb_private::SymbolContextList &equivalent_symbols) override
Some dynamic loaders provide features where there are a group of symbols "equivalent to" a given symbol one of which will be chosen when the symbol is bound.
lldb::addr_t GetThreadLocalData (const lldb::ModuleSP module, const lldb::ThreadSP thread, lldb::addr_t tls_file_addr) override
Retrieves the per-module TLS block for a given thread.
bool AlwaysRelyOnEHUnwindInfo (lldb_private::SymbolContext &sym_ctx) override
Ask if the eh_frame information for the given SymbolContext should be relied on even when it's the first frame in a stack unwind.
std::optional< lldb_private::Address > GetStartAddress () override
Return the start address in the dynamic loader module.
Public Member Functions inherited from lldb_private::DynamicLoader
DynamicLoader (Process *process)
Construct with a process.
bool GetStopWhenImagesChange () const
Get whether the process should stop when images change.
void SetStopWhenImagesChange (bool stop)
Set whether the process should stop when images change.
virtual lldb::ModuleSP LoadModuleAtAddress (const lldb_private::FileSpec &file, lldb::addr_t link_map_addr, lldb::addr_t base_addr, bool base_addr_is_offset)
Locates or creates a module given by file and updates/loads the resulting module at the virtual base address base_addr.
virtual void CalculateDynamicSaveCoreRanges (lldb_private::Process &process, std::vector< lldb_private::MemoryRegionInfo > &ranges, llvm::function_ref< bool(const lldb_private::Thread &)> save_thread_predicate)
Returns a list of memory ranges that should be saved in the core file, specific for this dynamic loader.
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static lldb_private::DynamicLoader * CreateInstance (lldb_private::Process *process, bool force)
Static Public Member Functions inherited from lldb_private::DynamicLoader
static DynamicLoader * FindPlugin (Process *process, llvm::StringRef plugin_name)
Find a dynamic loader plugin for a given process.
static lldb::ModuleSP LoadBinaryWithUUIDAndAddress (Process *process, llvm::StringRef name, UUID uuid, lldb::addr_t value, bool value_is_offset, bool force_symbol_search, bool notify, bool set_address_in_target, bool allow_memory_image_last_resort)
Find/load a binary into lldb given a UUID and the address where it is loaded in memory, or a slide to be applied to the file address.
Protected Member Functions
void PutToLog (lldb_private::Log *log) const
void DoInitialImageFetch () override
bool NeedToDoInitialImageFetch () override
bool DidSetNotificationBreakpoint () override
void DoClear () override
bool ReadDYLDInfoFromMemoryAndSetNotificationCallback (lldb::addr_t addr)
uint32_t AddrByteSize ()
bool ReadMachHeader (lldb::addr_t addr, llvm::MachO::mach_header *header, lldb_private::DataExtractor *load_command_data)
uint32_t ParseLoadCommands (const lldb_private::DataExtractor &data, ImageInfo &dylib_info, lldb_private::FileSpec *lc_id_dylinker)
bool SetNotificationBreakpoint () override
void ClearNotificationBreakpoint () override
bool InitializeFromAllImageInfos ()
bool ReadAllImageInfosStructure ()
bool AddModulesUsingImageInfosAddress (lldb::addr_t image_infos_addr, uint32_t image_infos_count)
bool RemoveModulesUsingImageInfosAddress (lldb::addr_t image_infos_addr, uint32_t image_infos_count)
void UpdateImageInfosHeaderAndLoadCommands (ImageInfo::collection &image_infos, uint32_t infos_count, bool update_executable)
bool ReadImageInfos (lldb::addr_t image_infos_addr, uint32_t image_infos_count, ImageInfo::collection &image_infos)
Protected Member Functions inherited from lldb_private::DynamicLoaderDarwin
void PrivateInitialize (lldb_private::Process *process)
void PrivateProcessStateChanged (lldb_private::Process *process, lldb::StateType state)
void Clear (bool clear_process)
void SetDYLDModule (lldb::ModuleSP &dyld_module_sp)
lldb::ModuleSP GetDYLDModule ()
void ClearDYLDModule ()
bool UpdateImageLoadAddress (lldb_private::Module *module, ImageInfo &info)
bool UnloadModuleSections (lldb_private::Module *module, ImageInfo &info)
lldb::ModuleSP FindTargetModuleForImageInfo (const ImageInfo &image_info, bool can_create, bool *did_create_ptr)
void UnloadImages (const std::vector< lldb::addr_t > &solib_addresses)
void UnloadAllImages ()
std::recursive_mutex & GetMutex () const
lldb::ModuleSP GetPThreadLibraryModule ()
lldb_private::Address GetPthreadSetSpecificAddress ()
bool JSONImageInformationIntoImageInfo (lldb_private::StructuredData::ObjectSP image_details, ImageInfo::collection &image_infos)
std::vector< std::pair< ImageInfo, lldb::ModuleSP > > PreloadModulesFromImageInfos (const ImageInfo::collection &image_infos)
void UpdateSpecialBinariesFromPreloadedModules (std::vector< std::pair< ImageInfo, lldb::ModuleSP > > &images)
bool UpdateDYLDImageInfoFromNewImageInfo (ImageInfo &image_info)
void AddExecutableModuleIfInImageInfos (ImageInfo::collection &image_infos)
bool AddModulesUsingImageInfos (ImageInfo::collection &image_infos)
bool AddModulesUsingPreloadedModules (std::vector< std::pair< ImageInfo, lldb::ModuleSP > > &images)
Protected Member Functions inherited from lldb_private::DynamicLoader
lldb::ModuleSP FindModuleViaTarget (const FileSpec &file)
Find a module in the target that matches the given file.
lldb::ModuleSP GetTargetExecutable ()
Checks to see if the target module has changed, updates the target accordingly and returns the target executable module.
virtual void UpdateLoadedSections (lldb::ModuleSP module, lldb::addr_t link_map_addr, lldb::addr_t base_addr, bool base_addr_is_offset)
Updates the load address of every allocatable section in module.
void UpdateLoadedSectionsCommon (lldb::ModuleSP module, lldb::addr_t base_addr, bool base_addr_is_offset)
virtual void UnloadSections (const lldb::ModuleSP module)
Removes the loaded sections from the target in module.
void UnloadSectionsCommon (const lldb::ModuleSP module)
const lldb_private::SectionList * GetSectionListFromModule (const lldb::ModuleSP module) const
int64_t ReadUnsignedIntWithSizeInBytes (lldb::addr_t addr, int size_in_bytes)
lldb::addr_t ReadPointer (lldb::addr_t addr)
void LoadOperatingSystemPlugin (bool flush)
Static Protected Member Functions
static bool NotifyBreakpointHit (void *baton, lldb_private::StoppointCallbackContext *context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id)
static lldb::ByteOrder GetByteOrderFromMagic (uint32_t magic)
Static Protected Member Functions inherited from lldb_private::DynamicLoaderDarwin
static bool UseDYLDSPI (lldb_private::Process *process)
Protected Attributes
lldb::addr_t m_dyld_all_image_infos_addr
DYLDAllImageInfos m_dyld_all_image_infos
uint32_t m_dyld_all_image_infos_stop_id
lldb::user_id_t m_break_id
std::recursive_mutex m_mutex
bool m_process_image_addr_is_all_images_infos
Protected Attributes inherited from lldb_private::DynamicLoaderDarwin
lldb::ModuleWP m_dyld_module_wp
lldb::ModuleWP m_libpthread_module_wp
lldb_private::Address m_pthread_getspecific_addr
ThreadIDToTLSMap m_tid_to_tls_map
ImageInfo::collection m_dyld_image_infos
uint32_t m_dyld_image_infos_stop_id
ImageInfo m_dyld
std::recursive_mutex m_mutex
Protected Attributes inherited from lldb_private::DynamicLoader
Process * m_process
The process that this dynamic loader plug-in is tracking.
Private Member Functions
DynamicLoaderMacOSXDYLD (const DynamicLoaderMacOSXDYLD &)=delete
const DynamicLoaderMacOSXDYLD & operator= (const DynamicLoaderMacOSXDYLD &)=delete
Additional Inherited Members
Protected Types inherited from lldb_private::DynamicLoaderDarwin
typedef std::map< uint64_t, lldb::addr_t > PthreadKeyToTLSMap
typedef std::map< lldb::user_id_t, PthreadKeyToTLSMap > ThreadIDToTLSMap
Detailed Description
Definition at line 35 of file DynamicLoaderMacOSXDYLD.h.
Constructor & Destructor Documentation
DynamicLoaderMacOSXDYLD() [1/2]
DynamicLoaderMacOSXDYLD::DynamicLoaderMacOSXDYLD (lldb_private::Process * process)
Definition at line 100 of file DynamicLoaderMacOSXDYLD.cpp.
References lldb_private::DynamicLoaderDarwin::DynamicLoaderDarwin(), LLDB_INVALID_ADDRESS, LLDB_INVALID_BREAK_ID, m_break_id, m_dyld_all_image_infos, m_dyld_all_image_infos_addr, m_dyld_all_image_infos_stop_id, m_mutex, m_process_image_addr_is_all_images_infos, and UINT32_MAX.
Referenced by CreateInstance(), DynamicLoaderMacOSXDYLD(), NotifyBreakpointHit(), and operator=().
~DynamicLoaderMacOSXDYLD()
DynamicLoaderMacOSXDYLD::~DynamicLoaderMacOSXDYLD () override
Definition at line 108 of file DynamicLoaderMacOSXDYLD.cpp.
References LLDB_BREAK_ID_IS_VALID, m_break_id, and lldb_private::DynamicLoader::m_process.
DynamicLoaderMacOSXDYLD() [2/2]
DynamicLoaderMacOSXDYLD::DynamicLoaderMacOSXDYLD (const DynamicLoaderMacOSXDYLD &) private delete
References DynamicLoaderMacOSXDYLD().
Member Function Documentation
AddModulesUsingImageInfosAddress()
bool DynamicLoaderMacOSXDYLD::AddModulesUsingImageInfosAddress (lldb::addr_t image_infos_addr, uint32_t image_infos_count) protected
Definition at line 551 of file DynamicLoaderMacOSXDYLD.cpp.
References lldb_private::DynamicLoaderDarwin::AddModulesUsingImageInfos(), lldb_private::DynamicLoaderDarwin::AddModulesUsingPreloadedModules(), lldb_private::DynamicLoader, lldb_private::GetLog(), lldb_private::DynamicLoaderDarwin::GetMutex(), lldb_private::DynamicLoaderDarwin::JSONImageInformationIntoImageInfo(), LLDB_LOGF, lldb_private::DynamicLoaderDarwin::m_dyld_image_infos_stop_id, m_mutex, lldb_private::DynamicLoader::m_process, lldb_private::DynamicLoaderDarwin::PreloadModulesFromImageInfos(), ReadImageInfos(), UpdateImageInfosHeaderAndLoadCommands(), and lldb_private::DynamicLoaderDarwin::UpdateSpecialBinariesFromPreloadedModules().
Referenced by InitializeFromAllImageInfos(), and NotifyBreakpointHit().
AddrByteSize()
uint32_t DynamicLoaderMacOSXDYLD::AddrByteSize () protected
Definition at line 1166 of file DynamicLoaderMacOSXDYLD.cpp.
References lldb_private::DynamicLoaderDarwin::GetMutex(), and lldb_private::DynamicLoaderDarwin::m_dyld.
CanLoadImage()
Status DynamicLoaderMacOSXDYLD::CanLoadImage () override virtual
Ask if it is ok to try and load or unload an shared library (image).
The dynamic loader often knows when it would be ok to try and load or unload a shared library. This function call allows the dynamic loader plug-ins to check any current dyld state to make sure it is an ok time to load a shared library.
Returns
true if it is currently ok to try and load a shared library into the process, false otherwise.
Implements lldb_private::DynamicLoader.
Definition at line 1054 of file DynamicLoaderMacOSXDYLD.cpp.
References error(), lldb_private::Status::FromErrorString(), m_dyld_all_image_infos, and ReadAllImageInfosStructure().
ClearNotificationBreakpoint()
void DynamicLoaderMacOSXDYLD::ClearNotificationBreakpoint () override protected virtual
Implements lldb_private::DynamicLoaderDarwin.
Definition at line 177 of file DynamicLoaderMacOSXDYLD.cpp.
References LLDB_BREAK_ID_IS_VALID, m_break_id, and lldb_private::DynamicLoader::m_process.
CreateInstance()
DynamicLoader * DynamicLoaderMacOSXDYLD::CreateInstance (lldb_private::Process * process, bool force) static
Definition at line 56 of file DynamicLoaderMacOSXDYLD.cpp.
References CreateInstance(), lldb_private::DynamicLoader::DynamicLoader(), DynamicLoaderMacOSXDYLD(), lldb_private::ObjectFile::eStrataUser, lldb_private::Module::GetObjectFile(), lldb_private::ObjectFile::GetStrata(), and lldb_private::DynamicLoaderDarwin::UseDYLDSPI().
Referenced by CreateInstance(), Initialize(), and Terminate().
DidSetNotificationBreakpoint()
bool DynamicLoaderMacOSXDYLD::DidSetNotificationBreakpoint () override protected virtual
Implements lldb_private::DynamicLoaderDarwin.
Definition at line 173 of file DynamicLoaderMacOSXDYLD.cpp.
References LLDB_BREAK_ID_IS_VALID, and m_break_id.
DoClear()
void DynamicLoaderMacOSXDYLD::DoClear () override protected virtual
Implements lldb_private::DynamicLoaderDarwin.
Definition at line 161 of file DynamicLoaderMacOSXDYLD.cpp.
References LLDB_BREAK_ID_IS_VALID, LLDB_INVALID_ADDRESS, LLDB_INVALID_BREAK_ID, m_break_id, m_dyld_all_image_infos, m_dyld_all_image_infos_addr, m_mutex, and lldb_private::DynamicLoader::m_process.
DoInitialImageFetch()
void DynamicLoaderMacOSXDYLD::DoInitialImageFetch () override protected virtual
Implements lldb_private::DynamicLoaderDarwin.
Definition at line 187 of file DynamicLoaderMacOSXDYLD.cpp.
References error(), lldb_private::ArchSpec::GetAddressByteSize(), lldb_private::Module::GetArchitecture(), lldb_private::ArchSpec::GetMachine(), lldb_private::DataExtractor::GetU32(), LLDB_INVALID_ADDRESS, m_dyld_all_image_infos, m_dyld_all_image_infos_addr, lldb_private::DynamicLoader::m_process, m_process_image_addr_is_all_images_infos, ReadAllImageInfosStructure(), and ReadDYLDInfoFromMemoryAndSetNotificationCallback().
GetByteOrderFromMagic()
lldb::ByteOrder DynamicLoaderMacOSXDYLD::GetByteOrderFromMagic (uint32_t magic) static protected
Definition at line 1184 of file DynamicLoaderMacOSXDYLD.cpp.
References lldb::eByteOrderBig, lldb::eByteOrderInvalid, lldb::eByteOrderLittle, and lldb_private::endian::InlHostByteOrder().
Referenced by ReadImageInfos(), and ReadMachHeader().
GetPluginDescriptionStatic()
llvm::StringRef DynamicLoaderMacOSXDYLD::GetPluginDescriptionStatic () static
Definition at line 1161 of file DynamicLoaderMacOSXDYLD.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef DynamicLoaderMacOSXDYLD::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 68 of file DynamicLoaderMacOSXDYLD.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef DynamicLoaderMacOSXDYLD::GetPluginNameStatic () inline static
Definition at line 46 of file DynamicLoaderMacOSXDYLD.h.
Referenced by ProcessMachCore::CleanupMemoryRegionPermissions(), GetPluginName(), Initialize(), ProcessMachCore::LoadBinariesAndSetDYLD(), and ProcessMachCore::LoadBinariesViaMetadata().
GetSharedCacheInformation()
bool DynamicLoaderMacOSXDYLD::GetSharedCacheInformation (lldb::addr_t & base_address, lldb_private::UUID & uuid, lldb_private::LazyBool & using_shared_cache, lldb_private::LazyBool & private_shared_cache, lldb_private::FileSpec & shared_cache_path) override virtual
Get information about the shared cache for a process, if possible.
On some systems (e.g. Darwin based systems), a set of libraries that are common to most processes may be put in a single region of memory and mapped into every process, this is called the shared cache, as a performance optimization.
Many targets will not have the concept of a shared cache.
Depending on how the DynamicLoader gathers information about the shared cache, it may be able to only return basic information - like the UUID of the cache - or it may be able to return additional information about the cache.
Parameters
[out] base_address The base address (load address) of the shared cache. LLDB_INVALID_ADDRESS if it cannot be determined.
[out] uuid The UUID of the shared cache, if it can be determined. If the UUID cannot be fetched, IsValid() will be false.
[out] using_shared_cache If this process is using a shared cache. If unknown, eLazyBoolCalculate is returned.
[out] private_shared_cache A LazyBool indicating whether this process is using a private shared cache. If this information cannot be fetched, eLazyBoolCalculate.
[out] shared_cache_path A FileSpec representing the shared cache path being run in the inferior process.
Returns
Returns false if this DynamicLoader cannot gather information about the shared cache / has no concept of a shared cache.
Reimplemented from lldb_private::DynamicLoader.
Definition at line 1072 of file DynamicLoaderMacOSXDYLD.cpp.
References lldb_private::UUID::Clear(), lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolYes, error(), lldb_private::UUID::IsValid(), LLDB_INVALID_ADDRESS, and lldb_private::DynamicLoader::m_process.
Initialize()
void DynamicLoaderMacOSXDYLD::Initialize () static
Definition at line 1150 of file DynamicLoaderMacOSXDYLD.cpp.
References CreateInstance(), GetPluginDescriptionStatic(), GetPluginNameStatic(), DynamicLoaderMacOS::Initialize(), and lldb_private::PluginManager::RegisterPlugin().
InitializeFromAllImageInfos()
bool DynamicLoaderMacOSXDYLD::InitializeFromAllImageInfos () protected
Definition at line 722 of file DynamicLoaderMacOSXDYLD.cpp.
References AddModulesUsingImageInfosAddress(), lldb_private::ModuleList::Append(), lldb_private::Stream::AsRawOstream(), DEBUG_PRINTF, lldb_private::DynamicLoader, lldb_private::StreamString::GetData(), lldb_private::Target::GetImages(), lldb_private::GetLog(), lldb_private::DynamicLoaderDarwin::GetMutex(), lldb_private::ModuleList::GetSize(), LLDB_LOGF, m_dyld_all_image_infos, lldb_private::DynamicLoaderDarwin::m_dyld_image_infos, lldb_private::DynamicLoaderDarwin::m_dyld_image_infos_stop_id, m_mutex, lldb_private::DynamicLoader::m_process, lldb_private::ModuleList::Modules(), ReadAllImageInfosStructure(), and lldb_private::ModuleList::Remove().
Referenced by NotifyBreakpointHit(), and ReadDYLDInfoFromMemoryAndSetNotificationCallback().
IsFullyInitialized()
bool DynamicLoaderMacOSXDYLD::IsFullyInitialized () override virtual
Return whether the dynamic loader is fully initialized and it's safe to call its APIs.
On some systems (e.g. Darwin based systems), lldb will get notified by the dynamic loader before it itself finished initializing and it's not safe to call certain APIs or SPIs.
Reimplemented from lldb_private::DynamicLoader.
Definition at line 1144 of file DynamicLoaderMacOSXDYLD.cpp.
References m_dyld_all_image_infos, and ReadAllImageInfosStructure().
NeedToDoInitialImageFetch()
bool DynamicLoaderMacOSXDYLD::NeedToDoInitialImageFetch () override protected virtual
Implements lldb_private::DynamicLoaderDarwin.
Definition at line 320 of file DynamicLoaderMacOSXDYLD.cpp.
References LLDB_INVALID_ADDRESS, and m_dyld_all_image_infos_addr.
NotifyBreakpointHit()
bool DynamicLoaderMacOSXDYLD::NotifyBreakpointHit (void * baton, lldb_private::StoppointCallbackContext * context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id) static protected
Definition at line 328 of file DynamicLoaderMacOSXDYLD.cpp.
References AddModulesUsingImageInfosAddress(), DynamicLoaderMacOSXDYLD(), lldb::eBasicTypeVoid, lldb::eEncodingUint, lldb_private::StoppointCallbackContext::exe_ctx_ref, lldb_private::Process::GetABI(), lldb_private::Target::GetArchitecture(), lldb_private::Target::GetDebugger(), lldb_private::ScratchTypeSystemClang::GetForTarget(), lldb_private::UserID::GetID(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::Value::GetScalar(), lldb_private::DynamicLoader::GetStopWhenImagesChange(), lldb_private::Process::GetTarget(), lldb_private::ExecutionContext::GetThreadRef(), lldb_private::ArchSpec::GetTriple(), lldb_private::ValueList::GetValueAtIndex(), InitializeFromAllImageInfos(), lldb_private::DynamicLoader::m_process, lldb_private::ValueList::PushValue(), RemoveModulesUsingImageInfosAddress(), lldb_private::Debugger::ReportWarning(), lldb_private::Value::Scalar, lldb_private::Value::SetCompilerType(), lldb_private::Value::SetValueType(), lldb_private::Scalar::UInt(), and lldb_private::Scalar::ULongLong().
Referenced by SetNotificationBreakpoint().
operator=()
const DynamicLoaderMacOSXDYLD & DynamicLoaderMacOSXDYLD::operator= (const DynamicLoaderMacOSXDYLD &) private delete
References DynamicLoaderMacOSXDYLD().
ParseLoadCommands()
uint32_t DynamicLoaderMacOSXDYLD::ParseLoadCommands (const lldb_private::DataExtractor & data, ImageInfo & dylib_info, lldb_private::FileSpec * lc_id_dylinker) protected
Definition at line 850 of file DynamicLoaderMacOSXDYLD.cpp.
References lldb_private::DynamicLoaderDarwin::ImageInfo::address, lldb_private::DynamicLoaderDarwin::ImageInfo::Clear(), lldb_private::DataExtractor::GetData(), lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU64(), lldb_private::DynamicLoaderDarwin::ImageInfo::header, lldb_private::FileSystem::Instance(), segment::name, lldb_private::DataExtractor::PeekCStr(), lldb_private::FileSystem::Resolve(), lldb_private::DynamicLoaderDarwin::ImageInfo::segments, lldb_private::FileSpec::SetFile(), lldb_private::DynamicLoaderDarwin::ImageInfo::slide, lldb_private::DynamicLoaderDarwin::ImageInfo::uuid, lldb_private::DataExtractor::ValidOffsetForDataOfSize(), segment::vmaddr, and segment::vmsize.
Referenced by ReadDYLDInfoFromMemoryAndSetNotificationCallback(), and UpdateImageInfosHeaderAndLoadCommands().
ProcessDidExec()
bool DynamicLoaderMacOSXDYLD::ProcessDidExec () override virtual
Called after attaching a process.
Allow DynamicLoader plug-ins to execute some code after attaching to a process.
Reimplemented from lldb_private::DynamicLoader.
Definition at line 113 of file DynamicLoaderMacOSXDYLD.cpp.
References lldb_private::DynamicLoaderDarwin::GetMutex(), lldb_private::Symbol::GetName(), lldb_private::DynamicLoaderDarwin::m_dyld, m_dyld_all_image_infos_addr, lldb_private::DynamicLoaderDarwin::m_libpthread_module_wp, lldb_private::DynamicLoader::m_process, m_process_image_addr_is_all_images_infos, and lldb_private::DynamicLoaderDarwin::m_pthread_getspecific_addr.
PutToLog()
void DynamicLoaderMacOSXDYLD::PutToLog (lldb_private::Log * log) const protected
Definition at line 997 of file DynamicLoaderMacOSXDYLD.cpp.
References lldb_private::DynamicLoaderDarwin::GetMutex(), LLDB_LOGF, m_dyld_all_image_infos, lldb_private::DynamicLoaderDarwin::m_dyld_image_infos, m_mutex, lldb_private::Log::PutCString(), and PutToLog().
Referenced by PutToLog().
ReadAllImageInfosStructure()
bool DynamicLoaderMacOSXDYLD::ReadAllImageInfosStructure () protected
Definition at line 430 of file DynamicLoaderMacOSXDYLD.cpp.
References lldb::eByteOrderBig, lldb::eByteOrderLittle, error(), lldb_private::DataExtractor::GetAddress(), lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU8(), LLDB_INVALID_ADDRESS, m_dyld_all_image_infos, m_dyld_all_image_infos_addr, m_dyld_all_image_infos_stop_id, m_mutex, lldb_private::DynamicLoader::m_process, lldb_private::DataExtractor::SetByteOrder(), and UNUSED_IF_ASSERT_DISABLED.
Referenced by CanLoadImage(), DoInitialImageFetch(), InitializeFromAllImageInfos(), and IsFullyInitialized().
ReadDYLDInfoFromMemoryAndSetNotificationCallback()
bool DynamicLoaderMacOSXDYLD::ReadDYLDInfoFromMemoryAndSetNotificationCallback (lldb::addr_t addr) protected
unique!
Definition at line 251 of file DynamicLoaderMacOSXDYLD.cpp.
References lldb_private::ModuleList::Append(), lldb_private::ModuleList::AppendIfNeeded(), lldb::eSymbolTypeData, lldb_private::DynamicLoaderDarwin::GetDYLDModule(), lldb_private::Target::GetImages(), lldb_private::Address::GetLoadAddress(), lldb_private::Symbol::GetLoadAddress(), lldb_private::DynamicLoaderDarwin::GetMutex(), InitializeFromAllImageInfos(), LLDB_INVALID_ADDRESS, lldb_private::DynamicLoaderDarwin::m_dyld, m_dyld_all_image_infos_addr, lldb_private::DynamicLoader::m_process, lldb_private::Target::ModulesDidLoad(), ParseLoadCommands(), ReadMachHeader(), lldb_private::DynamicLoaderDarwin::SetDYLDModule(), and lldb_private::DynamicLoaderDarwin::UpdateDYLDImageInfoFromNewImageInfo().
Referenced by DoInitialImageFetch().
ReadImageInfos()
bool DynamicLoaderMacOSXDYLD::ReadImageInfos (lldb::addr_t image_infos_addr, uint32_t image_infos_count, ImageInfo::collection & image_infos) protected
Definition at line 680 of file DynamicLoaderMacOSXDYLD.cpp.
References error(), lldb_private::DataExtractor::GetAddress(), GetByteOrderFromMagic(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::DataBufferHeap::GetByteSize(), lldb_private::DynamicLoaderDarwin::GetMutex(), lldb_private::DynamicLoaderDarwin::m_dyld, lldb_private::DynamicLoader::m_process, PATH_MAX, and lldb_private::DataExtractor::ValidOffset().
Referenced by AddModulesUsingImageInfosAddress(), and RemoveModulesUsingImageInfosAddress().
ReadMachHeader()
bool DynamicLoaderMacOSXDYLD::ReadMachHeader (lldb::addr_t addr, llvm::MachO::mach_header * header, lldb_private::DataExtractor * load_command_data) protected
Definition at line 782 of file DynamicLoaderMacOSXDYLD.cpp.
References error(), lldb_private::DataExtractor::GetAddressByteSize(), lldb_private::DataExtractor::GetByteOrder(), GetByteOrderFromMagic(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::DataBufferHeap::GetByteSize(), lldb_private::DataExtractor::GetU32(), lldb_private::endian::InlHostByteOrder(), lldb_private::DynamicLoader::m_process, lldb_private::DataExtractor::SetAddressByteSize(), lldb_private::DataExtractor::SetByteOrder(), and lldb_private::DataExtractor::SetData().
Referenced by ReadDYLDInfoFromMemoryAndSetNotificationCallback(), and UpdateImageInfosHeaderAndLoadCommands().
RemoveModulesUsingImageInfosAddress()
bool DynamicLoaderMacOSXDYLD::RemoveModulesUsingImageInfosAddress (lldb::addr_t image_infos_addr, uint32_t image_infos_count) protected
Definition at line 593 of file DynamicLoaderMacOSXDYLD.cpp.
References lldb_private::ModuleList::AppendIfNeeded(), lldb_private::DynamicLoader, lldb_private::DynamicLoaderDarwin::FindTargetModuleForImageInfo(), lldb_private::GetLog(), lldb_private::DynamicLoaderDarwin::GetMutex(), lldb_private::ModuleList::GetSize(), LLDB_LOGF, lldb_private::ModuleList::LogUUIDAndPaths(), lldb_private::DynamicLoaderDarwin::m_dyld_image_infos, lldb_private::DynamicLoaderDarwin::m_dyld_image_infos_stop_id, m_mutex, lldb_private::DynamicLoader::m_process, lldb_private::Log::PutCString(), ReadImageInfos(), and lldb_private::DynamicLoaderDarwin::UnloadModuleSections().
Referenced by NotifyBreakpointHit().
SetNotificationBreakpoint()
bool DynamicLoaderMacOSXDYLD::SetNotificationBreakpoint () override protected virtual
Implements lldb_private::DynamicLoaderDarwin.
Definition at line 1019 of file DynamicLoaderMacOSXDYLD.cpp.
References DEBUG_PRINTF, lldb_private::DynamicLoaderDarwin::GetDYLDModule(), lldb_private::Stoppoint::GetID(), lldb_private::DynamicLoaderDarwin::GetMutex(), LLDB_INVALID_ADDRESS, LLDB_INVALID_BREAK_ID, m_break_id, lldb_private::DynamicLoaderDarwin::m_dyld, m_dyld_all_image_infos, lldb_private::DynamicLoader::m_process, NotifyBreakpointHit(), lldb_private::Breakpoint::SetBreakpointKind(), lldb_private::Breakpoint::SetCallback(), lldb_private::StateAsCString(), and lldb_private::DynamicLoaderDarwin::UpdateImageLoadAddress().
Terminate()
void DynamicLoaderMacOSXDYLD::Terminate () static
Definition at line 1156 of file DynamicLoaderMacOSXDYLD.cpp.
References CreateInstance(), DynamicLoaderMacOS::Terminate(), and lldb_private::PluginManager::UnregisterPlugin().
UpdateImageInfosHeaderAndLoadCommands()
void DynamicLoaderMacOSXDYLD::UpdateImageInfosHeaderAndLoadCommands (ImageInfo::collection & image_infos, uint32_t infos_count, bool update_executable) protected
Definition at line 939 of file DynamicLoaderMacOSXDYLD.cpp.
References lldb_private::ModuleList::AppendIfNeeded(), lldb_private::eLoadDependentsNo, lldb_private::DynamicLoaderDarwin::FindTargetModuleForImageInfo(), lldb_private::DynamicLoaderDarwin::GetDYLDModule(), lldb_private::Target::GetExecutableModulePointer(), lldb_private::Target::GetImages(), lldb_private::DynamicLoaderDarwin::GetMutex(), lldb_private::DynamicLoaderDarwin::m_dyld, lldb_private::DynamicLoader::m_process, ParseLoadCommands(), ReadMachHeader(), UINT32_MAX, and lldb_private::DynamicLoaderDarwin::UpdateImageLoadAddress().
Referenced by AddModulesUsingImageInfosAddress().
Member Data Documentation
m_break_id
lldb::user_id_t DynamicLoaderMacOSXDYLD::m_break_id protected
Definition at line 163 of file DynamicLoaderMacOSXDYLD.h.
Referenced by ClearNotificationBreakpoint(), DidSetNotificationBreakpoint(), DoClear(), DynamicLoaderMacOSXDYLD(), SetNotificationBreakpoint(), and ~DynamicLoaderMacOSXDYLD().
m_dyld_all_image_infos
DYLDAllImageInfos DynamicLoaderMacOSXDYLD::m_dyld_all_image_infos protected
Definition at line 161 of file DynamicLoaderMacOSXDYLD.h.
Referenced by CanLoadImage(), DoClear(), DoInitialImageFetch(), DynamicLoaderMacOSXDYLD(), InitializeFromAllImageInfos(), IsFullyInitialized(), PutToLog(), ReadAllImageInfosStructure(), and SetNotificationBreakpoint().
m_dyld_all_image_infos_addr
lldb::addr_t DynamicLoaderMacOSXDYLD::m_dyld_all_image_infos_addr protected
Definition at line 160 of file DynamicLoaderMacOSXDYLD.h.
Referenced by DoClear(), DoInitialImageFetch(), DynamicLoaderMacOSXDYLD(), NeedToDoInitialImageFetch(), ProcessDidExec(), ReadAllImageInfosStructure(), and ReadDYLDInfoFromMemoryAndSetNotificationCallback().
m_dyld_all_image_infos_stop_id
uint32_t DynamicLoaderMacOSXDYLD::m_dyld_all_image_infos_stop_id protected
Definition at line 162 of file DynamicLoaderMacOSXDYLD.h.
Referenced by DynamicLoaderMacOSXDYLD(), and ReadAllImageInfosStructure().
m_mutex
std::recursive_mutex DynamicLoaderMacOSXDYLD::m_mutex mutable protected
Definition at line 164 of file DynamicLoaderMacOSXDYLD.h.
Referenced by AddModulesUsingImageInfosAddress(), DoClear(), DynamicLoaderMacOSXDYLD(), InitializeFromAllImageInfos(), PutToLog(), ReadAllImageInfosStructure(), and RemoveModulesUsingImageInfosAddress().
m_process_image_addr_is_all_images_infos
bool DynamicLoaderMacOSXDYLD::m_process_image_addr_is_all_images_infos protected
Definition at line 165 of file DynamicLoaderMacOSXDYLD.h.
Referenced by DoInitialImageFetch(), DynamicLoaderMacOSXDYLD(), and ProcessDidExec().
The documentation for this class was generated from the following files:
DynamicLoaderMacOSXDYLD.h
DynamicLoaderMacOSXDYLD.cpp