LLDB: lldb_private::TypeFormatImpl_Format Class Reference
lldb_private::TypeFormatImpl_Format Class Reference
#include <TypeFormat.h>
Public Types
typedef std::shared_ptr< TypeFormatImpl_Format > SharedPointer
Public Types inherited from lldb_private::TypeFormatImpl
enum class Type { eTypeUnknown , eTypeFormat , eTypeEnum }
typedef std::shared_ptr< TypeFormatImpl > SharedPointer
Public Member Functions
TypeFormatImpl_Format (lldb::Format f=lldb::eFormatInvalid, const TypeFormatImpl::Flags &flags=Flags())
~TypeFormatImpl_Format () override
lldb::Format GetFormat () const
void SetFormat (lldb::Format fmt)
TypeFormatImpl::Type GetType () override
bool FormatObject (ValueObject *valobj, std::string &dest) const override
std::string GetDescription () override
Public Member Functions inherited from lldb_private::TypeFormatImpl
TypeFormatImpl (const Flags &flags=Flags())
virtual ~TypeFormatImpl ()
bool Cascades () const
bool SkipsPointers () const
bool SkipsReferences () const
bool NonCacheable () const
void SetCascades (bool value)
void SetSkipsPointers (bool value)
void SetSkipsReferences (bool value)
void SetNonCacheable (bool value)
uint32_t GetOptions ()
void SetOptions (uint32_t value)
uint32_t GetPtrMatchDepth ()
void SetPtrMatchDepth (uint32_t value)
uint32_t & GetRevision ()
Protected Attributes
lldb::Format m_format
Protected Attributes inherited from lldb_private::TypeFormatImpl
Flags m_flags
uint32_t m_my_revision = 0
uint32_t m_ptr_match_depth = 1
Private Member Functions
TypeFormatImpl_Format (const TypeFormatImpl_Format &)=delete
const TypeFormatImpl_Format & operator= (const TypeFormatImpl_Format &)=delete
Detailed Description
Definition at line 164 of file TypeFormat.h.
Member Typedef Documentation
SharedPointer
typedef std::shared_ptr<TypeFormatImpl_Format> lldb_private::TypeFormatImpl_Format::SharedPointer
Definition at line 169 of file TypeFormat.h.
Constructor & Destructor Documentation
TypeFormatImpl_Format() [1/2]
TypeFormatImpl_Format::TypeFormatImpl_Format (lldb::Format f = lldb::eFormatInvalid, const TypeFormatImpl::Flags & flags = Flags())
Definition at line 35 of file TypeFormat.cpp.
References m_format, and lldb_private::TypeFormatImpl::TypeFormatImpl().
Referenced by operator=(), and TypeFormatImpl_Format().
~TypeFormatImpl_Format()
TypeFormatImpl_Format::~TypeFormatImpl_Format () override default
TypeFormatImpl_Format() [2/2]
lldb_private::TypeFormatImpl_Format::TypeFormatImpl_Format (const TypeFormatImpl_Format &) private delete
References TypeFormatImpl_Format().
Member Function Documentation
FormatObject()
bool TypeFormatImpl_Format::FormatObject (ValueObject * valobj, std::string & dest) const override virtual
Implements lldb_private::TypeFormatImpl.
Definition at line 41 of file TypeFormat.cpp.
References lldb_private::ValueObject::AddrAndType::address, lldb_private::RegisterInfo::byte_size, lldb_private::ValueObject::CanProvideValue(), lldb_private::DumpDataExtractor(), lldb_private::CompilerType::DumpTypeValue(), lldb::eFormatCString, error(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::ValueObject::GetBitfieldBitOffset(), lldb_private::ValueObject::GetBitfieldBitSize(), lldb_private::CompilerType::GetByteSize(), lldb_private::Value::GetCompilerType(), lldb_private::Value::GetContextType(), lldb_private::ValueObject::GetData(), lldb_private::ValueObject::GetExecutionContextRef(), GetFormat(), lldb_private::GetLog(), lldb_private::ValueObject::GetPointerValue(), lldb_private::Value::GetRegisterInfo(), lldb_private::StreamString::GetString(), lldb_private::ValueObject::GetTargetSP(), lldb_private::CompilerType::GetTypeInfo(), lldb_private::ValueObject::GetValue(), LLDB_INVALID_ADDRESS, LLDB_LOG_ERRORV, lldb_private::Value::RegisterInfo, lldb_private::DataExtractor::SetData(), lldb_private::Flags::Test(), lldb_private::Types, and UINT32_MAX.
GetDescription()
std::string TypeFormatImpl_Format::GetDescription () override virtual
Implements lldb_private::TypeFormatImpl.
Definition at line 130 of file TypeFormat.cpp.
References lldb_private::TypeFormatImpl::Cascades(), GetFormat(), lldb_private::FormatManager::GetFormatAsCString(), lldb_private::StreamString::GetString(), lldb_private::Stream::Printf(), lldb_private::TypeFormatImpl::SkipsPointers(), and lldb_private::TypeFormatImpl::SkipsReferences().
GetFormat()
lldb::Format lldb_private::TypeFormatImpl_Format::GetFormat () const inline
Definition at line 173 of file TypeFormat.h.
References m_format.
Referenced by FormatObject(), and GetDescription().
GetType()
TypeFormatImpl::Type lldb_private::TypeFormatImpl_Format::GetType () inline override virtual
Reimplemented from lldb_private::TypeFormatImpl.
Definition at line 177 of file TypeFormat.h.
References lldb_private::TypeFormatImpl::eTypeFormat.
operator=()
const TypeFormatImpl_Format & lldb_private::TypeFormatImpl_Format::operator= (const TypeFormatImpl_Format &) private delete
References TypeFormatImpl_Format().
SetFormat()
void lldb_private::TypeFormatImpl_Format::SetFormat (lldb::Format fmt) inline
Definition at line 175 of file TypeFormat.h.
References m_format.
Member Data Documentation
m_format
lldb::Format lldb_private::TypeFormatImpl_Format::m_format protected
Definition at line 186 of file TypeFormat.h.
Referenced by GetFormat(), SetFormat(), and TypeFormatImpl_Format().
The documentation for this class was generated from the following files:
TypeFormat.h
TypeFormat.cpp