LLDB: lldb_private::mcp::CommandTool Class Reference
lldb_private::mcp::CommandTool Class Reference
#include <Tool.h>
Public Member Functions
~CommandTool ()=default
llvm::Expected< lldb_protocol::mcp::CallToolResult > Call (const lldb_protocol::mcp::ToolArguments &args) override
std::optional< llvm::json::Value > GetSchema () const override
Tool (std::string name, std::string description)
Public Member Functions inherited from lldb_protocol::mcp::Tool
Tool (std::string name, std::string description)
virtual ~Tool ()=default
lldb_protocol::mcp::ToolDefinition GetDefinition () const
const std::string & GetName ()
Detailed Description
Definition at line 20 of file source/Plugins/Protocol/MCP/Tool.h.
Constructor & Destructor Documentation
~CommandTool()
lldb_private::mcp::CommandTool::~CommandTool () default
Member Function Documentation
Call()
Expected< lldb_protocol::mcp::CallToolResult > CommandTool::Call (const lldb_protocol::mcp::ToolArguments & args) override virtual
Implements lldb_protocol::mcp::Tool.
Definition at line 59 of file Plugins/Protocol/MCP/Tool.cpp.
References createStringError(), lldb_private::eLazyBoolYes, lldb_private::Debugger::FindDebuggerWithID(), lldb_private::fromJSON(), lldb_private::Debugger::GetDebuggerAtIndex(), lldb_private::CommandReturnObject::GetErrorString(), lldb_private::Debugger::GetNumDebuggers(), lldb_private::CommandReturnObject::GetOutputString(), and lldb_private::CommandReturnObject::Succeeded().
GetSchema()
std::optional< json::Value > CommandTool::GetSchema () const override virtual
Reimplemented from lldb_protocol::mcp::Tool.
Definition at line 111 of file Plugins/Protocol/MCP/Tool.cpp.
References lldb_private::Object.
Tool()
Tool::Tool (std::string name, std::string description)
Definition at line 21 of file Protocol/MCP/Tool.cpp.
The documentation for this class was generated from the following files:
source/Plugins/Protocol/MCP/Tool.h
Plugins/Protocol/MCP/Tool.cpp