LLDB: EntitySymbol Class Reference
EntitySymbol Class Reference
Public Member Functions
EntitySymbol (const Symbol &symbol)
void Materialize (lldb::StackFrameSP &frame_sp, IRMemoryMap &map, lldb::addr_t process_address, Status &err) override
void Dematerialize (lldb::StackFrameSP &frame_sp, IRMemoryMap &map, lldb::addr_t process_address, lldb::addr_t frame_top, lldb::addr_t frame_bottom, Status &err) override
void DumpToLog (IRMemoryMap &map, lldb::addr_t process_address, Log *log) override
void Wipe (IRMemoryMap &map, lldb::addr_t process_address) override
Public Member Functions inherited from lldb_private::Materializer::Entity
Entity ()=default
virtual ~Entity ()=default
uint32_t GetAlignment ()
uint32_t GetSize ()
uint32_t GetOffset ()
void SetOffset (uint32_t offset)
Private Attributes
Symbol m_symbol
Additional Inherited Members
Protected Attributes inherited from lldb_private::Materializer::Entity
uint32_t m_alignment = 1
uint32_t m_size = 0
uint32_t m_offset = 0
Detailed Description
Definition at line 1223 of file Materializer.cpp.
Constructor & Destructor Documentation
EntitySymbol()
EntitySymbol::EntitySymbol (const Symbol & symbol) inline
Definition at line 1225 of file Materializer.cpp.
References lldb_private::Materializer::Entity::Entity(), g_default_var_alignment, g_default_var_byte_size, lldb_private::Materializer::Entity::m_alignment, lldb_private::Materializer::Entity::m_size, and m_symbol.
Member Function Documentation
Dematerialize()
void EntitySymbol::Dematerialize (lldb::StackFrameSP & frame_sp, IRMemoryMap & map, lldb::addr_t process_address, lldb::addr_t frame_top, lldb::addr_t frame_bottom, Status & err) inline override virtual
Implements lldb_private::Materializer::Entity.
Definition at line 1279 of file Materializer.cpp.
References lldb_private::Expressions, lldb_private::GetLog(), LLDB_LOGF, lldb_private::Materializer::Entity::m_offset, and m_symbol.
DumpToLog()
void EntitySymbol::DumpToLog (IRMemoryMap & map, lldb::addr_t process_address, Log * log) inline override virtual
Implements lldb_private::Materializer::Entity.
Definition at line 1296 of file Materializer.cpp.
References lldb_private::DumpHexBytes(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::DataBufferHeap::GetByteSize(), lldb_private::StreamString::GetString(), lldb_private::Materializer::Entity::m_offset, lldb_private::Materializer::Entity::m_size, m_symbol, lldb_private::Stream::Printf(), lldb_private::Stream::PutChar(), lldb_private::Log::PutString(), lldb_private::IRMemoryMap::ReadMemory(), and lldb_private::Status::Success().
Materialize()
void EntitySymbol::Materialize (lldb::StackFrameSP & frame_sp, IRMemoryMap & map, lldb::addr_t process_address, Status & err) inline override virtual
Implements lldb_private::Materializer::Entity.
Definition at line 1231 of file Materializer.cpp.
References lldb_private::Status::AsCString(), lldb_private::ExecutionContextScope::CalculateTarget(), lldb_private::Expressions, lldb_private::Status::FromErrorStringWithFormat(), lldb_private::IRMemoryMap::GetBestExecutionContextScope(), lldb_private::Address::GetFileAddress(), lldb_private::Address::GetLoadAddress(), lldb_private::GetLog(), LLDB_INVALID_ADDRESS, LLDB_LOGF, lldb_private::Materializer::Entity::m_offset, m_symbol, lldb_private::Status::Success(), and lldb_private::IRMemoryMap::WritePointerToMemory().
Wipe()
void EntitySymbol::Wipe (IRMemoryMap & map, lldb::addr_t process_address) inline override virtual
Implements lldb_private::Materializer::Entity.
Definition at line 1327 of file Materializer.cpp.
Member Data Documentation
m_symbol
Symbol EntitySymbol::m_symbol private
Definition at line 1330 of file Materializer.cpp.
Referenced by Dematerialize(), DumpToLog(), EntitySymbol(), and Materialize().
The documentation for this class was generated from the following file:
Materializer.cpp