LLDB: sddarwinlog_private::ExactMatchFilterRule Class Reference
sddarwinlog_private::ExactMatchFilterRule Class Reference
Public Member Functions
void Dump (Stream &stream) const override
Public Member Functions inherited from sddarwinlog_private::FilterRule
virtual ~FilterRule ()=default
StructuredData::ObjectSP Serialize () const
llvm::StringRef GetOperationType () const
Static Public Member Functions
static void RegisterOperation ()
Static Public Member Functions inherited from sddarwinlog_private::FilterRule
static void RegisterOperation (llvm::StringRef operation, const OperationCreationFunc &creation_func)
static FilterRuleSP CreateRule (bool match_accepts, size_t attribute, llvm::StringRef operation, const std::string &op_arg, Status &error)
Protected Member Functions
void DoSerialization (StructuredData::Dictionary &dict) const override
Protected Member Functions inherited from sddarwinlog_private::FilterRule
FilterRule (bool accept, size_t attribute_index, llvm::StringRef operation)
bool GetMatchAccepts () const
const char * GetFilterAttribute () const
Private Member Functions
ExactMatchFilterRule (bool accept, size_t attribute_index, const std::string &match_text)
Static Private Member Functions
static FilterRuleSP CreateOperation (bool accept, size_t attribute_index, const std::string &op_arg, Status &error)
static llvm::StringRef StaticGetOperation ()
Private Attributes
const std::string m_match_text
Additional Inherited Members
Public Types inherited from sddarwinlog_private::FilterRule
using OperationCreationFunc
Detailed Description
Definition at line 314 of file StructuredDataDarwinLog.cpp.
Constructor & Destructor Documentation
ExactMatchFilterRule()
sddarwinlog_private::ExactMatchFilterRule::ExactMatchFilterRule (bool accept, size_t attribute_index, const std::string & match_text) inline private
Definition at line 351 of file StructuredDataDarwinLog.cpp.
References sddarwinlog_private::FilterRule::FilterRule(), m_match_text, and StaticGetOperation().
Referenced by CreateOperation().
Member Function Documentation
CreateOperation()
FilterRuleSP sddarwinlog_private::ExactMatchFilterRule::CreateOperation (bool accept, size_t attribute_index, const std::string & op_arg, Status & error) inline static private
Definition at line 331 of file StructuredDataDarwinLog.cpp.
References error(), ExactMatchFilterRule(), and lldb_private::Status::FromErrorString().
Referenced by RegisterOperation().
DoSerialization()
void sddarwinlog_private::ExactMatchFilterRule::DoSerialization (StructuredData::Dictionary & dict) const inline override protected virtual
Implements sddarwinlog_private::FilterRule.
Definition at line 326 of file StructuredDataDarwinLog.cpp.
References lldb_private::StructuredData::Dictionary::AddStringItem(), and m_match_text.
Dump()
void sddarwinlog_private::ExactMatchFilterRule::Dump (Stream & stream) const inline override virtual
Implements sddarwinlog_private::FilterRule.
Definition at line 320 of file StructuredDataDarwinLog.cpp.
References sddarwinlog_private::FilterRule::GetFilterAttribute(), sddarwinlog_private::FilterRule::GetMatchAccepts(), m_match_text, and lldb_private::Stream::Printf().
RegisterOperation()
void sddarwinlog_private::ExactMatchFilterRule::RegisterOperation () inline static
Definition at line 316 of file StructuredDataDarwinLog.cpp.
References CreateOperation(), sddarwinlog_private::FilterRule::RegisterOperation(), and StaticGetOperation().
Referenced by sddarwinlog_private::RegisterFilterOperations().
StaticGetOperation()
llvm::StringRef sddarwinlog_private::ExactMatchFilterRule::StaticGetOperation () inline static private
Definition at line 346 of file StructuredDataDarwinLog.cpp.
Referenced by ExactMatchFilterRule(), and RegisterOperation().
Member Data Documentation
m_match_text
const std::string sddarwinlog_private::ExactMatchFilterRule::m_match_text private
Definition at line 356 of file StructuredDataDarwinLog.cpp.
Referenced by DoSerialization(), Dump(), and ExactMatchFilterRule().
The documentation for this class was generated from the following file:
StructuredDataDarwinLog.cpp