LLDB: lldb_private::OptionParser Class Reference
lldb_private::OptionParser Class Reference
#include <OptionParser.h>
Public Types
enum OptionArgument { eNoArgument = 0 , eRequiredArgument , eOptionalArgument }
Static Public Member Functions
static void Prepare (std::unique_lock< std::mutex > &lock)
static void EnableError (bool error)
static int Parse (llvm::MutableArrayRef< char * > argv, llvm::StringRef optstring, const Option *longopts, int *longindex)
Argv must be an argument vector "as passed to main", i.e.
static char * GetOptionArgument ()
static int GetOptionIndex ()
static int GetOptionErrorCause ()
static std::string GetShortOptionString (struct option *long_options)
Detailed Description
Definition at line 33 of file OptionParser.h.
Member Enumeration Documentation
OptionArgument
enum lldb_private::OptionParser::OptionArgument
Enumerator
eNoArgument
eRequiredArgument
eOptionalArgument
Definition at line 35 of file OptionParser.h.
Member Function Documentation
EnableError()
void OptionParser::EnableError (bool error) static
Definition at line 29 of file OptionParser.cpp.
References error().
Referenced by lldb_private::Options::ParseForCompletion().
GetOptionArgument()
char * OptionParser::GetOptionArgument () static
Definition at line 50 of file OptionParser.cpp.
Referenced by lldb_private::Options::Parse(), lldb_private::Options::ParseAlias(), and lldb_private::Options::ParseForCompletion().
GetOptionErrorCause()
int OptionParser::GetOptionErrorCause () static
Definition at line 54 of file OptionParser.cpp.
Referenced by lldb_private::Options::ParseForCompletion().
GetOptionIndex()
int OptionParser::GetOptionIndex () static
Definition at line 52 of file OptionParser.cpp.
Referenced by lldb_private::Options::Parse(), and lldb_private::Options::ParseForCompletion().
GetShortOptionString()
std::string OptionParser::GetShortOptionString (struct option * long_options) static
Definition at line 56 of file OptionParser.cpp.
Parse()
int OptionParser::Parse (llvm::MutableArrayRef< char * > argv, llvm::StringRef optstring, const Option * longopts, int * longindex) static
Argv must be an argument vector "as passed to main", i.e.
terminated with a nullptr.
Definition at line 31 of file OptionParser.cpp.
References lldb_private::Option::definition, lldb_private::Option::flag, lldb_private::OptionDefinition::long_option, lldb_private::OptionDefinition::option_has_arg, and lldb_private::Option::val.
Referenced by lldb_private::Options::Parse(), lldb_private::Options::ParseAlias(), and lldb_private::Options::ParseForCompletion().
Prepare()
void OptionParser::Prepare (std::unique_lock< std::mutex > & lock) static
Definition at line 18 of file OptionParser.cpp.
Referenced by lldb_private::Options::Parse(), lldb_private::Options::ParseAlias(), and lldb_private::Options::ParseForCompletion().
The documentation for this class was generated from the following files:
OptionParser.h
OptionParser.cpp