LLDB: lldb_private::SymbolLocatorDefault Class Reference
lldb_private::SymbolLocatorDefault Class Reference
#include <SymbolLocatorDefault.h>
Public Member Functions
SymbolLocatorDefault ()
llvm::StringRef GetPluginName () override
PluginInterface protocol.
Public Member Functions inherited from lldb_private::SymbolLocator
SymbolLocator ()=default
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static lldb_private::SymbolLocator * CreateInstance ()
static std::optional< ModuleSpec > LocateExecutableObjectFile (const ModuleSpec &module_spec)
static std::optional< FileSpec > LocateExecutableSymbolFile (const ModuleSpec &module_spec, const FileSpecList &default_search_paths)
static bool DownloadObjectAndSymbolFile (ModuleSpec &module_spec, Status &error, bool force_lookup, bool copy_executable)
Static Public Member Functions inherited from lldb_private::SymbolLocator
static void DownloadSymbolFileAsync (const UUID &uuid)
Locate the symbol file for the given UUID on a background thread.
Detailed Description
Definition at line 17 of file SymbolLocatorDefault.h.
Constructor & Destructor Documentation
SymbolLocatorDefault()
SymbolLocatorDefault::SymbolLocatorDefault ()
Definition at line 52 of file SymbolLocatorDefault.cpp.
References lldb_private::SymbolLocator::SymbolLocator(), and SymbolLocatorDefault().
Referenced by CreateInstance(), and SymbolLocatorDefault().
Member Function Documentation
CreateInstance()
SymbolLocator * SymbolLocatorDefault::CreateInstance () static
Definition at line 69 of file SymbolLocatorDefault.cpp.
References lldb_private::SymbolLocator::SymbolLocator(), and SymbolLocatorDefault().
Referenced by Initialize(), and Terminate().
DownloadObjectAndSymbolFile()
bool SymbolLocatorDefault::DownloadObjectAndSymbolFile (ModuleSpec & module_spec, Status & error, bool force_lookup, bool copy_executable) static
Definition at line 256 of file SymbolLocatorDefault.cpp.
References error().
Referenced by Initialize().
GetPluginDescriptionStatic()
llvm::StringRef SymbolLocatorDefault::GetPluginDescriptionStatic () static
Definition at line 65 of file SymbolLocatorDefault.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef lldb_private::SymbolLocatorDefault::GetPluginName () inline override virtual
PluginInterface protocol.
Implements lldb_private::PluginInterface.
Definition at line 31 of file SymbolLocatorDefault.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::SymbolLocatorDefault::GetPluginNameStatic () inline static
Definition at line 24 of file SymbolLocatorDefault.h.
Referenced by GetPluginName(), and Initialize().
Initialize()
void SymbolLocatorDefault::Initialize () static
Definition at line 54 of file SymbolLocatorDefault.cpp.
References CreateInstance(), DownloadObjectAndSymbolFile(), GetPluginDescriptionStatic(), GetPluginNameStatic(), LocateExecutableObjectFile(), LocateExecutableSymbolFile(), and lldb_private::PluginManager::RegisterPlugin().
LocateExecutableObjectFile()
std::optional< ModuleSpec > SymbolLocatorDefault::LocateExecutableObjectFile (const ModuleSpec & module_spec) static
Definition at line 73 of file SymbolLocatorDefault.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::ModuleSpecList::FindMatchingModuleSpec(), lldb_private::ArchSpec::GetArchitectureName(), lldb_private::ModuleSpec::GetArchitecturePtr(), lldb_private::FileSpec::GetFilename(), lldb_private::ModuleSpec::GetFileSpec(), lldb_private::ObjectFile::GetModuleSpecifications(), lldb_private::ModuleSpec::GetUUIDPtr(), and LLDB_SCOPED_TIMERF.
Referenced by Initialize().
LocateExecutableSymbolFile()
std::optional< FileSpec > SymbolLocatorDefault::LocateExecutableSymbolFile (const ModuleSpec & module_spec, const FileSpecList & default_search_paths) static
Definition at line 97 of file SymbolLocatorDefault.cpp.
References lldb_private::FileSpecList::AppendIfUnique(), lldb_private::ConstString::AsCString(), lldb_private::ModuleSpec::GetArchitecture(), lldb_private::UUID::GetAsString(), lldb_private::ConstString::GetCString(), lldb_private::FileSpec::GetDirectory(), lldb_private::FileSpec::GetFilename(), lldb_private::ModuleSpec::GetFileSpec(), lldb_private::FileSpecList::GetFileSpecAtIndex(), lldb_private::ModuleList::GetGlobalModuleListProperties(), lldb_private::ModuleSpecList::GetModuleSpecAtIndex(), lldb_private::ObjectFile::GetModuleSpecifications(), lldb_private::FileSpec::GetPath(), lldb_private::FileSpecList::GetSize(), lldb_private::ModuleSpec::GetSymbolFileSpec(), lldb_private::ArchSpec::GetTriple(), lldb_private::ModuleSpec::GetUUID(), lldb_private::FileSystem::Instance(), lldb_private::FileSpec::IsAbsolute(), lldb_private::ConstString::IsEmpty(), lldb_private::UUID::IsValid(), PATH_MAX, lldb_private::FileSpec::PrependPathComponent(), lldb_private::FileSystem::Resolve(), and lldb_private::FileSystem::ResolveSymbolicLink().
Referenced by Initialize().
Terminate()
void SymbolLocatorDefault::Terminate () static
Definition at line 61 of file SymbolLocatorDefault.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
The documentation for this class was generated from the following files:
SymbolLocatorDefault.h
SymbolLocatorDefault.cpp