LLDB: lldb_private::OperatingSystem Class Reference
lldb_private::OperatingSystem Class Reference abstract
A plug-in interface definition class for halted OS helpers.
#include "lldb/Target/OperatingSystem.h"
Public Member Functions
OperatingSystem (Process *process)
virtual bool UpdateThreadList (ThreadList &old_thread_list, ThreadList &real_thread_list, ThreadList &new_thread_list)=0
virtual void ThreadWasSelected (Thread *thread)=0
virtual lldb::RegisterContextSP CreateRegisterContextForThread (Thread *thread, lldb::addr_t reg_data_addr)=0
virtual lldb::StopInfoSP CreateThreadStopReason (Thread *thread)=0
virtual lldb::ThreadSP CreateThread (lldb::tid_t tid, lldb::addr_t context)
virtual bool IsOperatingSystemPluginThread (const lldb::ThreadSP &thread_sp)
virtual bool DoesPluginReportAllThreads ()=0
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
virtual llvm::StringRef GetPluginName ()=0
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static OperatingSystem * FindPlugin (Process *process, const char *plugin_name)
Find a halted OS plugin for a given process.
Protected Attributes
Process * m_process
The process that this dynamic loader plug-in is tracking.
Detailed Description
A plug-in interface definition class for halted OS helpers.
Halted OS plug-ins can be used by any process to locate and create OS objects, like threads, during the lifetime of a debug session. This is commonly used when attaching to an operating system that is halted, such as when debugging over JTAG or connecting to low level kernel debug services.
Definition at line 27 of file OperatingSystem.h.
Constructor & Destructor Documentation
OperatingSystem()
OperatingSystem::OperatingSystem (Process * process)
Definition at line 44 of file OperatingSystem.cpp.
References m_process.
Referenced by FindPlugin().
Member Function Documentation
CreateRegisterContextForThread()
virtual lldb::RegisterContextSP lldb_private::OperatingSystem::CreateRegisterContextForThread (Thread * thread, lldb::addr_t reg_data_addr) pure virtual
Referenced by lldb_private::RegisterContextThreadMemory::UpdateRegisterContext().
CreateThread()
virtual lldb::ThreadSP lldb_private::OperatingSystem::CreateThread (lldb::tid_t tid, lldb::addr_t context) inline virtual
Definition at line 58 of file OperatingSystem.h.
Referenced by lldb_private::Process::CreateOSPluginThread().
CreateThreadStopReason()
virtual lldb::StopInfoSP lldb_private::OperatingSystem::CreateThreadStopReason (Thread * thread) pure virtual
Referenced by ThreadMemory::CalculateStopInfo().
DoesPluginReportAllThreads()
virtual bool lldb_private::OperatingSystem::DoesPluginReportAllThreads () pure virtual
Referenced by lldb_private::Process::UpdateThreadListIfNeeded().
FindPlugin()
OperatingSystem * OperatingSystem::FindPlugin (Process * process, const char * plugin_name) static
Find a halted OS plugin for a given process.
Scans the installed OperatingSystem plug-ins and tries to find an instance that matches the current target triple and executable.
Parameters
[in] process The process for which to try and locate a halted OS plug-in instance.
[in] plugin_name An optional name of a specific halted OS plug-in that should be used. If NULL, pick the best plug-in.
Definition at line 16 of file OperatingSystem.cpp.
References lldb_private::PluginManager::GetOperatingSystemCreateCallbackAtIndex(), lldb_private::PluginManager::GetOperatingSystemCreateCallbackForPluginName(), and OperatingSystem().
Referenced by lldb_private::Process::LoadOperatingSystemPlugin().
IsOperatingSystemPluginThread()
bool OperatingSystem::IsOperatingSystemPluginThread (const lldb::ThreadSP & thread_sp) virtual
Definition at line 46 of file OperatingSystem.cpp.
Referenced by lldb_private::RegisterContextThreadMemory::UpdateRegisterContext().
ThreadWasSelected()
virtual void lldb_private::OperatingSystem::ThreadWasSelected (Thread * thread) pure virtual
UpdateThreadList()
virtual bool lldb_private::OperatingSystem::UpdateThreadList (ThreadList & old_thread_list, ThreadList & real_thread_list, ThreadList & new_thread_list) pure virtual
Referenced by lldb_private::Process::UpdateThreadListIfNeeded().
Member Data Documentation
m_process
Process* lldb_private::OperatingSystem::m_process protected
The process that this dynamic loader plug-in is tracking.
Definition at line 69 of file OperatingSystem.h.
Referenced by OperatingSystem().
The documentation for this class was generated from the following files:
OperatingSystem.h
OperatingSystem.cpp