LLDB: lldb_private::Watchpoint Class Reference
lldb_private::Watchpoint Class Reference
#include <Watchpoint.h>
Classes
class WatchpointEventData
class WatchpointVariableBaton
struct WatchpointVariableContext
Represents the context of a watchpoint variable.
Public Member Functions
Watchpoint (Target &target, lldb::addr_t addr, uint32_t size, const CompilerType *type, bool hardware=true)
~Watchpoint () override
bool IsEnabled () const
void SetEnabled (bool enabled, bool notify=true)
bool IsHardware () const override
bool ShouldStop (StoppointCallbackContext *context) override
bool WatchpointRead () const
bool WatchpointWrite () const
bool WatchpointModify () const
uint32_t GetIgnoreCount () const
void SetIgnoreCount (uint32_t n)
void SetWatchpointType (uint32_t type, bool notify=true)
void SetDeclInfo (const std::string &str)
std::string GetWatchSpec ()
void SetWatchSpec (const std::string &str)
bool WatchedValueReportable (const ExecutionContext &exe_ctx)
bool IsWatchVariable () const
void SetWatchVariable (bool val)
bool CaptureWatchedValue (const ExecutionContext &exe_ctx)
bool SetupVariableWatchpointDisabler (lldb::StackFrameSP frame_sp) const
void GetDescription (Stream *s, lldb::DescriptionLevel level)
void Dump (Stream *s) const override
bool DumpSnapshots (Stream *s, const char *prefix=nullptr) const
void DumpWithLevel (Stream *s, lldb::DescriptionLevel description_level) const
Target & GetTarget ()
const Status & GetError ()
WatchpointOptions * GetOptions ()
Returns the WatchpointOptions structure set for this watchpoint.
void SetCallback (WatchpointHitCallback callback, void *callback_baton, bool is_synchronous=false)
Set the callback action invoked when the watchpoint is hit.
void SetCallback (WatchpointHitCallback callback, const lldb::BatonSP &callback_baton_sp, bool is_synchronous=false)
void ClearCallback ()
bool InvokeCallback (StoppointCallbackContext *context)
Invoke the callback action when the watchpoint is hit.
void SetCondition (const char *condition)
Set the watchpoint's condition.
const char * GetConditionText () const
Return a pointer to the text of the condition expression.
void TurnOnEphemeralMode ()
void TurnOffEphemeralMode ()
bool IsDisabledDuringEphemeralMode ()
const CompilerType & GetCompilerType ()
Public Member Functions inherited from lldb_private::StoppointSite
StoppointSite (lldb::break_id_t bid, lldb::addr_t m_addr, bool hardware)
StoppointSite (lldb::break_id_t bid, lldb::addr_t m_addr, uint32_t byte_size, bool hardware)
virtual ~StoppointSite ()=default
virtual lldb::addr_t GetLoadAddress () const
virtual void SetLoadAddress (lldb::addr_t addr)
uint32_t GetByteSize () const
uint32_t GetHitCount () const
void ResetHitCount ()
bool HardwareRequired () const
virtual bool ShouldStop (StoppointCallbackContext *context, BreakpointLocationCollection &stopping_bp_locs)
lldb::break_id_t GetID () const
Static Public Member Functions
static bool VariableWatchpointDisabler (void *baton, lldb_private::StoppointCallbackContext *context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id)
Callback routine to disable the watchpoint set on a local variable when it goes out of scope.
Private Member Functions
void ResetHistoricValues ()
void UndoHitCount ()
void SetID (lldb::watch_id_t id)
void SendWatchpointChangedEvent (lldb::WatchpointEventType eventKind)
Watchpoint (const Watchpoint &)=delete
const Watchpoint & operator= (const Watchpoint &)=delete
Private Attributes
Target & m_target
bool m_enabled
bool m_is_hardware
bool m_is_watch_variable
bool m_is_ephemeral
uint32_t m_disabled_count
uint32_t m_watch_read: 1
uint32_t m_watch_write: 1
uint32_t m_watch_modify: 1
uint32_t m_ignore_count
std::string m_decl_str
std::string m_watch_spec_str
lldb::ValueObjectSP m_old_value_sp
lldb::ValueObjectSP m_new_value_sp
CompilerType m_type
Status m_error
WatchpointOptions m_options
std::unique_ptr< UserExpression > m_condition_up
Friends
class Target
class WatchpointList
class StopInfoWatchpoint
Additional Inherited Members
Protected Attributes inherited from lldb_private::StoppointSite
lldb::break_id_t m_id
Stoppoint site ID.
lldb::addr_t m_addr
The load address of this stop point.
bool m_is_hardware_required
True if this point is required to use hardware (which may fail due to the lack of resources).
uint32_t m_byte_size
The size in bytes of stoppoint, e.g.
StoppointHitCounter m_hit_counter
Number of times this breakpoint/watchpoint has been hit.
Detailed Description
Definition at line 24 of file Watchpoint.h.
Constructor & Destructor Documentation
Watchpoint() [1/2]
Watchpoint::Watchpoint (Target & target, lldb::addr_t addr, uint32_t size, const CompilerType * type, bool hardware = true)
Definition at line 29 of file Watchpoint.cpp.
References lldb_private::GetLog(), lldb_private::CompilerType::IsValid(), LLDB_LOG_ERROR, m_disabled_count, m_enabled, m_ignore_count, m_is_ephemeral, m_is_hardware, m_is_watch_variable, m_target, m_type, m_watch_modify, m_watch_read, m_watch_write, lldb_private::StoppointSite::StoppointSite(), Target, and lldb_private::Watchpoints.
Referenced by operator=(), and Watchpoint().
~Watchpoint()
Watchpoint::~Watchpoint () override default
Watchpoint() [2/2]
lldb_private::Watchpoint::Watchpoint (const Watchpoint &) private delete
References Watchpoint().
Member Function Documentation
CaptureWatchedValue()
bool Watchpoint::CaptureWatchedValue (const ExecutionContext & exe_ctx)
Definition at line 202 of file Watchpoint.cpp.
References lldb_private::ValueObjectMemory::Create(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::StoppointSite::GetLoadAddress(), lldb_private::ConstString::GetStringRef(), m_new_value_sp, m_old_value_sp, and m_type.
ClearCallback()
void Watchpoint::ClearCallback ()
Definition at line 180 of file Watchpoint.cpp.
References m_options, and SendWatchpointChangedEvent().
Referenced by CommandObjectWatchpointCommandDelete::DoExecute().
Dump()
void Watchpoint::Dump (Stream * s) const override virtual
Implements lldb_private::StoppointSite.
Definition at line 269 of file Watchpoint.cpp.
References DumpWithLevel(), and lldb::eDescriptionLevelBrief.
DumpSnapshots()
bool Watchpoint::DumpSnapshots (Stream * s, const char * prefix = nullptr) const
Definition at line 275 of file Watchpoint.cpp.
References lldb::eNoDynamicValues, error(), lldb_private::StreamString::GetData(), lldb_private::StoppointSite::GetID(), lldb_private::StreamString::GetSize(), lldb_private::Stream::Indent(), m_new_value_sp, m_old_value_sp, m_watch_modify, m_watch_read, m_watch_write, lldb_private::Stream::Printf(), lldb_private::DumpValueObjectOptions::SetHideName(), lldb_private::DumpValueObjectOptions::SetHideRootName(), lldb_private::DumpValueObjectOptions::SetHideRootType(), lldb_private::DumpValueObjectOptions::SetUseDynamicType(), and lldb_private::toString().
Referenced by DumpWithLevel().
DumpWithLevel()
void Watchpoint::DumpWithLevel (Stream * s, lldb::DescriptionLevel description_level) const
Definition at line 344 of file Watchpoint.cpp.
References DumpSnapshots(), lldb::eDescriptionLevelBrief, lldb::eDescriptionLevelFull, lldb::eDescriptionLevelVerbose, GetConditionText(), lldb_private::StoppointSite::GetHitCount(), lldb_private::StoppointSite::GetID(), GetIgnoreCount(), lldb_private::StoppointSite::GetLoadAddress(), IsEnabled(), lldb_private::StoppointSite::m_byte_size, m_decl_str, m_options, m_target, m_watch_modify, m_watch_read, m_watch_spec_str, m_watch_write, and lldb_private::Stream::Printf().
Referenced by Dump(), and GetDescription().
GetCompilerType()
const CompilerType & lldb_private::Watchpoint::GetCompilerType () inline
Definition at line 189 of file Watchpoint.h.
References m_type.
GetConditionText()
const char * Watchpoint::GetConditionText () const
Return a pointer to the text of the condition expression.
Returns
A pointer to the condition expression text, or nullptr if no
Definition at line 477 of file Watchpoint.cpp.
References m_condition_up.
Referenced by DumpWithLevel().
GetDescription()
void Watchpoint::GetDescription (Stream * s, lldb::DescriptionLevel level)
Definition at line 265 of file Watchpoint.cpp.
References DumpWithLevel().
Referenced by AddWatchpointDescription().
GetError()
const Status & lldb_private::Watchpoint::GetError () inline
Definition at line 132 of file Watchpoint.h.
References m_error.
GetIgnoreCount()
uint32_t Watchpoint::GetIgnoreCount () const
Definition at line 446 of file Watchpoint.cpp.
References m_ignore_count.
Referenced by DumpWithLevel().
GetOptions()
WatchpointOptions * lldb_private::Watchpoint::GetOptions () inline
Returns the WatchpointOptions structure set for this watchpoint.
Returns
A pointer to this watchpoint's WatchpointOptions.
Definition at line 138 of file Watchpoint.h.
References m_options.
Referenced by CommandObjectWatchpointCommandList::DoExecute().
GetTarget()
Target & lldb_private::Watchpoint::GetTarget () inline
Definition at line 131 of file Watchpoint.h.
References m_target, and Target.
Referenced by SendWatchpointChangedEvent().
GetWatchSpec()
std::string Watchpoint::GetWatchSpec ()
Definition at line 187 of file Watchpoint.cpp.
References m_watch_spec_str.
InvokeCallback()
bool Watchpoint::InvokeCallback (StoppointCallbackContext * context)
Invoke the callback action when the watchpoint is hit.
Parameters
[in] context Described the watchpoint event.
Returns
true if the target should stop at this watchpoint and false not.
Definition at line 455 of file Watchpoint.cpp.
References lldb_private::StoppointSite::GetID(), and m_options.
IsDisabledDuringEphemeralMode()
bool Watchpoint::IsDisabledDuringEphemeralMode ()
Definition at line 407 of file Watchpoint.cpp.
References m_disabled_count, and m_is_ephemeral.
IsEnabled()
bool Watchpoint::IsEnabled () const
Definition at line 392 of file Watchpoint.cpp.
References m_enabled.
Referenced by DumpWithLevel(), and ShouldStop().
IsHardware()
bool Watchpoint::IsHardware () const override virtual
Implements lldb_private::StoppointSite.
Definition at line 193 of file Watchpoint.cpp.
References lldb_private::StoppointSite::HardwareRequired(), lldbassert, and m_is_hardware.
IsWatchVariable()
bool Watchpoint::IsWatchVariable () const
Definition at line 198 of file Watchpoint.cpp.
References m_is_watch_variable.
operator=()
const Watchpoint & lldb_private::Watchpoint::operator= (const Watchpoint &) private delete
References Watchpoint().
ResetHistoricValues()
void lldb_private::Watchpoint::ResetHistoricValues () inline private
Definition at line 196 of file Watchpoint.h.
References m_new_value_sp, and m_old_value_sp.
SendWatchpointChangedEvent()
void Watchpoint::SendWatchpointChangedEvent (lldb::WatchpointEventType eventKind) private
Definition at line 483 of file Watchpoint.cpp.
References lldb_private::Broadcaster::BroadcastEvent(), lldb_private::Target::eBroadcastBitWatchpointChanged, and GetTarget().
Referenced by ClearCallback(), SetCallback(), SetCallback(), SetCondition(), SetEnabled(), SetIgnoreCount(), and SetWatchpointType().
SetCallback() [1/2]
void Watchpoint::SetCallback (WatchpointHitCallback callback, const lldb::BatonSP & callback_baton_sp, bool is_synchronous = false)
Definition at line 85 of file Watchpoint.cpp.
References m_options, and SendWatchpointChangedEvent().
SetCallback() [2/2]
void Watchpoint::SetCallback (WatchpointHitCallback callback, void * callback_baton, bool is_synchronous = false)
Set the callback action invoked when the watchpoint is hit.
Parameters
[in] callback The method that will get called when the watchpoint is hit.
[in] callback_baton A void * pointer that will get passed back to the callback function.
[in] is_synchronous If true the callback will be run on the private event thread before the stop event gets reported. If false, the callback will get handled on the public event thread after the stop has been posted.
Definition at line 73 of file Watchpoint.cpp.
References m_options, and SendWatchpointChangedEvent().
SetCondition()
void Watchpoint::SetCondition (const char * condition)
Set the watchpoint's condition.
Parameters
[in] condition The condition expression to evaluate when the watchpoint is hit. Pass in nullptr to clear the condition.
Definition at line 459 of file Watchpoint.cpp.
References lldb_private::Expression::eResultTypeAny, error(), m_condition_up, m_target, and SendWatchpointChangedEvent().
SetDeclInfo()
void Watchpoint::SetDeclInfo (const std::string & str)
Definition at line 185 of file Watchpoint.cpp.
References m_decl_str.
SetEnabled()
void Watchpoint::SetEnabled (bool enabled, bool notify = true)
Definition at line 411 of file Watchpoint.cpp.
References m_disabled_count, m_enabled, m_is_ephemeral, and SendWatchpointChangedEvent().
SetID()
void lldb_private::Watchpoint::SetID (lldb::watch_id_t id) inline private
Definition at line 231 of file Watchpoint.h.
References lldb_private::StoppointSite::m_id.
SetIgnoreCount()
void Watchpoint::SetIgnoreCount (uint32_t n)
Definition at line 448 of file Watchpoint.cpp.
References m_ignore_count, and SendWatchpointChangedEvent().
SetupVariableWatchpointDisabler()
bool Watchpoint::SetupVariableWatchpointDisabler (lldb::StackFrameSP frame_sp) const
Definition at line 92 of file Watchpoint.cpp.
References DoNoSelectMostRelevantFrame, lldb_private::StoppointSite::GetID(), lldb_private::Address::GetLoadAddress(), lldb_private::ExecutionContext::GetTargetSP(), LLDB_INVALID_ADDRESS, LLDB_INVALID_FRAME_ID, and VariableWatchpointDisabler().
SetWatchpointType()
void Watchpoint::SetWatchpointType (uint32_t type, bool notify = true)
Definition at line 427 of file Watchpoint.cpp.
References LLDB_WATCH_TYPE_MODIFY, LLDB_WATCH_TYPE_READ, LLDB_WATCH_TYPE_WRITE, m_watch_modify, m_watch_read, m_watch_write, and SendWatchpointChangedEvent().
SetWatchSpec()
void Watchpoint::SetWatchSpec (const std::string & str)
Definition at line 189 of file Watchpoint.cpp.
References m_watch_spec_str.
SetWatchVariable()
void Watchpoint::SetWatchVariable (bool val)
Definition at line 200 of file Watchpoint.cpp.
References m_is_watch_variable.
ShouldStop()
bool Watchpoint::ShouldStop (StoppointCallbackContext * context) override virtual
Reimplemented from lldb_private::StoppointSite.
Definition at line 259 of file Watchpoint.cpp.
References IsEnabled(), and lldb_private::StoppointSite::m_hit_counter.
TurnOffEphemeralMode()
void Watchpoint::TurnOffEphemeralMode ()
Definition at line 401 of file Watchpoint.cpp.
References m_disabled_count, and m_is_ephemeral.
TurnOnEphemeralMode()
void Watchpoint::TurnOnEphemeralMode ()
Definition at line 399 of file Watchpoint.cpp.
References m_is_ephemeral.
UndoHitCount()
void lldb_private::Watchpoint::UndoHitCount () inline private
Definition at line 201 of file Watchpoint.h.
References lldb_private::StoppointSite::m_hit_counter.
VariableWatchpointDisabler()
bool Watchpoint::VariableWatchpointDisabler (void * baton, lldb_private::StoppointCallbackContext * context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id) static
Callback routine to disable the watchpoint set on a local variable when it goes out of scope.
Definition at line 133 of file Watchpoint.cpp.
References lldb_private::Watchpoint::WatchpointVariableContext::exe_ctx, lldb_private::StoppointCallbackContext::exe_ctx_ref, lldb_private::GetLog(), lldb_private::ExecutionContextRef::GetTargetSP(), LLDB_INVALID_WATCH_ID, LLDB_LOGF, lldb_private::Watchpoint::WatchpointVariableContext::watch_id, and lldb_private::Watchpoints.
Referenced by SetupVariableWatchpointDisabler().
WatchedValueReportable()
bool Watchpoint::WatchedValueReportable (const ExecutionContext & exe_ctx)
Definition at line 221 of file Watchpoint.cpp.
References lldb_private::ValueObjectMemory::Create(), error(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::DataExtractor::GetByteSize(), lldb_private::DataExtractor::GetDataStart(), lldb_private::StoppointSite::GetLoadAddress(), lldb_private::ConstString::GetStringRef(), m_new_value_sp, m_type, m_watch_modify, and m_watch_read.
WatchpointModify()
bool Watchpoint::WatchpointModify () const
Definition at line 444 of file Watchpoint.cpp.
References m_watch_modify.
WatchpointRead()
bool Watchpoint::WatchpointRead () const
Definition at line 440 of file Watchpoint.cpp.
References m_watch_read.
WatchpointWrite()
bool Watchpoint::WatchpointWrite () const
Definition at line 442 of file Watchpoint.cpp.
References m_watch_write.
Friends And Related Symbol Documentation
StopInfoWatchpoint
friend class StopInfoWatchpoint friend
Definition at line 194 of file Watchpoint.h.
References StopInfoWatchpoint.
Referenced by StopInfoWatchpoint.
Target
friend class Target friend
Definition at line 192 of file Watchpoint.h.
References Target.
Referenced by GetTarget(), Target, and Watchpoint().
WatchpointList
friend class WatchpointList friend
Definition at line 193 of file Watchpoint.h.
References WatchpointList.
Referenced by WatchpointList.
Member Data Documentation
m_condition_up
std::unique_ptr<UserExpression> lldb_private::Watchpoint::m_condition_up private
Definition at line 229 of file Watchpoint.h.
Referenced by GetConditionText(), and SetCondition().
m_decl_str
std::string lldb_private::Watchpoint::m_decl_str private
Definition at line 220 of file Watchpoint.h.
Referenced by DumpWithLevel(), and SetDeclInfo().
m_disabled_count
uint32_t lldb_private::Watchpoint::m_disabled_count private
Definition at line 211 of file Watchpoint.h.
Referenced by IsDisabledDuringEphemeralMode(), SetEnabled(), TurnOffEphemeralMode(), and Watchpoint().
m_enabled
bool lldb_private::Watchpoint::m_enabled private
Definition at line 204 of file Watchpoint.h.
Referenced by IsEnabled(), SetEnabled(), and Watchpoint().
m_error
Status lldb_private::Watchpoint::m_error private
Definition at line 225 of file Watchpoint.h.
Referenced by GetError().
m_ignore_count
uint32_t lldb_private::Watchpoint::m_ignore_count private
Definition at line 219 of file Watchpoint.h.
Referenced by GetIgnoreCount(), SetIgnoreCount(), and Watchpoint().
m_is_ephemeral
bool lldb_private::Watchpoint::m_is_ephemeral private
Definition at line 207 of file Watchpoint.h.
Referenced by IsDisabledDuringEphemeralMode(), SetEnabled(), TurnOffEphemeralMode(), TurnOnEphemeralMode(), and Watchpoint().
m_is_hardware
bool lldb_private::Watchpoint::m_is_hardware private
Definition at line 205 of file Watchpoint.h.
Referenced by IsHardware(), and Watchpoint().
m_is_watch_variable
bool lldb_private::Watchpoint::m_is_watch_variable private
Definition at line 206 of file Watchpoint.h.
Referenced by IsWatchVariable(), SetWatchVariable(), and Watchpoint().
m_new_value_sp
lldb::ValueObjectSP lldb_private::Watchpoint::m_new_value_sp private
Definition at line 223 of file Watchpoint.h.
Referenced by CaptureWatchedValue(), DumpSnapshots(), ResetHistoricValues(), and WatchedValueReportable().
m_old_value_sp
lldb::ValueObjectSP lldb_private::Watchpoint::m_old_value_sp private
Definition at line 222 of file Watchpoint.h.
Referenced by CaptureWatchedValue(), DumpSnapshots(), and ResetHistoricValues().
m_options
WatchpointOptions lldb_private::Watchpoint::m_options private
Definition at line 227 of file Watchpoint.h.
Referenced by ClearCallback(), DumpWithLevel(), GetOptions(), InvokeCallback(), SetCallback(), and SetCallback().
m_target
Target& lldb_private::Watchpoint::m_target private
Definition at line 203 of file Watchpoint.h.
Referenced by DumpWithLevel(), GetTarget(), SetCondition(), and Watchpoint().
m_type
CompilerType lldb_private::Watchpoint::m_type private
Definition at line 224 of file Watchpoint.h.
Referenced by CaptureWatchedValue(), GetCompilerType(), WatchedValueReportable(), and Watchpoint().
m_watch_modify
uint32_t lldb_private::Watchpoint::m_watch_modify private
Definition at line 218 of file Watchpoint.h.
Referenced by DumpSnapshots(), DumpWithLevel(), SetWatchpointType(), WatchedValueReportable(), Watchpoint(), and WatchpointModify().
m_watch_read
uint32_t lldb_private::Watchpoint::m_watch_read private
Definition at line 216 of file Watchpoint.h.
Referenced by DumpSnapshots(), DumpWithLevel(), SetWatchpointType(), WatchedValueReportable(), Watchpoint(), and WatchpointRead().
m_watch_spec_str
std::string lldb_private::Watchpoint::m_watch_spec_str private
Definition at line 221 of file Watchpoint.h.
Referenced by DumpWithLevel(), GetWatchSpec(), and SetWatchSpec().
m_watch_write
uint32_t lldb_private::Watchpoint::m_watch_write private
Definition at line 217 of file Watchpoint.h.
Referenced by DumpSnapshots(), DumpWithLevel(), SetWatchpointType(), Watchpoint(), and WatchpointWrite().
The documentation for this class was generated from the following files:
Watchpoint.h
Watchpoint.cpp