LLDB: MemoryRegionInfoListImpl Class Reference
MemoryRegionInfoListImpl Class Reference
Public Member Functions
MemoryRegionInfoListImpl ()
MemoryRegionInfoListImpl (const MemoryRegionInfoListImpl &rhs)=default
MemoryRegionInfoListImpl & operator= (const MemoryRegionInfoListImpl &rhs)
size_t GetSize () const
void Reserve (size_t capacity)
void Append (const MemoryRegionInfo &sb_region)
void Append (const MemoryRegionInfoListImpl &list)
void Clear ()
bool GetMemoryRegionContainingAddress (lldb::addr_t addr, MemoryRegionInfo &region_info)
bool GetMemoryRegionInfoAtIndex (size_t index, MemoryRegionInfo &region_info)
MemoryRegionInfos & Ref ()
const MemoryRegionInfos & Ref () const
Private Attributes
MemoryRegionInfos m_regions
Detailed Description
Definition at line 20 of file SBMemoryRegionInfoList.cpp.
Constructor & Destructor Documentation
MemoryRegionInfoListImpl() [1/2]
MemoryRegionInfoListImpl::MemoryRegionInfoListImpl () inline
Definition at line 22 of file SBMemoryRegionInfoList.cpp.
References m_regions.
Referenced by Append(), MemoryRegionInfoListImpl(), and operator=().
MemoryRegionInfoListImpl() [2/2]
MemoryRegionInfoListImpl::MemoryRegionInfoListImpl (const MemoryRegionInfoListImpl & rhs) default
References MemoryRegionInfoListImpl().
Member Function Documentation
Append() [1/2]
void MemoryRegionInfoListImpl::Append (const MemoryRegionInfo & sb_region) inline
Definition at line 37 of file SBMemoryRegionInfoList.cpp.
References m_regions.
Referenced by Append().
Append() [2/2]
void MemoryRegionInfoListImpl::Append (const MemoryRegionInfoListImpl & list) inline
Definition at line 41 of file SBMemoryRegionInfoList.cpp.
References Append(), GetSize(), m_regions, MemoryRegionInfoListImpl(), and Reserve().
Clear()
void MemoryRegionInfoListImpl::Clear () inline
Definition at line 48 of file SBMemoryRegionInfoList.cpp.
References m_regions.
GetMemoryRegionContainingAddress()
bool MemoryRegionInfoListImpl::GetMemoryRegionContainingAddress (lldb::addr_t addr, MemoryRegionInfo & region_info) inline
Definition at line 50 of file SBMemoryRegionInfoList.cpp.
References m_regions.
GetMemoryRegionInfoAtIndex()
bool MemoryRegionInfoListImpl::GetMemoryRegionInfoAtIndex (size_t index, MemoryRegionInfo & region_info) inline
Definition at line 61 of file SBMemoryRegionInfoList.cpp.
References GetSize(), and m_regions.
GetSize()
size_t MemoryRegionInfoListImpl::GetSize () const inline
Definition at line 33 of file SBMemoryRegionInfoList.cpp.
References m_regions.
Referenced by Append(), and GetMemoryRegionInfoAtIndex().
operator=()
MemoryRegionInfoListImpl & MemoryRegionInfoListImpl::operator= (const MemoryRegionInfoListImpl & rhs) inline
Definition at line 26 of file SBMemoryRegionInfoList.cpp.
References m_regions, and MemoryRegionInfoListImpl().
Ref() [1/2]
MemoryRegionInfos & MemoryRegionInfoListImpl::Ref () inline
Definition at line 69 of file SBMemoryRegionInfoList.cpp.
References m_regions.
Ref() [2/2]
const MemoryRegionInfos & MemoryRegionInfoListImpl::Ref () const inline
Definition at line 71 of file SBMemoryRegionInfoList.cpp.
References m_regions.
Reserve()
void MemoryRegionInfoListImpl::Reserve (size_t capacity) inline
Definition at line 35 of file SBMemoryRegionInfoList.cpp.
References m_regions.
Referenced by Append().
Member Data Documentation
m_regions
MemoryRegionInfos MemoryRegionInfoListImpl::m_regions private
Definition at line 74 of file SBMemoryRegionInfoList.cpp.
Referenced by Append(), Append(), Clear(), GetMemoryRegionContainingAddress(), GetMemoryRegionInfoAtIndex(), GetSize(), MemoryRegionInfoListImpl(), operator=(), Ref(), Ref(), and Reserve().
The documentation for this class was generated from the following file:
SBMemoryRegionInfoList.cpp