LLDB: ProcessOptionValueProperties Class Reference
ProcessOptionValueProperties Class Reference
Public Member Functions
ProcessOptionValueProperties (llvm::StringRef name)
const Property * GetPropertyAtIndex (size_t idx, const ExecutionContext *exe_ctx) const override
Public Member Functions inherited from lldb_private::Cloneable< ProcessOptionValueProperties, OptionValueProperties >
std::shared_ptr< typename OptionValueProperties::TopmostBase > Clone () const override
Public Member Functions inherited from lldb_private::OptionValueProperties
OptionValueProperties ()=default
OptionValueProperties (llvm::StringRef name)
~OptionValueProperties () override=default
Type GetType () const override
void Clear () override
lldb::OptionValueSP DeepCopy (const lldb::OptionValueSP &new_parent) const override
Status SetValueFromString (llvm::StringRef value, VarSetOperationType op=eVarSetOperationAssign) override
void DumpValue (const ExecutionContext *exe_ctx, Stream &strm, uint32_t dump_mask) override
llvm::json::Value ToJSON (const ExecutionContext *exe_ctx) const override
llvm::StringRef GetName () const override
virtual Status DumpPropertyValue (const ExecutionContext *exe_ctx, Stream &strm, llvm::StringRef property_path, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllDescriptions (CommandInterpreter &interpreter, Stream &strm) const
void Apropos (llvm::StringRef keyword, std::vector< const Property * > &matching_properties) const
void Initialize (const PropertyCollectionDefinition &setting_definitions)
void SetExpectedPath (std::string path)
virtual size_t GetPropertyIndex (llvm::StringRef name) const
virtual const Property * GetProperty (llvm::StringRef name, const ExecutionContext *exe_ctx=nullptr) const
virtual const Property * GetPropertyAtPath (const ExecutionContext *exe_ctx, llvm::StringRef property_path) const
virtual lldb::OptionValueSP GetPropertyValueAtIndex (size_t idx, const ExecutionContext *exe_ctx) const
virtual lldb::OptionValueSP GetValueForKey (const ExecutionContext *exe_ctx, llvm::StringRef key) const
lldb::OptionValueSP GetSubValue (const ExecutionContext *exe_ctx, llvm::StringRef name, Status &error) const override
Status SetSubValue (const ExecutionContext *exe_ctx, VarSetOperationType op, llvm::StringRef path, llvm::StringRef value) override
bool GetPropertyAtIndexAsArgs (size_t idx, Args &args, const ExecutionContext *exe_ctx=nullptr) const
bool SetPropertyAtIndexFromArgs (size_t idx, const Args &args, const ExecutionContext *exe_ctx=nullptr)
OptionValueDictionary * GetPropertyAtIndexAsOptionValueDictionary (size_t idx, const ExecutionContext *exe_ctx=nullptr) const
OptionValueSInt64 * GetPropertyAtIndexAsOptionValueSInt64 (size_t idx, const ExecutionContext *exe_ctx=nullptr) const
OptionValueUInt64 * GetPropertyAtIndexAsOptionValueUInt64 (size_t idx, const ExecutionContext *exe_ctx=nullptr) const
OptionValueString * GetPropertyAtIndexAsOptionValueString (size_t idx, const ExecutionContext *exe_ctx=nullptr) const
OptionValueFileSpec * GetPropertyAtIndexAsOptionValueFileSpec (size_t idx, const ExecutionContext *exe_ctx=nullptr) const
OptionValuePathMappings * GetPropertyAtIndexAsOptionValuePathMappings (size_t idx, const ExecutionContext *exe_ctx=nullptr) const
OptionValueFileSpecList * GetPropertyAtIndexAsOptionValueFileSpecList (size_t idx, const ExecutionContext *exe_ctx=nullptr) const
void AppendProperty (llvm::StringRef name, llvm::StringRef desc, bool is_global, const lldb::OptionValueSP &value_sp)
lldb::OptionValuePropertiesSP GetSubProperty (const ExecutionContext *exe_ctx, llvm::StringRef name)
void SetValueChangedCallback (size_t property_idx, std::function< void()> callback)
template<typename T>
auto GetPropertyAtIndexAs (size_t idx, const ExecutionContext *exe_ctx=nullptr) const
template<typename T>
bool SetPropertyAtIndex (size_t idx, T t, const ExecutionContext *exe_ctx=nullptr) const
Public Member Functions inherited from lldb_private::OptionValue
OptionValue ()=default
virtual ~OptionValue ()=default
OptionValue (const OptionValue &other)
OptionValue & operator= (const OptionValue &other)
virtual bool ValueIsTransparent () const
virtual const char * GetTypeAsCString () const
virtual void AutoComplete (CommandInterpreter &interpreter, CompletionRequest &request)
virtual bool IsAggregateValue () const
virtual bool DumpQualifiedName (Stream &strm) const
uint32_t GetTypeAsMask ()
OptionValueArch * GetAsArch ()
const OptionValueArch * GetAsArch () const
OptionValueArray * GetAsArray ()
const OptionValueArray * GetAsArray () const
OptionValueArgs * GetAsArgs ()
const OptionValueArgs * GetAsArgs () const
OptionValueBoolean * GetAsBoolean ()
const OptionValueBoolean * GetAsBoolean () const
OptionValueChar * GetAsChar ()
const OptionValueChar * GetAsChar () const
OptionValueDictionary * GetAsDictionary ()
const OptionValueDictionary * GetAsDictionary () const
OptionValueEnumeration * GetAsEnumeration ()
const OptionValueEnumeration * GetAsEnumeration () const
OptionValueFileSpec * GetAsFileSpec ()
const OptionValueFileSpec * GetAsFileSpec () const
OptionValueFileSpecList * GetAsFileSpecList ()
const OptionValueFileSpecList * GetAsFileSpecList () const
OptionValueFormat * GetAsFormat ()
const OptionValueFormat * GetAsFormat () const
OptionValueLanguage * GetAsLanguage ()
const OptionValueLanguage * GetAsLanguage () const
OptionValuePathMappings * GetAsPathMappings ()
const OptionValuePathMappings * GetAsPathMappings () const
OptionValueProperties * GetAsProperties ()
const OptionValueProperties * GetAsProperties () const
OptionValueRegex * GetAsRegex ()
const OptionValueRegex * GetAsRegex () const
OptionValueSInt64 * GetAsSInt64 ()
const OptionValueSInt64 * GetAsSInt64 () const
OptionValueString * GetAsString ()
const OptionValueString * GetAsString () const
OptionValueUInt64 * GetAsUInt64 ()
const OptionValueUInt64 * GetAsUInt64 () const
OptionValueUUID * GetAsUUID ()
const OptionValueUUID * GetAsUUID () const
OptionValueFormatEntity * GetAsFormatEntity ()
const OptionValueFormatEntity * GetAsFormatEntity () const
bool AppendFileSpecValue (FileSpec file_spec)
bool OptionWasSet () const
void SetOptionWasSet ()
void SetParent (const lldb::OptionValueSP &parent_sp)
lldb::OptionValueSP GetParent () const
void SetValueChangedCallback (std::function< void()> callback)
void NotifyValueChanged ()
template<typename T, std::enable_if_t<!std::is_pointer_v< T >, bool > = true>
std::optional< T > GetValueAs () const
template<typename T, typename U = typename std::remove_const< typename std::remove_pointer<T>::type>::type, std::enable_if_t< std::is_pointer_v< T >, bool > = true>
T GetValueAs () const
bool SetValueAs (bool v)
bool SetValueAs (char v)
bool SetValueAs (uint64_t v)
bool SetValueAs (int64_t v)
bool SetValueAs (UUID v)
bool SetValueAs (llvm::StringRef v)
bool SetValueAs (lldb::LanguageType v)
bool SetValueAs (lldb::Format v)
bool SetValueAs (FileSpec v)
bool SetValueAs (ArchSpec v)
bool SetValueAs (const FormatEntity::Entry &v)
template<typename T, std::enable_if_t< std::is_enum_v< T >, bool > = true>
bool SetValueAs (T t)
Additional Inherited Members
Public Types inherited from lldb_private::OptionValue
enum Type {
eTypeInvalid = 0 , eTypeArch , eTypeArgs , eTypeArray ,
eTypeBoolean , eTypeChar , eTypeDictionary , eTypeEnum ,
eTypeFileLineColumn , eTypeFileSpec , eTypeFileSpecList , eTypeFormat ,
eTypeLanguage , eTypePathMap , eTypeProperties , eTypeRegex ,
eTypeSInt64 , eTypeString , eTypeUInt64 , eTypeUUID ,
eTypeFormatEntity
}
enum {
eDumpOptionName = (1u << 0) , eDumpOptionType = (1u << 1) , eDumpOptionValue = (1u << 2) , eDumpOptionDescription = (1u << 3) ,
eDumpOptionRaw = (1u << 4) , eDumpOptionCommand = (1u << 5) , eDumpOptionDefaultValue = (1u << 6) , eDumpGroupValue = (eDumpOptionName | eDumpOptionType | eDumpOptionValue) ,
eDumpGroupHelp , eDumpGroupExport = (eDumpOptionCommand | eDumpOptionName | eDumpOptionValue)
}
Static Public Member Functions inherited from lldb_private::OptionValueProperties
static lldb::OptionValuePropertiesSP CreateLocalCopy (const Properties &global_properties)
Static Public Member Functions inherited from lldb_private::OptionValue
static const char * GetBuiltinTypeAsCString (Type t)
static uint32_t ConvertTypeToMask (OptionValue::Type type)
static OptionValue::Type ConvertTypeMaskToType (uint32_t type_mask)
static lldb::OptionValueSP CreateValueFromCStringForTypeMask (const char *value_cstr, uint32_t type_mask, Status &error)
Protected Types inherited from lldb_private::OptionValue
using TopmostBase = OptionValue
Protected Member Functions inherited from lldb_private::OptionValueProperties
Property * ProtectedGetPropertyAtIndex (size_t idx)
const Property * ProtectedGetPropertyAtIndex (size_t idx) const
bool VerifyPath ()
Protected Attributes inherited from lldb_private::OptionValueProperties
std::string m_name
std::vector< Property > m_properties
llvm::StringMap< size_t > m_name_to_index
std::string m_expected_path
Protected Attributes inherited from lldb_private::OptionValue
lldb::OptionValueWP m_parent_wp
std::function< void()> m_callback
bool m_value_was_set = false
Detailed Description
Definition at line 82 of file Process.cpp.
Constructor & Destructor Documentation
ProcessOptionValueProperties()
ProcessOptionValueProperties::ProcessOptionValueProperties (llvm::StringRef name) inline
Definition at line 85 of file Process.cpp.
Referenced by GetPropertyAtIndex().
Member Function Documentation
GetPropertyAtIndex()
const Property * ProcessOptionValueProperties::GetPropertyAtIndex (size_t idx, const ExecutionContext * exe_ctx) const inline override virtual
Reimplemented from lldb_private::OptionValueProperties.
Definition at line 88 of file Process.cpp.
References lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::Properties::GetValueProperties(), ProcessOptionValueProperties(), and lldb_private::OptionValueProperties::ProtectedGetPropertyAtIndex().
The documentation for this class was generated from the following file:
Process.cpp