LLDB: lldb_private::dil::IdentifierNode Class Reference
lldb_private::dil::IdentifierNode Class Reference
#include <DILAST.h>
Public Member Functions
IdentifierNode (uint32_t location, std::string name)
llvm::Expected< lldb::ValueObjectSP > Accept (Visitor *v) const override
std::string GetName () const
Public Member Functions inherited from lldb_private::dil::ASTNode
ASTNode (uint32_t location, NodeKind kind)
virtual ~ASTNode ()=default
uint32_t GetLocation () const
NodeKind GetKind () const
Static Public Member Functions
static bool classof (const ASTNode &node)
Private Attributes
std::string m_name
Detailed Description
Definition at line 91 of file DILAST.h.
Constructor & Destructor Documentation
IdentifierNode()
lldb_private::dil::IdentifierNode::IdentifierNode (uint32_t location, std::string name) inline
Definition at line 93 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), lldb_private::dil::eIdentifierNode, and m_name.
Member Function Documentation
Accept()
llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::IdentifierNode::Accept (Visitor * v) const override virtual
Implements lldb_private::dil::ASTNode.
Definition at line 18 of file DILAST.cpp.
References lldb_private::dil::Visitor::Visit().
classof()
bool lldb_private::dil::IdentifierNode::classof (const ASTNode & node) inline static
Definition at line 100 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), lldb_private::dil::eIdentifierNode, and lldb_private::dil::ASTNode::GetKind().
GetName()
std::string lldb_private::dil::IdentifierNode::GetName () const inline
Definition at line 98 of file DILAST.h.
References m_name.
Referenced by lldb_private::dil::Interpreter::Visit().
Member Data Documentation
m_name
std::string lldb_private::dil::IdentifierNode::m_name private
Definition at line 105 of file DILAST.h.
Referenced by GetName(), and IdentifierNode().
The documentation for this class was generated from the following files:
DILAST.h
DILAST.cpp