LLDB: MachSymtabSectionInfo Class Reference
MachSymtabSectionInfo Class Reference
Classes
struct SectionInfo
Public Member Functions
MachSymtabSectionInfo (SectionList *section_list)
SectionSP GetSection (uint8_t n_sect, addr_t file_addr)
Protected Attributes
SectionList * m_section_list
std::vector< SectionInfo > m_section_infos
Detailed Description
Definition at line 1901 of file ObjectFileMachO.cpp.
Constructor & Destructor Documentation
MachSymtabSectionInfo()
MachSymtabSectionInfo::MachSymtabSectionInfo (SectionList * section_list) inline
Definition at line 1903 of file ObjectFileMachO.cpp.
References lldb_private::SectionList::GetNumSections(), m_section_infos, and m_section_list.
Member Function Documentation
GetSection()
SectionSP MachSymtabSectionInfo::GetSection (uint8_t n_sect, addr_t file_addr) inline
Definition at line 1911 of file ObjectFileMachO.cpp.
References m_section_infos, m_section_list, and lldb_private::Debugger::ReportError().
Referenced by ObjectFileMachO::ParseSymtab().
Member Data Documentation
m_section_infos
std::vector<SectionInfo> MachSymtabSectionInfo::m_section_infos protected
Definition at line 1958 of file ObjectFileMachO.cpp.
Referenced by GetSection(), and MachSymtabSectionInfo().
m_section_list
SectionList* MachSymtabSectionInfo::m_section_list protected
Definition at line 1957 of file ObjectFileMachO.cpp.
Referenced by GetSection(), and MachSymtabSectionInfo().
The documentation for this class was generated from the following file:
ObjectFileMachO.cpp