LLDB: lldb::SBFrame Class Reference
lldb::SBFrame Class Reference
#include <SBFrame.h>
Public Member Functions
SBFrame ()
SBFrame (const lldb::SBFrame &rhs)
const lldb::SBFrame & operator= (const lldb::SBFrame &rhs)
~SBFrame ()
bool IsEqual (const lldb::SBFrame &that) const
operator bool () const
bool IsValid () const
uint32_t GetFrameID () const
lldb::addr_t GetCFA () const
lldb::addr_t GetPC () const
bool SetPC (lldb::addr_t new_pc)
lldb::addr_t GetSP () const
lldb::addr_t GetFP () const
lldb::SBAddress GetPCAddress () const
lldb::SBSymbolContext GetSymbolContext (uint32_t resolve_scope) const
lldb::SBModule GetModule () const
lldb::SBCompileUnit GetCompileUnit () const
lldb::SBFunction GetFunction () const
lldb::SBSymbol GetSymbol () const
lldb::SBBlock GetBlock () const
Gets the deepest block that contains the frame PC.
const char * GetFunctionName ()
Get the appropriate function name for this frame.
const char * GetDisplayFunctionName ()
const char * GetFunctionName () const
lldb::LanguageType GuessLanguage () const
bool IsInlined ()
Return true if this frame represents an inlined function.
bool IsInlined () const
bool IsArtificial ()
bool IsArtificial () const
bool IsSynthetic () const
bool IsHidden () const
Return whether a frame recognizer decided this frame should not be displayes in backtraces etc.
lldb::SBValue EvaluateExpression (const char *expr)
The version that doesn't supply a 'use_dynamic' value will use the target's default.
lldb::SBValue EvaluateExpression (const char *expr, lldb::DynamicValueType use_dynamic)
lldb::SBValue EvaluateExpression (const char *expr, lldb::DynamicValueType use_dynamic, bool unwind_on_error)
lldb::SBValue EvaluateExpression (const char *expr, const SBExpressionOptions &options)
SBStructuredData GetLanguageSpecificData () const
Language plugins can use this API to report language-specific runtime information about this compile unit, such as additional language version details or feature flags.
lldb::SBBlock GetFrameBlock () const
Gets the lexical block that defines the stack frame.
lldb::SBLineEntry GetLineEntry () const
lldb::SBThread GetThread () const
const char * Disassemble () const
void Clear ()
bool operator== (const lldb::SBFrame &rhs) const
bool operator!= (const lldb::SBFrame &rhs) const
lldb::SBValueList GetVariables (bool arguments, bool locals, bool statics, bool in_scope_only)
The version that doesn't supply a 'use_dynamic' value will use the target's default.
lldb::SBValueList GetVariables (bool arguments, bool locals, bool statics, bool in_scope_only, lldb::DynamicValueType use_dynamic)
lldb::SBValueList GetVariables (const lldb::SBVariablesOptions &options)
lldb::SBValueList GetRegisters ()
lldb::SBValue FindRegister (const char *name)
lldb::SBValue FindVariable (const char *var_name)
The version that doesn't supply a 'use_dynamic' value will use the target's default.
lldb::SBValue FindVariable (const char *var_name, lldb::DynamicValueType use_dynamic)
lldb::SBValue GetValueForVariablePath (const char *var_expr_cstr, DynamicValueType use_dynamic, lldb::DILMode mode=lldb::eDILModeFull)
lldb::SBValue GetValueForVariablePath (const char *var_path, lldb::DILMode mode=lldb::eDILModeFull)
The version that doesn't supply a 'use_dynamic' value will use the target's default.
lldb::SBValue FindValue (const char *name, ValueType value_type)
Find variables, register sets, registers, or persistent variables using the frame as the scope.
lldb::SBValue FindValue (const char *name, ValueType value_type, lldb::DynamicValueType use_dynamic)
bool GetDescription (lldb::SBStream &description)
SBError GetDescriptionWithFormat (const SBFormat &format, SBStream &output)
Similar to GetDescription() but the format of the description can be configured via the format parameter.
Protected Member Functions
SBFrame (const lldb::StackFrameSP &lldb_object_sp)
lldb::StackFrameSP GetFrameSP () const
void SetFrameSP (const lldb::StackFrameSP &lldb_object_sp)
Static Protected Member Functions
static SBValue CreateProcessIsRunningExprEvalError ()
Return an SBValue containing an error message that warns the process is not currently stopped.
Protected Attributes
lldb::ExecutionContextRefSP m_opaque_sp
Friends
class SBBlock
class SBExecutionContext
class SBFrameList
class SBInstruction
class SBThread
class SBValue
class lldb_private::ScriptInterpreter
class lldb_private::python::SWIGBridge
class lldb_private::lua::SWIGBridge
Detailed Description
Definition at line 26 of file SBFrame.h.
Constructor & Destructor Documentation
SBFrame() [1/3]
SBFrame::SBFrame ()
Definition at line 61 of file SBFrame.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by GetFunctionName(), IsArtificial(), IsEqual(), IsInlined(), lldb_private::lua::SWIGBridge, operator!=(), operator=(), operator==(), and SBFrame().
SBFrame() [2/3]
SBFrame::SBFrame (const lldb::SBFrame & rhs)
Definition at line 70 of file SBFrame.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBFrame().
~SBFrame()
SBFrame::~SBFrame () default
References Clear(), Disassemble(), lldb::eDILModeFull, FindRegister(), FindValue(), FindVariable(), GetBlock(), GetCFA(), GetCompileUnit(), GetDescription(), GetDescriptionWithFormat(), GetDisplayFunctionName(), GetFP(), GetFrameBlock(), GetFrameID(), GetFunction(), GetFunctionName(), GetLanguageSpecificData(), GetLineEntry(), GetModule(), GetPC(), GetPCAddress(), GetRegisters(), GetSP(), GetSymbol(), GetSymbolContext(), GetThread(), GetValueForVariablePath(), GetVariables(), GuessLanguage(), IsArtificial(), IsEqual(), IsHidden(), IsInlined(), IsSynthetic(), IsValid(), operator!=(), operator==(), and SetPC().
SBFrame() [3/3]
SBFrame::SBFrame (const lldb::StackFrameSP & lldb_object_sp) protected
Definition at line 65 of file SBFrame.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Member Function Documentation
Clear()
void SBFrame::Clear ()
Definition at line 360 of file SBFrame.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBFrame().
CreateProcessIsRunningExprEvalError()
lldb::SBValue SBFrame::CreateProcessIsRunningExprEvalError () static protected
Return an SBValue containing an error message that warns the process is not currently stopped.
Definition at line 1007 of file SBFrame.cpp.
References lldb_private::ValueObjectConstResult::Create(), error(), lldb_private::Status::FromErrorString(), SBValue, and lldb::SBValue::SetSP().
Referenced by EvaluateExpression(), EvaluateExpression(), EvaluateExpression(), EvaluateExpression(), and lldb_private::lua::SWIGBridge.
Disassemble()
const char * SBFrame::Disassemble () const
Definition at line 615 of file SBFrame.cpp.
References lldb_private::API, lldb_private::ConstString::GetCString(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBFrame().
EvaluateExpression() [1/4]
SBValue SBFrame::EvaluateExpression (const char * expr)
The version that doesn't supply a 'use_dynamic' value will use the target's default.
Definition at line 930 of file SBFrame.cpp.
References lldb_private::API, lldb_private::StackFrame::CalculateTarget(), CreateProcessIsRunningExprEvalError(), EvaluateExpression(), lldb_private::StackFrame::GetLanguage(), lldb_private::TargetProperties::GetLanguage(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, lldb_private::SourceLanguage::name, SBValue, lldb::SBExpressionOptions::SetFetchDynamicValue(), lldb::SBExpressionOptions::SetIgnoreBreakpoints(), lldb::SBExpressionOptions::SetLanguage(), lldb::SBExpressionOptions::SetUnwindOnError(), and lldb_private::SourceLanguage::version.
Referenced by EvaluateExpression(), EvaluateExpression(), and EvaluateExpression().
EvaluateExpression() [2/4]
lldb::SBValue SBFrame::EvaluateExpression (const char * expr, const SBExpressionOptions & options)
Definition at line 1017 of file SBFrame.cpp.
References lldb_private::API, CreateProcessIsRunningExprEvalError(), lldb_private::StackFrame::DumpUsingSettingsFormat(), lldb_private::Target::EvaluateExpression(), lldb_private::Expressions, lldb_private::StreamString::GetData(), lldb_private::TargetProperties::GetDisplayExpressionsInCrashlogs(), lldb::SBExpressionOptions::GetFetchDynamicValue(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, LLDB_LOGF, m_opaque_sp, lldb::SBExpressionOptions::ref(), SBValue, and lldb::SBValue::SetSP().
EvaluateExpression() [3/4]
SBValue SBFrame::EvaluateExpression (const char * expr, lldb::DynamicValueType use_dynamic)
Definition at line 958 of file SBFrame.cpp.
References lldb_private::API, CreateProcessIsRunningExprEvalError(), EvaluateExpression(), lldb_private::StackFrame::GetLanguage(), lldb_private::TargetProperties::GetLanguage(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, lldb_private::SourceLanguage::name, lldb::SBExpressionOptions::SetFetchDynamicValue(), lldb::SBExpressionOptions::SetIgnoreBreakpoints(), lldb::SBExpressionOptions::SetLanguage(), lldb::SBExpressionOptions::SetUnwindOnError(), and lldb_private::SourceLanguage::version.
EvaluateExpression() [4/4]
SBValue SBFrame::EvaluateExpression (const char * expr, lldb::DynamicValueType use_dynamic, bool unwind_on_error)
Definition at line 982 of file SBFrame.cpp.
References lldb_private::API, CreateProcessIsRunningExprEvalError(), EvaluateExpression(), lldb_private::StackFrame::GetLanguage(), lldb_private::TargetProperties::GetLanguage(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, lldb_private::SourceLanguage::name, SBValue, lldb::SBExpressionOptions::SetFetchDynamicValue(), lldb::SBExpressionOptions::SetIgnoreBreakpoints(), lldb::SBExpressionOptions::SetLanguage(), lldb::SBExpressionOptions::SetUnwindOnError(), and lldb_private::SourceLanguage::version.
FindRegister()
SBValue SBFrame::FindRegister (const char * name)
Definition at line 855 of file SBFrame.cpp.
References lldb_private::API, lldb_private::ValueObjectRegister::Create(), lldb_private::GetLog(), lldb_private::StackFrame::GetRegisterContext(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, SBValue, and lldb::SBValue::SetSP().
Referenced by ~SBFrame().
FindValue() [1/2]
SBValue SBFrame::FindValue (const char * name, ValueType value_type)
Find variables, register sets, registers, or persistent variables using the frame as the scope.
NB. This function does not look up ivars in the function object pointer. To do that use GetValueForVariablePath.
The version that doesn't supply a 'use_dynamic' value will use the target's default.
Definition at line 459 of file SBFrame.cpp.
References lldb_private::API, FindValue(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and SBValue.
Referenced by FindValue(), and ~SBFrame().
FindValue() [2/2]
SBValue SBFrame::FindValue (const char * name, ValueType value_type, lldb::DynamicValueType use_dynamic)
Definition at line 478 of file SBFrame.cpp.
References lldb_private::API, lldb_private::Block::AppendVariables(), lldb_private::VariableList::AppendVariablesIfUnique(), lldb_private::SymbolContext::block, lldb_private::ValueObjectRegister::Create(), lldb_private::ValueObjectRegisterSet::Create(), lldb::eNoDynamicValues, lldb::eValueTypeConstResult, lldb::eValueTypeRegister, lldb::eValueTypeRegisterSet, lldb::eValueTypeVariableArgument, lldb::eValueTypeVariableGlobal, lldb::eValueTypeVariableLocal, lldb::eValueTypeVariableStatic, lldb::eValueTypeVariableThreadLocal, lldb_private::VariableList::FindVariable(), lldb_private::GetLog(), lldb_private::Target::GetPersistentVariable(), lldb_private::StackFrame::GetRegisterContext(), lldb_private::GetStoppedExecutionContext(), lldb_private::StackFrame::GetSymbolContext(), lldb_private::StackFrame::GetValueObjectForFrameVariable(), lldb_private::StackFrame::GetVariableList(), lldb_private::Variable::IsInScope(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, lldb_private::RegisterSet::name, SBValue, lldb::SBValue::SetSP(), and lldb_private::RegisterSet::short_name.
FindVariable() [1/2]
SBValue SBFrame::FindVariable (const char * var_name)
The version that doesn't supply a 'use_dynamic' value will use the target's default.
Definition at line 416 of file SBFrame.cpp.
References lldb_private::API, FindVariable(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and SBValue.
Referenced by FindVariable(), and ~SBFrame().
FindVariable() [2/2]
SBValue SBFrame::FindVariable (const char * var_name, lldb::DynamicValueType use_dynamic)
Definition at line 434 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, SBValue, and lldb::SBValue::SetSP().
GetBlock()
SBBlock SBFrame::GetBlock () const
Gets the deepest block that contains the frame PC.
See also GetFrameBlock().
Definition at line 196 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and SBBlock.
Referenced by ~SBFrame().
GetCFA()
lldb::addr_t SBFrame::GetCFA () const
Definition at line 259 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_INVALID_ADDRESS, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBFrame().
GetCompileUnit()
SBCompileUnit SBFrame::GetCompileUnit () const
Definition at line 150 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and lldb::SBCompileUnit.
Referenced by ~SBFrame().
GetDescription()
bool SBFrame::GetDescription (lldb::SBStream & description)
Definition at line 911 of file SBFrame.cpp.
References lldb_private::API, lldb_private::StackFrame::DumpUsingSettingsFormat(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
Referenced by ~SBFrame().
GetDescriptionWithFormat()
SBError SBFrame::GetDescriptionWithFormat (const SBFormat & format, SBStream & output)
Similar to GetDescription() but the format of the description can be configured via the format parameter.
See https://lldb.llvm.org/use/formatting.html for more information on format strings.
Parameters
[in] format The format to use for generating the description.
[out] output The stream where the description will be written to.
Returns
An error object with an error message in case of failures.
Definition at line 885 of file SBFrame.cpp.
References lldb_private::StackFrame::DumpUsingFormat(), error(), lldb_private::Status::FromError(), lldb::SBFormat::GetFormatEntrySP(), lldb_private::GetStoppedExecutionContext(), m_opaque_sp, and lldb::SBStream::ref().
Referenced by ~SBFrame().
GetDisplayFunctionName()
const char * SBFrame::GetDisplayFunctionName ()
Definition at line 1204 of file SBFrame.cpp.
References lldb_private::API, lldb_private::StackFrame::GetDisplayFunctionName(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBFrame().
GetFP()
addr_t SBFrame::GetFP () const
Definition at line 328 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_INVALID_ADDRESS, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBFrame().
GetFrameBlock()
SBBlock SBFrame::GetFrameBlock () const
Gets the lexical block that defines the stack frame.
Another way to think of this is it will return the block that contains all of the variables for a stack frame. Inlined functions are represented as SBBlock objects that have inlined function information: the name of the inlined function, where it was called from. The block that is returned will be the first block at or above the block for the PC (SBFrame::GetBlock()) that defines the scope of the frame. When a function contains no inlined functions, this will be the top most lexical block that defines the function. When a function has inlined functions and the PC is currently in one of those inlined functions, this method will return the inlined block that defines this frame. If the PC isn't currently in an inlined function, the lexical block that defines the function is returned.
Definition at line 211 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and SBBlock.
Referenced by ~SBFrame().
GetFrameID()
uint32_t SBFrame::GetFrameID () const
Definition at line 242 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and UINT32_MAX.
Referenced by ~SBFrame().
GetFrameSP()
StackFrameSP SBFrame::GetFrameSP () const protected
Definition at line 86 of file SBFrame.cpp.
References m_opaque_sp.
Referenced by lldb::SBInstruction::EmulateWithFrame(), lldb::SBBlock::GetVariables(), IsEqual(), lldb_private::lua::SWIGBridge, operator bool(), lldb::SBThread::ReturnFromFrame(), lldb::SBExecutionContext::SBExecutionContext(), lldb::SBThread::StepOutOfFrame(), and lldb::SBThread::StepOverUntil().
GetFunction()
SBFunction SBFrame::GetFunction () const
Definition at line 166 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and lldb::SBFunction.
Referenced by ~SBFrame().
GetFunctionName() [1/2]
const char * SBFrame::GetFunctionName ()
Get the appropriate function name for this frame.
Inlined functions in LLDB are represented by Blocks that have inlined function information, so just looking at the SBFunction or SBSymbol for a frame isn't enough. This function will return the appropriate function, symbol or inlined function name for the frame.
This function returns:
the name of the inlined function (if there is one)
the name of the concrete function (if there is one)
the name of the symbol (if there is one)
NULL
See also IsInlined().
Definition at line 1168 of file SBFrame.cpp.
References GetFunctionName(), LLDB_INSTRUMENT_VA, and SBFrame().
Referenced by GetFunctionName(), and ~SBFrame().
GetFunctionName() [2/2]
const char * SBFrame::GetFunctionName () const
Definition at line 1189 of file SBFrame.cpp.
References lldb_private::API, lldb_private::StackFrame::GetFunctionName(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
GetLanguageSpecificData()
SBStructuredData SBFrame::GetLanguageSpecificData () const
Language plugins can use this API to report language-specific runtime information about this compile unit, such as additional language version details or feature flags.
Definition at line 1074 of file SBFrame.cpp.
References lldb_private::API, lldb_private::StackFrame::GetLanguageSpecificData(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, lldb::SBStructuredData::m_impl_up, and m_opaque_sp.
Referenced by ~SBFrame().
GetLineEntry()
SBLineEntry SBFrame::GetLineEntry () const
Definition at line 226 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and lldb::SBLineEntry.
Referenced by ~SBFrame().
GetModule()
SBModule SBFrame::GetModule () const
Definition at line 129 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), lldb_private::StackFrame::GetSymbolContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, lldb_private::SymbolContext::module_sp, lldb::SBModule, and lldb::SBModule::SetSP().
Referenced by ~SBFrame().
GetPC()
addr_t SBFrame::GetPC () const
Definition at line 274 of file SBFrame.cpp.
References lldb_private::API, lldb_private::eCode, lldb_private::GetLog(), lldb_private::Target::GetOpcodeLoadAddress(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_INVALID_ADDRESS, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBFrame().
GetPCAddress()
SBAddress SBFrame::GetPCAddress () const
Definition at line 345 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and lldb::SBAddress.
Referenced by ~SBFrame().
GetRegisters()
SBValueList SBFrame::GetRegisters ()
Definition at line 829 of file SBFrame.cpp.
References lldb_private::API, lldb::SBValueList::Append(), lldb_private::ValueObjectRegisterSet::Create(), lldb_private::GetLog(), lldb_private::StackFrame::GetRegisterContext(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and lldb::SBValueList.
Referenced by ~SBFrame().
GetSP()
addr_t SBFrame::GetSP () const
Definition at line 311 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_INVALID_ADDRESS, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBFrame().
GetSymbol()
SBSymbol SBFrame::GetSymbol () const
Definition at line 181 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and lldb::SBSymbol.
Referenced by ~SBFrame().
GetSymbolContext()
SBSymbolContext SBFrame::GetSymbolContext (uint32_t resolve_scope) const
Definition at line 110 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBFrame().
GetThread()
SBThread SBFrame::GetThread () const
Definition at line 599 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and SBThread.
Referenced by lldb::SBThread::StepOutOfFrame(), and ~SBFrame().
GetValueForVariablePath() [1/2]
lldb::SBValue SBFrame::GetValueForVariablePath (const char * var_expr_cstr, DynamicValueType use_dynamic, lldb::DILMode mode = lldb::eDILModeFull)
Definition at line 386 of file SBFrame.cpp.
References lldb_private::API, lldb_private::StackFrame::eExpressionPathOptionCheckPtrVsMember, lldb_private::StackFrame::eExpressionPathOptionsAllowDirectIVarAccess, lldb::eNoDynamicValues, error(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, SBValue, and lldb::SBValue::SetSP().
Referenced by GetValueForVariablePath(), and ~SBFrame().
GetValueForVariablePath() [2/2]
lldb::SBValue SBFrame::GetValueForVariablePath (const char * var_path, lldb::DILMode mode = lldb::eDILModeFull)
The version that doesn't supply a 'use_dynamic' value will use the target's default.
Definition at line 366 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), GetValueForVariablePath(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, and SBValue.
GetVariables() [1/3]
SBValueList SBFrame::GetVariables (bool arguments, bool locals, bool statics, bool in_scope_only)
The version that doesn't supply a 'use_dynamic' value will use the target's default.
Definition at line 631 of file SBFrame.cpp.
References lldb_private::API, lldb_private::TargetProperties::GetDisplayRuntimeSupportValues(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), GetVariables(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, lldb::SBVariablesOptions::SetIncludeArguments(), lldb::SBVariablesOptions::SetIncludeLocals(), lldb::SBVariablesOptions::SetIncludeRuntimeSupportValues(), lldb::SBVariablesOptions::SetIncludeStatics(), lldb::SBVariablesOptions::SetInScopeOnly(), and lldb::SBVariablesOptions::SetUseDynamic().
Referenced by GetVariables(), GetVariables(), and ~SBFrame().
GetVariables() [2/3]
lldb::SBValueList SBFrame::GetVariables (bool arguments, bool locals, bool statics, bool in_scope_only, lldb::DynamicValueType use_dynamic)
Definition at line 663 of file SBFrame.cpp.
References lldb_private::API, lldb_private::TargetProperties::GetDisplayRuntimeSupportValues(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), GetVariables(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, lldb::SBValueList, lldb::SBVariablesOptions::SetIncludeArguments(), lldb::SBVariablesOptions::SetIncludeLocals(), lldb::SBVariablesOptions::SetIncludeRuntimeSupportValues(), lldb::SBVariablesOptions::SetIncludeStatics(), lldb::SBVariablesOptions::SetInScopeOnly(), and lldb::SBVariablesOptions::SetUseDynamic().
GetVariables() [3/3]
SBValueList SBFrame::GetVariables (const lldb::SBVariablesOptions & options)
Definition at line 788 of file SBFrame.cpp.
References lldb_private::API, lldb::SBValueList::Append(), FetchRecognizedArguments(), FetchVariablesUnlessInterrupted(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), lldb::SBVariablesOptions::GetUseDynamic(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_opaque_sp, lldb::SBTarget, SBValue, lldb::SBValueList, lldb::SBValueList::SetError(), lldb::SBValue::SetSP(), and Yes.
GuessLanguage()
lldb::LanguageType SBFrame::GuessLanguage () const
Definition at line 1174 of file SBFrame.cpp.
References lldb_private::API, lldb_private::SourceLanguage::AsLanguageType(), lldb::eLanguageTypeUnknown, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), lldb_private::StackFrame::GuessLanguage(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBFrame().
IsArtificial() [1/2]
bool SBFrame::IsArtificial ()
Definition at line 1114 of file SBFrame.cpp.
References IsArtificial(), LLDB_INSTRUMENT_VA, and SBFrame().
Referenced by IsArtificial(), and ~SBFrame().
IsArtificial() [2/2]
bool SBFrame::IsArtificial () const
Definition at line 1120 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), lldb_private::StackFrame::IsArtificial(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
IsEqual()
bool SBFrame::IsEqual (const lldb::SBFrame & that) const
Definition at line 579 of file SBFrame.cpp.
References GetFrameSP(), LLDB_INSTRUMENT_VA, and SBFrame().
Referenced by operator!=(), operator==(), and ~SBFrame().
IsHidden()
bool SBFrame::IsHidden () const
Return whether a frame recognizer decided this frame should not be displayes in backtraces etc.
Definition at line 1152 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), lldb_private::StackFrame::IsHidden(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBFrame().
IsInlined() [1/2]
bool SBFrame::IsInlined ()
Return true if this frame represents an inlined function.
See also GetFunctionName().
Definition at line 1093 of file SBFrame.cpp.
References IsInlined(), LLDB_INSTRUMENT_VA, and SBFrame().
Referenced by IsInlined(), and ~SBFrame().
IsInlined() [2/2]
bool SBFrame::IsInlined () const
Definition at line 1099 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), lldb_private::StackFrame::IsInlined(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
IsSynthetic()
bool SBFrame::IsSynthetic () const
Definition at line 1136 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), lldb_private::StackFrame::IsSynthetic(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBFrame().
IsValid()
bool SBFrame::IsValid () const
Definition at line 94 of file SBFrame.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBThread::StepOutOfFrame(), and ~SBFrame().
operator bool()
SBFrame::operator bool () const explicit
Definition at line 98 of file SBFrame.cpp.
References lldb_private::API, GetFrameSP(), lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
operator!=()
bool SBFrame::operator!= (const lldb::SBFrame & rhs) const
Definition at line 593 of file SBFrame.cpp.
References IsEqual(), LLDB_INSTRUMENT_VA, and SBFrame().
Referenced by ~SBFrame().
operator=()
const SBFrame & SBFrame::operator= (const lldb::SBFrame & rhs)
Definition at line 78 of file SBFrame.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBFrame().
operator==()
bool SBFrame::operator== (const lldb::SBFrame & rhs) const
Definition at line 587 of file SBFrame.cpp.
References IsEqual(), LLDB_INSTRUMENT_VA, and SBFrame().
Referenced by ~SBFrame().
SetFrameSP()
void SBFrame::SetFrameSP (const lldb::StackFrameSP & lldb_object_sp) protected
Definition at line 90 of file SBFrame.cpp.
References m_opaque_sp.
Referenced by lldb::SBExecutionContext::GetFrame(), lldb::SBValue::GetFrame(), lldb::SBFrameList::GetFrameAtIndex(), lldb::SBThread::GetFrameAtIndex(), lldb::SBThread::GetSelectedFrame(), lldb_private::lua::SWIGBridge, and lldb::SBThread::SetSelectedFrame().
SetPC()
bool SBFrame::SetPC (lldb::addr_t new_pc)
Definition at line 293 of file SBFrame.cpp.
References lldb_private::API, lldb_private::GetLog(), lldb_private::GetStoppedExecutionContext(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, and m_opaque_sp.
Referenced by ~SBFrame().
Friends And Related Symbol Documentation
lldb_private::lua::SWIGBridge
friend class lldb_private::lua::SWIGBridge friend
Definition at line 236 of file SBFrame.h.
References CreateProcessIsRunningExprEvalError(), GetFrameSP(), SBFrame(), SBValue, and SetFrameSP().
lldb_private::python::SWIGBridge
friend class lldb_private::python::SWIGBridge friend
Definition at line 235 of file SBFrame.h.
lldb_private::ScriptInterpreter
friend class lldb_private::ScriptInterpreter friend
Definition at line 234 of file SBFrame.h.
SBBlock
friend class SBBlock friend
Definition at line 227 of file SBFrame.h.
References SBBlock.
Referenced by GetBlock(), GetFrameBlock(), and SBBlock.
SBExecutionContext
friend class SBExecutionContext friend
Definition at line 228 of file SBFrame.h.
References SBExecutionContext.
Referenced by SBExecutionContext.
SBFrameList
friend class SBFrameList friend
Definition at line 229 of file SBFrame.h.
References SBFrameList.
Referenced by SBFrameList.
SBInstruction
friend class SBInstruction friend
Definition at line 230 of file SBFrame.h.
References SBInstruction.
Referenced by SBInstruction.
SBThread
friend class SBThread friend
Definition at line 231 of file SBFrame.h.
References SBThread.
Referenced by GetThread(), and SBThread.
SBValue
friend class SBValue friend
Definition at line 232 of file SBFrame.h.
References SBValue.
Referenced by CreateProcessIsRunningExprEvalError(), EvaluateExpression(), EvaluateExpression(), EvaluateExpression(), FindRegister(), FindValue(), FindValue(), FindVariable(), FindVariable(), GetValueForVariablePath(), GetValueForVariablePath(), GetVariables(), lldb_private::lua::SWIGBridge, and SBValue.
Member Data Documentation
m_opaque_sp
lldb::ExecutionContextRefSP lldb::SBFrame::m_opaque_sp protected
Definition at line 248 of file SBFrame.h.
Referenced by Clear(), Disassemble(), EvaluateExpression(), EvaluateExpression(), EvaluateExpression(), EvaluateExpression(), FindRegister(), FindValue(), FindValue(), FindVariable(), FindVariable(), GetBlock(), GetCFA(), GetCompileUnit(), GetDescription(), GetDescriptionWithFormat(), GetDisplayFunctionName(), GetFP(), GetFrameBlock(), GetFrameID(), GetFrameSP(), GetFunction(), GetFunctionName(), GetLanguageSpecificData(), GetLineEntry(), GetModule(), lldb_private::ScriptInterpreter::GetOpaqueTypeFromSBFrame(), GetPC(), GetPCAddress(), GetRegisters(), GetSP(), GetSymbol(), GetSymbolContext(), GetThread(), GetValueForVariablePath(), GetValueForVariablePath(), GetVariables(), GetVariables(), GetVariables(), GuessLanguage(), IsArtificial(), IsHidden(), IsInlined(), IsSynthetic(), operator bool(), operator=(), SBFrame(), SBFrame(), SBFrame(), SetFrameSP(), and SetPC().
The documentation for this class was generated from the following files:
SBFrame.h
SBFrame.cpp