LLDB: lldb::SBStatisticsOptions Class Reference
lldb::SBStatisticsOptions Class Reference
This class handles the verbosity when dumping statistics.
#include <SBStatisticsOptions.h>
Public Member Functions
SBStatisticsOptions ()
SBStatisticsOptions (const lldb::SBStatisticsOptions &rhs)
~SBStatisticsOptions ()
const SBStatisticsOptions & operator= (const lldb::SBStatisticsOptions &rhs)
void SetSummaryOnly (bool b)
If true, dump only high-level summary statistics.
bool GetSummaryOnly ()
void SetIncludeTargets (bool b)
If true, dump statistics for the targets, including breakpoints, expression evaluations, frame variables, etc.
bool GetIncludeTargets () const
void SetIncludeModules (bool b)
If true, dump statistics for the modules, including time and size of various aspects of the module and debug information, type system, path, etc.
bool GetIncludeModules () const
void SetIncludeTranscript (bool b)
If true and the setting interpreter.save-transcript is enabled, include a JSON array with all commands the user and/or scripts executed during a debug session.
bool GetIncludeTranscript () const
void SetReportAllAvailableDebugInfo (bool b)
If set to true, the debugger will load all debug info that is available and report statistics on the total amount.
bool GetReportAllAvailableDebugInfo ()
Protected Member Functions
const lldb_private::StatisticsOptions & ref () const
Private Attributes
std::unique_ptr< lldb_private::StatisticsOptions > m_opaque_up
Friends
class SBTarget
Detailed Description
This class handles the verbosity when dumping statistics.
Definition at line 17 of file SBStatisticsOptions.h.
Constructor & Destructor Documentation
SBStatisticsOptions() [1/2]
SBStatisticsOptions::SBStatisticsOptions ()
Definition at line 18 of file SBStatisticsOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by operator=(), SBStatisticsOptions(), and ~SBStatisticsOptions().
SBStatisticsOptions() [2/2]
SBStatisticsOptions::SBStatisticsOptions (const lldb::SBStatisticsOptions & rhs)
Definition at line 23 of file SBStatisticsOptions.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBStatisticsOptions().
~SBStatisticsOptions()
SBStatisticsOptions::~SBStatisticsOptions () default
References GetIncludeModules(), GetIncludeTargets(), GetIncludeTranscript(), GetReportAllAvailableDebugInfo(), GetSummaryOnly(), operator=(), SBStatisticsOptions(), SetIncludeModules(), SetIncludeTargets(), SetIncludeTranscript(), SetReportAllAvailableDebugInfo(), and SetSummaryOnly().
Member Function Documentation
GetIncludeModules()
bool SBStatisticsOptions::GetIncludeModules () const
Definition at line 60 of file SBStatisticsOptions.cpp.
References m_opaque_up.
Referenced by ~SBStatisticsOptions().
GetIncludeTargets()
bool SBStatisticsOptions::GetIncludeTargets () const
Definition at line 52 of file SBStatisticsOptions.cpp.
References m_opaque_up.
Referenced by ~SBStatisticsOptions().
GetIncludeTranscript()
bool SBStatisticsOptions::GetIncludeTranscript () const
Definition at line 68 of file SBStatisticsOptions.cpp.
References m_opaque_up.
Referenced by ~SBStatisticsOptions().
GetReportAllAvailableDebugInfo()
bool SBStatisticsOptions::GetReportAllAvailableDebugInfo ()
Definition at line 76 of file SBStatisticsOptions.cpp.
References m_opaque_up.
Referenced by ~SBStatisticsOptions().
GetSummaryOnly()
bool SBStatisticsOptions::GetSummaryOnly ()
Definition at line 44 of file SBStatisticsOptions.cpp.
References m_opaque_up.
Referenced by ~SBStatisticsOptions().
operator=()
const SBStatisticsOptions & SBStatisticsOptions::operator= (const lldb::SBStatisticsOptions & rhs)
Definition at line 32 of file SBStatisticsOptions.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBStatisticsOptions().
Referenced by ~SBStatisticsOptions().
ref()
const lldb_private::StatisticsOptions & SBStatisticsOptions::ref () const protected
Definition at line 80 of file SBStatisticsOptions.cpp.
References m_opaque_up.
Referenced by lldb::SBTarget::GetStatistics(), and SBTarget.
SetIncludeModules()
void SBStatisticsOptions::SetIncludeModules (bool b)
If true, dump statistics for the modules, including time and size of various aspects of the module and debug information, type system, path, etc.
Defaults to true, unless the SummaryOnly mode is enabled, in which case this is turned off unless specified.
If both IncludeTargets and IncludeModules are true, a list of module identifiers will be added to the "targets" section.
Definition at line 56 of file SBStatisticsOptions.cpp.
References m_opaque_up.
Referenced by ~SBStatisticsOptions().
SetIncludeTargets()
void SBStatisticsOptions::SetIncludeTargets (bool b)
If true, dump statistics for the targets, including breakpoints, expression evaluations, frame variables, etc.
Defaults to true, unless the SummaryOnly mode is enabled, in which case this is turned off unless specified.
If both IncludeTargets and IncludeModules are true, a list of module identifiers will be added to the "targets" section.
Definition at line 48 of file SBStatisticsOptions.cpp.
References m_opaque_up.
Referenced by ~SBStatisticsOptions().
SetIncludeTranscript()
void SBStatisticsOptions::SetIncludeTranscript (bool b)
If true and the setting interpreter.save-transcript is enabled, include a JSON array with all commands the user and/or scripts executed during a debug session.
Defaults to false.
Definition at line 64 of file SBStatisticsOptions.cpp.
References m_opaque_up.
Referenced by ~SBStatisticsOptions().
SetReportAllAvailableDebugInfo()
void SBStatisticsOptions::SetReportAllAvailableDebugInfo (bool b)
If set to true, the debugger will load all debug info that is available and report statistics on the total amount.
If this is set to false, then only report statistics on the currently loaded debug information. This can avoid loading debug info from separate files just so it can report the total size which can slow down statistics reporting.
Definition at line 72 of file SBStatisticsOptions.cpp.
References m_opaque_up.
Referenced by ~SBStatisticsOptions().
SetSummaryOnly()
void SBStatisticsOptions::SetSummaryOnly (bool b)
If true, dump only high-level summary statistics.
Exclude details like targets, modules, breakpoints, etc. This turns off IncludeTargets, IncludeModules and IncludeTranscript by default.
Defaults to false.
Definition at line 40 of file SBStatisticsOptions.cpp.
References m_opaque_up.
Referenced by ~SBStatisticsOptions().
Friends And Related Symbol Documentation
SBTarget
friend class SBTarget friend
Definition at line 73 of file SBStatisticsOptions.h.
References ref(), and SBTarget.
Referenced by SBTarget.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::StatisticsOptions> lldb::SBStatisticsOptions::m_opaque_up private
Definition at line 77 of file SBStatisticsOptions.h.
Referenced by GetIncludeModules(), GetIncludeTargets(), GetIncludeTranscript(), GetReportAllAvailableDebugInfo(), GetSummaryOnly(), operator=(), ref(), SBStatisticsOptions(), SBStatisticsOptions(), SetIncludeModules(), SetIncludeTargets(), SetIncludeTranscript(), SetReportAllAvailableDebugInfo(), and SetSummaryOnly().
The documentation for this class was generated from the following files:
SBStatisticsOptions.h
SBStatisticsOptions.cpp