LLDB: ClangDiagnosticManagerAdapter Class Reference
ClangDiagnosticManagerAdapter Class Reference
Public Member Functions
ClangDiagnosticManagerAdapter (DiagnosticOptions &opts, StringRef filename)
void ResetManager (DiagnosticManager *manager=nullptr)
ClangDiagnostic * MaybeGetLastClangDiag () const
Returns the last error ClangDiagnostic message that the DiagnosticManager received or a nullptr.
void HandleDiagnostic (DiagnosticsEngine::Level DiagLevel, const clang::Diagnostic &Info) override
void BeginSourceFile (const LangOptions &LO, const Preprocessor *PP) override
void EndSourceFile () override
Private Attributes
DiagnosticManager * m_manager = nullptr
DiagnosticOptions m_options
std::string m_output
Output string filled by m_os.
std::unique_ptr< llvm::raw_string_ostream > m_os
Output stream of m_passthrough.
std::unique_ptr< clang::TextDiagnosticPrinter > m_passthrough
StringRef m_filename
Detailed Description
Definition at line 168 of file ClangExpressionParser.cpp.
Constructor & Destructor Documentation
ClangDiagnosticManagerAdapter()
ClangDiagnosticManagerAdapter::ClangDiagnosticManagerAdapter (DiagnosticOptions & opts, StringRef filename) inline
Definition at line 170 of file ClangExpressionParser.cpp.
References m_filename, m_options, m_os, m_output, and m_passthrough.
Member Function Documentation
BeginSourceFile()
void ClangDiagnosticManagerAdapter::BeginSourceFile (const LangOptions & LO, const Preprocessor * PP) inline override
Definition at line 309 of file ClangExpressionParser.cpp.
References m_passthrough.
Referenced by lldb_private::ClangExpressionParser::ParseInternal().
EndSourceFile()
void ClangDiagnosticManagerAdapter::EndSourceFile () inline override
Definition at line 313 of file ClangExpressionParser.cpp.
References m_passthrough.
Referenced by lldb_private::ClangExpressionParser::ParseInternal().
HandleDiagnostic()
void ClangDiagnosticManagerAdapter::HandleDiagnostic (DiagnosticsEngine::Level DiagLevel, const clang::Diagnostic & Info) inline override
Definition at line 201 of file ClangExpressionParser.cpp.
References AddAllFixIts(), lldb_private::DiagnosticDetail::SourceLocation::column, lldb::eSeverityError, lldb::eSeverityInfo, lldb::eSeverityWarning, lldb_private::Expressions, lldb_private::DiagnosticDetail::SourceLocation::file, lldb_private::GetLog(), lldb_private::DiagnosticDetail::SourceLocation::hidden, lldb_private::DiagnosticDetail::SourceLocation::in_user_input, lldb_private::DiagnosticDetail::SourceLocation::length, lldb_private::DiagnosticDetail::SourceLocation::line, LLDB_LOG, m_filename, m_manager, m_output, m_passthrough, MaybeGetLastClangDiag(), lldb_private::DiagnosticDetail::message, lldb_private::DiagnosticDetail::rendered, lldb_private::DiagnosticDetail::severity, and lldb_private::DiagnosticDetail::source_location.
MaybeGetLastClangDiag()
ClangDiagnostic * ClangDiagnosticManagerAdapter::MaybeGetLastClangDiag () const inline
Returns the last error ClangDiagnostic message that the DiagnosticManager received or a nullptr.
Definition at line 185 of file ClangExpressionParser.cpp.
References lldb::eSeverityError, lldb::eSeverityWarning, and m_manager.
Referenced by HandleDiagnostic().
ResetManager()
void ClangDiagnosticManagerAdapter::ResetManager (DiagnosticManager * manager = nullptr) inline
Definition at line 179 of file ClangExpressionParser.cpp.
References m_manager.
Referenced by lldb_private::ClangExpressionParser::ParseInternal().
Member Data Documentation
m_filename
StringRef ClangDiagnosticManagerAdapter::m_filename private
Definition at line 323 of file ClangExpressionParser.cpp.
Referenced by ClangDiagnosticManagerAdapter(), and HandleDiagnostic().
m_manager
DiagnosticManager* ClangDiagnosticManagerAdapter::m_manager = nullptr private
Definition at line 316 of file ClangExpressionParser.cpp.
Referenced by HandleDiagnostic(), MaybeGetLastClangDiag(), and ResetManager().
m_options
DiagnosticOptions ClangDiagnosticManagerAdapter::m_options private
Definition at line 317 of file ClangExpressionParser.cpp.
Referenced by ClangDiagnosticManagerAdapter().
m_os
std::unique_ptr<llvm::raw_string_ostream> ClangDiagnosticManagerAdapter::m_os private
Output stream of m_passthrough.
Definition at line 321 of file ClangExpressionParser.cpp.
Referenced by ClangDiagnosticManagerAdapter().
m_output
std::string ClangDiagnosticManagerAdapter::m_output private
Output string filled by m_os.
Definition at line 319 of file ClangExpressionParser.cpp.
Referenced by ClangDiagnosticManagerAdapter(), and HandleDiagnostic().
m_passthrough
std::unique_ptr<clang::TextDiagnosticPrinter> ClangDiagnosticManagerAdapter::m_passthrough private
Definition at line 322 of file ClangExpressionParser.cpp.
Referenced by BeginSourceFile(), ClangDiagnosticManagerAdapter(), EndSourceFile(), and HandleDiagnostic().
The documentation for this class was generated from the following file:
ClangExpressionParser.cpp