LLDB: ABISysV_s390x Class Reference
ABISysV_s390x Class Reference
#include <ABISysV_s390x.h>
Public Member Functions
~ABISysV_s390x () override=default
size_t GetRedZoneSize () const override
bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override
bool GetArgumentValues (lldb_private::Thread &thread, lldb_private::ValueList &values) const override
lldb_private::Status SetReturnValueObject (lldb::StackFrameSP &frame_sp, lldb::ValueObjectSP &new_value) override
lldb::ValueObjectSP GetReturnValueObjectImpl (lldb_private::Thread &thread, lldb_private::CompilerType &type) const override
lldb::UnwindPlanSP CreateFunctionEntryUnwindPlan () override
lldb::UnwindPlanSP CreateDefaultUnwindPlan () override
bool RegisterIsVolatile (const lldb_private::RegisterInfo *reg_info) override
bool GetFallbackRegisterLocation (const lldb_private::RegisterInfo *reg_info, lldb_private::UnwindPlan::Row::AbstractRegisterLocation &unwind_regloc) override
bool CallFrameAddressIsValid (lldb::addr_t cfa) override
bool CodeAddressIsValid (lldb::addr_t pc) override
const lldb_private::RegisterInfo * GetRegisterInfoArray (uint32_t &count) override
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::RegInfoBasedABI
void AugmentRegisterInfo (std::vector< DynamicRegisterInfo::Register > &regs) override
Public Member Functions inherited from lldb_private::ABI
~ABI () override
virtual bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::Type &prototype, llvm::ArrayRef< CallArgument > args) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, CompilerType &type, bool persistent=true) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, llvm::Type &type, bool persistent=true) const
virtual lldb::addr_t FixAnyAddress (lldb::addr_t pc)
Use this method when you do not know, or do not care what kind of address you are fixing.
llvm::MCRegisterInfo & GetMCRegisterInfo ()
virtual bool GetPointerReturnRegister (const char *&name)
virtual uint64_t GetStackFrameSize ()
virtual lldb::addr_t FixCodeAddress (lldb::addr_t pc)
Some targets might use bits in a code address to indicate a mode switch.
virtual lldb::addr_t FixDataAddress (lldb::addr_t pc)
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static lldb::ABISP CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec &arch)
static llvm::StringRef GetPluginNameStatic ()
Static Public Member Functions inherited from lldb_private::ABI
static lldb::ABISP FindPlugin (lldb::ProcessSP process_sp, const ArchSpec &arch)
Protected Member Functions
void CreateRegisterMapIfNeeded ()
lldb::ValueObjectSP GetReturnValueObjectSimple (lldb_private::Thread &thread, lldb_private::CompilerType &ast_type) const
bool RegisterIsCalleeSaved (const lldb_private::RegisterInfo *reg_info)
Protected Member Functions inherited from lldb_private::RegInfoBasedABI
bool GetRegisterInfoByName (llvm::StringRef name, RegisterInfo &info)
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Protected Member Functions inherited from lldb_private::ABI
virtual lldb::ValueObjectSP GetReturnValueObjectImpl (Thread &thread, llvm::Type &ir_type) const
lldb::ProcessSP GetProcessSP () const
Request to get a Process shared pointer.
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Additional Inherited Members
Static Protected Member Functions inherited from lldb_private::ABI
static std::unique_ptr< llvm::MCRegisterInfo > MakeMCRegisterInfo (const ArchSpec &arch)
Utility function to construct a MCRegisterInfo using the ArchSpec triple.
Protected Attributes inherited from lldb_private::ABI
lldb::ProcessWP m_process_wp
std::unique_ptr< llvm::MCRegisterInfo > m_mc_register_info_up
Detailed Description
Definition at line 15 of file ABISysV_s390x.h.
Constructor & Destructor Documentation
~ABISysV_s390x()
ABISysV_s390x::~ABISysV_s390x () override default
References sp.
Member Function Documentation
CallFrameAddressIsValid()
bool ABISysV_s390x::CallFrameAddressIsValid (lldb::addr_t cfa) inline override virtual
Implements lldb_private::ABI.
Definition at line 48 of file ABISysV_s390x.h.
CodeAddressIsValid()
bool ABISysV_s390x::CodeAddressIsValid (lldb::addr_t pc) inline override virtual
Implements lldb_private::ABI.
Definition at line 57 of file ABISysV_s390x.h.
References pc.
CreateDefaultUnwindPlan()
UnwindPlanSP ABISysV_s390x::CreateDefaultUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 631 of file ABISysV_s390x.cpp.
CreateFunctionEntryUnwindPlan()
UnwindPlanSP ABISysV_s390x::CreateFunctionEntryUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 614 of file ABISysV_s390x.cpp.
References dwarf_pswa_s390x, dwarf_r14_s390x, dwarf_r15_s390x, lldb_private::eLazyBoolNo, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), and lldb_private::UnwindPlan::Row::SetRegisterLocationToRegister().
CreateInstance()
ABISP ABISysV_s390x::CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec & arch) static
Definition at line 189 of file ABISysV_s390x.cpp.
References lldb_private::ArchSpec::GetTriple(), and lldb_private::ABI::MakeMCRegisterInfo().
Referenced by Initialize(), and Terminate().
CreateRegisterMapIfNeeded()
void ABISysV_s390x::CreateRegisterMapIfNeeded () protected
GetArgumentValues()
bool ABISysV_s390x::GetArgumentValues (lldb_private::Thread & thread, lldb_private::ValueList & values) const override virtual
Implements lldb_private::ABI.
Definition at line 309 of file ABISysV_s390x.cpp.
References lldb::eRegisterKindGeneric, lldb::eRegisterKindLLDB, lldb_private::CompilerType::GetBitSize(), lldb_private::Value::GetCompilerType(), lldb_private::RegisterContext::GetRegisterInfo(), lldb_private::Value::GetScalar(), lldb_private::ValueList::GetSize(), lldb_private::RegisterContext::GetSP(), lldb_private::ValueList::GetValueAtIndex(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), lldb_private::CompilerType::IsPointerType(), lldb_private::RegisterInfo::kinds, LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_ARG2, LLDB_REGNUM_GENERIC_ARG3, LLDB_REGNUM_GENERIC_ARG4, LLDB_REGNUM_GENERIC_ARG5, ReadIntegerArgument(), and sp.
GetFallbackRegisterLocation()
bool ABISysV_s390x::GetFallbackRegisterLocation (const lldb_private::RegisterInfo * reg_info, lldb_private::UnwindPlan::Row::AbstractRegisterLocation & unwind_regloc) override virtual
Reimplemented from lldb_private::ABI.
Definition at line 637 of file ABISysV_s390x.cpp.
References RegisterIsVolatile(), and lldb_private::UnwindPlan::Row::AbstractRegisterLocation::SetUndefined().
GetPluginName()
llvm::StringRef ABISysV_s390x::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 77 of file ABISysV_s390x.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef ABISysV_s390x::GetPluginNameStatic () inline static
Definition at line 73 of file ABISysV_s390x.h.
Referenced by GetPluginName(), and Initialize().
GetRedZoneSize()
size_t ABISysV_s390x::GetRedZoneSize () const override virtual
Implements lldb_private::ABI.
Definition at line 184 of file ABISysV_s390x.cpp.
GetRegisterInfoArray()
const lldb_private::RegisterInfo * ABISysV_s390x::GetRegisterInfoArray (uint32_t & count) override virtual
Implements lldb_private::RegInfoBasedABI.
Definition at line 179 of file ABISysV_s390x.cpp.
References g_register_infos, and k_num_register_infos.
GetReturnValueObjectImpl()
ValueObjectSP ABISysV_s390x::GetReturnValueObjectImpl (lldb_private::Thread & thread, lldb_private::CompilerType & type) const override virtual
Implements lldb_private::ABI.
Definition at line 579 of file ABISysV_s390x.cpp.
References lldb_private::ValueObjectMemory::Create(), lldb::eRegisterKindLLDB, GetReturnValueObjectSimple(), and lldb_private::CompilerType::IsAggregateType().
GetReturnValueObjectSimple()
ValueObjectSP ABISysV_s390x::GetReturnValueObjectSimple (lldb_private::Thread & thread, lldb_private::CompilerType & ast_type) const protected
Definition at line 470 of file ABISysV_s390x.cpp.
References lldb_private::ValueObjectConstResult::Create(), lldb::eRegisterKindLLDB, lldb_private::CompilerType::GetByteSize(), lldb_private::RegisterValue::GetData(), lldb_private::DataExtractor::GetDouble(), lldb_private::DataExtractor::GetFloat(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::Value::GetScalar(), lldb_private::CompilerType::GetTypeInfo(), lldb_private::RegisterInfo::kinds, lldb_private::RegisterContext::ReadRegister(), lldb_private::Value::Scalar, lldb_private::Value::SetCompilerType(), lldb_private::Value::SetValueType(), and UINT32_MAX.
Referenced by GetReturnValueObjectImpl().
Initialize()
void ABISysV_s390x::Initialize () static
Definition at line 706 of file ABISysV_s390x.cpp.
References CreateInstance(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
PrepareTrivialCall()
bool ABISysV_s390x::PrepareTrivialCall (lldb_private::Thread & thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override virtual
Implements lldb_private::ABI.
Definition at line 196 of file ABISysV_s390x.cpp.
References lldb::eRegisterKindGeneric, error(), lldb_private::Expressions, lldb_private::GetLog(), lldb_private::RegisterContext::GetRegisterInfo(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::StreamString::GetString(), LLDB_LOGF, LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_SP, lldb_private::RegisterInfo::name, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), lldb_private::Log::PutString(), sp, and lldb_private::RegisterContext::WriteRegisterFromUnsigned().
RegisterIsCalleeSaved()
bool ABISysV_s390x::RegisterIsCalleeSaved (const lldb_private::RegisterInfo * reg_info) protected
Definition at line 655 of file ABISysV_s390x.cpp.
References lldb_private::RegisterInfo::name.
Referenced by RegisterIsVolatile().
RegisterIsVolatile()
bool ABISysV_s390x::RegisterIsVolatile (const lldb_private::RegisterInfo * reg_info) override virtual
Implements lldb_private::ABI.
Definition at line 651 of file ABISysV_s390x.cpp.
References RegisterIsCalleeSaved().
Referenced by GetFallbackRegisterLocation().
SetReturnValueObject()
Status ABISysV_s390x::SetReturnValueObject (lldb::StackFrameSP & frame_sp, lldb::ValueObjectSP & new_value) override virtual
Implements lldb_private::ABI.
Definition at line 379 of file ABISysV_s390x.cpp.
References lldb_private::Status::AsCString(), lldb_private::DataExtractor::CopyByteOrderedData(), error(), lldb_private::Status::Fail(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::CompilerType::GetBitSize(), lldb_private::DataExtractor::GetByteOrder(), lldb_private::DataExtractor::GetMaxU64(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), lldb_private::CompilerType::IsPointerType(), lldb_private::CompilerType::IsRealFloatingPointType(), lldb_private::RegisterValue::SetBytes(), lldb_private::RegisterContext::WriteRegister(), and lldb_private::RegisterContext::WriteRegisterFromUnsigned().
Terminate()
void ABISysV_s390x::Terminate () static
Definition at line 711 of file ABISysV_s390x.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
The documentation for this class was generated from the following files:
ABISysV_s390x.h
ABISysV_s390x.cpp