LLDB: OptionPermissions Class Reference
OptionPermissions Class Reference
Public Member Functions
OptionPermissions ()=default
~OptionPermissions () override=default
lldb_private::Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext *execution_context) override
void OptionParsingStarting (ExecutionContext *execution_context) override
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Public Attributes
uint32_t m_permissions
Private Member Functions
OptionPermissions (const OptionPermissions &)=delete
const OptionPermissions & operator= (const OptionPermissions &)=delete
Detailed Description
Definition at line 66 of file CommandObjectPlatform.cpp.
Constructor & Destructor Documentation
OptionPermissions() [1/2]
OptionPermissions::OptionPermissions () default
Referenced by operator=(), and OptionPermissions().
~OptionPermissions()
OptionPermissions::~OptionPermissions () override default
OptionPermissions() [2/2]
OptionPermissions::OptionPermissions (const OptionPermissions &) private delete
References OptionPermissions().
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > OptionPermissions::GetDefinitions () inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 132 of file CommandObjectPlatform.cpp.
Referenced by SetOptionValue().
operator=()
const OptionPermissions & OptionPermissions::operator= (const OptionPermissions &) private delete
References OptionPermissions().
OptionParsingStarting()
void OptionPermissions::OptionParsingStarting (ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 128 of file CommandObjectPlatform.cpp.
References m_permissions.
SetOptionValue()
lldb_private::Status OptionPermissions::SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 73 of file CommandObjectPlatform.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormat(), GetDefinitions(), m_permissions, and ParsePermissionString().
Member Data Documentation
m_permissions
uint32_t OptionPermissions::m_permissions
Definition at line 138 of file CommandObjectPlatform.cpp.
Referenced by CommandObjectPlatformFOpen::DoExecute(), CommandObjectPlatformMkDir::DoExecute(), OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following file:
CommandObjectPlatform.cpp