LLDB: lldb_private::ScriptedInterface Class Reference
lldb_private::ScriptedInterface Class Reference abstract
#include <ScriptedInterface.h>
Classes
struct AbstractMethodRequirement
Public Member Functions
ScriptedInterface ()=default
virtual ~ScriptedInterface ()=default
StructuredData::GenericSP GetScriptObjectInstance ()
virtual llvm::SmallVector< AbstractMethodRequirement > GetAbstractMethodRequirements () const =0
virtual llvm::Expected< FileSpec > GetScriptedModulePath ()
llvm::SmallVector< llvm::StringLiteral > const GetAbstractMethods () const
Static Public Member Functions
template<typename Ret>
static Ret ErrorWithMessage (llvm::StringRef caller_name, llvm::StringRef error_msg, Status &error, LLDBLog log_category=LLDBLog::Process)
template<typename T = StructuredData::ObjectSP>
static bool CheckStructuredDataObject (llvm::StringRef caller, T obj, Status &error)
static bool CreateInstance (lldb::ScriptLanguage language, ScriptedInterfaceUsages usages)
Protected Attributes
StructuredData::GenericSP m_object_instance_sp
Detailed Description
Definition at line 25 of file ScriptedInterface.h.
Constructor & Destructor Documentation
ScriptedInterface()
lldb_private::ScriptedInterface::ScriptedInterface () default
Referenced by lldb_private::ScriptedPythonInterface::ScriptedPythonInterface().
~ScriptedInterface()
virtual lldb_private::ScriptedInterface::~ScriptedInterface () virtual default
Member Function Documentation
CheckStructuredDataObject()
template<typename T = StructuredData::ObjectSP> bool lldb_private::ScriptedInterface::CheckStructuredDataObject (llvm::StringRef caller, T obj, Status & error) inline static
Definition at line 75 of file ScriptedInterface.h.
References error(), and ErrorWithMessage().
Referenced by lldb_private::ScriptedFrameProviderPythonInterface::AppliesToThread(), lldb_private::ScriptedProcessPythonInterface::CreateBreakpoint(), lldb_private::OperatingSystemPythonInterface::CreateThread(), lldb_private::OperatingSystemPythonInterface::DoesPluginReportAllThreads(), lldb_private::ScriptedThreadPlanPythonInterface::ExplainsStop(), lldb_private::ScriptedProcessPythonInterface::GetCapabilities(), lldb_private::ScriptedBreakpointPythonInterface::GetDepth(), lldb_private::ScriptedFrameProviderPythonInterface::GetDescription(), lldb_private::ScriptedFramePythonInterface::GetDisplayFunctionName(), lldb_private::ScriptedThreadPythonInterface::GetExtendedInfo(), lldb_private::ScriptedFrameProviderPythonInterface::GetFrameAtIndex(), lldb_private::ScriptedFramePythonInterface::GetFunctionName(), lldb_private::ScriptedFramePythonInterface::GetID(), lldb_private::ScriptedProcessPythonInterface::GetLoadedImages(), lldb_private::ScriptedBreakpointPythonInterface::GetLocationDescription(), lldb_private::ScriptedProcessPythonInterface::GetMetadata(), lldb_private::ScriptedThreadPythonInterface::GetName(), lldb_private::ScriptedFramePythonInterface::GetPC(), lldb_private::ScriptedFrameProviderPythonInterface::GetPriority(), lldb_private::ScriptedProcessPythonInterface::GetProcessID(), lldb_private::ScriptedThreadPythonInterface::GetQueue(), lldb_private::ScriptedFramePythonInterface::GetRegisterContext(), lldb_private::ScriptedThreadPythonInterface::GetRegisterContext(), lldb_private::OperatingSystemPythonInterface::GetRegisterContextForTID(), lldb_private::ScriptedFramePythonInterface::GetRegisterInfo(), lldb_private::ScriptedThreadPythonInterface::GetRegisterInfo(), lldb_private::ScriptedThreadPlanPythonInterface::GetRunState(), lldb_private::ScriptedThreadPythonInterface::GetScriptedFramePluginName(), lldb_private::ScriptedProcessPythonInterface::GetScriptedThreadPluginName(), lldb_private::ScriptedBreakpointPythonInterface::GetShortHelp(), lldb_private::ScriptedThreadPythonInterface::GetStackFrames(), lldb_private::ScriptedThreadPythonInterface::GetState(), lldb_private::ScriptedThreadPythonInterface::GetStopReason(), lldb_private::ScriptedThreadPythonInterface::GetThreadID(), lldb_private::OperatingSystemPythonInterface::GetThreadInfo(), lldb_private::ScriptedProcessPythonInterface::GetThreadsInfo(), lldb_private::ScriptedStopHookPythonInterface::HandleStop(), lldb_private::ScriptedProcessPythonInterface::IsAlive(), lldb_private::ScriptedFramePythonInterface::IsArtificial(), lldb_private::ScriptedFramePythonInterface::IsHidden(), lldb_private::ScriptedFramePythonInterface::IsInlined(), lldb_private::ScriptedThreadPlanPythonInterface::IsStale(), lldb_private::ScriptedBreakpointPythonInterface::ResolverCallback(), lldb_private::ScriptedThreadPlanPythonInterface::ShouldStop(), and lldb_private::ScriptedProcessPythonInterface::WriteMemoryAtAddress().
CreateInstance()
bool lldb_private::ScriptedInterface::CreateInstance (lldb::ScriptLanguage language, ScriptedInterfaceUsages usages) inline static
Definition at line 92 of file ScriptedInterface.h.
Referenced by lldb_private::OperatingSystemPythonInterface::Initialize(), lldb_private::ScriptedBreakpointPythonInterface::Initialize(), lldb_private::ScriptedPlatformPythonInterface::Initialize(), lldb_private::ScriptedProcessPythonInterface::Initialize(), lldb_private::ScriptedStopHookPythonInterface::Initialize(), lldb_private::ScriptedThreadPlanPythonInterface::Initialize(), lldb_private::OperatingSystemPythonInterface::Terminate(), lldb_private::ScriptedBreakpointPythonInterface::Terminate(), lldb_private::ScriptedPlatformPythonInterface::Terminate(), lldb_private::ScriptedProcessPythonInterface::Terminate(), lldb_private::ScriptedStopHookPythonInterface::Terminate(), and lldb_private::ScriptedThreadPlanPythonInterface::Terminate().
ErrorWithMessage()
template<typename Ret> Ret lldb_private::ScriptedInterface::ErrorWithMessage (llvm::StringRef caller_name, llvm::StringRef error_msg, Status & error, LLDBLog log_category = LLDBLog::Process) inline static
Definition at line 56 of file ScriptedInterface.h.
References error(), lldb_private::GetLog(), LLDB_LOGF, lldb_private::Process, and lldb_private::Status.
Referenced by lldb_private::ScriptedThread::CalculateStopInfo(), lldb_private::ScriptedPythonInterface::CallStaticMethod(), CheckStructuredDataObject(), lldb_private::ScriptedThread::CreateRegisterContextForFrame(), lldb_private::ScriptedPythonInterface::Dispatch(), lldb_private::ScriptedProcess::DoReadMemory(), lldb_private::ScriptedProcess::DoUpdateThreadList(), lldb_private::ScriptedProcess::DoWriteMemory(), lldb_private::ScriptedThread::FetchThreadExtendedInfo(), lldb_private::ScriptedFrame::GetDynamicRegisterInfo(), lldb_private::ScriptedThread::GetDynamicRegisterInfo(), lldb_private::ScriptedFrameProvider::GetFrameAtIndex(), lldb_private::ScriptedProcess::GetLoadedDynamicLibrariesInfos(), lldb_private::ScriptedProcessPythonInterface::GetMemoryRegionContainingAddress(), lldb_private::ScriptedProcess::GetMetadata(), lldb_private::ScriptedPlatformPythonInterface::GetProcessInfo(), lldb_private::ScriptedFrame::GetRegisterContext(), lldb_private::ScriptedFramePythonInterface::GetSymbolContext(), lldb_private::ScriptedFramePythonInterface::GetValueObjectForVariableExpression(), lldb_private::ScriptedFramePythonInterface::GetVariables(), lldb_private::ScriptedPlatformPythonInterface::ListProcesses(), and lldb_private::ScriptedThread::LoadArtificialStackFrames().
GetAbstractMethodRequirements()
virtual llvm::SmallVector< AbstractMethodRequirement > lldb_private::ScriptedInterface::GetAbstractMethodRequirements () const pure virtual
Implemented in lldb_private::OperatingSystemPythonInterface, lldb_private::ScriptedBreakpointPythonInterface, lldb_private::ScriptedFrameProviderPythonInterface, lldb_private::ScriptedFramePythonInterface, lldb_private::ScriptedPlatformPythonInterface, lldb_private::ScriptedProcessPythonInterface, lldb_private::ScriptedStopHookPythonInterface, lldb_private::ScriptedThreadPlanPythonInterface, and lldb_private::ScriptedThreadPythonInterface.
Referenced by lldb_private::ScriptedPythonInterface::CheckAbstractMethodImplementation(), and GetAbstractMethods().
GetAbstractMethods()
llvm::SmallVector< llvm::StringLiteral > const lldb_private::ScriptedInterface::GetAbstractMethods () const inline
Definition at line 46 of file ScriptedInterface.h.
References GetAbstractMethodRequirements().
Referenced by lldb_private::ScriptedPythonInterface::Dispatch().
GetScriptedModulePath()
virtual llvm::Expected< FileSpec > lldb_private::ScriptedInterface::GetScriptedModulePath () inline virtual
Reimplemented in lldb_private::ScriptedPythonInterface.
Definition at line 42 of file ScriptedInterface.h.
GetScriptObjectInstance()
StructuredData::GenericSP lldb_private::ScriptedInterface::GetScriptObjectInstance () inline
Definition at line 30 of file ScriptedInterface.h.
References m_object_instance_sp.
Referenced by lldb_private::ScriptedProcess::GetImplementation().
Member Data Documentation
m_object_instance_sp
StructuredData::GenericSP lldb_private::ScriptedInterface::m_object_instance_sp protected
Definition at line 98 of file ScriptedInterface.h.
Referenced by lldb_private::ScriptedPythonInterface::CreatePluginObject(), lldb_private::ScriptedPythonInterface::Dispatch(), lldb_private::ScriptedPythonInterface::GetScriptedModulePath(), and GetScriptObjectInstance().
The documentation for this class was generated from the following file:
ScriptedInterface.h