LLDB: lldb_private::AppleObjCExternalASTSource Class Reference
lldb_private::AppleObjCExternalASTSource Class Reference
Public Member Functions
AppleObjCExternalASTSource (AppleObjCDeclVendor &decl_vendor)
bool FindExternalVisibleDeclsByName (const clang::DeclContext *decl_ctx, clang::DeclarationName name, const clang::DeclContext *original_dc) override
void CompleteType (clang::TagDecl *tag_decl) override
void CompleteType (clang::ObjCInterfaceDecl *interface_decl) override
bool layoutRecordType (const clang::RecordDecl *Record, uint64_t &Size, uint64_t &Alignment, llvm::DenseMap< const clang::FieldDecl *, uint64_t > &FieldOffsets, llvm::DenseMap< const clang::CXXRecordDecl *, clang::CharUnits > &BaseOffsets, llvm::DenseMap< const clang::CXXRecordDecl *, clang::CharUnits > &VirtualBaseOffsets) override
void StartTranslationUnit (clang::ASTConsumer *Consumer) override
Private Attributes
AppleObjCDeclVendor & m_decl_vendor
Detailed Description
Definition at line 26 of file AppleObjCDeclVendor.cpp.
Constructor & Destructor Documentation
AppleObjCExternalASTSource()
lldb_private::AppleObjCExternalASTSource::AppleObjCExternalASTSource (AppleObjCDeclVendor & decl_vendor) inline
Definition at line 29 of file AppleObjCDeclVendor.cpp.
References m_decl_vendor.
Member Function Documentation
CompleteType() [1/2]
void lldb_private::AppleObjCExternalASTSource::CompleteType (clang::ObjCInterfaceDecl * interface_decl) inline override
Definition at line 87 of file AppleObjCDeclVendor.cpp.
References lldb_private::ClangUtil::DumpDecl(), lldb_private::Expressions, lldb_private::GetLog(), LLDB_LOG, LLDB_LOGF, and m_decl_vendor.
CompleteType() [2/2]
void lldb_private::AppleObjCExternalASTSource::CompleteType (clang::TagDecl * tag_decl) inline override
Definition at line 71 of file AppleObjCDeclVendor.cpp.
References lldb_private::ClangUtil::DumpDecl(), lldb_private::Expressions, lldb_private::GetLog(), LLDB_LOG, and LLDB_LOGF.
FindExternalVisibleDeclsByName()
bool lldb_private::AppleObjCExternalASTSource::FindExternalVisibleDeclsByName (const clang::DeclContext * decl_ctx, clang::DeclarationName name, const clang::DeclContext * original_dc) inline override
Definition at line 32 of file AppleObjCDeclVendor.cpp.
References lldb_private::Expressions, lldb_private::GetLog(), LLDB_LOGF, and m_decl_vendor.
layoutRecordType()
bool lldb_private::AppleObjCExternalASTSource::layoutRecordType (const clang::RecordDecl * Record, uint64_t & Size, uint64_t & Alignment, llvm::DenseMap< const clang::FieldDecl *, uint64_t > & FieldOffsets, llvm::DenseMap< const clang::CXXRecordDecl *, clang::CharUnits > & BaseOffsets, llvm::DenseMap< const clang::CXXRecordDecl *, clang::CharUnits > & VirtualBaseOffsets) inline override
Definition at line 112 of file AppleObjCDeclVendor.cpp.
StartTranslationUnit()
void lldb_private::AppleObjCExternalASTSource::StartTranslationUnit (clang::ASTConsumer * Consumer) inline override
Definition at line 122 of file AppleObjCDeclVendor.cpp.
References m_decl_vendor.
Member Data Documentation
m_decl_vendor
AppleObjCDeclVendor& lldb_private::AppleObjCExternalASTSource::m_decl_vendor private
Definition at line 130 of file AppleObjCDeclVendor.cpp.
Referenced by AppleObjCExternalASTSource(), CompleteType(), FindExternalVisibleDeclsByName(), and StartTranslationUnit().
The documentation for this class was generated from the following file:
AppleObjCDeclVendor.cpp