LLDB: lldb_private::platform_android::PlatformAndroid Class Reference
lldb_private::platform_android::PlatformAndroid Class Reference
#include <PlatformAndroid.h>
Public Member Functions
PlatformAndroid (bool is_host)
llvm::StringRef GetPluginName () override
Status ConnectRemote (Args &args) override
Status GetFile (const FileSpec &source, const FileSpec &destination) override
Status PutFile (const FileSpec &source, const FileSpec &destination, uint32_t uid=UINT32_MAX, uint32_t gid=UINT32_MAX) override
uint32_t GetSdkVersion ()
bool GetRemoteOSVersion () override
Status DisconnectRemote () override
uint32_t GetDefaultMemoryCacheLineSize () override
Allow the platform to set preferred memory cache line size.
uint32_t FindProcesses (const ProcessInstanceInfoMatch &match_info, ProcessInstanceInfoList &process_infos) override
Attach to an existing process by process name.
virtual llvm::StringRef GetPropertyPackageName ()
Public Member Functions inherited from lldb_private::platform_linux::PlatformLinux
PlatformLinux (bool is_host)
Default Constructor.
llvm::StringRef GetPluginName () override
llvm::StringRef GetDescription () override
void GetStatus (Stream &strm) override
Report the current status for this platform.
std::vector< ArchSpec > GetSupportedArchitectures (const ArchSpec &process_host_arch) override
Get the platform's supported architectures in the order in which they should be searched.
uint32_t GetResumeCountForLaunchInfo (ProcessLaunchInfo &launch_info) override
bool CanDebugProcess () override
Not all platforms will support debugging a process by spawning somehow halted for a debugger (specified using the "eLaunchFlagDebug" launch flag) and then attaching.
void CalculateTrapHandlerSymbolNames () override
Ask the Platform subclass to fill in the list of trap handler names.
lldb::UnwindPlanSP GetTrapHandlerUnwindPlan (const ArchSpec &arch, ConstString name) override
Try to get a specific unwind plan for a named trap handler.
MmapArgList GetMmapArgumentList (const ArchSpec &arch, lldb::addr_t addr, lldb::addr_t length, unsigned prot, unsigned flags, lldb::addr_t fd, lldb::addr_t offset) override
CompilerType GetSiginfoType (const llvm::Triple &triple) override
lldb::StopInfoSP GetStopInfoFromSiginfo (Thread &thread) override
Public Member Functions inherited from PlatformPOSIX
PlatformPOSIX (bool is_host)
Default Constructor.
~PlatformPOSIX () override
Destructor.
lldb_private::OptionGroupOptions * GetConnectionOptions (lldb_private::CommandInterpreter &interpreter) override
lldb_private::Status PutFile (const lldb_private::FileSpec &source, const lldb_private::FileSpec &destination, uint32_t uid=UINT32_MAX, uint32_t gid=UINT32_MAX) override
lldb_private::Status GetFile (const lldb_private::FileSpec &source, const lldb_private::FileSpec &destination) override
const lldb::UnixSignalsSP & GetRemoteUnixSignals () override
lldb::ProcessSP Attach (lldb_private::ProcessAttachInfo &attach_info, lldb_private::Debugger &debugger, lldb_private::Target *target, lldb_private::Status &error) override
Attach to an existing process using a process ID.
lldb::ProcessSP DebugProcess (lldb_private::ProcessLaunchInfo &launch_info, lldb_private::Debugger &debugger, lldb_private::Target &target, lldb_private::Status &error) override
Subclasses do not need to implement this function as it uses the Platform::LaunchProcess() followed by Platform::Attach ().
std::string GetPlatformSpecificConnectionInformation () override
void CalculateTrapHandlerSymbolNames () override
Ask the Platform subclass to fill in the list of trap handler names.
lldb_private::Status ConnectRemote (lldb_private::Args &args) override
lldb_private::Status DisconnectRemote () override
uint32_t DoLoadImage (lldb_private::Process *process, const lldb_private::FileSpec &remote_file, const std::vector< std::string > *paths, lldb_private::Status &error, lldb_private::FileSpec *loaded_image) override
lldb_private::Status UnloadImage (lldb_private::Process *process, uint32_t image_token) override
lldb_private::ConstString GetFullNameForDylib (lldb_private::ConstString basename) override
Public Member Functions inherited from lldb_private::RemoteAwarePlatform
virtual Status ResolveExecutable (const ModuleSpec &module_spec, lldb::ModuleSP &exe_module_sp) override
Set the target's executable based off of the existing architecture information in target given a path to an executable exe_file.
bool GetModuleSpec (const FileSpec &module_file_spec, const ArchSpec &arch, ModuleSpec &module_spec) override
lldb::user_id_t OpenFile (const FileSpec &file_spec, File::OpenOptions flags, uint32_t mode, Status &error) override
bool CloseFile (lldb::user_id_t fd, Status &error) override
uint64_t ReadFile (lldb::user_id_t fd, uint64_t offset, void *dst, uint64_t dst_len, Status &error) override
uint64_t WriteFile (lldb::user_id_t fd, uint64_t offset, const void *src, uint64_t src_len, Status &error) override
lldb::user_id_t GetFileSize (const FileSpec &file_spec) override
Status CreateSymlink (const FileSpec &src, const FileSpec &dst) override
bool GetFileExists (const FileSpec &file_spec) override
Status Unlink (const FileSpec &file_spec) override
FileSpec GetRemoteWorkingDirectory () override
bool SetRemoteWorkingDirectory (const FileSpec &working_dir) override
Status MakeDirectory (const FileSpec &file_spec, uint32_t mode) override
Status GetFilePermissions (const FileSpec &file_spec, uint32_t &file_permissions) override
Status SetFilePermissions (const FileSpec &file_spec, uint32_t file_permissions) override
llvm::ErrorOr< llvm::MD5::MD5Result > CalculateMD5 (const FileSpec &file_spec) override
Status GetFileWithUUID (const FileSpec &platform_file, const UUID *uuid, FileSpec &local_file) override
Locate a file for a platform.
bool GetRemoteOSVersion () override
std::optional< std::string > GetRemoteOSBuildString () override
std::optional< std::string > GetRemoteOSKernelDescription () override
ArchSpec GetRemoteSystemArchitecture () override
Status RunShellCommand (llvm::StringRef command, const FileSpec &working_dir, int *status_ptr, int *signo_ptr, std::string *command_output, const Timeout< std::micro > &timeout) override
Status RunShellCommand (llvm::StringRef interpreter, llvm::StringRef command, const FileSpec &working_dir, int *status_ptr, int *signo_ptr, std::string *command_output, const Timeout< std::micro > &timeout) override
const char * GetHostname () override
UserIDResolver & GetUserIDResolver () override
lldb_private::Environment GetEnvironment () override
bool IsConnected () const override
bool GetProcessInfo (lldb::pid_t pid, ProcessInstanceInfo &proc_info) override
uint32_t FindProcesses (const ProcessInstanceInfoMatch &match_info, ProcessInstanceInfoList &process_infos) override
Attach to an existing process by process name.
lldb::ProcessSP ConnectProcess (llvm::StringRef connect_url, llvm::StringRef plugin_name, Debugger &debugger, Target *target, Status &error) override
Status LaunchProcess (ProcessLaunchInfo &launch_info) override
Launch a new process on a platform, not necessarily for debugging, it could be just for running the process.
Status KillProcess (const lldb::pid_t pid) override
Kill process on a platform.
size_t ConnectToWaitingProcesses (Debugger &debugger, Status &error) override
Connect to all processes waiting for a debugger to attach.
Platform (bool is_host_platform)
Default Constructor.
Public Member Functions inherited from lldb_private::Platform
Platform (bool is_host_platform)
Default Constructor.
~Platform () override
The destructor is virtual since this class is designed to be inherited from by the plug-in instance.
virtual Status ResolveSymbolFile (Target &target, const ModuleSpec &sym_spec, FileSpec &sym_file)
Find a symbol file given a symbol file module specification.
virtual bool ResolveRemotePath (const FileSpec &platform_path, FileSpec &resolved_platform_path)
Resolves the FileSpec to a (possibly) remote path.
virtual llvm::VersionTuple GetOSVersion (Process *process=nullptr)
Get the OS version from a connected platform.
bool SetOSVersion (llvm::VersionTuple os_version)
std::optional< std::string > GetOSBuildString ()
std::optional< std::string > GetOSKernelDescription ()
llvm::StringRef GetName ()
virtual FileSpecList LocateExecutableScriptingResources (Target *target, Module &module, Stream &feedback_stream)
virtual Status GetSharedModule (const ModuleSpec &module_spec, Process *process, lldb::ModuleSP &module_sp, llvm::SmallVectorImpl< lldb::ModuleSP > *old_modules, bool *did_create_ptr)
void CallLocateModuleCallbackIfSet (const ModuleSpec &module_spec, lldb::ModuleSP &module_sp, FileSpec &symbol_file_spec, bool *did_create_ptr)
virtual size_t GetSoftwareBreakpointTrapOpcode (Target &target, BreakpointSite *bp_site)
virtual Status ShellExpandArguments (ProcessLaunchInfo &launch_info)
Perform expansion of the command-line for this launch info This can potentially involve wildcard expansion environment variable replacement, and whatever other argument magic the platform defines as part of its typical user experience.
virtual bool IsCompatibleArchitecture (const ArchSpec &arch, const ArchSpec &process_host_arch, ArchSpec::MatchType match, ArchSpec *compatible_arch_ptr)
Lets a platform answer if it is compatible with a given architecture and the target triple contained within.
virtual lldb::ProcessSP ConnectProcessSynchronous (llvm::StringRef connect_url, llvm::StringRef plugin_name, Debugger &debugger, Stream &stream, Target *target, Status &error)
ProcessInstanceInfoList GetAllProcesses ()
virtual lldb::BreakpointSP SetThreadCreationBreakpoint (Target &target)
virtual lldb_private::ConstString GetSDKDirectory (lldb_private::Target &target)
virtual llvm::Expected< std::pair< XcodeSDK, bool > > GetSDKPathFromDebugInfo (Module &module)
Search each CU associated with the specified 'module' for the SDK paths the CUs were compiled against.
virtual llvm::Expected< std::string > ResolveSDKPathFromDebugInfo (Module &module)
Returns the full path of the most appropriate SDK for the specified 'module'.
virtual llvm::Expected< XcodeSDK > GetSDKPathFromDebugInfo (CompileUnit &unit)
Search CU for the SDK path the CUs was compiled against.
virtual llvm::Expected< std::string > ResolveSDKPathFromDebugInfo (CompileUnit &unit)
Returns the full path of the most appropriate SDK for the specified compile unit.
bool IsHost () const
bool IsRemote () const
const ArchSpec & GetSystemArchitecture ()
void SetSystemArchitecture (const ArchSpec &arch)
ArchSpec GetAugmentedArchSpec (llvm::StringRef triple)
If the triple contains not specify the vendor, os, and environment parts, we "augment" these using information from the platform and return the resulting ArchSpec object.
size_t GetMaxUserIDNameLength () const
size_t GetMaxGroupIDNameLength () const
const std::string & GetSDKRootDirectory () const
void SetSDKRootDirectory (std::string dir)
const std::string & GetSDKBuild () const
void SetSDKBuild (std::string sdk_build)
virtual bool SupportsModules ()
virtual void AddClangModuleCompilationOptions (Target *target, std::vector< std::string > &options)
FileSpec GetWorkingDirectory ()
bool SetWorkingDirectory (const FileSpec &working_dir)
virtual bool ModuleIsExcludedForUnconstrainedSearches (Target &target, const lldb::ModuleSP &module_sp)
virtual void AutoCompleteDiskFileOrDirectory (CompletionRequest &request, bool only_dir)
virtual Status Install (const FileSpec &src, const FileSpec &dst)
Install a file or directory to the remote system.
virtual bool GetSupportsRSync ()
virtual void SetSupportsRSync (bool flag)
virtual const char * GetRSyncOpts ()
virtual void SetRSyncOpts (const char *opts)
virtual const char * GetRSyncPrefix ()
virtual void SetRSyncPrefix (const char *prefix)
virtual bool GetSupportsSSH ()
virtual void SetSupportsSSH (bool flag)
virtual const char * GetSSHOpts ()
virtual void SetSSHOpts (const char *opts)
virtual bool GetIgnoresRemoteHostname ()
virtual void SetIgnoresRemoteHostname (bool flag)
virtual void SetLocalCacheDirectory (const char *local)
virtual const char * GetLocalCacheDirectory ()
lldb::UnixSignalsSP GetUnixSignals ()
virtual std::string GetQueueNameForThreadQAddress (Process *process, lldb::addr_t dispatch_qaddr)
Locate a queue name given a thread's qaddr.
virtual lldb::queue_id_t GetQueueIDForThreadQAddress (Process *process, lldb::addr_t dispatch_qaddr)
Locate a queue ID given a thread's qaddr.
virtual const std::vector< ConstString > & GetTrapHandlerSymbolNames ()
Provide a list of trap handler function names for this platform.
virtual FileSpec LocateExecutable (const char *basename)
Find a support executable that may not live within in the standard locations related to LLDB.
uint32_t LoadImage (lldb_private::Process *process, const lldb_private::FileSpec &local_file, const lldb_private::FileSpec &remote_file, lldb_private::Status &error)
Load a shared library into this process.
uint32_t LoadImageUsingPaths (lldb_private::Process *process, const lldb_private::FileSpec &library_name, const std::vector< std::string > &paths, lldb_private::Status &error, lldb_private::FileSpec *loaded_path)
Load a shared library specified by base name into this process, looking by hand along a set of paths.
virtual llvm::Expected< StructuredData::DictionarySP > FetchExtendedCrashInformation (lldb_private::Process &process)
Gather all of crash informations into a structured data dictionary.
virtual bool LoadPlatformBinaryAndSetup (Process *process, lldb::addr_t addr, bool notify)
Detect a binary in memory that will determine which Platform and DynamicLoader should be used in this target/process, and update the Platform/DynamicLoader.
virtual Args GetExtraStartupCommands ()
void SetLocateModuleCallback (LocateModuleCallback callback)
Set locate module callback.
LocateModuleCallback GetLocateModuleCallback () const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static lldb::PlatformSP CreateInstance (bool force, const ArchSpec *arch)
static void DebuggerInitialize (lldb_private::Debugger &debugger)
static llvm::StringRef GetPluginNameStatic (bool is_host)
static llvm::StringRef GetPluginDescriptionStatic (bool is_host)
Static Public Member Functions inherited from lldb_private::platform_linux::PlatformLinux
static void Initialize ()
static void Terminate ()
static lldb::PlatformSP CreateInstance (bool force, const ArchSpec *arch)
static llvm::StringRef GetPluginNameStatic (bool is_host)
static llvm::StringRef GetPluginDescriptionStatic (bool is_host)
Static Public Member Functions inherited from lldb_private::Platform
static void Initialize ()
static void Terminate ()
static PlatformProperties & GetGlobalPlatformProperties ()
static lldb::PlatformSP GetHostPlatform ()
Get the native host platform plug-in.
static const char * GetHostPlatformName ()
static void SetHostPlatform (const lldb::PlatformSP &platform_sp)
static lldb::PlatformSP Create (llvm::StringRef name)
static ArchSpec GetAugmentedArchSpec (Platform *platform, llvm::StringRef triple)
Augments the triple either with information from platform or the host system (if platform is null).
Protected Types
typedef std::unique_ptr< AdbClient > AdbClientUP
Protected Types inherited from lldb_private::Platform
typedef std::map< uint32_t, ConstString > IDToNameMap
Protected Member Functions
const char * GetCacheHostname () override
Status DownloadModuleSlice (const FileSpec &src_file_spec, const uint64_t src_offset, const uint64_t src_size, const FileSpec &dst_file_spec) override
Status DownloadSymbolFile (const lldb::ModuleSP &module_sp, const FileSpec &dst_file_spec) override
llvm::StringRef GetLibdlFunctionDeclarations (lldb_private::Process *process) override
virtual AdbClientUP GetAdbClient (Status &error)
std::string GetRunAs ()
virtual std::unique_ptr< AdbSyncService > GetSyncService (Status &error)
Protected Member Functions inherited from PlatformPOSIX
lldb_private::Status EvaluateLibdlExpression (lldb_private::Process *process, const char *expr_cstr, llvm::StringRef expr_prefix, lldb::ValueObjectSP &result_valobj_sp)
std::unique_ptr< lldb_private::UtilityFunction > MakeLoadImageUtilityFunction (lldb_private::ExecutionContext &exe_ctx, lldb_private::Status &error)
Protected Member Functions inherited from lldb_private::Platform
lldb::ProcessSP DoConnectProcess (llvm::StringRef connect_url, llvm::StringRef plugin_name, Debugger &debugger, Stream *stream, Target *target, Status &error)
Private implementation of connecting to a process.
Status GetCachedExecutable (ModuleSpec &module_spec, lldb::ModuleSP &module_sp)
Protected Attributes
std::string m_device_id
uint32_t m_sdk_version
Protected Attributes inherited from PlatformPOSIX
std::unique_ptr< lldb_private::OptionGroupPlatformRSync > m_option_group_platform_rsync
std::unique_ptr< lldb_private::OptionGroupPlatformSSH > m_option_group_platform_ssh
std::unique_ptr< lldb_private::OptionGroupPlatformCaching > m_option_group_platform_caching
std::map< lldb_private::CommandInterpreter *, std::unique_ptr< lldb_private::OptionGroupOptions > > m_options
Protected Attributes inherited from lldb_private::RemoteAwarePlatform
lldb::PlatformSP m_remote_platform_sp
Protected Attributes inherited from lldb_private::Platform
bool m_is_host
bool m_os_version_set_while_connected
bool m_system_arch_set_while_connected
std::string m_sdk_sysroot
std::string m_sdk_build
FileSpec m_working_dir
std::string m_hostname
llvm::VersionTuple m_os_version
ArchSpec m_system_arch
std::mutex m_mutex
size_t m_max_uid_name_len
size_t m_max_gid_name_len
bool m_supports_rsync
std::string m_rsync_opts
std::string m_rsync_prefix
bool m_supports_ssh
std::string m_ssh_opts
bool m_ignores_remote_hostname
std::string m_local_cache_directory
std::vector< ConstString > m_trap_handlers
bool m_calculated_trap_handlers
const std::unique_ptr< ModuleCache > m_module_cache
LocateModuleCallback m_locate_module_callback
Additional Inherited Members
Public Types inherited from lldb_private::Platform
typedef std::function< Status(const ModuleSpec &module_spec, FileSpec &module_file_spec, FileSpec &symbol_file_spec)> LocateModuleCallback
Public Attributes inherited from lldb_private::platform_linux::PlatformLinux
std::vector< ArchSpec > m_supported_architectures
Static Protected Member Functions inherited from lldb_private::Platform
static std::vector< ArchSpec > CreateArchList (llvm::ArrayRef< llvm::Triple::ArchType > archs, llvm::Triple::OSType os)
Create a list of ArchSpecs with the given OS and a architectures.
Detailed Description
Definition at line 22 of file PlatformAndroid.h.
Member Typedef Documentation
AdbClientUP
typedef std::unique_ptr<AdbClient> lldb_private::platform_android::PlatformAndroid::AdbClientUP protected
Definition at line 78 of file PlatformAndroid.h.
Constructor & Destructor Documentation
PlatformAndroid()
PlatformAndroid::PlatformAndroid (bool is_host)
Definition at line 168 of file PlatformAndroid.cpp.
References m_sdk_version, and lldb_private::platform_linux::PlatformLinux::PlatformLinux().
Referenced by CreateInstance(), and Initialize().
Member Function Documentation
ConnectRemote()
Status PlatformAndroid::ConnectRemote (Args & args) override virtual
Reimplemented from lldb_private::Platform.
Definition at line 177 of file PlatformAndroid.cpp.
References error(), lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::Args::GetArgumentAtIndex(), lldb_private::Platform::IsHost(), m_device_id, lldb_private::RemoteAwarePlatform::m_remote_platform_sp, lldb_private::URI::Parse(), and lldb_private::platform_android::AdbClient::ResolveDeviceID().
CreateInstance()
PlatformSP PlatformAndroid::CreateInstance (bool force, const ArchSpec * arch) static
Definition at line 89 of file PlatformAndroid.cpp.
References lldb_private::ArchSpec::GetArchitectureName(), lldb_private::GetLog(), lldb_private::ArchSpec::GetTriple(), lldb_private::ArchSpec::IsValid(), LLDB_LOGF, lldb_private::Platform, PlatformAndroid(), lldb_private::ArchSpec::TripleEnvironmentWasSpecified(), and lldb_private::ArchSpec::TripleVendorWasSpecified().
Referenced by Initialize(), and Terminate().
DebuggerInitialize()
void PlatformAndroid::DebuggerInitialize (lldb_private::Debugger & debugger) static
Definition at line 158 of file PlatformAndroid.cpp.
References lldb_private::PluginManager::CreateSettingForPlatformPlugin(), GetGlobalProperties(), GetPluginNameStatic(), and lldb_private::PluginManager::GetSettingForPlatformPlugin().
Referenced by Initialize().
DisconnectRemote()
Status PlatformAndroid::DisconnectRemote () override virtual
Reimplemented from lldb_private::Platform.
Definition at line 320 of file PlatformAndroid.cpp.
References error(), m_device_id, and m_sdk_version.
DownloadModuleSlice()
Status PlatformAndroid::DownloadModuleSlice (const FileSpec & src_file_spec, const uint64_t src_offset, const uint64_t src_size, const FileSpec & dst_file_spec) override protected virtual
Reimplemented from lldb_private::Platform.
Definition at line 277 of file PlatformAndroid.cpp.
References error(), lldb_private::Status::FromErrorString(), GetAdbClient(), GetFile(), lldb_private::FileSpec::GetPath(), GetRunAs(), and PATH_MAX.
DownloadSymbolFile()
Status PlatformAndroid::DownloadSymbolFile (const lldb::ModuleSP & module_sp, const FileSpec & dst_file_spec) override protected virtual
Reimplemented from lldb_private::Platform.
Definition at line 361 of file PlatformAndroid.cpp.
References error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), GetAdbClient(), lldb_private::StreamString::GetData(), GetFile(), lldb_private::GetLog(), GetSdkVersion(), LLDB_LOGF, lldb_private::Platform, and lldb_private::Stream::Printf().
FindProcesses()
uint32_t PlatformAndroid::FindProcesses (const ProcessInstanceInfoMatch & match_info, ProcessInstanceInfoList & proc_infos) override virtual
Attach to an existing process by process name.
This function is not meant to be overridden by Process subclasses. It will first call Process::WillAttach (const char *) and if that returns true, Process::DoAttach (const char *) will be called to actually do the attach. If DoAttach returns true, then Process::DidAttach() will be called.
Parameters
[in] process_name A process name to match against the current process list.
Returns
Returns pid if attaching was successful, or LLDB_INVALID_PROCESS_ID if attaching fails.
Reimplemented from lldb_private::Platform.
Definition at line 566 of file PlatformAndroid.cpp.
GetAdbClient()
PlatformAndroid::AdbClientUP PlatformAndroid::GetAdbClient (Status & error) protected virtual
Definition at line 452 of file PlatformAndroid.cpp.
Referenced by DownloadModuleSlice(), DownloadSymbolFile(), GetFile(), and GetSdkVersion().
GetCacheHostname()
const char * PlatformAndroid::GetCacheHostname () override protected virtual
Reimplemented from lldb_private::Platform.
Definition at line 275 of file PlatformAndroid.cpp.
References m_device_id.
GetDefaultMemoryCacheLineSize()
uint32_t PlatformAndroid::GetDefaultMemoryCacheLineSize () override virtual
Allow the platform to set preferred memory cache line size.
If non-zero (and the user has not set cache line size explicitly), this value will be used as the cache line size for memory reads.
Reimplemented from lldb_private::Platform.
Definition at line 329 of file PlatformAndroid.cpp.
GetFile()
Status PlatformAndroid::GetFile (const FileSpec & source, const FileSpec & destination) override virtual
Reimplemented from lldb_private::Platform.
Definition at line 206 of file PlatformAndroid.cpp.
References lldb_private::FileSpec::CopyByAppendingPathComponent(), error(), lldb_private::Status::FromErrorString(), GetAdbClient(), lldb_private::GetLog(), lldb_private::FileSpec::GetPath(), lldb_private::FileSpec::GetPathAsConstString(), lldb_private::RemoteAwarePlatform::GetRemoteWorkingDirectory(), GetRunAs(), lldb_private::ConstString::GetStringRef(), GetSyncService(), lldb_private::Platform::IsHost(), lldb_private::FileSpec::IsRelative(), LLDB_LOGF, lldb_private::RemoteAwarePlatform::m_remote_platform_sp, PATH_MAX, and lldb_private::Platform.
Referenced by DownloadModuleSlice(), and DownloadSymbolFile().
GetLibdlFunctionDeclarations()
llvm::StringRef PlatformAndroid::GetLibdlFunctionDeclarations (lldb_private::Process * process) override protected virtual
Reimplemented from PlatformPOSIX.
Definition at line 432 of file PlatformAndroid.cpp.
References lldb_private::ModuleList::FindFunctionSymbols(), lldb_private::Target::GetImages(), lldb_private::SymbolContextList::GetSize(), and lldb_private::Process::GetTarget().
GetPluginDescriptionStatic()
llvm::StringRef PlatformAndroid::GetPluginDescriptionStatic (bool is_host) static
Definition at line 171 of file PlatformAndroid.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef lldb_private::platform_android::PlatformAndroid::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 41 of file PlatformAndroid.h.
References GetPluginNameStatic(), and lldb_private::Platform::IsHost().
GetPluginNameStatic()
llvm::StringRef lldb_private::platform_android::PlatformAndroid::GetPluginNameStatic (bool is_host) inline static
Definition at line 35 of file PlatformAndroid.h.
References lldb_private::Platform::GetHostPlatformName().
Referenced by DebuggerInitialize(), GetPluginName(), and Initialize().
GetPropertyPackageName()
llvm::StringRef PlatformAndroid::GetPropertyPackageName () virtual
Definition at line 458 of file PlatformAndroid.cpp.
References error(), and m_device_id.
GetRemoteOSVersion()
bool PlatformAndroid::GetRemoteOSVersion () override virtual
Reimplemented from lldb_private::Platform.
Definition at line 426 of file PlatformAndroid.cpp.
References GetSdkVersion(), and lldb_private::Platform::m_os_version.
GetRunAs()
std::string PlatformAndroid::GetRunAs () protected
Definition at line 463 of file PlatformAndroid.cpp.
References GetGlobalProperties(), and lldb_private::Properties::GetPropertyAtIndexAs().
Referenced by DownloadModuleSlice(), and GetFile().
GetSdkVersion()
uint32_t PlatformAndroid::GetSdkVersion ()
Definition at line 333 of file PlatformAndroid.cpp.
References error(), GetAdbClient(), lldb_private::GetLog(), lldb_private::RemoteAwarePlatform::IsConnected(), LLDB_LOGF, m_sdk_version, and lldb_private::Platform.
Referenced by DownloadSymbolFile(), and GetRemoteOSVersion().
GetSyncService()
std::unique_ptr< AdbSyncService > PlatformAndroid::GetSyncService (Status & error) protected virtual
Definition at line 605 of file PlatformAndroid.cpp.
Referenced by GetFile(), and PutFile().
Initialize()
void PlatformAndroid::Initialize () static
Definition at line 63 of file PlatformAndroid.cpp.
References CreateInstance(), DebuggerInitialize(), g_initialize_count, GetPluginDescriptionStatic(), GetPluginNameStatic(), PlatformAndroid(), lldb_private::PluginManager::RegisterPlugin(), and lldb_private::Platform::SetHostPlatform().
PutFile()
Status PlatformAndroid::PutFile (const FileSpec & source, const FileSpec & destination, uint32_t uid = UINT32_MAX, uint32_t gid = UINT32_MAX) override virtual
Reimplemented from lldb_private::Platform.
Definition at line 256 of file PlatformAndroid.cpp.
References lldb_private::FileSpec::CopyByAppendingPathComponent(), error(), lldb_private::FileSpec::GetPath(), lldb_private::RemoteAwarePlatform::GetRemoteWorkingDirectory(), GetSyncService(), lldb_private::Platform::IsHost(), lldb_private::FileSpec::IsRelative(), and lldb_private::RemoteAwarePlatform::m_remote_platform_sp.
Terminate()
void PlatformAndroid::Terminate () static
Definition at line 79 of file PlatformAndroid.cpp.
References CreateInstance(), g_initialize_count, and lldb_private::PluginManager::UnregisterPlugin().
Member Data Documentation
m_device_id
std::string lldb_private::platform_android::PlatformAndroid::m_device_id protected
Definition at line 89 of file PlatformAndroid.h.
Referenced by ConnectRemote(), DisconnectRemote(), GetCacheHostname(), and GetPropertyPackageName().
m_sdk_version
uint32_t lldb_private::platform_android::PlatformAndroid::m_sdk_version protected
Definition at line 90 of file PlatformAndroid.h.
Referenced by DisconnectRemote(), GetSdkVersion(), and PlatformAndroid().
The documentation for this class was generated from the following files:
PlatformAndroid.h
PlatformAndroid.cpp