LLDB: lldb::SBModule Class Reference
lldb::SBModule Class Reference
#include <SBModule.h>
Public Member Functions
SBModule ()
SBModule (const SBModule &rhs)
SBModule (const SBModuleSpec &module_spec)
const SBModule & operator= (const SBModule &rhs)
SBModule (lldb::SBProcess &process, lldb::addr_t header_addr)
~SBModule ()
operator bool () const
bool IsValid () const
void Clear ()
bool IsFileBacked () const
lldb::SBFileSpec GetFileSpec () const
Get const accessor for the module file specification.
lldb::SBFileSpec GetPlatformFileSpec () const
Get accessor for the module platform file specification.
bool SetPlatformFileSpec (const lldb::SBFileSpec &platform_file)
lldb::SBFileSpec GetRemoteInstallFileSpec ()
Get accessor for the remote install path for a module.
bool SetRemoteInstallFileSpec (lldb::SBFileSpec &file)
Set accessor for the remote install path for a module.
lldb::ByteOrder GetByteOrder ()
uint32_t GetAddressByteSize ()
const char * GetTriple ()
const uint8_t * GetUUIDBytes () const
const char * GetUUIDString () const
bool operator== (const lldb::SBModule &rhs) const
bool operator!= (const lldb::SBModule &rhs) const
lldb::SBSection FindSection (const char *sect_name)
lldb::SBAddress ResolveFileAddress (lldb::addr_t vm_addr)
lldb::SBSymbolContext ResolveSymbolContextForAddress (const lldb::SBAddress &addr, uint32_t resolve_scope)
bool GetDescription (lldb::SBStream &description)
uint32_t GetNumCompileUnits ()
lldb::SBCompileUnit GetCompileUnitAtIndex (uint32_t)
lldb::SBSymbolContextList FindCompileUnits (const lldb::SBFileSpec &sb_file_spec)
Find compile units related to *this module and passed source file.
size_t GetNumSymbols ()
lldb::SBSymbol GetSymbolAtIndex (size_t idx)
lldb::SBSymbol FindSymbol (const char *name, lldb::SymbolType type=eSymbolTypeAny)
lldb::SBSymbolContextList FindSymbols (const char *name, lldb::SymbolType type=eSymbolTypeAny)
size_t GetNumSections ()
lldb::SBSection GetSectionAtIndex (size_t idx)
lldb::SBSymbolContextList FindFunctions (const char *name, uint32_t name_type_mask=lldb::eFunctionNameTypeAny)
Find functions by name.
lldb::SBValueList FindGlobalVariables (lldb::SBTarget &target, const char *name, uint32_t max_matches)
Find global and static variables by name.
lldb::SBValue FindFirstGlobalVariable (lldb::SBTarget &target, const char *name)
Find the first global (or static) variable by name.
lldb::SBType FindFirstType (const char *name)
lldb::SBTypeList FindTypes (const char *type)
lldb::SBType GetTypeByID (lldb::user_id_t uid)
Get a type using its type ID.
lldb::SBType GetBasicType (lldb::BasicType type)
lldb::SBTypeList GetTypes (uint32_t type_mask=lldb::eTypeClassAny)
Get all types matching type_mask from debug info in this module.
uint32_t GetVersion (uint32_t *versions, uint32_t num_versions)
Get the module version numbers.
lldb::SBFileSpec GetSymbolFileSpec () const
Get accessor for the symbol file specification.
lldb::SBAddress GetObjectFileHeaderAddress () const
lldb::SBAddress GetObjectFileEntryPointAddress () const
const char * GetObjectName () const
If this Module represents a specific object or part within a larger file, returns the name of that object or part.
Static Public Member Functions
static uint32_t GetNumberAllocatedModules ()
Get the number of global modules.
static void GarbageCollectAllocatedModules ()
Remove any global modules which are no longer needed.
Private Member Functions
SBModule (const lldb::ModuleSP &module_sp)
ModuleSP GetSP () const
void SetSP (const ModuleSP &module_sp)
Private Attributes
lldb::ModuleSP m_opaque_sp
Friends
class SBAddress
class SBFrame
class SBSection
class SBSymbolContext
class SBPlatform
class SBTarget
class SBType
class lldb_private::python::SWIGBridge
Detailed Description
Definition at line 20 of file SBModule.h.
Constructor & Destructor Documentation
SBModule() [1/5]
SBModule::SBModule ()
Definition at line 32 of file SBModule.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb_private::python::SWIGBridge, operator!=(), operator=(), operator==(), and SBModule().
SBModule() [2/5]
SBModule::SBModule (const SBModule & rhs)
Definition at line 46 of file SBModule.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBModule().
SBModule() [3/5]
SBModule::SBModule (const SBModuleSpec & module_spec)
Definition at line 36 of file SBModule.cpp.
References error(), lldb_private::ModuleList::GetSharedModule(), LLDB_INSTRUMENT_VA, lldb::SBModuleSpec::m_opaque_up, and SetSP().
SBModule() [4/5]
SBModule::SBModule (lldb::SBProcess & process, lldb::addr_t header_addr)
Definition at line 50 of file SBModule.cpp.
References lldb_private::ModuleList::Append(), lldb_private::Target::GetImages(), lldb::SBProcess::GetSP(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
~SBModule()
SBModule::~SBModule () default
References Clear(), lldb::eSymbolTypeAny, FindCompileUnits(), FindFirstGlobalVariable(), FindFirstType(), FindFunctions(), FindGlobalVariables(), FindSection(), FindSymbol(), FindSymbols(), FindTypes(), GarbageCollectAllocatedModules(), GetAddressByteSize(), GetBasicType(), GetByteOrder(), GetCompileUnitAtIndex(), GetDescription(), GetFileSpec(), GetNumberAllocatedModules(), GetNumCompileUnits(), GetNumSections(), GetNumSymbols(), GetObjectFileEntryPointAddress(), GetObjectFileHeaderAddress(), GetObjectName(), GetPlatformFileSpec(), GetRemoteInstallFileSpec(), GetSectionAtIndex(), GetSymbolAtIndex(), GetSymbolFileSpec(), GetTriple(), GetTypeByID(), GetTypes(), GetUUIDBytes(), GetUUIDString(), GetVersion(), IsFileBacked(), IsValid(), operator!=(), operator==(), ResolveFileAddress(), ResolveSymbolContextForAddress(), SetPlatformFileSpec(), and SetRemoteInstallFileSpec().
SBModule() [5/5]
SBModule::SBModule (const lldb::ModuleSP & module_sp) explicit private
Definition at line 34 of file SBModule.cpp.
References m_opaque_sp.
Member Function Documentation
Clear()
void SBModule::Clear ()
Definition at line 92 of file SBModule.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBModule().
FindCompileUnits()
SBSymbolContextList SBModule::FindCompileUnits (const lldb::SBFileSpec & sb_file_spec)
Find compile units related to *this module and passed source file.
Parameters
[in] sb_file_spec A lldb::SBFileSpec object that contains source file specification.
Returns
A lldb::SBSymbolContextList that gets filled in with all of the symbol contexts for all the matches.
Definition at line 282 of file SBModule.cpp.
References GetSP(), lldb::SBFileSpec::IsValid(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBModule().
FindFirstGlobalVariable()
lldb::SBValue SBModule::FindFirstGlobalVariable (lldb::SBTarget & target, const char * name)
Find the first global (or static) variable by name.
Parameters
[in] target A valid SBTarget instance representing the debuggee.
[in] name The name of the global or static variable we are looking for.
Returns
An SBValue that gets filled in with the found variable (if any).
Definition at line 433 of file SBModule.cpp.
References FindGlobalVariables(), lldb::SBValueList::GetSize(), lldb::SBValueList::GetValueAtIndex(), lldb::SBValueList::IsValid(), LLDB_INSTRUMENT_VA, and lldb::SBValue.
Referenced by ~SBModule().
FindFirstType()
lldb::SBType SBModule::FindFirstType (const char * name)
Definition at line 443 of file SBModule.cpp.
References lldb::eLanguageTypeC, lldb_private::TypeResults::GetFirstType(), GetSP(), lldb_private::ConstString::GetStringRef(), LLDB_INSTRUMENT_VA, and SBType.
Referenced by ~SBModule().
FindFunctions()
lldb::SBSymbolContextList SBModule::FindFunctions (const char * name, uint32_t name_type_mask = lldb::eFunctionNameTypeAny)
Find functions by name.
Parameters
[in] name The name of the function we are looking for.
[in] name_type_mask A logical OR of one or more FunctionNameType enum bits that indicate what kind of names should be used when doing the lookup. Bits include fully qualified names, base names, C++ methods, or ObjC selectors. See FunctionNameType for more details.
Returns
A lldb::SBSymbolContextList that gets filled in with all of the symbol contexts for all the matches.
Definition at line 393 of file SBModule.cpp.
References GetSP(), lldb_private::ModuleFunctionSearchOptions::include_inlines, lldb_private::ModuleFunctionSearchOptions::include_symbols, and LLDB_INSTRUMENT_VA.
Referenced by ~SBModule().
FindGlobalVariables()
SBValueList SBModule::FindGlobalVariables (lldb::SBTarget & target, const char * name, uint32_t max_matches)
Find global and static variables by name.
Parameters
[in] target A valid SBTarget instance representing the debuggee.
[in] name The name of the global or static variable we are looking for.
[in] max_matches Allow the number of matches to be limited to max_matches.
Returns
A list of matched variables in an SBValueList.
Definition at line 411 of file SBModule.cpp.
References lldb::SBValueList::Append(), lldb_private::ValueObjectVariable::Create(), GetSP(), lldb::SBTarget::GetSP(), LLDB_INSTRUMENT_VA, SBTarget, and lldb::SBValue.
Referenced by FindFirstGlobalVariable(), and ~SBModule().
FindSection()
SBSection SBModule::FindSection (const char * sect_name)
Definition at line 549 of file SBModule.cpp.
References lldb_private::SectionList::FindSectionByName(), GetSP(), LLDB_INSTRUMENT_VA, SBSection, and lldb::SBSection::SetSP().
Referenced by ~SBModule().
FindSymbol()
lldb::SBSymbol SBModule::FindSymbol (const char * name, lldb::SymbolType type = eSymbolTypeAny)
Definition at line 319 of file SBModule.cpp.
References lldb_private::Symtab::eDebugAny, lldb_private::Symtab::eVisibilityAny, lldb_private::Symtab::FindFirstSymbolWithNameAndType(), GetSP(), GetUnifiedSymbolTable(), LLDB_INSTRUMENT_VA, and lldb::SBSymbol::SetSymbol().
Referenced by ~SBModule().
FindSymbols()
lldb::SBSymbolContextList SBModule::FindSymbols (const char * name, lldb::SymbolType type = eSymbolTypeAny)
Definition at line 335 of file SBModule.cpp.
References lldb_private::SymbolContextList::Append(), lldb_private::Symtab::FindAllSymbolsWithNameAndType(), GetSP(), GetUnifiedSymbolTable(), LLDB_INSTRUMENT_VA, lldb_private::SymbolContext::module_sp, lldb_private::SymbolContext::symbol, and lldb_private::Symtab::SymbolAtIndex().
Referenced by ~SBModule().
FindTypes()
lldb::SBTypeList SBModule::FindTypes (const char * type)
Definition at line 486 of file SBModule.cpp.
References lldb::SBTypeList::Append(), lldb::eLanguageTypeC, lldb_private::TypeMap::Empty(), GetSP(), lldb_private::TypeResults::GetTypeMap(), LLDB_INSTRUMENT_VA, SBType, and lldb_private::TypeMap::Types().
Referenced by ~SBModule().
GarbageCollectAllocatedModules()
void SBModule::GarbageCollectAllocatedModules () static
Remove any global modules which are no longer needed.
Definition at line 675 of file SBModule.cpp.
References LLDB_INSTRUMENT, and lldb_private::ModuleList::RemoveOrphanSharedModules().
Referenced by ~SBModule().
GetAddressByteSize()
uint32_t SBModule::GetAddressByteSize ()
Definition at line 594 of file SBModule.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBModule().
GetBasicType()
lldb::SBType SBModule::GetBasicType (lldb::BasicType type)
Definition at line 469 of file SBModule.cpp.
References lldb::eLanguageTypeC, GetSP(), LLDB_INSTRUMENT_VA, and SBType.
Referenced by ~SBModule().
GetByteOrder()
lldb::ByteOrder SBModule::GetByteOrder ()
Definition at line 570 of file SBModule.cpp.
References lldb::eByteOrderInvalid, GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBModule().
GetCompileUnitAtIndex()
SBCompileUnit SBModule::GetCompileUnitAtIndex (uint32_t index)
Definition at line 270 of file SBModule.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBCompileUnit::reset().
Referenced by ~SBModule().
GetDescription()
bool SBModule::GetDescription (lldb::SBStream & description)
Definition at line 246 of file SBModule.cpp.
References lldb_private::Stream::AsRawOstream(), GetSP(), LLDB_INSTRUMENT_VA, lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
Referenced by ~SBModule().
GetFileSpec()
SBFileSpec SBModule::GetFileSpec () const
Get const accessor for the module file specification.
This function returns the file for the module on the host system that is running LLDB. This can differ from the path on the platform since we might be doing remote debugging.
Returns
A const reference to the file specification object.
Definition at line 112 of file SBModule.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBFileSpec::SetFileSpec().
Referenced by ~SBModule().
GetNumberAllocatedModules()
uint32_t SBModule::GetNumberAllocatedModules () static
Get the number of global modules.
Definition at line 669 of file SBModule.cpp.
References lldb_private::Module::GetNumberAllocatedModules(), and LLDB_INSTRUMENT.
Referenced by ~SBModule().
GetNumCompileUnits()
uint32_t SBModule::GetNumCompileUnits ()
Definition at line 260 of file SBModule.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBModule().
GetNumSections()
size_t SBModule::GetNumSections ()
Definition at line 363 of file SBModule.cpp.
References lldb_private::SectionList::GetSize(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBModule().
GetNumSymbols()
size_t SBModule::GetNumSymbols ()
Definition at line 299 of file SBModule.cpp.
References GetSP(), GetUnifiedSymbolTable(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBModule().
GetObjectFileEntryPointAddress()
lldb::SBAddress SBModule::GetObjectFileEntryPointAddress () const
Definition at line 656 of file SBModule.cpp.
References lldb_private::ObjectFile::GetEntryPointAddress(), GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBAddress::ref().
Referenced by ~SBModule().
GetObjectFileHeaderAddress()
lldb::SBAddress SBModule::GetObjectFileHeaderAddress () const
Definition at line 643 of file SBModule.cpp.
References lldb_private::ObjectFile::GetBaseAddress(), GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBAddress::ref().
Referenced by ~SBModule().
GetObjectName()
const char * SBModule::GetObjectName () const
If this Module represents a specific object or part within a larger file, returns the name of that object or part.
Otherwise, returns nullptr.
Definition at line 682 of file SBModule.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBModule().
GetPlatformFileSpec()
lldb::SBFileSpec SBModule::GetPlatformFileSpec () const
Get accessor for the module platform file specification.
Platform file refers to the path of the module as it is known on the remote system on which it is being debugged. For local debugging this is always the same as Module::GetFileSpec(). But remote debugging might mention a file '/usr/lib/liba.dylib' which might be locally downloaded and cached. In this case the platform file could be something like: '/tmp/lldb/platform-cache/remote.host.computer/usr/lib/liba.dylib' The file could also be cached in a local developer kit directory.
Returns
A const reference to the file specification object.
Definition at line 123 of file SBModule.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBFileSpec::SetFileSpec().
Referenced by ~SBModule().
GetRemoteInstallFileSpec()
lldb::SBFileSpec SBModule::GetRemoteInstallFileSpec ()
Get accessor for the remote install path for a module.
When debugging to a remote platform by connecting to a remote platform, the install path of the module can be set. If the install path is set, every time the process is about to launch the target will install this module on the remote platform prior to launching.
Returns
A file specification object.
Definition at line 148 of file SBModule.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBFileSpec::SetFileSpec().
Referenced by ~SBModule().
GetSectionAtIndex()
SBSection SBModule::GetSectionAtIndex (size_t idx)
Definition at line 377 of file SBModule.cpp.
References lldb_private::SectionList::GetSectionAtIndex(), GetSP(), LLDB_INSTRUMENT_VA, SBSection, and lldb::SBSection::SetSP().
Referenced by ~SBModule().
GetSP()
ModuleSP SBModule::GetSP () const private
Definition at line 216 of file SBModule.cpp.
References m_opaque_sp.
Referenced by lldb::SBTarget::AddModule(), lldb::SBTarget::AddModule(), lldb::SBTarget::ClearModuleLoadAddress(), FindCompileUnits(), FindFirstType(), FindFunctions(), FindGlobalVariables(), FindSection(), FindSymbol(), FindSymbols(), FindTypes(), GetAddressByteSize(), GetBasicType(), GetByteOrder(), GetCompileUnitAtIndex(), GetDescription(), GetFileSpec(), GetNumCompileUnits(), GetNumSections(), GetNumSymbols(), GetObjectFileEntryPointAddress(), GetObjectFileHeaderAddress(), GetPlatformFileSpec(), GetRemoteInstallFileSpec(), GetSectionAtIndex(), GetSymbolAtIndex(), GetSymbolFileSpec(), GetTriple(), GetTypeByID(), GetTypes(), GetUUIDBytes(), GetUUIDString(), GetVersion(), IsFileBacked(), lldb::SBTarget::IsLoaded(), lldb_private::python::SWIGBridge, lldb::SBTarget::RemoveModule(), ResolveFileAddress(), ResolveSymbolContextForAddress(), SetPlatformFileSpec(), and SetRemoteInstallFileSpec().
GetSymbolAtIndex()
SBSymbol SBModule::GetSymbolAtIndex (size_t idx)
Definition at line 308 of file SBModule.cpp.
References GetSP(), GetUnifiedSymbolTable(), LLDB_INSTRUMENT_VA, lldb::SBSymbol::SetSymbol(), and lldb_private::Symtab::SymbolAtIndex().
Referenced by ~SBModule().
GetSymbolFileSpec()
lldb::SBFileSpec SBModule::GetSymbolFileSpec () const
Get accessor for the symbol file specification.
When debugging an object file an additional debug information can be provided in separate file. Therefore if you debugging something like '/usr/lib/liba.dylib' then debug information can be located in folder like '/usr/lib/liba.dylib.dSYM/'.
Returns
A const reference to the file specification object.
Definition at line 631 of file SBModule.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBFileSpec::SetFileSpec().
Referenced by ~SBModule().
GetTriple()
const char * SBModule::GetTriple ()
Definition at line 579 of file SBModule.cpp.
References lldb_private::ConstString::GetCString(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBModule().
GetTypeByID()
lldb::SBType SBModule::GetTypeByID (lldb::user_id_t uid)
Get a type using its type ID.
Each symbol file reader will assign different user IDs to their types, but it is sometimes useful when debugging type issues to be able to grab a type using its type ID.
For DWARF debug info, the type ID is the DIE offset.
Parameters
[in] uid The type user ID.
Returns
An SBType for the given type ID, or an empty SBType if the type was not found.
Definition at line 516 of file SBModule.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and SBType.
Referenced by ~SBModule().
GetTypes()
lldb::SBTypeList SBModule::GetTypes (uint32_t type_mask = lldb::eTypeClassAny)
Get all types matching type_mask from debug info in this module.
Parameters
[in] type_mask A bitfield that consists of one or more bits logically OR'ed together from the lldb::TypeClass enumeration. This allows you to request only structure types, or only class, struct and union types. Passing in lldb::eTypeClassAny will return all types found in the debug information for this module.
Returns
A list of types in this module that match type_mask
Definition at line 530 of file SBModule.cpp.
References GetSP(), lldb_private::SymbolFile::GetTypes(), LLDB_INSTRUMENT_VA, and lldb::SBTypeList::m_opaque_up.
Referenced by ~SBModule().
GetUUIDBytes()
const uint8_t * SBModule::GetUUIDBytes () const
Definition at line 169 of file SBModule.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBModule().
GetUUIDString()
const char * SBModule::GetUUIDString () const
Definition at line 180 of file SBModule.cpp.
References lldb_private::ConstString::GetCString(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBModule().
GetVersion()
uint32_t SBModule::GetVersion (uint32_t * versions, uint32_t num_versions)
Get the module version numbers.
Many object files have a set of version numbers that describe the version of the executable or shared library. Typically there are major, minor and build, but there may be more. This function will extract the versions from object files if they are available.
If versions is NULL, or if num_versions is 0, the return value will indicate how many version numbers are available in this object file. Then a subsequent call can be made to this function with a value of versions and num_versions that has enough storage to store some or all version numbers.
Parameters
[out] versions A pointer to an array of uint32_t types that is num_versions long. If this value is NULL, the return value will indicate how many version numbers are required for a subsequent call to this function so that all versions can be retrieved. If the value is non-NULL, then at most num_versions of the existing versions numbers will be filled into versions. If there is no version information available, versions will be filled with num_versions UINT32_MAX values and zero will be returned.
[in] num_versions The maximum number of entries to fill into versions. If this value is zero, then the return value will indicate how many version numbers there are in total so another call to this function can be make with adequate storage in versions to get all of the version numbers. If num_versions is less than the actual number of version numbers in this object file, only num_versions will be filled into versions (if versions is non-NULL).
Returns
This function always returns the number of version numbers that this object file has regardless of the number of version numbers that were copied into versions.
Definition at line 603 of file SBModule.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and UINT32_MAX.
Referenced by ~SBModule().
IsFileBacked()
bool SBModule::IsFileBacked () const
Definition at line 98 of file SBModule.cpp.
References GetSP(), lldb_private::ObjectFile::IsInMemory(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBModule().
IsValid()
bool SBModule::IsValid () const
Definition at line 82 of file SBModule.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBTarget::AddModule(), and ~SBModule().
operator bool()
SBModule::operator bool () const explicit
Definition at line 86 of file SBModule.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator!=()
bool SBModule::operator!= (const lldb::SBModule & rhs) const
Definition at line 208 of file SBModule.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBModule().
Referenced by ~SBModule().
operator=()
const SBModule & SBModule::operator= (const SBModule & rhs)
Definition at line 72 of file SBModule.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBModule().
operator==()
bool SBModule::operator== (const lldb::SBModule & rhs) const
Definition at line 200 of file SBModule.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBModule().
Referenced by ~SBModule().
ResolveFileAddress()
SBAddress SBModule::ResolveFileAddress (lldb::addr_t vm_addr)
Definition at line 220 of file SBModule.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, lldb::SBAddress::ref(), and SBAddress.
Referenced by ~SBModule().
ResolveSymbolContextForAddress()
SBSymbolContext SBModule::ResolveSymbolContextForAddress (const lldb::SBAddress & addr, uint32_t resolve_scope)
Definition at line 234 of file SBModule.cpp.
References GetSP(), lldb::SBAddress::IsValid(), LLDB_INSTRUMENT_VA, lldb::SBAddress::ref(), SBAddress, and SBSymbolContext.
Referenced by ~SBModule().
SetPlatformFileSpec()
bool SBModule::SetPlatformFileSpec (const lldb::SBFileSpec & platform_file)
Definition at line 134 of file SBModule.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBModule().
SetRemoteInstallFileSpec()
bool SBModule::SetRemoteInstallFileSpec (lldb::SBFileSpec & file)
Set accessor for the remote install path for a module.
When debugging to a remote platform by connecting to a remote platform, the install path of the module can be set. If the install path is set, every time the process is about to launch the target will install this module on the remote platform prior to launching.
If file specifies a full path to an install location, the module will be installed to this path. If the path is relative (no directory specified, or the path is partial like "usr/lib" or "./usr/lib", then the install path will be resolved using the platform's current working directory as the base path.
Parameters
[in] file A file specification object.
Definition at line 158 of file SBModule.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBFileSpec::ref().
Referenced by ~SBModule().
SetSP()
void SBModule::SetSP (const ModuleSP & module_sp) private
Definition at line 218 of file SBModule.cpp.
References m_opaque_sp.
Referenced by lldb::SBTarget::AddModule(), lldb::SBTarget::FindModule(), lldb::SBTarget::FindModule(), lldb::SBAddress::GetModule(), lldb::SBFrame::GetModule(), lldb::SBSymbolContext::GetModule(), lldb::SBType::GetModule(), lldb::SBTarget::GetModuleAtIndex(), lldb_private::python::SWIGBridge, and SBModule().
Friends And Related Symbol Documentation
lldb_private::python::SWIGBridge
friend class lldb_private::python::SWIGBridge friend
Definition at line 313 of file SBModule.h.
References GetSP(), SBModule(), and SetSP().
SBAddress
friend class SBAddress friend
Definition at line 305 of file SBModule.h.
References SBAddress.
Referenced by ResolveFileAddress(), ResolveSymbolContextForAddress(), and SBAddress.
SBFrame
friend class SBFrame friend
Definition at line 306 of file SBModule.h.
References SBFrame.
Referenced by SBFrame.
SBPlatform
friend class SBPlatform friend
Definition at line 309 of file SBModule.h.
References SBPlatform.
Referenced by SBPlatform.
SBSection
friend class SBSection friend
Definition at line 307 of file SBModule.h.
References SBSection.
Referenced by FindSection(), GetSectionAtIndex(), and SBSection.
SBSymbolContext
friend class SBSymbolContext friend
Definition at line 308 of file SBModule.h.
References SBSymbolContext.
Referenced by ResolveSymbolContextForAddress(), and SBSymbolContext.
SBTarget
friend class SBTarget friend
Definition at line 310 of file SBModule.h.
References SBTarget.
Referenced by FindGlobalVariables(), and SBTarget.
SBType
friend class SBType friend
Definition at line 311 of file SBModule.h.
References SBType.
Referenced by FindFirstType(), FindTypes(), GetBasicType(), GetTypeByID(), and SBType.
Member Data Documentation
m_opaque_sp
lldb::ModuleSP lldb::SBModule::m_opaque_sp private
Definition at line 321 of file SBModule.h.
Referenced by Clear(), GetObjectName(), GetSP(), operator bool(), operator!=(), operator=(), operator==(), SBModule(), SBModule(), SBModule(), and SetSP().
The documentation for this class was generated from the following files:
SBModule.h
SBModule.cpp