LLDB: lldb_private::SymbolFileType Class Reference
lldb_private::SymbolFileType Class Reference
#include <Type.h>
Public Member Functions
SymbolFileType (SymbolFile &symbol_file, lldb::user_id_t uid)
SymbolFileType (SymbolFile &symbol_file, const lldb::TypeSP &type_sp)
~SymbolFileType ()=default
Type * operator-> ()
Type * GetType ()
SymbolFile & GetSymbolFile () const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Protected Attributes
SymbolFile & m_symbol_file
lldb::TypeSP m_type_sp
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Detailed Description
Definition at line 397 of file Type.h.
Constructor & Destructor Documentation
SymbolFileType() [1/2]
lldb_private::SymbolFileType::SymbolFileType (SymbolFile & symbol_file, lldb::user_id_t uid) inline
Definition at line 400 of file Type.h.
References m_symbol_file, and lldb_private::UserID::UserID().
SymbolFileType() [2/2]
SymbolFileType::SymbolFileType (SymbolFile & symbol_file, const lldb::TypeSP & type_sp)
Definition at line 263 of file Type.cpp.
References lldb_private::UserID::GetID(), LLDB_INVALID_UID, m_symbol_file, m_type_sp, and lldb_private::UserID::UserID().
~SymbolFileType()
lldb_private::SymbolFileType::~SymbolFileType () default
Member Function Documentation
GetSymbolFile()
SymbolFile & lldb_private::SymbolFileType::GetSymbolFile () const inline
Definition at line 410 of file Type.h.
References m_symbol_file.
GetType()
Type * SymbolFileType::GetType ()
Definition at line 268 of file Type.cpp.
References lldb_private::UserID::GetID(), m_symbol_file, and m_type_sp.
Referenced by operator->().
operator->()
Type * lldb_private::SymbolFileType::operator-> () inline
Definition at line 407 of file Type.h.
References GetType().
Member Data Documentation
m_symbol_file
SymbolFile& lldb_private::SymbolFileType::m_symbol_file protected
Definition at line 413 of file Type.h.
Referenced by GetSymbolFile(), GetType(), SymbolFileType(), and SymbolFileType().
m_type_sp
lldb::TypeSP lldb_private::SymbolFileType::m_type_sp protected
Definition at line 414 of file Type.h.
Referenced by GetType(), and SymbolFileType().
The documentation for this class was generated from the following files:
Type.h
Type.cpp