LLDB: lldb_private::NativeFile Class Reference
lldb_private::NativeFile Class Reference
#include <File.h>
Classes
struct ValueGuard
Public Types
enum TransferOwnership : bool { Owned = true , Unowned = false }
Public Types inherited from lldb_private::File
enum OpenOptions : uint32_t {
eOpenOptionReadOnly = 0x0 , eOpenOptionWriteOnly = 0x1 , eOpenOptionReadWrite = 0x2 , eOpenOptionAppend ,
eOpenOptionCanCreate = 0x200 , eOpenOptionTruncate = 0x400 , eOpenOptionCanCreateNewOnly , eOpenOptionNonBlocking = (1u << 28) ,
eOpenOptionDontFollowSymlinks = (1u << 29) , eOpenOptionCloseOnExec , eOpenOptionInvalid = (1u << 31)
}
Public Types inherited from lldb_private::IOObject
enum FDType { eFDTypeFile , eFDTypeSocket }
using WaitableHandle = lldb::file_t
Public Member Functions
NativeFile ()
NativeFile (FILE *fh, OpenOptions options, bool transfer_ownership)
NativeFile (int fd, OpenOptions options, bool transfer_ownership)
~NativeFile () override
bool IsValid () const override
IsValid.
Status Read (void *buf, size_t &num_bytes) override
Read bytes from a file from the current file position into buf.
Status Write (const void *buf, size_t &num_bytes) override
Write bytes from buf to a file at the current file position.
Status Close () override
Flush any buffers and release any resources owned by the file.
WaitableHandle GetWaitableHandle () override
Get a handle that can be used for OS polling interfaces, such as WaitForMultipleObjects, select, or epoll.
Status GetFileSpec (FileSpec &file_spec) const override
Get the file specification for this file, if possible.
int GetDescriptor () const override
Get underlying OS file descriptor for this file, or kInvalidDescriptor.
FILE * GetStream () override
Get the underlying libc stream for this file, or NULL.
off_t SeekFromStart (off_t offset, Status *error_ptr=nullptr) override
Seek to an offset relative to the beginning of the file.
off_t SeekFromCurrent (off_t offset, Status *error_ptr=nullptr) override
Seek to an offset relative to the current file position.
off_t SeekFromEnd (off_t offset, Status *error_ptr=nullptr) override
Seek to an offset relative to the end of the file.
Status Read (void *dst, size_t &num_bytes, off_t &offset) override
Read bytes from a file from the specified file offset.
Status Write (const void *src, size_t &num_bytes, off_t &offset) override
Write bytes to a file at the specified file offset.
Status Flush () override
Flush the current stream.
Status Sync () override
Sync to disk.
size_t PrintfVarArg (const char *format, va_list args) override
Output printf formatted output to the stream.
llvm::Expected< OpenOptions > GetOptions () const override
Return the OpenOptions for this file.
bool isA (const void *classID) const override
Public Member Functions inherited from lldb_private::File
File ()
size_t Printf (const char *format,...) __attribute__((format(printf
Output printf formatted output to the stream.
llvm::Expected< const char * > GetOpenMode () const
uint32_t GetPermissions (Status &error) const
Get the permissions for a this file.
bool GetIsInteractive ()
Return true if this file is interactive.
bool GetIsRealTerminal ()
Return true if this file from a real terminal.
bool GetIsTerminalWithColors ()
Return true if this file is a terminal which supports colors.
operator bool () const
bool operator! () const
Public Member Functions inherited from lldb_private::IOObject
IOObject (FDType type)
virtual ~IOObject ()
FDType GetFdType () const
Static Public Member Functions
static bool classof (const File *file)
Static Public Member Functions inherited from lldb_private::File
static mode_t ConvertOpenOptionsForPOSIXOpen (OpenOptions open_options)
static llvm::Expected< OpenOptions > GetOptionsFromMode (llvm::StringRef mode)
static bool DescriptorIsValid (int descriptor)
static llvm::Expected< const char * > GetStreamOpenModeFromOptions (OpenOptions options)
static bool classof (const File *file)
Static Public Attributes
static char ID = 0
Static Public Attributes inherited from lldb_private::File
static int kInvalidDescriptor = -1
static FILE * kInvalidStream = nullptr
static constexpr OpenOptions OpenOptionsModeMask
static char ID = 0
Static Public Attributes inherited from lldb_private::IOObject
static const WaitableHandle kInvalidHandleValue = -1
Protected Member Functions
bool DescriptorIsValidUnlocked () const
bool StreamIsValidUnlocked () const
ValueGuard DescriptorIsValid () const
ValueGuard StreamIsValid () const
Protected Member Functions inherited from lldb_private::File
void CalculateInteractiveAndTerminal ()
Protected Attributes
int m_descriptor = kInvalidDescriptor
bool m_own_descriptor = false
std::mutex m_descriptor_mutex
FILE * m_stream = kInvalidStream
std::mutex m_stream_mutex
OpenOptions m_options {}
bool m_own_stream = false
std::mutex offset_access_mutex
bool is_windows_console = false
Protected Attributes inherited from lldb_private::File
LazyBool m_is_interactive = eLazyBoolCalculate
LazyBool m_is_real_terminal = eLazyBoolCalculate
LazyBool m_supports_colors = eLazyBoolCalculate
Protected Attributes inherited from lldb_private::IOObject
FDType m_fd_type
Private Member Functions
NativeFile (const NativeFile &)=delete
const NativeFile & operator= (const NativeFile &)=delete
Detailed Description
Definition at line 381 of file File.h.
Member Enumeration Documentation
TransferOwnership
enum lldb_private::NativeFile::TransferOwnership : bool
Enumerator
Owned
Unowned
Definition at line 383 of file File.h.
Constructor & Destructor Documentation
NativeFile() [1/4]
NativeFile::NativeFile () default
Referenced by NativeFile(), operator=(), and lldb_private::SerialPort::SerialPort().
NativeFile() [2/4]
NativeFile::NativeFile (FILE * fh, OpenOptions options, bool transfer_ownership)
Definition at line 252 of file File.cpp.
References lldb_private::File::ConvertOpenOptionsForPOSIXOpen(), is_windows_console, m_options, m_own_stream, and m_stream.
NativeFile() [3/4]
NativeFile::NativeFile (int fd, OpenOptions options, bool transfer_ownership)
Definition at line 284 of file File.cpp.
References is_windows_console, m_descriptor, m_options, and m_own_descriptor.
~NativeFile()
lldb_private::NativeFile::~NativeFile () inline override
Definition at line 394 of file File.h.
References Close().
NativeFile() [4/4]
lldb_private::NativeFile::NativeFile (const NativeFile &) private delete
References NativeFile().
Member Function Documentation
classof()
bool lldb_private::NativeFile::classof (const File * file) inline static
Definition at line 419 of file File.h.
References lldb_private::File::File(), ID, and lldb_private::File::isA().
Close()
Status NativeFile::Close () override virtual
Flush any buffers and release any resources owned by the file.
After Close() the file will be invalid.
Returns
success or an error.
Reimplemented from lldb_private::File.
Reimplemented in lldb_private::SerialPort.
Definition at line 366 of file File.cpp.
References DescriptorIsValidUnlocked(), lldb_private::eLazyBoolCalculate, lldb_private::File::eOpenOptionReadOnly, lldb_private::File::eOpenOptionReadWrite, lldb_private::File::eOpenOptionWriteOnly, error(), lldb_private::Status::FromErrno(), lldb_private::File::kInvalidDescriptor, lldb_private::File::kInvalidStream, m_descriptor, m_descriptor_mutex, lldb_private::File::m_is_interactive, lldb_private::File::m_is_real_terminal, m_options, m_own_descriptor, m_own_stream, m_stream, m_stream_mutex, and StreamIsValidUnlocked().
Referenced by lldb_private::ClangUtilityFunction::ClangUtilityFunction(), lldb_private::SerialPort::Close(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_Close(), lldb_private::ClangExpressionParser::ParseInternal(), and ~NativeFile().
DescriptorIsValid()
ValueGuard lldb_private::NativeFile::DescriptorIsValid () const inline protected
Definition at line 436 of file File.h.
References DescriptorIsValidUnlocked(), and m_descriptor_mutex.
Referenced by Flush(), GetDescriptor(), GetStream(), Read(), SeekFromCurrent(), SeekFromEnd(), SeekFromStart(), Sync(), and Write().
DescriptorIsValidUnlocked()
bool lldb_private::NativeFile::DescriptorIsValidUnlocked () const inline protected
Definition at line 429 of file File.h.
References lldb_private::File::DescriptorIsValid(), and m_descriptor.
Referenced by Close(), DescriptorIsValid(), and IsValid().
Flush()
Status NativeFile::Flush () override virtual
Flush the current stream.
Returns
An error object that indicates success or the reason for failure.
Reimplemented from lldb_private::File.
Definition at line 531 of file File.cpp.
References DescriptorIsValid(), error(), lldb_private::Status::FromErrno(), lldb_private::Status::FromErrorString(), m_stream, and StreamIsValid().
GetDescriptor()
int NativeFile::GetDescriptor () const override virtual
Get underlying OS file descriptor for this file, or kInvalidDescriptor.
If the descriptor is valid, then it may be used directly for I/O However, the File may also perform it's own buffering, so avoid using this if it is not necessary, or use Flush() appropriately.
Returns
a valid file descriptor for this file or kInvalidDescriptor
Reimplemented from lldb_private::File.
Definition at line 304 of file File.cpp.
References DescriptorIsValid(), lldb_private::File::kInvalidDescriptor, m_descriptor, m_stream, and StreamIsValid().
Referenced by GetFileSpec(), GetWaitableHandle(), Read(), and Write().
GetFileSpec()
Status NativeFile::GetFileSpec (FileSpec & file_spec) const override virtual
Get the file specification for this file, if possible.
Parameters
[out] file_spec the file specification.
Returns
ENOTSUP, success, or another error.
Reimplemented from lldb_private::File.
Definition at line 403 of file File.cpp.
References lldb_private::FileSpec::Clear(), error(), lldb_private::Status::FromErrno(), lldb_private::Status::FromErrorString(), GetDescriptor(), IsValid(), PATH_MAX, and lldb_private::FileSpec::SetFile().
GetOptions()
Expected< File::OpenOptions > NativeFile::GetOptions () const override virtual
Return the OpenOptions for this file.
Some options like eOpenOptionDontFollowSymlinks only make sense when a file is being opened (or not at all) and may not be preserved for this method. But any valid File should return either eOpenOptionReadOnly, eOpenOptionWriteOnly or eOpenOptionReadWrite here.
Returns
OpenOptions flags for this file, or an error.
Reimplemented from lldb_private::File.
Definition at line 302 of file File.cpp.
References m_options.
GetStream()
FILE * NativeFile::GetStream () override virtual
Get the underlying libc stream for this file, or NULL.
Not all valid files will have a FILE* stream. This should only be used if absolutely necessary, such as to interact with 3rd party libraries that need FILE* streams.
Returns
a valid stream or NULL;
Reimplemented from lldb_private::File.
Definition at line 331 of file File.cpp.
References DescriptorIsValid(), lldb_private::File::GetStreamOpenModeFromOptions(), m_descriptor, m_options, m_own_descriptor, m_own_stream, m_stream, and StreamIsValid().
GetWaitableHandle()
IOObject::WaitableHandle NativeFile::GetWaitableHandle () override virtual
Get a handle that can be used for OS polling interfaces, such as WaitForMultipleObjects, select, or epoll.
This may return IOObject::kInvalidHandleValue if none is available. This will generally be the same as the file descriptor, this function is not interchangeable with GetDescriptor(). A WaitableHandle must only be used for polling, not actual I/O.
Returns
a valid handle or IOObject::kInvalidHandleValue
Reimplemented from lldb_private::File.
Definition at line 323 of file File.cpp.
References GetDescriptor().
isA()
bool lldb_private::NativeFile::isA (const void * classID) const inline override virtual
Reimplemented from lldb_private::File.
Reimplemented in lldb_private::SerialPort.
Definition at line 416 of file File.h.
References ID, and lldb_private::File::isA().
IsValid()
bool NativeFile::IsValid () const override virtual
IsValid.
Returns
true iff the file is valid.
Reimplemented from lldb_private::File.
Reimplemented in lldb_private::SerialPort.
Definition at line 296 of file File.cpp.
References DescriptorIsValidUnlocked(), m_descriptor_mutex, m_stream_mutex, and StreamIsValidUnlocked().
Referenced by GetFileSpec(), and lldb_private::SerialPort::IsValid().
operator=()
const NativeFile & lldb_private::NativeFile::operator= (const NativeFile &) private delete
References NativeFile().
PrintfVarArg()
size_t NativeFile::PrintfVarArg (const char * format, va_list args) override virtual
Output printf formatted output to the stream.
Print some formatted output to the stream.
Parameters
[in] format A printf style format string.
[in] args Variable arguments that are needed for the printf style format string format.
Reimplemented from lldb_private::File.
Definition at line 837 of file File.cpp.
References m_stream, lldb_private::File::PrintfVarArg(), and StreamIsValid().
Read() [1/2]
Status NativeFile::Read (void * buf, size_t & num_bytes) override virtual
Read bytes from a file from the current file position into buf.
NOTE: This function is NOT thread safe. Use the read function that takes an "off_t &offset" to ensure correct operation in multi- threaded environments.
Parameters
[in,out] num_bytes Pass in the size of buf. Read will pass out the number of bytes read. Zero bytes read with no error indicates EOF.
Returns
success, ENOTSUP, or another error.
Reimplemented from lldb_private::File.
Definition at line 570 of file File.cpp.
References DescriptorIsValid(), lldb_private::File::eOpenOptionWriteOnly, error(), lldb_private::Status::FromErrno(), lldb_private::Status::FromErrorString(), m_descriptor, m_options, m_stream, lldb_private::File::OpenOptionsModeMask, Read(), lldb_private::Status, and StreamIsValid().
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_pRead(), Read(), and Read().
Read() [2/2]
Status NativeFile::Read (void * dst, size_t & num_bytes, off_t & offset) override virtual
Read bytes from a file from the specified file offset.
NOTE: This function is thread safe in that clients manager their own file position markers and reads on other threads won't mess up the current read.
Parameters
[in] dst A buffer where to put the bytes that are read.
[in,out] num_bytes The number of bytes to read from the current file position which gets modified with the number of bytes that were read.
[in,out] offset The offset within the file from which to read num_bytes bytes. This offset gets incremented by the number of bytes that were read.
Returns
An error object that indicates success or the reason for failure.
Reimplemented from lldb_private::File.
Definition at line 713 of file File.cpp.
References error(), lldb_private::Status::FromErrno(), lldb_private::Status::FromErrorString(), GetDescriptor(), lldb_private::File::kInvalidDescriptor, m_descriptor, offset_access_mutex, Read(), and SeekFromStart().
SeekFromCurrent()
off_t NativeFile::SeekFromCurrent (off_t offset, Status * error_ptr = nullptr) override virtual
Seek to an offset relative to the current file position.
NOTE: This function is NOT thread safe, other threads that access this object might also change the current file position. For thread safe reads and writes see the following functions:
See also
File::Read (void *, size_t, off_t &)
File::Write (const void *, size_t, off_t &)
Parameters
[in] offset The offset to seek to within the file relative to the current file position.
[in] error_ptr A pointer to a lldb_private::Status object that will be filled in if non-nullptr.
Returns
The resulting seek offset, or -1 on error.
Reimplemented from lldb_private::File.
Definition at line 470 of file File.cpp.
References lldb_private::Status::Clear(), DescriptorIsValid(), lldb_private::Status::FromErrno(), lldb_private::Status::FromErrorString(), m_descriptor, m_stream, and StreamIsValid().
SeekFromEnd()
off_t NativeFile::SeekFromEnd (off_t offset, Status * error_ptr = nullptr) override virtual
Seek to an offset relative to the end of the file.
NOTE: This function is NOT thread safe, other threads that access this object might also change the current file position. For thread safe reads and writes see the following functions:
See also
File::Read (void *, size_t, off_t &)
File::Write (const void *, size_t, off_t &)
Parameters
[in,out] offset The offset to seek to within the file relative to the end of the file which gets filled in with the resulting absolute file offset.
[in] error_ptr A pointer to a lldb_private::Status object that will be filled in if non-nullptr.
Returns
The resulting seek offset, or -1 on error.
Reimplemented from lldb_private::File.
Definition at line 501 of file File.cpp.
References lldb_private::Status::Clear(), DescriptorIsValid(), lldb_private::Status::FromErrno(), lldb_private::Status::FromErrorString(), m_descriptor, m_stream, and StreamIsValid().
SeekFromStart()
off_t NativeFile::SeekFromStart (off_t offset, Status * error_ptr = nullptr) override virtual
Seek to an offset relative to the beginning of the file.
NOTE: This function is NOT thread safe, other threads that access this object might also change the current file position. For thread safe reads and writes see the following functions:
See also
File::Read (void *, size_t, off_t &)
File::Write (const void *, size_t, off_t &)
Parameters
[in] offset The offset to seek to within the file relative to the beginning of the file.
[in] error_ptr A pointer to a lldb_private::Status object that will be filled in if non-nullptr.
Returns
The resulting seek offset, or -1 on error.
Reimplemented from lldb_private::File.
Definition at line 439 of file File.cpp.
References lldb_private::Status::Clear(), DescriptorIsValid(), lldb_private::Status::FromErrno(), lldb_private::Status::FromErrorString(), m_descriptor, m_stream, and StreamIsValid().
Referenced by Read(), and Write().
StreamIsValid()
ValueGuard lldb_private::NativeFile::StreamIsValid () const inline protected
Definition at line 441 of file File.h.
References m_stream_mutex, and StreamIsValidUnlocked().
Referenced by Flush(), GetDescriptor(), GetStream(), PrintfVarArg(), Read(), SeekFromCurrent(), SeekFromEnd(), SeekFromStart(), and Write().
StreamIsValidUnlocked()
bool lldb_private::NativeFile::StreamIsValidUnlocked () const inline protected
Definition at line 434 of file File.h.
References lldb_private::File::kInvalidStream, and m_stream.
Referenced by Close(), IsValid(), and StreamIsValid().
Sync()
Status NativeFile::Sync () override virtual
Sync to disk.
Returns
An error object that indicates success or the reason for failure.
Reimplemented from lldb_private::File.
Definition at line 547 of file File.cpp.
References DescriptorIsValid(), error(), lldb_private::Status::FromErrno(), lldb_private::Status::FromErrorString(), and m_descriptor.
Write() [1/2]
Status NativeFile::Write (const void * buf, size_t & num_bytes) override virtual
Write bytes from buf to a file at the current file position.
NOTE: This function is NOT thread safe. Use the write function that takes an "off_t &offset" to ensure correct operation in multi- threaded environments.
Parameters
[in,out] num_bytes Pass in the size of buf. Write will pass out the number of bytes written. Write will attempt write the full number of bytes and will not return early except on error.
Returns
success, ENOTSUP, or another error.
Reimplemented from lldb_private::File.
Definition at line 638 of file File.cpp.
References DescriptorIsValid(), lldb_private::File::eOpenOptionReadOnly, error(), lldb_private::Status::FromErrno(), lldb_private::Status::FromErrorString(), is_windows_console, m_descriptor, m_options, m_stream, lldb_private::File::OpenOptionsModeMask, lldb_private::Status, StreamIsValid(), and Write().
Referenced by lldb_private::ClangUtilityFunction::ClangUtilityFunction(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_pWrite(), lldb_private::ClangExpressionParser::ParseInternal(), Write(), and Write().
Write() [2/2]
Status NativeFile::Write (const void * src, size_t & num_bytes, off_t & offset) override virtual
Write bytes to a file at the specified file offset.
NOTE: This function is thread safe in that clients manager their own file position markers, though clients will need to implement their own locking externally to avoid multiple people writing to the file at the same time.
Parameters
[in] src A buffer containing the bytes to write.
[in,out] num_bytes The number of bytes to write to the file at offset offset. num_bytes gets modified with the number of bytes that were read.
[in,out] offset The offset within the file at which to write num_bytes bytes. This offset gets incremented by the number of bytes that were written.
Returns
An error object that indicates success or the reason for failure.
Reimplemented from lldb_private::File.
Definition at line 773 of file File.cpp.
References error(), lldb_private::Status::FromErrno(), lldb_private::Status::FromErrorString(), GetDescriptor(), lldb_private::File::kInvalidDescriptor, m_descriptor, offset_access_mutex, SeekFromStart(), and Write().
Member Data Documentation
ID
char NativeFile::ID = 0 static
Definition at line 415 of file File.h.
Referenced by classof(), and isA().
is_windows_console
bool lldb_private::NativeFile::is_windows_console = false protected
Definition at line 457 of file File.h.
Referenced by NativeFile(), NativeFile(), and Write().
m_descriptor
int lldb_private::NativeFile::m_descriptor = kInvalidDescriptor protected
Definition at line 446 of file File.h.
Referenced by Close(), DescriptorIsValidUnlocked(), GetDescriptor(), GetStream(), NativeFile(), Read(), Read(), SeekFromCurrent(), SeekFromEnd(), SeekFromStart(), Sync(), Write(), and Write().
m_descriptor_mutex
std::mutex lldb_private::NativeFile::m_descriptor_mutex mutable protected
Definition at line 448 of file File.h.
Referenced by Close(), DescriptorIsValid(), and IsValid().
m_options
OpenOptions lldb_private::NativeFile::m_options {} protected
Definition at line 453 of file File.h.
Referenced by Close(), GetOptions(), GetStream(), NativeFile(), NativeFile(), Read(), and Write().
m_own_descriptor
bool lldb_private::NativeFile::m_own_descriptor = false protected
Definition at line 447 of file File.h.
Referenced by Close(), GetStream(), and NativeFile().
m_own_stream
bool lldb_private::NativeFile::m_own_stream = false protected
Definition at line 454 of file File.h.
Referenced by Close(), GetStream(), and NativeFile().
m_stream
FILE* lldb_private::NativeFile::m_stream = kInvalidStream protected
Definition at line 450 of file File.h.
Referenced by Close(), Flush(), GetDescriptor(), GetStream(), NativeFile(), PrintfVarArg(), Read(), SeekFromCurrent(), SeekFromEnd(), SeekFromStart(), StreamIsValidUnlocked(), and Write().
m_stream_mutex
std::mutex lldb_private::NativeFile::m_stream_mutex mutable protected
Definition at line 451 of file File.h.
Referenced by Close(), IsValid(), and StreamIsValid().
offset_access_mutex
std::mutex lldb_private::NativeFile::offset_access_mutex protected
Definition at line 455 of file File.h.
Referenced by Read(), and Write().
The documentation for this class was generated from the following files:
File.h
File.cpp