LLDB: lldb_private::dil::Visitor Class Reference
lldb_private::dil::Visitor Class Reference abstract
This class contains one Visit method for each specialized type of DIL AST node.
#include <DILAST.h>
Public Member Functions
virtual ~Visitor ()=default
virtual llvm::Expected< lldb::ValueObjectSP > Visit (const IdentifierNode &node)=0
virtual llvm::Expected< lldb::ValueObjectSP > Visit (const MemberOfNode &node)=0
virtual llvm::Expected< lldb::ValueObjectSP > Visit (const UnaryOpNode &node)=0
virtual llvm::Expected< lldb::ValueObjectSP > Visit (const ArraySubscriptNode &node)=0
virtual llvm::Expected< lldb::ValueObjectSP > Visit (const BitFieldExtractionNode &node)=0
virtual llvm::Expected< lldb::ValueObjectSP > Visit (const IntegerLiteralNode &node)=0
virtual llvm::Expected< lldb::ValueObjectSP > Visit (const FloatLiteralNode &node)=0
virtual llvm::Expected< lldb::ValueObjectSP > Visit (const BooleanLiteralNode &node)=0
virtual llvm::Expected< lldb::ValueObjectSP > Visit (const CastNode &node)=0
Detailed Description
This class contains one Visit method for each specialized type of DIL AST node.
The Visit methods are used to dispatch a DIL AST node to the correct function in the DIL expression evaluator for evaluating that type of AST node.
Definition at line 285 of file DILAST.h.
Constructor & Destructor Documentation
~Visitor()
virtual lldb_private::dil::Visitor::~Visitor () virtual default
Member Function Documentation
Visit() [1/9]
virtual llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::Visitor::Visit (const ArraySubscriptNode & node) pure virtual
Implemented in lldb_private::dil::Interpreter.
Visit() [2/9]
virtual llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::Visitor::Visit (const BitFieldExtractionNode & node) pure virtual
Implemented in lldb_private::dil::Interpreter.
Visit() [3/9]
virtual llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::Visitor::Visit (const BooleanLiteralNode & node) pure virtual
Implemented in lldb_private::dil::Interpreter.
Visit() [4/9]
virtual llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::Visitor::Visit (const CastNode & node) pure virtual
Implemented in lldb_private::dil::Interpreter.
Visit() [5/9]
virtual llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::Visitor::Visit (const FloatLiteralNode & node) pure virtual
Implemented in lldb_private::dil::Interpreter.
Visit() [6/9]
virtual llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::Visitor::Visit (const IdentifierNode & node) pure virtual
Implemented in lldb_private::dil::Interpreter.
Referenced by lldb_private::dil::ArraySubscriptNode::Accept(), lldb_private::dil::BitFieldExtractionNode::Accept(), lldb_private::dil::BooleanLiteralNode::Accept(), lldb_private::dil::CastNode::Accept(), lldb_private::dil::FloatLiteralNode::Accept(), lldb_private::dil::IdentifierNode::Accept(), lldb_private::dil::IntegerLiteralNode::Accept(), lldb_private::dil::MemberOfNode::Accept(), and lldb_private::dil::UnaryOpNode::Accept().
Visit() [7/9]
virtual llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::Visitor::Visit (const IntegerLiteralNode & node) pure virtual
Implemented in lldb_private::dil::Interpreter.
Visit() [8/9]
virtual llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::Visitor::Visit (const MemberOfNode & node) pure virtual
Implemented in lldb_private::dil::Interpreter.
Visit() [9/9]
virtual llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::Visitor::Visit (const UnaryOpNode & node) pure virtual
Implemented in lldb_private::dil::Interpreter.
The documentation for this class was generated from the following file:
DILAST.h