LLDB: lldb_private::SystemInitializerCommon Class Reference
lldb_private::SystemInitializerCommon Class Reference
Initializes common lldb functionality.
#include <SystemInitializerCommon.h>
Public Member Functions
SystemInitializerCommon (HostInfo::SharedLibraryDirectoryHelper *helper)
~SystemInitializerCommon () override
llvm::Error Initialize () override
void Terminate () override
Public Member Functions inherited from lldb_private::SystemInitializer
SystemInitializer ()
virtual ~SystemInitializer ()
Private Attributes
HostInfo::SharedLibraryDirectoryHelper * m_shlib_dir_helper
Detailed Description
Initializes common lldb functionality.
This class is responsible for initializing a subset of lldb useful to both debug servers and debug clients. Debug servers do not use all of LLDB and desire small binary sizes, so this functionality is separate. This class is used by constructing an instance of SystemLifetimeManager with this class passed to the constructor.
Definition at line 24 of file SystemInitializerCommon.h.
Constructor & Destructor Documentation
SystemInitializerCommon()
SystemInitializerCommon::SystemInitializerCommon (HostInfo::SharedLibraryDirectoryHelper * helper)
Definition at line 38 of file SystemInitializerCommon.cpp.
References m_shlib_dir_helper.
Referenced by lldb_private::SystemInitializerFull::SystemInitializerFull().
~SystemInitializerCommon()
SystemInitializerCommon::~SystemInitializerCommon () override default
Member Function Documentation
Initialize()
llvm::Error SystemInitializerCommon::Initialize () override virtual
Implements lldb_private::SystemInitializer.
Reimplemented in lldb_private::SystemInitializerFull.
Definition at line 44 of file SystemInitializerCommon.cpp.
References error(), lldb_private::Diagnostics::Initialize(), lldb_private::FileSystem::Initialize(), lldb_private::process_gdb_remote::ProcessGDBRemoteLog::Initialize(), lldb_private::ProcessPOSIXLog::Initialize(), lldb_private::ProcessWindowsLog::Initialize(), lldb_private::Socket::Initialize(), lldb_private::InitializeLldbChannel(), LLDB_SCOPED_TIMER, and m_shlib_dir_helper.
Referenced by lldb_private::SystemInitializerFull::Initialize().
Terminate()
void SystemInitializerCommon::Terminate () override virtual
Implements lldb_private::SystemInitializer.
Reimplemented in lldb_private::SystemInitializerFull.
Definition at line 92 of file SystemInitializerCommon.cpp.
References lldb_private::Log::DisableAllLogChannels(), LLDB_SCOPED_TIMER, lldb_private::Diagnostics::Terminate(), lldb_private::FileSystem::Terminate(), lldb_private::ProcessWindowsLog::Terminate(), and lldb_private::Socket::Terminate().
Referenced by lldb_private::SystemInitializerFull::Terminate().
Member Data Documentation
m_shlib_dir_helper
HostInfo::SharedLibraryDirectoryHelper* lldb_private::SystemInitializerCommon::m_shlib_dir_helper private
Definition at line 33 of file SystemInitializerCommon.h.
Referenced by Initialize(), and SystemInitializerCommon().
The documentation for this class was generated from the following files:
SystemInitializerCommon.h
SystemInitializerCommon.cpp