LLDB: lldb_private::ScriptInterpreter Class Reference
lldb_private::ScriptInterpreter Class Reference abstract
#include <ScriptInterpreter.h>
Public Types
enum ScriptReturnType {
eScriptReturnTypeCharPtr , eScriptReturnTypeBool , eScriptReturnTypeShortInt , eScriptReturnTypeShortIntUnsigned ,
eScriptReturnTypeInt , eScriptReturnTypeIntUnsigned , eScriptReturnTypeLongInt , eScriptReturnTypeLongIntUnsigned ,
eScriptReturnTypeLongLong , eScriptReturnTypeLongLongUnsigned , eScriptReturnTypeFloat , eScriptReturnTypeDouble ,
eScriptReturnTypeChar , eScriptReturnTypeCharStrOrNone , eScriptReturnTypeOpaqueObject
}
Public Member Functions
ScriptInterpreter (Debugger &debugger, lldb::ScriptLanguage script_lang)
virtual StructuredData::DictionarySP GetInterpreterInfo ()
~ScriptInterpreter () override=default
virtual bool Interrupt ()
virtual bool ExecuteOneLine (llvm::StringRef command, CommandReturnObject *result, const ExecuteScriptOptions &options=ExecuteScriptOptions())=0
virtual void ExecuteInterpreterLoop ()=0
virtual bool ExecuteOneLineWithReturn (llvm::StringRef in_string, ScriptReturnType return_type, void *ret_value, const ExecuteScriptOptions &options=ExecuteScriptOptions())
virtual Status ExecuteMultipleLines (const char *in_string, const ExecuteScriptOptions &options=ExecuteScriptOptions())
virtual Status ExportFunctionDefinitionToInterpreter (StringList &function_def)
virtual Status GenerateBreakpointCommandCallbackData (StringList &input, std::string &output, bool has_extra_args, bool is_callback)
virtual bool GenerateWatchpointCommandCallbackData (StringList &input, std::string &output, bool is_callback)
virtual bool GenerateTypeScriptFunction (const char *oneliner, std::string &output, const void *name_token=nullptr)
virtual bool GenerateTypeScriptFunction (StringList &input, std::string &output, const void *name_token=nullptr)
virtual bool GenerateScriptAliasFunction (StringList &input, std::string &output)
virtual bool GenerateTypeSynthClass (StringList &input, std::string &output, const void *name_token=nullptr)
virtual bool GenerateTypeSynthClass (const char *oneliner, std::string &output, const void *name_token=nullptr)
virtual StructuredData::ObjectSP CreateSyntheticScriptedProvider (const char *class_name, lldb::ValueObjectSP valobj)
virtual StructuredData::GenericSP CreateScriptCommandObject (const char *class_name)
virtual StructuredData::GenericSP CreateFrameRecognizer (const char *class_name)
virtual lldb::ValueObjectListSP GetRecognizedArguments (const StructuredData::ObjectSP &implementor, lldb::StackFrameSP frame_sp)
virtual bool ShouldHide (const StructuredData::ObjectSP &implementor, lldb::StackFrameSP frame_sp)
virtual StructuredData::ObjectSP LoadPluginModule (const FileSpec &file_spec, lldb_private::Status &error)
virtual StructuredData::DictionarySP GetDynamicSettings (StructuredData::ObjectSP plugin_module_sp, Target *target, const char *setting_name, lldb_private::Status &error)
virtual Status GenerateFunction (const char *signature, const StringList &input, bool is_callback)
virtual void CollectDataForBreakpointCommandCallback (std::vector< std::reference_wrapper< BreakpointOptions > > &options, CommandReturnObject &result)
virtual void CollectDataForWatchpointCommandCallback (WatchpointOptions *wp_options, CommandReturnObject &result)
Status SetBreakpointCommandCallback (std::vector< std::reference_wrapper< BreakpointOptions > > &bp_options_vec, const char *callback_text)
Set the specified text as the callback for the breakpoint.
virtual Status SetBreakpointCommandCallback (BreakpointOptions &bp_options, const char *callback_text, bool is_callback)
virtual Status SetBreakpointCommandCallback (BreakpointOptions &bp_options, std::unique_ptr< BreakpointOptions::CommandData > &data_up)
This one is for deserialization:
Status SetBreakpointCommandCallbackFunction (std::vector< std::reference_wrapper< BreakpointOptions > > &bp_options_vec, const char *function_name, StructuredData::ObjectSP extra_args_sp)
virtual Status SetBreakpointCommandCallbackFunction (BreakpointOptions &bp_options, const char *function_name, StructuredData::ObjectSP extra_args_sp)
Set a script function as the callback for the breakpoint.
virtual void SetWatchpointCommandCallback (WatchpointOptions *wp_options, const char *user_input, bool is_callback)
Set a one-liner as the callback for the watchpoint.
virtual bool GetScriptedSummary (const char *function_name, lldb::ValueObjectSP valobj, StructuredData::ObjectSP &callee_wrapper_sp, const TypeSummaryOptions &options, std::string &retval)
virtual bool FormatterCallbackFunction (const char *function_name, lldb::TypeImplSP type_impl_sp)
virtual void Clear ()
virtual size_t CalculateNumChildren (const StructuredData::ObjectSP &implementor, uint32_t max)
virtual lldb::ValueObjectSP GetChildAtIndex (const StructuredData::ObjectSP &implementor, uint32_t idx)
virtual llvm::Expected< uint32_t > GetIndexOfChildWithName (const StructuredData::ObjectSP &implementor, const char *child_name)
virtual bool UpdateSynthProviderInstance (const StructuredData::ObjectSP &implementor)
virtual bool MightHaveChildrenSynthProviderInstance (const StructuredData::ObjectSP &implementor)
virtual lldb::ValueObjectSP GetSyntheticValue (const StructuredData::ObjectSP &implementor)
virtual ConstString GetSyntheticTypeName (const StructuredData::ObjectSP &implementor)
virtual bool RunScriptBasedCommand (const char *impl_function, llvm::StringRef args, ScriptedCommandSynchronicity synchronicity, lldb_private::CommandReturnObject &cmd_retobj, Status &error, const lldb_private::ExecutionContext &exe_ctx)
virtual bool RunScriptBasedCommand (StructuredData::GenericSP impl_obj_sp, llvm::StringRef args, ScriptedCommandSynchronicity synchronicity, lldb_private::CommandReturnObject &cmd_retobj, Status &error, const lldb_private::ExecutionContext &exe_ctx)
virtual bool RunScriptBasedParsedCommand (StructuredData::GenericSP impl_obj_sp, Args &args, ScriptedCommandSynchronicity synchronicity, lldb_private::CommandReturnObject &cmd_retobj, Status &error, const lldb_private::ExecutionContext &exe_ctx)
virtual std::optional< std::string > GetRepeatCommandForScriptedCommand (StructuredData::GenericSP impl_obj_sp, Args &args)
virtual StructuredData::DictionarySP HandleArgumentCompletionForScriptedCommand (StructuredData::GenericSP impl_obj_sp, std::vector< llvm::StringRef > &args, size_t args_pos, size_t char_in_arg)
virtual StructuredData::DictionarySP HandleOptionArgumentCompletionForScriptedCommand (StructuredData::GenericSP impl_obj_sp, llvm::StringRef &long_name, size_t char_in_arg)
virtual bool RunScriptFormatKeyword (const char *impl_function, Process *process, std::string &output, Status &error)
virtual bool RunScriptFormatKeyword (const char *impl_function, Thread *thread, std::string &output, Status &error)
virtual bool RunScriptFormatKeyword (const char *impl_function, Target *target, std::string &output, Status &error)
virtual bool RunScriptFormatKeyword (const char *impl_function, StackFrame *frame, std::string &output, Status &error)
virtual bool RunScriptFormatKeyword (const char *impl_function, ValueObject *value, std::string &output, Status &error)
virtual bool GetDocumentationForItem (const char *item, std::string &dest)
virtual bool GetShortHelpForCommandObject (StructuredData::GenericSP cmd_obj_sp, std::string &dest)
virtual StructuredData::ObjectSP GetOptionsForCommandObject (StructuredData::GenericSP cmd_obj_sp)
virtual StructuredData::ObjectSP GetArgumentsForCommandObject (StructuredData::GenericSP cmd_obj_sp)
virtual bool SetOptionValueForCommandObject (StructuredData::GenericSP cmd_obj_sp, ExecutionContext *exe_ctx, llvm::StringRef long_option, llvm::StringRef value)
virtual void OptionParsingStartedForCommandObject (StructuredData::GenericSP cmd_obj_sp)
virtual uint32_t GetFlagsForCommandObject (StructuredData::GenericSP cmd_obj_sp)
virtual bool GetLongHelpForCommandObject (StructuredData::GenericSP cmd_obj_sp, std::string &dest)
virtual bool CheckObjectExists (const char *name)
virtual bool LoadScriptingModule (const char *filename, const LoadScriptOptions &options, lldb_private::Status &error, StructuredData::ObjectSP *module_sp=nullptr, FileSpec extra_search_dir={}, lldb::TargetSP loaded_into_target_sp={})
virtual bool IsReservedWord (const char *word)
virtual std::unique_ptr< ScriptInterpreterLocker > AcquireInterpreterLock ()
const char * GetScriptInterpreterPtyName ()
virtual llvm::Expected< unsigned > GetMaxPositionalArgumentsForCallable (const llvm::StringRef &callable_name)
lldb::ScriptLanguage GetLanguage ()
virtual lldb::ScriptedProcessInterfaceUP CreateScriptedProcessInterface ()
virtual lldb::ScriptedThreadInterfaceSP CreateScriptedThreadInterface ()
virtual lldb::ScriptedFrameInterfaceSP CreateScriptedFrameInterface ()
virtual lldb::ScriptedFrameProviderInterfaceSP CreateScriptedFrameProviderInterface ()
virtual lldb::ScriptedThreadPlanInterfaceSP CreateScriptedThreadPlanInterface ()
virtual lldb::OperatingSystemInterfaceSP CreateOperatingSystemInterface ()
virtual lldb::ScriptedPlatformInterfaceUP GetScriptedPlatformInterface ()
virtual lldb::ScriptedStopHookInterfaceSP CreateScriptedStopHookInterface ()
virtual lldb::ScriptedBreakpointInterfaceSP CreateScriptedBreakpointInterface ()
virtual StructuredData::ObjectSP CreateStructuredDataFromScriptObject (ScriptObject obj)
lldb::DataExtractorSP GetDataExtractorFromSBData (const lldb::SBData &data) const
Status GetStatusFromSBError (const lldb::SBError &error) const
Event * GetOpaqueTypeFromSBEvent (const lldb::SBEvent &event) const
lldb::StreamSP GetOpaqueTypeFromSBStream (const lldb::SBStream &stream) const
lldb::ThreadSP GetOpaqueTypeFromSBThread (const lldb::SBThread &exe_ctx) const
lldb::StackFrameSP GetOpaqueTypeFromSBFrame (const lldb::SBFrame &frame) const
SymbolContext GetOpaqueTypeFromSBSymbolContext (const lldb::SBSymbolContext &sym_ctx) const
lldb::BreakpointSP GetOpaqueTypeFromSBBreakpoint (const lldb::SBBreakpoint &breakpoint) const
lldb::BreakpointLocationSP GetOpaqueTypeFromSBBreakpointLocation (const lldb::SBBreakpointLocation &break_loc) const
lldb::ProcessAttachInfoSP GetOpaqueTypeFromSBAttachInfo (const lldb::SBAttachInfo &attach_info) const
lldb::ProcessLaunchInfoSP GetOpaqueTypeFromSBLaunchInfo (const lldb::SBLaunchInfo &launch_info) const
std::optional< MemoryRegionInfo > GetOpaqueTypeFromSBMemoryRegionInfo (const lldb::SBMemoryRegionInfo &mem_region) const
lldb::ExecutionContextRefSP GetOpaqueTypeFromSBExecutionContext (const lldb::SBExecutionContext &exe_ctx) const
lldb::StackFrameListSP GetOpaqueTypeFromSBFrameList (const lldb::SBFrameList &exe_ctx) const
lldb::ValueObjectSP GetOpaqueTypeFromSBValue (const lldb::SBValue &value) const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
virtual llvm::StringRef GetPluginName ()=0
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static std::string LanguageToString (lldb::ScriptLanguage language)
static lldb::ScriptLanguage StringToLanguage (const llvm::StringRef &string)
Protected Attributes
Debugger & m_debugger
lldb::ScriptLanguage m_script_lang
Detailed Description
Definition at line 149 of file ScriptInterpreter.h.
Member Enumeration Documentation
ScriptReturnType
enum lldb_private::ScriptInterpreter::ScriptReturnType
Enumerator
eScriptReturnTypeCharPtr
eScriptReturnTypeBool
eScriptReturnTypeShortInt
eScriptReturnTypeShortIntUnsigned
eScriptReturnTypeInt
eScriptReturnTypeIntUnsigned
eScriptReturnTypeLongInt
eScriptReturnTypeLongIntUnsigned
eScriptReturnTypeLongLong
eScriptReturnTypeLongLongUnsigned
eScriptReturnTypeFloat
eScriptReturnTypeDouble
eScriptReturnTypeChar
eScriptReturnTypeCharStrOrNone
eScriptReturnTypeOpaqueObject
Definition at line 151 of file ScriptInterpreter.h.
Constructor & Destructor Documentation
ScriptInterpreter()
ScriptInterpreter::ScriptInterpreter (Debugger & debugger, lldb::ScriptLanguage script_lang)
Definition at line 31 of file ScriptInterpreter.cpp.
References m_debugger, and m_script_lang.
Referenced by lldb_private::ScriptInterpreterLua::ScriptInterpreterLua(), lldb_private::ScriptInterpreterNone::ScriptInterpreterNone(), and lldb_private::ScriptInterpreterPython::ScriptInterpreterPython().
~ScriptInterpreter()
lldb_private::ScriptInterpreter::~ScriptInterpreter () override default
Member Function Documentation
AcquireInterpreterLock()
std::unique_ptr< ScriptInterpreterLocker > ScriptInterpreter::AcquireInterpreterLock () virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 213 of file ScriptInterpreter.cpp.
CalculateNumChildren()
virtual size_t lldb_private::ScriptInterpreter::CalculateNumChildren (const StructuredData::ObjectSP & implementor, uint32_t max) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 348 of file ScriptInterpreter.h.
CheckObjectExists()
virtual bool lldb_private::ScriptInterpreter::CheckObjectExists (const char * name) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 504 of file ScriptInterpreter.h.
Referenced by CommandObjectFrameRecognizerAdd::DoExecute(), and CommandObjectTypeFilterAdd::CommandOptions::OptionParsingStarting().
Clear()
virtual void lldb_private::ScriptInterpreter::Clear () inline virtual
Definition at line 343 of file ScriptInterpreter.h.
CollectDataForBreakpointCommandCallback()
void ScriptInterpreter::CollectDataForBreakpointCommandCallback (std::vector< std::reference_wrapper< BreakpointOptions > > & options, CommandReturnObject & result) virtual
Reimplemented in lldb_private::ScriptInterpreterLua, and lldb_private::ScriptInterpreterPythonImpl.
Definition at line 35 of file ScriptInterpreter.cpp.
References lldb_private::CommandReturnObject::AppendError().
CollectDataForWatchpointCommandCallback()
void ScriptInterpreter::CollectDataForWatchpointCommandCallback (WatchpointOptions * wp_options, CommandReturnObject & result) virtual
Reimplemented in lldb_private::ScriptInterpreterLua, and lldb_private::ScriptInterpreterPythonImpl.
Definition at line 42 of file ScriptInterpreter.cpp.
References lldb_private::CommandReturnObject::AppendError().
CreateFrameRecognizer()
virtual StructuredData::GenericSP lldb_private::ScriptInterpreter::CreateFrameRecognizer (const char * class_name) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 252 of file ScriptInterpreter.h.
CreateOperatingSystemInterface()
virtual lldb::OperatingSystemInterfaceSP lldb_private::ScriptInterpreter::CreateOperatingSystemInterface () inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 553 of file ScriptInterpreter.h.
CreateScriptCommandObject()
virtual StructuredData::GenericSP lldb_private::ScriptInterpreter::CreateScriptCommandObject (const char * class_name) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 247 of file ScriptInterpreter.h.
Referenced by CommandObjectCommandsScriptAdd::DoExecute().
CreateScriptedBreakpointInterface()
virtual lldb::ScriptedBreakpointInterfaceSP lldb_private::ScriptInterpreter::CreateScriptedBreakpointInterface () inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 566 of file ScriptInterpreter.h.
Referenced by lldb_private::BreakpointResolverScripted::CreateImplementationIfNeeded().
CreateScriptedFrameInterface()
virtual lldb::ScriptedFrameInterfaceSP lldb_private::ScriptInterpreter::CreateScriptedFrameInterface () inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 539 of file ScriptInterpreter.h.
Referenced by lldb_private::ScriptedFrame::Create().
CreateScriptedFrameProviderInterface()
virtual lldb::ScriptedFrameProviderInterfaceSP lldb_private::ScriptInterpreter::CreateScriptedFrameProviderInterface () inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 544 of file ScriptInterpreter.h.
Referenced by lldb_private::ScriptedFrameProvider::CreateInstance(), and CommandObjectTargetFrameProviderRegister::DoExecute().
CreateScriptedProcessInterface()
virtual lldb::ScriptedProcessInterfaceUP lldb_private::ScriptInterpreter::CreateScriptedProcessInterface () inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 531 of file ScriptInterpreter.h.
Referenced by lldb_private::ScriptedProcess::ScriptedProcess().
CreateScriptedStopHookInterface()
virtual lldb::ScriptedStopHookInterfaceSP lldb_private::ScriptInterpreter::CreateScriptedStopHookInterface () inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 561 of file ScriptInterpreter.h.
Referenced by lldb_private::Target::StopHookScripted::SetScriptCallback().
CreateScriptedThreadInterface()
virtual lldb::ScriptedThreadInterfaceSP lldb_private::ScriptInterpreter::CreateScriptedThreadInterface () inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 535 of file ScriptInterpreter.h.
CreateScriptedThreadPlanInterface()
virtual lldb::ScriptedThreadPlanInterfaceSP lldb_private::ScriptInterpreter::CreateScriptedThreadPlanInterface () inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 549 of file ScriptInterpreter.h.
Referenced by lldb_private::ScriptedThreadPlan::ScriptedThreadPlan().
CreateStructuredDataFromScriptObject()
virtual StructuredData::ObjectSP lldb_private::ScriptInterpreter::CreateStructuredDataFromScriptObject (ScriptObject obj) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 571 of file ScriptInterpreter.h.
Referenced by lldb::SBStructuredData::SBStructuredData().
CreateSyntheticScriptedProvider()
virtual StructuredData::ObjectSP lldb_private::ScriptInterpreter::CreateSyntheticScriptedProvider (const char * class_name, lldb::ValueObjectSP valobj) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 241 of file ScriptInterpreter.h.
ExecuteInterpreterLoop()
virtual void lldb_private::ScriptInterpreter::ExecuteInterpreterLoop () pure virtual
Implemented in lldb_private::ScriptInterpreterLua, lldb_private::ScriptInterpreterNone, and lldb_private::ScriptInterpreterPythonImpl.
Referenced by CommandObjectScriptingRun::DoExecute().
ExecuteMultipleLines()
virtual Status lldb_private::ScriptInterpreter::ExecuteMultipleLines (const char * in_string, const ExecuteScriptOptions & options = ExecuteScriptOptions()) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 189 of file ScriptInterpreter.h.
References lldb_private::Status::FromErrorString().
ExecuteOneLine()
virtual bool lldb_private::ScriptInterpreter::ExecuteOneLine (llvm::StringRef command, CommandReturnObject * result, const ExecuteScriptOptions & options = ExecuteScriptOptions()) pure virtual
Implemented in lldb_private::ScriptInterpreterLua, lldb_private::ScriptInterpreterNone, and lldb_private::ScriptInterpreterPythonImpl.
Referenced by CommandObjectScriptingRun::DoExecute().
ExecuteOneLineWithReturn()
virtual bool lldb_private::ScriptInterpreter::ExecuteOneLineWithReturn (llvm::StringRef in_string, ScriptReturnType return_type, void * ret_value, const ExecuteScriptOptions & options = ExecuteScriptOptions()) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 183 of file ScriptInterpreter.h.
ExportFunctionDefinitionToInterpreter()
virtual Status lldb_private::ScriptInterpreter::ExportFunctionDefinitionToInterpreter (StringList & function_def) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 196 of file ScriptInterpreter.h.
References lldb_private::Status::FromErrorString().
FormatterCallbackFunction()
virtual bool lldb_private::ScriptInterpreter::FormatterCallbackFunction (const char * function_name, lldb::TypeImplSP type_impl_sp) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 338 of file ScriptInterpreter.h.
Referenced by lldb_private::TypeMatcher::Matches().
GenerateBreakpointCommandCallbackData()
virtual Status lldb_private::ScriptInterpreter::GenerateBreakpointCommandCallbackData (StringList & input, std::string & output, bool has_extra_args, bool is_callback) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 200 of file ScriptInterpreter.h.
References lldb_private::Status::FromErrorString().
GenerateFunction()
virtual Status lldb_private::ScriptInterpreter::GenerateFunction (const char * signature, const StringList & input, bool is_callback) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 278 of file ScriptInterpreter.h.
References lldb_private::Status::FromErrorString().
GenerateScriptAliasFunction()
virtual bool lldb_private::ScriptInterpreter::GenerateScriptAliasFunction (StringList & input, std::string & output) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 225 of file ScriptInterpreter.h.
Referenced by CommandObjectCommandsScriptAdd::IOHandlerInputComplete().
GenerateTypeScriptFunction() [1/2]
virtual bool lldb_private::ScriptInterpreter::GenerateTypeScriptFunction (const char * oneliner, std::string & output, const void * name_token = nullptr) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 213 of file ScriptInterpreter.h.
Referenced by lldb::SBTypeCategory::AddTypeSummary(), and CommandObjectTypeSummaryAdd::IOHandlerInputComplete().
GenerateTypeScriptFunction() [2/2]
virtual bool lldb_private::ScriptInterpreter::GenerateTypeScriptFunction (StringList & input, std::string & output, const void * name_token = nullptr) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 219 of file ScriptInterpreter.h.
GenerateTypeSynthClass() [1/2]
virtual bool lldb_private::ScriptInterpreter::GenerateTypeSynthClass (const char * oneliner, std::string & output, const void * name_token = nullptr) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 235 of file ScriptInterpreter.h.
GenerateTypeSynthClass() [2/2]
virtual bool lldb_private::ScriptInterpreter::GenerateTypeSynthClass (StringList & input, std::string & output, const void * name_token = nullptr) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 230 of file ScriptInterpreter.h.
Referenced by lldb::SBTypeCategory::AddTypeSynthetic(), and CommandObjectTypeSynthAdd::IOHandlerInputComplete().
GenerateWatchpointCommandCallbackData()
virtual bool lldb_private::ScriptInterpreter::GenerateWatchpointCommandCallbackData (StringList & input, std::string & output, bool is_callback) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 207 of file ScriptInterpreter.h.
GetArgumentsForCommandObject()
virtual StructuredData::ObjectSP lldb_private::ScriptInterpreter::GetArgumentsForCommandObject (StructuredData::GenericSP cmd_obj_sp) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 480 of file ScriptInterpreter.h.
Referenced by CommandObjectScriptingObjectParsed::CommandObjectScriptingObjectParsed().
GetChildAtIndex()
virtual lldb::ValueObjectSP lldb_private::ScriptInterpreter::GetChildAtIndex (const StructuredData::ObjectSP & implementor, uint32_t idx) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 354 of file ScriptInterpreter.h.
GetDataExtractorFromSBData()
lldb::DataExtractorSP ScriptInterpreter::GetDataExtractorFromSBData (const lldb::SBData & data) const
Definition at line 76 of file ScriptInterpreter.cpp.
References lldb::SBData::m_opaque_sp.
GetDocumentationForItem()
virtual bool lldb_private::ScriptInterpreter::GetDocumentationForItem (const char * item, std::string & dest) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 462 of file ScriptInterpreter.h.
Referenced by CommandObjectPythonFunction::GetHelpLong().
GetDynamicSettings()
virtual StructuredData::DictionarySP lldb_private::ScriptInterpreter::GetDynamicSettings (StructuredData::ObjectSP plugin_module_sp, Target * target, const char * setting_name, lldb_private::Status & error) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 273 of file ScriptInterpreter.h.
References error().
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::ParsePythonTargetDefinition().
GetFlagsForCommandObject()
virtual uint32_t lldb_private::ScriptInterpreter::GetFlagsForCommandObject (StructuredData::GenericSP cmd_obj_sp) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 494 of file ScriptInterpreter.h.
Referenced by CommandObjectScriptingObjectParsed::CommandObjectScriptingObjectParsed().
GetIndexOfChildWithName()
virtual llvm::Expected< uint32_t > lldb_private::ScriptInterpreter::GetIndexOfChildWithName (const StructuredData::ObjectSP & implementor, const char * child_name) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 359 of file ScriptInterpreter.h.
GetInterpreterInfo()
StructuredData::DictionarySP ScriptInterpreter::GetInterpreterInfo () virtual
Reimplemented in lldb_private::ScriptInterpreterLua, and lldb_private::ScriptInterpreterPython.
Definition at line 48 of file ScriptInterpreter.cpp.
Referenced by lldb::SBDebugger::GetScriptInterpreterInfo().
GetLanguage()
lldb::ScriptLanguage lldb_private::ScriptInterpreter::GetLanguage () inline
Definition at line 529 of file ScriptInterpreter.h.
References m_script_lang.
Referenced by lldb_private::BreakpointOptions::CreateFromStructuredData().
GetLongHelpForCommandObject()
virtual bool lldb_private::ScriptInterpreter::GetLongHelpForCommandObject (StructuredData::GenericSP cmd_obj_sp, std::string & dest) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 498 of file ScriptInterpreter.h.
Referenced by CommandObjectScriptingObjectParsed::GetHelpLong(), and CommandObjectScriptingObjectRaw::GetHelpLong().
GetMaxPositionalArgumentsForCallable()
virtual llvm::Expected< unsigned > lldb_private::ScriptInterpreter::GetMaxPositionalArgumentsForCallable (const llvm::StringRef & callable_name) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 520 of file ScriptInterpreter.h.
GetOpaqueTypeFromSBAttachInfo()
lldb::ProcessAttachInfoSP ScriptInterpreter::GetOpaqueTypeFromSBAttachInfo (const lldb::SBAttachInfo & attach_info) const
Definition at line 91 of file ScriptInterpreter.cpp.
References lldb::SBAttachInfo::m_opaque_sp.
GetOpaqueTypeFromSBBreakpoint()
lldb::BreakpointSP ScriptInterpreter::GetOpaqueTypeFromSBBreakpoint (const lldb::SBBreakpoint & breakpoint) const
Definition at line 80 of file ScriptInterpreter.cpp.
References lldb::SBBreakpoint::m_opaque_wp.
GetOpaqueTypeFromSBBreakpointLocation()
lldb::BreakpointLocationSP ScriptInterpreter::GetOpaqueTypeFromSBBreakpointLocation (const lldb::SBBreakpointLocation & break_loc) const
Definition at line 86 of file ScriptInterpreter.cpp.
References lldb::SBBreakpointLocation::m_opaque_wp.
GetOpaqueTypeFromSBEvent()
Event * ScriptInterpreter::GetOpaqueTypeFromSBEvent (const lldb::SBEvent & event) const
Definition at line 125 of file ScriptInterpreter.cpp.
GetOpaqueTypeFromSBExecutionContext()
lldb::ExecutionContextRefSP ScriptInterpreter::GetOpaqueTypeFromSBExecutionContext (const lldb::SBExecutionContext & exe_ctx) const
Definition at line 156 of file ScriptInterpreter.cpp.
References lldb::SBExecutionContext::m_exe_ctx_sp.
GetOpaqueTypeFromSBFrame()
lldb::StackFrameSP ScriptInterpreter::GetOpaqueTypeFromSBFrame (const lldb::SBFrame & frame) const
Definition at line 118 of file ScriptInterpreter.cpp.
References lldb::SBFrame::m_opaque_sp.
GetOpaqueTypeFromSBFrameList()
lldb::StackFrameListSP ScriptInterpreter::GetOpaqueTypeFromSBFrameList (const lldb::SBFrameList & exe_ctx) const
Definition at line 161 of file ScriptInterpreter.cpp.
References lldb::SBFrameList::m_opaque_sp.
GetOpaqueTypeFromSBLaunchInfo()
lldb::ProcessLaunchInfoSP ScriptInterpreter::GetOpaqueTypeFromSBLaunchInfo (const lldb::SBLaunchInfo & launch_info) const
Definition at line 96 of file ScriptInterpreter.cpp.
References lldb::SBLaunchInfo::m_opaque_sp.
GetOpaqueTypeFromSBMemoryRegionInfo()
std::optional< lldb_private::MemoryRegionInfo > ScriptInterpreter::GetOpaqueTypeFromSBMemoryRegionInfo (const lldb::SBMemoryRegionInfo & mem_region) const
Definition at line 148 of file ScriptInterpreter.cpp.
References lldb::SBMemoryRegionInfo::m_opaque_up.
GetOpaqueTypeFromSBStream()
lldb::StreamSP ScriptInterpreter::GetOpaqueTypeFromSBStream (const lldb::SBStream & stream) const
Definition at line 129 of file ScriptInterpreter.cpp.
References lldb::SBStream::m_opaque_up.
GetOpaqueTypeFromSBSymbolContext()
SymbolContext ScriptInterpreter::GetOpaqueTypeFromSBSymbolContext (const lldb::SBSymbolContext & sym_ctx) const
Definition at line 140 of file ScriptInterpreter.cpp.
References lldb::SBSymbolContext::m_opaque_up.
GetOpaqueTypeFromSBThread()
lldb::ThreadSP ScriptInterpreter::GetOpaqueTypeFromSBThread (const lldb::SBThread & exe_ctx) const
Definition at line 110 of file ScriptInterpreter.cpp.
GetOpaqueTypeFromSBValue()
lldb::ValueObjectSP ScriptInterpreter::GetOpaqueTypeFromSBValue (const lldb::SBValue & value) const
Definition at line 167 of file ScriptInterpreter.cpp.
References lldb_private::ValueLocker::GetLockedSP(), and lldb::SBValue::m_opaque_sp.
GetOptionsForCommandObject()
virtual StructuredData::ObjectSP lldb_private::ScriptInterpreter::GetOptionsForCommandObject (StructuredData::GenericSP cmd_obj_sp) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 475 of file ScriptInterpreter.h.
Referenced by CommandObjectScriptingObjectParsed::CommandObjectScriptingObjectParsed().
GetRecognizedArguments()
virtual lldb::ValueObjectListSP lldb_private::ScriptInterpreter::GetRecognizedArguments (const StructuredData::ObjectSP & implementor, lldb::StackFrameSP frame_sp) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 256 of file ScriptInterpreter.h.
GetRepeatCommandForScriptedCommand()
virtual std::optional< std::string > lldb_private::ScriptInterpreter::GetRepeatCommandForScriptedCommand (StructuredData::GenericSP impl_obj_sp, Args & args) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 410 of file ScriptInterpreter.h.
Referenced by CommandObjectScriptingObjectParsed::GetRepeatCommand(), and CommandObjectScriptingObjectRaw::GetRepeatCommand().
GetScriptedPlatformInterface()
virtual lldb::ScriptedPlatformInterfaceUP lldb_private::ScriptInterpreter::GetScriptedPlatformInterface () inline virtual
Definition at line 557 of file ScriptInterpreter.h.
GetScriptedSummary()
virtual bool lldb_private::ScriptInterpreter::GetScriptedSummary (const char * function_name, lldb::ValueObjectSP valobj, StructuredData::ObjectSP & callee_wrapper_sp, const TypeSummaryOptions & options, std::string & retval) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 327 of file ScriptInterpreter.h.
Referenced by lldb_private::ScriptSummaryFormat::FormatObject().
GetScriptInterpreterPtyName()
const char * lldb_private::ScriptInterpreter::GetScriptInterpreterPtyName ()
GetShortHelpForCommandObject()
virtual bool lldb_private::ScriptInterpreter::GetShortHelpForCommandObject (StructuredData::GenericSP cmd_obj_sp, std::string & dest) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 468 of file ScriptInterpreter.h.
Referenced by CommandObjectScriptingObjectParsed::GetHelp(), and CommandObjectScriptingObjectRaw::GetHelp().
GetStatusFromSBError()
Status ScriptInterpreter::GetStatusFromSBError (const lldb::SBError & error) const
Definition at line 103 of file ScriptInterpreter.cpp.
References error(), and lldb_private::Status.
GetSyntheticTypeName()
virtual ConstString lldb_private::ScriptInterpreter::GetSyntheticTypeName (const StructuredData::ObjectSP & implementor) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 380 of file ScriptInterpreter.h.
GetSyntheticValue()
virtual lldb::ValueObjectSP lldb_private::ScriptInterpreter::GetSyntheticValue (const StructuredData::ObjectSP & implementor) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 375 of file ScriptInterpreter.h.
HandleArgumentCompletionForScriptedCommand()
virtual StructuredData::DictionarySP lldb_private::ScriptInterpreter::HandleArgumentCompletionForScriptedCommand (StructuredData::GenericSP impl_obj_sp, std::vector< llvm::StringRef > & args, size_t args_pos, size_t char_in_arg) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 416 of file ScriptInterpreter.h.
Referenced by CommandObjectScriptingObjectParsed::HandleArgumentCompletion().
HandleOptionArgumentCompletionForScriptedCommand()
virtual StructuredData::DictionarySP lldb_private::ScriptInterpreter::HandleOptionArgumentCompletionForScriptedCommand (StructuredData::GenericSP impl_obj_sp, llvm::StringRef & long_name, size_t char_in_arg) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 423 of file ScriptInterpreter.h.
Referenced by CommandObjectScriptingObjectParsed::CommandOptions::HandleOptionArgumentCompletion().
Interrupt()
virtual bool lldb_private::ScriptInterpreter::Interrupt () inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 175 of file ScriptInterpreter.h.
Referenced by lldb_private::CommandInterpreter::IOHandlerInterrupt().
IsReservedWord()
virtual bool lldb_private::ScriptInterpreter::IsReservedWord (const char * word) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 513 of file ScriptInterpreter.h.
Referenced by LocateExecutableScriptingResourcesFromDSYM().
LanguageToString()
std::string ScriptInterpreter::LanguageToString (lldb::ScriptLanguage language) static
Definition at line 61 of file ScriptInterpreter.cpp.
References lldb::eScriptLanguageLua, lldb::eScriptLanguageNone, lldb::eScriptLanguagePython, and lldb::eScriptLanguageUnknown.
Referenced by lldb_private::BreakpointOptions::CreateFromStructuredData(), CommandObjectScriptingExtensionList::DoExecute(), lldb_private::BreakpointOptions::CommandBaton::GetDescription(), lldb_private::BreakpointOptions::CommandData::SerializeToStructuredData(), and StringToLanguage().
LoadPluginModule()
virtual StructuredData::ObjectSP lldb_private::ScriptInterpreter::LoadPluginModule (const FileSpec & file_spec, lldb_private::Status & error) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 268 of file ScriptInterpreter.h.
References error().
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::ParsePythonTargetDefinition().
LoadScriptingModule()
bool ScriptInterpreter::LoadScriptingModule (const char * filename, const LoadScriptOptions & options, lldb_private::Status & error, StructuredData::ObjectSP * module_sp = nullptr, FileSpec extra_search_dir = {}, lldb::TargetSP loaded_into_target_sp = {}) virtual
Reimplemented in lldb_private::ScriptInterpreterLua, and lldb_private::ScriptInterpreterPythonImpl.
Definition at line 52 of file ScriptInterpreter.cpp.
References error(), and lldb_private::Status::FromErrorString().
Referenced by lldb_private::Module::LoadScriptingResourceInTarget().
MightHaveChildrenSynthProviderInstance()
virtual bool lldb_private::ScriptInterpreter::MightHaveChildrenSynthProviderInstance (const StructuredData::ObjectSP & implementor) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 369 of file ScriptInterpreter.h.
OptionParsingStartedForCommandObject()
virtual void lldb_private::ScriptInterpreter::OptionParsingStartedForCommandObject (StructuredData::GenericSP cmd_obj_sp) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 491 of file ScriptInterpreter.h.
Referenced by CommandObjectScriptingObjectParsed::CommandOptions::OptionParsingStarting().
RunScriptBasedCommand() [1/2]
virtual bool lldb_private::ScriptInterpreter::RunScriptBasedCommand (const char * impl_function, llvm::StringRef args, ScriptedCommandSynchronicity synchronicity, lldb_private::CommandReturnObject & cmd_retobj, Status & error, const lldb_private::ExecutionContext & exe_ctx) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 385 of file ScriptInterpreter.h.
References error().
Referenced by CommandObjectPythonFunction::DoExecute(), and CommandObjectScriptingObjectRaw::DoExecute().
RunScriptBasedCommand() [2/2]
virtual bool lldb_private::ScriptInterpreter::RunScriptBasedCommand (StructuredData::GenericSP impl_obj_sp, llvm::StringRef args, ScriptedCommandSynchronicity synchronicity, lldb_private::CommandReturnObject & cmd_retobj, Status & error, const lldb_private::ExecutionContext & exe_ctx) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 393 of file ScriptInterpreter.h.
References error().
RunScriptBasedParsedCommand()
virtual bool lldb_private::ScriptInterpreter::RunScriptBasedParsedCommand (StructuredData::GenericSP impl_obj_sp, Args & args, ScriptedCommandSynchronicity synchronicity, lldb_private::CommandReturnObject & cmd_retobj, Status & error, const lldb_private::ExecutionContext & exe_ctx) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 401 of file ScriptInterpreter.h.
References error().
Referenced by CommandObjectScriptingObjectParsed::DoExecute().
RunScriptFormatKeyword() [1/5]
virtual bool lldb_private::ScriptInterpreter::RunScriptFormatKeyword (const char * impl_function, Process * process, std::string & output, Status & error) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 429 of file ScriptInterpreter.h.
References error(), and lldb_private::Status::FromErrorString().
Referenced by RunScriptFormatKeyword().
RunScriptFormatKeyword() [2/5]
virtual bool lldb_private::ScriptInterpreter::RunScriptFormatKeyword (const char * impl_function, StackFrame * frame, std::string & output, Status & error) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 448 of file ScriptInterpreter.h.
References error(), and lldb_private::Status::FromErrorString().
RunScriptFormatKeyword() [3/5]
virtual bool lldb_private::ScriptInterpreter::RunScriptFormatKeyword (const char * impl_function, Target * target, std::string & output, Status & error) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 442 of file ScriptInterpreter.h.
References error(), and lldb_private::Status::FromErrorString().
RunScriptFormatKeyword() [4/5]
virtual bool lldb_private::ScriptInterpreter::RunScriptFormatKeyword (const char * impl_function, Thread * thread, std::string & output, Status & error) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 436 of file ScriptInterpreter.h.
References error(), and lldb_private::Status::FromErrorString().
RunScriptFormatKeyword() [5/5]
virtual bool lldb_private::ScriptInterpreter::RunScriptFormatKeyword (const char * impl_function, ValueObject * value, std::string & output, Status & error) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 455 of file ScriptInterpreter.h.
References error(), and lldb_private::Status::FromErrorString().
SetBreakpointCommandCallback() [1/3]
virtual Status lldb_private::ScriptInterpreter::SetBreakpointCommandCallback (BreakpointOptions & bp_options, const char * callback_text, bool is_callback) inline virtual
Reimplemented in lldb_private::ScriptInterpreterLua, and lldb_private::ScriptInterpreterPythonImpl.
Definition at line 297 of file ScriptInterpreter.h.
References lldb_private::Status::FromErrorString().
SetBreakpointCommandCallback() [2/3]
virtual Status lldb_private::ScriptInterpreter::SetBreakpointCommandCallback (BreakpointOptions & bp_options, std::unique_ptr< BreakpointOptions::CommandData > & data_up) inline virtual
This one is for deserialization:
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 304 of file ScriptInterpreter.h.
References lldb_private::Status::FromErrorString().
SetBreakpointCommandCallback() [3/3]
Status ScriptInterpreter::SetBreakpointCommandCallback (std::vector< std::reference_wrapper< BreakpointOptions > > & bp_options_vec, const char * callback_text)
Set the specified text as the callback for the breakpoint.
Definition at line 186 of file ScriptInterpreter.cpp.
References error(), and SetBreakpointCommandCallback().
Referenced by lldb_private::BreakpointOptions::CreateFromStructuredData(), and SetBreakpointCommandCallback().
SetBreakpointCommandCallbackFunction() [1/2]
virtual Status lldb_private::ScriptInterpreter::SetBreakpointCommandCallbackFunction (BreakpointOptions & bp_options, const char * function_name, StructuredData::ObjectSP extra_args_sp) inline virtual
Set a script function as the callback for the breakpoint.
Reimplemented in lldb_private::ScriptInterpreterLua, and lldb_private::ScriptInterpreterPythonImpl.
Definition at line 316 of file ScriptInterpreter.h.
References lldb_private::Status::FromErrorString().
SetBreakpointCommandCallbackFunction() [2/2]
Status ScriptInterpreter::SetBreakpointCommandCallbackFunction (std::vector< std::reference_wrapper< BreakpointOptions > > & bp_options_vec, const char * function_name, StructuredData::ObjectSP extra_args_sp)
Definition at line 199 of file ScriptInterpreter.cpp.
References error(), and SetBreakpointCommandCallbackFunction().
Referenced by SetBreakpointCommandCallbackFunction().
SetOptionValueForCommandObject()
virtual bool lldb_private::ScriptInterpreter::SetOptionValueForCommandObject (StructuredData::GenericSP cmd_obj_sp, ExecutionContext * exe_ctx, llvm::StringRef long_option, llvm::StringRef value) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 484 of file ScriptInterpreter.h.
Referenced by CommandObjectScriptingObjectParsed::CommandOptions::SetOptionValue().
SetWatchpointCommandCallback()
virtual void lldb_private::ScriptInterpreter::SetWatchpointCommandCallback (WatchpointOptions * wp_options, const char * user_input, bool is_callback) inline virtual
Set a one-liner as the callback for the watchpoint.
Reimplemented in lldb_private::ScriptInterpreterLua, and lldb_private::ScriptInterpreterPythonImpl.
Definition at line 323 of file ScriptInterpreter.h.
ShouldHide()
virtual bool lldb_private::ScriptInterpreter::ShouldHide (const StructuredData::ObjectSP & implementor, lldb::StackFrameSP frame_sp) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 262 of file ScriptInterpreter.h.
StringToLanguage()
lldb::ScriptLanguage ScriptInterpreter::StringToLanguage (const llvm::StringRef & string) static
Definition at line 176 of file ScriptInterpreter.cpp.
References lldb::eScriptLanguageLua, lldb::eScriptLanguageNone, lldb::eScriptLanguagePython, lldb::eScriptLanguageUnknown, and LanguageToString().
Referenced by lldb_private::BreakpointOptions::CommandData::CreateFromStructuredData().
UpdateSynthProviderInstance()
virtual bool lldb_private::ScriptInterpreter::UpdateSynthProviderInstance (const StructuredData::ObjectSP & implementor) inline virtual
Reimplemented in lldb_private::ScriptInterpreterPythonImpl.
Definition at line 365 of file ScriptInterpreter.h.
Member Data Documentation
m_debugger
Debugger& lldb_private::ScriptInterpreter::m_debugger protected
Definition at line 616 of file ScriptInterpreter.h.
Referenced by lldb_private::ScriptInterpreterLua::CollectDataForBreakpointCommandCallback(), lldb_private::ScriptInterpreterLua::CollectDataForWatchpointCommandCallback(), lldb_private::ScriptInterpreterPythonImpl::CollectDataForWatchpointCommandCallback(), lldb_private::ScriptInterpreterLua::ExecuteInterpreterLoop(), lldb_private::ScriptInterpreterNone::ExecuteInterpreterLoop(), lldb_private::ScriptInterpreterLua::ExecuteOneLine(), lldb_private::ScriptInterpreterNone::ExecuteOneLine(), ScriptInterpreter(), lldb_private::ScriptInterpreterPythonImpl::ScriptInterpreterPythonImpl(), and lldb_private::ScriptInterpreterPythonImpl::SetBreakpointCommandCallbackFunction().
m_script_lang
lldb::ScriptLanguage lldb_private::ScriptInterpreter::m_script_lang protected
Definition at line 617 of file ScriptInterpreter.h.
Referenced by GetLanguage(), and ScriptInterpreter().
The documentation for this class was generated from the following files:
ScriptInterpreter.h
ScriptInterpreter.cpp