LLDB: lldb_private::TypeListImpl Class Reference
lldb_private::TypeListImpl Class Reference
#include <Type.h>
Classes
class AppendVisitor
Public Member Functions
TypeListImpl ()=default
void Append (const lldb::TypeImplSP &type)
void Append (const lldb_private::TypeList &type_list)
lldb::TypeImplSP GetTypeAtIndex (size_t idx)
size_t GetSize ()
Private Attributes
std::vector< lldb::TypeImplSP > m_content
Detailed Description
Definition at line 697 of file Type.h.
Constructor & Destructor Documentation
TypeListImpl()
lldb_private::TypeListImpl::TypeListImpl () default
Referenced by lldb_private::TypeListImpl::AppendVisitor::AppendVisitor().
Member Function Documentation
Append() [1/2]
void lldb_private::TypeListImpl::Append (const lldb::TypeImplSP & type) inline
Definition at line 701 of file Type.h.
References m_content.
Append() [2/2]
void TypeListImpl::Append (const lldb_private::TypeList & type_list)
Definition at line 258 of file Type.cpp.
References lldb_private::TypeList::ForEach().
GetSize()
size_t lldb_private::TypeListImpl::GetSize () inline
Definition at line 722 of file Type.h.
References m_content.
Referenced by GetTypeAtIndex().
GetTypeAtIndex()
lldb::TypeImplSP lldb_private::TypeListImpl::GetTypeAtIndex (size_t idx) inline
Definition at line 715 of file Type.h.
References GetSize(), and m_content.
Member Data Documentation
m_content
std::vector<lldb::TypeImplSP> lldb_private::TypeListImpl::m_content private
Definition at line 725 of file Type.h.
Referenced by Append(), GetSize(), and GetTypeAtIndex().
The documentation for this class was generated from the following files:
Type.h
Type.cpp