LLDB: lldb::SBEvent Class Reference
lldb::SBEvent Class Reference
#include <SBEvent.h>
Public Member Functions
SBEvent ()
SBEvent (const lldb::SBEvent &rhs)
SBEvent (uint32_t event, const char *cstr, uint32_t cstr_len)
~SBEvent ()
const SBEvent & operator= (const lldb::SBEvent &rhs)
operator bool () const
bool IsValid () const
const char * GetDataFlavor ()
uint32_t GetType () const
lldb::SBBroadcaster GetBroadcaster () const
const char * GetBroadcasterClass () const
bool BroadcasterMatchesPtr (const lldb::SBBroadcaster *broadcaster)
bool BroadcasterMatchesRef (const lldb::SBBroadcaster &broadcaster)
void Clear ()
bool GetDescription (lldb::SBStream &description)
bool GetDescription (lldb::SBStream &description) const
Static Public Member Functions
static const char * GetCStringFromEvent (const lldb::SBEvent &event)
Protected Member Functions
SBEvent (lldb::EventSP &event_sp)
SBEvent (lldb_private::Event *event)
lldb::EventSP & GetSP () const
void reset (lldb::EventSP &event_sp)
void reset (lldb_private::Event *event)
lldb_private::Event * get () const
Private Attributes
lldb::EventSP m_event_sp
lldb_private::Event * m_opaque_ptr = nullptr
Friends
class SBListener
class SBBroadcaster
class SBBreakpoint
class SBDebugger
class SBProcess
class SBTarget
class SBThread
class SBWatchpoint
class lldb_private::ScriptInterpreter
class lldb_private::python::SWIGBridge
Detailed Description
Definition at line 28 of file SBEvent.h.
Constructor & Destructor Documentation
SBEvent() [1/5]
SBEvent::SBEvent ()
Definition at line 24 of file SBEvent.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by GetCStringFromEvent(), lldb_private::python::SWIGBridge, operator=(), SBEvent(), and ~SBEvent().
SBEvent() [2/5]
SBEvent::SBEvent (const lldb::SBEvent & rhs)
Definition at line 42 of file SBEvent.cpp.
References LLDB_INSTRUMENT_VA, m_event_sp, m_opaque_ptr, and SBEvent().
SBEvent() [3/5]
SBEvent::SBEvent (uint32_t event, const char * cstr, uint32_t cstr_len)
Definition at line 26 of file SBEvent.cpp.
References get(), LLDB_INSTRUMENT_VA, m_event_sp, and m_opaque_ptr.
~SBEvent()
SBEvent::~SBEvent () default
References BroadcasterMatchesPtr(), BroadcasterMatchesRef(), Clear(), GetBroadcaster(), GetBroadcasterClass(), GetCStringFromEvent(), GetDataFlavor(), GetDescription(), GetType(), IsValid(), operator=(), and SBEvent().
SBEvent() [4/5]
SBEvent::SBEvent (lldb::EventSP & event_sp) protected
Definition at line 33 of file SBEvent.cpp.
References get(), LLDB_INSTRUMENT_VA, m_event_sp, and m_opaque_ptr.
SBEvent() [5/5]
SBEvent::SBEvent (lldb_private::Event * event) protected
Definition at line 38 of file SBEvent.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
Member Function Documentation
BroadcasterMatchesPtr()
bool SBEvent::BroadcasterMatchesPtr (const lldb::SBBroadcaster * broadcaster)
Definition at line 104 of file SBEvent.cpp.
References BroadcasterMatchesRef(), LLDB_INSTRUMENT_VA, and SBBroadcaster.
Referenced by ~SBEvent().
BroadcasterMatchesRef()
bool SBEvent::BroadcasterMatchesRef (const lldb::SBBroadcaster & broadcaster)
Definition at line 112 of file SBEvent.cpp.
References lldb_private::Event::BroadcasterIs(), lldb::SBBroadcaster::get(), get(), LLDB_INSTRUMENT_VA, and SBBroadcaster.
Referenced by BroadcasterMatchesPtr(), and ~SBEvent().
Clear()
void SBEvent::Clear ()
Definition at line 124 of file SBEvent.cpp.
References lldb_private::Event::Clear(), get(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBEvent().
get()
Event * SBEvent::get () const protected
Definition at line 134 of file SBEvent.cpp.
References m_event_sp, and m_opaque_ptr.
Referenced by BroadcasterMatchesRef(), Clear(), lldb::SBBreakpoint::EventIsBreakpointEvent(), lldb::SBProcess::EventIsProcessEvent(), lldb::SBTarget::EventIsTargetEvent(), lldb::SBThread::EventIsThreadEvent(), lldb::SBWatchpoint::EventIsWatchpointEvent(), GetBroadcaster(), GetBroadcasterClass(), lldb::SBTarget::GetCreatedTargetFromEvent(), GetCStringFromEvent(), GetDataFlavor(), GetDescription(), GetDescription(), lldb::SBDebugger::GetDiagnosticFromEvent(), lldb::SBProcess::GetInterruptedFromEvent(), lldb::SBTarget::GetModuleAtIndexFromEvent(), lldb::SBTarget::GetNumModulesFromEvent(), lldb::SBProcess::GetNumRestartedReasonsFromEvent(), lldb::SBProcess::GetProcessFromEvent(), lldb::SBDebugger::GetProgressDataFromEvent(), lldb::SBDebugger::GetProgressFromEvent(), lldb::SBProcess::GetRestartedFromEvent(), lldb::SBProcess::GetRestartedReasonAtIndexFromEvent(), lldb::SBThread::GetStackFrameFromEvent(), lldb::SBProcess::GetStateFromEvent(), lldb::SBTarget::GetTargetFromEvent(), lldb::SBThread::GetThreadFromEvent(), GetType(), lldb_private::python::SWIGBridge, operator bool(), SBEvent(), and SBEvent().
GetBroadcaster()
SBBroadcaster SBEvent::GetBroadcaster () const
Definition at line 83 of file SBEvent.cpp.
References get(), lldb_private::Event::GetBroadcaster(), LLDB_INSTRUMENT_VA, lldb::SBBroadcaster::reset(), and SBBroadcaster.
Referenced by ~SBEvent().
GetBroadcasterClass()
const char * SBEvent::GetBroadcasterClass () const
Definition at line 93 of file SBEvent.cpp.
References lldb_private::ConstString::AsCString(), get(), lldb_private::Event::GetBroadcaster(), lldb_private::Broadcaster::GetBroadcasterClass(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBEvent().
GetCStringFromEvent()
const char * SBEvent::GetCStringFromEvent (const lldb::SBEvent & event) static
Definition at line 167 of file SBEvent.cpp.
References get(), lldb_private::EventDataBytes::GetBytesFromEvent(), lldb_private::ConstString::GetCString(), LLDB_INSTRUMENT_VA, and SBEvent().
Referenced by ~SBEvent().
GetDataFlavor()
const char * SBEvent::GetDataFlavor ()
Definition at line 59 of file SBEvent.cpp.
References get(), lldb_private::ConstString::GetCString(), lldb_private::Event::GetData(), lldb_private::EventData::GetFlavor(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBEvent().
GetDescription() [1/2]
bool SBEvent::GetDescription (lldb::SBStream & description)
Definition at line 175 of file SBEvent.cpp.
References get(), LLDB_INSTRUMENT_VA, m_opaque_ptr, lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
Referenced by ~SBEvent().
GetDescription() [2/2]
bool SBEvent::GetDescription (lldb::SBStream & description) const
Definition at line 188 of file SBEvent.cpp.
References get(), LLDB_INSTRUMENT_VA, m_opaque_ptr, lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
GetSP()
EventSP & SBEvent::GetSP () const protected
Definition at line 132 of file SBEvent.cpp.
References m_event_sp.
Referenced by lldb::SBBreakpoint::GetBreakpointEventTypeFromEvent(), lldb::SBBreakpoint::GetBreakpointFromEvent(), lldb::SBBreakpoint::GetBreakpointLocationAtIndexFromEvent(), lldb::SBBreakpoint::GetNumBreakpointLocationsFromEvent(), lldb::SBProcess::GetStructuredDataFromEvent(), lldb::SBWatchpoint::GetWatchpointEventTypeFromEvent(), lldb::SBWatchpoint::GetWatchpointFromEvent(), lldb::SBListener::HandleBroadcastEvent(), and lldb_private::python::SWIGBridge.
GetType()
uint32_t SBEvent::GetType () const
Definition at line 71 of file SBEvent.cpp.
References get(), lldb_private::Event::GetType(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBEvent().
IsValid()
bool SBEvent::IsValid () const
Definition at line 155 of file SBEvent.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBBreakpoint::GetBreakpointEventTypeFromEvent(), lldb::SBBreakpoint::GetBreakpointFromEvent(), lldb::SBBreakpoint::GetBreakpointLocationAtIndexFromEvent(), lldb::SBBreakpoint::GetNumBreakpointLocationsFromEvent(), lldb::SBWatchpoint::GetWatchpointEventTypeFromEvent(), lldb::SBWatchpoint::GetWatchpointFromEvent(), and ~SBEvent().
operator bool()
SBEvent::operator bool () const explicit
Definition at line 159 of file SBEvent.cpp.
References get(), and LLDB_INSTRUMENT_VA.
operator=()
const SBEvent & SBEvent::operator= (const lldb::SBEvent & rhs)
Definition at line 47 of file SBEvent.cpp.
References LLDB_INSTRUMENT_VA, m_event_sp, m_opaque_ptr, and SBEvent().
Referenced by ~SBEvent().
reset() [1/2]
void SBEvent::reset (lldb::EventSP & event_sp) protected
Definition at line 145 of file SBEvent.cpp.
References m_event_sp, and m_opaque_ptr.
Referenced by lldb::SBProcess::GetStopEventForStopID(), and lldb_private::python::SWIGBridge.
reset() [2/2]
void SBEvent::reset (lldb_private::Event * event) protected
Definition at line 150 of file SBEvent.cpp.
References m_event_sp, and m_opaque_ptr.
Friends And Related Symbol Documentation
lldb_private::python::SWIGBridge
friend class lldb_private::python::SWIGBridge friend
Definition at line 78 of file SBEvent.h.
References get(), GetSP(), reset(), and SBEvent().
lldb_private::ScriptInterpreter
friend class lldb_private::ScriptInterpreter friend
Definition at line 77 of file SBEvent.h.
SBBreakpoint
friend class SBBreakpoint friend
Definition at line 70 of file SBEvent.h.
References SBBreakpoint.
Referenced by SBBreakpoint.
SBBroadcaster
friend class SBBroadcaster friend
Definition at line 69 of file SBEvent.h.
References SBBroadcaster.
Referenced by BroadcasterMatchesPtr(), BroadcasterMatchesRef(), GetBroadcaster(), and SBBroadcaster.
SBDebugger
friend class SBDebugger friend
Definition at line 71 of file SBEvent.h.
References SBDebugger.
Referenced by SBDebugger.
SBListener
friend class SBListener friend
Definition at line 68 of file SBEvent.h.
References SBListener.
Referenced by SBListener.
SBProcess
friend class SBProcess friend
Definition at line 72 of file SBEvent.h.
References SBProcess.
Referenced by SBProcess.
SBTarget
friend class SBTarget friend
Definition at line 73 of file SBEvent.h.
References SBTarget.
Referenced by SBTarget.
SBThread
friend class SBThread friend
Definition at line 74 of file SBEvent.h.
References SBThread.
Referenced by SBThread.
SBWatchpoint
friend class SBWatchpoint friend
Definition at line 75 of file SBEvent.h.
References SBWatchpoint.
Referenced by SBWatchpoint.
Member Data Documentation
m_event_sp
lldb::EventSP lldb::SBEvent::m_event_sp mutable private
Definition at line 93 of file SBEvent.h.
Referenced by get(), GetSP(), operator=(), reset(), reset(), SBEvent(), SBEvent(), and SBEvent().
m_opaque_ptr
lldb_private::Event* lldb::SBEvent::m_opaque_ptr = nullptr mutable private
Definition at line 94 of file SBEvent.h.
Referenced by get(), GetDescription(), GetDescription(), operator=(), reset(), reset(), SBEvent(), SBEvent(), SBEvent(), and SBEvent().
The documentation for this class was generated from the following files:
SBEvent.h
SBEvent.cpp