LLDB: NSIndexPathSyntheticFrontEnd Class Reference
NSIndexPathSyntheticFrontEnd Class Reference
Classes
struct Impl
Public Member Functions
NSIndexPathSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
~NSIndexPathSyntheticFrontEnd () override=default
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
bool MightHaveChildren () override
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
lldb::ValueObjectSP GetSyntheticValue () override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual ConstString GetSyntheticTypeName ()
Protected Types
enum class Mode { Inlined , Outsourced , Invalid }
Protected Attributes
ObjCLanguageRuntime::ClassDescriptorSP m_descriptor_sp
struct NSIndexPathSyntheticFrontEnd::Impl m_impl
uint32_t m_ptr_size = 0
CompilerType m_uint_star_type
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Detailed Description
Definition at line 32 of file NSIndexPath.cpp.
Member Enumeration Documentation
Mode
enum class NSIndexPathSyntheticFrontEnd::Mode strong protected
Enumerator
Inlined
Outsourced
Invalid
Definition at line 147 of file NSIndexPath.cpp.
Constructor & Destructor Documentation
NSIndexPathSyntheticFrontEnd()
NSIndexPathSyntheticFrontEnd::NSIndexPathSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp) inline
Definition at line 34 of file NSIndexPath.cpp.
References lldb_private::SyntheticChildrenFrontEnd::m_backend, m_descriptor_sp, m_impl, m_ptr_size, m_uint_star_type, and lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd().
~NSIndexPathSyntheticFrontEnd()
NSIndexPathSyntheticFrontEnd::~NSIndexPathSyntheticFrontEnd () override default
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > NSIndexPathSyntheticFrontEnd::CalculateNumChildren () inline override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 43 of file NSIndexPath.cpp.
References m_impl.
GetChildAtIndex()
lldb::ValueObjectSP NSIndexPathSyntheticFrontEnd::GetChildAtIndex (uint32_t idx) inline override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 47 of file NSIndexPath.cpp.
References m_impl, and m_uint_star_type.
GetIndexOfChildWithName()
llvm::Expected< size_t > NSIndexPathSyntheticFrontEnd::GetIndexOfChildWithName (ConstString name) inline override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 129 of file NSIndexPath.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::SyntheticChildrenFrontEnd::CalculateNumChildrenIgnoringErrors(), and lldb_private::formatters::ExtractIndexFromString().
GetSyntheticValue()
lldb::ValueObjectSP NSIndexPathSyntheticFrontEnd::GetSyntheticValue () inline override virtual
Reimplemented from lldb_private::SyntheticChildrenFrontEnd.
Definition at line 142 of file NSIndexPath.cpp.
MightHaveChildren()
bool NSIndexPathSyntheticFrontEnd::MightHaveChildren () inline override virtual
Reimplemented from lldb_private::SyntheticChildrenFrontEnd.
Definition at line 127 of file NSIndexPath.cpp.
References Invalid, and m_impl.
Update()
lldb::ChildCacheState NSIndexPathSyntheticFrontEnd::Update () inline override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 51 of file NSIndexPath.cpp.
References lldb::eRefetch, lldb_private::ObjCLanguageRuntime::Get(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), lldb_private::ScratchTypeSystemClang::GetForTarget(), Inlined, lldb_private::SyntheticChildrenFrontEnd::m_backend, m_impl, lldb_private::ObjCLanguageRuntime::ClassDescriptor::iVarDescriptor::m_offset, m_uint_star_type, and Outsourced.
Member Data Documentation
m_descriptor_sp
ObjCLanguageRuntime::ClassDescriptorSP NSIndexPathSyntheticFrontEnd::m_descriptor_sp protected
Definition at line 145 of file NSIndexPath.cpp.
Referenced by NSIndexPathSyntheticFrontEnd().
m_impl
struct NSIndexPathSyntheticFrontEnd::Impl NSIndexPathSyntheticFrontEnd::m_impl protected
Referenced by CalculateNumChildren(), GetChildAtIndex(), MightHaveChildren(), NSIndexPathSyntheticFrontEnd(), and Update().
m_ptr_size
uint32_t NSIndexPathSyntheticFrontEnd::m_ptr_size = 0 protected
Definition at line 310 of file NSIndexPath.cpp.
Referenced by NSIndexPathSyntheticFrontEnd().
m_uint_star_type
CompilerType NSIndexPathSyntheticFrontEnd::m_uint_star_type protected
Definition at line 311 of file NSIndexPath.cpp.
Referenced by GetChildAtIndex(), NSIndexPathSyntheticFrontEnd(), and Update().
The documentation for this class was generated from the following file:
NSIndexPath.cpp