LLDB: lldb_private::SyntheticChildren::Flags Class Reference
lldb_private::SyntheticChildren::Flags Class Reference
#include <TypeSynthetic.h>
Public Member Functions
Flags ()=default
Flags (const Flags &other)
Flags (uint32_t value)
Flags & operator= (const Flags &rhs)
Flags & operator= (const uint32_t &rhs)
Flags & Clear ()
bool GetCascades () const
Flags & SetCascades (bool value=true)
bool GetSkipPointers () const
Flags & SetSkipPointers (bool value=true)
bool GetSkipReferences () const
Flags & SetSkipReferences (bool value=true)
bool GetNonCacheable () const
Flags & SetNonCacheable (bool value=true)
bool GetFrontEndWantsDereference () const
Flags & SetFrontEndWantsDereference (bool value=true)
uint32_t GetValue ()
void SetValue (uint32_t value)
Private Attributes
uint32_t m_flags = lldb::eTypeOptionCascade
Detailed Description
Definition at line 137 of file TypeSynthetic.h.
Constructor & Destructor Documentation
Flags() [1/3]
lldb_private::SyntheticChildren::Flags::Flags () default
Referenced by Clear(), Flags(), operator=(), operator=(), SetCascades(), SetFrontEndWantsDereference(), SetNonCacheable(), SetSkipPointers(), and SetSkipReferences().
Flags() [2/3]
lldb_private::SyntheticChildren::Flags::Flags (const Flags & other) inline
Definition at line 141 of file TypeSynthetic.h.
References Flags(), and m_flags.
Flags() [3/3]
lldb_private::SyntheticChildren::Flags::Flags (uint32_t value) inline
Definition at line 143 of file TypeSynthetic.h.
References m_flags.
Member Function Documentation
Clear()
Flags & lldb_private::SyntheticChildren::Flags::Clear () inline
Definition at line 157 of file TypeSynthetic.h.
References Flags(), and m_flags.
GetCascades()
bool lldb_private::SyntheticChildren::Flags::GetCascades () const inline
Definition at line 162 of file TypeSynthetic.h.
References m_flags.
GetFrontEndWantsDereference()
bool lldb_private::SyntheticChildren::Flags::GetFrontEndWantsDereference () const inline
Definition at line 213 of file TypeSynthetic.h.
References m_flags.
GetNonCacheable()
bool lldb_private::SyntheticChildren::Flags::GetNonCacheable () const inline
Definition at line 200 of file TypeSynthetic.h.
References m_flags.
GetSkipPointers()
bool lldb_private::SyntheticChildren::Flags::GetSkipPointers () const inline
Definition at line 174 of file TypeSynthetic.h.
References m_flags.
GetSkipReferences()
bool lldb_private::SyntheticChildren::Flags::GetSkipReferences () const inline
Definition at line 187 of file TypeSynthetic.h.
References m_flags.
GetValue()
uint32_t lldb_private::SyntheticChildren::Flags::GetValue () inline
Definition at line 226 of file TypeSynthetic.h.
References m_flags.
operator=() [1/2]
Flags & lldb_private::SyntheticChildren::Flags::operator= (const Flags & rhs) inline
Definition at line 145 of file TypeSynthetic.h.
References Flags(), and m_flags.
operator=() [2/2]
Flags & lldb_private::SyntheticChildren::Flags::operator= (const uint32_t & rhs) inline
Definition at line 152 of file TypeSynthetic.h.
References Flags(), and m_flags.
SetCascades()
Flags & lldb_private::SyntheticChildren::Flags::SetCascades (bool value = true) inline
Definition at line 166 of file TypeSynthetic.h.
References Flags(), and m_flags.
Referenced by LoadCommonStlFormatters(), LoadLibCxxFormatters(), LoadLibStdcppFormatters(), LoadMsvcStlFormatters(), and LoadObjCFormatters().
SetFrontEndWantsDereference()
Flags & lldb_private::SyntheticChildren::Flags::SetFrontEndWantsDereference (bool value = true) inline
Definition at line 218 of file TypeSynthetic.h.
References Flags(), and m_flags.
Referenced by LoadCommonStlFormatters(), LoadLibCxxFormatters(), and LoadLibStdcppFormatters().
SetNonCacheable()
Flags & lldb_private::SyntheticChildren::Flags::SetNonCacheable (bool value = true) inline
Definition at line 205 of file TypeSynthetic.h.
References Flags(), and m_flags.
SetSkipPointers()
Flags & lldb_private::SyntheticChildren::Flags::SetSkipPointers (bool value = true) inline
Definition at line 179 of file TypeSynthetic.h.
References Flags(), and m_flags.
Referenced by CommandObjectTypeSynthAdd::IOHandlerInputComplete(), LoadCommonStlFormatters(), LoadLibCxxFormatters(), LoadLibStdcppFormatters(), LoadMsvcStlFormatters(), and LoadObjCFormatters().
SetSkipReferences()
Flags & lldb_private::SyntheticChildren::Flags::SetSkipReferences (bool value = true) inline
Definition at line 192 of file TypeSynthetic.h.
References Flags(), and m_flags.
Referenced by CommandObjectTypeSynthAdd::IOHandlerInputComplete(), LoadCommonStlFormatters(), LoadLibCxxFormatters(), LoadLibStdcppFormatters(), LoadMsvcStlFormatters(), and LoadObjCFormatters().
SetValue()
void lldb_private::SyntheticChildren::Flags::SetValue (uint32_t value) inline
Definition at line 228 of file TypeSynthetic.h.
References m_flags.
Member Data Documentation
m_flags
uint32_t lldb_private::SyntheticChildren::Flags::m_flags = lldb::eTypeOptionCascade private
Definition at line 231 of file TypeSynthetic.h.
Referenced by Clear(), Flags(), Flags(), GetCascades(), GetFrontEndWantsDereference(), GetNonCacheable(), GetSkipPointers(), GetSkipReferences(), GetValue(), operator=(), operator=(), SetCascades(), SetFrontEndWantsDereference(), SetNonCacheable(), SetSkipPointers(), SetSkipReferences(), and SetValue().
The documentation for this class was generated from the following file:
TypeSynthetic.h