LLDB: lldb_private::NativeRegisterContextDBReg_x86 Class Reference
lldb_private::NativeRegisterContextDBReg_x86 Class Reference
#include <NativeRegisterContextDBReg_x86.h>
Public Member Functions
NativeRegisterContextDBReg_x86 (NativeThreadProtocol &thread)
Status IsWatchpointHit (uint32_t wp_index, bool &is_hit) override
Status GetWatchpointHitIndex (uint32_t &wp_index, lldb::addr_t trap_addr) override
Status IsWatchpointVacant (uint32_t wp_index, bool &is_vacant) override
bool ClearHardwareWatchpoint (uint32_t wp_index) override
Status ClearWatchpointHit (uint32_t wp_index) override
Status ClearAllHardwareWatchpoints () override
Status SetHardwareWatchpointWithIndex (lldb::addr_t addr, size_t size, uint32_t watch_flags, uint32_t wp_index)
uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, uint32_t watch_flags) override
lldb::addr_t GetWatchpointAddress (uint32_t wp_index) override
uint32_t NumSupportedHardwareWatchpoints () override
virtual const RegisterInfo * GetDR (int num) const
Public Member Functions inherited from lldb_private::NativeRegisterContextRegisterInfo
NativeRegisterContextRegisterInfo (NativeThreadProtocol &thread, RegisterInfoInterface *register_info_interface)
Construct a NativeRegisterContextRegisterInfo, taking ownership of the register_info_interface pointer.
uint32_t GetRegisterCount () const override
uint32_t GetUserRegisterCount () const override
const RegisterInfo * GetRegisterInfoAtIndex (uint32_t reg_index) const override
const RegisterInfoInterface & GetRegisterInfoInterface () const
Public Member Functions inherited from lldb_private::NativeRegisterContext
NativeRegisterContext (NativeThreadProtocol &thread)
virtual ~NativeRegisterContext ()
const char * GetRegisterSetNameForRegisterAtIndex (uint32_t reg_index) const
virtual uint32_t GetRegisterSetCount () const =0
virtual const RegisterSet * GetRegisterSet (uint32_t set_index) const =0
virtual Status ReadRegister (const RegisterInfo *reg_info, RegisterValue &reg_value)=0
virtual Status WriteRegister (const RegisterInfo *reg_info, const RegisterValue &reg_value)=0
virtual Status ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp)=0
virtual Status WriteAllRegisterValues (const lldb::DataBufferSP &data_sp)=0
uint32_t ConvertRegisterKindToRegisterNumber (uint32_t kind, uint32_t num) const
virtual uint32_t NumSupportedHardwareBreakpoints ()
virtual uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual bool ClearHardwareBreakpoint (uint32_t hw_idx)
virtual Status ClearAllHardwareBreakpoints ()
virtual Status GetHardwareBreakHitIndex (uint32_t &bp_index, lldb::addr_t trap_addr)
virtual lldb::addr_t GetWatchpointHitAddress (uint32_t wp_index)
virtual bool HardwareSingleStep (bool enable)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, size_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, size_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual NativeThreadProtocol & GetThread ()
virtual std::vector< uint32_t > GetExpeditedRegisters (ExpeditedRegs expType) const
virtual bool RegisterOffsetIsDynamic () const
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (uint32_t reg_kind, uint32_t reg_num)
lldb::addr_t GetPC (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
virtual lldb::addr_t GetPCfromBreakpointLocation (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
Status SetPC (lldb::addr_t pc)
lldb::addr_t GetSP (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
Status SetSP (lldb::addr_t sp)
lldb::addr_t GetFP (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
Status SetFP (lldb::addr_t fp)
const char * GetRegisterName (uint32_t reg)
lldb::addr_t GetReturnAddress (lldb::addr_t fail_value=LLDB_INVALID_ADDRESS)
lldb::addr_t GetFlags (lldb::addr_t fail_value=0)
lldb::addr_t ReadRegisterAsUnsigned (uint32_t reg, lldb::addr_t fail_value)
lldb::addr_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, lldb::addr_t fail_value)
Status WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
Status WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
Additional Inherited Members
Protected Attributes inherited from lldb_private::NativeRegisterContextRegisterInfo
std::unique_ptr< RegisterInfoInterface > m_register_info_interface_up
Protected Attributes inherited from lldb_private::NativeRegisterContext
NativeThreadProtocol & m_thread
Detailed Description
Definition at line 16 of file NativeRegisterContextDBReg_x86.h.
Constructor & Destructor Documentation
NativeRegisterContextDBReg_x86()
lldb_private::NativeRegisterContextDBReg_x86::NativeRegisterContextDBReg_x86 (NativeThreadProtocol & thread) inline
Definition at line 22 of file NativeRegisterContextDBReg_x86.h.
References lldb_private::NativeRegisterContextRegisterInfo::NativeRegisterContextRegisterInfo().
Member Function Documentation
ClearAllHardwareWatchpoints()
Status NativeRegisterContextDBReg_x86::ClearAllHardwareWatchpoints () override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 233 of file NativeRegisterContextDBReg_x86.cpp.
References error(), lldb_private::RegisterValue::GetAsUInt64(), GetDR(), lldb_private::NativeRegisterContext::ReadRegister(), watchpoint_all_control_bit_mask, and lldb_private::NativeRegisterContext::WriteRegister().
ClearHardwareWatchpoint()
bool NativeRegisterContextDBReg_x86::ClearHardwareWatchpoint (uint32_t wp_index) override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 205 of file NativeRegisterContextDBReg_x86.cpp.
References error(), lldb_private::RegisterValue::GetAsUInt64(), GetBothEnableBitMask(), GetDR(), NumSupportedHardwareWatchpoints(), lldb_private::NativeRegisterContext::ReadRegister(), lldb_private::Status::Success(), and lldb_private::NativeRegisterContext::WriteRegister().
ClearWatchpointHit()
Status NativeRegisterContextDBReg_x86::ClearWatchpointHit (uint32_t wp_index) override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 220 of file NativeRegisterContextDBReg_x86.cpp.
References error(), lldb_private::Status::FromErrorString(), lldb_private::RegisterValue::GetAsUInt64(), GetDR(), GetStatusBit(), NumSupportedHardwareWatchpoints(), lldb_private::NativeRegisterContext::ReadRegister(), and lldb_private::NativeRegisterContext::WriteRegister().
Referenced by SetHardwareWatchpointWithIndex().
GetDR()
const RegisterInfo * NativeRegisterContextDBReg_x86::GetDR (int num) const virtual
Definition at line 83 of file NativeRegisterContextDBReg_x86.cpp.
References lldb_private::NativeRegisterContextRegisterInfo::GetRegisterInfoAtIndex(), lldb_private::NativeRegisterContextRegisterInfo::GetRegisterInfoInterface(), lldb_private::lldb_dr0_i386, and lldb_private::lldb_dr0_x86_64.
Referenced by ClearAllHardwareWatchpoints(), ClearHardwareWatchpoint(), ClearWatchpointHit(), GetWatchpointAddress(), IsWatchpointHit(), IsWatchpointVacant(), and SetHardwareWatchpointWithIndex().
GetWatchpointAddress()
lldb::addr_t NativeRegisterContextDBReg_x86::GetWatchpointAddress (uint32_t wp_index) override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 264 of file NativeRegisterContextDBReg_x86.cpp.
References lldb_private::RegisterValue::GetAsUInt64(), GetDR(), LLDB_INVALID_ADDRESS, NumSupportedHardwareWatchpoints(), and lldb_private::NativeRegisterContext::ReadRegister().
GetWatchpointHitIndex()
Status NativeRegisterContextDBReg_x86::GetWatchpointHitIndex (uint32_t & wp_index, lldb::addr_t trap_addr) override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 111 of file NativeRegisterContextDBReg_x86.cpp.
References error(), IsWatchpointHit(), LLDB_INVALID_INDEX32, NumSupportedHardwareWatchpoints(), and lldb_private::Status.
IsWatchpointHit()
Status NativeRegisterContextDBReg_x86::IsWatchpointHit (uint32_t wp_index, bool & is_hit) override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 95 of file NativeRegisterContextDBReg_x86.cpp.
References error(), lldb_private::Status::FromErrorString(), lldb_private::RegisterValue::GetAsUInt64(), GetDR(), GetStatusBit(), NumSupportedHardwareWatchpoints(), and lldb_private::NativeRegisterContext::ReadRegister().
Referenced by GetWatchpointHitIndex().
IsWatchpointVacant()
Status NativeRegisterContextDBReg_x86::IsWatchpointVacant (uint32_t wp_index, bool & is_vacant) override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 128 of file NativeRegisterContextDBReg_x86.cpp.
References error(), lldb_private::Status::FromErrorString(), lldb_private::RegisterValue::GetAsUInt64(), GetDR(), GetEnableBit(), NumSupportedHardwareWatchpoints(), and lldb_private::NativeRegisterContext::ReadRegister().
Referenced by SetHardwareWatchpoint(), and SetHardwareWatchpointWithIndex().
NumSupportedHardwareWatchpoints()
uint32_t NativeRegisterContextDBReg_x86::NumSupportedHardwareWatchpoints () override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 273 of file NativeRegisterContextDBReg_x86.cpp.
Referenced by ClearHardwareWatchpoint(), ClearWatchpointHit(), GetWatchpointAddress(), GetWatchpointHitIndex(), IsWatchpointHit(), IsWatchpointVacant(), SetHardwareWatchpoint(), and SetHardwareWatchpointWithIndex().
SetHardwareWatchpoint()
uint32_t NativeRegisterContextDBReg_x86::SetHardwareWatchpoint (lldb::addr_t addr, size_t size, uint32_t watch_flags) override virtual
Reimplemented from lldb_private::NativeRegisterContext.
Definition at line 243 of file NativeRegisterContextDBReg_x86.cpp.
References error(), lldb_private::GetLog(), IsWatchpointVacant(), LLDB_INVALID_INDEX32, LLDB_LOGF, NumSupportedHardwareWatchpoints(), SetHardwareWatchpointWithIndex(), and lldb_private::Watchpoints.
SetHardwareWatchpointWithIndex()
Status NativeRegisterContextDBReg_x86::SetHardwareWatchpointWithIndex (lldb::addr_t addr, size_t size, uint32_t watch_flags, uint32_t wp_index)
Definition at line 143 of file NativeRegisterContextDBReg_x86.cpp.
References ClearWatchpointHit(), error(), lldb_private::Status::FromErrorString(), lldb_private::RegisterValue::GetAsUInt64(), GetDR(), GetEnableBit(), GetWatchControlBitmask(), GetWatchSizeBits(), GetWatchTypeBits(), IsWatchpointVacant(), NumSupportedHardwareWatchpoints(), lldb_private::NativeRegisterContext::ReadRegister(), and lldb_private::NativeRegisterContext::WriteRegister().
Referenced by SetHardwareWatchpoint().
The documentation for this class was generated from the following files:
NativeRegisterContextDBReg_x86.h
NativeRegisterContextDBReg_x86.cpp