LLDB: CommandObjectBreakpointAddScripted::CommandOptions Class Reference
CommandObjectBreakpointAddScripted::CommandOptions Class Reference
Public Member Functions
CommandOptions ()=default
~CommandOptions () override=default
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext *execution_context) override
void OptionParsingStarting (ExecutionContext *execution_context) override
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Public Attributes
bool m_hardware = false
FileSpecList m_files
FileSpecList m_modules
Detailed Description
Definition at line 1367 of file CommandObjectBreakpoint.cpp.
Constructor & Destructor Documentation
CommandOptions()
CommandObjectBreakpointAddScripted::CommandOptions::CommandOptions () default
~CommandOptions()
CommandObjectBreakpointAddScripted::CommandOptions::~CommandOptions () override default
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > CommandObjectBreakpointAddScripted::CommandOptions::GetDefinitions () inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 1402 of file CommandObjectBreakpoint.cpp.
Referenced by SetOptionValue().
OptionParsingStarting()
void CommandObjectBreakpointAddScripted::CommandOptions::OptionParsingStarting (ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 1396 of file CommandObjectBreakpoint.cpp.
References m_files, m_hardware, and m_modules.
SetOptionValue()
Status CommandObjectBreakpointAddScripted::CommandOptions::SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 1373 of file CommandObjectBreakpoint.cpp.
References error(), GetDefinitions(), m_files, m_hardware, and m_modules.
Member Data Documentation
m_files
FileSpecList CommandObjectBreakpointAddScripted::CommandOptions::m_files
Definition at line 1408 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_hardware
bool CommandObjectBreakpointAddScripted::CommandOptions::m_hardware = false
Definition at line 1407 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_modules
FileSpecList CommandObjectBreakpointAddScripted::CommandOptions::m_modules
Definition at line 1409 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following file:
CommandObjectBreakpoint.cpp