LLDB: lldb::SBCommandInterpreterRunResult Class Reference
lldb::SBCommandInterpreterRunResult Class Reference
#include <SBCommandInterpreterRunOptions.h>
Public Member Functions
SBCommandInterpreterRunResult ()
SBCommandInterpreterRunResult (const SBCommandInterpreterRunResult &rhs)
~SBCommandInterpreterRunResult ()
SBCommandInterpreterRunResult & operator= (const SBCommandInterpreterRunResult &rhs)
int GetNumberOfErrors () const
lldb::CommandInterpreterResult GetResult () const
Private Member Functions
SBCommandInterpreterRunResult (const lldb_private::CommandInterpreterRunResult &rhs)
Private Attributes
std::unique_ptr< lldb_private::CommandInterpreterRunResult > m_opaque_up
Friends
class SBDebugger
class SBCommandInterpreter
Detailed Description
Definition at line 94 of file SBCommandInterpreterRunOptions.h.
Constructor & Destructor Documentation
SBCommandInterpreterRunResult() [1/3]
SBCommandInterpreterRunResult::SBCommandInterpreterRunResult ()
Definition at line 189 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by operator=(), SBCommandInterpreter, SBCommandInterpreterRunResult(), and ~SBCommandInterpreterRunResult().
SBCommandInterpreterRunResult() [2/3]
SBCommandInterpreterRunResult::SBCommandInterpreterRunResult (const SBCommandInterpreterRunResult & rhs)
Definition at line 196 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and SBCommandInterpreterRunResult().
~SBCommandInterpreterRunResult()
SBCommandInterpreterRunResult::~SBCommandInterpreterRunResult () default
References GetNumberOfErrors(), GetResult(), operator=(), and SBCommandInterpreterRunResult().
SBCommandInterpreterRunResult() [3/3]
SBCommandInterpreterRunResult::SBCommandInterpreterRunResult (const lldb_private::CommandInterpreterRunResult & rhs) private
Definition at line 204 of file SBCommandInterpreterRunOptions.cpp.
References m_opaque_up.
Member Function Documentation
GetNumberOfErrors()
int SBCommandInterpreterRunResult::GetNumberOfErrors () const
Definition at line 221 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunResult().
GetResult()
lldb::CommandInterpreterResult SBCommandInterpreterRunResult::GetResult () const
Definition at line 228 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBCommandInterpreterRunResult().
operator=()
SBCommandInterpreterRunResult & SBCommandInterpreterRunResult::operator= (const SBCommandInterpreterRunResult & rhs)
Definition at line 211 of file SBCommandInterpreterRunOptions.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and SBCommandInterpreterRunResult().
Referenced by ~SBCommandInterpreterRunResult().
Friends And Related Symbol Documentation
SBCommandInterpreter
friend class SBCommandInterpreter friend
Definition at line 96 of file SBCommandInterpreterRunOptions.h.
References SBCommandInterpreter, and SBCommandInterpreterRunResult().
Referenced by SBCommandInterpreter.
SBDebugger
friend class SBDebugger friend
Definition at line 95 of file SBCommandInterpreterRunOptions.h.
References SBDebugger.
Referenced by SBDebugger.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::CommandInterpreterRunResult> lldb::SBCommandInterpreterRunResult::m_opaque_up private
Definition at line 114 of file SBCommandInterpreterRunOptions.h.
Referenced by GetNumberOfErrors(), GetResult(), operator=(), SBCommandInterpreterRunResult(), SBCommandInterpreterRunResult(), and SBCommandInterpreterRunResult().
The documentation for this class was generated from the following files:
SBCommandInterpreterRunOptions.h
SBCommandInterpreterRunOptions.cpp