LLDB: lldb_private::HostInfoMacOSX Class Reference
lldb_private::HostInfoMacOSX Class Reference
#include <HostInfoMacOSX.h>
Static Public Member Functions
static llvm::VersionTuple GetOSVersion ()
static llvm::VersionTuple GetMacCatalystVersion ()
static std::optional< std::string > GetOSBuildString ()
static FileSpec GetProgramFileSpec ()
static FileSpec GetXcodeContentsDirectory ()
static FileSpec GetXcodeDeveloperDirectory ()
static FileSpec GetCurrentXcodeToolchainDirectory ()
static FileSpec GetCurrentCommandLineToolsDirectory ()
static llvm::Expected< llvm::StringRef > GetSDKRoot (SDKOptions options)
Query xcrun to find an Xcode SDK directory.
static llvm::Expected< llvm::StringRef > FindSDKTool (XcodeSDK sdk, llvm::StringRef tool)
static SharedCacheImageInfo GetSharedCacheImageInfo (ConstString filepath, lldb::SymbolSharedCacheUse sc_mode)
Shared cache utilities.
static SharedCacheImageInfo GetSharedCacheImageInfo (const UUID &uuid, lldb::SymbolSharedCacheUse sc_mode)
static SharedCacheImageInfo GetSharedCacheImageInfo (ConstString filepath, const UUID &sc_uuid, lldb::SymbolSharedCacheUse sc_mode)
static SharedCacheImageInfo GetSharedCacheImageInfo (const UUID &uuid, const UUID &sc_uuid, lldb::SymbolSharedCacheUse sc_mode)
static bool SharedCacheIndexFiles (FileSpec &filepath, UUID &uuid, lldb::SymbolSharedCacheUse sc_mode)
Static Public Member Functions inherited from lldb_private::HostInfoPosix
static size_t GetPageSize ()
static bool GetHostname (std::string &s)
static std::optional< std::string > GetOSKernelDescription ()
static uint32_t GetUserID ()
static uint32_t GetGroupID ()
static uint32_t GetEffectiveUserID ()
static uint32_t GetEffectiveGroupID ()
static FileSpec GetDefaultShell ()
static bool GetEnvironmentVar (const std::string &var_name, std::string &var)
static UserIDResolver & GetUserIDResolver ()
static llvm::VersionTuple GetOSVersion ()
static std::optional< std::string > GetOSBuildString ()
static llvm::Expected< llvm::StringRef > GetSDKRoot (SDKOptions options)
The SDK is the directory where the system C headers, libraries, can be found.
Static Public Member Functions inherited from lldb_private::HostInfoBase
static void Initialize (SharedLibraryDirectoryHelper *helper=nullptr)
static void Terminate ()
static llvm::Triple GetTargetTriple ()
Gets the host target triple.
static const ArchSpec & GetArchitecture (ArchitectureKind arch_kind=eArchKindDefault)
static std::optional< ArchitectureKind > ParseArchitectureKind (llvm::StringRef kind)
static FileSpec GetShlibDir ()
Returns the directory containing the lldb shared library.
static FileSpec GetSupportExeDir ()
Returns the directory containing the support executables (debugserver, ...).
static FileSpec GetHeaderDir ()
Returns the directory containing the lldb headers.
static FileSpec GetSystemPluginDir ()
Returns the directory containing the system plugins.
static FileSpec GetUserHomeDir ()
Returns the directory containing the users home (e.g.
static FileSpec GetUserLLDBDir ()
Returns the directory containing the users lldb home (e.g.
static FileSpec GetUserPluginDir ()
Returns the directory containing the user plugins.
static FileSpec GetProcessTempDir ()
Returns the process temporary directory.
static FileSpec GetGlobalTempDir ()
Returns the global temporary directory.
static ArchSpec GetAugmentedArchSpec (llvm::StringRef triple)
If the triple does not specify the vendor, os, and environment parts, we "augment" these using information from the host and return the resulting ArchSpec object.
static bool ComputePathRelativeToLibrary (FileSpec &file_spec, llvm::StringRef dir)
static FileSpec GetXcodeContentsDirectory ()
static FileSpec GetXcodeDeveloperDirectory ()
static FileSpec GetCurrentXcodeToolchainDirectory ()
static FileSpec GetCurrentCommandLineToolsDirectory ()
static llvm::Expected< llvm::StringRef > GetSDKRoot (SDKOptions options)
Return the directory containing something like a SDK (reused for Swift).
static llvm::Expected< llvm::StringRef > FindSDKTool (XcodeSDK sdk, llvm::StringRef tool)
Return the path to a specific tool in the specified Xcode SDK.
static SharedCacheImageInfo GetSharedCacheImageInfo (ConstString filepath, lldb::SymbolSharedCacheUse sc_mode)
Return information about module filepath if it is loaded in the current process's address space.
static SharedCacheImageInfo GetSharedCacheImageInfo (const UUID &uuid, lldb::SymbolSharedCacheUse sc_mode)
Return information about module uuid if it is loaded in the current process's address space.
static SharedCacheImageInfo GetSharedCacheImageInfo (ConstString filepath, const UUID &sc_uuid, lldb::SymbolSharedCacheUse sc_mode)
Return information about module filepath, if it is loaded in the current process's address space using shared cache sc_uuid.
static SharedCacheImageInfo GetSharedCacheImageInfo (const UUID &uuid, const UUID &sc_uuid, lldb::SymbolSharedCacheUse sc_mode)
Return information about module uuid, if it is loaded in the current process's address space using shared cache sc_uuid.
static SharedCacheImageInfo GetSharedCacheImageInfo (llvm::StringRef image_name, const UUID &uuid, lldb::SymbolSharedCacheUse sc_mode)
Return information about module image_name if it is loaded in the current process's address space using shared cache uuid.
static bool SharedCacheIndexFiles (FileSpec &filepath, UUID &uuid, lldb::SymbolSharedCacheUse sc_mode)
Scan the files in a shared cache, if the filepath and uuid match on the debug host.
static llvm::StringRef GetDistributionId ()
Returns the distribution id of the host.
Static Protected Member Functions
static bool ComputeSupportExeDirectory (FileSpec &file_spec)
static void ComputeHostArchitectureSupport (ArchSpec &arch_32, ArchSpec &arch_64)
static bool ComputeHeaderDirectory (FileSpec &file_spec)
static bool ComputeSystemPluginsDirectory (FileSpec &file_spec)
static bool ComputeUserPluginsDirectory (FileSpec &file_spec)
static std::string FindComponentInPath (llvm::StringRef path, llvm::StringRef component)
Static Protected Member Functions inherited from lldb_private::HostInfoPosix
static bool ComputeSupportExeDirectory (FileSpec &file_spec)
static bool ComputeHeaderDirectory (FileSpec &file_spec)
static bool ComputeSystemPluginsDirectory (FileSpec &file_spec)
static bool ComputeUserPluginsDirectory (FileSpec &file_spec)
Static Protected Member Functions inherited from lldb_private::HostInfoBase
static bool ComputeSharedLibraryDirectory (FileSpec &file_spec)
static bool ComputeSupportExeDirectory (FileSpec &file_spec)
static bool ComputeProcessTempFileDirectory (FileSpec &file_spec)
static bool ComputeGlobalTempFileDirectory (FileSpec &file_spec)
static bool ComputeTempFileBaseDirectory (FileSpec &file_spec)
static bool ComputeHeaderDirectory (FileSpec &file_spec)
static bool ComputeSystemPluginsDirectory (FileSpec &file_spec)
static bool ComputeUserHomeDirectory (FileSpec &file_spec)
static bool ComputeUserLLDBHomeDirectory (FileSpec &file_spec)
static bool ComputeUserPluginsDirectory (FileSpec &file_spec)
static void ComputeHostArchitectureSupport (ArchSpec &arch_32, ArchSpec &arch_64)
Friends
class HostInfoBase
Additional Inherited Members
Public Types inherited from lldb_private::HostInfoBase
enum ArchitectureKind { eArchKindDefault , eArchKind32 , eArchKind64 }
using SharedLibraryDirectoryHelper = void(FileSpec &this_file)
A helper function for determining the liblldb location.
Detailed Description
Definition at line 23 of file HostInfoMacOSX.h.
Member Function Documentation
ComputeHeaderDirectory()
bool HostInfoMacOSX::ComputeHeaderDirectory (FileSpec & file_spec) static protected
Definition at line 200 of file HostInfoMacOSX.mm.
References lldb_private::FileSpec::GetPath(), lldb_private::HostInfoBase::GetShlibDir(), and lldb_private::FileSpec::SetDirectory().
ComputeHostArchitectureSupport()
void HostInfoMacOSX::ComputeHostArchitectureSupport (ArchSpec & arch_32, ArchSpec & arch_64) static protected
Definition at line 242 of file HostInfoMacOSX.mm.
References lldb_private::ArchSpec::Clear(), CPU_SUBTYPE_X86_64_H, CPU_TYPE_ARM64, CPU_TYPE_ARM64_32, lldb_private::eArchTypeMachO, lldb_private::ArchSpec::GetTriple(), and lldb_private::ArchSpec::SetArchitecture().
ComputeSupportExeDirectory()
bool HostInfoMacOSX::ComputeSupportExeDirectory (FileSpec & file_spec) static protected
Definition at line 141 of file HostInfoMacOSX.mm.
References lldb_private::FileSpec::CopyByAppendingPathComponent(), lldb_private::FileSpec::GetDirectory(), lldb_private::GetLog(), lldb_private::FileSpec::GetPath(), lldb_private::HostInfoBase::GetShlibDir(), lldb_private::Host, LLDB_LOG, ResolveAndVerifyCandidateSupportDir(), and lldb_private::FileSpec::SetDirectory().
ComputeSystemPluginsDirectory()
bool HostInfoMacOSX::ComputeSystemPluginsDirectory (FileSpec & file_spec) static protected
Definition at line 217 of file HostInfoMacOSX.mm.
References lldb_private::FileSpec::GetPath(), lldb_private::HostInfoBase::GetShlibDir(), and lldb_private::FileSpec::SetDirectory().
ComputeUserPluginsDirectory()
bool HostInfoMacOSX::ComputeUserPluginsDirectory (FileSpec & file_spec) static protected
Definition at line 235 of file HostInfoMacOSX.mm.
References lldb_private::FileSpec::AppendPathComponent(), lldb_private::FileSpec::GetPathAsConstString(), lldb_private::HostInfoBase::GetUserHomeDir(), and lldb_private::FileSpec::SetDirectory().
FindComponentInPath()
std::string HostInfoMacOSX::FindComponentInPath (llvm::StringRef path, llvm::StringRef component) static protected
Definition at line 404 of file HostInfoMacOSX.mm.
Referenced by GetCurrentCommandLineToolsDirectory(), and GetCurrentXcodeToolchainDirectory().
FindSDKTool()
llvm::Expected< llvm::StringRef > HostInfoMacOSX::FindSDKTool (XcodeSDK sdk, llvm::StringRef tool) static
Definition at line 625 of file HostInfoMacOSX.mm.
References find_cached_path(), lldb_private::XcodeSDK::GetCanonicalName(), lldb_private::XcodeSDK::GetString(), lldb_private::XcodeSDK::Parse(), and xcrun().
GetCurrentCommandLineToolsDirectory()
FileSpec HostInfoMacOSX::GetCurrentCommandLineToolsDirectory () static
Definition at line 425 of file HostInfoMacOSX.mm.
References FindComponentInPath().
GetCurrentXcodeToolchainDirectory()
FileSpec HostInfoMacOSX::GetCurrentXcodeToolchainDirectory () static
Definition at line 419 of file HostInfoMacOSX.mm.
References FindComponentInPath().
GetMacCatalystVersion()
llvm::VersionTuple HostInfoMacOSX::GetMacCatalystVersion () static
Definition at line 104 of file HostInfoMacOSX.mm.
References ParseOSVersion().
GetOSBuildString()
std::optional< std::string > HostInfoMacOSX::GetOSBuildString () static
Definition at line 76 of file HostInfoMacOSX.mm.
References PATH_MAX.
GetOSVersion()
llvm::VersionTuple HostInfoMacOSX::GetOSVersion () static
Definition at line 97 of file HostInfoMacOSX.mm.
References ParseOSVersion().
GetProgramFileSpec()
FileSpec HostInfoMacOSX::GetProgramFileSpec () static
Definition at line 112 of file HostInfoMacOSX.mm.
References PATH_MAX, and lldb_private::FileSpec::SetFile().
GetSDKRoot()
llvm::Expected< llvm::StringRef > HostInfoMacOSX::GetSDKRoot (SDKOptions options) static
Query xcrun to find an Xcode SDK directory.
Note, this is an expensive operation if the SDK we're querying does not exist in an Xcode installation path on the host.
Definition at line 611 of file HostInfoMacOSX.mm.
References find_cached_path(), lldb_private::XcodeSDK::GetString(), GetXcodeSDK(), and lldb_private::HostInfoBase::SDKOptions::XcodeSDKSelection.
GetSharedCacheImageInfo() [1/4]
SharedCacheImageInfo HostInfoMacOSX::GetSharedCacheImageInfo (const UUID & uuid, const UUID & sc_uuid, lldb::SymbolSharedCacheUse sc_mode) static
Definition at line 1082 of file HostInfoMacOSX.mm.
References GetSharedCacheSingleton().
GetSharedCacheImageInfo() [2/4]
SharedCacheImageInfo HostInfoMacOSX::GetSharedCacheImageInfo (const UUID & uuid, lldb::SymbolSharedCacheUse sc_mode) static
Definition at line 1072 of file HostInfoMacOSX.mm.
References GetSharedCacheSingleton().
GetSharedCacheImageInfo() [3/4]
SharedCacheImageInfo HostInfoMacOSX::GetSharedCacheImageInfo (ConstString filepath, const UUID & sc_uuid, lldb::SymbolSharedCacheUse sc_mode) static
Definition at line 1077 of file HostInfoMacOSX.mm.
References GetSharedCacheSingleton().
GetSharedCacheImageInfo() [4/4]
SharedCacheImageInfo HostInfoMacOSX::GetSharedCacheImageInfo (ConstString filepath, lldb::SymbolSharedCacheUse sc_mode) static
Shared cache utilities.
Definition at line 1066 of file HostInfoMacOSX.mm.
References GetSharedCacheSingleton().
GetXcodeContentsDirectory()
FileSpec HostInfoMacOSX::GetXcodeContentsDirectory () static
Definition at line 341 of file HostInfoMacOSX.mm.
References lldb_private::XcodeSDK::FindXcodeContentsDirectoryInPath(), lldb_private::XcodeSDK::GetAnyMacOS(), GetEnvDeveloperDir(), lldb_private::GetLog(), lldb_private::FileSpec::GetPath(), lldb_private::Host, lldb_private::FileSystem::Instance(), and LLDB_LOG_ERROR.
Referenced by GetXcodeDeveloperDirectory().
GetXcodeDeveloperDirectory()
lldb_private::FileSpec HostInfoMacOSX::GetXcodeDeveloperDirectory () static
Definition at line 391 of file HostInfoMacOSX.mm.
References GetXcodeContentsDirectory(), and lldb_private::FileSystem::Instance().
SharedCacheIndexFiles()
bool HostInfoMacOSX::SharedCacheIndexFiles (FileSpec & filepath, UUID & uuid, lldb::SymbolSharedCacheUse sc_mode) static
Definition at line 1087 of file HostInfoMacOSX.mm.
References lldb::eSymbolSharedCacheUseHostLLDBMemory, lldb_private::FileSpec::GetPath(), GetSharedCacheSingleton(), and lldb_private::FileSystem::Instance().
Friends And Related Symbol Documentation
HostInfoBase
friend class HostInfoBase friend
Definition at line 24 of file HostInfoMacOSX.h.
References HostInfoBase.
Referenced by HostInfoBase.
The documentation for this class was generated from the following files:
HostInfoMacOSX.h
HostInfoMacOSX.mm