LLDB: lldb_private::wasm::SymbolVendorWasm Class Reference
lldb_private::wasm::SymbolVendorWasm Class Reference
#include <SymbolVendorWasm.h>
Public Member Functions
SymbolVendorWasm (const lldb::ModuleSP &module_sp)
llvm::StringRef GetPluginName () override
PluginInterface protocol.
Public Member Functions inherited from lldb_private::SymbolVendor
SymbolVendor (const lldb::ModuleSP &module_sp)
void AddSymbolFileRepresentation (const lldb::ObjectFileSP &objfile_sp)
SymbolFile * GetSymbolFile ()
Public Member Functions inherited from lldb_private::ModuleChild
ModuleChild (const lldb::ModuleSP &module_sp)
Construct with owning module.
~ModuleChild ()
Destructor.
const ModuleChild & operator= (const ModuleChild &rhs)
Assignment operator.
lldb::ModuleSP GetModule () const
Get const accessor for the module pointer.
void SetModule (const lldb::ModuleSP &module_sp)
Set accessor for the module pointer.
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static lldb_private::SymbolVendor * CreateInstance (const lldb::ModuleSP &module_sp, lldb_private::Stream *feedback_strm)
Static Public Member Functions inherited from lldb_private::SymbolVendor
static SymbolVendor * FindPlugin (const lldb::ModuleSP &module_sp, Stream *feedback_strm)
Additional Inherited Members
Protected Attributes inherited from lldb_private::SymbolVendor
std::unique_ptr< SymbolFile > m_sym_file_up
Protected Attributes inherited from lldb_private::ModuleChild
lldb::ModuleWP m_module_wp
The Module that owns the object that inherits from this class.
Detailed Description
Definition at line 18 of file SymbolVendorWasm.h.
Constructor & Destructor Documentation
SymbolVendorWasm()
SymbolVendorWasm::SymbolVendorWasm (const lldb::ModuleSP & module_sp)
Definition at line 32 of file SymbolVendorWasm.cpp.
References lldb_private::SymbolVendor::SymbolVendor(), and SymbolVendorWasm().
Referenced by CreateInstance(), and SymbolVendorWasm().
Member Function Documentation
CreateInstance()
SymbolVendor * SymbolVendorWasm::CreateInstance (const lldb::ModuleSP & module_sp, lldb_private::Stream * feedback_strm) static
Definition at line 55 of file SymbolVendorWasm.cpp.
References lldb_private::SectionList::AddSection(), lldb_private::SymbolVendor::AddSymbolFileRepresentation(), lldb::eSectionTypeDWARFDebugAbbrev, lldb::eSectionTypeDWARFDebugAddr, lldb::eSectionTypeDWARFDebugAranges, lldb::eSectionTypeDWARFDebugCuIndex, lldb::eSectionTypeDWARFDebugFrame, lldb::eSectionTypeDWARFDebugInfo, lldb::eSectionTypeDWARFDebugLine, lldb::eSectionTypeDWARFDebugLineStr, lldb::eSectionTypeDWARFDebugLoc, lldb::eSectionTypeDWARFDebugLocLists, lldb::eSectionTypeDWARFDebugMacInfo, lldb::eSectionTypeDWARFDebugMacro, lldb::eSectionTypeDWARFDebugPubNames, lldb::eSectionTypeDWARFDebugPubTypes, lldb::eSectionTypeDWARFDebugRanges, lldb::eSectionTypeDWARFDebugRngLists, lldb::eSectionTypeDWARFDebugStr, lldb::eSectionTypeDWARFDebugStrOffsets, lldb::eSectionTypeDWARFDebugTypes, lldb_private::ObjectFile::eTypeDebugInfo, lldb_private::ObjectFile::FindPlugin(), lldb_private::SectionList::FindSectionByType(), lldb_private::Target::GetDefaultDebugFileSearchPaths(), lldb_private::wasm::ObjectFileWasm::GetExternalDebugInfoFileSpec(), lldb_private::ModuleSpec::GetFileSpec(), lldb_private::ObjectFile::GetFileSpec(), lldb_private::ObjectFile::GetSectionList(), lldb_private::ModuleSpec::GetSymbolFileSpec(), lldb_private::ModuleSpec::GetUUID(), lldb_private::wasm::ObjectFileWasm::GetUUID(), lldb_private::FileSystem::Instance(), LLDB_SCOPED_TIMERF, lldb_private::PluginManager::LocateExecutableSymbolFile(), lldb_private::SectionList::ReplaceSection(), lldb_private::FileSystem::Resolve(), and SymbolVendorWasm().
Referenced by Initialize(), and Terminate().
GetPluginDescriptionStatic()
llvm::StringRef SymbolVendorWasm::GetPluginDescriptionStatic () static
Definition at line 44 of file SymbolVendorWasm.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef lldb_private::wasm::SymbolVendorWasm::GetPluginName () inline override virtual
PluginInterface protocol.
Reimplemented from lldb_private::SymbolVendor.
Definition at line 33 of file SymbolVendorWasm.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::wasm::SymbolVendorWasm::GetPluginNameStatic () inline static
Definition at line 24 of file SymbolVendorWasm.h.
Referenced by GetPluginName(), and Initialize().
Initialize()
void SymbolVendorWasm::Initialize () static
Definition at line 35 of file SymbolVendorWasm.cpp.
References CreateInstance(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Terminate()
void SymbolVendorWasm::Terminate () static
Definition at line 40 of file SymbolVendorWasm.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
The documentation for this class was generated from the following files:
SymbolVendorWasm.h
SymbolVendorWasm.cpp