LLDB: lldb_private::ScriptedProcessPythonInterface Class Reference
lldb_private::ScriptedProcessPythonInterface Class Reference
#include <ScriptedProcessPythonInterface.h>
Public Member Functions
ScriptedProcessPythonInterface (ScriptInterpreterPythonImpl &interpreter)
llvm::Expected< StructuredData::GenericSP > CreatePluginObject (const llvm::StringRef class_name, ExecutionContext &exe_ctx, StructuredData::DictionarySP args_sp, StructuredData::Generic *script_obj=nullptr) override
llvm::SmallVector< AbstractMethodRequirement > GetAbstractMethodRequirements () const override
StructuredData::DictionarySP GetCapabilities () override
Status Attach (const ProcessAttachInfo &attach_info) override
Status Launch () override
Status Resume () override
std::optional< MemoryRegionInfo > GetMemoryRegionContainingAddress (lldb::addr_t address, Status &error) override
StructuredData::DictionarySP GetThreadsInfo () override
bool CreateBreakpoint (lldb::addr_t addr, Status &error) override
lldb::DataExtractorSP ReadMemoryAtAddress (lldb::addr_t address, size_t size, Status &error) override
lldb::offset_t WriteMemoryAtAddress (lldb::addr_t addr, lldb::DataExtractorSP data_sp, Status &error) override
StructuredData::ArraySP GetLoadedImages () override
lldb::pid_t GetProcessID () override
bool IsAlive () override
std::optional< std::string > GetScriptedThreadPluginName () override
StructuredData::DictionarySP GetMetadata () override
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::ScriptedInterface
ScriptedInterface ()=default
virtual ~ScriptedInterface ()=default
StructuredData::GenericSP GetScriptObjectInstance ()
llvm::SmallVector< llvm::StringLiteral > const GetAbstractMethods () const
Public Member Functions inherited from lldb_private::ScriptedPythonInterface
ScriptedPythonInterface (ScriptInterpreterPythonImpl &interpreter)
~ScriptedPythonInterface () override=default
llvm::Expected< FileSpec > GetScriptedModulePath () override
llvm::Expected< std::map< llvm::StringLiteral, AbstractMethodCheckerPayload > > CheckAbstractMethodImplementation (const python::PythonDictionary &class_dict) const
template<typename... Args>
llvm::Expected< StructuredData::GenericSP > CreatePluginObject (llvm::StringRef class_name, StructuredData::Generic *script_obj, Args... args)
template<typename T = StructuredData::ObjectSP, typename... Args>
T CallStaticMethod (llvm::StringRef class_name, llvm::StringRef method_name, Status &error, Args &&...args)
Call a static method on a Python class without creating an instance.
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
Static Public Member Functions inherited from lldb_private::ScriptedInterface
template<typename Ret>
static Ret ErrorWithMessage (llvm::StringRef caller_name, llvm::StringRef error_msg, Status &error, LLDBLog log_category=LLDBLog::Process)
template<typename T = StructuredData::ObjectSP>
static bool CheckStructuredDataObject (llvm::StringRef caller, T obj, Status &error)
static bool CreateInstance (lldb::ScriptLanguage language, ScriptedInterfaceUsages usages)
Private Member Functions
lldb::ScriptedThreadInterfaceSP CreateScriptedThreadInterface () override
Additional Inherited Members
Public Types inherited from lldb_private::ScriptedPythonInterface
enum class AbstractMethodCheckerCases {
eNotImplemented , eNotAllocated , eNotCallable , eUnknownArgumentCount ,
eInvalidArgumentCount , eValid
}
Protected Member Functions inherited from lldb_private::ScriptedPythonInterface
template<typename T = StructuredData::ObjectSP>
T ExtractValueFromPythonObject (python::PythonObject &p, Status &error)
template<typename T = StructuredData::ObjectSP, typename... Args>
T Dispatch (llvm::StringRef method_name, Status &error, Args &&...args)
template<typename... Args>
Status GetStatusFromMethod (llvm::StringRef method_name, Args &&...args)
template<typename T>
T Transform (T object)
python::PythonObject Transform (bool arg)
python::PythonObject Transform (const Status &arg)
python::PythonObject Transform (Status &&arg)
python::PythonObject Transform (const StructuredDataImpl &arg)
python::PythonObject Transform (lldb::ExecutionContextRefSP arg)
python::PythonObject Transform (lldb::TargetSP arg)
python::PythonObject Transform (lldb::BreakpointSP arg)
python::PythonObject Transform (lldb::BreakpointLocationSP arg)
python::PythonObject Transform (lldb::ProcessSP arg)
python::PythonObject Transform (lldb::ThreadSP arg)
python::PythonObject Transform (lldb::StackFrameListSP arg)
python::PythonObject Transform (lldb::ThreadPlanSP arg)
python::PythonObject Transform (lldb::ProcessAttachInfoSP arg)
python::PythonObject Transform (lldb::ProcessLaunchInfoSP arg)
python::PythonObject Transform (Event *arg)
python::PythonObject Transform (const SymbolContext &arg)
python::PythonObject Transform (lldb::StreamSP arg)
python::PythonObject Transform (lldb::StackFrameSP arg)
python::PythonObject Transform (lldb::DataExtractorSP arg)
python::PythonObject Transform (lldb::DescriptionLevel arg)
python::PythonObject Transform (lldb::ValueObjectSP arg)
template<typename T, typename U>
void ReverseTransform (T &original_arg, U transformed_arg, Status &error)
template<typename T>
void ReverseTransform (T &original_arg, python::PythonObject transformed_arg, Status &error)
void ReverseTransform (bool &original_arg, python::PythonObject transformed_arg, Status &error)
template<std::size_t... I, typename... Args>
auto TransformTuple (const std::tuple< Args... > &args, std::index_sequence< I... >)
template<typename... Args>
auto TransformArgs (const std::tuple< Args... > &args)
template<typename T, typename U>
void TransformBack (T &original_arg, U transformed_arg, Status &error)
template<std::size_t... I, typename... Ts, typename... Us>
bool ReassignPtrsOrRefsArgs (std::tuple< Ts... > &original_args, std::tuple< Us... > &transformed_args, std::index_sequence< I... >)
template<typename... Ts, typename... Us>
bool ReassignPtrsOrRefsArgs (std::tuple< Ts... > &original_args, std::tuple< Us... > &transformed_args)
template<typename T, typename... Args>
void FormatArgs (std::string &fmt, T arg, Args... args) const
template<typename T>
void FormatArgs (std::string &fmt, T arg) const
void FormatArgs (std::string &fmt) const
template<>
Status ExtractValueFromPythonObject (python::PythonObject &p, Status &error)
template<>
Event * ExtractValueFromPythonObject (python::PythonObject &p, Status &error)
template<>
SymbolContext ExtractValueFromPythonObject (python::PythonObject &p, Status &error)
template<>
Status ExtractValueFromPythonObject (python::PythonObject &p, Status &error)
template<>
Event * ExtractValueFromPythonObject (python::PythonObject &p, Status &error)
template<>
SymbolContext ExtractValueFromPythonObject (python::PythonObject &p, Status &error)
Protected Attributes inherited from lldb_private::ScriptedInterface
StructuredData::GenericSP m_object_instance_sp
Protected Attributes inherited from lldb_private::ScriptedPythonInterface
ScriptInterpreterPythonImpl & m_interpreter
Detailed Description
Definition at line 19 of file ScriptedProcessPythonInterface.h.
Constructor & Destructor Documentation
ScriptedProcessPythonInterface()
ScriptedProcessPythonInterface::ScriptedProcessPythonInterface (ScriptInterpreterPythonImpl & interpreter)
Definition at line 34 of file ScriptedProcessPythonInterface.cpp.
References lldb_private::ScriptedPythonInterface::ScriptedPythonInterface().
Member Function Documentation
Attach()
Status ScriptedProcessPythonInterface::Attach (const ProcessAttachInfo & attach_info) override virtual
Reimplemented from lldb_private::ScriptedProcessInterface.
Definition at line 62 of file ScriptedProcessPythonInterface.cpp.
References lldb_private::ScriptedPythonInterface::GetStatusFromMethod().
CreateBreakpoint()
bool ScriptedProcessPythonInterface::CreateBreakpoint (lldb::addr_t addr, Status & error) override virtual
Reimplemented from lldb_private::ScriptedProcessInterface.
Definition at line 103 of file ScriptedProcessPythonInterface.cpp.
References lldb_private::ScriptedInterface::CheckStructuredDataObject(), lldb_private::ScriptedPythonInterface::Dispatch(), error(), and lldb_private::Status::Fail().
CreatePluginObject()
llvm::Expected< StructuredData::GenericSP > ScriptedProcessPythonInterface::CreatePluginObject (const llvm::StringRef class_name, ExecutionContext & exe_ctx, StructuredData::DictionarySP args_sp, StructuredData::Generic * script_obj = nullptr) override virtual
Implements lldb_private::ScriptedProcessInterface.
Definition at line 39 of file ScriptedProcessPythonInterface.cpp.
References lldb_private::ScriptedPythonInterface::CreatePluginObject().
CreateScriptedThreadInterface()
lldb::ScriptedThreadInterfaceSP ScriptedProcessPythonInterface::CreateScriptedThreadInterface () override private virtual
Reimplemented from lldb_private::ScriptedProcessInterface.
Definition at line 197 of file ScriptedProcessPythonInterface.cpp.
References lldb_private::ScriptedPythonInterface::m_interpreter.
GetAbstractMethodRequirements()
llvm::SmallVector< AbstractMethodRequirement > lldb_private::ScriptedProcessPythonInterface::GetAbstractMethodRequirements () const inline override virtual
Implements lldb_private::ScriptedInterface.
Definition at line 32 of file ScriptedProcessPythonInterface.h.
GetCapabilities()
StructuredData::DictionarySP ScriptedProcessPythonInterface::GetCapabilities () override virtual
Reimplemented from lldb_private::ScriptedProcessInterface.
Definition at line 49 of file ScriptedProcessPythonInterface.cpp.
References lldb_private::ScriptedInterface::CheckStructuredDataObject(), lldb_private::ScriptedPythonInterface::Dispatch(), and error().
GetLoadedImages()
StructuredData::ArraySP ScriptedProcessPythonInterface::GetLoadedImages () override virtual
Reimplemented from lldb_private::ScriptedProcessInterface.
Definition at line 150 of file ScriptedProcessPythonInterface.cpp.
References lldb_private::ScriptedInterface::CheckStructuredDataObject(), lldb_private::ScriptedPythonInterface::Dispatch(), and error().
GetMemoryRegionContainingAddress()
std::optional< MemoryRegionInfo > ScriptedProcessPythonInterface::GetMemoryRegionContainingAddress (lldb::addr_t address, Status & error) override virtual
Reimplemented from lldb_private::ScriptedProcessInterface.
Definition at line 78 of file ScriptedProcessPythonInterface.cpp.
References lldb_private::ScriptedPythonInterface::Dispatch(), error(), and lldb_private::ScriptedInterface::ErrorWithMessage().
GetMetadata()
StructuredData::DictionarySP ScriptedProcessPythonInterface::GetMetadata () override virtual
Reimplemented from lldb_private::ScriptedProcessInterface.
Definition at line 201 of file ScriptedProcessPythonInterface.cpp.
References lldb_private::ScriptedInterface::CheckStructuredDataObject(), lldb_private::ScriptedPythonInterface::Dispatch(), and error().
GetPluginName()
llvm::StringRef lldb_private::ScriptedProcessPythonInterface::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 80 of file ScriptedProcessPythonInterface.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::ScriptedProcessPythonInterface::GetPluginNameStatic () inline static
Definition at line 76 of file ScriptedProcessPythonInterface.h.
Referenced by GetPluginName(), and Initialize().
GetProcessID()
lldb::pid_t ScriptedProcessPythonInterface::GetProcessID () override virtual
Reimplemented from lldb_private::ScriptedProcessInterface.
Definition at line 162 of file ScriptedProcessPythonInterface.cpp.
References lldb_private::ScriptedInterface::CheckStructuredDataObject(), lldb_private::ScriptedPythonInterface::Dispatch(), error(), and LLDB_INVALID_PROCESS_ID.
GetScriptedThreadPluginName()
std::optional< std::string > ScriptedProcessPythonInterface::GetScriptedThreadPluginName () override virtual
Reimplemented from lldb_private::ScriptedProcessInterface.
Definition at line 185 of file ScriptedProcessPythonInterface.cpp.
References lldb_private::ScriptedInterface::CheckStructuredDataObject(), lldb_private::ScriptedPythonInterface::Dispatch(), and error().
GetThreadsInfo()
StructuredData::DictionarySP ScriptedProcessPythonInterface::GetThreadsInfo () override virtual
Reimplemented from lldb_private::ScriptedProcessInterface.
Definition at line 91 of file ScriptedProcessPythonInterface.cpp.
References lldb_private::ScriptedInterface::CheckStructuredDataObject(), lldb_private::ScriptedPythonInterface::Dispatch(), and error().
Initialize()
void ScriptedProcessPythonInterface::Initialize () static
Definition at line 213 of file ScriptedProcessPythonInterface.cpp.
References lldb_private::ScriptedInterface::CreateInstance(), lldb::eScriptLanguagePython, GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Referenced by lldb_private::ScriptInterpreterPythonInterfaces::Initialize().
IsAlive()
bool ScriptedProcessPythonInterface::IsAlive () override virtual
Reimplemented from lldb_private::ScriptedProcessInterface.
Definition at line 173 of file ScriptedProcessPythonInterface.cpp.
References lldb_private::ScriptedInterface::CheckStructuredDataObject(), lldb_private::ScriptedPythonInterface::Dispatch(), and error().
Launch()
Status ScriptedProcessPythonInterface::Launch () override virtual
Reimplemented from lldb_private::ScriptedProcessInterface.
Definition at line 68 of file ScriptedProcessPythonInterface.cpp.
References lldb_private::ScriptedPythonInterface::GetStatusFromMethod().
ReadMemoryAtAddress()
lldb::DataExtractorSP ScriptedProcessPythonInterface::ReadMemoryAtAddress (lldb::addr_t address, size_t size, Status & error) override virtual
Reimplemented from lldb_private::ScriptedProcessInterface.
Definition at line 120 of file ScriptedProcessPythonInterface.cpp.
References lldb_private::ScriptedPythonInterface::Dispatch(), error(), and lldb_private::Status::Fail().
Resume()
Status ScriptedProcessPythonInterface::Resume () override virtual
Reimplemented from lldb_private::ScriptedProcessInterface.
Definition at line 72 of file ScriptedProcessPythonInterface.cpp.
References lldb_private::ScriptedPythonInterface::GetStatusFromMethod().
Terminate()
void ScriptedProcessPythonInterface::Terminate () static
Definition at line 229 of file ScriptedProcessPythonInterface.cpp.
References lldb_private::ScriptedInterface::CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Referenced by lldb_private::ScriptInterpreterPythonInterfaces::Terminate().
WriteMemoryAtAddress()
lldb::offset_t ScriptedProcessPythonInterface::WriteMemoryAtAddress (lldb::addr_t addr, lldb::DataExtractorSP data_sp, Status & error) override virtual
Reimplemented from lldb_private::ScriptedProcessInterface.
Definition at line 133 of file ScriptedProcessPythonInterface.cpp.
References lldb_private::ScriptedInterface::CheckStructuredDataObject(), lldb_private::ScriptedPythonInterface::Dispatch(), error(), lldb_private::Status::Fail(), and LLDB_INVALID_OFFSET.
The documentation for this class was generated from the following files:
ScriptedProcessPythonInterface.h
ScriptedProcessPythonInterface.cpp