LLDB: CFCMutableSet Class Reference
CFCMutableSet Class Reference
#include <CFCMutableSet.h>
Public Member Functions
CFCMutableSet (CFMutableSetRef s=NULL)
CFCMutableSet (const CFCMutableSet &rhs)
~CFCMutableSet () override
const CFCMutableSet & operator= (const CFCMutableSet &rhs)
CFIndex GetCount () const
CFIndex GetCountOfValue (const void *value) const
const void * GetValue (const void *value) const
const void * AddValue (const void *value, bool can_create)
void RemoveValue (const void *value)
void RemoveAllValues ()
Public Member Functions inherited from CFCReleaser< CFMutableSetRef >
CFCReleaser (CFMutableSetRef ptr=NULL)
virtual ~CFCReleaser ()
CFCReleaser & operator= (const CFCReleaser< CFMutableSetRef > &rhs)
CFMutableSetRef * ptr_address (bool enforce_null=true)
CFMutableSetRef get ()
void reset (CFMutableSetRef ptr=NULL)
CFMutableSetRef release ()
Detailed Description
Definition at line 14 of file CFCMutableSet.h.
Constructor & Destructor Documentation
CFCMutableSet() [1/2]
CFCMutableSet::CFCMutableSet (CFMutableSetRef s = NULL)
Definition at line 13 of file CFCMutableSet.cpp.
References CFCReleaser< CFMutableSetRef >::CFCReleaser().
Referenced by CFCMutableSet(), operator=(), and ~CFCMutableSet().
CFCMutableSet() [2/2]
CFCMutableSet::CFCMutableSet (const CFCMutableSet & rhs) default
References CFCMutableSet().
~CFCMutableSet()
CFCMutableSet::~CFCMutableSet () override default
References CFCMutableSet().
Member Function Documentation
AddValue()
const void * CFCMutableSet::AddValue (const void * value, bool can_create)
Definition at line 50 of file CFCMutableSet.cpp.
References CFCReleaser< CFMutableSetRef >::get(), and CFCReleaser< CFMutableSetRef >::reset().
GetCount()
CFIndex CFCMutableSet::GetCount () const
Definition at line 29 of file CFCMutableSet.cpp.
References CFCReleaser< CFMutableSetRef >::get().
GetCountOfValue()
CFIndex CFCMutableSet::GetCountOfValue (const void * value) const
Definition at line 36 of file CFCMutableSet.cpp.
References CFCReleaser< CFMutableSetRef >::get().
GetValue()
const void * CFCMutableSet::GetValue (const void * value) const
Definition at line 43 of file CFCMutableSet.cpp.
References CFCReleaser< CFMutableSetRef >::get().
operator=()
const CFCMutableSet & CFCMutableSet::operator= (const CFCMutableSet & rhs)
Definition at line 20 of file CFCMutableSet.cpp.
References CFCMutableSet().
RemoveAllValues()
void CFCMutableSet::RemoveAllValues ()
Definition at line 71 of file CFCMutableSet.cpp.
References CFCReleaser< CFMutableSetRef >::get().
RemoveValue()
void CFCMutableSet::RemoveValue (const void * value)
Definition at line 65 of file CFCMutableSet.cpp.
References CFCReleaser< CFMutableSetRef >::get().
The documentation for this class was generated from the following files:
CFCMutableSet.h
CFCMutableSet.cpp