LLDB: lldb_private::OptionValueProperties Class Reference
lldb_private::OptionValueProperties Class Reference
#include <OptionValueProperties.h>
Public Member Functions
OptionValueProperties ()=default
OptionValueProperties (llvm::StringRef name)
~OptionValueProperties () override=default
Type GetType () const override
void Clear () override
lldb::OptionValueSP DeepCopy (const lldb::OptionValueSP &new_parent) const override
Status SetValueFromString (llvm::StringRef value, VarSetOperationType op=eVarSetOperationAssign) override
void DumpValue (const ExecutionContext *exe_ctx, Stream &strm, uint32_t dump_mask) override
llvm::json::Value ToJSON (const ExecutionContext *exe_ctx) const override
llvm::StringRef GetName () const override
virtual Status DumpPropertyValue (const ExecutionContext *exe_ctx, Stream &strm, llvm::StringRef property_path, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllDescriptions (CommandInterpreter &interpreter, Stream &strm) const
void Apropos (llvm::StringRef keyword, std::vector< const Property * > &matching_properties) const
void Initialize (const PropertyCollectionDefinition &setting_definitions)
void SetExpectedPath (std::string path)
virtual size_t GetPropertyIndex (llvm::StringRef name) const
virtual const Property * GetProperty (llvm::StringRef name, const ExecutionContext *exe_ctx=nullptr) const
virtual const Property * GetPropertyAtIndex (size_t idx, const ExecutionContext *exe_ctx=nullptr) const
virtual const Property * GetPropertyAtPath (const ExecutionContext *exe_ctx, llvm::StringRef property_path) const
virtual lldb::OptionValueSP GetPropertyValueAtIndex (size_t idx, const ExecutionContext *exe_ctx) const
virtual lldb::OptionValueSP GetValueForKey (const ExecutionContext *exe_ctx, llvm::StringRef key) const
lldb::OptionValueSP GetSubValue (const ExecutionContext *exe_ctx, llvm::StringRef name, Status &error) const override
Status SetSubValue (const ExecutionContext *exe_ctx, VarSetOperationType op, llvm::StringRef path, llvm::StringRef value) override
bool GetPropertyAtIndexAsArgs (size_t idx, Args &args, const ExecutionContext *exe_ctx=nullptr) const
bool SetPropertyAtIndexFromArgs (size_t idx, const Args &args, const ExecutionContext *exe_ctx=nullptr)
OptionValueDictionary * GetPropertyAtIndexAsOptionValueDictionary (size_t idx, const ExecutionContext *exe_ctx=nullptr) const
OptionValueSInt64 * GetPropertyAtIndexAsOptionValueSInt64 (size_t idx, const ExecutionContext *exe_ctx=nullptr) const
OptionValueUInt64 * GetPropertyAtIndexAsOptionValueUInt64 (size_t idx, const ExecutionContext *exe_ctx=nullptr) const
OptionValueString * GetPropertyAtIndexAsOptionValueString (size_t idx, const ExecutionContext *exe_ctx=nullptr) const
OptionValueFileSpec * GetPropertyAtIndexAsOptionValueFileSpec (size_t idx, const ExecutionContext *exe_ctx=nullptr) const
OptionValuePathMappings * GetPropertyAtIndexAsOptionValuePathMappings (size_t idx, const ExecutionContext *exe_ctx=nullptr) const
OptionValueFileSpecList * GetPropertyAtIndexAsOptionValueFileSpecList (size_t idx, const ExecutionContext *exe_ctx=nullptr) const
void AppendProperty (llvm::StringRef name, llvm::StringRef desc, bool is_global, const lldb::OptionValueSP &value_sp)
lldb::OptionValuePropertiesSP GetSubProperty (const ExecutionContext *exe_ctx, llvm::StringRef name)
void SetValueChangedCallback (size_t property_idx, std::function< void()> callback)
template<typename T>
auto GetPropertyAtIndexAs (size_t idx, const ExecutionContext *exe_ctx=nullptr) const
template<typename T>
bool SetPropertyAtIndex (size_t idx, T t, const ExecutionContext *exe_ctx=nullptr) const
Public Member Functions inherited from lldb_private::Cloneable< OptionValueProperties, OptionValue >
std::shared_ptr< typename OptionValue::TopmostBase > Clone () const override
Public Member Functions inherited from lldb_private::OptionValue
OptionValue ()=default
virtual ~OptionValue ()=default
OptionValue (const OptionValue &other)
OptionValue & operator= (const OptionValue &other)
virtual bool ValueIsTransparent () const
virtual const char * GetTypeAsCString () const
virtual void AutoComplete (CommandInterpreter &interpreter, CompletionRequest &request)
virtual bool IsAggregateValue () const
virtual bool DumpQualifiedName (Stream &strm) const
uint32_t GetTypeAsMask ()
OptionValueArch * GetAsArch ()
const OptionValueArch * GetAsArch () const
OptionValueArray * GetAsArray ()
const OptionValueArray * GetAsArray () const
OptionValueArgs * GetAsArgs ()
const OptionValueArgs * GetAsArgs () const
OptionValueBoolean * GetAsBoolean ()
const OptionValueBoolean * GetAsBoolean () const
OptionValueChar * GetAsChar ()
const OptionValueChar * GetAsChar () const
OptionValueDictionary * GetAsDictionary ()
const OptionValueDictionary * GetAsDictionary () const
OptionValueEnumeration * GetAsEnumeration ()
const OptionValueEnumeration * GetAsEnumeration () const
OptionValueFileSpec * GetAsFileSpec ()
const OptionValueFileSpec * GetAsFileSpec () const
OptionValueFileSpecList * GetAsFileSpecList ()
const OptionValueFileSpecList * GetAsFileSpecList () const
OptionValueFormat * GetAsFormat ()
const OptionValueFormat * GetAsFormat () const
OptionValueLanguage * GetAsLanguage ()
const OptionValueLanguage * GetAsLanguage () const
OptionValuePathMappings * GetAsPathMappings ()
const OptionValuePathMappings * GetAsPathMappings () const
OptionValueProperties * GetAsProperties ()
const OptionValueProperties * GetAsProperties () const
OptionValueRegex * GetAsRegex ()
const OptionValueRegex * GetAsRegex () const
OptionValueSInt64 * GetAsSInt64 ()
const OptionValueSInt64 * GetAsSInt64 () const
OptionValueString * GetAsString ()
const OptionValueString * GetAsString () const
OptionValueUInt64 * GetAsUInt64 ()
const OptionValueUInt64 * GetAsUInt64 () const
OptionValueUUID * GetAsUUID ()
const OptionValueUUID * GetAsUUID () const
OptionValueFormatEntity * GetAsFormatEntity ()
const OptionValueFormatEntity * GetAsFormatEntity () const
bool AppendFileSpecValue (FileSpec file_spec)
bool OptionWasSet () const
void SetOptionWasSet ()
void SetParent (const lldb::OptionValueSP &parent_sp)
lldb::OptionValueSP GetParent () const
void SetValueChangedCallback (std::function< void()> callback)
void NotifyValueChanged ()
template<typename T, std::enable_if_t<!std::is_pointer_v< T >, bool > = true>
std::optional< T > GetValueAs () const
template<typename T, typename U = typename std::remove_const< typename std::remove_pointer<T>::type>::type, std::enable_if_t< std::is_pointer_v< T >, bool > = true>
T GetValueAs () const
bool SetValueAs (bool v)
bool SetValueAs (char v)
bool SetValueAs (uint64_t v)
bool SetValueAs (int64_t v)
bool SetValueAs (UUID v)
bool SetValueAs (llvm::StringRef v)
bool SetValueAs (lldb::LanguageType v)
bool SetValueAs (lldb::Format v)
bool SetValueAs (FileSpec v)
bool SetValueAs (ArchSpec v)
bool SetValueAs (const FormatEntity::Entry &v)
template<typename T, std::enable_if_t< std::is_enum_v< T >, bool > = true>
bool SetValueAs (T t)
Static Public Member Functions
static lldb::OptionValuePropertiesSP CreateLocalCopy (const Properties &global_properties)
Static Public Member Functions inherited from lldb_private::OptionValue
static const char * GetBuiltinTypeAsCString (Type t)
static uint32_t ConvertTypeToMask (OptionValue::Type type)
static OptionValue::Type ConvertTypeMaskToType (uint32_t type_mask)
static lldb::OptionValueSP CreateValueFromCStringForTypeMask (const char *value_cstr, uint32_t type_mask, Status &error)
Protected Member Functions
Property * ProtectedGetPropertyAtIndex (size_t idx)
const Property * ProtectedGetPropertyAtIndex (size_t idx) const
bool VerifyPath ()
Protected Attributes
std::string m_name
std::vector< Property > m_properties
llvm::StringMap< size_t > m_name_to_index
std::string m_expected_path
Protected Attributes inherited from lldb_private::OptionValue
lldb::OptionValueWP m_parent_wp
std::function< void()> m_callback
bool m_value_was_set = false
Additional Inherited Members
Public Types inherited from lldb_private::OptionValue
enum Type {
eTypeInvalid = 0 , eTypeArch , eTypeArgs , eTypeArray ,
eTypeBoolean , eTypeChar , eTypeDictionary , eTypeEnum ,
eTypeFileLineColumn , eTypeFileSpec , eTypeFileSpecList , eTypeFormat ,
eTypeLanguage , eTypePathMap , eTypeProperties , eTypeRegex ,
eTypeSInt64 , eTypeString , eTypeUInt64 , eTypeUUID ,
eTypeFormatEntity
}
enum {
eDumpOptionName = (1u << 0) , eDumpOptionType = (1u << 1) , eDumpOptionValue = (1u << 2) , eDumpOptionDescription = (1u << 3) ,
eDumpOptionRaw = (1u << 4) , eDumpOptionCommand = (1u << 5) , eDumpOptionDefaultValue = (1u << 6) , eDumpGroupValue = (eDumpOptionName | eDumpOptionType | eDumpOptionValue) ,
eDumpGroupHelp , eDumpGroupExport = (eDumpOptionCommand | eDumpOptionName | eDumpOptionValue)
}
Protected Types inherited from lldb_private::OptionValue
using TopmostBase = OptionValue
Detailed Description
Definition at line 22 of file OptionValueProperties.h.
Constructor & Destructor Documentation
OptionValueProperties() [1/2]
lldb_private::OptionValueProperties::OptionValueProperties () default
Referenced by AppendProperty(), Apropos(), DeepCopy(), GetPropertyAtPath(), GetSubProperty(), and VerifyPath().
OptionValueProperties() [2/2]
OptionValueProperties::OptionValueProperties (llvm::StringRef name)
Definition at line 23 of file OptionValueProperties.cpp.
References m_name.
~OptionValueProperties()
lldb_private::OptionValueProperties::~OptionValueProperties () override default
Member Function Documentation
AppendProperty()
void OptionValueProperties::AppendProperty (llvm::StringRef name, llvm::StringRef desc, bool is_global, const lldb::OptionValueSP & value_sp)
Definition at line 50 of file OptionValueProperties.cpp.
References m_name_to_index, m_properties, OptionValueProperties(), and VerifyPath().
Apropos()
void OptionValueProperties::Apropos (llvm::StringRef keyword, std::vector< const Property * > & matching_properties) const
Definition at line 467 of file OptionValueProperties.cpp.
References Apropos(), m_properties, OptionValueProperties(), and ProtectedGetPropertyAtIndex().
Referenced by Apropos().
Clear()
void OptionValueProperties::Clear () override virtual
Implements lldb_private::OptionValue.
Definition at line 306 of file OptionValueProperties.cpp.
References m_properties.
Referenced by SetValueFromString().
CreateLocalCopy()
OptionValuePropertiesSP OptionValueProperties::CreateLocalCopy (const Properties & global_properties) static
Definition at line 394 of file OptionValueProperties.cpp.
References lldb_private::Properties::GetValueProperties(), and lldbassert.
Referenced by lldb_private::ProcessProperties::ProcessProperties(), lldb_private::TargetProperties::TargetProperties(), and lldb_private::ThreadProperties::ThreadProperties().
DeepCopy()
OptionValueSP OptionValueProperties::DeepCopy (const lldb::OptionValueSP & new_parent) const override virtual
Reimplemented from lldb_private::OptionValue.
Definition at line 403 of file OptionValueProperties.cpp.
References lldb_private::OptionValue::DeepCopy(), lldbassert, and OptionValueProperties().
DumpAllDescriptions()
void OptionValueProperties::DumpAllDescriptions (CommandInterpreter & interpreter, Stream & strm) const virtual
Definition at line 451 of file OptionValueProperties.cpp.
References m_properties, and ProtectedGetPropertyAtIndex().
Referenced by lldb_private::Property::DumpDescription().
DumpPropertyValue()
Status OptionValueProperties::DumpPropertyValue (const ExecutionContext * exe_ctx, Stream & strm, llvm::StringRef property_path, uint32_t dump_mask, bool is_json = false) virtual
Definition at line 369 of file OptionValueProperties.cpp.
References lldb_private::OptionValue::eDumpOptionName, error(), GetSubValue(), lldb_private::Stream::Printf(), lldb_private::Stream::PutChar(), and lldb_private::Stream::PutCString().
DumpValue()
void OptionValueProperties::DumpValue (const ExecutionContext * exe_ctx, Stream & strm, uint32_t dump_mask) override virtual
Implements lldb_private::OptionValue.
Definition at line 337 of file OptionValueProperties.cpp.
References lldb_private::Stream::EOL(), GetPropertyAtIndex(), m_properties, and lldb_private::OptionValue::ValueIsTransparent().
GetName()
llvm::StringRef lldb_private::OptionValueProperties::GetName () const inline override virtual
Reimplemented from lldb_private::OptionValue.
Definition at line 51 of file OptionValueProperties.h.
References m_name.
Referenced by VerifyPath().
GetProperty()
const Property * OptionValueProperties::GetProperty (llvm::StringRef name, const ExecutionContext * exe_ctx = nullptr) const virtual
Definition at line 165 of file OptionValueProperties.cpp.
References GetPropertyAtIndex(), and m_name_to_index.
Referenced by GetPropertyAtPath().
GetPropertyAtIndex()
virtual const Property * lldb_private::OptionValueProperties::GetPropertyAtIndex (size_t idx, const ExecutionContext * exe_ctx = nullptr) const inline virtual
Reimplemented in ProcessOptionValueProperties, TargetOptionValueProperties, and ThreadOptionValueProperties.
Definition at line 82 of file OptionValueProperties.h.
References ProtectedGetPropertyAtIndex().
Referenced by DumpValue(), GetProperty(), GetPropertyAtIndexAs(), GetPropertyAtIndexAsArgs(), GetPropertyAtIndexAsOptionValueDictionary(), GetPropertyAtIndexAsOptionValueFileSpec(), GetPropertyAtIndexAsOptionValueSInt64(), GetPropertyAtIndexAsOptionValueUInt64(), GetPropertyValueAtIndex(), GetValueForKey(), SetPropertyAtIndex(), SetPropertyAtIndexFromArgs(), and ToJSON().
GetPropertyAtIndexAs()
template<typename T> auto lldb_private::OptionValueProperties::GetPropertyAtIndexAs (size_t idx, const ExecutionContext * exe_ctx = nullptr) const inline
Definition at line 144 of file OptionValueProperties.h.
References GetPropertyAtIndex().
Referenced by lldb_private::TargetProperties::GetExperimentalPropertyValue(), lldb_private::ProcessProperties::GetOSPluginReportsAllThreads(), and lldb_private::TargetProperties::GetUseDIL().
GetPropertyAtIndexAsArgs()
bool OptionValueProperties::GetPropertyAtIndexAsArgs (size_t idx, Args & args, const ExecutionContext * exe_ctx = nullptr) const
Definition at line 199 of file OptionValueProperties.cpp.
References lldb_private::OptionValueArgs::GetArgs(), lldb_private::OptionValueArray::GetArgs(), lldb_private::OptionValueDictionary::GetArgs(), lldb_private::OptionValue::GetAsArgs(), lldb_private::OptionValue::GetAsArray(), lldb_private::OptionValue::GetAsDictionary(), and GetPropertyAtIndex().
GetPropertyAtIndexAsOptionValueDictionary()
OptionValueDictionary * OptionValueProperties::GetPropertyAtIndexAsOptionValueDictionary (size_t idx, const ExecutionContext * exe_ctx = nullptr) const
Definition at line 256 of file OptionValueProperties.cpp.
References GetPropertyAtIndex().
GetPropertyAtIndexAsOptionValueFileSpec()
OptionValueFileSpec * OptionValueProperties::GetPropertyAtIndexAsOptionValueFileSpec (size_t idx, const ExecutionContext * exe_ctx = nullptr) const
Definition at line 265 of file OptionValueProperties.cpp.
References lldb_private::OptionValue::GetAsFileSpec(), and GetPropertyAtIndex().
GetPropertyAtIndexAsOptionValueFileSpecList()
OptionValueFileSpecList * OptionValueProperties::GetPropertyAtIndexAsOptionValueFileSpecList (size_t idx, const ExecutionContext * exe_ctx = nullptr) const
Definition at line 191 of file OptionValueProperties.cpp.
References GetPropertyValueAtIndex().
GetPropertyAtIndexAsOptionValuePathMappings()
OptionValuePathMappings * OptionValueProperties::GetPropertyAtIndexAsOptionValuePathMappings (size_t idx, const ExecutionContext * exe_ctx = nullptr) const
Definition at line 182 of file OptionValueProperties.cpp.
References GetPropertyValueAtIndex().
GetPropertyAtIndexAsOptionValueSInt64()
OptionValueSInt64 * OptionValueProperties::GetPropertyAtIndexAsOptionValueSInt64 (size_t idx, const ExecutionContext * exe_ctx = nullptr) const
Definition at line 276 of file OptionValueProperties.cpp.
References lldb_private::OptionValue::GetAsSInt64(), and GetPropertyAtIndex().
GetPropertyAtIndexAsOptionValueString()
OptionValueString * OptionValueProperties::GetPropertyAtIndexAsOptionValueString (size_t idx, const ExecutionContext * exe_ctx = nullptr) const
Definition at line 298 of file OptionValueProperties.cpp.
References GetPropertyValueAtIndex().
GetPropertyAtIndexAsOptionValueUInt64()
OptionValueUInt64 * OptionValueProperties::GetPropertyAtIndexAsOptionValueUInt64 (size_t idx, const ExecutionContext * exe_ctx = nullptr) const
Definition at line 287 of file OptionValueProperties.cpp.
References lldb_private::OptionValue::GetAsUInt64(), and GetPropertyAtIndex().
GetPropertyAtPath()
const Property * OptionValueProperties::GetPropertyAtPath (const ExecutionContext * exe_ctx, llvm::StringRef property_path) const virtual
Definition at line 422 of file OptionValueProperties.cpp.
References GetProperty(), GetPropertyAtPath(), and OptionValueProperties().
Referenced by GetPropertyAtPath().
GetPropertyIndex()
size_t OptionValueProperties::GetPropertyIndex (llvm::StringRef name) const virtual
Definition at line 157 of file OptionValueProperties.cpp.
References m_name_to_index.
GetPropertyValueAtIndex()
lldb::OptionValueSP OptionValueProperties::GetPropertyValueAtIndex (size_t idx, const ExecutionContext * exe_ctx) const virtual
Definition at line 173 of file OptionValueProperties.cpp.
References GetPropertyAtIndex(), and lldb_private::Property::GetValue().
Referenced by GetPropertyAtIndexAsOptionValueFileSpecList(), GetPropertyAtIndexAsOptionValuePathMappings(), and GetPropertyAtIndexAsOptionValueString().
GetSubProperty()
lldb::OptionValuePropertiesSP OptionValueProperties::GetSubProperty (const ExecutionContext * exe_ctx, llvm::StringRef name)
Definition at line 498 of file OptionValueProperties.cpp.
References GetValueForKey(), and OptionValueProperties().
GetSubValue()
lldb::OptionValueSP OptionValueProperties::GetSubValue (const ExecutionContext * exe_ctx, llvm::StringRef name, Status & error) const override virtual
Reimplemented from lldb_private::OptionValue.
Definition at line 81 of file OptionValueProperties.cpp.
References error(), lldb_private::Properties::GetExperimentalSettingsName(), GetValueForKey(), and lldb_private::Properties::IsSettingExperimental().
Referenced by DumpPropertyValue(), and SetSubValue().
GetType()
Type lldb_private::OptionValueProperties::GetType () const inline override virtual
Implements lldb_private::OptionValue.
Definition at line 32 of file OptionValueProperties.h.
References lldb_private::OptionValue::eTypeProperties.
GetValueForKey()
lldb::OptionValueSP OptionValueProperties::GetValueForKey (const ExecutionContext * exe_ctx, llvm::StringRef key) const virtual
Definition at line 69 of file OptionValueProperties.cpp.
References GetPropertyAtIndex(), lldb_private::Property::GetValue(), m_name_to_index, and m_properties.
Referenced by GetSubProperty(), and GetSubValue().
Initialize()
void OptionValueProperties::Initialize (const PropertyCollectionDefinition & setting_definitions)
Definition at line 26 of file OptionValueProperties.cpp.
References lldb_private::PropertyCollectionDefinition::definitions, lldb_private::PropertyCollectionDefinition::expected_path, lldb_private::Property::IsValid(), m_name_to_index, m_properties, and SetExpectedPath().
ProtectedGetPropertyAtIndex() [1/2]
Property * lldb_private::OptionValueProperties::ProtectedGetPropertyAtIndex (size_t idx) inline protected
Definition at line 169 of file OptionValueProperties.h.
References m_properties.
Referenced by Apropos(), DumpAllDescriptions(), GetPropertyAtIndex(), ProcessOptionValueProperties::GetPropertyAtIndex(), TargetOptionValueProperties::GetPropertyAtIndex(), ThreadOptionValueProperties::GetPropertyAtIndex(), and SetValueChangedCallback().
ProtectedGetPropertyAtIndex() [2/2]
const Property * lldb_private::OptionValueProperties::ProtectedGetPropertyAtIndex (size_t idx) const inline protected
Definition at line 174 of file OptionValueProperties.h.
References m_properties.
SetExpectedPath()
void OptionValueProperties::SetExpectedPath (std::string path)
Definition at line 38 of file OptionValueProperties.cpp.
References m_expected_path.
Referenced by Initialize().
SetPropertyAtIndex()
template<typename T> bool lldb_private::OptionValueProperties::SetPropertyAtIndex (size_t idx, T t, const ExecutionContext * exe_ctx = nullptr) const inline
Definition at line 157 of file OptionValueProperties.h.
References GetPropertyAtIndex().
Referenced by lldb_private::ProcessProperties::SetOSPluginReportsAllThreads(), and lldb_private::TargetProperties::SetUseDIL().
SetPropertyAtIndexFromArgs()
bool OptionValueProperties::SetPropertyAtIndexFromArgs (size_t idx, const Args & args, const ExecutionContext * exe_ctx = nullptr)
Definition at line 230 of file OptionValueProperties.cpp.
References lldb_private::eVarSetOperationAssign, lldb_private::OptionValue::GetAsArgs(), lldb_private::OptionValue::GetAsArray(), lldb_private::OptionValue::GetAsDictionary(), GetPropertyAtIndex(), lldb_private::OptionValueArray::SetArgs(), lldb_private::OptionValueDictionary::SetArgs(), and lldb_private::Status::Success().
SetSubValue()
Status OptionValueProperties::SetSubValue (const ExecutionContext * exe_ctx, VarSetOperationType op, llvm::StringRef path, llvm::StringRef value) override virtual
Reimplemented from lldb_private::OptionValue.
Definition at line 131 of file OptionValueProperties.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormat(), GetSubValue(), and lldb_private::Properties::IsSettingExperimental().
SetValueChangedCallback()
void OptionValueProperties::SetValueChangedCallback (size_t property_idx, std::function< void()> callback)
Definition at line 43 of file OptionValueProperties.cpp.
References ProtectedGetPropertyAtIndex().
SetValueFromString()
Status OptionValueProperties::SetValueFromString (llvm::StringRef value, VarSetOperationType op = eVarSetOperationAssign) override virtual
Reimplemented from lldb_private::OptionValue.
Definition at line 312 of file OptionValueProperties.cpp.
References Clear(), error(), lldb_private::eVarSetOperationAppend, lldb_private::eVarSetOperationAssign, lldb_private::eVarSetOperationClear, lldb_private::eVarSetOperationInsertAfter, lldb_private::eVarSetOperationInsertBefore, lldb_private::eVarSetOperationInvalid, lldb_private::eVarSetOperationRemove, lldb_private::eVarSetOperationReplace, and lldb_private::OptionValue::SetValueFromString().
ToJSON()
llvm::json::Value OptionValueProperties::ToJSON (const ExecutionContext * exe_ctx) const override virtual
Implements lldb_private::OptionValue.
Definition at line 354 of file OptionValueProperties.cpp.
References GetPropertyAtIndex(), m_properties, and lldb_private::OptionValue::ToJSON().
VerifyPath()
bool OptionValueProperties::VerifyPath () protected
Definition at line 509 of file OptionValueProperties.cpp.
References GetName(), lldb_private::OptionValue::GetParent(), m_expected_path, and OptionValueProperties().
Referenced by AppendProperty().
Member Data Documentation
m_expected_path
std::string lldb_private::OptionValueProperties::m_expected_path protected
Definition at line 184 of file OptionValueProperties.h.
Referenced by SetExpectedPath(), and VerifyPath().
m_name
std::string lldb_private::OptionValueProperties::m_name protected
Definition at line 181 of file OptionValueProperties.h.
Referenced by GetName(), and OptionValueProperties().
m_name_to_index
llvm::StringMap<size_t> lldb_private::OptionValueProperties::m_name_to_index protected
Definition at line 183 of file OptionValueProperties.h.
Referenced by AppendProperty(), GetProperty(), GetPropertyIndex(), GetValueForKey(), and Initialize().
m_properties
std::vector<Property> lldb_private::OptionValueProperties::m_properties protected
Definition at line 182 of file OptionValueProperties.h.
Referenced by AppendProperty(), Apropos(), Clear(), DumpAllDescriptions(), DumpValue(), GetValueForKey(), Initialize(), ProtectedGetPropertyAtIndex(), ProtectedGetPropertyAtIndex(), and ToJSON().
The documentation for this class was generated from the following files:
OptionValueProperties.h
OptionValueProperties.cpp