LLDB: lldb_private::StopInfo Class Reference
lldb_private::StopInfo Class Reference abstract
#include <StopInfo.h>
Public Member Functions
StopInfo (Thread &thread, uint64_t value)
virtual ~StopInfo ()=default
bool IsValid () const
void SetThread (const lldb::ThreadSP &thread_sp)
lldb::ThreadSP GetThread () const
uint64_t GetValue () const
virtual lldb::StopReason GetStopReason () const =0
virtual bool ShouldStopSynchronous (Event *event_ptr)
void OverrideShouldNotify (bool override_value)
virtual bool ShouldNotify (Event *event_ptr)
virtual void WillResume (lldb::StateType resume_state)
virtual const char * GetDescription ()
virtual void SetDescription (const char *desc_cstr)
virtual std::optional< uint32_t > GetSuggestedStackFrameIndex (bool inlined_stack)
This gives the StopInfo a chance to suggest a stack frame to select.
virtual bool IsValidForOperatingSystemThread (Thread &thread)
virtual bool WasContinueInterrupted (Thread &thread)
A Continue operation can result in a false stop event before any execution has happened.
virtual uint32_t GetStopReasonDataCount () const
virtual uint64_t GetStopReasonDataAtIndex (uint32_t idx)
void OverrideShouldStop (bool override_value)
bool GetOverrideShouldStop ()
bool GetOverriddenShouldStopValue ()
StructuredData::ObjectSP GetExtendedInfo ()
virtual bool ShouldShow () const
Returns true if this is a stop reason that should be shown to a user when viewing the thread with this stop info.
virtual bool ShouldSelect () const
Returns true if this is a stop reason that should cause a thread to be selected when stopping.
Static Public Member Functions
static lldb::StopInfoSP CreateStopReasonWithBreakpointSiteID (Thread &thread, lldb::break_id_t break_id)
static lldb::StopInfoSP CreateStopReasonWithBreakpointSiteID (Thread &thread, lldb::break_id_t break_id, bool should_stop)
static lldb::StopInfoSP CreateStopReasonWithWatchpointID (Thread &thread, lldb::break_id_t watch_id, bool silently_continue=false)
static lldb::StopInfoSP CreateStopReasonWithSignal (Thread &thread, int signo, const char *description=nullptr, std::optional< int > code=std::nullopt)
static lldb::StopInfoSP CreateStopReasonWithInterrupt (Thread &thread, int signo, const char *description)
static lldb::StopInfoSP CreateStopReasonToTrace (Thread &thread)
static lldb::StopInfoSP CreateStopReasonWithPlan (lldb::ThreadPlanSP &plan, lldb::ValueObjectSP return_valobj_sp, lldb::ExpressionVariableSP expression_variable_sp)
static lldb::StopInfoSP CreateStopReasonWithException (Thread &thread, const char *description)
static lldb::StopInfoSP CreateStopReasonWithExec (Thread &thread)
static lldb::StopInfoSP CreateStopReasonProcessorTrace (Thread &thread, const char *description)
static lldb::StopInfoSP CreateStopReasonHistoryBoundary (Thread &thread, const char *description)
static lldb::StopInfoSP CreateStopReasonFork (Thread &thread, lldb::pid_t child_pid, lldb::tid_t child_tid)
static lldb::StopInfoSP CreateStopReasonVFork (Thread &thread, lldb::pid_t child_pid, lldb::tid_t child_tid)
static lldb::StopInfoSP CreateStopReasonVForkDone (Thread &thread)
static lldb::ValueObjectSP GetReturnValueObject (lldb::StopInfoSP &stop_info_sp)
static lldb::ExpressionVariableSP GetExpressionVariable (lldb::StopInfoSP &stop_info_sp)
static lldb::ValueObjectSP GetCrashingDereference (lldb::StopInfoSP &stop_info_sp, lldb::addr_t *crashing_address=nullptr)
Protected Member Functions
virtual void PerformAction (Event *event_ptr)
virtual bool DoShouldNotify (Event *event_ptr)
virtual bool ShouldStop (Event *event_ptr)
bool HasTargetRunSinceMe ()
void MakeStopInfoValid ()
Protected Attributes
lldb::ThreadWP m_thread_wp
uint32_t m_stop_id
uint32_t m_resume_id
uint64_t m_value
std::string m_description
LazyBool m_override_should_notify
LazyBool m_override_should_stop
StructuredData::ObjectSP m_extended_info
Private Member Functions
StopInfo (const StopInfo &)=delete
const StopInfo & operator= (const StopInfo &)=delete
Friends
class Process::ProcessEventData
class ThreadPlanBase
class ThreadPlanReverseContinue
class Thread
Detailed Description
Definition at line 20 of file StopInfo.h.
Constructor & Destructor Documentation
StopInfo() [1/2]
StopInfo::StopInfo (Thread & thread, uint64_t value)
Definition at line 34 of file StopInfo.cpp.
References lldb_private::eLazyBoolCalculate, m_description, m_extended_info, m_override_should_notify, m_override_should_stop, m_resume_id, m_stop_id, m_thread_wp, m_value, and Thread.
Referenced by InstrumentationBoundsSafetyStopInfo::InstrumentationBoundsSafetyStopInfo(), lldb_private::InstrumentationRuntimeStopInfo::InstrumentationRuntimeStopInfo(), operator=(), StopInfo(), lldb_private::StopInfoBreakpoint::StopInfoBreakpoint(), lldb_private::StopInfoBreakpoint::StopInfoBreakpoint(), lldb_private::StopInfoException::StopInfoException(), lldb_private::StopInfoExec::StopInfoExec(), lldb_private::StopInfoFork::StopInfoFork(), lldb_private::StopInfoHistoryBoundary::StopInfoHistoryBoundary(), lldb_private::StopInfoInterrupt::StopInfoInterrupt(), lldb_private::StopInfoMachException::StopInfoMachException(), lldb_private::StopInfoProcessorTrace::StopInfoProcessorTrace(), lldb_private::StopInfoThreadPlan::StopInfoThreadPlan(), lldb_private::StopInfoTrace::StopInfoTrace(), lldb_private::StopInfoUnixSignal::StopInfoUnixSignal(), lldb_private::StopInfoVFork::StopInfoVFork(), lldb_private::StopInfoVForkDone::StopInfoVForkDone(), and lldb_private::StopInfoWatchpoint::StopInfoWatchpoint().
~StopInfo()
virtual lldb_private::StopInfo::~StopInfo () virtual default
StopInfo() [2/2]
lldb_private::StopInfo::StopInfo (const StopInfo &) private delete
References StopInfo().
Member Function Documentation
CreateStopReasonFork()
StopInfoSP StopInfo::CreateStopReasonFork (Thread & thread, lldb::pid_t child_pid, lldb::tid_t child_tid) static
Definition at line 1650 of file StopInfo.cpp.
References Thread.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo().
CreateStopReasonHistoryBoundary()
StopInfoSP StopInfo::CreateStopReasonHistoryBoundary (Thread & thread, const char * description) static
Definition at line 1641 of file StopInfo.cpp.
References Thread.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo().
CreateStopReasonProcessorTrace()
StopInfoSP StopInfo::CreateStopReasonProcessorTrace (Thread & thread, const char * description) static
Definition at line 1636 of file StopInfo.cpp.
References Thread.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo().
CreateStopReasonToTrace()
StopInfoSP StopInfo::CreateStopReasonToTrace (Thread & thread) static
Definition at line 1620 of file StopInfo.cpp.
References Thread.
Referenced by lldb_private::ScriptedThread::CalculateStopInfo(), lldb_private::StopInfoMachException::CreateStopReasonWithMachException(), lldb_private::ThreadPlanStepInRange::DoWillResume(), lldb_private::ProcessWindows::RefreshStateAfterStop(), and lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo().
CreateStopReasonVFork()
StopInfoSP StopInfo::CreateStopReasonVFork (Thread & thread, lldb::pid_t child_pid, lldb::tid_t child_tid) static
Definition at line 1657 of file StopInfo.cpp.
References Thread.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo().
CreateStopReasonVForkDone()
StopInfoSP StopInfo::CreateStopReasonVForkDone (Thread & thread) static
Definition at line 1663 of file StopInfo.cpp.
References Thread.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo().
CreateStopReasonWithBreakpointSiteID() [1/2]
lldb::StopInfoSP lldb_private::StopInfo::CreateStopReasonWithBreakpointSiteID (Thread & thread, lldb::break_id_t break_id) static
References Thread.
Referenced by lldb_private::ScriptedThread::CalculateStopInfo(), lldb_private::StopInfoMachException::CreateStopReasonWithMachException(), lldb_private::ProcessWindows::RefreshStateAfterStop(), and lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo().
CreateStopReasonWithBreakpointSiteID() [2/2]
lldb::StopInfoSP lldb_private::StopInfo::CreateStopReasonWithBreakpointSiteID (Thread & thread, lldb::break_id_t break_id, bool should_stop) static
References Thread.
CreateStopReasonWithException()
StopInfoSP StopInfo::CreateStopReasonWithException (Thread & thread, const char * description) static
Definition at line 1631 of file StopInfo.cpp.
References Thread.
Referenced by lldb_private::ScriptedThread::CalculateStopInfo(), ThreadFreeBSDKernelCore::CalculateStopInfo(), ThreadMachCore::CalculateStopInfo(), lldb_private::minidump::ProcessMinidump::RefreshStateAfterStop(), lldb_private::ProcessWindows::RefreshStateAfterStop(), and lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo().
CreateStopReasonWithExec()
StopInfoSP StopInfo::CreateStopReasonWithExec (Thread & thread) static
Definition at line 1646 of file StopInfo.cpp.
References Thread.
Referenced by lldb_private::StopInfoMachException::CreateStopReasonWithMachException(), and lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo().
CreateStopReasonWithInterrupt()
StopInfoSP StopInfo::CreateStopReasonWithInterrupt (Thread & thread, int signo, const char * description) static
Definition at line 1615 of file StopInfo.cpp.
References Thread.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::HandleThreadAsyncInterrupt().
CreateStopReasonWithPlan()
StopInfoSP StopInfo::CreateStopReasonWithPlan (lldb::ThreadPlanSP & plan, lldb::ValueObjectSP return_valobj_sp, lldb::ExpressionVariableSP expression_variable_sp) static
Definition at line 1624 of file StopInfo.cpp.
Referenced by lldb_private::Thread::GetStopInfo().
CreateStopReasonWithSignal()
StopInfoSP StopInfo::CreateStopReasonWithSignal (Thread & thread, int signo, const char * description = nullptr, std::optional< int > code = std::nullopt) static
Definition at line 1608 of file StopInfo.cpp.
References Thread.
Referenced by lldb_private::ScriptedThread::CalculateStopInfo(), ThreadElfCore::CalculateStopInfo(), ThreadKDP::CalculateStopInfo(), lldb_private::StopInfoMachException::CreateStopReasonWithMachException(), lldb_private::platform_linux::PlatformLinux::GetStopInfoFromSiginfo(), lldb_private::minidump::ProcessMinidump::RefreshStateAfterStop(), lldb_private::Thread::SetStopInfoToNothing(), and lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo().
CreateStopReasonWithWatchpointID()
StopInfoSP StopInfo::CreateStopReasonWithWatchpointID (Thread & thread, lldb::break_id_t watch_id, bool silently_continue = false) static
Definition at line 1601 of file StopInfo.cpp.
References Thread.
Referenced by lldb_private::StopInfoMachException::CreateStopReasonWithMachException(), lldb_private::ProcessWindows::RefreshStateAfterStop(), and lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo().
DoShouldNotify()
virtual bool lldb_private::StopInfo::DoShouldNotify (Event * event_ptr) inline protected virtual
Reimplemented in InstrumentationBoundsSafetyStopInfo, lldb_private::InstrumentationRuntimeStopInfo, lldb_private::StopInfoBreakpoint, and lldb_private::StopInfoUnixSignal.
Definition at line 210 of file StopInfo.h.
Referenced by ShouldNotify().
GetCrashingDereference()
lldb::ValueObjectSP StopInfo::GetCrashingDereference (lldb::StopInfoSP & stop_info_sp, lldb::addr_t * crashing_address = nullptr) static
Definition at line 1688 of file StopInfo.cpp.
References DoNoSelectMostRelevantFrame.
Referenced by CommandObjectFrameDiagnose::DoExecute(), and lldb_private::Process::HandleProcessStateChangedEvent().
GetDescription()
virtual const char * lldb_private::StopInfo::GetDescription () inline virtual
Reimplemented in InstrumentationBoundsSafetyStopInfo, lldb_private::InstrumentationRuntimeStopInfo, lldb_private::StopInfoBreakpoint, lldb_private::StopInfoException, lldb_private::StopInfoExec, lldb_private::StopInfoFork, lldb_private::StopInfoHistoryBoundary, lldb_private::StopInfoInterrupt, lldb_private::StopInfoMachException, lldb_private::StopInfoProcessorTrace, lldb_private::StopInfoThreadPlan, lldb_private::StopInfoTrace, lldb_private::StopInfoUnixSignal, lldb_private::StopInfoVFork, lldb_private::StopInfoVForkDone, and lldb_private::StopInfoWatchpoint.
Definition at line 72 of file StopInfo.h.
References m_description.
GetExpressionVariable()
ExpressionVariableSP StopInfo::GetExpressionVariable (lldb::StopInfoSP & stop_info_sp) static
Definition at line 1677 of file StopInfo.cpp.
References lldb::eStopReasonPlanComplete, and lldb_private::StopInfoThreadPlan::GetExpressionVariable().
Referenced by lldb_private::FormatEntity::Formatter::Format().
GetExtendedInfo()
StructuredData::ObjectSP lldb_private::StopInfo::GetExtendedInfo () inline
Definition at line 125 of file StopInfo.h.
References m_extended_info.
GetOverriddenShouldStopValue()
bool lldb_private::StopInfo::GetOverriddenShouldStopValue () inline
Definition at line 121 of file StopInfo.h.
References lldb_private::eLazyBoolYes, and m_override_should_stop.
GetOverrideShouldStop()
bool lldb_private::StopInfo::GetOverrideShouldStop () inline
Definition at line 117 of file StopInfo.h.
References lldb_private::eLazyBoolCalculate, and m_override_should_stop.
GetReturnValueObject()
ValueObjectSP StopInfo::GetReturnValueObject (lldb::StopInfoSP & stop_info_sp) static
Definition at line 1667 of file StopInfo.cpp.
References lldb::eStopReasonPlanComplete, and lldb_private::StopInfoThreadPlan::GetReturnValueObject().
Referenced by lldb_private::FormatEntity::Formatter::Format(), and lldb::SBThread::GetStopReturnValue().
GetStopReason()
virtual lldb::StopReason lldb_private::StopInfo::GetStopReason () const pure virtual
Implemented in InstrumentationBoundsSafetyStopInfo, lldb_private::InstrumentationRuntimeStopInfo, lldb_private::StopInfoBreakpoint, lldb_private::StopInfoException, lldb_private::StopInfoExec, lldb_private::StopInfoFork, lldb_private::StopInfoHistoryBoundary, lldb_private::StopInfoInterrupt, lldb_private::StopInfoMachException, lldb_private::StopInfoProcessorTrace, lldb_private::StopInfoThreadPlan, lldb_private::StopInfoTrace, lldb_private::StopInfoUnixSignal, lldb_private::StopInfoVFork, lldb_private::StopInfoVForkDone, and lldb_private::StopInfoWatchpoint.
Referenced by ShouldSelect().
GetStopReasonDataAtIndex()
virtual uint64_t lldb_private::StopInfo::GetStopReasonDataAtIndex (uint32_t idx) inline virtual
Reimplemented in lldb_private::StopInfoBreakpoint, lldb_private::StopInfoException, lldb_private::StopInfoFork, lldb_private::StopInfoInterrupt, lldb_private::StopInfoMachException, lldb_private::StopInfoUnixSignal, lldb_private::StopInfoVFork, and lldb_private::StopInfoWatchpoint.
Definition at line 101 of file StopInfo.h.
GetStopReasonDataCount()
virtual uint32_t lldb_private::StopInfo::GetStopReasonDataCount () const inline virtual
Reimplemented in lldb_private::StopInfoBreakpoint, lldb_private::StopInfoException, lldb_private::StopInfoFork, lldb_private::StopInfoInterrupt, lldb_private::StopInfoMachException, lldb_private::StopInfoUnixSignal, lldb_private::StopInfoVFork, and lldb_private::StopInfoWatchpoint.
Definition at line 100 of file StopInfo.h.
GetSuggestedStackFrameIndex()
virtual std::optional< uint32_t > lldb_private::StopInfo::GetSuggestedStackFrameIndex (bool inlined_stack) inline virtual
This gives the StopInfo a chance to suggest a stack frame to select.
Passing true for inlined_stack will request changes to the inlined call stack. Passing false will request changes to the real stack frame. The inlined stack gets adjusted before we call into the thread plans so they can reason based on the correct values. The real stack adjustment is handled after the frame recognizers get a chance to adjust the frame.
Reimplemented in InstrumentationBoundsSafetyStopInfo, lldb_private::InstrumentationRuntimeStopInfo, lldb_private::StopInfoBreakpoint, and lldb_private::StopInfoTrace.
Definition at line 89 of file StopInfo.h.
GetThread()
lldb::ThreadSP lldb_private::StopInfo::GetThread () const inline
Definition at line 35 of file StopInfo.h.
References m_thread_wp.
Referenced by InstrumentationBoundsSafetyStopInfo::ComputeStopReasonAndSuggestedStackFrame(), lldb_private::StopInfoBreakpoint::GetBreakpointSiteSP(), lldb_private::InstrumentationRuntimeStopInfo::GetSuggestedStackFrameIndex(), lldb_private::StopInfoTrace::GetSuggestedStackFrameIndex(), InstrumentationBoundsSafetyStopInfo::InstrumentationBoundsSafetyStopInfo(), lldb_private::StopInfoBreakpoint::PerformAction(), and lldb_private::StopInfoThreadPlan::StopInfoThreadPlan().
GetValue()
uint64_t lldb_private::StopInfo::GetValue () const inline
Definition at line 46 of file StopInfo.h.
References m_value.
Referenced by lldb_private::StopInfoMachException::GetDescription(), lldb_private::StopInfoException::GetStopReasonDataAtIndex(), lldb_private::StopInfoFork::GetStopReasonDataAtIndex(), lldb_private::StopInfoInterrupt::GetStopReasonDataAtIndex(), lldb_private::StopInfoMachException::GetStopReasonDataAtIndex(), lldb_private::StopInfoUnixSignal::GetStopReasonDataAtIndex(), lldb_private::StopInfoVFork::GetStopReasonDataAtIndex(), lldb_private::StopInfoWatchpoint::GetStopReasonDataAtIndex(), lldb_private::StopInfoWatchpoint::PerformAction(), and lldb_private::StopInfoWatchpoint::ShouldStopSynchronous().
HasTargetRunSinceMe()
bool StopInfo::HasTargetRunSinceMe () protected
Definition at line 56 of file StopInfo.cpp.
References lldb::eStateRunning, lldb::eStateStopped, m_resume_id, and m_thread_wp.
Referenced by lldb_private::StopInfoBreakpoint::PerformAction(), and lldb_private::StopInfoWatchpoint::PerformAction().
IsValid()
bool StopInfo::IsValid () const
Definition at line 41 of file StopInfo.cpp.
References m_stop_id, and m_thread_wp.
Referenced by ShouldShow().
IsValidForOperatingSystemThread()
virtual bool lldb_private::StopInfo::IsValidForOperatingSystemThread (Thread & thread) inline virtual
Reimplemented in lldb_private::StopInfoBreakpoint.
Definition at line 93 of file StopInfo.h.
References Thread.
MakeStopInfoValid()
void StopInfo::MakeStopInfoValid () protected
Definition at line 48 of file StopInfo.cpp.
References m_resume_id, m_stop_id, and m_thread_wp.
operator=()
const StopInfo & lldb_private::StopInfo::operator= (const StopInfo &) private delete
References StopInfo().
OverrideShouldNotify()
void lldb_private::StopInfo::OverrideShouldNotify (bool override_value) inline
Definition at line 56 of file StopInfo.h.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, and m_override_should_notify.
OverrideShouldStop()
void lldb_private::StopInfo::OverrideShouldStop (bool override_value) inline
Definition at line 113 of file StopInfo.h.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, and m_override_should_stop.
PerformAction()
virtual void lldb_private::StopInfo::PerformAction (Event * event_ptr) inline protected virtual
Reimplemented in lldb_private::StopInfoBreakpoint, lldb_private::StopInfoExec, lldb_private::StopInfoFork, lldb_private::StopInfoVFork, lldb_private::StopInfoVForkDone, and lldb_private::StopInfoWatchpoint.
Definition at line 208 of file StopInfo.h.
SetDescription()
virtual void lldb_private::StopInfo::SetDescription (const char * desc_cstr) inline virtual
Definition at line 74 of file StopInfo.h.
References m_description.
Referenced by lldb_private::StopInfoException::StopInfoException(), lldb_private::StopInfoHistoryBoundary::StopInfoHistoryBoundary(), lldb_private::StopInfoInterrupt::StopInfoInterrupt(), lldb_private::StopInfoProcessorTrace::StopInfoProcessorTrace(), and lldb_private::StopInfoUnixSignal::StopInfoUnixSignal().
SetThread()
void lldb_private::StopInfo::SetThread (const lldb::ThreadSP & thread_sp) inline
Definition at line 33 of file StopInfo.h.
References m_thread_wp.
ShouldNotify()
virtual bool lldb_private::StopInfo::ShouldNotify (Event * event_ptr) inline virtual
Definition at line 61 of file StopInfo.h.
References DoShouldNotify(), lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolYes, and m_override_should_notify.
ShouldSelect()
virtual bool lldb_private::StopInfo::ShouldSelect () const inline virtual
Returns true if this is a stop reason that should cause a thread to be selected when stopping.
Reimplemented in lldb_private::StopInfoBreakpoint, and lldb_private::StopInfoUnixSignal.
Definition at line 133 of file StopInfo.h.
References lldb::eStopReasonHistoryBoundary, lldb::eStopReasonInvalid, lldb::eStopReasonNone, and GetStopReason().
ShouldShow()
virtual bool lldb_private::StopInfo::ShouldShow () const inline virtual
Returns true if this is a stop reason that should be shown to a user when viewing the thread with this stop info.
Reimplemented in lldb_private::StopInfoBreakpoint.
Definition at line 129 of file StopInfo.h.
References IsValid().
ShouldStop()
virtual bool lldb_private::StopInfo::ShouldStop (Event * event_ptr) inline protected virtual
Reimplemented in lldb_private::StopInfoBreakpoint, lldb_private::StopInfoExec, lldb_private::StopInfoFork, lldb_private::StopInfoThreadPlan, lldb_private::StopInfoUnixSignal, lldb_private::StopInfoVFork, lldb_private::StopInfoVForkDone, and lldb_private::StopInfoWatchpoint.
Definition at line 219 of file StopInfo.h.
Referenced by lldb_private::StopInfoThreadPlan::ShouldStop().
ShouldStopSynchronous()
virtual bool lldb_private::StopInfo::ShouldStopSynchronous (Event * event_ptr) inline virtual
Reimplemented in lldb_private::StopInfoBreakpoint, lldb_private::StopInfoUnixSignal, and lldb_private::StopInfoWatchpoint.
Definition at line 54 of file StopInfo.h.
WasContinueInterrupted()
virtual bool lldb_private::StopInfo::WasContinueInterrupted (Thread & thread) inline virtual
A Continue operation can result in a false stop event before any execution has happened.
We need to detect this and silently continue again one more time.
Reimplemented in lldb_private::StopInfoMachException.
Definition at line 98 of file StopInfo.h.
References Thread.
WillResume()
virtual void lldb_private::StopInfo::WillResume (lldb::StateType resume_state) inline virtual
Reimplemented in lldb_private::StopInfoUnixSignal.
Definition at line 68 of file StopInfo.h.
Friends And Related Symbol Documentation
Process::ProcessEventData
friend class Process::ProcessEventData friend
Definition at line 21 of file StopInfo.h.
Thread
friend class Thread friend
Definition at line 245 of file StopInfo.h.
References Thread.
Referenced by InstrumentationBoundsSafetyStopInfo::CreateInstrumentationBoundsSafetyStopInfo(), CreateStopReasonFork(), CreateStopReasonHistoryBoundary(), CreateStopReasonProcessorTrace(), CreateStopReasonToTrace(), CreateStopReasonVFork(), CreateStopReasonVForkDone(), CreateStopReasonWithBreakpointSiteID(), CreateStopReasonWithBreakpointSiteID(), CreateStopReasonWithException(), CreateStopReasonWithExec(), lldb_private::InstrumentationRuntimeStopInfo::CreateStopReasonWithInstrumentationData(), CreateStopReasonWithInterrupt(), lldb_private::StopInfoMachException::CreateStopReasonWithMachException(), CreateStopReasonWithSignal(), CreateStopReasonWithWatchpointID(), lldb_private::StopInfoMachException::DeterminePtrauthFailure(), InstrumentationBoundsSafetyStopInfo::InstrumentationBoundsSafetyStopInfo(), lldb_private::InstrumentationRuntimeStopInfo::InstrumentationRuntimeStopInfo(), IsValidForOperatingSystemThread(), lldb_private::StopInfoBreakpoint::IsValidForOperatingSystemThread(), StopInfo(), lldb_private::StopInfoBreakpoint::StopInfoBreakpoint(), lldb_private::StopInfoBreakpoint::StopInfoBreakpoint(), lldb_private::StopInfoException::StopInfoException(), lldb_private::StopInfoExec::StopInfoExec(), lldb_private::StopInfoFork::StopInfoFork(), lldb_private::StopInfoHistoryBoundary::StopInfoHistoryBoundary(), lldb_private::StopInfoInterrupt::StopInfoInterrupt(), lldb_private::StopInfoMachException::StopInfoMachException(), lldb_private::StopInfoProcessorTrace::StopInfoProcessorTrace(), lldb_private::StopInfoTrace::StopInfoTrace(), lldb_private::StopInfoUnixSignal::StopInfoUnixSignal(), lldb_private::StopInfoVFork::StopInfoVFork(), lldb_private::StopInfoVForkDone::StopInfoVForkDone(), lldb_private::StopInfoWatchpoint::StopInfoWatchpoint(), Thread, ThreadPlanReverseContinue, lldb_private::StopInfoWatchpoint::ThreadPlanStepOverWatchpoint::ThreadPlanStepOverWatchpoint(), WasContinueInterrupted(), and lldb_private::StopInfoMachException::WasContinueInterrupted().
ThreadPlanBase
friend class ThreadPlanBase friend
Definition at line 22 of file StopInfo.h.
References ThreadPlanBase.
Referenced by ThreadPlanBase.
ThreadPlanReverseContinue
friend class ThreadPlanReverseContinue friend
Definition at line 23 of file StopInfo.h.
References Thread, and ThreadPlanReverseContinue.
Referenced by ThreadPlanReverseContinue.
Member Data Documentation
m_description
std::string lldb_private::StopInfo::m_description protected
Definition at line 227 of file StopInfo.h.
Referenced by lldb_private::StopInfoMachException::DeterminePtrauthFailure(), lldb_private::StopInfoMachException::DetermineTagMismatch(), InstrumentationBoundsSafetyStopInfo::GetDescription(), lldb_private::InstrumentationRuntimeStopInfo::GetDescription(), GetDescription(), lldb_private::StopInfoBreakpoint::GetDescription(), lldb_private::StopInfoException::GetDescription(), lldb_private::StopInfoHistoryBoundary::GetDescription(), lldb_private::StopInfoInterrupt::GetDescription(), lldb_private::StopInfoMachException::GetDescription(), lldb_private::StopInfoProcessorTrace::GetDescription(), lldb_private::StopInfoThreadPlan::GetDescription(), lldb_private::StopInfoTrace::GetDescription(), lldb_private::StopInfoUnixSignal::GetDescription(), lldb_private::StopInfoWatchpoint::GetDescription(), InstrumentationBoundsSafetyStopInfo::InstrumentationBoundsSafetyStopInfo(), lldb_private::InstrumentationRuntimeStopInfo::InstrumentationRuntimeStopInfo(), SetDescription(), and StopInfo().
m_extended_info
StructuredData::ObjectSP lldb_private::StopInfo::m_extended_info protected
Definition at line 232 of file StopInfo.h.
Referenced by GetExtendedInfo(), InstrumentationBoundsSafetyStopInfo::InstrumentationBoundsSafetyStopInfo(), lldb_private::InstrumentationRuntimeStopInfo::InstrumentationRuntimeStopInfo(), and StopInfo().
m_override_should_notify
LazyBool lldb_private::StopInfo::m_override_should_notify protected
Definition at line 228 of file StopInfo.h.
Referenced by OverrideShouldNotify(), ShouldNotify(), and StopInfo().
m_override_should_stop
LazyBool lldb_private::StopInfo::m_override_should_stop protected
Definition at line 229 of file StopInfo.h.
Referenced by GetOverriddenShouldStopValue(), GetOverrideShouldStop(), OverrideShouldStop(), and StopInfo().
m_resume_id
uint32_t lldb_private::StopInfo::m_resume_id protected
Definition at line 224 of file StopInfo.h.
Referenced by HasTargetRunSinceMe(), MakeStopInfoValid(), and StopInfo().
m_stop_id
uint32_t lldb_private::StopInfo::m_stop_id protected
Definition at line 223 of file StopInfo.h.
Referenced by IsValid(), MakeStopInfoValid(), and StopInfo().
m_thread_wp
lldb::ThreadWP lldb_private::StopInfo::m_thread_wp protected
Definition at line 222 of file StopInfo.h.
Referenced by lldb_private::StopInfoUnixSignal::DoShouldNotify(), lldb_private::StopInfoBreakpoint::GetDescription(), lldb_private::StopInfoMachException::GetDescription(), lldb_private::StopInfoUnixSignal::GetDescription(), lldb_private::StopInfoBreakpoint::GetSuggestedStackFrameIndex(), GetThread(), HasTargetRunSinceMe(), lldb_private::StopInfoUnixSignal::IsShouldStopSignal(), IsValid(), MakeStopInfoValid(), lldb_private::StopInfoBreakpoint::PerformAction(), lldb_private::StopInfoExec::PerformAction(), lldb_private::StopInfoFork::PerformAction(), lldb_private::StopInfoVFork::PerformAction(), lldb_private::StopInfoVForkDone::PerformAction(), lldb_private::StopInfoWatchpoint::PerformAction(), SetThread(), lldb_private::StopInfoExec::ShouldStop(), lldb_private::StopInfoBreakpoint::ShouldStopSynchronous(), lldb_private::StopInfoUnixSignal::ShouldStopSynchronous(), lldb_private::StopInfoWatchpoint::ShouldStopSynchronous(), StopInfo(), lldb_private::StopInfoBreakpoint::StoreBPInfo(), and lldb_private::StopInfoUnixSignal::WillResume().
m_value
uint64_t lldb_private::StopInfo::m_value protected
Definition at line 225 of file StopInfo.h.
Referenced by lldb_private::StopInfoMachException::DeterminePtrauthFailure(), lldb_private::StopInfoUnixSignal::DoShouldNotify(), lldb_private::StopInfoBreakpoint::GetBreakpointSiteSP(), lldb_private::StopInfoBreakpoint::GetDescription(), lldb_private::StopInfoMachException::GetDescription(), lldb_private::StopInfoUnixSignal::GetDescription(), lldb_private::StopInfoWatchpoint::GetDescription(), InstrumentationBoundsSafetyStopInfo::GetSuggestedStackFrameIndex(), lldb_private::StopInfoMachException::GetTagFaultAddress(), GetValue(), InstrumentationBoundsSafetyStopInfo::InstrumentationBoundsSafetyStopInfo(), lldb_private::StopInfoUnixSignal::IsShouldStopSignal(), lldb_private::StopInfoBreakpoint::PerformAction(), lldb_private::StopInfoWatchpoint::PerformAction(), lldb_private::StopInfoBreakpoint::ShouldStopSynchronous(), lldb_private::StopInfoUnixSignal::ShouldStopSynchronous(), StopInfo(), and lldb_private::StopInfoUnixSignal::WillResume().
The documentation for this class was generated from the following files:
StopInfo.h
StopInfo.cpp