LLDB: lldb_private::ThreadPlanStepOverRange Class Reference
lldb_private::ThreadPlanStepOverRange Class Reference
#include <ThreadPlanStepOverRange.h>
Public Member Functions
ThreadPlanStepOverRange (Thread &thread, const AddressRange &range, const SymbolContext &addr_context, lldb::RunMode stop_others, LazyBool step_out_avoids_no_debug)
~ThreadPlanStepOverRange () override
void GetDescription (Stream *s, lldb::DescriptionLevel level) override
Print a description of this thread to the stream s.
void SetStopOthers (bool new_value) override
bool ShouldStop (Event *event_ptr) override
void DidPush () override
Public Member Functions inherited from lldb_private::ThreadPlanStepRange
ThreadPlanStepRange (ThreadPlanKind kind, const char *name, Thread &thread, const AddressRange &range, const SymbolContext &addr_context, lldb::RunMode stop_others, bool given_ranges_only=false)
~ThreadPlanStepRange () override
bool ValidatePlan (Stream *error) override
Returns whether this plan could be successfully created.
Vote ShouldReportStop (Event *event_ptr) override
bool StopOthers () override
lldb::StateType GetPlanRunState () override
bool WillStop () override
bool MischiefManaged () override
void DidPush () override
bool IsPlanStale () override
void AddRange (const AddressRange &new_range)
Public Member Functions inherited from lldb_private::ThreadPlan
virtual ~ThreadPlan ()
const char * GetName () const
Returns the name of this thread plan.
Thread & GetThread ()
Returns the Thread that is using this thread plan.
Target & GetTarget ()
const Target & GetTarget () const
void ClearThreadCache ()
Clear the Thread* cache.
bool TracerExplainsStop ()
lldb::StateType RunState ()
bool PlanExplainsStop (Event *event_ptr)
virtual bool ShouldAutoContinue (Event *event_ptr)
Returns whether this thread plan overrides the ShouldStop of subsequently processed plans.
Vote ShouldReportRun (Event *event_ptr)
virtual bool SupportsResumeOthers ()
virtual bool ShouldRunBeforePublicStop ()
bool WillResume (lldb::StateType resume_state, bool current_plan)
bool IsControllingPlan ()
virtual bool IsLeafPlan ()
bool SetIsControllingPlan (bool value)
virtual bool OkayToDiscard ()
void SetOkayToDiscard (bool value)
virtual void ThreadDestroyed ()
bool GetPrivate ()
void SetPrivate (bool input)
virtual void DidPop ()
ThreadPlanKind GetKind () const
bool IsPlanComplete ()
void SetPlanComplete (bool success=true)
bool PlanSucceeded ()
virtual bool IsBasePlan ()
lldb::ThreadPlanTracerSP & GetThreadPlanTracer ()
void SetThreadPlanTracer (lldb::ThreadPlanTracerSP new_tracer_sp)
void DoTraceLog ()
virtual lldb::ValueObjectSP GetReturnValueObject ()
virtual lldb::ExpressionVariableSP GetExpressionVariable ()
virtual void RestoreThreadState ()
virtual bool IsVirtualStep ()
bool SetIterationCount (size_t count)
virtual lldb::RunDirection GetDirection () const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Protected Member Functions
bool DoPlanExplainsStop (Event *event_ptr) override
bool DoWillResume (lldb::StateType resume_state, bool current_plan) override
void SetFlagsToDefault () override
Protected Member Functions inherited from lldb_private::ThreadPlanStepRange
bool InRange ()
lldb::FrameComparison CompareCurrentFrameToStartFrame ()
bool InSymbol ()
void DumpRanges (Stream *s)
Disassembler * GetDisassembler ()
InstructionList * GetInstructionsForAddress (lldb::addr_t addr, size_t &range_index, size_t &insn_offset)
bool SetNextBranchBreakpoint ()
bool IsNextBranchBreakpointStop (lldb::StopInfoSP stop_info_sp)
void ClearNextBranchBreakpoint ()
void ClearNextBranchBreakpointExplainedStop ()
bool NextRangeBreakpointExplainsStop (lldb::StopInfoSP stop_info_sp)
Protected Member Functions inherited from lldb_private::ThreadPlan
ThreadPlan (ThreadPlanKind kind, const char *name, Thread &thread, Vote report_stop_vote, Vote report_run_vote)
void PushPlan (lldb::ThreadPlanSP &thread_plan_sp)
ThreadPlan * GetPreviousPlan ()
lldb::StopInfoSP GetPrivateStopInfo ()
void SetStopInfo (lldb::StopInfoSP stop_reason_sp)
bool IsUsuallyUnexplainedStopReason (lldb::StopReason)
Private Member Functions
void SetupAvoidNoDebug (LazyBool step_out_avoids_code_without_debug_info)
bool IsEquivalentContext (const SymbolContext &context)
ThreadPlanStepOverRange (const ThreadPlanStepOverRange &)=delete
const ThreadPlanStepOverRange & operator= (const ThreadPlanStepOverRange &)=delete
Private Member Functions inherited from lldb_private::ThreadPlanShouldStopHere
ThreadPlanShouldStopHere (ThreadPlan *owner)
ThreadPlanShouldStopHere (ThreadPlan *owner, const ThreadPlanShouldStopHereCallbacks *callbacks, void *baton=nullptr)
virtual ~ThreadPlanShouldStopHere ()
void SetShouldStopHereCallbacks (const ThreadPlanShouldStopHereCallbacks *callbacks, void *baton)
void ClearShouldStopHereCallbacks ()
bool InvokeShouldStopHereCallback (lldb::FrameComparison operation, Status &status)
lldb::ThreadPlanSP CheckShouldStopHereAndQueueStepOut (lldb::FrameComparison operation, Status &status)
lldb_private::Flags & GetFlags ()
const lldb_private::Flags & GetFlags () const
virtual lldb::ThreadPlanSP QueueStepOutFromHerePlan (Flags &flags, lldb::FrameComparison operation, Status &status)
Private Member Functions inherited from lldb_private::TimeoutResumeAll
TimeoutResumeAll (Thread &thread)
void PushNewTimeout ()
void ResumeWithTimeout ()
Private Attributes
bool m_first_resume
lldb::RunMode m_run_mode
Private Attributes inherited from lldb_private::ThreadPlanShouldStopHere
ThreadPlanShouldStopHereCallbacks m_callbacks
void * m_baton
ThreadPlan * m_owner
lldb_private::Flags m_flags
Static Private Attributes
static uint32_t s_default_flag_values = 0
Additional Inherited Members
Public Types inherited from lldb_private::ThreadPlan
enum ThreadPlanKind {
eKindGeneric , eKindNull , eKindBase , eKindCallFunction ,
eKindPython , eKindStepInstruction , eKindStepOut , eKindStepOverBreakpoint ,
eKindStepOverRange , eKindStepInRange , eKindRunToAddress , eKindStepThrough ,
eKindStepUntil , eKindSingleThreadTimeout
}
Protected Attributes inherited from lldb_private::ThreadPlanStepRange
SymbolContext m_addr_context
std::vector< AddressRange > m_address_ranges
lldb::RunMode m_stop_others
StackID m_stack_id
StackID m_parent_stack_id
bool m_no_more_plans
bool m_first_run_event
lldb::BreakpointSP m_next_branch_bp_sp
bool m_use_fast_step
bool m_given_ranges_only
bool m_found_calls = false
Protected Attributes inherited from lldb_private::ThreadPlan
Status m_status
Process & m_process
lldb::tid_t m_tid
Vote m_report_stop_vote
Vote m_report_run_vote
bool m_takes_iteration_count
bool m_could_not_resolve_hw_bp
int32_t m_iteration_count = 1
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Private Types inherited from lldb_private::ThreadPlanShouldStopHere
enum {
eNone = 0 , eAvoidInlines = (1 << 0) , eStepInAvoidNoDebug = (1 << 1) , eStepOutAvoidNoDebug = (1 << 2) ,
eStepOutPastThunks = (1 << 3)
}
Static Private Member Functions inherited from lldb_private::ThreadPlanShouldStopHere
static bool DefaultShouldStopHereCallback (ThreadPlan *current_plan, Flags &flags, lldb::FrameComparison operation, Status &status, void *baton)
static lldb::ThreadPlanSP DefaultStepFromHereCallback (ThreadPlan *current_plan, Flags &flags, lldb::FrameComparison operation, Status &status, void *baton)
Detailed Description
Definition at line 20 of file ThreadPlanStepOverRange.h.
Constructor & Destructor Documentation
ThreadPlanStepOverRange() [1/2]
ThreadPlanStepOverRange::ThreadPlanStepOverRange (Thread & thread, const AddressRange & range, const SymbolContext & addr_context, lldb::RunMode stop_others, LazyBool step_out_avoids_no_debug)
Definition at line 34 of file ThreadPlanStepOverRange.cpp.
References lldb_private::ThreadPlan::eKindStepOverRange, m_first_resume, m_run_mode, SetFlagsToDefault(), SetupAvoidNoDebug(), lldb_private::ThreadPlanShouldStopHere::ThreadPlanShouldStopHere(), lldb_private::ThreadPlanStepRange::ThreadPlanStepRange(), and lldb_private::TimeoutResumeAll::TimeoutResumeAll().
Referenced by operator=(), and ThreadPlanStepOverRange().
~ThreadPlanStepOverRange()
ThreadPlanStepOverRange::~ThreadPlanStepOverRange () override default
ThreadPlanStepOverRange() [2/2]
lldb_private::ThreadPlanStepOverRange::ThreadPlanStepOverRange (const ThreadPlanStepOverRange &) private delete
References ThreadPlanStepOverRange().
Member Function Documentation
DidPush()
void ThreadPlanStepOverRange::DidPush () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 355 of file ThreadPlanStepOverRange.cpp.
References lldb_private::ThreadPlanStepRange::DidPush(), lldb::eOnlyThisThread, lldb_private::ThreadPlan::IsControllingPlan(), m_run_mode, and lldb_private::TimeoutResumeAll::PushNewTimeout().
DoPlanExplainsStop()
bool ThreadPlanStepOverRange::DoPlanExplainsStop (Event * event_ptr) override protected virtual
Implements lldb_private::ThreadPlan.
Definition at line 361 of file ThreadPlanStepOverRange.cpp.
References lldb::eStopReasonBreakpoint, lldb::eStopReasonTrace, lldb_private::GetLog(), lldb_private::ThreadPlan::GetPrivateStopInfo(), lldb_private::ThreadPlanStepRange::NextRangeBreakpointExplainsStop(), lldb_private::Log::PutCString(), and lldb_private::Step.
DoWillResume()
bool ThreadPlanStepOverRange::DoWillResume (lldb::StateType resume_state, bool current_plan) override protected virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 392 of file ThreadPlanStepOverRange.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::ThreadPlanStepRange::DumpRanges(), lldb::eOnlyThisThread, lldb::eStateStepping, lldb::eStateSuspended, lldb_private::Block::GetInlinedFunctionInfo(), lldb_private::GetLog(), lldb_private::InlineFunctionInfo::GetName(), lldb_private::Block::GetRangeContainingLoadAddress(), lldb_private::StreamString::GetString(), lldb_private::ThreadPlan::GetThread(), lldb_private::ThreadPlan::IsControllingPlan(), LLDB_LOGF, lldb_private::ThreadPlanStepRange::m_address_ranges, m_first_resume, lldb_private::ThreadPlan::m_process, m_run_mode, lldb_private::Stream::Printf(), lldb_private::Log::PutString(), lldb_private::TimeoutResumeAll::ResumeWithTimeout(), and lldb_private::Step.
GetDescription()
void ThreadPlanStepOverRange::GetDescription (Stream * s, lldb::DescriptionLevel level) override virtual
Print a description of this thread to the stream s.
thread. Don't expect that the result of GetThread is valid in the description method. This might get called when the underlying Thread has not been reported, so we only know the TID and not the thread.
Parameters
[in] s The stream to which to print the description.
[in] level The level of description desired. Note that eDescriptionLevelBrief will be used in the stop message printed when the plan is complete.
Implements lldb_private::ThreadPlanStepRange.
Definition at line 49 of file ThreadPlanStepOverRange.cpp.
References lldb_private::ThreadPlanStepRange::DumpRanges(), lldb::eDescriptionLevelBrief, lldb::eDescriptionLevelVerbose, lldb_private::ThreadPlanStepRange::m_addr_context, lldb_private::ThreadPlan::m_status, lldb_private::Stream::Printf(), and lldb_private::Stream::PutChar().
IsEquivalentContext()
bool ThreadPlanStepOverRange::IsEquivalentContext (const SymbolContext & context) private
Definition at line 105 of file ThreadPlanStepOverRange.cpp.
References lldb_private::SymbolContext::block, lldb_private::SymbolContext::comp_unit, lldb_private::Language::FindPlugin(), lldb_private::SymbolContext::function, lldb_private::Block::GetInlinedFunctionInfo(), lldb_private::SymbolContext::GetLanguage(), lldb_private::ThreadPlanStepRange::m_addr_context, and lldb_private::SymbolContext::symbol.
Referenced by ShouldStop().
operator=()
const ThreadPlanStepOverRange & lldb_private::ThreadPlanStepOverRange::operator= (const ThreadPlanStepOverRange &) private delete
References ThreadPlanStepOverRange().
SetFlagsToDefault()
void lldb_private::ThreadPlanStepOverRange::SetFlagsToDefault () inline override protected virtual
Implements lldb_private::ThreadPlanShouldStopHere.
Definition at line 40 of file ThreadPlanStepOverRange.h.
References lldb_private::ThreadPlanShouldStopHere::GetFlags(), s_default_flag_values, and lldb_private::Flags::Set().
Referenced by ThreadPlanStepOverRange().
SetStopOthers()
void ThreadPlanStepOverRange::SetStopOthers (bool new_value) override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 134 of file ThreadPlanStepOverRange.cpp.
References lldb::eAllThreads, and lldb_private::ThreadPlanStepRange::m_stop_others.
SetupAvoidNoDebug()
void ThreadPlanStepOverRange::SetupAvoidNoDebug (LazyBool step_out_avoids_code_without_debug_info) private
Definition at line 81 of file ThreadPlanStepOverRange.cpp.
References lldb_private::Flags::Clear(), lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb_private::ThreadPlanShouldStopHere::eStepInAvoidNoDebug, lldb_private::ThreadPlanShouldStopHere::eStepOutAvoidNoDebug, lldb_private::ThreadPlanShouldStopHere::GetFlags(), lldb_private::ThreadProperties::GetStepOutAvoidsNoDebug(), lldb_private::ThreadPlan::GetThread(), and lldb_private::Flags::Set().
Referenced by ThreadPlanStepOverRange().
ShouldStop()
bool ThreadPlanStepOverRange::ShouldStop (Event * event_ptr) override virtual
Implements lldb_private::ThreadPlanStepRange.
Definition at line 139 of file ThreadPlanStepOverRange.cpp.
References lldb_private::Stream::AsRawOstream(), lldb_private::SymbolContext::block, lldb_private::Address::CalculateSymbolContext(), lldb_private::Address::CalculateSymbolContextFunction(), lldb_private::ThreadPlanShouldStopHere::CheckShouldStopHereAndQueueStepOut(), lldb_private::ThreadPlanStepRange::ClearNextBranchBreakpoint(), lldb_private::ThreadPlanStepRange::ClearNextBranchBreakpointExplainedStop(), lldb_private::SymbolContext::comp_unit, lldb_private::ThreadPlanStepRange::CompareCurrentFrameToStartFrame(), lldb_private::AddressRange::ContainsFileAddress(), lldb_private::DumpAddress(), lldb::eAllThreads, lldb_private::SupportFile::eEqualFileSpecAndChecksumIfSet, lldb::eFrameCompareOlder, lldb::eFrameCompareYounger, lldb::eOnlyThisThread, lldb_private::eVoteNo, lldb_private::eVoteNoOpinion, lldb_private::LineTable::FindLineEntryByAddress(), lldb_private::SymbolContext::function, lldb_private::AddressRange::GetBaseAddress(), lldb_private::Block::GetContainingInlinedBlock(), lldb_private::StreamString::GetData(), lldb_private::LineTable::GetLineEntryAtIndex(), lldb_private::Address::GetLoadAddress(), lldb_private::GetLog(), lldb_private::Block::GetRangeContainingAddress(), lldb_private::ThreadPlan::GetTarget(), lldb_private::ThreadPlan::GetThread(), lldb_private::ThreadPlanStepRange::InRange(), lldb_private::ThreadPlanStepRange::InSymbol(), IsEquivalentContext(), lldb_private::LineEntry::IsValid(), lldb_private::SymbolContext::line_entry, LLDB_LOGF, lldb_private::ThreadPlanStepRange::m_addr_context, lldb_private::ThreadPlanStepRange::m_next_branch_bp_sp, lldb_private::ThreadPlanStepRange::m_no_more_plans, lldb_private::ThreadPlanStepRange::m_stack_id, lldb_private::ThreadPlan::m_status, lldb_private::ThreadPlanStepRange::m_stop_others, lldb_private::LineEntry::original_file_sp, lldb_private::LineEntry::range, lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint(), lldb_private::ThreadPlan::SetPlanComplete(), and lldb_private::Step.
Member Data Documentation
m_first_resume
bool lldb_private::ThreadPlanStepOverRange::m_first_resume private
Definition at line 50 of file ThreadPlanStepOverRange.h.
Referenced by DoWillResume(), and ThreadPlanStepOverRange().
m_run_mode
lldb::RunMode lldb_private::ThreadPlanStepOverRange::m_run_mode private
Definition at line 51 of file ThreadPlanStepOverRange.h.
Referenced by DidPush(), DoWillResume(), and ThreadPlanStepOverRange().
s_default_flag_values
uint32_t ThreadPlanStepOverRange::s_default_flag_values = 0 static private
Definition at line 45 of file ThreadPlanStepOverRange.h.
Referenced by SetFlagsToDefault().
The documentation for this class was generated from the following files:
ThreadPlanStepOverRange.h
ThreadPlanStepOverRange.cpp