LLDB: ObjectFilePECOFF Class Reference
ObjectFilePECOFF Class Reference
#include <ObjectFilePECOFF.h>
Classes
struct coff_header
struct coff_opt_header
struct data_directory
struct dos_header
struct section_header
Public Types
enum MachineType {
MachineUnknown = 0x0 , MachineAm33 = 0x1d3 , MachineAmd64 = 0x8664 , MachineArm = 0x1c0 ,
MachineArmNt = 0x1c4 , MachineArm64 = 0xaa64 , MachineArm64X = 0xa64e , MachineEbc = 0xebc ,
MachineX86 = 0x14c , MachineIA64 = 0x200 , MachineM32R = 0x9041 , MachineMips16 = 0x266 ,
MachineMipsFpu = 0x366 , MachineMipsFpu16 = 0x466 , MachinePowerPc = 0x1f0 , MachinePowerPcfp = 0x1f1 ,
MachineR4000 = 0x166 , MachineSh3 = 0x1a2 , MachineSh3dsp = 0x1a3 , MachineSh4 = 0x1a6 ,
MachineSh5 = 0x1a8 , MachineThumb = 0x1c2 , MachineWcemIpsv2 = 0x169
}
Public Types inherited from lldb_private::ObjectFile
enum Type {
eTypeInvalid = 0 , eTypeCoreFile , eTypeExecutable , eTypeDebugInfo ,
eTypeDynamicLinker , eTypeObjectFile , eTypeSharedLibrary , eTypeStubLibrary ,
eTypeJIT , eTypeUnknown
}
enum Strata {
eStrataInvalid = 0 , eStrataUnknown , eStrataUser , eStrataKernel ,
eStrataRawImage , eStrataJIT
}
enum BinaryType {
eBinaryTypeInvalid = 0 , eBinaryTypeUnknown , eBinaryTypeKernel , eBinaryTypeUser ,
eBinaryTypeUserAllImageInfos , eBinaryTypeStandalone
}
If we have a corefile binary hint, this enum specifies the binary type which we can use to select the correct DynamicLoader plugin.
Public Member Functions
ObjectFilePECOFF (const lldb::ModuleSP &module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const lldb_private::FileSpec *file, lldb::offset_t file_offset, lldb::offset_t length)
ObjectFilePECOFF (const lldb::ModuleSP &module_sp, lldb::WritableDataBufferSP header_data_sp, const lldb::ProcessSP &process_sp, lldb::addr_t header_addr)
~ObjectFilePECOFF () override
bool isA (const void *ClassID) const override
bool ParseHeader () override
Attempts to parse the object header.
bool SetLoadAddress (lldb_private::Target &target, lldb::addr_t value, bool value_is_offset) override
Sets the load address for an entire module, assuming a rigid slide of sections, if possible in the implementation.
lldb::ByteOrder GetByteOrder () const override
Gets whether endian swapping should occur when extracting data from this object file.
bool IsExecutable () const override
Tells whether this object file is capable of being the main executable for a process.
uint32_t GetAddressByteSize () const override
Gets the address size in bytes for the current object file.
void ParseSymtab (lldb_private::Symtab &symtab) override
Parse the symbol table into the provides symbol table object.
bool IsStripped () override
Detect if this object file has been stripped of local symbols.
void CreateSections (lldb_private::SectionList &unified_section_list) override
void Dump (lldb_private::Stream *s) override
Dump a description of this object to a Stream.
lldb_private::ArchSpec GetArchitecture () override
Get the ArchSpec for this object file.
lldb_private::UUID GetUUID () override
Gets the UUID for this object file.
std::optional< lldb_private::FileSpec > GetDebugLink ()
Return the contents of the .gnu_debuglink section, if the object file contains it.
uint32_t GetDependentModules (lldb_private::FileSpecList &files) override
Extract the dependent modules from an object file.
lldb_private::Address GetEntryPointAddress () override
Returns the address of the Entry Point in this object file - if the object file doesn't have an entry point (because it is not an executable file) then an invalid address is returned.
lldb_private::Address GetBaseAddress () override
Returns base address of this object file.
ObjectFile::Type CalculateType () override
The object file should be able to calculate its type by looking at its file header and possibly the sections or other data in the object file.
ObjectFile::Strata CalculateStrata () override
The object file should be able to calculate the strata of the object file.
llvm::StringRef GetPluginName () override
bool IsWindowsSubsystem ()
uint32_t GetRVA (const lldb_private::Address &addr) const
lldb_private::Address GetAddress (uint32_t rva)
lldb::addr_t GetFileAddress (uint32_t rva) const
lldb_private::DataExtractor ReadImageData (uint32_t offset, size_t size)
lldb_private::DataExtractor ReadImageDataByRVA (uint32_t rva, size_t size)
std::unique_ptr< lldb_private::CallFrameInfo > CreateCallFrameInfo () override
Creates a plugin-specific call frame info.
Public Member Functions inherited from lldb_private::ObjectFile
ObjectFile (const lldb::ModuleSP &module_sp, const FileSpec *file_spec_ptr, lldb::offset_t file_offset, lldb::offset_t length, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset)
Construct with a parent module, offset, and header data.
ObjectFile (const lldb::ModuleSP &module_sp, const lldb::ProcessSP &process_sp, lldb::addr_t header_addr, lldb::DataExtractorSP extractor_sp)
~ObjectFile () override
Destructor.
virtual AddressClass GetAddressClass (lldb::addr_t file_addr)
Get the address type given a file address in an object file.
virtual lldb::addr_t GetFileOffset () const
Returns the offset into a file at which this object resides.
virtual lldb::addr_t GetByteSize () const
virtual FileSpec & GetFileSpec ()
Get accessor to the object file specification.
virtual const FileSpec & GetFileSpec () const
Get const accessor to the object file specification.
virtual SectionList * GetSectionList (bool update_module_section_list=true)
Gets the section list for the currently selected architecture (and object for archives).
virtual void SectionFileAddressesChanged ()
Notify the ObjectFile that the file addresses in the Sections for this module have been changed.
Symtab * GetSymtab (bool can_create=true)
Gets the symbol table for the currently selected architecture (and object for archives).
virtual void RelocateSection (lldb_private::Section *section)
Perform relocations on the section if necessary.
virtual void ClearSymtab ()
Frees the symbol table.
virtual lldb_private::FileSpecList GetReExportedLibraries ()
Gets the file spec list of libraries re-exported by this object file.
virtual bool AllowAssemblyEmulationUnwindPlans ()
Returns if the function bounds for symbols in this symbol file are likely accurate.
virtual lldb_private::Address GetImageInfoAddress (Target *target)
Similar to Process::GetImageInfoAddress().
virtual uint32_t GetNumThreadContexts ()
virtual std::string GetIdentifierString ()
Some object files may have an identifier string embedded in them, e.g.
virtual lldb_private::AddressableBits GetAddressableBits ()
Some object files may have the number of bits used for addressing embedded in them, e.g.
virtual bool GetCorefileMainBinaryInfo (lldb::addr_t &value, bool &value_is_offset, UUID &uuid, ObjectFile::BinaryType &type)
When the ObjectFile is a core file, lldb needs to locate the "binary" in the core file.
virtual bool GetCorefileThreadExtraInfos (std::vector< lldb::tid_t > &tids)
Get metadata about thread ids from the corefile.
virtual StructuredData::ObjectSP GetCorefileProcessMetadata ()
Get process metadata from the corefile in a StructuredData dictionary.
virtual lldb::RegisterContextSP GetThreadContextAtIndex (uint32_t idx, lldb_private::Thread &thread)
virtual void SetType (Type type)
In cases where the type can't be calculated (elf files), this routine allows someone to explicitly set it.
virtual llvm::VersionTuple GetVersion ()
Get the object file version numbers.
virtual llvm::VersionTuple GetMinimumOSVersion ()
Get the minimum OS version this object file can run on.
virtual llvm::VersionTuple GetSDKVersion ()
Get the SDK OS version this object file was built with.
virtual bool GetIsDynamicLinkEditor ()
Return true if this file is a dynamic link editor (dyld)
Type GetType ()
Strata GetStrata ()
size_t GetData (lldb::offset_t offset, size_t length, lldb::DataExtractorSP &data_sp) const
size_t CopyData (lldb::offset_t offset, size_t length, void *dst) const
virtual size_t ReadSectionData (Section *section, lldb::offset_t section_offset, void *dst, size_t dst_len)
virtual size_t ReadSectionData (Section *section, DataExtractor &section_data)
bool IsInMemory () const
Returns true if the object file exists only in memory.
virtual llvm::StringRef StripLinkerSymbolAnnotations (llvm::StringRef symbol_name) const
virtual bool CanTrustAddressRanges ()
Can we trust the address ranges accelerator associated with this object file to be complete.
virtual std::vector< LoadableData > GetLoadableData (Target &target)
Loads this objfile to memory.
virtual bool LoadCoreFileImages (lldb_private::Process &process)
Load binaries listed in a corefile.
virtual bool IsGOTSection (const lldb_private::Section &section) const
Returns true if the section is a global offset table section.
uint32_t GetCacheHash ()
Get a hash that can be used for caching object file releated information.
std::string GetObjectName () const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Public Member Functions inherited from lldb_private::ModuleChild
ModuleChild (const lldb::ModuleSP &module_sp)
Construct with owning module.
~ModuleChild ()
Destructor.
const ModuleChild & operator= (const ModuleChild &rhs)
Assignment operator.
lldb::ModuleSP GetModule () const
Get const accessor for the module pointer.
void SetModule (const lldb::ModuleSP &module_sp)
Set accessor for the module pointer.
Static Public Member Functions
static void Initialize ()
static void DebuggerInitialize (lldb_private::Debugger &debugger)
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static ObjectFile * CreateInstance (const lldb::ModuleSP &module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const lldb_private::FileSpec *file, lldb::offset_t offset, lldb::offset_t length)
static lldb_private::ObjectFile * CreateMemoryInstance (const lldb::ModuleSP &module_sp, lldb::WritableDataBufferSP data_sp, const lldb::ProcessSP &process_sp, lldb::addr_t header_addr)
static size_t GetModuleSpecifications (const lldb_private::FileSpec &file, lldb::DataExtractorSP &extractor_sp, lldb::offset_t data_offset, lldb::offset_t file_offset, lldb::offset_t length, lldb_private::ModuleSpecList &specs)
static bool SaveCore (const lldb::ProcessSP &process_sp, lldb_private::SaveCoreOptions &options, lldb_private::Status &error)
static bool MagicBytesMatch (lldb::DataExtractorSP extractor_sp)
static lldb::SymbolType MapSymbolType (uint16_t coff_symbol_type)
static bool classof (const ObjectFile *obj)
Static Public Member Functions inherited from lldb_private::ObjectFile
static lldb::ObjectFileSP FindPlugin (const lldb::ModuleSP &module_sp, const FileSpec *file_spec, lldb::offset_t file_offset, lldb::offset_t file_size, lldb::DataExtractorSP extractor_sp, lldb::offset_t &data_offset)
Find a ObjectFile plug-in that can parse file_spec.
static lldb::ObjectFileSP FindPlugin (const lldb::ModuleSP &module_sp, const lldb::ProcessSP &process_sp, lldb::addr_t header_addr, lldb::WritableDataBufferSP file_data_sp)
Find a ObjectFile plug-in that can parse a file in memory.
static size_t GetModuleSpecifications (const FileSpec &file, lldb::offset_t file_offset, lldb::offset_t file_size, ModuleSpecList &specs, lldb::DataExtractorSP=lldb::DataExtractorSP())
static size_t GetModuleSpecifications (const lldb_private::FileSpec &file, lldb::DataExtractorSP &extractor_sp, lldb::offset_t data_offset, lldb::offset_t file_offset, lldb::offset_t file_size, lldb_private::ModuleSpecList &specs)
static bool IsObjectFile (lldb_private::FileSpec file_spec)
static bool SplitArchivePathWithObject (llvm::StringRef path_with_object, lldb_private::FileSpec &archive_file, lldb_private::ConstString &archive_object, bool must_exist)
Split a path into a file path with object name.
static lldb::WritableDataBufferSP ReadMemory (const lldb::ProcessSP &process_sp, lldb::addr_t addr, size_t byte_size)
static lldb::SymbolType GetSymbolTypeFromName (llvm::StringRef name, lldb::SymbolType symbol_type_hint=lldb::eSymbolTypeUndefined)
static lldb::SectionType GetDWARFSectionTypeFromName (llvm::StringRef name)
Parses the section type from a section name for DWARF sections.
static lldb::DataBufferSP MapFileData (const FileSpec &file, uint64_t Size, uint64_t Offset)
Static Public Attributes
static char ID
Static Public Attributes inherited from lldb_private::ObjectFile
static char ID
Protected Types
typedef struct ObjectFilePECOFF::dos_header dos_header_t
typedef struct ObjectFilePECOFF::coff_header coff_header_t
typedef struct ObjectFilePECOFF::data_directory data_directory_t
typedef struct ObjectFilePECOFF::coff_opt_header coff_opt_header_t
typedef struct ObjectFilePECOFF::section_header section_header_t
typedef std::vector< section_header_t > SectionHeaderColl
typedef SectionHeaderColl::iterator SectionHeaderCollIter
typedef SectionHeaderColl::const_iterator SectionHeaderCollConstIter
Protected Types inherited from lldb_private::ObjectFile
typedef NonNullSharedPtr< lldb_private::DataExtractor > DataExtractorNSP
Protected Member Functions
bool NeedsEndianSwap () const
bool ParseCOFFOptionalHeader (lldb::offset_t *offset_ptr)
bool ParseSectionHeaders (uint32_t offset)
uint32_t ParseDependentModules ()
void DumpSectionHeaders (lldb_private::Stream *s)
void DumpSectionHeader (lldb_private::Stream *s, const section_header_t &sh)
void DumpDependentModules (lldb_private::Stream *s)
llvm::StringRef GetSectionName (const section_header_t &sect)
size_t GetSectionDataSize (lldb_private::Section *section) override
Protected Member Functions inherited from lldb_private::ObjectFile
bool SetModulesArchitecture (const ArchSpec &new_arch)
Sets the architecture for a module.
Static Protected Member Functions
static bool ParseDOSHeader (lldb_private::DataExtractor &data, dos_header_t &dos_header)
static bool ParseCOFFHeader (lldb_private::DataExtractor &data, lldb::offset_t *offset_ptr, coff_header_t &coff_header)
static void DumpDOSHeader (lldb_private::Stream *s, const dos_header_t &header)
static void DumpCOFFHeader (lldb_private::Stream *s, const coff_header_t &header)
static void DumpOptCOFFHeader (lldb_private::Stream *s, const coff_opt_header_t &header)
static lldb::SectionType GetSectionType (llvm::StringRef sect_name, const section_header_t &sect)
Private Types
typedef std::vector< std::pair< uint32_t, uint32_t > > rva_symbol_list_t
Private Member Functions
bool CreateBinary ()
void AppendFromCOFFSymbolTable (lldb_private::SectionList *sect_list, lldb_private::Symtab &symtab, const rva_symbol_list_t &sorted_exports)
rva_symbol_list_t AppendFromExportTable (lldb_private::SectionList *sect_list, lldb_private::Symtab &symtab)
Private Attributes
dos_header_t m_dos_header
coff_header_t m_coff_header
coff_opt_header_t m_coff_header_opt
SectionHeaderColl m_sect_headers
lldb::addr_t m_image_base
lldb_private::Address m_entry_point_address
std::optional< lldb_private::FileSpecList > m_deps_filespec
std::unique_ptr< llvm::object::COFFObjectFile > m_binary
lldb_private::UUID m_uuid
Additional Inherited Members
Protected Attributes inherited from lldb_private::ObjectFile
FileSpec m_file
Type m_type
Strata m_strata
lldb::addr_t m_file_offset
The offset in bytes into the file, or the address in memory.
lldb::addr_t m_length
The length of this object file if it is known (can be zero if length is unknown or can't be determined).
DataExtractorNSP m_data_nsp
The data for this object file so things can be parsed lazily.
lldb::ProcessWP m_process_wp
const lldb::addr_t m_memory_addr
Set if the object file only exists in memory.
std::unique_ptr< lldb_private::SectionList > m_sections_up
std::unique_ptr< lldb_private::Symtab > m_symtab_up
std::unique_ptr< llvm::once_flag > m_symtab_once_up
We need a llvm::once_flag that we can use to avoid locking the module lock and deadlocking LLDB.
std::optional< uint32_t > m_cache_hash
Protected Attributes inherited from lldb_private::ModuleChild
lldb::ModuleWP m_module_wp
The Module that owns the object that inherits from this class.
Static Protected Attributes inherited from lldb_private::ObjectFile
static size_t g_initial_bytes_to_read = 512
The number of bytes to read when going through the plugins.
Detailed Description
Definition at line 19 of file ObjectFilePECOFF.h.
Member Typedef Documentation
coff_header_t
typedef struct ObjectFilePECOFF::coff_header ObjectFilePECOFF::coff_header_t protected
coff_opt_header_t
typedef struct ObjectFilePECOFF::coff_opt_header ObjectFilePECOFF::coff_opt_header_t protected
data_directory_t
typedef struct ObjectFilePECOFF::data_directory ObjectFilePECOFF::data_directory_t protected
dos_header_t
typedef struct ObjectFilePECOFF::dos_header ObjectFilePECOFF::dos_header_t protected
rva_symbol_list_t
typedef std::vector<std::pair<uint32_t, uint32_t> > ObjectFilePECOFF::rva_symbol_list_t private
Definition at line 277 of file ObjectFilePECOFF.h.
section_header_t
typedef struct ObjectFilePECOFF::section_header ObjectFilePECOFF::section_header_t protected
SectionHeaderColl
typedef std::vector<section_header_t> ObjectFilePECOFF::SectionHeaderColl protected
Definition at line 271 of file ObjectFilePECOFF.h.
SectionHeaderCollConstIter
typedef SectionHeaderColl::const_iterator ObjectFilePECOFF::SectionHeaderCollConstIter protected
Definition at line 273 of file ObjectFilePECOFF.h.
SectionHeaderCollIter
typedef SectionHeaderColl::iterator ObjectFilePECOFF::SectionHeaderCollIter protected
Definition at line 272 of file ObjectFilePECOFF.h.
Member Enumeration Documentation
MachineType
enum ObjectFilePECOFF::MachineType
Enumerator
MachineUnknown
MachineAm33
MachineAmd64
MachineArm
MachineArmNt
MachineArm64
MachineArm64X
MachineEbc
MachineX86
MachineIA64
MachineM32R
MachineMips16
MachineMipsFpu
MachineMipsFpu16
MachinePowerPc
MachinePowerPcfp
MachineR4000
MachineSh3
MachineSh3dsp
MachineSh4
MachineSh5
MachineThumb
MachineWcemIpsv2
Definition at line 21 of file ObjectFilePECOFF.h.
Constructor & Destructor Documentation
ObjectFilePECOFF() [1/2]
ObjectFilePECOFF::ObjectFilePECOFF (const lldb::ModuleSP & module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const lldb_private::FileSpec * file, lldb::offset_t file_offset, lldb::offset_t length)
Definition at line 425 of file ObjectFilePECOFF.cpp.
References LLDB_INVALID_ADDRESS, m_coff_header, m_coff_header_opt, m_deps_filespec, m_dos_header, m_entry_point_address, m_image_base, m_sect_headers, and lldb_private::ObjectFile::ObjectFile().
ObjectFilePECOFF() [2/2]
ObjectFilePECOFF::ObjectFilePECOFF (const lldb::ModuleSP & module_sp, lldb::WritableDataBufferSP header_data_sp, const lldb::ProcessSP & process_sp, lldb::addr_t header_addr)
Definition at line 437 of file ObjectFilePECOFF.cpp.
References LLDB_INVALID_ADDRESS, m_coff_header, m_coff_header_opt, m_deps_filespec, m_dos_header, m_entry_point_address, m_image_base, m_sect_headers, and lldb_private::ObjectFile::ObjectFile().
~ObjectFilePECOFF()
ObjectFilePECOFF::~ObjectFilePECOFF () override default
Member Function Documentation
AppendFromCOFFSymbolTable()
void ObjectFilePECOFF::AppendFromCOFFSymbolTable (lldb_private::SectionList * sect_list, lldb_private::Symtab & symtab, const rva_symbol_list_t & sorted_exports) private
Definition at line 795 of file ObjectFilePECOFF.cpp.
References lldb_private::Symtab::AddSymbol(), lldb::eSymbolTypeAbsolute, lldb::eSymbolTypeAdditional, lldb::eSymbolTypeInvalid, lldb_private::SectionList::FindSectionByID(), lldb_private::Symbol::GetAddressRef(), lldb_private::Address::GetFileAddress(), lldb_private::GetLog(), lldb_private::Symbol::GetMangled(), lldb_private::Symtab::GetNumSymbols(), lldb_private::Symbol::GetType(), LLDB_LOG_ERROR, m_binary, m_coff_header_opt, MapSymbolType(), lldb_private::Object, lldb_private::Symtab::Reserve(), RVASymbolListCompareRVA(), lldb_private::Symbol::SetExternal(), lldb_private::Symbol::SetType(), lldb_private::Mangled::SetValue(), and lldb_private::Symtab::SymbolAtIndex().
Referenced by ParseSymtab().
AppendFromExportTable()
ObjectFilePECOFF::rva_symbol_list_t ObjectFilePECOFF::AppendFromExportTable (lldb_private::SectionList * sect_list, lldb_private::Symtab & symtab) private
Definition at line 863 of file ObjectFilePECOFF.cpp.
References lldb_private::Symtab::AddSymbol(), lldb::eSymbolTypeCode, lldb::eSymbolTypeData, lldb_private::Symbol::GetAddressRef(), lldb_private::Symbol::GetDisplayName(), lldb_private::GetLog(), lldb_private::Symbol::GetMangled(), lldb_private::Symtab::GetNumSymbols(), lldb_private::Address::GetSection(), lldb_private::ConstString::GetStringRef(), LLDB_LOG_ERROR, m_binary, m_coff_header_opt, lldb_private::Object, lldb_private::Symtab::Reserve(), RVASymbolListCompareRVA(), lldb_private::Mangled::SetDemangledName(), lldb_private::Symbol::SetDemangledNameIsSynthesized(), lldb_private::Symbol::SetExternal(), lldb_private::Symbol::SetID(), lldb_private::Symbol::SetType(), and lldb_private::Mangled::SetValue().
Referenced by ParseSymtab().
CalculateStrata()
ObjectFile::Strata ObjectFilePECOFF::CalculateStrata () override virtual
The object file should be able to calculate the strata of the object file.
Many object files for platforms might be for either user space debugging or for kernel debugging. If your object file subclass can figure this out, it will help with debugger plug-in selection when it comes time to debug.
Returns
The calculated object file strata for the current object file.
Implements lldb_private::ObjectFile.
Definition at line 1426 of file ObjectFilePECOFF.cpp.
References lldb_private::ObjectFile::eStrataUser.
CalculateType()
ObjectFile::Type ObjectFilePECOFF::CalculateType () override virtual
The object file should be able to calculate its type by looking at its file header and possibly the sections or other data in the object file.
The file type is used in the debugger to help select the correct plug- ins for the job at hand, so this is important to get right. If any eTypeXXX definitions do not match up with the type of file you are loading, please feel free to add a new enumeration value.
Returns
The calculated file type for the current object file.
Implements lldb_private::ObjectFile.
Definition at line 1416 of file ObjectFilePECOFF.cpp.
References lldb_private::ObjectFile::eTypeExecutable, lldb_private::ObjectFile::eTypeSharedLibrary, and m_coff_header.
classof()
bool ObjectFilePECOFF::classof (const ObjectFile * obj) inline static
Definition at line 101 of file ObjectFilePECOFF.h.
References ID, and lldb_private::ObjectFile::ObjectFile().
CreateBinary()
bool ObjectFilePECOFF::CreateBinary () private
Definition at line 399 of file ObjectFilePECOFF.cpp.
References lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), LLDB_LOG, LLDB_LOG_ERROR, m_binary, lldb_private::ObjectFile::m_data_nsp, lldb_private::ObjectFile::m_file, and lldb_private::Object.
Referenced by GetUUID(), and ParseDependentModules().
CreateCallFrameInfo()
std::unique_ptr< CallFrameInfo > ObjectFilePECOFF::CreateCallFrameInfo () override virtual
Creates a plugin-specific call frame info.
Reimplemented from lldb_private::ObjectFile.
Definition at line 941 of file ObjectFilePECOFF.cpp.
References m_coff_header, m_coff_header_opt, ObjectFilePECOFF::data_directory::vmaddr, and ObjectFilePECOFF::data_directory::vmsize.
CreateInstance()
ObjectFile * ObjectFilePECOFF::CreateInstance (const lldb::ModuleSP & module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const lldb_private::FileSpec * file, lldb::offset_t offset, lldb::offset_t length) static
Definition at line 205 of file ObjectFilePECOFF.cpp.
References MagicBytesMatch(), lldb_private::ObjectFile::MapFileData(), and lldb_private::ObjectFile::ObjectFile().
Referenced by Initialize(), and Terminate().
CreateMemoryInstance()
ObjectFile * ObjectFilePECOFF::CreateMemoryInstance (const lldb::ModuleSP & module_sp, lldb::WritableDataBufferSP data_sp, const lldb::ProcessSP & process_sp, lldb::addr_t header_addr) static
Definition at line 240 of file ObjectFilePECOFF.cpp.
References lldb::eByteOrderLittle, MagicBytesMatch(), and lldb_private::ObjectFile::ObjectFile().
Referenced by Initialize().
CreateSections()
void ObjectFilePECOFF::CreateSections (lldb_private::SectionList & unified_section_list) override virtual
Implements lldb_private::ObjectFile.
Definition at line 1035 of file ObjectFilePECOFF.cpp.
References lldb_private::SectionList::AddSection(), lldb::eSectionTypeOther, lldb_private::ModuleChild::GetModule(), GetSectionName(), GetSectionType(), m_coff_header_opt, m_sect_headers, and lldb_private::ObjectFile::m_sections_up.
DebuggerInitialize()
void ObjectFilePECOFF::DebuggerInitialize (lldb_private::Debugger & debugger) static
Definition at line 186 of file ObjectFilePECOFF.cpp.
References lldb_private::PluginManager::CreateSettingForObjectFilePlugin(), GetGlobalPluginProperties(), and lldb_private::PluginManager::GetSettingForObjectFilePlugin().
Referenced by Initialize().
Dump()
void ObjectFilePECOFF::Dump (lldb_private::Stream * s) override virtual
Dump a description of this object to a Stream.
Dump a description of the current contents of this object to the supplied stream s. The dumping should include the section list if it has been parsed, and the symbol table if it has been parsed.
Parameters
[in] s The stream to which to dump the object description.
Implements lldb_private::ObjectFile.
Definition at line 1195 of file ObjectFilePECOFF.cpp.
References lldb_private::Stream::AsRawOstream(), lldb_private::SectionList::Dump(), DumpCOFFHeader(), DumpDependentModules(), DumpDOSHeader(), DumpOptCOFFHeader(), DumpSectionHeaders(), lldb_private::Stream::EOL(), lldb_private::eSortOrderNone, GetArchitecture(), lldb_private::ArchSpec::GetArchitectureName(), lldb_private::Stream::GetIndentLevel(), lldb_private::ModuleChild::GetModule(), lldb_private::ObjectFile::GetSectionList(), lldb_private::Stream::Indent(), m_coff_header, m_coff_header_opt, m_dos_header, lldb_private::ObjectFile::m_file, lldb_private::ObjectFile::m_symtab_up, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and UINT32_MAX.
DumpCOFFHeader()
void ObjectFilePECOFF::DumpCOFFHeader (lldb_private::Stream * s, const coff_header_t & header) static protected
Definition at line 1267 of file ObjectFilePECOFF.cpp.
References ObjectFilePECOFF::coff_header::hdrsize, ObjectFilePECOFF::coff_header::machine, ObjectFilePECOFF::coff_header::modtime, ObjectFilePECOFF::coff_header::nsects, ObjectFilePECOFF::coff_header::nsyms, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and ObjectFilePECOFF::coff_header::symoff.
Referenced by Dump().
DumpDependentModules()
void ObjectFilePECOFF::DumpDependentModules (lldb_private::Stream * s) protected
Definition at line 1368 of file ObjectFilePECOFF.cpp.
References m_deps_filespec, ParseDependentModules(), lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
Referenced by Dump().
DumpDOSHeader()
void ObjectFilePECOFF::DumpDOSHeader (lldb_private::Stream * s, const dos_header_t & header) static protected
Definition at line 1235 of file ObjectFilePECOFF.cpp.
References ObjectFilePECOFF::dos_header::e_cblp, ObjectFilePECOFF::dos_header::e_cp, ObjectFilePECOFF::dos_header::e_cparhdr, ObjectFilePECOFF::dos_header::e_crlc, ObjectFilePECOFF::dos_header::e_cs, ObjectFilePECOFF::dos_header::e_csum, ObjectFilePECOFF::dos_header::e_ip, ObjectFilePECOFF::dos_header::e_lfanew, ObjectFilePECOFF::dos_header::e_lfarlc, ObjectFilePECOFF::dos_header::e_magic, ObjectFilePECOFF::dos_header::e_maxalloc, ObjectFilePECOFF::dos_header::e_minalloc, ObjectFilePECOFF::dos_header::e_oemid, ObjectFilePECOFF::dos_header::e_oeminfo, ObjectFilePECOFF::dos_header::e_ovno, ObjectFilePECOFF::dos_header::e_res, ObjectFilePECOFF::dos_header::e_res2, ObjectFilePECOFF::dos_header::e_sp, ObjectFilePECOFF::dos_header::e_ss, lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
Referenced by Dump().
DumpOptCOFFHeader()
void ObjectFilePECOFF::DumpOptCOFFHeader (lldb_private::Stream * s, const coff_opt_header_t & header) static protected
Definition at line 1280 of file ObjectFilePECOFF.cpp.
References ObjectFilePECOFF::coff_opt_header::bss_size, ObjectFilePECOFF::coff_opt_header::checksum, ObjectFilePECOFF::coff_opt_header::code_offset, ObjectFilePECOFF::coff_opt_header::code_size, ObjectFilePECOFF::coff_opt_header::data_dirs, ObjectFilePECOFF::coff_opt_header::data_offset, ObjectFilePECOFF::coff_opt_header::data_size, ObjectFilePECOFF::coff_opt_header::dll_flags, ObjectFilePECOFF::coff_opt_header::entry, ObjectFilePECOFF::coff_opt_header::file_alignment, ObjectFilePECOFF::coff_opt_header::header_size, ObjectFilePECOFF::coff_opt_header::heap_commit_size, ObjectFilePECOFF::coff_opt_header::heap_reserve_size, ObjectFilePECOFF::coff_opt_header::image_base, ObjectFilePECOFF::coff_opt_header::image_size, ObjectFilePECOFF::coff_opt_header::loader_flags, ObjectFilePECOFF::coff_opt_header::magic, ObjectFilePECOFF::coff_opt_header::major_image_version, ObjectFilePECOFF::coff_opt_header::major_linker_version, ObjectFilePECOFF::coff_opt_header::major_os_system_version, ObjectFilePECOFF::coff_opt_header::major_subsystem_version, ObjectFilePECOFF::coff_opt_header::minor_image_version, ObjectFilePECOFF::coff_opt_header::minor_linker_version, ObjectFilePECOFF::coff_opt_header::minor_os_system_version, ObjectFilePECOFF::coff_opt_header::minor_subsystem_version, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), ObjectFilePECOFF::coff_opt_header::reserved1, ObjectFilePECOFF::coff_opt_header::sect_alignment, ObjectFilePECOFF::coff_opt_header::stack_commit_size, ObjectFilePECOFF::coff_opt_header::stack_reserve_size, and ObjectFilePECOFF::coff_opt_header::subsystem.
Referenced by Dump().
DumpSectionHeader()
void ObjectFilePECOFF::DumpSectionHeader (lldb_private::Stream * s, const section_header_t & sh) protected
Definition at line 1336 of file ObjectFilePECOFF.cpp.
References ObjectFilePECOFF::section_header::flags, GetSectionName(), ObjectFilePECOFF::section_header::lineoff, ObjectFilePECOFF::section_header::nline, ObjectFilePECOFF::section_header::nreloc, ObjectFilePECOFF::section_header::offset, lldb_private::Stream::Printf(), ObjectFilePECOFF::section_header::reloff, ObjectFilePECOFF::section_header::size, ObjectFilePECOFF::section_header::vmaddr, and ObjectFilePECOFF::section_header::vmsize.
Referenced by DumpSectionHeaders().
DumpSectionHeaders()
void ObjectFilePECOFF::DumpSectionHeaders (lldb_private::Stream * s) protected
Definition at line 1348 of file ObjectFilePECOFF.cpp.
References DumpSectionHeader(), m_sect_headers, lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
Referenced by Dump().
GetAddress()
Address ObjectFilePECOFF::GetAddress (uint32_t rva)
Definition at line 686 of file ObjectFilePECOFF.cpp.
References GetFileAddress(), and lldb_private::ObjectFile::GetSectionList().
Referenced by ReadImageDataByRVA().
GetAddressByteSize()
uint32_t ObjectFilePECOFF::GetAddressByteSize () const override virtual
Gets the address size in bytes for the current object file.
Returns
The size of an address in bytes for the currently selected architecture (and object for archives). Returns zero if no architecture or object has been selected.
Implements lldb_private::ObjectFile.
Definition at line 511 of file ObjectFilePECOFF.cpp.
References m_coff_header_opt, OPT_HEADER_MAGIC_PE32, and OPT_HEADER_MAGIC_PE32_PLUS.
Referenced by ParseCOFFOptionalHeader(), and ParseHeader().
GetArchitecture()
ArchSpec ObjectFilePECOFF::GetArchitecture () override virtual
Get the ArchSpec for this object file.
Returns
The ArchSpec of this object file. In case of error, an invalid ArchSpec object is returned.
Implements lldb_private::ObjectFile.
Definition at line 1394 of file ObjectFilePECOFF.cpp.
References lldb_private::eArchTypeCOFF, IsWindowsSubsystem(), LLDB_INVALID_CPUTYPE, m_coff_header, and lldb_private::ArchSpec::SetArchitecture().
Referenced by Dump().
GetBaseAddress()
Address ObjectFilePECOFF::GetBaseAddress () override virtual
Returns base address of this object file.
This also sometimes referred to as the "preferred load address" or the "image base address". Addresses within object files are often expressed relative to this base. If this address corresponds to a specific section (usually the first byte of the first section) then the returned address will have this section set. Otherwise, the address will just have the offset member filled in, indicating that this represents a file address.
Reimplemented from lldb_private::ObjectFile.
Definition at line 1187 of file ObjectFilePECOFF.cpp.
References lldb_private::ObjectFile::GetSectionList().
GetByteOrder()
ByteOrder ObjectFilePECOFF::GetByteOrder () const override virtual
Gets whether endian swapping should occur when extracting data from this object file.
Returns
Returns true if endian swapping is needed, false otherwise.
Implements lldb_private::ObjectFile.
Definition at line 505 of file ObjectFilePECOFF.cpp.
References lldb::eByteOrderLittle.
GetDebugLink()
std::optional< FileSpec > ObjectFilePECOFF::GetDebugLink ()
Return the contents of the .gnu_debuglink section, if the object file contains it.
Definition at line 1103 of file ObjectFilePECOFF.cpp.
References GetDebugLinkContents(), and m_binary.
Referenced by SymbolVendorPECOFF::CreateInstance().
GetDependentModules()
uint32_t ObjectFilePECOFF::GetDependentModules (lldb_private::FileSpecList & file_list) override virtual
Extract the dependent modules from an object file.
If an object file has information about which other images it depends on (such as shared libraries), this function will provide the list. Since many executables or shared libraries may depend on the same files, FileSpecList::AppendIfUnique(const FileSpec &) should be used to make sure any files that are added are not already in the list.
Parameters
[out] file_list A list of file specification objects that gets dependent files appended to.
Returns
The number of new files that were appended to file_list.
See also
FileSpecList::AppendIfUnique(const FileSpec &)
Implements lldb_private::ObjectFile.
Definition at line 1159 of file ObjectFilePECOFF.cpp.
References lldb_private::FileSpecList::AppendIfUnique(), lldb_private::FileSpecList::GetSize(), m_deps_filespec, and ParseDependentModules().
GetEntryPointAddress()
lldb_private::Address ObjectFilePECOFF::GetEntryPointAddress () override virtual
Returns the address of the Entry Point in this object file - if the object file doesn't have an entry point (because it is not an executable file) then an invalid address is returned.
Returns
Returns the entry address for this module.
Reimplemented from lldb_private::ObjectFile.
Definition at line 1169 of file ObjectFilePECOFF.cpp.
References lldb_private::ObjectFile::GetSectionList(), IsExecutable(), m_coff_header_opt, m_entry_point_address, and ParseHeader().
GetFileAddress()
lldb::addr_t ObjectFilePECOFF::GetFileAddress (uint32_t rva) const
Definition at line 694 of file ObjectFilePECOFF.cpp.
References m_image_base.
Referenced by GetAddress().
GetModuleSpecifications()
size_t ObjectFilePECOFF::GetModuleSpecifications (const lldb_private::FileSpec & file, lldb::DataExtractorSP & extractor_sp, lldb::offset_t data_offset, lldb::offset_t file_offset, lldb::offset_t length, lldb_private::ModuleSpecList & specs) static
Definition at line 257 of file ObjectFilePECOFF.cpp.
References lldb_private::ModuleSpecList::Append(), lldb_private::ModuleSpec::GetArchitecture(), GetCoffUUID(), lldb_private::FileSpec::GetFilename(), GetGlobalPluginProperties(), lldb_private::GetLog(), lldb_private::ModuleSpecList::GetSize(), lldb_private::ConstString::GetStringRef(), lldb_private::ArchSpec::GetTriple(), lldb_private::ModuleSpec::GetUUID(), lldb_private::UUID::IsValid(), LLDB_LOG_ERROR, MachineAmd64, MachineArm64, MachineArm64X, MachineArmNt, MachineX86, MagicBytesMatch(), lldb_private::ObjectFile::MapFileData(), lldb_private::Object, and lldb_private::ArchSpec::SetTriple().
Referenced by Initialize().
GetPluginDescriptionStatic()
llvm::StringRef ObjectFilePECOFF::GetPluginDescriptionStatic () static
Definition at line 200 of file ObjectFilePECOFF.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef ObjectFilePECOFF::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 144 of file ObjectFilePECOFF.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef ObjectFilePECOFF::GetPluginNameStatic () inline static
Definition at line 66 of file ObjectFilePECOFF.h.
Referenced by GetPluginName(), and Initialize().
GetRVA()
uint32_t ObjectFilePECOFF::GetRVA (const lldb_private::Address & addr) const
Definition at line 682 of file ObjectFilePECOFF.cpp.
References lldb_private::Address::GetFileAddress(), and m_image_base.
GetSectionDataSize()
size_t ObjectFilePECOFF::GetSectionDataSize (lldb_private::Section * section) override protected virtual
Reimplemented from lldb_private::ObjectFile.
Definition at line 1025 of file ObjectFilePECOFF.cpp.
References lldb_private::Section::GetByteSize(), lldb_private::Section::GetFileSize(), and m_binary.
GetSectionName()
llvm::StringRef ObjectFilePECOFF::GetSectionName (const section_header_t & sect) protected
Definition at line 768 of file ObjectFilePECOFF.cpp.
References m_coff_header, lldb_private::ObjectFile::m_data_nsp, and ObjectFilePECOFF::section_header::name.
Referenced by CreateSections(), and DumpSectionHeader().
GetSectionType()
SectionType ObjectFilePECOFF::GetSectionType (llvm::StringRef sect_name, const section_header_t & sect) static protected
Definition at line 962 of file ObjectFilePECOFF.cpp.
References lldb::eSectionTypeCode, lldb::eSectionTypeData, lldb::eSectionTypeDataCString, lldb::eSectionTypeDebug, lldb::eSectionTypeEHFrame, lldb::eSectionTypeGoSymtab, lldb::eSectionTypeInvalid, lldb::eSectionTypeLLDBFormatters, lldb::eSectionTypeLLDBTypeSummaries, lldb::eSectionTypeOther, lldb::eSectionTypeSwiftModules, lldb::eSectionTypeZeroFill, ObjectFilePECOFF::section_header::flags, lldb_private::ObjectFile::GetDWARFSectionTypeFromName(), ObjectFilePECOFF::section_header::offset, and ObjectFilePECOFF::section_header::size.
Referenced by CreateSections().
GetUUID()
UUID ObjectFilePECOFF::GetUUID () override virtual
Gets the UUID for this object file.
If the object file format contains a UUID, the value should be returned. Else ObjectFile instances should return the MD5 checksum of all of the bytes for the object file (or memory for memory based object files).
Returns
The object file's UUID. In case of an error, an empty UUID is returned.
Implements lldb_private::ObjectFile.
Definition at line 1092 of file ObjectFilePECOFF.cpp.
References CreateBinary(), GetCoffUUID(), m_binary, and m_uuid.
Referenced by SymbolVendorPECOFF::CreateInstance().
Initialize()
void ObjectFilePECOFF::Initialize () static
Definition at line 179 of file ObjectFilePECOFF.cpp.
References CreateInstance(), CreateMemoryInstance(), DebuggerInitialize(), GetModuleSpecifications(), GetPluginDescriptionStatic(), GetPluginNameStatic(), lldb_private::PluginManager::RegisterPlugin(), and SaveCore().
isA()
bool ObjectFilePECOFF::isA (const void * ClassID) const inline override virtual
Reimplemented from lldb_private::ObjectFile.
Definition at line 98 of file ObjectFilePECOFF.h.
References ID.
IsExecutable()
bool ObjectFilePECOFF::IsExecutable () const override virtual
Tells whether this object file is capable of being the main executable for a process.
Returns
true if it is, false otherwise.
Implements lldb_private::ObjectFile.
Definition at line 507 of file ObjectFilePECOFF.cpp.
References m_coff_header.
Referenced by GetEntryPointAddress().
IsStripped()
bool ObjectFilePECOFF::IsStripped () override virtual
Detect if this object file has been stripped of local symbols.
Detect if this object file has been stripped of local symbols.
Returns
Return true if the object file has been stripped of local symbols.
Implements lldb_private::ObjectFile.
Definition at line 957 of file ObjectFilePECOFF.cpp.
IsWindowsSubsystem()
bool ObjectFilePECOFF::IsWindowsSubsystem ()
Definition at line 1379 of file ObjectFilePECOFF.cpp.
References m_coff_header_opt.
Referenced by GetArchitecture().
MagicBytesMatch()
bool ObjectFilePECOFF::MagicBytesMatch (lldb::DataExtractorSP extractor_sp) static
Definition at line 375 of file ObjectFilePECOFF.cpp.
References IMAGE_DOS_SIGNATURE.
Referenced by CreateInstance(), CreateMemoryInstance(), and GetModuleSpecifications().
MapSymbolType()
lldb::SymbolType ObjectFilePECOFF::MapSymbolType (uint16_t coff_symbol_type) static
Definition at line 381 of file ObjectFilePECOFF.cpp.
References lldb::eSymbolTypeCode, lldb::eSymbolTypeData, and lldb::eSymbolTypeInvalid.
Referenced by AppendFromCOFFSymbolTable().
NeedsEndianSwap()
bool ObjectFilePECOFF::NeedsEndianSwap () const protected
Definition at line 523 of file ObjectFilePECOFF.cpp.
ParseCOFFHeader()
bool ObjectFilePECOFF::ParseCOFFHeader (lldb_private::DataExtractor & data, lldb::offset_t * offset_ptr, coff_header_t & coff_header) static protected
Definition at line 590 of file ObjectFilePECOFF.cpp.
References ObjectFilePECOFF::coff_header::flags, lldb_private::DataExtractor::GetU16(), lldb_private::DataExtractor::GetU32(), ObjectFilePECOFF::coff_header::hdrsize, ObjectFilePECOFF::coff_header::machine, ObjectFilePECOFF::coff_header::modtime, ObjectFilePECOFF::coff_header::nsects, ObjectFilePECOFF::coff_header::nsyms, ObjectFilePECOFF::coff_header::symoff, and lldb_private::DataExtractor::ValidOffsetForDataOfSize().
Referenced by ParseHeader().
ParseCOFFOptionalHeader()
bool ObjectFilePECOFF::ParseCOFFOptionalHeader (lldb::offset_t * offset_ptr) protected
Definition at line 609 of file ObjectFilePECOFF.cpp.
References GetAddressByteSize(), m_coff_header, m_coff_header_opt, lldb_private::ObjectFile::m_data_nsp, m_image_base, and OPT_HEADER_MAGIC_PE32.
Referenced by ParseHeader().
ParseDependentModules()
uint32_t ObjectFilePECOFF::ParseDependentModules () protected
Definition at line 1111 of file ObjectFilePECOFF.cpp.
References CreateBinary(), lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), lldb_private::FileSpec::GetPath(), LLDB_LOG, LLDB_LOGF, m_binary, m_deps_filespec, lldb_private::ObjectFile::m_file, lldb_private::Object, and lldb_private::FileSpec::SetDirectory().
Referenced by DumpDependentModules(), and GetDependentModules().
ParseDOSHeader()
bool ObjectFilePECOFF::ParseDOSHeader (lldb_private::DataExtractor & data, dos_header_t & dos_header) static protected
Definition at line 531 of file ObjectFilePECOFF.cpp.
References ObjectFilePECOFF::dos_header::e_cblp, ObjectFilePECOFF::dos_header::e_cp, ObjectFilePECOFF::dos_header::e_cparhdr, ObjectFilePECOFF::dos_header::e_crlc, ObjectFilePECOFF::dos_header::e_cs, ObjectFilePECOFF::dos_header::e_csum, ObjectFilePECOFF::dos_header::e_ip, ObjectFilePECOFF::dos_header::e_lfanew, ObjectFilePECOFF::dos_header::e_lfarlc, ObjectFilePECOFF::dos_header::e_magic, ObjectFilePECOFF::dos_header::e_maxalloc, ObjectFilePECOFF::dos_header::e_minalloc, ObjectFilePECOFF::dos_header::e_oemid, ObjectFilePECOFF::dos_header::e_oeminfo, ObjectFilePECOFF::dos_header::e_ovno, ObjectFilePECOFF::dos_header::e_res, ObjectFilePECOFF::dos_header::e_res2, ObjectFilePECOFF::dos_header::e_sp, ObjectFilePECOFF::dos_header::e_ss, lldb_private::DataExtractor::GetU16(), lldb_private::DataExtractor::GetU32(), IMAGE_DOS_SIGNATURE, and lldb_private::DataExtractor::ValidOffsetForDataOfSize().
Referenced by ParseHeader().
ParseHeader()
bool ObjectFilePECOFF::ParseHeader () override virtual
Attempts to parse the object header.
This function is used as a test to see if a given plug-in instance can parse the header data already contained in ObjectFile::m_data_nsp. If an object file parser does not recognize that magic bytes in a header, false should be returned and the next plug-in can attempt to parse an object file.
Returns
Returns true if the header was parsed successfully, false otherwise.
Implements lldb_private::ObjectFile.
Definition at line 449 of file ObjectFilePECOFF.cpp.
References lldb::eByteOrderLittle, GetAddressByteSize(), lldb_private::ModuleChild::GetModule(), IMAGE_NT_SIGNATURE, m_coff_header, lldb_private::ObjectFile::m_data_nsp, m_dos_header, m_sect_headers, ParseCOFFHeader(), ParseCOFFOptionalHeader(), ParseDOSHeader(), and ParseSectionHeaders().
Referenced by GetEntryPointAddress().
ParseSectionHeaders()
bool ObjectFilePECOFF::ParseSectionHeaders (uint32_t offset) protected
Definition at line 732 of file ObjectFilePECOFF.cpp.
References m_coff_header, m_sect_headers, and ReadImageData().
Referenced by ParseHeader().
ParseSymtab()
void ObjectFilePECOFF::ParseSymtab (lldb_private::Symtab & symtab) override virtual
Parse the symbol table into the provides symbol table object.
Symbol table parsing will be done once when this function is called by each object file plugin. All of the necessary locks will already be acquired before this function is called and the symbol table object to populate is supplied as an argument and doesn't need to be created by each plug-in.
Parameters
The symbol table to populate.
Implements lldb_private::ObjectFile.
Definition at line 784 of file ObjectFilePECOFF.cpp.
References AppendFromCOFFSymbolTable(), AppendFromExportTable(), and lldb_private::ObjectFile::GetSectionList().
ReadImageData()
DataExtractor ObjectFilePECOFF::ReadImageData (uint32_t offset, size_t size)
Definition at line 698 of file ObjectFilePECOFF.cpp.
References lldb_private::ObjectFile::m_data_nsp, m_image_base, lldb_private::ObjectFile::m_process_wp, and lldb_private::DataExtractor::SetData().
Referenced by ParseSectionHeaders(), and ReadImageDataByRVA().
ReadImageDataByRVA()
DataExtractor ObjectFilePECOFF::ReadImageDataByRVA (uint32_t rva, size_t size)
Definition at line 721 of file ObjectFilePECOFF.cpp.
References GetAddress(), lldb_private::Address::GetOffset(), lldb_private::Address::GetSection(), and ReadImageData().
SaveCore()
bool ObjectFilePECOFF::SaveCore (const lldb::ProcessSP & process_sp, lldb_private::SaveCoreOptions & options, lldb_private::Status & error) static
Definition at line 366 of file ObjectFilePECOFF.cpp.
References error(), lldb_private::SaveCoreOptions::GetOutputFile(), and lldb_private::SaveMiniDump().
Referenced by Initialize().
SetLoadAddress()
bool ObjectFilePECOFF::SetLoadAddress (lldb_private::Target & target, lldb::addr_t value, bool value_is_offset) override virtual
Sets the load address for an entire module, assuming a rigid slide of sections, if possible in the implementation.
Returns
Returns true iff any section's load address changed.
Reimplemented from lldb_private::ObjectFile.
Definition at line 474 of file ObjectFilePECOFF.cpp.
References lldb_private::ModuleChild::GetModule(), lldb_private::SectionList::GetSectionAtIndex(), lldb_private::ObjectFile::GetSectionList(), lldb_private::SectionList::GetSize(), m_image_base, and lldb_private::Target::SetSectionLoadAddress().
Terminate()
void ObjectFilePECOFF::Terminate () static
Definition at line 196 of file ObjectFilePECOFF.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Member Data Documentation
ID
char ObjectFilePECOFF::ID static
Definition at line 97 of file ObjectFilePECOFF.h.
Referenced by classof(), and isA().
m_binary
std::unique_ptr<llvm::object::COFFObjectFile> ObjectFilePECOFF::m_binary private
Definition at line 291 of file ObjectFilePECOFF.h.
Referenced by AppendFromCOFFSymbolTable(), AppendFromExportTable(), CreateBinary(), GetDebugLink(), GetSectionDataSize(), GetUUID(), and ParseDependentModules().
m_coff_header
coff_header_t ObjectFilePECOFF::m_coff_header private
Definition at line 285 of file ObjectFilePECOFF.h.
Referenced by CalculateType(), CreateCallFrameInfo(), Dump(), GetArchitecture(), GetSectionName(), IsExecutable(), ObjectFilePECOFF(), ObjectFilePECOFF(), ParseCOFFOptionalHeader(), ParseHeader(), and ParseSectionHeaders().
m_coff_header_opt
coff_opt_header_t ObjectFilePECOFF::m_coff_header_opt private
Definition at line 286 of file ObjectFilePECOFF.h.
Referenced by AppendFromCOFFSymbolTable(), AppendFromExportTable(), CreateCallFrameInfo(), CreateSections(), Dump(), GetAddressByteSize(), GetEntryPointAddress(), IsWindowsSubsystem(), ObjectFilePECOFF(), ObjectFilePECOFF(), and ParseCOFFOptionalHeader().
m_deps_filespec
std::optional<lldb_private::FileSpecList> ObjectFilePECOFF::m_deps_filespec private
Definition at line 290 of file ObjectFilePECOFF.h.
Referenced by DumpDependentModules(), GetDependentModules(), ObjectFilePECOFF(), ObjectFilePECOFF(), and ParseDependentModules().
m_dos_header
dos_header_t ObjectFilePECOFF::m_dos_header private
Definition at line 284 of file ObjectFilePECOFF.h.
Referenced by Dump(), ObjectFilePECOFF(), ObjectFilePECOFF(), and ParseHeader().
m_entry_point_address
lldb_private::Address ObjectFilePECOFF::m_entry_point_address private
Definition at line 289 of file ObjectFilePECOFF.h.
Referenced by GetEntryPointAddress(), ObjectFilePECOFF(), and ObjectFilePECOFF().
m_image_base
lldb::addr_t ObjectFilePECOFF::m_image_base private
Definition at line 288 of file ObjectFilePECOFF.h.
Referenced by GetFileAddress(), GetRVA(), ObjectFilePECOFF(), ObjectFilePECOFF(), ParseCOFFOptionalHeader(), ReadImageData(), and SetLoadAddress().
m_sect_headers
SectionHeaderColl ObjectFilePECOFF::m_sect_headers private
Definition at line 287 of file ObjectFilePECOFF.h.
Referenced by CreateSections(), DumpSectionHeaders(), ObjectFilePECOFF(), ObjectFilePECOFF(), ParseHeader(), and ParseSectionHeaders().
m_uuid
lldb_private::UUID ObjectFilePECOFF::m_uuid private
Definition at line 292 of file ObjectFilePECOFF.h.
Referenced by GetUUID().
The documentation for this class was generated from the following files:
ObjectFilePECOFF.h
ObjectFilePECOFF.cpp