LLDB: lldb_private::RegisterInfoInterface Class Reference
lldb_private::RegisterInfoInterface Class Reference abstract
RegisterInfo interface to patch RegisterInfo structure for archs.
#include <RegisterInfoInterface.h>
Public Member Functions
RegisterInfoInterface (const lldb_private::ArchSpec &target_arch)
virtual ~RegisterInfoInterface ()=default
virtual size_t GetGPRSize () const =0
virtual const lldb_private::RegisterInfo * GetRegisterInfo () const =0
virtual uint32_t GetRegisterCount () const =0
virtual uint32_t GetUserRegisterCount () const
const lldb_private::ArchSpec & GetTargetArchitecture () const
Private Attributes
lldb_private::ArchSpec m_target_arch
Detailed Description
RegisterInfo interface to patch RegisterInfo structure for archs.
Definition at line 21 of file RegisterInfoInterface.h.
Constructor & Destructor Documentation
RegisterInfoInterface()
lldb_private::RegisterInfoInterface::RegisterInfoInterface (const lldb_private::ArchSpec & target_arch) inline
Definition at line 23 of file RegisterInfoInterface.h.
References m_target_arch.
Referenced by RegisterContextFreeBSD_i386::RegisterContextFreeBSD_i386(), RegisterContextFreeBSD_powerpc::RegisterContextFreeBSD_powerpc(), RegisterContextFreeBSD_x86_64::RegisterContextFreeBSD_x86_64(), RegisterContextLinux_s390x::RegisterContextLinux_s390x(), lldb_private::RegisterContextLinux_x86::RegisterContextLinux_x86(), RegisterContextNetBSD_i386::RegisterContextNetBSD_i386(), RegisterContextNetBSD_x86_64::RegisterContextNetBSD_x86_64(), RegisterContextOpenBSD_i386::RegisterContextOpenBSD_i386(), RegisterContextOpenBSD_x86_64::RegisterContextOpenBSD_x86_64(), RegisterContextWindows_i386::RegisterContextWindows_i386(), RegisterContextWindows_x86_64::RegisterContextWindows_x86_64(), lldb_private::RegisterInfoAndSetInterface::RegisterInfoAndSetInterface(), RegisterInfoPOSIX_ppc64::RegisterInfoPOSIX_ppc64(), and RegisterInfoPOSIX_ppc64le::RegisterInfoPOSIX_ppc64le().
~RegisterInfoInterface()
virtual lldb_private::RegisterInfoInterface::~RegisterInfoInterface () virtual default
Member Function Documentation
GetGPRSize()
virtual size_t lldb_private::RegisterInfoInterface::GetGPRSize () const pure virtual
Implemented in RegisterContextFreeBSD_i386, RegisterContextFreeBSD_powerpc32, RegisterContextFreeBSD_powerpc64, RegisterContextFreeBSD_powerpc, RegisterContextFreeBSD_x86_64, RegisterContextLinux_i386, RegisterContextLinux_s390x, RegisterContextLinux_x86_64, RegisterContextNetBSD_i386, RegisterContextNetBSD_x86_64, RegisterContextOpenBSD_i386, RegisterContextOpenBSD_x86_64, RegisterContextWindows_i386, RegisterContextWindows_x86_64, RegisterInfoPOSIX_arm64, RegisterInfoPOSIX_arm, RegisterInfoPOSIX_loongarch64, RegisterInfoPOSIX_ppc64, RegisterInfoPOSIX_ppc64le, RegisterInfoPOSIX_riscv32, and RegisterInfoPOSIX_riscv64.
Referenced by lldb_private::minidump::ConvertMinidumpContext_x86_32(), lldb_private::minidump::ConvertMinidumpContext_x86_64(), and lldb_private::process_linux::NativeRegisterContextLinux::GetGPRSize().
GetRegisterCount()
virtual uint32_t lldb_private::RegisterInfoInterface::GetRegisterCount () const pure virtual
Implemented in RegisterContextFreeBSD_i386, RegisterContextFreeBSD_powerpc32, RegisterContextFreeBSD_powerpc64, RegisterContextFreeBSD_powerpc, RegisterContextFreeBSD_x86_64, RegisterContextLinux_i386, RegisterContextLinux_s390x, RegisterContextLinux_x86_64, RegisterContextNetBSD_i386, RegisterContextNetBSD_x86_64, RegisterContextOpenBSD_i386, RegisterContextOpenBSD_x86_64, RegisterContextWindows_i386, RegisterContextWindows_x86_64, RegisterInfoPOSIX_arm64, RegisterInfoPOSIX_arm, RegisterInfoPOSIX_loongarch64, RegisterInfoPOSIX_ppc64, RegisterInfoPOSIX_ppc64le, RegisterInfoPOSIX_riscv32, and RegisterInfoPOSIX_riscv64.
Referenced by GetUserRegisterCount().
GetRegisterInfo()
virtual const lldb_private::RegisterInfo * lldb_private::RegisterInfoInterface::GetRegisterInfo () const pure virtual
Implemented in RegisterContextFreeBSD_i386, RegisterContextFreeBSD_powerpc32, RegisterContextFreeBSD_powerpc64, RegisterContextFreeBSD_powerpc, RegisterContextFreeBSD_x86_64, RegisterContextLinux_i386, RegisterContextLinux_s390x, RegisterContextLinux_x86_64, RegisterContextNetBSD_i386, RegisterContextNetBSD_x86_64, RegisterContextOpenBSD_i386, RegisterContextOpenBSD_x86_64, RegisterContextWindows_i386, RegisterContextWindows_x86_64, RegisterInfoPOSIX_arm64, RegisterInfoPOSIX_arm, RegisterInfoPOSIX_loongarch64, RegisterInfoPOSIX_ppc64, RegisterInfoPOSIX_ppc64le, RegisterInfoPOSIX_riscv32, and RegisterInfoPOSIX_riscv64.
Referenced by lldb_private::minidump::ConvertMinidumpContext_x86_32(), and lldb_private::minidump::ConvertMinidumpContext_x86_64().
GetTargetArchitecture()
const lldb_private::ArchSpec & lldb_private::RegisterInfoInterface::GetTargetArchitecture () const inline
Definition at line 40 of file RegisterInfoInterface.h.
References m_target_arch.
Referenced by RegisterContextFreeBSD_i386::GetRegisterInfo(), RegisterContextFreeBSD_powerpc64::GetRegisterInfo(), RegisterContextLinux_i386::GetRegisterInfo(), RegisterContextNetBSD_i386::GetRegisterInfo(), RegisterContextOpenBSD_i386::GetRegisterInfo(), RegisterContextCorePOSIX_powerpc::RegisterContextCorePOSIX_powerpc(), RegisterContextCorePOSIX_ppc64le::RegisterContextCorePOSIX_ppc64le(), RegisterContextCorePOSIX_s390x::RegisterContextCorePOSIX_s390x(), RegisterContextCorePOSIX_x86::RegisterContextCorePOSIX_x86(), and RegisterContextPOSIX_s390x::RegisterContextPOSIX_s390x().
GetUserRegisterCount()
virtual uint32_t lldb_private::RegisterInfoInterface::GetUserRegisterCount () const inline virtual
Reimplemented in RegisterContextLinux_i386, RegisterContextLinux_s390x, RegisterContextLinux_x86_64, RegisterContextNetBSD_x86_64, RegisterContextWindows_i386, and RegisterContextWindows_x86_64.
Definition at line 38 of file RegisterInfoInterface.h.
References GetRegisterCount().
Member Data Documentation
m_target_arch
lldb_private::ArchSpec lldb_private::RegisterInfoInterface::m_target_arch private
Definition at line 45 of file RegisterInfoInterface.h.
Referenced by GetTargetArchitecture(), and RegisterInfoInterface().
The documentation for this class was generated from the following file:
RegisterInfoInterface.h