LLDB: lldb_private::DWARFExpression::Delegate Class Reference
lldb_private::DWARFExpression::Delegate Class Reference abstract
#include <DWARFExpression.h>
Public Member Functions
Delegate ()=default
virtual ~Delegate ()=default
virtual uint16_t GetVersion () const =0
virtual dw_addr_t GetBaseAddress () const =0
virtual uint8_t GetAddressByteSize () const =0
virtual llvm::Expected< std::pair< uint64_t, bool > > GetDIEBitSizeAndSign (uint64_t relative_die_offset) const =0
virtual dw_addr_t ReadAddressFromDebugAddrSection (uint32_t index) const =0
virtual lldb::offset_t GetVendorDWARFOpcodeSize (const DataExtractor &data, const lldb::offset_t data_offset, const uint8_t op) const =0
virtual bool ParseVendorDWARFOpcode (uint8_t op, const DataExtractor &opcodes, lldb::offset_t &offset, RegisterContext *reg_ctx, lldb::RegisterKind reg_kind, Stack &stack) const =0
Delegate (const Delegate &)=delete
Delegate & operator= (const Delegate &)=delete
Detailed Description
Definition at line 40 of file DWARFExpression.h.
Constructor & Destructor Documentation
Delegate() [1/2]
lldb_private::DWARFExpression::Delegate::Delegate () default
Referenced by Delegate(), and operator=().
~Delegate()
virtual lldb_private::DWARFExpression::Delegate::~Delegate () virtual default
Delegate() [2/2]
lldb_private::DWARFExpression::Delegate::Delegate (const Delegate &) delete
References Delegate().
Member Function Documentation
GetAddressByteSize()
virtual uint8_t lldb_private::DWARFExpression::Delegate::GetAddressByteSize () const pure virtual
Implemented in lldb_private::plugin::dwarf::DWARFUnit.
Referenced by GetOpcodeDataSize().
GetBaseAddress()
virtual dw_addr_t lldb_private::DWARFExpression::Delegate::GetBaseAddress () const pure virtual
Implemented in lldb_private::plugin::dwarf::DWARFUnit.
GetDIEBitSizeAndSign()
virtual llvm::Expected< std::pair< uint64_t, bool > > lldb_private::DWARFExpression::Delegate::GetDIEBitSizeAndSign (uint64_t relative_die_offset) const pure virtual
Implemented in lldb_private::plugin::dwarf::DWARFUnit.
Referenced by lldb_private::DWARFExpression::Evaluate().
GetVendorDWARFOpcodeSize()
virtual lldb::offset_t lldb_private::DWARFExpression::Delegate::GetVendorDWARFOpcodeSize (const DataExtractor & data, const lldb::offset_t data_offset, const uint8_t op) const pure virtual
Implemented in lldb_private::plugin::dwarf::DWARFUnit.
Referenced by GetOpcodeDataSize().
GetVersion()
virtual uint16_t lldb_private::DWARFExpression::Delegate::GetVersion () const pure virtual
Implemented in lldb_private::plugin::dwarf::DWARFUnit.
operator=()
Delegate & lldb_private::DWARFExpression::Delegate::operator= (const Delegate &) delete
References Delegate().
ParseVendorDWARFOpcode()
virtual bool lldb_private::DWARFExpression::Delegate::ParseVendorDWARFOpcode (uint8_t op, const DataExtractor & opcodes, lldb::offset_t & offset, RegisterContext * reg_ctx, lldb::RegisterKind reg_kind, Stack & stack) const pure virtual
Referenced by lldb_private::DWARFExpression::Evaluate().
ReadAddressFromDebugAddrSection()
virtual dw_addr_t lldb_private::DWARFExpression::Delegate::ReadAddressFromDebugAddrSection (uint32_t index) const pure virtual
Implemented in lldb_private::plugin::dwarf::DWARFUnit.
Referenced by lldb_private::DWARFExpression::Evaluate(), and lldb_private::DWARFExpression::GetLocation_DW_OP_addr().
The documentation for this class was generated from the following file:
DWARFExpression.h