LLDB: lldb_private::FormattersContainer< ValueType > Class Template Reference
lldb_private::FormattersContainer< ValueType > Class Template Reference
#include <FormattersContainer.h>
Public Types
typedef std::shared_ptr< ValueType > ValueSP
typedef std::vector< std::pair< TypeMatcher, ValueSP > > MapType
typedef std::function< bool(const TypeMatcher &, const ValueSP &)> ForEachCallback
typedef std::shared_ptr< FormattersContainer< ValueType > > SharedPointer
Public Member Functions
FormattersContainer (IFormatChangeListener *lst)
void Add (TypeMatcher matcher, const ValueSP &entry)
bool Delete (TypeMatcher matcher)
bool Get (FormattersMatchCandidate candidate, ValueSP &entry)
bool Get (const FormattersMatchVector &candidates, ValueSP &entry)
bool GetExact (TypeMatcher matcher, ValueSP &entry)
ValueSP GetAtIndex (size_t index)
lldb::TypeNameSpecifierImplSP GetTypeNameSpecifierAtIndex (size_t index)
void Clear ()
void ForEach (ForEachCallback callback)
uint32_t GetCount ()
void AutoComplete (CompletionRequest &request)
Protected Member Functions
FormattersContainer (const FormattersContainer &)=delete
const FormattersContainer & operator= (const FormattersContainer &)=delete
Protected Attributes
MapType m_map
std::recursive_mutex m_map_mutex
IFormatChangeListener * listener
Friends
class TypeCategoryImpl
Detailed Description
template<typename ValueType>
class lldb_private::FormattersContainer< ValueType >
Definition at line 137 of file FormattersContainer.h.
Member Typedef Documentation
ForEachCallback
template<typename ValueType> typedef std::function<bool(const TypeMatcher &, const ValueSP &)> lldb_private::FormattersContainer< ValueType >::ForEachCallback
Definition at line 142 of file FormattersContainer.h.
MapType
template<typename ValueType> typedef std::vector<std::pair<TypeMatcher, ValueSP> > lldb_private::FormattersContainer< ValueType >::MapType
Definition at line 140 of file FormattersContainer.h.
SharedPointer
template<typename ValueType> typedef std::shared_ptr<FormattersContainer<ValueType> > lldb_private::FormattersContainer< ValueType >::SharedPointer
Definition at line 144 of file FormattersContainer.h.
ValueSP
template<typename ValueType> typedef std::shared_ptr<ValueType> lldb_private::FormattersContainer< ValueType >::ValueSP
Definition at line 139 of file FormattersContainer.h.
Constructor & Destructor Documentation
FormattersContainer() [1/2]
template<typename ValueType> lldb_private::FormattersContainer< ValueType >::FormattersContainer (IFormatChangeListener * lst) inline
Definition at line 148 of file FormattersContainer.h.
FormattersContainer() [2/2]
template<typename ValueType> lldb_private::FormattersContainer< ValueType >::FormattersContainer (const FormattersContainer< ValueType > &) protected delete
Member Function Documentation
Add()
template<typename ValueType> void lldb_private::FormattersContainer< ValueType >::Add (TypeMatcher matcher, const ValueSP & entry) inline
Definition at line 150 of file FormattersContainer.h.
Referenced by lldb_private::DataVisualization::NamedSummaryFormats::Add().
AutoComplete()
template<typename ValueType> void lldb_private::FormattersContainer< ValueType >::AutoComplete (CompletionRequest & request) inline
Definition at line 251 of file FormattersContainer.h.
Clear()
template<typename ValueType> void lldb_private::FormattersContainer< ValueType >::Clear () inline
Definition at line 228 of file FormattersContainer.h.
Referenced by lldb_private::DataVisualization::NamedSummaryFormats::Clear().
Delete()
template<typename ValueType> bool lldb_private::FormattersContainer< ValueType >::Delete (TypeMatcher matcher) inline
Definition at line 163 of file FormattersContainer.h.
Referenced by lldb_private::FormattersContainer< TypeSummaryImpl >::Add(), and lldb_private::DataVisualization::NamedSummaryFormats::Delete().
ForEach()
template<typename ValueType> void lldb_private::FormattersContainer< ValueType >::ForEach (ForEachCallback callback) inline
Definition at line 235 of file FormattersContainer.h.
Referenced by lldb_private::FormattersContainer< TypeSummaryImpl >::AutoComplete(), and lldb_private::DataVisualization::NamedSummaryFormats::ForEach().
Get() [1/2]
template<typename ValueType> bool lldb_private::FormattersContainer< ValueType >::Get (const FormattersMatchVector & candidates, ValueSP & entry) inline
Definition at line 189 of file FormattersContainer.h.
Get() [2/2]
template<typename ValueType> bool lldb_private::FormattersContainer< ValueType >::Get (FormattersMatchCandidate candidate, ValueSP & entry) inline
Definition at line 176 of file FormattersContainer.h.
Referenced by lldb_private::FormattersContainer< TypeSummaryImpl >::Get().
GetAtIndex()
template<typename ValueType> ValueSP lldb_private::FormattersContainer< ValueType >::GetAtIndex (size_t index) inline
Definition at line 211 of file FormattersContainer.h.
GetCount()
template<typename ValueType> uint32_t lldb_private::FormattersContainer< ValueType >::GetCount () inline
Definition at line 246 of file FormattersContainer.h.
Referenced by lldb_private::DataVisualization::NamedSummaryFormats::GetCount().
GetExact()
template<typename ValueType> bool lldb_private::FormattersContainer< ValueType >::GetExact (TypeMatcher matcher, ValueSP & entry) inline
Definition at line 201 of file FormattersContainer.h.
Referenced by lldb_private::DataVisualization::NamedSummaryFormats::GetSummaryFormat().
GetTypeNameSpecifierAtIndex()
template<typename ValueType> lldb::TypeNameSpecifierImplSP lldb_private::FormattersContainer< ValueType >::GetTypeNameSpecifierAtIndex (size_t index) inline
Definition at line 218 of file FormattersContainer.h.
operator=()
template<typename ValueType> const FormattersContainer & lldb_private::FormattersContainer< ValueType >::operator= (const FormattersContainer< ValueType > &) protected delete
Friends And Related Symbol Documentation
TypeCategoryImpl
template<typename ValueType> friend class TypeCategoryImpl friend
Definition at line 146 of file FormattersContainer.h.
Member Data Documentation
listener
template<typename ValueType> IFormatChangeListener* lldb_private::FormattersContainer< ValueType >::listener protected
Definition at line 264 of file FormattersContainer.h.
m_map
template<typename ValueType> MapType lldb_private::FormattersContainer< ValueType >::m_map protected
Definition at line 262 of file FormattersContainer.h.
m_map_mutex
template<typename ValueType> std::recursive_mutex lldb_private::FormattersContainer< ValueType >::m_map_mutex protected
Definition at line 263 of file FormattersContainer.h.
The documentation for this class was generated from the following file:
FormattersContainer.h