LLDB: lldb_private::plugin::dwarf::DWARFBaseDIE Class Reference
lldb_private::plugin::dwarf::DWARFBaseDIE Class Reference
#include <DWARFBaseDIE.h>
Public Types
enum class Recurse : bool { no , yes }
using DWARFFormValue = dwarf::DWARFFormValue
Public Member Functions
DWARFBaseDIE ()=default
DWARFBaseDIE (DWARFUnit *cu, DWARFDebugInfoEntry *die)
DWARFBaseDIE (const DWARFUnit *cu, DWARFDebugInfoEntry *die)
DWARFBaseDIE (DWARFUnit *cu, const DWARFDebugInfoEntry *die)
DWARFBaseDIE (const DWARFUnit *cu, const DWARFDebugInfoEntry *die)
operator bool () const
bool IsValid () const
bool HasChildren () const
bool Supports_DW_AT_APPLE_objc_complete_type () const
SymbolFileDWARF * GetDWARF () const
DWARFUnit * GetCU () const
DWARFDebugInfoEntry * GetDIE () const
std::optional< DIERef > GetDIERef () const
void Set (DWARFUnit *cu, DWARFDebugInfoEntry *die)
void Clear ()
const DWARFDataExtractor & GetData () const
dw_tag_t Tag () const
dw_offset_t GetOffset () const
lldb::user_id_t GetID () const
const char * GetName () const
lldb::ModuleSP GetModule () const
const char * GetAttributeValueAsString (const dw_attr_t attr, const char *fail_value) const
uint64_t GetAttributeValueAsUnsigned (const dw_attr_t attr, uint64_t fail_value) const
std::optional< uint64_t > GetAttributeValueAsOptionalUnsigned (const dw_attr_t attr) const
uint64_t GetAttributeValueAsAddress (const dw_attr_t attr, uint64_t fail_value) const
DWARFAttributes GetAttributes (Recurse recurse=Recurse::yes) const
dw_tag_t getTag () const
const char * getShortName () const
Protected Attributes
DWARFUnit * m_cu = nullptr
DWARFDebugInfoEntry * m_die = nullptr
Detailed Description
Definition at line 29 of file DWARFBaseDIE.h.
Member Typedef Documentation
DWARFFormValue
using lldb_private::plugin::dwarf::DWARFBaseDIE::DWARFFormValue = dwarf::DWARFFormValue
Definition at line 31 of file DWARFBaseDIE.h.
Member Enumeration Documentation
Recurse
enum class lldb_private::plugin::dwarf::DWARFBaseDIE::Recurse : bool strong
Enumerator
no
yes
Definition at line 119 of file DWARFBaseDIE.h.
Constructor & Destructor Documentation
DWARFBaseDIE() [1/5]
lldb_private::plugin::dwarf::DWARFBaseDIE::DWARFBaseDIE () default
DWARFBaseDIE() [2/5]
lldb_private::plugin::dwarf::DWARFBaseDIE::DWARFBaseDIE (DWARFUnit * cu, DWARFDebugInfoEntry * die) inline
Definition at line 34 of file DWARFBaseDIE.h.
References m_cu, and m_die.
DWARFBaseDIE() [3/5]
lldb_private::plugin::dwarf::DWARFBaseDIE::DWARFBaseDIE (const DWARFUnit * cu, DWARFDebugInfoEntry * die) inline
Definition at line 37 of file DWARFBaseDIE.h.
References m_cu, and m_die.
DWARFBaseDIE() [4/5]
lldb_private::plugin::dwarf::DWARFBaseDIE::DWARFBaseDIE (DWARFUnit * cu, const DWARFDebugInfoEntry * die) inline
Definition at line 40 of file DWARFBaseDIE.h.
References m_cu, and m_die.
DWARFBaseDIE() [5/5]
lldb_private::plugin::dwarf::DWARFBaseDIE::DWARFBaseDIE (const DWARFUnit * cu, const DWARFDebugInfoEntry * die) inline
Definition at line 43 of file DWARFBaseDIE.h.
References m_cu, and m_die.
Member Function Documentation
Clear()
void lldb_private::plugin::dwarf::DWARFBaseDIE::Clear () inline
Definition at line 74 of file DWARFBaseDIE.h.
References m_cu, and m_die.
Referenced by DWARFASTParserClang::GetUniqueTypeNameAndDeclaration(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseTypes(), and Set().
GetAttributes()
DWARFAttributes DWARFBaseDIE::GetAttributes (Recurse recurse = Recurse::yes) const
Definition at line 110 of file DWARFBaseDIE.cpp.
References IsValid(), m_cu, and m_die.
Referenced by lldb_private::plugin::dwarf::DWARFASTParser::GetTypeForDIE(), DWARFASTParserClang::MemberAttributes::MemberAttributes(), ParsedDWARFTypeAttributes::ParsedDWARFTypeAttributes(), DWARFASTParserClang::ParseInheritance(), DWARFASTParserClang::ParseTemplateDIE(), and lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE().
GetAttributeValueAsAddress()
uint64_t DWARFBaseDIE::GetAttributeValueAsAddress (const dw_attr_t attr, uint64_t fail_value) const
Definition at line 61 of file DWARFBaseDIE.cpp.
References GetCU(), IsValid(), and m_die.
GetAttributeValueAsOptionalUnsigned()
std::optional< uint64_t > DWARFBaseDIE::GetAttributeValueAsOptionalUnsigned (const dw_attr_t attr) const
Definition at line 55 of file DWARFBaseDIE.cpp.
References GetCU(), IsValid(), and m_die.
GetAttributeValueAsString()
const char * DWARFBaseDIE::GetAttributeValueAsString (const dw_attr_t attr, const char * fail_value) const
Definition at line 38 of file DWARFBaseDIE.cpp.
References GetCU(), IsValid(), and m_die.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::GetCompileOptions(), lldb_private::plugin::dwarf::DebugNamesDWARFIndex::GetForeignTypeUnit(), DWARFASTParserClang::GetOwningClangModule(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseImportedModules(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseXcodeSDK(), and lldb_private::plugin::dwarf::SymbolFileDWARF::UpdateExternalModuleListIfNeeded().
GetAttributeValueAsUnsigned()
uint64_t DWARFBaseDIE::GetAttributeValueAsUnsigned (const dw_attr_t attr, uint64_t fail_value) const
Definition at line 46 of file DWARFBaseDIE.cpp.
References GetCU(), IsValid(), and m_die.
Referenced by lldb_private::plugin::dwarf::DWARFDIE::AppendTypeName(), lldb_private::plugin::dwarf::SymbolFileDWARF::CollectCallEdges(), DWARFASTParserClang::CompleteRecordType(), DWARFASTParserClang::CopyUniqueClassMethodTypes(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindCompleteObjCDefinitionTypeForDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindDefinitionDIE(), lldb_private::plugin::dwarf::DebugNamesDWARFIndex::GetCompleteObjCClass(), lldb_private::plugin::dwarf::DWARFUnit::GetDIEBitSizeAndSign(), DWARFASTParserClang::GetObjectParameter(), GetPtrAuthMofidierPayload(), IsClangModuleFwdDecl(), DWARFASTParserClang::ParseChildParameters(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseDebugMacros(), DWARFASTParserClang::ParseSingleMember(), DWARFASTParserClang::ParseTypeModifier(), lldb_private::plugin::dwarf::DebugNamesDWARFIndex::ProcessEntry(), lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveFunctionCallLabel(), and DWARFASTParserClang::ResolveNamespaceDIE().
GetCU()
DWARFUnit * lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU () const inline
Definition at line 59 of file DWARFBaseDIE.h.
References m_cu.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::CompleteType(), lldb_private::plugin::dwarf::SymbolFileDWARF::ConstructFunctionDemangledName(), DWARFASTParserClang::CopyUniqueClassMethodTypes(), lldb_private::plugin::dwarf::SymbolFileDWARF::DIEInDeclContext(), ExtractDataMemberLocation(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindDefinitionDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindGlobalVariables(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindGlobalVariables(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindNamespace(), fixupExternalAddrZeroVariable(), GetAttributes(), lldb_private::plugin::dwarf::DWARFDebugInfoEntry::GetAttributeValue(), GetAttributeValueAsAddress(), GetAttributeValueAsOptionalUnsigned(), lldb_private::plugin::dwarf::DWARFDIE::GetAttributeValueAsReferenceDIE(), GetAttributeValueAsString(), GetAttributeValueAsUnsigned(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetContainingDeclContext(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDecl(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDeclContext(), lldb_private::plugin::dwarf::DWARFDIE::GetDIENamesAndRanges(), GetExprListFromAtConstValue(), GetExprListFromAtLocation(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetFunction(), lldb_private::plugin::dwarf::DWARFDIE::GetName(), DWARFASTParserClang::GetObjectParameter(), lldb_private::plugin::dwarf::DWARFDIE::GetReferencedDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetTypeForDIE(), GetUnitName(), IsSizeAndDeclarationMatching(), DWARFASTParserClang::MapDeclDIEToDefDIE(), lldb_private::plugin::dwarf::operator==(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseBlocksRecursive(), DWARFASTParserClang::ParseChildMembers(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseFunction(), DWARFASTParserClang::ParseFunctionFromDWARF(), DWARFASTParserClang::ParseRustVariantPart(), DWARFASTParserClang::ParseSingleMember(), DWARFASTParserClang::ParseStructureLikeDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseType(), DWARFASTParserClang::ParseTypeFromClangModule(), DWARFASTParserClang::ParseTypeModifier(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariablesForContext(), and lldb_private::plugin::dwarf::DWARFIndex::ProcessTypeDIEMatchQuery().
GetData()
const DWARFDataExtractor & DWARFBaseDIE::GetData () const
Definition at line 128 of file DWARFBaseDIE.cpp.
References IsValid(), and m_cu.
Referenced by ExtractDataMemberLocation(), GetExprListFromAtConstValue(), and GetExprListFromAtLocation().
GetDIE()
DWARFDebugInfoEntry * lldb_private::plugin::dwarf::DWARFBaseDIE::GetDIE () const inline
Definition at line 61 of file DWARFBaseDIE.h.
References m_die.
Referenced by lldb_private::plugin::dwarf::operator==(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseCompileUnit(), and lldb_private::plugin::dwarf::SymbolFileDWARF::UpdateExternalModuleListIfNeeded().
GetDIERef()
std::optional< DIERef > DWARFBaseDIE::GetDIERef () const
Definition at line 23 of file DWARFBaseDIE.cpp.
References IsValid(), m_cu, and m_die.
Referenced by GetID(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexUnitImpl(), lldb_private::plugin::dwarf::SymbolFileDWARF::MergeBlockAbstractParameters(), DWARFASTParserClang::ParseStructureLikeDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseType(), and lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariablesInFunctionContextRecursive().
GetDWARF()
SymbolFileDWARF * DWARFBaseDIE::GetDWARF () const
Definition at line 99 of file DWARFBaseDIE.cpp.
References m_cu.
Referenced by DWARFASTParserClang::CompleteRecordType(), DWARFASTParserClang::CompleteTypeFromDWARF(), DWARFASTParserClang::CopyUniqueClassMethodTypes(), DWARFASTParserClang::GetClangDeclContextContainingDIE(), DWARFASTParserClang::GetClangDeclContextForDIE(), DWARFASTParserClang::GetClangDeclForDIE(), GetContainingClangModule(), GetModule(), GetPtrAuthMofidierPayload(), lldb_private::plugin::dwarf::DWARFASTParser::GetTypeForDIE(), MakeLLDBFuncAsmLabel(), DWARFASTParserClang::MapDeclDIEToDefDIE(), DWARFASTParserClang::ParseArrayType(), DWARFASTParserClang::ParseChildMembers(), DWARFASTParserClang::ParseCXXMethod(), DWARFASTParserClang::ParseEnum(), DWARFASTParserClang::ParseFunctionFromDWARF(), DWARFASTParserClang::ParseObjCMethod(), DWARFASTParserClang::ParseObjCProperty(), DWARFASTParserClang::ParsePointerToMemberType(), DWARFASTParserClang::ParseRustVariantPart(), DWARFASTParserClang::ParseSingleMember(), DWARFASTParserClang::ParseStructureLikeDIE(), DWARFASTParserClang::ParseSubroutine(), DWARFASTParserClang::ParseTypeFromClangModule(), DWARFASTParserClang::ParseTypeFromDWARF(), DWARFASTParserClang::ParseTypeModifier(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIECached(), PrepareContextToReceiveMembers(), lldb_private::plugin::dwarf::DWARFIndex::ProcessFunctionDIE(), lldb_private::plugin::dwarf::DWARFDIE::ResolveType(), and lldb_private::plugin::dwarf::DWARFDIE::ResolveTypeUID().
GetID()
lldb::user_id_t DWARFBaseDIE::GetID () const
Definition at line 69 of file DWARFBaseDIE.cpp.
References GetDIERef(), and LLDB_INVALID_UID.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::CompleteType(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindCompleteObjCDefinitionTypeForDIE(), DWARFASTParserClang::GetClangDeclForDIE(), GetDeclContextImpl(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetFunction(), GetTypeLookupContextImpl(), lldb_private::plugin::dwarf::DWARFDIE::LookupDeepestBlock(), MakeLLDBFuncAsmLabel(), DWARFASTParserClang::MapDeclDIEToDefDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseAndAppendGlobalVariable(), DWARFASTParserClang::ParseArrayType(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseBlocksRecursive(), DWARFASTParserClang::ParseCXXMethod(), DWARFASTParserClang::ParseEnum(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseFunction(), DWARFASTParserClang::ParseFunctionFromDWARF(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseFunctions(), DWARFASTParserClang::ParseObjCMethod(), DWARFASTParserClang::ParseObjCProperty(), DWARFASTParserClang::ParsePointerToMemberType(), DWARFASTParserClang::ParseSingleMember(), DWARFASTParserClang::ParseStructureLikeDIE(), DWARFASTParserClang::ParseSubroutine(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseType(), DWARFASTParserClang::ParseTypeFromClangModule(), DWARFASTParserClang::ParseTypeModifier(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseTypes(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariablesForContext(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariablesInFunctionContextRecursive(), lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveFunction(), lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveFunctionAndBlock(), DWARFASTParserClang::UpdateSymbolContextScopeForType(), and lldb_private::plugin::dwarf::UniqueDWARFASTType::UpdateToDefDIE().
GetModule()
lldb::ModuleSP DWARFBaseDIE::GetModule () const
Definition at line 84 of file DWARFBaseDIE.cpp.
References GetDWARF().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::ParseFunction().
GetName()
const char * DWARFBaseDIE::GetName () const
Definition at line 77 of file DWARFBaseDIE.cpp.
References IsValid(), m_cu, and m_die.
Referenced by getShortName(), and lldb_private::plugin::dwarf::SymbolFileDWARF::ParseCompileUnit().
GetOffset()
dw_offset_t DWARFBaseDIE::GetOffset () const
Definition at line 92 of file DWARFBaseDIE.cpp.
References DW_INVALID_OFFSET, IsValid(), and m_die.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::FindBlockContainingSpecification(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindDefinitionDIE(), GetPtrAuthMofidierPayload(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetTypes(), DWARFASTParserClang::ParseCXXMethod(), DWARFASTParserClang::ParseEnum(), DWARFASTParserClang::ParseInheritance(), DWARFASTParserClang::ParseObjCMethod(), DWARFASTParserClang::ParseObjCProperty(), DWARFASTParserClang::ParseSingleMember(), DWARFASTParserClang::ParseTypeFromDWARF(), DWARFASTParserClang::ParseTypeModifier(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariablesInFunctionContextRecursive(), PrepareContextToReceiveMembers(), lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveFunction(), lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveType(), and lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveTypeUID().
getShortName()
const char * lldb_private::plugin::dwarf::DWARFBaseDIE::getShortName () const inline
Definition at line 126 of file DWARFBaseDIE.h.
References GetName().
getTag()
dw_tag_t lldb_private::plugin::dwarf::DWARFBaseDIE::getTag () const inline
Definition at line 124 of file DWARFBaseDIE.h.
References Tag().
HasChildren()
bool DWARFBaseDIE::HasChildren () const
Definition at line 106 of file DWARFBaseDIE.cpp.
References m_die.
Referenced by DWARFASTParserClang::CompleteEnumType(), lldb_private::plugin::dwarf::SymbolFileDWARF::MergeBlockAbstractParameters(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseBlocksRecursive(), DWARFASTParserClang::ParseCXXMethod(), DWARFASTParserClang::ParseSubroutine(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseTypes(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseTypes(), and lldb_private::plugin::dwarf::SymbolFileDWARF::UpdateExternalModuleListIfNeeded().
IsValid()
bool lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid () const inline
Definition at line 50 of file DWARFBaseDIE.h.
References m_cu, and m_die.
Referenced by lldb_private::plugin::dwarf::DWARFDIE::AppendTypeName(), lldb_private::plugin::dwarf::SymbolFileDWARF::ConstructFunctionDemangledName(), DWARFASTParserClang::CopyUniqueClassMethodTypes(), lldb_private::plugin::dwarf::DWARFUnit::ExtractUnitDIEIfNeeded(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindFunctionDefinition(), GetAttributes(), GetAttributeValueAsAddress(), GetAttributeValueAsOptionalUnsigned(), lldb_private::plugin::dwarf::DWARFDIE::GetAttributeValueAsReferenceDIE(), GetAttributeValueAsString(), GetAttributeValueAsUnsigned(), DWARFASTParserClang::GetClangDeclForDIE(), GetContainingClangModule(), GetContainingClangModuleDIE(), GetData(), lldb_private::plugin::dwarf::DWARFDIE::GetDIE(), lldb_private::plugin::dwarf::DWARFDIE::GetDIENamesAndRanges(), GetDIERef(), lldb_private::plugin::dwarf::DWARFDIE::GetFirstChild(), lldb_private::plugin::dwarf::DWARFDIE::getLanguage(), lldb_private::plugin::dwarf::DWARFDIE::GetMangledName(), GetName(), lldb_private::plugin::dwarf::DWARFDIE::GetName(), GetOffset(), DWARFASTParserClang::GetOwningClangModule(), lldb_private::plugin::dwarf::DWARFDIE::GetParent(), lldb_private::plugin::dwarf::DWARFDIE::GetPubname(), lldb_private::plugin::dwarf::DWARFDIE::GetReferencedDIE(), lldb_private::plugin::dwarf::DWARFDIE::GetSibling(), DWARFASTParserClang::GetUniqueTypeNameAndDeclaration(), lldb_private::plugin::dwarf::DWARFDIE::LookupDeepestBlock(), operator bool(), lldb_private::plugin::dwarf::DWARFDIE::child_iterator::operator==(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseCallEdgesInFunction(), DWARFASTParserClang::ParseCXXMethod(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseFunction(), lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveFunctionCallLabel(), lldb_private::plugin::dwarf::DWARFDIE::resolveReferencedType(), and lldb_private::plugin::dwarf::DWARFDIE::ResolveType().
operator bool()
lldb_private::plugin::dwarf::DWARFBaseDIE::operator bool () const inline explicit
Definition at line 48 of file DWARFBaseDIE.h.
References IsValid().
Set()
void lldb_private::plugin::dwarf::DWARFBaseDIE::Set (DWARFUnit * cu, DWARFDebugInfoEntry * die) inline
Definition at line 65 of file DWARFBaseDIE.h.
References Clear(), m_cu, and m_die.
Supports_DW_AT_APPLE_objc_complete_type()
bool lldb_private::plugin::dwarf::DWARFBaseDIE::Supports_DW_AT_APPLE_objc_complete_type () const
Tag()
dw_tag_t DWARFBaseDIE::Tag () const
Definition at line 31 of file DWARFBaseDIE.cpp.
References m_die.
Referenced by lldb_private::plugin::dwarf::DWARFDIE::AppendTypeName(), lldb_private::plugin::dwarf::SymbolFileDWARF::CompleteType(), DWARFASTParserClang::CompleteTypeFromDWARF(), DWARFASTParserClang::CopyUniqueClassMethodTypes(), DWARFASTParserClang::CreateStaticMemberVariable(), lldb_private::plugin::dwarf::SymbolFileDWARF::DIEInDeclContext(), lldb_private::plugin::dwarf::UniqueDWARFASTTypeList::Find(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindBlockContainingSpecification(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindCompleteObjCDefinitionTypeForDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindDefinitionDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindGlobalVariables(), DWARFASTParserClang::GetClangDeclContextForDIE(), DWARFASTParserClang::GetClangDeclForDIE(), GetContextEntry(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDeclContextDIEContainingDIE(), DWARFASTParserClang::GetDeclContextForBlock(), GetDeclContextImpl(), GetDefaultAccessibility(), GetDWARFDeclContextImpl(), DWARFASTParserClang::GetObjectParameter(), GetParentDeclContextDIEImpl(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetParentSymbolContextDIE(), getTag(), GetTypeLookupContextImpl(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetTypes(), DWARFASTParserClang::GetUniqueTypeNameAndDeclaration(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexUnit(), lldb_private::plugin::dwarf::DWARFDIE::IsStructUnionOrClass(), IsSubroutine(), lldb_private::plugin::dwarf::DWARFDIE::LookupDeepestBlock(), DWARFASTParserClang::MapDeclDIEToDefDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::MergeBlockAbstractParameters(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseAndAppendGlobalVariable(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseBlocksRecursive(), DWARFASTParserClang::ParseChildMembers(), DWARFASTParserClang::ParseChildParameters(), DWARFASTParserClang::ParseEnum(), DWARFASTParserClang::ParseFunctionFromDWARF(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseImportedModules(), DWARFASTParserClang::ParseObjCMethod(), DWARFASTParserClang::ParseObjCProperty(), DWARFASTParserClang::ParseRustVariantPart(), DWARFASTParserClang::ParseSingleMember(), DWARFASTParserClang::ParseStructureLikeDIE(), DWARFASTParserClang::ParseSubroutine(), DWARFASTParserClang::ParseTemplateDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseType(), DWARFASTParserClang::ParseTypeFromDWARF(), DWARFASTParserClang::ParseTypeModifier(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseTypes(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariablesInFunctionContextRecursive(), DWARFASTParserClang::ResolveBlockDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveFunction(), DWARFASTParserClang::ResolveImportedDeclarationDIE(), DWARFASTParserClang::ResolveNamespaceDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveType(), lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveTypeUID(), and DWARFASTParserClang::UpdateSymbolContextScopeForType().
Member Data Documentation
m_cu
DWARFUnit* lldb_private::plugin::dwarf::DWARFBaseDIE::m_cu = nullptr protected
Definition at line 129 of file DWARFBaseDIE.h.
Referenced by Clear(), DWARFBaseDIE(), DWARFBaseDIE(), DWARFBaseDIE(), DWARFBaseDIE(), lldb_private::plugin::dwarf::DWARFDIE::find(), GetAttributes(), GetCU(), GetData(), lldb_private::plugin::dwarf::DWARFDIE::GetDIE(), GetDIERef(), GetDWARF(), lldb_private::plugin::dwarf::DWARFDIE::GetFirstChild(), lldb_private::plugin::dwarf::DWARFDIE::getLanguage(), lldb_private::plugin::dwarf::DWARFDIE::GetMangledName(), GetName(), lldb_private::plugin::dwarf::DWARFDIE::GetParent(), lldb_private::plugin::dwarf::DWARFDIE::GetPubname(), lldb_private::plugin::dwarf::DWARFDIE::GetSibling(), IsValid(), lldb_private::plugin::dwarf::DWARFDIE::LookupDeepestBlock(), and Set().
m_die
DWARFDebugInfoEntry* lldb_private::plugin::dwarf::DWARFBaseDIE::m_die = nullptr protected
Definition at line 130 of file DWARFBaseDIE.h.
Referenced by Clear(), DWARFBaseDIE(), DWARFBaseDIE(), DWARFBaseDIE(), DWARFBaseDIE(), lldb_private::plugin::dwarf::UniqueDWARFASTTypeList::Find(), lldb_private::plugin::dwarf::DWARFDIE::find(), GetAttributes(), GetAttributeValueAsAddress(), GetAttributeValueAsOptionalUnsigned(), lldb_private::plugin::dwarf::DWARFDIE::GetAttributeValueAsReferenceDIE(), GetAttributeValueAsString(), GetAttributeValueAsUnsigned(), GetDIE(), lldb_private::plugin::dwarf::DWARFDIE::GetDIENamesAndRanges(), GetDIERef(), lldb_private::plugin::dwarf::DWARFDIE::GetFirstChild(), lldb_private::plugin::dwarf::DWARFDIE::GetMangledName(), GetName(), GetOffset(), lldb_private::plugin::dwarf::DWARFDIE::GetParent(), lldb_private::plugin::dwarf::DWARFDIE::GetPubname(), lldb_private::plugin::dwarf::DWARFDIE::GetReferencedDIE(), lldb_private::plugin::dwarf::DWARFDIE::GetSibling(), HasChildren(), IsValid(), lldb_private::plugin::dwarf::DWARFDIE::LookupDeepestBlock(), Set(), and Tag().
The documentation for this class was generated from the following files:
DWARFBaseDIE.h
DWARFBaseDIE.cpp