LLDB: lldb_private::MainLoopPosix::RunImpl Class Reference
lldb_private::MainLoopPosix::RunImpl Class Reference
Public Member Functions
RunImpl (MainLoopPosix &loop)
~RunImpl ()=default
Status Poll ()
void ProcessReadEvents ()
Private Attributes
MainLoopPosix & loop
std::vector< struct pollfd > read_fds
Detailed Description
Definition at line 96 of file MainLoopPosix.cpp.
Constructor & Destructor Documentation
RunImpl()
lldb_private::MainLoopPosix::RunImpl::RunImpl (MainLoopPosix & loop)
Definition at line 159 of file MainLoopPosix.cpp.
References loop, lldb_private::MainLoopPosix::MainLoopPosix(), and read_fds.
~RunImpl()
lldb_private::MainLoopPosix::RunImpl::~RunImpl () default
Member Function Documentation
Poll()
Status lldb_private::MainLoopPosix::RunImpl::Poll ()
Definition at line 179 of file MainLoopPosix.cpp.
References lldb::eErrorTypePOSIX, loop, read_fds, StartPoll(), and lldb_private::Status.
Referenced by lldb_private::MainLoopPosix::Run().
ProcessReadEvents()
void lldb_private::MainLoopPosix::RunImpl::ProcessReadEvents ()
Definition at line 197 of file MainLoopPosix.cpp.
References loop, and read_fds.
Referenced by lldb_private::MainLoopPosix::Run().
Member Data Documentation
loop
MainLoopPosix& lldb_private::MainLoopPosix::RunImpl::loop private
Definition at line 106 of file MainLoopPosix.cpp.
Referenced by Poll(), ProcessReadEvents(), and RunImpl().
read_fds
std::vector<struct pollfd> lldb_private::MainLoopPosix::RunImpl::read_fds private
Definition at line 114 of file MainLoopPosix.cpp.
Referenced by Poll(), ProcessReadEvents(), and RunImpl().
The documentation for this class was generated from the following file:
MainLoopPosix.cpp