LLDB: lldb::SBFunction Class Reference
lldb::SBFunction Class Reference
#include <SBFunction.h>
Public Member Functions
SBFunction ()
SBFunction (const lldb::SBFunction &rhs)
const lldb::SBFunction & operator= (const lldb::SBFunction &rhs)
~SBFunction ()
operator bool () const
bool IsValid () const
const char * GetName () const
const char * GetDisplayName () const
const char * GetMangledName () const
const char * GetBaseName () const
lldb::SBInstructionList GetInstructions (lldb::SBTarget target)
lldb::SBInstructionList GetInstructions (lldb::SBTarget target, const char *flavor)
lldb::SBAddress GetStartAddress ()
LLDB_DEPRECATED_FIXME("Not compatible with discontinuous functions.", "GetRanges()") lldb lldb::SBAddressRangeList GetRanges ()
const char * GetArgumentName (uint32_t arg_idx)
uint32_t GetPrologueByteSize ()
lldb::SBType GetType ()
lldb::SBBlock GetBlock ()
lldb::LanguageType GetLanguage ()
bool GetIsOptimized ()
bool operator== (const lldb::SBFunction &rhs) const
bool operator!= (const lldb::SBFunction &rhs) const
bool GetDescription (lldb::SBStream &description)
Protected Member Functions
lldb_private::Function * get ()
void reset (lldb_private::Function *lldb_object_ptr)
Private Member Functions
SBFunction (lldb_private::Function *lldb_object_ptr)
Private Attributes
lldb_private::Function * m_opaque_ptr = nullptr
Friends
class SBAddress
class SBFrame
class SBSymbolContext
Detailed Description
Definition at line 19 of file SBFunction.h.
Constructor & Destructor Documentation
SBFunction() [1/3]
SBFunction::SBFunction ()
Definition at line 27 of file SBFunction.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by operator!=(), operator=(), operator==(), and SBSymbolContext.
SBFunction() [2/3]
SBFunction::SBFunction (const lldb::SBFunction & rhs)
Definition at line 32 of file SBFunction.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
~SBFunction()
SBFunction::~SBFunction ()
Definition at line 44 of file SBFunction.cpp.
References m_opaque_ptr.
SBFunction() [3/3]
SBFunction::SBFunction (lldb_private::Function * lldb_object_ptr) private
Definition at line 29 of file SBFunction.cpp.
References m_opaque_ptr.
Member Function Documentation
get()
lldb_private::Function * SBFunction::get () protected
Definition at line 145 of file SBFunction.cpp.
References m_opaque_ptr.
Referenced by lldb::SBSymbolContext::SetFunction().
GetArgumentName()
const char * SBFunction::GetArgumentName (uint32_t arg_idx)
Definition at line 185 of file SBFunction.cpp.
References lldb::eValueTypeVariableArgument, lldb_private::Block::GetBlockVariableList(), lldb_private::VariableList::GetVariableAtIndex(), LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetBaseName()
const char * SBFunction::GetBaseName () const
Definition at line 82 of file SBFunction.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetBlock()
SBBlock SBFunction::GetBlock ()
Definition at line 226 of file SBFunction.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and lldb::SBBlock::SetPtr().
GetDescription()
bool SBFunction::GetDescription (lldb::SBStream & description)
Definition at line 103 of file SBFunction.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::Type::GetName(), LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetDisplayName()
const char * SBFunction::GetDisplayName () const
Definition at line 65 of file SBFunction.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetInstructions() [1/2]
SBInstructionList SBFunction::GetInstructions (lldb::SBTarget target)
Definition at line 118 of file SBFunction.cpp.
References GetInstructions(), and LLDB_INSTRUMENT_VA.
Referenced by GetInstructions().
GetInstructions() [2/2]
SBInstructionList SBFunction::GetInstructions (lldb::SBTarget target, const char * flavor)
Definition at line 124 of file SBFunction.cpp.
References lldb_private::Disassembler::DisassembleRange(), lldb::SBTarget::GetSP(), LLDB_INSTRUMENT_VA, m_opaque_ptr, and lldb::SBInstructionList::SetDisassembler().
GetIsOptimized()
bool SBFunction::GetIsOptimized ()
Definition at line 245 of file SBFunction.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetLanguage()
lldb::LanguageType SBFunction::GetLanguage ()
Definition at line 235 of file SBFunction.cpp.
References lldb::eLanguageTypeUnknown, LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetMangledName()
const char * SBFunction::GetMangledName () const
Definition at line 74 of file SBFunction.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetName()
const char * SBFunction::GetName () const
Definition at line 56 of file SBFunction.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetPrologueByteSize()
uint32_t SBFunction::GetPrologueByteSize ()
Definition at line 206 of file SBFunction.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetRanges()
lldb::SBAddressRangeList SBFunction::GetRanges ()
Definition at line 175 of file SBFunction.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and lldb::SBAddressRangeList::ref().
GetStartAddress()
SBAddress SBFunction::GetStartAddress ()
Definition at line 151 of file SBFunction.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, SBAddress, and lldb::SBAddress::SetAddress().
GetType()
SBType SBFunction::GetType ()
Definition at line 214 of file SBFunction.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, lldb::SBType::ref(), and lldb_private::TypeImpl::SetType().
IsValid()
bool SBFunction::IsValid () const
Definition at line 46 of file SBFunction.cpp.
References LLDB_INSTRUMENT_VA.
operator bool()
SBFunction::operator bool () const explicit
Definition at line 50 of file SBFunction.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
operator!=()
bool SBFunction::operator!= (const lldb::SBFunction & rhs) const
Definition at line 97 of file SBFunction.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBFunction().
operator=()
const SBFunction & SBFunction::operator= (const lldb::SBFunction & rhs)
Definition at line 37 of file SBFunction.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBFunction().
operator==()
bool SBFunction::operator== (const lldb::SBFunction & rhs) const
Definition at line 91 of file SBFunction.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBFunction().
reset()
void SBFunction::reset (lldb_private::Function * lldb_object_ptr) protected
Definition at line 147 of file SBFunction.cpp.
References m_opaque_ptr.
Referenced by lldb::SBAddress::GetFunction().
Friends And Related Symbol Documentation
SBAddress
friend class SBAddress friend
Definition at line 78 of file SBFunction.h.
References SBAddress.
Referenced by GetStartAddress(), and SBAddress.
SBFrame
friend class SBFrame friend
Definition at line 79 of file SBFunction.h.
References SBFrame.
Referenced by SBFrame.
SBSymbolContext
friend class SBSymbolContext friend
Definition at line 80 of file SBFunction.h.
References SBFunction(), and SBSymbolContext.
Referenced by SBSymbolContext.
Member Data Documentation
m_opaque_ptr
lldb_private::Function* lldb::SBFunction::m_opaque_ptr = nullptr private
Definition at line 84 of file SBFunction.h.
Referenced by get(), GetArgumentName(), GetBaseName(), GetBlock(), GetDescription(), GetDisplayName(), GetInstructions(), GetIsOptimized(), GetLanguage(), GetMangledName(), GetName(), GetPrologueByteSize(), GetRanges(), GetStartAddress(), GetType(), operator bool(), operator!=(), operator=(), operator==(), reset(), SBFunction(), SBFunction(), and ~SBFunction().
The documentation for this class was generated from the following files:
SBFunction.h
SBFunction.cpp