LLDB: ABIAArch64 Class Reference
ABIAArch64 Class Reference
#include <ABIAArch64.h>
Public Member Functions
lldb::addr_t FixCodeAddress (lldb::addr_t pc) override
Some targets might use bits in a code address to indicate a mode switch.
lldb::addr_t FixDataAddress (lldb::addr_t pc) override
lldb::UnwindPlanSP CreateFunctionEntryUnwindPlan () override
lldb::UnwindPlanSP CreateDefaultUnwindPlan () override
Public Member Functions inherited from lldb_private::MCBasedABI
void AugmentRegisterInfo (std::vector< DynamicRegisterInfo::Register > &regs) override
Public Member Functions inherited from lldb_private::ABI
~ABI () override
virtual size_t GetRedZoneSize () const =0
virtual bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const =0
virtual bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::Type &prototype, llvm::ArrayRef< CallArgument > args) const
virtual bool GetArgumentValues (Thread &thread, ValueList &values) const =0
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, CompilerType &type, bool persistent=true) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, llvm::Type &type, bool persistent=true) const
virtual Status SetReturnValueObject (lldb::StackFrameSP &frame_sp, lldb::ValueObjectSP &new_value)=0
virtual bool RegisterIsVolatile (const RegisterInfo *reg_info)=0
virtual bool GetFallbackRegisterLocation (const RegisterInfo *reg_info, UnwindPlan::Row::AbstractRegisterLocation &unwind_regloc)
virtual bool CallFrameAddressIsValid (lldb::addr_t cfa)=0
virtual bool CodeAddressIsValid (lldb::addr_t pc)=0
virtual lldb::addr_t FixAnyAddress (lldb::addr_t pc)
Use this method when you do not know, or do not care what kind of address you are fixing.
llvm::MCRegisterInfo & GetMCRegisterInfo ()
virtual bool GetPointerReturnRegister (const char *&name)
virtual uint64_t GetStackFrameSize ()
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
virtual llvm::StringRef GetPluginName ()=0
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
Static Public Member Functions inherited from lldb_private::MCBasedABI
static void MapRegisterName (std::string &reg, llvm::StringRef from_prefix, llvm::StringRef to_prefix)
If the register name is of the form "<from_prefix>[<number>]" then change the name to "<to_prefix>[<number>]".
Static Public Member Functions inherited from lldb_private::ABI
static lldb::ABISP FindPlugin (lldb::ProcessSP process_sp, const ArchSpec &arch)
Protected Member Functions
virtual lldb::addr_t FixAddress (lldb::addr_t pc, lldb::addr_t mask)
std::pair< uint32_t, uint32_t > GetEHAndDWARFNums (llvm::StringRef name) override
Return eh_frame and dwarf numbers for the given register.
std::string GetMCName (std::string reg) override
For the given (capitalized) lldb register name, return the name of this register in the MCRegisterInfo struct.
uint32_t GetGenericNum (llvm::StringRef name) override
Return the generic number of the given register.
void AugmentRegisterInfo (std::vector< lldb_private::DynamicRegisterInfo::Register > &regs) override
Protected Member Functions inherited from lldb_private::MCBasedABI
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Protected Member Functions inherited from lldb_private::ABI
virtual lldb::ValueObjectSP GetReturnValueObjectImpl (Thread &thread, CompilerType &ast_type) const =0
virtual lldb::ValueObjectSP GetReturnValueObjectImpl (Thread &thread, llvm::Type &ir_type) const
lldb::ProcessSP GetProcessSP () const
Request to get a Process shared pointer.
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Additional Inherited Members
Static Protected Member Functions inherited from lldb_private::ABI
static std::unique_ptr< llvm::MCRegisterInfo > MakeMCRegisterInfo (const ArchSpec &arch)
Utility function to construct a MCRegisterInfo using the ArchSpec triple.
Protected Attributes inherited from lldb_private::ABI
lldb::ProcessWP m_process_wp
std::unique_ptr< llvm::MCRegisterInfo > m_mc_register_info_up
Detailed Description
Definition at line 14 of file ABIAArch64.h.
Member Function Documentation
AugmentRegisterInfo()
void ABIAArch64::AugmentRegisterInfo (std::vector< lldb_private::DynamicRegisterInfo::Register > & regs) override protected virtual
Implements lldb_private::ABI.
Definition at line 133 of file ABIAArch64.cpp.
References addPartialRegisters(), lldb_private::DynamicRegisterInfo::Register::alt_name, lldb_private::MCBasedABI::AugmentRegisterInfo(), lldb_private::DynamicRegisterInfo::Register::byte_size, lldb::eEncodingIEEE754, lldb::eEncodingUint, lldb::eEncodingVector, lldb::eFormatFloat, lldb::eFormatHex, lldb::eFormatVectorOfUInt8, lldb_private::ConstString::GetStringRef(), lldb_private::DynamicRegisterInfo::Register::name, and lldb_private::ConstString::SetCString().
CreateDefaultUnwindPlan()
UnwindPlanSP ABIAArch64::CreateDefaultUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 225 of file ABIAArch64.cpp.
References lldb_private::eLazyBoolNo, lldb::eRegisterKindGeneric, lldb_private::UnwindPlan::Row::GetCFAValue(), LLDB_REGNUM_GENERIC_FP, LLDB_REGNUM_GENERIC_PC, lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), lldb_private::UnwindPlan::Row::SetRegisterLocationToAtCFAPlusOffset(), and lldb_private::UnwindPlan::Row::SetUnspecifiedRegistersAreUndefined().
CreateFunctionEntryUnwindPlan()
UnwindPlanSP ABIAArch64::CreateFunctionEntryUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 206 of file ABIAArch64.cpp.
References lldb_private::eLazyBoolNo, lldb::eRegisterKindGeneric, lldb_private::UnwindPlan::Row::GetCFAValue(), LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_RA, LLDB_REGNUM_GENERIC_SP, lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), and lldb_private::UnwindPlan::Row::SetRegisterLocationToRegister().
FixAddress()
virtual lldb::addr_t ABIAArch64::FixAddress (lldb::addr_t pc, lldb::addr_t mask) inline protected virtual
Reimplemented in ABISysV_arm64.
Definition at line 26 of file ABIAArch64.h.
References pc.
Referenced by FixCodeAddress(), and FixDataAddress().
FixCodeAddress()
lldb::addr_t ABIAArch64::FixCodeAddress (lldb::addr_t pc) override virtual
Some targets might use bits in a code address to indicate a mode switch.
ARM uses bit zero to signify a code address is thumb, so any ARM ABI plug-ins would strip those bits.
Reimplemented from lldb_private::ABI.
Reimplemented in ABIMacOSX_arm64, and ABISysV_arm64.
Definition at line 37 of file ABIAArch64.cpp.
References FixAddress(), lldb_private::ABI::GetProcessSP(), LLDB_INVALID_ADDRESS_MASK, pac_sign_extension, and pc.
FixDataAddress()
lldb::addr_t ABIAArch64::FixDataAddress (lldb::addr_t pc) override virtual
Reimplemented from lldb_private::ABI.
Reimplemented in ABIMacOSX_arm64, and ABISysV_arm64.
Definition at line 54 of file ABIAArch64.cpp.
References FixAddress(), lldb_private::ABI::GetProcessSP(), LLDB_INVALID_ADDRESS_MASK, pac_sign_extension, and pc.
GetEHAndDWARFNums()
std::pair< uint32_t, uint32_t > ABIAArch64::GetEHAndDWARFNums (llvm::StringRef reg) override protected virtual
Return eh_frame and dwarf numbers for the given register.
Reimplemented from lldb_private::MCBasedABI.
Definition at line 71 of file ABIAArch64.cpp.
References arm64_dwarf::cpsr, arm64_ehframe::cpsr, lldb_private::MCBasedABI::GetEHAndDWARFNums(), arm64_dwarf::pc, and arm64_ehframe::pc.
GetGenericNum()
uint32_t ABIAArch64::GetGenericNum (llvm::StringRef reg) override protected virtual
Return the generic number of the given register.
Implements lldb_private::MCBasedABI.
Definition at line 86 of file ABIAArch64.cpp.
References LLDB_INVALID_REGNUM, LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_ARG2, LLDB_REGNUM_GENERIC_ARG3, LLDB_REGNUM_GENERIC_ARG4, LLDB_REGNUM_GENERIC_ARG5, LLDB_REGNUM_GENERIC_ARG6, LLDB_REGNUM_GENERIC_ARG7, LLDB_REGNUM_GENERIC_ARG8, LLDB_REGNUM_GENERIC_FLAGS, LLDB_REGNUM_GENERIC_FP, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_RA, and LLDB_REGNUM_GENERIC_SP.
GetMCName()
std::string ABIAArch64::GetMCName (std::string reg) override protected virtual
For the given (capitalized) lldb register name, return the name of this register in the MCRegisterInfo struct.
Reimplemented from lldb_private::MCBasedABI.
Definition at line 79 of file ABIAArch64.cpp.
References lldb_private::MCBasedABI::MapRegisterName().
Initialize()
void ABIAArch64::Initialize () static
Definition at line 27 of file ABIAArch64.cpp.
References Initialize(), ABIMacOSX_arm64::Initialize(), and ABISysV_arm64::Initialize().
Referenced by Initialize().
Terminate()
void ABIAArch64::Terminate () static
Definition at line 32 of file ABIAArch64.cpp.
References ABIMacOSX_arm64::Terminate(), and ABISysV_arm64::Terminate().
The documentation for this class was generated from the following files:
ABIAArch64.h
ABIAArch64.cpp