LLDB: lldb::SBTypeStaticField Class Reference
lldb::SBTypeStaticField Class Reference
#include <SBType.h>
Public Member Functions
SBTypeStaticField ()
SBTypeStaticField (const lldb::SBTypeStaticField &rhs)
lldb::SBTypeStaticField & operator= (const lldb::SBTypeStaticField &rhs)
~SBTypeStaticField ()
operator bool () const
bool IsValid () const
const char * GetName ()
const char * GetMangledName ()
lldb::SBType GetType ()
lldb::SBValue GetConstantValue (lldb::SBTarget target)
Protected Member Functions
SBTypeStaticField (lldb_private::CompilerDecl decl)
Protected Attributes
std::unique_ptr< lldb_private::CompilerDecl > m_opaque_up
Friends
class SBType
Detailed Description
Definition at line 110 of file SBType.h.
Constructor & Destructor Documentation
SBTypeStaticField() [1/3]
SBTypeStaticField::SBTypeStaticField ()
Definition at line 346 of file SBType.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by operator=(), SBType, and SBTypeStaticField().
SBTypeStaticField() [2/3]
SBTypeStaticField::SBTypeStaticField (const lldb::SBTypeStaticField & rhs)
Definition at line 351 of file SBType.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBTypeStaticField().
~SBTypeStaticField()
SBTypeStaticField::~SBTypeStaticField ()
Definition at line 364 of file SBType.cpp.
References LLDB_INSTRUMENT_VA.
SBTypeStaticField() [3/3]
SBTypeStaticField::SBTypeStaticField (lldb_private::CompilerDecl decl) explicit protected
Definition at line 348 of file SBType.cpp.
References m_opaque_up.
Member Function Documentation
GetConstantValue()
SBValue SBTypeStaticField::GetConstantValue (lldb::SBTarget target)
Definition at line 402 of file SBType.cpp.
References lldb_private::ValueObjectConstResult::Create(), lldb_private::Scalar::GetData(), lldb::SBTarget::GetSP(), IsValid(), lldb_private::Scalar::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBValue.
GetMangledName()
const char * SBTypeStaticField::GetMangledName ()
Definition at line 386 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_up.
GetName()
const char * SBTypeStaticField::GetName ()
Definition at line 378 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_up.
GetType()
SBType SBTypeStaticField::GetType ()
Definition at line 394 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBType.
IsValid()
bool SBTypeStaticField::IsValid () const
Definition at line 372 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by GetConstantValue(), GetMangledName(), GetName(), GetType(), and operator bool().
operator bool()
SBTypeStaticField::operator bool () const explicit
Definition at line 366 of file SBType.cpp.
References IsValid(), and LLDB_INSTRUMENT_VA.
operator=()
SBTypeStaticField & SBTypeStaticField::operator= (const lldb::SBTypeStaticField & rhs)
Definition at line 357 of file SBType.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBTypeStaticField().
Friends And Related Symbol Documentation
SBType
friend class SBType friend
Definition at line 132 of file SBType.h.
References SBType, and SBTypeStaticField().
Referenced by GetType(), and SBType.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::CompilerDecl> lldb::SBTypeStaticField::m_opaque_up protected
Definition at line 136 of file SBType.h.
Referenced by GetConstantValue(), GetMangledName(), GetName(), GetType(), IsValid(), operator=(), SBTypeStaticField(), and SBTypeStaticField().
The documentation for this class was generated from the following files:
SBType.h
SBType.cpp