LLDB: lldb_private::Highlighter Class Reference
lldb_private::Highlighter Class Reference abstract
Annotates source code with color attributes.
#include <Highlighter.h>
Public Member Functions
Highlighter ()=default
virtual ~Highlighter ()=default
Highlighter (const Highlighter &)=delete
const Highlighter & operator= (const Highlighter &)=delete
virtual llvm::StringRef GetName () const =0
Returns a human readable name for the selected highlighter.
virtual void Highlight (const HighlightStyle &options, llvm::StringRef line, std::optional< size_t > cursor_pos, llvm::StringRef previous_lines, Stream &s) const =0
Highlights the given line.
std::string Highlight (const HighlightStyle &options, llvm::StringRef line, std::optional< size_t > cursor_pos, llvm::StringRef previous_lines="") const
Utility method for calling Highlight without a stream.
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
virtual llvm::StringRef GetPluginName ()=0
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Detailed Description
Annotates source code with color attributes.
Definition at line 96 of file Highlighter.h.
Constructor & Destructor Documentation
Highlighter() [1/2]
lldb_private::Highlighter::Highlighter () default
Referenced by lldb_private::ClangHighlighter::CreateInstance(), lldb_private::DefaultHighlighter::CreateInstance(), Highlighter(), and operator=().
~Highlighter()
virtual lldb_private::Highlighter::~Highlighter () virtual default
Highlighter() [2/2]
lldb_private::Highlighter::Highlighter (const Highlighter &) delete
References Highlighter().
Member Function Documentation
GetName()
virtual llvm::StringRef lldb_private::Highlighter::GetName () const pure virtual
Returns a human readable name for the selected highlighter.
Implemented in lldb_private::ClangHighlighter, lldb_private::DefaultHighlighter, lldb_private::RustTreeSitterHighlighter, and lldb_private::SwiftTreeSitterHighlighter.
Referenced by lldb_private::TreeSitterHighlighter::GetTSState().
Highlight() [1/2]
virtual void lldb_private::Highlighter::Highlight (const HighlightStyle & options, llvm::StringRef line, std::optional< size_t > cursor_pos, llvm::StringRef previous_lines, Stream & s) const pure virtual
Highlights the given line.
Parameters
options The highlight options.
line The user supplied line that needs to be highlighted.
cursor_pos The cursor position of the user in this line, starting at 0 (which means the cursor is on the first character in 'line').
previous_lines Any previous lines the user has written which we should only use for getting the context of the Highlighting right.
s The stream to which the highlighted version of the user string should be written.
Implemented in lldb_private::ClangHighlighter, lldb_private::DefaultHighlighter, and lldb_private::TreeSitterHighlighter.
Referenced by Highlight().
Highlight() [2/2]
std::string Highlighter::Highlight (const HighlightStyle & options, llvm::StringRef line, std::optional< size_t > cursor_pos, llvm::StringRef previous_lines = "") const
Utility method for calling Highlight without a stream.
Definition at line 67 of file Highlighter.cpp.
References lldb_private::StreamString::Flush(), lldb_private::StreamString::GetString(), and Highlight().
operator=()
const Highlighter & lldb_private::Highlighter::operator= (const Highlighter &) delete
References Highlighter().
The documentation for this class was generated from the following files:
Highlighter.h
Highlighter.cpp