LLDB: lldb_private::HostNativeProcessBase Class Reference
lldb_private::HostNativeProcessBase Class Reference abstract
#include <HostNativeProcessBase.h>
Public Member Functions
HostNativeProcessBase ()
HostNativeProcessBase (lldb::process_t process)
virtual ~HostNativeProcessBase ()=default
virtual Status Terminate ()=0
virtual lldb::pid_t GetProcessId () const =0
virtual bool IsRunning () const =0
lldb::process_t GetSystemHandle () const
virtual llvm::Expected< HostThread > StartMonitoring (const Host::MonitorChildProcessCallback &callback)=0
Protected Attributes
lldb::process_t m_process
Private Member Functions
HostNativeProcessBase (const HostNativeProcessBase &)=delete
const HostNativeProcessBase & operator= (const HostNativeProcessBase &)=delete
Detailed Description
Definition at line 21 of file HostNativeProcessBase.h.
Constructor & Destructor Documentation
HostNativeProcessBase() [1/3]
lldb_private::HostNativeProcessBase::HostNativeProcessBase (const HostNativeProcessBase &) private delete
References HostNativeProcessBase().
Referenced by HostNativeProcessBase(), lldb_private::HostProcessPosix::HostProcessPosix(), lldb_private::HostProcessPosix::HostProcessPosix(), lldb_private::HostProcessWindows::HostProcessWindows(), lldb_private::HostProcessWindows::HostProcessWindows(), and operator=().
HostNativeProcessBase() [2/3]
lldb_private::HostNativeProcessBase::HostNativeProcessBase () inline
Definition at line 27 of file HostNativeProcessBase.h.
References LLDB_INVALID_PROCESS, and m_process.
HostNativeProcessBase() [3/3]
lldb_private::HostNativeProcessBase::HostNativeProcessBase (lldb::process_t process) inline explicit
Definition at line 28 of file HostNativeProcessBase.h.
References m_process.
~HostNativeProcessBase()
virtual lldb_private::HostNativeProcessBase::~HostNativeProcessBase () virtual default
Member Function Documentation
GetProcessId()
virtual lldb::pid_t lldb_private::HostNativeProcessBase::GetProcessId () const pure virtual
Implemented in lldb_private::HostProcessPosix, and lldb_private::HostProcessWindows.
GetSystemHandle()
lldb::process_t lldb_private::HostNativeProcessBase::GetSystemHandle () const inline
Definition at line 37 of file HostNativeProcessBase.h.
References m_process.
Referenced by lldb_private::ProcessDebugger::AllocateMemory(), lldb_private::ProcessDebugger::DeallocateMemory(), lldb_private::ProcessDebugger::GetMemoryRegionInfo(), and lldb_private::ProcessDebugger::WriteMemory().
IsRunning()
virtual bool lldb_private::HostNativeProcessBase::IsRunning () const pure virtual
Implemented in lldb_private::HostProcessPosix, and lldb_private::HostProcessWindows.
operator=()
const HostNativeProcessBase & lldb_private::HostNativeProcessBase::operator= (const HostNativeProcessBase &) private delete
References HostNativeProcessBase().
StartMonitoring()
virtual llvm::Expected< HostThread > lldb_private::HostNativeProcessBase::StartMonitoring (const Host::MonitorChildProcessCallback & callback) pure virtual
Implemented in lldb_private::HostProcessPosix, and lldb_private::HostProcessWindows.
Terminate()
virtual Status lldb_private::HostNativeProcessBase::Terminate () pure virtual
Implemented in lldb_private::HostProcessPosix, and lldb_private::HostProcessWindows.
Member Data Documentation
m_process
lldb::process_t lldb_private::HostNativeProcessBase::m_process protected
Definition at line 43 of file HostNativeProcessBase.h.
Referenced by lldb_private::HostProcessWindows::Close(), lldb_private::HostProcessPosix::GetProcessId(), lldb_private::HostProcessWindows::GetProcessId(), GetSystemHandle(), HostNativeProcessBase(), HostNativeProcessBase(), lldb_private::HostProcessPosix::IsRunning(), lldb_private::HostProcessWindows::IsRunning(), lldb_private::HostProcessPosix::Signal(), lldb_private::HostProcessPosix::StartMonitoring(), lldb_private::HostProcessWindows::StartMonitoring(), and lldb_private::HostProcessWindows::Terminate().
The documentation for this class was generated from the following file:
HostNativeProcessBase.h