LLDB: lldb::SBHostOS Class Reference
lldb::SBHostOS Class Reference
#include <SBHostOS.h>
Public Member Functions
LLDB_DEPRECATED ("Threading functionality in SBHostOS is not well supported, " "not portable, and is difficult to use from Python.") static void ThreadCreated(const char *name)
Static Public Member Functions
static lldb::SBFileSpec GetProgramFileSpec ()
static lldb::SBFileSpec GetLLDBPythonPath ()
static lldb::SBFileSpec GetScriptPath (lldb::ScriptLanguage language)
static lldb::SBFileSpec GetLLDBPath (lldb::PathType path_type)
static lldb::SBFileSpec GetUserHomeDirectory ()
Detailed Description
Definition at line 17 of file SBHostOS.h.
Member Function Documentation
GetLLDBPath()
SBFileSpec SBHostOS::GetLLDBPath (lldb::PathType path_type) static
Definition at line 53 of file SBHostOS.cpp.
References lldb::ePathTypeClangDir, lldb::ePathTypeGlobalLLDBTempSystemDir, lldb::ePathTypeHeaderDir, lldb::ePathTypeLLDBShlibDir, lldb::ePathTypeLLDBSystemPlugins, lldb::ePathTypeLLDBTempSystemDir, lldb::ePathTypeLLDBUserPlugins, lldb::ePathTypePythonDir, lldb::ePathTypeSupportExecutableDir, lldb::eScriptLanguagePython, lldb_private::GetClangResourceDir(), lldb_private::PluginManager::GetScriptInterpreterLibraryPath(), LLDB_INSTRUMENT_VA, and lldb::SBFileSpec::SetFileSpec().
GetLLDBPythonPath()
SBFileSpec SBHostOS::GetLLDBPythonPath () static
Definition at line 38 of file SBHostOS.cpp.
References lldb::eScriptLanguagePython, GetScriptPath(), and LLDB_INSTRUMENT.
GetProgramFileSpec()
SBFileSpec SBHostOS::GetProgramFileSpec () static
Definition at line 30 of file SBHostOS.cpp.
References LLDB_INSTRUMENT, and lldb::SBFileSpec::SetFileSpec().
GetScriptPath()
SBFileSpec SBHostOS::GetScriptPath (lldb::ScriptLanguage language) static
Definition at line 44 of file SBHostOS.cpp.
References lldb_private::PluginManager::GetScriptInterpreterLibraryPath(), LLDB_INSTRUMENT, and lldb::SBFileSpec::SetFileSpec().
Referenced by GetLLDBPythonPath().
GetUserHomeDirectory()
SBFileSpec SBHostOS::GetUserHomeDirectory () static
Definition at line 93 of file SBHostOS.cpp.
References LLDB_INSTRUMENT.
LLDB_DEPRECATED()
lldb::SBHostOS::LLDB_DEPRECATED ("Threading functionality in SBHostOS is not well supported, " "not portable, and is difficult to use from Python.") const
References LLDB_DEPRECATED().
Referenced by LLDB_DEPRECATED().
The documentation for this class was generated from the following files:
SBHostOS.h
SBHostOS.cpp