LLDB: lldb_private::postfix::UnaryOpNode Class Reference
lldb_private::postfix::UnaryOpNode Class Reference
A node representing a unary operation.
#include <PostfixExpression.h>
Public Types
enum OpType { Deref }
Public Types inherited from lldb_private::postfix::Node
enum Kind {
BinaryOp , InitialValue , Integer , Register ,
Symbol , UnaryOp
}
Public Member Functions
UnaryOpNode (OpType op_type, Node &operand)
OpType GetOpType () const
const Node * Operand () const
Node *& Operand ()
Public Member Functions inherited from lldb_private::postfix::Node
Kind GetKind () const
Static Public Member Functions
static bool classof (const Node *node)
Private Attributes
OpType m_op_type
Node * m_operand
Additional Inherited Members
Protected Member Functions inherited from lldb_private::postfix::Node
Node (Kind kind)
Detailed Description
A node representing a unary operation.
Definition at line 132 of file PostfixExpression.h.
Member Enumeration Documentation
OpType
enum lldb_private::postfix::UnaryOpNode::OpType
Enumerator
Deref
Definition at line 134 of file PostfixExpression.h.
Constructor & Destructor Documentation
UnaryOpNode()
lldb_private::postfix::UnaryOpNode::UnaryOpNode (OpType op_type, Node & operand) inline
Definition at line 138 of file PostfixExpression.h.
References m_op_type, m_operand, lldb_private::postfix::Node::Node(), and lldb_private::postfix::Node::UnaryOp.
Member Function Documentation
classof()
bool lldb_private::postfix::UnaryOpNode::classof (const Node * node) inline static
Definition at line 146 of file PostfixExpression.h.
References lldb_private::postfix::Node::GetKind(), lldb_private::postfix::Node::Node(), and lldb_private::postfix::Node::UnaryOp.
GetOpType()
OpType lldb_private::postfix::UnaryOpNode::GetOpType () const inline
Definition at line 141 of file PostfixExpression.h.
References m_op_type.
Operand() [1/2]
Node *& lldb_private::postfix::UnaryOpNode::Operand () inline
Definition at line 144 of file PostfixExpression.h.
References m_operand, and lldb_private::postfix::Node::Node().
Operand() [2/2]
const Node * lldb_private::postfix::UnaryOpNode::Operand () const inline
Definition at line 143 of file PostfixExpression.h.
References m_operand, and lldb_private::postfix::Node::Node().
Member Data Documentation
m_op_type
OpType lldb_private::postfix::UnaryOpNode::m_op_type private
Definition at line 149 of file PostfixExpression.h.
Referenced by GetOpType(), and UnaryOpNode().
m_operand
Node* lldb_private::postfix::UnaryOpNode::m_operand private
Definition at line 150 of file PostfixExpression.h.
Referenced by Operand(), Operand(), and UnaryOpNode().
The documentation for this class was generated from the following file:
PostfixExpression.h