LLDB: RegisterContextCorePOSIX_s390x Class Reference
RegisterContextCorePOSIX_s390x Class Reference
#include <RegisterContextPOSIXCore_s390x.h>
Public Member Functions
RegisterContextCorePOSIX_s390x (lldb_private::Thread &thread, lldb_private::RegisterInfoInterface *register_info, const lldb_private::DataExtractor &gpregset, llvm::ArrayRef< lldb_private::CoreNote > notes)
~RegisterContextCorePOSIX_s390x () override
bool ReadRegister (const lldb_private::RegisterInfo *reg_info, lldb_private::RegisterValue &value) override
bool WriteRegister (const lldb_private::RegisterInfo *reg_info, const lldb_private::RegisterValue &value) override
bool ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp) override
bool WriteAllRegisterValues (const lldb::DataBufferSP &data_sp) override
bool HardwareSingleStep (bool enable) override
Public Member Functions inherited from RegisterContextPOSIX_s390x
RegisterContextPOSIX_s390x (lldb_private::Thread &thread, uint32_t concrete_frame_idx, lldb_private::RegisterInfoInterface *register_info)
~RegisterContextPOSIX_s390x () override
void Invalidate ()
void InvalidateAllRegisters () override
size_t GetRegisterCount () override
virtual unsigned GetRegisterSize (unsigned reg)
virtual unsigned GetRegisterOffset (unsigned reg)
const lldb_private::RegisterInfo * GetRegisterInfoAtIndex (size_t reg) override
size_t GetRegisterSetCount () override
const lldb_private::RegisterSet * GetRegisterSet (size_t set) override
const char * GetRegisterName (unsigned reg)
Public Member Functions inherited from lldb_private::RegisterContext
RegisterContext (Thread &thread, uint32_t concrete_frame_idx)
~RegisterContext () override
void InvalidateIfNeeded (bool force)
virtual lldb::ByteOrder GetByteOrder ()
virtual bool RegisterWriteCausesReconfigure (const llvm::StringRef name)
virtual bool ReconfigureRegisterInfo ()
virtual bool ReadAllRegisterValues (lldb_private::RegisterCheckpoint &reg_checkpoint)
virtual bool WriteAllRegisterValues (const lldb_private::RegisterCheckpoint &reg_checkpoint)
bool CopyFromRegisterContext (lldb::RegisterContextSP context)
virtual uint32_t ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num)
Convert from a given register numbering scheme to the lldb register numbering scheme.
virtual uint32_t NumSupportedHardwareBreakpoints ()
virtual uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual bool ClearHardwareBreakpoint (uint32_t hw_idx)
virtual uint32_t NumSupportedHardwareWatchpoints ()
virtual uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, bool read, bool write)
virtual bool ClearHardwareWatchpoint (uint32_t hw_index)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, uint32_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, uint32_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual Thread & GetThread ()
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num)
uint64_t GetPC (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetThreadPointer (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool GetPCForSymbolication (Address &address)
Get an address suitable for symbolication.
bool SetPC (uint64_t pc)
bool SetPC (Address addr)
uint64_t GetSP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetSP (uint64_t sp)
uint64_t GetFP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetFP (uint64_t fp)
const char * GetRegisterName (uint32_t reg)
uint64_t GetReturnAddress (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetFlags (uint64_t fail_value=0)
uint64_t ReadRegisterAsUnsigned (uint32_t reg, uint64_t fail_value)
uint64_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, uint64_t fail_value)
bool WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
bool WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
bool ConvertBetweenRegisterKinds (lldb::RegisterKind source_rk, uint32_t source_regnum, lldb::RegisterKind target_rk, uint32_t &target_regnum)
lldb::TargetSP CalculateTarget () override
lldb::ProcessSP CalculateProcess () override
lldb::ThreadSP CalculateThread () override
lldb::StackFrameSP CalculateStackFrame () override
void CalculateExecutionContext (ExecutionContext &exe_ctx) override
Reconstruct the object's execution context into sc.
uint32_t GetStopID () const
void SetStopID (uint32_t stop_id)
Public Member Functions inherited from lldb_private::ExecutionContextScope
virtual ~ExecutionContextScope ()=default
Protected Member Functions
bool ReadGPR () override
bool ReadFPR () override
bool WriteGPR () override
bool WriteFPR () override
Protected Member Functions inherited from RegisterContextPOSIX_s390x
virtual bool IsRegisterSetAvailable (size_t set_index)
virtual const lldb_private::RegisterInfo * GetRegisterInfo ()
bool IsGPR (unsigned reg)
bool IsFPR (unsigned reg)
Protected Member Functions inherited from lldb_private::RegisterContext
virtual bool BehavesLikeZerothFrame () const
Indicates that this frame is currently executing code, that the PC value is not a return-pc but an actual executing instruction.
Private Attributes
lldb::DataBufferSP m_gpr_buffer
lldb_private::DataExtractor m_gpr
lldb::DataBufferSP m_fpr_buffer
lldb_private::DataExtractor m_fpr
Additional Inherited Members
Protected Attributes inherited from RegisterContextPOSIX_s390x
RegInfo m_reg_info
std::unique_ptr< lldb_private::RegisterInfoInterface > m_register_info_up
Protected Attributes inherited from lldb_private::RegisterContext
Thread & m_thread
uint32_t m_concrete_frame_idx
uint32_t m_stop_id
Detailed Description
Definition at line 16 of file RegisterContextPOSIXCore_s390x.h.
Constructor & Destructor Documentation
RegisterContextCorePOSIX_s390x()
RegisterContextCorePOSIX_s390x::RegisterContextCorePOSIX_s390x (lldb_private::Thread & thread, lldb_private::RegisterInfoInterface * register_info, const lldb_private::DataExtractor & gpregset, llvm::ArrayRef< lldb_private::CoreNote > notes)
Definition at line 19 of file RegisterContextPOSIXCore_s390x.cpp.
References lldb_private::FPR_Desc, lldb_private::DataExtractor::GetByteOrder(), lldb_private::DataExtractor::GetByteSize(), lldb_private::DataExtractor::GetDataStart(), lldb_private::getRegset(), lldb_private::RegisterInfoInterface::GetTargetArchitecture(), lldb_private::ArchSpec::GetTriple(), m_fpr, m_fpr_buffer, m_gpr, m_gpr_buffer, and RegisterContextPOSIX_s390x::RegisterContextPOSIX_s390x().
~RegisterContextCorePOSIX_s390x()
RegisterContextCorePOSIX_s390x::~RegisterContextCorePOSIX_s390x () override default
Member Function Documentation
HardwareSingleStep()
bool RegisterContextCorePOSIX_s390x::HardwareSingleStep (bool enable) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 94 of file RegisterContextPOSIXCore_s390x.cpp.
ReadAllRegisterValues()
bool RegisterContextCorePOSIX_s390x::ReadAllRegisterValues (lldb::WritableDataBufferSP & data_sp) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 79 of file RegisterContextPOSIXCore_s390x.cpp.
ReadFPR()
bool RegisterContextCorePOSIX_s390x::ReadFPR () override protected virtual
Implements RegisterContextPOSIX_s390x.
Definition at line 40 of file RegisterContextPOSIXCore_s390x.cpp.
ReadGPR()
bool RegisterContextCorePOSIX_s390x::ReadGPR () override protected virtual
Implements RegisterContextPOSIX_s390x.
Definition at line 38 of file RegisterContextPOSIXCore_s390x.cpp.
ReadRegister()
bool RegisterContextCorePOSIX_s390x::ReadRegister (const lldb_private::RegisterInfo * reg_info, lldb_private::RegisterValue & value) override virtual
Implements lldb_private::RegisterContext.
Definition at line 52 of file RegisterContextPOSIXCore_s390x.cpp.
References lldb_private::RegisterInfo::byte_offset, lldb_private::RegisterInfo::byte_size, lldb::eRegisterKindLLDB, RegisterContextPOSIX_s390x::IsFPR(), RegisterContextPOSIX_s390x::IsGPR(), lldb_private::RegisterInfo::kinds, LLDB_INVALID_REGNUM, m_fpr, m_gpr, and lldb_private::RegisterValue::SetUInt().
WriteAllRegisterValues()
bool RegisterContextCorePOSIX_s390x::WriteAllRegisterValues (const lldb::DataBufferSP & data_sp) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 89 of file RegisterContextPOSIXCore_s390x.cpp.
WriteFPR()
bool RegisterContextCorePOSIX_s390x::WriteFPR () override protected virtual
Implements RegisterContextPOSIX_s390x.
Definition at line 47 of file RegisterContextPOSIXCore_s390x.cpp.
WriteGPR()
bool RegisterContextCorePOSIX_s390x::WriteGPR () override protected virtual
Implements RegisterContextPOSIX_s390x.
Definition at line 42 of file RegisterContextPOSIXCore_s390x.cpp.
WriteRegister()
bool RegisterContextCorePOSIX_s390x::WriteRegister (const lldb_private::RegisterInfo * reg_info, const lldb_private::RegisterValue & value) override virtual
Implements lldb_private::RegisterContext.
Definition at line 84 of file RegisterContextPOSIXCore_s390x.cpp.
Member Data Documentation
m_fpr
lldb_private::DataExtractor RegisterContextCorePOSIX_s390x::m_fpr private
Definition at line 52 of file RegisterContextPOSIXCore_s390x.h.
Referenced by ReadRegister(), and RegisterContextCorePOSIX_s390x().
m_fpr_buffer
lldb::DataBufferSP RegisterContextCorePOSIX_s390x::m_fpr_buffer private
Definition at line 51 of file RegisterContextPOSIXCore_s390x.h.
Referenced by RegisterContextCorePOSIX_s390x().
m_gpr
lldb_private::DataExtractor RegisterContextCorePOSIX_s390x::m_gpr private
Definition at line 49 of file RegisterContextPOSIXCore_s390x.h.
Referenced by ReadRegister(), and RegisterContextCorePOSIX_s390x().
m_gpr_buffer
lldb::DataBufferSP RegisterContextCorePOSIX_s390x::m_gpr_buffer private
Definition at line 48 of file RegisterContextPOSIXCore_s390x.h.
Referenced by RegisterContextCorePOSIX_s390x().
The documentation for this class was generated from the following files:
RegisterContextPOSIXCore_s390x.h
RegisterContextPOSIXCore_s390x.cpp