LLDB: MSVCUndecoratedNameParser Class Reference
MSVCUndecoratedNameParser Class Reference
#include <MSVCUndecoratedNameParser.h>
Public Member Functions
MSVCUndecoratedNameParser (llvm::StringRef name)
llvm::ArrayRef< MSVCUndecoratedNameSpecifier > GetSpecifiers () const
Static Public Member Functions
static bool IsMSVCUndecoratedName (llvm::StringRef name)
static bool ExtractContextAndIdentifier (llvm::StringRef name, llvm::StringRef &context, llvm::StringRef &identifier)
static llvm::StringRef DropScope (llvm::StringRef name)
Private Attributes
std::vector< MSVCUndecoratedNameSpecifier > m_specifiers
Detailed Description
Definition at line 31 of file MSVCUndecoratedNameParser.h.
Constructor & Destructor Documentation
MSVCUndecoratedNameParser()
MSVCUndecoratedNameParser::MSVCUndecoratedNameParser (llvm::StringRef name) explicit
Definition at line 13 of file MSVCUndecoratedNameParser.cpp.
References m_specifiers.
Referenced by DropScope(), and ExtractContextAndIdentifier().
Member Function Documentation
DropScope()
llvm::StringRef MSVCUndecoratedNameParser::DropScope (llvm::StringRef name) static
Definition at line 98 of file MSVCUndecoratedNameParser.cpp.
References GetSpecifiers(), and MSVCUndecoratedNameParser().
Referenced by PDBASTParser::AddEnumValue(), PDBASTParser::AddRecordMethod(), lldb_private::npdb::SymbolFileNativePDB::BuildParentMap(), SymbolFilePDB::CacheFunctionNames(), lldb_private::npdb::SymbolFileNativePDB::CacheGlobalBaseNames(), PDBASTParser::CreateLLDBTypeFromPDBType(), lldb_private::npdb::DropNameScope(), SymbolFilePDB::FindGlobalVariables(), SymbolFilePDB::FindTypes(), PDBASTParser::GetDeclForSymbol(), and GetUnqualifiedTypeName().
ExtractContextAndIdentifier()
bool MSVCUndecoratedNameParser::ExtractContextAndIdentifier (llvm::StringRef name, llvm::StringRef & context, llvm::StringRef & identifier) static
Definition at line 85 of file MSVCUndecoratedNameParser.cpp.
References GetSpecifiers(), and MSVCUndecoratedNameParser().
Referenced by lldb_private::CPlusPlusLanguage::ExtractContextAndIdentifier().
GetSpecifiers()
llvm::ArrayRef< MSVCUndecoratedNameSpecifier > MSVCUndecoratedNameParser::GetSpecifiers () const inline
Definition at line 35 of file MSVCUndecoratedNameParser.h.
References m_specifiers.
Referenced by lldb_private::npdb::PdbAstBuilderClang::CreateDeclInfoForUndecoratedName(), DropScope(), ExtractContextAndIdentifier(), and PDBASTParser::GetDeclContextContainingSymbol().
IsMSVCUndecoratedName()
bool MSVCUndecoratedNameParser::IsMSVCUndecoratedName (llvm::StringRef name) static
Definition at line 81 of file MSVCUndecoratedNameParser.cpp.
Referenced by lldb_private::CPlusPlusLanguage::ExtractContextAndIdentifier().
Member Data Documentation
m_specifiers
std::vector<MSVCUndecoratedNameSpecifier> MSVCUndecoratedNameParser::m_specifiers private
Definition at line 47 of file MSVCUndecoratedNameParser.h.
Referenced by GetSpecifiers(), and MSVCUndecoratedNameParser().
The documentation for this class was generated from the following files:
MSVCUndecoratedNameParser.h
MSVCUndecoratedNameParser.cpp