LLDB: lldb::SBSymbolContext Class Reference
lldb::SBSymbolContext Class Reference
#include <SBSymbolContext.h>
Public Member Functions
SBSymbolContext ()
SBSymbolContext (const lldb::SBSymbolContext &rhs)
~SBSymbolContext ()
operator bool () const
bool IsValid () const
const lldb::SBSymbolContext & operator= (const lldb::SBSymbolContext &rhs)
lldb::SBModule GetModule ()
lldb::SBCompileUnit GetCompileUnit ()
lldb::SBFunction GetFunction ()
lldb::SBBlock GetBlock ()
lldb::SBLineEntry GetLineEntry ()
lldb::SBSymbol GetSymbol ()
void SetModule (lldb::SBModule module)
void SetCompileUnit (lldb::SBCompileUnit compile_unit)
void SetFunction (lldb::SBFunction function)
void SetBlock (lldb::SBBlock block)
void SetLineEntry (lldb::SBLineEntry line_entry)
void SetSymbol (lldb::SBSymbol symbol)
SBSymbolContext GetParentOfInlinedScope (const SBAddress &curr_frame_pc, SBAddress &parent_frame_addr) const
bool GetDescription (lldb::SBStream &description)
Protected Member Functions
SBSymbolContext (const lldb_private::SymbolContext &sc_ptr)
lldb_private::SymbolContext * operator-> () const
lldb_private::SymbolContext & operator* ()
lldb_private::SymbolContext & ref ()
const lldb_private::SymbolContext & operator* () const
lldb_private::SymbolContext * get () const
Private Attributes
std::unique_ptr< lldb_private::SymbolContext > m_opaque_up
Friends
class SBAddress
class SBFrame
class SBModule
class SBThread
class SBTarget
class SBSymbolContextList
class lldb_private::ScriptInterpreter
class lldb_private::python::SWIGBridge
Detailed Description
Definition at line 28 of file SBSymbolContext.h.
Constructor & Destructor Documentation
SBSymbolContext() [1/3]
SBSymbolContext::SBSymbolContext ()
Definition at line 21 of file SBSymbolContext.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by GetParentOfInlinedScope(), lldb_private::python::SWIGBridge, operator=(), SBSymbolContext(), and ~SBSymbolContext().
SBSymbolContext() [2/3]
SBSymbolContext::SBSymbolContext (const lldb::SBSymbolContext & rhs)
Definition at line 28 of file SBSymbolContext.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBSymbolContext().
~SBSymbolContext()
SBSymbolContext::~SBSymbolContext () default
References GetBlock(), GetCompileUnit(), GetDescription(), GetFunction(), GetLineEntry(), GetModule(), GetParentOfInlinedScope(), GetSymbol(), IsValid(), operator=(), SBAddress, SBSymbolContext(), SetBlock(), SetCompileUnit(), SetFunction(), SetLineEntry(), SetModule(), and SetSymbol().
SBSymbolContext() [3/3]
SBSymbolContext::SBSymbolContext (const lldb_private::SymbolContext & sc_ptr) protected
Definition at line 23 of file SBSymbolContext.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Member Function Documentation
get()
lldb_private::SymbolContext * SBSymbolContext::get () const protected
Definition at line 175 of file SBSymbolContext.cpp.
References m_opaque_up.
Referenced by lldb_private::python::SWIGBridge.
GetBlock()
SBBlock SBSymbolContext::GetBlock ()
Definition at line 86 of file SBSymbolContext.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBBlock.
Referenced by ~SBSymbolContext().
GetCompileUnit()
SBCompileUnit SBSymbolContext::GetCompileUnit ()
Definition at line 67 of file SBSymbolContext.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBCompileUnit.
Referenced by ~SBSymbolContext().
GetDescription()
bool SBSymbolContext::GetDescription (lldb::SBStream & description)
Definition at line 179 of file SBSymbolContext.cpp.
References lldb::eDescriptionLevelFull, LLDB_INSTRUMENT_VA, m_opaque_up, lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
Referenced by ~SBSymbolContext().
GetFunction()
SBFunction SBSymbolContext::GetFunction ()
Definition at line 73 of file SBSymbolContext.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBSymbolContext().
GetLineEntry()
SBLineEntry SBSymbolContext::GetLineEntry ()
Definition at line 92 of file SBSymbolContext.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBLineEntry::SetLineEntry().
Referenced by ~SBSymbolContext().
GetModule()
SBModule SBSymbolContext::GetModule ()
Definition at line 54 of file SBSymbolContext.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, SBModule, and lldb::SBModule::SetSP().
Referenced by ~SBSymbolContext().
GetParentOfInlinedScope()
SBSymbolContext SBSymbolContext::GetParentOfInlinedScope (const SBAddress & curr_frame_pc, SBAddress & parent_frame_addr) const
Definition at line 193 of file SBSymbolContext.cpp.
References lldb::SBAddress::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_up, lldb::SBAddress::ref(), ref(), SBAddress, and SBSymbolContext().
Referenced by ~SBSymbolContext().
GetSymbol()
SBSymbol SBSymbolContext::GetSymbol ()
Definition at line 102 of file SBSymbolContext.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBSymbolContext().
IsValid()
bool SBSymbolContext::IsValid () const
Definition at line 44 of file SBSymbolContext.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBSymbolContextList::Append(), and ~SBSymbolContext().
operator bool()
SBSymbolContext::operator bool () const explicit
Definition at line 48 of file SBSymbolContext.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
operator*() [1/2]
lldb_private::SymbolContext & SBSymbolContext::operator* () protected
Definition at line 163 of file SBSymbolContext.cpp.
References m_opaque_up.
Referenced by lldb_private::python::SWIGBridge.
operator*() [2/2]
const lldb_private::SymbolContext & SBSymbolContext::operator* () const protected
Definition at line 158 of file SBSymbolContext.cpp.
References m_opaque_up.
operator->()
lldb_private::SymbolContext * SBSymbolContext::operator-> () const protected
Definition at line 154 of file SBSymbolContext.cpp.
References m_opaque_up.
Referenced by lldb_private::python::SWIGBridge.
operator=()
const SBSymbolContext & SBSymbolContext::operator= (const lldb::SBSymbolContext & rhs)
Definition at line 36 of file SBSymbolContext.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBSymbolContext().
Referenced by ~SBSymbolContext().
ref()
lldb_private::SymbolContext & SBSymbolContext::ref () protected
Definition at line 169 of file SBSymbolContext.cpp.
References m_opaque_up.
Referenced by GetParentOfInlinedScope(), lldb::SBAddress::GetSymbolContext(), lldb_private::python::SWIGBridge, lldb::SBTarget::ResolveSymbolContextForAddress(), SetBlock(), SetCompileUnit(), SetFunction(), SetLineEntry(), SetModule(), and SetSymbol().
SetBlock()
void SBSymbolContext::SetBlock (lldb::SBBlock block)
Definition at line 133 of file SBSymbolContext.cpp.
References lldb_private::SymbolContext::block, lldb::SBBlock::GetPtr(), LLDB_INSTRUMENT_VA, and ref().
Referenced by ~SBSymbolContext().
SetCompileUnit()
void SBSymbolContext::SetCompileUnit (lldb::SBCompileUnit compile_unit)
Definition at line 121 of file SBSymbolContext.cpp.
References lldb_private::SymbolContext::comp_unit, lldb::SBCompileUnit::get(), LLDB_INSTRUMENT_VA, and ref().
Referenced by ~SBSymbolContext().
SetFunction()
void SBSymbolContext::SetFunction (lldb::SBFunction function)
Definition at line 127 of file SBSymbolContext.cpp.
References lldb_private::SymbolContext::function, lldb::SBFunction::get(), LLDB_INSTRUMENT_VA, and ref().
Referenced by ~SBSymbolContext().
SetLineEntry()
void SBSymbolContext::SetLineEntry (lldb::SBLineEntry line_entry)
Definition at line 139 of file SBSymbolContext.cpp.
References lldb_private::LineEntry::Clear(), lldb::SBLineEntry::IsValid(), lldb_private::SymbolContext::line_entry, LLDB_INSTRUMENT_VA, lldb::SBLineEntry::ref(), and ref().
Referenced by ~SBSymbolContext().
SetModule()
void SBSymbolContext::SetModule (lldb::SBModule module)
Definition at line 115 of file SBSymbolContext.cpp.
References LLDB_INSTRUMENT_VA, lldb_private::SymbolContext::module_sp, and ref().
Referenced by ~SBSymbolContext().
SetSymbol()
void SBSymbolContext::SetSymbol (lldb::SBSymbol symbol)
Definition at line 148 of file SBSymbolContext.cpp.
References lldb::SBSymbol::get(), LLDB_INSTRUMENT_VA, ref(), and lldb_private::SymbolContext::symbol.
Referenced by ~SBSymbolContext().
Friends And Related Symbol Documentation
lldb_private::python::SWIGBridge
friend class lldb_private::python::SWIGBridge friend
Definition at line 70 of file SBSymbolContext.h.
References get(), operator*(), operator->(), ref(), and SBSymbolContext().
lldb_private::ScriptInterpreter
lldb_private::ScriptInterpreter friend
Definition at line 69 of file SBSymbolContext.h.
SBAddress
friend class SBAddress friend
Definition at line 62 of file SBSymbolContext.h.
References SBAddress.
Referenced by GetParentOfInlinedScope(), SBAddress, and ~SBSymbolContext().
SBFrame
friend class SBFrame friend
Definition at line 63 of file SBSymbolContext.h.
References SBFrame.
Referenced by SBFrame.
SBModule
friend class SBModule friend
Definition at line 64 of file SBSymbolContext.h.
References SBModule.
Referenced by GetModule(), and SBModule.
SBSymbolContextList
friend class SBSymbolContextList friend
Definition at line 67 of file SBSymbolContext.h.
References SBSymbolContextList.
Referenced by SBSymbolContextList.
SBTarget
friend class SBTarget friend
Definition at line 66 of file SBSymbolContext.h.
References SBTarget.
Referenced by SBTarget.
SBThread
friend class SBThread friend
Definition at line 65 of file SBSymbolContext.h.
References SBThread.
Referenced by SBThread.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::SymbolContext> lldb::SBSymbolContext::m_opaque_up private
Definition at line 87 of file SBSymbolContext.h.
Referenced by get(), GetBlock(), GetCompileUnit(), GetDescription(), GetFunction(), GetLineEntry(), GetModule(), lldb_private::ScriptInterpreter::GetOpaqueTypeFromSBSymbolContext(), GetParentOfInlinedScope(), GetSymbol(), operator bool(), operator*(), operator*(), operator->(), operator=(), ref(), SBSymbolContext(), and SBSymbolContext().
The documentation for this class was generated from the following files:
SBSymbolContext.h
SBSymbolContext.cpp