LLDB: RegisterContextCorePOSIX_arm64 Class Reference
RegisterContextCorePOSIX_arm64 Class Reference
#include <RegisterContextPOSIXCore_arm64.h>
Public Member Functions
~RegisterContextCorePOSIX_arm64 () override
bool ReadRegister (const lldb_private::RegisterInfo *reg_info, lldb_private::RegisterValue &value) override
bool WriteRegister (const lldb_private::RegisterInfo *reg_info, const lldb_private::RegisterValue &value) override
bool ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp) override
bool WriteAllRegisterValues (const lldb::DataBufferSP &data_sp) override
bool HardwareSingleStep (bool enable) override
Public Member Functions inherited from RegisterContextPOSIX_arm64
RegisterContextPOSIX_arm64 (lldb_private::Thread &thread, std::unique_ptr< RegisterInfoPOSIX_arm64 > register_info)
~RegisterContextPOSIX_arm64 () override
void Invalidate ()
void InvalidateAllRegisters () override
size_t GetRegisterCount () override
virtual size_t GetGPRSize ()
virtual unsigned GetRegisterSize (unsigned reg)
virtual unsigned GetRegisterOffset (unsigned reg)
const lldb_private::RegisterInfo * GetRegisterInfoAtIndex (size_t reg) override
size_t GetRegisterSetCount () override
const lldb_private::RegisterSet * GetRegisterSet (size_t set) override
const char * GetRegisterName (unsigned reg)
Public Member Functions inherited from lldb_private::RegisterContext
RegisterContext (Thread &thread, uint32_t concrete_frame_idx)
~RegisterContext () override
void InvalidateIfNeeded (bool force)
virtual lldb::ByteOrder GetByteOrder ()
virtual bool RegisterWriteCausesReconfigure (const llvm::StringRef name)
virtual bool ReconfigureRegisterInfo ()
virtual bool ReadAllRegisterValues (lldb_private::RegisterCheckpoint &reg_checkpoint)
virtual bool WriteAllRegisterValues (const lldb_private::RegisterCheckpoint &reg_checkpoint)
bool CopyFromRegisterContext (lldb::RegisterContextSP context)
virtual uint32_t ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num)
Convert from a given register numbering scheme to the lldb register numbering scheme.
virtual uint32_t NumSupportedHardwareBreakpoints ()
virtual uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual bool ClearHardwareBreakpoint (uint32_t hw_idx)
virtual uint32_t NumSupportedHardwareWatchpoints ()
virtual uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, bool read, bool write)
virtual bool ClearHardwareWatchpoint (uint32_t hw_index)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, uint32_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, uint32_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual Thread & GetThread ()
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num)
uint64_t GetPC (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetThreadPointer (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool GetPCForSymbolication (Address &address)
Get an address suitable for symbolication.
bool SetPC (uint64_t pc)
bool SetPC (Address addr)
uint64_t GetSP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetSP (uint64_t sp)
uint64_t GetFP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetFP (uint64_t fp)
const char * GetRegisterName (uint32_t reg)
uint64_t GetReturnAddress (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetFlags (uint64_t fail_value=0)
uint64_t ReadRegisterAsUnsigned (uint32_t reg, uint64_t fail_value)
uint64_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, uint64_t fail_value)
bool WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
bool WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
bool ConvertBetweenRegisterKinds (lldb::RegisterKind source_rk, uint32_t source_regnum, lldb::RegisterKind target_rk, uint32_t &target_regnum)
lldb::TargetSP CalculateTarget () override
lldb::ProcessSP CalculateProcess () override
lldb::ThreadSP CalculateThread () override
lldb::StackFrameSP CalculateStackFrame () override
void CalculateExecutionContext (ExecutionContext &exe_ctx) override
Reconstruct the object's execution context into sc.
uint32_t GetStopID () const
void SetStopID (uint32_t stop_id)
Public Member Functions inherited from lldb_private::ExecutionContextScope
virtual ~ExecutionContextScope ()=default
Static Public Member Functions
static std::unique_ptr< RegisterContextCorePOSIX_arm64 > Create (lldb_private::Thread &thread, const lldb_private::ArchSpec &arch, const lldb_private::DataExtractor &gpregset, llvm::ArrayRef< lldb_private::CoreNote > notes)
Protected Member Functions
RegisterContextCorePOSIX_arm64 (lldb_private::Thread &thread, std::unique_ptr< RegisterInfoPOSIX_arm64 > register_info, const lldb_private::DataExtractor &gpregset, llvm::ArrayRef< lldb_private::CoreNote > notes)
bool ReadGPR () override
bool ReadFPR () override
bool WriteGPR () override
bool WriteFPR () override
Protected Member Functions inherited from RegisterContextPOSIX_arm64
virtual const lldb_private::RegisterInfo * GetRegisterInfo ()
bool IsGPR (unsigned reg)
bool IsFPR (unsigned reg)
size_t GetFPUSize ()
bool IsSVE (unsigned reg) const
bool IsPAuth (unsigned reg) const
bool IsTLS (unsigned reg) const
bool IsSME (unsigned reg) const
bool IsMTE (unsigned reg) const
bool IsFPMR (unsigned reg) const
bool IsGCS (unsigned reg) const
bool IsPOE (unsigned reg) const
bool IsSVEZ (unsigned reg) const
bool IsSVEP (unsigned reg) const
bool IsSVEVG (unsigned reg) const
bool IsSMEZA (unsigned reg) const
uint32_t GetRegNumSVEZ0 () const
uint32_t GetRegNumSVEFFR () const
uint32_t GetRegNumFPCR () const
uint32_t GetRegNumFPSR () const
Protected Member Functions inherited from lldb_private::RegisterContext
virtual bool BehavesLikeZerothFrame () const
Indicates that this frame is currently executing code, that the PC value is not a return-pc but an actual executing instruction.
Private Member Functions
struct __attribute__ ((packed)) sme_pseudo_regs
const uint8_t * GetSVEBuffer (uint64_t offset=0)
void ConfigureRegisterContext ()
uint32_t CalculateSVEOffset (const lldb_private::RegisterInfo *reg_info)
uint64_t GetSVERegVG ()
Private Attributes
lldb_private::DataExtractor m_gpr_data
lldb_private::DataExtractor m_fpr_data
lldb_private::DataExtractor m_sve_data
lldb_private::DataExtractor m_pac_data
lldb_private::DataExtractor m_tls_data
lldb_private::DataExtractor m_za_data
lldb_private::DataExtractor m_mte_data
lldb_private::DataExtractor m_zt_data
lldb_private::DataExtractor m_fpmr_data
lldb_private::DataExtractor m_gcs_data
lldb_private::DataExtractor m_poe_data
SVEState m_sve_state = SVEState::Unknown
uint16_t m_sve_vector_length = 0
struct sme_pseudo_regs m_sme_pseudo_regs
lldb_private::Arm64RegisterFlagsDetector m_register_flags_detector
Additional Inherited Members
Protected Attributes inherited from RegisterContextPOSIX_arm64
std::unique_ptr< RegisterInfoPOSIX_arm64 > m_register_info_up
Protected Attributes inherited from lldb_private::RegisterContext
Thread & m_thread
uint32_t m_concrete_frame_idx
uint32_t m_stop_id
Detailed Description
Definition at line 20 of file RegisterContextPOSIXCore_arm64.h.
Constructor & Destructor Documentation
~RegisterContextCorePOSIX_arm64()
RegisterContextCorePOSIX_arm64::~RegisterContextCorePOSIX_arm64 () override default
RegisterContextCorePOSIX_arm64()
RegisterContextCorePOSIX_arm64::RegisterContextCorePOSIX_arm64 (lldb_private::Thread & thread, std::unique_ptr< RegisterInfoPOSIX_arm64 > register_info, const lldb_private::DataExtractor & gpregset, llvm::ArrayRef< lldb_private::CoreNote > notes) protected
Definition at line 95 of file RegisterContextPOSIXCore_arm64.cpp.
References lldb_private::AARCH64_FPMR_Desc, lldb_private::AARCH64_GCS_Desc, lldb_private::AARCH64_MTE_Desc, lldb_private::AARCH64_PAC_Desc, lldb_private::AARCH64_POE_Desc, lldb_private::AARCH64_SSVE_Desc, lldb_private::AARCH64_SVE_Desc, lldb_private::AARCH64_TLS_Desc, lldb_private::AARCH64_ZA_Desc, lldb_private::AARCH64_ZT_Desc, AuxVector::AUXV_AT_HWCAP, AuxVector::AUXV_AT_HWCAP2, AuxVector::AUXV_AT_HWCAP3, AuxVector::AUXV_FREEBSD_AT_HWCAP, ConfigureRegisterContext(), lldb_private::FPR_Desc, ProcessElfCore::GetArchitecture(), AuxVector::GetAuxValue(), ProcessElfCore::GetAuxvData(), lldb_private::DataExtractor::GetByteOrder(), lldb_private::DataExtractor::GetByteSize(), lldb_private::DataExtractor::GetDataStart(), RegisterContextPOSIX_arm64::GetRegisterCount(), RegisterContextPOSIX_arm64::GetRegisterInfo(), lldb_private::getRegset(), lldb_private::ArchSpec::GetTriple(), m_fpmr_data, m_fpr_data, m_gcs_data, m_gpr_data, m_mte_data, m_pac_data, m_poe_data, m_register_flags_detector, RegisterContextPOSIX_arm64::m_register_info_up, m_sme_pseudo_regs, m_sve_data, m_sve_state, m_tls_data, m_za_data, m_zt_data, lldb_private::sve::ptrace_regs_mask, lldb_private::sve::ptrace_regs_sve, RegisterContextPOSIX_arm64::RegisterContextPOSIX_arm64(), and Streaming.
Referenced by Create().
Member Function Documentation
__attribute__()
struct RegisterContextCorePOSIX_arm64::__attribute__ ((packed)) inline private
Definition at line 70 of file RegisterContextPOSIXCore_arm64.h.
References __attribute__(), and m_sve_vector_length.
Referenced by __attribute__(), and Create().
CalculateSVEOffset()
uint32_t RegisterContextCorePOSIX_arm64::CalculateSVEOffset (const lldb_private::RegisterInfo * reg_info) private
Definition at line 235 of file RegisterContextPOSIXCore_arm64.cpp.
References lldb_private::RegisterInfo::byte_offset, lldb::eRegisterKindLLDB, FPSIMD, Full, RegisterContextPOSIX_arm64::GetGPRSize(), RegisterContextPOSIX_arm64::GetRegNumSVEZ0(), lldb_private::RegisterInfo::kinds, LLDB_INVALID_INDEX32, m_sve_state, lldb_private::sve::ptrace_fpsimd_offset, lldb_private::sve::SigRegsOffset(), and Streaming.
Referenced by ReadRegister().
ConfigureRegisterContext()
void RegisterContextCorePOSIX_arm64::ConfigureRegisterContext () private
Definition at line 189 of file RegisterContextPOSIXCore_arm64.cpp.
References Disabled, FPSIMD, Full, RegisterContextPOSIX_arm64::m_register_info_up, m_sme_pseudo_regs, m_sve_data, m_sve_state, m_sve_vector_length, m_za_data, lldb_private::sve::ptrace_regs_fpsimd, lldb_private::sve::ptrace_regs_mask, lldb_private::sve::ptrace_regs_sve, Streaming, lldb_private::sve::vl_valid(), and lldb_private::sve::vq_from_vl().
Referenced by RegisterContextCorePOSIX_arm64().
Create()
std::unique_ptr< RegisterContextCorePOSIX_arm64 > RegisterContextCorePOSIX_arm64::Create (lldb_private::Thread & thread, const lldb_private::ArchSpec & arch, const lldb_private::DataExtractor & gpregset, llvm::ArrayRef< lldb_private::CoreNote > notes) static
Definition at line 24 of file RegisterContextPOSIXCore_arm64.cpp.
References __attribute__(), lldb_private::AARCH64_FPMR_Desc, lldb_private::AARCH64_GCS_Desc, lldb_private::AARCH64_MTE_Desc, lldb_private::AARCH64_PAC_Desc, lldb_private::AARCH64_POE_Desc, lldb_private::AARCH64_SSVE_Desc, lldb_private::AARCH64_SVE_Desc, lldb_private::AARCH64_TLS_Desc, lldb_private::AARCH64_ZA_Desc, lldb_private::AARCH64_ZT_Desc, RegisterInfoPOSIX_arm64::eRegsetMaskDefault, RegisterInfoPOSIX_arm64::eRegsetMaskFPMR, RegisterInfoPOSIX_arm64::eRegsetMaskGCS, RegisterInfoPOSIX_arm64::eRegsetMaskMTE, RegisterInfoPOSIX_arm64::eRegsetMaskPAuth, RegisterInfoPOSIX_arm64::eRegsetMaskPOE, RegisterInfoPOSIX_arm64::eRegsetMaskSSVE, RegisterInfoPOSIX_arm64::eRegsetMaskSVE, RegisterInfoPOSIX_arm64::eRegsetMaskTLS, RegisterInfoPOSIX_arm64::eRegsetMaskZA, RegisterInfoPOSIX_arm64::eRegsetMaskZT, lldb_private::DataExtractor::GetByteSize(), lldb_private::getRegset(), lldb_private::ArchSpec::GetTriple(), RegisterContextCorePOSIX_arm64(), and lldb_private::Flags::Set().
Referenced by ThreadElfCore::CreateRegisterContextForFrame().
GetSVEBuffer()
const uint8_t * RegisterContextCorePOSIX_arm64::GetSVEBuffer (uint64_t offset = 0) private
Definition at line 185 of file RegisterContextPOSIXCore_arm64.cpp.
References m_sve_data.
Referenced by ReadRegister().
GetSVERegVG()
uint64_t RegisterContextCorePOSIX_arm64::GetSVERegVG () inline private
Definition at line 89 of file RegisterContextPOSIXCore_arm64.h.
References m_sve_vector_length.
Referenced by ReadRegister().
HardwareSingleStep()
bool RegisterContextCorePOSIX_arm64::HardwareSingleStep (bool enable) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 444 of file RegisterContextPOSIXCore_arm64.cpp.
ReadAllRegisterValues()
bool RegisterContextCorePOSIX_arm64::ReadAllRegisterValues (lldb::WritableDataBufferSP & data_sp) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 429 of file RegisterContextPOSIXCore_arm64.cpp.
ReadFPR()
bool RegisterContextCorePOSIX_arm64::ReadFPR () override protected virtual
Implements RegisterContextPOSIX_arm64.
Definition at line 173 of file RegisterContextPOSIXCore_arm64.cpp.
ReadGPR()
bool RegisterContextCorePOSIX_arm64::ReadGPR () override protected virtual
Implements RegisterContextPOSIX_arm64.
Definition at line 171 of file RegisterContextPOSIXCore_arm64.cpp.
ReadRegister()
bool RegisterContextCorePOSIX_arm64::ReadRegister (const lldb_private::RegisterInfo * reg_info, lldb_private::RegisterValue & value) override virtual
Implements lldb_private::RegisterContext.
Definition at line 252 of file RegisterContextPOSIXCore_arm64.cpp.
References lldb_private::RegisterInfo::byte_offset, lldb_private::RegisterInfo::byte_size, CalculateSVEOffset(), Disabled, lldb::eByteOrderLittle, lldb::eRegisterKindLLDB, error(), FPSIMD, Full, RegisterContextPOSIX_arm64::GetGPRSize(), RegisterContextPOSIX_arm64::GetRegisterInfoAtIndex(), RegisterContextPOSIX_arm64::GetRegNumFPCR(), RegisterContextPOSIX_arm64::GetRegNumFPSR(), GetSVEBuffer(), GetSVERegVG(), lldb_private::endian::InlHostByteOrder(), RegisterContextPOSIX_arm64::IsFPMR(), RegisterContextPOSIX_arm64::IsFPR(), RegisterContextPOSIX_arm64::IsGCS(), RegisterContextPOSIX_arm64::IsMTE(), RegisterContextPOSIX_arm64::IsPAuth(), RegisterContextPOSIX_arm64::IsPOE(), RegisterContextPOSIX_arm64::IsSME(), RegisterContextPOSIX_arm64::IsSVE(), RegisterContextPOSIX_arm64::IsSVEVG(), RegisterContextPOSIX_arm64::IsSVEZ(), RegisterContextPOSIX_arm64::IsTLS(), lldb_private::RegisterInfo::kinds, LLDB_INVALID_REGNUM, m_fpmr_data, m_fpr_data, m_gcs_data, m_gpr_data, m_mte_data, m_pac_data, m_poe_data, RegisterContextPOSIX_arm64::m_register_info_up, m_sme_pseudo_regs, m_sve_data, m_sve_state, m_sve_vector_length, m_tls_data, m_za_data, m_zt_data, lldb_private::sve::ptrace_fpsimd_offset, lldb_private::sve::PTraceFPCROffset(), lldb_private::sve::PTraceFPSROffset(), lldb_private::RegisterValue::SetFromMemoryData(), Streaming, lldb_private::RegisterInfo::value_regs, and lldb_private::sve::vq_from_vl().
WriteAllRegisterValues()
bool RegisterContextCorePOSIX_arm64::WriteAllRegisterValues (const lldb::DataBufferSP & data_sp) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 439 of file RegisterContextPOSIXCore_arm64.cpp.
WriteFPR()
bool RegisterContextCorePOSIX_arm64::WriteFPR () override protected virtual
Implements RegisterContextPOSIX_arm64.
Definition at line 180 of file RegisterContextPOSIXCore_arm64.cpp.
WriteGPR()
bool RegisterContextCorePOSIX_arm64::WriteGPR () override protected virtual
Implements RegisterContextPOSIX_arm64.
Definition at line 175 of file RegisterContextPOSIXCore_arm64.cpp.
WriteRegister()
bool RegisterContextCorePOSIX_arm64::WriteRegister (const lldb_private::RegisterInfo * reg_info, const lldb_private::RegisterValue & value) override virtual
Implements lldb_private::RegisterContext.
Definition at line 434 of file RegisterContextPOSIXCore_arm64.cpp.
Member Data Documentation
m_fpmr_data
lldb_private::DataExtractor RegisterContextCorePOSIX_arm64::m_fpmr_data private
Definition at line 65 of file RegisterContextPOSIXCore_arm64.h.
Referenced by ReadRegister(), and RegisterContextCorePOSIX_arm64().
m_fpr_data
lldb_private::DataExtractor RegisterContextCorePOSIX_arm64::m_fpr_data private
Definition at line 58 of file RegisterContextPOSIXCore_arm64.h.
Referenced by ReadRegister(), and RegisterContextCorePOSIX_arm64().
m_gcs_data
lldb_private::DataExtractor RegisterContextCorePOSIX_arm64::m_gcs_data private
Definition at line 66 of file RegisterContextPOSIXCore_arm64.h.
Referenced by ReadRegister(), and RegisterContextCorePOSIX_arm64().
m_gpr_data
lldb_private::DataExtractor RegisterContextCorePOSIX_arm64::m_gpr_data private
Definition at line 57 of file RegisterContextPOSIXCore_arm64.h.
Referenced by ReadRegister(), and RegisterContextCorePOSIX_arm64().
m_mte_data
lldb_private::DataExtractor RegisterContextCorePOSIX_arm64::m_mte_data private
Definition at line 63 of file RegisterContextPOSIXCore_arm64.h.
Referenced by ReadRegister(), and RegisterContextCorePOSIX_arm64().
m_pac_data
lldb_private::DataExtractor RegisterContextCorePOSIX_arm64::m_pac_data private
Definition at line 60 of file RegisterContextPOSIXCore_arm64.h.
Referenced by ReadRegister(), and RegisterContextCorePOSIX_arm64().
m_poe_data
lldb_private::DataExtractor RegisterContextCorePOSIX_arm64::m_poe_data private
Definition at line 67 of file RegisterContextPOSIXCore_arm64.h.
Referenced by ReadRegister(), and RegisterContextCorePOSIX_arm64().
m_register_flags_detector
lldb_private::Arm64RegisterFlagsDetector RegisterContextCorePOSIX_arm64::m_register_flags_detector private
Definition at line 81 of file RegisterContextPOSIXCore_arm64.h.
Referenced by RegisterContextCorePOSIX_arm64().
m_sme_pseudo_regs
struct sme_pseudo_regs RegisterContextCorePOSIX_arm64::m_sme_pseudo_regs private
Definition at line 79 of file RegisterContextPOSIXCore_arm64.h.
Referenced by ConfigureRegisterContext(), ReadRegister(), and RegisterContextCorePOSIX_arm64().
m_sve_data
lldb_private::DataExtractor RegisterContextCorePOSIX_arm64::m_sve_data private
Definition at line 59 of file RegisterContextPOSIXCore_arm64.h.
Referenced by ConfigureRegisterContext(), GetSVEBuffer(), ReadRegister(), and RegisterContextCorePOSIX_arm64().
m_sve_state
SVEState RegisterContextCorePOSIX_arm64::m_sve_state = SVEState::Unknown private
Definition at line 69 of file RegisterContextPOSIXCore_arm64.h.
Referenced by CalculateSVEOffset(), ConfigureRegisterContext(), ReadRegister(), and RegisterContextCorePOSIX_arm64().
m_sve_vector_length
uint16_t RegisterContextCorePOSIX_arm64::m_sve_vector_length = 0 private
Definition at line 70 of file RegisterContextPOSIXCore_arm64.h.
Referenced by __attribute__(), ConfigureRegisterContext(), GetSVERegVG(), and ReadRegister().
m_tls_data
lldb_private::DataExtractor RegisterContextCorePOSIX_arm64::m_tls_data private
Definition at line 61 of file RegisterContextPOSIXCore_arm64.h.
Referenced by ReadRegister(), and RegisterContextCorePOSIX_arm64().
m_za_data
lldb_private::DataExtractor RegisterContextCorePOSIX_arm64::m_za_data private
Definition at line 62 of file RegisterContextPOSIXCore_arm64.h.
Referenced by ConfigureRegisterContext(), ReadRegister(), and RegisterContextCorePOSIX_arm64().
m_zt_data
lldb_private::DataExtractor RegisterContextCorePOSIX_arm64::m_zt_data private
Definition at line 64 of file RegisterContextPOSIXCore_arm64.h.
Referenced by ReadRegister(), and RegisterContextCorePOSIX_arm64().
The documentation for this class was generated from the following files:
RegisterContextPOSIXCore_arm64.h
RegisterContextPOSIXCore_arm64.cpp