LLDB: lldb_private::SwiftTreeSitterHighlighter Class Reference
lldb_private::SwiftTreeSitterHighlighter Class Reference
#include <SwiftTreeSitterHighlighter.h>
Public Member Functions
SwiftTreeSitterHighlighter ()=default
~SwiftTreeSitterHighlighter () override=default
llvm::StringRef GetName () const override
Returns a human readable name for the selected highlighter.
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::TreeSitterHighlighter
TreeSitterHighlighter ()=default
~TreeSitterHighlighter () override=default
void Highlight (const HighlightStyle &options, llvm::StringRef line, std::optional< size_t > cursor_pos, llvm::StringRef previous_lines, Stream &s) const override
Highlights a single line of code using tree-sitter parsing.
Public Member Functions inherited from lldb_private::Highlighter
Highlighter ()=default
virtual ~Highlighter ()=default
Highlighter (const Highlighter &)=delete
const Highlighter & operator= (const Highlighter &)=delete
std::string Highlight (const HighlightStyle &options, llvm::StringRef line, std::optional< size_t > cursor_pos, llvm::StringRef previous_lines="") const
Utility method for calling Highlight without a stream.
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static Highlighter * CreateInstance (lldb::LanguageType language)
static void Terminate ()
static void Initialize ()
static llvm::StringRef GetPluginNameStatic ()
Protected Member Functions
const TSLanguage * GetLanguage () const override
Returns the tree-sitter language for this highlighter.
llvm::StringRef GetHighlightQuery () const override
Returns the tree-sitter highlight query for this language.
Detailed Description
Definition at line 16 of file SwiftTreeSitterHighlighter.h.
Constructor & Destructor Documentation
SwiftTreeSitterHighlighter()
lldb_private::SwiftTreeSitterHighlighter::SwiftTreeSitterHighlighter () default
Referenced by CreateInstance().
~SwiftTreeSitterHighlighter()
lldb_private::SwiftTreeSitterHighlighter::~SwiftTreeSitterHighlighter () override default
Member Function Documentation
CreateInstance()
Highlighter * SwiftTreeSitterHighlighter::CreateInstance (lldb::LanguageType language) static
Definition at line 30 of file SwiftTreeSitterHighlighter.cpp.
References lldb::eLanguageTypeSwift, and SwiftTreeSitterHighlighter().
Referenced by Initialize(), and Terminate().
GetHighlightQuery()
llvm::StringRef SwiftTreeSitterHighlighter::GetHighlightQuery () const override protected virtual
Returns the tree-sitter highlight query for this language.
Implements lldb_private::TreeSitterHighlighter.
Definition at line 25 of file SwiftTreeSitterHighlighter.cpp.
GetLanguage()
const TSLanguage * SwiftTreeSitterHighlighter::GetLanguage () const override protected virtual
Returns the tree-sitter language for this highlighter.
Implements lldb_private::TreeSitterHighlighter.
Definition at line 21 of file SwiftTreeSitterHighlighter.cpp.
References tree_sitter_swift().
GetName()
llvm::StringRef lldb_private::SwiftTreeSitterHighlighter::GetName () const inline override virtual
Returns a human readable name for the selected highlighter.
Implements lldb_private::Highlighter.
Definition at line 21 of file SwiftTreeSitterHighlighter.h.
GetPluginName()
llvm::StringRef lldb_private::SwiftTreeSitterHighlighter::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 31 of file SwiftTreeSitterHighlighter.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::SwiftTreeSitterHighlighter::GetPluginNameStatic () inline static
Definition at line 28 of file SwiftTreeSitterHighlighter.h.
Referenced by GetPluginName(), and Initialize().
Initialize()
void SwiftTreeSitterHighlighter::Initialize () static
Definition at line 36 of file SwiftTreeSitterHighlighter.cpp.
References CreateInstance(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Terminate()
void SwiftTreeSitterHighlighter::Terminate () static
Definition at line 41 of file SwiftTreeSitterHighlighter.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
The documentation for this class was generated from the following files:
SwiftTreeSitterHighlighter.h
SwiftTreeSitterHighlighter.cpp