LLDB: lldb_private::CPlusPlusLanguage::CxxMethodName Class Reference
lldb_private::CPlusPlusLanguage::CxxMethodName Class Reference
#include <CPlusPlusLanguage.h>
Public Member Functions
CxxMethodName (ConstString s)
bool ContainsPath (llvm::StringRef path)
Public Member Functions inherited from lldb_private::Language::MethodName
MethodName ()
MethodName (ConstString full)
virtual ~MethodName ()
void Clear ()
bool IsValid ()
ConstString GetFullName () const
llvm::StringRef GetBasename ()
llvm::StringRef GetContext ()
llvm::StringRef GetArguments ()
llvm::StringRef GetQualifiers ()
llvm::StringRef GetReturnType ()
std::string GetScopeQualifiedName ()
Protected Member Functions
void Parse () override
bool TrySimplifiedParse ()
Private Member Functions
llvm::StringRef GetBasenameNoTemplateParameters ()
Returns the Basename of this method without a template parameter list, if any.
Additional Inherited Members
Protected Attributes inherited from lldb_private::Language::MethodName
ConstString m_full
llvm::StringRef m_basename
llvm::StringRef m_context
llvm::StringRef m_arguments
llvm::StringRef m_qualifiers
llvm::StringRef m_return_type
std::string m_scope_qualified
bool m_parsed = false
bool m_parse_error = false
Detailed Description
Definition at line 25 of file CPlusPlusLanguage.h.
Constructor & Destructor Documentation
CxxMethodName()
lldb_private::CPlusPlusLanguage::CxxMethodName::CxxMethodName (ConstString s) inline
Definition at line 27 of file CPlusPlusLanguage.h.
References lldb_private::Language::Language(), and lldb_private::Language::MethodName::MethodName().
Member Function Documentation
ContainsPath()
bool CPlusPlusLanguage::CxxMethodName::ContainsPath (llvm::StringRef path)
Definition at line 552 of file CPlusPlusLanguage.cpp.
References lldb_private::CPlusPlusLanguage::ExtractContextAndIdentifier(), lldb_private::Language::MethodName::GetBasename(), GetBasenameNoTemplateParameters(), lldb_private::Language::MethodName::m_context, lldb_private::Language::MethodName::m_full, lldb_private::Language::MethodName::m_parse_error, lldb_private::Language::MethodName::m_parsed, and Parse().
Referenced by lldb_private::CPlusPlusLanguage::DemangledNameContainsPath().
GetBasenameNoTemplateParameters()
llvm::StringRef CPlusPlusLanguage::CxxMethodName::GetBasenameNoTemplateParameters () private
Returns the Basename of this method without a template parameter list, if any.
Definition at line 542 of file CPlusPlusLanguage.cpp.
References lldb_private::Language::MethodName::GetBasename(), and ReverseFindMatchingChars().
Referenced by ContainsPath().
Parse()
void CPlusPlusLanguage::CxxMethodName::Parse () override protected virtual
Reimplemented from lldb_private::Language::MethodName.
Definition at line 513 of file CPlusPlusLanguage.cpp.
References lldb_private::Language::MethodName::m_arguments, lldb_private::Language::MethodName::m_basename, lldb_private::Language::MethodName::m_context, lldb_private::Language::MethodName::m_full, lldb_private::Language::MethodName::m_parse_error, lldb_private::Language::MethodName::m_parsed, lldb_private::Language::MethodName::m_qualifiers, lldb_private::Language::MethodName::m_return_type, lldb_private::Language::MethodName::m_scope_qualified, lldb_private::CPlusPlusNameParser::ParseAsFunctionDefinition(), and TrySimplifiedParse().
Referenced by ContainsPath().
TrySimplifiedParse()
bool CPlusPlusLanguage::CxxMethodName::TrySimplifiedParse () protected
Definition at line 471 of file CPlusPlusLanguage.cpp.
References IsTrivialBasename(), IsTrivialContext(), lldb_private::Language::MethodName::m_arguments, lldb_private::Language::MethodName::m_basename, lldb_private::Language::MethodName::m_context, lldb_private::Language::MethodName::m_full, lldb_private::Language::MethodName::m_qualifiers, lldb_private::Language::MethodName::m_return_type, and ReverseFindMatchingChars().
Referenced by Parse().
The documentation for this class was generated from the following files:
CPlusPlusLanguage.h
CPlusPlusLanguage.cpp