LLDB: lldb_private::DeclVendor Class Reference
lldb_private::DeclVendor Class Reference abstract
#include <DeclVendor.h>
Public Types
enum DeclVendorKind { eClangModuleDeclVendor , eAppleObjCDeclVendor , eLastClangDeclVendor }
Public Member Functions
DeclVendor (DeclVendorKind kind)
virtual ~DeclVendor ()=default
DeclVendorKind GetKind () const
virtual uint32_t FindDecls (ConstString name, bool append, uint32_t max_matches, std::vector< CompilerDecl > &decls)=0
Look up the set of Decls that the DeclVendor currently knows about matching a given name.
std::vector< CompilerType > FindTypes (ConstString name, uint32_t max_matches)
Look up the types that the DeclVendor currently knows about matching a given name.
Private Member Functions
DeclVendor (const DeclVendor &)=delete
const DeclVendor & operator= (const DeclVendor &)=delete
Private Attributes
const DeclVendorKind m_kind
Detailed Description
Definition at line 20 of file DeclVendor.h.
Member Enumeration Documentation
DeclVendorKind
enum lldb_private::DeclVendor::DeclVendorKind
Enumerator
eClangModuleDeclVendor
eAppleObjCDeclVendor
eLastClangDeclVendor
Definition at line 22 of file DeclVendor.h.
Constructor & Destructor Documentation
DeclVendor() [1/2]
lldb_private::DeclVendor::DeclVendor (DeclVendorKind kind) inline
Definition at line 28 of file DeclVendor.h.
References m_kind.
Referenced by lldb_private::AppleObjCDeclVendor::AppleObjCDeclVendor(), lldb_private::ClangModulesDeclVendor::ClangModulesDeclVendor(), lldb_private::AppleObjCDeclVendor::classof(), lldb_private::ClangModulesDeclVendor::classof(), DeclVendor(), and operator=().
~DeclVendor()
virtual lldb_private::DeclVendor::~DeclVendor () virtual default
DeclVendor() [2/2]
lldb_private::DeclVendor::DeclVendor (const DeclVendor &) private delete
References DeclVendor().
Member Function Documentation
FindDecls()
virtual uint32_t lldb_private::DeclVendor::FindDecls (ConstString name, bool append, uint32_t max_matches, std::vector< CompilerDecl > & decls) pure virtual
Look up the set of Decls that the DeclVendor currently knows about matching a given name.
Parameters
[in] name The name to look for.
[in] append If true, FindDecls will clear "decls" when it starts.
[in] max_matches The maximum number of Decls to return. UINT32_MAX means "as many as possible."
Returns
The number of Decls added to decls; will not exceed max_matches.
Implemented in lldb_private::AppleObjCDeclVendor.
Referenced by FindTypes().
FindTypes()
std::vector< CompilerType > DeclVendor::FindTypes (ConstString name, uint32_t max_matches)
Look up the types that the DeclVendor currently knows about matching a given name.
Parameters
[in] name The name to look for.
[in] max_matches
Returns
The vector of CompilerTypes that was found.
Definition at line 18 of file DeclVendor.cpp.
References FindDecls().
Referenced by lldb_private::AppleObjCTypeEncodingParser::BuildObjCObjectPointerType().
GetKind()
DeclVendorKind lldb_private::DeclVendor::GetKind () const inline
Definition at line 32 of file DeclVendor.h.
References m_kind.
Referenced by lldb_private::AppleObjCDeclVendor::classof(), and lldb_private::ClangModulesDeclVendor::classof().
operator=()
const DeclVendor & lldb_private::DeclVendor::operator= (const DeclVendor &) private delete
References DeclVendor().
Member Data Documentation
m_kind
const DeclVendorKind lldb_private::DeclVendor::m_kind private
Definition at line 72 of file DeclVendor.h.
Referenced by DeclVendor(), and GetKind().
The documentation for this class was generated from the following files:
DeclVendor.h
DeclVendor.cpp