LLDB: lldb::SBTypeList Class Reference
lldb::SBTypeList Class Reference
#include <SBType.h>
Public Member Functions
SBTypeList ()
SBTypeList (const lldb::SBTypeList &rhs)
~SBTypeList ()
lldb::SBTypeList & operator= (const lldb::SBTypeList &rhs)
operator bool () const
bool IsValid ()
void Append (lldb::SBType type)
lldb::SBType GetTypeAtIndex (uint32_t index)
uint32_t GetSize ()
Private Attributes
std::unique_ptr< lldb_private::TypeListImpl > m_opaque_up
Friends
class SBModule
class SBCompileUnit
Detailed Description
Definition at line 297 of file SBType.h.
Constructor & Destructor Documentation
SBTypeList() [1/2]
SBTypeList::SBTypeList ()
Definition at line 733 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by operator=(), and SBTypeList().
SBTypeList() [2/2]
SBTypeList::SBTypeList (const lldb::SBTypeList & rhs)
Definition at line 737 of file SBType.cpp.
References Append(), GetSize(), GetTypeAtIndex(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBTypeList().
~SBTypeList()
SBTypeList::~SBTypeList () default
Member Function Documentation
Append()
void SBTypeList::Append (lldb::SBType type)
Definition at line 768 of file SBType.cpp.
References lldb::SBType::IsValid(), LLDB_INSTRUMENT_VA, lldb::SBType::m_opaque_sp, and m_opaque_up.
Referenced by lldb::SBModule::FindTypes(), lldb::SBTarget::FindTypes(), lldb::SBType::GetFunctionArgumentTypes(), operator=(), and SBTypeList().
GetSize()
uint32_t SBTypeList::GetSize ()
Definition at line 783 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBTarget::FindTypes(), operator=(), and SBTypeList().
GetTypeAtIndex()
SBType SBTypeList::GetTypeAtIndex (uint32_t index)
Definition at line 775 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBType.
Referenced by operator=(), and SBTypeList().
IsValid()
bool SBTypeList::IsValid ()
Definition at line 746 of file SBType.cpp.
References LLDB_INSTRUMENT_VA.
operator bool()
SBTypeList::operator bool () const explicit
Definition at line 750 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
operator=()
SBTypeList & SBTypeList::operator= (const lldb::SBTypeList & rhs)
Definition at line 756 of file SBType.cpp.
References Append(), GetSize(), GetTypeAtIndex(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBTypeList().
Friends And Related Symbol Documentation
SBCompileUnit
friend class SBCompileUnit friend
Definition at line 320 of file SBType.h.
References SBCompileUnit.
Referenced by SBCompileUnit.
SBModule
friend class SBModule friend
Definition at line 319 of file SBType.h.
References SBModule.
Referenced by SBModule.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::TypeListImpl> lldb::SBTypeList::m_opaque_up private
Definition at line 318 of file SBType.h.
Referenced by Append(), GetSize(), GetTypeAtIndex(), lldb::SBCompileUnit::GetTypes(), lldb::SBModule::GetTypes(), operator bool(), operator=(), SBTypeList(), and SBTypeList().
The documentation for this class was generated from the following files:
SBType.h
SBType.cpp