LLDB: lldb_private::StatisticsMap Class Reference
lldb_private::StatisticsMap Class Reference
A class to count time for plugins.
#include <Statistics.h>
Public Member Functions
void add (llvm::StringRef key, double value)
void merge (StatisticsMap map_to_merge)
Public Attributes
llvm::StringMap< double > map
Detailed Description
A class to count time for plugins.
Definition at line 94 of file Statistics.h.
Member Function Documentation
add()
void lldb_private::StatisticsMap::add (llvm::StringRef key, double value) inline
Definition at line 96 of file Statistics.h.
References map.
Referenced by lldb_private::PluginManager::LocateExecutableObjectFile(), lldb_private::PluginManager::LocateExecutableSymbolFile(), and merge().
merge()
void lldb_private::StatisticsMap::merge (StatisticsMap map_to_merge) inline
Definition at line 105 of file Statistics.h.
References add(), and map.
Referenced by lldb_private::DebuggerStats::ReportStatistics().
Member Data Documentation
map
llvm::StringMap<double> lldb_private::StatisticsMap::map
Definition at line 110 of file Statistics.h.
Referenced by add(), and merge().
The documentation for this class was generated from the following file:
Statistics.h