LLDB: CoreSimulatorSupport::DeviceSet Class Reference
CoreSimulatorSupport::DeviceSet Class Reference
#include <PlatformiOSSimulatorCoreSimulatorSupport.h>
Public Member Functions
size_t GetNumDevices ()
Device GetDeviceAtIndex (size_t idx)
void ForEach (std::function< bool(const Device &)> f)
DeviceSet GetDevicesIf (std::function< bool(Device)> f)
DeviceSet GetDevices (DeviceType::ProductFamilyID dev_id)
Device GetFanciest (DeviceType::ProductFamilyID dev_id)
Static Public Member Functions
static DeviceSet GetAllDevices (const char *developer_dir)
static DeviceSet GetAvailableDevices (const char *developer_dir)
Private Member Functions
DeviceSet (id arr)
Private Attributes
id m_dev
Detailed Description
Definition at line 196 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
Constructor & Destructor Documentation
DeviceSet()
CoreSimulatorSupport::DeviceSet::DeviceSet (id arr) inline private
Definition at line 215 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
References m_dev.
Referenced by GetAvailableDevices().
Member Function Documentation
ForEach()
void CoreSimulatorSupport::DeviceSet::ForEach (std::function< bool(const Device &)> f)
Definition at line 590 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
Referenced by lldb_private::PlatformAppleSimulator::ConnectRemote().
GetAllDevices()
CoreSimulatorSupport::DeviceSet CoreSimulatorSupport::DeviceSet::GetAllDevices (const char * developer_dir) static
Definition at line 541 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References error().
GetAvailableDevices()
CoreSimulatorSupport::DeviceSet CoreSimulatorSupport::DeviceSet::GetAvailableDevices (const char * developer_dir) static
Definition at line 559 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References DeviceSet(), and error().
Referenced by lldb_private::PlatformAppleSimulator::ConnectRemote(), and lldb_private::PlatformAppleSimulator::GetStatus().
GetDeviceAtIndex()
CoreSimulatorSupport::Device CoreSimulatorSupport::DeviceSet::GetDeviceAtIndex (size_t idx)
Definition at line 572 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
Referenced by GetDevices(), and lldb_private::PlatformAppleSimulator::GetStatus().
GetDevices()
CoreSimulatorSupport::DeviceSet CoreSimulatorSupport::DeviceSet::GetDevices (DeviceType::ProductFamilyID dev_id)
Definition at line 599 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References GetDeviceAtIndex().
GetDevicesIf()
CoreSimulatorSupport::DeviceSet CoreSimulatorSupport::DeviceSet::GetDevicesIf (std::function< bool(Device)> f)
Definition at line 578 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References GetNumDevices(), and m_dev.
GetFanciest()
CoreSimulatorSupport::Device CoreSimulatorSupport::DeviceSet::GetFanciest (DeviceType::ProductFamilyID dev_id)
Definition at line 613 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
GetNumDevices()
size_t CoreSimulatorSupport::DeviceSet::GetNumDevices ()
Definition at line 567 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
Referenced by GetDevicesIf(), and lldb_private::PlatformAppleSimulator::GetStatus().
Member Data Documentation
m_dev
id CoreSimulatorSupport::DeviceSet::m_dev private
Definition at line 217 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
Referenced by DeviceSet(), and GetDevicesIf().
The documentation for this class was generated from the following files:
PlatformiOSSimulatorCoreSimulatorSupport.h
PlatformiOSSimulatorCoreSimulatorSupport.mm