LLDB: lldb_private::Host Class Reference
lldb_private::Host Class Reference
A class that provides host computer information.
#include "lldb/Host/Host.h"
Public Types
typedef std::function< void(lldb::pid_t pid, int signal, int status)> MonitorChildProcessCallback
typedef std::map< lldb::pid_t, bool > TidMap
typedef std::pair< lldb::pid_t, bool > TidPair
Static Public Member Functions
static llvm::Expected< HostThread > StartMonitoringChildProcess (const MonitorChildProcessCallback &callback, lldb::pid_t pid)
Start monitoring a child process.
static void SystemLog (lldb::Severity severity, llvm::StringRef message)
Emit the given message to the operating system log.
static lldb::pid_t GetCurrentProcessID ()
Get the process ID for the calling process.
static void Kill (lldb::pid_t pid, int signo)
static lldb::thread_t GetCurrentThread ()
Get the thread token (the one returned by ThreadCreate when the thread was created) for the calling thread in the current process.
static const char * GetSignalAsCString (int signo)
static FileSpec GetModuleFileSpecForHostAddress (const void *host_addr)
Given an address in the current process (the process that is running the LLDB code), return the name of the module that it comes from.
static bool GetBundleDirectory (const FileSpec &file, FileSpec &bundle_directory)
If you have an executable that is in a bundle and want to get back to the bundle directory from the path itself, this function will change a path to a file within a bundle to the bundle directory itself.
static bool ResolveExecutableInBundle (FileSpec &file)
When executable files may live within a directory, where the directory represents an executable bundle (like the MacOSX app bundles), then locate the executable within the containing bundle.
static uint32_t FindProcesses (const ProcessInstanceInfoMatch &match_info, ProcessInstanceInfoList &proc_infos)
static bool FindProcessThreads (const lldb::pid_t pid, TidMap &tids_to_attach)
static bool GetProcessInfo (lldb::pid_t pid, ProcessInstanceInfo &proc_info)
static Status LaunchProcess (ProcessLaunchInfo &launch_info)
Launch the process specified in launch_info.
static Status ShellExpandArguments (ProcessLaunchInfo &launch_info)
Perform expansion of the command-line for this launch info This can potentially involve wildcard expansion environment variable replacement, and whatever other argument magic the platform defines as part of its typical user experience.
static Status RunShellCommand (llvm::StringRef command, const FileSpec &working_dir, int *status_ptr, int *signo_ptr, std::string *command_output, const Timeout< std::micro > &timeout, bool run_in_shell=true, bool hide_stderr=false)
Run a shell command.
static Status RunShellCommand (llvm::StringRef shell, llvm::StringRef command, const FileSpec &working_dir, int *status_ptr, int *signo_ptr, std::string *command_output, const Timeout< std::micro > &timeout, bool run_in_shell=true, bool hide_stderr=false)
Run a shell command.
static Status RunShellCommand (const Args &args, const FileSpec &working_dir, int *status_ptr, int *signo_ptr, std::string *command_output, const Timeout< std::micro > &timeout, bool run_in_shell=true, bool hide_stderr=false)
Run a shell command.
static Status RunShellCommand (llvm::StringRef shell, const Args &args, const FileSpec &working_dir, int *status_ptr, int *signo_ptr, std::string *command_output, const Timeout< std::micro > &timeout, bool run_in_shell=true, bool hide_stderr=false)
Run a shell command.
static llvm::Error OpenFileInExternalEditor (llvm::StringRef editor, const FileSpec &file_spec, uint32_t line_no)
static llvm::Error OpenURL (llvm::StringRef url)
static bool IsInteractiveGraphicSession ()
Check if we're running in an interactive graphical session.
static Environment GetEnvironment ()
static std::unique_ptr< Connection > CreateDefaultConnection (llvm::StringRef url)
Static Protected Member Functions
static uint32_t FindProcessesImpl (const ProcessInstanceInfoMatch &match_info, ProcessInstanceInfoList &proc_infos)
Detailed Description
A class that provides host computer information.
Host is a class that answers information about the host operating system.
Definition at line 82 of file Host.h.
Member Typedef Documentation
MonitorChildProcessCallback
typedef std::function<void(lldb::pid_t pid, int signal, int status)> lldb_private::Host::MonitorChildProcessCallback
Definition at line 88 of file Host.h.
TidMap
typedef std::map<lldb::pid_t, bool> lldb_private::Host::TidMap
Definition at line 179 of file Host.h.
TidPair
typedef std::pair<lldb::pid_t, bool> lldb_private::Host::TidPair
Definition at line 180 of file Host.h.
Member Function Documentation
CreateDefaultConnection()
std::unique_ptr< Connection > Host::CreateDefaultConnection (llvm::StringRef url) static
Definition at line 573 of file common/Host.cpp.
Referenced by lldb::SBCommunication::Connect().
FindProcesses()
uint32_t Host::FindProcesses (const ProcessInstanceInfoMatch & match_info, ProcessInstanceInfoList & proc_infos) static
Definition at line 629 of file common/Host.cpp.
References FindProcessesImpl().
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::AttachWaitProcess(), lldb_private::Platform::FindProcesses(), lldb_private::PlatformAppleSimulator::FindProcesses(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qfProcessInfo().
FindProcessesImpl()
uint32_t Host::FindProcessesImpl (const ProcessInstanceInfoMatch & match_info, ProcessInstanceInfoList & proc_infos) static protected
Definition at line 135 of file aix/Host.cpp.
References lldb_private::ProcessInstanceInfoMatch::GetMatchAllUsers(), GetProcessAndStatInfo(), lldb_private::ProcessInfo::GetUserID(), lldb_private::ProcessInstanceInfoMatch::Matches(), and lldb_private::State.
Referenced by FindProcesses().
FindProcessThreads()
bool Host::FindProcessThreads (const lldb::pid_t pid, TidMap & tids_to_attach) static
Definition at line 362 of file common/Host.cpp.
Referenced by lldb_private::process_linux::NativeProcessLinux::Attach().
GetBundleDirectory()
bool Host::GetBundleDirectory (const FileSpec & file, FileSpec & bundle_directory) static
If you have an executable that is in a bundle and want to get back to the bundle directory from the path itself, this function will change a path to a file within a bundle to the bundle directory itself.
Parameters
[in] file A file spec that might point to a file in a bundle.
[out] bundle_directory An object will be filled in with the bundle directory for the bundle when true is returned. Otherwise file is left untouched and false is returned.
Returns
true if file was resolved in bundle_directory, false otherwise.
Definition at line 337 of file common/Host.cpp.
References lldb_private::FileSpec::Clear().
Referenced by lldb_private::PlatformDarwin::GetSharedModule().
GetCurrentProcessID()
lldb::pid_t Host::GetCurrentProcessID () static
Get the process ID for the calling process.
Returns
The process ID for the current process.
Definition at line 239 of file common/Host.cpp.
Referenced by lldb_private::HostInfoBase::ComputeProcessTempFileDirectory().
GetCurrentThread()
lldb::thread_t Host::GetCurrentThread () static
Get the thread token (the one returned by ThreadCreate when the thread was created) for the calling thread in the current process.
Returns
The thread token for the calling thread in the current process.
Definition at line 243 of file common/Host.cpp.
Referenced by lldb_private::Process::CurrentThreadIsPrivateStateThread(), lldb_private::Process::CurrentThreadPosesAsPrivateStateThread(), lldb_private::Process::PrivateStateThread::GetRunLock(), lldb_private::Debugger::IsIOHandlerThreadCurrentThread(), lldb_private::CommandInterpreter::RunCommandInterpreter(), and lldb_private::Process::RunThreadPlan().
GetEnvironment()
Environment Host::GetEnvironment () static
Definition at line 113 of file common/Host.cpp.
References environ.
Referenced by lldb_private::PlatformQemuUser::DebugProcess(), GetDebugserverPath(), lldb_private::Platform::GetEnvironment(), lldb_private::PlatformQemuUser::GetEnvironment(), RunShellCommand(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess().
GetModuleFileSpecForHostAddress()
FileSpec Host::GetModuleFileSpecForHostAddress (const void * host_addr) static
Given an address in the current process (the process that is running the LLDB code), return the name of the module that it comes from.
This can be useful when you need to know the path to the shared library that your code is running in for loading resources that are relative to your binary.
Parameters
[in] host_addr The pointer to some code in the current process.
Returns
A file spec with the module that contains host_addr, which may be invalid if host_addr doesn't fall into any valid module address range.
Definition at line 347 of file common/Host.cpp.
References lldb_private::FileSystem::Instance(), lldb_private::FileSystem::Resolve(), and lldb_private::FileSpec::SetFile().
Referenced by lldb_private::HostInfoBase::ComputeSharedLibraryDirectory().
GetProcessInfo()
bool Host::GetProcessInfo (lldb::pid_t pid, ProcessInstanceInfo & proc_info) static
Definition at line 177 of file aix/Host.cpp.
References GetProcessAndStatInfo(), and lldb_private::State.
Referenced by lldb_private::process_freebsd::NativeProcessFreeBSD::Manager::Attach(), lldb_private::process_netbsd::NativeProcessNetBSD::Manager::Attach(), lldb_private::NativeThreadWindows::GetName(), lldb_private::PlatformDarwin::GetOSVersion(), lldb_private::Platform::GetProcessInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qProcessInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qProcessInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qProcessInfoPID(), lldb_private::process_freebsd::NativeProcessFreeBSD::Manager::Launch(), lldb_private::process_netbsd::NativeProcessNetBSD::Manager::Launch(), lldb_private::NativeProcessWindows::NativeProcessWindows(), and lldb_private::NativeProcessWindows::OnDebuggerConnected().
GetSignalAsCString()
const char * Host::GetSignalAsCString (int signo) static
Definition at line 247 of file common/Host.cpp.
References SIGBUS, SIGFPE, SIGILL, SIGKILL, SIGSEGV, SIGSTOP, and SIGTRAP.
Referenced by CommandObjectPlatformShell::DoExecute(), lldb_private::process_linux::NativeProcessLinux::MonitorSignal(), and lldb_private::process_linux::NativeProcessLinux::Signal().
IsInteractiveGraphicSession()
bool Host::IsInteractiveGraphicSession () static
Check if we're running in an interactive graphical session.
Returns
True if we're running in an interactive graphical session. False if we're not or don't know.
Definition at line 570 of file common/Host.cpp.
Referenced by lldb_private::CommandInterpreter::SaveTranscript().
Kill()
void Host::Kill (lldb::pid_t pid, int signo) static
Definition at line 558 of file common/Host.cpp.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qLaunchGDBServer(), lldb_private::process_gdb_remote::ProcessGDBRemote::KillDebugserverProcess(), lldb_private::Platform::KillProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::KillSpawnedProcess(), and RunShellCommand().
LaunchProcess()
Status Host::LaunchProcess (ProcessLaunchInfo & launch_info) static
Launch the process specified in launch_info.
The monitoring callback in launch_info must be set, and it will be called when the process terminates.
Definition at line 537 of file common/Host.cpp.
References error(), lldb_private::HostProcess::GetProcessId(), lldb_private::MonitoringProcessLauncher::LaunchProcess(), and lldb_private::ProcessInfo::SetProcessID().
Referenced by lldb_private::PlatformQemuUser::DebugProcess(), lldb_private::PlatformWasm::DebugProcess(), lldb_private::Platform::LaunchProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::LaunchProcess(), RunShellCommand(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess().
OpenFileInExternalEditor()
llvm::Error Host::OpenFileInExternalEditor (llvm::StringRef editor, const FileSpec & file_spec, uint32_t line_no) static
Definition at line 563 of file common/Host.cpp.
Referenced by lldb_private::Thread::GetStatus(), lldb_private::CommandInterpreter::SaveTranscript(), and lldb_private::Thread::SetSelectedFrameByIndexNoisily().
OpenURL()
llvm::Error Host::OpenURL (llvm::StringRef url) static
Definition at line 455 of file Host.mm.
References error(), CFCReleaser< T >::get(), lldb_private::GetLog(), lldb_private::Host, and LLDB_LOG.
ResolveExecutableInBundle()
bool Host::ResolveExecutableInBundle (FileSpec & file) static
When executable files may live within a directory, where the directory represents an executable bundle (like the MacOSX app bundles), then locate the executable within the containing bundle.
Parameters
[in,out] file A file spec that currently points to the bundle that will be filled in with the executable path within the bundle if true is returned. Otherwise file is left untouched.
Returns
true if file was resolved, false if this function was not able to resolve the path.
Definition at line 342 of file common/Host.cpp.
Referenced by lldb::SBModuleSpecList::GetModuleSpecifications(), lldb_private::PlatformDarwin::GetSharedModule(), and lldb_private::Platform::ResolveExecutable().
RunShellCommand() [1/4]
Status Host::RunShellCommand (const Args & args, const FileSpec & working_dir, int * status_ptr, int * signo_ptr, std::string * command_output, const Timeout< std::micro > & timeout, bool run_in_shell = true, bool hide_stderr = false) static
Run a shell command.
working_dir Pass empty FileSpec to use the current working directory
status_ptr Pass NULL if you don't want the process exit status
signo_ptr Pass NULL if you don't want the signal that caused the process to exit
command_output Pass NULL if you don't want the command output
hide_stderr if this is false, redirect stderr to stdout
Definition at line 410 of file common/Host.cpp.
References RunShellCommand().
RunShellCommand() [2/4]
Status Host::RunShellCommand (llvm::StringRef command, const FileSpec & working_dir, int * status_ptr, int * signo_ptr, std::string * command_output, const Timeout< std::micro > & timeout, bool run_in_shell = true, bool hide_stderr = false) static
Run a shell command.
command shouldn't be empty
working_dir Pass empty FileSpec to use the current working directory
status_ptr Pass NULL if you don't want the process exit status
signo_ptr Pass NULL if you don't want the signal that caused the process to exit
command_output Pass NULL if you don't want the command output
hide_stderr if this is false, redirect stderr to stdout
Definition at line 389 of file common/Host.cpp.
References RunShellCommand().
Referenced by lldb_private::SymbolLocatorDebugSymbols::DownloadObjectAndSymbolFile(), PlatformPOSIX::GetFile(), GetXcodeSelectPath(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qPlatform_shell(), PlatformPOSIX::PutFile(), RunShellCommand(), RunShellCommand(), RunShellCommand(), lldb_private::Platform::RunShellCommand(), and xcrun().
RunShellCommand() [3/4]
Status Host::RunShellCommand (llvm::StringRef shell, const Args & args, const FileSpec & working_dir, int * status_ptr, int * signo_ptr, std::string * command_output, const Timeout< std::micro > & timeout, bool run_in_shell = true, bool hide_stderr = false) static
Run a shell command.
shell Pass an empty string if you want to use the default shell interpreter
command
working_dir Pass empty FileSpec to use the current working directory
status_ptr Pass NULL if you don't want the process exit status
signo_ptr Pass NULL if you don't want the signal that caused the process to exit
command_output Pass NULL if you don't want the command output
hide_stderr If this is false, redirect stderr to stdout
Definition at line 420 of file common/Host.cpp.
References lldb_private::Args::AppendArguments(), lldb_private::ProcessLaunchInfo::AppendDuplicateFileAction(), lldb_private::ProcessLaunchInfo::AppendOpenFileAction(), lldb_private::ProcessLaunchInfo::AppendSuppressFileAction(), lldb_private::ProcessLaunchInfo::ConvertArgumentsForLaunchingInShell(), lldb_private::FileSystem::CreateWritableDataBuffer(), error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::ProcessInfo::GetArguments(), lldb_private::FileSystem::GetByteSize(), GetEnvironment(), lldb_private::ProcessInfo::GetEnvironment(), lldb_private::FileSpec::GetPath(), lldb_private::ProcessInfo::GetProcessID(), lldb_private::FileSystem::Instance(), Kill(), LaunchProcess(), LLDB_INVALID_PROCESS_ID, MonitorShellCommand(), lldb_private::ProcessInfo::SetArchitecture(), lldb_private::ProcessInfo::SetArguments(), lldb_private::ProcessLaunchInfo::SetMonitorProcessCallback(), lldb_private::FileSpec::SetPath(), lldb_private::ProcessLaunchInfo::SetShell(), lldb_private::ProcessLaunchInfo::SetWorkingDirectory(), and SIGKILL.
RunShellCommand() [4/4]
Status Host::RunShellCommand (llvm::StringRef shell, llvm::StringRef command, const FileSpec & working_dir, int * status_ptr, int * signo_ptr, std::string * command_output, const Timeout< std::micro > & timeout, bool run_in_shell = true, bool hide_stderr = false) static
Run a shell command.
shell Pass an empty string if you want to use the default shell interpreter
command
working_dir Pass empty FileSpec to use the current working directory
status_ptr Pass NULL if you don't want the process exit status
signo_ptr Pass NULL if you don't want the signal that caused the process to exit
command_output Pass NULL if you don't want the command output
hide_stderr If this is false, redirect stderr to stdout
Definition at line 399 of file common/Host.cpp.
References RunShellCommand().
ShellExpandArguments()
Status Host::ShellExpandArguments (ProcessLaunchInfo & launch_info) static
Perform expansion of the command-line for this launch info This can potentially involve wildcard expansion environment variable replacement, and whatever other argument magic the platform defines as part of its typical user experience.
Definition at line 182 of file aix/Host.cpp.
References lldb_private::Status.
Referenced by lldb_private::Platform::ShellExpandArguments().
StartMonitoringChildProcess()
llvm::Expected< HostThread > Host::StartMonitoringChildProcess (const MonitorChildProcessCallback & callback, lldb::pid_t pid) static
Start monitoring a child process.
Allows easy monitoring of child processes. callback will be called when the child process exits or if it dies from a signal.
Parameters
[in] callback A function callback to call when a child receives a signal or exits.
[in] pid The process ID of a child process to monitor.
Returns
A thread handle that can be used to cancel the thread that was spawned to monitor pid.
Definition at line 119 of file common/Host.cpp.
References lldb_private::ThreadLauncher::LaunchThread(), MonitorChildProcessThreadFunction(), and UINT32_MAX.
Referenced by lldb_private::ProcessLaunchInfo::MonitorProcess(), and lldb_private::HostProcessPosix::StartMonitoring().
SystemLog()
void Host::SystemLog (lldb::Severity severity, llvm::StringRef message) static
Emit the given message to the operating system log.
Definition at line 91 of file common/Host.cpp.
Referenced by lldb_private::SystemLogHandler::Emit(), and lldb_private::Debugger::ReportDiagnosticImpl().
The documentation for this class was generated from the following files:
Host.h
aix/Host.cpp
common/Host.cpp
freebsd/Host.cpp
linux/Host.cpp
Host.mm
HostNetBSD.cpp
openbsd/Host.cpp
windows/Host.cpp