LLDB: lldb_private::wasm::RegisterContextWasm Class Reference
lldb_private::wasm::RegisterContextWasm Class Reference
#include <RegisterContextWasm.h>
Public Member Functions
RegisterContextWasm (process_gdb_remote::ThreadGDBRemote &thread, uint32_t concrete_frame_idx, process_gdb_remote::GDBRemoteDynamicRegisterInfoSP reg_info_sp)
~RegisterContextWasm () override
uint32_t ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num) override
Convert from a given register numbering scheme to the lldb register numbering scheme.
void InvalidateAllRegisters () override
size_t GetRegisterCount () override
const RegisterInfo * GetRegisterInfoAtIndex (size_t reg) override
size_t GetRegisterSetCount () override
const RegisterSet * GetRegisterSet (size_t reg_set) override
bool ReadRegister (const RegisterInfo *reg_info, RegisterValue &value) override
bool WriteRegister (const RegisterInfo *reg_info, const RegisterValue &value) override
Public Member Functions inherited from lldb_private::process_gdb_remote::GDBRemoteRegisterContext
GDBRemoteRegisterContext (ThreadGDBRemote &thread, uint32_t concrete_frame_idx, GDBRemoteDynamicRegisterInfoSP reg_info_sp, bool read_all_at_once, bool write_all_at_once)
~GDBRemoteRegisterContext () override
bool ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp) override
bool WriteAllRegisterValues (const lldb::DataBufferSP &data_sp) override
bool ReadAllRegisterValues (RegisterCheckpoint &reg_checkpoint) override
bool WriteAllRegisterValues (const RegisterCheckpoint &reg_checkpoint) override
bool RegisterWriteCausesReconfigure (const llvm::StringRef name) override
bool ReconfigureRegisterInfo () override
Public Member Functions inherited from lldb_private::RegisterContext
RegisterContext (Thread &thread, uint32_t concrete_frame_idx)
~RegisterContext () override
void InvalidateIfNeeded (bool force)
virtual lldb::ByteOrder GetByteOrder ()
bool CopyFromRegisterContext (lldb::RegisterContextSP context)
virtual uint32_t NumSupportedHardwareBreakpoints ()
virtual uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual bool ClearHardwareBreakpoint (uint32_t hw_idx)
virtual uint32_t NumSupportedHardwareWatchpoints ()
virtual uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, bool read, bool write)
virtual bool ClearHardwareWatchpoint (uint32_t hw_index)
virtual bool HardwareSingleStep (bool enable)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, uint32_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, uint32_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual Thread & GetThread ()
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num)
uint64_t GetPC (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetThreadPointer (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool GetPCForSymbolication (Address &address)
Get an address suitable for symbolication.
bool SetPC (uint64_t pc)
bool SetPC (Address addr)
uint64_t GetSP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetSP (uint64_t sp)
uint64_t GetFP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetFP (uint64_t fp)
const char * GetRegisterName (uint32_t reg)
uint64_t GetReturnAddress (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetFlags (uint64_t fail_value=0)
uint64_t ReadRegisterAsUnsigned (uint32_t reg, uint64_t fail_value)
uint64_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, uint64_t fail_value)
bool WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
bool WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
bool ConvertBetweenRegisterKinds (lldb::RegisterKind source_rk, uint32_t source_regnum, lldb::RegisterKind target_rk, uint32_t &target_regnum)
lldb::TargetSP CalculateTarget () override
lldb::ProcessSP CalculateProcess () override
lldb::ThreadSP CalculateThread () override
lldb::StackFrameSP CalculateStackFrame () override
void CalculateExecutionContext (ExecutionContext &exe_ctx) override
Reconstruct the object's execution context into sc.
uint32_t GetStopID () const
void SetStopID (uint32_t stop_id)
Public Member Functions inherited from lldb_private::ExecutionContextScope
virtual ~ExecutionContextScope ()=default
Private Attributes
std::unordered_map< size_t, std::unique_ptr< WasmVirtualRegisterInfo > > m_register_map
Additional Inherited Members
Protected Member Functions inherited from lldb_private::process_gdb_remote::GDBRemoteRegisterContext
bool ReadRegisterBytes (const RegisterInfo *reg_info)
bool WriteRegisterBytes (const RegisterInfo *reg_info, DataExtractor &data, uint32_t data_offset)
bool PrivateSetRegisterValue (uint32_t reg, llvm::ArrayRef< uint8_t > data)
bool PrivateSetRegisterValue (uint32_t reg, uint64_t val)
void SetAllRegisterValid (bool b)
bool GetRegisterIsValid (uint32_t reg) const
void SetRegisterIsValid (const RegisterInfo *reg_info, bool valid)
void SetRegisterIsValid (uint32_t reg, bool valid)
Protected Member Functions inherited from lldb_private::RegisterContext
virtual bool BehavesLikeZerothFrame () const
Indicates that this frame is currently executing code, that the PC value is not a return-pc but an actual executing instruction.
Protected Attributes inherited from lldb_private::process_gdb_remote::GDBRemoteRegisterContext
GDBRemoteDynamicRegisterInfoSP m_reg_info_sp
std::vector< bool > m_reg_valid
DataExtractor m_reg_data
bool m_read_all_at_once
bool m_write_all_at_once
bool m_gpacket_cached
Protected Attributes inherited from lldb_private::RegisterContext
Thread & m_thread
uint32_t m_concrete_frame_idx
uint32_t m_stop_id
Detailed Description
Definition at line 34 of file RegisterContextWasm.h.
Constructor & Destructor Documentation
RegisterContextWasm()
RegisterContextWasm::RegisterContextWasm (process_gdb_remote::ThreadGDBRemote & thread, uint32_t concrete_frame_idx, process_gdb_remote::GDBRemoteDynamicRegisterInfoSP reg_info_sp)
Definition at line 24 of file RegisterContextWasm.cpp.
References lldb_private::process_gdb_remote::GDBRemoteRegisterContext::GDBRemoteRegisterContext(), and lldb_private::process_gdb_remote::GDBRemoteRegisterContext::ThreadGDBRemote.
~RegisterContextWasm()
RegisterContextWasm::~RegisterContextWasm () override default
Member Function Documentation
ConvertRegisterKindToRegisterNumber()
uint32_t RegisterContextWasm::ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num) override virtual
Convert from a given register numbering scheme to the lldb register numbering scheme.
There may be multiple ways to enumerate the registers for a given architecture. ABI references will specify one to be used with DWARF, the register numberings from process plugin, there may be a variation used for eh_frame unwind instructions (e.g. on Darwin), and so on. Register 5 by itself is meaningless - RegisterKind enumeration tells you what context that number should be translated as.
Inside lldb, register numbers are in the eRegisterKindLLDB scheme; arguments which take a register number should take one in that scheme.
eRegisterKindGeneric is a special numbering scheme which gives us constant values for the pc, frame register, stack register, etc., for use within lldb. They may not be defined for all architectures but it allows generic code to translate these common registers into the lldb numbering scheme.
This method translates a given register kind + register number into the eRegisterKindLLDB register numbering.
Parameters
[in] kind The register numbering scheme (RegisterKind) that the following register number is in.
[in] num A register number in the 'kind' register numbering scheme.
Returns
The equivalent register number in the eRegisterKindLLDB numbering scheme, if possible, else LLDB_INVALID_REGNUM.
Reimplemented from lldb_private::process_gdb_remote::GDBRemoteRegisterContext.
Definition at line 32 of file RegisterContextWasm.cpp.
GetRegisterCount()
size_t RegisterContextWasm::GetRegisterCount () override virtual
Reimplemented from lldb_private::process_gdb_remote::GDBRemoteRegisterContext.
Definition at line 37 of file RegisterContextWasm.cpp.
GetRegisterInfoAtIndex()
const RegisterInfo * RegisterContextWasm::GetRegisterInfoAtIndex (size_t reg) override virtual
Reimplemented from lldb_private::process_gdb_remote::GDBRemoteRegisterContext.
Definition at line 42 of file RegisterContextWasm.cpp.
References lldb_private::eWasmTagNotAWasmLocation, lldb_private::GetWasmVirtualRegisterIndex(), lldb_private::GetWasmVirtualRegisterTag(), lldb_private::process_gdb_remote::GDBRemoteRegisterContext::m_reg_info_sp, and m_register_map.
GetRegisterSet()
const RegisterSet * RegisterContextWasm::GetRegisterSet (size_t reg_set) override virtual
Reimplemented from lldb_private::process_gdb_remote::GDBRemoteRegisterContext.
Definition at line 60 of file RegisterContextWasm.cpp.
GetRegisterSetCount()
size_t RegisterContextWasm::GetRegisterSetCount () override virtual
Reimplemented from lldb_private::process_gdb_remote::GDBRemoteRegisterContext.
Definition at line 58 of file RegisterContextWasm.cpp.
InvalidateAllRegisters()
void RegisterContextWasm::InvalidateAllRegisters () override virtual
Reimplemented from lldb_private::process_gdb_remote::GDBRemoteRegisterContext.
Definition at line 101 of file RegisterContextWasm.cpp.
ReadRegister()
bool RegisterContextWasm::ReadRegister (const RegisterInfo * reg_info, RegisterValue & value) override virtual
Reimplemented from lldb_private::process_gdb_remote::GDBRemoteRegisterContext.
Definition at line 65 of file RegisterContextWasm.cpp.
References lldb_private::RegisterInfo::byte_offset, lldb_private::RegisterInfo::byte_size, lldb::eEncodingUint, lldb_private::RegisterInfo::encoding, error(), lldb_private::Process::GetAddressByteSize(), lldb_private::Process::GetByteOrder(), lldb_private::GetLog(), lldb_private::RegisterContext::GetThread(), lldb_private::wasm::ProcessWasm::GetWasmVariable(), lldb_private::wasm::WasmVirtualRegisterInfo::index, lldb_private::wasm::WasmVirtualRegisterInfo::kind, LLDB_LOG_ERROR, lldb_private::RegisterContext::m_concrete_frame_idx, lldb_private::RegisterInfo::name, lldb_private::Process, lldb_private::process_gdb_remote::GDBRemoteRegisterContext::ReadRegister(), and lldb_private::RegisterValue::SetValueFromData().
WriteRegister()
bool RegisterContextWasm::WriteRegister (const RegisterInfo * reg_info, const RegisterValue & value) override virtual
Reimplemented from lldb_private::process_gdb_remote::GDBRemoteRegisterContext.
Definition at line 103 of file RegisterContextWasm.cpp.
References lldb_private::RegisterInfo::name, and lldb_private::process_gdb_remote::GDBRemoteRegisterContext::WriteRegister().
Member Data Documentation
m_register_map
std::unordered_map<size_t, std::unique_ptr<WasmVirtualRegisterInfo> > lldb_private::wasm::RegisterContextWasm::m_register_map private
Definition at line 64 of file RegisterContextWasm.h.
Referenced by GetRegisterInfoAtIndex().
The documentation for this class was generated from the following files:
RegisterContextWasm.h
RegisterContextWasm.cpp