LLDB: lldb_private::ProcessLaunchInfo Class Reference
lldb_private::ProcessLaunchInfo Class Reference
#include <ProcessLaunchInfo.h>
Public Member Functions
ProcessLaunchInfo ()
ProcessLaunchInfo (const FileSpec &stdin_file_spec, const FileSpec &stdout_file_spec, const FileSpec &stderr_file_spec, const FileSpec &working_dir, uint32_t launch_flags)
void AppendFileAction (const FileAction &info)
bool AppendCloseFileAction (int fd)
bool AppendDuplicateFileAction (int fd, int dup_fd)
bool AppendOpenFileAction (int fd, const FileSpec &file_spec, bool read, bool write)
bool AppendSuppressFileAction (int fd, bool read, bool write)
llvm::Error SetUpPtyRedirection ()
size_t GetNumFileActions () const
const FileAction * GetFileActionAtIndex (size_t idx) const
const FileAction * GetFileActionForFD (int fd) const
Flags & GetFlags ()
const Flags & GetFlags () const
const FileSpec & GetWorkingDirectory () const
void SetWorkingDirectory (const FileSpec &working_dir)
llvm::StringRef GetProcessPluginName () const
void SetProcessPluginName (llvm::StringRef plugin)
const FileSpec & GetShell () const
void SetShell (const FileSpec &shell)
uint32_t GetResumeCount () const
void SetResumeCount (uint32_t c)
bool GetLaunchInSeparateProcessGroup () const
void SetLaunchInSeparateProcessGroup (bool separate)
bool GetShellExpandArguments () const
void SetShellExpandArguments (bool expand)
void Clear ()
bool ConvertArgumentsForLaunchingInShell (Status &error, bool will_debug, bool first_arg_is_full_shell_command, uint32_t num_resumes)
void SetMonitorProcessCallback (Host::MonitorChildProcessCallback callback)
const Host::MonitorChildProcessCallback & GetMonitorProcessCallback () const
bool MonitorProcess () const
PTY & GetPTY () const
std::shared_ptr< PTY > TakePTY ()
bool ShouldUsePTY () const
Returns whether if lldb should read information from the PTY.
void SetLaunchEventData (const char *data)
const char * GetLaunchEventData () const
void SetDetachOnError (bool enable)
bool GetDetachOnError () const
Public Member Functions inherited from lldb_private::ProcessInfo
ProcessInfo ()
ProcessInfo (const char *name, const ArchSpec &arch, lldb::pid_t pid)
void Clear ()
const char * GetName () const
llvm::StringRef GetNameAsStringRef () const
FileSpec & GetExecutableFile ()
void SetExecutableFile (const FileSpec &exe_file, bool add_exe_file_as_first_arg)
const FileSpec & GetExecutableFile () const
uint32_t GetUserID () const
uint32_t GetGroupID () const
bool UserIDIsValid () const
bool GroupIDIsValid () const
void SetUserID (uint32_t uid)
void SetGroupID (uint32_t gid)
ArchSpec & GetArchitecture ()
const ArchSpec & GetArchitecture () const
void SetArchitecture (const ArchSpec &arch)
lldb::pid_t GetProcessID () const
void SetProcessID (lldb::pid_t pid)
bool ProcessIDIsValid () const
void Dump (Stream &s, Platform *platform) const
Args & GetArguments ()
const Args & GetArguments () const
llvm::StringRef GetArg0 () const
void SetArg0 (llvm::StringRef arg)
void SetArguments (const Args &args, bool first_arg_is_executable)
void SetArguments (char const **argv, bool first_arg_is_executable)
Environment & GetEnvironment ()
const Environment & GetEnvironment () const
bool IsScriptedProcess () const
lldb::ScriptedMetadataSP GetScriptedMetadata () const
void SetScriptedMetadata (lldb::ScriptedMetadataSP metadata_sp)
lldb::ListenerSP GetListener () const
void SetListener (const lldb::ListenerSP &listener_sp)
lldb::ListenerSP GetHijackListener () const
void SetHijackListener (const lldb::ListenerSP &listener_sp)
lldb::ListenerSP GetShadowListener () const
void SetShadowListener (const lldb::ListenerSP &listener_sp)
Static Public Member Functions
static void NoOpMonitorCallback (lldb::pid_t pid, int signal, int status)
A Monitor callback which does not take any action on process events.
Protected Attributes
FileSpec m_working_dir
std::string m_plugin_name
FileSpec m_shell
Flags m_flags
std::vector< FileAction > m_file_actions
std::shared_ptr< PTY > m_pty
uint32_t m_resume_count = 0
Host::MonitorChildProcessCallback m_monitor_callback
std::string m_event_data
Protected Attributes inherited from lldb_private::ProcessInfo
FileSpec m_executable
std::string m_arg0
Args m_arguments
Environment m_environment
uint32_t m_uid = UINT32_MAX
uint32_t m_gid = UINT32_MAX
ArchSpec m_arch
lldb::pid_t m_pid = LLDB_INVALID_PROCESS_ID
lldb::ScriptedMetadataSP m_scripted_metadata_sp = nullptr
lldb::ListenerSP m_listener_sp = nullptr
lldb::ListenerSP m_hijack_listener_sp = nullptr
lldb::ListenerSP m_shadow_listener_sp = nullptr
Detailed Description
Definition at line 40 of file ProcessLaunchInfo.h.
Constructor & Destructor Documentation
ProcessLaunchInfo() [1/2]
ProcessLaunchInfo::ProcessLaunchInfo ()
Definition at line 34 of file ProcessLaunchInfo.cpp.
References m_file_actions, m_flags, m_monitor_callback, m_plugin_name, m_pty, m_working_dir, and lldb_private::ProcessInfo::ProcessInfo().
Referenced by lldb_private::SBLaunchInfoImpl::operator=().
ProcessLaunchInfo() [2/2]
ProcessLaunchInfo::ProcessLaunchInfo (const FileSpec & stdin_file_spec, const FileSpec & stdout_file_spec, const FileSpec & stderr_file_spec, const FileSpec & working_dir, uint32_t launch_flags)
Definition at line 42 of file ProcessLaunchInfo.cpp.
References AppendFileAction(), m_file_actions, m_flags, m_plugin_name, m_pty, m_working_dir, lldb_private::FileAction::Open(), lldb_private::ProcessInfo::ProcessInfo(), and SetWorkingDirectory().
Member Function Documentation
AppendCloseFileAction()
bool ProcessLaunchInfo::AppendCloseFileAction (int fd)
Definition at line 77 of file ProcessLaunchInfo.cpp.
References AppendFileAction(), and lldb_private::FileAction::Close().
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess().
AppendDuplicateFileAction()
bool ProcessLaunchInfo::AppendDuplicateFileAction (int fd, int dup_fd)
Definition at line 86 of file ProcessLaunchInfo.cpp.
References AppendFileAction(), and lldb_private::FileAction::Duplicate().
Referenced by lldb_private::Host::RunShellCommand(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess().
AppendFileAction()
void lldb_private::ProcessLaunchInfo::AppendFileAction (const FileAction & info) inline
Definition at line 49 of file ProcessLaunchInfo.h.
References m_file_actions.
Referenced by AppendCloseFileAction(), AppendDuplicateFileAction(), AppendOpenFileAction(), AppendSuppressFileAction(), and ProcessLaunchInfo().
AppendOpenFileAction()
bool ProcessLaunchInfo::AppendOpenFileAction (int fd, const FileSpec & file_spec, bool read, bool write)
Definition at line 95 of file ProcessLaunchInfo.cpp.
References AppendFileAction(), and lldb_private::FileAction::Open().
Referenced by lldb_private::Target::FinalizeFileActions(), lldb_private::Host::RunShellCommand(), and SetUpPtyRedirection().
AppendSuppressFileAction()
bool ProcessLaunchInfo::AppendSuppressFileAction (int fd, bool read, bool write)
Definition at line 105 of file ProcessLaunchInfo.cpp.
References AppendFileAction(), lldb_private::FileSystem::DEV_NULL, and lldb_private::FileAction::Open().
Referenced by lldb_private::Target::FinalizeFileActions(), lldb_private::Host::RunShellCommand(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess().
Clear()
void ProcessLaunchInfo::Clear ()
Definition at line 170 of file ProcessLaunchInfo.cpp.
References lldb_private::ProcessInfo::Clear(), m_file_actions, m_flags, lldb_private::ProcessInfo::m_hijack_listener_sp, lldb_private::ProcessInfo::m_listener_sp, m_plugin_name, m_resume_count, m_shell, and m_working_dir.
ConvertArgumentsForLaunchingInShell()
bool ProcessLaunchInfo::ConvertArgumentsForLaunchingInShell (Status & error, bool will_debug, bool first_arg_is_full_shell_command, uint32_t num_resumes)
Definition at line 245 of file ProcessLaunchInfo.cpp.
References lldb_private::Args::AppendArgument(), lldb_private::ArchSpec::eCore_x86_64_x86_64h, error(), lldb_private::Status::FromErrorString(), lldb_private::ProcessInfo::GetArchitecture(), lldb_private::ProcessInfo::GetArguments(), lldb_private::Args::GetConstArgumentVector(), GetFlags(), lldb_private::FileSpec::GetPath(), lldb_private::Args::GetShellSafeArgument(), lldb_private::StreamString::GetString(), lldb_private::ArchSpec::GetTriple(), GetWorkingDirectory(), lldb_private::FileSpec::IsRelative(), lldb_private::ProcessInfo::m_arguments, lldb_private::ProcessInfo::m_executable, m_shell, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and SetResumeCount().
Referenced by lldb_private::Platform::LaunchProcess(), and lldb_private::Host::RunShellCommand().
GetDetachOnError()
bool lldb_private::ProcessLaunchInfo::GetDetachOnError () const inline
Definition at line 154 of file ProcessLaunchInfo.h.
References m_flags.
Referenced by lldb_private::ProcessAttachInfo::ProcessAttachInfo().
GetFileActionAtIndex()
const FileAction * ProcessLaunchInfo::GetFileActionAtIndex (size_t idx) const
Definition at line 115 of file ProcessLaunchInfo.cpp.
References m_file_actions.
Referenced by PlatformPOSIX::DebugProcess(), lldb_private::ProcessLauncherWindows::GetInheritedHandles(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::LaunchProcess(), LaunchProcessPosixSpawn(), and MakeForkActions().
GetFileActionForFD()
const FileAction * ProcessLaunchInfo::GetFileActionForFD (int fd) const
Definition at line 121 of file ProcessLaunchInfo.cpp.
References m_file_actions.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::DoLaunch(), lldb_private::Target::FinalizeFileActions(), lldb_private::ProcessLauncherWindows::GetStdioHandle(), HandleFileAction(), LaunchProcessXPC(), MaybeLogLaunchInfo(), lldb_private::TargetProperties::SetProcessLaunchInfo(), and SetUpPtyRedirection().
GetFlags() [1/2]
Flags & lldb_private::ProcessLaunchInfo::GetFlags () inline
Definition at line 73 of file ProcessLaunchInfo.h.
References m_flags.
Referenced by ConvertArgumentsForLaunchingInShell(), lldb_private::Platform::DebugProcess(), lldb_private::PlatformAppleSimulator::DebugProcess(), lldb_private::PlatformQemuUser::DebugProcess(), lldb_private::PlatformWasm::DebugProcess(), lldb_private::PlatformWindows::DebugProcess(), PlatformPOSIX::DebugProcess(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoLaunch(), lldb_private::StructuredDataDarwinLog::FilterLaunchInfo(), lldb_private::Target::FinalizeFileActions(), GetPosixspawnFlags(), lldb_private::platform_linux::PlatformLinux::GetResumeCountForLaunchInfo(), lldb_private::platform_netbsd::PlatformNetBSD::GetResumeCountForLaunchInfo(), lldb_private::Process::Launch(), lldb_private::Target::Launch(), lldb_private::MonitoringProcessLauncher::LaunchProcess(), lldb_private::Platform::LaunchProcess(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::LaunchProcess(), lldb_private::ProcessDebugger::LaunchProcess(), lldb_private::ProcessLauncherWindows::LaunchProcess(), LaunchProcessPosixSpawn(), lldb_private::TargetProperties::SetProcessLaunchInfo(), and CoreSimulatorSupport::Device::Spawn().
GetFlags() [2/2]
const Flags & lldb_private::ProcessLaunchInfo::GetFlags () const inline
Definition at line 75 of file ProcessLaunchInfo.h.
References m_flags.
GetLaunchEventData()
const char * lldb_private::ProcessLaunchInfo::GetLaunchEventData () const inline
Definition at line 150 of file ProcessLaunchInfo.h.
References m_event_data.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::DoLaunch().
GetLaunchInSeparateProcessGroup()
bool lldb_private::ProcessLaunchInfo::GetLaunchInSeparateProcessGroup () const inline
Definition at line 93 of file ProcessLaunchInfo.h.
References m_flags.
Referenced by GetPosixspawnFlags(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess().
GetMonitorProcessCallback()
const Host::MonitorChildProcessCallback & lldb_private::ProcessLaunchInfo::GetMonitorProcessCallback () const inline
Definition at line 115 of file ProcessLaunchInfo.h.
References m_monitor_callback.
Referenced by lldb_private::MonitoringProcessLauncher::LaunchProcess().
GetNumFileActions()
size_t lldb_private::ProcessLaunchInfo::GetNumFileActions () const inline
Definition at line 67 of file ProcessLaunchInfo.h.
References m_file_actions.
Referenced by lldb_private::ProcessLauncherWindows::GetInheritedHandles(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::LaunchProcess(), LaunchProcessPosixSpawn(), MakeForkActions(), and ShouldUsePTY().
GetProcessPluginName()
llvm::StringRef ProcessLaunchInfo::GetProcessPluginName () const
Definition at line 137 of file ProcessLaunchInfo.cpp.
References m_plugin_name.
Referenced by lldb_private::platform_gdb_server::PlatformRemoteGDBServer::DebugProcess(), lldb_private::PlatformWindows::DebugProcess(), lldb_private::Target::Launch(), and lldb_private::ProcessAttachInfo::ProcessAttachInfo().
GetPTY()
PTY & lldb_private::ProcessLaunchInfo::GetPTY () const inline
Definition at line 131 of file ProcessLaunchInfo.h.
References m_pty.
Referenced by lldb_private::Platform::DebugProcess(), lldb_private::PlatformAppleSimulator::DebugProcess(), lldb_private::PlatformQemuUser::DebugProcess(), lldb_private::PlatformWasm::DebugProcess(), PlatformPOSIX::DebugProcess(), HandleFileAction(), lldb_private::process_aix::NativeProcessAIX::Manager::Launch(), lldb_private::process_freebsd::NativeProcessFreeBSD::Manager::Launch(), lldb_private::process_linux::NativeProcessLinux::Manager::Launch(), lldb_private::process_netbsd::NativeProcessNetBSD::Manager::Launch(), lldb_private::ProcessLauncherWindows::LaunchProcess(), and ShouldUsePTY().
GetResumeCount()
uint32_t lldb_private::ProcessLaunchInfo::GetResumeCount () const inline
Definition at line 89 of file ProcessLaunchInfo.h.
References m_resume_count.
Referenced by lldb_private::Platform::LaunchProcess(), and lldb_private::ProcessAttachInfo::ProcessAttachInfo().
GetShell()
const FileSpec & ProcessLaunchInfo::GetShell () const
Definition at line 145 of file ProcessLaunchInfo.cpp.
References m_shell.
Referenced by lldb_private::platform_linux::PlatformLinux::GetResumeCountForLaunchInfo(), lldb_private::platform_netbsd::PlatformNetBSD::GetResumeCountForLaunchInfo(), lldb_private::PlatformDarwin::GetResumeCountForLaunchInfo(), lldb_private::Target::Launch(), lldb_private::Platform::LaunchProcess(), and LaunchProcessPosixSpawn().
GetShellExpandArguments()
bool lldb_private::ProcessLaunchInfo::GetShellExpandArguments () const inline
Definition at line 99 of file ProcessLaunchInfo.h.
References m_flags.
GetWorkingDirectory()
const FileSpec & ProcessLaunchInfo::GetWorkingDirectory () const
Definition at line 129 of file ProcessLaunchInfo.cpp.
References m_working_dir.
Referenced by ConvertArgumentsForLaunchingInShell(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoLaunch(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::LaunchProcess(), lldb_private::ProcessDebugger::LaunchProcess(), lldb_private::ProcessLauncherWindows::LaunchProcess(), and LaunchProcessPosixSpawn().
MonitorProcess()
bool ProcessLaunchInfo::MonitorProcess () const
Definition at line 188 of file ProcessLaunchInfo.cpp.
References lldb_private::GetLog(), lldb_private::ProcessInfo::GetProcessID(), lldb_private::Host, LLDB_LOG_ERROR, m_monitor_callback, lldb_private::ProcessInfo::ProcessIDIsValid(), and lldb_private::Host::StartMonitoringChildProcess().
NoOpMonitorCallback()
void ProcessLaunchInfo::NoOpMonitorCallback (lldb::pid_t pid, int signal, int status) static
A Monitor callback which does not take any action on process events.
Use this if you don't need to take any particular action when the process terminates, but you still need to reap it.
Definition at line 182 of file ProcessLaunchInfo.cpp.
References lldb_private::GetLog(), LLDB_LOG, and lldb_private::Process.
Referenced by lldb_private::PlatformDarwin::DebugProcess(), and lldb_private::PlatformQemuUser::DebugProcess().
SetDetachOnError()
void ProcessLaunchInfo::SetDetachOnError (bool enable)
Definition at line 200 of file ProcessLaunchInfo.cpp.
References m_flags.
SetLaunchEventData()
void lldb_private::ProcessLaunchInfo::SetLaunchEventData (const char * data) inline
Definition at line 148 of file ProcessLaunchInfo.h.
References m_event_data.
SetLaunchInSeparateProcessGroup()
void ProcessLaunchInfo::SetLaunchInSeparateProcessGroup (bool separate)
Definition at line 156 of file ProcessLaunchInfo.cpp.
References m_flags, and separate().
Referenced by lldb_private::Platform::DebugProcess(), lldb_private::PlatformAppleSimulator::DebugProcess(), lldb_private::PlatformQemuUser::DebugProcess(), lldb_private::PlatformWasm::DebugProcess(), PlatformPOSIX::DebugProcess(), lldb_private::process_gdb_remote::ProcessGDBRemote::LaunchAndConnectToDebugserver(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::LaunchGDBServer().
SetMonitorProcessCallback()
void lldb_private::ProcessLaunchInfo::SetMonitorProcessCallback (Host::MonitorChildProcessCallback callback) inline
Definition at line 111 of file ProcessLaunchInfo.h.
References m_monitor_callback.
Referenced by lldb_private::PlatformDarwin::DebugProcess(), lldb_private::PlatformQemuUser::DebugProcess(), lldb_private::PlatformWasm::DebugProcess(), lldb_private::process_gdb_remote::ProcessGDBRemote::LaunchAndConnectToDebugserver(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::LaunchGDBServer(), and lldb_private::Host::RunShellCommand().
SetProcessPluginName()
void ProcessLaunchInfo::SetProcessPluginName (llvm::StringRef plugin)
Definition at line 141 of file ProcessLaunchInfo.cpp.
References m_plugin_name.
Referenced by lldb_private::Target::SaveScriptedLaunchInfo().
SetResumeCount()
void lldb_private::ProcessLaunchInfo::SetResumeCount (uint32_t c) inline
Definition at line 91 of file ProcessLaunchInfo.h.
References m_resume_count.
Referenced by ConvertArgumentsForLaunchingInShell().
SetShell()
void ProcessLaunchInfo::SetShell (const FileSpec & shell)
Definition at line 147 of file ProcessLaunchInfo.cpp.
References lldb_private::FileSystem::Instance(), m_flags, m_shell, and lldb_private::FileSystem::ResolveExecutableLocation().
Referenced by lldb_private::Host::RunShellCommand().
SetShellExpandArguments()
void ProcessLaunchInfo::SetShellExpandArguments (bool expand)
Definition at line 163 of file ProcessLaunchInfo.cpp.
References m_flags.
SetUpPtyRedirection()
llvm::Error ProcessLaunchInfo::SetUpPtyRedirection ()
Definition at line 207 of file ProcessLaunchInfo.cpp.
References AppendOpenFileAction(), GetFileActionForFD(), lldb_private::GetLog(), LLDB_LOG, m_pty, O_NOCTTY, and lldb_private::Process.
Referenced by lldb_private::PlatformQemuUser::DebugProcess(), lldb_private::PlatformWasm::DebugProcess(), and lldb_private::Target::FinalizeFileActions().
SetWorkingDirectory()
void ProcessLaunchInfo::SetWorkingDirectory (const FileSpec & working_dir)
Definition at line 133 of file ProcessLaunchInfo.cpp.
References m_working_dir.
Referenced by ProcessLaunchInfo(), and lldb_private::Host::RunShellCommand().
ShouldUsePTY()
bool lldb_private::ProcessLaunchInfo::ShouldUsePTY () const inline
Returns whether if lldb should read information from the PTY.
This is always true on non Windows.
Definition at line 137 of file ProcessLaunchInfo.h.
References GetNumFileActions(), GetPTY(), and m_pty.
Referenced by lldb_private::ProcessLauncherWindows::LaunchProcess().
TakePTY()
std::shared_ptr< PTY > lldb_private::ProcessLaunchInfo::TakePTY () inline
Definition at line 133 of file ProcessLaunchInfo.h.
References m_pty.
Referenced by lldb_private::ProcessWindows::DoLaunch().
Member Data Documentation
m_event_data
std::string lldb_private::ProcessLaunchInfo::m_event_data protected
Definition at line 167 of file ProcessLaunchInfo.h.
Referenced by GetLaunchEventData(), and SetLaunchEventData().
m_file_actions
std::vector<FileAction> lldb_private::ProcessLaunchInfo::m_file_actions protected
Definition at line 163 of file ProcessLaunchInfo.h.
Referenced by AppendFileAction(), Clear(), GetFileActionAtIndex(), GetFileActionForFD(), GetNumFileActions(), ProcessLaunchInfo(), and ProcessLaunchInfo().
m_flags
Flags lldb_private::ProcessLaunchInfo::m_flags protected
Definition at line 162 of file ProcessLaunchInfo.h.
Referenced by Clear(), GetDetachOnError(), GetFlags(), GetFlags(), GetLaunchInSeparateProcessGroup(), GetShellExpandArguments(), ProcessLaunchInfo(), ProcessLaunchInfo(), SetDetachOnError(), SetLaunchInSeparateProcessGroup(), SetShell(), and SetShellExpandArguments().
m_monitor_callback
Host::MonitorChildProcessCallback lldb_private::ProcessLaunchInfo::m_monitor_callback protected
Definition at line 166 of file ProcessLaunchInfo.h.
Referenced by GetMonitorProcessCallback(), MonitorProcess(), ProcessLaunchInfo(), and SetMonitorProcessCallback().
m_plugin_name
std::string lldb_private::ProcessLaunchInfo::m_plugin_name protected
Definition at line 160 of file ProcessLaunchInfo.h.
Referenced by Clear(), GetProcessPluginName(), ProcessLaunchInfo(), ProcessLaunchInfo(), and SetProcessPluginName().
m_pty
std::shared_ptr<PTY> lldb_private::ProcessLaunchInfo::m_pty protected
Definition at line 164 of file ProcessLaunchInfo.h.
Referenced by GetPTY(), ProcessLaunchInfo(), ProcessLaunchInfo(), SetUpPtyRedirection(), ShouldUsePTY(), and TakePTY().
m_resume_count
uint32_t lldb_private::ProcessLaunchInfo::m_resume_count = 0 protected
Definition at line 165 of file ProcessLaunchInfo.h.
Referenced by Clear(), GetResumeCount(), and SetResumeCount().
m_shell
FileSpec lldb_private::ProcessLaunchInfo::m_shell protected
Definition at line 161 of file ProcessLaunchInfo.h.
Referenced by Clear(), ConvertArgumentsForLaunchingInShell(), GetShell(), and SetShell().
m_working_dir
FileSpec lldb_private::ProcessLaunchInfo::m_working_dir protected
Definition at line 159 of file ProcessLaunchInfo.h.
Referenced by Clear(), GetWorkingDirectory(), ProcessLaunchInfo(), ProcessLaunchInfo(), and SetWorkingDirectory().
The documentation for this class was generated from the following files:
ProcessLaunchInfo.h
ProcessLaunchInfo.cpp