LLDB: InstrumentationBoundsSafetyStopInfo Class Reference
InstrumentationBoundsSafetyStopInfo Class Reference
Public Member Functions
~InstrumentationBoundsSafetyStopInfo () override=default
lldb::StopReason GetStopReason () const override
std::optional< uint32_t > GetSuggestedStackFrameIndex (bool inlined_stack) override
This gives the StopInfo a chance to suggest a stack frame to select.
const char * GetDescription () override
bool DoShouldNotify (Event *event_ptr) override
Public Member Functions inherited from lldb_private::StopInfo
StopInfo (Thread &thread, uint64_t value)
virtual ~StopInfo ()=default
bool IsValid () const
void SetThread (const lldb::ThreadSP &thread_sp)
lldb::ThreadSP GetThread () const
uint64_t GetValue () const
virtual bool ShouldStopSynchronous (Event *event_ptr)
void OverrideShouldNotify (bool override_value)
virtual bool ShouldNotify (Event *event_ptr)
virtual void WillResume (lldb::StateType resume_state)
virtual void SetDescription (const char *desc_cstr)
virtual bool IsValidForOperatingSystemThread (Thread &thread)
virtual bool WasContinueInterrupted (Thread &thread)
A Continue operation can result in a false stop event before any execution has happened.
virtual uint32_t GetStopReasonDataCount () const
virtual uint64_t GetStopReasonDataAtIndex (uint32_t idx)
void OverrideShouldStop (bool override_value)
bool GetOverrideShouldStop ()
bool GetOverriddenShouldStopValue ()
StructuredData::ObjectSP GetExtendedInfo ()
virtual bool ShouldShow () const
Returns true if this is a stop reason that should be shown to a user when viewing the thread with this stop info.
virtual bool ShouldSelect () const
Returns true if this is a stop reason that should cause a thread to be selected when stopping.
Static Public Member Functions
static lldb::StopInfoSP CreateInstrumentationBoundsSafetyStopInfo (Thread &thread)
Static Public Member Functions inherited from lldb_private::StopInfo
static lldb::StopInfoSP CreateStopReasonWithBreakpointSiteID (Thread &thread, lldb::break_id_t break_id)
static lldb::StopInfoSP CreateStopReasonWithBreakpointSiteID (Thread &thread, lldb::break_id_t break_id, bool should_stop)
static lldb::StopInfoSP CreateStopReasonWithWatchpointID (Thread &thread, lldb::break_id_t watch_id, bool silently_continue=false)
static lldb::StopInfoSP CreateStopReasonWithSignal (Thread &thread, int signo, const char *description=nullptr, std::optional< int > code=std::nullopt)
static lldb::StopInfoSP CreateStopReasonWithInterrupt (Thread &thread, int signo, const char *description)
static lldb::StopInfoSP CreateStopReasonToTrace (Thread &thread)
static lldb::StopInfoSP CreateStopReasonWithPlan (lldb::ThreadPlanSP &plan, lldb::ValueObjectSP return_valobj_sp, lldb::ExpressionVariableSP expression_variable_sp)
static lldb::StopInfoSP CreateStopReasonWithException (Thread &thread, const char *description)
static lldb::StopInfoSP CreateStopReasonWithExec (Thread &thread)
static lldb::StopInfoSP CreateStopReasonProcessorTrace (Thread &thread, const char *description)
static lldb::StopInfoSP CreateStopReasonHistoryBoundary (Thread &thread, const char *description)
static lldb::StopInfoSP CreateStopReasonFork (Thread &thread, lldb::pid_t child_pid, lldb::tid_t child_tid)
static lldb::StopInfoSP CreateStopReasonVFork (Thread &thread, lldb::pid_t child_pid, lldb::tid_t child_tid)
static lldb::StopInfoSP CreateStopReasonVForkDone (Thread &thread)
static lldb::ValueObjectSP GetReturnValueObject (lldb::StopInfoSP &stop_info_sp)
static lldb::ExpressionVariableSP GetExpressionVariable (lldb::StopInfoSP &stop_info_sp)
static lldb::ValueObjectSP GetCrashingDereference (lldb::StopInfoSP &stop_info_sp, lldb::addr_t *crashing_address=nullptr)
Private Member Functions
InstrumentationBoundsSafetyStopInfo (Thread &thread)
ComputedStopInfo ComputeStopReasonAndSuggestedStackFrame (bool &warning_emitted_for_failure)
ComputedStopInfo ComputeStopReasonAndSuggestedStackFrameWithDebugInfo (lldb::StackFrameSP parent_sf, lldb::user_id_t debugger_id, bool &warning_emitted_for_failure)
ComputedStopInfo ComputeStopReasonAndSuggestedStackFrameWithoutDebugInfo (ThreadSP thread_sp, lldb::user_id_t debugger_id, bool &warning_emitted_for_failure)
Additional Inherited Members
Protected Member Functions inherited from lldb_private::StopInfo
virtual void PerformAction (Event *event_ptr)
virtual bool ShouldStop (Event *event_ptr)
bool HasTargetRunSinceMe ()
void MakeStopInfoValid ()
Protected Attributes inherited from lldb_private::StopInfo
lldb::ThreadWP m_thread_wp
uint32_t m_stop_id
uint32_t m_resume_id
uint64_t m_value
std::string m_description
LazyBool m_override_should_notify
LazyBool m_override_should_stop
StructuredData::ObjectSP m_extended_info
Detailed Description
Definition at line 56 of file InstrumentationRuntimeBoundsSafety.cpp.
Constructor & Destructor Documentation
~InstrumentationBoundsSafetyStopInfo()
InstrumentationBoundsSafetyStopInfo::~InstrumentationBoundsSafetyStopInfo () override default
InstrumentationBoundsSafetyStopInfo()
InstrumentationBoundsSafetyStopInfo::InstrumentationBoundsSafetyStopInfo (Thread & thread) private
Definition at line 93 of file InstrumentationRuntimeBoundsSafety.cpp.
References ComputeStopReasonAndSuggestedStackFrame(), lldb_private::GetLog(), lldb_private::StopInfo::GetThread(), lldb_private::InstrumentationRuntime, LLDB_LOG, lldb_private::StopInfo::m_description, lldb_private::StopInfo::m_extended_info, lldb_private::StopInfo::m_value, lldb_private::Debugger::ReportWarning(), SOFT_TRAP_FALLBACK_CATEGORY, lldb_private::StopInfo::StopInfo(), and lldb_private::StopInfo::Thread.
Referenced by CreateInstrumentationBoundsSafetyStopInfo().
Member Function Documentation
ComputeStopReasonAndSuggestedStackFrame()
ComputedStopInfo InstrumentationBoundsSafetyStopInfo::ComputeStopReasonAndSuggestedStackFrame (bool & warning_emitted_for_failure) private
Definition at line 145 of file InstrumentationRuntimeBoundsSafety.cpp.
References ComputeStopReasonAndSuggestedStackFrameWithDebugInfo(), ComputeStopReasonAndSuggestedStackFrameWithoutDebugInfo(), lldb_private::GetLog(), lldb_private::StopInfo::GetThread(), lldb_private::InstrumentationRuntime, LLDB_LOG, and LogFailedCSI().
Referenced by InstrumentationBoundsSafetyStopInfo().
ComputeStopReasonAndSuggestedStackFrameWithDebugInfo()
ComputedStopInfo InstrumentationBoundsSafetyStopInfo::ComputeStopReasonAndSuggestedStackFrameWithDebugInfo (lldb::StackFrameSP parent_sf, lldb::user_id_t debugger_id, bool & warning_emitted_for_failure) private
Definition at line 178 of file InstrumentationRuntimeBoundsSafety.cpp.
References LogFailedCSI(), lldb_private::Debugger::ReportWarning(), and SOFT_TRAP_CATEGORY_PREFIX.
Referenced by ComputeStopReasonAndSuggestedStackFrame().
ComputeStopReasonAndSuggestedStackFrameWithoutDebugInfo()
ComputedStopInfo InstrumentationBoundsSafetyStopInfo::ComputeStopReasonAndSuggestedStackFrameWithoutDebugInfo (ThreadSP thread_sp, lldb::user_id_t debugger_id, bool & warning_emitted_for_failure) private
Definition at line 226 of file InstrumentationRuntimeBoundsSafety.cpp.
References BoundsSafetySoftTrapMinimal(), BoundsSafetySoftTrapStr(), lldb_private::ArchSpec::eCore_x86_32_i386, lldb_private::ArchSpec::eCore_x86_32_i486, lldb_private::ArchSpec::eCore_x86_32_i486sx, lldb_private::ArchSpec::eCore_x86_32_i686, lldb::eRegisterKindGeneric, lldb_private::Status::Fail(), lldb_private::RegisterValue::GetAsUInt64(), lldb_private::GetLog(), lldb_private::InstrumentationRuntime, LLDB_LOG, LLDB_REGNUM_GENERIC_ARG1, LogFailedCSI(), lldb_private::RegisterInfo::name, lldb_private::Debugger::ReportWarning(), SOFT_TRAP_FALLBACK_CATEGORY, UINT64_MAX, and warning().
Referenced by ComputeStopReasonAndSuggestedStackFrame().
CreateInstrumentationBoundsSafetyStopInfo()
lldb::StopInfoSP InstrumentationBoundsSafetyStopInfo::CreateInstrumentationBoundsSafetyStopInfo (Thread & thread) inline static
Definition at line 74 of file InstrumentationRuntimeBoundsSafety.cpp.
References InstrumentationBoundsSafetyStopInfo(), and lldb_private::StopInfo::Thread.
DoShouldNotify()
bool InstrumentationBoundsSafetyStopInfo::DoShouldNotify (Event * event_ptr) inline override virtual
Reimplemented from lldb_private::StopInfo.
Definition at line 71 of file InstrumentationRuntimeBoundsSafety.cpp.
GetDescription()
const char * InstrumentationBoundsSafetyStopInfo::GetDescription () inline override virtual
Reimplemented from lldb_private::StopInfo.
Definition at line 69 of file InstrumentationRuntimeBoundsSafety.cpp.
References lldb_private::StopInfo::m_description.
GetStopReason()
lldb::StopReason InstrumentationBoundsSafetyStopInfo::GetStopReason () const inline override virtual
Implements lldb_private::StopInfo.
Definition at line 60 of file InstrumentationRuntimeBoundsSafety.cpp.
References lldb::eStopReasonInstrumentation.
GetSuggestedStackFrameIndex()
std::optional< uint32_t > InstrumentationBoundsSafetyStopInfo::GetSuggestedStackFrameIndex (bool inlined_stack) inline override virtual
This gives the StopInfo a chance to suggest a stack frame to select.
Passing true for inlined_stack will request changes to the inlined call stack. Passing false will request changes to the real stack frame. The inlined stack gets adjusted before we call into the thread plans so they can reason based on the correct values. The real stack adjustment is handled after the frame recognizers get a chance to adjust the frame.
Reimplemented from lldb_private::StopInfo.
Definition at line 65 of file InstrumentationRuntimeBoundsSafety.cpp.
References lldb_private::StopInfo::m_value.
The documentation for this class was generated from the following file:
InstrumentationRuntimeBoundsSafety.cpp