LLDB: lldb::SBScriptObject Class Reference
lldb::SBScriptObject Class Reference
#include <SBScriptObject.h>
Public Member Functions
SBScriptObject (const ScriptObjectPtr ptr, lldb::ScriptLanguage lang)
SBScriptObject (const lldb::SBScriptObject &rhs)
~SBScriptObject ()
const lldb::SBScriptObject & operator= (const lldb::SBScriptObject &rhs)
operator bool () const
bool operator!= (const SBScriptObject &rhs) const
bool IsValid () const
lldb::ScriptObjectPtr GetPointer () const
lldb::ScriptLanguage GetLanguage () const
Protected Member Functions
lldb_private::ScriptObject * get ()
lldb_private::ScriptObject & ref ()
const lldb_private::ScriptObject & ref () const
Private Attributes
std::unique_ptr< lldb_private::ScriptObject > m_opaque_up
Friends
class SBStructuredData
Detailed Description
Definition at line 20 of file SBScriptObject.h.
Constructor & Destructor Documentation
SBScriptObject() [1/2]
SBScriptObject::SBScriptObject (const ScriptObjectPtr ptr, lldb::ScriptLanguage lang)
Definition at line 19 of file SBScriptObject.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by operator!=(), operator=(), SBScriptObject(), and ~SBScriptObject().
SBScriptObject() [2/2]
SBScriptObject::SBScriptObject (const lldb::SBScriptObject & rhs)
Definition at line 25 of file SBScriptObject.cpp.
References lldb_private::clone(), lldb::eScriptLanguageNone, LLDB_INSTRUMENT_VA, m_opaque_up, and SBScriptObject().
~SBScriptObject()
SBScriptObject::~SBScriptObject () default
References GetLanguage(), GetPointer(), IsValid(), operator!=(), operator=(), and SBScriptObject().
Member Function Documentation
get()
ScriptObject * SBScriptObject::get () protected
Definition at line 84 of file SBScriptObject.cpp.
References m_opaque_up.
Referenced by SBStructuredData.
GetLanguage()
lldb::ScriptLanguage SBScriptObject::GetLanguage () const
Definition at line 65 of file SBScriptObject.cpp.
References lldb::eScriptLanguageNone, LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBStructuredData::SBStructuredData(), and ~SBScriptObject().
GetPointer()
lldb::ScriptObjectPtr SBScriptObject::GetPointer () const
Definition at line 59 of file SBScriptObject.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBStructuredData::SetGenericValue(), and ~SBScriptObject().
IsValid()
bool SBScriptObject::IsValid () const
Definition at line 47 of file SBScriptObject.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBStructuredData::SBStructuredData(), and ~SBScriptObject().
operator bool()
SBScriptObject::operator bool () const explicit
Definition at line 53 of file SBScriptObject.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
operator!=()
bool SBScriptObject::operator!= (const SBScriptObject & rhs) const
Definition at line 41 of file SBScriptObject.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and SBScriptObject().
Referenced by ~SBScriptObject().
operator=()
const SBScriptObject & SBScriptObject::operator= (const lldb::SBScriptObject & rhs)
Definition at line 33 of file SBScriptObject.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBScriptObject().
Referenced by ~SBScriptObject().
ref() [1/2]
ScriptObject & SBScriptObject::ref () protected
Definition at line 71 of file SBScriptObject.cpp.
References lldb::eScriptLanguageNone, and m_opaque_up.
Referenced by SBStructuredData, and lldb::SBStructuredData::SBStructuredData().
ref() [2/2]
const ScriptObject & SBScriptObject::ref () const protected
Definition at line 77 of file SBScriptObject.cpp.
References m_opaque_up.
Friends And Related Symbol Documentation
SBStructuredData
friend class SBStructuredData friend
Definition at line 41 of file SBScriptObject.h.
References get(), ref(), and SBStructuredData.
Referenced by SBStructuredData.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::ScriptObject> lldb::SBScriptObject::m_opaque_up private
Definition at line 50 of file SBScriptObject.h.
Referenced by get(), GetLanguage(), GetPointer(), operator bool(), operator!=(), operator=(), ref(), ref(), SBScriptObject(), and SBScriptObject().
The documentation for this class was generated from the following files:
SBScriptObject.h
SBScriptObject.cpp