LLDB: lldb::SBAttachInfo Class Reference
lldb::SBAttachInfo Class Reference
#include <SBAttachInfo.h>
Public Member Functions
SBAttachInfo ()
SBAttachInfo (lldb::pid_t pid)
SBAttachInfo (const char *path, bool wait_for)
Attach to a process by name.
SBAttachInfo (const char *path, bool wait_for, bool async)
Attach to a process by name.
SBAttachInfo (const SBAttachInfo &rhs)
~SBAttachInfo ()
SBAttachInfo & operator= (const SBAttachInfo &rhs)
lldb::pid_t GetProcessID ()
void SetProcessID (lldb::pid_t pid)
void SetExecutable (const char *path)
void SetExecutable (lldb::SBFileSpec exe_file)
bool GetWaitForLaunch ()
void SetWaitForLaunch (bool b)
Set attach by process name settings.
void SetWaitForLaunch (bool b, bool async)
Set attach by process name settings.
bool GetIgnoreExisting ()
void SetIgnoreExisting (bool b)
uint32_t GetResumeCount ()
void SetResumeCount (uint32_t c)
const char * GetProcessPluginName ()
void SetProcessPluginName (const char *plugin_name)
uint32_t GetUserID ()
uint32_t GetGroupID ()
bool UserIDIsValid ()
bool GroupIDIsValid ()
void SetUserID (uint32_t uid)
void SetGroupID (uint32_t gid)
uint32_t GetEffectiveUserID ()
uint32_t GetEffectiveGroupID ()
bool EffectiveUserIDIsValid ()
bool EffectiveGroupIDIsValid ()
void SetEffectiveUserID (uint32_t uid)
void SetEffectiveGroupID (uint32_t gid)
lldb::pid_t GetParentProcessID ()
void SetParentProcessID (lldb::pid_t pid)
bool ParentProcessIDIsValid ()
SBListener GetListener ()
Get the listener that will be used to receive process events.
void SetListener (SBListener &listener)
Set the listener that will be used to receive process events.
SBListener GetShadowListener ()
Get the shadow listener that receive public process events, additionally to the default process event listener.
void SetShadowListener (SBListener &listener)
Set the shadow listener that will receive public process events, additionally to the default process event listener.
const char * GetScriptedProcessClassName () const
void SetScriptedProcessClassName (const char *class_name)
lldb::SBStructuredData GetScriptedProcessDictionary () const
void SetScriptedProcessDictionary (lldb::SBStructuredData dict)
Protected Member Functions
lldb_private::ProcessAttachInfo & ref ()
Protected Attributes
ProcessAttachInfoSP m_opaque_sp
Friends
class SBTarget
class SBPlatform
class lldb_private::ScriptInterpreter
Detailed Description
Definition at line 22 of file SBAttachInfo.h.
Constructor & Destructor Documentation
SBAttachInfo() [1/5]
SBAttachInfo::SBAttachInfo ()
Definition at line 21 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by operator=(), SBAttachInfo(), and ~SBAttachInfo().
SBAttachInfo() [2/5]
SBAttachInfo::SBAttachInfo (lldb::pid_t pid)
Definition at line 25 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
SBAttachInfo() [3/5]
SBAttachInfo::SBAttachInfo (const char * path, bool wait_for)
Attach to a process by name.
This function implies that a future call to SBTarget::Attach(...) will be synchronous.
Parameters
[in] path A full or partial name for the process to attach to.
[in] wait_for If false, attach to an existing process whose name matches. If true, then wait for the next process whose name matches.
Definition at line 32 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
SBAttachInfo() [4/5]
SBAttachInfo::SBAttachInfo (const char * path, bool wait_for, bool async)
Attach to a process by name.
Future calls to SBTarget::Attach(...) will be synchronous or asynchronous depending on the async argument.
Parameters
[in] path A full or partial name for the process to attach to.
[in] wait_for If false, attach to an existing process whose name matches. If true, then wait for the next process whose name matches.
[in] async If false, then the SBTarget::Attach(...) call will be a synchronous call with no way to cancel the attach in progress. If true, then the SBTarget::Attach(...) function will return immediately and clients are expected to wait for a process eStateStopped event if a suitable process is eventually found. If the client wants to cancel the event, SBProcess::Stop() can be called and an eStateExited process event will be delivered.
Definition at line 41 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
SBAttachInfo() [5/5]
SBAttachInfo::SBAttachInfo (const SBAttachInfo & rhs)
Definition at line 51 of file SBAttachInfo.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBAttachInfo().
~SBAttachInfo()
SBAttachInfo::~SBAttachInfo () default
References EffectiveGroupIDIsValid(), EffectiveUserIDIsValid(), GetEffectiveGroupID(), GetEffectiveUserID(), GetGroupID(), GetIgnoreExisting(), GetListener(), GetParentProcessID(), GetProcessID(), GetProcessPluginName(), GetResumeCount(), GetScriptedProcessClassName(), GetScriptedProcessDictionary(), GetShadowListener(), GetUserID(), GetWaitForLaunch(), GroupIDIsValid(), operator=(), ParentProcessIDIsValid(), SBAttachInfo(), SetEffectiveGroupID(), SetEffectiveUserID(), SetExecutable(), SetGroupID(), SetIgnoreExisting(), SetListener(), SetParentProcessID(), SetProcessID(), SetProcessPluginName(), SetResumeCount(), SetScriptedProcessClassName(), SetScriptedProcessDictionary(), SetShadowListener(), SetUserID(), SetWaitForLaunch(), and UserIDIsValid().
Member Function Documentation
EffectiveGroupIDIsValid()
bool SBAttachInfo::EffectiveGroupIDIsValid ()
Definition at line 209 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
EffectiveUserIDIsValid()
bool SBAttachInfo::EffectiveUserIDIsValid ()
Definition at line 203 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
GetEffectiveGroupID()
uint32_t SBAttachInfo::GetEffectiveGroupID ()
Definition at line 197 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
GetEffectiveUserID()
uint32_t SBAttachInfo::GetEffectiveUserID ()
Definition at line 191 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
GetGroupID()
uint32_t SBAttachInfo::GetGroupID ()
Definition at line 161 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
GetIgnoreExisting()
bool SBAttachInfo::GetIgnoreExisting ()
Definition at line 143 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
GetListener()
SBListener SBAttachInfo::GetListener ()
Get the listener that will be used to receive process events.
If no listener has been set via a call to SBAttachInfo::SetListener(), then an invalid SBListener will be returned (SBListener::IsValid() will return false). If a listener has been set, then the valid listener object will be returned.
Definition at line 245 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBListener.
Referenced by ~SBAttachInfo().
GetParentProcessID()
lldb::pid_t SBAttachInfo::GetParentProcessID ()
Definition at line 227 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
GetProcessID()
lldb::pid_t SBAttachInfo::GetProcessID ()
Definition at line 70 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
GetProcessPluginName()
const char * SBAttachInfo::GetProcessPluginName ()
Definition at line 94 of file SBAttachInfo.cpp.
References lldb_private::ConstString::GetCString(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
GetResumeCount()
uint32_t SBAttachInfo::GetResumeCount ()
Definition at line 82 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
GetScriptedProcessClassName()
const char * SBAttachInfo::GetScriptedProcessClassName () const
Definition at line 272 of file SBAttachInfo.cpp.
References lldb_private::ConstString::AsCString(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
GetScriptedProcessDictionary()
lldb::SBStructuredData SBAttachInfo::GetScriptedProcessDictionary () const
Definition at line 300 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, lldb::SBStructuredData::m_impl_up, and m_opaque_sp.
Referenced by ~SBAttachInfo().
GetShadowListener()
SBListener SBAttachInfo::GetShadowListener ()
Get the shadow listener that receive public process events, additionally to the default process event listener.
If no listener has been set via a call to SBLaunchInfo::SetShadowListener(), then an invalid SBListener will be returned (SBListener::IsValid() will return false). If a listener has been set, then the valid listener object will be returned.
Definition at line 257 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBListener.
Referenced by ~SBAttachInfo().
GetUserID()
uint32_t SBAttachInfo::GetUserID ()
Definition at line 155 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
GetWaitForLaunch()
bool SBAttachInfo::GetWaitForLaunch ()
Definition at line 124 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
GroupIDIsValid()
bool SBAttachInfo::GroupIDIsValid ()
Definition at line 173 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
operator=()
SBAttachInfo & SBAttachInfo::operator= (const SBAttachInfo & rhs)
Definition at line 62 of file SBAttachInfo.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBAttachInfo().
Referenced by ~SBAttachInfo().
ParentProcessIDIsValid()
bool SBAttachInfo::ParentProcessIDIsValid ()
Definition at line 239 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
ref()
lldb_private::ProcessAttachInfo & SBAttachInfo::ref () protected
Definition at line 60 of file SBAttachInfo.cpp.
References m_opaque_sp.
Referenced by lldb::SBPlatform::Attach(), lldb::SBTarget::Attach(), and lldb_private::ScriptInterpreter.
SetEffectiveGroupID()
void SBAttachInfo::SetEffectiveGroupID (uint32_t gid)
Definition at line 221 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
SetEffectiveUserID()
void SBAttachInfo::SetEffectiveUserID (uint32_t uid)
Definition at line 215 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
SetExecutable() [1/2]
void SBAttachInfo::SetExecutable (const char * path)
Definition at line 106 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
SetExecutable() [2/2]
void SBAttachInfo::SetExecutable (lldb::SBFileSpec exe_file)
Definition at line 115 of file SBAttachInfo.cpp.
References lldb::SBFileSpec::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBFileSpec::ref().
SetGroupID()
void SBAttachInfo::SetGroupID (uint32_t gid)
Definition at line 185 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
SetIgnoreExisting()
void SBAttachInfo::SetIgnoreExisting (bool b)
Definition at line 149 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
SetListener()
void SBAttachInfo::SetListener (SBListener & listener)
Set the listener that will be used to receive process events.
By default the SBDebugger, which has a listener, that the SBTarget belongs to will listen for the process events. Calling this function allows a different listener to be used to listen for process events.
Definition at line 251 of file SBAttachInfo.cpp.
References lldb::SBListener::GetSP(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
SetParentProcessID()
void SBAttachInfo::SetParentProcessID (lldb::pid_t pid)
Definition at line 233 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
SetProcessID()
void SBAttachInfo::SetProcessID (lldb::pid_t pid)
Definition at line 76 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
SetProcessPluginName()
void SBAttachInfo::SetProcessPluginName (const char * plugin_name)
Definition at line 100 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
SetResumeCount()
void SBAttachInfo::SetResumeCount (uint32_t c)
Definition at line 88 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
SetScriptedProcessClassName()
void SBAttachInfo::SetScriptedProcessClassName (const char * class_name)
Definition at line 286 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
SetScriptedProcessDictionary()
void SBAttachInfo::SetScriptedProcessDictionary (lldb::SBStructuredData dict)
Definition at line 315 of file SBAttachInfo.cpp.
References lldb::eStructuredDataTypeInvalid, lldb::SBStructuredData::IsValid(), LLDB_INSTRUMENT_VA, lldb::SBStructuredData::m_impl_up, and m_opaque_sp.
Referenced by ~SBAttachInfo().
SetShadowListener()
void SBAttachInfo::SetShadowListener (SBListener & listener)
Set the shadow listener that will receive public process events, additionally to the default process event listener.
By default a process have no shadow event listener. Calling this function allows public process events to be broadcasted to an additional listener on top of the default process event listener. If the listener argument is invalid (SBListener::IsValid() will return false), this will clear the shadow listener.
Definition at line 266 of file SBAttachInfo.cpp.
References lldb::SBListener::GetSP(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
SetUserID()
void SBAttachInfo::SetUserID (uint32_t uid)
Definition at line 179 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
SetWaitForLaunch() [1/2]
void SBAttachInfo::SetWaitForLaunch (bool b)
Set attach by process name settings.
Designed to be used after a call to SBAttachInfo::SetExecutable(). This function implies that a call to SBTarget::Attach(...) will be synchronous.
Parameters
[in] b If false, attach to an existing process whose name matches. If true, then wait for the next process whose name matches.
Definition at line 130 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
SetWaitForLaunch() [2/2]
void SBAttachInfo::SetWaitForLaunch (bool b, bool async)
Set attach by process name settings.
Designed to be used after a call to SBAttachInfo::SetExecutable(). Future calls to SBTarget::Attach(...) will be synchronous or asynchronous depending on the async argument.
Parameters
[in] b If false, attach to an existing process whose name matches. If true, then wait for the next process whose name matches.
[in] async If false, then the SBTarget::Attach(...) call will be a synchronous call with no way to cancel the attach in progress. If true, then the SBTarget::Attach(...) function will return immediately and clients are expected to wait for a process eStateStopped event if a suitable process is eventually found. If the client wants to cancel the event, SBProcess::Stop() can be called and an eStateExited process event will be delivered.
Definition at line 136 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
UserIDIsValid()
bool SBAttachInfo::UserIDIsValid ()
Definition at line 167 of file SBAttachInfo.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBAttachInfo().
Friends And Related Symbol Documentation
lldb_private::ScriptInterpreter
friend class lldb_private::ScriptInterpreter friend
Definition at line 202 of file SBAttachInfo.h.
References ref().
SBPlatform
friend class SBPlatform friend
Definition at line 200 of file SBAttachInfo.h.
References SBPlatform.
Referenced by SBPlatform.
SBTarget
friend class SBTarget friend
Definition at line 199 of file SBAttachInfo.h.
References SBTarget.
Referenced by SBTarget.
Member Data Documentation
m_opaque_sp
ProcessAttachInfoSP lldb::SBAttachInfo::m_opaque_sp protected
Definition at line 206 of file SBAttachInfo.h.
Referenced by EffectiveGroupIDIsValid(), EffectiveUserIDIsValid(), GetEffectiveGroupID(), GetEffectiveUserID(), GetGroupID(), GetIgnoreExisting(), GetListener(), lldb_private::ScriptInterpreter::GetOpaqueTypeFromSBAttachInfo(), GetParentProcessID(), GetProcessID(), GetProcessPluginName(), GetResumeCount(), GetScriptedProcessClassName(), GetScriptedProcessDictionary(), GetShadowListener(), GetUserID(), GetWaitForLaunch(), GroupIDIsValid(), operator=(), ParentProcessIDIsValid(), ref(), SBAttachInfo(), SBAttachInfo(), SBAttachInfo(), SBAttachInfo(), SBAttachInfo(), SetEffectiveGroupID(), SetEffectiveUserID(), SetExecutable(), SetExecutable(), SetGroupID(), SetIgnoreExisting(), SetListener(), SetParentProcessID(), SetProcessID(), SetProcessPluginName(), SetResumeCount(), SetScriptedProcessClassName(), SetScriptedProcessDictionary(), SetShadowListener(), SetUserID(), SetWaitForLaunch(), SetWaitForLaunch(), and UserIDIsValid().
The documentation for this class was generated from the following files:
SBAttachInfo.h
SBAttachInfo.cpp