LLDB: lldb_private::formatters::NSDictionaryISyntheticFrontEnd Class Reference
lldb_private::formatters::NSDictionaryISyntheticFrontEnd Class Reference
Classes
struct DataDescriptor_32
struct DataDescriptor_64
struct DictionaryItemDescriptor
Public Member Functions
NSDictionaryISyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
~NSDictionaryISyntheticFrontEnd () override
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Attributes
ExecutionContextRef m_exe_ctx_ref
uint8_t m_ptr_size = 8
lldb::ByteOrder m_order = lldb::eByteOrderInvalid
DataDescriptor_32 * m_data_32 = nullptr
DataDescriptor_64 * m_data_64 = nullptr
lldb::addr_t m_data_ptr = LLDB_INVALID_ADDRESS
CompilerType m_pair_type
std::vector< DictionaryItemDescriptor > m_children
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
Definition at line 101 of file NSDictionary.cpp.
Constructor & Destructor Documentation
NSDictionaryISyntheticFrontEnd()
lldb_private::formatters::NSDictionaryISyntheticFrontEnd::NSDictionaryISyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
Definition at line 577 of file NSDictionary.cpp.
References m_exe_ctx_ref, m_pair_type, and lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd().
~NSDictionaryISyntheticFrontEnd()
lldb_private::formatters::NSDictionaryISyntheticFrontEnd::~NSDictionaryISyntheticFrontEnd () override
Definition at line 581 of file NSDictionary.cpp.
References m_data_32, and m_data_64.
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > lldb_private::formatters::NSDictionaryISyntheticFrontEnd::CalculateNumChildren () override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 603 of file NSDictionary.cpp.
References m_data_32, and m_data_64.
GetChildAtIndex()
lldb::ValueObjectSP lldb_private::formatters::NSDictionaryISyntheticFrontEnd::GetChildAtIndex (uint32_t idx) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 646 of file NSDictionary.cpp.
References lldb_private::SyntheticChildrenFrontEnd::CalculateNumChildrenIgnoringErrors(), lldb_private::SyntheticChildrenFrontEnd::CreateValueObjectFromData(), error(), GetLLDBNSPairType(), lldb_private::StreamString::GetString(), lldb_private::formatters::NSDictionaryISyntheticFrontEnd::DictionaryItemDescriptor::key_ptr, lldb_private::SyntheticChildrenFrontEnd::m_backend, m_children, m_data_ptr, m_exe_ctx_ref, m_order, m_pair_type, m_ptr_size, lldb_private::Stream::Printf(), lldb_private::formatters::NSDictionaryISyntheticFrontEnd::DictionaryItemDescriptor::val_ptr, and lldb_private::formatters::NSDictionaryISyntheticFrontEnd::DictionaryItemDescriptor::valobj_sp.
GetIndexOfChildWithName()
llvm::Expected< size_t > lldb_private::formatters::NSDictionaryISyntheticFrontEnd::GetIndexOfChildWithName (ConstString name) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 589 of file NSDictionary.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::SyntheticChildrenFrontEnd::CalculateNumChildrenIgnoringErrors(), and lldb_private::formatters::ExtractIndexFromString().
Update()
lldb::ChildCacheState lldb_private::formatters::NSDictionaryISyntheticFrontEnd::Update () override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 611 of file NSDictionary.cpp.
References lldb::eRefetch, error(), lldb_private::SyntheticChildrenFrontEnd::m_backend, m_children, m_data_32, m_data_64, m_data_ptr, m_exe_ctx_ref, m_order, and m_ptr_size.
Member Data Documentation
m_children
std::vector<DictionaryItemDescriptor> lldb_private::formatters::NSDictionaryISyntheticFrontEnd::m_children private
Definition at line 139 of file NSDictionary.cpp.
Referenced by GetChildAtIndex(), and Update().
m_data_32
DataDescriptor_32* lldb_private::formatters::NSDictionaryISyntheticFrontEnd::m_data_32 = nullptr private
Definition at line 135 of file NSDictionary.cpp.
Referenced by CalculateNumChildren(), Update(), and ~NSDictionaryISyntheticFrontEnd().
m_data_64
DataDescriptor_64* lldb_private::formatters::NSDictionaryISyntheticFrontEnd::m_data_64 = nullptr private
Definition at line 136 of file NSDictionary.cpp.
Referenced by CalculateNumChildren(), Update(), and ~NSDictionaryISyntheticFrontEnd().
m_data_ptr
lldb::addr_t lldb_private::formatters::NSDictionaryISyntheticFrontEnd::m_data_ptr = LLDB_INVALID_ADDRESS private
Definition at line 137 of file NSDictionary.cpp.
Referenced by GetChildAtIndex(), and Update().
m_exe_ctx_ref
ExecutionContextRef lldb_private::formatters::NSDictionaryISyntheticFrontEnd::m_exe_ctx_ref private
Definition at line 132 of file NSDictionary.cpp.
Referenced by GetChildAtIndex(), NSDictionaryISyntheticFrontEnd(), and Update().
m_order
lldb::ByteOrder lldb_private::formatters::NSDictionaryISyntheticFrontEnd::m_order = lldb::eByteOrderInvalid private
Definition at line 134 of file NSDictionary.cpp.
Referenced by GetChildAtIndex(), and Update().
m_pair_type
CompilerType lldb_private::formatters::NSDictionaryISyntheticFrontEnd::m_pair_type private
Definition at line 138 of file NSDictionary.cpp.
Referenced by GetChildAtIndex(), and NSDictionaryISyntheticFrontEnd().
m_ptr_size
uint8_t lldb_private::formatters::NSDictionaryISyntheticFrontEnd::m_ptr_size = 8 private
Definition at line 133 of file NSDictionary.cpp.
Referenced by GetChildAtIndex(), and Update().
The documentation for this class was generated from the following file:
NSDictionary.cpp