LLDB: lldb_private::ProcessInstanceInfo Class Reference
lldb_private::ProcessInstanceInfo Class Reference
#include <ProcessInfo.h>
Classes
struct timespec
Public Member Functions
ProcessInstanceInfo ()=default
ProcessInstanceInfo (const char *name, const ArchSpec &arch, lldb::pid_t pid)
void Clear ()
uint32_t GetEffectiveUserID () const
uint32_t GetEffectiveGroupID () const
bool EffectiveUserIDIsValid () const
bool EffectiveGroupIDIsValid () const
void SetEffectiveUserID (uint32_t uid)
void SetEffectiveGroupID (uint32_t gid)
lldb::pid_t GetParentProcessID () const
void SetParentProcessID (lldb::pid_t pid)
bool ParentProcessIDIsValid () const
lldb::pid_t GetProcessGroupID () const
void SetProcessGroupID (lldb::pid_t pgrp)
bool ProcessGroupIDIsValid () const
lldb::pid_t GetProcessSessionID () const
void SetProcessSessionID (lldb::pid_t session)
bool ProcessSessionIDIsValid () const
struct timespec GetUserTime () const
void SetUserTime (struct timespec utime)
bool UserTimeIsValid () const
struct timespec GetSystemTime () const
void SetSystemTime (struct timespec stime)
bool SystemTimeIsValid () const
struct timespec GetCumulativeUserTime () const
void SetCumulativeUserTime (struct timespec cutime)
bool CumulativeUserTimeIsValid () const
struct timespec GetCumulativeSystemTime () const
void SetCumulativeSystemTime (struct timespec cstime)
bool CumulativeSystemTimeIsValid () const
std::optional< int8_t > GetPriorityValue () const
void SetPriorityValue (int8_t priority_value)
void SetIsZombie (bool is_zombie)
std::optional< bool > IsZombie () const
void SetIsCoreDumping (bool is_coredumping)
std::optional< bool > IsCoreDumping () const
void Dump (Stream &s, UserIDResolver &resolver) const
void DumpAsTableRow (Stream &s, UserIDResolver &resolver, bool show_args, bool verbose) const
Public Member Functions inherited from lldb_private::ProcessInfo
ProcessInfo ()
ProcessInfo (const char *name, const ArchSpec &arch, lldb::pid_t pid)
void Clear ()
const char * GetName () const
llvm::StringRef GetNameAsStringRef () const
FileSpec & GetExecutableFile ()
void SetExecutableFile (const FileSpec &exe_file, bool add_exe_file_as_first_arg)
const FileSpec & GetExecutableFile () const
uint32_t GetUserID () const
uint32_t GetGroupID () const
bool UserIDIsValid () const
bool GroupIDIsValid () const
void SetUserID (uint32_t uid)
void SetGroupID (uint32_t gid)
ArchSpec & GetArchitecture ()
const ArchSpec & GetArchitecture () const
void SetArchitecture (const ArchSpec &arch)
lldb::pid_t GetProcessID () const
void SetProcessID (lldb::pid_t pid)
bool ProcessIDIsValid () const
void Dump (Stream &s, Platform *platform) const
Args & GetArguments ()
const Args & GetArguments () const
llvm::StringRef GetArg0 () const
void SetArg0 (llvm::StringRef arg)
void SetArguments (const Args &args, bool first_arg_is_executable)
void SetArguments (char const **argv, bool first_arg_is_executable)
Environment & GetEnvironment ()
const Environment & GetEnvironment () const
bool IsScriptedProcess () const
lldb::ScriptedMetadataSP GetScriptedMetadata () const
void SetScriptedMetadata (lldb::ScriptedMetadataSP metadata_sp)
lldb::ListenerSP GetListener () const
void SetListener (const lldb::ListenerSP &listener_sp)
lldb::ListenerSP GetHijackListener () const
void SetHijackListener (const lldb::ListenerSP &listener_sp)
lldb::ListenerSP GetShadowListener () const
void SetShadowListener (const lldb::ListenerSP &listener_sp)
Static Public Member Functions
static void DumpTableHeader (Stream &s, bool show_args, bool verbose)
Protected Attributes
uint32_t m_euid = UINT32_MAX
uint32_t m_egid = UINT32_MAX
lldb::pid_t m_parent_pid = LLDB_INVALID_PROCESS_ID
lldb::pid_t m_process_group_id = LLDB_INVALID_PROCESS_ID
lldb::pid_t m_process_session_id = LLDB_INVALID_PROCESS_ID
struct timespec m_user_time
struct timespec m_system_time
struct timespec m_cumulative_user_time
struct timespec m_cumulative_system_time
std::optional< int8_t > m_priority_value = std::nullopt
std::optional< bool > m_zombie = std::nullopt
std::optional< bool > m_coredumping = std::nullopt
Protected Attributes inherited from lldb_private::ProcessInfo
FileSpec m_executable
std::string m_arg0
Args m_arguments
Environment m_environment
uint32_t m_uid = UINT32_MAX
uint32_t m_gid = UINT32_MAX
ArchSpec m_arch
lldb::pid_t m_pid = LLDB_INVALID_PROCESS_ID
lldb::ScriptedMetadataSP m_scripted_metadata_sp = nullptr
lldb::ListenerSP m_listener_sp = nullptr
lldb::ListenerSP m_hijack_listener_sp = nullptr
lldb::ListenerSP m_shadow_listener_sp = nullptr
Detailed Description
Definition at line 141 of file ProcessInfo.h.
Constructor & Destructor Documentation
ProcessInstanceInfo() [1/2]
lldb_private::ProcessInstanceInfo::ProcessInstanceInfo () default
Referenced by DumpAsTableRow().
ProcessInstanceInfo() [2/2]
lldb_private::ProcessInstanceInfo::ProcessInstanceInfo (const char * name, const ArchSpec & arch, lldb::pid_t pid) inline
Definition at line 150 of file ProcessInfo.h.
References lldb_private::ProcessInfo::ProcessInfo().
Member Function Documentation
Clear()
void lldb_private::ProcessInstanceInfo::Clear () inline
Definition at line 153 of file ProcessInfo.h.
References lldb_private::ProcessInfo::Clear(), LLDB_INVALID_PROCESS_ID, m_egid, m_euid, m_parent_pid, and UINT32_MAX.
Referenced by lldb_private::ProcessAttachInfo::Clear(), GetFreeBSDProcessArgs(), GetProcessAndStatInfo(), GetProcessAndStatInfo(), lldb_private::minidump::ProcessMinidump::GetProcessInfo(), lldb_private::Process::GetProcessInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetProcessInfo(), lldb_private::ProcessTrace::GetProcessInfo(), lldb_private::ScriptedProcess::GetProcessInfo(), and ProcessElfCore::GetProcessInfo().
CumulativeSystemTimeIsValid()
bool lldb_private::ProcessInstanceInfo::CumulativeSystemTimeIsValid () const inline
Definition at line 235 of file ProcessInfo.h.
References m_cumulative_system_time.
CumulativeUserTimeIsValid()
bool lldb_private::ProcessInstanceInfo::CumulativeUserTimeIsValid () const inline
Definition at line 222 of file ProcessInfo.h.
References m_cumulative_user_time.
Dump()
void ProcessInstanceInfo::Dump (Stream & s, UserIDResolver & resolver) const
Definition at line 120 of file ProcessInfo.cpp.
References lldb_private::Stream::AsRawOstream(), EffectiveGroupIDIsValid(), EffectiveUserIDIsValid(), lldb_private::Stream::EOL(), lldb_private::Stream::Format(), GetEffectiveGroupID(), GetEffectiveUserID(), lldb_private::ProcessInfo::GetGroupID(), lldb_private::UserIDResolver::GetGroupName(), GetParentProcessID(), lldb_private::ProcessInfo::GetUserID(), lldb_private::UserIDResolver::GetUserName(), lldb_private::ProcessInfo::GroupIDIsValid(), LLDB_INVALID_PROCESS_ID, lldb_private::ProcessInfo::m_arch, lldb_private::ProcessInfo::m_arguments, lldb_private::ProcessInfo::m_environment, lldb_private::ProcessInfo::m_executable, lldb_private::ProcessInfo::m_pid, ParentProcessIDIsValid(), lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and lldb_private::ProcessInfo::UserIDIsValid().
Referenced by CommandObjectPlatformProcessInfo::DoExecute().
DumpAsTableRow()
void ProcessInstanceInfo::DumpAsTableRow (Stream & s, UserIDResolver & resolver, bool show_args, bool verbose) const
Definition at line 193 of file ProcessInfo.cpp.
References lldb_private::Stream::AsRawOstream(), EffectiveGroupIDIsValid(), EffectiveUserIDIsValid(), lldb_private::Stream::EOL(), lldb_private::Stream::Format(), lldb_private::StreamString::GetData(), GetEffectiveGroupID(), GetEffectiveUserID(), lldb_private::ProcessInfo::GetGroupID(), lldb_private::UserIDResolver::GetGroupName(), lldb_private::ProcessInfo::GetName(), GetParentProcessID(), lldb_private::ProcessInfo::GetUserID(), lldb_private::UserIDResolver::GetUserName(), lldb_private::ProcessInfo::GroupIDIsValid(), LLDB_INVALID_PROCESS_ID, lldb_private::ProcessInfo::m_arch, lldb_private::ProcessInfo::m_arg0, lldb_private::ProcessInfo::m_arguments, lldb_private::ProcessInfo::m_pid, ParentProcessIDIsValid(), lldb_private::Stream::Printf(), ProcessInstanceInfo(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), and lldb_private::ProcessInfo::UserIDIsValid().
Referenced by CommandObjectPlatformProcessList::DoExecute().
DumpTableHeader()
void ProcessInstanceInfo::DumpTableHeader (Stream & s, bool show_args, bool verbose) static
Definition at line 170 of file ProcessInfo.cpp.
References lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
Referenced by lldb_private::Process::Attach(), and CommandObjectPlatformProcessList::DoExecute().
EffectiveGroupIDIsValid()
bool lldb_private::ProcessInstanceInfo::EffectiveGroupIDIsValid () const inline
Definition at line 166 of file ProcessInfo.h.
References m_egid, and UINT32_MAX.
Referenced by Dump(), DumpAsTableRow(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), and ELFLinuxPrPsInfo::Populate().
EffectiveUserIDIsValid()
bool lldb_private::ProcessInstanceInfo::EffectiveUserIDIsValid () const inline
Definition at line 164 of file ProcessInfo.h.
References m_euid, and UINT32_MAX.
Referenced by Dump(), DumpAsTableRow(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), and ELFLinuxPrPsInfo::Populate().
GetCumulativeSystemTime()
struct timespec lldb_private::ProcessInstanceInfo::GetCumulativeSystemTime () const inline
Definition at line 227 of file ProcessInfo.h.
References GetCumulativeSystemTime(), and m_cumulative_system_time.
Referenced by GetCumulativeSystemTime(), and ELFLinuxPrStatus::Populate().
GetCumulativeUserTime()
struct timespec lldb_private::ProcessInstanceInfo::GetCumulativeUserTime () const inline
Definition at line 214 of file ProcessInfo.h.
References GetCumulativeUserTime(), and m_cumulative_user_time.
Referenced by GetCumulativeUserTime(), and ELFLinuxPrStatus::Populate().
GetEffectiveGroupID()
uint32_t lldb_private::ProcessInstanceInfo::GetEffectiveGroupID () const inline
Definition at line 162 of file ProcessInfo.h.
References m_egid.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse_DebugServerStyle(), Dump(), DumpAsTableRow(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), and lldb_private::ProcessInstanceInfoMatch::UserIDsMatch().
GetEffectiveUserID()
uint32_t lldb_private::ProcessInstanceInfo::GetEffectiveUserID () const inline
Definition at line 160 of file ProcessInfo.h.
References m_euid.
Referenced by lldb::SBTarget::Attach(), lldb::SBTarget::AttachToProcessWithID(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse_DebugServerStyle(), Dump(), DumpAsTableRow(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), and lldb_private::ProcessInstanceInfoMatch::UserIDsMatch().
GetParentProcessID()
lldb::pid_t lldb_private::ProcessInstanceInfo::GetParentProcessID () const inline
Definition at line 172 of file ProcessInfo.h.
References m_parent_pid.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse_DebugServerStyle(), Dump(), DumpAsTableRow(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), ELFLinuxPrPsInfo::Populate(), ELFLinuxPrStatus::Populate(), lldb_private::ProcessInstanceInfoMatch::ProcessIDsMatch(), and lldb_private::ProcessAttachInfo::ProcessInfoSpecified().
GetPriorityValue()
std::optional< int8_t > lldb_private::ProcessInstanceInfo::GetPriorityValue () const inline
Definition at line 240 of file ProcessInfo.h.
References m_priority_value.
Referenced by ELFLinuxPrPsInfo::Populate().
GetProcessGroupID()
lldb::pid_t lldb_private::ProcessInstanceInfo::GetProcessGroupID () const inline
Definition at line 180 of file ProcessInfo.h.
References m_process_group_id.
Referenced by ELFLinuxPrPsInfo::Populate(), and ELFLinuxPrStatus::Populate().
GetProcessSessionID()
lldb::pid_t lldb_private::ProcessInstanceInfo::GetProcessSessionID () const inline
Definition at line 188 of file ProcessInfo.h.
References m_process_session_id.
Referenced by ELFLinuxPrPsInfo::Populate(), and ELFLinuxPrStatus::Populate().
GetSystemTime()
struct timespec lldb_private::ProcessInstanceInfo::GetSystemTime () const inline
Definition at line 206 of file ProcessInfo.h.
References GetSystemTime(), and m_system_time.
Referenced by GetSystemTime(), and ELFLinuxPrStatus::Populate().
GetUserTime()
struct timespec lldb_private::ProcessInstanceInfo::GetUserTime () const inline
Definition at line 198 of file ProcessInfo.h.
References GetUserTime(), and m_user_time.
Referenced by GetUserTime(), and ELFLinuxPrStatus::Populate().
IsCoreDumping()
std::optional< bool > lldb_private::ProcessInstanceInfo::IsCoreDumping () const inline
Definition at line 253 of file ProcessInfo.h.
References m_coredumping.
IsZombie()
std::optional< bool > lldb_private::ProcessInstanceInfo::IsZombie () const inline
Definition at line 248 of file ProcessInfo.h.
References m_zombie.
Referenced by ELFLinuxPrPsInfo::Populate().
ParentProcessIDIsValid()
bool lldb_private::ProcessInstanceInfo::ParentProcessIDIsValid () const inline
Definition at line 176 of file ProcessInfo.h.
References LLDB_INVALID_PROCESS_ID, and m_parent_pid.
Referenced by Dump(), DumpAsTableRow(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), and ELFLinuxPrPsInfo::Populate().
ProcessGroupIDIsValid()
bool lldb_private::ProcessInstanceInfo::ProcessGroupIDIsValid () const inline
Definition at line 184 of file ProcessInfo.h.
References LLDB_INVALID_PROCESS_ID, and m_process_group_id.
Referenced by ELFLinuxPrPsInfo::Populate().
ProcessSessionIDIsValid()
bool lldb_private::ProcessInstanceInfo::ProcessSessionIDIsValid () const inline
Definition at line 194 of file ProcessInfo.h.
References LLDB_INVALID_PROCESS_ID, and m_process_session_id.
Referenced by ELFLinuxPrPsInfo::Populate().
SetCumulativeSystemTime()
void lldb_private::ProcessInstanceInfo::SetCumulativeSystemTime (struct timespec cstime) inline
Definition at line 231 of file ProcessInfo.h.
References m_cumulative_system_time.
Referenced by GetStatusInfo().
SetCumulativeUserTime()
void lldb_private::ProcessInstanceInfo::SetCumulativeUserTime (struct timespec cutime) inline
Definition at line 218 of file ProcessInfo.h.
References m_cumulative_user_time.
Referenced by GetStatusInfo().
SetEffectiveGroupID()
void lldb_private::ProcessInstanceInfo::SetEffectiveGroupID (uint32_t gid) inline
Definition at line 170 of file ProcessInfo.h.
References m_egid.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::DecodeProcessInfoResponse(), GetExePathAndIds(), GetFreeBSDProcessUserAndGroup(), GetMacOSXProcessUserAndGroup(), GetNetBSDProcessUserAndGroup(), GetOpenBSDProcessUserAndGroup(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qfProcessInfo().
SetEffectiveUserID()
void lldb_private::ProcessInstanceInfo::SetEffectiveUserID (uint32_t uid) inline
Definition at line 168 of file ProcessInfo.h.
References m_euid.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::DecodeProcessInfoResponse(), GetExePathAndIds(), GetFreeBSDProcessUserAndGroup(), GetMacOSXProcessUserAndGroup(), GetNetBSDProcessUserAndGroup(), GetOpenBSDProcessUserAndGroup(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qfProcessInfo().
SetIsCoreDumping()
void lldb_private::ProcessInstanceInfo::SetIsCoreDumping (bool is_coredumping) inline
Definition at line 252 of file ProcessInfo.h.
References m_coredumping.
SetIsZombie()
void lldb_private::ProcessInstanceInfo::SetIsZombie (bool is_zombie) inline
Definition at line 246 of file ProcessInfo.h.
References m_zombie.
Referenced by GetStatusInfo().
SetParentProcessID()
void lldb_private::ProcessInstanceInfo::SetParentProcessID (lldb::pid_t pid) inline
Definition at line 174 of file ProcessInfo.h.
References m_parent_pid.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::DecodeProcessInfoResponse(), GetExePathAndIds(), GetFreeBSDProcessUserAndGroup(), GetMacOSXProcessUserAndGroup(), GetNetBSDProcessUserAndGroup(), GetOpenBSDProcessUserAndGroup(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qfProcessInfo().
SetPriorityValue()
void lldb_private::ProcessInstanceInfo::SetPriorityValue (int8_t priority_value) inline
Definition at line 242 of file ProcessInfo.h.
References m_priority_value.
SetProcessGroupID()
void lldb_private::ProcessInstanceInfo::SetProcessGroupID (lldb::pid_t pgrp) inline
Definition at line 182 of file ProcessInfo.h.
References m_process_group_id.
Referenced by GetExePathAndIds().
SetProcessSessionID()
void lldb_private::ProcessInstanceInfo::SetProcessSessionID (lldb::pid_t session) inline
Definition at line 190 of file ProcessInfo.h.
References m_process_session_id.
Referenced by GetExePathAndIds().
SetSystemTime()
void lldb_private::ProcessInstanceInfo::SetSystemTime (struct timespec stime) inline
Definition at line 208 of file ProcessInfo.h.
References m_system_time.
Referenced by GetStatusInfo().
SetUserTime()
void lldb_private::ProcessInstanceInfo::SetUserTime (struct timespec utime) inline
Definition at line 200 of file ProcessInfo.h.
References m_user_time.
Referenced by GetStatusInfo().
SystemTimeIsValid()
bool lldb_private::ProcessInstanceInfo::SystemTimeIsValid () const inline
Definition at line 210 of file ProcessInfo.h.
References m_system_time.
UserTimeIsValid()
bool lldb_private::ProcessInstanceInfo::UserTimeIsValid () const inline
Definition at line 202 of file ProcessInfo.h.
References m_user_time.
Member Data Documentation
m_coredumping
std::optional<bool> lldb_private::ProcessInstanceInfo::m_coredumping = std::nullopt protected
Definition at line 274 of file ProcessInfo.h.
Referenced by IsCoreDumping(), and SetIsCoreDumping().
m_cumulative_system_time
struct timespec lldb_private::ProcessInstanceInfo::m_cumulative_system_time protected
Definition at line 271 of file ProcessInfo.h.
Referenced by CumulativeSystemTimeIsValid(), GetCumulativeSystemTime(), and SetCumulativeSystemTime().
m_cumulative_user_time
struct timespec lldb_private::ProcessInstanceInfo::m_cumulative_user_time protected
Definition at line 270 of file ProcessInfo.h.
Referenced by CumulativeUserTimeIsValid(), GetCumulativeUserTime(), and SetCumulativeUserTime().
m_egid
uint32_t lldb_private::ProcessInstanceInfo::m_egid = UINT32_MAX protected
Definition at line 264 of file ProcessInfo.h.
Referenced by Clear(), EffectiveGroupIDIsValid(), GetEffectiveGroupID(), and SetEffectiveGroupID().
m_euid
uint32_t lldb_private::ProcessInstanceInfo::m_euid = UINT32_MAX protected
Definition at line 263 of file ProcessInfo.h.
Referenced by Clear(), EffectiveUserIDIsValid(), GetEffectiveUserID(), and SetEffectiveUserID().
m_parent_pid
lldb::pid_t lldb_private::ProcessInstanceInfo::m_parent_pid = LLDB_INVALID_PROCESS_ID protected
Definition at line 265 of file ProcessInfo.h.
Referenced by Clear(), GetParentProcessID(), ParentProcessIDIsValid(), and SetParentProcessID().
m_priority_value
std::optional<int8_t> lldb_private::ProcessInstanceInfo::m_priority_value = std::nullopt protected
Definition at line 272 of file ProcessInfo.h.
Referenced by GetPriorityValue(), and SetPriorityValue().
m_process_group_id
lldb::pid_t lldb_private::ProcessInstanceInfo::m_process_group_id = LLDB_INVALID_PROCESS_ID protected
Definition at line 266 of file ProcessInfo.h.
Referenced by GetProcessGroupID(), ProcessGroupIDIsValid(), and SetProcessGroupID().
m_process_session_id
lldb::pid_t lldb_private::ProcessInstanceInfo::m_process_session_id = LLDB_INVALID_PROCESS_ID protected
Definition at line 267 of file ProcessInfo.h.
Referenced by GetProcessSessionID(), ProcessSessionIDIsValid(), and SetProcessSessionID().
m_system_time
struct timespec lldb_private::ProcessInstanceInfo::m_system_time protected
Definition at line 269 of file ProcessInfo.h.
Referenced by GetSystemTime(), SetSystemTime(), and SystemTimeIsValid().
m_user_time
struct timespec lldb_private::ProcessInstanceInfo::m_user_time protected
Definition at line 268 of file ProcessInfo.h.
Referenced by GetUserTime(), SetUserTime(), and UserTimeIsValid().
m_zombie
std::optional<bool> lldb_private::ProcessInstanceInfo::m_zombie = std::nullopt protected
Definition at line 273 of file ProcessInfo.h.
Referenced by IsZombie(), and SetIsZombie().
The documentation for this class was generated from the following files:
ProcessInfo.h
ProcessInfo.cpp