LLDB: lldb_private::ProcessInstanceInfoMatch Class Reference
lldb_private::ProcessInstanceInfoMatch Class Reference
#include <ProcessInfo.h>
Public Member Functions
ProcessInstanceInfoMatch ()=default
ProcessInstanceInfoMatch (const char *process_name, NameMatch process_name_match_type)
ProcessInstanceInfo & GetProcessInfo ()
const ProcessInstanceInfo & GetProcessInfo () const
bool GetMatchAllUsers () const
void SetMatchAllUsers (bool b)
NameMatch GetNameMatchType () const
void SetNameMatchType (NameMatch name_match_type)
bool ArchitectureMatches (const ArchSpec &arch_spec) const
Return true iff the architecture in this object matches arch_spec.
bool NameMatches (const char *process_name) const
Return true iff the process name in this object matches process_name.
bool ProcessIDsMatch (const ProcessInstanceInfo &proc_info) const
Return true iff the process ID and parent process IDs in this object match the ones in proc_info.
bool UserIDsMatch (const ProcessInstanceInfo &proc_info) const
Return true iff the (both effective and real) user and group IDs in this object match the ones in proc_info.
bool Matches (const ProcessInstanceInfo &proc_info) const
bool MatchAllProcesses () const
void Clear ()
Protected Attributes
ProcessInstanceInfo m_match_info
NameMatch m_name_match_type = NameMatch::Ignore
bool m_match_all_users = false
Detailed Description
Definition at line 303 of file ProcessInfo.h.
Constructor & Destructor Documentation
ProcessInstanceInfoMatch() [1/2]
lldb_private::ProcessInstanceInfoMatch::ProcessInstanceInfoMatch () default
ProcessInstanceInfoMatch() [2/2]
lldb_private::ProcessInstanceInfoMatch::ProcessInstanceInfoMatch (const char * process_name, NameMatch process_name_match_type) inline
Definition at line 307 of file ProcessInfo.h.
References m_match_all_users, m_match_info, and m_name_match_type.
Member Function Documentation
ArchitectureMatches()
bool ProcessInstanceInfoMatch::ArchitectureMatches (const ArchSpec & arch_spec) const
Return true iff the architecture in this object matches arch_spec.
Definition at line 253 of file ProcessInfo.cpp.
References m_match_info.
Referenced by Matches().
Clear()
void ProcessInstanceInfoMatch::Clear ()
Definition at line 338 of file ProcessInfo.cpp.
References lldb_private::Ignore, m_match_all_users, m_match_info, and m_name_match_type.
GetMatchAllUsers()
bool lldb_private::ProcessInstanceInfoMatch::GetMatchAllUsers () const inline
Definition at line 318 of file ProcessInfo.h.
References m_match_all_users.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), and lldb_private::Host::FindProcessesImpl().
GetNameMatchType()
NameMatch lldb_private::ProcessInstanceInfoMatch::GetNameMatchType () const inline
Definition at line 322 of file ProcessInfo.h.
References m_name_match_type.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), GetFreeBSDProcessArgs(), GetMacOSXProcessArgs(), GetNetBSDProcessArgs(), and GetOpenBSDProcessArgs().
GetProcessInfo() [1/2]
ProcessInstanceInfo & lldb_private::ProcessInstanceInfoMatch::GetProcessInfo () inline
Definition at line 314 of file ProcessInfo.h.
References m_match_info.
Referenced by lldb_private::Process::Attach(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::AttachWaitProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), GetFreeBSDProcessArgs(), GetMacOSXProcessArgs(), GetNetBSDProcessArgs(), GetOpenBSDProcessArgs(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qfProcessInfo().
GetProcessInfo() [2/2]
const ProcessInstanceInfo & lldb_private::ProcessInstanceInfoMatch::GetProcessInfo () const inline
Definition at line 316 of file ProcessInfo.h.
References m_match_info.
MatchAllProcesses()
bool ProcessInstanceInfoMatch::MatchAllProcesses () const
Definition at line 307 of file ProcessInfo.cpp.
References lldb_private::Ignore, m_match_all_users, m_match_info, and m_name_match_type.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), and lldb_private::Platform::GetAllProcesses().
Matches()
bool ProcessInstanceInfoMatch::Matches (const ProcessInstanceInfo & proc_info) const
Definition at line 300 of file ProcessInfo.cpp.
References ArchitectureMatches(), lldb_private::ProcessInfo::GetArchitecture(), lldb_private::ProcessInfo::GetName(), NameMatches(), ProcessIDsMatch(), and UserIDsMatch().
Referenced by lldb_private::Host::FindProcessesImpl().
NameMatches()
bool ProcessInstanceInfoMatch::NameMatches (const char * process_name) const
Return true iff the process name in this object matches process_name.
Definition at line 259 of file ProcessInfo.cpp.
References lldb_private::Ignore, m_match_info, m_name_match_type, and lldb_private::NameMatches().
Referenced by Matches().
ProcessIDsMatch()
bool ProcessInstanceInfoMatch::ProcessIDsMatch (const ProcessInstanceInfo & proc_info) const
Return true iff the process ID and parent process IDs in this object match the ones in proc_info.
Definition at line 269 of file ProcessInfo.cpp.
References lldb_private::ProcessInstanceInfo::GetParentProcessID(), lldb_private::ProcessInfo::GetProcessID(), and m_match_info.
Referenced by Matches().
SetMatchAllUsers()
void lldb_private::ProcessInstanceInfoMatch::SetMatchAllUsers (bool b) inline
Definition at line 320 of file ProcessInfo.h.
References m_match_all_users.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qfProcessInfo().
SetNameMatchType()
void lldb_private::ProcessInstanceInfoMatch::SetNameMatchType (NameMatch name_match_type) inline
Definition at line 324 of file ProcessInfo.h.
References m_name_match_type.
Referenced by lldb_private::Process::Attach(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::AttachWaitProcess(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qfProcessInfo().
UserIDsMatch()
bool ProcessInstanceInfoMatch::UserIDsMatch (const ProcessInstanceInfo & proc_info) const
Return true iff the (both effective and real) user and group IDs in this object match the ones in proc_info.
Definition at line 281 of file ProcessInfo.cpp.
References lldb_private::ProcessInstanceInfo::GetEffectiveGroupID(), lldb_private::ProcessInstanceInfo::GetEffectiveUserID(), lldb_private::ProcessInfo::GetGroupID(), lldb_private::ProcessInfo::GetUserID(), and m_match_info.
Referenced by Matches().
Member Data Documentation
m_match_all_users
bool lldb_private::ProcessInstanceInfoMatch::m_match_all_users = false protected
Definition at line 350 of file ProcessInfo.h.
Referenced by Clear(), GetMatchAllUsers(), MatchAllProcesses(), ProcessInstanceInfoMatch(), and SetMatchAllUsers().
m_match_info
ProcessInstanceInfo lldb_private::ProcessInstanceInfoMatch::m_match_info protected
Definition at line 348 of file ProcessInfo.h.
Referenced by ArchitectureMatches(), Clear(), GetProcessInfo(), GetProcessInfo(), MatchAllProcesses(), NameMatches(), ProcessIDsMatch(), ProcessInstanceInfoMatch(), and UserIDsMatch().
m_name_match_type
NameMatch lldb_private::ProcessInstanceInfoMatch::m_name_match_type = NameMatch::Ignore protected
Definition at line 349 of file ProcessInfo.h.
Referenced by Clear(), GetNameMatchType(), MatchAllProcesses(), NameMatches(), ProcessInstanceInfoMatch(), and SetNameMatchType().
The documentation for this class was generated from the following files:
ProcessInfo.h
ProcessInfo.cpp