LLDB: lldb_private::VariableList Class Reference
lldb_private::VariableList Class Reference
#include <VariableList.h>
Public Types
typedef collection::iterator iterator
typedef collection::const_iterator const_iterator
Public Member Functions
VariableList ()
virtual ~VariableList ()
VariableList (VariableList &&)=default
VariableList & operator= (VariableList &&)=default
void AddVariable (const lldb::VariableSP &var_sp)
bool AddVariableIfUnique (const lldb::VariableSP &var_sp)
void AddVariables (VariableList *variable_list)
void Clear ()
void Dump (Stream *s, bool show_context) const
lldb::VariableSP GetVariableAtIndex (size_t idx) const
lldb::VariableSP RemoveVariableAtIndex (size_t idx)
lldb::VariableSP FindVariable (ConstString name, bool include_static_members=true)
lldb::VariableSP FindVariable (ConstString name, lldb::ValueType value_type, bool include_static_members=true)
uint32_t FindVariableIndex (const lldb::VariableSP &var_sp)
size_t AppendVariablesIfUnique (VariableList &var_list)
size_t AppendVariablesIfUnique (const RegularExpression &regex, VariableList &var_list, size_t &total_matches)
size_t AppendVariablesWithScope (lldb::ValueType type, VariableList &var_list, bool if_unique=true)
uint32_t FindIndexForVariable (Variable *variable)
size_t MemorySize () const
size_t GetSize () const
bool Empty () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
llvm::ArrayRef< lldb::VariableSP > toArrayRef ()
Protected Attributes
collection m_variables
Private Types
typedef std::vector< lldb::VariableSP > collection
Private Member Functions
VariableList (const VariableList &)=delete
const VariableList & operator= (const VariableList &)=delete
Detailed Description
Definition at line 18 of file VariableList.h.
Member Typedef Documentation
collection
typedef std::vector<lldb::VariableSP> lldb_private::VariableList::collection private
Definition at line 19 of file VariableList.h.
const_iterator
typedef collection::const_iterator lldb_private::VariableList::const_iterator
Definition at line 74 of file VariableList.h.
iterator
typedef collection::iterator lldb_private::VariableList::iterator
Definition at line 73 of file VariableList.h.
Constructor & Destructor Documentation
VariableList() [1/3]
VariableList::VariableList ()
Definition at line 20 of file VariableList.cpp.
References m_variables.
Referenced by AddVariables(), AppendVariablesIfUnique(), AppendVariablesIfUnique(), AppendVariablesWithScope(), MemorySize(), operator=(), operator=(), VariableList(), and VariableList().
~VariableList()
VariableList::~VariableList () virtual default
VariableList() [2/3]
lldb_private::VariableList::VariableList (VariableList &&) default
References VariableList().
VariableList() [3/3]
lldb_private::VariableList::VariableList (const VariableList &) private delete
References VariableList().
Member Function Documentation
AddVariable()
void VariableList::AddVariable (const lldb::VariableSP & var_sp)
Definition at line 25 of file VariableList.cpp.
References m_variables.
Referenced by lldb_private::Block::AppendBlockVariables(), lldb_private::Block::AppendVariables(), AppendVariablesWithScope(), lldb_private::npdb::SymbolFileNativePDB::FindGlobalVariables(), lldb_private::SymbolFileCTF::FindGlobalVariables(), lldb_private::SymbolFileCTF::FindGlobalVariables(), and lldb_private::npdb::SymbolFileNativePDB::ParseVariablesForCompileUnit().
AddVariableIfUnique()
bool VariableList::AddVariableIfUnique (const lldb::VariableSP & var_sp)
Definition at line 29 of file VariableList.cpp.
References FindVariableIndex(), m_variables, and UINT32_MAX.
Referenced by AppendVariablesIfUnique(), AppendVariablesIfUnique(), AppendVariablesWithScope(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseAndAppendGlobalVariable(), SymbolFilePDB::ParseVariables(), and lldb_private::plugin::dwarf::SymbolFileDWARF::PopulateBlockVariableList().
AddVariables()
void VariableList::AddVariables (VariableList * variable_list)
Definition at line 37 of file VariableList.cpp.
References m_variables, and VariableList().
AppendVariablesIfUnique() [1/2]
size_t VariableList::AppendVariablesIfUnique (const RegularExpression & regex, VariableList & var_list, size_t & total_matches)
Definition at line 111 of file VariableList.cpp.
References AddVariableIfUnique(), end(), GetSize(), m_variables, and VariableList().
AppendVariablesIfUnique() [2/2]
size_t VariableList::AppendVariablesIfUnique (VariableList & var_list)
Definition at line 103 of file VariableList.cpp.
References AddVariableIfUnique(), end(), GetSize(), m_variables, and VariableList().
Referenced by lldb::SBFrame::FindValue().
AppendVariablesWithScope()
size_t VariableList::AppendVariablesWithScope (lldb::ValueType type, VariableList & var_list, bool if_unique = true)
Definition at line 128 of file VariableList.cpp.
References AddVariable(), AddVariableIfUnique(), end(), GetSize(), m_variables, and VariableList().
Referenced by lldb_private::CPlusPlusLanguage::HandleFrameFormatVariable(), PrintFunctionNameWithArgs(), and PrintFunctionNameWithArgs().
begin() [1/2]
iterator lldb_private::VariableList::begin () inline
Definition at line 76 of file VariableList.h.
References m_variables.
Referenced by FindIndexForVariable().
begin() [2/2]
const_iterator lldb_private::VariableList::begin () const inline
Definition at line 78 of file VariableList.h.
References m_variables.
Clear()
void VariableList::Clear ()
Definition at line 45 of file VariableList.cpp.
References m_variables.
Referenced by lldb_private::Variable::GetValuesForVariableExpressionPath().
Dump()
void VariableList::Dump (Stream * s, bool show_context) const
Definition at line 167 of file VariableList.cpp.
References end(), and m_variables.
Empty()
bool lldb_private::VariableList::Empty () const inline
Definition at line 71 of file VariableList.h.
References m_variables.
Referenced by CommandObjectTargetVariable::DumpGlobalVariableList(), lldb::SBTarget::FindGlobalVariables(), lldb::SBTarget::FindGlobalVariables(), and lldb_private::dil::LookupGlobalIdentifier().
end() [1/2]
iterator lldb_private::VariableList::end () inline
Definition at line 77 of file VariableList.h.
References m_variables.
Referenced by AppendVariablesIfUnique(), AppendVariablesIfUnique(), AppendVariablesWithScope(), Dump(), FindIndexForVariable(), FindVariable(), FindVariable(), FindVariableIndex(), and MemorySize().
end() [2/2]
const_iterator lldb_private::VariableList::end () const inline
Definition at line 79 of file VariableList.h.
References m_variables.
FindIndexForVariable()
uint32_t VariableList::FindIndexForVariable (Variable * variable)
Definition at line 145 of file VariableList.cpp.
References begin(), end(), m_variables, and UINT32_MAX.
Referenced by lldb_private::StackFrame::GetValueObjectForFrameVariable().
FindVariable() [1/2]
VariableSP VariableList::FindVariable (ConstString name, bool include_static_members = true)
Definition at line 72 of file VariableList.cpp.
References end(), and m_variables.
Referenced by lldb::SBFrame::FindValue(), lldb_private::StackFrame::FindVariable(), lldb_private::StackFrame::LegacyGetValueForVariableExpressionPath(), lldb_private::ClangExpressionDeclMap::LookUpLldbClass(), and lldb_private::ClangExpressionDeclMap::LookUpLldbObjCClass().
FindVariable() [2/2]
VariableSP VariableList::FindVariable (ConstString name, lldb::ValueType value_type, bool include_static_members = true)
Definition at line 87 of file VariableList.cpp.
References end(), and m_variables.
FindVariableIndex()
uint32_t VariableList::FindVariableIndex (const lldb::VariableSP & var_sp)
Definition at line 63 of file VariableList.cpp.
References end(), m_variables, and UINT32_MAX.
Referenced by AddVariableIfUnique().
GetSize()
size_t VariableList::GetSize () const
Definition at line 165 of file VariableList.cpp.
References m_variables.
Referenced by lldb_private::VariableAnnotator::AnnotateStructured(), AppendVariablesIfUnique(), AppendVariablesIfUnique(), AppendVariablesWithScope(), CommandObjectTargetVariable::DoExecute(), FetchVariablesUnlessInterrupted(), lldb_private::ClangExpressionDeclMap::FindGlobalVariable(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindGlobalVariables(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindGlobalVariables(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FindGlobalVariables(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FindGlobalVariables(), SymbolFilePDB::FindGlobalVariables(), SymbolFilePDB::FindGlobalVariables(), GetSymbolDeclarationFromAddress(), lldb_private::StackFrame::GetValueObjectForFrameVariable(), lldb_private::Variable::GetValuesForVariableExpressionPath(), CommandObjectTargetVariable::GetVariableCallback(), lldb_private::npdb::SymbolFileNativePDB::ParseVariablesForCompileUnit(), lldb_private::FormatEntity::PrettyPrintFunctionArguments(), PrintFunctionNameWithArgs(), PrintFunctionNameWithArgs(), and lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::PrivateFindGlobalVariables().
GetVariableAtIndex()
VariableSP VariableList::GetVariableAtIndex (size_t idx) const
Definition at line 47 of file VariableList.cpp.
References m_variables.
Referenced by lldb_private::VariableAnnotator::AnnotateStructured(), CommandObjectTargetVariable::DoExecute(), lldb_private::ClangExpressionDeclMap::FindGlobalVariable(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindGlobalVariables(), lldb::SBFunction::GetArgumentName(), GetSymbolDeclarationFromAddress(), lldb_private::Variable::GetValuesForVariableExpressionPath(), and lldb_private::FormatEntity::PrettyPrintFunctionArguments().
MemorySize()
size_t VariableList::MemorySize () const
Definition at line 157 of file VariableList.cpp.
References end(), m_variables, and VariableList().
operator=() [1/2]
const VariableList & lldb_private::VariableList::operator= (const VariableList &) private delete
References VariableList().
operator=() [2/2]
VariableList & lldb_private::VariableList::operator= (VariableList &&) default
References VariableList().
RemoveVariableAtIndex()
VariableSP VariableList::RemoveVariableAtIndex (size_t idx)
Definition at line 54 of file VariableList.cpp.
References m_variables.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::FindGlobalVariables(), and lldb_private::Variable::GetValuesForVariableExpressionPath().
toArrayRef()
llvm::ArrayRef< lldb::VariableSP > lldb_private::VariableList::toArrayRef () inline
Definition at line 81 of file VariableList.h.
References m_variables.
Member Data Documentation
m_variables
collection lldb_private::VariableList::m_variables protected
Definition at line 86 of file VariableList.h.
Referenced by AddVariable(), AddVariableIfUnique(), AddVariables(), AppendVariablesIfUnique(), AppendVariablesIfUnique(), AppendVariablesWithScope(), begin(), begin(), Clear(), Dump(), Empty(), end(), end(), FindIndexForVariable(), FindVariable(), FindVariable(), FindVariableIndex(), GetSize(), GetVariableAtIndex(), MemorySize(), RemoveVariableAtIndex(), toArrayRef(), and VariableList().
The documentation for this class was generated from the following files:
VariableList.h
VariableList.cpp