LLDB: CommandObjectBreakpointAddName::CommandOptions Class Reference
CommandObjectBreakpointAddName::CommandOptions Class Reference
Public Member Functions
CommandOptions ()=default
~CommandOptions () override=default
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext *execution_context) override
void OptionParsingStarting (ExecutionContext *execution_context) override
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Public Attributes
bool m_hardware = false
LazyBool m_skip_prologue = eLazyBoolCalculate
FileSpecList m_modules
LanguageType m_language = eLanguageTypeUnknown
FileSpecList m_files
LazyBool m_move_to_nearest_code = eLazyBoolCalculate
lldb::addr_t m_offset_addr = 0
NameMatchStyle m_lookup_style = eNameMatchStyleAuto
Detailed Description
Definition at line 981 of file CommandObjectBreakpoint.cpp.
Constructor & Destructor Documentation
CommandOptions()
CommandObjectBreakpointAddName::CommandOptions::CommandOptions () default
~CommandOptions()
CommandObjectBreakpointAddName::CommandOptions::~CommandOptions () override default
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > CommandObjectBreakpointAddName::CommandOptions::GetDefinitions () inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 1058 of file CommandObjectBreakpoint.cpp.
Referenced by SetOptionValue().
OptionParsingStarting()
void CommandObjectBreakpointAddName::CommandOptions::OptionParsingStarting (ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 1048 of file CommandObjectBreakpoint.cpp.
References lldb::eLanguageTypeUnknown, lldb_private::eLazyBoolCalculate, lldb::eNameMatchStyleAuto, m_files, m_hardware, m_language, m_lookup_style, m_modules, m_offset_addr, and m_skip_prologue.
SetOptionValue()
Status CommandObjectBreakpointAddName::CommandOptions::SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 987 of file CommandObjectBreakpoint.cpp.
References lldb_private::CreateOptionParsingError(), lldb::eLanguageTypeUnknown, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb::eNameMatchStyleAuto, error(), lldb_private::Status::FromError(), lldb_private::g_bool_parsing_error_message, lldb_private::g_language_parsing_error_message, GetDefinitions(), lldb_private::Language::GetLanguageTypeFromString(), m_files, m_hardware, m_language, m_lookup_style, m_modules, m_offset_addr, m_skip_prologue, lldb_private::OptionArgParser::ToAddress(), lldb_private::OptionArgParser::ToBoolean(), and lldb_private::OptionArgParser::ToOptionEnum().
Member Data Documentation
m_files
FileSpecList CommandObjectBreakpointAddName::CommandOptions::m_files
Definition at line 1067 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_hardware
bool CommandObjectBreakpointAddName::CommandOptions::m_hardware = false
Definition at line 1063 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_language
LanguageType CommandObjectBreakpointAddName::CommandOptions::m_language = eLanguageTypeUnknown
Definition at line 1066 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_lookup_style
NameMatchStyle CommandObjectBreakpointAddName::CommandOptions::m_lookup_style = eNameMatchStyleAuto
Definition at line 1070 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_modules
FileSpecList CommandObjectBreakpointAddName::CommandOptions::m_modules
Definition at line 1065 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_move_to_nearest_code
LazyBool CommandObjectBreakpointAddName::CommandOptions::m_move_to_nearest_code = eLazyBoolCalculate
Definition at line 1068 of file CommandObjectBreakpoint.cpp.
m_offset_addr
lldb::addr_t CommandObjectBreakpointAddName::CommandOptions::m_offset_addr = 0
Definition at line 1069 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_skip_prologue
LazyBool CommandObjectBreakpointAddName::CommandOptions::m_skip_prologue = eLazyBoolCalculate
Definition at line 1064 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following file:
CommandObjectBreakpoint.cpp