LLDB: lldb_private::HostProcessWindows Class Reference
lldb_private::HostProcessWindows Class Reference
#include <HostProcessWindows.h>
Public Member Functions
HostProcessWindows ()
HostProcessWindows (lldb::process_t process)
~HostProcessWindows ()
void SetOwnsHandle (bool owns)
Status Terminate () override
lldb::pid_t GetProcessId () const override
bool IsRunning () const override
virtual llvm::Expected< HostThread > StartMonitoring (const Host::MonitorChildProcessCallback &callback) override
Public Member Functions inherited from lldb_private::HostNativeProcessBase
HostNativeProcessBase ()
HostNativeProcessBase (lldb::process_t process)
virtual ~HostNativeProcessBase ()=default
lldb::process_t GetSystemHandle () const
Private Member Functions
void Close ()
Private Attributes
bool m_owns_handle
Additional Inherited Members
Protected Attributes inherited from lldb_private::HostNativeProcessBase
lldb::process_t m_process
Detailed Description
Definition at line 19 of file HostProcessWindows.h.
Constructor & Destructor Documentation
HostProcessWindows() [1/2]
HostProcessWindows::HostProcessWindows ()
Definition at line 30 of file HostProcessWindows.cpp.
References lldb_private::HostNativeProcessBase::HostNativeProcessBase(), and m_owns_handle.
HostProcessWindows() [2/2]
HostProcessWindows::HostProcessWindows (lldb::process_t process) explicit
Definition at line 33 of file HostProcessWindows.cpp.
References lldb_private::HostNativeProcessBase::HostNativeProcessBase(), and m_owns_handle.
~HostProcessWindows()
HostProcessWindows::~HostProcessWindows ()
Definition at line 36 of file HostProcessWindows.cpp.
References Close().
Member Function Documentation
Close()
void HostProcessWindows::Close () private
Definition at line 96 of file HostProcessWindows.cpp.
References LLDB_INVALID_PROCESS, m_owns_handle, and lldb_private::HostNativeProcessBase::m_process.
Referenced by ~HostProcessWindows().
GetProcessId()
lldb::pid_t HostProcessWindows::GetProcessId () const override virtual
Implements lldb_private::HostNativeProcessBase.
Definition at line 51 of file HostProcessWindows.cpp.
References GetProcessId(), LLDB_INVALID_PROCESS, and lldb_private::HostNativeProcessBase::m_process.
Referenced by GetProcessId().
IsRunning()
bool HostProcessWindows::IsRunning () const override virtual
Implements lldb_private::HostNativeProcessBase.
Definition at line 55 of file HostProcessWindows.cpp.
References lldb_private::HostNativeProcessBase::m_process.
SetOwnsHandle()
void HostProcessWindows::SetOwnsHandle (bool owns)
Definition at line 38 of file HostProcessWindows.cpp.
References m_owns_handle.
StartMonitoring()
llvm::Expected< HostThread > HostProcessWindows::StartMonitoring (const Host::MonitorChildProcessCallback & callback) override virtual
Implements lldb_private::HostNativeProcessBase.
Definition at line 78 of file HostProcessWindows.cpp.
References lldb_private::ThreadLauncher::LaunchThread(), lldb_private::HostNativeProcessBase::m_process, and MonitorThread().
Terminate()
Status HostProcessWindows::Terminate () override virtual
Implements lldb_private::HostNativeProcessBase.
Definition at line 40 of file HostProcessWindows.cpp.
References lldb::eErrorTypeWin32, error(), lldb_private::HostNativeProcessBase::m_process, and lldb_private::Status.
Member Data Documentation
m_owns_handle
bool lldb_private::HostProcessWindows::m_owns_handle private
Definition at line 38 of file HostProcessWindows.h.
Referenced by Close(), HostProcessWindows(), HostProcessWindows(), and SetOwnsHandle().
The documentation for this class was generated from the following files:
HostProcessWindows.h
HostProcessWindows.cpp