LLDB: lldb_private::FunctionInfo Class Reference
lldb_private::FunctionInfo Class Reference
A class that contains generic function information.
#include "lldb/Symbol/Function.h"
Public Member Functions
FunctionInfo (const char *name, const Declaration *decl_ptr)
Construct with the function method name and optional declaration information.
FunctionInfo (ConstString name, const Declaration *decl_ptr)
Construct with the function method name and optional declaration information.
virtual ~FunctionInfo ()
Destructor.
void Dump (Stream *s, bool show_fullpaths) const
Dump a description of this object to a Stream.
Declaration & GetDeclaration ()
Get accessor for the declaration information.
const Declaration & GetDeclaration () const
Get const accessor for the declaration information.
ConstString GetName () const
Get accessor for the method name.
virtual size_t MemorySize () const
Get the memory cost of this object.
Static Public Member Functions
static int Compare (const FunctionInfo &lhs, const FunctionInfo &rhs)
Compare two function information objects.
Protected Attributes
ConstString m_name
Function method name (not a mangled name).
Declaration m_declaration
Information describing where this function information was defined.
Detailed Description
A class that contains generic function information.
This provides generic function information that gets reused between inline functions and function types.
Definition at line 32 of file Function.h.
Constructor & Destructor Documentation
FunctionInfo() [1/2]
FunctionInfo::FunctionInfo (const char * name, const Declaration * decl_ptr)
Construct with the function method name and optional declaration information.
Parameters
[in] name A C string name for the method name for this function. This value should not be the mangled named, but the simple method name.
[in] decl_ptr Optional declaration information that describes where the function was declared. This can be NULL.
Definition at line 32 of file Function.cpp.
References m_declaration, and m_name.
Referenced by Compare(), lldb_private::InlineFunctionInfo::InlineFunctionInfo(), lldb_private::InlineFunctionInfo::InlineFunctionInfo(), and ~FunctionInfo().
FunctionInfo() [2/2]
FunctionInfo::FunctionInfo (ConstString name, const Declaration * decl_ptr)
Construct with the function method name and optional declaration information.
Parameters
[in] name A name for the method name for this function. This value should not be the mangled named, but the simple method name.
[in] decl_ptr Optional declaration information that describes where the function was declared. This can be NULL.
Definition at line 35 of file Function.cpp.
References m_declaration, and m_name.
~FunctionInfo()
FunctionInfo::~FunctionInfo () virtual default
Destructor.
The destructor is virtual since classes inherit from this class.
References FunctionInfo().
Member Function Documentation
Compare()
int FunctionInfo::Compare (const FunctionInfo & lhs, const FunctionInfo & rhs) static
Compare two function information objects.
First compares the method names, and if equal, then compares the declaration information.
Parameters
[in] lhs The Left Hand Side const FunctionInfo object reference.
[in] rhs The Right Hand Side const FunctionInfo object reference.
Returns
-1 if lhs < rhs 0 if lhs == rhs 1 if lhs > rhs
Definition at line 46 of file Function.cpp.
References lldb_private::ConstString::Compare(), lldb_private::Declaration::Compare(), FunctionInfo(), GetName(), and m_declaration.
Dump()
void FunctionInfo::Dump (Stream * s, bool show_fullpaths) const
Dump a description of this object to a Stream.
Dump a description of the contents of this object to the supplied stream s.
Parameters
[in] s The stream to which to dump the object description.
Definition at line 40 of file Function.cpp.
References m_declaration, and m_name.
Referenced by lldb_private::InlineFunctionInfo::Dump().
GetDeclaration() [1/2]
Declaration & FunctionInfo::GetDeclaration ()
Get accessor for the declaration information.
Returns
A reference to the declaration object.
Definition at line 54 of file Function.cpp.
References m_declaration.
Referenced by lldb_private::BreakpointResolverFileLine::FilterContexts(), lldb_private::BreakpointLocation::GetSuggestedStackFrameIndex(), and lldb_private::SymbolContextSpecifier::SymbolContextMatches().
GetDeclaration() [2/2]
const Declaration & FunctionInfo::GetDeclaration () const
Get const accessor for the declaration information.
Returns
A const reference to the declaration object.
Definition at line 56 of file Function.cpp.
References m_declaration.
GetName()
ConstString FunctionInfo::GetName () const
Get accessor for the method name.
Returns
A const reference to the method name object.
Definition at line 60 of file Function.cpp.
References m_name.
Referenced by Compare().
MemorySize()
size_t FunctionInfo::MemorySize () const virtual
Get the memory cost of this object.
Returns
The number of bytes that this object occupies in memory. The returned value does not include the bytes for any shared string values.
Reimplemented in lldb_private::InlineFunctionInfo.
Definition at line 62 of file Function.cpp.
References m_declaration, and m_name.
Referenced by lldb_private::InlineFunctionInfo::MemorySize().
Member Data Documentation
m_declaration
Declaration lldb_private::FunctionInfo::m_declaration protected
Information describing where this function information was defined.
Definition at line 121 of file Function.h.
Referenced by Compare(), Dump(), FunctionInfo(), FunctionInfo(), GetDeclaration(), GetDeclaration(), and MemorySize().
m_name
ConstString lldb_private::FunctionInfo::m_name protected
Function method name (not a mangled name).
Definition at line 118 of file Function.h.
Referenced by Dump(), lldb_private::InlineFunctionInfo::DumpStopContext(), FunctionInfo(), FunctionInfo(), lldb_private::InlineFunctionInfo::GetDisplayName(), GetName(), lldb_private::InlineFunctionInfo::GetName(), and MemorySize().
The documentation for this class was generated from the following files:
Function.h
Function.cpp