LLDB: lldb_private::DynamicLoaderWindowsDYLD Class Reference
lldb_private::DynamicLoaderWindowsDYLD Class Reference
#include <DynamicLoaderWindowsDYLD.h>
Public Member Functions
DynamicLoaderWindowsDYLD (Process *process)
~DynamicLoaderWindowsDYLD () override
void OnLoadModule (lldb::ModuleSP module_sp, const ModuleSpec module_spec, lldb::addr_t module_addr)
void OnUnloadModule (lldb::addr_t module_addr)
void DidAttach () override
Called after attaching a process.
void DidLaunch () override
Called after launching a process.
Status CanLoadImage () override
Ask if it is ok to try and load or unload an shared library (image).
lldb::ThreadPlanSP GetStepThroughTrampolinePlan (Thread &thread, bool stop) override
Provides a plan to step through the dynamic loader trampoline for the current state of thread.
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::DynamicLoader
DynamicLoader (Process *process)
Construct with a process.
virtual bool ProcessDidExec ()
Helper function that can be used to detect when a process has called exec and is now a new and different process.
bool GetStopWhenImagesChange () const
Get whether the process should stop when images change.
void SetStopWhenImagesChange (bool stop)
Set whether the process should stop when images change.
virtual void FindEquivalentSymbols (const Symbol *original_symbol, ModuleList &module_list, SymbolContextList &equivalent_symbols)
Some dynamic loaders provide features where there are a group of symbols "equivalent to" a given symbol one of which will be chosen when the symbol is bound.
virtual bool AlwaysRelyOnEHUnwindInfo (SymbolContext &sym_ctx)
Ask if the eh_frame information for the given SymbolContext should be relied on even when it's the first frame in a stack unwind.
virtual lldb::addr_t GetThreadLocalData (const lldb::ModuleSP module, const lldb::ThreadSP thread, lldb::addr_t tls_file_addr)
Retrieves the per-module TLS block for a given thread.
virtual lldb::ModuleSP LoadModuleAtAddress (const lldb_private::FileSpec &file, lldb::addr_t link_map_addr, lldb::addr_t base_addr, bool base_addr_is_offset)
Locates or creates a module given by file and updates/loads the resulting module at the virtual base address base_addr.
virtual bool GetSharedCacheInformation (lldb::addr_t &base_address, UUID &uuid, LazyBool &using_shared_cache, LazyBool &private_shared_cache, lldb_private::FileSpec &shared_cache_path)
Get information about the shared cache for a process, if possible.
virtual bool IsFullyInitialized ()
Return whether the dynamic loader is fully initialized and it's safe to call its APIs.
virtual std::optional< lldb_private::Address > GetStartAddress ()
Return the start address in the dynamic loader module.
virtual void CalculateDynamicSaveCoreRanges (lldb_private::Process &process, std::vector< lldb_private::MemoryRegionInfo > &ranges, llvm::function_ref< bool(const lldb_private::Thread &)> save_thread_predicate)
Returns a list of memory ranges that should be saved in the core file, specific for this dynamic loader.
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static DynamicLoader * CreateInstance (Process *process, bool force)
Static Public Member Functions inherited from lldb_private::DynamicLoader
static DynamicLoader * FindPlugin (Process *process, llvm::StringRef plugin_name)
Find a dynamic loader plugin for a given process.
static lldb::ModuleSP LoadBinaryWithUUIDAndAddress (Process *process, llvm::StringRef name, UUID uuid, lldb::addr_t value, bool value_is_offset, bool force_symbol_search, bool notify, bool set_address_in_target, bool allow_memory_image_last_resort)
Find/load a binary into lldb given a UUID and the address where it is loaded in memory, or a slide to be applied to the file address.
Protected Member Functions
lldb::addr_t GetLoadAddress (lldb::ModuleSP executable)
Protected Member Functions inherited from lldb_private::DynamicLoader
lldb::ModuleSP FindModuleViaTarget (const FileSpec &file)
Find a module in the target that matches the given file.
lldb::ModuleSP GetTargetExecutable ()
Checks to see if the target module has changed, updates the target accordingly and returns the target executable module.
virtual void UpdateLoadedSections (lldb::ModuleSP module, lldb::addr_t link_map_addr, lldb::addr_t base_addr, bool base_addr_is_offset)
Updates the load address of every allocatable section in module.
void UpdateLoadedSectionsCommon (lldb::ModuleSP module, lldb::addr_t base_addr, bool base_addr_is_offset)
virtual void UnloadSections (const lldb::ModuleSP module)
Removes the loaded sections from the target in module.
void UnloadSectionsCommon (const lldb::ModuleSP module)
const lldb_private::SectionList * GetSectionListFromModule (const lldb::ModuleSP module) const
int64_t ReadUnsignedIntWithSizeInBytes (lldb::addr_t addr, int size_in_bytes)
lldb::addr_t ReadPointer (lldb::addr_t addr)
void LoadOperatingSystemPlugin (bool flush)
Private Attributes
std::map< lldb::ModuleWP, lldb::addr_t, std::owner_less< lldb::ModuleWP > > m_loaded_modules
Additional Inherited Members
Protected Attributes inherited from lldb_private::DynamicLoader
Process * m_process
The process that this dynamic loader plug-in is tracking.
Detailed Description
Definition at line 19 of file DynamicLoaderWindowsDYLD.h.
Constructor & Destructor Documentation
DynamicLoaderWindowsDYLD()
DynamicLoaderWindowsDYLD::DynamicLoaderWindowsDYLD (Process * process)
Definition at line 29 of file DynamicLoaderWindowsDYLD.cpp.
References lldb_private::DynamicLoader::DynamicLoader(), and DynamicLoaderWindowsDYLD().
Referenced by CreateInstance(), and DynamicLoaderWindowsDYLD().
~DynamicLoaderWindowsDYLD()
DynamicLoaderWindowsDYLD::~DynamicLoaderWindowsDYLD () override default
Member Function Documentation
CanLoadImage()
Status DynamicLoaderWindowsDYLD::CanLoadImage () override virtual
Ask if it is ok to try and load or unload an shared library (image).
The dynamic loader often knows when it would be ok to try and load or unload a shared library. This function call allows the dynamic loader plug-ins to check any current dyld state to make sure it is an ok time to load a shared library.
Returns
true if it is currently ok to try and load a shared library into the process, false otherwise.
Implements lldb_private::DynamicLoader.
Definition at line 171 of file DynamicLoaderWindowsDYLD.cpp.
References lldb_private::Status.
CreateInstance()
DynamicLoader * DynamicLoaderWindowsDYLD::CreateInstance (Process * process, bool force) static
Definition at line 46 of file DynamicLoaderWindowsDYLD.cpp.
References lldb_private::DynamicLoader::DynamicLoader(), DynamicLoaderWindowsDYLD(), lldb_private::Target::GetArchitecture(), lldb_private::Process::GetTarget(), and lldb_private::ArchSpec::GetTriple().
Referenced by Initialize().
DidAttach()
void DynamicLoaderWindowsDYLD::DidAttach () override virtual
Called after attaching a process.
Allow DynamicLoader plug-ins to execute some code after attaching to a process.
Implements lldb_private::DynamicLoader.
Definition at line 120 of file DynamicLoaderWindowsDYLD.cpp.
References lldb_private::ModuleList::Append(), lldb_private::DynamicLoader, error(), GetLoadAddress(), lldb_private::GetLog(), lldb_private::DynamicLoader::GetTargetExecutable(), LLDB_INVALID_ADDRESS, LLDB_LOG_ERROR, LLDB_LOGF, lldb_private::DynamicLoader::m_process, and lldb_private::DynamicLoader::UpdateLoadedSections().
DidLaunch()
void DynamicLoaderWindowsDYLD::DidLaunch () override virtual
Called after launching a process.
Allow DynamicLoader plug-ins to execute some code after the process has stopped for the first time on launch.
Implements lldb_private::DynamicLoader.
Definition at line 150 of file DynamicLoaderWindowsDYLD.cpp.
References lldb_private::ModuleList::Append(), lldb_private::DynamicLoader, error(), GetLoadAddress(), lldb_private::GetLog(), lldb_private::DynamicLoader::GetTargetExecutable(), LLDB_INVALID_ADDRESS, LLDB_LOG_ERROR, LLDB_LOGF, lldb_private::DynamicLoader::m_process, and lldb_private::DynamicLoader::UpdateLoadedSections().
GetLoadAddress()
lldb::addr_t DynamicLoaderWindowsDYLD::GetLoadAddress (lldb::ModuleSP executable) protected
Definition at line 97 of file DynamicLoaderWindowsDYLD.cpp.
References LLDB_INVALID_ADDRESS, m_loaded_modules, lldb_private::DynamicLoader::m_process, and lldb_private::Status::Success().
Referenced by DidAttach(), and DidLaunch().
GetPluginDescriptionStatic()
llvm::StringRef DynamicLoaderWindowsDYLD::GetPluginDescriptionStatic () static
Definition at line 41 of file DynamicLoaderWindowsDYLD.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef lldb_private::DynamicLoaderWindowsDYLD::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 42 of file DynamicLoaderWindowsDYLD.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::DynamicLoaderWindowsDYLD::GetPluginNameStatic () inline static
Definition at line 27 of file DynamicLoaderWindowsDYLD.h.
Referenced by lldb_private::ProcessWindows::GetDynamicLoader(), GetPluginName(), and Initialize().
GetStepThroughTrampolinePlan()
ThreadPlanSP DynamicLoaderWindowsDYLD::GetStepThroughTrampolinePlan (Thread & thread, bool stop_others) override virtual
Provides a plan to step through the dynamic loader trampoline for the current state of thread.
Parameters
[in] stop_others Whether the plan should be set to stop other threads.
Returns
A pointer to the plan (caller owned) or NULL if we are not at such a trampoline.
Implements lldb_private::DynamicLoader.
Definition at line 174 of file DynamicLoaderWindowsDYLD.cpp.
References lldb_private::Disassembler::DisassembleRange(), lldb_private::eVoteNoOpinion, lldb_private::InstructionList::GetInstructionAtIndex(), lldb_private::DynamicLoader::m_process, and pc.
Initialize()
void DynamicLoaderWindowsDYLD::Initialize () static
Definition at line 34 of file DynamicLoaderWindowsDYLD.cpp.
References CreateInstance(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
OnLoadModule()
void DynamicLoaderWindowsDYLD::OnLoadModule (lldb::ModuleSP module_sp, const ModuleSpec module_spec, lldb::addr_t module_addr)
Definition at line 62 of file DynamicLoaderWindowsDYLD.cpp.
References lldb_private::ModuleList::Append(), error(), m_loaded_modules, lldb_private::DynamicLoader::m_process, and lldb_private::DynamicLoader::UpdateLoadedSectionsCommon().
OnUnloadModule()
void DynamicLoaderWindowsDYLD::OnUnloadModule (lldb::addr_t module_addr)
Definition at line 82 of file DynamicLoaderWindowsDYLD.cpp.
References lldb_private::ModuleList::Append(), lldb_private::Address::GetModule(), m_loaded_modules, lldb_private::DynamicLoader::m_process, and lldb_private::DynamicLoader::UnloadSectionsCommon().
Terminate()
void DynamicLoaderWindowsDYLD::Terminate () static
Definition at line 39 of file DynamicLoaderWindowsDYLD.cpp.
Member Data Documentation
m_loaded_modules
std::map<lldb::ModuleWP, lldb::addr_t, std::owner_less<lldb::ModuleWP> > lldb_private::DynamicLoaderWindowsDYLD::m_loaded_modules private
Definition at line 49 of file DynamicLoaderWindowsDYLD.h.
Referenced by GetLoadAddress(), OnLoadModule(), and OnUnloadModule().
The documentation for this class was generated from the following files:
DynamicLoaderWindowsDYLD.h
DynamicLoaderWindowsDYLD.cpp