LLDB: IOHandlerLuaInterpreter Class Reference
IOHandlerLuaInterpreter Class Reference
Public Member Functions
IOHandlerLuaInterpreter (Debugger &debugger, ScriptInterpreterLua &script_interpreter, ActiveIOHandler active_io_handler=eIOHandlerNone)
~IOHandlerLuaInterpreter () override
void IOHandlerActivated (IOHandler &io_handler, bool interactive) override
bool IOHandlerIsInputComplete (IOHandler &io_handler, StringList &lines) override
Called to determine whether typing enter after the last line in lines should end input.
void IOHandlerInputComplete (IOHandler &io_handler, std::string &data) override
Called when a line or lines have been retrieved.
Public Member Functions inherited from lldb_private::IOHandlerDelegate
IOHandlerDelegate (Completion completion=Completion::None)
virtual ~IOHandlerDelegate ()=default
virtual void IOHandlerDeactivated (IOHandler &io_handler)
virtual std::optional< std::string > IOHandlerSuggestion (IOHandler &io_handler, llvm::StringRef line)
virtual void IOHandlerComplete (IOHandler &io_handler, CompletionRequest &request)
virtual const char * IOHandlerGetFixIndentationCharacters ()
virtual int IOHandlerFixIndentation (IOHandler &io_handler, const StringList &lines, int cursor_position)
Called when a new line is created or one of an identified set of indentation characters is typed.
virtual void IOHandlerInputInterrupted (IOHandler &io_handler, std::string &data)
virtual llvm::StringRef IOHandlerGetControlSequence (char ch)
virtual const char * IOHandlerGetCommandPrefix ()
virtual const char * IOHandlerGetHelpPrologue ()
virtual bool IOHandlerInterrupt (IOHandler &io_handler)
Public Member Functions inherited from lldb_private::IOHandlerEditline
IOHandlerEditline (Debugger &debugger, IOHandler::Type type, const char *editline_name, llvm::StringRef prompt, llvm::StringRef continuation_prompt, bool multi_line, bool color, uint32_t line_number_start, IOHandlerDelegate &delegate)
IOHandlerEditline (Debugger &debugger, IOHandler::Type type, const lldb::FileSP &input_sp, const lldb::LockableStreamFileSP &output_sp, const lldb::LockableStreamFileSP &error_sp, uint32_t flags, const char *editline_name, llvm::StringRef prompt, llvm::StringRef continuation_prompt, bool multi_line, bool color, uint32_t line_number_start, IOHandlerDelegate &delegate)
IOHandlerEditline (Debugger &, IOHandler::Type, const char *, const char *, const char *, bool, bool, uint32_t, IOHandlerDelegate &)=delete
IOHandlerEditline (Debugger &, IOHandler::Type, const lldb::FileSP &, const lldb::LockableStreamFileSP &, const lldb::LockableStreamFileSP &, uint32_t, const char *, const char *, const char *, bool, bool, uint32_t, IOHandlerDelegate &)=delete
~IOHandlerEditline () override
void Run () override
void Cancel () override
bool Interrupt () override
void GotEOF () override
void Activate () override
void Deactivate () override
void TerminalSizeChanged () override
llvm::StringRef GetControlSequence (char ch) override
const char * GetCommandPrefix () override
const char * GetHelpPrologue () override
const char * GetPrompt () override
bool SetPrompt (llvm::StringRef prompt) override
bool SetPrompt (const char *prompt)=delete
bool SetUseColor (bool use_color) override
const char * GetContinuationPrompt ()
void SetContinuationPrompt (llvm::StringRef prompt)
void SetContinuationPrompt (const char *)=delete
bool GetLine (std::string &line, bool &interrupted)
bool GetLines (StringList &lines, bool &interrupted)
void SetBaseLineNumber (uint32_t line)
bool GetInterruptExits ()
void SetInterruptExits (bool b)
StringList GetCurrentLines () const
uint32_t GetCurrentLineIndex () const
void PrintAsync (const char *s, size_t len, bool is_stdout) override
void Refresh () override
Public Member Functions inherited from lldb_private::IOHandler
IOHandler (Debugger &debugger, IOHandler::Type type)
IOHandler (Debugger &debugger, IOHandler::Type type, const lldb::FileSP &input_sp, const lldb::LockableStreamFileSP &output_sp, const lldb::LockableStreamFileSP &error_sp, uint32_t flags)
virtual ~IOHandler ()
bool IsActive ()
void SetIsDone (bool b)
bool GetIsDone ()
Type GetType () const
bool SetPrompt (const char *)=delete
int GetInputFD ()
int GetOutputFD ()
int GetErrorFD ()
lldb::FileSP GetInputFileSP ()
lldb::LockableStreamFileSP GetOutputStreamFileSP ()
lldb::LockableStreamFileSP GetErrorStreamFileSP ()
Debugger & GetDebugger ()
void * GetUserData ()
void SetUserData (void *user_data)
Flags & GetFlags ()
const Flags & GetFlags () const
bool GetIsInteractive ()
Check if the input is being supplied interactively by a user.
bool GetIsRealTerminal ()
Check if the input is coming from a real terminal.
void SetPopped (bool b)
void WaitForPop ()
Private Member Functions
bool IsQuitCommand (llvm::StringRef cmd)
Private Attributes
ScriptInterpreterLua & m_script_interpreter
ActiveIOHandler m_active_io_handler
Additional Inherited Members
Public Types inherited from lldb_private::IOHandlerDelegate
enum class Completion { None , LLDBCommand , Expression }
Public Types inherited from lldb_private::IOHandler
enum class Type {
CommandInterpreter , CommandList , Confirm , Curses ,
Expression , REPL , ProcessIO , PythonInterpreter ,
LuaInterpreter , PythonCode , Other
}
Protected Attributes inherited from lldb_private::IOHandlerDelegate
Completion m_completion
Protected Attributes inherited from lldb_private::IOHandlerEditline
IOHandlerDelegate & m_delegate
std::string m_prompt
std::string m_continuation_prompt
StringList * m_current_lines_ptr
uint32_t m_base_line_number
uint32_t m_curr_line_idx
bool m_multi_line
bool m_color
bool m_interrupt_exits
std::string m_line_buffer
Protected Attributes inherited from lldb_private::IOHandler
Debugger & m_debugger
lldb::FileSP m_input_sp
lldb::LockableStreamFileSP m_output_sp
lldb::LockableStreamFileSP m_error_sp
Predicate< bool > m_popped
Flags m_flags
Type m_type
void * m_user_data
bool m_done
bool m_active
Detailed Description
Definition at line 37 of file ScriptInterpreterLua.cpp.
Constructor & Destructor Documentation
IOHandlerLuaInterpreter()
IOHandlerLuaInterpreter::IOHandlerLuaInterpreter (Debugger & debugger, ScriptInterpreterLua & script_interpreter, ActiveIOHandler active_io_handler = eIOHandlerNone) inline
Definition at line 40 of file ScriptInterpreterLua.cpp.
References eIOHandlerNone, lldb_private::Debugger::GetErrorFileSP(), lldb_private::UserID::GetID(), lldb_private::Debugger::GetOutputFileSP(), lldb_private::IOHandlerEditline::IOHandlerEditline(), lldb_private::IOHandler::LuaInterpreter, m_active_io_handler, and m_script_interpreter.
~IOHandlerLuaInterpreter()
IOHandlerLuaInterpreter::~IOHandlerLuaInterpreter () inline override
Definition at line 54 of file ScriptInterpreterLua.cpp.
References m_script_interpreter.
Member Function Documentation
IOHandlerActivated()
void IOHandlerLuaInterpreter::IOHandlerActivated (IOHandler & io_handler, bool interactive) inline override virtual
Reimplemented from lldb_private::IOHandlerDelegate.
Definition at line 58 of file ScriptInterpreterLua.cpp.
References eIOHandlerBreakpoint, eIOHandlerNone, eIOHandlerWatchpoint, lldb_private::IOHandler::GetOutputStreamFileSP(), m_active_io_handler, and lldb_private::IOHandlerEditline::SetPrompt().
IOHandlerInputComplete()
void IOHandlerLuaInterpreter::IOHandlerInputComplete (IOHandler & io_handler, std::string & data) inline override virtual
Called when a line or lines have been retrieved.
This function can handle the current line and possibly call IOHandler::SetIsDone(true) when the IO handler is done like when "quit" is entered as a command, of when an empty line is received. It is up to the delegate to determine when a line should cause a IOHandler to exit.
Implements lldb_private::IOHandlerDelegate.
Definition at line 111 of file ScriptInterpreterLua.cpp.
References eIOHandlerBreakpoint, eIOHandlerNone, eIOHandlerWatchpoint, error(), lldb_private::IOHandler::GetErrorStreamFileSP(), lldb_private::IOHandler::GetUserData(), IsQuitCommand(), m_active_io_handler, m_script_interpreter, lldb_private::IOHandler::SetIsDone(), and lldb_private::toString().
IOHandlerIsInputComplete()
bool IOHandlerLuaInterpreter::IOHandlerIsInputComplete (IOHandler & io_handler, StringList & lines) inline override virtual
Called to determine whether typing enter after the last line in lines should end input.
This function will not be called on IOHandler objects that are getting single lines.
Parameters
[in] io_handler The IOHandler that responsible for updating the lines.
[in] lines The current multi-line content. May be altered to provide alternative input when complete.
Returns
Return an boolean to indicate whether input is complete, true indicates that no additional input is necessary, while false indicates that more input is required.
Reimplemented from lldb_private::IOHandlerDelegate.
Definition at line 89 of file ScriptInterpreterLua.cpp.
References lldb_private::StringList::DeleteStringAtIndex(), eIOHandlerBreakpoint, eIOHandlerWatchpoint, lldb_private::StringList::GetSize(), lldb_private::StreamString::GetString(), lldb_private::StringList::GetStringAtIndex(), IsQuitCommand(), lldb_private::StringList::Join(), m_active_io_handler, m_script_interpreter, and lldb_private::toString().
IsQuitCommand()
bool IOHandlerLuaInterpreter::IsQuitCommand (llvm::StringRef cmd) inline private
Definition at line 155 of file ScriptInterpreterLua.cpp.
Referenced by IOHandlerInputComplete(), and IOHandlerIsInputComplete().
Member Data Documentation
m_active_io_handler
ActiveIOHandler IOHandlerLuaInterpreter::m_active_io_handler private
Definition at line 153 of file ScriptInterpreterLua.cpp.
Referenced by IOHandlerActivated(), IOHandlerInputComplete(), IOHandlerIsInputComplete(), and IOHandlerLuaInterpreter().
m_script_interpreter
ScriptInterpreterLua& IOHandlerLuaInterpreter::m_script_interpreter private
Definition at line 152 of file ScriptInterpreterLua.cpp.
Referenced by IOHandlerInputComplete(), IOHandlerIsInputComplete(), IOHandlerLuaInterpreter(), and ~IOHandlerLuaInterpreter().
The documentation for this class was generated from the following file:
ScriptInterpreterLua.cpp