LLDB: lldb_private::CommandObject Class Reference
lldb_private::CommandObject Class Reference abstract
#include <CommandObject.h>
Classes
struct ArgumentHelpCallback
struct ArgumentTableEntry
Entries in the main argument information table.
struct CommandArgumentData
Used to build individual command argument lists.
Public Types
enum IDType { eBreakpointArgs = 0 , eWatchpointArgs = 1 }
typedef llvm::StringRef ArgumentHelpCallbackFunction()
typedef std::vector< CommandArgumentData > CommandArgumentEntry
typedef std::map< std::string, lldb::CommandObjectSP, std::less<> > CommandMap
Public Member Functions
CommandObject (CommandInterpreter &interpreter, llvm::StringRef name, llvm::StringRef help="", llvm::StringRef syntax="", uint32_t flags=0)
virtual ~CommandObject ()=default
CommandInterpreter & GetCommandInterpreter ()
Debugger & GetDebugger ()
virtual llvm::StringRef GetHelp ()
virtual llvm::StringRef GetHelpLong ()
virtual llvm::StringRef GetSyntax ()
llvm::StringRef GetCommandName () const
virtual void SetHelp (llvm::StringRef str)
virtual void SetHelpLong (llvm::StringRef str)
void SetSyntax (llvm::StringRef str)
virtual bool IsRemovable () const
virtual bool IsMultiwordObject ()
bool IsUserCommand ()
void SetIsUserCommand (bool is_user)
virtual CommandObjectMultiword * GetAsMultiwordCommand ()
virtual bool IsAlias ()
virtual bool IsDashDashCommand ()
virtual lldb::CommandObjectSP GetSubcommandSP (llvm::StringRef sub_cmd, StringList *matches=nullptr)
virtual lldb::CommandObjectSP GetSubcommandSPExact (llvm::StringRef sub_cmd)
virtual CommandObject * GetSubcommandObject (llvm::StringRef sub_cmd, StringList *matches=nullptr)
void FormatLongHelpText (Stream &output_strm, llvm::StringRef long_help)
void GenerateHelpText (CommandReturnObject &result)
virtual void GenerateHelpText (Stream &result)
virtual bool LoadSubCommand (llvm::StringRef cmd_name, const lldb::CommandObjectSP &command_obj)
virtual llvm::Error LoadUserSubcommand (llvm::StringRef cmd_name, const lldb::CommandObjectSP &command_obj, bool can_replace)
virtual bool WantsRawCommandString ()=0
virtual bool WantsCompletion ()
virtual Options * GetOptions ()
void AddSimpleArgumentList (lldb::CommandArgumentType arg_type, ArgumentRepetitionType repetition_type=eArgRepeatPlain)
void AddIDsArgumentData (IDType type)
int GetNumArgumentEntries ()
CommandArgumentEntry * GetArgumentEntryAtIndex (int idx)
void GetFormattedCommandArguments (Stream &str, uint32_t opt_set_mask=LLDB_OPT_SET_ALL)
bool ParseOptions (Args &args, CommandReturnObject &result)
void SetCommandName (llvm::StringRef name)
virtual void HandleCompletion (CompletionRequest &request)
This default version handles calling option argument completions and then calls HandleArgumentCompletion if the cursor is on an argument, not an option.
virtual void HandleArgumentCompletion (CompletionRequest &request, OptionElementVector &opt_element_vector)
The default version handles argument definitions that have only one argument type, and use one of the argument types that have an entry in the CommonCompletions.
bool HelpTextContainsWord (llvm::StringRef search_word, bool search_short_help=true, bool search_long_help=true, bool search_syntax=true, bool search_options=true)
Flags & GetFlags ()
The flags accessor.
const Flags & GetFlags () const
The flags const accessor.
virtual std::optional< std::string > GetRepeatCommand (Args &current_command_args, uint32_t index)
Get the command that appropriate for a "repeat" of the current command.
bool HasOverrideCallback () const
void SetOverrideCallback (lldb::CommandOverrideCallback callback, void *baton)
void SetOverrideCallback (lldb_private::CommandOverrideCallbackWithResult callback, void *baton)
bool InvokeOverrideCallback (const char **argv, CommandReturnObject &result)
void SetOriginalCommandString (std::string s)
Set the command input as it appeared in the terminal.
virtual void Execute (const char *args_string, CommandReturnObject &result)=0
Static Public Member Functions
static const char * GetArgumentTypeAsCString (const lldb::CommandArgumentType arg_type)
static const char * GetArgumentDescriptionAsCString (const lldb::CommandArgumentType arg_type)
static lldb::CommandArgumentType LookupArgumentName (llvm::StringRef arg_name)
static const ArgumentTableEntry * FindArgumentDataByType (lldb::CommandArgumentType arg_type)
static void GetArgumentHelp (Stream &str, lldb::CommandArgumentType arg_type, CommandInterpreter &interpreter)
static const char * GetArgumentName (lldb::CommandArgumentType arg_type)
static bool IsPairType (ArgumentRepetitionType arg_repeat_type)
static std::optional< ArgumentRepetitionType > ArgRepetitionFromString (llvm::StringRef string)
Protected Member Functions
bool ParseOptionsAndNotify (Args &args, CommandReturnObject &result, OptionGroupOptions &group_options, ExecutionContext &exe_ctx)
virtual const char * GetInvalidTargetDescription ()
virtual const char * GetInvalidProcessDescription ()
virtual const char * GetInvalidThreadDescription ()
virtual const char * GetInvalidFrameDescription ()
virtual const char * GetInvalidRegContextDescription ()
Target & GetDummyTarget ()
Target & GetTarget ()
Thread * GetDefaultThread ()
bool CheckRequirements (CommandReturnObject &result)
Check the command to make sure anything required by this command is available.
void Cleanup ()
Protected Attributes
CommandInterpreter & m_interpreter
ExecutionContext m_exe_ctx
std::unique_lock< std::recursive_mutex > m_api_locker
std::string m_cmd_name
std::string m_cmd_help_short
std::string m_cmd_help_long
std::string m_cmd_syntax
std::string m_original_command
Flags m_flags
std::vector< CommandArgumentEntry > m_arguments
lldb::CommandOverrideCallback m_deprecated_command_override_callback
lldb_private::CommandOverrideCallbackWithResult m_command_override_callback
void * m_command_override_baton
bool m_is_user_command = false
Detailed Description
Definition at line 70 of file CommandObject.h.
Member Typedef Documentation
ArgumentHelpCallbackFunction
typedef llvm::StringRef lldb_private::CommandObject::ArgumentHelpCallbackFunction()
Definition at line 72 of file CommandObject.h.
CommandArgumentEntry
typedef std::vector<CommandArgumentData> lldb_private::CommandObject::CommandArgumentEntry
Definition at line 109 of file CommandObject.h.
CommandMap
typedef std::map<std::string, lldb::CommandObjectSP, std::less<> > lldb_private::CommandObject::CommandMap
Definition at line 111 of file CommandObject.h.
Member Enumeration Documentation
IDType
enum lldb_private::CommandObject::IDType
Enumerator
eBreakpointArgs
eWatchpointArgs
Definition at line 222 of file CommandObject.h.
Constructor & Destructor Documentation
CommandObject()
CommandObject::CommandObject (CommandInterpreter & interpreter, llvm::StringRef name, llvm::StringRef help = "", llvm::StringRef syntax = "", uint32_t flags = 0)
Definition at line 42 of file CommandObject.cpp.
References m_cmd_help_short, m_cmd_name, m_cmd_syntax, m_command_override_baton, m_command_override_callback, m_deprecated_command_override_callback, m_flags, and m_interpreter.
Referenced by lldb_private::CommandAlias::CommandAlias(), lldb_private::CommandObjectMultiword::CommandObjectMultiword(), lldb_private::CommandObjectParsed::CommandObjectParsed(), lldb_private::CommandObjectProxy::CommandObjectProxy(), lldb_private::CommandObjectRaw::CommandObjectRaw(), lldb_private::CommandObjectMultiword::Execute(), lldb_private::CommandObjectProxy::Execute(), lldb_private::CommandObjectProxy::GenerateHelpText(), lldb_private::CommandObjectProxy::GetAsMultiwordCommand(), lldb_private::CommandObjectProxy::GetHelp(), lldb_private::CommandObjectProxy::GetHelpLong(), lldb_private::CommandObjectProxy::GetOptions(), lldb_private::CommandObjectProxy::GetProxyCommandObject(), lldb_private::CommandObjectMultiword::GetRepeatCommand(), lldb_private::CommandObjectProxy::GetRepeatCommand(), GetSubcommandObject(), lldb_private::CommandObjectProxy::GetSubcommandObject(), lldb_private::CommandObjectProxy::GetSubcommandSP(), lldb_private::CommandObjectProxy::GetSyntax(), lldb_private::CommandObjectProxy::HandleArgumentCompletion(), lldb_private::CommandObjectMultiword::HandleCompletion(), lldb_private::CommandObjectProxy::HandleCompletion(), lldb_private::CommandObjectProxy::IsMultiwordObject(), lldb_private::CommandObjectProxy::IsRemovable(), lldb_private::CommandObjectProxy::LoadSubCommand(), lldb_private::CommandObjectProxy::WantsCompletion(), and lldb_private::CommandObjectProxy::WantsRawCommandString().
~CommandObject()
virtual lldb_private::CommandObject::~CommandObject () virtual default
Member Function Documentation
AddIDsArgumentData()
void CommandObject::AddIDsArgumentData (CommandObject::IDType type)
Definition at line 710 of file CommandObject.cpp.
References lldb_private::CommandObject::CommandArgumentData::arg_repetition, lldb_private::CommandObject::CommandArgumentData::arg_type, lldb_private::eArgRepeatOptional, lldb::eArgTypeBreakpointID, lldb::eArgTypeBreakpointIDRange, lldb::eArgTypeWatchpointID, lldb::eArgTypeWatchpointIDRange, eBreakpointArgs, eWatchpointArgs, and m_arguments.
Referenced by CommandObjectBreakpointDelete::CommandObjectBreakpointDelete(), CommandObjectBreakpointEnable::CommandObjectBreakpointEnable(), CommandObjectBreakpointModify::CommandObjectBreakpointModify(), CommandObjectBreakpointWrite::CommandObjectBreakpointWrite(), CommandObjectWatchpointDelete::CommandObjectWatchpointDelete(), CommandObjectWatchpointDisable::CommandObjectWatchpointDisable(), CommandObjectWatchpointEnable::CommandObjectWatchpointEnable(), CommandObjectWatchpointIgnore::CommandObjectWatchpointIgnore(), CommandObjectWatchpointList::CommandObjectWatchpointList(), and CommandObjectWatchpointModify::CommandObjectWatchpointModify().
AddSimpleArgumentList()
void CommandObject::AddSimpleArgumentList (lldb::CommandArgumentType arg_type, ArgumentRepetitionType repetition_type = eArgRepeatPlain)
Definition at line 389 of file CommandObject.cpp.
References lldb_private::CommandObject::CommandArgumentData::arg_repetition, lldb_private::CommandObject::CommandArgumentData::arg_type, and m_arguments.
Referenced by lldb_private::CommandObjectApropos::CommandObjectApropos(), CommandObjectBreakpointAddAddress::CommandObjectBreakpointAddAddress(), CommandObjectBreakpointAddException::CommandObjectBreakpointAddException(), CommandObjectBreakpointAddName::CommandObjectBreakpointAddName(), CommandObjectBreakpointAddPattern::CommandObjectBreakpointAddPattern(), CommandObjectBreakpointCommandDelete::CommandObjectBreakpointCommandDelete(), CommandObjectBreakpointCommandList::CommandObjectBreakpointCommandList(), CommandObjectBreakpointList::CommandObjectBreakpointList(), CommandObjectBreakpointNameAdd::CommandObjectBreakpointNameAdd(), CommandObjectBreakpointNameConfigure::CommandObjectBreakpointNameConfigure(), CommandObjectBreakpointNameDelete::CommandObjectBreakpointNameDelete(), CommandObjectCommandsContainerAdd::CommandObjectCommandsContainerAdd(), CommandObjectCommandsContainerDelete::CommandObjectCommandsContainerDelete(), CommandObjectCommandsDelete::CommandObjectCommandsDelete(), CommandObjectCommandsScriptAdd::CommandObjectCommandsScriptAdd(), CommandObjectCommandsScriptDelete::CommandObjectCommandsScriptDelete(), CommandObjectCommandsScriptImport::CommandObjectCommandsScriptImport(), CommandObjectCommandsSource::CommandObjectCommandsSource(), CommandObjectCommandsUnalias::CommandObjectCommandsUnalias(), lldb_private::CommandObjectDWIMPrint::CommandObjectDWIMPrint(), CommandObjectFrameDiagnose::CommandObjectFrameDiagnose(), CommandObjectFrameRecognizerDelete::CommandObjectFrameRecognizerDelete(), CommandObjectFrameRecognizerDisable::CommandObjectFrameRecognizerDisable(), CommandObjectFrameRecognizerEnable::CommandObjectFrameRecognizerEnable(), CommandObjectFrameRecognizerInfo::CommandObjectFrameRecognizerInfo(), CommandObjectFrameSelect::CommandObjectFrameSelect(), CommandObjectFrameVariable::CommandObjectFrameVariable(), lldb_private::CommandObjectHelp::CommandObjectHelp(), lldb_private::CommandObjectIterateOverThreads::CommandObjectIterateOverThreads(), CommandObjectLogDump::CommandObjectLogDump(), CommandObjectLogList::CommandObjectLogList(), CommandObjectLogTimerEnable::CommandObjectLogTimerEnable(), CommandObjectLogTimerIncrement::CommandObjectLogTimerIncrement(), lldb_private::CommandObjectMultipleThreads::CommandObjectMultipleThreads(), CommandObjectMultiwordItaniumABI_Demangle::CommandObjectMultiwordItaniumABI_Demangle(), CommandObjectMultiwordObjC_TaggedPointer_Info::CommandObjectMultiwordObjC_TaggedPointer_Info(), CommandObjectObjC_ClassTable_Dump::CommandObjectObjC_ClassTable_Dump(), CommandObjectPlatformConnect::CommandObjectPlatformConnect(), CommandObjectPlatformFClose::CommandObjectPlatformFClose(), CommandObjectPlatformFOpen::CommandObjectPlatformFOpen(), CommandObjectPlatformFRead::CommandObjectPlatformFRead(), CommandObjectPlatformFWrite::CommandObjectPlatformFWrite(), CommandObjectPlatformMkDir::CommandObjectPlatformMkDir(), CommandObjectPlatformProcessInfo::CommandObjectPlatformProcessInfo(), CommandObjectPlatformProcessLaunch::CommandObjectPlatformProcessLaunch(), CommandObjectPlatformSelect::CommandObjectPlatformSelect(), CommandObjectPlatformShell::CommandObjectPlatformShell(), CommandObjectPluginDisable::CommandObjectPluginDisable(), CommandObjectPluginEnable::CommandObjectPluginEnable(), CommandObjectPluginList::CommandObjectPluginList(), CommandObjectPluginLoad::CommandObjectPluginLoad(), CommandObjectProcessConnect::CommandObjectProcessConnect(), CommandObjectProcessGDBRemotePacketSend::CommandObjectProcessGDBRemotePacketSend(), CommandObjectProcessGDBRemotePacketXferSize::CommandObjectProcessGDBRemotePacketXferSize(), CommandObjectProcessHandle::CommandObjectProcessHandle(), CommandObjectProcessLaunch::CommandObjectProcessLaunch(), CommandObjectProcessLoad::CommandObjectProcessLoad(), CommandObjectProcessSaveCore::CommandObjectProcessSaveCore(), CommandObjectProcessSignal::CommandObjectProcessSignal(), CommandObjectProcessUnload::CommandObjectProcessUnload(), CommandObjectProtocolServerGet::CommandObjectProtocolServerGet(), CommandObjectProtocolServerStart::CommandObjectProtocolServerStart(), CommandObjectProtocolServerStop::CommandObjectProtocolServerStop(), lldb_private::CommandObjectQuit::CommandObjectQuit(), CommandObjectSessionSave::CommandObjectSessionSave(), CommandObjectSettingsClear::CommandObjectSettingsClear(), CommandObjectSettingsShow::CommandObjectSettingsShow(), CommandObjectSettingsWrite::CommandObjectSettingsWrite(), CommandObjectTargetCreate::CommandObjectTargetCreate(), CommandObjectTargetDelete::CommandObjectTargetDelete(), CommandObjectTargetFrameProviderRemove::CommandObjectTargetFrameProviderRemove(), CommandObjectTargetModulesAdd::CommandObjectTargetModulesAdd(), CommandObjectTargetModulesDumpClangPCMInfo::CommandObjectTargetModulesDumpClangPCMInfo(), CommandObjectTargetModulesList::CommandObjectTargetModulesList(), CommandObjectTargetModulesLookup::CommandObjectTargetModulesLookup(), CommandObjectTargetModulesModuleAutoComplete::CommandObjectTargetModulesModuleAutoComplete(), CommandObjectTargetModulesSearchPathsQuery::CommandObjectTargetModulesSearchPathsQuery(), CommandObjectTargetModulesSourceFileAutoComplete::CommandObjectTargetModulesSourceFileAutoComplete(), CommandObjectTargetSelect::CommandObjectTargetSelect(), CommandObjectTargetStopHookEnableDisable::CommandObjectTargetStopHookEnableDisable(), CommandObjectTargetSymbolsAdd::CommandObjectTargetSymbolsAdd(), CommandObjectTargetVariable::CommandObjectTargetVariable(), CommandObjectThreadContinue::CommandObjectThreadContinue(), CommandObjectThreadPlanDiscard::CommandObjectThreadPlanDiscard(), CommandObjectThreadPlanPrune::CommandObjectThreadPlanPrune(), CommandObjectThreadReturn::CommandObjectThreadReturn(), CommandObjectThreadStepWithTypeAndScope::CommandObjectThreadStepWithTypeAndScope(), CommandObjectThreadUntil::CommandObjectThreadUntil(), CommandObjectTraceDumpFunctionCalls::CommandObjectTraceDumpFunctionCalls(), CommandObjectTraceDumpInstructions::CommandObjectTraceDumpInstructions(), CommandObjectTraceLoad::CommandObjectTraceLoad(), CommandObjectTraceSave::CommandObjectTraceSave(), CommandObjectTraceSchema::CommandObjectTraceSchema(), CommandObjectTypeFilterList::CommandObjectTypeFilterList(), CommandObjectTypeFormatAdd::CommandObjectTypeFormatAdd(), CommandObjectTypeFormatterClear::CommandObjectTypeFormatterClear(), CommandObjectTypeFormatterDelete::CommandObjectTypeFormatterDelete(), CommandObjectTypeFormatterList< FormatterType >::CommandObjectTypeFormatterList(), CommandObjectTypeSummaryAdd::CommandObjectTypeSummaryAdd(), CommandObjectWatchpointCommandDelete::CommandObjectWatchpointCommandDelete(), CommandObjectWatchpointCommandList::CommandObjectWatchpointCommandList(), CommandObjectWatchpointSetExpression::CommandObjectWatchpointSetExpression(), CommandObjectWatchpointSetVariable::CommandObjectWatchpointSetVariable(), CommandObjectWithFrameRecognizerArg::CommandObjectWithFrameRecognizerArg(), CommandObjectTypeCategoryList::DoExecute(), and CommandObjectTypeCategoryEnable::CommandOptions::OptionParsingStarting().
ArgRepetitionFromString()
std::optional< ArgumentRepetitionType > CommandObject::ArgRepetitionFromString (llvm::StringRef string) static
Definition at line 500 of file CommandObject.cpp.
References lldb_private::eArgRepeatOptional, lldb_private::eArgRepeatPairOptional, lldb_private::eArgRepeatPairPlain, lldb_private::eArgRepeatPairPlus, lldb_private::eArgRepeatPairRange, lldb_private::eArgRepeatPairRangeOptional, lldb_private::eArgRepeatPairStar, lldb_private::eArgRepeatPlain, lldb_private::eArgRepeatPlus, lldb_private::eArgRepeatRange, and lldb_private::eArgRepeatStar.
Referenced by CommandObjectScriptingObjectParsed::CommandObjectScriptingObjectParsed().
CheckRequirements()
bool CommandObject::CheckRequirements (CommandReturnObject & result) protected
Check the command to make sure anything required by this command is available.
Parameters
[out] result A command result object, if it is not okay to run the command this will be filled in with a suitable error.
Returns
true if it is okay to run this command, false otherwise.
Definition at line 144 of file CommandObject.cpp.
References lldb_private::CommandReturnObject::AppendError(), lldb::eStateAttaching, lldb::eStateConnected, lldb::eStateCrashed, lldb::eStateDetached, lldb::eStateExited, lldb::eStateInvalid, lldb::eStateLaunching, lldb::eStateRunning, lldb::eStateStepping, lldb::eStateStopped, lldb::eStateSuspended, lldb::eStateUnloaded, lldb_private::Flags::Get(), lldb_private::Target::GetAPIMutex(), GetFlags(), GetInvalidFrameDescription(), GetInvalidProcessDescription(), GetInvalidRegContextDescription(), GetInvalidTargetDescription(), GetInvalidThreadDescription(), lldb_private::Process::GetState(), lldb_private::Target::GetTrace(), m_api_locker, m_exe_ctx, and m_interpreter.
Referenced by lldb_private::CommandObjectParsed::Execute(), and lldb_private::CommandObjectRaw::Execute().
Cleanup()
void CommandObject::Cleanup () protected
Definition at line 266 of file CommandObject.cpp.
References m_api_locker, and m_exe_ctx.
Referenced by lldb_private::CommandObjectParsed::Execute(), lldb_private::CommandObjectRaw::Execute(), and HandleCompletion().
Execute()
virtual void lldb_private::CommandObject::Execute (const char * args_string, CommandReturnObject & result) pure virtual
Parameters
offset_in_command is on what column args_string appears, if applicable. This enables diagnostics that refer back to the user input.
Implemented in lldb_private::CommandAlias, lldb_private::CommandObjectMultiword, lldb_private::CommandObjectParsed, lldb_private::CommandObjectProxy, and lldb_private::CommandObjectRaw.
Referenced by lldb_private::CommandObjectMultiword::Execute(), and lldb_private::CommandInterpreter::HandleCommand().
FindArgumentDataByType()
const CommandObject::ArgumentTableEntry * CommandObject::FindArgumentDataByType (lldb::CommandArgumentType arg_type) static
Definition at line 418 of file CommandObject.cpp.
References lldb::eArgTypeLastArg, and lldb_private::g_argument_table.
Referenced by GetArgumentHelp(), GetArgumentName(), HandleArgumentCompletion(), and lldb_private::Options::HandleOptionArgumentCompletion().
FormatLongHelpText()
void CommandObject::FormatLongHelpText (Stream & output_strm, llvm::StringRef long_help)
Definition at line 637 of file CommandObject.cpp.
References GetCommandInterpreter(), and lldb_private::CommandInterpreter::OutputFormattedHelpText().
Referenced by GenerateHelpText().
GenerateHelpText() [1/2]
void CommandObject::GenerateHelpText (CommandReturnObject & result)
Definition at line 658 of file CommandObject.cpp.
References lldb::eReturnStatusSuccessFinishNoResult, GenerateHelpText(), lldb_private::CommandReturnObject::GetOutputStream(), and lldb_private::CommandReturnObject::SetStatus().
Referenced by lldb_private::CommandObjectHelp::DoExecute(), lldb_private::CommandObjectMultiword::Execute(), GenerateHelpText(), lldb_private::CommandObjectMultiword::GenerateHelpText(), and lldb_private::CommandObjectProxy::GenerateHelpText().
GenerateHelpText() [2/2]
void CommandObject::GenerateHelpText (Stream & result) virtual
Reimplemented in lldb_private::CommandObjectMultiword, and lldb_private::CommandObjectProxy.
Definition at line 664 of file CommandObject.cpp.
References FormatLongHelpText(), lldb_private::Options::GenerateOptionUsage(), GetCommandInterpreter(), GetDebugger(), GetHelp(), GetHelpLong(), GetNumArgumentEntries(), GetOptions(), GetSyntax(), IsDashDashCommand(), lldb_private::Options::NumCommandOptions(), lldb_private::CommandInterpreter::OutputFormattedHelpText(), WantsCompletion(), and WantsRawCommandString().
GetArgumentDescriptionAsCString()
const char * CommandObject::GetArgumentDescriptionAsCString (const lldb::CommandArgumentType arg_type) static
Definition at line 745 of file CommandObject.cpp.
References lldb::eArgTypeLastArg, and lldb_private::g_argument_table.
Referenced by lldb::SBCommandInterpreter::GetArgumentDescriptionAsCString().
GetArgumentEntryAtIndex()
CommandObject::CommandArgumentEntry * CommandObject::GetArgumentEntryAtIndex (int idx)
Definition at line 410 of file CommandObject.cpp.
References m_arguments.
Referenced by HandleArgumentCompletion().
GetArgumentHelp()
void CommandObject::GetArgumentHelp (Stream & str, lldb::CommandArgumentType arg_type, CommandInterpreter & interpreter) static
Definition at line 426 of file CommandObject.cpp.
References lldb_private::CommandObject::ArgumentTableEntry::arg_name, lldb_private::CommandObject::ArgumentTableEntry::arg_type, lldb_private::Stream::EOL(), FindArgumentDataByType(), lldb_private::g_argument_table, lldb_private::StreamString::GetSize(), lldb_private::StreamString::GetString(), lldb_private::CommandObject::ArgumentTableEntry::help_function, lldb_private::CommandObject::ArgumentTableEntry::help_text, lldb_private::Stream::Indent(), lldb_private::Stream::IndentLess(), lldb_private::Stream::IndentMore(), lldb_private::CommandInterpreter::OutputFormattedHelpText(), lldb_private::CommandInterpreter::OutputHelpText(), lldb_private::Stream::Printf(), and lldb_private::CommandObject::ArgumentHelpCallback::self_formatting.
Referenced by lldb_private::CommandObjectHelp::DoExecute().
GetArgumentName()
const char * CommandObject::GetArgumentName (lldb::CommandArgumentType arg_type) static
Definition at line 475 of file CommandObject.cpp.
References lldb_private::CommandObject::ArgumentTableEntry::arg_name, lldb_private::CommandObject::ArgumentTableEntry::arg_type, FindArgumentDataByType(), and lldb_private::g_argument_table.
Referenced by GetFormattedCommandArguments(), and PrintOption().
GetArgumentTypeAsCString()
const char * CommandObject::GetArgumentTypeAsCString (const lldb::CommandArgumentType arg_type) static
Definition at line 738 of file CommandObject.cpp.
References lldb::eArgTypeLastArg, and lldb_private::g_argument_table.
Referenced by lldb::SBCommandInterpreter::GetArgumentTypeAsCString().
GetAsMultiwordCommand()
virtual CommandObjectMultiword * lldb_private::CommandObject::GetAsMultiwordCommand () inline virtual
Reimplemented in lldb_private::CommandObjectMultiword, and lldb_private::CommandObjectProxy.
Definition at line 153 of file CommandObject.h.
Referenced by lldb_private::CommandInterpreter::FindCommandsForApropos(), and lldb_private::CommandObjectProxy::GetAsMultiwordCommand().
GetCommandInterpreter()
CommandInterpreter & lldb_private::CommandObject::GetCommandInterpreter () inline
Definition at line 125 of file CommandObject.h.
References m_interpreter.
Referenced by CommandObjectBreakpointAddPattern::DoExecute(), CommandObjectCommandsContainerAdd::DoExecute(), CommandObjectCommandsContainerDelete::DoExecute(), CommandObjectCommandsScriptAdd::DoExecute(), CommandObjectCommandsScriptDelete::DoExecute(), CommandObjectFrameSelect::DoExecute(), CommandObjectPlatformShell::DoExecute(), CommandObjectStatsDump::DoExecute(), CommandObjectTargetDumpTypesystem::DoExecute(), CommandObjectTargetModulesDumpClangAST::DoExecute(), lldb_private::CommandObjectDisassemble::DoExecute(), sddarwinlog_private::EnableCommand::DoExecute(), sddarwinlog_private::StatusCommand::DoExecute(), FormatLongHelpText(), GenerateHelpText(), CommandObjectBreakpointDelete::HandleArgumentCompletion(), CommandObjectBreakpointEnable::HandleArgumentCompletion(), CommandObjectBreakpointModify::HandleArgumentCompletion(), CommandObjectBreakpointNameAdd::HandleArgumentCompletion(), CommandObjectBreakpointNameDelete::HandleArgumentCompletion(), CommandObjectBreakpointWrite::HandleArgumentCompletion(), CommandObjectPlatformGetFile::HandleArgumentCompletion(), CommandObjectPlatformInstall::HandleArgumentCompletion(), CommandObjectPlatformProcessLaunch::HandleArgumentCompletion(), CommandObjectPluginDisable::HandleArgumentCompletion(), CommandObjectPluginEnable::HandleArgumentCompletion(), CommandObjectPythonFunction::HandleArgumentCompletion(), CommandObjectRegisterWrite::HandleArgumentCompletion(), CommandObjectScriptingObjectRaw::HandleArgumentCompletion(), CommandObjectSettingsAppend::HandleArgumentCompletion(), CommandObjectSettingsClear::HandleArgumentCompletion(), CommandObjectSettingsInsertAfter::HandleArgumentCompletion(), CommandObjectSettingsInsertBefore::HandleArgumentCompletion(), CommandObjectSettingsList::HandleArgumentCompletion(), CommandObjectSettingsRemove::HandleArgumentCompletion(), CommandObjectSettingsReplace::HandleArgumentCompletion(), CommandObjectTargetModulesModuleAutoComplete::HandleArgumentCompletion(), CommandObjectTargetModulesSourceFileAutoComplete::HandleArgumentCompletion(), CommandObjectThreadException::HandleArgumentCompletion(), CommandObjectThreadInfo::HandleArgumentCompletion(), CommandObjectThreadSelect::HandleArgumentCompletion(), CommandObjectThreadSiginfo::HandleArgumentCompletion(), CommandObjectTraceLoad::HandleArgumentCompletion(), CommandObjectTraceSave::HandleArgumentCompletion(), CommandObjectWatchpointDelete::HandleArgumentCompletion(), CommandObjectWatchpointDisable::HandleArgumentCompletion(), CommandObjectWatchpointEnable::HandleArgumentCompletion(), CommandObjectWatchpointIgnore::HandleArgumentCompletion(), CommandObjectWatchpointModify::HandleArgumentCompletion(), HandleArgumentCompletion(), CommandObjectPlatformSelect::HandleCompletion(), HandleCompletion(), lldb_private::CommandObjectRegexCommand::HandleCompletion(), HelpTextContainsWord(), lldb_private::LanguageRuntime::InitializeCommands(), lldb_private::CommandObjectMultiword::LoadSubCommand(), lldb_private::CommandObjectMultiword::LoadUserSubcommand(), CommandObjectTargetModulesLookup::LookupInModule(), CommandObjectPluginList::OutputJsonFormat(), and ParseOptions().
GetCommandName()
llvm::StringRef CommandObject::GetCommandName () const
Definition at line 81 of file CommandObject.cpp.
References m_cmd_name.
Referenced by lldb_private::CommandInterpreter::BuildAliasCommandArgs(), lldb_private::CommandInterpreter::BuildAliasResult(), CommandObjectCommandsDelete::DoExecute(), CommandObjectCommandsSource::DoExecute(), lldb_private::CommandObjectHelp::DoExecute(), lldb_private::CommandObjectMultiword::Execute(), lldb_private::CommandObjectParsed::Execute(), lldb_private::CommandObjectRaw::Execute(), lldb_private::Options::GenerateOptionUsage(), lldb_private::CommandInterpreter::GetAliasCommandObject(), GetSyntax(), lldb_private::CommandInterpreter::GetUserCommandObject(), lldb_private::CommandInterpreter::HandleCommand(), lldb_private::CommandInterpreter::IncreaseCommandUsage(), and lldb_private::CommandInterpreter::ResolveCommandImpl().
GetDebugger()
Debugger & CommandObject::GetDebugger ()
Definition at line 52 of file CommandObject.cpp.
References m_interpreter.
Referenced by lldb_private::CommandObjectDisassemble::CheckRangeSize(), CommandObjectScriptingObjectParsed::CommandObjectScriptingObjectParsed(), CommandObjectScriptingObjectRaw::CommandObjectScriptingObjectRaw(), CommandObjectCommandsScriptAdd::DoExecute(), CommandObjectCommandsScriptImport::DoExecute(), CommandObjectCommandsSource::DoExecute(), CommandObjectFrameRecognizerAdd::DoExecute(), CommandObjectFrameSelect::DoExecute(), CommandObjectLogDump::DoExecute(), CommandObjectLogEnable::DoExecute(), CommandObjectPlatformConnect::DoExecute(), CommandObjectPlatformDisconnect::DoExecute(), CommandObjectPlatformFClose::DoExecute(), CommandObjectPlatformFOpen::DoExecute(), CommandObjectPlatformFRead::DoExecute(), CommandObjectPlatformFWrite::DoExecute(), CommandObjectPlatformInstall::DoExecute(), CommandObjectPlatformMkDir::DoExecute(), CommandObjectPlatformProcessAttach::DoExecute(), CommandObjectPlatformProcessInfo::DoExecute(), CommandObjectPlatformProcessLaunch::DoExecute(), CommandObjectPlatformProcessList::DoExecute(), CommandObjectPlatformSelect::DoExecute(), CommandObjectPlatformSettings::DoExecute(), CommandObjectPlatformShell::DoExecute(), CommandObjectPlatformStatus::DoExecute(), CommandObjectPluginLoad::DoExecute(), CommandObjectProcessAttach::DoExecute(), CommandObjectProcessConnect::DoExecute(), CommandObjectProcessContinue::DoExecute(), CommandObjectProcessLaunch::DoExecute(), CommandObjectPythonFunction::DoExecute(), CommandObjectScriptingObjectParsed::DoExecute(), CommandObjectScriptingObjectRaw::DoExecute(), CommandObjectScriptingRun::DoExecute(), CommandObjectSettingsAppend::DoExecute(), CommandObjectSettingsClear::DoExecute(), CommandObjectSettingsInsertAfter::DoExecute(), CommandObjectSettingsInsertBefore::DoExecute(), CommandObjectSettingsList::DoExecute(), CommandObjectSettingsRemove::DoExecute(), CommandObjectSettingsReplace::DoExecute(), CommandObjectSettingsShow::DoExecute(), CommandObjectSettingsWrite::DoExecute(), CommandObjectSourceCacheClear::DoExecute(), CommandObjectSourceCacheDump::DoExecute(), CommandObjectSourceList::DoExecute(), CommandObjectStatsDump::DoExecute(), CommandObjectTargetCreate::DoExecute(), CommandObjectTargetDelete::DoExecute(), CommandObjectTargetDumpTypesystem::DoExecute(), CommandObjectTargetFrameProviderList::DoExecute(), CommandObjectTargetFrameProviderRegister::DoExecute(), CommandObjectTargetFrameProviderRemove::DoExecute(), CommandObjectTargetList::DoExecute(), CommandObjectTargetModulesDumpClangAST::DoExecute(), CommandObjectTargetModulesDumpLineTable::DoExecute(), CommandObjectTargetModulesDumpSections::DoExecute(), CommandObjectTargetModulesDumpSeparateDebugInfoFiles::DoExecute(), CommandObjectTargetModulesDumpSymfile::DoExecute(), CommandObjectTargetModulesDumpSymtab::DoExecute(), CommandObjectTargetSelect::DoExecute(), CommandObjectThreadStepWithTypeAndScope::DoExecute(), CommandObjectTraceLoad::DoExecute(), lldb_private::CommandObjectApropos::DoExecute(), lldb_private::CommandObjectDisassemble::DoExecute(), lldb_private::CommandObjectDWIMPrint::DoExecute(), lldb_private::CommandObjectGUI::DoExecute(), GenerateHelpText(), CommandObjectScriptingObjectParsed::GetHelp(), CommandObjectScriptingObjectRaw::GetHelp(), CommandObjectPythonFunction::GetHelpLong(), CommandObjectScriptingObjectParsed::GetHelpLong(), CommandObjectScriptingObjectRaw::GetHelpLong(), CommandObjectPlatformConnect::GetOptions(), CommandObjectScriptingObjectParsed::GetRepeatCommand(), CommandObjectScriptingObjectRaw::GetRepeatCommand(), CommandObjectScriptingObjectParsed::HandleArgumentCompletion(), CommandObjectThreadBacktrace::HandleOneThread(), HelpTextContainsWord(), CommandObjectCommandsScriptAdd::IOHandlerInputComplete(), CommandObjectTypeSummaryAdd::IOHandlerInputComplete(), CommandObjectTypeSynthAdd::IOHandlerInputComplete(), CommandObjectTargetModulesLookup::LookupInModule(), and CommandObjectTypeFilterAdd::CommandOptions::OptionParsingStarting().
GetDefaultThread()
Thread * CommandObject::GetDefaultThread () protected
Definition at line 775 of file CommandObject.cpp.
References lldb_private::Target::GetProcessSP(), lldb_private::ThreadList::GetSelectedThread(), lldb_private::Process::GetThreadList(), m_exe_ctx, and m_interpreter.
Referenced by CommandObjectProcessContinue::DoExecute(), CommandObjectThreadContinue::DoExecute(), CommandObjectThreadStepWithTypeAndScope::DoExecute(), CommandObjectThreadUntil::DoExecute(), and lldb_private::ctf::CommandObjectThreadTraceExportCTF::DoExecute().
GetDummyTarget()
Target & CommandObject::GetDummyTarget () protected
Definition at line 752 of file CommandObject.cpp.
References m_interpreter.
Referenced by CommandObjectBreakpointAddException::DoExecute(), CommandObjectBreakpointAddFile::DoExecute(), CommandObjectBreakpointAddName::DoExecute(), CommandObjectBreakpointAddPattern::DoExecute(), CommandObjectBreakpointAddScripted::DoExecute(), CommandObjectBreakpointCommandDelete::DoExecute(), CommandObjectBreakpointDelete::DoExecute(), CommandObjectBreakpointList::DoExecute(), CommandObjectBreakpointModify::DoExecute(), CommandObjectBreakpointNameAdd::DoExecute(), CommandObjectBreakpointNameDelete::DoExecute(), CommandObjectBreakpointNameList::DoExecute(), CommandObjectBreakpointSet::DoExecute(), CommandObjectProcessHandle::DoExecute(), lldb_private::CommandObjectDWIMPrint::DoExecute(), and GetTarget().
GetFlags() [1/2]
Flags & lldb_private::CommandObject::GetFlags () inline
The flags accessor.
Returns
A reference to the Flags member variable.
Definition at line 288 of file CommandObject.h.
References m_flags.
Referenced by CheckRequirements(), CommandObjectScriptingObjectParsed::CommandObjectScriptingObjectParsed(), and CommandObjectScriptingObjectRaw::CommandObjectScriptingObjectRaw().
GetFlags() [2/2]
const Flags & lldb_private::CommandObject::GetFlags () const inline
The flags const accessor.
Returns
A const reference to the Flags member variable.
Definition at line 294 of file CommandObject.h.
References m_flags.
GetFormattedCommandArguments()
void CommandObject::GetFormattedCommandArguments (Stream & str, uint32_t opt_set_mask = LLDB_OPT_SET_ALL)
Definition at line 530 of file CommandObject.cpp.
References lldb_private::eArgRepeatOptional, lldb_private::eArgRepeatPairOptional, lldb_private::eArgRepeatPairPlain, lldb_private::eArgRepeatPairPlus, lldb_private::eArgRepeatPairRange, lldb_private::eArgRepeatPairRangeOptional, lldb_private::eArgRepeatPairStar, lldb_private::eArgRepeatPlain, lldb_private::eArgRepeatPlus, lldb_private::eArgRepeatRange, lldb_private::eArgRepeatStar, GetArgumentName(), lldb_private::StreamString::GetString(), IsPairType(), LLDB_OPT_SET_ALL, m_arguments, OptSetFiltered(), and lldb_private::Stream::Printf().
Referenced by lldb_private::Options::GenerateOptionUsage(), and GetSyntax().
GetHelp()
llvm::StringRef CommandObject::GetHelp () virtual
Reimplemented in CommandObjectScriptingObjectParsed, CommandObjectScriptingObjectRaw, lldb_private::CommandAlias, and lldb_private::CommandObjectProxy.
Definition at line 54 of file CommandObject.cpp.
References m_cmd_help_short.
Referenced by lldb_private::CommandInterpreter::FindCommandsForApropos(), GenerateHelpText(), lldb_private::CommandInterpreter::GetAliasCommandObject(), CommandObjectScriptingObjectParsed::GetHelp(), CommandObjectScriptingObjectRaw::GetHelp(), lldb_private::CommandObjectProxy::GetHelp(), lldb_private::CommandInterpreter::GetUserCommandObject(), and HelpTextContainsWord().
GetHelpLong()
llvm::StringRef CommandObject::GetHelpLong () virtual
Reimplemented in CommandObjectPythonFunction, CommandObjectScriptingObjectParsed, CommandObjectScriptingObjectRaw, CommandObjectTypeLookup, lldb_private::CommandAlias, and lldb_private::CommandObjectProxy.
Definition at line 56 of file CommandObject.cpp.
References m_cmd_help_long.
Referenced by GenerateHelpText(), CommandObjectPythonFunction::GetHelpLong(), CommandObjectScriptingObjectParsed::GetHelpLong(), CommandObjectScriptingObjectRaw::GetHelpLong(), lldb_private::CommandObjectProxy::GetHelpLong(), and HelpTextContainsWord().
GetInvalidFrameDescription()
virtual const char * lldb_private::CommandObject::GetInvalidFrameDescription () inline protected virtual
Definition at line 371 of file CommandObject.h.
Referenced by CheckRequirements().
GetInvalidProcessDescription()
virtual const char * lldb_private::CommandObject::GetInvalidProcessDescription () inline protected virtual
Definition at line 363 of file CommandObject.h.
Referenced by CheckRequirements().
GetInvalidRegContextDescription()
virtual const char * lldb_private::CommandObject::GetInvalidRegContextDescription () inline protected virtual
Definition at line 375 of file CommandObject.h.
Referenced by CheckRequirements().
GetInvalidTargetDescription()
virtual const char * lldb_private::CommandObject::GetInvalidTargetDescription () inline protected virtual
Definition at line 359 of file CommandObject.h.
Referenced by CheckRequirements().
GetInvalidThreadDescription()
virtual const char * lldb_private::CommandObject::GetInvalidThreadDescription () inline protected virtual
Definition at line 367 of file CommandObject.h.
Referenced by CheckRequirements().
GetNumArgumentEntries()
int CommandObject::GetNumArgumentEntries ()
Definition at line 407 of file CommandObject.cpp.
References m_arguments.
Referenced by GenerateHelpText(), and HandleArgumentCompletion().
GetOptions()
Options * CommandObject::GetOptions () virtual
Reimplemented in CommandObjectBreakpointAddAddress, CommandObjectBreakpointAddException, CommandObjectBreakpointAddFile, CommandObjectBreakpointAddName, CommandObjectBreakpointAddPattern, CommandObjectBreakpointAddScripted, CommandObjectBreakpointClear, CommandObjectBreakpointCommandAdd, CommandObjectBreakpointCommandDelete, CommandObjectBreakpointDelete, CommandObjectBreakpointList, CommandObjectBreakpointModify, CommandObjectBreakpointNameAdd, CommandObjectBreakpointNameConfigure, CommandObjectBreakpointNameDelete, CommandObjectBreakpointNameList, CommandObjectBreakpointRead, CommandObjectBreakpointSet, CommandObjectBreakpointWrite, CommandObjectCommandsAddRegex, CommandObjectCommandsAlias, CommandObjectCommandsContainerAdd, CommandObjectCommandsScriptAdd, CommandObjectCommandsScriptImport, CommandObjectCommandsSource, CommandObjectDiagnosticsDump, CommandObjectFrameDiagnose, CommandObjectFrameRecognizerAdd, CommandObjectFrameSelect, CommandObjectFrameVariable, CommandObjectLogDump, CommandObjectLogEnable, CommandObjectMemoryFind, CommandObjectMemoryRead, CommandObjectMemoryRegion, CommandObjectMemoryTagWrite, CommandObjectMemoryWrite, CommandObjectObjC_ClassTable_Dump, CommandObjectPlatformConnect, CommandObjectPlatformFOpen, CommandObjectPlatformFRead, CommandObjectPlatformFWrite, CommandObjectPlatformMkDir, CommandObjectPlatformProcessAttach, CommandObjectPlatformProcessLaunch, CommandObjectPlatformProcessList, CommandObjectPlatformSelect, CommandObjectPlatformSettings, CommandObjectPlatformShell, CommandObjectPluginList, CommandObjectProcessAttach, CommandObjectProcessConnect, CommandObjectProcessContinue, CommandObjectProcessDetach, CommandObjectProcessGDBRemoteSpeedTest, CommandObjectProcessHandle, CommandObjectProcessKDPPacketSend, CommandObjectProcessLaunch, CommandObjectProcessLoad, CommandObjectProcessMinidumpDump, CommandObjectProcessSaveCore, CommandObjectProcessStatus, CommandObjectRegisterRead, CommandObjectScriptingExtensionList, CommandObjectScriptingObjectParsed, CommandObjectScriptingRun, CommandObjectSessionHistory, CommandObjectSettingsClear, CommandObjectSettingsRead, CommandObjectSettingsSet, CommandObjectSettingsShow, CommandObjectSettingsWrite, CommandObjectSourceInfo, CommandObjectSourceList, CommandObjectStatsDump, CommandObjectTargetCreate, CommandObjectTargetDelete, CommandObjectTargetFrameProviderRegister, CommandObjectTargetModulesAdd, CommandObjectTargetModulesDumpClangAST, CommandObjectTargetModulesDumpLineTable, CommandObjectTargetModulesDumpSeparateDebugInfoFiles, CommandObjectTargetModulesDumpSymtab, CommandObjectTargetModulesList, CommandObjectTargetModulesLoad, CommandObjectTargetModulesLookup, CommandObjectTargetModulesShowUnwind, CommandObjectTargetStopHookAdd, CommandObjectTargetStopHookList, CommandObjectTargetSymbolsAdd, CommandObjectTargetVariable, CommandObjectThreadBacktrace, CommandObjectThreadInfo, CommandObjectThreadJump, CommandObjectThreadPlanList, CommandObjectThreadReturn, CommandObjectThreadSelect, CommandObjectThreadStepWithTypeAndScope, CommandObjectThreadUntil, CommandObjectTraceDump, CommandObjectTraceDumpFunctionCalls, CommandObjectTraceDumpInfo, CommandObjectTraceDumpInstructions, CommandObjectTraceLoad, CommandObjectTraceSave, CommandObjectTraceSchema, CommandObjectTypeCategoryDefine, CommandObjectTypeCategoryDisable, CommandObjectTypeCategoryEnable, CommandObjectTypeFilterAdd, CommandObjectTypeFormatAdd, CommandObjectTypeFormatterClear, CommandObjectTypeFormatterDelete, CommandObjectTypeFormatterList< FormatterType >, CommandObjectTypeFormatterList< SyntheticChildren >, CommandObjectTypeFormatterList< TypeFilterImpl >, CommandObjectTypeFormatterList< TypeFormatImpl >, CommandObjectTypeFormatterList< TypeSummaryImpl >, CommandObjectTypeLookup, CommandObjectTypeSummaryAdd, CommandObjectTypeSynthAdd, CommandObjectWatchpointCommandAdd, CommandObjectWatchpointDelete, CommandObjectWatchpointIgnore, CommandObjectWatchpointList, CommandObjectWatchpointModify, CommandObjectWatchpointSetExpression, CommandObjectWatchpointSetVariable, lldb_private::CommandAlias, lldb_private::CommandObjectDisassemble, lldb_private::CommandObjectDWIMPrint, lldb_private::CommandObjectExpression, lldb_private::CommandObjectHelp, lldb_private::CommandObjectProxy, lldb_private::CommandObjectVersion, lldb_private::ctf::CommandObjectThreadTraceExportCTF, lldb_private::trace_intel_pt::CommandObjectProcessTraceStartIntelPT, lldb_private::trace_intel_pt::CommandObjectThreadTraceStartIntelPT, and sddarwinlog_private::EnableCommand.
Definition at line 99 of file CommandObject.cpp.
Referenced by GenerateHelpText(), lldb_private::CommandObjectProxy::GetOptions(), GetSyntax(), HandleCompletion(), HelpTextContainsWord(), ParseOptions(), and lldb_private::CommandInterpreter::ResolveCommandImpl().
GetRepeatCommand()
virtual std::optional< std::string > lldb_private::CommandObject::GetRepeatCommand (Args & current_command_args, uint32_t index) inline virtual
Get the command that appropriate for a "repeat" of the current command.
Parameters
[in] current_command_args The command arguments.
[in] index This is for internal use - it is how the completion request is tracked in CommandObjectMultiword, and should otherwise be ignored.
Returns
std::nullopt if there is no special repeat command - it will use the current command line. Otherwise a std::string containing the command to be repeated. If the string is empty, the command won't be allow repeating.
Reimplemented in CommandObjectCommandsSource, CommandObjectMemoryHistory, CommandObjectMemoryRead, CommandObjectMemoryRegion, CommandObjectProcessLaunch, CommandObjectScriptingObjectParsed, CommandObjectScriptingObjectRaw, CommandObjectSourceList, CommandObjectTargetFrameProviderRegister, CommandObjectThreadBacktrace, CommandObjectTraceDumpInstructions, lldb_private::CommandObjectMultiword, lldb_private::CommandObjectProxy, and lldb_private::CommandPluginInterfaceImplementation.
Definition at line 311 of file CommandObject.h.
Referenced by lldb_private::CommandObjectMultiword::GetRepeatCommand(), lldb_private::CommandObjectProxy::GetRepeatCommand(), and lldb_private::CommandInterpreter::HandleCommand().
GetSubcommandObject()
virtual CommandObject * lldb_private::CommandObject::GetSubcommandObject (llvm::StringRef sub_cmd, StringList * matches = nullptr) inline virtual
Reimplemented in lldb_private::CommandObjectMultiword, and lldb_private::CommandObjectProxy.
Definition at line 171 of file CommandObject.h.
References CommandObject().
Referenced by lldb_private::CommandObjectHelp::DoExecute(), lldb_private::CommandInterpreter::GetCommandObjectForCommand(), lldb_private::CommandObjectProxy::GetSubcommandObject(), and lldb_private::CommandInterpreter::ResolveCommandImpl().
GetSubcommandSP()
virtual lldb::CommandObjectSP lldb_private::CommandObject::GetSubcommandSP (llvm::StringRef sub_cmd, StringList * matches = nullptr) inline virtual
Reimplemented in lldb_private::CommandObjectMultiword, and lldb_private::CommandObjectProxy.
Definition at line 162 of file CommandObject.h.
Referenced by lldb_private::CommandObjectProxy::GetSubcommandSP().
GetSubcommandSPExact()
virtual lldb::CommandObjectSP lldb_private::CommandObject::GetSubcommandSPExact (llvm::StringRef sub_cmd) inline virtual
Reimplemented in lldb_private::CommandObjectMultiword.
Definition at line 167 of file CommandObject.h.
GetSyntax()
llvm::StringRef CommandObject::GetSyntax () virtual
Reimplemented in lldb_private::CommandObjectProxy.
Definition at line 58 of file CommandObject.cpp.
References GetCommandName(), GetFormattedCommandArguments(), GetOptions(), lldb_private::StreamString::GetString(), IsDashDashCommand(), m_arguments, m_cmd_syntax, lldb_private::Stream::PutCString(), and WantsRawCommandString().
Referenced by CommandObjectPlatformShell::DoExecute(), CommandObjectThreadUntil::DoExecute(), lldb_private::CommandObjectRegexCommand::DoExecute(), GenerateHelpText(), lldb_private::CommandObjectProxy::GetSyntax(), and HelpTextContainsWord().
GetTarget()
Target & CommandObject::GetTarget () protected
Definition at line 756 of file CommandObject.cpp.
References GetDummyTarget(), m_exe_ctx, and m_interpreter.
Referenced by lldb_private::CommandObjectDisassemble::CheckRangeSize(), CommandObjectSourceList::DisplayFunctionSource(), CommandObjectBreakpointAddException::DoExecute(), CommandObjectBreakpointAddFile::DoExecute(), CommandObjectBreakpointAddName::DoExecute(), CommandObjectBreakpointAddPattern::DoExecute(), CommandObjectBreakpointAddScripted::DoExecute(), CommandObjectBreakpointClear::DoExecute(), CommandObjectBreakpointCommandDelete::DoExecute(), CommandObjectBreakpointCommandList::DoExecute(), CommandObjectBreakpointDelete::DoExecute(), CommandObjectBreakpointEnable::DoExecute(), CommandObjectBreakpointList::DoExecute(), CommandObjectBreakpointModify::DoExecute(), CommandObjectBreakpointNameAdd::DoExecute(), CommandObjectBreakpointNameConfigure::DoExecute(), CommandObjectBreakpointNameDelete::DoExecute(), CommandObjectBreakpointNameList::DoExecute(), CommandObjectBreakpointRead::DoExecute(), CommandObjectBreakpointSet::DoExecute(), CommandObjectBreakpointWrite::DoExecute(), CommandObjectFrameRecognizerAdd::DoExecute(), CommandObjectFrameRecognizerClear::DoExecute(), CommandObjectFrameRecognizerInfo::DoExecute(), CommandObjectFrameRecognizerList::DoExecute(), CommandObjectProcessContinue::DoExecute(), CommandObjectProcessHandle::DoExecute(), CommandObjectSourceInfo::DoExecute(), CommandObjectSourceList::DoExecute(), CommandObjectTargetDumpSectionLoadList::DoExecute(), CommandObjectTargetDumpTypesystem::DoExecute(), CommandObjectTargetModulesAdd::DoExecute(), CommandObjectTargetModulesDumpClangAST::DoExecute(), CommandObjectTargetModulesDumpObjfile::DoExecute(), CommandObjectTargetModulesDumpSections::DoExecute(), CommandObjectTargetModulesDumpSeparateDebugInfoFiles::DoExecute(), CommandObjectTargetModulesDumpSymfile::DoExecute(), CommandObjectTargetModulesDumpSymtab::DoExecute(), CommandObjectTargetModulesList::DoExecute(), CommandObjectTargetModulesLoad::DoExecute(), CommandObjectTargetModulesLookup::DoExecute(), CommandObjectTargetModulesSearchPathsAdd::DoExecute(), CommandObjectTargetModulesSearchPathsClear::DoExecute(), CommandObjectTargetModulesSearchPathsInsert::DoExecute(), CommandObjectTargetModulesSearchPathsList::DoExecute(), CommandObjectTargetModulesSearchPathsQuery::DoExecute(), CommandObjectTargetStopHookEnableDisable::DoExecute(), CommandObjectTargetStopHookList::DoExecute(), CommandObjectThreadUntil::DoExecute(), CommandObjectWatchpointCommandDelete::DoExecute(), CommandObjectWatchpointCommandList::DoExecute(), CommandObjectWatchpointDelete::DoExecute(), CommandObjectWatchpointDisable::DoExecute(), CommandObjectWatchpointEnable::DoExecute(), CommandObjectWatchpointIgnore::DoExecute(), CommandObjectWatchpointList::DoExecute(), CommandObjectWatchpointModify::DoExecute(), lldb_private::CommandObjectDisassemble::DoExecute(), sddarwinlog_private::EnableCommand::DoExecute(), sddarwinlog_private::StatusCommand::DoExecute(), CommandObjectFrameRecognizerDelete::DoExecuteWithId(), CommandObjectFrameRecognizerDisable::DoExecuteWithId(), CommandObjectFrameRecognizerEnable::DoExecuteWithId(), CommandObjectSourceInfo::DumpFileLinesInCompUnit(), CommandObjectSourceInfo::DumpLinesForAddress(), CommandObjectSourceInfo::DumpLinesForFile(), CommandObjectSourceInfo::DumpLinesInFunctions(), CommandObjectSourceInfo::DumpLinesInSymbolContexts(), lldb_private::CommandObjectDisassemble::GetContainingAddressRanges(), lldb_private::CommandObjectDisassemble::GetNameRanges(), CommandObjectSourceInfo::GetSymbolContextsForAddress(), CommandObjectWithFrameRecognizerArg::HandleArgumentCompletion(), CommandObjectTargetModulesLookup::LookupHere(), and CommandObjectTargetModulesLookup::LookupInModule().
HandleArgumentCompletion()
void CommandObject::HandleArgumentCompletion (CompletionRequest & request, OptionElementVector & opt_element_vector) virtual
The default version handles argument definitions that have only one argument type, and use one of the argument types that have an entry in the CommonCompletions.
Override this if you have a more complex argument setup. FIXME: we should be able to extend this to more complex argument definitions provided we have completers for all the argument types.
The input array contains a parsed version of the line.
We've constructed the map of options and their arguments as well if that is helpful for the completion.
Parameters
[in,out] request The completion request that needs to be answered.
Reimplemented in CommandObjectBreakpointDelete, CommandObjectBreakpointDisable, CommandObjectBreakpointEnable, CommandObjectBreakpointModify, CommandObjectBreakpointNameAdd, CommandObjectBreakpointNameDelete, CommandObjectBreakpointWrite, CommandObjectCommandsContainerAdd, CommandObjectCommandsContainerDelete, CommandObjectCommandsDelete, CommandObjectCommandsScriptAdd, CommandObjectCommandsScriptDelete, CommandObjectCommandsUnalias, CommandObjectLogDisable, CommandObjectLogDump, CommandObjectLogEnable, CommandObjectLogList, CommandObjectLogTimerIncrement, CommandObjectPlatformGetFile, CommandObjectPlatformInstall, CommandObjectPlatformProcessLaunch, CommandObjectPlatformPutFile, CommandObjectPluginDisable, CommandObjectPluginEnable, CommandObjectPluginList, CommandObjectProcessLoad, CommandObjectProcessSignal, CommandObjectProcessUnload, CommandObjectPythonFunction, CommandObjectRegisterInfo, CommandObjectRegisterRead, CommandObjectRegisterWrite, CommandObjectScriptingObjectParsed, CommandObjectScriptingObjectRaw, CommandObjectSettingsAppend, CommandObjectSettingsClear, CommandObjectSettingsInsertAfter, CommandObjectSettingsInsertBefore, CommandObjectSettingsList, CommandObjectSettingsRemove, CommandObjectSettingsReplace, CommandObjectSettingsSet, CommandObjectTargetModulesModuleAutoComplete, CommandObjectTargetModulesSearchPathsInsert, CommandObjectTargetModulesSourceFileAutoComplete, CommandObjectTargetStopHookDelete, CommandObjectTargetStopHookEnableDisable, CommandObjectThreadException, CommandObjectThreadInfo, CommandObjectThreadPlanDiscard, CommandObjectThreadSelect, CommandObjectThreadSiginfo, CommandObjectThreadStepWithTypeAndScope, CommandObjectTraceLoad, CommandObjectTraceSave, CommandObjectTypeCategoryList, CommandObjectTypeFormatterDelete, CommandObjectWatchpointDelete, CommandObjectWatchpointDisable, CommandObjectWatchpointEnable, CommandObjectWatchpointIgnore, CommandObjectWatchpointModify, CommandObjectWithFrameRecognizerArg, lldb_private::CommandAlias, and lldb_private::CommandObjectProxy.
Definition at line 304 of file CommandObject.cpp.
References lldb_private::CommandObject::ArgumentTableEntry::completion_type, lldb_private::eArgRepeatPlain, lldb::eNoCompletion, FindArgumentDataByType(), GetArgumentEntryAtIndex(), GetCommandInterpreter(), lldb_private::CompletionRequest::GetCursorIndex(), GetNumArgumentEntries(), and lldb_private::CommandCompletions::InvokeCommonCompletionCallbacks().
Referenced by CommandObjectTargetStopHookDelete::DoExecute(), CommandObjectProcessLoad::HandleArgumentCompletion(), CommandObjectRegisterRead::HandleArgumentCompletion(), CommandObjectScriptingObjectParsed::HandleArgumentCompletion(), CommandObjectTargetStopHookEnableDisable::HandleArgumentCompletion(), CommandObjectThreadStepWithTypeAndScope::HandleArgumentCompletion(), lldb_private::CommandObjectProxy::HandleArgumentCompletion(), and HandleCompletion().
HandleCompletion()
void CommandObject::HandleCompletion (CompletionRequest & request) virtual
This default version handles calling option argument completions and then calls HandleArgumentCompletion if the cursor is on an argument, not an option.
Don't override this method, override HandleArgumentCompletion instead unless you have special reasons.
Parameters
[in,out] request The completion request that needs to be answered.
Reimplemented in CommandObjectPlatformSelect, lldb_private::CommandAlias, lldb_private::CommandObjectExpression, lldb_private::CommandObjectHelp, lldb_private::CommandObjectMultiword, lldb_private::CommandObjectProxy, and lldb_private::CommandObjectRegexCommand.
Definition at line 272 of file CommandObject.cpp.
References Cleanup(), GetCommandInterpreter(), lldb_private::CompletionRequest::GetCursorIndex(), GetOptions(), lldb_private::CompletionRequest::GetParsedLine(), HandleArgumentCompletion(), lldb_private::Options::HandleOptionCompletion(), m_exe_ctx, m_interpreter, lldb_private::Options::ParseForCompletion(), WantsCompletion(), and WantsRawCommandString().
Referenced by lldb_private::CommandObjectHelp::HandleCompletion(), lldb_private::CommandObjectMultiword::HandleCompletion(), lldb_private::CommandObjectProxy::HandleCompletion(), and lldb_private::CommandInterpreter::HandleCompletionMatches().
HasOverrideCallback()
bool lldb_private::CommandObject::HasOverrideCallback () const inline
Definition at line 315 of file CommandObject.h.
References m_command_override_callback, and m_deprecated_command_override_callback.
Referenced by lldb_private::CommandObjectParsed::Execute(), and lldb_private::CommandObjectRaw::Execute().
HelpTextContainsWord()
bool CommandObject::HelpTextContainsWord (llvm::StringRef search_word, bool search_short_help = true, bool search_long_help = true, bool search_syntax = true, bool search_options = true)
Definition at line 340 of file CommandObject.cpp.
References lldb_private::StreamString::Empty(), lldb_private::Options::GenerateOptionUsage(), GetCommandInterpreter(), GetDebugger(), GetHelp(), GetHelpLong(), GetOptions(), lldb_private::StreamString::GetString(), and GetSyntax().
Referenced by lldb_private::CommandInterpreter::FindCommandsForApropos().
InvokeOverrideCallback()
bool lldb_private::CommandObject::InvokeOverrideCallback (const char ** argv, CommandReturnObject & result) inline
Definition at line 333 of file CommandObject.h.
References m_command_override_baton, m_command_override_callback, and m_deprecated_command_override_callback.
Referenced by lldb_private::CommandObjectParsed::Execute(), and lldb_private::CommandObjectRaw::Execute().
IsAlias()
virtual bool lldb_private::CommandObject::IsAlias () inline virtual
Reimplemented in lldb_private::CommandAlias.
Definition at line 155 of file CommandObject.h.
Referenced by lldb_private::CommandInterpreter::BuildAliasResult(), lldb_private::CommandObjectHelp::DoExecute(), and lldb_private::CommandInterpreter::ResolveCommandImpl().
IsDashDashCommand()
virtual bool lldb_private::CommandObject::IsDashDashCommand () inline virtual
Reimplemented in lldb_private::CommandAlias.
Definition at line 160 of file CommandObject.h.
Referenced by GenerateHelpText(), lldb_private::Options::GenerateOptionUsage(), and GetSyntax().
IsMultiwordObject()
virtual bool lldb_private::CommandObject::IsMultiwordObject () inline virtual
Reimplemented in lldb_private::CommandObjectMultiword, and lldb_private::CommandObjectProxy.
Definition at line 147 of file CommandObject.h.
Referenced by lldb_private::CommandObjectHelp::DoExecute(), lldb_private::CommandInterpreter::GetCommandObjectForCommand(), lldb_private::CommandInterpreter::HandleCompletionMatches(), lldb_private::LanguageRuntime::InitializeCommands(), lldb_private::CommandObjectProxy::IsMultiwordObject(), and lldb_private::CommandInterpreter::ResolveCommandImpl().
IsPairType()
bool CommandObject::IsPairType (ArgumentRepetitionType arg_repeat_type) static
Definition at line 490 of file CommandObject.cpp.
References lldb_private::eArgRepeatPairOptional, lldb_private::eArgRepeatPairPlain, lldb_private::eArgRepeatPairPlus, lldb_private::eArgRepeatPairRange, lldb_private::eArgRepeatPairRangeOptional, and lldb_private::eArgRepeatPairStar.
Referenced by GetFormattedCommandArguments().
IsRemovable()
virtual bool lldb_private::CommandObject::IsRemovable () const inline virtual
Reimplemented in CommandObjectPythonFunction, CommandObjectScriptingObjectParsed, CommandObjectScriptingObjectRaw, lldb_private::CommandObjectMultiword, lldb_private::CommandObjectProxy, lldb_private::CommandObjectRegexCommand, and lldb_private::CommandPluginInterfaceImplementation.
Definition at line 145 of file CommandObject.h.
Referenced by CommandObjectCommandsUnalias::DoExecute(), and lldb_private::CommandObjectProxy::IsRemovable().
IsUserCommand()
bool lldb_private::CommandObject::IsUserCommand () inline
Definition at line 149 of file CommandObject.h.
References m_is_user_command.
Referenced by lldb_private::CommandObjectMultiword::LoadUserSubcommand().
LoadSubCommand()
virtual bool lldb_private::CommandObject::LoadSubCommand (llvm::StringRef cmd_name, const lldb::CommandObjectSP & command_obj) inline virtual
Reimplemented in lldb_private::CommandObjectMultiword, and lldb_private::CommandObjectProxy.
Definition at line 185 of file CommandObject.h.
Referenced by lldb_private::LanguageRuntime::InitializeCommands(), and lldb_private::CommandObjectProxy::LoadSubCommand().
LoadUserSubcommand()
virtual llvm::Error lldb_private::CommandObject::LoadUserSubcommand (llvm::StringRef cmd_name, const lldb::CommandObjectSP & command_obj, bool can_replace) inline virtual
Reimplemented in lldb_private::CommandObjectMultiword.
Definition at line 190 of file CommandObject.h.
LookupArgumentName()
CommandArgumentType CommandObject::LookupArgumentName (llvm::StringRef arg_name) static
Definition at line 625 of file CommandObject.cpp.
References lldb::eArgTypeLastArg, and lldb_private::g_argument_table.
Referenced by lldb_private::CommandObjectHelp::DoExecute().
ParseOptions()
bool CommandObject::ParseOptions (Args & args, CommandReturnObject & result)
Definition at line 105 of file CommandObject.cpp.
References lldb::eReturnStatusFailed, lldb::eReturnStatusSuccessFinishNoResult, error(), lldb_private::Status::FromError(), GetCommandInterpreter(), lldb_private::CommandInterpreter::GetExecutionContext(), GetOptions(), lldb_private::Options::NotifyOptionParsingFinished(), lldb_private::Options::NotifyOptionParsingStarting(), lldb_private::Options::Parse(), lldb_private::CommandReturnObject::SetError(), lldb_private::CommandReturnObject::SetStatus(), and lldb_private::Options::VerifyOptions().
Referenced by CommandObjectPlatformShell::DoExecute(), CommandObjectScriptingRun::DoExecute(), CommandObjectSettingsRemove::DoExecute(), lldb_private::CommandObjectParsed::Execute(), and ParseOptionsAndNotify().
ParseOptionsAndNotify()
bool CommandObject::ParseOptionsAndNotify (Args & args, CommandReturnObject & result, OptionGroupOptions & group_options, ExecutionContext & exe_ctx) protected
Definition at line 374 of file CommandObject.cpp.
References lldb_private::CommandReturnObject::AppendError(), error(), lldb_private::Options::NotifyOptionParsingFinished(), and ParseOptions().
Referenced by CommandObjectBreakpointAddPattern::DoExecute(), and lldb_private::CommandObjectDWIMPrint::DoExecute().
SetCommandName()
void CommandObject::SetCommandName (llvm::StringRef name)
Definition at line 83 of file CommandObject.cpp.
References m_cmd_name.
Referenced by CommandObjectTypeFormat::CommandObjectTypeFormat(), and CommandObjectTypeFormatterDelete::CommandObjectTypeFormatterDelete().
SetHelp()
void CommandObject::SetHelp (llvm::StringRef str) virtual
Reimplemented in lldb_private::CommandAlias.
Definition at line 87 of file CommandObject.cpp.
References m_cmd_help_short.
Referenced by CommandObjectPythonFunction::CommandObjectPythonFunction(), CommandObjectScriptingObjectRaw::CommandObjectScriptingObjectRaw(), CommandObjectTypeFormat::CommandObjectTypeFormat(), CommandObjectTypeFormatterDelete::CommandObjectTypeFormatterDelete(), CommandObjectScriptingObjectParsed::GetHelp(), CommandObjectScriptingObjectRaw::GetHelp(), and lldb_private::CommandAlias::SetHelp().
SetHelpLong()
void CommandObject::SetHelpLong (llvm::StringRef str) virtual
Reimplemented in lldb_private::CommandAlias.
Definition at line 91 of file CommandObject.cpp.
References m_cmd_help_long.
Referenced by CommandObjectBreakpointAdd::CommandObjectBreakpointAdd(), CommandObjectBreakpointCommandAdd::CommandObjectBreakpointCommandAdd(), CommandObjectBreakpointDisable::CommandObjectBreakpointDisable(), CommandObjectBreakpointName::CommandObjectBreakpointName(), CommandObjectCommandsAddRegex::CommandObjectCommandsAddRegex(), CommandObjectCommandsAlias::CommandObjectCommandsAlias(), lldb_private::CommandObjectExpression::CommandObjectExpression(), CommandObjectFrameRecognizerAdd::CommandObjectFrameRecognizerAdd(), CommandObjectFrameVariable::CommandObjectFrameVariable(), lldb_private::CommandObjectLanguage::CommandObjectLanguage(), CommandObjectPlatformFileExists::CommandObjectPlatformFileExists(), CommandObjectPlatformGetFile::CommandObjectPlatformGetFile(), CommandObjectPlatformGetPermissions::CommandObjectPlatformGetPermissions(), CommandObjectPlatformGetSize::CommandObjectPlatformGetSize(), CommandObjectPlatformPutFile::CommandObjectPlatformPutFile(), CommandObjectPluginList::CommandObjectPluginList(), CommandObjectProcessHandle::CommandObjectProcessHandle(), CommandObjectRegisterInfo::CommandObjectRegisterInfo(), CommandObjectSettingsSet::CommandObjectSettingsSet(), CommandObjectTargetStopHookAdd::CommandObjectTargetStopHookAdd(), CommandObjectTargetStopHookDelete::CommandObjectTargetStopHookDelete(), CommandObjectTypeFormatAdd::CommandObjectTypeFormatAdd(), CommandObjectTypeFormatterDelete::CommandObjectTypeFormatterDelete(), CommandObjectTypeSummaryAdd::CommandObjectTypeSummaryAdd(), CommandObjectWatchpointCommandAdd::CommandObjectWatchpointCommandAdd(), CommandObjectWatchpointSetExpression::CommandObjectWatchpointSetExpression(), CommandObjectWatchpointSetVariable::CommandObjectWatchpointSetVariable(), CommandObjectPythonFunction::GetHelpLong(), CommandObjectScriptingObjectParsed::GetHelpLong(), CommandObjectScriptingObjectRaw::GetHelpLong(), and lldb_private::CommandAlias::SetHelpLong().
SetIsUserCommand()
void lldb_private::CommandObject::SetIsUserCommand (bool is_user) inline
Definition at line 151 of file CommandObject.h.
References m_is_user_command.
SetOriginalCommandString()
void lldb_private::CommandObject::SetOriginalCommandString (std::string s) inline
Set the command input as it appeared in the terminal.
This is used to have errors refer directly to the original command.
Definition at line 346 of file CommandObject.h.
References m_original_command.
Referenced by lldb_private::CommandInterpreter::HandleCommand().
SetOverrideCallback() [1/2]
void lldb_private::CommandObject::SetOverrideCallback (lldb::CommandOverrideCallback callback, void * baton) inline
Definition at line 320 of file CommandObject.h.
References m_command_override_baton, and m_deprecated_command_override_callback.
Referenced by lldb_private::REPL::RunLoop(), and lldb::SBCommandInterpreter::SetCommandOverrideCallback().
SetOverrideCallback() [2/2]
void lldb_private::CommandObject::SetOverrideCallback (lldb_private::CommandOverrideCallbackWithResult callback, void * baton) inline
Definition at line 327 of file CommandObject.h.
References m_command_override_baton, and m_command_override_callback.
SetSyntax()
void CommandObject::SetSyntax (llvm::StringRef str)
Definition at line 95 of file CommandObject.cpp.
References m_cmd_syntax.
Referenced by CommandObjectTypeFormat::CommandObjectTypeFormat(), and lldb_private::CommandInterpreter::Initialize().
WantsCompletion()
virtual bool lldb_private::CommandObject::WantsCompletion () inline virtual
Reimplemented in CommandObjectPythonFunction, CommandObjectScriptingObjectParsed, CommandObjectScriptingObjectRaw, CommandObjectSettingsAppend, CommandObjectSettingsInsertAfter, CommandObjectSettingsInsertBefore, CommandObjectSettingsRemove, CommandObjectSettingsReplace, CommandObjectSettingsSet, CommandObjectWatchpointSetExpression, lldb_private::CommandAlias, lldb_private::CommandObjectDWIMPrint, and lldb_private::CommandObjectProxy.
Definition at line 202 of file CommandObject.h.
References WantsRawCommandString().
Referenced by GenerateHelpText(), HandleCompletion(), and lldb_private::CommandObjectProxy::WantsCompletion().
WantsRawCommandString()
virtual bool lldb_private::CommandObject::WantsRawCommandString () pure virtual
Implemented in lldb_private::CommandAlias, lldb_private::CommandObjectMultiword, lldb_private::CommandObjectParsed, lldb_private::CommandObjectProxy, and lldb_private::CommandObjectRaw.
Referenced by lldb_private::CommandInterpreter::BuildAliasCommandArgs(), GenerateHelpText(), lldb_private::Options::GenerateOptionUsage(), GetSyntax(), lldb_private::CommandInterpreter::HandleCommand(), HandleCompletion(), lldb_private::CommandInterpreter::ResolveCommandImpl(), WantsCompletion(), and lldb_private::CommandObjectProxy::WantsRawCommandString().
Member Data Documentation
m_api_locker
std::unique_lock<std::recursive_mutex> lldb_private::CommandObject::m_api_locker protected
Definition at line 410 of file CommandObject.h.
Referenced by CheckRequirements(), and Cleanup().
m_arguments
std::vector<CommandArgumentEntry> lldb_private::CommandObject::m_arguments protected
Definition at line 417 of file CommandObject.h.
Referenced by AddIDsArgumentData(), AddSimpleArgumentList(), lldb_private::CommandAlias::CommandAlias(), CommandObjectBreakpointAddFile::CommandObjectBreakpointAddFile(), CommandObjectLogDisable::CommandObjectLogDisable(), CommandObjectLogEnable::CommandObjectLogEnable(), CommandObjectMemoryFind::CommandObjectMemoryFind(), CommandObjectMemoryHistory::CommandObjectMemoryHistory(), CommandObjectMemoryRead::CommandObjectMemoryRead(), CommandObjectMemoryRegion::CommandObjectMemoryRegion(), CommandObjectMemoryTagRead::CommandObjectMemoryTagRead(), CommandObjectMemoryTagWrite::CommandObjectMemoryTagWrite(), CommandObjectPlatformInstall::CommandObjectPlatformInstall(), CommandObjectRegisterWrite::CommandObjectRegisterWrite(), CommandObjectScriptingObjectParsed::CommandObjectScriptingObjectParsed(), CommandObjectSettingsAppend::CommandObjectSettingsAppend(), CommandObjectSettingsInsertAfter::CommandObjectSettingsInsertAfter(), CommandObjectSettingsInsertBefore::CommandObjectSettingsInsertBefore(), CommandObjectSettingsList::CommandObjectSettingsList(), CommandObjectSettingsRemove::CommandObjectSettingsRemove(), CommandObjectSettingsReplace::CommandObjectSettingsReplace(), CommandObjectSettingsSet::CommandObjectSettingsSet(), CommandObjectTargetModulesSearchPathsAdd::CommandObjectTargetModulesSearchPathsAdd(), CommandObjectTargetModulesSearchPathsInsert::CommandObjectTargetModulesSearchPathsInsert(), CommandObjectThreadSelect::CommandObjectThreadSelect(), lldb_private::CommandPluginInterfaceImplementation::CommandPluginInterfaceImplementation(), CommandObjectCommandsAlias::DoExecute(), lldb_private::CommandObjectParsed::Execute(), GetArgumentEntryAtIndex(), GetFormattedCommandArguments(), GetNumArgumentEntries(), GetSyntax(), and CommandObjectPlatformGetFile::~CommandObjectPlatformGetFile().
m_cmd_help_long
std::string lldb_private::CommandObject::m_cmd_help_long protected
Definition at line 413 of file CommandObject.h.
Referenced by lldb_private::CommandAlias::GetHelpLong(), GetHelpLong(), and SetHelpLong().
m_cmd_help_short
std::string lldb_private::CommandObject::m_cmd_help_short protected
Definition at line 412 of file CommandObject.h.
Referenced by CommandObject(), lldb_private::CommandAlias::GetHelp(), GetHelp(), and SetHelp().
m_cmd_name
std::string lldb_private::CommandObject::m_cmd_name protected
Definition at line 411 of file CommandObject.h.
Referenced by CommandObjectTypeSynthAdd::AddSynth(), CommandObject(), CommandObjectTypeSynthDelete::CommandObjectTypeSynthDelete(), CommandObjectFrameRecognizerAdd::DoExecute(), CommandObjectFrameRecognizerInfo::DoExecute(), CommandObjectLogDisable::DoExecute(), CommandObjectLogDump::DoExecute(), CommandObjectLogEnable::DoExecute(), CommandObjectMemoryHistory::DoExecute(), CommandObjectMemoryRead::DoExecute(), CommandObjectMemoryRegion::DoExecute(), CommandObjectMemoryWrite::DoExecute(), CommandObjectProcessConnect::DoExecute(), CommandObjectProcessGDBRemotePacketMonitor::DoExecute(), CommandObjectProcessGDBRemotePacketSend::DoExecute(), CommandObjectProcessGDBRemotePacketXferSize::DoExecute(), CommandObjectProcessGDBRemoteSpeedTest::DoExecute(), CommandObjectProcessMinidumpDump::DoExecute(), CommandObjectProcessSaveCore::DoExecute(), CommandObjectProcessSignal::DoExecute(), CommandObjectTargetCreate::DoExecute(), CommandObjectTargetModulesDumpClangPCMInfo::DoExecute(), CommandObjectTargetVariable::DoExecute(), CommandObjectThreadSelect::DoExecute(), CommandObjectTypeFormatterDelete::DoExecute(), lldb_private::CommandObjectDWIMPrint::DoExecute(), lldb_private::CommandObjectRegexCommand::DoExecute(), CommandObjectTypeSummaryAdd::Execute_StringSummary(), GetCommandName(), CommandObjectTypeCategoryDisable::CommandOptions::GetDefinitions(), CommandObjectMemoryHistory::GetRepeatCommand(), CommandObjectMemoryRead::GetRepeatCommand(), CommandObjectMemoryRegion::GetRepeatCommand(), CommandObjectSourceList::GetRepeatCommand(), CommandObjectTypeLookup::GuessLanguage(), and SetCommandName().
m_cmd_syntax
std::string lldb_private::CommandObject::m_cmd_syntax protected
Definition at line 414 of file CommandObject.h.
Referenced by CommandObject(), CommandObjectLogTimerDisable::DoExecute(), CommandObjectLogTimerDump::DoExecute(), CommandObjectLogTimerEnable::DoExecute(), CommandObjectLogTimerIncrement::DoExecute(), CommandObjectLogTimerReset::DoExecute(), CommandObjectMemoryRegion::DoExecute(), CommandObjectProcessConnect::DoExecute(), CommandObjectProcessSaveCore::DoExecute(), CommandObjectProcessSignal::DoExecute(), CommandObjectThreadSelect::DoExecute(), GetSyntax(), and SetSyntax().
m_command_override_baton
void* lldb_private::CommandObject::m_command_override_baton protected
Definition at line 420 of file CommandObject.h.
Referenced by CommandObject(), InvokeOverrideCallback(), SetOverrideCallback(), and SetOverrideCallback().
m_command_override_callback
lldb_private::CommandOverrideCallbackWithResult lldb_private::CommandObject::m_command_override_callback protected
Definition at line 419 of file CommandObject.h.
Referenced by CommandObject(), HasOverrideCallback(), InvokeOverrideCallback(), and SetOverrideCallback().
m_deprecated_command_override_callback
lldb::CommandOverrideCallback lldb_private::CommandObject::m_deprecated_command_override_callback protected
Definition at line 418 of file CommandObject.h.
Referenced by CommandObject(), HasOverrideCallback(), InvokeOverrideCallback(), and SetOverrideCallback().
m_exe_ctx
ExecutionContext lldb_private::CommandObject::m_exe_ctx protected
Definition at line 409 of file CommandObject.h.
Referenced by CommandObjectTargetSymbolsAdd::AddSymbolsForFile(), CommandObjectTargetSymbolsAdd::AddSymbolsForFrame(), CommandObjectTargetSymbolsAdd::AddSymbolsForStack(), lldb_private::CommandObjectIterateOverThreads::BucketThread(), CheckRequirements(), Cleanup(), CommandObjectSourceList::DisplayFunctionSource(), CommandObjectBreakpointAddFile::DoExecute(), CommandObjectBreakpointAddPattern::DoExecute(), CommandObjectBreakpointSet::DoExecute(), CommandObjectCommandsScriptImport::DoExecute(), CommandObjectFrameDiagnose::DoExecute(), CommandObjectFrameInfo::DoExecute(), CommandObjectFrameRecognizerInfo::DoExecute(), CommandObjectFrameSelect::DoExecute(), CommandObjectMemoryFind::DoExecute(), CommandObjectMemoryHistory::DoExecute(), CommandObjectMemoryRead::DoExecute(), CommandObjectMemoryRegion::DoExecute(), CommandObjectMemoryTagRead::DoExecute(), CommandObjectMemoryTagWrite::DoExecute(), CommandObjectMemoryWrite::DoExecute(), CommandObjectMultiwordObjC_TaggedPointer_Info::DoExecute(), CommandObjectObjC_ClassTable_Dump::DoExecute(), CommandObjectPlatformProcessLaunch::DoExecute(), CommandObjectProcessAttach::DoExecute(), CommandObjectProcessConnect::DoExecute(), CommandObjectProcessContinue::DoExecute(), CommandObjectProcessDetach::DoExecute(), CommandObjectProcessInterrupt::DoExecute(), CommandObjectProcessKill::DoExecute(), CommandObjectProcessLaunch::DoExecute(), CommandObjectProcessLoad::DoExecute(), CommandObjectProcessSaveCore::DoExecute(), CommandObjectProcessSignal::DoExecute(), CommandObjectProcessStatus::DoExecute(), CommandObjectProcessTraceStop::DoExecute(), CommandObjectProcessUnload::DoExecute(), CommandObjectPythonFunction::DoExecute(), CommandObjectRegisterRead::DoExecute(), CommandObjectRegisterWrite::DoExecute(), CommandObjectScriptingObjectParsed::DoExecute(), CommandObjectScriptingObjectRaw::DoExecute(), CommandObjectSettingsAppend::DoExecute(), CommandObjectSettingsClear::DoExecute(), CommandObjectSettingsInsertAfter::DoExecute(), CommandObjectSettingsInsertBefore::DoExecute(), CommandObjectSettingsList::DoExecute(), CommandObjectSettingsRemove::DoExecute(), CommandObjectSettingsReplace::DoExecute(), CommandObjectSettingsSet::DoExecute(), CommandObjectSettingsShow::DoExecute(), CommandObjectSourceCacheClear::DoExecute(), CommandObjectSourceCacheDump::DoExecute(), CommandObjectSourceList::DoExecute(), CommandObjectStatsDump::DoExecute(), CommandObjectTargetFrameProviderClear::DoExecute(), CommandObjectTargetFrameProviderList::DoExecute(), CommandObjectTargetFrameProviderRegister::DoExecute(), CommandObjectTargetFrameProviderRemove::DoExecute(), CommandObjectTargetModulesDumpLineTable::DoExecute(), CommandObjectTargetModulesLoad::DoExecute(), CommandObjectTargetModulesShowUnwind::DoExecute(), CommandObjectTargetShowLaunchEnvironment::DoExecute(), CommandObjectTargetSymbolsAdd::DoExecute(), CommandObjectTargetVariable::DoExecute(), CommandObjectThreadContinue::DoExecute(), CommandObjectThreadJump::DoExecute(), CommandObjectThreadList::DoExecute(), CommandObjectThreadPlanDiscard::DoExecute(), CommandObjectThreadPlanList::DoExecute(), CommandObjectThreadPlanPrune::DoExecute(), CommandObjectThreadReturn::DoExecute(), CommandObjectThreadSelect::DoExecute(), CommandObjectThreadStepWithTypeAndScope::DoExecute(), CommandObjectThreadUntil::DoExecute(), CommandObjectTraceDumpFunctionCalls::DoExecute(), CommandObjectTraceDumpInstructions::DoExecute(), CommandObjectTraceSave::DoExecute(), lldb_private::CommandObjectDisassemble::DoExecute(), lldb_private::CommandObjectDWIMPrint::DoExecute(), lldb_private::CommandObjectIterateOverThreads::DoExecute(), lldb_private::CommandObjectMultipleThreads::DoExecute(), lldb_private::ctf::CommandObjectThreadTraceExportCTF::DoExecute(), CommandObjectTraceStop::DoExecuteOnThreads(), CommandObjectTargetSymbolsAdd::DownloadObjectAndSymbolFile(), CommandObjectSourceInfo::DumpLinesForFrame(), lldb_private::CommandObjectDisassemble::GetCurrentFunctionRanges(), lldb_private::CommandObjectDisassemble::GetCurrentLineRanges(), GetDefaultThread(), lldb_private::CommandObjectDisassemble::GetPCRanges(), GetTarget(), CommandObjectProcessLoad::HandleArgumentCompletion(), CommandObjectProcessSignal::HandleArgumentCompletion(), CommandObjectProcessUnload::HandleArgumentCompletion(), CommandObjectRegisterRead::HandleArgumentCompletion(), CommandObjectRegisterWrite::HandleArgumentCompletion(), CommandObjectTargetModulesSearchPathsInsert::HandleArgumentCompletion(), CommandObjectThreadPlanDiscard::HandleArgumentCompletion(), HandleCompletion(), CommandObjectThreadBacktrace::HandleOneThread(), CommandObjectThreadException::HandleOneThread(), CommandObjectThreadInfo::HandleOneThread(), CommandObjectThreadPlanList::HandleOneThread(), CommandObjectThreadSiginfo::HandleOneThread(), CommandObjectTraceDumpInfo::HandleOneThread(), CommandObjectTargetModulesLookup::LookupHere(), and CommandObjectScriptingObjectParsed::PrepareOptionsForCompletion().
m_flags
Flags lldb_private::CommandObject::m_flags protected
Definition at line 416 of file CommandObject.h.
Referenced by CommandObject(), GetFlags(), and GetFlags().
m_interpreter
CommandInterpreter& lldb_private::CommandObject::m_interpreter protected
Definition at line 408 of file CommandObject.h.
Referenced by CheckRequirements(), CommandObject(), CommandObjectBreakpointAddAddress::DoExecute(), CommandObjectBreakpointDelete::DoExecute(), CommandObjectCommandsDelete::DoExecute(), CommandObjectCommandsScriptAdd::DoExecute(), CommandObjectCommandsScriptClear::DoExecute(), CommandObjectCommandsScriptDelete::DoExecute(), CommandObjectCommandsScriptList::DoExecute(), CommandObjectCommandsSource::DoExecute(), CommandObjectCommandsUnalias::DoExecute(), CommandObjectPlatformSelect::DoExecute(), CommandObjectProcessAttach::DoExecute(), CommandObjectProcessConnect::DoExecute(), CommandObjectProcessContinue::DoExecute(), CommandObjectProcessGDBRemotePacketHistory::DoExecute(), CommandObjectProcessGDBRemotePacketMonitor::DoExecute(), CommandObjectProcessGDBRemotePacketSend::DoExecute(), CommandObjectProcessGDBRemotePacketXferSize::DoExecute(), CommandObjectProcessGDBRemoteSpeedTest::DoExecute(), CommandObjectProcessHandle::DoExecute(), CommandObjectProcessKDPPacketSend::DoExecute(), CommandObjectProcessMinidumpDump::DoExecute(), CommandObjectPythonFunction::DoExecute(), CommandObjectScriptingRun::DoExecute(), CommandObjectSessionHistory::DoExecute(), CommandObjectSessionSave::DoExecute(), CommandObjectSettingsList::DoExecute(), CommandObjectSettingsRead::DoExecute(), CommandObjectSettingsSet::DoExecute(), CommandObjectTargetModulesDumpLineTable::DoExecute(), CommandObjectTargetModulesDumpSections::DoExecute(), CommandObjectTargetModulesDumpSymtab::DoExecute(), CommandObjectTargetModulesLookup::DoExecute(), CommandObjectTargetVariable::DoExecute(), CommandObjectThreadContinue::DoExecute(), CommandObjectThreadStepWithTypeAndScope::DoExecute(), CommandObjectThreadUntil::DoExecute(), CommandObjectWatchpointDelete::DoExecute(), lldb_private::CommandObjectApropos::DoExecute(), lldb_private::CommandObjectDWIMPrint::DoExecute(), lldb_private::CommandObjectHelp::DoExecute(), lldb_private::CommandObjectQuit::DoExecute(), lldb_private::CommandObjectRegexCommand::DoExecute(), lldb_private::CommandPluginInterfaceImplementation::DoExecute(), lldb_private::CommandObjectTraceProxy::DoGetProxyCommandObject(), lldb_private::CommandObjectParsed::Execute(), lldb_private::CommandObjectMultiword::GenerateHelpText(), GetCommandInterpreter(), GetDebugger(), GetDefaultThread(), CommandObjectBreakpointCommandAdd::CommandOptions::GetDefinitions(), CommandObjectProcessTraceStart::GetDelegateCommand(), CommandObjectTraceStart::GetDelegateCommand(), GetDummyTarget(), CommandObjectPlatformConnect::GetOptions(), CommandObjectProcessPlugin::GetProxyCommandObject(), GetTarget(), CommandObjectCommandsContainerAdd::HandleArgumentCompletion(), CommandObjectCommandsContainerDelete::HandleArgumentCompletion(), CommandObjectCommandsDelete::HandleArgumentCompletion(), CommandObjectCommandsScriptAdd::HandleArgumentCompletion(), CommandObjectCommandsScriptDelete::HandleArgumentCompletion(), CommandObjectCommandsUnalias::HandleArgumentCompletion(), HandleCompletion(), lldb_private::CommandObjectHelp::HandleCompletion(), CommandObjectCommandsScriptAdd::IOHandlerInputComplete(), CommandObjectTargetModulesLookup::LookupHere(), CommandObjectTargetModulesLookup::LookupInModule(), lldb_private::CommandObjectQuit::ShouldAskForConfirmation(), CommandObjectProcessLaunchOrAttach::StopProcessIfNecessary(), and CommandObjectCommandsAddRegex::CommandOptions::~CommandOptions().
m_is_user_command
bool lldb_private::CommandObject::m_is_user_command = false protected
Definition at line 421 of file CommandObject.h.
Referenced by IsUserCommand(), and SetIsUserCommand().
m_original_command
std::string lldb_private::CommandObject::m_original_command protected
Definition at line 415 of file CommandObject.h.
Referenced by lldb_private::CommandObjectDWIMPrint::DoExecute(), and SetOriginalCommandString().
The documentation for this class was generated from the following files:
CommandObject.h
CommandObject.cpp