LLDB: lldb_private::CommandOptionsProcessAttach Class Reference
lldb_private::CommandOptionsProcessAttach Class Reference
#include <CommandOptionsProcessAttach.h>
Public Member Functions
CommandOptionsProcessAttach ()
~CommandOptionsProcessAttach () override=default
lldb_private::Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, lldb_private::ExecutionContext *execution_context) override
void OptionParsingStarting (lldb_private::ExecutionContext *execution_context) override
llvm::ArrayRef< lldb_private::OptionDefinition > GetDefinitions () override
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Public Attributes
lldb_private::ProcessAttachInfo attach_info
Detailed Description
Definition at line 19 of file CommandOptionsProcessAttach.h.
Constructor & Destructor Documentation
CommandOptionsProcessAttach()
lldb_private::CommandOptionsProcessAttach::CommandOptionsProcessAttach () inline
Definition at line 21 of file CommandOptionsProcessAttach.h.
References OptionParsingStarting().
~CommandOptionsProcessAttach()
lldb_private::CommandOptionsProcessAttach::~CommandOptionsProcessAttach () override default
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > CommandOptionsProcessAttach::GetDefinitions () override virtual
Implements lldb_private::OptionGroup.
Definition at line 74 of file CommandOptionsProcessAttach.cpp.
OptionParsingStarting()
void lldb_private::CommandOptionsProcessAttach::OptionParsingStarting (lldb_private::ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 33 of file CommandOptionsProcessAttach.h.
References attach_info.
Referenced by CommandOptionsProcessAttach().
SetOptionValue()
Status CommandOptionsProcessAttach::SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, lldb_private::ExecutionContext * execution_context) override virtual
Implements lldb_private::OptionGroup.
Definition at line 31 of file CommandOptionsProcessAttach.cpp.
References attach_info, error(), and lldb_private::Status::FromErrorStringWithFormatv().
Member Data Documentation
attach_info
lldb_private::ProcessAttachInfo lldb_private::CommandOptionsProcessAttach::attach_info
Definition at line 42 of file CommandOptionsProcessAttach.h.
Referenced by OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following files:
CommandOptionsProcessAttach.h
CommandOptionsProcessAttach.cpp