LLDB: lldb_private::WritableDataBuffer Class Reference
lldb_private::WritableDataBuffer Class Reference
#include <DataBuffer.h>
Public Member Functions
~WritableDataBuffer () override=default
Destructor.
uint8_t * GetBytes ()
Get a pointer to the data.
llvm::MutableArrayRef< uint8_t > GetData ()
bool isA (const void *ClassID) const override
const uint8_t * GetBytes () const
Get a const pointer to the data.
llvm::ArrayRef< uint8_t > GetData () const
Public Member Functions inherited from lldb_private::DataBuffer
virtual ~DataBuffer ()=default
virtual lldb::offset_t GetByteSize () const =0
Get the number of bytes in the data buffer.
const uint8_t * GetBytes () const
Get a const pointer to the data.
llvm::ArrayRef< uint8_t > GetData () const
Static Public Member Functions
static bool classof (const DataBuffer *data_buffer)
Static Public Member Functions inherited from lldb_private::DataBuffer
static bool classof (const DataBuffer *data_buffer)
Static Public Attributes
static char ID
LLVM RTTI support.
Static Public Attributes inherited from lldb_private::DataBuffer
static char ID
LLVM RTTI support.
Additional Inherited Members
Protected Member Functions inherited from lldb_private::DataBuffer
virtual const uint8_t * GetBytesImpl () const =0
}
Detailed Description
Definition at line 90 of file DataBuffer.h.
Constructor & Destructor Documentation
~WritableDataBuffer()
lldb_private::WritableDataBuffer::~WritableDataBuffer () override default
Destructor.
The destructor is virtual as other classes will inherit from this class and be downcast to the DataBuffer pure virtual interface. The virtual destructor ensures that destructing the base class will destruct the class that inherited from it correctly.
References lldb_private::DataBuffer::GetBytes(), and lldb_private::DataBuffer::GetData().
Member Function Documentation
classof()
bool lldb_private::WritableDataBuffer::classof (const DataBuffer * data_buffer) inline static
Definition at line 120 of file DataBuffer.h.
References ID, and lldb_private::DataBuffer::isA().
GetBytes() [1/2]
uint8_t * lldb_private::WritableDataBuffer::GetBytes () inline
Get a pointer to the data.
Returns
A pointer to the bytes owned by this object, or NULL if the object contains no bytes.
Definition at line 108 of file DataBuffer.h.
References lldb_private::DataBuffer::GetBytesImpl().
Referenced by MinidumpFileBuilder::AddModuleList(), MinidumpFileBuilder::AddThreadList(), lldb_private::DataExtractor::Append(), lldb_private::DataExtractor::Append(), lldb_private::Value::AppendDataToHostBuffer(), ApplyELF32ABS32RelRelocation(), ApplyELF64ABS32Relocation(), ApplyELF64ABS64Relocation(), ObjectFileELF::ApplyRelocations(), InterpreterStackFrame::AssignValue(), SystemRuntimeMacOSX::CompleteQueueItem(), CommandObjectMemoryFind::DoExecute(), EntityPersistentVariable::DumpToLog(), EntityRegister::DumpToLog(), EntityResultVariable::DumpToLog(), EntitySymbol::DumpToLog(), EntityVariableBase::DumpToLog(), lldb_private::DWARFExpression::Evaluate(), lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::GetChildAtIndex(), lldb_private::formatters::NSSetISyntheticFrontEnd::GetChildAtIndex(), GetData(), SystemRuntimeMacOSX::GetExtendedBacktraceFromItemRef(), SystemRuntimeMacOSX::GetExtendedBacktraceThread(), GetMacOSXProcessArgs(), lldb_private::IRMemoryMap::GetMemoryData(), SystemRuntimeMacOSX::GetPendingItemRefsForQueue(), lldb_private::ValueObject::GetPointeeData(), ABISysV_arm::GetReturnValueObjectImpl(), GetReturnValuePassedInMemory(), lldb_private::IRExecutionUnit::GetRunnableInfo(), IRInterpreter::Interpret(), EntityRegister::Materialize(), lldb_private::Value::operator=(), lldb_private::AppleObjCRuntimeV2::ParseClassInfoArray(), SystemRuntimeMacOSX::PopulateQueuesUsingLibBTR(), InterpreterStackFrame::PrintData(), lldb_private::ClassDescriptorV2::class_ro_t::Read(), lldb_private::ClassDescriptorV2::class_rw_t::Read(), lldb_private::ClassDescriptorV2::ivar_list_t::Read(), lldb_private::ClassDescriptorV2::ivar_t::Read(), lldb_private::ClassDescriptorV2::method_list_t::Read(), lldb_private::ClassDescriptorV2::objc_class_t::Read(), lldb_private::ClassDescriptorV2::relative_list_entry_t::Read(), lldb_private::ClassDescriptorV2::relative_list_list_t::Read(), DynamicLoaderMacOSXDYLD::ReadImageInfos(), lldb_private::Target::ReadInstructions(), ReadJITEntry(), DynamicLoaderDarwinKernel::ReadKextSummaries(), DynamicLoaderMacOSXDYLD::ReadMachHeader(), lldb_private::IRMemoryMap::ReadMemory(), lldb_private::Process::ReadMemoryInChunks(), lldb_private::IRMemoryMap::ReadScalarFromMemory(), MinidumpFileBuilder::ReadWriteMemoryInChunks(), InterpreterStackFrame::ResolveConstant(), lldb_private::AppleObjCRuntimeV1::UpdateISAToDescriptorMapIfNeeded(), lldb_private::Value::Value(), lldb_private::IRMemoryMap::WriteMemory(), and lldb_private::IRExecutionUnit::WriteNow().
GetBytes() [2/2]
const uint8_t * lldb_private::DataBuffer::GetBytes () const inline
Get a const pointer to the data.
Returns
A const pointer to the bytes owned by this object, or NULL if the object contains no bytes.
Definition at line 57 of file DataBuffer.h.
GetData() [1/2]
llvm::MutableArrayRef< uint8_t > lldb_private::WritableDataBuffer::GetData () inline
Definition at line 110 of file DataBuffer.h.
References GetBytes(), and lldb_private::DataBuffer::GetByteSize().
GetData() [2/2]
llvm::ArrayRef< uint8_t > lldb_private::DataBuffer::GetData () const inline
Definition at line 59 of file DataBuffer.h.
isA()
bool lldb_private::WritableDataBuffer::isA (const void * ClassID) const inline override virtual
Reimplemented from lldb_private::DataBuffer.
Reimplemented in lldb_private::WritableDataBufferLLVM.
Definition at line 117 of file DataBuffer.h.
References ID, and lldb_private::DataBuffer::isA().
Referenced by lldb_private::DataBufferHeap::isA(), lldb_private::DataBufferUnowned::isA(), and lldb_private::WritableDataBufferLLVM::isA().
Member Data Documentation
ID
char WritableDataBuffer::ID static
LLVM RTTI support.
{
Definition at line 116 of file DataBuffer.h.
Referenced by classof(), and isA().
The documentation for this class was generated from the following files:
DataBuffer.h
DataBufferHeap.cpp