LLDB: lldb_private::plugin::dwarf::DWARFDIE Class Reference
lldb_private::plugin::dwarf::DWARFDIE Class Reference
#include <DWARFDIE.h>
Classes
class child_iterator
Public Member Functions
bool IsStructUnionOrClass () const
bool IsMethod () const
const char * GetMangledName (bool substitute_name_allowed=true) const
const char * GetPubname () const
void GetName (Stream &s) const
void AppendTypeName (Stream &s) const
Type * ResolveType () const
Type * ResolveTypeUID (const DWARFDIE &die) const
DWARFDIE GetParent () const
DWARFDIE GetFirstChild () const
DWARFDIE GetSibling () const
DWARFDIE GetReferencedDIE (const dw_attr_t attr) const
DWARFDIE GetDIE (dw_offset_t die_offset) const
DWARFDIE LookupDeepestBlock (lldb::addr_t file_addr) const
DWARFDIE GetParentDeclContextDIE () const
std::vector< CompilerContext > GetDeclContext (bool derive_template_names=false) const
Return this DIE's decl context as it is needed to look up types in Clang modules.
std::vector< CompilerContext > GetTypeLookupContext (bool derive_template_names=false) const
Get a context to a type so it can be looked up.
DWARFDeclContext GetDWARFDeclContext () const
DWARFDIE GetAttributeValueAsReferenceDIE (const dw_attr_t attr) const
bool GetDIENamesAndRanges (const char *&name, const char *&mangled, llvm::DWARFAddressRangesVector &ranges, std::optional< int > &decl_file, std::optional< int > &decl_line, std::optional< int > &decl_column, std::optional< int > &call_file, std::optional< int > &call_line, std::optional< int > &call_column, DWARFExpressionList *frame_base) const
std::optional< uint64_t > getLanguage () const
DWARFDIE getParent () const
DWARFDIE resolveReferencedType (dw_attr_t attr) const
DWARFDIE resolveReferencedType (DWARFFormValue v) const
DWARFDIE resolveTypeUnitReference () const
std::optional< DWARFFormValue > find (const dw_attr_t attr) const
llvm::iterator_range< child_iterator > children () const
The range of all the children of this DIE.
child_iterator begin () const
child_iterator end () const
DWARFBaseDIE ()=default
DWARFBaseDIE (DWARFUnit *cu, DWARFDebugInfoEntry *die)
DWARFBaseDIE (const DWARFUnit *cu, DWARFDebugInfoEntry *die)
DWARFBaseDIE (DWARFUnit *cu, const DWARFDebugInfoEntry *die)
DWARFBaseDIE (const DWARFUnit *cu, const DWARFDebugInfoEntry *die)
const char * GetName () const
DWARFDebugInfoEntry * GetDIE () const
Public Member Functions inherited from lldb_private::plugin::dwarf::DWARFBaseDIE
DWARFBaseDIE ()=default
DWARFBaseDIE (DWARFUnit *cu, DWARFDebugInfoEntry *die)
DWARFBaseDIE (const DWARFUnit *cu, DWARFDebugInfoEntry *die)
DWARFBaseDIE (DWARFUnit *cu, const DWARFDebugInfoEntry *die)
DWARFBaseDIE (const DWARFUnit *cu, const DWARFDebugInfoEntry *die)
operator bool () const
bool IsValid () const
bool HasChildren () const
bool Supports_DW_AT_APPLE_objc_complete_type () const
SymbolFileDWARF * GetDWARF () const
DWARFUnit * GetCU () const
DWARFDebugInfoEntry * GetDIE () const
std::optional< DIERef > GetDIERef () const
void Set (DWARFUnit *cu, DWARFDebugInfoEntry *die)
void Clear ()
const DWARFDataExtractor & GetData () const
dw_tag_t Tag () const
dw_offset_t GetOffset () const
lldb::user_id_t GetID () const
const char * GetName () const
lldb::ModuleSP GetModule () const
const char * GetAttributeValueAsString (const dw_attr_t attr, const char *fail_value) const
uint64_t GetAttributeValueAsUnsigned (const dw_attr_t attr, uint64_t fail_value) const
std::optional< uint64_t > GetAttributeValueAsOptionalUnsigned (const dw_attr_t attr) const
uint64_t GetAttributeValueAsAddress (const dw_attr_t attr, uint64_t fail_value) const
DWARFAttributes GetAttributes (Recurse recurse=Recurse::yes) const
dw_tag_t getTag () const
const char * getShortName () const
Additional Inherited Members
Public Types inherited from lldb_private::plugin::dwarf::DWARFBaseDIE
enum class Recurse : bool { no , yes }
using DWARFFormValue = dwarf::DWARFFormValue
Protected Attributes inherited from lldb_private::plugin::dwarf::DWARFBaseDIE
DWARFUnit * m_cu = nullptr
DWARFDebugInfoEntry * m_die = nullptr
Detailed Description
Definition at line 19 of file DWARFDIE.h.
Member Function Documentation
AppendTypeName()
void DWARFDIE::AppendTypeName (Stream & s) const
Definition at line 249 of file DWARFDIE.cpp.
References GetAttributeValueAsReferenceDIE(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetAttributeValueAsUnsigned(), GetDIE(), GetPubname(), lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), lldb_private::Stream::Printf(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
begin()
DWARFDIE::child_iterator DWARFDIE::begin () const
Definition at line 605 of file DWARFDIE.cpp.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::MergeBlockAbstractParameters().
children()
llvm::iterator_range< DWARFDIE::child_iterator > DWARFDIE::children () const
The range of all the children of this DIE.
Definition at line 601 of file DWARFDIE.cpp.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::ClassOrStructIsVirtual(), lldb_private::plugin::dwarf::SymbolFileDWARF::CollectCallEdges(), CollectCallSiteParameters(), DWARFASTParserClang::EnsureAllDIEsInDeclContextHaveBeenParsed(), FindAnyChildWithAbstractOrigin(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindBlockContainingSpecification(), DWARFASTParserClang::GetObjectParameter(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetTypes(), LookupDeepestBlock(), lldb_private::plugin::dwarf::DWARFASTParser::ParseChildArrayInfo(), DWARFASTParserClang::ParseChildEnumerators(), DWARFASTParserClang::ParseChildMembers(), DWARFASTParserClang::ParseChildParameters(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseImportedModules(), DWARFASTParserClang::ParseTemplateDIE(), DWARFASTParserClang::ParseTemplateParameterInfos(), and DWARFASTParserClang::ParseTypeModifier().
DWARFBaseDIE() [1/5]
lldb_private::plugin::dwarf::DWARFBaseDIE::DWARFBaseDIE () default
DWARFBaseDIE() [2/5]
lldb_private::plugin::dwarf::DWARFBaseDIE::DWARFBaseDIE (const DWARFUnit * cu, const DWARFDebugInfoEntry * die) inline
Definition at line 43 of file DWARFBaseDIE.h.
DWARFBaseDIE() [3/5]
lldb_private::plugin::dwarf::DWARFBaseDIE::DWARFBaseDIE (const DWARFUnit * cu, DWARFDebugInfoEntry * die) inline
Definition at line 37 of file DWARFBaseDIE.h.
DWARFBaseDIE() [4/5]
lldb_private::plugin::dwarf::DWARFBaseDIE::DWARFBaseDIE (DWARFUnit * cu, const DWARFDebugInfoEntry * die) inline
Definition at line 40 of file DWARFBaseDIE.h.
DWARFBaseDIE() [5/5]
lldb_private::plugin::dwarf::DWARFBaseDIE::DWARFBaseDIE (DWARFUnit * cu, DWARFDebugInfoEntry * die) inline
Definition at line 34 of file DWARFBaseDIE.h.
end()
DWARFDIE::child_iterator DWARFDIE::end () const
Definition at line 609 of file DWARFDIE.cpp.
find()
std::optional< DWARFFormValue > DWARFDIE::find (const dw_attr_t attr) const
Definition at line 611 of file DWARFDIE.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::m_cu, and lldb_private::plugin::dwarf::DWARFBaseDIE::m_die.
GetAttributeValueAsReferenceDIE()
DWARFDIE DWARFDIE::GetAttributeValueAsReferenceDIE (const dw_attr_t attr) const
Definition at line 134 of file DWARFDIE.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), lldb_private::plugin::dwarf::DWARFBaseDIE::m_die, and lldb_private::plugin::dwarf::DWARFFormValue::Reference().
Referenced by AppendTypeName(), DWARFASTParserClang::GetClangDeclForDIE(), GetCXXMethodCVQuals(), DWARFASTParserClang::ParseChildParameters(), and DWARFASTParserClang::ResolveImportedDeclarationDIE().
GetDeclContext()
std::vector< CompilerContext > DWARFDIE::GetDeclContext (bool derive_template_names = false) const
Return this DIE's decl context as it is needed to look up types in Clang modules.
This context will include any modules or functions that the type is declared in so an exact module match can be efficiently made.
Parameters
[in] derive_template_names If true, augments the returned names with template arguments derived from the child DIEs, if the names don't contained template arguments already. If false, the returned context will contain the names exactly as they are spelled in the debug info, regardless of whether that includes template arguments or not.
Definition at line 456 of file DWARFDIE.cpp.
References GetDeclContextImpl().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::FindTypes(), DWARFASTParserClang::ParseTypeFromClangModule(), and lldb_private::plugin::dwarf::DWARFIndex::ProcessTypeDIEMatchQuery().
GetDIE() [1/2]
DWARFDebugInfoEntry * lldb_private::plugin::dwarf::DWARFBaseDIE::GetDIE () const inline
Definition at line 61 of file DWARFBaseDIE.h.
Referenced by AppendTypeName(), and GetName().
GetDIE() [2/2]
DWARFDIE DWARFDIE::GetDIE (dw_offset_t die_offset) const
Definition at line 126 of file DWARFDIE.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), and lldb_private::plugin::dwarf::DWARFBaseDIE::m_cu.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::CompleteType(), DWARFASTParserClang::CopyUniqueClassMethodTypes(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindCompleteObjCDefinitionTypeForDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindFunctions(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindFunctions(), GetAttributes(), lldb_private::plugin::dwarf::DWARFDebugInfoEntry::GetAttributeValue(), DWARFASTParserClang::GetCachedClangDeclContextForDIE(), DWARFASTParserClang::GetClangDeclForDIE(), lldb_private::plugin::dwarf::DWARFDebugInfo::GetDIE(), lldb_private::plugin::dwarf::DebugNamesDWARFIndex::GetFunctions(), DWARFASTParserClang::GetObjectParameter(), DWARFASTParserClang::GetOwningClangModule(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetTypeForDIE(), DWARFASTParserClang::LinkDeclContextToDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseAndAppendGlobalVariable(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseBlocksRecursive(), DWARFASTParserClang::ParseCXXMethod(), DWARFASTParserClang::ParseEnum(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseFunction(), DWARFASTParserClang::ParseFunctionFromDWARF(), DWARFASTParserClang::ParseStructureLikeDIE(), DWARFASTParserClang::ParseTypeFromDWARF(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIECached(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariablesForContext(), DWARFASTParserClang::ResolveBlockDIE(), DWARFASTParserClang::ResolveImportedDeclarationDIE(), and DWARFASTParserClang::ResolveNamespaceDIE().
GetDIENamesAndRanges()
bool DWARFDIE::GetDIENamesAndRanges (const char *& name, const char *& mangled, llvm::DWARFAddressRangesVector & ranges, std::optional< int > & decl_file, std::optional< int > & decl_line, std::optional< int > & decl_column, std::optional< int > & call_file, std::optional< int > & call_line, std::optional< int > & call_column, lldb_private::DWARFExpressionList * frame_base) const
Definition at line 584 of file DWARFDIE.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), and lldb_private::plugin::dwarf::DWARFBaseDIE::m_die.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::ParseBlocksRecursive(), and DWARFASTParserClang::ParseFunctionFromDWARF().
GetDWARFDeclContext()
DWARFDeclContext DWARFDIE::GetDWARFDeclContext () const
Definition at line 526 of file DWARFDIE.cpp.
References GetDWARFDeclContextImpl().
Referenced by DWARFASTParserClang::ConstructDemangledNameFromDWARF(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindDefinitionDIE(), lldb_private::plugin::dwarf::DWARFIndex::GetFullyQualifiedTypeImpl(), and lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE().
GetFirstChild()
DWARFDIE DWARFDIE::GetFirstChild () const
Definition at line 102 of file DWARFDIE.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), lldb_private::plugin::dwarf::DWARFBaseDIE::m_cu, and lldb_private::plugin::dwarf::DWARFBaseDIE::m_die.
Referenced by lldb_private::plugin::dwarf::DWARFDIE::child_iterator::child_iterator(), DWARFASTParserClang::CopyUniqueClassMethodTypes(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexUnit(), lldb_private::plugin::dwarf::SymbolFileDWARF::MergeBlockAbstractParameters(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseBlocksRecursive(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseBlocksRecursive(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseTypes(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseTypes(), and lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariablesInFunctionContextRecursive().
getLanguage()
std::optional< uint64_t > DWARFDIE::getLanguage () const
Definition at line 618 of file DWARFDIE.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), and lldb_private::plugin::dwarf::DWARFBaseDIE::m_cu.
GetMangledName()
const char * DWARFDIE::GetMangledName (bool substitute_name_allowed = true) const
Definition at line 212 of file DWARFDIE.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), lldb_private::plugin::dwarf::DWARFBaseDIE::m_cu, and lldb_private::plugin::dwarf::DWARFBaseDIE::m_die.
Referenced by DWARFASTParserClang::CopyUniqueClassMethodTypes(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetMangledNamesForFunction(), MakeLLDBFuncAsmLabel(), lldb_private::plugin::dwarf::DWARFIndex::ProcessFunctionDIE(), and lldb_private::plugin::dwarf::DWARFIndex::ProcessTypeDIEMatchQuery().
GetName() [1/2]
const char * DWARFBaseDIE::GetName () const
Definition at line 98 of file DWARFBaseDIE.cpp.
GetName() [2/2]
void DWARFDIE::GetName (Stream & s) const
Definition at line 231 of file DWARFDIE.cpp.
References lldb_private::plugin::dwarf::DWARFDebugInfoEntry::GetAttributeValueAsString(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), GetDIE(), lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), and lldb_private::Stream::PutCString().
Referenced by DWARFASTParserClang::CompleteRecordType(), lldb_private::plugin::dwarf::UniqueDWARFASTTypeList::Find(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindDefinitionDIE(), DWARFASTParserClang::GetClangDeclForDIE(), GetContainingClangModule(), GetContextEntry(), DWARFASTParserClang::GetDIEClassTemplateParams(), GetDWARFDeclContextImpl(), DWARFASTParserClang::GetObjectParameter(), DWARFASTParserClang::GetUniqueTypeNameAndDeclaration(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseAndAppendGlobalVariable(), DWARFASTParserClang::ParseChildParameters(), DWARFASTParserClang::ParseCXXMethod(), DWARFASTParserClang::ParseSubroutine(), DWARFASTParserClang::ParseTemplateDIE(), DWARFASTParserClang::ParseTypeFromDWARF(), DWARFASTParserClang::ParseTypeModifier(), lldb_private::plugin::dwarf::DWARFIndex::ProcessFunctionDIE(), DWARFASTParserClang::ResolveNamespaceDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveType(), and lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveTypeUID().
GetParent()
DWARFDIE DWARFDIE::GetParent () const
Definition at line 94 of file DWARFDIE.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), lldb_private::plugin::dwarf::DWARFBaseDIE::m_cu, and lldb_private::plugin::dwarf::DWARFBaseDIE::m_die.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::DIEInDeclContext(), lldb_private::plugin::dwarf::UniqueDWARFASTTypeList::Find(), FindFirstChildWithAbstractOrigin(), DWARFASTParserClang::GetClangDeclForDIE(), GetContainingClangModuleDIE(), GetContainingFunctionWithAbstractOrigin(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDeclContextDIEContainingDIE(), GetDeclContextImpl(), DWARFASTParserClang::GetOwningClangModule(), getParent(), GetParentDeclContextDIEImpl(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetParentSymbolContextDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetTypeForDIE(), GetTypeLookupContextImpl(), IsClangModuleFwdDecl(), DWARFASTParserClang::ParseFunctionFromDWARF(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseImportedModules(), and lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveFunction().
getParent()
DWARFDIE lldb_private::plugin::dwarf::DWARFDIE::getParent () const inline
Definition at line 127 of file DWARFDIE.h.
References GetParent().
GetParentDeclContextDIE()
DWARFDIE DWARFDIE::GetParentDeclContextDIE () const
Definition at line 567 of file DWARFDIE.cpp.
References GetParentDeclContextDIEImpl().
Referenced by GetDWARFDeclContextImpl(), GetParentDeclContextDIEImpl(), and DWARFASTParserClang::GetUniqueTypeNameAndDeclaration().
GetPubname()
const char * DWARFDIE::GetPubname () const
Definition at line 219 of file DWARFDIE.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), lldb_private::plugin::dwarf::DWARFBaseDIE::m_cu, and lldb_private::plugin::dwarf::DWARFBaseDIE::m_die.
Referenced by AppendTypeName(), and lldb_private::plugin::dwarf::SymbolFileDWARF::CollectCallEdges().
GetReferencedDIE()
DWARFDIE DWARFDIE::GetReferencedDIE (const dw_attr_t attr) const
Definition at line 118 of file DWARFDIE.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), and lldb_private::plugin::dwarf::DWARFBaseDIE::m_die.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::FindBlockContainingSpecification(), DWARFASTParserClang::GetClangDeclForDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDeclContextDIEContainingDIE(), GetDeclContextImpl(), DWARFASTParserClang::GetDIEClassTemplateParams(), GetParentDeclContextDIEImpl(), lldb_private::plugin::dwarf::SymbolFileDWARF::MergeBlockAbstractParameters(), lldb_private::plugin::dwarf::DWARFASTParser::ParseChildArrayInfo(), DWARFASTParserClang::ParseTypeModifier(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIECached(), resolveReferencedType(), and resolveTypeUnitReference().
GetSibling()
DWARFDIE DWARFDIE::GetSibling () const
Definition at line 110 of file DWARFDIE.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), lldb_private::plugin::dwarf::DWARFBaseDIE::m_cu, and lldb_private::plugin::dwarf::DWARFBaseDIE::m_die.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::MergeBlockAbstractParameters(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseBlocksRecursive(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseTypes(), and lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariablesInFunctionContextRecursive().
GetTypeLookupContext()
std::vector< CompilerContext > DWARFDIE::GetTypeLookupContext (bool derive_template_names = false) const
Get a context to a type so it can be looked up.
This function uses the current DIE to fill in a CompilerContext array that is suitable for type lookup for comparison to a TypeQuery's compiler context (TypeQuery::GetContextRef()). If this DIE represents a named type, it should fill out the compiler context with the type itself as the last entry. The declaration context should be above the type and stop at an appropriate time, like either the translation unit or at a function context. This is designed to allow users to efficiently look for types using a full or partial CompilerContext array.
Parameters
[in] derive_template_names If true, augments the returned names with template arguments derived from the child DIEs, if the names don't contained template arguments already. If false, the returned context will contain the names exactly as they are spelled in the debug info, regardless of whether that includes template arguments or not.
Definition at line 503 of file DWARFDIE.cpp.
References GetTypeLookupContextImpl().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::FindTypes(), and lldb_private::plugin::dwarf::DWARFIndex::ProcessTypeDIEMatchQuery().
IsMethod()
bool DWARFDIE::IsMethod () const
Definition at line 577 of file DWARFDIE.cpp.
Referenced by lldb_private::plugin::dwarf::ManualDWARFIndex::IndexUnitImpl(), and lldb_private::plugin::dwarf::DWARFIndex::ProcessFunctionDIE().
IsStructUnionOrClass()
bool DWARFDIE::IsStructUnionOrClass () const
Definition at line 571 of file DWARFDIE.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
Referenced by DWARFASTParserClang::GetObjectParameter(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexUnitImpl(), and lldb_private::plugin::dwarf::DebugNamesDWARFIndex::ProcessEntry().
LookupDeepestBlock()
DWARFDIE DWARFDIE::LookupDeepestBlock (lldb::addr_t file_addr) const
Definition at line 147 of file DWARFDIE.cpp.
References children(), lldb_private::DebugInfo, lldb_private::plugin::dwarf::DWARFBaseDIE::GetID(), lldb_private::GetLog(), lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), LLDB_LOG_ERROR, LookupDeepestBlock(), lldb_private::plugin::dwarf::DWARFBaseDIE::m_cu, lldb_private::plugin::dwarf::DWARFBaseDIE::m_die, and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
Referenced by LookupDeepestBlock(), and lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveFunctionAndBlock().
resolveReferencedType() [1/2]
DWARFDIE DWARFDIE::resolveReferencedType (dw_attr_t attr) const
Definition at line 624 of file DWARFDIE.cpp.
References GetReferencedDIE(), and resolveTypeUnitReference().
resolveReferencedType() [2/2]
DWARFDIE DWARFDIE::resolveReferencedType (DWARFFormValue v) const
Definition at line 628 of file DWARFDIE.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), lldb_private::plugin::dwarf::DWARFFormValue::Reference(), and resolveTypeUnitReference().
ResolveType()
lldb_private::Type * DWARFDIE::ResolveType () const
Definition at line 368 of file DWARFDIE.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::GetDWARF(), lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), and lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveType().
Referenced by DWARFASTParserClang::CompleteRecordType().
ResolveTypeUID()
lldb_private::Type * DWARFDIE::ResolveTypeUID (const DWARFDIE & die) const
Definition at line 375 of file DWARFDIE.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::GetDWARF().
Referenced by DWARFASTParserClang::CreateStaticMemberVariable(), GetCXXMethodCVQuals(), DWARFASTParserClang::ParseChildParameters(), DWARFASTParserClang::ParseInheritance(), DWARFASTParserClang::ParseObjCProperty(), DWARFASTParserClang::ParseRustVariantPart(), DWARFASTParserClang::ParseSingleMember(), and DWARFASTParserClang::ParseTemplateDIE().
resolveTypeUnitReference()
DWARFDIE DWARFDIE::resolveTypeUnitReference () const
Definition at line 634 of file DWARFDIE.cpp.
References GetReferencedDIE().
Referenced by resolveReferencedType(), and resolveReferencedType().
The documentation for this class was generated from the following files:
DWARFDIE.h
DWARFDIE.cpp