LLDB: lldb_private::BreakpointID Class Reference
lldb_private::BreakpointID Class Reference
#include <BreakpointID.h>
Public Member Functions
BreakpointID (lldb::break_id_t bp_id=LLDB_INVALID_BREAK_ID, lldb::break_id_t loc_id=LLDB_INVALID_BREAK_ID)
virtual ~BreakpointID ()
bool operator== (BreakpointID rhs) const
lldb::break_id_t GetBreakpointID () const
lldb::break_id_t GetLocationID () const
void SetID (lldb::break_id_t bp_id, lldb::break_id_t loc_id)
void SetBreakpointID (lldb::break_id_t bp_id)
void SetBreakpointLocationID (lldb::break_id_t loc_id)
void GetDescription (Stream *s, lldb::DescriptionLevel level)
Static Public Member Functions
static bool IsRangeIdentifier (llvm::StringRef str)
static bool IsValidIDExpression (llvm::StringRef str)
static llvm::ArrayRef< llvm::StringRef > GetRangeSpecifiers ()
static std::optional< BreakpointID > ParseCanonicalReference (llvm::StringRef input)
Takes an input string containing the description of a breakpoint or breakpoint and location and returns a BreakpointID filled out with the proper id and location.
static bool StringIsBreakpointName (llvm::StringRef str, Status &error)
Takes an input string and checks to see whether it is a breakpoint name.
static void GetCanonicalReference (Stream *s, lldb::break_id_t break_id, lldb::break_id_t break_loc_id)
Takes a breakpoint ID and the breakpoint location id and returns a string containing the canonical description for the breakpoint or breakpoint location.
Protected Attributes
lldb::break_id_t m_break_id
lldb::break_id_t m_location_id
Detailed Description
Definition at line 22 of file BreakpointID.h.
Constructor & Destructor Documentation
BreakpointID()
BreakpointID::BreakpointID (lldb::break_id_t bp_id = LLDB_INVALID_BREAK_ID, lldb::break_id_t loc_id = LLDB_INVALID_BREAK_ID)
Definition at line 20 of file BreakpointID.cpp.
References m_break_id, and m_location_id.
Referenced by operator==(), and ParseCanonicalReference().
~BreakpointID()
BreakpointID::~BreakpointID () virtual default
Member Function Documentation
GetBreakpointID()
lldb::break_id_t lldb_private::BreakpointID::GetBreakpointID () const inline
Definition at line 33 of file BreakpointID.h.
References m_break_id.
Referenced by lldb::SBTarget::BreakpointsCreateFromFile(), CommandObjectBreakpointCommandDelete::DoExecute(), CommandObjectBreakpointCommandList::DoExecute(), CommandObjectBreakpointDelete::DoExecute(), CommandObjectBreakpointEnable::DoExecute(), CommandObjectBreakpointList::DoExecute(), CommandObjectBreakpointModify::DoExecute(), CommandObjectBreakpointNameAdd::DoExecute(), CommandObjectBreakpointNameDelete::DoExecute(), CommandObjectBreakpointRead::DoExecute(), CommandObjectProcessContinue::DoExecute(), lldb_private::Target::SerializeBreakpointsToFile(), and lldb_private::CommandObjectMultiwordBreakpoint::VerifyIDs().
GetCanonicalReference()
void BreakpointID::GetCanonicalReference (Stream * s, lldb::break_id_t break_id, lldb::break_id_t break_loc_id) static
Takes a breakpoint ID and the breakpoint location id and returns a string containing the canonical description for the breakpoint or breakpoint location.
Parameters
[out] break_id This is the break id.
[out] break_loc_id This is breakpoint location id, or LLDB_INVALID_BREAK_ID is no location is to be specified.
Definition at line 56 of file BreakpointID.cpp.
References LLDB_INVALID_BREAK_ID, lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
Referenced by CommandObjectBreakpointCommandList::DoExecute(), lldb_private::BreakpointIDList::FindAndReplaceIDRanges(), lldb_private::BreakpointLocation::GetDescription(), and lldb_private::CommandObjectMultiwordBreakpoint::VerifyIDs().
GetDescription()
void BreakpointID::GetDescription (Stream * s, lldb::DescriptionLevel level)
Definition at line 44 of file BreakpointID.cpp.
References lldb::eDescriptionLevelVerbose, LLDB_INVALID_BREAK_ID, m_break_id, m_location_id, lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
GetLocationID()
lldb::break_id_t lldb_private::BreakpointID::GetLocationID () const inline
Definition at line 35 of file BreakpointID.h.
References m_location_id.
Referenced by CommandObjectBreakpointCommandDelete::DoExecute(), CommandObjectBreakpointCommandList::DoExecute(), CommandObjectBreakpointDelete::DoExecute(), CommandObjectBreakpointEnable::DoExecute(), CommandObjectBreakpointModify::DoExecute(), CommandObjectProcessContinue::DoExecute(), and lldb_private::CommandObjectMultiwordBreakpoint::VerifyIDs().
GetRangeSpecifiers()
llvm::ArrayRef< llvm::StringRef > BreakpointID::GetRangeSpecifiers () static
Definition at line 40 of file BreakpointID.cpp.
References g_range_specifiers.
Referenced by lldb_private::BreakpointIDList::SplitIDRangeExpression().
IsRangeIdentifier()
bool BreakpointID::IsRangeIdentifier (llvm::StringRef str) static
Definition at line 32 of file BreakpointID.cpp.
References g_range_specifiers.
Referenced by lldb_private::BreakpointIDList::FindAndReplaceIDRanges().
IsValidIDExpression()
bool BreakpointID::IsValidIDExpression (llvm::StringRef str) static
Definition at line 36 of file BreakpointID.cpp.
References ParseCanonicalReference().
Referenced by lldb_private::BreakpointIDList::FindAndReplaceIDRanges(), and lldb_private::BreakpointIDList::SplitIDRangeExpression().
operator==()
bool lldb_private::BreakpointID::operator== (BreakpointID rhs) const inline
Definition at line 29 of file BreakpointID.h.
References BreakpointID(), m_break_id, and m_location_id.
ParseCanonicalReference()
std::optional< BreakpointID > BreakpointID::ParseCanonicalReference (llvm::StringRef input) static
Takes an input string containing the description of a breakpoint or breakpoint and location and returns a BreakpointID filled out with the proper id and location.
Parameters
[in] input A string containing JUST the breakpoint description.
Returns
If input was not a valid breakpoint ID string, returns std::nullopt. Otherwise returns a BreakpointID with members filled out accordingly.
Definition at line 67 of file BreakpointID.cpp.
References BreakpointID(), and LLDB_INVALID_BREAK_ID.
Referenced by lldb_private::BreakpointIDList::FindAndReplaceIDRanges(), IsValidIDExpression(), and lldb_private::CommandObjectMultiwordBreakpoint::VerifyIDs().
SetBreakpointID()
void lldb_private::BreakpointID::SetBreakpointID (lldb::break_id_t bp_id) inline
Definition at line 42 of file BreakpointID.h.
References m_break_id.
SetBreakpointLocationID()
void lldb_private::BreakpointID::SetBreakpointLocationID (lldb::break_id_t loc_id) inline
Definition at line 44 of file BreakpointID.h.
References m_location_id.
Referenced by CommandObjectProcessContinue::DoExecute().
SetID()
void lldb_private::BreakpointID::SetID (lldb::break_id_t bp_id, lldb::break_id_t loc_id) inline
Definition at line 37 of file BreakpointID.h.
References m_break_id, and m_location_id.
StringIsBreakpointName()
bool BreakpointID::StringIsBreakpointName (llvm::StringRef str, Status & error) static
Takes an input string and checks to see whether it is a breakpoint name.
If it is a mal-formed breakpoint name, error will be set to an appropriate error string.
Parameters
[in] str A string containing JUST the breakpoint description.
[out] error If the name is a well-formed breakpoint name, set to success, otherwise set to an error.
Returns
true if the name is a breakpoint name (as opposed to an ID or range) false otherwise.
Definition at line 91 of file BreakpointID.cpp.
References error(), lldb_private::Status::FromErrorString(), and lldb_private::Status::FromErrorStringWithFormatv().
Referenced by CommandObjectBreakpointNameConfigure::DoExecute(), lldb_private::BreakpointIDList::FindAndReplaceIDRanges(), lldb_private::Target::FindBreakpointName(), lldb_private::BreakpointList::FindBreakpointsByName(), BreakpointNameOptionGroup::SetOptionValue(), BreakpointNamesOptionGroup::SetOptionValue(), CommandObjectBreakpointRead::CommandOptions::SetOptionValue(), and CommandObjectBreakpointSet::CommandOptions::SetOptionValue().
Member Data Documentation
m_break_id
lldb::break_id_t lldb_private::BreakpointID::m_break_id protected
Definition at line 95 of file BreakpointID.h.
Referenced by BreakpointID(), GetBreakpointID(), GetDescription(), operator==(), SetBreakpointID(), and SetID().
m_location_id
lldb::break_id_t lldb_private::BreakpointID::m_location_id protected
Definition at line 96 of file BreakpointID.h.
Referenced by BreakpointID(), GetDescription(), GetLocationID(), operator==(), SetBreakpointLocationID(), and SetID().
The documentation for this class was generated from the following files:
BreakpointID.h
BreakpointID.cpp