LLDB: lldb_private::ScriptInterpreterPythonImpl Class Reference
lldb_private::ScriptInterpreterPythonImpl Class Reference
#include <ScriptInterpreterPythonImpl.h>
Classes
class Locker
class SynchronicityHandler
Public Types
enum class AddLocation { Beginning , End }
enum ActiveIOHandler { eIOHandlerNone , eIOHandlerBreakpoint , eIOHandlerWatchpoint }
Public Types inherited from lldb_private::ScriptInterpreter
enum ScriptReturnType {
eScriptReturnTypeCharPtr , eScriptReturnTypeBool , eScriptReturnTypeShortInt , eScriptReturnTypeShortIntUnsigned ,
eScriptReturnTypeInt , eScriptReturnTypeIntUnsigned , eScriptReturnTypeLongInt , eScriptReturnTypeLongIntUnsigned ,
eScriptReturnTypeLongLong , eScriptReturnTypeLongLongUnsigned , eScriptReturnTypeFloat , eScriptReturnTypeDouble ,
eScriptReturnTypeChar , eScriptReturnTypeCharStrOrNone , eScriptReturnTypeOpaqueObject
}
Public Types inherited from lldb_private::IOHandlerDelegate
enum class Completion { None , LLDBCommand , Expression }
Public Member Functions
ScriptInterpreterPythonImpl (Debugger &debugger)
~ScriptInterpreterPythonImpl () override
bool Interrupt () override
bool ExecuteOneLine (llvm::StringRef command, CommandReturnObject *result, const ExecuteScriptOptions &options=ExecuteScriptOptions()) override
void ExecuteInterpreterLoop () override
bool ExecuteOneLineWithReturn (llvm::StringRef in_string, ScriptInterpreter::ScriptReturnType return_type, void *ret_value, const ExecuteScriptOptions &options=ExecuteScriptOptions()) override
lldb_private::Status ExecuteMultipleLines (const char *in_string, const ExecuteScriptOptions &options=ExecuteScriptOptions()) override
Status ExportFunctionDefinitionToInterpreter (StringList &function_def) override
bool GenerateTypeScriptFunction (StringList &input, std::string &output, const void *name_token=nullptr) override
bool GenerateTypeSynthClass (StringList &input, std::string &output, const void *name_token=nullptr) override
bool GenerateTypeSynthClass (const char *oneliner, std::string &output, const void *name_token=nullptr) override
bool GenerateTypeScriptFunction (const char *oneliner, std::string &output, const void *name_token=nullptr) override
bool GenerateScriptAliasFunction (StringList &input, std::string &output) override
StructuredData::ObjectSP CreateSyntheticScriptedProvider (const char *class_name, lldb::ValueObjectSP valobj) override
StructuredData::GenericSP CreateScriptCommandObject (const char *class_name) override
StructuredData::ObjectSP CreateStructuredDataFromScriptObject (ScriptObject obj) override
StructuredData::GenericSP CreateFrameRecognizer (const char *class_name) override
lldb::ValueObjectListSP GetRecognizedArguments (const StructuredData::ObjectSP &implementor, lldb::StackFrameSP frame_sp) override
bool ShouldHide (const StructuredData::ObjectSP &implementor, lldb::StackFrameSP frame_sp) override
lldb::ScriptedProcessInterfaceUP CreateScriptedProcessInterface () override
lldb::ScriptedStopHookInterfaceSP CreateScriptedStopHookInterface () override
lldb::ScriptedBreakpointInterfaceSP CreateScriptedBreakpointInterface () override
lldb::ScriptedThreadInterfaceSP CreateScriptedThreadInterface () override
lldb::ScriptedFrameInterfaceSP CreateScriptedFrameInterface () override
lldb::ScriptedFrameProviderInterfaceSP CreateScriptedFrameProviderInterface () override
lldb::ScriptedThreadPlanInterfaceSP CreateScriptedThreadPlanInterface () override
lldb::OperatingSystemInterfaceSP CreateOperatingSystemInterface () override
StructuredData::ObjectSP LoadPluginModule (const FileSpec &file_spec, lldb_private::Status &error) override
StructuredData::DictionarySP GetDynamicSettings (StructuredData::ObjectSP plugin_module_sp, Target *target, const char *setting_name, lldb_private::Status &error) override
size_t CalculateNumChildren (const StructuredData::ObjectSP &implementor, uint32_t max) override
lldb::ValueObjectSP GetChildAtIndex (const StructuredData::ObjectSP &implementor, uint32_t idx) override
llvm::Expected< uint32_t > GetIndexOfChildWithName (const StructuredData::ObjectSP &implementor, const char *child_name) override
bool UpdateSynthProviderInstance (const StructuredData::ObjectSP &implementor) override
bool MightHaveChildrenSynthProviderInstance (const StructuredData::ObjectSP &implementor) override
lldb::ValueObjectSP GetSyntheticValue (const StructuredData::ObjectSP &implementor) override
ConstString GetSyntheticTypeName (const StructuredData::ObjectSP &implementor) override
bool RunScriptBasedCommand (const char *impl_function, llvm::StringRef args, ScriptedCommandSynchronicity synchronicity, lldb_private::CommandReturnObject &cmd_retobj, Status &error, const lldb_private::ExecutionContext &exe_ctx) override
bool RunScriptBasedCommand (StructuredData::GenericSP impl_obj_sp, llvm::StringRef args, ScriptedCommandSynchronicity synchronicity, lldb_private::CommandReturnObject &cmd_retobj, Status &error, const lldb_private::ExecutionContext &exe_ctx) override
bool RunScriptBasedParsedCommand (StructuredData::GenericSP impl_obj_sp, Args &args, ScriptedCommandSynchronicity synchronicity, lldb_private::CommandReturnObject &cmd_retobj, Status &error, const lldb_private::ExecutionContext &exe_ctx) override
std::optional< std::string > GetRepeatCommandForScriptedCommand (StructuredData::GenericSP impl_obj_sp, Args &args) override
StructuredData::DictionarySP HandleArgumentCompletionForScriptedCommand (StructuredData::GenericSP impl_obj_sp, std::vector< llvm::StringRef > &args, size_t args_pos, size_t char_in_arg) override
StructuredData::DictionarySP HandleOptionArgumentCompletionForScriptedCommand (StructuredData::GenericSP impl_obj_sp, llvm::StringRef &long_options, size_t char_in_arg) override
Status GenerateFunction (const char *signature, const StringList &input, bool is_callback) override
Status GenerateBreakpointCommandCallbackData (StringList &input, std::string &output, bool has_extra_args, bool is_callback) override
bool GenerateWatchpointCommandCallbackData (StringList &input, std::string &output, bool is_callback) override
bool GetScriptedSummary (const char *function_name, lldb::ValueObjectSP valobj, StructuredData::ObjectSP &callee_wrapper_sp, const TypeSummaryOptions &options, std::string &retval) override
bool FormatterCallbackFunction (const char *function_name, lldb::TypeImplSP type_impl_sp) override
bool GetDocumentationForItem (const char *item, std::string &dest) override
In Python, a special attribute doc contains the docstring for an object (function, method, class, ...) if any is defined Otherwise, the attribute's value is None.
bool GetShortHelpForCommandObject (StructuredData::GenericSP cmd_obj_sp, std::string &dest) override
uint32_t GetFlagsForCommandObject (StructuredData::GenericSP cmd_obj_sp) override
bool GetLongHelpForCommandObject (StructuredData::GenericSP cmd_obj_sp, std::string &dest) override
StructuredData::ObjectSP GetOptionsForCommandObject (StructuredData::GenericSP cmd_obj_sp) override
StructuredData::ObjectSP GetArgumentsForCommandObject (StructuredData::GenericSP cmd_obj_sp) override
bool SetOptionValueForCommandObject (StructuredData::GenericSP cmd_obj_sp, ExecutionContext *exe_ctx, llvm::StringRef long_option, llvm::StringRef value) override
void OptionParsingStartedForCommandObject (StructuredData::GenericSP cmd_obj_sp) override
bool CheckObjectExists (const char *name) override
bool RunScriptFormatKeyword (const char *impl_function, Process *process, std::string &output, Status &error) override
bool RunScriptFormatKeyword (const char *impl_function, Thread *thread, std::string &output, Status &error) override
bool RunScriptFormatKeyword (const char *impl_function, Target *target, std::string &output, Status &error) override
bool RunScriptFormatKeyword (const char *impl_function, StackFrame *frame, std::string &output, Status &error) override
bool RunScriptFormatKeyword (const char *impl_function, ValueObject *value, std::string &output, Status &error) override
bool LoadScriptingModule (const char *filename, const LoadScriptOptions &options, lldb_private::Status &error, StructuredData::ObjectSP *module_sp=nullptr, FileSpec extra_search_dir={}, lldb::TargetSP loaded_into_target_sp={}) override
bool IsReservedWord (const char *word) override
std::unique_ptr< ScriptInterpreterLocker > AcquireInterpreterLock () override
void CollectDataForBreakpointCommandCallback (std::vector< std::reference_wrapper< BreakpointOptions > > &bp_options_vec, CommandReturnObject &result) override
void CollectDataForWatchpointCommandCallback (WatchpointOptions *wp_options, CommandReturnObject &result) override
Status SetBreakpointCommandCallback (BreakpointOptions &bp_options, const char *callback_body, bool is_callback) override
Set the callback body text into the callback for the breakpoint.
Status SetBreakpointCommandCallbackFunction (BreakpointOptions &bp_options, const char *function_name, StructuredData::ObjectSP extra_args_sp) override
Set a script function as the callback for the breakpoint.
Status SetBreakpointCommandCallback (BreakpointOptions &bp_options, std::unique_ptr< BreakpointOptions::CommandData > &data_up) override
This one is for deserialization:
Status SetBreakpointCommandCallback (BreakpointOptions &bp_options, const char *command_body_text, StructuredData::ObjectSP extra_args_sp, bool uses_extra_args, bool is_callback)
void SetWatchpointCommandCallback (WatchpointOptions *wp_options, const char *user_input, bool is_callback) override
Set a one-liner as the callback for the watchpoint.
const char * GetDictionaryName ()
PyThreadState * GetThreadState ()
void SetThreadState (PyThreadState *s)
void IOHandlerActivated (IOHandler &io_handler, bool interactive) override
void IOHandlerInputComplete (IOHandler &io_handler, std::string &data) override
Called when a line or lines have been retrieved.
llvm::StringRef GetPluginName () override
bool EnterSession (uint16_t on_entry_flags, lldb::FileSP in, lldb::FileSP out, lldb::FileSP err)
void LeaveSession ()
uint32_t IsExecutingPython ()
uint32_t IncrementLockCount ()
uint32_t DecrementLockCount ()
python::PythonModule & GetMainModule ()
python::PythonDictionary & GetSessionDictionary ()
python::PythonDictionary & GetSysModuleDictionary ()
llvm::Expected< unsigned > GetMaxPositionalArgumentsForCallable (const llvm::StringRef &callable_name) override
bool GetEmbeddedInterpreterModuleObjects ()
bool SetStdHandle (lldb::FileSP file, const char *py_name, python::PythonObject &save_file, const char *mode)
Public Member Functions inherited from lldb_private::ScriptInterpreterPython
ScriptInterpreterPython (Debugger &debugger)
StructuredData::DictionarySP GetInterpreterInfo () override
Public Member Functions inherited from lldb_private::ScriptInterpreter
ScriptInterpreter (Debugger &debugger, lldb::ScriptLanguage script_lang)
~ScriptInterpreter () override=default
Status SetBreakpointCommandCallback (std::vector< std::reference_wrapper< BreakpointOptions > > &bp_options_vec, const char *callback_text)
Set the specified text as the callback for the breakpoint.
Status SetBreakpointCommandCallbackFunction (std::vector< std::reference_wrapper< BreakpointOptions > > &bp_options_vec, const char *function_name, StructuredData::ObjectSP extra_args_sp)
virtual void Clear ()
const char * GetScriptInterpreterPtyName ()
lldb::ScriptLanguage GetLanguage ()
virtual lldb::ScriptedPlatformInterfaceUP GetScriptedPlatformInterface ()
lldb::DataExtractorSP GetDataExtractorFromSBData (const lldb::SBData &data) const
Status GetStatusFromSBError (const lldb::SBError &error) const
Event * GetOpaqueTypeFromSBEvent (const lldb::SBEvent &event) const
lldb::StreamSP GetOpaqueTypeFromSBStream (const lldb::SBStream &stream) const
lldb::ThreadSP GetOpaqueTypeFromSBThread (const lldb::SBThread &exe_ctx) const
lldb::StackFrameSP GetOpaqueTypeFromSBFrame (const lldb::SBFrame &frame) const
SymbolContext GetOpaqueTypeFromSBSymbolContext (const lldb::SBSymbolContext &sym_ctx) const
lldb::BreakpointSP GetOpaqueTypeFromSBBreakpoint (const lldb::SBBreakpoint &breakpoint) const
lldb::BreakpointLocationSP GetOpaqueTypeFromSBBreakpointLocation (const lldb::SBBreakpointLocation &break_loc) const
lldb::ProcessAttachInfoSP GetOpaqueTypeFromSBAttachInfo (const lldb::SBAttachInfo &attach_info) const
lldb::ProcessLaunchInfoSP GetOpaqueTypeFromSBLaunchInfo (const lldb::SBLaunchInfo &launch_info) const
std::optional< MemoryRegionInfo > GetOpaqueTypeFromSBMemoryRegionInfo (const lldb::SBMemoryRegionInfo &mem_region) const
lldb::ExecutionContextRefSP GetOpaqueTypeFromSBExecutionContext (const lldb::SBExecutionContext &exe_ctx) const
lldb::StackFrameListSP GetOpaqueTypeFromSBFrameList (const lldb::SBFrameList &exe_ctx) const
lldb::ValueObjectSP GetOpaqueTypeFromSBValue (const lldb::SBValue &value) const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Public Member Functions inherited from lldb_private::IOHandlerDelegateMultiline
IOHandlerDelegateMultiline (llvm::StringRef end_line, Completion completion=Completion::None)
~IOHandlerDelegateMultiline () override=default
llvm::StringRef IOHandlerGetControlSequence (char ch) override
bool IOHandlerIsInputComplete (IOHandler &io_handler, StringList &lines) override
Called to determine whether typing enter after the last line in lines should end input.
Public Member Functions inherited from lldb_private::IOHandlerDelegate
IOHandlerDelegate (Completion completion=Completion::None)
virtual ~IOHandlerDelegate ()=default
virtual void IOHandlerDeactivated (IOHandler &io_handler)
virtual std::optional< std::string > IOHandlerSuggestion (IOHandler &io_handler, llvm::StringRef line)
virtual void IOHandlerComplete (IOHandler &io_handler, CompletionRequest &request)
virtual const char * IOHandlerGetFixIndentationCharacters ()
virtual int IOHandlerFixIndentation (IOHandler &io_handler, const StringList &lines, int cursor_position)
Called when a new line is created or one of an identified set of indentation characters is typed.
virtual void IOHandlerInputInterrupted (IOHandler &io_handler, std::string &data)
virtual const char * IOHandlerGetCommandPrefix ()
virtual const char * IOHandlerGetHelpPrologue ()
virtual bool IOHandlerInterrupt (IOHandler &io_handler)
Static Public Member Functions
static lldb::ScriptInterpreterSP CreateInstance (Debugger &debugger)
static bool BreakpointCallbackFunction (void *baton, StoppointCallbackContext *context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id)
static bool WatchpointCallbackFunction (void *baton, StoppointCallbackContext *context, lldb::user_id_t watch_id)
static void Initialize ()
static void AddToSysPath (AddLocation location, std::string path)
Static Public Member Functions inherited from lldb_private::ScriptInterpreterPython
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static FileSpec GetPythonDir ()
static void SharedLibraryDirectoryHelper (FileSpec &this_file)
Static Public Member Functions inherited from lldb_private::ScriptInterpreter
static std::string LanguageToString (lldb::ScriptLanguage language)
static lldb::ScriptLanguage StringToLanguage (const llvm::StringRef &string)
Public Attributes
python::PythonObject m_saved_stdin
python::PythonObject m_saved_stdout
python::PythonObject m_saved_stderr
python::PythonModule m_main_module
python::PythonDictionary m_session_dict
python::PythonDictionary m_sys_module_dict
python::PythonObject m_run_one_line_function
python::PythonObject m_run_one_line_str_global
std::string m_dictionary_name
ActiveIOHandler m_active_io_handler
bool m_session_is_active
bool m_pty_secondary_is_open
bool m_valid_session
uint32_t m_lock_count
std::mutex m_mutex
PyThreadState * m_command_thread_state
Friends
class IOHandlerPythonInterpreter
Additional Inherited Members
Static Protected Member Functions inherited from lldb_private::ScriptInterpreterPython
static void ComputePythonDirForApple (llvm::SmallVectorImpl< char > &path)
static void ComputePythonDir (llvm::SmallVectorImpl< char > &path)
Protected Attributes inherited from lldb_private::ScriptInterpreter
Debugger & m_debugger
lldb::ScriptLanguage m_script_lang
Protected Attributes inherited from lldb_private::IOHandlerDelegateMultiline
const std::string m_end_line
Protected Attributes inherited from lldb_private::IOHandlerDelegate
Completion m_completion
Detailed Description
Definition at line 25 of file ScriptInterpreterPythonImpl.h.
Member Enumeration Documentation
ActiveIOHandler
enum lldb_private::ScriptInterpreterPythonImpl::ActiveIOHandler
Enumerator
eIOHandlerNone
eIOHandlerBreakpoint
eIOHandlerWatchpoint
Definition at line 388 of file ScriptInterpreterPythonImpl.h.
AddLocation
enum class lldb_private::ScriptInterpreterPythonImpl::AddLocation strong
Enumerator
Beginning
End
Definition at line 362 of file ScriptInterpreterPythonImpl.h.
Constructor & Destructor Documentation
ScriptInterpreterPythonImpl()
ScriptInterpreterPythonImpl::ScriptInterpreterPythonImpl (Debugger & debugger)
Definition at line 369 of file ScriptInterpreterPython.cpp.
References lldb_private::ScriptInterpreterPythonImpl::Locker::AcquireLock, lldb_private::StreamString::Clear(), eIOHandlerNone, lldb_private::ScriptInterpreterPythonImpl::Locker::FreeAcquiredLock, lldb_private::StreamString::GetData(), lldb_private::Invalid, m_active_io_handler, m_command_thread_state, lldb_private::ScriptInterpreter::m_debugger, m_dictionary_name, m_lock_count, m_main_module, m_pty_secondary_is_open, m_run_one_line_function, m_run_one_line_str_global, m_saved_stderr, m_saved_stdin, m_saved_stdout, m_session_dict, m_session_is_active, m_sys_module_dict, m_valid_session, lldb_private::Stream::Printf(), lldb_private::python::RunSimpleString(), and lldb_private::ScriptInterpreterPython::ScriptInterpreterPython().
Referenced by lldb_private::ScriptInterpreterPythonImpl::Locker::Locker().
~ScriptInterpreterPythonImpl()
ScriptInterpreterPythonImpl::~ScriptInterpreterPythonImpl () override
Definition at line 425 of file ScriptInterpreterPython.cpp.
References m_session_dict.
Member Function Documentation
AcquireInterpreterLock()
std::unique_ptr< ScriptInterpreterLocker > ScriptInterpreterPythonImpl::AcquireInterpreterLock () override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 3006 of file ScriptInterpreterPython.cpp.
AddToSysPath()
void ScriptInterpreterPythonImpl::AddToSysPath (AddLocation location, std::string path) static
Definition at line 3064 of file ScriptInterpreterPython.cpp.
BreakpointCallbackFunction()
bool ScriptInterpreterPythonImpl::BreakpointCallbackFunction (void * baton, StoppointCallbackContext * context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id) static
Definition at line 1776 of file ScriptInterpreterPython.cpp.
References lldb_private::ScriptInterpreterPythonImpl::Locker::AcquireLock, lldb_private::ScriptInterpreterPythonImpl::Locker::InitSession, m_dictionary_name, and lldb_private::ScriptInterpreterPythonImpl::Locker::NoSTDIN.
Referenced by SetBreakpointCommandCallback().
CalculateNumChildren()
size_t ScriptInterpreterPythonImpl::CalculateNumChildren (const StructuredData::ObjectSP & implementor, uint32_t max) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1887 of file ScriptInterpreterPython.cpp.
CheckObjectExists()
bool lldb_private::ScriptInterpreterPythonImpl::CheckObjectExists (const char * name) inline override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 216 of file ScriptInterpreterPythonImpl.h.
References GetDocumentationForItem().
CollectDataForBreakpointCommandCallback()
void ScriptInterpreterPythonImpl::CollectDataForBreakpointCommandCallback (std::vector< std::reference_wrapper< BreakpointOptions > > & bp_options_vec, CommandReturnObject & result) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1094 of file ScriptInterpreterPython.cpp.
CollectDataForWatchpointCommandCallback()
void ScriptInterpreterPythonImpl::CollectDataForWatchpointCommandCallback (WatchpointOptions * wp_options, CommandReturnObject & result) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1102 of file ScriptInterpreterPython.cpp.
References eIOHandlerBreakpoint, m_active_io_handler, and lldb_private::ScriptInterpreter::m_debugger.
CreateFrameRecognizer()
StructuredData::GenericSP ScriptInterpreterPythonImpl::CreateFrameRecognizer (const char * class_name) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1415 of file ScriptInterpreterPython.cpp.
CreateInstance()
lldb::ScriptInterpreterSP ScriptInterpreterPythonImpl::CreateInstance (Debugger & debugger) static
Definition at line 522 of file ScriptInterpreterPython.cpp.
Referenced by lldb_private::ScriptInterpreterPython::Initialize().
CreateOperatingSystemInterface()
OperatingSystemInterfaceSP ScriptInterpreterPythonImpl::CreateOperatingSystemInterface () override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1536 of file ScriptInterpreterPython.cpp.
CreateScriptCommandObject()
StructuredData::GenericSP ScriptInterpreterPythonImpl::CreateScriptCommandObject (const char * class_name) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1630 of file ScriptInterpreterPython.cpp.
CreateScriptedBreakpointInterface()
ScriptedBreakpointInterfaceSP ScriptInterpreterPythonImpl::CreateScriptedBreakpointInterface () override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1511 of file ScriptInterpreterPython.cpp.
CreateScriptedFrameInterface()
ScriptedFrameInterfaceSP ScriptInterpreterPythonImpl::CreateScriptedFrameInterface () override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1521 of file ScriptInterpreterPython.cpp.
CreateScriptedFrameProviderInterface()
ScriptedFrameProviderInterfaceSP ScriptInterpreterPythonImpl::CreateScriptedFrameProviderInterface () override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1526 of file ScriptInterpreterPython.cpp.
CreateScriptedProcessInterface()
ScriptedProcessInterfaceUP ScriptInterpreterPythonImpl::CreateScriptedProcessInterface () override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1501 of file ScriptInterpreterPython.cpp.
CreateScriptedStopHookInterface()
ScriptedStopHookInterfaceSP ScriptInterpreterPythonImpl::CreateScriptedStopHookInterface () override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1506 of file ScriptInterpreterPython.cpp.
CreateScriptedThreadInterface()
ScriptedThreadInterfaceSP ScriptInterpreterPythonImpl::CreateScriptedThreadInterface () override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1516 of file ScriptInterpreterPython.cpp.
CreateScriptedThreadPlanInterface()
ScriptedThreadPlanInterfaceSP ScriptInterpreterPythonImpl::CreateScriptedThreadPlanInterface () override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1531 of file ScriptInterpreterPython.cpp.
CreateStructuredDataFromScriptObject()
StructuredData::ObjectSP ScriptInterpreterPythonImpl::CreateStructuredDataFromScriptObject (ScriptObject obj) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1541 of file ScriptInterpreterPython.cpp.
CreateSyntheticScriptedProvider()
StructuredData::ObjectSP ScriptInterpreterPythonImpl::CreateSyntheticScriptedProvider (const char * class_name, lldb::ValueObjectSP valobj) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1599 of file ScriptInterpreterPython.cpp.
DecrementLockCount()
uint32_t lldb_private::ScriptInterpreterPythonImpl::DecrementLockCount () inline
Definition at line 381 of file ScriptInterpreterPythonImpl.h.
References m_lock_count, and m_mutex.
EnterSession()
bool ScriptInterpreterPythonImpl::EnterSession (uint16_t on_entry_flags, lldb::FileSP in, lldb::FileSP out, lldb::FileSP err)
Definition at line 588 of file ScriptInterpreterPython.cpp.
ExecuteInterpreterLoop()
void ScriptInterpreterPythonImpl::ExecuteInterpreterLoop () override virtual
Implements lldb_private::ScriptInterpreter.
Definition at line 858 of file ScriptInterpreterPython.cpp.
ExecuteMultipleLines()
Status ScriptInterpreterPythonImpl::ExecuteMultipleLines (const char * in_string, const ExecuteScriptOptions & options = ExecuteScriptOptions()) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1043 of file ScriptInterpreterPython.cpp.
ExecuteOneLine()
bool ScriptInterpreterPythonImpl::ExecuteOneLine (llvm::StringRef command, CommandReturnObject * result, const ExecuteScriptOptions & options = ExecuteScriptOptions()) override virtual
Implements lldb_private::ScriptInterpreter.
Definition at line 766 of file ScriptInterpreterPython.cpp.
References m_run_one_line_function, and m_run_one_line_str_global.
ExecuteOneLineWithReturn()
bool ScriptInterpreterPythonImpl::ExecuteOneLineWithReturn (llvm::StringRef in_string, ScriptInterpreter::ScriptReturnType return_type, void * ret_value, const ExecuteScriptOptions & options = ExecuteScriptOptions()) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 919 of file ScriptInterpreterPython.cpp.
ExportFunctionDefinitionToInterpreter()
Status ScriptInterpreterPythonImpl::ExportFunctionDefinitionToInterpreter (StringList & function_def) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1223 of file ScriptInterpreterPython.cpp.
References WatchpointCallbackFunction().
FormatterCallbackFunction()
bool ScriptInterpreterPythonImpl::FormatterCallbackFunction (const char * function_name, lldb::TypeImplSP type_impl_sp) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1768 of file ScriptInterpreterPython.cpp.
GenerateBreakpointCommandCallbackData()
Status ScriptInterpreterPythonImpl::GenerateBreakpointCommandCallbackData (StringList & input, std::string & output, bool has_extra_args, bool is_callback) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1665 of file ScriptInterpreterPython.cpp.
GenerateFunction()
Status ScriptInterpreterPythonImpl::GenerateFunction (const char * signature, const StringList & input, bool is_callback) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1235 of file ScriptInterpreterPython.cpp.
References error().
GenerateScriptAliasFunction()
bool ScriptInterpreterPythonImpl::GenerateScriptAliasFunction (StringList & input, std::string & output) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1345 of file ScriptInterpreterPython.cpp.
GenerateTypeScriptFunction() [1/2]
bool ScriptInterpreterPythonImpl::GenerateTypeScriptFunction (const char * oneliner, std::string & output, const void * name_token = nullptr) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1651 of file ScriptInterpreterPython.cpp.
GenerateTypeScriptFunction() [2/2]
bool ScriptInterpreterPythonImpl::GenerateTypeScriptFunction (StringList & input, std::string & output, const void * name_token = nullptr) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1317 of file ScriptInterpreterPython.cpp.
References error().
GenerateTypeSynthClass() [1/2]
bool ScriptInterpreterPythonImpl::GenerateTypeSynthClass (const char * oneliner, std::string & output, const void * name_token = nullptr) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1658 of file ScriptInterpreterPython.cpp.
GenerateTypeSynthClass() [2/2]
bool ScriptInterpreterPythonImpl::GenerateTypeSynthClass (StringList & input, std::string & output, const void * name_token = nullptr) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1370 of file ScriptInterpreterPython.cpp.
GenerateWatchpointCommandCallbackData()
bool ScriptInterpreterPythonImpl::GenerateWatchpointCommandCallbackData (StringList & input, std::string & output, bool is_callback) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1695 of file ScriptInterpreterPython.cpp.
References error().
GetArgumentsForCommandObject()
StructuredData::ObjectSP ScriptInterpreterPythonImpl::GetArgumentsForCommandObject (StructuredData::GenericSP cmd_obj_sp) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2822 of file ScriptInterpreterPython.cpp.
GetChildAtIndex()
lldb::ValueObjectSP ScriptInterpreterPythonImpl::GetChildAtIndex (const StructuredData::ObjectSP & implementor, uint32_t idx) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1909 of file ScriptInterpreterPython.cpp.
GetDictionaryName()
const char * lldb_private::ScriptInterpreterPythonImpl::GetDictionaryName () inline
Definition at line 282 of file ScriptInterpreterPythonImpl.h.
References m_dictionary_name.
GetDocumentationForItem()
bool ScriptInterpreterPythonImpl::GetDocumentationForItem (const char * item, std::string & dest) override virtual
In Python, a special attribute doc contains the docstring for an object (function, method, class, ...) if any is defined Otherwise, the attribute's value is None.
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2659 of file ScriptInterpreterPython.cpp.
Referenced by CheckObjectExists().
GetDynamicSettings()
StructuredData::DictionarySP ScriptInterpreterPythonImpl::GetDynamicSettings (StructuredData::ObjectSP plugin_module_sp, Target * target, const char * setting_name, lldb_private::Status & error) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1570 of file ScriptInterpreterPython.cpp.
GetEmbeddedInterpreterModuleObjects()
bool ScriptInterpreterPythonImpl::GetEmbeddedInterpreterModuleObjects ()
Definition at line 745 of file ScriptInterpreterPython.cpp.
GetFlagsForCommandObject()
uint32_t ScriptInterpreterPythonImpl::GetFlagsForCommandObject (StructuredData::GenericSP cmd_obj_sp) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2724 of file ScriptInterpreterPython.cpp.
GetIndexOfChildWithName()
llvm::Expected< uint32_t > ScriptInterpreterPythonImpl::GetIndexOfChildWithName (const StructuredData::ObjectSP & implementor, const char * child_name) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1943 of file ScriptInterpreterPython.cpp.
GetLongHelpForCommandObject()
bool ScriptInterpreterPythonImpl::GetLongHelpForCommandObject (StructuredData::GenericSP cmd_obj_sp, std::string & dest) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2969 of file ScriptInterpreterPython.cpp.
GetMainModule()
PythonModule & ScriptInterpreterPythonImpl::GetMainModule ()
Definition at line 673 of file ScriptInterpreterPython.cpp.
GetMaxPositionalArgumentsForCallable()
llvm::Expected< unsigned > ScriptInterpreterPythonImpl::GetMaxPositionalArgumentsForCallable (const llvm::StringRef & callable_name) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 706 of file ScriptInterpreterPython.cpp.
References m_sys_module_dict.
GetOptionsForCommandObject()
StructuredData::ObjectSP ScriptInterpreterPythonImpl::GetOptionsForCommandObject (StructuredData::GenericSP cmd_obj_sp) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2774 of file ScriptInterpreterPython.cpp.
GetPluginName()
llvm::StringRef lldb_private::ScriptInterpreterPythonImpl::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 300 of file ScriptInterpreterPythonImpl.h.
References lldb_private::ScriptInterpreterPython::GetPluginNameStatic().
GetRecognizedArguments()
lldb::ValueObjectListSP ScriptInterpreterPythonImpl::GetRecognizedArguments (const StructuredData::ObjectSP & implementor, lldb::StackFrameSP frame_sp) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1427 of file ScriptInterpreterPython.cpp.
GetRepeatCommandForScriptedCommand()
std::optional< std::string > ScriptInterpreterPythonImpl::GetRepeatCommandForScriptedCommand (StructuredData::GenericSP impl_obj_sp, Args & args) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2589 of file ScriptInterpreterPython.cpp.
References error().
GetScriptedSummary()
bool ScriptInterpreterPythonImpl::GetScriptedSummary (const char * function_name, lldb::ValueObjectSP valobj, StructuredData::ObjectSP & callee_wrapper_sp, const TypeSummaryOptions & options, std::string & retval) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1717 of file ScriptInterpreterPython.cpp.
GetSessionDictionary()
PythonDictionary & ScriptInterpreterPythonImpl::GetSessionDictionary ()
Definition at line 679 of file ScriptInterpreterPython.cpp.
References lldb_private::python::PythonModule::Import(), and m_main_module.
GetShortHelpForCommandObject()
bool ScriptInterpreterPythonImpl::GetShortHelpForCommandObject (StructuredData::GenericSP cmd_obj_sp, std::string & dest) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2689 of file ScriptInterpreterPython.cpp.
GetSyntheticTypeName()
ConstString ScriptInterpreterPythonImpl::GetSyntheticTypeName (const StructuredData::ObjectSP & implementor) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2052 of file ScriptInterpreterPython.cpp.
GetSyntheticValue()
lldb::ValueObjectSP ScriptInterpreterPythonImpl::GetSyntheticValue (const StructuredData::ObjectSP & implementor) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2017 of file ScriptInterpreterPython.cpp.
GetSysModuleDictionary()
PythonDictionary & ScriptInterpreterPythonImpl::GetSysModuleDictionary ()
Definition at line 697 of file ScriptInterpreterPython.cpp.
References lldb_private::python::As(), m_dictionary_name, and m_session_dict.
GetThreadState()
PyThreadState * lldb_private::ScriptInterpreterPythonImpl::GetThreadState () inline
Definition at line 284 of file ScriptInterpreterPythonImpl.h.
References m_command_thread_state.
HandleArgumentCompletionForScriptedCommand()
StructuredData::DictionarySP ScriptInterpreterPythonImpl::HandleArgumentCompletionForScriptedCommand (StructuredData::GenericSP impl_obj_sp, std::vector< llvm::StringRef > & args, size_t args_pos, size_t char_in_arg) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2617 of file ScriptInterpreterPython.cpp.
HandleOptionArgumentCompletionForScriptedCommand()
StructuredData::DictionarySP ScriptInterpreterPythonImpl::HandleOptionArgumentCompletionForScriptedCommand (StructuredData::GenericSP impl_obj_sp, llvm::StringRef & long_options, size_t char_in_arg) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2637 of file ScriptInterpreterPython.cpp.
IncrementLockCount()
uint32_t lldb_private::ScriptInterpreterPythonImpl::IncrementLockCount () inline
Definition at line 376 of file ScriptInterpreterPythonImpl.h.
References m_lock_count, and m_mutex.
Initialize()
void ScriptInterpreterPythonImpl::Initialize () static
Definition at line 3013 of file ScriptInterpreterPython.cpp.
References lldb_private::ScriptInterpreterPythonImpl::Locker::AcquireLock, lldb_private::ScriptInterpreterPythonImpl::Locker::FreeLock, lldb_private::ScriptInterpreterPythonImpl::Locker::InitSession, lldb_private::ScriptInterpreterPythonImpl::Locker::NoSTDIN, and lldb_private::ScriptInterpreterPythonImpl::Locker::TearDownSession.
Referenced by lldb_private::ScriptInterpreterPython::Initialize().
Interrupt()
bool ScriptInterpreterPythonImpl::Interrupt () override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 878 of file ScriptInterpreterPython.cpp.
References lldb_private::Debugger::RunIOHandlerAsync().
IOHandlerActivated()
void ScriptInterpreterPythonImpl::IOHandlerActivated (IOHandler & io_handler, bool interactive) override virtual
Reimplemented from lldb_private::IOHandlerDelegate.
Definition at line 436 of file ScriptInterpreterPython.cpp.
References eIOHandlerBreakpoint, eIOHandlerNone, eIOHandlerWatchpoint, lldb_private::IOHandler::GetOutputStreamFileSP(), m_active_io_handler, and lldb_private::Stream::PutCString().
IOHandlerInputComplete()
void ScriptInterpreterPythonImpl::IOHandlerInputComplete (IOHandler & io_handler, std::string & data) override virtual
Called when a line or lines have been retrieved.
This function can handle the current line and possibly call IOHandler::SetIsDone(true) when the IO handler is done like when "quit" is entered as a command, of when an empty line is received. It is up to the delegate to determine when a line should cause a IOHandler to exit.
Implements lldb_private::IOHandlerDelegate.
Definition at line 460 of file ScriptInterpreterPython.cpp.
IsExecutingPython()
uint32_t lldb_private::ScriptInterpreterPythonImpl::IsExecutingPython () inline
Definition at line 371 of file ScriptInterpreterPythonImpl.h.
References m_lock_count, and m_mutex.
IsReservedWord()
bool ScriptInterpreterPythonImpl::IsReservedWord (const char * word) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2412 of file ScriptInterpreterPython.cpp.
References m_dictionary_name.
LeaveSession()
void ScriptInterpreterPythonImpl::LeaveSession ()
Definition at line 526 of file ScriptInterpreterPython.cpp.
LoadPluginModule()
StructuredData::ObjectSP ScriptInterpreterPythonImpl::LoadPluginModule (const FileSpec & file_spec, lldb_private::Status & error) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1552 of file ScriptInterpreterPython.cpp.
LoadScriptingModule()
bool ScriptInterpreterPythonImpl::LoadScriptingModule (const char * filename, const LoadScriptOptions & options, lldb_private::Status & error, StructuredData::ObjectSP * module_sp = nullptr, FileSpec extra_search_dir = {}, lldb::TargetSP loaded_into_target_sp = {}) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2221 of file ScriptInterpreterPython.cpp.
MightHaveChildrenSynthProviderInstance()
bool ScriptInterpreterPythonImpl::MightHaveChildrenSynthProviderInstance (const StructuredData::ObjectSP & implementor) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1993 of file ScriptInterpreterPython.cpp.
OptionParsingStartedForCommandObject()
void ScriptInterpreterPythonImpl::OptionParsingStartedForCommandObject (StructuredData::GenericSP cmd_obj_sp) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2869 of file ScriptInterpreterPython.cpp.
RunScriptBasedCommand() [1/2]
bool ScriptInterpreterPythonImpl::RunScriptBasedCommand (const char * impl_function, llvm::StringRef args, ScriptedCommandSynchronicity synchronicity, lldb_private::CommandReturnObject & cmd_retobj, Status & error, const lldb_private::ExecutionContext & exe_ctx) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2453 of file ScriptInterpreterPython.cpp.
References lldb_private::eScriptedCommandSynchronicityCurrentValue.
RunScriptBasedCommand() [2/2]
bool ScriptInterpreterPythonImpl::RunScriptBasedCommand (StructuredData::GenericSP impl_obj_sp, llvm::StringRef args, ScriptedCommandSynchronicity synchronicity, lldb_private::CommandReturnObject & cmd_retobj, Status & error, const lldb_private::ExecutionContext & exe_ctx) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2496 of file ScriptInterpreterPython.cpp.
References error().
RunScriptBasedParsedCommand()
bool ScriptInterpreterPythonImpl::RunScriptBasedParsedCommand (StructuredData::GenericSP impl_obj_sp, Args & args, ScriptedCommandSynchronicity synchronicity, lldb_private::CommandReturnObject & cmd_retobj, Status & error, const lldb_private::ExecutionContext & exe_ctx) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2539 of file ScriptInterpreterPython.cpp.
References error().
RunScriptFormatKeyword() [1/5]
bool ScriptInterpreterPythonImpl::RunScriptFormatKeyword (const char * impl_function, Process * process, std::string & output, Status & error) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2085 of file ScriptInterpreterPython.cpp.
References lldb_private::python::Borrowed.
RunScriptFormatKeyword() [2/5]
bool ScriptInterpreterPythonImpl::RunScriptFormatKeyword (const char * impl_function, StackFrame * frame, std::string & output, Status & error) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2160 of file ScriptInterpreterPython.cpp.
References error().
RunScriptFormatKeyword() [3/5]
bool ScriptInterpreterPythonImpl::RunScriptFormatKeyword (const char * impl_function, Target * target, std::string & output, Status & error) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2135 of file ScriptInterpreterPython.cpp.
RunScriptFormatKeyword() [4/5]
bool ScriptInterpreterPythonImpl::RunScriptFormatKeyword (const char * impl_function, Thread * thread, std::string & output, Status & error) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2110 of file ScriptInterpreterPython.cpp.
References error().
RunScriptFormatKeyword() [5/5]
bool ScriptInterpreterPythonImpl::RunScriptFormatKeyword (const char * impl_function, ValueObject * value, std::string & output, Status & error) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2185 of file ScriptInterpreterPython.cpp.
SetBreakpointCommandCallback() [1/3]
Status ScriptInterpreterPythonImpl::SetBreakpointCommandCallback (BreakpointOptions & bp_options, const char * callback_body, bool is_callback) override virtual
Set the callback body text into the callback for the breakpoint.
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1169 of file ScriptInterpreterPython.cpp.
References BreakpointCallbackFunction(), and error().
SetBreakpointCommandCallback() [2/3]
Status ScriptInterpreterPythonImpl::SetBreakpointCommandCallback (BreakpointOptions & bp_options, const char * command_body_text, StructuredData::ObjectSP extra_args_sp, bool uses_extra_args, bool is_callback)
Definition at line 1177 of file ScriptInterpreterPython.cpp.
SetBreakpointCommandCallback() [3/3]
Status ScriptInterpreterPythonImpl::SetBreakpointCommandCallback (BreakpointOptions & bp_options, std::unique_ptr< BreakpointOptions::CommandData > & data_up) override virtual
This one is for deserialization:
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1151 of file ScriptInterpreterPython.cpp.
References error().
SetBreakpointCommandCallbackFunction()
Status ScriptInterpreterPythonImpl::SetBreakpointCommandCallbackFunction (BreakpointOptions & bp_options, const char * function_name, StructuredData::ObjectSP extra_args_sp) override virtual
Set a script function as the callback for the breakpoint.
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1109 of file ScriptInterpreterPython.cpp.
References eIOHandlerWatchpoint, m_active_io_handler, and lldb_private::ScriptInterpreter::m_debugger.
SetOptionValueForCommandObject()
bool ScriptInterpreterPythonImpl::SetOptionValueForCommandObject (StructuredData::GenericSP cmd_obj_sp, ExecutionContext * exe_ctx, llvm::StringRef long_option, llvm::StringRef value) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 2915 of file ScriptInterpreterPython.cpp.
SetStdHandle()
bool ScriptInterpreterPythonImpl::SetStdHandle (lldb::FileSP file, const char * py_name, python::PythonObject & save_file, const char * mode)
Definition at line 561 of file ScriptInterpreterPython.cpp.
SetThreadState()
void lldb_private::ScriptInterpreterPythonImpl::SetThreadState (PyThreadState * s) inline
Definition at line 286 of file ScriptInterpreterPythonImpl.h.
References m_command_thread_state.
SetWatchpointCommandCallback()
void ScriptInterpreterPythonImpl::SetWatchpointCommandCallback (WatchpointOptions * wp_options, const char * user_input, bool is_callback) override virtual
Set a one-liner as the callback for the watchpoint.
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1202 of file ScriptInterpreterPython.cpp.
ShouldHide()
bool ScriptInterpreterPythonImpl::ShouldHide (const StructuredData::ObjectSP & implementor, lldb::StackFrameSP frame_sp) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1471 of file ScriptInterpreterPython.cpp.
UpdateSynthProviderInstance()
bool ScriptInterpreterPythonImpl::UpdateSynthProviderInstance (const StructuredData::ObjectSP & implementor) override virtual
Reimplemented from lldb_private::ScriptInterpreter.
Definition at line 1969 of file ScriptInterpreterPython.cpp.
References UINT32_MAX.
WatchpointCallbackFunction()
bool ScriptInterpreterPythonImpl::WatchpointCallbackFunction (void * baton, StoppointCallbackContext * context, lldb::user_id_t watch_id) static
Definition at line 1841 of file ScriptInterpreterPython.cpp.
Referenced by ExportFunctionDefinitionToInterpreter().
Friends And Related Symbol Documentation
IOHandlerPythonInterpreter
friend class IOHandlerPythonInterpreter friend
Definition at line 27 of file ScriptInterpreterPythonImpl.h.
References error(), and IOHandlerPythonInterpreter.
Referenced by IOHandlerPythonInterpreter.
Member Data Documentation
m_active_io_handler
ActiveIOHandler lldb_private::ScriptInterpreterPythonImpl::m_active_io_handler
Definition at line 417 of file ScriptInterpreterPythonImpl.h.
Referenced by CollectDataForWatchpointCommandCallback(), IOHandlerActivated(), ScriptInterpreterPythonImpl(), and SetBreakpointCommandCallbackFunction().
m_command_thread_state
PyThreadState* lldb_private::ScriptInterpreterPythonImpl::m_command_thread_state
Definition at line 423 of file ScriptInterpreterPythonImpl.h.
Referenced by GetThreadState(), ScriptInterpreterPythonImpl(), and SetThreadState().
m_dictionary_name
std::string lldb_private::ScriptInterpreterPythonImpl::m_dictionary_name
Definition at line 416 of file ScriptInterpreterPythonImpl.h.
Referenced by BreakpointCallbackFunction(), GetDictionaryName(), GetSysModuleDictionary(), IsReservedWord(), and ScriptInterpreterPythonImpl().
m_lock_count
uint32_t lldb_private::ScriptInterpreterPythonImpl::m_lock_count
Definition at line 421 of file ScriptInterpreterPythonImpl.h.
Referenced by DecrementLockCount(), IncrementLockCount(), IsExecutingPython(), and ScriptInterpreterPythonImpl().
m_main_module
python::PythonModule lldb_private::ScriptInterpreterPythonImpl::m_main_module
Definition at line 411 of file ScriptInterpreterPythonImpl.h.
Referenced by GetSessionDictionary(), and ScriptInterpreterPythonImpl().
m_mutex
std::mutex lldb_private::ScriptInterpreterPythonImpl::m_mutex
Definition at line 422 of file ScriptInterpreterPythonImpl.h.
Referenced by DecrementLockCount(), IncrementLockCount(), and IsExecutingPython().
m_pty_secondary_is_open
bool lldb_private::ScriptInterpreterPythonImpl::m_pty_secondary_is_open
Definition at line 419 of file ScriptInterpreterPythonImpl.h.
Referenced by ScriptInterpreterPythonImpl().
m_run_one_line_function
python::PythonObject lldb_private::ScriptInterpreterPythonImpl::m_run_one_line_function
Definition at line 414 of file ScriptInterpreterPythonImpl.h.
Referenced by ExecuteOneLine(), and ScriptInterpreterPythonImpl().
m_run_one_line_str_global
python::PythonObject lldb_private::ScriptInterpreterPythonImpl::m_run_one_line_str_global
Definition at line 415 of file ScriptInterpreterPythonImpl.h.
Referenced by ExecuteOneLine(), and ScriptInterpreterPythonImpl().
m_saved_stderr
python::PythonObject lldb_private::ScriptInterpreterPythonImpl::m_saved_stderr
Definition at line 410 of file ScriptInterpreterPythonImpl.h.
Referenced by ScriptInterpreterPythonImpl().
m_saved_stdin
python::PythonObject lldb_private::ScriptInterpreterPythonImpl::m_saved_stdin
Definition at line 408 of file ScriptInterpreterPythonImpl.h.
Referenced by ScriptInterpreterPythonImpl().
m_saved_stdout
python::PythonObject lldb_private::ScriptInterpreterPythonImpl::m_saved_stdout
Definition at line 409 of file ScriptInterpreterPythonImpl.h.
Referenced by ScriptInterpreterPythonImpl().
m_session_dict
python::PythonDictionary lldb_private::ScriptInterpreterPythonImpl::m_session_dict
Definition at line 412 of file ScriptInterpreterPythonImpl.h.
Referenced by GetSysModuleDictionary(), ScriptInterpreterPythonImpl(), and ~ScriptInterpreterPythonImpl().
m_session_is_active
bool lldb_private::ScriptInterpreterPythonImpl::m_session_is_active
Definition at line 418 of file ScriptInterpreterPythonImpl.h.
Referenced by ScriptInterpreterPythonImpl().
m_sys_module_dict
python::PythonDictionary lldb_private::ScriptInterpreterPythonImpl::m_sys_module_dict
Definition at line 413 of file ScriptInterpreterPythonImpl.h.
Referenced by GetMaxPositionalArgumentsForCallable(), and ScriptInterpreterPythonImpl().
m_valid_session
bool lldb_private::ScriptInterpreterPythonImpl::m_valid_session
Definition at line 420 of file ScriptInterpreterPythonImpl.h.
Referenced by ScriptInterpreterPythonImpl().
The documentation for this class was generated from the following files:
ScriptInterpreterPythonImpl.h
ScriptInterpreterPython.cpp