LLDB: lldb_private::AppleThreadPlanStepThroughDirectDispatch Class Reference
lldb_private::AppleThreadPlanStepThroughDirectDispatch Class Reference
#include <AppleThreadPlanStepThroughObjCTrampoline.h>
Public Member Functions
AppleThreadPlanStepThroughDirectDispatch (Thread &thread, AppleObjCTrampolineHandler &handler, llvm::StringRef dispatch_func_name)
~AppleThreadPlanStepThroughDirectDispatch () override
void GetDescription (Stream *s, lldb::DescriptionLevel level) override
Print a description of this thread to the stream s.
bool ShouldStop (Event *event_ptr) override
bool StopOthers () override
bool MischiefManaged () override
bool DoWillResume (lldb::StateType resume_state, bool current_plan) override
void SetFlagsToDefault () override
Public Member Functions inherited from lldb_private::ThreadPlanStepOut
ThreadPlanStepOut (Thread &thread, SymbolContext *addr_context, bool first_insn, bool stop_others, Vote report_stop_vote, Vote report_run_vote, uint32_t frame_idx, LazyBool step_out_avoids_code_without_debug_info, bool continue_to_next_branch=false, bool gather_return_value=true)
Creates a thread plan to step out from frame_idx, skipping parent frames if they are artificial or hidden frames.
ThreadPlanStepOut (Thread &thread, bool stop_others, Vote report_stop_vote, Vote report_run_vote, uint32_t frame_idx, bool continue_to_next_branch=false, bool gather_return_value=true)
Creates a thread plan to step out from frame_idx to frame_idx + 1.
~ThreadPlanStepOut () override
void GetDescription (Stream *s, lldb::DescriptionLevel level) override
Print a description of this thread to the stream s.
bool ValidatePlan (Stream *error) override
Returns whether this plan could be successfully created.
bool ShouldStop (Event *event_ptr) override
bool StopOthers () override
void SetStopOthers (bool new_value) override
lldb::StateType GetPlanRunState () override
bool WillStop () override
bool MischiefManaged () override
void DidPush () override
bool IsPlanStale () override
lldb::ValueObjectSP GetReturnValueObject () override
Public Member Functions inherited from lldb_private::ThreadPlan
virtual ~ThreadPlan ()
const char * GetName () const
Returns the name of this thread plan.
Thread & GetThread ()
Returns the Thread that is using this thread plan.
Target & GetTarget ()
const Target & GetTarget () const
void ClearThreadCache ()
Clear the Thread* cache.
bool TracerExplainsStop ()
lldb::StateType RunState ()
bool PlanExplainsStop (Event *event_ptr)
virtual bool ShouldAutoContinue (Event *event_ptr)
Returns whether this thread plan overrides the ShouldStop of subsequently processed plans.
virtual Vote ShouldReportStop (Event *event_ptr)
Vote ShouldReportRun (Event *event_ptr)
virtual bool SupportsResumeOthers ()
virtual bool ShouldRunBeforePublicStop ()
bool WillResume (lldb::StateType resume_state, bool current_plan)
bool IsControllingPlan ()
virtual bool IsLeafPlan ()
bool SetIsControllingPlan (bool value)
virtual bool OkayToDiscard ()
void SetOkayToDiscard (bool value)
virtual void ThreadDestroyed ()
bool GetPrivate ()
void SetPrivate (bool input)
virtual void DidPop ()
ThreadPlanKind GetKind () const
bool IsPlanComplete ()
void SetPlanComplete (bool success=true)
bool PlanSucceeded ()
virtual bool IsBasePlan ()
lldb::ThreadPlanTracerSP & GetThreadPlanTracer ()
void SetThreadPlanTracer (lldb::ThreadPlanTracerSP new_tracer_sp)
void DoTraceLog ()
virtual lldb::ExpressionVariableSP GetExpressionVariable ()
virtual void RestoreThreadState ()
virtual bool IsVirtualStep ()
bool SetIterationCount (size_t count)
virtual lldb::RunDirection GetDirection () const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Public Member Functions inherited from lldb_private::ThreadPlanShouldStopHere
ThreadPlanShouldStopHere (ThreadPlan *owner)
ThreadPlanShouldStopHere (ThreadPlan *owner, const ThreadPlanShouldStopHereCallbacks *callbacks, void *baton=nullptr)
virtual ~ThreadPlanShouldStopHere ()
void SetShouldStopHereCallbacks (const ThreadPlanShouldStopHereCallbacks *callbacks, void *baton)
void ClearShouldStopHereCallbacks ()
bool InvokeShouldStopHereCallback (lldb::FrameComparison operation, Status &status)
lldb::ThreadPlanSP CheckShouldStopHereAndQueueStepOut (lldb::FrameComparison operation, Status &status)
lldb_private::Flags & GetFlags ()
const lldb_private::Flags & GetFlags () const
Protected Member Functions
bool DoPlanExplainsStop (Event *event_ptr) override
Protected Member Functions inherited from lldb_private::ThreadPlanStepOut
void SetFlagsToDefault () override
bool DoPlanExplainsStop (Event *event_ptr) override
bool DoWillResume (lldb::StateType resume_state, bool current_plan) override
bool QueueInlinedStepPlan (bool queue_now)
Protected Member Functions inherited from lldb_private::ThreadPlan
ThreadPlan (ThreadPlanKind kind, const char *name, Thread &thread, Vote report_stop_vote, Vote report_run_vote)
void PushPlan (lldb::ThreadPlanSP &thread_plan_sp)
ThreadPlan * GetPreviousPlan ()
lldb::StopInfoSP GetPrivateStopInfo ()
void SetStopInfo (lldb::StopInfoSP stop_reason_sp)
bool IsUsuallyUnexplainedStopReason (lldb::StopReason)
Protected Member Functions inherited from lldb_private::ThreadPlanShouldStopHere
virtual lldb::ThreadPlanSP QueueStepOutFromHerePlan (Flags &flags, lldb::FrameComparison operation, Status &status)
Protected Attributes
AppleObjCTrampolineHandler & m_trampoline_handler
std::string m_dispatch_func_name
lldb::ThreadPlanSP m_objc_step_through_sp
Which dispatch function we're stepping through.
std::vector< lldb::BreakpointSP > m_msgSend_bkpts
When we hit an objc_msgSend, we'll use this plan to get to its target.
bool m_at_msg_send
Breakpoints on the objc dispatch functions.
Protected Attributes inherited from lldb_private::ThreadPlan
Status m_status
Process & m_process
lldb::tid_t m_tid
Vote m_report_stop_vote
Vote m_report_run_vote
bool m_takes_iteration_count
bool m_could_not_resolve_hw_bp
int32_t m_iteration_count = 1
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Protected Attributes inherited from lldb_private::ThreadPlanShouldStopHere
ThreadPlanShouldStopHereCallbacks m_callbacks
void * m_baton
ThreadPlan * m_owner
lldb_private::Flags m_flags
Additional Inherited Members
Public Types inherited from lldb_private::ThreadPlan
enum ThreadPlanKind {
eKindGeneric , eKindNull , eKindBase , eKindCallFunction ,
eKindPython , eKindStepInstruction , eKindStepOut , eKindStepOverBreakpoint ,
eKindStepOverRange , eKindStepInRange , eKindRunToAddress , eKindStepThrough ,
eKindStepUntil , eKindSingleThreadTimeout
}
Public Types inherited from lldb_private::ThreadPlanShouldStopHere
enum {
eNone = 0 , eAvoidInlines = (1 << 0) , eStepInAvoidNoDebug = (1 << 1) , eStepOutAvoidNoDebug = (1 << 2) ,
eStepOutPastThunks = (1 << 3)
}
Static Protected Member Functions inherited from lldb_private::ThreadPlanShouldStopHere
static bool DefaultShouldStopHereCallback (ThreadPlan *current_plan, Flags &flags, lldb::FrameComparison operation, Status &status, void *baton)
static lldb::ThreadPlanSP DefaultStepFromHereCallback (ThreadPlan *current_plan, Flags &flags, lldb::FrameComparison operation, Status &status, void *baton)
Detailed Description
Definition at line 83 of file AppleThreadPlanStepThroughObjCTrampoline.h.
Constructor & Destructor Documentation
AppleThreadPlanStepThroughDirectDispatch()
AppleThreadPlanStepThroughDirectDispatch::AppleThreadPlanStepThroughDirectDispatch (Thread & thread, AppleObjCTrampolineHandler & handler, llvm::StringRef dispatch_func_name)
Definition at line 241 of file AppleThreadPlanStepThroughObjCTrampoline.cpp.
References lldb_private::Flags::Clear(), lldb_private::eLazyBoolNo, lldb_private::ThreadPlanShouldStopHere::eStepInAvoidNoDebug, lldb_private::ThreadPlanShouldStopHere::eStepOutAvoidNoDebug, lldb_private::eVoteNoOpinion, lldb_private::AppleObjCTrampolineHandler::ForEachDispatchFunction(), lldb_private::ThreadPlanShouldStopHere::GetFlags(), lldb_private::UserID::GetID(), lldb_private::ThreadPlan::GetTarget(), lldb_private::ThreadPlan::GetThread(), m_at_msg_send, m_dispatch_func_name, m_msgSend_bkpts, m_trampoline_handler, and lldb_private::ThreadPlanStepOut::ThreadPlanStepOut().
~AppleThreadPlanStepThroughDirectDispatch()
AppleThreadPlanStepThroughDirectDispatch::~AppleThreadPlanStepThroughDirectDispatch () override
Definition at line 279 of file AppleThreadPlanStepThroughObjCTrampoline.cpp.
References lldb_private::ThreadPlan::GetTarget(), m_msgSend_bkpts, and lldb_private::Target::RemoveBreakpointByID().
Member Function Documentation
DoPlanExplainsStop()
bool AppleThreadPlanStepThroughDirectDispatch::DoPlanExplainsStop (Event * event_ptr) override protected virtual
Implements lldb_private::ThreadPlan.
Definition at line 309 of file AppleThreadPlanStepThroughObjCTrampoline.cpp.
References lldb_private::ThreadPlanStepOut::DoPlanExplainsStop(), lldb::eStopReasonBreakpoint, lldb::eStopReasonNone, lldb_private::ThreadPlan::GetPrivateStopInfo(), lldb_private::Thread::GetProcess(), lldb_private::ThreadPlan::GetThread(), m_at_msg_send, m_msgSend_bkpts, and lldb_private::ThreadPlan::SetPlanComplete().
DoWillResume()
bool AppleThreadPlanStepThroughDirectDispatch::DoWillResume (lldb::StateType resume_state, bool current_plan) override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 352 of file AppleThreadPlanStepThroughObjCTrampoline.cpp.
References lldb_private::ThreadPlanStepOut::DoWillResume(), and m_at_msg_send.
GetDescription()
void AppleThreadPlanStepThroughDirectDispatch::GetDescription (Stream * s, lldb::DescriptionLevel level) override virtual
Print a description of this thread to the stream s.
thread. Don't expect that the result of GetThread is valid in the description method. This might get called when the underlying Thread has not been reported, so we only know the TID and not the thread.
Parameters
[in] s The stream to which to print the description.
[in] level The level of description desired. Note that eDescriptionLevelBrief will be used in the stop message printed when the plan is complete.
Implements lldb_private::ThreadPlan.
Definition at line 286 of file AppleThreadPlanStepThroughObjCTrampoline.cpp.
References lldb::eDescriptionLevelBrief, m_dispatch_func_name, m_msgSend_bkpts, lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
MischiefManaged()
bool AppleThreadPlanStepThroughDirectDispatch::MischiefManaged () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 424 of file AppleThreadPlanStepThroughObjCTrampoline.cpp.
References lldb_private::ThreadPlan::IsPlanComplete(), and lldb_private::ThreadPlanStepOut::MischiefManaged().
SetFlagsToDefault()
void lldb_private::AppleThreadPlanStepThroughDirectDispatch::SetFlagsToDefault () inline override virtual
Implements lldb_private::ThreadPlanShouldStopHere.
Definition at line 101 of file AppleThreadPlanStepThroughObjCTrampoline.h.
References lldb_private::ThreadPlanStepInRange::GetDefaultFlagsValue(), lldb_private::ThreadPlanShouldStopHere::GetFlags(), and lldb_private::Flags::Set().
ShouldStop()
bool AppleThreadPlanStepThroughDirectDispatch::ShouldStop (Event * event_ptr) override virtual
Implements lldb_private::ThreadPlan.
Definition at line 359 of file AppleThreadPlanStepThroughObjCTrampoline.cpp.
References lldb::eFrameCompareYounger, lldb::eLanguageTypeObjC, error(), lldb_private::GetLog(), lldb_private::Thread::GetProcess(), lldb_private::LanguageRuntime::GetStepThroughTrampolinePlan(), lldb_private::ThreadPlan::GetThread(), lldb_private::ThreadPlanShouldStopHere::InvokeShouldStopHereCallback(), LLDB_LOG, LLDB_LOGF, m_at_msg_send, m_msgSend_bkpts, m_objc_step_through_sp, lldb_private::Thread::QueueThreadPlan(), lldb_private::ThreadPlan::SetPlanComplete(), lldb_private::ThreadPlanStepOut::ShouldStop(), and lldb_private::Step.
StopOthers()
bool lldb_private::AppleThreadPlanStepThroughDirectDispatch::StopOthers () inline override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 95 of file AppleThreadPlanStepThroughObjCTrampoline.h.
Member Data Documentation
m_at_msg_send
bool lldb_private::AppleThreadPlanStepThroughDirectDispatch::m_at_msg_send protected
Breakpoints on the objc dispatch functions.
Definition at line 116 of file AppleThreadPlanStepThroughObjCTrampoline.h.
Referenced by AppleThreadPlanStepThroughDirectDispatch(), DoPlanExplainsStop(), DoWillResume(), and ShouldStop().
m_dispatch_func_name
std::string lldb_private::AppleThreadPlanStepThroughDirectDispatch::m_dispatch_func_name protected
Definition at line 109 of file AppleThreadPlanStepThroughObjCTrampoline.h.
Referenced by AppleThreadPlanStepThroughDirectDispatch(), and GetDescription().
m_msgSend_bkpts
std::vector<lldb::BreakpointSP> lldb_private::AppleThreadPlanStepThroughDirectDispatch::m_msgSend_bkpts protected
When we hit an objc_msgSend, we'll use this plan to get to its target.
Definition at line 114 of file AppleThreadPlanStepThroughObjCTrampoline.h.
Referenced by AppleThreadPlanStepThroughDirectDispatch(), DoPlanExplainsStop(), GetDescription(), ShouldStop(), and ~AppleThreadPlanStepThroughDirectDispatch().
m_objc_step_through_sp
lldb::ThreadPlanSP lldb_private::AppleThreadPlanStepThroughDirectDispatch::m_objc_step_through_sp protected
Which dispatch function we're stepping through.
Definition at line 111 of file AppleThreadPlanStepThroughObjCTrampoline.h.
Referenced by ShouldStop().
m_trampoline_handler
AppleObjCTrampolineHandler& lldb_private::AppleThreadPlanStepThroughDirectDispatch::m_trampoline_handler protected
Definition at line 108 of file AppleThreadPlanStepThroughObjCTrampoline.h.
Referenced by AppleThreadPlanStepThroughDirectDispatch().
The documentation for this class was generated from the following files:
AppleThreadPlanStepThroughObjCTrampoline.h
AppleThreadPlanStepThroughObjCTrampoline.cpp