LLDB: lldb_private::ApplePropertyList Class Reference
lldb_private::ApplePropertyList Class Reference
#include <XML.h>
Public Member Functions
ApplePropertyList ()
ApplePropertyList (const char *path)
~ApplePropertyList ()
bool ParseFile (const char *path)
llvm::StringRef GetErrors () const
operator bool () const
bool IsValid () const
XMLNode GetValueNode (const char *key) const
bool GetValueAsString (const char *key, std::string &value) const
StructuredData::ObjectSP GetStructuredData ()
Static Protected Member Functions
static bool ExtractStringFromValueNode (const XMLNode &node, std::string &value)
Protected Attributes
XMLDocument m_xml_doc
XMLNode m_dict_node
Detailed Description
Definition at line 145 of file XML.h.
Constructor & Destructor Documentation
ApplePropertyList() [1/2]
ApplePropertyList::ApplePropertyList ()
Definition at line 374 of file XML.cpp.
References m_dict_node, and m_xml_doc.
ApplePropertyList() [2/2]
ApplePropertyList::ApplePropertyList (const char * path)
Definition at line 376 of file XML.cpp.
References m_dict_node, m_xml_doc, and ParseFile().
~ApplePropertyList()
ApplePropertyList::~ApplePropertyList () default
Member Function Documentation
ExtractStringFromValueNode()
bool ApplePropertyList::ExtractStringFromValueNode (const XMLNode & node, std::string & value) static protected
Definition at line 435 of file XML.cpp.
References lldb_private::XMLNode::GetElementText(), lldb_private::XMLNode::GetName(), and lldb_private::XMLNode::IsValid().
Referenced by GetValueAsString().
GetErrors()
llvm::StringRef ApplePropertyList::GetErrors () const
Definition at line 383 of file XML.cpp.
References m_xml_doc.
GetStructuredData()
StructuredData::ObjectSP ApplePropertyList::GetStructuredData ()
Definition at line 511 of file XML.cpp.
References IsValid(), and m_dict_node.
Referenced by SymbolVendorMacOSX::CreateInstance().
GetValueAsString()
bool ApplePropertyList::GetValueAsString (const char * key, std::string & value) const
Definition at line 404 of file XML.cpp.
References ExtractStringFromValueNode(), and GetValueNode().
Referenced by SymbolVendorMacOSX::CreateInstance(), and lldb_private::PlatformDarwin::GetOSVersion().
GetValueNode()
XMLNode ApplePropertyList::GetValueNode (const char * key) const
Definition at line 412 of file XML.cpp.
References lldb_private::XMLNode::GetElementText(), lldb_private::XMLNode::GetSibling(), lldb_private::XMLNode::IsElement(), IsValid(), and m_dict_node.
Referenced by GetValueAsString().
IsValid()
bool ApplePropertyList::IsValid () const
Definition at line 402 of file XML.cpp.
References m_dict_node.
Referenced by GetStructuredData(), GetValueNode(), and operator bool().
operator bool()
lldb_private::ApplePropertyList::operator bool () const inline explicit
Definition at line 157 of file XML.h.
References IsValid().
ParseFile()
bool ApplePropertyList::ParseFile (const char * path)
Definition at line 387 of file XML.cpp.
References lldb_private::XMLNode::ForEachChildElementWithName(), m_dict_node, and m_xml_doc.
Referenced by ApplePropertyList().
Member Data Documentation
m_dict_node
XMLNode lldb_private::ApplePropertyList::m_dict_node protected
Definition at line 177 of file XML.h.
Referenced by ApplePropertyList(), ApplePropertyList(), GetStructuredData(), GetValueNode(), IsValid(), and ParseFile().
m_xml_doc
XMLDocument lldb_private::ApplePropertyList::m_xml_doc protected
Definition at line 176 of file XML.h.
Referenced by ApplePropertyList(), ApplePropertyList(), GetErrors(), and ParseFile().
The documentation for this class was generated from the following files:
XML.h
XML.cpp