LLDB: lldb_private::Status Class Reference
lldb_private::Status Class Reference
An error handling class.
#include "lldb/Utility/Status.h"
Public Types
typedef uint32_t ValueType
into ValueType.
Public Member Functions
Status ()
Status (Status &&other)=default
Status (ValueType err, lldb::ErrorType type=lldb::eErrorTypeGeneric, std::string msg={})
Initialize the error object with a generic success value.
Status (std::error_code EC)
Status (std::string err_str)
Create a generic error with the message err_str.
~Status ()
const Status & operator= (Status &&)
llvm::Error ToError () const
FIXME: Replace all uses with takeError() instead.
llvm::Error takeError ()
Status Clone () const
Don't call this function in new code.
const char * AsCString (const char *default_error_str="unknown error") const
Get the error string associated with the current error.
StructuredData::ObjectSP GetAsStructuredData () const
Get the error in machine-readable form.
void Clear ()
Clear the object state.
bool Fail () const
Test for error condition.
ValueType GetError () const
Access the error value.
lldb::ErrorType GetType () const
Access the error type.
bool Success () const
Test for success condition.
Static Public Member Functions
static Status FromErrorString (const char *str)
static Status FromErrorStringWithFormat (const char *format,...) __attribute__((format(printf
template<typename... Args>
static Status static Status FromErrorStringWithFormatv (const char *format, Args &&...args)
static Status FromErrno ()
Set the current error to errno.
static Status FromError (llvm::Error error)
Avoid using this in new code. Migrate APIs to llvm::Expected instead.
Protected Member Functions
Status (llvm::Error error)
Protected Attributes
llvm::Error m_error
std::string m_string
TODO: Replace this with just calling toString(m_error).
Detailed Description
An error handling class.
This class is designed to be able to hold any error code that can be encountered on a given platform. The errors are stored as a value of type Status::ValueType. This value should be large enough to hold any and all errors that the class supports. Each error has an associated type that is of type lldb::ErrorType. New types can be added to support new error types, and architecture specific types can be enabled. In the future we may wish to switch to a registration mechanism where new error types can be registered at runtime instead of a hard coded scheme.
All errors in this class also know how to generate a string representation of themselves for printing results and error codes. The string value will be fetched on demand and its string value will be cached until the error is cleared of the value of the error changes.
API design notes:
Most APIs that currently vend a Status would be better served by returning llvm::Expected<> instead. If possibles APIs should be refactored to avoid Status. The only legitimate long-term uses of Status are objects that need to store an error for a long time (which should be questioned as a design decision, too).
Implementation notes:
Internally, Status stores an llvm::Error. eErrorTypeInvalid eErrorTypeGeneric llvm::StringError eErrorTypePOSIX llvm::ECError eErrorTypeMachKernel MachKernelError eErrorTypeExpression llvm::ErrorList<ExpressionError> eErrorTypeWin32 Win32Error
Definition at line 118 of file Status.h.
Member Typedef Documentation
ValueType
typedef uint32_t lldb_private::Status::ValueType
into ValueType.
Definition at line 121 of file Status.h.
Constructor & Destructor Documentation
Status() [1/6]
Status::Status ()
Definition at line 59 of file Status.cpp.
References m_error, and Status().
Referenced by Clone(), FromErrno(), FromError(), FromErrorString(), FromErrorStringWithFormat(), FromErrorStringWithFormatv(), operator=(), Status(), and Status().
Status() [2/6]
lldb_private::Status::Status (Status && other) default
References lldb::eErrorTypeGeneric, and Status().
Status() [3/6]
Status::Status (ValueType err, lldb::ErrorType type = lldb::eErrorTypeGeneric, std::string msg = {}) explicit
Initialize the error object with a generic success value.
Parameters
[in] err An error code.
[in] type The type for err.
Definition at line 86 of file Status.cpp.
References ErrorFromEnums(), and m_error.
Status() [4/6]
Status::Status (std::error_code EC)
Definition at line 92 of file Status.cpp.
References m_error.
Status() [5/6]
Status::Status (std::string err_str) explicit
Create a generic error with the message err_str.
Definition at line 95 of file Status.cpp.
References createStringError(), and m_error.
~Status()
Status::~Status ()
Definition at line 141 of file Status.cpp.
References m_error.
Status() [6/6]
lldb_private::Status::Status (llvm::Error error) inline protected
Definition at line 236 of file Status.h.
References error(), and m_error.
Member Function Documentation
AsCString()
const char * Status::AsCString (const char * default_error_str = "unknown error") const
Get the error string associated with the current error.
Gets the error value as a NULL terminated C string. The error string will be fetched and cached on demand. The error string will be retrieved from a callback that is appropriate for the type of the error and will be cached until the error value is changed or cleared.
Returns
The error as a NULL terminated C string value if the error is valid and is able to be converted to a string value, NULL otherwise.
Definition at line 195 of file Status.cpp.
References m_error, m_string, and Success().
Referenced by lldb_private::ClangUserExpression::AddArguments(), lldb_private::process_linux::NativeProcessLinux::AddThread(), lldb_private::process_gdb_remote::ProcessGDBRemote::AsyncThread(), lldb_private::Process::CanJIT(), CommandObjectScriptingObjectParsed::Create(), lldb_private::Breakpoint::CreateFromStructuredData(), lldb_private::BreakpointOptions::CreateFromStructuredData(), EntityPersistentVariable::Dematerialize(), EntityRegister::Dematerialize(), EntityVariableBase::Dematerialize(), EntityPersistentVariable::DestroyAllocation(), lldb_private::IRExecutionUnit::DisassembleFunction(), CommandObjectBreakpointAddException::DoExecute(), CommandObjectBreakpointSet::DoExecute(), CommandObjectCommandsContainerAdd::DoExecute(), CommandObjectCommandsContainerDelete::DoExecute(), CommandObjectCommandsScriptAdd::DoExecute(), CommandObjectPlatformProcessAttach::DoExecute(), CommandObjectTargetCreate::DoExecute(), lldb_private::LLVMUserExpression::DoExecute(), lldb_private::PlatformWindows::DoLoadImage(), lldb_private::ClangExpressionParser::DoPrepareForExecution(), lldb_private::LLVMUserExpression::FinalizeJITExecution(), lldb::SBValue::GetError(), lldb_private::Module::GetMemoryObjectFile(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetModuleByCompUnitInfo(), lldb_private::IRExecutionUnit::GetRunnableInfo(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetSeparateDebugInfo(), lldb::SBValue::GetValueAsSigned(), lldb::SBValue::GetValueAsUnsigned(), lldb_private::ScriptedFramePythonInterface::GetValueObjectForVariableExpression(), lldb_private::ValueObjectPrinter::GetValueSummaryError(), lldb_private::ClangExpressionDeclMap::GetVariableValue(), HandleFileAction(), lldb_private::ClangUtilityFunction::Install(), DynamicLoaderDarwinKernel::KextImageInfo::LoadImageUsingMemoryModule(), EntityPersistentVariable::MakeAllocation(), EntityPersistentVariable::Materialize(), EntityRegister::Materialize(), EntityResultVariable::Materialize(), EntitySymbol::Materialize(), EntityVariableBase::Materialize(), lldb_private::ConnectionFileDescriptor::OpenCommandPipe(), lldb_private::StopInfoBreakpoint::PerformAction(), lldb_private::ClangUserExpression::PrepareForParsing(), lldb_private::LLVMUserExpression::PrepareToExecuteJITExpression(), ABISysV_arm64::PrepareTrivialCall(), lldb::SBThreadPlan::QueueThreadPlanForRunToAddress(), lldb::SBThreadPlan::QueueThreadPlanForStepInRange(), lldb::SBThreadPlan::QueueThreadPlanForStepOut(), lldb::SBThreadPlan::QueueThreadPlanForStepOverRange(), lldb::SBThreadPlan::QueueThreadPlanForStepScripted(), lldb::SBThreadPlan::QueueThreadPlanForStepScripted(), lldb::SBThreadPlan::QueueThreadPlanForStepSingleInstruction(), lldb_private::RegisterContextUnwind::ReadFrameAddress(), RecurseCopy_Callback(), lldb_private::process_linux::NativeThreadLinux::RequestStop(), lldb_private::Process::RunThreadPlan(), lldb::SBThread::RunToAddress(), lldb::SBValue::SetData(), lldb_private::ValueObject::SetData(), CommandObjectBreakpointRead::CommandOptions::SetOptionValue(), CommandObjectBreakpointSet::CommandOptions::SetOptionValue(), CommandObjectSourceList::CommandOptions::SetOptionValue(), ABIMacOSX_arm64::SetReturnValueObject(), ABIMacOSX_arm::SetReturnValueObject(), ABIMacOSX_i386::SetReturnValueObject(), ABISysV_arc::SetReturnValueObject(), ABISysV_arm64::SetReturnValueObject(), ABISysV_arm::SetReturnValueObject(), ABISysV_i386::SetReturnValueObject(), ABISysV_loongarch::SetReturnValueObject(), ABISysV_mips64::SetReturnValueObject(), ABISysV_mips::SetReturnValueObject(), ABISysV_ppc64::SetReturnValueObject(), ABISysV_ppc::SetReturnValueObject(), ABISysV_riscv::SetReturnValueObject(), ABISysV_s390x::SetReturnValueObject(), ABISysV_x86_64::SetReturnValueObject(), ABIWindows_x86_64::SetReturnValueObject(), lldb::SBThread::StepInstruction(), lldb::SBThread::StepInto(), lldb::SBThread::StepOut(), lldb::SBThread::StepOutOfFrame(), lldb::SBThread::StepOverUntil(), lldb::SBThread::StepUsingScriptedThreadPlan(), CommandObjectProcessLaunchOrAttach::StopProcessIfNecessary(), lldb_private::ClangUserExpression::TryParse(), PlatformPOSIX::UnloadImage(), lldb_private::ValueObjectChild::UpdateValue(), lldb::SBValue::Watch(), and lldb_private::FunctionCaller::WriteFunctionWrapper().
Clear()
void Status::Clear ()
Clear the object state.
Reverts the state of this object to contain a generic success value and frees any cached error string value.
Definition at line 215 of file Status.cpp.
References lldb_private::API, lldb_private::GetLog(), LLDB_LOG_ERRORV, and m_error.
Referenced by CoreSimulatorSupport::Device::Boot(), EntityResultVariable::Dematerialize(), lldb_private::IRExecutionUnit::DisassembleFunction(), lldb_private::OptionArgParser::DoToAddress(), lldb_private::UserExpression::GetObjectPointerValueObject(), lldb_private::Value::GetValueByteSize(), IRInterpreter::Interpret(), operator=(), lldb_private::ConnectionGenericFile::Read(), lldb_private::NativeProcessProtocol::ReadCStringFromMemory(), lldb_private::Process::ReadCStringFromMemory(), lldb_private::Target::ReadCStringFromMemory(), lldb_private::process_freebsd::NativeThreadFreeBSD::Resume(), lldb_private::NativeFile::SeekFromCurrent(), lldb_private::NativeFile::SeekFromEnd(), lldb_private::NativeFile::SeekFromStart(), CoreSimulatorSupport::Device::Shutdown(), lldb_private::ThreadedCommunication::StartReadThread(), lldb_private::CommandInterpreter::VerifyUserMultiwordCmdPath(), lldb_private::ConnectionGenericFile::Write(), and lldb_private::IRMemoryMap::~IRMemoryMap().
Clone()
Status lldb_private::Status::Clone () const inline
Don't call this function in new code.
Instead, redesign the API to use llvm::Expected instead of Status.
Definition at line 174 of file Status.h.
References Status(), and ToError().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::CalculateFrameVariableError(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CalculateFrameVariableError(), lldb_private::process_linux::NativeProcessLinux::Detach(), ValueListImpl::operator=(), and lldb_private::ScriptedPythonInterface::Transform().
Fail()
bool Status::Fail () const
Test for error condition.
Returns
true if this object contains an error, false otherwise.
Definition at line 294 of file Status.cpp.
References m_error.
Referenced by lldb_private::Socket::Accept(), AddLinkMapSections(), lldb_private::process_linux::NativeProcessLinux::AddThread(), AddThreadLocalMemoryRegions(), lldb_private::process_gdb_remote::ProcessGDBRemote::AsyncThread(), lldb_private::process_freebsd::NativeProcessFreeBSD::Attach(), lldb_private::process_netbsd::NativeProcessNetBSD::Attach(), lldb_private::Process::CalculateCoreFileSaveRanges(), lldb_private::plugin::dwarf::SymbolFileDWARF::CalculateFrameVariableError(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CalculateFrameVariableError(), InstrumentationBoundsSafetyStopInfo::ComputeStopReasonAndSuggestedStackFrameWithoutDebugInfo(), CopyOverBreakpointOptions(), CommandObjectScriptingObjectParsed::Create(), lldb_private::ScriptedProcessPythonInterface::CreateBreakpoint(), lldb_private::Breakpoint::CreateFromStructuredData(), lldb_private::BreakpointOptions::CreateFromStructuredData(), lldb_private::process_linux::NativeProcessLinux::Detach(), lldb_private::process_linux::NativeRegisterContextLinux::DetermineArchitectureViaGPR(), lldb_private::Target::DisableAllWatchpoints(), lldb_private::ProcessWindows::DoDetach(), CommandObjectBreakpointAddException::DoExecute(), CommandObjectBreakpointSet::DoExecute(), CommandObjectCommandsContainerAdd::DoExecute(), CommandObjectCommandsScriptAdd::DoExecute(), CommandObjectMemoryTagWrite::DoExecute(), CommandObjectPlatformProcessAttach::DoExecute(), CommandObjectTargetCreate::DoExecute(), CommandObjectThreadJump::DoExecute(), lldb_private::PlatformWindows::DoLoadImage(), lldb_private::ProcessWindows::DoResume(), lldb_private::Target::EnableAllWatchpoints(), lldb_private::CPPLanguageRuntime::FindLibCppStdFunctionCallableInfo(), lldb_private::IRMemoryMap::FindSpace(), lldb_private::formatters::LibcxxVectorBoolSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd::GetChildAtIndex(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwoStats(), lldb_private::SymbolFile::GetFrameVariableError(), lldb_private::PlatformDarwinDevice::GetSharedModuleWithLocalCache(), lldb_private::ScriptedFramePythonInterface::GetValueObjectForVariableExpression(), lldb_private::Variable::GetValuesForVariableExpressionPath(), GetVTableAddress(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qPlatform_shell(), lldb_private::Process::Launch(), lldb_private::process_aix::NativeProcessAIX::Manager::Launch(), lldb_private::process_freebsd::NativeProcessFreeBSD::Manager::Launch(), lldb_private::process_linux::NativeProcessLinux::Manager::Launch(), lldb_private::process_netbsd::NativeProcessNetBSD::Manager::Launch(), lldb_private::PlatformAppleSimulator::LaunchProcess(), lldb_private::ProcessDebugger::LaunchProcess(), lldb_private::StackFrame::LegacyGetValueForVariableExpressionPath(), DynamicLoaderDarwinKernel::KextImageInfo::LoadImageUsingMemoryModule(), DynamicLoaderPOSIXDYLD::LoadInterpreterModule(), DynamicLoaderPOSIXDYLD::LoadVDSO(), lldb_private::ClangExpressionDeclMap::LookUpLldbClass(), lldb_private::ClangExpressionDeclMap::LookUpLldbObjCClass(), EntityVariableBase::Materialize(), lldb_private::process_freebsd::NativeProcessFreeBSD::MonitorClone(), lldb_private::process_netbsd::NativeProcessNetBSD::MonitorClone(), lldb_private::process_freebsd::NativeProcessFreeBSD::MonitorSIGTRAP(), lldb_private::process_linux::NativeProcessLinux::MonitorSIGTRAP(), lldb_private::formatters::NSIndirectTaggedString_SummaryProvider(), lldb_private::formatters::ObjCBOOLSummaryProvider(), ProcessElfCore::parseLinuxNotes(), lldb_private::process_linux::NativeProcessLinux::PopulateMemoryRegionCache(), ABISysV_arm64::PrepareTrivialCall(), lldb::SBThreadPlan::QueueThreadPlanForRunToAddress(), lldb::SBThreadPlan::QueueThreadPlanForStepInRange(), lldb::SBThreadPlan::QueueThreadPlanForStepOut(), lldb::SBThreadPlan::QueueThreadPlanForStepOverRange(), lldb::SBThreadPlan::QueueThreadPlanForStepScripted(), lldb::SBThreadPlan::QueueThreadPlanForStepScripted(), lldb::SBThreadPlan::QueueThreadPlanForStepSingleInstruction(), lldb_private::RegisterContextUnwind::ReadFrameAddress(), lldb_private::ScriptedProcessPythonInterface::ReadMemoryAtAddress(), lldb_private::Process::ReadMemoryRanges(), MinidumpFileBuilder::ReadWriteMemoryInChunks(), RecurseCopy_Callback(), lldb_private::Target::RemoveAllWatchpoints(), lldb_private::NativeProcessProtocol::RemoveWatchpoint(), lldb_private::NativeProcessWindows::Resume(), lldb_private::InstrumentationRuntimeMainThreadChecker::RetrieveReportData(), lldb_private::NativeProcessProtocol::SetHardwareBreakpoint(), ABIMacOSX_arm64::SetReturnValueObject(), ABIMacOSX_arm::SetReturnValueObject(), ABIMacOSX_i386::SetReturnValueObject(), ABISysV_arc::SetReturnValueObject(), ABISysV_arm64::SetReturnValueObject(), ABISysV_arm::SetReturnValueObject(), ABISysV_i386::SetReturnValueObject(), ABISysV_loongarch::SetReturnValueObject(), ABISysV_mips64::SetReturnValueObject(), ABISysV_mips::SetReturnValueObject(), ABISysV_ppc64::SetReturnValueObject(), ABISysV_ppc::SetReturnValueObject(), ABISysV_riscv::SetReturnValueObject(), ABISysV_s390x::SetReturnValueObject(), ABISysV_x86_64::SetReturnValueObject(), ABIWindows_x86_64::SetReturnValueObject(), lldb_private::process_freebsd::NativeProcessFreeBSD::SetupTrace(), lldb_private::process_netbsd::NativeProcessNetBSD::SetupTrace(), lldb_private::NativeProcessProtocol::SetWatchpoint(), lldb_private::AppleThreadPlanStepThroughObjCTrampoline::ShouldStop(), lldb_private::mcp::ProtocolServerMCP::Start(), lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess(), lldb::SBThread::StepUsingScriptedThreadPlan(), Success(), lldb_private::PlatformWindows::UnloadImage(), lldb_private::formatters::VectorIteratorSyntheticFrontEnd::Update(), lldb_private::dil::Interpreter::Visit(), lldb_private::ScriptedBreakpointPythonInterface::WasHit(), and lldb_private::ScriptedProcessPythonInterface::WriteMemoryAtAddress().
FromErrno()
Status Status::FromErrno () static
Set the current error to errno.
Update the error value to be errno and update the type to be Status::POSIX.
Definition at line 300 of file Status.cpp.
References Status().
Referenced by lldb_private::NativeFile::Close(), lldb_private::ConnectionFileDescriptor::ConnectFile(), lldb_private::ConnectionFileDescriptor::ConnectSerialPort(), lldb_private::PipePosix::CreateNew(), lldb_private::PipePosix::CreateNew(), EnsureFDFlags(), EnsureFDFlags(), EnsureFDFlags(), fileLock(), lldb_private::NativeFile::Flush(), lldb_private::NativeFile::GetFileSpec(), lldb_private::File::GetPermissions(), lldb_private::process_freebsd::NativeProcessFreeBSD::Halt(), lldb_private::process_linux::NativeProcessLinux::Halt(), HandleFileAction(), lldb_private::process_linux::NativeProcessLinux::Kill(), lldb_private::process_netbsd::NativeProcessNetBSD::Kill(), lldb_private::PipePosix::OpenAsReader(), lldb_private::process_freebsd::NativeProcessFreeBSD::PtraceWrapper(), lldb_private::process_linux::NativeProcessLinux::PtraceWrapper(), lldb_private::process_netbsd::NativeProcessNetBSD::PtraceWrapper(), lldb_private::NativeFile::Read(), lldb_private::NativeFile::Read(), lldb_private::FileSystem::Readlink(), lldb_private::process_linux::NativeThreadLinux::RequestStop(), lldb_private::FileSystem::ResolveSymbolicLink(), lldb_private::NativeFile::SeekFromCurrent(), lldb_private::NativeFile::SeekFromEnd(), lldb_private::NativeFile::SeekFromStart(), SelectHelper::Select(), lldb::SBError::SetErrorToErrno(), lldb_private::Socket::SetLastError(), lldb_private::HostProcessPosix::Signal(), lldb_private::process_freebsd::NativeProcessFreeBSD::Signal(), lldb_private::process_linux::NativeProcessLinux::Signal(), lldb_private::process_netbsd::NativeProcessNetBSD::Signal(), lldb_private::process_netbsd::NativeProcessNetBSD::StopProcess(), lldb_private::FileSystem::Symlink(), lldb_private::NativeFile::Sync(), lldb_private::NativeFile::Write(), and lldb_private::NativeFile::Write().
FromError()
Status Status::FromError (llvm::Error error) static
Avoid using this in new code. Migrate APIs to llvm::Expected instead.
Definition at line 137 of file Status.cpp.
References error(), and Status().
Referenced by lldb_private::Socket::Accept(), MinidumpFileBuilder::AddMemoryList(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::AttachToProcess(), lldb_private::ScriptedPythonInterface::CallStaticMethod(), lldb_private::NativeRegisterContextDBReg::ClearAllHardwareBreakpoints(), lldb_private::NativeRegisterContextDBReg::ClearAllHardwareWatchpoints(), lldb_private::IRExecutionUnit::CommitOneAllocation(), lldb_private::SharedSocket::CompleteSending(), lldb_private::BreakpointLocation::ConditionSaysStop(), lldb_private::TCPSocket::Connect(), lldb_private::platform_android::PlatformAndroid::ConnectRemote(), lldb_private::ConnectionFileDescriptor::ConnectSerialPort(), lldb_private::ConnectionFileDescriptor::ConnectUDP(), lldb_private::BreakpointResolverScripted::CreateImplementationIfNeeded(), sddarwinlog_private::RegexFilterRule::CreateOperation(), lldb_private::ScriptedPythonInterface::CreatePluginObject(), lldb_private::DebuggerThread::DebugAttach(), lldb_private::DebuggerThread::DebugLaunch(), lldb_private::PlatformWasm::DebugProcess(), lldb_private::StackFrame::DILGetValueForVariableExpressionPath(), lldb_private::ScriptedPythonInterface::Dispatch(), CommandObjectMemoryTagRead::DoExecute(), CommandObjectMemoryTagWrite::DoExecute(), CommandObjectTraceSchema::DoExecute(), lldb_private::minidump::ProcessMinidump::DoLoadCore(), ProcessElfCore::DoLoadCore(), lldb_private::PlatformWindows::DoLoadImage(), lldb_private::ClangExpressionParser::DoPrepareForExecution(), lldb_private::minidump::ProcessMinidump::DoReadMemory(), lldb_private::UserExpression::Evaluate(), ForwardPortWithAdb(), lldb_private::formatters::BlockPointerSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::VectorTypeSyntheticFrontEnd::GetChildAtIndex(), lldb::SBSaveCoreOptions::GetCurrentSizeInBytes(), lldb::SBFrame::GetDescriptionWithFormat(), lldb_private::StackFrame::GetFrameBaseValue(), lldb_private::SharedSocket::GetNativeSocket(), lldb_private::ScriptedFrame::GetRegisterContext(), lldb_private::Thread::GetSiginfoValue(), lldb_private::Value::GetValueByteSize(), lldb_private::NativeRegisterContextDBReg::GetWatchpointHitIndex(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_jLLDBTraceGetBinaryData(), HandleFileAction(), lldb::SBDebugger::InitializeWithErrorHandling(), lldb::SBThread::JumpToLine(), lldb_private::process_gdb_remote::ProcessGDBRemote::LaunchAndConnectToDebugserver(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::LaunchProcess(), lldb_private::ProcessLauncherWindows::LaunchProcess(), lldb_private::TCPSocket::Listen(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::LoadQXferMemoryMap(), lldb_private::UtilityFunction::MakeFunctionCaller(), EntityResultVariable::Materialize(), lldb_private::process_linux::NativeProcessLinux::NotifyTracersOfNewThread(), lldb_private::process_linux::NativeProcessLinux::NotifyTracersOfThreadDestroyed(), lldb_private::FileCache::OpenFile(), lldb_private::Options::Parse(), lldb_private::StructuredData::ParseJSONFromFile(), lldb_private::CommandObject::ParseOptions(), lldb_private::process_linux::NativeProcessLinux::PopulateMemoryRegionCache(), lldb_private::Platform::PutFile(), lldb_private::process_linux::NativeProcessLinux::ReadMemoryTags(), lldb_private::ScriptInterpreterLua::RegisterBreakpointCallback(), lldb_private::ScriptInterpreterLua::RegisterWatchpointCallback(), lldb::SBThread::ReturnFromFrame(), lldb_private::MainLoopWindows::Run(), lldb_private::ExpressionParser::RunStaticInitializers(), lldb::SBThread::RunToAddress(), lldb_private::PluginManager::SaveCore(), ObjectFileMachO::SaveCore(), ObjectFileMinidump::SaveCore(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::DescriptionLevel >(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb::SBBreakpoint::SetIsHardware(), lldb::SBTarget::SetLabel(), BreakpointAccessOptionGroup::SetOptionValue(), BreakpointNameOptionGroup::SetOptionValue(), BreakpointNamesOptionGroup::SetOptionValue(), CommandObjectBreakpointAddAddress::CommandOptions::SetOptionValue(), CommandObjectBreakpointAddFile::CommandOptions::SetOptionValue(), CommandObjectBreakpointAddName::CommandOptions::SetOptionValue(), CommandObjectBreakpointAddPattern::CommandOptions::SetOptionValue(), CommandObjectBreakpointRead::CommandOptions::SetOptionValue(), CommandObjectBreakpointSet::CommandOptions::SetOptionValue(), CommandObjectStatsDump::CommandOptions::SetOptionValue(), lldb_private::BreakpointOptionGroup::SetOptionValue(), lldb_private::Target::StopHookScripted::SetScriptCallback(), lldb_private::NativeProcessProtocol::SetSoftwareBreakpoint(), lldb_private::Scalar::SetValueFromCString(), lldb_private::OptionValueRegex::SetValueFromString(), lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess(), lldb_private::ThreadedCommunication::StartReadThread(), lldb::SBThread::StepInstruction(), lldb::SBThread::StepInto(), lldb::SBThread::StepOut(), lldb::SBThread::StepOutOfFrame(), lldb::SBThread::StepOver(), lldb::SBThread::StepOverUntil(), lldb::SBThread::StepUsingScriptedThreadPlan(), lldb::SBThread::Suspend(), lldb::SBThread::UnwindInnermostExpression(), lldb_private::ValueObjectVariable::UpdateValue(), lldb_private::ValueObjectVTable::UpdateValue(), lldb_private::Process::WriteMemoryTags(), lldb_private::process_linux::NativeProcessLinux::WriteMemoryTags(), and lldb_private::IRExecutionUnit::WriteNow().
FromErrorString()
Status lldb_private::Status::FromErrorString (const char * str) inline static
Definition at line 141 of file Status.h.
References Status().
Referenced by lldb_private::ClangUserExpression::AddArguments(), lldb::SBBreakpoint::AddLocation(), lldb::SBBreakpoint::AddNameWithErrorHandling(), AddPosixSpawnFileAction(), MinidumpFileBuilder::AddSystemInfo(), lldb_private::SaveCoreOptions::AddThread(), MinidumpFileBuilder::AddThreadList(), lldb_private::CommandInterpreter::AddUserCommand(), lldb::SBProcess::AllocateMemory(), lldb_private::Process::AllocateMemory(), lldb_private::ProcessDebugger::AllocateMemory(), AlreadyLocked(), lldb::SBPlatform::Attach(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::Attach(), lldb_private::PlatformQemuUser::Attach(), lldb_private::PlatformWasm::Attach(), lldb_private::PlatformWindows::Attach(), lldb_private::Process::Attach(), lldb_private::ScriptedProcessInterface::Attach(), lldb_private::Target::Attach(), PlatformPOSIX::Attach(), AttachToProcess(), lldb_private::ScriptedPlatformInterface::AttachToProcess(), CoreSimulatorSupport::Device::Boot(), lldb_private::ConnectionFileDescriptor::BytesAvailable(), lldb_private::Process::CalculateCoreFileSaveRanges(), lldb_private::plugin::dwarf::SymbolFileDWARF::CalculateFrameVariableError(), IRInterpreter::CanInterpret(), DynamicLoaderDarwinKernel::CanLoadImage(), DynamicLoaderFreeBSDKernel::CanLoadImage(), DynamicLoaderMacOS::CanLoadImage(), DynamicLoaderMacOSXDYLD::CanLoadImage(), DynamicLoaderStatic::CanLoadImage(), CanTrace(), lldb_private::ValueObject::Cast(), lldb_private::ValueObject::CastToBasicType(), lldb_private::ValueObject::CastToEnumType(), lldb_private::NativeRegisterContext::ClearAllHardwareBreakpoints(), lldb_private::NativeRegisterContext::ClearAllHardwareWatchpoints(), lldb_private::NativeRegisterContext::ClearWatchpointHit(), lldb_private::NativeRegisterContextDBReg_x86::ClearWatchpointHit(), lldb_private::FileCache::CloseFile(), CommandObjectScriptingObjectParsed::CommandObjectScriptingObjectParsed(), ComputeSignalInfo(), lldb_private::BreakpointLocation::ConditionSaysStop(), lldb_private::BreakpointPrecondition::ConfigurePrecondition(), lldb_private::ObjCLanguageRuntime::ObjCExceptionPrecondition::ConfigurePrecondition(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ConfigureRemoteStructuredData(), lldb_private::Process::ConfigureStructuredData(), lldb_private::ConnectionFileDescriptor::Connect(), lldb_private::DomainSocket::Connect(), lldb::SBPlatform::ConnectRemote(), lldb_private::platform_android::PlatformAndroid::ConnectRemote(), lldb_private::platform_android::PlatformAndroidRemoteGDBServer::ConnectRemote(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::ConnectRemote(), lldb_private::PlatformAppleSimulator::ConnectRemote(), lldb_private::PlatformWasm::ConnectRemote(), lldb_private::PlatformWindows::ConnectRemote(), lldb_private::Process::ConnectRemote(), PlatformPOSIX::ConnectRemote(), lldb_private::process_gdb_remote::ProcessGDBRemote::ConnectToDebugserver(), lldb_private::minidump::consumeObject(), lldb::SBProcess::Continue(), lldb_private::ProcessLaunchInfo::ConvertArgumentsForLaunchingInShell(), lldb_private::Socket::Create(), lldb_private::ScriptedProcessInterface::CreateBreakpoint(), lldb_private::Target::CreateBreakpointAtUserEntry(), lldb_private::UDPSocket::CreateConnected(), lldb_private::Breakpoint::CreateFromStructuredData(), lldb_private::BreakpointOptions::CommandData::CreateFromStructuredData(), lldb_private::BreakpointOptions::CreateFromStructuredData(), lldb_private::BreakpointResolver::CreateFromStructuredData(), lldb_private::BreakpointResolverAddress::CreateFromStructuredData(), lldb_private::BreakpointResolverFileLine::CreateFromStructuredData(), lldb_private::BreakpointResolverFileRegex::CreateFromStructuredData(), lldb_private::BreakpointResolverName::CreateFromStructuredData(), lldb_private::BreakpointResolverScripted::CreateFromStructuredData(), lldb_private::SearchFilter::CreateFromStructuredData(), lldb_private::SearchFilterByModule::CreateFromStructuredData(), lldb_private::SearchFilterByModuleListAndCU::CreateFromStructuredData(), lldb_private::ClangREPL::CreateInstance(), lldb_private::PipePosix::CreateNew(), lldb::SBTrace::CreateNewCursor(), sddarwinlog_private::ExactMatchFilterRule::CreateOperation(), sddarwinlog_private::RegexFilterRule::CreateOperation(), lldb::SBFrame::CreateProcessIsRunningExprEvalError(), lldb_private::Platform::CreateSymlink(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::CreateSymlink(), lldb::SBDebugger::CreateTarget(), lldb_private::OptionValue::CreateValueFromCStringForTypeMask(), lldb_private::Target::CreateWatchpoint(), lldb::SBProcess::DeallocateMemory(), lldb_private::ProcessDebugger::DeallocateMemory(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::DebugProcess(), lldb_private::PlatformDarwin::DebugProcess(), lldb_private::PlatformQemuUser::DebugProcess(), lldb_private::PlatformWasm::DebugProcess(), lldb_private::PlatformWindows::DebugProcess(), PlatformPOSIX::DebugProcess(), EntityResultVariable::Dematerialize(), lldb_private::Materializer::Dematerializer::Dematerialize(), lldb::SBProcess::Destroy(), lldb::SBProcess::Detach(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::Detach(), lldb_private::process_gdb_remote::ProcessGDBRemote::DisableBreakpointSite(), ProcessKDP::DisableBreakpointSite(), lldb_private::Process::DisableSoftwareBreakpoint(), lldb_private::Process::DisableWatchpoint(), lldb_private::process_gdb_remote::ProcessGDBRemote::DisableWatchpoint(), lldb_private::IRExecutionUnit::DisassembleFunction(), lldb_private::PlatformAppleSimulator::DisconnectRemote(), lldb_private::PlatformWindows::DisconnectRemote(), PlatformPOSIX::DisconnectRemote(), ProcessKDP::DoAllocateMemory(), ProcessKDP::DoAttachToProcessWithID(), lldb_private::Process::DoAttachToProcessWithName(), ProcessKDP::DoAttachToProcessWithName(), lldb_private::Process::DoConnectRemote(), ProcessKDP::DoConnectRemote(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoDeallocateMemory(), ProcessKDP::DoDeallocateMemory(), lldb_private::ProcessWindows::DoDetach(), CommandObjectPlatformShell::DoExecute(), lldb_private::Process::DoGetMemoryRegionInfo(), ProcessKDP::DoHalt(), ProcessKDP::DoLaunch(), ProcessElfCore::DoLoadCore(), ProcessMachCore::DoLoadCore(), lldb_private::Platform::DoLoadImage(), lldb_private::PlatformWindows::DoLoadImage(), lldb_private::LockFileBase::DoLock(), lldb_private::ClangExpressionParser::DoPrepareForExecution(), ProcessKDP::DoReadMemory(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoResume(), lldb_private::ProcessWindows::DoResume(), ProcessKDP::DoResume(), ProcessKDP::DoSignal(), ProcessKDP::DoWillAttachToProcessWithID(), ProcessKDP::DoWillAttachToProcessWithName(), ProcessKDP::DoWillLaunch(), lldb_private::Platform::DownloadModuleSlice(), lldb_private::platform_android::PlatformAndroid::DownloadModuleSlice(), lldb_private::Platform::DownloadSymbolFile(), lldb_private::platform_android::PlatformAndroid::DownloadSymbolFile(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoWriteMemory(), ProcessKDP::DoWriteMemory(), lldb_private::process_gdb_remote::ProcessGDBRemote::EnableBreakpointSite(), lldb_private::ProcessWindows::EnableBreakpointSite(), lldb_private::ScriptedProcess::EnableBreakpointSite(), ProcessKDP::EnableBreakpointSite(), lldb_private::Process::EnableSoftwareBreakpoint(), lldb_private::Process::EnableWatchpoint(), lldb_private::process_gdb_remote::ProcessGDBRemote::EnableWatchpoint(), lldb_private::process_gdb_remote::ProcessGDBRemote::EstablishConnectionIfNeeded(), lldb::SBTarget::EvaluateExpression(), PlatformPOSIX::EvaluateLibdlExpression(), lldb::SBPlatform::ExecuteConnected(), lldb_private::ScriptInterpreter::ExecuteMultipleLines(), lldb_private::ScriptInterpreter::ExportFunctionDefinitionToInterpreter(), ExtractRuntimeGlobalSymbol(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject(), fileLock(), lldb_private::StructuredDataDarwinLog::FilterLaunchInfo(), lldb_private::SymbolContext::FindBestGlobalDataSymbol(), lldb::SBProcess::FindInMemory(), lldb_private::Process::FindInMemory(), lldb::SBProcess::FindRangesInMemory(), lldb_private::Process::FindRangesInMemory(), lldb_private::process_gdb_remote::ProcessGDBRemote::FlashErase(), lldb::SBFile::Flush(), lldb_private::NativeFile::Flush(), CommandObjectTypeSummaryList::FormatterSpecificList(), ForwardPortWithAdb(), lldb_private::IRMemoryMap::Free(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::GDBRemoteCommunicationServerPlatform(), lldb_private::ScriptInterpreter::GenerateBreakpointCommandCallbackData(), lldb_private::ScriptInterpreter::GenerateFunction(), lldb::SBPlatform::Get(), lldb::SBPlatform::GetAllProcesses(), lldb_private::StructuredDataImpl::GetAsJSON(), lldb_private::RegisterValue::GetAsMemoryData(), lldb_private::Scalar::GetAsMemoryData(), lldb_private::AppleGetQueuesHandler::GetCurrentQueues(), lldb_private::SaveCoreOptions::GetCurrentSizeInBytes(), lldb_private::StructuredDataDarwinLog::GetDescription(), lldb_private::StructuredDataImpl::GetDescription(), lldb::SBThread::GetDescriptionWithFormat(), lldb_private::Platform::GetFile(), lldb_private::platform_android::PlatformAndroid::GetFile(), PlatformPOSIX::GetFile(), lldb_private::Process::GetFileLoadAddress(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetFileLoadAddress(), lldb_private::process_linux::NativeProcessLinux::GetFileLoadAddress(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetFilePermissions(), lldb_private::NativeFile::GetFileSpec(), lldb_private::StackFrame::GetFrameBaseExpression(), lldb_private::StackFrame::GetFrameBaseValue(), lldb_private::NativeRegisterContext::GetHardwareBreakHitIndex(), lldb_private::AppleGetItemInfoHandler::GetItemInfo(), lldb_private::IRMemoryMap::GetMemoryData(), lldb_private::Module::GetMemoryObjectFile(), lldb_private::ScriptedProcessInterface::GetMemoryRegionContainingAddress(), lldb::SBProcess::GetMemoryRegionInfo(), lldb_private::NativeProcessProtocol::GetMemoryRegionInfo(), lldb_private::Process::GetMemoryRegionInfo(), lldb_private::process_freebsd::NativeProcessFreeBSD::GetMemoryRegionInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetMemoryRegionInfo(), lldb_private::process_linux::NativeProcessLinux::GetMemoryRegionInfo(), lldb_private::process_netbsd::NativeProcessNetBSD::GetMemoryRegionInfo(), lldb_private::ProcessDebugger::GetMemoryRegionInfo(), lldb_private::SaveCoreOptions::GetMemoryRegionsToSave(), lldb::SBProcess::GetNumSupportedHardwareWatchpoints(), lldb_private::Target::GetOrCreateModule(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::GetPacketAndSendResponse(), lldb_private::AppleGetPendingItemsHandler::GetPendingItems(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetQXferMemoryMapRegionInfo(), lldb_private::Target::GetREPL(), lldb_private::IRExecutionUnit::GetRunnableInfo(), lldb_private::ModuleList::GetSharedModule(), lldb_private::PlatformDarwinDevice::GetSharedModuleWithLocalCache(), lldb_private::Thread::GetSiginfoValue(), lldb::SBValue::GetSP(), lldb_private::ValueImpl::GetSP(), lldb_private::PlatformAppleSimulator::GetSymbolFile(), lldb_private::PlatformRemoteDarwinDevice::GetSymbolFile(), lldb_private::AppleGetThreadItemInfoHandler::GetThreadItemInfo(), lldb_private::Value::GetValueAsData(), lldb::SBValue::GetValueAsSigned(), lldb::SBValue::GetValueAsUnsigned(), lldb_private::Value::GetValueByteSize(), lldb_private::Variable::GetValuesForVariableExpressionPath(), lldb_private::NativeRegisterContext::GetWatchpointHitIndex(), lldb_private::Process::Halt(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_jLLDBTraceGetBinaryData(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_jLLDBTraceGetState(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_jLLDBTraceStart(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_jLLDBTraceStop(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_jLLDBTraceSupported(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_QNonStop(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qSaveCore(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_vCtrlC(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_vRun(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::HandleNotificationAck(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::HandshakeWithServer(), lldb_private::SystemInitializerFull::Initialize(), lldb_private::Platform::Install(), IRInterpreter::Interpret(), lldb_private::NativeProcessProtocol::Interrupt(), lldb_private::ValueObject::IsLogicalTrue(), lldb_private::NativeRegisterContext::IsWatchpointHit(), lldb_private::NativeRegisterContextDBReg_x86::IsWatchpointHit(), lldb_private::NativeRegisterContext::IsWatchpointVacant(), lldb_private::NativeRegisterContextDBReg_x86::IsWatchpointVacant(), lldb::SBThread::JumpToLine(), lldb_private::Thread::JumpToLine(), lldb::SBProcess::Kill(), lldb_private::Platform::KillProcess(), lldb_private::ScriptedPlatformInterface::KillProcess(), lldb_private::Process::Launch(), lldb_private::ScriptedProcessInterface::Launch(), lldb_private::Target::Launch(), lldb_private::process_gdb_remote::ProcessGDBRemote::LaunchAndConnectToDebugserver(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::LaunchGDBServer(), lldb_private::Process::LaunchPrivate(), lldb_private::MonitoringProcessLauncher::LaunchProcess(), lldb_private::Platform::LaunchProcess(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::LaunchProcess(), lldb_private::PlatformAppleSimulator::LaunchProcess(), lldb_private::ProcessDebugger::LaunchProcess(), lldb_private::ScriptedPlatformInterface::LaunchProcess(), lldb_private::IRMemoryMap::Leak(), lldb_private::StackFrame::LegacyGetValueForVariableExpressionPath(), lldb_private::DomainSocket::Listen(), lldb_private::Process::LoadCore(), lldb::SBProcess::LoadImage(), lldb_private::Platform::LoadImage(), lldb::SBProcess::LoadImageUsingPaths(), lldb_private::Debugger::LoadPlugin(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::LoadQXferMemoryMap(), lldb_private::ScriptInterpreter::LoadScriptingModule(), lldb_private::Module::LoadScriptingResourceInTarget(), lldb::SBTrace::LoadTraceFromFile(), lldb::SBPlatform::MakeDirectory(), lldb_private::UtilityFunction::MakeFunctionCaller(), EntityResultVariable::Materialize(), lldb_private::Materializer::Materialize(), NotLocked(), lldb_private::PipePosix::OpenAsReader(), lldb_private::FileCache::OpenFile(), CommandObjectTargetModulesLookup::CommandOptions::OptionParsingFinished(), lldb_private::Options::Parse(), sddarwinlog_private::ParseAutoEnableOptions(), sddarwinlog_private::EnableOptions::ParseFilterRule(), ParseInternal(), lldb_private::process_freebsd::NativeProcessFreeBSD::PopulateMemoryRegionCache(), lldb_private::process_linux::NativeProcessLinux::PopulateMemoryRegionCache(), lldb_private::process_netbsd::NativeProcessNetBSD::PopulateMemoryRegionCache(), lldb_private::Process::PrivateResume(), lldb_private::Platform::PutFile(), PlatformPOSIX::PutFile(), lldb_private::Process::PutSTDIN(), lldb::SBFile::Read(), lldb_private::ConnectionFileDescriptor::Read(), lldb_private::NativeFile::Read(), lldb_private::NativeFile::Read(), lldb_private::ThreadedCommunication::Read(), lldb::SBProcess::ReadCStringFromMemory(), lldb_private::Process::ReadCStringFromMemory(), lldb_private::Target::ReadCStringFromMemory(), lldb_private::FileCache::ReadFile(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ReadFile(), lldb_private::Communication::ReadFromConnection(), lldb::SBProcess::ReadMemory(), lldb_private::IRMemoryMap::ReadMemory(), lldb_private::ProcessDebugger::ReadMemory(), lldb_private::Target::ReadMemoryFromFileCache(), lldb_private::NativeProcessProtocol::ReadMemoryTags(), lldb_private::platform_android::AdbClient::ReadMessageStream(), lldb_private::ValueObject::ReadPointedString(), lldb::SBProcess::ReadPointerFromMemory(), lldb_private::NativeRegisterContext::ReadRegisterValueFromMemory(), lldb_private::RegisterContext::ReadRegisterValueFromMemory(), lldb_private::RegisterContextThreadMemory::ReadRegisterValueFromMemory(), lldb_private::IRMemoryMap::ReadScalarFromMemory(), lldb_private::Process::ReadScalarIntegerFromMemory(), lldb::SBProcess::ReadUnsignedFromMemory(), RecurseCopy_Callback(), ObjectFileELF::RefineModuleDetailsFromNote(), lldb_private::MainLoopPosix::RegisterReadObject(), lldb_private::MainLoopWindows::RegisterReadObject(), lldb::SBProcess::RemoteAttachToProcessWithID(), lldb::SBProcess::RemoteLaunch(), lldb_private::NativeThreadWindows::RemoveHardwareBreakpoint(), lldb_private::process_freebsd::NativeThreadFreeBSD::RemoveHardwareBreakpoint(), lldb_private::process_linux::NativeThreadLinux::RemoveHardwareBreakpoint(), lldb_private::process_netbsd::NativeThreadNetBSD::RemoveHardwareBreakpoint(), lldb_private::NativeProcessProtocol::RemoveSoftwareBreakpoint(), lldb_private::NativeThreadWindows::RemoveWatchpoint(), lldb_private::process_freebsd::NativeThreadFreeBSD::RemoveWatchpoint(), lldb_private::process_linux::NativeThreadLinux::RemoveWatchpoint(), lldb_private::process_netbsd::NativeThreadNetBSD::RemoveWatchpoint(), lldb_private::Platform::ResolveExecutable(), lldb_private::Process::ResolveIndirectFunction(), lldb_private::Platform::ResolveSymbolFile(), lldb::SBThread::Resume(), lldb_private::NativeProcessWindows::Resume(), lldb_private::Process::Resume(), lldb_private::process_freebsd::NativeProcessFreeBSD::Resume(), lldb_private::process_netbsd::NativeProcessNetBSD::Resume(), lldb_private::ScriptedProcessInterface::Resume(), ResumeNewPlan(), lldb_private::Process::ResumeSynchronous(), lldb_private::Thread::ReturnFromFrame(), lldb::SBPlatform::Run(), lldb::SBDebugger::RunREPL(), lldb_private::Debugger::RunREPL(), lldb_private::ScriptInterpreter::RunScriptFormatKeyword(), lldb_private::ScriptInterpreter::RunScriptFormatKeyword(), lldb_private::ScriptInterpreter::RunScriptFormatKeyword(), lldb_private::ScriptInterpreter::RunScriptFormatKeyword(), lldb_private::ScriptInterpreter::RunScriptFormatKeyword(), lldb_private::Host::RunShellCommand(), lldb_private::Platform::RunShellCommand(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::RunShellCommand(), lldb_private::ExpressionParser::RunStaticInitializers(), lldb::SBThread::RunToAddress(), lldb::SBProcess::SaveCore(), lldb_private::PluginManager::SaveCore(), lldb_private::SaveMiniDump(), lldb::SBTrace::SaveToDisk(), lldb_private::ClangUserExpression::ScanContext(), lldb_private::ScriptedProcess::ScriptedProcess(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StreamSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ThreadSP >(), lldb_private::NativeFile::SeekFromCurrent(), lldb_private::NativeFile::SeekFromEnd(), lldb_private::NativeFile::SeekFromStart(), SelectHelper::Select(), lldb::SBProcess::SendEventData(), lldb_private::Process::SendEventData(), lldb_private::process_gdb_remote::ProcessGDBRemote::SendEventData(), CommunicationKDP::SendRawRequest(), CommunicationKDP::SendRequestReadMemory(), CommunicationKDP::SendRequestReadRegisters(), CommunicationKDP::SendRequestWriteMemory(), CommunicationKDP::SendRequestWriteRegisters(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendSignalsToIgnore(), lldb_private::Target::SerializeBreakpointsToFile(), lldb_private::OptionValueArray::SetArgs(), lldb_private::OptionValueDictionary::SetArgs(), lldb_private::process_netbsd::NativeProcessNetBSD::SetBreakpoint(), lldb_private::ScriptInterpreter::SetBreakpointCommandCallback(), lldb_private::ScriptInterpreter::SetBreakpointCommandCallback(), lldb_private::ScriptInterpreter::SetBreakpointCommandCallbackFunction(), lldb::SBDebugger::SetCurrentPlatform(), lldb::SBValue::SetData(), lldb_private::ValueObject::SetData(), lldb_private::ValueObjectDynamicValue::SetData(), lldb_private::ValueObjectRegister::SetData(), lldb_private::ValueObjectVariable::SetData(), lldb::SBCommandReturnObject::SetError(), lldb::SBDebugger::SetErrorFile(), lldb::SBError::SetErrorString(), SetErrorWithJSON(), lldb::SBPlatform::SetFilePermissions(), lldb::SBStructuredData::SetFromJSON(), lldb_private::NativeProcessProtocol::SetHardwareBreakpoint(), lldb_private::NativeThreadWindows::SetHardwareBreakpoint(), lldb_private::process_freebsd::NativeThreadFreeBSD::SetHardwareBreakpoint(), lldb_private::process_linux::NativeThreadLinux::SetHardwareBreakpoint(), lldb_private::process_netbsd::NativeThreadNetBSD::SetHardwareBreakpoint(), lldb_private::NativeRegisterContextDBReg_x86::SetHardwareWatchpointWithIndex(), lldb::SBDebugger::SetInputFile(), lldb::SBDebugger::SetInputString(), lldb_private::Debugger::SetInputString(), lldb::SBTarget::SetLabel(), CommandObjectScriptingObjectParsed::CommandOptions::SetOptionsFromArray(), CommandObjectBreakpointAddFile::CommandOptions::SetOptionValue(), CommandObjectMemoryFind::OptionGroupFindMemory::SetOptionValue(), CommandObjectScriptingObjectParsed::CommandOptions::SetOptionValue(), CommandObjectTargetModulesLookup::CommandOptions::SetOptionValue(), CommandObjectThreadJump::CommandOptions::SetOptionValue(), CommandObjectTypeSummaryAdd::CommandOptions::SetOptionValue(), CommandObjectTypeSynthAdd::CommandOptions::SetOptionValue(), lldb_private::OptionGroupFormat::SetOptionValue(), lldb_private::OptionGroupOptions::SetOptionValue(), lldb::SBDebugger::SetOutputFile(), lldb_private::SaveCoreOptions::SetProcess(), ABIMacOSX_arm64::SetReturnValueObject(), ABIMacOSX_arm::SetReturnValueObject(), ABIMacOSX_i386::SetReturnValueObject(), ABISysV_arc::SetReturnValueObject(), ABISysV_arm64::SetReturnValueObject(), ABISysV_arm::SetReturnValueObject(), ABISysV_i386::SetReturnValueObject(), ABISysV_loongarch::SetReturnValueObject(), ABISysV_mips64::SetReturnValueObject(), ABISysV_mips::SetReturnValueObject(), ABISysV_ppc64::SetReturnValueObject(), ABISysV_ppc::SetReturnValueObject(), ABISysV_riscv::SetReturnValueObject(), ABISysV_s390x::SetReturnValueObject(), ABISysV_x86_64::SetReturnValueObject(), ABIWindows_x86_64::SetReturnValueObject(), lldb_private::Target::StopHookScripted::SetScriptCallback(), lldb::SBBreakpoint::SetScriptCallbackBody(), lldb::SBBreakpointLocation::SetScriptCallbackBody(), lldb::SBBreakpoint::SetScriptCallbackFunction(), lldb::SBBreakpointLocation::SetScriptCallbackFunction(), lldb::SBBreakpointName::SetScriptCallbackFunction(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::SetSTDIOFileDescriptor(), lldb_private::OptionValue::SetSubValue(), lldb_private::NativeProcessSoftwareSingleStep::SetupSoftwareSingleStepping(), lldb_private::Scalar::SetValueFromCString(), lldb_private::ValueObject::SetValueFromCString(), lldb_private::ValueObjectDynamicValue::SetValueFromCString(), lldb_private::ValueObjectRegister::SetValueFromCString(), lldb_private::ValueObjectVariable::SetValueFromCString(), lldb_private::RegisterValue::SetValueFromData(), lldb_private::Scalar::SetValueFromData(), lldb_private::ValueObject::SetValueFromInteger(), lldb_private::ValueObject::SetValueFromInteger(), lldb_private::OptionValueBoolean::SetValueFromString(), lldb_private::OptionValueFileColonLine::SetValueFromString(), lldb_private::OptionValueFileSpec::SetValueFromString(), lldb_private::OptionValueFileSpecList::SetValueFromString(), lldb_private::OptionValueFormatEntity::SetValueFromString(), lldb_private::OptionValuePathMappings::SetValueFromString(), lldb_private::OptionValueRegex::SetValueFromString(), lldb_private::OptionValueString::SetValueFromString(), lldb_private::RegisterValue::SetValueFromString(), lldb_private::NativeThreadWindows::SetWatchpoint(), lldb_private::process_freebsd::NativeThreadFreeBSD::SetWatchpoint(), lldb_private::process_linux::NativeThreadLinux::SetWatchpoint(), lldb_private::process_netbsd::NativeThreadNetBSD::SetWatchpoint(), lldb_private::Platform::ShellExpandArguments(), CoreSimulatorSupport::Device::Shutdown(), lldb::SBProcess::Signal(), lldb_private::HostProcessPosix::Signal(), lldb_private::NativeProcessWindows::Signal(), CoreSimulatorSupport::Device::Spawn(), lldb::SBTrace::Start(), lldb::SBTrace::Start(), lldb_private::Thread::StepIn(), lldb::SBThread::StepInstruction(), lldb::SBThread::StepInto(), lldb::SBThread::StepOut(), lldb_private::Thread::StepOut(), lldb::SBThread::StepOutOfFrame(), lldb::SBThread::StepOver(), lldb_private::Thread::StepOver(), lldb::SBThread::StepOverUntil(), lldb::SBThread::StepUsingScriptedThreadPlan(), lldb::SBProcess::Stop(), lldb::SBTrace::Stop(), lldb::SBTrace::Stop(), lldb_private::BreakpointID::StringIsBreakpointName(), lldb::SBThread::Suspend(), lldb_private::NativeFile::Sync(), lldb_private::OptionArgParser::ToOptionEnum(), lldb_private::Platform::Unlink(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::Unlink(), lldb::SBProcess::UnloadImage(), lldb_private::Platform::UnloadImage(), lldb_private::PlatformWindows::UnloadImage(), lldb_private::Thread::UnwindInnermostExpression(), lldb_private::ValueObjectChild::UpdateValue(), lldb_private::ValueObjectDynamicValue::UpdateValue(), lldb_private::ValueObjectMemory::UpdateValue(), lldb_private::ValueObjectRegister::UpdateValue(), lldb_private::ValueObjectRegisterSet::UpdateValue(), lldb_private::ValueObjectVariable::UpdateValue(), lldb_private::ValueObjectVTable::UpdateValue(), ValueObjectVTableChild::UpdateValue(), lldb_private::ValueObject::UpdateValueIfNeeded(), lldb_private::CommandInterpreter::VerifyUserMultiwordCmdPath(), lldb::SBValue::Watch(), lldb::SBFile::Write(), lldb_private::Communication::Write(), lldb_private::ConnectionFileDescriptor::Write(), lldb_private::NativeFile::Write(), lldb_private::NativeFile::Write(), lldb_private::FileCache::WriteFile(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteFile(), lldb::SBProcess::WriteMemory(), lldb_private::IRMemoryMap::WriteMemory(), lldb_private::Process::WriteMemory(), lldb_private::ProcessDebugger::WriteMemory(), lldb_private::NativeProcessProtocol::WriteMemoryTags(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteMemoryTags(), lldb_private::NativeRegisterContext::WriteRegisterFromUnsigned(), lldb_private::NativeRegisterContext::WriteRegisterFromUnsigned(), lldb_private::NativeRegisterContext::WriteRegisterValueToMemory(), lldb_private::RegisterContext::WriteRegisterValueToMemory(), lldb_private::RegisterContextThreadMemory::WriteRegisterValueToMemory(), lldb_private::IRMemoryMap::WriteScalarToMemory(), and lldb_private::Process::WriteScalarToMemory().
FromErrorStringWithFormat()
Status Status::FromErrorStringWithFormat (const char * format, ...) static
Definition at line 106 of file Status.cpp.
References Status(), and lldb_private::VASprintf().
Referenced by MinidumpFileBuilder::AddDirectory(), CommandObjectTypeFilterAdd::AddFilter(), MinidumpFileBuilder::AddHeaderAndCalculateDirectories(), lldb::SBBreakpoint::AddLocation(), MinidumpFileBuilder::AddMemoryList(), MinidumpFileBuilder::AddMemoryList_64(), lldb_private::Target::AddNameToBreakpoint(), lldb_private::ValueObject::AddressOf(), MinidumpFileBuilder::AddSystemInfo(), MinidumpFileBuilder::AddThreadList(), lldb::SBTarget::Attach(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::Attach(), lldb_private::Process::Attach(), lldb_private::Target::Attach(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::AttachToProcess(), lldb_private::Process::CalculateCoreFileSaveRanges(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CalculateFrameVariableError(), lldb_private::ValueObject::CastToBasicType(), lldb_private::ValueObject::CastToEnumType(), CheckIfWatchpointsSupported(), lldb_private::FileCache::CloseFile(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::CloseFile(), lldb_private::SharedSocket::CompleteSending(), lldb_private::ConnectionFileDescriptor::Connect(), lldb_private::ConnectionGenericFile::Connect(), lldb_private::UDPSocket::Connect(), lldb_private::ConnectionFileDescriptor::ConnectFD(), lldb_private::platform_android::PlatformAndroid::ConnectRemote(), lldb_private::platform_android::PlatformAndroidRemoteGDBServer::ConnectRemote(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::ConnectRemote(), lldb_private::PlatformAppleSimulator::ConnectRemote(), lldb_private::Target::CreateBreakpointsFromFile(), lldb_private::UDPSocket::CreateConnected(), lldb_private::Breakpoint::CreateFromStructuredData(), lldb_private::BreakpointOptions::CreateFromStructuredData(), lldb_private::SearchFilterByModuleList::CreateFromStructuredData(), lldb_private::SearchFilterByModuleListAndCU::CreateFromStructuredData(), lldb_private::BreakpointResolverScripted::CreateImplementationIfNeeded(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::CreateSymlink(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::CreateSymlink(), lldb::SBDebugger::CreateTargetWithFileAndArch(), lldb_private::Target::CreateWatchpoint(), lldb_private::Process::DeallocateMemory(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::DebugProcess(), EntityPersistentVariable::Dematerialize(), EntityRegister::Dematerialize(), EntityResultVariable::Dematerialize(), EntityVariableBase::Dematerialize(), lldb_private::ValueObject::Dereference(), EntityPersistentVariable::DestroyAllocation(), lldb_private::Process::DisableBreakpointSiteByID(), lldb_private::ProcessWindows::DisableWatchpoint(), lldb_private::IRExecutionUnit::DisassembleFunction(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoAllocateMemory(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoConnectRemote(), ProcessKDP::DoConnectRemote(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoDeallocateMemory(), lldb_private::minidump::ProcessMinidump::DoLoadCore(), lldb_private::PlatformWindows::DoLoadImage(), PlatformPOSIX::DoLoadImage(), lldb_private::ClangExpressionParser::DoPrepareForExecution(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoReadMemory(), ProcessElfCore::DoReadMemory(), ProcessFreeBSDKernelCore::DoReadMemory(), ProcessMachCore::DoReadMemory(), ProcessKDP::DoResume(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoSignal(), lldb_private::OptionArgParser::DoToAddress(), lldb_private::Platform::DownloadModuleSlice(), lldb_private::platform_android::PlatformAndroid::DownloadSymbolFile(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoWriteMemory(), MinidumpFileBuilder::DumpDirectories(), MinidumpFileBuilder::DumpHeader(), lldb_private::process_gdb_remote::ProcessGDBRemote::EnableBreakpointSite(), lldb_private::Process::EnableBreakpointSiteByID(), lldb_private::Process::EnableSoftwareBreakpoint(), lldb_private::ProcessWindows::EnableWatchpoint(), ExceptionMaskValidator(), lldb_private::FormatEntity::ExtractVariableInfo(), lldb_private::CoreFileMemoryRanges::FinalizeCoreFileSaveRanges(), OptionGroupReadMemory::FinalizeSettings(), lldb_private::Target::FindBreakpointName(), MinidumpFileBuilder::FixThreadStacks(), lldb_private::process_gdb_remote::ProcessGDBRemote::FlashDone(), lldb_private::process_gdb_remote::ProcessGDBRemote::FlashErase(), MinidumpFileBuilder::FlushBufferToDisk(), lldb_private::ModuleCache::Get(), lldb_private::ModuleCache::GetAndPut(), lldb_private::RegisterValue::GetAsMemoryData(), lldb::SBThread::GetDescriptionWithFormat(), lldb::SBValue::GetError(), lldb_private::NativeProcessWindows::GetFileLoadAddress(), lldb_private::process_freebsd::NativeProcessFreeBSD::GetFileLoadAddress(), lldb_private::process_netbsd::NativeProcessNetBSD::GetFileLoadAddress(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::GetFilePermissions(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetFilePermissions(), PlatformPOSIX::GetFullNameForDylib(), lldb_private::Target::GetFunctionCallerForLanguage(), lldb_private::NativeProcessWindows::GetLoadedModuleFileSpec(), lldb_private::process_freebsd::NativeProcessFreeBSD::GetLoadedModuleFileSpec(), lldb_private::process_linux::NativeProcessLinux::GetLoadedModuleFileSpec(), lldb_private::process_netbsd::NativeProcessNetBSD::GetLoadedModuleFileSpec(), lldb_private::IRMemoryMap::GetMemoryData(), lldb_private::Module::GetMemoryObjectFile(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetModuleByCompUnitInfo(), lldb_private::Platform::GetRemoteSharedModule(), lldb_private::Target::GetREPL(), GetResponseError(), lldb_private::IRExecutionUnit::GetRunnableInfo(), lldb_private::ModuleList::GetSharedModule(), StringExtractorGDBRemote::GetStatus(), lldb_private::OptionValueArray::GetSubValue(), lldb_private::OptionValueDictionary::GetSubValue(), lldb_private::Target::GetUserExpressionForLanguage(), lldb_private::Value::GetValueAsData(), lldb::SBValue::GetValueAsSigned(), lldb::SBValue::GetValueAsUnsigned(), lldb_private::Process::Halt(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_D(), HandleFileAction(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::HandshakeWithServer(), lldb::SBPlatform::Install(), lldb_private::Platform::Install(), lldb_private::platform_android::AdbClient::internalShell(), IRInterpreter::Interpret(), lldb_private::Thread::JumpToLine(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::KillProcess(), lldb_private::Target::Launch(), lldb_private::Process::LaunchPrivate(), lldb_private::Platform::LaunchProcess(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::LaunchProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::LaunchProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::LaunchProcess(), lldb_private::ProcessDebugger::LaunchProcess(), LaunchProcessPosixSpawn(), LaunchProcessXPC(), lldb_private::StackFrame::LegacyGetValueForVariableExpressionPath(), lldb_private::UDPSocket::Listen(), lldb_private::ModuleList::LoadScriptingResourcesInTarget(), EntityPersistentVariable::MakeAllocation(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::MakeDirectory(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::MakeDirectory(), PlatformPOSIX::MakeLoadImageUtilityFunction(), EntityPersistentVariable::Materialize(), EntityRegister::Materialize(), EntityResultVariable::Materialize(), EntitySymbol::Materialize(), EntityVariableBase::Materialize(), lldb_private::OptionGroupPythonClassWithDict::OptionParsingFinished(), CommandObjectTypeFilterAdd::CommandOptions::OptionParsingStarting(), ELFLinuxPrPsInfo::Parse(), ELFLinuxPrStatus::Parse(), lldb_private::Options::Parse(), ParseEntry(), sddarwinlog_private::EnableOptions::ParseFilterRule(), ParseInternal(), lldb_private::CommandInterpreter::PreprocessToken(), lldb_private::platform_android::AdbSyncService::PullFileChunk(), lldb_private::platform_android::AdbSyncService::PullFileImpl(), lldb_private::platform_android::AdbSyncService::PushFileImpl(), lldb::SBPlatform::Put(), lldb_private::ModuleCache::Put(), lldb_private::MemoryCache::Read(), ReadAllBytes(), lldb_private::FileCache::ReadFile(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::ReadFile(), lldb::SBProcess::ReadMemory(), lldb_private::Target::ReadMemory(), lldb_private::Target::ReadMemoryFromFileCache(), lldb_private::process_linux::NativeRegisterContextLinux::ReadRegisterRaw(), lldb_private::NativeRegisterContext::ReadRegisterValueFromMemory(), lldb_private::RegisterContext::ReadRegisterValueFromMemory(), lldb_private::IRMemoryMap::ReadScalarFromMemory(), lldb_private::Process::ReadScalarIntegerFromMemory(), lldb_private::Target::ReadScalarIntegerFromMemory(), MinidumpFileBuilder::ReadWriteMemoryInChunks(), RecurseCopy_Callback(), ObjectFileELF::RefineModuleDetailsFromNote(), lldb_private::MainLoopPosix::RegisterReadObject(), lldb_private::MainLoopWindows::RegisterReadObject(), lldb_private::NativeProcessProtocol::RemoveSoftwareBreakpoint(), lldb_private::Process::ResolveIndirectFunction(), lldb_private::FileSystem::ResolveSymbolicLink(), lldb_private::NativeProcessWindows::Resume(), lldb_private::process_freebsd::NativeProcessFreeBSD::Resume(), lldb_private::process_linux::NativeProcessLinux::Resume(), lldb_private::process_netbsd::NativeProcessNetBSD::Resume(), lldb_private::Process::ResumeSynchronous(), lldb_private::Thread::ReturnFromFrameWithIndex(), lldb_private::Debugger::RunREPL(), lldb_private::Host::RunShellCommand(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::RunShellCommand(), ObjectFileMachO::SaveCore(), lldb_private::ScriptedProcess::ScriptedProcess(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointLocationSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::DataExtractorSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ExecutionContextRefSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessAttachInfoSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessLaunchInfoSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameListSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectListSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectSP >(), SelectHelper::Select(), lldb_private::process_gdb_remote::ProcessGDBRemote::SendEventData(), CommunicationKDP::SendRawRequest(), CommunicationKDP::SendRequestReadMemory(), CommunicationKDP::SendRequestReadRegisters(), CommunicationKDP::SendRequestWriteMemory(), CommunicationKDP::SendRequestWriteRegisters(), lldb_private::Target::SerializeBreakpointsToFile(), lldb_private::OptionValueArray::SetArgs(), lldb_private::OptionValueDictionary::SetArgs(), lldb::SBValue::SetData(), lldb_private::ValueObject::SetData(), SetErrorWithJSON(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::SetFilePermissions(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetFilePermissions(), lldb_private::RegisterValue::SetFromMemoryData(), lldb_private::Debugger::SetInputString(), lldb::SBDebugger::SetInternalVariable(), CommandObjectCommandsScriptAdd::CommandOptions::SetOptionValue(), CommandObjectFrameDiagnose::CommandOptions::SetOptionValue(), CommandObjectFrameRecognizerAdd::CommandOptions::SetOptionValue(), CommandObjectFrameSelect::CommandOptions::SetOptionValue(), CommandObjectMemoryWrite::OptionGroupWriteMemory::SetOptionValue(), CommandObjectObjC_ClassTable_Dump::CommandOptions::SetOptionValue(), CommandObjectPlatformFRead::CommandOptions::SetOptionValue(), CommandObjectPlatformFWrite::CommandOptions::SetOptionValue(), CommandObjectPlatformProcessList::CommandOptions::SetOptionValue(), CommandObjectPlatformShell::CommandOptions::SetOptionValue(), CommandObjectProcessContinue::CommandOptions::SetOptionValue(), CommandObjectProcessDetach::CommandOptions::SetOptionValue(), CommandObjectScriptingRun::CommandOptions::SetOptionValue(), CommandObjectSourceInfo::CommandOptions::SetOptionValue(), CommandObjectSourceList::CommandOptions::SetOptionValue(), CommandObjectTargetModulesLookup::CommandOptions::SetOptionValue(), CommandObjectTargetModulesShowUnwind::CommandOptions::SetOptionValue(), CommandObjectTargetStopHookAdd::CommandOptions::SetOptionValue(), CommandObjectThreadBacktrace::CommandOptions::SetOptionValue(), CommandObjectThreadJump::CommandOptions::SetOptionValue(), CommandObjectThreadPlanList::CommandOptions::SetOptionValue(), CommandObjectThreadReturn::CommandOptions::SetOptionValue(), CommandObjectThreadSelect::OptionGroupThreadSelect::SetOptionValue(), CommandObjectThreadUntil::CommandOptions::SetOptionValue(), CommandObjectTraceDumpInstructions::CommandOptions::SetOptionValue(), CommandObjectTypeFormatAdd::CommandOptions::SetOptionValue(), CommandObjectTypeSummaryAdd::CommandOptions::SetOptionValue(), CommandObjectTypeSynthAdd::CommandOptions::SetOptionValue(), CommandObjectWatchpointIgnore::CommandOptions::SetOptionValue(), lldb_private::CommandObjectDisassemble::CommandOptions::SetOptionValue(), lldb_private::CommandObjectExpression::CommandOptions::SetOptionValue(), lldb_private::CommandOptionsProcessLaunch::SetOptionValue(), lldb_private::OptionGroupFormat::SetOptionValue(), lldb_private::OptionGroupPlatformCaching::SetOptionValue(), lldb_private::OptionGroupPlatformRSync::SetOptionValue(), lldb_private::OptionGroupPlatformSSH::SetOptionValue(), lldb_private::OptionGroupValueObjectDisplay::SetOptionValue(), lldb_private::OptionGroupWatchpoint::SetOptionValue(), lldb_private::trace_intel_pt::CommandObjectProcessTraceStartIntelPT::CommandOptions::SetOptionValue(), lldb_private::trace_intel_pt::CommandObjectThreadTraceStartIntelPT::CommandOptions::SetOptionValue(), OptionGroupDependents::SetOptionValue(), OptionGroupReadMemory::SetOptionValue(), OptionPermissions::SetOptionValue(), sddarwinlog_private::EnableOptions::SetOptionValue(), ThreadStepScopeOptionGroup::SetOptionValue(), ABIMacOSX_arm64::SetReturnValueObject(), ABIMacOSX_arm::SetReturnValueObject(), ABIMacOSX_i386::SetReturnValueObject(), ABISysV_arc::SetReturnValueObject(), ABISysV_arm64::SetReturnValueObject(), ABISysV_arm::SetReturnValueObject(), ABISysV_i386::SetReturnValueObject(), ABISysV_loongarch::SetReturnValueObject(), ABISysV_mips64::SetReturnValueObject(), ABISysV_mips::SetReturnValueObject(), ABISysV_ppc64::SetReturnValueObject(), ABISysV_ppc::SetReturnValueObject(), ABISysV_riscv::SetReturnValueObject(), ABISysV_s390x::SetReturnValueObject(), ABISysV_x86_64::SetReturnValueObject(), ABIWindows_x86_64::SetReturnValueObject(), lldb_private::Target::StopHookScripted::SetScriptCallback(), lldb_private::OptionValueDictionary::SetSubValue(), lldb_private::OptionValueProperties::SetSubValue(), lldb_private::RegisterValue::SetValueFromData(), lldb_private::OptionValue::SetValueFromString(), lldb_private::OptionValueArch::SetValueFromString(), lldb_private::OptionValueBoolean::SetValueFromString(), lldb_private::OptionValueFileColonLine::SetValueFromString(), lldb_private::OptionValueFileSpecList::SetValueFromString(), lldb_private::OptionValuePathMappings::SetValueFromString(), lldb_private::OptionValueSInt64::SetValueFromString(), lldb_private::OptionValueUInt64::SetValueFromString(), lldb_private::OptionValueUUID::SetValueFromString(), lldb_private::RegisterValue::SetValueFromString(), lldb_private::platform_android::AdbClient::ShellToFile(), lldb_private::platform_android::AdbSyncService::StatImpl(), lldb::SBThread::StepOverUntil(), lldb_private::Process::StopForDestroyOrDetach(), lldb_private::OptionArgParser::ToFormat(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::Unlink(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::Unlink(), lldb_private::PlatformWindows::UnloadImage(), PlatformPOSIX::UnloadImage(), lldb_private::ValueObjectChild::UpdateValue(), lldb_private::ValueObjectVTable::UpdateValue(), ValueObjectVTableChild::UpdateValue(), ValidateNamedSummary(), ValidateSummaryString(), lldb_private::CommandInterpreter::VerifyUserMultiwordCmdPath(), lldb::SBValue::Watch(), lldb_private::FileCache::WriteFile(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::WriteFile(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteFile(), lldb_private::process_linux::NativeRegisterContextLinux::WriteRegisterRaw(), lldb_private::NativeRegisterContext::WriteRegisterValueToMemory(), lldb_private::RegisterContext::WriteRegisterValueToMemory(), and WriteString().
FromErrorStringWithFormatv()
template<typename... Args> Status static Status lldb_private::Status::FromErrorStringWithFormatv (const char * format, Args &&... args) inline static
Definition at line 151 of file Status.h.
References FromErrorStringWithFormatv(), and Status().
Referenced by lldb_private::CommandInterpreter::AddUserCommand(), lldb_private::Target::Attach(), CommandObjectScriptingObjectParsed::CommandObjectScriptingObjectParsed(), lldb_private::SharedSocket::CompleteSending(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ConfigureRemoteStructuredData(), lldb_private::TCPSocket::Connect(), lldb_private::platform_android::PlatformAndroidRemoteGDBServer::ConnectProcess(), lldb_private::Platform::ConnectRemote(), lldb_private::PlatformWindows::ConnectRemote(), PlatformPOSIX::ConnectRemote(), lldb::SBProcess::ContinueInDirection(), lldb_private::Breakpoint::CreateFromStructuredData(), lldb_private::BreakpointOptions::CommandData::CreateFromStructuredData(), lldb_private::BreakpointResolver::CreateFromStructuredData(), lldb_private::BreakpointResolverFileRegex::CreateFromStructuredData(), lldb_private::BreakpointResolverName::CreateFromStructuredData(), lldb_private::SearchFilter::CreateFromStructuredData(), lldb_private::OptionGroupPlatform::CreatePlatformWithOptions(), sddarwinlog_private::FilterRule::CreateRule(), lldb_private::PlatformWasm::DebugProcess(), lldb_private::NativeProcessWindows::Detach(), lldb_private::Process::DisableBreakpointSite(), lldb_private::Platform::DisconnectRemote(), lldb_private::PlatformWindows::DisconnectRemote(), PlatformPOSIX::DisconnectRemote(), lldb_private::Process::DoAllocateMemory(), lldb_private::Process::DoAttachToProcessWithID(), lldb_private::Process::DoDeallocateMemory(), lldb_private::Process::DoDetach(), lldb_private::ProcessWindows::DoDetach(), CommandObjectWatchpointCommandAdd::DoExecute(), lldb_private::Process::DoHalt(), lldb_private::Process::DoLaunch(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoLaunch(), lldb_private::minidump::ProcessMinidump::DoLoadCore(), lldb_private::Process::DoLoadCore(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoReadMemory(), lldb_private::Process::DoResume(), lldb_private::ProcessWindows::DoResume(), lldb_private::ScriptedProcess::DoResume(), ProcessKDP::DoResume(), lldb_private::Process::DoSignal(), lldb_private::Process::DoWriteMemory(), lldb_private::Process::DoWriteMemoryTags(), lldb_private::Process::EnableBreakpointSite(), lldb_private::UserExpression::Evaluate(), lldb_private::plugin::dwarf::DWARFUnit::ExtractUnitDIEIfNeeded(), lldb_private::CoreFileMemoryRanges::FinalizeCoreFileSaveRanges(), FromErrorStringWithFormatv(), lldb_private::RegisterValue::GetAsMemoryData(), lldb_private::ClangUserExpression::GetCppObjectPointer(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwoSymbolFileForCompileUnit(), lldb_private::Platform::GetFilePermissions(), lldb_private::SharedSocket::GetNativeSocket(), lldb_private::UserExpression::GetObjectPointer(), lldb_private::UserExpression::GetObjectPointerValueObject(), lldb_private::OptionValue::GetSubValue(), lldb_private::PlatformAppleSimulator::GetSymbolFile(), lldb_private::PlatformRemoteDarwinDevice::GetSymbolFile(), lldb_private::Variable::GetValuesForVariableExpressionPath(), HandleFileAction(), lldb_private::MonitoringProcessLauncher::LaunchProcess(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::LaunchProcess(), lldb_private::ProcessLauncherPosixFork::LaunchProcess(), lldb_private::StackFrame::LegacyGetValueForVariableExpressionPath(), lldb_private::ScriptInterpreterLua::LoadScriptingModule(), lldb_private::Platform::MakeDirectory(), lldb_private::UtilityFunction::MakeFunctionCaller(), lldb_private::ProcessDebugger::OnExitProcess(), lldb_private::StructuredData::ParseJSONFromFile(), CommandObjectScriptingObjectParsed::CommandOptions::ParseUsageMaskFromArray(), lldb_private::Platform::ReadFile(), lldb_private::Target::ReadMemory(), RecurseCopy_Callback(), lldb_private::Platform::ResolveExecutable(), lldb_private::ScriptedPythonInterface::ReverseTransform(), lldb_private::PluginManager::SaveCore(), lldb_private::Platform::SetFilePermissions(), CommandObjectScriptingObjectParsed::CommandOptions::SetOptionsFromArray(), CommandObjectLogEnable::CommandOptions::SetOptionValue(), CommandObjectScriptingExtensionList::CommandOptions::SetOptionValue(), CommandObjectScriptingObjectParsed::CommandOptions::SetOptionValue(), CommandObjectTargetModulesShowUnwind::CommandOptions::SetOptionValue(), lldb_private::CommandOptionsProcessAttach::SetOptionValue(), lldb_private::ctf::CommandObjectThreadTraceExportCTF::CommandOptions::SetOptionValue(), lldb_private::OptionGroupPlatform::SetOptionValue(), lldb_private::OptionGroupPythonClassWithDict::SetOptionValue(), lldb_private::Scalar::SetValueFromCString(), lldb_private::Scalar::SetValueFromData(), lldb_private::OptionValueChar::SetValueFromString(), lldb_private::RegisterValue::SetValueFromString(), lldb_private::BreakpointID::StringIsBreakpointName(), lldb_private::minidump::ProcessMinidump::WillResume(), lldb_private::ProcessTrace::WillResume(), ProcessElfCore::WillResume(), and lldb_private::Platform::WriteFile().
GetAsStructuredData()
StructuredData::ObjectSP Status::GetAsStructuredData () const
Get the error in machine-readable form.
Definition at line 255 of file Status.cpp.
References error(), GetAsStructuredData(), GetType(), and m_error.
Referenced by GetAsStructuredData().
GetError()
Status::ValueType Status::GetError () const
Access the error value.
If the internally stored llvm::Error is an llvm::ErrorList then this returns the error value of the first error.
Returns
The error value.
Definition at line 222 of file Status.cpp.
References error(), and m_error.
Referenced by lldb_private::process_linux::NativeProcessLinux::Attach(), and lldb_private::process_freebsd::NativeThreadFreeBSD::Resume().
GetType()
ErrorType Status::GetType () const
Access the error type.
If the internally stored llvm::Error is an llvm::ErrorList then this returns the error value of the first error.
Returns
The error type enumeration value.
Definition at line 279 of file Status.cpp.
References lldb::eErrorTypeInvalid, error(), ErrorCodeToErrorType(), and m_error.
Referenced by GetAsStructuredData().
operator=()
const Status & Status::operator= (Status && other)
Definition at line 99 of file Status.cpp.
References Clear(), m_error, and Status().
Success()
bool Status::Success () const
Test for success condition.
Returns true if the error code in this object is considered a successful return value.
Returns
true if this object contains an value that describes success (non-erro), false otherwise.
Definition at line 304 of file Status.cpp.
References Fail().
Referenced by lldb_private::ClangUserExpression::AddArguments(), lldb::SBCommandInterpreter::AddCommand(), lldb::SBCommandInterpreter::AddMultiwordCommand(), lldb_private::ClangExpressionDeclMap::AddValueToStruct(), lldb_private::NativeProcessWindows::AllocateMemory(), lldb_private::process_linux::NativeThreadLinux::AnnotateSyncTagCheckFault(), AsCString(), InterpreterStackFrame::AssignValue(), lldb_private::process_freebsd::NativeProcessFreeBSD::Manager::Attach(), lldb_private::process_netbsd::NativeProcessNetBSD::Manager::Attach(), lldb_private::Process::CanJIT(), lldb_private::NativeRegisterContextDBReg_x86::ClearHardwareWatchpoint(), lldb_private::PipeWindows::CreateNew(), EntityPersistentVariable::Dematerialize(), EntityRegister::Dematerialize(), EntityResultVariable::Dematerialize(), EntityVariableBase::Dematerialize(), EntityPersistentVariable::DestroyAllocation(), lldb_private::Target::DisableWatchpointByID(), lldb_private::IRExecutionUnit::DisassembleFunction(), lldb_private::CommandObjectDWIMPrint::DoExecute(), lldb_private::LLVMUserExpression::DoExecute(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoWriteMemory(), EntityPersistentVariable::DumpToLog(), EntityRegister::DumpToLog(), EntityResultVariable::DumpToLog(), EntitySymbol::DumpToLog(), EntityVariableBase::DumpToLog(), lldb_private::Target::EnableWatchpointByID(), InterpreterStackFrame::EvaluateValue(), lldb_private::LLVMUserExpression::FinalizeJITExecution(), lldb_private::IRMemoryMap::FindSpace(), lldb_private::process_gdb_remote::ProcessGDBRemote::FlashErase(), lldb_private::formatters::BlockPointerSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxSharedPtrSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::LibcxxUniquePtrSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlSmartPointerSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::MsvcStlUniquePtrSyntheticFrontEnd::GetChildAtIndex(), lldb_private::ClangUserExpression::GetCppObjectPointer(), lldb_private::DynamicLoaderWindowsDYLD::GetLoadAddress(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetMemoryRegionInfo(), lldb_private::UserExpression::GetObjectPointer(), lldb_private::Target::GetREPL(), lldb_private::IRExecutionUnit::GetRunnableInfo(), lldb_private::RegisterValue::GetScalarValue(), lldb_private::Value::GetValueByteSize(), GetXcodeSelectPath(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_QMemTags(), lldb_private::ClangUtilityFunction::Install(), IRInterpreter::Interpret(), IsInputPending(), lldb_private::StackFrame::LegacyGetValueForVariableExpressionPath(), lldb_private::ThreadPlanAssemblyTracer::Log(), EntityPersistentVariable::MakeAllocation(), InterpreterStackFrame::MakeArgument(), lldb_private::process_aix::NativeProcessAIX::Manager::Manager(), lldb_private::process_linux::NativeProcessLinux::Manager::Manager(), EntityPersistentVariable::Materialize(), EntityRegister::Materialize(), EntityResultVariable::Materialize(), EntitySymbol::Materialize(), EntityVariableBase::Materialize(), lldb_private::process_freebsd::NativeProcessFreeBSD::NativeProcessFreeBSD(), lldb_private::process_linux::NativeProcessLinux::NativeProcessLinux(), lldb_private::process_netbsd::NativeProcessNetBSD::NativeProcessNetBSD(), lldb_private::ConnectionFileDescriptor::OpenCommandPipe(), lldb_private::ClangExpressionParser::ParseInternal(), lldb_private::StopInfoBreakpoint::PerformAction(), lldb_private::ExpressionParser::PrepareForExecution(), lldb_private::ClangUserExpression::PrepareForParsing(), lldb_private::LLVMUserExpression::PrepareToExecuteJITExpression(), InterpreterStackFrame::PrintData(), lldb_private::NativeProcessProtocol::ReadCStringFromMemory(), lldb_private::Process::ReadMemory(), RegisterContextCorePOSIX_arm::ReadRegister(), RegisterContextMemory::ReadRegister(), InterpreterStackFrame::ResolveConstant(), lldb_private::process_freebsd::NativeProcessFreeBSD::Resume(), lldb_private::process_freebsd::NativeThreadFreeBSD::Resume(), lldb_private::process_netbsd::NativeProcessNetBSD::Resume(), lldb_private::process_netbsd::NativeThreadNetBSD::Resume(), lldb_private::process_linux::NativeProcessLinux::ResumeThread(), lldb_private::Thread::ReturnFromFrame(), lldb_private::Debugger::RunREPL(), lldb_private::Process::RunThreadPlan(), lldb::SBThread::RunToAddress(), SaveOffRegionsWithStackPointers(), lldb::SBValue::SetData(), lldb_private::ValueObject::SetData(), lldb_private::NativeProcessProtocol::SetHardwareBreakpoint(), CommandObjectBreakpointSet::CommandOptions::SetOptionValue(), CommandObjectSourceList::CommandOptions::SetOptionValue(), lldb_private::OptionValueProperties::SetPropertyAtIndexFromArgs(), lldb_private::NativeProcessProtocol::SetWatchpoint(), lldb_private::AppleThreadPlanStepThroughObjCTrampoline::ShouldStop(), lldb_private::process_freebsd::NativeThreadFreeBSD::SingleStep(), lldb_private::process_netbsd::NativeThreadNetBSD::SingleStep(), lldb::SBThread::StepInstruction(), lldb::SBThread::StepInto(), lldb::SBThread::StepOut(), lldb::SBThread::StepOutOfFrame(), lldb::SBThread::StepOverUntil(), lldb::SBThread::StepUsingScriptedThreadPlan(), CommandObjectProcessLaunchOrAttach::StopProcessIfNecessary(), lldb_private::process_freebsd::NativeThreadFreeBSD::Suspend(), lldb_private::process_netbsd::NativeThreadNetBSD::Suspend(), lldb_private::ClangUserExpression::TryParse(), lldb_private::ModuleListProperties::UpdateSymlinkMappings(), lldb_private::dil::Interpreter::Visit(), lldb_private::IRExecutionUnit::WriteData(), lldb_private::FunctionCaller::WriteFunctionWrapper(), and lldb_private::IRExecutionUnit::WriteNow().
takeError()
llvm::Error lldb_private::Status::takeError () inline
Definition at line 170 of file Status.h.
References m_error.
Referenced by lldb_private::process_aix::NativeProcessAIX::Detach(), lldb_private::SaveCoreOptions::GetCurrentSizeInBytes(), lldb_private::SaveCoreOptions::GetMemoryRegionsToSave(), lldb_private::PipeWindows::OpenAsWriter(), lldb_private::PipePosix::Read(), lldb_private::transport::IOTransport< Proto >::RegisterMessageHandler(), lldb_private::mcp::ProtocolServerMCP::Start(), and lldb_private::PipePosix::Write().
ToError()
llvm::Error Status::ToError () const
FIXME: Replace all uses with takeError() instead.
Definition at line 139 of file Status.cpp.
References CloneError(), and m_error.
Referenced by lldb_private::NativeProcessWindows::AllocateMemory(), lldb_private::process_freebsd::NativeProcessFreeBSD::Manager::Attach(), lldb_private::process_linux::NativeProcessLinux::Attach(), lldb_private::process_netbsd::NativeProcessNetBSD::Manager::Attach(), Clone(), ComputeSignalInfo(), lldb_private::NativeProcessWindows::DeallocateMemory(), lldb_private::process_linux::NativeRegisterContextLinux::DetermineArchitectureViaGPR(), lldb_private::process_aix::NativeProcessAIX::Manager::Launch(), lldb_private::process_freebsd::NativeProcessFreeBSD::Manager::Launch(), lldb_private::process_linux::NativeProcessLinux::Manager::Launch(), lldb_private::process_netbsd::NativeProcessNetBSD::Manager::Launch(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::LaunchProcess(), lldb_private::process_freebsd::NativeProcessFreeBSD::MonitorClone(), lldb_private::process_netbsd::NativeProcessNetBSD::MonitorClone(), lldb_private::NativeProcessWindows::NativeProcessWindows(), lldb_private::NativeProcessWindows::NativeProcessWindows(), ProcessElfCore::parseLinuxNotes(), lldb_private::NativeProcessProtocol::ReadCStringFromMemory(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceGetBinaryData(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceGetState(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceStart(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceStop(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceSupported(), and lldb_private::process_linux::NativeProcessLinux::Syscall().
Member Data Documentation
m_error
llvm::Error lldb_private::Status::m_error protected
Definition at line 237 of file Status.h.
Referenced by AsCString(), Clear(), Fail(), GetAsStructuredData(), GetError(), GetType(), operator=(), Status(), Status(), Status(), Status(), Status(), takeError(), ToError(), and ~Status().
m_string
std::string lldb_private::Status::m_string mutable protected
TODO: Replace this with just calling toString(m_error).
Definition at line 239 of file Status.h.
Referenced by AsCString().
The documentation for this class was generated from the following files:
Status.h
Status.cpp