LLDB: BreakpointNamesOptionGroup Class Reference
BreakpointNamesOptionGroup Class Reference
Public Member Functions
BreakpointNamesOptionGroup ()=default
~BreakpointNamesOptionGroup () override=default
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext *execution_context) override
void OptionParsingStarting (ExecutionContext *execution_context) override
const std::vector< std::string > & GetBreakpointNames ()
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Protected Attributes
std::vector< std::string > m_breakpoint_names
Detailed Description
Definition at line 241 of file CommandObjectBreakpoint.cpp.
Constructor & Destructor Documentation
BreakpointNamesOptionGroup()
BreakpointNamesOptionGroup::BreakpointNamesOptionGroup () default
~BreakpointNamesOptionGroup()
BreakpointNamesOptionGroup::~BreakpointNamesOptionGroup () override default
Member Function Documentation
GetBreakpointNames()
const std::vector< std::string > & BreakpointNamesOptionGroup::GetBreakpointNames () inline
Definition at line 274 of file CommandObjectBreakpoint.cpp.
References m_breakpoint_names.
GetDefinitions()
llvm::ArrayRef< OptionDefinition > BreakpointNamesOptionGroup::GetDefinitions () inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 247 of file CommandObjectBreakpoint.cpp.
Referenced by SetOptionValue().
OptionParsingStarting()
void BreakpointNamesOptionGroup::OptionParsingStarting (ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 270 of file CommandObjectBreakpoint.cpp.
References m_breakpoint_names.
SetOptionValue()
Status BreakpointNamesOptionGroup::SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 251 of file CommandObjectBreakpoint.cpp.
References lldb_private::CreateOptionParsingError(), error(), lldb_private::Status::FromError(), GetDefinitions(), m_breakpoint_names, and lldb_private::BreakpointID::StringIsBreakpointName().
Member Data Documentation
m_breakpoint_names
std::vector<std::string> BreakpointNamesOptionGroup::m_breakpoint_names protected
Definition at line 279 of file CommandObjectBreakpoint.cpp.
Referenced by GetBreakpointNames(), OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following file:
CommandObjectBreakpoint.cpp