LLDB: RegisterInfoPOSIX_ppc64le Class Reference
RegisterInfoPOSIX_ppc64le Class Reference
#include <RegisterInfoPOSIX_ppc64le.h>
Public Member Functions
RegisterInfoPOSIX_ppc64le (const lldb_private::ArchSpec &target_arch)
size_t GetGPRSize () const override
const lldb_private::RegisterInfo * GetRegisterInfo () const override
uint32_t GetRegisterCount () const override
Public Member Functions inherited from lldb_private::RegisterInfoInterface
RegisterInfoInterface (const lldb_private::ArchSpec &target_arch)
virtual ~RegisterInfoInterface ()=default
virtual uint32_t GetUserRegisterCount () const
const lldb_private::ArchSpec & GetTargetArchitecture () const
Private Attributes
const lldb_private::RegisterInfo * m_register_info_p
uint32_t m_register_info_count
Detailed Description
Definition at line 16 of file RegisterInfoPOSIX_ppc64le.h.
Constructor & Destructor Documentation
RegisterInfoPOSIX_ppc64le()
RegisterInfoPOSIX_ppc64le::RegisterInfoPOSIX_ppc64le (const lldb_private::ArchSpec & target_arch)
Definition at line 46 of file RegisterInfoPOSIX_ppc64le.cpp.
References GetRegisterInfoCount(), GetRegisterInfoPtr(), m_register_info_count, m_register_info_p, and lldb_private::RegisterInfoInterface::RegisterInfoInterface().
Member Function Documentation
GetGPRSize()
size_t RegisterInfoPOSIX_ppc64le::GetGPRSize () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 52 of file RegisterInfoPOSIX_ppc64le.cpp.
References GPR.
GetRegisterCount()
uint32_t RegisterInfoPOSIX_ppc64le::GetRegisterCount () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 61 of file RegisterInfoPOSIX_ppc64le.cpp.
References m_register_info_count.
GetRegisterInfo()
const lldb_private::RegisterInfo * RegisterInfoPOSIX_ppc64le::GetRegisterInfo () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 57 of file RegisterInfoPOSIX_ppc64le.cpp.
References m_register_info_p.
Member Data Documentation
m_register_info_count
uint32_t RegisterInfoPOSIX_ppc64le::m_register_info_count private
Definition at line 28 of file RegisterInfoPOSIX_ppc64le.h.
Referenced by GetRegisterCount(), and RegisterInfoPOSIX_ppc64le().
m_register_info_p
const lldb_private::RegisterInfo* RegisterInfoPOSIX_ppc64le::m_register_info_p private
Definition at line 27 of file RegisterInfoPOSIX_ppc64le.h.
Referenced by GetRegisterInfo(), and RegisterInfoPOSIX_ppc64le().
The documentation for this class was generated from the following files:
RegisterInfoPOSIX_ppc64le.h
RegisterInfoPOSIX_ppc64le.cpp