LLDB: lldb_private::IOObject Class Reference
lldb_private::IOObject Class Reference abstract
#include <IOObject.h>
Public Types
enum FDType { eFDTypeFile , eFDTypeSocket }
using WaitableHandle = lldb::file_t
Public Member Functions
IOObject (FDType type)
virtual ~IOObject ()
virtual Status Read (void *buf, size_t &num_bytes)=0
virtual Status Write (const void *buf, size_t &num_bytes)=0
virtual bool IsValid () const =0
virtual Status Close ()=0
FDType GetFdType () const
virtual WaitableHandle GetWaitableHandle ()=0
Static Public Attributes
static const WaitableHandle kInvalidHandleValue = -1
Protected Attributes
FDType m_fd_type
Private Member Functions
IOObject (const IOObject &)=delete
const IOObject & operator= (const IOObject &)=delete
Detailed Description
Definition at line 21 of file IOObject.h.
Member Typedef Documentation
WaitableHandle
using lldb_private::IOObject::WaitableHandle = lldb::file_t
Definition at line 29 of file IOObject.h.
Member Enumeration Documentation
FDType
enum lldb_private::IOObject::FDType
Enumerator
eFDTypeFile
eFDTypeSocket
Definition at line 23 of file IOObject.h.
Constructor & Destructor Documentation
IOObject() [1/2]
lldb_private::IOObject::IOObject (FDType type) inline
Definition at line 33 of file IOObject.h.
References m_fd_type.
Referenced by lldb_private::File::File(), IOObject(), operator=(), and lldb_private::Socket::Socket().
~IOObject()
IOObject::~IOObject () virtual default
IOObject() [2/2]
lldb_private::IOObject::IOObject (const IOObject &) private delete
References IOObject().
Member Function Documentation
Close()
virtual Status lldb_private::IOObject::Close () pure virtual
Implemented in lldb_private::File, lldb_private::NativeFile, lldb_private::SerialPort, and lldb_private::Socket.
GetFdType()
FDType lldb_private::IOObject::GetFdType () const inline
Definition at line 41 of file IOObject.h.
References m_fd_type.
GetWaitableHandle()
virtual WaitableHandle lldb_private::IOObject::GetWaitableHandle () pure virtual
Implemented in lldb_private::File, lldb_private::NativeFile, and lldb_private::Socket.
IsValid()
virtual bool lldb_private::IOObject::IsValid () const pure virtual
Implemented in lldb_private::File, lldb_private::NativeFile, lldb_private::SerialPort, lldb_private::Socket, and lldb_private::TCPSocket.
operator=()
const IOObject & lldb_private::IOObject::operator= (const IOObject &) private delete
References IOObject().
Read()
virtual Status lldb_private::IOObject::Read (void * buf, size_t & num_bytes) pure virtual
Implemented in lldb_private::File, lldb_private::NativeFile, and lldb_private::Socket.
Write()
virtual Status lldb_private::IOObject::Write (const void * buf, size_t & num_bytes) pure virtual
Implemented in lldb_private::File, lldb_private::NativeFile, and lldb_private::Socket.
Member Data Documentation
kInvalidHandleValue
const IOObject::WaitableHandle IOObject::kInvalidHandleValue = -1 static
Definition at line 31 of file IOObject.h.
Referenced by lldb_private::ConnectionFileDescriptor::BytesAvailable(), lldb_private::File::GetWaitableHandle(), and lldb_private::MainLoopWindows::RegisterReadObject().
m_fd_type
FDType lldb_private::IOObject::m_fd_type protected
Definition at line 46 of file IOObject.h.
Referenced by GetFdType(), and IOObject().
The documentation for this class was generated from the following files:
IOObject.h
IOObject.cpp