LLDB: lldb_private::ScriptInterpreterNone Class Reference
lldb_private::ScriptInterpreterNone Class Reference
#include <ScriptInterpreterNone.h>
Public Member Functions
ScriptInterpreterNone (Debugger &debugger)
~ScriptInterpreterNone () override
bool ExecuteOneLine (llvm::StringRef command, CommandReturnObject *result, const ExecuteScriptOptions &options=ExecuteScriptOptions()) override
void ExecuteInterpreterLoop () override
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::ScriptInterpreter
ScriptInterpreter (Debugger &debugger, lldb::ScriptLanguage script_lang)
virtual StructuredData::DictionarySP GetInterpreterInfo ()
~ScriptInterpreter () override=default
virtual bool Interrupt ()
virtual bool ExecuteOneLineWithReturn (llvm::StringRef in_string, ScriptReturnType return_type, void *ret_value, const ExecuteScriptOptions &options=ExecuteScriptOptions())
virtual Status ExecuteMultipleLines (const char *in_string, const ExecuteScriptOptions &options=ExecuteScriptOptions())
virtual Status ExportFunctionDefinitionToInterpreter (StringList &function_def)
virtual Status GenerateBreakpointCommandCallbackData (StringList &input, std::string &output, bool has_extra_args, bool is_callback)
virtual bool GenerateWatchpointCommandCallbackData (StringList &input, std::string &output, bool is_callback)
virtual bool GenerateTypeScriptFunction (const char *oneliner, std::string &output, const void *name_token=nullptr)
virtual bool GenerateTypeScriptFunction (StringList &input, std::string &output, const void *name_token=nullptr)
virtual bool GenerateScriptAliasFunction (StringList &input, std::string &output)
virtual bool GenerateTypeSynthClass (StringList &input, std::string &output, const void *name_token=nullptr)
virtual bool GenerateTypeSynthClass (const char *oneliner, std::string &output, const void *name_token=nullptr)
virtual StructuredData::ObjectSP CreateSyntheticScriptedProvider (const char *class_name, lldb::ValueObjectSP valobj)
virtual StructuredData::GenericSP CreateScriptCommandObject (const char *class_name)
virtual StructuredData::GenericSP CreateFrameRecognizer (const char *class_name)
virtual lldb::ValueObjectListSP GetRecognizedArguments (const StructuredData::ObjectSP &implementor, lldb::StackFrameSP frame_sp)
virtual bool ShouldHide (const StructuredData::ObjectSP &implementor, lldb::StackFrameSP frame_sp)
virtual StructuredData::ObjectSP LoadPluginModule (const FileSpec &file_spec, lldb_private::Status &error)
virtual StructuredData::DictionarySP GetDynamicSettings (StructuredData::ObjectSP plugin_module_sp, Target *target, const char *setting_name, lldb_private::Status &error)
virtual Status GenerateFunction (const char *signature, const StringList &input, bool is_callback)
virtual void CollectDataForBreakpointCommandCallback (std::vector< std::reference_wrapper< BreakpointOptions > > &options, CommandReturnObject &result)
virtual void CollectDataForWatchpointCommandCallback (WatchpointOptions *wp_options, CommandReturnObject &result)
Status SetBreakpointCommandCallback (std::vector< std::reference_wrapper< BreakpointOptions > > &bp_options_vec, const char *callback_text)
Set the specified text as the callback for the breakpoint.
virtual Status SetBreakpointCommandCallback (BreakpointOptions &bp_options, const char *callback_text, bool is_callback)
virtual Status SetBreakpointCommandCallback (BreakpointOptions &bp_options, std::unique_ptr< BreakpointOptions::CommandData > &data_up)
This one is for deserialization:
Status SetBreakpointCommandCallbackFunction (std::vector< std::reference_wrapper< BreakpointOptions > > &bp_options_vec, const char *function_name, StructuredData::ObjectSP extra_args_sp)
virtual Status SetBreakpointCommandCallbackFunction (BreakpointOptions &bp_options, const char *function_name, StructuredData::ObjectSP extra_args_sp)
Set a script function as the callback for the breakpoint.
virtual void SetWatchpointCommandCallback (WatchpointOptions *wp_options, const char *user_input, bool is_callback)
Set a one-liner as the callback for the watchpoint.
virtual bool GetScriptedSummary (const char *function_name, lldb::ValueObjectSP valobj, StructuredData::ObjectSP &callee_wrapper_sp, const TypeSummaryOptions &options, std::string &retval)
virtual bool FormatterCallbackFunction (const char *function_name, lldb::TypeImplSP type_impl_sp)
virtual void Clear ()
virtual size_t CalculateNumChildren (const StructuredData::ObjectSP &implementor, uint32_t max)
virtual lldb::ValueObjectSP GetChildAtIndex (const StructuredData::ObjectSP &implementor, uint32_t idx)
virtual llvm::Expected< uint32_t > GetIndexOfChildWithName (const StructuredData::ObjectSP &implementor, const char *child_name)
virtual bool UpdateSynthProviderInstance (const StructuredData::ObjectSP &implementor)
virtual bool MightHaveChildrenSynthProviderInstance (const StructuredData::ObjectSP &implementor)
virtual lldb::ValueObjectSP GetSyntheticValue (const StructuredData::ObjectSP &implementor)
virtual ConstString GetSyntheticTypeName (const StructuredData::ObjectSP &implementor)
virtual bool RunScriptBasedCommand (const char *impl_function, llvm::StringRef args, ScriptedCommandSynchronicity synchronicity, lldb_private::CommandReturnObject &cmd_retobj, Status &error, const lldb_private::ExecutionContext &exe_ctx)
virtual bool RunScriptBasedCommand (StructuredData::GenericSP impl_obj_sp, llvm::StringRef args, ScriptedCommandSynchronicity synchronicity, lldb_private::CommandReturnObject &cmd_retobj, Status &error, const lldb_private::ExecutionContext &exe_ctx)
virtual bool RunScriptBasedParsedCommand (StructuredData::GenericSP impl_obj_sp, Args &args, ScriptedCommandSynchronicity synchronicity, lldb_private::CommandReturnObject &cmd_retobj, Status &error, const lldb_private::ExecutionContext &exe_ctx)
virtual std::optional< std::string > GetRepeatCommandForScriptedCommand (StructuredData::GenericSP impl_obj_sp, Args &args)
virtual StructuredData::DictionarySP HandleArgumentCompletionForScriptedCommand (StructuredData::GenericSP impl_obj_sp, std::vector< llvm::StringRef > &args, size_t args_pos, size_t char_in_arg)
virtual StructuredData::DictionarySP HandleOptionArgumentCompletionForScriptedCommand (StructuredData::GenericSP impl_obj_sp, llvm::StringRef &long_name, size_t char_in_arg)
virtual bool RunScriptFormatKeyword (const char *impl_function, Process *process, std::string &output, Status &error)
virtual bool RunScriptFormatKeyword (const char *impl_function, Thread *thread, std::string &output, Status &error)
virtual bool RunScriptFormatKeyword (const char *impl_function, Target *target, std::string &output, Status &error)
virtual bool RunScriptFormatKeyword (const char *impl_function, StackFrame *frame, std::string &output, Status &error)
virtual bool RunScriptFormatKeyword (const char *impl_function, ValueObject *value, std::string &output, Status &error)
virtual bool GetDocumentationForItem (const char *item, std::string &dest)
virtual bool GetShortHelpForCommandObject (StructuredData::GenericSP cmd_obj_sp, std::string &dest)
virtual StructuredData::ObjectSP GetOptionsForCommandObject (StructuredData::GenericSP cmd_obj_sp)
virtual StructuredData::ObjectSP GetArgumentsForCommandObject (StructuredData::GenericSP cmd_obj_sp)
virtual bool SetOptionValueForCommandObject (StructuredData::GenericSP cmd_obj_sp, ExecutionContext *exe_ctx, llvm::StringRef long_option, llvm::StringRef value)
virtual void OptionParsingStartedForCommandObject (StructuredData::GenericSP cmd_obj_sp)
virtual uint32_t GetFlagsForCommandObject (StructuredData::GenericSP cmd_obj_sp)
virtual bool GetLongHelpForCommandObject (StructuredData::GenericSP cmd_obj_sp, std::string &dest)
virtual bool CheckObjectExists (const char *name)
virtual bool LoadScriptingModule (const char *filename, const LoadScriptOptions &options, lldb_private::Status &error, StructuredData::ObjectSP *module_sp=nullptr, FileSpec extra_search_dir={}, lldb::TargetSP loaded_into_target_sp={})
virtual bool IsReservedWord (const char *word)
virtual std::unique_ptr< ScriptInterpreterLocker > AcquireInterpreterLock ()
const char * GetScriptInterpreterPtyName ()
virtual llvm::Expected< unsigned > GetMaxPositionalArgumentsForCallable (const llvm::StringRef &callable_name)
lldb::ScriptLanguage GetLanguage ()
virtual lldb::ScriptedProcessInterfaceUP CreateScriptedProcessInterface ()
virtual lldb::ScriptedThreadInterfaceSP CreateScriptedThreadInterface ()
virtual lldb::ScriptedFrameInterfaceSP CreateScriptedFrameInterface ()
virtual lldb::ScriptedFrameProviderInterfaceSP CreateScriptedFrameProviderInterface ()
virtual lldb::ScriptedThreadPlanInterfaceSP CreateScriptedThreadPlanInterface ()
virtual lldb::OperatingSystemInterfaceSP CreateOperatingSystemInterface ()
virtual lldb::ScriptedPlatformInterfaceUP GetScriptedPlatformInterface ()
virtual lldb::ScriptedStopHookInterfaceSP CreateScriptedStopHookInterface ()
virtual lldb::ScriptedBreakpointInterfaceSP CreateScriptedBreakpointInterface ()
virtual StructuredData::ObjectSP CreateStructuredDataFromScriptObject (ScriptObject obj)
lldb::DataExtractorSP GetDataExtractorFromSBData (const lldb::SBData &data) const
Status GetStatusFromSBError (const lldb::SBError &error) const
Event * GetOpaqueTypeFromSBEvent (const lldb::SBEvent &event) const
lldb::StreamSP GetOpaqueTypeFromSBStream (const lldb::SBStream &stream) const
lldb::ThreadSP GetOpaqueTypeFromSBThread (const lldb::SBThread &exe_ctx) const
lldb::StackFrameSP GetOpaqueTypeFromSBFrame (const lldb::SBFrame &frame) const
SymbolContext GetOpaqueTypeFromSBSymbolContext (const lldb::SBSymbolContext &sym_ctx) const
lldb::BreakpointSP GetOpaqueTypeFromSBBreakpoint (const lldb::SBBreakpoint &breakpoint) const
lldb::BreakpointLocationSP GetOpaqueTypeFromSBBreakpointLocation (const lldb::SBBreakpointLocation &break_loc) const
lldb::ProcessAttachInfoSP GetOpaqueTypeFromSBAttachInfo (const lldb::SBAttachInfo &attach_info) const
lldb::ProcessLaunchInfoSP GetOpaqueTypeFromSBLaunchInfo (const lldb::SBLaunchInfo &launch_info) const
std::optional< MemoryRegionInfo > GetOpaqueTypeFromSBMemoryRegionInfo (const lldb::SBMemoryRegionInfo &mem_region) const
lldb::ExecutionContextRefSP GetOpaqueTypeFromSBExecutionContext (const lldb::SBExecutionContext &exe_ctx) const
lldb::StackFrameListSP GetOpaqueTypeFromSBFrameList (const lldb::SBFrameList &exe_ctx) const
lldb::ValueObjectSP GetOpaqueTypeFromSBValue (const lldb::SBValue &value) const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static lldb::ScriptInterpreterSP CreateInstance (Debugger &debugger)
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
Static Public Member Functions inherited from lldb_private::ScriptInterpreter
static std::string LanguageToString (lldb::ScriptLanguage language)
static lldb::ScriptLanguage StringToLanguage (const llvm::StringRef &string)
Additional Inherited Members
Public Types inherited from lldb_private::ScriptInterpreter
enum ScriptReturnType {
eScriptReturnTypeCharPtr , eScriptReturnTypeBool , eScriptReturnTypeShortInt , eScriptReturnTypeShortIntUnsigned ,
eScriptReturnTypeInt , eScriptReturnTypeIntUnsigned , eScriptReturnTypeLongInt , eScriptReturnTypeLongIntUnsigned ,
eScriptReturnTypeLongLong , eScriptReturnTypeLongLongUnsigned , eScriptReturnTypeFloat , eScriptReturnTypeDouble ,
eScriptReturnTypeChar , eScriptReturnTypeCharStrOrNone , eScriptReturnTypeOpaqueObject
}
Protected Attributes inherited from lldb_private::ScriptInterpreter
Debugger & m_debugger
lldb::ScriptLanguage m_script_lang
Detailed Description
Definition at line 16 of file ScriptInterpreterNone.h.
Constructor & Destructor Documentation
ScriptInterpreterNone()
ScriptInterpreterNone::ScriptInterpreterNone (Debugger & debugger)
Definition at line 24 of file ScriptInterpreterNone.cpp.
References lldb::eScriptLanguageNone, lldb_private::ScriptInterpreter::ScriptInterpreter(), and ScriptInterpreterNone().
Referenced by ScriptInterpreterNone().
~ScriptInterpreterNone()
ScriptInterpreterNone::~ScriptInterpreterNone () override default
Member Function Documentation
CreateInstance()
lldb::ScriptInterpreterSP ScriptInterpreterNone::CreateInstance (Debugger & debugger) static
Definition at line 57 of file ScriptInterpreterNone.cpp.
Referenced by Initialize().
ExecuteInterpreterLoop()
void ScriptInterpreterNone::ExecuteInterpreterLoop () override virtual
Implements lldb_private::ScriptInterpreter.
Definition at line 40 of file ScriptInterpreterNone.cpp.
References lldb_private::ScriptInterpreter::m_debugger, and no_interpreter_err_msg.
ExecuteOneLine()
bool ScriptInterpreterNone::ExecuteOneLine (llvm::StringRef command, CommandReturnObject * result, const ExecuteScriptOptions & options = ExecuteScriptOptions()) override virtual
Implements lldb_private::ScriptInterpreter.
Definition at line 33 of file ScriptInterpreterNone.cpp.
References lldb_private::ScriptInterpreter::m_debugger, and no_interpreter_err_msg.
GetPluginDescriptionStatic()
llvm::StringRef ScriptInterpreterNone::GetPluginDescriptionStatic () static
Definition at line 61 of file ScriptInterpreterNone.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef lldb_private::ScriptInterpreterNone::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 40 of file ScriptInterpreterNone.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::ScriptInterpreterNone::GetPluginNameStatic () inline static
Definition at line 35 of file ScriptInterpreterNone.h.
Referenced by GetPluginName(), and Initialize().
Initialize()
void ScriptInterpreterNone::Initialize () static
Definition at line 44 of file ScriptInterpreterNone.cpp.
References CreateInstance(), lldb::eScriptLanguageNone, GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Terminate()
void ScriptInterpreterNone::Terminate () static
Definition at line 54 of file ScriptInterpreterNone.cpp.
The documentation for this class was generated from the following files:
ScriptInterpreterNone.h
ScriptInterpreterNone.cpp