LLDB: lldb_private::ValueObjectRegisterSet Class Reference
lldb_private::ValueObjectRegisterSet Class Reference
#include <ValueObjectRegister.h>
Public Member Functions
~ValueObjectRegisterSet () override
llvm::Expected< uint64_t > GetByteSize () override
lldb::ValueType GetValueType () const override
ConstString GetTypeName () override
ConstString GetQualifiedTypeName () override
llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max) override
Should only be called by ValueObject::GetNumChildren().
lldb::ValueObjectSP GetChildMemberWithName (llvm::StringRef name, bool can_create=true) override
llvm::Expected< size_t > GetIndexOfChildWithName (llvm::StringRef name) override
Public Member Functions inherited from lldb_private::ValueObject
virtual ~ValueObject ()
const EvaluationPoint & GetUpdatePoint () const
EvaluationPoint & GetUpdatePoint ()
const ExecutionContextRef & GetExecutionContextRef () const
lldb::TargetSP GetTargetSP () const
lldb::ProcessSP GetProcessSP () const
lldb::ThreadSP GetThreadSP () const
lldb::StackFrameSP GetFrameSP () const
void SetNeedsUpdate ()
CompilerType GetCompilerType ()
virtual TypeImpl GetTypeImpl ()
virtual bool CanProvideValue ()
virtual ConstString GetDisplayTypeName ()
lldb::LanguageType GetObjectRuntimeLanguage ()
uint32_t GetTypeInfo (CompilerType *pointee_or_element_compiler_type=nullptr)
bool IsPointerType ()
bool IsArrayType ()
bool IsScalarType ()
bool IsPointerOrReferenceType ()
bool IsPossibleDynamicType ()
bool IsNilReference ()
bool IsUninitializedReference ()
virtual bool IsBaseClass ()
bool IsBaseClass (uint32_t &depth)
virtual bool IsDereferenceOfParent ()
bool IsIntegerType (bool &is_signed)
virtual void GetExpressionPath (Stream &s, GetExpressionPathFormat=eGetExpressionPathFormatDereferencePointers)
lldb::ValueObjectSP GetValueForExpressionPath (llvm::StringRef expression, ExpressionPathScanEndReason *reason_to_stop=nullptr, ExpressionPathEndResultType *final_value_type=nullptr, const GetValueForExpressionPathOptions &options=GetValueForExpressionPathOptions::DefaultOptions(), ExpressionPathAftermath *final_task_on_target=nullptr)
virtual bool IsInScope ()
virtual lldb::offset_t GetByteOffset ()
virtual uint32_t GetBitfieldBitSize ()
virtual uint32_t GetBitfieldBitOffset ()
bool IsBitfield ()
virtual const char * GetValueAsCString ()
virtual bool GetValueAsCString (const lldb_private::TypeFormatImpl &format, std::string &destination)
bool GetValueAsCString (lldb::Format format, std::string &destination)
virtual uint64_t GetValueAsUnsigned (uint64_t fail_value, bool *success=nullptr)
virtual int64_t GetValueAsSigned (int64_t fail_value, bool *success=nullptr)
llvm::Expected< llvm::APSInt > GetValueAsAPSInt ()
If the current ValueObject is of an appropriate type, convert the value to an APSInt and return that.
llvm::Expected< llvm::APFloat > GetValueAsAPFloat ()
If the current ValueObject is of an appropriate type, convert the value to an APFloat and return that.
llvm::Expected< bool > GetValueAsBool ()
If the current ValueObject is of an appropriate type, convert the value to a boolean and return that.
void SetValueFromInteger (const llvm::APInt &value, Status &error)
Update an existing integer ValueObject with a new integer value.
void SetValueFromInteger (lldb::ValueObjectSP new_val_sp, Status &error)
Update an existing integer ValueObject with an integer value created frome 'new_val_sp'.
virtual bool SetValueFromCString (const char *value_str, Status &error)
virtual lldb::ModuleSP GetModule ()
Return the module associated with this value object in case the value is from an executable file and might have its data in sections of the file.
ValueObject * GetRoot ()
ValueObject * FollowParentChain (std::function< bool(ValueObject *)>)
Given a ValueObject, loop over itself and its parent, and its parent's parent, .
virtual bool GetDeclaration (Declaration &decl)
const Status & GetError ()
ConstString GetName () const
lldb::user_id_t GetID () const
Returns a unique id for this ValueObject.
virtual lldb::ValueObjectSP GetChildAtIndex (uint32_t idx, bool can_create=true)
lldb::ValueObjectSP GetChildAtNamePath (llvm::ArrayRef< llvm::StringRef > names)
llvm::Expected< uint32_t > GetNumChildren (uint32_t max=UINT32_MAX)
uint32_t GetNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
Like GetNumChildren but returns 0 on error.
bool HasChildren ()
const Value & GetValue () const
Value & GetValue ()
virtual bool ResolveValue (Scalar &scalar)
virtual bool IsLogicalTrue (Status &error)
virtual const char * GetLocationAsCString ()
const char * GetSummaryAsCString (lldb::LanguageType lang=lldb::eLanguageTypeUnknown)
bool GetSummaryAsCString (TypeSummaryImpl *summary_ptr, std::string &destination, lldb::LanguageType lang=lldb::eLanguageTypeUnknown)
bool GetSummaryAsCString (std::string &destination, const TypeSummaryOptions &options)
bool GetSummaryAsCString (TypeSummaryImpl *summary_ptr, std::string &destination, const TypeSummaryOptions &options)
llvm::Expected< std::string > GetObjectDescription ()
bool HasSpecialPrintableRepresentation (ValueObjectRepresentationStyle val_obj_display, lldb::Format custom_format)
bool DumpPrintableRepresentation (Stream &s, ValueObjectRepresentationStyle val_obj_display=eValueObjectRepresentationStyleSummary, lldb::Format custom_format=lldb::eFormatInvalid, PrintableRepresentationSpecialCases special=PrintableRepresentationSpecialCases::eAllow, bool do_dump_error=true)
bool GetValueIsValid () const
bool GetValueDidChange ()
bool UpdateValueIfNeeded (bool update_format=true)
bool UpdateFormatsIfNeeded ()
lldb::ValueObjectSP GetSP ()
void SetName (ConstString name)
Change the name of the current ValueObject.
virtual AddrAndType GetAddressOf (bool scalar_is_load_address=true)
AddrAndType GetPointerValue ()
lldb::ValueObjectSP GetSyntheticChild (ConstString key) const
lldb::ValueObjectSP GetSyntheticArrayMember (size_t index, bool can_create)
lldb::ValueObjectSP GetSyntheticBitFieldChild (uint32_t from, uint32_t to, bool can_create)
lldb::ValueObjectSP GetSyntheticExpressionPathChild (const char *expression, bool can_create)
virtual lldb::ValueObjectSP GetSyntheticChildAtOffset (uint32_t offset, const CompilerType &type, bool can_create, ConstString name_const_str=ConstString())
virtual lldb::ValueObjectSP GetSyntheticBase (uint32_t offset, const CompilerType &type, bool can_create, ConstString name_const_str=ConstString())
virtual lldb::ValueObjectSP GetDynamicValue (lldb::DynamicValueType valueType)
lldb::DynamicValueType GetDynamicValueType ()
virtual lldb::ValueObjectSP GetStaticValue ()
virtual lldb::ValueObjectSP GetNonSyntheticValue ()
lldb::ValueObjectSP GetSyntheticValue ()
virtual bool HasSyntheticValue ()
virtual bool IsSynthetic ()
lldb::ValueObjectSP GetQualifiedRepresentationIfAvailable (lldb::DynamicValueType dynValue, bool synthValue)
virtual lldb::ValueObjectSP CreateConstantValue (ConstString name)
virtual lldb::ValueObjectSP Dereference (Status &error)
virtual lldb::ValueObjectSP Clone (ConstString new_name)
Creates a copy of the ValueObject with a new name and setting the current ValueObject as its parent.
virtual lldb::ValueObjectSP AddressOf (Status &error)
virtual lldb::addr_t GetLiveAddress ()
virtual void SetLiveAddress (lldb::addr_t addr=LLDB_INVALID_ADDRESS, AddressType address_type=eAddressTypeLoad)
lldb::ValueObjectSP Cast (const CompilerType &compiler_type)
virtual lldb::ValueObjectSP DoCast (const CompilerType &compiler_type)
virtual lldb::ValueObjectSP CastPointerType (const char *name, CompilerType &ast_type)
virtual lldb::ValueObjectSP CastPointerType (const char *name, lldb::TypeSP &type_sp)
lldb::addr_t GetLoadAddress ()
Return the target load address associated with this value object.
llvm::Expected< lldb::ValueObjectSP > CastDerivedToBaseType (CompilerType type, const llvm::ArrayRef< uint32_t > &base_type_indices)
Take a ValueObject whose type is an inherited class, and cast it to 'type', which should be one of its base classes.
llvm::Expected< lldb::ValueObjectSP > CastBaseToDerivedType (CompilerType type, uint64_t offset)
Take a ValueObject whose type is a base class, and cast it to 'type', which should be one of its derived classes.
lldb::ValueObjectSP CastToBasicType (CompilerType type)
lldb::ValueObjectSP CastToEnumType (CompilerType type)
lldb::ValueObjectSP GetVTable ()
If this object represents a C++ class with a vtable, return an object that represents the virtual function table.
void ValueUpdated ()
virtual bool IsDynamic ()
virtual bool DoesProvideSyntheticValue ()
virtual bool IsSyntheticChildrenGenerated ()
virtual void SetSyntheticChildrenGenerated (bool b)
virtual SymbolContextScope * GetSymbolContextScope ()
llvm::Error Dump (Stream &s)
llvm::Error Dump (Stream &s, const DumpValueObjectOptions &options)
lldb::ValueObjectSP Persist ()
bool IsCStringContainer (bool check_pointer=false)
Returns true if this is a char* or a char[] if it is a char* and check_pointer is true, it also checks that the pointer is valid.
std::pair< size_t, bool > ReadPointedString (lldb::WritableDataBufferSP &buffer_sp, Status &error, bool honor_array)
virtual size_t GetPointeeData (DataExtractor &data, uint32_t item_idx=0, uint32_t item_count=1)
virtual uint64_t GetData (DataExtractor &data, Status &error)
virtual bool SetData (DataExtractor &data, Status &error)
virtual bool GetIsConstant () const
bool NeedsUpdating ()
void SetIsConstant ()
lldb::Format GetFormat () const
virtual void SetFormat (lldb::Format format)
virtual lldb::LanguageType GetPreferredDisplayLanguage ()
void SetPreferredDisplayLanguage (lldb::LanguageType lt)
lldb::TypeSummaryImplSP GetSummaryFormat ()
void SetSummaryFormat (lldb::TypeSummaryImplSP format)
void SetDerefValobj (ValueObject *deref)
ValueObject * GetDerefValobj ()
void SetValueFormat (lldb::TypeFormatImplSP format)
lldb::TypeFormatImplSP GetValueFormat ()
void SetSyntheticChildren (const lldb::SyntheticChildrenSP &synth_sp)
lldb::SyntheticChildrenSP GetSyntheticChildren ()
virtual ValueObject * GetParent ()
virtual const ValueObject * GetParent () const
ValueObject * GetNonBaseClassParent ()
void SetAddressTypeOfChildren (AddressType at)
AddressType GetAddressTypeOfChildren ()
void SetHasCompleteType ()
virtual bool MightHaveChildren ()
Find out if a ValueObject might have children.
virtual lldb::VariableSP GetVariable ()
virtual bool IsRuntimeSupportValue ()
virtual uint64_t GetLanguageFlags ()
virtual void SetLanguageFlags (uint64_t flags)
llvm::ArrayRef< uint8_t > GetLocalBuffer () const
Returns the local buffer that this ValueObject points to if it's available.
Static Public Member Functions
static lldb::ValueObjectSP Create (ExecutionContextScope *exe_scope, lldb::RegisterContextSP &reg_ctx_sp, uint32_t set_idx)
Static Public Member Functions inherited from lldb_private::ValueObject
static lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
static lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx, const EvaluateExpressionOptions &options)
static lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
Given an address either create a value object containing the value at that address, or create a value object containing the address itself (pointer value), depending on whether the parameter 'do_deref' is true or false.
static lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
static lldb::ValueObjectSP CreateValueObjectFromAPInt (lldb::TargetSP target, const llvm::APInt &v, CompilerType type, llvm::StringRef name)
Create a value object containing the given APInt value.
static lldb::ValueObjectSP CreateValueObjectFromAPFloat (lldb::TargetSP target, const llvm::APFloat &v, CompilerType type, llvm::StringRef name)
Create a value object containing the given APFloat value.
static lldb::ValueObjectSP CreateValueObjectFromScalar (lldb::TargetSP target, Scalar &s, CompilerType type, llvm::StringRef name)
Create a value object containing the given Scalar value.
static lldb::ValueObjectSP CreateValueObjectFromBool (lldb::TargetSP target, bool value, llvm::StringRef name)
Create a value object containing the given boolean value.
static lldb::ValueObjectSP CreateValueObjectFromNullptr (lldb::TargetSP target, CompilerType type, llvm::StringRef name)
Create a nullptr value object with the specified type (must be a nullptr type).
Protected Member Functions
bool UpdateValue () override
CompilerType GetCompilerTypeImpl () override
Protected Member Functions inherited from lldb_private::ValueObject
ValueObject (ExecutionContextScope *exe_scope, ValueObjectManager &manager, AddressType child_ptr_or_ref_addr_type=eAddressTypeLoad)
Use this constructor to create a "root variable object".
ValueObject (ValueObject &parent)
Use this constructor to create a ValueObject owned by another ValueObject.
ValueObjectManager * GetManager ()
virtual LazyBool CanUpdateWithInvalidExecutionContext ()
virtual void CalculateDynamicValue (lldb::DynamicValueType use_dynamic)
virtual lldb::DynamicValueType GetDynamicValueTypeImpl ()
virtual bool HasDynamicValueTypeInfo ()
virtual void CalculateSyntheticValue ()
void SetNumChildren (uint32_t num_children)
void SetValueDidChange (bool value_changed)
void SetValueIsValid (bool valid)
void ClearUserVisibleData (uint32_t items=ValueObject::eClearUserVisibleDataItemsAllStrings)
void AddSyntheticChild (ConstString key, ValueObject *valobj)
DataExtractor & GetDataExtractor ()
void ClearDynamicTypeInformation ()
const char * GetLocationAsCStringImpl (const Value &value, const DataExtractor &data)
bool IsChecksumEmpty ()
void SetPreferredDisplayLanguageIfNeeded (lldb::LanguageType)
virtual void DoUpdateChildrenAddressType (ValueObject &valobj)
Protected Attributes
lldb::RegisterContextSP m_reg_ctx_sp
const RegisterSet * m_reg_set
uint32_t m_reg_set_idx
Protected Attributes inherited from lldb_private::ValueObject
ValueObject * m_parent = nullptr
The parent value object, or nullptr if this has no parent.
ValueObject * m_root = nullptr
The root of the hierarchy for this ValueObject (or nullptr if never calculated).
EvaluationPoint m_update_point
Stores both the stop id and the full context at which this value was last updated.
ConstString m_name
The name of this object.
DataExtractor m_data
A data extractor that can be used to extract the value.
Value m_value
Status m_error
An error object that can describe any errors that occur when updating values.
std::string m_value_str
Cached value string that will get cleared if/when the value is updated.
std::string m_old_value_str
Cached old value string from the last time the value was gotten.
std::string m_location_str
Cached location string that will get cleared if/when the value is updated.
std::string m_summary_str
Cached summary string that will get cleared if/when the value is updated.
std::string m_object_desc_str
Cached result of the "object printer".
CompilerType m_override_type
If the type of the value object should be overridden, the type to impose.
ValueObjectManager * m_manager = nullptr
This object is managed by the root object (any ValueObject that gets created without a parent.) The manager gets passed through all the generations of dependent objects, and will keep the whole cluster of objects alive as long as a shared pointer to any of them has been handed out.
ChildrenManager m_children
std::map< ConstString, ValueObject * > m_synthetic_children
ValueObject * m_dynamic_value = nullptr
ValueObject * m_synthetic_value = nullptr
ValueObject * m_deref_valobj = nullptr
lldb::ValueObjectSP m_addr_of_valobj_sp
We have to hold onto a shared pointer to this one because it is created as an independent ValueObjectConstResult, which isn't managed by us.
lldb::Format m_format = lldb::eFormatDefault
lldb::Format m_last_format = lldb::eFormatDefault
uint32_t m_last_format_mgr_revision = 0
lldb::TypeSummaryImplSP m_type_summary_sp
lldb::TypeFormatImplSP m_type_format_sp
lldb::SyntheticChildrenSP m_synthetic_children_sp
ProcessModID m_user_id_of_forced_summary
AddressType m_address_type_of_ptr_or_ref_children = eAddressTypeInvalid
llvm::SmallVector< uint8_t, 16 > m_value_checksum
lldb::LanguageType m_preferred_display_language = lldb::eLanguageTypeUnknown
uint64_t m_language_flags = 0
UserID m_id
Unique identifier for every value object.
struct lldb_private::ValueObject::Bitflags m_flags
Private Member Functions
ValueObjectRegisterSet (ExecutionContextScope *exe_scope, ValueObjectManager &manager, lldb::RegisterContextSP &reg_ctx_sp, uint32_t set_idx)
ValueObject * CreateChildAtIndex (size_t idx) override
Should only be called by ValueObject::GetChildAtIndex().
ValueObject * CreateSyntheticArrayMember (size_t idx) override
Should only be called by ValueObject::GetSyntheticArrayMember().
ValueObjectRegisterSet (const ValueObjectRegisterSet &)=delete
const ValueObjectRegisterSet & operator= (const ValueObjectRegisterSet &)=delete
Friends
class ValueObjectRegisterContext
Additional Inherited Members
Public Types inherited from lldb_private::ValueObject
enum GetExpressionPathFormat { eGetExpressionPathFormatDereferencePointers = 1 , eGetExpressionPathFormatHonorPointers }
enum ValueObjectRepresentationStyle {
eValueObjectRepresentationStyleValue = 1 , eValueObjectRepresentationStyleSummary , eValueObjectRepresentationStyleLanguageSpecific , eValueObjectRepresentationStyleLocation ,
eValueObjectRepresentationStyleChildrenCount , eValueObjectRepresentationStyleType , eValueObjectRepresentationStyleName , eValueObjectRepresentationStyleExpressionPath
}
enum ExpressionPathScanEndReason {
eExpressionPathScanEndReasonEndOfString = 1 , eExpressionPathScanEndReasonNoSuchChild , eExpressionPathScanEndReasonNoSuchSyntheticChild , eExpressionPathScanEndReasonEmptyRangeNotAllowed ,
eExpressionPathScanEndReasonDotInsteadOfArrow , eExpressionPathScanEndReasonArrowInsteadOfDot , eExpressionPathScanEndReasonFragileIVarNotAllowed , eExpressionPathScanEndReasonRangeOperatorNotAllowed ,
eExpressionPathScanEndReasonRangeOperatorInvalid , eExpressionPathScanEndReasonArrayRangeOperatorMet , eExpressionPathScanEndReasonBitfieldRangeOperatorMet , eExpressionPathScanEndReasonUnexpectedSymbol ,
eExpressionPathScanEndReasonTakingAddressFailed , eExpressionPathScanEndReasonDereferencingFailed , eExpressionPathScanEndReasonRangeOperatorExpanded , eExpressionPathScanEndReasonSyntheticValueMissing ,
eExpressionPathScanEndReasonUnknown = 0xFFFF
}
enum ExpressionPathEndResultType {
eExpressionPathEndResultTypePlain = 1 , eExpressionPathEndResultTypeBitfield , eExpressionPathEndResultTypeBoundedRange , eExpressionPathEndResultTypeUnboundedRange ,
eExpressionPathEndResultTypeValueObjectList , eExpressionPathEndResultTypeInvalid = 0xFFFF
}
enum ExpressionPathAftermath { eExpressionPathAftermathNothing = 1 , eExpressionPathAftermathDereference , eExpressionPathAftermathTakeAddress }
enum ClearUserVisibleDataItems {
eClearUserVisibleDataItemsNothing = 1u << 0 , eClearUserVisibleDataItemsValue = 1u << 1 , eClearUserVisibleDataItemsSummary = 1u << 2 , eClearUserVisibleDataItemsLocation = 1u << 3 ,
eClearUserVisibleDataItemsDescription = 1u << 4 , eClearUserVisibleDataItemsSyntheticChildren = 1u << 5 , eClearUserVisibleDataItemsAllStrings , eClearUserVisibleDataItemsAll = 0xFFFF
}
enum class PrintableRepresentationSpecialCases : bool { eDisable = false , eAllow = true }
Protected Types inherited from lldb_private::ValueObject
typedef ClusterManager< ValueObject > ValueObjectManager
Detailed Description
Definition at line 32 of file ValueObjectRegister.h.
Constructor & Destructor Documentation
~ValueObjectRegisterSet()
ValueObjectRegisterSet::~ValueObjectRegisterSet () override default
ValueObjectRegisterSet() [1/2]
ValueObjectRegisterSet::ValueObjectRegisterSet (ExecutionContextScope * exe_scope, ValueObjectManager & manager, lldb::RegisterContextSP & reg_ctx_sp, uint32_t set_idx) private
Definition at line 52 of file ValueObjectRegister.cpp.
References lldb_private::ValueObject::m_name, m_reg_ctx_sp, m_reg_set, m_reg_set_idx, and lldb_private::ValueObject::ValueObject().
Referenced by Create(), operator=(), and ValueObjectRegisterSet().
ValueObjectRegisterSet() [2/2]
lldb_private::ValueObjectRegisterSet::ValueObjectRegisterSet (const ValueObjectRegisterSet &) private delete
References ValueObjectRegisterSet().
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > ValueObjectRegisterSet::CalculateNumChildren (uint32_t max) override virtual
Should only be called by ValueObject::GetNumChildren().
Implements lldb_private::ValueObject.
Definition at line 78 of file ValueObjectRegister.cpp.
References m_reg_ctx_sp, m_reg_set_idx, and lldb_private::RegisterSet::num_registers.
Create()
ValueObjectSP ValueObjectRegisterSet::Create (ExecutionContextScope * exe_scope, lldb::RegisterContextSP & reg_ctx_sp, uint32_t set_idx) static
Definition at line 43 of file ValueObjectRegister.cpp.
References lldb_private::ClusterManager< ValueObject >::Create(), and ValueObjectRegisterSet().
Referenced by lldb::SBFrame::FindValue(), and lldb::SBFrame::GetRegisters().
CreateChildAtIndex()
ValueObject * ValueObjectRegisterSet::CreateChildAtIndex (size_t idx) override private virtual
Should only be called by ValueObject::GetChildAtIndex().
Returns
A ValueObject managed by this ValueObject's manager.
Reimplemented from lldb_private::ValueObject.
Definition at line 118 of file ValueObjectRegister.cpp.
References m_reg_ctx_sp, m_reg_set, and lldb_private::ValueObject::ValueObject().
CreateSyntheticArrayMember()
ValueObject * lldb_private::ValueObjectRegisterSet::CreateSyntheticArrayMember (size_t idx) inline override private virtual
Should only be called by ValueObject::GetSyntheticArrayMember().
Returns
A ValueObject managed by this ValueObject's manager.
Reimplemented from lldb_private::ValueObject.
Definition at line 74 of file ValueObjectRegister.h.
References lldb_private::ValueObject::ValueObject().
GetByteSize()
llvm::Expected< uint64_t > ValueObjectRegisterSet::GetByteSize () override virtual
Implements lldb_private::ValueObject.
Definition at line 87 of file ValueObjectRegister.cpp.
GetChildMemberWithName()
lldb::ValueObjectSP ValueObjectRegisterSet::GetChildMemberWithName (llvm::StringRef name, bool can_create = true) override virtual
Reimplemented from lldb_private::ValueObject.
Definition at line 128 of file ValueObjectRegister.cpp.
References lldb_private::ValueObject::GetSP(), m_reg_ctx_sp, m_reg_set, and lldb_private::ValueObject::ValueObject().
GetCompilerTypeImpl()
CompilerType ValueObjectRegisterSet::GetCompilerTypeImpl () override protected virtual
Implements lldb_private::ValueObject.
Definition at line 67 of file ValueObjectRegister.cpp.
GetIndexOfChildWithName()
llvm::Expected< size_t > ValueObjectRegisterSet::GetIndexOfChildWithName (llvm::StringRef name) override virtual
Reimplemented from lldb_private::ValueObject.
Definition at line 143 of file ValueObjectRegister.cpp.
References lldb::eRegisterKindLLDB, lldb_private::RegisterInfo::kinds, m_reg_ctx_sp, and m_reg_set.
GetQualifiedTypeName()
ConstString ValueObjectRegisterSet::GetQualifiedTypeName () override virtual
Reimplemented from lldb_private::ValueObject.
Definition at line 73 of file ValueObjectRegister.cpp.
GetTypeName()
ConstString ValueObjectRegisterSet::GetTypeName () override virtual
Reimplemented from lldb_private::ValueObject.
Definition at line 71 of file ValueObjectRegister.cpp.
GetValueType()
lldb::ValueType lldb_private::ValueObjectRegisterSet::GetValueType () const inline override virtual
Implements lldb_private::ValueObject.
Definition at line 42 of file ValueObjectRegister.h.
References lldb::eValueTypeRegisterSet.
operator=()
const ValueObjectRegisterSet & lldb_private::ValueObjectRegisterSet::operator= (const ValueObjectRegisterSet &) private delete
References ValueObjectRegisterSet().
UpdateValue()
bool ValueObjectRegisterSet::UpdateValue () override protected virtual
Implements lldb_private::ValueObject.
Definition at line 89 of file ValueObjectRegister.cpp.
References lldb_private::Status::FromErrorString(), lldb_private::ValueObject::GetExecutionContextRef(), lldb_private::ExecutionContext::GetFramePtr(), lldb_private::StackFrame::GetRegisterContext(), lldb_private::ValueObject::m_children, lldb_private::ValueObject::m_error, lldb_private::ValueObject::m_name, m_reg_ctx_sp, m_reg_set, m_reg_set_idx, lldb_private::RegisterSet::name, lldb_private::ValueObject::SetValueDidChange(), and lldb_private::ValueObject::SetValueIsValid().
Friends And Related Symbol Documentation
ValueObjectRegisterContext
friend class ValueObjectRegisterContext friend
Definition at line 67 of file ValueObjectRegister.h.
References lldb_private::ValueObject::ValueObject(), and ValueObjectRegisterContext.
Referenced by ValueObjectRegisterContext.
Member Data Documentation
m_reg_ctx_sp
lldb::RegisterContextSP lldb_private::ValueObjectRegisterSet::m_reg_ctx_sp protected
Definition at line 62 of file ValueObjectRegister.h.
Referenced by CalculateNumChildren(), CreateChildAtIndex(), GetChildMemberWithName(), GetIndexOfChildWithName(), UpdateValue(), and ValueObjectRegisterSet().
m_reg_set
const RegisterSet* lldb_private::ValueObjectRegisterSet::m_reg_set protected
Definition at line 63 of file ValueObjectRegister.h.
Referenced by CreateChildAtIndex(), GetChildMemberWithName(), GetIndexOfChildWithName(), UpdateValue(), and ValueObjectRegisterSet().
m_reg_set_idx
uint32_t lldb_private::ValueObjectRegisterSet::m_reg_set_idx protected
Definition at line 64 of file ValueObjectRegister.h.
Referenced by CalculateNumChildren(), UpdateValue(), and ValueObjectRegisterSet().
The documentation for this class was generated from the following files:
ValueObjectRegister.h
ValueObjectRegister.cpp