LLDB: lldb_private::process_netbsd::NativeProcessNetBSD::Manager Class Reference
lldb_private::process_netbsd::NativeProcessNetBSD::Manager Class Reference
#include <NativeProcessNetBSD.h>
Public Member Functions
llvm::Expected< std::unique_ptr< NativeProcessProtocol > > Launch (ProcessLaunchInfo &launch_info, NativeDelegate &native_delegate) override
Launch a process for debugging.
llvm::Expected< std::unique_ptr< NativeProcessProtocol > > Attach (lldb::pid_t pid, NativeDelegate &native_delegate) override
Attach to an existing process.
Extension GetSupportedExtensions () const override
Get the bitmask of extensions supported by this process plugin.
Manager (MainLoop &mainloop)
Manager (const Manager &)=delete
Public Member Functions inherited from lldb_private::NativeProcessProtocol::Manager
Manager (MainLoop &mainloop)
Manager (const Manager &)=delete
Manager & operator= (const Manager &)=delete
virtual ~Manager ()
Additional Inherited Members
Protected Attributes inherited from lldb_private::NativeProcessProtocol::Manager
MainLoop & m_mainloop
Detailed Description
Definition at line 30 of file NativeProcessNetBSD.h.
Constructor & Destructor Documentation
Manager() [1/2]
lldb_private::NativeProcessProtocol::Manager::Manager (MainLoop & mainloop) inline
Definition at line 273 of file NativeProcessProtocol.h.
Manager() [2/2]
lldb_private::NativeProcessProtocol::Manager::Manager (const Manager &) delete
Member Function Documentation
Attach()
llvm::Expected< std::unique_ptr< NativeProcessProtocol > > NativeProcessNetBSD::Manager::Attach (lldb::pid_t pid, NativeDelegate & native_delegate) override virtual
Attach to an existing process.
Parameters
[in] pid pid of the process locatable
[in] native_delegate The delegate that will receive messages regarding the inferior. Must outlive the NativeProcessProtocol instance.
[in] mainloop The mainloop instance with which the process can register callbacks. Must outlive the NativeProcessProtocol instance.
Returns
A NativeProcessProtocol shared pointer if the operation succeeded or an error object if it failed.
Implements lldb_private::NativeProcessProtocol::Manager.
Definition at line 112 of file NativeProcessNetBSD.cpp.
References lldb_private::GetLog(), lldb_private::Host::GetProcessInfo(), LLDB_LOG, lldb_private::NativeProcessProtocol::Manager::m_mainloop, lldb_private::process_netbsd::NativeProcessNetBSD::NativeProcessNetBSD(), lldb_private::Process, lldb_private::Status::Success(), and lldb_private::Status::ToError().
GetSupportedExtensions()
NativeProcessNetBSD::Extension NativeProcessNetBSD::Manager::GetSupportedExtensions () const override virtual
Get the bitmask of extensions supported by this process plugin.
Returns
A NativeProcessProtocol::Extension bitmask.
Reimplemented from lldb_private::NativeProcessProtocol::Manager.
Definition at line 135 of file NativeProcessNetBSD.cpp.
References lldb_private::NativeProcessProtocol::auxv, lldb_private::NativeProcessProtocol::fork, lldb_private::NativeProcessProtocol::libraries_svr4, lldb_private::NativeProcessProtocol::multiprocess, lldb_private::NativeProcessProtocol::pass_signals, lldb_private::NativeProcessProtocol::savecore, and lldb_private::NativeProcessProtocol::vfork.
Launch()
llvm::Expected< std::unique_ptr< NativeProcessProtocol > > NativeProcessNetBSD::Manager::Launch (ProcessLaunchInfo & launch_info, NativeDelegate & native_delegate) override virtual
Launch a process for debugging.
Parameters
[in] launch_info Information required to launch the process.
[in] native_delegate The delegate that will receive messages regarding the inferior. Must outlive the NativeProcessProtocol instance.
[in] mainloop The mainloop instance with which the process can register callbacks. Must outlive the NativeProcessProtocol instance.
Returns
A NativeProcessProtocol shared pointer if the operation succeeded or an error object if it failed.
Implements lldb_private::NativeProcessProtocol::Manager.
Definition at line 59 of file NativeProcessNetBSD.cpp.
References lldb_private::WaitStatus::Decode(), lldb::eStateStopped, lldb_private::Status::Fail(), lldb_private::GetLog(), lldb_private::HostProcess::GetProcessId(), lldb_private::Host::GetProcessInfo(), lldb_private::ProcessLaunchInfo::GetPTY(), lldb_private::ProcessLauncherPosixFork::LaunchProcess(), LLDB_LOG, lldb_private::NativeProcessProtocol::Manager::m_mainloop, lldb_private::process_netbsd::NativeProcessNetBSD::NativeProcessNetBSD(), lldb_private::Process, lldb_private::PseudoTerminal::ReleasePrimaryFileDescriptor(), lldb_private::process_netbsd::NativeThreadNetBSD::SetStoppedBySignal(), SIGSTOP, and lldb_private::Status::ToError().
The documentation for this class was generated from the following files:
NativeProcessNetBSD.h
NativeProcessNetBSD.cpp