LLDB: lldb_private::LockFileWindows Class Reference
lldb_private::LockFileWindows Class Reference
#include <LockFileWindows.h>
Public Member Functions
LockFileWindows (int fd)
~LockFileWindows ()
Public Member Functions inherited from lldb_private::LockFileBase
virtual ~LockFileBase ()=default
bool IsLocked () const
Status WriteLock (const uint64_t start, const uint64_t len)
Status TryWriteLock (const uint64_t start, const uint64_t len)
Status ReadLock (const uint64_t start, const uint64_t len)
Status TryReadLock (const uint64_t start, const uint64_t len)
Status Unlock ()
Protected Member Functions
Status DoWriteLock (const uint64_t start, const uint64_t len) override
Status DoTryWriteLock (const uint64_t start, const uint64_t len) override
Status DoReadLock (const uint64_t start, const uint64_t len) override
Status DoTryReadLock (const uint64_t start, const uint64_t len) override
Status DoUnlock () override
bool IsValidFile () const override
Protected Member Functions inherited from lldb_private::LockFileBase
LockFileBase (int fd)
Status DoLock (const Locker &locker, const uint64_t start, const uint64_t len)
Private Attributes
HANDLE m_file
Additional Inherited Members
Protected Types inherited from lldb_private::LockFileBase
using Locker = std::function<Status(const uint64_t, const uint64_t)>
Protected Attributes inherited from lldb_private::LockFileBase
int m_fd
bool m_locked
uint64_t m_start
uint64_t m_len
Detailed Description
Definition at line 17 of file LockFileWindows.h.
Constructor & Destructor Documentation
LockFileWindows()
LockFileWindows::LockFileWindows (int fd) explicit
Definition at line 35 of file LockFileWindows.cpp.
References lldb_private::LockFileBase::LockFileBase(), and m_file.
~LockFileWindows()
LockFileWindows::~LockFileWindows ()
Definition at line 38 of file LockFileWindows.cpp.
References lldb_private::LockFileBase::Unlock().
Member Function Documentation
DoReadLock()
Status LockFileWindows::DoReadLock (const uint64_t start, const uint64_t len) override protected virtual
Implements lldb_private::LockFileBase.
Definition at line 54 of file LockFileWindows.cpp.
References fileLock(), and m_file.
DoTryReadLock()
Status LockFileWindows::DoTryReadLock (const uint64_t start, const uint64_t len) override protected virtual
Implements lldb_private::LockFileBase.
Definition at line 58 of file LockFileWindows.cpp.
References fileLock(), and m_file.
DoTryWriteLock()
Status LockFileWindows::DoTryWriteLock (const uint64_t start, const uint64_t len) override protected virtual
Implements lldb_private::LockFileBase.
Definition at line 48 of file LockFileWindows.cpp.
References fileLock(), and m_file.
DoUnlock()
Status LockFileWindows::DoUnlock () override protected virtual
Implements lldb_private::LockFileBase.
Definition at line 63 of file LockFileWindows.cpp.
References lldb::eErrorTypeWin32, m_file, lldb_private::LockFileBase::m_len, and lldb_private::Status.
DoWriteLock()
Status LockFileWindows::DoWriteLock (const uint64_t start, const uint64_t len) override protected virtual
Implements lldb_private::LockFileBase.
Definition at line 44 of file LockFileWindows.cpp.
References fileLock(), and m_file.
IsValidFile()
bool LockFileWindows::IsValidFile () const override protected virtual
Reimplemented from lldb_private::LockFileBase.
Definition at line 40 of file LockFileWindows.cpp.
References lldb_private::LockFileBase::IsValidFile(), and m_file.
Member Data Documentation
m_file
HANDLE lldb_private::LockFileWindows::m_file private
Definition at line 36 of file LockFileWindows.h.
Referenced by DoReadLock(), DoTryReadLock(), DoTryWriteLock(), DoUnlock(), DoWriteLock(), IsValidFile(), and LockFileWindows().
The documentation for this class was generated from the following files:
LockFileWindows.h
LockFileWindows.cpp