LLDB: lldb_private::SingleStepBreakpointLocationsPredictor Class Reference
lldb_private::SingleStepBreakpointLocationsPredictor Class Reference
#include <EmulateInstruction.h>
Public Member Functions
SingleStepBreakpointLocationsPredictor (std::unique_ptr< EmulateInstruction > emulator_up)
virtual BreakpointLocations GetBreakpointLocations (Status &status)
virtual llvm::Expected< unsigned > GetBreakpointSize (lldb::addr_t bp_addr)
virtual ~SingleStepBreakpointLocationsPredictor ()=default
Protected Member Functions
lldb::addr_t GetNextInstructionAddress (Status &error)
lldb::addr_t GetBreakpointLocationAddress (lldb::addr_t entry_pc, Status &error)
Protected Attributes
std::unique_ptr< EmulateInstruction > m_emulator_up
bool m_emulation_result = false
Detailed Description
Definition at line 41 of file EmulateInstruction.h.
Constructor & Destructor Documentation
SingleStepBreakpointLocationsPredictor()
lldb_private::SingleStepBreakpointLocationsPredictor::SingleStepBreakpointLocationsPredictor (std::unique_ptr< EmulateInstruction > emulator_up) inline
Definition at line 43 of file EmulateInstruction.h.
References m_emulator_up.
Referenced by lldb_private::ARMSingleStepBreakpointLocationsPredictor::ARMSingleStepBreakpointLocationsPredictor(), and lldb_private::RISCVSingleStepBreakpointLocationsPredictor::RISCVSingleStepBreakpointLocationsPredictor().
~SingleStepBreakpointLocationsPredictor()
virtual lldb_private::SingleStepBreakpointLocationsPredictor::~SingleStepBreakpointLocationsPredictor () virtual default
References error().
Member Function Documentation
GetBreakpointLocationAddress()
lldb::addr_t SingleStepBreakpointLocationsPredictor::GetBreakpointLocationAddress (lldb::addr_t entry_pc, Status & error) protected
Definition at line 659 of file EmulateInstruction.cpp.
References error(), LLDB_INVALID_ADDRESS, m_emulation_result, m_emulator_up, pc, and lldb_private::Status.
Referenced by GetBreakpointLocations().
GetBreakpointLocations()
BreakpointLocations SingleStepBreakpointLocationsPredictor::GetBreakpointLocations (Status & status) virtual
Reimplemented in lldb_private::RISCVSingleStepBreakpointLocationsPredictor.
Definition at line 620 of file EmulateInstruction.cpp.
References GetBreakpointLocationAddress(), GetNextInstructionAddress(), m_emulation_result, m_emulator_up, and lldb_private::Status.
Referenced by lldb_private::RISCVSingleStepBreakpointLocationsPredictor::GetBreakpointLocations().
GetBreakpointSize()
virtual llvm::Expected< unsigned > lldb_private::SingleStepBreakpointLocationsPredictor::GetBreakpointSize (lldb::addr_t bp_addr) inline virtual
Reimplemented in lldb_private::ARMSingleStepBreakpointLocationsPredictor, and lldb_private::RISCVSingleStepBreakpointLocationsPredictor.
Definition at line 50 of file EmulateInstruction.h.
GetNextInstructionAddress()
lldb::addr_t SingleStepBreakpointLocationsPredictor::GetNextInstructionAddress (Status & error) protected
Definition at line 640 of file EmulateInstruction.cpp.
References error(), LLDB_INVALID_ADDRESS, m_emulator_up, pc, and lldb_private::Status.
Referenced by GetBreakpointLocations().
Member Data Documentation
m_emulation_result
bool lldb_private::SingleStepBreakpointLocationsPredictor::m_emulation_result = false protected
Definition at line 67 of file EmulateInstruction.h.
Referenced by GetBreakpointLocationAddress(), and GetBreakpointLocations().
m_emulator_up
std::unique_ptr<EmulateInstruction> lldb_private::SingleStepBreakpointLocationsPredictor::m_emulator_up protected
Definition at line 66 of file EmulateInstruction.h.
Referenced by GetBreakpointLocationAddress(), lldb_private::RISCVSingleStepBreakpointLocationsPredictor::GetBreakpointLocations(), GetBreakpointLocations(), lldb_private::ARMSingleStepBreakpointLocationsPredictor::GetBreakpointSize(), lldb_private::RISCVSingleStepBreakpointLocationsPredictor::GetBreakpointSize(), GetNextInstructionAddress(), lldb_private::RISCVSingleStepBreakpointLocationsPredictor::HandleAtomicSequence(), and SingleStepBreakpointLocationsPredictor().
The documentation for this class was generated from the following files:
EmulateInstruction.h
EmulateInstruction.cpp