LLDB: lldb_private::postfix::Node Class Reference
lldb_private::postfix::Node Class Reference
The base class for all nodes in the parsed postfix tree.
#include <PostfixExpression.h>
Public Types
enum Kind {
BinaryOp , InitialValue , Integer , Register ,
Symbol , UnaryOp
}
Public Member Functions
Kind GetKind () const
Protected Member Functions
Node (Kind kind)
Private Attributes
Kind m_kind
Detailed Description
The base class for all nodes in the parsed postfix tree.
Definition at line 29 of file PostfixExpression.h.
Member Enumeration Documentation
Kind
enum lldb_private::postfix::Node::Kind
Enumerator
BinaryOp
InitialValue
Integer
Register
Symbol
UnaryOp
Definition at line 31 of file PostfixExpression.h.
Constructor & Destructor Documentation
Node()
lldb_private::postfix::Node::Node (Kind kind) inline protected
Definition at line 41 of file PostfixExpression.h.
References m_kind.
Referenced by lldb_private::postfix::BinaryOpNode::BinaryOpNode(), lldb_private::postfix::BinaryOpNode::classof(), lldb_private::postfix::InitialValueNode::classof(), lldb_private::postfix::IntegerNode::classof(), lldb_private::postfix::RegisterNode::classof(), lldb_private::postfix::SymbolNode::classof(), lldb_private::postfix::UnaryOpNode::classof(), lldb_private::postfix::InitialValueNode::InitialValueNode(), lldb_private::postfix::IntegerNode::IntegerNode(), lldb_private::postfix::BinaryOpNode::Left(), lldb_private::postfix::BinaryOpNode::Left(), lldb_private::postfix::UnaryOpNode::Operand(), lldb_private::postfix::UnaryOpNode::Operand(), lldb_private::postfix::RegisterNode::RegisterNode(), lldb_private::postfix::BinaryOpNode::Right(), lldb_private::postfix::BinaryOpNode::Right(), lldb_private::postfix::SymbolNode::SymbolNode(), and lldb_private::postfix::UnaryOpNode::UnaryOpNode().
Member Function Documentation
GetKind()
Kind lldb_private::postfix::Node::GetKind () const inline
Definition at line 44 of file PostfixExpression.h.
References m_kind.
Referenced by lldb_private::postfix::BinaryOpNode::classof(), lldb_private::postfix::InitialValueNode::classof(), lldb_private::postfix::IntegerNode::classof(), lldb_private::postfix::RegisterNode::classof(), lldb_private::postfix::SymbolNode::classof(), lldb_private::postfix::UnaryOpNode::classof(), and lldb_private::postfix::Visitor< ResultT >::Dispatch().
Member Data Documentation
m_kind
Kind lldb_private::postfix::Node::m_kind private
Definition at line 47 of file PostfixExpression.h.
Referenced by GetKind(), and Node().
The documentation for this class was generated from the following file:
PostfixExpression.h