LLDB: lldb_private::NativeProcessProtocol::NativeDelegate Class Reference
lldb_private::NativeProcessProtocol::NativeDelegate Class Reference abstract
#include <NativeProcessProtocol.h>
Public Member Functions
virtual ~NativeDelegate ()=default
virtual void InitializeDelegate (NativeProcessProtocol *process)=0
virtual void ProcessStateChanged (NativeProcessProtocol *process, lldb::StateType state)=0
virtual void DidExec (NativeProcessProtocol *process)=0
virtual void NewSubprocess (NativeProcessProtocol *parent_process, std::unique_ptr< NativeProcessProtocol > child_process)=0
Detailed Description
Definition at line 233 of file NativeProcessProtocol.h.
Constructor & Destructor Documentation
~NativeDelegate()
virtual lldb_private::NativeProcessProtocol::NativeDelegate::~NativeDelegate () virtual default
Member Function Documentation
DidExec()
virtual void lldb_private::NativeProcessProtocol::NativeDelegate::DidExec (NativeProcessProtocol * process) pure virtual
Implemented in lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS.
References lldb_private::NativeProcessProtocol::NativeProcessProtocol().
InitializeDelegate()
virtual void lldb_private::NativeProcessProtocol::NativeDelegate::InitializeDelegate (NativeProcessProtocol * process) pure virtual
Implemented in lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS.
References lldb_private::NativeProcessProtocol::NativeProcessProtocol().
Referenced by lldb_private::NativeProcessProtocol::NativeProcessProtocol().
NewSubprocess()
virtual void lldb_private::NativeProcessProtocol::NativeDelegate::NewSubprocess (NativeProcessProtocol * parent_process, std::unique_ptr< NativeProcessProtocol > child_process) pure virtual
Implemented in lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS.
References lldb_private::NativeProcessProtocol::NativeProcessProtocol().
ProcessStateChanged()
virtual void lldb_private::NativeProcessProtocol::NativeDelegate::ProcessStateChanged (NativeProcessProtocol * process, lldb::StateType state) pure virtual
Implemented in lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS.
References lldb_private::NativeProcessProtocol::NativeProcessProtocol().
The documentation for this class was generated from the following file:
NativeProcessProtocol.h