LLDB: lldb_private::ModuleChild Class Reference
lldb_private::ModuleChild Class Reference
A mix in class that contains a pointer back to the module that owns the object which inherits from it.
#include "lldb/Core/ModuleChild.h"
Public Member Functions
ModuleChild (const lldb::ModuleSP &module_sp)
Construct with owning module.
~ModuleChild ()
Destructor.
const ModuleChild & operator= (const ModuleChild &rhs)
Assignment operator.
lldb::ModuleSP GetModule () const
Get const accessor for the module pointer.
void SetModule (const lldb::ModuleSP &module_sp)
Set accessor for the module pointer.
Protected Attributes
lldb::ModuleWP m_module_wp
The Module that owns the object that inherits from this class.
Detailed Description
A mix in class that contains a pointer back to the module that owns the object which inherits from it.
Definition at line 19 of file ModuleChild.h.
Constructor & Destructor Documentation
ModuleChild()
ModuleChild::ModuleChild (const lldb::ModuleSP & module_sp)
Construct with owning module.
Parameters
[in] module_sp The module that owns the object that inherits from this class.
Definition at line 13 of file ModuleChild.cpp.
References m_module_wp.
Referenced by lldb_private::CompileUnit::CompileUnit(), lldb_private::ObjectContainer::ObjectContainer(), lldb_private::ObjectFile::ObjectFile(), lldb_private::ObjectFile::ObjectFile(), operator=(), lldb_private::Section::Section(), lldb_private::Section::Section(), lldb_private::SymbolVendor::SymbolVendor(), and ~ModuleChild().
~ModuleChild()
ModuleChild::~ModuleChild () default
Destructor.
References ModuleChild().
Member Function Documentation
GetModule()
lldb::ModuleSP ModuleChild::GetModule () const
Get const accessor for the module pointer.
Returns
A const pointer to the module that owns the object that inherits from this class.
Definition at line 24 of file ModuleChild.cpp.
References m_module_wp.
Referenced by PDBASTParser::AddRecordBases(), PDBASTParser::AddRecordMembers(), PDBASTParser::AddRecordMethod(), lldb_private::SymbolVendor::AddSymbolFileRepresentation(), ObjectFileELF::ApplyRelocations(), lldb_private::CacheSignature::CacheSignature(), ObjectFileMachO::CalculateSectionLoadAddressForMemoryImage(), lldb_private::CompileUnit::CalculateSymbolContext(), lldb_private::CompileUnit::CalculateSymbolContextModule(), lldb_private::Function::CalculateSymbolContextModule(), lldb_private::ObjectFile::ClearSymtab(), lldb_private::plugin::dwarf::SymbolFileDWARF::CompleteType(), lldb_private::SearchFilterByModuleListAndCU::CompUnitPasses(), ObjectFilePECOFF::CreateBinary(), ObjectFileXCOFF::CreateBinary(), lldb_private::npdb::SymbolFileNativePDB::CreateBlock(), lldb_private::npdb::SymbolFileNativePDB::CreateConstantSymbol(), lldb_private::npdb::SymbolFileNativePDB::CreateFunction(), lldb_private::npdb::SymbolFileNativePDB::CreateGlobalVariable(), lldb_private::npdb::SymbolFileNativePDB::CreateLocalVariable(), lldb_private::breakpad::ObjectFileBreakpad::CreateSections(), lldb_private::ObjectFileJSON::CreateSections(), lldb_private::wasm::ObjectFileWasm::CreateSections(), ObjectFileCOFF::CreateSections(), ObjectFileELF::CreateSections(), ObjectFileMachO::CreateSections(), ObjectFilePECOFF::CreateSections(), ObjectFilePlaceholder::CreateSections(), ObjectFileXCOFF::CreateSectionsWithBitness(), lldb_private::plugin::dwarf::SymbolFileDWARF::DeclContextMatchesThisSymbolFile(), lldb_private::ObjectFileJIT::Dump(), lldb_private::wasm::ObjectFileWasm::Dump(), ObjectFileCOFF::Dump(), ObjectFileELF::Dump(), ObjectFileMachO::Dump(), ObjectFilePECOFF::Dump(), lldb_private::Section::DumpName(), lldb_private::CompileUnit::DumpSymbolContext(), lldb_private::plugin::dwarf::DWARFDebugInfoEntry::Extract(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindDefinitionDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindFunctions(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindFunctions(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindGlobalVariables(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindGlobalVariables(), ObjectFileMachO::FindLC_NOTEByName(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindNamespace(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindTypes(), lldb_private::CompileUnit::ForEachExternalModule(), ObjectFileMachO::GetAddressableBits(), ObjectFileMachO::GetArchitecture(), lldb_private::plugin::dwarf::ManualDWARFIndex::GetCacheKey(), ObjectFileMachO::GetCorefileMainBinaryInfo(), ObjectFileMachO::GetCorefileProcessMetadata(), ObjectFileMachO::GetCorefileThreadExtraInfos(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetDebugInfoModules(), lldb_private::CompileUnit::GetDebugMacros(), ObjectFileMachO::GetDependentModules(), lldb_private::plugin::dwarf::DWARFUnit::GetDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwoSymbolFileForCompileUnit(), ObjectFileMachO::GetEntryPointAddress(), lldb_private::Type::GetExeModule(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo::GetFileRangeMap(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetGlobalAranges(), ObjectFileELF::GetGnuDebugDataObjectFile(), ObjectFileMachO::GetIdentifierString(), lldb_private::CompileUnit::GetImportedModules(), lldb_private::CompileUnit::GetIsOptimized(), lldb_private::CompileUnit::GetLanguage(), lldb_private::CompileUnit::GetLineTable(), ObjectFileMachO::GetMachHeaderSection(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetModuleByCompUnitInfo(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetModuleMutex(), lldb_private::SymbolFile::GetModuleMutex(), ObjectFileMachO::GetNumThreadContexts(), lldb_private::ObjectContainerMachOFileset::GetObjectFile(), ObjectContainerBSDArchive::GetObjectFile(), ObjectContainerUniversalMachO::GetObjectFile(), lldb_private::ObjectFile::GetObjectName(), lldb_private::breakpad::SymbolFileBreakpad::GetOrCreateFunction(), GetPtrAuthMofidierPayload(), lldb_private::plugin::dwarf::DWARFUnit::GetRnglistData(), lldb_private::plugin::dwarf::DWARFUnit::GetRnglistTable(), lldb_private::ObjectFile::GetSectionList(), lldb_private::CompileUnit::GetSupportFiles(), lldb_private::ObjectFile::GetSymtab(), ObjectFileMachO::GetThreadContextAtIndex(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetTypeForDIE(), ObjectFileMachO::GetUUID(), ObjectFileMachO::GetVersion(), lldb_private::plugin::dwarf::SymbolFileDWARF::InitializeObject(), ObjectFileMachO::IsStripped(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::LinkOSOAddress(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseAndAppendGlobalVariable(), DWARFASTParserClang::ParseChildMembers(), ObjectFilePECOFF::ParseDependentModules(), lldb_private::SymbolFileCTF::ParseFunctions(), lldb_private::ObjectContainerMachOFileset::ParseHeader(), lldb_private::SymbolFileCTF::ParseHeader(), ObjectContainerBSDArchive::ParseHeader(), ObjectFileCOFF::ParseHeader(), ObjectFileMachO::ParseHeader(), ObjectFilePECOFF::ParseHeader(), lldb_private::npdb::SymbolFileNativePDB::ParseLineTable(), DWARFASTParserClang::ParseObjCProperty(), lldb_private::SymbolFileCTF::ParseObjects(), DWARFASTParserClang::ParseRustVariantPart(), DWARFASTParserClang::ParseSingleMember(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseSupportFiles(), ObjectFileELF::ParseSymbols(), lldb_private::ObjectFileJSON::ParseSymtab(), ObjectFileELF::ParseSymtab(), ObjectFileMachO::ParseSymtab(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE(), SymbolFilePDB::ParseVariableForPDBData(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseXcodeSDK(), lldb_private::IRExecutionUnit::PopulateSectionList(), PrepareContextToReceiveMembers(), ObjectFileMachO::ProcessSegmentCommand(), ObjectFileELF::ReadSectionData(), lldb_private::Section::ResolveContainedAddress(), SymbolFilePDB::ResolveFunction(), lldb_private::CompileUnit::ResolveSymbolContext(), lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveType(), lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveTypeUID(), ObjectFileMachO::SanitizeSegmentCommand(), ObjectFileMachO::SectionIsLoadable(), lldb_private::wasm::ObjectFileWasm::SetLoadAddress(), ObjectFileELF::SetLoadAddress(), ObjectFileMachO::SetLoadAddress(), ObjectFilePECOFF::SetLoadAddress(), ObjectFilePlaceholder::SetLoadAddress(), lldb_private::plugin::dwarf::DWARFUnit::SetLoclistsBase(), lldb_private::ObjectFile::SetModulesArchitecture(), and lldb_private::plugin::dwarf::SymbolFileDWARF::UpdateExternalModuleListIfNeeded().
operator=()
const ModuleChild & ModuleChild::operator= (const ModuleChild & rhs)
Assignment operator.
Parameters
[in] rhs A const ModuleChild class reference to copy.
Returns
A const reference to this object.
Definition at line 18 of file ModuleChild.cpp.
References m_module_wp, and ModuleChild().
SetModule()
void ModuleChild::SetModule (const lldb::ModuleSP & module_sp)
Set accessor for the module pointer.
Parameters
[in] module_sp A new module that owns the object that inherits from this class.
Definition at line 26 of file ModuleChild.cpp.
References m_module_wp.
Member Data Documentation
m_module_wp
lldb::ModuleWP lldb_private::ModuleChild::m_module_wp protected
The Module that owns the object that inherits from this class.
Definition at line 56 of file ModuleChild.h.
Referenced by GetModule(), ModuleChild(), operator=(), and SetModule().
The documentation for this class was generated from the following files:
ModuleChild.h
ModuleChild.cpp