LLDB: lldb_private::RISCVSingleStepBreakpointLocationsPredictor Class Reference
lldb_private::RISCVSingleStepBreakpointLocationsPredictor Class Reference
#include <EmulateInstructionRISCV.h>
Public Member Functions
RISCVSingleStepBreakpointLocationsPredictor (std::unique_ptr< EmulateInstruction > emulator)
BreakpointLocations GetBreakpointLocations (Status &status) override
llvm::Expected< unsigned > GetBreakpointSize (lldb::addr_t bp_addr) override
Public Member Functions inherited from lldb_private::SingleStepBreakpointLocationsPredictor
SingleStepBreakpointLocationsPredictor (std::unique_ptr< EmulateInstruction > emulator_up)
virtual ~SingleStepBreakpointLocationsPredictor ()=default
Private Member Functions
BreakpointLocations HandleAtomicSequence (lldb::addr_t pc, Status &error)
Static Private Member Functions
static bool FoundLoadReserve (const RISCVInst &inst)
static bool FoundStoreConditional (const RISCVInst &inst)
Static Private Attributes
static constexpr size_t s_max_atomic_sequence_length = 64
Additional Inherited Members
Protected Member Functions inherited from lldb_private::SingleStepBreakpointLocationsPredictor
lldb::addr_t GetNextInstructionAddress (Status &error)
lldb::addr_t GetBreakpointLocationAddress (lldb::addr_t entry_pc, Status &error)
Protected Attributes inherited from lldb_private::SingleStepBreakpointLocationsPredictor
std::unique_ptr< EmulateInstruction > m_emulator_up
bool m_emulation_result = false
Detailed Description
Definition at line 23 of file EmulateInstructionRISCV.h.
Constructor & Destructor Documentation
RISCVSingleStepBreakpointLocationsPredictor()
lldb_private::RISCVSingleStepBreakpointLocationsPredictor::RISCVSingleStepBreakpointLocationsPredictor (std::unique_ptr< EmulateInstruction > emulator) inline
Definition at line 26 of file EmulateInstructionRISCV.h.
References lldb_private::SingleStepBreakpointLocationsPredictor::SingleStepBreakpointLocationsPredictor().
Member Function Documentation
FoundLoadReserve()
bool lldb_private::RISCVSingleStepBreakpointLocationsPredictor::FoundLoadReserve (const RISCVInst & inst) inline static private
Definition at line 35 of file EmulateInstructionRISCV.h.
Referenced by GetBreakpointLocations().
FoundStoreConditional()
bool lldb_private::RISCVSingleStepBreakpointLocationsPredictor::FoundStoreConditional (const RISCVInst & inst) inline static private
Definition at line 40 of file EmulateInstructionRISCV.h.
Referenced by GetBreakpointLocations(), and HandleAtomicSequence().
GetBreakpointLocations()
BreakpointLocations lldb_private::RISCVSingleStepBreakpointLocationsPredictor::GetBreakpointLocations (Status & status) override virtual
Reimplemented from lldb_private::SingleStepBreakpointLocationsPredictor.
Definition at line 1955 of file EmulateInstructionRISCV.cpp.
References FoundLoadReserve(), FoundStoreConditional(), lldb_private::SingleStepBreakpointLocationsPredictor::GetBreakpointLocations(), lldb_private::GetLog(), HandleAtomicSequence(), LLDB_LOGF, lldb_private::SingleStepBreakpointLocationsPredictor::m_emulator_up, pc, lldb_private::EmulateInstructionRISCV::ReadInstructionAt(), lldb_private::EmulateInstruction::ReadPC(), lldb_private::Status, and lldb_private::Unwind.
GetBreakpointSize()
llvm::Expected< unsigned > lldb_private::RISCVSingleStepBreakpointLocationsPredictor::GetBreakpointSize (lldb::addr_t bp_addr) override virtual
Reimplemented from lldb_private::SingleStepBreakpointLocationsPredictor.
Definition at line 1992 of file EmulateInstructionRISCV.cpp.
References lldb_private::EmulateInstructionRISCV::GetLastInstrSize(), lldb_private::SingleStepBreakpointLocationsPredictor::m_emulator_up, and lldb_private::EmulateInstructionRISCV::ReadInstructionAt().
HandleAtomicSequence()
BreakpointLocations lldb_private::RISCVSingleStepBreakpointLocationsPredictor::HandleAtomicSequence (lldb::addr_t pc, Status & error) private
Definition at line 2010 of file EmulateInstructionRISCV.cpp.
References error(), FoundStoreConditional(), lldb_private::GetLog(), lldb_private::B::imm, LLDB_LOGF, lldb_private::SingleStepBreakpointLocationsPredictor::m_emulator_up, pc, lldb_private::EmulateInstructionRISCV::ReadInstructionAt(), s_max_atomic_sequence_length, lldb_private::SignExt(), lldb_private::Status, and lldb_private::Unwind.
Referenced by GetBreakpointLocations().
Member Data Documentation
s_max_atomic_sequence_length
size_t lldb_private::RISCVSingleStepBreakpointLocationsPredictor::s_max_atomic_sequence_length = 64 static constexpr private
Definition at line 47 of file EmulateInstructionRISCV.h.
Referenced by HandleAtomicSequence().
The documentation for this class was generated from the following files:
EmulateInstructionRISCV.h
EmulateInstructionRISCV.cpp