LLDB: lldb_private::BytecodeSummaryFormat Class Reference
lldb_private::BytecodeSummaryFormat Class Reference
A summary formatter that is defined in LLDB formmater bytecode.
#include <TypeSummary.h>
Public Member Functions
BytecodeSummaryFormat (const TypeSummaryImpl::Flags &flags, std::unique_ptr< llvm::MemoryBuffer > bytecode)
bool FormatObject (ValueObject *valobj, std::string &dest, const TypeSummaryOptions &options) override
std::string GetDescription () override
std::string GetName () override
Get the name of the Type Summary Provider, either a C++ class, a summary string, or a script function name.
Public Member Functions inherited from lldb_private::TypeSummaryImpl
virtual ~TypeSummaryImpl ()=default
Kind GetKind () const
bool Cascades () const
bool SkipsPointers () const
bool SkipsReferences () const
bool NonCacheable () const
virtual bool DoesPrintChildren (ValueObject *valobj) const
virtual bool DoesPrintEmptyAggregates () const
virtual bool DoesPrintValue (ValueObject *valobj) const
bool IsOneLiner () const
virtual bool HideNames (ValueObject *valobj) const
void SetCascades (bool value)
void SetSkipsPointers (bool value)
void SetSkipsReferences (bool value)
virtual void SetDoesPrintChildren (bool value)
virtual void SetDoesPrintValue (bool value)
void SetIsOneLiner (bool value)
virtual void SetHideNames (bool value)
virtual void SetNonCacheable (bool value)
uint32_t GetOptions ()
void SetOptions (uint32_t value)
uint32_t GetPtrMatchDepth ()
void SetPtrMatchDepth (uint32_t value)
virtual std::string GetSummaryKindName ()
Get the name of the kind of Summary Provider, either c++, summary string, script or python.
uint32_t & GetRevision ()
Static Public Member Functions
static bool classof (const TypeSummaryImpl *S)
Private Attributes
std::unique_ptr< llvm::MemoryBuffer > m_bytecode
Additional Inherited Members
Public Types inherited from lldb_private::TypeSummaryImpl
enum class Kind {
eSummaryString , eScript , eBytecode , eCallback ,
eInternal
}
typedef std::shared_ptr< TypeSummaryImpl > SharedPointer
Protected Member Functions inherited from lldb_private::TypeSummaryImpl
TypeSummaryImpl (Kind kind, const TypeSummaryImpl::Flags &flags, uint32_t ptr_match_depth=1)
Protected Attributes inherited from lldb_private::TypeSummaryImpl
uint32_t m_my_revision = 0
Flags m_flags
Detailed Description
A summary formatter that is defined in LLDB formmater bytecode.
See BytecodeSyntheticChildren for the corresponding synthetic formatter.
Formatter bytecode documentation can be found in lldb/docs/resources/formatterbytecode.rst
Definition at line 432 of file TypeSummary.h.
Constructor & Destructor Documentation
BytecodeSummaryFormat()
BytecodeSummaryFormat::BytecodeSummaryFormat (const TypeSummaryImpl::Flags & flags, std::unique_ptr< llvm::MemoryBuffer > bytecode)
Definition at line 245 of file TypeSummary.cpp.
References lldb_private::TypeSummaryImpl::eBytecode, m_bytecode, and lldb_private::TypeSummaryImpl::TypeSummaryImpl().
Member Function Documentation
classof()
bool lldb_private::BytecodeSummaryFormat::classof (const TypeSummaryImpl * S) inline static
Definition at line 442 of file TypeSummary.h.
References lldb_private::TypeSummaryImpl::eBytecode, and lldb_private::TypeSummaryImpl::TypeSummaryImpl().
FormatObject()
bool BytecodeSummaryFormat::FormatObject (ValueObject * valobj, std::string & dest, const TypeSummaryOptions & options) override virtual
Implements lldb_private::TypeSummaryImpl.
Definition at line 251 of file TypeSummary.cpp.
References error(), lldb_private::ValueObject::GetSP(), lldb_private::ValueObject::GetTargetSP(), lldb_private::ValueObject::GetValueAsCString(), lldb_private::FormatterBytecode::Interpret(), m_bytecode, and lldb_private::toString().
GetDescription()
std::string BytecodeSummaryFormat::GetDescription () override virtual
Implements lldb_private::TypeSummaryImpl.
Definition at line 298 of file TypeSummary.cpp.
References lldb_private::TypeSummaryImpl::Cascades(), lldb_private::TypeSummaryImpl::DoesPrintChildren(), lldb_private::TypeSummaryImpl::DoesPrintValue(), lldb_private::StreamString::GetString(), lldb_private::TypeSummaryImpl::HideNames(), lldb_private::TypeSummaryImpl::IsOneLiner(), lldb_private::Stream::Printf(), lldb_private::TypeSummaryImpl::SkipsPointers(), and lldb_private::TypeSummaryImpl::SkipsReferences().
GetName()
std::string BytecodeSummaryFormat::GetName () override virtual
Get the name of the Type Summary Provider, either a C++ class, a summary string, or a script function name.
Implements lldb_private::TypeSummaryImpl.
Definition at line 311 of file TypeSummary.cpp.
Member Data Documentation
m_bytecode
std::unique_ptr<llvm::MemoryBuffer> lldb_private::BytecodeSummaryFormat::m_bytecode private
Definition at line 433 of file TypeSummary.h.
Referenced by BytecodeSummaryFormat(), and FormatObject().
The documentation for this class was generated from the following files:
TypeSummary.h
TypeSummary.cpp