LLDB: OptionGroupDependents Class Reference
OptionGroupDependents Class Reference
Public Member Functions
OptionGroupDependents ()=default
~OptionGroupDependents () override=default
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext *execution_context) override
Status SetOptionValue (uint32_t, const char *, ExecutionContext *)=delete
void OptionParsingStarting (ExecutionContext *execution_context) override
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Public Attributes
LoadDependentFiles m_load_dependent_files
Private Member Functions
OptionGroupDependents (const OptionGroupDependents &)=delete
const OptionGroupDependents & operator= (const OptionGroupDependents &)=delete
Detailed Description
Definition at line 162 of file CommandObjectTarget.cpp.
Constructor & Destructor Documentation
OptionGroupDependents() [1/2]
OptionGroupDependents::OptionGroupDependents () default
Referenced by operator=(), and OptionGroupDependents().
~OptionGroupDependents()
OptionGroupDependents::~OptionGroupDependents () override default
OptionGroupDependents() [2/2]
OptionGroupDependents::OptionGroupDependents (const OptionGroupDependents &) private delete
References OptionGroupDependents().
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > OptionGroupDependents::GetDefinitions () inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 168 of file CommandObjectTarget.cpp.
operator=()
const OptionGroupDependents & OptionGroupDependents::operator= (const OptionGroupDependents &) private delete
References OptionGroupDependents().
OptionParsingStarting()
void OptionGroupDependents::OptionParsingStarting (ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 201 of file CommandObjectTarget.cpp.
References lldb_private::eLoadDependentsDefault, and m_load_dependent_files.
SetOptionValue() [1/2]
Status OptionGroupDependents::SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 172 of file CommandObjectTarget.cpp.
References lldb_private::eLoadDependentsNo, error(), lldb_private::Status::FromErrorStringWithFormat(), m_load_dependent_files, and lldb_private::OptionArgParser::ToOptionEnum().
SetOptionValue() [2/2]
Status OptionGroupDependents::SetOptionValue (uint32_t , const char * , ExecutionContext *) delete
Member Data Documentation
m_load_dependent_files
LoadDependentFiles OptionGroupDependents::m_load_dependent_files
Definition at line 205 of file CommandObjectTarget.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following file:
CommandObjectTarget.cpp