LLDB: lldb_private::SymbolChangeEventData Class Reference
lldb_private::SymbolChangeEventData Class Reference
#include <DebuggerEvents.h>
Public Member Functions
SymbolChangeEventData (lldb::DebuggerWP debugger_wp, ModuleSpec module_spec)
llvm::StringRef GetFlavor () const override
void DoOnRemoval (Event *event_ptr) override
Public Member Functions inherited from lldb_private::EventData
EventData ()
virtual ~EventData ()
virtual Log * GetLogChannel ()
virtual void Dump (Stream *s) const
Static Public Member Functions
static llvm::StringRef GetFlavorString ()
static const SymbolChangeEventData * GetEventDataFromEvent (const Event *event_ptr)
Private Member Functions
SymbolChangeEventData (const SymbolChangeEventData &)=delete
const SymbolChangeEventData & operator= (const SymbolChangeEventData &)=delete
Private Attributes
lldb::DebuggerWP m_debugger_wp
ModuleSpec m_module_spec
Detailed Description
Definition at line 111 of file DebuggerEvents.h.
Constructor & Destructor Documentation
SymbolChangeEventData() [1/2]
lldb_private::SymbolChangeEventData::SymbolChangeEventData (lldb::DebuggerWP debugger_wp, ModuleSpec module_spec) inline
Definition at line 113 of file DebuggerEvents.h.
References m_debugger_wp, and m_module_spec.
Referenced by operator=(), and SymbolChangeEventData().
SymbolChangeEventData() [2/2]
lldb_private::SymbolChangeEventData::SymbolChangeEventData (const SymbolChangeEventData &) private delete
References SymbolChangeEventData().
Member Function Documentation
DoOnRemoval()
void SymbolChangeEventData::DoOnRemoval (Event * event_ptr) override virtual
Reimplemented from lldb_private::EventData.
Definition at line 139 of file DebuggerEvents.cpp.
References lldb_private::ModuleList::Append(), lldb_private::EventData::Event, m_debugger_wp, and m_module_spec.
GetEventDataFromEvent()
const SymbolChangeEventData * SymbolChangeEventData::GetEventDataFromEvent (const Event * event_ptr) static
Definition at line 135 of file DebuggerEvents.cpp.
References lldb_private::EventData::Event, and GetEventDataFromEventImpl().
GetFlavor()
llvm::StringRef SymbolChangeEventData::GetFlavor () const override virtual
Implements lldb_private::EventData.
Definition at line 130 of file DebuggerEvents.cpp.
References GetFlavorString().
GetFlavorString()
llvm::StringRef SymbolChangeEventData::GetFlavorString () static
Definition at line 126 of file DebuggerEvents.cpp.
Referenced by GetFlavor().
operator=()
const SymbolChangeEventData & lldb_private::SymbolChangeEventData::operator= (const SymbolChangeEventData &) private delete
References SymbolChangeEventData().
Member Data Documentation
m_debugger_wp
lldb::DebuggerWP lldb_private::SymbolChangeEventData::m_debugger_wp private
Definition at line 125 of file DebuggerEvents.h.
Referenced by DoOnRemoval(), and SymbolChangeEventData().
m_module_spec
ModuleSpec lldb_private::SymbolChangeEventData::m_module_spec private
Definition at line 126 of file DebuggerEvents.h.
Referenced by DoOnRemoval(), and SymbolChangeEventData().
The documentation for this class was generated from the following files:
DebuggerEvents.h
DebuggerEvents.cpp