LLDB: lldb_private::ProcessInfo Class Reference
lldb_private::ProcessInfo Class Reference
#include <ProcessInfo.h>
Public Member Functions
ProcessInfo ()
ProcessInfo (const char *name, const ArchSpec &arch, lldb::pid_t pid)
void Clear ()
const char * GetName () const
llvm::StringRef GetNameAsStringRef () const
FileSpec & GetExecutableFile ()
void SetExecutableFile (const FileSpec &exe_file, bool add_exe_file_as_first_arg)
const FileSpec & GetExecutableFile () const
uint32_t GetUserID () const
uint32_t GetGroupID () const
bool UserIDIsValid () const
bool GroupIDIsValid () const
void SetUserID (uint32_t uid)
void SetGroupID (uint32_t gid)
ArchSpec & GetArchitecture ()
const ArchSpec & GetArchitecture () const
void SetArchitecture (const ArchSpec &arch)
lldb::pid_t GetProcessID () const
void SetProcessID (lldb::pid_t pid)
bool ProcessIDIsValid () const
void Dump (Stream &s, Platform *platform) const
Args & GetArguments ()
const Args & GetArguments () const
llvm::StringRef GetArg0 () const
void SetArg0 (llvm::StringRef arg)
void SetArguments (const Args &args, bool first_arg_is_executable)
void SetArguments (char const **argv, bool first_arg_is_executable)
Environment & GetEnvironment ()
const Environment & GetEnvironment () const
bool IsScriptedProcess () const
lldb::ScriptedMetadataSP GetScriptedMetadata () const
void SetScriptedMetadata (lldb::ScriptedMetadataSP metadata_sp)
lldb::ListenerSP GetListener () const
void SetListener (const lldb::ListenerSP &listener_sp)
lldb::ListenerSP GetHijackListener () const
void SetHijackListener (const lldb::ListenerSP &listener_sp)
lldb::ListenerSP GetShadowListener () const
void SetShadowListener (const lldb::ListenerSP &listener_sp)
Protected Attributes
FileSpec m_executable
std::string m_arg0
Args m_arguments
Environment m_environment
uint32_t m_uid = UINT32_MAX
uint32_t m_gid = UINT32_MAX
ArchSpec m_arch
lldb::pid_t m_pid = LLDB_INVALID_PROCESS_ID
lldb::ScriptedMetadataSP m_scripted_metadata_sp = nullptr
lldb::ListenerSP m_listener_sp = nullptr
lldb::ListenerSP m_hijack_listener_sp = nullptr
lldb::ListenerSP m_shadow_listener_sp = nullptr
Detailed Description
Definition at line 31 of file ProcessInfo.h.
Constructor & Destructor Documentation
ProcessInfo() [1/2]
ProcessInfo::ProcessInfo ()
Definition at line 24 of file ProcessInfo.cpp.
References m_arch, m_arguments, m_environment, m_executable, m_hijack_listener_sp, m_listener_sp, and m_shadow_listener_sp.
Referenced by lldb_private::ProcessInstanceInfo::ProcessInstanceInfo(), lldb_private::ProcessLaunchInfo::ProcessLaunchInfo(), and lldb_private::ProcessLaunchInfo::ProcessLaunchInfo().
ProcessInfo() [2/2]
ProcessInfo::ProcessInfo (const char * name, const ArchSpec & arch, lldb::pid_t pid)
Definition at line 28 of file ProcessInfo.cpp.
References m_arch, m_arguments, m_environment, m_executable, m_hijack_listener_sp, m_listener_sp, m_pid, and m_shadow_listener_sp.
Member Function Documentation
Clear()
void ProcessInfo::Clear ()
Definition at line 34 of file ProcessInfo.cpp.
References LLDB_INVALID_PROCESS_ID, m_arch, m_arguments, m_environment, m_executable, m_gid, m_pid, m_scripted_metadata_sp, m_uid, and UINT32_MAX.
Referenced by lldb_private::ProcessInstanceInfo::Clear(), and lldb_private::ProcessLaunchInfo::Clear().
Dump()
void ProcessInfo::Dump (Stream & s, Platform * platform) const
Definition at line 53 of file ProcessInfo.cpp.
References lldb_private::Stream::AsRawOstream(), lldb_private::Stream::Format(), GetName(), m_arch, m_arguments, and m_environment.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess().
GetArchitecture() [1/2]
ArchSpec & lldb_private::ProcessInfo::GetArchitecture () inline
Definition at line 62 of file ProcessInfo.h.
References m_arch.
Referenced by lldb_private::Process::CompleteAttach(), lldb_private::ProcessLaunchInfo::ConvertArgumentsForLaunchingInShell(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse_DebugServerStyle(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::DecodeProcessInfoResponse(), lldb_private::StructuredDataDarwinLog::FilterLaunchInfo(), lldb_private::PlatformAppleSimulator::FindProcesses(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), GetMacOSXProcessArgs(), GetMacOSXProcessCPUType(), GetNetBSDProcessCPUType(), GetOpenBSDProcessCPUType(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qfProcessInfo(), lldb::SBTarget::Launch(), lldb_private::Target::Launch(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::LaunchProcess(), LaunchProcessPosixSpawn(), LaunchProcessXPC(), lldb_private::ProcessInstanceInfoMatch::Matches(), lldb_private::NativeProcessWindows::NativeProcessWindows(), lldb_private::NativeProcessWindows::OnDebuggerConnected(), and DynamicLoaderPOSIXDYLD::ResolveExecutableModule().
GetArchitecture() [2/2]
const ArchSpec & lldb_private::ProcessInfo::GetArchitecture () const inline
Definition at line 64 of file ProcessInfo.h.
References m_arch.
GetArg0()
llvm::StringRef ProcessInfo::GetArg0 () const
Definition at line 80 of file ProcessInfo.cpp.
References m_arg0.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse(), lldb_private::PlatformQemuUser::DebugProcess(), and lldb_private::TargetProperties::SetProcessLaunchInfo().
GetArguments() [1/2]
Args & lldb_private::ProcessInfo::GetArguments () inline
Definition at line 76 of file ProcessInfo.h.
References m_arguments.
Referenced by lldb_private::ProcessLaunchInfo::ConvertArgumentsForLaunchingInShell(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse(), lldb_private::PlatformQemuUser::DebugProcess(), lldb_private::PlatformWasm::DebugProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::DecodeProcessInfoResponse(), CommandObjectProcessLaunch::DoExecute(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoLaunch(), GetFreeBSDProcessArgs(), GetMacOSXProcessArgs(), GetNetBSDProcessArgs(), GetOpenBSDProcessArgs(), GetProcessArgs(), lldb::SBTarget::Launch(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::LaunchProcess(), lldb_private::ProcessLauncherWindows::LaunchProcess(), LaunchProcessPosixSpawn(), LaunchProcessXPC(), MaybeLogLaunchInfo(), ELFLinuxPrPsInfo::Populate(), lldb::SBProcess::RemoteLaunch(), lldb_private::Host::RunShellCommand(), lldb_private::TargetProperties::SetProcessLaunchInfo(), CoreSimulatorSupport::Device::Spawn(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess().
GetArguments() [2/2]
const Args & lldb_private::ProcessInfo::GetArguments () const inline
Definition at line 78 of file ProcessInfo.h.
References m_arguments.
GetEnvironment() [1/2]
Environment & lldb_private::ProcessInfo::GetEnvironment () inline
Definition at line 88 of file ProcessInfo.h.
References m_environment.
Referenced by lldb_private::PlatformQemuUser::DebugProcess(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoLaunch(), lldb_private::StructuredDataDarwinLog::FilterLaunchInfo(), GetMacOSXProcessArgs(), lldb_private::PlatformDarwin::GetOSVersion(), GetProcessEnviron(), lldb_private::PlatformDarwin::GetResumeCountForLaunchInfo(), lldb::SBTarget::Launch(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::LaunchProcess(), lldb_private::PlatformDarwin::LaunchProcess(), lldb_private::ProcessLauncherWindows::LaunchProcess(), LaunchProcessPosixSpawn(), LaunchProcessXPC(), lldb_private::SBLaunchInfoImpl::RegenerateEnvp(), lldb::SBProcess::RemoteLaunch(), lldb_private::Host::RunShellCommand(), lldb_private::SBLaunchInfoImpl::SBLaunchInfoImpl(), lldb_private::TargetProperties::SetProcessLaunchInfo(), CoreSimulatorSupport::Device::Spawn(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess().
GetEnvironment() [2/2]
const Environment & lldb_private::ProcessInfo::GetEnvironment () const inline
Definition at line 89 of file ProcessInfo.h.
References m_environment.
GetExecutableFile() [1/2]
FileSpec & lldb_private::ProcessInfo::GetExecutableFile () inline
Definition at line 43 of file ProcessInfo.h.
References m_executable.
Referenced by lldb_private::Process::Attach(), lldb_private::Target::Attach(), lldb::SBTarget::AttachToProcessWithName(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::AttachWaitProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse(), lldb_private::DebuggerThread::DebuggerThreadLaunchRoutine(), lldb_private::DebuggerThread::DebugLaunch(), lldb_private::PlatformQemuUser::DebugProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::DecodeProcessInfoResponse(), CommandObjectProcessLaunch::DoExecute(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoLaunch(), GetExePathAndArch(), GetExePathAndIds(), GetFreeBSDProcessArgs(), GetMacOSXProcessArgs(), GetNetBSDProcessArgs(), GetNetBSDProcessCPUType(), GetOpenBSDProcessArgs(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qfProcessInfo(), lldb::SBTarget::Launch(), lldb_private::Target::Launch(), lldb_private::Process::LaunchPrivate(), lldb_private::MonitoringProcessLauncher::LaunchProcess(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::LaunchProcess(), lldb_private::ProcessDebugger::LaunchProcess(), lldb_private::ProcessLauncherWindows::LaunchProcess(), lldb_private::ProcessAttachInfo::ProcessInfoSpecified(), and DynamicLoaderPOSIXDYLD::ResolveExecutableModule().
GetExecutableFile() [2/2]
const FileSpec & lldb_private::ProcessInfo::GetExecutableFile () const inline
Definition at line 48 of file ProcessInfo.h.
References m_executable.
GetGroupID()
uint32_t lldb_private::ProcessInfo::GetGroupID () const inline
Definition at line 52 of file ProcessInfo.h.
References m_gid.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse_DebugServerStyle(), lldb_private::ProcessInstanceInfo::Dump(), lldb_private::ProcessInstanceInfo::DumpAsTableRow(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), ELFLinuxPrPsInfo::Populate(), and lldb_private::ProcessInstanceInfoMatch::UserIDsMatch().
GetHijackListener()
lldb::ListenerSP lldb_private::ProcessInfo::GetHijackListener () const inline
Definition at line 108 of file ProcessInfo.h.
References m_hijack_listener_sp.
Referenced by lldb_private::platform_gdb_server::PlatformRemoteGDBServer::Attach(), lldb_private::PlatformWindows::Attach(), lldb_private::Target::Attach(), PlatformPOSIX::Attach(), lldb_private::Platform::DebugProcess(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::DebugProcess(), lldb_private::PlatformAppleSimulator::DebugProcess(), lldb_private::PlatformQemuUser::DebugProcess(), lldb_private::PlatformWasm::DebugProcess(), lldb_private::PlatformWindows::DebugProcess(), PlatformPOSIX::DebugProcess(), and lldb_private::Target::Launch().
GetListener()
lldb::ListenerSP lldb_private::ProcessInfo::GetListener () const inline
Definition at line 102 of file ProcessInfo.h.
References m_listener_sp.
Referenced by AttachToProcess(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::DebugProcess(), lldb_private::PlatformQemuUser::DebugProcess(), lldb_private::PlatformWasm::DebugProcess(), lldb_private::PlatformWindows::DebugProcess(), PlatformPOSIX::DebugProcess(), and lldb_private::Target::Launch().
GetName()
const char * ProcessInfo::GetName () const
Definition at line 45 of file ProcessInfo.cpp.
References m_executable.
Referenced by Dump(), lldb_private::ProcessInstanceInfo::DumpAsTableRow(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), GetFreeBSDProcessArgs(), GetMacOSXProcessArgs(), lldb_private::NativeThreadWindows::GetName(), GetNetBSDProcessArgs(), GetOpenBSDProcessArgs(), and lldb_private::ProcessInstanceInfoMatch::Matches().
GetNameAsStringRef()
llvm::StringRef ProcessInfo::GetNameAsStringRef () const
Definition at line 49 of file ProcessInfo.cpp.
References m_executable.
Referenced by ELFLinuxPrPsInfo::Populate().
GetProcessID()
lldb::pid_t lldb_private::ProcessInfo::GetProcessID () const inline
Definition at line 68 of file ProcessInfo.h.
References m_pid.
Referenced by MinidumpFileBuilder::AddLinuxFileStreams(), MinidumpFileBuilder::AddMiscInfo(), lldb::SBTarget::Attach(), lldb_private::Process::Attach(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse_DebugServerStyle(), lldb_private::Platform::DebugProcess(), lldb_private::PlatformAppleSimulator::DebugProcess(), lldb_private::PlatformWindows::DebugProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::DecodeProcessInfoResponse(), lldb_private::ProcessWindows::DoLaunch(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), GetFreeBSDProcessArgs(), GetFreeBSDProcessUserAndGroup(), GetMacOSXProcessArgs(), GetMacOSXProcessCPUType(), GetMacOSXProcessUserAndGroup(), GetNetBSDProcessArgs(), GetNetBSDProcessUserAndGroup(), GetOpenBSDProcessArgs(), GetOpenBSDProcessUserAndGroup(), lldb_private::process_gdb_remote::ProcessGDBRemote::LaunchAndConnectToDebugserver(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::LaunchGDBServer(), lldb_private::ProcessLaunchInfo::MonitorProcess(), ELFLinuxPrPsInfo::Populate(), lldb_private::ProcessInstanceInfoMatch::ProcessIDsMatch(), lldb_private::ProcessAttachInfo::ProcessInfoSpecified(), and lldb_private::Host::RunShellCommand().
GetScriptedMetadata()
lldb::ScriptedMetadataSP lldb_private::ProcessInfo::GetScriptedMetadata () const inline
Definition at line 93 of file ProcessInfo.h.
References m_scripted_metadata_sp.
Referenced by lldb_private::Target::SaveScriptedLaunchInfo(), and lldb_private::ScriptedMetadata::ScriptedMetadata().
GetShadowListener()
lldb::ListenerSP lldb_private::ProcessInfo::GetShadowListener () const inline
Definition at line 114 of file ProcessInfo.h.
References m_shadow_listener_sp.
Referenced by lldb_private::platform_gdb_server::PlatformRemoteGDBServer::Attach(), PlatformPOSIX::Attach(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::DebugProcess(), PlatformPOSIX::DebugProcess(), and lldb_private::Target::Launch().
GetUserID()
uint32_t lldb_private::ProcessInfo::GetUserID () const inline
Definition at line 50 of file ProcessInfo.h.
References m_uid.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::CreateProcessInfoResponse_DebugServerStyle(), lldb_private::ProcessInstanceInfo::Dump(), lldb_private::ProcessInstanceInfo::DumpAsTableRow(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), lldb_private::Host::FindProcessesImpl(), lldb_private::process_gdb_remote::ProcessGDBRemote::LaunchAndConnectToDebugserver(), LaunchProcessXPC(), ELFLinuxPrPsInfo::Populate(), ShouldLaunchUsingXPC(), and lldb_private::ProcessInstanceInfoMatch::UserIDsMatch().
GroupIDIsValid()
bool lldb_private::ProcessInfo::GroupIDIsValid () const inline
Definition at line 56 of file ProcessInfo.h.
References m_gid, and UINT32_MAX.
Referenced by lldb_private::ProcessInstanceInfo::Dump(), lldb_private::ProcessInstanceInfo::DumpAsTableRow(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses().
IsScriptedProcess()
bool ProcessInfo::IsScriptedProcess () const
Definition at line 116 of file ProcessInfo.cpp.
References m_scripted_metadata_sp.
Referenced by lldb::SBTarget::Attach(), lldb_private::Target::Attach(), lldb_private::Target::Launch(), lldb_private::Process::LaunchPrivate(), and lldb_private::Target::SaveScriptedLaunchInfo().
ProcessIDIsValid()
bool lldb_private::ProcessInfo::ProcessIDIsValid () const inline
Definition at line 72 of file ProcessInfo.h.
References LLDB_INVALID_PROCESS_ID, and m_pid.
Referenced by MinidumpFileBuilder::AddLinuxFileStreams(), MinidumpFileBuilder::AddMiscInfo(), lldb::SBTarget::Attach(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses(), GetFreeBSDProcessArgs(), GetFreeBSDProcessUserAndGroup(), GetMacOSXProcessArgs(), GetMacOSXProcessCPUType(), GetMacOSXProcessUserAndGroup(), GetNetBSDProcessArgs(), GetNetBSDProcessCPUType(), GetNetBSDProcessUserAndGroup(), GetOpenBSDProcessArgs(), GetOpenBSDProcessCPUType(), GetOpenBSDProcessUserAndGroup(), and lldb_private::ProcessLaunchInfo::MonitorProcess().
SetArchitecture()
void lldb_private::ProcessInfo::SetArchitecture (const ArchSpec & arch) inline
Definition at line 66 of file ProcessInfo.h.
References m_arch.
Referenced by GetExePathAndArch(), GetExePathAndIds(), GetFreeBSDProcessArgs(), GetProcessExecutableAndTriple(), lldb_private::minidump::ProcessMinidump::GetProcessInfo(), lldb_private::ProcessTrace::GetProcessInfo(), lldb_private::ScriptedProcess::GetProcessInfo(), ProcessElfCore::GetProcessInfo(), and lldb_private::Host::RunShellCommand().
SetArg0()
void ProcessInfo::SetArg0 (llvm::StringRef arg)
Definition at line 82 of file ProcessInfo.cpp.
References m_arg0.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::DecodeProcessInfoResponse(), GetFreeBSDProcessArgs(), GetNetBSDProcessArgs(), and GetProcessArgs().
SetArguments() [1/2]
void ProcessInfo::SetArguments (char const ** argv, bool first_arg_is_executable)
Definition at line 84 of file ProcessInfo.cpp.
References m_arguments, and m_executable.
SetArguments() [2/2]
void ProcessInfo::SetArguments (const Args & args, bool first_arg_is_executable)
Definition at line 100 of file ProcessInfo.cpp.
References m_arguments, and m_executable.
Referenced by lldb_private::PlatformQemuUser::DebugProcess(), lldb_private::PlatformWasm::DebugProcess(), and lldb_private::Host::RunShellCommand().
SetExecutableFile()
void ProcessInfo::SetExecutableFile (const FileSpec & exe_file, bool add_exe_file_as_first_arg)
Definition at line 65 of file ProcessInfo.cpp.
References lldb_private::FileSpec::GetPath(), m_arguments, and m_executable.
Referenced by CommandObjectTargetCreate::DoExecute(), GetProcessExecutableAndTriple(), lldb_private::minidump::ProcessMinidump::GetProcessInfo(), lldb_private::ProcessTrace::GetProcessInfo(), lldb_private::ScriptedProcess::GetProcessInfo(), ProcessElfCore::GetProcessInfo(), lldb::SBTarget::Launch(), lldb::SBTarget::Launch(), lldb_private::process_gdb_remote::ProcessGDBRemote::LaunchAndConnectToDebugserver(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::LaunchGDBServer(), lldb_private::MonitoringProcessLauncher::LaunchProcess(), and lldb::SBProcess::RemoteLaunch().
SetGroupID()
void lldb_private::ProcessInfo::SetGroupID (uint32_t gid) inline
Definition at line 60 of file ProcessInfo.h.
References m_gid.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::DecodeProcessInfoResponse(), GetExePathAndIds(), GetFreeBSDProcessUserAndGroup(), GetMacOSXProcessUserAndGroup(), GetNetBSDProcessUserAndGroup(), GetOpenBSDProcessUserAndGroup(), GetStatusInfo(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qfProcessInfo().
SetHijackListener()
void lldb_private::ProcessInfo::SetHijackListener (const lldb::ListenerSP & listener_sp) inline
Definition at line 110 of file ProcessInfo.h.
References m_hijack_listener_sp.
Referenced by lldb_private::Target::Attach(), PlatformPOSIX::Attach(), lldb_private::Platform::DebugProcess(), lldb_private::PlatformAppleSimulator::DebugProcess(), and lldb_private::Target::Launch().
SetListener()
void lldb_private::ProcessInfo::SetListener (const lldb::ListenerSP & listener_sp) inline
Definition at line 104 of file ProcessInfo.h.
References m_listener_sp.
Referenced by lldb::SBTarget::AttachToProcessWithID(), lldb::SBTarget::AttachToProcessWithName(), and lldb::SBTarget::Launch().
SetProcessID()
void lldb_private::ProcessInfo::SetProcessID (lldb::pid_t pid) inline
Definition at line 70 of file ProcessInfo.h.
References m_pid.
Referenced by lldb::SBTarget::AttachToProcessWithID(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::DecodeProcessInfoResponse(), GetProcessAndStatInfo(), GetProcessAndStatInfo(), lldb_private::minidump::ProcessMinidump::GetProcessInfo(), lldb_private::ProcessTrace::GetProcessInfo(), lldb_private::ScriptedProcess::GetProcessInfo(), ProcessElfCore::GetProcessInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qfProcessInfo(), lldb_private::Host::LaunchProcess(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::LaunchProcess(), lldb_private::PlatformAppleSimulator::LaunchProcess(), lldb_private::ProcessDebugger::LaunchProcess(), lldb_private::NativeProcessWindows::NativeProcessWindows(), and lldb::SBProcess::RemoteAttachToProcessWithID().
SetScriptedMetadata()
void lldb_private::ProcessInfo::SetScriptedMetadata (lldb::ScriptedMetadataSP metadata_sp) inline
Definition at line 97 of file ProcessInfo.h.
References m_scripted_metadata_sp.
Referenced by lldb_private::Target::SaveScriptedLaunchInfo().
SetShadowListener()
void lldb_private::ProcessInfo::SetShadowListener (const lldb::ListenerSP & listener_sp) inline
Definition at line 116 of file ProcessInfo.h.
References m_shadow_listener_sp.
SetUserID()
void lldb_private::ProcessInfo::SetUserID (uint32_t uid) inline
Definition at line 58 of file ProcessInfo.h.
References m_uid.
Referenced by lldb::SBTarget::Attach(), lldb::SBTarget::AttachToProcessWithID(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::DecodeProcessInfoResponse(), GetExePathAndIds(), GetFreeBSDProcessUserAndGroup(), GetMacOSXProcessUserAndGroup(), GetNetBSDProcessUserAndGroup(), GetOpenBSDProcessUserAndGroup(), GetStatusInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qfProcessInfo(), and lldb_private::process_gdb_remote::ProcessGDBRemote::LaunchAndConnectToDebugserver().
UserIDIsValid()
bool lldb_private::ProcessInfo::UserIDIsValid () const inline
Definition at line 54 of file ProcessInfo.h.
References m_uid, and UINT32_MAX.
Referenced by lldb::SBTarget::Attach(), lldb_private::ProcessInstanceInfo::Dump(), lldb_private::ProcessInstanceInfo::DumpAsTableRow(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::FindProcesses().
Member Data Documentation
m_arch
ArchSpec lldb_private::ProcessInfo::m_arch protected
Definition at line 129 of file ProcessInfo.h.
Referenced by Clear(), Dump(), lldb_private::ProcessInstanceInfo::Dump(), lldb_private::ProcessInstanceInfo::DumpAsTableRow(), GetArchitecture(), GetArchitecture(), ProcessInfo(), ProcessInfo(), and SetArchitecture().
m_arg0
std::string lldb_private::ProcessInfo::m_arg0 protected
Definition at line 122 of file ProcessInfo.h.
Referenced by lldb_private::ProcessInstanceInfo::DumpAsTableRow(), GetArg0(), and SetArg0().
m_arguments
Args lldb_private::ProcessInfo::m_arguments protected
Definition at line 125 of file ProcessInfo.h.
Referenced by Clear(), lldb_private::ProcessLaunchInfo::ConvertArgumentsForLaunchingInShell(), Dump(), lldb_private::ProcessInstanceInfo::Dump(), lldb_private::ProcessInstanceInfo::DumpAsTableRow(), GetArguments(), GetArguments(), ProcessInfo(), ProcessInfo(), SetArguments(), SetArguments(), and SetExecutableFile().
m_environment
Environment lldb_private::ProcessInfo::m_environment protected
Definition at line 126 of file ProcessInfo.h.
Referenced by Clear(), Dump(), lldb_private::ProcessInstanceInfo::Dump(), GetEnvironment(), GetEnvironment(), ProcessInfo(), and ProcessInfo().
m_executable
FileSpec lldb_private::ProcessInfo::m_executable protected
Definition at line 121 of file ProcessInfo.h.
Referenced by Clear(), lldb_private::ProcessLaunchInfo::ConvertArgumentsForLaunchingInShell(), lldb_private::ProcessInstanceInfo::Dump(), GetExecutableFile(), GetExecutableFile(), GetName(), GetNameAsStringRef(), ProcessInfo(), ProcessInfo(), SetArguments(), SetArguments(), and SetExecutableFile().
m_gid
uint32_t lldb_private::ProcessInfo::m_gid = UINT32_MAX protected
Definition at line 128 of file ProcessInfo.h.
Referenced by Clear(), GetGroupID(), GroupIDIsValid(), and SetGroupID().
m_hijack_listener_sp
lldb::ListenerSP lldb_private::ProcessInfo::m_hijack_listener_sp = nullptr protected
Definition at line 133 of file ProcessInfo.h.
Referenced by lldb_private::ProcessLaunchInfo::Clear(), GetHijackListener(), ProcessInfo(), ProcessInfo(), and SetHijackListener().
m_listener_sp
lldb::ListenerSP lldb_private::ProcessInfo::m_listener_sp = nullptr protected
Definition at line 132 of file ProcessInfo.h.
Referenced by lldb_private::ProcessLaunchInfo::Clear(), GetListener(), lldb_private::ProcessAttachInfo::GetListenerForProcess(), ProcessInfo(), ProcessInfo(), and SetListener().
m_pid
lldb::pid_t lldb_private::ProcessInfo::m_pid = LLDB_INVALID_PROCESS_ID protected
Definition at line 130 of file ProcessInfo.h.
Referenced by Clear(), lldb_private::ProcessInstanceInfo::Dump(), lldb_private::ProcessInstanceInfo::DumpAsTableRow(), GetProcessID(), ProcessIDIsValid(), ProcessInfo(), and SetProcessID().
m_scripted_metadata_sp
lldb::ScriptedMetadataSP lldb_private::ProcessInfo::m_scripted_metadata_sp = nullptr protected
Definition at line 131 of file ProcessInfo.h.
Referenced by Clear(), GetScriptedMetadata(), IsScriptedProcess(), and SetScriptedMetadata().
m_shadow_listener_sp
lldb::ListenerSP lldb_private::ProcessInfo::m_shadow_listener_sp = nullptr protected
Definition at line 134 of file ProcessInfo.h.
Referenced by GetShadowListener(), ProcessInfo(), ProcessInfo(), and SetShadowListener().
m_uid
uint32_t lldb_private::ProcessInfo::m_uid = UINT32_MAX protected
Definition at line 127 of file ProcessInfo.h.
Referenced by Clear(), GetUserID(), SetUserID(), and UserIDIsValid().
The documentation for this class was generated from the following files:
ProcessInfo.h
ProcessInfo.cpp