LLDB: lldb_private::AllocatedBlock Class Reference
lldb_private::AllocatedBlock Class Reference
#include <Memory.h>
Public Member Functions
AllocatedBlock (lldb::addr_t addr, uint32_t byte_size, uint32_t permissions, uint32_t chunk_size)
~AllocatedBlock ()
lldb::addr_t ReserveBlock (uint32_t size)
bool FreeBlock (lldb::addr_t addr)
lldb::addr_t GetBaseAddress () const
uint32_t GetByteSize () const
uint32_t GetPermissions () const
uint32_t GetChunkSize () const
bool Contains (lldb::addr_t addr) const
Protected Member Functions
uint32_t TotalChunks () const
uint32_t CalculateChunksNeededForSize (uint32_t size) const
Protected Attributes
Range< lldb::addr_t, uint32_t > m_range
const uint32_t m_permissions
const uint32_t m_chunk_size
RangeVector< lldb::addr_t, uint32_t > m_free_blocks
RangeVector< lldb::addr_t, uint32_t > m_reserved_blocks
Detailed Description
Definition at line 70 of file Memory.h.
Constructor & Destructor Documentation
AllocatedBlock()
AllocatedBlock::AllocatedBlock (lldb::addr_t addr, uint32_t byte_size, uint32_t permissions, uint32_t chunk_size)
Definition at line 268 of file Memory.cpp.
References m_chunk_size, m_free_blocks, m_permissions, and m_range.
~AllocatedBlock()
AllocatedBlock::~AllocatedBlock () default
Member Function Documentation
CalculateChunksNeededForSize()
uint32_t lldb_private::AllocatedBlock::CalculateChunksNeededForSize (uint32_t size) const inline protected
Definition at line 96 of file Memory.h.
References m_chunk_size.
Referenced by ReserveBlock().
Contains()
bool lldb_private::AllocatedBlock::Contains (lldb::addr_t addr) const inline
Definition at line 89 of file Memory.h.
References m_range.
FreeBlock()
bool AllocatedBlock::FreeBlock (lldb::addr_t addr)
Definition at line 331 of file Memory.cpp.
References lldb_private::GetLog(), LLDB_LOGV, m_free_blocks, m_reserved_blocks, lldb_private::Process, and UINT32_MAX.
GetBaseAddress()
lldb::addr_t lldb_private::AllocatedBlock::GetBaseAddress () const inline
Definition at line 81 of file Memory.h.
References m_range.
GetByteSize()
uint32_t lldb_private::AllocatedBlock::GetByteSize () const inline
Definition at line 83 of file Memory.h.
References m_range.
Referenced by TotalChunks().
GetChunkSize()
uint32_t lldb_private::AllocatedBlock::GetChunkSize () const inline
Definition at line 87 of file Memory.h.
References m_chunk_size.
Referenced by TotalChunks().
GetPermissions()
uint32_t lldb_private::AllocatedBlock::GetPermissions () const inline
Definition at line 85 of file Memory.h.
References m_permissions.
ReserveBlock()
lldb::addr_t AllocatedBlock::ReserveBlock (uint32_t size)
Definition at line 280 of file Memory.cpp.
References CalculateChunksNeededForSize(), lldb_private::GetLog(), lldb_private::Range< B, S >::GetRangeEnd(), LLDB_INVALID_ADDRESS, LLDB_LOGV, m_chunk_size, m_free_blocks, m_reserved_blocks, lldb_private::Process, and lldb_private::Range< B, S >::SetByteSize().
TotalChunks()
uint32_t lldb_private::AllocatedBlock::TotalChunks () const inline protected
Definition at line 94 of file Memory.h.
References GetByteSize(), and GetChunkSize().
Member Data Documentation
m_chunk_size
const uint32_t lldb_private::AllocatedBlock::m_chunk_size protected
Definition at line 104 of file Memory.h.
Referenced by AllocatedBlock(), CalculateChunksNeededForSize(), GetChunkSize(), and ReserveBlock().
m_free_blocks
RangeVector<lldb::addr_t, uint32_t> lldb_private::AllocatedBlock::m_free_blocks protected
Definition at line 106 of file Memory.h.
Referenced by AllocatedBlock(), FreeBlock(), and ReserveBlock().
m_permissions
const uint32_t lldb_private::AllocatedBlock::m_permissions protected
Definition at line 102 of file Memory.h.
Referenced by AllocatedBlock(), and GetPermissions().
m_range
Range<lldb::addr_t, uint32_t> lldb_private::AllocatedBlock::m_range protected
Definition at line 100 of file Memory.h.
Referenced by AllocatedBlock(), Contains(), GetBaseAddress(), and GetByteSize().
m_reserved_blocks
RangeVector<lldb::addr_t, uint32_t> lldb_private::AllocatedBlock::m_reserved_blocks protected
Definition at line 108 of file Memory.h.
Referenced by FreeBlock(), and ReserveBlock().
The documentation for this class was generated from the following files:
Memory.h
Memory.cpp