LLDB: lldb_private::OptionGroupWatchpoint Class Reference
lldb_private::OptionGroupWatchpoint Class Reference
#include <OptionGroupWatchpoint.h>
Public Types
enum WatchType {
eWatchInvalid = 0 , eWatchRead , eWatchWrite , eWatchModify ,
eWatchReadWrite
}
eWatchRead == LLDB_WATCH_TYPE_READ eWatchWrite == LLDB_WATCH_TYPE_WRITE eWatchModify == LLDB_WATCH_TYPE_MODIFY eWatchReadWrite == LLDB_WATCH_TYPE_READ | LLDB_WATCH_TYPE_WRITE
Public Member Functions
OptionGroupWatchpoint ()=default
~OptionGroupWatchpoint () override=default
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext *execution_context) override
void OptionParsingStarting (ExecutionContext *execution_context) override
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Public Attributes
WatchType watch_type
OptionValueUInt64 watch_size
bool watch_type_specified
lldb::LanguageType language_type
Private Member Functions
OptionGroupWatchpoint (const OptionGroupWatchpoint &)=delete
const OptionGroupWatchpoint & operator= (const OptionGroupWatchpoint &)=delete
Detailed Description
Definition at line 19 of file OptionGroupWatchpoint.h.
Member Enumeration Documentation
WatchType
enum lldb_private::OptionGroupWatchpoint::WatchType
eWatchRead == LLDB_WATCH_TYPE_READ eWatchWrite == LLDB_WATCH_TYPE_WRITE eWatchModify == LLDB_WATCH_TYPE_MODIFY eWatchReadWrite == LLDB_WATCH_TYPE_READ | LLDB_WATCH_TYPE_WRITE
Enumerator
eWatchInvalid
eWatchRead
eWatchWrite
eWatchModify
eWatchReadWrite
Definition at line 36 of file OptionGroupWatchpoint.h.
Constructor & Destructor Documentation
OptionGroupWatchpoint() [1/2]
lldb_private::OptionGroupWatchpoint::OptionGroupWatchpoint () default
Referenced by operator=(), and OptionGroupWatchpoint().
~OptionGroupWatchpoint()
lldb_private::OptionGroupWatchpoint::~OptionGroupWatchpoint () override default
OptionGroupWatchpoint() [2/2]
lldb_private::OptionGroupWatchpoint::OptionGroupWatchpoint (const OptionGroupWatchpoint &) private delete
References OptionGroupWatchpoint().
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > OptionGroupWatchpoint::GetDefinitions () override virtual
Implements lldb_private::OptionGroup.
Definition at line 111 of file OptionGroupWatchpoint.cpp.
References g_option_table.
operator=()
const OptionGroupWatchpoint & lldb_private::OptionGroupWatchpoint::operator= (const OptionGroupWatchpoint &) private delete
References OptionGroupWatchpoint().
OptionParsingStarting()
void OptionGroupWatchpoint::OptionParsingStarting (ExecutionContext * execution_context) override virtual
Implements lldb_private::OptionGroup.
Definition at line 103 of file OptionGroupWatchpoint.cpp.
References lldb::eLanguageTypeUnknown, eWatchInvalid, language_type, watch_size, watch_type, and watch_type_specified.
SetOptionValue()
Status OptionGroupWatchpoint::SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext * execution_context) override virtual
Implements lldb_private::OptionGroup.
Definition at line 61 of file OptionGroupWatchpoint.cpp.
References lldb::eLanguageTypeUnknown, error(), lldb_private::Status::FromErrorStringWithFormat(), g_option_table, lldb_private::Language::GetLanguageTypeFromString(), lldb_private::StreamString::GetString(), language_type, lldb_private::Stream::Printf(), lldb_private::Language::PrintSupportedLanguagesForExpressions(), lldb_private::Status, lldb_private::OptionArgParser::ToOptionEnum(), watch_size, watch_type, and watch_type_specified.
Member Data Documentation
language_type
lldb::LanguageType lldb_private::OptionGroupWatchpoint::language_type
Definition at line 47 of file OptionGroupWatchpoint.h.
Referenced by OptionParsingStarting(), and SetOptionValue().
watch_size
OptionValueUInt64 lldb_private::OptionGroupWatchpoint::watch_size
Definition at line 45 of file OptionGroupWatchpoint.h.
Referenced by OptionParsingStarting(), and SetOptionValue().
watch_type
WatchType lldb_private::OptionGroupWatchpoint::watch_type
Definition at line 44 of file OptionGroupWatchpoint.h.
Referenced by OptionParsingStarting(), and SetOptionValue().
watch_type_specified
bool lldb_private::OptionGroupWatchpoint::watch_type_specified
Definition at line 46 of file OptionGroupWatchpoint.h.
Referenced by OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following files:
OptionGroupWatchpoint.h
OptionGroupWatchpoint.cpp