LLDB: lldb_private::RegisterTypeBuilderClang Class Reference
lldb_private::RegisterTypeBuilderClang Class Reference
#include <RegisterTypeBuilderClang.h>
Public Member Functions
RegisterTypeBuilderClang (Target &target)
llvm::StringRef GetPluginName () override
CompilerType GetRegisterType (const std::string &name, const lldb_private::RegisterFlags &flags, uint32_t byte_size) override
Public Member Functions inherited from lldb_private::RegisterTypeBuilder
~RegisterTypeBuilder () override=default
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static lldb::RegisterTypeBuilderSP CreateInstance (Target &target)
Private Attributes
Target & m_target
Additional Inherited Members
Protected Member Functions inherited from lldb_private::RegisterTypeBuilder
RegisterTypeBuilder ()=default
Detailed Description
Definition at line 16 of file RegisterTypeBuilderClang.h.
Constructor & Destructor Documentation
RegisterTypeBuilderClang()
RegisterTypeBuilderClang::RegisterTypeBuilderClang (Target & target)
Definition at line 36 of file RegisterTypeBuilderClang.cpp.
References m_target.
Referenced by Initialize().
Member Function Documentation
CreateInstance()
lldb::RegisterTypeBuilderSP RegisterTypeBuilderClang::CreateInstance (Target & target) static
Definition at line 32 of file RegisterTypeBuilderClang.cpp.
Referenced by Initialize().
GetPluginDescriptionStatic()
llvm::StringRef lldb_private::RegisterTypeBuilderClang::GetPluginDescriptionStatic () inline static
Definition at line 26 of file RegisterTypeBuilderClang.h.
Referenced by Initialize().
GetPluginName()
llvm::StringRef lldb_private::RegisterTypeBuilderClang::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 25 of file RegisterTypeBuilderClang.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::RegisterTypeBuilderClang::GetPluginNameStatic () inline static
Definition at line 22 of file RegisterTypeBuilderClang.h.
Referenced by GetPluginName(), and Initialize().
GetRegisterType()
CompilerType RegisterTypeBuilderClang::GetRegisterType (const std::string & name, const lldb_private::RegisterFlags & flags, uint32_t byte_size) override virtual
Implements lldb_private::RegisterTypeBuilder.
Definition at line 39 of file RegisterTypeBuilderClang.cpp.
References lldb::eAccessPublic, lldb::eEncodingUint, lldb::eLanguageTypeC, lldb_private::CompilerType::GetByteSize(), lldb_private::RegisterFlags::GetFields(), lldb_private::ScratchTypeSystemClang::GetForTarget(), lldb_private::RegisterFlags::GetSize(), and m_target.
Initialize()
void RegisterTypeBuilderClang::Initialize () static
Definition at line 21 of file RegisterTypeBuilderClang.cpp.
References CreateInstance(), GetPluginDescriptionStatic(), GetPluginNameStatic(), Initialize(), lldb_private::PluginManager::RegisterPlugin(), and RegisterTypeBuilderClang().
Referenced by Initialize().
Terminate()
void RegisterTypeBuilderClang::Terminate () static
Definition at line 29 of file RegisterTypeBuilderClang.cpp.
Member Data Documentation
m_target
Target& lldb_private::RegisterTypeBuilderClang::m_target private
Definition at line 36 of file RegisterTypeBuilderClang.h.
Referenced by GetRegisterType(), and RegisterTypeBuilderClang().
The documentation for this class was generated from the following files:
RegisterTypeBuilderClang.h
RegisterTypeBuilderClang.cpp