LLDB: lldb_private::DiagnosticManager Class Reference
lldb_private::DiagnosticManager Class Reference
#include <DiagnosticManager.h>
Public Member Functions
void Clear ()
const DiagnosticList & Diagnostics () const
DiagnosticList & Diagnostics ()
bool HasFixIts () const
void AddDiagnostic (llvm::StringRef message, lldb::Severity severity, DiagnosticOrigin origin, uint32_t compiler_id=LLDB_INVALID_COMPILER_ID)
void AddDiagnostic (std::unique_ptr< Diagnostic > diagnostic)
void Consume (DiagnosticManager &&other)
Moves over the contents of a second diagnostic manager over.
size_t Printf (lldb::Severity severity, const char *format,...) __attribute__((format(printf
size_t void PutString (lldb::Severity severity, llvm::StringRef str)
void AppendMessageToDiagnostic (llvm::StringRef str)
llvm::Error GetAsError (lldb::ExpressionResults result, llvm::Twine message={}) const
Returns an ExpressionError with arg as error code.
std::string GetString (char separator='\n')
void Dump (Log *log)
const std::string & GetFixedExpression ()
void SetFixedExpression (std::string fixed_expression)
Protected Attributes
DiagnosticList m_diagnostics
std::string m_fixed_expression
Detailed Description
Definition at line 103 of file DiagnosticManager.h.
Member Function Documentation
AddDiagnostic() [1/2]
void DiagnosticManager::AddDiagnostic (llvm::StringRef message, lldb::Severity severity, DiagnosticOrigin origin, uint32_t compiler_id = LLDB_INVALID_COMPILER_ID)
Definition at line 119 of file DiagnosticManager.cpp.
References m_diagnostics.
Referenced by lldb_private::UserExpression::Evaluate(), Printf(), PutString(), and SetupLangOpts().
AddDiagnostic() [2/2]
void lldb_private::DiagnosticManager::AddDiagnostic (std::unique_ptr< Diagnostic > diagnostic) inline
Definition at line 124 of file DiagnosticManager.h.
References m_diagnostics.
AppendMessageToDiagnostic()
void lldb_private::DiagnosticManager::AppendMessageToDiagnostic (llvm::StringRef str) inline
Definition at line 142 of file DiagnosticManager.h.
References AppendMessageToDiagnostic(), and m_diagnostics.
Referenced by AppendMessageToDiagnostic(), lldb_private::LLVMUserExpression::DoExecute(), and lldb_private::ClangExpressionParser::ParseInternal().
Clear()
void lldb_private::DiagnosticManager::Clear () inline
Definition at line 105 of file DiagnosticManager.h.
References m_diagnostics, and m_fixed_expression.
Referenced by lldb_private::BreakpointLocation::ConditionSaysStop(), lldb_private::PlatformWindows::DoLoadImage(), lldb_private::UserExpression::Evaluate(), lldb_private::UtilityFunction::MakeFunctionCaller(), lldb_private::AppleGetItemInfoHandler::SetupGetItemInfoFunction(), lldb_private::AppleGetPendingItemsHandler::SetupGetPendingItemsFunction(), lldb_private::AppleGetQueuesHandler::SetupGetQueuesFunction(), and lldb_private::AppleGetThreadItemInfoHandler::SetupGetThreadItemInfoFunction().
Consume()
void lldb_private::DiagnosticManager::Consume (DiagnosticManager && other) inline
Moves over the contents of a second diagnostic manager over.
Leaves other diagnostic manager in an empty state.
Definition at line 131 of file DiagnosticManager.h.
References m_diagnostics, and m_fixed_expression.
Diagnostics() [1/2]
DiagnosticList & lldb_private::DiagnosticManager::Diagnostics () inline
Definition at line 111 of file DiagnosticManager.h.
References m_diagnostics.
Diagnostics() [2/2]
const DiagnosticList & lldb_private::DiagnosticManager::Diagnostics () const inline
Definition at line 110 of file DiagnosticManager.h.
References m_diagnostics.
Referenced by lldb_private::UserExpression::Evaluate(), lldb_private::ClangUserExpression::FixupCVRParseErrorDiagnostics(), lldb_private::ClangUserExpression::FixupTemplateLookupDiagnostics(), GetString(), and lldb_private::ClangExpressionParser::RewriteExpression().
Dump()
void DiagnosticManager::Dump (Log * log)
Definition at line 96 of file DiagnosticManager.cpp.
References GetString(), and lldb_private::Log::PutString().
Referenced by lldb_private::AppleObjCTrampolineHandler::SetupDispatchFunction(), lldb_private::AppleGetItemInfoHandler::SetupGetItemInfoFunction(), lldb_private::AppleGetPendingItemsHandler::SetupGetPendingItemsFunction(), lldb_private::AppleGetQueuesHandler::SetupGetQueuesFunction(), and lldb_private::AppleGetThreadItemInfoHandler::SetupGetThreadItemInfoFunction().
GetAsError()
llvm::Error DiagnosticManager::GetAsError (lldb::ExpressionResults result, llvm::Twine message = {}) const
Returns an ExpressionError with arg as error code.
Definition at line 111 of file DiagnosticManager.cpp.
References m_diagnostics.
Referenced by lldb_private::BreakpointLocation::ConditionSaysStop(), lldb_private::Target::CreateUtilityFunction(), lldb_private::PlatformWindows::DoLoadImage(), lldb_private::ClangExpressionParser::DoPrepareForExecution(), lldb_private::UserExpression::Evaluate(), lldb_private::UtilityFunction::MakeFunctionCaller(), and lldb_private::ExpressionParser::RunStaticInitializers().
GetFixedExpression()
const std::string & lldb_private::DiagnosticManager::GetFixedExpression () inline
Definition at line 160 of file DiagnosticManager.h.
References m_fixed_expression.
Referenced by lldb_private::ClangUserExpression::TryParse().
GetString()
std::string DiagnosticManager::GetString (char separator = '\n')
Definition at line 77 of file DiagnosticManager.cpp.
References Diagnostics(), and StringForSeverity().
Referenced by Dump().
HasFixIts()
bool lldb_private::DiagnosticManager::HasFixIts () const inline
Definition at line 113 of file DiagnosticManager.h.
References m_diagnostics.
Referenced by lldb_private::ClangUserExpression::TryParse().
Printf()
size_t DiagnosticManager::Printf (lldb::Severity severity, const char * format, ...)
Definition at line 128 of file DiagnosticManager.cpp.
References AddDiagnostic(), lldb_private::eDiagnosticOriginLLDB, lldb_private::StreamString::GetString(), and lldb_private::Stream::PrintfVarArg().
Referenced by lldb_private::ClangUserExpression::AddArguments(), lldb_private::ClangFunctionCaller::CompileFunction(), lldb_private::LLVMUserExpression::DoExecute(), lldb_private::LLVMUserExpression::FinalizeJITExecution(), lldb_private::ClangUtilityFunction::Install(), lldb_private::LLVMUserExpression::PrepareToExecuteJITExpression(), lldb_private::Process::RunThreadPlan(), lldb_private::FunctionCaller::WriteFunctionArguments(), and lldb_private::FunctionCaller::WriteFunctionWrapper().
PutString()
void DiagnosticManager::PutString (lldb::Severity severity, llvm::StringRef str)
Definition at line 142 of file DiagnosticManager.cpp.
References AddDiagnostic(), and lldb_private::eDiagnosticOriginLLDB.
Referenced by lldb_private::ClangUserExpression::AddArguments(), lldb_private::ClangFunctionCaller::CompileFunction(), lldb_private::ClangUserExpression::Complete(), lldb_private::ClangUserExpression::CreateSourceCode(), lldb_private::LLVMUserExpression::DoExecute(), lldb_private::FunctionCaller::GetThreadPlanToCallFunction(), lldb_private::FunctionCaller::InsertFunction(), lldb_private::ClangUtilityFunction::Install(), lldb_private::ClangUserExpression::Parse(), lldb_private::ClangExpressionParser::ParseInternal(), lldb_private::ClangUserExpression::PrepareForParsing(), lldb_private::LLVMUserExpression::PrepareToExecuteJITExpression(), lldb_private::Process::RunThreadPlan(), lldb_private::ClangUserExpression::SetupPersistentState(), lldb_private::ClangUserExpression::TryParse(), and lldb_private::FunctionCaller::WriteFunctionArguments().
SetFixedExpression()
void lldb_private::DiagnosticManager::SetFixedExpression (std::string fixed_expression) inline
Definition at line 163 of file DiagnosticManager.h.
References m_fixed_expression.
Referenced by lldb_private::ClangExpressionParser::RewriteExpression().
Member Data Documentation
m_diagnostics
DiagnosticList lldb_private::DiagnosticManager::m_diagnostics protected
Definition at line 168 of file DiagnosticManager.h.
Referenced by AddDiagnostic(), AddDiagnostic(), AppendMessageToDiagnostic(), Clear(), Consume(), Diagnostics(), Diagnostics(), GetAsError(), and HasFixIts().
m_fixed_expression
std::string lldb_private::DiagnosticManager::m_fixed_expression protected
Definition at line 169 of file DiagnosticManager.h.
Referenced by Clear(), Consume(), GetFixedExpression(), and SetFixedExpression().
The documentation for this class was generated from the following files:
DiagnosticManager.h
DiagnosticManager.cpp