LLDB: lldb::SBSymbolContextList Class Reference
lldb::SBSymbolContextList Class Reference
#include <SBSymbolContextList.h>
Public Member Functions
SBSymbolContextList ()
SBSymbolContextList (const lldb::SBSymbolContextList &rhs)
~SBSymbolContextList ()
const lldb::SBSymbolContextList & operator= (const lldb::SBSymbolContextList &rhs)
operator bool () const
bool IsValid () const
uint32_t GetSize () const
lldb::SBSymbolContext GetContextAtIndex (uint32_t idx)
bool GetDescription (lldb::SBStream &description)
void Append (lldb::SBSymbolContext &sc)
void Append (lldb::SBSymbolContextList &sc_list)
void Clear ()
Protected Member Functions
lldb_private::SymbolContextList * operator-> () const
lldb_private::SymbolContextList & operator* () const
Private Attributes
std::unique_ptr< lldb_private::SymbolContextList > m_opaque_up
Friends
class SBModule
class SBTarget
class SBCompileUnit
Detailed Description
Definition at line 17 of file SBSymbolContextList.h.
Constructor & Destructor Documentation
SBSymbolContextList() [1/2]
SBSymbolContextList::SBSymbolContextList ()
Definition at line 18 of file SBSymbolContextList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by Append(), operator=(), and SBSymbolContextList().
SBSymbolContextList() [2/2]
SBSymbolContextList::SBSymbolContextList (const lldb::SBSymbolContextList & rhs)
Definition at line 23 of file SBSymbolContextList.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBSymbolContextList().
~SBSymbolContextList()
SBSymbolContextList::~SBSymbolContextList () default
References Append(), Clear(), GetContextAtIndex(), GetDescription(), GetSize(), IsValid(), and operator=().
Member Function Documentation
Append() [1/2]
void SBSymbolContextList::Append (lldb::SBSymbolContext & sc)
Definition at line 67 of file SBSymbolContextList.cpp.
References lldb::SBSymbolContext::IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBSymbolContextList().
Append() [2/2]
void SBSymbolContextList::Append (lldb::SBSymbolContextList & sc_list)
Definition at line 74 of file SBSymbolContextList.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBSymbolContextList().
Clear()
void SBSymbolContextList::Clear ()
Definition at line 60 of file SBSymbolContextList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBSymbolContextList().
GetContextAtIndex()
SBSymbolContext SBSymbolContextList::GetContextAtIndex (uint32_t idx)
Definition at line 48 of file SBSymbolContextList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBSymbolContextList().
GetDescription()
bool SBSymbolContextList::GetDescription (lldb::SBStream & description)
Definition at line 100 of file SBSymbolContextList.cpp.
References lldb::eDescriptionLevelFull, LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBStream::ref().
Referenced by ~SBSymbolContextList().
GetSize()
uint32_t SBSymbolContextList::GetSize () const
Definition at line 40 of file SBSymbolContextList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBSymbolContextList().
IsValid()
bool SBSymbolContextList::IsValid () const
Definition at line 81 of file SBSymbolContextList.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by Append(), and ~SBSymbolContextList().
operator bool()
SBSymbolContextList::operator bool () const explicit
Definition at line 85 of file SBSymbolContextList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
operator*()
lldb_private::SymbolContextList & SBSymbolContextList::operator* () const protected
Definition at line 95 of file SBSymbolContextList.cpp.
References m_opaque_up.
Referenced by SBCompileUnit.
operator->()
lldb_private::SymbolContextList * SBSymbolContextList::operator-> () const protected
Definition at line 91 of file SBSymbolContextList.cpp.
References m_opaque_up.
Referenced by SBCompileUnit.
operator=()
const SBSymbolContextList & SBSymbolContextList::operator= (const lldb::SBSymbolContextList & rhs)
Definition at line 31 of file SBSymbolContextList.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBSymbolContextList().
Referenced by ~SBSymbolContextList().
Friends And Related Symbol Documentation
SBCompileUnit
friend class SBCompileUnit friend
Definition at line 47 of file SBSymbolContextList.h.
References operator*(), operator->(), and SBCompileUnit.
Referenced by SBCompileUnit.
SBModule
friend class SBModule friend
Definition at line 45 of file SBSymbolContextList.h.
References SBModule.
Referenced by SBModule.
SBTarget
friend class SBTarget friend
Definition at line 46 of file SBSymbolContextList.h.
References SBTarget.
Referenced by SBTarget.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::SymbolContextList> lldb::SBSymbolContextList::m_opaque_up private
Definition at line 54 of file SBSymbolContextList.h.
Referenced by Append(), Append(), Clear(), GetContextAtIndex(), GetDescription(), GetSize(), operator bool(), operator*(), operator->(), operator=(), SBSymbolContextList(), and SBSymbolContextList().
The documentation for this class was generated from the following files:
SBSymbolContextList.h
SBSymbolContextList.cpp