LLDB: lldb_private::AssertFrameRecognizer Class Reference
lldb_private::AssertFrameRecognizer Class Reference
When a thread stops, it checks depending on the platform if the top frame is an abort stack frame.
#include <AssertFrameRecognizer.h>
Public Member Functions
std::string GetName () override
lldb::RecognizedStackFrameSP RecognizeFrame (lldb::StackFrameSP frame_sp) override
Public Member Functions inherited from lldb_private::StackFrameRecognizer
virtual ~StackFrameRecognizer ()=default
Detailed Description
When a thread stops, it checks depending on the platform if the top frame is an abort stack frame.
If so, it looks for an assert stack frame in the upper frames and set it as the most relavant frame when found.
Definition at line 45 of file AssertFrameRecognizer.h.
Member Function Documentation
GetName()
std::string lldb_private::AssertFrameRecognizer::GetName () inline override virtual
Reimplemented from lldb_private::StackFrameRecognizer.
Definition at line 47 of file AssertFrameRecognizer.h.
RecognizeFrame()
lldb::RecognizedStackFrameSP AssertFrameRecognizer::RecognizeFrame (lldb::StackFrameSP frame_sp) override virtual
Reimplemented from lldb_private::StackFrameRecognizer.
Definition at line 123 of file AssertFrameRecognizer.cpp.
References lldb_private::Target::GetArchitecture(), lldb_private::GetAssertLocation(), lldb_private::SymbolContext::GetFunctionName(), lldb_private::GetLog(), lldb_private::ArchSpec::GetTriple(), LLDB_LOG, lldb_private::SymbolContext::module_sp, lldb_private::SymbolLocation::module_spec, lldb_private::SymbolLocation::symbols, and lldb_private::Unwind.
The documentation for this class was generated from the following files:
AssertFrameRecognizer.h
AssertFrameRecognizer.cpp