LLDB: lldb_private::Language::ImageListTypeScavenger Class Reference
lldb_private::Language::ImageListTypeScavenger Class Reference abstract
#include <Language.h>
Classes
class Result
Protected Member Functions
ImageListTypeScavenger ()=default
~ImageListTypeScavenger () override=default
virtual CompilerType AdjustForInclusion (CompilerType &candidate)=0
bool Find_Impl (ExecutionContextScope *exe_scope, const char *key, ResultSet &results) override
Protected Member Functions inherited from lldb_private::Language::TypeScavenger
TypeScavenger ()=default
Additional Inherited Members
Public Types inherited from lldb_private::Language::TypeScavenger
typedef std::set< std::unique_ptr< Result > > ResultSet
Public Member Functions inherited from lldb_private::Language::TypeScavenger
virtual ~TypeScavenger ()=default
size_t Find (ExecutionContextScope *exe_scope, const char *key, ResultSet &results, bool append=true)
Detailed Description
Definition at line 67 of file Language.h.
Constructor & Destructor Documentation
ImageListTypeScavenger()
lldb_private::Language::ImageListTypeScavenger::ImageListTypeScavenger () protected default
~ImageListTypeScavenger()
lldb_private::Language::ImageListTypeScavenger::~ImageListTypeScavenger () override protected default
Member Function Documentation
AdjustForInclusion()
virtual CompilerType lldb_private::Language::ImageListTypeScavenger::AdjustForInclusion (CompilerType & candidate) protected pure virtual
Referenced by Find_Impl().
Find_Impl()
bool Language::ImageListTypeScavenger::Find_Impl (ExecutionContextScope * exe_scope, const char * key, ResultSet & results) override protected virtual
Implements lldb_private::Language::TypeScavenger.
Definition at line 508 of file Language.cpp.
References AdjustForInclusion(), lldb_private::ExecutionContextScope::CalculateTarget(), lldb_private::Target::GetImages(), lldb_private::TypeResults::GetTypeMap(), and lldb_private::TypeMap::Types().
The documentation for this class was generated from the following files:
Language.h
Language.cpp