LLDB: lldb_private::transport::IOTransport< Proto > Class Template Reference
lldb_private::transport::IOTransport< Proto > Class Template Reference abstract
An IOTransport sends and receives messages using an IOObject.
#include <JSONTransport.h>
Public Types
using Message = typename JSONTransport<Proto>::Message
using MessageHandler = typename JSONTransport<Proto>::MessageHandler
Public Types inherited from lldb_private::transport::JSONTransport< Proto >
using Req = typename Proto::Req
using Resp = typename Proto::Resp
using Evt = typename Proto::Evt
using Message = std::variant<Req, Resp, Evt>
Public Member Functions
IOTransport (MainLoop &loop, lldb::IOObjectSP in, lldb::IOObjectSP out)
llvm::Error Send (const typename Proto::Evt &evt) override
llvm::Error Send (const typename Proto::Req &req) override
llvm::Error Send (const typename Proto::Resp &resp) override
llvm::Error RegisterMessageHandler (MessageHandler &handler) override
RegisterMessageHandler registers the Transport with the given MainLoop and handles any incoming messages using the given MessageHandler.
Public Member Functions inherited from lldb_private::transport::JSONTransport< Proto >
virtual ~JSONTransport ()=default
virtual llvm::Error Send (const Evt &)=0
Sends an event, a message that does not require a response.
virtual llvm::Error Send (const Req &)=0
Sends a request, a message that expects a response.
virtual llvm::Error Send (const Resp &)=0
Sends a response to a specific request.
Static Public Attributes
static constexpr size_t kReadBufferSize = 1024
Public for testing purposes, otherwise this should be an implementation detail.
Protected Member Functions
llvm::Error Write (const llvm::json::Value &message)
virtual llvm::Expected< std::vector< std::string > > Parse ()=0
virtual std::string Encode (const llvm::json::Value &message)=0
Protected Member Functions inherited from lldb_private::transport::JSONTransport< Proto >
template<typename... Ts>
auto Logv (const char *Fmt, Ts &&...Vals)
virtual void Log (llvm::StringRef message)=0
Protected Attributes
llvm::SmallString< kReadBufferSize > m_buffer
Private Member Functions
void OnRead (MainLoopBase &loop, MessageHandler &handler)
Private Attributes
MainLoop & m_loop
lldb::IOObjectSP m_in
lldb::IOObjectSP m_out
MainLoop::ReadHandleUP m_read_handle
Detailed Description
template<typename Proto>
class lldb_private::transport::IOTransport< Proto >
An IOTransport sends and receives messages using an IOObject.
Definition at line 179 of file JSONTransport.h.
Member Typedef Documentation
Message
template<typename Proto> using lldb_private::transport::IOTransport< Proto >::Message = typename JSONTransport<Proto>::Message
Definition at line 181 of file JSONTransport.h.
MessageHandler
template<typename Proto> using lldb_private::transport::IOTransport< Proto >::MessageHandler = typename JSONTransport<Proto>::MessageHandler
Definition at line 182 of file JSONTransport.h.
Constructor & Destructor Documentation
IOTransport()
template<typename Proto> lldb_private::transport::IOTransport< Proto >::IOTransport (MainLoop & loop, lldb::IOObjectSP in, lldb::IOObjectSP out) inline
Definition at line 184 of file JSONTransport.h.
References m_in, m_loop, and m_out.
Member Function Documentation
Encode()
template<typename Proto> virtual std::string lldb_private::transport::IOTransport< Proto >::Encode (const llvm::json::Value & message) protected pure virtual
Implemented in lldb_private::transport::HTTPDelimitedJSONTransport< Proto >, lldb_private::transport::JSONRPCTransport< Proto >, and lldb_private::transport::JSONRPCTransport< ProtocolDescriptor >.
Referenced by Write().
OnRead()
template<typename Proto> void lldb_private::transport::IOTransport< Proto >::OnRead (MainLoopBase & loop, MessageHandler & handler) inline private
Definition at line 225 of file JSONTransport.h.
References error(), kReadBufferSize, m_buffer, m_in, m_read_handle, and Parse().
Referenced by RegisterMessageHandler().
Parse()
template<typename Proto> virtual llvm::Expected< std::vector< std::string > > lldb_private::transport::IOTransport< Proto >::Parse () protected pure virtual
Implemented in lldb_private::transport::HTTPDelimitedJSONTransport< Proto >, lldb_private::transport::JSONRPCTransport< Proto >, and lldb_private::transport::JSONRPCTransport< ProtocolDescriptor >.
Referenced by OnRead().
RegisterMessageHandler()
template<typename Proto> llvm::Error lldb_private::transport::IOTransport< Proto >::RegisterMessageHandler (MessageHandler & handler) inline override virtual
RegisterMessageHandler registers the Transport with the given MainLoop and handles any incoming messages using the given MessageHandler.
If an unexpected error occurs, the MainLoop will be terminated and a log message will include additional information about the termination reason.
Implements lldb_private::transport::JSONTransport< Proto >.
Definition at line 199 of file JSONTransport.h.
References m_in, m_loop, m_read_handle, OnRead(), and lldb_private::Status::takeError().
Send() [1/3]
template<typename Proto> llvm::Error lldb_private::transport::IOTransport< Proto >::Send (const typename Proto::Evt & evt) inline override
Definition at line 187 of file JSONTransport.h.
References Write().
Send() [2/3]
template<typename Proto> llvm::Error lldb_private::transport::IOTransport< Proto >::Send (const typename Proto::Req & req) inline override
Definition at line 191 of file JSONTransport.h.
References Write().
Send() [3/3]
template<typename Proto> llvm::Error lldb_private::transport::IOTransport< Proto >::Send (const typename Proto::Resp & resp) inline override
Definition at line 195 of file JSONTransport.h.
References Write().
Write()
template<typename Proto> llvm::Error lldb_private::transport::IOTransport< Proto >::Write (const llvm::json::Value & message) inline protected
Definition at line 212 of file JSONTransport.h.
References Encode(), lldb_private::transport::JSONTransport< Proto >::Logv(), and m_out.
Referenced by Send(), Send(), and Send().
Member Data Documentation
kReadBufferSize
template<typename Proto> size_t lldb_private::transport::IOTransport< Proto >::kReadBufferSize = 1024 static constexpr
Public for testing purposes, otherwise this should be an implementation detail.
Definition at line 209 of file JSONTransport.h.
Referenced by OnRead().
m_buffer
template<typename Proto> llvm::SmallString<kReadBufferSize> lldb_private::transport::IOTransport< Proto >::m_buffer protected
Definition at line 222 of file JSONTransport.h.
Referenced by OnRead(), lldb_private::transport::HTTPDelimitedJSONTransport< Proto >::Parse(), and lldb_private::transport::JSONRPCTransport< Proto >::Parse().
m_in
template<typename Proto> lldb::IOObjectSP lldb_private::transport::IOTransport< Proto >::m_in private
Definition at line 269 of file JSONTransport.h.
Referenced by IOTransport(), OnRead(), and RegisterMessageHandler().
m_loop
template<typename Proto> MainLoop& lldb_private::transport::IOTransport< Proto >::m_loop private
Definition at line 268 of file JSONTransport.h.
Referenced by IOTransport(), and RegisterMessageHandler().
m_out
template<typename Proto> lldb::IOObjectSP lldb_private::transport::IOTransport< Proto >::m_out private
Definition at line 270 of file JSONTransport.h.
Referenced by IOTransport(), and Write().
m_read_handle
template<typename Proto> MainLoop::ReadHandleUP lldb_private::transport::IOTransport< Proto >::m_read_handle private
Definition at line 271 of file JSONTransport.h.
Referenced by OnRead(), and RegisterMessageHandler().
The documentation for this class was generated from the following file:
JSONTransport.h