LLDB: lldb_private::AppleObjCRuntimeV2::ClassInfoExtractor Class Reference
lldb_private::AppleObjCRuntimeV2::ClassInfoExtractor Class Reference
Abstraction to read the Objective-C class info.
Public Member Functions
ClassInfoExtractor (AppleObjCRuntimeV2 &runtime)
std::mutex & GetMutex ()
Protected Attributes
AppleObjCRuntimeV2 & m_runtime
The lifetime of this object is tied to that of the runtime.
std::mutex m_mutex
Detailed Description
Abstraction to read the Objective-C class info.
Definition at line 312 of file AppleObjCRuntimeV2.h.
Constructor & Destructor Documentation
ClassInfoExtractor()
lldb_private::AppleObjCRuntimeV2::ClassInfoExtractor::ClassInfoExtractor (AppleObjCRuntimeV2 & runtime) inline
Definition at line 314 of file AppleObjCRuntimeV2.h.
References lldb_private::AppleObjCRuntimeV2::AppleObjCRuntimeV2(), and m_runtime.
Referenced by lldb_private::AppleObjCRuntimeV2::DynamicClassInfoExtractor::DynamicClassInfoExtractor(), and lldb_private::AppleObjCRuntimeV2::SharedCacheClassInfoExtractor::SharedCacheClassInfoExtractor().
Member Function Documentation
GetMutex()
std::mutex & lldb_private::AppleObjCRuntimeV2::ClassInfoExtractor::GetMutex () inline
Definition at line 315 of file AppleObjCRuntimeV2.h.
References m_mutex.
Member Data Documentation
m_mutex
std::mutex lldb_private::AppleObjCRuntimeV2::ClassInfoExtractor::m_mutex protected
Definition at line 320 of file AppleObjCRuntimeV2.h.
Referenced by GetMutex().
m_runtime
AppleObjCRuntimeV2& lldb_private::AppleObjCRuntimeV2::ClassInfoExtractor::m_runtime protected
The lifetime of this object is tied to that of the runtime.
Definition at line 319 of file AppleObjCRuntimeV2.h.
Referenced by ClassInfoExtractor().
The documentation for this class was generated from the following file:
AppleObjCRuntimeV2.h