LLDB: lldb::SBBroadcaster Class Reference
lldb::SBBroadcaster Class Reference
#include <SBBroadcaster.h>
Public Member Functions
SBBroadcaster ()
SBBroadcaster (const char *name)
SBBroadcaster (const SBBroadcaster &rhs)
const SBBroadcaster & operator= (const SBBroadcaster &rhs)
~SBBroadcaster ()
operator bool () const
bool IsValid () const
void Clear ()
void BroadcastEventByType (uint32_t event_type, bool unique=false)
void BroadcastEvent (const lldb::SBEvent &event, bool unique=false)
void AddInitialEventsToListener (const lldb::SBListener &listener, uint32_t requested_events)
uint32_t AddListener (const lldb::SBListener &listener, uint32_t event_mask)
const char * GetName () const
bool EventTypeHasListeners (uint32_t event_type)
bool RemoveListener (const lldb::SBListener &listener, uint32_t event_mask=UINT32_MAX)
bool operator== (const lldb::SBBroadcaster &rhs) const
bool operator!= (const lldb::SBBroadcaster &rhs) const
bool operator< (const lldb::SBBroadcaster &rhs) const
Protected Member Functions
SBBroadcaster (lldb_private::Broadcaster *broadcaster, bool owns)
lldb_private::Broadcaster * get () const
void reset (lldb_private::Broadcaster *broadcaster, bool owns)
Private Attributes
lldb::BroadcasterSP m_opaque_sp
lldb_private::Broadcaster * m_opaque_ptr = nullptr
Friends
class SBCommandInterpreter
class SBCommunication
class SBDebugger
class SBEvent
class SBListener
class SBProcess
class SBTarget
Detailed Description
Definition at line 16 of file SBBroadcaster.h.
Constructor & Destructor Documentation
SBBroadcaster() [1/4]
SBBroadcaster::SBBroadcaster ()
Definition at line 19 of file SBBroadcaster.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by operator!=(), operator<(), operator=(), operator==(), SBBroadcaster(), and SBTarget.
SBBroadcaster() [2/4]
SBBroadcaster::SBBroadcaster (const char * name)
Definition at line 21 of file SBBroadcaster.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and m_opaque_sp.
SBBroadcaster() [3/4]
SBBroadcaster::SBBroadcaster (const SBBroadcaster & rhs)
Definition at line 31 of file SBBroadcaster.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, m_opaque_sp, and SBBroadcaster().
~SBBroadcaster()
SBBroadcaster::~SBBroadcaster ()
Definition at line 46 of file SBBroadcaster.cpp.
References reset().
SBBroadcaster() [4/4]
SBBroadcaster::SBBroadcaster (lldb_private::Broadcaster * broadcaster, bool owns) protected
Definition at line 28 of file SBBroadcaster.cpp.
References m_opaque_ptr, and m_opaque_sp.
Member Function Documentation
AddInitialEventsToListener()
void SBBroadcaster::AddInitialEventsToListener (const lldb::SBListener & listener, uint32_t requested_events)
Definition at line 73 of file SBBroadcaster.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, lldb::SBListener::m_opaque_sp, and SBListener.
AddListener()
uint32_t SBBroadcaster::AddListener (const lldb::SBListener & listener, uint32_t event_mask)
Definition at line 82 of file SBBroadcaster.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, lldb::SBListener::m_opaque_sp, and SBListener.
BroadcastEvent()
void SBBroadcaster::BroadcastEvent (const lldb::SBEvent & event, bool unique = false)
Definition at line 60 of file SBBroadcaster.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBEvent.
BroadcastEventByType()
void SBBroadcaster::BroadcastEventByType (uint32_t event_type, bool unique = false)
Definition at line 48 of file SBBroadcaster.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
Clear()
void SBBroadcaster::Clear ()
Definition at line 136 of file SBBroadcaster.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and m_opaque_sp.
EventTypeHasListeners()
bool SBBroadcaster::EventTypeHasListeners (uint32_t event_type)
Definition at line 99 of file SBBroadcaster.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
get()
Broadcaster * SBBroadcaster::get () const protected
Definition at line 116 of file SBBroadcaster.cpp.
References m_opaque_ptr.
Referenced by lldb::SBEvent::BroadcasterMatchesRef(), lldb::SBListener::GetNextEventForBroadcaster(), lldb::SBListener::GetNextEventForBroadcasterWithType(), lldb::SBListener::PeekAtNextEventForBroadcaster(), lldb::SBListener::PeekAtNextEventForBroadcasterWithType(), SBTarget, lldb::SBListener::StartListeningForEvents(), lldb::SBListener::StopListeningForEvents(), lldb::SBListener::WaitForEventForBroadcaster(), and lldb::SBListener::WaitForEventForBroadcasterWithType().
GetName()
const char * SBBroadcaster::GetName () const
Definition at line 91 of file SBBroadcaster.cpp.
References lldb_private::ConstString::GetCString(), LLDB_INSTRUMENT_VA, and m_opaque_ptr.
IsValid()
bool SBBroadcaster::IsValid () const
Definition at line 126 of file SBBroadcaster.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBListener::GetNextEventForBroadcaster(), lldb::SBListener::GetNextEventForBroadcasterWithType(), lldb::SBListener::PeekAtNextEventForBroadcaster(), lldb::SBListener::PeekAtNextEventForBroadcasterWithType(), lldb::SBListener::StartListeningForEvents(), lldb::SBListener::StopListeningForEvents(), lldb::SBListener::WaitForEventForBroadcaster(), and lldb::SBListener::WaitForEventForBroadcasterWithType().
operator bool()
SBBroadcaster::operator bool () const explicit
Definition at line 130 of file SBBroadcaster.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
operator!=()
bool SBBroadcaster::operator!= (const lldb::SBBroadcaster & rhs) const
Definition at line 149 of file SBBroadcaster.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBBroadcaster().
operator<()
bool SBBroadcaster::operator< (const lldb::SBBroadcaster & rhs) const
Definition at line 155 of file SBBroadcaster.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBBroadcaster().
operator=()
const SBBroadcaster & SBBroadcaster::operator= (const SBBroadcaster & rhs)
Definition at line 36 of file SBBroadcaster.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, m_opaque_sp, and SBBroadcaster().
operator==()
bool SBBroadcaster::operator== (const lldb::SBBroadcaster & rhs) const
Definition at line 143 of file SBBroadcaster.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBBroadcaster().
RemoveListener()
bool SBBroadcaster::RemoveListener (const lldb::SBListener & listener, uint32_t event_mask = UINT32_MAX)
Definition at line 107 of file SBBroadcaster.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, lldb::SBListener::m_opaque_sp, and SBListener.
reset()
void SBBroadcaster::reset (lldb_private::Broadcaster * broadcaster, bool owns) protected
Definition at line 118 of file SBBroadcaster.cpp.
References m_opaque_ptr, and m_opaque_sp.
Referenced by lldb::SBEvent::GetBroadcaster(), SBTarget, and ~SBBroadcaster().
Friends And Related Symbol Documentation
SBCommandInterpreter
friend class SBCommandInterpreter friend
Definition at line 64 of file SBBroadcaster.h.
References SBCommandInterpreter.
Referenced by SBCommandInterpreter.
SBCommunication
friend class SBCommunication friend
Definition at line 65 of file SBBroadcaster.h.
References SBCommunication.
Referenced by SBCommunication.
SBDebugger
friend class SBDebugger friend
Definition at line 66 of file SBBroadcaster.h.
References SBDebugger.
Referenced by SBDebugger.
SBEvent
friend class SBEvent friend
Definition at line 67 of file SBBroadcaster.h.
References SBEvent.
Referenced by BroadcastEvent(), and SBEvent.
SBListener
friend class SBListener friend
Definition at line 68 of file SBBroadcaster.h.
References SBListener.
Referenced by AddInitialEventsToListener(), AddListener(), RemoveListener(), and SBListener.
SBProcess
friend class SBProcess friend
Definition at line 69 of file SBBroadcaster.h.
References SBProcess.
Referenced by SBProcess.
SBTarget
friend class SBTarget friend
Definition at line 70 of file SBBroadcaster.h.
References get(), reset(), SBBroadcaster(), and SBTarget.
Referenced by SBTarget.
Member Data Documentation
m_opaque_ptr
lldb_private::Broadcaster* lldb::SBBroadcaster::m_opaque_ptr = nullptr private
Definition at line 80 of file SBBroadcaster.h.
Referenced by AddInitialEventsToListener(), AddListener(), BroadcastEvent(), BroadcastEventByType(), Clear(), EventTypeHasListeners(), get(), GetName(), operator bool(), operator!=(), operator<(), operator=(), operator==(), RemoveListener(), reset(), SBBroadcaster(), SBBroadcaster(), and SBBroadcaster().
m_opaque_sp
lldb::BroadcasterSP lldb::SBBroadcaster::m_opaque_sp private
Definition at line 79 of file SBBroadcaster.h.
Referenced by Clear(), operator=(), reset(), SBBroadcaster(), SBBroadcaster(), and SBBroadcaster().
The documentation for this class was generated from the following files:
SBBroadcaster.h
SBBroadcaster.cpp