LLDB: lldb_private::RegisterTypeBuilder Class Reference
lldb_private::RegisterTypeBuilder Class Reference abstract
#include <RegisterTypeBuilder.h>
Public Member Functions
~RegisterTypeBuilder () override=default
virtual CompilerType GetRegisterType (const std::string &name, const lldb_private::RegisterFlags &flags, uint32_t byte_size)=0
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
virtual llvm::StringRef GetPluginName ()=0
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Protected Member Functions
RegisterTypeBuilder ()=default
Private Member Functions
RegisterTypeBuilder (const RegisterTypeBuilder &)=delete
const RegisterTypeBuilder & operator= (const RegisterTypeBuilder &)=delete
Detailed Description
Definition at line 17 of file RegisterTypeBuilder.h.
Constructor & Destructor Documentation
~RegisterTypeBuilder()
lldb_private::RegisterTypeBuilder::~RegisterTypeBuilder () override default
RegisterTypeBuilder() [1/2]
lldb_private::RegisterTypeBuilder::RegisterTypeBuilder () protected default
Referenced by operator=(), and RegisterTypeBuilder().
RegisterTypeBuilder() [2/2]
lldb_private::RegisterTypeBuilder::RegisterTypeBuilder (const RegisterTypeBuilder &) private delete
References RegisterTypeBuilder().
Member Function Documentation
GetRegisterType()
virtual CompilerType lldb_private::RegisterTypeBuilder::GetRegisterType (const std::string & name, const lldb_private::RegisterFlags & flags, uint32_t byte_size) pure virtual
Implemented in lldb_private::RegisterTypeBuilderClang.
operator=()
const RegisterTypeBuilder & lldb_private::RegisterTypeBuilder::operator= (const RegisterTypeBuilder &) private delete
References RegisterTypeBuilder().
The documentation for this class was generated from the following file:
RegisterTypeBuilder.h