LLDB: lldb_private::OptionalClangModuleID Class Reference
lldb_private::OptionalClangModuleID Class Reference
A Clang module ID.
#include <TypeSystemClang.h>
Public Member Functions
OptionalClangModuleID ()=default
OptionalClangModuleID (unsigned id)
bool HasValue () const
unsigned GetValue () const
Private Attributes
unsigned m_id = 0
Detailed Description
A Clang module ID.
Definition at line 66 of file TypeSystemClang.h.
Constructor & Destructor Documentation
OptionalClangModuleID() [1/2]
lldb_private::OptionalClangModuleID::OptionalClangModuleID () default
OptionalClangModuleID() [2/2]
lldb_private::OptionalClangModuleID::OptionalClangModuleID (unsigned id) inline explicit
Definition at line 71 of file TypeSystemClang.h.
References m_id.
Member Function Documentation
GetValue()
unsigned lldb_private::OptionalClangModuleID::GetValue () const inline
Definition at line 73 of file TypeSystemClang.h.
References m_id.
Referenced by lldb_private::TypeSystemClang::GetOrCreateClangModule(), RemapModule(), and lldb_private::TypeSystemClang::SetOwningModule().
HasValue()
bool lldb_private::OptionalClangModuleID::HasValue () const inline
Definition at line 72 of file TypeSystemClang.h.
References m_id.
Referenced by RemapModule(), and lldb_private::TypeSystemClang::SetOwningModule().
Member Data Documentation
m_id
unsigned lldb_private::OptionalClangModuleID::m_id = 0 private
Definition at line 67 of file TypeSystemClang.h.
Referenced by GetValue(), HasValue(), and OptionalClangModuleID().
The documentation for this class was generated from the following file:
TypeSystemClang.h