LLDB: lldb_private::DeclFromParser< D > Class Template Reference
lldb_private::DeclFromParser< D > Class Template Reference
#include <ClangASTImporter.h>
Public Member Functions
DeclFromParser ()
DeclFromParser (D *_decl)
DeclFromUser< D > GetOrigin (ClangASTImporter &importer)
Public Member Functions inherited from lldb_private::TaggedASTDecl< D >
TaggedASTDecl ()
TaggedASTDecl (D *_decl)
bool IsValid () const
bool IsInvalid () const
D * operator-> () const
Additional Inherited Members
Public Attributes inherited from lldb_private::TaggedASTDecl< D >
D * decl
Detailed Description
template<class D>
class lldb_private::DeclFromParser< D >
Definition at line 503 of file ClangASTImporter.h.
Constructor & Destructor Documentation
DeclFromParser() [1/2]
template<class D> lldb_private::DeclFromParser< D >::DeclFromParser () inline
Definition at line 505 of file ClangASTImporter.h.
References lldb_private::TaggedASTDecl< D >::TaggedASTDecl().
DeclFromParser() [2/2]
template<class D> lldb_private::DeclFromParser< D >::DeclFromParser (D * _decl) inline
Definition at line 506 of file ClangASTImporter.h.
References lldb_private::TaggedASTDecl< D >::TaggedASTDecl().
Member Function Documentation
GetOrigin()
template<class D> DeclFromUser< D > lldb_private::DeclFromParser< D >::GetOrigin (ClangASTImporter & importer)
Definition at line 521 of file ClangASTImporter.h.
References lldb_private::ClangASTImporter::DeclOrigin::decl, lldb_private::TaggedASTDecl< D >::decl, lldb_private::ClangASTImporter::GetDeclOrigin(), and lldb_private::ClangASTImporter::DeclOrigin::Valid().
Referenced by lldb_private::ClangASTSource::FindObjCPropertyAndIvarDecls(), and lldb_private::ClangASTImporter::importRecordLayoutFromOrigin().
The documentation for this class was generated from the following file:
ClangASTImporter.h