LLDB: EntityPersistentVariable Class Reference
EntityPersistentVariable Class Reference
Public Member Functions
EntityPersistentVariable (lldb::ExpressionVariableSP &persistent_variable_sp, Materializer::PersistentVariableDelegate *delegate)
void MakeAllocation (IRMemoryMap &map, Status &err)
void DestroyAllocation (IRMemoryMap &map, Status &err)
void Materialize (lldb::StackFrameSP &frame_sp, IRMemoryMap &map, lldb::addr_t process_address, Status &err) override
void Dematerialize (lldb::StackFrameSP &frame_sp, IRMemoryMap &map, lldb::addr_t process_address, lldb::addr_t frame_top, lldb::addr_t frame_bottom, Status &err) override
void DumpToLog (IRMemoryMap &map, lldb::addr_t process_address, Log *log) override
void Wipe (IRMemoryMap &map, lldb::addr_t process_address) override
Public Member Functions inherited from lldb_private::Materializer::Entity
Entity ()=default
virtual ~Entity ()=default
uint32_t GetAlignment ()
uint32_t GetSize ()
uint32_t GetOffset ()
void SetOffset (uint32_t offset)
Private Attributes
lldb::ExpressionVariableSP m_persistent_variable_sp
Materializer::PersistentVariableDelegate * m_delegate
Additional Inherited Members
Protected Attributes inherited from lldb_private::Materializer::Entity
uint32_t m_alignment = 1
uint32_t m_size = 0
uint32_t m_offset = 0
Detailed Description
Definition at line 59 of file Materializer.cpp.
Constructor & Destructor Documentation
EntityPersistentVariable()
EntityPersistentVariable::EntityPersistentVariable (lldb::ExpressionVariableSP & persistent_variable_sp, Materializer::PersistentVariableDelegate * delegate) inline
Definition at line 61 of file Materializer.cpp.
References lldb_private::Materializer::Entity::Entity(), g_default_var_alignment, g_default_var_byte_size, lldb_private::Materializer::Entity::m_alignment, m_delegate, m_persistent_variable_sp, and lldb_private::Materializer::Entity::m_size.
Member Function Documentation
Dematerialize()
void EntityPersistentVariable::Dematerialize (lldb::StackFrameSP & frame_sp, IRMemoryMap & map, lldb::addr_t process_address, lldb::addr_t frame_top, lldb::addr_t frame_bottom, Status & err) inline override virtual
Implements lldb_private::Materializer::Entity.
Definition at line 212 of file Materializer.cpp.
References lldb_private::Status::AsCString(), lldb_private::ValueObjectConstResult::Create(), DestroyAllocation(), lldb_private::eAddressTypeLoad, lldb_private::ExpressionVariable::EVIsLLDBAllocated, lldb_private::ExpressionVariable::EVIsProgramReference, lldb_private::ExpressionVariable::EVKeepInTarget, lldb_private::ExpressionVariable::EVNeedsAllocation, lldb_private::ExpressionVariable::EVNeedsFreezeDry, lldb_private::Expressions, lldb_private::Status::FromErrorStringWithFormat(), lldb_private::IRMemoryMap::GetBestExecutionContextScope(), lldb_private::GetLog(), LLDB_INVALID_ADDRESS, LLDB_LOGF, m_delegate, lldb_private::Materializer::Entity::m_offset, m_persistent_variable_sp, lldb_private::IRMemoryMap::ReadMemory(), lldb_private::IRMemoryMap::ReadPointerFromMemory(), and lldb_private::Status::Success().
DestroyAllocation()
void EntityPersistentVariable::DestroyAllocation (IRMemoryMap & map, Status & err) inline
Definition at line 143 of file Materializer.cpp.
References lldb_private::Status::AsCString(), lldb_private::IRMemoryMap::Free(), lldb_private::Status::FromErrorStringWithFormat(), m_persistent_variable_sp, and lldb_private::Status::Success().
Referenced by Dematerialize().
DumpToLog()
void EntityPersistentVariable::DumpToLog (IRMemoryMap & map, lldb::addr_t process_address, Log * log) inline override virtual
Implements lldb_private::Materializer::Entity.
Definition at line 350 of file Materializer.cpp.
References lldb_private::DumpHexBytes(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::DataBufferHeap::GetByteSize(), lldb_private::StreamString::GetString(), lldb_private::Materializer::Entity::m_offset, m_persistent_variable_sp, lldb_private::Materializer::Entity::m_size, lldb_private::Stream::Printf(), lldb_private::Stream::PutChar(), lldb_private::Log::PutString(), lldb_private::IRMemoryMap::ReadMemory(), lldb_private::IRMemoryMap::ReadPointerFromMemory(), and lldb_private::Status::Success().
MakeAllocation()
void EntityPersistentVariable::MakeAllocation (IRMemoryMap & map, Status & err) inline
Definition at line 71 of file Materializer.cpp.
References lldb_private::Status::AsCString(), lldb_private::ValueObjectConstResult::Create(), lldb_private::eAddressTypeLoad, lldb_private::IRMemoryMap::eAllocationPolicyMirror, lldb_private::ExpressionVariable::EVKeepInTarget, lldb_private::ExpressionVariable::EVNeedsFreezeDry, lldb_private::Expressions, lldb_private::Status::FromErrorStringWithFormat(), lldb_private::IRMemoryMap::GetAddressByteSize(), lldb_private::IRMemoryMap::GetBestExecutionContextScope(), lldb_private::GetLog(), lldb_private::IRMemoryMap::Leak(), LLDB_LOGF, m_persistent_variable_sp, lldb_private::IRMemoryMap::Malloc(), lldb_private::Status::Success(), lldb_private::toString(), and lldb_private::IRMemoryMap::WriteMemory().
Referenced by Materialize().
Materialize()
void EntityPersistentVariable::Materialize (lldb::StackFrameSP & frame_sp, IRMemoryMap & map, lldb::addr_t process_address, Status & err) inline override virtual
Implements lldb_private::Materializer::Entity.
Definition at line 161 of file Materializer.cpp.
References lldb_private::Status::AsCString(), lldb_private::ExpressionVariable::EVIsLLDBAllocated, lldb_private::ExpressionVariable::EVIsProgramReference, lldb_private::ExpressionVariable::EVNeedsAllocation, lldb_private::Expressions, lldb_private::Status::FromErrorStringWithFormat(), lldb_private::IRMemoryMap::GetAddressByteSize(), lldb_private::GetLog(), LLDB_LOGF, lldb_private::Materializer::Entity::m_offset, m_persistent_variable_sp, MakeAllocation(), lldb_private::Status::Success(), and lldb_private::IRMemoryMap::WriteScalarToMemory().
Wipe()
void EntityPersistentVariable::Wipe (IRMemoryMap & map, lldb::addr_t process_address) inline override virtual
Implements lldb_private::Materializer::Entity.
Definition at line 414 of file Materializer.cpp.
Member Data Documentation
m_delegate
Materializer::PersistentVariableDelegate* EntityPersistentVariable::m_delegate private
Definition at line 418 of file Materializer.cpp.
Referenced by Dematerialize(), and EntityPersistentVariable().
m_persistent_variable_sp
lldb::ExpressionVariableSP EntityPersistentVariable::m_persistent_variable_sp private
Definition at line 417 of file Materializer.cpp.
Referenced by Dematerialize(), DestroyAllocation(), DumpToLog(), EntityPersistentVariable(), MakeAllocation(), and Materialize().
The documentation for this class was generated from the following file:
Materializer.cpp