LLDB: lldb_private::AddressResolver Class Reference
lldb_private::AddressResolver Class Reference abstract
General Outline: The AddressResolver is a Searcher.
#include "lldb/Core/AddressResolver.h"
Public Types
enum MatchType { Exact , Regexp , Glob }
Public Types inherited from lldb_private::Searcher
enum CallbackReturn { eCallbackReturnStop = 0 , eCallbackReturnContinue , eCallbackReturnPop }
Public Member Functions
AddressResolver ()
~AddressResolver () override
virtual void ResolveAddress (SearchFilter &filter)
virtual void ResolveAddressInModules (SearchFilter &filter, ModuleList &modules)
void GetDescription (Stream *s) override=0
Prints a canonical description for the searcher to the stream s.
std::vector< AddressRange > & GetAddressRanges ()
size_t GetNumberOfAddresses ()
AddressRange & GetAddressRangeAtIndex (size_t idx)
Public Member Functions inherited from lldb_private::Searcher
Searcher ()
virtual ~Searcher ()
virtual CallbackReturn SearchCallback (SearchFilter &filter, SymbolContext &context, Address *addr)=0
virtual lldb::SearchDepth GetDepth ()=0
Protected Attributes
std::vector< AddressRange > m_address_ranges
Private Member Functions
AddressResolver (const AddressResolver &)=delete
const AddressResolver & operator= (const AddressResolver &)=delete
Detailed Description
General Outline: The AddressResolver is a Searcher.
This class works with SearchFilter to resolve function names and source file locations to their concrete addresses.
In that protocol, the SearchFilter asks the question "At what depth of the symbol context descent do you want your callback to get called?" of the filter. The resolver answers this question (in the GetDepth method) and provides the resolution callback.
Definition at line 33 of file AddressResolver.h.
Member Enumeration Documentation
MatchType
enum lldb_private::AddressResolver::MatchType
Enumerator
Exact
Regexp
Glob
Definition at line 35 of file AddressResolver.h.
Constructor & Destructor Documentation
AddressResolver() [1/2]
AddressResolver::AddressResolver () default
Referenced by AddressResolver(), lldb_private::AddressResolverFileLine::AddressResolverFileLine(), and operator=().
~AddressResolver()
AddressResolver::~AddressResolver () override default
AddressResolver() [2/2]
lldb_private::AddressResolver::AddressResolver (const AddressResolver &) private delete
References AddressResolver().
Member Function Documentation
GetAddressRangeAtIndex()
AddressRange & AddressResolver::GetAddressRangeAtIndex (size_t idx)
Definition at line 41 of file AddressResolver.cpp.
References m_address_ranges.
Referenced by lldb_private::Module::FindAddressesForLine().
GetAddressRanges()
std::vector< AddressRange > & AddressResolver::GetAddressRanges ()
Definition at line 33 of file AddressResolver.cpp.
References m_address_ranges.
GetDescription()
void lldb_private::AddressResolver::GetDescription (Stream * s) override pure virtual
Prints a canonical description for the searcher to the stream s.
Parameters
[in] s Stream to which the output is copied.
Reimplemented from lldb_private::Searcher.
Implemented in lldb_private::AddressResolverFileLine.
GetNumberOfAddresses()
size_t AddressResolver::GetNumberOfAddresses ()
Definition at line 37 of file AddressResolver.cpp.
References m_address_ranges.
Referenced by lldb_private::Module::FindAddressesForLine().
operator=()
const AddressResolver & lldb_private::AddressResolver::operator= (const AddressResolver &) private delete
References AddressResolver().
ResolveAddress()
void AddressResolver::ResolveAddress (SearchFilter & filter) virtual
Definition at line 29 of file AddressResolver.cpp.
References lldb_private::SearchFilter::Search().
Referenced by lldb_private::Module::FindAddressesForLine().
ResolveAddressInModules()
void AddressResolver::ResolveAddressInModules (SearchFilter & filter, ModuleList & modules) virtual
Definition at line 24 of file AddressResolver.cpp.
References lldb_private::SearchFilter::SearchInModuleList().
Member Data Documentation
m_address_ranges
std::vector<AddressRange> lldb_private::AddressResolver::m_address_ranges protected
Definition at line 55 of file AddressResolver.h.
Referenced by GetAddressRangeAtIndex(), GetAddressRanges(), GetNumberOfAddresses(), and lldb_private::AddressResolverFileLine::SearchCallback().
The documentation for this class was generated from the following files:
AddressResolver.h
AddressResolver.cpp