LLDB: RegisterContextLinux_s390x Class Reference
RegisterContextLinux_s390x Class Reference
#include <RegisterContextLinux_s390x.h>
Public Member Functions
RegisterContextLinux_s390x (const lldb_private::ArchSpec &target_arch)
size_t GetGPRSize () const override
const lldb_private::RegisterInfo * GetRegisterInfo () const override
uint32_t GetRegisterCount () const override
uint32_t GetUserRegisterCount () const override
Public Member Functions inherited from lldb_private::RegisterInfoInterface
RegisterInfoInterface (const lldb_private::ArchSpec &target_arch)
virtual ~RegisterInfoInterface ()=default
const lldb_private::ArchSpec & GetTargetArchitecture () const
Private Attributes
const lldb_private::RegisterInfo * m_register_info_p
uint32_t m_register_info_count
uint32_t m_user_register_count
Detailed Description
Definition at line 14 of file RegisterContextLinux_s390x.h.
Constructor & Destructor Documentation
RegisterContextLinux_s390x()
RegisterContextLinux_s390x::RegisterContextLinux_s390x (const lldb_private::ArchSpec & target_arch)
Definition at line 50 of file RegisterContextLinux_s390x.cpp.
References GetRegisterInfoCount(), GetRegisterInfoPtr(), GetUserRegisterInfoCount(), m_register_info_count, m_register_info_p, m_user_register_count, and lldb_private::RegisterInfoInterface::RegisterInfoInterface().
Member Function Documentation
GetGPRSize()
size_t RegisterContextLinux_s390x::GetGPRSize () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 69 of file RegisterContextLinux_s390x.cpp.
GetRegisterCount()
uint32_t RegisterContextLinux_s390x::GetRegisterCount () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 61 of file RegisterContextLinux_s390x.cpp.
References m_register_info_count.
GetRegisterInfo()
const RegisterInfo * RegisterContextLinux_s390x::GetRegisterInfo () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 57 of file RegisterContextLinux_s390x.cpp.
References m_register_info_p.
GetUserRegisterCount()
uint32_t RegisterContextLinux_s390x::GetUserRegisterCount () const override virtual
Reimplemented from lldb_private::RegisterInfoInterface.
Definition at line 65 of file RegisterContextLinux_s390x.cpp.
References m_user_register_count.
Member Data Documentation
m_register_info_count
uint32_t RegisterContextLinux_s390x::m_register_info_count private
Definition at line 28 of file RegisterContextLinux_s390x.h.
Referenced by GetRegisterCount(), and RegisterContextLinux_s390x().
m_register_info_p
const lldb_private::RegisterInfo* RegisterContextLinux_s390x::m_register_info_p private
Definition at line 27 of file RegisterContextLinux_s390x.h.
Referenced by GetRegisterInfo(), and RegisterContextLinux_s390x().
m_user_register_count
uint32_t RegisterContextLinux_s390x::m_user_register_count private
Definition at line 29 of file RegisterContextLinux_s390x.h.
Referenced by GetUserRegisterCount(), and RegisterContextLinux_s390x().
The documentation for this class was generated from the following files:
RegisterContextLinux_s390x.h
RegisterContextLinux_s390x.cpp