LLDB: lldb_private::Instruction Class Reference
lldb_private::Instruction Class Reference abstract
#include <Disassembler.h>
Classes
struct Operand
Public Member Functions
Instruction (const Address &address, AddressClass addr_class=AddressClass::eInvalid)
virtual ~Instruction ()
const Address & GetAddress () const
const char * GetMnemonic (const ExecutionContext *exe_ctx, bool markup=false)
const char * GetOperands (const ExecutionContext *exe_ctx, bool markup=false)
const char * GetComment (const ExecutionContext *exe_ctx)
virtual lldb::InstructionControlFlowKind GetControlFlowKind (const ExecutionContext *exe_ctx)
virtual void CalculateMnemonicOperandsAndComment (const ExecutionContext *exe_ctx)=0
AddressClass GetAddressClass ()
void SetAddress (const Address &addr)
virtual void Dump (Stream *s, uint32_t max_opcode_byte_size, bool show_address, bool show_bytes, bool show_control_flow_kind, const ExecutionContext *exe_ctx, const SymbolContext *sym_ctx, const SymbolContext *prev_sym_ctx, const FormatEntity::Entry *disassembly_addr_format, size_t max_address_text_size)
Dump the text representation of this Instruction to a Stream.
virtual bool DoesBranch ()=0
virtual bool HasDelaySlot ()
virtual bool IsLoad ()=0
virtual bool IsBarrier ()=0
virtual bool IsAuthenticated ()=0
bool CanSetBreakpoint ()
virtual size_t Decode (const Disassembler &disassembler, const DataExtractor &data, lldb::offset_t data_offset)=0
virtual void SetDescription (llvm::StringRef)
lldb::OptionValueSP ReadArray (FILE *in_file, Stream &out_stream, OptionValue::Type data_type)
lldb::OptionValueSP ReadDictionary (FILE *in_file, Stream &out_stream)
bool DumpEmulation (const ArchSpec &arch)
virtual bool TestEmulation (Stream &stream, const char *test_file_name)
bool Emulate (const ArchSpec &arch, uint32_t evaluate_options, void *baton, EmulateInstruction::ReadMemoryCallback read_mem_callback, EmulateInstruction::WriteMemoryCallback write_mem_calback, EmulateInstruction::ReadRegisterCallback read_reg_callback, EmulateInstruction::WriteRegisterCallback write_reg_callback)
const Opcode & GetOpcode () const
uint32_t GetData (DataExtractor &data)
virtual bool ParseOperands (llvm::SmallVectorImpl< Operand > &operands)
virtual bool IsCall ()
StructuredData::ArraySP GetVariableAnnotations ()
Get variable annotations for this instruction as structured data.
Static Public Member Functions
static const char * GetNameForInstructionControlFlowKind (lldb::InstructionControlFlowKind instruction_control_flow_kind)
Protected Member Functions
void CalculateMnemonicOperandsAndCommentIfNeeded (const ExecutionContext *exe_ctx)
Protected Attributes
Address m_address
Opcode m_opcode
std::string m_opcode_name
std::string m_markup_opcode_name
std::string m_mnemonics
std::string m_markup_mnemonics
std::string m_comment
bool m_calculated_strings
Private Attributes
AddressClass m_address_class
Detailed Description
Definition at line 59 of file Disassembler.h.
Constructor & Destructor Documentation
Instruction()
Instruction::Instruction (const Address & address, AddressClass addr_class = AddressClass::eInvalid)
Definition at line 790 of file Disassembler.cpp.
References m_address, m_address_class, m_calculated_strings, and m_opcode.
Referenced by InstructionLLVMC::InstructionLLVMC(), and lldb_private::PseudoInstruction::PseudoInstruction().
~Instruction()
Instruction::~Instruction () virtual default
Member Function Documentation
CalculateMnemonicOperandsAndComment()
virtual void lldb_private::Instruction::CalculateMnemonicOperandsAndComment (const ExecutionContext * exe_ctx) pure virtual
Implemented in InstructionLLVMC, and lldb_private::PseudoInstruction.
Referenced by CalculateMnemonicOperandsAndCommentIfNeeded().
CalculateMnemonicOperandsAndCommentIfNeeded()
void lldb_private::Instruction::CalculateMnemonicOperandsAndCommentIfNeeded (const ExecutionContext * exe_ctx) inline protected
Definition at line 263 of file Disassembler.h.
References CalculateMnemonicOperandsAndComment(), and m_calculated_strings.
Referenced by Dump(), GetComment(), GetMnemonic(), and GetOperands().
CanSetBreakpoint()
bool Instruction::CanSetBreakpoint ()
Definition at line 920 of file Disassembler.cpp.
References HasDelaySlot().
Decode()
virtual size_t lldb_private::Instruction::Decode (const Disassembler & disassembler, const DataExtractor & data, lldb::offset_t data_offset) pure virtual
Implemented in InstructionLLVMC, and lldb_private::PseudoInstruction.
DoesBranch()
virtual bool lldb_private::Instruction::DoesBranch () pure virtual
Implemented in InstructionLLVMC, and lldb_private::PseudoInstruction.
Dump()
void Instruction::Dump (lldb_private::Stream * s, uint32_t max_opcode_byte_size, bool show_address, bool show_bytes, bool show_control_flow_kind, const ExecutionContext * exe_ctx, const SymbolContext * sym_ctx, const SymbolContext * prev_sym_ctx, const FormatEntity::Entry * disassembly_addr_format, size_t max_address_text_size) virtual
Dump the text representation of this Instruction to a Stream.
Print the (optional) address, (optional) bytes, opcode, operands, and instruction comments to a stream.
Parameters
[in] s The Stream to add the text to.
[in] show_address Whether the address (using disassembly_addr_format_spec formatting) should be printed.
[in] show_bytes Whether the bytes of the assembly instruction should be printed.
[in] show_control_flow_kind Whether the control flow kind of the instruction should be printed.
[in] max_opcode_byte_size The size (in bytes) of the largest instruction in the list that we are printing (for text justification/alignment purposes) Only needed if show_bytes is true.
[in] exe_ctx The current execution context, if available. May be used in the assembling of the operands+comments for this instruction. Pass NULL if not applicable.
[in] sym_ctx The SymbolContext for this instruction. Pass NULL if not available/computed. Only needed if show_address is true.
[in] prev_sym_ctx The SymbolContext for the previous instruction. Depending on the disassembly address format specification, a change in Symbol / Function may mean that a line is printed with the new symbol/function name. Pass NULL if unavailable, or if this is the first instruction of the InstructionList. Only needed if show_address is true.
[in] disassembly_addr_format The format specification for how addresses are printed. Only needed if show_address is true.
[in] max_address_text_size The length of the longest address string at the start of the disassembly line that will be printed (the Debugger::FormatDisassemblerAddress() string) so this method can properly align the instruction opcodes. May be 0 to indicate no indentation/alignment of the opcodes.
Definition at line 827 of file Disassembler.cpp.
References CalculateMnemonicOperandsAndCommentIfNeeded(), lldb_private::Opcode::eTypeBytes, lldb_private::StreamString::FillLastLineToColumn(), lldb_private::Debugger::FormatDisassemblerAddress(), GetControlFlowKind(), GetNameForInstructionControlFlowKind(), lldb_private::StreamString::GetSizeOfLastLine(), lldb_private::StreamString::GetString(), lldb_private::ExecutionContext::GetTargetSP(), m_address, m_comment, m_markup_mnemonics, m_markup_opcode_name, m_mnemonics, m_opcode, m_opcode_name, lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
Referenced by DumpInstToLog(), lldb::SBInstructionList::GetDescription(), lldb_private::ThreadPlanAssemblyTracer::Log(), and lldb_private::Disassembler::PrintInstructions().
DumpEmulation()
bool Instruction::DumpEmulation (const ArchSpec & arch)
Definition at line 909 of file Disassembler.cpp.
References lldb_private::eInstructionTypeAny, lldb_private::EmulateInstruction::FindPlugin(), GetAddress(), and GetOpcode().
Emulate()
bool Instruction::Emulate (const ArchSpec & arch, uint32_t evaluate_options, void * baton, EmulateInstruction::ReadMemoryCallback read_mem_callback, EmulateInstruction::WriteMemoryCallback write_mem_calback, EmulateInstruction::ReadRegisterCallback read_reg_callback, EmulateInstruction::WriteRegisterCallback write_reg_callback)
Definition at line 1169 of file Disassembler.cpp.
References lldb_private::eInstructionTypeAny, lldb_private::EmulateInstruction::FindPlugin(), GetAddress(), and GetOpcode().
GetAddress()
const Address & lldb_private::Instruction::GetAddress () const inline
Definition at line 66 of file Disassembler.h.
References m_address.
Referenced by lldb_private::VariableAnnotator::AnnotateStructured(), DumpEmulation(), Emulate(), lldb::SBInstructionList::GetDescription(), UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly(), and lldb_private::Disassembler::PrintInstructions().
GetAddressClass()
AddressClass Instruction::GetAddressClass ()
Definition at line 796 of file Disassembler.cpp.
References lldb_private::eInvalid, m_address, and m_address_class.
Referenced by InstructionLLVMC::CalculateMnemonicOperandsAndComment(), and InstructionLLVMC::GetDisasmToUse().
GetComment()
const char * lldb_private::Instruction::GetComment (const ExecutionContext * exe_ctx) inline
Definition at line 80 of file Disassembler.h.
References CalculateMnemonicOperandsAndCommentIfNeeded(), and m_comment.
GetControlFlowKind()
virtual lldb::InstructionControlFlowKind lldb_private::Instruction::GetControlFlowKind (const ExecutionContext * exe_ctx) inline virtual
Returns
The control flow kind of this instruction, or eInstructionControlFlowKindUnknown if the instruction can't be classified.
Reimplemented in InstructionLLVMC.
Definition at line 90 of file Disassembler.h.
References lldb::eInstructionControlFlowKindUnknown.
Referenced by Dump().
GetData()
uint32_t Instruction::GetData (DataExtractor & data)
Definition at line 1188 of file Disassembler.cpp.
References m_opcode.
GetMnemonic()
const char * lldb_private::Instruction::GetMnemonic (const ExecutionContext * exe_ctx, bool markup = false) inline
Definition at line 68 of file Disassembler.h.
References CalculateMnemonicOperandsAndCommentIfNeeded(), m_markup_opcode_name, and m_opcode_name.
GetNameForInstructionControlFlowKind()
const char * Instruction::GetNameForInstructionControlFlowKind (lldb::InstructionControlFlowKind instruction_control_flow_kind) static
Definition at line 802 of file Disassembler.cpp.
References lldb::eInstructionControlFlowKindCall, lldb::eInstructionControlFlowKindCondJump, lldb::eInstructionControlFlowKindFarCall, lldb::eInstructionControlFlowKindFarJump, lldb::eInstructionControlFlowKindFarReturn, lldb::eInstructionControlFlowKindJump, lldb::eInstructionControlFlowKindOther, lldb::eInstructionControlFlowKindReturn, and lldb::eInstructionControlFlowKindUnknown.
Referenced by Dump(), and OutputWriterJSON::DumpInstruction().
GetOpcode()
const Opcode & lldb_private::Instruction::GetOpcode () const inline
Definition at line 199 of file Disassembler.h.
References m_opcode.
Referenced by DumpEmulation(), Emulate(), lldb::SBInstructionList::GetDescription(), and UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly().
GetOperands()
const char * lldb_private::Instruction::GetOperands (const ExecutionContext * exe_ctx, bool markup = false) inline
Definition at line 74 of file Disassembler.h.
References CalculateMnemonicOperandsAndCommentIfNeeded(), m_markup_mnemonics, and m_mnemonics.
Referenced by InstructionLLVMC::ParseOperands().
GetVariableAnnotations()
StructuredData::ArraySP Instruction::GetVariableAnnotations ()
Get variable annotations for this instruction as structured data.
Returns an array of dictionaries to be used in SBInstruction class.
Definition at line 1192 of file Disassembler.cpp.
References lldb_private::VariableAnnotator::AnnotateStructured().
HasDelaySlot()
bool Instruction::HasDelaySlot () virtual
Reimplemented in InstructionLLVMC, and lldb_private::PseudoInstruction.
Definition at line 922 of file Disassembler.cpp.
Referenced by CanSetBreakpoint().
IsAuthenticated()
virtual bool lldb_private::Instruction::IsAuthenticated () pure virtual
Implemented in InstructionLLVMC, and lldb_private::PseudoInstruction.
IsBarrier()
virtual bool lldb_private::Instruction::IsBarrier () pure virtual
Implemented in InstructionLLVMC, and lldb_private::PseudoInstruction.
Referenced by UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly().
IsCall()
virtual bool lldb_private::Instruction::IsCall () inline virtual
Reimplemented in InstructionLLVMC.
Definition at line 232 of file Disassembler.h.
IsLoad()
virtual bool lldb_private::Instruction::IsLoad () pure virtual
Implemented in InstructionLLVMC, and lldb_private::PseudoInstruction.
ParseOperands()
virtual bool lldb_private::Instruction::ParseOperands (llvm::SmallVectorImpl< Operand > & operands) inline virtual
Reimplemented in InstructionLLVMC.
Definition at line 228 of file Disassembler.h.
ReadArray()
OptionValueSP Instruction::ReadArray (FILE * in_file, Stream & out_stream, OptionValue::Type data_type)
Definition at line 927 of file Disassembler.cpp.
References lldb_private::OptionValue::eTypeUInt64, lldb_private::RegularExpression::Execute(), and lldb_private::Stream::Printf().
Referenced by ReadDictionary().
ReadDictionary()
OptionValueSP Instruction::ReadDictionary (FILE * in_file, Stream & out_stream)
Definition at line 986 of file Disassembler.cpp.
References lldb_private::OptionValue::eTypeInvalid, lldb_private::OptionValue::eTypeUInt64, lldb_private::RegularExpression::Execute(), lldb_private::Stream::Printf(), ReadArray(), and ReadDictionary().
Referenced by ReadDictionary(), and TestEmulation().
SetAddress()
void lldb_private::Instruction::SetAddress (const Address & addr) inline
Definition at line 99 of file Disassembler.h.
References lldb_private::eInvalid, m_address, and m_address_class.
SetDescription()
virtual void lldb_private::Instruction::SetDescription (llvm::StringRef) inline virtual
Reimplemented in lldb_private::PseudoInstruction.
Definition at line 181 of file Disassembler.h.
Referenced by TestEmulation().
TestEmulation()
bool Instruction::TestEmulation (Stream & stream, const char * test_file_name) virtual
Definition at line 1088 of file Disassembler.cpp.
References lldb_private::eInstructionTypeAny, lldb_private::EmulateInstruction::FindPlugin(), lldb_private::FileSystem::Fopen(), lldb_private::OptionValueDictionary::GetValueForKey(), lldb_private::FileSystem::Instance(), lldb_private::Stream::Printf(), ReadDictionary(), SetDescription(), and lldb_private::ArchSpec::SetTriple().
Member Data Documentation
m_address
Address lldb_private::Instruction::m_address protected
Definition at line 242 of file Disassembler.h.
Referenced by InstructionLLVMC::CalculateMnemonicOperandsAndComment(), InstructionLLVMC::Decode(), Dump(), GetAddress(), GetAddressClass(), Instruction(), SetAddress(), and InstructionLLVMC::VisitInstruction().
m_address_class
AddressClass lldb_private::Instruction::m_address_class private
Definition at line 251 of file Disassembler.h.
Referenced by GetAddressClass(), Instruction(), and SetAddress().
m_calculated_strings
bool lldb_private::Instruction::m_calculated_strings protected
Definition at line 260 of file Disassembler.h.
Referenced by CalculateMnemonicOperandsAndCommentIfNeeded(), and Instruction().
m_comment
std::string lldb_private::Instruction::m_comment protected
Definition at line 259 of file Disassembler.h.
Referenced by InstructionLLVMC::AppendComment(), InstructionLLVMC::CalculateMnemonicOperandsAndComment(), Dump(), and GetComment().
m_markup_mnemonics
std::string lldb_private::Instruction::m_markup_mnemonics protected
Definition at line 258 of file Disassembler.h.
Referenced by InstructionLLVMC::CalculateMnemonicOperandsAndComment(), Dump(), and GetOperands().
m_markup_opcode_name
std::string lldb_private::Instruction::m_markup_opcode_name protected
Definition at line 256 of file Disassembler.h.
Referenced by InstructionLLVMC::CalculateMnemonicOperandsAndComment(), Dump(), and GetMnemonic().
m_mnemonics
std::string lldb_private::Instruction::m_mnemonics protected
Definition at line 257 of file Disassembler.h.
Referenced by InstructionLLVMC::CalculateMnemonicOperandsAndComment(), Dump(), and GetOperands().
m_opcode
Opcode lldb_private::Instruction::m_opcode protected
Definition at line 254 of file Disassembler.h.
Referenced by InstructionLLVMC::CalculateMnemonicOperandsAndComment(), InstructionLLVMC::Decode(), lldb_private::PseudoInstruction::Decode(), Dump(), InstructionLLVMC::GetByteSize(), InstructionLLVMC::GetControlFlowKind(), GetData(), GetOpcode(), Instruction(), lldb_private::PseudoInstruction::SetOpcode(), and InstructionLLVMC::VisitInstruction().
m_opcode_name
std::string lldb_private::Instruction::m_opcode_name protected
Definition at line 255 of file Disassembler.h.
Referenced by InstructionLLVMC::CalculateMnemonicOperandsAndComment(), Dump(), and GetMnemonic().
The documentation for this class was generated from the following files:
Disassembler.h
Disassembler.cpp