LLDB: lldb_private::StructuredDataImpl Class Reference
lldb_private::StructuredDataImpl Class Reference
#include <StructuredDataImpl.h>
Public Member Functions
StructuredDataImpl ()=default
StructuredDataImpl (const StructuredDataImpl &rhs)=default
StructuredDataImpl (StructuredData::ObjectSP obj)
StructuredDataImpl (const lldb::EventSP &event_sp)
~StructuredDataImpl ()=default
StructuredDataImpl & operator= (const StructuredDataImpl &rhs)=default
bool IsValid () const
void Clear ()
Status GetAsJSON (Stream &stream) const
Status GetDescription (Stream &stream) const
StructuredData::ObjectSP GetObjectSP ()
void SetObjectSP (const StructuredData::ObjectSP &obj)
void SetValueForKey (llvm::StringRef key, const StructuredData::ObjectSP &value)
void SetUnsignedIntegerValue (uint64_t value)
void SetSignedIntegerValue (int64_t value)
void SetFloatValue (double value)
void SetBooleanValue (bool value)
void SetStringValue (std::string value)
void SetGenericValue (void *value)
lldb::StructuredDataType GetType () const
size_t GetSize () const
StructuredData::ObjectSP GetValueForKey (const char *key) const
StructuredData::ObjectSP GetItemAtIndex (size_t idx) const
uint64_t GetIntegerValue (uint64_t fail_value=0) const
int64_t GetIntegerValue (int64_t fail_value=0) const
double GetFloatValue (double fail_value=0.0) const
bool GetBooleanValue (bool fail_value=false) const
size_t GetStringValue (char *dst, size_t dst_len) const
void * GetGenericValue () const
StructuredData::ObjectSP GetObjectSP () const
Private Attributes
lldb::StructuredDataPluginWP m_plugin_wp
StructuredData::ObjectSP m_data_sp
Detailed Description
Definition at line 26 of file StructuredDataImpl.h.
Constructor & Destructor Documentation
StructuredDataImpl() [1/4]
lldb_private::StructuredDataImpl::StructuredDataImpl () default
Referenced by operator=(), and StructuredDataImpl().
StructuredDataImpl() [2/4]
lldb_private::StructuredDataImpl::StructuredDataImpl (const StructuredDataImpl & rhs) default
References StructuredDataImpl().
StructuredDataImpl() [3/4]
lldb_private::StructuredDataImpl::StructuredDataImpl (StructuredData::ObjectSP obj) inline
Definition at line 32 of file StructuredDataImpl.h.
References m_data_sp.
StructuredDataImpl() [4/4]
lldb_private::StructuredDataImpl::StructuredDataImpl (const lldb::EventSP & event_sp) inline
Definition at line 35 of file StructuredDataImpl.h.
References m_data_sp, and m_plugin_wp.
~StructuredDataImpl()
lldb_private::StructuredDataImpl::~StructuredDataImpl () default
Member Function Documentation
Clear()
void lldb_private::StructuredDataImpl::Clear () inline
Definition at line 47 of file StructuredDataImpl.h.
References m_data_sp, and m_plugin_wp.
GetAsJSON()
Status lldb_private::StructuredDataImpl::GetAsJSON (Stream & stream) const inline
Definition at line 52 of file StructuredDataImpl.h.
References lldb_private::Stream::AsRawOstream(), lldb_private::Status::FromErrorString(), m_data_sp, and lldb_private::Status.
GetBooleanValue()
bool lldb_private::StructuredDataImpl::GetBooleanValue (bool fail_value = false) const inline
Definition at line 170 of file StructuredDataImpl.h.
References m_data_sp.
GetDescription()
Status lldb_private::StructuredDataImpl::GetDescription (Stream & stream) const inline
Definition at line 61 of file StructuredDataImpl.h.
References lldb_private::Status::FromErrorString(), m_data_sp, m_plugin_wp, and lldb_private::Status.
GetFloatValue()
double lldb_private::StructuredDataImpl::GetFloatValue (double fail_value = 0.0) const inline
Definition at line 166 of file StructuredDataImpl.h.
References m_data_sp.
GetGenericValue()
void * lldb_private::StructuredDataImpl::GetGenericValue () const inline
Definition at line 189 of file StructuredDataImpl.h.
References lldb_private::StructuredData::Generic::GetValue(), and m_data_sp.
GetIntegerValue() [1/2]
int64_t lldb_private::StructuredDataImpl::GetIntegerValue (int64_t fail_value = 0) const inline
Definition at line 161 of file StructuredDataImpl.h.
References m_data_sp.
GetIntegerValue() [2/2]
uint64_t lldb_private::StructuredDataImpl::GetIntegerValue (uint64_t fail_value = 0) const inline
Definition at line 156 of file StructuredDataImpl.h.
References m_data_sp.
GetItemAtIndex()
StructuredData::ObjectSP lldb_private::StructuredDataImpl::GetItemAtIndex (size_t idx) const inline
Definition at line 147 of file StructuredDataImpl.h.
References m_data_sp.
GetObjectSP() [1/2]
StructuredData::ObjectSP lldb_private::StructuredDataImpl::GetObjectSP () inline
Definition at line 80 of file StructuredDataImpl.h.
References m_data_sp.
Referenced by lldb_private::telemetry::TelemetryManager::DispatchClientTelemetry().
GetObjectSP() [2/2]
StructuredData::ObjectSP lldb_private::StructuredDataImpl::GetObjectSP () const inline
Definition at line 200 of file StructuredDataImpl.h.
References m_data_sp.
GetSize()
size_t lldb_private::StructuredDataImpl::GetSize () const inline
Definition at line 124 of file StructuredDataImpl.h.
References lldb::eStructuredDataTypeArray, lldb::eStructuredDataTypeDictionary, and m_data_sp.
GetStringValue()
size_t lldb_private::StructuredDataImpl::GetStringValue (char * dst, size_t dst_len) const inline
Definition at line 174 of file StructuredDataImpl.h.
References m_data_sp.
GetType()
lldb::StructuredDataType lldb_private::StructuredDataImpl::GetType () const inline
Definition at line 119 of file StructuredDataImpl.h.
References lldb::eStructuredDataTypeInvalid, and m_data_sp.
GetValueForKey()
StructuredData::ObjectSP lldb_private::StructuredDataImpl::GetValueForKey (const char * key) const inline
Definition at line 138 of file StructuredDataImpl.h.
References m_data_sp.
IsValid()
bool lldb_private::StructuredDataImpl::IsValid () const inline
Definition at line 45 of file StructuredDataImpl.h.
References m_data_sp.
operator=()
StructuredDataImpl & lldb_private::StructuredDataImpl::operator= (const StructuredDataImpl & rhs) default
References StructuredDataImpl().
SetBooleanValue()
void lldb_private::StructuredDataImpl::SetBooleanValue (bool value) inline
Definition at line 107 of file StructuredDataImpl.h.
References lldb_private::StructuredData::FromBoolean(), and m_data_sp.
SetFloatValue()
void lldb_private::StructuredDataImpl::SetFloatValue (double value) inline
Definition at line 103 of file StructuredDataImpl.h.
References lldb_private::StructuredData::FromFloat(), and m_data_sp.
SetGenericValue()
void lldb_private::StructuredDataImpl::SetGenericValue (void * value) inline
Definition at line 115 of file StructuredDataImpl.h.
References lldb_private::StructuredData::FromGeneric(), and m_data_sp.
SetObjectSP()
void lldb_private::StructuredDataImpl::SetObjectSP (const StructuredData::ObjectSP & obj) inline
Definition at line 82 of file StructuredDataImpl.h.
References m_data_sp.
Referenced by lldb_private::BreakpointResolverScripted::CreateFromStructuredData().
SetSignedIntegerValue()
void lldb_private::StructuredDataImpl::SetSignedIntegerValue (int64_t value) inline
Definition at line 99 of file StructuredDataImpl.h.
References lldb_private::StructuredData::FromInteger(), and m_data_sp.
SetStringValue()
void lldb_private::StructuredDataImpl::SetStringValue (std::string value) inline
Definition at line 111 of file StructuredDataImpl.h.
References lldb_private::StructuredData::FromString(), and m_data_sp.
SetUnsignedIntegerValue()
void lldb_private::StructuredDataImpl::SetUnsignedIntegerValue (uint64_t value) inline
Definition at line 95 of file StructuredDataImpl.h.
References lldb_private::StructuredData::FromInteger(), and m_data_sp.
SetValueForKey()
void lldb_private::StructuredDataImpl::SetValueForKey (llvm::StringRef key, const StructuredData::ObjectSP & value) inline
Definition at line 84 of file StructuredDataImpl.h.
References lldb::eStructuredDataTypeDictionary, lldb_private::StructuredData::FromKeyValue(), and m_data_sp.
Member Data Documentation
m_data_sp
StructuredData::ObjectSP lldb_private::StructuredDataImpl::m_data_sp private
Definition at line 204 of file StructuredDataImpl.h.
Referenced by Clear(), GetAsJSON(), GetBooleanValue(), GetDescription(), GetFloatValue(), GetGenericValue(), GetIntegerValue(), GetIntegerValue(), GetItemAtIndex(), GetObjectSP(), GetObjectSP(), GetSize(), GetStringValue(), GetType(), GetValueForKey(), IsValid(), SetBooleanValue(), SetFloatValue(), SetGenericValue(), SetObjectSP(), SetSignedIntegerValue(), SetStringValue(), SetUnsignedIntegerValue(), SetValueForKey(), StructuredDataImpl(), and StructuredDataImpl().
m_plugin_wp
lldb::StructuredDataPluginWP lldb_private::StructuredDataImpl::m_plugin_wp private
Definition at line 203 of file StructuredDataImpl.h.
Referenced by Clear(), GetDescription(), and StructuredDataImpl().
The documentation for this class was generated from the following file:
StructuredDataImpl.h