LLDB: RegisterContextFreeBSDKernelCore_arm64 Class Reference
RegisterContextFreeBSDKernelCore_arm64 Class Reference
#include <RegisterContextFreeBSDKernelCore_arm64.h>
Public Member Functions
RegisterContextFreeBSDKernelCore_arm64 (lldb_private::Thread &thread, std::unique_ptr< RegisterInfoPOSIX_arm64 > register_info_up, lldb::addr_t pcb_addr)
bool ReadRegister (const lldb_private::RegisterInfo *reg_info, lldb_private::RegisterValue &value) override
bool WriteRegister (const lldb_private::RegisterInfo *reg_info, const lldb_private::RegisterValue &value) override
Public Member Functions inherited from RegisterContextPOSIX_arm64
RegisterContextPOSIX_arm64 (lldb_private::Thread &thread, std::unique_ptr< RegisterInfoPOSIX_arm64 > register_info)
~RegisterContextPOSIX_arm64 () override
void Invalidate ()
void InvalidateAllRegisters () override
size_t GetRegisterCount () override
virtual size_t GetGPRSize ()
virtual unsigned GetRegisterSize (unsigned reg)
virtual unsigned GetRegisterOffset (unsigned reg)
const lldb_private::RegisterInfo * GetRegisterInfoAtIndex (size_t reg) override
size_t GetRegisterSetCount () override
const lldb_private::RegisterSet * GetRegisterSet (size_t set) override
const char * GetRegisterName (unsigned reg)
Public Member Functions inherited from lldb_private::RegisterContext
RegisterContext (Thread &thread, uint32_t concrete_frame_idx)
~RegisterContext () override
void InvalidateIfNeeded (bool force)
virtual lldb::ByteOrder GetByteOrder ()
virtual bool ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp)
virtual bool WriteAllRegisterValues (const lldb::DataBufferSP &data_sp)
virtual bool RegisterWriteCausesReconfigure (const llvm::StringRef name)
virtual bool ReconfigureRegisterInfo ()
virtual bool ReadAllRegisterValues (lldb_private::RegisterCheckpoint &reg_checkpoint)
virtual bool WriteAllRegisterValues (const lldb_private::RegisterCheckpoint &reg_checkpoint)
bool CopyFromRegisterContext (lldb::RegisterContextSP context)
virtual uint32_t ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num)
Convert from a given register numbering scheme to the lldb register numbering scheme.
virtual uint32_t NumSupportedHardwareBreakpoints ()
virtual uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual bool ClearHardwareBreakpoint (uint32_t hw_idx)
virtual uint32_t NumSupportedHardwareWatchpoints ()
virtual uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, bool read, bool write)
virtual bool ClearHardwareWatchpoint (uint32_t hw_index)
virtual bool HardwareSingleStep (bool enable)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, uint32_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, uint32_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual Thread & GetThread ()
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num)
uint64_t GetPC (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetThreadPointer (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool GetPCForSymbolication (Address &address)
Get an address suitable for symbolication.
bool SetPC (uint64_t pc)
bool SetPC (Address addr)
uint64_t GetSP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetSP (uint64_t sp)
uint64_t GetFP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetFP (uint64_t fp)
const char * GetRegisterName (uint32_t reg)
uint64_t GetReturnAddress (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetFlags (uint64_t fail_value=0)
uint64_t ReadRegisterAsUnsigned (uint32_t reg, uint64_t fail_value)
uint64_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, uint64_t fail_value)
bool WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
bool WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
bool ConvertBetweenRegisterKinds (lldb::RegisterKind source_rk, uint32_t source_regnum, lldb::RegisterKind target_rk, uint32_t &target_regnum)
lldb::TargetSP CalculateTarget () override
lldb::ProcessSP CalculateProcess () override
lldb::ThreadSP CalculateThread () override
lldb::StackFrameSP CalculateStackFrame () override
void CalculateExecutionContext (ExecutionContext &exe_ctx) override
Reconstruct the object's execution context into sc.
uint32_t GetStopID () const
void SetStopID (uint32_t stop_id)
Public Member Functions inherited from lldb_private::ExecutionContextScope
virtual ~ExecutionContextScope ()=default
Protected Member Functions
bool ReadGPR () override
bool ReadFPR () override
bool WriteGPR () override
bool WriteFPR () override
Protected Member Functions inherited from RegisterContextPOSIX_arm64
virtual const lldb_private::RegisterInfo * GetRegisterInfo ()
bool IsGPR (unsigned reg)
bool IsFPR (unsigned reg)
size_t GetFPUSize ()
bool IsSVE (unsigned reg) const
bool IsPAuth (unsigned reg) const
bool IsTLS (unsigned reg) const
bool IsSME (unsigned reg) const
bool IsMTE (unsigned reg) const
bool IsFPMR (unsigned reg) const
bool IsGCS (unsigned reg) const
bool IsPOE (unsigned reg) const
bool IsSVEZ (unsigned reg) const
bool IsSVEP (unsigned reg) const
bool IsSVEVG (unsigned reg) const
bool IsSMEZA (unsigned reg) const
uint32_t GetRegNumSVEZ0 () const
uint32_t GetRegNumSVEFFR () const
uint32_t GetRegNumFPCR () const
uint32_t GetRegNumFPSR () const
Protected Member Functions inherited from lldb_private::RegisterContext
virtual bool BehavesLikeZerothFrame () const
Indicates that this frame is currently executing code, that the PC value is not a return-pc but an actual executing instruction.
Private Member Functions
std::optional< int > GetOsreldate ()
Private Attributes
lldb::addr_t m_pcb_addr
Additional Inherited Members
Protected Attributes inherited from RegisterContextPOSIX_arm64
std::unique_ptr< RegisterInfoPOSIX_arm64 > m_register_info_up
Protected Attributes inherited from lldb_private::RegisterContext
Thread & m_thread
uint32_t m_concrete_frame_idx
uint32_t m_stop_id
Detailed Description
Definition at line 17 of file RegisterContextFreeBSDKernelCore_arm64.h.
Constructor & Destructor Documentation
RegisterContextFreeBSDKernelCore_arm64()
RegisterContextFreeBSDKernelCore_arm64::RegisterContextFreeBSDKernelCore_arm64 (lldb_private::Thread & thread, std::unique_ptr< RegisterInfoPOSIX_arm64 > register_info_up, lldb::addr_t pcb_addr)
Definition at line 24 of file RegisterContextFreeBSDKernelCore_arm64.cpp.
References m_pcb_addr, and RegisterContextPOSIX_arm64::RegisterContextPOSIX_arm64().
Member Function Documentation
GetOsreldate()
std::optional< int > RegisterContextFreeBSDKernelCore_arm64::GetOsreldate () private
Definition at line 173 of file RegisterContextFreeBSDKernelCore_arm64.cpp.
References error(), lldb::eSymbolTypeData, lldb_private::ModuleList::FindSymbolsWithNameAndType(), lldb_private::SymbolContextList::GetContextAtIndex(), lldb_private::Target::GetImages(), lldb_private::Symbol::GetLoadAddress(), lldb_private::SymbolContextList::GetSize(), LLDB_INVALID_ADDRESS, lldb_private::RegisterContext::m_thread, and lldb_private::SymbolContext::symbol.
Referenced by ReadRegister().
ReadFPR()
bool RegisterContextFreeBSDKernelCore_arm64::ReadFPR () override protected virtual
Implements RegisterContextPOSIX_arm64.
Definition at line 32 of file RegisterContextFreeBSDKernelCore_arm64.cpp.
ReadGPR()
bool RegisterContextFreeBSDKernelCore_arm64::ReadGPR () override protected virtual
Implements RegisterContextPOSIX_arm64.
Definition at line 30 of file RegisterContextFreeBSDKernelCore_arm64.cpp.
ReadRegister()
bool RegisterContextFreeBSDKernelCore_arm64::ReadRegister (const lldb_private::RegisterInfo * reg_info, lldb_private::RegisterValue & value) override virtual
Implements lldb_private::RegisterContext.
Definition at line 44 of file RegisterContextFreeBSDKernelCore_arm64.cpp.
References lldb::eRegisterKindLLDB, error(), lldb_private::GetLog(), GetOsreldate(), lldb_private::gpr_fp_arm64, lldb_private::gpr_lr_arm64, lldb_private::gpr_pc_arm64, lldb_private::gpr_sp_arm64, lldb_private::gpr_x0_arm64, lldb_private::gpr_x10_arm64, lldb_private::gpr_x11_arm64, lldb_private::gpr_x12_arm64, lldb_private::gpr_x13_arm64, lldb_private::gpr_x14_arm64, lldb_private::gpr_x15_arm64, lldb_private::gpr_x16_arm64, lldb_private::gpr_x17_arm64, lldb_private::gpr_x18_arm64, lldb_private::gpr_x19_arm64, lldb_private::gpr_x1_arm64, lldb_private::gpr_x20_arm64, lldb_private::gpr_x21_arm64, lldb_private::gpr_x22_arm64, lldb_private::gpr_x23_arm64, lldb_private::gpr_x24_arm64, lldb_private::gpr_x25_arm64, lldb_private::gpr_x26_arm64, lldb_private::gpr_x27_arm64, lldb_private::gpr_x28_arm64, lldb_private::gpr_x2_arm64, lldb_private::gpr_x3_arm64, lldb_private::gpr_x4_arm64, lldb_private::gpr_x5_arm64, lldb_private::gpr_x6_arm64, lldb_private::gpr_x7_arm64, lldb_private::gpr_x8_arm64, lldb_private::gpr_x9_arm64, lldb_private::RegisterInfo::kinds, LLDB_INVALID_ADDRESS, LLDB_LOGF, m_pcb_addr, lldb_private::RegisterContext::m_thread, lldb_private::Object, and sp.
WriteFPR()
bool RegisterContextFreeBSDKernelCore_arm64::WriteFPR () override protected virtual
Implements RegisterContextPOSIX_arm64.
Definition at line 39 of file RegisterContextFreeBSDKernelCore_arm64.cpp.
WriteGPR()
bool RegisterContextFreeBSDKernelCore_arm64::WriteGPR () override protected virtual
Implements RegisterContextPOSIX_arm64.
Definition at line 34 of file RegisterContextFreeBSDKernelCore_arm64.cpp.
WriteRegister()
bool RegisterContextFreeBSDKernelCore_arm64::WriteRegister (const lldb_private::RegisterInfo * reg_info, const lldb_private::RegisterValue & value) override virtual
Implements lldb_private::RegisterContext.
Definition at line 168 of file RegisterContextFreeBSDKernelCore_arm64.cpp.
Member Data Documentation
m_pcb_addr
lldb::addr_t RegisterContextFreeBSDKernelCore_arm64::m_pcb_addr private
Definition at line 41 of file RegisterContextFreeBSDKernelCore_arm64.h.
Referenced by ReadRegister(), and RegisterContextFreeBSDKernelCore_arm64().
The documentation for this class was generated from the following files:
RegisterContextFreeBSDKernelCore_arm64.h
RegisterContextFreeBSDKernelCore_arm64.cpp