LLDB: ABISysV_mips64 Class Reference
ABISysV_mips64 Class Reference
#include <ABISysV_mips64.h>
Public Member Functions
~ABISysV_mips64 () override=default
size_t GetRedZoneSize () const override
bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override
bool GetArgumentValues (lldb_private::Thread &thread, lldb_private::ValueList &values) const override
lldb_private::Status SetReturnValueObject (lldb::StackFrameSP &frame_sp, lldb::ValueObjectSP &new_value) override
lldb::ValueObjectSP GetReturnValueObjectImpl (lldb_private::Thread &thread, lldb_private::CompilerType &type) const override
lldb::UnwindPlanSP CreateFunctionEntryUnwindPlan () override
lldb::UnwindPlanSP CreateDefaultUnwindPlan () override
bool RegisterIsVolatile (const lldb_private::RegisterInfo *reg_info) override
bool IsSoftFloat (uint32_t fp_flag) const
bool CallFrameAddressIsValid (lldb::addr_t cfa) override
bool CodeAddressIsValid (lldb::addr_t pc) override
const lldb_private::RegisterInfo * GetRegisterInfoArray (uint32_t &count) override
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::RegInfoBasedABI
void AugmentRegisterInfo (std::vector< DynamicRegisterInfo::Register > &regs) override
Public Member Functions inherited from lldb_private::ABI
~ABI () override
virtual bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::Type &prototype, llvm::ArrayRef< CallArgument > args) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, CompilerType &type, bool persistent=true) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, llvm::Type &type, bool persistent=true) const
virtual bool GetFallbackRegisterLocation (const RegisterInfo *reg_info, UnwindPlan::Row::AbstractRegisterLocation &unwind_regloc)
virtual lldb::addr_t FixAnyAddress (lldb::addr_t pc)
Use this method when you do not know, or do not care what kind of address you are fixing.
llvm::MCRegisterInfo & GetMCRegisterInfo ()
virtual bool GetPointerReturnRegister (const char *&name)
virtual uint64_t GetStackFrameSize ()
virtual lldb::addr_t FixCodeAddress (lldb::addr_t pc)
Some targets might use bits in a code address to indicate a mode switch.
virtual lldb::addr_t FixDataAddress (lldb::addr_t pc)
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static lldb::ABISP CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec &arch)
static llvm::StringRef GetPluginNameStatic ()
Static Public Member Functions inherited from lldb_private::ABI
static lldb::ABISP FindPlugin (lldb::ProcessSP process_sp, const ArchSpec &arch)
Protected Member Functions
void CreateRegisterMapIfNeeded ()
lldb::ValueObjectSP GetReturnValueObjectSimple (lldb_private::Thread &thread, lldb_private::CompilerType &ast_type) const
bool RegisterIsCalleeSaved (const lldb_private::RegisterInfo *reg_info)
Protected Member Functions inherited from lldb_private::RegInfoBasedABI
bool GetRegisterInfoByName (llvm::StringRef name, RegisterInfo &info)
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Protected Member Functions inherited from lldb_private::ABI
virtual lldb::ValueObjectSP GetReturnValueObjectImpl (Thread &thread, llvm::Type &ir_type) const
lldb::ProcessSP GetProcessSP () const
Request to get a Process shared pointer.
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Additional Inherited Members
Static Protected Member Functions inherited from lldb_private::ABI
static std::unique_ptr< llvm::MCRegisterInfo > MakeMCRegisterInfo (const ArchSpec &arch)
Utility function to construct a MCRegisterInfo using the ArchSpec triple.
Protected Attributes inherited from lldb_private::ABI
lldb::ProcessWP m_process_wp
std::unique_ptr< llvm::MCRegisterInfo > m_mc_register_info_up
Detailed Description
Definition at line 15 of file ABISysV_mips64.h.
Constructor & Destructor Documentation
~ABISysV_mips64()
ABISysV_mips64::~ABISysV_mips64 () override default
References sp.
Member Function Documentation
CallFrameAddressIsValid()
bool ABISysV_mips64::CallFrameAddressIsValid (lldb::addr_t cfa) inline override virtual
Implements lldb_private::ABI.
Definition at line 56 of file ABISysV_mips64.h.
CodeAddressIsValid()
bool ABISysV_mips64::CodeAddressIsValid (lldb::addr_t pc) inline override virtual
Implements lldb_private::ABI.
Definition at line 65 of file ABISysV_mips64.h.
References pc.
CreateDefaultUnwindPlan()
UnwindPlanSP ABISysV_mips64::CreateDefaultUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 1146 of file ABISysV_mips64.cpp.
References dwarf_pc, dwarf_r29, dwarf_r31, lldb_private::eLazyBoolNo, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), lldb_private::UnwindPlan::Row::SetRegisterLocationToRegister(), and lldb_private::UnwindPlan::Row::SetUnspecifiedRegistersAreUndefined().
CreateFunctionEntryUnwindPlan()
UnwindPlanSP ABISysV_mips64::CreateFunctionEntryUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 1129 of file ABISysV_mips64.cpp.
References dwarf_pc, dwarf_r29, dwarf_r31, lldb_private::eLazyBoolNo, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), and lldb_private::UnwindPlan::Row::SetRegisterLocationToRegister().
CreateInstance()
ABISP ABISysV_mips64::CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec & arch) static
Definition at line 553 of file ABISysV_mips64.cpp.
References lldb_private::ArchSpec::GetTriple(), and lldb_private::ABI::MakeMCRegisterInfo().
Referenced by Initialize(), and Terminate().
CreateRegisterMapIfNeeded()
void ABISysV_mips64::CreateRegisterMapIfNeeded () protected
GetArgumentValues()
bool ABISysV_mips64::GetArgumentValues (lldb_private::Thread & thread, lldb_private::ValueList & values) const override virtual
Implements lldb_private::ABI.
Definition at line 651 of file ABISysV_mips64.cpp.
GetPluginName()
llvm::StringRef ABISysV_mips64::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 88 of file ABISysV_mips64.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef ABISysV_mips64::GetPluginNameStatic () inline static
Definition at line 84 of file ABISysV_mips64.h.
Referenced by GetPluginName(), and Initialize().
GetRedZoneSize()
size_t ABISysV_mips64::GetRedZoneSize () const override virtual
Implements lldb_private::ABI.
Definition at line 548 of file ABISysV_mips64.cpp.
GetRegisterInfoArray()
const lldb_private::RegisterInfo * ABISysV_mips64::GetRegisterInfoArray (uint32_t & count) override virtual
Implements lldb_private::RegInfoBasedABI.
Definition at line 543 of file ABISysV_mips64.cpp.
References g_register_infos_mips64, and k_num_register_infos.
GetReturnValueObjectImpl()
ValueObjectSP ABISysV_mips64::GetReturnValueObjectImpl (lldb_private::Thread & thread, lldb_private::CompilerType & type) const override virtual
Implements lldb_private::ABI.
Definition at line 734 of file ABISysV_mips64.cpp.
References lldb_private::RegisterInfo::byte_size, lldb_private::DataExtractor::CopyByteOrderedData(), lldb_private::ValueObjectConstResult::Create(), lldb_private::ValueObjectMemory::Create(), lldb::eByteOrderLittle, lldb_private::ArchSpec::eMIPS_ABI_FP_mask, error(), lldb_private::ArchSpec::GetAddressByteSize(), lldb_private::Target::GetArchitecture(), lldb_private::RegisterValue::GetAsMemoryData(), lldb_private::ArchSpec::GetByteOrder(), lldb_private::CompilerType::GetByteSize(), lldb_private::DataExtractor::GetByteSize(), lldb_private::RegisterValue::GetData(), lldb_private::DataExtractor::GetDouble(), lldb_private::CompilerType::GetFieldAtIndex(), lldb_private::ArchSpec::GetFlags(), lldb_private::DataExtractor::GetFloat(), lldb_private::CompilerType::GetNumFields(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::Value::GetScalar(), lldb_private::ExecutionContext::GetTargetPtr(), lldb_private::CompilerType::GetTypeInfo(), lldb_private::DataExtractor::GetU64(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), lldb_private::CompilerType::IsPointerType(), IsSoftFloat(), lldb_private::RegisterContext::ReadRegister(), lldb_private::RegisterContext::ReadRegisterAsUnsigned(), lldb_private::Value::Scalar, lldb_private::Value::SetCompilerType(), lldb_private::DataExtractor::SetData(), lldb_private::Value::SetValueType(), and UINT32_MAX.
GetReturnValueObjectSimple()
ValueObjectSP ABISysV_mips64::GetReturnValueObjectSimple (lldb_private::Thread & thread, lldb_private::CompilerType & ast_type) const protected
Definition at line 728 of file ABISysV_mips64.cpp.
Initialize()
void ABISysV_mips64::Initialize () static
Definition at line 1186 of file ABISysV_mips64.cpp.
References CreateInstance(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Referenced by ABIMips::Initialize().
IsSoftFloat()
bool ABISysV_mips64::IsSoftFloat (uint32_t fp_flag) const
Definition at line 1167 of file ABISysV_mips64.cpp.
References lldb_private::ArchSpec::eMIPS_ABI_FP_SOFT.
Referenced by GetReturnValueObjectImpl().
PrepareTrivialCall()
bool ABISysV_mips64::PrepareTrivialCall (lldb_private::Thread & thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override virtual
Implements lldb_private::ABI.
Definition at line 560 of file ABISysV_mips64.cpp.
References lldb::eRegisterKindGeneric, error(), lldb_private::Expressions, lldb_private::GetLog(), lldb_private::RegisterContext::GetRegisterInfo(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::StreamString::GetString(), LLDB_LOGF, LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_RA, LLDB_REGNUM_GENERIC_SP, lldb_private::RegisterInfo::name, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), lldb_private::Log::PutString(), sp, and lldb_private::RegisterContext::WriteRegisterFromUnsigned().
RegisterIsCalleeSaved()
bool ABISysV_mips64::RegisterIsCalleeSaved (const lldb_private::RegisterInfo * reg_info) protected
Definition at line 1171 of file ABISysV_mips64.cpp.
References lldb_private::RegisterInfo::byte_offset.
Referenced by RegisterIsVolatile().
RegisterIsVolatile()
bool ABISysV_mips64::RegisterIsVolatile (const lldb_private::RegisterInfo * reg_info) override virtual
Implements lldb_private::ABI.
Definition at line 1163 of file ABISysV_mips64.cpp.
References RegisterIsCalleeSaved().
SetReturnValueObject()
Status ABISysV_mips64::SetReturnValueObject (lldb::StackFrameSP & frame_sp, lldb::ValueObjectSP & new_value) override virtual
Implements lldb_private::ABI.
Definition at line 656 of file ABISysV_mips64.cpp.
References lldb_private::Status::AsCString(), error(), lldb_private::Status::Fail(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataExtractor::GetMaxU64(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::CompilerType::GetTypeInfo(), and lldb_private::RegisterContext::WriteRegisterFromUnsigned().
Terminate()
void ABISysV_mips64::Terminate () static
Definition at line 1191 of file ABISysV_mips64.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Referenced by ABIMips::Terminate().
The documentation for this class was generated from the following files:
ABISysV_mips64.h
ABISysV_mips64.cpp