LLDB: lldb_private::ValueLocker Class Reference
lldb_private::ValueLocker Class Reference
#include <ValueObject.h>
Public Member Functions
ValueLocker ()=default
lldb::ValueObjectSP GetLockedSP (ValueImpl &in_value)
Status & GetError ()
Private Attributes
Process::StopLocker m_stop_locker
std::unique_lock< std::recursive_mutex > m_lock
Status m_lock_error
Detailed Description
Definition at line 1185 of file ValueObject.h.
Constructor & Destructor Documentation
ValueLocker()
lldb_private::ValueLocker::ValueLocker () default
Member Function Documentation
GetError()
Status & lldb_private::ValueLocker::GetError () inline
Definition at line 1193 of file ValueObject.h.
References m_lock_error.
Referenced by lldb::SBValue::GetError(), lldb::SBValue::GetSP(), lldb::SBValue::GetValueAsSigned(), lldb::SBValue::GetValueAsUnsigned(), lldb::SBValue::SetData(), and lldb::SBValue::Watch().
GetLockedSP()
lldb::ValueObjectSP lldb_private::ValueLocker::GetLockedSP (ValueImpl & in_value) inline
Definition at line 1189 of file ValueObject.h.
References lldb_private::ValueImpl::GetSP(), m_lock, m_lock_error, and m_stop_locker.
Referenced by lldb_private::ScriptInterpreter::GetOpaqueTypeFromSBValue(), and lldb::SBValue::GetSP().
Member Data Documentation
m_lock
std::unique_lock<std::recursive_mutex> lldb_private::ValueLocker::m_lock private
Definition at line 1197 of file ValueObject.h.
Referenced by GetLockedSP().
m_lock_error
Status lldb_private::ValueLocker::m_lock_error private
Definition at line 1198 of file ValueObject.h.
Referenced by GetError(), and GetLockedSP().
m_stop_locker
Process::StopLocker lldb_private::ValueLocker::m_stop_locker private
Definition at line 1196 of file ValueObject.h.
Referenced by GetLockedSP().
The documentation for this class was generated from the following file:
ValueObject.h