LLDB: lldb_private::plugin::dwarf::DWARFDIE::child_iterator Class Reference
lldb_private::plugin::dwarf::DWARFDIE::child_iterator Class Reference
#include <DWARFDIE.h>
Public Member Functions
child_iterator ()=default
child_iterator (const DWARFDIE &parent)
bool operator== (const child_iterator &it) const
const DWARFDIE & operator* () const
DWARFDIE & operator* ()
child_iterator & operator++ ()
Private Attributes
DWARFDIE m_die
The current child or an invalid DWARFDie.
Detailed Description
Definition at line 144 of file DWARFDIE.h.
Constructor & Destructor Documentation
child_iterator() [1/2]
lldb_private::plugin::dwarf::DWARFDIE::child_iterator::child_iterator () default
Referenced by operator++(), and operator==().
child_iterator() [2/2]
lldb_private::plugin::dwarf::DWARFDIE::child_iterator::child_iterator (const DWARFDIE & parent) inline
Definition at line 152 of file DWARFDIE.h.
References lldb_private::plugin::dwarf::DWARFDIE::GetFirstChild(), and m_die.
Member Function Documentation
operator*() [1/2]
DWARFDIE & lldb_private::plugin::dwarf::DWARFDIE::child_iterator::operator* () inline
Definition at line 166 of file DWARFDIE.h.
References m_die.
operator*() [2/2]
const DWARFDIE & lldb_private::plugin::dwarf::DWARFDIE::child_iterator::operator* () const inline
Definition at line 162 of file DWARFDIE.h.
References m_die.
operator++()
child_iterator & lldb_private::plugin::dwarf::DWARFDIE::child_iterator::operator++ () inline
Definition at line 170 of file DWARFDIE.h.
References child_iterator(), and m_die.
operator==()
bool lldb_private::plugin::dwarf::DWARFDIE::child_iterator::operator== (const child_iterator & it) const inline
Definition at line 153 of file DWARFDIE.h.
References child_iterator(), lldb_private::plugin::dwarf::DWARFBaseDIE::IsValid(), and m_die.
Member Data Documentation
m_die
DWARFDIE lldb_private::plugin::dwarf::DWARFDIE::child_iterator::m_die private
The current child or an invalid DWARFDie.
Definition at line 148 of file DWARFDIE.h.
Referenced by child_iterator(), operator*(), operator*(), operator++(), and operator==().
The documentation for this class was generated from the following file:
DWARFDIE.h