LLDB: ObjectContainerUniversalMachO Class Reference
ObjectContainerUniversalMachO Class Reference
#include <ObjectContainerUniversalMachO.h>
Classes
struct FatArch
Public Member Functions
ObjectContainerUniversalMachO (const lldb::ModuleSP &module_sp, lldb::DataBufferSP &data_sp, lldb::offset_t data_offset, const lldb_private::FileSpec *file, lldb::offset_t offset, lldb::offset_t length)
~ObjectContainerUniversalMachO () override
bool ParseHeader () override
Attempts to parse the object header.
size_t GetNumArchitectures () const override
Get the number of architectures in this object file.
bool GetArchitectureAtIndex (uint32_t cpu_idx, lldb_private::ArchSpec &arch) const override
Gets the architecture given an index.
lldb::ObjectFileSP GetObjectFile (const lldb_private::FileSpec *file) override
Selects an architecture in an object file.
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::ObjectContainer
ObjectContainer (const lldb::ModuleSP &module_sp, const FileSpec *file, lldb::offset_t file_offset, lldb::offset_t length, lldb::DataBufferSP data_sp, lldb::offset_t data_offset)
Construct with a parent module, offset, and header data.
~ObjectContainer () override=default
Destructor.
virtual lldb::addr_t GetOffset () const
Returns the offset into a file at which this object resides.
virtual lldb::addr_t GetByteSize () const
virtual size_t GetNumObjects () const
Get the number of objects within this object file (archives).
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Public Member Functions inherited from lldb_private::ModuleChild
ModuleChild (const lldb::ModuleSP &module_sp)
Construct with owning module.
~ModuleChild ()
Destructor.
const ModuleChild & operator= (const ModuleChild &rhs)
Assignment operator.
lldb::ModuleSP GetModule () const
Get const accessor for the module pointer.
void SetModule (const lldb::ModuleSP &module_sp)
Set accessor for the module pointer.
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static lldb_private::ObjectContainer * CreateInstance (const lldb::ModuleSP &module_sp, lldb::DataBufferSP &data_sp, lldb::offset_t data_offset, const lldb_private::FileSpec *file, lldb::offset_t offset, lldb::offset_t length)
static size_t GetModuleSpecifications (const lldb_private::FileSpec &file, lldb::DataExtractorSP &extractor_sp, lldb::offset_t data_offset, lldb::offset_t file_offset, lldb::offset_t length, lldb_private::ModuleSpecList &specs)
static bool MagicBytesMatch (const lldb_private::DataExtractor &data)
Static Public Member Functions inherited from lldb_private::ObjectContainer
static lldb::ObjectContainerSP FindPlugin (const lldb::ModuleSP &module_sp, const lldb::ProcessSP &process_sp, lldb::addr_t header_addr, lldb::WritableDataBufferSP file_data_sp)
Static Protected Member Functions
static bool ParseHeader (lldb_private::DataExtractor &data, llvm::MachO::fat_header &header, std::vector< FatArch > &fat_archs)
Protected Attributes
llvm::MachO::fat_header m_header
std::vector< FatArch > m_fat_archs
Protected Attributes inherited from lldb_private::ObjectContainer
FileSpec m_file
The file that represents this container objects (which can be different from the module's file).
lldb::addr_t m_offset
The offset in bytes into the file, or the address in memory.
lldb::addr_t m_length
The size in bytes if known (can be zero).
lldb::DataExtractorSP m_extractor_sp
The data for this object file so things can be parsed lazily.
Protected Attributes inherited from lldb_private::ModuleChild
lldb::ModuleWP m_module_wp
The Module that owns the object that inherits from this class.
Detailed Description
Definition at line 16 of file ObjectContainerUniversalMachO.h.
Constructor & Destructor Documentation
ObjectContainerUniversalMachO()
ObjectContainerUniversalMachO::ObjectContainerUniversalMachO (const lldb::ModuleSP & module_sp, lldb::DataBufferSP & data_sp, lldb::offset_t data_offset, const lldb_private::FileSpec * file, lldb::offset_t offset, lldb::offset_t length)
Definition at line 64 of file ObjectContainerUniversalMachO.cpp.
References m_fat_archs, m_header, and lldb_private::ObjectContainer::ObjectContainer().
Referenced by CreateInstance().
~ObjectContainerUniversalMachO()
ObjectContainerUniversalMachO::~ObjectContainerUniversalMachO () override default
Member Function Documentation
CreateInstance()
ObjectContainer * ObjectContainerUniversalMachO::CreateInstance (const lldb::ModuleSP & module_sp, lldb::DataBufferSP & data_sp, lldb::offset_t data_offset, const lldb_private::FileSpec * file, lldb::offset_t offset, lldb::offset_t length) static
Definition at line 36 of file ObjectContainerUniversalMachO.cpp.
References MagicBytesMatch(), lldb_private::ObjectContainer::ObjectContainer(), ObjectContainerUniversalMachO(), and lldb_private::DataExtractor::SetData().
Referenced by LLDB_PLUGIN_DEFINE_ADV(), and Terminate().
GetArchitectureAtIndex()
bool ObjectContainerUniversalMachO::GetArchitectureAtIndex (uint32_t idx, lldb_private::ArchSpec & arch) const override virtual
Gets the architecture given an index.
Copies the architecture specification for index idx.
Parameters
[in] idx The architecture index to extract.
[out] arch A architecture object that will be filled in if idx is a architecture valid index.
Returns
Returns true if idx is valid and arch has been filled in, false otherwise.
See also
ObjectContainer::GetNumArchitectures() const
Reimplemented from lldb_private::ObjectContainer.
Definition at line 138 of file ObjectContainerUniversalMachO.cpp.
References lldb_private::eArchTypeMachO, m_fat_archs, m_header, and lldb_private::ArchSpec::SetArchitecture().
Referenced by GetObjectFile().
GetModuleSpecifications()
size_t ObjectContainerUniversalMachO::GetModuleSpecifications (const lldb_private::FileSpec & file, lldb::DataExtractorSP & extractor_sp, lldb::offset_t data_offset, lldb::offset_t file_offset, lldb::offset_t length, lldb_private::ModuleSpecList & specs) static
Definition at line 191 of file ObjectContainerUniversalMachO.cpp.
References lldb_private::ObjectFile::GetModuleSpecifications(), lldb_private::ModuleSpecList::GetSize(), MagicBytesMatch(), and ParseHeader().
Referenced by LLDB_PLUGIN_DEFINE_ADV().
GetNumArchitectures()
size_t ObjectContainerUniversalMachO::GetNumArchitectures () const override virtual
Get the number of architectures in this object file.
The default implementation returns 1 as for object files that contain a single architecture. ObjectContainer instances that contain more than one architecture should override this function and return an appropriate value.
Returns
The number of architectures contained in this object file.
Reimplemented from lldb_private::ObjectContainer.
Definition at line 134 of file ObjectContainerUniversalMachO.cpp.
References m_header.
GetObjectFile()
ObjectFileSP ObjectContainerUniversalMachO::GetObjectFile (const lldb_private::FileSpec * file) override virtual
Selects an architecture in an object file.
Object files that contain a single architecture should verify that the specified arch matches the architecture in the object file and return true or false accordingly.
Object files that contain more than one architecture should attempt to select that architecture, and if successful, clear out any previous state from any previously selected architecture and prepare to return information for the new architecture.
Returns
Returns a pointer to the object file of the requested arch and optional name. Returns nullptr of no such object file exists in the container.
Implements lldb_private::ObjectContainer.
Definition at line 149 of file ObjectContainerUniversalMachO.cpp.
References lldb_private::ObjectFile::FindPlugin(), GetArchitectureAtIndex(), lldb_private::Target::GetDefaultArchitecture(), lldb_private::ModuleChild::GetModule(), lldb_private::ObjectContainer::GetOffset(), lldb_private::ArchSpec::IsCompatibleMatch(), lldb_private::ArchSpec::IsExactMatch(), lldb_private::ArchSpec::IsValid(), LLDB_ARCH_DEFAULT, m_fat_archs, m_header, lldb_private::ObjectContainer::m_offset, and lldb_private::ArchSpec::SetTriple().
GetPluginDescriptionStatic()
llvm::StringRef ObjectContainerUniversalMachO::GetPluginDescriptionStatic () inline static
Definition at line 33 of file ObjectContainerUniversalMachO.h.
Referenced by LLDB_PLUGIN_DEFINE_ADV().
GetPluginName()
llvm::StringRef ObjectContainerUniversalMachO::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 62 of file ObjectContainerUniversalMachO.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef ObjectContainerUniversalMachO::GetPluginNameStatic () inline static
Definition at line 31 of file ObjectContainerUniversalMachO.h.
Referenced by GetPluginName(), and LLDB_PLUGIN_DEFINE_ADV().
Initialize()
void ObjectContainerUniversalMachO::Initialize () static
MagicBytesMatch()
bool ObjectContainerUniversalMachO::MagicBytesMatch (const lldb_private::DataExtractor & data) static
Definition at line 57 of file ObjectContainerUniversalMachO.cpp.
References lldb_private::DataExtractor::GetU32().
Referenced by CreateInstance(), and GetModuleSpecifications().
ParseHeader() [1/2]
bool ObjectContainerUniversalMachO::ParseHeader () override virtual
Attempts to parse the object header.
This function is used as a test to see if a given plug-in instance can parse the header data already contained in ObjectContainer::m_extractor_sp. If an object file parser does not recognize that magic bytes in a header, false should be returned and the next plug-in can attempt to parse an object file.
Returns
Returns true if the header was parsed successfully, false otherwise.
Implements lldb_private::ObjectContainer.
Definition at line 76 of file ObjectContainerUniversalMachO.cpp.
References lldb_private::ObjectContainer::m_extractor_sp, m_fat_archs, m_header, and ParseHeader().
Referenced by GetModuleSpecifications(), and ParseHeader().
ParseHeader() [2/2]
bool ObjectContainerUniversalMachO::ParseHeader (lldb_private::DataExtractor & data, llvm::MachO::fat_header & header, std::vector< FatArch > & fat_archs) static protected
Definition at line 85 of file ObjectContainerUniversalMachO.cpp.
References lldb::eByteOrderBig, lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU64(), lldb_private::DataExtractor::SetAddressByteSize(), lldb_private::DataExtractor::SetByteOrder(), and lldb_private::DataExtractor::ValidOffsetForDataOfSize().
Terminate()
void ObjectContainerUniversalMachO::Terminate () static
Definition at line 32 of file ObjectContainerUniversalMachO.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Member Data Documentation
m_fat_archs
std::vector<FatArch> ObjectContainerUniversalMachO::m_fat_archs protected
Definition at line 101 of file ObjectContainerUniversalMachO.h.
Referenced by GetArchitectureAtIndex(), GetObjectFile(), ObjectContainerUniversalMachO(), and ParseHeader().
m_header
llvm::MachO::fat_header ObjectContainerUniversalMachO::m_header protected
Definition at line 65 of file ObjectContainerUniversalMachO.h.
Referenced by GetArchitectureAtIndex(), GetNumArchitectures(), GetObjectFile(), ObjectContainerUniversalMachO(), and ParseHeader().
The documentation for this class was generated from the following files:
ObjectContainerUniversalMachO.h
ObjectContainerUniversalMachO.cpp