LLDB: DYLDRendezvous Class Reference
DYLDRendezvous Class Reference
Interface to the runtime linker.
#include <DYLDRendezvous.h>
Classes
struct Rendezvous
struct SOEntry
Structure representing the shared objects currently loaded into the inferior process.
struct ThreadInfo
Public Types
enum RendezvousState { eConsistent , eAdd , eDelete }
Constants describing the state of the rendezvous.
typedef SOEntryList::const_iterator iterator
Public Member Functions
DYLDRendezvous (lldb_private::Process *process)
void UpdateExecutablePath ()
Update the cached executable path.
bool Resolve ()
Update the internal snapshot of runtime linker rendezvous and recompute the currently loaded modules.
bool IsValid ()
lldb::addr_t GetRendezvousAddress () const
uint64_t GetVersion () const
lldb::addr_t GetLinkMapAddress () const
lldb::addr_t GetBreakAddress () const
A breakpoint should be set at this address and Resolve called on each hit.
uint64_t GetState () const
Returns the current state of the rendezvous structure.
lldb::addr_t GetLDBase () const
const ThreadInfo & GetThreadInfo ()
bool ModulesDidLoad () const
bool ModulesDidUnload () const
void DumpToLog (lldb_private::Log *log) const
iterator begin () const
Iterators over all currently loaded modules.
iterator end () const
iterator loaded_begin () const
Iterators over all modules loaded into the inferior since the last call to Resolve().
iterator loaded_end () const
iterator unloaded_begin () const
Iterators over all modules unloaded from the inferior since the last call to Resolve().
iterator unloaded_end () const
Protected Types
enum PThreadField { eSize , eNElem , eOffset }
enum RendezvousAction { eNoAction , eTakeSnapshot , eAddModules , eRemoveModules }
typedef std::list< SOEntry > SOEntryList
Protected Member Functions
lldb::addr_t ReadWord (lldb::addr_t addr, uint64_t *dst, size_t size)
Reads an unsigned integer of size bytes from the inferior's address space starting at addr.
lldb::addr_t ReadPointer (lldb::addr_t addr, lldb::addr_t *dst)
Reads an address from the inferior's address space starting at addr.
std::string ReadStringFromMemory (lldb::addr_t addr)
Reads a null-terminated C string from the memory location starting at addr.
bool ReadSOEntryFromMemory (lldb::addr_t addr, SOEntry &entry)
Reads an SOEntry starting at addr.
bool UpdateSOEntries ()
Updates the current set of SOEntries, the set of added entries, and the set of removed entries.
bool UpdateSOEntriesFromRemote ()
Same as UpdateSOEntries but it gets the list of loaded modules from the remote debug server (faster when supported).
bool FillSOEntryFromModuleInfo (LoadedModuleInfoList::LoadedModuleInfo const &modInfo, SOEntry &entry)
bool SaveSOEntriesFromRemote (const LoadedModuleInfoList &module_list)
bool AddSOEntriesFromRemote (const LoadedModuleInfoList &module_list)
bool RemoveSOEntriesFromRemote (const LoadedModuleInfoList &module_list)
bool AddSOEntries ()
bool RemoveSOEntries ()
void UpdateBaseAddrIfNecessary (SOEntry &entry, std::string const &file_path)
void UpdateFileSpecIfNecessary (SOEntry &entry)
bool SOEntryIsMainExecutable (const SOEntry &entry)
bool TakeSnapshot (SOEntryList &entry_list)
Reads the current list of shared objects according to the link map supplied by the runtime linker.
bool FindMetadata (const char *name, PThreadField field, uint32_t &value)
bool IsCoreFile () const
RendezvousAction GetAction () const
Returns the current action to be taken given the current and previous state.
Static Protected Member Functions
static const char * StateToCStr (RendezvousState state)
static const char * ActionToCStr (RendezvousAction action)
Protected Attributes
lldb_private::Process * m_process
lldb_private::FileSpec m_exe_file_spec
lldb::addr_t m_rendezvous_addr
Location of the r_debug structure in the inferiors address space.
bool m_executable_interpreter
Rendezvous m_current
Current and previous snapshots of the rendezvous structure.
Rendezvous m_previous
LoadedModuleInfoList m_loaded_modules
List of currently loaded SO modules.
SOEntryList m_soentries
List of SOEntry objects corresponding to the current link map state.
SOEntryList m_added_soentries
List of SOEntry's added to the link map since the last call to Resolve().
SOEntryList m_removed_soentries
List of SOEntry's removed from the link map since the last call to Resolve().
ThreadInfo m_thread_info
Threading metadata read from the inferior.
Private Member Functions
lldb::addr_t ResolveRendezvousAddress ()
Locates the address of the rendezvous structure.
Detailed Description
Interface to the runtime linker.
A structure is present in a processes memory space which is updated by the dynamic linker each time a module is loaded or unloaded. This class provides an interface to this structure and maintains a consistent snapshot of the currently loaded modules.
In the dynamic loader sources, this structure has a type of "r_debug" and the name of the structure us "_r_debug". The structure looks like:
struct r_debug { // Version number for this protocol. int r_version; // Head of the chain of loaded objects. struct link_map *r_map; // The address the debugger should set a breakpoint at in order to get // notified when shared libraries are added or removed uintptr_t r_brk; // This state value describes the mapping change taking place when the // 'r_brk' address is called. enum { RT_CONSISTENT, // Mapping change is complete. RT_ADD, // Beginning to add a new object. RT_DELETE, // Beginning to remove an object mapping. } r_state; // Base address the linker is loaded at. uintptr_t r_ldbase; };
The dynamic linker then defines a global variable using this type named "_r_debug":
r_debug _r_debug;
The DYLDRendezvous class defines a local version of this structure named DYLDRendezvous::Rendezvous. See the definition inside the class definition for DYLDRendezvous.
This structure can be located by looking through the .dynamic section in the main executable and finding the DT_DEBUG tag entry. This value starts out with a value of zero when the program first is initially loaded, but the address of the "_r_debug" structure from ld.so is filled in by the dynamic loader during program initialization code in ld.so prior to loading or unloading and shared libraries.
The dynamic loader will update this structure as shared libraries are loaded and will call a specific function that LLDB knows to set a breakpoint on (from _r_debug.r_brk) so LLDB will find out when shared libraries are loaded or unloaded. Each time this breakpoint is hit, LLDB looks at the contents of this structure and the contents tell LLDB what needs to be done.
Currently we expect the "state" in this structure to change as things happen.
When any shared libraries are loaded the following happens:
_r_debug.r_map is updated with the new shared libraries. This is a doubly linked list of "link_map *" entries.
_r_debug.r_state is set to RT_ADD and the debugger notification function is called notifying the debugger that shared libraries are about to be added, but are not yet ready for use.
Once the the shared libraries are fully loaded, _r_debug.r_state is set to RT_CONSISTENT and the debugger notification function is called again notifying the debugger that shared libraries are ready for use. DYLDRendezvous must remember that the previous state was RT_ADD when it receives a RT_CONSISTENT in order to know to add libraries
When any shared libraries are unloaded the following happens:
_r_debug.r_map is updated and the unloaded libraries are removed.
_r_debug.r_state is set to RT_DELETE and the debugger notification function is called notifying the debugger that shared libraries are about to be removed.
Once the the shared libraries are removed _r_debug.r_state is set to RT_CONSISTENT and the debugger notification function is called again notifying the debugger that shared libraries have been removed. DYLDRendezvous must remember that the previous state was RT_DELETE when it receives a RT_CONSISTENT in order to know to remove libraries
Definition at line 107 of file DYLDRendezvous.h.
Member Typedef Documentation
iterator
typedef SOEntryList::const_iterator DYLDRendezvous::iterator
Definition at line 249 of file DYLDRendezvous.h.
SOEntryList
typedef std::list<SOEntry> DYLDRendezvous::SOEntryList protected
Definition at line 246 of file DYLDRendezvous.h.
Member Enumeration Documentation
PThreadField
enum DYLDRendezvous::PThreadField protected
Enumerator
eSize
eNElem
eOffset
Definition at line 348 of file DYLDRendezvous.h.
RendezvousAction
enum DYLDRendezvous::RendezvousAction protected
Enumerator
eNoAction
eTakeSnapshot
eAddModules
eRemoveModules
Definition at line 354 of file DYLDRendezvous.h.
RendezvousState
enum DYLDRendezvous::RendezvousState
Constants describing the state of the rendezvous.
These values are defined to match the r_debug.r_state enum from the actual dynamic loader sources.
See also
GetState().
Enumerator
eConsistent
eAdd
eDelete
Definition at line 208 of file DYLDRendezvous.h.
Constructor & Destructor Documentation
DYLDRendezvous()
DYLDRendezvous::DYLDRendezvous (lldb_private::Process * process)
Definition at line 54 of file DYLDRendezvous.cpp.
References LLDB_INVALID_ADDRESS, m_added_soentries, m_current, m_executable_interpreter, m_loaded_modules, m_previous, m_process, m_removed_soentries, m_rendezvous_addr, m_soentries, m_thread_info, and UpdateExecutablePath().
Member Function Documentation
ActionToCStr()
const char * DYLDRendezvous::ActionToCStr (RendezvousAction action) static protected
Definition at line 40 of file DYLDRendezvous.cpp.
References eAddModules, eNoAction, eRemoveModules, and eTakeSnapshot.
Referenced by UpdateSOEntries(), and UpdateSOEntriesFromRemote().
AddSOEntries()
bool DYLDRendezvous::AddSOEntries () protected
Definition at line 498 of file DYLDRendezvous.cpp.
References eAdd, m_added_soentries, m_current, m_previous, m_soentries, DYLDRendezvous::SOEntry::next, ReadSOEntryFromMemory(), SOEntryIsMainExecutable(), and UpdateFileSpecIfNecessary().
Referenced by UpdateSOEntries().
AddSOEntriesFromRemote()
bool DYLDRendezvous::AddSOEntriesFromRemote (const LoadedModuleInfoList & module_list) protected
Definition at line 435 of file DYLDRendezvous.cpp.
References FillSOEntryFromModuleInfo(), m_added_soentries, lldb_private::LoadedModuleInfoList::m_list, m_loaded_modules, m_soentries, SOEntryIsMainExecutable(), and UpdateFileSpecIfNecessary().
Referenced by UpdateSOEntriesFromRemote().
begin()
iterator DYLDRendezvous::begin () const inline
Iterators over all currently loaded modules.
Definition at line 252 of file DYLDRendezvous.h.
References m_soentries.
Referenced by DumpToLog(), and RemoveSOEntries().
DumpToLog()
void DYLDRendezvous::DumpToLog (lldb_private::Log * log) const
Definition at line 756 of file DYLDRendezvous.cpp.
References begin(), eAdd, eConsistent, eDelete, end(), GetBreakAddress(), GetLDBase(), GetLinkMapAddress(), GetRendezvousAddress(), GetState(), GetVersion(), LLDB_LOGF, and lldb_private::Log::PutCString().
end()
iterator DYLDRendezvous::end () const inline
Definition at line 253 of file DYLDRendezvous.h.
References m_soentries.
Referenced by DumpToLog(), and RemoveSOEntries().
FillSOEntryFromModuleInfo()
bool DYLDRendezvous::FillSOEntryFromModuleInfo (LoadedModuleInfoList::LoadedModuleInfo const & modInfo, SOEntry & entry) protected
Definition at line 390 of file DYLDRendezvous.cpp.
References DYLDRendezvous::SOEntry::base_addr, DYLDRendezvous::SOEntry::dyn_addr, DYLDRendezvous::SOEntry::file_spec, lldb_private::LoadedModuleInfoList::LoadedModuleInfo::get_base(), lldb_private::LoadedModuleInfoList::LoadedModuleInfo::get_dynamic(), lldb_private::LoadedModuleInfoList::LoadedModuleInfo::get_link_map(), lldb_private::LoadedModuleInfoList::LoadedModuleInfo::get_name(), DYLDRendezvous::SOEntry::link_addr, DYLDRendezvous::SOEntry::next, DYLDRendezvous::SOEntry::path_addr, DYLDRendezvous::SOEntry::prev, lldb_private::FileSpec::SetFile(), and UpdateBaseAddrIfNecessary().
Referenced by AddSOEntriesFromRemote(), RemoveSOEntriesFromRemote(), and SaveSOEntriesFromRemote().
FindMetadata()
bool DYLDRendezvous::FindMetadata (const char * name, PThreadField field, uint32_t & value) protected
Definition at line 706 of file DYLDRendezvous.cpp.
References error(), eSize, lldb::eSymbolTypeAny, lldb_private::ModuleList::FindSymbolsWithNameAndType(), lldb_private::Target::GetImages(), lldb_private::Address::GetOffset(), lldb_private::SymbolContextList::IsEmpty(), m_process, lldb_private::Target::ReadUnsignedIntegerFromMemory(), and lldb_private::Address::SetOffset().
Referenced by GetThreadInfo().
GetAction()
DYLDRendezvous::RendezvousAction DYLDRendezvous::GetAction () const protected
Returns the current action to be taken given the current and previous state.
Definition at line 228 of file DYLDRendezvous.cpp.
References lldb_private::DynamicLoader, eAdd, eAddModules, eConsistent, eDelete, eNoAction, eRemoveModules, eTakeSnapshot, lldb_private::GetLog(), IsCoreFile(), LLDB_LOG, m_current, and m_previous.
Referenced by UpdateSOEntries(), and UpdateSOEntriesFromRemote().
GetBreakAddress()
lldb::addr_t DYLDRendezvous::GetBreakAddress () const inline
A breakpoint should be set at this address and Resolve called on each hit.
Returns
the address of a function called by the runtime linker each time a module is loaded/unloaded, or about to be loaded/unloaded.
See also
Resolve()
Definition at line 180 of file DYLDRendezvous.h.
References m_current.
Referenced by DumpToLog().
GetLDBase()
lldb::addr_t DYLDRendezvous::GetLDBase () const inline
Returns
the base address of the runtime linker in the inferiors address space.
Definition at line 187 of file DYLDRendezvous.h.
References m_current.
Referenced by DumpToLog().
GetLinkMapAddress()
lldb::addr_t DYLDRendezvous::GetLinkMapAddress () const inline
Returns
address in the inferiors address space containing the linked list of shared object descriptors.
Definition at line 171 of file DYLDRendezvous.h.
References m_current.
Referenced by DumpToLog().
GetRendezvousAddress()
lldb::addr_t DYLDRendezvous::GetRendezvousAddress () const inline
Returns
the address of the rendezvous structure in the inferiors address space.
Definition at line 164 of file DYLDRendezvous.h.
References m_rendezvous_addr.
Referenced by DumpToLog().
GetState()
uint64_t DYLDRendezvous::GetState () const inline
Returns the current state of the rendezvous structure.
Definition at line 183 of file DYLDRendezvous.h.
References m_current.
Referenced by DumpToLog().
GetThreadInfo()
const DYLDRendezvous::ThreadInfo & DYLDRendezvous::GetThreadInfo ()
Returns
the thread layout metadata from the inferiors thread library.
Definition at line 736 of file DYLDRendezvous.cpp.
References eOffset, eSize, FindMetadata(), and m_thread_info.
GetVersion()
uint64_t DYLDRendezvous::GetVersion () const inline
Returns
the version of the rendezvous protocol being used.
Definition at line 167 of file DYLDRendezvous.h.
References m_current.
Referenced by DumpToLog().
IsCoreFile()
bool DYLDRendezvous::IsCoreFile () const protected
Definition at line 790 of file DYLDRendezvous.cpp.
References m_process.
Referenced by GetAction().
IsValid()
bool DYLDRendezvous::IsValid ()
Returns
true if this rendezvous has been located in the inferiors address space and false otherwise.
Definition at line 224 of file DYLDRendezvous.cpp.
References LLDB_INVALID_ADDRESS, and m_rendezvous_addr.
loaded_begin()
iterator DYLDRendezvous::loaded_begin () const inline
Iterators over all modules loaded into the inferior since the last call to Resolve().
Definition at line 257 of file DYLDRendezvous.h.
References m_added_soentries.
loaded_end()
iterator DYLDRendezvous::loaded_end () const inline
Definition at line 258 of file DYLDRendezvous.h.
References m_added_soentries.
ModulesDidLoad()
bool DYLDRendezvous::ModulesDidLoad () const inline
Returns
true if modules have been loaded into the inferior since the last call to Resolve().
Definition at line 194 of file DYLDRendezvous.h.
References m_added_soentries.
ModulesDidUnload()
bool DYLDRendezvous::ModulesDidUnload () const inline
Returns
true if modules have been unloaded from the inferior since the last call to Resolve().
Definition at line 198 of file DYLDRendezvous.h.
References m_removed_soentries.
ReadPointer()
addr_t DYLDRendezvous::ReadPointer (lldb::addr_t addr, lldb::addr_t * dst) protected
Reads an address from the inferior's address space starting at addr.
Returns
addr + target address size if the read was successful and 0 otherwise.
Definition at line 602 of file DYLDRendezvous.cpp.
References error(), and m_process.
Referenced by ReadSOEntryFromMemory(), and Resolve().
ReadSOEntryFromMemory()
bool DYLDRendezvous::ReadSOEntryFromMemory (lldb::addr_t addr, SOEntry & entry) protected
Reads an SOEntry starting at addr.
Definition at line 664 of file DYLDRendezvous.cpp.
References DYLDRendezvous::SOEntry::base_addr, DYLDRendezvous::SOEntry::clear(), DYLDRendezvous::SOEntry::dyn_addr, DYLDRendezvous::SOEntry::file_spec, lldb_private::ArchSpec::GetTriple(), lldb_private::ArchSpec::IsMIPS(), DYLDRendezvous::SOEntry::link_addr, m_process, DYLDRendezvous::SOEntry::next, DYLDRendezvous::SOEntry::path_addr, DYLDRendezvous::SOEntry::prev, ReadPointer(), ReadStringFromMemory(), lldb_private::FileSpec::SetFile(), and UpdateBaseAddrIfNecessary().
Referenced by AddSOEntries(), and TakeSnapshot().
ReadStringFromMemory()
std::string DYLDRendezvous::ReadStringFromMemory (lldb::addr_t addr) protected
Reads a null-terminated C string from the memory location starting at addr.
Definition at line 612 of file DYLDRendezvous.cpp.
References error(), LLDB_INVALID_ADDRESS, and m_process.
Referenced by ReadSOEntryFromMemory().
ReadWord()
addr_t DYLDRendezvous::ReadWord (lldb::addr_t addr, uint64_t * dst, size_t size) protected
Reads an unsigned integer of size bytes from the inferior's address space starting at addr.
Returns
addr + size if the read was successful and false otherwise.
Definition at line 592 of file DYLDRendezvous.cpp.
References error(), and m_process.
Referenced by Resolve().
RemoveSOEntries()
bool DYLDRendezvous::RemoveSOEntries () protected
Definition at line 526 of file DYLDRendezvous.cpp.
References begin(), eDelete, end(), m_previous, m_removed_soentries, m_soentries, and TakeSnapshot().
Referenced by UpdateSOEntries().
RemoveSOEntriesFromRemote()
bool DYLDRendezvous::RemoveSOEntriesFromRemote (const LoadedModuleInfoList & module_list) protected
Definition at line 465 of file DYLDRendezvous.cpp.
References FillSOEntryFromModuleInfo(), lldb_private::LoadedModuleInfoList::m_list, m_loaded_modules, m_removed_soentries, m_soentries, and SOEntryIsMainExecutable().
Referenced by UpdateSOEntriesFromRemote().
Resolve()
bool DYLDRendezvous::Resolve ()
Update the internal snapshot of runtime linker rendezvous and recompute the currently loaded modules.
This method should be called once one start up, then once each time the runtime linker enters the function given by GetBreakAddress().
Returns
true on success and false on failure.
See also
GetBreakAddress().
Definition at line 165 of file DYLDRendezvous.cpp.
References DYLDRendezvous::Rendezvous::brk, lldb_private::DynamicLoader, lldb_private::GetLog(), DYLDRendezvous::Rendezvous::ldbase, LLDB_INVALID_ADDRESS, LLDB_LOGF, m_current, m_previous, m_process, m_rendezvous_addr, DYLDRendezvous::Rendezvous::map_addr, ReadPointer(), ReadWord(), ResolveRendezvousAddress(), DYLDRendezvous::Rendezvous::state, UpdateSOEntries(), UpdateSOEntriesFromRemote(), DYLDRendezvous::Rendezvous::version, and word_size.
ResolveRendezvousAddress()
addr_t DYLDRendezvous::ResolveRendezvousAddress () private
Locates the address of the rendezvous structure.
It updates m_executable_interpreter if address is extracted from _r_debug.
Returns
address on success and LLDB_INVALID_ADDRESS on failure.
Definition at line 63 of file DYLDRendezvous.cpp.
References lldb_private::DynamicLoader, error(), lldb_private::Symbol::GetAddress(), lldb_private::Target::GetExecutableModule(), lldb_private::ObjectFile::GetImageInfoAddress(), lldb_private::Address::GetLoadAddress(), lldb_private::GetLog(), lldb_private::Address::IsValid(), LLDB_INVALID_ADDRESS, LLDB_LOGF, m_executable_interpreter, and m_process.
Referenced by Resolve().
SaveSOEntriesFromRemote()
bool DYLDRendezvous::SaveSOEntriesFromRemote (const LoadedModuleInfoList & module_list) protected
Definition at line 417 of file DYLDRendezvous.cpp.
References FillSOEntryFromModuleInfo(), lldb_private::LoadedModuleInfoList::m_list, m_loaded_modules, m_soentries, SOEntryIsMainExecutable(), and UpdateFileSpecIfNecessary().
Referenced by UpdateSOEntriesFromRemote().
SOEntryIsMainExecutable()
bool DYLDRendezvous::SOEntryIsMainExecutable (const SOEntry & entry) protected
Definition at line 544 of file DYLDRendezvous.cpp.
References DYLDRendezvous::SOEntry::file_spec, m_exe_file_spec, m_executable_interpreter, and m_process.
Referenced by AddSOEntries(), AddSOEntriesFromRemote(), RemoveSOEntriesFromRemote(), SaveSOEntriesFromRemote(), and TakeSnapshot().
StateToCStr()
const char * DYLDRendezvous::StateToCStr (RendezvousState state) static protected
Definition at line 28 of file DYLDRendezvous.cpp.
References eAdd, eConsistent, and eDelete.
Referenced by DYLDRendezvous::Rendezvous::DumpToLog().
TakeSnapshot()
bool DYLDRendezvous::TakeSnapshot (SOEntryList & entry_list) protected
Reads the current list of shared objects according to the link map supplied by the runtime linker.
Definition at line 567 of file DYLDRendezvous.cpp.
References DYLDRendezvous::SOEntry::clear(), m_current, DYLDRendezvous::SOEntry::next, ReadSOEntryFromMemory(), SOEntryIsMainExecutable(), and UpdateFileSpecIfNecessary().
Referenced by RemoveSOEntries(), and UpdateSOEntries().
unloaded_begin()
iterator DYLDRendezvous::unloaded_begin () const inline
Iterators over all modules unloaded from the inferior since the last call to Resolve().
Definition at line 262 of file DYLDRendezvous.h.
References m_removed_soentries.
unloaded_end()
iterator DYLDRendezvous::unloaded_end () const inline
Definition at line 263 of file DYLDRendezvous.h.
References m_removed_soentries.
UpdateBaseAddrIfNecessary()
void DYLDRendezvous::UpdateBaseAddrIfNecessary (SOEntry & entry, std::string const & file_path) protected
Definition at line 637 of file DYLDRendezvous.cpp.
References DYLDRendezvous::SOEntry::base_addr, error(), DYLDRendezvous::SOEntry::file_spec, isLoadBiasIncorrect(), LLDB_INVALID_ADDRESS, and m_process.
Referenced by FillSOEntryFromModuleInfo(), and ReadSOEntryFromMemory().
UpdateExecutablePath()
void DYLDRendezvous::UpdateExecutablePath ()
Update the cached executable path.
Definition at line 141 of file DYLDRendezvous.cpp.
References lldb_private::DynamicLoader, lldb_private::GetLog(), lldb_private::Module::GetPlatformFileSpec(), LLDB_LOGF, m_exe_file_spec, and m_process.
Referenced by DYLDRendezvous().
UpdateFileSpecIfNecessary()
void DYLDRendezvous::UpdateFileSpecIfNecessary (SOEntry & entry) protected
Definition at line 651 of file DYLDRendezvous.cpp.
References lldb_private::ConstString::AsCString(), DYLDRendezvous::SOEntry::dyn_addr, DYLDRendezvous::SOEntry::file_spec, lldb_private::MemoryRegionInfo::GetName(), lldb_private::ConstString::IsEmpty(), m_process, and lldb_private::FileSpec::SetFile().
Referenced by AddSOEntries(), AddSOEntriesFromRemote(), SaveSOEntriesFromRemote(), and TakeSnapshot().
UpdateSOEntries()
bool DYLDRendezvous::UpdateSOEntries () protected
Updates the current set of SOEntries, the set of added entries, and the set of removed entries.
Definition at line 370 of file DYLDRendezvous.cpp.
References ActionToCStr(), AddSOEntries(), lldb_private::DynamicLoader, eAddModules, eNoAction, eRemoveModules, eTakeSnapshot, GetAction(), lldb_private::GetLog(), LLDB_LOG, m_added_soentries, m_removed_soentries, m_soentries, RemoveSOEntries(), and TakeSnapshot().
Referenced by Resolve().
UpdateSOEntriesFromRemote()
bool DYLDRendezvous::UpdateSOEntriesFromRemote () protected
Same as UpdateSOEntries but it gets the list of loaded modules from the remote debug server (faster when supported).
Definition at line 332 of file DYLDRendezvous.cpp.
References ActionToCStr(), AddSOEntriesFromRemote(), lldb_private::DynamicLoader, eAddModules, eNoAction, eRemoveModules, eTakeSnapshot, GetAction(), lldb_private::GetLog(), LLDB_LOG, m_added_soentries, m_loaded_modules, m_process, m_removed_soentries, m_soentries, RemoveSOEntriesFromRemote(), and SaveSOEntriesFromRemote().
Referenced by Resolve().
Member Data Documentation
m_added_soentries
SOEntryList DYLDRendezvous::m_added_soentries protected
List of SOEntry's added to the link map since the last call to Resolve().
Definition at line 289 of file DYLDRendezvous.h.
Referenced by AddSOEntries(), AddSOEntriesFromRemote(), DYLDRendezvous(), loaded_begin(), loaded_end(), ModulesDidLoad(), UpdateSOEntries(), and UpdateSOEntriesFromRemote().
m_current
Rendezvous DYLDRendezvous::m_current protected
Current and previous snapshots of the rendezvous structure.
Definition at line 278 of file DYLDRendezvous.h.
Referenced by AddSOEntries(), DYLDRendezvous(), GetAction(), GetBreakAddress(), GetLDBase(), GetLinkMapAddress(), GetState(), GetVersion(), Resolve(), and TakeSnapshot().
m_exe_file_spec
lldb_private::FileSpec DYLDRendezvous::m_exe_file_spec protected
Definition at line 269 of file DYLDRendezvous.h.
Referenced by SOEntryIsMainExecutable(), and UpdateExecutablePath().
m_executable_interpreter
bool DYLDRendezvous::m_executable_interpreter protected
Definition at line 275 of file DYLDRendezvous.h.
Referenced by DYLDRendezvous(), ResolveRendezvousAddress(), and SOEntryIsMainExecutable().
m_loaded_modules
LoadedModuleInfoList DYLDRendezvous::m_loaded_modules protected
List of currently loaded SO modules.
Definition at line 282 of file DYLDRendezvous.h.
Referenced by AddSOEntriesFromRemote(), DYLDRendezvous(), RemoveSOEntriesFromRemote(), SaveSOEntriesFromRemote(), and UpdateSOEntriesFromRemote().
m_previous
Rendezvous DYLDRendezvous::m_previous protected
Definition at line 279 of file DYLDRendezvous.h.
Referenced by AddSOEntries(), DYLDRendezvous(), GetAction(), RemoveSOEntries(), and Resolve().
m_process
lldb_private::Process* DYLDRendezvous::m_process protected
Definition at line 266 of file DYLDRendezvous.h.
Referenced by DYLDRendezvous(), FindMetadata(), IsCoreFile(), ReadPointer(), ReadSOEntryFromMemory(), ReadStringFromMemory(), ReadWord(), Resolve(), ResolveRendezvousAddress(), SOEntryIsMainExecutable(), UpdateBaseAddrIfNecessary(), UpdateExecutablePath(), UpdateFileSpecIfNecessary(), and UpdateSOEntriesFromRemote().
m_removed_soentries
SOEntryList DYLDRendezvous::m_removed_soentries protected
List of SOEntry's removed from the link map since the last call to Resolve().
Definition at line 293 of file DYLDRendezvous.h.
Referenced by DYLDRendezvous(), ModulesDidUnload(), RemoveSOEntries(), RemoveSOEntriesFromRemote(), unloaded_begin(), unloaded_end(), UpdateSOEntries(), and UpdateSOEntriesFromRemote().
m_rendezvous_addr
lldb::addr_t DYLDRendezvous::m_rendezvous_addr protected
Location of the r_debug structure in the inferiors address space.
Definition at line 272 of file DYLDRendezvous.h.
Referenced by DYLDRendezvous(), GetRendezvousAddress(), IsValid(), and Resolve().
m_soentries
SOEntryList DYLDRendezvous::m_soentries protected
List of SOEntry objects corresponding to the current link map state.
Definition at line 285 of file DYLDRendezvous.h.
Referenced by AddSOEntries(), AddSOEntriesFromRemote(), begin(), DYLDRendezvous(), end(), RemoveSOEntries(), RemoveSOEntriesFromRemote(), SaveSOEntriesFromRemote(), UpdateSOEntries(), and UpdateSOEntriesFromRemote().
m_thread_info
ThreadInfo DYLDRendezvous::m_thread_info protected
Threading metadata read from the inferior.
Definition at line 296 of file DYLDRendezvous.h.
Referenced by DYLDRendezvous(), and GetThreadInfo().
The documentation for this class was generated from the following files:
DYLDRendezvous.h
DYLDRendezvous.cpp