LLDB: lldb_private::HistoryUnwind Class Reference
lldb_private::HistoryUnwind Class Reference
#include <HistoryUnwind.h>
Public Member Functions
HistoryUnwind (Thread &thread, std::vector< lldb::addr_t > pcs, HistoryPCType pc_type=HistoryPCType::Returns)
~HistoryUnwind () override
Public Member Functions inherited from lldb_private::Unwind
virtual ~Unwind ()=default
void Clear ()
uint32_t GetFrameCount ()
uint32_t GetFramesUpTo (uint32_t end_idx)
bool GetFrameInfoAtIndex (uint32_t frame_idx, lldb::addr_t &cfa, lldb::addr_t &pc, bool &behaves_like_zeroth_frame)
lldb::RegisterContextSP CreateRegisterContextForFrame (StackFrame *frame)
Thread & GetThread ()
Protected Member Functions
void DoClear () override
lldb::RegisterContextSP DoCreateRegisterContextForFrame (StackFrame *frame) override
bool DoGetFrameInfoAtIndex (uint32_t frame_idx, lldb::addr_t &cfa, lldb::addr_t &pc, bool &behaves_like_zeroth_frame) override
uint32_t DoGetFrameCount () override
Protected Member Functions inherited from lldb_private::Unwind
Unwind (Thread &thread)
Private Attributes
std::vector< lldb::addr_t > m_pcs
HistoryPCType m_pc_type
Additional Inherited Members
Protected Attributes inherited from lldb_private::Unwind
Thread & m_thread
std::recursive_mutex m_unwind_mutex
Detailed Description
Definition at line 19 of file HistoryUnwind.h.
Constructor & Destructor Documentation
HistoryUnwind()
HistoryUnwind::HistoryUnwind (Thread & thread, std::vector< lldb::addr_t > pcs, HistoryPCType pc_type = HistoryPCType::Returns)
Definition at line 26 of file HistoryUnwind.cpp.
References m_pc_type, m_pcs, and lldb_private::Unwind::Unwind().
~HistoryUnwind()
HistoryUnwind::~HistoryUnwind () override default
References pc.
Member Function Documentation
DoClear()
void HistoryUnwind::DoClear () override protected virtual
Implements lldb_private::Unwind.
Definition at line 34 of file HistoryUnwind.cpp.
References m_pcs, and lldb_private::Unwind::m_unwind_mutex.
DoCreateRegisterContextForFrame()
lldb::RegisterContextSP HistoryUnwind::DoCreateRegisterContextForFrame (StackFrame * frame) override protected virtual
Implements lldb_private::Unwind.
Definition at line 40 of file HistoryUnwind.cpp.
References lldb_private::StackFrame::GetConcreteFrameIndex(), lldb_private::StackFrame::GetFrameCodeAddress(), lldb_private::Address::GetLoadAddress(), lldb_private::StackFrame::GetThread(), LLDB_INVALID_ADDRESS, and pc.
DoGetFrameCount()
uint32_t HistoryUnwind::DoGetFrameCount () override protected virtual
Implements lldb_private::Unwind.
Definition at line 81 of file HistoryUnwind.cpp.
References m_pcs.
DoGetFrameInfoAtIndex()
bool HistoryUnwind::DoGetFrameInfoAtIndex (uint32_t frame_idx, lldb::addr_t & cfa, lldb::addr_t & pc, bool & behaves_like_zeroth_frame) override protected virtual
Implements lldb_private::Unwind.
Definition at line 66 of file HistoryUnwind.cpp.
References BehavesLikeZerothFrame(), m_pc_type, m_pcs, lldb_private::Unwind::m_unwind_mutex, and pc.
Member Data Documentation
m_pc_type
HistoryPCType lldb_private::HistoryUnwind::m_pc_type private
Definition at line 39 of file HistoryUnwind.h.
Referenced by DoGetFrameInfoAtIndex(), and HistoryUnwind().
m_pcs
std::vector<lldb::addr_t> lldb_private::HistoryUnwind::m_pcs private
Definition at line 38 of file HistoryUnwind.h.
Referenced by DoClear(), DoGetFrameCount(), DoGetFrameInfoAtIndex(), and HistoryUnwind().
The documentation for this class was generated from the following files:
HistoryUnwind.h
HistoryUnwind.cpp