LLDB: lldb_private::MonitoringProcessLauncher Class Reference
lldb_private::MonitoringProcessLauncher Class Reference
#include <MonitoringProcessLauncher.h>
Public Member Functions
MonitoringProcessLauncher (std::unique_ptr< ProcessLauncher > delegate_launcher)
HostProcess LaunchProcess (const ProcessLaunchInfo &launch_info, Status &error) override
Launch the process specified in launch_info.
Public Member Functions inherited from lldb_private::ProcessLauncher
virtual ~ProcessLauncher ()=default
Private Attributes
std::unique_ptr< ProcessLauncher > m_delegate_launcher
Detailed Description
Definition at line 17 of file MonitoringProcessLauncher.h.
Constructor & Destructor Documentation
MonitoringProcessLauncher()
MonitoringProcessLauncher::MonitoringProcessLauncher (std::unique_ptr< ProcessLauncher > delegate_launcher) explicit
Definition at line 21 of file MonitoringProcessLauncher.cpp.
References m_delegate_launcher.
Member Function Documentation
LaunchProcess()
HostProcess MonitoringProcessLauncher::LaunchProcess (const ProcessLaunchInfo & launch_info, Status & error) override virtual
Launch the process specified in launch_info.
The monitoring callback in launch_info must be set, and it will be called when the process terminates.
Implements lldb_private::ProcessLauncher.
Definition at line 26 of file MonitoringProcessLauncher.cpp.
References error(), lldb_private::FileSystem::Exists(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::ProcessInfo::GetExecutableFile(), lldb_private::ProcessLaunchInfo::GetFlags(), lldb_private::GetLog(), lldb_private::ProcessLaunchInfo::GetMonitorProcessCallback(), lldb_private::HostProcess::GetProcessId(), lldb_private::FileSystem::Instance(), LLDB_INVALID_PROCESS_ID, m_delegate_launcher, lldb_private::Process, lldb_private::Log::PutCString(), lldb_private::FileSystem::Resolve(), lldb_private::FileSystem::ResolveExecutableLocation(), lldb_private::ProcessInfo::SetExecutableFile(), lldb_private::HostProcess::StartMonitoring(), and lldb_private::Flags::Test().
Referenced by lldb_private::Host::LaunchProcess().
Member Data Documentation
m_delegate_launcher
std::unique_ptr<ProcessLauncher> lldb_private::MonitoringProcessLauncher::m_delegate_launcher private
Definition at line 29 of file MonitoringProcessLauncher.h.
Referenced by LaunchProcess(), and MonitoringProcessLauncher().
The documentation for this class was generated from the following files:
MonitoringProcessLauncher.h
MonitoringProcessLauncher.cpp