LLDB: RegisterContextLinux_i386 Class Reference
RegisterContextLinux_i386 Class Reference
#include <RegisterContextLinux_i386.h>
Public Member Functions
RegisterContextLinux_i386 (const lldb_private::ArchSpec &target_arch)
size_t GetGPRSize () const override
const lldb_private::RegisterInfo * GetRegisterInfo () const override
uint32_t GetRegisterCount () const override
uint32_t GetUserRegisterCount () const override
Public Member Functions inherited from lldb_private::RegisterContextLinux_x86
RegisterContextLinux_x86 (const ArchSpec &target_arch, RegisterInfo orig_ax_info)
const RegisterInfo & GetOrigAxInfo () const
Public Member Functions inherited from lldb_private::RegisterInfoInterface
RegisterInfoInterface (const lldb_private::ArchSpec &target_arch)
virtual ~RegisterInfoInterface ()=default
const lldb_private::ArchSpec & GetTargetArchitecture () const
Static Public Member Functions
static size_t GetGPRSizeStatic ()
Detailed Description
Definition at line 14 of file RegisterContextLinux_i386.h.
Constructor & Destructor Documentation
RegisterContextLinux_i386()
RegisterContextLinux_i386::RegisterContextLinux_i386 (const lldb_private::ArchSpec & target_arch)
Definition at line 89 of file RegisterContextLinux_i386.cpp.
References lldb::eEncodingUint, lldb::eFormatHex, LLDB_INVALID_REGNUM, and lldb_private::RegisterContextLinux_x86::RegisterContextLinux_x86().
Member Function Documentation
GetGPRSize()
size_t RegisterContextLinux_i386::GetGPRSize () const inline override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 20 of file RegisterContextLinux_i386.h.
References GetGPRSizeStatic().
GetGPRSizeStatic()
size_t RegisterContextLinux_i386::GetGPRSizeStatic () static
Definition at line 105 of file RegisterContextLinux_i386.cpp.
Referenced by GetGPRSize().
GetRegisterCount()
uint32_t RegisterContextLinux_i386::GetRegisterCount () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 118 of file RegisterContextLinux_i386.cpp.
GetRegisterInfo()
const RegisterInfo * RegisterContextLinux_i386::GetRegisterInfo () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 107 of file RegisterContextLinux_i386.cpp.
References lldb_private::RegisterInfoInterface::GetTargetArchitecture().
GetUserRegisterCount()
uint32_t RegisterContextLinux_i386::GetUserRegisterCount () const override virtual
Reimplemented from lldb_private::RegisterInfoInterface.
Definition at line 123 of file RegisterContextLinux_i386.cpp.
References lldb_private::k_num_user_registers_i386.
The documentation for this class was generated from the following files:
RegisterContextLinux_i386.h
RegisterContextLinux_i386.cpp