LLDB: lldb::SBTypeSummary Class Reference
lldb::SBTypeSummary Class Reference
#include <SBTypeSummary.h>
Public Types
typedef bool(* FormatCallback) (SBValue, SBTypeSummaryOptions, SBStream &)
Public Member Functions
SBTypeSummary ()
SBTypeSummary (const lldb::SBTypeSummary &rhs)
~SBTypeSummary ()
operator bool () const
bool IsValid () const
bool IsFunctionCode ()
bool IsFunctionName ()
bool IsSummaryString ()
const char * GetData ()
void SetSummaryString (const char *data)
void SetFunctionName (const char *data)
void SetFunctionCode (const char *data)
uint32_t GetPtrMatchDepth ()
void SetPtrMatchDepth (uint32_t ptr_match_depth)
uint32_t GetOptions ()
void SetOptions (uint32_t)
bool GetDescription (lldb::SBStream &description, lldb::DescriptionLevel description_level)
lldb::SBTypeSummary & operator= (const lldb::SBTypeSummary &rhs)
bool DoesPrintValue (lldb::SBValue value)
bool IsEqualTo (lldb::SBTypeSummary &rhs)
bool operator== (lldb::SBTypeSummary &rhs)
bool operator!= (lldb::SBTypeSummary &rhs)
Static Public Member Functions
static SBTypeSummary CreateWithSummaryString (const char *data, uint32_t options=0)
static SBTypeSummary CreateWithFunctionName (const char *data, uint32_t options=0)
static SBTypeSummary CreateWithScriptCode (const char *data, uint32_t options=0)
static SBTypeSummary CreateWithCallback (FormatCallback cb, uint32_t options=0, const char *description=nullptr)
Protected Member Functions
lldb::TypeSummaryImplSP GetSP ()
void SetSP (const lldb::TypeSummaryImplSP &typefilter_impl_sp)
SBTypeSummary (const lldb::TypeSummaryImplSP &)
bool CopyOnWrite_Impl ()
bool ChangeSummaryType (bool want_script)
Protected Attributes
lldb::TypeSummaryImplSP m_opaque_sp
Friends
class SBDebugger
class SBTypeCategory
class SBValue
Detailed Description
Definition at line 65 of file SBTypeSummary.h.
Member Typedef Documentation
FormatCallback
typedef bool(* lldb::SBTypeSummary::FormatCallback) (SBValue, SBTypeSummaryOptions, SBStream &)
Definition at line 70 of file SBTypeSummary.h.
Constructor & Destructor Documentation
SBTypeSummary() [1/3]
SBTypeSummary::SBTypeSummary ()
Definition at line 103 of file SBTypeSummary.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by CreateWithCallback(), CreateWithFunctionName(), CreateWithScriptCode(), and CreateWithSummaryString().
SBTypeSummary() [2/3]
SBTypeSummary::SBTypeSummary (const lldb::SBTypeSummary & rhs)
Definition at line 163 of file SBTypeSummary.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
~SBTypeSummary()
SBTypeSummary::~SBTypeSummary () default
SBTypeSummary() [3/3]
SBTypeSummary::SBTypeSummary (const lldb::TypeSummaryImplSP & typesummary_impl_sp) protected
Definition at line 394 of file SBTypeSummary.cpp.
References m_opaque_sp.
Member Function Documentation
ChangeSummaryType()
bool SBTypeSummary::ChangeSummaryType (bool want_script) protected
Definition at line 427 of file SBTypeSummary.cpp.
References CopyOnWrite_Impl(), lldb_private::TypeSummaryImpl::eCallback, lldb_private::TypeSummaryImpl::eScript, GetOptions(), IsValid(), m_opaque_sp, and SetSP().
Referenced by SetFunctionCode(), SetFunctionName(), and SetSummaryString().
CopyOnWrite_Impl()
bool SBTypeSummary::CopyOnWrite_Impl () protected
Definition at line 397 of file SBTypeSummary.cpp.
References GetOptions(), IsValid(), m_opaque_sp, and SetSP().
Referenced by ChangeSummaryType(), GetDescription(), and SetOptions().
CreateWithCallback()
SBTypeSummary SBTypeSummary::CreateWithCallback (FormatCallback cb, uint32_t options = 0, const char * description = nullptr) static
Definition at line 138 of file SBTypeSummary.cpp.
References lldb::SBStream::GetData(), lldb::SBStream::GetSize(), lldb_private::ValueObject::GetSP(), LLDB_INSTRUMENT_VA, SBTypeSummary(), SBValue, SetSP(), and lldb_private::Stream::Write().
CreateWithFunctionName()
SBTypeSummary SBTypeSummary::CreateWithFunctionName (const char * data, uint32_t options = 0) static
Definition at line 116 of file SBTypeSummary.cpp.
References LLDB_INSTRUMENT_VA, and SBTypeSummary().
CreateWithScriptCode()
SBTypeSummary SBTypeSummary::CreateWithScriptCode (const char * data, uint32_t options = 0) static
Definition at line 127 of file SBTypeSummary.cpp.
References LLDB_INSTRUMENT_VA, and SBTypeSummary().
CreateWithSummaryString()
SBTypeSummary SBTypeSummary::CreateWithSummaryString (const char * data, uint32_t options = 0) static
Definition at line 105 of file SBTypeSummary.cpp.
References LLDB_INSTRUMENT_VA, and SBTypeSummary().
DoesPrintValue()
bool SBTypeSummary::DoesPrintValue (lldb::SBValue value)
Definition at line 313 of file SBTypeSummary.cpp.
References lldb::SBValue::GetSP(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetData()
const char * SBTypeSummary::GetData ()
Definition at line 215 of file SBTypeSummary.cpp.
References lldb_private::ConstString::GetCString(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by lldb::SBTypeCategory::AddTypeSummary().
GetDescription()
bool SBTypeSummary::GetDescription (lldb::SBStream & description, lldb::DescriptionLevel description_level)
Definition at line 301 of file SBTypeSummary.cpp.
References CopyOnWrite_Impl(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetOptions()
uint32_t SBTypeSummary::GetOptions ()
Definition at line 249 of file SBTypeSummary.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ChangeSummaryType(), CopyOnWrite_Impl(), and IsEqualTo().
GetPtrMatchDepth()
uint32_t SBTypeSummary::GetPtrMatchDepth ()
Definition at line 233 of file SBTypeSummary.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetSP()
lldb::TypeSummaryImplSP SBTypeSummary::GetSP () protected
Definition at line 388 of file SBTypeSummary.cpp.
References m_opaque_sp.
Referenced by lldb::SBTypeCategory::AddTypeSummary().
IsEqualTo()
bool SBTypeSummary::IsEqualTo (lldb::SBTypeSummary & rhs)
Definition at line 339 of file SBTypeSummary.cpp.
References lldb_private::TypeSummaryImpl::eBytecode, lldb_private::TypeSummaryImpl::eCallback, lldb_private::TypeSummaryImpl::eInternal, lldb_private::TypeSummaryImpl::eScript, lldb_private::TypeSummaryImpl::eSummaryString, GetOptions(), IsFunctionCode(), IsFunctionName(), IsSummaryString(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
IsFunctionCode()
bool SBTypeSummary::IsFunctionCode ()
Definition at line 180 of file SBTypeSummary.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by lldb::SBTypeCategory::AddTypeSummary(), and IsEqualTo().
IsFunctionName()
bool SBTypeSummary::IsFunctionName ()
Definition at line 193 of file SBTypeSummary.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by IsEqualTo().
IsSummaryString()
bool SBTypeSummary::IsSummaryString ()
Definition at line 206 of file SBTypeSummary.cpp.
References lldb_private::TypeSummaryImpl::eSummaryString, IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by IsEqualTo().
IsValid()
bool SBTypeSummary::IsValid () const
Definition at line 170 of file SBTypeSummary.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBTypeCategory::AddTypeSummary(), ChangeSummaryType(), CopyOnWrite_Impl(), DoesPrintValue(), GetData(), GetOptions(), GetPtrMatchDepth(), IsEqualTo(), IsFunctionCode(), IsFunctionName(), IsSummaryString(), operator!=(), operator==(), SetFunctionCode(), SetFunctionName(), SetPtrMatchDepth(), and SetSummaryString().
operator bool()
SBTypeSummary::operator bool () const explicit
Definition at line 174 of file SBTypeSummary.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator!=()
bool SBTypeSummary::operator!= (lldb::SBTypeSummary & rhs)
Definition at line 380 of file SBTypeSummary.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator=()
lldb::SBTypeSummary & SBTypeSummary::operator= (const lldb::SBTypeSummary & rhs)
Definition at line 322 of file SBTypeSummary.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator==()
bool SBTypeSummary::operator== (lldb::SBTypeSummary & rhs)
Definition at line 331 of file SBTypeSummary.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
SetFunctionCode()
void SBTypeSummary::SetFunctionCode (const char * data)
Definition at line 289 of file SBTypeSummary.cpp.
References ChangeSummaryType(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
SetFunctionName()
void SBTypeSummary::SetFunctionName (const char * data)
Definition at line 277 of file SBTypeSummary.cpp.
References ChangeSummaryType(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by lldb::SBTypeCategory::AddTypeSummary().
SetOptions()
void SBTypeSummary::SetOptions (uint32_t value)
Definition at line 257 of file SBTypeSummary.cpp.
References CopyOnWrite_Impl(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
SetPtrMatchDepth()
void SBTypeSummary::SetPtrMatchDepth (uint32_t ptr_match_depth)
Definition at line 241 of file SBTypeSummary.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
SetSP()
void SBTypeSummary::SetSP (const lldb::TypeSummaryImplSP & typefilter_impl_sp) protected
Definition at line 390 of file SBTypeSummary.cpp.
References m_opaque_sp.
Referenced by ChangeSummaryType(), CopyOnWrite_Impl(), CreateWithCallback(), and lldb::SBValue::GetTypeSummary().
SetSummaryString()
void SBTypeSummary::SetSummaryString (const char * data)
Definition at line 265 of file SBTypeSummary.cpp.
References ChangeSummaryType(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Friends And Related Symbol Documentation
SBDebugger
friend class SBDebugger friend
Definition at line 134 of file SBTypeSummary.h.
References SBDebugger.
Referenced by SBDebugger.
SBTypeCategory
friend class SBTypeCategory friend
Definition at line 135 of file SBTypeSummary.h.
References SBTypeCategory.
Referenced by SBTypeCategory.
SBValue
friend class SBValue friend
Definition at line 136 of file SBTypeSummary.h.
References SBValue.
Referenced by CreateWithCallback(), and SBValue.
Member Data Documentation
m_opaque_sp
lldb::TypeSummaryImplSP lldb::SBTypeSummary::m_opaque_sp protected
Definition at line 142 of file SBTypeSummary.h.
Referenced by ChangeSummaryType(), CopyOnWrite_Impl(), DoesPrintValue(), GetData(), GetDescription(), GetOptions(), GetPtrMatchDepth(), GetSP(), IsEqualTo(), IsFunctionCode(), IsFunctionName(), IsSummaryString(), operator bool(), operator!=(), operator=(), operator==(), SBTypeSummary(), SBTypeSummary(), SetFunctionCode(), SetFunctionName(), SetOptions(), SetPtrMatchDepth(), SetSP(), and SetSummaryString().
The documentation for this class was generated from the following files:
SBTypeSummary.h
SBTypeSummary.cpp