LLDB: lldb_private::npdb::CompileUnitIndex Class Reference
lldb_private::npdb::CompileUnitIndex Class Reference
Indexes information about all compile units.
#include <CompileUnitIndex.h>
Public Member Functions
CompileUnitIndex (PdbIndex &index)
CompilandIndexItem & GetOrCreateCompiland (uint16_t modi)
const CompilandIndexItem * GetCompiland (uint16_t modi) const
CompilandIndexItem * GetCompiland (uint16_t modi)
llvm::SmallString< 64 > GetMainSourceFile (const CompilandIndexItem &item) const
Private Attributes
PdbIndex & m_index
llvm::DenseMap< uint16_t, std::unique_ptr< CompilandIndexItem > > m_comp_units
Detailed Description
Indexes information about all compile units.
This is really just a map of global compile unit index to |CompilandIndexItem| structures.
Definition at line 90 of file CompileUnitIndex.h.
Constructor & Destructor Documentation
CompileUnitIndex()
lldb_private::npdb::CompileUnitIndex::CompileUnitIndex (PdbIndex & index) inline explicit
Definition at line 95 of file CompileUnitIndex.h.
References m_index.
Member Function Documentation
GetCompiland() [1/2]
CompilandIndexItem * CompileUnitIndex::GetCompiland (uint16_t modi)
Definition at line 204 of file CompileUnitIndex.cpp.
References m_comp_units.
GetCompiland() [2/2]
const CompilandIndexItem * CompileUnitIndex::GetCompiland (uint16_t modi) const
Definition at line 197 of file CompileUnitIndex.cpp.
References m_comp_units.
Referenced by lldb_private::npdb::PdbAstBuilderClang::CreateFunctionParameters(), GetBaseFrameRegister(), lldb_private::npdb::PdbAstBuilderClang::GetOrCreateInlinedFunctionDecl(), and lldb_private::npdb::PdbIndex::ReadSymbolRecord().
GetMainSourceFile()
llvm::SmallString< 64 > CompileUnitIndex::GetMainSourceFile (const CompilandIndexItem & item) const
Definition at line 212 of file CompileUnitIndex.cpp.
References lldb_private::npdb::CompilandIndexItem::m_build_info, and m_index.
Referenced by GetOrCreateCompiland().
GetOrCreateCompiland()
CompilandIndexItem & CompileUnitIndex::GetOrCreateCompiland (uint16_t modi)
Definition at line 133 of file CompileUnitIndex.cpp.
References GetMainSourceFile(), IsMainFile(), m_comp_units, m_index, ParseExtendedInfo(), and ParseInlineeLineTableForCompileUnit().
Referenced by lldb_private::npdb::PdbIndex::FindSymbolsByVa(), lldb_private::npdb::PdbAstBuilderClang::ParseAllFunctionsAndNonLocalVars(), and lldb_private::npdb::PdbAstBuilderClang::ParseBlockChildren().
Member Data Documentation
m_comp_units
llvm::DenseMap<uint16_t, std::unique_ptr<CompilandIndexItem> > lldb_private::npdb::CompileUnitIndex::m_comp_units private
Definition at line 92 of file CompileUnitIndex.h.
Referenced by GetCompiland(), GetCompiland(), and GetOrCreateCompiland().
m_index
PdbIndex& lldb_private::npdb::CompileUnitIndex::m_index private
Definition at line 91 of file CompileUnitIndex.h.
Referenced by CompileUnitIndex(), GetMainSourceFile(), and GetOrCreateCompiland().
The documentation for this class was generated from the following files:
CompileUnitIndex.h
CompileUnitIndex.cpp