LLDB: lldb_private::EventDataBytes Class Reference
lldb_private::EventDataBytes Class Reference
#include <Event.h>
Public Member Functions
EventDataBytes ()
EventDataBytes (llvm::StringRef str)
~EventDataBytes () override
llvm::StringRef GetFlavor () const override
void Dump (Stream *s) const override
const void * GetBytes () const
size_t GetByteSize () const
Public Member Functions inherited from lldb_private::EventData
EventData ()
virtual ~EventData ()
virtual Log * GetLogChannel ()
Static Public Member Functions
static const EventDataBytes * GetEventDataFromEvent (const Event *event_ptr)
static const void * GetBytesFromEvent (const Event *event_ptr)
static size_t GetByteSizeFromEvent (const Event *event_ptr)
static llvm::StringRef GetFlavorString ()
Private Member Functions
EventDataBytes (const EventDataBytes &)=delete
const EventDataBytes & operator= (const EventDataBytes &)=delete
Private Attributes
std::string m_bytes
Detailed Description
Definition at line 68 of file Event.h.
Constructor & Destructor Documentation
EventDataBytes() [1/3]
EventDataBytes::EventDataBytes ()
Definition at line 118 of file Event.cpp.
References m_bytes.
Referenced by EventDataBytes(), GetBytesFromEvent(), GetByteSizeFromEvent(), GetEventDataFromEvent(), operator=(), and ~EventDataBytes().
EventDataBytes() [2/3]
EventDataBytes::EventDataBytes (llvm::StringRef str)
Definition at line 120 of file Event.cpp.
References m_bytes.
~EventDataBytes()
EventDataBytes::~EventDataBytes () override default
References lldb_private::EventData::Event, and EventDataBytes().
EventDataBytes() [3/3]
lldb_private::EventDataBytes::EventDataBytes (const EventDataBytes &) private delete
References EventDataBytes().
Member Function Documentation
Dump()
void EventDataBytes::Dump (Stream * s) const override virtual
Reimplemented from lldb_private::EventData.
Definition at line 130 of file Event.cpp.
References lldb_private::Stream::Format(), and m_bytes.
GetBytes()
const void * EventDataBytes::GetBytes () const
Definition at line 140 of file Event.cpp.
References m_bytes.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::AsyncThread(), and GetBytesFromEvent().
GetBytesFromEvent()
const void * EventDataBytes::GetBytesFromEvent (const Event * event_ptr) static
Definition at line 146 of file Event.cpp.
References lldb_private::EventData::Event, EventDataBytes(), GetBytes(), and GetEventDataFromEvent().
Referenced by lldb_private::Debugger::DefaultEventHandler(), and lldb::SBEvent::GetCStringFromEvent().
GetByteSize()
size_t EventDataBytes::GetByteSize () const
Definition at line 144 of file Event.cpp.
References m_bytes.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::AsyncThread(), and GetByteSizeFromEvent().
GetByteSizeFromEvent()
size_t EventDataBytes::GetByteSizeFromEvent (const Event * event_ptr) static
Definition at line 153 of file Event.cpp.
References lldb_private::EventData::Event, EventDataBytes(), GetByteSize(), and GetEventDataFromEvent().
GetEventDataFromEvent()
const EventDataBytes * EventDataBytes::GetEventDataFromEvent (const Event * event_ptr) static
Definition at line 161 of file Event.cpp.
References lldb_private::EventData::Event, lldb_private::EventData::EventData(), EventDataBytes(), lldb_private::Event::GetData(), lldb_private::EventData::GetFlavor(), and GetFlavorString().
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::AsyncThread(), GetBytesFromEvent(), and GetByteSizeFromEvent().
GetFlavor()
llvm::StringRef EventDataBytes::GetFlavor () const override virtual
Implements lldb_private::EventData.
Definition at line 126 of file Event.cpp.
References GetFlavorString().
GetFlavorString()
llvm::StringRef EventDataBytes::GetFlavorString () static
Definition at line 124 of file Event.cpp.
Referenced by GetEventDataFromEvent(), and GetFlavor().
operator=()
const EventDataBytes & lldb_private::EventDataBytes::operator= (const EventDataBytes &) private delete
References EventDataBytes().
Member Data Documentation
m_bytes
std::string lldb_private::EventDataBytes::m_bytes private
Definition at line 96 of file Event.h.
Referenced by Dump(), EventDataBytes(), EventDataBytes(), GetBytes(), and GetByteSize().
The documentation for this class was generated from the following files:
Event.h
Event.cpp