LLDB: lldb::SBVariablesOptions Class Reference
lldb::SBVariablesOptions Class Reference
#include <SBVariablesOptions.h>
Public Member Functions
SBVariablesOptions ()
SBVariablesOptions (const SBVariablesOptions &options)
SBVariablesOptions & operator= (const SBVariablesOptions &options)
~SBVariablesOptions ()
operator bool () const
bool IsValid () const
bool GetIncludeArguments () const
void SetIncludeArguments (bool)
bool GetIncludeRecognizedArguments (const lldb::SBTarget &) const
void SetIncludeRecognizedArguments (bool)
bool GetIncludeLocals () const
void SetIncludeLocals (bool)
bool GetIncludeStatics () const
void SetIncludeStatics (bool)
bool GetInScopeOnly () const
void SetInScopeOnly (bool)
bool GetIncludeRuntimeSupportValues () const
void SetIncludeRuntimeSupportValues (bool)
lldb::DynamicValueType GetUseDynamic () const
void SetUseDynamic (lldb::DynamicValueType)
Protected Member Functions
VariablesOptionsImpl * operator-> ()
const VariablesOptionsImpl * operator-> () const
VariablesOptionsImpl * get ()
VariablesOptionsImpl & ref ()
const VariablesOptionsImpl & ref () const
SBVariablesOptions (VariablesOptionsImpl *lldb_object_ptr)
void SetOptions (VariablesOptionsImpl *lldb_object_ptr)
Private Attributes
std::unique_ptr< VariablesOptionsImpl > m_opaque_up
Detailed Description
Definition at line 19 of file SBVariablesOptions.h.
Constructor & Destructor Documentation
SBVariablesOptions() [1/3]
SBVariablesOptions::SBVariablesOptions ()
Definition at line 81 of file SBVariablesOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by operator=(), SBVariablesOptions(), and ~SBVariablesOptions().
SBVariablesOptions() [2/3]
SBVariablesOptions::SBVariablesOptions (const SBVariablesOptions & options)
Definition at line 86 of file SBVariablesOptions.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, ref(), and SBVariablesOptions().
~SBVariablesOptions()
SBVariablesOptions::~SBVariablesOptions () default
References get(), GetIncludeArguments(), GetIncludeLocals(), GetIncludeRecognizedArguments(), GetIncludeRuntimeSupportValues(), GetIncludeStatics(), GetInScopeOnly(), GetUseDynamic(), IsValid(), operator->(), ref(), SBVariablesOptions(), SetIncludeArguments(), SetIncludeLocals(), SetIncludeRecognizedArguments(), SetIncludeRuntimeSupportValues(), SetIncludeStatics(), SetInScopeOnly(), SetOptions(), and SetUseDynamic().
SBVariablesOptions() [3/3]
SBVariablesOptions::SBVariablesOptions (VariablesOptionsImpl * lldb_object_ptr) protected
Definition at line 213 of file SBVariablesOptions.cpp.
References m_opaque_up.
Member Function Documentation
get()
VariablesOptionsImpl * SBVariablesOptions::get () protected
Definition at line 205 of file SBVariablesOptions.cpp.
References m_opaque_up.
Referenced by ~SBVariablesOptions().
GetIncludeArguments()
bool SBVariablesOptions::GetIncludeArguments () const
Definition at line 111 of file SBVariablesOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by FetchVariablesUnlessInterrupted(), and ~SBVariablesOptions().
GetIncludeLocals()
bool SBVariablesOptions::GetIncludeLocals () const
Definition at line 136 of file SBVariablesOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by FetchVariablesUnlessInterrupted(), and ~SBVariablesOptions().
GetIncludeRecognizedArguments()
bool SBVariablesOptions::GetIncludeRecognizedArguments (const lldb::SBTarget & target) const
Definition at line 123 of file SBVariablesOptions.cpp.
References lldb::SBTarget::GetSP(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by FetchRecognizedArguments(), and ~SBVariablesOptions().
GetIncludeRuntimeSupportValues()
bool SBVariablesOptions::GetIncludeRuntimeSupportValues () const
Definition at line 172 of file SBVariablesOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by FetchVariablesUnlessInterrupted(), and ~SBVariablesOptions().
GetIncludeStatics()
bool SBVariablesOptions::GetIncludeStatics () const
Definition at line 148 of file SBVariablesOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by FetchVariablesUnlessInterrupted(), and ~SBVariablesOptions().
GetInScopeOnly()
bool SBVariablesOptions::GetInScopeOnly () const
Definition at line 160 of file SBVariablesOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by FetchVariablesUnlessInterrupted(), and ~SBVariablesOptions().
GetUseDynamic()
lldb::DynamicValueType SBVariablesOptions::GetUseDynamic () const
Definition at line 185 of file SBVariablesOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by FetchVariablesUnlessInterrupted(), lldb::SBFrame::GetVariables(), and ~SBVariablesOptions().
IsValid()
bool SBVariablesOptions::IsValid () const
Definition at line 101 of file SBVariablesOptions.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBVariablesOptions().
operator bool()
SBVariablesOptions::operator bool () const explicit
Definition at line 105 of file SBVariablesOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
operator->() [1/2]
VariablesOptionsImpl * SBVariablesOptions::operator-> () protected
Definition at line 197 of file SBVariablesOptions.cpp.
References m_opaque_up.
Referenced by ~SBVariablesOptions().
operator->() [2/2]
const VariablesOptionsImpl * SBVariablesOptions::operator-> () const protected
Definition at line 201 of file SBVariablesOptions.cpp.
References m_opaque_up.
operator=()
SBVariablesOptions & SBVariablesOptions::operator= (const SBVariablesOptions & options)
Definition at line 91 of file SBVariablesOptions.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, ref(), and SBVariablesOptions().
ref() [1/2]
VariablesOptionsImpl & SBVariablesOptions::ref () protected
Definition at line 207 of file SBVariablesOptions.cpp.
References m_opaque_up.
Referenced by operator=(), SBVariablesOptions(), and ~SBVariablesOptions().
ref() [2/2]
const VariablesOptionsImpl & SBVariablesOptions::ref () const protected
Definition at line 209 of file SBVariablesOptions.cpp.
References m_opaque_up.
SetIncludeArguments()
void SBVariablesOptions::SetIncludeArguments (bool arguments)
Definition at line 117 of file SBVariablesOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBFrame::GetVariables(), lldb::SBFrame::GetVariables(), and ~SBVariablesOptions().
SetIncludeLocals()
void SBVariablesOptions::SetIncludeLocals (bool locals)
Definition at line 142 of file SBVariablesOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBFrame::GetVariables(), lldb::SBFrame::GetVariables(), and ~SBVariablesOptions().
SetIncludeRecognizedArguments()
void SBVariablesOptions::SetIncludeRecognizedArguments (bool arguments)
Definition at line 130 of file SBVariablesOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBVariablesOptions().
SetIncludeRuntimeSupportValues()
void SBVariablesOptions::SetIncludeRuntimeSupportValues (bool runtime_support_values)
Definition at line 178 of file SBVariablesOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBFrame::GetVariables(), lldb::SBFrame::GetVariables(), and ~SBVariablesOptions().
SetIncludeStatics()
void SBVariablesOptions::SetIncludeStatics (bool statics)
Definition at line 154 of file SBVariablesOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBFrame::GetVariables(), lldb::SBFrame::GetVariables(), and ~SBVariablesOptions().
SetInScopeOnly()
void SBVariablesOptions::SetInScopeOnly (bool in_scope_only)
Definition at line 166 of file SBVariablesOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBFrame::GetVariables(), lldb::SBFrame::GetVariables(), and ~SBVariablesOptions().
SetOptions()
void SBVariablesOptions::SetOptions (VariablesOptionsImpl * lldb_object_ptr) protected
Definition at line 216 of file SBVariablesOptions.cpp.
References m_opaque_up.
Referenced by ~SBVariablesOptions().
SetUseDynamic()
void SBVariablesOptions::SetUseDynamic (lldb::DynamicValueType dynamic)
Definition at line 191 of file SBVariablesOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBFrame::GetVariables(), lldb::SBFrame::GetVariables(), and ~SBVariablesOptions().
Member Data Documentation
m_opaque_up
std::unique_ptr<VariablesOptionsImpl> lldb::SBVariablesOptions::m_opaque_up private
Definition at line 77 of file SBVariablesOptions.h.
Referenced by get(), GetIncludeArguments(), GetIncludeLocals(), GetIncludeRecognizedArguments(), GetIncludeRuntimeSupportValues(), GetIncludeStatics(), GetInScopeOnly(), GetUseDynamic(), operator bool(), operator->(), operator->(), operator=(), ref(), ref(), SBVariablesOptions(), SBVariablesOptions(), SBVariablesOptions(), SetIncludeArguments(), SetIncludeLocals(), SetIncludeRecognizedArguments(), SetIncludeRuntimeSupportValues(), SetIncludeStatics(), SetInScopeOnly(), SetOptions(), and SetUseDynamic().
The documentation for this class was generated from the following files:
SBVariablesOptions.h
SBVariablesOptions.cpp