LLDB: lldb_private::ProcessRunLock::ProcessRunLocker Class Reference
lldb_private::ProcessRunLock::ProcessRunLocker Class Reference
#include <ProcessRunLock.h>
Public Member Functions
ProcessRunLocker ()=default
ProcessRunLocker (ProcessRunLocker &&other)
ProcessRunLocker & operator= (ProcessRunLocker &&other)
~ProcessRunLocker ()
bool IsLocked () const
bool TryLock (ProcessRunLock *lock)
Protected Member Functions
void Unlock ()
Protected Attributes
ProcessRunLock * m_lock = nullptr
Private Member Functions
ProcessRunLocker (const ProcessRunLocker &)=delete
const ProcessRunLocker & operator= (const ProcessRunLocker &)=delete
Detailed Description
Definition at line 41 of file ProcessRunLock.h.
Constructor & Destructor Documentation
ProcessRunLocker() [1/3]
lldb_private::ProcessRunLock::ProcessRunLocker::ProcessRunLocker () default
Referenced by operator=(), operator=(), ProcessRunLocker(), and ProcessRunLocker().
ProcessRunLocker() [2/3]
lldb_private::ProcessRunLock::ProcessRunLocker::ProcessRunLocker (ProcessRunLocker && other) inline
Definition at line 44 of file ProcessRunLock.h.
References m_lock, and ProcessRunLocker().
~ProcessRunLocker()
lldb_private::ProcessRunLock::ProcessRunLocker::~ProcessRunLocker () inline
Definition at line 56 of file ProcessRunLock.h.
References Unlock().
ProcessRunLocker() [3/3]
lldb_private::ProcessRunLock::ProcessRunLocker::ProcessRunLocker (const ProcessRunLocker &) private delete
References ProcessRunLocker().
Member Function Documentation
IsLocked()
bool lldb_private::ProcessRunLock::ProcessRunLocker::IsLocked () const inline
Definition at line 58 of file ProcessRunLock.h.
References m_lock.
operator=() [1/2]
const ProcessRunLocker & lldb_private::ProcessRunLock::ProcessRunLocker::operator= (const ProcessRunLocker &) private delete
References ProcessRunLocker().
operator=() [2/2]
ProcessRunLocker & lldb_private::ProcessRunLock::ProcessRunLocker::operator= (ProcessRunLocker && other) inline
Definition at line 47 of file ProcessRunLock.h.
References m_lock, ProcessRunLocker(), and Unlock().
TryLock()
bool lldb_private::ProcessRunLock::ProcessRunLocker::TryLock (ProcessRunLock * lock) inline
Definition at line 61 of file ProcessRunLock.h.
References m_lock, lldb_private::ProcessRunLock::ProcessRunLock(), lldb_private::ProcessRunLock::ReadTryLock(), and Unlock().
Referenced by lldb::SBProcess::AllocateMemory(), lldb::SBProcess::DeallocateMemory(), lldb::SBTarget::EvaluateExpression(), lldb_private::QueueImpl::FetchItems(), lldb_private::QueueImpl::FetchThreads(), lldb::SBProcess::FindInMemory(), lldb::SBProcess::FindRangesInMemory(), lldb::SBQueueItem::GetExtendedBacktraceThread(), lldb::SBProcess::GetMemoryRegionInfo(), lldb::SBProcess::GetMemoryRegions(), lldb::SBProcess::GetNumQueues(), lldb::SBProcess::GetNumThreads(), lldb::SBProcess::GetQueueAtIndex(), lldb_private::ValueImpl::GetSP(), lldb_private::GetStoppedExecutionContext(), lldb::SBProcess::GetThreadAtIndex(), lldb::SBProcess::GetThreadByID(), lldb::SBProcess::GetThreadByIndexID(), lldb::SBProcess::LoadImage(), lldb::SBProcess::LoadImageUsingPaths(), lldb::SBProcess::ReadCStringFromMemory(), lldb::SBProcess::ReadMemory(), lldb::SBProcess::ReadPointerFromMemory(), lldb::SBProcess::ReadUnsignedFromMemory(), lldb::SBProcess::SendEventData(), lldb_private::ExecutionContextRef::SetProcessPtr(), lldb_private::ExecutionContextRef::SetThreadPtr(), lldb::SBProcess::UnloadImage(), and lldb::SBProcess::WriteMemory().
Unlock()
void lldb_private::ProcessRunLock::ProcessRunLocker::Unlock () inline protected
Definition at line 78 of file ProcessRunLock.h.
References m_lock.
Referenced by operator=(), TryLock(), and ~ProcessRunLocker().
Member Data Documentation
m_lock
ProcessRunLock* lldb_private::ProcessRunLock::ProcessRunLocker::m_lock = nullptr protected
Definition at line 85 of file ProcessRunLock.h.
Referenced by IsLocked(), operator=(), ProcessRunLocker(), TryLock(), and Unlock().
The documentation for this class was generated from the following file:
ProcessRunLock.h