LLDB: lldb_private::Language::MethodName Class Reference
lldb_private::Language::MethodName Class Reference
#include <Language.h>
Public Member Functions
MethodName ()
MethodName (ConstString full)
virtual ~MethodName ()
void Clear ()
bool IsValid ()
ConstString GetFullName () const
llvm::StringRef GetBasename ()
llvm::StringRef GetContext ()
llvm::StringRef GetArguments ()
llvm::StringRef GetQualifiers ()
llvm::StringRef GetReturnType ()
std::string GetScopeQualifiedName ()
Protected Member Functions
virtual void Parse ()
Protected Attributes
ConstString m_full
llvm::StringRef m_basename
llvm::StringRef m_context
llvm::StringRef m_arguments
llvm::StringRef m_qualifiers
llvm::StringRef m_return_type
std::string m_scope_qualified
bool m_parsed = false
bool m_parse_error = false
Detailed Description
Definition at line 218 of file Language.h.
Constructor & Destructor Documentation
MethodName() [1/2]
lldb_private::Language::MethodName::MethodName () inline
Definition at line 220 of file Language.h.
Referenced by lldb_private::CPlusPlusLanguage::CxxMethodName::CxxMethodName().
MethodName() [2/2]
lldb_private::Language::MethodName::MethodName (ConstString full) inline
Definition at line 222 of file Language.h.
References m_arguments, m_basename, m_context, m_full, m_parse_error, m_parsed, m_qualifiers, m_return_type, and m_scope_qualified.
~MethodName()
virtual lldb_private::Language::MethodName::~MethodName () inline virtual
Definition at line 227 of file Language.h.
Member Function Documentation
Clear()
void lldb_private::Language::MethodName::Clear () inline
Definition at line 229 of file Language.h.
References m_arguments, m_basename, m_context, m_full, m_parse_error, m_parsed, m_qualifiers, m_return_type, and m_scope_qualified.
GetArguments()
llvm::StringRef lldb_private::Language::MethodName::GetArguments () inline
Definition at line 263 of file Language.h.
References m_arguments, m_parsed, and Parse().
Referenced by lldb_private::CPlusPlusLanguage::FindBestAlternateFunctionMangledName().
GetBasename()
llvm::StringRef lldb_private::Language::MethodName::GetBasename () inline
Definition at line 251 of file Language.h.
References m_basename, m_parsed, and Parse().
Referenced by lldb_private::CPlusPlusLanguage::CxxMethodName::ContainsPath(), lldb_private::CPlusPlusLanguage::CxxMethodName::GetBasenameNoTemplateParameters(), lldb_private::CPlusPlusLanguage::GetDemangledFunctionNameWithoutArguments(), and lldb_private::CPlusPlusLanguage::GetFunctionNameInfo().
GetContext()
llvm::StringRef lldb_private::Language::MethodName::GetContext () inline
Definition at line 257 of file Language.h.
References m_context, m_parsed, and Parse().
Referenced by lldb_private::CPlusPlusLanguage::GetDemangledFunctionNameWithoutArguments().
GetFullName()
ConstString lldb_private::Language::MethodName::GetFullName () const inline
Definition at line 249 of file Language.h.
References m_full.
GetQualifiers()
llvm::StringRef lldb_private::Language::MethodName::GetQualifiers () inline
Definition at line 269 of file Language.h.
References m_parsed, m_qualifiers, and Parse().
Referenced by lldb_private::CPlusPlusLanguage::FindBestAlternateFunctionMangledName(), lldb_private::CPlusPlusLanguage::GetFunctionNameInfo(), and PrettyPrintFunctionNameWithArgs().
GetReturnType()
llvm::StringRef lldb_private::Language::MethodName::GetReturnType () inline
Definition at line 275 of file Language.h.
References m_parsed, m_return_type, and Parse().
Referenced by PrettyPrintFunctionNameWithArgs().
GetScopeQualifiedName()
std::string lldb_private::Language::MethodName::GetScopeQualifiedName () inline
Definition at line 281 of file Language.h.
References m_parsed, m_scope_qualified, and Parse().
Referenced by lldb_private::CPlusPlusLanguage::FindBestAlternateFunctionMangledName(), and PrettyPrintFunctionNameWithArgs().
IsValid()
bool lldb_private::Language::MethodName::IsValid () inline
Definition at line 241 of file Language.h.
References m_full, m_parse_error, m_parsed, and Parse().
Referenced by lldb_private::CPlusPlusLanguage::FindBestAlternateFunctionMangledName(), and PrettyPrintFunctionNameWithArgs().
Parse()
virtual void lldb_private::Language::MethodName::Parse () inline protected virtual
Reimplemented in lldb_private::CPlusPlusLanguage::CxxMethodName.
Definition at line 288 of file Language.h.
References m_parse_error, and m_parsed.
Referenced by GetArguments(), GetBasename(), GetContext(), GetQualifiers(), GetReturnType(), GetScopeQualifiedName(), and IsValid().
Member Data Documentation
m_arguments
llvm::StringRef lldb_private::Language::MethodName::m_arguments protected
Definition at line 298 of file Language.h.
Referenced by Clear(), GetArguments(), MethodName(), lldb_private::CPlusPlusLanguage::CxxMethodName::Parse(), and lldb_private::CPlusPlusLanguage::CxxMethodName::TrySimplifiedParse().
m_basename
llvm::StringRef lldb_private::Language::MethodName::m_basename protected
Definition at line 296 of file Language.h.
Referenced by Clear(), GetBasename(), MethodName(), lldb_private::CPlusPlusLanguage::CxxMethodName::Parse(), and lldb_private::CPlusPlusLanguage::CxxMethodName::TrySimplifiedParse().
m_context
llvm::StringRef lldb_private::Language::MethodName::m_context protected
Definition at line 297 of file Language.h.
Referenced by Clear(), lldb_private::CPlusPlusLanguage::CxxMethodName::ContainsPath(), GetContext(), MethodName(), lldb_private::CPlusPlusLanguage::CxxMethodName::Parse(), and lldb_private::CPlusPlusLanguage::CxxMethodName::TrySimplifiedParse().
m_full
ConstString lldb_private::Language::MethodName::m_full protected
Definition at line 293 of file Language.h.
Referenced by Clear(), lldb_private::CPlusPlusLanguage::CxxMethodName::ContainsPath(), GetFullName(), IsValid(), MethodName(), lldb_private::CPlusPlusLanguage::CxxMethodName::Parse(), and lldb_private::CPlusPlusLanguage::CxxMethodName::TrySimplifiedParse().
m_parse_error
bool lldb_private::Language::MethodName::m_parse_error = false protected
Definition at line 303 of file Language.h.
Referenced by Clear(), lldb_private::CPlusPlusLanguage::CxxMethodName::ContainsPath(), IsValid(), MethodName(), lldb_private::CPlusPlusLanguage::CxxMethodName::Parse(), and Parse().
m_parsed
bool lldb_private::Language::MethodName::m_parsed = false protected
Definition at line 302 of file Language.h.
Referenced by Clear(), lldb_private::CPlusPlusLanguage::CxxMethodName::ContainsPath(), GetArguments(), GetBasename(), GetContext(), GetQualifiers(), GetReturnType(), GetScopeQualifiedName(), IsValid(), MethodName(), lldb_private::CPlusPlusLanguage::CxxMethodName::Parse(), and Parse().
m_qualifiers
llvm::StringRef lldb_private::Language::MethodName::m_qualifiers protected
Definition at line 299 of file Language.h.
Referenced by Clear(), GetQualifiers(), MethodName(), lldb_private::CPlusPlusLanguage::CxxMethodName::Parse(), and lldb_private::CPlusPlusLanguage::CxxMethodName::TrySimplifiedParse().
m_return_type
llvm::StringRef lldb_private::Language::MethodName::m_return_type protected
Definition at line 300 of file Language.h.
Referenced by Clear(), GetReturnType(), MethodName(), lldb_private::CPlusPlusLanguage::CxxMethodName::Parse(), and lldb_private::CPlusPlusLanguage::CxxMethodName::TrySimplifiedParse().
m_scope_qualified
std::string lldb_private::Language::MethodName::m_scope_qualified protected
Definition at line 301 of file Language.h.
Referenced by Clear(), GetScopeQualifiedName(), MethodName(), and lldb_private::CPlusPlusLanguage::CxxMethodName::Parse().
The documentation for this class was generated from the following file:
Language.h