LLDB: RegisterContextPOSIX_s390x Class Reference
RegisterContextPOSIX_s390x Class Reference abstract
#include <RegisterContextPOSIX_s390x.h>
Classes
struct RegInfo
Public Member Functions
RegisterContextPOSIX_s390x (lldb_private::Thread &thread, uint32_t concrete_frame_idx, lldb_private::RegisterInfoInterface *register_info)
~RegisterContextPOSIX_s390x () override
void Invalidate ()
void InvalidateAllRegisters () override
size_t GetRegisterCount () override
virtual unsigned GetRegisterSize (unsigned reg)
virtual unsigned GetRegisterOffset (unsigned reg)
const lldb_private::RegisterInfo * GetRegisterInfoAtIndex (size_t reg) override
size_t GetRegisterSetCount () override
const lldb_private::RegisterSet * GetRegisterSet (size_t set) override
const char * GetRegisterName (unsigned reg)
Public Member Functions inherited from lldb_private::RegisterContext
RegisterContext (Thread &thread, uint32_t concrete_frame_idx)
~RegisterContext () override
void InvalidateIfNeeded (bool force)
virtual lldb::ByteOrder GetByteOrder ()
virtual bool ReadRegister (const RegisterInfo *reg_info, RegisterValue &reg_value)=0
virtual bool WriteRegister (const RegisterInfo *reg_info, const RegisterValue &reg_value)=0
virtual bool ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp)
virtual bool WriteAllRegisterValues (const lldb::DataBufferSP &data_sp)
virtual bool RegisterWriteCausesReconfigure (const llvm::StringRef name)
virtual bool ReconfigureRegisterInfo ()
virtual bool ReadAllRegisterValues (lldb_private::RegisterCheckpoint &reg_checkpoint)
virtual bool WriteAllRegisterValues (const lldb_private::RegisterCheckpoint &reg_checkpoint)
bool CopyFromRegisterContext (lldb::RegisterContextSP context)
virtual uint32_t ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num)
Convert from a given register numbering scheme to the lldb register numbering scheme.
virtual uint32_t NumSupportedHardwareBreakpoints ()
virtual uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual bool ClearHardwareBreakpoint (uint32_t hw_idx)
virtual uint32_t NumSupportedHardwareWatchpoints ()
virtual uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, bool read, bool write)
virtual bool ClearHardwareWatchpoint (uint32_t hw_index)
virtual bool HardwareSingleStep (bool enable)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, uint32_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, uint32_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual Thread & GetThread ()
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num)
uint64_t GetPC (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetThreadPointer (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool GetPCForSymbolication (Address &address)
Get an address suitable for symbolication.
bool SetPC (uint64_t pc)
bool SetPC (Address addr)
uint64_t GetSP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetSP (uint64_t sp)
uint64_t GetFP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetFP (uint64_t fp)
const char * GetRegisterName (uint32_t reg)
uint64_t GetReturnAddress (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetFlags (uint64_t fail_value=0)
uint64_t ReadRegisterAsUnsigned (uint32_t reg, uint64_t fail_value)
uint64_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, uint64_t fail_value)
bool WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
bool WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
bool ConvertBetweenRegisterKinds (lldb::RegisterKind source_rk, uint32_t source_regnum, lldb::RegisterKind target_rk, uint32_t &target_regnum)
lldb::TargetSP CalculateTarget () override
lldb::ProcessSP CalculateProcess () override
lldb::ThreadSP CalculateThread () override
lldb::StackFrameSP CalculateStackFrame () override
void CalculateExecutionContext (ExecutionContext &exe_ctx) override
Reconstruct the object's execution context into sc.
uint32_t GetStopID () const
void SetStopID (uint32_t stop_id)
Public Member Functions inherited from lldb_private::ExecutionContextScope
virtual ~ExecutionContextScope ()=default
Protected Member Functions
virtual bool IsRegisterSetAvailable (size_t set_index)
virtual const lldb_private::RegisterInfo * GetRegisterInfo ()
bool IsGPR (unsigned reg)
bool IsFPR (unsigned reg)
virtual bool ReadGPR ()=0
virtual bool ReadFPR ()=0
virtual bool WriteGPR ()=0
virtual bool WriteFPR ()=0
Protected Member Functions inherited from lldb_private::RegisterContext
virtual bool BehavesLikeZerothFrame () const
Indicates that this frame is currently executing code, that the PC value is not a return-pc but an actual executing instruction.
Protected Attributes
RegInfo m_reg_info
std::unique_ptr< lldb_private::RegisterInfoInterface > m_register_info_up
Protected Attributes inherited from lldb_private::RegisterContext
Thread & m_thread
uint32_t m_concrete_frame_idx
uint32_t m_stop_id
Detailed Description
Definition at line 18 of file RegisterContextPOSIX_s390x.h.
Constructor & Destructor Documentation
RegisterContextPOSIX_s390x()
RegisterContextPOSIX_s390x::RegisterContextPOSIX_s390x (lldb_private::Thread & thread, uint32_t concrete_frame_idx, lldb_private::RegisterInfoInterface * register_info)
Definition at line 80 of file RegisterContextPOSIX_s390x.cpp.
References lldb_private::ArchSpec::GetMachine(), lldb_private::RegisterInfoInterface::GetTargetArchitecture(), m_register_info_up, and lldb_private::RegisterContext::RegisterContext().
Referenced by RegisterContextCorePOSIX_s390x::RegisterContextCorePOSIX_s390x().
~RegisterContextPOSIX_s390x()
RegisterContextPOSIX_s390x::~RegisterContextPOSIX_s390x () override default
Member Function Documentation
GetRegisterCount()
size_t RegisterContextPOSIX_s390x::GetRegisterCount () override virtual
Implements lldb_private::RegisterContext.
Definition at line 119 of file RegisterContextPOSIX_s390x.cpp.
References m_reg_info.
GetRegisterInfo()
const RegisterInfo * RegisterContextPOSIX_s390x::GetRegisterInfo () protected virtual
Definition at line 107 of file RegisterContextPOSIX_s390x.cpp.
References m_register_info_up.
Referenced by GetRegisterInfoAtIndex(), GetRegisterName(), GetRegisterOffset(), and GetRegisterSize().
GetRegisterInfoAtIndex()
const RegisterInfo * RegisterContextPOSIX_s390x::GetRegisterInfoAtIndex (size_t reg) override virtual
Implements lldb_private::RegisterContext.
Definition at line 112 of file RegisterContextPOSIX_s390x.cpp.
References GetRegisterInfo(), and m_reg_info.
GetRegisterName()
const char * RegisterContextPOSIX_s390x::GetRegisterName (unsigned reg)
Definition at line 133 of file RegisterContextPOSIX_s390x.cpp.
References GetRegisterInfo(), m_reg_info, and lldb_private::RegisterInfo::name.
GetRegisterOffset()
unsigned RegisterContextPOSIX_s390x::GetRegisterOffset (unsigned reg) virtual
Definition at line 123 of file RegisterContextPOSIX_s390x.cpp.
References lldb_private::RegisterInfo::byte_offset, GetRegisterInfo(), and m_reg_info.
GetRegisterSet()
const RegisterSet * RegisterContextPOSIX_s390x::GetRegisterSet (size_t set) override virtual
Implements lldb_private::RegisterContext.
Definition at line 152 of file RegisterContextPOSIX_s390x.cpp.
References g_reg_sets_s390x, IsRegisterSetAvailable(), and m_register_info_up.
GetRegisterSetCount()
size_t RegisterContextPOSIX_s390x::GetRegisterSetCount () override virtual
Implements lldb_private::RegisterContext.
Definition at line 142 of file RegisterContextPOSIX_s390x.cpp.
References IsRegisterSetAvailable(), and k_num_register_sets.
GetRegisterSize()
unsigned RegisterContextPOSIX_s390x::GetRegisterSize (unsigned reg) virtual
Definition at line 128 of file RegisterContextPOSIX_s390x.cpp.
References lldb_private::RegisterInfo::byte_size, GetRegisterInfo(), and m_reg_info.
Invalidate()
void RegisterContextPOSIX_s390x::Invalidate ()
Definition at line 103 of file RegisterContextPOSIX_s390x.cpp.
InvalidateAllRegisters()
void RegisterContextPOSIX_s390x::InvalidateAllRegisters () override virtual
Implements lldb_private::RegisterContext.
Definition at line 105 of file RegisterContextPOSIX_s390x.cpp.
IsFPR()
bool RegisterContextPOSIX_s390x::IsFPR (unsigned reg) protected
Definition at line 76 of file RegisterContextPOSIX_s390x.cpp.
References m_reg_info.
Referenced by RegisterContextCorePOSIX_s390x::ReadRegister().
IsGPR()
bool RegisterContextPOSIX_s390x::IsGPR (unsigned reg) protected
Definition at line 72 of file RegisterContextPOSIX_s390x.cpp.
References m_reg_info.
Referenced by RegisterContextCorePOSIX_s390x::ReadRegister().
IsRegisterSetAvailable()
bool RegisterContextPOSIX_s390x::IsRegisterSetAvailable (size_t set_index) protected virtual
Definition at line 138 of file RegisterContextPOSIX_s390x.cpp.
References k_num_register_sets.
Referenced by GetRegisterSet(), and GetRegisterSetCount().
ReadFPR()
virtual bool RegisterContextPOSIX_s390x::ReadFPR () protected pure virtual
Implemented in RegisterContextCorePOSIX_s390x.
ReadGPR()
virtual bool RegisterContextPOSIX_s390x::ReadGPR () protected pure virtual
Implemented in RegisterContextCorePOSIX_s390x.
WriteFPR()
virtual bool RegisterContextPOSIX_s390x::WriteFPR () protected pure virtual
Implemented in RegisterContextCorePOSIX_s390x.
WriteGPR()
virtual bool RegisterContextPOSIX_s390x::WriteGPR () protected pure virtual
Implemented in RegisterContextCorePOSIX_s390x.
Member Data Documentation
m_reg_info
RegInfo RegisterContextPOSIX_s390x::m_reg_info protected
Definition at line 55 of file RegisterContextPOSIX_s390x.h.
Referenced by GetRegisterCount(), GetRegisterInfoAtIndex(), GetRegisterName(), GetRegisterOffset(), GetRegisterSize(), IsFPR(), and IsGPR().
m_register_info_up
std::unique_ptr<lldb_private::RegisterInfoInterface> RegisterContextPOSIX_s390x::m_register_info_up protected
Definition at line 56 of file RegisterContextPOSIX_s390x.h.
Referenced by GetRegisterInfo(), GetRegisterSet(), and RegisterContextPOSIX_s390x().
The documentation for this class was generated from the following files:
RegisterContextPOSIX_s390x.h
RegisterContextPOSIX_s390x.cpp