LLDB: lldb_private::ThreadPlanRunToAddress Class Reference
lldb_private::ThreadPlanRunToAddress Class Reference
#include <ThreadPlanRunToAddress.h>
Public Member Functions
ThreadPlanRunToAddress (Thread &thread, Address &address, bool stop_others)
ThreadPlanRunToAddress (Thread &thread, lldb::addr_t address, bool stop_others)
ThreadPlanRunToAddress (Thread &thread, const std::vector< lldb::addr_t > &addresses, bool stop_others)
~ThreadPlanRunToAddress () override
void GetDescription (Stream *s, lldb::DescriptionLevel level) override
Print a description of this thread to the stream s.
bool ValidatePlan (Stream *error) override
Returns whether this plan could be successfully created.
bool ShouldStop (Event *event_ptr) override
bool StopOthers () override
void SetStopOthers (bool new_value) override
lldb::StateType GetPlanRunState () override
bool WillStop () override
bool MischiefManaged () override
Public Member Functions inherited from lldb_private::ThreadPlan
virtual ~ThreadPlan ()
const char * GetName () const
Returns the name of this thread plan.
Thread & GetThread ()
Returns the Thread that is using this thread plan.
Target & GetTarget ()
const Target & GetTarget () const
void ClearThreadCache ()
Clear the Thread* cache.
bool TracerExplainsStop ()
lldb::StateType RunState ()
bool PlanExplainsStop (Event *event_ptr)
virtual bool ShouldAutoContinue (Event *event_ptr)
Returns whether this thread plan overrides the ShouldStop of subsequently processed plans.
virtual Vote ShouldReportStop (Event *event_ptr)
Vote ShouldReportRun (Event *event_ptr)
virtual bool SupportsResumeOthers ()
virtual bool ShouldRunBeforePublicStop ()
bool WillResume (lldb::StateType resume_state, bool current_plan)
bool IsControllingPlan ()
virtual bool IsLeafPlan ()
bool SetIsControllingPlan (bool value)
virtual bool OkayToDiscard ()
void SetOkayToDiscard (bool value)
virtual void ThreadDestroyed ()
bool GetPrivate ()
void SetPrivate (bool input)
virtual void DidPush ()
virtual void DidPop ()
ThreadPlanKind GetKind () const
bool IsPlanComplete ()
void SetPlanComplete (bool success=true)
virtual bool IsPlanStale ()
bool PlanSucceeded ()
virtual bool IsBasePlan ()
lldb::ThreadPlanTracerSP & GetThreadPlanTracer ()
void SetThreadPlanTracer (lldb::ThreadPlanTracerSP new_tracer_sp)
void DoTraceLog ()
virtual lldb::ValueObjectSP GetReturnValueObject ()
virtual lldb::ExpressionVariableSP GetExpressionVariable ()
virtual void RestoreThreadState ()
virtual bool IsVirtualStep ()
bool SetIterationCount (size_t count)
virtual lldb::RunDirection GetDirection () const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Protected Member Functions
bool DoPlanExplainsStop (Event *event_ptr) override
void SetInitialBreakpoints ()
bool AtOurAddress ()
Protected Member Functions inherited from lldb_private::ThreadPlan
ThreadPlan (ThreadPlanKind kind, const char *name, Thread &thread, Vote report_stop_vote, Vote report_run_vote)
virtual bool DoWillResume (lldb::StateType resume_state, bool current_plan)
void PushPlan (lldb::ThreadPlanSP &thread_plan_sp)
ThreadPlan * GetPreviousPlan ()
lldb::StopInfoSP GetPrivateStopInfo ()
void SetStopInfo (lldb::StopInfoSP stop_reason_sp)
bool IsUsuallyUnexplainedStopReason (lldb::StopReason)
Private Member Functions
ThreadPlanRunToAddress (const ThreadPlanRunToAddress &)=delete
const ThreadPlanRunToAddress & operator= (const ThreadPlanRunToAddress &)=delete
Private Attributes
bool m_stop_others
std::vector< lldb::addr_t > m_addresses
std::vector< lldb::break_id_t > m_break_ids
Additional Inherited Members
Public Types inherited from lldb_private::ThreadPlan
enum ThreadPlanKind {
eKindGeneric , eKindNull , eKindBase , eKindCallFunction ,
eKindPython , eKindStepInstruction , eKindStepOut , eKindStepOverBreakpoint ,
eKindStepOverRange , eKindStepInRange , eKindRunToAddress , eKindStepThrough ,
eKindStepUntil , eKindSingleThreadTimeout
}
Protected Attributes inherited from lldb_private::ThreadPlan
Status m_status
Process & m_process
lldb::tid_t m_tid
Vote m_report_stop_vote
Vote m_report_run_vote
bool m_takes_iteration_count
bool m_could_not_resolve_hw_bp
int32_t m_iteration_count = 1
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Detailed Description
Definition at line 19 of file ThreadPlanRunToAddress.h.
Constructor & Destructor Documentation
ThreadPlanRunToAddress() [1/4]
ThreadPlanRunToAddress::ThreadPlanRunToAddress (Thread & thread, Address & address, bool stop_others)
Definition at line 23 of file ThreadPlanRunToAddress.cpp.
References lldb_private::ThreadPlan::eKindRunToAddress, lldb_private::eVoteNoOpinion, lldb_private::Address::GetOpcodeLoadAddress(), m_addresses, m_break_ids, m_stop_others, SetInitialBreakpoints(), and lldb_private::ThreadPlan::ThreadPlan().
Referenced by operator=(), and ThreadPlanRunToAddress().
ThreadPlanRunToAddress() [2/4]
ThreadPlanRunToAddress::ThreadPlanRunToAddress (Thread & thread, lldb::addr_t address, bool stop_others)
Definition at line 33 of file ThreadPlanRunToAddress.cpp.
References lldb_private::ThreadPlan::eKindRunToAddress, lldb_private::eVoteNoOpinion, m_addresses, m_break_ids, m_stop_others, SetInitialBreakpoints(), and lldb_private::ThreadPlan::ThreadPlan().
ThreadPlanRunToAddress() [3/4]
ThreadPlanRunToAddress::ThreadPlanRunToAddress (Thread & thread, const std::vector< lldb::addr_t > & addresses, bool stop_others)
Definition at line 44 of file ThreadPlanRunToAddress.cpp.
References lldb_private::ThreadPlan::eKindRunToAddress, lldb_private::eVoteNoOpinion, lldb_private::Target::GetOpcodeLoadAddress(), lldb_private::ThreadPlan::GetTarget(), m_addresses, m_break_ids, m_stop_others, SetInitialBreakpoints(), and lldb_private::ThreadPlan::ThreadPlan().
~ThreadPlanRunToAddress()
ThreadPlanRunToAddress::~ThreadPlanRunToAddress () override
Definition at line 78 of file ThreadPlanRunToAddress.cpp.
References lldb_private::ThreadPlan::GetTarget(), m_break_ids, lldb_private::ThreadPlan::m_could_not_resolve_hw_bp, and lldb_private::Target::RemoveBreakpointByID().
ThreadPlanRunToAddress() [4/4]
lldb_private::ThreadPlanRunToAddress::ThreadPlanRunToAddress (const ThreadPlanRunToAddress &) private delete
References ThreadPlanRunToAddress().
Member Function Documentation
AtOurAddress()
bool ThreadPlanRunToAddress::AtOurAddress () protected
Definition at line 192 of file ThreadPlanRunToAddress.cpp.
References lldb_private::Thread::GetRegisterContext(), lldb_private::ThreadPlan::GetThread(), and m_addresses.
Referenced by DoPlanExplainsStop(), MischiefManaged(), and ShouldStop().
DoPlanExplainsStop()
bool ThreadPlanRunToAddress::DoPlanExplainsStop (Event * event_ptr) override protected virtual
Implements lldb_private::ThreadPlan.
Definition at line 154 of file ThreadPlanRunToAddress.cpp.
References AtOurAddress().
GetDescription()
void ThreadPlanRunToAddress::GetDescription (Stream * s, lldb::DescriptionLevel level) override virtual
Print a description of this thread to the stream s.
thread. Don't expect that the result of GetThread is valid in the description method. This might get called when the underlying Thread has not been reported, so we only know the TID and not the thread.
Parameters
[in] s The stream to which to print the description.
[in] level The level of description desired. Note that eDescriptionLevelBrief will be used in the stop message printed when the plan is complete.
Implements lldb_private::ThreadPlan.
Definition at line 86 of file ThreadPlanRunToAddress.cpp.
References lldb_private::Stream::AsRawOstream(), lldb_private::Breakpoint::Dump(), lldb_private::DumpAddress(), lldb::eDescriptionLevelBrief, lldb_private::Target::GetBreakpointByID(), lldb_private::ThreadPlan::GetTarget(), lldb_private::Stream::Indent(), m_addresses, m_break_ids, and lldb_private::Stream::Printf().
GetPlanRunState()
StateType ThreadPlanRunToAddress::GetPlanRunState () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 168 of file ThreadPlanRunToAddress.cpp.
References lldb::eStateRunning.
MischiefManaged()
bool ThreadPlanRunToAddress::MischiefManaged () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 172 of file ThreadPlanRunToAddress.cpp.
References AtOurAddress(), lldb_private::GetLog(), lldb_private::ThreadPlan::GetTarget(), LLDB_INVALID_BREAK_ID, LLDB_LOGF, m_break_ids, lldb_private::ThreadPlan::MischiefManaged(), lldb_private::Target::RemoveBreakpointByID(), and lldb_private::Step.
operator=()
const ThreadPlanRunToAddress & lldb_private::ThreadPlanRunToAddress::operator= (const ThreadPlanRunToAddress &) private delete
References ThreadPlanRunToAddress().
SetInitialBreakpoints()
void ThreadPlanRunToAddress::SetInitialBreakpoints () protected
Definition at line 60 of file ThreadPlanRunToAddress.cpp.
References lldb_private::Target::CreateBreakpoint(), lldb_private::Stoppoint::GetID(), lldb_private::ThreadPlan::GetTarget(), lldb_private::Breakpoint::HasResolvedLocations(), lldb_private::Breakpoint::IsHardware(), m_addresses, m_break_ids, lldb_private::ThreadPlan::m_could_not_resolve_hw_bp, lldb_private::ThreadPlan::m_tid, lldb_private::Breakpoint::SetBreakpointKind(), and lldb_private::Breakpoint::SetThreadID().
Referenced by ThreadPlanRunToAddress(), ThreadPlanRunToAddress(), and ThreadPlanRunToAddress().
SetStopOthers()
void ThreadPlanRunToAddress::SetStopOthers (bool new_value) override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 164 of file ThreadPlanRunToAddress.cpp.
References m_stop_others.
ShouldStop()
bool ThreadPlanRunToAddress::ShouldStop (Event * event_ptr) override virtual
Implements lldb_private::ThreadPlan.
Definition at line 158 of file ThreadPlanRunToAddress.cpp.
References AtOurAddress().
StopOthers()
bool ThreadPlanRunToAddress::StopOthers () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 162 of file ThreadPlanRunToAddress.cpp.
References m_stop_others.
ValidatePlan()
bool ThreadPlanRunToAddress::ValidatePlan (Stream * error) override virtual
Returns whether this plan could be successfully created.
Parameters
[in] error A stream to which to print some reason why the plan could not be created. Can be NULL.
Returns
true if the plan should be queued, false otherwise.
Implements lldb_private::ThreadPlan.
Definition at line 131 of file ThreadPlanRunToAddress.cpp.
References lldb_private::DumpAddress(), error(), LLDB_INVALID_BREAK_ID, m_addresses, m_break_ids, and lldb_private::ThreadPlan::m_could_not_resolve_hw_bp.
WillStop()
bool ThreadPlanRunToAddress::WillStop () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 170 of file ThreadPlanRunToAddress.cpp.
Member Data Documentation
m_addresses
std::vector<lldb::addr_t> lldb_private::ThreadPlanRunToAddress::m_addresses private
Definition at line 57 of file ThreadPlanRunToAddress.h.
Referenced by AtOurAddress(), GetDescription(), SetInitialBreakpoints(), ThreadPlanRunToAddress(), ThreadPlanRunToAddress(), ThreadPlanRunToAddress(), and ValidatePlan().
m_break_ids
std::vector<lldb::break_id_t> lldb_private::ThreadPlanRunToAddress::m_break_ids private
Definition at line 59 of file ThreadPlanRunToAddress.h.
Referenced by GetDescription(), MischiefManaged(), SetInitialBreakpoints(), ThreadPlanRunToAddress(), ThreadPlanRunToAddress(), ThreadPlanRunToAddress(), ValidatePlan(), and ~ThreadPlanRunToAddress().
m_stop_others
bool lldb_private::ThreadPlanRunToAddress::m_stop_others private
Definition at line 55 of file ThreadPlanRunToAddress.h.
Referenced by SetStopOthers(), StopOthers(), ThreadPlanRunToAddress(), ThreadPlanRunToAddress(), and ThreadPlanRunToAddress().
The documentation for this class was generated from the following files:
ThreadPlanRunToAddress.h
ThreadPlanRunToAddress.cpp