LLDB: lldb_private::AppleObjCRuntimeV2::SharedCacheImageHeaders Class Reference
lldb_private::AppleObjCRuntimeV2::SharedCacheImageHeaders Class Reference
Public Member Functions
void SetNeedsUpdate ()
bool IsImageLoaded (uint16_t image_index)
uint64_t GetVersion ()
Static Public Member Functions
static std::unique_ptr< SharedCacheImageHeaders > CreateSharedCacheImageHeaders (AppleObjCRuntimeV2 &runtime)
Private Member Functions
SharedCacheImageHeaders (AppleObjCRuntimeV2 &runtime, lldb::addr_t headerInfoRWs_ptr, uint32_t count, uint32_t entsize)
llvm::Error UpdateIfNeeded ()
Private Attributes
AppleObjCRuntimeV2 & m_runtime
lldb::addr_t m_headerInfoRWs_ptr
llvm::BitVector m_loaded_images
uint64_t m_version
uint32_t m_count
uint32_t m_entsize
bool m_needs_update
Detailed Description
Definition at line 390 of file AppleObjCRuntimeV2.h.
Constructor & Destructor Documentation
SharedCacheImageHeaders()
lldb_private::AppleObjCRuntimeV2::SharedCacheImageHeaders::SharedCacheImageHeaders (AppleObjCRuntimeV2 & runtime, lldb::addr_t headerInfoRWs_ptr, uint32_t count, uint32_t entsize) inline private
Definition at line 402 of file AppleObjCRuntimeV2.h.
References lldb_private::AppleObjCRuntimeV2::AppleObjCRuntimeV2(), m_count, m_entsize, m_headerInfoRWs_ptr, m_loaded_images, m_needs_update, m_runtime, and m_version.
Member Function Documentation
CreateSharedCacheImageHeaders()
std::unique_ptr< AppleObjCRuntimeV2::SharedCacheImageHeaders > AppleObjCRuntimeV2::SharedCacheImageHeaders::CreateSharedCacheImageHeaders (AppleObjCRuntimeV2 & runtime) static
Definition at line 1621 of file AppleObjCRuntimeV2.cpp.
References LLDB_INVALID_ADDRESS, and lldb_private::AppleObjCRuntimeV2::m_tagged_pointer_obfuscator.
Referenced by ObjCExceptionRecognizedStackFrame::ObjCExceptionRecognizedStackFrame().
GetVersion()
uint64_t AppleObjCRuntimeV2::SharedCacheImageHeaders::GetVersion ()
Definition at line 1751 of file AppleObjCRuntimeV2.cpp.
References lldb_private::DataExtractor::GetU32_unchecked(), and m_entsize.
IsImageLoaded()
bool AppleObjCRuntimeV2::SharedCacheImageHeaders::IsImageLoaded (uint16_t image_index)
Definition at line 1739 of file AppleObjCRuntimeV2.cpp.
References error(), lldb_private::Process::GetAddressByteSize(), lldb_private::Process::GetByteOrder(), m_count, m_entsize, and lldb_private::Process::ReadMemory().
SetNeedsUpdate()
void lldb_private::AppleObjCRuntimeV2::SharedCacheImageHeaders::SetNeedsUpdate () inline
Definition at line 395 of file AppleObjCRuntimeV2.h.
References m_needs_update.
UpdateIfNeeded()
llvm::Error AppleObjCRuntimeV2::SharedCacheImageHeaders::UpdateIfNeeded () private
Definition at line 1693 of file AppleObjCRuntimeV2.cpp.
References error(), and LLDB_LOG.
Member Data Documentation
m_count
uint32_t lldb_private::AppleObjCRuntimeV2::SharedCacheImageHeaders::m_count private
Definition at line 414 of file AppleObjCRuntimeV2.h.
Referenced by IsImageLoaded(), and SharedCacheImageHeaders().
m_entsize
uint32_t lldb_private::AppleObjCRuntimeV2::SharedCacheImageHeaders::m_entsize private
Definition at line 415 of file AppleObjCRuntimeV2.h.
Referenced by GetVersion(), IsImageLoaded(), and SharedCacheImageHeaders().
m_headerInfoRWs_ptr
lldb::addr_t lldb_private::AppleObjCRuntimeV2::SharedCacheImageHeaders::m_headerInfoRWs_ptr private
Definition at line 411 of file AppleObjCRuntimeV2.h.
Referenced by SharedCacheImageHeaders().
m_loaded_images
llvm::BitVector lldb_private::AppleObjCRuntimeV2::SharedCacheImageHeaders::m_loaded_images private
Definition at line 412 of file AppleObjCRuntimeV2.h.
Referenced by SharedCacheImageHeaders().
m_needs_update
bool lldb_private::AppleObjCRuntimeV2::SharedCacheImageHeaders::m_needs_update private
Definition at line 416 of file AppleObjCRuntimeV2.h.
Referenced by SetNeedsUpdate(), and SharedCacheImageHeaders().
m_runtime
AppleObjCRuntimeV2& lldb_private::AppleObjCRuntimeV2::SharedCacheImageHeaders::m_runtime private
Definition at line 410 of file AppleObjCRuntimeV2.h.
Referenced by SharedCacheImageHeaders().
m_version
uint64_t lldb_private::AppleObjCRuntimeV2::SharedCacheImageHeaders::m_version private
Definition at line 413 of file AppleObjCRuntimeV2.h.
Referenced by SharedCacheImageHeaders().
The documentation for this class was generated from the following files:
AppleObjCRuntimeV2.h
AppleObjCRuntimeV2.cpp