LLDB: lldb_private::AddressRangeListImpl Class Reference
lldb_private::AddressRangeListImpl Class Reference
#include <AddressRangeListImpl.h>
Public Member Functions
AddressRangeListImpl ()
AddressRangeListImpl (AddressRanges ranges)
size_t GetSize () const
void Reserve (size_t capacity)
void Append (const AddressRange &sb_region)
void Append (const AddressRangeListImpl &list)
void Clear ()
lldb_private::AddressRange GetAddressRangeAtIndex (size_t index)
Private Member Functions
AddressRanges & ref ()
Private Attributes
AddressRanges m_ranges
Friends
class lldb::SBAddressRangeList
class lldb::SBBlock
class lldb::SBProcess
Detailed Description
Definition at line 23 of file AddressRangeListImpl.h.
Constructor & Destructor Documentation
AddressRangeListImpl() [1/2]
AddressRangeListImpl::AddressRangeListImpl ()
Definition at line 14 of file AddressRangeListImpl.cpp.
References m_ranges.
Referenced by Append().
AddressRangeListImpl() [2/2]
lldb_private::AddressRangeListImpl::AddressRangeListImpl (AddressRanges ranges) inline explicit
Definition at line 27 of file AddressRangeListImpl.h.
References m_ranges.
Member Function Documentation
Append() [1/2]
void AddressRangeListImpl::Append (const AddressRange & sb_region)
Definition at line 22 of file AddressRangeListImpl.cpp.
References m_ranges.
Referenced by lldb::SBAddressRangeList::Append(), lldb::SBAddressRangeList::Append(), and Append().
Append() [2/2]
void AddressRangeListImpl::Append (const AddressRangeListImpl & list)
Definition at line 26 of file AddressRangeListImpl.cpp.
References AddressRangeListImpl(), Append(), GetSize(), m_ranges, and Reserve().
Clear()
void AddressRangeListImpl::Clear ()
Definition at line 33 of file AddressRangeListImpl.cpp.
References m_ranges.
Referenced by lldb::SBAddressRangeList::Clear().
GetAddressRangeAtIndex()
lldb_private::AddressRange AddressRangeListImpl::GetAddressRangeAtIndex (size_t index)
Definition at line 36 of file AddressRangeListImpl.cpp.
References GetSize(), and m_ranges.
Referenced by lldb::SBAddressRangeList::GetAddressRangeAtIndex().
GetSize()
size_t AddressRangeListImpl::GetSize () const
Definition at line 16 of file AddressRangeListImpl.cpp.
References m_ranges.
Referenced by Append(), GetAddressRangeAtIndex(), and lldb::SBAddressRangeList::GetSize().
ref()
AddressRanges & AddressRangeListImpl::ref () private
Definition at line 42 of file AddressRangeListImpl.cpp.
References m_ranges.
Referenced by lldb::SBProcess::FindRangesInMemory().
Reserve()
void AddressRangeListImpl::Reserve (size_t capacity)
Definition at line 18 of file AddressRangeListImpl.cpp.
References m_ranges.
Referenced by Append().
Friends And Related Symbol Documentation
lldb::SBAddressRangeList
friend class lldb::SBAddressRangeList friend
Definition at line 43 of file AddressRangeListImpl.h.
lldb::SBBlock
friend class lldb::SBBlock friend
Definition at line 44 of file AddressRangeListImpl.h.
lldb::SBProcess
friend class lldb::SBProcess friend
Definition at line 45 of file AddressRangeListImpl.h.
Member Data Documentation
m_ranges
AddressRanges lldb_private::AddressRangeListImpl::m_ranges private
Definition at line 49 of file AddressRangeListImpl.h.
Referenced by AddressRangeListImpl(), AddressRangeListImpl(), Append(), Append(), Clear(), GetAddressRangeAtIndex(), GetSize(), ref(), and Reserve().
The documentation for this class was generated from the following files:
AddressRangeListImpl.h
AddressRangeListImpl.cpp