LLDB: CommandObjectBreakpointAddException::CommandOptions Class Reference
CommandObjectBreakpointAddException::CommandOptions Class Reference
Public Member Functions
CommandOptions ()=default
~CommandOptions () override=default
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext *execution_context) override
void OptionParsingStarting (ExecutionContext *execution_context) override
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Public Attributes
bool m_hardware = false
Args m_exception_extra_args
uint32_t m_exception_stage = eExceptionStageThrow
Detailed Description
Definition at line 556 of file CommandObjectBreakpoint.cpp.
Constructor & Destructor Documentation
CommandOptions()
CommandObjectBreakpointAddException::CommandOptions::CommandOptions () default
~CommandOptions()
CommandObjectBreakpointAddException::CommandOptions::~CommandOptions () override default
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > CommandObjectBreakpointAddException::CommandOptions::GetDefinitions () inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 598 of file CommandObjectBreakpoint.cpp.
Referenced by SetOptionValue().
OptionParsingStarting()
void CommandObjectBreakpointAddException::CommandOptions::OptionParsingStarting (ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 592 of file CommandObjectBreakpoint.cpp.
References lldb::eExceptionStageThrow, m_exception_extra_args, m_exception_stage, and m_hardware.
SetOptionValue()
Status CommandObjectBreakpointAddException::CommandOptions::SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 562 of file CommandObjectBreakpoint.cpp.
References lldb::eExceptionStageThrow, error(), GetDefinitions(), m_exception_extra_args, m_exception_stage, m_hardware, and lldb_private::OptionArgParser::ToOptionEnum().
Member Data Documentation
m_exception_extra_args
Args CommandObjectBreakpointAddException::CommandOptions::m_exception_extra_args
Definition at line 604 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_exception_stage
uint32_t CommandObjectBreakpointAddException::CommandOptions::m_exception_stage = eExceptionStageThrow
Definition at line 605 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_hardware
bool CommandObjectBreakpointAddException::CommandOptions::m_hardware = false
Definition at line 603 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following file:
CommandObjectBreakpoint.cpp