LLDB: lldb_private::LockFilePosix Class Reference
lldb_private::LockFilePosix Class Reference
#include <LockFilePosix.h>
Public Member Functions
LockFilePosix (int fd)
~LockFilePosix () override
Public Member Functions inherited from lldb_private::LockFileBase
virtual ~LockFileBase ()=default
bool IsLocked () const
Status WriteLock (const uint64_t start, const uint64_t len)
Status TryWriteLock (const uint64_t start, const uint64_t len)
Status ReadLock (const uint64_t start, const uint64_t len)
Status TryReadLock (const uint64_t start, const uint64_t len)
Status Unlock ()
Protected Member Functions
Status DoWriteLock (const uint64_t start, const uint64_t len) override
Status DoTryWriteLock (const uint64_t start, const uint64_t len) override
Status DoReadLock (const uint64_t start, const uint64_t len) override
Status DoTryReadLock (const uint64_t start, const uint64_t len) override
Status DoUnlock () override
Protected Member Functions inherited from lldb_private::LockFileBase
LockFileBase (int fd)
virtual bool IsValidFile () const
Status DoLock (const Locker &locker, const uint64_t start, const uint64_t len)
Additional Inherited Members
Protected Types inherited from lldb_private::LockFileBase
using Locker = std::function<Status(const uint64_t, const uint64_t)>
Protected Attributes inherited from lldb_private::LockFileBase
int m_fd
bool m_locked
uint64_t m_start
uint64_t m_len
Detailed Description
Definition at line 16 of file LockFilePosix.h.
Constructor & Destructor Documentation
LockFilePosix()
LockFilePosix::LockFilePosix (int fd) explicit
Definition at line 35 of file LockFilePosix.cpp.
References lldb_private::LockFileBase::LockFileBase().
~LockFilePosix()
LockFilePosix::~LockFilePosix () override
Definition at line 37 of file LockFilePosix.cpp.
References lldb_private::LockFileBase::Unlock().
Member Function Documentation
DoReadLock()
Status LockFilePosix::DoReadLock (const uint64_t start, const uint64_t len) override protected virtual
Implements lldb_private::LockFileBase.
Definition at line 47 of file LockFilePosix.cpp.
References fileLock(), and lldb_private::LockFileBase::m_fd.
DoTryReadLock()
Status LockFilePosix::DoTryReadLock (const uint64_t start, const uint64_t len) override protected virtual
Implements lldb_private::LockFileBase.
Definition at line 51 of file LockFilePosix.cpp.
References fileLock(), and lldb_private::LockFileBase::m_fd.
DoTryWriteLock()
Status LockFilePosix::DoTryWriteLock (const uint64_t start, const uint64_t len) override protected virtual
Implements lldb_private::LockFileBase.
Definition at line 43 of file LockFilePosix.cpp.
References fileLock(), and lldb_private::LockFileBase::m_fd.
DoUnlock()
Status LockFilePosix::DoUnlock () override protected virtual
Implements lldb_private::LockFileBase.
Definition at line 55 of file LockFilePosix.cpp.
References fileLock(), lldb_private::LockFileBase::m_fd, lldb_private::LockFileBase::m_len, and lldb_private::LockFileBase::m_start.
DoWriteLock()
Status LockFilePosix::DoWriteLock (const uint64_t start, const uint64_t len) override protected virtual
Implements lldb_private::LockFileBase.
Definition at line 39 of file LockFilePosix.cpp.
References fileLock(), and lldb_private::LockFileBase::m_fd.
The documentation for this class was generated from the following files:
LockFilePosix.h
LockFilePosix.cpp