LLDB: lldb_private::BytecodeSyntheticChildren::FrontEnd Class Reference
lldb_private::BytecodeSyntheticChildren::FrontEnd Class Reference
Public Member Functions
FrontEnd (ValueObject &backend, SyntheticBytecodeImplementation &impl)
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Attributes
const SyntheticBytecodeImplementation & m_impl
FormatterBytecode::DataStack m_self
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
Definition at line 496 of file TypeSynthetic.h.
Constructor & Destructor Documentation
FrontEnd()
BytecodeSyntheticChildren::FrontEnd::FrontEnd (ValueObject & backend, SyntheticBytecodeImplementation & impl)
Definition at line 258 of file TypeSynthetic.cpp.
References lldb_private::DataFormatters, error(), lldb_private::GetLog(), lldb_private::ValueObject::GetSP(), lldb_private::FormatterBytecode::Interpret(), LLDB_LOG_ERROR, m_impl, m_self, and lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd().
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > BytecodeSyntheticChildren::FrontEnd::CalculateNumChildren () override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 301 of file TypeSynthetic.cpp.
References lldb_private::DataFormatters, error(), lldb_private::GetLog(), lldb_private::FormatterBytecode::Interpret(), LLDB_LOG, m_impl, m_self, and UINT32_MAX.
GetChildAtIndex()
lldb::ValueObjectSP BytecodeSyntheticChildren::FrontEnd::GetChildAtIndex (uint32_t idx) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 332 of file TypeSynthetic.cpp.
References lldb_private::DataFormatters, error(), lldb_private::GetLog(), lldb_private::FormatterBytecode::Interpret(), LLDB_LOG, LLDB_LOG_ERROR, m_impl, and m_self.
GetIndexOfChildWithName()
llvm::Expected< size_t > BytecodeSyntheticChildren::FrontEnd::GetIndexOfChildWithName (ConstString name) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 362 of file TypeSynthetic.cpp.
References lldb_private::DataFormatters, error(), lldb_private::GetLog(), lldb_private::ConstString::GetString(), lldb_private::FormatterBytecode::Interpret(), LLDB_LOG, m_impl, and m_self.
Update()
lldb::ChildCacheState BytecodeSyntheticChildren::FrontEnd::Update () override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 280 of file TypeSynthetic.cpp.
References lldb_private::DataFormatters, lldb::eRefetch, error(), lldb_private::GetLog(), lldb_private::FormatterBytecode::Interpret(), LLDB_LOG_ERROR, m_impl, and m_self.
Member Data Documentation
m_impl
const SyntheticBytecodeImplementation& lldb_private::BytecodeSyntheticChildren::FrontEnd::m_impl private
Definition at line 506 of file TypeSynthetic.h.
Referenced by CalculateNumChildren(), FrontEnd(), GetChildAtIndex(), GetIndexOfChildWithName(), and Update().
m_self
FormatterBytecode::DataStack lldb_private::BytecodeSyntheticChildren::FrontEnd::m_self private
Definition at line 507 of file TypeSynthetic.h.
Referenced by CalculateNumChildren(), FrontEnd(), GetChildAtIndex(), GetIndexOfChildWithName(), and Update().
The documentation for this class was generated from the following files:
TypeSynthetic.h
TypeSynthetic.cpp