LLDB: lldb_private::TypeSummaryOptions Class Reference
lldb_private::TypeSummaryOptions Class Reference
#include <TypeSummary.h>
Public Member Functions
TypeSummaryOptions ()
~TypeSummaryOptions ()=default
lldb::LanguageType GetLanguage () const
lldb::TypeSummaryCapping GetCapping () const
TypeSummaryOptions & SetLanguage (lldb::LanguageType)
TypeSummaryOptions & SetCapping (lldb::TypeSummaryCapping)
Private Attributes
lldb::LanguageType m_lang = lldb::eLanguageTypeUnknown
lldb::TypeSummaryCapping m_capping = lldb::eTypeSummaryCapped
Detailed Description
Definition at line 30 of file TypeSummary.h.
Constructor & Destructor Documentation
TypeSummaryOptions()
TypeSummaryOptions::TypeSummaryOptions () default
Referenced by SetLanguage(), and ~TypeSummaryOptions().
~TypeSummaryOptions()
lldb_private::TypeSummaryOptions::~TypeSummaryOptions () default
References TypeSummaryOptions().
Member Function Documentation
GetCapping()
lldb::TypeSummaryCapping TypeSummaryOptions::GetCapping () const
Definition at line 32 of file TypeSummary.cpp.
References m_capping.
Referenced by lldb_private::formatters::NSStringSummaryProvider().
GetLanguage()
lldb::LanguageType TypeSummaryOptions::GetLanguage () const
Definition at line 30 of file TypeSummary.cpp.
References m_lang.
Referenced by lldb_private::formatters::CFBagSummaryProvider(), lldb_private::formatters::CFBinaryHeapSummaryProvider(), lldb_private::ValueObject::GetSummaryAsCString(), lldb_private::formatters::NSArraySummaryProvider(), lldb_private::formatters::NSDictionarySummaryProvider(), lldb_private::formatters::NSIndirectTaggedString_SummaryProvider(), lldb_private::formatters::NSNumberSummaryProvider(), lldb_private::formatters::NSSetSummaryProvider(), lldb_private::formatters::NSStringSummaryProvider(), lldb_private::formatters::NSTaggedString_SummaryProvider(), and lldb_private::formatters::NSURLSummaryProvider().
SetCapping()
TypeSummaryOptions & TypeSummaryOptions::SetCapping (lldb::TypeSummaryCapping cap)
Definition at line 42 of file TypeSummary.cpp.
References m_capping.
SetLanguage()
TypeSummaryOptions & TypeSummaryOptions::SetLanguage (lldb::LanguageType lang)
Definition at line 36 of file TypeSummary.cpp.
References m_lang, and TypeSummaryOptions().
Referenced by lldb_private::ValueObject::GetSummaryAsCString(), and lldb_private::ValueObject::GetSummaryAsCString().
Member Data Documentation
m_capping
lldb::TypeSummaryCapping lldb_private::TypeSummaryOptions::m_capping = lldb::eTypeSummaryCapped private
Definition at line 46 of file TypeSummary.h.
Referenced by GetCapping(), and SetCapping().
m_lang
lldb::LanguageType lldb_private::TypeSummaryOptions::m_lang = lldb::eLanguageTypeUnknown private
Definition at line 45 of file TypeSummary.h.
Referenced by GetLanguage(), and SetLanguage().
The documentation for this class was generated from the following files:
TypeSummary.h
TypeSummary.cpp