LLDB: lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd Class Reference
lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd Class Reference
Public Member Functions
LibcxxStdMapSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
~LibcxxStdMapSyntheticFrontEnd () override=default
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Member Functions
llvm::Expected< uint32_t > CalculateNumChildrenForOldCompressedPairLayout (ValueObject &pair)
ValueObjectSP GetKeyValuePair (size_t idx, size_t max_depth)
Returns the ValueObject for the __tree_node type that holds the key/value pair of the node at index idx.
Private Attributes
ValueObject * m_tree = nullptr
ValueObject * m_root_node = nullptr
CompilerType m_node_ptr_type
size_t m_count = UINT32_MAX
std::map< size_t, MapIterator > m_iterators
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
Definition at line 188 of file LibCxxMap.cpp.
Constructor & Destructor Documentation
LibcxxStdMapSyntheticFrontEnd()
lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::LibcxxStdMapSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
Definition at line 249 of file LibCxxMap.cpp.
References lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd(), and Update().
~LibcxxStdMapSyntheticFrontEnd()
lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::~LibcxxStdMapSyntheticFrontEnd () override default
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::CalculateNumChildren () override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 269 of file LibCxxMap.cpp.
References CalculateNumChildrenForOldCompressedPairLayout(), lldb_private::formatters::GetValueOrOldCompressedPair(), m_count, m_tree, and UINT32_MAX.
CalculateNumChildrenForOldCompressedPairLayout()
llvm::Expected< uint32_t > lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::CalculateNumChildrenForOldCompressedPairLayout (ValueObject & pair) private
Definition at line 257 of file LibCxxMap.cpp.
References lldb_private::formatters::GetFirstValueOfLibCXXCompressedPair(), and m_count.
Referenced by CalculateNumChildren().
GetChildAtIndex()
lldb::ValueObjectSP lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::GetChildAtIndex (uint32_t idx) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 330 of file LibCxxMap.cpp.
References lldb_private::SyntheticChildrenFrontEnd::CalculateNumChildrenIgnoringErrors(), GetKeyValuePair(), lldb_private::StreamString::GetString(), m_root_node, m_tree, and lldb_private::Stream::Printf().
GetIndexOfChildWithName()
llvm::Expected< size_t > lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::GetIndexOfChildWithName (ConstString name) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 393 of file LibCxxMap.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::formatters::ExtractIndexFromString(), and lldb_private::ConstString::GetCString().
GetKeyValuePair()
ValueObjectSP lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::GetKeyValuePair (size_t idx, size_t max_depth) private
Returns the ValueObject for the __tree_node type that holds the key/value pair of the node at index idx.
Parameters
[in] idx The child index that we're looking to get the key/value pair for.
[in] max_depth The maximum search depth after which we stop trying to find the key/value pair for.
Returns
On success, returns the ValueObjectSP corresponding to the __tree_node's __value_ member (which holds the key/value pair the formatter wants to display). On failure, will return nullptr.
Definition at line 290 of file LibCxxMap.cpp.
References m_iterators, m_node_ptr_type, and m_root_node.
Referenced by GetChildAtIndex().
Update()
lldb::ChildCacheState lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::Update () override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 378 of file LibCxxMap.cpp.
References lldb::eRefetch, lldb_private::SyntheticChildrenFrontEnd::m_backend, m_count, m_iterators, m_node_ptr_type, m_root_node, m_tree, and UINT32_MAX.
Referenced by LibcxxStdMapSyntheticFrontEnd().
Member Data Documentation
m_count
size_t lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::m_count = UINT32_MAX private
Definition at line 225 of file LibCxxMap.cpp.
Referenced by CalculateNumChildren(), CalculateNumChildrenForOldCompressedPairLayout(), and Update().
m_iterators
std::map<size_t, MapIterator> lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::m_iterators private
Definition at line 226 of file LibCxxMap.cpp.
Referenced by GetKeyValuePair(), and Update().
m_node_ptr_type
CompilerType lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::m_node_ptr_type private
Definition at line 224 of file LibCxxMap.cpp.
Referenced by GetKeyValuePair(), and Update().
m_root_node
ValueObject* lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::m_root_node = nullptr private
Definition at line 223 of file LibCxxMap.cpp.
Referenced by GetChildAtIndex(), GetKeyValuePair(), and Update().
m_tree
ValueObject* lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::m_tree = nullptr private
Definition at line 222 of file LibCxxMap.cpp.
Referenced by CalculateNumChildren(), GetChildAtIndex(), and Update().
The documentation for this class was generated from the following file:
LibCxxMap.cpp