LLDB: lldb_private::ThreadPlanNull Class Reference
lldb_private::ThreadPlanNull Class Reference
#include <ThreadPlan.h>
Public Member Functions
ThreadPlanNull (Thread &thread)
~ThreadPlanNull () override
void GetDescription (Stream *s, lldb::DescriptionLevel level) override
Print a description of this thread to the stream s.
bool ValidatePlan (Stream *error) override
Returns whether this plan could be successfully created.
bool ShouldStop (Event *event_ptr) override
bool MischiefManaged () override
bool WillStop () override
bool IsBasePlan () override
bool OkayToDiscard () override
const Status & GetStatus ()
Public Member Functions inherited from lldb_private::ThreadPlan
virtual ~ThreadPlan ()
const char * GetName () const
Returns the name of this thread plan.
Thread & GetThread ()
Returns the Thread that is using this thread plan.
Target & GetTarget ()
const Target & GetTarget () const
void ClearThreadCache ()
Clear the Thread* cache.
bool TracerExplainsStop ()
lldb::StateType RunState ()
bool PlanExplainsStop (Event *event_ptr)
virtual bool ShouldAutoContinue (Event *event_ptr)
Returns whether this thread plan overrides the ShouldStop of subsequently processed plans.
virtual Vote ShouldReportStop (Event *event_ptr)
Vote ShouldReportRun (Event *event_ptr)
virtual void SetStopOthers (bool new_value)
virtual bool StopOthers ()
virtual bool SupportsResumeOthers ()
virtual bool ShouldRunBeforePublicStop ()
bool WillResume (lldb::StateType resume_state, bool current_plan)
bool IsControllingPlan ()
virtual bool IsLeafPlan ()
bool SetIsControllingPlan (bool value)
void SetOkayToDiscard (bool value)
virtual void ThreadDestroyed ()
bool GetPrivate ()
void SetPrivate (bool input)
virtual void DidPush ()
virtual void DidPop ()
ThreadPlanKind GetKind () const
bool IsPlanComplete ()
void SetPlanComplete (bool success=true)
virtual bool IsPlanStale ()
bool PlanSucceeded ()
lldb::ThreadPlanTracerSP & GetThreadPlanTracer ()
void SetThreadPlanTracer (lldb::ThreadPlanTracerSP new_tracer_sp)
void DoTraceLog ()
virtual lldb::ValueObjectSP GetReturnValueObject ()
virtual lldb::ExpressionVariableSP GetExpressionVariable ()
virtual void RestoreThreadState ()
virtual bool IsVirtualStep ()
bool SetIterationCount (size_t count)
virtual lldb::RunDirection GetDirection () const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Protected Member Functions
bool DoPlanExplainsStop (Event *event_ptr) override
lldb::StateType GetPlanRunState () override
ThreadPlanNull (const ThreadPlanNull &)=delete
const ThreadPlanNull & operator= (const ThreadPlanNull &)=delete
Protected Member Functions inherited from lldb_private::ThreadPlan
ThreadPlan (ThreadPlanKind kind, const char *name, Thread &thread, Vote report_stop_vote, Vote report_run_vote)
virtual bool DoWillResume (lldb::StateType resume_state, bool current_plan)
void PushPlan (lldb::ThreadPlanSP &thread_plan_sp)
ThreadPlan * GetPreviousPlan ()
lldb::StopInfoSP GetPrivateStopInfo ()
void SetStopInfo (lldb::StopInfoSP stop_reason_sp)
bool IsUsuallyUnexplainedStopReason (lldb::StopReason)
Additional Inherited Members
Public Types inherited from lldb_private::ThreadPlan
enum ThreadPlanKind {
eKindGeneric , eKindNull , eKindBase , eKindCallFunction ,
eKindPython , eKindStepInstruction , eKindStepOut , eKindStepOverBreakpoint ,
eKindStepOverRange , eKindStepInRange , eKindRunToAddress , eKindStepThrough ,
eKindStepUntil , eKindSingleThreadTimeout
}
Protected Attributes inherited from lldb_private::ThreadPlan
Status m_status
Process & m_process
lldb::tid_t m_tid
Vote m_report_stop_vote
Vote m_report_run_vote
bool m_takes_iteration_count
bool m_could_not_resolve_hw_bp
int32_t m_iteration_count = 1
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Detailed Description
Definition at line 596 of file ThreadPlan.h.
Constructor & Destructor Documentation
ThreadPlanNull() [1/2]
ThreadPlanNull::ThreadPlanNull (Thread & thread)
Definition at line 186 of file ThreadPlan.cpp.
References lldb_private::ThreadPlan::eKindNull, lldb_private::eVoteNoOpinion, and lldb_private::ThreadPlan::ThreadPlan().
Referenced by operator=(), and ThreadPlanNull().
~ThreadPlanNull()
ThreadPlanNull::~ThreadPlanNull () override default
References error().
ThreadPlanNull() [2/2]
lldb_private::ThreadPlanNull::ThreadPlanNull (const ThreadPlanNull &) protected delete
References ThreadPlanNull().
Member Function Documentation
DoPlanExplainsStop()
bool ThreadPlanNull::DoPlanExplainsStop (Event * event_ptr) override protected virtual
Implements lldb_private::ThreadPlan.
Definition at line 244 of file ThreadPlan.cpp.
References lldb_private::Log::Error(), lldb_private::UserID::GetID(), lldb_private::GetLog(), lldb_private::ThreadPlan::GetThread(), lldb_private::ThreadPlan::m_tid, and lldb_private::Thread.
GetDescription()
void ThreadPlanNull::GetDescription (Stream * s, lldb::DescriptionLevel level) override virtual
Print a description of this thread to the stream s.
thread. Don't expect that the result of GetThread is valid in the description method. This might get called when the underlying Thread has not been reported, so we only know the TID and not the thread.
Parameters
[in] s The stream to which to print the description.
[in] level The level of description desired. Note that eDescriptionLevelBrief will be used in the stop message printed when the plan is complete.
Implements lldb_private::ThreadPlan.
Definition at line 192 of file ThreadPlan.cpp.
References lldb_private::Stream::PutCString().
GetPlanRunState()
lldb::StateType ThreadPlanNull::GetPlanRunState () override protected virtual
Implements lldb_private::ThreadPlan.
Definition at line 278 of file ThreadPlan.cpp.
References lldb_private::Log::Error(), lldb::eStateRunning, lldb_private::GetLog(), lldb_private::ThreadPlan::GetThread(), lldb_private::ThreadPlan::m_tid, and lldb_private::Thread.
GetStatus()
const Status & lldb_private::ThreadPlanNull::GetStatus () inline
Definition at line 615 of file ThreadPlan.h.
References lldb_private::ThreadPlan::m_status.
IsBasePlan()
bool lldb_private::ThreadPlanNull::IsBasePlan () inline override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 611 of file ThreadPlan.h.
MischiefManaged()
bool ThreadPlanNull::MischiefManaged () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 261 of file ThreadPlan.cpp.
References lldb_private::Log::Error(), lldb_private::GetLog(), lldb_private::ThreadPlan::GetThread(), lldb_private::ThreadPlan::m_tid, and lldb_private::Thread.
OkayToDiscard()
bool lldb_private::ThreadPlanNull::OkayToDiscard () inline override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 613 of file ThreadPlan.h.
operator=()
const ThreadPlanNull & lldb_private::ThreadPlanNull::operator= (const ThreadPlanNull &) protected delete
References ThreadPlanNull().
ShouldStop()
bool ThreadPlanNull::ShouldStop (Event * event_ptr) override virtual
Implements lldb_private::ThreadPlan.
Definition at line 212 of file ThreadPlan.cpp.
References lldb_private::Log::Error(), lldb_private::GetLog(), lldb_private::ThreadPlan::GetThread(), lldb_private::ThreadPlan::m_tid, and lldb_private::Thread.
ValidatePlan()
bool ThreadPlanNull::ValidatePlan (Stream * error) override virtual
Returns whether this plan could be successfully created.
Parameters
[in] error A stream to which to print some reason why the plan could not be created. Can be NULL.
Returns
true if the plan should be queued, false otherwise.
Implements lldb_private::ThreadPlan.
Definition at line 196 of file ThreadPlan.cpp.
References lldb_private::Log::Error(), error(), lldb_private::GetLog(), lldb_private::ThreadPlan::GetThread(), lldb_private::ThreadPlan::m_tid, and lldb_private::Thread.
WillStop()
bool ThreadPlanNull::WillStop () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 228 of file ThreadPlan.cpp.
References lldb_private::Log::Error(), lldb_private::GetLog(), lldb_private::ThreadPlan::GetThread(), lldb_private::ThreadPlan::m_tid, and lldb_private::Thread.
The documentation for this class was generated from the following files:
ThreadPlan.h
ThreadPlan.cpp