LLDB: lldb_private::ProtocolServer Class Reference
lldb_private::ProtocolServer Class Reference abstract
#include <ProtocolServer.h>
Classes
struct Connection
Public Member Functions
ProtocolServer ()=default
virtual ~ProtocolServer ()=default
virtual llvm::Error Start (Connection connection)=0
virtual llvm::Error Stop ()=0
virtual Socket * GetSocket () const =0
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
virtual llvm::StringRef GetPluginName ()=0
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static ProtocolServer * GetOrCreate (llvm::StringRef name)
static llvm::Error Terminate ()
static std::vector< llvm::StringRef > GetSupportedProtocols ()
Detailed Description
Definition at line 18 of file ProtocolServer.h.
Constructor & Destructor Documentation
ProtocolServer()
lldb_private::ProtocolServer::ProtocolServer () default
Referenced by GetOrCreate(), lldb_private::mcp::ProtocolServerMCP::ProtocolServerMCP(), and ~ProtocolServer().
~ProtocolServer()
virtual lldb_private::ProtocolServer::~ProtocolServer () virtual default
References ProtocolServer().
Member Function Documentation
GetOrCreate()
ProtocolServer * ProtocolServer::GetOrCreate (llvm::StringRef name) static
Definition at line 22 of file ProtocolServer.cpp.
References lldb_private::PluginManager::GetProtocolCreateCallbackForPluginName(), ProtocolServer(), and Servers().
Referenced by CommandObjectProtocolServerGet::DoExecute(), CommandObjectProtocolServerStart::DoExecute(), and CommandObjectProtocolServerStop::DoExecute().
GetSocket()
virtual Socket * lldb_private::ProtocolServer::GetSocket () const pure virtual
Implemented in lldb_private::mcp::ProtocolServerMCP.
Referenced by CommandObjectProtocolServerGet::DoExecute(), and CommandObjectProtocolServerStart::DoExecute().
GetSupportedProtocols()
std::vector< llvm::StringRef > ProtocolServer::GetSupportedProtocols () static
Definition at line 40 of file ProtocolServer.cpp.
References lldb_private::PluginManager::GetProtocolServerPluginNameAtIndex().
Referenced by CommandObjectProtocolServerGet::DoExecute(), CommandObjectProtocolServerStart::DoExecute(), and CommandObjectProtocolServerStop::DoExecute().
Start()
virtual llvm::Error lldb_private::ProtocolServer::Start (Connection connection) pure virtual
Implemented in lldb_private::mcp::ProtocolServerMCP.
Referenced by CommandObjectProtocolServerStart::DoExecute().
Stop()
virtual llvm::Error lldb_private::ProtocolServer::Stop () pure virtual
Implemented in lldb_private::mcp::ProtocolServerMCP.
Referenced by CommandObjectProtocolServerStop::DoExecute().
Terminate()
llvm::Error ProtocolServer::Terminate () static
Definition at line 54 of file ProtocolServer.cpp.
References error(), and Servers().
Referenced by lldb_private::mcp::ProtocolServerMCP::Terminate().
The documentation for this class was generated from the following files:
ProtocolServer.h
ProtocolServer.cpp