LLDB: lldb_private::TypeMatcher Class Reference
lldb_private::TypeMatcher Class Reference
Class for matching type names.
#include <FormattersContainer.h>
Public Member Functions
TypeMatcher ()=delete
TypeMatcher (ConstString type_name)
Creates a matcher that accepts any type with exactly the given type name.
TypeMatcher (RegularExpression regex)
Creates a matcher that accepts any type matching the given regex.
TypeMatcher (lldb::TypeNameSpecifierImplSP type_specifier)
Creates a matcher using the matching type and string from the given type name specifier.
bool Matches (FormattersMatchCandidate candidate_type) const
True iff this matches the given type.
lldb::FormatterMatchType GetMatchType () const
ConstString GetMatchString () const
Returns the underlying match string for this TypeMatcher.
bool CreatedBySameMatchString (TypeMatcher other) const
Returns true if this TypeMatcher and the given one were most created by the same match string.
Static Private Member Functions
static ConstString StripTypeName (ConstString type)
Private Attributes
ConstString m_name
Type name for exact match, or name of the python callback if m_match_type is eFormatterMatchCallback.
RegularExpression m_type_name_regex
lldb::FormatterMatchType m_match_type
Indicates what kind of matching strategy should be used:
Detailed Description
Class for matching type names.
Definition at line 40 of file FormattersContainer.h.
Constructor & Destructor Documentation
TypeMatcher() [1/4]
lldb_private::TypeMatcher::TypeMatcher () delete
Referenced by CreatedBySameMatchString().
TypeMatcher() [2/4]
lldb_private::TypeMatcher::TypeMatcher (ConstString type_name) inline
Creates a matcher that accepts any type with exactly the given type name.
Definition at line 75 of file FormattersContainer.h.
References m_match_type, and m_name.
TypeMatcher() [3/4]
lldb_private::TypeMatcher::TypeMatcher (RegularExpression regex) inline
Creates a matcher that accepts any type matching the given regex.
Definition at line 78 of file FormattersContainer.h.
References m_match_type, and m_type_name_regex.
TypeMatcher() [4/4]
lldb_private::TypeMatcher::TypeMatcher (lldb::TypeNameSpecifierImplSP type_specifier) inline
Creates a matcher using the matching type and string from the given type name specifier.
Definition at line 83 of file FormattersContainer.h.
References lldb::eFormatterMatchRegex, GetMatchType(), GetName(), m_match_type, m_name, m_type_name_regex, and lldb_private::RegularExpression.
Member Function Documentation
CreatedBySameMatchString()
bool lldb_private::TypeMatcher::CreatedBySameMatchString (TypeMatcher other) const inline
Returns true if this TypeMatcher and the given one were most created by the same match string.
The main purpose of this function is to find existing TypeMatcher instances by the user input that created them. This is necessary as LLDB allows referencing existing TypeMatchers in commands by the user input that originally created them: (lldb) type summary add –summary-string "A" -x TypeName (lldb) type summary delete TypeName
Definition at line 132 of file FormattersContainer.h.
References GetMatchString(), and TypeMatcher().
GetMatchString()
ConstString lldb_private::TypeMatcher::GetMatchString () const inline
Returns the underlying match string for this TypeMatcher.
Definition at line 116 of file FormattersContainer.h.
References lldb::eFormatterMatchExact, lldb::eFormatterMatchRegex, m_match_type, m_name, m_type_name_regex, and StripTypeName().
Referenced by lldb_private::FormattersContainer< TypeSummaryImpl >::AutoComplete(), CommandObjectTypeCategoryDefine::CommandObjectTypeCategoryDefine(), CreatedBySameMatchString(), and lldb_private::FormattersContainer< TypeSummaryImpl >::GetTypeNameSpecifierAtIndex().
GetMatchType()
lldb::FormatterMatchType lldb_private::TypeMatcher::GetMatchType () const inline
Definition at line 113 of file FormattersContainer.h.
References m_match_type.
Referenced by lldb_private::FormattersContainer< TypeSummaryImpl >::GetTypeNameSpecifierAtIndex(), and TypeMatcher().
Matches()
bool lldb_private::TypeMatcher::Matches (FormattersMatchCandidate candidate_type) const inline
True iff this matches the given type.
Definition at line 91 of file FormattersContainer.h.
References lldb::eFormatterMatchCallback, lldb::eFormatterMatchExact, lldb::eFormatterMatchRegex, lldb_private::ScriptInterpreter::FormatterCallbackFunction(), lldb_private::FormattersMatchCandidate::GetScriptInterpreter(), lldb_private::ConstString::GetStringRef(), lldb_private::FormattersMatchCandidate::GetType(), lldb_private::FormattersMatchCandidate::GetTypeName(), m_match_type, m_name, m_type_name_regex, and StripTypeName().
StripTypeName()
ConstString lldb_private::TypeMatcher::StripTypeName (ConstString type) inline static private
Definition at line 57 of file FormattersContainer.h.
References lldb_private::ConstString::AsCString(), and lldb_private::ConstString::IsEmpty().
Referenced by GetMatchString(), and Matches().
Member Data Documentation
m_match_type
lldb::FormatterMatchType lldb_private::TypeMatcher::m_match_type private
Indicates what kind of matching strategy should be used:
eFormatterMatchExact: match the exact type name in m_name.
eFormatterMatchRegex: match using the RegularExpression object m_type_name_regex instead.
eFormatterMatchCallback: run the function in m_name to decide if a type matches or not.
Definition at line 51 of file FormattersContainer.h.
Referenced by GetMatchString(), GetMatchType(), Matches(), TypeMatcher(), TypeMatcher(), and TypeMatcher().
m_name
ConstString lldb_private::TypeMatcher::m_name private
Type name for exact match, or name of the python callback if m_match_type is eFormatterMatchCallback.
Definition at line 43 of file FormattersContainer.h.
Referenced by GetMatchString(), Matches(), TypeMatcher(), and TypeMatcher().
m_type_name_regex
RegularExpression lldb_private::TypeMatcher::m_type_name_regex private
Definition at line 44 of file FormattersContainer.h.
Referenced by GetMatchString(), Matches(), TypeMatcher(), and TypeMatcher().
The documentation for this class was generated from the following file:
FormattersContainer.h