LLDB: DynamicLoaderDarwinKernel Class Reference
DynamicLoaderDarwinKernel Class Reference
#include <DynamicLoaderDarwinKernel.h>
Classes
class KextImageInfo
struct OSKextLoadedKextSummaryHeader
Public Member Functions
DynamicLoaderDarwinKernel (lldb_private::Process *process, lldb::addr_t kernel_addr)
~DynamicLoaderDarwinKernel () override
void DidAttach () override
Called after attaching a process.
void DidLaunch () override
Called after attaching a process.
lldb::ThreadPlanSP GetStepThroughTrampolinePlan (lldb_private::Thread &thread, bool stop_others) override
Provides a plan to step through the dynamic loader trampoline for the current state of thread.
lldb_private::Status CanLoadImage () override
Ask if it is ok to try and load or unload an shared library (image).
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::DynamicLoader
DynamicLoader (Process *process)
Construct with a process.
virtual bool ProcessDidExec ()
Helper function that can be used to detect when a process has called exec and is now a new and different process.
bool GetStopWhenImagesChange () const
Get whether the process should stop when images change.
void SetStopWhenImagesChange (bool stop)
Set whether the process should stop when images change.
virtual void FindEquivalentSymbols (const Symbol *original_symbol, ModuleList &module_list, SymbolContextList &equivalent_symbols)
Some dynamic loaders provide features where there are a group of symbols "equivalent to" a given symbol one of which will be chosen when the symbol is bound.
virtual bool AlwaysRelyOnEHUnwindInfo (SymbolContext &sym_ctx)
Ask if the eh_frame information for the given SymbolContext should be relied on even when it's the first frame in a stack unwind.
virtual lldb::addr_t GetThreadLocalData (const lldb::ModuleSP module, const lldb::ThreadSP thread, lldb::addr_t tls_file_addr)
Retrieves the per-module TLS block for a given thread.
virtual lldb::ModuleSP LoadModuleAtAddress (const lldb_private::FileSpec &file, lldb::addr_t link_map_addr, lldb::addr_t base_addr, bool base_addr_is_offset)
Locates or creates a module given by file and updates/loads the resulting module at the virtual base address base_addr.
virtual bool GetSharedCacheInformation (lldb::addr_t &base_address, UUID &uuid, LazyBool &using_shared_cache, LazyBool &private_shared_cache, lldb_private::FileSpec &shared_cache_path)
Get information about the shared cache for a process, if possible.
virtual bool IsFullyInitialized ()
Return whether the dynamic loader is fully initialized and it's safe to call its APIs.
virtual std::optional< lldb_private::Address > GetStartAddress ()
Return the start address in the dynamic loader module.
virtual void CalculateDynamicSaveCoreRanges (lldb_private::Process &process, std::vector< lldb_private::MemoryRegionInfo > &ranges, llvm::function_ref< bool(const lldb_private::Thread &)> save_thread_predicate)
Returns a list of memory ranges that should be saved in the core file, specific for this dynamic loader.
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static lldb_private::DynamicLoader * CreateInstance (lldb_private::Process *process, bool force)
static void DebuggerInitialize (lldb_private::Debugger &debugger)
static lldb::addr_t SearchForDarwinKernel (lldb_private::Process *process)
Static Public Member Functions inherited from lldb_private::DynamicLoader
static DynamicLoader * FindPlugin (Process *process, llvm::StringRef plugin_name)
Find a dynamic loader plugin for a given process.
static lldb::ModuleSP LoadBinaryWithUUIDAndAddress (Process *process, llvm::StringRef name, UUID uuid, lldb::addr_t value, bool value_is_offset, bool force_symbol_search, bool notify, bool set_address_in_target, bool allow_memory_image_last_resort)
Find/load a binary into lldb given a UUID and the address where it is loaded in memory, or a slide to be applied to the file address.
Protected Types
enum { KERNEL_MODULE_MAX_NAME = 64u , KERNEL_MODULE_ENTRY_SIZE_VERSION_1 = 64u + 16u + 8u + 8u + 8u + 4u + 4u }
Protected Member Functions
void PrivateInitialize (lldb_private::Process *process)
void PrivateProcessStateChanged (lldb_private::Process *process, lldb::StateType state)
void UpdateIfNeeded ()
void LoadKernelModuleIfNeeded ()
void Clear (bool clear_process)
void PutToLog (lldb_private::Log *log) const
bool BreakpointHit (lldb_private::StoppointCallbackContext *context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id)
uint32_t GetAddrByteSize ()
void RegisterNotificationCallbacks ()
void UnregisterNotificationCallbacks ()
void SetNotificationBreakpointIfNeeded ()
bool ReadAllKextSummaries ()
bool ReadKextSummaryHeader ()
bool ParseKextSummaries (const lldb_private::Address &kext_summary_addr, uint32_t count)
void UpdateImageInfosHeaderAndLoadCommands (KextImageInfo::collection &image_infos, uint32_t infos_count, bool update_executable)
uint32_t ReadKextSummaries (const lldb_private::Address &kext_summary_addr, uint32_t image_infos_count, KextImageInfo::collection &image_infos)
Protected Member Functions inherited from lldb_private::DynamicLoader
lldb::ModuleSP FindModuleViaTarget (const FileSpec &file)
Find a module in the target that matches the given file.
lldb::ModuleSP GetTargetExecutable ()
Checks to see if the target module has changed, updates the target accordingly and returns the target executable module.
virtual void UpdateLoadedSections (lldb::ModuleSP module, lldb::addr_t link_map_addr, lldb::addr_t base_addr, bool base_addr_is_offset)
Updates the load address of every allocatable section in module.
void UpdateLoadedSectionsCommon (lldb::ModuleSP module, lldb::addr_t base_addr, bool base_addr_is_offset)
virtual void UnloadSections (const lldb::ModuleSP module)
Removes the loaded sections from the target in module.
void UnloadSectionsCommon (const lldb::ModuleSP module)
const lldb_private::SectionList * GetSectionListFromModule (const lldb::ModuleSP module) const
int64_t ReadUnsignedIntWithSizeInBytes (lldb::addr_t addr, int size_in_bytes)
lldb::addr_t ReadPointer (lldb::addr_t addr)
void LoadOperatingSystemPlugin (bool flush)
Static Protected Member Functions
static bool BreakpointHitCallback (void *baton, lldb_private::StoppointCallbackContext *context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id)
static lldb::ByteOrder GetByteOrderFromMagic (uint32_t magic)
static lldb::addr_t SearchForKernelAtSameLoadAddr (lldb_private::Process *process)
static lldb::addr_t SearchForKernelWithDebugHints (lldb_private::Process *process)
static lldb::addr_t SearchForKernelNearPC (lldb_private::Process *process)
static lldb::addr_t SearchForKernelViaExhaustiveSearch (lldb_private::Process *process)
static bool ReadMachHeader (lldb::addr_t addr, lldb_private::Process *process, llvm::MachO::mach_header &mh, bool *read_error=nullptr)
static lldb_private::UUID CheckForKernelImageAtAddress (lldb::addr_t addr, lldb_private::Process *process, bool *read_error=nullptr)
Protected Attributes
lldb::addr_t m_kernel_load_address
KextImageInfo m_kernel
lldb_private::Address m_kext_summary_header_ptr_addr
lldb_private::Address m_kext_summary_header_addr
OSKextLoadedKextSummaryHeader m_kext_summary_header
KextImageInfo::collection m_known_kexts
std::recursive_mutex m_mutex
lldb::user_id_t m_break_id
Protected Attributes inherited from lldb_private::DynamicLoader
Process * m_process
The process that this dynamic loader plug-in is tracking.
Private Member Functions
DynamicLoaderDarwinKernel (const DynamicLoaderDarwinKernel &)=delete
const DynamicLoaderDarwinKernel & operator= (const DynamicLoaderDarwinKernel &)=delete
Detailed Description
Definition at line 25 of file DynamicLoaderDarwinKernel.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
KERNEL_MODULE_MAX_NAME
KERNEL_MODULE_ENTRY_SIZE_VERSION_1
Definition at line 89 of file DynamicLoaderDarwinKernel.h.
Constructor & Destructor Documentation
DynamicLoaderDarwinKernel() [1/2]
DynamicLoaderDarwinKernel::DynamicLoaderDarwinKernel (lldb_private::Process * process, lldb::addr_t kernel_addr)
Definition at line 518 of file DynamicLoaderDarwinKernel.cpp.
References lldb_private::DynamicLoader::DynamicLoader(), error(), lldb_private::PlatformDarwinKernel::GetPluginNameStatic(), lldb_private::Process::GetTarget(), LLDB_INVALID_BREAK_ID, m_break_id, m_kernel, m_kernel_load_address, m_kext_summary_header, m_kext_summary_header_addr, m_kext_summary_header_ptr_addr, m_known_kexts, m_mutex, lldb_private::Process::SetCanRunCode(), and lldb_private::Target::SetPlatform().
Referenced by BreakpointHitCallback(), CreateInstance(), DynamicLoaderDarwinKernel(), and operator=().
~DynamicLoaderDarwinKernel()
DynamicLoaderDarwinKernel::~DynamicLoaderDarwinKernel () override
Definition at line 534 of file DynamicLoaderDarwinKernel.cpp.
References Clear().
DynamicLoaderDarwinKernel() [2/2]
DynamicLoaderDarwinKernel::DynamicLoaderDarwinKernel (const DynamicLoaderDarwinKernel &) private delete
References DynamicLoaderDarwinKernel().
Member Function Documentation
BreakpointHit()
bool DynamicLoaderDarwinKernel::BreakpointHit (lldb_private::StoppointCallbackContext * context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id) protected
Definition at line 1169 of file DynamicLoaderDarwinKernel.cpp.
References lldb_private::DynamicLoader, lldb_private::GetLog(), lldb_private::DynamicLoader::GetStopWhenImagesChange(), LLDB_LOGF, PutToLog(), and ReadAllKextSummaries().
Referenced by BreakpointHitCallback().
BreakpointHitCallback()
bool DynamicLoaderDarwinKernel::BreakpointHitCallback (void * baton, lldb_private::StoppointCallbackContext * context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id) static protected
Definition at line 1162 of file DynamicLoaderDarwinKernel.cpp.
References BreakpointHit(), and DynamicLoaderDarwinKernel().
Referenced by SetNotificationBreakpointIfNeeded().
CanLoadImage()
Status DynamicLoaderDarwinKernel::CanLoadImage () override virtual
Ask if it is ok to try and load or unload an shared library (image).
The dynamic loader often knows when it would be ok to try and load or unload a shared library. This function call allows the dynamic loader plug-ins to check any current dyld state to make sure it is an ok time to load a shared library.
Returns
true if it is currently ok to try and load a shared library into the process, false otherwise.
Implements lldb_private::DynamicLoader.
Definition at line 1625 of file DynamicLoaderDarwinKernel.cpp.
References error(), and lldb_private::Status::FromErrorString().
CheckForKernelImageAtAddress()
lldb_private::UUID DynamicLoaderDarwinKernel::CheckForKernelImageAtAddress (lldb::addr_t addr, lldb_private::Process * process, bool * read_error = nullptr) static protected
Definition at line 440 of file DynamicLoaderDarwinKernel.cpp.
References lldb_private::DynamicLoader, lldb_private::eArchTypeMachO, lldb_private::Target::GetArchitecture(), lldb_private::GetLog(), lldb_private::Process::GetTarget(), lldb_private::ArchSpec::GetTriple(), is_kernel(), lldb_private::ArchSpec::IsCompatibleMatch(), LLDB_INVALID_ADDRESS, LLDB_LOG_ERROR, LLDB_LOGF, ReadMachHeader(), lldb_private::Process::ReadModuleFromMemory(), and lldb_private::Target::SetArchitecture().
Referenced by CreateInstance(), SearchForKernelAtSameLoadAddr(), SearchForKernelNearPC(), SearchForKernelViaExhaustiveSearch(), and SearchForKernelWithDebugHints().
Clear()
void DynamicLoaderDarwinKernel::Clear (bool clear_process) protected
Definition at line 559 of file DynamicLoaderDarwinKernel.cpp.
References LLDB_BREAK_ID_IS_VALID, LLDB_INVALID_BREAK_ID, m_break_id, m_kernel, m_kext_summary_header_addr, m_kext_summary_header_ptr_addr, m_known_kexts, m_mutex, and lldb_private::DynamicLoader::m_process.
Referenced by PrivateInitialize(), PrivateProcessStateChanged(), and ~DynamicLoaderDarwinKernel().
CreateInstance()
DynamicLoader * DynamicLoaderDarwinKernel::CreateInstance (lldb_private::Process * process, bool force) static
Definition at line 152 of file DynamicLoaderDarwinKernel.cpp.
References CheckForKernelImageAtAddress(), lldb_private::DynamicLoader::DynamicLoader(), DynamicLoaderDarwinKernel(), lldb_private::Target::GetArchitecture(), lldb_private::Target::GetExecutableModulePointer(), lldb_private::Process::GetTarget(), lldb_private::ArchSpec::GetTriple(), is_kernel(), and SearchForDarwinKernel().
Referenced by Initialize(), and Terminate().
DebuggerInitialize()
void DynamicLoaderDarwinKernel::DebuggerInitialize (lldb_private::Debugger & debugger) static
Definition at line 1642 of file DynamicLoaderDarwinKernel.cpp.
References lldb_private::PluginManager::CreateSettingForDynamicLoaderPlugin(), GetGlobalProperties(), lldb_private::PluginManager::GetSettingForDynamicLoaderPlugin(), and DynamicLoaderDarwinKernelProperties::GetSettingName().
Referenced by Initialize().
DidAttach()
void DynamicLoaderDarwinKernel::DidAttach () override virtual
Called after attaching a process.
We've attached to a remote connection, or read a corefile.
Allow DynamicLoader plug-ins to execute some code after attaching to a process.
Now load the kernel binary and potentially the kexts, add them to the Target.
Implements lldb_private::DynamicLoader.
Definition at line 544 of file DynamicLoaderDarwinKernel.cpp.
References lldb_private::DynamicLoader::m_process, PrivateInitialize(), and UpdateIfNeeded().
DidLaunch()
void DynamicLoaderDarwinKernel::DidLaunch () override virtual
Called after attaching a process.
Allow DynamicLoader plug-ins to execute some code after attaching to a process.
Implements lldb_private::DynamicLoader.
Definition at line 553 of file DynamicLoaderDarwinKernel.cpp.
References lldb_private::DynamicLoader::m_process, PrivateInitialize(), and UpdateIfNeeded().
GetAddrByteSize()
uint32_t DynamicLoaderDarwinKernel::GetAddrByteSize () inline protected
Definition at line 85 of file DynamicLoaderDarwinKernel.h.
References m_kernel.
GetByteOrderFromMagic()
lldb::ByteOrder DynamicLoaderDarwinKernel::GetByteOrderFromMagic (uint32_t magic) static protected
Definition at line 1660 of file DynamicLoaderDarwinKernel.cpp.
References lldb::eByteOrderBig, lldb::eByteOrderInvalid, lldb::eByteOrderLittle, and lldb_private::endian::InlHostByteOrder().
GetPluginDescriptionStatic()
llvm::StringRef DynamicLoaderDarwinKernel::GetPluginDescriptionStatic () static
Definition at line 1654 of file DynamicLoaderDarwinKernel.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef DynamicLoaderDarwinKernel::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 62 of file DynamicLoaderDarwinKernel.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef DynamicLoaderDarwinKernel::GetPluginNameStatic () inline static
Definition at line 37 of file DynamicLoaderDarwinKernel.h.
Referenced by ProcessKDP::DoConnectRemote(), GetPluginName(), Initialize(), ProcessMachCore::LoadBinariesAndSetDYLD(), and ProcessMachCore::LoadBinariesViaMetadata().
GetStepThroughTrampolinePlan()
ThreadPlanSP DynamicLoaderDarwinKernel::GetStepThroughTrampolinePlan (lldb_private::Thread & thread, bool stop_others) override virtual
Provides a plan to step through the dynamic loader trampoline for the current state of thread.
Parameters
[in] stop_others Whether the plan should be set to stop other threads.
Returns
A pointer to the plan (caller owned) or NULL if we are not at such a trampoline.
Implements lldb_private::DynamicLoader.
Definition at line 1617 of file DynamicLoaderDarwinKernel.cpp.
References lldb_private::GetLog(), LLDB_LOGF, and lldb_private::Step.
Initialize()
void DynamicLoaderDarwinKernel::Initialize () static
Definition at line 1632 of file DynamicLoaderDarwinKernel.cpp.
References CreateInstance(), DebuggerInitialize(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
LoadKernelModuleIfNeeded()
void DynamicLoaderDarwinKernel::LoadKernelModuleIfNeeded () protected
Definition at line 1047 of file DynamicLoaderDarwinKernel.cpp.
References lldb_private::AddressableBits::AddressableBitToMask(), lldb_private::ConstString::AsCString(), error(), lldb::eSymbolTypeAny, lldb::eSymbolTypeData, lldb_private::Symbol::GetAddress(), lldb_private::ObjectFile::GetBaseAddress(), lldb_private::Address::GetFileAddress(), lldb_private::Address::GetLoadAddress(), is_kernel(), LLDB_INVALID_ADDRESS, lldb_private::DynamicLoader::LoadOperatingSystemPlugin(), m_kernel, m_kernel_load_address, m_kext_summary_header_ptr_addr, lldb_private::DynamicLoader::m_process, and ReadAllKextSummaries().
Referenced by UpdateIfNeeded().
operator=()
const DynamicLoaderDarwinKernel & DynamicLoaderDarwinKernel::operator= (const DynamicLoaderDarwinKernel &) private delete
References DynamicLoaderDarwinKernel().
ParseKextSummaries()
bool DynamicLoaderDarwinKernel::ParseKextSummaries (const lldb_private::Address & kext_summary_addr, uint32_t count) protected
Definition at line 1267 of file DynamicLoaderDarwinKernel.cpp.
References lldb_private::ModuleList::AppendIfNeeded(), DynamicLoaderDarwinKernel::KextImageInfo::Clear(), lldb_private::DynamicLoader, GetGlobalProperties(), DynamicLoaderDarwinKernel::KextImageInfo::GetLoadAddress(), DynamicLoaderDarwinKernelProperties::GetLoadKexts(), lldb_private::GetLog(), DynamicLoaderDarwinKernel::KextImageInfo::GetModule(), GetName(), DynamicLoaderDarwinKernel::KextImageInfo::GetProcessStopId(), DynamicLoaderDarwinKernel::KextImageInfo::IsKernel(), LLDB_INVALID_ADDRESS, LLDB_LOGF, DynamicLoaderDarwinKernel::KextImageInfo::LoadImageAtFileAddress(), DynamicLoaderDarwinKernel::KextImageInfo::LoadImageUsingMemoryModule(), m_kernel, m_known_kexts, m_mutex, lldb_private::DynamicLoader::m_process, and ReadKextSummaries().
Referenced by ReadAllKextSummaries().
PrivateInitialize()
void DynamicLoaderDarwinKernel::PrivateInitialize (lldb_private::Process * process) protected
Definition at line 1556 of file DynamicLoaderDarwinKernel.cpp.
References Clear(), DEBUG_PRINTF, lldb_private::DynamicLoader::m_process, and lldb_private::StateAsCString().
Referenced by DidAttach(), and DidLaunch().
PrivateProcessStateChanged()
void DynamicLoaderDarwinKernel::PrivateProcessStateChanged (lldb_private::Process * process, lldb::StateType state) protected
Definition at line 1589 of file DynamicLoaderDarwinKernel.cpp.
References Clear(), DEBUG_PRINTF, lldb::eStateAttaching, lldb::eStateConnected, lldb::eStateCrashed, lldb::eStateDetached, lldb::eStateExited, lldb::eStateInvalid, lldb::eStateLaunching, lldb::eStateRunning, lldb::eStateStepping, lldb::eStateStopped, lldb::eStateSuspended, lldb::eStateUnloaded, lldb_private::StateAsCString(), and UpdateIfNeeded().
PutToLog()
void DynamicLoaderDarwinKernel::PutToLog (lldb_private::Log * log) const protected
Definition at line 1535 of file DynamicLoaderDarwinKernel.cpp.
References LLDB_LOGF, m_kext_summary_header, m_kext_summary_header_addr, m_known_kexts, m_mutex, lldb_private::Log::PutCString(), and PutToLog().
Referenced by BreakpointHit(), and PutToLog().
ReadAllKextSummaries()
bool DynamicLoaderDarwinKernel::ReadAllKextSummaries () protected
Definition at line 1504 of file DynamicLoaderDarwinKernel.cpp.
References m_kext_summary_header, m_kext_summary_header_addr, m_known_kexts, m_mutex, ParseKextSummaries(), ReadKextSummaryHeader(), and lldb_private::Address::Slide().
Referenced by BreakpointHit(), and LoadKernelModuleIfNeeded().
ReadKextSummaries()
uint32_t DynamicLoaderDarwinKernel::ReadKextSummaries (const lldb_private::Address & kext_summary_addr, uint32_t image_infos_count, KextImageInfo::collection & image_infos) protected
Definition at line 1461 of file DynamicLoaderDarwinKernel.cpp.
References error(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::DataBufferHeap::GetByteSize(), lldb_private::DataExtractor::GetData(), lldb_private::DataExtractor::GetU64(), KERNEL_MODULE_MAX_NAME, m_kernel, m_kext_summary_header, lldb_private::DynamicLoader::m_process, and lldb_private::DataExtractor::ValidOffsetForDataOfSize().
Referenced by ParseKextSummaries().
ReadKextSummaryHeader()
bool DynamicLoaderDarwinKernel::ReadKextSummaryHeader () protected
Definition at line 1183 of file DynamicLoaderDarwinKernel.cpp.
References error(), lldb_private::DataExtractor::GetU32(), KERNEL_MODULE_ENTRY_SIZE_VERSION_1, m_kernel, m_kext_summary_header, m_kext_summary_header_addr, m_kext_summary_header_ptr_addr, m_mutex, and lldb_private::DynamicLoader::m_process.
Referenced by ReadAllKextSummaries().
ReadMachHeader()
bool DynamicLoaderDarwinKernel::ReadMachHeader (lldb::addr_t addr, lldb_private::Process * process, llvm::MachO::mach_header & mh, bool * read_error = nullptr) static protected
Definition at line 397 of file DynamicLoaderDarwinKernel.cpp.
References error(), and lldb_private::Process::ReadMemory().
Referenced by CheckForKernelImageAtAddress(), and DynamicLoaderDarwinKernel::KextImageInfo::ReadMemoryModule().
RegisterNotificationCallbacks()
void DynamicLoaderDarwinKernel::RegisterNotificationCallbacks () protected
SearchForDarwinKernel()
lldb::addr_t DynamicLoaderDarwinKernel::SearchForDarwinKernel (lldb_private::Process * process) static
Definition at line 199 of file DynamicLoaderDarwinKernel.cpp.
References lldb_private::Process::GetImageInfoAddress(), LLDB_INVALID_ADDRESS, SearchForKernelAtSameLoadAddr(), SearchForKernelNearPC(), SearchForKernelViaExhaustiveSearch(), and SearchForKernelWithDebugHints().
Referenced by CreateInstance(), and ProcessMachCore::LoadBinariesViaExhaustiveSearch().
SearchForKernelAtSameLoadAddr()
lldb::addr_t DynamicLoaderDarwinKernel::SearchForKernelAtSameLoadAddr (lldb_private::Process * process) static protected
Definition at line 217 of file DynamicLoaderDarwinKernel.cpp.
References CheckForKernelImageAtAddress(), lldb_private::ObjectFile::GetBaseAddress(), lldb_private::Target::GetExecutableModulePointer(), lldb_private::Address::GetFileAddress(), lldb_private::Module::GetObjectFile(), lldb_private::Process::GetTarget(), lldb_private::Module::GetUUID(), is_kernel(), lldb_private::Address::IsValid(), and LLDB_INVALID_ADDRESS.
Referenced by SearchForDarwinKernel().
SearchForKernelNearPC()
lldb::addr_t DynamicLoaderDarwinKernel::SearchForKernelNearPC (lldb_private::Process * process) static protected
Definition at line 295 of file DynamicLoaderDarwinKernel.cpp.
References CheckForKernelImageAtAddress(), eKASLRScanLowgloAddresses, eKASLRScanNone, lldb_private::ArchSpec::GetAddressByteSize(), lldb_private::Target::GetArchitecture(), GetGlobalProperties(), lldb_private::ThreadList::GetSelectedThread(), lldb_private::Process::GetTarget(), lldb_private::Process::GetThreadList(), LLDB_INVALID_ADDRESS, and pc.
Referenced by SearchForDarwinKernel().
SearchForKernelViaExhaustiveSearch()
lldb::addr_t DynamicLoaderDarwinKernel::SearchForKernelViaExhaustiveSearch (lldb_private::Process * process) static protected
Definition at line 352 of file DynamicLoaderDarwinKernel.cpp.
References CheckForKernelImageAtAddress(), eKASLRScanExhaustiveScan, lldb_private::ArchSpec::GetAddressByteSize(), lldb_private::Target::GetArchitecture(), GetGlobalProperties(), lldb_private::Process::GetTarget(), LLDB_INVALID_ADDRESS, UINT32_MAX, and UINT64_MAX.
Referenced by SearchForDarwinKernel().
SearchForKernelWithDebugHints()
lldb::addr_t DynamicLoaderDarwinKernel::SearchForKernelWithDebugHints (lldb_private::Process * process) static protected
Definition at line 240 of file DynamicLoaderDarwinKernel.cpp.
References CheckForKernelImageAtAddress(), eKASLRScanNone, lldb_private::Process::GetAddressByteSize(), lldb_private::Process::GetByteOrder(), GetGlobalProperties(), lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU64(), LLDB_INVALID_ADDRESS, and lldb_private::Process::ReadMemoryFromInferior().
Referenced by SearchForDarwinKernel().
SetNotificationBreakpointIfNeeded()
void DynamicLoaderDarwinKernel::SetNotificationBreakpointIfNeeded () protected
Definition at line 1563 of file DynamicLoaderDarwinKernel.cpp.
References lldb_private::FileSpecList::Append(), BreakpointHitCallback(), DEBUG_PRINTF, lldb::eLanguageTypeUnknown, lldb_private::eLazyBoolNo, lldb_private::Stoppoint::GetID(), LLDB_INVALID_BREAK_ID, m_break_id, m_kernel, lldb_private::DynamicLoader::m_process, lldb_private::Breakpoint::SetCallback(), and lldb_private::StateAsCString().
Referenced by UpdateIfNeeded().
Terminate()
void DynamicLoaderDarwinKernel::Terminate () static
Definition at line 1638 of file DynamicLoaderDarwinKernel.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
UnregisterNotificationCallbacks()
void DynamicLoaderDarwinKernel::UnregisterNotificationCallbacks () protected
UpdateIfNeeded()
void DynamicLoaderDarwinKernel::UpdateIfNeeded () protected
Definition at line 536 of file DynamicLoaderDarwinKernel.cpp.
References LoadKernelModuleIfNeeded(), and SetNotificationBreakpointIfNeeded().
Referenced by DidAttach(), DidLaunch(), and PrivateProcessStateChanged().
UpdateImageInfosHeaderAndLoadCommands()
void DynamicLoaderDarwinKernel::UpdateImageInfosHeaderAndLoadCommands (KextImageInfo::collection & image_infos, uint32_t infos_count, bool update_executable) protected
Member Data Documentation
m_break_id
lldb::user_id_t DynamicLoaderDarwinKernel::m_break_id protected
Definition at line 292 of file DynamicLoaderDarwinKernel.h.
Referenced by Clear(), DynamicLoaderDarwinKernel(), and SetNotificationBreakpointIfNeeded().
m_kernel
KextImageInfo DynamicLoaderDarwinKernel::m_kernel protected
Definition at line 285 of file DynamicLoaderDarwinKernel.h.
Referenced by Clear(), DynamicLoaderDarwinKernel(), GetAddrByteSize(), LoadKernelModuleIfNeeded(), ParseKextSummaries(), ReadKextSummaries(), ReadKextSummaryHeader(), and SetNotificationBreakpointIfNeeded().
m_kernel_load_address
lldb::addr_t DynamicLoaderDarwinKernel::m_kernel_load_address protected
Definition at line 284 of file DynamicLoaderDarwinKernel.h.
Referenced by DynamicLoaderDarwinKernel(), and LoadKernelModuleIfNeeded().
m_kext_summary_header
OSKextLoadedKextSummaryHeader DynamicLoaderDarwinKernel::m_kext_summary_header protected
Definition at line 289 of file DynamicLoaderDarwinKernel.h.
Referenced by DynamicLoaderDarwinKernel(), PutToLog(), ReadAllKextSummaries(), ReadKextSummaries(), and ReadKextSummaryHeader().
m_kext_summary_header_addr
lldb_private::Address DynamicLoaderDarwinKernel::m_kext_summary_header_addr protected
Definition at line 288 of file DynamicLoaderDarwinKernel.h.
Referenced by Clear(), DynamicLoaderDarwinKernel(), PutToLog(), ReadAllKextSummaries(), and ReadKextSummaryHeader().
m_kext_summary_header_ptr_addr
lldb_private::Address DynamicLoaderDarwinKernel::m_kext_summary_header_ptr_addr protected
Definition at line 287 of file DynamicLoaderDarwinKernel.h.
Referenced by Clear(), DynamicLoaderDarwinKernel(), LoadKernelModuleIfNeeded(), and ReadKextSummaryHeader().
m_known_kexts
KextImageInfo::collection DynamicLoaderDarwinKernel::m_known_kexts protected
Definition at line 290 of file DynamicLoaderDarwinKernel.h.
Referenced by Clear(), DynamicLoaderDarwinKernel(), ParseKextSummaries(), PutToLog(), and ReadAllKextSummaries().
m_mutex
std::recursive_mutex DynamicLoaderDarwinKernel::m_mutex mutable protected
Definition at line 291 of file DynamicLoaderDarwinKernel.h.
Referenced by Clear(), DynamicLoaderDarwinKernel(), ParseKextSummaries(), PutToLog(), ReadAllKextSummaries(), and ReadKextSummaryHeader().
The documentation for this class was generated from the following files:
DynamicLoaderDarwinKernel.h
DynamicLoaderDarwinKernel.cpp