LLDB: lldb_protocol::mcp::Server Class Reference
lldb_protocol::mcp::Server Class Reference
#include <Server.h>
Classes
struct Client
Public Member Functions
Server (std::string name, std::string version, LogCallback log_callback={})
~Server ()=default
void AddTool (std::unique_ptr< Tool > tool)
void AddResourceProvider (std::unique_ptr< ResourceProvider > resource_provider)
llvm::Error Accept (MCPTransportUP)
Protected Member Functions
MCPBinderUP Bind (MCPTransport &)
ServerCapabilities GetCapabilities ()
llvm::Expected< InitializeResult > InitializeHandler (const InitializeParams &)
llvm::Expected< ListToolsResult > ToolsListHandler ()
llvm::Expected< CallToolResult > ToolsCallHandler (const CallToolParams &)
llvm::Expected< ListResourcesResult > ResourcesListHandler ()
llvm::Expected< ReadResourceResult > ResourcesReadHandler (const ReadResourceParams &)
template<typename... Ts>
auto Logv (const char *Fmt, Ts &&...Vals)
void Log (llvm::StringRef message)
Private Types
using MCPTransportUP = std::unique_ptr<lldb_protocol::mcp::MCPTransport>
using ReadHandleUP = lldb_private::MainLoop::ReadHandleUP
Private Attributes
const std::string m_name
const std::string m_version
LogCallback m_log_callback
std::map< MCPTransport *, Client > m_instances
llvm::StringMap< std::unique_ptr< Tool > > m_tools
std::vector< std::unique_ptr< ResourceProvider > > m_resource_providers
Detailed Description
Definition at line 31 of file Server.h.
Member Typedef Documentation
MCPTransportUP
using lldb_protocol::mcp::Server::MCPTransportUP = std::unique_ptr<lldb_protocol::mcp::MCPTransport> private
Definition at line 33 of file Server.h.
ReadHandleUP
using lldb_protocol::mcp::Server::ReadHandleUP = lldb_private::MainLoop::ReadHandleUP private
Definition at line 35 of file Server.h.
Constructor & Destructor Documentation
Server()
Server::Server (std::string name, std::string version, LogCallback log_callback = {})
Definition at line 113 of file Server.cpp.
References m_log_callback, m_name, and m_version.
~Server()
lldb_protocol::mcp::Server::~Server () default
Member Function Documentation
Accept()
llvm::Error Server::Accept (MCPTransportUP transport)
Definition at line 147 of file Server.cpp.
References Bind(), Logv(), and m_instances.
AddResourceProvider()
void Server::AddResourceProvider (std::unique_ptr< ResourceProvider > resource_provider)
Definition at line 123 of file Server.cpp.
References m_resource_providers.
Referenced by lldb_private::mcp::ProtocolServerMCP::Extend().
AddTool()
void Server::AddTool (std::unique_ptr< Tool > tool)
Definition at line 117 of file Server.cpp.
References m_tools.
Referenced by lldb_private::mcp::ProtocolServerMCP::Extend().
Bind()
MCPBinderUP Server::Bind (MCPTransport & transport) protected
Definition at line 130 of file Server.cpp.
References InitializeHandler(), Log(), ResourcesListHandler(), ResourcesReadHandler(), ToolsCallHandler(), and ToolsListHandler().
Referenced by Accept().
GetCapabilities()
ServerCapabilities Server::GetCapabilities () protected
Definition at line 240 of file Server.cpp.
References lldb_protocol::mcp::ServerCapabilities::supportsResourcesList, lldb_protocol::mcp::ServerCapabilities::supportsResourcesSubscribe, and lldb_protocol::mcp::ServerCapabilities::supportsToolsList.
Referenced by InitializeHandler().
InitializeHandler()
Expected< InitializeResult > Server::InitializeHandler (const InitializeParams & request) protected
Definition at line 167 of file Server.cpp.
References lldb_protocol::mcp::InitializeResult::capabilities, GetCapabilities(), lldb_protocol::mcp::kProtocolVersion, m_name, m_version, lldb_protocol::mcp::Implementation::name, lldb_protocol::mcp::InitializeResult::protocolVersion, lldb_protocol::mcp::InitializeResult::serverInfo, and lldb_protocol::mcp::Implementation::version.
Referenced by Bind().
Log()
void lldb_protocol::mcp::Server::Log (llvm::StringRef message) inline protected
Definition at line 63 of file Server.h.
References m_log_callback.
Referenced by Bind(), and Logv().
Logv()
template<typename... Ts> auto lldb_protocol::mcp::Server::Logv (const char * Fmt, Ts &&... Vals) inline protected
Definition at line 60 of file Server.h.
References Log().
Referenced by Accept().
ResourcesListHandler()
llvm::Expected< ListResourcesResult > Server::ResourcesListHandler () protected
Definition at line 205 of file Server.cpp.
References m_resource_providers, and lldb_protocol::mcp::ListResourcesResult::resources.
Referenced by Bind().
ResourcesReadHandler()
Expected< ReadResourceResult > Server::ResourcesReadHandler (const ReadResourceParams & params) protected
Definition at line 216 of file Server.cpp.
References createStringError(), lldb_protocol::mcp::MCPError::kResourceNotFound, m_resource_providers, and lldb_protocol::mcp::ReadResourceParams::uri.
Referenced by Bind().
ToolsCallHandler()
llvm::Expected< CallToolResult > Server::ToolsCallHandler (const CallToolParams & params) protected
Definition at line 185 of file Server.cpp.
References lldb_protocol::mcp::CallToolParams::arguments, m_tools, and lldb_protocol::mcp::CallToolParams::name.
Referenced by Bind().
ToolsListHandler()
llvm::Expected< ListToolsResult > Server::ToolsListHandler () protected
Definition at line 176 of file Server.cpp.
References m_tools, and lldb_protocol::mcp::ListToolsResult::tools.
Referenced by Bind().
Member Data Documentation
m_instances
std::map<MCPTransport *, Client> lldb_protocol::mcp::Server::m_instances private
Definition at line 77 of file Server.h.
Referenced by Accept().
m_log_callback
LogCallback lldb_protocol::mcp::Server::m_log_callback private
Definition at line 72 of file Server.h.
Referenced by Log(), and Server().
m_name
const std::string lldb_protocol::mcp::Server::m_name private
Definition at line 69 of file Server.h.
Referenced by InitializeHandler(), and Server().
m_resource_providers
std::vector<std::unique_ptr<ResourceProvider> > lldb_protocol::mcp::Server::m_resource_providers private
Definition at line 80 of file Server.h.
Referenced by AddResourceProvider(), ResourcesListHandler(), and ResourcesReadHandler().
m_tools
llvm::StringMap<std::unique_ptr<Tool> > lldb_protocol::mcp::Server::m_tools private
Definition at line 79 of file Server.h.
Referenced by AddTool(), ToolsCallHandler(), and ToolsListHandler().
m_version
const std::string lldb_protocol::mcp::Server::m_version private
Definition at line 70 of file Server.h.
Referenced by InitializeHandler(), and Server().
The documentation for this class was generated from the following files:
Server.h
Server.cpp