LLDB: lldb::SBBreakpointCallbackBaton Class Reference
lldb::SBBreakpointCallbackBaton Class Reference
#include <SBBreakpointOptionCommon.h>
Public Member Functions
SBBreakpointCallbackBaton (SBBreakpointHitCallback callback, void *baton)
~SBBreakpointCallbackBaton () override
Public Member Functions inherited from lldb_private::TypedBaton< CallbackData >
TypedBaton (std::unique_ptr< CallbackData > Item)
CallbackData * getItem ()
void * data () override
void GetDescription (llvm::raw_ostream &s, lldb::DescriptionLevel level, unsigned indentation) const override
Public Member Functions inherited from lldb_private::Baton
Baton ()=default
virtual ~Baton ()=default
Static Public Member Functions
static bool PrivateBreakpointHitCallback (void *baton, lldb_private::StoppointCallbackContext *ctx, lldb::user_id_t break_id, lldb::user_id_t break_loc_id)
Additional Inherited Members
Protected Attributes inherited from lldb_private::TypedBaton< CallbackData >
std::unique_ptr< CallbackData > Item
Detailed Description
Definition at line 22 of file SBBreakpointOptionCommon.h.
Constructor & Destructor Documentation
SBBreakpointCallbackBaton()
SBBreakpointCallbackBaton::SBBreakpointCallbackBaton (SBBreakpointHitCallback callback, void * baton)
Definition at line 41 of file SBBreakpointOptionCommon.cpp.
References lldb::CallbackData::callback, lldb::CallbackData::callback_baton, lldb_private::TypedBaton< CallbackData >::getItem(), LLDB_INSTRUMENT_VA, and lldb_private::TypedBaton< CallbackData >::TypedBaton().
~SBBreakpointCallbackBaton()
SBBreakpointCallbackBaton::~SBBreakpointCallbackBaton () override default
Member Function Documentation
PrivateBreakpointHitCallback()
bool SBBreakpointCallbackBaton::PrivateBreakpointHitCallback (void * baton, lldb_private::StoppointCallbackContext * ctx, lldb::user_id_t break_id, lldb::user_id_t break_loc_id) static
Definition at line 49 of file SBBreakpointOptionCommon.cpp.
References lldb_private::TypedBaton< CallbackData >::data(), lldb_private::StoppointCallbackContext::exe_ctx_ref, lldb_private::BreakpointList::FindBreakpointByID(), lldb_private::Target::GetBreakpointList(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::ExecutionContext::GetTargetRef(), lldb_private::ExecutionContext::GetThreadPtr(), LLDB_INSTRUMENT_VA, lldb::SBBreakpointLocation::SetLocation(), and lldb::SBThread::SetThread().
Referenced by lldb::SBBreakpointLocation::SetCallback().
The documentation for this class was generated from the following files:
SBBreakpointOptionCommon.h
SBBreakpointOptionCommon.cpp