LLDB: lldb_private::ThreadPlanTracer Class Reference
lldb_private::ThreadPlanTracer Class Reference
#include <ThreadPlanTracer.h>
Public Types
enum ThreadPlanTracerStyle { eLocation = 0 , eStateChange , eCheckFrames , ePython }
Public Member Functions
ThreadPlanTracer (Thread &thread, lldb::StreamSP &stream_sp)
ThreadPlanTracer (Thread &thread)
virtual ~ThreadPlanTracer ()=default
virtual void TracingStarted ()
virtual void TracingEnded ()
bool EnableTracing (bool value)
bool TracingEnabled ()
Thread & GetThread ()
Protected Member Functions
lldb::StreamSP GetLogStreamSP ()
virtual void Log ()
Protected Attributes
Process & m_process
lldb::tid_t m_tid
Private Member Functions
bool TracerExplainsStop ()
Private Attributes
bool m_enabled
lldb::StreamSP m_stream_sp
Thread * m_thread
Friends
class ThreadPlan
Detailed Description
Definition at line 20 of file ThreadPlanTracer.h.
Member Enumeration Documentation
ThreadPlanTracerStyle
enum lldb_private::ThreadPlanTracer::ThreadPlanTracerStyle
Enumerator
eLocation
eStateChange
eCheckFrames
ePython
Definition at line 24 of file ThreadPlanTracer.h.
Constructor & Destructor Documentation
ThreadPlanTracer() [1/2]
ThreadPlanTracer::ThreadPlanTracer (Thread & thread, lldb::StreamSP & stream_sp)
Definition at line 37 of file ThreadPlanTracer.cpp.
References m_enabled, m_process, m_stream_sp, m_thread, and m_tid.
Referenced by lldb_private::ThreadPlanAssemblyTracer::ThreadPlanAssemblyTracer(), and lldb_private::ThreadPlanAssemblyTracer::ThreadPlanAssemblyTracer().
ThreadPlanTracer() [2/2]
ThreadPlanTracer::ThreadPlanTracer (Thread & thread)
Definition at line 41 of file ThreadPlanTracer.cpp.
References m_enabled, m_process, m_stream_sp, m_thread, and m_tid.
~ThreadPlanTracer()
virtual lldb_private::ThreadPlanTracer::~ThreadPlanTracer () virtual default
Member Function Documentation
EnableTracing()
bool lldb_private::ThreadPlanTracer::EnableTracing (bool value) inline
Definition at line 40 of file ThreadPlanTracer.h.
References m_enabled, TracingEnded(), and TracingStarted().
GetLogStreamSP()
StreamSP ThreadPlanTracer::GetLogStreamSP () protected
Definition at line 45 of file ThreadPlanTracer.cpp.
References GetThread(), and m_stream_sp.
Referenced by lldb_private::ThreadPlanAssemblyTracer::Log(), and Log().
GetThread()
Thread & ThreadPlanTracer::GetThread ()
Definition at line 56 of file ThreadPlanTracer.cpp.
References m_process, m_thread, and m_tid.
Referenced by GetLogStreamSP(), lldb_private::ThreadPlanAssemblyTracer::Log(), Log(), and TracerExplainsStop().
Log()
void ThreadPlanTracer::Log () protected virtual
Reimplemented in lldb_private::ThreadPlanAssemblyTracer.
Definition at line 64 of file ThreadPlanTracer.cpp.
References GetLogStreamSP(), lldb_private::Thread::GetStackFrameAtIndex(), and GetThread().
TracerExplainsStop()
bool ThreadPlanTracer::TracerExplainsStop () private
Definition at line 77 of file ThreadPlanTracer.cpp.
References lldb::eStopReasonTrace, lldb_private::Thread::GetStopInfo(), GetThread(), and m_enabled.
TracingEnabled()
bool lldb_private::ThreadPlanTracer::TracingEnabled () inline
Definition at line 51 of file ThreadPlanTracer.h.
References m_enabled.
TracingEnded()
virtual void lldb_private::ThreadPlanTracer::TracingEnded () inline virtual
Reimplemented in lldb_private::ThreadPlanAssemblyTracer.
Definition at line 38 of file ThreadPlanTracer.h.
Referenced by EnableTracing().
TracingStarted()
virtual void lldb_private::ThreadPlanTracer::TracingStarted () inline virtual
Reimplemented in lldb_private::ThreadPlanAssemblyTracer.
Definition at line 36 of file ThreadPlanTracer.h.
Referenced by EnableTracing().
Friends And Related Symbol Documentation
ThreadPlan
friend class ThreadPlan friend
Definition at line 21 of file ThreadPlanTracer.h.
References ThreadPlan.
Referenced by ThreadPlan.
Member Data Documentation
m_enabled
bool lldb_private::ThreadPlanTracer::m_enabled private
Definition at line 66 of file ThreadPlanTracer.h.
Referenced by EnableTracing(), ThreadPlanTracer(), ThreadPlanTracer(), TracerExplainsStop(), and TracingEnabled().
m_process
Process& lldb_private::ThreadPlanTracer::m_process protected
Definition at line 56 of file ThreadPlanTracer.h.
Referenced by lldb_private::ThreadPlanAssemblyTracer::GetDisassembler(), lldb_private::ThreadPlanAssemblyTracer::GetIntPointerType(), GetThread(), lldb_private::ThreadPlanAssemblyTracer::Log(), ThreadPlanTracer(), and ThreadPlanTracer().
m_stream_sp
lldb::StreamSP lldb_private::ThreadPlanTracer::m_stream_sp private
Definition at line 67 of file ThreadPlanTracer.h.
Referenced by GetLogStreamSP(), ThreadPlanTracer(), and ThreadPlanTracer().
m_thread
Thread* lldb_private::ThreadPlanTracer::m_thread private
Definition at line 68 of file ThreadPlanTracer.h.
Referenced by GetThread(), ThreadPlanTracer(), and ThreadPlanTracer().
m_tid
lldb::tid_t lldb_private::ThreadPlanTracer::m_tid protected
Definition at line 57 of file ThreadPlanTracer.h.
Referenced by GetThread(), ThreadPlanTracer(), and ThreadPlanTracer().
The documentation for this class was generated from the following files:
ThreadPlanTracer.h
ThreadPlanTracer.cpp