LLDB: lldb_private::FileLineResolver Class Reference
lldb_private::FileLineResolver Class Reference
This class finds address for source file and line.
#include "lldb/Core/FileLineResolver.h"
Public Member Functions
FileLineResolver ()
FileLineResolver (const FileSpec &resolver, uint32_t line_no, bool check_inlines)
~FileLineResolver () override
Searcher::CallbackReturn SearchCallback (SearchFilter &filter, SymbolContext &context, Address *addr) override
lldb::SearchDepth GetDepth () override
void GetDescription (Stream *s) override
Prints a canonical description for the searcher to the stream s.
const SymbolContextList & GetFileLineMatches ()
void Clear ()
void Reset (const FileSpec &file_spec, uint32_t line, bool check_inlines)
Public Member Functions inherited from lldb_private::Searcher
Searcher ()
virtual ~Searcher ()
Protected Attributes
FileSpec m_file_spec
uint32_t m_line_number
SymbolContextList m_sc_list
bool m_inlines = true
Private Member Functions
FileLineResolver (const FileLineResolver &)=delete
const FileLineResolver & operator= (const FileLineResolver &)=delete
Additional Inherited Members
Public Types inherited from lldb_private::Searcher
enum CallbackReturn { eCallbackReturnStop = 0 , eCallbackReturnContinue , eCallbackReturnPop }
Detailed Description
This class finds address for source file and line.
Optionally, it will look for inlined instances of the file and line specification.
Definition at line 27 of file FileLineResolver.h.
Constructor & Destructor Documentation
FileLineResolver() [1/3]
lldb_private::FileLineResolver::FileLineResolver () inline
Definition at line 29 of file FileLineResolver.h.
References m_file_spec, and m_sc_list.
Referenced by FileLineResolver(), and operator=().
FileLineResolver() [2/3]
FileLineResolver::FileLineResolver (const FileSpec & resolver, uint32_t line_no, bool check_inlines)
Definition at line 27 of file FileLineResolver.cpp.
References m_file_spec, m_inlines, m_line_number, and lldb_private::Searcher::Searcher().
~FileLineResolver()
FileLineResolver::~FileLineResolver () override default
FileLineResolver() [3/3]
lldb_private::FileLineResolver::FileLineResolver (const FileLineResolver &) private delete
References FileLineResolver().
Member Function Documentation
Clear()
void FileLineResolver::Clear ()
Definition at line 76 of file FileLineResolver.cpp.
References m_file_spec, m_inlines, m_line_number, m_sc_list, and UINT32_MAX.
GetDepth()
lldb::SearchDepth FileLineResolver::GetDepth () override virtual
Implements lldb_private::Searcher.
Definition at line 67 of file FileLineResolver.cpp.
References lldb::eSearchDepthCompUnit.
GetDescription()
void FileLineResolver::GetDescription (Stream * s) override virtual
Prints a canonical description for the searcher to the stream s.
Parameters
[in] s Stream to which the output is copied.
Reimplemented from lldb_private::Searcher.
Definition at line 71 of file FileLineResolver.cpp.
References m_file_spec, m_line_number, and lldb_private::Stream::Printf().
GetFileLineMatches()
const SymbolContextList & lldb_private::FileLineResolver::GetFileLineMatches () inline
Definition at line 47 of file FileLineResolver.h.
References m_sc_list.
operator=()
const FileLineResolver & lldb_private::FileLineResolver::operator= (const FileLineResolver &) private delete
References FileLineResolver().
Reset()
void FileLineResolver::Reset (const FileSpec & file_spec, uint32_t line, bool check_inlines)
Definition at line 83 of file FileLineResolver.cpp.
References m_file_spec, m_inlines, m_line_number, and m_sc_list.
SearchCallback()
Searcher::CallbackReturn FileLineResolver::SearchCallback (SearchFilter & filter, SymbolContext & context, Address * addr) override virtual
Implements lldb_private::Searcher.
Definition at line 35 of file FileLineResolver.cpp.
References lldb_private::SymbolContext::comp_unit, lldb_private::Searcher::eCallbackReturnContinue, lldb_private::SupportFileList::FindFileIndex(), lldb_private::LineTable::FindLineEntriesForFileIndex(), lldb_private::CompileUnit::GetLineTable(), lldb_private::CompileUnit::GetPrimaryFile(), lldb_private::CompileUnit::GetSupportFiles(), m_file_spec, m_inlines, m_line_number, m_sc_list, and UINT32_MAX.
Member Data Documentation
m_file_spec
FileSpec lldb_private::FileLineResolver::m_file_spec protected
Definition at line 54 of file FileLineResolver.h.
Referenced by Clear(), FileLineResolver(), FileLineResolver(), GetDescription(), Reset(), and SearchCallback().
m_inlines
bool lldb_private::FileLineResolver::m_inlines = true protected
Definition at line 58 of file FileLineResolver.h.
Referenced by Clear(), FileLineResolver(), Reset(), and SearchCallback().
m_line_number
uint32_t lldb_private::FileLineResolver::m_line_number protected
Initial value:
=
      UINT32_MAX
Definition at line 55 of file FileLineResolver.h.
Referenced by Clear(), FileLineResolver(), GetDescription(), Reset(), and SearchCallback().
m_sc_list
SymbolContextList lldb_private::FileLineResolver::m_sc_list protected
Definition at line 57 of file FileLineResolver.h.
Referenced by Clear(), FileLineResolver(), GetFileLineMatches(), Reset(), and SearchCallback().
The documentation for this class was generated from the following files:
FileLineResolver.h
FileLineResolver.cpp