LLDB: lldb_private::BroadcastEventSpec Class Reference
lldb_private::BroadcastEventSpec Class Reference
lldb::BroadcastEventSpec
#include <Broadcaster.h>
Public Member Functions
BroadcastEventSpec (llvm::StringRef broadcaster_class, uint32_t event_bits)
~BroadcastEventSpec ()=default
const std::string & GetBroadcasterClass () const
uint32_t GetEventBits () const
bool IsContainedIn (const BroadcastEventSpec &in_spec) const
Tell whether this BroadcastEventSpec is contained in in_spec.
bool operator< (const BroadcastEventSpec &rhs) const
Private Attributes
std::string m_broadcaster_class
uint32_t m_event_bits
Detailed Description
lldb::BroadcastEventSpec
This class is used to specify a kind of event to register for. The Debugger maintains a list of BroadcastEventSpec's and when it is made
Definition at line 40 of file Broadcaster.h.
Constructor & Destructor Documentation
BroadcastEventSpec()
lldb_private::BroadcastEventSpec::BroadcastEventSpec (llvm::StringRef broadcaster_class, uint32_t event_bits) inline
Definition at line 42 of file Broadcaster.h.
References m_broadcaster_class, and m_event_bits.
Referenced by IsContainedIn(), and operator<().
~BroadcastEventSpec()
lldb_private::BroadcastEventSpec::~BroadcastEventSpec () default
Member Function Documentation
GetBroadcasterClass()
const std::string & lldb_private::BroadcastEventSpec::GetBroadcasterClass () const inline
Definition at line 47 of file Broadcaster.h.
References m_broadcaster_class.
Referenced by IsContainedIn(), operator<(), lldb_private::BroadcasterManager::RegisterListenerForEventsNoLock(), and lldb_private::BroadcasterManager::UnregisterListenerForEventsNoLock().
GetEventBits()
uint32_t lldb_private::BroadcastEventSpec::GetEventBits () const inline
Definition at line 49 of file Broadcaster.h.
References m_event_bits.
Referenced by IsContainedIn(), operator<(), lldb_private::BroadcasterManager::RegisterListenerForEventsNoLock(), and lldb_private::BroadcasterManager::UnregisterListenerForEventsNoLock().
IsContainedIn()
bool lldb_private::BroadcastEventSpec::IsContainedIn (const BroadcastEventSpec & in_spec) const inline
Tell whether this BroadcastEventSpec is contained in in_spec.
That is: (a) the two spec's share the same broadcaster class (b) the event bits of this spec are wholly contained in those of in_spec.
Definition at line 54 of file Broadcaster.h.
References BroadcastEventSpec(), GetBroadcasterClass(), GetEventBits(), m_broadcaster_class, and m_event_bits.
operator<()
bool BroadcastEventSpec::operator< (const BroadcastEventSpec & rhs) const
Definition at line 381 of file Broadcaster.cpp.
References BroadcastEventSpec(), lldb_private::Broadcaster::GetBroadcasterClass(), GetBroadcasterClass(), and GetEventBits().
Member Data Documentation
m_broadcaster_class
std::string lldb_private::BroadcastEventSpec::m_broadcaster_class private
Definition at line 70 of file Broadcaster.h.
Referenced by BroadcastEventSpec(), GetBroadcasterClass(), and IsContainedIn().
m_event_bits
uint32_t lldb_private::BroadcastEventSpec::m_event_bits private
Definition at line 71 of file Broadcaster.h.
Referenced by BroadcastEventSpec(), GetEventBits(), and IsContainedIn().
The documentation for this class was generated from the following files:
Broadcaster.h
Broadcaster.cpp