LLDB: ABIMacOSX_arm Class Reference
ABIMacOSX_arm Class Reference
#include <ABIMacOSX_arm.h>
Public Member Functions
~ABIMacOSX_arm () override=default
size_t GetRedZoneSize () const override
bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t func_addr, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override
bool GetArgumentValues (lldb_private::Thread &thread, lldb_private::ValueList &values) const override
lldb_private::Status SetReturnValueObject (lldb::StackFrameSP &frame_sp, lldb::ValueObjectSP &new_value) override
lldb::UnwindPlanSP CreateFunctionEntryUnwindPlan () override
lldb::UnwindPlanSP CreateDefaultUnwindPlan () override
bool RegisterIsVolatile (const lldb_private::RegisterInfo *reg_info) override
bool CallFrameAddressIsValid (lldb::addr_t cfa) override
bool CodeAddressIsValid (lldb::addr_t pc) override
lldb::addr_t FixCodeAddress (lldb::addr_t pc) override
Some targets might use bits in a code address to indicate a mode switch.
const lldb_private::RegisterInfo * GetRegisterInfoArray (uint32_t &count) override
bool IsArmv7kProcess () const
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::RegInfoBasedABI
void AugmentRegisterInfo (std::vector< DynamicRegisterInfo::Register > &regs) override
Public Member Functions inherited from lldb_private::ABI
~ABI () override
virtual bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::Type &prototype, llvm::ArrayRef< CallArgument > args) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, CompilerType &type, bool persistent=true) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, llvm::Type &type, bool persistent=true) const
virtual bool GetFallbackRegisterLocation (const RegisterInfo *reg_info, UnwindPlan::Row::AbstractRegisterLocation &unwind_regloc)
virtual lldb::addr_t FixAnyAddress (lldb::addr_t pc)
Use this method when you do not know, or do not care what kind of address you are fixing.
llvm::MCRegisterInfo & GetMCRegisterInfo ()
virtual bool GetPointerReturnRegister (const char *&name)
virtual uint64_t GetStackFrameSize ()
virtual lldb::addr_t FixDataAddress (lldb::addr_t pc)
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static lldb::ABISP CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec &arch)
static llvm::StringRef GetPluginNameStatic ()
Static Public Member Functions inherited from lldb_private::ABI
static lldb::ABISP FindPlugin (lldb::ProcessSP process_sp, const ArchSpec &arch)
Protected Member Functions
lldb::ValueObjectSP GetReturnValueObjectImpl (lldb_private::Thread &thread, lldb_private::CompilerType &ast_type) const override
Protected Member Functions inherited from lldb_private::RegInfoBasedABI
bool GetRegisterInfoByName (llvm::StringRef name, RegisterInfo &info)
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Protected Member Functions inherited from lldb_private::ABI
virtual lldb::ValueObjectSP GetReturnValueObjectImpl (Thread &thread, llvm::Type &ir_type) const
lldb::ProcessSP GetProcessSP () const
Request to get a Process shared pointer.
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Additional Inherited Members
Static Protected Member Functions inherited from lldb_private::ABI
static std::unique_ptr< llvm::MCRegisterInfo > MakeMCRegisterInfo (const ArchSpec &arch)
Utility function to construct a MCRegisterInfo using the ArchSpec triple.
Protected Attributes inherited from lldb_private::ABI
lldb::ProcessWP m_process_wp
std::unique_ptr< llvm::MCRegisterInfo > m_mc_register_info_up
Detailed Description
Definition at line 15 of file ABIMacOSX_arm.h.
Constructor & Destructor Documentation
~ABIMacOSX_arm()
ABIMacOSX_arm::~ABIMacOSX_arm () override default
References sp.
Member Function Documentation
CallFrameAddressIsValid()
bool ABIMacOSX_arm::CallFrameAddressIsValid (lldb::addr_t cfa) inline override virtual
Implements lldb_private::ABI.
Definition at line 38 of file ABIMacOSX_arm.h.
CodeAddressIsValid()
bool ABIMacOSX_arm::CodeAddressIsValid (lldb::addr_t pc) inline override virtual
Implements lldb_private::ABI.
Definition at line 47 of file ABIMacOSX_arm.h.
References pc, and UINT32_MAX.
CreateDefaultUnwindPlan()
UnwindPlanSP ABIMacOSX_arm::CreateDefaultUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 1797 of file ABIMacOSX_arm.cpp.
References dwarf_pc, dwarf_r7, lldb_private::eLazyBoolNo, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), lldb_private::UnwindPlan::Row::SetRegisterLocationToAtCFAPlusOffset(), and lldb_private::UnwindPlan::Row::SetUnspecifiedRegistersAreUndefined().
CreateFunctionEntryUnwindPlan()
UnwindPlanSP ABIMacOSX_arm::CreateFunctionEntryUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 1777 of file ABIMacOSX_arm.cpp.
References dwarf_lr, dwarf_pc, dwarf_sp, lldb_private::eLazyBoolNo, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), and lldb_private::UnwindPlan::Row::SetRegisterLocationToRegister().
CreateInstance()
ABISP ABIMacOSX_arm::CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec & arch) static
Definition at line 1301 of file ABIMacOSX_arm.cpp.
References lldb_private::ArchSpec::GetTriple(), and lldb_private::ABI::MakeMCRegisterInfo().
Referenced by Initialize(), and Terminate().
FixCodeAddress()
lldb::addr_t ABIMacOSX_arm::FixCodeAddress (lldb::addr_t pc) inline override virtual
Some targets might use bits in a code address to indicate a mode switch.
ARM uses bit zero to signify a code address is thumb, so any ARM ABI plug-ins would strip those bits.
Reimplemented from lldb_private::ABI.
Definition at line 54 of file ABIMacOSX_arm.h.
References pc.
GetArgumentValues()
bool ABIMacOSX_arm::GetArgumentValues (lldb_private::Thread & thread, lldb_private::ValueList & values) const override virtual
Implements lldb_private::ABI.
Definition at line 1422 of file ABIMacOSX_arm.cpp.
References lldb_private::RegisterContext::ConvertRegisterKindToRegisterNumber(), lldb::eRegisterKindGeneric, error(), lldb_private::Process::GetAddressByteSize(), lldb_private::CompilerType::GetBitSize(), lldb_private::Value::GetCompilerType(), lldb_private::ExecutionContext::GetProcessRef(), lldb_private::RegisterContext::GetRegisterInfoAtIndex(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::Value::GetScalar(), lldb_private::RegisterValue::GetScalarValue(), lldb_private::ValueList::GetSize(), lldb_private::RegisterContext::GetSP(), lldb_private::ValueList::GetValueAtIndex(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), lldb_private::CompilerType::IsPointerOrReferenceType(), LLDB_INVALID_REGNUM, LLDB_REGNUM_GENERIC_ARG1, lldb_private::RegisterContext::ReadRegister(), lldb_private::Process::ReadScalarIntegerFromMemory(), lldb_private::RegisterValue::SignExtend(), and sp.
GetPluginName()
llvm::StringRef ABIMacOSX_arm::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 77 of file ABIMacOSX_arm.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef ABIMacOSX_arm::GetPluginNameStatic () inline static
Definition at line 73 of file ABIMacOSX_arm.h.
Referenced by GetPluginName(), and Initialize().
GetRedZoneSize()
size_t ABIMacOSX_arm::GetRedZoneSize () const override virtual
Implements lldb_private::ABI.
Definition at line 1296 of file ABIMacOSX_arm.cpp.
GetRegisterInfoArray()
const lldb_private::RegisterInfo * ABIMacOSX_arm::GetRegisterInfoArray (uint32_t & count) override virtual
Implements lldb_private::RegInfoBasedABI.
Definition at line 1291 of file ABIMacOSX_arm.cpp.
References g_register_infos, and k_num_register_infos.
GetReturnValueObjectImpl()
ValueObjectSP ABIMacOSX_arm::GetReturnValueObjectImpl (lldb_private::Thread & thread, lldb_private::CompilerType & ast_type) const override protected virtual
Implements lldb_private::ABI.
Definition at line 1536 of file ABIMacOSX_arm.cpp.
References lldb_private::RegisterInfo::byte_size, lldb_private::ValueObjectConstResult::Create(), error(), lldb_private::RegisterValue::GetAsMemoryData(), lldb_private::CompilerType::GetBitSize(), lldb_private::CompilerType::GetByteSize(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::Value::GetScalar(), IsArmv7kProcess(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), lldb_private::CompilerType::IsPointerType(), lldb_private::RegisterContext::ReadRegister(), lldb_private::RegisterContext::ReadRegisterAsUnsigned(), lldb_private::Value::SetCompilerType(), and UINT32_MAX.
Initialize()
void ABIMacOSX_arm::Initialize () static
Definition at line 1999 of file ABIMacOSX_arm.cpp.
References CreateInstance(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Referenced by ABIARM::Initialize().
IsArmv7kProcess()
bool ABIMacOSX_arm::IsArmv7kProcess () const
Definition at line 1523 of file ABIMacOSX_arm.cpp.
References lldb_private::ArchSpec::eCore_arm_armv7k, lldb_private::ArchSpec::GetCore(), and lldb_private::ABI::GetProcessSP().
Referenced by GetReturnValueObjectImpl(), and SetReturnValueObject().
PrepareTrivialCall()
bool ABIMacOSX_arm::PrepareTrivialCall (lldb_private::Thread & thread, lldb::addr_t sp, lldb::addr_t func_addr, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override virtual
Implements lldb_private::ABI.
Definition at line 1316 of file ABIMacOSX_arm.cpp.
References lldb_private::RegisterInfo::byte_size, lldb_private::RegisterContext::ConvertRegisterKindToRegisterNumber(), lldb::eRegisterKindGeneric, lldb_private::Address::GetCallableLoadAddress(), lldb_private::RegisterContext::GetRegisterInfo(), lldb_private::RegisterContext::GetRegisterInfoByName(), LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_RA, LLDB_REGNUM_GENERIC_SP, MASK_CPSR_IT_MASK, MASK_CPSR_T, lldb_private::RegisterContext::ReadRegisterAsUnsigned(), lldb_private::Address::SetLoadAddress(), lldb_private::RegisterValue::SetUInt32(), sp, lldb_private::RegisterContext::WriteRegister(), and lldb_private::RegisterContext::WriteRegisterFromUnsigned().
RegisterIsVolatile()
bool ABIMacOSX_arm::RegisterIsVolatile (const lldb_private::RegisterInfo * reg_info) override virtual
Implements lldb_private::ABI.
Definition at line 1844 of file ABIMacOSX_arm.cpp.
References lldb_private::RegisterInfo::name.
SetReturnValueObject()
Status ABIMacOSX_arm::SetReturnValueObject (lldb::StackFrameSP & frame_sp, lldb::ValueObjectSP & new_value) override virtual
Implements lldb_private::ABI.
Definition at line 1681 of file ABIMacOSX_arm.cpp.
References lldb_private::Status::AsCString(), error(), lldb_private::Status::Fail(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataExtractor::GetMaxU32(), lldb_private::DataExtractor::GetMaxU64(), lldb_private::RegisterContext::GetRegisterInfoByName(), IsArmv7kProcess(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), lldb_private::CompilerType::IsPointerType(), and lldb_private::RegisterContext::WriteRegisterFromUnsigned().
Terminate()
void ABIMacOSX_arm::Terminate () static
Definition at line 2004 of file ABIMacOSX_arm.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Referenced by ABIARM::Terminate().
The documentation for this class was generated from the following files:
ABIMacOSX_arm.h
ABIMacOSX_arm.cpp