LLDB: lldb_private::SummaryStatistics Class Reference
lldb_private::SummaryStatistics Class Reference
A class that represents statistics about a TypeSummaryProviders invocations.
#include <Statistics.h>
Classes
class SummaryInvocation
Basic RAII class to increment the summary count when the call is complete.
Public Member Functions
SummaryStatistics (std::string name, std::string impl_type)
std::string GetName () const
double GetTotalTime () const
uint64_t GetSummaryCount () const
StatsDuration & GetDurationReference ()
std::string GetSummaryKindName () const
llvm::json::Value ToJSON () const
void Reset ()
Private Member Functions
void OnInvoked () noexcept
Private Attributes
lldb_private::StatsDuration m_total_time
const std::string m_impl_type
const std::string m_name
std::atomic< uint64_t > m_count
Detailed Description
A class that represents statistics about a TypeSummaryProviders invocations.
Note
All members of this class need to be accessed in a thread safe manner
Definition at line 234 of file Statistics.h.
Constructor & Destructor Documentation
SummaryStatistics()
lldb_private::SummaryStatistics::SummaryStatistics (std::string name, std::string impl_type) inline explicit
Definition at line 236 of file Statistics.h.
References m_count, m_impl_type, m_name, and m_total_time.
Member Function Documentation
GetDurationReference()
StatsDuration & lldb_private::SummaryStatistics::GetDurationReference () inline
Definition at line 247 of file Statistics.h.
References m_total_time.
Referenced by lldb_private::SummaryStatistics::SummaryInvocation::SummaryInvocation().
GetName()
std::string lldb_private::SummaryStatistics::GetName () const inline
Definition at line 240 of file Statistics.h.
References m_name.
Referenced by ToJSON().
GetSummaryCount()
uint64_t lldb_private::SummaryStatistics::GetSummaryCount () const inline
Definition at line 243 of file Statistics.h.
References m_count.
Referenced by ToJSON().
GetSummaryKindName()
std::string lldb_private::SummaryStatistics::GetSummaryKindName () const inline
Definition at line 249 of file Statistics.h.
References m_impl_type.
Referenced by ToJSON().
GetTotalTime()
double lldb_private::SummaryStatistics::GetTotalTime () const inline
Definition at line 241 of file Statistics.h.
References m_total_time.
Referenced by ToJSON().
OnInvoked()
void lldb_private::SummaryStatistics::OnInvoked () inline private noexcept
Definition at line 276 of file Statistics.h.
References m_count.
Reset()
void lldb_private::SummaryStatistics::Reset () inline
Definition at line 253 of file Statistics.h.
References m_total_time.
ToJSON()
llvm::json::Value SummaryStatistics::ToJSON () const
Definition at line 520 of file Statistics.cpp.
References GetName(), GetSummaryCount(), GetSummaryKindName(), and GetTotalTime().
Member Data Documentation
m_count
std::atomic<uint64_t> lldb_private::SummaryStatistics::m_count private
Definition at line 280 of file Statistics.h.
Referenced by GetSummaryCount(), OnInvoked(), and SummaryStatistics().
m_impl_type
const std::string lldb_private::SummaryStatistics::m_impl_type private
Definition at line 278 of file Statistics.h.
Referenced by GetSummaryKindName(), and SummaryStatistics().
m_name
const std::string lldb_private::SummaryStatistics::m_name private
Definition at line 279 of file Statistics.h.
Referenced by GetName(), and SummaryStatistics().
m_total_time
lldb_private::StatsDuration lldb_private::SummaryStatistics::m_total_time private
Definition at line 277 of file Statistics.h.
Referenced by GetDurationReference(), GetTotalTime(), Reset(), and SummaryStatistics().
The documentation for this class was generated from the following files:
Statistics.h
Statistics.cpp