LLDB: lldb_private::SymbolLocatorDebuginfod Class Reference
lldb_private::SymbolLocatorDebuginfod Class Reference
#include <SymbolLocatorDebuginfod.h>
Public Member Functions
SymbolLocatorDebuginfod ()
llvm::StringRef GetPluginName () override
PluginInterface protocol.
Public Member Functions inherited from lldb_private::SymbolLocator
SymbolLocator ()=default
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static void DebuggerInitialize (Debugger &debugger)
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static lldb_private::SymbolLocator * CreateInstance ()
static std::optional< ModuleSpec > LocateExecutableObjectFile (const ModuleSpec &module_spec)
static std::optional< FileSpec > LocateExecutableSymbolFile (const ModuleSpec &module_spec, const FileSpecList &default_search_paths)
Static Public Member Functions inherited from lldb_private::SymbolLocator
static void DownloadSymbolFileAsync (const UUID &uuid)
Locate the symbol file for the given UUID on a background thread.
Detailed Description
Definition at line 18 of file SymbolLocatorDebuginfod.h.
Constructor & Destructor Documentation
SymbolLocatorDebuginfod()
SymbolLocatorDebuginfod::SymbolLocatorDebuginfod ()
Definition at line 105 of file SymbolLocatorDebuginfod.cpp.
References lldb_private::SymbolLocator::SymbolLocator().
Referenced by CreateInstance().
Member Function Documentation
CreateInstance()
SymbolLocator * SymbolLocatorDebuginfod::CreateInstance () static
Definition at line 139 of file SymbolLocatorDebuginfod.cpp.
References lldb_private::SymbolLocator::SymbolLocator(), and SymbolLocatorDebuginfod().
Referenced by Initialize(), and Terminate().
DebuggerInitialize()
void SymbolLocatorDebuginfod::DebuggerInitialize (Debugger & debugger) static
Definition at line 119 of file SymbolLocatorDebuginfod.cpp.
References lldb_private::PluginManager::CreateSettingForSymbolLocatorPlugin(), GetGlobalPluginProperties(), and lldb_private::PluginManager::GetSettingForSymbolLocatorPlugin().
Referenced by Initialize().
GetPluginDescriptionStatic()
llvm::StringRef SymbolLocatorDebuginfod::GetPluginDescriptionStatic () static
Definition at line 135 of file SymbolLocatorDebuginfod.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef lldb_private::SymbolLocatorDebuginfod::GetPluginName () inline override virtual
PluginInterface protocol.
Implements lldb_private::PluginInterface.
Definition at line 33 of file SymbolLocatorDebuginfod.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::SymbolLocatorDebuginfod::GetPluginNameStatic () inline static
Definition at line 26 of file SymbolLocatorDebuginfod.h.
Referenced by GetPluginName(), and Initialize().
Initialize()
void SymbolLocatorDebuginfod::Initialize () static
Definition at line 107 of file SymbolLocatorDebuginfod.cpp.
References CreateInstance(), DebuggerInitialize(), GetPluginDescriptionStatic(), GetPluginNameStatic(), LocateExecutableObjectFile(), LocateExecutableSymbolFile(), and lldb_private::PluginManager::RegisterPlugin().
LocateExecutableObjectFile()
std::optional< ModuleSpec > SymbolLocatorDebuginfod::LocateExecutableObjectFile (const ModuleSpec & module_spec) static
Definition at line 203 of file SymbolLocatorDebuginfod.cpp.
References GetFileForModule().
Referenced by Initialize().
LocateExecutableSymbolFile()
std::optional< FileSpec > SymbolLocatorDebuginfod::LocateExecutableSymbolFile (const ModuleSpec & module_spec, const FileSpecList & default_search_paths) static
Definition at line 208 of file SymbolLocatorDebuginfod.cpp.
References GetFileForModule().
Referenced by Initialize().
Terminate()
void SymbolLocatorDebuginfod::Terminate () static
Definition at line 130 of file SymbolLocatorDebuginfod.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
The documentation for this class was generated from the following files:
SymbolLocatorDebuginfod.h
SymbolLocatorDebuginfod.cpp