LLDB: MapEntry Class Reference
MapEntry Class Reference
Public Member Functions
MapEntry ()=default
MapEntry (ValueObjectSP entry_sp)
MapEntry (ValueObject *entry)
ValueObjectSP left () const
ValueObjectSP right () const
ValueObjectSP parent () const
uint64_t value () const
bool error () const
bool null () const
ValueObjectSP GetEntry () const
void SetEntry (ValueObjectSP entry)
bool operator== (const MapEntry &rhs) const
Private Attributes
ValueObjectSP m_entry_sp
Detailed Description
Definition at line 47 of file LibCxxMap.cpp.
Constructor & Destructor Documentation
MapEntry() [1/3]
MapEntry::MapEntry () default
Referenced by operator==().
MapEntry() [2/3]
MapEntry::MapEntry (ValueObjectSP entry_sp) inline explicit
Definition at line 50 of file LibCxxMap.cpp.
References m_entry_sp.
MapEntry() [3/3]
MapEntry::MapEntry (ValueObject * entry) inline explicit
Definition at line 51 of file LibCxxMap.cpp.
References m_entry_sp.
Member Function Documentation
error()
bool MapEntry::error () const inline
Definition at line 83 of file LibCxxMap.cpp.
References m_entry_sp.
Referenced by MapIterator::tree_min().
GetEntry()
ValueObjectSP MapEntry::GetEntry () const inline
Definition at line 91 of file LibCxxMap.cpp.
References m_entry_sp.
left()
ValueObjectSP MapEntry::left () const inline
Definition at line 54 of file LibCxxMap.cpp.
References m_entry_sp.
Referenced by MapIterator::is_left_child(), and MapIterator::tree_min().
null()
bool MapEntry::null () const inline
Definition at line 89 of file LibCxxMap.cpp.
References value().
Referenced by MapIterator::is_left_child(), MapIterator::next(), and MapIterator::tree_min().
operator==()
bool MapEntry::operator== (const MapEntry & rhs) const inline
Definition at line 95 of file LibCxxMap.cpp.
References m_entry_sp, and MapEntry().
parent()
ValueObjectSP MapEntry::parent () const inline
Definition at line 69 of file LibCxxMap.cpp.
References m_entry_sp.
Referenced by MapIterator::is_left_child().
right()
ValueObjectSP MapEntry::right () const inline
Definition at line 61 of file LibCxxMap.cpp.
References m_entry_sp.
SetEntry()
void MapEntry::SetEntry (ValueObjectSP entry) inline
Definition at line 93 of file LibCxxMap.cpp.
References m_entry_sp.
Referenced by MapIterator::is_left_child(), and MapIterator::tree_min().
value()
uint64_t MapEntry::value () const inline
Definition at line 77 of file LibCxxMap.cpp.
References m_entry_sp.
Referenced by MapIterator::is_left_child(), and null().
Member Data Documentation
m_entry_sp
ValueObjectSP MapEntry::m_entry_sp private
Definition at line 100 of file LibCxxMap.cpp.
Referenced by error(), GetEntry(), left(), MapEntry(), MapEntry(), operator==(), parent(), right(), SetEntry(), and value().
The documentation for this class was generated from the following file:
LibCxxMap.cpp