LLDB: lldb_private::CommandObjectParsed Class Reference
lldb_private::CommandObjectParsed Class Reference abstract
#include <CommandObject.h>
Inherits lldb_private::CommandObject.
Inherited by CommandObjectTypeFormatterList< TypeFilterImpl >, CommandObjectTypeFormatterList< TypeFormatImpl >, CommandObjectTypeFormatterList< TypeSummaryImpl >, CommandObjectTypeFormatterList< SyntheticChildren >, CommandObjectBreakpointAddAddress, CommandObjectBreakpointAddException, CommandObjectBreakpointAddFile, CommandObjectBreakpointAddName, CommandObjectBreakpointAddScripted, CommandObjectBreakpointClear, CommandObjectBreakpointCommandAdd, CommandObjectBreakpointCommandDelete, CommandObjectBreakpointCommandList, CommandObjectBreakpointDelete, CommandObjectBreakpointDisable, CommandObjectBreakpointEnable, CommandObjectBreakpointList, CommandObjectBreakpointModify, CommandObjectBreakpointNameAdd, CommandObjectBreakpointNameConfigure, CommandObjectBreakpointNameDelete, CommandObjectBreakpointNameList, CommandObjectBreakpointRead, CommandObjectBreakpointSet, CommandObjectBreakpointWrite, CommandObjectCommandsAddRegex, CommandObjectCommandsContainerAdd, CommandObjectCommandsContainerDelete, CommandObjectCommandsDelete, CommandObjectCommandsScriptAdd, CommandObjectCommandsScriptClear, CommandObjectCommandsScriptDelete, CommandObjectCommandsScriptImport, CommandObjectCommandsScriptList, CommandObjectCommandsSource, CommandObjectCommandsUnalias, CommandObjectDiagnosticsDump, CommandObjectFrameDiagnose, CommandObjectFrameInfo, CommandObjectFrameRecognizerAdd, CommandObjectFrameRecognizerClear, CommandObjectFrameRecognizerInfo, CommandObjectFrameRecognizerList, CommandObjectFrameSelect, CommandObjectFrameVariable, CommandObjectLogDisable, CommandObjectLogDump, CommandObjectLogEnable, CommandObjectLogList, CommandObjectLogTimerDisable, CommandObjectLogTimerDump, CommandObjectLogTimerEnable, CommandObjectLogTimerIncrement, CommandObjectLogTimerReset, CommandObjectMemoryFind, CommandObjectMemoryHistory, CommandObjectMemoryRead, CommandObjectMemoryRegion, CommandObjectMemoryTagRead, CommandObjectMemoryTagWrite, CommandObjectMemoryWrite, CommandObjectMultiwordItaniumABI_Demangle, CommandObjectMultiwordObjC_TaggedPointer_Info, CommandObjectObjC_ClassTable_Dump, CommandObjectPlatformConnect, CommandObjectPlatformDisconnect, CommandObjectPlatformFClose, CommandObjectPlatformFOpen, CommandObjectPlatformFRead, CommandObjectPlatformFWrite, CommandObjectPlatformFileExists, CommandObjectPlatformGetFile, CommandObjectPlatformGetPermissions, CommandObjectPlatformGetSize, CommandObjectPlatformInstall, CommandObjectPlatformList, CommandObjectPlatformMkDir, CommandObjectPlatformProcessAttach, CommandObjectPlatformProcessInfo, CommandObjectPlatformProcessLaunch, CommandObjectPlatformProcessList, CommandObjectPlatformPutFile, CommandObjectPlatformSelect, CommandObjectPlatformSettings, CommandObjectPlatformStatus, CommandObjectPluginDisable, CommandObjectPluginEnable, CommandObjectPluginList, CommandObjectPluginLoad, CommandObjectProcessConnect, CommandObjectProcessContinue, CommandObjectProcessDetach, CommandObjectProcessGDBRemotePacketHistory, CommandObjectProcessGDBRemotePacketSend, CommandObjectProcessGDBRemotePacketXferSize, CommandObjectProcessGDBRemoteSpeedTest, CommandObjectProcessHandle, CommandObjectProcessInterrupt, CommandObjectProcessKDPPacketSend, CommandObjectProcessKill, CommandObjectProcessLaunchOrAttach, CommandObjectProcessLoad, CommandObjectProcessMinidumpDump, CommandObjectProcessSaveCore, CommandObjectProcessSignal, CommandObjectProcessStatus, CommandObjectProcessTraceStop, CommandObjectProcessUnload, CommandObjectProtocolServerGet, CommandObjectProtocolServerStart, CommandObjectProtocolServerStop, CommandObjectRegisterInfo, CommandObjectRegisterRead, CommandObjectRegisterWrite, CommandObjectScriptingExtensionList, CommandObjectScriptingObjectParsed, CommandObjectSessionHistory, CommandObjectSessionSave, CommandObjectSettingsClear, CommandObjectSettingsList, CommandObjectSettingsRead, CommandObjectSettingsShow, CommandObjectSettingsWrite, CommandObjectSourceCacheClear, CommandObjectSourceCacheDump, CommandObjectSourceInfo, CommandObjectSourceList, CommandObjectStatsDisable, CommandObjectStatsDump, CommandObjectStatsEnable, CommandObjectTargetCreate, CommandObjectTargetDelete, CommandObjectTargetDumpSectionLoadList, CommandObjectTargetDumpTypesystem, CommandObjectTargetFrameProviderClear, CommandObjectTargetFrameProviderList, CommandObjectTargetFrameProviderRegister, CommandObjectTargetFrameProviderRemove, CommandObjectTargetList, CommandObjectTargetModulesAdd, CommandObjectTargetModulesDumpClangPCMInfo, CommandObjectTargetModulesList, CommandObjectTargetModulesLookup, CommandObjectTargetModulesModuleAutoComplete, CommandObjectTargetModulesSearchPathsAdd, CommandObjectTargetModulesSearchPathsClear, CommandObjectTargetModulesSearchPathsInsert, CommandObjectTargetModulesSearchPathsList, CommandObjectTargetModulesSearchPathsQuery, CommandObjectTargetModulesShowUnwind, CommandObjectTargetModulesSourceFileAutoComplete, CommandObjectTargetSelect, CommandObjectTargetShowLaunchEnvironment, CommandObjectTargetStopHookAdd, CommandObjectTargetStopHookDelete, CommandObjectTargetStopHookEnableDisable, CommandObjectTargetStopHookList, CommandObjectTargetSymbolsAdd, CommandObjectTargetVariable, CommandObjectThreadContinue, CommandObjectThreadJump, CommandObjectThreadList, CommandObjectThreadPlanDiscard, CommandObjectThreadPlanPrune, CommandObjectThreadSelect, CommandObjectThreadStepWithTypeAndScope, CommandObjectThreadUntil, CommandObjectTraceDump, CommandObjectTraceDumpFunctionCalls, CommandObjectTraceDumpInstructions, CommandObjectTraceLoad, CommandObjectTraceSave, CommandObjectTraceSchema, CommandObjectTypeCategoryDefine, CommandObjectTypeCategoryDelete, CommandObjectTypeCategoryDisable, CommandObjectTypeCategoryEnable, CommandObjectTypeCategoryList, CommandObjectTypeFilterAdd, CommandObjectTypeFormatAdd, CommandObjectTypeFormatterClear, CommandObjectTypeFormatterDelete, CommandObjectTypeFormatterList< FormatterType >, CommandObjectTypeSummaryAdd, CommandObjectTypeSynthAdd, CommandObjectWatchpointCommandAdd, CommandObjectWatchpointCommandDelete, CommandObjectWatchpointCommandList, CommandObjectWatchpointDelete, CommandObjectWatchpointDisable, CommandObjectWatchpointEnable, CommandObjectWatchpointIgnore, CommandObjectWatchpointList, CommandObjectWatchpointModify, CommandObjectWatchpointSetVariable, CommandObjectWithFrameRecognizerArg, lldb_private::CommandObjectApropos, lldb_private::CommandObjectDisassemble, lldb_private::CommandObjectGUI, lldb_private::CommandObjectHelp, lldb_private::CommandObjectIterateOverThreads, lldb_private::CommandObjectMultipleThreads, lldb_private::CommandObjectQuit, lldb_private::CommandObjectVersion, lldb_private::CommandPluginInterfaceImplementation, lldb_private::ctf::CommandObjectThreadTraceExportCTF, lldb_private::trace_intel_pt::CommandObjectProcessTraceStartIntelPT, sddarwinlog_private::EnableCommand, and sddarwinlog_private::StatusCommand.
Public Member Functions
CommandObjectParsed (CommandInterpreter &interpreter, const char *name, const char *help=nullptr, const char *syntax=nullptr, uint32_t flags=0)
~CommandObjectParsed () override=default
void Execute (const char *args_string, CommandReturnObject &result) override
Public Member Functions inherited from lldb_private::CommandObject
CommandObject (CommandInterpreter &interpreter, llvm::StringRef name, llvm::StringRef help="", llvm::StringRef syntax="", uint32_t flags=0)
virtual ~CommandObject ()=default
CommandInterpreter & GetCommandInterpreter ()
Debugger & GetDebugger ()
virtual llvm::StringRef GetHelp ()
virtual llvm::StringRef GetHelpLong ()
virtual llvm::StringRef GetSyntax ()
llvm::StringRef GetCommandName () const
virtual void SetHelp (llvm::StringRef str)
virtual void SetHelpLong (llvm::StringRef str)
void SetSyntax (llvm::StringRef str)
virtual bool IsRemovable () const
virtual bool IsMultiwordObject ()
bool IsUserCommand ()
void SetIsUserCommand (bool is_user)
virtual CommandObjectMultiword * GetAsMultiwordCommand ()
virtual bool IsAlias ()
virtual bool IsDashDashCommand ()
virtual lldb::CommandObjectSP GetSubcommandSP (llvm::StringRef sub_cmd, StringList *matches=nullptr)
virtual lldb::CommandObjectSP GetSubcommandSPExact (llvm::StringRef sub_cmd)
virtual CommandObject * GetSubcommandObject (llvm::StringRef sub_cmd, StringList *matches=nullptr)
void FormatLongHelpText (Stream &output_strm, llvm::StringRef long_help)
void GenerateHelpText (CommandReturnObject &result)
virtual void GenerateHelpText (Stream &result)
virtual bool LoadSubCommand (llvm::StringRef cmd_name, const lldb::CommandObjectSP &command_obj)
virtual llvm::Error LoadUserSubcommand (llvm::StringRef cmd_name, const lldb::CommandObjectSP &command_obj, bool can_replace)
virtual bool WantsCompletion ()
virtual Options * GetOptions ()
void AddSimpleArgumentList (lldb::CommandArgumentType arg_type, ArgumentRepetitionType repetition_type=eArgRepeatPlain)
void AddIDsArgumentData (IDType type)
int GetNumArgumentEntries ()
CommandArgumentEntry * GetArgumentEntryAtIndex (int idx)
void GetFormattedCommandArguments (Stream &str, uint32_t opt_set_mask=LLDB_OPT_SET_ALL)
bool ParseOptions (Args &args, CommandReturnObject &result)
void SetCommandName (llvm::StringRef name)
virtual void HandleCompletion (CompletionRequest &request)
This default version handles calling option argument completions and then calls HandleArgumentCompletion if the cursor is on an argument, not an option.
virtual void HandleArgumentCompletion (CompletionRequest &request, OptionElementVector &opt_element_vector)
The default version handles argument definitions that have only one argument type, and use one of the argument types that have an entry in the CommonCompletions.
bool HelpTextContainsWord (llvm::StringRef search_word, bool search_short_help=true, bool search_long_help=true, bool search_syntax=true, bool search_options=true)
Flags & GetFlags ()
The flags accessor.
const Flags & GetFlags () const
The flags const accessor.
virtual std::optional< std::string > GetRepeatCommand (Args &current_command_args, uint32_t index)
Get the command that appropriate for a "repeat" of the current command.
bool HasOverrideCallback () const
void SetOverrideCallback (lldb::CommandOverrideCallback callback, void *baton)
void SetOverrideCallback (lldb_private::CommandOverrideCallbackWithResult callback, void *baton)
bool InvokeOverrideCallback (const char **argv, CommandReturnObject &result)
void SetOriginalCommandString (std::string s)
Set the command input as it appeared in the terminal.
Protected Member Functions
virtual void DoExecute (Args &command, CommandReturnObject &result)=0
bool WantsRawCommandString () override
Protected Member Functions inherited from lldb_private::CommandObject
bool ParseOptionsAndNotify (Args &args, CommandReturnObject &result, OptionGroupOptions &group_options, ExecutionContext &exe_ctx)
virtual const char * GetInvalidTargetDescription ()
virtual const char * GetInvalidProcessDescription ()
virtual const char * GetInvalidThreadDescription ()
virtual const char * GetInvalidFrameDescription ()
virtual const char * GetInvalidRegContextDescription ()
Target & GetDummyTarget ()
Target & GetTarget ()
Thread * GetDefaultThread ()
bool CheckRequirements (CommandReturnObject &result)
Check the command to make sure anything required by this command is available.
void Cleanup ()
Additional Inherited Members
Public Types inherited from lldb_private::CommandObject
enum IDType { eBreakpointArgs = 0 , eWatchpointArgs = 1 }
typedef llvm::StringRef ArgumentHelpCallbackFunction()
typedef std::vector< CommandArgumentData > CommandArgumentEntry
typedef std::map< std::string, lldb::CommandObjectSP, std::less<> > CommandMap
Static Public Member Functions inherited from lldb_private::CommandObject
static const char * GetArgumentTypeAsCString (const lldb::CommandArgumentType arg_type)
static const char * GetArgumentDescriptionAsCString (const lldb::CommandArgumentType arg_type)
static lldb::CommandArgumentType LookupArgumentName (llvm::StringRef arg_name)
static const ArgumentTableEntry * FindArgumentDataByType (lldb::CommandArgumentType arg_type)
static void GetArgumentHelp (Stream &str, lldb::CommandArgumentType arg_type, CommandInterpreter &interpreter)
static const char * GetArgumentName (lldb::CommandArgumentType arg_type)
static bool IsPairType (ArgumentRepetitionType arg_repeat_type)
static std::optional< ArgumentRepetitionType > ArgRepetitionFromString (llvm::StringRef string)
Protected Attributes inherited from lldb_private::CommandObject
CommandInterpreter & m_interpreter
ExecutionContext m_exe_ctx
std::unique_lock< std::recursive_mutex > m_api_locker
std::string m_cmd_name
std::string m_cmd_help_short
std::string m_cmd_help_long
std::string m_cmd_syntax
std::string m_original_command
Flags m_flags
std::vector< CommandArgumentEntry > m_arguments
lldb::CommandOverrideCallback m_deprecated_command_override_callback
lldb_private::CommandOverrideCallbackWithResult m_command_override_callback
void * m_command_override_baton
bool m_is_user_command = false
Detailed Description
Definition at line 424 of file CommandObject.h.
Constructor & Destructor Documentation
CommandObjectParsed()
lldb_private::CommandObjectParsed::CommandObjectParsed (CommandInterpreter & interpreter, const char * name, const char * help = nullptr, const char * syntax = nullptr, uint32_t flags = 0) inline
Definition at line 426 of file CommandObject.h.
References lldb_private::CommandObject::CommandObject().
Referenced by lldb_private::CommandObjectApropos::CommandObjectApropos(), CommandObjectBreakpointAddAddress::CommandObjectBreakpointAddAddress(), CommandObjectBreakpointAddException::CommandObjectBreakpointAddException(), CommandObjectBreakpointAddFile::CommandObjectBreakpointAddFile(), CommandObjectBreakpointAddName::CommandObjectBreakpointAddName(), CommandObjectBreakpointAddScripted::CommandObjectBreakpointAddScripted(), CommandObjectBreakpointClear::CommandObjectBreakpointClear(), CommandObjectBreakpointCommandAdd::CommandObjectBreakpointCommandAdd(), CommandObjectBreakpointCommandDelete::CommandObjectBreakpointCommandDelete(), CommandObjectBreakpointCommandList::CommandObjectBreakpointCommandList(), CommandObjectBreakpointDelete::CommandObjectBreakpointDelete(), CommandObjectBreakpointDisable::CommandObjectBreakpointDisable(), CommandObjectBreakpointEnable::CommandObjectBreakpointEnable(), CommandObjectBreakpointList::CommandObjectBreakpointList(), CommandObjectBreakpointModify::CommandObjectBreakpointModify(), CommandObjectBreakpointNameAdd::CommandObjectBreakpointNameAdd(), CommandObjectBreakpointNameConfigure::CommandObjectBreakpointNameConfigure(), CommandObjectBreakpointNameDelete::CommandObjectBreakpointNameDelete(), CommandObjectBreakpointNameList::CommandObjectBreakpointNameList(), CommandObjectBreakpointRead::CommandObjectBreakpointRead(), CommandObjectBreakpointSet::CommandObjectBreakpointSet(), CommandObjectBreakpointWrite::CommandObjectBreakpointWrite(), CommandObjectCommandsAddRegex::CommandObjectCommandsAddRegex(), CommandObjectCommandsContainerAdd::CommandObjectCommandsContainerAdd(), CommandObjectCommandsContainerDelete::CommandObjectCommandsContainerDelete(), CommandObjectCommandsDelete::CommandObjectCommandsDelete(), CommandObjectCommandsScriptAdd::CommandObjectCommandsScriptAdd(), CommandObjectCommandsScriptClear::CommandObjectCommandsScriptClear(), CommandObjectCommandsScriptDelete::CommandObjectCommandsScriptDelete(), CommandObjectCommandsScriptImport::CommandObjectCommandsScriptImport(), CommandObjectCommandsScriptList::CommandObjectCommandsScriptList(), CommandObjectCommandsSource::CommandObjectCommandsSource(), CommandObjectCommandsUnalias::CommandObjectCommandsUnalias(), CommandObjectDiagnosticsDump::CommandObjectDiagnosticsDump(), lldb_private::CommandObjectDisassemble::CommandObjectDisassemble(), CommandObjectFrameDiagnose::CommandObjectFrameDiagnose(), CommandObjectFrameInfo::CommandObjectFrameInfo(), CommandObjectFrameRecognizerAdd::CommandObjectFrameRecognizerAdd(), CommandObjectFrameRecognizerClear::CommandObjectFrameRecognizerClear(), CommandObjectFrameRecognizerInfo::CommandObjectFrameRecognizerInfo(), CommandObjectFrameRecognizerList::CommandObjectFrameRecognizerList(), CommandObjectFrameSelect::CommandObjectFrameSelect(), CommandObjectFrameVariable::CommandObjectFrameVariable(), lldb_private::CommandObjectGUI::CommandObjectGUI(), lldb_private::CommandObjectHelp::CommandObjectHelp(), lldb_private::CommandObjectIterateOverThreads::CommandObjectIterateOverThreads(), CommandObjectLogDisable::CommandObjectLogDisable(), CommandObjectLogDump::CommandObjectLogDump(), CommandObjectLogEnable::CommandObjectLogEnable(), CommandObjectLogList::CommandObjectLogList(), CommandObjectLogTimerDisable::CommandObjectLogTimerDisable(), CommandObjectLogTimerDump::CommandObjectLogTimerDump(), CommandObjectLogTimerEnable::CommandObjectLogTimerEnable(), CommandObjectLogTimerIncrement::CommandObjectLogTimerIncrement(), CommandObjectLogTimerReset::CommandObjectLogTimerReset(), CommandObjectMemoryFind::CommandObjectMemoryFind(), CommandObjectMemoryHistory::CommandObjectMemoryHistory(), CommandObjectMemoryRead::CommandObjectMemoryRead(), CommandObjectMemoryRegion::CommandObjectMemoryRegion(), CommandObjectMemoryTagRead::CommandObjectMemoryTagRead(), CommandObjectMemoryTagWrite::CommandObjectMemoryTagWrite(), CommandObjectMemoryWrite::CommandObjectMemoryWrite(), lldb_private::CommandObjectMultipleThreads::CommandObjectMultipleThreads(), CommandObjectMultiwordItaniumABI_Demangle::CommandObjectMultiwordItaniumABI_Demangle(), CommandObjectMultiwordObjC_TaggedPointer_Info::CommandObjectMultiwordObjC_TaggedPointer_Info(), CommandObjectObjC_ClassTable_Dump::CommandObjectObjC_ClassTable_Dump(), CommandObjectPlatformConnect::CommandObjectPlatformConnect(), CommandObjectPlatformDisconnect::CommandObjectPlatformDisconnect(), CommandObjectPlatformFClose::CommandObjectPlatformFClose(), CommandObjectPlatformFileExists::CommandObjectPlatformFileExists(), CommandObjectPlatformFOpen::CommandObjectPlatformFOpen(), CommandObjectPlatformFRead::CommandObjectPlatformFRead(), CommandObjectPlatformFWrite::CommandObjectPlatformFWrite(), CommandObjectPlatformGetFile::CommandObjectPlatformGetFile(), CommandObjectPlatformGetPermissions::CommandObjectPlatformGetPermissions(), CommandObjectPlatformGetSize::CommandObjectPlatformGetSize(), CommandObjectPlatformInstall::CommandObjectPlatformInstall(), CommandObjectPlatformList::CommandObjectPlatformList(), CommandObjectPlatformMkDir::CommandObjectPlatformMkDir(), CommandObjectPlatformProcessAttach::CommandObjectPlatformProcessAttach(), CommandObjectPlatformProcessInfo::CommandObjectPlatformProcessInfo(), CommandObjectPlatformProcessLaunch::CommandObjectPlatformProcessLaunch(), CommandObjectPlatformProcessList::CommandObjectPlatformProcessList(), CommandObjectPlatformPutFile::CommandObjectPlatformPutFile(), CommandObjectPlatformSelect::CommandObjectPlatformSelect(), CommandObjectPlatformSettings::CommandObjectPlatformSettings(), CommandObjectPlatformStatus::CommandObjectPlatformStatus(), CommandObjectPluginDisable::CommandObjectPluginDisable(), CommandObjectPluginEnable::CommandObjectPluginEnable(), CommandObjectPluginList::CommandObjectPluginList(), CommandObjectPluginLoad::CommandObjectPluginLoad(), CommandObjectProcessConnect::CommandObjectProcessConnect(), CommandObjectProcessContinue::CommandObjectProcessContinue(), CommandObjectProcessDetach::CommandObjectProcessDetach(), CommandObjectProcessGDBRemotePacketHistory::CommandObjectProcessGDBRemotePacketHistory(), CommandObjectProcessGDBRemotePacketSend::CommandObjectProcessGDBRemotePacketSend(), CommandObjectProcessGDBRemotePacketXferSize::CommandObjectProcessGDBRemotePacketXferSize(), CommandObjectProcessGDBRemoteSpeedTest::CommandObjectProcessGDBRemoteSpeedTest(), CommandObjectProcessHandle::CommandObjectProcessHandle(), CommandObjectProcessInterrupt::CommandObjectProcessInterrupt(), CommandObjectProcessKDPPacketSend::CommandObjectProcessKDPPacketSend(), CommandObjectProcessKill::CommandObjectProcessKill(), CommandObjectProcessLaunchOrAttach::CommandObjectProcessLaunchOrAttach(), CommandObjectProcessLoad::CommandObjectProcessLoad(), CommandObjectProcessMinidumpDump::CommandObjectProcessMinidumpDump(), CommandObjectProcessSaveCore::CommandObjectProcessSaveCore(), CommandObjectProcessSignal::CommandObjectProcessSignal(), CommandObjectProcessStatus::CommandObjectProcessStatus(), lldb_private::trace_intel_pt::CommandObjectProcessTraceStartIntelPT::CommandObjectProcessTraceStartIntelPT(), CommandObjectProcessTraceStop::CommandObjectProcessTraceStop(), CommandObjectProcessUnload::CommandObjectProcessUnload(), CommandObjectProtocolServerGet::CommandObjectProtocolServerGet(), CommandObjectProtocolServerStart::CommandObjectProtocolServerStart(), CommandObjectProtocolServerStop::CommandObjectProtocolServerStop(), lldb_private::CommandObjectQuit::CommandObjectQuit(), CommandObjectRegisterInfo::CommandObjectRegisterInfo(), CommandObjectRegisterRead::CommandObjectRegisterRead(), CommandObjectRegisterWrite::CommandObjectRegisterWrite(), CommandObjectScriptingExtensionList::CommandObjectScriptingExtensionList(), CommandObjectScriptingObjectParsed::CommandObjectScriptingObjectParsed(), CommandObjectSessionHistory::CommandObjectSessionHistory(), CommandObjectSessionSave::CommandObjectSessionSave(), CommandObjectSettingsClear::CommandObjectSettingsClear(), CommandObjectSettingsList::CommandObjectSettingsList(), CommandObjectSettingsRead::CommandObjectSettingsRead(), CommandObjectSettingsShow::CommandObjectSettingsShow(), CommandObjectSettingsWrite::CommandObjectSettingsWrite(), CommandObjectSourceCacheClear::CommandObjectSourceCacheClear(), CommandObjectSourceCacheDump::CommandObjectSourceCacheDump(), CommandObjectSourceInfo::CommandObjectSourceInfo(), CommandObjectSourceList::CommandObjectSourceList(), CommandObjectStatsDisable::CommandObjectStatsDisable(), CommandObjectStatsDump::CommandObjectStatsDump(), CommandObjectStatsEnable::CommandObjectStatsEnable(), CommandObjectTargetCreate::CommandObjectTargetCreate(), CommandObjectTargetDelete::CommandObjectTargetDelete(), CommandObjectTargetDumpSectionLoadList::CommandObjectTargetDumpSectionLoadList(), CommandObjectTargetDumpTypesystem::CommandObjectTargetDumpTypesystem(), CommandObjectTargetFrameProviderClear::CommandObjectTargetFrameProviderClear(), CommandObjectTargetFrameProviderList::CommandObjectTargetFrameProviderList(), CommandObjectTargetFrameProviderRegister::CommandObjectTargetFrameProviderRegister(), CommandObjectTargetFrameProviderRemove::CommandObjectTargetFrameProviderRemove(), CommandObjectTargetList::CommandObjectTargetList(), CommandObjectTargetModulesAdd::CommandObjectTargetModulesAdd(), CommandObjectTargetModulesDumpClangPCMInfo::CommandObjectTargetModulesDumpClangPCMInfo(), CommandObjectTargetModulesList::CommandObjectTargetModulesList(), CommandObjectTargetModulesLookup::CommandObjectTargetModulesLookup(), CommandObjectTargetModulesModuleAutoComplete::CommandObjectTargetModulesModuleAutoComplete(), CommandObjectTargetModulesSearchPathsAdd::CommandObjectTargetModulesSearchPathsAdd(), CommandObjectTargetModulesSearchPathsClear::CommandObjectTargetModulesSearchPathsClear(), CommandObjectTargetModulesSearchPathsInsert::CommandObjectTargetModulesSearchPathsInsert(), CommandObjectTargetModulesSearchPathsList::CommandObjectTargetModulesSearchPathsList(), CommandObjectTargetModulesSearchPathsQuery::CommandObjectTargetModulesSearchPathsQuery(), CommandObjectTargetModulesShowUnwind::CommandObjectTargetModulesShowUnwind(), CommandObjectTargetModulesSourceFileAutoComplete::CommandObjectTargetModulesSourceFileAutoComplete(), CommandObjectTargetSelect::CommandObjectTargetSelect(), CommandObjectTargetShowLaunchEnvironment::CommandObjectTargetShowLaunchEnvironment(), CommandObjectTargetStopHookAdd::CommandObjectTargetStopHookAdd(), CommandObjectTargetStopHookDelete::CommandObjectTargetStopHookDelete(), CommandObjectTargetStopHookEnableDisable::CommandObjectTargetStopHookEnableDisable(), CommandObjectTargetStopHookList::CommandObjectTargetStopHookList(), CommandObjectTargetSymbolsAdd::CommandObjectTargetSymbolsAdd(), CommandObjectTargetVariable::CommandObjectTargetVariable(), CommandObjectThreadContinue::CommandObjectThreadContinue(), CommandObjectThreadJump::CommandObjectThreadJump(), CommandObjectThreadList::CommandObjectThreadList(), CommandObjectThreadPlanDiscard::CommandObjectThreadPlanDiscard(), CommandObjectThreadPlanPrune::CommandObjectThreadPlanPrune(), CommandObjectThreadSelect::CommandObjectThreadSelect(), CommandObjectThreadStepWithTypeAndScope::CommandObjectThreadStepWithTypeAndScope(), lldb_private::ctf::CommandObjectThreadTraceExportCTF::CommandObjectThreadTraceExportCTF(), CommandObjectThreadUntil::CommandObjectThreadUntil(), CommandObjectTraceDump::CommandObjectTraceDump(), CommandObjectTraceDumpFunctionCalls::CommandObjectTraceDumpFunctionCalls(), CommandObjectTraceDumpInstructions::CommandObjectTraceDumpInstructions(), CommandObjectTraceLoad::CommandObjectTraceLoad(), CommandObjectTraceSave::CommandObjectTraceSave(), CommandObjectTraceSchema::CommandObjectTraceSchema(), CommandObjectTypeFormatAdd::CommandObjectTypeFormatAdd(), CommandObjectTypeFormatterClear::CommandObjectTypeFormatterClear(), CommandObjectTypeFormatterDelete::CommandObjectTypeFormatterDelete(), CommandObjectTypeFormatterList< FormatterType >::CommandObjectTypeFormatterList(), CommandObjectTypeSummaryAdd::CommandObjectTypeSummaryAdd(), lldb_private::CommandObjectVersion::CommandObjectVersion(), CommandObjectWatchpointCommandAdd::CommandObjectWatchpointCommandAdd(), CommandObjectWatchpointCommandDelete::CommandObjectWatchpointCommandDelete(), CommandObjectWatchpointCommandList::CommandObjectWatchpointCommandList(), CommandObjectWatchpointDelete::CommandObjectWatchpointDelete(), CommandObjectWatchpointDisable::CommandObjectWatchpointDisable(), CommandObjectWatchpointEnable::CommandObjectWatchpointEnable(), CommandObjectWatchpointIgnore::CommandObjectWatchpointIgnore(), CommandObjectWatchpointList::CommandObjectWatchpointList(), CommandObjectWatchpointModify::CommandObjectWatchpointModify(), CommandObjectWatchpointSetVariable::CommandObjectWatchpointSetVariable(), CommandObjectWithFrameRecognizerArg::CommandObjectWithFrameRecognizerArg(), lldb_private::CommandPluginInterfaceImplementation::CommandPluginInterfaceImplementation(), CommandObjectTypeCategoryList::DoExecute(), sddarwinlog_private::EnableCommand::EnableCommand(), and sddarwinlog_private::StatusCommand::StatusCommand().
~CommandObjectParsed()
lldb_private::CommandObjectParsed::~CommandObjectParsed () override default
Member Function Documentation
DoExecute()
virtual void lldb_private::CommandObjectParsed::DoExecute (Args & command, CommandReturnObject & result) protected pure virtual
Implemented in CommandObjectBreakpointAddAddress, CommandObjectBreakpointAddException, CommandObjectBreakpointAddFile, CommandObjectBreakpointAddName, CommandObjectBreakpointAddScripted, CommandObjectBreakpointClear, CommandObjectBreakpointCommandAdd, CommandObjectBreakpointCommandDelete, CommandObjectBreakpointCommandList, CommandObjectBreakpointDelete, CommandObjectBreakpointDisable, CommandObjectBreakpointEnable, CommandObjectBreakpointList, CommandObjectBreakpointModify, CommandObjectBreakpointNameAdd, CommandObjectBreakpointNameConfigure, CommandObjectBreakpointNameDelete, CommandObjectBreakpointNameList, CommandObjectBreakpointRead, CommandObjectBreakpointSet, CommandObjectBreakpointWrite, CommandObjectCommandsAddRegex, CommandObjectCommandsContainerAdd, CommandObjectCommandsContainerDelete, CommandObjectCommandsDelete, CommandObjectCommandsScriptAdd, CommandObjectCommandsScriptClear, CommandObjectCommandsScriptDelete, CommandObjectCommandsScriptImport, CommandObjectCommandsScriptList, CommandObjectCommandsSource, CommandObjectCommandsUnalias, CommandObjectDiagnosticsDump, CommandObjectFrameDiagnose, CommandObjectFrameInfo, CommandObjectFrameRecognizerAdd, CommandObjectFrameRecognizerClear, CommandObjectFrameRecognizerInfo, CommandObjectFrameRecognizerList, CommandObjectFrameSelect, CommandObjectFrameVariable, CommandObjectLogDisable, CommandObjectLogDump, CommandObjectLogEnable, CommandObjectLogList, CommandObjectLogTimerDisable, CommandObjectLogTimerDump, CommandObjectLogTimerEnable, CommandObjectLogTimerIncrement, CommandObjectLogTimerReset, CommandObjectMemoryFind, CommandObjectMemoryHistory, CommandObjectMemoryRead, CommandObjectMemoryRegion, CommandObjectMemoryTagRead, CommandObjectMemoryTagWrite, CommandObjectMemoryWrite, CommandObjectMultiwordItaniumABI_Demangle, CommandObjectMultiwordObjC_TaggedPointer_Info, CommandObjectObjC_ClassTable_Dump, CommandObjectPlatformConnect, CommandObjectPlatformDisconnect, CommandObjectPlatformFClose, CommandObjectPlatformFileExists, CommandObjectPlatformFOpen, CommandObjectPlatformFRead, CommandObjectPlatformFWrite, CommandObjectPlatformGetFile, CommandObjectPlatformGetPermissions, CommandObjectPlatformGetSize, CommandObjectPlatformInstall, CommandObjectPlatformList, CommandObjectPlatformMkDir, CommandObjectPlatformProcessAttach, CommandObjectPlatformProcessInfo, CommandObjectPlatformProcessLaunch, CommandObjectPlatformProcessList, CommandObjectPlatformPutFile, CommandObjectPlatformSelect, CommandObjectPlatformSettings, CommandObjectPlatformStatus, CommandObjectPluginDisable, CommandObjectPluginEnable, CommandObjectPluginList, CommandObjectPluginLoad, CommandObjectProcessAttach, CommandObjectProcessConnect, CommandObjectProcessContinue, CommandObjectProcessDetach, CommandObjectProcessGDBRemotePacketHistory, CommandObjectProcessGDBRemotePacketSend, CommandObjectProcessGDBRemotePacketXferSize, CommandObjectProcessGDBRemoteSpeedTest, CommandObjectProcessHandle, CommandObjectProcessInterrupt, CommandObjectProcessKDPPacketSend, CommandObjectProcessKill, CommandObjectProcessLaunch, CommandObjectProcessLoad, CommandObjectProcessMinidumpDump, CommandObjectProcessSaveCore, CommandObjectProcessSignal, CommandObjectProcessStatus, CommandObjectProcessTraceStop, CommandObjectProcessUnload, CommandObjectProtocolServerGet, CommandObjectProtocolServerStart, CommandObjectProtocolServerStop, CommandObjectRegisterInfo, CommandObjectRegisterRead, CommandObjectRegisterWrite, CommandObjectScriptingExtensionList, CommandObjectScriptingObjectParsed, CommandObjectSessionHistory, CommandObjectSessionSave, CommandObjectSettingsClear, CommandObjectSettingsList, CommandObjectSettingsRead, CommandObjectSettingsShow, CommandObjectSettingsWrite, CommandObjectSourceCacheClear, CommandObjectSourceCacheDump, CommandObjectSourceInfo, CommandObjectSourceList, CommandObjectStatsDisable, CommandObjectStatsDump, CommandObjectStatsEnable, CommandObjectTargetCreate, CommandObjectTargetDelete, CommandObjectTargetDumpSectionLoadList, CommandObjectTargetDumpTypesystem, CommandObjectTargetFrameProviderClear, CommandObjectTargetFrameProviderList, CommandObjectTargetFrameProviderRegister, CommandObjectTargetFrameProviderRemove, CommandObjectTargetList, CommandObjectTargetModulesAdd, CommandObjectTargetModulesDumpClangAST, CommandObjectTargetModulesDumpClangPCMInfo, CommandObjectTargetModulesDumpLineTable, CommandObjectTargetModulesDumpObjfile, CommandObjectTargetModulesDumpSections, CommandObjectTargetModulesDumpSeparateDebugInfoFiles, CommandObjectTargetModulesDumpSymfile, CommandObjectTargetModulesDumpSymtab, CommandObjectTargetModulesList, CommandObjectTargetModulesLoad, CommandObjectTargetModulesLookup, CommandObjectTargetModulesSearchPathsAdd, CommandObjectTargetModulesSearchPathsClear, CommandObjectTargetModulesSearchPathsInsert, CommandObjectTargetModulesSearchPathsList, CommandObjectTargetModulesSearchPathsQuery, CommandObjectTargetModulesShowUnwind, CommandObjectTargetSelect, CommandObjectTargetShowLaunchEnvironment, CommandObjectTargetStopHookAdd, CommandObjectTargetStopHookDelete, CommandObjectTargetStopHookEnableDisable, CommandObjectTargetStopHookList, CommandObjectTargetSymbolsAdd, CommandObjectTargetVariable, CommandObjectThreadContinue, CommandObjectThreadJump, CommandObjectThreadList, CommandObjectThreadPlanDiscard, CommandObjectThreadPlanList, CommandObjectThreadPlanPrune, CommandObjectThreadSelect, CommandObjectThreadStepWithTypeAndScope, CommandObjectThreadUntil, CommandObjectTraceDump, CommandObjectTraceDumpFunctionCalls, CommandObjectTraceDumpInstructions, CommandObjectTraceLoad, CommandObjectTraceSave, CommandObjectTraceSchema, CommandObjectTypeCategoryDefine, CommandObjectTypeCategoryDelete, CommandObjectTypeCategoryDisable, CommandObjectTypeCategoryEnable, CommandObjectTypeCategoryList, CommandObjectTypeFilterAdd, CommandObjectTypeFormatAdd, CommandObjectTypeFormatterClear, CommandObjectTypeFormatterDelete, CommandObjectTypeFormatterList< FormatterType >, CommandObjectTypeSummaryAdd, CommandObjectTypeSynthAdd, CommandObjectWatchpointCommandAdd, CommandObjectWatchpointCommandDelete, CommandObjectWatchpointCommandList, CommandObjectWatchpointDelete, CommandObjectWatchpointDisable, CommandObjectWatchpointEnable, CommandObjectWatchpointIgnore, CommandObjectWatchpointList, CommandObjectWatchpointModify, CommandObjectWatchpointSetVariable, CommandObjectWithFrameRecognizerArg, lldb_private::CommandObjectApropos, lldb_private::CommandObjectDisassemble, lldb_private::CommandObjectGUI, lldb_private::CommandObjectHelp, lldb_private::CommandObjectIterateOverThreads, lldb_private::CommandObjectMultipleThreads, lldb_private::CommandObjectQuit, lldb_private::CommandObjectVersion, lldb_private::CommandPluginInterfaceImplementation, lldb_private::ctf::CommandObjectThreadTraceExportCTF, lldb_private::trace_intel_pt::CommandObjectProcessTraceStartIntelPT, sddarwinlog_private::EnableCommand, and sddarwinlog_private::StatusCommand.
Referenced by Execute().
Execute()
void CommandObjectParsed::Execute (const char * args_string, CommandReturnObject & result) override virtual
Parameters
offset_in_command is on what column args_string appears, if applicable. This enables diagnostics that refer back to the user input.
Implements lldb_private::CommandObject.
Definition at line 796 of file CommandObject.cpp.
References lldb_private::Args::AppendArguments(), lldb_private::CommandReturnObject::AppendErrorWithFormatv(), lldb_private::Args::ArgEntry::c_str(), lldb_private::CommandObject::CheckRequirements(), lldb_private::CommandObject::Cleanup(), DoExecute(), lldb_private::Args::entries(), error(), lldb_private::Args::GetArgumentCount(), lldb_private::CommandObject::GetCommandName(), lldb_private::Args::GetConstArgumentVector(), lldb_private::Args::ArgEntry::GetQuoteChar(), lldb_private::CommandObject::HasOverrideCallback(), lldb_private::CommandObject::InvokeOverrideCallback(), lldb_private::CommandObject::m_arguments, lldb_private::CommandObject::m_interpreter, lldb_private::CommandObject::ParseOptions(), lldb_private::Args::ArgEntry::ref(), and lldb_private::Args::ReplaceArgumentAtIndex().
WantsRawCommandString()
bool lldb_private::CommandObjectParsed::WantsRawCommandString () inline override protected virtual
Implements lldb_private::CommandObject.
Definition at line 438 of file CommandObject.h.
The documentation for this class was generated from the following files:
CommandObject.h
CommandObject.cpp