LLDB: lldb_private::SyntheticValueProviderFrontEnd Class Reference
lldb_private::SyntheticValueProviderFrontEnd Class Reference abstract
#include <TypeSynthetic.h>
Public Member Functions
SyntheticValueProviderFrontEnd (ValueObject &backend)
~SyntheticValueProviderFrontEnd () override=default
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
bool MightHaveChildren () override
lldb::ValueObjectSP GetSyntheticValue () override=0
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual ConstString GetSyntheticTypeName ()
Private Member Functions
SyntheticValueProviderFrontEnd (const SyntheticValueProviderFrontEnd &)=delete
const SyntheticValueProviderFrontEnd & operator= (const SyntheticValueProviderFrontEnd &)=delete
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
Definition at line 104 of file TypeSynthetic.h.
Constructor & Destructor Documentation
SyntheticValueProviderFrontEnd() [1/2]
lldb_private::SyntheticValueProviderFrontEnd::SyntheticValueProviderFrontEnd (ValueObject & backend) inline
Definition at line 106 of file TypeSynthetic.h.
References lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd().
Referenced by operator=(), and SyntheticValueProviderFrontEnd().
~SyntheticValueProviderFrontEnd()
lldb_private::SyntheticValueProviderFrontEnd::~SyntheticValueProviderFrontEnd () override default
SyntheticValueProviderFrontEnd() [2/2]
lldb_private::SyntheticValueProviderFrontEnd::SyntheticValueProviderFrontEnd (const SyntheticValueProviderFrontEnd &) private delete
References SyntheticValueProviderFrontEnd().
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > lldb_private::SyntheticValueProviderFrontEnd::CalculateNumChildren () inline override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 111 of file TypeSynthetic.h.
GetChildAtIndex()
lldb::ValueObjectSP lldb_private::SyntheticValueProviderFrontEnd::GetChildAtIndex (uint32_t idx) inline override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 113 of file TypeSynthetic.h.
GetIndexOfChildWithName()
llvm::Expected< size_t > lldb_private::SyntheticValueProviderFrontEnd::GetIndexOfChildWithName (ConstString name) inline override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 115 of file TypeSynthetic.h.
References lldb_private::ConstString::AsCString().
GetSyntheticValue()
lldb::ValueObjectSP lldb_private::SyntheticValueProviderFrontEnd::GetSyntheticValue () override pure virtual
Reimplemented from lldb_private::SyntheticChildrenFrontEnd.
MightHaveChildren()
bool lldb_private::SyntheticValueProviderFrontEnd::MightHaveChildren () inline override virtual
Reimplemented from lldb_private::SyntheticChildrenFrontEnd.
Definition at line 124 of file TypeSynthetic.h.
operator=()
const SyntheticValueProviderFrontEnd & lldb_private::SyntheticValueProviderFrontEnd::operator= (const SyntheticValueProviderFrontEnd &) private delete
References SyntheticValueProviderFrontEnd().
Update()
lldb::ChildCacheState lldb_private::SyntheticValueProviderFrontEnd::Update () inline override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 120 of file TypeSynthetic.h.
References lldb::eRefetch.
The documentation for this class was generated from the following file:
TypeSynthetic.h