LLDB: lldb_private::OptionGroupPlatformRSync Class Reference
lldb_private::OptionGroupPlatformRSync Class Reference
#include <Platform.h>
Public Member Functions
OptionGroupPlatformRSync ()=default
~OptionGroupPlatformRSync () override=default
lldb_private::Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext *execution_context) override
void OptionParsingStarting (ExecutionContext *execution_context) override
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Public Attributes
bool m_rsync
std::string m_rsync_opts
std::string m_rsync_prefix
bool m_ignores_remote_hostname
Private Member Functions
OptionGroupPlatformRSync (const OptionGroupPlatformRSync &)=delete
const OptionGroupPlatformRSync & operator= (const OptionGroupPlatformRSync &)=delete
Detailed Description
Definition at line 1189 of file Platform.h.
Constructor & Destructor Documentation
OptionGroupPlatformRSync() [1/2]
lldb_private::OptionGroupPlatformRSync::OptionGroupPlatformRSync () default
Referenced by operator=(), and OptionGroupPlatformRSync().
~OptionGroupPlatformRSync()
lldb_private::OptionGroupPlatformRSync::~OptionGroupPlatformRSync () override default
OptionGroupPlatformRSync() [2/2]
lldb_private::OptionGroupPlatformRSync::OptionGroupPlatformRSync (const OptionGroupPlatformRSync &) private delete
References OptionGroupPlatformRSync().
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > OptionGroupPlatformRSync::GetDefinitions () override virtual
Implements lldb_private::OptionGroup.
Definition at line 1319 of file Platform.cpp.
References g_rsync_option_table.
Referenced by SetOptionValue().
operator=()
const OptionGroupPlatformRSync & lldb_private::OptionGroupPlatformRSync::operator= (const OptionGroupPlatformRSync &) private delete
References OptionGroupPlatformRSync().
OptionParsingStarting()
void OptionGroupPlatformRSync::OptionParsingStarting (ExecutionContext * execution_context) override virtual
Implements lldb_private::OptionGroup.
Definition at line 1323 of file Platform.cpp.
References m_ignores_remote_hostname, m_rsync, m_rsync_opts, and m_rsync_prefix.
SetOptionValue()
lldb_private::Status OptionGroupPlatformRSync::SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext * execution_context) override virtual
Implements lldb_private::OptionGroup.
Definition at line 1332 of file Platform.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormat(), GetDefinitions(), m_ignores_remote_hostname, m_rsync, m_rsync_opts, and m_rsync_prefix.
Member Data Documentation
m_ignores_remote_hostname
bool lldb_private::OptionGroupPlatformRSync::m_ignores_remote_hostname
Definition at line 1208 of file Platform.h.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_rsync
bool lldb_private::OptionGroupPlatformRSync::m_rsync
Definition at line 1205 of file Platform.h.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_rsync_opts
std::string lldb_private::OptionGroupPlatformRSync::m_rsync_opts
Definition at line 1206 of file Platform.h.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_rsync_prefix
std::string lldb_private::OptionGroupPlatformRSync::m_rsync_prefix
Definition at line 1207 of file Platform.h.
Referenced by OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following files:
Platform.h
Platform.cpp