LLDB: lldb_private::SystemLifetimeManager Class Reference
lldb_private::SystemLifetimeManager Class Reference
#include <SystemLifetimeManager.h>
Public Member Functions
SystemLifetimeManager ()
~SystemLifetimeManager ()
llvm::Error Initialize (std::unique_ptr< SystemInitializer > initializer)
void Terminate ()
Private Member Functions
SystemLifetimeManager (const SystemLifetimeManager &other)=delete
SystemLifetimeManager & operator= (const SystemLifetimeManager &other)=delete
Private Attributes
std::recursive_mutex m_mutex
std::unique_ptr< SystemInitializer > m_initializer
bool m_initialized = false
Detailed Description
Definition at line 21 of file SystemLifetimeManager.h.
Constructor & Destructor Documentation
SystemLifetimeManager() [1/2]
SystemLifetimeManager::SystemLifetimeManager ()
Definition at line 17 of file SystemLifetimeManager.cpp.
References m_mutex.
Referenced by operator=(), and SystemLifetimeManager().
~SystemLifetimeManager()
SystemLifetimeManager::~SystemLifetimeManager ()
Definition at line 19 of file SystemLifetimeManager.cpp.
References m_initialized.
SystemLifetimeManager() [2/2]
lldb_private::SystemLifetimeManager::SystemLifetimeManager (const SystemLifetimeManager & other) private delete
References SystemLifetimeManager().
Member Function Documentation
Initialize()
llvm::Error SystemLifetimeManager::Initialize (std::unique_ptr< SystemInitializer > initializer)
Definition at line 24 of file SystemLifetimeManager.cpp.
References m_initialized, m_initializer, and m_mutex.
operator=()
SystemLifetimeManager & lldb_private::SystemLifetimeManager::operator= (const SystemLifetimeManager & other) private delete
References SystemLifetimeManager().
Terminate()
void SystemLifetimeManager::Terminate ()
Definition at line 41 of file SystemLifetimeManager.cpp.
References m_initialized, m_initializer, and m_mutex.
Member Data Documentation
m_initialized
bool lldb_private::SystemLifetimeManager::m_initialized = false private
Definition at line 32 of file SystemLifetimeManager.h.
Referenced by Initialize(), Terminate(), and ~SystemLifetimeManager().
m_initializer
std::unique_ptr<SystemInitializer> lldb_private::SystemLifetimeManager::m_initializer private
Definition at line 31 of file SystemLifetimeManager.h.
Referenced by Initialize(), and Terminate().
m_mutex
std::recursive_mutex lldb_private::SystemLifetimeManager::m_mutex private
Definition at line 30 of file SystemLifetimeManager.h.
Referenced by Initialize(), SystemLifetimeManager(), and Terminate().
The documentation for this class was generated from the following files:
SystemLifetimeManager.h
SystemLifetimeManager.cpp