LLDB: lldb_private::formatters::MsvcStlAtomicSyntheticFrontEnd Class Reference
lldb_private::formatters::MsvcStlAtomicSyntheticFrontEnd Class Reference
Public Member Functions
MsvcStlAtomicSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Attributes
ValueObject * m_storage = nullptr
CompilerType m_element_type
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
Definition at line 18 of file MsvcStlAtomic.cpp.
Constructor & Destructor Documentation
MsvcStlAtomicSyntheticFrontEnd()
lldb_private::formatters::MsvcStlAtomicSyntheticFrontEnd::MsvcStlAtomicSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
Definition at line 38 of file MsvcStlAtomic.cpp.
References m_element_type, lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd(), and Update().
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > lldb_private::formatters::MsvcStlAtomicSyntheticFrontEnd::CalculateNumChildren () override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 45 of file MsvcStlAtomic.cpp.
References m_storage.
GetChildAtIndex()
lldb::ValueObjectSP lldb_private::formatters::MsvcStlAtomicSyntheticFrontEnd::GetChildAtIndex (uint32_t idx) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 51 of file MsvcStlAtomic.cpp.
References m_element_type, and m_storage.
GetIndexOfChildWithName()
llvm::Expected< size_t > lldb_private::formatters::MsvcStlAtomicSyntheticFrontEnd::GetIndexOfChildWithName (ConstString name) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 84 of file MsvcStlAtomic.cpp.
References lldb_private::ConstString::AsCString().
Update()
lldb::ChildCacheState lldb_private::formatters::MsvcStlAtomicSyntheticFrontEnd::Update () override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 59 of file MsvcStlAtomic.cpp.
References lldb::eRefetch, lldb_private::CompilerType::GetDirectNestedTypeWithName(), lldb_private::CompilerType::GetTypeTemplateArgument(), lldb_private::SyntheticChildrenFrontEnd::m_backend, m_element_type, and m_storage.
Referenced by MsvcStlAtomicSyntheticFrontEnd().
Member Data Documentation
m_element_type
CompilerType lldb_private::formatters::MsvcStlAtomicSyntheticFrontEnd::m_element_type private
Definition at line 32 of file MsvcStlAtomic.cpp.
Referenced by GetChildAtIndex(), MsvcStlAtomicSyntheticFrontEnd(), and Update().
m_storage
ValueObject* lldb_private::formatters::MsvcStlAtomicSyntheticFrontEnd::m_storage = nullptr private
Definition at line 31 of file MsvcStlAtomic.cpp.
Referenced by CalculateNumChildren(), GetChildAtIndex(), and Update().
The documentation for this class was generated from the following file:
MsvcStlAtomic.cpp