LLDB: JITLoaderGDB Class Reference
JITLoaderGDB Class Reference
#include <JITLoaderGDB.h>
Public Member Functions
JITLoaderGDB (lldb_private::Process *process)
~JITLoaderGDB () override
llvm::StringRef GetPluginName () override
void DidAttach () override
Called after attaching a process.
void DidLaunch () override
Called after launching a process.
void ModulesDidLoad (lldb_private::ModuleList &module_list) override
Called after a new shared object has been loaded so that it can be probed for JIT entry point hooks.
Public Member Functions inherited from lldb_private::JITLoader
JITLoader (Process *process)
Construct with a process.
~JITLoader () override
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static lldb::JITLoaderSP CreateInstance (lldb_private::Process *process, bool force)
static void DebuggerInitialize (lldb_private::Debugger &debugger)
Static Public Member Functions inherited from lldb_private::JITLoader
static void LoadPlugins (Process *process, lldb_private::JITLoaderList &list)
Find a JIT loader plugin for a given process.
Private Types
typedef std::map< lldb::addr_t, const lldb::ModuleSP > JITObjectMap
Private Member Functions
lldb::addr_t GetSymbolAddress (lldb_private::ModuleList &module_list, lldb_private::ConstString name, lldb::SymbolType symbol_type) const
void SetJITBreakpoint (lldb_private::ModuleList &module_list)
bool DidSetJITBreakpoint () const
bool ReadJITDescriptor (bool all_entries)
template<typename ptr_t>
bool ReadJITDescriptorImpl (bool all_entries)
Static Private Member Functions
static bool JITDebugBreakpointHit (void *baton, lldb_private::StoppointCallbackContext *context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id)
static void ProcessStateChangedCallback (void *baton, lldb_private::Process *process, lldb::StateType state)
Private Attributes
JITObjectMap m_jit_objects
lldb::user_id_t m_jit_break_id
lldb::addr_t m_jit_descriptor_addr
Additional Inherited Members
Protected Attributes inherited from lldb_private::JITLoader
Process * m_process
Detailed Description
Definition at line 17 of file JITLoaderGDB.h.
Member Typedef Documentation
JITObjectMap
typedef std::map<lldb::addr_t, const lldb::ModuleSP> JITLoaderGDB::JITObjectMap private
Definition at line 71 of file JITLoaderGDB.h.
Constructor & Destructor Documentation
JITLoaderGDB()
JITLoaderGDB::JITLoaderGDB (lldb_private::Process * process)
Definition at line 146 of file JITLoaderGDB.cpp.
References lldb_private::JITLoader::JITLoader(), LLDB_INVALID_ADDRESS, LLDB_INVALID_BREAK_ID, m_jit_break_id, m_jit_descriptor_addr, and m_jit_objects.
Referenced by JITDebugBreakpointHit().
~JITLoaderGDB()
JITLoaderGDB::~JITLoaderGDB () override
Definition at line 151 of file JITLoaderGDB.cpp.
References LLDB_BREAK_ID_IS_VALID, m_jit_break_id, and lldb_private::JITLoader::m_process.
Member Function Documentation
CreateInstance()
JITLoaderSP JITLoaderGDB::CreateInstance (lldb_private::Process * process, bool force) static
Definition at line 412 of file JITLoaderGDB.cpp.
References lldb_private::Target::GetArchitecture(), GetGlobalPluginProperties(), lldb_private::Process::GetTarget(), and lldb_private::ArchSpec::GetTriple().
Referenced by Initialize(), and Terminate().
DebuggerInitialize()
void JITLoaderGDB::DebuggerInitialize (lldb_private::Debugger & debugger) static
Definition at line 156 of file JITLoaderGDB.cpp.
References lldb_private::PluginManager::CreateSettingForJITLoaderPlugin(), GetGlobalPluginProperties(), and lldb_private::PluginManager::GetSettingForJITLoaderPlugin().
Referenced by Initialize().
DidAttach()
void JITLoaderGDB::DidAttach () override virtual
Called after attaching a process.
Allow JITLoader plug-ins to execute some code after attaching to a process.
Implements lldb_private::JITLoader.
Definition at line 166 of file JITLoaderGDB.cpp.
References lldb_private::Target::GetImages(), lldb_private::JITLoader::m_process, and SetJITBreakpoint().
DidLaunch()
void JITLoaderGDB::DidLaunch () override virtual
Called after launching a process.
Allow JITLoader plug-ins to execute some code after the process has stopped for the first time on launch.
Implements lldb_private::JITLoader.
Definition at line 172 of file JITLoaderGDB.cpp.
References lldb_private::Target::GetImages(), lldb_private::JITLoader::m_process, and SetJITBreakpoint().
DidSetJITBreakpoint()
bool JITLoaderGDB::DidSetJITBreakpoint () const private
Definition at line 447 of file JITLoaderGDB.cpp.
References LLDB_BREAK_ID_IS_VALID, and m_jit_break_id.
Referenced by ModulesDidLoad(), and SetJITBreakpoint().
GetPluginDescriptionStatic()
llvm::StringRef JITLoaderGDB::GetPluginDescriptionStatic () static
Definition at line 432 of file JITLoaderGDB.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef JITLoaderGDB::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 38 of file JITLoaderGDB.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef JITLoaderGDB::GetPluginNameStatic () inline static
Definition at line 28 of file JITLoaderGDB.h.
Referenced by GetPluginName(), and Initialize().
GetSymbolAddress()
addr_t JITLoaderGDB::GetSymbolAddress (lldb_private::ModuleList & module_list, lldb_private::ConstString name, lldb::SymbolType symbol_type) const private
Definition at line 451 of file JITLoaderGDB.cpp.
References lldb_private::ModuleList::FindSymbolsWithNameAndType(), lldb_private::Symbol::GetAddress(), lldb_private::SymbolContextList::GetContextAtIndex(), lldb_private::Address::GetLoadAddress(), lldb_private::SymbolContextList::IsEmpty(), lldb_private::Address::IsValid(), LLDB_INVALID_ADDRESS, lldb_private::JITLoader::m_process, and lldb_private::SymbolContext::symbol.
Referenced by SetJITBreakpoint().
Initialize()
void JITLoaderGDB::Initialize () static
Definition at line 437 of file JITLoaderGDB.cpp.
References CreateInstance(), DebuggerInitialize(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
JITDebugBreakpointHit()
bool JITLoaderGDB::JITDebugBreakpointHit (void * baton, lldb_private::StoppointCallbackContext * context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id) static private
Definition at line 216 of file JITLoaderGDB.cpp.
References lldb_private::GetLog(), lldb_private::JITLoader, JITLoaderGDB(), LLDB_LOGF, and ReadJITDescriptor().
Referenced by SetJITBreakpoint().
ModulesDidLoad()
void JITLoaderGDB::ModulesDidLoad (lldb_private::ModuleList & module_list) override virtual
Called after a new shared object has been loaded so that it can be probed for JIT entry point hooks.
Implements lldb_private::JITLoader.
Definition at line 178 of file JITLoaderGDB.cpp.
References DidSetJITBreakpoint(), lldb_private::JITLoader::m_process, and SetJITBreakpoint().
ProcessStateChangedCallback()
void JITLoaderGDB::ProcessStateChangedCallback (void * baton, lldb_private::Process * process, lldb::StateType state) static private
ReadJITDescriptor()
bool JITLoaderGDB::ReadJITDescriptor (bool all_entries) private
Definition at line 272 of file JITLoaderGDB.cpp.
References lldb_private::JITLoader::m_process, and ReadJITDescriptorImpl().
Referenced by JITDebugBreakpointHit(), and SetJITBreakpoint().
ReadJITDescriptorImpl()
template<typename ptr_t> bool JITLoaderGDB::ReadJITDescriptorImpl (bool all_entries) private
Definition at line 280 of file JITLoaderGDB.cpp.
References lldb_private::ModuleList::Append(), lldb_private::ModuleList::AppendIfNeeded(), error(), lldb_private::ObjectFile::eTypeJIT, lldb_private::Target::GetImages(), lldb_private::GetLog(), lldb_private::SectionList::GetSectionAtIndex(), lldb_private::ObjectFile::GetSectionList(), lldb_private::SectionList::GetSize(), lldb_private::JITLoader, LLDB_INVALID_ADDRESS, LLDB_LOG_ERROR, LLDB_LOGF, m_jit_descriptor_addr, m_jit_objects, lldb_private::JITLoader::m_process, lldb_private::Target::ModulesDidLoad(), ReadJITEntry(), lldb_private::ModuleList::Remove(), lldb_private::Target::SetSectionUnloaded(), and updateSectionLoadAddress().
Referenced by ReadJITDescriptor().
SetJITBreakpoint()
void JITLoaderGDB::SetJITBreakpoint (lldb_private::ModuleList & module_list) private
Definition at line 184 of file JITLoaderGDB.cpp.
References DidSetJITBreakpoint(), lldb::eSymbolTypeCode, lldb::eSymbolTypeData, lldb_private::Stoppoint::GetID(), lldb_private::GetLog(), GetSymbolAddress(), JITDebugBreakpointHit(), lldb_private::JITLoader, LLDB_INVALID_ADDRESS, LLDB_LOGF, m_jit_break_id, m_jit_descriptor_addr, lldb_private::JITLoader::m_process, ReadJITDescriptor(), lldb_private::Breakpoint::SetBreakpointKind(), and lldb_private::Breakpoint::SetCallback().
Referenced by DidAttach(), DidLaunch(), and ModulesDidLoad().
Terminate()
void JITLoaderGDB::Terminate () static
Definition at line 443 of file JITLoaderGDB.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Member Data Documentation
m_jit_break_id
lldb::user_id_t JITLoaderGDB::m_jit_break_id private
Definition at line 74 of file JITLoaderGDB.h.
Referenced by DidSetJITBreakpoint(), JITLoaderGDB(), SetJITBreakpoint(), and ~JITLoaderGDB().
m_jit_descriptor_addr
lldb::addr_t JITLoaderGDB::m_jit_descriptor_addr private
Definition at line 75 of file JITLoaderGDB.h.
Referenced by JITLoaderGDB(), ReadJITDescriptorImpl(), and SetJITBreakpoint().
m_jit_objects
JITObjectMap JITLoaderGDB::m_jit_objects private
Definition at line 72 of file JITLoaderGDB.h.
Referenced by JITLoaderGDB(), and ReadJITDescriptorImpl().
The documentation for this class was generated from the following files:
JITLoaderGDB.h
JITLoaderGDB.cpp