LLDB: lldb_private::ThreadPlanAssemblyTracer Class Reference
lldb_private::ThreadPlanAssemblyTracer Class Reference
#include <ThreadPlanTracer.h>
Public Member Functions
ThreadPlanAssemblyTracer (Thread &thread, lldb::StreamSP &stream_sp)
ThreadPlanAssemblyTracer (Thread &thread)
~ThreadPlanAssemblyTracer () override
void TracingStarted () override
void TracingEnded () override
void Log () override
Public Member Functions inherited from lldb_private::ThreadPlanTracer
ThreadPlanTracer (Thread &thread, lldb::StreamSP &stream_sp)
ThreadPlanTracer (Thread &thread)
virtual ~ThreadPlanTracer ()=default
bool EnableTracing (bool value)
bool TracingEnabled ()
Thread & GetThread ()
Private Member Functions
Disassembler * GetDisassembler ()
TypeFromUser GetIntPointerType ()
Private Attributes
lldb::DisassemblerSP m_disassembler_sp
TypeFromUser m_intptr_type
std::vector< RegisterValue > m_register_values
lldb::DataBufferSP m_buffer_sp
Additional Inherited Members
Public Types inherited from lldb_private::ThreadPlanTracer
enum ThreadPlanTracerStyle { eLocation = 0 , eStateChange , eCheckFrames , ePython }
Protected Member Functions inherited from lldb_private::ThreadPlanTracer
lldb::StreamSP GetLogStreamSP ()
Protected Attributes inherited from lldb_private::ThreadPlanTracer
Process & m_process
lldb::tid_t m_tid
Detailed Description
Definition at line 71 of file ThreadPlanTracer.h.
Constructor & Destructor Documentation
ThreadPlanAssemblyTracer() [1/2]
ThreadPlanAssemblyTracer::ThreadPlanAssemblyTracer (Thread & thread, lldb::StreamSP & stream_sp)
Definition at line 87 of file ThreadPlanTracer.cpp.
References m_disassembler_sp, m_intptr_type, m_register_values, and lldb_private::ThreadPlanTracer::ThreadPlanTracer().
ThreadPlanAssemblyTracer() [2/2]
ThreadPlanAssemblyTracer::ThreadPlanAssemblyTracer (Thread & thread)
Definition at line 92 of file ThreadPlanTracer.cpp.
References m_disassembler_sp, m_intptr_type, m_register_values, and lldb_private::ThreadPlanTracer::ThreadPlanTracer().
~ThreadPlanAssemblyTracer()
ThreadPlanAssemblyTracer::~ThreadPlanAssemblyTracer () override default
Member Function Documentation
GetDisassembler()
Disassembler * ThreadPlanAssemblyTracer::GetDisassembler () private
Definition at line 96 of file ThreadPlanTracer.cpp.
References lldb_private::Disassembler::FindPlugin(), m_disassembler_sp, and lldb_private::ThreadPlanTracer::m_process.
Referenced by Log().
GetIntPointerType()
TypeFromUser ThreadPlanAssemblyTracer::GetIntPointerType () private
Definition at line 104 of file ThreadPlanTracer.cpp.
References lldb::eEncodingUint, lldb::eLanguageTypeC, lldb_private::GetLog(), LLDB_LOG_ERROR, m_intptr_type, lldb_private::ThreadPlanTracer::m_process, and lldb_private::Types.
Referenced by Log().
Log()
void ThreadPlanAssemblyTracer::Log () override virtual
Reimplemented from lldb_private::ThreadPlanTracer.
Definition at line 131 of file ThreadPlanTracer.cpp.
References lldb_private::Disassembler::DecodeInstructions(), lldb_private::Address::Dump(), lldb_private::Instruction::Dump(), lldb_private::DumpRegisterValue(), lldb_private::Address::DumpStyleModuleWithFileAddress, lldb_private::Address::DumpStyleResolvedDescription, lldb::eFormatDefault, lldb_private::RegisterValue::eTypeInvalid, lldb_private::ABI::GetArgumentValues(), GetDisassembler(), lldb_private::InstructionList::GetInstructionAtIndex(), lldb_private::Disassembler::GetInstructionList(), GetIntPointerType(), lldb_private::ThreadPlanTracer::GetLogStreamSP(), lldb_private::InstructionList::GetMaxOpcocdeByteSize(), lldb_private::RegisterContext::GetPC(), lldb_private::Thread::GetRegisterContext(), lldb_private::RegisterContext::GetRegisterCount(), lldb_private::RegisterContext::GetRegisterInfoAtIndex(), lldb_private::Value::GetScalar(), lldb_private::InstructionList::GetSize(), lldb_private::ThreadPlanTracer::GetThread(), lldb_private::RegisterValue::GetType(), lldb_private::ValueList::GetValueAtIndex(), lldb_private::CompilerType::IsValid(), lldb_private::ThreadPlanTracer::m_process, m_register_values, pc, lldb_private::ValueList::PushValue(), lldb_private::RegisterContext::ReadRegister(), lldb_private::Value::Scalar, lldb_private::Value::SetCompilerType(), lldb_private::Value::SetValueType(), lldb_private::Status::Success(), and lldb_private::Scalar::ULongLong().
TracingEnded()
void ThreadPlanAssemblyTracer::TracingEnded () override virtual
Reimplemented from lldb_private::ThreadPlanTracer.
Definition at line 129 of file ThreadPlanTracer.cpp.
References m_register_values.
TracingStarted()
void ThreadPlanAssemblyTracer::TracingStarted () override virtual
Reimplemented from lldb_private::ThreadPlanTracer.
Definition at line 126 of file ThreadPlanTracer.cpp.
Member Data Documentation
m_buffer_sp
lldb::DataBufferSP lldb_private::ThreadPlanAssemblyTracer::m_buffer_sp private
Definition at line 89 of file ThreadPlanTracer.h.
m_disassembler_sp
lldb::DisassemblerSP lldb_private::ThreadPlanAssemblyTracer::m_disassembler_sp private
Definition at line 86 of file ThreadPlanTracer.h.
Referenced by GetDisassembler(), ThreadPlanAssemblyTracer(), and ThreadPlanAssemblyTracer().
m_intptr_type
TypeFromUser lldb_private::ThreadPlanAssemblyTracer::m_intptr_type private
Definition at line 87 of file ThreadPlanTracer.h.
Referenced by GetIntPointerType(), ThreadPlanAssemblyTracer(), and ThreadPlanAssemblyTracer().
m_register_values
std::vector<RegisterValue> lldb_private::ThreadPlanAssemblyTracer::m_register_values private
Definition at line 88 of file ThreadPlanTracer.h.
Referenced by Log(), ThreadPlanAssemblyTracer(), ThreadPlanAssemblyTracer(), and TracingEnded().
The documentation for this class was generated from the following files:
ThreadPlanTracer.h
ThreadPlanTracer.cpp