LLDB: ABISysV_x86_64 Class Reference
ABISysV_x86_64 Class Reference
#include <ABISysV_x86_64.h>
Public Member Functions
~ABISysV_x86_64 () override=default
size_t GetRedZoneSize () const override
bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override
bool GetArgumentValues (lldb_private::Thread &thread, lldb_private::ValueList &values) const override
lldb_private::Status SetReturnValueObject (lldb::StackFrameSP &frame_sp, lldb::ValueObjectSP &new_value) override
lldb::ValueObjectSP GetReturnValueObjectImpl (lldb_private::Thread &thread, lldb_private::CompilerType &type) const override
lldb::UnwindPlanSP CreateFunctionEntryUnwindPlan () override
lldb::UnwindPlanSP CreateDefaultUnwindPlan () override
bool RegisterIsVolatile (const lldb_private::RegisterInfo *reg_info) override
bool CallFrameAddressIsValid (lldb::addr_t cfa) override
bool CodeAddressIsValid (lldb::addr_t pc) override
bool GetPointerReturnRegister (const char *&name) override
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::MCBasedABI
void AugmentRegisterInfo (std::vector< DynamicRegisterInfo::Register > &regs) override
Public Member Functions inherited from lldb_private::ABI
~ABI () override
virtual bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::Type &prototype, llvm::ArrayRef< CallArgument > args) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, CompilerType &type, bool persistent=true) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, llvm::Type &type, bool persistent=true) const
virtual bool GetFallbackRegisterLocation (const RegisterInfo *reg_info, UnwindPlan::Row::AbstractRegisterLocation &unwind_regloc)
virtual lldb::addr_t FixAnyAddress (lldb::addr_t pc)
Use this method when you do not know, or do not care what kind of address you are fixing.
llvm::MCRegisterInfo & GetMCRegisterInfo ()
virtual uint64_t GetStackFrameSize ()
virtual lldb::addr_t FixCodeAddress (lldb::addr_t pc)
Some targets might use bits in a code address to indicate a mode switch.
virtual lldb::addr_t FixDataAddress (lldb::addr_t pc)
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static lldb::ABISP CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec &arch)
static llvm::StringRef GetPluginNameStatic ()
Static Public Member Functions inherited from ABIX86
static void Initialize ()
static void Terminate ()
Static Public Member Functions inherited from lldb_private::MCBasedABI
static void MapRegisterName (std::string &reg, llvm::StringRef from_prefix, llvm::StringRef to_prefix)
If the register name is of the form "<from_prefix>[<number>]" then change the name to "<to_prefix>[<number>]".
Static Public Member Functions inherited from lldb_private::ABI
static lldb::ABISP FindPlugin (lldb::ProcessSP process_sp, const ArchSpec &arch)
Protected Member Functions
void CreateRegisterMapIfNeeded ()
lldb::ValueObjectSP GetReturnValueObjectSimple (lldb_private::Thread &thread, lldb_private::CompilerType &ast_type) const
bool RegisterIsCalleeSaved (const lldb_private::RegisterInfo *reg_info)
uint32_t GetGenericNum (llvm::StringRef reg) override
Return the generic number of the given register.
Protected Member Functions inherited from ABIX86_64
std::string GetMCName (std::string name) override
For the given (capitalized) lldb register name, return the name of this register in the MCRegisterInfo struct.
Protected Member Functions inherited from ABIX86
void AugmentRegisterInfo (std::vector< lldb_private::DynamicRegisterInfo::Register > &regs) override
Protected Member Functions inherited from lldb_private::MCBasedABI
virtual std::pair< uint32_t, uint32_t > GetEHAndDWARFNums (llvm::StringRef reg)
Return eh_frame and dwarf numbers for the given register.
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Protected Member Functions inherited from lldb_private::ABI
virtual lldb::ValueObjectSP GetReturnValueObjectImpl (Thread &thread, llvm::Type &ir_type) const
lldb::ProcessSP GetProcessSP () const
Request to get a Process shared pointer.
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Additional Inherited Members
Static Protected Member Functions inherited from lldb_private::ABI
static std::unique_ptr< llvm::MCRegisterInfo > MakeMCRegisterInfo (const ArchSpec &arch)
Utility function to construct a MCRegisterInfo using the ArchSpec triple.
Protected Attributes inherited from lldb_private::ABI
lldb::ProcessWP m_process_wp
std::unique_ptr< llvm::MCRegisterInfo > m_mc_register_info_up
Detailed Description
Definition at line 14 of file ABISysV_x86_64.h.
Constructor & Destructor Documentation
~ABISysV_x86_64()
ABISysV_x86_64::~ABISysV_x86_64 () override default
References sp.
Member Function Documentation
CallFrameAddressIsValid()
bool ABISysV_x86_64::CallFrameAddressIsValid (lldb::addr_t cfa) inline override virtual
Implements lldb_private::ABI.
Definition at line 53 of file ABISysV_x86_64.h.
CodeAddressIsValid()
bool ABISysV_x86_64::CodeAddressIsValid (lldb::addr_t pc) inline override virtual
Implements lldb_private::ABI.
Definition at line 62 of file ABISysV_x86_64.h.
References pc.
CreateDefaultUnwindPlan()
UnwindPlanSP ABISysV_x86_64::CreateDefaultUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 876 of file ABISysV_x86_64.cpp.
References dwarf_rbp, dwarf_rip, dwarf_rsp, lldb_private::eLazyBoolNo, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), lldb_private::UnwindPlan::Row::SetOffset(), lldb_private::UnwindPlan::Row::SetRegisterLocationToAtCFAPlusOffset(), lldb_private::UnwindPlan::Row::SetRegisterLocationToIsCFAPlusOffset(), and lldb_private::UnwindPlan::Row::SetUnspecifiedRegistersAreUndefined().
CreateFunctionEntryUnwindPlan()
UnwindPlanSP ABISysV_x86_64::CreateFunctionEntryUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 855 of file ABISysV_x86_64.cpp.
References dwarf_rip, dwarf_rsp, lldb_private::eLazyBoolNo, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), lldb_private::UnwindPlan::Row::SetRegisterLocationToAtCFAPlusOffset(), and lldb_private::UnwindPlan::Row::SetRegisterLocationToIsCFAPlusOffset().
CreateInstance()
ABISP ABISysV_x86_64::CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec & arch) static
Definition at line 72 of file ABISysV_x86_64.cpp.
References lldb_private::ArchSpec::GetTriple(), and lldb_private::ABI::MakeMCRegisterInfo().
Referenced by Initialize(), and Terminate().
CreateRegisterMapIfNeeded()
void ABISysV_x86_64::CreateRegisterMapIfNeeded () protected
GetArgumentValues()
bool ABISysV_x86_64::GetArgumentValues (lldb_private::Thread & thread, lldb_private::ValueList & values) const override virtual
Implements lldb_private::ABI.
Definition at line 219 of file ABISysV_x86_64.cpp.
References lldb::eRegisterKindGeneric, lldb::eRegisterKindLLDB, lldb_private::CompilerType::GetBitSize(), lldb_private::Value::GetCompilerType(), lldb_private::RegisterContext::GetRegisterInfo(), lldb_private::Value::GetScalar(), lldb_private::ValueList::GetSize(), lldb_private::RegisterContext::GetSP(), lldb_private::ValueList::GetValueAtIndex(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), lldb_private::CompilerType::IsPointerType(), lldb_private::RegisterInfo::kinds, LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_ARG2, LLDB_REGNUM_GENERIC_ARG3, LLDB_REGNUM_GENERIC_ARG4, LLDB_REGNUM_GENERIC_ARG5, LLDB_REGNUM_GENERIC_ARG6, ReadIntegerArgument(), and sp.
GetGenericNum()
uint32_t ABISysV_x86_64::GetGenericNum (llvm::StringRef reg) override protected virtual
Return the generic number of the given register.
Implements lldb_private::MCBasedABI.
Definition at line 927 of file ABISysV_x86_64.cpp.
References LLDB_INVALID_REGNUM, LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_ARG2, LLDB_REGNUM_GENERIC_ARG3, LLDB_REGNUM_GENERIC_ARG4, LLDB_REGNUM_GENERIC_ARG5, LLDB_REGNUM_GENERIC_ARG6, LLDB_REGNUM_GENERIC_FLAGS, LLDB_REGNUM_GENERIC_FP, LLDB_REGNUM_GENERIC_PC, and LLDB_REGNUM_GENERIC_SP.
GetPluginName()
llvm::StringRef ABISysV_x86_64::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 81 of file ABISysV_x86_64.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef ABISysV_x86_64::GetPluginNameStatic () inline static
Definition at line 78 of file ABISysV_x86_64.h.
Referenced by GetPluginName(), and Initialize().
GetPointerReturnRegister()
bool ABISysV_x86_64::GetPointerReturnRegister (const char *& name) override virtual
Reimplemented from lldb_private::ABI.
Definition at line 62 of file ABISysV_x86_64.cpp.
GetRedZoneSize()
size_t ABISysV_x86_64::GetRedZoneSize () const override virtual
Implements lldb_private::ABI.
Definition at line 67 of file ABISysV_x86_64.cpp.
GetReturnValueObjectImpl()
ValueObjectSP ABISysV_x86_64::GetReturnValueObjectImpl (lldb_private::Thread & thread, lldb_private::CompilerType & type) const override virtual
Implements lldb_private::ABI.
Definition at line 614 of file ABISysV_x86_64.cpp.
References lldb_private::DataExtractor::CopyByteOrderedData(), lldb_private::ValueObjectConstResult::Create(), lldb_private::ValueObjectMemory::Create(), lldb::eRegisterKindLLDB, FlattenAggregateType(), lldb_private::ArchSpec::GetAddressByteSize(), lldb_private::Target::GetArchitecture(), lldb_private::CompilerType::GetBitSize(), lldb_private::ArchSpec::GetByteOrder(), lldb_private::CompilerType::GetByteSize(), lldb_private::DataExtractor::GetByteSize(), lldb_private::RegisterValue::GetData(), GetReturnValueObjectSimple(), lldb_private::ExecutionContext::GetTargetPtr(), lldb_private::CompilerType::GetTypeInfo(), lldb_private::CompilerType::GetTypeSystem(), lldb_private::CompilerType::IsAggregateType(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), and lldb_private::CompilerType::IsPointerType().
GetReturnValueObjectSimple()
ValueObjectSP ABISysV_x86_64::GetReturnValueObjectSimple (lldb_private::Thread & thread, lldb_private::CompilerType & ast_type) const protected
Definition at line 384 of file ABISysV_x86_64.cpp.
References lldb_private::RegisterInfo::byte_size, lldb_private::ValueObjectConstResult::Create(), lldb::eRegisterKindLLDB, error(), lldb_private::RegisterValue::GetAsMemoryData(), lldb_private::CompilerType::GetByteSize(), lldb_private::RegisterValue::GetData(), lldb_private::DataExtractor::GetDouble(), lldb_private::DataExtractor::GetFloat(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::Value::GetScalar(), lldb_private::CompilerType::GetTypeInfo(), lldb_private::RegisterInfo::kinds, lldb_private::RegisterContext::ReadRegister(), lldb_private::Value::Scalar, lldb_private::Value::SetCompilerType(), lldb_private::Value::SetValueType(), and UINT32_MAX.
Referenced by GetReturnValueObjectImpl().
Initialize()
void ABISysV_x86_64::Initialize () static
Definition at line 944 of file ABISysV_x86_64.cpp.
References CreateInstance(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Referenced by ABIX86::Initialize().
PrepareTrivialCall()
bool ABISysV_x86_64::PrepareTrivialCall (lldb_private::Thread & thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override virtual
Implements lldb_private::ABI.
Definition at line 111 of file ABISysV_x86_64.cpp.
References lldb::eRegisterKindGeneric, error(), lldb_private::Expressions, lldb_private::GetLog(), lldb_private::RegisterContext::GetRegisterInfo(), lldb_private::StreamString::GetString(), LLDB_LOGF, LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_SP, lldb_private::RegisterInfo::name, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), lldb_private::Log::PutString(), sp, and lldb_private::RegisterContext::WriteRegisterFromUnsigned().
RegisterIsCalleeSaved()
bool ABISysV_x86_64::RegisterIsCalleeSaved (const lldb_private::RegisterInfo * reg_info) protected
Definition at line 914 of file ABISysV_x86_64.cpp.
References lldb_private::RegisterInfo::name.
Referenced by RegisterIsVolatile().
RegisterIsVolatile()
bool ABISysV_x86_64::RegisterIsVolatile (const lldb_private::RegisterInfo * reg_info) override virtual
Implements lldb_private::ABI.
Definition at line 901 of file ABISysV_x86_64.cpp.
References RegisterIsCalleeSaved().
SetReturnValueObject()
Status ABISysV_x86_64::SetReturnValueObject (lldb::StackFrameSP & frame_sp, lldb::ValueObjectSP & new_value) override virtual
Implements lldb_private::ABI.
Definition at line 293 of file ABISysV_x86_64.cpp.
References lldb_private::Status::AsCString(), lldb_private::DataExtractor::CopyByteOrderedData(), error(), lldb_private::Status::Fail(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::CompilerType::GetBitSize(), lldb_private::DataExtractor::GetByteOrder(), lldb_private::DataExtractor::GetMaxU64(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), lldb_private::CompilerType::IsPointerType(), lldb_private::CompilerType::IsRealFloatingPointType(), lldb_private::RegisterValue::SetBytes(), lldb_private::RegisterContext::WriteRegister(), and lldb_private::RegisterContext::WriteRegisterFromUnsigned().
Terminate()
void ABISysV_x86_64::Terminate () static
Definition at line 949 of file ABISysV_x86_64.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Referenced by ABIX86::Terminate().
The documentation for this class was generated from the following files:
ABISysV_x86_64.h
ABISysV_x86_64.cpp