LLDB: lldb_private::CommandOptionsProcessLaunch Class Reference
lldb_private::CommandOptionsProcessLaunch Class Reference
#include <CommandOptionsProcessLaunch.h>
Public Member Functions
CommandOptionsProcessLaunch ()
~CommandOptionsProcessLaunch () override=default
lldb_private::Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, lldb_private::ExecutionContext *execution_context) override
void OptionParsingStarting (lldb_private::ExecutionContext *execution_context) override
llvm::ArrayRef< lldb_private::OptionDefinition > GetDefinitions () override
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Public Attributes
lldb_private::ProcessLaunchInfo launch_info
lldb_private::LazyBool disable_aslr
Detailed Description
Definition at line 19 of file CommandOptionsProcessLaunch.h.
Constructor & Destructor Documentation
CommandOptionsProcessLaunch()
lldb_private::CommandOptionsProcessLaunch::CommandOptionsProcessLaunch () inline
Definition at line 21 of file CommandOptionsProcessLaunch.h.
References OptionParsingStarting().
~CommandOptionsProcessLaunch()
lldb_private::CommandOptionsProcessLaunch::~CommandOptionsProcessLaunch () override default
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > CommandOptionsProcessLaunch::GetDefinitions () override virtual
Implements lldb_private::OptionGroup.
Definition at line 152 of file CommandOptionsProcessLaunch.cpp.
OptionParsingStarting()
void lldb_private::CommandOptionsProcessLaunch::OptionParsingStarting (lldb_private::ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 33 of file CommandOptionsProcessLaunch.h.
References disable_aslr, lldb_private::eLazyBoolCalculate, and launch_info.
Referenced by CommandOptionsProcessLaunch().
SetOptionValue()
Status CommandOptionsProcessLaunch::SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, lldb_private::ExecutionContext * execution_context) override virtual
Implements lldb_private::OptionGroup.
Definition at line 31 of file CommandOptionsProcessLaunch.cpp.
References lldb_private::FileSystem::DEV_NULL, disable_aslr, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::Platform::GetAugmentedArchSpec(), lldb_private::ExecutionContext::GetTargetSP(), launch_info, lldb_private::FileAction::Open(), and lldb_private::OptionArgParser::ToBoolean().
Member Data Documentation
disable_aslr
lldb_private::LazyBool lldb_private::CommandOptionsProcessLaunch::disable_aslr
Definition at line 44 of file CommandOptionsProcessLaunch.h.
Referenced by OptionParsingStarting(), and SetOptionValue().
launch_info
lldb_private::ProcessLaunchInfo lldb_private::CommandOptionsProcessLaunch::launch_info
Definition at line 43 of file CommandOptionsProcessLaunch.h.
Referenced by OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following files:
CommandOptionsProcessLaunch.h
CommandOptionsProcessLaunch.cpp