LLDB: lldb_private::StructuredData::String Class Reference
lldb_private::StructuredData::String Class Reference
#include <StructuredData.h>
Public Member Functions
String ()
String (llvm::StringRef S)
void SetValue (llvm::StringRef S)
llvm::StringRef GetValue ()
void Serialize (llvm::json::OStream &s) const override
void GetDescription (lldb_private::Stream &s) const override
Public Member Functions inherited from lldb_private::StructuredData::Object
Object (lldb::StructuredDataType t=lldb::eStructuredDataTypeInvalid)
virtual ~Object ()=default
virtual bool IsValid () const
virtual void Clear ()
lldb::StructuredDataType GetType () const
void SetType (lldb::StructuredDataType t)
Array * GetAsArray ()
Dictionary * GetAsDictionary ()
UnsignedInteger * GetAsUnsignedInteger ()
SignedInteger * GetAsSignedInteger ()
uint64_t GetUnsignedIntegerValue (uint64_t fail_value=0)
int64_t GetSignedIntegerValue (int64_t fail_value=0)
Float * GetAsFloat ()
double GetFloatValue (double fail_value=0.0)
Boolean * GetAsBoolean ()
bool GetBooleanValue (bool fail_value=false)
String * GetAsString ()
llvm::StringRef GetStringValue (const char *fail_value=nullptr)
Generic * GetAsGeneric ()
ObjectSP GetObjectForDotSeparatedPath (llvm::StringRef path)
void DumpToStdout (bool pretty_print=true) const
void Dump (lldb_private::Stream &s, bool pretty_print=true) const
Protected Attributes
std::string m_value
Detailed Description
Definition at line 366 of file StructuredData.h.
Constructor & Destructor Documentation
String() [1/2]
lldb_private::StructuredData::String::String () inline
Definition at line 368 of file StructuredData.h.
References lldb_private::StructuredData::Object::Object().
String() [2/2]
lldb_private::StructuredData::String::String (llvm::StringRef S) inline explicit
Definition at line 369 of file StructuredData.h.
References m_value, and lldb_private::StructuredData::Object::Object().
Member Function Documentation
GetDescription()
void StructuredData::String::GetDescription (lldb_private::Stream & s) const override virtual
Reimplemented from lldb_private::StructuredData::Object.
Definition at line 199 of file StructuredData.cpp.
References m_value, and lldb_private::Stream::Printf().
GetValue()
llvm::StringRef lldb_private::StructuredData::String::GetValue () inline
Definition at line 374 of file StructuredData.h.
References m_value.
Referenced by lldb_private::StructuredData::Object::GetStringValue().
Serialize()
void StructuredData::String::Serialize (llvm::json::OStream & s) const override virtual
Implements lldb_private::StructuredData::Object.
Definition at line 159 of file StructuredData.cpp.
References m_value.
SetValue()
void lldb_private::StructuredData::String::SetValue (llvm::StringRef S) inline
Definition at line 372 of file StructuredData.h.
References m_value.
Member Data Documentation
m_value
std::string lldb_private::StructuredData::String::m_value protected
Definition at line 381 of file StructuredData.h.
Referenced by GetDescription(), GetValue(), Serialize(), SetValue(), and String().
The documentation for this class was generated from the following files:
StructuredData.h
StructuredData.cpp