LLDB: CommandObjectProcessMinidumpDump Class Reference
CommandObjectProcessMinidumpDump Class Reference
Public Member Functions
CommandObjectProcessMinidumpDump (CommandInterpreter &interpreter)
~CommandObjectProcessMinidumpDump () override=default
Options * GetOptions () override
void DoExecute (Args &command, CommandReturnObject &result) override
Public Member Functions inherited from lldb_private::CommandObjectParsed
CommandObjectParsed (CommandInterpreter &interpreter, const char *name, const char *help=nullptr, const char *syntax=nullptr, uint32_t flags=0)
~CommandObjectParsed () override=default
void Execute (const char *args_string, CommandReturnObject &result) override
Public Member Functions inherited from lldb_private::CommandObject
CommandObject (CommandInterpreter &interpreter, llvm::StringRef name, llvm::StringRef help="", llvm::StringRef syntax="", uint32_t flags=0)
virtual ~CommandObject ()=default
CommandInterpreter & GetCommandInterpreter ()
Debugger & GetDebugger ()
virtual llvm::StringRef GetHelp ()
virtual llvm::StringRef GetHelpLong ()
virtual llvm::StringRef GetSyntax ()
llvm::StringRef GetCommandName () const
virtual void SetHelp (llvm::StringRef str)
virtual void SetHelpLong (llvm::StringRef str)
void SetSyntax (llvm::StringRef str)
virtual bool IsRemovable () const
virtual bool IsMultiwordObject ()
bool IsUserCommand ()
void SetIsUserCommand (bool is_user)
virtual CommandObjectMultiword * GetAsMultiwordCommand ()
virtual bool IsAlias ()
virtual bool IsDashDashCommand ()
virtual lldb::CommandObjectSP GetSubcommandSP (llvm::StringRef sub_cmd, StringList *matches=nullptr)
virtual lldb::CommandObjectSP GetSubcommandSPExact (llvm::StringRef sub_cmd)
virtual CommandObject * GetSubcommandObject (llvm::StringRef sub_cmd, StringList *matches=nullptr)
void FormatLongHelpText (Stream &output_strm, llvm::StringRef long_help)
void GenerateHelpText (CommandReturnObject &result)
virtual void GenerateHelpText (Stream &result)
virtual bool LoadSubCommand (llvm::StringRef cmd_name, const lldb::CommandObjectSP &command_obj)
virtual llvm::Error LoadUserSubcommand (llvm::StringRef cmd_name, const lldb::CommandObjectSP &command_obj, bool can_replace)
virtual bool WantsCompletion ()
void AddSimpleArgumentList (lldb::CommandArgumentType arg_type, ArgumentRepetitionType repetition_type=eArgRepeatPlain)
void AddIDsArgumentData (IDType type)
int GetNumArgumentEntries ()
CommandArgumentEntry * GetArgumentEntryAtIndex (int idx)
void GetFormattedCommandArguments (Stream &str, uint32_t opt_set_mask=LLDB_OPT_SET_ALL)
bool ParseOptions (Args &args, CommandReturnObject &result)
void SetCommandName (llvm::StringRef name)
virtual void HandleCompletion (CompletionRequest &request)
This default version handles calling option argument completions and then calls HandleArgumentCompletion if the cursor is on an argument, not an option.
virtual void HandleArgumentCompletion (CompletionRequest &request, OptionElementVector &opt_element_vector)
The default version handles argument definitions that have only one argument type, and use one of the argument types that have an entry in the CommonCompletions.
bool HelpTextContainsWord (llvm::StringRef search_word, bool search_short_help=true, bool search_long_help=true, bool search_syntax=true, bool search_options=true)
Flags & GetFlags ()
The flags accessor.
const Flags & GetFlags () const
The flags const accessor.
virtual std::optional< std::string > GetRepeatCommand (Args &current_command_args, uint32_t index)
Get the command that appropriate for a "repeat" of the current command.
bool HasOverrideCallback () const
void SetOverrideCallback (lldb::CommandOverrideCallback callback, void *baton)
void SetOverrideCallback (lldb_private::CommandOverrideCallbackWithResult callback, void *baton)
bool InvokeOverrideCallback (const char **argv, CommandReturnObject &result)
void SetOriginalCommandString (std::string s)
Set the command input as it appeared in the terminal.
Private Member Functions
void SetDefaultOptionsIfNoneAreSet ()
bool DumpAll () const
bool DumpDirectory () const
bool DumpLinux () const
bool DumpLinuxCPUInfo () const
bool DumpLinuxProcStatus () const
bool DumpLinuxProcStat () const
bool DumpLinuxLSBRelease () const
bool DumpLinuxCMDLine () const
bool DumpLinuxEnviron () const
bool DumpLinuxAuxv () const
bool DumpLinuxMaps () const
bool DumpLinuxProcUptime () const
bool DumpLinuxProcFD () const
bool DumpFacebook () const
bool DumpFacebookAppData () const
bool DumpFacebookBuildID () const
bool DumpFacebookVersionName () const
bool DumpFacebookJavaStack () const
bool DumpFacebookDalvikInfo () const
bool DumpFacebookUnwindSymbols () const
bool DumpFacebookErrorLog () const
bool DumpFacebookAppStateLog () const
bool DumpFacebookAbortReason () const
bool DumpFacebookThreadName () const
bool DumpFacebookLogcat () const
Private Attributes
OptionGroupOptions m_option_group
OptionGroupBoolean m_dump_all
OptionGroupBoolean m_dump_directory
OptionGroupBoolean m_dump_linux_cpuinfo
OptionGroupBoolean m_dump_linux_proc_status
OptionGroupBoolean m_dump_linux_lsb_release
OptionGroupBoolean m_dump_linux_cmdline
OptionGroupBoolean m_dump_linux_environ
OptionGroupBoolean m_dump_linux_auxv
OptionGroupBoolean m_dump_linux_maps
OptionGroupBoolean m_dump_linux_proc_stat
OptionGroupBoolean m_dump_linux_proc_uptime
OptionGroupBoolean m_dump_linux_proc_fd
OptionGroupBoolean m_dump_linux_all
OptionGroupBoolean m_fb_app_data
OptionGroupBoolean m_fb_build_id
OptionGroupBoolean m_fb_version
OptionGroupBoolean m_fb_java_stack
OptionGroupBoolean m_fb_dalvik
OptionGroupBoolean m_fb_unwind
OptionGroupBoolean m_fb_error_log
OptionGroupBoolean m_fb_app_state
OptionGroupBoolean m_fb_abort
OptionGroupBoolean m_fb_thread
OptionGroupBoolean m_fb_logcat
OptionGroupBoolean m_fb_all
Additional Inherited Members
Public Types inherited from lldb_private::CommandObject
enum IDType { eBreakpointArgs = 0 , eWatchpointArgs = 1 }
typedef llvm::StringRef ArgumentHelpCallbackFunction()
typedef std::vector< CommandArgumentData > CommandArgumentEntry
typedef std::map< std::string, lldb::CommandObjectSP, std::less<> > CommandMap
Static Public Member Functions inherited from lldb_private::CommandObject
static const char * GetArgumentTypeAsCString (const lldb::CommandArgumentType arg_type)
static const char * GetArgumentDescriptionAsCString (const lldb::CommandArgumentType arg_type)
static lldb::CommandArgumentType LookupArgumentName (llvm::StringRef arg_name)
static const ArgumentTableEntry * FindArgumentDataByType (lldb::CommandArgumentType arg_type)
static void GetArgumentHelp (Stream &str, lldb::CommandArgumentType arg_type, CommandInterpreter &interpreter)
static const char * GetArgumentName (lldb::CommandArgumentType arg_type)
static bool IsPairType (ArgumentRepetitionType arg_repeat_type)
static std::optional< ArgumentRepetitionType > ArgRepetitionFromString (llvm::StringRef string)
Protected Member Functions inherited from lldb_private::CommandObjectParsed
bool WantsRawCommandString () override
Protected Member Functions inherited from lldb_private::CommandObject
bool ParseOptionsAndNotify (Args &args, CommandReturnObject &result, OptionGroupOptions &group_options, ExecutionContext &exe_ctx)
virtual const char * GetInvalidTargetDescription ()
virtual const char * GetInvalidProcessDescription ()
virtual const char * GetInvalidThreadDescription ()
virtual const char * GetInvalidFrameDescription ()
virtual const char * GetInvalidRegContextDescription ()
Target & GetDummyTarget ()
Target & GetTarget ()
Thread * GetDefaultThread ()
bool CheckRequirements (CommandReturnObject &result)
Check the command to make sure anything required by this command is available.
void Cleanup ()
Protected Attributes inherited from lldb_private::CommandObject
CommandInterpreter & m_interpreter
ExecutionContext m_exe_ctx
std::unique_lock< std::recursive_mutex > m_api_locker
std::string m_cmd_name
std::string m_cmd_help_short
std::string m_cmd_help_long
std::string m_cmd_syntax
std::string m_original_command
Flags m_flags
std::vector< CommandArgumentEntry > m_arguments
lldb::CommandOverrideCallback m_deprecated_command_override_callback
lldb_private::CommandOverrideCallbackWithResult m_command_override_callback
void * m_command_override_baton
bool m_is_user_command = false
Detailed Description
Definition at line 621 of file ProcessMinidump.cpp.
Constructor & Destructor Documentation
CommandObjectProcessMinidumpDump()
CommandObjectProcessMinidumpDump::CommandObjectProcessMinidumpDump (CommandInterpreter & interpreter) inline
Definition at line 767 of file ProcessMinidump.cpp.
References APPEND_OPT, lldb_private::CommandObjectParsed::CommandObjectParsed(), INIT_BOOL, m_dump_all, m_dump_directory, m_dump_linux_all, m_dump_linux_auxv, m_dump_linux_cmdline, m_dump_linux_cpuinfo, m_dump_linux_environ, m_dump_linux_lsb_release, m_dump_linux_maps, m_dump_linux_proc_fd, m_dump_linux_proc_stat, m_dump_linux_proc_status, m_dump_linux_proc_uptime, m_fb_abort, m_fb_all, m_fb_app_data, m_fb_app_state, m_fb_build_id, m_fb_dalvik, m_fb_error_log, m_fb_java_stack, m_fb_logcat, m_fb_thread, m_fb_unwind, m_fb_version, and m_option_group.
~CommandObjectProcessMinidumpDump()
CommandObjectProcessMinidumpDump::~CommandObjectProcessMinidumpDump () override default
Member Function Documentation
DoExecute()
void CommandObjectProcessMinidumpDump::DoExecute (Args & command, CommandReturnObject & result) inline override virtual
Implements lldb_private::CommandObjectParsed.
Definition at line 852 of file ProcessMinidump.cpp.
References lldb_private::CommandReturnObject::AppendErrorWithFormat(), lldb_private::DumpDataExtractor(), DumpDirectory(), DumpFacebookAbortReason(), DumpFacebookAppData(), DumpFacebookAppStateLog(), DumpFacebookBuildID(), DumpFacebookDalvikInfo(), DumpFacebookErrorLog(), DumpFacebookJavaStack(), DumpFacebookLogcat(), DumpFacebookThreadName(), DumpFacebookUnwindSymbols(), DumpFacebookVersionName(), DumpLinuxAuxv(), DumpLinuxCMDLine(), DumpLinuxCPUInfo(), DumpLinuxEnviron(), DumpLinuxLSBRelease(), DumpLinuxMaps(), DumpLinuxProcFD(), DumpLinuxProcStat(), DumpLinuxProcStatus(), DumpLinuxProcUptime(), lldb::eByteOrderLittle, lldb::eFormatBytesWithASCII, lldb::eReturnStatusSuccessFinishResult, lldb_private::Process::GetAddressByteSize(), lldb_private::Args::GetArgumentCount(), lldb_private::CommandReturnObject::GetOutputStream(), lldb_private::minidump::MinidumpParser::GetStreamTypeAsString(), lldb_private::DataExtractor::GetU32(), lldb_private::CommandObject::m_cmd_name, lldb_private::CommandObject::m_interpreter, lldb_private::minidump::ProcessMinidump::m_minidump_parser, lldb_private::Stream::Printf(), SetDefaultOptionsIfNoneAreSet(), and lldb_private::CommandReturnObject::SetStatus().
DumpAll()
bool CommandObjectProcessMinidumpDump::DumpAll () const inline private
Definition at line 680 of file ProcessMinidump.cpp.
References m_dump_all.
Referenced by DumpDirectory(), DumpFacebook(), and DumpLinux().
DumpDirectory()
bool CommandObjectProcessMinidumpDump::DumpDirectory () const inline private
Definition at line 683 of file ProcessMinidump.cpp.
References DumpAll(), and m_dump_directory.
DumpFacebook()
bool CommandObjectProcessMinidumpDump::DumpFacebook () const inline private
Definition at line 730 of file ProcessMinidump.cpp.
References DumpAll(), and m_fb_all.
Referenced by DumpFacebookAbortReason(), DumpFacebookAppData(), DumpFacebookAppStateLog(), DumpFacebookBuildID(), DumpFacebookDalvikInfo(), DumpFacebookErrorLog(), DumpFacebookJavaStack(), DumpFacebookLogcat(), DumpFacebookThreadName(), DumpFacebookUnwindSymbols(), and DumpFacebookVersionName().
DumpFacebookAbortReason()
bool CommandObjectProcessMinidumpDump::DumpFacebookAbortReason () const inline private
Definition at line 757 of file ProcessMinidump.cpp.
References DumpFacebook(), and m_fb_abort.
Referenced by DoExecute().
DumpFacebookAppData()
bool CommandObjectProcessMinidumpDump::DumpFacebookAppData () const inline private
Definition at line 733 of file ProcessMinidump.cpp.
References DumpFacebook(), and m_fb_app_data.
Referenced by DoExecute().
DumpFacebookAppStateLog()
bool CommandObjectProcessMinidumpDump::DumpFacebookAppStateLog () const inline private
Definition at line 754 of file ProcessMinidump.cpp.
References DumpFacebook(), and m_fb_app_state.
Referenced by DoExecute().
DumpFacebookBuildID()
bool CommandObjectProcessMinidumpDump::DumpFacebookBuildID () const inline private
Definition at line 736 of file ProcessMinidump.cpp.
References DumpFacebook(), and m_fb_build_id.
Referenced by DoExecute().
DumpFacebookDalvikInfo()
bool CommandObjectProcessMinidumpDump::DumpFacebookDalvikInfo () const inline private
Definition at line 745 of file ProcessMinidump.cpp.
References DumpFacebook(), and m_fb_dalvik.
Referenced by DoExecute().
DumpFacebookErrorLog()
bool CommandObjectProcessMinidumpDump::DumpFacebookErrorLog () const inline private
Definition at line 751 of file ProcessMinidump.cpp.
References DumpFacebook(), and m_fb_error_log.
Referenced by DoExecute().
DumpFacebookJavaStack()
bool CommandObjectProcessMinidumpDump::DumpFacebookJavaStack () const inline private
Definition at line 742 of file ProcessMinidump.cpp.
References DumpFacebook(), and m_fb_java_stack.
Referenced by DoExecute().
DumpFacebookLogcat()
bool CommandObjectProcessMinidumpDump::DumpFacebookLogcat () const inline private
Definition at line 763 of file ProcessMinidump.cpp.
References DumpFacebook(), and m_fb_logcat.
Referenced by DoExecute().
DumpFacebookThreadName()
bool CommandObjectProcessMinidumpDump::DumpFacebookThreadName () const inline private
Definition at line 760 of file ProcessMinidump.cpp.
References DumpFacebook(), and m_fb_thread.
Referenced by DoExecute().
DumpFacebookUnwindSymbols()
bool CommandObjectProcessMinidumpDump::DumpFacebookUnwindSymbols () const inline private
Definition at line 748 of file ProcessMinidump.cpp.
References DumpFacebook(), and m_fb_unwind.
Referenced by DoExecute().
DumpFacebookVersionName()
bool CommandObjectProcessMinidumpDump::DumpFacebookVersionName () const inline private
Definition at line 739 of file ProcessMinidump.cpp.
References DumpFacebook(), and m_fb_version.
Referenced by DoExecute().
DumpLinux()
bool CommandObjectProcessMinidumpDump::DumpLinux () const inline private
Definition at line 687 of file ProcessMinidump.cpp.
References DumpAll(), and m_dump_linux_all.
Referenced by DumpLinuxAuxv(), DumpLinuxCMDLine(), DumpLinuxCPUInfo(), DumpLinuxEnviron(), DumpLinuxLSBRelease(), DumpLinuxMaps(), DumpLinuxProcFD(), DumpLinuxProcStat(), DumpLinuxProcStatus(), and DumpLinuxProcUptime().
DumpLinuxAuxv()
bool CommandObjectProcessMinidumpDump::DumpLinuxAuxv () const inline private
Definition at line 714 of file ProcessMinidump.cpp.
References DumpLinux(), and m_dump_linux_auxv.
Referenced by DoExecute().
DumpLinuxCMDLine()
bool CommandObjectProcessMinidumpDump::DumpLinuxCMDLine () const inline private
Definition at line 706 of file ProcessMinidump.cpp.
References DumpLinux(), and m_dump_linux_cmdline.
Referenced by DoExecute().
DumpLinuxCPUInfo()
bool CommandObjectProcessMinidumpDump::DumpLinuxCPUInfo () const inline private
Definition at line 690 of file ProcessMinidump.cpp.
References DumpLinux(), and m_dump_linux_cpuinfo.
Referenced by DoExecute().
DumpLinuxEnviron()
bool CommandObjectProcessMinidumpDump::DumpLinuxEnviron () const inline private
Definition at line 710 of file ProcessMinidump.cpp.
References DumpLinux(), and m_dump_linux_environ.
Referenced by DoExecute().
DumpLinuxLSBRelease()
bool CommandObjectProcessMinidumpDump::DumpLinuxLSBRelease () const inline private
Definition at line 702 of file ProcessMinidump.cpp.
References DumpLinux(), and m_dump_linux_lsb_release.
Referenced by DoExecute().
DumpLinuxMaps()
bool CommandObjectProcessMinidumpDump::DumpLinuxMaps () const inline private
Definition at line 718 of file ProcessMinidump.cpp.
References DumpLinux(), and m_dump_linux_maps.
Referenced by DoExecute().
DumpLinuxProcFD()
bool CommandObjectProcessMinidumpDump::DumpLinuxProcFD () const inline private
Definition at line 726 of file ProcessMinidump.cpp.
References DumpLinux(), and m_dump_linux_proc_fd.
Referenced by DoExecute().
DumpLinuxProcStat()
bool CommandObjectProcessMinidumpDump::DumpLinuxProcStat () const inline private
Definition at line 698 of file ProcessMinidump.cpp.
References DumpLinux(), and m_dump_linux_proc_stat.
Referenced by DoExecute().
DumpLinuxProcStatus()
bool CommandObjectProcessMinidumpDump::DumpLinuxProcStatus () const inline private
Definition at line 694 of file ProcessMinidump.cpp.
References DumpLinux(), and m_dump_linux_proc_status.
Referenced by DoExecute().
DumpLinuxProcUptime()
bool CommandObjectProcessMinidumpDump::DumpLinuxProcUptime () const inline private
Definition at line 722 of file ProcessMinidump.cpp.
References DumpLinux(), and m_dump_linux_proc_uptime.
Referenced by DoExecute().
GetOptions()
Options * CommandObjectProcessMinidumpDump::GetOptions () inline override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 850 of file ProcessMinidump.cpp.
References m_option_group.
SetDefaultOptionsIfNoneAreSet()
void CommandObjectProcessMinidumpDump::SetDefaultOptionsIfNoneAreSet () inline private
Definition at line 650 of file ProcessMinidump.cpp.
References m_dump_all, m_dump_directory, m_dump_linux_all, m_dump_linux_auxv, m_dump_linux_cmdline, m_dump_linux_cpuinfo, m_dump_linux_environ, m_dump_linux_lsb_release, m_dump_linux_maps, m_dump_linux_proc_fd, m_dump_linux_proc_stat, m_dump_linux_proc_status, m_dump_linux_proc_uptime, m_fb_abort, m_fb_all, m_fb_app_data, m_fb_app_state, m_fb_build_id, m_fb_dalvik, m_fb_error_log, m_fb_java_stack, m_fb_logcat, m_fb_thread, m_fb_unwind, and m_fb_version.
Referenced by DoExecute().
Member Data Documentation
m_dump_all
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_dump_all private
Definition at line 624 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpAll(), and SetDefaultOptionsIfNoneAreSet().
m_dump_directory
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_dump_directory private
Definition at line 625 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpDirectory(), and SetDefaultOptionsIfNoneAreSet().
m_dump_linux_all
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_dump_linux_all private
Definition at line 636 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpLinux(), and SetDefaultOptionsIfNoneAreSet().
m_dump_linux_auxv
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_dump_linux_auxv private
Definition at line 631 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpLinuxAuxv(), and SetDefaultOptionsIfNoneAreSet().
m_dump_linux_cmdline
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_dump_linux_cmdline private
Definition at line 629 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpLinuxCMDLine(), and SetDefaultOptionsIfNoneAreSet().
m_dump_linux_cpuinfo
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_dump_linux_cpuinfo private
Definition at line 626 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpLinuxCPUInfo(), and SetDefaultOptionsIfNoneAreSet().
m_dump_linux_environ
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_dump_linux_environ private
Definition at line 630 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpLinuxEnviron(), and SetDefaultOptionsIfNoneAreSet().
m_dump_linux_lsb_release
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_dump_linux_lsb_release private
Definition at line 628 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpLinuxLSBRelease(), and SetDefaultOptionsIfNoneAreSet().
m_dump_linux_maps
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_dump_linux_maps private
Definition at line 632 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpLinuxMaps(), and SetDefaultOptionsIfNoneAreSet().
m_dump_linux_proc_fd
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_dump_linux_proc_fd private
Definition at line 635 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpLinuxProcFD(), and SetDefaultOptionsIfNoneAreSet().
m_dump_linux_proc_stat
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_dump_linux_proc_stat private
Definition at line 633 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpLinuxProcStat(), and SetDefaultOptionsIfNoneAreSet().
m_dump_linux_proc_status
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_dump_linux_proc_status private
Definition at line 627 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpLinuxProcStatus(), and SetDefaultOptionsIfNoneAreSet().
m_dump_linux_proc_uptime
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_dump_linux_proc_uptime private
Definition at line 634 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpLinuxProcUptime(), and SetDefaultOptionsIfNoneAreSet().
m_fb_abort
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_fb_abort private
Definition at line 645 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpFacebookAbortReason(), and SetDefaultOptionsIfNoneAreSet().
m_fb_all
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_fb_all private
Definition at line 648 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpFacebook(), and SetDefaultOptionsIfNoneAreSet().
m_fb_app_data
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_fb_app_data private
Definition at line 637 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpFacebookAppData(), and SetDefaultOptionsIfNoneAreSet().
m_fb_app_state
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_fb_app_state private
Definition at line 644 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpFacebookAppStateLog(), and SetDefaultOptionsIfNoneAreSet().
m_fb_build_id
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_fb_build_id private
Definition at line 638 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpFacebookBuildID(), and SetDefaultOptionsIfNoneAreSet().
m_fb_dalvik
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_fb_dalvik private
Definition at line 641 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpFacebookDalvikInfo(), and SetDefaultOptionsIfNoneAreSet().
m_fb_error_log
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_fb_error_log private
Definition at line 643 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpFacebookErrorLog(), and SetDefaultOptionsIfNoneAreSet().
m_fb_java_stack
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_fb_java_stack private
Definition at line 640 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpFacebookJavaStack(), and SetDefaultOptionsIfNoneAreSet().
m_fb_logcat
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_fb_logcat private
Definition at line 647 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpFacebookLogcat(), and SetDefaultOptionsIfNoneAreSet().
m_fb_thread
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_fb_thread private
Definition at line 646 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpFacebookThreadName(), and SetDefaultOptionsIfNoneAreSet().
m_fb_unwind
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_fb_unwind private
Definition at line 642 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpFacebookUnwindSymbols(), and SetDefaultOptionsIfNoneAreSet().
m_fb_version
OptionGroupBoolean CommandObjectProcessMinidumpDump::m_fb_version private
Definition at line 639 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), DumpFacebookVersionName(), and SetDefaultOptionsIfNoneAreSet().
m_option_group
OptionGroupOptions CommandObjectProcessMinidumpDump::m_option_group private
Definition at line 623 of file ProcessMinidump.cpp.
Referenced by CommandObjectProcessMinidumpDump(), and GetOptions().
The documentation for this class was generated from the following file:
ProcessMinidump.cpp