LLDB: lldb_private::SyntheticChildren Class Reference
lldb_private::SyntheticChildren Class Reference abstract
#include <TypeSynthetic.h>
Classes
class Flags
Public Types
typedef std::shared_ptr< SyntheticChildren > SharedPointer
Public Member Functions
SyntheticChildren (const Flags &flags)
virtual ~SyntheticChildren ()
bool Cascades () const
bool SkipsPointers () const
bool SkipsReferences () const
bool NonCacheable () const
bool WantsDereference () const
void SetCascades (bool value)
void SetSkipsPointers (bool value)
void SetSkipsReferences (bool value)
void SetNonCacheable (bool value)
uint32_t GetOptions ()
void SetOptions (uint32_t value)
virtual bool IsScripted ()=0
virtual std::string GetDescription ()=0
virtual SyntheticChildrenFrontEnd::UniquePointer GetFrontEnd (ValueObject &backend)=0
uint32_t & GetRevision ()
uint32_t GetPtrMatchDepth ()
void SetPtrMatchDepth (uint32_t value)
Protected Attributes
uint32_t m_my_revision = 0
Flags m_flags
uint32_t m_ptr_match_depth = 1
Private Member Functions
SyntheticChildren (const SyntheticChildren &)=delete
const SyntheticChildren & operator= (const SyntheticChildren &)=delete
Detailed Description
Definition at line 135 of file TypeSynthetic.h.
Member Typedef Documentation
SharedPointer
typedef std::shared_ptr<SyntheticChildren> lldb_private::SyntheticChildren::SharedPointer
Definition at line 267 of file TypeSynthetic.h.
Constructor & Destructor Documentation
SyntheticChildren() [1/2]
SyntheticChildren::SyntheticChildren (const Flags & flags)
Definition at line 91 of file TypeSynthetic.cpp.
References m_flags.
Referenced by lldb_private::BytecodeSyntheticChildren::BytecodeSyntheticChildren(), lldb_private::CXXSyntheticChildren::CXXSyntheticChildren(), operator=(), lldb_private::ScriptedSyntheticChildren::ScriptedSyntheticChildren(), SyntheticChildren(), lldb_private::TypeFilterImpl::TypeFilterImpl(), and lldb_private::TypeFilterImpl::TypeFilterImpl().
~SyntheticChildren()
SyntheticChildren::~SyntheticChildren () virtual default
SyntheticChildren() [2/2]
lldb_private::SyntheticChildren::SyntheticChildren (const SyntheticChildren &) private delete
References SyntheticChildren().
Member Function Documentation
Cascades()
bool lldb_private::SyntheticChildren::Cascades () const inline
Definition at line 238 of file TypeSynthetic.h.
References m_flags.
Referenced by lldb_private::BytecodeSyntheticChildren::GetDescription(), lldb_private::CXXSyntheticChildren::GetDescription(), lldb_private::ScriptedSyntheticChildren::GetDescription(), and lldb_private::TypeFilterImpl::GetDescription().
GetDescription()
std::string SyntheticChildren::GetDescription () pure virtual
Implemented in lldb_private::BytecodeSyntheticChildren, lldb_private::CXXSyntheticChildren, lldb_private::ScriptedSyntheticChildren, and lldb_private::TypeFilterImpl.
Definition at line 105 of file TypeSynthetic.cpp.
GetFrontEnd()
SyntheticChildrenFrontEnd::UniquePointer SyntheticChildren::GetFrontEnd (ValueObject & backend) pure virtual
Implemented in lldb_private::BytecodeSyntheticChildren, lldb_private::CXXSyntheticChildren, lldb_private::ScriptedSyntheticChildren, and lldb_private::TypeFilterImpl.
Definition at line 108 of file TypeSynthetic.cpp.
GetOptions()
uint32_t lldb_private::SyntheticChildren::GetOptions () inline
Definition at line 256 of file TypeSynthetic.h.
References m_flags.
GetPtrMatchDepth()
uint32_t lldb_private::SyntheticChildren::GetPtrMatchDepth () inline
Definition at line 271 of file TypeSynthetic.h.
References m_ptr_match_depth.
GetRevision()
uint32_t & lldb_private::SyntheticChildren::GetRevision () inline
Definition at line 269 of file TypeSynthetic.h.
References m_my_revision.
IsScripted()
bool SyntheticChildren::IsScripted () pure virtual
Implemented in lldb_private::BytecodeSyntheticChildren, lldb_private::CXXSyntheticChildren, lldb_private::ScriptedSyntheticChildren, and lldb_private::TypeFilterImpl.
Definition at line 103 of file TypeSynthetic.cpp.
NonCacheable()
bool lldb_private::SyntheticChildren::NonCacheable () const inline
Definition at line 244 of file TypeSynthetic.h.
References m_flags.
operator=()
const SyntheticChildren & lldb_private::SyntheticChildren::operator= (const SyntheticChildren &) private delete
References SyntheticChildren().
SetCascades()
void lldb_private::SyntheticChildren::SetCascades (bool value) inline
Definition at line 248 of file TypeSynthetic.h.
References m_flags.
SetNonCacheable()
void lldb_private::SyntheticChildren::SetNonCacheable (bool value) inline
Definition at line 254 of file TypeSynthetic.h.
References m_flags.
SetOptions()
void lldb_private::SyntheticChildren::SetOptions (uint32_t value) inline
Definition at line 258 of file TypeSynthetic.h.
References m_flags.
SetPtrMatchDepth()
void lldb_private::SyntheticChildren::SetPtrMatchDepth (uint32_t value) inline
Definition at line 273 of file TypeSynthetic.h.
References m_ptr_match_depth.
SetSkipsPointers()
void lldb_private::SyntheticChildren::SetSkipsPointers (bool value) inline
Definition at line 250 of file TypeSynthetic.h.
References m_flags.
SetSkipsReferences()
void lldb_private::SyntheticChildren::SetSkipsReferences (bool value) inline
Definition at line 252 of file TypeSynthetic.h.
References m_flags.
SkipsPointers()
bool lldb_private::SyntheticChildren::SkipsPointers () const inline
Definition at line 240 of file TypeSynthetic.h.
References m_flags.
Referenced by lldb_private::BytecodeSyntheticChildren::GetDescription(), lldb_private::CXXSyntheticChildren::GetDescription(), lldb_private::ScriptedSyntheticChildren::GetDescription(), and lldb_private::TypeFilterImpl::GetDescription().
SkipsReferences()
bool lldb_private::SyntheticChildren::SkipsReferences () const inline
Definition at line 242 of file TypeSynthetic.h.
References m_flags.
Referenced by lldb_private::BytecodeSyntheticChildren::GetDescription(), lldb_private::CXXSyntheticChildren::GetDescription(), lldb_private::ScriptedSyntheticChildren::GetDescription(), and lldb_private::TypeFilterImpl::GetDescription().
WantsDereference()
bool lldb_private::SyntheticChildren::WantsDereference () const inline
Definition at line 246 of file TypeSynthetic.h.
References m_flags.
Member Data Documentation
m_flags
Flags lldb_private::SyntheticChildren::m_flags protected
Definition at line 277 of file TypeSynthetic.h.
Referenced by Cascades(), GetOptions(), NonCacheable(), SetCascades(), SetNonCacheable(), SetOptions(), SetSkipsPointers(), SetSkipsReferences(), SkipsPointers(), SkipsReferences(), SyntheticChildren(), and WantsDereference().
m_my_revision
uint32_t lldb_private::SyntheticChildren::m_my_revision = 0 protected
Definition at line 276 of file TypeSynthetic.h.
Referenced by GetRevision().
m_ptr_match_depth
uint32_t lldb_private::SyntheticChildren::m_ptr_match_depth = 1 protected
Definition at line 278 of file TypeSynthetic.h.
Referenced by GetPtrMatchDepth(), and SetPtrMatchDepth().
The documentation for this class was generated from the following files:
TypeSynthetic.h
TypeSynthetic.cpp