LLDB: lldb_private::process_gdb_remote::GDBRemoteClientBase::Lock Class Reference
lldb_private::process_gdb_remote::GDBRemoteClientBase::Lock Class Reference
#include <GDBRemoteClientBase.h>
Public Member Functions
Lock (GDBRemoteClientBase &comm, std::chrono::seconds interrupt_timeout=std::chrono::seconds(0))
~Lock ()
operator bool ()
bool DidInterrupt () const
Private Member Functions
void SyncWithContinueThread ()
Private Attributes
std::unique_lock< std::recursive_mutex > m_async_lock
GDBRemoteClientBase & m_comm
std::chrono::seconds m_interrupt_timeout
bool m_acquired
bool m_did_interrupt
Detailed Description
Definition at line 77 of file GDBRemoteClientBase.h.
Constructor & Destructor Documentation
Lock()
GDBRemoteClientBase::Lock::Lock (GDBRemoteClientBase & comm, std::chrono::seconds interrupt_timeout = std::chrono::seconds(0))
Definition at line 356 of file GDBRemoteClientBase.cpp.
References lldb_private::process_gdb_remote::GDBRemoteClientBase::GDBRemoteClientBase(), m_acquired, m_async_lock, lldb_private::process_gdb_remote::GDBRemoteClientBase::m_async_mutex, m_comm, m_did_interrupt, m_interrupt_timeout, and SyncWithContinueThread().
~Lock()
GDBRemoteClientBase::Lock::~Lock ()
Definition at line 397 of file GDBRemoteClientBase.cpp.
References m_acquired, and m_comm.
Member Function Documentation
DidInterrupt()
bool lldb_private::process_gdb_remote::GDBRemoteClientBase::Lock::DidInterrupt () const inline
Definition at line 93 of file GDBRemoteClientBase.h.
References m_did_interrupt.
Referenced by lldb_private::process_gdb_remote::GDBRemoteClientBase::Interrupt(), and lldb_private::process_gdb_remote::GDBRemoteClientBase::SendAsyncSignal().
operator bool()
lldb_private::process_gdb_remote::GDBRemoteClientBase::Lock::operator bool () inline explicit
Definition at line 89 of file GDBRemoteClientBase.h.
References m_acquired.
SyncWithContinueThread()
void GDBRemoteClientBase::Lock::SyncWithContinueThread () private
Definition at line 366 of file GDBRemoteClientBase.cpp.
References lldb::eConnectionStatusSuccess, lldb_private::GetLog(), LLDB_LOGF, m_acquired, m_comm, m_did_interrupt, m_interrupt_timeout, lldb_private::process_gdb_remote::Packets, lldb_private::process_gdb_remote::Process, and lldb_private::Log::PutCString().
Referenced by Lock().
Member Data Documentation
m_acquired
bool lldb_private::process_gdb_remote::GDBRemoteClientBase::Lock::m_acquired private
Definition at line 99 of file GDBRemoteClientBase.h.
Referenced by Lock(), operator bool(), SyncWithContinueThread(), and ~Lock().
m_async_lock
std::unique_lock<std::recursive_mutex> lldb_private::process_gdb_remote::GDBRemoteClientBase::Lock::m_async_lock private
Definition at line 96 of file GDBRemoteClientBase.h.
Referenced by Lock().
m_comm
GDBRemoteClientBase& lldb_private::process_gdb_remote::GDBRemoteClientBase::Lock::m_comm private
Definition at line 97 of file GDBRemoteClientBase.h.
Referenced by Lock(), SyncWithContinueThread(), and ~Lock().
m_did_interrupt
bool lldb_private::process_gdb_remote::GDBRemoteClientBase::Lock::m_did_interrupt private
Definition at line 100 of file GDBRemoteClientBase.h.
Referenced by DidInterrupt(), Lock(), and SyncWithContinueThread().
m_interrupt_timeout
std::chrono::seconds lldb_private::process_gdb_remote::GDBRemoteClientBase::Lock::m_interrupt_timeout private
Definition at line 98 of file GDBRemoteClientBase.h.
Referenced by Lock(), and SyncWithContinueThread().
The documentation for this class was generated from the following files:
GDBRemoteClientBase.h
GDBRemoteClientBase.cpp