LLDB: lldb_private::plugin::dwarf::DWARFDebugMacroHeader Class Reference
lldb_private::plugin::dwarf::DWARFDebugMacroHeader Class Reference
#include <DWARFDebugMacro.h>
Public Types
enum HeaderFlagMask { OFFSET_SIZE_MASK = 0x1 , DEBUG_LINE_OFFSET_MASK = 0x2 , OPCODE_OPERANDS_TABLE_MASK = 0x4 }
Public Member Functions
bool OffsetIs64Bit () const
Static Public Member Functions
static DWARFDebugMacroHeader ParseHeader (const DWARFDataExtractor &debug_macro_data, lldb::offset_t *offset)
Static Private Member Functions
static void SkipOperandTable (const DWARFDataExtractor &debug_macro_data, lldb::offset_t *offset)
Private Attributes
uint16_t m_version = 0
bool m_offset_is_64_bit = false
uint64_t m_debug_line_offset = 0
Detailed Description
Definition at line 27 of file DWARFDebugMacro.h.
Member Enumeration Documentation
HeaderFlagMask
enum lldb_private::plugin::dwarf::DWARFDebugMacroHeader::HeaderFlagMask
Enumerator
OFFSET_SIZE_MASK
DEBUG_LINE_OFFSET_MASK
OPCODE_OPERANDS_TABLE_MASK
Definition at line 29 of file DWARFDebugMacro.h.
Member Function Documentation
OffsetIs64Bit()
bool lldb_private::plugin::dwarf::DWARFDebugMacroHeader::OffsetIs64Bit () const inline
Definition at line 39 of file DWARFDebugMacro.h.
References m_offset_is_64_bit.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::ParseDebugMacros().
ParseHeader()
DWARFDebugMacroHeader DWARFDebugMacroHeader::ParseHeader (const DWARFDataExtractor & debug_macro_data, lldb::offset_t * offset) static
Definition at line 21 of file DWARFDebugMacro.cpp.
References DEBUG_LINE_OFFSET_MASK, lldb_private::DataExtractor::GetU16(), lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU64(), lldb_private::DataExtractor::GetU8(), m_debug_line_offset, m_offset_is_64_bit, m_version, OFFSET_SIZE_MASK, OPCODE_OPERANDS_TABLE_MASK, and SkipOperandTable().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::ParseDebugMacros().
SkipOperandTable()
void DWARFDebugMacroHeader::SkipOperandTable (const DWARFDataExtractor & debug_macro_data, lldb::offset_t * offset) static private
Definition at line 45 of file DWARFDebugMacro.cpp.
References lldb_private::DataExtractor::GetU8(), and lldb_private::DataExtractor::GetULEB128().
Referenced by ParseHeader().
Member Data Documentation
m_debug_line_offset
uint64_t lldb_private::plugin::dwarf::DWARFDebugMacroHeader::m_debug_line_offset = 0 private
Definition at line 47 of file DWARFDebugMacro.h.
Referenced by ParseHeader().
m_offset_is_64_bit
bool lldb_private::plugin::dwarf::DWARFDebugMacroHeader::m_offset_is_64_bit = false private
Definition at line 46 of file DWARFDebugMacro.h.
Referenced by OffsetIs64Bit(), and ParseHeader().
m_version
uint16_t lldb_private::plugin::dwarf::DWARFDebugMacroHeader::m_version = 0 private
Definition at line 45 of file DWARFDebugMacro.h.
Referenced by ParseHeader().
The documentation for this class was generated from the following files:
DWARFDebugMacro.h
DWARFDebugMacro.cpp