LLDB: lldb_private::TypeSystemClang Class Reference
lldb_private::TypeSystemClang Class Reference
A TypeSystem implementation based on Clang.
#include <TypeSystemClang.h>
Classes
class TemplateParameterInfos
Public Types
typedef void(* CompleteTagDeclCallback) (void *baton, clang::TagDecl *)
typedef void(* CompleteObjCInterfaceDeclCallback) (void *baton, clang::ObjCInterfaceDecl *)
Public Member Functions
bool isA (const void *ClassID) const override
TypeSystemClang (llvm::StringRef name, llvm::Triple triple)
Constructs a TypeSystemClang with an ASTContext using the given triple.
TypeSystemClang (llvm::StringRef name, clang::ASTContext &existing_ctxt)
Constructs a TypeSystemClang that uses an existing ASTContext internally.
~TypeSystemClang () override
void Finalize () override
Free up any resources associated with this TypeSystem.
llvm::StringRef GetPluginName () override
llvm::StringRef getDisplayName () const
Returns the display name of this TypeSystemClang that indicates what purpose it serves in LLDB.
clang::ASTContext & getASTContext () const
Returns the clang::ASTContext instance managed by this TypeSystemClang.
clang::MangleContext * getMangleContext ()
std::shared_ptr< clang::TargetOptions > & getTargetOptions ()
clang::TargetInfo * getTargetInfo ()
void setSema (clang::Sema *s)
clang::Sema * getSema ()
const char * GetTargetTriple ()
void SetExternalSource (llvm::IntrusiveRefCntPtr< clang::ExternalASTSource > ast_source_sp)
bool GetCompleteDecl (clang::Decl *decl)
void SetMetadataAsUserID (const clang::Decl *decl, lldb::user_id_t user_id)
void SetMetadataAsUserID (const clang::Type *type, lldb::user_id_t user_id)
void SetMetadata (const clang::Decl *object, ClangASTMetadata meta_data)
void SetMetadata (const clang::Type *object, ClangASTMetadata meta_data)
std::optional< ClangASTMetadata > GetMetadata (const clang::Decl *object)
std::optional< ClangASTMetadata > GetMetadata (const clang::Type *object)
CompilerType GetBuiltinTypeForEncodingAndBitSize (lldb::Encoding encoding, size_t bit_size) override
CompilerType GetBasicType (lldb::BasicType type)
CompilerType GetBuiltinTypeForDWARFEncodingAndBitSize (llvm::StringRef type_name, uint32_t dw_ate, uint32_t bit_size)
CompilerType GetCStringType (bool is_const)
CompilerDeclContext GetCompilerDeclContextForType (const CompilerType &type) override
Returns the direct parent context of specified type.
uint32_t GetPointerByteSize () override
clang::TranslationUnitDecl * GetTranslationUnitDecl ()
CompilerType GetType (clang::QualType qt)
Creates a CompilerType from the given QualType with the current TypeSystemClang instance as the CompilerType's typesystem.
CompilerType GetTypeForDecl (clang::NamedDecl *decl)
CompilerType GetTypeForDecl (clang::TagDecl *decl)
CompilerType GetTypeForDecl (clang::ObjCInterfaceDecl *objc_decl)
CompilerType GetTypeForDecl (clang::ValueDecl *value_decl)
template<typename RecordDeclType>
CompilerType GetTypeForIdentifier (const clang::ASTContext &Ctx, llvm::StringRef type_name, clang::DeclContext *decl_context=nullptr)
CompilerType CreateStructForIdentifier (llvm::StringRef type_name, const std::initializer_list< std::pair< const char *, CompilerType > > &type_fields, bool packed=false)
CompilerType GetOrCreateStructForIdentifier (llvm::StringRef type_name, const std::initializer_list< std::pair< const char *, CompilerType > > &type_fields, bool packed=false)
uint32_t GetNumBaseClasses (const clang::CXXRecordDecl *cxx_record_decl, bool omit_empty_base_classes)
uint32_t GetIndexForRecordChild (const clang::RecordDecl *record_decl, clang::NamedDecl *canonical_decl, bool omit_empty_base_classes)
uint32_t GetIndexForRecordBase (const clang::RecordDecl *record_decl, const clang::CXXBaseSpecifier *base_spec, bool omit_empty_base_classes)
OptionalClangModuleID GetOrCreateClangModule (llvm::StringRef name, OptionalClangModuleID parent, bool is_framework=false, bool is_explicit=false)
Synthesize a clang::Module and return its ID or a default-constructed ID.
CompilerType CreateRecordType (clang::DeclContext *decl_ctx, OptionalClangModuleID owning_module, lldb::AccessType access_type, llvm::StringRef name, int kind, lldb::LanguageType language, std::optional< ClangASTMetadata > metadata=std::nullopt, bool exports_symbols=false)
clang::FunctionTemplateDecl * CreateFunctionTemplateDecl (clang::DeclContext *decl_ctx, OptionalClangModuleID owning_module, clang::FunctionDecl *func_decl, const TemplateParameterInfos &infos)
void CreateFunctionTemplateSpecializationInfo (clang::FunctionDecl *func_decl, clang::FunctionTemplateDecl *Template, const TemplateParameterInfos &infos)
clang::ClassTemplateDecl * CreateClassTemplateDecl (clang::DeclContext *decl_ctx, OptionalClangModuleID owning_module, lldb::AccessType access_type, llvm::StringRef class_name, int kind, const TemplateParameterInfos &infos)
clang::TemplateTemplateParmDecl * CreateTemplateTemplateParmDecl (const char *template_name)
clang::ClassTemplateSpecializationDecl * CreateClassTemplateSpecializationDecl (clang::DeclContext *decl_ctx, OptionalClangModuleID owning_module, clang::ClassTemplateDecl *class_template_decl, int kind, const TemplateParameterInfos &infos)
CompilerType CreateClassTemplateSpecializationType (clang::ClassTemplateSpecializationDecl *class_template_specialization_decl)
bool FieldIsBitfield (clang::FieldDecl *field, uint32_t &bitfield_bit_size)
bool RecordHasFields (const clang::RecordDecl *record_decl)
bool BaseSpecifierIsEmpty (const clang::CXXBaseSpecifier *b)
CompilerType CreateObjCClass (llvm::StringRef name, clang::DeclContext *decl_ctx, OptionalClangModuleID owning_module, bool isInternal, std::optional< ClangASTMetadata > metadata=std::nullopt)
clang::NamespaceDecl * GetUniqueNamespaceDeclaration (const char *name, clang::DeclContext *decl_ctx, OptionalClangModuleID owning_module, bool is_inline=false)
clang::FunctionDecl * CreateFunctionDeclaration (clang::DeclContext *decl_ctx, OptionalClangModuleID owning_module, llvm::StringRef name, const CompilerType &function_Type, clang::StorageClass storage, bool is_inline, llvm::StringRef asm_label)
CompilerType CreateFunctionType (const CompilerType &result_type, llvm::ArrayRef< CompilerType > args, bool is_variadic, unsigned type_quals, clang::CallingConv cc=clang::CC_C, clang::RefQualifierKind ref_qual=clang::RQ_None)
clang::ParmVarDecl * CreateParameterDeclaration (clang::DeclContext *decl_ctx, OptionalClangModuleID owning_module, const char *name, const CompilerType &param_type, int storage, bool add_decl=false)
CompilerType CreateBlockPointerType (const CompilerType &function_type)
CompilerType CreateArrayType (const CompilerType &element_type, std::optional< size_t > element_count, bool is_vector)
CompilerType CreateEnumerationType (llvm::StringRef name, clang::DeclContext *decl_ctx, OptionalClangModuleID owning_module, const Declaration &decl, const CompilerType &integer_qual_type, bool is_scoped, std::optional< clang::EnumExtensibilityAttr::Kind > enum_kind=std::nullopt)
CompilerType GetIntTypeFromBitSize (size_t bit_size, bool is_signed)
CompilerType GetPointerSizedIntType (bool is_signed)
plugin::dwarf::DWARFASTParser * GetDWARFParser () override
PDBASTParser * GetPDBParser () override
npdb::PdbAstBuilder * GetNativePDBParser () override
void CompleteTagDecl (clang::TagDecl *)
void CompleteObjCInterfaceDecl (clang::ObjCInterfaceDecl *)
bool LayoutRecordType (const clang::RecordDecl *record_decl, uint64_t &size, uint64_t &alignment, llvm::DenseMap< const clang::FieldDecl *, uint64_t > &field_offsets, llvm::DenseMap< const clang::CXXRecordDecl *, clang::CharUnits > &base_offsets, llvm::DenseMap< const clang::CXXRecordDecl *, clang::CharUnits > &vbase_offsets)
CompilerDecl GetCompilerDecl (clang::Decl *decl)
Creates a CompilerDecl from the given Decl with the current TypeSystemClang instance as its typesystem.
ConstString DeclGetName (void *opaque_decl) override
ConstString DeclGetMangledName (void *opaque_decl) override
CompilerDeclContext DeclGetDeclContext (void *opaque_decl) override
CompilerType DeclGetFunctionReturnType (void *opaque_decl) override
size_t DeclGetFunctionNumArguments (void *opaque_decl) override
CompilerType DeclGetFunctionArgumentType (void *opaque_decl, size_t arg_idx) override
std::vector< lldb_private::CompilerContext > DeclGetCompilerContext (void *opaque_decl) override
Scalar DeclGetConstantValue (void *opaque_decl) override
CompilerType GetTypeForDecl (void *opaque_decl) override
CompilerDeclContext CreateDeclContext (clang::DeclContext *ctx)
Creates a CompilerDeclContext from the given DeclContext with the current TypeSystemClang instance as its typesystem.
std::vector< CompilerDecl > DeclContextFindDeclByName (void *opaque_decl_ctx, ConstString name, const bool ignore_using_decls) override
ConstString DeclContextGetName (void *opaque_decl_ctx) override
ConstString DeclContextGetScopeQualifiedName (void *opaque_decl_ctx) override
bool DeclContextIsClassMethod (void *opaque_decl_ctx) override
bool DeclContextIsContainedInLookup (void *opaque_decl_ctx, void *other_opaque_decl_ctx) override
lldb::LanguageType DeclContextGetLanguage (void *opaque_decl_ctx) override
std::vector< lldb_private::CompilerContext > DeclContextGetCompilerContext (void *opaque_decl_ctx) override
bool Verify (lldb::opaque_compiler_type_t type) override
Verify the integrity of the type to catch CompilerTypes that mix and match invalid TypeSystem/Opaque type pairs.
bool IsArrayType (lldb::opaque_compiler_type_t type, CompilerType *element_type, uint64_t *size, bool *is_incomplete) override
bool IsVectorType (lldb::opaque_compiler_type_t type, CompilerType *element_type, uint64_t *size) override
bool IsAggregateType (lldb::opaque_compiler_type_t type) override
bool IsAnonymousType (lldb::opaque_compiler_type_t type) override
bool IsBeingDefined (lldb::opaque_compiler_type_t type) override
bool IsCharType (lldb::opaque_compiler_type_t type) override
bool IsCompleteType (lldb::opaque_compiler_type_t type) override
bool IsConst (lldb::opaque_compiler_type_t type) override
bool IsCStringType (lldb::opaque_compiler_type_t type, uint32_t &length)
bool IsDefined (lldb::opaque_compiler_type_t type) override
bool IsFloatingPointType (lldb::opaque_compiler_type_t type) override
unsigned GetPtrAuthKey (lldb::opaque_compiler_type_t type) override
unsigned GetPtrAuthDiscriminator (lldb::opaque_compiler_type_t type) override
bool GetPtrAuthAddressDiversity (lldb::opaque_compiler_type_t type) override
bool IsFunctionType (lldb::opaque_compiler_type_t type) override
uint32_t IsHomogeneousAggregate (lldb::opaque_compiler_type_t type, CompilerType *base_type_ptr) override
size_t GetNumberOfFunctionArguments (lldb::opaque_compiler_type_t type) override
CompilerType GetFunctionArgumentAtIndex (lldb::opaque_compiler_type_t type, const size_t index) override
bool IsFunctionPointerType (lldb::opaque_compiler_type_t type) override
bool IsMemberFunctionPointerType (lldb::opaque_compiler_type_t type) override
bool IsBlockPointerType (lldb::opaque_compiler_type_t type, CompilerType *function_pointer_type_ptr) override
bool IsIntegerType (lldb::opaque_compiler_type_t type, bool &is_signed) override
bool IsEnumerationType (lldb::opaque_compiler_type_t type, bool &is_signed) override
bool IsScopedEnumerationType (lldb::opaque_compiler_type_t type) override
bool IsPolymorphicClass (lldb::opaque_compiler_type_t type) override
bool IsPossibleDynamicType (lldb::opaque_compiler_type_t type, CompilerType *target_type, bool check_cplusplus, bool check_objc) override
bool IsRuntimeGeneratedType (lldb::opaque_compiler_type_t type) override
This is used by swift.
bool IsPointerType (lldb::opaque_compiler_type_t type, CompilerType *pointee_type) override
bool IsPointerOrReferenceType (lldb::opaque_compiler_type_t type, CompilerType *pointee_type) override
bool IsReferenceType (lldb::opaque_compiler_type_t type, CompilerType *pointee_type, bool *is_rvalue) override
bool IsScalarType (lldb::opaque_compiler_type_t type) override
bool IsTypedefType (lldb::opaque_compiler_type_t type) override
bool IsVoidType (lldb::opaque_compiler_type_t type) override
bool CanPassInRegisters (const CompilerType &type) override
bool SupportsLanguage (lldb::LanguageType language) override
bool GetCompleteType (lldb::opaque_compiler_type_t type) override
bool IsForcefullyCompleted (lldb::opaque_compiler_type_t type) override
ConstString GetTypeName (lldb::opaque_compiler_type_t type, bool base_only) override
ConstString GetDisplayTypeName (lldb::opaque_compiler_type_t type) override
uint32_t GetTypeInfo (lldb::opaque_compiler_type_t type, CompilerType *pointee_or_element_compiler_type) override
lldb::LanguageType GetMinimumLanguage (lldb::opaque_compiler_type_t type) override
lldb::TypeClass GetTypeClass (lldb::opaque_compiler_type_t type) override
unsigned GetTypeQualifiers (lldb::opaque_compiler_type_t type) override
CompilerType GetArrayElementType (lldb::opaque_compiler_type_t type, ExecutionContextScope *exe_scope) override
CompilerType GetArrayType (lldb::opaque_compiler_type_t type, uint64_t size) override
CompilerType GetCanonicalType (lldb::opaque_compiler_type_t type) override
CompilerType GetFullyUnqualifiedType (lldb::opaque_compiler_type_t type) override
CompilerType GetEnumerationIntegerType (lldb::opaque_compiler_type_t type) override
int GetFunctionArgumentCount (lldb::opaque_compiler_type_t type) override
CompilerType GetFunctionArgumentTypeAtIndex (lldb::opaque_compiler_type_t type, size_t idx) override
CompilerType GetFunctionReturnType (lldb::opaque_compiler_type_t type) override
size_t GetNumMemberFunctions (lldb::opaque_compiler_type_t type) override
TypeMemberFunctionImpl GetMemberFunctionAtIndex (lldb::opaque_compiler_type_t type, size_t idx) override
CompilerType GetNonReferenceType (lldb::opaque_compiler_type_t type) override
CompilerType GetPointeeType (lldb::opaque_compiler_type_t type) override
CompilerType GetPointerType (lldb::opaque_compiler_type_t type) override
CompilerType GetLValueReferenceType (lldb::opaque_compiler_type_t type) override
CompilerType GetRValueReferenceType (lldb::opaque_compiler_type_t type) override
CompilerType GetAtomicType (lldb::opaque_compiler_type_t type) override
CompilerType AddConstModifier (lldb::opaque_compiler_type_t type) override
CompilerType AddPtrAuthModifier (lldb::opaque_compiler_type_t type, uint32_t payload) override
CompilerType AddVolatileModifier (lldb::opaque_compiler_type_t type) override
CompilerType AddRestrictModifier (lldb::opaque_compiler_type_t type) override
CompilerType CreateTypedef (lldb::opaque_compiler_type_t type, const char *name, const CompilerDeclContext &decl_ctx, uint32_t opaque_payload) override
Using the current type, create a new typedef to that type using "typedef_name" as the name and "decl_ctx" as the decl context.
CompilerType GetTypedefedType (lldb::opaque_compiler_type_t type) override
CompilerType GetBasicTypeFromAST (lldb::BasicType basic_type) override
CompilerType CreateGenericFunctionPrototype () override
const llvm::fltSemantics & GetFloatTypeSemantics (size_t byte_size, lldb::Format format) override
llvm::Expected< uint64_t > GetByteSize (lldb::opaque_compiler_type_t type, ExecutionContextScope *exe_scope)
llvm::Expected< uint64_t > GetBitSize (lldb::opaque_compiler_type_t type, ExecutionContextScope *exe_scope) override
lldb::Encoding GetEncoding (lldb::opaque_compiler_type_t type) override
lldb::Format GetFormat (lldb::opaque_compiler_type_t type) override
std::optional< size_t > GetTypeBitAlign (lldb::opaque_compiler_type_t type, ExecutionContextScope *exe_scope) override
llvm::Expected< uint32_t > GetNumChildren (lldb::opaque_compiler_type_t type, bool omit_empty_base_classes, const ExecutionContext *exe_ctx) override
CompilerType GetBuiltinTypeByName (ConstString name) override
lldb::BasicType GetBasicTypeEnumeration (lldb::opaque_compiler_type_t type) override
void ForEachEnumerator (lldb::opaque_compiler_type_t type, std::function< bool(const CompilerType &integer_type, ConstString name, const llvm::APSInt &value)> const &callback) override
uint32_t GetNumFields (lldb::opaque_compiler_type_t type) override
CompilerType GetFieldAtIndex (lldb::opaque_compiler_type_t type, size_t idx, std::string &name, uint64_t *bit_offset_ptr, uint32_t *bitfield_bit_size_ptr, bool *is_bitfield_ptr) override
uint32_t GetNumDirectBaseClasses (lldb::opaque_compiler_type_t type) override
uint32_t GetNumVirtualBaseClasses (lldb::opaque_compiler_type_t type) override
CompilerType GetDirectBaseClassAtIndex (lldb::opaque_compiler_type_t type, size_t idx, uint32_t *bit_offset_ptr) override
CompilerType GetVirtualBaseClassAtIndex (lldb::opaque_compiler_type_t type, size_t idx, uint32_t *bit_offset_ptr) override
CompilerDecl GetStaticFieldWithName (lldb::opaque_compiler_type_t type, llvm::StringRef name) override
llvm::Expected< CompilerType > GetDereferencedType (lldb::opaque_compiler_type_t type, ExecutionContext *exe_ctx, std::string &deref_name, uint32_t &deref_byte_size, int32_t &deref_byte_offset, ValueObject *valobj, uint64_t &language_flags) override
llvm::Expected< CompilerType > GetChildCompilerTypeAtIndex (lldb::opaque_compiler_type_t type, ExecutionContext *exe_ctx, size_t idx, bool transparent_pointers, bool omit_empty_base_classes, bool ignore_array_bounds, std::string &child_name, uint32_t &child_byte_size, int32_t &child_byte_offset, uint32_t &child_bitfield_bit_size, uint32_t &child_bitfield_bit_offset, bool &child_is_base_class, bool &child_is_deref_of_parent, ValueObject *valobj, uint64_t &language_flags) override
llvm::Expected< uint32_t > GetIndexOfChildWithName (lldb::opaque_compiler_type_t type, llvm::StringRef name, bool omit_empty_base_classes) override
size_t GetIndexOfChildMemberWithName (lldb::opaque_compiler_type_t type, llvm::StringRef name, bool omit_empty_base_classes, std::vector< uint32_t > &child_indexes) override
CompilerType GetDirectNestedTypeWithName (lldb::opaque_compiler_type_t type, llvm::StringRef name) override
bool IsTemplateType (lldb::opaque_compiler_type_t type) override
size_t GetNumTemplateArguments (lldb::opaque_compiler_type_t type, bool expand_pack) override
lldb::TemplateArgumentKind GetTemplateArgumentKind (lldb::opaque_compiler_type_t type, size_t idx, bool expand_pack) override
CompilerType GetTypeTemplateArgument (lldb::opaque_compiler_type_t type, size_t idx, bool expand_pack) override
std::optional< CompilerType::IntegralTemplateArgument > GetIntegralTemplateArgument (lldb::opaque_compiler_type_t type, size_t idx, bool expand_pack) override
CompilerType GetTypeForFormatters (void *type) override
bool IsPromotableIntegerType (lldb::opaque_compiler_type_t type) override
Checks if the type is eligible for integral promotion.
llvm::Expected< CompilerType > DoIntegralPromotion (CompilerType from, ExecutionContextScope *exe_scope) override
Perform integral promotion on a given type.
uint32_t CountDeclLevels (clang::DeclContext *frame_decl_ctx, clang::DeclContext *child_decl_ctx, ConstString *child_name=nullptr, CompilerType *child_type=nullptr)
llvm::SmallVector< clang::ParmVarDecl * > CreateParameterDeclarations (clang::FunctionDecl *context, const clang::FunctionProtoType &prototype, const llvm::SmallVector< llvm::StringRef > &param_names)
For each parameter type of prototype, creates a clang::ParmVarDecl whose clang::DeclContext is context.
clang::CXXMethodDecl * AddMethodToCXXRecordType (lldb::opaque_compiler_type_t type, llvm::StringRef name, llvm::StringRef asm_label, const CompilerType &method_type, lldb::AccessType access, bool is_virtual, bool is_static, bool is_inline, bool is_explicit, bool is_attr_used, bool is_artificial)
void AddMethodOverridesForCXXRecordType (lldb::opaque_compiler_type_t type)
std::unique_ptr< clang::CXXBaseSpecifier > CreateBaseClassSpecifier (lldb::opaque_compiler_type_t type, lldb::AccessType access, bool is_virtual, bool base_of_class)
bool TransferBaseClasses (lldb::opaque_compiler_type_t type, std::vector< std::unique_ptr< clang::CXXBaseSpecifier > > bases)
clang::EnumConstantDecl * AddEnumerationValueToEnumerationType (const CompilerType &enum_type, const Declaration &decl, const char *name, uint64_t enum_value, uint32_t enum_value_bit_size)
clang::EnumConstantDecl * AddEnumerationValueToEnumerationType (const CompilerType &enum_type, const Declaration &decl, const char *name, const llvm::APSInt &value)
CompilerType GetEnumerationIntegerType (CompilerType type)
Returns the underlying integer type for an enum type.
LLVM_DUMP_METHOD void dump (lldb::opaque_compiler_type_t type) const override
Convenience LLVM-style dump method for use in the debugger only.
void Dump (llvm::raw_ostream &output, llvm::StringRef filter, bool show_color) override
void DumpFromSymbolFile (Stream &s, llvm::StringRef symbol_name)
Dump clang AST types from the symbol file.
bool DumpTypeValue (lldb::opaque_compiler_type_t type, Stream &s, lldb::Format format, const DataExtractor &data, lldb::offset_t data_offset, size_t data_byte_size, uint32_t bitfield_bit_size, uint32_t bitfield_bit_offset, ExecutionContextScope *exe_scope) override
void DumpTypeDescription (lldb::opaque_compiler_type_t type, lldb::DescriptionLevel level=lldb::eDescriptionLevelFull) override
Dump the type to stdout.
void DumpTypeDescription (lldb::opaque_compiler_type_t type, Stream &s, lldb::DescriptionLevel level=lldb::eDescriptionLevelFull) override
Print a description of the type to a stream.
clang::ClassTemplateDecl * ParseClassTemplateDecl (clang::DeclContext *decl_ctx, OptionalClangModuleID owning_module, lldb::AccessType access_type, const char *parent_name, int tag_decl_kind, const TypeSystemClang::TemplateParameterInfos &template_param_infos)
clang::BlockDecl * CreateBlockDeclaration (clang::DeclContext *ctx, OptionalClangModuleID owning_module)
clang::UsingDirectiveDecl * CreateUsingDirectiveDeclaration (clang::DeclContext *decl_ctx, OptionalClangModuleID owning_module, clang::NamespaceDecl *ns_decl)
clang::UsingDecl * CreateUsingDeclaration (clang::DeclContext *current_decl_ctx, OptionalClangModuleID owning_module, clang::NamedDecl *target)
clang::VarDecl * CreateVariableDeclaration (clang::DeclContext *decl_context, OptionalClangModuleID owning_module, const char *name, clang::QualType type)
clang::DeclarationName GetDeclarationName (llvm::StringRef name, const CompilerType &function_clang_type)
clang::LangOptions * GetLangOpts () const
clang::SourceManager * GetSourceMgr () const
bool SetDeclIsForcefullyCompleted (const clang::TagDecl *td)
Public Member Functions inherited from lldb_private::TypeSystem
TypeSystem ()
~TypeSystem () override
virtual SymbolFile * GetSymbolFile () const
virtual void SetSymbolFile (SymbolFile *sym_file)
virtual ConstString GetMangledTypeName (lldb::opaque_compiler_type_t type)
Defaults to GetTypeName(type).
virtual bool ShouldTreatScalarValueAsAddress (lldb::opaque_compiler_type_t type)
virtual UserExpression * GetUserExpression (llvm::StringRef expr, llvm::StringRef prefix, SourceLanguage language, Expression::ResultType desired_type, const EvaluateExpressionOptions &options, ValueObject *ctx_obj)
virtual FunctionCaller * GetFunctionCaller (const CompilerType &return_type, const Address &function_address, const ValueList &arg_value_list, const char *name)
virtual std::unique_ptr< UtilityFunction > CreateUtilityFunction (std::string text, std::string name)
virtual PersistentExpressionState * GetPersistentExpressionState ()
virtual LazyBool ShouldPrintAsOneLiner (void *type, ValueObject *valobj)
virtual bool IsMeaninglessWithoutDynamicResolution (void *type)
virtual std::optional< llvm::json::Value > ReportStatistics ()
bool GetHasForcefullyCompletedTypes () const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static bool classof (const TypeSystem *ts)
static llvm::StringRef GetPluginNameStatic ()
static lldb::TypeSystemSP CreateInstance (lldb::LanguageType language, Module *module, Target *target)
static LanguageSet GetSupportedLanguagesForTypes ()
static LanguageSet GetSupportedLanguagesForExpressions ()
static void Initialize ()
static void Terminate ()
static TypeSystemClang * GetASTContext (clang::ASTContext *ast_ctx)
static void DumpDeclHiearchy (clang::Decl *decl)
static void DumpDeclContextHiearchy (clang::DeclContext *decl_ctx)
static bool GetCompleteDecl (clang::ASTContext *ast, clang::Decl *decl)
static lldb::BasicType GetBasicTypeEnumeration (llvm::StringRef name)
static clang::DeclContext * GetDeclContextForType (clang::QualType type)
static clang::DeclContext * GetDeclContextForType (const CompilerType &type)
static bool AreTypesSame (CompilerType type1, CompilerType type2, bool ignore_qualifiers=false)
static bool IsOperator (llvm::StringRef name, clang::OverloadedOperatorKind &op_kind)
static clang::AccessSpecifier ConvertAccessTypeToAccessSpecifier (lldb::AccessType access)
static clang::DeclContext * GetAsDeclContext (clang::FunctionDecl *function_decl)
static bool CheckOverloadedOperatorKindParameterCount (bool is_method, clang::OverloadedOperatorKind op_kind, uint32_t num_params)
static CompilerType GetFloatTypeFromBitSize (clang::ASTContext *ast, size_t bit_size)
static void SetOwningModule (clang::Decl *decl, OptionalClangModuleID owning_module)
Set the owning module for decl.
static clang::DeclContext * DeclContextGetAsDeclContext (const CompilerDeclContext &dc)
static clang::ObjCMethodDecl * DeclContextGetAsObjCMethodDecl (const CompilerDeclContext &dc)
static clang::CXXMethodDecl * DeclContextGetAsCXXMethodDecl (const CompilerDeclContext &dc)
static clang::FunctionDecl * DeclContextGetAsFunctionDecl (const CompilerDeclContext &dc)
static clang::NamespaceDecl * DeclContextGetAsNamespaceDecl (const CompilerDeclContext &dc)
static std::optional< ClangASTMetadata > DeclContextGetMetaData (const CompilerDeclContext &dc, const clang::Decl *object)
static clang::ASTContext * DeclContextGetTypeSystemClang (const CompilerDeclContext &dc)
static bool IsCXXClassType (const CompilerType &type)
static bool IsObjCClassType (const CompilerType &type)
static bool IsObjCObjectOrInterfaceType (const CompilerType &type)
static bool IsObjCObjectPointerType (const CompilerType &type, CompilerType *target_type=nullptr)
static bool IsClassType (lldb::opaque_compiler_type_t type)
static bool IsEnumType (lldb::opaque_compiler_type_t type)
static std::optional< std::string > GetCXXClassName (const CompilerType &type)
static uint32_t GetNumPointeeChildren (clang::QualType type)
static clang::FieldDecl * AddFieldToRecordType (const CompilerType &type, llvm::StringRef name, const CompilerType &field_type, lldb::AccessType access, uint32_t bitfield_bit_size)
static void BuildIndirectFields (const CompilerType &type)
static void SetIsPacked (const CompilerType &type)
static clang::VarDecl * AddVariableToRecordType (const CompilerType &type, llvm::StringRef name, const CompilerType &var_type, lldb::AccessType access)
static void SetIntegerInitializerForVariable (clang::VarDecl *var, const llvm::APInt &init_value)
Initializes a variable with an integer value.
static void SetFloatingInitializerForVariable (clang::VarDecl *var, const llvm::APFloat &init_value)
Initializes a variable with a floating point value.
static bool SetObjCSuperClass (const CompilerType &type, const CompilerType &superclass_compiler_type)
static bool AddObjCClassProperty (const CompilerType &type, const char *property_name, const CompilerType &property_compiler_type, clang::ObjCIvarDecl *ivar_decl, const char *property_setter_name, const char *property_getter_name, uint32_t property_attributes, ClangASTMetadata metadata)
static clang::ObjCMethodDecl * AddMethodToObjCObjectType (const CompilerType &type, const char *name, const CompilerType &method_compiler_type, bool is_artificial, bool is_variadic, bool is_objc_direct_call)
static bool SetHasExternalStorage (lldb::opaque_compiler_type_t type, bool has_extern)
static bool StartTagDeclarationDefinition (const CompilerType &type)
static bool CompleteTagDeclarationDefinition (const CompilerType &type)
static CompilerType CreateMemberPointerType (const CompilerType &type, const CompilerType &pointee_type)
static void DumpTypeName (const CompilerType &type)
static clang::EnumDecl * GetAsEnumDecl (const CompilerType &type)
static clang::RecordDecl * GetAsRecordDecl (const CompilerType &type)
static clang::TagDecl * GetAsTagDecl (const CompilerType &type)
static clang::TypedefNameDecl * GetAsTypedefDecl (const CompilerType &type)
static clang::CXXRecordDecl * GetAsCXXRecordDecl (lldb::opaque_compiler_type_t type)
static clang::ObjCInterfaceDecl * GetAsObjCInterfaceDecl (const CompilerType &type)
static lldb::opaque_compiler_type_t GetOpaqueCompilerType (clang::ASTContext *ast, lldb::BasicType basic_type)
static clang::QualType GetQualType (lldb::opaque_compiler_type_t type)
static clang::QualType GetCanonicalQualType (lldb::opaque_compiler_type_t type)
static void RequireCompleteType (CompilerType type)
Complete a type from debug info, or mark it as forcefully completed if there is no definition of the type in the current Module.
Static Public Member Functions inherited from lldb_private::TypeSystem
static lldb::TypeSystemSP CreateInstance (lldb::LanguageType language, Module *module)
static lldb::TypeSystemSP CreateInstance (lldb::LanguageType language, Target *target)
static bool SupportsLanguageStatic (lldb::LanguageType language)
Private Types
typedef llvm::DenseMap< const clang::Decl *, ClangASTMetadata > DeclMetadataMap
typedef llvm::DenseMap< const clang::Type *, ClangASTMetadata > TypeMetadataMap
Private Member Functions
clang::PrintingPolicy GetTypePrintingPolicy ()
Returns the PrintingPolicy used when generating the internal type names.
std::string GetTypeNameForDecl (const clang::NamedDecl *named_decl, bool qualified=true)
Returns the internal type name for the given NamedDecl using the type printing policy.
const clang::ClassTemplateSpecializationDecl * GetAsTemplateSpecialization (lldb::opaque_compiler_type_t type)
bool IsTypeImpl (lldb::opaque_compiler_type_t type, llvm::function_ref< bool(clang::QualType)> predicate) const
void LogCreation () const
Emits information about this TypeSystem into the expression log.
llvm::Expected< uint64_t > GetObjCBitSize (clang::QualType qual_type, ExecutionContextScope *exe_scope)
TypeSystemClang (const TypeSystemClang &)
const TypeSystemClang & operator= (const TypeSystemClang &)
void CreateASTContext ()
Creates the internal ASTContext.
void SetTargetTriple (llvm::StringRef target_triple)
Private Attributes
std::string m_target_triple
std::unique_ptr< clang::ASTContext > m_ast_up
std::unique_ptr< clang::LangOptions > m_language_options_up
std::unique_ptr< clang::FileManager > m_file_manager_up
std::unique_ptr< clang::SourceManager > m_source_manager_up
std::unique_ptr< clang::DiagnosticOptions > m_diagnostic_options_up
std::unique_ptr< clang::DiagnosticsEngine > m_diagnostics_engine_up
std::unique_ptr< clang::DiagnosticConsumer > m_diagnostic_consumer_up
std::shared_ptr< clang::TargetOptions > m_target_options_rp
std::unique_ptr< clang::TargetInfo > m_target_info_up
std::unique_ptr< clang::IdentifierTable > m_identifier_table_up
std::unique_ptr< clang::SelectorTable > m_selector_table_up
std::unique_ptr< clang::Builtin::Context > m_builtins_up
std::unique_ptr< clang::HeaderSearchOptions > m_header_search_opts_up
std::unique_ptr< clang::HeaderSearch > m_header_search_up
std::unique_ptr< clang::ModuleMap > m_module_map_up
std::unique_ptr< DWARFASTParserClang > m_dwarf_ast_parser_up
std::unique_ptr< PDBASTParser > m_pdb_ast_parser_up
std::unique_ptr< npdb::PdbAstBuilderClang > m_native_pdb_ast_parser_up
std::unique_ptr< clang::MangleContext > m_mangle_ctx_up
uint32_t m_pointer_byte_size = 0
bool m_ast_owned = false
std::string m_display_name
A string describing what this TypeSystemClang represents (e.g., AST for debug information, an expression, some other utility ClangAST).
DeclMetadataMap m_decl_metadata
Maps Decls to their associated ClangASTMetadata.
TypeMetadataMap m_type_metadata
Maps Types to their associated ClangASTMetadata.
clang::Sema * m_sema = nullptr
The sema associated that is currently used to build this ASTContext.
Static Private Attributes
static char ID
Additional Inherited Members
Protected Attributes inherited from lldb_private::TypeSystem
SymbolFile * m_sym_file = nullptr
bool m_has_forcefully_completed_types = false
Used for reporting statistics.
Detailed Description
A TypeSystem implementation based on Clang.
This class uses a single clang::ASTContext as the backend for storing its types and declarations. Every clang::ASTContext should also just have a single associated TypeSystemClang instance that manages it.
The clang::ASTContext instance can either be created by TypeSystemClang itself or it can adopt an existing clang::ASTContext (for example, when it is necessary to provide a TypeSystem interface for an existing clang::ASTContext that was created by clang::CompilerInstance).
Definition at line 117 of file TypeSystemClang.h.
Member Typedef Documentation
CompleteObjCInterfaceDeclCallback
typedef void(* lldb_private::TypeSystemClang::CompleteObjCInterfaceDeclCallback) (void *baton, clang::ObjCInterfaceDecl *)
Definition at line 123 of file TypeSystemClang.h.
CompleteTagDeclCallback
typedef void(* lldb_private::TypeSystemClang::CompleteTagDeclCallback) (void *baton, clang::TagDecl *)
Definition at line 122 of file TypeSystemClang.h.
DeclMetadataMap
typedef llvm::DenseMap<const clang::Decl *, ClangASTMetadata> lldb_private::TypeSystemClang::DeclMetadataMap private
Definition at line 1231 of file TypeSystemClang.h.
TypeMetadataMap
typedef llvm::DenseMap<const clang::Type *, ClangASTMetadata> lldb_private::TypeSystemClang::TypeMetadataMap private
Definition at line 1235 of file TypeSystemClang.h.
Constructor & Destructor Documentation
TypeSystemClang() [1/3]
TypeSystemClang::TypeSystemClang (llvm::StringRef name, llvm::Triple triple) explicit
Constructs a TypeSystemClang with an ASTContext using the given triple.
Parameters
name The name for the TypeSystemClang (for logging purposes)
triple The llvm::Triple used for the ASTContext. The triple defines certain characteristics of the ASTContext and its types (e.g., whether certain primitive types exist or what their signedness is).
Definition at line 485 of file TypeSystemClang.cpp.
References CreateASTContext(), LogCreation(), m_display_name, and SetTargetTriple().
Referenced by AddFieldToRecordType(), AddMethodToObjCObjectType(), AddObjCClassProperty(), AddVariableToRecordType(), AreTypesSame(), BuildIndirectFields(), CompleteTagDeclarationDefinition(), CreateMemberPointerType(), DeclContextGetMetaData(), DeclContextGetTypeSystemClang(), GetASTContext(), lldb_private::ScratchTypeSystemClang::GetIsolatedAST(), operator=(), RequireCompleteType(), lldb_private::ScratchTypeSystemClang::ScratchTypeSystemClang(), SetIsPacked(), SetObjCSuperClass(), and TypeSystemClang().
TypeSystemClang() [2/3]
lldb_private::TypeSystemClang::TypeSystemClang (llvm::StringRef name, clang::ASTContext & existing_ctxt) explicit
Constructs a TypeSystemClang that uses an existing ASTContext internally.
Useful when having an existing ASTContext created by Clang.
Parameters
name The name for the TypeSystemClang (for logging purposes)
existing_ctxt An existing ASTContext.
~TypeSystemClang()
TypeSystemClang::~TypeSystemClang () override
Definition at line 509 of file TypeSystemClang.cpp.
References Finalize().
TypeSystemClang() [3/3]
lldb_private::TypeSystemClang::TypeSystemClang (const TypeSystemClang &) private
References TypeSystemClang().
Member Function Documentation
AddConstModifier()
CompilerType TypeSystemClang::AddConstModifier (lldb::opaque_compiler_type_t type) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 4540 of file TypeSystemClang.cpp.
References GetQualType(), and GetType().
AddEnumerationValueToEnumerationType() [1/2]
clang::EnumConstantDecl * TypeSystemClang::AddEnumerationValueToEnumerationType (const CompilerType & enum_type, const Declaration & decl, const char * name, const llvm::APSInt & value)
Definition at line 8434 of file TypeSystemClang.cpp.
References getASTContext(), GetCanonicalQualType(), lldb_private::CompilerType::GetOpaqueQualType(), lldb_private::CompilerType::TypeSystemSPWrapper::GetSharedPointer(), lldb_private::CompilerType::GetTypeSystem(), lldbassert, SetMemberOwningModule(), and lldb_private::TypeSystem::TypeSystem().
AddEnumerationValueToEnumerationType() [2/2]
clang::EnumConstantDecl * TypeSystemClang::AddEnumerationValueToEnumerationType (const CompilerType & enum_type, const Declaration & decl, const char * name, uint64_t enum_value, uint32_t enum_value_bit_size)
Definition at line 8484 of file TypeSystemClang.cpp.
References AddEnumerationValueToEnumerationType(), lldb_private::CompilerType::IsEnumerationIntegerTypeSigned(), and lldb_private::CompilerType::IsEnumerationType().
Referenced by AddEnumerationValueToEnumerationType().
AddFieldToRecordType()
clang::FieldDecl * TypeSystemClang::AddFieldToRecordType (const CompilerType & type, llvm::StringRef name, const CompilerType & field_type, lldb::AccessType access, uint32_t bitfield_bit_size) static
Definition at line 7384 of file TypeSystemClang.cpp.
References lldb_private::Expressions, lldb_private::CompilerType::GetCompleteType(), lldb_private::GetLog(), lldb_private::ClangUtil::GetQualType(), lldb_private::CompilerType::GetTypeSystem(), lldb_private::CompilerType::IsValid(), LLDB_LOG, SetMemberOwningModule(), and TypeSystemClang().
Referenced by lldb_private::npdb::UdtRecordCompleter::AddMember(), PDBASTParser::AddRecordMembers(), DWARFASTParserClang::AddUnnamedBitfieldToRecordTypeIfNeeded(), lldb_private::AppleObjCTypeEncodingParser::BuildAggregate(), lldb_private::SymbolFileCTF::CompleteType(), CreateStructForIdentifier(), GetLLDBNSPairType(), lldb_private::platform_freebsd::PlatformFreeBSD::GetSiginfoType(), lldb_private::platform_linux::PlatformLinux::GetSiginfoType(), lldb_private::platform_netbsd::PlatformNetBSD::GetSiginfoType(), DWARFASTParserClang::ParseSingleMember(), and SystemRuntimeMacOSX::ReadLibdispatchTSDIndexes().
AddMethodOverridesForCXXRecordType()
void TypeSystemClang::AddMethodOverridesForCXXRecordType (lldb::opaque_compiler_type_t type)
Definition at line 7879 of file TypeSystemClang.cpp.
References GetAsCXXRecordDecl().
AddMethodToCXXRecordType()
clang::CXXMethodDecl * TypeSystemClang::AddMethodToCXXRecordType (lldb::opaque_compiler_type_t type, llvm::StringRef name, llvm::StringRef asm_label, const CompilerType & method_type, lldb::AccessType access, bool is_virtual, bool is_static, bool is_inline, bool is_explicit, bool is_attr_used, bool is_artificial)
Definition at line 7701 of file TypeSystemClang.cpp.
References CheckOverloadedOperatorKindParameterCount(), CreateParameterDeclarations(), getASTContext(), GetCanonicalQualType(), lldb_private::ClangUtil::GetQualType(), IsOperator(), lldb_private::CompilerType::IsValid(), and SetMemberOwningModule().
AddMethodToObjCObjectType()
clang::ObjCMethodDecl * TypeSystemClang::AddMethodToObjCObjectType (const CompilerType & type, const char * name, const CompilerType & method_compiler_type, bool is_artificial, bool is_variadic, bool is_objc_direct_call) static
Force this to true because we don't have source locations.
Definition at line 8148 of file TypeSystemClang.cpp.
References GetAsObjCInterfaceDecl(), lldb_private::ClangUtil::GetQualType(), lldb_private::CompilerType::GetTypeSystem(), lldb_private::CompilerType::IsValid(), SetMemberOwningModule(), and TypeSystemClang().
AddObjCClassProperty()
bool TypeSystemClang::AddObjCClassProperty (const CompilerType & type, const char * property_name, const CompilerType & property_compiler_type, clang::ObjCIvarDecl * ivar_decl, const char * property_setter_name, const char * property_getter_name, uint32_t property_attributes, ClangASTMetadata metadata) static
Definition at line 7943 of file TypeSystemClang.cpp.
References GetAsObjCInterfaceDecl(), lldb_private::ClangUtil::GetQualType(), lldb_private::CompilerType::GetTypeSystem(), lldb_private::CompilerType::IsValid(), SetMemberOwningModule(), and TypeSystemClang().
Referenced by DWARFASTParserClang::DelayedAddObjCClassProperty::Finalize().
AddPtrAuthModifier()
CompilerType TypeSystemClang::AddPtrAuthModifier (lldb::opaque_compiler_type_t type, uint32_t payload) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 4550 of file TypeSystemClang.cpp.
References getASTContext(), GetQualType(), and GetType().
AddRestrictModifier()
CompilerType TypeSystemClang::AddRestrictModifier (lldb::opaque_compiler_type_t type) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 4573 of file TypeSystemClang.cpp.
References GetQualType(), and GetType().
AddVariableToRecordType()
clang::VarDecl * TypeSystemClang::AddVariableToRecordType (const CompilerType & type, llvm::StringRef name, const CompilerType & var_type, lldb::AccessType access) static
Definition at line 7602 of file TypeSystemClang.cpp.
References lldb_private::ClangUtil::GetQualType(), lldb_private::CompilerType::GetTypeSystem(), lldb_private::CompilerType::IsValid(), SetMemberOwningModule(), and TypeSystemClang().
Referenced by PDBASTParser::AddRecordMembers(), and DWARFASTParserClang::CreateStaticMemberVariable().
AddVolatileModifier()
CompilerType TypeSystemClang::AddVolatileModifier (lldb::opaque_compiler_type_t type) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 4563 of file TypeSystemClang.cpp.
References GetQualType(), and GetType().
AreTypesSame()
bool TypeSystemClang::AreTypesSame (CompilerType type1, CompilerType type2, bool ignore_qualifiers = false) static
Definition at line 1161 of file TypeSystemClang.cpp.
References lldb_private::CompilerType::GetOpaqueQualType(), lldb_private::ClangUtil::GetQualType(), lldb_private::CompilerType::GetTypeSystem(), and TypeSystemClang().
Referenced by CountDeclLevels(), and lldb_private::ItaniumABILanguageRuntime::GetDynamicTypeAndAddress().
BaseSpecifierIsEmpty()
bool TypeSystemClang::BaseSpecifierIsEmpty (const clang::CXXBaseSpecifier * b)
Definition at line 1826 of file TypeSystemClang.cpp.
References RecordHasFields().
Referenced by GetIndexForRecordBase(), and GetNumBaseClasses().
BuildIndirectFields()
void TypeSystemClang::BuildIndirectFields (const CompilerType & type) static
Definition at line 7480 of file TypeSystemClang.cpp.
References lldb_private::CompilerType::GetTypeSystem(), SetMemberOwningModule(), and TypeSystemClang().
Referenced by lldb_private::npdb::UdtRecordCompleter::complete(), DWARFASTParserClang::CompleteRecordType(), and PDBASTParser::CompleteTypeFromUDT().
CanPassInRegisters()
bool TypeSystemClang::CanPassInRegisters (const CompilerType & type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3629 of file TypeSystemClang.cpp.
References GetAsRecordDecl().
CheckOverloadedOperatorKindParameterCount()
bool TypeSystemClang::CheckOverloadedOperatorKindParameterCount (bool is_method, clang::OverloadedOperatorKind op_kind, uint32_t num_params) static
Definition at line 1724 of file TypeSystemClang.cpp.
Referenced by lldb_private::NameSearchContext::AddFunDecl(), AddMethodToCXXRecordType(), and GetDeclarationName().
classof()
bool lldb_private::TypeSystemClang::classof (const TypeSystem * ts) inline static
Definition at line 128 of file TypeSystemClang.h.
References ID, lldb_private::TypeSystem::isA(), and lldb_private::TypeSystem::TypeSystem().
CompleteObjCInterfaceDecl()
void TypeSystemClang::CompleteObjCInterfaceDecl (clang::ObjCInterfaceDecl * decl)
Definition at line 9014 of file TypeSystemClang.cpp.
References lldb_private::SymbolFile::CompleteType(), lldb_private::TypeSystem::GetSymbolFile(), and GetTypeForDecl().
CompleteTagDecl()
void TypeSystemClang::CompleteTagDecl (clang::TagDecl * decl)
Definition at line 9005 of file TypeSystemClang.cpp.
References lldb_private::SymbolFile::CompleteType(), lldb_private::TypeSystem::GetSymbolFile(), and GetTypeForDecl().
CompleteTagDeclarationDefinition()
bool TypeSystemClang::CompleteTagDeclarationDefinition (const CompilerType & type) static
Definition at line 8360 of file TypeSystemClang.cpp.
References lldb_private::ClangUtil::GetQualType(), lldb_private::CompilerType::GetTypeSystem(), and TypeSystemClang().
Referenced by lldb_private::npdb::UdtRecordCompleter::AddMember(), PDBASTParser::AddRecordBases(), PDBASTParser::AddRecordMembers(), PDBASTParser::AddRecordMethod(), lldb_private::AppleObjCTypeEncodingParser::BuildAggregate(), lldb_private::npdb::UdtRecordCompleter::complete(), DWARFASTParserClang::CompleteEnumType(), DWARFASTParserClang::CompleteRecordType(), lldb_private::ClangASTImporter::CompleteType(), DWARFASTParserClang::CompleteTypeFromDWARF(), PDBASTParser::CompleteTypeFromUDT(), lldb_private::SymbolFileCTF::CreateEnum(), PDBASTParser::CreateLLDBTypeFromPDBType(), CreateStructForIdentifier(), GetLLDBNSPairType(), lldb_private::platform_freebsd::PlatformFreeBSD::GetSiginfoType(), lldb_private::platform_linux::PlatformLinux::GetSiginfoType(), lldb_private::platform_netbsd::PlatformNetBSD::GetSiginfoType(), PrepareContextToReceiveMembers(), SystemRuntimeMacOSX::ReadLibdispatchTSDIndexes(), and RequireCompleteType().
ConvertAccessTypeToAccessSpecifier()
clang::AccessSpecifier TypeSystemClang::ConvertAccessTypeToAccessSpecifier (lldb::AccessType access) static
Definition at line 450 of file TypeSystemClang.cpp.
References lldb::eAccessNone, lldb::eAccessPrivate, lldb::eAccessProtected, and lldb::eAccessPublic.
Referenced by CreateBaseClassSpecifier().
CountDeclLevels()
uint32_t TypeSystemClang::CountDeclLevels (clang::DeclContext * frame_decl_ctx, clang::DeclContext * child_decl_ctx, ConstString * child_name = nullptr, CompilerType * child_type = nullptr)
Definition at line 9349 of file TypeSystemClang.cpp.
References AreTypesSame(), lldb_private::ConstString::AsCString(), CreateDeclContext(), lldb_private::TypeSystem::GetSymbolFile(), GetTypeForDecl(), LLDB_INVALID_DECL_LEVEL, and lldb_private::SymbolFile::ParseDeclsForContext().
Referenced by lldb_private::ClangExpressionDeclMap::SearchFunctionsInSymbolContexts().
CreateArrayType()
CompilerType TypeSystemClang::CreateArrayType (const CompilerType & element_type, std::optional< size_t > element_count, bool is_vector)
Definition at line 2249 of file TypeSystemClang.cpp.
References getASTContext(), lldb_private::ClangUtil::GetQualType(), GetType(), and lldb_private::CompilerType::IsValid().
Referenced by lldb_private::AppleObjCTypeEncodingParser::BuildArray().
CreateASTContext()
void TypeSystemClang::CreateASTContext () private
Creates the internal ASTContext.
Definition at line 653 of file TypeSystemClang.cpp.
References lldb_private::Expressions, GetASTMap(), lldb_private::GetLog(), getTargetInfo(), GetTargetTriple(), lldb_private::ThreadSafeDenseMap< _KeyType, _ValueType >::Insert(), lldb_private::FileSystem::Instance(), LLDB_LOG, m_ast_owned, m_ast_up, m_builtins_up, m_diagnostic_consumer_up, m_diagnostic_options_up, m_diagnostics_engine_up, m_file_manager_up, m_identifier_table_up, m_language_options_up, m_selector_table_up, m_source_manager_up, m_target_triple, ParseLangArgs(), lldb_private::Debugger::ReportWarning(), and SetExternalSource().
Referenced by TypeSystemClang().
CreateBaseClassSpecifier()
std::unique_ptr< clang::CXXBaseSpecifier > TypeSystemClang::CreateBaseClassSpecifier (lldb::opaque_compiler_type_t type, lldb::AccessType access, bool is_virtual, bool base_of_class)
Definition at line 7889 of file TypeSystemClang.cpp.
References ConvertAccessTypeToAccessSpecifier(), getASTContext(), and GetQualType().
CreateBlockDeclaration()
clang::BlockDecl * TypeSystemClang::CreateBlockDeclaration (clang::DeclContext * ctx, OptionalClangModuleID owning_module)
Definition at line 1917 of file TypeSystemClang.cpp.
References getASTContext(), and SetOwningModule().
CreateBlockPointerType()
CompilerType TypeSystemClang::CreateBlockPointerType (const CompilerType & function_type)
Definition at line 2239 of file TypeSystemClang.cpp.
References lldb_private::CompilerType::GetOpaqueQualType(), GetType(), and m_ast_up.
CreateClassTemplateDecl()
ClassTemplateDecl * TypeSystemClang::CreateClassTemplateDecl (clang::DeclContext * decl_ctx, OptionalClangModuleID owning_module, lldb::AccessType access_type, llvm::StringRef class_name, int kind, const TemplateParameterInfos & infos)
Definition at line 1552 of file TypeSystemClang.cpp.
References ClassTemplateAllowsToInstantiationArgs(), CreateTemplateParameterList(), getASTContext(), and SetOwningModule().
Referenced by ParseClassTemplateDecl().
CreateClassTemplateSpecializationDecl()
ClassTemplateSpecializationDecl * TypeSystemClang::CreateClassTemplateSpecializationDecl (clang::DeclContext * decl_ctx, OptionalClangModuleID owning_module, clang::ClassTemplateDecl * class_template_decl, int kind, const TemplateParameterInfos & infos)
Definition at line 1651 of file TypeSystemClang.cpp.
References lldb_private::TypeSystemClang::TemplateParameterInfos::GetArgs(), getASTContext(), lldb_private::TypeSystemClang::TemplateParameterInfos::GetParameterPackArgs(), lldb_private::TypeSystemClang::TemplateParameterInfos::hasParameterPack(), SetOwningModule(), and lldb_private::TypeSystemClang::TemplateParameterInfos::Size().
CreateClassTemplateSpecializationType()
CompilerType TypeSystemClang::CreateClassTemplateSpecializationType (clang::ClassTemplateSpecializationDecl * class_template_specialization_decl)
Definition at line 1696 of file TypeSystemClang.cpp.
References getASTContext(), and GetType().
CreateDeclContext()
CompilerDeclContext TypeSystemClang::CreateDeclContext (clang::DeclContext * ctx)
Creates a CompilerDeclContext from the given DeclContext with the current TypeSystemClang instance as its typesystem.
The DeclContext has to come from the ASTContext of this TypeSystemClang.
Definition at line 1191 of file TypeSystemClang.cpp.
References getASTContext().
Referenced by CountDeclLevels(), DeclContextFindDeclByName(), DeclGetDeclContext(), GetCompilerDeclContextForType(), SymbolFilePDB::GetDeclContextContainingUID(), and SymbolFilePDB::GetDeclContextForUID().
CreateEnumerationType()
CompilerType TypeSystemClang::CreateEnumerationType (llvm::StringRef name, clang::DeclContext * decl_ctx, OptionalClangModuleID owning_module, const Declaration & decl, const CompilerType & integer_qual_type, bool is_scoped, std::optional< clang::EnumExtensibilityAttr::Kind > enum_kind = std::nullopt)
Definition at line 2317 of file TypeSystemClang.cpp.
References getASTContext(), lldb_private::ClangUtil::GetQualType(), GetType(), and SetOwningModule().
CreateFunctionDeclaration()
FunctionDecl * TypeSystemClang::CreateFunctionDeclaration (clang::DeclContext * decl_ctx, OptionalClangModuleID owning_module, llvm::StringRef name, const CompilerType & function_Type, clang::StorageClass storage, bool is_inline, llvm::StringRef asm_label)
Definition at line 2139 of file TypeSystemClang.cpp.
References getASTContext(), GetDeclarationName(), lldb_private::ClangUtil::GetQualType(), and SetOwningModule().
CreateFunctionTemplateDecl()
clang::FunctionTemplateDecl * TypeSystemClang::CreateFunctionTemplateDecl (clang::DeclContext * decl_ctx, OptionalClangModuleID owning_module, clang::FunctionDecl * func_decl, const TemplateParameterInfos & infos)
Definition at line 1417 of file TypeSystemClang.cpp.
References CreateTemplateParameterList(), getASTContext(), and SetOwningModule().
CreateFunctionTemplateSpecializationInfo()
void TypeSystemClang::CreateFunctionTemplateSpecializationInfo (clang::FunctionDecl * func_decl, clang::FunctionTemplateDecl * Template, const TemplateParameterInfos & infos)
Definition at line 1446 of file TypeSystemClang.cpp.
References lldb_private::TypeSystemClang::TemplateParameterInfos::GetArgs().
CreateFunctionType()
CompilerType TypeSystemClang::CreateFunctionType (const CompilerType & result_type, llvm::ArrayRef< CompilerType > args, bool is_variadic, unsigned type_quals, clang::CallingConv cc = clang::CC_C, clang::RefQualifierKind ref_qual = clang::RQ_None)
Definition at line 2185 of file TypeSystemClang.cpp.
References getASTContext(), lldb_private::ClangUtil::GetQualType(), GetType(), lldb_private::ClangUtil::IsClangType(), and lldbassert.
CreateGenericFunctionPrototype()
CompilerType TypeSystemClang::CreateGenericFunctionPrototype () override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 4644 of file TypeSystemClang.cpp.
References getASTContext(), and GetType().
CreateInstance()
lldb::TypeSystemSP TypeSystemClang::CreateInstance (lldb::LanguageType language, lldb_private::Module * module, Target * target) static
Definition at line 511 of file TypeSystemClang.cpp.
References lldb_private::Target::GetArchitecture(), lldb_private::ArchSpec::GetTriple(), lldb_private::ArchSpec::IsValid(), and lldb_private::Target::IsValid().
Referenced by Initialize(), and Terminate().
CreateMemberPointerType()
CompilerType TypeSystemClang::CreateMemberPointerType (const CompilerType & type, const CompilerType & pointee_type) static
Definition at line 8506 of file TypeSystemClang.cpp.
References lldb_private::ClangUtil::GetQualType(), lldb_private::CompilerType::GetTypeSystem(), lldb_private::CompilerType::IsValid(), and TypeSystemClang().
Referenced by PDBASTParser::CreateLLDBTypeFromPDBType(), and DWARFASTParserClang::ParsePointerToMemberType().
CreateObjCClass()
CompilerType TypeSystemClang::CreateObjCClass (llvm::StringRef name, clang::DeclContext * decl_ctx, OptionalClangModuleID owning_module, bool isInternal, std::optional< ClangASTMetadata > metadata = std::nullopt)
Definition at line 1804 of file TypeSystemClang.cpp.
References getASTContext(), GetType(), SetMetadata(), and SetOwningModule().
Referenced by CreateRecordType().
CreateParameterDeclaration()
ParmVarDecl * TypeSystemClang::CreateParameterDeclaration (clang::DeclContext * decl_ctx, OptionalClangModuleID owning_module, const char * name, const CompilerType & param_type, int storage, bool add_decl = false)
Definition at line 2220 of file TypeSystemClang.cpp.
References getASTContext(), lldb_private::ClangUtil::GetQualType(), and SetOwningModule().
Referenced by CreateParameterDeclarations().
CreateParameterDeclarations()
llvm::SmallVector< clang::ParmVarDecl * > TypeSystemClang::CreateParameterDeclarations (clang::FunctionDecl * context, const clang::FunctionProtoType & prototype, const llvm::SmallVector< llvm::StringRef > & param_names)
For each parameter type of prototype, creates a clang::ParmVarDecl whose clang::DeclContext is context.
Parameters
[in] context Non-null clang::FunctionDecl which will be the clang::DeclContext of each parameter created/returned by this function.
[in] prototype The clang::FunctionProtoType of context.
[in] param_names The ith element of this vector contains the name of the ith parameter. This parameter may be unnamed, in which case the ith entry in param_names is an empty string. This vector is either empty, or will have an entry for each parameter of the prototype regardless of whether a parameter is unnamed or not.
Returns
A list of newly created of non-null clang::ParmVarDecl (one for each parameter of prototype).
Definition at line 7676 of file TypeSystemClang.cpp.
References CreateParameterDeclaration(), and GetType().
Referenced by AddMethodToCXXRecordType().
CreateRecordType()
CompilerType TypeSystemClang::CreateRecordType (clang::DeclContext * decl_ctx, OptionalClangModuleID owning_module, lldb::AccessType access_type, llvm::StringRef name, int kind, lldb::LanguageType language, std::optional< ClangASTMetadata > metadata = std::nullopt, bool exports_symbols = false)
Definition at line 1268 of file TypeSystemClang.cpp.
References CreateObjCClass(), lldb::eLanguageTypeObjC, lldb::eLanguageTypeObjC_plus_plus, getASTContext(), GetType(), SetMetadata(), and SetOwningModule().
Referenced by lldb_private::AppleObjCTypeEncodingParser::BuildAggregate(), CreateStructForIdentifier(), lldb_private::platform_freebsd::PlatformFreeBSD::GetSiginfoType(), lldb_private::platform_linux::PlatformLinux::GetSiginfoType(), and lldb_private::platform_netbsd::PlatformNetBSD::GetSiginfoType().
CreateStructForIdentifier()
CompilerType TypeSystemClang::CreateStructForIdentifier (llvm::StringRef type_name, const std::initializer_list< std::pair< const char *, CompilerType > > & type_fields, bool packed = false)
Definition at line 2275 of file TypeSystemClang.cpp.
References AddFieldToRecordType(), CompleteTagDeclarationDefinition(), CreateRecordType(), lldb::eAccessPublic, lldb::eLanguageTypeC, getASTContext(), GetTypeForIdentifier(), lldbassert, SetIsPacked(), and StartTagDeclarationDefinition().
Referenced by GetOrCreateStructForIdentifier(), lldb_private::platform_freebsd::PlatformFreeBSD::GetSiginfoType(), lldb_private::platform_linux::PlatformLinux::GetSiginfoType(), and lldb_private::platform_netbsd::PlatformNetBSD::GetSiginfoType().
CreateTemplateTemplateParmDecl()
TemplateTemplateParmDecl * TypeSystemClang::CreateTemplateTemplateParmDecl (const char * template_name)
Definition at line 1626 of file TypeSystemClang.cpp.
References CreateTemplateParameterList(), and getASTContext().
CreateTypedef()
CompilerType TypeSystemClang::CreateTypedef (lldb::opaque_compiler_type_t type, const char * name, const CompilerDeclContext & decl_ctx, uint32_t opaque_payload) override virtual
Using the current type, create a new typedef to that type using "typedef_name" as the name and "decl_ctx" as the decl context.
Parameters
opaque_payload is an opaque TypePayloadClang.
Reimplemented from lldb_private::TypeSystem.
Definition at line 4582 of file TypeSystemClang.cpp.
References DeclContextGetAsDeclContext(), getASTContext(), GetQualType(), GetType(), and SetOwningModule().
CreateUsingDeclaration()
clang::UsingDecl * TypeSystemClang::CreateUsingDeclaration (clang::DeclContext * current_decl_ctx, OptionalClangModuleID owning_module, clang::NamedDecl * target)
Definition at line 1966 of file TypeSystemClang.cpp.
References getASTContext(), and SetOwningModule().
CreateUsingDirectiveDeclaration()
clang::UsingDirectiveDecl * TypeSystemClang::CreateUsingDirectiveDeclaration (clang::DeclContext * decl_ctx, OptionalClangModuleID owning_module, clang::NamespaceDecl * ns_decl)
Definition at line 1947 of file TypeSystemClang.cpp.
References FindLCABetweenDecls(), getASTContext(), and SetOwningModule().
CreateVariableDeclaration()
clang::VarDecl * TypeSystemClang::CreateVariableDeclaration (clang::DeclContext * decl_context, OptionalClangModuleID owning_module, const char * name, clang::QualType type)
Definition at line 1985 of file TypeSystemClang.cpp.
References getASTContext(), and SetOwningModule().
DeclContextFindDeclByName()
std::vector< CompilerDecl > TypeSystemClang::DeclContextFindDeclByName (void * opaque_decl_ctx, ConstString name, const bool ignore_using_decls) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 9253 of file TypeSystemClang.cpp.
References lldb_private::ConstString::AsCString(), CreateDeclContext(), GetCompilerDecl(), lldb_private::TypeSystem::GetSymbolFile(), and lldb_private::SymbolFile::ParseDeclsForContext().
DeclContextGetAsCXXMethodDecl()
CXXMethodDecl * TypeSystemClang::DeclContextGetAsCXXMethodDecl (const CompilerDeclContext & dc) static
Definition at line 9549 of file TypeSystemClang.cpp.
References lldb_private::CompilerDeclContext::GetOpaqueDeclContext(), and IsClangDeclContext().
Referenced by lldb_private::ClangExpressionDeclMap::LookUpLldbClass(), and lldb_private::ClangUserExpression::ScanContext().
DeclContextGetAsDeclContext()
clang::DeclContext * TypeSystemClang::DeclContextGetAsDeclContext (const CompilerDeclContext & dc) static
Definition at line 9534 of file TypeSystemClang.cpp.
References lldb_private::CompilerDeclContext::GetOpaqueDeclContext(), and IsClangDeclContext().
Referenced by CreateTypedef(), and DWARFASTParserClang::GetClangDeclForDIE().
DeclContextGetAsFunctionDecl()
clang::FunctionDecl * TypeSystemClang::DeclContextGetAsFunctionDecl (const CompilerDeclContext & dc) static
Definition at line 9557 of file TypeSystemClang.cpp.
References lldb_private::CompilerDeclContext::GetOpaqueDeclContext(), and IsClangDeclContext().
Referenced by lldb_private::ClangUserExpression::ScanContext().
DeclContextGetAsNamespaceDecl()
clang::NamespaceDecl * TypeSystemClang::DeclContextGetAsNamespaceDecl (const CompilerDeclContext & dc) static
Definition at line 9565 of file TypeSystemClang.cpp.
References lldb_private::CompilerDeclContext::GetOpaqueDeclContext(), and IsClangDeclContext().
Referenced by lldb_private::ClangASTSource::AddNamespace(), and DWARFASTParserClang::GetClangDeclForDIE().
DeclContextGetAsObjCMethodDecl()
ObjCMethodDecl * TypeSystemClang::DeclContextGetAsObjCMethodDecl (const CompilerDeclContext & dc) static
Definition at line 9541 of file TypeSystemClang.cpp.
References lldb_private::CompilerDeclContext::GetOpaqueDeclContext(), and IsClangDeclContext().
Referenced by lldb_private::ClangASTSource::FindObjCMethodDecls(), lldb_private::ClangExpressionDeclMap::LookUpLldbObjCClass(), and lldb_private::ClangUserExpression::ScanContext().
DeclContextGetCompilerContext()
std::vector< lldb_private::CompilerContext > TypeSystemClang::DeclContextGetCompilerContext (void * opaque_decl_ctx) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 9477 of file TypeSystemClang.cpp.
References InsertCompilerContext().
DeclContextGetLanguage()
lldb::LanguageType TypeSystemClang::DeclContextGetLanguage (void * opaque_decl_ctx) override virtual
Implements lldb_private::TypeSystem.
Definition at line 9512 of file TypeSystemClang.cpp.
References lldb::eLanguageTypeC_plus_plus, lldb::eLanguageTypeObjC, lldb::eLanguageTypeUnknown, and GetMetadata().
DeclContextGetMetaData()
std::optional< ClangASTMetadata > TypeSystemClang::DeclContextGetMetaData (const CompilerDeclContext & dc, const clang::Decl * object) static
Definition at line 9573 of file TypeSystemClang.cpp.
References GetMetadata(), lldb_private::CompilerDeclContext::GetTypeSystem(), and TypeSystemClang().
Referenced by lldb_private::ClangUserExpression::ScanContext().
DeclContextGetName()
ConstString TypeSystemClang::DeclContextGetName (void * opaque_decl_ctx) override virtual
Implements lldb_private::TypeSystem.
Definition at line 9431 of file TypeSystemClang.cpp.
References GetTypePrintingPolicy().
Referenced by InsertCompilerContext().
DeclContextGetScopeQualifiedName()
ConstString TypeSystemClang::DeclContextGetScopeQualifiedName (void * opaque_decl_ctx) override virtual
Implements lldb_private::TypeSystem.
Definition at line 9448 of file TypeSystemClang.cpp.
References GetTypeNameForDecl().
DeclContextGetTypeSystemClang()
clang::ASTContext * TypeSystemClang::DeclContextGetTypeSystemClang (const CompilerDeclContext & dc) static
Definition at line 9580 of file TypeSystemClang.cpp.
References getASTContext(), lldb_private::CompilerDeclContext::GetTypeSystem(), and TypeSystemClang().
Referenced by lldb_private::ClangASTSource::AddNamespace().
DeclContextIsClassMethod()
bool TypeSystemClang::DeclContextIsClassMethod (void * opaque_decl_ctx) override virtual
Implements lldb_private::TypeSystem.
Definition at line 9458 of file TypeSystemClang.cpp.
References GetMetadata().
DeclContextIsContainedInLookup()
bool TypeSystemClang::DeclContextIsContainedInLookup (void * opaque_decl_ctx, void * other_opaque_decl_ctx) override virtual
Implements lldb_private::TypeSystem.
Definition at line 9484 of file TypeSystemClang.cpp.
DeclGetCompilerContext()
std::vector< lldb_private::CompilerContext > TypeSystemClang::DeclGetCompilerContext (void * opaque_decl) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 9202 of file TypeSystemClang.cpp.
References DeclGetName(), GetCompilerKind(), and InsertCompilerContext().
DeclGetConstantValue()
Scalar TypeSystemClang::DeclGetConstantValue (void * opaque_decl) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 9236 of file TypeSystemClang.cpp.
References getASTContext().
DeclGetDeclContext()
CompilerDeclContext TypeSystemClang::DeclGetDeclContext (void * opaque_decl) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 9132 of file TypeSystemClang.cpp.
References CreateDeclContext().
DeclGetFunctionArgumentType()
CompilerType TypeSystemClang::DeclGetFunctionArgumentType (void * opaque_decl, size_t arg_idx) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 9218 of file TypeSystemClang.cpp.
References GetType().
DeclGetFunctionNumArguments()
size_t TypeSystemClang::DeclGetFunctionNumArguments (void * opaque_decl) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 9149 of file TypeSystemClang.cpp.
DeclGetFunctionReturnType()
CompilerType TypeSystemClang::DeclGetFunctionReturnType (void * opaque_decl) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 9138 of file TypeSystemClang.cpp.
References GetType().
DeclGetMangledName()
ConstString TypeSystemClang::DeclGetMangledName (void * opaque_decl) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 9092 of file TypeSystemClang.cpp.
References ExtractMangledNameFromFunctionCallLabel(), and getMangleContext().
DeclGetName()
ConstString TypeSystemClang::DeclGetName (void * opaque_decl) override virtual
Implements lldb_private::TypeSystem.
Definition at line 9067 of file TypeSystemClang.cpp.
References GetTypeNameForDecl().
Referenced by DeclGetCompilerContext().
DoIntegralPromotion()
llvm::Expected< CompilerType > TypeSystemClang::DoIntegralPromotion (CompilerType from, ExecutionContextScope * exe_scope) override virtual
Perform integral promotion on a given type.
This promotes eligible types (boolean, integers, unscoped enumerations) to a larger integer type according to type system rules.
Returns
Promoted type.
Reimplemented from lldb_private::TypeSystem.
Definition at line 7276 of file TypeSystemClang.cpp.
References DoIntegralPromotion(), lldb::eBasicTypeChar16, lldb::eBasicTypeChar32, lldb::eBasicTypeInt, lldb::eBasicTypeLong, lldb::eBasicTypeLongLong, lldb::eBasicTypeSignedWChar, lldb::eBasicTypeUnsignedInt, lldb::eBasicTypeUnsignedLong, lldb::eBasicTypeUnsignedLongLong, lldb::eBasicTypeUnsignedWChar, lldb::eBasicTypeWChar, GetAsEnumDecl(), lldb_private::CompilerType::GetBasicTypeEnumeration(), GetBasicTypeFromAST(), lldb_private::CompilerType::GetByteSize(), lldb_private::CompilerType::GetCanonicalType(), GetType(), lldb_private::CompilerType::IsInteger(), lldb_private::CompilerType::IsPromotableIntegerType(), lldb_private::CompilerType::IsSigned(), and lldb_private::CompilerType::IsUnscopedEnumerationType().
Referenced by DoIntegralPromotion().
Dump()
void TypeSystemClang::Dump (llvm::raw_ostream & output, llvm::StringRef filter, bool show_color) override virtual
See also
lldb_private::TypeSystem::Dump
Implements lldb_private::TypeSystem.
Definition at line 8548 of file TypeSystemClang.cpp.
References getASTContext(), and m_ast_up.
Referenced by lldb_private::ScratchTypeSystemClang::Dump(), and SymbolFilePDB::DumpClangAST().
dump()
LLVM_DUMP_METHOD void TypeSystemClang::dump (lldb::opaque_compiler_type_t type) const override virtual
Convenience LLVM-style dump method for use in the debugger only.
In contrast to the other Dump() methods this directly invokes clang::QualType::dump().
Implements lldb_private::TypeSystem.
Definition at line 8526 of file TypeSystemClang.cpp.
References GetQualType().
DumpDeclContextHiearchy()
void TypeSystemClang::DumpDeclContextHiearchy (clang::DeclContext * decl_ctx) static
Definition at line 2406 of file TypeSystemClang.cpp.
References DumpDeclContextHiearchy().
Referenced by DumpDeclContextHiearchy(), and DumpDeclHiearchy().
DumpDeclHiearchy()
void TypeSystemClang::DumpDeclHiearchy (clang::Decl * decl) static
Definition at line 2420 of file TypeSystemClang.cpp.
References DumpDeclContextHiearchy().
DumpFromSymbolFile()
void TypeSystemClang::DumpFromSymbolFile (Stream & s, llvm::StringRef symbol_name)
Dump clang AST types from the symbol file.
Parameters
[in] s A stream to send the dumped AST node(s) to
[in] symbol_name The name of the symbol to dump, if it is empty dump all the symbols
Definition at line 8563 of file TypeSystemClang.cpp.
References lldb_private::Stream::AsRawOstream(), GetAsTagDecl(), getASTContext(), GetAsTypedefDecl(), GetCanonicalQualType(), lldb_private::CompilerType::GetOpaqueQualType(), lldb_private::ClangUtil::GetQualType(), lldb_private::TypeList::GetSize(), lldb_private::TypeSystem::GetSymbolFile(), lldb_private::TypeList::GetTypeAtIndex(), and lldb_private::SymbolFile::GetTypes().
DumpTypeDescription() [1/2]
void TypeSystemClang::DumpTypeDescription (lldb::opaque_compiler_type_t type, lldb::DescriptionLevel level = lldb::eDescriptionLevelFull) override virtual
Dump the type to stdout.
Implements lldb_private::TypeSystem.
Definition at line 8821 of file TypeSystemClang.cpp.
References DumpTypeDescription(), GetMetadata(), and lldb_private::ClangUtil::GetQualType().
Referenced by DumpTypeDescription(), and GetObjCBitSize().
DumpTypeDescription() [2/2]
void TypeSystemClang::DumpTypeDescription (lldb::opaque_compiler_type_t type, Stream & s, lldb::DescriptionLevel level = lldb::eDescriptionLevelFull) override virtual
Print a description of the type to a stream.
The exact implementation varies, but the expectation is that eDescriptionLevelFull returns a source-like representation of the type, whereas eDescriptionLevelVerbose does a dump of the underlying AST if applicable.
Implements lldb_private::TypeSystem.
Definition at line 8833 of file TypeSystemClang.cpp.
References lldb::eDescriptionLevelVerbose, getASTContext(), GetCompleteType(), lldb_private::Stream::GetIndentLevel(), GetQualType(), GetTypeNameForDecl(), lldb_private::Stream::PutCString(), RemoveWrappingTypes(), and lldb_private::Stream::Write().
DumpTypeName()
void TypeSystemClang::DumpTypeName (const CompilerType & type) static
Definition at line 8922 of file TypeSystemClang.cpp.
References DumpTypeName(), lldb_private::ClangUtil::GetCanonicalQualType(), lldb_private::CompilerType::GetTypeSystem(), lldb_private::ClangUtil::IsClangType(), and lldb_private::ClangUtil::RemoveFastQualifiers().
Referenced by DumpTypeName().
DumpTypeValue()
bool TypeSystemClang::DumpTypeValue (lldb::opaque_compiler_type_t type, Stream & s, lldb::Format format, const DataExtractor & data, lldb::offset_t data_offset, size_t data_byte_size, uint32_t bitfield_bit_size, uint32_t bitfield_bit_offset, ExecutionContextScope * exe_scope) override virtual
Implements lldb_private::TypeSystem.
Definition at line 8704 of file TypeSystemClang.cpp.
References lldb_private::DumpDataExtractor(), DumpEnumValue(), lldb_private::CompilerType::DumpTypeValue(), lldb::eFormatBinary, lldb::eFormatBoolean, lldb::eFormatBytes, lldb::eFormatBytesWithASCII, lldb::eFormatChar, lldb::eFormatCharArray, lldb::eFormatCharPrintable, lldb::eFormatComplex, lldb::eFormatCString, lldb::eFormatDecimal, lldb::eFormatDefault, lldb::eFormatEnum, lldb::eFormatFloat, lldb::eFormatFloat128, lldb::eFormatHex, lldb::eFormatHexUppercase, lldb::eFormatOctal, lldb::eFormatOSType, lldb::eFormatPointer, lldb::eFormatUnicode16, lldb::eFormatUnicode32, lldb::eFormatUnicode8, lldb::eFormatUnsigned, lldb::eFormatVectorOfChar, lldb::eFormatVectorOfFloat32, lldb::eFormatVectorOfFloat64, lldb::eFormatVectorOfSInt16, lldb::eFormatVectorOfSInt32, lldb::eFormatVectorOfSInt64, lldb::eFormatVectorOfSInt8, lldb::eFormatVectorOfUInt128, lldb::eFormatVectorOfUInt16, lldb::eFormatVectorOfUInt32, lldb::eFormatVectorOfUInt64, lldb::eFormatVectorOfUInt8, getASTContext(), GetCompleteType(), lldb_private::CompilerType::GetFormat(), GetQualType(), GetType(), IsAggregateType(), LLDB_INVALID_ADDRESS, and UINT32_MAX.
FieldIsBitfield()
bool TypeSystemClang::FieldIsBitfield (clang::FieldDecl * field, uint32_t & bitfield_bit_size)
Definition at line 1749 of file TypeSystemClang.cpp.
References getASTContext(), and UINT32_MAX.
Referenced by GetChildCompilerTypeAtIndex().
Finalize()
void TypeSystemClang::Finalize () override virtual
Free up any resources associated with this TypeSystem.
Done before removing all the TypeSystems from the TypeSystemMap.
Reimplemented from lldb_private::TypeSystem.
Definition at line 589 of file TypeSystemClang.cpp.
References lldb_private::ThreadSafeDenseMap< _KeyType, _ValueType >::Erase(), GetASTMap(), m_ast_owned, m_ast_up, m_builtins_up, m_diagnostics_engine_up, m_identifier_table_up, m_language_options_up, m_selector_table_up, m_source_manager_up, m_target_info_up, and m_target_options_rp.
Referenced by lldb_private::ScratchTypeSystemClang::Finalize(), and ~TypeSystemClang().
ForEachEnumerator()
void TypeSystemClang::ForEachEnumerator (lldb::opaque_compiler_type_t type, std::function< bool(const CompilerType &integer_type, ConstString name, const llvm::APSInt &value)> const & callback) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 5488 of file TypeSystemClang.cpp.
References GetCanonicalQualType(), and GetType().
GetArrayElementType()
CompilerType TypeSystemClang::GetArrayElementType (lldb::opaque_compiler_type_t type, ExecutionContextScope * exe_scope) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4209 of file TypeSystemClang.cpp.
References GetQualType(), and GetType().
GetArrayType()
CompilerType TypeSystemClang::GetArrayType (lldb::opaque_compiler_type_t type, uint64_t size) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 4225 of file TypeSystemClang.cpp.
References getASTContext(), GetCanonicalQualType(), and GetType().
GetAsCXXRecordDecl()
clang::CXXRecordDecl * TypeSystemClang::GetAsCXXRecordDecl (lldb::opaque_compiler_type_t type) static
Definition at line 7370 of file TypeSystemClang.cpp.
References GetCanonicalQualType().
Referenced by AddMethodOverridesForCXXRecordType(), and TransferBaseClasses().
GetAsDeclContext()
clang::DeclContext * lldb_private::TypeSystemClang::GetAsDeclContext (clang::FunctionDecl * function_decl) static
GetAsEnumDecl()
clang::EnumDecl * TypeSystemClang::GetAsEnumDecl (const CompilerType & type) static
Definition at line 7340 of file TypeSystemClang.cpp.
References lldb_private::ClangUtil::GetCanonicalQualType().
Referenced by PDBASTParser::CreateLLDBTypeFromPDBType(), and DoIntegralPromotion().
GetAsObjCInterfaceDecl()
clang::ObjCInterfaceDecl * TypeSystemClang::GetAsObjCInterfaceDecl (const CompilerType & type) static
Definition at line 7375 of file TypeSystemClang.cpp.
References lldb_private::ClangUtil::GetCanonicalQualType().
Referenced by AddMethodToObjCObjectType(), AddObjCClassProperty(), and SetObjCSuperClass().
GetAsRecordDecl()
clang::RecordDecl * TypeSystemClang::GetAsRecordDecl (const CompilerType & type) static
Definition at line 7348 of file TypeSystemClang.cpp.
References lldb_private::ClangUtil::GetCanonicalQualType().
Referenced by CanPassInRegisters(), and SetIsPacked().
GetAsTagDecl()
clang::TagDecl * TypeSystemClang::GetAsTagDecl (const CompilerType & type) static
Definition at line 7356 of file TypeSystemClang.cpp.
References lldb_private::ClangUtil::GetAsTagDecl().
Referenced by DumpFromSymbolFile(), and DWARFASTParserClang::ParseTypeFromClangModule().
GetASTContext()
TypeSystemClang * TypeSystemClang::GetASTContext (clang::ASTContext * ast_ctx) static
Definition at line 711 of file TypeSystemClang.cpp.
References GetASTMap(), lldb_private::ThreadSafeDenseMap< _KeyType, _ValueType >::Lookup(), and TypeSystemClang().
Referenced by lldb_private::ClangASTImporter::GetDeclMetadata(), and lldb_private::ClangASTImporter::importRecordLayoutFromOrigin().
getASTContext()
ASTContext & TypeSystemClang::getASTContext () const
Returns the clang::ASTContext instance managed by this TypeSystemClang.
Definition at line 626 of file TypeSystemClang.cpp.
References m_ast_up.
Referenced by AddEnumerationValueToEnumerationType(), AddMethodToCXXRecordType(), AddPtrAuthModifier(), lldb_private::AppleObjCTypeEncodingParser::BuildObjCObjectPointerType(), lldb_private::AppleObjCTypeEncodingParser::BuildType(), lldb_private::ClangASTImporter::CopyType(), CreateArrayType(), CreateBaseClassSpecifier(), CreateBlockDeclaration(), CreateClassTemplateDecl(), CreateClassTemplateSpecializationDecl(), CreateClassTemplateSpecializationType(), CreateDeclContext(), CreateEnumerationType(), CreateFunctionDeclaration(), CreateFunctionTemplateDecl(), CreateFunctionType(), CreateGenericFunctionPrototype(), CreateObjCClass(), CreateParameterDeclaration(), CreateRecordType(), CreateStructForIdentifier(), CreateTemplateTemplateParmDecl(), CreateTypedef(), CreateUsingDeclaration(), CreateUsingDirectiveDeclaration(), CreateVariableDeclaration(), DeclContextGetTypeSystemClang(), DeclGetConstantValue(), lldb_private::ClangASTImporter::DeportType(), lldb_private::ClangExpressionDeclMap::DeportType(), Dump(), DumpFromSymbolFile(), DumpTypeDescription(), DumpTypeValue(), DWARFASTParserClang::ExtractIntFromFormValue(), FieldIsBitfield(), lldb_private::ScratchTypeSystemClang::ForgetSource(), GetArrayType(), GetAtomicType(), GetBasicType(), GetBitSize(), GetBuiltinTypeByName(), GetBuiltinTypeForDWARFEncodingAndBitSize(), GetBuiltinTypeForEncodingAndBitSize(), GetBuiltinTypeForPDBEncodingAndBitSize(), GetChildCompilerTypeAtIndex(), GetCompilerDecl(), GetCompleteDecl(), GetCompleteType(), GetCStringType(), GetDeclarationName(), GetDirectBaseClassAtIndex(), GetDirectNestedTypeWithName(), GetDisplayTypeName(), GetFieldAtIndex(), GetFloatTypeSemantics(), GetFullyUnqualifiedType(), GetIndexOfChildMemberWithName(), GetIntTypeFromBitSize(), GetLValueReferenceType(), getMangleContext(), GetMemberFunctionAtIndex(), GetMinimumLanguage(), GetNumChildren(), GetNumMemberFunctions(), GetObjCBitSize(), GetOrCreateClangModule(), GetOrCreateStructForIdentifier(), GetPointerSizedIntType(), GetPointerType(), GetRValueReferenceType(), GetStaticFieldWithName(), getTargetInfo(), GetTranslationUnitDecl(), GetType(), GetTypeBitAlign(), GetTypeForIdentifier(), GetTypeInfo(), GetTypePrintingPolicy(), GetUniqueNamespaceDeclaration(), GetVirtualBaseClassAtIndex(), lldb_private::ClangASTSource::InstallASTContext(), IsCompleteType(), IsHomogeneousAggregate(), IsIntegerType(), LogCreation(), and SetExternalSource().
GetAsTemplateSpecialization()
const clang::ClassTemplateSpecializationDecl * TypeSystemClang::GetAsTemplateSpecialization (lldb::opaque_compiler_type_t type) private
Definition at line 7089 of file TypeSystemClang.cpp.
References GetCanonicalQualType(), GetCompleteType(), and RemoveWrappingTypes().
Referenced by GetIntegralTemplateArgument(), GetTemplateArgumentKind(), and GetTypeTemplateArgument().
GetAsTypedefDecl()
clang::TypedefNameDecl * TypeSystemClang::GetAsTypedefDecl (const CompilerType & type) static
Definition at line 7361 of file TypeSystemClang.cpp.
References lldb_private::ClangUtil::GetQualType().
Referenced by PDBASTParser::CreateLLDBTypeFromPDBType(), and DumpFromSymbolFile().
GetAtomicType()
CompilerType TypeSystemClang::GetAtomicType (lldb::opaque_compiler_type_t type) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 4533 of file TypeSystemClang.cpp.
References getASTContext(), GetQualType(), and GetType().
GetBasicType()
CompilerType TypeSystemClang::GetBasicType (lldb::BasicType type)
Definition at line 900 of file TypeSystemClang.cpp.
References getASTContext(), and GetOpaqueCompilerType().
Referenced by GetBasicTypeFromAST(), GetBuiltinTypeByName(), GetBuiltinTypeForPDBEncodingAndBitSize(), GetPointerByteSize(), lldb_private::platform_freebsd::PlatformFreeBSD::GetSiginfoType(), lldb_private::platform_linux::PlatformLinux::GetSiginfoType(), and lldb_private::platform_netbsd::PlatformNetBSD::GetSiginfoType().
GetBasicTypeEnumeration() [1/2]
lldb::BasicType TypeSystemClang::GetBasicTypeEnumeration (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 5412 of file TypeSystemClang.cpp.
References lldb::eBasicTypeBool, lldb::eBasicTypeChar16, lldb::eBasicTypeChar32, lldb::eBasicTypeChar8, lldb::eBasicTypeDouble, lldb::eBasicTypeFloat, lldb::eBasicTypeFloat128, lldb::eBasicTypeHalf, lldb::eBasicTypeInt, lldb::eBasicTypeInt128, lldb::eBasicTypeInvalid, lldb::eBasicTypeLong, lldb::eBasicTypeLongDouble, lldb::eBasicTypeLongLong, lldb::eBasicTypeNullPtr, lldb::eBasicTypeObjCClass, lldb::eBasicTypeObjCID, lldb::eBasicTypeObjCSel, lldb::eBasicTypeOther, lldb::eBasicTypeShort, lldb::eBasicTypeSignedChar, lldb::eBasicTypeSignedWChar, lldb::eBasicTypeUnsignedChar, lldb::eBasicTypeUnsignedInt, lldb::eBasicTypeUnsignedInt128, lldb::eBasicTypeUnsignedLong, lldb::eBasicTypeUnsignedLongLong, lldb::eBasicTypeUnsignedShort, lldb::eBasicTypeUnsignedWChar, lldb::eBasicTypeVoid, and GetCanonicalQualType().
GetBasicTypeEnumeration() [2/2]
lldb::BasicType TypeSystemClang::GetBasicTypeEnumeration (llvm::StringRef name) static
Definition at line 814 of file TypeSystemClang.cpp.
References lldb::eBasicTypeBool, lldb::eBasicTypeChar, lldb::eBasicTypeDouble, lldb::eBasicTypeFloat, lldb::eBasicTypeInt, lldb::eBasicTypeInt128, lldb::eBasicTypeInvalid, lldb::eBasicTypeLong, lldb::eBasicTypeLongDouble, lldb::eBasicTypeLongLong, lldb::eBasicTypeNullPtr, lldb::eBasicTypeObjCID, lldb::eBasicTypeObjCSel, lldb::eBasicTypeShort, lldb::eBasicTypeSignedChar, lldb::eBasicTypeSignedWChar, lldb::eBasicTypeUnsignedChar, lldb::eBasicTypeUnsignedInt, lldb::eBasicTypeUnsignedInt128, lldb::eBasicTypeUnsignedLong, lldb::eBasicTypeUnsignedLongLong, lldb::eBasicTypeUnsignedShort, lldb::eBasicTypeUnsignedWChar, lldb::eBasicTypeVoid, and lldb::eBasicTypeWChar.
Referenced by lldb_private::SymbolFileCTF::CreateInteger(), GetBuiltinTypeByName(), and IsPromotableIntegerType().
GetBasicTypeFromAST()
CompilerType TypeSystemClang::GetBasicTypeFromAST (lldb::BasicType basic_type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4640 of file TypeSystemClang.cpp.
References GetBasicType().
Referenced by DoIntegralPromotion().
GetBitSize()
llvm::Expected< uint64_t > TypeSystemClang::GetBitSize (lldb::opaque_compiler_type_t type, ExecutionContextScope * exe_scope) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4716 of file TypeSystemClang.cpp.
References getASTContext(), GetCanonicalQualType(), GetCompleteType(), GetObjCBitSize(), and GetTypeName().
Referenced by GetByteSize().
GetBuiltinTypeByName()
CompilerType TypeSystemClang::GetBuiltinTypeByName (ConstString name) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 5392 of file TypeSystemClang.cpp.
References getASTContext(), GetBasicType(), GetBasicTypeEnumeration(), lldb_private::ConstString::GetStringRef(), and GetType().
GetBuiltinTypeForDWARFEncodingAndBitSize()
CompilerType TypeSystemClang::GetBuiltinTypeForDWARFEncodingAndBitSize (llvm::StringRef type_name, uint32_t dw_ate, uint32_t bit_size)
Definition at line 911 of file TypeSystemClang.cpp.
References getASTContext(), GetBuiltinTypeForDWARFEncodingAndBitSize(), lldb_private::GetLog(), lldb_private::ClangUtil::GetQualType(), getTargetInfo(), GetType(), LLDB_LOG, QualTypeMatchesBitSize(), and lldb_private::Types.
Referenced by GetBuiltinTypeForDWARFEncodingAndBitSize().
GetBuiltinTypeForEncodingAndBitSize()
CompilerType TypeSystemClang::GetBuiltinTypeForEncodingAndBitSize (lldb::Encoding encoding, size_t bit_size) override virtual
Implements lldb_private::TypeSystem.
Definition at line 748 of file TypeSystemClang.cpp.
References lldb::eEncodingIEEE754, lldb::eEncodingInvalid, lldb::eEncodingSint, lldb::eEncodingUint, lldb::eEncodingVector, getASTContext(), GetType(), and QualTypeMatchesBitSize().
Referenced by GetBuiltinTypeForPDBEncodingAndBitSize().
GetByteSize()
llvm::Expected< uint64_t > lldb_private::TypeSystemClang::GetByteSize (lldb::opaque_compiler_type_t type, ExecutionContextScope * exe_scope) inline
Definition at line 825 of file TypeSystemClang.h.
References GetBitSize().
GetCanonicalQualType()
clang::QualType lldb_private::TypeSystemClang::GetCanonicalQualType (lldb::opaque_compiler_type_t type) inline static
Definition at line 1154 of file TypeSystemClang.h.
Referenced by AddEnumerationValueToEnumerationType(), AddMethodToCXXRecordType(), DumpFromSymbolFile(), ForEachEnumerator(), GetArrayType(), GetAsCXXRecordDecl(), GetAsTemplateSpecialization(), GetBasicTypeEnumeration(), GetBitSize(), GetCanonicalType(), GetChildCompilerTypeAtIndex(), GetDirectBaseClassAtIndex(), GetDirectNestedTypeWithName(), GetEncoding(), GetEnumerationIntegerType(), GetFieldAtIndex(), GetFormat(), GetFunctionArgumentCount(), GetIndexOfChildMemberWithName(), GetIndexOfChildWithName(), GetMemberFunctionAtIndex(), GetMinimumLanguage(), GetNumberOfFunctionArguments(), GetNumDirectBaseClasses(), GetNumFields(), GetNumMemberFunctions(), GetNumTemplateArguments(), GetNumVirtualBaseClasses(), GetPtrAuthAddressDiversity(), GetPtrAuthDiscriminator(), GetPtrAuthKey(), GetStaticFieldWithName(), GetVirtualBaseClassAtIndex(), IsAggregateType(), IsAnonymousType(), IsArrayType(), IsBeingDefined(), IsClassType(), IsCStringType(), IsEnumerationType(), IsEnumType(), IsFloatingPointType(), IsHomogeneousAggregate(), IsIntegerType(), IsPointerOrReferenceType(), IsPointerType(), IsPolymorphicClass(), IsPossibleDynamicType(), IsReferenceType(), IsScopedEnumerationType(), IsTypeImpl(), IsVectorType(), IsVoidType(), and SetHasExternalStorage().
GetCanonicalType()
CompilerType TypeSystemClang::GetCanonicalType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4243 of file TypeSystemClang.cpp.
References GetCanonicalQualType(), and GetType().
GetChildCompilerTypeAtIndex()
llvm::Expected< CompilerType > TypeSystemClang::GetChildCompilerTypeAtIndex (lldb::opaque_compiler_type_t type, ExecutionContext * exe_ctx, size_t idx, bool transparent_pointers, bool omit_empty_base_classes, bool ignore_array_bounds, std::string & child_name, uint32_t & child_byte_size, int32_t & child_byte_offset, uint32_t & child_bitfield_bit_size, uint32_t & child_bitfield_bit_offset, bool & child_is_base_class, bool & child_is_deref_of_parent, ValueObject * valobj, uint64_t & language_flags) override virtual
Implements lldb_private::TypeSystem.
Definition at line 6131 of file TypeSystemClang.cpp.
References lldb_private::ConstString::AsCString(), FieldIsBitfield(), lldb_private::ObjCLanguageRuntime::Get(), getASTContext(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::CompilerType::GetBitSize(), lldb_private::ObjCLanguageRuntime::GetByteOffsetForIvar(), lldb_private::CompilerType::GetByteSize(), GetCanonicalQualType(), lldb_private::CompilerType::GetChildCompilerTypeAtIndex(), lldb_private::CompilerType::GetCompleteType(), GetCompleteType(), lldb_private::ConstString::GetCString(), lldb_private::ValueObject::GetName(), lldb_private::CompilerType::GetNumChildren(), GetNumChildren(), GetPointeeType(), lldb_private::ExecutionContext::GetProcessPtr(), GetQualType(), GetType(), lldb_private::CompilerType::GetTypeName(), GetVBaseBitOffset(), INT32_MAX, lldb_private::CompilerType::IsAggregateType(), lldb_private::CompilerType::IsVoidType(), LLDB_INVALID_IVAR_OFFSET, RecordHasFields(), and RemoveWrappingTypes().
Referenced by GetDereferencedType().
GetCompilerDecl()
CompilerDecl lldb_private::TypeSystemClang::GetCompilerDecl (clang::Decl * decl) inline
Creates a CompilerDecl from the given Decl with the current TypeSystemClang instance as its typesystem.
The Decl has to come from the ASTContext of this TypeSystemClang.
Definition at line 540 of file TypeSystemClang.h.
References getASTContext().
Referenced by DeclContextFindDeclByName(), SymbolFilePDB::GetDeclForUID(), and GetMemberFunctionAtIndex().
GetCompilerDeclContextForType()
CompilerDeclContext TypeSystemClang::GetCompilerDeclContextForType (const CompilerType & type) override virtual
Returns the direct parent context of specified type.
Reimplemented from lldb_private::TypeSystem.
Definition at line 2529 of file TypeSystemClang.cpp.
References CreateDeclContext(), and GetDeclContextForType().
GetCompleteDecl() [1/2]
bool TypeSystemClang::GetCompleteDecl (clang::ASTContext * ast, clang::Decl * decl) static
Definition at line 2445 of file TypeSystemClang.cpp.
GetCompleteDecl() [2/2]
bool lldb_private::TypeSystemClang::GetCompleteDecl (clang::Decl * decl) inline
Definition at line 189 of file TypeSystemClang.h.
References getASTContext(), and GetCompleteDecl().
Referenced by lldb_private::ClangASTImporter::CompleteObjCInterfaceDecl(), lldb_private::ClangASTImporter::CompleteTagDecl(), lldb_private::ClangASTImporter::CompleteTagDeclWithOrigin(), lldb_private::ClangASTSource::FindCompleteType(), lldb_private::ClangASTSource::FindObjCMethodDeclsWithOrigin(), GetCompleteDecl(), and lldb_private::ClangASTImporter::importRecordLayoutFromOrigin().
GetCompleteType()
bool TypeSystemClang::GetCompleteType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3705 of file TypeSystemClang.cpp.
References getASTContext(), GetCompleteQualType(), and GetQualType().
Referenced by DumpTypeDescription(), DumpTypeValue(), GetAsTemplateSpecialization(), GetBitSize(), GetChildCompilerTypeAtIndex(), GetDirectBaseClassAtIndex(), GetDirectNestedTypeWithName(), GetFieldAtIndex(), GetIndexOfChildMemberWithName(), GetIndexOfChildWithName(), GetMemberFunctionAtIndex(), GetNumDirectBaseClasses(), GetNumFields(), GetNumMemberFunctions(), GetNumTemplateArguments(), GetNumVirtualBaseClasses(), GetStaticFieldWithName(), GetTypeBitAlign(), GetVirtualBaseClassAtIndex(), IsHomogeneousAggregate(), IsPolymorphicClass(), and IsPossibleDynamicType().
GetCStringType()
CompilerType TypeSystemClang::GetCStringType (bool is_const)
Definition at line 1151 of file TypeSystemClang.cpp.
References getASTContext(), and GetType().
GetCXXClassName()
std::optional< std::string > TypeSystemClang::GetCXXClassName (const CompilerType & type) static
Definition at line 3642 of file TypeSystemClang.cpp.
References lldb_private::ClangUtil::GetCanonicalQualType().
GetDeclarationName()
clang::DeclarationName TypeSystemClang::GetDeclarationName (llvm::StringRef name, const CompilerType & function_clang_type)
Definition at line 2081 of file TypeSystemClang.cpp.
References CheckOverloadedOperatorKindParameterCount(), getASTContext(), lldb_private::ClangUtil::GetQualType(), and IsOperator().
Referenced by CreateFunctionDeclaration().
GetDeclContextForType() [1/2]
clang::DeclContext * TypeSystemClang::GetDeclContextForType (clang::QualType type) static
Definition at line 2569 of file TypeSystemClang.cpp.
References GetDeclContextForType(), and RemoveWrappingTypes().
Referenced by GetCompilerDeclContextForType(), GetDeclContextForType(), GetDeclContextForType(), IsRuntimeGeneratedType(), DWARFASTParserClang::ParseCXXMethod(), DWARFASTParserClang::ParseEnum(), and DWARFASTParserClang::ParseStructureLikeDIE().
GetDeclContextForType() [2/2]
clang::DeclContext * TypeSystemClang::GetDeclContextForType (const CompilerType & type) static
Definition at line 2524 of file TypeSystemClang.cpp.
References GetDeclContextForType(), and lldb_private::ClangUtil::GetQualType().
GetDereferencedType()
llvm::Expected< CompilerType > TypeSystemClang::GetDereferencedType (lldb::opaque_compiler_type_t type, ExecutionContext * exe_ctx, std::string & deref_name, uint32_t & deref_byte_size, int32_t & deref_byte_offset, ValueObject * valobj, uint64_t & language_flags) override virtual
Implements lldb_private::TypeSystem.
Definition at line 6113 of file TypeSystemClang.cpp.
References GetChildCompilerTypeAtIndex(), IsArrayType(), and IsPointerOrReferenceType().
GetDirectBaseClassAtIndex()
CompilerType TypeSystemClang::GetDirectBaseClassAtIndex (lldb::opaque_compiler_type_t type, size_t idx, uint32_t * bit_offset_ptr) override virtual
Implements lldb_private::TypeSystem.
Definition at line 5806 of file TypeSystemClang.cpp.
References getASTContext(), GetCanonicalQualType(), GetCompleteType(), lldb_private::CompilerType::GetDirectBaseClassAtIndex(), GetPointeeType(), GetType(), and RemoveWrappingTypes().
GetDirectNestedTypeWithName()
CompilerType TypeSystemClang::GetDirectNestedTypeWithName (lldb::opaque_compiler_type_t type, llvm::StringRef name) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 7004 of file TypeSystemClang.cpp.
References getASTContext(), GetCanonicalQualType(), GetCompleteType(), GetType(), and RemoveWrappingTypes().
getDisplayName()
llvm::StringRef lldb_private::TypeSystemClang::getDisplayName () const inline
Returns the display name of this TypeSystemClang that indicates what purpose it serves in LLDB.
Used for example in logs.
Definition at line 170 of file TypeSystemClang.h.
References m_display_name.
Referenced by LogCreation().
GetDisplayTypeName()
ConstString TypeSystemClang::GetDisplayTypeName (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3744 of file TypeSystemClang.cpp.
References getASTContext(), and GetQualType().
Referenced by GetNumChildren().
GetDWARFParser()
DWARFASTParser * TypeSystemClang::GetDWARFParser () override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 9024 of file TypeSystemClang.cpp.
References m_dwarf_ast_parser_up.
GetEncoding()
lldb::Encoding TypeSystemClang::GetEncoding (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4761 of file TypeSystemClang.cpp.
References lldb::eEncodingIEEE754, lldb::eEncodingInvalid, lldb::eEncodingSint, lldb::eEncodingUint, GetCanonicalQualType(), lldb_private::CompilerType::GetEncoding(), GetType(), and RemoveWrappingTypes().
GetEnumerationIntegerType() [1/2]
CompilerType TypeSystemClang::GetEnumerationIntegerType (CompilerType type)
Returns the underlying integer type for an enum type.
If the given type is invalid or not an enum-type, the function returns an invalid CompilerType.
Definition at line 8495 of file TypeSystemClang.cpp.
References lldb_private::ClangUtil::GetQualType(), and GetType().
GetEnumerationIntegerType() [2/2]
CompilerType TypeSystemClang::GetEnumerationIntegerType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4277 of file TypeSystemClang.cpp.
References GetCanonicalQualType(), GetEnumerationIntegerType(), and GetType().
Referenced by GetEnumerationIntegerType().
GetFieldAtIndex()
CompilerType TypeSystemClang::GetFieldAtIndex (lldb::opaque_compiler_type_t type, size_t idx, std::string & name, uint64_t * bit_offset_ptr, uint32_t * bitfield_bit_size_ptr, bool * is_bitfield_ptr) override virtual
Implements lldb_private::TypeSystem.
Definition at line 5628 of file TypeSystemClang.cpp.
References getASTContext(), GetCanonicalQualType(), GetCompleteType(), GetObjCFieldAtIndex(), GetType(), and RemoveWrappingTypes().
GetFloatTypeFromBitSize()
CompilerType lldb_private::TypeSystemClang::GetFloatTypeFromBitSize (clang::ASTContext * ast, size_t bit_size) static
GetFloatTypeSemantics()
const llvm::fltSemantics & TypeSystemClang::GetFloatTypeSemantics (size_t byte_size, lldb::Format format) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4661 of file TypeSystemClang.cpp.
References lldb::eFormatFloat128, and getASTContext().
GetFormat()
lldb::Format TypeSystemClang::GetFormat (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 5063 of file TypeSystemClang.cpp.
References lldb::eFormatBoolean, lldb::eFormatBytes, lldb::eFormatChar, lldb::eFormatComplex, lldb::eFormatComplexInteger, lldb::eFormatDecimal, lldb::eFormatDefault, lldb::eFormatEnum, lldb::eFormatFloat, lldb::eFormatFloat128, lldb::eFormatHex, lldb::eFormatUnicode16, lldb::eFormatUnicode32, lldb::eFormatUnicode8, lldb::eFormatUnsigned, lldb::eFormatVoid, GetCanonicalQualType(), and RemoveWrappingTypes().
GetFullyUnqualifiedType()
CompilerType TypeSystemClang::GetFullyUnqualifiedType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4269 of file TypeSystemClang.cpp.
References getASTContext(), GetFullyUnqualifiedType_Impl(), GetQualType(), and GetType().
GetFunctionArgumentAtIndex()
CompilerType TypeSystemClang::GetFunctionArgumentAtIndex (lldb::opaque_compiler_type_t type, const size_t index) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3115 of file TypeSystemClang.cpp.
References GetQualType().
GetFunctionArgumentCount()
int TypeSystemClang::GetFunctionArgumentCount (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4283 of file TypeSystemClang.cpp.
References GetCanonicalQualType().
GetFunctionArgumentTypeAtIndex()
CompilerType TypeSystemClang::GetFunctionArgumentTypeAtIndex (lldb::opaque_compiler_type_t type, size_t idx) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4294 of file TypeSystemClang.cpp.
References GetQualType(), and GetType().
GetFunctionReturnType()
CompilerType TypeSystemClang::GetFunctionReturnType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4309 of file TypeSystemClang.cpp.
References GetQualType(), and GetType().
GetIndexForRecordBase()
uint32_t TypeSystemClang::GetIndexForRecordBase (const clang::RecordDecl * record_decl, const clang::CXXBaseSpecifier * base_spec, bool omit_empty_base_classes)
Definition at line 6586 of file TypeSystemClang.cpp.
References BaseSpecifierIsEmpty(), and UINT32_MAX.
Referenced by GetIndexOfChildMemberWithName().
GetIndexForRecordChild()
uint32_t TypeSystemClang::GetIndexForRecordChild (const clang::RecordDecl * record_decl, clang::NamedDecl * canonical_decl, bool omit_empty_base_classes)
Definition at line 6614 of file TypeSystemClang.cpp.
References GetNumBaseClasses(), and UINT32_MAX.
Referenced by GetIndexOfChildMemberWithName().
GetIndexOfChildMemberWithName()
size_t TypeSystemClang::GetIndexOfChildMemberWithName (lldb::opaque_compiler_type_t type, llvm::StringRef name, bool omit_empty_base_classes, std::vector< uint32_t > & child_indexes) override virtual
Implements lldb_private::TypeSystem.
Definition at line 6664 of file TypeSystemClang.cpp.
References getASTContext(), GetCanonicalQualType(), GetCompleteType(), GetIndexForRecordBase(), GetIndexForRecordChild(), lldb_private::CompilerType::GetIndexOfChildMemberWithName(), GetNumBaseClasses(), GetPointeeType(), GetType(), lldb_private::CompilerType::IsAggregateType(), ObjCDeclHasIVars(), RemoveWrappingTypes(), and UINT32_MAX.
GetIndexOfChildWithName()
llvm::Expected< uint32_t > TypeSystemClang::GetIndexOfChildWithName (lldb::opaque_compiler_type_t type, llvm::StringRef name, bool omit_empty_base_classes) override virtual
Implements lldb_private::TypeSystem.
Definition at line 6865 of file TypeSystemClang.cpp.
References lldb_private::ConstString::AsCString(), GetCanonicalQualType(), GetCompleteType(), lldb_private::CompilerType::GetIndexOfChildWithName(), GetType(), lldb_private::CompilerType::GetTypeName(), lldb_private::CompilerType::IsAggregateType(), ObjCDeclHasIVars(), RecordHasFields(), and RemoveWrappingTypes().
GetIntegralTemplateArgument()
std::optional< CompilerType::IntegralTemplateArgument > TypeSystemClang::GetIntegralTemplateArgument (lldb::opaque_compiler_type_t type, size_t idx, bool expand_pack) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 7207 of file TypeSystemClang.cpp.
References GetAsTemplateSpecialization(), GetNthTemplateArgument(), and GetType().
GetIntTypeFromBitSize()
CompilerType TypeSystemClang::GetIntTypeFromBitSize (size_t bit_size, bool is_signed)
Definition at line 2351 of file TypeSystemClang.cpp.
References getASTContext(), and GetType().
Referenced by GetPointerSizedIntType().
GetLangOpts()
clang::LangOptions * lldb_private::TypeSystemClang::GetLangOpts () const inline
Definition at line 1164 of file TypeSystemClang.h.
References m_language_options_up.
GetLValueReferenceType()
CompilerType TypeSystemClang::GetLValueReferenceType (lldb::opaque_compiler_type_t type) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 4518 of file TypeSystemClang.cpp.
References getASTContext(), GetQualType(), and GetType().
getMangleContext()
clang::MangleContext * TypeSystemClang::getMangleContext ()
Definition at line 716 of file TypeSystemClang.cpp.
References getASTContext(), and m_mangle_ctx_up.
Referenced by DeclGetMangledName().
GetMemberFunctionAtIndex()
TypeMemberFunctionImpl TypeSystemClang::GetMemberFunctionAtIndex (lldb::opaque_compiler_type_t type, size_t idx) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4374 of file TypeSystemClang.cpp.
References lldb::eMemberFunctionKindConstructor, lldb::eMemberFunctionKindDestructor, lldb::eMemberFunctionKindInstanceMethod, lldb::eMemberFunctionKindStaticMethod, lldb::eMemberFunctionKindUnknown, getASTContext(), GetCanonicalQualType(), GetCompilerDecl(), GetCompleteQualType(), GetCompleteType(), GetType(), and RemoveWrappingTypes().
GetMetadata() [1/2]
std::optional< ClangASTMetadata > TypeSystemClang::GetMetadata (const clang::Decl * object)
Definition at line 2506 of file TypeSystemClang.cpp.
References m_decl_metadata.
Referenced by DeclContextGetLanguage(), DeclContextGetMetaData(), DeclContextIsClassMethod(), DumpTypeDescription(), lldb_private::ClangASTImporter::GetDeclMetadata(), GetDynamicArrayInfo(), IsForcefullyCompleted(), IsPossibleDynamicType(), IsRuntimeGeneratedType(), RecordHasFields(), and SetDeclIsForcefullyCompleted().
GetMetadata() [2/2]
std::optional< ClangASTMetadata > TypeSystemClang::GetMetadata (const clang::Type * object)
Definition at line 2515 of file TypeSystemClang.cpp.
References m_type_metadata.
GetMinimumLanguage()
lldb::LanguageType TypeSystemClang::GetMinimumLanguage (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3973 of file TypeSystemClang.cpp.
References lldb::eLanguageTypeC, lldb::eLanguageTypeC_plus_plus, lldb::eLanguageTypeObjC, getASTContext(), GetCanonicalQualType(), lldb_private::CompilerType::GetMinimumLanguage(), and GetType().
GetNativePDBParser()
npdb::PdbAstBuilder * TypeSystemClang::GetNativePDBParser () override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 9036 of file TypeSystemClang.cpp.
References m_native_pdb_ast_parser_up.
GetNonReferenceType()
CompilerType TypeSystemClang::GetNonReferenceType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4485 of file TypeSystemClang.cpp.
References GetQualType(), and GetType().
GetNumBaseClasses()
uint32_t TypeSystemClang::GetNumBaseClasses (const clang::CXXRecordDecl * cxx_record_decl, bool omit_empty_base_classes)
Definition at line 1831 of file TypeSystemClang.cpp.
References BaseSpecifierIsEmpty().
Referenced by GetIndexForRecordChild(), GetIndexOfChildMemberWithName(), and GetNumChildren().
GetNumberOfFunctionArguments()
size_t TypeSystemClang::GetNumberOfFunctionArguments (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3102 of file TypeSystemClang.cpp.
References GetCanonicalQualType().
GetNumChildren()
llvm::Expected< uint32_t > TypeSystemClang::GetNumChildren (lldb::opaque_compiler_type_t type, bool omit_empty_base_classes, const ExecutionContext * exe_ctx) override virtual
Implements lldb_private::TypeSystem.
Definition at line 5256 of file TypeSystemClang.cpp.
References getASTContext(), GetCompleteQualType(), GetDisplayTypeName(), GetDynamicArrayInfo(), GetNumBaseClasses(), lldb_private::CompilerType::GetNumChildren(), GetNumPointeeChildren(), GetPointeeType(), GetQualType(), lldb_private::TypeSystem::GetSymbolFile(), GetType(), lldb_private::CompilerType::IsAggregateType(), ObjCDeclHasIVars(), and RemoveWrappingTypes().
Referenced by GetChildCompilerTypeAtIndex().
GetNumDirectBaseClasses()
uint32_t TypeSystemClang::GetNumDirectBaseClasses (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 5734 of file TypeSystemClang.cpp.
References GetCanonicalQualType(), GetCompleteType(), lldb_private::CompilerType::GetNumDirectBaseClasses(), GetPointeeType(), and RemoveWrappingTypes().
GetNumFields()
uint32_t TypeSystemClang::GetNumFields (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 5515 of file TypeSystemClang.cpp.
References GetCanonicalQualType(), GetCompleteType(), and RemoveWrappingTypes().
GetNumMemberFunctions()
size_t TypeSystemClang::GetNumMemberFunctions (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4321 of file TypeSystemClang.cpp.
References getASTContext(), GetCanonicalQualType(), GetCompleteQualType(), GetCompleteType(), and RemoveWrappingTypes().
GetNumPointeeChildren()
uint32_t TypeSystemClang::GetNumPointeeChildren (clang::QualType type) static
Definition at line 5980 of file TypeSystemClang.cpp.
References RemoveWrappingTypes().
Referenced by GetNumChildren().
GetNumTemplateArguments()
size_t TypeSystemClang::GetNumTemplateArguments (lldb::opaque_compiler_type_t type, bool expand_pack) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 7050 of file TypeSystemClang.cpp.
References GetCanonicalQualType(), GetCompleteType(), and RemoveWrappingTypes().
GetNumVirtualBaseClasses()
uint32_t TypeSystemClang::GetNumVirtualBaseClasses (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 5786 of file TypeSystemClang.cpp.
References GetCanonicalQualType(), GetCompleteType(), and RemoveWrappingTypes().
GetObjCBitSize()
llvm::Expected< uint64_t > TypeSystemClang::GetObjCBitSize (clang::QualType qual_type, ExecutionContextScope * exe_scope) private
Definition at line 4683 of file TypeSystemClang.cpp.
References DumpTypeDescription(), lldb_private::ObjCLanguageRuntime::Get(), getASTContext(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::StreamString::GetString(), and GetType().
Referenced by GetBitSize().
GetOpaqueCompilerType()
lldb::opaque_compiler_type_t TypeSystemClang::GetOpaqueCompilerType (clang::ASTContext * ast, lldb::BasicType basic_type) static
Definition at line 2004 of file TypeSystemClang.cpp.
References lldb::eBasicTypeBool, lldb::eBasicTypeChar, lldb::eBasicTypeChar16, lldb::eBasicTypeChar32, lldb::eBasicTypeChar8, lldb::eBasicTypeDouble, lldb::eBasicTypeDoubleComplex, lldb::eBasicTypeFloat, lldb::eBasicTypeFloat128, lldb::eBasicTypeFloatComplex, lldb::eBasicTypeHalf, lldb::eBasicTypeInt, lldb::eBasicTypeInt128, lldb::eBasicTypeLong, lldb::eBasicTypeLongDouble, lldb::eBasicTypeLongDoubleComplex, lldb::eBasicTypeLongLong, lldb::eBasicTypeNullPtr, lldb::eBasicTypeObjCClass, lldb::eBasicTypeObjCID, lldb::eBasicTypeObjCSel, lldb::eBasicTypeShort, lldb::eBasicTypeSignedChar, lldb::eBasicTypeSignedWChar, lldb::eBasicTypeUnsignedChar, lldb::eBasicTypeUnsignedInt, lldb::eBasicTypeUnsignedInt128, lldb::eBasicTypeUnsignedLong, lldb::eBasicTypeUnsignedLongLong, lldb::eBasicTypeUnsignedShort, lldb::eBasicTypeUnsignedWChar, lldb::eBasicTypeVoid, and lldb::eBasicTypeWChar.
Referenced by GetBasicType().
GetOrCreateClangModule()
OptionalClangModuleID TypeSystemClang::GetOrCreateClangModule (llvm::StringRef name, OptionalClangModuleID parent, bool is_framework = false, bool is_explicit = false)
Synthesize a clang::Module and return its ID or a default-constructed ID.
Definition at line 1233 of file TypeSystemClang.cpp.
References getASTContext(), lldb_private::OptionalClangModuleID::GetValue(), m_diagnostics_engine_up, m_header_search_opts_up, m_header_search_up, m_language_options_up, m_module_map_up, m_source_manager_up, and m_target_info_up.
Referenced by RemapModule().
GetOrCreateStructForIdentifier()
CompilerType TypeSystemClang::GetOrCreateStructForIdentifier (llvm::StringRef type_name, const std::initializer_list< std::pair< const char *, CompilerType > > & type_fields, bool packed = false)
Definition at line 2301 of file TypeSystemClang.cpp.
References CreateStructForIdentifier(), getASTContext(), and GetTypeForIdentifier().
GetPDBParser()
PDBASTParser * TypeSystemClang::GetPDBParser () override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 9030 of file TypeSystemClang.cpp.
References m_pdb_ast_parser_up.
Referenced by SymbolFilePDB::CompleteType(), SymbolFilePDB::GetDeclContextContainingUID(), SymbolFilePDB::GetDeclContextForUID(), SymbolFilePDB::GetDeclForUID(), SymbolFilePDB::ParseCompileUnitFunctionForPDBFunc(), SymbolFilePDB::ParseDeclsForContext(), and SymbolFilePDB::ResolveTypeUID().
GetPluginName()
llvm::StringRef lldb_private::TypeSystemClang::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 152 of file TypeSystemClang.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::TypeSystemClang::GetPluginNameStatic () inline static
Definition at line 154 of file TypeSystemClang.h.
Referenced by GetPluginName(), and Initialize().
GetPointeeType()
CompilerType TypeSystemClang::GetPointeeType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4492 of file TypeSystemClang.cpp.
References GetQualType(), and GetType().
Referenced by GetChildCompilerTypeAtIndex(), GetDirectBaseClassAtIndex(), GetIndexOfChildMemberWithName(), GetNumChildren(), and GetNumDirectBaseClasses().
GetPointerByteSize()
uint32_t TypeSystemClang::GetPointerByteSize () override virtual
Implements lldb_private::TypeSystem.
Definition at line 887 of file TypeSystemClang.cpp.
References lldb::eBasicTypeVoid, GetBasicType(), lldb_private::CompilerType::GetByteSize(), lldb_private::GetLog(), lldb_private::CompilerType::GetPointerType(), LLDB_LOG_ERROR, m_pointer_byte_size, and lldb_private::Types.
GetPointerSizedIntType()
CompilerType TypeSystemClang::GetPointerSizedIntType (bool is_signed)
Definition at line 2398 of file TypeSystemClang.cpp.
References getASTContext(), and GetIntTypeFromBitSize().
GetPointerType()
CompilerType TypeSystemClang::GetPointerType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4501 of file TypeSystemClang.cpp.
References getASTContext(), GetQualType(), and GetType().
GetPtrAuthAddressDiversity()
bool TypeSystemClang::GetPtrAuthAddressDiversity (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3000 of file TypeSystemClang.cpp.
References GetCanonicalQualType().
GetPtrAuthDiscriminator()
unsigned TypeSystemClang::GetPtrAuthDiscriminator (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 2991 of file TypeSystemClang.cpp.
References GetCanonicalQualType().
GetPtrAuthKey()
unsigned TypeSystemClang::GetPtrAuthKey (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 2981 of file TypeSystemClang.cpp.
References GetCanonicalQualType().
GetQualType()
clang::QualType lldb_private::TypeSystemClang::GetQualType (lldb::opaque_compiler_type_t type) inline static
Definition at line 1147 of file TypeSystemClang.h.
Referenced by AddConstModifier(), AddPtrAuthModifier(), AddRestrictModifier(), AddVolatileModifier(), CreateBaseClassSpecifier(), CreateTypedef(), dump(), DumpTypeDescription(), DumpTypeValue(), GetArrayElementType(), GetAtomicType(), GetChildCompilerTypeAtIndex(), GetCompleteType(), GetDisplayTypeName(), GetFullyUnqualifiedType(), GetFunctionArgumentAtIndex(), GetFunctionArgumentTypeAtIndex(), GetFunctionReturnType(), GetLValueReferenceType(), GetNonReferenceType(), GetNumChildren(), GetPointeeType(), GetPointerType(), GetRValueReferenceType(), GetTypeBitAlign(), GetTypeClass(), GetTypedefedType(), GetTypeInfo(), GetTypeName(), GetTypeQualifiers(), IsCharType(), IsCompleteType(), IsConst(), IsDefined(), IsForcefullyCompleted(), IsRuntimeGeneratedType(), IsTypedefType(), and Verify().
GetRValueReferenceType()
CompilerType TypeSystemClang::GetRValueReferenceType (lldb::opaque_compiler_type_t type) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 4526 of file TypeSystemClang.cpp.
References getASTContext(), GetQualType(), and GetType().
getSema()
clang::Sema * lldb_private::TypeSystemClang::getSema () inline
Definition at line 182 of file TypeSystemClang.h.
References m_sema.
GetSourceMgr()
clang::SourceManager * lldb_private::TypeSystemClang::GetSourceMgr () const inline
Definition at line 1167 of file TypeSystemClang.h.
References m_source_manager_up.
GetStaticFieldWithName()
CompilerDecl TypeSystemClang::GetStaticFieldWithName (lldb::opaque_compiler_type_t type, llvm::StringRef name) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 5945 of file TypeSystemClang.cpp.
References getASTContext(), GetCanonicalQualType(), GetCompleteType(), and RemoveWrappingTypes().
GetSupportedLanguagesForExpressions()
LanguageSet TypeSystemClang::GetSupportedLanguagesForExpressions () static
Definition at line 567 of file TypeSystemClang.cpp.
References lldb::eLanguageTypeC_plus_plus, lldb::eLanguageTypeC_plus_plus_03, lldb::eLanguageTypeC_plus_plus_11, lldb::eLanguageTypeC_plus_plus_14, lldb::eLanguageTypeC_plus_plus_17, lldb::eLanguageTypeC_plus_plus_20, lldb::eLanguageTypeObjC_plus_plus, and lldb_private::LanguageSet::Insert().
Referenced by Initialize().
GetSupportedLanguagesForTypes()
LanguageSet TypeSystemClang::GetSupportedLanguagesForTypes () static
Definition at line 549 of file TypeSystemClang.cpp.
References lldb::eLanguageTypeC, lldb::eLanguageTypeC11, lldb::eLanguageTypeC89, lldb::eLanguageTypeC99, lldb::eLanguageTypeC_plus_plus, lldb::eLanguageTypeC_plus_plus_03, lldb::eLanguageTypeC_plus_plus_11, lldb::eLanguageTypeC_plus_plus_14, lldb::eLanguageTypeC_plus_plus_17, lldb::eLanguageTypeC_plus_plus_20, lldb::eLanguageTypeObjC, lldb::eLanguageTypeObjC_plus_plus, and lldb_private::LanguageSet::Insert().
Referenced by Initialize().
getTargetInfo()
TargetInfo * TypeSystemClang::getTargetInfo ()
Definition at line 731 of file TypeSystemClang.cpp.
References getASTContext(), getTargetOptions(), m_target_info_up, and m_target_triple.
Referenced by CreateASTContext(), and GetBuiltinTypeForDWARFEncodingAndBitSize().
getTargetOptions()
std::shared_ptr< clang::TargetOptions > & TypeSystemClang::getTargetOptions ()
Definition at line 722 of file TypeSystemClang.cpp.
References m_target_options_rp, and m_target_triple.
Referenced by getTargetInfo().
GetTargetTriple()
const char * TypeSystemClang::GetTargetTriple ()
Definition at line 611 of file TypeSystemClang.cpp.
References m_target_triple.
Referenced by CreateASTContext().
GetTemplateArgumentKind()
lldb::TemplateArgumentKind TypeSystemClang::GetTemplateArgumentKind (lldb::opaque_compiler_type_t type, size_t idx, bool expand_pack) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 7146 of file TypeSystemClang.cpp.
References lldb::eTemplateArgumentKindDeclaration, lldb::eTemplateArgumentKindExpression, lldb::eTemplateArgumentKindIntegral, lldb::eTemplateArgumentKindNull, lldb::eTemplateArgumentKindNullPtr, lldb::eTemplateArgumentKindPack, lldb::eTemplateArgumentKindStructuralValue, lldb::eTemplateArgumentKindTemplate, lldb::eTemplateArgumentKindTemplateExpansion, lldb::eTemplateArgumentKindType, GetAsTemplateSpecialization(), and GetNthTemplateArgument().
GetTranslationUnitDecl()
clang::TranslationUnitDecl * lldb_private::TypeSystemClang::GetTranslationUnitDecl () inline
Definition at line 231 of file TypeSystemClang.h.
References getASTContext().
GetType()
CompilerType lldb_private::TypeSystemClang::GetType (clang::QualType qt) inline
Creates a CompilerType from the given QualType with the current TypeSystemClang instance as the CompilerType's typesystem.
Parameters
qt The QualType for a type that belongs to the ASTContext of this TypeSystemClang.
Returns
The CompilerType representing the given QualType. If the QualType's type pointer is a nullptr then the function returns an invalid CompilerType.
Definition at line 245 of file TypeSystemClang.h.
References getASTContext().
Referenced by AddConstModifier(), AddPtrAuthModifier(), AddRestrictModifier(), AddVolatileModifier(), lldb_private::AppleObjCTypeEncodingParser::BuildAggregate(), CreateArrayType(), CreateBlockPointerType(), CreateClassTemplateSpecializationType(), CreateEnumerationType(), CreateFunctionType(), CreateGenericFunctionPrototype(), CreateObjCClass(), CreateParameterDeclarations(), CreateRecordType(), CreateTypedef(), DeclGetFunctionArgumentType(), DeclGetFunctionReturnType(), DoIntegralPromotion(), DumpTypeValue(), ForEachEnumerator(), GetArrayElementType(), GetArrayType(), GetAtomicType(), GetBuiltinTypeByName(), GetBuiltinTypeForDWARFEncodingAndBitSize(), GetBuiltinTypeForEncodingAndBitSize(), GetCanonicalType(), GetChildCompilerTypeAtIndex(), GetCStringType(), GetDirectBaseClassAtIndex(), GetDirectNestedTypeWithName(), GetEncoding(), GetEnumerationIntegerType(), GetEnumerationIntegerType(), GetFieldAtIndex(), GetFullyUnqualifiedType(), GetFunctionArgumentTypeAtIndex(), GetFunctionReturnType(), GetIndexOfChildMemberWithName(), GetIndexOfChildWithName(), GetIntegralTemplateArgument(), GetIntTypeFromBitSize(), GetLValueReferenceType(), GetMemberFunctionAtIndex(), GetMinimumLanguage(), GetNonReferenceType(), GetNumChildren(), GetObjCBitSize(), GetPointeeType(), GetPointerType(), GetRValueReferenceType(), GetTypedefedType(), GetTypeForDecl(), GetTypeInfo(), GetTypeTemplateArgument(), GetVirtualBaseClassAtIndex(), IsPossibleDynamicType(), IsVectorType(), and lldb_private::AppleObjCTypeEncodingParser::RealizeType().
GetTypeBitAlign()
std::optional< size_t > TypeSystemClang::GetTypeBitAlign (lldb::opaque_compiler_type_t type, ExecutionContextScope * exe_scope) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4754 of file TypeSystemClang.cpp.
References getASTContext(), GetCompleteType(), and GetQualType().
GetTypeClass()
lldb::TypeClass TypeSystemClang::GetTypeClass (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4057 of file TypeSystemClang.cpp.
References GetQualType(), and RemoveWrappingTypes().
GetTypedefedType()
CompilerType TypeSystemClang::GetTypedefedType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4628 of file TypeSystemClang.cpp.
References GetQualType(), GetType(), and RemoveWrappingTypes().
GetTypeForDecl() [1/5]
CompilerType TypeSystemClang::GetTypeForDecl (clang::NamedDecl * decl)
Definition at line 1197 of file TypeSystemClang.cpp.
References GetTypeForDecl().
Referenced by CompleteObjCInterfaceDecl(), CompleteTagDecl(), CountDeclLevels(), GetTypeForDecl(), GetTypeForDecl(), and PrepareContextToReceiveMembers().
GetTypeForDecl() [2/5]
CompilerType lldb_private::TypeSystemClang::GetTypeForDecl (clang::ObjCInterfaceDecl * objc_decl)
GetTypeForDecl() [3/5]
CompilerType lldb_private::TypeSystemClang::GetTypeForDecl (clang::TagDecl * decl)
GetTypeForDecl() [4/5]
CompilerType TypeSystemClang::GetTypeForDecl (clang::ValueDecl * value_decl)
Definition at line 1216 of file TypeSystemClang.cpp.
References GetType().
GetTypeForDecl() [5/5]
CompilerType TypeSystemClang::GetTypeForDecl (void * opaque_decl) override virtual
Implements lldb_private::TypeSystem.
Definition at line 1181 of file TypeSystemClang.cpp.
References GetTypeForDecl().
GetTypeForFormatters()
CompilerType TypeSystemClang::GetTypeForFormatters (void * type) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 7238 of file TypeSystemClang.cpp.
References lldb_private::ClangUtil::RemoveFastQualifiers().
GetTypeForIdentifier()
template<typename RecordDeclType> CompilerType lldb_private::TypeSystemClang::GetTypeForIdentifier (const clang::ASTContext & Ctx, llvm::StringRef type_name, clang::DeclContext * decl_context = nullptr) inline
Definition at line 264 of file TypeSystemClang.h.
References getASTContext().
Referenced by CreateStructForIdentifier(), and GetOrCreateStructForIdentifier().
GetTypeInfo()
uint32_t TypeSystemClang::GetTypeInfo (lldb::opaque_compiler_type_t type, CompilerType * pointee_or_element_compiler_type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3759 of file TypeSystemClang.cpp.
References lldb_private::CompilerType::Clear(), getASTContext(), GetQualType(), GetType(), lldb_private::CompilerType::GetTypeInfo(), GetTypeInfo(), RemoveWrappingTypes(), and lldb_private::CompilerType::SetCompilerType().
Referenced by GetTypeInfo(), IsCStringType(), and IsScalarType().
GetTypeName()
ConstString TypeSystemClang::GetTypeName (lldb::opaque_compiler_type_t type, bool base_only) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3711 of file TypeSystemClang.cpp.
References GetQualType(), GetTypeNameForDecl(), GetTypePrintingPolicy(), and RemoveWrappingTypes().
Referenced by GetBitSize().
GetTypeNameForDecl()
std::string TypeSystemClang::GetTypeNameForDecl (const clang::NamedDecl * named_decl, bool qualified = true) private
Returns the internal type name for the given NamedDecl using the type printing policy.
Definition at line 2130 of file TypeSystemClang.cpp.
References GetTypePrintingPolicy().
Referenced by DeclContextGetScopeQualifiedName(), DeclGetName(), DumpTypeDescription(), and GetTypeName().
GetTypePrintingPolicy()
PrintingPolicy TypeSystemClang::GetTypePrintingPolicy () private
Returns the PrintingPolicy used when generating the internal type names.
These type names are mostly used for the formatter selection.
Definition at line 2107 of file TypeSystemClang.cpp.
References getASTContext().
Referenced by DeclContextGetName(), GetTypeName(), and GetTypeNameForDecl().
GetTypeQualifiers()
unsigned TypeSystemClang::GetTypeQualifiers (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 4200 of file TypeSystemClang.cpp.
References GetQualType().
GetTypeTemplateArgument()
CompilerType TypeSystemClang::GetTypeTemplateArgument (lldb::opaque_compiler_type_t type, size_t idx, bool expand_pack) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 7192 of file TypeSystemClang.cpp.
References GetAsTemplateSpecialization(), GetNthTemplateArgument(), and GetType().
GetUniqueNamespaceDeclaration()
NamespaceDecl * TypeSystemClang::GetUniqueNamespaceDeclaration (const char * name, clang::DeclContext * decl_ctx, OptionalClangModuleID owning_module, bool is_inline = false)
Definition at line 1853 of file TypeSystemClang.cpp.
References getASTContext(), and SetOwningModule().
GetVirtualBaseClassAtIndex()
CompilerType TypeSystemClang::GetVirtualBaseClassAtIndex (lldb::opaque_compiler_type_t type, size_t idx, uint32_t * bit_offset_ptr) override virtual
Implements lldb_private::TypeSystem.
Definition at line 5901 of file TypeSystemClang.cpp.
References getASTContext(), GetCanonicalQualType(), GetCompleteType(), GetType(), and RemoveWrappingTypes().
Initialize()
void TypeSystemClang::Initialize () static
Definition at line 579 of file TypeSystemClang.cpp.
References CreateInstance(), GetPluginNameStatic(), GetSupportedLanguagesForExpressions(), GetSupportedLanguagesForTypes(), and lldb_private::PluginManager::RegisterPlugin().
isA()
bool lldb_private::TypeSystemClang::isA (const void * ClassID) const inline override virtual
Implements lldb_private::TypeSystem.
Definition at line 127 of file TypeSystemClang.h.
References ID.
Referenced by lldb_private::ScratchTypeSystemClang::isA().
IsAggregateType()
bool TypeSystemClang::IsAggregateType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 2771 of file TypeSystemClang.cpp.
References GetCanonicalQualType(), and RemoveWrappingTypes().
Referenced by DumpTypeValue().
IsAnonymousType()
bool TypeSystemClang::IsAnonymousType (lldb::opaque_compiler_type_t type) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 2792 of file TypeSystemClang.cpp.
References GetCanonicalQualType(), and RemoveWrappingTypes().
IsArrayType()
bool TypeSystemClang::IsArrayType (lldb::opaque_compiler_type_t type, CompilerType * element_type, uint64_t * size, bool * is_incomplete) override virtual
Implements lldb_private::TypeSystem.
Definition at line 2814 of file TypeSystemClang.cpp.
References lldb_private::CompilerType::Clear(), GetCanonicalQualType(), RemoveWrappingTypes(), and lldb_private::CompilerType::SetCompilerType().
Referenced by GetDereferencedType().
IsBeingDefined()
bool TypeSystemClang::IsBeingDefined (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3665 of file TypeSystemClang.cpp.
References GetCanonicalQualType().
IsBlockPointerType()
bool TypeSystemClang::IsBlockPointerType (lldb::opaque_compiler_type_t type, CompilerType * function_pointer_type_ptr) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3172 of file TypeSystemClang.cpp.
References IsTypeImpl(), and m_ast_up.
IsCharType()
bool TypeSystemClang::IsCharType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 2939 of file TypeSystemClang.cpp.
References GetQualType().
IsClassType()
bool TypeSystemClang::IsClassType (lldb::opaque_compiler_type_t type) static
Definition at line 3454 of file TypeSystemClang.cpp.
References GetCanonicalQualType().
IsCompleteType()
bool TypeSystemClang::IsCompleteType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 2943 of file TypeSystemClang.cpp.
References getASTContext(), GetCompleteQualType(), and GetQualType().
IsConst()
bool TypeSystemClang::IsConst (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 2952 of file TypeSystemClang.cpp.
References GetQualType().
IsCStringType()
bool TypeSystemClang::IsCStringType (lldb::opaque_compiler_type_t type, uint32_t & length)
Definition at line 2956 of file TypeSystemClang.cpp.
References lldb_private::Flags::AnySet(), GetCanonicalQualType(), GetTypeInfo(), lldb_private::CompilerType::IsCharType(), lldb_private::CompilerType::IsValid(), and lldb_private::Flags::Test().
IsCXXClassType()
bool TypeSystemClang::IsCXXClassType (const CompilerType & type) static
Definition at line 3657 of file TypeSystemClang.cpp.
References lldb_private::ClangUtil::GetCanonicalQualType().
Referenced by PDBASTParser::CreateLLDBTypeFromPDBType(), lldb_private::ItaniumABILanguageRuntime::GetTypeInfo(), DWARFASTParserClang::ParseCXXMethod(), and RequireCompleteType().
IsDefined()
bool TypeSystemClang::IsDefined (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3410 of file TypeSystemClang.cpp.
References GetQualType().
IsEnumerationType()
bool TypeSystemClang::IsEnumerationType (lldb::opaque_compiler_type_t type, bool & is_signed) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 3214 of file TypeSystemClang.cpp.
References GetCanonicalQualType().
Referenced by IsPromotableIntegerType().
IsEnumType()
bool TypeSystemClang::IsEnumType (lldb::opaque_compiler_type_t type) static
Definition at line 3462 of file TypeSystemClang.cpp.
References GetCanonicalQualType().
IsFloatingPointType()
bool TypeSystemClang::IsFloatingPointType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3399 of file TypeSystemClang.cpp.
References GetCanonicalQualType().
IsForcefullyCompleted()
bool TypeSystemClang::IsForcefullyCompleted (lldb::opaque_compiler_type_t type) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 9800 of file TypeSystemClang.cpp.
References GetMetadata(), and GetQualType().
IsFunctionPointerType()
bool TypeSystemClang::IsFunctionPointerType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3164 of file TypeSystemClang.cpp.
References IsTypeImpl().
IsFunctionType()
bool TypeSystemClang::IsFunctionType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3010 of file TypeSystemClang.cpp.
References IsTypeImpl().
IsHomogeneousAggregate()
uint32_t TypeSystemClang::IsHomogeneousAggregate (lldb::opaque_compiler_type_t type, CompilerType * base_type_ptr) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3020 of file TypeSystemClang.cpp.
References getASTContext(), GetCanonicalQualType(), GetCompleteType(), and RemoveWrappingTypes().
IsIntegerType()
bool TypeSystemClang::IsIntegerType (lldb::opaque_compiler_type_t type, bool & is_signed) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3194 of file TypeSystemClang.cpp.
References getASTContext(), and GetCanonicalQualType().
IsMemberFunctionPointerType()
bool TypeSystemClang::IsMemberFunctionPointerType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3155 of file TypeSystemClang.cpp.
References IsTypeImpl().
IsObjCClassType()
bool TypeSystemClang::IsObjCClassType (const CompilerType & type) static
Definition at line 3435 of file TypeSystemClang.cpp.
References lldb_private::ClangUtil::GetCanonicalQualType(), and lldb_private::ClangUtil::IsClangType().
Referenced by lldb_private::ClangExpressionDeclMap::LookUpLldbObjCClass(), and lldb_private::ClangUserExpression::ScanContext().
IsObjCObjectOrInterfaceType()
bool TypeSystemClang::IsObjCObjectOrInterfaceType (const CompilerType & type) static
Definition at line 3448 of file TypeSystemClang.cpp.
References lldb_private::ClangUtil::GetCanonicalQualType(), and lldb_private::ClangUtil::IsClangType().
Referenced by DWARFASTParserClang::CompleteRecordType(), lldb_private::ObjCLanguageRuntime::GetRuntimeType(), lldb_private::ObjCLanguageRuntime::LookupInCompleteClassCache(), DWARFASTParserClang::ParseInheritance(), DWARFASTParserClang::ParseObjCMethod(), DWARFASTParserClang::ParseSingleMember(), and RequireCompleteType().
IsObjCObjectPointerType()
bool TypeSystemClang::IsObjCObjectPointerType (const CompilerType & type, CompilerType * target_type = nullptr) static
Definition at line 3675 of file TypeSystemClang.cpp.
References lldb_private::CompilerType::Clear(), lldb_private::ClangUtil::GetCanonicalQualType(), lldb_private::CompilerType::GetTypeSystem(), lldb_private::ClangUtil::IsClangType(), and lldb_private::CompilerType::SetCompilerType().
Referenced by lldb_private::AppleObjCRuntime::GetObjectDescription(), lldb_private::ObjCLanguageRuntime::GetRuntimeType(), lldb_private::ClangExpressionDeclMap::LookUpLldbObjCClass(), and lldb_private::ClangUserExpression::ScanContext().
IsOperator()
bool TypeSystemClang::IsOperator (llvm::StringRef name, clang::OverloadedOperatorKind & op_kind) static
Definition at line 368 of file TypeSystemClang.cpp.
Referenced by lldb_private::NameSearchContext::AddFunDecl(), AddMethodToCXXRecordType(), and GetDeclarationName().
IsPointerOrReferenceType()
bool TypeSystemClang::IsPointerOrReferenceType (lldb::opaque_compiler_type_t type, CompilerType * pointee_type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3296 of file TypeSystemClang.cpp.
References lldb_private::CompilerType::Clear(), GetCanonicalQualType(), RemoveWrappingTypes(), and lldb_private::CompilerType::SetCompilerType().
Referenced by GetDereferencedType().
IsPointerType()
bool TypeSystemClang::IsPointerType (lldb::opaque_compiler_type_t type, CompilerType * pointee_type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3243 of file TypeSystemClang.cpp.
References lldb_private::CompilerType::Clear(), GetCanonicalQualType(), RemoveWrappingTypes(), and lldb_private::CompilerType::SetCompilerType().
IsPolymorphicClass()
bool TypeSystemClang::IsPolymorphicClass (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3470 of file TypeSystemClang.cpp.
References GetCanonicalQualType(), and GetCompleteType().
IsPossibleDynamicType()
bool TypeSystemClang::IsPossibleDynamicType (lldb::opaque_compiler_type_t type, CompilerType * target_type, bool check_cplusplus, bool check_objc) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3496 of file TypeSystemClang.cpp.
References lldb_private::CompilerType::Clear(), GetCanonicalQualType(), GetCompleteType(), GetMetadata(), GetType(), RemoveWrappingTypes(), and lldb_private::CompilerType::SetCompilerType().
IsPromotableIntegerType()
bool TypeSystemClang::IsPromotableIntegerType (lldb::opaque_compiler_type_t type) override virtual
Checks if the type is eligible for integral promotion.
Reimplemented from lldb_private::TypeSystem.
Definition at line 7244 of file TypeSystemClang.cpp.
References lldb::eBasicTypeBool, lldb::eBasicTypeChar, lldb::eBasicTypeChar16, lldb::eBasicTypeChar32, lldb::eBasicTypeShort, lldb::eBasicTypeSignedChar, lldb::eBasicTypeSignedWChar, lldb::eBasicTypeUnsignedChar, lldb::eBasicTypeUnsignedShort, lldb::eBasicTypeUnsignedWChar, lldb::eBasicTypeWChar, GetBasicTypeEnumeration(), IsEnumerationType(), and IsScopedEnumerationType().
IsReferenceType()
bool TypeSystemClang::IsReferenceType (lldb::opaque_compiler_type_t type, CompilerType * pointee_type, bool * is_rvalue) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3363 of file TypeSystemClang.cpp.
References lldb_private::CompilerType::Clear(), GetCanonicalQualType(), RemoveWrappingTypes(), and lldb_private::CompilerType::SetCompilerType().
IsRuntimeGeneratedType()
bool TypeSystemClang::IsRuntimeGeneratedType (lldb::opaque_compiler_type_t type) override virtual
This is used by swift.
Implements lldb_private::TypeSystem.
Definition at line 2920 of file TypeSystemClang.cpp.
References GetDeclContextForType(), GetMetadata(), and GetQualType().
IsScalarType()
bool TypeSystemClang::IsScalarType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3609 of file TypeSystemClang.cpp.
References GetTypeInfo().
IsScopedEnumerationType()
bool TypeSystemClang::IsScopedEnumerationType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3229 of file TypeSystemClang.cpp.
References GetCanonicalQualType().
Referenced by IsPromotableIntegerType().
IsTemplateType()
bool TypeSystemClang::IsTemplateType (lldb::opaque_compiler_type_t type) override virtual
Reimplemented from lldb_private::TypeSystem.
Definition at line 7038 of file TypeSystemClang.cpp.
References lldb_private::ClangUtil::GetQualType().
IsTypedefType()
bool TypeSystemClang::IsTypedefType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3616 of file TypeSystemClang.cpp.
References GetQualType(), and RemoveWrappingTypes().
IsTypeImpl()
bool TypeSystemClang::IsTypeImpl (lldb::opaque_compiler_type_t type, llvm::function_ref< bool(clang::QualType)> predicate) const private
Definition at line 3129 of file TypeSystemClang.cpp.
References GetCanonicalQualType(), IsTypeImpl(), and RemoveWrappingTypes().
Referenced by IsBlockPointerType(), IsFunctionPointerType(), IsFunctionType(), IsMemberFunctionPointerType(), and IsTypeImpl().
IsVectorType()
bool TypeSystemClang::IsVectorType (lldb::opaque_compiler_type_t type, CompilerType * element_type, uint64_t * size) override virtual
Implements lldb_private::TypeSystem.
Definition at line 2884 of file TypeSystemClang.cpp.
References GetCanonicalQualType(), and GetType().
IsVoidType()
bool TypeSystemClang::IsVoidType (lldb::opaque_compiler_type_t type) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3623 of file TypeSystemClang.cpp.
References GetCanonicalQualType().
LayoutRecordType()
bool TypeSystemClang::LayoutRecordType (const clang::RecordDecl * record_decl, uint64_t & size, uint64_t & alignment, llvm::DenseMap< const clang::FieldDecl *, uint64_t > & field_offsets, llvm::DenseMap< const clang::CXXRecordDecl *, clang::CharUnits > & base_offsets, llvm::DenseMap< const clang::CXXRecordDecl *, clang::CharUnits > & vbase_offsets)
Definition at line 9043 of file TypeSystemClang.cpp.
References lldb_private::ClangASTImporter::LayoutRecordType(), m_dwarf_ast_parser_up, m_native_pdb_ast_parser_up, and m_pdb_ast_parser_up.
LogCreation()
void TypeSystemClang::LogCreation () const private
Emits information about this TypeSystem into the expression log.
Helper method that is used in TypeSystemClang::TypeSystemClang on creation of a new instance.
Definition at line 9828 of file TypeSystemClang.cpp.
References lldb_private::Expressions, getASTContext(), getDisplayName(), lldb_private::GetLog(), and LLDB_LOG.
Referenced by TypeSystemClang().
operator=()
const TypeSystemClang & lldb_private::TypeSystemClang::operator= (const TypeSystemClang &) private
References TypeSystemClang().
ParseClassTemplateDecl()
clang::ClassTemplateDecl * TypeSystemClang::ParseClassTemplateDecl (clang::DeclContext * decl_ctx, OptionalClangModuleID owning_module, lldb::AccessType access_type, const char * parent_name, int tag_decl_kind, const TypeSystemClang::TemplateParameterInfos & template_param_infos)
Definition at line 8987 of file TypeSystemClang.cpp.
References CreateClassTemplateDecl(), and lldb_private::TypeSystemClang::TemplateParameterInfos::IsValid().
RecordHasFields()
bool TypeSystemClang::RecordHasFields (const clang::RecordDecl * record_decl)
Definition at line 1768 of file TypeSystemClang.cpp.
References GetMetadata(), and RecordHasFields().
Referenced by BaseSpecifierIsEmpty(), GetChildCompilerTypeAtIndex(), GetIndexOfChildWithName(), and RecordHasFields().
RequireCompleteType()
void TypeSystemClang::RequireCompleteType (CompilerType type) static
Complete a type from debug info, or mark it as forcefully completed if there is no definition of the type in the current Module.
Call this function in contexts where the usual C++ rules require a type to be complete (base class, member, etc.).
Definition at line 9588 of file TypeSystemClang.cpp.
References CompleteTagDeclarationDefinition(), lldb_private::ClangUtil::GetAsTagDecl(), lldb_private::CompilerType::GetCompleteType(), lldb_private::CompilerType::GetTypeSystem(), IsCXXClassType(), IsObjCObjectOrInterfaceType(), lldbassert, StartTagDeclarationDefinition(), and TypeSystemClang().
Referenced by lldb_private::npdb::UdtRecordCompleter::AddMethod(), lldb_private::npdb::UdtRecordCompleter::complete(), lldb_private::npdb::PdbAstBuilderClang::CreateArrayType(), DWARFASTParserClang::ParseArrayType(), DWARFASTParserClang::ParseInheritance(), and DWARFASTParserClang::ParseSingleMember().
SetDeclIsForcefullyCompleted()
bool TypeSystemClang::SetDeclIsForcefullyCompleted (const clang::TagDecl * td)
Definition at line 9815 of file TypeSystemClang.cpp.
References GetMetadata(), lldb_private::TypeSystem::m_has_forcefully_completed_types, and SetMetadata().
Referenced by PrepareContextToReceiveMembers().
SetExternalSource()
void TypeSystemClang::SetExternalSource (llvm::IntrusiveRefCntPtr< clang::ExternalASTSource > ast_source_sp)
Definition at line 619 of file TypeSystemClang.cpp.
References getASTContext().
Referenced by CreateASTContext(), and lldb_private::ScratchTypeSystemClang::ScratchTypeSystemClang().
SetFloatingInitializerForVariable()
void TypeSystemClang::SetFloatingInitializerForVariable (clang::VarDecl * var, const llvm::APFloat & init_value) static
Initializes a variable with a floating point value.
Parameters
var The variable to initialize. Must not already have an initializer and must have a floating point type.
init_value The float value that the variable should be initialized to.
Definition at line 7664 of file TypeSystemClang.cpp.
Referenced by PDBASTParser::AddRecordMembers().
SetHasExternalStorage()
bool TypeSystemClang::SetHasExternalStorage (lldb::opaque_compiler_type_t type, bool has_extern) static
Definition at line 8282 of file TypeSystemClang.cpp.
References GetCanonicalQualType(), and RemoveWrappingTypes().
Referenced by lldb_private::npdb::PdbAstBuilderClang::CompleteTagDecl(), lldb_private::ClangASTImporter::CompleteType(), PDBASTParser::CompleteTypeFromPDB(), lldb_private::npdb::PdbAstBuilderClang::CreateEnumType(), PDBASTParser::CreateLLDBTypeFromPDBType(), and lldb_private::npdb::PdbAstBuilderClang::CreateRecordType().
SetIntegerInitializerForVariable()
void TypeSystemClang::SetIntegerInitializerForVariable (clang::VarDecl * var, const llvm::APInt & init_value) static
Initializes a variable with an integer value.
Parameters
var The variable to initialize. Must not already have an initializer and must have an integer or enum type.
init_value The integer value that the variable should be initialized to. Has to match the bit width of the variable type.
Definition at line 7639 of file TypeSystemClang.cpp.
Referenced by PDBASTParser::AddRecordMembers(), and DWARFASTParserClang::CreateStaticMemberVariable().
SetIsPacked()
void TypeSystemClang::SetIsPacked (const CompilerType & type) static
Definition at line 7587 of file TypeSystemClang.cpp.
References GetAsRecordDecl(), lldb_private::CompilerType::GetTypeSystem(), and TypeSystemClang().
Referenced by CreateStructForIdentifier().
SetMetadata() [1/2]
void TypeSystemClang::SetMetadata (const clang::Decl * object, ClangASTMetadata meta_data)
Definition at line 2495 of file TypeSystemClang.cpp.
References m_decl_metadata.
Referenced by CreateObjCClass(), CreateRecordType(), SetDeclIsForcefullyCompleted(), SetMetadataAsUserID(), and SetMetadataAsUserID().
SetMetadata() [2/2]
void TypeSystemClang::SetMetadata (const clang::Type * object, ClangASTMetadata meta_data)
Definition at line 2500 of file TypeSystemClang.cpp.
References m_type_metadata.
SetMetadataAsUserID() [1/2]
void TypeSystemClang::SetMetadataAsUserID (const clang::Decl * decl, lldb::user_id_t user_id)
Definition at line 2481 of file TypeSystemClang.cpp.
References SetMetadata(), and lldb_private::ClangASTMetadata::SetUserID().
SetMetadataAsUserID() [2/2]
void TypeSystemClang::SetMetadataAsUserID (const clang::Type * type, lldb::user_id_t user_id)
Definition at line 2488 of file TypeSystemClang.cpp.
References SetMetadata(), and lldb_private::ClangASTMetadata::SetUserID().
SetObjCSuperClass()
bool TypeSystemClang::SetObjCSuperClass (const CompilerType & type, const CompilerType & superclass_compiler_type) static
Definition at line 7921 of file TypeSystemClang.cpp.
References GetAsObjCInterfaceDecl(), lldb_private::CompilerType::GetTypeSystem(), lldb_private::CompilerType::IsValid(), and TypeSystemClang().
SetOwningModule()
void TypeSystemClang::SetOwningModule (clang::Decl * decl, OptionalClangModuleID owning_module) static
Set the owning module for decl.
Definition at line 1222 of file TypeSystemClang.cpp.
References lldb_private::OptionalClangModuleID::GetValue(), and lldb_private::OptionalClangModuleID::HasValue().
Referenced by CreateBlockDeclaration(), CreateClassTemplateDecl(), CreateClassTemplateSpecializationDecl(), CreateEnumerationType(), CreateFunctionDeclaration(), CreateFunctionTemplateDecl(), CreateObjCClass(), CreateParameterDeclaration(), CreateRecordType(), CreateTypedef(), CreateUsingDeclaration(), CreateUsingDirectiveDeclaration(), CreateVariableDeclaration(), GetUniqueNamespaceDeclaration(), and lldb_private::ClangASTImporter::ASTImporterDelegate::Imported().
setSema()
void TypeSystemClang::setSema (clang::Sema * s)
Definition at line 605 of file TypeSystemClang.cpp.
References m_ast_up, and m_sema.
SetTargetTriple()
void TypeSystemClang::SetTargetTriple (llvm::StringRef target_triple) private
Definition at line 615 of file TypeSystemClang.cpp.
References m_target_triple.
Referenced by TypeSystemClang().
StartTagDeclarationDefinition()
bool TypeSystemClang::StartTagDeclarationDefinition (const CompilerType & type) static
Definition at line 8335 of file TypeSystemClang.cpp.
References lldb_private::ClangUtil::GetQualType().
Referenced by lldb_private::npdb::UdtRecordCompleter::AddMember(), PDBASTParser::AddRecordBases(), PDBASTParser::AddRecordMembers(), PDBASTParser::AddRecordMethod(), lldb_private::AppleObjCTypeEncodingParser::BuildAggregate(), DWARFASTParserClang::CompleteEnumType(), DWARFASTParserClang::CompleteRecordType(), lldb_private::npdb::PdbAstBuilderClang::CreateEnumType(), PDBASTParser::CreateLLDBTypeFromPDBType(), lldb_private::npdb::PdbAstBuilderClang::CreateRecordType(), CreateStructForIdentifier(), GetLLDBNSPairType(), lldb_private::platform_freebsd::PlatformFreeBSD::GetSiginfoType(), lldb_private::platform_linux::PlatformLinux::GetSiginfoType(), lldb_private::platform_netbsd::PlatformNetBSD::GetSiginfoType(), PrepareContextToReceiveMembers(), SystemRuntimeMacOSX::ReadLibdispatchTSDIndexes(), and RequireCompleteType().
SupportsLanguage()
bool TypeSystemClang::SupportsLanguage (lldb::LanguageType language) override virtual
Implements lldb_private::TypeSystem.
Definition at line 3637 of file TypeSystemClang.cpp.
Terminate()
void TypeSystemClang::Terminate () static
Definition at line 585 of file TypeSystemClang.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
TransferBaseClasses()
bool TypeSystemClang::TransferBaseClasses (lldb::opaque_compiler_type_t type, std::vector< std::unique_ptr< clang::CXXBaseSpecifier > > bases)
Definition at line 7902 of file TypeSystemClang.cpp.
References GetAsCXXRecordDecl().
Verify()
bool TypeSystemClang::Verify (lldb::opaque_compiler_type_t type) override virtual
Verify the integrity of the type to catch CompilerTypes that mix and match invalid TypeSystem/Opaque type pairs.
Implements lldb_private::TypeSystem.
Definition at line 2766 of file TypeSystemClang.cpp.
References GetQualType().
Member Data Documentation
ID
char TypeSystemClang::ID static private
Definition at line 119 of file TypeSystemClang.h.
Referenced by classof(), and isA().
m_ast_owned
bool lldb_private::TypeSystemClang::m_ast_owned = false private
Definition at line 1225 of file TypeSystemClang.h.
Referenced by CreateASTContext(), and Finalize().
m_ast_up
std::unique_ptr<clang::ASTContext> lldb_private::TypeSystemClang::m_ast_up private
Definition at line 1205 of file TypeSystemClang.h.
Referenced by CreateASTContext(), CreateBlockPointerType(), Dump(), Finalize(), getASTContext(), IsBlockPointerType(), and setSema().
m_builtins_up
std::unique_ptr<clang::Builtin::Context> lldb_private::TypeSystemClang::m_builtins_up private
Definition at line 1216 of file TypeSystemClang.h.
Referenced by CreateASTContext(), and Finalize().
m_decl_metadata
DeclMetadataMap lldb_private::TypeSystemClang::m_decl_metadata private
Maps Decls to their associated ClangASTMetadata.
Definition at line 1233 of file TypeSystemClang.h.
Referenced by GetMetadata(), and SetMetadata().
m_diagnostic_consumer_up
std::unique_ptr<clang::DiagnosticConsumer> lldb_private::TypeSystemClang::m_diagnostic_consumer_up private
Definition at line 1211 of file TypeSystemClang.h.
Referenced by CreateASTContext().
m_diagnostic_options_up
std::unique_ptr<clang::DiagnosticOptions> lldb_private::TypeSystemClang::m_diagnostic_options_up private
Definition at line 1209 of file TypeSystemClang.h.
Referenced by CreateASTContext().
m_diagnostics_engine_up
std::unique_ptr<clang::DiagnosticsEngine> lldb_private::TypeSystemClang::m_diagnostics_engine_up private
Definition at line 1210 of file TypeSystemClang.h.
Referenced by CreateASTContext(), Finalize(), and GetOrCreateClangModule().
m_display_name
std::string lldb_private::TypeSystemClang::m_display_name private
A string describing what this TypeSystemClang represents (e.g., AST for debug information, an expression, some other utility ClangAST).
Useful for logging and debugging.
Definition at line 1229 of file TypeSystemClang.h.
Referenced by getDisplayName(), and TypeSystemClang().
m_dwarf_ast_parser_up
std::unique_ptr<DWARFASTParserClang> lldb_private::TypeSystemClang::m_dwarf_ast_parser_up private
Definition at line 1220 of file TypeSystemClang.h.
Referenced by GetDWARFParser(), and LayoutRecordType().
m_file_manager_up
std::unique_ptr<clang::FileManager> lldb_private::TypeSystemClang::m_file_manager_up private
Definition at line 1207 of file TypeSystemClang.h.
Referenced by CreateASTContext().
m_header_search_opts_up
std::unique_ptr<clang::HeaderSearchOptions> lldb_private::TypeSystemClang::m_header_search_opts_up private
Definition at line 1217 of file TypeSystemClang.h.
Referenced by GetOrCreateClangModule().
m_header_search_up
std::unique_ptr<clang::HeaderSearch> lldb_private::TypeSystemClang::m_header_search_up private
Definition at line 1218 of file TypeSystemClang.h.
Referenced by GetOrCreateClangModule().
m_identifier_table_up
std::unique_ptr<clang::IdentifierTable> lldb_private::TypeSystemClang::m_identifier_table_up private
Definition at line 1214 of file TypeSystemClang.h.
Referenced by CreateASTContext(), and Finalize().
m_language_options_up
std::unique_ptr<clang::LangOptions> lldb_private::TypeSystemClang::m_language_options_up private
Definition at line 1206 of file TypeSystemClang.h.
Referenced by CreateASTContext(), Finalize(), GetLangOpts(), and GetOrCreateClangModule().
m_mangle_ctx_up
std::unique_ptr<clang::MangleContext> lldb_private::TypeSystemClang::m_mangle_ctx_up private
Definition at line 1223 of file TypeSystemClang.h.
Referenced by getMangleContext().
m_module_map_up
std::unique_ptr<clang::ModuleMap> lldb_private::TypeSystemClang::m_module_map_up private
Definition at line 1219 of file TypeSystemClang.h.
Referenced by GetOrCreateClangModule().
m_native_pdb_ast_parser_up
std::unique_ptr<npdb::PdbAstBuilderClang> lldb_private::TypeSystemClang::m_native_pdb_ast_parser_up private
Definition at line 1222 of file TypeSystemClang.h.
Referenced by GetNativePDBParser(), and LayoutRecordType().
m_pdb_ast_parser_up
std::unique_ptr<PDBASTParser> lldb_private::TypeSystemClang::m_pdb_ast_parser_up private
Definition at line 1221 of file TypeSystemClang.h.
Referenced by GetPDBParser(), and LayoutRecordType().
m_pointer_byte_size
uint32_t lldb_private::TypeSystemClang::m_pointer_byte_size = 0 private
Definition at line 1224 of file TypeSystemClang.h.
Referenced by GetPointerByteSize().
m_selector_table_up
std::unique_ptr<clang::SelectorTable> lldb_private::TypeSystemClang::m_selector_table_up private
Definition at line 1215 of file TypeSystemClang.h.
Referenced by CreateASTContext(), and Finalize().
m_sema
clang::Sema* lldb_private::TypeSystemClang::m_sema = nullptr private
The sema associated that is currently used to build this ASTContext.
May be null if we are already done parsing this ASTContext or the ASTContext wasn't created by parsing source code.
Definition at line 1242 of file TypeSystemClang.h.
Referenced by getSema(), and setSema().
m_source_manager_up
std::unique_ptr<clang::SourceManager> lldb_private::TypeSystemClang::m_source_manager_up private
Definition at line 1208 of file TypeSystemClang.h.
Referenced by CreateASTContext(), Finalize(), GetOrCreateClangModule(), and GetSourceMgr().
m_target_info_up
std::unique_ptr<clang::TargetInfo> lldb_private::TypeSystemClang::m_target_info_up private
Definition at line 1213 of file TypeSystemClang.h.
Referenced by Finalize(), GetOrCreateClangModule(), and getTargetInfo().
m_target_options_rp
std::shared_ptr<clang::TargetOptions> lldb_private::TypeSystemClang::m_target_options_rp private
Definition at line 1212 of file TypeSystemClang.h.
Referenced by Finalize(), and getTargetOptions().
m_target_triple
std::string lldb_private::TypeSystemClang::m_target_triple private
Definition at line 1204 of file TypeSystemClang.h.
Referenced by CreateASTContext(), getTargetInfo(), getTargetOptions(), GetTargetTriple(), and SetTargetTriple().
m_type_metadata
TypeMetadataMap lldb_private::TypeSystemClang::m_type_metadata private
Maps Types to their associated ClangASTMetadata.
Definition at line 1237 of file TypeSystemClang.h.
Referenced by GetMetadata(), and SetMetadata().
The documentation for this class was generated from the following files:
TypeSystemClang.h
TypeSystemClang.cpp