LLDB: lldb_private::Unwind Class Reference
lldb_private::Unwind Class Reference abstract
#include <Unwind.h>
Public Member Functions
virtual ~Unwind ()=default
void Clear ()
uint32_t GetFrameCount ()
uint32_t GetFramesUpTo (uint32_t end_idx)
bool GetFrameInfoAtIndex (uint32_t frame_idx, lldb::addr_t &cfa, lldb::addr_t &pc, bool &behaves_like_zeroth_frame)
lldb::RegisterContextSP CreateRegisterContextForFrame (StackFrame *frame)
Thread & GetThread ()
Protected Member Functions
Unwind (Thread &thread)
virtual void DoClear ()=0
virtual uint32_t DoGetFrameCount ()=0
virtual bool DoGetFrameInfoAtIndex (uint32_t frame_idx, lldb::addr_t &cfa, lldb::addr_t &pc, bool &behaves_like_zeroth_frame)=0
virtual lldb::RegisterContextSP DoCreateRegisterContextForFrame (StackFrame *frame)=0
Protected Attributes
Thread & m_thread
std::recursive_mutex m_unwind_mutex
Private Member Functions
Unwind (const Unwind &)=delete
const Unwind & operator= (const Unwind &)=delete
Detailed Description
Definition at line 18 of file Unwind.h.
Constructor & Destructor Documentation
Unwind() [1/2]
lldb_private::Unwind::Unwind (Thread & thread) inline protected
Definition at line 21 of file Unwind.h.
References m_thread.
Referenced by lldb_private::HistoryUnwind::HistoryUnwind(), operator=(), Unwind(), lldb_private::UnwindLLDB::UnwindLLDB(), and lldb_private::wasm::UnwindWasm::UnwindWasm().
~Unwind()
virtual lldb_private::Unwind::~Unwind () virtual default
Unwind() [2/2]
lldb_private::Unwind::Unwind (const Unwind &) private delete
References Unwind().
Member Function Documentation
Clear()
void lldb_private::Unwind::Clear () inline
Definition at line 26 of file Unwind.h.
References DoClear(), and m_unwind_mutex.
Referenced by lldb_private::Thread::ClearStackFrames().
CreateRegisterContextForFrame()
lldb::RegisterContextSP lldb_private::Unwind::CreateRegisterContextForFrame (StackFrame * frame) inline
Definition at line 56 of file Unwind.h.
References DoCreateRegisterContextForFrame(), and m_unwind_mutex.
Referenced by lldb_private::process_gdb_remote::ThreadGDBRemote::CreateRegisterContextForFrame(), lldb_private::ScriptedThread::CreateRegisterContextForFrame(), lldb_private::TargetThreadWindows::CreateRegisterContextForFrame(), lldb_private::wasm::ThreadWasm::CreateRegisterContextForFrame(), ThreadElfCore::CreateRegisterContextForFrame(), ThreadFreeBSDKernelCore::CreateRegisterContextForFrame(), ThreadKDP::CreateRegisterContextForFrame(), ThreadMachCore::CreateRegisterContextForFrame(), and ThreadMemory::CreateRegisterContextForFrame().
DoClear()
virtual void lldb_private::Unwind::DoClear () protected pure virtual
Implemented in lldb_private::HistoryUnwind, lldb_private::UnwindLLDB, and lldb_private::wasm::UnwindWasm.
Referenced by Clear().
DoCreateRegisterContextForFrame()
virtual lldb::RegisterContextSP lldb_private::Unwind::DoCreateRegisterContextForFrame (StackFrame * frame) protected pure virtual
Implemented in lldb_private::HistoryUnwind, lldb_private::UnwindLLDB, and lldb_private::wasm::UnwindWasm.
Referenced by CreateRegisterContextForFrame().
DoGetFrameCount()
virtual uint32_t lldb_private::Unwind::DoGetFrameCount () protected pure virtual
Implemented in lldb_private::HistoryUnwind, lldb_private::UnwindLLDB, and lldb_private::wasm::UnwindWasm.
Referenced by GetFrameCount().
DoGetFrameInfoAtIndex()
virtual bool lldb_private::Unwind::DoGetFrameInfoAtIndex (uint32_t frame_idx, lldb::addr_t & cfa, lldb::addr_t & pc, bool & behaves_like_zeroth_frame) protected pure virtual
Implemented in lldb_private::HistoryUnwind, lldb_private::UnwindLLDB, and lldb_private::wasm::UnwindWasm.
References pc.
Referenced by GetFrameInfoAtIndex(), and GetFramesUpTo().
GetFrameCount()
uint32_t lldb_private::Unwind::GetFrameCount () inline
Definition at line 31 of file Unwind.h.
References DoGetFrameCount(), and m_unwind_mutex.
GetFrameInfoAtIndex()
bool lldb_private::Unwind::GetFrameInfoAtIndex (uint32_t frame_idx, lldb::addr_t & cfa, lldb::addr_t & pc, bool & behaves_like_zeroth_frame) inline
Definition at line 50 of file Unwind.h.
References DoGetFrameInfoAtIndex(), m_unwind_mutex, and pc.
Referenced by lldb_private::StackFrameList::FetchFramesUpTo().
GetFramesUpTo()
uint32_t lldb_private::Unwind::GetFramesUpTo (uint32_t end_idx) inline
Definition at line 36 of file Unwind.h.
References DoGetFrameInfoAtIndex(), and pc.
Referenced by lldb_private::StackFrameList::FetchOnlyConcreteFramesUpTo().
GetThread()
Thread & lldb_private::Unwind::GetThread () inline
Definition at line 61 of file Unwind.h.
References m_thread.
Referenced by lldb_private::wasm::UnwindWasm::DoGetFrameCount().
operator=()
const Unwind & lldb_private::Unwind::operator= (const Unwind &) private delete
References Unwind().
Member Data Documentation
m_thread
Thread& lldb_private::Unwind::m_thread protected
Definition at line 76 of file Unwind.h.
Referenced by lldb_private::UnwindLLDB::AddFirstFrame(), lldb_private::UnwindLLDB::AddOneMoreFrame(), lldb_private::UnwindLLDB::DoCreateRegisterContextForFrame(), lldb_private::UnwindLLDB::DoGetFrameCount(), lldb_private::UnwindLLDB::DoGetFrameInfoAtIndex(), lldb_private::UnwindLLDB::GetOneMoreFrame(), GetThread(), and Unwind().
m_unwind_mutex
std::recursive_mutex lldb_private::Unwind::m_unwind_mutex protected
Definition at line 77 of file Unwind.h.
Referenced by Clear(), CreateRegisterContextForFrame(), lldb_private::HistoryUnwind::DoClear(), lldb_private::HistoryUnwind::DoGetFrameInfoAtIndex(), GetFrameCount(), and GetFrameInfoAtIndex().
The documentation for this class was generated from the following file:
Unwind.h