LLDB: lldb::SBExpressionOptions Class Reference
lldb::SBExpressionOptions Class Reference
#include <SBExpressionOptions.h>
Public Member Functions
SBExpressionOptions ()
SBExpressionOptions (const lldb::SBExpressionOptions &rhs)
~SBExpressionOptions ()
const SBExpressionOptions & operator= (const lldb::SBExpressionOptions &rhs)
bool GetCoerceResultToId () const
void SetCoerceResultToId (bool coerce=true)
bool GetUnwindOnError () const
void SetUnwindOnError (bool unwind=true)
bool GetIgnoreBreakpoints () const
void SetIgnoreBreakpoints (bool ignore=true)
lldb::DynamicValueType GetFetchDynamicValue () const
void SetFetchDynamicValue (lldb::DynamicValueType dynamic=lldb::eDynamicCanRunTarget)
uint32_t GetTimeoutInMicroSeconds () const
void SetTimeoutInMicroSeconds (uint32_t timeout=0)
uint32_t GetOneThreadTimeoutInMicroSeconds () const
void SetOneThreadTimeoutInMicroSeconds (uint32_t timeout=0)
bool GetTryAllThreads () const
void SetTryAllThreads (bool run_others=true)
bool GetStopOthers () const
void SetStopOthers (bool stop_others=true)
bool GetTrapExceptions () const
void SetTrapExceptions (bool trap_exceptions=true)
void SetLanguage (lldb::LanguageType language)
void SetLanguage (lldb::SBSourceLanguageName name, uint32_t version)
Set the language using a pair of language code and version as defined by the DWARF 6 specification.
void SetCancelCallback (lldb::ExpressionCancelCallback callback, void *baton)
bool GetGenerateDebugInfo ()
void SetGenerateDebugInfo (bool b=true)
bool GetSuppressPersistentResult ()
void SetSuppressPersistentResult (bool b=false)
const char * GetPrefix () const
void SetPrefix (const char *prefix)
void SetAutoApplyFixIts (bool b=true)
bool GetAutoApplyFixIts ()
void SetRetriesWithFixIts (uint64_t retries)
uint64_t GetRetriesWithFixIts ()
bool GetTopLevel ()
void SetTopLevel (bool b=true)
bool GetAllowJIT ()
void SetAllowJIT (bool allow)
bool GetBooleanLanguageOption (const char *option_name, SBError &error) const
SBError SetBooleanLanguageOption (const char *option_name, bool value)
Protected Member Functions
lldb_private::EvaluateExpressionOptions * get () const
lldb_private::EvaluateExpressionOptions & ref () const
Private Attributes
std::unique_ptr< lldb_private::EvaluateExpressionOptions > m_opaque_up
Friends
class SBFrame
class SBValue
class SBTarget
Detailed Description
Definition at line 19 of file SBExpressionOptions.h.
Constructor & Destructor Documentation
SBExpressionOptions() [1/2]
SBExpressionOptions::SBExpressionOptions ()
Definition at line 19 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by operator=(), SBExpressionOptions(), and ~SBExpressionOptions().
SBExpressionOptions() [2/2]
SBExpressionOptions::SBExpressionOptions (const lldb::SBExpressionOptions & rhs)
Definition at line 24 of file SBExpressionOptions.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBExpressionOptions().
~SBExpressionOptions()
SBExpressionOptions::~SBExpressionOptions () default
References lldb::eDynamicCanRunTarget, error(), get(), GetAllowJIT(), GetAutoApplyFixIts(), GetBooleanLanguageOption(), GetCoerceResultToId(), GetFetchDynamicValue(), GetGenerateDebugInfo(), GetIgnoreBreakpoints(), GetOneThreadTimeoutInMicroSeconds(), GetPrefix(), GetRetriesWithFixIts(), GetStopOthers(), GetSuppressPersistentResult(), GetTimeoutInMicroSeconds(), GetTopLevel(), GetTrapExceptions(), GetTryAllThreads(), GetUnwindOnError(), operator=(), ref(), SBExpressionOptions(), SetAllowJIT(), SetAutoApplyFixIts(), SetBooleanLanguageOption(), SetCancelCallback(), SetCoerceResultToId(), SetFetchDynamicValue(), SetGenerateDebugInfo(), SetIgnoreBreakpoints(), SetLanguage(), SetOneThreadTimeoutInMicroSeconds(), SetPrefix(), SetRetriesWithFixIts(), SetStopOthers(), SetSuppressPersistentResult(), SetTimeoutInMicroSeconds(), SetTopLevel(), SetTrapExceptions(), SetTryAllThreads(), and SetUnwindOnError().
Member Function Documentation
get()
EvaluateExpressionOptions * SBExpressionOptions::get () const protected
Definition at line 292 of file SBExpressionOptions.cpp.
References m_opaque_up.
Referenced by ~SBExpressionOptions().
GetAllowJIT()
bool SBExpressionOptions::GetAllowJIT ()
Definition at line 247 of file SBExpressionOptions.cpp.
References lldb_private::eExecutionPolicyNever, LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
GetAutoApplyFixIts()
bool SBExpressionOptions::GetAutoApplyFixIts ()
Definition at line 210 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
GetBooleanLanguageOption()
bool SBExpressionOptions::GetBooleanLanguageOption (const char * option_name, SBError & error) const
Definition at line 264 of file SBExpressionOptions.cpp.
References error(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
GetCoerceResultToId()
bool SBExpressionOptions::GetCoerceResultToId () const
Definition at line 41 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
GetFetchDynamicValue()
lldb::DynamicValueType SBExpressionOptions::GetFetchDynamicValue () const
Definition at line 77 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBFrame::EvaluateExpression(), lldb::SBTarget::EvaluateExpression(), lldb::SBValue::EvaluateExpression(), and ~SBExpressionOptions().
GetGenerateDebugInfo()
bool SBExpressionOptions::GetGenerateDebugInfo ()
Definition at line 174 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
GetIgnoreBreakpoints()
bool SBExpressionOptions::GetIgnoreBreakpoints () const
Definition at line 65 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
GetOneThreadTimeoutInMicroSeconds()
uint32_t SBExpressionOptions::GetOneThreadTimeoutInMicroSeconds () const
Definition at line 102 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
GetPrefix()
const char * SBExpressionOptions::GetPrefix () const
Definition at line 198 of file SBExpressionOptions.cpp.
References lldb_private::ConstString::GetCString(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
GetRetriesWithFixIts()
uint64_t SBExpressionOptions::GetRetriesWithFixIts ()
Definition at line 222 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
GetStopOthers()
bool SBExpressionOptions::GetStopOthers () const
Definition at line 130 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
GetSuppressPersistentResult()
bool SBExpressionOptions::GetSuppressPersistentResult ()
Definition at line 186 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
GetTimeoutInMicroSeconds()
uint32_t SBExpressionOptions::GetTimeoutInMicroSeconds () const
Definition at line 89 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
GetTopLevel()
bool SBExpressionOptions::GetTopLevel ()
Definition at line 234 of file SBExpressionOptions.cpp.
References lldb_private::eExecutionPolicyTopLevel, LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
GetTrapExceptions()
bool SBExpressionOptions::GetTrapExceptions () const
Definition at line 142 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
GetTryAllThreads()
bool SBExpressionOptions::GetTryAllThreads () const
Definition at line 118 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
GetUnwindOnError()
bool SBExpressionOptions::GetUnwindOnError () const
Definition at line 53 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
operator=()
const SBExpressionOptions & SBExpressionOptions::operator= (const lldb::SBExpressionOptions & rhs)
Definition at line 30 of file SBExpressionOptions.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBExpressionOptions().
Referenced by ~SBExpressionOptions().
ref()
EvaluateExpressionOptions & SBExpressionOptions::ref () const protected
Definition at line 296 of file SBExpressionOptions.cpp.
References m_opaque_up.
Referenced by lldb::SBValue::CreateValueFromExpression(), lldb::SBValue::CreateValueFromExpression(), lldb::SBFrame::EvaluateExpression(), lldb::SBTarget::EvaluateExpression(), lldb::SBValue::EvaluateExpression(), and ~SBExpressionOptions().
SetAllowJIT()
void SBExpressionOptions::SetAllowJIT (bool allow)
Definition at line 253 of file SBExpressionOptions.cpp.
References lldb_private::eExecutionPolicyNever, LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
SetAutoApplyFixIts()
void SBExpressionOptions::SetAutoApplyFixIts (bool b = true)
Definition at line 216 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
SetBooleanLanguageOption()
SBError SBExpressionOptions::SetBooleanLanguageOption (const char * option_name, bool value)
Definition at line 279 of file SBExpressionOptions.cpp.
References error(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
SetCancelCallback()
void SBExpressionOptions::SetCancelCallback (lldb::ExpressionCancelCallback callback, void * baton)
Definition at line 167 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
SetCoerceResultToId()
void SBExpressionOptions::SetCoerceResultToId (bool coerce = true)
Definition at line 47 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
SetFetchDynamicValue()
void SBExpressionOptions::SetFetchDynamicValue (lldb::DynamicValueType dynamic = lldb::eDynamicCanRunTarget)
Definition at line 83 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::EvaluateExpression(), lldb::SBTarget::EvaluateExpression(), lldb::SBValue::EvaluateExpression(), and ~SBExpressionOptions().
SetGenerateDebugInfo()
void SBExpressionOptions::SetGenerateDebugInfo (bool b = true)
Definition at line 180 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
SetIgnoreBreakpoints()
void SBExpressionOptions::SetIgnoreBreakpoints (bool ignore = true)
Definition at line 71 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::EvaluateExpression(), lldb::SBValue::EvaluateExpression(), and ~SBExpressionOptions().
SetLanguage() [1/2]
void SBExpressionOptions::SetLanguage (lldb::LanguageType language)
Definition at line 154 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::EvaluateExpression(), and ~SBExpressionOptions().
SetLanguage() [2/2]
void SBExpressionOptions::SetLanguage (lldb::SBSourceLanguageName name, uint32_t version)
Set the language using a pair of language code and version as defined by the DWARF 6 specification.
WARNING: These codes may change until DWARF 6 is finalized.
Definition at line 160 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
SetOneThreadTimeoutInMicroSeconds()
void SBExpressionOptions::SetOneThreadTimeoutInMicroSeconds (uint32_t timeout = 0)
Definition at line 110 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
SetPrefix()
void SBExpressionOptions::SetPrefix (const char * prefix)
Definition at line 204 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
SetRetriesWithFixIts()
void SBExpressionOptions::SetRetriesWithFixIts (uint64_t retries)
Definition at line 228 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
SetStopOthers()
void SBExpressionOptions::SetStopOthers (bool stop_others = true)
Definition at line 136 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
SetSuppressPersistentResult()
void SBExpressionOptions::SetSuppressPersistentResult (bool b = false)
Definition at line 192 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
SetTimeoutInMicroSeconds()
void SBExpressionOptions::SetTimeoutInMicroSeconds (uint32_t timeout = 0)
Definition at line 95 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
SetTopLevel()
void SBExpressionOptions::SetTopLevel (bool b = true)
Definition at line 240 of file SBExpressionOptions.cpp.
References lldb_private::eExecutionPolicyTopLevel, LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
SetTrapExceptions()
void SBExpressionOptions::SetTrapExceptions (bool trap_exceptions = true)
Definition at line 148 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
SetTryAllThreads()
void SBExpressionOptions::SetTryAllThreads (bool run_others = true)
Definition at line 124 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBExpressionOptions().
SetUnwindOnError()
void SBExpressionOptions::SetUnwindOnError (bool unwind = true)
Definition at line 59 of file SBExpressionOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::EvaluateExpression(), lldb::SBTarget::EvaluateExpression(), lldb::SBValue::EvaluateExpression(), and ~SBExpressionOptions().
Friends And Related Symbol Documentation
SBFrame
friend class SBFrame friend
Definition at line 119 of file SBExpressionOptions.h.
References SBFrame.
Referenced by SBFrame.
SBTarget
friend class SBTarget friend
Definition at line 121 of file SBExpressionOptions.h.
References SBTarget.
Referenced by SBTarget.
SBValue
friend class SBValue friend
Definition at line 120 of file SBExpressionOptions.h.
References SBValue.
Referenced by SBValue.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::EvaluateExpressionOptions> lldb::SBExpressionOptions::m_opaque_up mutable private
Definition at line 125 of file SBExpressionOptions.h.
Referenced by get(), GetAllowJIT(), GetAutoApplyFixIts(), GetBooleanLanguageOption(), GetCoerceResultToId(), GetFetchDynamicValue(), GetGenerateDebugInfo(), GetIgnoreBreakpoints(), GetOneThreadTimeoutInMicroSeconds(), GetPrefix(), GetRetriesWithFixIts(), GetStopOthers(), GetSuppressPersistentResult(), GetTimeoutInMicroSeconds(), GetTopLevel(), GetTrapExceptions(), GetTryAllThreads(), GetUnwindOnError(), operator=(), ref(), SBExpressionOptions(), SBExpressionOptions(), SetAllowJIT(), SetAutoApplyFixIts(), SetBooleanLanguageOption(), SetCancelCallback(), SetCoerceResultToId(), SetFetchDynamicValue(), SetGenerateDebugInfo(), SetIgnoreBreakpoints(), SetLanguage(), SetLanguage(), SetOneThreadTimeoutInMicroSeconds(), SetPrefix(), SetRetriesWithFixIts(), SetStopOthers(), SetSuppressPersistentResult(), SetTimeoutInMicroSeconds(), SetTopLevel(), SetTrapExceptions(), SetTryAllThreads(), and SetUnwindOnError().
The documentation for this class was generated from the following files:
SBExpressionOptions.h
SBExpressionOptions.cpp