LLDB: lldb_private::SBLaunchInfoImpl Class Reference
lldb_private::SBLaunchInfoImpl Class Reference
Public Member Functions
SBLaunchInfoImpl ()
const char *const * GetEnvp () const
void RegenerateEnvp ()
SBLaunchInfoImpl & operator= (const ProcessLaunchInfo &rhs)
Public Member Functions inherited from lldb_private::ProcessLaunchInfo
ProcessLaunchInfo ()
ProcessLaunchInfo (const FileSpec &stdin_file_spec, const FileSpec &stdout_file_spec, const FileSpec &stderr_file_spec, const FileSpec &working_dir, uint32_t launch_flags)
void AppendFileAction (const FileAction &info)
bool AppendCloseFileAction (int fd)
bool AppendDuplicateFileAction (int fd, int dup_fd)
bool AppendOpenFileAction (int fd, const FileSpec &file_spec, bool read, bool write)
bool AppendSuppressFileAction (int fd, bool read, bool write)
llvm::Error SetUpPtyRedirection ()
size_t GetNumFileActions () const
const FileAction * GetFileActionAtIndex (size_t idx) const
const FileAction * GetFileActionForFD (int fd) const
Flags & GetFlags ()
const Flags & GetFlags () const
const FileSpec & GetWorkingDirectory () const
void SetWorkingDirectory (const FileSpec &working_dir)
llvm::StringRef GetProcessPluginName () const
void SetProcessPluginName (llvm::StringRef plugin)
const FileSpec & GetShell () const
void SetShell (const FileSpec &shell)
uint32_t GetResumeCount () const
void SetResumeCount (uint32_t c)
bool GetLaunchInSeparateProcessGroup () const
void SetLaunchInSeparateProcessGroup (bool separate)
bool GetShellExpandArguments () const
void SetShellExpandArguments (bool expand)
void Clear ()
bool ConvertArgumentsForLaunchingInShell (Status &error, bool will_debug, bool first_arg_is_full_shell_command, uint32_t num_resumes)
void SetMonitorProcessCallback (Host::MonitorChildProcessCallback callback)
const Host::MonitorChildProcessCallback & GetMonitorProcessCallback () const
bool MonitorProcess () const
PTY & GetPTY () const
std::shared_ptr< PTY > TakePTY ()
bool ShouldUsePTY () const
Returns whether if lldb should read information from the PTY.
void SetLaunchEventData (const char *data)
const char * GetLaunchEventData () const
void SetDetachOnError (bool enable)
bool GetDetachOnError () const
Public Member Functions inherited from lldb_private::ProcessInfo
ProcessInfo ()
ProcessInfo (const char *name, const ArchSpec &arch, lldb::pid_t pid)
void Clear ()
const char * GetName () const
llvm::StringRef GetNameAsStringRef () const
FileSpec & GetExecutableFile ()
void SetExecutableFile (const FileSpec &exe_file, bool add_exe_file_as_first_arg)
const FileSpec & GetExecutableFile () const
uint32_t GetUserID () const
uint32_t GetGroupID () const
bool UserIDIsValid () const
bool GroupIDIsValid () const
void SetUserID (uint32_t uid)
void SetGroupID (uint32_t gid)
ArchSpec & GetArchitecture ()
const ArchSpec & GetArchitecture () const
void SetArchitecture (const ArchSpec &arch)
lldb::pid_t GetProcessID () const
void SetProcessID (lldb::pid_t pid)
bool ProcessIDIsValid () const
void Dump (Stream &s, Platform *platform) const
Args & GetArguments ()
const Args & GetArguments () const
llvm::StringRef GetArg0 () const
void SetArg0 (llvm::StringRef arg)
void SetArguments (const Args &args, bool first_arg_is_executable)
void SetArguments (char const **argv, bool first_arg_is_executable)
Environment & GetEnvironment ()
const Environment & GetEnvironment () const
bool IsScriptedProcess () const
lldb::ScriptedMetadataSP GetScriptedMetadata () const
void SetScriptedMetadata (lldb::ScriptedMetadataSP metadata_sp)
lldb::ListenerSP GetListener () const
void SetListener (const lldb::ListenerSP &listener_sp)
lldb::ListenerSP GetHijackListener () const
void SetHijackListener (const lldb::ListenerSP &listener_sp)
lldb::ListenerSP GetShadowListener () const
void SetShadowListener (const lldb::ListenerSP &listener_sp)
Private Attributes
Environment::Envp m_envp
Additional Inherited Members
Static Public Member Functions inherited from lldb_private::ProcessLaunchInfo
static void NoOpMonitorCallback (lldb::pid_t pid, int signal, int status)
A Monitor callback which does not take any action on process events.
Protected Attributes inherited from lldb_private::ProcessLaunchInfo
FileSpec m_working_dir
std::string m_plugin_name
FileSpec m_shell
Flags m_flags
std::vector< FileAction > m_file_actions
std::shared_ptr< PTY > m_pty
uint32_t m_resume_count = 0
Host::MonitorChildProcessCallback m_monitor_callback
std::string m_event_data
Protected Attributes inherited from lldb_private::ProcessInfo
FileSpec m_executable
std::string m_arg0
Args m_arguments
Environment m_environment
uint32_t m_uid = UINT32_MAX
uint32_t m_gid = UINT32_MAX
ArchSpec m_arch
lldb::pid_t m_pid = LLDB_INVALID_PROCESS_ID
lldb::ScriptedMetadataSP m_scripted_metadata_sp = nullptr
lldb::ListenerSP m_listener_sp = nullptr
lldb::ListenerSP m_hijack_listener_sp = nullptr
lldb::ListenerSP m_shadow_listener_sp = nullptr
Detailed Description
Definition at line 26 of file SBLaunchInfo.cpp.
Constructor & Destructor Documentation
SBLaunchInfoImpl()
lldb_private::SBLaunchInfoImpl::SBLaunchInfoImpl () inline
Definition at line 28 of file SBLaunchInfo.cpp.
References lldb_private::ProcessInfo::GetEnvironment(), and m_envp.
Referenced by operator=().
Member Function Documentation
GetEnvp()
const char *const * lldb_private::SBLaunchInfoImpl::GetEnvp () const inline
Definition at line 30 of file SBLaunchInfo.cpp.
References m_envp.
operator=()
SBLaunchInfoImpl & lldb_private::SBLaunchInfoImpl::operator= (const ProcessLaunchInfo & rhs) inline
Definition at line 33 of file SBLaunchInfo.cpp.
References lldb_private::ProcessLaunchInfo::ProcessLaunchInfo(), RegenerateEnvp(), and SBLaunchInfoImpl().
RegenerateEnvp()
void lldb_private::SBLaunchInfoImpl::RegenerateEnvp () inline
Definition at line 31 of file SBLaunchInfo.cpp.
References lldb_private::ProcessInfo::GetEnvironment(), lldb_private::Environment::getEnvp(), and m_envp.
Referenced by operator=().
Member Data Documentation
m_envp
Environment::Envp lldb_private::SBLaunchInfoImpl::m_envp private
Definition at line 40 of file SBLaunchInfo.cpp.
Referenced by GetEnvp(), RegenerateEnvp(), and SBLaunchInfoImpl().
The documentation for this class was generated from the following file:
SBLaunchInfo.cpp