LLDB: lldb_private::VariableAnnotator Class Reference
lldb_private::VariableAnnotator Class Reference
Tracks live variable annotations across instructions and produces per-instruction "events" like name = RDI or name = <undef>.
#include <Disassembler.h>
Public Member Functions
std::vector< std::string > Annotate (Instruction &inst)
Compute annotation strings for a single instruction and update m_live_vars.
std::vector< VariableAnnotation > AnnotateStructured (Instruction &inst)
Returns structured data for all variables relevant at this instruction.
Private Attributes
llvm::DenseMap< lldb::user_id_t, VariableAnnotation > m_live_vars
Detailed Description
Tracks live variable annotations across instructions and produces per-instruction "events" like name = RDI or name = <undef>.
Definition at line 603 of file Disassembler.h.
Member Function Documentation
Annotate()
std::vector< std::string > VariableAnnotator::Annotate (Instruction & inst)
Compute annotation strings for a single instruction and update m_live_vars.
Returns only the events that should be printed at this instruction.
Definition at line 314 of file Disassembler.cpp.
References AnnotateStructured(), kUndefLocation, and kUndefLocationFormatted.
Referenced by lldb_private::Disassembler::PrintInstructions().
AnnotateStructured()
std::vector< VariableAnnotation > VariableAnnotator::AnnotateStructured (Instruction & inst)
Returns structured data for all variables relevant at this instruction.
Definition at line 335 of file Disassembler.cpp.
References AddVariableAnnotationToVector(), lldb_private::ConstString::AsCString(), lldb_private::SymbolContext::block, lldb::eDescriptionLevelBrief, lldb_private::ABI::FindPlugin(), lldb_private::SymbolContext::function, lldb_private::Function::GetAddress(), lldb_private::Instruction::GetAddress(), lldb_private::DWARFExpressionList::GetExpressionEntryAtAddress(), lldb_private::Declaration::GetFile(), lldb_private::Address::GetFileAddress(), lldb_private::FileSpec::GetFilename(), lldb_private::Declaration::GetLine(), lldb_private::Address::GetModule(), lldb_private::VariableList::GetSize(), lldb_private::StreamString::GetString(), lldb_private::VariableList::GetVariableAtIndex(), lldb_private::DWARFExpressionList::IsValid(), and m_live_vars.
Referenced by Annotate(), and lldb_private::Instruction::GetVariableAnnotations().
Member Data Documentation
m_live_vars
llvm::DenseMap<lldb::user_id_t, VariableAnnotation> lldb_private::VariableAnnotator::m_live_vars private
Definition at line 606 of file Disassembler.h.
Referenced by AnnotateStructured().
The documentation for this class was generated from the following files:
Disassembler.h
Disassembler.cpp