LLDB: lldb_private::InstructionList Class Reference
lldb_private::InstructionList Class Reference
#include <Disassembler.h>
Public Member Functions
InstructionList ()
~InstructionList ()
size_t GetSize () const
size_t GetTotalByteSize () const
uint32_t GetMaxOpcocdeByteSize () const
lldb::InstructionSP GetInstructionAtIndex (size_t idx) const
llvm::ArrayRef< lldb::InstructionSP > Instructions () const
lldb::InstructionSP GetInstructionAtAddress (const Address &addr)
Get the instruction at the given address.
uint32_t GetIndexOfNextBranchInstruction (uint32_t start, bool ignore_calls, bool *found_calls) const
Get the index of the next branch instruction.
uint32_t GetIndexOfInstructionAtLoadAddress (lldb::addr_t load_addr, Target &target)
uint32_t GetIndexOfInstructionAtAddress (const Address &addr)
void Clear ()
void Append (lldb::InstructionSP &inst_sp)
void Dump (Stream *s, bool show_address, bool show_bytes, bool show_control_flow_kind, const ExecutionContext *exe_ctx)
Private Types
typedef std::vector< lldb::InstructionSP > collection
typedef collection::iterator iterator
typedef collection::const_iterator const_iterator
Private Attributes
collection m_instructions
Detailed Description
Definition at line 294 of file Disassembler.h.
Member Typedef Documentation
collection
typedef std::vector<lldb::InstructionSP> lldb_private::InstructionList::collection private
Definition at line 358 of file Disassembler.h.
const_iterator
typedef collection::const_iterator lldb_private::InstructionList::const_iterator private
Definition at line 360 of file Disassembler.h.
iterator
typedef collection::iterator lldb_private::InstructionList::iterator private
Definition at line 359 of file Disassembler.h.
Constructor & Destructor Documentation
InstructionList()
InstructionList::InstructionList ()
Definition at line 1233 of file Disassembler.cpp.
References m_instructions.
~InstructionList()
InstructionList::~InstructionList () default
Member Function Documentation
Append()
void InstructionList::Append (lldb::InstructionSP & inst_sp)
Definition at line 1303 of file Disassembler.cpp.
References m_instructions.
Referenced by lldb_private::ArchitectureMips::GetInstructionAtAddress().
Clear()
void InstructionList::Clear ()
Definition at line 1301 of file Disassembler.cpp.
References m_instructions.
Dump()
void InstructionList::Dump (Stream * s, bool show_address, bool show_bytes, bool show_control_flow_kind, const ExecutionContext * exe_ctx)
Definition at line 1275 of file Disassembler.cpp.
References lldb_private::Stream::EOL(), lldb_private::Target::GetDebugger(), lldb_private::Debugger::GetDisassemblyFormat(), GetMaxOpcocdeByteSize(), lldb_private::ExecutionContext::GetTargetRef(), lldb_private::ExecutionContext::HasTargetScope(), m_instructions, and lldb_private::FormatEntity::Parse().
Referenced by lldb_private::IRExecutionUnit::DisassembleFunction().
GetIndexOfInstructionAtAddress()
uint32_t InstructionList::GetIndexOfInstructionAtAddress (const Address & addr)
Definition at line 1332 of file Disassembler.cpp.
References m_instructions, and UINT32_MAX.
Referenced by lldb_private::Process::AdvanceAddressToNextBranchInstruction(), GetIndexOfInstructionAtLoadAddress(), GetInstructionAtAddress(), and UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly().
GetIndexOfInstructionAtLoadAddress()
uint32_t InstructionList::GetIndexOfInstructionAtLoadAddress (lldb::addr_t load_addr, Target & target)
Definition at line 1345 of file Disassembler.cpp.
References GetIndexOfInstructionAtAddress(), and lldb_private::Address::SetLoadAddress().
GetIndexOfNextBranchInstruction()
uint32_t InstructionList::GetIndexOfNextBranchInstruction (uint32_t start, bool ignore_calls, bool * found_calls) const
Get the index of the next branch instruction.
Given a list of instructions, find the next branch instruction in the list by returning an index.
Parameters
[in] start The instruction index of the first instruction to check.
[in] ignore_calls It true, then fine the first branch instruction that isn't a function call (a branch that calls and returns to the next instruction). If false, find the instruction index of any branch in the list.
[out] found_calls If non-null, this will be set to true if any calls were found in extending the range.
Returns
The instruction index of the first branch that is at or past start. Returns UINT32_MAX if no matching branches are found.
Definition at line 1308 of file Disassembler.cpp.
References m_instructions, and UINT32_MAX.
Referenced by lldb_private::Process::AdvanceAddressToNextBranchInstruction(), and lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint().
GetInstructionAtAddress()
InstructionSP InstructionList::GetInstructionAtAddress (const Address & addr)
Get the instruction at the given address.
Returns
A valid InstructionSP if the address could be found, or null otherwise.
Definition at line 1268 of file Disassembler.cpp.
References GetIndexOfInstructionAtAddress(), GetInstructionAtIndex(), and UINT32_MAX.
GetInstructionAtIndex()
InstructionSP InstructionList::GetInstructionAtIndex (size_t idx) const
Definition at line 1261 of file Disassembler.cpp.
References m_instructions.
Referenced by lldb_private::Process::AdvanceAddressToNextBranchInstruction(), lldb_private::ArchitectureMips::GetInstructionAtAddress(), GetInstructionAtAddress(), UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly(), GetPtrauthInstructionInfo(), lldb_private::DynamicLoaderWindowsDYLD::GetStepThroughTrampolinePlan(), lldb_private::ThreadPlanAssemblyTracer::Log(), lldb_private::Disassembler::PrintInstructions(), and lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint().
GetMaxOpcocdeByteSize()
uint32_t InstructionList::GetMaxOpcocdeByteSize () const
Definition at line 1239 of file Disassembler.cpp.
References m_instructions.
Referenced by Dump(), DumpInstToLog(), lldb_private::ThreadPlanAssemblyTracer::Log(), and lldb_private::Disassembler::PrintInstructions().
GetSize()
size_t InstructionList::GetSize () const
Definition at line 1237 of file Disassembler.cpp.
References m_instructions.
Referenced by lldb_private::ArchitectureMips::GetInstructionAtAddress(), UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly(), lldb_private::ThreadPlanAssemblyTracer::Log(), lldb_private::Disassembler::PrintInstructions(), and lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint().
GetTotalByteSize()
size_t InstructionList::GetTotalByteSize () const
Definition at line 1251 of file Disassembler.cpp.
References m_instructions.
Instructions()
llvm::ArrayRef< lldb::InstructionSP > lldb_private::InstructionList::Instructions () const inline
Definition at line 307 of file Disassembler.h.
References m_instructions.
Member Data Documentation
m_instructions
collection lldb_private::InstructionList::m_instructions private
Definition at line 362 of file Disassembler.h.
Referenced by Append(), Clear(), Dump(), GetIndexOfInstructionAtAddress(), GetIndexOfNextBranchInstruction(), GetInstructionAtIndex(), GetMaxOpcocdeByteSize(), GetSize(), GetTotalByteSize(), InstructionList(), and Instructions().
The documentation for this class was generated from the following files:
Disassembler.h
Disassembler.cpp