LLDB: lldb_private::CommandObjectExpression Class Reference
lldb_private::CommandObjectExpression Class Reference
#include <CommandObjectExpression.h>
Classes
class CommandOptions
Public Member Functions
CommandObjectExpression (CommandInterpreter &interpreter)
~CommandObjectExpression () override
Options * GetOptions () override
void HandleCompletion (CompletionRequest &request) override
This default version handles calling option argument completions and then calls HandleArgumentCompletion if the cursor is on an argument, not an option.
Public Member Functions inherited from lldb_private::CommandObjectRaw
CommandObjectRaw (CommandInterpreter &interpreter, llvm::StringRef name, llvm::StringRef help="", llvm::StringRef syntax="", uint32_t flags=0)
~CommandObjectRaw () override=default
void Execute (const char *args_string, CommandReturnObject &result) override
Public Member Functions inherited from lldb_private::CommandObject
CommandObject (CommandInterpreter &interpreter, llvm::StringRef name, llvm::StringRef help="", llvm::StringRef syntax="", uint32_t flags=0)
virtual ~CommandObject ()=default
CommandInterpreter & GetCommandInterpreter ()
Debugger & GetDebugger ()
virtual llvm::StringRef GetHelp ()
virtual llvm::StringRef GetHelpLong ()
virtual llvm::StringRef GetSyntax ()
llvm::StringRef GetCommandName () const
virtual void SetHelp (llvm::StringRef str)
virtual void SetHelpLong (llvm::StringRef str)
void SetSyntax (llvm::StringRef str)
virtual bool IsRemovable () const
virtual bool IsMultiwordObject ()
bool IsUserCommand ()
void SetIsUserCommand (bool is_user)
virtual CommandObjectMultiword * GetAsMultiwordCommand ()
virtual bool IsAlias ()
virtual bool IsDashDashCommand ()
virtual lldb::CommandObjectSP GetSubcommandSP (llvm::StringRef sub_cmd, StringList *matches=nullptr)
virtual lldb::CommandObjectSP GetSubcommandSPExact (llvm::StringRef sub_cmd)
virtual CommandObject * GetSubcommandObject (llvm::StringRef sub_cmd, StringList *matches=nullptr)
void FormatLongHelpText (Stream &output_strm, llvm::StringRef long_help)
void GenerateHelpText (CommandReturnObject &result)
virtual void GenerateHelpText (Stream &result)
virtual bool LoadSubCommand (llvm::StringRef cmd_name, const lldb::CommandObjectSP &command_obj)
virtual llvm::Error LoadUserSubcommand (llvm::StringRef cmd_name, const lldb::CommandObjectSP &command_obj, bool can_replace)
virtual bool WantsCompletion ()
void AddSimpleArgumentList (lldb::CommandArgumentType arg_type, ArgumentRepetitionType repetition_type=eArgRepeatPlain)
void AddIDsArgumentData (IDType type)
int GetNumArgumentEntries ()
CommandArgumentEntry * GetArgumentEntryAtIndex (int idx)
void GetFormattedCommandArguments (Stream &str, uint32_t opt_set_mask=LLDB_OPT_SET_ALL)
bool ParseOptions (Args &args, CommandReturnObject &result)
void SetCommandName (llvm::StringRef name)
virtual void HandleArgumentCompletion (CompletionRequest &request, OptionElementVector &opt_element_vector)
The default version handles argument definitions that have only one argument type, and use one of the argument types that have an entry in the CommonCompletions.
bool HelpTextContainsWord (llvm::StringRef search_word, bool search_short_help=true, bool search_long_help=true, bool search_syntax=true, bool search_options=true)
Flags & GetFlags ()
The flags accessor.
const Flags & GetFlags () const
The flags const accessor.
virtual std::optional< std::string > GetRepeatCommand (Args &current_command_args, uint32_t index)
Get the command that appropriate for a "repeat" of the current command.
bool HasOverrideCallback () const
void SetOverrideCallback (lldb::CommandOverrideCallback callback, void *baton)
void SetOverrideCallback (lldb_private::CommandOverrideCallbackWithResult callback, void *baton)
bool InvokeOverrideCallback (const char **argv, CommandReturnObject &result)
void SetOriginalCommandString (std::string s)
Set the command input as it appeared in the terminal.
Public Member Functions inherited from lldb_private::IOHandlerDelegate
IOHandlerDelegate (Completion completion=Completion::None)
virtual ~IOHandlerDelegate ()=default
virtual void IOHandlerActivated (IOHandler &io_handler, bool interactive)
virtual void IOHandlerDeactivated (IOHandler &io_handler)
virtual std::optional< std::string > IOHandlerSuggestion (IOHandler &io_handler, llvm::StringRef line)
virtual void IOHandlerComplete (IOHandler &io_handler, CompletionRequest &request)
virtual const char * IOHandlerGetFixIndentationCharacters ()
virtual int IOHandlerFixIndentation (IOHandler &io_handler, const StringList &lines, int cursor_position)
Called when a new line is created or one of an identified set of indentation characters is typed.
virtual void IOHandlerInputInterrupted (IOHandler &io_handler, std::string &data)
virtual llvm::StringRef IOHandlerGetControlSequence (char ch)
virtual const char * IOHandlerGetCommandPrefix ()
virtual const char * IOHandlerGetHelpPrologue ()
virtual bool IOHandlerInterrupt (IOHandler &io_handler)
Protected Member Functions
void IOHandlerInputComplete (IOHandler &io_handler, std::string &line) override
Called when a line or lines have been retrieved.
bool IOHandlerIsInputComplete (IOHandler &io_handler, StringList &lines) override
Called to determine whether typing enter after the last line in lines should end input.
void DoExecute (llvm::StringRef command, CommandReturnObject &result) override
bool EvaluateExpression (llvm::StringRef expr, Stream &output_stream, Stream &error_stream, CommandReturnObject &result)
Evaluates the given expression.
void GetMultilineExpression ()
Protected Member Functions inherited from lldb_private::CommandObjectRaw
bool WantsRawCommandString () override
Protected Member Functions inherited from lldb_private::CommandObject
bool ParseOptionsAndNotify (Args &args, CommandReturnObject &result, OptionGroupOptions &group_options, ExecutionContext &exe_ctx)
virtual const char * GetInvalidTargetDescription ()
virtual const char * GetInvalidProcessDescription ()
virtual const char * GetInvalidThreadDescription ()
virtual const char * GetInvalidFrameDescription ()
virtual const char * GetInvalidRegContextDescription ()
Target & GetDummyTarget ()
Target & GetTarget ()
Thread * GetDefaultThread ()
bool CheckRequirements (CommandReturnObject &result)
Check the command to make sure anything required by this command is available.
void Cleanup ()
Protected Attributes
OptionGroupOptions m_option_group
OptionGroupFormat m_format_options
OptionGroupValueObjectDisplay m_varobj_options
OptionGroupBoolean m_repl_option
CommandOptions m_command_options
uint32_t m_expr_line_count
std::string m_expr_lines
std::string m_fixed_expression
Protected Attributes inherited from lldb_private::CommandObject
CommandInterpreter & m_interpreter
ExecutionContext m_exe_ctx
std::unique_lock< std::recursive_mutex > m_api_locker
std::string m_cmd_name
std::string m_cmd_help_short
std::string m_cmd_help_long
std::string m_cmd_syntax
std::string m_original_command
Flags m_flags
std::vector< CommandArgumentEntry > m_arguments
lldb::CommandOverrideCallback m_deprecated_command_override_callback
lldb_private::CommandOverrideCallbackWithResult m_command_override_callback
void * m_command_override_baton
bool m_is_user_command = false
Protected Attributes inherited from lldb_private::IOHandlerDelegate
Completion m_completion
Additional Inherited Members
Public Types inherited from lldb_private::CommandObject
enum IDType { eBreakpointArgs = 0 , eWatchpointArgs = 1 }
typedef llvm::StringRef ArgumentHelpCallbackFunction()
typedef std::vector< CommandArgumentData > CommandArgumentEntry
typedef std::map< std::string, lldb::CommandObjectSP, std::less<> > CommandMap
Public Types inherited from lldb_private::IOHandlerDelegate
enum class Completion { None , LLDBCommand , Expression }
Static Public Member Functions inherited from lldb_private::CommandObject
static const char * GetArgumentTypeAsCString (const lldb::CommandArgumentType arg_type)
static const char * GetArgumentDescriptionAsCString (const lldb::CommandArgumentType arg_type)
static lldb::CommandArgumentType LookupArgumentName (llvm::StringRef arg_name)
static const ArgumentTableEntry * FindArgumentDataByType (lldb::CommandArgumentType arg_type)
static void GetArgumentHelp (Stream &str, lldb::CommandArgumentType arg_type, CommandInterpreter &interpreter)
static const char * GetArgumentName (lldb::CommandArgumentType arg_type)
static bool IsPairType (ArgumentRepetitionType arg_repeat_type)
static std::optional< ArgumentRepetitionType > ArgRepetitionFromString (llvm::StringRef string)
Detailed Description
Definition at line 22 of file CommandObjectExpression.h.
Constructor & Destructor Documentation
CommandObjectExpression()
CommandObjectExpression::CommandObjectExpression (CommandInterpreter & interpreter)
Definition at line 257 of file CommandObjectExpression.cpp.
References lldb_private::CommandObjectRaw::CommandObjectRaw(), lldb::eFormatDefault, lldb_private::IOHandlerDelegate::Expression, lldb_private::IOHandlerDelegate::IOHandlerDelegate(), LLDB_OPT_SET_1, m_expr_line_count, m_format_options, m_repl_option, and lldb_private::CommandObject::SetHelpLong().
~CommandObjectExpression()
CommandObjectExpression::~CommandObjectExpression () override default
Member Function Documentation
DoExecute()
void CommandObjectExpression::DoExecute (llvm::StringRef command, CommandReturnObject & result) override protected virtual
Implements lldb_private::CommandObjectRaw.
Definition at line 566 of file CommandObjectExpression.cpp.
References lldb_private::CommandObjectExpression::CommandOptions::debug, lldb_private::CommandObjectExpression::CommandOptions::ignore_breakpoints, lldb_private::CommandObjectExpression::CommandOptions::OptionParsingStarting(), lldb_private::EvaluateExpressionOptions::SetIgnoreBreakpoints(), lldb_private::EvaluateExpressionOptions::SetTimeout(), lldb_private::EvaluateExpressionOptions::SetTryAllThreads(), lldb_private::EvaluateExpressionOptions::SetUnwindOnError(), lldb_private::CommandObjectExpression::CommandOptions::timeout, lldb_private::CommandObjectExpression::CommandOptions::try_all_threads, and lldb_private::CommandObjectExpression::CommandOptions::unwind_on_error.
EvaluateExpression()
bool CommandObjectExpression::EvaluateExpression (llvm::StringRef expr, Stream & output_stream, Stream & error_stream, CommandReturnObject & result) protected
Evaluates the given expression.
Parameters
output_stream The stream to which the evaluation result will be printed.
error_stream Contains error messages that should be displayed to the user in case the evaluation fails.
result A CommandReturnObject which status will be set to the appropriate value depending on evaluation success and whether the expression produced any result.
Returns
Returns true iff the expression was successfully evaluated, executed and the result could be printed to the output stream.
Definition at line 385 of file CommandObjectExpression.cpp.
References lldb_private::Expression::eResultTypeAny, and error().
GetMultilineExpression()
void CommandObjectExpression::GetMultilineExpression () protected
Definition at line 519 of file CommandObjectExpression.cpp.
GetOptions()
Options * CommandObjectExpression::GetOptions () override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 314 of file CommandObjectExpression.cpp.
HandleCompletion()
void CommandObjectExpression::HandleCompletion (CompletionRequest & request) override virtual
This default version handles calling option argument completions and then calls HandleArgumentCompletion if the cursor is on an argument, not an option.
Don't override this method, override HandleArgumentCompletion instead unless you have special reasons.
Parameters
[in,out] request The completion request that needs to be answered.
Reimplemented from lldb_private::CommandObject.
Definition at line 316 of file CommandObjectExpression.cpp.
References lldb::eArgTypeExpression, LLDB_OPT_SET_1, LLDB_OPT_SET_2, LLDB_OPT_SET_3, LLDB_OPT_SET_ALL, m_command_options, m_format_options, m_option_group, m_repl_option, m_varobj_options, lldb_private::OptionGroupFormat::OPTION_GROUP_FORMAT, and lldb_private::OptionGroupFormat::OPTION_GROUP_GDB_FMT.
IOHandlerInputComplete()
void CommandObjectExpression::IOHandlerInputComplete (IOHandler & io_handler, std::string & data) override protected virtual
Called when a line or lines have been retrieved.
This function can handle the current line and possibly call IOHandler::SetIsDone(true) when the IO handler is done like when "quit" is entered as a command, of when an empty line is received. It is up to the delegate to determine when a line should cause a IOHandler to exit.
Implements lldb_private::IOHandlerDelegate.
Definition at line 490 of file CommandObjectExpression.cpp.
IOHandlerIsInputComplete()
bool CommandObjectExpression::IOHandlerIsInputComplete (IOHandler & io_handler, StringList & lines) override protected virtual
Called to determine whether typing enter after the last line in lines should end input.
This function will not be called on IOHandler objects that are getting single lines.
Parameters
[in] io_handler The IOHandler that responsible for updating the lines.
[in] lines The current multi-line content. May be altered to provide alternative input when complete.
Returns
Return an boolean to indicate whether input is complete, true indicates that no additional input is necessary, while false indicates that more input is required.
Reimplemented from lldb_private::IOHandlerDelegate.
Definition at line 506 of file CommandObjectExpression.cpp.
Member Data Documentation
m_command_options
CommandOptions lldb_private::CommandObjectExpression::m_command_options protected
Definition at line 100 of file CommandObjectExpression.h.
Referenced by HandleCompletion().
m_expr_line_count
uint32_t lldb_private::CommandObjectExpression::m_expr_line_count protected
Definition at line 101 of file CommandObjectExpression.h.
Referenced by CommandObjectExpression().
m_expr_lines
std::string lldb_private::CommandObjectExpression::m_expr_lines protected
Definition at line 102 of file CommandObjectExpression.h.
m_fixed_expression
std::string lldb_private::CommandObjectExpression::m_fixed_expression protected
Definition at line 103 of file CommandObjectExpression.h.
m_format_options
OptionGroupFormat lldb_private::CommandObjectExpression::m_format_options protected
Definition at line 97 of file CommandObjectExpression.h.
Referenced by CommandObjectExpression(), and HandleCompletion().
m_option_group
OptionGroupOptions lldb_private::CommandObjectExpression::m_option_group protected
Definition at line 96 of file CommandObjectExpression.h.
Referenced by HandleCompletion().
m_repl_option
OptionGroupBoolean lldb_private::CommandObjectExpression::m_repl_option protected
Definition at line 99 of file CommandObjectExpression.h.
Referenced by CommandObjectExpression(), and HandleCompletion().
m_varobj_options
OptionGroupValueObjectDisplay lldb_private::CommandObjectExpression::m_varobj_options protected
Definition at line 98 of file CommandObjectExpression.h.
Referenced by HandleCompletion().
The documentation for this class was generated from the following files:
CommandObjectExpression.h
CommandObjectExpression.cpp