LLDB: RegisterContextCorePOSIX_ppc64le Class Reference
RegisterContextCorePOSIX_ppc64le Class Reference
#include <RegisterContextPOSIXCore_ppc64le.h>
Public Member Functions
RegisterContextCorePOSIX_ppc64le (lldb_private::Thread &thread, lldb_private::RegisterInfoInterface *register_info, const lldb_private::DataExtractor &gpregset, llvm::ArrayRef< lldb_private::CoreNote > notes)
bool ReadRegister (const lldb_private::RegisterInfo *reg_info, lldb_private::RegisterValue &value) override
bool WriteRegister (const lldb_private::RegisterInfo *reg_info, const lldb_private::RegisterValue &value) override
Public Member Functions inherited from RegisterContextPOSIX_ppc64le
RegisterContextPOSIX_ppc64le (lldb_private::Thread &thread, uint32_t concrete_frame_idx, lldb_private::RegisterInfoInterface *register_info)
void InvalidateAllRegisters () override
size_t GetRegisterCount () override
virtual size_t GetGPRSize ()
virtual unsigned GetRegisterSize (unsigned reg)
virtual unsigned GetRegisterOffset (unsigned reg)
const lldb_private::RegisterInfo * GetRegisterInfoAtIndex (size_t reg) override
size_t GetRegisterSetCount () override
const lldb_private::RegisterSet * GetRegisterSet (size_t set) override
const char * GetRegisterName (unsigned reg)
Public Member Functions inherited from lldb_private::RegisterContext
RegisterContext (Thread &thread, uint32_t concrete_frame_idx)
~RegisterContext () override
void InvalidateIfNeeded (bool force)
virtual lldb::ByteOrder GetByteOrder ()
virtual bool ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp)
virtual bool WriteAllRegisterValues (const lldb::DataBufferSP &data_sp)
virtual bool RegisterWriteCausesReconfigure (const llvm::StringRef name)
virtual bool ReconfigureRegisterInfo ()
virtual bool ReadAllRegisterValues (lldb_private::RegisterCheckpoint &reg_checkpoint)
virtual bool WriteAllRegisterValues (const lldb_private::RegisterCheckpoint &reg_checkpoint)
bool CopyFromRegisterContext (lldb::RegisterContextSP context)
virtual uint32_t ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num)
Convert from a given register numbering scheme to the lldb register numbering scheme.
virtual uint32_t NumSupportedHardwareBreakpoints ()
virtual uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual bool ClearHardwareBreakpoint (uint32_t hw_idx)
virtual uint32_t NumSupportedHardwareWatchpoints ()
virtual uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, bool read, bool write)
virtual bool ClearHardwareWatchpoint (uint32_t hw_index)
virtual bool HardwareSingleStep (bool enable)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, uint32_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, uint32_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual Thread & GetThread ()
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num)
uint64_t GetPC (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetThreadPointer (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool GetPCForSymbolication (Address &address)
Get an address suitable for symbolication.
bool SetPC (uint64_t pc)
bool SetPC (Address addr)
uint64_t GetSP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetSP (uint64_t sp)
uint64_t GetFP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetFP (uint64_t fp)
const char * GetRegisterName (uint32_t reg)
uint64_t GetReturnAddress (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetFlags (uint64_t fail_value=0)
uint64_t ReadRegisterAsUnsigned (uint32_t reg, uint64_t fail_value)
uint64_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, uint64_t fail_value)
bool WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
bool WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
bool ConvertBetweenRegisterKinds (lldb::RegisterKind source_rk, uint32_t source_regnum, lldb::RegisterKind target_rk, uint32_t &target_regnum)
lldb::TargetSP CalculateTarget () override
lldb::ProcessSP CalculateProcess () override
lldb::ThreadSP CalculateThread () override
lldb::StackFrameSP CalculateStackFrame () override
void CalculateExecutionContext (ExecutionContext &exe_ctx) override
Reconstruct the object's execution context into sc.
uint32_t GetStopID () const
void SetStopID (uint32_t stop_id)
Public Member Functions inherited from lldb_private::ExecutionContextScope
virtual ~ExecutionContextScope ()=default
Protected Member Functions
size_t GetFPRSize () const
size_t GetVMXSize () const
size_t GetVSXSize () const
Protected Member Functions inherited from RegisterContextPOSIX_ppc64le
virtual bool IsRegisterSetAvailable (size_t set_index)
virtual const lldb_private::RegisterInfo * GetRegisterInfo ()
bool IsGPR (unsigned reg)
bool IsFPR (unsigned reg)
bool IsVMX (unsigned reg)
bool IsVSX (unsigned reg)
Protected Member Functions inherited from lldb_private::RegisterContext
virtual bool BehavesLikeZerothFrame () const
Indicates that this frame is currently executing code, that the PC value is not a return-pc but an actual executing instruction.
Private Attributes
lldb::DataBufferSP m_gpr_buffer
lldb::DataBufferSP m_fpr_buffer
lldb::DataBufferSP m_vmx_buffer
lldb::DataBufferSP m_vsx_buffer
lldb_private::DataExtractor m_gpr
lldb_private::DataExtractor m_fpr
lldb_private::DataExtractor m_vmx
lldb_private::DataExtractor m_vsx
Additional Inherited Members
Protected Attributes inherited from RegisterContextPOSIX_ppc64le
uint64_t m_gpr_ppc64le [k_num_gpr_registers_ppc64le]
uint64_t m_fpr_ppc64le [k_num_fpr_registers_ppc64le]
uint64_t m_vmx_ppc64le [k_num_vmx_registers_ppc64le *2]
uint64_t m_vsx_ppc64le [k_num_vsx_registers_ppc64le *2]
std::unique_ptr< lldb_private::RegisterInfoInterface > m_register_info_up
Protected Attributes inherited from lldb_private::RegisterContext
Thread & m_thread
uint32_t m_concrete_frame_idx
uint32_t m_stop_id
Detailed Description
Definition at line 16 of file RegisterContextPOSIXCore_ppc64le.h.
Constructor & Destructor Documentation
RegisterContextCorePOSIX_ppc64le()
RegisterContextCorePOSIX_ppc64le::RegisterContextCorePOSIX_ppc64le (lldb_private::Thread & thread, lldb_private::RegisterInfoInterface * register_info, const lldb_private::DataExtractor & gpregset, llvm::ArrayRef< lldb_private::CoreNote > notes)
Definition at line 22 of file RegisterContextPOSIXCore_ppc64le.cpp.
References lldb_private::FPR_Desc, lldb_private::DataExtractor::GetByteOrder(), lldb_private::DataExtractor::GetByteSize(), lldb_private::DataExtractor::GetDataStart(), lldb_private::getRegset(), lldb_private::RegisterInfoInterface::GetTargetArchitecture(), lldb_private::ArchSpec::GetTriple(), m_fpr, m_fpr_buffer, m_gpr, m_gpr_buffer, m_vmx, m_vmx_buffer, m_vsx, m_vsx_buffer, lldb_private::PPC_VMX_Desc, lldb_private::PPC_VSX_Desc, and RegisterContextPOSIX_ppc64le::RegisterContextPOSIX_ppc64le().
Member Function Documentation
GetFPRSize()
size_t RegisterContextCorePOSIX_ppc64le::GetFPRSize () const protected
Definition at line 51 of file RegisterContextPOSIXCore_ppc64le.cpp.
References k_num_fpr_registers_ppc64le.
Referenced by ReadRegister().
GetVMXSize()
size_t RegisterContextCorePOSIX_ppc64le::GetVMXSize () const protected
Definition at line 55 of file RegisterContextPOSIXCore_ppc64le.cpp.
References k_num_vmx_registers_ppc64le.
Referenced by ReadRegister().
GetVSXSize()
size_t RegisterContextCorePOSIX_ppc64le::GetVSXSize () const protected
Definition at line 60 of file RegisterContextPOSIXCore_ppc64le.cpp.
References k_num_vsx_registers_ppc64le.
Referenced by ReadRegister().
ReadRegister()
bool RegisterContextCorePOSIX_ppc64le::ReadRegister (const lldb_private::RegisterInfo * reg_info, lldb_private::RegisterValue & value) override virtual
Implements lldb_private::RegisterContext.
Definition at line 64 of file RegisterContextPOSIXCore_ppc64le.cpp.
References lldb_private::RegisterInfo::byte_offset, lldb_private::RegisterInfo::byte_size, lldb::eRegisterKindLLDB, GetFPRSize(), RegisterContextPOSIX_ppc64le::GetGPRSize(), GetVMXSize(), GetVSXSize(), RegisterContextPOSIX_ppc64le::IsFPR(), RegisterContextPOSIX_ppc64le::IsVMX(), RegisterContextPOSIX_ppc64le::IsVSX(), lldb_private::RegisterInfo::kinds, m_fpr, m_gpr, m_vmx, m_vsx, and lldb_private::RegisterValue::SetBytes().
WriteRegister()
bool RegisterContextCorePOSIX_ppc64le::WriteRegister (const lldb_private::RegisterInfo * reg_info, const lldb_private::RegisterValue & value) override virtual
Implements lldb_private::RegisterContext.
Definition at line 130 of file RegisterContextPOSIXCore_ppc64le.cpp.
Member Data Documentation
m_fpr
lldb_private::DataExtractor RegisterContextCorePOSIX_ppc64le::m_fpr private
Definition at line 43 of file RegisterContextPOSIXCore_ppc64le.h.
Referenced by ReadRegister(), and RegisterContextCorePOSIX_ppc64le().
m_fpr_buffer
lldb::DataBufferSP RegisterContextCorePOSIX_ppc64le::m_fpr_buffer private
Definition at line 39 of file RegisterContextPOSIXCore_ppc64le.h.
Referenced by RegisterContextCorePOSIX_ppc64le().
m_gpr
lldb_private::DataExtractor RegisterContextCorePOSIX_ppc64le::m_gpr private
Definition at line 42 of file RegisterContextPOSIXCore_ppc64le.h.
Referenced by ReadRegister(), and RegisterContextCorePOSIX_ppc64le().
m_gpr_buffer
lldb::DataBufferSP RegisterContextCorePOSIX_ppc64le::m_gpr_buffer private
Definition at line 38 of file RegisterContextPOSIXCore_ppc64le.h.
Referenced by RegisterContextCorePOSIX_ppc64le().
m_vmx
lldb_private::DataExtractor RegisterContextCorePOSIX_ppc64le::m_vmx private
Definition at line 44 of file RegisterContextPOSIXCore_ppc64le.h.
Referenced by ReadRegister(), and RegisterContextCorePOSIX_ppc64le().
m_vmx_buffer
lldb::DataBufferSP RegisterContextCorePOSIX_ppc64le::m_vmx_buffer private
Definition at line 40 of file RegisterContextPOSIXCore_ppc64le.h.
Referenced by RegisterContextCorePOSIX_ppc64le().
m_vsx
lldb_private::DataExtractor RegisterContextCorePOSIX_ppc64le::m_vsx private
Definition at line 45 of file RegisterContextPOSIXCore_ppc64le.h.
Referenced by ReadRegister(), and RegisterContextCorePOSIX_ppc64le().
m_vsx_buffer
lldb::DataBufferSP RegisterContextCorePOSIX_ppc64le::m_vsx_buffer private
Definition at line 41 of file RegisterContextPOSIXCore_ppc64le.h.
Referenced by RegisterContextCorePOSIX_ppc64le().
The documentation for this class was generated from the following files:
RegisterContextPOSIXCore_ppc64le.h
RegisterContextPOSIXCore_ppc64le.cpp