LLDB: lldb_private::LanguageRuntime Class Reference
lldb_private::LanguageRuntime Class Reference abstract
#include <LanguageRuntime.h>
Classes
struct VTableInfo
Public Member Functions
virtual lldb::LanguageType GetLanguageType () const =0
virtual LanguageRuntime * GetPreferredLanguageRuntime (ValueObject &in_value)
Return the preferred language runtime instance, which in most cases will be the current instance.
virtual llvm::Error GetObjectDescription (Stream &str, ValueObject &object)=0
virtual llvm::Error GetObjectDescription (Stream &str, Value &value, ExecutionContextScope *exe_scope)=0
virtual llvm::Expected< VTableInfo > GetVTableInfo (ValueObject &in_value, bool check_type)
Get the vtable information for a given value.
virtual bool GetDynamicTypeAndAddress (ValueObject &in_value, lldb::DynamicValueType use_dynamic, TypeAndOrName &class_type_or_name, Address &address, Value::ValueType &value_type, llvm::ArrayRef< uint8_t > &local_buffer)=0
This call should return true if it could set the name and/or the type Sets address to the address of the dynamic type if value_type is set to a file or load address.
virtual CompilerType GetConcreteType (ExecutionContextScope *exe_scope, ConstString abstract_type_name)
virtual bool CouldHaveDynamicValue (ValueObject &in_value)=0
virtual TypeAndOrName FixUpDynamicType (const TypeAndOrName &type_and_or_name, ValueObject &static_value)=0
virtual void SetExceptionBreakpoints ()
virtual void ClearExceptionBreakpoints ()
virtual bool ExceptionBreakpointsAreSet ()
virtual bool ExceptionBreakpointsExplainStop (lldb::StopInfoSP stop_reason)
virtual lldb::ValueObjectSP GetExceptionObjectForThread (lldb::ThreadSP thread_sp)
virtual lldb::ThreadSP GetBacktraceThreadFromException (lldb::ValueObjectSP thread_sp)
virtual DeclVendor * GetDeclVendor ()
virtual lldb::BreakpointResolverSP CreateExceptionResolver (const lldb::BreakpointSP &bkpt, bool catch_bp, bool throw_bp)=0
virtual lldb::SearchFilterSP CreateExceptionSearchFilter ()
virtual std::optional< uint64_t > GetTypeBitSize (const CompilerType &compiler_type)
virtual void SymbolsDidLoad (const ModuleList &module_list)
virtual lldb::ThreadPlanSP GetStepThroughTrampolinePlan (Thread &thread, bool stop_others)=0
virtual bool IsAllowedRuntimeValue (ConstString name)
Identify whether a name is a runtime value that should not be hidden by from the user interface.
virtual std::optional< CompilerType > GetRuntimeType (CompilerType base_type)
void ModulesDidLoad (const ModuleList &module_list) override
Called when modules have been loaded in the process.
virtual bool GetIRPasses (LLVMUserExpression::IRPasses &custom_passes)
virtual bool IsSymbolARuntimeThunk (const Symbol &symbol)
virtual lldb::addr_t LookupRuntimeSymbol (ConstString name)
virtual bool isA (const void *ClassID) const
virtual StructuredData::ObjectSP GetLanguageSpecificData (SymbolContext sc)
Language runtime plugins can use this API to report language-specific runtime information about this compile unit, such as additional language version details or feature flags.
Public Member Functions inherited from lldb_private::Runtime
Runtime (Process *process)
virtual ~Runtime ()=default
Runtime (const Runtime &)=delete
const Runtime & operator= (const Runtime &)=delete
Process * GetProcess ()
Target & GetTargetRef ()
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
virtual llvm::StringRef GetPluginName ()=0
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static LanguageRuntime * FindPlugin (Process *process, lldb::LanguageType language)
static void InitializeCommands (CommandObject *parent)
static lldb::BreakpointSP CreateExceptionBreakpoint (Target &target, lldb::LanguageType language, bool catch_bp, bool throw_bp, bool is_internal=false)
static lldb::BreakpointPreconditionSP GetExceptionPrecondition (lldb::LanguageType language, bool throw_bp)
static lldb::UnwindPlanSP GetRuntimeUnwindPlan (lldb_private::Thread &thread, lldb_private::RegisterContext *regctx, bool &behaves_like_zeroth_frame)
A language runtime may be able to provide a special UnwindPlan for the frame represented by the register contents regctx when that frame is not following the normal ABI conventions.
Static Public Attributes
static char ID = 0
Protected Member Functions
virtual lldb::UnwindPlanSP GetRuntimeUnwindPlan (lldb::ProcessSP process_sp, lldb_private::RegisterContext *regctx, bool &behaves_like_zeroth_frame)
LanguageRuntime (Process *process)
Additional Inherited Members
Protected Attributes inherited from lldb_private::Runtime
Process * m_process
Detailed Description
Definition at line 61 of file LanguageRuntime.h.
Constructor & Destructor Documentation
LanguageRuntime()
LanguageRuntime::LanguageRuntime (Process * process) protected
Definition at line 216 of file LanguageRuntime.cpp.
References lldb_private::Runtime::Runtime().
Referenced by lldb_private::CPPLanguageRuntime::classof(), lldb_private::ObjCLanguageRuntime::classof(), lldb_private::CPPLanguageRuntime::CPPLanguageRuntime(), FindPlugin(), GetPreferredLanguageRuntime(), GetRuntimeUnwindPlan(), and lldb_private::ObjCLanguageRuntime::ObjCLanguageRuntime().
Member Function Documentation
ClearExceptionBreakpoints()
virtual void lldb_private::LanguageRuntime::ClearExceptionBreakpoints () inline virtual
Reimplemented in lldb_private::AppleObjCRuntime, and lldb_private::ItaniumABILanguageRuntime.
Definition at line 141 of file LanguageRuntime.h.
CouldHaveDynamicValue()
virtual bool lldb_private::LanguageRuntime::CouldHaveDynamicValue (ValueObject & in_value) pure virtual
Implemented in lldb_private::AppleObjCRuntime, lldb_private::GNUstepObjCRuntime, and lldb_private::ItaniumABILanguageRuntime.
Referenced by lldb_private::Process::IsPossibleDynamicValue().
CreateExceptionBreakpoint()
BreakpointSP LanguageRuntime::CreateExceptionBreakpoint (Target & target, lldb::LanguageType language, bool catch_bp, bool throw_bp, bool is_internal = false) static
Definition at line 238 of file LanguageRuntime.cpp.
References lldb_private::Target::CreateBreakpoint(), and GetExceptionPrecondition().
Referenced by lldb_private::Target::CreateExceptionBreakpoint(), and lldb_private::AppleObjCRuntime::SetExceptionBreakpoints().
CreateExceptionResolver()
virtual lldb::BreakpointResolverSP lldb_private::LanguageRuntime::CreateExceptionResolver (const lldb::BreakpointSP & bkpt, bool catch_bp, bool throw_bp) pure virtual
Implemented in lldb_private::AppleObjCRuntimeV1, lldb_private::AppleObjCRuntimeV2, lldb_private::GNUstepObjCRuntime, and lldb_private::ItaniumABILanguageRuntime.
CreateExceptionSearchFilter()
virtual lldb::SearchFilterSP lldb_private::LanguageRuntime::CreateExceptionSearchFilter () inline virtual
Reimplemented in lldb_private::AppleObjCRuntime, and lldb_private::ItaniumABILanguageRuntime.
Definition at line 173 of file LanguageRuntime.h.
References lldb_private::Runtime::m_process.
ExceptionBreakpointsAreSet()
virtual bool lldb_private::LanguageRuntime::ExceptionBreakpointsAreSet () inline virtual
Reimplemented in lldb_private::AppleObjCRuntime, and lldb_private::ItaniumABILanguageRuntime.
Definition at line 143 of file LanguageRuntime.h.
ExceptionBreakpointsExplainStop()
virtual bool lldb_private::LanguageRuntime::ExceptionBreakpointsExplainStop (lldb::StopInfoSP stop_reason) inline virtual
Reimplemented in lldb_private::AppleObjCRuntime, and lldb_private::ItaniumABILanguageRuntime.
Definition at line 145 of file LanguageRuntime.h.
FindPlugin()
LanguageRuntime * LanguageRuntime::FindPlugin (Process * process, lldb::LanguageType language) static
Definition at line 202 of file LanguageRuntime.cpp.
References lldb_private::PluginManager::GetLanguageRuntimeCreateCallbackAtIndex(), and LanguageRuntime().
Referenced by lldb_private::Process::GetLanguageRuntime().
FixUpDynamicType()
virtual TypeAndOrName lldb_private::LanguageRuntime::FixUpDynamicType (const TypeAndOrName & type_and_or_name, ValueObject & static_value) pure virtual
Implemented in lldb_private::AppleObjCRuntime, lldb_private::GNUstepObjCRuntime, and lldb_private::ItaniumABILanguageRuntime.
Referenced by lldb_private::ValueObjectDynamicValue::UpdateValue().
GetBacktraceThreadFromException()
virtual lldb::ThreadSP lldb_private::LanguageRuntime::GetBacktraceThreadFromException (lldb::ValueObjectSP thread_sp) inline virtual
Reimplemented in lldb_private::AppleObjCRuntime.
Definition at line 162 of file LanguageRuntime.h.
GetConcreteType()
virtual CompilerType lldb_private::LanguageRuntime::GetConcreteType (ExecutionContextScope * exe_scope, ConstString abstract_type_name) inline virtual
Definition at line 122 of file LanguageRuntime.h.
GetDeclVendor()
virtual DeclVendor * lldb_private::LanguageRuntime::GetDeclVendor () inline virtual
Reimplemented in lldb_private::AppleObjCRuntimeV1, and lldb_private::AppleObjCRuntimeV2.
Definition at line 167 of file LanguageRuntime.h.
Referenced by lldb_private::ClangASTSource::FindDeclInObjCRuntime(), lldb_private::ClangASTSource::FindObjCMethodDecls(), lldb_private::ClangASTSource::FindObjCPropertyAndIvarDecls(), and lldb_private::ObjCLanguageRuntime::LookupInRuntime().
GetDynamicTypeAndAddress()
virtual bool lldb_private::LanguageRuntime::GetDynamicTypeAndAddress (ValueObject & in_value, lldb::DynamicValueType use_dynamic, TypeAndOrName & class_type_or_name, Address & address, Value::ValueType & value_type, llvm::ArrayRef< uint8_t > & local_buffer) pure virtual
This call should return true if it could set the name and/or the type Sets address to the address of the dynamic type if value_type is set to a file or load address.
Sets local_buffer to a buffer containing the data of the dynamic type if value_type is set to a host address. Callers should copy local_buffer over into their own buffer if they want to keep the data alive.
Implemented in lldb_private::AppleObjCRuntime, lldb_private::AppleObjCRuntimeV1, lldb_private::AppleObjCRuntimeV2, lldb_private::GNUstepObjCRuntime, and lldb_private::ItaniumABILanguageRuntime.
Referenced by lldb_private::ValueObjectDynamicValue::UpdateValue().
GetExceptionObjectForThread()
virtual lldb::ValueObjectSP lldb_private::LanguageRuntime::GetExceptionObjectForThread (lldb::ThreadSP thread_sp) inline virtual
Reimplemented in lldb_private::AppleObjCRuntime, and lldb_private::ItaniumABILanguageRuntime.
Definition at line 157 of file LanguageRuntime.h.
GetExceptionPrecondition()
BreakpointPreconditionSP LanguageRuntime::GetExceptionPrecondition (lldb::LanguageType language, bool throw_bp) static
Definition at line 219 of file LanguageRuntime.cpp.
References lldb_private::PluginManager::GetLanguageRuntimeCreateCallbackAtIndex(), and lldb_private::PluginManager::GetLanguageRuntimeGetExceptionPreconditionAtIndex().
Referenced by CreateExceptionBreakpoint().
GetIRPasses()
virtual bool lldb_private::LanguageRuntime::GetIRPasses (LLVMUserExpression::IRPasses & custom_passes) inline virtual
Definition at line 200 of file LanguageRuntime.h.
GetLanguageSpecificData()
StructuredData::ObjectSP LanguageRuntime::GetLanguageSpecificData (SymbolContext sc) virtual
Language runtime plugins can use this API to report language-specific runtime information about this compile unit, such as additional language version details or feature flags.
Reimplemented in lldb_private::AppleObjCRuntimeV2.
Definition at line 281 of file LanguageRuntime.cpp.
GetLanguageType()
virtual lldb::LanguageType lldb_private::LanguageRuntime::GetLanguageType () const pure virtual
Implemented in lldb_private::CPPLanguageRuntime, and lldb_private::ObjCLanguageRuntime.
Referenced by lldb_private::Process::GetLanguageRuntime().
GetObjectDescription() [1/2]
virtual llvm::Error lldb_private::LanguageRuntime::GetObjectDescription (Stream & str, Value & value, ExecutionContextScope * exe_scope) pure virtual
Implemented in lldb_private::AppleObjCRuntime, lldb_private::CPPLanguageRuntime, and lldb_private::GNUstepObjCRuntime.
GetObjectDescription() [2/2]
virtual llvm::Error lldb_private::LanguageRuntime::GetObjectDescription (Stream & str, ValueObject & object) pure virtual
Implemented in lldb_private::AppleObjCRuntime, lldb_private::CPPLanguageRuntime, and lldb_private::GNUstepObjCRuntime.
GetPreferredLanguageRuntime()
virtual LanguageRuntime * lldb_private::LanguageRuntime::GetPreferredLanguageRuntime (ValueObject & in_value) inline virtual
Return the preferred language runtime instance, which in most cases will be the current instance.
Reimplemented in lldb_private::AppleObjCRuntimeV2.
Definition at line 72 of file LanguageRuntime.h.
References LanguageRuntime().
Referenced by lldb_private::ValueObjectDynamicValue::UpdateValue().
GetRuntimeType()
virtual std::optional< CompilerType > lldb_private::LanguageRuntime::GetRuntimeType (CompilerType base_type) inline virtual
Reimplemented in lldb_private::ObjCLanguageRuntime.
Definition at line 191 of file LanguageRuntime.h.
GetRuntimeUnwindPlan() [1/2]
virtual lldb::UnwindPlanSP lldb_private::LanguageRuntime::GetRuntimeUnwindPlan (lldb::ProcessSP process_sp, lldb_private::RegisterContext * regctx, bool & behaves_like_zeroth_frame) inline protected virtual
Definition at line 260 of file LanguageRuntime.h.
GetRuntimeUnwindPlan() [2/2]
UnwindPlanSP LanguageRuntime::GetRuntimeUnwindPlan (lldb_private::Thread & thread, lldb_private::RegisterContext * regctx, bool & behaves_like_zeroth_frame) static
A language runtime may be able to provide a special UnwindPlan for the frame represented by the register contents regctx when that frame is not following the normal ABI conventions.
Instead of using the normal UnwindPlan for the function, we will use this special UnwindPlan for this one backtrace. One example of this would be a language that has asynchronous functions, functions that may not be currently-executing, while waiting on other asynchronous calls they made, but are part of a logical backtrace that we want to show the developer because that's how they think of the program flow.
Parameters
[in] thread The thread that the unwind is happening on.
[in] regctx The RegisterContext for the frame we need to create an UnwindPlan. We don't yet have a StackFrame when we're selecting the UnwindPlan.
[out] behaves_like_zeroth_frame With normal ABI calls, all stack frames except the zeroth frame need to have the return-pc value backed up by 1 for symbolication purposes. For these LanguageRuntime unwind plans, they may not follow normal ABI calling conventions and the return pc may need to be symbolicated as-is.
Returns
Returns an UnwindPlan to find the caller frame if it should be used, instead of the UnwindPlan that would normally be used for this function.
Definition at line 262 of file LanguageRuntime.cpp.
References lldb_private::Language::GetSupportedLanguages(), and LanguageRuntime().
Referenced by lldb_private::RegisterContextUnwind::InitializeNonZerothFrame(), and lldb_private::RegisterContextUnwind::InitializeZerothFrame().
GetStepThroughTrampolinePlan()
virtual lldb::ThreadPlanSP lldb_private::LanguageRuntime::GetStepThroughTrampolinePlan (Thread & thread, bool stop_others) pure virtual
Implemented in lldb_private::AppleObjCRuntime, lldb_private::CPPLanguageRuntime, and lldb_private::GNUstepObjCRuntime.
Referenced by lldb_private::AppleThreadPlanStepThroughDirectDispatch::ShouldStop().
GetTypeBitSize()
virtual std::optional< uint64_t > lldb_private::LanguageRuntime::GetTypeBitSize (const CompilerType & compiler_type) inline virtual
Reimplemented in lldb_private::ObjCLanguageRuntime.
Definition at line 178 of file LanguageRuntime.h.
GetVTableInfo()
virtual llvm::Expected< VTableInfo > lldb_private::LanguageRuntime::GetVTableInfo (ValueObject & in_value, bool check_type) inline virtual
Get the vtable information for a given value.
Parameters
[in] in_value The value object to try and extract the VTableInfo from.
[in] check_type If true, the compiler type of in_value will be checked to see if it is an instance to, or pointer or reference to a class or struct that has a vtable. If the type doesn't meet the requirements, an error will be returned explaining why the type isn't suitable.
Returns
An error if anything goes wrong while trying to extract the vtable or if check_type is true and the type doesn't have a vtable.
Reimplemented in lldb_private::ItaniumABILanguageRuntime.
Definition at line 101 of file LanguageRuntime.h.
Referenced by lldb_private::ValueObjectVTable::UpdateValue().
InitializeCommands()
void LanguageRuntime::InitializeCommands (CommandObject * parent) static
Definition at line 285 of file LanguageRuntime.cpp.
References lldb_private::CommandObject::GetCommandInterpreter(), lldb_private::PluginManager::GetLanguageRuntimeCreateCallbackAtIndex(), lldb_private::PluginManager::GetLanguageRuntimeGetCommandObjectAtIndex(), lldb_private::CommandObject::IsMultiwordObject(), and lldb_private::CommandObject::LoadSubCommand().
Referenced by lldb_private::CommandObjectLanguage::CommandObjectLanguage().
isA()
virtual bool lldb_private::LanguageRuntime::isA (const void * ClassID) const inline virtual
Reimplemented in lldb_private::AppleObjCRuntime, lldb_private::AppleObjCRuntimeV1, lldb_private::AppleObjCRuntimeV2, lldb_private::CPPLanguageRuntime, lldb_private::GNUstepObjCRuntime, lldb_private::ItaniumABILanguageRuntime, and lldb_private::ObjCLanguageRuntime.
Definition at line 213 of file LanguageRuntime.h.
References ID.
Referenced by lldb_private::AppleObjCRuntime::classof(), lldb_private::AppleObjCRuntimeV1::classof(), lldb_private::AppleObjCRuntimeV2::classof(), lldb_private::CPPLanguageRuntime::classof(), lldb_private::GNUstepObjCRuntime::classof(), lldb_private::ItaniumABILanguageRuntime::classof(), lldb_private::ObjCLanguageRuntime::classof(), lldb_private::CPPLanguageRuntime::isA(), and lldb_private::ObjCLanguageRuntime::isA().
IsAllowedRuntimeValue()
virtual bool lldb_private::LanguageRuntime::IsAllowedRuntimeValue (ConstString name) inline virtual
Identify whether a name is a runtime value that should not be hidden by from the user interface.
Reimplemented in lldb_private::CPPLanguageRuntime, and lldb_private::ObjCLanguageRuntime.
Definition at line 189 of file LanguageRuntime.h.
IsSymbolARuntimeThunk()
virtual bool lldb_private::LanguageRuntime::IsSymbolARuntimeThunk (const Symbol & symbol) inline virtual
Reimplemented in lldb_private::CPPLanguageRuntime.
Definition at line 204 of file LanguageRuntime.h.
LookupRuntimeSymbol()
virtual lldb::addr_t lldb_private::LanguageRuntime::LookupRuntimeSymbol (ConstString name) inline virtual
Reimplemented in lldb_private::AppleObjCRuntimeV2.
Definition at line 209 of file LanguageRuntime.h.
References LLDB_INVALID_ADDRESS.
Referenced by lldb_private::ClangExpressionDeclMap::GetSymbolAddress().
ModulesDidLoad()
void lldb_private::LanguageRuntime::ModulesDidLoad (const ModuleList & module_list) inline override virtual
Called when modules have been loaded in the process.
Implements lldb_private::Runtime.
Definition at line 195 of file LanguageRuntime.h.
SetExceptionBreakpoints()
virtual void lldb_private::LanguageRuntime::SetExceptionBreakpoints () inline virtual
Reimplemented in lldb_private::AppleObjCRuntime, and lldb_private::ItaniumABILanguageRuntime.
Definition at line 139 of file LanguageRuntime.h.
SymbolsDidLoad()
virtual void lldb_private::LanguageRuntime::SymbolsDidLoad (const ModuleList & module_list) inline virtual
Reimplemented in lldb_private::ObjCLanguageRuntime.
Definition at line 182 of file LanguageRuntime.h.
Member Data Documentation
ID
char LanguageRuntime::ID = 0 static
Definition at line 214 of file LanguageRuntime.h.
Referenced by isA().
The documentation for this class was generated from the following files:
LanguageRuntime.h
LanguageRuntime.cpp