LLDB: lldb_private::SBCommandReturnObjectImpl Class Reference
lldb_private::SBCommandReturnObjectImpl Class Reference
Public Member Functions
SBCommandReturnObjectImpl ()
SBCommandReturnObjectImpl (CommandReturnObject &ref)
SBCommandReturnObjectImpl (const SBCommandReturnObjectImpl &rhs)
SBCommandReturnObjectImpl & operator= (const SBCommandReturnObjectImpl &rhs)
~SBCommandReturnObjectImpl ()
CommandReturnObject & operator* () const
Private Attributes
CommandReturnObject * m_ptr
bool m_owned = true
Detailed Description
Definition at line 28 of file SBCommandReturnObject.cpp.
Constructor & Destructor Documentation
SBCommandReturnObjectImpl() [1/3]
lldb_private::SBCommandReturnObjectImpl::SBCommandReturnObjectImpl () inline
Definition at line 30 of file SBCommandReturnObject.cpp.
References m_ptr.
Referenced by operator=(), and SBCommandReturnObjectImpl().
SBCommandReturnObjectImpl() [2/3]
lldb_private::SBCommandReturnObjectImpl::SBCommandReturnObjectImpl (CommandReturnObject & ref) inline
Definition at line 31 of file SBCommandReturnObject.cpp.
References m_owned, and m_ptr.
SBCommandReturnObjectImpl() [3/3]
lldb_private::SBCommandReturnObjectImpl::SBCommandReturnObjectImpl (const SBCommandReturnObjectImpl & rhs) inline
Definition at line 33 of file SBCommandReturnObject.cpp.
References m_owned, m_ptr, and SBCommandReturnObjectImpl().
~SBCommandReturnObjectImpl()
lldb_private::SBCommandReturnObjectImpl::~SBCommandReturnObjectImpl () inline
Definition at line 41 of file SBCommandReturnObject.cpp.
References m_owned, and m_ptr.
Member Function Documentation
operator*()
CommandReturnObject & lldb_private::SBCommandReturnObjectImpl::operator* () const inline
Definition at line 46 of file SBCommandReturnObject.cpp.
References m_ptr.
operator=()
SBCommandReturnObjectImpl & lldb_private::SBCommandReturnObjectImpl::operator= (const SBCommandReturnObjectImpl & rhs) inline
Definition at line 35 of file SBCommandReturnObject.cpp.
References SBCommandReturnObjectImpl().
Member Data Documentation
m_owned
bool lldb_private::SBCommandReturnObjectImpl::m_owned = true private
Definition at line 50 of file SBCommandReturnObject.cpp.
Referenced by SBCommandReturnObjectImpl(), SBCommandReturnObjectImpl(), and ~SBCommandReturnObjectImpl().
m_ptr
CommandReturnObject* lldb_private::SBCommandReturnObjectImpl::m_ptr private
Definition at line 49 of file SBCommandReturnObject.cpp.
Referenced by operator*(), SBCommandReturnObjectImpl(), SBCommandReturnObjectImpl(), SBCommandReturnObjectImpl(), and ~SBCommandReturnObjectImpl().
The documentation for this class was generated from the following file:
SBCommandReturnObject.cpp