LLDB: lldb_private::HTRBlock Class Reference
lldb_private::HTRBlock Class Reference
Block structure representing a sequence of trace "units" (ie instructions).
#include <TraceHTR.h>
Public Member Functions
HTRBlock (size_t offset, size_t size, HTRBlockMetadata metadata)
Constructor for a block of an HTR layer.
size_t GetOffset () const
Get the offset of the start of this block in the previous layer.
size_t GetSize () const
Get the number of blocks/instructions that make up this block in the previous layer.
HTRBlockMetadata const & GetMetadata () const
Get the metadata for this block.
Private Attributes
size_t m_offset
Offset in the previous layer.
size_t m_size
Number of blocks/instructions that make up this block in the previous layer.
HTRBlockMetadata m_metadata
General metadata for this block.
Detailed Description
Block structure representing a sequence of trace "units" (ie instructions).
Sequences of blocks are merged to create a new, single block See lldb/docs/htr.rst for comprehensive HTR documentation
Definition at line 91 of file TraceHTR.h.
Constructor & Destructor Documentation
HTRBlock()
lldb_private::HTRBlock::HTRBlock (size_t offset, size_t size, HTRBlockMetadata metadata) inline
Constructor for a block of an HTR layer.
Parameters
[in] offset The offset of the start of this block in the previous layer.
[in] size Number of blocks/instructions that make up this block in the previous layer.
[in] metadata General metadata for this block.
Definition at line 104 of file TraceHTR.h.
References m_metadata, m_offset, and m_size.
Member Function Documentation
GetMetadata()
HTRBlockMetadata const & HTRBlock::GetMetadata () const
Get the metadata for this block.
Returns
The metadata of the block.
Definition at line 54 of file TraceHTR.cpp.
References m_metadata.
Referenced by lldb_private::HTRBlockLayer::GetMetadataByIndex(), lldb_private::toJSON(), and lldb_private::toJSON().
GetOffset()
size_t HTRBlock::GetOffset () const
Get the offset of the start of this block in the previous layer.
Returns
The offset of the block.
Definition at line 50 of file TraceHTR.cpp.
References m_offset.
GetSize()
size_t HTRBlock::GetSize () const
Get the number of blocks/instructions that make up this block in the previous layer.
Returns
The size of the block.
Definition at line 52 of file TraceHTR.cpp.
References m_size.
Member Data Documentation
m_metadata
HTRBlockMetadata lldb_private::HTRBlock::m_metadata private
General metadata for this block.
Definition at line 133 of file TraceHTR.h.
Referenced by GetMetadata(), and HTRBlock().
m_offset
size_t lldb_private::HTRBlock::m_offset private
Offset in the previous layer.
Definition at line 128 of file TraceHTR.h.
Referenced by GetOffset(), and HTRBlock().
m_size
size_t lldb_private::HTRBlock::m_size private
Number of blocks/instructions that make up this block in the previous layer.
Definition at line 131 of file TraceHTR.h.
Referenced by GetSize(), and HTRBlock().
The documentation for this class was generated from the following files:
TraceHTR.h
TraceHTR.cpp