LLDB: lldb_private::formatters::NSDictionary_Additionals::AdditionalFormatterMatching::Prefix Class Reference
lldb_private::formatters::NSDictionary_Additionals::AdditionalFormatterMatching::Prefix Class Reference
#include <NSDictionary.h>
Public Member Functions
Prefix (ConstString p)
~Prefix () override=default
bool Match (ConstString class_name) override
Public Member Functions inherited from lldb_private::formatters::NSDictionary_Additionals::AdditionalFormatterMatching::Matcher
virtual ~Matcher ()=default
Private Attributes
ConstString m_prefix
Additional Inherited Members
Public Types inherited from lldb_private::formatters::NSDictionary_Additionals::AdditionalFormatterMatching::Matcher
typedef std::unique_ptr< Matcher > UP
Detailed Description
Definition at line 50 of file NSDictionary.h.
Constructor & Destructor Documentation
Prefix()
NSDictionary_Additionals::AdditionalFormatterMatching::Prefix::Prefix (ConstString p)
Definition at line 34 of file NSDictionary.cpp.
References m_prefix.
~Prefix()
lldb_private::formatters::NSDictionary_Additionals::AdditionalFormatterMatching::Prefix::~Prefix () override default
References Match().
Member Function Documentation
Match()
bool NSDictionary_Additionals::AdditionalFormatterMatching::Prefix::Match (ConstString class_name) override virtual
Implements lldb_private::formatters::NSDictionary_Additionals::AdditionalFormatterMatching::Matcher.
Definition at line 38 of file NSDictionary.cpp.
References lldb_private::ConstString::GetStringRef(), and m_prefix.
Referenced by ~Prefix().
Member Data Documentation
m_prefix
ConstString lldb_private::formatters::NSDictionary_Additionals::AdditionalFormatterMatching::Prefix::m_prefix private
Definition at line 57 of file NSDictionary.h.
Referenced by Match(), and Prefix().
The documentation for this class was generated from the following files:
NSDictionary.h
NSDictionary.cpp