LLDB: lldb_private::NativeThreadProtocol Class Reference
lldb_private::NativeThreadProtocol Class Reference abstract
#include <NativeThreadProtocol.h>
Public Member Functions
NativeThreadProtocol (NativeProcessProtocol &process, lldb::tid_t tid)
virtual ~NativeThreadProtocol ()=default
virtual std::string GetName ()=0
virtual lldb::StateType GetState ()=0
virtual NativeRegisterContext & GetRegisterContext ()=0
virtual bool GetStopReason (ThreadStopInfo &stop_info, std::string &description)=0
lldb::tid_t GetID () const
NativeProcessProtocol & GetProcess ()
virtual Status SetWatchpoint (lldb::addr_t addr, size_t size, uint32_t watch_flags, bool hardware)=0
virtual Status RemoveWatchpoint (lldb::addr_t addr)=0
virtual Status SetHardwareBreakpoint (lldb::addr_t addr, size_t size)=0
virtual Status RemoveHardwareBreakpoint (lldb::addr_t addr)=0
virtual llvm::Expected< std::unique_ptr< llvm::MemoryBuffer > > GetSiginfo () const
Protected Attributes
NativeProcessProtocol & m_process
lldb::tid_t m_tid
Detailed Description
Definition at line 24 of file NativeThreadProtocol.h.
Constructor & Destructor Documentation
NativeThreadProtocol()
NativeThreadProtocol::NativeThreadProtocol (NativeProcessProtocol & process, lldb::tid_t tid)
Definition at line 17 of file NativeThreadProtocol.cpp.
References m_process, and m_tid.
Referenced by lldb_private::process_aix::NativeThreadAIX::NativeThreadAIX(), lldb_private::process_freebsd::NativeThreadFreeBSD::NativeThreadFreeBSD(), lldb_private::process_linux::NativeThreadLinux::NativeThreadLinux(), lldb_private::process_netbsd::NativeThreadNetBSD::NativeThreadNetBSD(), and lldb_private::NativeThreadWindows::NativeThreadWindows().
~NativeThreadProtocol()
virtual lldb_private::NativeThreadProtocol::~NativeThreadProtocol () virtual default
Member Function Documentation
GetID()
lldb::tid_t lldb_private::NativeThreadProtocol::GetID () const inline
Definition at line 39 of file NativeThreadProtocol.h.
References m_tid.
Referenced by lldb_private::process_freebsd::NativeThreadFreeBSD::GetName(), lldb_private::process_linux::NativeThreadLinux::GetName(), lldb_private::process_freebsd::NativeThreadFreeBSD::GetSiginfo(), lldb_private::process_linux::NativeThreadLinux::GetSiginfo(), lldb_private::NativeThreadWindows::GetStopReason(), lldb_private::process_freebsd::NativeThreadFreeBSD::GetStopReason(), lldb_private::process_linux::NativeThreadLinux::GetStopReason(), lldb_private::process_netbsd::NativeThreadNetBSD::GetStopReason(), lldb_private::process_linux::NativeProcessLinux::Interrupt(), lldb_private::process_linux::NativeThreadLinux::MaybeLogStateChange(), lldb_private::process_linux::NativeProcessLinux::MonitorClone(), lldb_private::process_linux::NativeThreadLinux::RequestStop(), lldb_private::process_freebsd::NativeThreadFreeBSD::Resume(), lldb_private::process_linux::NativeThreadLinux::Resume(), lldb_private::process_netbsd::NativeThreadNetBSD::Resume(), lldb_private::process_freebsd::NativeThreadFreeBSD::SetStoppedBySignal(), lldb_private::process_netbsd::NativeThreadNetBSD::SetStoppedBySignal(), lldb_private::process_freebsd::NativeThreadFreeBSD::SingleStep(), lldb_private::process_netbsd::NativeThreadNetBSD::SingleStep(), lldb_private::process_freebsd::NativeThreadFreeBSD::Suspend(), and lldb_private::process_netbsd::NativeThreadNetBSD::Suspend().
GetName()
virtual std::string lldb_private::NativeThreadProtocol::GetName () pure virtual
Implemented in lldb_private::NativeThreadWindows, lldb_private::process_aix::NativeThreadAIX, lldb_private::process_freebsd::NativeThreadFreeBSD, lldb_private::process_linux::NativeThreadLinux, and lldb_private::process_netbsd::NativeThreadNetBSD.
GetProcess()
NativeProcessProtocol & lldb_private::NativeThreadProtocol::GetProcess () inline
Definition at line 41 of file NativeThreadProtocol.h.
References m_process.
Referenced by lldb_private::NativeThreadWindows::DoResume(), and lldb_private::NativeThreadWindows::GetName().
GetRegisterContext()
virtual NativeRegisterContext & lldb_private::NativeThreadProtocol::GetRegisterContext () pure virtual
Implemented in lldb_private::NativeThreadWindows, lldb_private::process_freebsd::NativeThreadFreeBSD, lldb_private::process_linux::NativeThreadLinux, and lldb_private::process_netbsd::NativeThreadNetBSD.
GetSiginfo()
virtual llvm::Expected< std::unique_ptr< llvm::MemoryBuffer > > lldb_private::NativeThreadProtocol::GetSiginfo () const inline virtual
Reimplemented in lldb_private::process_aix::NativeThreadAIX, lldb_private::process_freebsd::NativeThreadFreeBSD, and lldb_private::process_linux::NativeThreadLinux.
Definition at line 55 of file NativeThreadProtocol.h.
GetState()
virtual lldb::StateType lldb_private::NativeThreadProtocol::GetState () pure virtual
Implemented in lldb_private::NativeThreadWindows, lldb_private::process_aix::NativeThreadAIX, lldb_private::process_freebsd::NativeThreadFreeBSD, lldb_private::process_linux::NativeThreadLinux, and lldb_private::process_netbsd::NativeThreadNetBSD.
GetStopReason()
virtual bool lldb_private::NativeThreadProtocol::GetStopReason (ThreadStopInfo & stop_info, std::string & description) pure virtual
Implemented in lldb_private::NativeThreadWindows, lldb_private::process_aix::NativeThreadAIX, lldb_private::process_freebsd::NativeThreadFreeBSD, lldb_private::process_linux::NativeThreadLinux, and lldb_private::process_netbsd::NativeThreadNetBSD.
RemoveHardwareBreakpoint()
virtual Status lldb_private::NativeThreadProtocol::RemoveHardwareBreakpoint (lldb::addr_t addr) pure virtual
Implemented in lldb_private::NativeThreadWindows, lldb_private::process_aix::NativeThreadAIX, lldb_private::process_freebsd::NativeThreadFreeBSD, lldb_private::process_linux::NativeThreadLinux, and lldb_private::process_netbsd::NativeThreadNetBSD.
RemoveWatchpoint()
virtual Status lldb_private::NativeThreadProtocol::RemoveWatchpoint (lldb::addr_t addr) pure virtual
Implemented in lldb_private::NativeThreadWindows, lldb_private::process_aix::NativeThreadAIX, lldb_private::process_freebsd::NativeThreadFreeBSD, lldb_private::process_linux::NativeThreadLinux, and lldb_private::process_netbsd::NativeThreadNetBSD.
SetHardwareBreakpoint()
virtual Status lldb_private::NativeThreadProtocol::SetHardwareBreakpoint (lldb::addr_t addr, size_t size) pure virtual
Implemented in lldb_private::NativeThreadWindows, lldb_private::process_aix::NativeThreadAIX, lldb_private::process_freebsd::NativeThreadFreeBSD, lldb_private::process_linux::NativeThreadLinux, and lldb_private::process_netbsd::NativeThreadNetBSD.
SetWatchpoint()
virtual Status lldb_private::NativeThreadProtocol::SetWatchpoint (lldb::addr_t addr, size_t size, uint32_t watch_flags, bool hardware) pure virtual
Implemented in lldb_private::NativeThreadWindows, lldb_private::process_aix::NativeThreadAIX, lldb_private::process_freebsd::NativeThreadFreeBSD, lldb_private::process_linux::NativeThreadLinux, and lldb_private::process_netbsd::NativeThreadNetBSD.
Member Data Documentation
m_process
NativeProcessProtocol& lldb_private::NativeThreadProtocol::m_process protected
Definition at line 60 of file NativeThreadProtocol.h.
Referenced by lldb_private::process_netbsd::NativeThreadNetBSD::GetName(), GetProcess(), lldb_private::process_aix::NativeThreadAIX::GetProcess(), lldb_private::process_aix::NativeThreadAIX::GetProcess(), lldb_private::process_freebsd::NativeThreadFreeBSD::GetProcess(), lldb_private::process_linux::NativeThreadLinux::GetProcess(), lldb_private::process_linux::NativeThreadLinux::GetProcess(), lldb_private::process_linux::NativeThreadLinux::MaybeLogStateChange(), NativeThreadProtocol(), lldb_private::process_netbsd::NativeThreadNetBSD::Resume(), lldb_private::process_netbsd::NativeThreadNetBSD::SingleStep(), and lldb_private::process_netbsd::NativeThreadNetBSD::Suspend().
m_tid
lldb::tid_t lldb_private::NativeThreadProtocol::m_tid protected
Definition at line 61 of file NativeThreadProtocol.h.
Referenced by GetID(), lldb_private::process_netbsd::NativeThreadNetBSD::GetName(), NativeThreadProtocol(), and lldb_private::process_linux::NativeThreadLinux::SingleStep().
The documentation for this class was generated from the following files:
NativeThreadProtocol.h
NativeThreadProtocol.cpp