LLDB: lldb_private::ThreadPlanStepOut Class Reference
lldb_private::ThreadPlanStepOut Class Reference
#include <ThreadPlanStepOut.h>
Public Member Functions
ThreadPlanStepOut (Thread &thread, SymbolContext *addr_context, bool first_insn, bool stop_others, Vote report_stop_vote, Vote report_run_vote, uint32_t frame_idx, LazyBool step_out_avoids_code_without_debug_info, bool continue_to_next_branch=false, bool gather_return_value=true)
Creates a thread plan to step out from frame_idx, skipping parent frames if they are artificial or hidden frames.
ThreadPlanStepOut (Thread &thread, bool stop_others, Vote report_stop_vote, Vote report_run_vote, uint32_t frame_idx, bool continue_to_next_branch=false, bool gather_return_value=true)
Creates a thread plan to step out from frame_idx to frame_idx + 1.
~ThreadPlanStepOut () override
void GetDescription (Stream *s, lldb::DescriptionLevel level) override
Print a description of this thread to the stream s.
bool ValidatePlan (Stream *error) override
Returns whether this plan could be successfully created.
bool ShouldStop (Event *event_ptr) override
bool StopOthers () override
void SetStopOthers (bool new_value) override
lldb::StateType GetPlanRunState () override
bool WillStop () override
bool MischiefManaged () override
void DidPush () override
bool IsPlanStale () override
lldb::ValueObjectSP GetReturnValueObject () override
Public Member Functions inherited from lldb_private::ThreadPlan
virtual ~ThreadPlan ()
const char * GetName () const
Returns the name of this thread plan.
Thread & GetThread ()
Returns the Thread that is using this thread plan.
Target & GetTarget ()
const Target & GetTarget () const
void ClearThreadCache ()
Clear the Thread* cache.
bool TracerExplainsStop ()
lldb::StateType RunState ()
bool PlanExplainsStop (Event *event_ptr)
virtual bool ShouldAutoContinue (Event *event_ptr)
Returns whether this thread plan overrides the ShouldStop of subsequently processed plans.
virtual Vote ShouldReportStop (Event *event_ptr)
Vote ShouldReportRun (Event *event_ptr)
virtual bool SupportsResumeOthers ()
virtual bool ShouldRunBeforePublicStop ()
bool WillResume (lldb::StateType resume_state, bool current_plan)
bool IsControllingPlan ()
virtual bool IsLeafPlan ()
bool SetIsControllingPlan (bool value)
virtual bool OkayToDiscard ()
void SetOkayToDiscard (bool value)
virtual void ThreadDestroyed ()
bool GetPrivate ()
void SetPrivate (bool input)
virtual void DidPop ()
ThreadPlanKind GetKind () const
bool IsPlanComplete ()
void SetPlanComplete (bool success=true)
bool PlanSucceeded ()
virtual bool IsBasePlan ()
lldb::ThreadPlanTracerSP & GetThreadPlanTracer ()
void SetThreadPlanTracer (lldb::ThreadPlanTracerSP new_tracer_sp)
void DoTraceLog ()
virtual lldb::ExpressionVariableSP GetExpressionVariable ()
virtual void RestoreThreadState ()
virtual bool IsVirtualStep ()
bool SetIterationCount (size_t count)
virtual lldb::RunDirection GetDirection () const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Public Member Functions inherited from lldb_private::ThreadPlanShouldStopHere
ThreadPlanShouldStopHere (ThreadPlan *owner)
ThreadPlanShouldStopHere (ThreadPlan *owner, const ThreadPlanShouldStopHereCallbacks *callbacks, void *baton=nullptr)
virtual ~ThreadPlanShouldStopHere ()
void SetShouldStopHereCallbacks (const ThreadPlanShouldStopHereCallbacks *callbacks, void *baton)
void ClearShouldStopHereCallbacks ()
bool InvokeShouldStopHereCallback (lldb::FrameComparison operation, Status &status)
lldb::ThreadPlanSP CheckShouldStopHereAndQueueStepOut (lldb::FrameComparison operation, Status &status)
lldb_private::Flags & GetFlags ()
const lldb_private::Flags & GetFlags () const
Protected Member Functions
void SetFlagsToDefault () override
bool DoPlanExplainsStop (Event *event_ptr) override
bool DoWillResume (lldb::StateType resume_state, bool current_plan) override
bool QueueInlinedStepPlan (bool queue_now)
Protected Member Functions inherited from lldb_private::ThreadPlan
ThreadPlan (ThreadPlanKind kind, const char *name, Thread &thread, Vote report_stop_vote, Vote report_run_vote)
void PushPlan (lldb::ThreadPlanSP &thread_plan_sp)
ThreadPlan * GetPreviousPlan ()
lldb::StopInfoSP GetPrivateStopInfo ()
void SetStopInfo (lldb::StopInfoSP stop_reason_sp)
bool IsUsuallyUnexplainedStopReason (lldb::StopReason)
Protected Member Functions inherited from lldb_private::ThreadPlanShouldStopHere
virtual lldb::ThreadPlanSP QueueStepOutFromHerePlan (Flags &flags, lldb::FrameComparison operation, Status &status)
Private Member Functions
void SetupAvoidNoDebug (LazyBool step_out_avoids_code_without_debug_info)
void SetupReturnAddress (lldb::StackFrameSP return_frame_sp, lldb::StackFrameSP immediate_return_from_sp, uint32_t frame_idx, bool continue_to_next_branch)
void CalculateReturnValue ()
ThreadPlanStepOut (const ThreadPlanStepOut &)=delete
const ThreadPlanStepOut & operator= (const ThreadPlanStepOut &)=delete
Private Attributes
lldb::addr_t m_step_from_insn
StackID m_step_out_to_id
StackID m_immediate_step_from_id
lldb::break_id_t m_return_bp_id
lldb::addr_t m_return_addr
bool m_stop_others
lldb::ThreadPlanSP m_step_out_to_inline_plan_sp
lldb::ThreadPlanSP m_step_through_inline_plan_sp
lldb::ThreadPlanSP m_step_out_further_plan_sp
Function * m_immediate_step_from_function
std::vector< lldb::StackFrameSP > m_stepped_past_frames
lldb::ValueObjectSP m_return_valobj_sp
bool m_calculate_return_value
StreamString m_constructor_errors
Static Private Attributes
static uint32_t s_default_flag_values = 0
Friends
lldb::ThreadPlanSP Thread::QueueThreadPlanForStepOut (bool abort_other_plans, SymbolContext *addr_context, bool first_insn, bool stop_others, Vote report_stop_vote, Vote report_run_vote, uint32_t frame_idx, Status &status, LazyBool step_out_avoids_code_without_debug_info)
Additional Inherited Members
Public Types inherited from lldb_private::ThreadPlan
enum ThreadPlanKind {
eKindGeneric , eKindNull , eKindBase , eKindCallFunction ,
eKindPython , eKindStepInstruction , eKindStepOut , eKindStepOverBreakpoint ,
eKindStepOverRange , eKindStepInRange , eKindRunToAddress , eKindStepThrough ,
eKindStepUntil , eKindSingleThreadTimeout
}
Public Types inherited from lldb_private::ThreadPlanShouldStopHere
enum {
eNone = 0 , eAvoidInlines = (1 << 0) , eStepInAvoidNoDebug = (1 << 1) , eStepOutAvoidNoDebug = (1 << 2) ,
eStepOutPastThunks = (1 << 3)
}
Static Protected Member Functions inherited from lldb_private::ThreadPlanShouldStopHere
static bool DefaultShouldStopHereCallback (ThreadPlan *current_plan, Flags &flags, lldb::FrameComparison operation, Status &status, void *baton)
static lldb::ThreadPlanSP DefaultStepFromHereCallback (ThreadPlan *current_plan, Flags &flags, lldb::FrameComparison operation, Status &status, void *baton)
Protected Attributes inherited from lldb_private::ThreadPlan
Status m_status
Process & m_process
lldb::tid_t m_tid
Vote m_report_stop_vote
Vote m_report_run_vote
bool m_takes_iteration_count
bool m_could_not_resolve_hw_bp
int32_t m_iteration_count = 1
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Protected Attributes inherited from lldb_private::ThreadPlanShouldStopHere
ThreadPlanShouldStopHereCallbacks m_callbacks
void * m_baton
ThreadPlan * m_owner
lldb_private::Flags m_flags
Detailed Description
Definition at line 18 of file ThreadPlanStepOut.h.
Constructor & Destructor Documentation
ThreadPlanStepOut() [1/3]
ThreadPlanStepOut::ThreadPlanStepOut (Thread & thread, SymbolContext * addr_context, bool first_insn, bool stop_others, Vote report_stop_vote, Vote report_run_vote, uint32_t frame_idx, LazyBool step_out_avoids_code_without_debug_info, bool continue_to_next_branch = false, bool gather_return_value = true)
Creates a thread plan to step out from frame_idx, skipping parent frames if they are artificial or hidden frames.
Also skips frames without debug info based on step_out_avoids_code_without_debug_info.
Definition at line 61 of file ThreadPlanStepOut.cpp.
References ComputeTargetFrame(), lldb_private::ThreadPlan::eKindStepOut, LLDB_INVALID_ADDRESS, LLDB_INVALID_BREAK_ID, m_calculate_return_value, m_immediate_step_from_function, m_return_addr, m_return_bp_id, m_step_from_insn, m_stepped_past_frames, m_stop_others, SetFlagsToDefault(), SetupAvoidNoDebug(), SetupReturnAddress(), lldb_private::ThreadPlan::ThreadPlan(), and lldb_private::ThreadPlanShouldStopHere::ThreadPlanShouldStopHere().
Referenced by lldb_private::AppleThreadPlanStepThroughDirectDispatch::AppleThreadPlanStepThroughDirectDispatch(), operator=(), SetupReturnAddress(), and ThreadPlanStepOut().
ThreadPlanStepOut() [2/3]
ThreadPlanStepOut::ThreadPlanStepOut (Thread & thread, bool stop_others, Vote report_stop_vote, Vote report_run_vote, uint32_t frame_idx, bool continue_to_next_branch = false, bool gather_return_value = true)
Creates a thread plan to step out from frame_idx to frame_idx + 1.
Definition at line 86 of file ThreadPlanStepOut.cpp.
References lldb_private::ThreadPlan::eKindStepOut, LLDB_INVALID_ADDRESS, LLDB_INVALID_BREAK_ID, m_calculate_return_value, m_immediate_step_from_function, m_return_addr, m_return_bp_id, m_step_from_insn, m_stop_others, SetFlagsToDefault(), SetupReturnAddress(), lldb_private::ThreadPlan::ThreadPlan(), and lldb_private::ThreadPlanShouldStopHere::ThreadPlanShouldStopHere().
~ThreadPlanStepOut()
ThreadPlanStepOut::~ThreadPlanStepOut () override
Definition at line 230 of file ThreadPlanStepOut.cpp.
References lldb_private::ThreadPlan::GetTarget(), LLDB_INVALID_BREAK_ID, m_return_bp_id, and lldb_private::Target::RemoveBreakpointByID().
ThreadPlanStepOut() [3/3]
lldb_private::ThreadPlanStepOut::ThreadPlanStepOut (const ThreadPlanStepOut &) private delete
References ThreadPlanStepOut().
Member Function Documentation
CalculateReturnValue()
void ThreadPlanStepOut::CalculateReturnValue () private
Definition at line 544 of file ThreadPlanStepOut.cpp.
References lldb_private::ThreadPlan::GetThread(), m_calculate_return_value, m_immediate_step_from_function, lldb_private::ThreadPlan::m_process, and m_return_valobj_sp.
Referenced by DoPlanExplainsStop(), and ShouldStop().
DidPush()
void ThreadPlanStepOut::DidPush () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 222 of file ThreadPlanStepOut.cpp.
References lldb_private::ThreadPlan::GetThread(), m_step_out_to_inline_plan_sp, and m_step_through_inline_plan_sp.
DoPlanExplainsStop()
bool ThreadPlanStepOut::DoPlanExplainsStop (Event * event_ptr) override protected virtual
Implements lldb_private::ThreadPlan.
Definition at line 309 of file ThreadPlanStepOut.cpp.
References CalculateReturnValue(), lldb::eFrameCompareOlder, lldb::eStopReasonBreakpoint, lldb_private::ThreadPlan::GetPrivateStopInfo(), lldb_private::Thread::GetStackFrameAtIndex(), lldb_private::ThreadPlan::GetThread(), lldb_private::ThreadPlanShouldStopHere::InvokeShouldStopHereCallback(), lldb_private::ThreadPlan::IsUsuallyUnexplainedStopReason(), m_immediate_step_from_id, lldb_private::ThreadPlan::m_process, m_return_bp_id, lldb_private::ThreadPlan::m_status, m_step_out_further_plan_sp, m_step_out_to_id, m_step_out_to_inline_plan_sp, m_step_through_inline_plan_sp, and lldb_private::ThreadPlan::SetPlanComplete().
Referenced by lldb_private::AppleThreadPlanStepThroughDirectDispatch::DoPlanExplainsStop().
DoWillResume()
bool ThreadPlanStepOut::DoWillResume (lldb::StateType resume_state, bool current_plan) override protected virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 433 of file ThreadPlanStepOut.cpp.
References lldb_private::Target::GetBreakpointByID(), lldb_private::ThreadPlan::GetTarget(), LLDB_INVALID_BREAK_ID, m_return_bp_id, m_step_out_to_inline_plan_sp, m_step_through_inline_plan_sp, and lldb_private::Breakpoint::SetEnabled().
Referenced by lldb_private::AppleThreadPlanStepThroughDirectDispatch::DoWillResume().
GetDescription()
void ThreadPlanStepOut::GetDescription (Stream * s, lldb::DescriptionLevel level) override virtual
Print a description of this thread to the stream s.
thread. Don't expect that the result of GetThread is valid in the description method. This might get called when the underlying Thread has not been reported, so we only know the TID and not the thread.
Parameters
[in] s The stream to which to print the description.
[in] level The level of description desired. Note that eDescriptionLevelBrief will be used in the stop message printed when the plan is complete.
Implements lldb_private::ThreadPlan.
Definition at line 235 of file ThreadPlanStepOut.cpp.
References lldb_private::Address::Dump(), lldb_private::Address::DumpStyleLoadAddress, lldb_private::Address::DumpStyleResolvedDescription, lldb::eDescriptionLevelBrief, lldb::eDescriptionLevelVerbose, lldb_private::ThreadPlan::GetTarget(), lldb_private::ThreadPlan::m_process, m_return_addr, m_return_bp_id, m_step_from_insn, m_step_out_to_inline_plan_sp, m_step_through_inline_plan_sp, m_stepped_past_frames, lldb_private::Stream::Printf(), and lldb_private::Address::SetLoadAddress().
GetPlanRunState()
StateType ThreadPlanStepOut::GetPlanRunState () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 431 of file ThreadPlanStepOut.cpp.
References lldb::eStateRunning.
GetReturnValueObject()
lldb::ValueObjectSP lldb_private::ThreadPlanStepOut::GetReturnValueObject () inline override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 49 of file ThreadPlanStepOut.h.
References m_return_valobj_sp.
IsPlanStale()
bool ThreadPlanStepOut::IsPlanStale () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 564 of file ThreadPlanStepOut.cpp.
References lldb_private::Thread::GetStackFrameAtIndex(), lldb_private::ThreadPlan::GetThread(), and m_step_out_to_id.
MischiefManaged()
bool ThreadPlanStepOut::MischiefManaged () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 459 of file ThreadPlanStepOut.cpp.
References lldb_private::GetLog(), lldb_private::ThreadPlan::GetTarget(), lldb_private::ThreadPlan::IsPlanComplete(), LLDB_INVALID_BREAK_ID, LLDB_LOGF, m_return_bp_id, lldb_private::ThreadPlan::MischiefManaged(), lldb_private::Target::RemoveBreakpointByID(), and lldb_private::Step.
Referenced by lldb_private::AppleThreadPlanStepThroughDirectDispatch::MischiefManaged().
operator=()
const ThreadPlanStepOut & lldb_private::ThreadPlanStepOut::operator= (const ThreadPlanStepOut &) private delete
References ThreadPlanStepOut().
QueueInlinedStepPlan()
bool ThreadPlanStepOut::QueueInlinedStepPlan (bool queue_now) protected
Definition at line 483 of file ThreadPlanStepOut.cpp.
References lldb_private::ThreadPlanStepRange::AddRange(), lldb_private::Block::CalculateSymbolContext(), lldb::eAllThreads, lldb_private::eLazyBoolNo, lldb::eOnlyThisThread, lldb_private::Block::GetContainingInlinedBlock(), lldb_private::StreamString::GetData(), lldb_private::GetLog(), lldb_private::Block::GetNumRanges(), lldb_private::Block::GetRangeAtIndex(), lldb_private::ThreadPlan::GetTarget(), lldb_private::ThreadPlan::GetThread(), LLDB_LOGF, m_step_through_inline_plan_sp, m_stop_others, lldb_private::ThreadPlan::SetOkayToDiscard(), lldb_private::Step, lldb_private::SymbolContext::target_sp, and lldb_private::ThreadPlanStepRange::ValidatePlan().
Referenced by SetupReturnAddress(), and ShouldStop().
SetFlagsToDefault()
void lldb_private::ThreadPlanStepOut::SetFlagsToDefault () inline override protected virtual
Implements lldb_private::ThreadPlanShouldStopHere.
Definition at line 54 of file ThreadPlanStepOut.h.
References lldb_private::ThreadPlanShouldStopHere::GetFlags(), s_default_flag_values, and lldb_private::Flags::Set().
Referenced by ThreadPlanStepOut(), and ThreadPlanStepOut().
SetStopOthers()
void lldb_private::ThreadPlanStepOut::SetStopOthers (bool new_value) inline override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 42 of file ThreadPlanStepOut.h.
References m_stop_others.
SetupAvoidNoDebug()
void ThreadPlanStepOut::SetupAvoidNoDebug (LazyBool step_out_avoids_code_without_debug_info) private
Definition at line 202 of file ThreadPlanStepOut.cpp.
References lldb_private::Flags::Clear(), lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb_private::ThreadPlanShouldStopHere::eStepOutAvoidNoDebug, lldb_private::ThreadPlanShouldStopHere::GetFlags(), lldb_private::ThreadProperties::GetStepOutAvoidsNoDebug(), lldb_private::ThreadPlan::GetThread(), and lldb_private::Flags::Set().
Referenced by ThreadPlanStepOut().
SetupReturnAddress()
void ThreadPlanStepOut::SetupReturnAddress (lldb::StackFrameSP return_frame_sp, lldb::StackFrameSP immediate_return_from_sp, uint32_t frame_idx, bool continue_to_next_branch) private
Definition at line 108 of file ThreadPlanStepOut.cpp.
References lldb_private::Address::CalculateSymbolContext(), lldb_private::Target::CreateBreakpoint(), lldb_private::eLazyBoolNo, lldb_private::eVoteNoOpinion, lldb_private::SymbolContext::function, lldb_private::AddressRange::GetByteSize(), lldb_private::Stoppoint::GetID(), lldb_private::Address::GetLoadAddress(), lldb_private::GetLog(), lldb_private::Address::GetOffset(), lldb_private::LineEntry::GetSameLineContiguousAddressRange(), lldb_private::ThreadPlan::GetTarget(), lldb_private::ThreadPlan::GetThread(), lldb_private::Breakpoint::HasResolvedLocations(), lldb_private::Breakpoint::IsHardware(), lldb_private::LineEntry::IsValid(), lldb_private::SymbolContext::line_entry, LLDB_INVALID_ADDRESS, LLDB_LOGF, m_constructor_errors, lldb_private::ThreadPlan::m_could_not_resolve_hw_bp, m_immediate_step_from_function, m_immediate_step_from_id, lldb_private::ThreadPlan::m_process, m_return_addr, m_return_bp_id, m_step_out_to_id, m_step_out_to_inline_plan_sp, m_stop_others, lldb_private::ThreadPlan::m_tid, QueueInlinedStepPlan(), lldb_private::Breakpoint::SetBreakpointKind(), lldb_private::Breakpoint::SetThreadID(), lldb_private::Address::Slide(), lldb_private::Step, and ThreadPlanStepOut().
Referenced by ThreadPlanStepOut(), and ThreadPlanStepOut().
ShouldStop()
bool ThreadPlanStepOut::ShouldStop (Event * event_ptr) override virtual
Implements lldb_private::ThreadPlan.
Definition at line 374 of file ThreadPlanStepOut.cpp.
References CalculateReturnValue(), lldb::eFrameCompareOlder, lldb::eStopReasonBreakpoint, lldb_private::ThreadPlan::GetPrivateStopInfo(), lldb_private::Thread::GetStackFrameAtIndex(), lldb_private::ThreadPlan::GetThread(), lldb_private::ThreadPlanShouldStopHere::InvokeShouldStopHereCallback(), lldb_private::ThreadPlan::IsPlanComplete(), lldb_private::ThreadPlanShouldStopHere::m_flags, lldb_private::ThreadPlan::m_status, m_step_out_further_plan_sp, m_step_out_to_id, m_step_out_to_inline_plan_sp, m_step_through_inline_plan_sp, QueueInlinedStepPlan(), lldb_private::ThreadPlanShouldStopHere::QueueStepOutFromHerePlan(), and lldb_private::ThreadPlan::SetPlanComplete().
Referenced by lldb_private::AppleThreadPlanStepThroughDirectDispatch::ShouldStop().
StopOthers()
bool ThreadPlanStepOut::StopOthers () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 429 of file ThreadPlanStepOut.cpp.
References m_stop_others.
ValidatePlan()
bool ThreadPlanStepOut::ValidatePlan (Stream * error) override virtual
Returns whether this plan could be successfully created.
Parameters
[in] error A stream to which to print some reason why the plan could not be created. Can be NULL.
Returns
true if the plan should be queued, false otherwise.
Implements lldb_private::ThreadPlan.
Definition at line 281 of file ThreadPlanStepOut.cpp.
References error(), LLDB_INVALID_BREAK_ID, m_constructor_errors, lldb_private::ThreadPlan::m_could_not_resolve_hw_bp, m_return_bp_id, m_step_out_to_inline_plan_sp, and m_step_through_inline_plan_sp.
WillStop()
bool ThreadPlanStepOut::WillStop () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 449 of file ThreadPlanStepOut.cpp.
References lldb_private::Target::GetBreakpointByID(), lldb_private::ThreadPlan::GetTarget(), LLDB_INVALID_BREAK_ID, m_return_bp_id, and lldb_private::Breakpoint::SetEnabled().
Friends And Related Symbol Documentation
Thread::QueueThreadPlanForStepOut
lldb::ThreadPlanSP Thread::QueueThreadPlanForStepOut (bool abort_other_plans, SymbolContext * addr_context, bool first_insn, bool stop_others, Vote report_stop_vote, Vote report_run_vote, uint32_t frame_idx, Status & status, LazyBool step_out_avoids_code_without_debug_info) friend
Member Data Documentation
m_calculate_return_value
bool lldb_private::ThreadPlanStepOut::m_calculate_return_value private
Definition at line 84 of file ThreadPlanStepOut.h.
Referenced by CalculateReturnValue(), ThreadPlanStepOut(), and ThreadPlanStepOut().
m_constructor_errors
StreamString lldb_private::ThreadPlanStepOut::m_constructor_errors private
Definition at line 85 of file ThreadPlanStepOut.h.
Referenced by SetupReturnAddress(), and ValidatePlan().
m_immediate_step_from_function
Function* lldb_private::ThreadPlanStepOut::m_immediate_step_from_function private
Definition at line 81 of file ThreadPlanStepOut.h.
Referenced by CalculateReturnValue(), SetupReturnAddress(), ThreadPlanStepOut(), and ThreadPlanStepOut().
m_immediate_step_from_id
StackID lldb_private::ThreadPlanStepOut::m_immediate_step_from_id private
Definition at line 68 of file ThreadPlanStepOut.h.
Referenced by DoPlanExplainsStop(), and SetupReturnAddress().
m_return_addr
lldb::addr_t lldb_private::ThreadPlanStepOut::m_return_addr private
Definition at line 70 of file ThreadPlanStepOut.h.
Referenced by GetDescription(), SetupReturnAddress(), ThreadPlanStepOut(), and ThreadPlanStepOut().
m_return_bp_id
lldb::break_id_t lldb_private::ThreadPlanStepOut::m_return_bp_id private
Definition at line 69 of file ThreadPlanStepOut.h.
Referenced by DoPlanExplainsStop(), DoWillResume(), GetDescription(), MischiefManaged(), SetupReturnAddress(), ThreadPlanStepOut(), ThreadPlanStepOut(), ValidatePlan(), WillStop(), and ~ThreadPlanStepOut().
m_return_valobj_sp
lldb::ValueObjectSP lldb_private::ThreadPlanStepOut::m_return_valobj_sp private
Definition at line 83 of file ThreadPlanStepOut.h.
Referenced by CalculateReturnValue(), and GetReturnValueObject().
m_step_from_insn
lldb::addr_t lldb_private::ThreadPlanStepOut::m_step_from_insn private
Definition at line 66 of file ThreadPlanStepOut.h.
Referenced by GetDescription(), ThreadPlanStepOut(), and ThreadPlanStepOut().
m_step_out_further_plan_sp
lldb::ThreadPlanSP lldb_private::ThreadPlanStepOut::m_step_out_further_plan_sp private
Definition at line 78 of file ThreadPlanStepOut.h.
Referenced by DoPlanExplainsStop(), and ShouldStop().
m_step_out_to_id
StackID lldb_private::ThreadPlanStepOut::m_step_out_to_id private
Definition at line 67 of file ThreadPlanStepOut.h.
Referenced by DoPlanExplainsStop(), IsPlanStale(), SetupReturnAddress(), and ShouldStop().
m_step_out_to_inline_plan_sp
lldb::ThreadPlanSP lldb_private::ThreadPlanStepOut::m_step_out_to_inline_plan_sp private
Definition at line 72 of file ThreadPlanStepOut.h.
Referenced by DidPush(), DoPlanExplainsStop(), DoWillResume(), GetDescription(), SetupReturnAddress(), ShouldStop(), and ValidatePlan().
m_step_through_inline_plan_sp
lldb::ThreadPlanSP lldb_private::ThreadPlanStepOut::m_step_through_inline_plan_sp private
Definition at line 76 of file ThreadPlanStepOut.h.
Referenced by DidPush(), DoPlanExplainsStop(), DoWillResume(), GetDescription(), QueueInlinedStepPlan(), ShouldStop(), and ValidatePlan().
m_stepped_past_frames
std::vector<lldb::StackFrameSP> lldb_private::ThreadPlanStepOut::m_stepped_past_frames private
Definition at line 82 of file ThreadPlanStepOut.h.
Referenced by GetDescription(), and ThreadPlanStepOut().
m_stop_others
bool lldb_private::ThreadPlanStepOut::m_stop_others private
Definition at line 71 of file ThreadPlanStepOut.h.
Referenced by QueueInlinedStepPlan(), SetStopOthers(), SetupReturnAddress(), StopOthers(), ThreadPlanStepOut(), and ThreadPlanStepOut().
s_default_flag_values
uint32_t ThreadPlanStepOut::s_default_flag_values = 0 static private
Definition at line 63 of file ThreadPlanStepOut.h.
Referenced by SetFlagsToDefault().
The documentation for this class was generated from the following files:
ThreadPlanStepOut.h
ThreadPlanStepOut.cpp