LLDB: ThreadStepScopeOptionGroup Class Reference
ThreadStepScopeOptionGroup Class Reference
Public Member Functions
ThreadStepScopeOptionGroup ()
~ThreadStepScopeOptionGroup () override=default
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext *execution_context) override
void OptionParsingStarting (ExecutionContext *execution_context) override
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Public Attributes
LazyBool m_step_in_avoid_no_debug
LazyBool m_step_out_avoid_no_debug
RunMode m_run_mode
std::string m_avoid_regexp
std::string m_step_in_target
uint32_t m_step_count
uint32_t m_end_line
bool m_end_line_is_block_end
Detailed Description
Definition at line 263 of file CommandObjectThread.cpp.
Constructor & Destructor Documentation
ThreadStepScopeOptionGroup()
ThreadStepScopeOptionGroup::ThreadStepScopeOptionGroup () inline
Definition at line 265 of file CommandObjectThread.cpp.
References OptionParsingStarting().
~ThreadStepScopeOptionGroup()
ThreadStepScopeOptionGroup::~ThreadStepScopeOptionGroup () override default
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > ThreadStepScopeOptionGroup::GetDefinitions () inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 273 of file CommandObjectThread.cpp.
Referenced by SetOptionValue().
OptionParsingStarting()
void ThreadStepScopeOptionGroup::OptionParsingStarting (ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 349 of file CommandObjectThread.cpp.
References lldb::eAllThreads, lldb_private::eLazyBoolCalculate, lldb::eOnlyDuringStepping, lldb_private::ExecutionContext::GetProcessSP(), lldb_private::ExecutionContext::GetTargetSP(), LLDB_INVALID_LINE_NUMBER, m_avoid_regexp, m_end_line, m_end_line_is_block_end, m_run_mode, m_step_count, m_step_in_avoid_no_debug, m_step_in_target, and m_step_out_avoid_no_debug.
Referenced by ThreadStepScopeOptionGroup().
SetOptionValue()
Status ThreadStepScopeOptionGroup::SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 277 of file CommandObjectThread.cpp.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb::eOnlyDuringStepping, error(), lldb_private::Status::FromErrorStringWithFormat(), GetDefinitions(), m_avoid_regexp, m_end_line, m_end_line_is_block_end, m_run_mode, m_step_count, m_step_in_avoid_no_debug, m_step_in_target, m_step_out_avoid_no_debug, lldb_private::OptionArgParser::ToBoolean(), and lldb_private::OptionArgParser::ToOptionEnum().
Member Data Documentation
m_avoid_regexp
std::string ThreadStepScopeOptionGroup::m_avoid_regexp
Definition at line 373 of file CommandObjectThread.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_end_line
uint32_t ThreadStepScopeOptionGroup::m_end_line
Definition at line 376 of file CommandObjectThread.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_end_line_is_block_end
bool ThreadStepScopeOptionGroup::m_end_line_is_block_end
Definition at line 377 of file CommandObjectThread.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_run_mode
RunMode ThreadStepScopeOptionGroup::m_run_mode
Definition at line 372 of file CommandObjectThread.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_step_count
uint32_t ThreadStepScopeOptionGroup::m_step_count
Definition at line 375 of file CommandObjectThread.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_step_in_avoid_no_debug
LazyBool ThreadStepScopeOptionGroup::m_step_in_avoid_no_debug
Definition at line 370 of file CommandObjectThread.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_step_in_target
std::string ThreadStepScopeOptionGroup::m_step_in_target
Definition at line 374 of file CommandObjectThread.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_step_out_avoid_no_debug
LazyBool ThreadStepScopeOptionGroup::m_step_out_avoid_no_debug
Definition at line 371 of file CommandObjectThread.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following file:
CommandObjectThread.cpp