LLDB: lldb_private::formatters::NSCFSetSyntheticFrontEnd Class Reference
lldb_private::formatters::NSCFSetSyntheticFrontEnd Class Reference
Classes
struct SetItemDescriptor
Public Member Functions
NSCFSetSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Attributes
ExecutionContextRef m_exe_ctx_ref
uint8_t m_ptr_size = 8
lldb::ByteOrder m_order = lldb::eByteOrderInvalid
CFBasicHash m_hashtable
CompilerType m_pair_type
std::vector< SetItemDescriptor > m_children
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
Definition at line 81 of file NSSet.cpp.
Constructor & Destructor Documentation
NSCFSetSyntheticFrontEnd()
lldb_private::formatters::NSCFSetSyntheticFrontEnd::NSCFSetSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
Definition at line 520 of file NSSet.cpp.
References m_exe_ctx_ref, m_hashtable, m_pair_type, and lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd().
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > lldb_private::formatters::NSCFSetSyntheticFrontEnd::CalculateNumChildren () override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 541 of file NSSet.cpp.
References m_hashtable.
GetChildAtIndex()
lldb::ValueObjectSP lldb_private::formatters::NSCFSetSyntheticFrontEnd::GetChildAtIndex (uint32_t idx) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 567 of file NSSet.cpp.
References lldb_private::SyntheticChildrenFrontEnd::CalculateNumChildrenIgnoringErrors(), lldb_private::SyntheticChildrenFrontEnd::CreateValueObjectFromData(), lldb::eBasicTypeObjCID, error(), lldb_private::StreamString::GetString(), lldb_private::formatters::NSCFSetSyntheticFrontEnd::SetItemDescriptor::item_ptr, lldbassert, lldb_private::SyntheticChildrenFrontEnd::m_backend, m_children, m_exe_ctx_ref, m_hashtable, m_order, m_ptr_size, lldb_private::Stream::Printf(), and lldb_private::formatters::NSCFSetSyntheticFrontEnd::SetItemDescriptor::valobj_sp.
GetIndexOfChildWithName()
llvm::Expected< size_t > lldb_private::formatters::NSCFSetSyntheticFrontEnd::GetIndexOfChildWithName (ConstString name) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 526 of file NSSet.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::SyntheticChildrenFrontEnd::CalculateNumChildrenIgnoringErrors(), and lldb_private::formatters::ExtractIndexFromString().
Update()
lldb::ChildCacheState lldb_private::formatters::NSCFSetSyntheticFrontEnd::Update () override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 548 of file NSSet.cpp.
References lldb::eRefetch, lldb::eReuse, lldb_private::SyntheticChildrenFrontEnd::m_backend, m_children, m_exe_ctx_ref, m_hashtable, m_order, and m_ptr_size.
Member Data Documentation
m_children
std::vector<SetItemDescriptor> lldb_private::formatters::NSCFSetSyntheticFrontEnd::m_children private
Definition at line 106 of file NSSet.cpp.
Referenced by GetChildAtIndex(), and Update().
m_exe_ctx_ref
ExecutionContextRef lldb_private::formatters::NSCFSetSyntheticFrontEnd::m_exe_ctx_ref private
Definition at line 99 of file NSSet.cpp.
Referenced by GetChildAtIndex(), NSCFSetSyntheticFrontEnd(), and Update().
m_hashtable
CFBasicHash lldb_private::formatters::NSCFSetSyntheticFrontEnd::m_hashtable private
Definition at line 103 of file NSSet.cpp.
Referenced by CalculateNumChildren(), GetChildAtIndex(), NSCFSetSyntheticFrontEnd(), and Update().
m_order
lldb::ByteOrder lldb_private::formatters::NSCFSetSyntheticFrontEnd::m_order = lldb::eByteOrderInvalid private
Definition at line 101 of file NSSet.cpp.
Referenced by GetChildAtIndex(), and Update().
m_pair_type
CompilerType lldb_private::formatters::NSCFSetSyntheticFrontEnd::m_pair_type private
Definition at line 105 of file NSSet.cpp.
Referenced by NSCFSetSyntheticFrontEnd().
m_ptr_size
uint8_t lldb_private::formatters::NSCFSetSyntheticFrontEnd::m_ptr_size = 8 private
Definition at line 100 of file NSSet.cpp.
Referenced by GetChildAtIndex(), and Update().
The documentation for this class was generated from the following file:
NSSet.cpp