LLDB: EntityVariableBase Class Reference
EntityVariableBase Class Reference abstract
Base class for materialization of Variables and ValueObjects.
Public Member Functions
virtual ~EntityVariableBase ()=default
EntityVariableBase ()
void Materialize (lldb::StackFrameSP &frame_sp, IRMemoryMap &map, lldb::addr_t process_address, Status &err) override
void Dematerialize (lldb::StackFrameSP &frame_sp, IRMemoryMap &map, lldb::addr_t process_address, lldb::addr_t frame_top, lldb::addr_t frame_bottom, Status &err) override
void DumpToLog (IRMemoryMap &map, lldb::addr_t process_address, Log *log) override
void Wipe (IRMemoryMap &map, lldb::addr_t process_address) override
Public Member Functions inherited from lldb_private::Materializer::Entity
Entity ()=default
virtual ~Entity ()=default
uint32_t GetAlignment ()
uint32_t GetSize ()
uint32_t GetOffset ()
void SetOffset (uint32_t offset)
Protected Attributes
bool m_is_reference = false
lldb::addr_t m_temporary_allocation = LLDB_INVALID_ADDRESS
size_t m_temporary_allocation_size = 0
lldb::DataBufferSP m_original_data
Protected Attributes inherited from lldb_private::Materializer::Entity
uint32_t m_alignment = 1
uint32_t m_size = 0
uint32_t m_offset = 0
Private Member Functions
virtual ConstString GetName () const =0
virtual lldb::ValueObjectSP SetupValueObject (ExecutionContextScope *scope)=0
Creates and returns ValueObject tied to this variable and prepares Entity for materialization.
virtual llvm::Expected< uint64_t > GetByteSize (ExecutionContextScope *scope) const =0
Returns size in bytes of the type associated with this variable.
virtual bool LocationExpressionIsValid () const =0
Returns 'true' if the location expression associated with this variable is valid.
virtual std::optional< size_t > GetTypeBitAlign (ExecutionContextScope *scope) const =0
Returns alignment of the type associated with this variable in bits.
Detailed Description
Base class for materialization of Variables and ValueObjects.
Subclasses specify how to obtain the Value which is to be materialized.
Definition at line 436 of file Materializer.cpp.
Constructor & Destructor Documentation
~EntityVariableBase()
virtual EntityVariableBase::~EntityVariableBase () virtual default
EntityVariableBase()
EntityVariableBase::EntityVariableBase () inline
Definition at line 440 of file Materializer.cpp.
References g_default_var_alignment, g_default_var_byte_size, lldb_private::Materializer::Entity::m_alignment, and lldb_private::Materializer::Entity::m_size.
Member Function Documentation
Dematerialize()
void EntityVariableBase::Dematerialize (lldb::StackFrameSP & frame_sp, IRMemoryMap & map, lldb::addr_t process_address, lldb::addr_t frame_top, lldb::addr_t frame_bottom, Status & err) inline override virtual
Implements lldb_private::Materializer::Entity.
Definition at line 609 of file Materializer.cpp.
References lldb_private::Status::AsCString(), lldb_private::Expressions, lldb_private::IRMemoryMap::Free(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::IRMemoryMap::GetBestExecutionContextScope(), lldb_private::DataExtractor::GetByteSize(), lldb_private::DataExtractor::GetDataStart(), lldb_private::GetLog(), lldb_private::IRMemoryMap::GetMemoryData(), GetName(), LLDB_INVALID_ADDRESS, LLDB_LOGF, lldb_private::Materializer::Entity::m_offset, m_original_data, m_temporary_allocation, m_temporary_allocation_size, SetupValueObject(), and lldb_private::Status::Success().
DumpToLog()
void EntityVariableBase::DumpToLog (IRMemoryMap & map, lldb::addr_t process_address, Log * log) inline override virtual
Implements lldb_private::Materializer::Entity.
Definition at line 692 of file Materializer.cpp.
References lldb_private::DumpHexBytes(), lldb_private::DataExtractor::GetAddress(), lldb_private::IRMemoryMap::GetAddressByteSize(), lldb_private::IRMemoryMap::GetByteOrder(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::DataBufferHeap::GetByteSize(), lldb_private::StreamString::GetString(), LLDB_INVALID_ADDRESS, lldb_private::Materializer::Entity::m_offset, lldb_private::Materializer::Entity::m_size, m_temporary_allocation, m_temporary_allocation_size, lldb_private::Stream::Printf(), lldb_private::Stream::PutChar(), lldb_private::Log::PutString(), lldb_private::IRMemoryMap::ReadMemory(), and lldb_private::Status::Success().
GetByteSize()
virtual llvm::Expected< uint64_t > EntityVariableBase::GetByteSize (ExecutionContextScope * scope) const private pure virtual
Returns size in bytes of the type associated with this variable.
Returns
On success, returns byte size of the type associated with this variable. Returns std::nullopt otherwise.
Implemented in EntityValueObject, and EntityVariable.
Referenced by Materialize().
GetName()
virtual ConstString EntityVariableBase::GetName () const private pure virtual
Implemented in EntityValueObject, and EntityVariable.
GetTypeBitAlign()
virtual std::optional< size_t > EntityVariableBase::GetTypeBitAlign (ExecutionContextScope * scope) const private pure virtual
Returns alignment of the type associated with this variable in bits.
Returns
On success, returns alignment in bits for the type associated with this variable. Returns std::nullopt otherwise.
Implemented in EntityValueObject, and EntityVariable.
Referenced by Materialize().
LocationExpressionIsValid()
virtual bool EntityVariableBase::LocationExpressionIsValid () const private pure virtual
Returns 'true' if the location expression associated with this variable is valid.
Implemented in EntityValueObject, and EntityVariable.
Referenced by Materialize().
Materialize()
void EntityVariableBase::Materialize (lldb::StackFrameSP & frame_sp, IRMemoryMap & map, lldb::addr_t process_address, Status & err) inline override virtual
Implements lldb_private::Materializer::Entity.
Definition at line 447 of file Materializer.cpp.
References lldb_private::Status::AsCString(), lldb_private::IRMemoryMap::eAllocationPolicyMirror, lldb_private::Expressions, lldb_private::Status::Fail(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataExtractor::GetAddress(), lldb_private::IRMemoryMap::GetBestExecutionContextScope(), GetByteSize(), lldb_private::DataExtractor::GetByteSize(), lldb_private::DataExtractor::GetDataStart(), lldb_private::GetLog(), GetName(), GetTypeBitAlign(), LLDB_INVALID_ADDRESS, LLDB_LOGF, LocationExpressionIsValid(), m_is_reference, lldb_private::Materializer::Entity::m_offset, m_original_data, m_temporary_allocation, m_temporary_allocation_size, lldb_private::IRMemoryMap::Malloc(), SetupValueObject(), lldb_private::Status::Success(), lldb_private::toString(), lldb_private::IRMemoryMap::WriteMemory(), and lldb_private::IRMemoryMap::WritePointerToMemory().
SetupValueObject()
virtual lldb::ValueObjectSP EntityVariableBase::SetupValueObject (ExecutionContextScope * scope) private pure virtual
Creates and returns ValueObject tied to this variable and prepares Entity for materialization.
Called each time the Materializer (de)materializes a variable. We re-create the ValueObject based on the current ExecutionContextScope since clients such as conditional breakpoints may materialize the same EntityVariable multiple times with different frames.
Each subsequent use of the EntityVariableBase interface will query the newly created ValueObject until this function is called again.
Implemented in EntityValueObject, and EntityVariable.
Referenced by Dematerialize(), and Materialize().
Wipe()
void EntityVariableBase::Wipe (IRMemoryMap & map, lldb::addr_t process_address) inline override virtual
Implements lldb_private::Materializer::Entity.
Definition at line 754 of file Materializer.cpp.
References lldb_private::IRMemoryMap::Free(), LLDB_INVALID_ADDRESS, m_temporary_allocation, and m_temporary_allocation_size.
Member Data Documentation
m_is_reference
bool EntityVariableBase::m_is_reference = false protected
Definition at line 802 of file Materializer.cpp.
Referenced by EntityVariable::EntityVariable(), Materialize(), and EntityValueObject::SetupValueObject().
m_original_data
lldb::DataBufferSP EntityVariableBase::m_original_data protected
Definition at line 805 of file Materializer.cpp.
Referenced by Dematerialize(), and Materialize().
m_temporary_allocation
lldb::addr_t EntityVariableBase::m_temporary_allocation = LLDB_INVALID_ADDRESS protected
Definition at line 803 of file Materializer.cpp.
Referenced by Dematerialize(), DumpToLog(), Materialize(), and Wipe().
m_temporary_allocation_size
size_t EntityVariableBase::m_temporary_allocation_size = 0 protected
Definition at line 804 of file Materializer.cpp.
Referenced by Dematerialize(), DumpToLog(), Materialize(), and Wipe().
The documentation for this class was generated from the following file:
Materializer.cpp