LLDB: CommandObjectCommandsAlias::CommandOptions Class Reference
CommandObjectCommandsAlias::CommandOptions Class Reference
Public Member Functions
CommandOptions ()=default
~CommandOptions () override=default
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext *execution_context) override
void OptionParsingStarting (ExecutionContext *execution_context) override
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Public Attributes
OptionValueString m_help
OptionValueString m_long_help
Detailed Description
Definition at line 190 of file CommandObjectCommands.cpp.
Constructor & Destructor Documentation
CommandOptions()
CommandObjectCommandsAlias::CommandOptions::CommandOptions () default
~CommandOptions()
CommandObjectCommandsAlias::CommandOptions::~CommandOptions () override default
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > CommandObjectCommandsAlias::CommandOptions::GetDefinitions () inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 196 of file CommandObjectCommands.cpp.
Referenced by SetOptionValue().
OptionParsingStarting()
void CommandObjectCommandsAlias::CommandOptions::OptionParsingStarting (ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 225 of file CommandObjectCommands.cpp.
References m_help, and m_long_help.
SetOptionValue()
Status CommandObjectCommandsAlias::CommandOptions::SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 200 of file CommandObjectCommands.cpp.
References error(), GetDefinitions(), m_help, and m_long_help.
Member Data Documentation
m_help
OptionValueString CommandObjectCommandsAlias::CommandOptions::m_help
Definition at line 230 of file CommandObjectCommands.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_long_help
OptionValueString CommandObjectCommandsAlias::CommandOptions::m_long_help
Definition at line 231 of file CommandObjectCommands.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following file:
CommandObjectCommands.cpp