LLDB: lldb_private::FormattersMatchData Class Reference
lldb_private::FormattersMatchData Class Reference
#include <FormatClasses.h>
Public Member Functions
FormattersMatchData (ValueObject &, lldb::DynamicValueType)
FormattersMatchVector GetMatchesVector ()
ConstString GetTypeForCache ()
CandidateLanguagesVector GetCandidateLanguages ()
ValueObject & GetValueObject ()
lldb::DynamicValueType GetDynamicValueType ()
Private Attributes
ValueObject & m_valobj
lldb::DynamicValueType m_dynamic_value_type
std::pair< FormattersMatchVector, bool > m_formatters_match_vector
ConstString m_type_for_cache
CandidateLanguagesVector m_candidate_languages
Detailed Description
Definition at line 130 of file FormatClasses.h.
Constructor & Destructor Documentation
FormattersMatchData()
FormattersMatchData::FormattersMatchData (ValueObject & valobj, lldb::DynamicValueType use_dynamic)
Definition at line 20 of file FormatClasses.cpp.
References m_dynamic_value_type, m_formatters_match_vector, and m_valobj.
Member Function Documentation
GetCandidateLanguages()
CandidateLanguagesVector FormattersMatchData::GetCandidateLanguages ()
Definition at line 41 of file FormatClasses.cpp.
References m_candidate_languages.
Referenced by lldb_private::FormatManager::Get(), and lldb_private::FormatManager::GetHardcoded().
GetDynamicValueType()
lldb::DynamicValueType FormattersMatchData::GetDynamicValueType ()
Definition at line 47 of file FormatClasses.cpp.
References m_dynamic_value_type.
Referenced by lldb_private::LanguageCategory::GetHardcoded().
GetMatchesVector()
FormattersMatchVector FormattersMatchData::GetMatchesVector ()
Definition at line 30 of file FormatClasses.cpp.
References lldb_private::FormatManager::GetPossibleMatches(), m_dynamic_value_type, m_formatters_match_vector, and m_valobj.
Referenced by lldb_private::LanguageCategory::Get(), and lldb_private::TypeCategoryMap::Get().
GetTypeForCache()
ConstString FormattersMatchData::GetTypeForCache ()
Definition at line 39 of file FormatClasses.cpp.
References m_type_for_cache.
Referenced by lldb_private::LanguageCategory::Get(), and lldb_private::FormatManager::GetCached().
GetValueObject()
ValueObject & FormattersMatchData::GetValueObject ()
Definition at line 45 of file FormatClasses.cpp.
References m_valobj.
Referenced by lldb_private::LanguageCategory::Get(), lldb_private::TypeCategoryMap::Get(), and lldb_private::LanguageCategory::GetHardcoded().
Member Data Documentation
m_candidate_languages
CandidateLanguagesVector lldb_private::FormattersMatchData::m_candidate_languages private
Definition at line 149 of file FormatClasses.h.
Referenced by GetCandidateLanguages().
m_dynamic_value_type
lldb::DynamicValueType lldb_private::FormattersMatchData::m_dynamic_value_type private
Definition at line 146 of file FormatClasses.h.
Referenced by FormattersMatchData(), GetDynamicValueType(), and GetMatchesVector().
m_formatters_match_vector
std::pair<FormattersMatchVector, bool> lldb_private::FormattersMatchData::m_formatters_match_vector private
Definition at line 147 of file FormatClasses.h.
Referenced by FormattersMatchData(), and GetMatchesVector().
m_type_for_cache
ConstString lldb_private::FormattersMatchData::m_type_for_cache private
Definition at line 148 of file FormatClasses.h.
Referenced by GetTypeForCache().
m_valobj
ValueObject& lldb_private::FormattersMatchData::m_valobj private
Definition at line 145 of file FormatClasses.h.
Referenced by FormattersMatchData(), GetMatchesVector(), and GetValueObject().
The documentation for this class was generated from the following files:
FormatClasses.h
FormatClasses.cpp