LLDB: lldb_private::ScriptedInterfaceUsages Class Reference
lldb_private::ScriptedInterfaceUsages Class Reference
#include <ScriptedInterfaceUsages.h>
Public Types
enum class UsageKind { CommandInterpreter , API }
Public Member Functions
ScriptedInterfaceUsages ()=default
ScriptedInterfaceUsages (const std::vector< llvm::StringRef > ci_usages, const std::vector< llvm::StringRef > sbapi_usages)
const std::vector< llvm::StringRef > & GetCommandInterpreterUsages () const
const std::vector< llvm::StringRef > & GetSBAPIUsages () const
void Dump (Stream &s, UsageKind kind) const
Private Attributes
std::vector< llvm::StringRef > m_command_interpreter_usages
std::vector< llvm::StringRef > m_sbapi_usages
Detailed Description
Definition at line 18 of file ScriptedInterfaceUsages.h.
Member Enumeration Documentation
UsageKind
enum class lldb_private::ScriptedInterfaceUsages::UsageKind strong
Enumerator
CommandInterpreter
API
Definition at line 33 of file ScriptedInterfaceUsages.h.
Constructor & Destructor Documentation
ScriptedInterfaceUsages() [1/2]
lldb_private::ScriptedInterfaceUsages::ScriptedInterfaceUsages () default
ScriptedInterfaceUsages() [2/2]
lldb_private::ScriptedInterfaceUsages::ScriptedInterfaceUsages (const std::vector< llvm::StringRef > ci_usages, const std::vector< llvm::StringRef > sbapi_usages) inline
Definition at line 21 of file ScriptedInterfaceUsages.h.
References m_command_interpreter_usages, and m_sbapi_usages.
Member Function Documentation
Dump()
void ScriptedInterfaceUsages::Dump (Stream & s, UsageKind kind) const
Definition at line 14 of file ScriptedInterfaceUsages.cpp.
References CommandInterpreter, GetCommandInterpreterUsages(), GetSBAPIUsages(), lldb_private::Stream::Indent(), lldb_private::Stream::IndentLess(), and lldb_private::Stream::IndentMore().
Referenced by CommandObjectScriptingExtensionList::DoExecute().
GetCommandInterpreterUsages()
const std::vector< llvm::StringRef > & lldb_private::ScriptedInterfaceUsages::GetCommandInterpreterUsages () const inline
Definition at line 25 of file ScriptedInterfaceUsages.h.
References m_command_interpreter_usages.
Referenced by Dump().
GetSBAPIUsages()
const std::vector< llvm::StringRef > & lldb_private::ScriptedInterfaceUsages::GetSBAPIUsages () const inline
Definition at line 29 of file ScriptedInterfaceUsages.h.
References m_sbapi_usages.
Referenced by Dump().
Member Data Documentation
m_command_interpreter_usages
std::vector<llvm::StringRef> lldb_private::ScriptedInterfaceUsages::m_command_interpreter_usages private
Definition at line 38 of file ScriptedInterfaceUsages.h.
Referenced by GetCommandInterpreterUsages(), and ScriptedInterfaceUsages().
m_sbapi_usages
std::vector<llvm::StringRef> lldb_private::ScriptedInterfaceUsages::m_sbapi_usages private
Definition at line 39 of file ScriptedInterfaceUsages.h.
Referenced by GetSBAPIUsages(), and ScriptedInterfaceUsages().
The documentation for this class was generated from the following files:
ScriptedInterfaceUsages.h
ScriptedInterfaceUsages.cpp