LLDB: lldb_private::npdb::PdbAstBuilder Class Reference
lldb_private::npdb::PdbAstBuilder Class Reference abstract
#include <PdbAstBuilder.h>
Public Member Functions
virtual ~PdbAstBuilder ()=default
virtual CompilerDecl GetOrCreateDeclForUid (PdbSymUid uid)=0
virtual CompilerDeclContext GetOrCreateDeclContextForUid (PdbSymUid uid)=0
virtual CompilerDeclContext GetParentDeclContext (PdbSymUid uid)=0
virtual void EnsureFunction (PdbCompilandSymId func_id)=0
virtual void EnsureInlinedFunction (PdbCompilandSymId inlinesite_id)=0
virtual void EnsureBlock (PdbCompilandSymId block_id)=0
virtual void EnsureVariable (PdbCompilandSymId scope_id, PdbCompilandSymId var_id)=0
virtual void EnsureVariable (PdbGlobalSymId var_id)=0
virtual CompilerType GetOrCreateType (PdbTypeSymId type)=0
virtual CompilerType GetOrCreateTypedefType (PdbGlobalSymId id)=0
virtual bool CompleteType (CompilerType ct)=0
virtual void ParseDeclsForContext (CompilerDeclContext context)=0
virtual CompilerDeclContext FindNamespaceDecl (CompilerDeclContext parent_ctx, llvm::StringRef name)=0
virtual void Dump (Stream &stream, llvm::StringRef filter, bool show_color)=0
Detailed Description
Definition at line 25 of file PdbAstBuilder.h.
Constructor & Destructor Documentation
~PdbAstBuilder()
virtual lldb_private::npdb::PdbAstBuilder::~PdbAstBuilder () virtual default
Member Function Documentation
CompleteType()
virtual bool lldb_private::npdb::PdbAstBuilder::CompleteType (CompilerType ct) pure virtual
Implemented in lldb_private::npdb::PdbAstBuilderClang.
Referenced by lldb_private::npdb::SymbolFileNativePDB::CompleteType().
Dump()
virtual void lldb_private::npdb::PdbAstBuilder::Dump (Stream & stream, llvm::StringRef filter, bool show_color) pure virtual
Implemented in lldb_private::npdb::PdbAstBuilderClang.
Referenced by lldb_private::npdb::SymbolFileNativePDB::DumpClangAST().
EnsureBlock()
virtual void lldb_private::npdb::PdbAstBuilder::EnsureBlock (PdbCompilandSymId block_id) pure virtual
Implemented in lldb_private::npdb::PdbAstBuilderClang.
Referenced by lldb_private::npdb::SymbolFileNativePDB::CreateBlock().
EnsureFunction()
virtual void lldb_private::npdb::PdbAstBuilder::EnsureFunction (PdbCompilandSymId func_id) pure virtual
Implemented in lldb_private::npdb::PdbAstBuilderClang.
EnsureInlinedFunction()
virtual void lldb_private::npdb::PdbAstBuilder::EnsureInlinedFunction (PdbCompilandSymId inlinesite_id) pure virtual
Implemented in lldb_private::npdb::PdbAstBuilderClang.
Referenced by lldb_private::npdb::SymbolFileNativePDB::CreateBlock().
EnsureVariable() [1/2]
virtual void lldb_private::npdb::PdbAstBuilder::EnsureVariable (PdbCompilandSymId scope_id, PdbCompilandSymId var_id) pure virtual
Implemented in lldb_private::npdb::PdbAstBuilderClang.
EnsureVariable() [2/2]
virtual void lldb_private::npdb::PdbAstBuilder::EnsureVariable (PdbGlobalSymId var_id) pure virtual
Implemented in lldb_private::npdb::PdbAstBuilderClang.
FindNamespaceDecl()
virtual CompilerDeclContext lldb_private::npdb::PdbAstBuilder::FindNamespaceDecl (CompilerDeclContext parent_ctx, llvm::StringRef name) pure virtual
Implemented in lldb_private::npdb::PdbAstBuilderClang.
Referenced by lldb_private::npdb::SymbolFileNativePDB::FindNamespace().
GetOrCreateDeclContextForUid()
virtual CompilerDeclContext lldb_private::npdb::PdbAstBuilder::GetOrCreateDeclContextForUid (PdbSymUid uid) pure virtual
Implemented in lldb_private::npdb::PdbAstBuilderClang.
Referenced by lldb_private::npdb::SymbolFileNativePDB::GetDeclContextForUID().
GetOrCreateDeclForUid()
virtual CompilerDecl lldb_private::npdb::PdbAstBuilder::GetOrCreateDeclForUid (PdbSymUid uid) pure virtual
Implemented in lldb_private::npdb::PdbAstBuilderClang.
Referenced by lldb_private::npdb::SymbolFileNativePDB::GetDeclForUID().
GetOrCreateType()
virtual CompilerType lldb_private::npdb::PdbAstBuilder::GetOrCreateType (PdbTypeSymId type) pure virtual
Implemented in lldb_private::npdb::PdbAstBuilderClang.
Referenced by lldb_private::npdb::SymbolFileNativePDB::CreateAndCacheType().
GetOrCreateTypedefType()
virtual CompilerType lldb_private::npdb::PdbAstBuilder::GetOrCreateTypedefType (PdbGlobalSymId id) pure virtual
Implemented in lldb_private::npdb::PdbAstBuilderClang.
Referenced by lldb_private::npdb::SymbolFileNativePDB::CreateTypedef().
GetParentDeclContext()
virtual CompilerDeclContext lldb_private::npdb::PdbAstBuilder::GetParentDeclContext (PdbSymUid uid) pure virtual
Implemented in lldb_private::npdb::PdbAstBuilderClang.
Referenced by lldb_private::npdb::SymbolFileNativePDB::GetDeclContextContainingUID().
ParseDeclsForContext()
virtual void lldb_private::npdb::PdbAstBuilder::ParseDeclsForContext (CompilerDeclContext context) pure virtual
Implemented in lldb_private::npdb::PdbAstBuilderClang.
Referenced by lldb_private::npdb::SymbolFileNativePDB::ParseDeclsForContext().
The documentation for this class was generated from the following file:
PdbAstBuilder.h