LLDB: lldb_private::ScriptedSyntheticChildren Class Reference
lldb_private::ScriptedSyntheticChildren Class Reference
#include <TypeSynthetic.h>
Classes
class FrontEnd
Public Member Functions
ScriptedSyntheticChildren (const SyntheticChildren::Flags &flags, const char *pclass, const char *pcode=nullptr)
const char * GetPythonClassName ()
const char * GetPythonCode ()
void SetPythonClassName (const char *fname)
void SetPythonCode (const char *script)
std::string GetDescription () override
bool IsScripted () override
SyntheticChildrenFrontEnd::UniquePointer GetFrontEnd (ValueObject &backend) override
Public Member Functions inherited from lldb_private::SyntheticChildren
SyntheticChildren (const Flags &flags)
virtual ~SyntheticChildren ()
bool Cascades () const
bool SkipsPointers () const
bool SkipsReferences () const
bool NonCacheable () const
bool WantsDereference () const
void SetCascades (bool value)
void SetSkipsPointers (bool value)
void SetSkipsReferences (bool value)
void SetNonCacheable (bool value)
uint32_t GetOptions ()
void SetOptions (uint32_t value)
uint32_t & GetRevision ()
uint32_t GetPtrMatchDepth ()
void SetPtrMatchDepth (uint32_t value)
Private Member Functions
ScriptedSyntheticChildren (const ScriptedSyntheticChildren &)=delete
const ScriptedSyntheticChildren & operator= (const ScriptedSyntheticChildren &)=delete
Private Attributes
std::string m_python_class
std::string m_python_code
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildren
typedef std::shared_ptr< SyntheticChildren > SharedPointer
Protected Attributes inherited from lldb_private::SyntheticChildren
uint32_t m_my_revision = 0
Flags m_flags
uint32_t m_ptr_match_depth = 1
Detailed Description
Definition at line 400 of file TypeSynthetic.h.
Constructor & Destructor Documentation
ScriptedSyntheticChildren() [1/2]
lldb_private::ScriptedSyntheticChildren::ScriptedSyntheticChildren (const SyntheticChildren::Flags & flags, const char * pclass, const char * pcode = nullptr) inline
Definition at line 405 of file TypeSynthetic.h.
References m_python_class, m_python_code, and lldb_private::SyntheticChildren::SyntheticChildren().
Referenced by operator=(), and ScriptedSyntheticChildren().
ScriptedSyntheticChildren() [2/2]
lldb_private::ScriptedSyntheticChildren::ScriptedSyntheticChildren (const ScriptedSyntheticChildren &) private delete
References ScriptedSyntheticChildren().
Member Function Documentation
GetDescription()
std::string ScriptedSyntheticChildren::GetDescription () override virtual
Implements lldb_private::SyntheticChildren.
Definition at line 248 of file TypeSynthetic.cpp.
References lldb_private::SyntheticChildren::Cascades(), lldb_private::StreamString::GetString(), m_python_class, lldb_private::Stream::Printf(), lldb_private::SyntheticChildren::SkipsPointers(), and lldb_private::SyntheticChildren::SkipsReferences().
GetFrontEnd()
SyntheticChildrenFrontEnd::UniquePointer lldb_private::ScriptedSyntheticChildren::GetFrontEnd (ValueObject & backend) inline override virtual
Implements lldb_private::SyntheticChildren.
Definition at line 465 of file TypeSynthetic.h.
References m_python_class.
GetPythonClassName()
const char * lldb_private::ScriptedSyntheticChildren::GetPythonClassName () inline
Definition at line 414 of file TypeSynthetic.h.
References m_python_class.
GetPythonCode()
const char * lldb_private::ScriptedSyntheticChildren::GetPythonCode () inline
Definition at line 416 of file TypeSynthetic.h.
References m_python_code.
IsScripted()
bool lldb_private::ScriptedSyntheticChildren::IsScripted () inline override virtual
Implements lldb_private::SyntheticChildren.
Definition at line 427 of file TypeSynthetic.h.
operator=()
const ScriptedSyntheticChildren & lldb_private::ScriptedSyntheticChildren::operator= (const ScriptedSyntheticChildren &) private delete
References ScriptedSyntheticChildren().
SetPythonClassName()
void lldb_private::ScriptedSyntheticChildren::SetPythonClassName (const char * fname) inline
Definition at line 418 of file TypeSynthetic.h.
References m_python_class, and m_python_code.
SetPythonCode()
void lldb_private::ScriptedSyntheticChildren::SetPythonCode (const char * script) inline
Definition at line 423 of file TypeSynthetic.h.
References m_python_code.
Member Data Documentation
m_python_class
std::string lldb_private::ScriptedSyntheticChildren::m_python_class private
Definition at line 401 of file TypeSynthetic.h.
Referenced by GetDescription(), GetFrontEnd(), GetPythonClassName(), ScriptedSyntheticChildren(), and SetPythonClassName().
m_python_code
std::string lldb_private::ScriptedSyntheticChildren::m_python_code private
Definition at line 402 of file TypeSynthetic.h.
Referenced by GetPythonCode(), ScriptedSyntheticChildren(), SetPythonClassName(), and SetPythonCode().
The documentation for this class was generated from the following files:
TypeSynthetic.h
TypeSynthetic.cpp