LLDB: lldb_private::trace_intel_pt::ThreadDecoder Class Reference
lldb_private::trace_intel_pt::ThreadDecoder Class Reference
Class that handles the decoding of a thread and caches the result.
#include <ThreadDecoder.h>
Public Member Functions
ThreadDecoder (const lldb::ThreadSP &thread_sp, TraceIntelPT &trace)
llvm::Expected< DecodedThreadSP > Decode ()
Decode the thread and store the result internally, to avoid recomputations.
llvm::Expected< std::optional< uint64_t > > FindLowestTSC ()
ThreadDecoder (const ThreadDecoder &other)=delete
ThreadDecoder & operator= (const ThreadDecoder &other)=delete
Private Member Functions
llvm::Expected< DecodedThreadSP > DoDecode ()
Private Attributes
lldb::ThreadSP m_thread_sp
TraceIntelPT & m_trace
std::optional< DecodedThreadSP > m_decoded_thread
Detailed Description
Class that handles the decoding of a thread and caches the result.
Definition at line 23 of file ThreadDecoder.h.
Constructor & Destructor Documentation
ThreadDecoder() [1/2]
ThreadDecoder::ThreadDecoder (const lldb::ThreadSP & thread_sp, TraceIntelPT & trace)
Parameters
[in] thread_sp The thread whose intel pt trace buffer will be decoded.
[in] trace The main Trace object who owns this decoder and its data.
Definition at line 21 of file ThreadDecoder.cpp.
References m_thread_sp, and m_trace.
Referenced by operator=(), and ThreadDecoder().
ThreadDecoder() [2/2]
lldb_private::trace_intel_pt::ThreadDecoder::ThreadDecoder (const ThreadDecoder & other) delete
References ThreadDecoder().
Member Function Documentation
Decode()
Expected< DecodedThreadSP > ThreadDecoder::Decode ()
Decode the thread and store the result internally, to avoid recomputations.
Returns
A DecodedThread instance.
Definition at line 40 of file ThreadDecoder.cpp.
References DoDecode(), and m_decoded_thread.
DoDecode()
llvm::Expected< DecodedThreadSP > ThreadDecoder::DoDecode () private
Definition at line 51 of file ThreadDecoder.cpp.
References m_thread_sp, and m_trace.
Referenced by Decode().
FindLowestTSC()
Expected< std::optional< uint64_t > > ThreadDecoder::FindLowestTSC ()
Returns
The lowest TSC value in this trace if available, std::nullopt if the trace is empty or the trace contains no timing information, or an llvm::Error if it was not possible to set up the decoder.
Definition at line 24 of file ThreadDecoder.cpp.
References m_thread_sp, and m_trace.
operator=()
ThreadDecoder & lldb_private::trace_intel_pt::ThreadDecoder::operator= (const ThreadDecoder & other) delete
References ThreadDecoder().
Member Data Documentation
m_decoded_thread
std::optional<DecodedThreadSP> lldb_private::trace_intel_pt::ThreadDecoder::m_decoded_thread private
Definition at line 53 of file ThreadDecoder.h.
Referenced by Decode().
m_thread_sp
lldb::ThreadSP lldb_private::trace_intel_pt::ThreadDecoder::m_thread_sp private
Definition at line 51 of file ThreadDecoder.h.
Referenced by DoDecode(), FindLowestTSC(), and ThreadDecoder().
m_trace
TraceIntelPT& lldb_private::trace_intel_pt::ThreadDecoder::m_trace private
Definition at line 52 of file ThreadDecoder.h.
Referenced by DoDecode(), FindLowestTSC(), and ThreadDecoder().
The documentation for this class was generated from the following files:
ThreadDecoder.h
ThreadDecoder.cpp