LLDB: lldb_private::EmulateInstructionARM Class Reference
lldb_private::EmulateInstructionARM Class Reference
#include <EmulateInstructionARM.h>
Classes
struct AddWithCarryResult
struct ARMOpcode
Public Types
enum ARMEncoding {
eEncodingA1 , eEncodingA2 , eEncodingA3 , eEncodingA4 ,
eEncodingA5 , eEncodingT1 , eEncodingT2 , eEncodingT3 ,
eEncodingT4 , eEncodingT5
}
enum Mode { eModeInvalid = -1 , eModeARM , eModeThumb }
Public Types inherited from lldb_private::EmulateInstruction
enum ContextType {
eContextInvalid = 0 , eContextReadOpcode , eContextImmediate , eContextPushRegisterOnStack ,
eContextPopRegisterOffStack , eContextAdjustStackPointer , eContextSetFramePointer , eContextRestoreStackPointer ,
eContextAdjustBaseRegister , eContextAdjustPC , eContextRegisterPlusOffset , eContextRegisterStore ,
eContextRegisterLoad , eContextRelativeBranchImmediate , eContextAbsoluteBranchRegister , eContextSupervisorCall ,
eContextTableBranchReadMemory , eContextWriteRegisterRandomBits , eContextWriteMemoryRandomBits , eContextArithmetic ,
eContextAdvancePC , eContextReturnFromException
}
enum InfoType {
eInfoTypeRegisterPlusOffset , eInfoTypeRegisterPlusIndirectOffset , eInfoTypeRegisterToRegisterPlusOffset , eInfoTypeRegisterToRegisterPlusIndirectOffset ,
eInfoTypeRegisterRegisterOperands , eInfoTypeOffset , eInfoTypeRegister , eInfoTypeImmediate ,
eInfoTypeImmediateSigned , eInfoTypeAddress , eInfoTypeISAAndImmediate , eInfoTypeISAAndImmediateSigned ,
eInfoTypeISA , eInfoTypeNoArgs
}
typedef size_t(* ReadMemoryCallback) (EmulateInstruction *instruction, void *baton, const Context &context, lldb::addr_t addr, void *dst, size_t length)
typedef size_t(* WriteMemoryCallback) (EmulateInstruction *instruction, void *baton, const Context &context, lldb::addr_t addr, const void *dst, size_t length)
typedef bool(* ReadRegisterCallback) (EmulateInstruction *instruction, void *baton, const RegisterInfo *reg_info, RegisterValue &reg_value)
typedef bool(* WriteRegisterCallback) (EmulateInstruction *instruction, void *baton, const Context &context, const RegisterInfo *reg_info, const RegisterValue &reg_value)
typedef uint32_t InstructionCondition
Public Member Functions
llvm::StringRef GetPluginName () override
bool SetTargetTriple (const ArchSpec &arch) override
EmulateInstructionARM (const ArchSpec &arch)
bool SupportsEmulatingInstructionsOfType (InstructionType inst_type) override
virtual bool SetArchitecture (const ArchSpec &arch)
bool ReadInstruction () override
bool SetInstruction (const Opcode &insn_opcode, const Address &inst_addr, Target *target) override
bool EvaluateInstruction (uint32_t evaluate_options) override
InstructionCondition GetInstructionCondition () override
bool TestEmulation (Stream &out_stream, ArchSpec &arch, OptionValueDictionary *test_data) override
std::optional< RegisterInfo > GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num) override
bool CreateFunctionEntryUnwind (UnwindPlan &unwind_plan) override
uint32_t ArchVersion ()
bool ConditionPassed (const uint32_t opcode)
uint32_t CurrentCond (const uint32_t opcode)
bool InITBlock ()
bool LastInITBlock ()
bool BadMode (uint32_t mode)
bool CurrentModeIsPrivileged ()
void CPSRWriteByInstr (uint32_t value, uint32_t bytemask, bool affect_execstate)
bool BranchWritePC (const Context &context, uint32_t addr)
bool BXWritePC (Context &context, uint32_t addr)
bool LoadWritePC (Context &context, uint32_t addr)
bool ALUWritePC (Context &context, uint32_t addr)
Mode CurrentInstrSet ()
bool SelectInstrSet (Mode arm_or_thumb)
bool WriteBits32Unknown (int n)
bool WriteBits32UnknownToMemory (lldb::addr_t address)
bool UnalignedSupport ()
AddWithCarryResult AddWithCarry (uint32_t x, uint32_t y, uint8_t carry_in)
uint32_t ReadCoreReg (uint32_t regnum, bool *success)
bool WriteCoreRegOptionalFlags (Context &context, const uint32_t result, const uint32_t Rd, bool setflags, const uint32_t carry=~0u, const uint32_t overflow=~0u)
bool WriteCoreReg (Context &context, const uint32_t result, const uint32_t Rd)
bool WriteFlags (Context &context, const uint32_t result, const uint32_t carry=~0u, const uint32_t overflow=~0u)
uint64_t MemARead (EmulateInstruction::Context &context, lldb::addr_t address, uint32_t size, uint64_t fail_value, bool *success_ptr)
bool MemAWrite (EmulateInstruction::Context &context, lldb::addr_t address, uint64_t data_val, uint32_t size)
uint64_t MemURead (EmulateInstruction::Context &context, lldb::addr_t address, uint32_t size, uint64_t fail_value, bool *success_ptr)
bool MemUWrite (EmulateInstruction::Context &context, lldb::addr_t address, uint64_t data_val, uint32_t size)
Public Member Functions inherited from lldb_private::EmulateInstruction
EmulateInstruction (const ArchSpec &arch)
~EmulateInstruction () override=default
virtual std::optional< uint32_t > GetLastInstrSize ()
std::optional< RegisterValue > ReadRegister (const RegisterInfo &reg_info)
uint64_t ReadRegisterUnsigned (const RegisterInfo &reg_info, uint64_t fail_value, bool *success_ptr)
bool WriteRegister (const Context &context, const RegisterInfo &ref_info, const RegisterValue &reg_value)
bool WriteRegisterUnsigned (const Context &context, const RegisterInfo &reg_info, uint64_t reg_value)
bool ReadRegister (lldb::RegisterKind reg_kind, uint32_t reg_num, RegisterValue &reg_value)
bool WriteRegister (const Context &context, lldb::RegisterKind reg_kind, uint32_t reg_num, const RegisterValue &reg_value)
uint64_t ReadRegisterUnsigned (lldb::RegisterKind reg_kind, uint32_t reg_num, uint64_t fail_value, bool *success_ptr)
bool WriteRegisterUnsigned (const Context &context, lldb::RegisterKind reg_kind, uint32_t reg_num, uint64_t reg_value)
size_t ReadMemory (const Context &context, lldb::addr_t addr, void *dst, size_t dst_len)
uint64_t ReadMemoryUnsigned (const Context &context, lldb::addr_t addr, size_t byte_size, uint64_t fail_value, bool *success_ptr)
bool WriteMemory (const Context &context, lldb::addr_t addr, const void *src, size_t src_len)
bool WriteMemoryUnsigned (const Context &context, lldb::addr_t addr, uint64_t uval, size_t uval_byte_size)
uint32_t GetAddressByteSize () const
lldb::ByteOrder GetByteOrder () const
const Opcode & GetOpcode () const
lldb::addr_t GetAddress () const
const ArchSpec & GetArchitecture () const
void SetBaton (void *baton)
void SetCallbacks (ReadMemoryCallback read_mem_callback, WriteMemoryCallback write_mem_callback, ReadRegisterCallback read_reg_callback, WriteRegisterCallback write_reg_callback)
void SetReadMemCallback (ReadMemoryCallback read_mem_callback)
void SetWriteMemCallback (WriteMemoryCallback write_mem_callback)
void SetReadRegCallback (ReadRegisterCallback read_reg_callback)
void SetWriteRegCallback (WriteRegisterCallback write_reg_callback)
std::optional< lldb::addr_t > ReadPC ()
bool WritePC (lldb::addr_t addr)
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static lldb_private::EmulateInstruction * CreateInstance (const lldb_private::ArchSpec &arch, InstructionType inst_type)
static bool SupportsEmulatingInstructionsOfTypeStatic (InstructionType inst_type)
Static Public Member Functions inherited from lldb_private::EmulateInstruction
static EmulateInstruction * FindPlugin (const ArchSpec &arch, InstructionType supported_inst_type, const char *plugin_name)
static const char * TranslateRegister (lldb::RegisterKind reg_kind, uint32_t reg_num, std::string &reg_name)
static size_t ReadMemoryFrame (EmulateInstruction *instruction, void *baton, const Context &context, lldb::addr_t addr, void *dst, size_t length)
static size_t WriteMemoryFrame (EmulateInstruction *instruction, void *baton, const Context &context, lldb::addr_t addr, const void *dst, size_t length)
static bool ReadRegisterFrame (EmulateInstruction *instruction, void *baton, const RegisterInfo *reg_info, RegisterValue &reg_value)
static bool WriteRegisterFrame (EmulateInstruction *instruction, void *baton, const Context &context, const RegisterInfo *reg_info, const RegisterValue &reg_value)
static size_t ReadMemoryDefault (EmulateInstruction *instruction, void *baton, const Context &context, lldb::addr_t addr, void *dst, size_t length)
static size_t WriteMemoryDefault (EmulateInstruction *instruction, void *baton, const Context &context, lldb::addr_t addr, const void *dst, size_t length)
static bool ReadRegisterDefault (EmulateInstruction *instruction, void *baton, const RegisterInfo *reg_info, RegisterValue &reg_value)
static bool WriteRegisterDefault (EmulateInstruction *instruction, void *baton, const Context &context, const RegisterInfo *reg_info, const RegisterValue &reg_value)
static bool GetBestRegisterKindAndNumber (const RegisterInfo *reg_info, lldb::RegisterKind &reg_kind, uint32_t &reg_num)
static uint32_t GetInternalRegisterNumber (RegisterContext *reg_ctx, const RegisterInfo &reg_info)
static std::unique_ptr< SingleStepBreakpointLocationsPredictor > CreateBreakpointLocationPredictor (std::unique_ptr< EmulateInstruction > emulator_up)
Protected Types
enum ARMInstrSize { eSize16 , eSize32 }
Protected Types inherited from lldb_private::EmulateInstruction
using BreakpointLocationsPredictorCreator
Protected Member Functions
uint32_t GetFramePointerRegisterNumber () const
uint32_t GetFramePointerDWARFRegisterNumber () const
bool EmulatePUSH (const uint32_t opcode, const ARMEncoding encoding)
bool EmulatePOP (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateADDRdSPImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateMOVRdSP (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateMOVLowHigh (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRRtPCRelative (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateADDSPImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateADDSPRm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateBLXImmediate (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateBLXRm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateBXRm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateBXJRm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSUBR7IPImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSUBIPSPImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSUBSPImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSUBSPReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTRRtSP (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateVPUSH (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateVPOP (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSVC (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateIT (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateNop (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateB (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateCB (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateTB (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateADDImmThumb (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateADDImmARM (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateADDReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateADDRegShift (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateMOVRdRm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateMOVRdImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateCMPImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateCMPReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateASRImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateASRReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLSLImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLSLReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLSRImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLSRReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateRORImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateRORReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateRRX (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateShiftImm (const uint32_t opcode, const ARMEncoding encoding, ARM_ShifterType shift_type)
bool EmulateShiftReg (const uint32_t opcode, const ARMEncoding encoding, ARM_ShifterType shift_type)
bool EmulateLDM (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDMDA (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDMDB (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDMIB (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRRtRnImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRImmediateARM (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRLiteral (const uint32_t, const ARMEncoding encoding)
bool EmulateLDRRegister (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRBImmediate (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRBImmediateARM (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRBLiteral (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRBRegister (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRBT (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRDImmediate (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRDLiteral (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRDRegister (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDREX (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDREXB (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDREXD (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDREXH (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRHImmediate (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRHImmediateARM (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRHLiteral (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRHRegister (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRHT (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRSBImmediate (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRSBLiteral (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRSBRegister (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRSBT (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRSHImmediate (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRSHLiteral (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRSHRegister (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRSHT (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateLDRT (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTM (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTMDA (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTMDB (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTMIB (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTRThumb (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTRImmARM (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTRRegister (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTRBThumb (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTRBImmARM (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTRBReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTRBT (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTRDImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTRDReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTREX (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTREXB (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTREXD (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTREXH (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTRHImmThumb (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTRHImmARM (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTRHRegister (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTRHT (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSTRT (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateADCImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateADCReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateADR (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateANDImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateANDReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateBICImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateBICReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateBXJ (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateCMNImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateCMNReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateEORImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateEORReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateMUL (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateMVNImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateMVNReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateORRImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateORRReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulatePLDImmediate (const uint32_t opcode, const ARMEncoding encoding)
bool EmulatePLIImmediate (const uint32_t opcode, const ARMEncoding encoding)
bool EmulatePLIRegister (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateRSBImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateRSBReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateRSCImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateRSCReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSBCImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSBCReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSUBImmThumb (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSUBImmARM (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSUBReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSUBRegShift (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSXTB (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSXTH (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateTEQImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateTEQReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateTSTImm (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateTSTReg (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateUXTB (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateUXTH (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateRFE (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateVLDM (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateVSTM (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateVLD1Multiple (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateVLD1Single (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateVLD1SingleAll (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateVST1Multiple (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateVST1Single (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateVLDR (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateVSTR (const uint32_t opcode, const ARMEncoding encoding)
bool EmulateSUBSPcLrEtc (const uint32_t opcode, const ARMEncoding encoding)
BreakpointLocationsPredictorCreator GetSingleStepBreakpointLocationsPredictorCreator () override
Static Protected Member Functions
static ARMOpcode * GetARMOpcodeForInstruction (const uint32_t opcode, uint32_t isa_mask)
static ARMOpcode * GetThumbOpcodeForInstruction (const uint32_t opcode, uint32_t isa_mask)
Protected Attributes
uint32_t m_arm_isa
Mode m_opcode_mode
uint32_t m_opcode_cpsr
uint32_t m_new_inst_cpsr
ITSession m_it_session
bool m_ignore_conditions
Protected Attributes inherited from lldb_private::EmulateInstruction
ArchSpec m_arch
void * m_baton = nullptr
ReadMemoryCallback m_read_mem_callback = &ReadMemoryDefault
WriteMemoryCallback m_write_mem_callback = &WriteMemoryDefault
ReadRegisterCallback m_read_reg_callback = &ReadRegisterDefault
WriteRegisterCallback m_write_reg_callback = &WriteRegisterDefault
lldb::addr_t m_addr = LLDB_INVALID_ADDRESS
Opcode m_opcode
Additional Inherited Members
Static Public Attributes inherited from lldb_private::EmulateInstruction
static const InstructionCondition UnconditionalCondition = UINT32_MAX
Detailed Description
Definition at line 56 of file EmulateInstructionARM.h.
Member Enumeration Documentation
ARMEncoding
enum lldb_private::EmulateInstructionARM::ARMEncoding
Enumerator
eEncodingA1
eEncodingA2
eEncodingA3
eEncodingA4
eEncodingA5
eEncodingT1
eEncodingT2
eEncodingT3
eEncodingT4
eEncodingT5
Definition at line 58 of file EmulateInstructionARM.h.
ARMInstrSize
enum lldb_private::EmulateInstructionARM::ARMInstrSize protected
Enumerator
eSize16
eSize32
Definition at line 301 of file EmulateInstructionARM.h.
Mode
enum lldb_private::EmulateInstructionARM::Mode
Enumerator
eModeInvalid
eModeARM
eModeThumb
Definition at line 100 of file EmulateInstructionARM.h.
Constructor & Destructor Documentation
EmulateInstructionARM()
lldb_private::EmulateInstructionARM::EmulateInstructionARM (const ArchSpec & arch) inline
Definition at line 102 of file EmulateInstructionARM.h.
References eModeInvalid, lldb_private::EmulateInstruction::EmulateInstruction(), m_arm_isa, m_ignore_conditions, m_it_session, m_new_inst_cpsr, m_opcode_cpsr, m_opcode_mode, and SetArchitecture().
Referenced by CreateInstance().
Member Function Documentation
AddWithCarry()
EmulateInstructionARM::AddWithCarryResult EmulateInstructionARM::AddWithCarry (uint32_t x, uint32_t y, uint8_t carry_in)
Definition at line 14132 of file EmulateInstructionARM.cpp.
References lldb_private::UnsignedBits().
Referenced by EmulateADCImm(), EmulateADCReg(), EmulateADDImmARM(), EmulateADDImmThumb(), EmulateADDRdSPImm(), EmulateADDReg(), EmulateADDRegShift(), EmulateADDSPImm(), EmulateADDSPRm(), EmulateCMNImm(), EmulateCMNReg(), EmulateCMPImm(), EmulateCMPReg(), EmulateRSBImm(), EmulateRSBReg(), EmulateRSCImm(), EmulateRSCReg(), EmulateSBCImm(), EmulateSBCReg(), EmulateSUBImmARM(), EmulateSUBImmThumb(), EmulateSUBIPSPImm(), EmulateSUBR7IPImm(), EmulateSUBReg(), EmulateSUBSPcLrEtc(), EmulateSUBSPImm(), and EmulateSUBSPReg().
ALUWritePC()
bool EmulateInstructionARM::ALUWritePC (Context & context, uint32_t addr)
Definition at line 14089 of file EmulateInstructionARM.cpp.
References ArchVersion(), ARMv7, BranchWritePC(), BXWritePC(), CurrentInstrSet(), and eModeARM.
Referenced by EmulateADCImm(), EmulateADCReg(), EmulateADDImmARM(), EmulateADDRdSPImm(), EmulateADDReg(), EmulateADDSPImm(), EmulateADDSPRm(), EmulateADR(), EmulateANDImm(), EmulateANDReg(), EmulateASRImm(), EmulateBICImm(), EmulateBICReg(), EmulateEORImm(), EmulateEORReg(), EmulateLSLImm(), EmulateLSRImm(), EmulateMOVRdImm(), EmulateMOVRdRm(), EmulateMOVRdSP(), EmulateMVNImm(), EmulateMVNReg(), EmulateORRImm(), EmulateORRReg(), EmulateRORImm(), EmulateRRX(), EmulateRSBImm(), EmulateRSBReg(), EmulateRSCImm(), EmulateRSCReg(), EmulateSBCImm(), EmulateSBCReg(), EmulateSUBImmARM(), EmulateSUBIPSPImm(), EmulateSUBR7IPImm(), EmulateSUBReg(), EmulateSUBSPImm(), EmulateSUBSPReg(), and WriteCoreRegOptionalFlags().
ArchVersion()
uint32_t EmulateInstructionARM::ArchVersion ()
Definition at line 13842 of file EmulateInstructionARM.cpp.
References m_arm_isa.
Referenced by ALUWritePC(), EmulateLDRDRegister(), EmulateMUL(), EmulatePOP(), EmulateSTRDReg(), LoadWritePC(), and UnalignedSupport().
BadMode()
bool EmulateInstructionARM::BadMode (uint32_t mode)
Definition at line 13956 of file EmulateInstructionARM.cpp.
Referenced by CurrentModeIsPrivileged().
BranchWritePC()
bool EmulateInstructionARM::BranchWritePC (const Context & context, uint32_t addr)
Definition at line 14029 of file EmulateInstructionARM.cpp.
References CurrentInstrSet(), eModeARM, lldb::eRegisterKindGeneric, LLDB_REGNUM_GENERIC_PC, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by ALUWritePC(), EmulateB(), EmulateBLXImmediate(), EmulateCB(), EmulateRFE(), EmulateSUBSPcLrEtc(), EmulateTB(), and LoadWritePC().
BXWritePC()
bool EmulateInstructionARM::BXWritePC (Context & context, uint32_t addr)
Definition at line 14045 of file EmulateInstructionARM.cpp.
References lldb_private::BitIsClear(), lldb_private::BitIsSet(), CurrentInstrSet(), eModeARM, eModeThumb, lldb::eRegisterKindGeneric, LLDB_REGNUM_GENERIC_FLAGS, LLDB_REGNUM_GENERIC_PC, m_new_inst_cpsr, SelectInstrSet(), lldb_private::EmulateInstruction::Context::SetISA(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by ALUWritePC(), EmulateBLXRm(), EmulateBXJRm(), EmulateBXRm(), and LoadWritePC().
ConditionPassed()
bool EmulateInstructionARM::ConditionPassed (const uint32_t opcode)
Definition at line 13844 of file EmulateInstructionARM.cpp.
References CurrentCond(), m_ignore_conditions, m_opcode_cpsr, MASK_CPSR_C, MASK_CPSR_N, MASK_CPSR_V, MASK_CPSR_Z, UINT32_MAX, and lldb_private::UnsignedBits().
Referenced by EmulateADCImm(), EmulateADCReg(), EmulateADDImmARM(), EmulateADDImmThumb(), EmulateADDRdSPImm(), EmulateADDReg(), EmulateADDRegShift(), EmulateADDSPImm(), EmulateADDSPRm(), EmulateADR(), EmulateANDImm(), EmulateANDReg(), EmulateASRImm(), EmulateASRReg(), EmulateB(), EmulateBICImm(), EmulateBICReg(), EmulateBLXImmediate(), EmulateBLXRm(), EmulateBXJRm(), EmulateBXRm(), EmulateCMNImm(), EmulateCMNReg(), EmulateCMPImm(), EmulateCMPReg(), EmulateEORImm(), EmulateEORReg(), EmulateLDM(), EmulateLDMDA(), EmulateLDMDB(), EmulateLDMIB(), EmulateLDRBImmediate(), EmulateLDRBLiteral(), EmulateLDRBRegister(), EmulateLDRDImmediate(), EmulateLDRDRegister(), EmulateLDRHImmediate(), EmulateLDRHLiteral(), EmulateLDRHRegister(), EmulateLDRImmediateARM(), EmulateLDRRegister(), EmulateLDRRtPCRelative(), EmulateLDRRtRnImm(), EmulateLDRSBImmediate(), EmulateLDRSBLiteral(), EmulateLDRSBRegister(), EmulateLDRSHImmediate(), EmulateLDRSHLiteral(), EmulateLDRSHRegister(), EmulateLSLImm(), EmulateLSLReg(), EmulateLSRImm(), EmulateLSRReg(), EmulateMOVRdImm(), EmulateMOVRdRm(), EmulateMOVRdSP(), EmulateMUL(), EmulateMVNImm(), EmulateMVNReg(), EmulateORRImm(), EmulateORRReg(), EmulatePOP(), EmulatePUSH(), EmulateRFE(), EmulateRORImm(), EmulateRORReg(), EmulateRRX(), EmulateRSBImm(), EmulateRSBReg(), EmulateRSCImm(), EmulateRSCReg(), EmulateSBCImm(), EmulateSBCReg(), EmulateShiftImm(), EmulateShiftReg(), EmulateSTM(), EmulateSTMDA(), EmulateSTMDB(), EmulateSTMIB(), EmulateSTRBImmARM(), EmulateSTRBThumb(), EmulateSTRDImm(), EmulateSTRDReg(), EmulateSTREX(), EmulateSTRHRegister(), EmulateSTRImmARM(), EmulateSTRRegister(), EmulateSTRRtSP(), EmulateSTRThumb(), EmulateSUBImmARM(), EmulateSUBImmThumb(), EmulateSUBIPSPImm(), EmulateSUBR7IPImm(), EmulateSUBReg(), EmulateSUBSPcLrEtc(), EmulateSUBSPImm(), EmulateSUBSPReg(), EmulateSVC(), EmulateSXTB(), EmulateSXTH(), EmulateTB(), EmulateTEQImm(), EmulateTEQReg(), EmulateTSTImm(), EmulateTSTReg(), EmulateUXTB(), EmulateUXTH(), EmulateVLD1Multiple(), EmulateVLD1Single(), EmulateVLD1SingleAll(), EmulateVLDM(), EmulateVLDR(), EmulateVPOP(), EmulateVPUSH(), EmulateVST1Multiple(), EmulateVST1Single(), EmulateVSTM(), and EmulateVSTR().
CPSRWriteByInstr()
void EmulateInstructionARM::CPSRWriteByInstr (uint32_t value, uint32_t bytemask, bool affect_execstate)
Definition at line 13993 of file EmulateInstructionARM.cpp.
References lldb_private::Bit32(), lldb_private::BitIsSet(), lldb_private::Bits32(), CurrentModeIsPrivileged(), and m_opcode_cpsr.
Referenced by EmulateRFE(), and EmulateSUBSPcLrEtc().
CreateFunctionEntryUnwind()
bool EmulateInstructionARM::CreateFunctionEntryUnwind (UnwindPlan & unwind_plan) override virtual
Reimplemented from lldb_private::EmulateInstruction.
Definition at line 14463 of file EmulateInstructionARM.cpp.
References lldb_private::UnwindPlan::AppendRow(), lldb_private::UnwindPlan::Clear(), dwarf_lr, dwarf_sp, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), lldb_private::UnwindPlan::SetRegisterKind(), lldb_private::UnwindPlan::SetReturnAddressRegister(), lldb_private::UnwindPlan::SetSourcedFromCompiler(), lldb_private::UnwindPlan::SetSourceName(), lldb_private::UnwindPlan::SetUnwindPlanForSignalTrap(), and lldb_private::UnwindPlan::SetUnwindPlanValidAtAllInstructions().
CreateInstance()
EmulateInstruction * EmulateInstructionARM::CreateInstance (const lldb_private::ArchSpec & arch, InstructionType inst_type) static
Definition at line 722 of file EmulateInstructionARM.cpp.
References EmulateInstructionARM(), lldb_private::ArchSpec::GetTriple(), and SupportsEmulatingInstructionsOfTypeStatic().
Referenced by Initialize(), and Terminate().
CurrentCond()
uint32_t EmulateInstructionARM::CurrentCond (const uint32_t opcode)
Definition at line 13917 of file EmulateInstructionARM.cpp.
References lldb_private::Bits32(), eModeARM, eModeInvalid, eModeThumb, m_it_session, lldb_private::EmulateInstruction::m_opcode, m_opcode_mode, UINT32_MAX, and lldb_private::UnsignedBits().
Referenced by ConditionPassed(), and GetInstructionCondition().
CurrentInstrSet()
EmulateInstructionARM::Mode EmulateInstructionARM::CurrentInstrSet ()
Definition at line 14096 of file EmulateInstructionARM.cpp.
References m_opcode_mode.
Referenced by ALUWritePC(), BranchWritePC(), BXWritePC(), EmulateBLXImmediate(), EmulateBLXRm(), EmulateBXJRm(), EmulateLDRRegister(), EmulateLDRRtPCRelative(), EmulateRFE(), EmulateSTRRegister(), EmulateSUBSPcLrEtc(), EmulateVLDM(), EmulateVSTM(), EmulateVSTR(), InITBlock(), LastInITBlock(), and ReadCoreReg().
CurrentModeIsPrivileged()
bool EmulateInstructionARM::CurrentModeIsPrivileged ()
Definition at line 13981 of file EmulateInstructionARM.cpp.
References BadMode(), lldb_private::Bits32(), and m_opcode_cpsr.
Referenced by CPSRWriteByInstr(), and EmulateRFE().
EmulateADCImm()
bool EmulateInstructionARM::EmulateADCImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 5780 of file EmulateInstructionARM.cpp.
References AddWithCarry(), ALUWritePC(), APSR_C, lldb_private::ARMExpandImm(), lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, EmulateSUBSPcLrEtc(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::ThumbExpandImm(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateADCReg()
bool EmulateInstructionARM::EmulateADCReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 5849 of file EmulateInstructionARM.cpp.
References AddWithCarry(), ALUWritePC(), APSR_C, lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::DecodeImmShiftARM(), lldb_private::DecodeImmShiftThumb(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, eEncodingT2, EmulateSUBSPcLrEtc(), InITBlock(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::Shift(), lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateADDImmARM()
bool EmulateInstructionARM::EmulateADDImmARM (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 3131 of file EmulateInstructionARM.cpp.
References AddWithCarry(), ALUWritePC(), lldb_private::ARMExpandImm(), lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb_private::EmulateInstruction::eContextRegisterPlusOffset, lldb_private::EmulateInstruction::eContextSetFramePointer, eEncodingA1, lldb::eRegisterKindDWARF, GetFramePointerRegisterNumber(), GetRegisterInfo(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction().
EmulateADDImmThumb()
bool EmulateInstructionARM::EmulateADDImmThumb (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 3010 of file EmulateInstructionARM.cpp.
References AddWithCarry(), APSR_C, lldb_private::BadReg(), lldb_private::Bit32(), lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextArithmetic, eEncodingT1, eEncodingT2, eEncodingT3, eEncodingT4, EmulateADDSPImm(), lldb::eRegisterKindDWARF, GetRegisterInfo(), InITBlock(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::ThumbExpandImm_C(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetThumbOpcodeForInstruction().
EmulateADDRdSPImm()
bool EmulateInstructionARM::EmulateADDRdSPImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 1142 of file EmulateInstructionARM.cpp.
References AddWithCarry(), ALUWritePC(), lldb_private::ARMExpandImm(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, dwarf_sp, lldb_private::EmulateInstruction::eContextRegisterPlusOffset, lldb_private::EmulateInstruction::eContextSetFramePointer, eEncodingA1, eEncodingT1, lldb::eRegisterKindDWARF, GetFramePointerRegisterNumber(), GetRegisterInfo(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), sp, SP_REG, lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateADDReg()
bool EmulateInstructionARM::EmulateADDReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 3196 of file EmulateInstructionARM.cpp.
References AddWithCarry(), ALUWritePC(), APSR_C, lldb_private::Bit32(), lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::DecodeImmShiftARM(), dwarf_r0, lldb_private::EmulateInstruction::eContextArithmetic, eEncodingA1, eEncodingT1, eEncodingT2, lldb::eRegisterKindDWARF, GetRegisterInfo(), InITBlock(), LastInITBlock(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetRegisterRegisterOperands(), lldb_private::Shift(), lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateADDRegShift()
bool EmulateInstructionARM::EmulateADDRegShift (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 10086 of file EmulateInstructionARM.cpp.
References AddWithCarry(), APSR_C, lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::DecodeRegShift(), dwarf_r0, lldb_private::EmulateInstruction::eContextArithmetic, eEncodingA1, lldb::eRegisterKindDWARF, GetRegisterInfo(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetRegisterRegisterOperands(), lldb_private::Shift(), lldb_private::EmulateInstruction::Context::type, UInt, WriteFlags(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction().
EmulateADDSPImm()
bool EmulateInstructionARM::EmulateADDSPImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 1827 of file EmulateInstructionARM.cpp.
References AddWithCarry(), ALUWritePC(), lldb_private::Bit32(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), dwarf_sp, lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb_private::EmulateInstruction::eContextRegisterPlusOffset, eEncodingT1, eEncodingT2, eEncodingT3, eEncodingT4, lldb::eRegisterKindDWARF, GetRegisterInfo(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), sp, SP_REG, lldb_private::ThumbExpandImm(), lldb_private::ThumbImm7Scaled(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by EmulateADDImmThumb(), and GetThumbOpcodeForInstruction().
EmulateADDSPRm()
bool EmulateInstructionARM::EmulateADDSPRm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 1938 of file EmulateInstructionARM.cpp.
References AddWithCarry(), ALUWritePC(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, dwarf_sp, lldb_private::EmulateInstruction::eContextArithmetic, eEncodingT2, lldb::eRegisterKindDWARF, lldb::eRegisterKindGeneric, GetRegisterInfo(), LLDB_REGNUM_GENERIC_SP, ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetRegisterRegisterOperands(), lldb_private::Shift(), sp, SP_REG, lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetThumbOpcodeForInstruction().
EmulateADR()
bool EmulateInstructionARM::EmulateADR (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 5934 of file EmulateInstructionARM.cpp.
References lldb_private::Align(), ALUWritePC(), lldb_private::ARMExpandImm(), lldb_private::BadReg(), lldb_private::Bits32(), ConditionPassed(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingA2, eEncodingT1, eEncodingT2, eEncodingT3, pc, PC_REG, ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::ThumbImm12(), lldb_private::ThumbImm8Scaled(), lldb_private::EmulateInstruction::Context::type, and WriteCoreReg().
Referenced by EmulateSUBImmARM(), EmulateSUBImmThumb(), GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateANDImm()
bool EmulateInstructionARM::EmulateANDImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 5997 of file EmulateInstructionARM.cpp.
References ALUWritePC(), APSR_C, lldb_private::ARMExpandImm_C(), lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, EmulateSUBSPcLrEtc(), EmulateTSTImm(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::ThumbExpandImm_C(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateANDReg()
bool EmulateInstructionARM::EmulateANDReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 6072 of file EmulateInstructionARM.cpp.
References ALUWritePC(), APSR_C, lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), lldb_private::DecodeImmShiftARM(), lldb_private::DecodeImmShiftThumb(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, eEncodingT2, EmulateSUBSPcLrEtc(), EmulateTSTReg(), InITBlock(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::Shift_C(), lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateASRImm()
bool EmulateInstructionARM::EmulateASRImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 3526 of file EmulateInstructionARM.cpp.
References ALUWritePC(), ConditionPassed(), EmulateShiftImm(), lldb_private::Shift_C(), and lldb_private::SRType_ASR.
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateASRReg()
bool EmulateInstructionARM::EmulateASRReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 3552 of file EmulateInstructionARM.cpp.
References ConditionPassed(), EmulateShiftReg(), lldb_private::Shift_C(), lldb_private::SRType_ASR, and UInt.
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateB()
bool EmulateInstructionARM::EmulateB (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 2798 of file EmulateInstructionARM.cpp.
References lldb_private::Bit32(), lldb_private::Bits32(), BranchWritePC(), ConditionPassed(), lldb_private::EmulateInstruction::eContextRelativeBranchImmediate, eEncodingA1, eEncodingT1, eEncodingT2, eEncodingT3, eEncodingT4, eModeARM, eModeThumb, pc, PC_REG, ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetISAAndImmediateSigned(), and lldb_private::EmulateInstruction::Context::type.
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateBICImm()
bool EmulateInstructionARM::EmulateBICImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 6162 of file EmulateInstructionARM.cpp.
References ALUWritePC(), APSR_C, lldb_private::ARMExpandImm_C(), lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, EmulateSUBSPcLrEtc(), NOT(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::ThumbExpandImm_C(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateBICReg()
bool EmulateInstructionARM::EmulateBICReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 6237 of file EmulateInstructionARM.cpp.
References ALUWritePC(), APSR_C, lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), lldb_private::DecodeImmShiftARM(), lldb_private::DecodeImmShiftThumb(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, eEncodingT2, EmulateSUBSPcLrEtc(), InITBlock(), NOT(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::Shift_C(), lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateBLXImmediate()
bool EmulateInstructionARM::EmulateBLXImmediate (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 1998 of file EmulateInstructionARM.cpp.
References lldb_private::Align(), lldb_private::Bit32(), lldb_private::Bits32(), BranchWritePC(), ConditionPassed(), CurrentInstrSet(), lldb_private::EmulateInstruction::eContextRelativeBranchImmediate, eEncodingA1, eEncodingA2, eEncodingT1, eEncodingT2, eModeARM, eModeThumb, lldb::eRegisterKindGeneric, InITBlock(), LastInITBlock(), LLDB_REGNUM_GENERIC_FLAGS, LLDB_REGNUM_GENERIC_RA, m_new_inst_cpsr, m_opcode_cpsr, pc, PC_REG, ReadCoreReg(), SelectInstrSet(), lldb_private::EmulateInstruction::Context::SetISAAndImmediateSigned(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateBLXRm()
bool EmulateInstructionARM::EmulateBLXRm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 2102 of file EmulateInstructionARM.cpp.
References lldb_private::Bits32(), BXWritePC(), ConditionPassed(), CurrentInstrSet(), dwarf_r0, lldb_private::EmulateInstruction::eContextAbsoluteBranchRegister, eEncodingA1, eEncodingT1, lldb::eRegisterKindDWARF, lldb::eRegisterKindGeneric, GetRegisterInfo(), InITBlock(), LastInITBlock(), LLDB_REGNUM_GENERIC_RA, pc, PC_REG, ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetRegister(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateBXJ()
bool lldb_private::EmulateInstructionARM::EmulateBXJ (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateBXJRm()
bool EmulateInstructionARM::EmulateBXJRm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 2215 of file EmulateInstructionARM.cpp.
References lldb_private::BadReg(), lldb_private::Bits32(), BXWritePC(), ConditionPassed(), CurrentInstrSet(), dwarf_r0, lldb_private::EmulateInstruction::eContextAbsoluteBranchRegister, eEncodingA1, eEncodingT1, lldb::eRegisterKindDWARF, GetRegisterInfo(), InITBlock(), LastInITBlock(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetRegister(), and lldb_private::EmulateInstruction::Context::type.
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateBXRm()
bool EmulateInstructionARM::EmulateBXRm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 2167 of file EmulateInstructionARM.cpp.
References lldb_private::Bits32(), BXWritePC(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAbsoluteBranchRegister, eEncodingA1, eEncodingT1, lldb::eRegisterKindDWARF, GetRegisterInfo(), InITBlock(), LastInITBlock(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetRegister(), and lldb_private::EmulateInstruction::Context::type.
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateCB()
bool EmulateInstructionARM::EmulateCB (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 2882 of file EmulateInstructionARM.cpp.
References lldb_private::Bit32(), lldb_private::BitIsSet(), lldb_private::Bits32(), BranchWritePC(), lldb_private::EmulateInstruction::eContextRelativeBranchImmediate, eEncodingT1, eModeThumb, IsZero(), m_ignore_conditions, pc, PC_REG, ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetISAAndImmediateSigned(), and lldb_private::EmulateInstruction::Context::type.
Referenced by GetThumbOpcodeForInstruction().
EmulateCMNImm()
bool EmulateInstructionARM::EmulateCMNImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 3285 of file EmulateInstructionARM.cpp.
References AddWithCarry(), lldb_private::ARMExpandImm(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::ThumbExpandImm(), lldb_private::EmulateInstruction::Context::type, and WriteFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateCMNReg()
bool EmulateInstructionARM::EmulateCMNReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 3332 of file EmulateInstructionARM.cpp.
References AddWithCarry(), APSR_C, lldb_private::BadReg(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::DecodeImmShiftARM(), lldb_private::DecodeImmShiftThumb(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, eEncodingT2, lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::Shift(), lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, and WriteFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateCMPImm()
bool EmulateInstructionARM::EmulateCMPImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 3398 of file EmulateInstructionARM.cpp.
References AddWithCarry(), lldb_private::ARMExpandImm(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, eEncodingT2, NOT(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::ThumbExpandImm(), lldb_private::EmulateInstruction::Context::type, and WriteFlags().
Referenced by EmulateSUBImmThumb(), EmulateSUBReg(), EmulateSUBSPImm(), GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateCMPReg()
bool EmulateInstructionARM::EmulateCMPReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 3449 of file EmulateInstructionARM.cpp.
References AddWithCarry(), APSR_C, lldb_private::BadReg(), lldb_private::Bit32(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::DecodeImmShiftARM(), lldb_private::DecodeImmShiftThumb(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, eEncodingT2, eEncodingT3, NOT(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::Shift(), lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, and WriteFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateEORImm()
bool EmulateInstructionARM::EmulateEORImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 8801 of file EmulateInstructionARM.cpp.
References ALUWritePC(), APSR_C, lldb_private::ARMExpandImm_C(), lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, EmulateSUBSPcLrEtc(), EmulateTEQImm(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::ThumbExpandImm_C(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateEORReg()
bool EmulateInstructionARM::EmulateEORReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 8879 of file EmulateInstructionARM.cpp.
References ALUWritePC(), APSR_C, lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), lldb_private::DecodeImmShiftARM(), lldb_private::DecodeImmShiftThumb(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, eEncodingT2, EmulateSUBSPcLrEtc(), EmulateTEQReg(), InITBlock(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::Shift_C(), lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateIT()
bool EmulateInstructionARM::EmulateIT (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 2779 of file EmulateInstructionARM.cpp.
References lldb_private::Bits32(), and m_it_session.
Referenced by EvaluateInstruction(), and GetThumbOpcodeForInstruction().
EmulateLDM()
bool EmulateInstructionARM::EmulateLDM (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 3901 of file EmulateInstructionARM.cpp.
References lldb_private::BitCount(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextPopRegisterOffStack, lldb_private::EmulateInstruction::eContextRegisterPlusOffset, eEncodingA1, eEncodingT1, eEncodingT2, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), InITBlock(), LastInITBlock(), LoadWritePC(), MemARead(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, WriteBits32Unknown(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateLDMDA()
bool EmulateInstructionARM::EmulateLDMDA (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 4044 of file EmulateInstructionARM.cpp.
References lldb_private::BitCount(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterPlusOffset, eEncodingA1, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), LoadWritePC(), MemARead(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::type, WriteBits32Unknown(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction().
EmulateLDMDB()
bool EmulateInstructionARM::EmulateLDMDB (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 4159 of file EmulateInstructionARM.cpp.
References lldb_private::BitCount(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterPlusOffset, eEncodingA1, eEncodingT1, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), InITBlock(), LastInITBlock(), LoadWritePC(), MemARead(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::type, WriteBits32Unknown(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateLDMIB()
bool EmulateInstructionARM::EmulateLDMIB (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 4296 of file EmulateInstructionARM.cpp.
References lldb_private::BitCount(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterPlusOffset, eEncodingA1, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), LoadWritePC(), MemARead(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetImmediateSigned(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, WriteBits32Unknown(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction().
EmulateLDRBImmediate()
bool EmulateInstructionARM::EmulateLDRBImmediate (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 6668 of file EmulateInstructionARM.cpp.
References lldb_private::BadReg(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingT1, eEncodingT2, eEncodingT3, EmulateLDRBLiteral(), lldb::eRegisterKindDWARF, GetRegisterInfo(), MemURead(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetThumbOpcodeForInstruction().
EmulateLDRBImmediateARM()
bool lldb_private::EmulateInstructionARM::EmulateLDRBImmediateARM (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateLDRBLiteral()
bool EmulateInstructionARM::EmulateLDRBLiteral (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 6815 of file EmulateInstructionARM.cpp.
References lldb_private::Align(), AlignPC, lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextRelativeBranchImmediate, eEncodingA1, eEncodingT1, lldb::eRegisterKindDWARF, MemURead(), PC_REG, ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetImmediate(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by EmulateLDRBImmediate(), EmulateLDRBRegister(), GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateLDRBRegister()
bool EmulateInstructionARM::EmulateLDRBRegister (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 6896 of file EmulateInstructionARM.cpp.
References APSR_C, lldb_private::BadReg(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), lldb_private::DecodeImmShift(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingT1, eEncodingT2, EmulateLDRBLiteral(), lldb::eRegisterKindDWARF, GetRegisterInfo(), MemURead(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::Shift(), lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateLDRBT()
bool lldb_private::EmulateInstructionARM::EmulateLDRBT (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateLDRDImmediate()
bool EmulateInstructionARM::EmulateLDRDImmediate (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 10629 of file EmulateInstructionARM.cpp.
References lldb_private::BadReg(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextPopRegisterOffStack, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingT1, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), MemARead(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateLDRDLiteral()
bool lldb_private::EmulateInstructionARM::EmulateLDRDLiteral (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateLDRDRegister()
bool EmulateInstructionARM::EmulateLDRDRegister (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 10775 of file EmulateInstructionARM.cpp.
References ArchVersion(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextPopRegisterOffStack, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), MemARead(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction().
EmulateLDREX()
bool lldb_private::EmulateInstructionARM::EmulateLDREX (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateLDREXB()
bool lldb_private::EmulateInstructionARM::EmulateLDREXB (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateLDREXD()
bool lldb_private::EmulateInstructionARM::EmulateLDREXD (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateLDREXH()
bool lldb_private::EmulateInstructionARM::EmulateLDREXH (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateLDRHImmediate()
bool EmulateInstructionARM::EmulateLDRHImmediate (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 7058 of file EmulateInstructionARM.cpp.
References lldb_private::BadReg(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingT1, eEncodingT2, eEncodingT3, lldb::eRegisterKindDWARF, GetRegisterInfo(), MemURead(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, UnalignedSupport(), WriteBits32Unknown(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetThumbOpcodeForInstruction().
EmulateLDRHImmediateARM()
bool lldb_private::EmulateInstructionARM::EmulateLDRHImmediateARM (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateLDRHLiteral()
bool EmulateInstructionARM::EmulateLDRHLiteral (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 7205 of file EmulateInstructionARM.cpp.
References lldb_private::Align(), AlignPC, lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingT1, lldb::eRegisterKindDWARF, lldb::eRegisterKindGeneric, GetRegisterInfo(), LLDB_REGNUM_GENERIC_PC, MemURead(), PC_REG, ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, UnalignedSupport(), WriteBits32Unknown(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateLDRHRegister()
bool EmulateInstructionARM::EmulateLDRHRegister (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 7309 of file EmulateInstructionARM.cpp.
References APSR_C, lldb_private::BadReg(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingT1, eEncodingT2, lldb::eRegisterKindDWARF, GetRegisterInfo(), MemURead(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::SetRegisterPlusIndirectOffset(), lldb_private::Shift(), lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, UnalignedSupport(), WriteBits32Unknown(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateLDRHT()
bool lldb_private::EmulateInstructionARM::EmulateLDRHT (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateLDRImmediateARM()
bool EmulateInstructionARM::EmulateLDRImmediateARM (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 6326 of file EmulateInstructionARM.cpp.
References lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), LoadWritePC(), MemURead(), ReadCoreReg(), lldb_private::ROR(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::SetImmediate(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, UInt, UnalignedSupport(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction().
EmulateLDRLiteral()
bool lldb_private::EmulateInstructionARM::EmulateLDRLiteral (const uint32_t , const ARMEncoding encoding) protected
EmulateLDRRegister()
bool EmulateInstructionARM::EmulateLDRRegister (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 6462 of file EmulateInstructionARM.cpp.
References APSR_C, lldb_private::BadReg(), lldb_private::Bit32(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), CurrentInstrSet(), lldb_private::DecodeImmShift(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingT1, eEncodingT2, eModeARM, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), InITBlock(), LastInITBlock(), LoadWritePC(), m_opcode_cpsr, MemURead(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::ROR(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::SetImmediate(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::Shift(), lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, UInt, UnalignedSupport(), WriteBits32Unknown(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateLDRRtPCRelative()
bool EmulateInstructionARM::EmulateLDRRtPCRelative (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 1739 of file EmulateInstructionARM.cpp.
References lldb_private::Align(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), CurrentInstrSet(), dwarf_pc, dwarf_r0, lldb_private::EmulateInstruction::eContextRegisterPlusOffset, eEncodingT1, eEncodingT2, lldb::eRegisterKindDWARF, GetRegisterInfo(), InITBlock(), LastInITBlock(), LoadWritePC(), MemURead(), pc, PC_REG, ReadCoreReg(), lldb_private::ROR(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, UInt, UnalignedSupport(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetThumbOpcodeForInstruction().
EmulateLDRRtRnImm()
bool EmulateInstructionARM::EmulateLDRRtRnImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 4406 of file EmulateInstructionARM.cpp.
References lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb_private::EmulateInstruction::eContextRegisterLoad, lldb_private::EmulateInstruction::eContextSetFramePointer, eEncodingT1, eEncodingT2, eEncodingT3, eEncodingT4, lldb::eRegisterKindDWARF, GetFramePointerRegisterNumber(), GetRegisterInfo(), InITBlock(), LastInITBlock(), LoadWritePC(), MemURead(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetImmediateSigned(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, UnalignedSupport(), WriteBits32Unknown(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetThumbOpcodeForInstruction().
EmulateLDRSBImmediate()
bool EmulateInstructionARM::EmulateLDRSBImmediate (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 7485 of file EmulateInstructionARM.cpp.
References lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingT1, eEncodingT2, lldb::eRegisterKindDWARF, GetRegisterInfo(), MemURead(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateLDRSBLiteral()
bool EmulateInstructionARM::EmulateLDRSBLiteral (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 7634 of file EmulateInstructionARM.cpp.
References lldb_private::Align(), AlignPC, lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingT1, lldb::eRegisterKindDWARF, lldb::eRegisterKindGeneric, GetRegisterInfo(), LLDB_REGNUM_GENERIC_PC, MemURead(), PC_REG, ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateLDRSBRegister()
bool EmulateInstructionARM::EmulateLDRSBRegister (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 7722 of file EmulateInstructionARM.cpp.
References APSR_C, lldb_private::BadReg(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingT1, eEncodingT2, lldb::eRegisterKindDWARF, GetRegisterInfo(), MemURead(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::SetRegisterPlusIndirectOffset(), lldb_private::Shift(), lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateLDRSBT()
bool lldb_private::EmulateInstructionARM::EmulateLDRSBT (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateLDRSHImmediate()
bool EmulateInstructionARM::EmulateLDRSHImmediate (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 7882 of file EmulateInstructionARM.cpp.
References lldb_private::BadReg(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingT1, eEncodingT2, lldb::eRegisterKindDWARF, GetRegisterInfo(), MemURead(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, UnalignedSupport(), WriteBits32Unknown(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateLDRSHLiteral()
bool EmulateInstructionARM::EmulateLDRSHLiteral (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 8041 of file EmulateInstructionARM.cpp.
References lldb_private::Align(), AlignPC, lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingT1, lldb::eRegisterKindDWARF, lldb::eRegisterKindGeneric, GetRegisterInfo(), LLDB_REGNUM_GENERIC_PC, MemURead(), PC_REG, ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, UnalignedSupport(), WriteBits32Unknown(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateLDRSHRegister()
bool EmulateInstructionARM::EmulateLDRSHRegister (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 8142 of file EmulateInstructionARM.cpp.
References APSR_C, lldb_private::BadReg(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingT1, eEncodingT2, lldb::eRegisterKindDWARF, GetRegisterInfo(), MemURead(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::SetRegisterPlusIndirectOffset(), lldb_private::Shift(), lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, UnalignedSupport(), WriteBits32Unknown(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateLDRSHT()
bool lldb_private::EmulateInstructionARM::EmulateLDRSHT (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateLDRT()
bool lldb_private::EmulateInstructionARM::EmulateLDRT (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateLSLImm()
bool EmulateInstructionARM::EmulateLSLImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 3574 of file EmulateInstructionARM.cpp.
References ALUWritePC(), ConditionPassed(), EmulateShiftImm(), lldb_private::Shift_C(), and lldb_private::SRType_LSL.
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateLSLReg()
bool EmulateInstructionARM::EmulateLSLReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 3599 of file EmulateInstructionARM.cpp.
References ConditionPassed(), EmulateShiftReg(), lldb_private::Shift_C(), lldb_private::SRType_LSL, and UInt.
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateLSRImm()
bool EmulateInstructionARM::EmulateLSRImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 3622 of file EmulateInstructionARM.cpp.
References ALUWritePC(), ConditionPassed(), EmulateShiftImm(), lldb_private::Shift_C(), and lldb_private::SRType_LSR.
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateLSRReg()
bool EmulateInstructionARM::EmulateLSRReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 3647 of file EmulateInstructionARM.cpp.
References ConditionPassed(), EmulateShiftReg(), lldb_private::Shift_C(), lldb_private::SRType_LSR, and UInt.
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateMOVLowHigh()
bool EmulateInstructionARM::EmulateMOVLowHigh (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 1258 of file EmulateInstructionARM.cpp.
References EmulateMOVRdRm().
Referenced by GetThumbOpcodeForInstruction().
EmulateMOVRdImm()
bool EmulateInstructionARM::EmulateMOVRdImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 1356 of file EmulateInstructionARM.cpp.
References ALUWritePC(), APSR_C, lldb_private::ARMExpandImm_C(), lldb_private::BadReg(), lldb_private::Bit32(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingA2, eEncodingT1, eEncodingT2, eEncodingT3, EmulateSUBSPcLrEtc(), InITBlock(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::ThumbExpandImm_C(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by EmulateORRImm(), GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateMOVRdRm()
bool EmulateInstructionARM::EmulateMOVRdRm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 1265 of file EmulateInstructionARM.cpp.
References ALUWritePC(), lldb_private::BadReg(), lldb_private::Bit32(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb_private::EmulateInstruction::eContextRegisterPlusOffset, lldb_private::EmulateInstruction::eContextSetFramePointer, eEncodingA1, eEncodingT1, eEncodingT2, eEncodingT3, EmulateSUBSPcLrEtc(), lldb::eRegisterKindDWARF, GetFramePointerRegisterNumber(), GetRegisterInfo(), InITBlock(), LastInITBlock(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by EmulateMOVLowHigh(), EmulateORRReg(), GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateMOVRdSP()
bool EmulateInstructionARM::EmulateMOVRdSP (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 1203 of file EmulateInstructionARM.cpp.
References ALUWritePC(), ConditionPassed(), dwarf_r0, dwarf_sp, lldb_private::EmulateInstruction::eContextRegisterPlusOffset, lldb_private::EmulateInstruction::eContextSetFramePointer, eEncodingA1, eEncodingT1, lldb::eRegisterKindDWARF, GetFramePointerRegisterNumber(), GetRegisterInfo(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), sp, SP_REG, lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateMUL()
bool EmulateInstructionARM::EmulateMUL (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 1469 of file EmulateInstructionARM.cpp.
References ArchVersion(), ARMv6, lldb_private::BadReg(), lldb_private::bit(), lldb_private::Bit32(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), CPSR_N_POS, CPSR_Z_POS, dwarf_r0, lldb_private::EmulateInstruction::eContextArithmetic, eEncodingA1, eEncodingT1, eEncodingT2, lldb::eRegisterKindDWARF, lldb::eRegisterKindGeneric, GetRegisterInfo(), InITBlock(), LLDB_REGNUM_GENERIC_FLAGS, m_new_inst_cpsr, m_opcode_cpsr, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::SetBit32(), lldb_private::EmulateInstruction::Context::SetRegisterRegisterOperands(), SInt, lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateMVNImm()
bool EmulateInstructionARM::EmulateMVNImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 1598 of file EmulateInstructionARM.cpp.
References ALUWritePC(), APSR_C, lldb_private::ARMExpandImm_C(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, EmulateSUBSPcLrEtc(), NOT(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::ThumbExpandImm_C(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateMVNReg()
bool EmulateInstructionARM::EmulateMVNReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 1658 of file EmulateInstructionARM.cpp.
References ALUWritePC(), APSR_C, lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), lldb_private::DecodeImmShiftARM(), lldb_private::DecodeImmShiftThumb(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, eEncodingT2, InITBlock(), NOT(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::Shift_C(), lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateNop()
bool EmulateInstructionARM::EmulateNop (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 2791 of file EmulateInstructionARM.cpp.
Referenced by GetThumbOpcodeForInstruction().
EmulateORRImm()
bool EmulateInstructionARM::EmulateORRImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 8970 of file EmulateInstructionARM.cpp.
References ALUWritePC(), APSR_C, lldb_private::ARMExpandImm_C(), lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, eEncodingT2, EmulateMOVRdImm(), EmulateSUBSPcLrEtc(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::ThumbExpandImm_C(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateORRReg()
bool EmulateInstructionARM::EmulateORRReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 9046 of file EmulateInstructionARM.cpp.
References ALUWritePC(), APSR_C, lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), lldb_private::DecodeImmShiftARM(), lldb_private::DecodeImmShiftThumb(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, eEncodingT2, eEncodingT3, EmulateMOVRdRm(), EmulateSUBSPcLrEtc(), InITBlock(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::Shift_C(), lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulatePLDImmediate()
bool lldb_private::EmulateInstructionARM::EmulatePLDImmediate (const uint32_t opcode, const ARMEncoding encoding) protected
EmulatePLIImmediate()
bool lldb_private::EmulateInstructionARM::EmulatePLIImmediate (const uint32_t opcode, const ARMEncoding encoding) protected
EmulatePLIRegister()
bool lldb_private::EmulateInstructionARM::EmulatePLIRegister (const uint32_t opcode, const ARMEncoding encoding) protected
EmulatePOP()
bool EmulateInstructionARM::EmulatePOP (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 1014 of file EmulateInstructionARM.cpp.
References ArchVersion(), ARMv7, lldb_private::Bit32(), lldb_private::BitCount(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, dwarf_sp, lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb_private::EmulateInstruction::eContextPopRegisterOffStack, eEncodingA1, eEncodingA2, eEncodingT1, eEncodingT2, eEncodingT3, lldb::eRegisterKindDWARF, lldb::eRegisterKindGeneric, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), InITBlock(), LastInITBlock(), LLDB_REGNUM_GENERIC_SP, LoadWritePC(), MemARead(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::SetImmediateSigned(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), sp, SP_REG, lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulatePUSH()
bool EmulateInstructionARM::EmulatePUSH (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 891 of file EmulateInstructionARM.cpp.
References lldb_private::BadReg(), lldb_private::Bit32(), lldb_private::BitCount(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), dwarf_pc, dwarf_r0, dwarf_sp, lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb_private::EmulateInstruction::eContextPushRegisterOnStack, eEncodingA1, eEncodingA2, eEncodingT1, eEncodingT2, eEncodingT3, lldb::eRegisterKindDWARF, lldb::eRegisterKindGeneric, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), LLDB_REGNUM_GENERIC_SP, MemAWrite(), pc, PC_REG, ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetImmediateSigned(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), sp, SP_REG, lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateRFE()
bool EmulateInstructionARM::EmulateRFE (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 8655 of file EmulateInstructionARM.cpp.
References lldb_private::Bit32(), lldb_private::BitIsSet(), lldb_private::Bits32(), BranchWritePC(), ConditionPassed(), CPSRWriteByInstr(), CurrentInstrSet(), CurrentModeIsPrivileged(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextReturnFromException, eEncodingA1, eEncodingT1, eEncodingT2, lldb::eRegisterKindDWARF, GetRegisterInfo(), InITBlock(), LastInITBlock(), MemARead(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetOffset(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateRORImm()
bool EmulateInstructionARM::EmulateRORImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 3670 of file EmulateInstructionARM.cpp.
References ALUWritePC(), ConditionPassed(), EmulateShiftImm(), lldb_private::Shift_C(), and lldb_private::SRType_ROR.
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateRORReg()
bool EmulateInstructionARM::EmulateRORReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 3696 of file EmulateInstructionARM.cpp.
References ConditionPassed(), EmulateShiftReg(), lldb_private::Shift_C(), lldb_private::SRType_ROR, and UInt.
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateRRX()
bool EmulateInstructionARM::EmulateRRX (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 3720 of file EmulateInstructionARM.cpp.
References ALUWritePC(), ConditionPassed(), EmulateShiftImm(), lldb_private::Shift_C(), and lldb_private::SRType_RRX.
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateRSBImm()
bool EmulateInstructionARM::EmulateRSBImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 9135 of file EmulateInstructionARM.cpp.
References AddWithCarry(), ALUWritePC(), lldb_private::ARMExpandImm(), lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, eEncodingT2, EmulateSUBSPcLrEtc(), InITBlock(), NOT(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::ThumbExpandImm(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateRSBReg()
bool EmulateInstructionARM::EmulateRSBReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 9207 of file EmulateInstructionARM.cpp.
References AddWithCarry(), ALUWritePC(), APSR_C, lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::DecodeImmShiftARM(), lldb_private::DecodeImmShiftThumb(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, EmulateSUBSPcLrEtc(), NOT(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::Shift(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateRSCImm()
bool EmulateInstructionARM::EmulateRSCImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 9286 of file EmulateInstructionARM.cpp.
References AddWithCarry(), ALUWritePC(), APSR_C, lldb_private::ARMExpandImm(), lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, EmulateSUBSPcLrEtc(), NOT(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction().
EmulateRSCReg()
bool EmulateInstructionARM::EmulateRSCReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 9345 of file EmulateInstructionARM.cpp.
References AddWithCarry(), ALUWritePC(), APSR_C, lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::DecodeImmShiftARM(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, EmulateSUBSPcLrEtc(), NOT(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::Shift(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction().
EmulateSBCImm()
bool EmulateInstructionARM::EmulateSBCImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 9415 of file EmulateInstructionARM.cpp.
References AddWithCarry(), ALUWritePC(), APSR_C, lldb_private::ARMExpandImm(), lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, EmulateSUBSPcLrEtc(), NOT(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::ThumbExpandImm(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateSBCReg()
bool EmulateInstructionARM::EmulateSBCReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 9483 of file EmulateInstructionARM.cpp.
References AddWithCarry(), ALUWritePC(), APSR_C, lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::DecodeImmShiftARM(), lldb_private::DecodeImmShiftThumb(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, eEncodingT2, EmulateSUBSPcLrEtc(), InITBlock(), NOT(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::Shift(), lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateShiftImm()
bool EmulateInstructionARM::EmulateShiftImm (const uint32_t opcode, const ARMEncoding encoding, ARM_ShifterType shift_type) protected
Definition at line 3741 of file EmulateInstructionARM.cpp.
References APSR_C, lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), lldb_private::DecodeImmShift(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, eEncodingT2, InITBlock(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::Shift_C(), lldb_private::SRType_ROR, lldb_private::SRType_RRX, lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by EmulateASRImm(), EmulateLSLImm(), EmulateLSRImm(), EmulateRORImm(), and EmulateRRX().
EmulateShiftReg()
bool EmulateInstructionARM::EmulateShiftReg (const uint32_t opcode, const ARMEncoding encoding, ARM_ShifterType shift_type) protected
Definition at line 3827 of file EmulateInstructionARM.cpp.
References APSR_C, lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, eEncodingT2, InITBlock(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::Shift_C(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by EmulateASRReg(), EmulateLSLReg(), EmulateLSRReg(), and EmulateRORReg().
EmulateSTM()
bool EmulateInstructionARM::EmulateSTM (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 4569 of file EmulateInstructionARM.cpp.
References lldb_private::BitCount(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), dwarf_pc, dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterStore, eEncodingA1, eEncodingT1, eEncodingT2, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), MemAWrite(), pc, PC_REG, ReadCoreReg(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetImmediateSigned(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, WriteBits32UnknownToMemory(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateSTMDA()
bool EmulateInstructionARM::EmulateSTMDA (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 4721 of file EmulateInstructionARM.cpp.
References lldb_private::BitCount(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), dwarf_pc, dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterStore, eEncodingA1, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), MemAWrite(), pc, PC_REG, ReadCoreReg(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::type, WriteBits32UnknownToMemory(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction().
EmulateSTMDB()
bool EmulateInstructionARM::EmulateSTMDB (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 4843 of file EmulateInstructionARM.cpp.
References lldb_private::BitCount(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), dwarf_pc, dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterStore, eEncodingA1, eEncodingT1, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), MemAWrite(), pc, PC_REG, ReadCoreReg(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::type, WriteBits32UnknownToMemory(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateSTMIB()
bool EmulateInstructionARM::EmulateSTMIB (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 4992 of file EmulateInstructionARM.cpp.
References lldb_private::BitCount(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), dwarf_pc, dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterStore, eEncodingA1, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), MemAWrite(), pc, PC_REG, ReadCoreReg(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetImmediateSigned(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, WriteBits32UnknownToMemory(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction().
EmulateSTRBImmARM()
bool EmulateInstructionARM::EmulateSTRBImmARM (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 10427 of file EmulateInstructionARM.cpp.
References lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextRegisterStore, eEncodingA1, lldb::eRegisterKindDWARF, GetRegisterInfo(), MemUWrite(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction().
EmulateSTRBReg()
bool lldb_private::EmulateInstructionARM::EmulateSTRBReg (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateSTRBT()
bool lldb_private::EmulateInstructionARM::EmulateSTRBT (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateSTRBThumb()
bool EmulateInstructionARM::EmulateSTRBThumb (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 5470 of file EmulateInstructionARM.cpp.
References lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextRegisterLoad, lldb_private::EmulateInstruction::eContextRegisterStore, eEncodingT1, eEncodingT2, eEncodingT3, lldb::eRegisterKindDWARF, GetRegisterInfo(), MemUWrite(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetThumbOpcodeForInstruction().
EmulateSTRDImm()
bool EmulateInstructionARM::EmulateSTRDImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 10900 of file EmulateInstructionARM.cpp.
References lldb_private::BadReg(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb_private::EmulateInstruction::eContextPushRegisterOnStack, lldb_private::EmulateInstruction::eContextRegisterStore, eEncodingA1, eEncodingT1, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), MemAWrite(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateSTRDReg()
bool EmulateInstructionARM::EmulateSTRDReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 11053 of file EmulateInstructionARM.cpp.
References ArchVersion(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextPushRegisterOnStack, lldb_private::EmulateInstruction::eContextRegisterStore, eEncodingA1, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), MemAWrite(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusIndirectOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction().
EmulateSTREX()
bool EmulateInstructionARM::EmulateSTREX (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 10316 of file EmulateInstructionARM.cpp.
References lldb_private::BadReg(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextRegisterStore, eEncodingA1, eEncodingT1, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), MemAWrite(), ReadCoreReg(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateSTREXB()
bool lldb_private::EmulateInstructionARM::EmulateSTREXB (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateSTREXD()
bool lldb_private::EmulateInstructionARM::EmulateSTREXD (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateSTREXH()
bool lldb_private::EmulateInstructionARM::EmulateSTREXH (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateSTRHImmARM()
bool lldb_private::EmulateInstructionARM::EmulateSTRHImmARM (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateSTRHImmThumb()
bool lldb_private::EmulateInstructionARM::EmulateSTRHImmThumb (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateSTRHRegister()
bool EmulateInstructionARM::EmulateSTRHRegister (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 5606 of file EmulateInstructionARM.cpp.
References APSR_C, lldb_private::BadReg(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterStore, eEncodingA1, eEncodingT1, eEncodingT2, lldb::eRegisterKindDWARF, GetRegisterInfo(), MemUWrite(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusIndirectOffset(), lldb_private::Shift(), lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, UnalignedSupport(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateSTRHT()
bool lldb_private::EmulateInstructionARM::EmulateSTRHT (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateSTRImmARM()
bool EmulateInstructionARM::EmulateSTRImmARM (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 10520 of file EmulateInstructionARM.cpp.
References lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterStore, eEncodingA1, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), MemUWrite(), PC_REG, ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetImmediate(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction().
EmulateSTRRegister()
bool EmulateInstructionARM::EmulateSTRRegister (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 5281 of file EmulateInstructionARM.cpp.
References APSR_C, lldb_private::BadReg(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), CurrentInstrSet(), lldb_private::DecodeImmShift(), dwarf_r0, lldb_private::EmulateInstruction::eContextRegisterLoad, lldb_private::EmulateInstruction::eContextRegisterStore, eEncodingA1, eEncodingT1, eEncodingT2, eModeARM, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), MemUWrite(), PC_REG, ReadCoreReg(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), lldb_private::Shift(), lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, UnalignedSupport(), WriteBits32UnknownToMemory(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateSTRRtSP()
bool EmulateInstructionARM::EmulateSTRRtSP (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 2457 of file EmulateInstructionARM.cpp.
References lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, dwarf_sp, lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb_private::EmulateInstruction::eContextPushRegisterOnStack, eEncodingA1, lldb::eRegisterKindDWARF, lldb::eRegisterKindGeneric, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), LLDB_REGNUM_GENERIC_SP, MemUWrite(), pc, PC_REG, ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetImmediateSigned(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), sp, SP_REG, lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction().
EmulateSTRT()
bool lldb_private::EmulateInstructionARM::EmulateSTRT (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateSTRThumb()
bool EmulateInstructionARM::EmulateSTRThumb (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 5114 of file EmulateInstructionARM.cpp.
References lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::bits(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb_private::EmulateInstruction::eContextPushRegisterOnStack, lldb_private::EmulateInstruction::eContextRegisterStore, eEncodingT1, eEncodingT2, eEncodingT3, eEncodingT4, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), MemUWrite(), ReadCoreReg(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, UnalignedSupport(), WriteBits32UnknownToMemory(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetThumbOpcodeForInstruction().
EmulateSUBImmARM()
bool EmulateInstructionARM::EmulateSUBImmARM (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 9657 of file EmulateInstructionARM.cpp.
References AddWithCarry(), ALUWritePC(), lldb_private::ARMExpandImm(), lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb_private::EmulateInstruction::eContextRegisterPlusOffset, eEncodingA1, eEncodingA2, EmulateADR(), EmulateSUBSPcLrEtc(), EmulateSUBSPImm(), lldb::eRegisterKindDWARF, GetRegisterInfo(), NOT(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction().
EmulateSUBImmThumb()
bool EmulateInstructionARM::EmulateSUBImmThumb (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 9567 of file EmulateInstructionARM.cpp.
References AddWithCarry(), lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingT1, eEncodingT2, eEncodingT3, eEncodingT4, EmulateADR(), EmulateCMPImm(), EmulateSUBSPImm(), InITBlock(), NOT(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::ThumbExpandImm(), lldb_private::ThumbImm12(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetThumbOpcodeForInstruction().
EmulateSUBIPSPImm()
bool EmulateInstructionARM::EmulateSUBIPSPImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 2318 of file EmulateInstructionARM.cpp.
References AddWithCarry(), ALUWritePC(), lldb_private::ARMExpandImm(), ConditionPassed(), dwarf_r12, lldb_private::EmulateInstruction::eContextRegisterPlusOffset, eEncodingA1, lldb::eRegisterKindDWARF, lldb::eRegisterKindGeneric, GetRegisterInfo(), LLDB_REGNUM_GENERIC_SP, NOT(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), sp, SP_REG, lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction().
EmulateSUBR7IPImm()
bool EmulateInstructionARM::EmulateSUBR7IPImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 2268 of file EmulateInstructionARM.cpp.
References AddWithCarry(), ALUWritePC(), lldb_private::ARMExpandImm(), ConditionPassed(), dwarf_r12, dwarf_r7, lldb_private::EmulateInstruction::eContextRegisterPlusOffset, eEncodingA1, lldb::eRegisterKindDWARF, GetRegisterInfo(), NOT(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction().
EmulateSUBReg()
bool EmulateInstructionARM::EmulateSUBReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 10182 of file EmulateInstructionARM.cpp.
References AddWithCarry(), ALUWritePC(), APSR_C, lldb_private::BadReg(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::DecodeImmShiftARM(), lldb_private::DecodeImmShiftThumb(), dwarf_r0, lldb_private::EmulateInstruction::eContextArithmetic, eEncodingA1, eEncodingT1, eEncodingT2, eEncodingT3, EmulateCMPImm(), EmulateSUBSPcLrEtc(), EmulateSUBSPReg(), lldb::eRegisterKindDWARF, GetRegisterInfo(), InITBlock(), NOT(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetRegisterRegisterOperands(), lldb_private::Shift(), lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateSUBRegShift()
bool lldb_private::EmulateInstructionARM::EmulateSUBRegShift (const uint32_t opcode, const ARMEncoding encoding) protected
EmulateSUBSPcLrEtc()
bool EmulateInstructionARM::EmulateSUBSPcLrEtc (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 12626 of file EmulateInstructionARM.cpp.
References AddWithCarry(), APSR_C, lldb_private::ARMExpandImm(), lldb_private::Bits32(), BranchWritePC(), ConditionPassed(), CPSRWriteByInstr(), CurrentInstrSet(), lldb_private::DecodeImmShiftARM(), dwarf_cpsr, lldb_private::EmulateInstruction::eContextAdjustPC, eEncodingA1, eEncodingA2, eEncodingT1, lldb::eRegisterKindDWARF, InITBlock(), LastInITBlock(), NOT(), ReadCoreReg(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetImmediate(), lldb_private::Shift(), and lldb_private::EmulateInstruction::Context::type.
Referenced by EmulateADCImm(), EmulateADCReg(), EmulateANDImm(), EmulateANDReg(), EmulateBICImm(), EmulateBICReg(), EmulateEORImm(), EmulateEORReg(), EmulateMOVRdImm(), EmulateMOVRdRm(), EmulateMVNImm(), EmulateORRImm(), EmulateORRReg(), EmulateRSBImm(), EmulateRSBReg(), EmulateRSCImm(), EmulateRSCReg(), EmulateSBCImm(), EmulateSBCReg(), EmulateSUBImmARM(), EmulateSUBReg(), EmulateSUBSPImm(), EmulateSUBSPReg(), GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateSUBSPImm()
bool EmulateInstructionARM::EmulateSUBSPImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 2371 of file EmulateInstructionARM.cpp.
References AddWithCarry(), ALUWritePC(), lldb_private::ARMExpandImm(), lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, eEncodingT2, eEncodingT3, EmulateCMPImm(), EmulateSUBSPcLrEtc(), NOT(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetImmediateSigned(), lldb_private::EmulateInstruction::Context::SetNoArgs(), sp, SP_REG, lldb_private::ThumbExpandImm(), lldb_private::ThumbImm12(), lldb_private::ThumbImm7Scaled(), lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by EmulateSUBImmARM(), EmulateSUBImmThumb(), GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateSUBSPReg()
bool EmulateInstructionARM::EmulateSUBSPReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 9988 of file EmulateInstructionARM.cpp.
References AddWithCarry(), ALUWritePC(), APSR_C, lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::EmulateInstructionARM::AddWithCarryResult::carry_out, ConditionPassed(), lldb_private::DecodeImmShiftARM(), lldb_private::DecodeImmShiftThumb(), dwarf_r0, dwarf_sp, lldb_private::EmulateInstruction::eContextArithmetic, eEncodingA1, eEncodingT1, EmulateSUBSPcLrEtc(), lldb::eRegisterKindDWARF, GetRegisterInfo(), NOT(), lldb_private::EmulateInstructionARM::AddWithCarryResult::overflow, ReadCoreReg(), lldb_private::EmulateInstructionARM::AddWithCarryResult::result, lldb_private::EmulateInstruction::Context::SetRegisterRegisterOperands(), lldb_private::Shift(), SP_REG, lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, and WriteCoreRegOptionalFlags().
Referenced by EmulateSUBReg(), GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateSVC()
bool EmulateInstructionARM::EmulateSVC (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 2733 of file EmulateInstructionARM.cpp.
References lldb_private::Bits32(), ConditionPassed(), lldb_private::EmulateInstruction::eContextSupervisorCall, eEncodingA1, eEncodingT1, eModeARM, eModeThumb, lldb::eRegisterKindGeneric, LLDB_REGNUM_GENERIC_RA, pc, PC_REG, ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetISAAndImmediate(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateSXTB()
bool EmulateInstructionARM::EmulateSXTB (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 8321 of file EmulateInstructionARM.cpp.
References lldb_private::BadReg(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingT1, eEncodingT2, lldb::eRegisterKindDWARF, GetRegisterInfo(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::ROR(), lldb_private::EmulateInstruction::Context::SetRegister(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateSXTH()
bool EmulateInstructionARM::EmulateSXTH (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 8406 of file EmulateInstructionARM.cpp.
References lldb_private::BadReg(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingT1, eEncodingT2, lldb::eRegisterKindDWARF, GetRegisterInfo(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::ROR(), lldb_private::EmulateInstruction::Context::SetRegister(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateTB()
bool EmulateInstructionARM::EmulateTB (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 2936 of file EmulateInstructionARM.cpp.
References lldb_private::BadReg(), lldb_private::BitIsSet(), lldb_private::Bits32(), BranchWritePC(), ConditionPassed(), lldb_private::EmulateInstruction::eContextRelativeBranchImmediate, lldb_private::EmulateInstruction::eContextTableBranchReadMemory, eEncodingT1, eModeThumb, InITBlock(), LastInITBlock(), lldb_private::LSL(), MemURead(), pc, PC_REG, ReadCoreReg(), lldb_private::EmulateInstruction::Context::type, and UInt.
Referenced by GetThumbOpcodeForInstruction().
EmulateTEQImm()
bool EmulateInstructionARM::EmulateTEQImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 9734 of file EmulateInstructionARM.cpp.
References APSR_C, lldb_private::ARMExpandImm_C(), lldb_private::BadReg(), lldb_private::Bits32(), ConditionPassed(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::ThumbExpandImm_C(), lldb_private::EmulateInstruction::Context::type, and WriteFlags().
Referenced by EmulateEORImm(), GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateTEQReg()
bool EmulateInstructionARM::EmulateTEQReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 9793 of file EmulateInstructionARM.cpp.
References APSR_C, lldb_private::BadReg(), lldb_private::Bits32(), ConditionPassed(), lldb_private::DecodeImmShiftARM(), lldb_private::DecodeImmShiftThumb(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::Shift_C(), lldb_private::EmulateInstruction::Context::type, and WriteFlags().
Referenced by EmulateEORReg(), GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateTSTImm()
bool EmulateInstructionARM::EmulateTSTImm (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 9859 of file EmulateInstructionARM.cpp.
References APSR_C, lldb_private::ARMExpandImm_C(), lldb_private::BadReg(), lldb_private::Bits32(), ConditionPassed(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::ThumbExpandImm_C(), lldb_private::EmulateInstruction::Context::type, and WriteFlags().
Referenced by EmulateANDImm(), GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateTSTReg()
bool EmulateInstructionARM::EmulateTSTReg (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 9918 of file EmulateInstructionARM.cpp.
References APSR_C, lldb_private::BadReg(), lldb_private::Bits32(), ConditionPassed(), lldb_private::DecodeImmShiftARM(), lldb_private::DecodeImmShiftThumb(), lldb_private::EmulateInstruction::eContextImmediate, eEncodingA1, eEncodingT1, eEncodingT2, ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::Shift_C(), lldb_private::SRType_LSL, lldb_private::EmulateInstruction::Context::type, and WriteFlags().
Referenced by EmulateANDReg(), GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateUXTB()
bool EmulateInstructionARM::EmulateUXTB (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 8491 of file EmulateInstructionARM.cpp.
References lldb_private::BadReg(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingT1, eEncodingT2, lldb::eRegisterKindDWARF, GetRegisterInfo(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::ROR(), lldb_private::EmulateInstruction::Context::SetRegister(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateUXTH()
bool EmulateInstructionARM::EmulateUXTH (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 8574 of file EmulateInstructionARM.cpp.
References lldb_private::BadReg(), lldb_private::Bits32(), ConditionPassed(), dwarf_r0, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingT1, eEncodingT2, lldb::eRegisterKindDWARF, GetRegisterInfo(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::ROR(), lldb_private::EmulateInstruction::Context::SetRegister(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateVLD1Multiple()
bool EmulateInstructionARM::EmulateVLD1Multiple (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 11847 of file EmulateInstructionARM.cpp.
References lldb_private::Bit32(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), dwarf_d0, dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingT1, lldb::eRegisterKindDWARF, GetRegisterInfo(), MemURead(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateVLD1Single()
bool EmulateInstructionARM::EmulateVLD1Single (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 12005 of file EmulateInstructionARM.cpp.
References lldb_private::Bit32(), lldb_private::BitIsClear(), lldb_private::Bits32(), lldb_private::Bits64(), ConditionPassed(), dwarf_d0, dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingT1, EmulateVLD1SingleAll(), lldb::eRegisterKindDWARF, GetRegisterInfo(), MemURead(), ReadCoreReg(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateVLD1SingleAll()
bool EmulateInstructionARM::EmulateVLD1SingleAll (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 12496 of file EmulateInstructionARM.cpp.
References lldb_private::Bit32(), lldb_private::BitIsClear(), lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::Bits64(), ConditionPassed(), dwarf_d0, dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingT1, lldb::eRegisterKindDWARF, GetRegisterInfo(), MemURead(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by EmulateVLD1Single(), GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateVLDM()
bool EmulateInstructionARM::EmulateVLDM (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 11190 of file EmulateInstructionARM.cpp.
References lldb_private::Bit32(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), CurrentInstrSet(), dwarf_d0, dwarf_r0, dwarf_s0, lldb::eByteOrderBig, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingA2, eEncodingT1, eEncodingT2, eModeARM, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), lldb_private::EmulateInstruction::GetByteOrder(), GetRegisterInfo(), MemARead(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetImmediateSigned(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateVLDR()
bool EmulateInstructionARM::EmulateVLDR (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 11588 of file EmulateInstructionARM.cpp.
References lldb_private::Align(), AlignPC, lldb_private::Bit32(), lldb_private::BitIsSet(), lldb_private::Bits32(), ConditionPassed(), dwarf_d0, dwarf_r0, dwarf_s0, lldb::eByteOrderBig, lldb_private::EmulateInstruction::eContextRegisterLoad, eEncodingA1, eEncodingA2, eEncodingT1, eEncodingT2, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), lldb_private::EmulateInstruction::GetByteOrder(), GetRegisterInfo(), MemARead(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateVPOP()
bool EmulateInstructionARM::EmulateVPOP (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 2644 of file EmulateInstructionARM.cpp.
References lldb_private::Bit32(), lldb_private::Bits32(), ConditionPassed(), dwarf_d0, dwarf_s0, lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb_private::EmulateInstruction::eContextPopRegisterOffStack, eEncodingA1, eEncodingA2, eEncodingT1, eEncodingT2, lldb::eRegisterKindDWARF, lldb::eRegisterKindGeneric, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), LLDB_REGNUM_GENERIC_SP, MemARead(), ReadCoreReg(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::SetImmediateSigned(), sp, SP_REG, lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateVPUSH()
bool EmulateInstructionARM::EmulateVPUSH (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 2551 of file EmulateInstructionARM.cpp.
References lldb_private::Bit32(), lldb_private::Bits32(), ConditionPassed(), dwarf_d0, dwarf_s0, dwarf_sp, lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb_private::EmulateInstruction::eContextPushRegisterOnStack, eEncodingA1, eEncodingA2, eEncodingT1, eEncodingT2, lldb::eRegisterKindDWARF, lldb::eRegisterKindGeneric, lldb_private::EmulateInstruction::GetAddressByteSize(), GetRegisterInfo(), LLDB_REGNUM_GENERIC_SP, MemAWrite(), ReadCoreReg(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetImmediateSigned(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), sp, SP_REG, lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateVST1Multiple()
bool EmulateInstructionARM::EmulateVST1Multiple (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 12181 of file EmulateInstructionARM.cpp.
References lldb_private::Bit32(), lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::Bits64(), ConditionPassed(), dwarf_d0, dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterStore, eEncodingA1, eEncodingT1, lldb::eRegisterKindDWARF, GetRegisterInfo(), MemUWrite(), ReadCoreReg(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateVST1Single()
bool EmulateInstructionARM::EmulateVST1Single (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 12337 of file EmulateInstructionARM.cpp.
References lldb_private::Bit32(), lldb_private::BitIsClear(), lldb_private::Bits32(), lldb_private::Bits64(), ConditionPassed(), dwarf_d0, dwarf_r0, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterStore, eEncodingA1, eEncodingT1, lldb::eRegisterKindDWARF, GetRegisterInfo(), MemUWrite(), ReadCoreReg(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateVSTM()
bool EmulateInstructionARM::EmulateVSTM (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 11383 of file EmulateInstructionARM.cpp.
References lldb_private::Bit32(), lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::Bits64(), ConditionPassed(), CurrentInstrSet(), dwarf_d0, dwarf_r0, dwarf_s0, lldb::eByteOrderBig, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextRegisterStore, eEncodingA1, eEncodingA2, eEncodingT1, eEncodingT2, eModeARM, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), lldb_private::EmulateInstruction::GetByteOrder(), GetRegisterInfo(), MemAWrite(), ReadCoreReg(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EmulateVSTR()
bool EmulateInstructionARM::EmulateVSTR (const uint32_t opcode, const ARMEncoding encoding) protected
Definition at line 11715 of file EmulateInstructionARM.cpp.
References lldb_private::Bit32(), lldb_private::BitIsSet(), lldb_private::Bits32(), lldb_private::Bits64(), ConditionPassed(), CurrentInstrSet(), dwarf_d0, dwarf_r0, dwarf_s0, lldb::eByteOrderBig, lldb_private::EmulateInstruction::eContextRegisterStore, eEncodingA1, eEncodingA2, eEncodingT1, eEncodingT2, eModeARM, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::GetAddressByteSize(), lldb_private::EmulateInstruction::GetByteOrder(), GetRegisterInfo(), MemAWrite(), ReadCoreReg(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), and lldb_private::EmulateInstruction::Context::type.
Referenced by GetARMOpcodeForInstruction(), and GetThumbOpcodeForInstruction().
EvaluateInstruction()
bool EmulateInstructionARM::EvaluateInstruction (uint32_t evaluate_options) override virtual
Implements lldb_private::EmulateInstruction.
Definition at line 14279 of file EmulateInstructionARM.cpp.
References lldb_private::EmulateInstructionARM::ARMOpcode::callback, dwarf_cpsr, dwarf_pc, lldb_private::EmulateInstruction::eContextAdvancePC, eModeARM, eModeThumb, EmulateIT(), lldb_private::EmulateInstructionARM::ARMOpcode::encoding, lldb::eRegisterKindDWARF, GetARMOpcodeForInstruction(), GetThumbOpcodeForInstruction(), m_arm_isa, m_ignore_conditions, m_it_session, lldb_private::EmulateInstruction::m_opcode, m_opcode_cpsr, m_opcode_mode, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by TestEmulation().
GetARMOpcodeForInstruction()
EmulateInstructionARM::ARMOpcode * EmulateInstructionARM::GetARMOpcodeForInstruction (const uint32_t opcode, uint32_t isa_mask) static protected
Definition at line 12810 of file EmulateInstructionARM.cpp.
References AdvancedSIMD, ARMV5_ABOVE, ARMV5TE_ABOVE, ARMV6_ABOVE, ARMV6T2_ABOVE, ARMvAll, eEncodingA1, eEncodingA2, EmulateADCImm(), EmulateADCReg(), EmulateADDImmARM(), EmulateADDRdSPImm(), EmulateADDReg(), EmulateADDRegShift(), EmulateADR(), EmulateANDImm(), EmulateANDReg(), EmulateASRImm(), EmulateASRReg(), EmulateB(), EmulateBICImm(), EmulateBICReg(), EmulateBLXImmediate(), EmulateBLXRm(), EmulateBXJRm(), EmulateBXRm(), EmulateCMNImm(), EmulateCMNReg(), EmulateCMPImm(), EmulateCMPReg(), EmulateEORImm(), EmulateEORReg(), EmulateLDM(), EmulateLDMDA(), EmulateLDMDB(), EmulateLDMIB(), EmulateLDRBLiteral(), EmulateLDRBRegister(), EmulateLDRDImmediate(), EmulateLDRDRegister(), EmulateLDRHLiteral(), EmulateLDRHRegister(), EmulateLDRImmediateARM(), EmulateLDRRegister(), EmulateLDRSBImmediate(), EmulateLDRSBLiteral(), EmulateLDRSBRegister(), EmulateLDRSHImmediate(), EmulateLDRSHLiteral(), EmulateLDRSHRegister(), EmulateLSLImm(), EmulateLSLReg(), EmulateLSRImm(), EmulateLSRReg(), EmulateMOVRdImm(), EmulateMOVRdRm(), EmulateMOVRdSP(), EmulateMUL(), EmulateMVNImm(), EmulateMVNReg(), EmulateORRImm(), EmulateORRReg(), EmulatePOP(), EmulatePUSH(), EmulateRFE(), EmulateRORImm(), EmulateRORReg(), EmulateRRX(), EmulateRSBImm(), EmulateRSBReg(), EmulateRSCImm(), EmulateRSCReg(), EmulateSBCImm(), EmulateSBCReg(), EmulateSTM(), EmulateSTMDA(), EmulateSTMDB(), EmulateSTMIB(), EmulateSTRBImmARM(), EmulateSTRDImm(), EmulateSTRDReg(), EmulateSTREX(), EmulateSTRHRegister(), EmulateSTRImmARM(), EmulateSTRRegister(), EmulateSTRRtSP(), EmulateSUBImmARM(), EmulateSUBIPSPImm(), EmulateSUBR7IPImm(), EmulateSUBReg(), EmulateSUBSPcLrEtc(), EmulateSUBSPImm(), EmulateSUBSPReg(), EmulateSVC(), EmulateSXTB(), EmulateSXTH(), EmulateTEQImm(), EmulateTEQReg(), EmulateTSTImm(), EmulateTSTReg(), EmulateUXTB(), EmulateUXTH(), EmulateVLD1Multiple(), EmulateVLD1Single(), EmulateVLD1SingleAll(), EmulateVLDM(), EmulateVLDR(), EmulateVPOP(), EmulateVPUSH(), EmulateVST1Multiple(), EmulateVST1Single(), EmulateVSTM(), EmulateVSTR(), eSize32, No_VFP, VFPv2_ABOVE, and VFPv2v3.
Referenced by EvaluateInstruction().
GetFramePointerDWARFRegisterNumber()
uint32_t EmulateInstructionARM::GetFramePointerDWARFRegisterNumber () const protected
Definition at line 857 of file EmulateInstructionARM.cpp.
References dwarf_r11, dwarf_r7, eModeThumb, lldb_private::EmulateInstruction::m_arch, and m_opcode_mode.
GetFramePointerRegisterNumber()
uint32_t EmulateInstructionARM::GetFramePointerRegisterNumber () const protected
Definition at line 821 of file EmulateInstructionARM.cpp.
References eModeThumb, LLDB_INVALID_REGNUM, lldb_private::EmulateInstruction::m_arch, and m_opcode_mode.
Referenced by EmulateADDImmARM(), EmulateADDRdSPImm(), EmulateLDRRtRnImm(), EmulateMOVRdRm(), and EmulateMOVRdSP().
GetInstructionCondition()
EmulateInstruction::InstructionCondition EmulateInstructionARM::GetInstructionCondition () override virtual
Reimplemented from lldb_private::EmulateInstruction.
Definition at line 14348 of file EmulateInstructionARM.cpp.
References CurrentCond(), lldb_private::EmulateInstruction::m_opcode, UINT32_MAX, and lldb_private::EmulateInstruction::UnconditionalCondition.
GetPluginDescriptionStatic()
llvm::StringRef EmulateInstructionARM::GetPluginDescriptionStatic () static
Definition at line 717 of file EmulateInstructionARM.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef lldb_private::EmulateInstructionARM::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 96 of file EmulateInstructionARM.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::EmulateInstructionARM::GetPluginNameStatic () inline static
Definition at line 75 of file EmulateInstructionARM.h.
Referenced by GetPluginName(), and Initialize().
GetRegisterInfo()
std::optional< RegisterInfo > EmulateInstructionARM::GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num) override virtual
Implements lldb_private::EmulateInstruction.
Definition at line 787 of file EmulateInstructionARM.cpp.
References dwarf_cpsr, dwarf_lr, dwarf_pc, dwarf_r7, dwarf_sp, lldb::eRegisterKindDWARF, lldb::eRegisterKindGeneric, GetARMDWARFRegisterInfo(), LLDB_REGNUM_GENERIC_FLAGS, LLDB_REGNUM_GENERIC_FP, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_RA, and LLDB_REGNUM_GENERIC_SP.
Referenced by EmulateADDImmARM(), EmulateADDImmThumb(), EmulateADDRdSPImm(), EmulateADDReg(), EmulateADDRegShift(), EmulateADDSPImm(), EmulateADDSPRm(), EmulateBLXRm(), EmulateBXJRm(), EmulateBXRm(), EmulateLDM(), EmulateLDMDA(), EmulateLDMDB(), EmulateLDMIB(), EmulateLDRBImmediate(), EmulateLDRBRegister(), EmulateLDRHImmediate(), EmulateLDRHLiteral(), EmulateLDRHRegister(), EmulateLDRImmediateARM(), EmulateLDRRegister(), EmulateLDRRtPCRelative(), EmulateLDRRtRnImm(), EmulateLDRSBImmediate(), EmulateLDRSBLiteral(), EmulateLDRSBRegister(), EmulateLDRSHImmediate(), EmulateLDRSHLiteral(), EmulateLDRSHRegister(), EmulateMOVRdRm(), EmulateMOVRdSP(), EmulateMUL(), EmulatePOP(), EmulatePUSH(), EmulateRFE(), EmulateSTM(), EmulateSTMDA(), EmulateSTMDB(), EmulateSTMIB(), EmulateSTRBImmARM(), EmulateSTRBThumb(), EmulateSTRDImm(), EmulateSTRDReg(), EmulateSTREX(), EmulateSTRHRegister(), EmulateSTRImmARM(), EmulateSTRRegister(), EmulateSTRRtSP(), EmulateSTRThumb(), EmulateSUBImmARM(), EmulateSUBIPSPImm(), EmulateSUBR7IPImm(), EmulateSUBReg(), EmulateSUBSPReg(), EmulateSXTB(), EmulateSXTH(), EmulateUXTB(), EmulateUXTH(), EmulateVLD1Multiple(), EmulateVLD1Single(), EmulateVLD1SingleAll(), EmulateVLDM(), EmulateVLDR(), EmulateVPOP(), EmulateVPUSH(), EmulateVST1Multiple(), EmulateVST1Single(), EmulateVSTM(), and EmulateVSTR().
GetSingleStepBreakpointLocationsPredictorCreator()
BreakpointLocationsPredictorCreator lldb_private::EmulateInstructionARM::GetSingleStepBreakpointLocationsPredictorCreator () inline override protected virtual
Reimplemented from lldb_private::EmulateInstruction.
Definition at line 784 of file EmulateInstructionARM.h.
GetThumbOpcodeForInstruction()
EmulateInstructionARM::ARMOpcode * EmulateInstructionARM::GetThumbOpcodeForInstruction (const uint32_t opcode, uint32_t isa_mask) static protected
Definition at line 13182 of file EmulateInstructionARM.cpp.
References AdvancedSIMD, ARMV4T_ABOVE, ARMV5_ABOVE, ARMV5J_ABOVE, ARMV6_ABOVE, ARMV6T2_ABOVE, ARMV7_ABOVE, ARMvAll, eEncodingT1, eEncodingT2, eEncodingT3, eEncodingT4, EmulateADCImm(), EmulateADCReg(), EmulateADDImmThumb(), EmulateADDRdSPImm(), EmulateADDReg(), EmulateADDSPImm(), EmulateADDSPRm(), EmulateADR(), EmulateANDImm(), EmulateANDReg(), EmulateASRImm(), EmulateASRReg(), EmulateB(), EmulateBICImm(), EmulateBICReg(), EmulateBLXImmediate(), EmulateBLXRm(), EmulateBXJRm(), EmulateBXRm(), EmulateCB(), EmulateCMNImm(), EmulateCMNReg(), EmulateCMPImm(), EmulateCMPReg(), EmulateEORImm(), EmulateEORReg(), EmulateIT(), EmulateLDM(), EmulateLDMDB(), EmulateLDRBImmediate(), EmulateLDRBLiteral(), EmulateLDRBRegister(), EmulateLDRDImmediate(), EmulateLDRHImmediate(), EmulateLDRHLiteral(), EmulateLDRHRegister(), EmulateLDRRegister(), EmulateLDRRtPCRelative(), EmulateLDRRtRnImm(), EmulateLDRSBImmediate(), EmulateLDRSBLiteral(), EmulateLDRSBRegister(), EmulateLDRSHImmediate(), EmulateLDRSHLiteral(), EmulateLDRSHRegister(), EmulateLSLImm(), EmulateLSLReg(), EmulateLSRImm(), EmulateLSRReg(), EmulateMOVLowHigh(), EmulateMOVRdImm(), EmulateMOVRdRm(), EmulateMOVRdSP(), EmulateMUL(), EmulateMVNImm(), EmulateMVNReg(), EmulateNop(), EmulateORRImm(), EmulateORRReg(), EmulatePOP(), EmulatePUSH(), EmulateRFE(), EmulateRORImm(), EmulateRORReg(), EmulateRRX(), EmulateRSBImm(), EmulateRSBReg(), EmulateSBCImm(), EmulateSBCReg(), EmulateSTM(), EmulateSTMDB(), EmulateSTRBThumb(), EmulateSTRDImm(), EmulateSTREX(), EmulateSTRHRegister(), EmulateSTRRegister(), EmulateSTRThumb(), EmulateSUBImmThumb(), EmulateSUBReg(), EmulateSUBSPcLrEtc(), EmulateSUBSPImm(), EmulateSUBSPReg(), EmulateSVC(), EmulateSXTB(), EmulateSXTH(), EmulateTB(), EmulateTEQImm(), EmulateTEQReg(), EmulateTSTImm(), EmulateTSTReg(), EmulateUXTB(), EmulateUXTH(), EmulateVLD1Multiple(), EmulateVLD1Single(), EmulateVLD1SingleAll(), EmulateVLDM(), EmulateVLDR(), EmulateVPOP(), EmulateVPUSH(), EmulateVST1Multiple(), EmulateVST1Single(), EmulateVSTM(), EmulateVSTR(), eSize16, eSize32, No_VFP, VFPv2_ABOVE, and VFPv2v3.
Referenced by EvaluateInstruction().
InITBlock()
bool EmulateInstructionARM::InITBlock ()
Definition at line 13948 of file EmulateInstructionARM.cpp.
References CurrentInstrSet(), eModeThumb, and m_it_session.
Referenced by EmulateADCReg(), EmulateADDImmThumb(), EmulateADDReg(), EmulateANDReg(), EmulateBICReg(), EmulateBLXImmediate(), EmulateBLXRm(), EmulateBXJRm(), EmulateBXRm(), EmulateEORReg(), EmulateLDM(), EmulateLDMDB(), EmulateLDRRegister(), EmulateLDRRtPCRelative(), EmulateLDRRtRnImm(), EmulateMOVRdImm(), EmulateMOVRdRm(), EmulateMUL(), EmulateMVNReg(), EmulateORRReg(), EmulatePOP(), EmulateRFE(), EmulateRSBImm(), EmulateSBCReg(), EmulateShiftImm(), EmulateShiftReg(), EmulateSUBImmThumb(), EmulateSUBReg(), EmulateSUBSPcLrEtc(), and EmulateTB().
Initialize()
void EmulateInstructionARM::Initialize () static
Definition at line 708 of file EmulateInstructionARM.cpp.
References CreateInstance(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
LastInITBlock()
bool EmulateInstructionARM::LastInITBlock ()
Definition at line 13952 of file EmulateInstructionARM.cpp.
References CurrentInstrSet(), eModeThumb, and m_it_session.
Referenced by EmulateADDReg(), EmulateBLXImmediate(), EmulateBLXRm(), EmulateBXJRm(), EmulateBXRm(), EmulateLDM(), EmulateLDMDB(), EmulateLDRRegister(), EmulateLDRRtPCRelative(), EmulateLDRRtRnImm(), EmulateMOVRdRm(), EmulatePOP(), EmulateRFE(), EmulateSUBSPcLrEtc(), and EmulateTB().
LoadWritePC()
bool EmulateInstructionARM::LoadWritePC (Context & context, uint32_t addr)
Definition at line 14080 of file EmulateInstructionARM.cpp.
References ArchVersion(), ARMv5T, BranchWritePC(), and BXWritePC().
Referenced by EmulateLDM(), EmulateLDMDA(), EmulateLDMDB(), EmulateLDMIB(), EmulateLDRImmediateARM(), EmulateLDRRegister(), EmulateLDRRtPCRelative(), EmulateLDRRtRnImm(), and EmulatePOP().
MemARead()
uint64_t lldb_private::EmulateInstructionARM::MemARead (EmulateInstruction::Context & context, lldb::addr_t address, uint32_t size, uint64_t fail_value, bool * success_ptr) inline
Definition at line 224 of file EmulateInstructionARM.h.
References lldb_private::EmulateInstruction::ReadMemoryUnsigned().
Referenced by EmulateLDM(), EmulateLDMDA(), EmulateLDMDB(), EmulateLDMIB(), EmulateLDRDImmediate(), EmulateLDRDRegister(), EmulatePOP(), EmulateRFE(), EmulateVLDM(), EmulateVLDR(), EmulateVPOP(), and ReadInstruction().
MemAWrite()
bool lldb_private::EmulateInstructionARM::MemAWrite (EmulateInstruction::Context & context, lldb::addr_t address, uint64_t data_val, uint32_t size) inline
Definition at line 242 of file EmulateInstructionARM.h.
References lldb_private::EmulateInstruction::WriteMemoryUnsigned().
Referenced by EmulatePUSH(), EmulateSTM(), EmulateSTMDA(), EmulateSTMDB(), EmulateSTMIB(), EmulateSTRDImm(), EmulateSTRDReg(), EmulateSTREX(), EmulateVPUSH(), EmulateVSTM(), EmulateVSTR(), and WriteBits32UnknownToMemory().
MemURead()
uint64_t lldb_private::EmulateInstructionARM::MemURead (EmulateInstruction::Context & context, lldb::addr_t address, uint32_t size, uint64_t fail_value, bool * success_ptr) inline
Definition at line 261 of file EmulateInstructionARM.h.
References lldb_private::EmulateInstruction::ReadMemoryUnsigned().
Referenced by EmulateLDRBImmediate(), EmulateLDRBLiteral(), EmulateLDRBRegister(), EmulateLDRHImmediate(), EmulateLDRHLiteral(), EmulateLDRHRegister(), EmulateLDRImmediateARM(), EmulateLDRRegister(), EmulateLDRRtPCRelative(), EmulateLDRRtRnImm(), EmulateLDRSBImmediate(), EmulateLDRSBLiteral(), EmulateLDRSBRegister(), EmulateLDRSHImmediate(), EmulateLDRSHLiteral(), EmulateLDRSHRegister(), EmulateTB(), EmulateVLD1Multiple(), EmulateVLD1Single(), and EmulateVLD1SingleAll().
MemUWrite()
bool lldb_private::EmulateInstructionARM::MemUWrite (EmulateInstruction::Context & context, lldb::addr_t address, uint64_t data_val, uint32_t size) inline
Definition at line 279 of file EmulateInstructionARM.h.
References lldb_private::EmulateInstruction::WriteMemoryUnsigned().
Referenced by EmulateSTRBImmARM(), EmulateSTRBThumb(), EmulateSTRHRegister(), EmulateSTRImmARM(), EmulateSTRRegister(), EmulateSTRRtSP(), EmulateSTRThumb(), EmulateVST1Multiple(), and EmulateVST1Single().
ReadCoreReg()
uint32_t EmulateInstructionARM::ReadCoreReg (uint32_t regnum, bool * success)
Definition at line 14159 of file EmulateInstructionARM.cpp.
References CurrentInstrSet(), dwarf_r0, eModeARM, lldb::eRegisterKindDWARF, lldb::eRegisterKindGeneric, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_RA, LLDB_REGNUM_GENERIC_SP, LR_REG, PC_REG, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), SP_REG, and UINT32_MAX.
Referenced by EmulateADCImm(), EmulateADCReg(), EmulateADDImmARM(), EmulateADDRdSPImm(), EmulateADDReg(), EmulateADDRegShift(), EmulateADDSPImm(), EmulateADDSPRm(), EmulateADR(), EmulateANDImm(), EmulateANDReg(), EmulateB(), EmulateBICImm(), EmulateBICReg(), EmulateBLXImmediate(), EmulateBLXRm(), EmulateBXJRm(), EmulateBXRm(), EmulateCB(), EmulateCMNImm(), EmulateCMNReg(), EmulateCMPImm(), EmulateCMPReg(), EmulateEORImm(), EmulateEORReg(), EmulateLDMDA(), EmulateLDRBLiteral(), EmulateLDRDImmediate(), EmulateLDRDRegister(), EmulateLDRHLiteral(), EmulateLDRImmediateARM(), EmulateLDRRtPCRelative(), EmulateLDRRtRnImm(), EmulateLDRSBImmediate(), EmulateLDRSBLiteral(), EmulateLDRSHLiteral(), EmulateMOVRdRm(), EmulateMOVRdSP(), EmulateMVNReg(), EmulateORRImm(), EmulateORRReg(), EmulatePOP(), EmulatePUSH(), EmulateRSBImm(), EmulateRSBReg(), EmulateRSCImm(), EmulateRSCReg(), EmulateSBCImm(), EmulateSBCReg(), EmulateShiftImm(), EmulateShiftReg(), EmulateSTM(), EmulateSTMDA(), EmulateSTMDB(), EmulateSTMIB(), EmulateSTRBImmARM(), EmulateSTRDImm(), EmulateSTRDReg(), EmulateSTREX(), EmulateSTRHRegister(), EmulateSTRImmARM(), EmulateSTRRegister(), EmulateSTRRtSP(), EmulateSTRThumb(), EmulateSUBImmARM(), EmulateSUBImmThumb(), EmulateSUBIPSPImm(), EmulateSUBR7IPImm(), EmulateSUBReg(), EmulateSUBSPcLrEtc(), EmulateSUBSPImm(), EmulateSUBSPReg(), EmulateSVC(), EmulateTB(), EmulateTEQImm(), EmulateTEQReg(), EmulateTSTImm(), EmulateTSTReg(), EmulateVLD1Multiple(), EmulateVLD1Single(), EmulateVLD1SingleAll(), EmulateVLDM(), EmulateVLDR(), EmulateVPOP(), EmulateVPUSH(), EmulateVST1Multiple(), EmulateVST1Single(), EmulateVSTM(), and EmulateVSTR().
ReadInstruction()
bool EmulateInstructionARM::ReadInstruction () override virtual
Implements lldb_private::EmulateInstruction.
Definition at line 13791 of file EmulateInstructionARM.cpp.
References lldb_private::Bits32(), lldb_private::EmulateInstruction::eContextReadOpcode, eModeARM, eModeInvalid, eModeThumb, lldb::eRegisterKindGeneric, lldb_private::EmulateInstruction::GetByteOrder(), LLDB_INVALID_ADDRESS, LLDB_REGNUM_GENERIC_FLAGS, LLDB_REGNUM_GENERIC_PC, lldb_private::EmulateInstruction::m_addr, lldb_private::EmulateInstruction::m_arch, m_ignore_conditions, m_it_session, lldb_private::EmulateInstruction::m_opcode, m_opcode_cpsr, m_opcode_mode, MASK_CPSR_T, MemARead(), pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetNoArgs(), and lldb_private::EmulateInstruction::Context::type.
SelectInstrSet()
bool EmulateInstructionARM::SelectInstrSet (Mode arm_or_thumb)
Definition at line 14103 of file EmulateInstructionARM.cpp.
References eModeARM, eModeThumb, m_new_inst_cpsr, m_opcode_cpsr, and MASK_CPSR_T.
Referenced by BXWritePC(), and EmulateBLXImmediate().
SetArchitecture()
bool EmulateInstructionARM::SetArchitecture (const ArchSpec & arch) virtual
Definition at line 13731 of file EmulateInstructionARM.cpp.
References ARMv4, ARMv4T, ARMv5T, ARMv5TE, ARMv5TEJ, ARMv6, ARMv6K, ARMv6T2, ARMv7, ARMv7S, ARMv8, ARMvAll, lldb_private::ArchSpec::GetArchitectureName(), lldb_private::EmulateInstruction::m_arch, and m_arm_isa.
Referenced by EmulateInstructionARM().
SetInstruction()
bool EmulateInstructionARM::SetInstruction (const Opcode & insn_opcode, const Address & inst_addr, Target * target) override virtual
Reimplemented from lldb_private::EmulateInstruction.
Definition at line 13764 of file EmulateInstructionARM.cpp.
References CPSR_MODE_USR, lldb_private::eCode, lldb_private::eCodeAlternateISA, eModeARM, eModeThumb, lldb_private::eUnknown, lldb_private::Address::GetAddressClass(), lldb_private::EmulateInstruction::m_arch, m_opcode_cpsr, m_opcode_mode, MASK_CPSR_T, and lldb_private::EmulateInstruction::SetInstruction().
SetTargetTriple()
bool EmulateInstructionARM::SetTargetTriple (const ArchSpec & arch) override virtual
Implements lldb_private::EmulateInstruction.
Definition at line 744 of file EmulateInstructionARM.cpp.
References lldb_private::ArchSpec::GetTriple().
SupportsEmulatingInstructionsOfType()
bool lldb_private::EmulateInstructionARM::SupportsEmulatingInstructionsOfType (InstructionType inst_type) inline override virtual
Implements lldb_private::EmulateInstruction.
Definition at line 130 of file EmulateInstructionARM.h.
References SupportsEmulatingInstructionsOfTypeStatic().
SupportsEmulatingInstructionsOfTypeStatic()
bool lldb_private::EmulateInstructionARM::SupportsEmulatingInstructionsOfTypeStatic (InstructionType inst_type) inline static
Definition at line 83 of file EmulateInstructionARM.h.
References lldb_private::eInstructionTypeAll, lldb_private::eInstructionTypeAny, lldb_private::eInstructionTypePCModifying, and lldb_private::eInstructionTypePrologueEpilogue.
Referenced by CreateInstance(), and SupportsEmulatingInstructionsOfType().
Terminate()
void EmulateInstructionARM::Terminate () static
Definition at line 713 of file EmulateInstructionARM.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
TestEmulation()
bool EmulateInstructionARM::TestEmulation (Stream & out_stream, ArchSpec & arch, OptionValueDictionary * test_data) override virtual
Implements lldb_private::EmulateInstruction.
Definition at line 14355 of file EmulateInstructionARM.cpp.
References EmulationStateARM::CompareState(), eModeARM, eModeThumb, lldb_private::OptionValue::eTypeDictionary, lldb_private::OptionValue::eTypeUInt64, EvaluateInstruction(), lldb_private::ArchSpec::GetTriple(), lldb_private::OptionValueDictionary::GetValueForKey(), lldb_private::endian::InlHostByteOrder(), lldb_private::ArchSpec::IsAlwaysThumbInstructions(), EmulationStateARM::LoadStateFromDictionary(), lldb_private::EmulateInstruction::m_opcode, m_opcode_mode, lldb_private::Stream::Printf(), EmulationStateARM::ReadPseudoMemory(), EmulationStateARM::ReadPseudoRegister(), lldb_private::EmulateInstruction::SetBaton(), lldb_private::EmulateInstruction::SetCallbacks(), EmulationStateARM::WritePseudoMemory(), and EmulationStateARM::WritePseudoRegister().
UnalignedSupport()
bool EmulateInstructionARM::UnalignedSupport ()
Definition at line 14123 of file EmulateInstructionARM.cpp.
References ArchVersion(), and ARMv7.
Referenced by EmulateLDRHImmediate(), EmulateLDRHLiteral(), EmulateLDRHRegister(), EmulateLDRImmediateARM(), EmulateLDRRegister(), EmulateLDRRtPCRelative(), EmulateLDRRtRnImm(), EmulateLDRSHImmediate(), EmulateLDRSHLiteral(), EmulateLDRSHRegister(), EmulateSTRHRegister(), EmulateSTRRegister(), and EmulateSTRThumb().
WriteBits32Unknown()
bool EmulateInstructionARM::WriteBits32Unknown (int n)
Definition at line 768 of file EmulateInstructionARM.cpp.
References dwarf_r0, lldb_private::EmulateInstruction::eContextWriteRegisterRandomBits, lldb::eRegisterKindDWARF, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by EmulateLDM(), EmulateLDMDA(), EmulateLDMDB(), EmulateLDMIB(), EmulateLDRHImmediate(), EmulateLDRHLiteral(), EmulateLDRHRegister(), EmulateLDRRegister(), EmulateLDRRtRnImm(), EmulateLDRSHImmediate(), EmulateLDRSHLiteral(), and EmulateLDRSHRegister().
WriteBits32UnknownToMemory()
bool EmulateInstructionARM::WriteBits32UnknownToMemory (lldb::addr_t address)
Definition at line 755 of file EmulateInstructionARM.cpp.
References lldb_private::EmulateInstruction::eContextWriteMemoryRandomBits, lldb_private::EmulateInstruction::GetAddressByteSize(), MemAWrite(), lldb_private::EmulateInstruction::Context::SetNoArgs(), and lldb_private::EmulateInstruction::Context::type.
Referenced by EmulateSTM(), EmulateSTMDA(), EmulateSTMDB(), EmulateSTMIB(), EmulateSTRRegister(), and EmulateSTRThumb().
WriteCoreReg()
bool lldb_private::EmulateInstructionARM::WriteCoreReg (Context & context, const uint32_t result, const uint32_t Rd) inline
Definition at line 211 of file EmulateInstructionARM.h.
References WriteCoreRegOptionalFlags().
Referenced by EmulateADR().
WriteCoreRegOptionalFlags()
bool EmulateInstructionARM::WriteCoreRegOptionalFlags (Context & context, const uint32_t result, const uint32_t Rd, bool setflags, const uint32_t carry = ~0u, const uint32_t overflow = ~0u)
Definition at line 14221 of file EmulateInstructionARM.cpp.
References ALUWritePC(), dwarf_r0, lldb::eRegisterKindDWARF, lldb::eRegisterKindGeneric, LLDB_REGNUM_GENERIC_RA, LLDB_REGNUM_GENERIC_SP, LR_REG, SP_REG, WriteFlags(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by EmulateADCImm(), EmulateADCReg(), EmulateADDImmARM(), EmulateADDImmThumb(), EmulateADDReg(), EmulateADDSPImm(), EmulateANDImm(), EmulateANDReg(), EmulateBICImm(), EmulateBICReg(), EmulateEORImm(), EmulateEORReg(), EmulateMOVRdImm(), EmulateMOVRdRm(), EmulateMVNImm(), EmulateMVNReg(), EmulateORRImm(), EmulateORRReg(), EmulateRSBImm(), EmulateRSBReg(), EmulateRSCImm(), EmulateRSCReg(), EmulateSBCImm(), EmulateSBCReg(), EmulateShiftImm(), EmulateShiftReg(), EmulateSUBImmARM(), EmulateSUBImmThumb(), EmulateSUBReg(), EmulateSUBSPImm(), EmulateSUBSPReg(), and WriteCoreReg().
WriteFlags()
bool EmulateInstructionARM::WriteFlags (Context & context, const uint32_t result, const uint32_t carry = ~0u, const uint32_t overflow = ~0u)
Definition at line 14261 of file EmulateInstructionARM.cpp.
References lldb_private::Bit32(), CPSR_C_POS, CPSR_N_POS, CPSR_V_POS, CPSR_Z_POS, lldb::eRegisterKindGeneric, LLDB_REGNUM_GENERIC_FLAGS, m_new_inst_cpsr, m_opcode_cpsr, lldb_private::SetBit32(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by EmulateADDRegShift(), EmulateCMNImm(), EmulateCMNReg(), EmulateCMPImm(), EmulateCMPReg(), EmulateTEQImm(), EmulateTEQReg(), EmulateTSTImm(), EmulateTSTReg(), and WriteCoreRegOptionalFlags().
Member Data Documentation
m_arm_isa
uint32_t lldb_private::EmulateInstructionARM::m_arm_isa protected
Definition at line 791 of file EmulateInstructionARM.h.
Referenced by ArchVersion(), EmulateInstructionARM(), EvaluateInstruction(), and SetArchitecture().
m_ignore_conditions
bool lldb_private::EmulateInstructionARM::m_ignore_conditions protected
Definition at line 796 of file EmulateInstructionARM.h.
Referenced by ConditionPassed(), EmulateCB(), EmulateInstructionARM(), EvaluateInstruction(), and ReadInstruction().
m_it_session
ITSession lldb_private::EmulateInstructionARM::m_it_session protected
Definition at line 795 of file EmulateInstructionARM.h.
Referenced by CurrentCond(), EmulateInstructionARM(), EmulateIT(), EvaluateInstruction(), InITBlock(), LastInITBlock(), and ReadInstruction().
m_new_inst_cpsr
uint32_t lldb_private::EmulateInstructionARM::m_new_inst_cpsr protected
Definition at line 794 of file EmulateInstructionARM.h.
Referenced by BXWritePC(), EmulateBLXImmediate(), EmulateInstructionARM(), EmulateMUL(), SelectInstrSet(), and WriteFlags().
m_opcode_cpsr
uint32_t lldb_private::EmulateInstructionARM::m_opcode_cpsr protected
Definition at line 793 of file EmulateInstructionARM.h.
Referenced by ConditionPassed(), CPSRWriteByInstr(), CurrentModeIsPrivileged(), EmulateBLXImmediate(), EmulateInstructionARM(), EmulateLDRRegister(), EmulateMUL(), EvaluateInstruction(), ReadInstruction(), SelectInstrSet(), SetInstruction(), and WriteFlags().
m_opcode_mode
Mode lldb_private::EmulateInstructionARM::m_opcode_mode protected
Definition at line 792 of file EmulateInstructionARM.h.
Referenced by CurrentCond(), CurrentInstrSet(), EmulateInstructionARM(), EvaluateInstruction(), GetFramePointerDWARFRegisterNumber(), GetFramePointerRegisterNumber(), ReadInstruction(), SetInstruction(), and TestEmulation().
The documentation for this class was generated from the following files:
EmulateInstructionARM.h
EmulateInstructionARM.cpp