LLDB: lldb::SBCommandReturnObject Class Reference
lldb::SBCommandReturnObject Class Reference
#include <SBCommandReturnObject.h>
Public Member Functions
SBCommandReturnObject ()
SBCommandReturnObject (const lldb::SBCommandReturnObject &rhs)
~SBCommandReturnObject ()
lldb::SBCommandReturnObject & operator= (const lldb::SBCommandReturnObject &rhs)
operator bool () const
bool IsValid () const
const char * GetCommand ()
Get the command as the user typed it.
const char * GetOutput ()
const char * GetError ()
SBStructuredData GetErrorData ()
LLDB_DEPRECATED_FIXME ("Use PutOutput(SBFile) or PutOutput(FileSP)", "PutOutput(SBFile)") size_t PutOutput(FILE *fh)
size_t PutOutput (SBFile file)
size_t PutOutput (FileSP BORROWED)
size_t GetOutputSize ()
size_t GetErrorSize ()
LLDB_DEPRECATED_FIXME ("Use PutError(SBFile) or PutError(FileSP)", "PutError(SBFile)") size_t PutError(FILE *fh)
size_t PutError (SBFile file)
size_t PutError (FileSP BORROWED)
void Clear ()
lldb::ReturnStatus GetStatus ()
void SetStatus (lldb::ReturnStatus status)
bool Succeeded ()
bool HasResult ()
void AppendMessage (const char *message)
void AppendWarning (const char *message)
bool GetDescription (lldb::SBStream &description)
LLDB_DEPRECATED_FIXME ("Use SetImmediateOutputFile(SBFile) or SetImmediateOutputFile(FileSP)", "SetImmediateOutputFile(SBFile)") void SetImmediateOutputFile(FILE *fh)
LLDB_DEPRECATED_FIXME ("Use SetImmediateErrorFile(SBFile) or SetImmediateErrorFile(FileSP)", "SetImmediateErrorFile(SBFile)") void SetImmediateErrorFile(FILE *fh)
LLDB_DEPRECATED_FIXME ("Use SetImmediateOutputFile(SBFile) or SetImmediateOutputFile(FileSP)", "SetImmediateOutputFile(SBFile)") void SetImmediateOutputFile(FILE *fh
LLDB_DEPRECATED_FIXME ("Use SetImmediateErrorFile(SBFile) or SetImmediateErrorFile(FileSP)", "SetImmediateErrorFile(SBFile)") void SetImmediateErrorFile(FILE *fh
void SetImmediateOutputFile (SBFile file)
void SetImmediateErrorFile (SBFile file)
void SetImmediateOutputFile (FileSP BORROWED)
void SetImmediateErrorFile (FileSP BORROWED)
void PutCString (const char *string, int len=-1)
__attribute__ ((format(printf, 2, 3))) size_t Printf(const char *format
const char * GetOutput (bool only_if_no_immediate)
const char * GetError (bool only_if_no_immediate)
void SetError (lldb::SBError &error, const char *fallback_error_cstr=nullptr)
void SetError (const char *error_cstr)
lldb::SBValueList GetValues (lldb::DynamicValueType use_dynamic)
Public Attributes
bool transfer_ownership
Protected Member Functions
SBCommandReturnObject (lldb_private::CommandReturnObject &ref)
lldb_private::CommandReturnObject * operator-> () const
lldb_private::CommandReturnObject * get () const
lldb_private::CommandReturnObject & operator* () const
Private Member Functions
lldb_private::CommandReturnObject & ref () const
Private Attributes
std::unique_ptr< lldb_private::SBCommandReturnObjectImpl > m_opaque_up
Friends
class SBCommandInterpreter
class SBOptions
class lldb_private::CommandPluginInterfaceImplementation
class lldb_private::python::SWIGBridge
Detailed Description
Definition at line 28 of file SBCommandReturnObject.h.
Constructor & Destructor Documentation
SBCommandReturnObject() [1/3]
SBCommandReturnObject::SBCommandReturnObject ()
Definition at line 53 of file SBCommandReturnObject.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb_private::python::SWIGBridge, operator=(), and SBCommandReturnObject().
SBCommandReturnObject() [2/3]
SBCommandReturnObject::SBCommandReturnObject (const lldb::SBCommandReturnObject & rhs)
Definition at line 63 of file SBCommandReturnObject.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBCommandReturnObject().
~SBCommandReturnObject()
SBCommandReturnObject::~SBCommandReturnObject () default
References GetCommand(), GetError(), GetErrorData(), GetOutput(), IsValid(), and operator=().
SBCommandReturnObject() [3/3]
SBCommandReturnObject::SBCommandReturnObject (lldb_private::CommandReturnObject & ref) protected
Definition at line 58 of file SBCommandReturnObject.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and ref().
Member Function Documentation
__attribute__()
lldb::SBCommandReturnObject::__attribute__ ((format(printf, 2, 3))) const
References error(), GetError(), GetOutput(), GetValues(), and SetError().
AppendMessage()
void SBCommandReturnObject::AppendMessage (const char * message)
Definition at line 211 of file SBCommandReturnObject.cpp.
References lldb_private::CommandReturnObject::AppendMessage(), LLDB_INSTRUMENT_VA, and ref().
Referenced by lldb::SBProcess::AppendEventStateReport(), and LLDB_DEPRECATED_FIXME().
AppendWarning()
void SBCommandReturnObject::AppendWarning (const char * message)
Definition at line 217 of file SBCommandReturnObject.cpp.
References lldb_private::CommandReturnObject::AppendWarning(), LLDB_INSTRUMENT_VA, and ref().
Referenced by LLDB_DEPRECATED_FIXME().
Clear()
void SBCommandReturnObject::Clear ()
Definition at line 181 of file SBCommandReturnObject.cpp.
References lldb_private::CommandReturnObject::Clear(), LLDB_INSTRUMENT_VA, and ref().
Referenced by lldb::SBCommandInterpreter::HandleCommand(), LLDB_DEPRECATED_FIXME(), lldb::SBCommandInterpreter::ResolveCommand(), lldb::SBCommandInterpreter::SourceInitFileInCurrentWorkingDirectory(), lldb::SBCommandInterpreter::SourceInitFileInGlobalDirectory(), and lldb::SBCommandInterpreter::SourceInitFileInHomeDirectory().
get()
CommandReturnObject * SBCommandReturnObject::get () const protected
Definition at line 227 of file SBCommandReturnObject.cpp.
References m_opaque_up.
Referenced by GetError(), GetOutput(), and lldb_private::python::SWIGBridge.
GetCommand()
const char * SBCommandReturnObject::GetCommand ()
Get the command as the user typed it.
Empty string if commands were run on behalf of lldb.
Definition at line 91 of file SBCommandReturnObject.cpp.
References lldb_private::ConstString::AsCString(), GetCommand(), LLDB_INSTRUMENT_VA, and ref().
Referenced by GetCommand(), and ~SBCommandReturnObject().
GetDescription()
bool SBCommandReturnObject::GetDescription (lldb::SBStream & description)
Definition at line 239 of file SBCommandReturnObject.cpp.
References lldb::eReturnStatusInvalid, lldb::eReturnStatusStarted, GetError(), GetErrorSize(), GetOutput(), GetOutputSize(), lldb_private::CommandReturnObject::GetStatus(), LLDB_INSTRUMENT_VA, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), ref(), lldb::SBStream::ref(), and Succeeded().
Referenced by LLDB_DEPRECATED_FIXME().
GetError() [1/2]
const char * SBCommandReturnObject::GetError ()
Definition at line 105 of file SBCommandReturnObject.cpp.
References lldb_private::ConstString::AsCString(), LLDB_INSTRUMENT_VA, and ref().
Referenced by __attribute__(), GetDescription(), GetError(), PutError(), PutError(), and ~SBCommandReturnObject().
GetError() [2/2]
const char * SBCommandReturnObject::GetError (bool only_if_no_immediate)
Definition at line 333 of file SBCommandReturnObject.cpp.
References get(), GetError(), LLDB_INSTRUMENT_VA, and ref().
GetErrorData()
SBStructuredData SBCommandReturnObject::GetErrorData ()
Definition at line 112 of file SBCommandReturnObject.cpp.
References GetErrorData(), LLDB_INSTRUMENT_VA, lldb::SBStructuredData::m_impl_up, and ref().
Referenced by GetErrorData(), and ~SBCommandReturnObject().
GetErrorSize()
size_t SBCommandReturnObject::GetErrorSize ()
Definition at line 127 of file SBCommandReturnObject.cpp.
References lldb_private::CommandReturnObject::GetErrorString(), LLDB_INSTRUMENT_VA, and ref().
Referenced by GetDescription(), and LLDB_DEPRECATED_FIXME().
GetOutput() [1/2]
const char * SBCommandReturnObject::GetOutput ()
Definition at line 98 of file SBCommandReturnObject.cpp.
References lldb_private::ConstString::AsCString(), LLDB_INSTRUMENT_VA, and ref().
Referenced by __attribute__(), GetDescription(), GetOutput(), PutOutput(), PutOutput(), and ~SBCommandReturnObject().
GetOutput() [2/2]
const char * SBCommandReturnObject::GetOutput (bool only_if_no_immediate)
Definition at line 324 of file SBCommandReturnObject.cpp.
References get(), GetOutput(), LLDB_INSTRUMENT_VA, and ref().
GetOutputSize()
size_t SBCommandReturnObject::GetOutputSize ()
Definition at line 121 of file SBCommandReturnObject.cpp.
References lldb_private::CommandReturnObject::GetOutputString(), LLDB_INSTRUMENT_VA, and ref().
Referenced by GetDescription(), and LLDB_DEPRECATED_FIXME().
GetStatus()
lldb::ReturnStatus SBCommandReturnObject::GetStatus ()
Definition at line 187 of file SBCommandReturnObject.cpp.
References lldb_private::CommandReturnObject::GetStatus(), LLDB_INSTRUMENT_VA, and ref().
Referenced by lldb::SBCommandInterpreter::HandleCommand(), and LLDB_DEPRECATED_FIXME().
GetValues()
SBValueList SBCommandReturnObject::GetValues (lldb::DynamicValueType use_dynamic)
Definition at line 367 of file SBCommandReturnObject.cpp.
References lldb::SBValueList::Append(), LLDB_INSTRUMENT_VA, ref(), and lldb::SBValue::SetSP().
Referenced by __attribute__().
HasResult()
bool SBCommandReturnObject::HasResult ()
Definition at line 205 of file SBCommandReturnObject.cpp.
References lldb_private::CommandReturnObject::HasResult(), LLDB_INSTRUMENT_VA, and ref().
Referenced by LLDB_DEPRECATED_FIXME().
IsValid()
bool SBCommandReturnObject::IsValid () const
Definition at line 80 of file SBCommandReturnObject.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBCommandReturnObject().
LLDB_DEPRECATED_FIXME() [1/6]
lldb::SBCommandReturnObject::LLDB_DEPRECATED_FIXME ("Use PutError(SBFile) or PutError(FileSP)" , "PutError(SBFile)")
References AppendMessage(), AppendWarning(), Clear(), GetDescription(), GetStatus(), HasResult(), PutError(), SetStatus(), and Succeeded().
LLDB_DEPRECATED_FIXME() [2/6]
lldb::SBCommandReturnObject::LLDB_DEPRECATED_FIXME ("Use PutOutput(SBFile) or PutOutput(FileSP)" , "PutOutput(SBFile)")
References GetErrorSize(), GetOutputSize(), and PutOutput().
Referenced by LLDB_DEPRECATED_FIXME(), LLDB_DEPRECATED_FIXME(), and LLDB_DEPRECATED_FIXME().
LLDB_DEPRECATED_FIXME() [3/6]
lldb::SBCommandReturnObject::LLDB_DEPRECATED_FIXME ("Use SetImmediateErrorFile(SBFile) or SetImmediateErrorFile(FileSP)" , "SetImmediateErrorFile(SBFile)")
References LLDB_DEPRECATED_FIXME(), PutCString(), SetImmediateErrorFile(), SetImmediateOutputFile(), and transfer_ownership.
LLDB_DEPRECATED_FIXME() [4/6]
lldb::SBCommandReturnObject::LLDB_DEPRECATED_FIXME ("Use SetImmediateErrorFile(SBFile) or SetImmediateErrorFile(FileSP)" , "SetImmediateErrorFile(SBFile)")
References LLDB_DEPRECATED_FIXME(), and SetImmediateErrorFile().
LLDB_DEPRECATED_FIXME() [5/6]
lldb::SBCommandReturnObject::LLDB_DEPRECATED_FIXME ("Use SetImmediateOutputFile(SBFile) or SetImmediateOutputFile(FileSP)" , "SetImmediateOutputFile(SBFile)")
References LLDB_DEPRECATED_FIXME().
LLDB_DEPRECATED_FIXME() [6/6]
lldb::SBCommandReturnObject::LLDB_DEPRECATED_FIXME ("Use SetImmediateOutputFile(SBFile) or SetImmediateOutputFile(FileSP)" , "SetImmediateOutputFile(SBFile)")
References SetImmediateOutputFile().
operator bool()
SBCommandReturnObject::operator bool () const explicit
Definition at line 84 of file SBCommandReturnObject.cpp.
References LLDB_INSTRUMENT_VA.
operator*()
CommandReturnObject & SBCommandReturnObject::operator* () const protected
Definition at line 231 of file SBCommandReturnObject.cpp.
References m_opaque_up.
Referenced by lldb_private::python::SWIGBridge.
operator->()
CommandReturnObject * SBCommandReturnObject::operator-> () const protected
Definition at line 223 of file SBCommandReturnObject.cpp.
References m_opaque_up.
Referenced by lldb_private::python::SWIGBridge.
operator=()
SBCommandReturnObject & SBCommandReturnObject::operator= (const lldb::SBCommandReturnObject & rhs)
Definition at line 69 of file SBCommandReturnObject.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBCommandReturnObject().
Referenced by ~SBCommandReturnObject().
PutCString()
void SBCommandReturnObject::PutCString (const char * string, int len = -1)
Definition at line 312 of file SBCommandReturnObject.cpp.
References lldb_private::CommandReturnObject::AppendMessage(), LLDB_INSTRUMENT_VA, and ref().
Referenced by LLDB_DEPRECATED_FIXME().
PutError() [1/2]
size_t SBCommandReturnObject::PutError (FileSP BORROWED)
Definition at line 167 of file SBCommandReturnObject.cpp.
References GetError(), and LLDB_INSTRUMENT_VA.
PutError() [2/2]
size_t SBCommandReturnObject::PutError (SBFile file)
Definition at line 174 of file SBCommandReturnObject.cpp.
References GetError(), LLDB_INSTRUMENT_VA, and lldb::SBFile::m_opaque_sp.
Referenced by lldb::SBDebugger::HandleCommand(), and LLDB_DEPRECATED_FIXME().
PutOutput() [1/2]
size_t SBCommandReturnObject::PutOutput (FileSP BORROWED)
Definition at line 143 of file SBCommandReturnObject.cpp.
References GetOutput(), and LLDB_INSTRUMENT_VA.
PutOutput() [2/2]
size_t SBCommandReturnObject::PutOutput (SBFile file)
Definition at line 150 of file SBCommandReturnObject.cpp.
References GetOutput(), LLDB_INSTRUMENT_VA, and lldb::SBFile::m_opaque_sp.
Referenced by lldb::SBDebugger::HandleCommand(), and LLDB_DEPRECATED_FIXME().
ref()
CommandReturnObject & SBCommandReturnObject::ref () const private
Definition at line 235 of file SBCommandReturnObject.cpp.
References m_opaque_up.
Referenced by AppendMessage(), AppendWarning(), Clear(), GetCommand(), GetDescription(), GetError(), GetError(), GetErrorData(), GetErrorSize(), GetOutput(), GetOutput(), GetOutputSize(), GetStatus(), GetValues(), lldb::SBCommandInterpreter::HandleCommand(), lldb::SBCommandInterpreter::HandleCommandsFromFile(), HasResult(), lldb_private::python::SWIGBridge, PutCString(), lldb::SBCommandInterpreter::ResolveCommand(), SBCommandReturnObject(), SetError(), SetError(), SetImmediateErrorFile(), SetImmediateOutputFile(), SetStatus(), lldb::SBCommandInterpreter::SourceInitFileInCurrentWorkingDirectory(), lldb::SBCommandInterpreter::SourceInitFileInGlobalDirectory(), lldb::SBCommandInterpreter::SourceInitFileInHomeDirectory(), and Succeeded().
SetError() [1/2]
void SBCommandReturnObject::SetError (const char * error_cstr)
Definition at line 359 of file SBCommandReturnObject.cpp.
References lldb_private::CommandReturnObject::AppendError(), LLDB_INSTRUMENT_VA, and ref().
SetError() [2/2]
void SBCommandReturnObject::SetError (lldb::SBError & error, const char * fallback_error_cstr = nullptr)
Definition at line 349 of file SBCommandReturnObject.cpp.
References error(), lldb_private::Status::FromErrorString(), LLDB_INSTRUMENT_VA, ref(), and lldb_private::CommandReturnObject::SetError().
Referenced by __attribute__().
SetImmediateErrorFile() [1/2]
void SBCommandReturnObject::SetImmediateErrorFile (FileSP BORROWED)
Definition at line 307 of file SBCommandReturnObject.cpp.
References LLDB_INSTRUMENT_VA, lldb::SBFile, and SetImmediateErrorFile().
SetImmediateErrorFile() [2/2]
void SBCommandReturnObject::SetImmediateErrorFile (SBFile file)
Definition at line 297 of file SBCommandReturnObject.cpp.
References LLDB_INSTRUMENT_VA, lldb::SBFile::m_opaque_sp, ref(), and lldb_private::CommandReturnObject::SetImmediateErrorFile().
Referenced by LLDB_DEPRECATED_FIXME(), LLDB_DEPRECATED_FIXME(), and SetImmediateErrorFile().
SetImmediateOutputFile() [1/2]
void SBCommandReturnObject::SetImmediateOutputFile (FileSP BORROWED)
Definition at line 302 of file SBCommandReturnObject.cpp.
References LLDB_INSTRUMENT_VA, lldb::SBFile, and SetImmediateOutputFile().
SetImmediateOutputFile() [2/2]
void SBCommandReturnObject::SetImmediateOutputFile (SBFile file)
Definition at line 292 of file SBCommandReturnObject.cpp.
References LLDB_INSTRUMENT_VA, lldb::SBFile::m_opaque_sp, ref(), and lldb_private::CommandReturnObject::SetImmediateOutputFile().
Referenced by LLDB_DEPRECATED_FIXME(), LLDB_DEPRECATED_FIXME(), and SetImmediateOutputFile().
SetStatus()
void SBCommandReturnObject::SetStatus (lldb::ReturnStatus status)
Definition at line 193 of file SBCommandReturnObject.cpp.
References LLDB_INSTRUMENT_VA, ref(), and lldb_private::CommandReturnObject::SetStatus().
Referenced by LLDB_DEPRECATED_FIXME().
Succeeded()
bool SBCommandReturnObject::Succeeded ()
Definition at line 199 of file SBCommandReturnObject.cpp.
References LLDB_INSTRUMENT_VA, ref(), and lldb_private::CommandReturnObject::Succeeded().
Referenced by GetDescription(), and LLDB_DEPRECATED_FIXME().
Friends And Related Symbol Documentation
lldb_private::CommandPluginInterfaceImplementation
friend class lldb_private::CommandPluginInterfaceImplementation friend
Definition at line 145 of file SBCommandReturnObject.h.
lldb_private::python::SWIGBridge
friend class lldb_private::python::SWIGBridge friend
Definition at line 146 of file SBCommandReturnObject.h.
References get(), operator*(), operator->(), ref(), and SBCommandReturnObject().
SBCommandInterpreter
friend class SBCommandInterpreter friend
Definition at line 142 of file SBCommandReturnObject.h.
References SBCommandInterpreter.
Referenced by SBCommandInterpreter.
SBOptions
friend class SBOptions friend
Definition at line 143 of file SBCommandReturnObject.h.
References SBOptions.
Referenced by SBOptions.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::SBCommandReturnObjectImpl> lldb::SBCommandReturnObject::m_opaque_up private
Definition at line 159 of file SBCommandReturnObject.h.
Referenced by get(), operator*(), operator->(), operator=(), ref(), SBCommandReturnObject(), SBCommandReturnObject(), and SBCommandReturnObject().
transfer_ownership
bool lldb::SBCommandReturnObject::transfer_ownership
Definition at line 108 of file SBCommandReturnObject.h.
Referenced by LLDB_DEPRECATED_FIXME().
The documentation for this class was generated from the following files:
SBCommandReturnObject.h
SBCommandReturnObject.cpp