LLDB: lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd Class Reference
lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd Class Reference
Public Member Functions
LibcxxStdUnorderedMapSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
~LibcxxStdUnorderedMapSyntheticFrontEnd () override=default
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Member Functions
CompilerType GetNodeType ()
CompilerType GetElementType (CompilerType table_type)
llvm::Expected< size_t > CalculateNumChildrenImpl (ValueObject &table)
Private Attributes
CompilerType m_element_type
CompilerType m_node_type
ValueObject * m_tree = nullptr
size_t m_num_elements = 0
ValueObject * m_next_element = nullptr
std::vector< ValueObject * > m_elements_cache
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
Definition at line 30 of file LibCxxUnorderedMap.cpp.
Constructor & Destructor Documentation
LibcxxStdUnorderedMapSyntheticFrontEnd()
lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::LibcxxStdUnorderedMapSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
Definition at line 82 of file LibCxxUnorderedMap.cpp.
References m_element_type, m_elements_cache, lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd(), and Update().
~LibcxxStdUnorderedMapSyntheticFrontEnd()
lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::~LibcxxStdUnorderedMapSyntheticFrontEnd () override default
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::CalculateNumChildren () override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 90 of file LibCxxUnorderedMap.cpp.
References m_num_elements.
CalculateNumChildrenImpl()
llvm::Expected< size_t > lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::CalculateNumChildrenImpl (ValueObject & table) private
Definition at line 219 of file LibCxxUnorderedMap.cpp.
References lldb_private::formatters::GetFirstValueOfLibCXXCompressedPair(), and lldb_private::formatters::GetValueOrOldCompressedPair().
Referenced by Update().
GetChildAtIndex()
lldb::ValueObjectSP lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::GetChildAtIndex (uint32_t idx) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 149 of file LibCxxUnorderedMap.cpp.
References lldb_private::SyntheticChildrenFrontEnd::CalculateNumChildrenIgnoringErrors(), lldb_private::SyntheticChildrenFrontEnd::CreateValueObjectFromData(), error(), lldb_private::ValueObject::GetData(), lldb_private::ValueObject::GetExecutionContextRef(), lldb_private::StreamString::GetString(), lldb_private::ExecutionContextRef::Lock(), m_element_type, m_elements_cache, m_next_element, m_node_type, m_tree, and lldb_private::Stream::Printf().
GetElementType()
CompilerType lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::GetElementType (CompilerType table_type) private
Definition at line 100 of file LibCxxUnorderedMap.cpp.
References lldb_private::CompilerType::GetCanonicalType(), lldb_private::CompilerType::GetDirectNestedTypeWithName(), lldb_private::CompilerType::GetFieldAtIndex(), lldb_private::CompilerType::GetPointeeType(), lldb_private::CompilerType::GetTypedefedType(), lldb_private::CompilerType::GetTypeName(), lldb_private::CompilerType::IsPointerOrReferenceType(), lldb_private::formatters::isStdTemplate(), isUnorderedMap(), and lldb_private::SyntheticChildrenFrontEnd::m_backend.
Referenced by Update().
GetIndexOfChildWithName()
llvm::Expected< size_t > lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::GetIndexOfChildWithName (ConstString name) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 289 of file LibCxxUnorderedMap.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::formatters::ExtractIndexFromString(), and lldb_private::ConstString::GetCString().
GetNodeType()
CompilerType lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::GetNodeType () private
Definition at line 132 of file LibCxxUnorderedMap.cpp.
References lldb_private::formatters::GetFirstValueOfLibCXXCompressedPair(), lldb_private::formatters::GetValueOrOldCompressedPair(), and lldb_private::SyntheticChildrenFrontEnd::m_backend.
Referenced by Update().
Update()
lldb::ChildCacheState lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::Update () override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 252 of file LibCxxUnorderedMap.cpp.
References CalculateNumChildrenImpl(), lldb_private::DataFormatters, lldb::eRefetch, GetElementType(), lldb_private::GetLog(), GetNodeType(), GetTreePointer(), LLDB_LOG_ERRORV, lldb_private::SyntheticChildrenFrontEnd::m_backend, m_element_type, m_elements_cache, m_next_element, m_node_type, m_num_elements, and m_tree.
Referenced by LibcxxStdUnorderedMapSyntheticFrontEnd().
Member Data Documentation
m_element_type
CompilerType lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::m_element_type private
Definition at line 50 of file LibCxxUnorderedMap.cpp.
Referenced by GetChildAtIndex(), LibcxxStdUnorderedMapSyntheticFrontEnd(), and Update().
m_elements_cache
std::vector<ValueObject *> lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::m_elements_cache private
Definition at line 55 of file LibCxxUnorderedMap.cpp.
Referenced by GetChildAtIndex(), LibcxxStdUnorderedMapSyntheticFrontEnd(), and Update().
m_next_element
ValueObject* lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::m_next_element = nullptr private
Definition at line 54 of file LibCxxUnorderedMap.cpp.
Referenced by GetChildAtIndex(), and Update().
m_node_type
CompilerType lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::m_node_type private
Definition at line 51 of file LibCxxUnorderedMap.cpp.
Referenced by GetChildAtIndex(), and Update().
m_num_elements
size_t lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::m_num_elements = 0 private
Definition at line 53 of file LibCxxUnorderedMap.cpp.
Referenced by CalculateNumChildren(), and Update().
m_tree
ValueObject* lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::m_tree = nullptr private
Definition at line 52 of file LibCxxUnorderedMap.cpp.
Referenced by GetChildAtIndex(), and Update().
The documentation for this class was generated from the following file:
LibCxxUnorderedMap.cpp