LLDB: lldb_private::ProcessAttachInfo Class Reference
lldb_private::ProcessAttachInfo Class Reference
#include <Process.h>
Public Member Functions
ProcessAttachInfo ()=default
ProcessAttachInfo (const ProcessLaunchInfo &launch_info)
bool GetWaitForLaunch () const
void SetWaitForLaunch (bool b)
bool GetAsync () const
void SetAsync (bool b)
bool GetIgnoreExisting () const
void SetIgnoreExisting (bool b)
bool GetContinueOnceAttached () const
void SetContinueOnceAttached (bool b)
uint32_t GetResumeCount () const
void SetResumeCount (uint32_t c)
llvm::StringRef GetProcessPluginName () const
void SetProcessPluginName (llvm::StringRef plugin)
void Clear ()
bool ProcessInfoSpecified () const
bool GetDetachOnError () const
void SetDetachOnError (bool enable)
lldb::ListenerSP GetListenerForProcess (Debugger &debugger)
Public Member Functions inherited from lldb_private::ProcessInstanceInfo
ProcessInstanceInfo ()=default
ProcessInstanceInfo (const char *name, const ArchSpec &arch, lldb::pid_t pid)
void Clear ()
uint32_t GetEffectiveUserID () const
uint32_t GetEffectiveGroupID () const
bool EffectiveUserIDIsValid () const
bool EffectiveGroupIDIsValid () const
void SetEffectiveUserID (uint32_t uid)
void SetEffectiveGroupID (uint32_t gid)
lldb::pid_t GetParentProcessID () const
void SetParentProcessID (lldb::pid_t pid)
bool ParentProcessIDIsValid () const
lldb::pid_t GetProcessGroupID () const
void SetProcessGroupID (lldb::pid_t pgrp)
bool ProcessGroupIDIsValid () const
lldb::pid_t GetProcessSessionID () const
void SetProcessSessionID (lldb::pid_t session)
bool ProcessSessionIDIsValid () const
struct timespec GetUserTime () const
void SetUserTime (struct timespec utime)
bool UserTimeIsValid () const
struct timespec GetSystemTime () const
void SetSystemTime (struct timespec stime)
bool SystemTimeIsValid () const
struct timespec GetCumulativeUserTime () const
void SetCumulativeUserTime (struct timespec cutime)
bool CumulativeUserTimeIsValid () const
struct timespec GetCumulativeSystemTime () const
void SetCumulativeSystemTime (struct timespec cstime)
bool CumulativeSystemTimeIsValid () const
std::optional< int8_t > GetPriorityValue () const
void SetPriorityValue (int8_t priority_value)
void SetIsZombie (bool is_zombie)
std::optional< bool > IsZombie () const
void SetIsCoreDumping (bool is_coredumping)
std::optional< bool > IsCoreDumping () const
void Dump (Stream &s, UserIDResolver &resolver) const
void DumpAsTableRow (Stream &s, UserIDResolver &resolver, bool show_args, bool verbose) const
Public Member Functions inherited from lldb_private::ProcessInfo
ProcessInfo ()
ProcessInfo (const char *name, const ArchSpec &arch, lldb::pid_t pid)
void Clear ()
const char * GetName () const
llvm::StringRef GetNameAsStringRef () const
FileSpec & GetExecutableFile ()
void SetExecutableFile (const FileSpec &exe_file, bool add_exe_file_as_first_arg)
const FileSpec & GetExecutableFile () const
uint32_t GetUserID () const
uint32_t GetGroupID () const
bool UserIDIsValid () const
bool GroupIDIsValid () const
void SetUserID (uint32_t uid)
void SetGroupID (uint32_t gid)
ArchSpec & GetArchitecture ()
const ArchSpec & GetArchitecture () const
void SetArchitecture (const ArchSpec &arch)
lldb::pid_t GetProcessID () const
void SetProcessID (lldb::pid_t pid)
bool ProcessIDIsValid () const
void Dump (Stream &s, Platform *platform) const
Args & GetArguments ()
const Args & GetArguments () const
llvm::StringRef GetArg0 () const
void SetArg0 (llvm::StringRef arg)
void SetArguments (const Args &args, bool first_arg_is_executable)
void SetArguments (char const **argv, bool first_arg_is_executable)
Environment & GetEnvironment ()
const Environment & GetEnvironment () const
bool IsScriptedProcess () const
lldb::ScriptedMetadataSP GetScriptedMetadata () const
void SetScriptedMetadata (lldb::ScriptedMetadataSP metadata_sp)
lldb::ListenerSP GetListener () const
void SetListener (const lldb::ListenerSP &listener_sp)
lldb::ListenerSP GetHijackListener () const
void SetHijackListener (const lldb::ListenerSP &listener_sp)
lldb::ListenerSP GetShadowListener () const
void SetShadowListener (const lldb::ListenerSP &listener_sp)
Protected Attributes
std::string m_plugin_name
uint32_t m_resume_count = 0
bool m_wait_for_launch = false
bool m_ignore_existing = true
bool m_continue_once_attached = false
bool m_detach_on_error
bool m_async
Protected Attributes inherited from lldb_private::ProcessInstanceInfo
uint32_t m_euid = UINT32_MAX
uint32_t m_egid = UINT32_MAX
lldb::pid_t m_parent_pid = LLDB_INVALID_PROCESS_ID
lldb::pid_t m_process_group_id = LLDB_INVALID_PROCESS_ID
lldb::pid_t m_process_session_id = LLDB_INVALID_PROCESS_ID
struct timespec m_user_time
struct timespec m_system_time
struct timespec m_cumulative_user_time
struct timespec m_cumulative_system_time
std::optional< int8_t > m_priority_value = std::nullopt
std::optional< bool > m_zombie = std::nullopt
std::optional< bool > m_coredumping = std::nullopt
Protected Attributes inherited from lldb_private::ProcessInfo
FileSpec m_executable
std::string m_arg0
Args m_arguments
Environment m_environment
uint32_t m_uid = UINT32_MAX
uint32_t m_gid = UINT32_MAX
ArchSpec m_arch
lldb::pid_t m_pid = LLDB_INVALID_PROCESS_ID
lldb::ScriptedMetadataSP m_scripted_metadata_sp = nullptr
lldb::ListenerSP m_listener_sp = nullptr
lldb::ListenerSP m_hijack_listener_sp = nullptr
lldb::ListenerSP m_shadow_listener_sp = nullptr
Additional Inherited Members
Static Public Member Functions inherited from lldb_private::ProcessInstanceInfo
static void DumpTableHeader (Stream &s, bool show_args, bool verbose)
Detailed Description
Definition at line 126 of file Process.h.
Constructor & Destructor Documentation
ProcessAttachInfo() [1/2]
lldb_private::ProcessAttachInfo::ProcessAttachInfo () default
ProcessAttachInfo() [2/2]
lldb_private::ProcessAttachInfo::ProcessAttachInfo (const ProcessLaunchInfo & launch_info) inline
Definition at line 130 of file Process.h.
References lldb_private::ProcessLaunchInfo::GetDetachOnError(), lldb_private::ProcessLaunchInfo::GetProcessPluginName(), lldb_private::ProcessLaunchInfo::GetResumeCount(), m_detach_on_error, SetProcessPluginName(), and SetResumeCount().
Member Function Documentation
Clear()
void lldb_private::ProcessAttachInfo::Clear () inline
Definition at line 165 of file Process.h.
References lldb_private::ProcessInstanceInfo::Clear(), m_continue_once_attached, m_ignore_existing, m_plugin_name, m_resume_count, and m_wait_for_launch.
GetAsync()
bool lldb_private::ProcessAttachInfo::GetAsync () const inline
Definition at line 141 of file Process.h.
References m_async.
Referenced by lldb_private::Target::Attach().
GetContinueOnceAttached()
bool lldb_private::ProcessAttachInfo::GetContinueOnceAttached () const inline
Definition at line 149 of file Process.h.
References m_continue_once_attached.
Referenced by lldb_private::ProcessDebugger::AttachProcess().
GetDetachOnError()
bool lldb_private::ProcessAttachInfo::GetDetachOnError () const inline
Definition at line 184 of file Process.h.
References m_detach_on_error.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::DoAttachToProcessWithID(), and lldb_private::process_gdb_remote::ProcessGDBRemote::DoAttachToProcessWithName().
GetIgnoreExisting()
bool lldb_private::ProcessAttachInfo::GetIgnoreExisting () const inline
Definition at line 145 of file Process.h.
References m_ignore_existing.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::DoAttachToProcessWithName().
GetListenerForProcess()
ListenerSP ProcessAttachInfo::GetListenerForProcess (Debugger & debugger)
Definition at line 3052 of file Process.cpp.
References lldb_private::Debugger::GetListener(), and lldb_private::ProcessInfo::m_listener_sp.
Referenced by lldb_private::platform_gdb_server::PlatformRemoteGDBServer::Attach(), lldb_private::PlatformWindows::Attach(), lldb_private::Target::Attach(), and PlatformPOSIX::Attach().
GetProcessPluginName()
llvm::StringRef lldb_private::ProcessAttachInfo::GetProcessPluginName () const inline
Definition at line 157 of file Process.h.
References m_plugin_name.
Referenced by lldb_private::platform_gdb_server::PlatformRemoteGDBServer::Attach(), lldb_private::PlatformWindows::Attach(), and lldb_private::Target::Attach().
GetResumeCount()
uint32_t lldb_private::ProcessAttachInfo::GetResumeCount () const inline
Definition at line 153 of file Process.h.
References m_resume_count.
Referenced by lldb_private::Process::Attach().
GetWaitForLaunch()
bool lldb_private::ProcessAttachInfo::GetWaitForLaunch () const inline
Definition at line 137 of file Process.h.
References m_wait_for_launch.
Referenced by lldb_private::Process::Attach(), and lldb_private::process_gdb_remote::ProcessGDBRemote::DoAttachToProcessWithName().
ProcessInfoSpecified()
bool lldb_private::ProcessAttachInfo::ProcessInfoSpecified () const inline
Definition at line 174 of file Process.h.
References lldb_private::ProcessInfo::GetExecutableFile(), lldb_private::ProcessInstanceInfo::GetParentProcessID(), lldb_private::ProcessInfo::GetProcessID(), and LLDB_INVALID_PROCESS_ID.
Referenced by lldb_private::Target::Attach().
SetAsync()
void lldb_private::ProcessAttachInfo::SetAsync (bool b) inline
Definition at line 143 of file Process.h.
References m_async.
SetContinueOnceAttached()
void lldb_private::ProcessAttachInfo::SetContinueOnceAttached (bool b) inline
Definition at line 151 of file Process.h.
References m_continue_once_attached.
SetDetachOnError()
void lldb_private::ProcessAttachInfo::SetDetachOnError (bool enable) inline
Definition at line 186 of file Process.h.
References m_detach_on_error.
SetIgnoreExisting()
void lldb_private::ProcessAttachInfo::SetIgnoreExisting (bool b) inline
Definition at line 147 of file Process.h.
References m_ignore_existing.
SetProcessPluginName()
void lldb_private::ProcessAttachInfo::SetProcessPluginName (llvm::StringRef plugin) inline
Definition at line 161 of file Process.h.
References m_plugin_name.
Referenced by ProcessAttachInfo().
SetResumeCount()
void lldb_private::ProcessAttachInfo::SetResumeCount (uint32_t c) inline
Definition at line 155 of file Process.h.
References m_resume_count.
Referenced by ProcessAttachInfo().
SetWaitForLaunch()
void lldb_private::ProcessAttachInfo::SetWaitForLaunch (bool b) inline
Definition at line 139 of file Process.h.
References m_wait_for_launch.
Referenced by lldb::SBTarget::AttachToProcessWithName().
Member Data Documentation
m_async
bool lldb_private::ProcessAttachInfo::m_async protected
Initial value:
=
      false
Definition at line 201 of file Process.h.
Referenced by GetAsync(), and SetAsync().
m_continue_once_attached
bool lldb_private::ProcessAttachInfo::m_continue_once_attached = false protected
Definition at line 195 of file Process.h.
Referenced by Clear(), GetContinueOnceAttached(), and SetContinueOnceAttached().
m_detach_on_error
bool lldb_private::ProcessAttachInfo::m_detach_on_error protected
Initial value:
=
      true
Definition at line 198 of file Process.h.
Referenced by GetDetachOnError(), ProcessAttachInfo(), and SetDetachOnError().
m_ignore_existing
bool lldb_private::ProcessAttachInfo::m_ignore_existing = true protected
Definition at line 194 of file Process.h.
Referenced by Clear(), GetIgnoreExisting(), and SetIgnoreExisting().
m_plugin_name
std::string lldb_private::ProcessAttachInfo::m_plugin_name protected
Definition at line 191 of file Process.h.
Referenced by Clear(), GetProcessPluginName(), and SetProcessPluginName().
m_resume_count
uint32_t lldb_private::ProcessAttachInfo::m_resume_count = 0 protected
Definition at line 192 of file Process.h.
Referenced by Clear(), GetResumeCount(), and SetResumeCount().
m_wait_for_launch
bool lldb_private::ProcessAttachInfo::m_wait_for_launch = false protected
Definition at line 193 of file Process.h.
Referenced by Clear(), GetWaitForLaunch(), and SetWaitForLaunch().
The documentation for this class was generated from the following files:
Process.h
Process.cpp