LLDB: lldb_private::ModuleSpecList Class Reference
lldb_private::ModuleSpecList Class Reference
#include <ModuleSpec.h>
Public Types
typedef std::vector< ModuleSpec > collection
typedef LockingAdaptedIterable< std::recursive_mutex, collection > ModuleSpecIterable
Public Member Functions
ModuleSpecList ()=default
ModuleSpecList (const ModuleSpecList &rhs)
~ModuleSpecList ()=default
ModuleSpecList & operator= (const ModuleSpecList &rhs)
size_t GetSize () const
void Clear ()
void Append (const ModuleSpec &spec)
void Append (const ModuleSpecList &rhs)
ModuleSpec & GetModuleSpecRefAtIndex (size_t i)
bool GetModuleSpecAtIndex (size_t i, ModuleSpec &module_spec) const
bool FindMatchingModuleSpec (const ModuleSpec &module_spec, ModuleSpec &match_module_spec) const
void FindMatchingModuleSpecs (const ModuleSpec &module_spec, ModuleSpecList &matching_list) const
void Dump (Stream &strm)
ModuleSpecIterable ModuleSpecs ()
Protected Attributes
collection m_specs
The collection of modules.
std::recursive_mutex m_mutex
Detailed Description
Definition at line 308 of file ModuleSpec.h.
Member Typedef Documentation
collection
typedef std::vector<ModuleSpec> lldb_private::ModuleSpecList::collection
Definition at line 424 of file ModuleSpec.h.
ModuleSpecIterable
typedef LockingAdaptedIterable<std::recursive_mutex, collection> lldb_private::ModuleSpecList::ModuleSpecIterable
Definition at line 426 of file ModuleSpec.h.
Constructor & Destructor Documentation
ModuleSpecList() [1/2]
lldb_private::ModuleSpecList::ModuleSpecList () default
Referenced by Append(), FindMatchingModuleSpecs(), ModuleSpecList(), and operator=().
ModuleSpecList() [2/2]
lldb_private::ModuleSpecList::ModuleSpecList (const ModuleSpecList & rhs) inline
Definition at line 312 of file ModuleSpec.h.
References m_mutex, m_specs, and ModuleSpecList().
~ModuleSpecList()
lldb_private::ModuleSpecList::~ModuleSpecList () default
Member Function Documentation
Append() [1/2]
void lldb_private::ModuleSpecList::Append (const ModuleSpec & spec) inline
Definition at line 341 of file ModuleSpec.h.
References m_mutex, and m_specs.
Referenced by FindMatchingModuleSpecs(), ObjectFileMachO::GetAllArchSpecs(), lldb_private::breakpad::ObjectFileBreakpad::GetModuleSpecifications(), lldb_private::ObjectFileJSON::GetModuleSpecifications(), lldb_private::ObjectFilePDB::GetModuleSpecifications(), lldb_private::wasm::ObjectFileWasm::GetModuleSpecifications(), ObjectFileCOFF::GetModuleSpecifications(), ObjectFileELF::GetModuleSpecifications(), ObjectFilePECOFF::GetModuleSpecifications(), and ObjectFileXCOFF::GetModuleSpecifications().
Append() [2/2]
void lldb_private::ModuleSpecList::Append (const ModuleSpecList & rhs) inline
Definition at line 346 of file ModuleSpec.h.
References m_mutex, m_specs, and ModuleSpecList().
Clear()
void lldb_private::ModuleSpecList::Clear () inline
Definition at line 336 of file ModuleSpec.h.
References m_mutex, and m_specs.
Referenced by ObjectFileMinidump::GetModuleSpecifications().
Dump()
void lldb_private::ModuleSpecList::Dump (Stream & strm) inline
Definition at line 413 of file ModuleSpec.h.
References lldb_private::Stream::EOL(), m_mutex, m_specs, and lldb_private::Stream::Printf().
FindMatchingModuleSpec()
bool lldb_private::ModuleSpecList::FindMatchingModuleSpec (const ModuleSpec & module_spec, ModuleSpec & match_module_spec) const inline
Definition at line 366 of file ModuleSpec.h.
References lldb_private::ModuleSpec::Clear(), lldb_private::ModuleSpec::GetArchitecturePtr(), m_mutex, and m_specs.
Referenced by CommandObjectTargetSymbolsAdd::AddModuleSymbols(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::GetModuleInfo(), lldb_private::Platform::GetModuleSpec(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableObjectFile(), lldb_private::SymbolLocatorDefault::LocateExecutableObjectFile(), LocateMacOSXFilesUsingDebugSymbols(), and lldb_private::Module::Module().
FindMatchingModuleSpecs()
void lldb_private::ModuleSpecList::FindMatchingModuleSpecs (const ModuleSpec & module_spec, ModuleSpecList & matching_list) const inline
Definition at line 391 of file ModuleSpec.h.
References Append(), lldb_private::ModuleSpec::GetArchitecturePtr(), GetSize(), m_mutex, m_specs, and ModuleSpecList().
GetModuleSpecAtIndex()
bool lldb_private::ModuleSpecList::GetModuleSpecAtIndex (size_t i, ModuleSpec & module_spec) const inline
Definition at line 356 of file ModuleSpec.h.
References lldb_private::ModuleSpec::Clear(), m_mutex, and m_specs.
Referenced by CommandObjectTargetSymbolsAdd::AddModuleSymbols(), FileAtPathContainsArchAndUUID(), lldb_private::SymbolLocatorDebugSymbols::FindSymbolFileInBundle(), ObjectContainerBSDArchive::GetModuleSpecifications(), and lldb_private::SymbolLocatorDefault::LocateExecutableSymbolFile().
GetModuleSpecRefAtIndex()
ModuleSpec & lldb_private::ModuleSpecList::GetModuleSpecRefAtIndex (size_t i) inline
Definition at line 354 of file ModuleSpec.h.
References m_specs.
Referenced by ObjectFileMachO::Dump(), ObjectFileMachO::GetArchitecture(), lldb_private::ObjectContainerMachOFileset::GetModuleSpecifications(), ObjectContainerBSDArchive::GetModuleSpecifications(), and ObjectFileMachO::ParseHeader().
GetSize()
size_t lldb_private::ModuleSpecList::GetSize () const inline
Definition at line 331 of file ModuleSpec.h.
References m_mutex, and m_specs.
Referenced by CommandObjectTargetSymbolsAdd::AddModuleSymbols(), ObjectFileMachO::Dump(), FileAtPathContainsArchAndUUID(), FindMatchingModuleSpecs(), lldb_private::SymbolLocatorDebugSymbols::FindSymbolFileInBundle(), ObjectFileMachO::GetArchitecture(), lldb_private::ObjectContainerMachOFileset::GetModuleSpecifications(), lldb_private::ObjectFile::GetModuleSpecifications(), lldb_private::ObjectFilePDB::GetModuleSpecifications(), ObjectContainerBSDArchive::GetModuleSpecifications(), ObjectContainerUniversalMachO::GetModuleSpecifications(), ObjectFileELF::GetModuleSpecifications(), ObjectFileMachO::GetModuleSpecifications(), ObjectFilePECOFF::GetModuleSpecifications(), ObjectFileXCOFF::GetModuleSpecifications(), and ObjectFileMachO::ParseHeader().
ModuleSpecs()
ModuleSpecIterable lldb_private::ModuleSpecList::ModuleSpecs () inline
Definition at line 428 of file ModuleSpec.h.
References m_mutex, and m_specs.
operator=()
ModuleSpecList & lldb_private::ModuleSpecList::operator= (const ModuleSpecList & rhs) inline
Definition at line 320 of file ModuleSpec.h.
References m_mutex, m_specs, and ModuleSpecList().
Member Data Documentation
m_mutex
std::recursive_mutex lldb_private::ModuleSpecList::m_mutex mutable protected
Definition at line 434 of file ModuleSpec.h.
Referenced by Append(), Append(), Clear(), Dump(), FindMatchingModuleSpec(), FindMatchingModuleSpecs(), GetModuleSpecAtIndex(), GetSize(), ModuleSpecList(), ModuleSpecs(), and operator=().
m_specs
collection lldb_private::ModuleSpecList::m_specs protected
The collection of modules.
Definition at line 433 of file ModuleSpec.h.
Referenced by Append(), Append(), Clear(), Dump(), FindMatchingModuleSpec(), FindMatchingModuleSpecs(), GetModuleSpecAtIndex(), GetModuleSpecRefAtIndex(), GetSize(), ModuleSpecList(), ModuleSpecs(), and operator=().
The documentation for this class was generated from the following file:
ModuleSpec.h