LLDB: lldb_private::npdb::PdbSymUid Class Reference
lldb_private::npdb::PdbSymUid Class Reference
#include <PdbSymUid.h>
Public Member Functions
PdbSymUid ()=default
PdbSymUid (uint64_t repr)
PdbSymUid (const PdbCompilandId &cid)
PdbSymUid (const PdbCompilandSymId &csid)
PdbSymUid (const PdbGlobalSymId &gsid)
PdbSymUid (const PdbTypeSymId &tsid)
PdbSymUid (const PdbFieldListMemberId &flmid)
uint64_t toOpaqueId () const
PdbSymUidKind kind () const
PdbCompilandId asCompiland () const
PdbCompilandSymId asCompilandSym () const
PdbGlobalSymId asGlobalSym () const
PdbTypeSymId asTypeSym () const
PdbFieldListMemberId asFieldListMember () const
Private Attributes
uint64_t m_repr = 0
Detailed Description
Definition at line 91 of file PdbSymUid.h.
Constructor & Destructor Documentation
PdbSymUid() [1/7]
lldb_private::npdb::PdbSymUid::PdbSymUid () default
PdbSymUid() [2/7]
lldb_private::npdb::PdbSymUid::PdbSymUid (uint64_t repr) inline
Definition at line 96 of file PdbSymUid.h.
References m_repr.
PdbSymUid() [3/7]
PdbSymUid::PdbSymUid (const PdbCompilandId & cid)
Definition at line 68 of file PdbSymUid.cpp.
References lldb_private::npdb::Compiland, m_repr, lldb_private::npdb::PdbCompilandId::modi, and repr_cast().
PdbSymUid() [4/7]
PdbSymUid::PdbSymUid (const PdbCompilandSymId & csid)
Definition at line 76 of file PdbSymUid.cpp.
References lldb_private::npdb::CompilandSym, m_repr, lldb_private::npdb::PdbCompilandSymId::modi, lldb_private::npdb::PdbCompilandSymId::offset, and repr_cast().
PdbSymUid() [5/7]
PdbSymUid::PdbSymUid (const PdbGlobalSymId & gsid)
Definition at line 85 of file PdbSymUid.cpp.
References lldb_private::npdb::GlobalSym, lldb_private::npdb::PdbGlobalSymId::is_public, m_repr, lldb_private::npdb::PdbGlobalSymId::offset, and repr_cast().
PdbSymUid() [6/7]
PdbSymUid::PdbSymUid (const PdbTypeSymId & tsid)
Definition at line 94 of file PdbSymUid.cpp.
References lldb_private::npdb::PdbTypeSymId::index, lldb_private::npdb::PdbTypeSymId::is_ipi, m_repr, repr_cast(), and lldb_private::npdb::Type.
PdbSymUid() [7/7]
PdbSymUid::PdbSymUid (const PdbFieldListMemberId & flmid)
Definition at line 103 of file PdbSymUid.cpp.
References lldb_private::npdb::FieldListMember, lldb_private::npdb::PdbFieldListMemberId::index, m_repr, lldb_private::npdb::PdbFieldListMemberId::offset, and repr_cast().
Member Function Documentation
asCompiland()
PdbCompilandId PdbSymUid::asCompiland () const
Definition at line 117 of file PdbSymUid.cpp.
References lldb_private::npdb::Compiland, kind(), m_repr, lldb_private::npdb::PdbCompilandId::modi, and repr_cast().
Referenced by lldb_private::npdb::SymbolFileNativePDB::ParseFunctions(), lldb_private::npdb::SymbolFileNativePDB::ParseLanguage(), lldb_private::npdb::SymbolFileNativePDB::ParseLineTable(), and lldb_private::npdb::SymbolFileNativePDB::ParseSupportFiles().
asCompilandSym()
PdbCompilandSymId PdbSymUid::asCompilandSym () const
Definition at line 125 of file PdbSymUid.cpp.
References lldb_private::npdb::CompilandSym, kind(), m_repr, lldb_private::npdb::PdbCompilandSymId::modi, lldb_private::npdb::PdbCompilandSymId::offset, and repr_cast().
Referenced by lldb_private::npdb::PdbAstBuilderClang::GetOrCreateClangDeclContextForUid(), lldb_private::npdb::PdbAstBuilderClang::GetOrCreateDeclForUid(), lldb_private::npdb::PdbAstBuilderClang::GetOrCreateSymbolForId(), lldb_private::npdb::PdbAstBuilderClang::GetParentClangDeclContext(), lldb_private::npdb::GetVariableLocationInfo(), lldb_private::npdb::SymbolFileNativePDB::ParseBlocksRecursive(), lldb_private::npdb::PdbAstBuilderClang::ParseDeclsForSimpleContext(), and lldb_private::npdb::SymbolFileNativePDB::ParseVariablesForContext().
asFieldListMember()
PdbFieldListMemberId PdbSymUid::asFieldListMember () const
Definition at line 153 of file PdbSymUid.cpp.
References lldb_private::npdb::FieldListMember, lldb_private::npdb::PdbFieldListMemberId::index, kind(), m_repr, lldb_private::npdb::PdbFieldListMemberId::offset, and repr_cast().
asGlobalSym()
PdbGlobalSymId PdbSymUid::asGlobalSym () const
Definition at line 134 of file PdbSymUid.cpp.
References lldb_private::npdb::GlobalSym, lldb_private::npdb::PdbGlobalSymId::is_public, kind(), m_repr, lldb_private::npdb::PdbGlobalSymId::offset, lldb_private::npdb::PublicSym, and repr_cast().
Referenced by lldb_private::npdb::PdbAstBuilderClang::GetParentClangDeclContext().
asTypeSym()
PdbTypeSymId PdbSymUid::asTypeSym () const
Definition at line 144 of file PdbSymUid.cpp.
References lldb_private::npdb::PdbTypeSymId::index, lldb_private::npdb::PdbTypeSymId::is_ipi, kind(), m_repr, repr_cast(), and lldb_private::npdb::Type.
Referenced by lldb_private::npdb::PdbAstBuilderClang::CompleteTagDecl(), lldb_private::npdb::PdbAstBuilderClang::GetOrCreateDeclForUid(), lldb_private::npdb::PdbAstBuilderClang::GetParentClangDeclContext(), and lldb_private::npdb::SymbolFileNativePDB::ResolveTypeUID().
kind()
PdbSymUidKind PdbSymUid::kind () const
Definition at line 112 of file PdbSymUid.cpp.
References m_repr, and repr_cast().
Referenced by asCompiland(), asCompilandSym(), asFieldListMember(), asGlobalSym(), asTypeSym(), lldb_private::npdb::PdbAstBuilderClang::GetOrCreateClangDeclContextForUid(), lldb_private::npdb::PdbAstBuilderClang::GetOrCreateDeclForUid(), lldb_private::npdb::PdbAstBuilderClang::GetParentClangDeclContext(), lldb_private::npdb::SymbolFileNativePDB::ParseFunctions(), lldb_private::npdb::SymbolFileNativePDB::ParseLanguage(), lldb_private::npdb::SymbolFileNativePDB::ParseLineTable(), lldb_private::npdb::SymbolFileNativePDB::ParseSupportFiles(), lldb_private::npdb::SymbolFileNativePDB::ParseVariablesForCompileUnit(), and lldb_private::npdb::SymbolFileNativePDB::ResolveTypeUID().
toOpaqueId()
uint64_t lldb_private::npdb::PdbSymUid::toOpaqueId () const inline
Definition at line 103 of file PdbSymUid.h.
References m_repr.
Referenced by lldb_private::npdb::toOpaqueUid().
Member Data Documentation
m_repr
uint64_t lldb_private::npdb::PdbSymUid::m_repr = 0 private
Definition at line 92 of file PdbSymUid.h.
Referenced by asCompiland(), asCompilandSym(), asFieldListMember(), asGlobalSym(), asTypeSym(), kind(), PdbSymUid(), PdbSymUid(), PdbSymUid(), PdbSymUid(), PdbSymUid(), PdbSymUid(), and toOpaqueId().
The documentation for this class was generated from the following files:
PdbSymUid.h
PdbSymUid.cpp