LLDB: lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions Class Reference
lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions Class Reference
#include <StringPrinter.h>
Public Member Functions
ReadBufferAndDumpToStreamOptions ()=default
ReadBufferAndDumpToStreamOptions (ValueObject &valobj)
ReadBufferAndDumpToStreamOptions (const ReadStringAndDumpToStreamOptions &options)
void SetData (DataExtractor &&d)
const lldb_private::DataExtractor & GetData () const
void SetIsTruncated (bool t)
bool GetIsTruncated () const
Public Member Functions inherited from lldb_private::formatters::StringPrinter::DumpToStreamOptions
DumpToStreamOptions ()=default
void SetStream (Stream *s)
Stream * GetStream () const
void SetPrefixToken (const std::string &p)
void SetPrefixToken (std::nullptr_t)
const char * GetPrefixToken () const
void SetSuffixToken (const std::string &p)
void SetSuffixToken (std::nullptr_t)
const char * GetSuffixToken () const
void SetQuote (char q)
char GetQuote () const
void SetSourceSize (uint32_t s)
uint32_t GetSourceSize () const
void SetNeedsZeroTermination (bool z)
bool GetNeedsZeroTermination () const
void SetBinaryZeroIsTerminator (bool e)
bool GetBinaryZeroIsTerminator () const
void SetEscapeNonPrintables (bool e)
bool GetEscapeNonPrintables () const
void SetIgnoreMaxLength (bool e)
bool GetIgnoreMaxLength () const
void SetEscapeStyle (EscapeStyle style)
EscapeStyle GetEscapeStyle () const
Private Attributes
DataExtractor m_data
bool m_is_truncated = false
Detailed Description
Definition at line 127 of file StringPrinter.h.
Constructor & Destructor Documentation
ReadBufferAndDumpToStreamOptions() [1/3]
lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::ReadBufferAndDumpToStreamOptions () default
Referenced by ReadBufferAndDumpToStreamOptions(), and ReadBufferAndDumpToStreamOptions().
ReadBufferAndDumpToStreamOptions() [2/3]
lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::ReadBufferAndDumpToStreamOptions (ValueObject & valobj)
Definition at line 371 of file StringPrinter.cpp.
References lldb_private::ValueObject::GetTargetSP(), ReadBufferAndDumpToStreamOptions(), and lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetEscapeNonPrintables().
ReadBufferAndDumpToStreamOptions() [3/3]
lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::ReadBufferAndDumpToStreamOptions (const ReadStringAndDumpToStreamOptions & options)
Definition at line 378 of file StringPrinter.cpp.
References lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetBinaryZeroIsTerminator(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetEscapeNonPrintables(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetEscapeStyle(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetPrefixToken(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetQuote(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetStream(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetSuffixToken(), ReadBufferAndDumpToStreamOptions(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetBinaryZeroIsTerminator(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetEscapeNonPrintables(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetEscapeStyle(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetPrefixToken(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetQuote(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetStream(), and lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetSuffixToken().
Member Function Documentation
GetData()
const lldb_private::DataExtractor & lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::GetData () const inline
Definition at line 138 of file StringPrinter.h.
References m_data.
Referenced by DumpEncodedBufferToStream().
GetIsTruncated()
bool lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::GetIsTruncated () const inline
Definition at line 142 of file StringPrinter.h.
References m_is_truncated.
Referenced by DumpEncodedBufferToStream().
SetData()
void lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::SetData (DataExtractor && d) inline
Definition at line 136 of file StringPrinter.h.
References m_data.
Referenced by CharSummaryProvider(), lldb_private::formatters::ReadEncodedBufferAndDumpToStream(), and lldb_private::formatters::WCharSummaryProvider().
SetIsTruncated()
void lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::SetIsTruncated (bool t) inline
Definition at line 140 of file StringPrinter.h.
References m_is_truncated.
Referenced by lldb_private::formatters::ReadEncodedBufferAndDumpToStream().
Member Data Documentation
m_data
DataExtractor lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::m_data private
Definition at line 144 of file StringPrinter.h.
Referenced by GetData(), and SetData().
m_is_truncated
bool lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::m_is_truncated = false private
Definition at line 145 of file StringPrinter.h.
Referenced by GetIsTruncated(), and SetIsTruncated().
The documentation for this class was generated from the following files:
StringPrinter.h
StringPrinter.cpp