LLDB: lldb::SBTypeCategory Class Reference
lldb::SBTypeCategory Class Reference
#include <SBTypeCategory.h>
Public Member Functions
SBTypeCategory ()
SBTypeCategory (const lldb::SBTypeCategory &rhs)
~SBTypeCategory ()
operator bool () const
bool IsValid () const
bool GetEnabled ()
void SetEnabled (bool)
const char * GetName ()
lldb::LanguageType GetLanguageAtIndex (uint32_t idx)
uint32_t GetNumLanguages ()
void AddLanguage (lldb::LanguageType language)
bool GetDescription (lldb::SBStream &description, lldb::DescriptionLevel description_level)
uint32_t GetNumFormats ()
uint32_t GetNumSummaries ()
uint32_t GetNumFilters ()
uint32_t GetNumSynthetics ()
SBTypeNameSpecifier GetTypeNameSpecifierForFilterAtIndex (uint32_t)
SBTypeNameSpecifier GetTypeNameSpecifierForFormatAtIndex (uint32_t)
SBTypeNameSpecifier GetTypeNameSpecifierForSummaryAtIndex (uint32_t)
SBTypeNameSpecifier GetTypeNameSpecifierForSyntheticAtIndex (uint32_t)
SBTypeFilter GetFilterForType (SBTypeNameSpecifier)
SBTypeFormat GetFormatForType (SBTypeNameSpecifier)
SBTypeSummary GetSummaryForType (SBTypeNameSpecifier)
SBTypeSynthetic GetSyntheticForType (SBTypeNameSpecifier)
SBTypeFilter GetFilterAtIndex (uint32_t)
SBTypeFormat GetFormatAtIndex (uint32_t)
SBTypeSummary GetSummaryAtIndex (uint32_t)
SBTypeSynthetic GetSyntheticAtIndex (uint32_t)
bool AddTypeFormat (SBTypeNameSpecifier, SBTypeFormat)
bool DeleteTypeFormat (SBTypeNameSpecifier)
bool AddTypeSummary (SBTypeNameSpecifier, SBTypeSummary)
bool DeleteTypeSummary (SBTypeNameSpecifier)
bool AddTypeFilter (SBTypeNameSpecifier, SBTypeFilter)
bool DeleteTypeFilter (SBTypeNameSpecifier)
bool AddTypeSynthetic (SBTypeNameSpecifier, SBTypeSynthetic)
bool DeleteTypeSynthetic (SBTypeNameSpecifier)
lldb::SBTypeCategory & operator= (const lldb::SBTypeCategory &rhs)
bool operator== (lldb::SBTypeCategory &rhs)
bool operator!= (lldb::SBTypeCategory &rhs)
Protected Member Functions
lldb::TypeCategoryImplSP GetSP ()
void SetSP (const lldb::TypeCategoryImplSP &typecategory_impl_sp)
SBTypeCategory (const lldb::TypeCategoryImplSP &)
SBTypeCategory (const char *)
bool IsDefaultCategory ()
Protected Attributes
TypeCategoryImplSP m_opaque_sp
Friends
class SBDebugger
Detailed Description
Definition at line 17 of file SBTypeCategory.h.
Constructor & Destructor Documentation
SBTypeCategory() [1/4]
SBTypeCategory::SBTypeCategory ()
Definition at line 29 of file SBTypeCategory.cpp.
References LLDB_INSTRUMENT_VA.
SBTypeCategory() [2/4]
SBTypeCategory::SBTypeCategory (const lldb::SBTypeCategory & rhs)
Definition at line 35 of file SBTypeCategory.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
~SBTypeCategory()
SBTypeCategory::~SBTypeCategory () default
References AddLanguage(), AddTypeFilter(), AddTypeFormat(), AddTypeSummary(), AddTypeSynthetic(), DeleteTypeFilter(), DeleteTypeFormat(), DeleteTypeSummary(), DeleteTypeSynthetic(), GetDescription(), GetEnabled(), GetFilterAtIndex(), GetFilterForType(), GetFormatAtIndex(), GetFormatForType(), GetLanguageAtIndex(), GetNumFilters(), GetNumFormats(), GetNumLanguages(), GetNumSummaries(), GetNumSynthetics(), GetSummaryAtIndex(), GetSummaryForType(), GetSyntheticAtIndex(), GetSyntheticForType(), GetTypeNameSpecifierForFilterAtIndex(), GetTypeNameSpecifierForFormatAtIndex(), GetTypeNameSpecifierForSummaryAtIndex(), GetTypeNameSpecifierForSyntheticAtIndex(), IsValid(), operator!=(), operator=(), operator==(), and SetEnabled().
SBTypeCategory() [3/4]
SBTypeCategory::SBTypeCategory (const lldb::TypeCategoryImplSP & typecategory_impl_sp) protected
Definition at line 535 of file SBTypeCategory.cpp.
References m_opaque_sp.
SBTypeCategory() [4/4]
SBTypeCategory::SBTypeCategory (const char * name) protected
Definition at line 31 of file SBTypeCategory.cpp.
References lldb_private::DataVisualization::Categories::GetCategory(), and m_opaque_sp.
Member Function Documentation
AddLanguage()
void SBTypeCategory::AddLanguage (lldb::LanguageType language)
Definition at line 95 of file SBTypeCategory.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeCategory().
AddTypeFilter()
bool SBTypeCategory::AddTypeFilter (SBTypeNameSpecifier type_name, SBTypeFilter filter)
Definition at line 394 of file SBTypeCategory.cpp.
References lldb::SBTypeFilter::GetSP(), lldb::SBTypeNameSpecifier::GetSP(), IsValid(), lldb::SBTypeFilter::IsValid(), lldb::SBTypeNameSpecifier::IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeCategory().
AddTypeFormat()
bool SBTypeCategory::AddTypeFormat (SBTypeNameSpecifier type_name, SBTypeFormat format)
Definition at line 302 of file SBTypeCategory.cpp.
References lldb::SBTypeFormat::GetSP(), lldb::SBTypeNameSpecifier::GetSP(), IsValid(), lldb::SBTypeFormat::IsValid(), lldb::SBTypeNameSpecifier::IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeCategory().
AddTypeSummary()
bool SBTypeCategory::AddTypeSummary (SBTypeNameSpecifier type_name, SBTypeSummary summary)
Definition at line 331 of file SBTypeCategory.cpp.
References lldb_private::ScriptInterpreter::GenerateTypeScriptFunction(), lldb_private::ConstString::GetCString(), lldb::SBTypeSummary::GetData(), lldb_private::Debugger::GetDebuggerAtIndex(), lldb::SBTypeNameSpecifier::GetName(), lldb_private::Debugger::GetNumDebuggers(), lldb::SBTypeNameSpecifier::GetSP(), lldb::SBTypeSummary::GetSP(), lldb::SBTypeSummary::IsFunctionCode(), IsValid(), lldb::SBTypeNameSpecifier::IsValid(), lldb::SBTypeSummary::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, lldb::SBTypeSummary::SetFunctionName(), and lldb_private::StringList::SplitIntoLines().
Referenced by ~SBTypeCategory().
AddTypeSynthetic()
bool SBTypeCategory::AddTypeSynthetic (SBTypeNameSpecifier type_name, SBTypeSynthetic synth)
Definition at line 423 of file SBTypeCategory.cpp.
References lldb_private::ScriptInterpreter::GenerateTypeSynthClass(), lldb_private::ConstString::GetCString(), lldb::SBTypeSynthetic::GetData(), lldb_private::Debugger::GetDebuggerAtIndex(), lldb::SBTypeNameSpecifier::GetName(), lldb_private::Debugger::GetNumDebuggers(), lldb::SBTypeNameSpecifier::GetSP(), lldb::SBTypeSynthetic::GetSP(), lldb::SBTypeSynthetic::IsClassCode(), IsValid(), lldb::SBTypeNameSpecifier::IsValid(), lldb::SBTypeSynthetic::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, lldb::SBTypeSynthetic::SetClassName(), and lldb_private::StringList::SplitIntoLines().
Referenced by ~SBTypeCategory().
DeleteTypeFilter()
bool SBTypeCategory::DeleteTypeFilter (SBTypeNameSpecifier type_name)
Definition at line 411 of file SBTypeCategory.cpp.
References lldb::SBTypeNameSpecifier::GetSP(), IsValid(), lldb::SBTypeNameSpecifier::IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeCategory().
DeleteTypeFormat()
bool SBTypeCategory::DeleteTypeFormat (SBTypeNameSpecifier type_name)
Definition at line 319 of file SBTypeCategory.cpp.
References lldb::SBTypeNameSpecifier::GetSP(), IsValid(), lldb::SBTypeNameSpecifier::IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeCategory().
DeleteTypeSummary()
bool SBTypeCategory::DeleteTypeSummary (SBTypeNameSpecifier type_name)
Definition at line 382 of file SBTypeCategory.cpp.
References lldb::SBTypeNameSpecifier::GetSP(), IsValid(), lldb::SBTypeNameSpecifier::IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeCategory().
DeleteTypeSynthetic()
bool SBTypeCategory::DeleteTypeSynthetic (SBTypeNameSpecifier type_name)
Definition at line 474 of file SBTypeCategory.cpp.
References lldb::SBTypeNameSpecifier::GetSP(), IsValid(), lldb::SBTypeNameSpecifier::IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeCategory().
GetDescription()
bool SBTypeCategory::GetDescription (lldb::SBStream & description, lldb::DescriptionLevel description_level)
Definition at line 486 of file SBTypeCategory.cpp.
References GetName(), IsValid(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTypeCategory().
GetEnabled()
bool SBTypeCategory::GetEnabled ()
Definition at line 52 of file SBTypeCategory.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by lldb::SBDebugger::GetFormatForType(), and ~SBTypeCategory().
GetFilterAtIndex()
SBTypeFilter SBTypeCategory::GetFilterAtIndex (uint32_t index)
Definition at line 252 of file SBTypeCategory.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBTypeFilter.
Referenced by ~SBTypeCategory().
GetFilterForType()
SBTypeFilter SBTypeCategory::GetFilterForType (SBTypeNameSpecifier spec)
Definition at line 175 of file SBTypeCategory.cpp.
References lldb::SBTypeNameSpecifier::GetSP(), IsValid(), lldb::SBTypeNameSpecifier::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBTypeFilter.
Referenced by ~SBTypeCategory().
GetFormatAtIndex()
SBTypeFormat SBTypeCategory::GetFormatAtIndex (uint32_t index)
Definition at line 269 of file SBTypeCategory.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBTypeFormat.
Referenced by ~SBTypeCategory().
GetFormatForType()
SBTypeFormat SBTypeCategory::GetFormatForType (SBTypeNameSpecifier spec)
Definition at line 195 of file SBTypeCategory.cpp.
References lldb::SBTypeNameSpecifier::GetSP(), IsValid(), lldb::SBTypeNameSpecifier::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBTypeFormat.
Referenced by lldb::SBDebugger::GetFormatForType(), and ~SBTypeCategory().
GetLanguageAtIndex()
lldb::LanguageType SBTypeCategory::GetLanguageAtIndex (uint32_t idx)
Definition at line 79 of file SBTypeCategory.cpp.
References lldb::eLanguageTypeUnknown, IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeCategory().
GetName()
const char * SBTypeCategory::GetName ()
Definition at line 71 of file SBTypeCategory.cpp.
References lldb_private::ConstString::GetCString(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by GetDescription().
GetNumFilters()
uint32_t SBTypeCategory::GetNumFilters ()
Definition at line 119 of file SBTypeCategory.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeCategory().
GetNumFormats()
uint32_t SBTypeCategory::GetNumFormats ()
Definition at line 102 of file SBTypeCategory.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeCategory().
GetNumLanguages()
uint32_t SBTypeCategory::GetNumLanguages ()
Definition at line 87 of file SBTypeCategory.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeCategory().
GetNumSummaries()
uint32_t SBTypeCategory::GetNumSummaries ()
Definition at line 111 of file SBTypeCategory.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeCategory().
GetNumSynthetics()
uint32_t SBTypeCategory::GetNumSynthetics ()
Definition at line 127 of file SBTypeCategory.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeCategory().
GetSP()
lldb::TypeCategoryImplSP SBTypeCategory::GetSP () protected
Definition at line 524 of file SBTypeCategory.cpp.
References IsValid(), and m_opaque_sp.
Referenced by SBDebugger.
GetSummaryAtIndex()
SBTypeSummary SBTypeCategory::GetSummaryAtIndex (uint32_t index)
Definition at line 277 of file SBTypeCategory.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBTypeSummary.
Referenced by ~SBTypeCategory().
GetSummaryForType()
SBTypeSummary SBTypeCategory::GetSummaryForType (SBTypeNameSpecifier spec)
Definition at line 213 of file SBTypeCategory.cpp.
References lldb::SBTypeNameSpecifier::GetSP(), IsValid(), lldb::SBTypeNameSpecifier::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBTypeSummary.
Referenced by ~SBTypeCategory().
GetSyntheticAtIndex()
SBTypeSynthetic SBTypeCategory::GetSyntheticAtIndex (uint32_t index)
Definition at line 285 of file SBTypeCategory.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBTypeSynthetic.
Referenced by ~SBTypeCategory().
GetSyntheticForType()
SBTypeSynthetic SBTypeCategory::GetSyntheticForType (SBTypeNameSpecifier spec)
Definition at line 231 of file SBTypeCategory.cpp.
References lldb::SBTypeNameSpecifier::GetSP(), IsValid(), lldb::SBTypeNameSpecifier::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBTypeSynthetic.
Referenced by ~SBTypeCategory().
GetTypeNameSpecifierForFilterAtIndex()
lldb::SBTypeNameSpecifier SBTypeCategory::GetTypeNameSpecifierForFilterAtIndex (uint32_t index)
Definition at line 136 of file SBTypeCategory.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBTypeNameSpecifier.
Referenced by ~SBTypeCategory().
GetTypeNameSpecifierForFormatAtIndex()
lldb::SBTypeNameSpecifier SBTypeCategory::GetTypeNameSpecifierForFormatAtIndex (uint32_t index)
Definition at line 146 of file SBTypeCategory.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBTypeNameSpecifier.
Referenced by ~SBTypeCategory().
GetTypeNameSpecifierForSummaryAtIndex()
lldb::SBTypeNameSpecifier SBTypeCategory::GetTypeNameSpecifierForSummaryAtIndex (uint32_t index)
Definition at line 156 of file SBTypeCategory.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBTypeNameSpecifier.
Referenced by ~SBTypeCategory().
GetTypeNameSpecifierForSyntheticAtIndex()
lldb::SBTypeNameSpecifier SBTypeCategory::GetTypeNameSpecifierForSyntheticAtIndex (uint32_t index)
Definition at line 166 of file SBTypeCategory.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBTypeNameSpecifier.
Referenced by ~SBTypeCategory().
IsDefaultCategory()
bool SBTypeCategory::IsDefaultCategory () protected
Definition at line 539 of file SBTypeCategory.cpp.
References IsValid(), and m_opaque_sp.
IsValid()
bool SBTypeCategory::IsValid () const
Definition at line 42 of file SBTypeCategory.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by AddLanguage(), AddTypeFilter(), AddTypeFormat(), AddTypeSummary(), AddTypeSynthetic(), DeleteTypeFilter(), DeleteTypeFormat(), DeleteTypeSummary(), DeleteTypeSynthetic(), GetDescription(), GetEnabled(), GetFilterAtIndex(), GetFilterForType(), GetFormatAtIndex(), GetFormatForType(), GetLanguageAtIndex(), GetName(), GetNumFilters(), GetNumFormats(), GetNumLanguages(), GetNumSummaries(), GetNumSynthetics(), GetSP(), GetSummaryAtIndex(), GetSummaryForType(), GetSyntheticAtIndex(), GetSyntheticForType(), GetTypeNameSpecifierForFilterAtIndex(), GetTypeNameSpecifierForFormatAtIndex(), GetTypeNameSpecifierForSummaryAtIndex(), GetTypeNameSpecifierForSyntheticAtIndex(), IsDefaultCategory(), operator!=(), operator==(), SetEnabled(), and ~SBTypeCategory().
operator bool()
SBTypeCategory::operator bool () const explicit
Definition at line 46 of file SBTypeCategory.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator!=()
bool SBTypeCategory::operator!= (lldb::SBTypeCategory & rhs)
Definition at line 515 of file SBTypeCategory.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeCategory().
operator=()
lldb::SBTypeCategory & SBTypeCategory::operator= (const lldb::SBTypeCategory & rhs)
Definition at line 496 of file SBTypeCategory.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeCategory().
operator==()
bool SBTypeCategory::operator== (lldb::SBTypeCategory & rhs)
Definition at line 506 of file SBTypeCategory.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeCategory().
SetEnabled()
void SBTypeCategory::SetEnabled (bool enabled)
Definition at line 60 of file SBTypeCategory.cpp.
References lldb_private::DataVisualization::Categories::Disable(), lldb_private::DataVisualization::Categories::Enable(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeCategory().
SetSP()
void SBTypeCategory::SetSP (const lldb::TypeCategoryImplSP & typecategory_impl_sp) protected
Definition at line 530 of file SBTypeCategory.cpp.
References m_opaque_sp.
Referenced by SBDebugger.
Friends And Related Symbol Documentation
SBDebugger
friend class SBDebugger friend
Definition at line 99 of file SBTypeCategory.h.
References GetSP(), SBDebugger, and SetSP().
Referenced by SBDebugger.
Member Data Documentation
m_opaque_sp
TypeCategoryImplSP lldb::SBTypeCategory::m_opaque_sp protected
Definition at line 105 of file SBTypeCategory.h.
Referenced by AddLanguage(), AddTypeFilter(), AddTypeFormat(), AddTypeSummary(), AddTypeSynthetic(), DeleteTypeFilter(), DeleteTypeFormat(), DeleteTypeSummary(), DeleteTypeSynthetic(), GetEnabled(), GetFilterAtIndex(), GetFilterForType(), GetFormatAtIndex(), GetFormatForType(), GetLanguageAtIndex(), GetName(), GetNumFilters(), GetNumFormats(), GetNumLanguages(), GetNumSummaries(), GetNumSynthetics(), GetSP(), GetSummaryAtIndex(), GetSummaryForType(), GetSyntheticAtIndex(), GetSyntheticForType(), GetTypeNameSpecifierForFilterAtIndex(), GetTypeNameSpecifierForFormatAtIndex(), GetTypeNameSpecifierForSummaryAtIndex(), GetTypeNameSpecifierForSyntheticAtIndex(), IsDefaultCategory(), operator bool(), operator!=(), operator=(), operator==(), SBTypeCategory(), SBTypeCategory(), SBTypeCategory(), SetEnabled(), and SetSP().
The documentation for this class was generated from the following files:
SBTypeCategory.h
SBTypeCategory.cpp