LLDB: lldb_private::DumpValueObjectOptions Class Reference
lldb_private::DumpValueObjectOptions Class Reference
#include <DumpValueObjectOptions.h>
Classes
struct PointerAsArraySettings
struct PointerDepth
Public Types
typedef std::function< bool(ConstString, ConstString, const DumpValueObjectOptions &, Stream &)> DeclPrintingHelper
typedef std::function< bool(ConstString)> ChildPrintingDecider
Public Member Functions
DumpValueObjectOptions ()
DumpValueObjectOptions (ValueObject &valobj)
DumpValueObjectOptions & SetMaximumPointerDepth (uint32_t depth)
DumpValueObjectOptions & SetMaximumDepth (uint32_t depth, bool is_default)
DumpValueObjectOptions & SetDeclPrintingHelper (DeclPrintingHelper helper)
DumpValueObjectOptions & SetChildPrintingDecider (ChildPrintingDecider decider)
DumpValueObjectOptions & SetShowTypes (bool show=false)
DumpValueObjectOptions & SetShowLocation (bool show=false)
DumpValueObjectOptions & DisableObjectDescription ()
DumpValueObjectOptions & SetUseObjectDescription (bool use=false)
DumpValueObjectOptions & SetShowSummary (bool show=true)
DumpValueObjectOptions & SetUseDynamicType (lldb::DynamicValueType dyn=lldb::eNoDynamicValues)
DumpValueObjectOptions & SetUseSyntheticValue (bool use_synthetic=true)
DumpValueObjectOptions & SetScopeChecked (bool check=true)
DumpValueObjectOptions & SetFlatOutput (bool flat=false)
DumpValueObjectOptions & SetOmitSummaryDepth (uint32_t depth=0)
DumpValueObjectOptions & SetIgnoreCap (bool ignore=false)
DumpValueObjectOptions & SetRawDisplay ()
DumpValueObjectOptions & SetFormat (lldb::Format format=lldb::eFormatDefault)
DumpValueObjectOptions & SetSummary (lldb::TypeSummaryImplSP summary=lldb::TypeSummaryImplSP())
DumpValueObjectOptions & SetRootValueObjectName (const char *name=nullptr)
DumpValueObjectOptions & SetHideRootType (bool hide_root_type=false)
DumpValueObjectOptions & SetHideRootName (bool hide_root_name)
DumpValueObjectOptions & SetHideName (bool hide_name=false)
DumpValueObjectOptions & SetHideValue (bool hide_value=false)
DumpValueObjectOptions & SetHidePointerValue (bool hide=false)
DumpValueObjectOptions & SetVariableFormatDisplayLanguage (lldb::LanguageType lang=lldb::eLanguageTypeUnknown)
DumpValueObjectOptions & SetRunValidator (bool run=true)
DumpValueObjectOptions & SetUseTypeDisplayName (bool dis=false)
DumpValueObjectOptions & SetAllowOnelinerMode (bool oneliner=false)
DumpValueObjectOptions & SetRevealEmptyAggregates (bool reveal=true)
DumpValueObjectOptions & SetExpandPointerTypeFlags (unsigned flags)
DumpValueObjectOptions & SetElementCount (uint32_t element_count=0)
DumpValueObjectOptions & SetPointerAsArray (const PointerAsArraySettings &ptr_array)
Static Public Member Functions
static const DumpValueObjectOptions DefaultOptions ()
Public Attributes
uint32_t m_max_depth = UINT32_MAX
bool m_max_depth_is_default = true
lldb::DynamicValueType m_use_dynamic = lldb::eNoDynamicValues
uint32_t m_omit_summary_depth = 0
lldb::Format m_format = lldb::eFormatDefault
lldb::TypeSummaryImplSP m_summary_sp
std::string m_root_valobj_name
lldb::LanguageType m_varformat_language = lldb::eLanguageTypeUnknown
PointerDepth m_max_ptr_depth
DeclPrintingHelper m_decl_printing_helper
ChildPrintingDecider m_child_printing_decider
PointerAsArraySettings m_pointer_as_array
unsigned m_expand_ptr_type_flags = 0
bool m_use_synthetic: 1
bool m_scope_already_checked: 1
bool m_flat_output: 1
bool m_ignore_cap: 1
bool m_show_types: 1
bool m_show_location: 1
bool m_use_object_desc: 1
bool m_hide_root_type: 1
bool m_hide_root_name: 1
bool m_hide_name: 1
bool m_hide_value: 1
bool m_run_validator: 1
bool m_use_type_display_name: 1
bool m_allow_oneliner_mode: 1
bool m_hide_pointer_value: 1
bool m_reveal_empty_aggregates: 1
Detailed Description
Definition at line 22 of file DumpValueObjectOptions.h.
Member Typedef Documentation
ChildPrintingDecider
typedef std::function<bool(ConstString)> lldb_private::DumpValueObjectOptions::ChildPrintingDecider
Definition at line 55 of file DumpValueObjectOptions.h.
DeclPrintingHelper
typedef std::function<bool(ConstString, ConstString, const DumpValueObjectOptions &, Stream &)> lldb_private::DumpValueObjectOptions::DeclPrintingHelper
Definition at line 53 of file DumpValueObjectOptions.h.
Constructor & Destructor Documentation
DumpValueObjectOptions() [1/2]
DumpValueObjectOptions::DumpValueObjectOptions ()
Definition at line 16 of file DumpValueObjectOptions.cpp.
References m_allow_oneliner_mode, m_child_printing_decider, m_decl_printing_helper, m_flat_output, m_hide_name, m_hide_pointer_value, m_hide_root_name, m_hide_root_type, m_hide_value, m_ignore_cap, m_pointer_as_array, m_reveal_empty_aggregates, m_root_valobj_name, m_run_validator, m_scope_already_checked, m_show_location, m_show_types, m_summary_sp, m_use_object_desc, m_use_synthetic, and m_use_type_display_name.
Referenced by DefaultOptions(), DisableObjectDescription(), DumpValueObjectOptions(), SetFlatOutput(), SetFormat(), SetHideName(), SetHidePointerValue(), SetHideValue(), SetIgnoreCap(), SetPointerAsArray(), SetRawDisplay(), SetRunValidator(), SetScopeChecked(), SetShowLocation(), SetShowSummary(), and SetShowTypes().
DumpValueObjectOptions() [2/2]
DumpValueObjectOptions::DumpValueObjectOptions (ValueObject & valobj)
Definition at line 26 of file DumpValueObjectOptions.cpp.
References DumpValueObjectOptions(), lldb_private::ValueObject::GetDynamicValueType(), lldb_private::ValueObject::GetPreferredDisplayLanguage(), lldb_private::ValueObject::IsSynthetic(), m_use_dynamic, m_use_synthetic, and m_varformat_language.
Member Function Documentation
DefaultOptions()
const DumpValueObjectOptions lldb_private::DumpValueObjectOptions::DefaultOptions () inline static
Definition at line 57 of file DumpValueObjectOptions.h.
References DumpValueObjectOptions().
DisableObjectDescription()
DumpValueObjectOptions & DumpValueObjectOptions::DisableObjectDescription ()
Definition at line 68 of file DumpValueObjectOptions.cpp.
References DumpValueObjectOptions(), SetHideName(), SetHideRootType(), SetHideValue(), SetShowSummary(), and SetUseObjectDescription().
SetAllowOnelinerMode()
DumpValueObjectOptions & DumpValueObjectOptions::SetAllowOnelinerMode (bool oneliner = false)
Definition at line 202 of file DumpValueObjectOptions.cpp.
References m_allow_oneliner_mode.
Referenced by GetDumpOptions(), and SetRawDisplay().
SetChildPrintingDecider()
DumpValueObjectOptions & DumpValueObjectOptions::SetChildPrintingDecider (ChildPrintingDecider decider)
Definition at line 53 of file DumpValueObjectOptions.cpp.
References m_child_printing_decider.
Referenced by dump_type_value().
SetDeclPrintingHelper()
DumpValueObjectOptions & DumpValueObjectOptions::SetDeclPrintingHelper (DeclPrintingHelper helper)
Definition at line 47 of file DumpValueObjectOptions.cpp.
References m_decl_printing_helper.
Referenced by CommandObjectFrameDiagnose::DoExecute().
SetElementCount()
DumpValueObjectOptions & DumpValueObjectOptions::SetElementCount (uint32_t element_count = 0)
Definition at line 220 of file DumpValueObjectOptions.cpp.
References m_pointer_as_array.
Referenced by lldb_private::OptionGroupValueObjectDisplay::GetAsDumpOptions(), and lldb_private::ValueObjectPrinter::PrintChild().
SetExpandPointerTypeFlags()
DumpValueObjectOptions & DumpValueObjectOptions::SetExpandPointerTypeFlags (unsigned flags)
Definition at line 214 of file DumpValueObjectOptions.cpp.
References m_expand_ptr_type_flags.
Referenced by lldb_private::CommandObjectDWIMPrint::DoExecute().
SetFlatOutput()
DumpValueObjectOptions & DumpValueObjectOptions::SetFlatOutput (bool flat = false)
Definition at line 109 of file DumpValueObjectOptions.cpp.
References DumpValueObjectOptions(), and m_flat_output.
Referenced by lldb_private::OptionGroupValueObjectDisplay::GetAsDumpOptions().
SetFormat()
DumpValueObjectOptions & DumpValueObjectOptions::SetFormat (lldb::Format format = lldb::eFormatDefault)
Definition at line 136 of file DumpValueObjectOptions.cpp.
References DumpValueObjectOptions(), and m_format.
Referenced by CommandObjectTargetVariable::DumpValueObject(), lldb_private::OptionGroupValueObjectDisplay::GetAsDumpOptions(), and lldb_private::ValueObjectPrinter::PrintChild().
SetHideName()
DumpValueObjectOptions & DumpValueObjectOptions::SetHideName (bool hide_name = false)
Definition at line 168 of file DumpValueObjectOptions.cpp.
References DumpValueObjectOptions(), and m_hide_name.
Referenced by DisableObjectDescription(), lldb_private::Watchpoint::DumpSnapshots(), lldb_private::OptionGroupValueObjectDisplay::GetAsDumpOptions(), lldb_private::ValueObjectPrinter::PrintChild(), lldb_private::ValueObjectPrinter::PrintDecl(), and SetRawDisplay().
SetHidePointerValue()
DumpValueObjectOptions & DumpValueObjectOptions::SetHidePointerValue (bool hide = false)
Definition at line 178 of file DumpValueObjectOptions.cpp.
References DumpValueObjectOptions(), and m_hide_pointer_value.
SetHideRootName()
DumpValueObjectOptions & DumpValueObjectOptions::SetHideRootName (bool hide_root_name)
Definition at line 163 of file DumpValueObjectOptions.cpp.
References m_hide_root_name.
Referenced by lldb_private::CommandObjectDWIMPrint::DoExecute(), lldb_private::Watchpoint::DumpSnapshots(), and GetDumpOptions().
SetHideRootType()
DumpValueObjectOptions & DumpValueObjectOptions::SetHideRootType (bool hide_root_type = false)
Definition at line 157 of file DumpValueObjectOptions.cpp.
References m_hide_root_type.
Referenced by DisableObjectDescription(), dump_type_value(), lldb_private::Watchpoint::DumpSnapshots(), lldb_private::OptionGroupValueObjectDisplay::GetAsDumpOptions(), and GetDumpOptions().
SetHideValue()
DumpValueObjectOptions & DumpValueObjectOptions::SetHideValue (bool hide_value = false)
Definition at line 173 of file DumpValueObjectOptions.cpp.
References DumpValueObjectOptions(), and m_hide_value.
Referenced by DisableObjectDescription(), lldb_private::OptionGroupValueObjectDisplay::GetAsDumpOptions(), lldb_private::ValueObjectPrinter::PrintChild(), and SetRawDisplay().
SetIgnoreCap()
DumpValueObjectOptions & DumpValueObjectOptions::SetIgnoreCap (bool ignore = false)
Definition at line 120 of file DumpValueObjectOptions.cpp.
References DumpValueObjectOptions(), and m_ignore_cap.
Referenced by lldb_private::OptionGroupValueObjectDisplay::GetAsDumpOptions(), and SetRawDisplay().
SetMaximumDepth()
DumpValueObjectOptions & DumpValueObjectOptions::SetMaximumDepth (uint32_t depth, bool is_default)
Definition at line 40 of file DumpValueObjectOptions.cpp.
References m_max_depth, and m_max_depth_is_default.
Referenced by lldb_private::OptionGroupValueObjectDisplay::GetAsDumpOptions().
SetMaximumPointerDepth()
DumpValueObjectOptions & DumpValueObjectOptions::SetMaximumPointerDepth (uint32_t depth)
Definition at line 34 of file DumpValueObjectOptions.cpp.
References m_max_ptr_depth.
Referenced by lldb_private::OptionGroupValueObjectDisplay::GetAsDumpOptions().
SetOmitSummaryDepth()
DumpValueObjectOptions & DumpValueObjectOptions::SetOmitSummaryDepth (uint32_t depth = 0)
Definition at line 115 of file DumpValueObjectOptions.cpp.
References m_omit_summary_depth.
Referenced by lldb_private::OptionGroupValueObjectDisplay::GetAsDumpOptions(), lldb_private::ValueObjectPrinter::PrintChild(), SetRawDisplay(), and SetShowSummary().
SetPointerAsArray()
DumpValueObjectOptions & DumpValueObjectOptions::SetPointerAsArray (const PointerAsArraySettings & ptr_array)
Definition at line 225 of file DumpValueObjectOptions.cpp.
References DumpValueObjectOptions(), and m_pointer_as_array.
SetRawDisplay()
DumpValueObjectOptions & DumpValueObjectOptions::SetRawDisplay ()
Definition at line 125 of file DumpValueObjectOptions.cpp.
References DumpValueObjectOptions(), SetAllowOnelinerMode(), SetHideName(), SetHideValue(), SetIgnoreCap(), SetOmitSummaryDepth(), SetUseSyntheticValue(), SetUseTypeDisplayName(), and UINT32_MAX.
Referenced by lldb_private::OptionGroupValueObjectDisplay::GetAsDumpOptions().
SetRevealEmptyAggregates()
DumpValueObjectOptions & DumpValueObjectOptions::SetRevealEmptyAggregates (bool reveal = true)
Definition at line 208 of file DumpValueObjectOptions.cpp.
References m_reveal_empty_aggregates.
SetRootValueObjectName()
DumpValueObjectOptions & DumpValueObjectOptions::SetRootValueObjectName (const char * name = nullptr)
Definition at line 148 of file DumpValueObjectOptions.cpp.
References m_root_valobj_name.
Referenced by CommandObjectTargetVariable::DumpValueObject(), and lldb_private::ValueObjectPrinter::PrintChild().
SetRunValidator()
DumpValueObjectOptions & DumpValueObjectOptions::SetRunValidator (bool run = true)
Definition at line 190 of file DumpValueObjectOptions.cpp.
References DumpValueObjectOptions(), and m_run_validator.
Referenced by lldb_private::OptionGroupValueObjectDisplay::GetAsDumpOptions().
SetScopeChecked()
DumpValueObjectOptions & DumpValueObjectOptions::SetScopeChecked (bool check = true)
Definition at line 104 of file DumpValueObjectOptions.cpp.
References DumpValueObjectOptions(), and m_scope_already_checked.
Referenced by lldb_private::ValueObjectPrinter::PrintChild().
SetShowLocation()
DumpValueObjectOptions & DumpValueObjectOptions::SetShowLocation (bool show = false)
Definition at line 63 of file DumpValueObjectOptions.cpp.
References DumpValueObjectOptions(), and m_show_location.
Referenced by lldb_private::OptionGroupValueObjectDisplay::GetAsDumpOptions(), and GetDumpOptions().
SetShowSummary()
DumpValueObjectOptions & DumpValueObjectOptions::SetShowSummary (bool show = true)
Definition at line 84 of file DumpValueObjectOptions.cpp.
References DumpValueObjectOptions(), SetOmitSummaryDepth(), and UINT32_MAX.
Referenced by DisableObjectDescription(), and lldb_private::OptionGroupValueObjectDisplay::GetAsDumpOptions().
SetShowTypes()
DumpValueObjectOptions & DumpValueObjectOptions::SetShowTypes (bool show = false)
Definition at line 58 of file DumpValueObjectOptions.cpp.
References DumpValueObjectOptions(), and m_show_types.
Referenced by lldb_private::OptionGroupValueObjectDisplay::GetAsDumpOptions(), and GetDumpOptions().
SetSummary()
DumpValueObjectOptions & DumpValueObjectOptions::SetSummary (lldb::TypeSummaryImplSP summary = lldb::TypeSummaryImplSP())
Definition at line 142 of file DumpValueObjectOptions.cpp.
References m_summary_sp.
Referenced by lldb_private::OptionGroupValueObjectDisplay::GetAsDumpOptions(), and lldb_private::ValueObjectPrinter::PrintChild().
SetUseDynamicType()
DumpValueObjectOptions & DumpValueObjectOptions::SetUseDynamicType (lldb::DynamicValueType dyn = lldb::eNoDynamicValues)
Definition at line 93 of file DumpValueObjectOptions.cpp.
References m_use_dynamic.
Referenced by lldb_private::Watchpoint::DumpSnapshots(), lldb_private::OptionGroupValueObjectDisplay::GetAsDumpOptions(), and GetDumpOptions().
SetUseObjectDescription()
DumpValueObjectOptions & DumpValueObjectOptions::SetUseObjectDescription (bool use = false)
Definition at line 79 of file DumpValueObjectOptions.cpp.
References m_use_object_desc.
Referenced by DisableObjectDescription(), and lldb_private::OptionGroupValueObjectDisplay::GetAsDumpOptions().
SetUseSyntheticValue()
DumpValueObjectOptions & DumpValueObjectOptions::SetUseSyntheticValue (bool use_synthetic = true)
Definition at line 99 of file DumpValueObjectOptions.cpp.
References m_use_synthetic.
Referenced by lldb_private::OptionGroupValueObjectDisplay::GetAsDumpOptions(), GetDumpOptions(), and SetRawDisplay().
SetUseTypeDisplayName()
DumpValueObjectOptions & DumpValueObjectOptions::SetUseTypeDisplayName (bool dis = false)
Definition at line 196 of file DumpValueObjectOptions.cpp.
References m_use_type_display_name.
Referenced by SetRawDisplay().
SetVariableFormatDisplayLanguage()
DumpValueObjectOptions & DumpValueObjectOptions::SetVariableFormatDisplayLanguage (lldb::LanguageType lang = lldb::eLanguageTypeUnknown)
Definition at line 184 of file DumpValueObjectOptions.cpp.
References m_varformat_language.
Member Data Documentation
m_allow_oneliner_mode
bool lldb_private::DumpValueObjectOptions::m_allow_oneliner_mode
Definition at line 162 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetAllowOnelinerMode().
m_child_printing_decider
ChildPrintingDecider lldb_private::DumpValueObjectOptions::m_child_printing_decider
Definition at line 145 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetChildPrintingDecider().
m_decl_printing_helper
DeclPrintingHelper lldb_private::DumpValueObjectOptions::m_decl_printing_helper
Definition at line 144 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetDeclPrintingHelper().
m_expand_ptr_type_flags
unsigned lldb_private::DumpValueObjectOptions::m_expand_ptr_type_flags = 0
Definition at line 147 of file DumpValueObjectOptions.h.
Referenced by SetExpandPointerTypeFlags().
m_flat_output
bool lldb_private::DumpValueObjectOptions::m_flat_output
Definition at line 151 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetFlatOutput().
m_format
lldb::Format lldb_private::DumpValueObjectOptions::m_format = lldb::eFormatDefault
Definition at line 139 of file DumpValueObjectOptions.h.
Referenced by SetFormat().
m_hide_name
bool lldb_private::DumpValueObjectOptions::m_hide_name
Definition at line 158 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetHideName().
m_hide_pointer_value
bool lldb_private::DumpValueObjectOptions::m_hide_pointer_value
Definition at line 163 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetHidePointerValue().
m_hide_root_name
bool lldb_private::DumpValueObjectOptions::m_hide_root_name
Definition at line 157 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetHideRootName().
m_hide_root_type
bool lldb_private::DumpValueObjectOptions::m_hide_root_type
Definition at line 156 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetHideRootType().
m_hide_value
bool lldb_private::DumpValueObjectOptions::m_hide_value
Definition at line 159 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetHideValue().
m_ignore_cap
bool lldb_private::DumpValueObjectOptions::m_ignore_cap
Definition at line 152 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetIgnoreCap().
m_max_depth
uint32_t lldb_private::DumpValueObjectOptions::m_max_depth = UINT32_MAX
Definition at line 135 of file DumpValueObjectOptions.h.
Referenced by SetMaximumDepth().
m_max_depth_is_default
bool lldb_private::DumpValueObjectOptions::m_max_depth_is_default = true
Definition at line 136 of file DumpValueObjectOptions.h.
Referenced by SetMaximumDepth().
m_max_ptr_depth
PointerDepth lldb_private::DumpValueObjectOptions::m_max_ptr_depth
Definition at line 143 of file DumpValueObjectOptions.h.
Referenced by SetMaximumPointerDepth().
m_omit_summary_depth
uint32_t lldb_private::DumpValueObjectOptions::m_omit_summary_depth = 0
Definition at line 138 of file DumpValueObjectOptions.h.
Referenced by lldb_private::ValueObjectPrinter::PrintChild(), and SetOmitSummaryDepth().
m_pointer_as_array
PointerAsArraySettings lldb_private::DumpValueObjectOptions::m_pointer_as_array
Definition at line 146 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), SetElementCount(), and SetPointerAsArray().
m_reveal_empty_aggregates
bool lldb_private::DumpValueObjectOptions::m_reveal_empty_aggregates
Definition at line 164 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetRevealEmptyAggregates().
m_root_valobj_name
std::string lldb_private::DumpValueObjectOptions::m_root_valobj_name
Definition at line 141 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetRootValueObjectName().
m_run_validator
bool lldb_private::DumpValueObjectOptions::m_run_validator
Definition at line 160 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetRunValidator().
m_scope_already_checked
bool lldb_private::DumpValueObjectOptions::m_scope_already_checked
Definition at line 150 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetScopeChecked().
m_show_location
bool lldb_private::DumpValueObjectOptions::m_show_location
Definition at line 154 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetShowLocation().
m_show_types
bool lldb_private::DumpValueObjectOptions::m_show_types
Definition at line 153 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetShowTypes().
m_summary_sp
lldb::TypeSummaryImplSP lldb_private::DumpValueObjectOptions::m_summary_sp
Definition at line 140 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetSummary().
m_use_dynamic
lldb::DynamicValueType lldb_private::DumpValueObjectOptions::m_use_dynamic = lldb::eNoDynamicValues
Definition at line 137 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetUseDynamicType().
m_use_object_desc
bool lldb_private::DumpValueObjectOptions::m_use_object_desc
Definition at line 155 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetUseObjectDescription().
m_use_synthetic
bool lldb_private::DumpValueObjectOptions::m_use_synthetic
Definition at line 149 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), DumpValueObjectOptions(), and SetUseSyntheticValue().
m_use_type_display_name
bool lldb_private::DumpValueObjectOptions::m_use_type_display_name
Definition at line 161 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetUseTypeDisplayName().
m_varformat_language
lldb::LanguageType lldb_private::DumpValueObjectOptions::m_varformat_language = lldb::eLanguageTypeUnknown
Definition at line 142 of file DumpValueObjectOptions.h.
Referenced by DumpValueObjectOptions(), and SetVariableFormatDisplayLanguage().
The documentation for this class was generated from the following files:
DumpValueObjectOptions.h
DumpValueObjectOptions.cpp