LLDB: RemoteNXMapTable Class Reference
RemoteNXMapTable Class Reference
Classes
class const_iterator
Public Types
typedef std::pair< ConstString, ObjCLanguageRuntime::ObjCISA > element
Public Member Functions
RemoteNXMapTable ()
void Dump ()
bool ParseHeader (Process *process, lldb::addr_t load_addr)
const_iterator begin ()
const_iterator end ()
uint32_t GetCount () const
uint32_t GetBucketCount () const
lldb::addr_t GetBucketDataPointer () const
lldb::addr_t GetTableLoadAddress () const
Private Attributes
uint32_t m_count = 0
uint32_t m_num_buckets_minus_one = 0
lldb::addr_t m_buckets_ptr = LLDB_INVALID_ADDRESS
lldb_private::Process * m_process = nullptr
const_iterator m_end_iterator
lldb::addr_t m_load_addr = LLDB_INVALID_ADDRESS
size_t m_map_pair_size = 0
lldb::addr_t m_invalid_key = 0
Friends
class const_iterator
Detailed Description
Definition at line 1276 of file AppleObjCRuntimeV2.cpp.
Member Typedef Documentation
element
typedef std::pair<ConstString, ObjCLanguageRuntime::ObjCISA> RemoteNXMapTable::element
Definition at line 1337 of file AppleObjCRuntimeV2.cpp.
Constructor & Destructor Documentation
RemoteNXMapTable()
RemoteNXMapTable::RemoteNXMapTable () inline
Definition at line 1278 of file AppleObjCRuntimeV2.cpp.
References error().
Referenced by RemoteNXMapTable::const_iterator::operator++().
Member Function Documentation
begin()
const_iterator RemoteNXMapTable::begin () inline
Definition at line 1436 of file AppleObjCRuntimeV2.cpp.
Dump()
void RemoteNXMapTable::Dump () inline
Definition at line 1280 of file AppleObjCRuntimeV2.cpp.
References lldb_private::Symbol::GetLoadAddress(), and lldb_private::SymbolContext::symbol.
end()
const_iterator RemoteNXMapTable::end () inline
Definition at line 1440 of file AppleObjCRuntimeV2.cpp.
GetBucketCount()
uint32_t RemoteNXMapTable::GetBucketCount () const inline
Definition at line 1444 of file AppleObjCRuntimeV2.cpp.
Referenced by lldb_private::AppleObjCRuntimeV2::GetClassDescriptorImpl().
GetBucketDataPointer()
lldb::addr_t RemoteNXMapTable::GetBucketDataPointer () const inline
Definition at line 1446 of file AppleObjCRuntimeV2.cpp.
Referenced by lldb_private::AppleObjCRuntimeV2::GetClassDescriptorImpl().
GetCount()
uint32_t RemoteNXMapTable::GetCount () const inline
Definition at line 1442 of file AppleObjCRuntimeV2.cpp.
Referenced by lldb_private::AppleObjCRuntimeV2::GetClassDescriptorImpl().
GetTableLoadAddress()
lldb::addr_t RemoteNXMapTable::GetTableLoadAddress () const inline
Definition at line 1448 of file AppleObjCRuntimeV2.cpp.
ParseHeader()
bool RemoteNXMapTable::ParseHeader (Process * process, lldb::addr_t load_addr) inline
Definition at line 1288 of file AppleObjCRuntimeV2.cpp.
References error(), LLDB_INVALID_ADDRESS, LLDB_INVALID_IVAR_OFFSET, and m_process.
Referenced by lldb_private::AppleObjCRuntimeV2::GetClassDescriptorImpl().
Friends And Related Symbol Documentation
const_iterator
friend class const_iterator friend
Definition at line 1339 of file AppleObjCRuntimeV2.cpp.
Member Data Documentation
m_buckets_ptr
lldb::addr_t RemoteNXMapTable::m_buckets_ptr = LLDB_INVALID_ADDRESS private
Definition at line 1454 of file AppleObjCRuntimeV2.cpp.
Referenced by RemoteNXMapTable::const_iterator::operator=().
m_count
uint32_t RemoteNXMapTable::m_count = 0 private
Definition at line 1452 of file AppleObjCRuntimeV2.cpp.
Referenced by RemoteNXMapTable::const_iterator::const_iterator(), and RemoteNXMapTable::const_iterator::operator=().
m_end_iterator
const_iterator RemoteNXMapTable::m_end_iterator private
Definition at line 1456 of file AppleObjCRuntimeV2.cpp.
m_invalid_key
lldb::addr_t RemoteNXMapTable::m_invalid_key = 0 private
Definition at line 1459 of file AppleObjCRuntimeV2.cpp.
m_load_addr
lldb::addr_t RemoteNXMapTable::m_load_addr = LLDB_INVALID_ADDRESS private
Definition at line 1457 of file AppleObjCRuntimeV2.cpp.
m_map_pair_size
size_t RemoteNXMapTable::m_map_pair_size = 0 private
Definition at line 1458 of file AppleObjCRuntimeV2.cpp.
m_num_buckets_minus_one
uint32_t RemoteNXMapTable::m_num_buckets_minus_one = 0 private
Definition at line 1453 of file AppleObjCRuntimeV2.cpp.
Referenced by RemoteNXMapTable::const_iterator::const_iterator().
m_process
lldb_private::Process* RemoteNXMapTable::m_process = nullptr private
Definition at line 1455 of file AppleObjCRuntimeV2.cpp.
Referenced by RemoteNXMapTable::const_iterator::const_iterator(), RemoteNXMapTable::const_iterator::const_iterator(), RemoteNXMapTable::const_iterator::operator=(), and ParseHeader().
The documentation for this class was generated from the following file:
AppleObjCRuntimeV2.cpp