LLDB: lldb_private::TargetList Class Reference
lldb_private::TargetList Class Reference
#include <TargetList.h>
Public Types
enum { eBroadcastBitInterrupt = (1 << 0) }
Broadcaster event bits definitions.
typedef std::vector< lldb::TargetSP > collection
typedef LockingAdaptedIterable< std::recursive_mutex, collection > TargetIterable
Public Member Functions
llvm::StringRef GetBroadcasterClass () const override
This needs to be filled in if you are going to register the broadcaster with the broadcaster manager and do broadcaster class matching.
Status CreateTarget (Debugger &debugger, llvm::StringRef user_exe_path, llvm::StringRef triple_str, LoadDependentFiles get_dependent_modules, const OptionGroupPlatform *platform_options, lldb::TargetSP &target_sp)
Create a new Target.
Status CreateTarget (Debugger &debugger, llvm::StringRef user_exe_path, const ArchSpec &arch, LoadDependentFiles get_dependent_modules, lldb::PlatformSP &platform_sp, lldb::TargetSP &target_sp)
Create a new Target.
bool DeleteTarget (lldb::TargetSP &target_sp)
Delete a Target object from the list.
size_t GetNumTargets () const
lldb::TargetSP GetTargetAtIndex (uint32_t index) const
uint32_t GetIndexOfTarget (lldb::TargetSP target_sp) const
lldb::TargetSP FindTargetWithExecutableAndArchitecture (const FileSpec &exe_file_spec, const ArchSpec *exe_arch_ptr=nullptr) const
Find the target that contains has an executable whose path matches exe_file_spec, and whose architecture matches arch_ptr if arch_ptr is not nullptr.
lldb::TargetSP FindTargetWithProcessID (lldb::pid_t pid) const
Find the target that contains a process with process ID pid.
lldb::TargetSP FindTargetWithProcess (lldb_private::Process *process) const
lldb::TargetSP FindTargetByGloballyUniqueID (lldb::user_id_t id) const
Find the target that has a globally unique ID that matches ID id.
lldb::TargetSP GetTargetSP (Target *target) const
uint32_t SendAsyncInterrupt (lldb::pid_t pid=LLDB_INVALID_PROCESS_ID)
Send an async interrupt to one or all processes.
uint32_t SignalIfRunning (lldb::pid_t pid, int signo)
void SetSelectedTarget (uint32_t index)
void SetSelectedTarget (const lldb::TargetSP &target)
lldb::TargetSP GetSelectedTarget ()
bool AnyTargetContainsModule (Module &module)
Returns whether any module, including ones in the process of being added, contains this module.
TargetIterable Targets ()
Public Member Functions inherited from lldb_private::Broadcaster
Broadcaster (lldb::BroadcasterManagerSP manager_sp, std::string name)
Construct with a broadcaster with a name.
virtual ~Broadcaster ()
Destructor.
void CheckInWithManager ()
void BroadcastEvent (lldb::EventSP &event_sp)
Broadcast an event which has no associated data.
void BroadcastEventIfUnique (lldb::EventSP &event_sp)
void BroadcastEvent (uint32_t event_type, const lldb::EventDataSP &event_data_sp)
void BroadcastEvent (uint32_t event_type)
void BroadcastEventIfUnique (uint32_t event_type)
void Clear ()
virtual void AddInitialEventsToListener (const lldb::ListenerSP &listener_sp, uint32_t requested_events)
uint32_t AddListener (const lldb::ListenerSP &listener_sp, uint32_t event_mask)
Listen for any events specified by event_mask.
const std::string & GetBroadcasterName ()
Get this broadcaster's name.
bool GetEventNames (Stream &s, const uint32_t event_mask, bool prefix_with_broadcaster_name) const
Get the event name(s) for one or more event bits.
void SetEventName (uint32_t event_mask, const char *name)
Set the name for an event bit.
const char * GetEventName (uint32_t event_mask) const
bool EventTypeHasListeners (uint32_t event_type)
bool RemoveListener (const lldb::ListenerSP &listener_sp, uint32_t event_mask=UINT32_MAX)
Removes a Listener from this broadcasters list and frees the event bits specified by event_mask that were previously acquired by listener (assuming listener was listening to this object) for other listener objects to use.
bool HijackBroadcaster (const lldb::ListenerSP &listener_sp, uint32_t event_mask=UINT32_MAX)
Provides a simple mechanism to temporarily redirect events from broadcaster.
bool IsHijackedForEvent (uint32_t event_mask)
void RestoreBroadcaster ()
Restore the state of the Broadcaster from a previous hijack attempt.
lldb::BroadcasterManagerSP GetManager ()
void SetPrimaryListener (lldb::ListenerSP listener_sp)
lldb::ListenerSP GetPrimaryListener ()
Static Public Member Functions
static llvm::StringRef GetStaticBroadcasterClass ()
Private Member Functions
TargetList (Debugger &debugger)
Constructor.
void RegisterInProcessTarget (lldb::TargetSP target_sp)
void UnregisterInProcessTarget (lldb::TargetSP target_sp)
bool IsTargetInProcess (lldb::TargetSP target_sp)
void AddTargetInternal (lldb::TargetSP target_sp, bool do_select)
void SetSelectedTargetInternal (uint32_t index)
TargetList (const TargetList &)=delete
const TargetList & operator= (const TargetList &)=delete
Static Private Member Functions
static Status CreateTargetInternal (Debugger &debugger, llvm::StringRef user_exe_path, llvm::StringRef triple_str, LoadDependentFiles load_dependent_files, const OptionGroupPlatform *platform_options, lldb::TargetSP &target_sp)
static Status CreateTargetInternal (Debugger &debugger, llvm::StringRef user_exe_path, const ArchSpec &arch, LoadDependentFiles get_dependent_modules, lldb::PlatformSP &platform_sp, lldb::TargetSP &target_sp)
Private Attributes
collection m_target_list
std::unordered_set< lldb::TargetSP > m_in_process_target_list
std::recursive_mutex m_target_list_mutex
uint32_t m_selected_target_idx
Friends
class Debugger
Additional Inherited Members
Protected Types inherited from lldb_private::Broadcaster
typedef std::shared_ptr< BroadcasterImpl > BroadcasterImplSP
typedef std::weak_ptr< BroadcasterImpl > BroadcasterImplWP
Protected Member Functions inherited from lldb_private::Broadcaster
BroadcasterImplSP GetBroadcasterImpl ()
const char * GetHijackingListenerName ()
Detailed Description
Definition at line 21 of file TargetList.h.
Member Typedef Documentation
collection
typedef std::vector<lldb::TargetSP> lldb_private::TargetList::collection
Definition at line 46 of file TargetList.h.
TargetIterable
typedef LockingAdaptedIterable<std::recursive_mutex, collection> lldb_private::TargetList::TargetIterable
Definition at line 48 of file TargetList.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Broadcaster event bits definitions.
Enumerator
eBroadcastBitInterrupt
Definition at line 36 of file TargetList.h.
Constructor & Destructor Documentation
TargetList() [1/2]
TargetList::TargetList (Debugger & debugger) private
Constructor.
The constructor for the target list is private. Clients can get ahold of the one and only target list through the lldb_private::Debugger::GetSharedInstance().GetTargetList().
See also
static TargetList& lldb_private::Debugger::GetTargetList().
Definition at line 38 of file TargetList.cpp.
References lldb_private::Broadcaster::Broadcaster(), lldb_private::Broadcaster::CheckInWithManager(), Debugger, GetStaticBroadcasterClass(), m_selected_target_idx, m_target_list, m_target_list_mutex, and TargetList().
Referenced by operator=(), TargetList(), and TargetList().
TargetList() [2/2]
lldb_private::TargetList::TargetList (const TargetList &) private delete
References TargetList().
Member Function Documentation
AddTargetInternal()
void TargetList::AddTargetInternal (lldb::TargetSP target_sp, bool do_select) private
Definition at line 527 of file TargetList.cpp.
References lldbassert, m_target_list, m_target_list_mutex, SetSelectedTargetInternal(), and UnregisterInProcessTarget().
AnyTargetContainsModule()
bool TargetList::AnyTargetContainsModule (Module & module)
Returns whether any module, including ones in the process of being added, contains this module.
I don't want to give direct access to these not yet added target, but for interruption purposes, we might need to ask whether this target contains this module.
Definition at line 564 of file TargetList.cpp.
References m_in_process_target_list, m_target_list, and m_target_list_mutex.
CreateTarget() [1/2]
Status lldb_private::TargetList::CreateTarget (Debugger & debugger, llvm::StringRef user_exe_path, const ArchSpec & arch, LoadDependentFiles get_dependent_modules, lldb::PlatformSP & platform_sp, lldb::TargetSP & target_sp)
Create a new Target.
Same as the function above, but used when you already know the platform you will be using
References Debugger, and LLDB_INVALID_PROCESS_ID.
CreateTarget() [2/2]
Status lldb_private::TargetList::CreateTarget (Debugger & debugger, llvm::StringRef user_exe_path, llvm::StringRef triple_str, LoadDependentFiles get_dependent_modules, const OptionGroupPlatform * platform_options, lldb::TargetSP & target_sp)
Create a new Target.
Clients must use this function to create a Target. This allows a global list of targets to be maintained in a central location so signal handlers and other global functions can use it to locate an appropriate target to deliver asynchronous information to.
Parameters
[in] debugger The debugger to associate this target with
[in] user_exe_path The main executable file for a debug target. This value can be empty and the file can be set later using: Target::SetExecutableModule (ModuleSP&)
[in] triple_str A target triple string to be used for the target. This can be nullptr if the triple is not known or when attaching to a process.
[in] get_dependent_modules Track down the dependent modules for an executable and load those into the module list.
[in] platform_options A pointer to the platform options to use when creating this target. If this value is nullptr, then the currently selected platform will be used.
[out] target_sp A shared pointer to a target that will be filled in if this call is successful.
Returns
An error object that indicates success or failure
References Debugger.
Referenced by lldb_private::platform_gdb_server::PlatformRemoteGDBServer::Attach(), lldb_private::PlatformWindows::Attach(), PlatformPOSIX::Attach(), lldb_private::Platform::DoConnectProcess(), CommandObjectProcessAttach::DoExecute(), and CommandObjectTargetCreate::DoExecute().
CreateTargetInternal() [1/2]
Status lldb_private::TargetList::CreateTargetInternal (Debugger & debugger, llvm::StringRef user_exe_path, const ArchSpec & arch, LoadDependentFiles get_dependent_modules, lldb::PlatformSP & platform_sp, lldb::TargetSP & target_sp) static private
References Debugger.
CreateTargetInternal() [2/2]
Status lldb_private::TargetList::CreateTargetInternal (Debugger & debugger, llvm::StringRef user_exe_path, llvm::StringRef triple_str, LoadDependentFiles load_dependent_files, const OptionGroupPlatform * platform_options, lldb::TargetSP & target_sp) static private
References Debugger.
DeleteTarget()
bool TargetList::DeleteTarget (lldb::TargetSP & target_sp)
Delete a Target object from the list.
When clients are done with the Target objects, this function should be called to release the memory associated with a target object.
Parameters
[in] target_sp The shared pointer to a target.
Returns
Returns true if the target was successfully removed from from this target list, false otherwise. The client will be left with the last remaining shared pointer to the target in target_sp which can then be properly released.
Definition at line 372 of file TargetList.cpp.
References m_target_list, and m_target_list_mutex.
Referenced by CommandObjectTargetDelete::DoExecute().
FindTargetByGloballyUniqueID()
TargetSP TargetList::FindTargetByGloballyUniqueID (lldb::user_id_t id) const
Find the target that has a globally unique ID that matches ID id.
Parameters
[in] id The globally unique target ID to search our target list for.
Returns
A shared pointer to a target object. The returned shared pointer will contain nullptr if no target objects has a matching target ID.
Definition at line 431 of file TargetList.cpp.
References m_target_list, and m_target_list_mutex.
FindTargetWithExecutableAndArchitecture()
TargetSP TargetList::FindTargetWithExecutableAndArchitecture (const FileSpec & exe_file_spec, const ArchSpec * exe_arch_ptr = nullptr) const
Find the target that contains has an executable whose path matches exe_file_spec, and whose architecture matches arch_ptr if arch_ptr is not nullptr.
Parameters
[in] exe_file_spec A file spec containing a basename, or a full path (directory and basename). If exe_file_spec contains only a filename (empty GetDirectory() value) then matching will be done solely based on the filenames and directories won't be compared. If exe_file_spec contains a filename and a directory, then both must match.
[in] exe_arch_ptr If not nullptr then the architecture also needs to match, else the architectures will be compared.
Returns
A shared pointer to a target object. The returned shared pointer will contain nullptr if no target objects have a executable whose full or partial path matches with a matching process ID.
Definition at line 382 of file TargetList.cpp.
References lldb_private::Module::GetArchitecture(), lldb_private::Module::GetFileSpec(), lldb_private::ArchSpec::IsCompatibleMatch(), m_target_list, m_target_list_mutex, and lldb_private::FileSpec::Match().
FindTargetWithProcess()
TargetSP TargetList::FindTargetWithProcess (lldb_private::Process * process) const
Definition at line 415 of file TargetList.cpp.
References m_target_list, and m_target_list_mutex.
FindTargetWithProcessID()
TargetSP TargetList::FindTargetWithProcessID (lldb::pid_t pid) const
Find the target that contains a process with process ID pid.
Parameters
[in] pid The process ID to search our target list for.
Returns
A shared pointer to a target object. The returned shared pointer will contain nullptr if no target objects own a process with a matching process ID.
Definition at line 402 of file TargetList.cpp.
References m_target_list, and m_target_list_mutex.
Referenced by SendAsyncInterrupt(), and SignalIfRunning().
GetBroadcasterClass()
llvm::StringRef lldb_private::TargetList::GetBroadcasterClass () const inline override virtual
This needs to be filled in if you are going to register the broadcaster with the broadcaster manager and do broadcaster class matching.
FIXME: Probably should make a ManagedBroadcaster subclass with all the bits needed to work with the BroadcasterManager, so that it is clearer how to add one.
Reimplemented from lldb_private::Broadcaster.
Definition at line 42 of file TargetList.h.
References GetStaticBroadcasterClass().
GetIndexOfTarget()
uint32_t TargetList::GetIndexOfTarget (lldb::TargetSP target_sp) const
Definition at line 519 of file TargetList.cpp.
References m_target_list, m_target_list_mutex, and UINT32_MAX.
Referenced by lldb_private::Process::HandleProcessStateChangedEvent().
GetNumTargets()
size_t TargetList::GetNumTargets () const
Definition at line 506 of file TargetList.cpp.
References m_target_list, and m_target_list_mutex.
Referenced by CommandObjectTargetDelete::DoExecute(), CommandObjectTargetSelect::DoExecute(), DumpTargetList(), lldb_private::mcp::DebuggerResourceProvider::GetResources(), lldb_private::Target::SetLabel(), and lldb_private::CommandObjectQuit::ShouldAskForConfirmation().
GetSelectedTarget()
lldb::TargetSP TargetList::GetSelectedTarget ()
Definition at line 557 of file TargetList.cpp.
References GetTargetAtIndex(), m_selected_target_idx, m_target_list, and m_target_list_mutex.
Referenced by CommandObjectTargetDelete::DoExecute(), DumpTargetList(), and lldb_private::Process::HandleProcessStateChangedEvent().
GetStaticBroadcasterClass()
llvm::StringRef TargetList::GetStaticBroadcasterClass () static
Definition at line 32 of file TargetList.cpp.
Referenced by GetBroadcasterClass(), and TargetList().
GetTargetAtIndex()
lldb::TargetSP TargetList::GetTargetAtIndex (uint32_t index) const
Definition at line 511 of file TargetList.cpp.
References m_target_list, and m_target_list_mutex.
Referenced by CommandObjectTargetDelete::DoExecute(), CommandObjectTargetSelect::DoExecute(), DumpTargetList(), lldb_private::mcp::DebuggerResourceProvider::GetResources(), GetSelectedTarget(), lldb_private::mcp::DebuggerResourceProvider::ReadTargetResource(), lldb_private::Target::SetLabel(), and lldb_private::CommandObjectQuit::ShouldAskForConfirmation().
GetTargetSP()
TargetSP TargetList::GetTargetSP (Target * target) const
Definition at line 443 of file TargetList.cpp.
References m_target_list, and m_target_list_mutex.
IsTargetInProcess()
bool TargetList::IsTargetInProcess (lldb::TargetSP target_sp) private
Definition at line 592 of file TargetList.cpp.
References m_in_process_target_list, and m_target_list_mutex.
operator=()
const TargetList & lldb_private::TargetList::operator= (const TargetList &) private delete
References TargetList().
RegisterInProcessTarget()
void TargetList::RegisterInProcessTarget (lldb::TargetSP target_sp) private
Definition at line 577 of file TargetList.cpp.
References m_in_process_target_list, and m_target_list_mutex.
SendAsyncInterrupt()
uint32_t TargetList::SendAsyncInterrupt (lldb::pid_t pid = LLDB_INVALID_PROCESS_ID)
Send an async interrupt to one or all processes.
Find the target that contains the process with process ID pid and send a LLDB_EVENT_ASYNC_INTERRUPT event to the process's event queue.
Parameters
[in] pid The process ID to search our target list for, if pid is LLDB_INVALID_PROCESS_ID, then the interrupt will be sent to all processes.
Returns
The number of async interrupts sent.
Definition at line 458 of file TargetList.cpp.
References lldb_private::Broadcaster::BroadcastEvent(), lldb_private::Process::eBroadcastBitInterrupt, FindTargetWithProcessID(), LLDB_INVALID_PROCESS_ID, and lldb_private::Process::SendAsyncInterrupt().
SetSelectedTarget() [1/2]
void lldb_private::TargetList::SetSelectedTarget (const lldb::TargetSP & target)
SetSelectedTarget() [2/2]
void TargetList::SetSelectedTarget (uint32_t index)
Definition at line 542 of file TargetList.cpp.
References m_target_list_mutex, and SetSelectedTargetInternal().
Referenced by CommandObjectTargetSelect::DoExecute().
SetSelectedTargetInternal()
void TargetList::SetSelectedTargetInternal (uint32_t index) private
Definition at line 537 of file TargetList.cpp.
References lldbassert, m_selected_target_idx, and m_target_list.
Referenced by AddTargetInternal(), and SetSelectedTarget().
SignalIfRunning()
uint32_t TargetList::SignalIfRunning (lldb::pid_t pid, int signo)
Definition at line 479 of file TargetList.cpp.
References FindTargetWithProcessID(), lldb_private::Process::IsAlive(), LLDB_INVALID_PROCESS_ID, m_target_list, m_target_list_mutex, and lldb_private::Process::Signal().
Targets()
TargetIterable lldb_private::TargetList::Targets () inline
Definition at line 204 of file TargetList.h.
References m_target_list, and m_target_list_mutex.
Referenced by lldb_private::DebuggerStats::ResetStatistics().
UnregisterInProcessTarget()
void TargetList::UnregisterInProcessTarget (lldb::TargetSP target_sp) private
Definition at line 585 of file TargetList.cpp.
References m_in_process_target_list, and m_target_list_mutex.
Referenced by AddTargetInternal().
Friends And Related Symbol Documentation
Debugger
friend class Debugger friend
Definition at line 23 of file TargetList.h.
References Debugger.
Referenced by CreateTarget(), CreateTarget(), CreateTargetInternal(), CreateTargetInternal(), Debugger, and TargetList().
Member Data Documentation
m_in_process_target_list
std::unordered_set<lldb::TargetSP> lldb_private::TargetList::m_in_process_target_list private
Definition at line 210 of file TargetList.h.
Referenced by AnyTargetContainsModule(), IsTargetInProcess(), RegisterInProcessTarget(), and UnregisterInProcessTarget().
m_selected_target_idx
uint32_t lldb_private::TargetList::m_selected_target_idx private
Definition at line 212 of file TargetList.h.
Referenced by GetSelectedTarget(), SetSelectedTargetInternal(), and TargetList().
m_target_list
collection lldb_private::TargetList::m_target_list private
Definition at line 209 of file TargetList.h.
Referenced by AddTargetInternal(), AnyTargetContainsModule(), DeleteTarget(), FindTargetByGloballyUniqueID(), FindTargetWithExecutableAndArchitecture(), FindTargetWithProcess(), FindTargetWithProcessID(), GetIndexOfTarget(), GetNumTargets(), GetSelectedTarget(), GetTargetAtIndex(), GetTargetSP(), SetSelectedTargetInternal(), SignalIfRunning(), TargetList(), and Targets().
m_target_list_mutex
std::recursive_mutex lldb_private::TargetList::m_target_list_mutex mutable private
Definition at line 211 of file TargetList.h.
Referenced by AddTargetInternal(), AnyTargetContainsModule(), DeleteTarget(), FindTargetByGloballyUniqueID(), FindTargetWithExecutableAndArchitecture(), FindTargetWithProcess(), FindTargetWithProcessID(), GetIndexOfTarget(), GetNumTargets(), GetSelectedTarget(), GetTargetAtIndex(), GetTargetSP(), IsTargetInProcess(), RegisterInProcessTarget(), SetSelectedTarget(), SignalIfRunning(), TargetList(), Targets(), and UnregisterInProcessTarget().
The documentation for this class was generated from the following files:
TargetList.h
TargetList.cpp