LLDB: ABIMacOSX_arm64 Class Reference
ABIMacOSX_arm64 Class Reference
#include <ABIMacOSX_arm64.h>
Public Member Functions
~ABIMacOSX_arm64 () override=default
size_t GetRedZoneSize () const override
bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override
bool GetArgumentValues (lldb_private::Thread &thread, lldb_private::ValueList &values) const override
bool RegisterIsVolatile (const lldb_private::RegisterInfo *reg_info) override
bool CallFrameAddressIsValid (lldb::addr_t cfa) override
bool CodeAddressIsValid (lldb::addr_t pc) override
lldb::addr_t FixCodeAddress (lldb::addr_t pc) override
Some targets might use bits in a code address to indicate a mode switch.
lldb::addr_t FixDataAddress (lldb::addr_t pc) override
llvm::StringRef GetPluginName () override
lldb_private::Status SetReturnValueObject (lldb::StackFrameSP &frame_sp, lldb::ValueObjectSP &new_value) override
Public Member Functions inherited from ABIAArch64
lldb::UnwindPlanSP CreateFunctionEntryUnwindPlan () override
lldb::UnwindPlanSP CreateDefaultUnwindPlan () override
Public Member Functions inherited from lldb_private::MCBasedABI
void AugmentRegisterInfo (std::vector< DynamicRegisterInfo::Register > &regs) override
Public Member Functions inherited from lldb_private::ABI
~ABI () override
virtual bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::Type &prototype, llvm::ArrayRef< CallArgument > args) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, CompilerType &type, bool persistent=true) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, llvm::Type &type, bool persistent=true) const
virtual bool GetFallbackRegisterLocation (const RegisterInfo *reg_info, UnwindPlan::Row::AbstractRegisterLocation &unwind_regloc)
virtual lldb::addr_t FixAnyAddress (lldb::addr_t pc)
Use this method when you do not know, or do not care what kind of address you are fixing.
llvm::MCRegisterInfo & GetMCRegisterInfo ()
virtual bool GetPointerReturnRegister (const char *&name)
virtual uint64_t GetStackFrameSize ()
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static lldb::ABISP CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec &arch)
static llvm::StringRef GetPluginNameStatic ()
Static Public Member Functions inherited from ABIAArch64
static void Initialize ()
static void Terminate ()
Static Public Member Functions inherited from lldb_private::MCBasedABI
static void MapRegisterName (std::string &reg, llvm::StringRef from_prefix, llvm::StringRef to_prefix)
If the register name is of the form "<from_prefix>[<number>]" then change the name to "<to_prefix>[<number>]".
Static Public Member Functions inherited from lldb_private::ABI
static lldb::ABISP FindPlugin (lldb::ProcessSP process_sp, const ArchSpec &arch)
Protected Member Functions
lldb::ValueObjectSP GetReturnValueObjectImpl (lldb_private::Thread &thread, lldb_private::CompilerType &ast_type) const override
Protected Member Functions inherited from ABIAArch64
virtual lldb::addr_t FixAddress (lldb::addr_t pc, lldb::addr_t mask)
std::pair< uint32_t, uint32_t > GetEHAndDWARFNums (llvm::StringRef name) override
Return eh_frame and dwarf numbers for the given register.
std::string GetMCName (std::string reg) override
For the given (capitalized) lldb register name, return the name of this register in the MCRegisterInfo struct.
uint32_t GetGenericNum (llvm::StringRef name) override
Return the generic number of the given register.
void AugmentRegisterInfo (std::vector< lldb_private::DynamicRegisterInfo::Register > &regs) override
Protected Member Functions inherited from lldb_private::MCBasedABI
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Protected Member Functions inherited from lldb_private::ABI
virtual lldb::ValueObjectSP GetReturnValueObjectImpl (Thread &thread, llvm::Type &ir_type) const
lldb::ProcessSP GetProcessSP () const
Request to get a Process shared pointer.
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Additional Inherited Members
Static Protected Member Functions inherited from lldb_private::ABI
static std::unique_ptr< llvm::MCRegisterInfo > MakeMCRegisterInfo (const ArchSpec &arch)
Utility function to construct a MCRegisterInfo using the ArchSpec triple.
Protected Attributes inherited from lldb_private::ABI
lldb::ProcessWP m_process_wp
std::unique_ptr< llvm::MCRegisterInfo > m_mc_register_info_up
Detailed Description
Definition at line 16 of file ABIMacOSX_arm64.h.
Constructor & Destructor Documentation
~ABIMacOSX_arm64()
ABIMacOSX_arm64::~ABIMacOSX_arm64 () override default
References sp.
Member Function Documentation
CallFrameAddressIsValid()
bool ABIMacOSX_arm64::CallFrameAddressIsValid (lldb::addr_t cfa) inline override virtual
Implements lldb_private::ABI.
Definition at line 43 of file ABIMacOSX_arm64.h.
CodeAddressIsValid()
bool ABIMacOSX_arm64::CodeAddressIsValid (lldb::addr_t pc) inline override virtual
Implements lldb_private::ABI.
Definition at line 52 of file ABIMacOSX_arm64.h.
References pc.
CreateInstance()
ABISP ABIMacOSX_arm64::CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec & arch) static
Definition at line 42 of file ABIMacOSX_arm64.cpp.
References lldb_private::ArchSpec::GetTriple(), and lldb_private::ABI::MakeMCRegisterInfo().
Referenced by Initialize(), and Terminate().
FixCodeAddress()
addr_t ABIMacOSX_arm64::FixCodeAddress (lldb::addr_t pc) override virtual
Some targets might use bits in a code address to indicate a mode switch.
ARM uses bit zero to signify a code address is thumb, so any ARM ABI plug-ins would strip those bits.
Reimplemented from ABIAArch64.
Definition at line 785 of file ABIMacOSX_arm64.cpp.
References DoFixAddr(), lldb_private::ABI::GetProcessSP(), and pc.
FixDataAddress()
addr_t ABIMacOSX_arm64::FixDataAddress (lldb::addr_t pc) override virtual
Reimplemented from ABIAArch64.
Definition at line 790 of file ABIMacOSX_arm64.cpp.
References DoFixAddr(), and lldb_private::ABI::GetProcessSP().
GetArgumentValues()
bool ABIMacOSX_arm64::GetArgumentValues (lldb_private::Thread & thread, lldb_private::ValueList & values) const override virtual
Implements lldb_private::ABI.
Definition at line 118 of file ABIMacOSX_arm64.cpp.
References lldb_private::RegisterContext::ConvertRegisterKindToRegisterNumber(), lldb::eRegisterKindGeneric, error(), lldb_private::Process::GetAddressByteSize(), lldb_private::CompilerType::GetBitSize(), lldb_private::Value::GetCompilerType(), lldb_private::ExecutionContext::GetProcessRef(), lldb_private::RegisterContext::GetRegisterInfoAtIndex(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::Value::GetScalar(), lldb_private::RegisterValue::GetScalarValue(), lldb_private::ValueList::GetSize(), lldb_private::RegisterContext::GetSP(), lldb_private::ValueList::GetValueAtIndex(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), lldb_private::CompilerType::IsPointerOrReferenceType(), LLDB_INVALID_REGNUM, LLDB_REGNUM_GENERIC_ARG1, lldb_private::RegisterContext::ReadRegister(), lldb_private::Process::ReadScalarIntegerFromMemory(), lldb_private::RegisterValue::SignExtend(), and sp.
GetPluginName()
llvm::StringRef ABIMacOSX_arm64::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 75 of file ABIMacOSX_arm64.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef ABIMacOSX_arm64::GetPluginNameStatic () inline static
Definition at line 73 of file ABIMacOSX_arm64.h.
Referenced by GetPluginName(), and Initialize().
GetRedZoneSize()
size_t ABIMacOSX_arm64::GetRedZoneSize () const override virtual
Implements lldb_private::ABI.
Definition at line 37 of file ABIMacOSX_arm64.cpp.
GetReturnValueObjectImpl()
ValueObjectSP ABIMacOSX_arm64::GetReturnValueObjectImpl (lldb_private::Thread & thread, lldb_private::CompilerType & ast_type) const override protected virtual
Implements lldb_private::ABI.
Definition at line 577 of file ABIMacOSX_arm64.cpp.
References lldb_private::RegisterInfo::byte_size, lldb_private::ValueObjectConstResult::Create(), error(), lldb_private::Process::GetAddressByteSize(), lldb_private::RegisterValue::GetAsMemoryData(), lldb_private::Process::GetByteOrder(), lldb_private::CompilerType::GetByteSize(), lldb_private::RegisterValue::GetData(), lldb_private::DataExtractor::GetDouble(), lldb_private::DataExtractor::GetFloat(), lldb_private::DataExtractor::GetLongDouble(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::ExecutionContext::GetProcessRef(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::Value::GetScalar(), lldb_private::ExecutionContext::GetTargetPtr(), lldb_private::CompilerType::GetTypeInfo(), LoadValueFromConsecutiveGPRRegisters(), lldb_private::RegisterContext::ReadRegister(), lldb_private::Value::Scalar, lldb_private::Value::SetCompilerType(), lldb_private::Value::SetValueType(), and UINT32_MAX.
Initialize()
void ABIMacOSX_arm64::Initialize () static
Definition at line 795 of file ABIMacOSX_arm64.cpp.
References CreateInstance(), GetPluginNameStatic(), pluginDesc, and lldb_private::PluginManager::RegisterPlugin().
Referenced by ABIAArch64::Initialize().
PrepareTrivialCall()
bool ABIMacOSX_arm64::PrepareTrivialCall (lldb_private::Thread & thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override virtual
Implements lldb_private::ABI.
Definition at line 57 of file ABIMacOSX_arm64.cpp.
References lldb_private::RegisterContext::ConvertRegisterKindToRegisterNumber(), lldb::eRegisterKindGeneric, lldb_private::Expressions, lldb_private::GetLog(), lldb_private::RegisterContext::GetRegisterInfo(), lldb_private::RegisterContext::GetRegisterInfoAtIndex(), lldb_private::StreamString::GetString(), LLDB_LOGF, LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_RA, LLDB_REGNUM_GENERIC_SP, lldb_private::RegisterInfo::name, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), lldb_private::Log::PutString(), sp, and lldb_private::RegisterContext::WriteRegisterFromUnsigned().
RegisterIsVolatile()
bool ABIMacOSX_arm64::RegisterIsVolatile (const lldb_private::RegisterInfo * reg_info) override virtual
Implements lldb_private::ABI.
Definition at line 354 of file ABIMacOSX_arm64.cpp.
References lldb_private::RegisterInfo::name.
SetReturnValueObject()
Status ABIMacOSX_arm64::SetReturnValueObject (lldb::StackFrameSP & frame_sp, lldb::ValueObjectSP & new_value) override virtual
Implements lldb_private::ABI.
Definition at line 237 of file ABIMacOSX_arm64.cpp.
References lldb_private::Status::AsCString(), error(), lldb_private::Status::Fail(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataExtractor::GetMaxU64(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::CompilerType::GetTypeInfo(), lldb_private::RegisterValue::SetValueFromData(), lldb_private::RegisterContext::WriteRegister(), and lldb_private::RegisterContext::WriteRegisterFromUnsigned().
Terminate()
void ABIMacOSX_arm64::Terminate () static
Definition at line 800 of file ABIMacOSX_arm64.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Referenced by ABIAArch64::Terminate().
The documentation for this class was generated from the following files:
ABIMacOSX_arm64.h
ABIMacOSX_arm64.cpp