LLDB: lldb_private::breakpad::FileRecord Class Reference
lldb_private::breakpad::FileRecord Class Reference
#include <BreakpadRecords.h>
Public Member Functions
FileRecord (size_t Number, llvm::StringRef Name)
Public Member Functions inherited from lldb_private::breakpad::Record
Kind getKind ()
Static Public Member Functions
static std::optional< FileRecord > parse (llvm::StringRef Line)
Static Public Member Functions inherited from lldb_private::breakpad::Record
static std::optional< Kind > classify (llvm::StringRef Line)
Attempt to guess the kind of the record present in the argument without doing a full parse.
Public Attributes
size_t Number
llvm::StringRef Name
Additional Inherited Members
Public Types inherited from lldb_private::breakpad::Record
enum Kind {
Module , Info , File , Func ,
Inline , InlineOrigin , Line , Public ,
StackCFI , StackWin
}
Protected Member Functions inherited from lldb_private::breakpad::Record
Record (Kind K)
~Record ()=default
Detailed Description
Definition at line 89 of file BreakpadRecords.h.
Constructor & Destructor Documentation
FileRecord()
lldb_private::breakpad::FileRecord::FileRecord (size_t Number, llvm::StringRef Name) inline
Definition at line 92 of file BreakpadRecords.h.
References lldb_private::breakpad::Record::File, Name, Number, and lldb_private::breakpad::Record::Record().
Member Function Documentation
parse()
std::optional< FileRecord > FileRecord::parse (llvm::StringRef Line) static
Definition at line 248 of file BreakpadRecords.cpp.
References lldb_private::breakpad::Record::Line, and parseNumberName().
Referenced by lldb_private::breakpad::SymbolFileBreakpad::ParseFileRecords().
Member Data Documentation
Name
llvm::StringRef lldb_private::breakpad::FileRecord::Name
Definition at line 96 of file BreakpadRecords.h.
Referenced by FileRecord(), lldb_private::breakpad::operator<<(), and lldb_private::breakpad::operator==().
Number
size_t lldb_private::breakpad::FileRecord::Number
Definition at line 95 of file BreakpadRecords.h.
Referenced by FileRecord(), lldb_private::breakpad::operator<<(), and lldb_private::breakpad::operator==().
The documentation for this class was generated from the following files:
BreakpadRecords.h
BreakpadRecords.cpp