LLDB: lldb::SBUnixSignals Class Reference
lldb::SBUnixSignals Class Reference
#include <SBUnixSignals.h>
Public Member Functions
SBUnixSignals ()
SBUnixSignals (const lldb::SBUnixSignals &rhs)
~SBUnixSignals ()
const SBUnixSignals & operator= (const lldb::SBUnixSignals &rhs)
void Clear ()
operator bool () const
bool IsValid () const
const char * GetSignalAsCString (int32_t signo) const
int32_t GetSignalNumberFromName (const char *name) const
bool GetShouldSuppress (int32_t signo) const
bool SetShouldSuppress (int32_t signo, bool value)
bool GetShouldStop (int32_t signo) const
bool SetShouldStop (int32_t signo, bool value)
bool GetShouldNotify (int32_t signo) const
bool SetShouldNotify (int32_t signo, bool value)
int32_t GetNumSignals () const
int32_t GetSignalAtIndex (int32_t index) const
Protected Member Functions
SBUnixSignals (lldb::ProcessSP &process_sp)
SBUnixSignals (lldb::PlatformSP &platform_sp)
lldb::UnixSignalsSP GetSP () const
void SetSP (const lldb::UnixSignalsSP &signals_sp)
Private Attributes
lldb::UnixSignalsWP m_opaque_wp
Friends
class SBProcess
class SBPlatform
Detailed Description
Definition at line 17 of file SBUnixSignals.h.
Constructor & Destructor Documentation
SBUnixSignals() [1/4]
SBUnixSignals::SBUnixSignals ()
Definition at line 20 of file SBUnixSignals.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by operator=(), SBPlatform, SBUnixSignals(), and ~SBUnixSignals().
SBUnixSignals() [2/4]
SBUnixSignals::SBUnixSignals (const lldb::SBUnixSignals & rhs)
Definition at line 22 of file SBUnixSignals.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_wp, and SBUnixSignals().
~SBUnixSignals()
SBUnixSignals::~SBUnixSignals () default
References Clear(), GetNumSignals(), GetShouldNotify(), GetShouldStop(), GetShouldSuppress(), GetSignalAsCString(), GetSignalAtIndex(), GetSignalNumberFromName(), IsValid(), operator=(), SBUnixSignals(), SetShouldNotify(), SetShouldStop(), and SetShouldSuppress().
SBUnixSignals() [3/4]
SBUnixSignals::SBUnixSignals (lldb::ProcessSP & process_sp) protected
Definition at line 27 of file SBUnixSignals.cpp.
References m_opaque_wp.
SBUnixSignals() [4/4]
lldb::SBUnixSignals::SBUnixSignals (lldb::PlatformSP & platform_sp) protected
References GetSP(), and SetSP().
Member Function Documentation
Clear()
void SBUnixSignals::Clear ()
Definition at line 49 of file SBUnixSignals.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_wp.
Referenced by ~SBUnixSignals().
GetNumSignals()
int32_t SBUnixSignals::GetNumSignals () const
Definition at line 143 of file SBUnixSignals.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBUnixSignals().
GetShouldNotify()
bool SBUnixSignals::GetShouldNotify (int32_t signo) const
Definition at line 123 of file SBUnixSignals.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBUnixSignals().
GetShouldStop()
bool SBUnixSignals::GetShouldStop (int32_t signo) const
Definition at line 103 of file SBUnixSignals.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBUnixSignals().
GetShouldSuppress()
bool SBUnixSignals::GetShouldSuppress (int32_t signo) const
Definition at line 83 of file SBUnixSignals.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBUnixSignals().
GetSignalAsCString()
const char * SBUnixSignals::GetSignalAsCString (int32_t signo) const
Definition at line 65 of file SBUnixSignals.cpp.
References lldb_private::ConstString::GetCString(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBUnixSignals().
GetSignalAtIndex()
int32_t SBUnixSignals::GetSignalAtIndex (int32_t index) const
Definition at line 152 of file SBUnixSignals.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and LLDB_INVALID_SIGNAL_NUMBER.
Referenced by ~SBUnixSignals().
GetSignalNumberFromName()
int32_t SBUnixSignals::GetSignalNumberFromName (const char * name) const
Definition at line 74 of file SBUnixSignals.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and LLDB_INVALID_SIGNAL_NUMBER.
Referenced by ~SBUnixSignals().
GetSP()
UnixSignalsSP SBUnixSignals::GetSP () const protected
Definition at line 43 of file SBUnixSignals.cpp.
References m_opaque_wp.
Referenced by GetNumSignals(), GetShouldNotify(), GetShouldStop(), GetShouldSuppress(), GetSignalAsCString(), GetSignalAtIndex(), GetSignalNumberFromName(), operator bool(), SBUnixSignals(), SetShouldNotify(), SetShouldStop(), and SetShouldSuppress().
IsValid()
bool SBUnixSignals::IsValid () const
Definition at line 55 of file SBUnixSignals.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBUnixSignals().
operator bool()
SBUnixSignals::operator bool () const explicit
Definition at line 59 of file SBUnixSignals.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
operator=()
const SBUnixSignals & SBUnixSignals::operator= (const lldb::SBUnixSignals & rhs)
Definition at line 33 of file SBUnixSignals.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_wp, and SBUnixSignals().
Referenced by ~SBUnixSignals().
SetShouldNotify()
bool SBUnixSignals::SetShouldNotify (int32_t signo, bool value)
Definition at line 132 of file SBUnixSignals.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBUnixSignals().
SetShouldStop()
bool SBUnixSignals::SetShouldStop (int32_t signo, bool value)
Definition at line 112 of file SBUnixSignals.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBUnixSignals().
SetShouldSuppress()
bool SBUnixSignals::SetShouldSuppress (int32_t signo, bool value)
Definition at line 92 of file SBUnixSignals.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBUnixSignals().
SetSP()
void SBUnixSignals::SetSP (const lldb::UnixSignalsSP & signals_sp) protected
Definition at line 45 of file SBUnixSignals.cpp.
References m_opaque_wp.
Referenced by SBUnixSignals().
Friends And Related Symbol Documentation
SBPlatform
friend class SBPlatform friend
Definition at line 55 of file SBUnixSignals.h.
References SBPlatform, and SBUnixSignals().
Referenced by SBPlatform.
SBProcess
friend class SBProcess friend
Definition at line 54 of file SBUnixSignals.h.
References SBProcess.
Referenced by SBProcess.
Member Data Documentation
m_opaque_wp
lldb::UnixSignalsWP lldb::SBUnixSignals::m_opaque_wp private
Definition at line 66 of file SBUnixSignals.h.
Referenced by Clear(), GetSP(), operator=(), SBUnixSignals(), SBUnixSignals(), and SetSP().
The documentation for this class was generated from the following files:
SBUnixSignals.h
SBUnixSignals.cpp