LLDB: lldb_private::SummaryStatisticsCache Class Reference
lldb_private::SummaryStatisticsCache Class Reference
A class that wraps a std::map of SummaryStatistics objects behind a mutex.
#include <Statistics.h>
Public Member Functions
SummaryStatisticsSP GetSummaryStatisticsForProvider (lldb_private::TypeSummaryImpl &provider)
Get the SummaryStatistics object for a given provider name, or insert if statistics for that provider is not in the map.
llvm::json::Value ToJSON ()
void Reset ()
Private Attributes
llvm::StringMap< SummaryStatisticsSP > m_summary_stats_map
std::mutex m_map_mutex
Detailed Description
A class that wraps a std::map of SummaryStatistics objects behind a mutex.
Definition at line 284 of file Statistics.h.
Member Function Documentation
GetSummaryStatisticsForProvider()
SummaryStatisticsSP lldb_private::SummaryStatisticsCache::GetSummaryStatisticsForProvider (lldb_private::TypeSummaryImpl & provider) inline
Get the SummaryStatistics object for a given provider name, or insert if statistics for that provider is not in the map.
Definition at line 289 of file Statistics.h.
References lldb_private::TypeSummaryImpl::GetName(), lldb_private::TypeSummaryImpl::GetSummaryKindName(), m_map_mutex, and m_summary_stats_map.
Reset()
void SummaryStatisticsCache::Reset ()
Definition at line 538 of file Statistics.cpp.
References m_summary_stats_map.
Referenced by lldb_private::TargetStats::Reset().
ToJSON()
json::Value SummaryStatisticsCache::ToJSON ()
Definition at line 529 of file Statistics.cpp.
References m_map_mutex, and m_summary_stats_map.
Referenced by lldb_private::TargetStats::ToJSON().
Member Data Documentation
m_map_mutex
std::mutex lldb_private::SummaryStatisticsCache::m_map_mutex private
Definition at line 308 of file Statistics.h.
Referenced by GetSummaryStatisticsForProvider(), and ToJSON().
m_summary_stats_map
llvm::StringMap<SummaryStatisticsSP> lldb_private::SummaryStatisticsCache::m_summary_stats_map private
Definition at line 307 of file Statistics.h.
Referenced by GetSummaryStatisticsForProvider(), Reset(), and ToJSON().
The documentation for this class was generated from the following files:
Statistics.h
Statistics.cpp