LLDB: OutputWriterJSON Class Reference
OutputWriterJSON Class Reference
Public Member Functions
OutputWriterJSON (Stream &s, const TraceDumperOptions &options)
~OutputWriterJSON ()
void FunctionCallForest (const std::vector< TraceDumper::FunctionCallUP > &forest) override
Dump a function call forest.
void DumpFunctionCallTree (const TraceDumper::FunctionCall &function_call)
void DumpEvent (const TraceDumper::TraceItem &item)
void DumpInstruction (const TraceDumper::TraceItem &item)
void TraceItem (const TraceDumper::TraceItem &item) override
Dump a trace item (instruction, error or event).
Public Member Functions inherited from lldb_private::TraceDumper::OutputWriter
virtual ~OutputWriter ()=default
virtual void NoMoreData ()
Notify this writer that the cursor ran out of data.
Private Attributes
Stream & m_s
TraceDumperOptions m_options
json::OStream m_j
Detailed Description
Definition at line 281 of file TraceDumper.cpp.
Constructor & Destructor Documentation
OutputWriterJSON()
OutputWriterJSON::OutputWriterJSON (Stream & s, const TraceDumperOptions & options) inline
Definition at line 309 of file TraceDumper.cpp.
References m_j, m_options, and m_s.
~OutputWriterJSON()
OutputWriterJSON::~OutputWriterJSON () inline
Definition at line 316 of file TraceDumper.cpp.
References m_j.
Member Function Documentation
DumpEvent()
void OutputWriterJSON::DumpEvent (const TraceDumper::TraceItem & item) inline
Definition at line 355 of file TraceDumper.cpp.
References lldb_private::TraceDumper::TraceItem::cpu_id, lldb::eTraceEventCPUChanged, lldb::eTraceEventDisabledHW, lldb::eTraceEventDisabledSW, lldb::eTraceEventHWClockTick, lldb::eTraceEventSyncPoint, lldb_private::TraceDumper::TraceItem::event, lldb_private::TraceCursor::EventKindToString(), lldb_private::TraceDumper::TraceItem::hw_clock, m_j, and lldb_private::TraceDumper::TraceItem::sync_point_metadata.
Referenced by TraceItem().
DumpFunctionCallTree()
void OutputWriterJSON::DumpFunctionCallTree (const TraceDumper::FunctionCall & function_call) inline
Definition at line 325 of file TraceDumper.cpp.
References DumpFunctionCallTree(), lldb_private::TraceDumper::FunctionCall::GetTracedSegments(), lldb_private::TraceDumper::FunctionCall::GetUntracedPrefixSegment(), and m_j.
Referenced by DumpFunctionCallTree(), and FunctionCallForest().
DumpInstruction()
void OutputWriterJSON::DumpInstruction (const TraceDumper::TraceItem & item) inline
Definition at line 373 of file TraceDumper.cpp.
References GetModuleName(), lldb_private::Instruction::GetNameForInstructionControlFlowKind(), IsLineEntryValid(), lldb_private::TraceDumper::TraceItem::load_address, m_j, m_options, lldb_private::TraceDumper::TraceItem::symbol_info, and ToOptionalString().
Referenced by TraceItem().
FunctionCallForest()
void OutputWriterJSON::FunctionCallForest (const std::vector< TraceDumper::FunctionCallUP > & forest) inline override virtual
Dump a function call forest.
Implements lldb_private::TraceDumper::OutputWriter.
Definition at line 318 of file TraceDumper.cpp.
References DumpFunctionCallTree(), and m_j.
TraceItem()
void OutputWriterJSON::TraceItem (const TraceDumper::TraceItem & item) inline override virtual
Dump a trace item (instruction, error or event).
Implements lldb_private::TraceDumper::OutputWriter.
Definition at line 406 of file TraceDumper.cpp.
References DumpEvent(), DumpInstruction(), lldb_private::TraceDumper::TraceItem::error, lldb_private::TraceDumper::TraceItem::event, lldb_private::TraceDumper::TraceItem::id, m_j, m_options, and lldb_private::TraceDumper::TraceItem::timestamp.
Member Data Documentation
m_j
json::OStream OutputWriterJSON::m_j private
Definition at line 428 of file TraceDumper.cpp.
Referenced by DumpEvent(), DumpFunctionCallTree(), DumpInstruction(), FunctionCallForest(), OutputWriterJSON(), TraceItem(), and ~OutputWriterJSON().
m_options
TraceDumperOptions OutputWriterJSON::m_options private
Definition at line 427 of file TraceDumper.cpp.
Referenced by DumpInstruction(), OutputWriterJSON(), and TraceItem().
m_s
Stream& OutputWriterJSON::m_s private
Definition at line 426 of file TraceDumper.cpp.
Referenced by OutputWriterJSON().
The documentation for this class was generated from the following file:
TraceDumper.cpp