LLDB: ABISysV_msp430 Class Reference
ABISysV_msp430 Class Reference
#include <ABISysV_msp430.h>
Public Member Functions
~ABISysV_msp430 () override=default
size_t GetRedZoneSize () const override
bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override
bool GetArgumentValues (lldb_private::Thread &thread, lldb_private::ValueList &values) const override
lldb_private::Status SetReturnValueObject (lldb::StackFrameSP &frame_sp, lldb::ValueObjectSP &new_value) override
lldb::ValueObjectSP GetReturnValueObjectImpl (lldb_private::Thread &thread, lldb_private::CompilerType &type) const override
lldb::UnwindPlanSP CreateFunctionEntryUnwindPlan () override
lldb::UnwindPlanSP CreateDefaultUnwindPlan () override
bool RegisterIsVolatile (const lldb_private::RegisterInfo *reg_info) override
bool CallFrameAddressIsValid (lldb::addr_t cfa) override
bool CodeAddressIsValid (lldb::addr_t pc) override
const lldb_private::RegisterInfo * GetRegisterInfoArray (uint32_t &count) override
uint64_t GetStackFrameSize () override
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::RegInfoBasedABI
void AugmentRegisterInfo (std::vector< DynamicRegisterInfo::Register > &regs) override
Public Member Functions inherited from lldb_private::ABI
~ABI () override
virtual bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::Type &prototype, llvm::ArrayRef< CallArgument > args) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, CompilerType &type, bool persistent=true) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, llvm::Type &type, bool persistent=true) const
virtual bool GetFallbackRegisterLocation (const RegisterInfo *reg_info, UnwindPlan::Row::AbstractRegisterLocation &unwind_regloc)
virtual lldb::addr_t FixAnyAddress (lldb::addr_t pc)
Use this method when you do not know, or do not care what kind of address you are fixing.
llvm::MCRegisterInfo & GetMCRegisterInfo ()
virtual bool GetPointerReturnRegister (const char *&name)
virtual lldb::addr_t FixCodeAddress (lldb::addr_t pc)
Some targets might use bits in a code address to indicate a mode switch.
virtual lldb::addr_t FixDataAddress (lldb::addr_t pc)
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static lldb::ABISP CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec &arch)
static llvm::StringRef GetPluginNameStatic ()
Static Public Member Functions inherited from lldb_private::ABI
static lldb::ABISP FindPlugin (lldb::ProcessSP process_sp, const ArchSpec &arch)
Protected Member Functions
void CreateRegisterMapIfNeeded ()
lldb::ValueObjectSP GetReturnValueObjectSimple (lldb_private::Thread &thread, lldb_private::CompilerType &ast_type) const
bool RegisterIsCalleeSaved (const lldb_private::RegisterInfo *reg_info)
Protected Member Functions inherited from lldb_private::RegInfoBasedABI
bool GetRegisterInfoByName (llvm::StringRef name, RegisterInfo &info)
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Protected Member Functions inherited from lldb_private::ABI
virtual lldb::ValueObjectSP GetReturnValueObjectImpl (Thread &thread, llvm::Type &ir_type) const
lldb::ProcessSP GetProcessSP () const
Request to get a Process shared pointer.
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Additional Inherited Members
Static Protected Member Functions inherited from lldb_private::ABI
static std::unique_ptr< llvm::MCRegisterInfo > MakeMCRegisterInfo (const ArchSpec &arch)
Utility function to construct a MCRegisterInfo using the ArchSpec triple.
Protected Attributes inherited from lldb_private::ABI
lldb::ProcessWP m_process_wp
std::unique_ptr< llvm::MCRegisterInfo > m_mc_register_info_up
Detailed Description
Definition at line 16 of file ABISysV_msp430.h.
Constructor & Destructor Documentation
~ABISysV_msp430()
ABISysV_msp430::~ABISysV_msp430 () override default
References sp.
Member Function Documentation
CallFrameAddressIsValid()
bool ABISysV_msp430::CallFrameAddressIsValid (lldb::addr_t cfa) inline override virtual
Implements lldb_private::ABI.
Definition at line 44 of file ABISysV_msp430.h.
CodeAddressIsValid()
bool ABISysV_msp430::CodeAddressIsValid (lldb::addr_t pc) inline override virtual
Implements lldb_private::ABI.
Definition at line 52 of file ABISysV_msp430.h.
References pc.
CreateDefaultUnwindPlan()
UnwindPlanSP ABISysV_msp430::CreateDefaultUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 324 of file ABISysV_msp430.cpp.
References dwarf_fp, dwarf_pc, dwarf_sp, lldb_private::eLazyBoolNo, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), lldb_private::UnwindPlan::Row::SetRegisterLocationToAtCFAPlusOffset(), lldb_private::UnwindPlan::Row::SetRegisterLocationToIsCFAPlusOffset(), and lldb_private::UnwindPlan::Row::SetRegisterLocationToUnspecified().
CreateFunctionEntryUnwindPlan()
UnwindPlanSP ABISysV_msp430::CreateFunctionEntryUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 308 of file ABISysV_msp430.cpp.
References dwarf_pc, dwarf_sp, lldb_private::eLazyBoolNo, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), lldb_private::UnwindPlan::Row::SetRegisterLocationToAtCFAPlusOffset(), and lldb_private::UnwindPlan::Row::SetRegisterLocationToIsCFAPlusOffset().
CreateInstance()
ABISP ABISysV_msp430::CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec & arch) static
Definition at line 269 of file ABISysV_msp430.cpp.
References lldb_private::ArchSpec::GetTriple(), and lldb_private::ABI::MakeMCRegisterInfo().
Referenced by Initialize(), and Terminate().
CreateRegisterMapIfNeeded()
void ABISysV_msp430::CreateRegisterMapIfNeeded () protected
GetArgumentValues()
bool ABISysV_msp430::GetArgumentValues (lldb_private::Thread & thread, lldb_private::ValueList & values) const override virtual
Implements lldb_private::ABI.
Definition at line 285 of file ABISysV_msp430.cpp.
GetPluginName()
llvm::StringRef ABISysV_msp430::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 74 of file ABISysV_msp430.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef ABISysV_msp430::GetPluginNameStatic () inline static
Definition at line 70 of file ABISysV_msp430.h.
Referenced by GetPluginName(), and Initialize().
GetRedZoneSize()
size_t ABISysV_msp430::GetRedZoneSize () const override virtual
Implements lldb_private::ABI.
Definition at line 262 of file ABISysV_msp430.cpp.
GetRegisterInfoArray()
const lldb_private::RegisterInfo * ABISysV_msp430::GetRegisterInfoArray (uint32_t & count) override virtual
Implements lldb_private::RegInfoBasedABI.
Definition at line 254 of file ABISysV_msp430.cpp.
References g_register_infos, and k_num_register_infos.
GetReturnValueObjectImpl()
ValueObjectSP ABISysV_msp430::GetReturnValueObjectImpl (lldb_private::Thread & thread, lldb_private::CompilerType & type) const override virtual
Implements lldb_private::ABI.
Definition at line 301 of file ABISysV_msp430.cpp.
GetReturnValueObjectSimple()
ValueObjectSP ABISysV_msp430::GetReturnValueObjectSimple (lldb_private::Thread & thread, lldb_private::CompilerType & ast_type) const protected
Definition at line 295 of file ABISysV_msp430.cpp.
GetStackFrameSize()
uint64_t ABISysV_msp430::GetStackFrameSize () inline override virtual
Reimplemented from lldb_private::ABI.
Definition at line 57 of file ABISysV_msp430.h.
Initialize()
void ABISysV_msp430::Initialize (void) static
Definition at line 354 of file ABISysV_msp430.cpp.
References CreateInstance(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
PrepareTrivialCall()
bool ABISysV_msp430::PrepareTrivialCall (lldb_private::Thread & thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override virtual
Implements lldb_private::ABI.
Definition at line 278 of file ABISysV_msp430.cpp.
References pc, ra, and sp.
RegisterIsCalleeSaved()
bool ABISysV_msp430::RegisterIsCalleeSaved (const lldb_private::RegisterInfo * reg_info) protected
Definition at line 347 of file ABISysV_msp430.cpp.
References lldb_private::RegisterInfo::byte_offset.
Referenced by RegisterIsVolatile().
RegisterIsVolatile()
bool ABISysV_msp430::RegisterIsVolatile (const lldb_private::RegisterInfo * reg_info) override virtual
Implements lldb_private::ABI.
Definition at line 343 of file ABISysV_msp430.cpp.
References RegisterIsCalleeSaved().
SetReturnValueObject()
Status ABISysV_msp430::SetReturnValueObject (lldb::StackFrameSP & frame_sp, lldb::ValueObjectSP & new_value) override virtual
Implements lldb_private::ABI.
Definition at line 290 of file ABISysV_msp430.cpp.
References lldb_private::Status.
Terminate()
void ABISysV_msp430::Terminate (void) static
Definition at line 359 of file ABISysV_msp430.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
The documentation for this class was generated from the following files:
ABISysV_msp430.h
ABISysV_msp430.cpp