LLDB: lldb_private::PluginInterface Class Reference
lldb_private::PluginInterface Class Reference abstract
#include <PluginInterface.h>
Public Member Functions
PluginInterface ()=default
virtual ~PluginInterface ()=default
virtual llvm::StringRef GetPluginName ()=0
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Detailed Description
Definition at line 16 of file PluginInterface.h.
Constructor & Destructor Documentation
PluginInterface() [1/2]
lldb_private::PluginInterface::PluginInterface () default
Referenced by operator=(), PluginInterface(), and lldb_private::StructuredDataPlugin::StructuredDataPlugin().
~PluginInterface()
virtual lldb_private::PluginInterface::~PluginInterface () virtual default
PluginInterface() [2/2]
lldb_private::PluginInterface::PluginInterface (const PluginInterface &) delete
References PluginInterface().
Member Function Documentation
GetPluginName()
virtual llvm::StringRef lldb_private::PluginInterface::GetPluginName () pure virtual
Implemented in ABIMacOSX_arm64, ABIMacOSX_arm, ABIMacOSX_i386, ABISysV_arc, ABISysV_arm64, ABISysV_arm, ABISysV_hexagon, ABISysV_i386, ABISysV_loongarch, ABISysV_mips64, ABISysV_mips, ABISysV_msp430, ABISysV_ppc64, ABISysV_ppc, ABISysV_riscv, ABISysV_s390x, ABISysV_x86_64, ABIWindows_x86_64, DisassemblerLLVMC, DynamicLoaderDarwinKernel, DynamicLoaderFreeBSDKernel, DynamicLoaderHexagonDYLD, DynamicLoaderMacOS, DynamicLoaderMacOSXDYLD, DynamicLoaderPOSIXDYLD, DynamicLoaderStatic, EmulateInstructionARM64, EmulateInstructionMIPS64, EmulateInstructionMIPS, InstrumentationRuntimeASanLibsanitizers, JITLoaderGDB, lldb_private::AppleObjCRuntimeV1, lldb_private::AppleObjCRuntimeV2, lldb_private::ArchitectureAArch64, lldb_private::ArchitectureArm, lldb_private::ArchitectureMips, lldb_private::ArchitecturePPC64, lldb_private::breakpad::ObjectFileBreakpad, lldb_private::breakpad::SymbolFileBreakpad, lldb_private::ClangHighlighter, lldb_private::CPlusPlusLanguage, lldb_private::ctf::TraceExporterCTF, lldb_private::DefaultHighlighter, lldb_private::DynamicLoaderWindowsDYLD, lldb_private::EmulateInstructionARM, lldb_private::EmulateInstructionLoongArch, lldb_private::EmulateInstructionPPC64, lldb_private::EmulateInstructionRISCV, lldb_private::GNUstepObjCRuntime, lldb_private::InstrumentationRuntimeASan, lldb_private::InstrumentationRuntimeBoundsSafety, lldb_private::InstrumentationRuntimeMainThreadChecker, lldb_private::InstrumentationRuntimeTSan, lldb_private::InstrumentationRuntimeUBSan, lldb_private::ItaniumABILanguageRuntime, lldb_private::mcp::ProtocolServerMCP, lldb_private::MemoryHistoryASan, lldb_private::minidump::ProcessMinidump, lldb_private::npdb::SymbolFileNativePDB, lldb_private::ObjCLanguage, lldb_private::ObjCPlusPlusLanguage, lldb_private::ObjectContainerMachOFileset, lldb_private::ObjectFileJIT, lldb_private::ObjectFileJSON, lldb_private::ObjectFilePDB, lldb_private::OperatingSystemPythonInterface, lldb_private::platform_aix::PlatformAIX, lldb_private::platform_android::PlatformAndroid, lldb_private::platform_freebsd::PlatformFreeBSD, lldb_private::platform_gdb_server::PlatformRemoteGDBServer, lldb_private::platform_linux::PlatformLinux, lldb_private::platform_netbsd::PlatformNetBSD, lldb_private::platform_openbsd::PlatformOpenBSD, lldb_private::PlatformAppleSimulator, lldb_private::PlatformMacOSX, lldb_private::PlatformQemuUser, lldb_private::PlatformRemoteAppleBridge, lldb_private::PlatformRemoteAppleTV, lldb_private::PlatformRemoteAppleWatch, lldb_private::PlatformRemoteAppleXR, lldb_private::PlatformRemoteiOS, lldb_private::PlatformRemoteMacOSX, lldb_private::PlatformWasm, lldb_private::PlatformWindows, lldb_private::plugin::dwarf::SymbolFileDWARF, lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap, lldb_private::process_gdb_remote::ProcessGDBRemote, lldb_private::ProcessTrace, lldb_private::ProcessWindows, lldb_private::RegisterTypeBuilderClang, lldb_private::RustTreeSitterHighlighter, lldb_private::ScriptedBreakpointPythonInterface, lldb_private::ScriptedFrameProvider, lldb_private::ScriptedFrameProviderPythonInterface, lldb_private::ScriptedPlatformPythonInterface, lldb_private::ScriptedProcess, lldb_private::ScriptedProcessPythonInterface, lldb_private::ScriptedStopHookPythonInterface, lldb_private::ScriptedThreadPlanPythonInterface, lldb_private::ScriptInterpreterLua, lldb_private::ScriptInterpreterNone, lldb_private::ScriptInterpreterPythonImpl, lldb_private::StructuredDataDarwinLog, lldb_private::SwiftTreeSitterHighlighter, lldb_private::SymbolFileCTF, lldb_private::SymbolFileJSON, lldb_private::SymbolFileOnDemand, lldb_private::SymbolLocatorDebuginfod, lldb_private::SymbolLocatorDebugSymbols, lldb_private::SymbolLocatorDefault, lldb_private::SymbolVendor, lldb_private::trace_intel_pt::TraceIntelPT, lldb_private::TypeSystemClang, lldb_private::wasm::DynamicLoaderWasmDYLD, lldb_private::wasm::ObjectFileWasm, lldb_private::wasm::ProcessWasm, lldb_private::wasm::SymbolVendorWasm, ObjectContainerBigArchive, ObjectContainerBSDArchive, ObjectContainerUniversalMachO, ObjectFileCOFF, ObjectFileELF, ObjectFileMachO, ObjectFileMinidump, ObjectFilePECOFF, ObjectFilePlaceholder, ObjectFileXCOFF, ProcessElfCore, ProcessFreeBSDKernelCore, ProcessKDP, ProcessMachCore, SymbolFilePDB, SymbolFileSymtab, SymbolVendorELF, SymbolVendorMacOSX, SymbolVendorPECOFF, SystemRuntimeMacOSX, UnwindAssembly_x86, and UnwindAssemblyInstEmulation.
Referenced by lldb_private::Process::CompleteAttach(), lldb_private::Platform::ConnectRemote(), PlatformPOSIX::ConnectRemote(), lldb_private::Process::DisableBreakpointSite(), lldb_private::Platform::DisconnectRemote(), PlatformPOSIX::DisconnectRemote(), lldb_private::Process::DoAllocateMemory(), lldb_private::Process::DoAttachToProcessWithID(), lldb_private::Process::DoDeallocateMemory(), lldb_private::Process::DoDetach(), lldb_private::Process::DoHalt(), lldb_private::Process::DoLaunch(), lldb_private::Process::DoLoadCore(), lldb_private::Process::DoReadMemoryTags(), lldb_private::Process::DoResume(), lldb_private::Process::DoSignal(), lldb_private::Process::DoWriteMemory(), lldb_private::Process::DoWriteMemoryTags(), lldb_private::SymbolFileCommon::Dump(), lldb_private::Process::EnableBreakpointSite(), lldb_private::Platform::GetFilePermissions(), lldb_private::Trace::GetLiveCpuBinaryData(), lldb_private::Trace::GetLiveProcessBinaryData(), lldb_private::Trace::GetLiveProcessState(), lldb_private::Trace::GetLiveThreadBinaryData(), lldb_private::Platform::GetModuleCacheRoot(), lldb_private::Platform::GetName(), lldb_private::PlatformDarwin::GetOSVersion(), lldb_private::Platform::GetStatus(), lldb_private::PlatformRemoteDarwinDevice::GetSymbolFile(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetSymbolFileAsSymbolFileDWARF(), ProcessMachCore::LoadBinariesViaMetadata(), lldb_private::Platform::MakeDirectory(), lldb_private::Platform::ReadFile(), lldb_private::Platform::ResolveExecutable(), lldb_private::Process::Resume(), lldb_private::Process::SetExitStatus(), lldb_private::Platform::SetFilePermissions(), lldb_private::Process::SetPrivateState(), lldb_private::Process::SetPublicState(), lldb_private::Trace::Stop(), lldb_private::Trace::Stop(), and lldb_private::Platform::WriteFile().
operator=()
PluginInterface & lldb_private::PluginInterface::operator= (const PluginInterface &) delete
References PluginInterface().
The documentation for this class was generated from the following file:
PluginInterface.h