LLDB: CommandObjectBreakpointAddAddress::CommandOptions Class Reference
CommandObjectBreakpointAddAddress::CommandOptions Class Reference
Public Member Functions
CommandOptions ()=default
~CommandOptions () override=default
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext *execution_context) override
void OptionParsingStarting (ExecutionContext *execution_context) override
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Public Attributes
bool m_hardware = false
FileSpecList m_modules
Detailed Description
Definition at line 411 of file CommandObjectBreakpoint.cpp.
Constructor & Destructor Documentation
CommandOptions()
CommandObjectBreakpointAddAddress::CommandOptions::CommandOptions () default
~CommandOptions()
CommandObjectBreakpointAddAddress::CommandOptions::~CommandOptions () override default
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > CommandObjectBreakpointAddAddress::CommandOptions::GetDefinitions () inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 450 of file CommandObjectBreakpoint.cpp.
Referenced by SetOptionValue().
OptionParsingStarting()
void CommandObjectBreakpointAddAddress::CommandOptions::OptionParsingStarting (ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 445 of file CommandObjectBreakpoint.cpp.
References m_hardware, and m_modules.
SetOptionValue()
Status CommandObjectBreakpointAddAddress::CommandOptions::SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 417 of file CommandObjectBreakpoint.cpp.
References lldb_private::CreateOptionParsingError(), error(), lldb_private::Status::FromError(), GetDefinitions(), m_hardware, and m_modules.
Member Data Documentation
m_hardware
bool CommandObjectBreakpointAddAddress::CommandOptions::m_hardware = false
Definition at line 455 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_modules
FileSpecList CommandObjectBreakpointAddAddress::CommandOptions::m_modules
Definition at line 456 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following file:
CommandObjectBreakpoint.cpp