LLDB: CFCReleaser< T > Class Template Reference
CFCReleaser< T > Class Template Reference
#include <CFCReleaser.h>
Public Member Functions
CFCReleaser (T ptr=NULL)
CFCReleaser (const CFCReleaser &rhs)
virtual ~CFCReleaser ()
CFCReleaser & operator= (const CFCReleaser< T > &rhs)
T * ptr_address (bool enforce_null=true)
T get ()
const T get () const
void reset (T ptr=NULL)
T release ()
Private Attributes
T _ptr
Detailed Description
template<class T>
class CFCReleaser< T >
Definition at line 24 of file CFCReleaser.h.
Constructor & Destructor Documentation
CFCReleaser() [1/2]
template<class T> CFCReleaser< T >::CFCReleaser (T ptr = NULL) inline
Definition at line 28 of file CFCReleaser.h.
References _ptr.
Referenced by CFCReleaser(), and operator=().
CFCReleaser() [2/2]
template<class T> CFCReleaser< T >::CFCReleaser (const CFCReleaser< T > & rhs) inline
Definition at line 36 of file CFCReleaser.h.
References _ptr, CFCReleaser(), and get().
~CFCReleaser()
template<class T> virtual CFCReleaser< T >::~CFCReleaser () inline virtual
Definition at line 43 of file CFCReleaser.h.
References reset().
Member Function Documentation
get() [1/2]
template<class T> T CFCReleaser< T >::get () inline
Definition at line 80 of file CFCReleaser.h.
References _ptr.
Referenced by CFCMutableDictionary::AddValueCString(), CFCMutableDictionary::AddValueDouble(), CFCMutableDictionary::AddValueSInt16(), CFCMutableDictionary::AddValueSInt32(), CFCMutableDictionary::AddValueSInt64(), CFCMutableDictionary::AddValueSInt8(), CFCMutableDictionary::AddValueUInt16(), CFCMutableDictionary::AddValueUInt32(), CFCMutableDictionary::AddValueUInt64(), CFCMutableDictionary::AddValueUInt8(), CFCMutableArray::AppendCStringAsCFString(), CFCMutableArray::AppendFileSystemRepresentationAsCFString(), CFCReleaser(), lldb_private::SymbolLocatorDebugSymbols::DownloadObjectAndSymbolFile(), CFCBundle::GetPath(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableObjectFile(), LocateMacOSXFilesUsingDebugSymbols(), lldb_private::Host::OpenURL(), operator=(), CFCData::Serialize(), CFCBundle::SetPath(), CFCMutableDictionary::SetValueCString(), CFCMutableDictionary::SetValueDouble(), CFCMutableDictionary::SetValueSInt16(), CFCMutableDictionary::SetValueSInt32(), CFCMutableDictionary::SetValueSInt64(), CFCMutableDictionary::SetValueSInt8(), CFCMutableDictionary::SetValueUInt16(), CFCMutableDictionary::SetValueUInt32(), CFCMutableDictionary::SetValueUInt64(), and CFCMutableDictionary::SetValueUInt8().
get() [2/2]
template<class T> const T CFCReleaser< T >::get () const inline
Definition at line 82 of file CFCReleaser.h.
References _ptr.
operator=()
template<class T> CFCReleaser & CFCReleaser< T >::operator= (const CFCReleaser< T > & rhs) inline
Definition at line 51 of file CFCReleaser.h.
References CFCReleaser(), get(), and reset().
ptr_address()
template<class T> T * CFCReleaser< T >::ptr_address (bool enforce_null = true) inline
Definition at line 73 of file CFCReleaser.h.
References _ptr.
release()
template<class T> T CFCReleaser< T >::release () inline
Definition at line 96 of file CFCReleaser.h.
References _ptr.
reset()
template<class T> void CFCReleaser< T >::reset (T ptr = NULL) inline
Definition at line 86 of file CFCReleaser.h.
References _ptr.
Referenced by lldb_private::SymbolLocatorDebugSymbols::LocateExecutableObjectFile(), LocateMacOSXFilesUsingDebugSymbols(), operator=(), and ~CFCReleaser().
Member Data Documentation
_ptr
template<class T> T CFCReleaser< T >::_ptr private
Definition at line 103 of file CFCReleaser.h.
Referenced by CFCReleaser(), CFCReleaser(), get(), get(), ptr_address(), release(), and reset().
The documentation for this class was generated from the following file:
CFCReleaser.h