LLDB: lldb_private::ObjectContainer Class Reference
lldb_private::ObjectContainer Class Reference abstract
A plug-in interface definition class for object containers.
#include "lldb/Symbol/ObjectContainer.h"
Public Member Functions
ObjectContainer (const lldb::ModuleSP &module_sp, const FileSpec *file, lldb::offset_t file_offset, lldb::offset_t length, lldb::DataBufferSP data_sp, lldb::offset_t data_offset)
Construct with a parent module, offset, and header data.
~ObjectContainer () override=default
Destructor.
virtual bool GetArchitectureAtIndex (uint32_t idx, ArchSpec &arch) const
Gets the architecture given an index.
virtual lldb::addr_t GetOffset () const
Returns the offset into a file at which this object resides.
virtual lldb::addr_t GetByteSize () const
virtual size_t GetNumObjects () const
Get the number of objects within this object file (archives).
virtual size_t GetNumArchitectures () const
Get the number of architectures in this object file.
virtual bool ParseHeader ()=0
Attempts to parse the object header.
virtual lldb::ObjectFileSP GetObjectFile (const FileSpec *file)=0
Selects an architecture in an object file.
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
virtual llvm::StringRef GetPluginName ()=0
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Public Member Functions inherited from lldb_private::ModuleChild
ModuleChild (const lldb::ModuleSP &module_sp)
Construct with owning module.
~ModuleChild ()
Destructor.
const ModuleChild & operator= (const ModuleChild &rhs)
Assignment operator.
lldb::ModuleSP GetModule () const
Get const accessor for the module pointer.
void SetModule (const lldb::ModuleSP &module_sp)
Set accessor for the module pointer.
Static Public Member Functions
static lldb::ObjectContainerSP FindPlugin (const lldb::ModuleSP &module_sp, const lldb::ProcessSP &process_sp, lldb::addr_t header_addr, lldb::WritableDataBufferSP file_data_sp)
Protected Attributes
FileSpec m_file
The file that represents this container objects (which can be different from the module's file).
lldb::addr_t m_offset
The offset in bytes into the file, or the address in memory.
lldb::addr_t m_length
The size in bytes if known (can be zero).
lldb::DataExtractorSP m_extractor_sp
The data for this object file so things can be parsed lazily.
Protected Attributes inherited from lldb_private::ModuleChild
lldb::ModuleWP m_module_wp
The Module that owns the object that inherits from this class.
Private Member Functions
ObjectContainer (const ObjectContainer &)=delete
const ObjectContainer & operator= (const ObjectContainer &)=delete
Detailed Description
A plug-in interface definition class for object containers.
Object containers contain object files from one or more architectures, and also can contain one or more named objects.
Typical object containers are static libraries (.a files) that contain multiple named object files, and universal files that contain multiple architectures.
Definition at line 30 of file ObjectContainer.h.
Constructor & Destructor Documentation
ObjectContainer() [1/2]
ObjectContainer::ObjectContainer (const lldb::ModuleSP & module_sp, const FileSpec * file, lldb::offset_t file_offset, lldb::offset_t length, lldb::DataBufferSP data_sp, lldb::offset_t data_offset)
Construct with a parent module, offset, and header data.
Object files belong to modules and a valid module must be supplied upon construction. The at an offset within a file for objects that contain more than one architecture or object.
Definition at line 18 of file ObjectContainer.cpp.
References m_extractor_sp, m_file, m_length, m_offset, and lldb_private::ModuleChild::ModuleChild().
Referenced by lldb_private::ObjectContainerMachOFileset::CreateInstance(), ObjectContainerBigArchive::CreateInstance(), ObjectContainerBSDArchive::CreateInstance(), ObjectContainerUniversalMachO::CreateInstance(), lldb_private::ObjectContainerMachOFileset::CreateMemoryInstance(), ObjectContainer(), ObjectContainerBigArchive::ObjectContainerBigArchive(), ObjectContainerBSDArchive::ObjectContainerBSDArchive(), lldb_private::ObjectContainerMachOFileset::ObjectContainerMachOFileset(), lldb_private::ObjectContainerMachOFileset::ObjectContainerMachOFileset(), ObjectContainerUniversalMachO::ObjectContainerUniversalMachO(), and operator=().
~ObjectContainer()
lldb_private::ObjectContainer::~ObjectContainer () override default
Destructor.
The destructor is virtual since this class is designed to be inherited from by the plug-in instance.
ObjectContainer() [2/2]
lldb_private::ObjectContainer::ObjectContainer (const ObjectContainer &) private delete
References ObjectContainer().
Member Function Documentation
FindPlugin()
ObjectContainerSP ObjectContainer::FindPlugin (const lldb::ModuleSP & module_sp, const lldb::ProcessSP & process_sp, lldb::addr_t header_addr, lldb::WritableDataBufferSP file_data_sp) static
Definition at line 35 of file ObjectContainer.cpp.
References lldb_private::PluginManager::GetObjectContainerCreateMemoryCallbackAtIndex(), and LLDB_SCOPED_TIMERF.
GetArchitectureAtIndex()
virtual bool lldb_private::ObjectContainer::GetArchitectureAtIndex (uint32_t idx, ArchSpec & arch) const inline virtual
Gets the architecture given an index.
Copies the architecture specification for index idx.
Parameters
[in] idx The architecture index to extract.
[out] arch A architecture object that will be filled in if idx is a architecture valid index.
Returns
Returns true if idx is valid and arch has been filled in, false otherwise.
See also
ObjectContainer::GetNumArchitectures() const
Reimplemented in ObjectContainerUniversalMachO.
Definition at line 63 of file ObjectContainer.h.
GetByteSize()
virtual lldb::addr_t lldb_private::ObjectContainer::GetByteSize () const inline virtual
Definition at line 77 of file ObjectContainer.h.
References m_length.
Referenced by lldb_private::ObjectContainerMachOFileset::ObjectContainerMachOFileset().
GetNumArchitectures()
virtual size_t lldb_private::ObjectContainer::GetNumArchitectures () const inline virtual
Get the number of architectures in this object file.
The default implementation returns 1 as for object files that contain a single architecture. ObjectContainer instances that contain more than one architecture should override this function and return an appropriate value.
Returns
The number of architectures contained in this object file.
Reimplemented in ObjectContainerUniversalMachO.
Definition at line 95 of file ObjectContainer.h.
GetNumObjects()
virtual size_t lldb_private::ObjectContainer::GetNumObjects () const inline virtual
Get the number of objects within this object file (archives).
Returns
Zero for object files that are not archives, or the number of objects contained in the archive.
Reimplemented in lldb_private::ObjectContainerMachOFileset, ObjectContainerBigArchive, and ObjectContainerBSDArchive.
Definition at line 84 of file ObjectContainer.h.
GetObjectFile()
virtual lldb::ObjectFileSP lldb_private::ObjectContainer::GetObjectFile (const FileSpec * file) pure virtual
Selects an architecture in an object file.
Object files that contain a single architecture should verify that the specified arch matches the architecture in the object file and return true or false accordingly.
Object files that contain more than one architecture should attempt to select that architecture, and if successful, clear out any previous state from any previously selected architecture and prepare to return information for the new architecture.
Returns
Returns a pointer to the object file of the requested arch and optional name. Returns nullptr of no such object file exists in the container.
Implemented in lldb_private::ObjectContainerMachOFileset, ObjectContainerBigArchive, ObjectContainerBSDArchive, and ObjectContainerUniversalMachO.
GetOffset()
virtual lldb::addr_t lldb_private::ObjectContainer::GetOffset () const inline virtual
Returns the offset into a file at which this object resides.
Some files contain many object files, and this function allows access to an object's offset within the file.
Returns
The offset in bytes into the file. Defaults to zero for simple object files that a represented by an entire file.
Definition at line 75 of file ObjectContainer.h.
References m_offset.
Referenced by ObjectContainerUniversalMachO::GetObjectFile().
operator=()
const ObjectContainer & lldb_private::ObjectContainer::operator= (const ObjectContainer &) private delete
References ObjectContainer().
ParseHeader()
virtual bool lldb_private::ObjectContainer::ParseHeader () pure virtual
Attempts to parse the object header.
This function is used as a test to see if a given plug-in instance can parse the header data already contained in ObjectContainer::m_extractor_sp. If an object file parser does not recognize that magic bytes in a header, false should be returned and the next plug-in can attempt to parse an object file.
Returns
Returns true if the header was parsed successfully, false otherwise.
Implemented in lldb_private::ObjectContainerMachOFileset, ObjectContainerBigArchive, ObjectContainerBSDArchive, and ObjectContainerUniversalMachO.
Member Data Documentation
m_extractor_sp
lldb::DataExtractorSP lldb_private::ObjectContainer::m_extractor_sp protected
The data for this object file so things can be parsed lazily.
Definition at line 143 of file ObjectContainer.h.
Referenced by lldb_private::ObjectContainerMachOFileset::GetObjectFile(), ObjectContainer(), lldb_private::ObjectContainerMachOFileset::ParseHeader(), ObjectContainerBSDArchive::ParseHeader(), and ObjectContainerUniversalMachO::ParseHeader().
m_file
FileSpec lldb_private::ObjectContainer::m_file protected
The file that represents this container objects (which can be different from the module's file).
Definition at line 134 of file ObjectContainer.h.
Referenced by ObjectContainerBSDArchive::GetObjectFile(), ObjectContainer(), lldb_private::ObjectContainerMachOFileset::ParseHeader(), and ObjectContainerBSDArchive::ParseHeader().
m_length
lldb::addr_t lldb_private::ObjectContainer::m_length protected
The size in bytes if known (can be zero).
Definition at line 140 of file ObjectContainer.h.
Referenced by GetByteSize(), and ObjectContainer().
m_offset
lldb::addr_t lldb_private::ObjectContainer::m_offset protected
The offset in bytes into the file, or the address in memory.
Definition at line 137 of file ObjectContainer.h.
Referenced by lldb_private::ObjectContainerMachOFileset::GetObjectFile(), ObjectContainerBSDArchive::GetObjectFile(), ObjectContainerUniversalMachO::GetObjectFile(), GetOffset(), ObjectContainer(), lldb_private::ObjectContainerMachOFileset::ParseHeader(), and ObjectContainerBSDArchive::ParseHeader().
The documentation for this class was generated from the following files:
ObjectContainer.h
ObjectContainer.cpp