LLDB: lldb::SBExecutionContext Class Reference
lldb::SBExecutionContext Class Reference
#include <SBExecutionContext.h>
Public Member Functions
SBExecutionContext ()
SBExecutionContext (const lldb::SBExecutionContext &rhs)
SBExecutionContext (const lldb::SBTarget &target)
SBExecutionContext (const lldb::SBProcess &process)
SBExecutionContext (lldb::SBThread thread)
SBExecutionContext (const lldb::SBFrame &frame)
~SBExecutionContext ()
const SBExecutionContext & operator= (const lldb::SBExecutionContext &rhs)
SBTarget GetTarget () const
SBProcess GetProcess () const
SBThread GetThread () const
SBFrame GetFrame () const
Protected Member Functions
lldb_private::ExecutionContextRef * get () const
SBExecutionContext (lldb::ExecutionContextRefSP exe_ctx_ref_sp)
Private Attributes
lldb::ExecutionContextRefSP m_exe_ctx_sp
Friends
class SBCommandInterpreter
class SBInstructionList
class lldb_private::python::SWIGBridge
class lldb_private::ScriptInterpreter
Detailed Description
Definition at line 27 of file SBExecutionContext.h.
Constructor & Destructor Documentation
SBExecutionContext() [1/7]
SBExecutionContext::SBExecutionContext ()
Definition at line 22 of file SBExecutionContext.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb_private::ScriptInterpreter, operator=(), SBCommandInterpreter, and ~SBExecutionContext().
SBExecutionContext() [2/7]
SBExecutionContext::SBExecutionContext (const lldb::SBExecutionContext & rhs)
Definition at line 24 of file SBExecutionContext.cpp.
References LLDB_INSTRUMENT_VA, and m_exe_ctx_sp.
SBExecutionContext() [3/7]
SBExecutionContext::SBExecutionContext (const lldb::SBTarget & target)
Definition at line 35 of file SBExecutionContext.cpp.
References lldb::SBTarget::GetSP(), LLDB_INSTRUMENT_VA, and m_exe_ctx_sp.
SBExecutionContext() [4/7]
SBExecutionContext::SBExecutionContext (const lldb::SBProcess & process)
Definition at line 42 of file SBExecutionContext.cpp.
References lldb::SBProcess::GetSP(), LLDB_INSTRUMENT_VA, and m_exe_ctx_sp.
SBExecutionContext() [5/7]
SBExecutionContext::SBExecutionContext (lldb::SBThread thread)
Definition at line 49 of file SBExecutionContext.cpp.
References LLDB_INSTRUMENT_VA, and m_exe_ctx_sp.
SBExecutionContext() [6/7]
SBExecutionContext::SBExecutionContext (const lldb::SBFrame & frame)
Definition at line 56 of file SBExecutionContext.cpp.
References lldb::SBFrame::GetFrameSP(), LLDB_INSTRUMENT_VA, and m_exe_ctx_sp.
~SBExecutionContext()
SBExecutionContext::~SBExecutionContext () default
References GetFrame(), GetProcess(), GetTarget(), GetThread(), operator=(), and SBExecutionContext().
SBExecutionContext() [7/7]
SBExecutionContext::SBExecutionContext (lldb::ExecutionContextRefSP exe_ctx_ref_sp) protected
Definition at line 29 of file SBExecutionContext.cpp.
References LLDB_INSTRUMENT_VA, and m_exe_ctx_sp.
Member Function Documentation
get()
ExecutionContextRef * SBExecutionContext::get () const protected
Definition at line 73 of file SBExecutionContext.cpp.
References m_exe_ctx_sp.
Referenced by lldb::SBInstructionList::GetDescription(), lldb::SBCommandInterpreter::HandleCommand(), lldb::SBCommandInterpreter::HandleCommandsFromFile(), and lldb_private::ScriptInterpreter.
GetFrame()
SBFrame SBExecutionContext::GetFrame () const
Definition at line 113 of file SBExecutionContext.cpp.
References LLDB_INSTRUMENT_VA, m_exe_ctx_sp, and lldb::SBFrame::SetFrameSP().
Referenced by ~SBExecutionContext().
GetProcess()
SBProcess SBExecutionContext::GetProcess () const
Definition at line 89 of file SBExecutionContext.cpp.
References LLDB_INSTRUMENT_VA, m_exe_ctx_sp, and lldb::SBProcess::SetSP().
Referenced by ~SBExecutionContext().
GetTarget()
SBTarget SBExecutionContext::GetTarget () const
Definition at line 77 of file SBExecutionContext.cpp.
References LLDB_INSTRUMENT_VA, m_exe_ctx_sp, and lldb::SBTarget::SetSP().
Referenced by ~SBExecutionContext().
GetThread()
SBThread SBExecutionContext::GetThread () const
Definition at line 101 of file SBExecutionContext.cpp.
References LLDB_INSTRUMENT_VA, m_exe_ctx_sp, and lldb::SBThread::SetThread().
Referenced by ~SBExecutionContext().
operator=()
const SBExecutionContext & SBExecutionContext::operator= (const lldb::SBExecutionContext & rhs)
Definition at line 65 of file SBExecutionContext.cpp.
References LLDB_INSTRUMENT_VA, m_exe_ctx_sp, and SBExecutionContext().
Referenced by ~SBExecutionContext().
Friends And Related Symbol Documentation
lldb_private::python::SWIGBridge
friend class lldb_private::python::SWIGBridge friend
Definition at line 59 of file SBExecutionContext.h.
lldb_private::ScriptInterpreter
friend class lldb_private::ScriptInterpreter friend
Definition at line 60 of file SBExecutionContext.h.
References get(), and SBExecutionContext().
SBCommandInterpreter
friend class SBCommandInterpreter friend
Definition at line 28 of file SBExecutionContext.h.
References SBCommandInterpreter, and SBExecutionContext().
Referenced by SBCommandInterpreter.
SBInstructionList
friend class SBInstructionList friend
Definition at line 58 of file SBExecutionContext.h.
References SBInstructionList.
Referenced by SBInstructionList.
Member Data Documentation
m_exe_ctx_sp
lldb::ExecutionContextRefSP lldb::SBExecutionContext::m_exe_ctx_sp mutable private
Definition at line 67 of file SBExecutionContext.h.
Referenced by get(), GetFrame(), lldb_private::ScriptInterpreter::GetOpaqueTypeFromSBExecutionContext(), GetProcess(), GetTarget(), GetThread(), operator=(), SBExecutionContext(), SBExecutionContext(), SBExecutionContext(), SBExecutionContext(), SBExecutionContext(), and SBExecutionContext().
The documentation for this class was generated from the following files:
SBExecutionContext.h
SBExecutionContext.cpp