LLDB: lldb_private::Breakpoint::BreakpointEventData Class Reference
lldb_private::Breakpoint::BreakpointEventData Class Reference
#include <Breakpoint.h>
Public Member Functions
BreakpointEventData (lldb::BreakpointEventType sub_type, const lldb::BreakpointSP &new_breakpoint_sp)
~BreakpointEventData () override
Log * GetLogChannel () override
llvm::StringRef GetFlavor () const override
lldb::BreakpointEventType GetBreakpointEventType () const
lldb::BreakpointSP GetBreakpoint () const
BreakpointLocationCollection & GetBreakpointLocationCollection ()
void Dump (Stream *s) const override
Public Member Functions inherited from lldb_private::EventData
EventData ()
virtual ~EventData ()
Static Public Member Functions
static llvm::StringRef GetFlavorString ()
static lldb::BreakpointEventType GetBreakpointEventTypeFromEvent (const lldb::EventSP &event_sp)
static lldb::BreakpointSP GetBreakpointFromEvent (const lldb::EventSP &event_sp)
static lldb::BreakpointLocationSP GetBreakpointLocationAtIndexFromEvent (const lldb::EventSP &event_sp, uint32_t loc_idx)
static size_t GetNumBreakpointLocationsFromEvent (const lldb::EventSP &event_sp)
static const BreakpointEventData * GetEventDataFromEvent (const Event *event_sp)
Private Member Functions
BreakpointEventData (const BreakpointEventData &)=delete
const BreakpointEventData & operator= (const BreakpointEventData &)=delete
Private Attributes
lldb::BreakpointEventType m_breakpoint_event
lldb::BreakpointSP m_new_breakpoint_sp
BreakpointLocationCollection m_locations
Detailed Description
Definition at line 101 of file Breakpoint.h.
Constructor & Destructor Documentation
BreakpointEventData() [1/2]
lldb_private::Breakpoint::BreakpointEventData::BreakpointEventData (lldb::BreakpointEventType sub_type, const lldb::BreakpointSP & new_breakpoint_sp)
Referenced by BreakpointEventData(), GetBreakpointEventTypeFromEvent(), GetBreakpointFromEvent(), GetBreakpointLocationAtIndexFromEvent(), GetEventDataFromEvent(), GetNumBreakpointLocationsFromEvent(), and operator=().
~BreakpointEventData()
Breakpoint::BreakpointEventData::~BreakpointEventData () override default
BreakpointEventData() [2/2]
lldb_private::Breakpoint::BreakpointEventData::BreakpointEventData (const BreakpointEventData &) private delete
References BreakpointEventData().
Member Function Documentation
Dump()
void Breakpoint::BreakpointEventData::Dump (Stream * s) const override virtual
Reimplemented from lldb_private::EventData.
Definition at line 1174 of file Breakpoint.cpp.
References lldb_private::Breakpoint::BreakpointEventTypeAsCString(), lldb_private::Stream::Format(), GetBreakpoint(), and GetBreakpointEventType().
GetBreakpoint()
BreakpointSP Breakpoint::BreakpointEventData::GetBreakpoint () const
Definition at line 1165 of file Breakpoint.cpp.
References m_new_breakpoint_sp.
Referenced by Dump().
GetBreakpointEventType()
BreakpointEventType Breakpoint::BreakpointEventData::GetBreakpointEventType () const
Definition at line 1170 of file Breakpoint.cpp.
References m_breakpoint_event.
Referenced by Dump(), and GetBreakpointEventTypeFromEvent().
GetBreakpointEventTypeFromEvent()
BreakpointEventType Breakpoint::BreakpointEventData::GetBreakpointEventTypeFromEvent (const lldb::EventSP & event_sp) static
Definition at line 1195 of file Breakpoint.cpp.
References BreakpointEventData(), GetBreakpointEventType(), and GetEventDataFromEvent().
Referenced by lldb::SBBreakpoint::GetBreakpointEventTypeFromEvent(), and lldb_private::Debugger::HandleBreakpointEvent().
GetBreakpointFromEvent()
BreakpointSP Breakpoint::BreakpointEventData::GetBreakpointFromEvent (const lldb::EventSP & event_sp) static
Definition at line 1204 of file Breakpoint.cpp.
References BreakpointEventData(), GetEventDataFromEvent(), and m_new_breakpoint_sp.
Referenced by lldb::SBBreakpoint::GetBreakpointFromEvent(), and lldb_private::Debugger::HandleBreakpointEvent().
GetBreakpointLocationAtIndexFromEvent()
lldb::BreakpointLocationSP Breakpoint::BreakpointEventData::GetBreakpointLocationAtIndexFromEvent (const lldb::EventSP & event_sp, uint32_t loc_idx) static
Definition at line 1225 of file Breakpoint.cpp.
References BreakpointEventData(), lldb_private::BreakpointLocationCollection::GetByIndex(), GetEventDataFromEvent(), and m_locations.
Referenced by lldb::SBBreakpoint::GetBreakpointLocationAtIndexFromEvent().
GetBreakpointLocationCollection()
BreakpointLocationCollection & lldb_private::Breakpoint::BreakpointEventData::GetBreakpointLocationCollection () inline
Definition at line 118 of file Breakpoint.h.
References m_locations.
GetEventDataFromEvent()
const Breakpoint::BreakpointEventData * Breakpoint::BreakpointEventData::GetEventDataFromEvent (const Event * event_sp) static
Definition at line 1184 of file Breakpoint.cpp.
References BreakpointEventData(), lldb_private::EventData::Event, lldb_private::EventData::EventData(), lldb_private::EventData::GetFlavor(), and GetFlavorString().
Referenced by lldb_private::Debugger::DefaultEventHandler(), lldb::SBBreakpoint::EventIsBreakpointEvent(), GetBreakpointEventTypeFromEvent(), GetBreakpointFromEvent(), GetBreakpointLocationAtIndexFromEvent(), and GetNumBreakpointLocationsFromEvent().
GetFlavor()
llvm::StringRef Breakpoint::BreakpointEventData::GetFlavor () const override virtual
Implements lldb_private::EventData.
Definition at line 1161 of file Breakpoint.cpp.
References GetFlavorString().
GetFlavorString()
llvm::StringRef Breakpoint::BreakpointEventData::GetFlavorString () static
Definition at line 1157 of file Breakpoint.cpp.
Referenced by GetEventDataFromEvent(), and GetFlavor().
GetLogChannel()
Log * Breakpoint::BreakpointEventData::GetLogChannel () override virtual
Reimplemented from lldb_private::EventData.
Definition at line 1147 of file Breakpoint.cpp.
References lldb_private::Breakpoints, and lldb_private::GetLog().
GetNumBreakpointLocationsFromEvent()
size_t Breakpoint::BreakpointEventData::GetNumBreakpointLocationsFromEvent (const lldb::EventSP & event_sp) static
Definition at line 1215 of file Breakpoint.cpp.
References BreakpointEventData(), GetEventDataFromEvent(), lldb_private::BreakpointLocationCollection::GetSize(), and m_locations.
Referenced by lldb::SBBreakpoint::GetNumBreakpointLocationsFromEvent(), and lldb_private::Debugger::HandleBreakpointEvent().
operator=()
const BreakpointEventData & lldb_private::Breakpoint::BreakpointEventData::operator= (const BreakpointEventData &) private delete
References BreakpointEventData().
Member Data Documentation
m_breakpoint_event
lldb::BreakpointEventType lldb_private::Breakpoint::BreakpointEventData::m_breakpoint_event private
Definition at line 141 of file Breakpoint.h.
Referenced by GetBreakpointEventType().
m_locations
BreakpointLocationCollection lldb_private::Breakpoint::BreakpointEventData::m_locations private
Definition at line 143 of file Breakpoint.h.
Referenced by GetBreakpointLocationAtIndexFromEvent(), GetBreakpointLocationCollection(), and GetNumBreakpointLocationsFromEvent().
m_new_breakpoint_sp
lldb::BreakpointSP lldb_private::Breakpoint::BreakpointEventData::m_new_breakpoint_sp private
Definition at line 142 of file Breakpoint.h.
Referenced by GetBreakpoint(), and GetBreakpointFromEvent().
The documentation for this class was generated from the following files:
Breakpoint.h
Breakpoint.cpp