LLDB: IOHandlerProcessSTDIO Class Reference
IOHandlerProcessSTDIO Class Reference
Public Member Functions
IOHandlerProcessSTDIO (Process *process, int write_fd)
~IOHandlerProcessSTDIO () override=default
void SetIsRunning (bool running)
void Run () override
void Cancel () override
bool Interrupt () override
void GotEOF () override
Public Member Functions inherited from lldb_private::IOHandler
IOHandler (Debugger &debugger, IOHandler::Type type)
IOHandler (Debugger &debugger, IOHandler::Type type, const lldb::FileSP &input_sp, const lldb::LockableStreamFileSP &output_sp, const lldb::LockableStreamFileSP &error_sp, uint32_t flags)
virtual ~IOHandler ()
bool IsActive ()
void SetIsDone (bool b)
bool GetIsDone ()
Type GetType () const
virtual void Activate ()
virtual void Deactivate ()
virtual void TerminalSizeChanged ()
virtual void Refresh ()
virtual const char * GetPrompt ()
virtual bool SetPrompt (llvm::StringRef prompt)
virtual bool SetUseColor (bool use_color)
bool SetPrompt (const char *)=delete
virtual llvm::StringRef GetControlSequence (char ch)
virtual const char * GetCommandPrefix ()
virtual const char * GetHelpPrologue ()
int GetInputFD ()
int GetOutputFD ()
int GetErrorFD ()
lldb::FileSP GetInputFileSP ()
lldb::LockableStreamFileSP GetOutputStreamFileSP ()
lldb::LockableStreamFileSP GetErrorStreamFileSP ()
Debugger & GetDebugger ()
void * GetUserData ()
void SetUserData (void *user_data)
Flags & GetFlags ()
const Flags & GetFlags () const
bool GetIsInteractive ()
Check if the input is being supplied interactively by a user.
bool GetIsRealTerminal ()
Check if the input is coming from a real terminal.
void SetPopped (bool b)
void WaitForPop ()
virtual void PrintAsync (const char *s, size_t len, bool is_stdout)
Protected Attributes
Process * m_process
NativeFile m_read_file
NativeFile m_write_file
Pipe m_pipe
std::mutex m_mutex
bool m_is_running = false
Protected Attributes inherited from lldb_private::IOHandler
Debugger & m_debugger
lldb::FileSP m_input_sp
lldb::LockableStreamFileSP m_output_sp
lldb::LockableStreamFileSP m_error_sp
Predicate< bool > m_popped
Flags m_flags
Type m_type
void * m_user_data
bool m_done
bool m_active
Additional Inherited Members
Public Types inherited from lldb_private::IOHandler
enum class Type {
CommandInterpreter , CommandList , Confirm , Curses ,
Expression , REPL , ProcessIO , PythonInterpreter ,
LuaInterpreter , PythonCode , Other
}
Detailed Description
Definition at line 4791 of file Process.cpp.
Constructor & Destructor Documentation
IOHandlerProcessSTDIO()
IOHandlerProcessSTDIO::IOHandlerProcessSTDIO (Process * process, int write_fd) inline
Definition at line 4793 of file Process.cpp.
References lldb_private::IOHandler::GetDebugger(), lldb_private::IOHandler::GetInputFD(), lldb_private::IOHandler::IOHandler(), m_pipe, m_process, m_read_file, m_write_file, and lldb_private::IOHandler::ProcessIO.
~IOHandlerProcessSTDIO()
IOHandlerProcessSTDIO::~IOHandlerProcessSTDIO () override default
Member Function Documentation
Cancel()
void IOHandlerProcessSTDIO::Cancel () inline override virtual
Implements lldb_private::IOHandler.
Definition at line 4874 of file Process.cpp.
References lldb_private::GetLog(), LLDB_LOG_ERROR, m_is_running, m_mutex, m_pipe, lldb_private::Process, and lldb_private::IOHandler::SetIsDone().
GotEOF()
void IOHandlerProcessSTDIO::GotEOF () inline override virtual
Implements lldb_private::IOHandler.
Definition at line 4924 of file Process.cpp.
Interrupt()
bool IOHandlerProcessSTDIO::Interrupt () inline override virtual
Implements lldb_private::IOHandler.
Definition at line 4897 of file Process.cpp.
References lldb_private::IOHandler::m_active, m_pipe, m_process, and lldb_private::StateIsRunningState().
Run()
void IOHandlerProcessSTDIO::Run () inline override virtual
Implements lldb_private::IOHandler.
Definition at line 4812 of file Process.cpp.
References error(), SelectHelper::FDIsSetRead(), SelectHelper::FDSetRead(), lldb_private::IOHandler::GetIsDone(), lldb_private::GetLog(), LLDB_LOG_ERROR, m_mutex, m_pipe, m_process, m_read_file, m_write_file, lldb_private::Process, SelectHelper::Select(), lldb_private::Terminal::SetCanonical(), lldb_private::Terminal::SetEcho(), lldb_private::IOHandler::SetIsDone(), SetIsRunning(), and lldb_private::StateIsRunningState().
SetIsRunning()
void IOHandlerProcessSTDIO::SetIsRunning (bool running) inline
Definition at line 4804 of file Process.cpp.
References m_is_running, m_mutex, and lldb_private::IOHandler::SetIsDone().
Referenced by Run().
Member Data Documentation
m_is_running
bool IOHandlerProcessSTDIO::m_is_running = false protected
Definition at line 4933 of file Process.cpp.
Referenced by Cancel(), and SetIsRunning().
m_mutex
std::mutex IOHandlerProcessSTDIO::m_mutex protected
Definition at line 4932 of file Process.cpp.
Referenced by Cancel(), Run(), and SetIsRunning().
m_pipe
Pipe IOHandlerProcessSTDIO::m_pipe protected
Definition at line 4931 of file Process.cpp.
Referenced by Cancel(), Interrupt(), IOHandlerProcessSTDIO(), and Run().
m_process
Process* IOHandlerProcessSTDIO::m_process protected
Definition at line 4927 of file Process.cpp.
Referenced by Interrupt(), IOHandlerProcessSTDIO(), and Run().
m_read_file
NativeFile IOHandlerProcessSTDIO::m_read_file protected
Definition at line 4928 of file Process.cpp.
Referenced by IOHandlerProcessSTDIO(), and Run().
m_write_file
NativeFile IOHandlerProcessSTDIO::m_write_file protected
Definition at line 4929 of file Process.cpp.
Referenced by IOHandlerProcessSTDIO(), and Run().
The documentation for this class was generated from the following file:
Process.cpp