LLDB: lldb_private::Checksum Class Reference
lldb_private::Checksum Class Reference
#include <Checksum.h>
Public Member Functions
Checksum (llvm::MD5::MD5Result md5=g_sentinel)
Checksum (const Checksum &checksum)
Checksum & operator= (const Checksum &checksum)
operator bool () const
bool operator== (const Checksum &checksum) const
bool operator!= (const Checksum &checksum) const
std::string digest () const
Static Public Attributes
static llvm::MD5::MD5Result g_sentinel
Private Member Functions
void SetMD5 (llvm::MD5::MD5Result)
Private Attributes
llvm::MD5::MD5Result m_checksum
Detailed Description
Definition at line 15 of file Checksum.h.
Constructor & Destructor Documentation
Checksum() [1/2]
Checksum::Checksum (llvm::MD5::MD5Result md5 = g_sentinel)
Definition at line 15 of file Checksum.cpp.
References SetMD5().
Referenced by Checksum(), operator!=(), operator=(), and operator==().
Checksum() [2/2]
Checksum::Checksum (const Checksum & checksum)
Definition at line 17 of file Checksum.cpp.
References Checksum(), m_checksum, and SetMD5().
Member Function Documentation
digest()
std::string Checksum::digest () const
Definition at line 36 of file Checksum.cpp.
References m_checksum.
Referenced by toString().
operator bool()
Checksum::operator bool () const explicit
Definition at line 26 of file Checksum.cpp.
References g_sentinel, and m_checksum.
operator!=()
bool Checksum::operator!= (const Checksum & checksum) const
Definition at line 32 of file Checksum.cpp.
References Checksum().
operator=()
Checksum & Checksum::operator= (const Checksum & checksum)
Definition at line 19 of file Checksum.cpp.
References Checksum(), m_checksum, and SetMD5().
operator==()
bool Checksum::operator== (const Checksum & checksum) const
Definition at line 28 of file Checksum.cpp.
References Checksum(), and m_checksum.
SetMD5()
void Checksum::SetMD5 (llvm::MD5::MD5Result md5) private
Definition at line 24 of file Checksum.cpp.
References m_checksum.
Referenced by Checksum(), Checksum(), and operator=().
Member Data Documentation
g_sentinel
llvm::MD5::MD5Result Checksum::g_sentinel static
Initial value:
= {
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
Definition at line 17 of file Checksum.h.
Referenced by operator bool().
m_checksum
llvm::MD5::MD5Result lldb_private::Checksum::m_checksum private
Definition at line 32 of file Checksum.h.
Referenced by Checksum(), digest(), operator bool(), operator=(), operator==(), and SetMD5().
The documentation for this class was generated from the following files:
Checksum.h
Checksum.cpp