LLDB: lldb_private::WatchpointOptions::CommandBaton Class Reference
lldb_private::WatchpointOptions::CommandBaton Class Reference
#include <WatchpointOptions.h>
Public Member Functions
CommandBaton (std::unique_ptr< CommandData > Data)
void GetDescription (llvm::raw_ostream &s, lldb::DescriptionLevel level, unsigned indentation) const override
Public Member Functions inherited from lldb_private::TypedBaton< CommandData >
TypedBaton (std::unique_ptr< CommandData > Item)
CommandData * getItem ()
void * data () override
void GetDescription (llvm::raw_ostream &s, lldb::DescriptionLevel level, unsigned indentation) const override
Public Member Functions inherited from lldb_private::Baton
Baton ()=default
virtual ~Baton ()=default
Additional Inherited Members
Protected Attributes inherited from lldb_private::TypedBaton< CommandData >
std::unique_ptr< CommandData > Item
Detailed Description
Definition at line 173 of file WatchpointOptions.h.
Constructor & Destructor Documentation
CommandBaton()
lldb_private::WatchpointOptions::CommandBaton::CommandBaton (std::unique_ptr< CommandData > Data) inline
Definition at line 175 of file WatchpointOptions.h.
References lldb_private::TypedBaton< CommandData >::TypedBaton().
Member Function Documentation
GetDescription()
void WatchpointOptions::CommandBaton::GetDescription (llvm::raw_ostream & s, lldb::DescriptionLevel level, unsigned indentation) const override virtual
Implements lldb_private::Baton.
Definition at line 157 of file WatchpointOptions.cpp.
References lldb_private::TypedBaton< CommandData >::data(), lldb::eDescriptionLevelBrief, and lldb_private::TypedBaton< CommandData >::getItem().
The documentation for this class was generated from the following files:
WatchpointOptions.h
WatchpointOptions.cpp