LLDB: lldb::SBTypeSynthetic Class Reference
lldb::SBTypeSynthetic Class Reference
#include <SBTypeSynthetic.h>
Public Member Functions
SBTypeSynthetic ()
SBTypeSynthetic (const lldb::SBTypeSynthetic &rhs)
~SBTypeSynthetic ()
operator bool () const
bool IsValid () const
bool IsClassCode ()
bool IsClassName ()
const char * GetData ()
void SetClassName (const char *data)
void SetClassCode (const char *data)
uint32_t GetOptions ()
void SetOptions (uint32_t)
bool GetDescription (lldb::SBStream &description, lldb::DescriptionLevel description_level)
lldb::SBTypeSynthetic & operator= (const lldb::SBTypeSynthetic &rhs)
bool IsEqualTo (lldb::SBTypeSynthetic &rhs)
bool operator== (lldb::SBTypeSynthetic &rhs)
bool operator!= (lldb::SBTypeSynthetic &rhs)
Static Public Member Functions
static SBTypeSynthetic CreateWithClassName (const char *data, uint32_t options=0)
static SBTypeSynthetic CreateWithScriptCode (const char *data, uint32_t options=0)
Protected Member Functions
lldb::ScriptedSyntheticChildrenSP GetSP ()
void SetSP (const lldb::ScriptedSyntheticChildrenSP &typefilter_impl_sp)
SBTypeSynthetic (const lldb::ScriptedSyntheticChildrenSP &)
bool CopyOnWrite_Impl ()
Protected Attributes
lldb::ScriptedSyntheticChildrenSP m_opaque_sp
Friends
class SBDebugger
class SBTypeCategory
class SBValue
Detailed Description
Definition at line 17 of file SBTypeSynthetic.h.
Constructor & Destructor Documentation
SBTypeSynthetic() [1/3]
SBTypeSynthetic::SBTypeSynthetic ()
Definition at line 19 of file SBTypeSynthetic.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by CreateWithClassName(), and CreateWithScriptCode().
SBTypeSynthetic() [2/3]
SBTypeSynthetic::SBTypeSynthetic (const lldb::SBTypeSynthetic & rhs)
Definition at line 41 of file SBTypeSynthetic.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
~SBTypeSynthetic()
SBTypeSynthetic::~SBTypeSynthetic () default
References GetData(), GetDescription(), GetOptions(), IsClassCode(), IsClassName(), IsEqualTo(), IsValid(), operator!=(), operator=(), operator==(), SetClassCode(), SetClassName(), and SetOptions().
SBTypeSynthetic() [3/3]
SBTypeSynthetic::SBTypeSynthetic (const lldb::ScriptedSyntheticChildrenSP & TypeSynthetic_impl_sp) protected
Definition at line 180 of file SBTypeSynthetic.cpp.
References m_opaque_sp.
Member Function Documentation
CopyOnWrite_Impl()
bool SBTypeSynthetic::CopyOnWrite_Impl () protected
Definition at line 184 of file SBTypeSynthetic.cpp.
References IsValid(), m_opaque_sp, and SetSP().
Referenced by SetOptions().
CreateWithClassName()
SBTypeSynthetic SBTypeSynthetic::CreateWithClassName (const char * data, uint32_t options = 0) static
Definition at line 21 of file SBTypeSynthetic.cpp.
References LLDB_INSTRUMENT_VA, and SBTypeSynthetic().
CreateWithScriptCode()
SBTypeSynthetic SBTypeSynthetic::CreateWithScriptCode (const char * data, uint32_t options = 0) static
Definition at line 31 of file SBTypeSynthetic.cpp.
References LLDB_INSTRUMENT_VA, and SBTypeSynthetic().
GetData()
const char * SBTypeSynthetic::GetData ()
Definition at line 75 of file SBTypeSynthetic.cpp.
References lldb_private::ConstString::GetCString(), IsClassCode(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by lldb::SBTypeCategory::AddTypeSynthetic(), IsEqualTo(), and ~SBTypeSynthetic().
GetDescription()
bool SBTypeSynthetic::GetDescription (lldb::SBStream & description, lldb::DescriptionLevel description_level)
Definition at line 116 of file SBTypeSynthetic.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeSynthetic().
GetOptions()
uint32_t SBTypeSynthetic::GetOptions ()
Definition at line 100 of file SBTypeSynthetic.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by IsEqualTo(), and ~SBTypeSynthetic().
GetSP()
lldb::ScriptedSyntheticChildrenSP SBTypeSynthetic::GetSP () protected
Definition at line 171 of file SBTypeSynthetic.cpp.
References m_opaque_sp.
Referenced by lldb::SBTypeCategory::AddTypeSynthetic(), and SBValue.
IsClassCode()
bool SBTypeSynthetic::IsClassCode ()
Definition at line 58 of file SBTypeSynthetic.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by lldb::SBTypeCategory::AddTypeSynthetic(), GetData(), IsClassName(), IsEqualTo(), and ~SBTypeSynthetic().
IsClassName()
bool SBTypeSynthetic::IsClassName ()
Definition at line 67 of file SBTypeSynthetic.cpp.
References IsClassCode(), IsValid(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBTypeSynthetic().
IsEqualTo()
bool SBTypeSynthetic::IsEqualTo (lldb::SBTypeSynthetic & rhs)
Definition at line 145 of file SBTypeSynthetic.cpp.
References GetData(), GetOptions(), IsClassCode(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeSynthetic().
IsValid()
bool SBTypeSynthetic::IsValid () const
Definition at line 48 of file SBTypeSynthetic.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBTypeCategory::AddTypeSynthetic(), CopyOnWrite_Impl(), GetData(), GetOptions(), IsClassCode(), IsClassName(), IsEqualTo(), operator!=(), operator==(), SetClassCode(), SetClassName(), and ~SBTypeSynthetic().
operator bool()
SBTypeSynthetic::operator bool () const explicit
Definition at line 52 of file SBTypeSynthetic.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator!=()
bool SBTypeSynthetic::operator!= (lldb::SBTypeSynthetic & rhs)
Definition at line 163 of file SBTypeSynthetic.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeSynthetic().
operator=()
lldb::SBTypeSynthetic & SBTypeSynthetic::operator= (const lldb::SBTypeSynthetic & rhs)
Definition at line 127 of file SBTypeSynthetic.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeSynthetic().
operator==()
bool SBTypeSynthetic::operator== (lldb::SBTypeSynthetic & rhs)
Definition at line 137 of file SBTypeSynthetic.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeSynthetic().
SetClassCode()
void SBTypeSynthetic::SetClassCode (const char * data)
Definition at line 93 of file SBTypeSynthetic.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeSynthetic().
SetClassName()
void SBTypeSynthetic::SetClassName (const char * data)
Definition at line 86 of file SBTypeSynthetic.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by lldb::SBTypeCategory::AddTypeSynthetic(), and ~SBTypeSynthetic().
SetOptions()
void SBTypeSynthetic::SetOptions (uint32_t value)
Definition at line 108 of file SBTypeSynthetic.cpp.
References CopyOnWrite_Impl(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBTypeSynthetic().
SetSP()
void SBTypeSynthetic::SetSP (const lldb::ScriptedSyntheticChildrenSP & typefilter_impl_sp) protected
Definition at line 175 of file SBTypeSynthetic.cpp.
References m_opaque_sp.
Referenced by CopyOnWrite_Impl(), lldb::SBValue::GetTypeSynthetic(), and SBValue.
Friends And Related Symbol Documentation
SBDebugger
friend class SBDebugger friend
Definition at line 63 of file SBTypeSynthetic.h.
References SBDebugger.
Referenced by SBDebugger.
SBTypeCategory
friend class SBTypeCategory friend
Definition at line 64 of file SBTypeSynthetic.h.
References SBTypeCategory.
Referenced by SBTypeCategory.
SBValue
friend class SBValue friend
Definition at line 65 of file SBTypeSynthetic.h.
References GetSP(), SBValue, and SetSP().
Referenced by SBValue.
Member Data Documentation
m_opaque_sp
lldb::ScriptedSyntheticChildrenSP lldb::SBTypeSynthetic::m_opaque_sp protected
Definition at line 71 of file SBTypeSynthetic.h.
Referenced by CopyOnWrite_Impl(), GetData(), GetDescription(), GetOptions(), GetSP(), IsClassCode(), IsEqualTo(), operator bool(), operator!=(), operator=(), operator==(), SBTypeSynthetic(), SBTypeSynthetic(), SetClassCode(), SetClassName(), SetOptions(), and SetSP().
The documentation for this class was generated from the following files:
SBTypeSynthetic.h
SBTypeSynthetic.cpp