LLDB: lldb_private::dil::BitFieldExtractionNode Class Reference
lldb_private::dil::BitFieldExtractionNode Class Reference
#include <DILAST.h>
Public Member Functions
BitFieldExtractionNode (uint32_t location, ASTNodeUP base, ASTNodeUP first_index, ASTNodeUP last_index)
llvm::Expected< lldb::ValueObjectSP > Accept (Visitor *v) const override
ASTNode & GetBase () const
ASTNode & GetFirstIndex () const
ASTNode & GetLastIndex () const
Public Member Functions inherited from lldb_private::dil::ASTNode
ASTNode (uint32_t location, NodeKind kind)
virtual ~ASTNode ()=default
uint32_t GetLocation () const
NodeKind GetKind () const
Static Public Member Functions
static bool classof (const ASTNode &node)
Private Attributes
ASTNodeUP m_base
ASTNodeUP m_first_index
ASTNodeUP m_last_index
Detailed Description
Definition at line 171 of file DILAST.h.
Constructor & Destructor Documentation
BitFieldExtractionNode()
lldb_private::dil::BitFieldExtractionNode::BitFieldExtractionNode (uint32_t location, ASTNodeUP base, ASTNodeUP first_index, ASTNodeUP last_index) inline
Definition at line 173 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), lldb_private::dil::eBitExtractionNode, m_base, m_first_index, and m_last_index.
Member Function Documentation
Accept()
llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::BitFieldExtractionNode::Accept (Visitor * v) const override virtual
Implements lldb_private::dil::ASTNode.
Definition at line 36 of file DILAST.cpp.
References lldb_private::dil::Visitor::Visit().
classof()
bool lldb_private::dil::BitFieldExtractionNode::classof (const ASTNode & node) inline static
Definition at line 185 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), lldb_private::dil::eBitExtractionNode, and lldb_private::dil::ASTNode::GetKind().
GetBase()
ASTNode & lldb_private::dil::BitFieldExtractionNode::GetBase () const inline
Definition at line 181 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), and m_base.
Referenced by lldb_private::dil::Interpreter::Visit().
GetFirstIndex()
ASTNode & lldb_private::dil::BitFieldExtractionNode::GetFirstIndex () const inline
Definition at line 182 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), and m_first_index.
Referenced by lldb_private::dil::Interpreter::Visit().
GetLastIndex()
ASTNode & lldb_private::dil::BitFieldExtractionNode::GetLastIndex () const inline
Definition at line 183 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), and m_last_index.
Referenced by lldb_private::dil::Interpreter::Visit().
Member Data Documentation
m_base
ASTNodeUP lldb_private::dil::BitFieldExtractionNode::m_base private
Definition at line 190 of file DILAST.h.
Referenced by BitFieldExtractionNode(), and GetBase().
m_first_index
ASTNodeUP lldb_private::dil::BitFieldExtractionNode::m_first_index private
Definition at line 191 of file DILAST.h.
Referenced by BitFieldExtractionNode(), and GetFirstIndex().
m_last_index
ASTNodeUP lldb_private::dil::BitFieldExtractionNode::m_last_index private
Definition at line 192 of file DILAST.h.
Referenced by BitFieldExtractionNode(), and GetLastIndex().
The documentation for this class was generated from the following files:
DILAST.h
DILAST.cpp