LLDB: lldb_private::breakpad::SymbolFileBreakpad::LineIterator Class Reference
lldb_private::breakpad::SymbolFileBreakpad::LineIterator Class Reference
Public Member Functions
LineIterator (ObjectFile &obj, Record::Kind section_type)
LineIterator (ObjectFile &obj, Record::Kind section_type, Bookmark bookmark)
LineIterator (ObjectFile &obj)
const LineIterator & operator++ ()
llvm::StringRef operator* () const
Bookmark GetBookmark () const
Private Member Functions
void FindNextLine ()
Private Attributes
ObjectFile * m_obj
ConstString m_section_type
uint32_t m_next_section_idx
llvm::StringRef m_section_text
size_t m_current_line
size_t m_next_line
Friends
bool operator!= (const LineIterator &lhs, const LineIterator &rhs)
Detailed Description
Definition at line 34 of file SymbolFileBreakpad.cpp.
Constructor & Destructor Documentation
LineIterator() [1/3]
lldb_private::breakpad::SymbolFileBreakpad::LineIterator::LineIterator (ObjectFile & obj, Record::Kind section_type) inline
Definition at line 37 of file SymbolFileBreakpad.cpp.
References m_next_line, m_next_section_idx, m_obj, m_section_type, and lldb_private::breakpad::toString().
Referenced by operator!=.
LineIterator() [2/3]
lldb_private::breakpad::SymbolFileBreakpad::LineIterator::LineIterator (ObjectFile & obj, Record::Kind section_type, Bookmark bookmark)
Definition at line 90 of file SymbolFileBreakpad.cpp.
References FindNextLine(), lldb_private::DataExtractor::GetData(), lldb_private::Section::GetName(), lldb_private::ObjectFile::GetSectionList(), m_current_line, m_next_section_idx, m_obj, m_section_text, m_section_type, lldb_private::ObjectFile::ReadSectionData(), and lldb_private::breakpad::toString().
LineIterator() [3/3]
lldb_private::breakpad::SymbolFileBreakpad::LineIterator::LineIterator (ObjectFile & obj) inline explicit
Definition at line 47 of file SymbolFileBreakpad.cpp.
References m_current_line, m_next_line, m_next_section_idx, and m_obj.
Member Function Documentation
FindNextLine()
void lldb_private::breakpad::SymbolFileBreakpad::LineIterator::FindNextLine () inline private
Definition at line 80 of file SymbolFileBreakpad.cpp.
References m_current_line, m_next_line, and m_section_text.
Referenced by LineIterator(), and operator++().
GetBookmark()
Bookmark lldb_private::breakpad::SymbolFileBreakpad::LineIterator::GetBookmark () const inline
Definition at line 68 of file SymbolFileBreakpad.cpp.
References m_current_line, and m_next_section_idx.
operator*()
llvm::StringRef lldb_private::breakpad::SymbolFileBreakpad::LineIterator::operator* () const inline
Definition at line 64 of file SymbolFileBreakpad.cpp.
References m_current_line, m_next_line, and m_section_text.
operator++()
const SymbolFileBreakpad::LineIterator & lldb_private::breakpad::SymbolFileBreakpad::LineIterator::operator++ ()
Definition at line 108 of file SymbolFileBreakpad.cpp.
References FindNextLine(), lldb_private::DataExtractor::GetData(), lldb_private::Section::GetName(), lldb_private::SectionList::GetNumSections(), lldb_private::SectionList::GetSectionAtIndex(), m_current_line, m_next_line, m_next_section_idx, m_obj, m_section_text, and m_section_type.
Friends And Related Symbol Documentation
operator!=
bool operator!= (const LineIterator & lhs, const LineIterator & rhs) friend
Definition at line 53 of file SymbolFileBreakpad.cpp.
References LineIterator(), m_current_line, m_next_line, m_next_section_idx, and m_obj.
Member Data Documentation
m_current_line
size_t lldb_private::breakpad::SymbolFileBreakpad::LineIterator::m_current_line private
Definition at line 77 of file SymbolFileBreakpad.cpp.
Referenced by FindNextLine(), GetBookmark(), LineIterator(), LineIterator(), operator!=, operator*(), and operator++().
m_next_line
size_t lldb_private::breakpad::SymbolFileBreakpad::LineIterator::m_next_line private
Definition at line 78 of file SymbolFileBreakpad.cpp.
Referenced by FindNextLine(), LineIterator(), LineIterator(), operator!=, operator*(), and operator++().
m_next_section_idx
uint32_t lldb_private::breakpad::SymbolFileBreakpad::LineIterator::m_next_section_idx private
Definition at line 75 of file SymbolFileBreakpad.cpp.
Referenced by GetBookmark(), LineIterator(), LineIterator(), LineIterator(), operator!=, and operator++().
m_obj
ObjectFile* lldb_private::breakpad::SymbolFileBreakpad::LineIterator::m_obj private
Definition at line 73 of file SymbolFileBreakpad.cpp.
Referenced by LineIterator(), LineIterator(), LineIterator(), operator!=, and operator++().
m_section_text
llvm::StringRef lldb_private::breakpad::SymbolFileBreakpad::LineIterator::m_section_text private
Definition at line 76 of file SymbolFileBreakpad.cpp.
Referenced by FindNextLine(), LineIterator(), operator*(), and operator++().
m_section_type
ConstString lldb_private::breakpad::SymbolFileBreakpad::LineIterator::m_section_type private
Definition at line 74 of file SymbolFileBreakpad.cpp.
Referenced by LineIterator(), LineIterator(), and operator++().
The documentation for this class was generated from the following file:
SymbolFileBreakpad.cpp