LLDB: lldb_private::ValueObjectList Class Reference
lldb_private::ValueObjectList Class Reference
A collection of ValueObject values that.
#include <ValueObjectList.h>
Public Member Functions
void Append (const lldb::ValueObjectSP &val_obj_sp)
void Append (const ValueObjectList &valobj_list)
lldb::ValueObjectSP FindValueObjectByPointer (ValueObject *valobj)
size_t GetSize () const
void Resize (size_t size)
lldb::ValueObjectSP GetValueObjectAtIndex (size_t idx)
lldb::ValueObjectSP RemoveValueObjectAtIndex (size_t idx)
void SetValueObjectAtIndex (size_t idx, const lldb::ValueObjectSP &valobj_sp)
lldb::ValueObjectSP FindValueObjectByValueName (const char *name)
lldb::ValueObjectSP FindValueObjectByUID (lldb::user_id_t uid)
void Swap (ValueObjectList &value_object_list)
void Clear ()
const std::vector< lldb::ValueObjectSP > & GetObjects () const
Protected Types
typedef std::vector< lldb::ValueObjectSP > collection
Protected Attributes
collection m_value_objects
Detailed Description
A collection of ValueObject values that.
Definition at line 23 of file ValueObjectList.h.
Member Typedef Documentation
collection
typedef std::vector<lldb::ValueObjectSP> lldb_private::ValueObjectList::collection protected
Definition at line 54 of file ValueObjectList.h.
Member Function Documentation
Append() [1/2]
void ValueObjectList::Append (const lldb::ValueObjectSP & val_obj_sp)
Definition at line 19 of file ValueObjectList.cpp.
References m_value_objects.
Referenced by CommandObjectFrameDiagnose::DoExecute(), lldb_private::CommandObjectDWIMPrint::DoExecute(), CommandObjectTargetVariable::DumpGlobalVariableList(), and lldb_private::Variable::GetValuesForVariableExpressionPath().
Append() [2/2]
void ValueObjectList::Append (const ValueObjectList & valobj_list)
Definition at line 23 of file ValueObjectList.cpp.
References m_value_objects.
Clear()
void lldb_private::ValueObjectList::Clear () inline
Definition at line 47 of file ValueObjectList.h.
References m_value_objects.
FindValueObjectByPointer()
ValueObjectSP ValueObjectList::FindValueObjectByPointer (ValueObject * valobj)
Definition at line 87 of file ValueObjectList.cpp.
References m_value_objects.
FindValueObjectByUID()
ValueObjectSP ValueObjectList::FindValueObjectByUID (lldb::user_id_t uid)
Definition at line 70 of file ValueObjectList.cpp.
References lldb_private::ValueObject::GetID(), and m_value_objects.
FindValueObjectByValueName()
ValueObjectSP ValueObjectList::FindValueObjectByValueName (const char * name)
Definition at line 56 of file ValueObjectList.cpp.
References lldb_private::ValueObject::GetName(), and m_value_objects.
GetObjects()
const std::vector< lldb::ValueObjectSP > & lldb_private::ValueObjectList::GetObjects () const inline
Definition at line 49 of file ValueObjectList.h.
References m_value_objects.
GetSize()
size_t ValueObjectList::GetSize () const
Definition at line 29 of file ValueObjectList.cpp.
References m_value_objects.
Referenced by lldb_private::Variable::GetValuesForVariableExpressionPath().
GetValueObjectAtIndex()
lldb::ValueObjectSP ValueObjectList::GetValueObjectAtIndex (size_t idx)
Definition at line 33 of file ValueObjectList.cpp.
References m_value_objects.
Referenced by CommandObjectTargetVariable::DoExecute(), and lldb_private::Variable::GetValuesForVariableExpressionPath().
RemoveValueObjectAtIndex()
lldb::ValueObjectSP ValueObjectList::RemoveValueObjectAtIndex (size_t idx)
Definition at line 40 of file ValueObjectList.cpp.
References m_value_objects.
Referenced by lldb_private::Variable::GetValuesForVariableExpressionPath().
Resize()
void ValueObjectList::Resize (size_t size)
Definition at line 31 of file ValueObjectList.cpp.
References m_value_objects.
SetValueObjectAtIndex()
void ValueObjectList::SetValueObjectAtIndex (size_t idx, const lldb::ValueObjectSP & valobj_sp)
Definition at line 49 of file ValueObjectList.cpp.
References m_value_objects.
Referenced by lldb_private::Variable::GetValuesForVariableExpressionPath().
Swap()
void ValueObjectList::Swap (ValueObjectList & value_object_list)
Definition at line 101 of file ValueObjectList.cpp.
References m_value_objects.
Member Data Documentation
m_value_objects
collection lldb_private::ValueObjectList::m_value_objects protected
Definition at line 56 of file ValueObjectList.h.
Referenced by Append(), Append(), Clear(), FindValueObjectByPointer(), FindValueObjectByUID(), FindValueObjectByValueName(), GetObjects(), GetSize(), GetValueObjectAtIndex(), RemoveValueObjectAtIndex(), Resize(), SetValueObjectAtIndex(), and Swap().
The documentation for this class was generated from the following files:
ValueObjectList.h
ValueObjectList.cpp