LLDB: SelectHelper Class Reference
SelectHelper Class Reference
#include <SelectHelper.h>
Classes
struct FDInfo
Public Member Functions
SelectHelper ()
void SetTimeout (const std::chrono::microseconds &timeout)
void FDSetRead (lldb::socket_t fd)
void FDSetWrite (lldb::socket_t fd)
void FDSetError (lldb::socket_t fd)
bool FDIsSetRead (lldb::socket_t fd) const
bool FDIsSetWrite (lldb::socket_t fd) const
bool FDIsSetError (lldb::socket_t fd) const
lldb_private::Status Select ()
Protected Attributes
llvm::DenseMap< lldb::socket_t, FDInfo > m_fd_map
std::optional< std::chrono::steady_clock::time_point > m_end_time
Detailed Description
Definition at line 20 of file SelectHelper.h.
Constructor & Destructor Documentation
SelectHelper()
SelectHelper::SelectHelper ()
Definition at line 39 of file SelectHelper.cpp.
References m_end_time, and m_fd_map.
Member Function Documentation
FDIsSetError()
bool SelectHelper::FDIsSetError (lldb::socket_t fd) const
Definition at line 77 of file SelectHelper.cpp.
References m_fd_map.
FDIsSetRead()
bool SelectHelper::FDIsSetRead (lldb::socket_t fd) const
Definition at line 61 of file SelectHelper.cpp.
References m_fd_map.
Referenced by lldb_private::ConnectionFileDescriptor::BytesAvailable(), and IOHandlerProcessSTDIO::Run().
FDIsSetWrite()
bool SelectHelper::FDIsSetWrite (lldb::socket_t fd) const
Definition at line 69 of file SelectHelper.cpp.
References m_fd_map.
FDSetError()
void SelectHelper::FDSetError (lldb::socket_t fd)
Definition at line 57 of file SelectHelper.cpp.
References m_fd_map.
FDSetRead()
void SelectHelper::FDSetRead (lldb::socket_t fd)
Definition at line 49 of file SelectHelper.cpp.
References m_fd_map.
Referenced by lldb_private::ConnectionFileDescriptor::BytesAvailable(), IsInputPending(), lldb_private::PipePosix::Read(), and IOHandlerProcessSTDIO::Run().
FDSetWrite()
void SelectHelper::FDSetWrite (lldb::socket_t fd)
Definition at line 53 of file SelectHelper.cpp.
References m_fd_map.
Referenced by lldb_private::PipePosix::Write().
Select()
lldb_private::Status SelectHelper::Select ()
Definition at line 93 of file SelectHelper.cpp.
References lldb::eErrorTypePOSIX, error(), lldb_private::Status::FromErrno(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldbassert, m_end_time, m_fd_map, lldb_private::Status, and updateMaxFd().
Referenced by lldb_private::ConnectionFileDescriptor::BytesAvailable(), IsInputPending(), lldb_private::PipePosix::Read(), IOHandlerProcessSTDIO::Run(), and lldb_private::PipePosix::Write().
SetTimeout()
void SelectHelper::SetTimeout (const std::chrono::microseconds & timeout)
Definition at line 44 of file SelectHelper.cpp.
References m_end_time.
Referenced by lldb_private::ConnectionFileDescriptor::BytesAvailable(), IsInputPending(), lldb_private::PipePosix::Read(), and lldb_private::PipePosix::Write().
Member Data Documentation
m_end_time
std::optional<std::chrono::steady_clock::time_point> SelectHelper::m_end_time protected
Definition at line 68 of file SelectHelper.h.
Referenced by Select(), SelectHelper(), and SetTimeout().
m_fd_map
llvm::DenseMap<lldb::socket_t, FDInfo> SelectHelper::m_fd_map protected
Definition at line 67 of file SelectHelper.h.
Referenced by FDIsSetError(), FDIsSetRead(), FDIsSetWrite(), FDSetError(), FDSetRead(), FDSetWrite(), Select(), and SelectHelper().
The documentation for this class was generated from the following files:
SelectHelper.h
SelectHelper.cpp