LLDB: lldb_private::process_gdb_remote::GDBRemoteCommunicationClient Class Reference
lldb_private::process_gdb_remote::GDBRemoteCommunicationClient Class Reference
#include <GDBRemoteCommunicationClient.h>
Public Types
enum class xPacketState { Unimplemented , Prefixed , Bare }
Public Types inherited from lldb_private::process_gdb_remote::GDBRemoteClientBase
enum { eBroadcastBitRunPacketSent = (1u << 0) }
Public Types inherited from lldb_private::process_gdb_remote::GDBRemoteCommunication
enum class PacketType { Invalid = 0 , Standard , Notify }
enum class PacketResult {
Success = 0 , ErrorSendFailed , ErrorSendAck , ErrorReplyFailed ,
ErrorReplyTimeout , ErrorReplyInvalid , ErrorReplyAck , ErrorDisconnected ,
ErrorNoSequenceLock
}
Public Member Functions
GDBRemoteCommunicationClient ()
~GDBRemoteCommunicationClient () override
bool HandshakeWithServer (Status *error_ptr)
bool GetThreadSuffixSupported ()
bool QueryNoAckModeSupported ()
void GetListThreadsInStopReplySupported ()
lldb::pid_t GetCurrentProcessID (bool allow_lazy=true)
bool LaunchGDBServer (const char *remote_accept_hostname, lldb::pid_t &pid, uint16_t &port, std::string &socket_name)
size_t QueryGDBServer (std::vector< std::pair< uint16_t, std::string > > &connection_urls)
bool KillSpawnedProcess (lldb::pid_t pid)
llvm::Error LaunchProcess (const Args &args)
Launch the process using the provided arguments.
int SendEnvironmentPacket (char const *name_equal_value)
Sends a "QEnvironment:NAME=VALUE" packet that will build up the environment that will get used when launching an application in conjunction with the 'A' packet.
int SendEnvironment (const Environment &env)
int SendLaunchArchPacket (const char *arch)
int SendLaunchEventDataPacket (const char *data, bool *was_supported=nullptr)
int SendStdinNotification (const char *data, size_t data_len)
Sends a GDB remote protocol 'I' packet that delivers stdin data to the remote process.
int SetSTDIN (const FileSpec &file_spec)
Sets the path to use for stdin/out/err for a process that will be launched with the 'A' packet.
int SetSTDOUT (const FileSpec &file_spec)
int SetSTDERR (const FileSpec &file_spec)
int SetDisableASLR (bool enable)
Sets the disable ASLR flag to enable for a process that will be launched with the 'A' packet.
int SetDetachOnError (bool enable)
Sets the DetachOnError flag to enable for the process controlled by the stub.
int SetWorkingDir (const FileSpec &working_dir)
Sets the working directory to path for a process that will be launched with the 'A' packet for non platform based connections.
bool GetWorkingDir (FileSpec &working_dir)
Gets the current working directory of a remote platform GDB server.
lldb::addr_t AllocateMemory (size_t size, uint32_t permissions)
bool DeallocateMemory (lldb::addr_t addr)
Status Detach (bool keep_stopped, lldb::pid_t pid=LLDB_INVALID_PROCESS_ID)
Status GetMemoryRegionInfo (lldb::addr_t addr, MemoryRegionInfo &range_info)
std::optional< uint32_t > GetWatchpointSlotCount ()
std::optional< bool > GetWatchpointReportedAfter ()
WatchpointHardwareFeature GetSupportedWatchpointTypes ()
const ArchSpec & GetHostArchitecture ()
std::chrono::seconds GetHostDefaultPacketTimeout ()
const ArchSpec & GetProcessArchitecture ()
bool GetProcessStandaloneBinary (UUID &uuid, lldb::addr_t &value, bool &value_is_offset)
std::vector< lldb::addr_t > GetProcessStandaloneBinaries ()
void GetRemoteQSupported ()
bool GetVContSupported (llvm::StringRef flavor)
bool GetpPacketSupported (lldb::tid_t tid)
xPacketState GetxPacketState ()
bool GetVAttachOrWaitSupported ()
bool GetSyncThreadStateSupported ()
void ResetDiscoverableSettings (bool did_exec)
bool GetHostInfo (bool force=false)
bool GetDefaultThreadId (lldb::tid_t &tid)
llvm::VersionTuple GetOSVersion ()
llvm::VersionTuple GetMacCatalystVersion ()
std::optional< std::string > GetOSBuildString ()
std::optional< std::string > GetOSKernelDescription ()
ArchSpec GetSystemArchitecture ()
lldb_private::AddressableBits GetAddressableBits ()
bool GetHostname (std::string &s)
lldb::addr_t GetShlibInfoAddr ()
bool GetProcessInfo (lldb::pid_t pid, ProcessInstanceInfo &process_info)
uint32_t FindProcesses (const ProcessInstanceInfoMatch &process_match_info, ProcessInstanceInfoList &process_infos)
bool GetUserName (uint32_t uid, std::string &name)
bool GetGroupName (uint32_t gid, std::string &name)
bool HasFullVContSupport ()
bool HasAnyVContSupport ()
bool GetStopReply (StringExtractorGDBRemote &response)
bool GetThreadStopInfo (lldb::tid_t tid, StringExtractorGDBRemote &response)
bool SupportsGDBStoppointPacket (GDBStoppointType type)
uint8_t SendGDBStoppointTypePacket (GDBStoppointType type, bool insert, lldb::addr_t addr, uint32_t length, std::chrono::seconds interrupt_timeout)
void TestPacketSpeed (const uint32_t num_packets, uint32_t max_send, uint32_t max_recv, uint64_t recv_amount, bool json, Stream &strm)
bool SendSpeedTestPacket (uint32_t send_size, uint32_t recv_size)
std::optional< PidTid > SendSetCurrentThreadPacket (uint64_t tid, uint64_t pid, char op)
bool SetCurrentThread (uint64_t tid, lldb::pid_t pid=LLDB_INVALID_PROCESS_ID)
bool SetCurrentThreadForRun (uint64_t tid, lldb::pid_t pid=LLDB_INVALID_PROCESS_ID)
bool GetQXferAuxvReadSupported ()
void EnableErrorStringInPacket ()
bool GetQXferLibrariesReadSupported ()
bool GetQXferLibrariesSVR4ReadSupported ()
uint64_t GetRemoteMaxPacketSize ()
bool GetEchoSupported ()
bool GetQPassSignalsSupported ()
bool GetAugmentedLibrariesSVR4ReadSupported ()
bool GetQXferFeaturesReadSupported ()
bool GetQXferMemoryMapReadSupported ()
bool GetQXferSigInfoReadSupported ()
bool GetMultiprocessSupported ()
bool GetReverseContinueSupported ()
bool GetReverseStepSupported ()
bool GetMultiMemReadSupported ()
LazyBool SupportsAllocDeallocMemory ()
std::vector< std::pair< lldb::pid_t, lldb::tid_t > > GetCurrentProcessAndThreadIDs (bool &sequence_mutex_unavailable)
size_t GetCurrentThreadIDs (std::vector< lldb::tid_t > &thread_ids, bool &sequence_mutex_unavailable)
lldb::user_id_t OpenFile (const FileSpec &file_spec, File::OpenOptions flags, mode_t mode, Status &error)
bool CloseFile (lldb::user_id_t fd, Status &error)
std::optional< GDBRemoteFStatData > FStat (lldb::user_id_t fd)
std::optional< GDBRemoteFStatData > Stat (const FileSpec &file_spec)
lldb::user_id_t GetFileSize (const FileSpec &file_spec)
void AutoCompleteDiskFileOrDirectory (CompletionRequest &request, bool only_dir)
Status GetFilePermissions (const FileSpec &file_spec, uint32_t &file_permissions)
Status SetFilePermissions (const FileSpec &file_spec, uint32_t file_permissions)
uint64_t ReadFile (lldb::user_id_t fd, uint64_t offset, void *dst, uint64_t dst_len, Status &error)
uint64_t WriteFile (lldb::user_id_t fd, uint64_t offset, const void *src, uint64_t src_len, Status &error)
Status CreateSymlink (const FileSpec &src, const FileSpec &dst)
Status Unlink (const FileSpec &file_spec)
Status MakeDirectory (const FileSpec &file_spec, uint32_t mode)
bool GetFileExists (const FileSpec &file_spec)
Status RunShellCommand (llvm::StringRef command, const FileSpec &working_dir, int *status_ptr, int *signo_ptr, std::string *command_output, const Timeout< std::micro > &timeout)
llvm::ErrorOr< llvm::MD5::MD5Result > CalculateMD5 (const FileSpec &file_spec)
lldb::DataBufferSP ReadRegister (lldb::tid_t tid, uint32_t reg_num)
lldb::DataBufferSP ReadAllRegisters (lldb::tid_t tid)
bool WriteRegister (lldb::tid_t tid, uint32_t reg_num, llvm::ArrayRef< uint8_t > data)
bool WriteAllRegisters (lldb::tid_t tid, llvm::ArrayRef< uint8_t > data)
bool SaveRegisterState (lldb::tid_t tid, uint32_t &save_id)
bool RestoreRegisterState (lldb::tid_t tid, uint32_t save_id)
bool SyncThreadState (lldb::tid_t tid)
const char * GetGDBServerProgramName ()
uint32_t GetGDBServerProgramVersion ()
bool AvoidGPackets (ProcessGDBRemote *process)
StructuredData::ObjectSP GetThreadsInfo ()
bool GetThreadExtendedInfoSupported ()
bool GetLoadedDynamicLibrariesInfosSupported ()
bool GetSharedCacheInfoSupported ()
bool GetDynamicLoaderProcessStateSupported ()
bool GetMemoryTaggingSupported ()
bool UsesNativeSignals ()
lldb::DataBufferSP ReadMemoryTags (lldb::addr_t addr, size_t len, int32_t type)
Status WriteMemoryTags (lldb::addr_t addr, size_t len, int32_t type, const std::vector< uint8_t > &tags)
std::optional< QOffsets > GetQOffsets ()
Use qOffsets to query the offset used when relocating the target executable.
bool GetModuleInfo (const FileSpec &module_file_spec, const ArchSpec &arch_spec, ModuleSpec &module_spec)
std::optional< std::vector< ModuleSpec > > GetModulesInfo (llvm::ArrayRef< FileSpec > module_file_specs, const llvm::Triple &triple)
llvm::Expected< std::string > ReadExtFeature (llvm::StringRef object, llvm::StringRef annex)
void ServeSymbolLookups (lldb_private::Process *process)
Status SendSignalsToIgnore (llvm::ArrayRef< int32_t > signals)
const std::string & GetServerSupportedFeatures () const
Return the feature set supported by the gdb-remote server.
lldb_private::StructuredData::Array * GetSupportedStructuredDataPlugins ()
Return the array of async JSON packet types supported by the remote.
Status ConfigureRemoteStructuredData (llvm::StringRef type_name, const StructuredData::ObjectSP &config_sp)
Configure a StructuredData feature on the remote end.
llvm::Expected< TraceSupportedResponse > SendTraceSupported (std::chrono::seconds interrupt_timeout)
llvm::Error SendTraceStart (const llvm::json::Value &request, std::chrono::seconds interrupt_timeout)
llvm::Error SendTraceStop (const TraceStopRequest &request, std::chrono::seconds interrupt_timeout)
llvm::Expected< std::string > SendTraceGetState (llvm::StringRef type, std::chrono::seconds interrupt_timeout)
llvm::Expected< std::vector< uint8_t > > SendTraceGetBinaryData (const TraceGetBinaryDataRequest &request, std::chrono::seconds interrupt_timeout)
bool GetSaveCoreSupported () const
llvm::Expected< int > KillProcess (lldb::pid_t pid)
Public Member Functions inherited from lldb_private::process_gdb_remote::GDBRemoteClientBase
GDBRemoteClientBase (const char *comm_name)
bool SendAsyncSignal (int signo, std::chrono::seconds interrupt_timeout)
bool Interrupt (std::chrono::seconds interrupt_timeout)
lldb::StateType SendContinuePacketAndWaitForResponse (ContinueDelegate &delegate, const UnixSignals &signals, llvm::StringRef payload, std::chrono::seconds interrupt_timeout, StringExtractorGDBRemote &response)
PacketResult SendPacketAndWaitForResponse (llvm::StringRef payload, StringExtractorGDBRemote &response, std::chrono::seconds interrupt_timeout=std::chrono::seconds(0), bool sync_on_timeout=true)
PacketResult ReadPacketWithOutputSupport (StringExtractorGDBRemote &response, Timeout< std::micro > timeout, bool sync_on_timeout, llvm::function_ref< void(llvm::StringRef)> output_callback)
PacketResult SendPacketAndReceiveResponseWithOutputSupport (llvm::StringRef payload, StringExtractorGDBRemote &response, std::chrono::seconds interrupt_timeout, llvm::function_ref< void(llvm::StringRef)> output_callback)
Public Member Functions inherited from lldb_private::process_gdb_remote::GDBRemoteCommunication
GDBRemoteCommunication ()
~GDBRemoteCommunication () override
PacketResult GetAck ()
size_t SendAck ()
size_t SendNack ()
char CalculcateChecksum (llvm::StringRef payload)
PacketType CheckForPacket (const uint8_t *src, size_t src_len, StringExtractorGDBRemote &packet)
bool GetSendAcks ()
std::chrono::seconds SetPacketTimeout (std::chrono::seconds packet_timeout)
std::chrono::seconds GetPacketTimeout () const
void DumpHistory (Stream &strm)
Public Member Functions inherited from lldb_private::Communication
Communication ()
Construct the Communication object.
virtual ~Communication ()
Destructor.
virtual void Clear ()
lldb::ConnectionStatus Connect (const char *url, Status *error_ptr)
Connect using the current connection by passing url to its connect function.
virtual lldb::ConnectionStatus Disconnect (Status *error_ptr=nullptr)
Disconnect the communications connection if one is currently connected.
bool IsConnected () const
Check if the connection is valid.
bool HasConnection () const
lldb_private::Connection * GetConnection ()
virtual size_t Read (void *dst, size_t dst_len, const Timeout< std::micro > &timeout, lldb::ConnectionStatus &status, Status *error_ptr)
Read bytes from the current connection.
size_t Write (const void *src, size_t src_len, lldb::ConnectionStatus &status, Status *error_ptr)
The actual write function that attempts to write to the communications protocol.
size_t WriteAll (const void *src, size_t src_len, lldb::ConnectionStatus &status, Status *error_ptr)
Repeatedly attempt writing until either src_len bytes are written or a permanent failure occurs.
virtual void SetConnection (std::unique_ptr< Connection > connection)
Sets the connection that it to be used by this class.
bool GetCloseOnEOF () const
void SetCloseOnEOF (bool b)
Public Member Functions inherited from lldb_private::Broadcaster
Broadcaster (lldb::BroadcasterManagerSP manager_sp, std::string name)
Construct with a broadcaster with a name.
virtual ~Broadcaster ()
Destructor.
void CheckInWithManager ()
void BroadcastEvent (lldb::EventSP &event_sp)
Broadcast an event which has no associated data.
void BroadcastEventIfUnique (lldb::EventSP &event_sp)
void BroadcastEvent (uint32_t event_type, const lldb::EventDataSP &event_data_sp)
void BroadcastEvent (uint32_t event_type)
void BroadcastEventIfUnique (uint32_t event_type)
void Clear ()
virtual void AddInitialEventsToListener (const lldb::ListenerSP &listener_sp, uint32_t requested_events)
uint32_t AddListener (const lldb::ListenerSP &listener_sp, uint32_t event_mask)
Listen for any events specified by event_mask.
const std::string & GetBroadcasterName ()
Get this broadcaster's name.
bool GetEventNames (Stream &s, const uint32_t event_mask, bool prefix_with_broadcaster_name) const
Get the event name(s) for one or more event bits.
void SetEventName (uint32_t event_mask, const char *name)
Set the name for an event bit.
const char * GetEventName (uint32_t event_mask) const
bool EventTypeHasListeners (uint32_t event_type)
bool RemoveListener (const lldb::ListenerSP &listener_sp, uint32_t event_mask=UINT32_MAX)
Removes a Listener from this broadcasters list and frees the event bits specified by event_mask that were previously acquired by listener (assuming listener was listening to this object) for other listener objects to use.
bool HijackBroadcaster (const lldb::ListenerSP &listener_sp, uint32_t event_mask=UINT32_MAX)
Provides a simple mechanism to temporarily redirect events from broadcaster.
bool IsHijackedForEvent (uint32_t event_mask)
void RestoreBroadcaster ()
Restore the state of the Broadcaster from a previous hijack attempt.
virtual llvm::StringRef GetBroadcasterClass () const
This needs to be filled in if you are going to register the broadcaster with the broadcaster manager and do broadcaster class matching.
lldb::BroadcasterManagerSP GetManager ()
void SetPrimaryListener (lldb::ListenerSP listener_sp)
lldb::ListenerSP GetPrimaryListener ()
Protected Member Functions
bool GetCurrentProcessInfo (bool allow_lazy_pid=true)
bool GetGDBServerVersion ()
void MaybeEnableCompression (llvm::ArrayRef< llvm::StringRef > supported_compressions)
bool DecodeProcessInfoResponse (StringExtractorGDBRemote &response, ProcessInstanceInfo &process_info)
void OnRunPacketSent (bool first) override
PacketResult SendThreadSpecificPacketAndWaitForResponse (lldb::tid_t tid, StreamString &&payload, StringExtractorGDBRemote &response)
Status SendGetTraceDataPacket (StreamGDBRemote &packet, lldb::user_id_t uid, lldb::tid_t thread_id, llvm::MutableArrayRef< uint8_t > &buffer, size_t offset)
Status LoadQXferMemoryMap ()
Status GetQXferMemoryMapRegionInfo (lldb::addr_t addr, MemoryRegionInfo &region)
LazyBool GetThreadPacketSupported (lldb::tid_t tid, llvm::StringRef packetStr)
Protected Member Functions inherited from lldb_private::process_gdb_remote::GDBRemoteClientBase
PacketResult SendPacketAndWaitForResponseNoLock (llvm::StringRef payload, StringExtractorGDBRemote &response, bool sync_on_timeout=true)
Protected Member Functions inherited from lldb_private::process_gdb_remote::GDBRemoteCommunication
PacketResult SendPacketNoLock (llvm::StringRef payload)
PacketResult SendNotificationPacketNoLock (llvm::StringRef notify_type, std::deque< std::string > &queue, llvm::StringRef payload)
PacketResult SendRawPacketNoLock (llvm::StringRef payload, bool skip_ack=false)
PacketResult ReadPacket (StringExtractorGDBRemote &response, Timeout< std::micro > timeout, bool sync_on_timeout)
PacketResult WaitForPacketNoLock (StringExtractorGDBRemote &response, Timeout< std::micro > timeout, bool sync_on_timeout)
bool CompressionIsEnabled ()
bool DecompressPacket ()
Protected Member Functions inherited from lldb_private::Communication
size_t ReadFromConnection (void *dst, size_t dst_len, const Timeout< std::micro > &timeout, lldb::ConnectionStatus &status, Status *error_ptr)
Protected Member Functions inherited from lldb_private::Broadcaster
BroadcasterImplSP GetBroadcasterImpl ()
const char * GetHijackingListenerName ()
Protected Attributes
LazyBool m_supports_not_sending_acks = eLazyBoolCalculate
LazyBool m_supports_thread_suffix = eLazyBoolCalculate
LazyBool m_supports_threads_in_stop_reply = eLazyBoolCalculate
LazyBool m_supports_vCont_all = eLazyBoolCalculate
LazyBool m_supports_vCont_any = eLazyBoolCalculate
LazyBool m_supports_vCont_c = eLazyBoolCalculate
LazyBool m_supports_vCont_C = eLazyBoolCalculate
LazyBool m_supports_vCont_s = eLazyBoolCalculate
LazyBool m_supports_vCont_S = eLazyBoolCalculate
LazyBool m_qHostInfo_is_valid = eLazyBoolCalculate
LazyBool m_curr_pid_is_valid = eLazyBoolCalculate
LazyBool m_qProcessInfo_is_valid = eLazyBoolCalculate
LazyBool m_qGDBServerVersion_is_valid = eLazyBoolCalculate
LazyBool m_supports_alloc_dealloc_memory = eLazyBoolCalculate
LazyBool m_supports_memory_region_info = eLazyBoolCalculate
LazyBool m_supports_watchpoint_support_info = eLazyBoolCalculate
LazyBool m_supports_detach_stay_stopped = eLazyBoolCalculate
LazyBool m_watchpoints_trigger_after_instruction = eLazyBoolCalculate
LazyBool m_attach_or_wait_reply = eLazyBoolCalculate
LazyBool m_prepare_for_reg_writing_reply = eLazyBoolCalculate
LazyBool m_supports_p = eLazyBoolCalculate
LazyBool m_avoid_g_packets = eLazyBoolCalculate
LazyBool m_supports_QSaveRegisterState = eLazyBoolCalculate
LazyBool m_supports_qXfer_auxv_read = eLazyBoolCalculate
LazyBool m_supports_qXfer_libraries_read = eLazyBoolCalculate
LazyBool m_supports_qXfer_libraries_svr4_read = eLazyBoolCalculate
LazyBool m_supports_qXfer_features_read = eLazyBoolCalculate
LazyBool m_supports_qXfer_memory_map_read = eLazyBoolCalculate
LazyBool m_supports_qXfer_siginfo_read = eLazyBoolCalculate
LazyBool m_supports_augmented_libraries_svr4_read = eLazyBoolCalculate
LazyBool m_supports_jThreadExtendedInfo = eLazyBoolCalculate
LazyBool m_supports_jLoadedDynamicLibrariesInfos = eLazyBoolCalculate
LazyBool m_supports_jGetSharedCacheInfo = eLazyBoolCalculate
LazyBool m_supports_jGetDyldProcessState = eLazyBoolCalculate
LazyBool m_supports_QPassSignals = eLazyBoolCalculate
LazyBool m_supports_error_string_reply = eLazyBoolCalculate
LazyBool m_supports_multiprocess = eLazyBoolCalculate
LazyBool m_supports_memory_tagging = eLazyBoolCalculate
LazyBool m_supports_qSaveCore = eLazyBoolCalculate
LazyBool m_uses_native_signals = eLazyBoolCalculate
std::optional< xPacketState > m_x_packet_state
LazyBool m_supports_reverse_continue = eLazyBoolCalculate
LazyBool m_supports_reverse_step = eLazyBoolCalculate
LazyBool m_supports_multi_mem_read = eLazyBoolCalculate
bool m_supports_qProcessInfoPID: 1
bool m_supports_qfProcessInfo: 1
bool m_supports_qUserName: 1
bool m_supports_qGroupName: 1
bool m_supports_qThreadStopInfo: 1
bool m_supports_z0: 1
bool m_supports_z1: 1
bool m_supports_z2: 1
bool m_supports_z3: 1
bool m_supports_z4: 1
bool m_supports_QEnvironment: 1
bool m_supports_QEnvironmentHexEncoded: 1
bool m_supports_qSymbol: 1
bool m_qSymbol_requests_done: 1
bool m_supports_qModuleInfo: 1
bool m_supports_jThreadsInfo: 1
bool m_supports_jModulesInfo: 1
bool m_supports_vFileSize: 1
bool m_supports_vFileMode: 1
bool m_supports_vFileExists: 1
bool m_supports_vRun: 1
lldb::pid_t m_curr_pid = LLDB_INVALID_PROCESS_ID
Current gdb remote protocol process identifier for all other operations.
lldb::pid_t m_curr_pid_run = LLDB_INVALID_PROCESS_ID
Current gdb remote protocol process identifier for continue, step, etc.
lldb::tid_t m_curr_tid = LLDB_INVALID_THREAD_ID
Current gdb remote protocol thread identifier for all other operations.
lldb::tid_t m_curr_tid_run = LLDB_INVALID_THREAD_ID
Current gdb remote protocol thread identifier for continue, step, etc.
uint32_t m_num_supported_hardware_watchpoints = 0
WatchpointHardwareFeature m_watchpoint_types
uint32_t m_low_mem_addressing_bits = 0
uint32_t m_high_mem_addressing_bits = 0
ArchSpec m_host_arch
std::string m_host_distribution_id
ArchSpec m_process_arch
UUID m_process_standalone_uuid
lldb::addr_t m_process_standalone_value = LLDB_INVALID_ADDRESS
bool m_process_standalone_value_is_offset = false
std::vector< lldb::addr_t > m_binary_addresses
llvm::VersionTuple m_os_version
llvm::VersionTuple m_maccatalyst_version
std::string m_os_build
std::string m_os_kernel
std::string m_hostname
std::string m_gdb_server_name
uint32_t m_gdb_server_version
std::chrono::seconds m_default_packet_timeout
int m_target_vm_page_size = 0
uint64_t m_max_packet_size = 0
std::string m_qSupported_response
bool m_supported_async_json_packets_is_valid = false
lldb_private::StructuredData::ObjectSP m_supported_async_json_packets_sp
std::vector< MemoryRegionInfo > m_qXfer_memory_map
bool m_qXfer_memory_map_loaded = false
Protected Attributes inherited from lldb_private::process_gdb_remote::GDBRemoteCommunication
std::chrono::seconds m_packet_timeout
uint32_t m_echo_number
LazyBool m_supports_qEcho
GDBRemoteCommunicationHistory m_history
bool m_send_acks
bool m_is_platform
std::string m_bytes
std::recursive_mutex m_bytes_mutex
CompressionType m_compression_type
Protected Attributes inherited from lldb_private::Communication
lldb::ConnectionSP m_connection_sp
The connection that is current in use by this communications class.
std::mutex m_write_mutex
Don't let multiple threads write at the same time...
bool m_close_on_eof
Private Member Functions
GDBRemoteCommunicationClient (const GDBRemoteCommunicationClient &)=delete
const GDBRemoteCommunicationClient & operator= (const GDBRemoteCommunicationClient &)=delete
Additional Inherited Members
Static Public Member Functions inherited from lldb_private::process_gdb_remote::GDBRemoteCommunication
static Status StartDebugserverProcess (std::variant< llvm::StringRef, shared_fd_t > comm, ProcessLaunchInfo &launch_info, const Args *inferior_args)
static std::optional< std::string > ExpandRLE (std::string)
Expand GDB run-length encoding.
Static Public Member Functions inherited from lldb_private::Communication
static std::string ConnectionStatusAsString (lldb::ConnectionStatus status)
Protected Types inherited from lldb_private::Broadcaster
typedef std::shared_ptr< BroadcasterImpl > BroadcasterImplSP
typedef std::weak_ptr< BroadcasterImpl > BroadcasterImplWP
Detailed Description
Definition at line 60 of file GDBRemoteCommunicationClient.h.
Member Enumeration Documentation
xPacketState
enum class lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::xPacketState strong
Enumerator
Unimplemented
Prefixed
Bare
Definition at line 221 of file GDBRemoteCommunicationClient.h.
Constructor & Destructor Documentation
GDBRemoteCommunicationClient() [1/2]
GDBRemoteCommunicationClient::GDBRemoteCommunicationClient ()
Definition at line 61 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::process_gdb_remote::GDBRemoteClientBase::GDBRemoteClientBase(), m_default_packet_timeout, m_gdb_server_name, m_host_arch, m_host_distribution_id, m_hostname, m_os_build, m_os_kernel, m_process_arch, m_qSupported_response, m_qSymbol_requests_done, m_qXfer_memory_map, m_supported_async_json_packets_sp, m_supports_jModulesInfo, m_supports_jThreadsInfo, m_supports_QEnvironment, m_supports_QEnvironmentHexEncoded, m_supports_qfProcessInfo, m_supports_qGroupName, m_supports_qModuleInfo, m_supports_qProcessInfoPID, m_supports_qSymbol, m_supports_qThreadStopInfo, m_supports_qUserName, m_supports_vFileExists, m_supports_vFileMode, m_supports_vFileSize, m_supports_vRun, m_supports_z0, m_supports_z1, m_supports_z2, m_supports_z3, and m_supports_z4.
Referenced by GDBRemoteCommunicationClient(), and operator=().
~GDBRemoteCommunicationClient()
GDBRemoteCommunicationClient::~GDBRemoteCommunicationClient () override
Definition at line 81 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::Communication::Disconnect(), and lldb_private::Communication::IsConnected().
GDBRemoteCommunicationClient() [2/2]
lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GDBRemoteCommunicationClient (const GDBRemoteCommunicationClient &) private delete
References GDBRemoteCommunicationClient().
Member Function Documentation
AllocateMemory()
addr_t GDBRemoteCommunicationClient::AllocateMemory (size_t size, uint32_t permissions)
Definition at line 1474 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, StringExtractor::GetHexMaxU64(), StringExtractorGDBRemote::IsErrorResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), LLDB_INVALID_ADDRESS, m_supports_alloc_dealloc_memory, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UNUSED_IF_ASSERT_DISABLED.
AutoCompleteDiskFileOrDirectory()
void GDBRemoteCommunicationClient::AutoCompleteDiskFileOrDirectory (CompletionRequest & request, bool only_dir)
Definition at line 3201 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::CompletionRequest::AddCompletion(), lldb_private::StreamString::Clear(), StringExtractor::GetChar(), lldb_private::CompletionRequest::GetCursorArgumentPrefix(), StringExtractor::GetHexU8(), lldb_private::StreamString::GetString(), StringExtractor::Peek(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), lldb_private::Stream::PutHex32(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
AvoidGPackets()
bool GDBRemoteCommunicationClient::AvoidGPackets (ProcessGDBRemote * process)
Definition at line 3510 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb_private::Target::GetArchitecture(), GetGDBServerProgramName(), GetGDBServerProgramVersion(), lldb_private::Process::GetTarget(), lldb_private::ArchSpec::GetTriple(), lldb_private::ArchSpec::IsValid(), and m_avoid_g_packets.
Referenced by lldb_private::process_gdb_remote::GDBRemoteRegisterContext::ReadAllRegisterValues(), and lldb_private::process_gdb_remote::GDBRemoteRegisterContext::WriteAllRegisterValues().
CalculateMD5()
llvm::ErrorOr< llvm::MD5::MD5Result > GDBRemoteCommunicationClient::CalculateMD5 (const FileSpec & file_spec)
Definition at line 3444 of file GDBRemoteCommunicationClient.cpp.
References StringExtractor::GetChar(), StringExtractor::GetFilePos(), lldb_private::FileSpec::GetPath(), lldb_private::StreamString::GetString(), StringExtractor::GetStringRef(), StringExtractor::Peek(), lldb_private::Stream::PutCString(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), StringExtractor::SetFilePos(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
CloseFile()
bool GDBRemoteCommunicationClient::CloseFile (lldb::user_id_t fd, Status & error)
Definition at line 3127 of file GDBRemoteCommunicationClient.cpp.
References error(), lldb_private::StreamString::GetString(), ParseHostIOPacketResponse(), lldb_private::Stream::Printf(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by GetFileExists(), and Stat().
ConfigureRemoteStructuredData()
Status GDBRemoteCommunicationClient::ConfigureRemoteStructuredData (llvm::StringRef type_name, const StructuredData::ObjectSP & config_sp)
Configure a StructuredData feature on the remote end.
See also
Process::ConfigureStructuredData(...) for details.
Definition at line 4293 of file GDBRemoteCommunicationClient.cpp.
References error(), lldb_private::StreamString::Flush(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::StreamString::GetSize(), lldb_private::StreamString::GetString(), StringExtractor::GetStringRef(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), lldb_private::StreamGDBRemote::PutEscapedBytes(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
CreateSymlink()
Status GDBRemoteCommunicationClient::CreateSymlink (const FileSpec & src, const FileSpec & dst)
Definition at line 3347 of file GDBRemoteCommunicationClient.cpp.
References lldb::eErrorTypePOSIX, error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), gdb_errno_to_system(), StringExtractor::GetChar(), StringExtractor::GetHexMaxU32(), lldb_private::FileSpec::GetPath(), StringExtractor::GetS32(), lldb_private::StreamString::GetString(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::Status, lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UINT32_MAX.
DeallocateMemory()
bool GDBRemoteCommunicationClient::DeallocateMemory (lldb::addr_t addr)
Definition at line 1500 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, StringExtractorGDBRemote::IsOKResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), m_supports_alloc_dealloc_memory, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UNUSED_IF_ASSERT_DISABLED.
DecodeProcessInfoResponse()
bool GDBRemoteCommunicationClient::DecodeProcessInfoResponse (StringExtractorGDBRemote & response, ProcessInstanceInfo & process_info) protected
Definition at line 2016 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::Args::AppendArgument(), lldb_private::Args::Clear(), lldb_private::eArchTypeMachO, lldb_private::ProcessInfo::GetArchitecture(), lldb_private::ProcessInfo::GetArguments(), lldb_private::ProcessInfo::GetExecutableFile(), StringExtractor::GetHexByteString(), StringExtractor::GetNameColonValue(), lldb_private::ProcessInfo::GetProcessID(), lldb_private::ArchSpec::GetTriple(), StringExtractorGDBRemote::IsNormalResponse(), LLDB_INVALID_CPUTYPE, LLDB_INVALID_PROCESS_ID, lldb_private::ArchSpec::SetArchitecture(), lldb_private::ProcessInfo::SetArg0(), lldb_private::ProcessInstanceInfo::SetEffectiveGroupID(), lldb_private::ProcessInstanceInfo::SetEffectiveUserID(), lldb_private::FileSpec::SetFile(), lldb_private::ProcessInfo::SetGroupID(), lldb_private::ProcessInstanceInfo::SetParentProcessID(), lldb_private::ProcessInfo::SetProcessID(), lldb_private::ArchSpec::SetTriple(), lldb_private::ProcessInfo::SetUserID(), and UINT32_MAX.
Referenced by FindProcesses(), and GetProcessInfo().
Detach()
Status GDBRemoteCommunicationClient::Detach (bool keep_stopped, lldb::pid_t pid = LLDB_INVALID_PROCESS_ID)
Definition at line 1522 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, error(), lldb_private::Status::FromErrorString(), GetCurrentProcessID(), GetMultiprocessSupported(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsOKResponse(), LLDB_INVALID_PROCESS_ID, m_supports_detach_stay_stopped, lldb_private::Stream::PutChar(), lldb_private::Stream::PutHex64(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UNUSED_IF_ASSERT_DISABLED.
EnableErrorStringInPacket()
void GDBRemoteCommunicationClient::EnableErrorStringInPacket ()
Definition at line 617 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, StringExtractorGDBRemote::IsOKResponse(), m_supports_error_string_reply, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
FindProcesses()
uint32_t GDBRemoteCommunicationClient::FindProcesses (const ProcessInstanceInfoMatch & process_match_info, ProcessInstanceInfoList & process_infos)
Definition at line 2305 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::Contains, DecodeProcessInfoResponse(), lldb_private::ProcessInstanceInfo::EffectiveGroupIDIsValid(), lldb_private::ProcessInstanceInfo::EffectiveUserIDIsValid(), lldb_private::EndsWith, lldb_private::Equals, lldb_private::ProcessInfo::GetArchitecture(), lldb_private::ProcessInstanceInfo::GetEffectiveGroupID(), lldb_private::ProcessInstanceInfo::GetEffectiveUserID(), lldb_private::ProcessInfo::GetGroupID(), lldb_private::ProcessInstanceInfoMatch::GetMatchAllUsers(), lldb_private::ProcessInfo::GetName(), lldb_private::ProcessInstanceInfoMatch::GetNameMatchType(), lldb_private::ProcessInstanceInfo::GetParentProcessID(), lldb_private::ProcessInfo::GetProcessID(), lldb_private::ProcessInstanceInfoMatch::GetProcessInfo(), lldb_private::StreamString::GetString(), lldb_private::ArchSpec::GetTriple(), lldb_private::ProcessInfo::GetUserID(), lldb_private::ProcessInfo::GroupIDIsValid(), lldb_private::Ignore, lldb_private::ArchSpec::IsValid(), m_supports_qfProcessInfo, lldb_private::ProcessInstanceInfoMatch::MatchAllProcesses(), lldb_private::ProcessInstanceInfo::ParentProcessIDIsValid(), lldb_private::Stream::Printf(), lldb_private::ProcessInfo::ProcessIDIsValid(), lldb_private::Stream::PutBytesAsRawHex8(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), lldb_private::RegularExpression, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::StartsWith, lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and lldb_private::ProcessInfo::UserIDIsValid().
FStat()
std::optional< GDBRemoteFStatData > GDBRemoteCommunicationClient::FStat (lldb::user_id_t fd)
Definition at line 3140 of file GDBRemoteCommunicationClient.cpp.
References StringExtractor::GetChar(), StringExtractorGDBRemote::GetEscapedBinaryData(), StringExtractor::GetS64(), lldb_private::StreamString::GetString(), lldb_private::Stream::Printf(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by Stat().
GetAddressableBits()
AddressableBits GDBRemoteCommunicationClient::GetAddressableBits ()
Definition at line 1455 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, GetHostInfo(), m_high_mem_addressing_bits, m_low_mem_addressing_bits, m_qHostInfo_is_valid, and lldb_private::AddressableBits::SetAddressableBits().
GetAugmentedLibrariesSVR4ReadSupported()
bool GDBRemoteCommunicationClient::GetAugmentedLibrariesSVR4ReadSupported ()
Definition at line 140 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolYes, GetRemoteQSupported(), and m_supports_augmented_libraries_svr4_read.
GetCurrentProcessAndThreadIDs()
std::vector< std::pair< lldb::pid_t, lldb::tid_t > > GDBRemoteCommunicationClient::GetCurrentProcessAndThreadIDs (bool & sequence_mutex_unavailable)
Definition at line 2892 of file GDBRemoteCommunicationClient.cpp.
References StringExtractor::GetChar(), lldb_private::GetLog(), StringExtractorGDBRemote::GetPidTid(), lldb_private::Communication::IsConnected(), StringExtractorGDBRemote::IsNormalResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), LLDB_INVALID_PROCESS_ID, LLDB_LOG, lldb_private::process_gdb_remote::Packets, lldb_private::process_gdb_remote::Process, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponseNoLock(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by GetCurrentProcessID(), and GetCurrentThreadIDs().
GetCurrentProcessID()
lldb::pid_t GDBRemoteCommunicationClient::GetCurrentProcessID (bool allow_lazy = true)
Definition at line 758 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolYes, StringExtractor::GetChar(), GetCurrentProcessAndThreadIDs(), GetCurrentProcessInfo(), StringExtractor::GetHexMaxU64(), LLDB_INVALID_PROCESS_ID, m_curr_pid, m_curr_pid_is_valid, m_curr_pid_run, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by Detach(), and GetCurrentThreadIDs().
GetCurrentProcessInfo()
bool GDBRemoteCommunicationClient::GetCurrentProcessInfo (bool allow_lazy_pid = true) protected
Definition at line 2135 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eArchTypeCOFF, lldb_private::eArchTypeELF, lldb_private::eArchTypeMachO, lldb::eByteOrderBig, lldb::eByteOrderInvalid, lldb::eByteOrderLittle, lldb::eByteOrderPDP, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, GetGDBServerVersion(), StringExtractor::GetHexByteString(), GetHostInfo(), lldb_private::GetLog(), StringExtractor::GetNameColonValue(), StringExtractor::GetU64(), StringExtractorGDBRemote::IsNormalResponse(), LLDB_INVALID_ADDRESS, LLDB_INVALID_CPUTYPE, LLDB_INVALID_PROCESS_ID, LLDB_LOGF, m_binary_addresses, m_curr_pid, m_curr_pid_is_valid, m_curr_pid_run, m_gdb_server_version, m_process_arch, m_process_standalone_uuid, m_process_standalone_value, m_process_standalone_value_is_offset, m_qProcessInfo_is_valid, lldb_private::process_gdb_remote::Packets, ParseOSType(), lldb_private::process_gdb_remote::Process, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by GetCurrentProcessID(), GetProcessArchitecture(), GetProcessStandaloneBinaries(), and GetProcessStandaloneBinary().
GetCurrentThreadIDs()
size_t GDBRemoteCommunicationClient::GetCurrentThreadIDs (std::vector< lldb::tid_t > & thread_ids, bool & sequence_mutex_unavailable)
Definition at line 2948 of file GDBRemoteCommunicationClient.cpp.
References StringExtractorGDBRemote::AllThreads, GetCurrentProcessAndThreadIDs(), GetCurrentProcessID(), LLDB_INVALID_PROCESS_ID, and LLDB_INVALID_THREAD_ID.
GetDefaultThreadId()
bool GDBRemoteCommunicationClient::GetDefaultThreadId (lldb::tid_t & tid)
Definition at line 1188 of file GDBRemoteCommunicationClient.cpp.
References StringExtractorGDBRemote::AllProcesses, lldb_private::eLazyBoolYes, StringExtractor::GetChar(), StringExtractorGDBRemote::GetPidTid(), StringExtractorGDBRemote::IsNormalResponse(), m_curr_pid, m_curr_pid_is_valid, m_curr_pid_run, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetDynamicLoaderProcessStateSupported()
bool GDBRemoteCommunicationClient::GetDynamicLoaderProcessStateSupported ()
Definition at line 660 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, StringExtractorGDBRemote::IsUnsupportedResponse(), m_supports_jGetDyldProcessState, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetEchoSupported()
bool GDBRemoteCommunicationClient::GetEchoSupported ()
Definition at line 126 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolYes, GetRemoteQSupported(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::m_supports_qEcho.
GetFileExists()
bool GDBRemoteCommunicationClient::GetFileExists (const FileSpec & file_spec)
Definition at line 3413 of file GDBRemoteCommunicationClient.cpp.
References CloseFile(), lldb_private::File::eOpenOptionReadOnly, error(), StringExtractor::GetChar(), lldb_private::FileSpec::GetPath(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsUnsupportedResponse(), m_supports_vFileExists, OpenFile(), lldb_private::Stream::PutCString(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UINT64_MAX.
GetFilePermissions()
Status GDBRemoteCommunicationClient::GetFilePermissions (const FileSpec & file_spec, uint32_t & file_permissions)
Definition at line 3227 of file GDBRemoteCommunicationClient.cpp.
References lldb::eErrorTypePOSIX, error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), gdb_errno_to_system(), StringExtractor::GetChar(), lldb_private::StreamString::GetData(), lldb_private::FileSpec::GetPath(), StringExtractor::GetS32(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsUnsupportedResponse(), m_supports_vFileMode, lldb_private::Stream::PutCString(), lldb_private::Stream::PutStringAsRawHex8(), S_IRWXG, S_IRWXO, S_IRWXU, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), Stat(), lldb_private::Status, and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetFileSize()
lldb::user_id_t GDBRemoteCommunicationClient::GetFileSize (const FileSpec & file_spec)
Definition at line 3175 of file GDBRemoteCommunicationClient.cpp.
References StringExtractor::GetChar(), StringExtractor::GetHexMaxU64(), lldb_private::FileSpec::GetPath(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsUnsupportedResponse(), m_supports_vFileSize, lldb_private::Stream::PutCString(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), Stat(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UINT64_MAX.
GetGDBServerProgramName()
const char * GDBRemoteCommunicationClient::GetGDBServerProgramName ()
Definition at line 1174 of file GDBRemoteCommunicationClient.cpp.
References GetGDBServerVersion(), and m_gdb_server_name.
Referenced by AvoidGPackets().
GetGDBServerProgramVersion()
uint32_t GDBRemoteCommunicationClient::GetGDBServerProgramVersion ()
Definition at line 1182 of file GDBRemoteCommunicationClient.cpp.
References GetGDBServerVersion(), and m_gdb_server_version.
Referenced by AvoidGPackets().
GetGDBServerVersion()
bool GDBRemoteCommunicationClient::GetGDBServerVersion () protected
Definition at line 1072 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, StringExtractor::GetNameColonValue(), StringExtractorGDBRemote::IsNormalResponse(), m_gdb_server_name, m_gdb_server_version, m_qGDBServerVersion_is_valid, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by GetCurrentProcessInfo(), GetGDBServerProgramName(), and GetGDBServerProgramVersion().
GetGroupName()
bool GDBRemoteCommunicationClient::GetGroupName (uint32_t gid, std::string & name)
Definition at line 2427 of file GDBRemoteCommunicationClient.cpp.
References StringExtractor::GetHexByteString(), StringExtractor::GetStringRef(), StringExtractorGDBRemote::IsNormalResponse(), m_supports_qGroupName, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UNUSED_IF_ASSERT_DISABLED.
GetHostArchitecture()
const lldb_private::ArchSpec & GDBRemoteCommunicationClient::GetHostArchitecture ()
Definition at line 1449 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, GetHostInfo(), m_host_arch, and m_qHostInfo_is_valid.
Referenced by GetWorkingDir().
GetHostDefaultPacketTimeout()
seconds GDBRemoteCommunicationClient::GetHostDefaultPacketTimeout ()
Definition at line 1468 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, GetHostInfo(), m_default_packet_timeout, and m_qHostInfo_is_valid.
GetHostInfo()
bool GDBRemoteCommunicationClient::GetHostInfo (bool force = false)
Definition at line 1232 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eArchTypeMachO, lldb::eByteOrderBig, lldb::eByteOrderInvalid, lldb::eByteOrderLittle, lldb::eByteOrderPDP, lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, StringExtractor::GetHexByteString(), lldb_private::GetLog(), StringExtractor::GetNameColonValue(), StringExtractorGDBRemote::IsNormalResponse(), LLDB_INVALID_CPUTYPE, LLDB_LOGF, m_default_packet_timeout, m_high_mem_addressing_bits, m_host_arch, m_host_distribution_id, m_hostname, m_low_mem_addressing_bits, m_maccatalyst_version, m_os_build, m_os_kernel, m_os_version, m_qHostInfo_is_valid, m_target_vm_page_size, m_watchpoints_trigger_after_instruction, ParseOSType(), lldb_private::process_gdb_remote::Process, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SetPacketTimeout(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by GetAddressableBits(), GetCurrentProcessInfo(), GetHostArchitecture(), GetHostDefaultPacketTimeout(), GetHostname(), GetMacCatalystVersion(), GetOSBuildString(), GetOSKernelDescription(), GetOSVersion(), GetSystemArchitecture(), and GetWatchpointReportedAfter().
GetHostname()
bool GDBRemoteCommunicationClient::GetHostname (std::string & s)
Definition at line 1024 of file GDBRemoteCommunicationClient.cpp.
References GetHostInfo(), and m_hostname.
GetListThreadsInStopReplySupported()
void GDBRemoteCommunicationClient::GetListThreadsInStopReplySupported ()
Definition at line 244 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, StringExtractorGDBRemote::IsOKResponse(), m_supports_threads_in_stop_reply, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetLoadedDynamicLibrariesInfosSupported()
bool GDBRemoteCommunicationClient::GetLoadedDynamicLibrariesInfosSupported ()
Definition at line 632 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, StringExtractorGDBRemote::IsOKResponse(), m_supports_jLoadedDynamicLibrariesInfos, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetMacCatalystVersion()
llvm::VersionTuple GDBRemoteCommunicationClient::GetMacCatalystVersion ()
Definition at line 1002 of file GDBRemoteCommunicationClient.cpp.
References GetHostInfo(), and m_maccatalyst_version.
GetMemoryRegionInfo()
Status GDBRemoteCommunicationClient::GetMemoryRegionInfo (lldb::addr_t addr, lldb_private::MemoryRegionInfo & region_info)
Definition at line 1575 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::MemoryRegionInfo::Clear(), lldb_private::Range< B, S >::Contains(), lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb_private::MemoryRegionInfo::eNo, StringExtractorGDBRemote::eResponse, error(), lldb_private::MemoryRegionInfo::eYes, lldb_private::Status::FromErrorString(), lldb_private::MemoryRegionInfo::GetBlocksize(), lldb_private::MemoryRegionInfo::GetFlash(), StringExtractor::GetHexByteString(), StringExtractor::GetNameColonValue(), GetQXferMemoryMapRegionInfo(), lldb_private::MemoryRegionInfo::GetRange(), lldb_private::Range< B, S >::GetRangeBase(), lldb_private::Range< B, S >::GetRangeEnd(), StringExtractorGDBRemote::GetResponseType(), lldb_private::Range< B, S >::IsValid(), LLDB_INVALID_ADDRESS, m_supports_memory_region_info, m_target_vm_page_size, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::MemoryRegionInfo::SetBlocksize(), lldb_private::Range< B, S >::SetByteSize(), lldb_private::MemoryRegionInfo::SetDirtyPageList(), lldb_private::MemoryRegionInfo::SetExecutable(), lldb_private::MemoryRegionInfo::SetFlash(), lldb_private::MemoryRegionInfo::SetIsShadowStack(), lldb_private::MemoryRegionInfo::SetIsStackMemory(), lldb_private::MemoryRegionInfo::SetMapped(), lldb_private::MemoryRegionInfo::SetMemoryTagged(), lldb_private::MemoryRegionInfo::SetName(), lldb_private::MemoryRegionInfo::SetPageSize(), lldb_private::Range< B, S >::SetRangeBase(), lldb_private::Range< B, S >::SetRangeEnd(), lldb_private::MemoryRegionInfo::SetReadable(), lldb_private::MemoryRegionInfo::SetWritable(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, lldb_private::Status::Success(), and UNUSED_IF_ASSERT_DISABLED.
GetMemoryTaggingSupported()
bool GDBRemoteCommunicationClient::GetMemoryTaggingSupported ()
Definition at line 673 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolYes, GetRemoteQSupported(), and m_supports_memory_tagging.
GetModuleInfo()
bool GDBRemoteCommunicationClient::GetModuleInfo (const FileSpec & module_file_spec, const ArchSpec & arch_spec, ModuleSpec & module_spec)
Definition at line 3851 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::ModuleSpec::Clear(), lldb_private::ModuleSpec::GetArchitecture(), lldb_private::ModuleSpec::GetFileSpec(), StringExtractor::GetHexByteString(), StringExtractor::GetNameColonValue(), lldb_private::FileSpec::GetPath(), lldb_private::StreamString::GetString(), lldb_private::ArchSpec::GetTriple(), lldb_private::ModuleSpec::GetUUID(), StringExtractorGDBRemote::IsErrorResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), m_supports_qModuleInfo, lldb_private::Stream::PutCString(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::UUID::SetFromStringRef(), lldb_private::ModuleSpec::SetObjectOffset(), lldb_private::ModuleSpec::SetObjectSize(), lldb_private::ArchSpec::SetTriple(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetModulesInfo()
std::optional< std::vector< ModuleSpec > > GDBRemoteCommunicationClient::GetModulesInfo (llvm::ArrayRef< FileSpec > module_file_specs, const llvm::Triple & triple)
Definition at line 3951 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::Stream::AsRawOstream(), lldb_private::StructuredData::Array::GetItemAtIndex(), lldb_private::StreamString::GetSize(), lldb_private::StructuredData::Array::GetSize(), lldb_private::StreamString::GetString(), StringExtractor::GetStringRef(), StringExtractorGDBRemote::IsErrorResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), m_supports_jModulesInfo, lldb_private::StructuredData::ParseJSON(), ParseModuleSpec(), lldb_private::Stream::PutCString(), lldb_private::StreamGDBRemote::PutEscapedBytes(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetMultiMemReadSupported()
bool GDBRemoteCommunicationClient::GetMultiMemReadSupported ()
Definition at line 214 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolYes, GetRemoteQSupported(), and m_supports_multi_mem_read.
GetMultiprocessSupported()
bool GDBRemoteCommunicationClient::GetMultiprocessSupported ()
Definition at line 189 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolYes, GetRemoteQSupported(), m_supports_memory_tagging, and m_supports_multiprocess.
Referenced by Detach().
GetOSBuildString()
std::optional< std::string > GDBRemoteCommunicationClient::GetOSBuildString ()
Definition at line 1007 of file GDBRemoteCommunicationClient.cpp.
References GetHostInfo(), and m_os_build.
GetOSKernelDescription()
std::optional< std::string > GDBRemoteCommunicationClient::GetOSKernelDescription ()
Definition at line 1016 of file GDBRemoteCommunicationClient.cpp.
References GetHostInfo(), and m_os_kernel.
GetOSVersion()
llvm::VersionTuple GDBRemoteCommunicationClient::GetOSVersion ()
Definition at line 997 of file GDBRemoteCommunicationClient.cpp.
References GetHostInfo(), and m_os_version.
GetpPacketSupported()
bool GDBRemoteCommunicationClient::GetpPacketSupported (lldb::tid_t tid)
Definition at line 561 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, GetThreadPacketSupported(), and m_supports_p.
Referenced by lldb_private::process_gdb_remote::ThreadGDBRemote::CreateRegisterContextForFrame().
GetProcessArchitecture()
const lldb_private::ArchSpec & GDBRemoteCommunicationClient::GetProcessArchitecture ()
Definition at line 1042 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, GetCurrentProcessInfo(), m_process_arch, and m_qProcessInfo_is_valid.
GetProcessInfo()
bool GDBRemoteCommunicationClient::GetProcessInfo (lldb::pid_t pid, ProcessInstanceInfo & process_info)
Definition at line 2113 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::ProcessInstanceInfo::Clear(), DecodeProcessInfoResponse(), m_supports_qProcessInfoPID, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UNUSED_IF_ASSERT_DISABLED.
GetProcessStandaloneBinaries()
std::vector< addr_t > GDBRemoteCommunicationClient::GetProcessStandaloneBinaries ()
Definition at line 1066 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, GetCurrentProcessInfo(), m_binary_addresses, and m_qProcessInfo_is_valid.
GetProcessStandaloneBinary()
bool GDBRemoteCommunicationClient::GetProcessStandaloneBinary (UUID & uuid, lldb::addr_t & value, bool & value_is_offset)
Definition at line 1048 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, GetCurrentProcessInfo(), LLDB_INVALID_ADDRESS, m_process_standalone_uuid, m_process_standalone_value, m_process_standalone_value_is_offset, and m_qProcessInfo_is_valid.
GetQOffsets()
std::optional< QOffsets > GDBRemoteCommunicationClient::GetQOffsets ()
Use qOffsets to query the offset used when relocating the target executable.
If successful, the returned structure will contain at least one value in the offsets field.
Definition at line 3811 of file GDBRemoteCommunicationClient.cpp.
References StringExtractor::GetStringRef(), StringExtractorGDBRemote::IsNormalResponse(), lldb_private::process_gdb_remote::QOffsets::offsets, lldb_private::process_gdb_remote::QOffsets::segments, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetQPassSignalsSupported()
bool GDBRemoteCommunicationClient::GetQPassSignalsSupported ()
Definition at line 133 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolYes, GetRemoteQSupported(), and m_supports_QPassSignals.
GetQXferAuxvReadSupported()
bool GDBRemoteCommunicationClient::GetQXferAuxvReadSupported ()
Definition at line 161 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolYes, GetRemoteQSupported(), and m_supports_qXfer_auxv_read.
GetQXferFeaturesReadSupported()
bool GDBRemoteCommunicationClient::GetQXferFeaturesReadSupported ()
Definition at line 168 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolYes, GetRemoteQSupported(), and m_supports_qXfer_features_read.
GetQXferLibrariesReadSupported()
bool GDBRemoteCommunicationClient::GetQXferLibrariesReadSupported ()
Definition at line 154 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolYes, GetRemoteQSupported(), and m_supports_qXfer_libraries_read.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::GetLoadedModuleList().
GetQXferLibrariesSVR4ReadSupported()
bool GDBRemoteCommunicationClient::GetQXferLibrariesSVR4ReadSupported ()
Definition at line 147 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolYes, GetRemoteQSupported(), and m_supports_qXfer_libraries_svr4_read.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::GetLoadedModuleList().
GetQXferMemoryMapReadSupported()
bool GDBRemoteCommunicationClient::GetQXferMemoryMapReadSupported ()
Definition at line 175 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolYes, GetRemoteQSupported(), and m_supports_qXfer_memory_map_read.
Referenced by LoadQXferMemoryMap().
GetQXferMemoryMapRegionInfo()
Status GDBRemoteCommunicationClient::GetQXferMemoryMapRegionInfo (lldb::addr_t addr, MemoryRegionInfo & region) protected
Definition at line 1734 of file GDBRemoteCommunicationClient.cpp.
References error(), lldb_private::Status::FromErrorString(), LoadQXferMemoryMap(), and m_qXfer_memory_map.
Referenced by GetMemoryRegionInfo().
GetQXferSigInfoReadSupported()
bool GDBRemoteCommunicationClient::GetQXferSigInfoReadSupported ()
Definition at line 182 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolYes, GetRemoteQSupported(), and m_supports_qXfer_siginfo_read.
Referenced by lldb_private::process_gdb_remote::ThreadGDBRemote::GetSiginfo().
GetRemoteMaxPacketSize()
uint64_t GDBRemoteCommunicationClient::GetRemoteMaxPacketSize ()
Definition at line 195 of file GDBRemoteCommunicationClient.cpp.
References GetRemoteQSupported(), and m_max_packet_size.
Referenced by ReadExtFeature().
GetRemoteQSupported()
void GDBRemoteCommunicationClient::GetRemoteQSupported ()
Definition at line 357 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, StringExtractor::GetHexMaxU64(), lldb_private::GetLog(), lldb_private::StreamString::GetString(), StringExtractor::GetStringRef(), LLDB_LOGF, m_max_packet_size, m_qSupported_response, m_supports_augmented_libraries_svr4_read, m_supports_memory_tagging, m_supports_multi_mem_read, m_supports_multiprocess, lldb_private::process_gdb_remote::GDBRemoteCommunication::m_supports_qEcho, m_supports_QPassSignals, m_supports_qSaveCore, m_supports_qXfer_auxv_read, m_supports_qXfer_features_read, m_supports_qXfer_libraries_read, m_supports_qXfer_libraries_svr4_read, m_supports_qXfer_memory_map_read, m_supports_qXfer_siginfo_read, m_supports_reverse_continue, m_supports_reverse_step, m_uses_native_signals, m_watchpoint_types, m_x_packet_state, MaybeEnableCompression(), Prefixed, lldb_private::process_gdb_remote::Process, lldb_private::Stream::PutCString(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UINT64_MAX.
Referenced by GetAugmentedLibrariesSVR4ReadSupported(), GetEchoSupported(), GetMemoryTaggingSupported(), GetMultiMemReadSupported(), GetMultiprocessSupported(), GetQPassSignalsSupported(), GetQXferAuxvReadSupported(), GetQXferFeaturesReadSupported(), GetQXferLibrariesReadSupported(), GetQXferLibrariesSVR4ReadSupported(), GetQXferMemoryMapReadSupported(), GetQXferSigInfoReadSupported(), GetRemoteMaxPacketSize(), GetReverseContinueSupported(), GetReverseStepSupported(), GetxPacketState(), and UsesNativeSignals().
GetReverseContinueSupported()
bool GDBRemoteCommunicationClient::GetReverseContinueSupported ()
Definition at line 202 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolYes, GetRemoteQSupported(), and m_supports_reverse_continue.
GetReverseStepSupported()
bool GDBRemoteCommunicationClient::GetReverseStepSupported ()
Definition at line 208 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolYes, GetRemoteQSupported(), and m_supports_reverse_step.
GetSaveCoreSupported()
bool GDBRemoteCommunicationClient::GetSaveCoreSupported () const
Definition at line 580 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolYes, and m_supports_qSaveCore.
GetServerSupportedFeatures()
const std::string & lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetServerSupportedFeatures () const inline
Return the feature set supported by the gdb-remote server.
This method returns the remote side's response to the qSupported packet. The response is the complete string payload returned to the client.
Returns
The string returned by the server to the qSupported query.
Definition at line 484 of file GDBRemoteCommunicationClient.h.
References m_qSupported_response.
GetSharedCacheInfoSupported()
bool GDBRemoteCommunicationClient::GetSharedCacheInfoSupported ()
Definition at line 646 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, StringExtractorGDBRemote::IsOKResponse(), m_supports_jGetSharedCacheInfo, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetShlibInfoAddr()
lldb::addr_t GDBRemoteCommunicationClient::GetShlibInfoAddr ()
Definition at line 2969 of file GDBRemoteCommunicationClient.cpp.
References StringExtractor::GetHexMaxU64(), StringExtractorGDBRemote::IsNormalResponse(), LLDB_INVALID_ADDRESS, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetStopReply()
bool GDBRemoteCommunicationClient::GetStopReply (StringExtractorGDBRemote & response)
Definition at line 2800 of file GDBRemoteCommunicationClient.cpp.
References StringExtractorGDBRemote::IsNormalResponse(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetSupportedStructuredDataPlugins()
StructuredData::Array * GDBRemoteCommunicationClient::GetSupportedStructuredDataPlugins ()
Return the array of async JSON packet types supported by the remote.
This method returns the remote side's array of supported JSON packet types as a list of type names. Each of the results are expected to have an Enable{type_name} command to enable and configure the related feature. Each type_name for an enabled feature will possibly send async-style packets that contain a payload of a binhex-encoded JSON dictionary. The dictionary will have a string field named 'type', that contains the type_name of the supported packet type.
There is a Plugin category called structured-data plugins. A plugin indicates whether it knows how to handle a type_name. If so, it can be used to process the async JSON packet.
Returns
The string returned by the server to the qSupported query.
Definition at line 4226 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::StreamString::GetData(), lldb_private::GetLog(), StringExtractor::GetStringRef(), LLDB_LOGF, m_supported_async_json_packets_is_valid, m_supported_async_json_packets_sp, lldb_private::StructuredData::ParseJSON(), lldb_private::process_gdb_remote::Process, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetSupportedWatchpointTypes()
WatchpointHardwareFeature GDBRemoteCommunicationClient::GetSupportedWatchpointTypes ()
Definition at line 1865 of file GDBRemoteCommunicationClient.cpp.
References m_watchpoint_types.
GetSyncThreadStateSupported()
bool GDBRemoteCommunicationClient::GetSyncThreadStateSupported ()
Definition at line 271 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, StringExtractorGDBRemote::IsOKResponse(), m_prepare_for_reg_writing_reply, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by SyncThreadState().
GetSystemArchitecture()
ArchSpec GDBRemoteCommunicationClient::GetSystemArchitecture ()
Definition at line 1035 of file GDBRemoteCommunicationClient.cpp.
References GetHostInfo(), and m_host_arch.
GetThreadExtendedInfoSupported()
bool GDBRemoteCommunicationClient::GetThreadExtendedInfoSupported ()
Definition at line 603 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, StringExtractorGDBRemote::IsOKResponse(), m_supports_jThreadExtendedInfo, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetThreadPacketSupported()
LazyBool GDBRemoteCommunicationClient::GetThreadPacketSupported (lldb::tid_t tid, llvm::StringRef packetStr) protected
Definition at line 567 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, StringExtractorGDBRemote::IsNormalResponse(), lldb_private::Stream::PutCString(), SendThreadSpecificPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by GetpPacketSupported().
GetThreadsInfo()
StructuredData::ObjectSP GDBRemoteCommunicationClient::GetThreadsInfo ()
Definition at line 584 of file GDBRemoteCommunicationClient.cpp.
References StringExtractor::Empty(), StringExtractor::GetStringRef(), StringExtractorGDBRemote::IsUnsupportedResponse(), m_supports_jThreadsInfo, lldb_private::StructuredData::ParseJSON(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), StringExtractorGDBRemote::SetResponseValidatorToJSON(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetThreadStopInfo()
bool GDBRemoteCommunicationClient::GetThreadStopInfo (lldb::tid_t tid, StringExtractorGDBRemote & response)
Definition at line 2807 of file GDBRemoteCommunicationClient.cpp.
References StringExtractorGDBRemote::IsNormalResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), m_supports_qThreadStopInfo, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UNUSED_IF_ASSERT_DISABLED.
GetThreadSuffixSupported()
bool GDBRemoteCommunicationClient::GetThreadSuffixSupported ()
Definition at line 471 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, StringExtractorGDBRemote::IsOKResponse(), m_supports_thread_suffix, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by SendThreadSpecificPacketAndWaitForResponse(), and UsesNativeSignals().
GetUserName()
bool GDBRemoteCommunicationClient::GetUserName (uint32_t uid, std::string & name)
Definition at line 2400 of file GDBRemoteCommunicationClient.cpp.
References StringExtractor::GetHexByteString(), StringExtractor::GetStringRef(), StringExtractorGDBRemote::IsNormalResponse(), m_supports_qUserName, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UNUSED_IF_ASSERT_DISABLED.
GetVAttachOrWaitSupported()
bool GDBRemoteCommunicationClient::GetVAttachOrWaitSupported ()
Definition at line 257 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, StringExtractorGDBRemote::IsOKResponse(), m_attach_or_wait_reply, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetVContSupported()
bool GDBRemoteCommunicationClient::GetVContSupported (llvm::StringRef flavor)
Definition at line 484 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, StringExtractor::GetStringRef(), m_supports_vCont_all, m_supports_vCont_any, m_supports_vCont_C, m_supports_vCont_c, m_supports_vCont_S, m_supports_vCont_s, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by HasAnyVContSupport(), and HasFullVContSupport().
GetWatchpointReportedAfter()
std::optional< bool > GDBRemoteCommunicationClient::GetWatchpointReportedAfter ()
Definition at line 1869 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, GetHostInfo(), m_qHostInfo_is_valid, and m_watchpoints_trigger_after_instruction.
GetWatchpointSlotCount()
std::optional< uint32_t > GDBRemoteCommunicationClient::GetWatchpointSlotCount ()
Definition at line 1834 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, StringExtractor::GetNameColonValue(), m_num_supported_hardware_watchpoints, m_supports_watchpoint_support_info, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetWorkingDir()
bool GDBRemoteCommunicationClient::GetWorkingDir (FileSpec & working_dir)
Gets the current working directory of a remote platform GDB server.
Parameters
[out] working_dir The current working directory on the remote platform.
Returns
Boolean for success
Definition at line 1946 of file GDBRemoteCommunicationClient.cpp.
References StringExtractor::GetHexByteString(), GetHostArchitecture(), StringExtractorGDBRemote::IsErrorResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::FileSpec::SetFile(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
GetxPacketState()
GDBRemoteCommunicationClient::xPacketState GDBRemoteCommunicationClient::GetxPacketState ()
Definition at line 743 of file GDBRemoteCommunicationClient.cpp.
References Bare, GetRemoteQSupported(), StringExtractorGDBRemote::IsOKResponse(), m_x_packet_state, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and Unimplemented.
HandshakeWithServer()
bool GDBRemoteCommunicationClient::HandshakeWithServer (Status * error_ptr)
Definition at line 86 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::Communication::IsConnected(), QueryNoAckModeSupported(), ResetDiscoverableSettings(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::SendAck().
HasAnyVContSupport()
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::HasAnyVContSupport () inline
Definition at line 267 of file GDBRemoteCommunicationClient.h.
References GetVContSupported().
HasFullVContSupport()
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::HasFullVContSupport () inline
Definition at line 265 of file GDBRemoteCommunicationClient.h.
References GetVContSupported().
KillProcess()
llvm::Expected< int > GDBRemoteCommunicationClient::KillProcess (lldb::pid_t pid)
Definition at line 4358 of file GDBRemoteCommunicationClient.cpp.
References StringExtractor::GetChar(), StringExtractor::GetHexU8(), lldb_private::process_gdb_remote::GDBRemoteCommunication::GetPacketTimeout(), StringExtractor::GetStringRef(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
KillSpawnedProcess()
bool GDBRemoteCommunicationClient::KillSpawnedProcess (lldb::pid_t pid)
Definition at line 2724 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsOKResponse(), lldb_private::Stream::Printf(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
LaunchGDBServer()
bool GDBRemoteCommunicationClient::LaunchGDBServer (const char * remote_accept_hostname, lldb::pid_t & pid, uint16_t & port, std::string & socket_name)
Definition at line 2635 of file GDBRemoteCommunicationClient.cpp.
References StringExtractor::GetHexByteString(), StringExtractor::GetNameColonValue(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsErrorResponse(), LLDB_INVALID_PROCESS_ID, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
LaunchProcess()
llvm::Error GDBRemoteCommunicationClient::LaunchProcess (const Args & args)
Launch the process using the provided arguments.
Parameters
[in] args A list of program arguments. The first entry is the program being run.
Definition at line 807 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::Stream::Format(), lldb_private::Args::GetArgumentAtIndex(), StringExtractor::GetChar(), StringExtractorGDBRemote::GetStatus(), lldb_private::StreamString::GetString(), StringExtractor::GetStringRef(), StringExtractorGDBRemote::IsErrorResponse(), StringExtractorGDBRemote::IsOKResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), m_supports_vRun, lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and lldb_private::Status::ToError().
LoadQXferMemoryMap()
Status GDBRemoteCommunicationClient::LoadQXferMemoryMap () protected
Definition at line 1749 of file GDBRemoteCommunicationClient.cpp.
References error(), lldb_private::MemoryRegionInfo::eYes, lldb_private::XMLNode::ForEachChildElement(), lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), lldb_private::XMLNode::GetAttributeValue(), lldb_private::XMLNode::GetAttributeValueAsUnsigned(), lldb_private::XMLNode::GetElementTextAsUnsigned(), lldb_private::XMLNode::GetName(), GetQXferMemoryMapReadSupported(), lldb_private::MemoryRegionInfo::GetRange(), lldb_private::XMLDocument::GetRootElement(), lldb_private::XMLNode::IsElement(), m_qXfer_memory_map, m_qXfer_memory_map_loaded, lldb_private::XMLDocument::ParseMemory(), ReadExtFeature(), lldb_private::MemoryRegionInfo::SetBlocksize(), lldb_private::Range< B, S >::SetByteSize(), lldb_private::MemoryRegionInfo::SetFlash(), lldb_private::Range< B, S >::SetRangeBase(), lldb_private::MemoryRegionInfo::SetReadable(), lldb_private::MemoryRegionInfo::SetWritable(), and lldb_private::XMLDocument::XMLEnabled().
Referenced by GetQXferMemoryMapRegionInfo().
MakeDirectory()
Status GDBRemoteCommunicationClient::MakeDirectory (const FileSpec & file_spec, uint32_t mode)
Definition at line 3031 of file GDBRemoteCommunicationClient.cpp.
References lldb::eErrorTypePOSIX, lldb_private::Status::FromErrorStringWithFormat(), StringExtractor::GetChar(), StringExtractor::GetHexMaxU32(), lldb_private::FileSpec::GetPath(), lldb_private::StreamString::GetString(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), lldb_private::Stream::PutHex32(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::Status, lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UINT32_MAX.
MaybeEnableCompression()
void GDBRemoteCommunicationClient::MaybeEnableCompression (llvm::ArrayRef< llvm::StringRef > supported_compressions) protected
Definition at line 1103 of file GDBRemoteCommunicationClient.cpp.
References StringExtractorGDBRemote::IsOKResponse(), lldb_private::process_gdb_remote::LZ4, lldb_private::process_gdb_remote::LZFSE, lldb_private::process_gdb_remote::LZMA, lldb_private::process_gdb_remote::GDBRemoteCommunication::m_compression_type, lldb_private::process_gdb_remote::None, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and lldb_private::process_gdb_remote::ZlibDeflate.
Referenced by GetRemoteQSupported().
OnRunPacketSent()
void GDBRemoteCommunicationClient::OnRunPacketSent (bool first) override protected virtual
Reimplemented from lldb_private::process_gdb_remote::GDBRemoteClientBase.
Definition at line 4342 of file GDBRemoteCommunicationClient.cpp.
References LLDB_INVALID_THREAD_ID, m_curr_tid, and lldb_private::process_gdb_remote::GDBRemoteClientBase::OnRunPacketSent().
OpenFile()
lldb::user_id_t GDBRemoteCommunicationClient::OpenFile (const FileSpec & file_spec, File::OpenOptions flags, mode_t mode, Status & error)
Definition at line 3106 of file GDBRemoteCommunicationClient.cpp.
References error(), lldb_private::FileSpec::GetPath(), lldb_private::StreamString::GetString(), ParseHostIOPacketResponse(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), lldb_private::Stream::PutHex32(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UINT64_MAX.
Referenced by GetFileExists(), and Stat().
operator=()
const GDBRemoteCommunicationClient & lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::operator= (const GDBRemoteCommunicationClient &) private delete
References GDBRemoteCommunicationClient().
QueryGDBServer()
size_t GDBRemoteCommunicationClient::QueryGDBServer (std::vector< std::pair< uint16_t, std::string > > & connection_urls)
Definition at line 2683 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::StructuredData::Array::GetItemAtIndexAsDictionary(), lldb_private::StructuredData::Array::GetSize(), StringExtractor::GetStringRef(), lldb_private::StructuredData::Dictionary::GetValueForKey(), lldb_private::StructuredData::ParseJSON(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
QueryNoAckModeSupported()
bool GDBRemoteCommunicationClient::QueryNoAckModeSupported ()
Definition at line 220 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb_private::process_gdb_remote::GDBRemoteCommunication::GetPacketTimeout(), StringExtractorGDBRemote::IsOKResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::m_send_acks, m_supports_not_sending_acks, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by HandshakeWithServer().
ReadAllRegisters()
DataBufferSP GDBRemoteCommunicationClient::ReadAllRegisters (lldb::tid_t tid)
Definition at line 3552 of file GDBRemoteCommunicationClient.cpp.
References StringExtractor::GetHexBytes(), StringExtractor::GetStringRef(), StringExtractorGDBRemote::IsNormalResponse(), lldb_private::Stream::PutChar(), SendThreadSpecificPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by lldb_private::process_gdb_remote::GDBRemoteRegisterContext::ReadAllRegisterValues(), and lldb_private::process_gdb_remote::GDBRemoteRegisterContext::ReadRegisterBytes().
ReadExtFeature()
llvm::Expected< std::string > GDBRemoteCommunicationClient::ReadExtFeature (llvm::StringRef object, llvm::StringRef annex)
Definition at line 4010 of file GDBRemoteCommunicationClient.cpp.
References GetRemoteMaxPacketSize(), StringExtractor::GetStringRef(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::GetLoadedModuleList(), lldb_private::process_gdb_remote::ThreadGDBRemote::GetSiginfo(), and LoadQXferMemoryMap().
ReadFile()
uint64_t GDBRemoteCommunicationClient::ReadFile (lldb::user_id_t fd, uint64_t offset, void * dst, uint64_t dst_len, Status & error)
Definition at line 3275 of file GDBRemoteCommunicationClient.cpp.
References lldb::eErrorTypePOSIX, error(), lldb_private::Status::FromErrorString(), gdb_errno_to_system(), StringExtractor::GetChar(), StringExtractorGDBRemote::GetEscapedBinaryData(), StringExtractor::GetS32(), StringExtractor::GetS64(), lldb_private::StreamString::GetString(), StringExtractor::Peek(), lldb_private::Stream::Printf(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::Status, and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
ReadMemoryTags()
DataBufferSP GDBRemoteCommunicationClient::ReadMemoryTags (lldb::addr_t addr, size_t len, int32_t type)
Definition at line 680 of file GDBRemoteCommunicationClient.cpp.
References StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), StringExtractor::GetHexBytesAvail(), lldb_private::GetLog(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsNormalResponse(), LLDB_LOGF, lldb_private::process_gdb_remote::Memory, lldb_private::Stream::Printf(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
ReadRegister()
DataBufferSP GDBRemoteCommunicationClient::ReadRegister (lldb::tid_t tid, uint32_t reg_num)
Definition at line 3536 of file GDBRemoteCommunicationClient.cpp.
References StringExtractor::GetHexBytes(), StringExtractor::GetStringRef(), StringExtractorGDBRemote::IsNormalResponse(), lldb_private::Stream::Printf(), SendThreadSpecificPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by lldb_private::process_gdb_remote::GDBRemoteRegisterContext::GetPrimordialRegister().
ResetDiscoverableSettings()
void GDBRemoteCommunicationClient::ResetDiscoverableSettings (bool did_exec)
Definition at line 285 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, m_attach_or_wait_reply, m_avoid_g_packets, m_curr_pid_is_valid, m_default_packet_timeout, m_gdb_server_name, m_gdb_server_version, m_host_arch, m_host_distribution_id, m_hostname, m_max_packet_size, m_os_build, m_os_kernel, m_os_version, m_prepare_for_reg_writing_reply, m_process_arch, m_qGDBServerVersion_is_valid, m_qHostInfo_is_valid, m_qProcessInfo_is_valid, m_qSupported_response, m_qSymbol_requests_done, m_supported_async_json_packets_is_valid, m_supported_async_json_packets_sp, m_supports_alloc_dealloc_memory, m_supports_augmented_libraries_svr4_read, m_supports_jModulesInfo, m_supports_memory_region_info, m_supports_multi_mem_read, m_supports_multiprocess, m_supports_not_sending_acks, m_supports_p, m_supports_QEnvironment, m_supports_QEnvironmentHexEncoded, m_supports_qfProcessInfo, m_supports_qGroupName, m_supports_qModuleInfo, m_supports_qProcessInfoPID, m_supports_qSaveCore, m_supports_QSaveRegisterState, m_supports_qSymbol, m_supports_qThreadStopInfo, m_supports_qUserName, m_supports_qXfer_auxv_read, m_supports_qXfer_features_read, m_supports_qXfer_libraries_read, m_supports_qXfer_libraries_svr4_read, m_supports_qXfer_memory_map_read, m_supports_qXfer_siginfo_read, m_supports_reverse_continue, m_supports_reverse_step, m_supports_thread_suffix, m_supports_threads_in_stop_reply, m_supports_vCont_C, m_supports_vCont_c, m_supports_vCont_S, m_supports_vCont_s, m_supports_z0, m_supports_z1, m_supports_z2, m_supports_z3, m_supports_z4, m_target_vm_page_size, m_uses_native_signals, m_x_packet_state, and UINT32_MAX.
Referenced by HandshakeWithServer().
RestoreRegisterState()
bool GDBRemoteCommunicationClient::RestoreRegisterState (lldb::tid_t tid, uint32_t save_id)
Definition at line 3619 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolNo, StringExtractorGDBRemote::IsOKResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), m_supports_QSaveRegisterState, lldb_private::Stream::Printf(), SendThreadSpecificPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by lldb_private::process_gdb_remote::GDBRemoteRegisterContext::WriteAllRegisterValues().
RunShellCommand()
lldb_private::Status GDBRemoteCommunicationClient::RunShellCommand (llvm::StringRef command, const FileSpec & working_dir, int * status_ptr, int * signo_ptr, std::string * command_output, const Timeout< std::micro > & timeout)
Definition at line 2978 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::Status::FromErrorString(), StringExtractor::GetChar(), StringExtractorGDBRemote::GetEscapedBinaryData(), StringExtractor::GetHexMaxU32(), lldb_private::FileSpec::GetPath(), lldb_private::StreamString::GetString(), lldb_private::Stream::PutBytesAsRawHex8(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), lldb_private::Stream::PutHex32(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::Status, lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UINT32_MAX.
SaveRegisterState()
bool GDBRemoteCommunicationClient::SaveRegisterState (lldb::tid_t tid, uint32_t & save_id)
Definition at line 3594 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, StringExtractor::GetU32(), StringExtractorGDBRemote::IsUnsupportedResponse(), m_supports_QSaveRegisterState, lldb_private::Stream::PutCString(), SendThreadSpecificPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by lldb_private::process_gdb_remote::GDBRemoteRegisterContext::ReadAllRegisterValues().
SendEnvironment()
int GDBRemoteCommunicationClient::SendEnvironment (const Environment & env)
Definition at line 872 of file GDBRemoteCommunicationClient.cpp.
References SendEnvironmentPacket().
SendEnvironmentPacket()
int GDBRemoteCommunicationClient::SendEnvironmentPacket (char const * name_equal_value)
Sends a "QEnvironment:NAME=VALUE" packet that will build up the environment that will get used when launching an application in conjunction with the 'A' packet.
This function can be called multiple times in a row in order to pass on the desired environment that the inferior should be launched with.
Parameters
[in] name_equal_value A NULL terminated C string that contains a single environment in the format "NAME=VALUE".
Returns
Zero if the response was "OK", a positive value if the the response was "Exx" where xx are two hex digits, or -1 if the call is unsupported or any other unexpected response was received.
Definition at line 885 of file GDBRemoteCommunicationClient.cpp.
References error(), StringExtractorGDBRemote::GetError(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsOKResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), m_supports_QEnvironment, m_supports_QEnvironmentHexEncoded, lldb_private::Stream::Printf(), lldb_private::Stream::PutBytesAsRawHex8(), lldb_private::Stream::PutCString(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by SendEnvironment().
SendGDBStoppointTypePacket()
uint8_t GDBRemoteCommunicationClient::SendGDBStoppointTypePacket (GDBStoppointType type, bool insert, lldb::addr_t addr, uint32_t length, std::chrono::seconds interrupt_timeout)
Definition at line 2830 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::Breakpoints, lldb_private::process_gdb_remote::eBreakpointHardware, lldb_private::process_gdb_remote::eBreakpointSoftware, lldb_private::process_gdb_remote::eStoppointInvalid, lldb_private::process_gdb_remote::eWatchpointRead, lldb_private::process_gdb_remote::eWatchpointReadWrite, lldb_private::process_gdb_remote::eWatchpointWrite, StringExtractorGDBRemote::GetError(), lldb_private::GetLog(), StringExtractorGDBRemote::IsErrorResponse(), StringExtractorGDBRemote::IsOKResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), LLDB_LOGF, m_supports_z0, m_supports_z1, m_supports_z2, m_supports_z3, m_supports_z4, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), StringExtractorGDBRemote::SetResponseValidatorToOKErrorNotSupported(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, SupportsGDBStoppointPacket(), and UNUSED_IF_ASSERT_DISABLED.
SendGetTraceDataPacket()
Status lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendGetTraceDataPacket (StreamGDBRemote & packet, lldb::user_id_t uid, lldb::tid_t thread_id, llvm::MutableArrayRef< uint8_t > & buffer, size_t offset) protected
SendLaunchArchPacket()
int GDBRemoteCommunicationClient::SendLaunchArchPacket (const char * arch)
Definition at line 952 of file GDBRemoteCommunicationClient.cpp.
References error(), StringExtractorGDBRemote::GetError(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsOKResponse(), lldb_private::Stream::Printf(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
SendLaunchEventDataPacket()
int GDBRemoteCommunicationClient::SendLaunchEventDataPacket (const char * data, bool * was_supported = nullptr)
Definition at line 969 of file GDBRemoteCommunicationClient.cpp.
References error(), StringExtractorGDBRemote::GetError(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsOKResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), lldb_private::Stream::Printf(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
SendSetCurrentThreadPacket()
std::optional< PidTid > GDBRemoteCommunicationClient::SendSetCurrentThreadPacket (uint64_t tid, uint64_t pid, char op)
Definition at line 2737 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::StreamString::GetString(), lldb_private::Communication::IsConnected(), StringExtractorGDBRemote::IsOKResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), LLDB_INVALID_PROCESS_ID, lldb_private::Stream::Printf(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UINT64_MAX.
Referenced by SetCurrentThread(), and SetCurrentThreadForRun().
SendSignalsToIgnore()
Status GDBRemoteCommunicationClient::SendSignalsToIgnore (llvm::ArrayRef< int32_t > signals)
Definition at line 4272 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::Status::FromErrorString(), StringExtractorGDBRemote::IsOKResponse(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::Status, and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
SendSpeedTestPacket()
bool GDBRemoteCommunicationClient::SendSpeedTestPacket (uint32_t send_size, uint32_t recv_size)
Definition at line 2614 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::StreamString::GetString(), lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by TestPacketSpeed().
SendStdinNotification()
int GDBRemoteCommunicationClient::SendStdinNotification (const char * data, size_t data_len)
Sends a GDB remote protocol 'I' packet that delivers stdin data to the remote process.
Parameters
[in] data A pointer to stdin data.
[in] data_len The number of bytes available at data.
Returns
Zero if the attach was successful, or an error indicating an error code.
Definition at line 1435 of file GDBRemoteCommunicationClient.cpp.
References StringExtractorGDBRemote::GetError(), lldb_private::StreamString::GetString(), lldb_private::Stream::PutBytesAsRawHex8(), lldb_private::Stream::PutCString(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
SendThreadSpecificPacketAndWaitForResponse()
GDBRemoteCommunication::PacketResult GDBRemoteCommunicationClient::SendThreadSpecificPacketAndWaitForResponse (lldb::tid_t tid, StreamString && payload, StringExtractorGDBRemote & response) protected
Definition at line 534 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::process_gdb_remote::GDBRemoteCommunication::ErrorNoSequenceLock, lldb_private::process_gdb_remote::GDBRemoteCommunication::ErrorSendFailed, lldb_private::GetLog(), GetThreadSuffixSupported(), LLDB_LOGF, lldb_private::process_gdb_remote::Packets, lldb_private::process_gdb_remote::Process, lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponseNoLock(), and SetCurrentThread().
Referenced by GetThreadPacketSupported(), ReadAllRegisters(), ReadRegister(), RestoreRegisterState(), SaveRegisterState(), WriteAllRegisters(), and WriteRegister().
SendTraceGetBinaryData()
llvm::Expected< std::vector< uint8_t > > GDBRemoteCommunicationClient::SendTraceGetBinaryData (const TraceGetBinaryDataRequest & request, std::chrono::seconds interrupt_timeout)
Definition at line 3781 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::StreamString::GetData(), StringExtractorGDBRemote::GetEscapedBinaryData(), lldb_private::GetLog(), StringExtractorGDBRemote::GetStatus(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsErrorResponse(), LLDB_LOG, lldb_private::process_gdb_remote::Process, lldb_private::Stream::PutCString(), lldb_private::StreamGDBRemote::PutEscapedBytes(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, lldb_private::Status::ToError(), and lldb_private::toJSON().
SendTraceGetState()
llvm::Expected< std::string > GDBRemoteCommunicationClient::SendTraceGetState (llvm::StringRef type, std::chrono::seconds interrupt_timeout)
Definition at line 3748 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::StreamString::GetData(), lldb_private::GetLog(), StringExtractorGDBRemote::GetStatus(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsErrorResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), LLDB_LOG, StringExtractor::Peek(), lldb_private::process_gdb_remote::Process, lldb_private::Stream::PutCString(), lldb_private::StreamGDBRemote::PutEscapedBytes(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, lldb_private::Status::ToError(), and lldb_private::toJSON().
SendTraceStart()
llvm::Error GDBRemoteCommunicationClient::SendTraceStart (const llvm::json::Value & request, std::chrono::seconds interrupt_timeout)
Definition at line 3714 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::StreamString::GetData(), lldb_private::GetLog(), StringExtractorGDBRemote::GetStatus(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsErrorResponse(), StringExtractorGDBRemote::IsOKResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), LLDB_LOG, lldb_private::process_gdb_remote::Process, lldb_private::Stream::PutCString(), lldb_private::StreamGDBRemote::PutEscapedBytes(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and lldb_private::Status::ToError().
SendTraceStop()
llvm::Error GDBRemoteCommunicationClient::SendTraceStop (const TraceStopRequest & request, std::chrono::seconds interrupt_timeout)
Definition at line 3680 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::StreamString::GetData(), lldb_private::GetLog(), StringExtractorGDBRemote::GetStatus(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsErrorResponse(), StringExtractorGDBRemote::IsOKResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), LLDB_LOG, lldb_private::process_gdb_remote::Process, lldb_private::Stream::PutCString(), lldb_private::StreamGDBRemote::PutEscapedBytes(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, lldb_private::Status::ToError(), and lldb_private::toJSON().
SendTraceSupported()
llvm::Expected< TraceSupportedResponse > GDBRemoteCommunicationClient::SendTraceSupported (std::chrono::seconds interrupt_timeout)
Definition at line 3655 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::GetLog(), StringExtractorGDBRemote::GetStatus(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsErrorResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), LLDB_LOG, StringExtractor::Peek(), lldb_private::process_gdb_remote::Process, lldb_private::Stream::PutCString(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and lldb_private::Status::ToError().
ServeSymbolLookups()
void GDBRemoteCommunicationClient::ServeSymbolLookups (lldb_private::Process * process)
Definition at line 4104 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::StreamString::Clear(), lldb::eSymbolTypeAbsolute, lldb::eSymbolTypeAdditional, lldb::eSymbolTypeAny, lldb::eSymbolTypeBlock, lldb::eSymbolTypeCode, lldb::eSymbolTypeCommonBlock, lldb::eSymbolTypeCompiler, lldb::eSymbolTypeData, lldb::eSymbolTypeException, lldb::eSymbolTypeHeaderFile, lldb::eSymbolTypeInstrumentation, lldb::eSymbolTypeInvalid, lldb::eSymbolTypeLineEntry, lldb::eSymbolTypeLineHeader, lldb::eSymbolTypeLocal, lldb::eSymbolTypeObjCClass, lldb::eSymbolTypeObjCIVar, lldb::eSymbolTypeObjCMetaClass, lldb::eSymbolTypeObjectFile, lldb::eSymbolTypeParam, lldb::eSymbolTypeReExported, lldb::eSymbolTypeResolver, lldb::eSymbolTypeRuntime, lldb::eSymbolTypeScopeBegin, lldb::eSymbolTypeScopeEnd, lldb::eSymbolTypeSourceFile, lldb::eSymbolTypeTrampoline, lldb::eSymbolTypeUndefined, lldb::eSymbolTypeVariable, lldb::eSymbolTypeVariableType, lldb_private::ModuleList::FindSymbolsWithNameAndType(), StringExtractor::GetHexByteString(), lldb_private::Target::GetImages(), lldb_private::GetLog(), lldb_private::StreamString::GetString(), StringExtractor::GetStringRef(), lldb_private::Process::GetTarget(), StringExtractorGDBRemote::IsOKResponse(), StringExtractorGDBRemote::IsUnsupportedResponse(), LLDB_INVALID_ADDRESS, LLDB_LOGF, m_qSymbol_requests_done, m_supports_qSymbol, lldb_private::process_gdb_remote::Packets, lldb_private::Stream::Printf(), lldb_private::process_gdb_remote::Process, lldb_private::Stream::PutBytesAsRawHex8(), lldb_private::Stream::PutCString(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponseNoLock(), StringExtractor::SetFilePos(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
SetCurrentThread()
bool GDBRemoteCommunicationClient::SetCurrentThread (uint64_t tid, lldb::pid_t pid = LLDB_INVALID_PROCESS_ID)
Definition at line 2770 of file GDBRemoteCommunicationClient.cpp.
References LLDB_INVALID_PROCESS_ID, m_curr_pid, m_curr_tid, and SendSetCurrentThreadPacket().
Referenced by SendThreadSpecificPacketAndWaitForResponse().
SetCurrentThreadForRun()
bool GDBRemoteCommunicationClient::SetCurrentThreadForRun (uint64_t tid, lldb::pid_t pid = LLDB_INVALID_PROCESS_ID)
Definition at line 2785 of file GDBRemoteCommunicationClient.cpp.
References LLDB_INVALID_PROCESS_ID, m_curr_pid_run, m_curr_tid_run, and SendSetCurrentThreadPacket().
SetDetachOnError()
int GDBRemoteCommunicationClient::SetDetachOnError (bool enable)
Sets the DetachOnError flag to enable for the process controlled by the stub.
Parameters
[in] enable A boolean value indicating whether to detach on error or not.
Returns
Zero if the for success, or an error code for failure.
Definition at line 1999 of file GDBRemoteCommunicationClient.cpp.
References error(), StringExtractorGDBRemote::GetError(), StringExtractorGDBRemote::IsOKResponse(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UNUSED_IF_ASSERT_DISABLED.
SetDisableASLR()
int GDBRemoteCommunicationClient::SetDisableASLR (bool enable)
Sets the disable ASLR flag to enable for a process that will be launched with the 'A' packet.
Parameters
[in] enable A boolean value indicating whether to disable ASLR or not.
Returns
Zero if the for success, or an error code for failure.
Definition at line 1982 of file GDBRemoteCommunicationClient.cpp.
References error(), StringExtractorGDBRemote::GetError(), StringExtractorGDBRemote::IsOKResponse(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UNUSED_IF_ASSERT_DISABLED.
SetFilePermissions()
Status GDBRemoteCommunicationClient::SetFilePermissions (const FileSpec & file_spec, uint32_t file_permissions)
Definition at line 3054 of file GDBRemoteCommunicationClient.cpp.
References lldb::eErrorTypePOSIX, lldb_private::Status::FromErrorStringWithFormat(), StringExtractor::GetChar(), lldb_private::StreamString::GetData(), StringExtractor::GetHexMaxU32(), lldb_private::FileSpec::GetPath(), lldb_private::StreamString::GetString(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), lldb_private::Stream::PutHex32(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::Status, lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UINT32_MAX.
SetSTDERR()
int GDBRemoteCommunicationClient::SetSTDERR (const FileSpec & file_spec)
Definition at line 1926 of file GDBRemoteCommunicationClient.cpp.
References error(), StringExtractorGDBRemote::GetError(), lldb_private::FileSpec::GetPath(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsOKResponse(), lldb_private::Stream::PutCString(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
SetSTDIN()
int GDBRemoteCommunicationClient::SetSTDIN (const FileSpec & file_spec)
Sets the path to use for stdin/out/err for a process that will be launched with the 'A' packet.
Parameters
[in] file_spec The path to use for stdin/out/err
Returns
Zero if the for success, or an error code for failure.
Definition at line 1886 of file GDBRemoteCommunicationClient.cpp.
References error(), StringExtractorGDBRemote::GetError(), lldb_private::FileSpec::GetPath(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsOKResponse(), lldb_private::Stream::PutCString(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
SetSTDOUT()
int GDBRemoteCommunicationClient::SetSTDOUT (const FileSpec & file_spec)
Definition at line 1906 of file GDBRemoteCommunicationClient.cpp.
References error(), StringExtractorGDBRemote::GetError(), lldb_private::FileSpec::GetPath(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsOKResponse(), lldb_private::Stream::PutCString(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
SetWorkingDir()
int GDBRemoteCommunicationClient::SetWorkingDir (const FileSpec & working_dir)
Sets the working directory to path for a process that will be launched with the 'A' packet for non platform based connections.
If this packet is sent to a GDB server that implements the platform, it will change the current working directory for the platform process.
Parameters
[in] working_dir The path to a directory to use when launching our process
Returns
Zero if the for success, or an error code for failure.
Definition at line 1962 of file GDBRemoteCommunicationClient.cpp.
References error(), StringExtractorGDBRemote::GetError(), lldb_private::FileSpec::GetPath(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsOKResponse(), lldb_private::Stream::PutCString(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Stat()
std::optional< GDBRemoteFStatData > GDBRemoteCommunicationClient::Stat (const FileSpec & file_spec)
Definition at line 3164 of file GDBRemoteCommunicationClient.cpp.
References CloseFile(), lldb_private::File::eOpenOptionReadOnly, error(), FStat(), OpenFile(), and UINT64_MAX.
Referenced by GetFilePermissions(), and GetFileSize().
SupportsAllocDeallocMemory()
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SupportsAllocDeallocMemory () inline
Definition at line 347 of file GDBRemoteCommunicationClient.h.
References m_supports_alloc_dealloc_memory.
SupportsGDBStoppointPacket()
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SupportsGDBStoppointPacket (GDBStoppointType type) inline
Definition at line 273 of file GDBRemoteCommunicationClient.h.
References lldb_private::process_gdb_remote::eBreakpointHardware, lldb_private::process_gdb_remote::eBreakpointSoftware, lldb_private::process_gdb_remote::eWatchpointRead, lldb_private::process_gdb_remote::eWatchpointReadWrite, lldb_private::process_gdb_remote::eWatchpointWrite, m_supports_z0, m_supports_z1, m_supports_z2, m_supports_z3, and m_supports_z4.
Referenced by SendGDBStoppointTypePacket().
SyncThreadState()
bool GDBRemoteCommunicationClient::SyncThreadState (lldb::tid_t tid)
Definition at line 3642 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::StreamString::GetString(), GetSyncThreadStateSupported(), StringExtractorGDBRemote::IsOKResponse(), lldb_private::Stream::Printf(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by lldb_private::process_gdb_remote::GDBRemoteRegisterContext::ReadAllRegisterValues().
TestPacketSpeed()
void GDBRemoteCommunicationClient::TestPacketSpeed (const uint32_t num_packets, uint32_t max_send, uint32_t max_recv, uint64_t recv_amount, bool json, Stream & strm)
Definition at line 2487 of file GDBRemoteCommunicationClient.cpp.
References calculate_standard_deviation(), lldb_private::Stream::EOL(), lldb_private::Stream::Flush(), lldb_private::Stream::Format(), lldb_private::StreamString::GetString(), MakeSpeedTestPacket(), lldb_private::Stream::Printf(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and SendSpeedTestPacket().
Referenced by CommandObjectProcessGDBRemoteSpeedTest::DoExecute().
Unlink()
Status GDBRemoteCommunicationClient::Unlink (const FileSpec & file_spec)
Definition at line 3381 of file GDBRemoteCommunicationClient.cpp.
References lldb::eErrorTypePOSIX, error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), gdb_errno_to_system(), StringExtractor::GetChar(), StringExtractor::GetHexMaxU32(), lldb_private::FileSpec::GetPath(), StringExtractor::GetS32(), lldb_private::StreamString::GetString(), lldb_private::Stream::PutCString(), lldb_private::Stream::PutStringAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::Status, lldb_private::process_gdb_remote::GDBRemoteCommunication::Success, and UINT32_MAX.
UsesNativeSignals()
bool GDBRemoteCommunicationClient::UsesNativeSignals ()
Definition at line 4347 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolYes, GetRemoteQSupported(), GetThreadSuffixSupported(), and m_uses_native_signals.
WriteAllRegisters()
bool GDBRemoteCommunicationClient::WriteAllRegisters (lldb::tid_t tid, llvm::ArrayRef< uint8_t > data)
Definition at line 3581 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::endian::InlHostByteOrder(), StringExtractorGDBRemote::IsOKResponse(), lldb_private::Stream::PutBytesAsRawHex8(), lldb_private::Stream::PutChar(), SendThreadSpecificPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by lldb_private::process_gdb_remote::GDBRemoteRegisterContext::WriteAllRegisterValues(), and lldb_private::process_gdb_remote::GDBRemoteRegisterContext::WriteRegisterBytes().
WriteFile()
uint64_t GDBRemoteCommunicationClient::WriteFile (lldb::user_id_t fd, uint64_t offset, const void * src, uint64_t src_len, Status & error)
Definition at line 3315 of file GDBRemoteCommunicationClient.cpp.
References lldb::eErrorTypePOSIX, error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), gdb_errno_to_system(), StringExtractor::GetChar(), StringExtractor::GetS32(), StringExtractor::GetS64(), lldb_private::StreamString::GetString(), lldb_private::Stream::Printf(), lldb_private::StreamGDBRemote::PutEscapedBytes(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::Status, and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
WriteMemoryTags()
Status GDBRemoteCommunicationClient::WriteMemoryTags (lldb::addr_t addr, size_t len, int32_t type, const std::vector< uint8_t > & tags)
Definition at line 724 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::Status::FromErrorString(), lldb_private::StreamString::GetString(), StringExtractorGDBRemote::IsOKResponse(), lldb_private::Stream::Printf(), lldb_private::Stream::PutBytesAsRawHex8(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
WriteRegister()
bool GDBRemoteCommunicationClient::WriteRegister (lldb::tid_t tid, uint32_t reg_num, llvm::ArrayRef< uint8_t > data)
Definition at line 3567 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::endian::InlHostByteOrder(), StringExtractorGDBRemote::IsOKResponse(), lldb_private::Stream::Printf(), lldb_private::Stream::PutBytesAsRawHex8(), SendThreadSpecificPacketAndWaitForResponse(), and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by lldb_private::process_gdb_remote::GDBRemoteRegisterContext::SetPrimordialRegister(), and lldb_private::process_gdb_remote::GDBRemoteRegisterContext::WriteAllRegisterValues().
Member Data Documentation
m_attach_or_wait_reply
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_attach_or_wait_reply = eLazyBoolCalculate protected
Definition at line 554 of file GDBRemoteCommunicationClient.h.
Referenced by GetVAttachOrWaitSupported(), and ResetDiscoverableSettings().
m_avoid_g_packets
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_avoid_g_packets = eLazyBoolCalculate protected
Definition at line 557 of file GDBRemoteCommunicationClient.h.
Referenced by AvoidGPackets(), and ResetDiscoverableSettings().
m_binary_addresses
std::vector<lldb::addr_t> lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_binary_addresses protected
Definition at line 613 of file GDBRemoteCommunicationClient.h.
Referenced by GetCurrentProcessInfo(), and GetProcessStandaloneBinaries().
m_curr_pid
lldb::pid_t lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_curr_pid = LLDB_INVALID_PROCESS_ID protected
Current gdb remote protocol process identifier for all other operations.
Definition at line 593 of file GDBRemoteCommunicationClient.h.
Referenced by GetCurrentProcessID(), GetCurrentProcessInfo(), GetDefaultThreadId(), and SetCurrentThread().
m_curr_pid_is_valid
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_curr_pid_is_valid = eLazyBoolCalculate protected
Definition at line 546 of file GDBRemoteCommunicationClient.h.
Referenced by GetCurrentProcessID(), GetCurrentProcessInfo(), GetDefaultThreadId(), and ResetDiscoverableSettings().
m_curr_pid_run
lldb::pid_t lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_curr_pid_run = LLDB_INVALID_PROCESS_ID protected
Current gdb remote protocol process identifier for continue, step, etc.
Definition at line 595 of file GDBRemoteCommunicationClient.h.
Referenced by GetCurrentProcessID(), GetCurrentProcessInfo(), GetDefaultThreadId(), and SetCurrentThreadForRun().
m_curr_tid
lldb::tid_t lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_curr_tid = LLDB_INVALID_THREAD_ID protected
Current gdb remote protocol thread identifier for all other operations.
Definition at line 597 of file GDBRemoteCommunicationClient.h.
Referenced by OnRunPacketSent(), and SetCurrentThread().
m_curr_tid_run
lldb::tid_t lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_curr_tid_run = LLDB_INVALID_THREAD_ID protected
Current gdb remote protocol thread identifier for continue, step, etc.
Definition at line 599 of file GDBRemoteCommunicationClient.h.
Referenced by SetCurrentThreadForRun().
m_default_packet_timeout
std::chrono::seconds lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_default_packet_timeout protected
Definition at line 624 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), GetHostDefaultPacketTimeout(), GetHostInfo(), and ResetDiscoverableSettings().
m_gdb_server_name
std::string lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_gdb_server_name protected
Definition at line 619 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), GetGDBServerProgramName(), GetGDBServerVersion(), and ResetDiscoverableSettings().
m_gdb_server_version
uint32_t lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_gdb_server_version protected
Initial value:
=
      UINT32_MAX
Definition at line 621 of file GDBRemoteCommunicationClient.h.
Referenced by GetCurrentProcessInfo(), GetGDBServerProgramVersion(), GetGDBServerVersion(), and ResetDiscoverableSettings().
m_high_mem_addressing_bits
uint32_t lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_high_mem_addressing_bits = 0 protected
Definition at line 605 of file GDBRemoteCommunicationClient.h.
Referenced by GetAddressableBits(), and GetHostInfo().
m_host_arch
ArchSpec lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_host_arch protected
Definition at line 607 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), GetHostArchitecture(), GetHostInfo(), GetSystemArchitecture(), and ResetDiscoverableSettings().
m_host_distribution_id
std::string lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_host_distribution_id protected
Definition at line 608 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), GetHostInfo(), and ResetDiscoverableSettings().
m_hostname
std::string lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_hostname protected
Definition at line 618 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), GetHostInfo(), GetHostname(), and ResetDiscoverableSettings().
m_low_mem_addressing_bits
uint32_t lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_low_mem_addressing_bits = 0 protected
Definition at line 604 of file GDBRemoteCommunicationClient.h.
Referenced by GetAddressableBits(), and GetHostInfo().
m_maccatalyst_version
llvm::VersionTuple lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_maccatalyst_version protected
Definition at line 615 of file GDBRemoteCommunicationClient.h.
Referenced by GetHostInfo(), and GetMacCatalystVersion().
m_max_packet_size
uint64_t lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_max_packet_size = 0 protected
Definition at line 626 of file GDBRemoteCommunicationClient.h.
Referenced by GetRemoteMaxPacketSize(), GetRemoteQSupported(), and ResetDiscoverableSettings().
m_num_supported_hardware_watchpoints
uint32_t lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_num_supported_hardware_watchpoints = 0 protected
Definition at line 601 of file GDBRemoteCommunicationClient.h.
Referenced by GetWatchpointSlotCount().
m_os_build
std::string lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_os_build protected
Definition at line 616 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), GetHostInfo(), GetOSBuildString(), and ResetDiscoverableSettings().
m_os_kernel
std::string lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_os_kernel protected
Definition at line 617 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), GetHostInfo(), GetOSKernelDescription(), and ResetDiscoverableSettings().
m_os_version
llvm::VersionTuple lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_os_version protected
Definition at line 614 of file GDBRemoteCommunicationClient.h.
Referenced by GetHostInfo(), GetOSVersion(), and ResetDiscoverableSettings().
m_prepare_for_reg_writing_reply
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_prepare_for_reg_writing_reply = eLazyBoolCalculate protected
Definition at line 555 of file GDBRemoteCommunicationClient.h.
Referenced by GetSyncThreadStateSupported(), and ResetDiscoverableSettings().
m_process_arch
ArchSpec lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_process_arch protected
Definition at line 609 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), GetCurrentProcessInfo(), GetProcessArchitecture(), and ResetDiscoverableSettings().
m_process_standalone_uuid
UUID lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_process_standalone_uuid protected
Definition at line 610 of file GDBRemoteCommunicationClient.h.
Referenced by GetCurrentProcessInfo(), and GetProcessStandaloneBinary().
m_process_standalone_value
lldb::addr_t lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_process_standalone_value = LLDB_INVALID_ADDRESS protected
Definition at line 611 of file GDBRemoteCommunicationClient.h.
Referenced by GetCurrentProcessInfo(), and GetProcessStandaloneBinary().
m_process_standalone_value_is_offset
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_process_standalone_value_is_offset = false protected
Definition at line 612 of file GDBRemoteCommunicationClient.h.
Referenced by GetCurrentProcessInfo(), and GetProcessStandaloneBinary().
m_qGDBServerVersion_is_valid
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_qGDBServerVersion_is_valid = eLazyBoolCalculate protected
Definition at line 548 of file GDBRemoteCommunicationClient.h.
Referenced by GetGDBServerVersion(), and ResetDiscoverableSettings().
m_qHostInfo_is_valid
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_qHostInfo_is_valid = eLazyBoolCalculate protected
Definition at line 545 of file GDBRemoteCommunicationClient.h.
Referenced by GetAddressableBits(), GetHostArchitecture(), GetHostDefaultPacketTimeout(), GetHostInfo(), GetWatchpointReportedAfter(), and ResetDiscoverableSettings().
m_qProcessInfo_is_valid
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_qProcessInfo_is_valid = eLazyBoolCalculate protected
Definition at line 547 of file GDBRemoteCommunicationClient.h.
Referenced by GetCurrentProcessInfo(), GetProcessArchitecture(), GetProcessStandaloneBinaries(), GetProcessStandaloneBinary(), and ResetDiscoverableSettings().
m_qSupported_response
std::string lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_qSupported_response protected
Definition at line 627 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), GetRemoteQSupported(), GetServerSupportedFeatures(), and ResetDiscoverableSettings().
m_qSymbol_requests_done
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_qSymbol_requests_done protected
Definition at line 586 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), ResetDiscoverableSettings(), and ServeSymbolLookups().
m_qXfer_memory_map
std::vector<MemoryRegionInfo> lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_qXfer_memory_map protected
Definition at line 632 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), GetQXferMemoryMapRegionInfo(), and LoadQXferMemoryMap().
m_qXfer_memory_map_loaded
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_qXfer_memory_map_loaded = false protected
Definition at line 633 of file GDBRemoteCommunicationClient.h.
Referenced by LoadQXferMemoryMap().
m_supported_async_json_packets_is_valid
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supported_async_json_packets_is_valid = false protected
Definition at line 629 of file GDBRemoteCommunicationClient.h.
Referenced by GetSupportedStructuredDataPlugins(), and ResetDiscoverableSettings().
m_supported_async_json_packets_sp
lldb_private::StructuredData::ObjectSP lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supported_async_json_packets_sp protected
Definition at line 630 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), GetSupportedStructuredDataPlugins(), and ResetDiscoverableSettings().
m_supports_alloc_dealloc_memory
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_alloc_dealloc_memory = eLazyBoolCalculate protected
Definition at line 549 of file GDBRemoteCommunicationClient.h.
Referenced by AllocateMemory(), DeallocateMemory(), ResetDiscoverableSettings(), and SupportsAllocDeallocMemory().
m_supports_augmented_libraries_svr4_read
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_augmented_libraries_svr4_read = eLazyBoolCalculate protected
Definition at line 565 of file GDBRemoteCommunicationClient.h.
Referenced by GetAugmentedLibrariesSVR4ReadSupported(), GetRemoteQSupported(), and ResetDiscoverableSettings().
m_supports_detach_stay_stopped
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_detach_stay_stopped = eLazyBoolCalculate protected
Definition at line 552 of file GDBRemoteCommunicationClient.h.
Referenced by Detach().
m_supports_error_string_reply
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_error_string_reply = eLazyBoolCalculate protected
Definition at line 571 of file GDBRemoteCommunicationClient.h.
Referenced by EnableErrorStringInPacket().
m_supports_jGetDyldProcessState
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_jGetDyldProcessState = eLazyBoolCalculate protected
Definition at line 569 of file GDBRemoteCommunicationClient.h.
Referenced by GetDynamicLoaderProcessStateSupported().
m_supports_jGetSharedCacheInfo
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_jGetSharedCacheInfo = eLazyBoolCalculate protected
Definition at line 568 of file GDBRemoteCommunicationClient.h.
Referenced by GetSharedCacheInfoSupported().
m_supports_jLoadedDynamicLibrariesInfos
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_jLoadedDynamicLibrariesInfos = eLazyBoolCalculate protected
Definition at line 567 of file GDBRemoteCommunicationClient.h.
Referenced by GetLoadedDynamicLibrariesInfosSupported().
m_supports_jModulesInfo
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_jModulesInfo protected
Definition at line 588 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), GetModulesInfo(), and ResetDiscoverableSettings().
m_supports_jThreadExtendedInfo
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_jThreadExtendedInfo = eLazyBoolCalculate protected
Definition at line 566 of file GDBRemoteCommunicationClient.h.
Referenced by GetThreadExtendedInfoSupported().
m_supports_jThreadsInfo
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_jThreadsInfo protected
Definition at line 587 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), and GetThreadsInfo().
m_supports_memory_region_info
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_memory_region_info = eLazyBoolCalculate protected
Definition at line 550 of file GDBRemoteCommunicationClient.h.
Referenced by GetMemoryRegionInfo(), and ResetDiscoverableSettings().
m_supports_memory_tagging
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_memory_tagging = eLazyBoolCalculate protected
Definition at line 573 of file GDBRemoteCommunicationClient.h.
Referenced by GetMemoryTaggingSupported(), GetMultiprocessSupported(), and GetRemoteQSupported().
m_supports_multi_mem_read
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_multi_mem_read = eLazyBoolCalculate protected
Definition at line 579 of file GDBRemoteCommunicationClient.h.
Referenced by GetMultiMemReadSupported(), GetRemoteQSupported(), and ResetDiscoverableSettings().
m_supports_multiprocess
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_multiprocess = eLazyBoolCalculate protected
Definition at line 572 of file GDBRemoteCommunicationClient.h.
Referenced by GetMultiprocessSupported(), GetRemoteQSupported(), and ResetDiscoverableSettings().
m_supports_not_sending_acks
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_not_sending_acks = eLazyBoolCalculate protected
Definition at line 536 of file GDBRemoteCommunicationClient.h.
Referenced by QueryNoAckModeSupported(), and ResetDiscoverableSettings().
m_supports_p
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_p = eLazyBoolCalculate protected
Definition at line 556 of file GDBRemoteCommunicationClient.h.
Referenced by GetpPacketSupported(), and ResetDiscoverableSettings().
m_supports_QEnvironment
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_QEnvironment protected
Definition at line 585 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), ResetDiscoverableSettings(), and SendEnvironmentPacket().
m_supports_QEnvironmentHexEncoded
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_QEnvironmentHexEncoded protected
Definition at line 585 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), ResetDiscoverableSettings(), and SendEnvironmentPacket().
m_supports_qfProcessInfo
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_qfProcessInfo protected
Definition at line 581 of file GDBRemoteCommunicationClient.h.
Referenced by FindProcesses(), GDBRemoteCommunicationClient(), and ResetDiscoverableSettings().
m_supports_qGroupName
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_qGroupName protected
Definition at line 582 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), GetGroupName(), and ResetDiscoverableSettings().
m_supports_qModuleInfo
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_qModuleInfo protected
Definition at line 587 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), GetModuleInfo(), and ResetDiscoverableSettings().
m_supports_QPassSignals
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_QPassSignals = eLazyBoolCalculate protected
Definition at line 570 of file GDBRemoteCommunicationClient.h.
Referenced by GetQPassSignalsSupported(), and GetRemoteQSupported().
m_supports_qProcessInfoPID
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_qProcessInfoPID protected
Definition at line 581 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), GetProcessInfo(), and ResetDiscoverableSettings().
m_supports_qSaveCore
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_qSaveCore = eLazyBoolCalculate protected
Definition at line 574 of file GDBRemoteCommunicationClient.h.
Referenced by GetRemoteQSupported(), GetSaveCoreSupported(), and ResetDiscoverableSettings().
m_supports_QSaveRegisterState
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_QSaveRegisterState = eLazyBoolCalculate protected
Definition at line 558 of file GDBRemoteCommunicationClient.h.
Referenced by ResetDiscoverableSettings(), RestoreRegisterState(), and SaveRegisterState().
m_supports_qSymbol
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_qSymbol protected
Definition at line 586 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), ResetDiscoverableSettings(), and ServeSymbolLookups().
m_supports_qThreadStopInfo
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_qThreadStopInfo protected
Definition at line 583 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), GetThreadStopInfo(), and ResetDiscoverableSettings().
m_supports_qUserName
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_qUserName protected
Definition at line 582 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), GetUserName(), and ResetDiscoverableSettings().
m_supports_qXfer_auxv_read
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_qXfer_auxv_read = eLazyBoolCalculate protected
Definition at line 559 of file GDBRemoteCommunicationClient.h.
Referenced by GetQXferAuxvReadSupported(), GetRemoteQSupported(), and ResetDiscoverableSettings().
m_supports_qXfer_features_read
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_qXfer_features_read = eLazyBoolCalculate protected
Definition at line 562 of file GDBRemoteCommunicationClient.h.
Referenced by GetQXferFeaturesReadSupported(), GetRemoteQSupported(), and ResetDiscoverableSettings().
m_supports_qXfer_libraries_read
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_qXfer_libraries_read = eLazyBoolCalculate protected
Definition at line 560 of file GDBRemoteCommunicationClient.h.
Referenced by GetQXferLibrariesReadSupported(), GetRemoteQSupported(), and ResetDiscoverableSettings().
m_supports_qXfer_libraries_svr4_read
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_qXfer_libraries_svr4_read = eLazyBoolCalculate protected
Definition at line 561 of file GDBRemoteCommunicationClient.h.
Referenced by GetQXferLibrariesSVR4ReadSupported(), GetRemoteQSupported(), and ResetDiscoverableSettings().
m_supports_qXfer_memory_map_read
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_qXfer_memory_map_read = eLazyBoolCalculate protected
Definition at line 563 of file GDBRemoteCommunicationClient.h.
Referenced by GetQXferMemoryMapReadSupported(), GetRemoteQSupported(), and ResetDiscoverableSettings().
m_supports_qXfer_siginfo_read
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_qXfer_siginfo_read = eLazyBoolCalculate protected
Definition at line 564 of file GDBRemoteCommunicationClient.h.
Referenced by GetQXferSigInfoReadSupported(), GetRemoteQSupported(), and ResetDiscoverableSettings().
m_supports_reverse_continue
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_reverse_continue = eLazyBoolCalculate protected
Definition at line 577 of file GDBRemoteCommunicationClient.h.
Referenced by GetRemoteQSupported(), GetReverseContinueSupported(), and ResetDiscoverableSettings().
m_supports_reverse_step
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_reverse_step = eLazyBoolCalculate protected
Definition at line 578 of file GDBRemoteCommunicationClient.h.
Referenced by GetRemoteQSupported(), GetReverseStepSupported(), and ResetDiscoverableSettings().
m_supports_thread_suffix
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_thread_suffix = eLazyBoolCalculate protected
Definition at line 537 of file GDBRemoteCommunicationClient.h.
Referenced by GetThreadSuffixSupported(), and ResetDiscoverableSettings().
m_supports_threads_in_stop_reply
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_threads_in_stop_reply = eLazyBoolCalculate protected
Definition at line 538 of file GDBRemoteCommunicationClient.h.
Referenced by GetListThreadsInStopReplySupported(), and ResetDiscoverableSettings().
m_supports_vCont_all
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_vCont_all = eLazyBoolCalculate protected
Definition at line 539 of file GDBRemoteCommunicationClient.h.
Referenced by GetVContSupported().
m_supports_vCont_any
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_vCont_any = eLazyBoolCalculate protected
Definition at line 540 of file GDBRemoteCommunicationClient.h.
Referenced by GetVContSupported().
m_supports_vCont_C
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_vCont_C = eLazyBoolCalculate protected
Definition at line 542 of file GDBRemoteCommunicationClient.h.
Referenced by GetVContSupported(), and ResetDiscoverableSettings().
m_supports_vCont_c
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_vCont_c = eLazyBoolCalculate protected
Definition at line 541 of file GDBRemoteCommunicationClient.h.
Referenced by GetVContSupported(), and ResetDiscoverableSettings().
m_supports_vCont_S
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_vCont_S = eLazyBoolCalculate protected
Definition at line 544 of file GDBRemoteCommunicationClient.h.
Referenced by GetVContSupported(), and ResetDiscoverableSettings().
m_supports_vCont_s
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_vCont_s = eLazyBoolCalculate protected
Definition at line 543 of file GDBRemoteCommunicationClient.h.
Referenced by GetVContSupported(), and ResetDiscoverableSettings().
m_supports_vFileExists
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_vFileExists protected
Definition at line 589 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), and GetFileExists().
m_supports_vFileMode
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_vFileMode protected
Definition at line 589 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), and GetFilePermissions().
m_supports_vFileSize
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_vFileSize protected
Definition at line 588 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), and GetFileSize().
m_supports_vRun
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_vRun protected
Definition at line 590 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), and LaunchProcess().
m_supports_watchpoint_support_info
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_watchpoint_support_info = eLazyBoolCalculate protected
Definition at line 551 of file GDBRemoteCommunicationClient.h.
Referenced by GetWatchpointSlotCount().
m_supports_z0
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_z0 protected
Definition at line 583 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), ResetDiscoverableSettings(), SendGDBStoppointTypePacket(), and SupportsGDBStoppointPacket().
m_supports_z1
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_z1 protected
Definition at line 583 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), ResetDiscoverableSettings(), SendGDBStoppointTypePacket(), and SupportsGDBStoppointPacket().
m_supports_z2
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_z2 protected
Definition at line 584 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), ResetDiscoverableSettings(), SendGDBStoppointTypePacket(), and SupportsGDBStoppointPacket().
m_supports_z3
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_z3 protected
Definition at line 584 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), ResetDiscoverableSettings(), SendGDBStoppointTypePacket(), and SupportsGDBStoppointPacket().
m_supports_z4
bool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_supports_z4 protected
Definition at line 584 of file GDBRemoteCommunicationClient.h.
Referenced by GDBRemoteCommunicationClient(), ResetDiscoverableSettings(), SendGDBStoppointTypePacket(), and SupportsGDBStoppointPacket().
m_target_vm_page_size
int lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_target_vm_page_size = 0 protected
Definition at line 625 of file GDBRemoteCommunicationClient.h.
Referenced by GetHostInfo(), GetMemoryRegionInfo(), and ResetDiscoverableSettings().
m_uses_native_signals
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_uses_native_signals = eLazyBoolCalculate protected
Definition at line 575 of file GDBRemoteCommunicationClient.h.
Referenced by GetRemoteQSupported(), ResetDiscoverableSettings(), and UsesNativeSignals().
m_watchpoint_types
WatchpointHardwareFeature lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_watchpoint_types protected
Initial value:
=
      eWatchpointHardwareFeatureUnknown
Definition at line 602 of file GDBRemoteCommunicationClient.h.
Referenced by GetRemoteQSupported(), and GetSupportedWatchpointTypes().
m_watchpoints_trigger_after_instruction
LazyBool lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_watchpoints_trigger_after_instruction = eLazyBoolCalculate protected
Definition at line 553 of file GDBRemoteCommunicationClient.h.
Referenced by GetHostInfo(), and GetWatchpointReportedAfter().
m_x_packet_state
std::optional<xPacketState> lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::m_x_packet_state protected
Definition at line 576 of file GDBRemoteCommunicationClient.h.
Referenced by GetRemoteQSupported(), GetxPacketState(), and ResetDiscoverableSettings().
The documentation for this class was generated from the following files:
GDBRemoteCommunicationClient.h
GDBRemoteCommunicationClient.cpp