LLDB: lldb_private::process_gdb_remote::GDBRemoteRegisterContext Class Reference
lldb_private::process_gdb_remote::GDBRemoteRegisterContext Class Reference
#include <GDBRemoteRegisterContext.h>
Public Member Functions
GDBRemoteRegisterContext (ThreadGDBRemote &thread, uint32_t concrete_frame_idx, GDBRemoteDynamicRegisterInfoSP reg_info_sp, bool read_all_at_once, bool write_all_at_once)
~GDBRemoteRegisterContext () override
void InvalidateAllRegisters () override
size_t GetRegisterCount () override
const RegisterInfo * GetRegisterInfoAtIndex (size_t reg) override
size_t GetRegisterSetCount () override
const RegisterSet * GetRegisterSet (size_t reg_set) override
bool ReadRegister (const RegisterInfo *reg_info, RegisterValue &value) override
bool WriteRegister (const RegisterInfo *reg_info, const RegisterValue &value) override
bool ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp) override
bool WriteAllRegisterValues (const lldb::DataBufferSP &data_sp) override
bool ReadAllRegisterValues (RegisterCheckpoint &reg_checkpoint) override
bool WriteAllRegisterValues (const RegisterCheckpoint &reg_checkpoint) override
uint32_t ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num) override
Convert from a given register numbering scheme to the lldb register numbering scheme.
bool RegisterWriteCausesReconfigure (const llvm::StringRef name) override
bool ReconfigureRegisterInfo () override
Public Member Functions inherited from lldb_private::RegisterContext
RegisterContext (Thread &thread, uint32_t concrete_frame_idx)
~RegisterContext () override
void InvalidateIfNeeded (bool force)
virtual lldb::ByteOrder GetByteOrder ()
bool CopyFromRegisterContext (lldb::RegisterContextSP context)
virtual uint32_t NumSupportedHardwareBreakpoints ()
virtual uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual bool ClearHardwareBreakpoint (uint32_t hw_idx)
virtual uint32_t NumSupportedHardwareWatchpoints ()
virtual uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, bool read, bool write)
virtual bool ClearHardwareWatchpoint (uint32_t hw_index)
virtual bool HardwareSingleStep (bool enable)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, uint32_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, uint32_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual Thread & GetThread ()
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num)
uint64_t GetPC (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetThreadPointer (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool GetPCForSymbolication (Address &address)
Get an address suitable for symbolication.
bool SetPC (uint64_t pc)
bool SetPC (Address addr)
uint64_t GetSP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetSP (uint64_t sp)
uint64_t GetFP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetFP (uint64_t fp)
const char * GetRegisterName (uint32_t reg)
uint64_t GetReturnAddress (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetFlags (uint64_t fail_value=0)
uint64_t ReadRegisterAsUnsigned (uint32_t reg, uint64_t fail_value)
uint64_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, uint64_t fail_value)
bool WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
bool WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
bool ConvertBetweenRegisterKinds (lldb::RegisterKind source_rk, uint32_t source_regnum, lldb::RegisterKind target_rk, uint32_t &target_regnum)
lldb::TargetSP CalculateTarget () override
lldb::ProcessSP CalculateProcess () override
lldb::ThreadSP CalculateThread () override
lldb::StackFrameSP CalculateStackFrame () override
void CalculateExecutionContext (ExecutionContext &exe_ctx) override
Reconstruct the object's execution context into sc.
uint32_t GetStopID () const
void SetStopID (uint32_t stop_id)
Public Member Functions inherited from lldb_private::ExecutionContextScope
virtual ~ExecutionContextScope ()=default
Protected Member Functions
bool ReadRegisterBytes (const RegisterInfo *reg_info)
bool WriteRegisterBytes (const RegisterInfo *reg_info, DataExtractor &data, uint32_t data_offset)
bool PrivateSetRegisterValue (uint32_t reg, llvm::ArrayRef< uint8_t > data)
bool PrivateSetRegisterValue (uint32_t reg, uint64_t val)
void SetAllRegisterValid (bool b)
bool GetRegisterIsValid (uint32_t reg) const
void SetRegisterIsValid (const RegisterInfo *reg_info, bool valid)
void SetRegisterIsValid (uint32_t reg, bool valid)
Protected Member Functions inherited from lldb_private::RegisterContext
virtual bool BehavesLikeZerothFrame () const
Indicates that this frame is currently executing code, that the PC value is not a return-pc but an actual executing instruction.
Protected Attributes
GDBRemoteDynamicRegisterInfoSP m_reg_info_sp
std::vector< bool > m_reg_valid
DataExtractor m_reg_data
bool m_read_all_at_once
bool m_write_all_at_once
bool m_gpacket_cached
Protected Attributes inherited from lldb_private::RegisterContext
Thread & m_thread
uint32_t m_concrete_frame_idx
uint32_t m_stop_id
Private Member Functions
bool GetPrimordialRegister (const RegisterInfo *reg_info, GDBRemoteCommunicationClient &gdb_comm)
bool SetPrimordialRegister (const RegisterInfo *reg_info, GDBRemoteCommunicationClient &gdb_comm)
GDBRemoteRegisterContext (const GDBRemoteRegisterContext &)=delete
const GDBRemoteRegisterContext & operator= (const GDBRemoteRegisterContext &)=delete
Friends
class ThreadGDBRemote
Detailed Description
Definition at line 45 of file GDBRemoteRegisterContext.h.
Constructor & Destructor Documentation
GDBRemoteRegisterContext() [1/2]
GDBRemoteRegisterContext::GDBRemoteRegisterContext (ThreadGDBRemote & thread, uint32_t concrete_frame_idx, GDBRemoteDynamicRegisterInfoSP reg_info_sp, bool read_all_at_once, bool write_all_at_once)
Definition at line 33 of file GDBRemoteRegisterContext.cpp.
References m_gpacket_cached, m_read_all_at_once, m_reg_data, m_reg_info_sp, m_reg_valid, m_write_all_at_once, lldb_private::RegisterContext::RegisterContext(), and ThreadGDBRemote.
Referenced by GDBRemoteRegisterContext(), operator=(), and lldb_private::wasm::RegisterContextWasm::RegisterContextWasm().
~GDBRemoteRegisterContext()
GDBRemoteRegisterContext::~GDBRemoteRegisterContext () override default
GDBRemoteRegisterContext() [2/2]
lldb_private::process_gdb_remote::GDBRemoteRegisterContext::GDBRemoteRegisterContext (const GDBRemoteRegisterContext &) private delete
References GDBRemoteRegisterContext().
Member Function Documentation
ConvertRegisterKindToRegisterNumber()
uint32_t GDBRemoteRegisterContext::ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num) override virtual
Convert from a given register numbering scheme to the lldb register numbering scheme.
There may be multiple ways to enumerate the registers for a given architecture. ABI references will specify one to be used with DWARF, the register numberings from process plugin, there may be a variation used for eh_frame unwind instructions (e.g. on Darwin), and so on. Register 5 by itself is meaningless - RegisterKind enumeration tells you what context that number should be translated as.
Inside lldb, register numbers are in the eRegisterKindLLDB scheme; arguments which take a register number should take one in that scheme.
eRegisterKindGeneric is a special numbering scheme which gives us constant values for the pc, frame register, stack register, etc., for use within lldb. They may not be defined for all architectures but it allows generic code to translate these common registers into the lldb numbering scheme.
This method translates a given register kind + register number into the eRegisterKindLLDB register numbering.
Parameters
[in] kind The register numbering scheme (RegisterKind) that the following register number is in.
[in] num A register number in the 'kind' register numbering scheme.
Returns
The equivalent register number in the eRegisterKindLLDB numbering scheme, if possible, else LLDB_INVALID_REGNUM.
Reimplemented from lldb_private::RegisterContext.
Reimplemented in lldb_private::wasm::RegisterContextWasm.
Definition at line 758 of file GDBRemoteRegisterContext.cpp.
References m_reg_info_sp.
Referenced by WriteRegisterBytes().
GetPrimordialRegister()
bool GDBRemoteRegisterContext::GetPrimordialRegister (const RegisterInfo * reg_info, GDBRemoteCommunicationClient & gdb_comm) private
Definition at line 194 of file GDBRemoteRegisterContext.cpp.
References lldb::eRegisterKindLLDB, lldb::eRegisterKindProcessPlugin, lldb_private::RegisterInfo::kinds, lldb_private::RegisterContext::m_thread, PrivateSetRegisterValue(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ReadRegister().
Referenced by ReadRegisterBytes().
GetRegisterCount()
size_t GDBRemoteRegisterContext::GetRegisterCount () override virtual
Implements lldb_private::RegisterContext.
Reimplemented in lldb_private::wasm::RegisterContextWasm.
Definition at line 67 of file GDBRemoteRegisterContext.cpp.
References m_reg_info_sp.
GetRegisterInfoAtIndex()
const RegisterInfo * GDBRemoteRegisterContext::GetRegisterInfoAtIndex (size_t reg) override virtual
Implements lldb_private::RegisterContext.
Reimplemented in lldb_private::wasm::RegisterContextWasm.
Definition at line 72 of file GDBRemoteRegisterContext.cpp.
References m_reg_info_sp.
Referenced by PrivateSetRegisterValue(), PrivateSetRegisterValue(), ReadAllRegisterValues(), and WriteAllRegisterValues().
GetRegisterIsValid()
bool lldb_private::process_gdb_remote::GDBRemoteRegisterContext::GetRegisterIsValid (uint32_t reg) const inline protected
Definition at line 99 of file GDBRemoteRegisterContext.h.
References m_reg_valid.
Referenced by ReadRegisterBytes().
GetRegisterSet()
const RegisterSet * GDBRemoteRegisterContext::GetRegisterSet (size_t reg_set) override virtual
Implements lldb_private::RegisterContext.
Reimplemented in lldb_private::wasm::RegisterContextWasm.
Definition at line 80 of file GDBRemoteRegisterContext.cpp.
References m_reg_info_sp.
GetRegisterSetCount()
size_t GDBRemoteRegisterContext::GetRegisterSetCount () override virtual
Implements lldb_private::RegisterContext.
Reimplemented in lldb_private::wasm::RegisterContextWasm.
Definition at line 76 of file GDBRemoteRegisterContext.cpp.
References m_reg_info_sp.
InvalidateAllRegisters()
void GDBRemoteRegisterContext::InvalidateAllRegisters () override virtual
Implements lldb_private::RegisterContext.
Reimplemented in lldb_private::wasm::RegisterContextWasm.
Definition at line 56 of file GDBRemoteRegisterContext.cpp.
References SetAllRegisterValid().
Referenced by ReadAllRegisterValues(), and WriteRegisterBytes().
operator=()
const GDBRemoteRegisterContext & lldb_private::process_gdb_remote::GDBRemoteRegisterContext::operator= (const GDBRemoteRegisterContext &) private delete
References GDBRemoteRegisterContext().
PrivateSetRegisterValue() [1/2]
bool GDBRemoteRegisterContext::PrivateSetRegisterValue (uint32_t reg, llvm::ArrayRef< uint8_t > data) protected
Definition at line 123 of file GDBRemoteRegisterContext.cpp.
References lldb_private::RegisterInfo::byte_offset, lldb_private::RegisterInfo::byte_size, GetRegisterInfoAtIndex(), lldb_private::RegisterContext::InvalidateIfNeeded(), m_reg_data, and SetRegisterIsValid().
Referenced by GetPrimordialRegister(), lldb_private::process_gdb_remote::ThreadGDBRemote::PrivateSetRegisterValue(), and lldb_private::process_gdb_remote::ThreadGDBRemote::PrivateSetRegisterValue().
PrivateSetRegisterValue() [2/2]
bool GDBRemoteRegisterContext::PrivateSetRegisterValue (uint32_t reg, uint64_t val) protected
Definition at line 147 of file GDBRemoteRegisterContext.cpp.
References lldb_private::RegisterInfo::byte_offset, lldb_private::RegisterInfo::byte_size, lldb_private::DataExtractor::CopyByteOrderedData(), lldb::eByteOrderInvalid, GetRegisterInfoAtIndex(), lldb_private::RegisterContext::InvalidateIfNeeded(), m_reg_data, lldb_private::DataExtractor::SetData(), and SetRegisterIsValid().
ReadAllRegisterValues() [1/2]
bool GDBRemoteRegisterContext::ReadAllRegisterValues (lldb::WritableDataBufferSP & data_sp) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 519 of file GDBRemoteRegisterContext.cpp.
References lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::AvoidGPackets(), lldb_private::RegisterContext::CalculateThread(), lldb_private::Process::DumpPluginHistory(), lldb_private::StreamString::GetData(), lldb_private::GetLog(), lldb_private::ExecutionContext::GetProcessPtr(), GetRegisterInfoAtIndex(), lldb_private::ExecutionContext::GetThreadPtr(), lldb_private::Log::GetVerbose(), InvalidateAllRegisters(), LLDB_LOGF, m_reg_data, m_reg_info_sp, lldb_private::RegisterContext::m_thread, lldb_private::process_gdb_remote::Packets, lldb_private::process_gdb_remote::Process, lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ReadAllRegisters(), ReadRegisterBytes(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SyncThreadState(), and lldb_private::process_gdb_remote::Thread.
Referenced by ReadAllRegisterValues().
ReadAllRegisterValues() [2/2]
bool GDBRemoteRegisterContext::ReadAllRegisterValues (RegisterCheckpoint & reg_checkpoint) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 476 of file GDBRemoteRegisterContext.cpp.
References lldb_private::RegisterContext::CalculateThread(), lldb_private::RegisterCheckpoint::GetData(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::ExecutionContext::GetThreadPtr(), lldb_private::process_gdb_remote::Process, ReadAllRegisterValues(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SaveRegisterState(), lldb_private::UserID::SetID(), and lldb_private::process_gdb_remote::Thread.
ReadRegister()
bool GDBRemoteRegisterContext::ReadRegister (const RegisterInfo * reg_info, RegisterValue & value) override virtual
Implements lldb_private::RegisterContext.
Reimplemented in lldb_private::wasm::RegisterContextWasm.
Definition at line 84 of file GDBRemoteRegisterContext.cpp.
References lldb_private::RegisterInfo::byte_offset, lldb_private::RegisterInfo::byte_size, lldb::eRegisterKindLLDB, error(), lldb_private::RegisterContext::GetRegisterInfo(), lldb_private::RegisterInfo::kinds, LLDB_INVALID_REGNUM, m_reg_data, m_reg_valid, ReadRegisterBytes(), lldb_private::RegisterValue::SetFromMemoryData(), lldb_private::RegisterValue::SetValueFromData(), and lldb_private::RegisterInfo::value_regs.
Referenced by lldb_private::wasm::RegisterContextWasm::ReadRegister().
ReadRegisterBytes()
bool GDBRemoteRegisterContext::ReadRegisterBytes (const RegisterInfo * reg_info) protected
Definition at line 207 of file GDBRemoteRegisterContext.cpp.
References lldb_private::RegisterInfo::byte_offset, lldb_private::RegisterInfo::byte_size, lldb_private::RegisterContext::CalculateThread(), lldb::eRegisterKindLLDB, lldb_private::GetLog(), GetPrimordialRegister(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::RegisterContext::GetRegisterInfo(), GetRegisterIsValid(), lldb_private::ExecutionContext::GetThreadPtr(), lldb_private::RegisterContext::InvalidateIfNeeded(), lldb_private::RegisterInfo::kinds, LLDB_INVALID_REGNUM, LLDB_LOGF, m_gpacket_cached, m_read_all_at_once, m_reg_data, m_reg_info_sp, m_reg_valid, lldb_private::RegisterContext::m_thread, lldb_private::process_gdb_remote::Packets, lldb_private::process_gdb_remote::Process, lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ReadAllRegisters(), SetAllRegisterValid(), SetRegisterIsValid(), lldb_private::process_gdb_remote::Thread, and lldb_private::RegisterInfo::value_regs.
Referenced by ReadAllRegisterValues(), and ReadRegister().
ReconfigureRegisterInfo()
bool GDBRemoteRegisterContext::ReconfigureRegisterInfo () override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 771 of file GDBRemoteRegisterContext.cpp.
References lldb_private::RegisterContext::CalculateThread(), lldb_private::Target::GetArchitecturePlugin(), lldb_private::ExecutionContext::GetProcessRef(), lldb_private::Process::GetTarget(), m_reg_data, m_reg_info_sp, and lldb_private::Architecture::ReconfigureRegisterInfo().
Referenced by WriteRegisterBytes().
RegisterWriteCausesReconfigure()
bool GDBRemoteRegisterContext::RegisterWriteCausesReconfigure (const llvm::StringRef name) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 763 of file GDBRemoteRegisterContext.cpp.
References lldb_private::RegisterContext::CalculateThread(), lldb_private::Target::GetArchitecturePlugin(), lldb_private::ExecutionContext::GetProcessRef(), lldb_private::Process::GetTarget(), and lldb_private::Architecture::RegisterWriteCausesReconfigure().
Referenced by WriteRegisterBytes().
SetAllRegisterValid()
void GDBRemoteRegisterContext::SetAllRegisterValid (bool b) protected
Definition at line 60 of file GDBRemoteRegisterContext.cpp.
References m_gpacket_cached, and m_reg_valid.
Referenced by InvalidateAllRegisters(), and ReadRegisterBytes().
SetPrimordialRegister()
bool GDBRemoteRegisterContext::SetPrimordialRegister (const RegisterInfo * reg_info, GDBRemoteCommunicationClient & gdb_comm) private
Definition at line 339 of file GDBRemoteRegisterContext.cpp.
References lldb::eRegisterKindLLDB, lldb::eRegisterKindProcessPlugin, lldb_private::RegisterInfo::kinds, lldb_private::RegisterContext::m_thread, SetRegisterIsValid(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteRegister().
Referenced by WriteRegisterBytes().
SetRegisterIsValid() [1/2]
void lldb_private::process_gdb_remote::GDBRemoteRegisterContext::SetRegisterIsValid (const RegisterInfo * reg_info, bool valid) inline protected
Definition at line 106 of file GDBRemoteRegisterContext.h.
References lldb::eRegisterKindLLDB, lldb_private::RegisterInfo::kinds, and SetRegisterIsValid().
Referenced by PrivateSetRegisterValue(), PrivateSetRegisterValue(), ReadRegisterBytes(), SetPrimordialRegister(), SetRegisterIsValid(), WriteAllRegisterValues(), and WriteRegisterBytes().
SetRegisterIsValid() [2/2]
void lldb_private::process_gdb_remote::GDBRemoteRegisterContext::SetRegisterIsValid (uint32_t reg, bool valid) inline protected
Definition at line 112 of file GDBRemoteRegisterContext.h.
References m_reg_valid.
WriteAllRegisterValues() [1/2]
bool GDBRemoteRegisterContext::WriteAllRegisterValues (const lldb::DataBufferSP & data_sp) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 585 of file GDBRemoteRegisterContext.cpp.
References lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::AvoidGPackets(), lldb_private::RegisterInfo::byte_offset, lldb_private::RegisterInfo::byte_size, lldb_private::RegisterContext::CalculateThread(), lldb_private::Process::DumpPluginHistory(), lldb::eRegisterKindLLDB, lldb::eRegisterKindProcessPlugin, lldb_private::DataExtractor::GetByteSize(), lldb_private::StreamString::GetData(), lldb_private::GetLog(), lldb_private::ArchSpec::GetMachine(), lldb_private::ExecutionContext::GetProcessPtr(), GetRegisterInfoAtIndex(), lldb_private::ExecutionContext::GetThreadPtr(), lldb_private::ArchSpec::GetTriple(), lldb_private::Log::GetVerbose(), lldb_private::ArchSpec::IsValid(), lldb_private::RegisterInfo::kinds, LLDB_LOGF, m_reg_data, lldb_private::RegisterContext::m_thread, lldb_private::RegisterInfo::name, lldb_private::process_gdb_remote::Packets, lldb_private::DataExtractor::PeekData(), lldb_private::process_gdb_remote::Process, SetRegisterIsValid(), lldb_private::process_gdb_remote::Thread, lldb_private::RegisterInfo::value_regs, lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteAllRegisters(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteRegister().
Referenced by WriteAllRegisterValues().
WriteAllRegisterValues() [2/2]
bool GDBRemoteRegisterContext::WriteAllRegisterValues (const RegisterCheckpoint & reg_checkpoint) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 499 of file GDBRemoteRegisterContext.cpp.
References lldb_private::RegisterContext::CalculateThread(), lldb_private::RegisterCheckpoint::GetData(), lldb_private::UserID::GetID(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::ExecutionContext::GetThreadPtr(), lldb_private::RegisterContext::m_thread, lldb_private::process_gdb_remote::Process, lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::RestoreRegisterState(), lldb_private::process_gdb_remote::Thread, and WriteAllRegisterValues().
WriteRegister()
bool GDBRemoteRegisterContext::WriteRegister (const RegisterInfo * reg_info, const RegisterValue & value) override virtual
Implements lldb_private::RegisterContext.
Reimplemented in lldb_private::wasm::RegisterContextWasm.
Definition at line 300 of file GDBRemoteRegisterContext.cpp.
References lldb_private::RegisterInfo::byte_size, lldb::eRegisterKindLLDB, lldb_private::DataExtractor::GetByteSize(), lldb_private::RegisterValue::GetData(), lldb_private::RegisterContext::GetRegisterInfo(), LLDB_INVALID_REGNUM, lldb_private::RegisterInfo::value_regs, and WriteRegisterBytes().
Referenced by lldb_private::wasm::RegisterContextWasm::WriteRegister().
WriteRegisterBytes()
bool GDBRemoteRegisterContext::WriteRegisterBytes (const RegisterInfo * reg_info, DataExtractor & data, uint32_t data_offset) protected
Definition at line 353 of file GDBRemoteRegisterContext.cpp.
References lldb_private::RegisterInfo::byte_offset, lldb_private::RegisterInfo::byte_size, lldb_private::RegisterContext::CalculateThread(), ConvertRegisterKindToRegisterNumber(), lldb_private::DataExtractor::CopyByteOrderedData(), lldb_private::Process::DumpPluginHistory(), lldb::eRegisterKindLLDB, lldb_private::StreamString::GetData(), lldb_private::GetLog(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::RegisterContext::GetRegisterInfo(), lldb_private::ExecutionContext::GetThreadPtr(), lldb_private::Log::GetVerbose(), lldb_private::RegisterInfo::invalidate_regs, InvalidateAllRegisters(), lldb_private::RegisterContext::InvalidateIfNeeded(), LLDB_INVALID_REGNUM, LLDB_LOGF, m_reg_data, lldb_private::RegisterContext::m_thread, m_write_all_at_once, lldb_private::RegisterInfo::name, lldb_private::process_gdb_remote::Packets, lldb_private::process_gdb_remote::Process, ReconfigureRegisterInfo(), RegisterWriteCausesReconfigure(), SetPrimordialRegister(), SetRegisterIsValid(), lldb_private::process_gdb_remote::Thread, lldb_private::RegisterInfo::value_regs, and lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteAllRegisters().
Referenced by WriteRegister().
Friends And Related Symbol Documentation
ThreadGDBRemote
friend class ThreadGDBRemote friend
Definition at line 86 of file GDBRemoteRegisterContext.h.
References ThreadGDBRemote.
Referenced by GDBRemoteRegisterContext(), lldb_private::wasm::RegisterContextWasm::RegisterContextWasm(), and ThreadGDBRemote.
Member Data Documentation
m_gpacket_cached
bool lldb_private::process_gdb_remote::GDBRemoteRegisterContext::m_gpacket_cached protected
Definition at line 123 of file GDBRemoteRegisterContext.h.
Referenced by GDBRemoteRegisterContext(), ReadRegisterBytes(), and SetAllRegisterValid().
m_read_all_at_once
bool lldb_private::process_gdb_remote::GDBRemoteRegisterContext::m_read_all_at_once protected
Definition at line 121 of file GDBRemoteRegisterContext.h.
Referenced by GDBRemoteRegisterContext(), and ReadRegisterBytes().
m_reg_data
DataExtractor lldb_private::process_gdb_remote::GDBRemoteRegisterContext::m_reg_data protected
Definition at line 120 of file GDBRemoteRegisterContext.h.
Referenced by GDBRemoteRegisterContext(), PrivateSetRegisterValue(), PrivateSetRegisterValue(), ReadAllRegisterValues(), ReadRegister(), ReadRegisterBytes(), ReconfigureRegisterInfo(), WriteAllRegisterValues(), and WriteRegisterBytes().
m_reg_info_sp
GDBRemoteDynamicRegisterInfoSP lldb_private::process_gdb_remote::GDBRemoteRegisterContext::m_reg_info_sp protected
Definition at line 118 of file GDBRemoteRegisterContext.h.
Referenced by ConvertRegisterKindToRegisterNumber(), GDBRemoteRegisterContext(), GetRegisterCount(), GetRegisterInfoAtIndex(), lldb_private::wasm::RegisterContextWasm::GetRegisterInfoAtIndex(), GetRegisterSet(), GetRegisterSetCount(), ReadAllRegisterValues(), ReadRegisterBytes(), and ReconfigureRegisterInfo().
m_reg_valid
std::vector<bool> lldb_private::process_gdb_remote::GDBRemoteRegisterContext::m_reg_valid protected
Definition at line 119 of file GDBRemoteRegisterContext.h.
Referenced by GDBRemoteRegisterContext(), GetRegisterIsValid(), ReadRegister(), ReadRegisterBytes(), SetAllRegisterValid(), and SetRegisterIsValid().
m_write_all_at_once
bool lldb_private::process_gdb_remote::GDBRemoteRegisterContext::m_write_all_at_once protected
Definition at line 122 of file GDBRemoteRegisterContext.h.
Referenced by GDBRemoteRegisterContext(), and WriteRegisterBytes().
The documentation for this class was generated from the following files:
GDBRemoteRegisterContext.h
GDBRemoteRegisterContext.cpp