LLDB: lldb_private::Listener Class Reference
lldb_private::Listener Class Reference
#include <Listener.h>
Classes
struct BroadcasterInfo
Public Types
typedef bool(* HandleBroadcastCallback) (lldb::EventSP &event_sp, void *baton)
Public Member Functions
~Listener ()
void AddEvent (lldb::EventSP &event)
void Clear ()
const char * GetName ()
uint32_t StartListeningForEventSpec (const lldb::BroadcasterManagerSP &manager_sp, const BroadcastEventSpec &event_spec)
bool StopListeningForEventSpec (const lldb::BroadcasterManagerSP &manager_sp, const BroadcastEventSpec &event_spec)
uint32_t StartListeningForEvents (Broadcaster *broadcaster, uint32_t event_mask)
uint32_t StartListeningForEvents (Broadcaster *broadcaster, uint32_t event_mask, HandleBroadcastCallback callback, void *callback_user_data)
bool StopListeningForEvents (Broadcaster *broadcaster, uint32_t event_mask)
Event * PeekAtNextEvent ()
Event * PeekAtNextEventForBroadcaster (Broadcaster *broadcaster)
Event * PeekAtNextEventForBroadcasterWithType (Broadcaster *broadcaster, uint32_t event_type_mask)
bool GetEvent (lldb::EventSP &event_sp, const Timeout< std::micro > &timeout)
bool GetEventForBroadcaster (Broadcaster *broadcaster, lldb::EventSP &event_sp, const Timeout< std::micro > &timeout)
bool GetEventForBroadcasterWithType (Broadcaster *broadcaster, uint32_t event_type_mask, lldb::EventSP &event_sp, const Timeout< std::micro > &timeout)
size_t HandleBroadcastEvent (lldb::EventSP &event_sp)
Static Public Member Functions
static lldb::ListenerSP MakeListener (const char *name)
Protected Member Functions
Listener (const char *name)
Private Types
typedef std::multimap< Broadcaster::BroadcasterImplWP, BroadcasterInfo, std::owner_less< Broadcaster::BroadcasterImplWP > > broadcaster_collection
typedef std::list< lldb::EventSP > event_collection
typedef std::vector< lldb::BroadcasterManagerWP > broadcaster_manager_collection
Private Member Functions
bool FindNextEventInternal (std::unique_lock< std::mutex > &lock, Broadcaster *broadcaster, uint32_t event_type_mask, lldb::EventSP &event_sp, bool remove)
bool GetEventInternal (const Timeout< std::micro > &timeout, Broadcaster *broadcaster, uint32_t event_type_mask, lldb::EventSP &event_sp)
void BroadcasterWillDestruct (Broadcaster *)
void BroadcasterManagerWillDestruct (lldb::BroadcasterManagerSP manager_sp)
Listener (const Listener &)=delete
const Listener & operator= (const Listener &)=delete
Private Attributes
std::string m_name
broadcaster_collection m_broadcasters
std::mutex m_broadcasters_mutex
event_collection m_events
std::mutex m_events_mutex
std::condition_variable m_events_condition
broadcaster_manager_collection m_broadcaster_managers
Friends
class Broadcaster
class BroadcasterManager
Detailed Description
Definition at line 35 of file Listener.h.
Member Typedef Documentation
broadcaster_collection
typedef std::multimap<Broadcaster::BroadcasterImplWP, BroadcasterInfo, std::owner_less<Broadcaster::BroadcasterImplWP> > lldb_private::Listener::broadcaster_collection private
Definition at line 111 of file Listener.h.
broadcaster_manager_collection
typedef std::vector<lldb::BroadcasterManagerWP> lldb_private::Listener::broadcaster_manager_collection private
Definition at line 114 of file Listener.h.
event_collection
typedef std::list<lldb::EventSP> lldb_private::Listener::event_collection private
Definition at line 112 of file Listener.h.
HandleBroadcastCallback
typedef bool(* lldb_private::Listener::HandleBroadcastCallback) (lldb::EventSP &event_sp, void *baton)
Definition at line 37 of file Listener.h.
Constructor & Destructor Documentation
Listener() [1/2]
Listener::Listener (const char * name) protected
Definition at line 21 of file Listener.cpp.
References lldb_private::GetLog(), LLDB_LOGF, m_name, and lldb_private::Object.
Referenced by Listener(), MakeListener(), and operator=().
~Listener()
Listener::~Listener ()
Definition at line 26 of file Listener.cpp.
References lldb_private::GetLog(), LLDB_LOGF, m_name, and lldb_private::Object.
Listener() [2/2]
lldb_private::Listener::Listener (const Listener &) private delete
References Listener().
Member Function Documentation
AddEvent()
void Listener::AddEvent (lldb::EventSP & event)
Definition at line 167 of file Listener.cpp.
References lldb_private::Events, lldb_private::GetLog(), LLDB_LOGF, m_events, m_events_condition, m_events_mutex, and m_name.
BroadcasterManagerWillDestruct()
void Listener::BroadcasterManagerWillDestruct (lldb::BroadcasterManagerSP manager_sp) private
Definition at line 158 of file Listener.cpp.
References m_broadcaster_managers.
BroadcasterWillDestruct()
void Listener::BroadcasterWillDestruct (Broadcaster * broadcaster) private
Definition at line 137 of file Listener.cpp.
References Broadcaster, lldb_private::Broadcaster::GetBroadcasterImpl(), m_broadcasters, m_broadcasters_mutex, m_events, and m_events_mutex.
Clear()
void Listener::Clear ()
Definition at line 33 of file Listener.cpp.
References lldb_private::GetLog(), LLDB_LOGF, m_broadcaster_managers, m_broadcasters, m_broadcasters_mutex, m_events, m_events_mutex, m_name, and lldb_private::Object.
FindNextEventInternal()
bool Listener::FindNextEventInternal (std::unique_lock< std::mutex > & lock, Broadcaster * broadcaster, uint32_t event_type_mask, lldb::EventSP & event_sp, bool remove) private
Definition at line 179 of file Listener.cpp.
References Broadcaster, lldb_private::Events, lldb_private::GetLog(), GetName(), LLDB_LOGF, and m_events.
Referenced by GetEventInternal(), PeekAtNextEvent(), PeekAtNextEventForBroadcaster(), and PeekAtNextEventForBroadcasterWithType().
GetEvent()
bool Listener::GetEvent (lldb::EventSP & event_sp, const Timeout< std::micro > & timeout)
Definition at line 308 of file Listener.cpp.
References GetEventInternal().
GetEventForBroadcaster()
bool Listener::GetEventForBroadcaster (Broadcaster * broadcaster, lldb::EventSP & event_sp, const Timeout< std::micro > & timeout)
Definition at line 302 of file Listener.cpp.
References Broadcaster, and GetEventInternal().
GetEventForBroadcasterWithType()
bool Listener::GetEventForBroadcasterWithType (Broadcaster * broadcaster, uint32_t event_type_mask, lldb::EventSP & event_sp, const Timeout< std::micro > & timeout)
Definition at line 296 of file Listener.cpp.
References Broadcaster, and GetEventInternal().
GetEventInternal()
bool Listener::GetEventInternal (const Timeout< std::micro > & timeout, Broadcaster * broadcaster, uint32_t event_type_mask, lldb::EventSP & event_sp) private
Definition at line 259 of file Listener.cpp.
References Broadcaster, lldb_private::Events, FindNextEventInternal(), lldb_private::GetLog(), LLDB_LOG, LLDB_LOGF, m_events_condition, m_events_mutex, and m_name.
Referenced by GetEvent(), GetEventForBroadcaster(), and GetEventForBroadcasterWithType().
GetName()
const char * lldb_private::Listener::GetName () inline
Definition at line 58 of file Listener.h.
References m_name.
Referenced by FindNextEventInternal().
HandleBroadcastEvent()
size_t Listener::HandleBroadcastEvent (lldb::EventSP & event_sp)
Definition at line 312 of file Listener.cpp.
References Broadcaster, lldb_private::Listener::BroadcasterInfo::callback, lldb_private::Listener::BroadcasterInfo::callback_user_data, lldb_private::Listener::BroadcasterInfo::event_mask, lldb_private::Broadcaster::GetBroadcasterImpl(), m_broadcasters, and m_broadcasters_mutex.
MakeListener()
ListenerSP Listener::MakeListener (const char * name) static
Definition at line 375 of file Listener.cpp.
References Listener().
Referenced by ProcessKDP::AsyncThread(), lldb_private::Target::Attach(), PlatformPOSIX::Attach(), lldb_private::ProcessTrace::DidAttach(), lldb_private::Platform::DoConnectProcess(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoResume(), lldb_private::Process::Halt(), lldb_private::Target::Launch(), lldb_private::Process::LaunchPrivate(), lldb_private::Process::LoadCore(), lldb_private::ThreadedCommunication::Read(), lldb_private::Process::ResumeSynchronous(), lldb_private::Process::RunThreadPlan(), lldb_private::Debugger::StartEventHandlerThread(), lldb_private::Process::StopForDestroyOrDetach(), and lldb_private::ThreadedCommunication::SynchronizeWithReadThread().
operator=()
const Listener & lldb_private::Listener::operator= (const Listener &) private delete
References Listener().
PeekAtNextEvent()
Event * Listener::PeekAtNextEvent ()
Definition at line 232 of file Listener.cpp.
References FindNextEventInternal(), and m_events_mutex.
PeekAtNextEventForBroadcaster()
Event * Listener::PeekAtNextEventForBroadcaster (Broadcaster * broadcaster)
Definition at line 240 of file Listener.cpp.
References Broadcaster, FindNextEventInternal(), and m_events_mutex.
PeekAtNextEventForBroadcasterWithType()
Event * Listener::PeekAtNextEventForBroadcasterWithType (Broadcaster * broadcaster, uint32_t event_type_mask)
Definition at line 249 of file Listener.cpp.
References Broadcaster, FindNextEventInternal(), and m_events_mutex.
StartListeningForEvents() [1/2]
uint32_t Listener::StartListeningForEvents (Broadcaster * broadcaster, uint32_t event_mask)
Definition at line 58 of file Listener.cpp.
References lldb_private::Broadcaster::AddListener(), Broadcaster, lldb_private::Events, lldb_private::Broadcaster::GetBroadcasterImpl(), lldb_private::GetLog(), LLDB_LOGF, m_broadcasters, m_broadcasters_mutex, and m_name.
StartListeningForEvents() [2/2]
uint32_t Listener::StartListeningForEvents (Broadcaster * broadcaster, uint32_t event_mask, HandleBroadcastCallback callback, void * callback_user_data)
Definition at line 86 of file Listener.cpp.
References lldb_private::Broadcaster::AddListener(), Broadcaster, lldb_private::Events, lldb_private::Broadcaster::GetBroadcasterImpl(), lldb_private::GetLog(), LLDB_LOGF, m_broadcasters, m_broadcasters_mutex, and m_name.
StartListeningForEventSpec()
uint32_t Listener::StartListeningForEventSpec (const lldb::BroadcasterManagerSP & manager_sp, const BroadcastEventSpec & event_spec)
Definition at line 336 of file Listener.cpp.
References m_broadcaster_managers, and m_broadcasters_mutex.
StopListeningForEvents()
bool Listener::StopListeningForEvents (Broadcaster * broadcaster, uint32_t event_mask)
Definition at line 120 of file Listener.cpp.
References Broadcaster, lldb_private::Broadcaster::GetBroadcasterImpl(), m_broadcasters, m_broadcasters_mutex, and lldb_private::Broadcaster::RemoveListener().
StopListeningForEventSpec()
bool Listener::StopListeningForEventSpec (const lldb::BroadcasterManagerSP & manager_sp, const BroadcastEventSpec & event_spec)
Definition at line 362 of file Listener.cpp.
References m_broadcasters_mutex.
Friends And Related Symbol Documentation
Broadcaster
friend class Broadcaster friend
Definition at line 39 of file Listener.h.
References Broadcaster.
Referenced by Broadcaster, BroadcasterWillDestruct(), FindNextEventInternal(), GetEventForBroadcaster(), GetEventForBroadcasterWithType(), GetEventInternal(), HandleBroadcastEvent(), PeekAtNextEventForBroadcaster(), PeekAtNextEventForBroadcasterWithType(), StartListeningForEvents(), StartListeningForEvents(), and StopListeningForEvents().
BroadcasterManager
friend class BroadcasterManager friend
Definition at line 40 of file Listener.h.
References BroadcasterManager.
Referenced by BroadcasterManager.
Member Data Documentation
m_broadcaster_managers
broadcaster_manager_collection lldb_private::Listener::m_broadcaster_managers private
Definition at line 132 of file Listener.h.
Referenced by BroadcasterManagerWillDestruct(), Clear(), and StartListeningForEventSpec().
m_broadcasters
broadcaster_collection lldb_private::Listener::m_broadcasters private
Definition at line 127 of file Listener.h.
Referenced by BroadcasterWillDestruct(), Clear(), HandleBroadcastEvent(), StartListeningForEvents(), StartListeningForEvents(), and StopListeningForEvents().
m_broadcasters_mutex
std::mutex lldb_private::Listener::m_broadcasters_mutex private
Definition at line 128 of file Listener.h.
Referenced by BroadcasterWillDestruct(), Clear(), HandleBroadcastEvent(), StartListeningForEvents(), StartListeningForEvents(), StartListeningForEventSpec(), StopListeningForEvents(), and StopListeningForEventSpec().
m_events
event_collection lldb_private::Listener::m_events private
Definition at line 129 of file Listener.h.
Referenced by AddEvent(), BroadcasterWillDestruct(), Clear(), and FindNextEventInternal().
m_events_condition
std::condition_variable lldb_private::Listener::m_events_condition private
Definition at line 131 of file Listener.h.
Referenced by AddEvent(), and GetEventInternal().
m_events_mutex
std::mutex lldb_private::Listener::m_events_mutex private
Definition at line 130 of file Listener.h.
Referenced by AddEvent(), BroadcasterWillDestruct(), Clear(), GetEventInternal(), PeekAtNextEvent(), PeekAtNextEventForBroadcaster(), and PeekAtNextEventForBroadcasterWithType().
m_name
std::string lldb_private::Listener::m_name private
Definition at line 126 of file Listener.h.
Referenced by AddEvent(), Clear(), GetEventInternal(), GetName(), Listener(), StartListeningForEvents(), StartListeningForEvents(), and ~Listener().
The documentation for this class was generated from the following files:
Listener.h
Listener.cpp