LLDB: lldb_private::plugin::dwarf::DWARFDebugAranges Class Reference
lldb_private::plugin::dwarf::DWARFDebugAranges Class Reference
#include <DWARFDebugAranges.h>
Public Types
typedef RangeToDIE::Entry Range
typedef std::vector< RangeToDIE::Entry > RangeColl
Public Member Functions
DWARFDebugAranges ()
void Clear ()
void extract (const DWARFDataExtractor &debug_aranges_data)
void AppendRange (dw_offset_t cu_offset, dw_addr_t low_pc, dw_addr_t high_pc)
void Sort (bool minimize)
void Dump (Log *log) const
dw_offset_t FindAddress (dw_addr_t address) const
bool IsEmpty () const
size_t GetNumRanges () const
dw_offset_t OffsetAtIndex (uint32_t idx) const
Protected Types
typedef RangeDataVector< dw_addr_t, uint32_t, dw_offset_t > RangeToDIE
Protected Attributes
RangeToDIE m_aranges
Detailed Description
Definition at line 18 of file DWARFDebugAranges.h.
Member Typedef Documentation
Range
typedef RangeToDIE::Entry lldb_private::plugin::dwarf::DWARFDebugAranges::Range
Definition at line 23 of file DWARFDebugAranges.h.
RangeColl
typedef std::vector<RangeToDIE::Entry> lldb_private::plugin::dwarf::DWARFDebugAranges::RangeColl
Definition at line 24 of file DWARFDebugAranges.h.
RangeToDIE
typedef RangeDataVector<dw_addr_t, uint32_t, dw_offset_t> lldb_private::plugin::dwarf::DWARFDebugAranges::RangeToDIE protected
Definition at line 20 of file DWARFDebugAranges.h.
Constructor & Destructor Documentation
DWARFDebugAranges()
DWARFDebugAranges::DWARFDebugAranges ()
Definition at line 22 of file DWARFDebugAranges.cpp.
References m_aranges.
Member Function Documentation
AppendRange()
void DWARFDebugAranges::AppendRange (dw_offset_t cu_offset, dw_addr_t low_pc, dw_addr_t high_pc)
Definition at line 64 of file DWARFDebugAranges.cpp.
References m_aranges.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::AddOSOARanges(), lldb_private::plugin::dwarf::DWARFCompileUnit::BuildAddressRangeTable(), and lldb_private::plugin::dwarf::DWARFDebugInfoEntry::BuildFunctionAddressRangeTable().
Clear()
void lldb_private::plugin::dwarf::DWARFDebugAranges::Clear () inline
Definition at line 28 of file DWARFDebugAranges.h.
References m_aranges.
Dump()
void DWARFDebugAranges::Dump (Log * log) const
Definition at line 51 of file DWARFDebugAranges.cpp.
References lldb_private::RangeData< B, S, T >::data, lldb_private::Range< B, S >::GetRangeBase(), lldb_private::Range< B, S >::GetRangeEnd(), LLDB_LOG, and m_aranges.
extract()
void DWARFDebugAranges::extract (const DWARFDataExtractor & debug_aranges_data)
Definition at line 25 of file DWARFDebugAranges.cpp.
References lldb_private::DebugInfo, error(), lldb_private::DWARFDataExtractor::GetAsLLVMDWARF(), lldb_private::GetLog(), LLDB_LOG_ERROR, and m_aranges.
FindAddress()
dw_offset_t DWARFDebugAranges::FindAddress (dw_addr_t address) const
Definition at line 78 of file DWARFDebugAranges.cpp.
References lldb_private::RangeData< B, S, T >::data, DW_INVALID_OFFSET, and m_aranges.
Referenced by lldb_private::plugin::dwarf::DWARFCompileUnit::LookupAddress().
GetNumRanges()
size_t lldb_private::plugin::dwarf::DWARFDebugAranges::GetNumRanges () const inline
Definition at line 42 of file DWARFDebugAranges.h.
References m_aranges.
Referenced by lldb_private::plugin::dwarf::DWARFCompileUnit::BuildAddressRangeTable().
IsEmpty()
bool lldb_private::plugin::dwarf::DWARFDebugAranges::IsEmpty () const inline
Definition at line 41 of file DWARFDebugAranges.h.
References m_aranges.
Referenced by lldb_private::plugin::dwarf::DWARFCompileUnit::LookupAddress().
OffsetAtIndex()
dw_offset_t lldb_private::plugin::dwarf::DWARFDebugAranges::OffsetAtIndex (uint32_t idx) const inline
Definition at line 44 of file DWARFDebugAranges.h.
References lldb_private::RangeData< B, S, T >::data, DW_INVALID_OFFSET, and m_aranges.
Sort()
void DWARFDebugAranges::Sort (bool minimize)
Definition at line 70 of file DWARFDebugAranges.cpp.
References LLDB_SCOPED_TIMER, and m_aranges.
Member Data Documentation
m_aranges
RangeToDIE lldb_private::plugin::dwarf::DWARFDebugAranges::m_aranges protected
Definition at line 52 of file DWARFDebugAranges.h.
Referenced by AppendRange(), Clear(), Dump(), DWARFDebugAranges(), extract(), FindAddress(), GetNumRanges(), IsEmpty(), OffsetAtIndex(), and Sort().
The documentation for this class was generated from the following files:
DWARFDebugAranges.h
DWARFDebugAranges.cpp