LLDB: lldb_private::process_gdb_remote::GDBRemoteClientBase::ContinueLock Class Reference
lldb_private::process_gdb_remote::GDBRemoteClientBase::ContinueLock Class Reference
Public Types
enum class LockResult { Success , Cancelled , Failed }
Public Member Functions
ContinueLock (GDBRemoteClientBase &comm)
~ContinueLock ()
operator bool ()
LockResult lock ()
void unlock ()
Private Attributes
GDBRemoteClientBase & m_comm
bool m_acquired
Detailed Description
Definition at line 161 of file GDBRemoteClientBase.h.
Member Enumeration Documentation
LockResult
enum class lldb_private::process_gdb_remote::GDBRemoteClientBase::ContinueLock::LockResult strong
Enumerator
Success
Cancelled
Failed
Definition at line 163 of file GDBRemoteClientBase.h.
Constructor & Destructor Documentation
ContinueLock()
GDBRemoteClientBase::ContinueLock::ContinueLock (GDBRemoteClientBase & comm) explicit
Definition at line 307 of file GDBRemoteClientBase.cpp.
References lldb_private::process_gdb_remote::GDBRemoteClientBase::GDBRemoteClientBase(), lock(), m_acquired, and m_comm.
~ContinueLock()
GDBRemoteClientBase::ContinueLock::~ContinueLock ()
Definition at line 312 of file GDBRemoteClientBase.cpp.
References m_acquired, and unlock().
Member Function Documentation
lock()
GDBRemoteClientBase::ContinueLock::LockResult GDBRemoteClientBase::ContinueLock::lock ()
Definition at line 328 of file GDBRemoteClientBase.cpp.
References Cancelled, Failed, lldb_private::GetLog(), LLDB_LOGF, lldbassert, lock(), m_acquired, m_comm, lldb_private::process_gdb_remote::Process, Success, and lldb_private::process_gdb_remote::GDBRemoteCommunication::Success.
Referenced by ContinueLock(), lock(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendContinuePacketAndWaitForResponse(), and unlock().
operator bool()
lldb_private::process_gdb_remote::GDBRemoteClientBase::ContinueLock::operator bool () inline explicit
Definition at line 167 of file GDBRemoteClientBase.h.
References m_acquired.
unlock()
void GDBRemoteClientBase::ContinueLock::unlock ()
Definition at line 317 of file GDBRemoteClientBase.cpp.
References lldbassert, lock(), m_acquired, and m_comm.
Referenced by lldb_private::process_gdb_remote::GDBRemoteClientBase::SendContinuePacketAndWaitForResponse(), and ~ContinueLock().
Member Data Documentation
m_acquired
bool lldb_private::process_gdb_remote::GDBRemoteClientBase::ContinueLock::m_acquired private
Definition at line 175 of file GDBRemoteClientBase.h.
Referenced by ContinueLock(), lock(), operator bool(), unlock(), and ~ContinueLock().
m_comm
GDBRemoteClientBase& lldb_private::process_gdb_remote::GDBRemoteClientBase::ContinueLock::m_comm private
Definition at line 174 of file GDBRemoteClientBase.h.
Referenced by ContinueLock(), lock(), and unlock().
The documentation for this class was generated from the following files:
GDBRemoteClientBase.h
GDBRemoteClientBase.cpp