LLDB: lldb_private::StructuredData::Dictionary Class Reference
lldb_private::StructuredData::Dictionary Class Reference
#include <StructuredData.h>
Public Member Functions
Dictionary ()
Dictionary (ObjectSP obj_sp)
~Dictionary () override=default
size_t GetSize () const
void ForEach (std::function< bool(llvm::StringRef key, Object *object)> const &callback) const
ArraySP GetKeys () const
ObjectSP GetValueForKey (llvm::StringRef key) const
bool GetValueForKeyAsBoolean (llvm::StringRef key, bool &result) const
template<class IntType>
bool GetValueForKeyAsInteger (llvm::StringRef key, IntType &result) const
template<class IntType>
bool GetValueForKeyAsInteger (llvm::StringRef key, IntType &result, IntType default_val) const
bool GetValueForKeyAsString (llvm::StringRef key, llvm::StringRef &result) const
bool GetValueForKeyAsString (llvm::StringRef key, llvm::StringRef &result, const char *default_val) const
bool GetValueForKeyAsDictionary (llvm::StringRef key, Dictionary *&result) const
bool GetValueForKeyAsArray (llvm::StringRef key, Array *&result) const
bool HasKey (llvm::StringRef key) const
void AddItem (llvm::StringRef key, ObjectSP value_sp)
template<typename T>
void AddIntegerItem (llvm::StringRef key, T value)
void AddFloatItem (llvm::StringRef key, double value)
void AddStringItem (llvm::StringRef key, llvm::StringRef value)
void AddBooleanItem (llvm::StringRef key, bool value)
void Serialize (llvm::json::OStream &s) const override
void GetDescription (lldb_private::Stream &s) const override
Public Member Functions inherited from lldb_private::StructuredData::Object
Object (lldb::StructuredDataType t=lldb::eStructuredDataTypeInvalid)
virtual ~Object ()=default
virtual bool IsValid () const
virtual void Clear ()
lldb::StructuredDataType GetType () const
void SetType (lldb::StructuredDataType t)
Array * GetAsArray ()
Dictionary * GetAsDictionary ()
UnsignedInteger * GetAsUnsignedInteger ()
SignedInteger * GetAsSignedInteger ()
uint64_t GetUnsignedIntegerValue (uint64_t fail_value=0)
int64_t GetSignedIntegerValue (int64_t fail_value=0)
Float * GetAsFloat ()
double GetFloatValue (double fail_value=0.0)
Boolean * GetAsBoolean ()
bool GetBooleanValue (bool fail_value=false)
String * GetAsString ()
llvm::StringRef GetStringValue (const char *fail_value=nullptr)
Generic * GetAsGeneric ()
ObjectSP GetObjectForDotSeparatedPath (llvm::StringRef path)
void DumpToStdout (bool pretty_print=true) const
void Dump (lldb_private::Stream &s, bool pretty_print=true) const
Protected Attributes
llvm::StringMap< ObjectSP > m_dict
Detailed Description
Definition at line 384 of file StructuredData.h.
Constructor & Destructor Documentation
Dictionary() [1/2]
lldb_private::StructuredData::Dictionary::Dictionary () inline
Definition at line 386 of file StructuredData.h.
References lldb_private::StructuredData::Object::Object().
Referenced by Dictionary(), and GetValueForKeyAsDictionary().
Dictionary() [2/2]
lldb_private::StructuredData::Dictionary::Dictionary (ObjectSP obj_sp) inline
Definition at line 388 of file StructuredData.h.
References Dictionary(), lldb::eStructuredDataTypeDictionary, m_dict, and lldb_private::StructuredData::Object::Object().
~Dictionary()
lldb_private::StructuredData::Dictionary::~Dictionary () override default
Member Function Documentation
AddBooleanItem()
void lldb_private::StructuredData::Dictionary::AddBooleanItem (llvm::StringRef key, bool value) inline
Definition at line 533 of file StructuredData.h.
References AddItem().
Referenced by sddarwinlog_private::FilterRule::Serialize().
AddFloatItem()
void lldb_private::StructuredData::Dictionary::AddFloatItem (llvm::StringRef key, double value) inline
Definition at line 525 of file StructuredData.h.
References AddItem().
AddIntegerItem()
template<typename T> void lldb_private::StructuredData::Dictionary::AddIntegerItem (llvm::StringRef key, T value) inline
Definition at line 515 of file StructuredData.h.
References AddItem().
Referenced by SystemRuntimeMacOSX::AddThreadExtendedInfoPacketHints(), and lldb_private::RegisterContextUnifiedCore::RegisterContextUnifiedCore().
AddItem()
void lldb_private::StructuredData::Dictionary::AddItem (llvm::StringRef key, ObjectSP value_sp) inline
Definition at line 511 of file StructuredData.h.
References m_dict.
Referenced by AddBoolConfigEntry(), AddBooleanItem(), AddFloatItem(), AddIntegerItem(), AddLLVMTargets(), AddStringItem(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetSeparateDebugInfo(), and lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetSeparateDebugInfo().
AddStringItem()
void lldb_private::StructuredData::Dictionary::AddStringItem (llvm::StringRef key, llvm::StringRef value) inline
Definition at line 529 of file StructuredData.h.
References AddItem().
Referenced by sddarwinlog_private::ExactMatchFilterRule::DoSerialization(), sddarwinlog_private::RegexFilterRule::DoSerialization(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetSeparateDebugInfo(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetSeparateDebugInfo(), and sddarwinlog_private::FilterRule::Serialize().
ForEach()
void lldb_private::StructuredData::Dictionary::ForEach (std::function< bool(llvm::StringRef key, Object *object)> const & callback) const inline
Definition at line 402 of file StructuredData.h.
References m_dict, and lldb_private::StructuredData::Object::Object().
Referenced by SymbolVendorMacOSX::CreateInstance(), dump(), lldb_private::PlatformDarwin::ExtractAppSpecificInfo(), lldb_private::Target::StopHookScripted::GetSubclassDescription(), CommandObjectScriptingObjectParsed::CommandOptions::SetOptionsFromArray(), and lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo().
GetDescription()
void StructuredData::Dictionary::GetDescription (lldb_private::Stream & s) const override virtual
Reimplemented from lldb_private::StructuredData::Object.
Definition at line 239 of file StructuredData.cpp.
References lldb_private::Stream::EOL(), lldb_private::Stream::Format(), lldb_private::Stream::GetIndentLevel(), lldb_private::Stream::Indent(), lldb_private::Stream::IndentLess(), lldb_private::Stream::IndentMore(), lldb_private::StructuredData::IsRecordType(), m_dict, lldb_private::Stream::PutChar(), and lldb_private::Stream::SetIndentLevel().
GetKeys()
ArraySP lldb_private::StructuredData::Dictionary::GetKeys () const inline
Definition at line 410 of file StructuredData.h.
References m_dict.
Referenced by lldb::SBStructuredData::GetKeys().
GetSize()
size_t lldb_private::StructuredData::Dictionary::GetSize () const inline
Definition at line 400 of file StructuredData.h.
References m_dict.
Referenced by lldb_private::Target::StopHookScripted::GetSubclassDescription(), and CommandObjectScriptingObjectParsed::CommandOptions::SetOptionsFromArray().
GetValueForKey()
ObjectSP lldb_private::StructuredData::Dictionary::GetValueForKey (llvm::StringRef key) const inline
Definition at line 419 of file StructuredData.h.
References m_dict.
Referenced by CommandObjectScriptingObjectParsed::CommandObjectScriptingObjectParsed(), lldb_private::Target::CreateBreakpointsFromFile(), dump(), GenerateThreadName(), lldb_private::telemetry::GetAsNanosec(), lldb_private::Thread::GetDescription(), lldb_private::StructuredData::Object::GetObjectForDotSeparatedPath(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetSharedCacheInfo(), DynamicLoaderMacOS::GetSharedCacheInformation(), GetValueForKeyAsArray(), GetValueForKeyAsBoolean(), GetValueForKeyAsDictionary(), GetValueForKeyAsInteger(), GetValueForKeyAsString(), CommandObjectBreakpointRead::CommandOptions::HandleOptionArgumentCompletion(), lldb_private::DynamicLoaderDarwin::JSONImageInformationIntoImageInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::QueryGDBServer(), and CommandObjectScriptingObjectParsed::CommandOptions::SetOptionsFromArray().
GetValueForKeyAsArray()
bool lldb_private::StructuredData::Dictionary::GetValueForKeyAsArray (llvm::StringRef key, Array *& result) const inline
Definition at line 499 of file StructuredData.h.
References lldb_private::StructuredData::Object::GetAsArray(), and GetValueForKey().
Referenced by lldb_private::DynamicRegisterInfo::ByteOffsetFromRegInfoDict(), lldb_private::ScriptedThread::CalculateStopInfo(), lldb_private::Breakpoint::CreateFromStructuredData(), lldb_private::BreakpointOptions::CommandData::CreateFromStructuredData(), lldb_private::BreakpointResolverFileRegex::CreateFromStructuredData(), lldb_private::BreakpointResolverName::CreateFromStructuredData(), lldb_private::SearchFilterByModule::CreateFromStructuredData(), lldb_private::SearchFilterByModuleList::CreateFromStructuredData(), lldb_private::SearchFilterByModuleListAndCU::CreateFromStructuredData(), CommandObjectTargetModulesDumpSeparateDebugInfoFiles::DoExecute(), ObjectFileMachO::GetCorefileThreadExtraInfos(), lldb_private::StructuredDataDarwinLog::GetDescription(), CommandObjectBreakpointRead::CommandOptions::HandleOptionArgumentCompletion(), lldb_private::RegisterContextUnifiedCore::RegisterContextUnifiedCore(), lldb_private::Breakpoint::SerializedBreakpointMatchesNames(), and lldb_private::DynamicRegisterInfo::SetRegisterInfo().
GetValueForKeyAsBoolean()
bool lldb_private::StructuredData::Dictionary::GetValueForKeyAsBoolean (llvm::StringRef key, bool & result) const inline
Definition at line 423 of file StructuredData.h.
References lldb_private::StructuredData::Object::GetAsBoolean(), lldb_private::StructuredData::Boolean::GetValue(), and GetValueForKey().
Referenced by lldb_private::Breakpoint::CreateFromStructuredData(), lldb_private::BreakpointOptions::CommandData::CreateFromStructuredData(), lldb_private::BreakpointOptions::CreateFromStructuredData(), lldb_private::BreakpointResolverFileLine::CreateFromStructuredData(), lldb_private::BreakpointResolverFileRegex::CreateFromStructuredData(), lldb_private::BreakpointResolverName::CreateFromStructuredData(), and lldb_private::EvaluateExpressionOptions::GetBooleanLanguageOption().
GetValueForKeyAsDictionary()
bool lldb_private::StructuredData::Dictionary::GetValueForKeyAsDictionary (llvm::StringRef key, Dictionary *& result) const inline
Definition at line 488 of file StructuredData.h.
References Dictionary(), lldb_private::StructuredData::Object::GetAsDictionary(), and GetValueForKey().
Referenced by lldb_private::ScriptedThread::CalculateStopInfo(), lldb_private::Breakpoint::CreateFromStructuredData(), lldb_private::BreakpointOptions::CreateFromStructuredData(), lldb_private::BreakpointResolver::CreateFromStructuredData(), lldb_private::BreakpointResolverScripted::CreateFromStructuredData(), and lldb_private::SearchFilter::CreateFromStructuredData().
GetValueForKeyAsInteger() [1/2]
template<class IntType> bool lldb_private::StructuredData::Dictionary::GetValueForKeyAsInteger (llvm::StringRef key, IntType & result) const inline
Definition at line 437 of file StructuredData.h.
References GetValueForKey().
Referenced by lldb_private::DynamicRegisterInfo::ByteOffsetFromRegInfoDict(), lldb_private::ScriptedThread::CalculateStopInfo(), lldb_private::BreakpointOptions::CreateFromStructuredData(), lldb_private::BreakpointResolver::CreateFromStructuredData(), lldb_private::BreakpointResolverAddress::CreateFromStructuredData(), lldb_private::BreakpointResolverFileLine::CreateFromStructuredData(), lldb_private::BreakpointResolverName::CreateFromStructuredData(), lldb_private::ThreadSpec::CreateFromStructuredData(), DumpDwoFilesTable(), lldb_private::StructuredDataDarwinLog::DumpHeader(), DumpOsoFilesTable(), SystemRuntimeMacOSX::GetExtendedBacktraceThread(), lldb_private::ScriptedFrameProvider::GetFrameAtIndex(), lldb_private::ScriptedProcess::GetLoadedDynamicLibrariesInfos(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetThreadStopInfoFromJSON(), GetValueForKeyAsInteger(), lldb_private::ScriptedThread::LoadArtificialStackFrames(), ParseModuleSpec(), lldb_private::RegisterContextUnifiedCore::RegisterContextUnifiedCore(), lldb_private::DynamicRegisterInfo::SetRegisterInfo(), lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo(), and lldb_private::process_gdb_remote::ProcessGDBRemote::UpdateThreadIDList().
GetValueForKeyAsInteger() [2/2]
template<class IntType> bool lldb_private::StructuredData::Dictionary::GetValueForKeyAsInteger (llvm::StringRef key, IntType & result, IntType default_val) const inline
Definition at line 456 of file StructuredData.h.
References GetValueForKeyAsInteger().
GetValueForKeyAsString() [1/2]
bool lldb_private::StructuredData::Dictionary::GetValueForKeyAsString (llvm::StringRef key, llvm::StringRef & result) const inline
Definition at line 464 of file StructuredData.h.
References GetValueForKey().
Referenced by lldb_private::DynamicRegisterInfo::ByteOffsetFromRegInfoDict(), lldb_private::ScriptedThread::CalculateStopInfo(), lldb_private::BreakpointOptions::CommandData::CreateFromStructuredData(), lldb_private::BreakpointOptions::CreateFromStructuredData(), lldb_private::BreakpointResolver::CreateFromStructuredData(), lldb_private::BreakpointResolverAddress::CreateFromStructuredData(), lldb_private::BreakpointResolverFileLine::CreateFromStructuredData(), lldb_private::BreakpointResolverFileRegex::CreateFromStructuredData(), lldb_private::BreakpointResolverName::CreateFromStructuredData(), lldb_private::BreakpointResolverScripted::CreateFromStructuredData(), lldb_private::SearchFilter::CreateFromStructuredData(), lldb_private::ThreadSpec::CreateFromStructuredData(), CommandObjectTargetModulesDumpSeparateDebugInfoFiles::DoExecute(), DumpDwoFilesTable(), lldb_private::StructuredDataDarwinLog::DumpHeader(), DumpOsoFilesTable(), lldb_private::StructuredDataDarwinLog::GetDescription(), lldb_private::ScriptedProcess::GetLoadedDynamicLibrariesInfos(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetSharedCacheInfo(), GetValueForKeyAsString(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_jModulesInfo(), lldb_private::StructuredDataDarwinLog::HandleDisplayOfEvent(), ParseModuleSpec(), lldb_private::Process::RouteAsyncStructuredData(), lldb_private::DynamicRegisterInfo::SetRegisterInfo(), and lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo().
GetValueForKeyAsString() [2/2]
bool lldb_private::StructuredData::Dictionary::GetValueForKeyAsString (llvm::StringRef key, llvm::StringRef & result, const char * default_val) const inline
Definition at line 476 of file StructuredData.h.
References GetValueForKeyAsString().
HasKey()
bool lldb_private::StructuredData::Dictionary::HasKey (llvm::StringRef key) const inline
Definition at line 509 of file StructuredData.h.
References m_dict.
Referenced by lldb_private::BreakpointOptions::CreateFromStructuredData(), lldb_private::BreakpointResolverAddress::CreateFromStructuredData(), lldb_private::EvaluateExpressionOptions::GetBooleanLanguageOption(), lldb_private::ScriptedProcess::GetLoadedDynamicLibrariesInfos(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetSharedCacheInfo(), DynamicLoaderMacOS::GetSharedCacheInformation(), lldb_private::DynamicLoaderDarwin::JSONImageInformationIntoImageInfo(), and lldb_private::RegisterContextUnifiedCore::RegisterContextUnifiedCore().
Serialize()
void StructuredData::Dictionary::Serialize (llvm::json::OStream & s) const override virtual
Implements lldb_private::StructuredData::Object.
Definition at line 163 of file StructuredData.cpp.
References m_dict.
Member Data Documentation
m_dict
llvm::StringMap<ObjectSP> lldb_private::StructuredData::Dictionary::m_dict protected
Definition at line 542 of file StructuredData.h.
Referenced by AddItem(), Dictionary(), ForEach(), GetDescription(), GetKeys(), GetSize(), GetValueForKey(), HasKey(), and Serialize().
The documentation for this class was generated from the following files:
StructuredData.h
StructuredData.cpp