LLDB: lldb_private::Platform Class Reference
lldb_private::Platform Class Reference abstract
A plug-in interface definition class for debug platform that includes many platform abilities such as:
#include "lldb/Target/Platform.h"
Public Types
typedef std::function< Status(const ModuleSpec &module_spec, FileSpec &module_file_spec, FileSpec &symbol_file_spec)> LocateModuleCallback
Public Member Functions
Platform (bool is_host_platform)
Default Constructor.
~Platform () override
The destructor is virtual since this class is designed to be inherited from by the plug-in instance.
virtual Status ResolveExecutable (const ModuleSpec &module_spec, lldb::ModuleSP &exe_module_sp)
Set the target's executable based off of the existing architecture information in target given a path to an executable exe_file.
virtual Status ResolveSymbolFile (Target &target, const ModuleSpec &sym_spec, FileSpec &sym_file)
Find a symbol file given a symbol file module specification.
virtual bool ResolveRemotePath (const FileSpec &platform_path, FileSpec &resolved_platform_path)
Resolves the FileSpec to a (possibly) remote path.
virtual llvm::VersionTuple GetOSVersion (Process *process=nullptr)
Get the OS version from a connected platform.
bool SetOSVersion (llvm::VersionTuple os_version)
std::optional< std::string > GetOSBuildString ()
std::optional< std::string > GetOSKernelDescription ()
llvm::StringRef GetName ()
virtual const char * GetHostname ()
virtual ConstString GetFullNameForDylib (ConstString basename)
virtual llvm::StringRef GetDescription ()=0
virtual void GetStatus (Stream &strm)
Report the current status for this platform.
virtual bool GetRemoteOSVersion ()
virtual std::optional< std::string > GetRemoteOSBuildString ()
virtual std::optional< std::string > GetRemoteOSKernelDescription ()
virtual ArchSpec GetRemoteSystemArchitecture ()
virtual FileSpec GetRemoteWorkingDirectory ()
virtual bool SetRemoteWorkingDirectory (const FileSpec &working_dir)
virtual UserIDResolver & GetUserIDResolver ()
virtual Status GetFileWithUUID (const FileSpec &platform_file, const UUID *uuid_ptr, FileSpec &local_file)
Locate a file for a platform.
virtual FileSpecList LocateExecutableScriptingResources (Target *target, Module &module, Stream &feedback_stream)
virtual Status GetSharedModule (const ModuleSpec &module_spec, Process *process, lldb::ModuleSP &module_sp, llvm::SmallVectorImpl< lldb::ModuleSP > *old_modules, bool *did_create_ptr)
void CallLocateModuleCallbackIfSet (const ModuleSpec &module_spec, lldb::ModuleSP &module_sp, FileSpec &symbol_file_spec, bool *did_create_ptr)
virtual bool GetModuleSpec (const FileSpec &module_file_spec, const ArchSpec &arch, ModuleSpec &module_spec)
virtual Status ConnectRemote (Args &args)
virtual Status DisconnectRemote ()
virtual std::vector< ArchSpec > GetSupportedArchitectures (const ArchSpec &process_host_arch)=0
Get the platform's supported architectures in the order in which they should be searched.
virtual size_t GetSoftwareBreakpointTrapOpcode (Target &target, BreakpointSite *bp_site)
virtual Status LaunchProcess (ProcessLaunchInfo &launch_info)
Launch a new process on a platform, not necessarily for debugging, it could be just for running the process.
virtual Status ShellExpandArguments (ProcessLaunchInfo &launch_info)
Perform expansion of the command-line for this launch info This can potentially involve wildcard expansion environment variable replacement, and whatever other argument magic the platform defines as part of its typical user experience.
virtual Status KillProcess (const lldb::pid_t pid)
Kill process on a platform.
virtual bool IsCompatibleArchitecture (const ArchSpec &arch, const ArchSpec &process_host_arch, ArchSpec::MatchType match, ArchSpec *compatible_arch_ptr)
Lets a platform answer if it is compatible with a given architecture and the target triple contained within.
virtual bool CanDebugProcess ()
Not all platforms will support debugging a process by spawning somehow halted for a debugger (specified using the "eLaunchFlagDebug" launch flag) and then attaching.
virtual lldb::ProcessSP DebugProcess (ProcessLaunchInfo &launch_info, Debugger &debugger, Target &target, Status &error)
Subclasses do not need to implement this function as it uses the Platform::LaunchProcess() followed by Platform::Attach ().
virtual lldb::ProcessSP ConnectProcess (llvm::StringRef connect_url, llvm::StringRef plugin_name, Debugger &debugger, Target *target, Status &error)
virtual lldb::ProcessSP ConnectProcessSynchronous (llvm::StringRef connect_url, llvm::StringRef plugin_name, Debugger &debugger, Stream &stream, Target *target, Status &error)
virtual lldb::ProcessSP Attach (ProcessAttachInfo &attach_info, Debugger &debugger, Target *target, Status &error)=0
Attach to an existing process using a process ID.
virtual uint32_t FindProcesses (const ProcessInstanceInfoMatch &match_info, ProcessInstanceInfoList &proc_infos)
Attach to an existing process by process name.
ProcessInstanceInfoList GetAllProcesses ()
virtual bool GetProcessInfo (lldb::pid_t pid, ProcessInstanceInfo &proc_info)
virtual lldb::BreakpointSP SetThreadCreationBreakpoint (Target &target)
virtual lldb_private::ConstString GetSDKDirectory (lldb_private::Target &target)
virtual llvm::Expected< std::pair< XcodeSDK, bool > > GetSDKPathFromDebugInfo (Module &module)
Search each CU associated with the specified 'module' for the SDK paths the CUs were compiled against.
virtual llvm::Expected< std::string > ResolveSDKPathFromDebugInfo (Module &module)
Returns the full path of the most appropriate SDK for the specified 'module'.
virtual llvm::Expected< XcodeSDK > GetSDKPathFromDebugInfo (CompileUnit &unit)
Search CU for the SDK path the CUs was compiled against.
virtual llvm::Expected< std::string > ResolveSDKPathFromDebugInfo (CompileUnit &unit)
Returns the full path of the most appropriate SDK for the specified compile unit.
bool IsHost () const
bool IsRemote () const
virtual bool IsConnected () const
const ArchSpec & GetSystemArchitecture ()
void SetSystemArchitecture (const ArchSpec &arch)
ArchSpec GetAugmentedArchSpec (llvm::StringRef triple)
If the triple contains not specify the vendor, os, and environment parts, we "augment" these using information from the platform and return the resulting ArchSpec object.
size_t GetMaxUserIDNameLength () const
size_t GetMaxGroupIDNameLength () const
const std::string & GetSDKRootDirectory () const
void SetSDKRootDirectory (std::string dir)
const std::string & GetSDKBuild () const
void SetSDKBuild (std::string sdk_build)
virtual bool SupportsModules ()
virtual void AddClangModuleCompilationOptions (Target *target, std::vector< std::string > &options)
FileSpec GetWorkingDirectory ()
bool SetWorkingDirectory (const FileSpec &working_dir)
virtual bool ModuleIsExcludedForUnconstrainedSearches (Target &target, const lldb::ModuleSP &module_sp)
virtual Status MakeDirectory (const FileSpec &file_spec, uint32_t permissions)
virtual Status GetFilePermissions (const FileSpec &file_spec, uint32_t &file_permissions)
virtual Status SetFilePermissions (const FileSpec &file_spec, uint32_t file_permissions)
virtual lldb::user_id_t OpenFile (const FileSpec &file_spec, File::OpenOptions flags, uint32_t mode, Status &error)
virtual bool CloseFile (lldb::user_id_t fd, Status &error)
virtual lldb::user_id_t GetFileSize (const FileSpec &file_spec)
virtual void AutoCompleteDiskFileOrDirectory (CompletionRequest &request, bool only_dir)
virtual uint64_t ReadFile (lldb::user_id_t fd, uint64_t offset, void *dst, uint64_t dst_len, Status &error)
virtual uint64_t WriteFile (lldb::user_id_t fd, uint64_t offset, const void *src, uint64_t src_len, Status &error)
virtual Status GetFile (const FileSpec &source, const FileSpec &destination)
virtual Status PutFile (const FileSpec &source, const FileSpec &destination, uint32_t uid=UINT32_MAX, uint32_t gid=UINT32_MAX)
virtual Status CreateSymlink (const FileSpec &src, const FileSpec &dst)
virtual Status Install (const FileSpec &src, const FileSpec &dst)
Install a file or directory to the remote system.
virtual Environment GetEnvironment ()
virtual bool GetFileExists (const lldb_private::FileSpec &file_spec)
virtual Status Unlink (const FileSpec &file_spec)
virtual MmapArgList GetMmapArgumentList (const ArchSpec &arch, lldb::addr_t addr, lldb::addr_t length, unsigned prot, unsigned flags, lldb::addr_t fd, lldb::addr_t offset)
virtual bool GetSupportsRSync ()
virtual void SetSupportsRSync (bool flag)
virtual const char * GetRSyncOpts ()
virtual void SetRSyncOpts (const char *opts)
virtual const char * GetRSyncPrefix ()
virtual void SetRSyncPrefix (const char *prefix)
virtual bool GetSupportsSSH ()
virtual void SetSupportsSSH (bool flag)
virtual const char * GetSSHOpts ()
virtual void SetSSHOpts (const char *opts)
virtual bool GetIgnoresRemoteHostname ()
virtual void SetIgnoresRemoteHostname (bool flag)
virtual lldb_private::OptionGroupOptions * GetConnectionOptions (CommandInterpreter &interpreter)
virtual lldb_private::Status RunShellCommand (llvm::StringRef command, const FileSpec &working_dir, int *status_ptr, int *signo_ptr, std::string *command_output, const Timeout< std::micro > &timeout)
virtual lldb_private::Status RunShellCommand (llvm::StringRef shell, llvm::StringRef command, const FileSpec &working_dir, int *status_ptr, int *signo_ptr, std::string *command_output, const Timeout< std::micro > &timeout)
virtual void SetLocalCacheDirectory (const char *local)
virtual const char * GetLocalCacheDirectory ()
virtual std::string GetPlatformSpecificConnectionInformation ()
virtual llvm::ErrorOr< llvm::MD5::MD5Result > CalculateMD5 (const FileSpec &file_spec)
virtual uint32_t GetResumeCountForLaunchInfo (ProcessLaunchInfo &launch_info)
virtual const lldb::UnixSignalsSP & GetRemoteUnixSignals ()
lldb::UnixSignalsSP GetUnixSignals ()
virtual std::string GetQueueNameForThreadQAddress (Process *process, lldb::addr_t dispatch_qaddr)
Locate a queue name given a thread's qaddr.
virtual lldb::queue_id_t GetQueueIDForThreadQAddress (Process *process, lldb::addr_t dispatch_qaddr)
Locate a queue ID given a thread's qaddr.
virtual const std::vector< ConstString > & GetTrapHandlerSymbolNames ()
Provide a list of trap handler function names for this platform.
virtual lldb::UnwindPlanSP GetTrapHandlerUnwindPlan (const ArchSpec &arch, ConstString name)
Try to get a specific unwind plan for a named trap handler.
virtual FileSpec LocateExecutable (const char *basename)
Find a support executable that may not live within in the standard locations related to LLDB.
virtual uint32_t GetDefaultMemoryCacheLineSize ()
Allow the platform to set preferred memory cache line size.
uint32_t LoadImage (lldb_private::Process *process, const lldb_private::FileSpec &local_file, const lldb_private::FileSpec &remote_file, lldb_private::Status &error)
Load a shared library into this process.
uint32_t LoadImageUsingPaths (lldb_private::Process *process, const lldb_private::FileSpec &library_name, const std::vector< std::string > &paths, lldb_private::Status &error, lldb_private::FileSpec *loaded_path)
Load a shared library specified by base name into this process, looking by hand along a set of paths.
virtual uint32_t DoLoadImage (lldb_private::Process *process, const lldb_private::FileSpec &remote_file, const std::vector< std::string > *paths, lldb_private::Status &error, lldb_private::FileSpec *loaded_path=nullptr)
virtual Status UnloadImage (lldb_private::Process *process, uint32_t image_token)
virtual size_t ConnectToWaitingProcesses (lldb_private::Debugger &debugger, lldb_private::Status &error)
Connect to all processes waiting for a debugger to attach.
virtual llvm::Expected< StructuredData::DictionarySP > FetchExtendedCrashInformation (lldb_private::Process &process)
Gather all of crash informations into a structured data dictionary.
virtual bool LoadPlatformBinaryAndSetup (Process *process, lldb::addr_t addr, bool notify)
Detect a binary in memory that will determine which Platform and DynamicLoader should be used in this target/process, and update the Platform/DynamicLoader.
virtual CompilerType GetSiginfoType (const llvm::Triple &triple)
virtual lldb::StopInfoSP GetStopInfoFromSiginfo (Thread &thread)
virtual Args GetExtraStartupCommands ()
void SetLocateModuleCallback (LocateModuleCallback callback)
Set locate module callback.
LocateModuleCallback GetLocateModuleCallback () const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
virtual llvm::StringRef GetPluginName ()=0
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static PlatformProperties & GetGlobalPlatformProperties ()
static lldb::PlatformSP GetHostPlatform ()
Get the native host platform plug-in.
static const char * GetHostPlatformName ()
static void SetHostPlatform (const lldb::PlatformSP &platform_sp)
static lldb::PlatformSP Create (llvm::StringRef name)
static ArchSpec GetAugmentedArchSpec (Platform *platform, llvm::StringRef triple)
Augments the triple either with information from platform or the host system (if platform is null).
Protected Types
typedef std::map< uint32_t, ConstString > IDToNameMap
Protected Member Functions
lldb::ProcessSP DoConnectProcess (llvm::StringRef connect_url, llvm::StringRef plugin_name, Debugger &debugger, Stream *stream, Target *target, Status &error)
Private implementation of connecting to a process.
virtual void CalculateTrapHandlerSymbolNames ()=0
Ask the Platform subclass to fill in the list of trap handler names.
Status GetCachedExecutable (ModuleSpec &module_spec, lldb::ModuleSP &module_sp)
virtual Status DownloadModuleSlice (const FileSpec &src_file_spec, const uint64_t src_offset, const uint64_t src_size, const FileSpec &dst_file_spec)
virtual Status DownloadSymbolFile (const lldb::ModuleSP &module_sp, const FileSpec &dst_file_spec)
virtual const char * GetCacheHostname ()
Static Protected Member Functions
static std::vector< ArchSpec > CreateArchList (llvm::ArrayRef< llvm::Triple::ArchType > archs, llvm::Triple::OSType os)
Create a list of ArchSpecs with the given OS and a architectures.
Protected Attributes
bool m_is_host
bool m_os_version_set_while_connected
bool m_system_arch_set_while_connected
std::string m_sdk_sysroot
std::string m_sdk_build
FileSpec m_working_dir
std::string m_hostname
llvm::VersionTuple m_os_version
ArchSpec m_system_arch
std::mutex m_mutex
size_t m_max_uid_name_len
size_t m_max_gid_name_len
bool m_supports_rsync
std::string m_rsync_opts
std::string m_rsync_prefix
bool m_supports_ssh
std::string m_ssh_opts
bool m_ignores_remote_hostname
std::string m_local_cache_directory
std::vector< ConstString > m_trap_handlers
bool m_calculated_trap_handlers
const std::unique_ptr< ModuleCache > m_module_cache
LocateModuleCallback m_locate_module_callback
Private Types
typedef std::function< Status(const ModuleSpec &)> ModuleResolver
Private Member Functions
Status GetRemoteSharedModule (const ModuleSpec &module_spec, Process *process, lldb::ModuleSP &module_sp, const ModuleResolver &module_resolver, bool *did_create_ptr)
bool GetCachedSharedModule (const ModuleSpec &module_spec, lldb::ModuleSP &module_sp, bool *did_create_ptr)
FileSpec GetModuleCacheRoot ()
Detailed Description
A plug-in interface definition class for debug platform that includes many platform abilities such as:
getting platform information such as supported architectures, supported binary file formats and more
launching new processes
attaching to existing processes
download/upload files
execute shell commands
listing and getting info for existing processes
attaching and possibly debugging the platform's kernel
Definition at line 77 of file Platform.h.
Member Typedef Documentation
IDToNameMap
typedef std::map<uint32_t, ConstString> lldb_private::Platform::IDToNameMap protected
Definition at line 1011 of file Platform.h.
LocateModuleCallback
typedef std::function<Status(const ModuleSpec &module_spec, FileSpec &module_file_spec, FileSpec &symbol_file_spec)> lldb_private::Platform::LocateModuleCallback
Definition at line 971 of file Platform.h.
ModuleResolver
typedef std::function<Status(const ModuleSpec &)> lldb_private::Platform::ModuleResolver private
Definition at line 1056 of file Platform.h.
Constructor & Destructor Documentation
Platform()
Platform::Platform (bool is_host_platform)
Default Constructor.
Definition at line 233 of file Platform.cpp.
References lldb_private::GetLog(), LLDB_LOGF, m_calculated_trap_handlers, m_ignores_remote_hostname, m_is_host, m_max_gid_name_len, m_max_uid_name_len, m_module_cache, m_os_version_set_while_connected, m_rsync_opts, m_rsync_prefix, m_ssh_opts, m_supports_rsync, m_supports_ssh, m_system_arch_set_while_connected, m_trap_handlers, and lldb_private::Object.
Referenced by GetAugmentedArchSpec(), lldb_private::PlatformQemuUser::PlatformQemuUser(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::PlatformRemoteGDBServer(), and ~Platform().
~Platform()
Platform::~Platform () override default
The destructor is virtual since this class is designed to be inherited from by the plug-in instance.
References Platform().
Member Function Documentation
AddClangModuleCompilationOptions()
void Platform::AddClangModuleCompilationOptions (Target * target, std::vector< std::string > & options) virtual
Reimplemented in lldb_private::PlatformAppleSimulator, lldb_private::PlatformMacOSX, and lldb_private::PlatformRemoteDarwinDevice.
Definition at line 350 of file Platform.cpp.
Attach()
virtual lldb::ProcessSP lldb_private::Platform::Attach (ProcessAttachInfo & attach_info, Debugger & debugger, Target * target, Status & error) pure virtual
Attach to an existing process using a process ID.
Each platform subclass needs to implement this function and attempt to attach to the process with the process ID of pid. The platform subclass should return an appropriate ProcessSP subclass that is attached to the process, or an empty shared pointer with an appropriate error.
Returns
An appropriate ProcessSP containing a valid shared pointer to the default Process subclass for the platform that is attached to the process, or an empty shared pointer with an appropriate error fill into the error object.
Implemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, lldb_private::PlatformQemuUser, lldb_private::PlatformWasm, lldb_private::PlatformWindows, and PlatformPOSIX.
References error().
Referenced by DebugProcess().
AutoCompleteDiskFileOrDirectory()
virtual void lldb_private::Platform::AutoCompleteDiskFileOrDirectory (CompletionRequest & request, bool only_dir) inline virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer.
Definition at line 584 of file Platform.h.
CalculateMD5()
llvm::ErrorOr< llvm::MD5::MD5Result > Platform::CalculateMD5 (const FileSpec & file_spec) virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 1276 of file Platform.cpp.
References lldb_private::FileSpec::GetPath(), and IsHost().
Referenced by lldb_private::RemoteAwarePlatform::CalculateMD5(), and PutFile().
CalculateTrapHandlerSymbolNames()
virtual void lldb_private::Platform::CalculateTrapHandlerSymbolNames () protected pure virtual
Ask the Platform subclass to fill in the list of trap handler names.
For most Unix user process environments, this will be a single function name, _sigtramp. More specialized environments may have additional handler names. The unwinder code needs to know when a trap handler is on the stack because the unwind rules for the frame that caused the trap are different.
The base class Platform ivar m_trap_handlers should be updated by the Platform subclass when this method is called. If there are no predefined trap handlers, this method may be a no-op.
Implemented in lldb_private::platform_aix::PlatformAIX, lldb_private::platform_freebsd::PlatformFreeBSD, lldb_private::platform_gdb_server::PlatformRemoteGDBServer, lldb_private::platform_linux::PlatformLinux, lldb_private::platform_netbsd::PlatformNetBSD, lldb_private::platform_openbsd::PlatformOpenBSD, lldb_private::PlatformDarwin, lldb_private::PlatformQemuUser, lldb_private::PlatformWasm, lldb_private::PlatformWindows, and PlatformPOSIX.
Referenced by GetTrapHandlerSymbolNames().
CallLocateModuleCallbackIfSet()
void Platform::CallLocateModuleCallbackIfSet (const ModuleSpec & module_spec, lldb::ModuleSP & module_sp, FileSpec & symbol_file_spec, bool * did_create_ptr)
Definition at line 1587 of file Platform.cpp.
References lldb_private::FileSpec::Clear(), error(), lldb_private::ModuleSpec::GetFileSpec(), lldb_private::GetLog(), lldb_private::FileSpec::GetPath(), lldb_private::ModuleList::GetSharedModule(), lldb_private::FileSystem::Instance(), LLDB_LOGF, m_locate_module_callback, and lldb_private::Platform.
Referenced by GetRemoteSharedModule().
CanDebugProcess()
virtual bool lldb_private::Platform::CanDebugProcess () inline virtual
Not all platforms will support debugging a process by spawning somehow halted for a debugger (specified using the "eLaunchFlagDebug" launch flag) and then attaching.
If your platform doesn't support this, override this function and return false.
Reimplemented in lldb_private::platform_freebsd::PlatformFreeBSD, lldb_private::platform_linux::PlatformLinux, lldb_private::platform_netbsd::PlatformNetBSD, lldb_private::platform_openbsd::PlatformOpenBSD, and lldb_private::PlatformWindows.
Definition at line 361 of file Platform.h.
CloseFile()
bool Platform::CloseFile (lldb::user_id_t fd, Status & error) virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 648 of file Platform.cpp.
References lldb_private::FileCache::CloseFile(), error(), lldb_private::FileCache::GetInstance(), and IsHost().
Referenced by lldb_private::RemoteAwarePlatform::CloseFile(), DownloadModuleSlice(), and PutFile().
ConnectProcess()
lldb::ProcessSP Platform::ConnectProcess (llvm::StringRef connect_url, llvm::StringRef plugin_name, Debugger & debugger, Target * target, Status & error) virtual
Reimplemented in lldb_private::platform_android::PlatformAndroidRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 1871 of file Platform.cpp.
References DoConnectProcess(), and error().
Referenced by lldb_private::RemoteAwarePlatform::ConnectProcess(), and lldb_private::platform_gdb_server::PlatformRemoteGDBServer::ConnectToWaitingProcesses().
ConnectProcessSynchronous()
lldb::ProcessSP Platform::ConnectProcessSynchronous (llvm::StringRef connect_url, llvm::StringRef plugin_name, Debugger & debugger, Stream & stream, Target * target, Status & error) virtual
Definition at line 1879 of file Platform.cpp.
References DoConnectProcess(), and error().
ConnectRemote()
Status Platform::ConnectRemote (Args & args) virtual
Reimplemented in lldb_private::platform_android::PlatformAndroid, lldb_private::platform_android::PlatformAndroidRemoteGDBServer, lldb_private::platform_gdb_server::PlatformRemoteGDBServer, lldb_private::PlatformAppleSimulator, lldb_private::PlatformWasm, lldb_private::PlatformWindows, and PlatformPOSIX.
Definition at line 875 of file Platform.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::PluginInterface::GetPluginName(), and IsHost().
ConnectToWaitingProcesses()
size_t Platform::ConnectToWaitingProcesses (lldb_private::Debugger & debugger, lldb_private::Status & error) virtual
Connect to all processes waiting for a debugger to attach.
If the platform have a list of processes waiting for a debugger to connect to them then connect to all of these pending processes.
Parameters
[in] debugger The debugger used for the connect.
[out] error If an error occurred during the connect then this object will contain the error message.
Returns
The number of processes we are successfully connected to.
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 1943 of file Platform.cpp.
References error().
Referenced by lldb_private::RemoteAwarePlatform::ConnectToWaitingProcesses().
Create()
PlatformSP Platform::Create (llvm::StringRef name) static
Definition at line 215 of file Platform.cpp.
References GetHostPlatform(), GetHostPlatformName(), and lldb_private::PluginManager::GetPlatformCreateCallbackForPluginName().
Referenced by lldb_private::PlatformList::Create(), and lldb::SBPlatform::SBPlatform().
CreateArchList()
std::vector< ArchSpec > Platform::CreateArchList (llvm::ArrayRef< llvm::Triple::ArchType > archs, llvm::Triple::OSType os) static protected
Create a list of ArchSpecs with the given OS and a architectures.
The vendor field is left as an "unspecified unknown".
Definition at line 1082 of file Platform.cpp.
Referenced by lldb_private::platform_aix::PlatformAIX::PlatformAIX(), lldb_private::platform_freebsd::PlatformFreeBSD::PlatformFreeBSD(), lldb_private::platform_linux::PlatformLinux::PlatformLinux(), lldb_private::platform_netbsd::PlatformNetBSD::PlatformNetBSD(), and lldb_private::platform_openbsd::PlatformOpenBSD::PlatformOpenBSD().
CreateSymlink()
Status Platform::CreateSymlink (const FileSpec & src, const FileSpec & dst) virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 1208 of file Platform.cpp.
References lldb_private::Status::FromErrorString(), lldb_private::FileSystem::Instance(), IsHost(), and lldb_private::FileSystem::Symlink().
Referenced by lldb_private::RemoteAwarePlatform::CreateSymlink(), Install(), and RecurseCopy_Callback().
DebugProcess()
lldb::ProcessSP Platform::DebugProcess (ProcessLaunchInfo & launch_info, Debugger & debugger, Target & target, Status & error) virtual
Subclasses do not need to implement this function as it uses the Platform::LaunchProcess() followed by Platform::Attach ().
Remote platforms will want to subclass this function in order to be able to intercept STDIO and possibly launch a separate process that will debug the debuggee.
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, lldb_private::PlatformAppleSimulator, lldb_private::PlatformDarwin, lldb_private::PlatformQemuUser, lldb_private::PlatformWasm, lldb_private::PlatformWindows, and PlatformPOSIX.
Definition at line 997 of file Platform.cpp.
References Attach(), error(), lldb_private::ProcessLaunchInfo::GetFlags(), lldb_private::ProcessInfo::GetHijackListener(), lldb_private::GetLog(), lldb_private::ProcessInfo::GetProcessID(), lldb_private::ProcessLaunchInfo::GetPTY(), lldb_private::PluginManager::GetStructuredDataFilterCallbackAtIndex(), lldb_private::PseudoTerminal::invalid_fd, LaunchProcess(), LLDB_INVALID_PROCESS_ID, LLDB_LOG, LLDB_LOGF, lldb_private::Platform, lldb_private::PseudoTerminal::ReleasePrimaryFileDescriptor(), lldb_private::Flags::Set(), lldb_private::ProcessInfo::SetHijackListener(), and lldb_private::ProcessLaunchInfo::SetLaunchInSeparateProcessGroup().
Referenced by lldb_private::PlatformDarwin::DebugProcess().
DisconnectRemote()
Status Platform::DisconnectRemote () virtual
Reimplemented in lldb_private::platform_android::PlatformAndroid, lldb_private::platform_android::PlatformAndroidRemoteGDBServer, lldb_private::platform_gdb_server::PlatformRemoteGDBServer, lldb_private::PlatformAppleSimulator, lldb_private::PlatformWindows, and PlatformPOSIX.
Definition at line 888 of file Platform.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::PluginInterface::GetPluginName(), and IsHost().
DoConnectProcess()
lldb::ProcessSP Platform::DoConnectProcess (llvm::StringRef connect_url, llvm::StringRef plugin_name, Debugger & debugger, Stream * stream, Target * target, Status & error) protected
Private implementation of connecting to a process.
If the stream is set we connect synchronously.
Definition at line 1886 of file Platform.cpp.
References lldb_private::Target::CreateProcess(), lldb_private::TargetList::CreateTarget(), lldb_private::eLoadDependentsNo, error(), lldb_private::Target::GetDefaultArchitecture(), lldb_private::Debugger::GetListener(), lldb_private::Debugger::GetTargetList(), lldb_private::ArchSpec::GetTriple(), lldb_private::Process::HandleProcessStateChangedEvent(), lldb_private::ArchSpec::IsValid(), lldb_private::Listener::MakeListener(), and SelectMostRelevantFrame.
Referenced by ConnectProcess(), and ConnectProcessSynchronous().
DoLoadImage()
uint32_t Platform::DoLoadImage (lldb_private::Process * process, const lldb_private::FileSpec & remote_file, const std::vector< std::string > * paths, lldb_private::Status & error, lldb_private::FileSpec * loaded_path = nullptr) virtual
Reimplemented in lldb_private::PlatformWindows, and PlatformPOSIX.
Definition at line 1838 of file Platform.cpp.
References error(), lldb_private::Status::FromErrorString(), and LLDB_INVALID_IMAGE_TOKEN.
Referenced by LoadImage(), and LoadImageUsingPaths().
DownloadModuleSlice()
Status Platform::DownloadModuleSlice (const FileSpec & src_file_spec, const uint64_t src_offset, const uint64_t src_size, const FileSpec & dst_file_spec) protected virtual
Reimplemented in lldb_private::platform_android::PlatformAndroid.
Definition at line 1727 of file Platform.cpp.
References CloseFile(), lldb_private::File::eOpenOptionReadOnly, error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::FileSpec::GetPath(), OpenFile(), and ReadFile().
Referenced by GetCachedSharedModule().
DownloadSymbolFile()
Status Platform::DownloadSymbolFile (const lldb::ModuleSP & module_sp, const FileSpec & dst_file_spec) protected virtual
Reimplemented in lldb_private::platform_android::PlatformAndroid.
Definition at line 1775 of file Platform.cpp.
References lldb_private::Status::FromErrorString().
Referenced by GetCachedSharedModule().
FetchExtendedCrashInformation()
virtual llvm::Expected< StructuredData::DictionarySP > lldb_private::Platform::FetchExtendedCrashInformation (lldb_private::Process & process) inline virtual
Gather all of crash informations into a structured data dictionary.
If the platform have a crashed process with crash information entries, gather all the entries into an structured data dictionary or return a nullptr. This dictionary is generic and extensible, as it contains an array for each different type of crash information.
Parameters
[in] process The crashed process.
Returns
A structured data dictionary containing at each entry, the crash information type as the entry key and the matching an array as the entry value. nullptr if not implemented or if the process has no crash information entry. error if an error occurred.
Reimplemented in lldb_private::PlatformDarwin.
Definition at line 930 of file Platform.h.
FindProcesses()
uint32_t Platform::FindProcesses (const ProcessInstanceInfoMatch & match_info, ProcessInstanceInfoList & proc_infos) virtual
Attach to an existing process by process name.
This function is not meant to be overridden by Process subclasses. It will first call Process::WillAttach (const char *) and if that returns true, Process::DoAttach (const char *) will be called to actually do the attach. If DoAttach returns true, then Process::DidAttach() will be called.
Parameters
[in] process_name A process name to match against the current process list.
Returns
Returns pid if attaching was successful, or LLDB_INVALID_PROCESS_ID if attaching fails.
Reimplemented in lldb_private::platform_android::PlatformAndroid, lldb_private::platform_gdb_server::PlatformRemoteGDBServer, lldb_private::PlatformAppleSimulator, lldb_private::PlatformQemuUser, and lldb_private::RemoteAwarePlatform.
Definition at line 911 of file Platform.cpp.
References lldb_private::Host::FindProcesses(), and IsHost().
Referenced by lldb_private::RemoteAwarePlatform::FindProcesses(), and GetAllProcesses().
GetAllProcesses()
ProcessInstanceInfoList Platform::GetAllProcesses ()
Definition at line 921 of file Platform.cpp.
References FindProcesses(), and lldb_private::ProcessInstanceInfoMatch::MatchAllProcesses().
GetAugmentedArchSpec() [1/2]
ArchSpec Platform::GetAugmentedArchSpec (llvm::StringRef triple)
If the triple contains not specify the vendor, os, and environment parts, we "augment" these using information from the platform and return the resulting ArchSpec object.
Definition at line 846 of file Platform.cpp.
References lldb_private::ArchSpec::CompatibleMatch, lldb_private::ArchSpec::ContainsOnlyArch(), lldb_private::ArchSpec::GetTriple(), IsCompatibleArchitecture(), and lldb_private::ArchSpec::IsValid().
GetAugmentedArchSpec() [2/2]
ArchSpec Platform::GetAugmentedArchSpec (Platform * platform, llvm::StringRef triple) static
Augments the triple either with information from platform or the host system (if platform is null).
Definition at line 226 of file Platform.cpp.
References GetAugmentedArchSpec(), and Platform().
Referenced by lldb::SBTarget::AddModule(), lldb::SBDebugger::CreateTargetWithFileAndArch(), lldb::SBDebugger::FindTargetWithFileAndArch(), lldb_private::OptionGroupArchitecture::GetArchitecture(), GetAugmentedArchSpec(), CommandObjectPlatformProcessList::CommandOptions::SetOptionValue(), lldb_private::CommandObjectDisassemble::CommandOptions::SetOptionValue(), and lldb_private::CommandOptionsProcessLaunch::SetOptionValue().
GetCachedExecutable()
Status Platform::GetCachedExecutable (ModuleSpec & module_spec, lldb::ModuleSP & module_sp) protected
Definition at line 1447 of file Platform.cpp.
References error(), lldb_private::ModuleSpec::GetFileSpec(), lldb_private::ModuleSpec::GetPlatformFileSpec(), GetRemoteSharedModule(), and ResolveExecutable().
Referenced by lldb_private::RemoteAwarePlatform::ResolveExecutable().
GetCachedSharedModule()
bool Platform::GetCachedSharedModule (const ModuleSpec & module_spec, lldb::ModuleSP & module_sp, bool * did_create_ptr) private
Definition at line 1694 of file Platform.cpp.
References DownloadModuleSlice(), DownloadSymbolFile(), error(), lldb_private::UUID::GetAsString(), GetCacheHostname(), lldb_private::ModuleSpec::GetFileSpec(), GetGlobalPlatformProperties(), lldb_private::GetLog(), GetModuleCacheRoot(), lldb_private::ModuleSpec::GetObjectOffset(), lldb_private::ModuleSpec::GetObjectSize(), lldb_private::ModuleSpec::GetUUID(), IsHost(), LLDB_LOGF, m_module_cache, and lldb_private::Platform.
Referenced by GetRemoteSharedModule().
GetCacheHostname()
const char * Platform::GetCacheHostname () protected virtual
Reimplemented in lldb_private::platform_android::PlatformAndroid.
Definition at line 1787 of file Platform.cpp.
References GetHostname().
Referenced by GetCachedSharedModule().
GetConnectionOptions()
virtual lldb_private::OptionGroupOptions * lldb_private::Platform::GetConnectionOptions (CommandInterpreter & interpreter) inline virtual
Reimplemented in PlatformPOSIX.
Definition at line 667 of file Platform.h.
GetDefaultMemoryCacheLineSize()
virtual uint32_t lldb_private::Platform::GetDefaultMemoryCacheLineSize () inline virtual
Allow the platform to set preferred memory cache line size.
If non-zero (and the user has not set cache line size explicitly), this value will be used as the cache line size for memory reads.
Reimplemented in lldb_private::platform_android::PlatformAndroid.
Definition at line 814 of file Platform.h.
GetDescription()
virtual llvm::StringRef lldb_private::Platform::GetDescription () pure virtual
Implemented in lldb_private::platform_aix::PlatformAIX, lldb_private::platform_freebsd::PlatformFreeBSD, lldb_private::platform_gdb_server::PlatformRemoteGDBServer, lldb_private::platform_linux::PlatformLinux, lldb_private::platform_netbsd::PlatformNetBSD, lldb_private::platform_openbsd::PlatformOpenBSD, lldb_private::PlatformAppleSimulator, lldb_private::PlatformMacOSX, lldb_private::PlatformQemuUser, lldb_private::PlatformRemoteAppleBridge, lldb_private::PlatformRemoteAppleTV, lldb_private::PlatformRemoteAppleWatch, lldb_private::PlatformRemoteAppleXR, lldb_private::PlatformRemoteiOS, lldb_private::PlatformRemoteMacOSX, lldb_private::PlatformWasm, and lldb_private::PlatformWindows.
GetEnvironment()
Environment Platform::GetEnvironment () virtual
Reimplemented in lldb_private::PlatformQemuUser, and lldb_private::RemoteAwarePlatform.
Definition at line 1430 of file Platform.cpp.
References lldb_private::Host::GetEnvironment(), and IsHost().
Referenced by lldb_private::RemoteAwarePlatform::GetEnvironment().
GetExtraStartupCommands()
Args Platform::GetExtraStartupCommands () virtual
Reimplemented in lldb_private::PlatformDarwin.
Definition at line 2097 of file Platform.cpp.
GetFile()
Status Platform::GetFile (const FileSpec & source, const FileSpec & destination) virtual
Reimplemented in lldb_private::platform_android::PlatformAndroid, lldb_private::PlatformMacOSX, and PlatformPOSIX.
Definition at line 1203 of file Platform.cpp.
References lldb_private::Status::FromErrorString().
Referenced by BringInRemoteFile(), lldb_private::PlatformMacOSX::GetFile(), PlatformPOSIX::GetFile(), and lldb_private::process_gdb_remote::ProcessGDBRemote::SaveCore().
GetFileExists()
bool Platform::GetFileExists (const lldb_private::FileSpec & file_spec) virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 1216 of file Platform.cpp.
References lldb_private::FileSystem::Exists(), lldb_private::FileSystem::Instance(), and IsHost().
Referenced by lldb_private::RemoteAwarePlatform::GetFileExists().
GetFilePermissions()
Status Platform::GetFilePermissions (const FileSpec & file_spec, uint32_t & file_permissions) virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 610 of file Platform.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::FileSpec::GetPath(), lldb_private::PluginInterface::GetPluginName(), IsHost(), and lldb_private::Status.
Referenced by lldb_private::RemoteAwarePlatform::GetFilePermissions().
GetFileSize()
user_id_t Platform::GetFileSize (const FileSpec & file_spec) virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 654 of file Platform.cpp.
References lldb_private::FileSpec::GetPath(), IsHost(), and UINT64_MAX.
Referenced by lldb_private::RemoteAwarePlatform::GetFileSize().
GetFileWithUUID()
Status Platform::GetFileWithUUID (const FileSpec & platform_file, const UUID * uuid_ptr, FileSpec & local_file) virtual
Locate a file for a platform.
The default implementation of this function will return the same file patch in local_file as was in platform_file.
Parameters
[in] platform_file The platform file path to locate and cache locally.
[in] uuid_ptr If we know the exact UUID of the file we are looking for, it can be specified. If it is not specified, we might now know the exact file. The UUID is usually some sort of MD5 checksum for the file and is sometimes known by dynamic linkers/loaders. If the UUID is known, it is best to supply it to platform file queries to ensure we are finding the correct file, not just a file at the correct path.
[out] local_file A locally cached version of the platform file. For platforms that describe the current host computer, this will just be the same file. For remote platforms, this file might come from and SDK directory, or might need to be sync'ed over to the current machine for efficient debugging access.
Returns
An error object.
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 151 of file Platform.cpp.
References lldb_private::Status.
GetFullNameForDylib()
ConstString Platform::GetFullNameForDylib (ConstString basename) virtual
Reimplemented in lldb_private::PlatformDarwin, lldb_private::PlatformWindows, and PlatformPOSIX.
Definition at line 699 of file Platform.cpp.
GetGlobalPlatformProperties()
PlatformProperties & Platform::GetGlobalPlatformProperties () static
Definition at line 140 of file Platform.cpp.
Referenced by lldb_private::Debugger::Debugger(), GetCachedSharedModule(), and GetModuleCacheRoot().
GetHostname()
const char * Platform::GetHostname () virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 690 of file Platform.cpp.
References IsHost(), and m_hostname.
Referenced by GetCacheHostname(), lldb_private::RemoteAwarePlatform::GetHostname(), and GetStatus().
GetHostPlatform()
PlatformSP Platform::GetHostPlatform () static
Get the native host platform plug-in.
There should only be one of these for each host that LLDB runs upon that should be statically compiled in and registered using preprocessor macros or other similar build mechanisms in a PlatformSubclass::Initialize() function.
This platform will be used as the default platform when launching or attaching to processes unless another platform is specified.
There should only be one of these for each host that LLDB runs upon that should be statically compiled in and registered using preprocessor macros or other similar build mechanisms.
This platform will be used as the default platform when launching or attaching to processes unless another platform is specified.
Definition at line 134 of file Platform.cpp.
References GetHostPlatformSP().
Referenced by Create(), lldb_private::Debugger::Debugger(), CommandObjectPlatformList::DoExecute(), CommandObjectPlatformShell::DoExecute(), lldb::SBDebugger::GetAvailablePlatformInfoAtIndex(), lldb::SBPlatform::GetHostPlatform(), lldb_private::PlatformQemuUser::GetMmapArgumentList(), lldb_private::PlatformWasm::GetMmapArgumentList(), and lldb_private::PlatformList::GetOrCreate().
GetHostPlatformName()
const char * Platform::GetHostPlatformName () static
Definition at line 61 of file Platform.cpp.
Referenced by Create(), lldb_private::platform_aix::PlatformAIX::GetPluginNameStatic(), lldb_private::platform_android::PlatformAndroid::GetPluginNameStatic(), lldb_private::platform_freebsd::PlatformFreeBSD::GetPluginNameStatic(), lldb_private::platform_linux::PlatformLinux::GetPluginNameStatic(), lldb_private::platform_netbsd::PlatformNetBSD::GetPluginNameStatic(), lldb_private::platform_openbsd::PlatformOpenBSD::GetPluginNameStatic(), lldb_private::PlatformMacOSX::GetPluginNameStatic(), and lldb_private::PlatformWindows::GetPluginNameStatic().
GetIgnoresRemoteHostname()
virtual bool lldb_private::Platform::GetIgnoresRemoteHostname () inline virtual
Definition at line 660 of file Platform.h.
References m_ignores_remote_hostname.
Referenced by PlatformPOSIX::GetFile(), PlatformPOSIX::GetPlatformSpecificConnectionInformation(), and PlatformPOSIX::PutFile().
GetLocalCacheDirectory()
const char * Platform::GetLocalCacheDirectory () virtual
Definition at line 1286 of file Platform.cpp.
References m_local_cache_directory.
Referenced by PlatformPOSIX::GetPlatformSpecificConnectionInformation(), and lldb_private::PlatformDarwinDevice::GetSharedModuleWithLocalCache().
GetLocateModuleCallback()
Platform::LocateModuleCallback Platform::GetLocateModuleCallback () const
Definition at line 2105 of file Platform.cpp.
References m_locate_module_callback.
GetMaxGroupIDNameLength()
size_t lldb_private::Platform::GetMaxGroupIDNameLength () const inline
Definition at line 531 of file Platform.h.
References m_max_gid_name_len.
GetMaxUserIDNameLength()
size_t lldb_private::Platform::GetMaxUserIDNameLength () const inline
Definition at line 528 of file Platform.h.
References m_max_uid_name_len.
GetMmapArgumentList()
MmapArgList Platform::GetMmapArgumentList (const ArchSpec & arch, lldb::addr_t addr, lldb::addr_t length, unsigned prot, unsigned flags, lldb::addr_t fd, lldb::addr_t offset) virtual
Reimplemented in lldb_private::platform_aix::PlatformAIX, lldb_private::platform_freebsd::PlatformFreeBSD, lldb_private::platform_linux::PlatformLinux, lldb_private::platform_netbsd::PlatformNetBSD, lldb_private::platform_openbsd::PlatformOpenBSD, lldb_private::PlatformQemuUser, and lldb_private::PlatformWasm.
Definition at line 1228 of file Platform.cpp.
References lldb_private::eMmapFlagsAnon, lldb_private::eMmapFlagsPrivate, MAP_ANON, and MAP_PRIVATE.
GetModuleCacheRoot()
FileSpec Platform::GetModuleCacheRoot () private
Definition at line 1781 of file Platform.cpp.
References lldb_private::FileSpec::AppendPathComponent(), GetGlobalPlatformProperties(), lldb_private::PlatformProperties::GetModuleCacheDirectory(), and lldb_private::PluginInterface::GetPluginName().
Referenced by GetCachedSharedModule().
GetModuleSpec()
bool Platform::GetModuleSpec (const FileSpec & module_file_spec, const ArchSpec & arch, ModuleSpec & module_spec) virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 203 of file Platform.cpp.
References lldb_private::ModuleSpecList::FindMatchingModuleSpec(), and lldb_private::ObjectFile::GetModuleSpecifications().
Referenced by GetRemoteSharedModule().
GetName()
llvm::StringRef lldb_private::Platform::GetName () inline
Definition at line 201 of file Platform.h.
References lldb_private::PluginInterface::GetPluginName().
Referenced by GetSDKPathFromDebugInfo(), GetSDKPathFromDebugInfo(), ResolveSDKPathFromDebugInfo(), and ResolveSDKPathFromDebugInfo().
GetOSBuildString()
std::optional< std::string > Platform::GetOSBuildString ()
Definition at line 338 of file Platform.cpp.
References GetRemoteOSBuildString(), and IsHost().
Referenced by lldb_private::PlatformDarwinDevice::GetSDKDirectoryForCurrentOSVersion(), and GetStatus().
GetOSKernelDescription()
std::optional< std::string > Platform::GetOSKernelDescription ()
Definition at line 344 of file Platform.cpp.
References GetRemoteOSKernelDescription(), and IsHost().
Referenced by GetStatus().
GetOSVersion()
llvm::VersionTuple Platform::GetOSVersion (Process * process = nullptr) virtual
Get the OS version from a connected platform.
Some platforms might not be connected to a remote platform, but can figure out the OS version for a process. This is common for simulator platforms that will run native programs on the current host, but the simulator might be simulating a different OS. The process parameter might be specified to help to determine the OS version.
Reimplemented in lldb_private::PlatformDarwin.
Definition at line 296 of file Platform.cpp.
References lldb_private::Process::GetHostOSVersion(), GetRemoteOSVersion(), IsConnected(), IsHost(), m_mutex, m_os_version, and m_os_version_set_while_connected.
Referenced by lldb_private::PlatformDarwin::GetOSVersion(), and GetStatus().
GetPlatformSpecificConnectionInformation()
virtual std::string lldb_private::Platform::GetPlatformSpecificConnectionInformation () inline virtual
Reimplemented in PlatformPOSIX.
Definition at line 697 of file Platform.h.
Referenced by GetStatus().
GetProcessInfo()
bool Platform::GetProcessInfo (lldb::pid_t pid, ProcessInstanceInfo & proc_info) virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, lldb_private::PlatformQemuUser, and lldb_private::RemoteAwarePlatform.
Definition at line 902 of file Platform.cpp.
References lldb_private::Host::GetProcessInfo(), and IsHost().
Referenced by lldb_private::RemoteAwarePlatform::GetProcessInfo().
GetQueueIDForThreadQAddress()
virtual lldb::queue_id_t lldb_private::Platform::GetQueueIDForThreadQAddress (Process * process, lldb::addr_t dispatch_qaddr) inline virtual
Locate a queue ID given a thread's qaddr.
On a system using libdispatch ("Grand Central Dispatch") style queues, a thread may be associated with a GCD queue or not, and a queue may be associated with multiple threads. The process/thread must provide a way to find the "dispatch_qaddr" for each thread, and from that dispatch_qaddr this Platform method will locate the queue ID and provide that.
Parameters
[in] process A process is required for reading memory.
[in] dispatch_qaddr The dispatch_qaddr for this thread.
Returns
The queue_id for this thread, if this thread is associated with a dispatch queue. Else LLDB_INVALID_QUEUE_ID is returned.
Definition at line 753 of file Platform.h.
References LLDB_INVALID_QUEUE_ID.
GetQueueNameForThreadQAddress()
virtual std::string lldb_private::Platform::GetQueueNameForThreadQAddress (Process * process, lldb::addr_t dispatch_qaddr) inline virtual
Locate a queue name given a thread's qaddr.
On a system using libdispatch ("Grand Central Dispatch") style queues, a thread may be associated with a GCD queue or not, and a queue may be associated with multiple threads. The process/thread must provide a way to find the "dispatch_qaddr" for each thread, and from that dispatch_qaddr this Platform method will locate the queue name and provide that.
Parameters
[in] process A process is required for reading memory.
[in] dispatch_qaddr The dispatch_qaddr for this thread.
Returns
The name of the queue, if there is one. An empty string means that this thread is not associated with a dispatch queue.
Definition at line 730 of file Platform.h.
GetRemoteOSBuildString()
virtual std::optional< std::string > lldb_private::Platform::GetRemoteOSBuildString () inline virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 224 of file Platform.h.
Referenced by GetOSBuildString().
GetRemoteOSKernelDescription()
virtual std::optional< std::string > lldb_private::Platform::GetRemoteOSKernelDescription () inline virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 228 of file Platform.h.
Referenced by GetOSKernelDescription().
GetRemoteOSVersion()
virtual bool lldb_private::Platform::GetRemoteOSVersion () inline virtual
Reimplemented in lldb_private::platform_android::PlatformAndroid, lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 222 of file Platform.h.
Referenced by GetOSVersion().
GetRemoteSharedModule()
Status Platform::GetRemoteSharedModule (const ModuleSpec & module_spec, Process * process, lldb::ModuleSP & module_sp, const ModuleResolver & module_resolver, bool * did_create_ptr) private
Definition at line 1464 of file Platform.cpp.
References CallLocateModuleCallbackIfSet(), error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::ModuleSpec::GetArchitecture(), GetCachedSharedModule(), lldb_private::ModuleSpec::GetFileSpec(), GetModuleSpec(), lldb_private::Process::GetModuleSpec(), lldb_private::ModuleList::GetSharedModule(), GetSupportedArchitectures(), lldb_private::Process::GetSystemArchitecture(), lldb_private::ModuleSpec::GetUUID(), lldb_private::ArchSpec::IsValid(), lldb_private::UUID::IsValid(), and lldb_private::Status.
Referenced by GetCachedExecutable(), and GetSharedModule().
GetRemoteSystemArchitecture()
virtual ArchSpec lldb_private::Platform::GetRemoteSystemArchitecture () inline virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 233 of file Platform.h.
Referenced by GetSystemArchitecture().
GetRemoteUnixSignals()
const UnixSignalsSP & Platform::GetRemoteUnixSignals () virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and PlatformPOSIX.
Definition at line 1789 of file Platform.cpp.
Referenced by lldb_private::platform_gdb_server::PlatformRemoteGDBServer::GetRemoteUnixSignals(), PlatformPOSIX::GetRemoteUnixSignals(), and GetUnixSignals().
GetRemoteWorkingDirectory()
virtual FileSpec lldb_private::Platform::GetRemoteWorkingDirectory () inline virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 237 of file Platform.h.
References m_working_dir.
Referenced by lldb_private::platform_gdb_server::PlatformRemoteGDBServer::GetRemoteWorkingDirectory(), lldb_private::RemoteAwarePlatform::GetRemoteWorkingDirectory(), and GetWorkingDirectory().
GetResumeCountForLaunchInfo()
virtual uint32_t lldb_private::Platform::GetResumeCountForLaunchInfo (ProcessLaunchInfo & launch_info) inline virtual
Reimplemented in lldb_private::platform_linux::PlatformLinux, lldb_private::platform_netbsd::PlatformNetBSD, and lldb_private::PlatformDarwin.
Definition at line 702 of file Platform.h.
Referenced by LaunchProcess().
GetRSyncOpts()
virtual const char * lldb_private::Platform::GetRSyncOpts () inline virtual
Definition at line 642 of file Platform.h.
References m_rsync_opts.
Referenced by PlatformPOSIX::GetFile(), PlatformPOSIX::GetPlatformSpecificConnectionInformation(), and PlatformPOSIX::PutFile().
GetRSyncPrefix()
virtual const char * lldb_private::Platform::GetRSyncPrefix () inline virtual
Definition at line 646 of file Platform.h.
References m_rsync_prefix.
Referenced by PlatformPOSIX::GetFile(), PlatformPOSIX::GetPlatformSpecificConnectionInformation(), and PlatformPOSIX::PutFile().
GetSDKBuild()
const std::string & lldb_private::Platform::GetSDKBuild () const inline
Definition at line 537 of file Platform.h.
References m_sdk_build.
Referenced by lldb_private::PlatformDarwinDevice::GetSDKDirectoryForCurrentOSVersion().
GetSDKDirectory()
virtual lldb_private::ConstString lldb_private::Platform::GetSDKDirectory (lldb_private::Target & target) inline virtual
Reimplemented in lldb_private::PlatformMacOSX.
Definition at line 438 of file Platform.h.
GetSDKPathFromDebugInfo() [1/2]
virtual llvm::Expected< XcodeSDK > lldb_private::Platform::GetSDKPathFromDebugInfo (CompileUnit & unit) inline virtual
Search CU for the SDK path the CUs was compiled against.
Parameters
[in] unit The CU
Returns
A parsed XcodeSDK object if successful, an Error otherwise.
Reimplemented in lldb_private::PlatformDarwin.
Definition at line 482 of file Platform.h.
References GetName().
GetSDKPathFromDebugInfo() [2/2]
virtual llvm::Expected< std::pair< XcodeSDK, bool > > lldb_private::Platform::GetSDKPathFromDebugInfo (Module & module) inline virtual
Search each CU associated with the specified 'module' for the SDK paths the CUs were compiled against.
In the presence of different SDKs, we try to pick the most appropriate one using XcodeSDK::Merge.
Parameters
[in] module Module whose debug-info CUs to parse for which SDK they were compiled against.
Returns
If successful, returns a pair of a parsed XcodeSDK object and a boolean that is 'true' if we encountered a conflicting combination of SDKs when parsing the CUs (e.g., a public and internal SDK).
Reimplemented in lldb_private::PlatformDarwin.
Definition at line 455 of file Platform.h.
References GetName().
GetSDKRootDirectory()
const std::string & lldb_private::Platform::GetSDKRootDirectory () const inline
Definition at line 533 of file Platform.h.
References m_sdk_sysroot.
Referenced by lldb_private::PlatformQemuUser::DebugProcess(), and GetStatus().
GetSharedModule()
Status Platform::GetSharedModule (const ModuleSpec & module_spec, Process * process, lldb::ModuleSP & module_sp, llvm::SmallVectorImpl< lldb::ModuleSP > * old_modules, bool * did_create_ptr) virtual
Parameters
[in] module_spec The ModuleSpec of a binary to find.
[in] process A Process.
[out] module_sp A Module that matches the ModuleSpec, if one is found.
[in] module_search_paths_ptr Locations to possibly look for a binary that matches the ModuleSpec.
[out] old_modules Existing Modules in the Process' Target image list which match the FileSpec.
[out] did_create_ptr Optional boolean, nullptr may be passed for this argument. If this method is returning a new ModuleSP, this will be set to true. If this method is returning a ModuleSP that is already in the Target's image list, it will be false.
Returns
The Status object for any errors found while searching for the binary.
Reimplemented in lldb_private::PlatformAppleSimulator, lldb_private::PlatformDarwin, lldb_private::PlatformMacOSX, and lldb_private::PlatformRemoteDarwinDevice.
Definition at line 164 of file Platform.cpp.
References lldb::eErrorTypeGeneric, error(), lldb_private::ModuleSpec::GetFileSpec(), GetRemoteSharedModule(), lldb_private::ModuleList::GetSharedModule(), IsHost(), m_sdk_sysroot, and lldb_private::FileSpec::PrependPathComponent().
Referenced by lldb_private::PlatformDarwin::FindBundleBinaryInExecSearchPaths(), and lldb_private::PlatformDarwin::GetSharedModule().
GetSiginfoType()
CompilerType Platform::GetSiginfoType (const llvm::Triple & triple) virtual
Reimplemented in lldb_private::platform_aix::PlatformAIX, lldb_private::platform_freebsd::PlatformFreeBSD, lldb_private::platform_linux::PlatformLinux, and lldb_private::platform_netbsd::PlatformNetBSD.
Definition at line 2093 of file Platform.cpp.
GetSoftwareBreakpointTrapOpcode()
size_t Platform::GetSoftwareBreakpointTrapOpcode (Target & target, BreakpointSite * bp_site) virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, lldb_private::PlatformDarwin, and lldb_private::PlatformWindows.
Definition at line 1949 of file Platform.cpp.
References lldb_private::eCodeAlternateISA, lldb_private::ArchSpec::eRISCV_rvc, lldb_private::eUnknown, lldb_private::Target::GetArchitecture(), lldb_private::BreakpointSite::GetConstituentAtIndex(), lldb_private::ArchSpec::GetFlags(), lldb_private::ArchSpec::GetMachine(), lldb_private::ArchSpec::IsValid(), and lldb_private::BreakpointSite::SetTrapOpcode().
Referenced by lldb_private::PlatformDarwin::GetSoftwareBreakpointTrapOpcode(), and lldb_private::PlatformWindows::GetSoftwareBreakpointTrapOpcode().
GetSSHOpts()
virtual const char * lldb_private::Platform::GetSSHOpts () inline virtual
Definition at line 656 of file Platform.h.
References m_ssh_opts.
Referenced by PlatformPOSIX::GetPlatformSpecificConnectionInformation().
GetStatus()
void Platform::GetStatus (Stream & strm) virtual
Report the current status for this platform.
The returned string usually involves returning the OS version (if available), and any SDK directory that might be being used for local file caching, and if connected a quick blurb about what this platform is connected to.
Reimplemented in lldb_private::platform_aix::PlatformAIX, lldb_private::platform_freebsd::PlatformFreeBSD, lldb_private::platform_linux::PlatformLinux, lldb_private::platform_netbsd::PlatformNetBSD, lldb_private::platform_openbsd::PlatformOpenBSD, lldb_private::PlatformAppleSimulator, lldb_private::PlatformRemoteDarwinDevice, and lldb_private::PlatformWindows.
Definition at line 247 of file Platform.cpp.
References lldb_private::Stream::AsRawOstream(), lldb_private::ArchSpec::DumpTriple(), lldb_private::Stream::EOL(), lldb_private::Stream::Format(), GetHostname(), GetOSBuildString(), GetOSKernelDescription(), GetOSVersion(), GetPlatformSpecificConnectionInformation(), lldb_private::PluginInterface::GetPluginName(), GetSDKRootDirectory(), GetSystemArchitecture(), lldb_private::ArchSpec::GetTriple(), GetWorkingDirectory(), IsConnected(), IsHost(), lldb_private::ArchSpec::IsValid(), and lldb_private::Stream::Printf().
Referenced by lldb_private::platform_aix::PlatformAIX::GetStatus(), lldb_private::platform_freebsd::PlatformFreeBSD::GetStatus(), lldb_private::platform_linux::PlatformLinux::GetStatus(), lldb_private::platform_netbsd::PlatformNetBSD::GetStatus(), lldb_private::platform_openbsd::PlatformOpenBSD::GetStatus(), lldb_private::PlatformAppleSimulator::GetStatus(), lldb_private::PlatformRemoteDarwinDevice::GetStatus(), and lldb_private::PlatformWindows::GetStatus().
GetStopInfoFromSiginfo()
virtual lldb::StopInfoSP lldb_private::Platform::GetStopInfoFromSiginfo (Thread & thread) inline virtual
Reimplemented in lldb_private::platform_linux::PlatformLinux.
Definition at line 964 of file Platform.h.
GetSupportedArchitectures()
virtual std::vector< ArchSpec > lldb_private::Platform::GetSupportedArchitectures (const ArchSpec & process_host_arch) pure virtual
Get the platform's supported architectures in the order in which they should be searched.
Parameters
[in] process_host_arch The process host architecture if it's known. An invalid ArchSpec represents that the process host architecture is unknown.
Implemented in lldb_private::platform_aix::PlatformAIX, lldb_private::platform_freebsd::PlatformFreeBSD, lldb_private::platform_gdb_server::PlatformRemoteGDBServer, lldb_private::platform_linux::PlatformLinux, lldb_private::platform_netbsd::PlatformNetBSD, lldb_private::platform_openbsd::PlatformOpenBSD, lldb_private::PlatformAppleSimulator, lldb_private::PlatformMacOSX, lldb_private::PlatformQemuUser, lldb_private::PlatformRemoteAppleBridge, lldb_private::PlatformRemoteAppleTV, lldb_private::PlatformRemoteAppleWatch, lldb_private::PlatformRemoteAppleXR, lldb_private::PlatformRemoteiOS, lldb_private::PlatformRemoteMacOSX, lldb_private::PlatformWasm, and lldb_private::PlatformWindows.
Referenced by GetRemoteSharedModule(), IsCompatibleArchitecture(), and ResolveExecutable().
GetSupportsRSync()
virtual bool lldb_private::Platform::GetSupportsRSync () inline virtual
Definition at line 638 of file Platform.h.
References m_supports_rsync.
Referenced by PlatformPOSIX::GetFile(), PlatformPOSIX::GetPlatformSpecificConnectionInformation(), lldb_private::PlatformDarwinDevice::GetSharedModuleWithLocalCache(), Install(), and PlatformPOSIX::PutFile().
GetSupportsSSH()
virtual bool lldb_private::Platform::GetSupportsSSH () inline virtual
Definition at line 652 of file Platform.h.
References m_supports_ssh.
Referenced by PlatformPOSIX::GetPlatformSpecificConnectionInformation().
GetSystemArchitecture()
const ArchSpec & Platform::GetSystemArchitecture ()
Definition at line 812 of file Platform.cpp.
References GetRemoteSystemArchitecture(), IsConnected(), IsHost(), m_system_arch, and m_system_arch_set_while_connected.
Referenced by lldb_private::PlatformDarwin::ARMGetSupportedArchitectures(), GetStatus(), lldb_private::PlatformRemoteAppleTV::GetSupportedArchitectures(), lldb_private::PlatformRemoteAppleWatch::GetSupportedArchitectures(), and lldb_private::PosixPlatformCommandOptionValidator::IsValid().
GetTrapHandlerSymbolNames()
const std::vector< ConstString > & Platform::GetTrapHandlerSymbolNames () virtual
Provide a list of trap handler function names for this platform.
The unwinder needs to treat trap handlers specially – the stack frame may not be aligned correctly for a trap handler (the kernel often won't perturb the stack pointer, or won't re-align it properly, in the process of calling the handler) and the frame above the handler needs to be treated by the unwinder's "frame 0" rules instead of its "middle of the stack frame" rules.
In a user process debugging scenario, the list of trap handlers is typically just "_sigtramp".
The Platform base class provides the m_trap_handlers ivar but it does not populate it. Subclasses should add the names of the asynchronous signal handler routines as needed. For most Unix platforms, add _sigtramp.
Returns
A list of symbol names. The list may be empty.
Definition at line 1436 of file Platform.cpp.
References CalculateTrapHandlerSymbolNames(), m_calculated_trap_handlers, m_mutex, and m_trap_handlers.
GetTrapHandlerUnwindPlan()
virtual lldb::UnwindPlanSP lldb_private::Platform::GetTrapHandlerUnwindPlan (const ArchSpec & arch, ConstString name) inline virtual
Try to get a specific unwind plan for a named trap handler.
The default is not to have specific unwind plans for trap handlers.
Parameters
[in] arch Architecture of the current target.
[in] name Name of the trap handler function.
Returns
A specific unwind plan for that trap handler, or an empty shared pointer. The latter means there is no specific plan, unwind as normal.
Reimplemented in lldb_private::platform_aix::PlatformAIX, and lldb_private::platform_linux::PlatformLinux.
Definition at line 791 of file Platform.h.
GetUnixSignals()
UnixSignalsSP Platform::GetUnixSignals ()
Definition at line 1794 of file Platform.cpp.
References lldb_private::UnixSignals::CreateForHost(), GetRemoteUnixSignals(), and IsHost().
GetUserIDResolver()
UserIDResolver & Platform::GetUserIDResolver () virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, lldb_private::PlatformQemuUser, lldb_private::PlatformWasm, and lldb_private::RemoteAwarePlatform.
Definition at line 684 of file Platform.cpp.
References lldb_private::UserIDResolver::GetNoopResolver(), and IsHost().
Referenced by lldb_private::RemoteAwarePlatform::GetUserIDResolver().
GetWorkingDirectory()
FileSpec Platform::GetWorkingDirectory ()
Definition at line 359 of file Platform.cpp.
References GetRemoteWorkingDirectory(), lldb_private::FileSystem::Instance(), IsHost(), m_working_dir, and lldb_private::FileSystem::Resolve().
Referenced by GetStatus(), Install(), and LoadImage().
Initialize()
void Platform::Initialize () static
Definition at line 136 of file Platform.cpp.
Referenced by lldb_private::platform_aix::PlatformAIX::Initialize(), lldb_private::platform_freebsd::PlatformFreeBSD::Initialize(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::Initialize(), lldb_private::platform_linux::PlatformLinux::Initialize(), lldb_private::platform_netbsd::PlatformNetBSD::Initialize(), lldb_private::platform_openbsd::PlatformOpenBSD::Initialize(), lldb_private::PlatformDarwin::Initialize(), and lldb_private::PlatformWindows::Initialize().
Install()
Status Platform::Install (const FileSpec & src, const FileSpec & dst) virtual
Install a file or directory to the remote system.
Install is similar to Platform::PutFile(), but it differs in that if an application/framework/shared library is installed on a remote platform and the remote platform requires something to be done to register the application/framework/shared library, then this extra registration can be done.
Parameters
[in] src The source file/directory to install on the remote system.
[in] dst The destination file/directory where src will be installed. If dst has no filename specified, then its filename will be set from src. It dst has no directory specified, it will use the platform working directory. If dst has a directory specified, but the directory path is relative, the platform working directory will be prepended to the relative directory.
Returns
An error object that describes anything that went wrong.
Definition at line 470 of file Platform.cpp.
References lldb_private::FileSpec::AppendPathComponent(), CreateSymlink(), lldb_private::FileSystem::EnumerateDirectory(), error(), RecurseCopyBaton::error, lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::ConstString::GetCString(), lldb_private::FileSpec::GetDirectory(), lldb_private::FileSpec::GetFilename(), lldb_private::GetLog(), lldb_private::FileSpec::GetPath(), lldb_private::FileSpec::GetPathAsConstString(), lldb_private::FileSystem::GetPermissions(), GetSupportsRSync(), GetWorkingDirectory(), lldb_private::FileSystem::Instance(), LLDB_LOGF, MakeDirectory(), lldb_private::Platform, PutFile(), lldb_private::FileSystem::Readlink(), RecurseCopy_Callback(), lldb_private::FileSpec::SetDirectory(), lldb_private::FileSpec::SetFilename(), and lldb_private::Status.
Referenced by LoadImage().
IsCompatibleArchitecture()
bool Platform::IsCompatibleArchitecture (const ArchSpec & arch, const ArchSpec & process_host_arch, ArchSpec::MatchType match, ArchSpec * compatible_arch_ptr) virtual
Lets a platform answer if it is compatible with a given architecture and the target triple contained within.
Definition at line 1096 of file Platform.cpp.
References lldb_private::ArchSpec::Clear(), GetSupportedArchitectures(), lldb_private::ArchSpec::IsMatch(), and lldb_private::ArchSpec::IsValid().
Referenced by GetAugmentedArchSpec().
IsConnected()
virtual bool lldb_private::Platform::IsConnected () const inline virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, lldb_private::PlatformQemuUser, and lldb_private::RemoteAwarePlatform.
Definition at line 509 of file Platform.h.
References IsHost().
Referenced by GetOSVersion(), GetStatus(), GetSystemArchitecture(), lldb_private::RemoteAwarePlatform::IsConnected(), and SetOSVersion().
IsHost()
bool lldb_private::Platform::IsHost () const inline
Definition at line 503 of file Platform.h.
References m_is_host.
Referenced by lldb_private::PlatformWindows::Attach(), PlatformPOSIX::Attach(), CalculateMD5(), lldb_private::platform_freebsd::PlatformFreeBSD::CanDebugProcess(), lldb_private::platform_linux::PlatformLinux::CanDebugProcess(), lldb_private::platform_netbsd::PlatformNetBSD::CanDebugProcess(), lldb_private::PlatformDarwin::CheckLocalSharedCache(), CloseFile(), ConnectRemote(), lldb_private::platform_android::PlatformAndroid::ConnectRemote(), lldb_private::PlatformWasm::ConnectRemote(), lldb_private::PlatformWindows::ConnectRemote(), PlatformPOSIX::ConnectRemote(), CreateSymlink(), lldb_private::PlatformDarwin::DebugProcess(), PlatformPOSIX::DebugProcess(), DisconnectRemote(), lldb_private::PlatformWindows::DisconnectRemote(), PlatformPOSIX::DisconnectRemote(), FindProcesses(), GetCachedSharedModule(), lldb_private::platform_aix::PlatformAIX::GetDescription(), lldb_private::platform_freebsd::PlatformFreeBSD::GetDescription(), lldb_private::platform_linux::PlatformLinux::GetDescription(), lldb_private::platform_netbsd::PlatformNetBSD::GetDescription(), lldb_private::platform_openbsd::PlatformOpenBSD::GetDescription(), lldb_private::PlatformWindows::GetDescription(), GetEnvironment(), lldb_private::platform_android::PlatformAndroid::GetFile(), PlatformPOSIX::GetFile(), GetFileExists(), GetFilePermissions(), GetFileSize(), GetHostname(), GetOSBuildString(), GetOSKernelDescription(), GetOSVersion(), lldb_private::platform_aix::PlatformAIX::GetPluginName(), lldb_private::platform_android::PlatformAndroid::GetPluginName(), lldb_private::platform_freebsd::PlatformFreeBSD::GetPluginName(), lldb_private::platform_linux::PlatformLinux::GetPluginName(), lldb_private::platform_netbsd::PlatformNetBSD::GetPluginName(), lldb_private::platform_openbsd::PlatformOpenBSD::GetPluginName(), lldb_private::PlatformWindows::GetPluginName(), GetProcessInfo(), GetSharedModule(), lldb_private::PlatformDarwinDevice::GetSharedModuleWithLocalCache(), GetStatus(), lldb_private::platform_aix::PlatformAIX::GetStatus(), lldb_private::platform_freebsd::PlatformFreeBSD::GetStatus(), lldb_private::platform_linux::PlatformLinux::GetStatus(), lldb_private::platform_netbsd::PlatformNetBSD::GetStatus(), lldb_private::platform_openbsd::PlatformOpenBSD::GetStatus(), GetSystemArchitecture(), GetUnixSignals(), GetUserIDResolver(), GetWorkingDirectory(), IsConnected(), KillProcess(), LaunchProcess(), MakeDirectory(), OpenFile(), lldb_private::platform_android::PlatformAndroid::PutFile(), PlatformPOSIX::PutFile(), ReadFile(), lldb_private::RemoteAwarePlatform::ResolveExecutable(), RunShellCommand(), SetFilePermissions(), SetOSVersion(), SetSystemArchitecture(), SetWorkingDirectory(), ShellExpandArguments(), Unlink(), and WriteFile().
IsRemote()
bool lldb_private::Platform::IsRemote () const inline
Definition at line 507 of file Platform.h.
References m_is_host.
Referenced by lldb_private::platform_gdb_server::PlatformRemoteGDBServer::Attach(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::DebugProcess(), lldb_private::PlatformWindows::DebugProcess(), lldb_private::RemoteAwarePlatform::GetFileWithUUID(), PlatformPOSIX::GetRemoteUnixSignals(), lldb_private::RemoteAwarePlatform::GetRemoteWorkingDirectory(), lldb_private::PlatformDarwin::GetSharedModule(), LoadImage(), lldb_private::process_gdb_remote::ProcessGDBRemote::SaveCore(), and lldb_private::RemoteAwarePlatform::SetRemoteWorkingDirectory().
KillProcess()
Status Platform::KillProcess (const lldb::pid_t pid) virtual
Kill process on a platform.
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 985 of file Platform.cpp.
References lldb_private::Status::FromErrorString(), lldb_private::GetLog(), IsHost(), lldb_private::Host::Kill(), LLDB_LOGF, lldb_private::Platform, SIGKILL, and lldb_private::Status.
Referenced by lldb_private::RemoteAwarePlatform::KillProcess().
LaunchProcess()
Status Platform::LaunchProcess (ProcessLaunchInfo & launch_info) virtual
Launch a new process on a platform, not necessarily for debugging, it could be just for running the process.
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, lldb_private::PlatformAppleSimulator, lldb_private::PlatformDarwin, and lldb_private::RemoteAwarePlatform.
Definition at line 929 of file Platform.cpp.
References lldb_private::ProcessLaunchInfo::ConvertArgumentsForLaunchingInShell(), error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::ProcessLaunchInfo::GetFlags(), lldb_private::GetLog(), lldb_private::FileSpec::GetPath(), lldb_private::ProcessLaunchInfo::GetResumeCount(), GetResumeCountForLaunchInfo(), lldb_private::ProcessLaunchInfo::GetShell(), IsHost(), lldb_private::Host::LaunchProcess(), LLDB_LOGF, lldb_private::Platform, lldb_private::Flags::Set(), ShellExpandArguments(), and lldb_private::Flags::Test().
Referenced by DebugProcess(), lldb_private::PlatformDarwin::LaunchProcess(), and lldb_private::RemoteAwarePlatform::LaunchProcess().
LoadImage()
uint32_t Platform::LoadImage (lldb_private::Process * process, const lldb_private::FileSpec & local_file, const lldb_private::FileSpec & remote_file, lldb_private::Status & error)
Load a shared library into this process.
Try and load a shared library into the current process. This call might fail in the dynamic loader plug-in says it isn't safe to try and load shared libraries at the moment.
Parameters
[in] process The process to load the image.
[in] local_file The file spec that points to the shared library that you want to load if the library is located on the host. The library will be copied over to the location specified by remote_file or into the current working directory with the same filename if the remote_file isn't specified.
[in] remote_file If local_file is specified then the location where the library should be copied over from the host. If local_file isn't specified, then the path for the shared library on the target what you want to load.
[out] error An error object that gets filled in with any errors that might occur when trying to load the shared library.
Returns
A token that represents the shared library that can be later used to unload the shared library. A value of LLDB_INVALID_IMAGE_TOKEN will be returned if the shared library can't be opened.
Definition at line 1800 of file Platform.cpp.
References lldb_private::FileSpec::AppendPathComponent(), lldb_private::ConstString::AsCString(), DoLoadImage(), error(), lldb_private::Status::FromErrorString(), lldb_private::FileSpec::GetFilename(), GetWorkingDirectory(), Install(), IsRemote(), and LLDB_INVALID_IMAGE_TOKEN.
LoadImageUsingPaths()
uint32_t Platform::LoadImageUsingPaths (lldb_private::Process * process, const lldb_private::FileSpec & library_name, const std::vector< std::string > & paths, lldb_private::Status & error, lldb_private::FileSpec * loaded_path)
Load a shared library specified by base name into this process, looking by hand along a set of paths.
Parameters
[in] process The process to load the image.
[in] library_name The name of the library to look for. If library_name is an absolute path, the basename will be extracted and searched for along the paths. This emulates the behavior of the loader when given an install name and a set (e.g. DYLD_LIBRARY_PATH provided) of alternate paths.
[in] paths The list of paths to use to search for the library. First match wins.
[out] error An error object that gets filled in with any errors that might occur when trying to load the shared library.
[out] loaded_path If non-null, the path to the dylib that was successfully loaded is stored in this path.
Returns
A token that represents the shared library which can be passed to UnloadImage. A value of LLDB_INVALID_IMAGE_TOKEN will be returned if the shared library can't be opened.
Definition at line 1848 of file Platform.cpp.
References DoLoadImage(), error(), lldb_private::FileSpec::GetFilename(), lldb_private::FileSpec::GetPathStyle(), lldb_private::ConstString::GetStringRef(), and lldb_private::FileSpec::IsAbsolute().
LoadPlatformBinaryAndSetup()
virtual bool lldb_private::Platform::LoadPlatformBinaryAndSetup (Process * process, lldb::addr_t addr, bool notify) inline virtual
Detect a binary in memory that will determine which Platform and DynamicLoader should be used in this target/process, and update the Platform/DynamicLoader.
The binary will be loaded into the Target, or will be registered with the DynamicLoader so that it will be loaded at a later stage. Returns true to indicate that this is a platform binary and has been loaded/registered, no further action should be taken by the caller.
Parameters
[in] process Process read memory from, a Process must be provided.
[in] addr Address of a binary in memory.
[in] notify Whether ModulesDidLoad should be called, if a binary is loaded. Caller may prefer to call ModulesDidLoad for multiple binaries that were loaded at the same time.
Returns
Returns true if the binary was loaded in the target (or will be via a DynamicLoader). Returns false if the binary was not loaded/registered, and the caller must load it into the target.
Definition at line 957 of file Platform.h.
LocateExecutable()
virtual FileSpec lldb_private::Platform::LocateExecutable (const char * basename) inline virtual
Find a support executable that may not live within in the standard locations related to LLDB.
Executable might exist within the Platform SDK directories, or in standard tool directories within the current IDE that is running LLDB.
Parameters
[in] basename The basename of the executable to locate in the current platform.
Returns
A FileSpec pointing to the executable on disk, or an invalid FileSpec if the executable cannot be found.
Reimplemented in lldb_private::PlatformDarwin.
Definition at line 809 of file Platform.h.
Referenced by GetDebugserverPath().
LocateExecutableScriptingResources()
FileSpecList Platform::LocateExecutableScriptingResources (Target * target, Module & module, Stream & feedback_stream) virtual
Reimplemented in lldb_private::PlatformDarwin.
Definition at line 159 of file Platform.cpp.
MakeDirectory()
Status Platform::MakeDirectory (const FileSpec & file_spec, uint32_t permissions) virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 597 of file Platform.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::FileSpec::GetPath(), lldb_private::PluginInterface::GetPluginName(), and IsHost().
Referenced by Install(), lldb_private::RemoteAwarePlatform::MakeDirectory(), and RecurseCopy_Callback().
ModuleIsExcludedForUnconstrainedSearches()
virtual bool lldb_private::Platform::ModuleIsExcludedForUnconstrainedSearches (Target & target, const lldb::ModuleSP & module_sp) inline virtual
Reimplemented in lldb_private::PlatformDarwin.
Definition at line 563 of file Platform.h.
OpenFile()
user_id_t Platform::OpenFile (const FileSpec & file_spec, File::OpenOptions flags, uint32_t mode, Status & error) virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 640 of file Platform.cpp.
References error(), lldb_private::FileCache::GetInstance(), IsHost(), lldb_private::FileCache::OpenFile(), and UINT64_MAX.
Referenced by DownloadModuleSlice(), lldb_private::RemoteAwarePlatform::OpenFile(), and PutFile().
PutFile()
Status Platform::PutFile (const FileSpec & source, const FileSpec & destination, uint32_t uid = UINT32_MAX, uint32_t gid = UINT32_MAX) virtual
Reimplemented in lldb_private::platform_android::PlatformAndroid, lldb_private::platform_gdb_server::PlatformRemoteGDBServer, lldb_private::PlatformDarwin, and PlatformPOSIX.
Definition at line 1117 of file Platform.cpp.
References CalculateMD5(), CloseFile(), lldb_private::File::eOpenOptionCanCreate, lldb_private::File::eOpenOptionCloseOnExec, lldb_private::File::eOpenOptionDontFollowSymlinks, lldb_private::File::eOpenOptionReadOnly, lldb_private::File::eOpenOptionTruncate, lldb_private::File::eOpenOptionWriteOnly, error(), lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), lldb_private::GetLog(), lldb_private::FileSpec::GetPath(), lldb_private::FileSystem::Instance(), LLDB_LOG, LLDB_LOGF, lldb_private::FileSystem::Open(), OpenFile(), lldb_private::Platform, UINT32_MAX, UINT64_MAX, and WriteFile().
Referenced by Install(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::PutFile(), PlatformPOSIX::PutFile(), and RecurseCopy_Callback().
ReadFile()
uint64_t Platform::ReadFile (lldb::user_id_t fd, uint64_t offset, void * dst, uint64_t dst_len, Status & error) virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 664 of file Platform.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::FileCache::GetInstance(), lldb_private::PluginInterface::GetPluginName(), IsHost(), and lldb_private::FileCache::ReadFile().
Referenced by DownloadModuleSlice(), and lldb_private::RemoteAwarePlatform::ReadFile().
ResolveExecutable()
Status Platform::ResolveExecutable (const ModuleSpec & module_spec, lldb::ModuleSP & exe_module_sp) virtual
Set the target's executable based off of the existing architecture information in target given a path to an executable exe_file.
Each platform knows the architectures that it supports and can select the correct architecture slice within exe_file by inspecting the architecture in target. If the target had an architecture specified, then in can try and obey that request and optionally fail if the architecture doesn't match up. If no architecture is specified, the platform should select the default architecture from exe_file. Any application bundles or executable wrappers can also be inspected for the actual application binary within the bundle that should be used.
Returns
Returns true if this Platform plug-in was able to find a suitable executable, false otherwise.
Reimplemented in lldb_private::RemoteAwarePlatform.
Definition at line 733 of file Platform.cpp.
References error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::ModuleSpec::GetArchitecture(), lldb_private::StreamString::GetData(), lldb_private::ModuleSpec::GetFileSpec(), lldb_private::PluginInterface::GetPluginName(), lldb_private::ModuleList::GetSharedModule(), GetSupportedArchitectures(), lldb_private::ModuleSpec::GetUUID(), lldb_private::FileSystem::Instance(), lldb_private::ObjectFile::IsObjectFile(), lldb_private::ArchSpec::IsValid(), lldb_private::UUID::IsValid(), and lldb_private::Host::ResolveExecutableInBundle().
Referenced by GetCachedExecutable(), and lldb_private::RemoteAwarePlatform::ResolveExecutable().
ResolveRemotePath()
bool Platform::ResolveRemotePath (const FileSpec & platform_path, FileSpec & resolved_platform_path) virtual
Resolves the FileSpec to a (possibly) remote path.
Remote platforms must override this to resolve to a path on the remote side.
Definition at line 805 of file Platform.cpp.
References lldb_private::FileSystem::Instance(), and lldb_private::FileSystem::Resolve().
ResolveSDKPathFromDebugInfo() [1/2]
virtual llvm::Expected< std::string > lldb_private::Platform::ResolveSDKPathFromDebugInfo (CompileUnit & unit) inline virtual
Returns the full path of the most appropriate SDK for the specified compile unit.
This function gets this path by parsing debug-info (see `GetSDKPathFromDebugInfo`).
Parameters
[in] unit The CU to scan.
Returns
If successful, returns the full path to an Xcode SDK.
Reimplemented in lldb_private::PlatformDarwin.
Definition at line 497 of file Platform.h.
References GetName().
ResolveSDKPathFromDebugInfo() [2/2]
virtual llvm::Expected< std::string > lldb_private::Platform::ResolveSDKPathFromDebugInfo (Module & module) inline virtual
Returns the full path of the most appropriate SDK for the specified 'module'.
This function gets this path by parsing debug-info (see `GetSDKPathFromDebugInfo`).
Parameters
[in] module Module whose debug-info to parse for which SDK it was compiled against.
Returns
If successful, returns the full path to an Xcode SDK.
Reimplemented in lldb_private::PlatformDarwin.
Definition at line 471 of file Platform.h.
References GetName().
ResolveSymbolFile()
Status Platform::ResolveSymbolFile (Target & target, const ModuleSpec & sym_spec, FileSpec & sym_file) virtual
Find a symbol file given a symbol file module specification.
Each platform might have tricks to find symbol files for an executable given information in a symbol file ModuleSpec. Some platforms might also support symbol files that are bundles and know how to extract the right symbol file given a bundle.
Parameters
[in] target The target in which we are trying to resolve the symbol file. The target has a list of modules that we might be able to use in order to help find the right symbol file. If the "m_file" or "m_platform_file" entries in the sym_spec are filled in, then we might be able to locate a module in the target, extract its UUID and locate a symbol file. If just the "m_uuid" is specified, then we might be able to find the module in the target that matches that UUID and pair the symbol file along with it. If just "m_symbol_file" is specified, we can use a variety of tricks to locate the symbols in an SDK, PDK, or other development kit location.
[in] sym_spec A module spec that describes some information about the symbol file we are trying to resolve. The ModuleSpec might contain the following: m_file - A full or partial path to an executable from the target (might be empty). m_platform_file - Another executable hint that contains the path to the file as known on the local/remote platform. m_symbol_file - A full or partial path to a symbol file or symbol bundle that should be used when trying to resolve the symbol file. m_arch - The architecture we are looking for when resolving the symbol file. m_uuid - The UUID of the executable and symbol file. This can often be used to match up an executable with a symbol file, or resolve an symbol file in a symbol file bundle.
[out] sym_file The resolved symbol file spec if the returned error indicates success.
Returns
Returns an error that describes success or failure.
Reimplemented in lldb_private::PlatformDarwin.
Definition at line 795 of file Platform.cpp.
References error(), lldb_private::Status::FromErrorString(), lldb_private::ModuleSpec::GetSymbolFileSpec(), and lldb_private::FileSystem::Instance().
RunShellCommand() [1/2]
lldb_private::Status Platform::RunShellCommand (llvm::StringRef command, const FileSpec & working_dir, int * status_ptr, int * signo_ptr, std::string * command_output, const Timeout< std::micro > & timeout) virtual
Reimplemented in lldb_private::RemoteAwarePlatform.
Definition at line 1242 of file Platform.cpp.
References RunShellCommand().
Referenced by chown_file(), RunShellCommand(), and lldb_private::RemoteAwarePlatform::RunShellCommand().
RunShellCommand() [2/2]
lldb_private::Status Platform::RunShellCommand (llvm::StringRef shell, llvm::StringRef command, const FileSpec & working_dir, int * status_ptr, int * signo_ptr, std::string * command_output, const Timeout< std::micro > & timeout) virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 1256 of file Platform.cpp.
References lldb_private::Status::FromErrorString(), IsHost(), and lldb_private::Host::RunShellCommand().
SetFilePermissions()
Status Platform::SetFilePermissions (const FileSpec & file_spec, uint32_t file_permissions) virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 626 of file Platform.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::FileSpec::GetPath(), lldb_private::PluginInterface::GetPluginName(), and IsHost().
Referenced by lldb_private::RemoteAwarePlatform::SetFilePermissions().
SetHostPlatform()
void Platform::SetHostPlatform (const lldb::PlatformSP & platform_sp) static
Definition at line 145 of file Platform.cpp.
References GetHostPlatformSP().
Referenced by lldb_private::platform_aix::PlatformAIX::Initialize(), lldb_private::platform_android::PlatformAndroid::Initialize(), lldb_private::platform_freebsd::PlatformFreeBSD::Initialize(), lldb_private::platform_linux::PlatformLinux::Initialize(), lldb_private::platform_netbsd::PlatformNetBSD::Initialize(), lldb_private::platform_openbsd::PlatformOpenBSD::Initialize(), lldb_private::PlatformMacOSX::Initialize(), and lldb_private::PlatformWindows::Initialize().
SetIgnoresRemoteHostname()
virtual void lldb_private::Platform::SetIgnoresRemoteHostname (bool flag) inline virtual
Definition at line 662 of file Platform.h.
References m_ignores_remote_hostname.
Referenced by PlatformPOSIX::ConnectRemote().
SetLocalCacheDirectory()
void Platform::SetLocalCacheDirectory (const char * local) virtual
Definition at line 1282 of file Platform.cpp.
References m_local_cache_directory.
Referenced by PlatformPOSIX::ConnectRemote().
SetLocateModuleCallback()
void Platform::SetLocateModuleCallback (LocateModuleCallback callback)
Set locate module callback.
This allows users to implement their own module cache system. For example, to leverage artifacts of build system, to bypass pulling files from remote platform, or to search symbol files from symbol servers.
Definition at line 2101 of file Platform.cpp.
References m_locate_module_callback.
SetOSVersion()
bool Platform::SetOSVersion (llvm::VersionTuple os_version)
Definition at line 711 of file Platform.cpp.
References IsConnected(), IsHost(), and m_os_version.
SetRemoteWorkingDirectory()
bool Platform::SetRemoteWorkingDirectory (const FileSpec & working_dir) virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 703 of file Platform.cpp.
References lldb_private::GetLog(), lldb_private::FileSpec::GetPath(), LLDB_LOGF, m_working_dir, and lldb_private::Platform.
Referenced by lldb_private::platform_gdb_server::PlatformRemoteGDBServer::SetRemoteWorkingDirectory(), lldb_private::RemoteAwarePlatform::SetRemoteWorkingDirectory(), and SetWorkingDirectory().
SetRSyncOpts()
virtual void lldb_private::Platform::SetRSyncOpts (const char * opts) inline virtual
Definition at line 644 of file Platform.h.
References m_rsync_opts.
Referenced by PlatformPOSIX::ConnectRemote().
SetRSyncPrefix()
virtual void lldb_private::Platform::SetRSyncPrefix (const char * prefix) inline virtual
Definition at line 648 of file Platform.h.
References m_rsync_prefix.
Referenced by PlatformPOSIX::ConnectRemote().
SetSDKBuild()
void lldb_private::Platform::SetSDKBuild (std::string sdk_build) inline
Definition at line 539 of file Platform.h.
References m_sdk_build.
SetSDKRootDirectory()
void lldb_private::Platform::SetSDKRootDirectory (std::string dir) inline
Definition at line 535 of file Platform.h.
References m_sdk_sysroot.
SetSSHOpts()
virtual void lldb_private::Platform::SetSSHOpts (const char * opts) inline virtual
Definition at line 658 of file Platform.h.
References m_ssh_opts.
Referenced by PlatformPOSIX::ConnectRemote().
SetSupportsRSync()
virtual void lldb_private::Platform::SetSupportsRSync (bool flag) inline virtual
Definition at line 640 of file Platform.h.
References m_supports_rsync.
Referenced by PlatformPOSIX::ConnectRemote().
SetSupportsSSH()
virtual void lldb_private::Platform::SetSupportsSSH (bool flag) inline virtual
Definition at line 654 of file Platform.h.
References m_supports_ssh.
Referenced by PlatformPOSIX::ConnectRemote().
SetSystemArchitecture()
void lldb_private::Platform::SetSystemArchitecture (const ArchSpec & arch) inline
Definition at line 516 of file Platform.h.
References IsHost(), m_os_version_set_while_connected, and m_system_arch.
SetThreadCreationBreakpoint()
lldb::BreakpointSP Platform::SetThreadCreationBreakpoint (lldb_private::Target & target) virtual
Reimplemented in lldb_private::PlatformDarwin.
Definition at line 1364 of file Platform.cpp.
SetWorkingDirectory()
bool Platform::SetWorkingDirectory (const FileSpec & working_dir)
Definition at line 582 of file Platform.cpp.
References lldb_private::GetLog(), lldb_private::FileSpec::GetPath(), IsHost(), LLDB_LOG, m_working_dir, lldb_private::Platform, and SetRemoteWorkingDirectory().
ShellExpandArguments()
Status Platform::ShellExpandArguments (ProcessLaunchInfo & launch_info) virtual
Perform expansion of the command-line for this launch info This can potentially involve wildcard expansion environment variable replacement, and whatever other argument magic the platform defines as part of its typical user experience.
Definition at line 978 of file Platform.cpp.
References lldb_private::Status::FromErrorString(), IsHost(), and lldb_private::Host::ShellExpandArguments().
Referenced by LaunchProcess().
SupportsModules()
virtual bool lldb_private::Platform::SupportsModules () inline virtual
Reimplemented in lldb_private::PlatformDarwin.
Definition at line 546 of file Platform.h.
Terminate()
void Platform::Terminate () static
Definition at line 138 of file Platform.cpp.
Referenced by lldb_private::platform_aix::PlatformAIX::Terminate(), lldb_private::platform_freebsd::PlatformFreeBSD::Terminate(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::Terminate(), lldb_private::platform_linux::PlatformLinux::Terminate(), lldb_private::platform_netbsd::PlatformNetBSD::Terminate(), lldb_private::platform_openbsd::PlatformOpenBSD::Terminate(), lldb_private::PlatformDarwin::Terminate(), and lldb_private::PlatformWindows::Terminate().
Unlink()
Status Platform::Unlink (const FileSpec & file_spec) virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 1222 of file Platform.cpp.
References lldb_private::Status::FromErrorString(), lldb_private::FileSpec::GetPath(), and IsHost().
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::SaveCore(), and lldb_private::RemoteAwarePlatform::Unlink().
UnloadImage()
Status Platform::UnloadImage (lldb_private::Process * process, uint32_t image_token) virtual
Reimplemented in lldb_private::PlatformWindows, and PlatformPOSIX.
Definition at line 1865 of file Platform.cpp.
References lldb_private::Status::FromErrorString().
WriteFile()
uint64_t Platform::WriteFile (lldb::user_id_t fd, uint64_t offset, const void * src, uint64_t src_len, Status & error) virtual
Reimplemented in lldb_private::platform_gdb_server::PlatformRemoteGDBServer, and lldb_private::RemoteAwarePlatform.
Definition at line 674 of file Platform.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::FileCache::GetInstance(), lldb_private::PluginInterface::GetPluginName(), IsHost(), and lldb_private::FileCache::WriteFile().
Referenced by PutFile(), and lldb_private::RemoteAwarePlatform::WriteFile().
Member Data Documentation
m_calculated_trap_handlers
bool lldb_private::Platform::m_calculated_trap_handlers protected
Definition at line 1025 of file Platform.h.
Referenced by GetTrapHandlerSymbolNames(), and Platform().
m_hostname
std::string lldb_private::Platform::m_hostname protected
Definition at line 1007 of file Platform.h.
Referenced by GetHostname(), and lldb_private::platform_gdb_server::PlatformRemoteGDBServer::GetHostname().
m_ignores_remote_hostname
bool lldb_private::Platform::m_ignores_remote_hostname protected
Definition at line 1022 of file Platform.h.
Referenced by GetIgnoresRemoteHostname(), Platform(), and SetIgnoresRemoteHostname().
m_is_host
bool lldb_private::Platform::m_is_host protected
Definition at line 994 of file Platform.h.
Referenced by IsHost(), IsRemote(), and Platform().
m_local_cache_directory
std::string lldb_private::Platform::m_local_cache_directory protected
Definition at line 1023 of file Platform.h.
Referenced by GetLocalCacheDirectory(), and SetLocalCacheDirectory().
m_locate_module_callback
LocateModuleCallback lldb_private::Platform::m_locate_module_callback protected
Definition at line 1027 of file Platform.h.
Referenced by CallLocateModuleCallbackIfSet(), GetLocateModuleCallback(), and SetLocateModuleCallback().
m_max_gid_name_len
size_t lldb_private::Platform::m_max_gid_name_len protected
Definition at line 1016 of file Platform.h.
Referenced by GetMaxGroupIDNameLength(), and Platform().
m_max_uid_name_len
size_t lldb_private::Platform::m_max_uid_name_len protected
Definition at line 1015 of file Platform.h.
Referenced by GetMaxUserIDNameLength(), and Platform().
m_module_cache
const std::unique_ptr<ModuleCache> lldb_private::Platform::m_module_cache protected
Definition at line 1026 of file Platform.h.
Referenced by GetCachedSharedModule(), and Platform().
m_mutex
std::mutex lldb_private::Platform::m_mutex protected
Definition at line 1014 of file Platform.h.
Referenced by lldb_private::PlatformDarwin::AddClangModuleCompilationOptionsForSDKType(), GetOSVersion(), and GetTrapHandlerSymbolNames().
m_os_version
llvm::VersionTuple lldb_private::Platform::m_os_version protected
Definition at line 1008 of file Platform.h.
Referenced by GetOSVersion(), lldb_private::platform_android::PlatformAndroid::GetRemoteOSVersion(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::GetRemoteOSVersion(), lldb_private::RemoteAwarePlatform::GetRemoteOSVersion(), and SetOSVersion().
m_os_version_set_while_connected
bool lldb_private::Platform::m_os_version_set_while_connected protected
Definition at line 1000 of file Platform.h.
Referenced by GetOSVersion(), Platform(), and SetSystemArchitecture().
m_rsync_opts
std::string lldb_private::Platform::m_rsync_opts protected
Definition at line 1018 of file Platform.h.
Referenced by GetRSyncOpts(), Platform(), and SetRSyncOpts().
m_rsync_prefix
std::string lldb_private::Platform::m_rsync_prefix protected
Definition at line 1019 of file Platform.h.
Referenced by GetRSyncPrefix(), Platform(), and SetRSyncPrefix().
m_sdk_build
std::string lldb_private::Platform::m_sdk_build protected
Definition at line 1004 of file Platform.h.
Referenced by GetSDKBuild(), and SetSDKBuild().
m_sdk_sysroot
std::string lldb_private::Platform::m_sdk_sysroot protected
Definition at line 1003 of file Platform.h.
Referenced by lldb_private::PlatformDarwinDevice::GetDeviceSupportDirectoryForOSVersion(), GetSDKRootDirectory(), GetSharedModule(), SetSDKRootDirectory(), and lldb_private::PlatformDarwinDevice::UpdateSDKDirectoryInfosIfNeeded().
m_ssh_opts
std::string lldb_private::Platform::m_ssh_opts protected
Definition at line 1021 of file Platform.h.
Referenced by GetSSHOpts(), Platform(), and SetSSHOpts().
m_supports_rsync
bool lldb_private::Platform::m_supports_rsync protected
Definition at line 1017 of file Platform.h.
Referenced by GetSupportsRSync(), Platform(), and SetSupportsRSync().
m_supports_ssh
bool lldb_private::Platform::m_supports_ssh protected
Definition at line 1020 of file Platform.h.
Referenced by GetSupportsSSH(), Platform(), and SetSupportsSSH().
m_system_arch
ArchSpec lldb_private::Platform::m_system_arch protected
Definition at line 1010 of file Platform.h.
Referenced by GetSystemArchitecture(), and SetSystemArchitecture().
m_system_arch_set_while_connected
bool lldb_private::Platform::m_system_arch_set_while_connected protected
Definition at line 1001 of file Platform.h.
Referenced by GetSystemArchitecture(), and Platform().
m_trap_handlers
std::vector<ConstString> lldb_private::Platform::m_trap_handlers protected
Definition at line 1024 of file Platform.h.
Referenced by lldb_private::platform_freebsd::PlatformFreeBSD::CalculateTrapHandlerSymbolNames(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::CalculateTrapHandlerSymbolNames(), lldb_private::platform_linux::PlatformLinux::CalculateTrapHandlerSymbolNames(), lldb_private::platform_netbsd::PlatformNetBSD::CalculateTrapHandlerSymbolNames(), lldb_private::platform_openbsd::PlatformOpenBSD::CalculateTrapHandlerSymbolNames(), lldb_private::PlatformDarwin::CalculateTrapHandlerSymbolNames(), PlatformPOSIX::CalculateTrapHandlerSymbolNames(), GetTrapHandlerSymbolNames(), and Platform().
m_working_dir
FileSpec lldb_private::Platform::m_working_dir protected
Definition at line 1005 of file Platform.h.
Referenced by lldb_private::platform_gdb_server::PlatformRemoteGDBServer::ConnectRemote(), GetRemoteWorkingDirectory(), GetWorkingDirectory(), SetRemoteWorkingDirectory(), and SetWorkingDirectory().
The documentation for this class was generated from the following files:
Platform.h
Platform.cpp