LLDB: lldb_private::TaggedASTDecl< D > Class Template Reference
lldb_private::TaggedASTDecl< D > Class Template Reference
#include <ClangASTImporter.h>
Public Member Functions
TaggedASTDecl ()
TaggedASTDecl (D *_decl)
bool IsValid () const
bool IsInvalid () const
D * operator-> () const
Public Attributes
D * decl
Detailed Description
template<class D>
class lldb_private::TaggedASTDecl< D >
Definition at line 485 of file ClangASTImporter.h.
Constructor & Destructor Documentation
TaggedASTDecl() [1/2]
template<class D> lldb_private::TaggedASTDecl< D >::TaggedASTDecl () inline
Definition at line 487 of file ClangASTImporter.h.
References decl.
Referenced by lldb_private::DeclFromParser< D >::DeclFromParser(), lldb_private::DeclFromParser< D >::DeclFromParser(), lldb_private::DeclFromUser< D >::DeclFromUser(), and lldb_private::DeclFromUser< D >::DeclFromUser().
TaggedASTDecl() [2/2]
template<class D> lldb_private::TaggedASTDecl< D >::TaggedASTDecl (D * _decl) inline
Definition at line 488 of file ClangASTImporter.h.
References decl.
Member Function Documentation
IsInvalid()
template<class D> bool lldb_private::TaggedASTDecl< D >::IsInvalid () const inline
Definition at line 490 of file ClangASTImporter.h.
References IsValid().
Referenced by ExtractBaseOffsets(), lldb_private::ClangASTSource::FindObjCPropertyAndIvarDeclsWithOrigin(), lldb_private::DeclFromUser< D >::Import(), ImportOffsetMap(), and lldb_private::ClangASTImporter::importRecordLayoutFromOrigin().
IsValid()
template<class D> bool lldb_private::TaggedASTDecl< D >::IsValid () const inline
Definition at line 489 of file ClangASTImporter.h.
References decl.
Referenced by lldb_private::ClangASTSource::FindObjCPropertyAndIvarDecls(), lldb_private::ClangASTSource::FindObjCPropertyAndIvarDeclsWithOrigin(), lldb_private::ClangASTImporter::importRecordLayoutFromOrigin(), and IsInvalid().
operator->()
template<class D> D * lldb_private::TaggedASTDecl< D >::operator-> () const inline
Definition at line 491 of file ClangASTImporter.h.
References decl.
Member Data Documentation
decl
template<class D> D* lldb_private::TaggedASTDecl< D >::decl
Definition at line 492 of file ClangASTImporter.h.
Referenced by ExtractBaseOffsets(), lldb_private::ClangASTSource::FindObjCPropertyAndIvarDecls(), lldb_private::ClangASTSource::FindObjCPropertyAndIvarDeclsWithOrigin(), lldb_private::DeclFromParser< D >::GetOrigin(), lldb_private::DeclFromUser< D >::Import(), ImportOffsetMap(), lldb_private::ClangASTImporter::importRecordLayoutFromOrigin(), IsValid(), operator->(), TaggedASTDecl(), and TaggedASTDecl().
The documentation for this class was generated from the following file:
ClangASTImporter.h