LLDB: SymbolVendorMacOSX Class Reference
SymbolVendorMacOSX Class Reference
#include <SymbolVendorMacOSX.h>
Public Member Functions
SymbolVendorMacOSX (const lldb::ModuleSP &module_sp)
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::SymbolVendor
SymbolVendor (const lldb::ModuleSP &module_sp)
void AddSymbolFileRepresentation (const lldb::ObjectFileSP &objfile_sp)
SymbolFile * GetSymbolFile ()
Public Member Functions inherited from lldb_private::ModuleChild
ModuleChild (const lldb::ModuleSP &module_sp)
Construct with owning module.
~ModuleChild ()
Destructor.
const ModuleChild & operator= (const ModuleChild &rhs)
Assignment operator.
lldb::ModuleSP GetModule () const
Get const accessor for the module pointer.
void SetModule (const lldb::ModuleSP &module_sp)
Set accessor for the module pointer.
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static lldb_private::SymbolVendor * CreateInstance (const lldb::ModuleSP &module_sp, lldb_private::Stream *feedback_strm)
Static Public Member Functions inherited from lldb_private::SymbolVendor
static SymbolVendor * FindPlugin (const lldb::ModuleSP &module_sp, Stream *feedback_strm)
Additional Inherited Members
Protected Attributes inherited from lldb_private::SymbolVendor
std::unique_ptr< SymbolFile > m_sym_file_up
Protected Attributes inherited from lldb_private::ModuleChild
lldb::ModuleWP m_module_wp
The Module that owns the object that inherits from this class.
Detailed Description
Definition at line 15 of file SymbolVendorMacOSX.h.
Constructor & Destructor Documentation
SymbolVendorMacOSX()
SymbolVendorMacOSX::SymbolVendorMacOSX (const lldb::ModuleSP & module_sp)
Definition at line 31 of file SymbolVendorMacOSX.cpp.
References lldb_private::SymbolVendor::SymbolVendor(), and SymbolVendorMacOSX().
Referenced by CreateInstance(), and SymbolVendorMacOSX().
Member Function Documentation
CreateInstance()
SymbolVendor * SymbolVendorMacOSX::CreateInstance (const lldb::ModuleSP & module_sp, lldb_private::Stream * feedback_strm) static
Definition at line 89 of file SymbolVendorMacOSX.cpp.
References lldb_private::SymbolVendor::AddSymbolFileRepresentation(), lldb_private::ObjectFile::eTypeObjectFile, lldb_private::ObjectFile::FindPlugin(), lldb_private::StructuredData::Dictionary::ForEach(), lldb_private::UUID::GetAsString(), lldb_private::Target::GetDefaultDebugFileSearchPaths(), lldb_private::ObjectFile::GetFileSpec(), lldb_private::FileSpec::GetPath(), lldb_private::PathMappingList::GetSize(), lldb_private::ModuleSpec::GetSourceMappingList(), lldb_private::ApplePropertyList::GetStructuredData(), lldb_private::ModuleSpec::GetUUID(), lldb_private::ApplePropertyList::GetValueAsString(), lldb_private::FileSystem::Instance(), lldb_private::PluginManager::LocateExecutableSymbolFile(), PATH_MAX, lldb_private::FileSpec::RemoveLastPathComponent(), SymbolVendorMacOSX(), UUIDsMatch(), and lldb_private::XMLDocument::XMLEnabled().
Referenced by Initialize(), and Terminate().
GetPluginDescriptionStatic()
llvm::StringRef SymbolVendorMacOSX::GetPluginDescriptionStatic () static
Definition at line 78 of file SymbolVendorMacOSX.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef SymbolVendorMacOSX::GetPluginName () inline override virtual
Reimplemented from lldb_private::SymbolVendor.
Definition at line 34 of file SymbolVendorMacOSX.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef SymbolVendorMacOSX::GetPluginNameStatic () inline static
Definition at line 22 of file SymbolVendorMacOSX.h.
Referenced by GetPluginName(), and Initialize().
Initialize()
void SymbolVendorMacOSX::Initialize () static
Definition at line 69 of file SymbolVendorMacOSX.cpp.
References CreateInstance(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Terminate()
void SymbolVendorMacOSX::Terminate () static
Definition at line 74 of file SymbolVendorMacOSX.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
The documentation for this class was generated from the following files:
SymbolVendorMacOSX.h
SymbolVendorMacOSX.cpp