LLDB: lldb_private::Process::ProcessEventData Class Reference
lldb_private::Process::ProcessEventData Class Reference
#include <Process.h>
Public Member Functions
ProcessEventData ()
ProcessEventData (const lldb::ProcessSP &process, lldb::StateType state)
~ProcessEventData () override
llvm::StringRef GetFlavor () const override
lldb::ProcessSP GetProcessSP () const
lldb::StateType GetState () const
bool GetRestarted () const
size_t GetNumRestartedReasons ()
const char * GetRestartedReasonAtIndex (size_t idx)
bool GetInterrupted () const
void Dump (Stream *s) const override
virtual bool ShouldStop (Event *event_ptr, bool &found_valid_stopinfo)
void DoOnRemoval (Event *event_ptr) override
Public Member Functions inherited from lldb_private::EventData
EventData ()
virtual ~EventData ()
virtual Log * GetLogChannel ()
Static Public Member Functions
static llvm::StringRef GetFlavorString ()
static const Process::ProcessEventData * GetEventDataFromEvent (const Event *event_ptr)
static lldb::ProcessSP GetProcessFromEvent (const Event *event_ptr)
static lldb::StateType GetStateFromEvent (const Event *event_ptr)
static bool GetRestartedFromEvent (const Event *event_ptr)
static size_t GetNumRestartedReasons (const Event *event_ptr)
static const char * GetRestartedReasonAtIndex (const Event *event_ptr, size_t idx)
static void AddRestartedReason (Event *event_ptr, const char *reason)
static void SetRestartedInEvent (Event *event_ptr, bool new_value)
static bool GetInterruptedFromEvent (const Event *event_ptr)
static void SetInterruptedInEvent (Event *event_ptr, bool new_value)
static bool SetUpdateStateOnRemoval (Event *event_ptr)
Private Member Functions
bool ForwardEventToPendingListeners (Event *event_ptr) override
This will be queried for a Broadcaster with a primary and some secondary listeners after the primary listener pulled the event from the event queue and ran its DoOnRemoval, right before the event is delivered.
void SetUpdateStateOnRemoval ()
void SetRestarted (bool new_value)
void SetInterrupted (bool new_value)
void AddRestartedReason (const char *reason)
ProcessEventData (const ProcessEventData &)=delete
const ProcessEventData & operator= (const ProcessEventData &)=delete
Private Attributes
lldb::ProcessWP m_process_wp
lldb::StateType m_state = lldb::eStateInvalid
std::vector< std::string > m_restarted_reasons
bool m_restarted = false
int m_update_state = 0
bool m_interrupted = false
Friends
class Process
Detailed Description
Definition at line 422 of file Process.h.
Constructor & Destructor Documentation
ProcessEventData() [1/3]
Process::ProcessEventData::ProcessEventData ()
Definition at line 4333 of file Process.cpp.
References lldb_private::EventData::EventData(), and m_process_wp.
Referenced by AddRestartedReason(), GetEventDataFromEvent(), GetInterruptedFromEvent(), GetNumRestartedReasons(), GetProcessFromEvent(), GetRestartedFromEvent(), GetRestartedReasonAtIndex(), GetStateFromEvent(), operator=(), ProcessEventData(), SetInterruptedInEvent(), SetRestartedInEvent(), and SetUpdateStateOnRemoval().
ProcessEventData() [2/3]
Process::ProcessEventData::ProcessEventData (const lldb::ProcessSP & process, lldb::StateType state)
Definition at line 4335 of file Process.cpp.
References lldb_private::EventData::EventData(), m_process_wp, and m_state.
~ProcessEventData()
Process::ProcessEventData::~ProcessEventData () override default
ProcessEventData() [3/3]
lldb_private::Process::ProcessEventData::ProcessEventData (const ProcessEventData &) private delete
References ProcessEventData().
Member Function Documentation
AddRestartedReason() [1/2]
void lldb_private::Process::ProcessEventData::AddRestartedReason (const char * reason) inline private
Definition at line 489 of file Process.h.
References m_restarted_reasons.
AddRestartedReason() [2/2]
void Process::ProcessEventData::AddRestartedReason (Event * event_ptr, const char * reason) static
Definition at line 4616 of file Process.cpp.
References AddRestartedReason(), lldb_private::EventData::Event, GetEventDataFromEvent(), and ProcessEventData().
Referenced by AddRestartedReason(), and lldb_private::StopInfoUnixSignal::DoShouldNotify().
DoOnRemoval()
void Process::ProcessEventData::DoOnRemoval (Event * event_ptr) override virtual
Reimplemented from lldb_private::EventData.
Definition at line 4467 of file Process.cpp.
References lldb_private::Process::eBroadcastBitStateChanged, lldb::eStateStopped, lldb_private::EventData::Event, GetRestarted(), GetRestartedFromEvent(), lldb_private::Event::GetType(), m_interrupted, m_process_wp, m_restarted, m_state, m_update_state, SetRestarted(), and ShouldStop().
Dump()
void Process::ProcessEventData::Dump (Stream * s) const override virtual
Reimplemented from lldb_private::EventData.
Definition at line 4539 of file Process.cpp.
References lldb_private::Process::GetState(), m_process_wp, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and lldb_private::StateAsCString().
ForwardEventToPendingListeners()
bool Process::ProcessEventData::ForwardEventToPendingListeners (Event * event_ptr) override private virtual
This will be queried for a Broadcaster with a primary and some secondary listeners after the primary listener pulled the event from the event queue and ran its DoOnRemoval, right before the event is delivered.
If it returns true, the event will also be forwarded to the secondary listeners, and if false, event propagation stops at the primary listener. Some broadcasters (particularly the Process broadcaster) fetch events on a private Listener, and then forward the event to the Public Listeners after some processing. The Process broadcaster does not want to forward to the secondary listeners at the private processing stage.
Reimplemented from lldb_private::EventData.
Definition at line 4456 of file Process.cpp.
References lldb_private::Process::eBroadcastBitStateChanged, lldb_private::EventData::Event, lldb_private::Event::GetType(), and m_update_state.
GetEventDataFromEvent()
const Process::ProcessEventData * Process::ProcessEventData::GetEventDataFromEvent (const Event * event_ptr) static
Definition at line 4552 of file Process.cpp.
References lldb_private::EventData::Event, lldb_private::EventData::EventData(), lldb_private::Event::GetData(), lldb_private::EventData::GetFlavor(), GetFlavorString(), and ProcessEventData().
Referenced by AddRestartedReason(), lldb::SBProcess::EventIsProcessEvent(), GetInterruptedFromEvent(), GetNumRestartedReasons(), GetProcessFromEvent(), GetRestartedFromEvent(), GetRestartedReasonAtIndex(), GetStateFromEvent(), lldb_private::Process::RunThreadPlan(), SetInterruptedInEvent(), SetRestartedInEvent(), and SetUpdateStateOnRemoval().
GetFlavor()
llvm::StringRef Process::ProcessEventData::GetFlavor () const override virtual
Implements lldb_private::EventData.
Definition at line 4348 of file Process.cpp.
References GetFlavorString().
GetFlavorString()
llvm::StringRef Process::ProcessEventData::GetFlavorString () static
Definition at line 4344 of file Process.cpp.
Referenced by GetEventDataFromEvent(), and GetFlavor().
GetInterrupted()
bool lldb_private::Process::ProcessEventData::GetInterrupted () const inline
Definition at line 448 of file Process.h.
References m_interrupted.
Referenced by GetInterruptedFromEvent().
GetInterruptedFromEvent()
bool Process::ProcessEventData::GetInterruptedFromEvent (const Event * event_ptr) static
Definition at line 4624 of file Process.cpp.
References lldb_private::EventData::Event, GetEventDataFromEvent(), GetInterrupted(), and ProcessEventData().
Referenced by lldb_private::ThreadPlanCallFunction::DoPlanExplainsStop(), lldb::SBProcess::GetInterruptedFromEvent(), HandleStoppedEvent(), lldb_private::Process::RunThreadPlan(), lldb_private::Process::ShouldBroadcastEvent(), and lldb_private::ThreadList::ShouldStop().
GetNumRestartedReasons() [1/2]
size_t lldb_private::Process::ProcessEventData::GetNumRestartedReasons () inline
Definition at line 440 of file Process.h.
References m_restarted_reasons.
Referenced by GetNumRestartedReasons(), lldb::SBProcess::GetNumRestartedReasonsFromEvent(), and lldb_private::Process::HandleProcessStateChangedEvent().
GetNumRestartedReasons() [2/2]
size_t Process::ProcessEventData::GetNumRestartedReasons (const Event * event_ptr) static
Definition at line 4596 of file Process.cpp.
References lldb_private::EventData::Event, GetEventDataFromEvent(), GetNumRestartedReasons(), and ProcessEventData().
GetProcessFromEvent()
ProcessSP Process::ProcessEventData::GetProcessFromEvent (const Event * event_ptr) static
Definition at line 4563 of file Process.cpp.
References lldb_private::EventData::Event, GetEventDataFromEvent(), GetProcessSP(), and ProcessEventData().
Referenced by lldb::SBProcess::GetProcessFromEvent(), lldb_private::Debugger::HandleProcessEvent(), and lldb_private::Process::HandleProcessStateChangedEvent().
GetProcessSP()
lldb::ProcessSP lldb_private::Process::ProcessEventData::GetProcessSP () const inline
Definition at line 435 of file Process.h.
References m_process_wp.
Referenced by GetProcessFromEvent(), and lldb_private::Process::RunThreadPlan().
GetRestarted()
bool lldb_private::Process::ProcessEventData::GetRestarted () const inline
Definition at line 438 of file Process.h.
References m_restarted.
Referenced by DoOnRemoval(), and GetRestartedFromEvent().
GetRestartedFromEvent()
bool Process::ProcessEventData::GetRestartedFromEvent (const Event * event_ptr) static
Definition at line 4579 of file Process.cpp.
References lldb_private::EventData::Event, GetEventDataFromEvent(), GetRestarted(), and ProcessEventData().
Referenced by DoOnRemoval(), lldb::SBProcess::GetRestartedFromEvent(), lldb_private::ThreadPlanSingleThreadTimeout::HandleEvent(), lldb_private::Process::HandlePrivateEvent(), lldb_private::Process::HandleProcessStateChangedEvent(), lldb_private::Process::RunThreadPlan(), lldb_private::Process::ShouldBroadcastEvent(), lldb_private::Thread::ShouldStop(), and lldb_private::Process::WaitForProcessToStop().
GetRestartedReasonAtIndex() [1/2]
const char * Process::ProcessEventData::GetRestartedReasonAtIndex (const Event * event_ptr, size_t idx) static
Definition at line 4606 of file Process.cpp.
References lldb_private::EventData::Event, GetEventDataFromEvent(), GetRestartedReasonAtIndex(), and ProcessEventData().
GetRestartedReasonAtIndex() [2/2]
const char * lldb_private::Process::ProcessEventData::GetRestartedReasonAtIndex (size_t idx) inline
Definition at line 442 of file Process.h.
References m_restarted_reasons.
Referenced by GetRestartedReasonAtIndex(), lldb::SBProcess::GetRestartedReasonAtIndexFromEvent(), and lldb_private::Process::HandleProcessStateChangedEvent().
GetState()
lldb::StateType lldb_private::Process::ProcessEventData::GetState () const inline
Definition at line 437 of file Process.h.
References m_state.
Referenced by GetStateFromEvent().
GetStateFromEvent()
StateType Process::ProcessEventData::GetStateFromEvent (const Event * event_ptr) static
Definition at line 4571 of file Process.cpp.
References lldb::eStateInvalid, lldb_private::EventData::Event, GetEventDataFromEvent(), GetState(), and ProcessEventData().
Referenced by lldb_private::Process::GetNextEvent(), lldb_private::Process::GetStateChangedEvents(), lldb_private::Process::GetStateChangedEventsPrivate(), lldb::SBProcess::GetStateFromEvent(), lldb_private::Process::HandlePrivateEvent(), lldb_private::Debugger::HandleProcessEvent(), lldb_private::Process::HandleProcessStateChangedEvent(), lldb_private::ThreadPlanSingleThreadTimeout::IsTimeoutAsyncInterrupt(), lldb_private::Process::PeekAtStateChangedEvents(), lldb_private::Process::AttachCompletionHandler::PerformAction(), lldb_private::Process::RunPrivateStateThread(), lldb_private::Process::RunThreadPlan(), and lldb_private::Process::ShouldBroadcastEvent().
operator=()
const ProcessEventData & lldb_private::Process::ProcessEventData::operator= (const ProcessEventData &) private delete
References ProcessEventData().
SetInterrupted()
void lldb_private::Process::ProcessEventData::SetInterrupted (bool new_value) inline private
Definition at line 487 of file Process.h.
References m_interrupted.
Referenced by SetInterruptedInEvent().
SetInterruptedInEvent()
void Process::ProcessEventData::SetInterruptedInEvent (Event * event_ptr, bool new_value) static
Definition at line 4633 of file Process.cpp.
References lldb_private::EventData::Event, GetEventDataFromEvent(), ProcessEventData(), and SetInterrupted().
Referenced by lldb_private::Process::RunPrivateStateThread().
SetRestarted()
void lldb_private::Process::ProcessEventData::SetRestarted (bool new_value) inline private
Definition at line 485 of file Process.h.
References m_restarted.
Referenced by DoOnRemoval(), SetRestartedInEvent(), and ShouldStop().
SetRestartedInEvent()
void Process::ProcessEventData::SetRestartedInEvent (Event * event_ptr, bool new_value) static
Definition at line 4587 of file Process.cpp.
References lldb_private::EventData::Event, GetEventDataFromEvent(), ProcessEventData(), and SetRestarted().
Referenced by lldb_private::Process::ShouldBroadcastEvent().
SetUpdateStateOnRemoval() [1/2]
void lldb_private::Process::ProcessEventData::SetUpdateStateOnRemoval () inline private
Definition at line 483 of file Process.h.
References m_update_state.
Referenced by lldb_private::Process::HandlePrivateEvent().
SetUpdateStateOnRemoval() [2/2]
bool Process::ProcessEventData::SetUpdateStateOnRemoval (Event * event_ptr) static
Definition at line 4641 of file Process.cpp.
References lldb_private::EventData::Event, GetEventDataFromEvent(), ProcessEventData(), and SetUpdateStateOnRemoval().
Referenced by SetUpdateStateOnRemoval().
ShouldStop()
bool Process::ProcessEventData::ShouldStop (Event * event_ptr, bool & found_valid_stopinfo) virtual
Definition at line 4352 of file Process.cpp.
References lldb::eStateSuspended, lldb_private::EventData::Event, lldb_private::GetLog(), lldb_private::ThreadList::GetSize(), lldb_private::ThreadList::GetThreadAtIndex(), LLDB_LOG, LLDB_LOGF, m_process_wp, lldb_private::Process, SetRestarted(), lldb_private::Step, and lldb_private::Process::ThreadList.
Referenced by DoOnRemoval().
Friends And Related Symbol Documentation
Process
friend class Process friend
Definition at line 423 of file Process.h.
References Process.
Referenced by Process.
Member Data Documentation
m_interrupted
bool lldb_private::Process::ProcessEventData::m_interrupted = false private
Definition at line 499 of file Process.h.
Referenced by DoOnRemoval(), GetInterrupted(), and SetInterrupted().
m_process_wp
lldb::ProcessWP lldb_private::Process::ProcessEventData::m_process_wp private
Definition at line 493 of file Process.h.
Referenced by DoOnRemoval(), Dump(), GetProcessSP(), ProcessEventData(), ProcessEventData(), and ShouldStop().
m_restarted
bool lldb_private::Process::ProcessEventData::m_restarted = false private
Definition at line 496 of file Process.h.
Referenced by DoOnRemoval(), GetRestarted(), and SetRestarted().
m_restarted_reasons
std::vector<std::string> lldb_private::Process::ProcessEventData::m_restarted_reasons private
Definition at line 495 of file Process.h.
Referenced by AddRestartedReason(), GetNumRestartedReasons(), and GetRestartedReasonAtIndex().
m_state
lldb::StateType lldb_private::Process::ProcessEventData::m_state = lldb::eStateInvalid private
Definition at line 494 of file Process.h.
Referenced by DoOnRemoval(), GetState(), and ProcessEventData().
m_update_state
int lldb_private::Process::ProcessEventData::m_update_state = 0 private
Definition at line 498 of file Process.h.
Referenced by DoOnRemoval(), ForwardEventToPendingListeners(), and SetUpdateStateOnRemoval().
The documentation for this class was generated from the following files:
Process.h
Process.cpp