LLDB: EntityRegister Class Reference
EntityRegister Class Reference
Public Member Functions
EntityRegister (const RegisterInfo &register_info)
void Materialize (lldb::StackFrameSP &frame_sp, IRMemoryMap &map, lldb::addr_t process_address, Status &err) override
void Dematerialize (lldb::StackFrameSP &frame_sp, IRMemoryMap &map, lldb::addr_t process_address, lldb::addr_t frame_top, lldb::addr_t frame_bottom, Status &err) override
void DumpToLog (IRMemoryMap &map, lldb::addr_t process_address, Log *log) override
void Wipe (IRMemoryMap &map, lldb::addr_t process_address) override
Public Member Functions inherited from lldb_private::Materializer::Entity
Entity ()=default
virtual ~Entity ()=default
uint32_t GetAlignment ()
uint32_t GetSize ()
uint32_t GetOffset ()
void SetOffset (uint32_t offset)
Private Attributes
RegisterInfo m_register_info
lldb::DataBufferSP m_register_contents
Additional Inherited Members
Protected Attributes inherited from lldb_private::Materializer::Entity
uint32_t m_alignment = 1
uint32_t m_size = 0
uint32_t m_offset = 0
Detailed Description
Definition at line 1341 of file Materializer.cpp.
Constructor & Destructor Documentation
EntityRegister()
EntityRegister::EntityRegister (const RegisterInfo & register_info) inline
Definition at line 1343 of file Materializer.cpp.
References lldb_private::Materializer::Entity::Entity(), lldb_private::Materializer::Entity::m_alignment, m_register_info, and lldb_private::Materializer::Entity::m_size.
Member Function Documentation
Dematerialize()
void EntityRegister::Dematerialize (lldb::StackFrameSP & frame_sp, IRMemoryMap & map, lldb::addr_t process_address, lldb::addr_t frame_top, lldb::addr_t frame_bottom, Status & err) inline override virtual
Implements lldb_private::Materializer::Entity.
Definition at line 1409 of file Materializer.cpp.
References lldb_private::Status::AsCString(), lldb_private::Expressions, lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataExtractor::GetByteOrder(), lldb_private::DataExtractor::GetByteSize(), lldb_private::DataExtractor::GetData(), lldb_private::DataExtractor::GetDataStart(), lldb_private::GetLog(), lldb_private::IRMemoryMap::GetMemoryData(), LLDB_LOGF, lldb_private::Materializer::Entity::m_offset, m_register_contents, m_register_info, and lldb_private::Status::Success().
DumpToLog()
void EntityRegister::DumpToLog (IRMemoryMap & map, lldb::addr_t process_address, Log * log) inline override virtual
Implements lldb_private::Materializer::Entity.
Definition at line 1467 of file Materializer.cpp.
References lldb_private::DumpHexBytes(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::DataBufferHeap::GetByteSize(), lldb_private::StreamString::GetString(), lldb_private::Materializer::Entity::m_offset, m_register_info, lldb_private::Materializer::Entity::m_size, lldb_private::Stream::Printf(), lldb_private::Stream::PutChar(), lldb_private::Log::PutString(), lldb_private::IRMemoryMap::ReadMemory(), and lldb_private::Status::Success().
Materialize()
void EntityRegister::Materialize (lldb::StackFrameSP & frame_sp, IRMemoryMap & map, lldb::addr_t process_address, Status & err) inline override virtual
Implements lldb_private::Materializer::Entity.
Definition at line 1350 of file Materializer.cpp.
References lldb_private::Status::AsCString(), lldb_private::Expressions, lldb_private::Status::FromErrorStringWithFormat(), lldb_private::RegisterValue::GetAsMemoryData(), lldb_private::IRMemoryMap::GetByteOrder(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::DataBufferHeap::GetByteSize(), lldb_private::RegisterValue::GetByteSize(), lldb_private::GetLog(), LLDB_LOGF, lldb_private::Materializer::Entity::m_offset, m_register_contents, m_register_info, lldb_private::Status::Success(), and lldb_private::IRMemoryMap::WriteMemory().
Wipe()
void EntityRegister::Wipe (IRMemoryMap & map, lldb::addr_t process_address) inline override virtual
Implements lldb_private::Materializer::Entity.
Definition at line 1498 of file Materializer.cpp.
Member Data Documentation
m_register_contents
lldb::DataBufferSP EntityRegister::m_register_contents private
Definition at line 1502 of file Materializer.cpp.
Referenced by Dematerialize(), and Materialize().
m_register_info
RegisterInfo EntityRegister::m_register_info private
Definition at line 1501 of file Materializer.cpp.
Referenced by Dematerialize(), DumpToLog(), EntityRegister(), and Materialize().
The documentation for this class was generated from the following file:
Materializer.cpp