LLDB: OptionGroupReadMemory Class Reference
OptionGroupReadMemory Class Reference
Public Member Functions
OptionGroupReadMemory ()
~OptionGroupReadMemory () override=default
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext *execution_context) override
void OptionParsingStarting (ExecutionContext *execution_context) override
Status FinalizeSettings (Target *target, OptionGroupFormat &format_options)
bool AnyOptionWasSet () const
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Public Attributes
OptionValueUInt64 m_num_per_line
bool m_output_as_binary = false
OptionValueString m_view_as_type
bool m_force = false
OptionValueUInt64 m_offset
OptionValueLanguage m_language_for_type
Detailed Description
Definition at line 50 of file CommandObjectMemory.cpp.
Constructor & Destructor Documentation
OptionGroupReadMemory()
OptionGroupReadMemory::OptionGroupReadMemory () inline
Definition at line 52 of file CommandObjectMemory.cpp.
References lldb::eLanguageTypeUnknown, m_language_for_type, m_num_per_line, and m_offset.
~OptionGroupReadMemory()
OptionGroupReadMemory::~OptionGroupReadMemory () override default
Member Function Documentation
AnyOptionWasSet()
bool OptionGroupReadMemory::AnyOptionWasSet () const inline
Definition at line 271 of file CommandObjectMemory.cpp.
References m_language_for_type, m_num_per_line, m_offset, m_output_as_binary, and m_view_as_type.
FinalizeSettings()
Status OptionGroupReadMemory::FinalizeSettings (Target * target, OptionGroupFormat & format_options) inline
Definition at line 111 of file CommandObjectMemory.cpp.
References lldb::eFormatAddressInfo, lldb::eFormatBinary, lldb::eFormatBoolean, lldb::eFormatBytes, lldb::eFormatBytesWithASCII, lldb::eFormatChar, lldb::eFormatCharArray, lldb::eFormatCharPrintable, lldb::eFormatComplex, lldb::eFormatComplexInteger, lldb::eFormatCString, lldb::eFormatDecimal, lldb::eFormatEnum, lldb::eFormatFloat, lldb::eFormatFloat128, lldb::eFormatHex, lldb::eFormatHexFloat, lldb::eFormatInstruction, lldb::eFormatOctal, lldb::eFormatPointer, lldb::eFormatUnicode16, lldb::eFormatUnicode32, lldb::eFormatUnicode8, lldb::eFormatUnsigned, lldb::eFormatVectorOfChar, lldb::eFormatVectorOfFloat16, lldb::eFormatVectorOfFloat32, lldb::eFormatVectorOfFloat64, lldb::eFormatVectorOfSInt16, lldb::eFormatVectorOfSInt32, lldb::eFormatVectorOfSInt64, lldb::eFormatVectorOfSInt8, lldb::eFormatVectorOfUInt128, lldb::eFormatVectorOfUInt16, lldb::eFormatVectorOfUInt32, lldb::eFormatVectorOfUInt64, lldb::eFormatVectorOfUInt8, error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::ArchSpec::GetAddressByteSize(), lldb_private::Target::GetArchitecture(), lldb_private::OptionGroupFormat::GetByteSizeValue(), lldb_private::OptionGroupFormat::GetCountValue(), lldb_private::OptionValueUInt64::GetCurrentValue(), lldb_private::OptionGroupFormat::GetFormat(), lldb_private::ArchSpec::GetMaximumOpcodeByteSize(), m_num_per_line, and lldb_private::OptionValue::OptionWasSet().
GetDefinitions()
llvm::ArrayRef< OptionDefinition > OptionGroupReadMemory::GetDefinitions () inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 58 of file CommandObjectMemory.cpp.
OptionParsingStarting()
void OptionGroupReadMemory::OptionParsingStarting (ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 102 of file CommandObjectMemory.cpp.
References m_force, m_language_for_type, m_num_per_line, m_offset, m_output_as_binary, and m_view_as_type.
SetOptionValue()
Status OptionGroupReadMemory::SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 62 of file CommandObjectMemory.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormat(), m_force, m_language_for_type, m_num_per_line, m_offset, m_output_as_binary, and m_view_as_type.
Member Data Documentation
m_force
bool OptionGroupReadMemory::m_force = false
Definition at line 280 of file CommandObjectMemory.cpp.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_language_for_type
OptionValueLanguage OptionGroupReadMemory::m_language_for_type
Definition at line 282 of file CommandObjectMemory.cpp.
Referenced by AnyOptionWasSet(), OptionGroupReadMemory(), OptionParsingStarting(), and SetOptionValue().
m_num_per_line
OptionValueUInt64 OptionGroupReadMemory::m_num_per_line
Definition at line 277 of file CommandObjectMemory.cpp.
Referenced by AnyOptionWasSet(), FinalizeSettings(), OptionGroupReadMemory(), OptionParsingStarting(), and SetOptionValue().
m_offset
OptionValueUInt64 OptionGroupReadMemory::m_offset
Definition at line 281 of file CommandObjectMemory.cpp.
Referenced by AnyOptionWasSet(), OptionGroupReadMemory(), OptionParsingStarting(), and SetOptionValue().
m_output_as_binary
bool OptionGroupReadMemory::m_output_as_binary = false
Definition at line 278 of file CommandObjectMemory.cpp.
Referenced by AnyOptionWasSet(), OptionParsingStarting(), and SetOptionValue().
m_view_as_type
OptionValueString OptionGroupReadMemory::m_view_as_type
Definition at line 279 of file CommandObjectMemory.cpp.
Referenced by AnyOptionWasSet(), OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following file:
CommandObjectMemory.cpp