LLDB: RegisterInfoPOSIX_riscv32 Class Reference
RegisterInfoPOSIX_riscv32 Class Reference
#include <RegisterInfoPOSIX_riscv32.h>
Classes
struct FPR
struct GPR
Public Types
enum { eRegsetMaskDefault = 0 , eRegsetMaskFP = 1 , eRegsetMaskAll = -1 }
Public Member Functions
RegisterInfoPOSIX_riscv32 (const lldb_private::ArchSpec &target_arch, lldb_private::Flags flags)
size_t GetGPRSize () const override
size_t GetFPRSize () const override
const lldb_private::RegisterInfo * GetRegisterInfo () const override
uint32_t GetRegisterCount () const override
const lldb_private::RegisterSet * GetRegisterSet (size_t reg_set) const override
size_t GetRegisterSetCount () const override
size_t GetRegisterSetFromRegisterIndex (uint32_t reg_index) const override
bool IsFPPresent () const
Public Member Functions inherited from lldb_private::RegisterInfoAndSetInterface
RegisterInfoAndSetInterface (const lldb_private::ArchSpec &target_arch)
Public Member Functions inherited from lldb_private::RegisterInfoInterface
RegisterInfoInterface (const lldb_private::ArchSpec &target_arch)
virtual ~RegisterInfoInterface ()=default
virtual uint32_t GetUserRegisterCount () const
const lldb_private::ArchSpec & GetTargetArchitecture () const
Static Public Member Functions
static const lldb_private::RegisterInfo * GetRegisterInfoPtr (const lldb_private::ArchSpec &target_arch)
static uint32_t GetRegisterInfoCount (const lldb_private::ArchSpec &target_arch)
Private Attributes
const lldb_private::RegisterInfo * m_register_info_p
uint32_t m_register_info_count
lldb_private::Flags m_opt_regsets
Detailed Description
Definition at line 19 of file RegisterInfoPOSIX_riscv32.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
eRegsetMaskDefault
eRegsetMaskFP
eRegsetMaskAll
Definition at line 29 of file RegisterInfoPOSIX_riscv32.h.
Constructor & Destructor Documentation
RegisterInfoPOSIX_riscv32()
RegisterInfoPOSIX_riscv32::RegisterInfoPOSIX_riscv32 (const lldb_private::ArchSpec & target_arch, lldb_private::Flags flags)
Definition at line 99 of file RegisterInfoPOSIX_riscv32.cpp.
References GetRegisterInfoCount(), GetRegisterInfoPtr(), m_opt_regsets, m_register_info_count, m_register_info_p, and lldb_private::RegisterInfoAndSetInterface::RegisterInfoAndSetInterface().
Member Function Documentation
GetFPRSize()
size_t RegisterInfoPOSIX_riscv32::GetFPRSize () const override virtual
Implements lldb_private::RegisterInfoAndSetInterface.
Definition at line 114 of file RegisterInfoPOSIX_riscv32.cpp.
GetGPRSize()
size_t RegisterInfoPOSIX_riscv32::GetGPRSize () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 110 of file RegisterInfoPOSIX_riscv32.cpp.
GetRegisterCount()
uint32_t RegisterInfoPOSIX_riscv32::GetRegisterCount () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 106 of file RegisterInfoPOSIX_riscv32.cpp.
References m_register_info_count.
GetRegisterInfo()
const lldb_private::RegisterInfo * RegisterInfoPOSIX_riscv32::GetRegisterInfo () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 119 of file RegisterInfoPOSIX_riscv32.cpp.
References m_register_info_p.
GetRegisterInfoCount()
uint32_t RegisterInfoPOSIX_riscv32::GetRegisterInfoCount (const lldb_private::ArchSpec & target_arch) static
Definition at line 39 of file RegisterInfoPOSIX_riscv32.cpp.
References lldb_private::ArchSpec::GetMachine().
Referenced by RegisterInfoPOSIX_riscv32().
GetRegisterInfoPtr()
const lldb_private::RegisterInfo * RegisterInfoPOSIX_riscv32::GetRegisterInfoPtr (const lldb_private::ArchSpec & target_arch) static
Definition at line 28 of file RegisterInfoPOSIX_riscv32.cpp.
References lldb_private::ArchSpec::GetMachine().
Referenced by RegisterInfoPOSIX_riscv32().
GetRegisterSet()
const lldb_private::RegisterSet * RegisterInfoPOSIX_riscv32::GetRegisterSet (size_t reg_set) const override virtual
Implements lldb_private::RegisterInfoAndSetInterface.
Definition at line 138 of file RegisterInfoPOSIX_riscv32.cpp.
References g_reg_sets_riscv32, and GetRegisterSetCount().
GetRegisterSetCount()
size_t RegisterInfoPOSIX_riscv32::GetRegisterSetCount () const override virtual
Implements lldb_private::RegisterInfoAndSetInterface.
Definition at line 123 of file RegisterInfoPOSIX_riscv32.cpp.
References k_num_register_sets.
Referenced by GetRegisterSet().
GetRegisterSetFromRegisterIndex()
size_t RegisterInfoPOSIX_riscv32::GetRegisterSetFromRegisterIndex (uint32_t reg_index) const override virtual
Implements lldb_private::RegisterInfoAndSetInterface.
Definition at line 127 of file RegisterInfoPOSIX_riscv32.cpp.
References eRegsetMaskDefault, eRegsetMaskFP, fpr_first_riscv, fpr_last_riscv, gpr_first_riscv, gpr_last_riscv, and LLDB_INVALID_REGNUM.
IsFPPresent()
bool RegisterInfoPOSIX_riscv32::IsFPPresent () const inline
Definition at line 63 of file RegisterInfoPOSIX_riscv32.h.
References eRegsetMaskFP, and m_opt_regsets.
Member Data Documentation
m_opt_regsets
lldb_private::Flags RegisterInfoPOSIX_riscv32::m_opt_regsets private
Definition at line 68 of file RegisterInfoPOSIX_riscv32.h.
Referenced by IsFPPresent(), and RegisterInfoPOSIX_riscv32().
m_register_info_count
uint32_t RegisterInfoPOSIX_riscv32::m_register_info_count private
Definition at line 67 of file RegisterInfoPOSIX_riscv32.h.
Referenced by GetRegisterCount(), and RegisterInfoPOSIX_riscv32().
m_register_info_p
const lldb_private::RegisterInfo* RegisterInfoPOSIX_riscv32::m_register_info_p private
Definition at line 66 of file RegisterInfoPOSIX_riscv32.h.
Referenced by GetRegisterInfo(), and RegisterInfoPOSIX_riscv32().
The documentation for this class was generated from the following files:
RegisterInfoPOSIX_riscv32.h
RegisterInfoPOSIX_riscv32.cpp