LLDB: lldb_private::StringList Class Reference
lldb_private::StringList Class Reference
#include <StringList.h>
Public Types
typedef collection::iterator iterator
typedef collection::const_iterator const_iterator
Public Member Functions
StringList ()
StringList (const char *str)
StringList (const char **strv, int strc)
virtual ~StringList ()
void AppendString (const std::string &s)
void AppendString (std::string &&s)
void AppendString (const char *str)
void AppendString (const char *str, size_t str_len)
void AppendString (llvm::StringRef str)
void AppendString (const llvm::Twine &str)
void AppendList (const char **strv, int strc)
void AppendList (const StringList &strings)
size_t GetSize () const
void SetSize (size_t n)
size_t GetMaxStringLength () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
std::string & operator[] (size_t idx)
const std::string & operator[] (size_t idx) const
void PopBack ()
const char * GetStringAtIndex (size_t idx) const
void Join (const char *separator, Stream &strm)
void Clear ()
std::string LongestCommonPrefix ()
void InsertStringAtIndex (size_t idx, const std::string &str)
void InsertStringAtIndex (size_t idx, std::string &&str)
void InsertStringAtIndex (size_t id, const char *str)
void DeleteStringAtIndex (size_t id)
void RemoveBlankLines ()
size_t SplitIntoLines (const std::string &lines)
size_t SplitIntoLines (const char *lines, size_t len)
std::string CopyList (const char *item_preamble=nullptr, const char *items_sep="\n") const
StringList & operator<< (const char *str)
StringList & operator<< (const std::string &s)
StringList & operator<< (const StringList &strings)
StringList & operator= (const std::vector< std::string > &rhs)
virtual void LogDump (Log *log, const char *name=nullptr)
Static Public Member Functions
template<typename T>
static void LogDump (Log *log, T s_iterable, const char *name=nullptr)
Private Types
typedef std::vector< std::string > collection
Private Attributes
collection m_strings
Detailed Description
Definition at line 26 of file StringList.h.
Member Typedef Documentation
collection
typedef std::vector<std::string> lldb_private::StringList::collection private
Definition at line 27 of file StringList.h.
const_iterator
typedef collection::const_iterator lldb_private::StringList::const_iterator
Definition at line 61 of file StringList.h.
iterator
typedef collection::iterator lldb_private::StringList::iterator
Definition at line 60 of file StringList.h.
Constructor & Destructor Documentation
StringList() [1/3]
StringList::StringList ()
Definition at line 22 of file StringList.cpp.
References m_strings.
Referenced by AppendList(), LogDump(), operator<<(), operator<<(), operator<<(), operator=(), and ~StringList().
StringList() [2/3]
StringList::StringList (const char * str) explicit
Definition at line 24 of file StringList.cpp.
References m_strings.
StringList() [3/3]
StringList::StringList (const char ** strv, int strc)
Definition at line 29 of file StringList.cpp.
References m_strings.
~StringList()
StringList::~StringList () virtual default
References StringList().
Member Function Documentation
AppendList() [1/2]
void StringList::AppendList (const char ** strv, int strc)
Definition at line 62 of file StringList.cpp.
References m_strings.
Referenced by lldb_private::CommandInterpreter::GetCommandSP(), and operator<<().
AppendList() [2/2]
void StringList::AppendList (const StringList & strings)
Definition at line 69 of file StringList.cpp.
References begin(), end(), GetSize(), m_strings, and StringList().
AppendString() [1/6]
void StringList::AppendString (const char * str)
Definition at line 38 of file StringList.cpp.
References m_strings.
AppendString() [2/6]
void StringList::AppendString (const char * str, size_t str_len)
Definition at line 49 of file StringList.cpp.
References m_strings.
AppendString() [3/6]
void StringList::AppendString (const llvm::Twine & str)
Definition at line 58 of file StringList.cpp.
References m_strings.
AppendString() [4/6]
void StringList::AppendString (const std::string & s)
Definition at line 43 of file StringList.cpp.
References m_strings.
Referenced by AddMatches(), lldb_private::AddNamesMatchingPartialString(), lldb_private::Editline::BreakLineCommand(), lldb_private::CommandInterpreter::FindCommandsForApropos(), lldb_private::CommandInterpreter::GetAliasCommandObject(), lldb_private::CommandInterpreter::GetCommandSP(), lldb_private::CompletionResult::GetDescriptions(), lldb_private::Editline::GetInputAsStringList(), lldb::SBStructuredData::GetKeys(), lldb_private::IOHandlerEditline::GetLines(), lldb_private::CompletionResult::GetMatches(), lldb_private::CommandObjectMultiword::GetSubcommandSP(), lldb_private::CommandInterpreter::GetUserCommandObject(), lldb_private::ArchSpec::ListSupportedArchNames(), lldb_private::Editline::NextLineCommand(), operator<<(), and operator<<().
AppendString() [5/6]
void StringList::AppendString (llvm::StringRef str)
Definition at line 54 of file StringList.cpp.
References m_strings.
AppendString() [6/6]
void StringList::AppendString (std::string && s)
Definition at line 45 of file StringList.cpp.
References m_strings.
begin() [1/2]
iterator lldb_private::StringList::begin () inline
Definition at line 63 of file StringList.h.
References m_strings.
Referenced by AppendList(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qPathComplete().
begin() [2/2]
const_iterator lldb_private::StringList::begin () const inline
Definition at line 65 of file StringList.h.
References m_strings.
Clear()
void StringList::Clear ()
Definition at line 105 of file StringList.cpp.
References m_strings.
Referenced by lldb_private::CommandObjectHelp::DoExecute(), lldb_private::CompletionResult::GetDescriptions(), lldb_private::CompletionResult::GetMatches(), and lldb_private::CommandInterpreter::ResolveCommandImpl().
CopyList()
std::string StringList::CopyList (const char * item_preamble = nullptr, const char * items_sep = "\n") const
Definition at line 198 of file StringList.cpp.
References GetSize(), lldb_private::StreamString::GetString(), and GetStringAtIndex().
Referenced by CommandObjectTypeSummaryAdd::IOHandlerInputComplete(), lldb_private::REPL::IOHandlerIsInputComplete(), and lldb_private::IOHandlerEditline::Run().
DeleteStringAtIndex()
void StringList::DeleteStringAtIndex (size_t id)
Definition at line 147 of file StringList.cpp.
References m_strings.
Referenced by lldb_private::CommandObjectMultiword::HandleCompletion(), lldb_private::CommandInterpreter::HandleCompletionMatches(), IOHandlerLuaInterpreter::IOHandlerIsInputComplete(), and RemoveBlankLines().
end() [1/2]
iterator lldb_private::StringList::end () inline
Definition at line 64 of file StringList.h.
References m_strings.
Referenced by AppendList(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qPathComplete(), and SplitIntoLines().
end() [2/2]
const_iterator lldb_private::StringList::end () const inline
Definition at line 66 of file StringList.h.
References m_strings.
GetMaxStringLength()
size_t StringList::GetMaxStringLength () const
Definition at line 76 of file StringList.cpp.
References m_strings.
Referenced by lldb_private::CommandObjectApropos::DoExecute().
GetSize()
size_t StringList::GetSize () const
Definition at line 74 of file StringList.cpp.
References m_strings.
Referenced by lldb_private::CompletionRequest::AddCompletions(), AppendList(), lldb_private::BreakpointOptions::BreakpointOptionsCallbackFunction(), lldb_private::REPL::CalculateActualIndentation(), lldb_private::CommandCompletions::CompleteModifiableCmdPathArgs(), CopyList(), lldb_private::CommandObjectApropos::DoExecute(), lldb_private::CommandObjectHelp::DoExecute(), lldb_private::CommandObjectMultiword::Execute(), lldb_private::CommandInterpreter::GetAliasFullName(), lldb_private::CommandInterpreter::GetCommandNamesMatchingPartialString(), lldb_private::CommandInterpreter::GetCommandSP(), lldb_private::IOHandlerEditline::GetLines(), lldb_private::CommandInterpreter::HandleCommands(), lldb_private::CommandObjectMultiword::HandleCompletion(), lldb_private::CommandInterpreter::HandleCompletionMatches(), lldb::SBCommandInterpreter::HandleCompletionWithDescriptions(), lldb_private::REPL::IOHandlerComplete(), lldb_private::REPL::IOHandlerFixIndentation(), CommandObjectCommandsScriptAdd::IOHandlerInputComplete(), CommandObjectTypeSummaryAdd::IOHandlerInputComplete(), CommandObjectTypeSynthAdd::IOHandlerInputComplete(), IOHandlerLuaInterpreter::IOHandlerIsInputComplete(), lldb_private::IOHandlerDelegateMultiline::IOHandlerIsInputComplete(), lldb_private::REPL::IOHandlerIsInputComplete(), Join(), RemoveBlankLines(), lldb_private::CommandInterpreter::ResolveCommandImpl(), and lldb_private::CommandCompletions::SettingsNames().
GetStringAtIndex()
const char * StringList::GetStringAtIndex (size_t idx) const
Definition at line 86 of file StringList.cpp.
References m_strings.
Referenced by lldb_private::CompletionRequest::AddCompletions(), CopyList(), lldb_private::CommandObjectApropos::DoExecute(), lldb_private::CommandObjectHelp::DoExecute(), lldb_private::Editline::FixIndentationCommand(), lldb_private::CommandInterpreter::GetAliasFullName(), lldb_private::CommandInterpreter::GetCommandSP(), lldb_private::CommandObjectMultiword::GetSubcommandSP(), lldb_private::CommandInterpreter::HandleCommands(), lldb_private::CommandObjectMultiword::HandleCompletion(), lldb_private::CommandInterpreter::HandleCompletionMatches(), lldb_private::REPL::IOHandlerComplete(), IOHandlerLuaInterpreter::IOHandlerIsInputComplete(), lldb_private::REPL::IOHandlerIsInputComplete(), Join(), and lldb_private::CommandInterpreter::ResolveCommandImpl().
InsertStringAtIndex() [1/3]
void StringList::InsertStringAtIndex (size_t id, const char * str)
Definition at line 124 of file StringList.cpp.
References m_strings.
InsertStringAtIndex() [2/3]
void StringList::InsertStringAtIndex (size_t idx, const std::string & str)
Definition at line 133 of file StringList.cpp.
References m_strings.
Referenced by lldb::SBCommandInterpreter::HandleCompletionWithDescriptions().
InsertStringAtIndex() [3/3]
void StringList::InsertStringAtIndex (size_t idx, std::string && str)
Definition at line 140 of file StringList.cpp.
References m_strings.
Join()
void StringList::Join (const char * separator, Stream & strm)
Definition at line 92 of file StringList.cpp.
References GetSize(), GetStringAtIndex(), and lldb_private::Stream::PutCString().
Referenced by lldb_private::arch_helper(), and IOHandlerLuaInterpreter::IOHandlerIsInputComplete().
LogDump() [1/2]
void StringList::LogDump (Log * log, const char * name = nullptr) virtual
Definition at line 232 of file StringList.cpp.
References lldb_private::StreamString::GetData(), lldb_private::Stream::Indent(), LLDB_LOGV, m_strings, and lldb_private::Stream::Printf().
LogDump() [2/2]
template<typename T> void lldb_private::StringList::LogDump (Log * log, T s_iterable, const char * name = nullptr) inline static
Definition at line 121 of file StringList.h.
References l, and StringList().
LongestCommonPrefix()
std::string StringList::LongestCommonPrefix ()
Definition at line 107 of file StringList.cpp.
References m_strings.
Referenced by lldb::SBCommandInterpreter::HandleCompletionWithDescriptions(), and lldb_private::Editline::TabCommand().
operator<<() [1/3]
StringList & StringList::operator<< (const char * str)
Definition at line 211 of file StringList.cpp.
References AppendString(), and StringList().
operator<<() [2/3]
StringList & StringList::operator<< (const std::string & s)
Definition at line 216 of file StringList.cpp.
References AppendString(), and StringList().
operator<<() [3/3]
StringList & StringList::operator<< (const StringList & strings)
Definition at line 221 of file StringList.cpp.
References AppendList(), and StringList().
operator=()
StringList & StringList::operator= (const std::vector< std::string > & rhs)
Definition at line 226 of file StringList.cpp.
References m_strings, and StringList().
operator[]() [1/2]
std::string & lldb_private::StringList::operator[] (size_t idx) inline
Definition at line 68 of file StringList.h.
References m_strings.
operator[]() [2/2]
const std::string & lldb_private::StringList::operator[] (size_t idx) const inline
Definition at line 73 of file StringList.h.
References m_strings.
PopBack()
void lldb_private::StringList::PopBack () inline
Definition at line 78 of file StringList.h.
References m_strings.
Referenced by lldb_private::IOHandlerDelegateMultiline::IOHandlerIsInputComplete().
RemoveBlankLines()
void StringList::RemoveBlankLines ()
Definition at line 185 of file StringList.cpp.
References DeleteStringAtIndex(), GetSize(), and m_strings.
SetSize()
void lldb_private::StringList::SetSize (size_t n) inline
Definition at line 56 of file StringList.h.
References m_strings.
Referenced by lldb::SBCommandInterpreter::HandleCompletionWithDescriptions().
SplitIntoLines() [1/2]
size_t StringList::SplitIntoLines (const char * lines, size_t len)
Definition at line 156 of file StringList.cpp.
References end(), and m_strings.
SplitIntoLines() [2/2]
size_t StringList::SplitIntoLines (const std::string & lines)
Definition at line 152 of file StringList.cpp.
References SplitIntoLines().
Referenced by lldb::SBTypeCategory::AddTypeSummary(), lldb::SBTypeCategory::AddTypeSynthetic(), lldb::SBDebugger::GetInternalVariableValue(), CommandObjectCommandsScriptAdd::IOHandlerInputComplete(), CommandObjectTypeSummaryAdd::IOHandlerInputComplete(), CommandObjectTypeSynthAdd::IOHandlerInputComplete(), lldb_private::CommandCompletions::SettingsNames(), and SplitIntoLines().
Member Data Documentation
m_strings
collection lldb_private::StringList::m_strings private
Definition at line 133 of file StringList.h.
Referenced by AppendList(), AppendList(), AppendString(), AppendString(), AppendString(), AppendString(), AppendString(), AppendString(), begin(), begin(), Clear(), DeleteStringAtIndex(), end(), end(), GetMaxStringLength(), GetSize(), GetStringAtIndex(), InsertStringAtIndex(), InsertStringAtIndex(), InsertStringAtIndex(), LogDump(), LongestCommonPrefix(), operator=(), operator[](), operator[](), PopBack(), RemoveBlankLines(), SetSize(), SplitIntoLines(), StringList(), StringList(), and StringList().
The documentation for this class was generated from the following files:
StringList.h
StringList.cpp