LLDB: lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl > Class Template Reference
lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl > Class Template Reference
Public Member Functions
GenericInitializerListSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
~GenericInitializerListSyntheticFrontEnd () override
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Attributes
ValueObject * m_start = nullptr
CompilerType m_element_type
uint32_t m_element_size = 0
size_t m_num_elements = 0
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
template<class StandardImpl>
class lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >
Definition at line 55 of file GenericInitializerList.cpp.
Constructor & Destructor Documentation
GenericInitializerListSyntheticFrontEnd()
template<class StandardImpl> lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >::GenericInitializerListSyntheticFrontEnd (lldb::ValueObjectSP valobj_sp) inline
Definition at line 61 of file GenericInitializerList.cpp.
References m_element_type, lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd(), and Update().
~GenericInitializerListSyntheticFrontEnd()
template<class StandardImpl> lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >::~GenericInitializerListSyntheticFrontEnd () inline override
Definition at line 67 of file GenericInitializerList.cpp.
Member Function Documentation
CalculateNumChildren()
template<class StandardImpl> llvm::Expected< uint32_t > lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >::CalculateNumChildren () inline override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 73 of file GenericInitializerList.cpp.
References lldb_private::SyntheticChildrenFrontEnd::m_backend, and m_num_elements.
GetChildAtIndex()
template<class StandardImpl> lldb::ValueObjectSP lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >::GetChildAtIndex (uint32_t idx) inline override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 82 of file GenericInitializerList.cpp.
References lldb_private::SyntheticChildrenFrontEnd::CreateValueObjectFromAddress(), lldb_private::StreamString::GetString(), lldb_private::SyntheticChildrenFrontEnd::m_backend, m_element_size, m_element_type, m_start, and lldb_private::Stream::Printf().
GetIndexOfChildWithName()
template<class StandardImpl> llvm::Expected< size_t > lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >::GetIndexOfChildWithName (ConstString name) inline override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 115 of file GenericInitializerList.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::formatters::ExtractIndexFromString(), lldb_private::ConstString::GetCString(), and m_start.
Update()
template<class StandardImpl> lldb::ChildCacheState lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >::Update () inline override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 95 of file GenericInitializerList.cpp.
References lldb_private::DataFormatters, lldb::eRefetch, lldb_private::GetLog(), LLDB_LOG_ERRORV, lldb_private::SyntheticChildrenFrontEnd::m_backend, m_element_size, m_element_type, m_num_elements, and m_start.
Referenced by GenericInitializerListSyntheticFrontEnd().
Member Data Documentation
m_element_size
template<class StandardImpl> uint32_t lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >::m_element_size = 0 private
Definition at line 131 of file GenericInitializerList.cpp.
Referenced by GetChildAtIndex(), and Update().
m_element_type
template<class StandardImpl> CompilerType lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >::m_element_type private
Definition at line 130 of file GenericInitializerList.cpp.
Referenced by GenericInitializerListSyntheticFrontEnd(), GetChildAtIndex(), and Update().
m_num_elements
template<class StandardImpl> size_t lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >::m_num_elements = 0 private
Definition at line 132 of file GenericInitializerList.cpp.
Referenced by CalculateNumChildren(), and Update().
m_start
template<class StandardImpl> ValueObject* lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >::m_start = nullptr private
Definition at line 129 of file GenericInitializerList.cpp.
Referenced by GetChildAtIndex(), GetIndexOfChildWithName(), and Update().
The documentation for this class was generated from the following file:
GenericInitializerList.cpp