LLDB: lldb_private::OptionGroupPlatformSSH Class Reference
lldb_private::OptionGroupPlatformSSH Class Reference
#include <Platform.h>
Public Member Functions
OptionGroupPlatformSSH ()=default
~OptionGroupPlatformSSH () override=default
lldb_private::Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext *execution_context) override
void OptionParsingStarting (ExecutionContext *execution_context) override
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
virtual Status OptionParsingFinished (ExecutionContext *execution_context)
Public Attributes
bool m_ssh
std::string m_ssh_opts
Private Member Functions
OptionGroupPlatformSSH (const OptionGroupPlatformSSH &)=delete
const OptionGroupPlatformSSH & operator= (const OptionGroupPlatformSSH &)=delete
Detailed Description
Definition at line 1216 of file Platform.h.
Constructor & Destructor Documentation
OptionGroupPlatformSSH() [1/2]
lldb_private::OptionGroupPlatformSSH::OptionGroupPlatformSSH () default
Referenced by operator=(), and OptionGroupPlatformSSH().
~OptionGroupPlatformSSH()
lldb_private::OptionGroupPlatformSSH::~OptionGroupPlatformSSH () override default
OptionGroupPlatformSSH() [2/2]
lldb_private::OptionGroupPlatformSSH::OptionGroupPlatformSSH (const OptionGroupPlatformSSH &) private delete
References OptionGroupPlatformSSH().
Member Function Documentation
GetDefinitions()
llvm::ArrayRef< OptionDefinition > OptionGroupPlatformSSH::GetDefinitions () override virtual
Implements lldb_private::OptionGroup.
Definition at line 1368 of file Platform.cpp.
References g_ssh_option_table.
Referenced by SetOptionValue().
operator=()
const OptionGroupPlatformSSH & lldb_private::OptionGroupPlatformSSH::operator= (const OptionGroupPlatformSSH &) private delete
References OptionGroupPlatformSSH().
OptionParsingStarting()
void OptionGroupPlatformSSH::OptionParsingStarting (ExecutionContext * execution_context) override virtual
Implements lldb_private::OptionGroup.
Definition at line 1372 of file Platform.cpp.
References m_ssh, and m_ssh_opts.
SetOptionValue()
lldb_private::Status OptionGroupPlatformSSH::SetOptionValue (uint32_t option_idx, llvm::StringRef option_value, ExecutionContext * execution_context) override virtual
Implements lldb_private::OptionGroup.
Definition at line 1379 of file Platform.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormat(), GetDefinitions(), m_ssh, and m_ssh_opts.
Member Data Documentation
m_ssh
bool lldb_private::OptionGroupPlatformSSH::m_ssh
Definition at line 1232 of file Platform.h.
Referenced by OptionParsingStarting(), and SetOptionValue().
m_ssh_opts
std::string lldb_private::OptionGroupPlatformSSH::m_ssh_opts
Definition at line 1233 of file Platform.h.
Referenced by OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following files:
Platform.h
Platform.cpp