LLDB: PECallFrameInfo Class Reference
PECallFrameInfo Class Reference
#include <PECallFrameInfo.h>
Public Member Functions
PECallFrameInfo (ObjectFilePECOFF &object_file, uint32_t exception_dir_rva, uint32_t exception_dir_size)
bool GetAddressRange (lldb_private::Address addr, lldb_private::AddressRange &range) override
std::unique_ptr< lldb_private::UnwindPlan > GetUnwindPlan (const lldb_private::Address &addr) override
std::unique_ptr< lldb_private::UnwindPlan > GetUnwindPlan (llvm::ArrayRef< lldb_private::AddressRange > ranges, const lldb_private::Address &addr) override
Public Member Functions inherited from lldb_private::CallFrameInfo
virtual ~CallFrameInfo ()=default
Private Member Functions
const llvm::Win64EH::RuntimeFunction * FindRuntimeFunctionIntersectsWithRange (const lldb_private::AddressRange &range) const
Private Attributes
ObjectFilePECOFF & m_object_file
lldb_private::DataExtractor m_exception_dir
Detailed Description
Definition at line 27 of file PECallFrameInfo.h.
Constructor & Destructor Documentation
PECallFrameInfo()
PECallFrameInfo::PECallFrameInfo (ObjectFilePECOFF & object_file, uint32_t exception_dir_rva, uint32_t exception_dir_size) explicit
Definition at line 435 of file PECallFrameInfo.cpp.
References m_exception_dir, and m_object_file.
Member Function Documentation
FindRuntimeFunctionIntersectsWithRange()
const RuntimeFunction * PECallFrameInfo::FindRuntimeFunctionIntersectsWithRange (const lldb_private::AddressRange & range) const private
Definition at line 505 of file PECallFrameInfo.cpp.
References lldb_private::AddressRange::GetBaseAddress(), lldb_private::AddressRange::GetByteSize(), m_exception_dir, m_object_file, and TypedRead().
Referenced by GetAddressRange(), and GetUnwindPlan().
GetAddressRange()
bool PECallFrameInfo::GetAddressRange (lldb_private::Address addr, lldb_private::AddressRange & range) override virtual
Implements lldb_private::CallFrameInfo.
Definition at line 442 of file PECallFrameInfo.cpp.
References lldb_private::AddressRange::Clear(), FindRuntimeFunctionIntersectsWithRange(), lldb_private::AddressRange::GetBaseAddress(), m_object_file, and lldb_private::AddressRange::SetByteSize().
GetUnwindPlan() [1/2]
std::unique_ptr< lldb_private::UnwindPlan > PECallFrameInfo::GetUnwindPlan (const lldb_private::Address & addr) inline override virtual
Implements lldb_private::CallFrameInfo.
Definition at line 37 of file PECallFrameInfo.h.
References GetUnwindPlan().
Referenced by GetUnwindPlan().
GetUnwindPlan() [2/2]
std::unique_ptr< UnwindPlan > PECallFrameInfo::GetUnwindPlan (llvm::ArrayRef< lldb_private::AddressRange > ranges, const lldb_private::Address & addr) override virtual
Implements lldb_private::CallFrameInfo.
Definition at line 458 of file PECallFrameInfo.cpp.
References EHProgramBuilder::Build(), EHProgramRange::BuildUnwindPlanRow(), lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb::eRegisterKindLLDB, FindRuntimeFunctionIntersectsWithRange(), EHProgramBuilder::GetProgram(), m_object_file, and UINT32_MAX.
Member Data Documentation
m_exception_dir
lldb_private::DataExtractor PECallFrameInfo::m_exception_dir private
Definition at line 50 of file PECallFrameInfo.h.
Referenced by FindRuntimeFunctionIntersectsWithRange(), and PECallFrameInfo().
m_object_file
ObjectFilePECOFF& PECallFrameInfo::m_object_file private
Definition at line 49 of file PECallFrameInfo.h.
Referenced by FindRuntimeFunctionIntersectsWithRange(), GetAddressRange(), GetUnwindPlan(), and PECallFrameInfo().
The documentation for this class was generated from the following files:
PECallFrameInfo.h
PECallFrameInfo.cpp