LLDB: lldb::SBBreakpointList Class Reference
lldb::SBBreakpointList Class Reference
#include <SBBreakpoint.h>
Public Member Functions
SBBreakpointList (SBTarget &target)
~SBBreakpointList ()
size_t GetSize () const
SBBreakpoint GetBreakpointAtIndex (size_t idx)
SBBreakpoint FindBreakpointByID (lldb::break_id_t)
void Append (const SBBreakpoint &sb_bkpt)
bool AppendIfUnique (const SBBreakpoint &sb_bkpt)
void AppendByID (lldb::break_id_t id)
void Clear ()
Protected Member Functions
void CopyToBreakpointIDList (lldb_private::BreakpointIDList &bp_id_list)
Private Attributes
std::shared_ptr< SBBreakpointListImpl > m_opaque_sp
Friends
class SBTarget
Detailed Description
Definition at line 184 of file SBBreakpoint.h.
Constructor & Destructor Documentation
SBBreakpointList()
SBBreakpointList::SBBreakpointList (SBTarget & target)
Definition at line 897 of file SBBreakpoint.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBTarget.
~SBBreakpointList()
SBBreakpointList::~SBBreakpointList () default
References Append(), AppendByID(), AppendIfUnique(), Clear(), FindBreakpointByID(), GetBreakpointAtIndex(), and GetSize().
Member Function Documentation
Append()
void SBBreakpointList::Append (const SBBreakpoint & sb_bkpt)
Definition at line 932 of file SBBreakpoint.cpp.
References lldb::SBBreakpoint::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBBreakpoint::m_opaque_wp.
Referenced by ~SBBreakpointList().
AppendByID()
void SBBreakpointList::AppendByID (lldb::break_id_t id)
Definition at line 942 of file SBBreakpoint.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by lldb::SBTarget::BreakpointsCreateFromFile(), lldb::SBTarget::FindBreakpointsByName(), and ~SBBreakpointList().
AppendIfUnique()
bool SBBreakpointList::AppendIfUnique (const SBBreakpoint & sb_bkpt)
Definition at line 950 of file SBBreakpoint.cpp.
References lldb::SBBreakpoint::GetSP(), lldb::SBBreakpoint::IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBBreakpointList().
Clear()
void SBBreakpointList::Clear ()
Definition at line 960 of file SBBreakpoint.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBBreakpointList().
CopyToBreakpointIDList()
void SBBreakpointList::CopyToBreakpointIDList (lldb_private::BreakpointIDList & bp_id_list) protected
Definition at line 967 of file SBBreakpoint.cpp.
References m_opaque_sp.
Referenced by lldb::SBTarget::BreakpointsWriteToFile(), and SBTarget.
FindBreakpointByID()
SBBreakpoint SBBreakpointList::FindBreakpointByID (lldb::break_id_t id)
Definition at line 923 of file SBBreakpoint.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBBreakpoint.
Referenced by ~SBBreakpointList().
GetBreakpointAtIndex()
SBBreakpoint SBBreakpointList::GetBreakpointAtIndex (size_t idx)
Definition at line 913 of file SBBreakpoint.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBBreakpoint.
Referenced by ~SBBreakpointList().
GetSize()
size_t SBBreakpointList::GetSize () const
Definition at line 904 of file SBBreakpoint.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBBreakpointList().
Friends And Related Symbol Documentation
SBTarget
friend class SBTarget friend
Definition at line 205 of file SBBreakpoint.h.
References CopyToBreakpointIDList(), and SBTarget.
Referenced by SBBreakpointList(), and SBTarget.
Member Data Documentation
m_opaque_sp
std::shared_ptr<SBBreakpointListImpl> lldb::SBBreakpointList::m_opaque_sp private
Definition at line 210 of file SBBreakpoint.h.
Referenced by Append(), AppendByID(), AppendIfUnique(), Clear(), CopyToBreakpointIDList(), FindBreakpointByID(), GetBreakpointAtIndex(), GetSize(), and SBBreakpointList().
The documentation for this class was generated from the following files:
SBBreakpoint.h
SBBreakpoint.cpp