LLDB: lldb_private::ClangASTMetadata Class Reference
lldb_private::ClangASTMetadata Class Reference
#include <ClangASTMetadata.h>
Public Member Functions
ClangASTMetadata ()
std::optional< bool > GetIsDynamicCXXType () const
void SetIsDynamicCXXType (std::optional< bool > b)
void SetUserID (lldb::user_id_t user_id)
lldb::user_id_t GetUserID () const
void SetISAPtr (uint64_t isa_ptr)
uint64_t GetISAPtr () const
void SetObjectPtrName (const char *name)
lldb::LanguageType GetObjectPtrLanguage () const
const char * GetObjectPtrName () const
bool HasObjectPtr () const
bool IsForcefullyCompleted () const
A type is "forcefully completed" if it was declared complete to satisfy an AST invariant (e.g.
void SetIsForcefullyCompleted (bool value=true)
void Dump (Stream *s)
Private Attributes
union {
lldb::user_id_t m_user_id
uint64_t m_isa_ptr
};
unsigned m_union_is_user_id: 1
unsigned m_union_is_isa_ptr: 1
unsigned m_has_object_ptr: 1
unsigned m_is_self: 1
unsigned m_is_dynamic_cxx: 2
unsigned m_is_forcefully_completed: 1
Detailed Description
Definition at line 19 of file ClangASTMetadata.h.
Constructor & Destructor Documentation
ClangASTMetadata()
lldb_private::ClangASTMetadata::ClangASTMetadata () inline
Definition at line 21 of file ClangASTMetadata.h.
References m_has_object_ptr, m_is_forcefully_completed, m_is_self, m_union_is_isa_ptr, m_union_is_user_id, m_user_id, and SetIsDynamicCXXType().
Member Function Documentation
Dump()
void ClangASTMetadata::Dump (Stream * s)
Definition at line 30 of file ClangASTMetadata.cpp.
References lldb_private::Stream::EOL(), GetISAPtr(), GetObjectPtrName(), GetUserID(), LLDB_INVALID_UID, m_is_dynamic_cxx, and lldb_private::Stream::Printf().
GetISAPtr()
uint64_t lldb_private::ClangASTMetadata::GetISAPtr () const inline
Definition at line 51 of file ClangASTMetadata.h.
References m_isa_ptr, and m_union_is_isa_ptr.
Referenced by Dump().
GetIsDynamicCXXType()
std::optional< bool > ClangASTMetadata::GetIsDynamicCXXType () const
Definition at line 14 of file ClangASTMetadata.cpp.
References m_is_dynamic_cxx.
GetObjectPtrLanguage()
lldb::LanguageType lldb_private::ClangASTMetadata::GetObjectPtrLanguage () const inline
Definition at line 68 of file ClangASTMetadata.h.
References lldb::eLanguageTypeC_plus_plus, lldb::eLanguageTypeObjC, lldb::eLanguageTypeUnknown, m_has_object_ptr, and m_is_self.
GetObjectPtrName()
const char * lldb_private::ClangASTMetadata::GetObjectPtrName () const inline
Definition at line 78 of file ClangASTMetadata.h.
References m_has_object_ptr, and m_is_self.
Referenced by Dump().
GetUserID()
lldb::user_id_t lldb_private::ClangASTMetadata::GetUserID () const inline
Definition at line 38 of file ClangASTMetadata.h.
References LLDB_INVALID_UID, m_union_is_user_id, and m_user_id.
Referenced by Dump().
HasObjectPtr()
bool lldb_private::ClangASTMetadata::HasObjectPtr () const inline
Definition at line 88 of file ClangASTMetadata.h.
References m_has_object_ptr.
IsForcefullyCompleted()
bool lldb_private::ClangASTMetadata::IsForcefullyCompleted () const inline
A type is "forcefully completed" if it was declared complete to satisfy an AST invariant (e.g.
base classes must be complete types), but in fact we were not able to find a actual definition for it.
Definition at line 93 of file ClangASTMetadata.h.
References m_is_forcefully_completed.
SetISAPtr()
void lldb_private::ClangASTMetadata::SetISAPtr (uint64_t isa_ptr) inline
Definition at line 45 of file ClangASTMetadata.h.
References m_isa_ptr, m_union_is_isa_ptr, and m_union_is_user_id.
Referenced by lldb_private::AppleObjCDeclVendor::GetDeclForISA().
SetIsDynamicCXXType()
void ClangASTMetadata::SetIsDynamicCXXType (std::optional< bool > b)
Definition at line 26 of file ClangASTMetadata.cpp.
References m_is_dynamic_cxx.
Referenced by lldb_private::npdb::UdtRecordCompleter::AddMember(), ClangASTMetadata(), PDBASTParser::CreateLLDBTypeFromPDBType(), lldb_private::npdb::PdbAstBuilderClang::CreateRecordType(), and DWARFASTParserClang::ParseStructureLikeDIE().
SetIsForcefullyCompleted()
void lldb_private::ClangASTMetadata::SetIsForcefullyCompleted (bool value = true) inline
Definition at line 95 of file ClangASTMetadata.h.
References m_is_forcefully_completed.
SetObjectPtrName()
void lldb_private::ClangASTMetadata::SetObjectPtrName (const char * name) inline
Definition at line 58 of file ClangASTMetadata.h.
References m_has_object_ptr, and m_is_self.
Referenced by DWARFASTParserClang::ParseCXXMethod(), and DWARFASTParserClang::ParseSubroutine().
SetUserID()
void lldb_private::ClangASTMetadata::SetUserID (lldb::user_id_t user_id) inline
Definition at line 32 of file ClangASTMetadata.h.
References m_union_is_isa_ptr, m_union_is_user_id, and m_user_id.
Referenced by lldb_private::npdb::UdtRecordCompleter::AddMember(), PDBASTParser::CreateLLDBTypeFromPDBType(), lldb_private::npdb::PdbAstBuilderClang::CreateRecordType(), DWARFASTParserClang::ParseCXXMethod(), DWARFASTParserClang::ParseObjCProperty(), DWARFASTParserClang::ParseStructureLikeDIE(), DWARFASTParserClang::ParseSubroutine(), lldb_private::TypeSystemClang::SetMetadataAsUserID(), and lldb_private::TypeSystemClang::SetMetadataAsUserID().
Member Data Documentation
[union]
union { ... } lldb_private::ClangASTMetadata
m_has_object_ptr
unsigned lldb_private::ClangASTMetadata::m_has_object_ptr private
Definition at line 107 of file ClangASTMetadata.h.
Referenced by ClangASTMetadata(), GetObjectPtrLanguage(), GetObjectPtrName(), HasObjectPtr(), and SetObjectPtrName().
m_is_dynamic_cxx
unsigned lldb_private::ClangASTMetadata::m_is_dynamic_cxx private
Definition at line 108 of file ClangASTMetadata.h.
Referenced by Dump(), GetIsDynamicCXXType(), and SetIsDynamicCXXType().
m_is_forcefully_completed
unsigned lldb_private::ClangASTMetadata::m_is_forcefully_completed private
Definition at line 108 of file ClangASTMetadata.h.
Referenced by ClangASTMetadata(), IsForcefullyCompleted(), and SetIsForcefullyCompleted().
m_is_self
unsigned lldb_private::ClangASTMetadata::m_is_self private
Definition at line 108 of file ClangASTMetadata.h.
Referenced by ClangASTMetadata(), GetObjectPtrLanguage(), GetObjectPtrName(), and SetObjectPtrName().
m_isa_ptr
uint64_t lldb_private::ClangASTMetadata::m_isa_ptr
Definition at line 104 of file ClangASTMetadata.h.
Referenced by GetISAPtr(), and SetISAPtr().
m_union_is_isa_ptr
unsigned lldb_private::ClangASTMetadata::m_union_is_isa_ptr private
Definition at line 107 of file ClangASTMetadata.h.
Referenced by ClangASTMetadata(), GetISAPtr(), SetISAPtr(), and SetUserID().
m_union_is_user_id
unsigned lldb_private::ClangASTMetadata::m_union_is_user_id private
Definition at line 107 of file ClangASTMetadata.h.
Referenced by ClangASTMetadata(), GetUserID(), SetISAPtr(), and SetUserID().
m_user_id
lldb::user_id_t lldb_private::ClangASTMetadata::m_user_id
Definition at line 103 of file ClangASTMetadata.h.
Referenced by ClangASTMetadata(), GetUserID(), and SetUserID().
The documentation for this class was generated from the following files:
ClangASTMetadata.h
ClangASTMetadata.cpp