LLDB: lldb_private::ReportRetriever Class Reference
lldb_private::ReportRetriever Class Reference
#include <ReportRetriever.h>
Static Public Member Functions
static bool NotifyBreakpointHit (lldb::ProcessSP process_sp, StoppointCallbackContext *context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id)
static Breakpoint * SetupBreakpoint (lldb::ModuleSP, lldb::ProcessSP, ConstString)
Static Private Member Functions
static StructuredData::ObjectSP RetrieveReportData (const lldb::ProcessSP process_sp)
static std::string FormatDescription (StructuredData::ObjectSP report)
Detailed Description
Definition at line 16 of file ReportRetriever.h.
Member Function Documentation
FormatDescription()
std::string ReportRetriever::FormatDescription (StructuredData::ObjectSP report) static private
Definition at line 152 of file ReportRetriever.cpp.
Referenced by NotifyBreakpointHit().
NotifyBreakpointHit()
bool ReportRetriever::NotifyBreakpointHit (lldb::ProcessSP process_sp, StoppointCallbackContext * context, lldb::user_id_t break_id, lldb::user_id_t break_loc_id) static
Definition at line 198 of file ReportRetriever.cpp.
References lldb_private::InstrumentationRuntimeStopInfo::CreateStopReasonWithInstrumentationData(), lldb::eStructuredDataTypeDictionary, lldb_private::StoppointCallbackContext::exe_ctx_ref, FormatDescription(), lldb_private::GetLog(), lldb_private::ExecutionContextRef::GetProcessSP(), lldb_private::ExecutionContextRef::GetThreadSP(), lldb_private::InstrumentationRuntime, LLDB_LOGF, and RetrieveReportData().
Referenced by InstrumentationRuntimeASanLibsanitizers::NotifyBreakpointHit(), and lldb_private::InstrumentationRuntimeASan::NotifyBreakpointHit().
RetrieveReportData()
StructuredData::ObjectSP ReportRetriever::RetrieveReportData (const lldb::ProcessSP process_sp) static private
Definition at line 60 of file ReportRetriever.cpp.
References address_sanitizer_retrieve_report_data_command, address_sanitizer_retrieve_report_data_prefix, lldb_private::SymbolContextList::Append(), DoNoSelectMostRelevantFrame, lldb::eExpressionCompleted, lldb::eLanguageTypeC, error(), lldb_private::UserExpression::Evaluate(), lldb_private::GetPreferredAsanModule(), lldb_private::StreamString::GetString(), pc, lldb_private::Debugger::ReportWarning(), lldb_private::EvaluateExpressionOptions::SetAutoApplyFixIts(), lldb_private::EvaluateExpressionOptions::SetIgnoreBreakpoints(), lldb_private::EvaluateExpressionOptions::SetLanguage(), lldb_private::EvaluateExpressionOptions::SetPreferredSymbolContexts(), lldb_private::EvaluateExpressionOptions::SetPrefix(), lldb_private::EvaluateExpressionOptions::SetStopOthers(), lldb_private::EvaluateExpressionOptions::SetTimeout(), lldb_private::EvaluateExpressionOptions::SetTryAllThreads(), lldb_private::EvaluateExpressionOptions::SetUnwindOnError(), and sp.
Referenced by NotifyBreakpointHit().
SetupBreakpoint()
Breakpoint * ReportRetriever::SetupBreakpoint (lldb::ModuleSP module_sp, lldb::ProcessSP process_sp, ConstString symbol_name) static
Definition at line 232 of file ReportRetriever.cpp.
References lldb::eSymbolTypeCode, lldb_private::Symbol::GetAddressRef(), lldb_private::Address::IsValid(), and lldb_private::Symbol::ValueIsAddress().
Referenced by InstrumentationRuntimeASanLibsanitizers::Activate(), and lldb_private::InstrumentationRuntimeASan::Activate().
The documentation for this class was generated from the following files:
ReportRetriever.h
ReportRetriever.cpp