LLDB: lldb::SBFileSpec Class Reference
lldb::SBFileSpec Class Reference
#include <SBFileSpec.h>
Public Member Functions
SBFileSpec ()
SBFileSpec (const lldb::SBFileSpec &rhs)
LLDB_DEPRECATED_FIXME ("Use the other constructor to determine if this the file " "spec should be resolved", "SBFileSpec(const char *, bool)") SBFileSpec(const char *path)
SBFileSpec (const char *path, bool resolve)
~SBFileSpec ()
const SBFileSpec & operator= (const lldb::SBFileSpec &rhs)
operator bool () const
bool operator== (const SBFileSpec &rhs) const
bool operator!= (const SBFileSpec &rhs) const
bool IsValid () const
bool Exists () const
bool ResolveExecutableLocation ()
const char * GetFilename () const
const char * GetDirectory () const
void SetFilename (const char *filename)
void SetDirectory (const char *directory)
uint32_t GetPath (char *dst_path, size_t dst_len) const
bool GetDescription (lldb::SBStream &description) const
void AppendPathComponent (const char *file_or_directory)
Static Public Member Functions
static int ResolvePath (const char *src_path, char *dst_path, size_t dst_len)
Private Member Functions
SBFileSpec (const lldb_private::FileSpec &fspec)
void SetFileSpec (const lldb_private::FileSpec &fspec)
const lldb_private::FileSpec * operator-> () const
const lldb_private::FileSpec * get () const
const lldb_private::FileSpec & operator* () const
const lldb_private::FileSpec & ref () const
Private Attributes
std::unique_ptr< lldb_private::FileSpec > m_opaque_up
Friends
class SBAttachInfo
class SBBlock
class SBCommandInterpreter
class SBCompileUnit
class SBDeclaration
class SBFileSpecList
class SBHostOS
class SBLaunchInfo
class SBLineEntry
class SBModule
class SBModuleSpec
class SBPlatform
class SBProcess
class SBProcessInfo
class SBSourceManager
class SBTarget
class SBThread
class SBTrace
class SBSaveCoreOptions
Detailed Description
Definition at line 16 of file SBFileSpec.h.
Constructor & Destructor Documentation
SBFileSpec() [1/4]
SBFileSpec::SBFileSpec ()
Definition at line 26 of file SBFileSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by LLDB_DEPRECATED_FIXME(), operator!=(), operator=(), operator==(), SBFileSpec(), SBSaveCoreOptions, and ~SBFileSpec().
SBFileSpec() [2/4]
SBFileSpec::SBFileSpec (const lldb::SBFileSpec & rhs)
Definition at line 30 of file SBFileSpec.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBFileSpec().
SBFileSpec() [3/4]
SBFileSpec::SBFileSpec (const char * path, bool resolve)
Definition at line 46 of file SBFileSpec.cpp.
References lldb_private::FileSystem::Instance(), LLDB_INSTRUMENT_VA, m_opaque_up, and lldb_private::FileSystem::Resolve().
~SBFileSpec()
SBFileSpec::~SBFileSpec () default
References AppendPathComponent(), Exists(), GetDescription(), GetDirectory(), GetFilename(), GetPath(), IsValid(), ResolveExecutableLocation(), ResolvePath(), SBFileSpec(), SetDirectory(), and SetFilename().
SBFileSpec() [4/4]
SBFileSpec::SBFileSpec (const lldb_private::FileSpec & fspec) private
Definition at line 36 of file SBFileSpec.cpp.
References m_opaque_up.
Member Function Documentation
AppendPathComponent()
void SBFileSpec::AppendPathComponent (const char * file_or_directory)
Definition at line 178 of file SBFileSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBFileSpec().
Exists()
bool SBFileSpec::Exists () const
Definition at line 86 of file SBFileSpec.cpp.
References lldb_private::FileSystem::Exists(), lldb_private::FileSystem::Instance(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBPlatform::Install(), lldb::SBPlatform::Put(), and ~SBFileSpec().
get()
const lldb_private::FileSpec * SBFileSpec::get () const private
Definition at line 154 of file SBFileSpec.cpp.
References m_opaque_up.
Referenced by lldb::SBCompileUnit::FindLineEntryIndex(), and SBSaveCoreOptions.
GetDescription()
bool SBFileSpec::GetDescription (lldb::SBStream & description) const
Definition at line 168 of file SBFileSpec.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, PATH_MAX, lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
Referenced by lldb::SBCommandInterpreter::HandleCommandsFromFile(), and ~SBFileSpec().
GetDirectory()
const char * SBFileSpec::GetDirectory () const
Definition at line 114 of file SBFileSpec.cpp.
References lldb_private::FileSpec::ClearFilename(), lldb_private::ConstString::GetCString(), lldb_private::FileSpec::GetPathAsConstString(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBFileSpec().
GetFilename()
const char * SBFileSpec::GetFilename () const
Definition at line 108 of file SBFileSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBFileSpec().
GetPath()
uint32_t SBFileSpec::GetPath (char * dst_path, size_t dst_len) const
Definition at line 140 of file SBFileSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBProcess::GetDescription(), and ~SBFileSpec().
IsValid()
bool SBFileSpec::IsValid () const
Definition at line 76 of file SBFileSpec.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBTarget::BreakpointCreateBySourceRegex(), lldb::SBModule::FindCompileUnits(), lldb::SBTarget::FindCompileUnits(), lldb::SBTarget::FindModule(), lldb::SBCommandInterpreter::HandleCommandsFromFile(), lldb::SBAttachInfo::SetExecutable(), lldb::SBDeclaration::SetFileSpec(), lldb::SBLineEntry::SetFileSpec(), lldb::SBThread::StepOverUntil(), and ~SBFileSpec().
LLDB_DEPRECATED_FIXME()
lldb::SBFileSpec::LLDB_DEPRECATED_FIXME ("Use the other constructor to determine if this the file " "spec should be resolved" , "SBFileSpec(const char *, bool)") const
References SBFileSpec().
operator bool()
SBFileSpec::operator bool () const explicit
Definition at line 80 of file SBFileSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
operator!=()
bool SBFileSpec::operator!= (const SBFileSpec & rhs) const
Definition at line 70 of file SBFileSpec.cpp.
References LLDB_INSTRUMENT_VA, and SBFileSpec().
operator*()
const lldb_private::FileSpec & SBFileSpec::operator* () const private
Definition at line 158 of file SBFileSpec.cpp.
References m_opaque_up.
operator->()
const lldb_private::FileSpec * SBFileSpec::operator-> () const private
Definition at line 150 of file SBFileSpec.cpp.
References m_opaque_up.
operator=()
const SBFileSpec & SBFileSpec::operator= (const lldb::SBFileSpec & rhs)
Definition at line 56 of file SBFileSpec.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBFileSpec().
operator==()
bool SBFileSpec::operator== (const SBFileSpec & rhs) const
Definition at line 64 of file SBFileSpec.cpp.
References LLDB_INSTRUMENT_VA, ref(), and SBFileSpec().
ref()
const lldb_private::FileSpec & SBFileSpec::ref () const private
Definition at line 162 of file SBFileSpec.cpp.
References m_opaque_up.
Referenced by lldb::SBFileSpecList::Append(), lldb::SBFileSpecList::AppendIfUnique(), lldb::SBTarget::BreakpointsCreateFromFile(), lldb::SBTarget::BreakpointsWriteToFile(), lldb::SBSourceManager::DisplaySourceLinesWithLineNumbers(), lldb::SBSourceManager::DisplaySourceLinesWithLineNumbersAndColumn(), lldb::SBFileSpecList::FindFileIndex(), lldb::SBCompileUnit::FindSupportFileIndex(), lldb::SBPlatform::Get(), lldb::SBCommandInterpreter::HandleCommandsFromFile(), lldb::SBPlatform::Install(), lldb::SBThread::JumpToLine(), lldb::SBTrace::LoadTraceFromFile(), operator==(), lldb::SBPlatform::Put(), lldb::SBTrace::SaveToDisk(), SBSaveCoreOptions, lldb::SBAttachInfo::SetExecutable(), lldb::SBLaunchInfo::SetExecutableFile(), lldb::SBDeclaration::SetFileSpec(), lldb::SBLineEntry::SetFileSpec(), lldb::SBPlatform::SetLocateModuleCallback(), lldb::SBSaveCoreOptions::SetOutputFile(), lldb::SBModule::SetRemoteInstallFileSpec(), and lldb::SBThread::StepOverUntil().
ResolveExecutableLocation()
bool SBFileSpec::ResolveExecutableLocation ()
Definition at line 92 of file SBFileSpec.cpp.
References lldb_private::FileSystem::Instance(), LLDB_INSTRUMENT_VA, m_opaque_up, and lldb_private::FileSystem::ResolveExecutableLocation().
Referenced by ~SBFileSpec().
ResolvePath()
int SBFileSpec::ResolvePath (const char * src_path, char * dst_path, size_t dst_len) static
Definition at line 98 of file SBFileSpec.cpp.
References lldb_private::FileSystem::Instance(), LLDB_INSTRUMENT_VA, and lldb_private::FileSystem::Resolve().
Referenced by ~SBFileSpec().
SetDirectory()
void SBFileSpec::SetDirectory (const char * directory)
Definition at line 131 of file SBFileSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBFileSpec().
SetFilename()
void SBFileSpec::SetFilename (const char * filename)
Definition at line 122 of file SBFileSpec.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBFileSpec().
SetFileSpec()
void SBFileSpec::SetFileSpec (const lldb_private::FileSpec & fspec) private
Definition at line 164 of file SBFileSpec.cpp.
References m_opaque_up.
Referenced by lldb::SBTarget::GetExecutable(), lldb::SBProcessInfo::GetExecutableFile(), lldb::SBCompileUnit::GetFileSpec(), lldb::SBDeclaration::GetFileSpec(), lldb::SBLineEntry::GetFileSpec(), lldb::SBModule::GetFileSpec(), lldb::SBFileSpecList::GetFileSpecAtIndex(), lldb::SBBlock::GetInlinedCallSiteFile(), lldb::SBHostOS::GetLLDBPath(), lldb::SBModule::GetPlatformFileSpec(), lldb::SBHostOS::GetProgramFileSpec(), lldb::SBModule::GetRemoteInstallFileSpec(), lldb::SBHostOS::GetScriptPath(), lldb::SBCompileUnit::GetSupportFileAtIndex(), lldb::SBModule::GetSymbolFileSpec(), lldb::SBTrace::SaveToDisk(), and SBSaveCoreOptions.
Friends And Related Symbol Documentation
SBAttachInfo
friend class SBAttachInfo friend
Definition at line 63 of file SBFileSpec.h.
References SBAttachInfo.
Referenced by SBAttachInfo.
SBBlock
friend class SBBlock friend
Definition at line 64 of file SBFileSpec.h.
References SBBlock.
Referenced by SBBlock.
SBCommandInterpreter
friend class SBCommandInterpreter friend
Definition at line 65 of file SBFileSpec.h.
References SBCommandInterpreter.
Referenced by SBCommandInterpreter.
SBCompileUnit
friend class SBCompileUnit friend
Definition at line 66 of file SBFileSpec.h.
References SBCompileUnit.
Referenced by SBCompileUnit.
SBDeclaration
friend class SBDeclaration friend
Definition at line 67 of file SBFileSpec.h.
References SBDeclaration.
Referenced by SBDeclaration.
SBFileSpecList
friend class SBFileSpecList friend
Definition at line 68 of file SBFileSpec.h.
References SBFileSpecList.
Referenced by SBFileSpecList.
SBHostOS
friend class SBHostOS friend
Definition at line 69 of file SBFileSpec.h.
References SBHostOS.
Referenced by SBHostOS.
SBLaunchInfo
friend class SBLaunchInfo friend
Definition at line 70 of file SBFileSpec.h.
References SBLaunchInfo.
Referenced by SBLaunchInfo.
SBLineEntry
friend class SBLineEntry friend
Definition at line 71 of file SBFileSpec.h.
References SBLineEntry.
Referenced by SBLineEntry.
SBModule
friend class SBModule friend
Definition at line 72 of file SBFileSpec.h.
References SBModule.
Referenced by SBModule.
SBModuleSpec
friend class SBModuleSpec friend
Definition at line 73 of file SBFileSpec.h.
References SBModuleSpec.
Referenced by SBModuleSpec.
SBPlatform
friend class SBPlatform friend
Definition at line 74 of file SBFileSpec.h.
References SBPlatform.
Referenced by SBPlatform.
SBProcess
friend class SBProcess friend
Definition at line 75 of file SBFileSpec.h.
References SBProcess.
Referenced by SBProcess.
SBProcessInfo
friend class SBProcessInfo friend
Definition at line 76 of file SBFileSpec.h.
References SBProcessInfo.
Referenced by SBProcessInfo.
SBSaveCoreOptions
friend class SBSaveCoreOptions friend
Definition at line 81 of file SBFileSpec.h.
References get(), ref(), SBFileSpec(), SBSaveCoreOptions, and SetFileSpec().
Referenced by SBSaveCoreOptions.
SBSourceManager
friend class SBSourceManager friend
Definition at line 77 of file SBFileSpec.h.
References SBSourceManager.
Referenced by SBSourceManager.
SBTarget
friend class SBTarget friend
Definition at line 78 of file SBFileSpec.h.
References SBTarget.
Referenced by SBTarget.
SBThread
friend class SBThread friend
Definition at line 79 of file SBFileSpec.h.
References SBThread.
Referenced by SBThread.
SBTrace
friend class SBTrace friend
Definition at line 80 of file SBFileSpec.h.
References SBTrace.
Referenced by SBTrace.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::FileSpec> lldb::SBFileSpec::m_opaque_up private
Definition at line 95 of file SBFileSpec.h.
Referenced by AppendPathComponent(), Exists(), get(), GetDescription(), GetDirectory(), GetFilename(), GetPath(), operator bool(), operator*(), operator->(), operator=(), ref(), ResolveExecutableLocation(), SBFileSpec(), SBFileSpec(), SBFileSpec(), SBFileSpec(), SetDirectory(), SetFilename(), and SetFileSpec().
The documentation for this class was generated from the following files:
SBFileSpec.h
SBFileSpec.cpp