LLDB: lldb::SBBlock Class Reference
lldb::SBBlock Class Reference
#include <SBBlock.h>
Public Member Functions
SBBlock ()
SBBlock (const lldb::SBBlock &rhs)
~SBBlock ()
const lldb::SBBlock & operator= (const lldb::SBBlock &rhs)
bool IsInlined () const
operator bool () const
bool IsValid () const
const char * GetInlinedName () const
lldb::SBFileSpec GetInlinedCallSiteFile () const
uint32_t GetInlinedCallSiteLine () const
uint32_t GetInlinedCallSiteColumn () const
lldb::SBBlock GetParent ()
lldb::SBBlock GetSibling ()
lldb::SBBlock GetFirstChild ()
uint32_t GetNumRanges ()
lldb::SBAddress GetRangeStartAddress (uint32_t idx)
lldb::SBAddress GetRangeEndAddress (uint32_t idx)
lldb::SBAddressRangeList GetRanges ()
uint32_t GetRangeIndexForBlockAddress (lldb::SBAddress block_addr)
lldb::SBValueList GetVariables (lldb::SBFrame &frame, bool arguments, bool locals, bool statics, lldb::DynamicValueType use_dynamic)
lldb::SBValueList GetVariables (lldb::SBTarget &target, bool arguments, bool locals, bool statics)
lldb::SBBlock GetContainingInlinedBlock ()
Get the inlined block that contains this block.
bool GetDescription (lldb::SBStream &description)
Private Member Functions
lldb_private::Block * GetPtr ()
void SetPtr (lldb_private::Block *lldb_object_ptr)
SBBlock (lldb_private::Block *lldb_object_ptr)
void AppendVariables (bool can_create, bool get_parent_variables, lldb_private::VariableList *var_list)
Private Attributes
lldb_private::Block * m_opaque_ptr = nullptr
Friends
class SBAddress
class SBFrame
class SBFunction
class SBSymbolContext
Detailed Description
Definition at line 21 of file SBBlock.h.
Constructor & Destructor Documentation
SBBlock() [1/3]
SBBlock::SBBlock ()
Definition at line 29 of file SBBlock.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by GetContainingInlinedBlock(), GetFirstChild(), GetParent(), GetSibling(), operator=(), SBBlock(), and SBSymbolContext.
SBBlock() [2/3]
SBBlock::SBBlock (const lldb::SBBlock & rhs)
Definition at line 34 of file SBBlock.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBBlock().
~SBBlock()
SBBlock::~SBBlock ()
Definition at line 45 of file SBBlock.cpp.
References m_opaque_ptr.
SBBlock() [3/3]
SBBlock::SBBlock (lldb_private::Block * lldb_object_ptr) private
Definition at line 31 of file SBBlock.cpp.
References m_opaque_ptr.
Member Function Documentation
AppendVariables()
void SBBlock::AppendVariables (bool can_create, bool get_parent_variables, lldb_private::VariableList * var_list) private
Definition at line 115 of file SBBlock.cpp.
References IsValid(), and m_opaque_ptr.
Referenced by SBSymbolContext.
GetContainingInlinedBlock()
lldb::SBBlock SBBlock::GetContainingInlinedBlock ()
Get the inlined block that contains this block.
Returns
If this block is inlined, it will return this block, else parent blocks will be searched to see if any contain this block and are themselves inlined. An invalid SBBlock will be returned if this block nor any parent blocks are inlined function blocks.
Definition at line 133 of file SBBlock.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBBlock().
GetDescription()
bool SBBlock::GetDescription (lldb::SBStream & description)
Definition at line 164 of file SBBlock.cpp.
References lldb_private::SymbolContext::function, lldb_private::Function::GetAddress(), lldb_private::Address::GetFileAddress(), GetInlinedName(), IsInlined(), LLDB_INSTRUMENT_VA, m_opaque_ptr, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
GetFirstChild()
SBBlock SBBlock::GetFirstChild ()
Definition at line 151 of file SBBlock.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBBlock().
GetInlinedCallSiteColumn()
uint32_t SBBlock::GetInlinedCallSiteColumn () const
Definition at line 103 of file SBBlock.cpp.
References lldb_private::InlineFunctionInfo::GetCallSite(), lldb_private::Declaration::GetColumn(), LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetInlinedCallSiteFile()
SBFileSpec SBBlock::GetInlinedCallSiteFile () const
Definition at line 78 of file SBBlock.cpp.
References lldb_private::InlineFunctionInfo::GetCallSite(), lldb_private::Declaration::GetFile(), LLDB_INSTRUMENT_VA, m_opaque_ptr, and lldb::SBFileSpec::SetFileSpec().
GetInlinedCallSiteLine()
uint32_t SBBlock::GetInlinedCallSiteLine () const
Definition at line 91 of file SBBlock.cpp.
References lldb_private::InlineFunctionInfo::GetCallSite(), lldb_private::Declaration::GetLine(), LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetInlinedName()
const char * SBBlock::GetInlinedName () const
Definition at line 65 of file SBBlock.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::InlineFunctionInfo::GetName(), LLDB_INSTRUMENT_VA, and m_opaque_ptr.
Referenced by GetDescription().
GetNumRanges()
uint32_t SBBlock::GetNumRanges ()
Definition at line 187 of file SBBlock.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
GetParent()
SBBlock SBBlock::GetParent ()
Definition at line 124 of file SBBlock.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBBlock().
GetPtr()
lldb_private::Block * SBBlock::GetPtr () private
Definition at line 160 of file SBBlock.cpp.
References m_opaque_ptr.
Referenced by GetVariables(), GetVariables(), SBSymbolContext, and lldb::SBSymbolContext::SetBlock().
GetRangeEndAddress()
lldb::SBAddress SBBlock::GetRangeEndAddress (uint32_t idx)
Definition at line 208 of file SBBlock.cpp.
References lldb_private::AddressRange::GetBaseAddress(), lldb_private::AddressRange::GetByteSize(), LLDB_INSTRUMENT_VA, m_opaque_ptr, lldb::SBAddress::ref(), and lldb_private::Address::Slide().
GetRangeIndexForBlockAddress()
uint32_t SBBlock::GetRangeIndexForBlockAddress (lldb::SBAddress block_addr)
Definition at line 231 of file SBBlock.cpp.
References lldb::SBAddress::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_ptr, lldb::SBAddress::ref(), and UINT32_MAX.
GetRanges()
lldb::SBAddressRangeList SBBlock::GetRanges ()
Definition at line 222 of file SBBlock.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and lldb::SBAddressRangeList::m_opaque_up.
GetRangeStartAddress()
lldb::SBAddress SBBlock::GetRangeStartAddress (uint32_t idx)
Definition at line 195 of file SBBlock.cpp.
References lldb_private::AddressRange::GetBaseAddress(), LLDB_INSTRUMENT_VA, m_opaque_ptr, and lldb::SBAddress::ref().
GetSibling()
SBBlock SBBlock::GetSibling ()
Definition at line 142 of file SBBlock.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBBlock().
GetVariables() [1/2]
lldb::SBValueList SBBlock::GetVariables (lldb::SBFrame & frame, bool arguments, bool locals, bool statics, lldb::DynamicValueType use_dynamic)
Definition at line 241 of file SBBlock.cpp.
References lldb::SBValueList::Append(), lldb::eNoDynamicValues, lldb::eValueTypeVariableArgument, lldb::eValueTypeVariableGlobal, lldb::eValueTypeVariableLocal, lldb::eValueTypeVariableStatic, lldb::eValueTypeVariableThreadLocal, lldb_private::Block::GetBlockVariableList(), lldb::SBFrame::GetFrameSP(), GetPtr(), LLDB_INSTRUMENT_VA, and lldb::SBValue::SetSP().
GetVariables() [2/2]
lldb::SBValueList SBBlock::GetVariables (lldb::SBTarget & target, bool arguments, bool locals, bool statics)
Definition at line 295 of file SBBlock.cpp.
References lldb::SBValueList::Append(), lldb_private::ValueObjectVariable::Create(), lldb::eValueTypeVariableArgument, lldb::eValueTypeVariableGlobal, lldb::eValueTypeVariableLocal, lldb::eValueTypeVariableStatic, lldb::eValueTypeVariableThreadLocal, lldb_private::Block::GetBlockVariableList(), GetPtr(), lldb::SBTarget::GetSP(), and LLDB_INSTRUMENT_VA.
IsInlined()
bool SBBlock::IsInlined () const
Definition at line 57 of file SBBlock.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
Referenced by GetDescription().
IsValid()
bool SBBlock::IsValid () const
Definition at line 47 of file SBBlock.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by AppendVariables().
operator bool()
SBBlock::operator bool () const explicit
Definition at line 51 of file SBBlock.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_ptr.
operator=()
const SBBlock & SBBlock::operator= (const lldb::SBBlock & rhs)
Definition at line 38 of file SBBlock.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_ptr, and SBBlock().
SetPtr()
void SBBlock::SetPtr (lldb_private::Block * lldb_object_ptr) private
Definition at line 162 of file SBBlock.cpp.
References m_opaque_ptr.
Referenced by lldb::SBAddress::GetBlock(), lldb::SBFunction::GetBlock(), and SBSymbolContext.
Friends And Related Symbol Documentation
SBAddress
friend class SBAddress friend
Definition at line 80 of file SBBlock.h.
References SBAddress.
Referenced by SBAddress.
SBFrame
friend class SBFrame friend
Definition at line 81 of file SBBlock.h.
References SBFrame.
Referenced by SBFrame.
SBFunction
friend class SBFunction friend
Definition at line 82 of file SBBlock.h.
References SBFunction.
Referenced by SBFunction.
SBSymbolContext
friend class SBSymbolContext friend
Definition at line 83 of file SBBlock.h.
References AppendVariables(), GetPtr(), SBBlock(), SBSymbolContext, and SetPtr().
Referenced by SBSymbolContext.
Member Data Documentation
m_opaque_ptr
lldb_private::Block* lldb::SBBlock::m_opaque_ptr = nullptr private
Definition at line 94 of file SBBlock.h.
Referenced by AppendVariables(), GetContainingInlinedBlock(), GetDescription(), GetFirstChild(), GetInlinedCallSiteColumn(), GetInlinedCallSiteFile(), GetInlinedCallSiteLine(), GetInlinedName(), GetNumRanges(), GetParent(), GetPtr(), GetRangeEndAddress(), GetRangeIndexForBlockAddress(), GetRanges(), GetRangeStartAddress(), GetSibling(), IsInlined(), operator bool(), operator=(), SBBlock(), SBBlock(), SetPtr(), and ~SBBlock().
The documentation for this class was generated from the following files:
SBBlock.h
SBBlock.cpp