LLDB: lldb_private::StructuredData::Object Class Reference
lldb_private::StructuredData::Object Class Reference abstract
#include <StructuredData.h>
Public Member Functions
Object (lldb::StructuredDataType t=lldb::eStructuredDataTypeInvalid)
virtual ~Object ()=default
virtual bool IsValid () const
virtual void Clear ()
lldb::StructuredDataType GetType () const
void SetType (lldb::StructuredDataType t)
Array * GetAsArray ()
Dictionary * GetAsDictionary ()
UnsignedInteger * GetAsUnsignedInteger ()
SignedInteger * GetAsSignedInteger ()
uint64_t GetUnsignedIntegerValue (uint64_t fail_value=0)
int64_t GetSignedIntegerValue (int64_t fail_value=0)
Float * GetAsFloat ()
double GetFloatValue (double fail_value=0.0)
Boolean * GetAsBoolean ()
bool GetBooleanValue (bool fail_value=false)
String * GetAsString ()
llvm::StringRef GetStringValue (const char *fail_value=nullptr)
Generic * GetAsGeneric ()
ObjectSP GetObjectForDotSeparatedPath (llvm::StringRef path)
void DumpToStdout (bool pretty_print=true) const
virtual void Serialize (llvm::json::OStream &s) const =0
void Dump (lldb_private::Stream &s, bool pretty_print=true) const
virtual void GetDescription (lldb_private::Stream &s) const
Private Attributes
lldb::StructuredDataType m_type
Detailed Description
Definition at line 78 of file StructuredData.h.
Constructor & Destructor Documentation
Object()
lldb_private::StructuredData::Object::Object (lldb::StructuredDataType t = lldb::eStructuredDataTypeInvalid) inline
Definition at line 80 of file StructuredData.h.
References lldb::eStructuredDataTypeInvalid, and m_type.
Referenced by lldb_private::StructuredData::Array::Array(), lldb_private::StructuredData::Boolean::Boolean(), lldb_private::StructuredData::Dictionary::Dictionary(), lldb_private::StructuredData::Dictionary::Dictionary(), lldb_private::StructuredData::Float::Float(), lldb_private::StructuredData::Array::ForEach(), lldb_private::StructuredData::Dictionary::ForEach(), lldb_private::StructuredData::Generic::Generic(), lldb_private::StructuredData::Integer< uint64_t >::Integer(), lldb_private::StructuredData::Null::Null(), lldb_private::StructuredData::String::String(), and lldb_private::StructuredData::String::String().
~Object()
virtual lldb_private::StructuredData::Object::~Object () virtual default
Member Function Documentation
Clear()
virtual void lldb_private::StructuredData::Object::Clear () inline virtual
Definition at line 87 of file StructuredData.h.
References lldb::eStructuredDataTypeInvalid, and m_type.
Dump()
void lldb_private::StructuredData::Object::Dump (lldb_private::Stream & s, bool pretty_print = true) const inline
Definition at line 178 of file StructuredData.h.
References lldb_private::Stream::AsRawOstream(), and Serialize().
Referenced by CommandObjectTargetModulesDumpSeparateDebugInfoFiles::DoExecute(), ObjectFileMachO::GetCorefileThreadExtraInfos(), GetDescription(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_jSignalsInfo(), and lldb_private::Target::SerializeBreakpointsToFile().
DumpToStdout()
void StructuredData::Object::DumpToStdout (bool pretty_print = true) const
Definition at line 138 of file StructuredData.cpp.
References lldb_private::Serialize().
Referenced by lldb_private::DynamicRegisterInfo::SetRegisterInfo().
GetAsArray()
Array * lldb_private::StructuredData::Object::GetAsArray () inline
Definition at line 93 of file StructuredData.h.
References lldb::eStructuredDataTypeArray, and m_type.
Referenced by CommandObjectScriptingObjectParsed::CommandObjectScriptingObjectParsed(), lldb_private::PlatformDarwin::ExtractAppSpecificInfo(), GetObjectForDotSeparatedPath(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsArray(), CommandObjectScriptingObjectParsed::CommandOptions::ParseUsageMaskFromArray(), CommandObjectScriptingObjectParsed::CommandOptions::SetOptionsFromArray(), and lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo().
GetAsBoolean()
Boolean * lldb_private::StructuredData::Object::GetAsBoolean () inline
Definition at line 141 of file StructuredData.h.
References lldb::eStructuredDataTypeBoolean, and m_type.
Referenced by GetBooleanValue(), and lldb_private::StructuredData::Dictionary::GetValueForKeyAsBoolean().
GetAsDictionary()
Dictionary * lldb_private::StructuredData::Object::GetAsDictionary () inline
Definition at line 99 of file StructuredData.h.
References lldb::eStructuredDataTypeDictionary, and m_type.
Referenced by CommandObjectScriptingObjectParsed::CommandObjectScriptingObjectParsed(), CommandObjectTargetModulesDumpSeparateDebugInfoFiles::DoExecute(), dump(), DumpDwoFilesTable(), DumpOsoFilesTable(), GenerateThreadName(), ObjectFileMachO::GetCorefileThreadExtraInfos(), SystemRuntimeMacOSX::GetExtendedBacktraceThread(), lldb_private::ScriptedProcess::GetLoadedDynamicLibrariesInfos(), GetObjectForDotSeparatedPath(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsDictionary(), lldb_private::RegisterContextUnifiedCore::RegisterContextUnifiedCore(), CommandObjectScriptingObjectParsed::CommandOptions::SetOptionsFromArray(), lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo(), and lldb_private::process_gdb_remote::ProcessGDBRemote::UpdateThreadIDList().
GetAsFloat()
Float * lldb_private::StructuredData::Object::GetAsFloat () inline
Definition at line 130 of file StructuredData.h.
References lldb::eStructuredDataTypeFloat, and m_type.
Referenced by GetFloatValue().
GetAsGeneric()
Generic * lldb_private::StructuredData::Object::GetAsGeneric () inline
Definition at line 166 of file StructuredData.h.
References lldb::eStructuredDataTypeGeneric, and m_type.
GetAsSignedInteger()
SignedInteger * lldb_private::StructuredData::Object::GetAsSignedInteger () inline
Definition at line 114 of file StructuredData.h.
References lldb::eStructuredDataTypeSignedInteger, and m_type.
Referenced by GetSignedIntegerValue().
GetAsString()
String * lldb_private::StructuredData::Object::GetAsString () inline
Definition at line 152 of file StructuredData.h.
References lldb::eStructuredDataTypeString, and m_type.
Referenced by GetStringValue().
GetAsUnsignedInteger()
UnsignedInteger * lldb_private::StructuredData::Object::GetAsUnsignedInteger () inline
Definition at line 105 of file StructuredData.h.
References lldb::eStructuredDataTypeInteger, lldb::eStructuredDataTypeUnsignedInteger, and m_type.
Referenced by GetUnsignedIntegerValue().
GetBooleanValue()
bool lldb_private::StructuredData::Object::GetBooleanValue (bool fail_value = false) inline
Definition at line 147 of file StructuredData.h.
References GetAsBoolean(), and lldb_private::StructuredData::Boolean::GetValue().
GetDescription()
virtual void lldb_private::StructuredData::Object::GetDescription (lldb_private::Stream & s) const inline virtual
Reimplemented in lldb_private::StructuredData::Array, lldb_private::StructuredData::Boolean, lldb_private::StructuredData::Dictionary, lldb_private::StructuredData::Float, lldb_private::StructuredData::Generic, lldb_private::StructuredData::Integer< N >, lldb_private::StructuredData::Integer< int64_t >, lldb_private::StructuredData::Integer< uint64_t >, lldb_private::StructuredData::Null, and lldb_private::StructuredData::String.
Definition at line 183 of file StructuredData.h.
References Dump(), lldb_private::Stream::IndentLess(), and lldb_private::Stream::IndentMore().
GetFloatValue()
double lldb_private::StructuredData::Object::GetFloatValue (double fail_value = 0.0) inline
Definition at line 136 of file StructuredData.h.
References GetAsFloat(), and lldb_private::StructuredData::Float::GetValue().
GetObjectForDotSeparatedPath()
StructuredData::ObjectSP StructuredData::Object::GetObjectForDotSeparatedPath (llvm::StringRef path)
Definition at line 107 of file StructuredData.cpp.
References lldb::eStructuredDataTypeArray, lldb::eStructuredDataTypeDictionary, GetAsArray(), GetAsDictionary(), lldb_private::StructuredData::Array::GetItemAtIndex(), GetType(), and lldb_private::StructuredData::Dictionary::GetValueForKey().
Referenced by AddThreadsForPath(), GenerateThreadName(), lldb_private::InstrumentationRuntimeTSan::GetMainRacyAddress(), and lldb_private::InstrumentationRuntimeTSan::NotifyBreakpointHit().
GetSignedIntegerValue()
int64_t lldb_private::StructuredData::Object::GetSignedIntegerValue (int64_t fail_value = 0) inline
Definition at line 125 of file StructuredData.h.
References GetAsSignedInteger(), and integer.
GetStringValue()
llvm::StringRef lldb_private::StructuredData::Object::GetStringValue (const char * fail_value = nullptr) inline
Definition at line 158 of file StructuredData.h.
References GetAsString(), and lldb_private::StructuredData::String::GetValue().
GetType()
lldb::StructuredDataType lldb_private::StructuredData::Object::GetType () const inline
Definition at line 89 of file StructuredData.h.
References m_type.
Referenced by GetObjectForDotSeparatedPath().
GetUnsignedIntegerValue()
uint64_t lldb_private::StructuredData::Object::GetUnsignedIntegerValue (uint64_t fail_value = 0) inline
Definition at line 120 of file StructuredData.h.
References GetAsUnsignedInteger(), and integer.
Referenced by lldb_private::InstrumentationRuntimeMainThreadChecker::GetBacktracesFromExtendedStopInfo(), and lldb_private::InstrumentationRuntimeUBSan::GetBacktracesFromExtendedStopInfo().
IsValid()
virtual bool lldb_private::StructuredData::Object::IsValid () const inline virtual
Reimplemented in lldb_private::python::StructuredPythonObject, lldb_private::StructuredData::Generic, and lldb_private::StructuredData::Null.
Definition at line 85 of file StructuredData.h.
Referenced by lldb_private::Breakpoint::CreateFromStructuredData(), lldb_private::BreakpointResolver::CreateFromStructuredData(), lldb_private::SearchFilter::CreateFromStructuredData(), and lldb_private::Target::StopHookScripted::GetSubclassDescription().
Serialize()
virtual void lldb_private::StructuredData::Object::Serialize (llvm::json::OStream & s) const pure virtual
Implemented in lldb_private::python::StructuredPythonObject, lldb_private::StructuredData::Array, lldb_private::StructuredData::Boolean, lldb_private::StructuredData::Dictionary, lldb_private::StructuredData::Float, lldb_private::StructuredData::Generic, lldb_private::StructuredData::Integer< N >, lldb_private::StructuredData::Integer< int64_t >, lldb_private::StructuredData::Integer< uint64_t >, lldb_private::StructuredData::Null, and lldb_private::StructuredData::String.
Referenced by Dump().
SetType()
void lldb_private::StructuredData::Object::SetType (lldb::StructuredDataType t) inline
Definition at line 91 of file StructuredData.h.
References m_type.
Member Data Documentation
m_type
lldb::StructuredDataType lldb_private::StructuredData::Object::m_type private
Definition at line 190 of file StructuredData.h.
Referenced by Clear(), GetAsArray(), GetAsBoolean(), GetAsDictionary(), GetAsFloat(), GetAsGeneric(), GetAsSignedInteger(), GetAsString(), GetAsUnsignedInteger(), GetType(), Object(), and SetType().
The documentation for this class was generated from the following files:
StructuredData.h
StructuredData.cpp