LLDB: lldb::SBBreakpoint Class Reference
lldb::SBBreakpoint Class Reference
#include <SBBreakpoint.h>
Public Member Functions
SBBreakpoint ()
SBBreakpoint (const lldb::SBBreakpoint &rhs)
~SBBreakpoint ()
const lldb::SBBreakpoint & operator= (const lldb::SBBreakpoint &rhs)
bool operator== (const lldb::SBBreakpoint &rhs)
bool operator!= (const lldb::SBBreakpoint &rhs)
break_id_t GetID () const
operator bool () const
bool IsValid () const
void ClearAllBreakpointSites ()
lldb::SBTarget GetTarget () const
lldb::SBBreakpointLocation FindLocationByAddress (lldb::addr_t vm_addr)
lldb::break_id_t FindLocationIDByAddress (lldb::addr_t vm_addr)
lldb::SBBreakpointLocation FindLocationByID (lldb::break_id_t bp_loc_id)
lldb::SBBreakpointLocation GetLocationAtIndex (uint32_t index)
void SetEnabled (bool enable)
bool IsEnabled ()
void SetOneShot (bool one_shot)
bool IsOneShot () const
bool IsInternal ()
uint32_t GetHitCount () const
void SetIgnoreCount (uint32_t count)
uint32_t GetIgnoreCount () const
void SetCondition (const char *condition)
const char * GetCondition ()
void SetAutoContinue (bool auto_continue)
bool GetAutoContinue ()
void SetThreadID (lldb::tid_t sb_thread_id)
lldb::tid_t GetThreadID ()
void SetThreadIndex (uint32_t index)
uint32_t GetThreadIndex () const
void SetThreadName (const char *thread_name)
const char * GetThreadName () const
void SetQueueName (const char *queue_name)
const char * GetQueueName () const
void SetCallback (SBBreakpointHitCallback callback, void *baton)
void SetScriptCallbackFunction (const char *callback_function_name)
SBError SetScriptCallbackFunction (const char *callback_function_name, SBStructuredData &extra_args)
void SetCommandLineCommands (SBStringList &commands)
bool GetCommandLineCommands (SBStringList &commands)
SBError SetScriptCallbackBody (const char *script_body_text)
LLDB_DEPRECATED_FIXME ("Doesn't provide error handling", "AddNameWithErrorHandling") bool AddName(const char *new_name)
SBError AddNameWithErrorHandling (const char *new_name)
void RemoveName (const char *name_to_remove)
bool MatchesName (const char *name)
void GetNames (SBStringList &names)
size_t GetNumResolvedLocations () const
size_t GetNumLocations () const
bool GetDescription (lldb::SBStream &description)
bool GetDescription (lldb::SBStream &description, bool include_locations)
bool IsHardware () const
lldb::SBError SetIsHardware (bool is_hardware)
Make this breakpoint a hardware breakpoint.
SBError AddLocation (SBAddress &address)
Adds a location to the breakpoint at the address passed in.
SBBreakpointLocation AddFacadeLocation ()
Add a "Facade location" to the breakpoint.
SBStructuredData SerializeToStructuredData ()
Static Public Member Functions
static bool EventIsBreakpointEvent (const lldb::SBEvent &event)
static lldb::BreakpointEventType GetBreakpointEventTypeFromEvent (const lldb::SBEvent &event)
static lldb::SBBreakpoint GetBreakpointFromEvent (const lldb::SBEvent &event)
static lldb::SBBreakpointLocation GetBreakpointLocationAtIndexFromEvent (const lldb::SBEvent &event, uint32_t loc_idx)
static uint32_t GetNumBreakpointLocationsFromEvent (const lldb::SBEvent &event_sp)
Private Member Functions
SBBreakpoint (const lldb::BreakpointSP &bp_sp)
lldb::BreakpointSP GetSP () const
Private Attributes
lldb::BreakpointWP m_opaque_wp
Friends
class SBBreakpointList
class SBBreakpointLocation
class SBBreakpointName
class SBTarget
class lldb_private::ScriptInterpreter
class lldb_private::python::SWIGBridge
Detailed Description
Definition at line 25 of file SBBreakpoint.h.
Constructor & Destructor Documentation
SBBreakpoint() [1/3]
SBBreakpoint::SBBreakpoint ()
Definition at line 47 of file SBBreakpoint.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by GetBreakpointFromEvent(), LLDB_DEPRECATED_FIXME(), lldb_private::python::SWIGBridge, operator=(), and SBBreakpoint().
SBBreakpoint() [2/3]
SBBreakpoint::SBBreakpoint (const lldb::SBBreakpoint & rhs)
Definition at line 49 of file SBBreakpoint.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_wp, and SBBreakpoint().
~SBBreakpoint()
SBBreakpoint::~SBBreakpoint () default
References ClearAllBreakpointSites(), FindLocationByAddress(), FindLocationByID(), FindLocationIDByAddress(), GetAutoContinue(), GetCommandLineCommands(), GetCondition(), GetHitCount(), GetID(), GetIgnoreCount(), GetLocationAtIndex(), GetQueueName(), GetTarget(), GetThreadID(), GetThreadIndex(), GetThreadName(), IsEnabled(), IsInternal(), IsOneShot(), IsValid(), operator!=(), operator=(), operator==(), SetAutoContinue(), SetCallback(), SetCommandLineCommands(), SetCondition(), SetEnabled(), SetIgnoreCount(), SetOneShot(), SetQueueName(), SetScriptCallbackBody(), SetScriptCallbackFunction(), SetThreadID(), SetThreadIndex(), and SetThreadName().
SBBreakpoint() [3/3]
SBBreakpoint::SBBreakpoint (const lldb::BreakpointSP & bp_sp) private
Definition at line 54 of file SBBreakpoint.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_wp.
Member Function Documentation
AddFacadeLocation()
SBBreakpointLocation SBBreakpoint::AddFacadeLocation ()
Add a "Facade location" to the breakpoint.
This returns the Facade Location that was added, which you can then use in get_location_description and was_hit in your breakpoint resolver. Can only be called from a ScriptedBreakpointResolver.
Definition at line 577 of file SBBreakpoint.cpp.
References GetSP(), and SBBreakpointLocation.
Referenced by LLDB_DEPRECATED_FIXME().
AddLocation()
SBError SBBreakpoint::AddLocation (SBAddress & address)
Adds a location to the breakpoint at the address passed in.
Can only be called from a ScriptedBreakpointResolver...
Definition at line 543 of file SBBreakpoint.cpp.
References lldb_private::Address::Dump(), lldb_private::Address::DumpStyleModuleWithFileAddress, error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb::SBAddress::get(), lldb_private::StreamString::GetData(), GetSP(), lldb::SBAddress::IsValid(), LLDB_INSTRUMENT_VA, and lldb::SBAddress::ref().
Referenced by LLDB_DEPRECATED_FIXME().
AddNameWithErrorHandling()
SBError SBBreakpoint::AddNameWithErrorHandling (const char * new_name)
Definition at line 678 of file SBBreakpoint.cpp.
References error(), lldb_private::Status::FromErrorString(), GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBError::SetError().
Referenced by LLDB_DEPRECATED_FIXME().
ClearAllBreakpointSites()
void SBBreakpoint::ClearAllBreakpointSites ()
Definition at line 117 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
EventIsBreakpointEvent()
bool SBBreakpoint::EventIsBreakpointEvent (const lldb::SBEvent & event) static
Definition at line 740 of file SBBreakpoint.cpp.
References lldb::SBEvent::get(), lldb_private::Breakpoint::BreakpointEventData::GetEventDataFromEvent(), and LLDB_INSTRUMENT_VA.
Referenced by LLDB_DEPRECATED_FIXME().
FindLocationByAddress()
SBBreakpointLocation SBBreakpoint::FindLocationByAddress (lldb::addr_t vm_addr)
Definition at line 128 of file SBBreakpoint.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, LLDB_INVALID_ADDRESS, lldb_private::Target::ResolveLoadAddress(), SBBreakpointLocation, lldb::SBBreakpointLocation::SetLocation(), and lldb_private::Address::SetRawAddress().
Referenced by ~SBBreakpoint().
FindLocationByID()
SBBreakpointLocation SBBreakpoint::FindLocationByID (lldb::break_id_t bp_loc_id)
Definition at line 169 of file SBBreakpoint.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, SBBreakpointLocation, and lldb::SBBreakpointLocation::SetLocation().
Referenced by ~SBBreakpoint().
FindLocationIDByAddress()
break_id_t SBBreakpoint::FindLocationIDByAddress (lldb::addr_t vm_addr)
Definition at line 149 of file SBBreakpoint.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, LLDB_INVALID_ADDRESS, LLDB_INVALID_BREAK_ID, lldb_private::Target::ResolveLoadAddress(), and lldb_private::Address::SetRawAddress().
Referenced by ~SBBreakpoint().
GetAutoContinue()
bool SBBreakpoint::GetAutoContinue ()
Definition at line 312 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
GetBreakpointEventTypeFromEvent()
BreakpointEventType SBBreakpoint::GetBreakpointEventTypeFromEvent (const lldb::SBEvent & event) static
Definition at line 748 of file SBBreakpoint.cpp.
References lldb_private::Breakpoint::BreakpointEventData::GetBreakpointEventTypeFromEvent(), lldb::SBEvent::GetSP(), lldb::SBEvent::IsValid(), and LLDB_INSTRUMENT_VA.
Referenced by LLDB_DEPRECATED_FIXME().
GetBreakpointFromEvent()
SBBreakpoint SBBreakpoint::GetBreakpointFromEvent (const lldb::SBEvent & event) static
Definition at line 757 of file SBBreakpoint.cpp.
References lldb_private::Breakpoint::BreakpointEventData::GetBreakpointFromEvent(), lldb::SBEvent::GetSP(), lldb::SBEvent::IsValid(), LLDB_INSTRUMENT_VA, and SBBreakpoint().
Referenced by LLDB_DEPRECATED_FIXME().
GetBreakpointLocationAtIndexFromEvent()
SBBreakpointLocation SBBreakpoint::GetBreakpointLocationAtIndexFromEvent (const lldb::SBEvent & event, uint32_t loc_idx) static
Definition at line 767 of file SBBreakpoint.cpp.
References lldb_private::Breakpoint::BreakpointEventData::GetBreakpointLocationAtIndexFromEvent(), lldb::SBEvent::GetSP(), lldb::SBEvent::IsValid(), LLDB_INSTRUMENT_VA, SBBreakpointLocation, and lldb::SBBreakpointLocation::SetLocation().
Referenced by LLDB_DEPRECATED_FIXME().
GetCommandLineCommands()
bool SBBreakpoint::GetCommandLineCommands (SBStringList & commands)
Definition at line 503 of file SBBreakpoint.cpp.
References lldb::SBStringList::AppendList(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
GetCondition()
const char * SBBreakpoint::GetCondition ()
Definition at line 286 of file SBBreakpoint.cpp.
References lldb_private::ConstString::GetCString(), GetSP(), lldb_private::StopCondition::GetText(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
GetDescription() [1/2]
bool SBBreakpoint::GetDescription (lldb::SBStream & description)
Definition at line 517 of file SBBreakpoint.cpp.
References GetDescription(), and LLDB_INSTRUMENT_VA.
Referenced by GetDescription(), and LLDB_DEPRECATED_FIXME().
GetDescription() [2/2]
bool SBBreakpoint::GetDescription (lldb::SBStream & description, bool include_locations)
Definition at line 523 of file SBBreakpoint.cpp.
References lldb::SBStream::get(), GetSP(), and LLDB_INSTRUMENT_VA.
GetHitCount()
uint32_t SBBreakpoint::GetHitCount () const
Definition at line 324 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
GetID()
break_id_t SBBreakpoint::GetID () const
Definition at line 90 of file SBBreakpoint.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and LLDB_INVALID_BREAK_ID.
Referenced by ~SBBreakpoint().
GetIgnoreCount()
uint32_t SBBreakpoint::GetIgnoreCount () const
Definition at line 338 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
GetLocationAtIndex()
SBBreakpointLocation SBBreakpoint::GetLocationAtIndex (uint32_t index)
Definition at line 184 of file SBBreakpoint.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, SBBreakpointLocation, and lldb::SBBreakpointLocation::SetLocation().
Referenced by ~SBBreakpoint().
GetNames()
void SBBreakpoint::GetNames (SBStringList & names)
Definition at line 724 of file SBBreakpoint.cpp.
References lldb::SBStringList::AppendString(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by LLDB_DEPRECATED_FIXME().
GetNumBreakpointLocationsFromEvent()
uint32_t SBBreakpoint::GetNumBreakpointLocationsFromEvent (const lldb::SBEvent & event_sp) static
Definition at line 780 of file SBBreakpoint.cpp.
References lldb_private::Breakpoint::BreakpointEventData::GetNumBreakpointLocationsFromEvent(), lldb::SBEvent::GetSP(), lldb::SBEvent::IsValid(), and LLDB_INSTRUMENT_VA.
Referenced by LLDB_DEPRECATED_FIXME().
GetNumLocations()
size_t SBBreakpoint::GetNumLocations () const
Definition at line 473 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by LLDB_DEPRECATED_FIXME().
GetNumResolvedLocations()
size_t SBBreakpoint::GetNumResolvedLocations () const
Definition at line 460 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by LLDB_DEPRECATED_FIXME().
GetQueueName()
const char * SBBreakpoint::GetQueueName () const
Definition at line 444 of file SBBreakpoint.cpp.
References lldb_private::ConstString::GetCString(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
GetSP()
BreakpointSP SBBreakpoint::GetSP () const private
Definition at line 812 of file SBBreakpoint.cpp.
References m_opaque_wp.
Referenced by AddFacadeLocation(), AddLocation(), AddNameWithErrorHandling(), lldb::SBBreakpointList::AppendIfUnique(), ClearAllBreakpointSites(), FindLocationByAddress(), FindLocationByID(), FindLocationIDByAddress(), GetAutoContinue(), GetCommandLineCommands(), GetCondition(), GetDescription(), GetHitCount(), GetID(), GetIgnoreCount(), GetLocationAtIndex(), GetNames(), GetNumLocations(), GetNumResolvedLocations(), GetQueueName(), GetTarget(), GetThreadID(), GetThreadIndex(), GetThreadName(), IsEnabled(), IsHardware(), IsInternal(), IsOneShot(), lldb_private::python::SWIGBridge, MatchesName(), operator bool(), RemoveName(), lldb::SBBreakpointName::SBBreakpointName(), SerializeToStructuredData(), SetAutoContinue(), SetCallback(), SetCommandLineCommands(), SetCondition(), SetEnabled(), SetIgnoreCount(), SetIsHardware(), SetOneShot(), SetQueueName(), SetScriptCallbackBody(), SetScriptCallbackFunction(), SetThreadID(), SetThreadIndex(), and SetThreadName().
GetTarget()
SBTarget SBBreakpoint::GetTarget () const
Definition at line 80 of file SBBreakpoint.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and SBTarget.
Referenced by ~SBBreakpoint().
GetThreadID()
lldb::tid_t SBBreakpoint::GetThreadID ()
Definition at line 363 of file SBBreakpoint.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and LLDB_INVALID_THREAD_ID.
Referenced by ~SBBreakpoint().
GetThreadIndex()
uint32_t SBBreakpoint::GetThreadIndex () const
Definition at line 388 of file SBBreakpoint.cpp.
References lldb_private::ThreadSpec::GetIndex(), GetSP(), LLDB_INSTRUMENT_VA, and UINT32_MAX.
Referenced by ~SBBreakpoint().
GetThreadName()
const char * SBBreakpoint::GetThreadName () const
Definition at line 417 of file SBBreakpoint.cpp.
References lldb_private::ConstString::GetCString(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
IsEnabled()
bool SBBreakpoint::IsEnabled ()
Definition at line 211 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
IsHardware()
bool SBBreakpoint::IsHardware () const
Definition at line 791 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by LLDB_DEPRECATED_FIXME().
IsInternal()
bool SBBreakpoint::IsInternal ()
Definition at line 247 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
IsOneShot()
bool SBBreakpoint::IsOneShot () const
Definition at line 235 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
IsValid()
bool SBBreakpoint::IsValid () const
Definition at line 101 of file SBBreakpoint.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBBreakpointList::Append(), lldb::SBBreakpointList::AppendIfUnique(), lldb::SBBreakpointName::SBBreakpointName(), and ~SBBreakpoint().
LLDB_DEPRECATED_FIXME()
lldb::SBBreakpoint::LLDB_DEPRECATED_FIXME ("Doesn't provide error handling" , "AddNameWithErrorHandling") const
References AddFacadeLocation(), AddLocation(), AddNameWithErrorHandling(), EventIsBreakpointEvent(), GetBreakpointEventTypeFromEvent(), GetBreakpointFromEvent(), GetBreakpointLocationAtIndexFromEvent(), GetDescription(), GetNames(), GetNumBreakpointLocationsFromEvent(), GetNumLocations(), GetNumResolvedLocations(), IsHardware(), MatchesName(), RemoveName(), SBBreakpoint(), SBBreakpointLocation, SerializeToStructuredData(), and SetIsHardware().
MatchesName()
bool SBBreakpoint::MatchesName (const char * name)
Definition at line 710 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by LLDB_DEPRECATED_FIXME().
operator bool()
SBBreakpoint::operator bool () const explicit
Definition at line 105 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
operator!=()
bool SBBreakpoint::operator!= (const lldb::SBBreakpoint & rhs)
Definition at line 74 of file SBBreakpoint.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_wp.
Referenced by ~SBBreakpoint().
operator=()
const SBBreakpoint & SBBreakpoint::operator= (const lldb::SBBreakpoint & rhs)
Definition at line 61 of file SBBreakpoint.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_wp, and SBBreakpoint().
Referenced by ~SBBreakpoint().
operator==()
bool SBBreakpoint::operator== (const lldb::SBBreakpoint & rhs)
Definition at line 68 of file SBBreakpoint.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_wp.
Referenced by ~SBBreakpoint().
RemoveName()
void SBBreakpoint::RemoveName (const char * name_to_remove)
Definition at line 697 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by LLDB_DEPRECATED_FIXME().
SerializeToStructuredData()
SBStructuredData SBBreakpoint::SerializeToStructuredData ()
Definition at line 586 of file SBBreakpoint.cpp.
References GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBStructuredData::m_impl_up.
Referenced by LLDB_DEPRECATED_FIXME().
SetAutoContinue()
void SBBreakpoint::SetAutoContinue (bool auto_continue)
Definition at line 301 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
SetCallback()
void SBBreakpoint::SetCallback (SBBreakpointHitCallback callback, void * baton)
Definition at line 600 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
SetCommandLineCommands()
void SBBreakpoint::SetCommandLineCommands (SBStringList & commands)
Definition at line 486 of file SBBreakpoint.cpp.
References lldb::eScriptLanguageNone, lldb::SBStringList::GetSize(), GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
SetCondition()
void SBBreakpoint::SetCondition (const char * condition)
Definition at line 271 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
SetEnabled()
void SBBreakpoint::SetEnabled (bool enable)
Definition at line 199 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
SetIgnoreCount()
void SBBreakpoint::SetIgnoreCount (uint32_t count)
Definition at line 259 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
SetIsHardware()
lldb::SBError SBBreakpoint::SetIsHardware (bool is_hardware)
Make this breakpoint a hardware breakpoint.
This will replace all existing breakpoint locations with hardware breakpoints. Returns an error if this fails, e.g. when there aren't enough hardware resources available.
Definition at line 800 of file SBBreakpoint.cpp.
References lldb_private::Status::FromError(), GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBError.
Referenced by LLDB_DEPRECATED_FIXME().
SetOneShot()
void SBBreakpoint::SetOneShot (bool one_shot)
Definition at line 223 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
SetQueueName()
void SBBreakpoint::SetQueueName (const char * queue_name)
Definition at line 433 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
SetScriptCallbackBody()
SBError SBBreakpoint::SetScriptCallbackBody (const char * script_body_text)
Definition at line 648 of file SBBreakpoint.cpp.
References error(), lldb_private::Status::FromErrorString(), GetSP(), LLDB_INSTRUMENT_VA, and lldb::SBError::SetError().
Referenced by ~SBBreakpoint().
SetScriptCallbackFunction() [1/2]
void SBBreakpoint::SetScriptCallbackFunction (const char * callback_function_name)
Definition at line 615 of file SBBreakpoint.cpp.
References LLDB_INSTRUMENT_VA, and SetScriptCallbackFunction().
Referenced by SetScriptCallbackFunction(), and ~SBBreakpoint().
SetScriptCallbackFunction() [2/2]
SBError SBBreakpoint::SetScriptCallbackFunction (const char * callback_function_name, SBStructuredData & extra_args)
Definition at line 622 of file SBBreakpoint.cpp.
References error(), lldb_private::Status::FromErrorString(), GetSP(), LLDB_INSTRUMENT_VA, lldb::SBStructuredData::m_impl_up, and lldb::SBError::SetError().
SetThreadID()
void SBBreakpoint::SetThreadID (lldb::tid_t sb_thread_id)
Definition at line 352 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
SetThreadIndex()
void SBBreakpoint::SetThreadIndex (uint32_t index)
Definition at line 377 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
SetThreadName()
void SBBreakpoint::SetThreadName (const char * thread_name)
Definition at line 405 of file SBBreakpoint.cpp.
References GetSP(), and LLDB_INSTRUMENT_VA.
Referenced by ~SBBreakpoint().
Friends And Related Symbol Documentation
lldb_private::python::SWIGBridge
friend class lldb_private::python::SWIGBridge friend
Definition at line 175 of file SBBreakpoint.h.
References GetSP(), lldb_private::python::SWIGBridge, and SBBreakpoint().
Referenced by lldb_private::python::SWIGBridge.
lldb_private::ScriptInterpreter
friend class lldb_private::ScriptInterpreter friend
Definition at line 174 of file SBBreakpoint.h.
References lldb_private::ScriptInterpreter.
Referenced by lldb_private::ScriptInterpreter.
SBBreakpointList
friend class SBBreakpointList friend
Definition at line 169 of file SBBreakpoint.h.
References SBBreakpointList.
Referenced by SBBreakpointList.
SBBreakpointLocation
friend class SBBreakpointLocation friend
Definition at line 170 of file SBBreakpoint.h.
References SBBreakpointLocation.
Referenced by AddFacadeLocation(), FindLocationByAddress(), FindLocationByID(), GetBreakpointLocationAtIndexFromEvent(), GetLocationAtIndex(), LLDB_DEPRECATED_FIXME(), and SBBreakpointLocation.
SBBreakpointName
friend class SBBreakpointName friend
Definition at line 171 of file SBBreakpoint.h.
References SBBreakpointName.
Referenced by SBBreakpointName.
SBTarget
friend class SBTarget friend
Definition at line 172 of file SBBreakpoint.h.
References SBTarget.
Referenced by GetTarget(), and SBTarget.
Member Data Documentation
m_opaque_wp
lldb::BreakpointWP lldb::SBBreakpoint::m_opaque_wp private
Definition at line 181 of file SBBreakpoint.h.
Referenced by lldb::SBBreakpointList::Append(), lldb_private::ScriptInterpreter::GetOpaqueTypeFromSBBreakpoint(), GetSP(), operator!=(), operator=(), operator==(), SBBreakpoint(), and SBBreakpoint().
The documentation for this class was generated from the following files:
SBBreakpoint.h
SBBreakpoint.cpp