LLDB: lldb_private::ZipFileResolver Class Reference
lldb_private::ZipFileResolver Class Reference
In Android API level 23 and above, bionic dynamic linker is able to load .so file directly from APK or .zip file.
#include <ZipFileResolver.h>
Public Types
enum FileKind { eFileKindInvalid = 0 , eFileKindNormal , eFileKindZip }
Static Public Member Functions
static bool ResolveSharedLibraryPath (const FileSpec &file_spec, FileKind &file_kind, std::string &file_path, lldb::offset_t &so_file_offset, lldb::offset_t &so_file_size)
Detailed Description
In Android API level 23 and above, bionic dynamic linker is able to load .so file directly from APK or .zip file.
This is a utility class to resolve the file spec in order to get the zip path and the .so file offset and size if the file spec contains "zip_path!/so_path". https://android.googlesource.com/platform/bionic/+/master/ android-changes-for-ndk-developers.md# opening-shared-libraries-directly-from-an-apk
Definition at line 23 of file ZipFileResolver.h.
Member Enumeration Documentation
FileKind
enum lldb_private::ZipFileResolver::FileKind
Enumerator
eFileKindInvalid
eFileKindNormal
eFileKindZip
Definition at line 25 of file ZipFileResolver.h.
Member Function Documentation
ResolveSharedLibraryPath()
bool ZipFileResolver::ResolveSharedLibraryPath (const FileSpec & file_spec, FileKind & file_kind, std::string & file_path, lldb::offset_t & so_file_offset, lldb::offset_t & so_file_size) static
Definition at line 18 of file ZipFileResolver.cpp.
References lldb_private::FileSystem::CreateDataBuffer(), eFileKindNormal, eFileKindZip, lldb_private::ZipFile::Find(), lldb_private::FileSystem::GetByteSize(), lldb_private::FileSpec::GetPath(), and lldb_private::FileSystem::Instance().
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::GetModuleInfo().
The documentation for this class was generated from the following files:
ZipFileResolver.h
ZipFileResolver.cpp