LLDB: EHProgramRange Class Reference
EHProgramRange Class Reference
Public Member Functions
EHProgramRange (EHProgram::const_iterator begin, EHProgram::const_iterator end)
UnwindPlan::Row BuildUnwindPlanRow () const
Private Member Functions
int32_t GetCFAFrameOffset () const
Private Attributes
EHProgram::const_iterator m_begin
EHProgram::const_iterator m_end
Detailed Description
Definition at line 349 of file PECallFrameInfo.cpp.
Constructor & Destructor Documentation
EHProgramRange()
EHProgramRange::EHProgramRange (EHProgram::const_iterator begin, EHProgram::const_iterator end)
Definition at line 363 of file PECallFrameInfo.cpp.
References m_begin, and m_end.
Member Function Documentation
BuildUnwindPlanRow()
UnwindPlan::Row EHProgramRange::BuildUnwindPlanRow () const
Definition at line 367 of file PECallFrameInfo.cpp.
References EHInstruction::ALLOCATE, GetCFAFrameOffset(), lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::lldb_rsp_x86_64, m_begin, m_end, EHInstruction::PUSH_REGISTER, EHInstruction::SAVE_REGISTER, EHInstruction::SET_FRAME_POINTER_REGISTER, lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), lldb_private::UnwindPlan::Row::SetOffset(), lldb_private::UnwindPlan::Row::SetRegisterLocationToAtCFAPlusOffset(), and lldb_private::UnwindPlan::Row::SetRegisterLocationToIsCFAPlusOffset().
Referenced by PECallFrameInfo::GetUnwindPlan().
GetCFAFrameOffset()
int32_t EHProgramRange::GetCFAFrameOffset () const private
Definition at line 418 of file PECallFrameInfo.cpp.
References EHInstruction::ALLOCATE, m_begin, m_end, and EHInstruction::PUSH_REGISTER.
Referenced by BuildUnwindPlanRow().
Member Data Documentation
m_begin
EHProgram::const_iterator EHProgramRange::m_begin private
Definition at line 359 of file PECallFrameInfo.cpp.
Referenced by BuildUnwindPlanRow(), EHProgramRange(), and GetCFAFrameOffset().
m_end
EHProgram::const_iterator EHProgramRange::m_end private
Definition at line 360 of file PECallFrameInfo.cpp.
Referenced by BuildUnwindPlanRow(), EHProgramRange(), and GetCFAFrameOffset().
The documentation for this class was generated from the following file:
PECallFrameInfo.cpp