LLDB: lldb_private::npdb::SymbolFileNativePDB Class Reference
lldb_private::npdb::SymbolFileNativePDB Class Reference
#include <SymbolFileNativePDB.h>
Classes
struct InlineSite
struct LineTableEntryComparator
struct UdtDeclaration
Public Member Functions
SymbolFileNativePDB (lldb::ObjectFileSP objfile_sp)
~SymbolFileNativePDB () override
uint32_t CalculateAbilities () override
void InitializeObject () override
Initialize the SymbolFile object.
uint64_t GetDebugInfoSize (bool load_all_debug_info=false) override
Metrics gathering functions.
void ParseDeclsForContext (lldb_private::CompilerDeclContext decl_ctx) override
lldb::LanguageType ParseLanguage (lldb_private::CompileUnit &comp_unit) override
size_t ParseFunctions (lldb_private::CompileUnit &comp_unit) override
bool ParseLineTable (lldb_private::CompileUnit &comp_unit) override
bool ParseDebugMacros (lldb_private::CompileUnit &comp_unit) override
bool ParseSupportFiles (lldb_private::CompileUnit &comp_unit, SupportFileList &support_files) override
size_t ParseTypes (lldb_private::CompileUnit &comp_unit) override
bool ParseImportedModules (const SymbolContext &sc, std::vector< lldb_private::SourceModule > &imported_modules) override
size_t ParseBlocksRecursive (Function &func) override
void FindGlobalVariables (ConstString name, const CompilerDeclContext &parent_decl_ctx, uint32_t max_matches, VariableList &variables) override
size_t ParseVariablesForContext (const SymbolContext &sc) override
void AddSymbols (Symtab &symtab) override
CompilerDecl GetDeclForUID (lldb::user_id_t uid) override
CompilerDeclContext GetDeclContextForUID (lldb::user_id_t uid) override
CompilerDeclContext GetDeclContextContainingUID (lldb::user_id_t uid) override
Type * ResolveTypeUID (lldb::user_id_t type_uid) override
std::optional< ArrayInfo > GetDynamicArrayInfoForUID (lldb::user_id_t type_uid, const lldb_private::ExecutionContext *exe_ctx) override
If type_uid points to an array type, return its characteristics.
bool CompleteType (CompilerType &compiler_type) override
uint32_t ResolveSymbolContext (const Address &so_addr, lldb::SymbolContextItem resolve_scope, SymbolContext &sc) override
uint32_t ResolveSymbolContext (const SourceLocationSpec &src_location_spec, lldb::SymbolContextItem resolve_scope, SymbolContextList &sc_list) override
void GetTypes (SymbolContextScope *sc_scope, lldb::TypeClass type_mask, TypeList &type_list) override
void FindFunctions (const Module::LookupInfo &lookup_info, const CompilerDeclContext &parent_decl_ctx, bool include_inlines, SymbolContextList &sc_list) override
void FindFunctions (const RegularExpression &regex, bool include_inlines, SymbolContextList &sc_list) override
std::optional< PdbCompilandSymId > FindSymbolScope (PdbCompilandSymId id)
std::optional< llvm::StringRef > FindMangledFunctionName (PdbCompilandSymId id)
Find the mangled name for a function.
void FindTypes (const lldb_private::TypeQuery &match, lldb_private::TypeResults &results) override
Find types using a type-matching object that contains all search parameters.
llvm::Expected< lldb::TypeSystemSP > GetTypeSystemForLanguage (lldb::LanguageType language) override
CompilerDeclContext FindNamespace (ConstString name, const CompilerDeclContext &parent_decl_ctx, bool only_root_namespaces) override
Finds a namespace of name name and whose parent context is parent_decl_ctx.
llvm::StringRef GetPluginName () override
llvm::pdb::PDBFile & GetPDBFile ()
const llvm::pdb::PDBFile & GetPDBFile () const
PdbIndex & GetIndex ()
void DumpClangAST (Stream &s, llvm::StringRef filter, bool show_color) override
std::optional< llvm::codeview::TypeIndex > GetParentType (llvm::codeview::TypeIndex ti)
Public Member Functions inherited from lldb_private::SymbolFileCommon
SymbolFileCommon (lldb::ObjectFileSP objfile_sp)
~SymbolFileCommon () override=default
uint32_t GetAbilities () override
Get a mask of what this symbol file supports for the object file that it was constructed with.
Symtab * GetSymtab (bool can_create=true) override
ObjectFile * GetObjectFile () override
const ObjectFile * GetObjectFile () const override
ObjectFile * GetMainObjectFile () override
void SectionFileAddressesChanged () override
Notify the SymbolFile that the file addresses in the Sections for this module have been changed.
uint32_t GetNumCompileUnits () override
lldb::CompUnitSP GetCompileUnitAtIndex (uint32_t idx) override
void Dump (Stream &s) override
bool GetDebugInfoIndexWasLoadedFromCache () const override
Accessors for the bool that indicates if the debug info index was loaded from, or saved to the module index cache.
void SetDebugInfoIndexWasLoadedFromCache () override
bool GetDebugInfoIndexWasSavedToCache () const override
void SetDebugInfoIndexWasSavedToCache () override
bool GetDebugInfoHadFrameVariableErrors () const override
Accessors for the bool that indicates if there was debug info, but errors stopped variables from being able to be displayed correctly.
void SetDebugInfoHadFrameVariableErrors () override
lldb::TypeSP MakeType (lldb::user_id_t uid, ConstString name, std::optional< uint64_t > byte_size, SymbolContextScope *context, lldb::user_id_t encoding_uid, Type::EncodingDataType encoding_uid_type, const Declaration &decl, const CompilerType &compiler_qual_type, Type::ResolveState compiler_type_resolve_state, uint32_t opaque_payload=0) override
This function is used to create types that belong to a SymbolFile.
lldb::TypeSP CopyType (const lldb::TypeSP &other_type) override
Public Member Functions inherited from lldb_private::SymbolFile
SymbolFile ()=default
~SymbolFile () override=default
virtual SymbolFile * GetBackingSymbolFile ()
SymbolFileOnDemand class overrides this to return the underlying backing SymbolFile implementation that loads on-demand.
virtual std::recursive_mutex & GetModuleMutex () const
Symbols file subclasses should override this to return the Module that owns the TypeSystem that this symbol file modifies type information in.
virtual bool GetLoadDebugInfoEnabled ()
Whether debug info will be loaded or not.
virtual void SetLoadDebugInfoEnabled ()
Specify debug info should be loaded.
virtual XcodeSDK ParseXcodeSDK (CompileUnit &comp_unit)
Return the Xcode SDK comp_unit was compiled against.
virtual llvm::SmallSet< lldb::LanguageType, 4 > ParseAllLanguages (CompileUnit &comp_unit)
This function exists because SymbolFileDWARFDebugMap may extra compile units which aren't exposed as "real" compile units.
virtual bool ForEachExternalModule (lldb_private::CompileUnit &comp_unit, llvm::DenseSet< lldb_private::SymbolFile * > &visited_symbol_files, llvm::function_ref< bool(Module &)> lambda)
Apply a lambda to each external lldb::Module referenced by this comp_unit.
virtual bool ParseIsOptimized (CompileUnit &comp_unit)
virtual std::vector< CompilerContext > GetCompilerContextForUID (lldb::user_id_t uid)
Status GetFrameVariableError (StackFrame &frame)
Get an error that describes why variables might be missing for a given symbol context.
virtual Status CalculateFrameVariableError (StackFrame &frame)
Subclasses will override this function to for GetFrameVariableError().
virtual void FindGlobalVariables (const RegularExpression &regex, uint32_t max_matches, VariableList &variables)
virtual void FindFunctions (llvm::ArrayRef< Module::LookupInfo > lookup_infos, const CompilerDeclContext &parent_decl_ctx, bool include_inlines, SymbolContextList &sc_list)
virtual void GetMangledNamesForFunction (const std::string &scope_qualified_name, std::vector< ConstString > &mangled_names)
virtual llvm::Expected< SymbolContext > ResolveFunctionCallLabel (FunctionCallLabel &label)
Resolves the function corresponding to the specified LLDB function call label.
virtual void PreloadSymbols ()
virtual std::vector< std::unique_ptr< CallEdge > > ParseCallEdgesInFunction (UserID func_id)
virtual lldb::UnwindPlanSP GetUnwindPlan (const Address &address, const RegisterInfoResolver &resolver)
virtual llvm::Expected< lldb::addr_t > GetParameterStackSize (const Symbol &symbol)
Return the number of stack bytes taken up by the parameters to this function.
virtual StatsDuration::Duration GetDebugInfoParseTime ()
Return the time taken to parse the debug information.
virtual StatsDuration::Duration GetDebugInfoIndexTime ()
Return the time it took to index the debug information in the object file.
virtual void ResetStatistics ()
Reset the statistics for the symbol file.
virtual ModuleList GetDebugInfoModules ()
Get the additional modules that this symbol file uses to parse debug info.
virtual bool GetSeparateDebugInfo (StructuredData::Dictionary &d, bool errors_only, bool load_all_debug_info=false)
Return true if separate debug info files are supported and this function succeeded, false otherwise.
virtual DWOStats GetDwoStats ()
Retrieves statistics about DWO files associated with this symbol file.
std::unordered_map< lldb::CompUnitSP, Args > GetCompileOptions ()
Returns a map of compilation unit to the compile option arguments associated with that compilation unit.
std::string GetObjectName () const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static void DebuggerInitialize (Debugger &debugger)
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static SymbolFile * CreateInstance (lldb::ObjectFileSP objfile_sp)
static bool classof (const SymbolFileCommon *obj)
Static Public Member Functions inherited from lldb_private::SymbolFile
static SymbolFile * FindPlugin (lldb::ObjectFileSP objfile_sp)
static bool classof (const SymbolFile *obj)
Private Types
using RangeSourceLineVector
Private Member Functions
void BuildParentMap ()
uint32_t CalculateNumCompileUnits () override
lldb::CompUnitSP ParseCompileUnitAtIndex (uint32_t index) override
void FindTypesByName (llvm::StringRef name, uint32_t max_matches, TypeMap &types)
lldb::TypeSP CreateModifierType (PdbTypeSymId type_id, const llvm::codeview::ModifierRecord &mr, CompilerType ct)
lldb::TypeSP CreatePointerType (PdbTypeSymId type_id, const llvm::codeview::PointerRecord &pr, CompilerType ct)
lldb::TypeSP CreateSimpleType (llvm::codeview::TypeIndex ti, CompilerType ct)
lldb::TypeSP CreateTagType (PdbTypeSymId type_id, const llvm::codeview::ClassRecord &cr, CompilerType ct)
lldb::TypeSP CreateTagType (PdbTypeSymId type_id, const llvm::codeview::EnumRecord &er, CompilerType ct)
lldb::TypeSP CreateTagType (PdbTypeSymId type_id, const llvm::codeview::UnionRecord &ur, CompilerType ct)
lldb::TypeSP CreateArrayType (PdbTypeSymId type_id, const llvm::codeview::ArrayRecord &ar, CompilerType ct)
lldb::TypeSP CreateFunctionType (PdbTypeSymId type_id, const llvm::codeview::MemberFunctionRecord &pr, CompilerType ct)
lldb::TypeSP CreateProcedureType (PdbTypeSymId type_id, const llvm::codeview::ProcedureRecord &pr, CompilerType ct)
lldb::TypeSP CreateClassStructUnion (PdbTypeSymId type_id, const llvm::codeview::TagRecord &record, size_t size, CompilerType ct)
lldb::FunctionSP GetOrCreateFunction (PdbCompilandSymId func_id, CompileUnit &comp_unit)
lldb::CompUnitSP GetOrCreateCompileUnit (const CompilandIndexItem &cci)
lldb::TypeSP GetOrCreateType (PdbTypeSymId type_id)
lldb::TypeSP GetOrCreateType (llvm::codeview::TypeIndex ti)
lldb::VariableSP GetOrCreateGlobalVariable (PdbGlobalSymId var_id)
Block * GetOrCreateBlock (PdbCompilandSymId block_id)
lldb::VariableSP GetOrCreateLocalVariable (PdbCompilandSymId scope_id, PdbCompilandSymId var_id, bool is_param, bool is_constant=false)
lldb::TypeSP GetOrCreateTypedef (PdbGlobalSymId id)
lldb::FunctionSP CreateFunction (PdbCompilandSymId func_id, CompileUnit &comp_unit)
Block * CreateBlock (PdbCompilandSymId block_id)
lldb::VariableSP CreateLocalVariable (PdbCompilandSymId scope_id, PdbCompilandSymId var_id, bool is_param, bool is_constant=false)
lldb::TypeSP CreateTypedef (PdbGlobalSymId id)
lldb::CompUnitSP CreateCompileUnit (const CompilandIndexItem &cci)
lldb::TypeSP CreateType (PdbTypeSymId type_id, CompilerType ct)
lldb::TypeSP CreateAndCacheType (PdbTypeSymId type_id)
lldb::VariableSP CreateGlobalVariable (PdbGlobalSymId var_id)
lldb::VariableSP CreateConstantSymbol (PdbGlobalSymId var_id, const llvm::codeview::CVSymbol &cvs)
size_t ParseVariablesForCompileUnit (CompileUnit &comp_unit, VariableList &variables)
size_t ParseVariablesForBlock (PdbCompilandSymId block_id)
void CreateSimpleArgumentListTypes (llvm::codeview::TypeIndex arglist_ti)
llvm::Expected< uint32_t > GetFileIndex (const CompilandIndexItem &cii, uint32_t file_id)
size_t ParseSymbolArrayInScope (PdbCompilandSymId parent, llvm::function_ref< bool(llvm::codeview::SymbolKind, PdbCompilandSymId)> fn)
void ParseInlineSite (PdbCompilandSymId inline_site_id, Address func_addr)
std::vector< CompilerContext > GetContextForType (llvm::codeview::TypeIndex ti)
void CacheGlobalBaseNames ()
Caches the basenames of symbols found in the globals stream.
void CacheUdtDeclarations ()
llvm::Expected< Declaration > ResolveUdtDeclaration (PdbTypeSymId type_id)
std::optional< llvm::StringRef > FindMangledSymbol (SegmentOffset so, llvm::codeview::TypeIndex function_type=llvm::codeview::TypeIndex())
Find a symbol name at a specific address (so).
llvm::StringRef StripMangledFunctionName (llvm::StringRef mangled, PdbTypeSymId func_ty)
Private Attributes
llvm::BumpPtrAllocator m_allocator
lldb::addr_t m_obj_load_address = 0
bool m_done_full_type_scan = false
lldb::user_id_t anonymous_id = LLDB_INVALID_UID - 1
std::unique_ptr< llvm::pdb::PDBFile > m_file_up
std::unique_ptr< PdbIndex > m_index
llvm::DenseMap< lldb::user_id_t, lldb::VariableSP > m_global_vars
llvm::DenseMap< lldb::user_id_t, lldb::VariableSP > m_local_variables
llvm::DenseMap< lldb::user_id_t, lldb::BlockSP > m_blocks
llvm::DenseMap< lldb::user_id_t, lldb::FunctionSP > m_functions
llvm::DenseMap< lldb::user_id_t, lldb::CompUnitSP > m_compilands
llvm::DenseMap< lldb::user_id_t, lldb::TypeSP > m_types
llvm::DenseMap< lldb::user_id_t, std::shared_ptr< InlineSite > > m_inline_sites
llvm::DenseMap< llvm::codeview::TypeIndex, llvm::codeview::TypeIndex > m_parent_types
llvm::DenseMap< llvm::codeview::TypeIndex, UdtDeclaration > m_udt_declarations
std::once_flag m_cached_udt_declarations
lldb_private::UniqueCStringMap< uint32_t > m_type_base_names
lldb_private::UniqueCStringMap< uint32_t > m_func_full_names
mangled name/full function name -> Global ID(s)
lldb_private::UniqueCStringMap< uint32_t > m_func_base_names
basename -> Global ID(s)
lldb_private::UniqueCStringMap< uint32_t > m_func_method_names
method basename -> Global ID(s)
lldb_private::UniqueCStringMap< uint32_t > m_global_variable_base_names
global variable basename -> Global ID(s)
Static Private Attributes
static char ID
LLVM RTTI support.
Friends
class UdtRecordCompleter
bool isA (const void *ClassID) const override
LLVM RTTI support.
static bool classof (const SymbolFile *obj)
Additional Inherited Members
Public Types inherited from lldb_private::SymbolFile
enum Abilities {
CompileUnits = (1u << 0) , LineTables = (1u << 1) , Functions = (1u << 2) , Blocks = (1u << 3) ,
GlobalVariables = (1u << 4) , LocalVariables = (1u << 5) , VariableTypes = (1u << 6) , kAllAbilities = ((1u << 7) - 1u)
}
Protected Member Functions inherited from lldb_private::SymbolFileCommon
virtual TypeList & GetTypeList ()
void SetCompileUnitAtIndex (uint32_t idx, const lldb::CompUnitSP &cu_sp)
Protected Member Functions inherited from lldb_private::SymbolFile
void AssertModuleLock ()
virtual void GetCompileOptions (std::unordered_map< lldb::CompUnitSP, lldb_private::Args > &args)
Protected Attributes inherited from lldb_private::SymbolFileCommon
lldb::ObjectFileSP m_objfile_sp
std::optional< std::vector< lldb::CompUnitSP > > m_compile_units
TypeList m_type_list
uint32_t m_abilities = 0
bool m_calculated_abilities = false
bool m_index_was_loaded_from_cache = false
bool m_index_was_saved_to_cache = false
bool m_debug_info_had_variable_errors = false
Set to true if any variable feteching errors have been found when calling GetFrameVariableError().
Detailed Description
Definition at line 43 of file SymbolFileNativePDB.h.
Member Typedef Documentation
RangeSourceLineVector
using lldb_private::npdb::SymbolFileNativePDB::RangeSourceLineVector private
Initial value:
      lldb_private::RangeDataVector<uint32_t, uint32_t, int32_t>
Definition at line 181 of file SymbolFileNativePDB.h.
Constructor & Destructor Documentation
SymbolFileNativePDB()
SymbolFileNativePDB::SymbolFileNativePDB (lldb::ObjectFileSP objfile_sp)
Definition at line 377 of file SymbolFileNativePDB.cpp.
References lldb_private::SymbolFileCommon::SymbolFileCommon().
Referenced by CreateInstance().
~SymbolFileNativePDB()
SymbolFileNativePDB::~SymbolFileNativePDB () override default
References lldb_private::npdb::Type.
Member Function Documentation
AddSymbols()
void SymbolFileNativePDB::AddSymbols (Symtab & symtab) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 1165 of file SymbolFileNativePDB.cpp.
References lldb_private::Symtab::AddSymbol(), lldb::eSymbolTypeCode, lldb::eSymbolTypeData, m_index, lldb_private::SymbolFileCommon::m_objfile_sp, lldb_private::Symbol::SetByteSize(), and lldb_private::Symtab::SymbolAtIndex().
BuildParentMap()
void SymbolFileNativePDB::BuildParentMap () private
Definition at line 2589 of file SymbolFileNativePDB.cpp.
References lldb_private::npdb::CVTagRecord::asTag(), lldb_private::npdb::CVTagRecord::create(), MSVCUndecoratedNameParser::DropScope(), error(), GetNestedTagDefinition(), lldb_private::npdb::IsTagRecord(), m_index, m_parent_types, m_type_base_names, lldb_private::npdb::CVTagRecord::name(), and lldb_private::npdb::PdbIndex::tpi().
Referenced by InitializeObject().
CacheGlobalBaseNames()
void SymbolFileNativePDB::CacheGlobalBaseNames () private
Caches the basenames of symbols found in the globals stream.
This includes functions and global variables
Definition at line 1849 of file SymbolFileNativePDB.cpp.
References MSVCUndecoratedNameParser::DropScope(), lldb_private::Mangled::IsMangledName(), lldb_private::npdb::CompilandIndexItem::m_debug_stream, m_func_base_names, m_func_full_names, m_func_method_names, m_global_variable_base_names, and m_index.
Referenced by FindFunctions(), and FindGlobalVariables().
CacheUdtDeclarations()
void SymbolFileNativePDB::CacheUdtDeclarations () private
Definition at line 2897 of file SymbolFileNativePDB.cpp.
References m_index, and m_udt_declarations.
Referenced by ResolveUdtDeclaration().
CalculateAbilities()
uint32_t SymbolFileNativePDB::CalculateAbilities () override virtual
Implements lldb_private::SymbolFile.
Definition at line 382 of file SymbolFileNativePDB.cpp.
References lldb_private::SymbolFile::Blocks, lldb_private::npdb::PdbIndex::create(), lldb_private::SymbolFile::kAllAbilities, loadMatchingPDBFile(), lldb_private::SymbolFile::LocalVariables, m_allocator, m_file_up, m_index, and lldb_private::SymbolFileCommon::m_objfile_sp.
CalculateNumCompileUnits()
uint32_t SymbolFileNativePDB::CalculateNumCompileUnits () override private virtual
Implements lldb_private::SymbolFileCommon.
Definition at line 440 of file SymbolFileNativePDB.cpp.
References m_index.
classof()
bool lldb_private::npdb::SymbolFileNativePDB::classof (const SymbolFile * obj) inline static
Definition at line 55 of file SymbolFileNativePDB.h.
References ID, lldb_private::SymbolFile::isA(), and lldb_private::SymbolFile::SymbolFile().
CompleteType()
bool SymbolFileNativePDB::CompleteType (CompilerType & compiler_type) override virtual
Implements lldb_private::SymbolFile.
Definition at line 2536 of file SymbolFileNativePDB.cpp.
References lldb_private::npdb::PdbAstBuilder::CompleteType(), lldb_private::SymbolFile::GetModuleMutex(), and lldb_private::CompilerType::GetTypeSystem().
CreateAndCacheType()
TypeSP SymbolFileNativePDB::CreateAndCacheType (PdbTypeSymId type_id) private
Definition at line 893 of file SymbolFileNativePDB.cpp.
References CreateType(), lldb::eLanguageTypeC_plus_plus, lldb_private::npdb::PdbAstBuilder::GetOrCreateType(), GetTypeSystemForLanguage(), lldb_private::npdb::PdbTypeSymId::index, lldb_private::npdb::IsForwardRefUdt(), m_index, m_types, and lldb_private::npdb::toOpaqueUid().
Referenced by GetOrCreateType(), and ResolveTypeUID().
CreateArrayType()
TypeSP SymbolFileNativePDB::CreateArrayType (PdbTypeSymId type_id, const llvm::codeview::ArrayRecord & ar, CompilerType ct) private
Definition at line 777 of file SymbolFileNativePDB.cpp.
References lldb_private::Type::eEncodingIsUID, lldb_private::Type::Full, GetOrCreateType(), LLDB_INVALID_UID, lldb_private::SymbolFileCommon::MakeType(), and lldb_private::npdb::toOpaqueUid().
Referenced by CreateType().
CreateBlock()
Block * SymbolFileNativePDB::CreateBlock (PdbCompilandSymId block_id) private
Definition at line 455 of file SymbolFileNativePDB.cpp.
References lldb_private::Block::CalculateSymbolContextFunction(), lldb_private::Block::CreateChild(), lldb_private::npdb::PdbAstBuilder::EnsureBlock(), lldb_private::npdb::PdbAstBuilder::EnsureInlinedFunction(), lldb_private::Function::GetAddress(), lldb_private::Address::GetFileAddress(), lldb_private::ModuleChild::GetModule(), lldb_private::SymbolFileCommon::GetObjectFile(), GetOrCreateBlock(), GetOrCreateCompileUnit(), GetOrCreateFunction(), GetTypeSystemForLanguage(), lldbassert, m_blocks, lldb_private::npdb::CompilandIndexItem::m_debug_stream, m_index, m_inline_sites, lldb_private::npdb::PdbCompilandSymId::modi, lldb_private::npdb::PdbCompilandSymId::offset, and lldb_private::npdb::toOpaqueUid().
Referenced by GetOrCreateBlock().
CreateClassStructUnion()
lldb::TypeSP SymbolFileNativePDB::CreateClassStructUnion (PdbTypeSymId type_id, const llvm::codeview::TagRecord & record, size_t size, CompilerType ct) private
Definition at line 724 of file SymbolFileNativePDB.cpp.
References lldb_private::Type::eEncodingIsUID, lldb_private::Type::Forward, lldb_private::GetLog(), GetUnqualifiedTypeName(), LLDB_INVALID_UID, LLDB_LOG_ERROR, lldb_private::SymbolFileCommon::MakeType(), ResolveUdtDeclaration(), lldb_private::Symbols, and lldb_private::npdb::toOpaqueUid().
CreateCompileUnit()
CompUnitSP SymbolFileNativePDB::CreateCompileUnit (const CompilandIndexItem & cci) private
Definition at line 599 of file SymbolFileNativePDB.cpp.
References lldb::eLanguageTypeUnknown, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb_private::npdb::CompilandIndexItem::m_compile_opts, lldb_private::npdb::CompilandIndexItem::m_id, m_index, lldb_private::SymbolFileCommon::m_objfile_sp, lldb_private::npdb::PdbCompilandId::modi, lldb_private::SymbolFileCommon::SetCompileUnitAtIndex(), lldb_private::npdb::toOpaqueUid(), and TranslateLanguage().
Referenced by GetOrCreateCompileUnit().
CreateConstantSymbol()
lldb::VariableSP SymbolFileNativePDB::CreateConstantSymbol (PdbGlobalSymId var_id, const llvm::codeview::CVSymbol & cvs) private
Definition at line 1051 of file SymbolFileNativePDB.cpp.
References lldb::eValueTypeVariableGlobal, lldb_private::ModuleChild::GetModule(), lldb_private::SymbolFileCommon::GetObjectFile(), m_index, lldb_private::npdb::MakeConstantLocationExpression(), and lldb_private::npdb::toOpaqueUid().
Referenced by CreateGlobalVariable().
CreateFunction()
lldb::FunctionSP SymbolFileNativePDB::CreateFunction (PdbCompilandSymId func_id, CompileUnit & comp_unit) private
Definition at line 546 of file SymbolFileNativePDB.cpp.
References lldb_private::CompileUnit::AddFunction(), FindMangledSymbol(), lldb_private::CompileUnit::GetLanguage(), lldb_private::ModuleChild::GetModule(), GetOrCreateType(), lldb_private::npdb::GetSegmentOffsetAndLength(), GetTypeSystemForLanguage(), lldb_private::Address::IsValid(), LLDB_INVALID_ADDRESS, lldbassert, lldb_private::npdb::CompilandIndexItem::m_debug_stream, m_index, lldb_private::npdb::PdbCompilandSymId::modi, lldb_private::npdb::PdbCompilandSymId::offset, lldb_private::npdb::SegmentOffset::offset, lldb_private::npdb::SegmentOffset::segment, lldb_private::npdb::SegmentOffsetLength::so, and lldb_private::npdb::toOpaqueUid().
Referenced by GetOrCreateFunction().
CreateFunctionType()
TypeSP SymbolFileNativePDB::CreateFunctionType (PdbTypeSymId type_id, const llvm::codeview::MemberFunctionRecord & pr, CompilerType ct) private
Definition at line 791 of file SymbolFileNativePDB.cpp.
References CreateSimpleArgumentListTypes(), lldb_private::Type::eEncodingIsUID, lldb_private::Type::Full, GetOrCreateType(), LLDB_INVALID_UID, lldb_private::SymbolFileCommon::MakeType(), and lldb_private::npdb::toOpaqueUid().
Referenced by CreateType().
CreateGlobalVariable()
VariableSP SymbolFileNativePDB::CreateGlobalVariable (PdbGlobalSymId var_id) private
Definition at line 962 of file SymbolFileNativePDB.cpp.
References CreateConstantSymbol(), lldb::eValueTypeInvalid, lldb::eValueTypeVariableGlobal, lldb::eValueTypeVariableStatic, lldb::eValueTypeVariableThreadLocal, lldb_private::ModuleChild::GetModule(), lldb_private::SymbolFileCommon::GetNumCompileUnits(), lldb_private::SymbolFileCommon::GetObjectFile(), GetOrCreateCompileUnit(), GetTypeSystemForLanguage(), m_index, lldb_private::npdb::MakeGlobalLocationExpression(), lldb_private::npdb::PdbGlobalSymId::offset, and lldb_private::npdb::toOpaqueUid().
Referenced by GetOrCreateGlobalVariable().
CreateInstance()
SymbolFile * SymbolFileNativePDB::CreateInstance (lldb::ObjectFileSP objfile_sp) static
Definition at line 370 of file SymbolFileNativePDB.cpp.
References lldb_private::SymbolFile::SymbolFile(), SymbolFileNativePDB(), and SymbolFilePDB::UseNativePDB().
Referenced by Initialize(), and Terminate().
CreateLocalVariable()
VariableSP SymbolFileNativePDB::CreateLocalVariable (PdbCompilandSymId scope_id, PdbCompilandSymId var_id, bool is_param, bool is_constant = false) private
Definition at line 2197 of file SymbolFileNativePDB.cpp.
References lldb_private::Block::CalculateSymbolContextFunction(), lldb::eValueTypeVariableArgument, lldb::eValueTypeVariableLocal, lldb_private::Function::GetAddress(), lldb_private::Address::GetFileAddress(), lldb_private::ModuleChild::GetModule(), lldb_private::SymbolFileCommon::GetObjectFile(), GetOrCreateBlock(), GetOrCreateCompileUnit(), GetOrCreateType(), lldb_private::Block::GetParent(), lldb_private::Block::GetStartAddress(), GetTypeSystemForLanguage(), lldb_private::npdb::GetVariableLocationInfo(), lldb_private::npdb::VariableInfo::is_param, lldb_private::DWARFExpressionList::IsValid(), lldb_private::npdb::VariableInfo::location, lldb_private::npdb::CompilandIndexItem::m_debug_stream, m_index, m_local_variables, lldb_private::npdb::MakeConstantLocationExpression(), lldb_private::npdb::PdbCompilandSymId::modi, lldb_private::npdb::VariableInfo::name, lldb_private::npdb::PdbCompilandSymId::offset, lldb_private::DWARFExpressionList::SetFuncFileAddress(), lldb_private::npdb::toOpaqueUid(), and lldb_private::npdb::VariableInfo::type.
Referenced by GetOrCreateLocalVariable().
CreateModifierType()
lldb::TypeSP SymbolFileNativePDB::CreateModifierType (PdbTypeSymId type_id, const llvm::codeview::ModifierRecord & mr, CompilerType ct) private
Definition at line 621 of file SymbolFileNativePDB.cpp.
References lldb_private::Type::eEncodingIsUID, lldb_private::Type::Full, GetOrCreateType(), GetSimpleTypeName(), LLDB_INVALID_UID, m_index, lldb_private::SymbolFileCommon::MakeType(), and lldb_private::npdb::toOpaqueUid().
Referenced by CreateType().
CreatePointerType()
lldb::TypeSP SymbolFileNativePDB::CreatePointerType (PdbTypeSymId type_id, const llvm::codeview::PointerRecord & pr, CompilerType ct) private
Definition at line 649 of file SymbolFileNativePDB.cpp.
References lldb_private::Type::eEncodingIsUID, lldb_private::Type::Full, GetOrCreateType(), LLDB_INVALID_UID, lldb_private::SymbolFileCommon::MakeType(), and lldb_private::npdb::toOpaqueUid().
Referenced by CreateType().
CreateProcedureType()
TypeSP SymbolFileNativePDB::CreateProcedureType (PdbTypeSymId type_id, const llvm::codeview::ProcedureRecord & pr, CompilerType ct) private
Definition at line 804 of file SymbolFileNativePDB.cpp.
References CreateSimpleArgumentListTypes(), lldb_private::Type::eEncodingIsUID, lldb_private::Type::Full, GetOrCreateType(), LLDB_INVALID_UID, lldb_private::SymbolFileCommon::MakeType(), and lldb_private::npdb::toOpaqueUid().
Referenced by CreateType().
CreateSimpleArgumentListTypes()
void SymbolFileNativePDB::CreateSimpleArgumentListTypes (llvm::codeview::TypeIndex arglist_ti) private
Definition at line 817 of file SymbolFileNativePDB.cpp.
References GetOrCreateType(), and m_index.
Referenced by CreateFunctionType(), and CreateProcedureType().
CreateSimpleType()
lldb::TypeSP SymbolFileNativePDB::CreateSimpleType (llvm::codeview::TypeIndex ti, CompilerType ct) private
Definition at line 667 of file SymbolFileNativePDB.cpp.
References lldb_private::Type::eEncodingIsUID, lldb_private::Type::Full, GetOrCreateType(), GetSimpleTypeName(), lldb_private::npdb::GetTypeSizeForSimpleKind(), LLDB_INVALID_UID, lldb_private::SymbolFileCommon::MakeType(), and lldb_private::npdb::toOpaqueUid().
Referenced by CreateType().
CreateTagType() [1/3]
lldb::TypeSP lldb_private::npdb::SymbolFileNativePDB::CreateTagType (PdbTypeSymId type_id, const llvm::codeview::ClassRecord & cr, CompilerType ct) private
Referenced by CreateType().
CreateTagType() [2/3]
lldb::TypeSP lldb_private::npdb::SymbolFileNativePDB::CreateTagType (PdbTypeSymId type_id, const llvm::codeview::EnumRecord & er, CompilerType ct) private
CreateTagType() [3/3]
lldb::TypeSP lldb_private::npdb::SymbolFileNativePDB::CreateTagType (PdbTypeSymId type_id, const llvm::codeview::UnionRecord & ur, CompilerType ct) private
CreateType()
TypeSP SymbolFileNativePDB::CreateType (PdbTypeSymId type_id, CompilerType ct) private
Definition at line 834 of file SymbolFileNativePDB.cpp.
References CreateArrayType(), CreateFunctionType(), CreateModifierType(), CreatePointerType(), CreateProcedureType(), CreateSimpleType(), CreateTagType(), lldb_private::npdb::PdbTypeSymId::index, lldb_private::npdb::PdbTypeSymId::is_ipi, IsClassRecord(), and m_index.
Referenced by CreateAndCacheType().
CreateTypedef()
TypeSP SymbolFileNativePDB::CreateTypedef (PdbGlobalSymId id) private
Definition at line 2291 of file SymbolFileNativePDB.cpp.
References lldb_private::Type::eEncodingIsTypedefUID, lldb::eLanguageTypeC_plus_plus, lldb_private::Type::Forward, GetOrCreateType(), lldb_private::npdb::PdbAstBuilder::GetOrCreateTypedefType(), GetTypeSystemForLanguage(), lldbassert, m_index, lldb_private::SymbolFileCommon::MakeType(), and lldb_private::npdb::toOpaqueUid().
Referenced by GetOrCreateTypedef().
DebuggerInitialize()
void SymbolFileNativePDB::DebuggerInitialize (Debugger & debugger) static
Definition at line 364 of file SymbolFileNativePDB.cpp.
Referenced by Initialize().
DumpClangAST()
void SymbolFileNativePDB::DumpClangAST (Stream & s, llvm::StringRef filter, bool show_color) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 1834 of file SymbolFileNativePDB.cpp.
References lldb_private::npdb::PdbAstBuilder::Dump(), lldb::eLanguageTypeC_plus_plus, and GetTypeSystemForLanguage().
FindFunctions() [1/2]
void SymbolFileNativePDB::FindFunctions (const Module::LookupInfo & lookup_info, const CompilerDeclContext & parent_decl_ctx, bool include_inlines, SymbolContextList & sc_list) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 2007 of file SymbolFileNativePDB.cpp.
References lldb_private::SymbolContextList::Append(), CacheGlobalBaseNames(), lldb_private::SymbolContext::comp_unit, lldb_private::SymbolContext::function, GetDeclContextContainingUID(), lldb_private::Module::LookupInfo::GetLookupName(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::Module::LookupInfo::GetName(), lldb_private::Module::LookupInfo::GetNameTypeMask(), GetOrCreateCompileUnit(), GetOrCreateFunction(), lldb_private::CompilerDeclContext::IsValid(), lldb_private::npdb::IsValidRecord(), lldbassert, m_func_base_names, m_func_full_names, m_func_method_names, m_index, and lldb_private::npdb::toOpaqueUid().
FindFunctions() [2/2]
void SymbolFileNativePDB::FindFunctions (const RegularExpression & regex, bool include_inlines, SymbolContextList & sc_list) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 2073 of file SymbolFileNativePDB.cpp.
FindGlobalVariables()
void SymbolFileNativePDB::FindGlobalVariables (ConstString name, const CompilerDeclContext & parent_decl_ctx, uint32_t max_matches, VariableList & variables) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 1979 of file SymbolFileNativePDB.cpp.
References lldb_private::VariableList::AddVariable(), CacheGlobalBaseNames(), GetDeclContextContainingUID(), lldb_private::SymbolFile::GetModuleMutex(), GetOrCreateGlobalVariable(), lldb_private::CompilerDeclContext::IsValid(), m_global_variable_base_names, and lldb_private::npdb::toOpaqueUid().
FindMangledFunctionName()
std::optional< llvm::StringRef > SymbolFileNativePDB::FindMangledFunctionName (PdbCompilandSymId id)
Find the mangled name for a function.
Parameters
id A symbol ID of a S_LPROC32/S_GPROC32 record
Returns
The mangled name of the function (if available)
Definition at line 2821 of file SymbolFileNativePDB.cpp.
References FindMangledSymbol(), lldb_private::npdb::CompilandIndexItem::m_debug_stream, m_index, lldb_private::npdb::PdbCompilandSymId::modi, and lldb_private::npdb::PdbCompilandSymId::offset.
FindMangledSymbol()
std::optional< llvm::StringRef > SymbolFileNativePDB::FindMangledSymbol (SegmentOffset so, llvm::codeview::TypeIndex function_type = llvm::codeview::TypeIndex()) private
Find a symbol name at a specific address (so).
Parameters
[in] so The segment and offset where the symbol is located.
[in] function_type If the symbol is expected to be a function, this has to be the type of the function. It's used to strip the name of __cdecl functions on x86.
Returns
The mangled symbol name if found, otherwise std::nullopt.
Definition at line 2839 of file SymbolFileNativePDB.cpp.
References m_index, lldb_private::npdb::SegmentOffset::offset, lldb_private::npdb::SegmentOffset::segment, and StripMangledFunctionName().
Referenced by CreateFunction(), and FindMangledFunctionName().
FindNamespace()
CompilerDeclContext SymbolFileNativePDB::FindNamespace (ConstString name, const CompilerDeclContext & parent_decl_ctx, bool only_root_namespaces) override virtual
Finds a namespace of name name and whose parent context is parent_decl_ctx.
If
!parent_decl_ctx.IsValid()
then this function will consider all namespaces that match the name. If only_root_namespaces is true, only consider in the search those DIEs that represent top-level namespaces.
Reimplemented from lldb_private::SymbolFile.
Definition at line 2553 of file SymbolFileNativePDB.cpp.
References lldb::eLanguageTypeC_plus_plus, lldb_private::npdb::PdbAstBuilder::FindNamespaceDecl(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::ConstString::GetStringRef(), and GetTypeSystemForLanguage().
FindSymbolScope()
std::optional< PdbCompilandSymId > SymbolFileNativePDB::FindSymbolScope (PdbCompilandSymId id)
Definition at line 2711 of file SymbolFileNativePDB.cpp.
References lldbassert, lldb_private::npdb::CompilandIndexItem::m_debug_stream, and m_index.
FindTypes()
void SymbolFileNativePDB::FindTypes (const lldb_private::TypeQuery & query, lldb_private::TypeResults & results) override virtual
Find types using a type-matching object that contains all search parameters.
See also
lldb_private::TypeQuery
Parameters
[in] query A type matching object that contains all of the details of the type search.
[in] results Any matching types will be populated into the results object using TypeMap::InsertUnique(...).
Reimplemented from lldb_private::SymbolFile.
Definition at line 2077 of file SymbolFileNativePDB.cpp.
References lldb_private::TypeResults::AlreadySearched(), lldb_private::TypeQuery::ContextMatches(), lldb_private::TypeResults::Done(), GetContextForType(), lldb_private::SymbolFile::GetModuleMutex(), GetOrCreateType(), lldb_private::TypeQuery::GetTypeBasename(), lldb_private::TypeResults::InsertUnique(), and m_type_base_names.
FindTypesByName()
void SymbolFileNativePDB::FindTypesByName (llvm::StringRef name, uint32_t max_matches, TypeMap & types) private
Definition at line 2109 of file SymbolFileNativePDB.cpp.
References GetOrCreateType(), lldb_private::TypeMap::Insert(), and m_index.
GetContextForType()
std::vector< CompilerContext > SymbolFileNativePDB::GetContextForType (llvm::codeview::TypeIndex ti) private
Definition at line 2772 of file SymbolFileNativePDB.cpp.
References lldb_private::ClassOrStruct, lldb_private::npdb::CVTagRecord::contextKind(), lldb_private::npdb::CVTagRecord::create(), lldb_private::Enum, GetParentType(), lldb_private::Type::GetTypeScopeAndBasename(), lldb_private::npdb::IsTagRecord(), m_index, lldb_private::npdb::CVTagRecord::name(), lldb_private::Namespace, and lldb_private::Union.
Referenced by FindTypes().
GetDebugInfoSize()
uint64_t SymbolFileNativePDB::GetDebugInfoSize (bool load_all_debug_info = false) override virtual
Metrics gathering functions.
Return the size in bytes of all loaded debug information or total possible debug info in the symbol file.
If the debug information is contained in sections of an ObjectFile, then this call should add the size of all sections that contain debug information. Symbols the symbol tables are not considered debug information for this call to make it easy and quick for this number to be calculated. If the symbol file is all debug information, the size of the entire file should be returned. The default implementation of this function will iterate over all sections in a module and add up their debug info only section byte sizes.
Parameters
load_all_debug_info If true, force loading any symbol files if they are not yet loaded and add to the total size. Default to false.
Returns
Total currently loaded debug info size in bytes
Reimplemented from lldb_private::SymbolFileCommon.
Definition at line 2584 of file SymbolFileNativePDB.cpp.
References m_index.
GetDeclContextContainingUID()
CompilerDeclContext SymbolFileNativePDB::GetDeclContextContainingUID (lldb::user_id_t uid) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 2494 of file SymbolFileNativePDB.cpp.
References lldb::eLanguageTypeC_plus_plus, lldb_private::npdb::PdbAstBuilder::GetParentDeclContext(), and GetTypeSystemForLanguage().
Referenced by FindFunctions(), and FindGlobalVariables().
GetDeclContextForUID()
CompilerDeclContext SymbolFileNativePDB::GetDeclContextForUID (lldb::user_id_t uid) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 2480 of file SymbolFileNativePDB.cpp.
References lldb::eLanguageTypeC_plus_plus, lldb_private::npdb::PdbAstBuilder::GetOrCreateDeclContextForUid(), and GetTypeSystemForLanguage().
GetDeclForUID()
CompilerDecl SymbolFileNativePDB::GetDeclForUID (lldb::user_id_t uid) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 2466 of file SymbolFileNativePDB.cpp.
References lldb::eLanguageTypeC_plus_plus, lldb_private::npdb::PdbAstBuilder::GetOrCreateDeclForUid(), and GetTypeSystemForLanguage().
GetDynamicArrayInfoForUID()
std::optional< SymbolFile::ArrayInfo > SymbolFileNativePDB::GetDynamicArrayInfoForUID (lldb::user_id_t type_uid, const lldb_private::ExecutionContext * exe_ctx) override virtual
If type_uid points to an array type, return its characteristics.
To support variable-length array types, this function takes an optional ExecutionContext. If exe_ctx is non-null, the dynamic characteristics for that context are returned.
Implements lldb_private::SymbolFile.
Definition at line 2531 of file SymbolFileNativePDB.cpp.
GetFileIndex()
llvm::Expected< uint32_t > SymbolFileNativePDB::GetFileIndex (const CompilandIndexItem & cii, uint32_t file_id) private
Definition at line 1534 of file SymbolFileNativePDB.cpp.
References lldb_private::npdb::CompilandIndexItem::m_file_list, and lldb_private::npdb::CompilandIndexItem::m_strings.
Referenced by ParseInlineSite(), and ParseLineTable().
GetIndex()
PdbIndex & lldb_private::npdb::SymbolFileNativePDB::GetIndex () inline
Definition at line 164 of file SymbolFileNativePDB.h.
References m_index.
Referenced by lldb_private::npdb::PdbAstBuilderClang::CompleteTagDecl().
GetOrCreateBlock()
Block * SymbolFileNativePDB::GetOrCreateBlock (PdbCompilandSymId block_id) private
Definition at line 1120 of file SymbolFileNativePDB.cpp.
References CreateBlock(), m_blocks, and lldb_private::npdb::toOpaqueUid().
Referenced by CreateBlock(), CreateLocalVariable(), ParseBlocksRecursive(), and ParseVariablesForBlock().
GetOrCreateCompileUnit()
CompUnitSP SymbolFileNativePDB::GetOrCreateCompileUnit (const CompilandIndexItem & cci) private
Definition at line 1109 of file SymbolFileNativePDB.cpp.
References CreateCompileUnit(), lldbassert, m_compilands, lldb_private::npdb::CompilandIndexItem::m_id, and lldb_private::npdb::toOpaqueUid().
Referenced by CreateBlock(), CreateGlobalVariable(), CreateLocalVariable(), FindFunctions(), ParseCompileUnitAtIndex(), and ParseInlineSite().
GetOrCreateFunction()
FunctionSP SymbolFileNativePDB::GetOrCreateFunction (PdbCompilandSymId func_id, CompileUnit & comp_unit) private
Definition at line 1099 of file SymbolFileNativePDB.cpp.
References CreateFunction(), m_functions, and lldb_private::npdb::toOpaqueUid().
Referenced by CreateBlock(), FindFunctions(), and ParseFunctions().
GetOrCreateGlobalVariable()
VariableSP SymbolFileNativePDB::GetOrCreateGlobalVariable (PdbGlobalSymId var_id) private
Definition at line 1083 of file SymbolFileNativePDB.cpp.
References CreateGlobalVariable(), m_global_vars, and lldb_private::npdb::toOpaqueUid().
Referenced by FindGlobalVariables(), and ParseVariablesForCompileUnit().
GetOrCreateLocalVariable()
VariableSP SymbolFileNativePDB::GetOrCreateLocalVariable (PdbCompilandSymId scope_id, PdbCompilandSymId var_id, bool is_param, bool is_constant = false) private
Definition at line 2281 of file SymbolFileNativePDB.cpp.
References CreateLocalVariable(), m_local_variables, and lldb_private::npdb::toOpaqueUid().
Referenced by ParseVariablesForBlock().
GetOrCreateType() [1/2]
lldb::TypeSP lldb_private::npdb::SymbolFileNativePDB::GetOrCreateType (llvm::codeview::TypeIndex ti) private
GetOrCreateType() [2/2]
TypeSP SymbolFileNativePDB::GetOrCreateType (PdbTypeSymId type_id) private
Definition at line 948 of file SymbolFileNativePDB.cpp.
References CreateAndCacheType(), lldb_private::SymbolFileCommon::GetTypeList(), lldb_private::TypeList::Insert(), m_types, and lldb_private::npdb::toOpaqueUid().
Referenced by CreateArrayType(), CreateFunction(), CreateFunctionType(), CreateLocalVariable(), CreateModifierType(), CreatePointerType(), CreateProcedureType(), CreateSimpleArgumentListTypes(), CreateSimpleType(), CreateTypedef(), FindTypes(), FindTypesByName(), and ParseTypes().
GetOrCreateTypedef()
TypeSP SymbolFileNativePDB::GetOrCreateTypedef (PdbGlobalSymId id) private
Definition at line 2320 of file SymbolFileNativePDB.cpp.
References CreateTypedef(), m_types, and lldb_private::npdb::toOpaqueUid().
Referenced by ParseTypes().
GetParentType()
std::optional< llvm::codeview::TypeIndex > SymbolFileNativePDB::GetParentType (llvm::codeview::TypeIndex ti)
Definition at line 2764 of file SymbolFileNativePDB.cpp.
References m_parent_types.
Referenced by GetContextForType().
GetPDBFile() [1/2]
llvm::pdb::PDBFile & lldb_private::npdb::SymbolFileNativePDB::GetPDBFile () inline
Definition at line 161 of file SymbolFileNativePDB.h.
References m_index.
GetPDBFile() [2/2]
const llvm::pdb::PDBFile & lldb_private::npdb::SymbolFileNativePDB::GetPDBFile () const inline
Definition at line 162 of file SymbolFileNativePDB.h.
References m_index.
GetPluginDescriptionStatic()
llvm::StringRef SymbolFileNativePDB::GetPluginDescriptionStatic () static
Definition at line 366 of file SymbolFileNativePDB.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef lldb_private::npdb::SymbolFileNativePDB::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 159 of file SymbolFileNativePDB.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::npdb::SymbolFileNativePDB::GetPluginNameStatic () inline static
Definition at line 65 of file SymbolFileNativePDB.h.
Referenced by GetPluginName(), and Initialize().
GetTypes()
void SymbolFileNativePDB::GetTypes (SymbolContextScope * sc_scope, lldb::TypeClass type_mask, TypeList & type_list) override virtual
Implements lldb_private::SymbolFile.
Definition at line 2548 of file SymbolFileNativePDB.cpp.
GetTypeSystemForLanguage()
llvm::Expected< lldb::TypeSystemSP > SymbolFileNativePDB::GetTypeSystemForLanguage (lldb::LanguageType language) override virtual
Reimplemented from lldb_private::SymbolFileCommon.
Definition at line 2575 of file SymbolFileNativePDB.cpp.
References lldb_private::SymbolFileCommon::m_objfile_sp.
Referenced by CreateAndCacheType(), CreateBlock(), CreateFunction(), CreateGlobalVariable(), CreateLocalVariable(), CreateTypedef(), DumpClangAST(), FindNamespace(), GetDeclContextContainingUID(), GetDeclContextForUID(), and GetDeclForUID().
Initialize()
void SymbolFileNativePDB::Initialize () static
Definition at line 354 of file SymbolFileNativePDB.cpp.
References CreateInstance(), DebuggerInitialize(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Referenced by SymbolFilePDB::Initialize().
InitializeObject()
void SymbolFileNativePDB::InitializeObject () override virtual
Initialize the SymbolFile object.
The SymbolFile object with the best set of abilities (detected in "uint32_t SymbolFile::GetAbilities()) will have this function called if it is chosen to parse an object file. More complete initialization can happen in this function which will get called prior to any other functions in the SymbolFile protocol.
Reimplemented from lldb_private::SymbolFile.
Definition at line 420 of file SymbolFileNativePDB.cpp.
References BuildParentMap(), lldb::eLanguageTypeC_plus_plus, lldb_private::GetLog(), LLDB_LOG_ERROR, m_index, m_obj_load_address, lldb_private::SymbolFileCommon::m_objfile_sp, and lldb_private::Symbols.
isA()
bool lldb_private::npdb::SymbolFileNativePDB::isA (const void * ClassID) const inline override virtual
LLVM RTTI support.
Reimplemented from lldb_private::SymbolFileCommon.
Definition at line 52 of file SymbolFileNativePDB.h.
References ID, and lldb_private::SymbolFileCommon::isA().
ParseBlocksRecursive()
size_t SymbolFileNativePDB::ParseBlocksRecursive (Function & func) override virtual
Implements lldb_private::SymbolFile.
Definition at line 1792 of file SymbolFileNativePDB.cpp.
References lldb_private::npdb::PdbSymUid::asCompilandSym(), lldb_private::Function::GetBlock(), lldb_private::UserID::GetID(), lldb_private::SymbolFile::GetModuleMutex(), GetOrCreateBlock(), m_inline_sites, ParseSymbolArrayInScope(), lldb_private::Block::SetBlockInfoHasBeenParsed(), and lldb_private::npdb::toOpaqueUid().
ParseCompileUnitAtIndex()
lldb::CompUnitSP SymbolFileNativePDB::ParseCompileUnitAtIndex (uint32_t index) override private virtual
Implements lldb_private::SymbolFileCommon.
Definition at line 1139 of file SymbolFileNativePDB.cpp.
References lldb_private::SymbolFileCommon::GetNumCompileUnits(), GetOrCreateCompileUnit(), lldbassert, and m_index.
Referenced by ResolveSymbolContext().
ParseDebugMacros()
bool SymbolFileNativePDB::ParseDebugMacros (lldb_private::CompileUnit & comp_unit) override virtual
Implements lldb_private::SymbolFile.
Definition at line 1528 of file SymbolFileNativePDB.cpp.
ParseDeclsForContext()
void SymbolFileNativePDB::ParseDeclsForContext (lldb_private::CompilerDeclContext decl_ctx) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 1128 of file SymbolFileNativePDB.cpp.
References lldb_private::TypeSystem::GetNativePDBParser(), lldb_private::CompilerDeclContext::GetTypeSystem(), and lldb_private::npdb::PdbAstBuilder::ParseDeclsForContext().
ParseFunctions()
size_t SymbolFileNativePDB::ParseFunctions (lldb_private::CompileUnit & comp_unit) override virtual
Implements lldb_private::SymbolFile.
Definition at line 1240 of file SymbolFileNativePDB.cpp.
References lldb_private::npdb::PdbSymUid::asCompiland(), lldb_private::npdb::Compiland, lldb_private::UserID::GetID(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::CompileUnit::GetNumFunctions(), GetOrCreateFunction(), lldb_private::npdb::PdbSymUid::kind(), lldbassert, lldb_private::npdb::CompilandIndexItem::m_debug_stream, m_index, and lldb_private::npdb::PdbCompilandId::modi.
ParseImportedModules()
bool SymbolFileNativePDB::ParseImportedModules (const SymbolContext & sc, std::vector< lldb_private::SourceModule > & imported_modules) override virtual
Implements lldb_private::SymbolFile.
Definition at line 1578 of file SymbolFileNativePDB.cpp.
ParseInlineSite()
void SymbolFileNativePDB::ParseInlineSite (PdbCompilandSymId inline_site_id, Address func_addr) private
Definition at line 1584 of file SymbolFileNativePDB.cpp.
References lldb_private::RangeDataVector< B, S, T, N, Compare >::FindEntryThatContains(), lldb_private::Address::GetFileAddress(), GetFileIndex(), lldb_private::SupportFileList::GetFileSpecAtIndex(), GetOrCreateCompileUnit(), lldb_private::npdb::CompilandIndexItem::m_debug_stream, lldb_private::npdb::CompilandIndexItem::m_global_line_table, m_index, lldb_private::npdb::CompilandIndexItem::m_inline_map, m_inline_sites, lldb_private::npdb::PdbCompilandSymId::offset, ParseInlineSite(), and lldb_private::npdb::toOpaqueUid().
Referenced by ParseInlineSite(), and ParseLineTable().
ParseLanguage()
lldb::LanguageType SymbolFileNativePDB::ParseLanguage (lldb_private::CompileUnit & comp_unit) override virtual
Implements lldb_private::SymbolFile.
Definition at line 1151 of file SymbolFileNativePDB.cpp.
References lldb_private::npdb::PdbSymUid::asCompiland(), lldb_private::npdb::Compiland, lldb::eLanguageTypeUnknown, lldb_private::UserID::GetID(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::npdb::PdbSymUid::kind(), lldbassert, lldb_private::npdb::CompilandIndexItem::m_compile_opts, m_index, lldb_private::npdb::PdbCompilandId::modi, and TranslateLanguage().
ParseLineTable()
bool SymbolFileNativePDB::ParseLineTable (lldb_private::CompileUnit & comp_unit) override virtual
Implements lldb_private::SymbolFile.
Definition at line 1371 of file SymbolFileNativePDB.cpp.
References lldb_private::RangeDataVector< B, S, T, N, Compare >::Append(), lldb_private::LineTable::AppendLineEntryToSequence(), lldb_private::npdb::PdbSymUid::asCompiland(), lldb_private::RangeDataVector< B, S, T, N, Compare >::Clear(), lldb_private::npdb::Compiland, lldb_private::RangeData< B, S, T >::data, GetFileIndex(), lldb_private::UserID::GetID(), lldb_private::ModuleChild::GetModule(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::Range< B, S >::GetRangeBase(), lldb_private::npdb::GetSegmentOffsetAndLength(), IsFunctionEpilogue(), IsFunctionPrologue(), lldb_private::npdb::PdbSymUid::kind(), LLDB_INVALID_ADDRESS, lldbassert, lldb_private::npdb::CompilandIndexItem::m_debug_stream, lldb_private::npdb::CompilandIndexItem::m_global_line_table, m_index, m_inline_sites, lldb_private::npdb::PdbCompilandId::modi, lldb_private::npdb::SegmentOffset::offset, ParseInlineSite(), ParseSymbolArrayInScope(), lldb_private::npdb::SegmentOffset::segment, lldb_private::CompileUnit::SetLineTable(), lldb_private::Range< B, S >::SetRangeBase(), lldb_private::Range< B, S >::SetRangeEnd(), lldb_private::npdb::SegmentOffsetLength::so, lldb_private::RangeDataVector< B, S, T, N, Compare >::Sort(), and lldb_private::npdb::toOpaqueUid().
ParseSupportFiles()
bool SymbolFileNativePDB::ParseSupportFiles (lldb_private::CompileUnit & comp_unit, SupportFileList & support_files) override virtual
Implements lldb_private::SymbolFile.
Definition at line 1560 of file SymbolFileNativePDB.cpp.
References lldb_private::SupportFileList::Append(), lldb_private::npdb::PdbSymUid::asCompiland(), lldb_private::npdb::Compiland, lldb_private::UserID::GetID(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::npdb::PdbSymUid::kind(), lldbassert, lldb_private::npdb::CompilandIndexItem::m_file_list, m_index, and lldb_private::npdb::PdbCompilandId::modi.
ParseSymbolArrayInScope()
size_t SymbolFileNativePDB::ParseSymbolArrayInScope (PdbCompilandSymId parent, llvm::function_ref< bool(llvm::codeview::SymbolKind, PdbCompilandSymId)> fn) private
Definition at line 1817 of file SymbolFileNativePDB.cpp.
References lldb_private::npdb::CompilandIndexItem::m_debug_stream, m_index, lldb_private::npdb::PdbCompilandSymId::modi, and lldb_private::npdb::PdbCompilandSymId::offset.
Referenced by ParseBlocksRecursive(), and ParseLineTable().
ParseTypes()
size_t SymbolFileNativePDB::ParseTypes (lldb_private::CompileUnit & comp_unit) override virtual
Implements lldb_private::SymbolFile.
Definition at line 2126 of file SymbolFileNativePDB.cpp.
References lldb_private::npdb::CVTagRecord::create(), lldb_private::SymbolFile::GetModuleMutex(), GetOrCreateType(), GetOrCreateTypedef(), lldb_private::TypeList::GetSize(), lldb_private::SymbolFileCommon::GetTypeList(), lldb_private::npdb::IsTagRecord(), m_done_full_type_scan, m_index, and lldb_private::npdb::CVTagRecord::name().
ParseVariablesForBlock()
size_t SymbolFileNativePDB::ParseVariablesForBlock (PdbCompilandSymId block_id) private
Definition at line 2328 of file SymbolFileNativePDB.cpp.
References lldb_private::Block::GetBlockVariableList(), GetOrCreateBlock(), GetOrCreateLocalVariable(), lldbassert, lldb_private::npdb::CompilandIndexItem::m_debug_stream, m_index, lldb_private::npdb::PdbCompilandSymId::modi, lldb_private::npdb::PdbCompilandSymId::offset, ParseVariablesForBlock(), lldb_private::Block::SetDidParseVariables(), and lldb_private::Block::SetVariableList().
Referenced by ParseVariablesForBlock(), and ParseVariablesForContext().
ParseVariablesForCompileUnit()
size_t SymbolFileNativePDB::ParseVariablesForCompileUnit (CompileUnit & comp_unit, VariableList & variables) private
Definition at line 2170 of file SymbolFileNativePDB.cpp.
References lldb_private::VariableList::AddVariable(), lldb_private::npdb::Compiland, lldb_private::UserID::GetID(), GetOrCreateGlobalVariable(), lldb_private::VariableList::GetSize(), lldb_private::npdb::PdbSymUid::kind(), lldbassert, and m_index.
Referenced by ParseVariablesForContext().
ParseVariablesForContext()
size_t SymbolFileNativePDB::ParseVariablesForContext (const SymbolContext & sc) override virtual
Implements lldb_private::SymbolFile.
Definition at line 2435 of file SymbolFileNativePDB.cpp.
References lldb_private::npdb::PdbSymUid::asCompilandSym(), lldb_private::SymbolContext::block, lldb_private::SymbolContext::comp_unit, lldb_private::SymbolContext::function, lldb_private::UserID::GetID(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::CompileUnit::GetVariableList(), lldbassert, ParseVariablesForBlock(), ParseVariablesForCompileUnit(), and lldb_private::CompileUnit::SetVariableList().
ResolveSymbolContext() [1/2]
uint32_t lldb_private::npdb::SymbolFileNativePDB::ResolveSymbolContext (const Address & so_addr, lldb::SymbolContextItem resolve_scope, SymbolContext & sc) override virtual
Implements lldb_private::SymbolFile.
ResolveSymbolContext() [2/2]
uint32_t SymbolFileNativePDB::ResolveSymbolContext (const SourceLocationSpec & src_location_spec, lldb::SymbolContextItem resolve_scope, SymbolContextList & sc_list) override virtual
Reimplemented from lldb_private::SymbolFile.
Definition at line 1348 of file SymbolFileNativePDB.cpp.
References lldb_private::SourceLocationSpec::GetFileSpec(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::SymbolFileCommon::GetNumCompileUnits(), lldb_private::CompileUnit::GetPrimaryFile(), lldb_private::SymbolContextList::GetSize(), lldb_private::FileSpec::Match(), ParseCompileUnitAtIndex(), and lldb_private::CompileUnit::ResolveSymbolContext().
ResolveTypeUID()
Type * SymbolFileNativePDB::ResolveTypeUID (lldb::user_id_t type_uid) override virtual
Implements lldb_private::SymbolFile.
Definition at line 2507 of file SymbolFileNativePDB.cpp.
References lldb_private::npdb::PdbSymUid::asTypeSym(), CreateAndCacheType(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::npdb::PdbTypeSymId::index, lldb_private::npdb::PdbSymUid::kind(), lldbassert, m_types, and lldb_private::npdb::Type.
ResolveUdtDeclaration()
llvm::Expected< Declaration > SymbolFileNativePDB::ResolveUdtDeclaration (PdbTypeSymId type_id) private
Definition at line 2927 of file SymbolFileNativePDB.cpp.
References CacheUdtDeclarations(), lldb_private::npdb::PdbTypeSymId::index, m_cached_udt_declarations, m_index, and m_udt_declarations.
Referenced by CreateClassStructUnion().
StripMangledFunctionName()
llvm::StringRef SymbolFileNativePDB::StripMangledFunctionName (llvm::StringRef mangled, PdbTypeSymId func_ty) private
Definition at line 2857 of file SymbolFileNativePDB.cpp.
References error(), lldb_private::GetLog(), lldb_private::npdb::PdbTypeSymId::index, LLDB_LOG, m_index, and lldb_private::Symbols.
Referenced by FindMangledSymbol().
Terminate()
void SymbolFileNativePDB::Terminate () static
Definition at line 360 of file SymbolFileNativePDB.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Referenced by SymbolFilePDB::Terminate().
Friends And Related Symbol Documentation
UdtRecordCompleter
friend class UdtRecordCompleter friend
Definition at line 44 of file SymbolFileNativePDB.h.
References UdtRecordCompleter.
Referenced by UdtRecordCompleter.
Member Data Documentation
anonymous_id
lldb::user_id_t lldb_private::npdb::SymbolFileNativePDB::anonymous_id = LLDB_INVALID_UID - 1 private
Definition at line 302 of file SymbolFileNativePDB.h.
ID
char SymbolFileNativePDB::ID static private
LLVM RTTI support.
Definition at line 47 of file SymbolFileNativePDB.h.
Referenced by classof(), and isA().
m_allocator
llvm::BumpPtrAllocator lldb_private::npdb::SymbolFileNativePDB::m_allocator private
Definition at line 296 of file SymbolFileNativePDB.h.
Referenced by CalculateAbilities().
m_blocks
llvm::DenseMap<lldb::user_id_t, lldb::BlockSP> lldb_private::npdb::SymbolFileNativePDB::m_blocks private
Definition at line 309 of file SymbolFileNativePDB.h.
Referenced by CreateBlock(), and GetOrCreateBlock().
m_cached_udt_declarations
std::once_flag lldb_private::npdb::SymbolFileNativePDB::m_cached_udt_declarations private
Definition at line 327 of file SymbolFileNativePDB.h.
Referenced by ResolveUdtDeclaration().
m_compilands
llvm::DenseMap<lldb::user_id_t, lldb::CompUnitSP> lldb_private::npdb::SymbolFileNativePDB::m_compilands private
Definition at line 311 of file SymbolFileNativePDB.h.
Referenced by GetOrCreateCompileUnit().
m_done_full_type_scan
bool lldb_private::npdb::SymbolFileNativePDB::m_done_full_type_scan = false private
Definition at line 299 of file SymbolFileNativePDB.h.
Referenced by ParseTypes().
m_file_up
std::unique_ptr<llvm::pdb::PDBFile> lldb_private::npdb::SymbolFileNativePDB::m_file_up private
Definition at line 304 of file SymbolFileNativePDB.h.
Referenced by CalculateAbilities().
m_func_base_names
lldb_private::UniqueCStringMap<uint32_t> lldb_private::npdb::SymbolFileNativePDB::m_func_base_names private
basename -> Global ID(s)
Definition at line 334 of file SymbolFileNativePDB.h.
Referenced by CacheGlobalBaseNames(), and FindFunctions().
m_func_full_names
lldb_private::UniqueCStringMap<uint32_t> lldb_private::npdb::SymbolFileNativePDB::m_func_full_names private
mangled name/full function name -> Global ID(s)
Definition at line 332 of file SymbolFileNativePDB.h.
Referenced by CacheGlobalBaseNames(), and FindFunctions().
m_func_method_names
lldb_private::UniqueCStringMap<uint32_t> lldb_private::npdb::SymbolFileNativePDB::m_func_method_names private
method basename -> Global ID(s)
Definition at line 336 of file SymbolFileNativePDB.h.
Referenced by CacheGlobalBaseNames(), and FindFunctions().
m_functions
llvm::DenseMap<lldb::user_id_t, lldb::FunctionSP> lldb_private::npdb::SymbolFileNativePDB::m_functions private
Definition at line 310 of file SymbolFileNativePDB.h.
Referenced by GetOrCreateFunction().
m_global_variable_base_names
lldb_private::UniqueCStringMap<uint32_t> lldb_private::npdb::SymbolFileNativePDB::m_global_variable_base_names private
global variable basename -> Global ID(s)
Definition at line 339 of file SymbolFileNativePDB.h.
Referenced by CacheGlobalBaseNames(), and FindGlobalVariables().
m_global_vars
llvm::DenseMap<lldb::user_id_t, lldb::VariableSP> lldb_private::npdb::SymbolFileNativePDB::m_global_vars private
Definition at line 307 of file SymbolFileNativePDB.h.
Referenced by GetOrCreateGlobalVariable().
m_index
std::unique_ptr<PdbIndex> lldb_private::npdb::SymbolFileNativePDB::m_index private
Definition at line 305 of file SymbolFileNativePDB.h.
Referenced by AddSymbols(), BuildParentMap(), CacheGlobalBaseNames(), CacheUdtDeclarations(), CalculateAbilities(), CalculateNumCompileUnits(), CreateAndCacheType(), CreateBlock(), CreateCompileUnit(), CreateConstantSymbol(), CreateFunction(), CreateGlobalVariable(), CreateLocalVariable(), CreateModifierType(), CreateSimpleArgumentListTypes(), CreateType(), CreateTypedef(), FindFunctions(), FindMangledFunctionName(), FindMangledSymbol(), FindSymbolScope(), FindTypesByName(), GetContextForType(), GetDebugInfoSize(), GetIndex(), GetPDBFile(), GetPDBFile(), InitializeObject(), ParseCompileUnitAtIndex(), ParseFunctions(), ParseInlineSite(), ParseLanguage(), ParseLineTable(), ParseSupportFiles(), ParseSymbolArrayInScope(), ParseTypes(), ParseVariablesForBlock(), ParseVariablesForCompileUnit(), ResolveUdtDeclaration(), and StripMangledFunctionName().
m_inline_sites
llvm::DenseMap<lldb::user_id_t, std::shared_ptr<InlineSite> > lldb_private::npdb::SymbolFileNativePDB::m_inline_sites private
Definition at line 313 of file SymbolFileNativePDB.h.
Referenced by CreateBlock(), ParseBlocksRecursive(), ParseInlineSite(), and ParseLineTable().
m_local_variables
llvm::DenseMap<lldb::user_id_t, lldb::VariableSP> lldb_private::npdb::SymbolFileNativePDB::m_local_variables private
Definition at line 308 of file SymbolFileNativePDB.h.
Referenced by CreateLocalVariable(), and GetOrCreateLocalVariable().
m_obj_load_address
lldb::addr_t lldb_private::npdb::SymbolFileNativePDB::m_obj_load_address = 0 private
Definition at line 298 of file SymbolFileNativePDB.h.
Referenced by InitializeObject().
m_parent_types
llvm::DenseMap<llvm::codeview::TypeIndex, llvm::codeview::TypeIndex> lldb_private::npdb::SymbolFileNativePDB::m_parent_types private
Definition at line 315 of file SymbolFileNativePDB.h.
Referenced by BuildParentMap(), and GetParentType().
m_type_base_names
lldb_private::UniqueCStringMap<uint32_t> lldb_private::npdb::SymbolFileNativePDB::m_type_base_names private
Definition at line 329 of file SymbolFileNativePDB.h.
Referenced by BuildParentMap(), and FindTypes().
m_types
llvm::DenseMap<lldb::user_id_t, lldb::TypeSP> lldb_private::npdb::SymbolFileNativePDB::m_types private
Definition at line 312 of file SymbolFileNativePDB.h.
Referenced by CreateAndCacheType(), GetOrCreateType(), GetOrCreateTypedef(), and ResolveTypeUID().
m_udt_declarations
llvm::DenseMap<llvm::codeview::TypeIndex, UdtDeclaration> lldb_private::npdb::SymbolFileNativePDB::m_udt_declarations private
Definition at line 326 of file SymbolFileNativePDB.h.
Referenced by CacheUdtDeclarations(), and ResolveUdtDeclaration().
The documentation for this class was generated from the following files:
SymbolFileNativePDB.h
SymbolFileNativePDB.cpp