LLDB: lldb_private::ctf::TraceExporterCTF Class Reference
lldb_private::ctf::TraceExporterCTF Class Reference
Trace Exporter Plugin that can produce traces in Chrome Trace Format.
#include <TraceExporterCTF.h>
Public Member Functions
~TraceExporterCTF () override=default
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
llvm::StringRef GetPluginName () override
static llvm::Expected< lldb::TraceExporterUP > CreateInstance ()
PluginInterface protocol.
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
Additional Inherited Members
Static Public Member Functions inherited from lldb_private::TraceExporter
static llvm::Expected< lldb::TraceExporterUP > FindPlugin (llvm::StringRef plugin_name)
Create an instance of a trace exporter plugin given its name.
Detailed Description
Trace Exporter Plugin that can produce traces in Chrome Trace Format.
Still in development.
Definition at line 19 of file TraceExporterCTF.h.
Constructor & Destructor Documentation
~TraceExporterCTF()
lldb_private::ctf::TraceExporterCTF::~TraceExporterCTF () override default
Member Function Documentation
CreateInstance()
Expected< TraceExporterUP > TraceExporterCTF::CreateInstance () static
PluginInterface protocol.
Definition at line 42 of file TraceExporterCTF.cpp.
Referenced by Initialize(), and Terminate().
GetPluginName()
llvm::StringRef lldb_private::ctf::TraceExporterCTF::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 27 of file TraceExporterCTF.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::ctf::TraceExporterCTF::GetPluginNameStatic () inline static
Definition at line 35 of file TraceExporterCTF.h.
Referenced by GetPluginName(), and Initialize().
Initialize()
void TraceExporterCTF::Initialize () static
Definition at line 32 of file TraceExporterCTF.cpp.
References CreateInstance(), GetPluginNameStatic(), GetThreadTraceExportCommand(), and lldb_private::PluginManager::RegisterPlugin().
Terminate()
void TraceExporterCTF::Terminate () static
Definition at line 38 of file TraceExporterCTF.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
The documentation for this class was generated from the following files:
TraceExporterCTF.h
TraceExporterCTF.cpp