LLDB: lldb_private::CommandObjectMultiword Class Reference
lldb_private::CommandObjectMultiword Class Reference
#include <CommandObjectMultiword.h>
Inherits lldb_private::CommandObject.
Inherited by CommandObjectBreakpointAdd, CommandObjectBreakpointName, CommandObjectCommandContainer, CommandObjectFrameRecognizer, CommandObjectLogTimer, CommandObjectMultiwordCommandsScript, CommandObjectMultiwordItaniumABI, CommandObjectMultiwordObjC, CommandObjectMultiwordObjC_ClassTable, CommandObjectMultiwordObjC_TaggedPointer, CommandObjectMultiwordProcessGDBRemote, CommandObjectMultiwordProcessKDP, CommandObjectMultiwordProcessMinidump, CommandObjectMultiwordProcessTrace, CommandObjectMultiwordScriptingExtension, CommandObjectMultiwordTargetStopHooks, CommandObjectMultiwordThreadPlan, CommandObjectMultiwordTrace, CommandObjectMultiwordTraceDump, CommandObjectPlatformFile, CommandObjectPlatformProcess, CommandObjectProcessGDBRemotePacket, CommandObjectProcessKDPPacket, CommandObjectSourceCache, CommandObjectTargetDump, CommandObjectTargetFrameProvider, CommandObjectTargetModules, CommandObjectTargetModulesDump, CommandObjectTargetModulesImageSearchPaths, CommandObjectTargetSymbols, CommandObjectTraceExport, CommandObjectTypeCategory, CommandObjectTypeFilter, CommandObjectTypeFormat, CommandObjectTypeSummary, CommandObjectTypeSynth, CommandObjectWatchpointSet, lldb_private::CommandObjectBreakpointCommand, lldb_private::CommandObjectDiagnostics, lldb_private::CommandObjectLanguage, lldb_private::CommandObjectLog, lldb_private::CommandObjectMemory, lldb_private::CommandObjectMemoryTag, lldb_private::CommandObjectMultiwordBreakpoint, lldb_private::CommandObjectMultiwordCommands, lldb_private::CommandObjectMultiwordFrame, lldb_private::CommandObjectMultiwordProcess, lldb_private::CommandObjectMultiwordScripting, lldb_private::CommandObjectMultiwordSettings, lldb_private::CommandObjectMultiwordSource, lldb_private::CommandObjectMultiwordTarget, lldb_private::CommandObjectMultiwordThread, lldb_private::CommandObjectMultiwordWatchpoint, lldb_private::CommandObjectPlatform, lldb_private::CommandObjectPlugin, lldb_private::CommandObjectProtocolServer, lldb_private::CommandObjectRegister, lldb_private::CommandObjectSession, lldb_private::CommandObjectStats, lldb_private::CommandObjectTrace, lldb_private::CommandObjectType, lldb_private::CommandObjectWatchpointCommand, and sddarwinlog_private::BaseCommand.
Public Member Functions
CommandObjectMultiword (CommandInterpreter &interpreter, const char *name, const char *help=nullptr, const char *syntax=nullptr, uint32_t flags=0)
~CommandObjectMultiword () override
bool IsMultiwordObject () override
CommandObjectMultiword * GetAsMultiwordCommand () override
bool LoadSubCommand (llvm::StringRef cmd_name, const lldb::CommandObjectSP &command_obj) override
llvm::Error LoadUserSubcommand (llvm::StringRef cmd_name, const lldb::CommandObjectSP &command_obj, bool can_replace) override
llvm::Error RemoveUserSubcommand (llvm::StringRef cmd_name, bool multiword_okay)
void GenerateHelpText (Stream &output_stream) override
lldb::CommandObjectSP GetSubcommandSP (llvm::StringRef sub_cmd, StringList *matches=nullptr) override
lldb::CommandObjectSP GetSubcommandSPExact (llvm::StringRef sub_cmd) override
CommandObject * GetSubcommandObject (llvm::StringRef sub_cmd, StringList *matches=nullptr) override
bool WantsRawCommandString () override
void HandleCompletion (CompletionRequest &request) override
This default version handles calling option argument completions and then calls HandleArgumentCompletion if the cursor is on an argument, not an option.
std::optional< std::string > GetRepeatCommand (Args &current_command_args, uint32_t index) override
Get the command that appropriate for a "repeat" of the current command.
void Execute (const char *args_string, CommandReturnObject &result) override
bool IsRemovable () const override
void SetRemovable (bool removable)
Public Member Functions inherited from lldb_private::CommandObject
CommandObject (CommandInterpreter &interpreter, llvm::StringRef name, llvm::StringRef help="", llvm::StringRef syntax="", uint32_t flags=0)
virtual ~CommandObject ()=default
CommandInterpreter & GetCommandInterpreter ()
Debugger & GetDebugger ()
virtual llvm::StringRef GetHelp ()
virtual llvm::StringRef GetHelpLong ()
virtual llvm::StringRef GetSyntax ()
llvm::StringRef GetCommandName () const
virtual void SetHelp (llvm::StringRef str)
virtual void SetHelpLong (llvm::StringRef str)
void SetSyntax (llvm::StringRef str)
bool IsUserCommand ()
void SetIsUserCommand (bool is_user)
virtual bool IsAlias ()
virtual bool IsDashDashCommand ()
void FormatLongHelpText (Stream &output_strm, llvm::StringRef long_help)
void GenerateHelpText (CommandReturnObject &result)
virtual bool WantsCompletion ()
virtual Options * GetOptions ()
void AddSimpleArgumentList (lldb::CommandArgumentType arg_type, ArgumentRepetitionType repetition_type=eArgRepeatPlain)
void AddIDsArgumentData (IDType type)
int GetNumArgumentEntries ()
CommandArgumentEntry * GetArgumentEntryAtIndex (int idx)
void GetFormattedCommandArguments (Stream &str, uint32_t opt_set_mask=LLDB_OPT_SET_ALL)
bool ParseOptions (Args &args, CommandReturnObject &result)
void SetCommandName (llvm::StringRef name)
virtual void HandleArgumentCompletion (CompletionRequest &request, OptionElementVector &opt_element_vector)
The default version handles argument definitions that have only one argument type, and use one of the argument types that have an entry in the CommonCompletions.
bool HelpTextContainsWord (llvm::StringRef search_word, bool search_short_help=true, bool search_long_help=true, bool search_syntax=true, bool search_options=true)
Flags & GetFlags ()
The flags accessor.
const Flags & GetFlags () const
The flags const accessor.
bool HasOverrideCallback () const
void SetOverrideCallback (lldb::CommandOverrideCallback callback, void *baton)
void SetOverrideCallback (lldb_private::CommandOverrideCallbackWithResult callback, void *baton)
bool InvokeOverrideCallback (const char **argv, CommandReturnObject &result)
void SetOriginalCommandString (std::string s)
Set the command input as it appeared in the terminal.
Protected Member Functions
CommandObject::CommandMap & GetSubcommandDictionary ()
std::string GetSubcommandsHintText ()
Protected Member Functions inherited from lldb_private::CommandObject
bool ParseOptionsAndNotify (Args &args, CommandReturnObject &result, OptionGroupOptions &group_options, ExecutionContext &exe_ctx)
virtual const char * GetInvalidTargetDescription ()
virtual const char * GetInvalidProcessDescription ()
virtual const char * GetInvalidThreadDescription ()
virtual const char * GetInvalidFrameDescription ()
virtual const char * GetInvalidRegContextDescription ()
Target & GetDummyTarget ()
Target & GetTarget ()
Thread * GetDefaultThread ()
bool CheckRequirements (CommandReturnObject &result)
Check the command to make sure anything required by this command is available.
void Cleanup ()
Protected Attributes
CommandObject::CommandMap m_subcommand_dict
bool m_can_be_removed
Protected Attributes inherited from lldb_private::CommandObject
CommandInterpreter & m_interpreter
ExecutionContext m_exe_ctx
std::unique_lock< std::recursive_mutex > m_api_locker
std::string m_cmd_name
std::string m_cmd_help_short
std::string m_cmd_help_long
std::string m_cmd_syntax
std::string m_original_command
Flags m_flags
std::vector< CommandArgumentEntry > m_arguments
lldb::CommandOverrideCallback m_deprecated_command_override_callback
lldb_private::CommandOverrideCallbackWithResult m_command_override_callback
void * m_command_override_baton
bool m_is_user_command = false
Friends
class CommandInterpreter
class CommandObjectSyntax
Additional Inherited Members
Public Types inherited from lldb_private::CommandObject
enum IDType { eBreakpointArgs = 0 , eWatchpointArgs = 1 }
typedef llvm::StringRef ArgumentHelpCallbackFunction()
typedef std::vector< CommandArgumentData > CommandArgumentEntry
typedef std::map< std::string, lldb::CommandObjectSP, std::less<> > CommandMap
Static Public Member Functions inherited from lldb_private::CommandObject
static const char * GetArgumentTypeAsCString (const lldb::CommandArgumentType arg_type)
static const char * GetArgumentDescriptionAsCString (const lldb::CommandArgumentType arg_type)
static lldb::CommandArgumentType LookupArgumentName (llvm::StringRef arg_name)
static const ArgumentTableEntry * FindArgumentDataByType (lldb::CommandArgumentType arg_type)
static void GetArgumentHelp (Stream &str, lldb::CommandArgumentType arg_type, CommandInterpreter &interpreter)
static const char * GetArgumentName (lldb::CommandArgumentType arg_type)
static bool IsPairType (ArgumentRepetitionType arg_repeat_type)
static std::optional< ArgumentRepetitionType > ArgRepetitionFromString (llvm::StringRef string)
Detailed Description
Definition at line 20 of file CommandObjectMultiword.h.
Constructor & Destructor Documentation
CommandObjectMultiword()
CommandObjectMultiword::CommandObjectMultiword (CommandInterpreter & interpreter, const char * name, const char * help = nullptr, const char * syntax = nullptr, uint32_t flags = 0)
Definition at line 20 of file CommandObjectMultiword.cpp.
References CommandInterpreter, lldb_private::CommandObject::CommandObject(), and m_can_be_removed.
Referenced by sddarwinlog_private::BaseCommand::BaseCommand(), CommandObjectBreakpointAdd::CommandObjectBreakpointAdd(), lldb_private::CommandObjectBreakpointCommand::CommandObjectBreakpointCommand(), CommandObjectBreakpointName::CommandObjectBreakpointName(), CommandObjectCommandContainer::CommandObjectCommandContainer(), lldb_private::CommandObjectDiagnostics::CommandObjectDiagnostics(), CommandObjectFrameRecognizer::CommandObjectFrameRecognizer(), lldb_private::CommandObjectLanguage::CommandObjectLanguage(), lldb_private::CommandObjectLog::CommandObjectLog(), CommandObjectLogTimer::CommandObjectLogTimer(), lldb_private::CommandObjectMemory::CommandObjectMemory(), lldb_private::CommandObjectMemoryTag::CommandObjectMemoryTag(), lldb_private::CommandObjectMultiwordBreakpoint::CommandObjectMultiwordBreakpoint(), lldb_private::CommandObjectMultiwordCommands::CommandObjectMultiwordCommands(), CommandObjectMultiwordCommandsScript::CommandObjectMultiwordCommandsScript(), lldb_private::CommandObjectMultiwordFrame::CommandObjectMultiwordFrame(), CommandObjectMultiwordItaniumABI::CommandObjectMultiwordItaniumABI(), CommandObjectMultiwordObjC::CommandObjectMultiwordObjC(), CommandObjectMultiwordObjC_ClassTable::CommandObjectMultiwordObjC_ClassTable(), CommandObjectMultiwordObjC_TaggedPointer::CommandObjectMultiwordObjC_TaggedPointer(), lldb_private::CommandObjectMultiwordProcess::CommandObjectMultiwordProcess(), CommandObjectMultiwordProcessGDBRemote::CommandObjectMultiwordProcessGDBRemote(), CommandObjectMultiwordProcessKDP::CommandObjectMultiwordProcessKDP(), CommandObjectMultiwordProcessMinidump::CommandObjectMultiwordProcessMinidump(), CommandObjectMultiwordProcessTrace::CommandObjectMultiwordProcessTrace(), lldb_private::CommandObjectMultiwordScripting::CommandObjectMultiwordScripting(), CommandObjectMultiwordScriptingExtension::CommandObjectMultiwordScriptingExtension(), lldb_private::CommandObjectMultiwordSettings::CommandObjectMultiwordSettings(), lldb_private::CommandObjectMultiwordSource::CommandObjectMultiwordSource(), lldb_private::CommandObjectMultiwordTarget::CommandObjectMultiwordTarget(), CommandObjectMultiwordTargetStopHooks::CommandObjectMultiwordTargetStopHooks(), lldb_private::CommandObjectMultiwordThread::CommandObjectMultiwordThread(), CommandObjectMultiwordThreadPlan::CommandObjectMultiwordThreadPlan(), CommandObjectMultiwordTrace::CommandObjectMultiwordTrace(), CommandObjectMultiwordTraceDump::CommandObjectMultiwordTraceDump(), lldb_private::CommandObjectMultiwordWatchpoint::CommandObjectMultiwordWatchpoint(), lldb_private::CommandObjectPlatform::CommandObjectPlatform(), CommandObjectPlatformFile::CommandObjectPlatformFile(), CommandObjectPlatformProcess::CommandObjectPlatformProcess(), lldb_private::CommandObjectPlugin::CommandObjectPlugin(), CommandObjectProcessGDBRemotePacket::CommandObjectProcessGDBRemotePacket(), CommandObjectProcessKDPPacket::CommandObjectProcessKDPPacket(), lldb_private::CommandObjectProtocolServer::CommandObjectProtocolServer(), lldb_private::CommandObjectRegister::CommandObjectRegister(), lldb_private::CommandObjectSession::CommandObjectSession(), CommandObjectSourceCache::CommandObjectSourceCache(), lldb_private::CommandObjectStats::CommandObjectStats(), CommandObjectTargetDump::CommandObjectTargetDump(), CommandObjectTargetFrameProvider::CommandObjectTargetFrameProvider(), CommandObjectTargetModules::CommandObjectTargetModules(), CommandObjectTargetModulesDump::CommandObjectTargetModulesDump(), CommandObjectTargetModulesImageSearchPaths::CommandObjectTargetModulesImageSearchPaths(), CommandObjectTargetSymbols::CommandObjectTargetSymbols(), lldb_private::CommandObjectTrace::CommandObjectTrace(), CommandObjectTraceExport::CommandObjectTraceExport(), lldb_private::CommandObjectWatchpointCommand::CommandObjectWatchpointCommand(), CommandObjectWatchpointSet::CommandObjectWatchpointSet(), GetAsMultiwordCommand(), CommandObjectTypeCategory::~CommandObjectTypeCategory(), and CommandObjectTypeSummary::~CommandObjectTypeSummary().
~CommandObjectMultiword()
CommandObjectMultiword::~CommandObjectMultiword () override default
Member Function Documentation
Execute()
void CommandObjectMultiword::Execute (const char * args_string, CommandReturnObject & result) override virtual
Parameters
offset_in_command is on what column args_string appears, if applicable. This enables diagnostics that refer back to the user input.
Implements lldb_private::CommandObject.
Definition at line 151 of file CommandObjectMultiword.cpp.
References lldb_private::CommandReturnObject::AppendError(), lldb_private::CommandReturnObject::AppendErrorWithFormat(), lldb_private::CommandObject::CommandObject(), lldb_private::CommandObject::Execute(), lldb_private::CommandObject::GenerateHelpText(), lldb_private::Args::GetArgumentCount(), lldb_private::CommandObject::GetCommandName(), lldb_private::StringList::GetSize(), GetSubcommandObject(), GetSubcommandsHintText(), m_subcommand_dict, and lldb_private::Args::Shift().
GenerateHelpText()
void CommandObjectMultiword::GenerateHelpText (Stream & output_stream) override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 233 of file CommandObjectMultiword.cpp.
References lldb_private::FindLongestCommandWord(), lldb_private::CommandObject::GenerateHelpText(), lldb_private::CommandObject::m_interpreter, m_subcommand_dict, and lldb_private::Stream::PutCString().
GetAsMultiwordCommand()
CommandObjectMultiword * lldb_private::CommandObjectMultiword::GetAsMultiwordCommand () inline override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 34 of file CommandObjectMultiword.h.
References CommandObjectMultiword().
Referenced by lldb_private::CommandInterpreter::GetCommandSP().
GetRepeatCommand()
std::optional< std::string > CommandObjectMultiword::GetRepeatCommand (Args & current_command_args, uint32_t index) override virtual
Get the command that appropriate for a "repeat" of the current command.
Parameters
[in] current_command_args The command arguments.
[in] index This is for internal use - it is how the completion request is tracked in CommandObjectMultiword, and should otherwise be ignored.
Returns
std::nullopt if there is no special repeat command - it will use the current command line. Otherwise a std::string containing the command to be repeated. If the string is empty, the command won't be allow repeating.
Reimplemented from lldb_private::CommandObject.
Definition at line 303 of file CommandObjectMultiword.cpp.
References lldb_private::CommandObject::CommandObject(), lldb_private::Args::GetArgumentCount(), lldb_private::CommandObject::GetRepeatCommand(), and GetSubcommandObject().
GetSubcommandDictionary()
CommandObject::CommandMap & lldb_private::CommandObjectMultiword::GetSubcommandDictionary () inline protected
Definition at line 69 of file CommandObjectMultiword.h.
References m_subcommand_dict.
Referenced by lldb_private::CommandInterpreter::GetCommandSP().
GetSubcommandObject()
CommandObject * CommandObjectMultiword::GetSubcommandObject (llvm::StringRef sub_cmd, StringList * matches = nullptr) override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 76 of file CommandObjectMultiword.cpp.
References GetSubcommandSP().
Referenced by lldb_private::CommandCompletions::CompleteModifiableCmdPathArgs(), Execute(), GetRepeatCommand(), and HandleCompletion().
GetSubcommandsHintText()
std::string CommandObjectMultiword::GetSubcommandsHintText () protected
Definition at line 210 of file CommandObjectMultiword.cpp.
References m_subcommand_dict.
Referenced by Execute().
GetSubcommandSP()
CommandObjectSP CommandObjectMultiword::GetSubcommandSP (llvm::StringRef sub_cmd, StringList * matches = nullptr) override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 42 of file CommandObjectMultiword.cpp.
References lldb_private::AddNamesMatchingPartialString(), lldb_private::StringList::AppendString(), lldb_private::StringList::GetStringAtIndex(), GetSubcommandSPExact(), and m_subcommand_dict.
Referenced by GetSubcommandObject().
GetSubcommandSPExact()
CommandObjectSP CommandObjectMultiword::GetSubcommandSPExact (llvm::StringRef sub_cmd) override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 31 of file CommandObjectMultiword.cpp.
References m_subcommand_dict.
Referenced by GetSubcommandSP(), and lldb_private::CommandInterpreter::VerifyUserMultiwordCmdPath().
HandleCompletion()
void CommandObjectMultiword::HandleCompletion (CompletionRequest & request) override virtual
This default version handles calling option argument completions and then calls HandleArgumentCompletion if the cursor is on an argument, not an option.
Don't override this method, override HandleArgumentCompletion instead unless you have special reasons.
Parameters
[in,out] request The completion request that needs to be answered.
Reimplemented from lldb_private::CommandObject.
Definition at line 264 of file CommandObjectMultiword.cpp.
References lldb_private::CompletionRequest::AddCompletions(), lldb_private::AddNamesMatchingPartialString(), lldb_private::CompletionRequest::AppendEmptyArgument(), lldb_private::CommandObject::CommandObject(), lldb_private::StringList::DeleteStringAtIndex(), lldb_private::Args::GetArgumentCount(), lldb_private::CompletionRequest::GetCursorIndex(), lldb_private::CompletionRequest::GetParsedLine(), lldb_private::StringList::GetSize(), lldb_private::StringList::GetStringAtIndex(), GetSubcommandObject(), lldb_private::CommandObject::HandleCompletion(), m_subcommand_dict, lldb_private::Args::Shift(), and lldb_private::CompletionRequest::ShiftArguments().
IsMultiwordObject()
bool lldb_private::CommandObjectMultiword::IsMultiwordObject () inline override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 32 of file CommandObjectMultiword.h.
IsRemovable()
bool lldb_private::CommandObjectMultiword::IsRemovable () const inline override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 64 of file CommandObjectMultiword.h.
References m_can_be_removed.
LoadSubCommand()
bool CommandObjectMultiword::LoadSubCommand (llvm::StringRef cmd_name, const lldb::CommandObjectSP & command_obj) override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 81 of file CommandObjectMultiword.cpp.
References lldb_private::CommandObject::GetCommandInterpreter(), lldbassert, and m_subcommand_dict.
Referenced by sddarwinlog_private::BaseCommand::BaseCommand(), CommandObjectBreakpointAdd::CommandObjectBreakpointAdd(), lldb_private::CommandObjectBreakpointCommand::CommandObjectBreakpointCommand(), CommandObjectCommandContainer::CommandObjectCommandContainer(), lldb_private::CommandObjectDiagnostics::CommandObjectDiagnostics(), CommandObjectFrameRecognizer::CommandObjectFrameRecognizer(), lldb_private::CommandObjectLog::CommandObjectLog(), CommandObjectLogTimer::CommandObjectLogTimer(), lldb_private::CommandObjectMemory::CommandObjectMemory(), lldb_private::CommandObjectMemoryTag::CommandObjectMemoryTag(), lldb_private::CommandObjectMultiwordBreakpoint::CommandObjectMultiwordBreakpoint(), lldb_private::CommandObjectMultiwordCommands::CommandObjectMultiwordCommands(), CommandObjectMultiwordCommandsScript::CommandObjectMultiwordCommandsScript(), lldb_private::CommandObjectMultiwordFrame::CommandObjectMultiwordFrame(), CommandObjectMultiwordItaniumABI::CommandObjectMultiwordItaniumABI(), CommandObjectMultiwordObjC::CommandObjectMultiwordObjC(), CommandObjectMultiwordObjC_ClassTable::CommandObjectMultiwordObjC_ClassTable(), CommandObjectMultiwordObjC_TaggedPointer::CommandObjectMultiwordObjC_TaggedPointer(), lldb_private::CommandObjectMultiwordProcess::CommandObjectMultiwordProcess(), CommandObjectMultiwordProcessGDBRemote::CommandObjectMultiwordProcessGDBRemote(), CommandObjectMultiwordProcessKDP::CommandObjectMultiwordProcessKDP(), CommandObjectMultiwordProcessMinidump::CommandObjectMultiwordProcessMinidump(), CommandObjectMultiwordProcessTrace::CommandObjectMultiwordProcessTrace(), lldb_private::CommandObjectMultiwordScripting::CommandObjectMultiwordScripting(), CommandObjectMultiwordScriptingExtension::CommandObjectMultiwordScriptingExtension(), lldb_private::CommandObjectMultiwordSettings::CommandObjectMultiwordSettings(), lldb_private::CommandObjectMultiwordSource::CommandObjectMultiwordSource(), lldb_private::CommandObjectMultiwordTarget::CommandObjectMultiwordTarget(), CommandObjectMultiwordTargetStopHooks::CommandObjectMultiwordTargetStopHooks(), lldb_private::CommandObjectMultiwordThread::CommandObjectMultiwordThread(), CommandObjectMultiwordThreadPlan::CommandObjectMultiwordThreadPlan(), CommandObjectMultiwordTrace::CommandObjectMultiwordTrace(), CommandObjectMultiwordTraceDump::CommandObjectMultiwordTraceDump(), lldb_private::CommandObjectMultiwordWatchpoint::CommandObjectMultiwordWatchpoint(), lldb_private::CommandObjectPlatform::CommandObjectPlatform(), CommandObjectPlatformFile::CommandObjectPlatformFile(), CommandObjectPlatformProcess::CommandObjectPlatformProcess(), lldb_private::CommandObjectPlugin::CommandObjectPlugin(), CommandObjectProcessGDBRemotePacket::CommandObjectProcessGDBRemotePacket(), CommandObjectProcessKDPPacket::CommandObjectProcessKDPPacket(), lldb_private::CommandObjectProtocolServer::CommandObjectProtocolServer(), lldb_private::CommandObjectRegister::CommandObjectRegister(), lldb_private::CommandObjectSession::CommandObjectSession(), CommandObjectSourceCache::CommandObjectSourceCache(), lldb_private::CommandObjectStats::CommandObjectStats(), CommandObjectTargetDump::CommandObjectTargetDump(), CommandObjectTargetFrameProvider::CommandObjectTargetFrameProvider(), CommandObjectTargetModules::CommandObjectTargetModules(), CommandObjectTargetModulesDump::CommandObjectTargetModulesDump(), CommandObjectTargetModulesImageSearchPaths::CommandObjectTargetModulesImageSearchPaths(), CommandObjectTargetSymbols::CommandObjectTargetSymbols(), lldb_private::CommandObjectTrace::CommandObjectTrace(), CommandObjectTraceExport::CommandObjectTraceExport(), lldb_private::CommandObjectWatchpointCommand::CommandObjectWatchpointCommand(), CommandObjectWatchpointSet::CommandObjectWatchpointSet(), and CommandObjectTypeSummary::~CommandObjectTypeSummary().
LoadUserSubcommand()
llvm::Error CommandObjectMultiword::LoadUserSubcommand (llvm::StringRef cmd_name, const lldb::CommandObjectSP & command_obj, bool can_replace) override virtual
Reimplemented from lldb_private::CommandObject.
Definition at line 90 of file CommandObjectMultiword.cpp.
References lldb_private::CommandObject::GetCommandInterpreter(), lldb_private::CommandObject::IsUserCommand(), lldbassert, and m_subcommand_dict.
Referenced by CommandObjectCommandsContainerAdd::DoExecute().
RemoveUserSubcommand()
llvm::Error CommandObjectMultiword::RemoveUserSubcommand (llvm::StringRef cmd_name, bool multiword_okay)
Definition at line 122 of file CommandObjectMultiword.cpp.
References m_subcommand_dict.
Referenced by CommandObjectCommandsContainerDelete::DoExecute(), and CommandObjectCommandsScriptDelete::DoExecute().
SetRemovable()
void lldb_private::CommandObjectMultiword::SetRemovable (bool removable) inline
Definition at line 66 of file CommandObjectMultiword.h.
References m_can_be_removed.
Referenced by lldb::SBCommand::AddMultiwordCommand().
WantsRawCommandString()
bool lldb_private::CommandObjectMultiword::WantsRawCommandString () inline override virtual
Implements lldb_private::CommandObject.
Definition at line 55 of file CommandObjectMultiword.h.
Friends And Related Symbol Documentation
CommandInterpreter
friend class CommandInterpreter friend
Definition at line 22 of file CommandObjectMultiword.h.
References CommandInterpreter.
Referenced by sddarwinlog_private::BaseCommand::BaseCommand(), CommandInterpreter, CommandObjectBreakpointAdd::CommandObjectBreakpointAdd(), lldb_private::CommandObjectBreakpointCommand::CommandObjectBreakpointCommand(), CommandObjectBreakpointName::CommandObjectBreakpointName(), CommandObjectCommandContainer::CommandObjectCommandContainer(), lldb_private::CommandObjectDiagnostics::CommandObjectDiagnostics(), CommandObjectFrameRecognizer::CommandObjectFrameRecognizer(), lldb_private::CommandObjectLanguage::CommandObjectLanguage(), lldb_private::CommandObjectLog::CommandObjectLog(), CommandObjectLogTimer::CommandObjectLogTimer(), lldb_private::CommandObjectMemory::CommandObjectMemory(), lldb_private::CommandObjectMemoryTag::CommandObjectMemoryTag(), CommandObjectMultiword(), lldb_private::CommandObjectMultiwordBreakpoint::CommandObjectMultiwordBreakpoint(), lldb_private::CommandObjectMultiwordCommands::CommandObjectMultiwordCommands(), CommandObjectMultiwordCommandsScript::CommandObjectMultiwordCommandsScript(), lldb_private::CommandObjectMultiwordFrame::CommandObjectMultiwordFrame(), CommandObjectMultiwordItaniumABI::CommandObjectMultiwordItaniumABI(), CommandObjectMultiwordObjC::CommandObjectMultiwordObjC(), CommandObjectMultiwordObjC_ClassTable::CommandObjectMultiwordObjC_ClassTable(), CommandObjectMultiwordObjC_TaggedPointer::CommandObjectMultiwordObjC_TaggedPointer(), lldb_private::CommandObjectMultiwordProcess::CommandObjectMultiwordProcess(), CommandObjectMultiwordProcessGDBRemote::CommandObjectMultiwordProcessGDBRemote(), CommandObjectMultiwordProcessKDP::CommandObjectMultiwordProcessKDP(), CommandObjectMultiwordProcessMinidump::CommandObjectMultiwordProcessMinidump(), CommandObjectMultiwordProcessTrace::CommandObjectMultiwordProcessTrace(), lldb_private::CommandObjectMultiwordScripting::CommandObjectMultiwordScripting(), CommandObjectMultiwordScriptingExtension::CommandObjectMultiwordScriptingExtension(), lldb_private::CommandObjectMultiwordSettings::CommandObjectMultiwordSettings(), lldb_private::CommandObjectMultiwordSource::CommandObjectMultiwordSource(), lldb_private::CommandObjectMultiwordTarget::CommandObjectMultiwordTarget(), CommandObjectMultiwordTargetStopHooks::CommandObjectMultiwordTargetStopHooks(), lldb_private::CommandObjectMultiwordThread::CommandObjectMultiwordThread(), CommandObjectMultiwordThreadPlan::CommandObjectMultiwordThreadPlan(), CommandObjectMultiwordTrace::CommandObjectMultiwordTrace(), CommandObjectMultiwordTraceDump::CommandObjectMultiwordTraceDump(), lldb_private::CommandObjectMultiwordWatchpoint::CommandObjectMultiwordWatchpoint(), lldb_private::CommandObjectPlatform::CommandObjectPlatform(), CommandObjectPlatformFile::CommandObjectPlatformFile(), CommandObjectPlatformProcess::CommandObjectPlatformProcess(), lldb_private::CommandObjectPlugin::CommandObjectPlugin(), CommandObjectProcessGDBRemotePacket::CommandObjectProcessGDBRemotePacket(), CommandObjectProcessKDPPacket::CommandObjectProcessKDPPacket(), lldb_private::CommandObjectProtocolServer::CommandObjectProtocolServer(), lldb_private::CommandObjectRegister::CommandObjectRegister(), lldb_private::CommandObjectSession::CommandObjectSession(), CommandObjectSourceCache::CommandObjectSourceCache(), lldb_private::CommandObjectStats::CommandObjectStats(), CommandObjectSyntax, CommandObjectTargetDump::CommandObjectTargetDump(), CommandObjectTargetFrameProvider::CommandObjectTargetFrameProvider(), CommandObjectTargetModules::CommandObjectTargetModules(), CommandObjectTargetModulesDump::CommandObjectTargetModulesDump(), CommandObjectTargetModulesImageSearchPaths::CommandObjectTargetModulesImageSearchPaths(), CommandObjectTargetSymbols::CommandObjectTargetSymbols(), lldb_private::CommandObjectTrace::CommandObjectTrace(), CommandObjectTraceExport::CommandObjectTraceExport(), lldb_private::CommandObjectWatchpointCommand::CommandObjectWatchpointCommand(), CommandObjectWatchpointSet::CommandObjectWatchpointSet(), and CommandObjectTypeSummary::~CommandObjectTypeSummary().
CommandObjectSyntax
friend class CommandObjectSyntax friend
Definition at line 23 of file CommandObjectMultiword.h.
References CommandInterpreter, and CommandObjectSyntax.
Referenced by CommandObjectSyntax.
Member Data Documentation
m_can_be_removed
bool lldb_private::CommandObjectMultiword::m_can_be_removed protected
Definition at line 76 of file CommandObjectMultiword.h.
Referenced by CommandObjectMultiword(), IsRemovable(), and SetRemovable().
m_subcommand_dict
CommandObject::CommandMap lldb_private::CommandObjectMultiword::m_subcommand_dict protected
Definition at line 75 of file CommandObjectMultiword.h.
Referenced by Execute(), GenerateHelpText(), GetSubcommandDictionary(), GetSubcommandsHintText(), GetSubcommandSP(), GetSubcommandSPExact(), HandleCompletion(), LoadSubCommand(), LoadUserSubcommand(), and RemoveUserSubcommand().
The documentation for this class was generated from the following files:
CommandObjectMultiword.h
CommandObjectMultiword.cpp