LLDB: lldb_private::Watchpoint::WatchpointEventData Class Reference
lldb_private::Watchpoint::WatchpointEventData Class Reference
#include <Watchpoint.h>
Public Member Functions
WatchpointEventData (lldb::WatchpointEventType sub_type, const lldb::WatchpointSP &new_watchpoint_sp)
~WatchpointEventData () override
llvm::StringRef GetFlavor () const override
lldb::WatchpointEventType GetWatchpointEventType () const
lldb::WatchpointSP & GetWatchpoint ()
void Dump (Stream *s) const override
Public Member Functions inherited from lldb_private::EventData
EventData ()
virtual ~EventData ()
virtual Log * GetLogChannel ()
Static Public Member Functions
static llvm::StringRef GetFlavorString ()
static lldb::WatchpointEventType GetWatchpointEventTypeFromEvent (const lldb::EventSP &event_sp)
static lldb::WatchpointSP GetWatchpointFromEvent (const lldb::EventSP &event_sp)
static const WatchpointEventData * GetEventDataFromEvent (const Event *event_sp)
Private Member Functions
WatchpointEventData (const WatchpointEventData &)=delete
const WatchpointEventData & operator= (const WatchpointEventData &)=delete
Private Attributes
lldb::WatchpointEventType m_watchpoint_event
lldb::WatchpointSP m_new_watchpoint_sp
Detailed Description
Definition at line 27 of file Watchpoint.h.
Constructor & Destructor Documentation
WatchpointEventData() [1/2]
lldb_private::Watchpoint::WatchpointEventData::WatchpointEventData (lldb::WatchpointEventType sub_type, const lldb::WatchpointSP & new_watchpoint_sp)
Referenced by GetEventDataFromEvent(), GetWatchpointEventTypeFromEvent(), GetWatchpointFromEvent(), operator=(), WatchpointEventData(), and ~WatchpointEventData().
~WatchpointEventData()
Watchpoint::WatchpointEventData::~WatchpointEventData () override default
References lldb_private::EventData::Event, and WatchpointEventData().
WatchpointEventData() [2/2]
lldb_private::Watchpoint::WatchpointEventData::WatchpointEventData (const WatchpointEventData &) private delete
References WatchpointEventData().
Member Function Documentation
Dump()
void Watchpoint::WatchpointEventData::Dump (Stream * s) const override virtual
Reimplemented from lldb_private::EventData.
Definition at line 516 of file Watchpoint.cpp.
GetEventDataFromEvent()
const Watchpoint::WatchpointEventData * Watchpoint::WatchpointEventData::GetEventDataFromEvent (const Event * event_sp) static
Definition at line 519 of file Watchpoint.cpp.
References lldb_private::EventData::Event, lldb_private::EventData::EventData(), lldb_private::EventData::GetFlavor(), GetFlavorString(), and WatchpointEventData().
Referenced by lldb::SBWatchpoint::EventIsWatchpointEvent(), GetWatchpointEventTypeFromEvent(), and GetWatchpointFromEvent().
GetFlavor()
llvm::StringRef Watchpoint::WatchpointEventData::GetFlavor () const override virtual
Implements lldb_private::EventData.
Definition at line 503 of file Watchpoint.cpp.
References GetFlavorString().
GetFlavorString()
llvm::StringRef Watchpoint::WatchpointEventData::GetFlavorString () static
Definition at line 499 of file Watchpoint.cpp.
Referenced by GetEventDataFromEvent(), and GetFlavor().
GetWatchpoint()
WatchpointSP & Watchpoint::WatchpointEventData::GetWatchpoint ()
Definition at line 507 of file Watchpoint.cpp.
References m_new_watchpoint_sp.
GetWatchpointEventType()
WatchpointEventType Watchpoint::WatchpointEventData::GetWatchpointEventType () const
Definition at line 512 of file Watchpoint.cpp.
References m_watchpoint_event.
Referenced by GetWatchpointEventTypeFromEvent().
GetWatchpointEventTypeFromEvent()
WatchpointEventType Watchpoint::WatchpointEventData::GetWatchpointEventTypeFromEvent (const lldb::EventSP & event_sp) static
Definition at line 530 of file Watchpoint.cpp.
References GetEventDataFromEvent(), GetWatchpointEventType(), and WatchpointEventData().
Referenced by lldb::SBWatchpoint::GetWatchpointEventTypeFromEvent().
GetWatchpointFromEvent()
WatchpointSP Watchpoint::WatchpointEventData::GetWatchpointFromEvent (const lldb::EventSP & event_sp) static
Definition at line 539 of file Watchpoint.cpp.
References GetEventDataFromEvent(), m_new_watchpoint_sp, and WatchpointEventData().
Referenced by lldb::SBWatchpoint::GetWatchpointFromEvent().
operator=()
const WatchpointEventData & lldb_private::Watchpoint::WatchpointEventData::operator= (const WatchpointEventData &) private delete
References WatchpointEventData().
Member Data Documentation
m_new_watchpoint_sp
lldb::WatchpointSP lldb_private::Watchpoint::WatchpointEventData::m_new_watchpoint_sp private
Definition at line 55 of file Watchpoint.h.
Referenced by GetWatchpoint(), and GetWatchpointFromEvent().
m_watchpoint_event
lldb::WatchpointEventType lldb_private::Watchpoint::WatchpointEventData::m_watchpoint_event private
Definition at line 54 of file Watchpoint.h.
Referenced by GetWatchpointEventType().
The documentation for this class was generated from the following files:
Watchpoint.h
Watchpoint.cpp