LLDB: lldb::SBWatchpointOptions Class Reference
lldb::SBWatchpointOptions Class Reference
#include <SBWatchpointOptions.h>
Public Member Functions
SBWatchpointOptions ()
SBWatchpointOptions (const lldb::SBWatchpointOptions &rhs)
~SBWatchpointOptions ()
const SBWatchpointOptions & operator= (const lldb::SBWatchpointOptions &rhs)
void SetWatchpointTypeRead (bool read)
Stop when the watched memory region is read.
bool GetWatchpointTypeRead () const
void SetWatchpointTypeWrite (lldb::WatchpointWriteType write_type)
Stop when the watched memory region is written to/modified.
lldb::WatchpointWriteType GetWatchpointTypeWrite () const
Private Attributes
std::unique_ptr< WatchpointOptionsImpl > m_opaque_up
Detailed Description
Definition at line 18 of file SBWatchpointOptions.h.
Constructor & Destructor Documentation
SBWatchpointOptions() [1/2]
SBWatchpointOptions::SBWatchpointOptions ()
Definition at line 26 of file SBWatchpointOptions.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by operator=(), SBWatchpointOptions(), and ~SBWatchpointOptions().
SBWatchpointOptions() [2/2]
SBWatchpointOptions::SBWatchpointOptions (const lldb::SBWatchpointOptions & rhs)
Definition at line 31 of file SBWatchpointOptions.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBWatchpointOptions().
~SBWatchpointOptions()
SBWatchpointOptions::~SBWatchpointOptions () default
References GetWatchpointTypeRead(), GetWatchpointTypeWrite(), operator=(), SBWatchpointOptions(), SetWatchpointTypeRead(), and SetWatchpointTypeWrite().
Member Function Documentation
GetWatchpointTypeRead()
bool SBWatchpointOptions::GetWatchpointTypeRead () const
Definition at line 51 of file SBWatchpointOptions.cpp.
References m_opaque_up.
Referenced by lldb::SBTarget::WatchpointCreateByAddress(), and ~SBWatchpointOptions().
GetWatchpointTypeWrite()
WatchpointWriteType SBWatchpointOptions::GetWatchpointTypeWrite () const
Definition at line 67 of file SBWatchpointOptions.cpp.
References lldb::eWatchpointWriteTypeAlways, lldb::eWatchpointWriteTypeDisabled, lldb::eWatchpointWriteTypeOnModify, and m_opaque_up.
Referenced by lldb::SBTarget::WatchpointCreateByAddress(), and ~SBWatchpointOptions().
operator=()
const SBWatchpointOptions & SBWatchpointOptions::operator= (const lldb::SBWatchpointOptions & rhs)
Definition at line 38 of file SBWatchpointOptions.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBWatchpointOptions().
Referenced by ~SBWatchpointOptions().
SetWatchpointTypeRead()
void SBWatchpointOptions::SetWatchpointTypeRead (bool read)
Stop when the watched memory region is read.
Definition at line 48 of file SBWatchpointOptions.cpp.
References m_opaque_up.
Referenced by lldb::SBTarget::WatchAddress(), and ~SBWatchpointOptions().
SetWatchpointTypeWrite()
void SBWatchpointOptions::SetWatchpointTypeWrite (lldb::WatchpointWriteType write_type)
Stop when the watched memory region is written to/modified.
Definition at line 55 of file SBWatchpointOptions.cpp.
References lldb::eWatchpointWriteTypeAlways, lldb::eWatchpointWriteTypeOnModify, and m_opaque_up.
Referenced by lldb::SBTarget::WatchAddress(), and ~SBWatchpointOptions().
Member Data Documentation
m_opaque_up
std::unique_ptr<WatchpointOptionsImpl> lldb::SBWatchpointOptions::m_opaque_up mutable private
Definition at line 38 of file SBWatchpointOptions.h.
Referenced by GetWatchpointTypeRead(), GetWatchpointTypeWrite(), operator=(), SBWatchpointOptions(), SBWatchpointOptions(), SetWatchpointTypeRead(), and SetWatchpointTypeWrite().
The documentation for this class was generated from the following files:
SBWatchpointOptions.h
SBWatchpointOptions.cpp