LLDB: CommunicationKDP Class Reference
CommunicationKDP Class Reference
#include <CommunicationKDP.h>
Public Types
enum CommandType {
KDP_CONNECT = 0u , KDP_DISCONNECT , KDP_HOSTINFO , KDP_VERSION ,
KDP_MAXBYTES , KDP_READMEM , KDP_WRITEMEM , KDP_READREGS ,
KDP_WRITEREGS , KDP_LOAD , KDP_IMAGEPATH , KDP_SUSPEND ,
KDP_RESUMECPUS , KDP_EXCEPTION , KDP_TERMINATION , KDP_BREAKPOINT_SET ,
KDP_BREAKPOINT_REMOVE , KDP_REGIONS , KDP_REATTACH , KDP_HOSTREBOOT ,
KDP_READMEM64 , KDP_WRITEMEM64 , KDP_BREAKPOINT_SET64 , KDP_BREAKPOINT_REMOVE64 ,
KDP_KERNELVERSION , KDP_READPHYSMEM64 , KDP_WRITEPHYSMEM64 , KDP_READIOPORT ,
KDP_WRITEIOPORT , KDP_READMSR64 , KDP_WRITEMSR64 , KDP_DUMPINFO
}
enum { KDP_FEATURE_BP = (1u << 0) }
enum KDPError { KDP_PROTERR_SUCCESS = 0 , KDP_PROTERR_ALREADY_CONNECTED , KDP_PROTERR_BAD_NBYTES , KDP_PROTERR_BADFLAVOR }
enum PacketType { ePacketTypeRequest = 0x00u , ePacketTypeReply = 0x80u , ePacketTypeMask = 0x80u , eCommandTypeMask = 0x7fu }
typedef lldb_private::StreamBuffer< 4096 > PacketStreamType
Public Member Functions
CommunicationKDP (const char *comm_name)
~CommunicationKDP () override
bool SendRequestPacket (const PacketStreamType &request_packet)
size_t WaitForPacketWithTimeoutMicroSeconds (lldb_private::DataExtractor &response, uint32_t usec)
bool GetSequenceMutex (std::unique_lock< std::recursive_mutex > &lock)
bool CheckForPacket (const uint8_t *src, size_t src_len, lldb_private::DataExtractor &packet)
bool IsRunning () const
std::chrono::seconds SetPacketTimeout (std::chrono::seconds packet_timeout)
std::chrono::seconds GetPacketTimeout () const
bool SendRequestConnect (uint16_t reply_port, uint16_t exc_port, const char *greeting)
bool SendRequestReattach (uint16_t reply_port)
bool SendRequestDisconnect ()
uint32_t SendRequestReadMemory (lldb::addr_t addr, void *dst, uint32_t dst_size, lldb_private::Status &error)
uint32_t SendRequestWriteMemory (lldb::addr_t addr, const void *src, uint32_t src_len, lldb_private::Status &error)
bool SendRawRequest (uint8_t command_byte, const void *src, uint32_t src_len, lldb_private::DataExtractor &reply, lldb_private::Status &error)
uint32_t SendRequestReadRegisters (uint32_t cpu, uint32_t flavor, void *dst, uint32_t dst_size, lldb_private::Status &error)
uint32_t SendRequestWriteRegisters (uint32_t cpu, uint32_t flavor, const void *src, uint32_t src_size, lldb_private::Status &error)
const char * GetKernelVersion ()
uint32_t GetVersion ()
uint32_t GetFeatureFlags ()
bool LocalBreakpointsAreSupported ()
uint32_t GetCPUMask ()
uint32_t GetCPUType ()
uint32_t GetCPUSubtype ()
lldb_private::UUID GetUUID ()
bool RemoteIsEFI ()
bool RemoteIsDarwinKernel ()
lldb::addr_t GetLoadAddress ()
bool SendRequestResume ()
bool SendRequestSuspend ()
bool SendRequestBreakpoint (bool set, lldb::addr_t addr)
Public Member Functions inherited from lldb_private::Communication
Communication ()
Construct the Communication object.
virtual ~Communication ()
Destructor.
virtual void Clear ()
lldb::ConnectionStatus Connect (const char *url, Status *error_ptr)
Connect using the current connection by passing url to its connect function.
virtual lldb::ConnectionStatus Disconnect (Status *error_ptr=nullptr)
Disconnect the communications connection if one is currently connected.
bool IsConnected () const
Check if the connection is valid.
bool HasConnection () const
lldb_private::Connection * GetConnection ()
virtual size_t Read (void *dst, size_t dst_len, const Timeout< std::micro > &timeout, lldb::ConnectionStatus &status, Status *error_ptr)
Read bytes from the current connection.
size_t Write (const void *src, size_t src_len, lldb::ConnectionStatus &status, Status *error_ptr)
The actual write function that attempts to write to the communications protocol.
size_t WriteAll (const void *src, size_t src_len, lldb::ConnectionStatus &status, Status *error_ptr)
Repeatedly attempt writing until either src_len bytes are written or a permanent failure occurs.
virtual void SetConnection (std::unique_ptr< Connection > connection)
Sets the connection that it to be used by this class.
bool GetCloseOnEOF () const
void SetCloseOnEOF (bool b)
Static Public Attributes
static const uint32_t kMaxPacketSize = 1200
static const uint32_t kMaxDataSize = 1024
Protected Member Functions
bool SendRequestPacketNoLock (const PacketStreamType &request_packet)
size_t WaitForPacketWithTimeoutMicroSecondsNoLock (lldb_private::DataExtractor &response, uint32_t timeout_usec)
bool WaitForNotRunningPrivate (const std::chrono::microseconds &timeout)
void MakeRequestPacketHeader (CommandType request_type, PacketStreamType &request_packet, uint16_t request_length)
bool SendRequestVersion ()
bool SendRequestHostInfo ()
bool SendRequestKernelVersion ()
void DumpPacket (lldb_private::Stream &s, const void *data, uint32_t data_len)
void DumpPacket (lldb_private::Stream &s, const lldb_private::DataExtractor &extractor)
bool VersionIsValid () const
bool HostInfoIsValid () const
bool ExtractIsReply (uint8_t first_packet_byte) const
CommandType ExtractCommand (uint8_t first_packet_byte) const
void ClearKDPSettings ()
bool SendRequestAndGetReply (const CommandType command, const PacketStreamType &request_packet, lldb_private::DataExtractor &reply_packet)
Protected Member Functions inherited from lldb_private::Communication
size_t ReadFromConnection (void *dst, size_t dst_len, const Timeout< std::micro > &timeout, lldb::ConnectionStatus &status, Status *error_ptr)
Static Protected Member Functions
static const char * GetCommandAsCString (uint8_t command)
Protected Attributes
uint32_t m_addr_byte_size
lldb::ByteOrder m_byte_order
std::string m_bytes
std::recursive_mutex m_bytes_mutex
std::chrono::seconds m_packet_timeout
std::recursive_mutex m_sequence_mutex
lldb_private::Predicate< bool > m_is_running
uint32_t m_session_key
uint8_t m_request_sequence_id
uint8_t m_exception_sequence_id
uint32_t m_kdp_version_version
uint32_t m_kdp_version_feature
uint32_t m_kdp_hostinfo_cpu_mask
uint32_t m_kdp_hostinfo_cpu_type
uint32_t m_kdp_hostinfo_cpu_subtype
std::string m_kernel_version
lldb::addr_t m_last_read_memory_addr
Protected Attributes inherited from lldb_private::Communication
lldb::ConnectionSP m_connection_sp
The connection that is current in use by this communications class.
std::mutex m_write_mutex
Don't let multiple threads write at the same time...
bool m_close_on_eof
Private Member Functions
CommunicationKDP (const CommunicationKDP &)=delete
const CommunicationKDP & operator= (const CommunicationKDP &)=delete
Additional Inherited Members
Static Public Member Functions inherited from lldb_private::Communication
static std::string ConnectionStatusAsString (lldb::ConnectionStatus status)
Detailed Description
Definition at line 22 of file CommunicationKDP.h.
Member Typedef Documentation
PacketStreamType
typedef lldb_private::StreamBuffer<4096> CommunicationKDP::PacketStreamType
Definition at line 26 of file CommunicationKDP.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
KDP_FEATURE_BP
Definition at line 62 of file CommunicationKDP.h.
CommandType
enum CommunicationKDP::CommandType
Enumerator
KDP_CONNECT
KDP_DISCONNECT
KDP_HOSTINFO
KDP_VERSION
KDP_MAXBYTES
KDP_READMEM
KDP_WRITEMEM
KDP_READREGS
KDP_WRITEREGS
KDP_LOAD
KDP_IMAGEPATH
KDP_SUSPEND
KDP_RESUMECPUS
KDP_EXCEPTION
KDP_TERMINATION
KDP_BREAKPOINT_SET
KDP_BREAKPOINT_REMOVE
KDP_REGIONS
KDP_REATTACH
KDP_HOSTREBOOT
KDP_READMEM64
KDP_WRITEMEM64
KDP_BREAKPOINT_SET64
KDP_BREAKPOINT_REMOVE64
KDP_KERNELVERSION
KDP_READPHYSMEM64
KDP_WRITEPHYSMEM64
KDP_READIOPORT
KDP_WRITEIOPORT
KDP_READMSR64
KDP_WRITEMSR64
KDP_DUMPINFO
Definition at line 27 of file CommunicationKDP.h.
KDPError
enum CommunicationKDP::KDPError
Enumerator
KDP_PROTERR_SUCCESS
KDP_PROTERR_ALREADY_CONNECTED
KDP_PROTERR_BAD_NBYTES
KDP_PROTERR_BADFLAVOR
Definition at line 64 of file CommunicationKDP.h.
PacketType
enum CommunicationKDP::PacketType
Enumerator
ePacketTypeRequest
ePacketTypeReply
ePacketTypeMask
eCommandTypeMask
Definition at line 71 of file CommunicationKDP.h.
Constructor & Destructor Documentation
CommunicationKDP() [1/2]
CommunicationKDP::CommunicationKDP (const char * comm_name)
Definition at line 31 of file CommunicationKDP.cpp.
References lldb_private::Communication::Communication(), lldb::eByteOrderLittle, m_addr_byte_size, m_byte_order, m_exception_sequence_id, m_is_running, m_kdp_hostinfo_cpu_mask, m_kdp_hostinfo_cpu_subtype, m_kdp_hostinfo_cpu_type, m_kdp_version_feature, m_kdp_version_version, m_packet_timeout, m_request_sequence_id, m_sequence_mutex, and m_session_key.
Referenced by CommunicationKDP(), and operator=().
~CommunicationKDP()
CommunicationKDP::~CommunicationKDP () override
Definition at line 40 of file CommunicationKDP.cpp.
References lldb_private::Communication::Disconnect(), and lldb_private::Communication::IsConnected().
CommunicationKDP() [2/2]
CommunicationKDP::CommunicationKDP (const CommunicationKDP &) private delete
References CommunicationKDP().
Member Function Documentation
CheckForPacket()
bool CommunicationKDP::CheckForPacket (const uint8_t * src, size_t src_len, lldb_private::DataExtractor & packet)
Definition at line 229 of file CommunicationKDP.cpp.
References lldb_private::DataExtractor::Clear(), lldb_private::DumpHexBytes(), DumpPacket(), lldb_private::Stream::eBinary, lldb_private::eBroadcastAlways, ePacketTypeReply, ePacketTypeRequest, lldb_private::StreamBuffer< N >::GetData(), lldb_private::GetLog(), lldb_private::StreamBuffer< N >::GetSize(), lldb_private::DataExtractor::GetU16(), lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU8(), lldb_private::Log::GetVerbose(), KDP_BREAKPOINT_REMOVE, KDP_BREAKPOINT_REMOVE64, KDP_BREAKPOINT_SET, KDP_BREAKPOINT_SET64, KDP_CONNECT, KDP_DISCONNECT, KDP_DUMPINFO, KDP_EXCEPTION, KDP_HOSTINFO, KDP_HOSTREBOOT, KDP_IMAGEPATH, KDP_KERNELVERSION, KDP_LOAD, KDP_MAXBYTES, KDP_READIOPORT, KDP_READMEM, KDP_READMEM64, KDP_READMSR64, KDP_READPHYSMEM64, KDP_READREGS, KDP_REATTACH, KDP_REGIONS, KDP_RESUMECPUS, KDP_SUSPEND, KDP_TERMINATION, KDP_VERSION, KDP_WRITEIOPORT, KDP_WRITEMEM, KDP_WRITEMEM64, KDP_WRITEMSR64, KDP_WRITEPHYSMEM64, KDP_WRITEREGS, LLDB_INVALID_ADDRESS, LLDB_LOGF, m_addr_byte_size, m_byte_order, m_bytes, m_bytes_mutex, m_is_running, lldb_private::Packets, lldb_private::Stream::PutChar(), lldb_private::Stream::PutHex16(), lldb_private::Stream::PutHex32(), lldb_private::Stream::PutHex8(), SendRequestPacketNoLock(), lldb_private::DataExtractor::SetData(), and UINT32_MAX.
Referenced by WaitForPacketWithTimeoutMicroSecondsNoLock().
ClearKDPSettings()
void CommunicationKDP::ClearKDPSettings () protected
Definition at line 357 of file CommunicationKDP.cpp.
References m_kdp_hostinfo_cpu_mask, m_kdp_hostinfo_cpu_subtype, m_kdp_hostinfo_cpu_type, m_kdp_version_feature, m_kdp_version_version, and m_request_sequence_id.
Referenced by SendRequestDisconnect(), and SendRequestReattach().
DumpPacket() [1/2]
void CommunicationKDP::DumpPacket (lldb_private::Stream & s, const lldb_private::DataExtractor & extractor) protected
Definition at line 722 of file CommunicationKDP.cpp.
References lldb_private::DumpDataExtractor(), lldb_private::DumpHexBytes(), lldb::eFormatBytes, lldb::eFormatBytesWithASCII, lldb::eFormatHex, error(), ExtractCommand(), ExtractIsReply(), lldb_private::DataExtractor::GetAddress(), lldb_private::DataExtractor::GetByteSize(), GetCommandAsCString(), lldb_private::DataExtractor::GetCStr(), lldb_private::DataExtractor::GetData(), lldb_private::GetPermissionsAsCString(), lldb_private::DataExtractor::GetU16(), lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU64(), lldb_private::DataExtractor::GetU8(), IsRunning(), KDP_BREAKPOINT_REMOVE, KDP_BREAKPOINT_REMOVE64, KDP_BREAKPOINT_SET, KDP_BREAKPOINT_SET64, KDP_CONNECT, KDP_DISCONNECT, KDP_DUMPINFO, KDP_EXCEPTION, KDP_HOSTINFO, KDP_HOSTREBOOT, KDP_IMAGEPATH, KDP_KERNELVERSION, KDP_LOAD, KDP_MAXBYTES, KDP_READIOPORT, KDP_READMEM, KDP_READMEM64, KDP_READMSR64, KDP_READPHYSMEM64, KDP_READREGS, KDP_REATTACH, KDP_REGIONS, KDP_RESUMECPUS, KDP_SUSPEND, KDP_TERMINATION, KDP_VERSION, KDP_WRITEIOPORT, KDP_WRITEMEM, KDP_WRITEMEM64, KDP_WRITEMSR64, KDP_WRITEPHYSMEM64, KDP_WRITEREGS, LLDB_INVALID_ADDRESS, m_addr_byte_size, m_last_read_memory_addr, lldb_private::DataExtractor::PeekCStr(), lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and UINT32_MAX.
DumpPacket() [2/2]
void CommunicationKDP::DumpPacket (lldb_private::Stream & s, const void * data, uint32_t data_len) protected
Definition at line 716 of file CommunicationKDP.cpp.
References DumpPacket(), m_addr_byte_size, and m_byte_order.
Referenced by CheckForPacket(), DumpPacket(), SendRequestAndGetReply(), and SendRequestPacketNoLock().
ExtractCommand()
CommandType CommunicationKDP::ExtractCommand (uint8_t first_packet_byte) const inline protected
Definition at line 209 of file CommunicationKDP.h.
References eCommandTypeMask.
Referenced by DumpPacket().
ExtractIsReply()
bool CommunicationKDP::ExtractIsReply (uint8_t first_packet_byte) const inline protected
Definition at line 204 of file CommunicationKDP.h.
References ePacketTypeMask.
Referenced by DumpPacket().
GetCommandAsCString()
const char * CommunicationKDP::GetCommandAsCString (uint8_t command) static protected
Definition at line 646 of file CommunicationKDP.cpp.
References KDP_BREAKPOINT_REMOVE, KDP_BREAKPOINT_REMOVE64, KDP_BREAKPOINT_SET, KDP_BREAKPOINT_SET64, KDP_CONNECT, KDP_DISCONNECT, KDP_DUMPINFO, KDP_EXCEPTION, KDP_HOSTINFO, KDP_HOSTREBOOT, KDP_IMAGEPATH, KDP_KERNELVERSION, KDP_LOAD, KDP_MAXBYTES, KDP_READIOPORT, KDP_READMEM, KDP_READMEM64, KDP_READMSR64, KDP_READPHYSMEM64, KDP_READREGS, KDP_REATTACH, KDP_REGIONS, KDP_RESUMECPUS, KDP_SUSPEND, KDP_TERMINATION, KDP_VERSION, KDP_WRITEIOPORT, KDP_WRITEMEM, KDP_WRITEMEM64, KDP_WRITEMSR64, KDP_WRITEPHYSMEM64, and KDP_WRITEREGS.
Referenced by DumpPacket().
GetCPUMask()
uint32_t CommunicationKDP::GetCPUMask ()
Definition at line 416 of file CommunicationKDP.cpp.
References HostInfoIsValid(), m_kdp_hostinfo_cpu_mask, and SendRequestHostInfo().
Referenced by SendRequestResume().
GetCPUSubtype()
uint32_t CommunicationKDP::GetCPUSubtype ()
Definition at line 428 of file CommunicationKDP.cpp.
References HostInfoIsValid(), m_kdp_hostinfo_cpu_subtype, and SendRequestHostInfo().
GetCPUType()
uint32_t CommunicationKDP::GetCPUType ()
Definition at line 422 of file CommunicationKDP.cpp.
References HostInfoIsValid(), m_kdp_hostinfo_cpu_type, and SendRequestHostInfo().
GetFeatureFlags()
uint32_t CommunicationKDP::GetFeatureFlags ()
Definition at line 394 of file CommunicationKDP.cpp.
References m_kdp_version_feature, SendRequestVersion(), and VersionIsValid().
Referenced by LocalBreakpointsAreSupported().
GetKernelVersion()
const char * CommunicationKDP::GetKernelVersion ()
Definition at line 510 of file CommunicationKDP.cpp.
References m_kernel_version, and SendRequestKernelVersion().
Referenced by GetLoadAddress(), GetUUID(), RemoteIsDarwinKernel(), and RemoteIsEFI().
GetLoadAddress()
lldb::addr_t CommunicationKDP::GetLoadAddress ()
Definition at line 467 of file CommunicationKDP.cpp.
References GetKernelVersion(), LLDB_INVALID_ADDRESS, and m_kernel_version.
GetPacketTimeout()
std::chrono::seconds CommunicationKDP::GetPacketTimeout () const inline
Definition at line 107 of file CommunicationKDP.h.
References m_packet_timeout.
Referenced by SendRequestAndGetReply().
GetSequenceMutex()
bool CommunicationKDP::GetSequenceMutex (std::unique_lock< std::recursive_mutex > & lock)
Definition at line 157 of file CommunicationKDP.cpp.
References m_sequence_mutex.
GetUUID()
lldb_private::UUID CommunicationKDP::GetUUID ()
Definition at line 434 of file CommunicationKDP.cpp.
References GetKernelVersion(), m_kernel_version, and lldb_private::UUID::SetFromStringRef().
GetVersion()
uint32_t CommunicationKDP::GetVersion ()
Definition at line 388 of file CommunicationKDP.cpp.
References m_kdp_version_version, SendRequestVersion(), and VersionIsValid().
Referenced by SendRequestBreakpoint(), SendRequestReadMemory(), and SendRequestWriteMemory().
HostInfoIsValid()
bool CommunicationKDP::HostInfoIsValid () const inline protected
Definition at line 202 of file CommunicationKDP.h.
References m_kdp_hostinfo_cpu_type.
Referenced by GetCPUMask(), GetCPUSubtype(), and GetCPUType().
IsRunning()
bool CommunicationKDP::IsRunning () const inline
Definition at line 93 of file CommunicationKDP.h.
References m_is_running.
Referenced by DumpPacket(), and SendRequestAndGetReply().
LocalBreakpointsAreSupported()
bool CommunicationKDP::LocalBreakpointsAreSupported () inline
Definition at line 147 of file CommunicationKDP.h.
References GetFeatureFlags(), and KDP_FEATURE_BP.
MakeRequestPacketHeader()
void CommunicationKDP::MakeRequestPacketHeader (CommandType request_type, PacketStreamType & request_packet, uint16_t request_length) protected
Definition at line 52 of file CommunicationKDP.cpp.
References lldb_private::StreamBuffer< N >::Clear(), ePacketTypeRequest, m_request_sequence_id, m_session_key, lldb_private::Stream::PutHex16(), lldb_private::Stream::PutHex32(), and lldb_private::Stream::PutHex8().
Referenced by SendRawRequest(), SendRequestBreakpoint(), SendRequestConnect(), SendRequestDisconnect(), SendRequestHostInfo(), SendRequestKernelVersion(), SendRequestReadMemory(), SendRequestReadRegisters(), SendRequestReattach(), SendRequestResume(), SendRequestSuspend(), SendRequestVersion(), SendRequestWriteMemory(), and SendRequestWriteRegisters().
operator=()
const CommunicationKDP & CommunicationKDP::operator= (const CommunicationKDP &) private delete
References CommunicationKDP().
RemoteIsDarwinKernel()
bool CommunicationKDP::RemoteIsDarwinKernel ()
Definition at line 461 of file CommunicationKDP.cpp.
References GetKernelVersion(), and m_kernel_version.
RemoteIsEFI()
bool CommunicationKDP::RemoteIsEFI ()
Definition at line 455 of file CommunicationKDP.cpp.
References GetKernelVersion(), and m_kernel_version.
SendRawRequest()
bool CommunicationKDP::SendRawRequest (uint8_t command_byte, const void * src, uint32_t src_len, lldb_private::DataExtractor & reply, lldb_private::Status & error)
Definition at line 617 of file CommunicationKDP.cpp.
References lldb_private::Stream::eBinary, error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataExtractor::GetU32(), KDP_DUMPINFO, m_addr_byte_size, m_byte_order, MakeRequestPacketHeader(), lldb_private::Stream::PutRawBytes(), and SendRequestAndGetReply().
Referenced by CommandObjectProcessKDPPacketSend::DoExecute().
SendRequestAndGetReply()
bool CommunicationKDP::SendRequestAndGetReply (const CommandType command, const PacketStreamType & request_packet, lldb_private::DataExtractor & reply_packet) protected
Definition at line 64 of file CommunicationKDP.cpp.
References lldb_private::DataExtractor::Clear(), DumpPacket(), lldb_private::eBroadcastAlways, eCommandTypeMask, lldb_private::StreamBuffer< N >::GetData(), lldb_private::GetLog(), GetPacketTimeout(), lldb_private::StreamBuffer< N >::GetSize(), lldb_private::DataExtractor::GetU8(), IsRunning(), KDP_RESUMECPUS, LLDB_LOGF, m_is_running, m_sequence_mutex, lldb_private::Packets, SendRequestPacketNoLock(), and WaitForPacketWithTimeoutMicroSecondsNoLock().
Referenced by SendRawRequest(), SendRequestBreakpoint(), SendRequestConnect(), SendRequestDisconnect(), SendRequestHostInfo(), SendRequestKernelVersion(), SendRequestReadMemory(), SendRequestReadRegisters(), SendRequestReattach(), SendRequestResume(), SendRequestSuspend(), SendRequestVersion(), SendRequestWriteMemory(), and SendRequestWriteRegisters().
SendRequestBreakpoint()
bool CommunicationKDP::SendRequestBreakpoint (bool set, lldb::addr_t addr)
Definition at line 1250 of file CommunicationKDP.cpp.
References lldb_private::Stream::eBinary, lldb_private::DataExtractor::GetU32(), GetVersion(), KDP_BREAKPOINT_REMOVE, KDP_BREAKPOINT_REMOVE64, KDP_BREAKPOINT_SET, KDP_BREAKPOINT_SET64, m_addr_byte_size, m_byte_order, MakeRequestPacketHeader(), lldb_private::Stream::PutMaxHex64(), and SendRequestAndGetReply().
SendRequestConnect()
bool CommunicationKDP::SendRequestConnect (uint16_t reply_port, uint16_t exc_port, const char * greeting)
Definition at line 334 of file CommunicationKDP.cpp.
References lldb_private::Stream::eBinary, lldb::eByteOrderLittle, KDP_CONNECT, m_addr_byte_size, m_byte_order, MakeRequestPacketHeader(), lldb_private::Stream::PutCString(), lldb_private::Stream::PutHex16(), SendRequestAndGetReply(), and lldb_private::Stream::SetByteOrder().
SendRequestDisconnect()
bool CommunicationKDP::SendRequestDisconnect ()
Definition at line 532 of file CommunicationKDP.cpp.
References ClearKDPSettings(), lldb_private::Stream::eBinary, KDP_DISCONNECT, m_addr_byte_size, m_byte_order, MakeRequestPacketHeader(), and SendRequestAndGetReply().
SendRequestHostInfo()
bool CommunicationKDP::SendRequestHostInfo () protected
Definition at line 486 of file CommunicationKDP.cpp.
References lldb_private::eArchTypeMachO, lldb_private::Stream::eBinary, lldb_private::ArchSpec::GetAddressByteSize(), lldb_private::ArchSpec::GetByteOrder(), lldb_private::DataExtractor::GetU32(), KDP_HOSTINFO, m_addr_byte_size, m_byte_order, m_kdp_hostinfo_cpu_mask, m_kdp_hostinfo_cpu_subtype, m_kdp_hostinfo_cpu_type, MakeRequestPacketHeader(), SendRequestAndGetReply(), and lldb_private::ArchSpec::SetArchitecture().
Referenced by GetCPUMask(), GetCPUSubtype(), and GetCPUType().
SendRequestKernelVersion()
bool CommunicationKDP::SendRequestKernelVersion () protected
Definition at line 516 of file CommunicationKDP.cpp.
References lldb_private::Stream::eBinary, KDP_KERNELVERSION, m_addr_byte_size, m_byte_order, m_kernel_version, MakeRequestPacketHeader(), lldb_private::DataExtractor::PeekCStr(), and SendRequestAndGetReply().
Referenced by GetKernelVersion().
SendRequestPacket()
bool CommunicationKDP::SendRequestPacket (const PacketStreamType & request_packet)
Definition at line 46 of file CommunicationKDP.cpp.
References m_sequence_mutex, and SendRequestPacketNoLock().
SendRequestPacketNoLock()
bool CommunicationKDP::SendRequestPacketNoLock (const PacketStreamType & request_packet) protected
Definition at line 130 of file CommunicationKDP.cpp.
References DumpPacket(), lldb::eConnectionStatusSuccess, lldb_private::StreamBuffer< N >::GetData(), lldb_private::GetLog(), lldb_private::StreamBuffer< N >::GetSize(), lldb_private::Communication::IsConnected(), LLDB_LOGF, lldb_private::Packets, and lldb_private::Communication::Write().
Referenced by CheckForPacket(), SendRequestAndGetReply(), and SendRequestPacket().
SendRequestReadMemory()
uint32_t CommunicationKDP::SendRequestReadMemory (lldb::addr_t addr, void * dst, uint32_t dst_size, lldb_private::Status & error)
Definition at line 546 of file CommunicationKDP.cpp.
References lldb_private::Stream::eBinary, error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataExtractor::GetByteSize(), lldb_private::DataExtractor::GetData(), lldb_private::DataExtractor::GetU32(), GetVersion(), KDP_READMEM, KDP_READMEM64, m_addr_byte_size, m_byte_order, MakeRequestPacketHeader(), lldb_private::Stream::PutHex32(), lldb_private::Stream::PutMaxHex64(), and SendRequestAndGetReply().
SendRequestReadRegisters()
uint32_t CommunicationKDP::SendRequestReadRegisters (uint32_t cpu, uint32_t flavor, void * dst, uint32_t dst_size, lldb_private::Status & error)
Definition at line 1167 of file CommunicationKDP.cpp.
References lldb_private::Stream::eBinary, error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataExtractor::GetByteSize(), lldb_private::DataExtractor::GetData(), lldb_private::DataExtractor::GetU32(), KDP_READREGS, m_addr_byte_size, m_byte_order, MakeRequestPacketHeader(), lldb_private::Stream::PutHex32(), and SendRequestAndGetReply().
Referenced by RegisterContextKDP_arm64::DoReadDBG(), RegisterContextKDP_arm::DoReadDBG(), RegisterContextKDP_arm64::DoReadEXC(), RegisterContextKDP_arm::DoReadEXC(), RegisterContextKDP_x86_64::DoReadEXC(), RegisterContextKDP_arm64::DoReadFPU(), RegisterContextKDP_arm::DoReadFPU(), RegisterContextKDP_x86_64::DoReadFPU(), RegisterContextKDP_arm64::DoReadGPR(), RegisterContextKDP_arm::DoReadGPR(), and RegisterContextKDP_x86_64::DoReadGPR().
SendRequestReattach()
bool CommunicationKDP::SendRequestReattach (uint16_t reply_port)
Definition at line 366 of file CommunicationKDP.cpp.
References ClearKDPSettings(), lldb_private::Stream::eBinary, lldb::eByteOrderLittle, lldb_private::DataExtractor::GetU32(), KDP_REATTACH, m_addr_byte_size, m_byte_order, m_session_key, MakeRequestPacketHeader(), lldb_private::Stream::PutHex16(), SendRequestAndGetReply(), and lldb_private::Stream::SetByteOrder().
SendRequestResume()
bool CommunicationKDP::SendRequestResume ()
Definition at line 1238 of file CommunicationKDP.cpp.
References lldb_private::Stream::eBinary, GetCPUMask(), KDP_RESUMECPUS, m_addr_byte_size, m_byte_order, MakeRequestPacketHeader(), lldb_private::Stream::PutHex32(), and SendRequestAndGetReply().
SendRequestSuspend()
bool CommunicationKDP::SendRequestSuspend ()
Definition at line 1273 of file CommunicationKDP.cpp.
References lldb_private::Stream::eBinary, KDP_SUSPEND, m_addr_byte_size, m_byte_order, MakeRequestPacketHeader(), and SendRequestAndGetReply().
SendRequestVersion()
bool CommunicationKDP::SendRequestVersion () protected
Definition at line 400 of file CommunicationKDP.cpp.
References lldb_private::Stream::eBinary, lldb_private::DataExtractor::GetU32(), KDP_VERSION, m_addr_byte_size, m_byte_order, m_kdp_version_feature, m_kdp_version_version, MakeRequestPacketHeader(), and SendRequestAndGetReply().
Referenced by GetFeatureFlags(), and GetVersion().
SendRequestWriteMemory()
uint32_t CommunicationKDP::SendRequestWriteMemory (lldb::addr_t addr, const void * src, uint32_t src_len, lldb_private::Status & error)
Definition at line 584 of file CommunicationKDP.cpp.
References lldb_private::Stream::eBinary, error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataExtractor::GetU32(), GetVersion(), KDP_WRITEMEM, KDP_WRITEMEM64, m_addr_byte_size, m_byte_order, MakeRequestPacketHeader(), lldb_private::Stream::PutHex32(), lldb_private::Stream::PutMaxHex64(), lldb_private::Stream::PutRawBytes(), and SendRequestAndGetReply().
SendRequestWriteRegisters()
uint32_t CommunicationKDP::SendRequestWriteRegisters (uint32_t cpu, uint32_t flavor, const void * src, uint32_t src_size, lldb_private::Status & error)
Definition at line 1209 of file CommunicationKDP.cpp.
References lldb_private::Stream::eBinary, error(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataExtractor::GetU32(), KDP_WRITEREGS, m_addr_byte_size, m_byte_order, MakeRequestPacketHeader(), lldb_private::Stream::PutHex32(), SendRequestAndGetReply(), and lldb_private::Stream::Write().
Referenced by RegisterContextKDP_arm64::DoWriteDBG(), RegisterContextKDP_arm::DoWriteDBG(), RegisterContextKDP_arm64::DoWriteEXC(), RegisterContextKDP_arm::DoWriteEXC(), RegisterContextKDP_x86_64::DoWriteEXC(), RegisterContextKDP_arm64::DoWriteFPU(), RegisterContextKDP_arm::DoWriteFPU(), RegisterContextKDP_x86_64::DoWriteFPU(), RegisterContextKDP_arm64::DoWriteGPR(), RegisterContextKDP_arm::DoWriteGPR(), and RegisterContextKDP_x86_64::DoWriteGPR().
SetPacketTimeout()
std::chrono::seconds CommunicationKDP::SetPacketTimeout (std::chrono::seconds packet_timeout) inline
Definition at line 101 of file CommunicationKDP.h.
References m_packet_timeout.
VersionIsValid()
bool CommunicationKDP::VersionIsValid () const inline protected
Definition at line 200 of file CommunicationKDP.h.
References m_kdp_version_version.
Referenced by GetFeatureFlags(), and GetVersion().
WaitForNotRunningPrivate()
bool CommunicationKDP::WaitForNotRunningPrivate (const std::chrono::microseconds & timeout) protected
Definition at line 164 of file CommunicationKDP.cpp.
References m_is_running.
WaitForPacketWithTimeoutMicroSeconds()
size_t CommunicationKDP::WaitForPacketWithTimeoutMicroSeconds (lldb_private::DataExtractor & response, uint32_t usec)
Definition at line 170 of file CommunicationKDP.cpp.
References m_sequence_mutex, and WaitForPacketWithTimeoutMicroSecondsNoLock().
WaitForPacketWithTimeoutMicroSecondsNoLock()
size_t CommunicationKDP::WaitForPacketWithTimeoutMicroSecondsNoLock (lldb_private::DataExtractor & response, uint32_t timeout_usec) protected
Definition at line 176 of file CommunicationKDP.cpp.
References CheckForPacket(), lldb_private::DataExtractor::Clear(), lldb_private::Communication::ConnectionStatusAsString(), lldb_private::Communication::Disconnect(), lldb::eConnectionStatusEndOfFile, lldb::eConnectionStatusError, lldb::eConnectionStatusInterrupted, lldb::eConnectionStatusLostConnection, lldb::eConnectionStatusNoConnection, lldb::eConnectionStatusSuccess, lldb::eConnectionStatusTimedOut, error(), lldb_private::DataExtractor::GetByteSize(), lldb_private::GetLog(), lldb_private::Communication::IsConnected(), LLDB_LOGV, lldb_private::Packets, lldb_private::Communication::Read(), and UINT32_MAX.
Referenced by SendRequestAndGetReply(), and WaitForPacketWithTimeoutMicroSeconds().
Member Data Documentation
kMaxDataSize
const uint32_t CommunicationKDP::kMaxDataSize = 1024 static
Definition at line 25 of file CommunicationKDP.h.
kMaxPacketSize
const uint32_t CommunicationKDP::kMaxPacketSize = 1200 static
Definition at line 24 of file CommunicationKDP.h.
m_addr_byte_size
uint32_t CommunicationKDP::m_addr_byte_size protected
Definition at line 222 of file CommunicationKDP.h.
Referenced by CheckForPacket(), CommunicationKDP(), DumpPacket(), DumpPacket(), SendRawRequest(), SendRequestBreakpoint(), SendRequestConnect(), SendRequestDisconnect(), SendRequestHostInfo(), SendRequestKernelVersion(), SendRequestReadMemory(), SendRequestReadRegisters(), SendRequestReattach(), SendRequestResume(), SendRequestSuspend(), SendRequestVersion(), SendRequestWriteMemory(), and SendRequestWriteRegisters().
m_byte_order
lldb::ByteOrder CommunicationKDP::m_byte_order protected
Definition at line 223 of file CommunicationKDP.h.
Referenced by CheckForPacket(), CommunicationKDP(), DumpPacket(), SendRawRequest(), SendRequestBreakpoint(), SendRequestConnect(), SendRequestDisconnect(), SendRequestHostInfo(), SendRequestKernelVersion(), SendRequestReadMemory(), SendRequestReadRegisters(), SendRequestReattach(), SendRequestResume(), SendRequestSuspend(), SendRequestVersion(), SendRequestWriteMemory(), and SendRequestWriteRegisters().
m_bytes
std::string CommunicationKDP::m_bytes protected
Definition at line 224 of file CommunicationKDP.h.
Referenced by CheckForPacket().
m_bytes_mutex
std::recursive_mutex CommunicationKDP::m_bytes_mutex protected
Definition at line 225 of file CommunicationKDP.h.
Referenced by CheckForPacket().
m_exception_sequence_id
uint8_t CommunicationKDP::m_exception_sequence_id protected
Definition at line 232 of file CommunicationKDP.h.
Referenced by CommunicationKDP().
m_is_running
lldb_private::Predicate<bool> CommunicationKDP::m_is_running protected
Definition at line 229 of file CommunicationKDP.h.
Referenced by CheckForPacket(), CommunicationKDP(), IsRunning(), SendRequestAndGetReply(), and WaitForNotRunningPrivate().
m_kdp_hostinfo_cpu_mask
uint32_t CommunicationKDP::m_kdp_hostinfo_cpu_mask protected
Definition at line 235 of file CommunicationKDP.h.
Referenced by ClearKDPSettings(), CommunicationKDP(), GetCPUMask(), and SendRequestHostInfo().
m_kdp_hostinfo_cpu_subtype
uint32_t CommunicationKDP::m_kdp_hostinfo_cpu_subtype protected
Definition at line 237 of file CommunicationKDP.h.
Referenced by ClearKDPSettings(), CommunicationKDP(), GetCPUSubtype(), and SendRequestHostInfo().
m_kdp_hostinfo_cpu_type
uint32_t CommunicationKDP::m_kdp_hostinfo_cpu_type protected
Definition at line 236 of file CommunicationKDP.h.
Referenced by ClearKDPSettings(), CommunicationKDP(), GetCPUType(), HostInfoIsValid(), and SendRequestHostInfo().
m_kdp_version_feature
uint32_t CommunicationKDP::m_kdp_version_feature protected
Definition at line 234 of file CommunicationKDP.h.
Referenced by ClearKDPSettings(), CommunicationKDP(), GetFeatureFlags(), and SendRequestVersion().
m_kdp_version_version
uint32_t CommunicationKDP::m_kdp_version_version protected
Definition at line 233 of file CommunicationKDP.h.
Referenced by ClearKDPSettings(), CommunicationKDP(), GetVersion(), SendRequestVersion(), and VersionIsValid().
m_kernel_version
std::string CommunicationKDP::m_kernel_version protected
Definition at line 238 of file CommunicationKDP.h.
Referenced by GetKernelVersion(), GetLoadAddress(), GetUUID(), RemoteIsDarwinKernel(), RemoteIsEFI(), and SendRequestKernelVersion().
m_last_read_memory_addr
lldb::addr_t CommunicationKDP::m_last_read_memory_addr protected
Definition at line 241 of file CommunicationKDP.h.
Referenced by DumpPacket().
m_packet_timeout
std::chrono::seconds CommunicationKDP::m_packet_timeout protected
Definition at line 226 of file CommunicationKDP.h.
Referenced by CommunicationKDP(), GetPacketTimeout(), and SetPacketTimeout().
m_request_sequence_id
uint8_t CommunicationKDP::m_request_sequence_id protected
Definition at line 231 of file CommunicationKDP.h.
Referenced by ClearKDPSettings(), CommunicationKDP(), and MakeRequestPacketHeader().
m_sequence_mutex
std::recursive_mutex CommunicationKDP::m_sequence_mutex protected
Definition at line 227 of file CommunicationKDP.h.
Referenced by CommunicationKDP(), GetSequenceMutex(), SendRequestAndGetReply(), SendRequestPacket(), and WaitForPacketWithTimeoutMicroSeconds().
m_session_key
uint32_t CommunicationKDP::m_session_key protected
Definition at line 230 of file CommunicationKDP.h.
Referenced by CommunicationKDP(), MakeRequestPacketHeader(), and SendRequestReattach().
The documentation for this class was generated from the following files:
CommunicationKDP.h
CommunicationKDP.cpp