LLDB: lldb_private::ProgressEventData Class Reference
lldb_private::ProgressEventData Class Reference
#include <DebuggerEvents.h>
Public Member Functions
ProgressEventData (uint64_t progress_id, std::string title, std::string details, uint64_t completed, uint64_t total, bool debugger_specific)
llvm::StringRef GetFlavor () const override
void Dump (Stream *s) const override
uint64_t GetID () const
bool IsFinite () const
uint64_t GetCompleted () const
uint64_t GetTotal () const
std::string GetMessage () const
const std::string & GetTitle () const
const std::string & GetDetails () const
bool IsDebuggerSpecific () const
Public Member Functions inherited from lldb_private::EventData
EventData ()
virtual ~EventData ()
virtual Log * GetLogChannel ()
Static Public Member Functions
static llvm::StringRef GetFlavorString ()
static const ProgressEventData * GetEventDataFromEvent (const Event *event_ptr)
static StructuredData::DictionarySP GetAsStructuredData (const Event *event_ptr)
Private Member Functions
ProgressEventData (const ProgressEventData &)=delete
const ProgressEventData & operator= (const ProgressEventData &)=delete
Private Attributes
std::string m_title
The title of this progress event.
std::string m_details
Details associated with this progress event update.
const uint64_t m_id
Unique ID used to associate progress events.
uint64_t m_completed
const uint64_t m_total
const bool m_debugger_specific
Detailed Description
Definition at line 22 of file DebuggerEvents.h.
Constructor & Destructor Documentation
ProgressEventData() [1/2]
lldb_private::ProgressEventData::ProgressEventData (uint64_t progress_id, std::string title, std::string details, uint64_t completed, uint64_t total, bool debugger_specific) inline
Definition at line 24 of file DebuggerEvents.h.
References m_completed, m_debugger_specific, m_details, m_id, m_title, and m_total.
Referenced by GetAsStructuredData(), operator=(), and ProgressEventData().
ProgressEventData() [2/2]
lldb_private::ProgressEventData::ProgressEventData (const ProgressEventData &) private delete
References ProgressEventData().
Member Function Documentation
Dump()
void ProgressEventData::Dump (Stream * s) const override virtual
Reimplemented from lldb_private::EventData.
Definition at line 35 of file DebuggerEvents.cpp.
References lldb_private::Progress::kNonDeterministicTotal, m_completed, m_details, m_id, m_title, m_total, lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
GetAsStructuredData()
StructuredData::DictionarySP ProgressEventData::GetAsStructuredData (const Event * event_ptr) static
Definition at line 55 of file DebuggerEvents.cpp.
References lldb_private::EventData::Event, GetCompleted(), GetDetails(), GetEventDataFromEvent(), GetID(), GetMessage(), GetTitle(), GetTotal(), IsDebuggerSpecific(), and ProgressEventData().
Referenced by lldb::SBDebugger::GetProgressDataFromEvent().
GetCompleted()
uint64_t lldb_private::ProgressEventData::GetCompleted () const inline
Definition at line 44 of file DebuggerEvents.h.
References m_completed.
Referenced by GetAsStructuredData(), and lldb::SBDebugger::GetProgressFromEvent().
GetDetails()
const std::string & lldb_private::ProgressEventData::GetDetails () const inline
Definition at line 55 of file DebuggerEvents.h.
References m_details.
Referenced by GetAsStructuredData().
GetEventDataFromEvent()
const ProgressEventData * ProgressEventData::GetEventDataFromEvent (const Event * event_ptr) static
Definition at line 50 of file DebuggerEvents.cpp.
References lldb_private::EventData::Event, and GetEventDataFromEventImpl().
Referenced by GetAsStructuredData(), lldb::SBDebugger::GetProgressFromEvent(), and lldb_private::Debugger::HandleProgressEvent().
GetFlavor()
llvm::StringRef ProgressEventData::GetFlavor () const override virtual
Implements lldb_private::EventData.
Definition at line 31 of file DebuggerEvents.cpp.
References GetFlavorString().
GetFlavorString()
llvm::StringRef ProgressEventData::GetFlavorString () static
Definition at line 27 of file DebuggerEvents.cpp.
Referenced by GetFlavor().
GetID()
uint64_t lldb_private::ProgressEventData::GetID () const inline
Definition at line 42 of file DebuggerEvents.h.
References m_id.
Referenced by GetAsStructuredData(), and lldb::SBDebugger::GetProgressFromEvent().
GetMessage()
std::string lldb_private::ProgressEventData::GetMessage () const inline
Definition at line 46 of file DebuggerEvents.h.
References m_details, and m_title.
Referenced by GetAsStructuredData(), and lldb::SBDebugger::GetProgressFromEvent().
GetTitle()
const std::string & lldb_private::ProgressEventData::GetTitle () const inline
Definition at line 54 of file DebuggerEvents.h.
References m_title.
Referenced by GetAsStructuredData().
GetTotal()
uint64_t lldb_private::ProgressEventData::GetTotal () const inline
Definition at line 45 of file DebuggerEvents.h.
References m_total.
Referenced by GetAsStructuredData(), and lldb::SBDebugger::GetProgressFromEvent().
IsDebuggerSpecific()
bool lldb_private::ProgressEventData::IsDebuggerSpecific () const inline
Definition at line 56 of file DebuggerEvents.h.
References m_debugger_specific.
Referenced by GetAsStructuredData(), and lldb::SBDebugger::GetProgressFromEvent().
IsFinite()
bool lldb_private::ProgressEventData::IsFinite () const inline
Definition at line 43 of file DebuggerEvents.h.
References lldb_private::Progress::kNonDeterministicTotal, and m_total.
operator=()
const ProgressEventData & lldb_private::ProgressEventData::operator= (const ProgressEventData &) private delete
References ProgressEventData().
Member Data Documentation
m_completed
uint64_t lldb_private::ProgressEventData::m_completed private
Definition at line 70 of file DebuggerEvents.h.
Referenced by Dump(), GetCompleted(), and ProgressEventData().
m_debugger_specific
const bool lldb_private::ProgressEventData::m_debugger_specific private
Definition at line 72 of file DebuggerEvents.h.
Referenced by IsDebuggerSpecific(), and ProgressEventData().
m_details
std::string lldb_private::ProgressEventData::m_details private
Details associated with this progress event update.
The value is expected to change between progress events.
Definition at line 65 of file DebuggerEvents.h.
Referenced by Dump(), GetDetails(), GetMessage(), and ProgressEventData().
m_id
const uint64_t lldb_private::ProgressEventData::m_id private
Unique ID used to associate progress events.
Definition at line 68 of file DebuggerEvents.h.
Referenced by Dump(), GetID(), and ProgressEventData().
m_title
std::string lldb_private::ProgressEventData::m_title private
The title of this progress event.
The value is expected to remain stable for a given progress ID.
Definition at line 61 of file DebuggerEvents.h.
Referenced by Dump(), GetMessage(), GetTitle(), and ProgressEventData().
m_total
const uint64_t lldb_private::ProgressEventData::m_total private
Definition at line 71 of file DebuggerEvents.h.
Referenced by Dump(), GetTotal(), IsFinite(), and ProgressEventData().
The documentation for this class was generated from the following files:
DebuggerEvents.h
DebuggerEvents.cpp