LLDB: lldb_private::dil::ArraySubscriptNode Class Reference
lldb_private::dil::ArraySubscriptNode Class Reference
#include <DILAST.h>
Public Member Functions
ArraySubscriptNode (uint32_t location, ASTNodeUP base, ASTNodeUP index)
llvm::Expected< lldb::ValueObjectSP > Accept (Visitor *v) const override
ASTNode & GetBase () const
ASTNode & GetIndex () const
Public Member Functions inherited from lldb_private::dil::ASTNode
ASTNode (uint32_t location, NodeKind kind)
virtual ~ASTNode ()=default
uint32_t GetLocation () const
NodeKind GetKind () const
Static Public Member Functions
static bool classof (const ASTNode &node)
Private Attributes
ASTNodeUP m_base
ASTNodeUP m_index
Detailed Description
Definition at line 151 of file DILAST.h.
Constructor & Destructor Documentation
ArraySubscriptNode()
lldb_private::dil::ArraySubscriptNode::ArraySubscriptNode (uint32_t location, ASTNodeUP base, ASTNodeUP index) inline
Definition at line 153 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), lldb_private::dil::eArraySubscriptNode, m_base, and m_index.
Member Function Documentation
Accept()
llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::ArraySubscriptNode::Accept (Visitor * v) const override virtual
Implements lldb_private::dil::ASTNode.
Definition at line 31 of file DILAST.cpp.
References lldb_private::dil::Visitor::Visit().
classof()
bool lldb_private::dil::ArraySubscriptNode::classof (const ASTNode & node) inline static
Definition at line 162 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), lldb_private::dil::eArraySubscriptNode, and lldb_private::dil::ASTNode::GetKind().
GetBase()
ASTNode & lldb_private::dil::ArraySubscriptNode::GetBase () const inline
Definition at line 159 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), and m_base.
Referenced by lldb_private::dil::Interpreter::Visit().
GetIndex()
ASTNode & lldb_private::dil::ArraySubscriptNode::GetIndex () const inline
Definition at line 160 of file DILAST.h.
References lldb_private::dil::ASTNode::ASTNode(), and m_index.
Referenced by lldb_private::dil::Interpreter::Visit().
Member Data Documentation
m_base
ASTNodeUP lldb_private::dil::ArraySubscriptNode::m_base private
Definition at line 167 of file DILAST.h.
Referenced by ArraySubscriptNode(), and GetBase().
m_index
ASTNodeUP lldb_private::dil::ArraySubscriptNode::m_index private
Definition at line 168 of file DILAST.h.
Referenced by ArraySubscriptNode(), and GetIndex().
The documentation for this class was generated from the following files:
DILAST.h
DILAST.cpp