LLDB: SymbolVendorELF Class Reference
SymbolVendorELF Class Reference
#include <SymbolVendorELF.h>
Public Member Functions
SymbolVendorELF (const lldb::ModuleSP &module_sp)
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::SymbolVendor
SymbolVendor (const lldb::ModuleSP &module_sp)
void AddSymbolFileRepresentation (const lldb::ObjectFileSP &objfile_sp)
SymbolFile * GetSymbolFile ()
Public Member Functions inherited from lldb_private::ModuleChild
ModuleChild (const lldb::ModuleSP &module_sp)
Construct with owning module.
~ModuleChild ()
Destructor.
const ModuleChild & operator= (const ModuleChild &rhs)
Assignment operator.
lldb::ModuleSP GetModule () const
Get const accessor for the module pointer.
void SetModule (const lldb::ModuleSP &module_sp)
Set accessor for the module pointer.
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static lldb_private::SymbolVendor * CreateInstance (const lldb::ModuleSP &module_sp, lldb_private::Stream *feedback_strm)
Static Public Member Functions inherited from lldb_private::SymbolVendor
static SymbolVendor * FindPlugin (const lldb::ModuleSP &module_sp, Stream *feedback_strm)
Additional Inherited Members
Protected Attributes inherited from lldb_private::SymbolVendor
std::unique_ptr< SymbolFile > m_sym_file_up
Protected Attributes inherited from lldb_private::ModuleChild
lldb::ModuleWP m_module_wp
The Module that owns the object that inherits from this class.
Detailed Description
Definition at line 15 of file SymbolVendorELF.h.
Constructor & Destructor Documentation
SymbolVendorELF()
SymbolVendorELF::SymbolVendorELF (const lldb::ModuleSP & module_sp)
Definition at line 30 of file SymbolVendorELF.cpp.
References lldb_private::SymbolVendor::SymbolVendor(), and SymbolVendorELF().
Referenced by CreateInstance(), and SymbolVendorELF().
Member Function Documentation
CreateInstance()
SymbolVendor * SymbolVendorELF::CreateInstance (const lldb::ModuleSP & module_sp, lldb_private::Stream * feedback_strm) static
Definition at line 71 of file SymbolVendorELF.cpp.
References lldb_private::SectionList::AddSection(), lldb_private::SymbolVendor::AddSymbolFileRepresentation(), lldb::eSectionTypeDWARFDebugAbbrev, lldb::eSectionTypeDWARFDebugAddr, lldb::eSectionTypeDWARFDebugAranges, lldb::eSectionTypeDWARFDebugCuIndex, lldb::eSectionTypeDWARFDebugFrame, lldb::eSectionTypeDWARFDebugInfo, lldb::eSectionTypeDWARFDebugLine, lldb::eSectionTypeDWARFDebugLineStr, lldb::eSectionTypeDWARFDebugLoc, lldb::eSectionTypeDWARFDebugLocLists, lldb::eSectionTypeDWARFDebugMacInfo, lldb::eSectionTypeDWARFDebugMacro, lldb::eSectionTypeDWARFDebugNames, lldb::eSectionTypeDWARFDebugPubNames, lldb::eSectionTypeDWARFDebugPubTypes, lldb::eSectionTypeDWARFDebugRanges, lldb::eSectionTypeDWARFDebugRngLists, lldb::eSectionTypeDWARFDebugStr, lldb::eSectionTypeDWARFDebugStrOffsets, lldb::eSectionTypeDWARFDebugTypes, lldb::eSectionTypeDWARFGNUDebugAltLink, lldb::eSectionTypeELFSymbolTable, lldb_private::ObjectFile::eTypeDebugInfo, lldb_private::ObjectFile::FindPlugin(), lldb_private::SectionList::FindSectionByType(), ObjectFileELF::GetDebugLink(), lldb_private::Target::GetDefaultDebugFileSearchPaths(), lldb_private::ModuleSpec::GetFileSpec(), lldb_private::ObjectFile::GetFileSpec(), lldb_private::ObjectFile::GetSectionList(), lldb_private::ModuleSpec::GetSymbolFileSpec(), lldb_private::ModuleSpec::GetUUID(), ObjectFileELF::GetUUID(), lldb_private::FileSystem::Instance(), IsDwpSymbolFile(), LLDB_SCOPED_TIMERF, lldb_private::PluginManager::LocateExecutableObjectFile(), lldb_private::PluginManager::LocateExecutableSymbolFile(), lldb_private::SectionList::ReplaceSection(), lldb_private::FileSystem::Resolve(), and SymbolVendorELF().
Referenced by Initialize(), and Terminate().
GetPluginDescriptionStatic()
llvm::StringRef SymbolVendorELF::GetPluginDescriptionStatic () static
Definition at line 42 of file SymbolVendorELF.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef SymbolVendorELF::GetPluginName () inline override virtual
Reimplemented from lldb_private::SymbolVendor.
Definition at line 34 of file SymbolVendorELF.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef SymbolVendorELF::GetPluginNameStatic () inline static
Definition at line 25 of file SymbolVendorELF.h.
Referenced by GetPluginName(), and Initialize().
Initialize()
void SymbolVendorELF::Initialize () static
Definition at line 33 of file SymbolVendorELF.cpp.
References CreateInstance(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Terminate()
void SymbolVendorELF::Terminate () static
Definition at line 38 of file SymbolVendorELF.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
The documentation for this class was generated from the following files:
SymbolVendorELF.h
SymbolVendorELF.cpp