LLDB: lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted Class Reference
lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted Class Reference
Public Member Functions
bool IsPossibleTaggedPointer (lldb::addr_t ptr) override
ObjCLanguageRuntime::ClassDescriptorSP GetClassDescriptor (lldb::addr_t ptr) override
Public Member Functions inherited from lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2
~TaggedPointerVendorV2 () override=default
Public Member Functions inherited from lldb_private::ObjCLanguageRuntime::TaggedPointerVendor
virtual ~TaggedPointerVendor ()=default
Protected Types
typedef std::map< uint8_t, ObjCLanguageRuntime::ClassDescriptorSP > Cache
typedef Cache::iterator CacheIterator
Protected Member Functions
TaggedPointerVendorRuntimeAssisted (AppleObjCRuntimeV2 &runtime, uint64_t objc_debug_taggedpointer_mask, uint32_t objc_debug_taggedpointer_slot_shift, uint32_t objc_debug_taggedpointer_slot_mask, uint32_t objc_debug_taggedpointer_payload_lshift, uint32_t objc_debug_taggedpointer_payload_rshift, lldb::addr_t objc_debug_taggedpointer_classes)
TaggedPointerVendorRuntimeAssisted (const TaggedPointerVendorRuntimeAssisted &)=delete
const TaggedPointerVendorRuntimeAssisted & operator= (const TaggedPointerVendorRuntimeAssisted &)=delete
Protected Member Functions inherited from lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2
TaggedPointerVendorV2 (AppleObjCRuntimeV2 &runtime)
Protected Member Functions inherited from lldb_private::ObjCLanguageRuntime::TaggedPointerVendor
TaggedPointerVendor ()=default
Protected Attributes
Cache m_cache
uint64_t m_objc_debug_taggedpointer_mask
uint32_t m_objc_debug_taggedpointer_slot_shift
uint32_t m_objc_debug_taggedpointer_slot_mask
uint32_t m_objc_debug_taggedpointer_payload_lshift
uint32_t m_objc_debug_taggedpointer_payload_rshift
lldb::addr_t m_objc_debug_taggedpointer_classes
Protected Attributes inherited from lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2
AppleObjCRuntimeV2 & m_runtime
Friends
class AppleObjCRuntimeV2::TaggedPointerVendorV2
Additional Inherited Members
Static Public Member Functions inherited from lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2
static TaggedPointerVendorV2 * CreateInstance (AppleObjCRuntimeV2 &runtime, const lldb::ModuleSP &objc_module_sp)
Detailed Description
Definition at line 197 of file AppleObjCRuntimeV2.h.
Member Typedef Documentation
Cache
typedef std::map<uint8_t, ObjCLanguageRuntime::ClassDescriptorSP> lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted::Cache protected
Definition at line 213 of file AppleObjCRuntimeV2.h.
CacheIterator
typedef Cache::iterator lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted::CacheIterator protected
Definition at line 214 of file AppleObjCRuntimeV2.h.
Constructor & Destructor Documentation
TaggedPointerVendorRuntimeAssisted() [1/2]
AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted::TaggedPointerVendorRuntimeAssisted (AppleObjCRuntimeV2 & runtime, uint64_t objc_debug_taggedpointer_mask, uint32_t objc_debug_taggedpointer_slot_shift, uint32_t objc_debug_taggedpointer_slot_mask, uint32_t objc_debug_taggedpointer_payload_lshift, uint32_t objc_debug_taggedpointer_payload_rshift, lldb::addr_t objc_debug_taggedpointer_classes) protected
Definition at line 3044 of file AppleObjCRuntimeV2.cpp.
Referenced by lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorExtended::GetClassDescriptor(), operator=(), and TaggedPointerVendorRuntimeAssisted().
TaggedPointerVendorRuntimeAssisted() [2/2]
lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted::TaggedPointerVendorRuntimeAssisted (const TaggedPointerVendorRuntimeAssisted &) protected delete
References TaggedPointerVendorRuntimeAssisted().
Member Function Documentation
GetClassDescriptor()
ObjCLanguageRuntime::ClassDescriptorSP AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted::GetClassDescriptor (lldb::addr_t ptr) override virtual
Implements lldb_private::ObjCLanguageRuntime::TaggedPointerVendor.
Definition at line 3069 of file AppleObjCRuntimeV2.cpp.
IsPossibleTaggedPointer()
bool AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted::IsPossibleTaggedPointer (lldb::addr_t ptr) override virtual
Implements lldb_private::ObjCLanguageRuntime::TaggedPointerVendor.
Definition at line 3063 of file AppleObjCRuntimeV2.cpp.
operator=()
const TaggedPointerVendorRuntimeAssisted & lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted::operator= (const TaggedPointerVendorRuntimeAssisted &) protected delete
References TaggedPointerVendorRuntimeAssisted().
Friends And Related Symbol Documentation
AppleObjCRuntimeV2::TaggedPointerVendorV2
friend class AppleObjCRuntimeV2::TaggedPointerVendorV2 friend
Definition at line 223 of file AppleObjCRuntimeV2.h.
Member Data Documentation
m_cache
Cache lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted::m_cache protected
Definition at line 215 of file AppleObjCRuntimeV2.h.
m_objc_debug_taggedpointer_classes
lldb::addr_t lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted::m_objc_debug_taggedpointer_classes protected
Definition at line 221 of file AppleObjCRuntimeV2.h.
m_objc_debug_taggedpointer_mask
uint64_t lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted::m_objc_debug_taggedpointer_mask protected
Definition at line 216 of file AppleObjCRuntimeV2.h.
m_objc_debug_taggedpointer_payload_lshift
uint32_t lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted::m_objc_debug_taggedpointer_payload_lshift protected
Definition at line 219 of file AppleObjCRuntimeV2.h.
m_objc_debug_taggedpointer_payload_rshift
uint32_t lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted::m_objc_debug_taggedpointer_payload_rshift protected
Definition at line 220 of file AppleObjCRuntimeV2.h.
m_objc_debug_taggedpointer_slot_mask
uint32_t lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted::m_objc_debug_taggedpointer_slot_mask protected
Definition at line 218 of file AppleObjCRuntimeV2.h.
m_objc_debug_taggedpointer_slot_shift
uint32_t lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted::m_objc_debug_taggedpointer_slot_shift protected
Definition at line 217 of file AppleObjCRuntimeV2.h.
The documentation for this class was generated from the following files:
AppleObjCRuntimeV2.h
AppleObjCRuntimeV2.cpp