LLDB: lldb_private::ThreadPlanStepUntil Class Reference
lldb_private::ThreadPlanStepUntil Class Reference
#include <ThreadPlanStepUntil.h>
Public Member Functions
~ThreadPlanStepUntil () override
void GetDescription (Stream *s, lldb::DescriptionLevel level) override
Print a description of this thread to the stream s.
bool ValidatePlan (Stream *error) override
Returns whether this plan could be successfully created.
bool ShouldStop (Event *event_ptr) override
bool StopOthers () override
lldb::StateType GetPlanRunState () override
bool WillStop () override
bool MischiefManaged () override
Public Member Functions inherited from lldb_private::ThreadPlan
virtual ~ThreadPlan ()
const char * GetName () const
Returns the name of this thread plan.
Thread & GetThread ()
Returns the Thread that is using this thread plan.
Target & GetTarget ()
const Target & GetTarget () const
void ClearThreadCache ()
Clear the Thread* cache.
bool TracerExplainsStop ()
lldb::StateType RunState ()
bool PlanExplainsStop (Event *event_ptr)
virtual bool ShouldAutoContinue (Event *event_ptr)
Returns whether this thread plan overrides the ShouldStop of subsequently processed plans.
virtual Vote ShouldReportStop (Event *event_ptr)
Vote ShouldReportRun (Event *event_ptr)
virtual void SetStopOthers (bool new_value)
virtual bool SupportsResumeOthers ()
virtual bool ShouldRunBeforePublicStop ()
bool WillResume (lldb::StateType resume_state, bool current_plan)
bool IsControllingPlan ()
virtual bool IsLeafPlan ()
bool SetIsControllingPlan (bool value)
virtual bool OkayToDiscard ()
void SetOkayToDiscard (bool value)
virtual void ThreadDestroyed ()
bool GetPrivate ()
void SetPrivate (bool input)
virtual void DidPush ()
virtual void DidPop ()
ThreadPlanKind GetKind () const
bool IsPlanComplete ()
void SetPlanComplete (bool success=true)
virtual bool IsPlanStale ()
bool PlanSucceeded ()
virtual bool IsBasePlan ()
lldb::ThreadPlanTracerSP & GetThreadPlanTracer ()
void SetThreadPlanTracer (lldb::ThreadPlanTracerSP new_tracer_sp)
void DoTraceLog ()
virtual lldb::ValueObjectSP GetReturnValueObject ()
virtual lldb::ExpressionVariableSP GetExpressionVariable ()
virtual void RestoreThreadState ()
virtual bool IsVirtualStep ()
bool SetIterationCount (size_t count)
virtual lldb::RunDirection GetDirection () const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Protected Member Functions
bool DoWillResume (lldb::StateType resume_state, bool current_plan) override
bool DoPlanExplainsStop (Event *event_ptr) override
ThreadPlanStepUntil (Thread &thread, lldb::addr_t *address_list, size_t num_addresses, bool stop_others, uint32_t frame_idx=0)
void AnalyzeStop ()
Protected Member Functions inherited from lldb_private::ThreadPlan
ThreadPlan (ThreadPlanKind kind, const char *name, Thread &thread, Vote report_stop_vote, Vote report_run_vote)
void PushPlan (lldb::ThreadPlanSP &thread_plan_sp)
ThreadPlan * GetPreviousPlan ()
lldb::StopInfoSP GetPrivateStopInfo ()
void SetStopInfo (lldb::StopInfoSP stop_reason_sp)
bool IsUsuallyUnexplainedStopReason (lldb::StopReason)
Private Types
typedef std::map< lldb::addr_t, lldb::break_id_t > until_collection
Private Member Functions
void Clear ()
ThreadPlanStepUntil (const ThreadPlanStepUntil &)=delete
const ThreadPlanStepUntil & operator= (const ThreadPlanStepUntil &)=delete
Private Attributes
StackID m_stack_id
lldb::addr_t m_step_from_insn
lldb::break_id_t m_return_bp_id
lldb::addr_t m_return_addr
bool m_stepped_out
bool m_should_stop
bool m_ran_analyze
bool m_explains_stop
until_collection m_until_points
bool m_stop_others
Friends
lldb::ThreadPlanSP Thread::QueueThreadPlanForStepUntil (bool abort_other_plans, lldb::addr_t *address_list, size_t num_addresses, bool stop_others, uint32_t frame_idx, Status &status)
Additional Inherited Members
Public Types inherited from lldb_private::ThreadPlan
enum ThreadPlanKind {
eKindGeneric , eKindNull , eKindBase , eKindCallFunction ,
eKindPython , eKindStepInstruction , eKindStepOut , eKindStepOverBreakpoint ,
eKindStepOverRange , eKindStepInRange , eKindRunToAddress , eKindStepThrough ,
eKindStepUntil , eKindSingleThreadTimeout
}
Protected Attributes inherited from lldb_private::ThreadPlan
Status m_status
Process & m_process
lldb::tid_t m_tid
Vote m_report_stop_vote
Vote m_report_run_vote
bool m_takes_iteration_count
bool m_could_not_resolve_hw_bp
int32_t m_iteration_count = 1
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Detailed Description
Definition at line 17 of file ThreadPlanStepUntil.h.
Member Typedef Documentation
until_collection
typedef std::map<lldb::addr_t, lldb::break_id_t> lldb_private::ThreadPlanStepUntil::until_collection private
Definition at line 49 of file ThreadPlanStepUntil.h.
Constructor & Destructor Documentation
~ThreadPlanStepUntil()
ThreadPlanStepUntil::~ThreadPlanStepUntil () override
Definition at line 80 of file ThreadPlanStepUntil.cpp.
References Clear().
ThreadPlanStepUntil() [1/2]
ThreadPlanStepUntil::ThreadPlanStepUntil (Thread & thread, lldb::addr_t * address_list, size_t num_addresses, bool stop_others, uint32_t frame_idx = 0) protected
Definition at line 26 of file ThreadPlanStepUntil.cpp.
References lldb_private::ThreadPlan::eKindStepUntil, lldb_private::eVoteNoOpinion, lldb_private::Stoppoint::GetID(), lldb_private::Breakpoint::HasResolvedLocations(), lldb_private::Breakpoint::IsHardware(), LLDB_INVALID_ADDRESS, LLDB_INVALID_BREAK_ID, lldb_private::ThreadPlan::m_could_not_resolve_hw_bp, m_explains_stop, m_ran_analyze, m_return_addr, m_return_bp_id, m_should_stop, m_stack_id, m_step_from_insn, m_stepped_out, m_stop_others, lldb_private::ThreadPlan::m_tid, m_until_points, lldb_private::Breakpoint::SetBreakpointKind(), lldb_private::Breakpoint::SetThreadID(), and lldb_private::ThreadPlan::ThreadPlan().
Referenced by operator=(), and ThreadPlanStepUntil().
ThreadPlanStepUntil() [2/2]
lldb_private::ThreadPlanStepUntil::ThreadPlanStepUntil (const ThreadPlanStepUntil &) private delete
References ThreadPlanStepUntil().
Member Function Documentation
AnalyzeStop()
void ThreadPlanStepUntil::AnalyzeStop () protected
Definition at line 144 of file ThreadPlanStepUntil.cpp.
References lldb::eStopReasonBreakpoint, lldb_private::ThreadPlan::GetPrivateStopInfo(), lldb_private::ThreadPlan::GetThread(), lldb_private::ThreadPlan::IsUsuallyUnexplainedStopReason(), m_explains_stop, lldb_private::ThreadPlan::m_process, m_ran_analyze, m_return_bp_id, m_should_stop, m_stack_id, m_stepped_out, m_until_points, and lldb_private::ThreadPlan::SetPlanComplete().
Referenced by DoPlanExplainsStop(), and ShouldStop().
Clear()
void ThreadPlanStepUntil::Clear () private
Definition at line 82 of file ThreadPlanStepUntil.cpp.
References lldb_private::ThreadPlan::GetTarget(), LLDB_INVALID_BREAK_ID, lldb_private::ThreadPlan::m_could_not_resolve_hw_bp, m_return_bp_id, m_until_points, and lldb_private::Target::RemoveBreakpointByID().
Referenced by MischiefManaged(), and ~ThreadPlanStepUntil().
DoPlanExplainsStop()
bool ThreadPlanStepUntil::DoPlanExplainsStop (Event * event_ptr) override protected virtual
Implements lldb_private::ThreadPlan.
Definition at line 253 of file ThreadPlanStepUntil.cpp.
References AnalyzeStop(), and m_explains_stop.
DoWillResume()
bool ThreadPlanStepUntil::DoWillResume (lldb::StateType resume_state, bool current_plan) override protected virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 277 of file ThreadPlanStepUntil.cpp.
References lldb_private::Target::GetBreakpointByID(), lldb_private::ThreadPlan::GetTarget(), m_explains_stop, m_ran_analyze, m_return_bp_id, m_should_stop, m_until_points, and lldb_private::Breakpoint::SetEnabled().
GetDescription()
void ThreadPlanStepUntil::GetDescription (Stream * s, lldb::DescriptionLevel level) override virtual
Print a description of this thread to the stream s.
thread. Don't expect that the result of GetThread is valid in the description method. This might get called when the underlying Thread has not been reported, so we only know the TID and not the thread.
Parameters
[in] s The stream to which to print the description.
[in] level The level of description desired. Note that eDescriptionLevelBrief will be used in the stop message printed when the plan is complete.
Implements lldb_private::ThreadPlan.
Definition at line 97 of file ThreadPlanStepUntil.cpp.
References lldb::eDescriptionLevelBrief, m_return_addr, m_step_from_insn, m_stepped_out, m_until_points, and lldb_private::Stream::Printf().
GetPlanRunState()
StateType ThreadPlanStepUntil::GetPlanRunState () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 275 of file ThreadPlanStepUntil.cpp.
References lldb::eStateRunning.
MischiefManaged()
bool ThreadPlanStepUntil::MischiefManaged () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 314 of file ThreadPlanStepUntil.cpp.
References Clear(), lldb_private::GetLog(), lldb_private::ThreadPlan::IsPlanComplete(), LLDB_LOGF, lldb_private::ThreadPlan::MischiefManaged(), and lldb_private::Step.
operator=()
const ThreadPlanStepUntil & lldb_private::ThreadPlanStepUntil::operator= (const ThreadPlanStepUntil &) private delete
References ThreadPlanStepUntil().
ShouldStop()
bool ThreadPlanStepUntil::ShouldStop (Event * event_ptr) override virtual
Implements lldb_private::ThreadPlan.
Definition at line 260 of file ThreadPlanStepUntil.cpp.
References AnalyzeStop(), lldb::eStopReasonNone, lldb_private::ThreadPlan::GetPrivateStopInfo(), and m_should_stop.
StopOthers()
bool ThreadPlanStepUntil::StopOthers () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 273 of file ThreadPlanStepUntil.cpp.
References m_stop_others.
ValidatePlan()
bool ThreadPlanStepUntil::ValidatePlan (Stream * error) override virtual
Returns whether this plan could be successfully created.
Parameters
[in] error A stream to which to print some reason why the plan could not be created. Can be NULL.
Returns
true if the plan should be queued, false otherwise.
Implements lldb_private::ThreadPlan.
Definition at line 124 of file ThreadPlanStepUntil.cpp.
References error(), LLDB_BREAK_ID_IS_VALID, LLDB_INVALID_BREAK_ID, lldb_private::ThreadPlan::m_could_not_resolve_hw_bp, m_return_bp_id, and m_until_points.
WillStop()
bool ThreadPlanStepUntil::WillStop () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 299 of file ThreadPlanStepUntil.cpp.
References lldb_private::Target::GetBreakpointByID(), lldb_private::ThreadPlan::GetTarget(), m_return_bp_id, m_until_points, and lldb_private::Breakpoint::SetEnabled().
Friends And Related Symbol Documentation
Thread::QueueThreadPlanForStepUntil
lldb::ThreadPlanSP Thread::QueueThreadPlanForStepUntil (bool abort_other_plans, lldb::addr_t * address_list, size_t num_addresses, bool stop_others, uint32_t frame_idx, Status & status) friend
Member Data Documentation
m_explains_stop
bool lldb_private::ThreadPlanStepUntil::m_explains_stop private
Definition at line 47 of file ThreadPlanStepUntil.h.
Referenced by AnalyzeStop(), DoPlanExplainsStop(), DoWillResume(), and ThreadPlanStepUntil().
m_ran_analyze
bool lldb_private::ThreadPlanStepUntil::m_ran_analyze private
Definition at line 46 of file ThreadPlanStepUntil.h.
Referenced by AnalyzeStop(), DoWillResume(), and ThreadPlanStepUntil().
m_return_addr
lldb::addr_t lldb_private::ThreadPlanStepUntil::m_return_addr private
Definition at line 43 of file ThreadPlanStepUntil.h.
Referenced by GetDescription(), and ThreadPlanStepUntil().
m_return_bp_id
lldb::break_id_t lldb_private::ThreadPlanStepUntil::m_return_bp_id private
Definition at line 42 of file ThreadPlanStepUntil.h.
Referenced by AnalyzeStop(), Clear(), DoWillResume(), ThreadPlanStepUntil(), ValidatePlan(), and WillStop().
m_should_stop
bool lldb_private::ThreadPlanStepUntil::m_should_stop private
Definition at line 45 of file ThreadPlanStepUntil.h.
Referenced by AnalyzeStop(), DoWillResume(), ShouldStop(), and ThreadPlanStepUntil().
m_stack_id
StackID lldb_private::ThreadPlanStepUntil::m_stack_id private
Definition at line 40 of file ThreadPlanStepUntil.h.
Referenced by AnalyzeStop(), and ThreadPlanStepUntil().
m_step_from_insn
lldb::addr_t lldb_private::ThreadPlanStepUntil::m_step_from_insn private
Definition at line 41 of file ThreadPlanStepUntil.h.
Referenced by GetDescription(), and ThreadPlanStepUntil().
m_stepped_out
bool lldb_private::ThreadPlanStepUntil::m_stepped_out private
Definition at line 44 of file ThreadPlanStepUntil.h.
Referenced by AnalyzeStop(), GetDescription(), and ThreadPlanStepUntil().
m_stop_others
bool lldb_private::ThreadPlanStepUntil::m_stop_others private
Definition at line 51 of file ThreadPlanStepUntil.h.
Referenced by StopOthers(), and ThreadPlanStepUntil().
m_until_points
until_collection lldb_private::ThreadPlanStepUntil::m_until_points private
Definition at line 50 of file ThreadPlanStepUntil.h.
Referenced by AnalyzeStop(), Clear(), DoWillResume(), GetDescription(), ThreadPlanStepUntil(), ValidatePlan(), and WillStop().
The documentation for this class was generated from the following files:
ThreadPlanStepUntil.h
ThreadPlanStepUntil.cpp