LLDB: lldb_private::ExecuteScriptOptions Class Reference
lldb_private::ExecuteScriptOptions Class Reference
#include <ScriptInterpreter.h>
Public Member Functions
ExecuteScriptOptions ()=default
bool GetEnableIO () const
bool GetSetLLDBGlobals () const
bool GetMaskoutErrors () const
ExecuteScriptOptions & SetEnableIO (bool enable)
ExecuteScriptOptions & SetSetLLDBGlobals (bool set)
ExecuteScriptOptions & SetMaskoutErrors (bool maskout)
Private Attributes
bool m_enable_io = true
bool m_set_lldb_globals = true
bool m_maskout_errors = true
Detailed Description
Definition at line 59 of file ScriptInterpreter.h.
Constructor & Destructor Documentation
ExecuteScriptOptions()
lldb_private::ExecuteScriptOptions::ExecuteScriptOptions () default
Referenced by SetEnableIO(), SetMaskoutErrors(), and SetSetLLDBGlobals().
Member Function Documentation
GetEnableIO()
bool lldb_private::ExecuteScriptOptions::GetEnableIO () const inline
Definition at line 63 of file ScriptInterpreter.h.
References m_enable_io.
Referenced by lldb_private::ScriptInterpreterLua::ExecuteOneLine().
GetMaskoutErrors()
bool lldb_private::ExecuteScriptOptions::GetMaskoutErrors () const inline
Definition at line 70 of file ScriptInterpreter.h.
References m_maskout_errors.
GetSetLLDBGlobals()
bool lldb_private::ExecuteScriptOptions::GetSetLLDBGlobals () const inline
Definition at line 65 of file ScriptInterpreter.h.
References m_set_lldb_globals.
SetEnableIO()
ExecuteScriptOptions & lldb_private::ExecuteScriptOptions::SetEnableIO (bool enable) inline
Definition at line 72 of file ScriptInterpreter.h.
References ExecuteScriptOptions(), and m_enable_io.
SetMaskoutErrors()
ExecuteScriptOptions & lldb_private::ExecuteScriptOptions::SetMaskoutErrors (bool maskout) inline
Definition at line 82 of file ScriptInterpreter.h.
References ExecuteScriptOptions(), and m_maskout_errors.
SetSetLLDBGlobals()
ExecuteScriptOptions & lldb_private::ExecuteScriptOptions::SetSetLLDBGlobals (bool set) inline
Definition at line 77 of file ScriptInterpreter.h.
References ExecuteScriptOptions(), and m_set_lldb_globals.
Member Data Documentation
m_enable_io
bool lldb_private::ExecuteScriptOptions::m_enable_io = true private
Definition at line 88 of file ScriptInterpreter.h.
Referenced by GetEnableIO(), and SetEnableIO().
m_maskout_errors
bool lldb_private::ExecuteScriptOptions::m_maskout_errors = true private
Definition at line 90 of file ScriptInterpreter.h.
Referenced by GetMaskoutErrors(), and SetMaskoutErrors().
m_set_lldb_globals
bool lldb_private::ExecuteScriptOptions::m_set_lldb_globals = true private
Definition at line 89 of file ScriptInterpreter.h.
Referenced by GetSetLLDBGlobals(), and SetSetLLDBGlobals().
The documentation for this class was generated from the following file:
ScriptInterpreter.h