LLDB: sddarwinlog_private::RegexFilterRule Class Reference
sddarwinlog_private::RegexFilterRule Class Reference
Public Member Functions
void Dump (Stream &stream) const override
Public Member Functions inherited from sddarwinlog_private::FilterRule
virtual ~FilterRule ()=default
StructuredData::ObjectSP Serialize () const
llvm::StringRef GetOperationType () const
Static Public Member Functions
static void RegisterOperation ()
Static Public Member Functions inherited from sddarwinlog_private::FilterRule
static void RegisterOperation (llvm::StringRef operation, const OperationCreationFunc &creation_func)
static FilterRuleSP CreateRule (bool match_accepts, size_t attribute, llvm::StringRef operation, const std::string &op_arg, Status &error)
Protected Member Functions
void DoSerialization (StructuredData::Dictionary &dict) const override
Protected Member Functions inherited from sddarwinlog_private::FilterRule
FilterRule (bool accept, size_t attribute_index, llvm::StringRef operation)
bool GetMatchAccepts () const
const char * GetFilterAttribute () const
Private Member Functions
RegexFilterRule (bool accept, size_t attribute_index, const std::string &regex_text)
Static Private Member Functions
static FilterRuleSP CreateOperation (bool accept, size_t attribute_index, const std::string &op_arg, Status &error)
static llvm::StringRef StaticGetOperation ()
Private Attributes
const std::string m_regex_text
Additional Inherited Members
Public Types inherited from sddarwinlog_private::FilterRule
using OperationCreationFunc
Detailed Description
Definition at line 262 of file StructuredDataDarwinLog.cpp.
Constructor & Destructor Documentation
RegexFilterRule()
sddarwinlog_private::RegexFilterRule::RegexFilterRule (bool accept, size_t attribute_index, const std::string & regex_text) inline private
Definition at line 306 of file StructuredDataDarwinLog.cpp.
References sddarwinlog_private::FilterRule::FilterRule(), m_regex_text, and StaticGetOperation().
Referenced by CreateOperation().
Member Function Documentation
CreateOperation()
FilterRuleSP sddarwinlog_private::RegexFilterRule::CreateOperation (bool accept, size_t attribute_index, const std::string & op_arg, Status & error) inline static private
Definition at line 279 of file StructuredDataDarwinLog.cpp.
References error(), lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), RegexFilterRule(), and lldb_private::RegularExpression.
Referenced by RegisterOperation().
DoSerialization()
void sddarwinlog_private::RegexFilterRule::DoSerialization (StructuredData::Dictionary & dict) const inline override protected virtual
Implements sddarwinlog_private::FilterRule.
Definition at line 274 of file StructuredDataDarwinLog.cpp.
References lldb_private::StructuredData::Dictionary::AddStringItem(), and m_regex_text.
Dump()
void sddarwinlog_private::RegexFilterRule::Dump (Stream & stream) const inline override virtual
Implements sddarwinlog_private::FilterRule.
Definition at line 268 of file StructuredDataDarwinLog.cpp.
References sddarwinlog_private::FilterRule::GetFilterAttribute(), sddarwinlog_private::FilterRule::GetMatchAccepts(), m_regex_text, and lldb_private::Stream::Printf().
RegisterOperation()
void sddarwinlog_private::RegexFilterRule::RegisterOperation () inline static
Definition at line 264 of file StructuredDataDarwinLog.cpp.
References CreateOperation(), sddarwinlog_private::FilterRule::RegisterOperation(), and StaticGetOperation().
Referenced by sddarwinlog_private::RegisterFilterOperations().
StaticGetOperation()
llvm::StringRef sddarwinlog_private::RegexFilterRule::StaticGetOperation () inline static private
Definition at line 301 of file StructuredDataDarwinLog.cpp.
Referenced by RegexFilterRule(), and RegisterOperation().
Member Data Documentation
m_regex_text
const std::string sddarwinlog_private::RegexFilterRule::m_regex_text private
Definition at line 311 of file StructuredDataDarwinLog.cpp.
Referenced by DoSerialization(), Dump(), and RegexFilterRule().
The documentation for this class was generated from the following file:
StructuredDataDarwinLog.cpp