LLDB: lldb::SBValueList Class Reference
lldb::SBValueList Class Reference
#include <SBValueList.h>
Public Member Functions
SBValueList ()
SBValueList (const lldb::SBValueList &rhs)
~SBValueList ()
operator bool () const
bool IsValid () const
void Clear ()
void Append (const lldb::SBValue &val_obj)
void Append (const lldb::SBValueList &value_list)
uint32_t GetSize () const
lldb::SBValue GetValueAtIndex (uint32_t idx) const
lldb::SBValue GetFirstValueByName (const char *name) const
lldb::SBValue FindValueObjectByUID (lldb::user_id_t uid)
const lldb::SBValueList & operator= (const lldb::SBValueList &rhs)
lldb::SBError GetError ()
Protected Member Functions
void * opaque_ptr ()
Private Member Functions
SBValueList (const ValueListImpl *lldb_object_ptr)
void Append (lldb::ValueObjectSP &val_obj_sp)
void CreateIfNeeded ()
ValueListImpl * operator-> ()
ValueListImpl & operator* ()
const ValueListImpl * operator-> () const
const ValueListImpl & operator* () const
ValueListImpl & ref ()
void SetError (lldb_private::Status &&status)
Private Attributes
std::unique_ptr< ValueListImpl > m_opaque_up
Friends
class SBFrame
Detailed Description
Definition at line 18 of file SBValueList.h.
Constructor & Destructor Documentation
SBValueList() [1/3]
SBValueList::SBValueList ()
Definition at line 78 of file SBValueList.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by operator=(), SBFrame, and SBValueList().
SBValueList() [2/3]
SBValueList::SBValueList (const lldb::SBValueList & rhs)
Definition at line 80 of file SBValueList.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBValueList().
~SBValueList()
SBValueList::~SBValueList () default
References Append(), Clear(), FindValueObjectByUID(), GetError(), GetFirstValueByName(), GetSize(), GetValueAtIndex(), IsValid(), opaque_ptr(), and operator=().
SBValueList() [3/3]
SBValueList::SBValueList (const ValueListImpl * lldb_object_ptr) private
Definition at line 87 of file SBValueList.cpp.
References m_opaque_up.
Member Function Documentation
Append() [1/3]
void SBValueList::Append (const lldb::SBValue & val_obj)
Definition at line 132 of file SBValueList.cpp.
References CreateIfNeeded(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by FetchVariablesUnlessInterrupted(), lldb::SBModule::FindGlobalVariables(), lldb::SBTarget::FindGlobalVariables(), lldb::SBTarget::FindGlobalVariables(), lldb::SBFrame::GetRegisters(), lldb::SBCommandReturnObject::GetValues(), lldb::SBBlock::GetVariables(), lldb::SBBlock::GetVariables(), lldb::SBFrame::GetVariables(), SBFrame, and ~SBValueList().
Append() [2/3]
void SBValueList::Append (const lldb::SBValueList & value_list)
Definition at line 146 of file SBValueList.cpp.
References CreateIfNeeded(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Append() [3/3]
void SBValueList::Append (lldb::ValueObjectSP & val_obj_sp) private
Definition at line 139 of file SBValueList.cpp.
References CreateIfNeeded(), m_opaque_up, and lldb::SBValue.
Clear()
void SBValueList::Clear ()
Definition at line 104 of file SBValueList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBValueList().
CreateIfNeeded()
void SBValueList::CreateIfNeeded () private
Definition at line 175 of file SBValueList.cpp.
References m_opaque_up.
Referenced by Append(), Append(), Append(), ref(), and SBFrame.
FindValueObjectByUID()
SBValue SBValueList::FindValueObjectByUID (lldb::user_id_t uid)
Definition at line 180 of file SBValueList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBValueList().
GetError()
lldb::SBError SBValueList::GetError ()
Definition at line 205 of file SBValueList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_up, and lldb::SBError::SetError().
Referenced by ~SBValueList().
GetFirstValueByName()
SBValue SBValueList::GetFirstValueByName (const char * name) const
Definition at line 189 of file SBValueList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by ~SBValueList().
GetSize()
uint32_t SBValueList::GetSize () const
Definition at line 165 of file SBValueList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBModule::FindFirstGlobalVariable(), lldb::SBTarget::FindFirstGlobalVariable(), and ~SBValueList().
GetValueAtIndex()
SBValue SBValueList::GetValueAtIndex (uint32_t idx) const
Definition at line 155 of file SBValueList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBModule::FindFirstGlobalVariable(), lldb::SBTarget::FindFirstGlobalVariable(), and ~SBValueList().
IsValid()
bool SBValueList::IsValid () const
Definition at line 94 of file SBValueList.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by Append(), lldb::SBModule::FindFirstGlobalVariable(), lldb::SBTarget::FindFirstGlobalVariable(), operator=(), SBValueList(), and ~SBValueList().
opaque_ptr()
void * SBValueList::opaque_ptr () protected
Definition at line 198 of file SBValueList.cpp.
References m_opaque_up.
Referenced by ~SBValueList().
operator bool()
SBValueList::operator bool () const explicit
Definition at line 98 of file SBValueList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
operator*() [1/2]
ValueListImpl & SBValueList::operator* () private
Definition at line 124 of file SBValueList.cpp.
References m_opaque_up.
Referenced by SBFrame.
operator*() [2/2]
const ValueListImpl & SBValueList::operator* () const private
Definition at line 130 of file SBValueList.cpp.
References m_opaque_up.
operator->() [1/2]
ValueListImpl * SBValueList::operator-> () private
Definition at line 122 of file SBValueList.cpp.
References m_opaque_up.
Referenced by SBFrame.
operator->() [2/2]
const ValueListImpl * SBValueList::operator-> () const private
Definition at line 126 of file SBValueList.cpp.
References m_opaque_up.
operator=()
const SBValueList & SBValueList::operator= (const lldb::SBValueList & rhs)
Definition at line 110 of file SBValueList.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBValueList().
Referenced by ~SBValueList().
ref()
ValueListImpl & SBValueList::ref () private
Definition at line 200 of file SBValueList.cpp.
References CreateIfNeeded(), and m_opaque_up.
Referenced by SBFrame, and SetError().
SetError()
void SBValueList::SetError (lldb_private::Status && status) private
Definition at line 213 of file SBValueList.cpp.
References ref(), and ValueListImpl::SetError().
Referenced by lldb::SBFrame::GetVariables().
Friends And Related Symbol Documentation
SBFrame
friend class SBFrame friend
Definition at line 79 of file SBValueList.h.
References Append(), CreateIfNeeded(), operator*(), operator->(), ref(), SBFrame, and SBValueList().
Referenced by SBFrame.
Member Data Documentation
m_opaque_up
std::unique_ptr<ValueListImpl> lldb::SBValueList::m_opaque_up private
Definition at line 97 of file SBValueList.h.
Referenced by Append(), Append(), Append(), Clear(), CreateIfNeeded(), FindValueObjectByUID(), GetError(), GetFirstValueByName(), GetSize(), GetValueAtIndex(), opaque_ptr(), operator bool(), operator*(), operator*(), operator->(), operator->(), operator=(), ref(), SBValueList(), and SBValueList().
The documentation for this class was generated from the following files:
SBValueList.h
SBValueList.cpp