LLDB: lldb_private::ClangDiagnostic Class Reference
lldb_private::ClangDiagnostic Class Reference
#include <ClangDiagnostic.h>
Public Types
typedef std::vector< clang::FixItHint > FixItList
Public Member Functions
ClangDiagnostic (DiagnosticDetail detail, uint32_t compiler_id)
~ClangDiagnostic () override=default
bool HasFixIts () const override
void AddFixitHint (const clang::FixItHint &fixit)
const FixItList & FixIts () const
Public Member Functions inherited from lldb_private::Diagnostic
DiagnosticOrigin getKind () const
Diagnostic (DiagnosticOrigin origin, uint32_t compiler_id, DiagnosticDetail detail)
virtual ~Diagnostic ()=default
lldb::Severity GetSeverity () const
uint32_t GetCompilerID () const
llvm::StringRef GetMessage () const
const DiagnosticDetail & GetDetail () const
void AppendMessage (llvm::StringRef message, bool precede_with_newline=true)
Static Public Member Functions
static bool classof (const ClangDiagnostic *)
static bool classof (const Diagnostic *diag)
Static Public Member Functions inherited from lldb_private::Diagnostic
static bool classof (const Diagnostic *diag)
Private Attributes
FixItList m_fixit_vec
Additional Inherited Members
Protected Attributes inherited from lldb_private::Diagnostic
DiagnosticOrigin m_origin
uint32_t m_compiler_id
Compiler-specific diagnostic ID.
DiagnosticDetail m_detail
Detailed Description
Definition at line 23 of file ClangDiagnostic.h.
Member Typedef Documentation
FixItList
typedef std::vector<clang::FixItHint> lldb_private::ClangDiagnostic::FixItList
Definition at line 25 of file ClangDiagnostic.h.
Constructor & Destructor Documentation
ClangDiagnostic()
lldb_private::ClangDiagnostic::ClangDiagnostic (DiagnosticDetail detail, uint32_t compiler_id) inline
Definition at line 32 of file ClangDiagnostic.h.
References lldb_private::Diagnostic::Diagnostic(), and lldb_private::eDiagnosticOriginClang.
Referenced by classof().
~ClangDiagnostic()
lldb_private::ClangDiagnostic::~ClangDiagnostic () override default
Member Function Documentation
AddFixitHint()
void lldb_private::ClangDiagnostic::AddFixitHint (const clang::FixItHint & fixit) inline
Definition at line 39 of file ClangDiagnostic.h.
References m_fixit_vec.
Referenced by AddAllFixIts().
classof() [1/2]
bool lldb_private::ClangDiagnostic::classof (const ClangDiagnostic *) inline static
Definition at line 27 of file ClangDiagnostic.h.
References ClangDiagnostic().
classof() [2/2]
bool lldb_private::ClangDiagnostic::classof (const Diagnostic * diag) inline static
Definition at line 28 of file ClangDiagnostic.h.
References lldb_private::Diagnostic::Diagnostic(), lldb_private::eDiagnosticOriginClang, and lldb_private::Diagnostic::getKind().
FixIts()
const FixItList & lldb_private::ClangDiagnostic::FixIts () const inline
Definition at line 43 of file ClangDiagnostic.h.
References m_fixit_vec.
HasFixIts()
bool lldb_private::ClangDiagnostic::HasFixIts () const inline override virtual
Reimplemented from lldb_private::Diagnostic.
Definition at line 37 of file ClangDiagnostic.h.
References m_fixit_vec.
Member Data Documentation
m_fixit_vec
FixItList lldb_private::ClangDiagnostic::m_fixit_vec private
Definition at line 45 of file ClangDiagnostic.h.
Referenced by AddFixitHint(), FixIts(), and HasFixIts().
The documentation for this class was generated from the following file:
ClangDiagnostic.h