LLDB: ExceptionBreakpointResolver Class Reference
ExceptionBreakpointResolver Class Reference
Public Member Functions
ExceptionBreakpointResolver (lldb::LanguageType language, bool catch_bp, bool throw_bp)
~ExceptionBreakpointResolver () override=default
Searcher::CallbackReturn SearchCallback (SearchFilter &filter, SymbolContext &context, Address *addr) override
lldb::SearchDepth GetDepth () override
void GetDescription (Stream *s) override
Prints a canonical description for the breakpoint to the stream s.
void Dump (Stream *s) const override
Standard "Dump" method. At present it does nothing.
Public Member Functions inherited from lldb_private::BreakpointResolver
BreakpointResolver (const lldb::BreakpointSP &bkpt, unsigned char resolverType, lldb::addr_t offset=0, bool offset_is_insn_count=false)
The breakpoint resolver need to have a breakpoint for "ResolveBreakpoint to make sense.
~BreakpointResolver () override
The Destructor is virtual, all significant breakpoint resolvers derive from this class.
void SetBreakpoint (const lldb::BreakpointSP &bkpt)
This sets the breakpoint for this resolver.
lldb::BreakpointSP GetBreakpoint () const
This gets the breakpoint for this resolver.
void SetOffset (lldb::addr_t offset)
This updates the offset for this breakpoint.
lldb::addr_t GetOffset () const
lldb::addr_t GetOffsetIsInsnCount () const
virtual void ResolveBreakpoint (SearchFilter &filter)
In response to this method the resolver scans all the modules in the breakpoint's target, and adds any new locations it finds.
virtual void ResolveBreakpointInModules (SearchFilter &filter, ModuleList &modules)
In response to this method the resolver scans the modules in the module list modules, and adds any new locations it finds.
virtual StructuredData::ObjectSP SerializeToStructuredData ()
StructuredData::DictionarySP WrapOptionsDict (StructuredData::DictionarySP options_dict_sp)
unsigned getResolverID () const
getResolverID - Return an ID for the concrete type of this object.
enum ResolverTy GetResolverTy ()
const char * GetResolverName ()
Public Member Functions inherited from lldb_private::Searcher
Searcher ()
virtual ~Searcher ()
Static Public Member Functions
static bool classof (const BreakpointResolverName *)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const BreakpointResolver *V)
Static Public Member Functions inherited from lldb_private::BreakpointResolver
static lldb::BreakpointResolverSP CreateFromStructuredData (const StructuredData::Dictionary &resolver_dict, Status &error)
This section handles serializing and deserializing from StructuredData objects.
static const char * GetSerializationKey ()
static const char * GetSerializationSubclassKey ()
static const char * GetSerializationSubclassOptionsKey ()
static const char * ResolverTyToName (enum ResolverTy)
static ResolverTy NameToResolverTy (llvm::StringRef name)
static const char * GetKey (OptionNames enum_value)
Protected Member Functions
BreakpointResolverSP CopyForBreakpoint (BreakpointSP &breakpoint) override
bool SetActualResolver ()
Protected Member Functions inherited from lldb_private::BreakpointResolver
virtual void NotifyBreakpointSet ()
void SetSCMatchesByLine (SearchFilter &filter, SymbolContextList &sc_list, bool skip_prologue, llvm::StringRef log_ident, uint32_t line=0, std::optional< uint16_t > column=std::nullopt)
Takes a symbol context list of matches which supposedly represent the same file and line number in a CU, and find the nearest actual line number that matches, and then filter down the matching addresses to unique entries, and skip the prologue if asked to do so, and then set breakpoint locations in this breakpoint for all the resultant addresses.
void SetSCMatchesByLine (SearchFilter &, SymbolContextList &, bool, const char *)=delete
lldb::BreakpointLocationSP AddLocation (Address loc_addr, bool *new_location=nullptr)
Protected Attributes
lldb::BreakpointResolverSP m_actual_resolver_sp
lldb::LanguageType m_language
LanguageRuntime * m_language_runtime = nullptr
bool m_catch_bp
bool m_throw_bp
Additional Inherited Members
Public Types inherited from lldb_private::BreakpointResolver
enum ResolverTy {
FileLineResolver = 0 , AddressResolver , NameResolver , FileRegexResolver ,
PythonResolver , ExceptionResolver , LastKnownResolverType = ExceptionResolver , UnknownResolver
}
An enumeration for keeping track of the concrete subclass that is actually instantiated.
Public Types inherited from lldb_private::Searcher
enum CallbackReturn { eCallbackReturnStop = 0 , eCallbackReturnContinue , eCallbackReturnPop }
Static Public Attributes inherited from lldb_private::BreakpointResolver
static const char * g_ty_to_name [LastKnownResolverType+2]
Protected Types inherited from lldb_private::BreakpointResolver
enum class OptionNames : uint32_t {
AddressOffset = 0 , ExactMatch , FileName , Inlines ,
LanguageName , LineNumber , Column , ModuleName ,
NameMaskArray , Offset , PythonClassName , RegexString ,
ScriptArgs , SectionName , SearchDepth , SkipPrologue ,
SymbolNameArray , LastOptionName
}
Static Protected Attributes inherited from lldb_private::BreakpointResolver
static const char * g_option_names [static_cast< uint32_t >(OptionNames::LastOptionName)]
Detailed Description
Definition at line 102 of file LanguageRuntime.cpp.
Constructor & Destructor Documentation
ExceptionBreakpointResolver()
ExceptionBreakpointResolver::ExceptionBreakpointResolver (lldb::LanguageType language, bool catch_bp, bool throw_bp) inline
Definition at line 104 of file LanguageRuntime.cpp.
References lldb_private::BreakpointResolver::BreakpointResolver(), lldb_private::BreakpointResolver::ExceptionResolver, m_catch_bp, m_language, and m_throw_bp.
Referenced by CopyForBreakpoint().
~ExceptionBreakpointResolver()
ExceptionBreakpointResolver::~ExceptionBreakpointResolver () override default
Member Function Documentation
classof() [1/2]
bool ExceptionBreakpointResolver::classof (const BreakpointResolver * V) inline static
Definition at line 150 of file LanguageRuntime.cpp.
References lldb_private::BreakpointResolver::BreakpointResolver(), lldb_private::BreakpointResolver::ExceptionResolver, and lldb_private::BreakpointResolver::getResolverID().
classof() [2/2]
bool ExceptionBreakpointResolver::classof (const BreakpointResolverName *) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 149 of file LanguageRuntime.cpp.
CopyForBreakpoint()
BreakpointResolverSP ExceptionBreakpointResolver::CopyForBreakpoint (BreakpointSP & breakpoint) inline override protected virtual
Implements lldb_private::BreakpointResolver.
Definition at line 155 of file LanguageRuntime.cpp.
References ExceptionBreakpointResolver(), m_catch_bp, m_language, and m_throw_bp.
Dump()
void ExceptionBreakpointResolver::Dump (Stream * s) const inline override virtual
Standard "Dump" method. At present it does nothing.
Implements lldb_private::BreakpointResolver.
Definition at line 146 of file LanguageRuntime.cpp.
GetDepth()
lldb::SearchDepth ExceptionBreakpointResolver::GetDepth () inline override virtual
Implements lldb_private::Searcher.
Definition at line 121 of file LanguageRuntime.cpp.
References lldb::eSearchDepthTarget, m_actual_resolver_sp, and SetActualResolver().
GetDescription()
void ExceptionBreakpointResolver::GetDescription (Stream * s) inline override virtual
Prints a canonical description for the breakpoint to the stream s.
Parameters
[in] s Stream to which the output is copied.
Implements lldb_private::BreakpointResolver.
Definition at line 128 of file LanguageRuntime.cpp.
References lldb_private::Language::FindPlugin(), lldb_private::Language::GetDefaultExceptionResolverDescription(), lldb_private::Language::GetExceptionResolverDescription(), m_actual_resolver_sp, m_catch_bp, m_language, m_throw_bp, lldb_private::Stream::Printf(), and SetActualResolver().
SearchCallback()
Searcher::CallbackReturn ExceptionBreakpointResolver::SearchCallback (SearchFilter & filter, SymbolContext & context, Address * addr) inline override virtual
Implements lldb_private::Searcher.
Definition at line 111 of file LanguageRuntime.cpp.
References lldb_private::Searcher::eCallbackReturnStop, m_actual_resolver_sp, and SetActualResolver().
SetActualResolver()
bool ExceptionBreakpointResolver::SetActualResolver () inline protected
Definition at line 162 of file LanguageRuntime.cpp.
References lldb_private::BreakpointResolver::GetBreakpoint(), m_actual_resolver_sp, m_catch_bp, m_language, m_language_runtime, and m_throw_bp.
Referenced by GetDepth(), GetDescription(), and SearchCallback().
Member Data Documentation
m_actual_resolver_sp
lldb::BreakpointResolverSP ExceptionBreakpointResolver::m_actual_resolver_sp protected
Definition at line 195 of file LanguageRuntime.cpp.
Referenced by GetDepth(), GetDescription(), SearchCallback(), and SetActualResolver().
m_catch_bp
bool ExceptionBreakpointResolver::m_catch_bp protected
Definition at line 198 of file LanguageRuntime.cpp.
Referenced by CopyForBreakpoint(), ExceptionBreakpointResolver(), GetDescription(), and SetActualResolver().
m_language
lldb::LanguageType ExceptionBreakpointResolver::m_language protected
Definition at line 196 of file LanguageRuntime.cpp.
Referenced by CopyForBreakpoint(), ExceptionBreakpointResolver(), GetDescription(), and SetActualResolver().
m_language_runtime
LanguageRuntime* ExceptionBreakpointResolver::m_language_runtime = nullptr protected
Definition at line 197 of file LanguageRuntime.cpp.
Referenced by SetActualResolver().
m_throw_bp
bool ExceptionBreakpointResolver::m_throw_bp protected
Definition at line 199 of file LanguageRuntime.cpp.
Referenced by CopyForBreakpoint(), ExceptionBreakpointResolver(), GetDescription(), and SetActualResolver().
The documentation for this class was generated from the following file:
LanguageRuntime.cpp