LLDB: lldb_private::LanguageCategory Class Reference
lldb_private::LanguageCategory Class Reference
#include <LanguageCategory.h>
Public Types
typedef std::unique_ptr< LanguageCategory > UniquePointer
Public Member Functions
LanguageCategory (lldb::LanguageType lang_type)
template<typename ImplSP>
bool Get (FormattersMatchData &match_data, ImplSP &format_sp)
template<typename ImplSP>
bool GetHardcoded (FormatManager &fmt_mgr, FormattersMatchData &match_data, ImplSP &format_sp)
lldb::TypeCategoryImplSP GetCategory () const
FormatCache & GetFormatCache ()
void Enable ()
void Disable ()
bool IsEnabled ()
Private Member Functions
template<typename ImplSP>
auto & GetHardcodedFinder ()
Private Attributes
lldb::TypeCategoryImplSP m_category_sp
HardcodedFormatters::HardcodedFormatFinder m_hardcoded_formats
HardcodedFormatters::HardcodedSummaryFinder m_hardcoded_summaries
HardcodedFormatters::HardcodedSyntheticFinder m_hardcoded_synthetics
lldb_private::FormatCache m_format_cache
bool m_enabled
Detailed Description
Definition at line 21 of file LanguageCategory.h.
Member Typedef Documentation
UniquePointer
typedef std::unique_ptr<LanguageCategory> lldb_private::LanguageCategory::UniquePointer
Definition at line 23 of file LanguageCategory.h.
Constructor & Destructor Documentation
LanguageCategory()
LanguageCategory::LanguageCategory (lldb::LanguageType lang_type)
Definition at line 21 of file LanguageCategory.cpp.
References Enable(), lldb_private::Language::FindPlugin(), m_category_sp, m_enabled, m_format_cache, m_hardcoded_formats, m_hardcoded_summaries, and m_hardcoded_synthetics.
Member Function Documentation
Disable()
void LanguageCategory::Disable ()
Definition at line 130 of file LanguageCategory.cpp.
References m_category_sp, and m_enabled.
Enable()
void LanguageCategory::Enable ()
Definition at line 124 of file LanguageCategory.cpp.
References lldb_private::TypeCategoryMap::Default, m_category_sp, and m_enabled.
Referenced by LanguageCategory().
Get()
template<typename ImplSP> bool LanguageCategory::Get (FormattersMatchData & match_data, ImplSP & format_sp)
Definition at line 34 of file LanguageCategory.cpp.
References lldb_private::FormattersMatchData::GetMatchesVector(), lldb_private::ValueObject::GetObjectRuntimeLanguage(), lldb_private::FormattersMatchData::GetTypeForCache(), lldb_private::FormattersMatchData::GetValueObject(), IsEnabled(), m_category_sp, and m_format_cache.
Referenced by lldb_private::LanguageCategory::Get< lldb::SyntheticChildrenSP >(), lldb_private::LanguageCategory::Get< lldb::TypeFormatImplSP >(), and lldb_private::LanguageCategory::Get< lldb::TypeSummaryImplSP >().
GetCategory()
lldb::TypeCategoryImplSP LanguageCategory::GetCategory () const
Definition at line 118 of file LanguageCategory.cpp.
References m_category_sp.
GetFormatCache()
FormatCache & LanguageCategory::GetFormatCache ()
Definition at line 122 of file LanguageCategory.cpp.
References m_format_cache.
GetHardcoded()
template<typename ImplSP> bool LanguageCategory::GetHardcoded (FormatManager & fmt_mgr, FormattersMatchData & match_data, ImplSP & format_sp)
Definition at line 90 of file LanguageCategory.cpp.
References lldb_private::FormattersMatchData::GetDynamicValueType(), GetHardcodedFinder(), lldb_private::FormattersMatchData::GetValueObject(), and IsEnabled().
Referenced by LanguageCategory::GetHardcoded< lldb::SyntheticChildrenSP >(), LanguageCategory::GetHardcoded< lldb::TypeFormatImplSP >(), and LanguageCategory::GetHardcoded< lldb::TypeSummaryImplSP >().
GetHardcodedFinder()
template<typename ImplSP> auto & lldb_private::LanguageCategory::GetHardcodedFinder () private
Referenced by GetHardcoded(), lldb_private::LanguageCategory::GetHardcodedFinder< lldb::SyntheticChildrenSP >(), lldb_private::LanguageCategory::GetHardcodedFinder< lldb::TypeFormatImplSP >(), and lldb_private::LanguageCategory::GetHardcodedFinder< lldb::TypeSummaryImplSP >().
IsEnabled()
bool LanguageCategory::IsEnabled ()
Definition at line 136 of file LanguageCategory.cpp.
References m_enabled.
Referenced by Get(), and GetHardcoded().
Member Data Documentation
m_category_sp
lldb::TypeCategoryImplSP lldb_private::LanguageCategory::m_category_sp private
Definition at line 44 of file LanguageCategory.h.
Referenced by Disable(), Enable(), Get(), GetCategory(), and LanguageCategory().
m_enabled
bool lldb_private::LanguageCategory::m_enabled private
Definition at line 55 of file LanguageCategory.h.
Referenced by Disable(), Enable(), IsEnabled(), and LanguageCategory().
m_format_cache
lldb_private::FormatCache lldb_private::LanguageCategory::m_format_cache private
Definition at line 53 of file LanguageCategory.h.
Referenced by Get(), GetFormatCache(), and LanguageCategory().
m_hardcoded_formats
HardcodedFormatters::HardcodedFormatFinder lldb_private::LanguageCategory::m_hardcoded_formats private
Definition at line 46 of file LanguageCategory.h.
Referenced by LanguageCategory().
m_hardcoded_summaries
HardcodedFormatters::HardcodedSummaryFinder lldb_private::LanguageCategory::m_hardcoded_summaries private
Definition at line 47 of file LanguageCategory.h.
Referenced by LanguageCategory().
m_hardcoded_synthetics
HardcodedFormatters::HardcodedSyntheticFinder lldb_private::LanguageCategory::m_hardcoded_synthetics private
Definition at line 48 of file LanguageCategory.h.
Referenced by LanguageCategory().
The documentation for this class was generated from the following files:
LanguageCategory.h
LanguageCategory.cpp