LLDB: lldb_private::ObjectFileJSON Class Reference
lldb_private::ObjectFileJSON Class Reference
#include <ObjectFileJSON.h>
Classes
struct Body
struct Header
Public Member Functions
llvm::StringRef GetPluginName () override
bool isA (const void *ClassID) const override
bool ParseHeader () override
Attempts to parse the object header.
lldb::ByteOrder GetByteOrder () const override
Gets whether endian swapping should occur when extracting data from this object file.
bool IsExecutable () const override
Tells whether this object file is capable of being the main executable for a process.
uint32_t GetAddressByteSize () const override
Gets the address size in bytes for the current object file.
AddressClass GetAddressClass (lldb::addr_t file_addr) override
Get the address type given a file address in an object file.
void ParseSymtab (lldb_private::Symtab &symtab) override
Parse the symbol table into the provides symbol table object.
bool IsStripped () override
Detect if this object file has been stripped of local symbols.
void CreateSections (SectionList &unified_section_list) override
void Dump (Stream *s) override
Dump a description of this object to a Stream.
ArchSpec GetArchitecture () override
Get the ArchSpec for this object file.
UUID GetUUID () override
Gets the UUID for this object file.
uint32_t GetDependentModules (FileSpecList &files) override
Extract the dependent modules from an object file.
Type CalculateType () override
The object file should be able to calculate its type by looking at its file header and possibly the sections or other data in the object file.
Strata CalculateStrata () override
The object file should be able to calculate the strata of the object file.
bool SetLoadAddress (Target &target, lldb::addr_t value, bool value_is_offset) override
Sets the load address for an entire module, assuming a rigid slide of sections, if possible in the implementation.
Public Member Functions inherited from lldb_private::ObjectFile
ObjectFile (const lldb::ModuleSP &module_sp, const FileSpec *file_spec_ptr, lldb::offset_t file_offset, lldb::offset_t length, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset)
Construct with a parent module, offset, and header data.
ObjectFile (const lldb::ModuleSP &module_sp, const lldb::ProcessSP &process_sp, lldb::addr_t header_addr, lldb::DataExtractorSP extractor_sp)
~ObjectFile () override
Destructor.
virtual lldb::addr_t GetFileOffset () const
Returns the offset into a file at which this object resides.
virtual lldb::addr_t GetByteSize () const
virtual FileSpec & GetFileSpec ()
Get accessor to the object file specification.
virtual const FileSpec & GetFileSpec () const
Get const accessor to the object file specification.
virtual SectionList * GetSectionList (bool update_module_section_list=true)
Gets the section list for the currently selected architecture (and object for archives).
virtual void SectionFileAddressesChanged ()
Notify the ObjectFile that the file addresses in the Sections for this module have been changed.
Symtab * GetSymtab (bool can_create=true)
Gets the symbol table for the currently selected architecture (and object for archives).
virtual void RelocateSection (lldb_private::Section *section)
Perform relocations on the section if necessary.
virtual void ClearSymtab ()
Frees the symbol table.
virtual lldb_private::FileSpecList GetReExportedLibraries ()
Gets the file spec list of libraries re-exported by this object file.
virtual bool AllowAssemblyEmulationUnwindPlans ()
Returns if the function bounds for symbols in this symbol file are likely accurate.
virtual lldb_private::Address GetImageInfoAddress (Target *target)
Similar to Process::GetImageInfoAddress().
virtual lldb_private::Address GetEntryPointAddress ()
Returns the address of the Entry Point in this object file - if the object file doesn't have an entry point (because it is not an executable file) then an invalid address is returned.
virtual lldb_private::Address GetBaseAddress ()
Returns base address of this object file.
virtual uint32_t GetNumThreadContexts ()
virtual std::string GetIdentifierString ()
Some object files may have an identifier string embedded in them, e.g.
virtual lldb_private::AddressableBits GetAddressableBits ()
Some object files may have the number of bits used for addressing embedded in them, e.g.
virtual bool GetCorefileMainBinaryInfo (lldb::addr_t &value, bool &value_is_offset, UUID &uuid, ObjectFile::BinaryType &type)
When the ObjectFile is a core file, lldb needs to locate the "binary" in the core file.
virtual bool GetCorefileThreadExtraInfos (std::vector< lldb::tid_t > &tids)
Get metadata about thread ids from the corefile.
virtual StructuredData::ObjectSP GetCorefileProcessMetadata ()
Get process metadata from the corefile in a StructuredData dictionary.
virtual lldb::RegisterContextSP GetThreadContextAtIndex (uint32_t idx, lldb_private::Thread &thread)
virtual void SetType (Type type)
In cases where the type can't be calculated (elf files), this routine allows someone to explicitly set it.
virtual llvm::VersionTuple GetVersion ()
Get the object file version numbers.
virtual llvm::VersionTuple GetMinimumOSVersion ()
Get the minimum OS version this object file can run on.
virtual llvm::VersionTuple GetSDKVersion ()
Get the SDK OS version this object file was built with.
virtual bool GetIsDynamicLinkEditor ()
Return true if this file is a dynamic link editor (dyld)
Type GetType ()
Strata GetStrata ()
size_t GetData (lldb::offset_t offset, size_t length, lldb::DataExtractorSP &data_sp) const
size_t CopyData (lldb::offset_t offset, size_t length, void *dst) const
virtual size_t ReadSectionData (Section *section, lldb::offset_t section_offset, void *dst, size_t dst_len)
virtual size_t ReadSectionData (Section *section, DataExtractor &section_data)
virtual size_t GetSectionDataSize (Section *section)
bool IsInMemory () const
Returns true if the object file exists only in memory.
virtual llvm::StringRef StripLinkerSymbolAnnotations (llvm::StringRef symbol_name) const
virtual bool CanTrustAddressRanges ()
Can we trust the address ranges accelerator associated with this object file to be complete.
virtual std::vector< LoadableData > GetLoadableData (Target &target)
Loads this objfile to memory.
virtual std::unique_ptr< CallFrameInfo > CreateCallFrameInfo ()
Creates a plugin-specific call frame info.
virtual bool LoadCoreFileImages (lldb_private::Process &process)
Load binaries listed in a corefile.
virtual bool IsGOTSection (const lldb_private::Section &section) const
Returns true if the section is a global offset table section.
uint32_t GetCacheHash ()
Get a hash that can be used for caching object file releated information.
std::string GetObjectName () const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Public Member Functions inherited from lldb_private::ModuleChild
ModuleChild (const lldb::ModuleSP &module_sp)
Construct with owning module.
~ModuleChild ()
Destructor.
const ModuleChild & operator= (const ModuleChild &rhs)
Assignment operator.
lldb::ModuleSP GetModule () const
Get const accessor for the module pointer.
void SetModule (const lldb::ModuleSP &module_sp)
Set accessor for the module pointer.
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static const char * GetPluginDescriptionStatic ()
static ObjectFile * CreateInstance (const lldb::ModuleSP &module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const FileSpec *file, lldb::offset_t file_offset, lldb::offset_t length)
static ObjectFile * CreateMemoryInstance (const lldb::ModuleSP &module_sp, lldb::WritableDataBufferSP data_sp, const lldb::ProcessSP &process_sp, lldb::addr_t header_addr)
static size_t GetModuleSpecifications (const FileSpec &file, lldb::DataExtractorSP &extractor_sp, lldb::offset_t data_offset, lldb::offset_t file_offset, lldb::offset_t length, ModuleSpecList &specs)
static bool classof (const ObjectFile *obj)
static bool MagicBytesMatch (lldb::DataExtractorSP extractor_sp)
Static Public Member Functions inherited from lldb_private::ObjectFile
static lldb::ObjectFileSP FindPlugin (const lldb::ModuleSP &module_sp, const FileSpec *file_spec, lldb::offset_t file_offset, lldb::offset_t file_size, lldb::DataExtractorSP extractor_sp, lldb::offset_t &data_offset)
Find a ObjectFile plug-in that can parse file_spec.
static lldb::ObjectFileSP FindPlugin (const lldb::ModuleSP &module_sp, const lldb::ProcessSP &process_sp, lldb::addr_t header_addr, lldb::WritableDataBufferSP file_data_sp)
Find a ObjectFile plug-in that can parse a file in memory.
static size_t GetModuleSpecifications (const FileSpec &file, lldb::offset_t file_offset, lldb::offset_t file_size, ModuleSpecList &specs, lldb::DataExtractorSP=lldb::DataExtractorSP())
static size_t GetModuleSpecifications (const lldb_private::FileSpec &file, lldb::DataExtractorSP &extractor_sp, lldb::offset_t data_offset, lldb::offset_t file_offset, lldb::offset_t file_size, lldb_private::ModuleSpecList &specs)
static bool IsObjectFile (lldb_private::FileSpec file_spec)
static bool SplitArchivePathWithObject (llvm::StringRef path_with_object, lldb_private::FileSpec &archive_file, lldb_private::ConstString &archive_object, bool must_exist)
Split a path into a file path with object name.
static lldb::WritableDataBufferSP ReadMemory (const lldb::ProcessSP &process_sp, lldb::addr_t addr, size_t byte_size)
static lldb::SymbolType GetSymbolTypeFromName (llvm::StringRef name, lldb::SymbolType symbol_type_hint=lldb::eSymbolTypeUndefined)
static lldb::SectionType GetDWARFSectionTypeFromName (llvm::StringRef name)
Parses the section type from a section name for DWARF sections.
static lldb::DataBufferSP MapFileData (const FileSpec &file, uint64_t Size, uint64_t Offset)
Static Public Attributes
static char ID
Static Public Attributes inherited from lldb_private::ObjectFile
static char ID
Private Member Functions
ObjectFileJSON (const lldb::ModuleSP &module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const FileSpec *file, lldb::offset_t offset, lldb::offset_t length, ArchSpec arch, UUID uuid, Type type, std::vector< JSONSymbol > symbols, std::vector< JSONSection > sections)
Private Attributes
ArchSpec m_arch
UUID m_uuid
ObjectFile::Type m_type
std::optional< uint64_t > m_size
std::vector< JSONSymbol > m_symbols
std::vector< JSONSection > m_sections
Additional Inherited Members
Public Types inherited from lldb_private::ObjectFile
enum Type {
eTypeInvalid = 0 , eTypeCoreFile , eTypeExecutable , eTypeDebugInfo ,
eTypeDynamicLinker , eTypeObjectFile , eTypeSharedLibrary , eTypeStubLibrary ,
eTypeJIT , eTypeUnknown
}
enum Strata {
eStrataInvalid = 0 , eStrataUnknown , eStrataUser , eStrataKernel ,
eStrataRawImage , eStrataJIT
}
enum BinaryType {
eBinaryTypeInvalid = 0 , eBinaryTypeUnknown , eBinaryTypeKernel , eBinaryTypeUser ,
eBinaryTypeUserAllImageInfos , eBinaryTypeStandalone
}
If we have a corefile binary hint, this enum specifies the binary type which we can use to select the correct DynamicLoader plugin.
Protected Types inherited from lldb_private::ObjectFile
typedef NonNullSharedPtr< lldb_private::DataExtractor > DataExtractorNSP
Protected Member Functions inherited from lldb_private::ObjectFile
bool SetModulesArchitecture (const ArchSpec &new_arch)
Sets the architecture for a module.
Protected Attributes inherited from lldb_private::ObjectFile
FileSpec m_file
Type m_type
Strata m_strata
lldb::addr_t m_file_offset
The offset in bytes into the file, or the address in memory.
lldb::addr_t m_length
The length of this object file if it is known (can be zero if length is unknown or can't be determined).
DataExtractorNSP m_data_nsp
The data for this object file so things can be parsed lazily.
lldb::ProcessWP m_process_wp
const lldb::addr_t m_memory_addr
Set if the object file only exists in memory.
std::unique_ptr< lldb_private::SectionList > m_sections_up
std::unique_ptr< lldb_private::Symtab > m_symtab_up
std::unique_ptr< llvm::once_flag > m_symtab_once_up
We need a llvm::once_flag that we can use to avoid locking the module lock and deadlocking LLDB.
std::optional< uint32_t > m_cache_hash
Protected Attributes inherited from lldb_private::ModuleChild
lldb::ModuleWP m_module_wp
The Module that owns the object that inherits from this class.
Static Protected Attributes inherited from lldb_private::ObjectFile
static size_t g_initial_bytes_to_read = 512
The number of bytes to read when going through the plugins.
Detailed Description
Definition at line 18 of file ObjectFileJSON.h.
Constructor & Destructor Documentation
ObjectFileJSON()
ObjectFileJSON::ObjectFileJSON (const lldb::ModuleSP & module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const FileSpec * file, lldb::offset_t offset, lldb::offset_t length, ArchSpec arch, UUID uuid, Type type, std::vector< JSONSymbol > symbols, std::vector< JSONSection > sections) private
Definition at line 156 of file ObjectFileJSON.cpp.
References m_arch, m_sections, m_symbols, m_type, m_uuid, and lldb_private::ObjectFile::ObjectFile().
Referenced by CreateInstance().
Member Function Documentation
CalculateStrata()
Strata lldb_private::ObjectFileJSON::CalculateStrata () inline override virtual
The object file should be able to calculate the strata of the object file.
Many object files for platforms might be for either user space debugging or for kernel debugging. If your object file subclass can figure this out, it will help with debugger plug-in selection when it comes time to debug.
Returns
The calculated object file strata for the current object file.
Implements lldb_private::ObjectFile.
Definition at line 89 of file ObjectFileJSON.h.
References lldb_private::ObjectFile::eStrataUser.
CalculateType()
Type lldb_private::ObjectFileJSON::CalculateType () inline override virtual
The object file should be able to calculate its type by looking at its file header and possibly the sections or other data in the object file.
The file type is used in the debugger to help select the correct plug- ins for the job at hand, so this is important to get right. If any eTypeXXX definitions do not match up with the type of file you are loading, please feel free to add a new enumeration value.
Returns
The calculated file type for the current object file.
Implements lldb_private::ObjectFile.
Definition at line 87 of file ObjectFileJSON.h.
References m_type.
classof()
bool lldb_private::ObjectFileJSON::classof (const ObjectFile * obj) inline static
Definition at line 55 of file ObjectFileJSON.h.
References ID, lldb_private::ObjectFile::isA(), and lldb_private::ObjectFile::ObjectFile().
CreateInstance()
ObjectFile * ObjectFileJSON::CreateInstance (const lldb::ModuleSP & module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const FileSpec * file, lldb::offset_t file_offset, lldb::offset_t length) static
Definition at line 39 of file ObjectFileJSON.cpp.
References lldb_private::ObjectFile::eTypeDebugInfo, lldb_private::fromJSON(), lldb_private::GetLog(), LLDB_LOG_ERROR, MagicBytesMatch(), lldb_private::ObjectFile::MapFileData(), lldb_private::ObjectFile::ObjectFile(), ObjectFileJSON(), lldb_private::ObjectFileJSON::Body::sections, lldb_private::UUID::SetFromStringRef(), lldb_private::Symbols, lldb_private::ObjectFileJSON::Body::symbols, lldb_private::ObjectFileJSON::Header::triple, lldb_private::ObjectFileJSON::Header::type, and lldb_private::ObjectFileJSON::Header::uuid.
Referenced by Initialize(), and Terminate().
CreateMemoryInstance()
ObjectFile * ObjectFileJSON::CreateMemoryInstance (const lldb::ModuleSP & module_sp, lldb::WritableDataBufferSP data_sp, const lldb::ProcessSP & process_sp, lldb::addr_t header_addr) static
Definition at line 104 of file ObjectFileJSON.cpp.
References lldb_private::ObjectFile::ObjectFile().
Referenced by Initialize().
CreateSections()
void ObjectFileJSON::CreateSections (SectionList & unified_section_list) override virtual
Implements lldb_private::ObjectFile.
Definition at line 186 of file ObjectFileJSON.cpp.
References lldb_private::JSONSection::address, lldb_private::SectionList::AddSection(), lldb_private::JSONSection::encrypted, lldb::eSectionTypeCode, lldb_private::JSONSection::execute, lldb_private::JSONSection::fake, lldb_private::JSONSection::file_offset, lldb_private::JSONSection::file_size, lldb_private::JSONSection::flags, lldb_private::ModuleChild::GetModule(), lldb_private::JSONSection::log2align, m_sections, lldb_private::ObjectFile::m_sections_up, lldb_private::JSONSection::name, lldb_private::JSONSection::read, lldb_private::JSONSection::size, lldb_private::JSONSection::thread_specific, lldb_private::JSONSection::type, lldb_private::JSONSection::user_id, and lldb_private::JSONSection::write.
Dump()
void lldb_private::ObjectFileJSON::Dump (Stream * s) inline override virtual
Dump a description of this object to a Stream.
Dump a description of the current contents of this object to the supplied stream s. The dumping should include the section list if it has been parsed, and the symbol table if it has been parsed.
Parameters
[in] s The stream to which to dump the object description.
Implements lldb_private::ObjectFile.
Definition at line 79 of file ObjectFileJSON.h.
GetAddressByteSize()
uint32_t lldb_private::ObjectFileJSON::GetAddressByteSize () const inline override virtual
Gets the address size in bytes for the current object file.
Returns
The size of an address in bytes for the currently selected architecture (and object for archives). Returns zero if no architecture or object has been selected.
Implements lldb_private::ObjectFile.
Definition at line 65 of file ObjectFileJSON.h.
References m_arch.
GetAddressClass()
AddressClass lldb_private::ObjectFileJSON::GetAddressClass (lldb::addr_t file_addr) inline override virtual
Get the address type given a file address in an object file.
Many binary file formats know what kinds This is primarily for ARM binaries, though it can be applied to any executable file format that supports different opcode types within the same binary. ARM binaries support having both ARM and Thumb within the same executable container. We need to be able to get
Returns
The size of an address in bytes for the currently selected architecture (and object for archives). Returns zero if no architecture or object has been selected.
Reimplemented from lldb_private::ObjectFile.
Definition at line 69 of file ObjectFileJSON.h.
References lldb_private::eInvalid.
GetArchitecture()
ArchSpec lldb_private::ObjectFileJSON::GetArchitecture () inline override virtual
Get the ArchSpec for this object file.
Returns
The ArchSpec of this object file. In case of error, an invalid ArchSpec object is returned.
Implements lldb_private::ObjectFile.
Definition at line 81 of file ObjectFileJSON.h.
References m_arch.
GetByteOrder()
lldb::ByteOrder lldb_private::ObjectFileJSON::GetByteOrder () const inline override virtual
Gets whether endian swapping should occur when extracting data from this object file.
Returns
Returns true if endian swapping is needed, false otherwise.
Implements lldb_private::ObjectFile.
Definition at line 59 of file ObjectFileJSON.h.
References m_arch.
GetDependentModules()
uint32_t lldb_private::ObjectFileJSON::GetDependentModules (FileSpecList & file_list) inline override virtual
Extract the dependent modules from an object file.
If an object file has information about which other images it depends on (such as shared libraries), this function will provide the list. Since many executables or shared libraries may depend on the same files, FileSpecList::AppendIfUnique(const FileSpec &) should be used to make sure any files that are added are not already in the list.
Parameters
[out] file_list A list of file specification objects that gets dependent files appended to.
Returns
The number of new files that were appended to file_list.
See also
FileSpecList::AppendIfUnique(const FileSpec &)
Implements lldb_private::ObjectFile.
Definition at line 85 of file ObjectFileJSON.h.
GetModuleSpecifications()
size_t ObjectFileJSON::GetModuleSpecifications (const FileSpec & file, lldb::DataExtractorSP & extractor_sp, lldb::offset_t data_offset, lldb::offset_t file_offset, lldb::offset_t length, ModuleSpecList & specs) static
Definition at line 111 of file ObjectFileJSON.cpp.
References lldb_private::ModuleSpecList::Append(), lldb_private::fromJSON(), lldb_private::GetLog(), lldb_private::ModuleSpec::GetUUID(), LLDB_LOG_ERROR, MagicBytesMatch(), lldb_private::ObjectFile::MapFileData(), lldb_private::UUID::SetFromStringRef(), lldb_private::Symbols, lldb_private::ObjectFileJSON::Header::triple, and lldb_private::ObjectFileJSON::Header::uuid.
Referenced by Initialize().
GetPluginDescriptionStatic()
const char * lldb_private::ObjectFileJSON::GetPluginDescriptionStatic () inline static
Definition at line 25 of file ObjectFileJSON.h.
Referenced by Initialize().
GetPluginName()
llvm::StringRef lldb_private::ObjectFileJSON::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 48 of file ObjectFileJSON.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef lldb_private::ObjectFileJSON::GetPluginNameStatic () inline static
Definition at line 23 of file ObjectFileJSON.h.
Referenced by GetPluginName(), and Initialize().
GetUUID()
UUID lldb_private::ObjectFileJSON::GetUUID () inline override virtual
Gets the UUID for this object file.
If the object file format contains a UUID, the value should be returned. Else ObjectFile instances should return the MD5 checksum of all of the bytes for the object file (or memory for memory based object files).
Returns
The object file's UUID. In case of an error, an empty UUID is returned.
Implements lldb_private::ObjectFile.
Definition at line 83 of file ObjectFileJSON.h.
References m_uuid.
Initialize()
void ObjectFileJSON::Initialize () static
Definition at line 29 of file ObjectFileJSON.cpp.
References CreateInstance(), CreateMemoryInstance(), GetModuleSpecifications(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
isA()
bool lldb_private::ObjectFileJSON::isA (const void * ClassID) const inline override virtual
Reimplemented from lldb_private::ObjectFile.
Definition at line 52 of file ObjectFileJSON.h.
References ID, and lldb_private::ObjectFile::isA().
IsExecutable()
bool lldb_private::ObjectFileJSON::IsExecutable () const inline override virtual
Tells whether this object file is capable of being the main executable for a process.
Returns
true if it is, false otherwise.
Implements lldb_private::ObjectFile.
Definition at line 63 of file ObjectFileJSON.h.
IsStripped()
bool lldb_private::ObjectFileJSON::IsStripped () inline override virtual
Detect if this object file has been stripped of local symbols.
Detect if this object file has been stripped of local symbols.
Returns
Return true if the object file has been stripped of local symbols.
Implements lldb_private::ObjectFile.
Definition at line 75 of file ObjectFileJSON.h.
MagicBytesMatch()
bool ObjectFileJSON::MagicBytesMatch (lldb::DataExtractorSP extractor_sp) static
Definition at line 279 of file ObjectFileJSON.cpp.
Referenced by CreateInstance(), and GetModuleSpecifications().
ParseHeader()
bool ObjectFileJSON::ParseHeader () override virtual
Attempts to parse the object header.
This function is used as a test to see if a given plug-in instance can parse the header data already contained in ObjectFile::m_data_nsp. If an object file parser does not recognize that magic bytes in a header, false should be returned and the next plug-in can attempt to parse an object file.
Returns
Returns true if the header was parsed successfully, false otherwise.
Implements lldb_private::ObjectFile.
Definition at line 167 of file ObjectFileJSON.cpp.
ParseSymtab()
void ObjectFileJSON::ParseSymtab (lldb_private::Symtab & symtab) override virtual
Parse the symbol table into the provides symbol table object.
Symbol table parsing will be done once when this function is called by each object file plugin. All of the necessary locks will already be acquired before this function is called and the symbol table object to populate is supplied as an argument and doesn't need to be created by each plug-in.
Parameters
The symbol table to populate.
Implements lldb_private::ObjectFile.
Definition at line 172 of file ObjectFileJSON.cpp.
References lldb_private::Symtab::AddSymbol(), lldb_private::Symtab::Finalize(), lldb_private::Symbol::FromJSON(), lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), LLDB_LOG_ERROR, m_symbols, and lldb_private::Symbols.
SetLoadAddress()
bool ObjectFileJSON::SetLoadAddress (Target & target, lldb::addr_t value, bool value_is_offset) override virtual
Sets the load address for an entire module, assuming a rigid slide of sections, if possible in the implementation.
Returns
Returns true iff any section's load address changed.
Reimplemented from lldb_private::ObjectFile.
Definition at line 245 of file ObjectFileJSON.cpp.
References lldb_private::DynamicLoader, lldb_private::GetLog(), LLDB_INVALID_ADDRESS, LLDB_LOGF, lldb_private::ObjectFile::m_sections_up, and lldb_private::Target::SetSectionLoadAddress().
Terminate()
void ObjectFileJSON::Terminate () static
Definition at line 35 of file ObjectFileJSON.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Member Data Documentation
ID
char ObjectFileJSON::ID static
Definition at line 51 of file ObjectFileJSON.h.
Referenced by classof(), and isA().
m_arch
ArchSpec lldb_private::ObjectFileJSON::m_arch private
Definition at line 108 of file ObjectFileJSON.h.
Referenced by GetAddressByteSize(), GetArchitecture(), GetByteOrder(), and ObjectFileJSON().
m_sections
std::vector<JSONSection> lldb_private::ObjectFileJSON::m_sections private
Definition at line 113 of file ObjectFileJSON.h.
Referenced by CreateSections(), and ObjectFileJSON().
m_size
std::optional<uint64_t> lldb_private::ObjectFileJSON::m_size private
Definition at line 111 of file ObjectFileJSON.h.
m_symbols
std::vector<JSONSymbol> lldb_private::ObjectFileJSON::m_symbols private
Definition at line 112 of file ObjectFileJSON.h.
Referenced by ObjectFileJSON(), and ParseSymtab().
m_type
ObjectFile::Type lldb_private::ObjectFileJSON::m_type private
Definition at line 110 of file ObjectFileJSON.h.
Referenced by CalculateType(), and ObjectFileJSON().
m_uuid
UUID lldb_private::ObjectFileJSON::m_uuid private
Definition at line 109 of file ObjectFileJSON.h.
Referenced by GetUUID(), and ObjectFileJSON().
The documentation for this class was generated from the following files:
ObjectFileJSON.h
ObjectFileJSON.cpp