LLDB: RegisterContextFreeBSD_x86_64 Class Reference
RegisterContextFreeBSD_x86_64 Class Reference
#include <RegisterContextFreeBSD_x86_64.h>
Public Member Functions
RegisterContextFreeBSD_x86_64 (const lldb_private::ArchSpec &target_arch)
size_t GetGPRSize () const override
const lldb_private::RegisterInfo * GetRegisterInfo () const override
uint32_t GetRegisterCount () const override
Public Member Functions inherited from lldb_private::RegisterInfoInterface
RegisterInfoInterface (const lldb_private::ArchSpec &target_arch)
virtual ~RegisterInfoInterface ()=default
virtual uint32_t GetUserRegisterCount () const
const lldb_private::ArchSpec & GetTargetArchitecture () const
Private Attributes
const lldb_private::RegisterInfo * m_register_info_p
const uint32_t m_register_count
Detailed Description
Definition at line 14 of file RegisterContextFreeBSD_x86_64.h.
Constructor & Destructor Documentation
RegisterContextFreeBSD_x86_64()
RegisterContextFreeBSD_x86_64::RegisterContextFreeBSD_x86_64 (const lldb_private::ArchSpec & target_arch)
Definition at line 127 of file RegisterContextFreeBSD_x86_64.cpp.
References m_register_count, m_register_info_p, PrivateGetRegisterCount(), PrivateGetRegisterInfoPtr(), and lldb_private::RegisterInfoInterface::RegisterInfoInterface().
Member Function Documentation
GetGPRSize()
size_t RegisterContextFreeBSD_x86_64::GetGPRSize () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 133 of file RegisterContextFreeBSD_x86_64.cpp.
GetRegisterCount()
uint32_t RegisterContextFreeBSD_x86_64::GetRegisterCount () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 139 of file RegisterContextFreeBSD_x86_64.cpp.
References m_register_count.
GetRegisterInfo()
const RegisterInfo * RegisterContextFreeBSD_x86_64::GetRegisterInfo () const override virtual
Implements lldb_private::RegisterInfoInterface.
Definition at line 135 of file RegisterContextFreeBSD_x86_64.cpp.
References m_register_info_p.
Member Data Documentation
m_register_count
const uint32_t RegisterContextFreeBSD_x86_64::m_register_count private
Definition at line 27 of file RegisterContextFreeBSD_x86_64.h.
Referenced by GetRegisterCount(), and RegisterContextFreeBSD_x86_64().
m_register_info_p
const lldb_private::RegisterInfo* RegisterContextFreeBSD_x86_64::m_register_info_p private
Definition at line 26 of file RegisterContextFreeBSD_x86_64.h.
Referenced by GetRegisterInfo(), and RegisterContextFreeBSD_x86_64().
The documentation for this class was generated from the following files:
RegisterContextFreeBSD_x86_64.h
RegisterContextFreeBSD_x86_64.cpp