LLDB: lldb_private::ObjCLanguageRuntime::ObjCExceptionPrecondition Class Reference
lldb_private::ObjCLanguageRuntime::ObjCExceptionPrecondition Class Reference
#include <ObjCLanguageRuntime.h>
Public Member Functions
ObjCExceptionPrecondition ()
~ObjCExceptionPrecondition () override=default
bool EvaluatePrecondition (StoppointCallbackContext &context) override
void GetDescription (Stream &stream, lldb::DescriptionLevel level) override
Status ConfigurePrecondition (Args &args) override
Public Member Functions inherited from lldb_private::BreakpointPrecondition
virtual ~BreakpointPrecondition ()=default
Protected Member Functions
void AddClassName (const char *class_name)
Private Attributes
std::unordered_set< std::string > m_class_names
Detailed Description
Definition at line 172 of file ObjCLanguageRuntime.h.
Constructor & Destructor Documentation
ObjCExceptionPrecondition()
ObjCLanguageRuntime::ObjCExceptionPrecondition::ObjCExceptionPrecondition () default
~ObjCExceptionPrecondition()
lldb_private::ObjCLanguageRuntime::ObjCExceptionPrecondition::~ObjCExceptionPrecondition () override default
Member Function Documentation
AddClassName()
void ObjCLanguageRuntime::ObjCExceptionPrecondition::AddClassName (const char * class_name) protected
Definition at line 401 of file ObjCLanguageRuntime.cpp.
References m_class_names.
ConfigurePrecondition()
Status ObjCLanguageRuntime::ObjCExceptionPrecondition::ConfigurePrecondition (Args & args) override virtual
Reimplemented from lldb_private::BreakpointPrecondition.
Definition at line 417 of file ObjCLanguageRuntime.cpp.
References error(), lldb_private::Status::FromErrorString(), and lldb_private::Args::GetArgumentCount().
EvaluatePrecondition()
bool ObjCLanguageRuntime::ObjCExceptionPrecondition::EvaluatePrecondition (StoppointCallbackContext & context) override virtual
Reimplemented from lldb_private::BreakpointPrecondition.
Definition at line 409 of file ObjCLanguageRuntime.cpp.
GetDescription()
void ObjCLanguageRuntime::ObjCExceptionPrecondition::GetDescription (Stream & stream, lldb::DescriptionLevel level) override virtual
Reimplemented from lldb_private::BreakpointPrecondition.
Definition at line 414 of file ObjCLanguageRuntime.cpp.
Member Data Documentation
m_class_names
std::unordered_set<std::string> lldb_private::ObjCLanguageRuntime::ObjCExceptionPrecondition::m_class_names private
Definition at line 186 of file ObjCLanguageRuntime.h.
Referenced by AddClassName().
The documentation for this class was generated from the following files:
ObjCLanguageRuntime.h
ObjCLanguageRuntime.cpp