LLDB: lldb_private::DynamicRegisterInfo Class Reference
lldb_private::DynamicRegisterInfo Class Reference
#include <DynamicRegisterInfo.h>
Classes
struct Register
Public Types
typedef std::vector< lldb_private::RegisterInfo > reg_collection
typedef llvm::iterator_range< reg_collection::const_iterator > reg_collection_const_range
typedef llvm::iterator_range< reg_collection::iterator > reg_collection_range
Public Member Functions
DynamicRegisterInfo ()=default
virtual ~DynamicRegisterInfo ()=default
DynamicRegisterInfo (DynamicRegisterInfo &&info)
DynamicRegisterInfo & operator= (DynamicRegisterInfo &&info)
size_t SetRegisterInfo (const lldb_private::StructuredData::Dictionary &dict, const lldb_private::ArchSpec &arch)
size_t SetRegisterInfo (std::vector< Register > &&regs, const lldb_private::ArchSpec &arch)
size_t GetNumRegisters () const
size_t GetNumRegisterSets () const
size_t GetRegisterDataByteSize () const
const lldb_private::RegisterInfo * GetRegisterInfoAtIndex (uint32_t i) const
const lldb_private::RegisterSet * GetRegisterSet (uint32_t i) const
uint32_t GetRegisterSetIndexByName (const lldb_private::ConstString &set_name, bool can_create)
uint32_t ConvertRegisterKindToRegisterNumber (uint32_t kind, uint32_t num) const
const lldb_private::RegisterInfo * GetRegisterInfo (uint32_t kind, uint32_t num) const
void Dump () const
void Clear ()
bool IsReconfigurable ()
const lldb_private::RegisterInfo * GetRegisterInfo (llvm::StringRef reg_name) const
template<typename T>
T registers ()=delete
void ConfigureOffsets ()
template<>
DynamicRegisterInfo::reg_collection_const_range registers ()
template<>
DynamicRegisterInfo::reg_collection_range registers ()
Static Public Member Functions
static std::unique_ptr< DynamicRegisterInfo > Create (const StructuredData::Dictionary &dict, const ArchSpec &arch)
Protected Types
typedef std::vector< lldb_private::RegisterSet > set_collection
typedef std::vector< uint32_t > reg_num_collection
typedef std::vector< reg_num_collection > set_reg_num_collection
typedef std::vector< lldb_private::ConstString > name_collection
typedef std::map< uint32_t, reg_num_collection > reg_to_regs_map
typedef std::map< uint32_t, uint32_t > reg_offset_map
Protected Member Functions
DynamicRegisterInfo (DynamicRegisterInfo &)=default
DynamicRegisterInfo & operator= (DynamicRegisterInfo &)=default
llvm::Expected< uint32_t > ByteOffsetFromSlice (uint32_t index, llvm::StringRef slice_str, lldb::ByteOrder byte_order)
llvm::Expected< uint32_t > ByteOffsetFromComposite (uint32_t index, lldb_private::StructuredData::Array &composite_reg_list, lldb::ByteOrder byte_order)
llvm::Expected< uint32_t > ByteOffsetFromRegInfoDict (uint32_t index, lldb_private::StructuredData::Dictionary &reg_info_dict, lldb::ByteOrder byte_order)
void MoveFrom (DynamicRegisterInfo &&info)
void Finalize (const lldb_private::ArchSpec &arch)
Protected Attributes
reg_collection m_regs
set_collection m_sets
set_reg_num_collection m_set_reg_nums
name_collection m_set_names
reg_to_regs_map m_value_regs_map
reg_to_regs_map m_invalidate_regs_map
reg_offset_map m_value_reg_offset_map
size_t m_reg_data_byte_size = 0u
bool m_finalized = false
bool m_is_reconfigurable = false
Detailed Description
Definition at line 22 of file DynamicRegisterInfo.h.
Member Typedef Documentation
name_collection
typedef std::vector<lldb_private::ConstString> lldb_private::DynamicRegisterInfo::name_collection protected
Definition at line 105 of file DynamicRegisterInfo.h.
reg_collection
typedef std::vector<lldb_private::RegisterInfo> lldb_private::DynamicRegisterInfo::reg_collection
Definition at line 91 of file DynamicRegisterInfo.h.
reg_collection_const_range
typedef llvm::iterator_range<reg_collection::const_iterator> lldb_private::DynamicRegisterInfo::reg_collection_const_range
Definition at line 93 of file DynamicRegisterInfo.h.
reg_collection_range
typedef llvm::iterator_range<reg_collection::iterator> lldb_private::DynamicRegisterInfo::reg_collection_range
Definition at line 94 of file DynamicRegisterInfo.h.
reg_num_collection
typedef std::vector<uint32_t> lldb_private::DynamicRegisterInfo::reg_num_collection protected
Definition at line 103 of file DynamicRegisterInfo.h.
reg_offset_map
typedef std::map<uint32_t, uint32_t> lldb_private::DynamicRegisterInfo::reg_offset_map protected
Definition at line 107 of file DynamicRegisterInfo.h.
reg_to_regs_map
typedef std::map<uint32_t, reg_num_collection> lldb_private::DynamicRegisterInfo::reg_to_regs_map protected
Definition at line 106 of file DynamicRegisterInfo.h.
set_collection
typedef std::vector<lldb_private::RegisterSet> lldb_private::DynamicRegisterInfo::set_collection protected
Definition at line 102 of file DynamicRegisterInfo.h.
set_reg_num_collection
typedef std::vector<reg_num_collection> lldb_private::DynamicRegisterInfo::set_reg_num_collection protected
Definition at line 104 of file DynamicRegisterInfo.h.
Constructor & Destructor Documentation
DynamicRegisterInfo() [1/3]
lldb_private::DynamicRegisterInfo::DynamicRegisterInfo (DynamicRegisterInfo &) protected default
References DynamicRegisterInfo().
Referenced by DynamicRegisterInfo(), DynamicRegisterInfo(), lldb_private::process_gdb_remote::GDBRemoteDynamicRegisterInfo::GDBRemoteDynamicRegisterInfo(), MoveFrom(), operator=(), operator=(), and ~DynamicRegisterInfo().
DynamicRegisterInfo() [2/3]
lldb_private::DynamicRegisterInfo::DynamicRegisterInfo () default
~DynamicRegisterInfo()
virtual lldb_private::DynamicRegisterInfo::~DynamicRegisterInfo () virtual default
References DynamicRegisterInfo().
DynamicRegisterInfo() [3/3]
DynamicRegisterInfo::DynamicRegisterInfo (DynamicRegisterInfo && info)
Definition at line 36 of file DynamicRegisterInfo.cpp.
References DynamicRegisterInfo(), and MoveFrom().
Member Function Documentation
ByteOffsetFromComposite()
llvm::Expected< uint32_t > DynamicRegisterInfo::ByteOffsetFromComposite (uint32_t index, lldb_private::StructuredData::Array & composite_reg_list, lldb::ByteOrder byte_order) protected
Definition at line 136 of file DynamicRegisterInfo.cpp.
References lldb_private::RegisterInfo::byte_offset, lldb::eRegisterKindLLDB, lldb_private::StructuredData::Array::GetItemAtIndexAsString(), GetRegisterInfo(), lldb_private::StructuredData::Array::GetSize(), lldb_private::RegisterInfo::kinds, m_invalidate_regs_map, m_value_regs_map, and UINT32_MAX.
Referenced by ByteOffsetFromRegInfoDict().
ByteOffsetFromRegInfoDict()
llvm::Expected< uint32_t > DynamicRegisterInfo::ByteOffsetFromRegInfoDict (uint32_t index, lldb_private::StructuredData::Dictionary & reg_info_dict, lldb::ByteOrder byte_order) protected
Definition at line 176 of file DynamicRegisterInfo.cpp.
References ByteOffsetFromComposite(), ByteOffsetFromSlice(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsArray(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsInteger(), and lldb_private::StructuredData::Dictionary::GetValueForKeyAsString().
Referenced by SetRegisterInfo().
ByteOffsetFromSlice()
llvm::Expected< uint32_t > DynamicRegisterInfo::ByteOffsetFromSlice (uint32_t index, llvm::StringRef slice_str, lldb::ByteOrder byte_order) protected
Definition at line 66 of file DynamicRegisterInfo.cpp.
References lldb_private::RegisterInfo::byte_offset, lldb_private::RegisterInfo::byte_size, lldb::eByteOrderBig, lldb::eByteOrderLittle, lldb::eRegisterKindLLDB, GetRegisterInfo(), lldb_private::RegisterInfo::kinds, m_invalidate_regs_map, and m_value_regs_map.
Referenced by ByteOffsetFromRegInfoDict().
Clear()
void DynamicRegisterInfo::Clear ()
Definition at line 736 of file DynamicRegisterInfo.cpp.
References m_finalized, m_invalidate_regs_map, m_reg_data_byte_size, m_regs, m_set_names, m_set_reg_nums, m_sets, and m_value_regs_map.
Referenced by SetRegisterInfo().
ConfigureOffsets()
void DynamicRegisterInfo::ConfigureOffsets ()
Definition at line 628 of file DynamicRegisterInfo.cpp.
References lldb_private::RegisterInfo::byte_offset, lldb::eRegisterKindLLDB, lldb::eRegisterKindProcessPlugin, GetRegisterInfoAtIndex(), LLDB_INVALID_INDEX32, m_reg_data_byte_size, m_regs, and m_value_reg_offset_map.
Referenced by Finalize(), and lldb_private::ArchitectureAArch64::ReconfigureRegisterInfo().
ConvertRegisterKindToRegisterNumber()
uint32_t DynamicRegisterInfo::ConvertRegisterKindToRegisterNumber (uint32_t kind, uint32_t num) const
Definition at line 725 of file DynamicRegisterInfo.cpp.
References LLDB_INVALID_REGNUM, and m_regs.
Referenced by GetRegisterInfo().
Create()
std::unique_ptr< DynamicRegisterInfo > DynamicRegisterInfo::Create (const StructuredData::Dictionary & dict, const ArchSpec & arch) static
Definition at line 24 of file DynamicRegisterInfo.cpp.
Referenced by lldb_private::ScriptedFrame::CreateRegisterContext(), lldb_private::ScriptedFrame::GetDynamicRegisterInfo(), lldb_private::ScriptedThread::GetDynamicRegisterInfo(), and lldb_private::RegisterContextUnifiedCore::RegisterContextUnifiedCore().
Dump()
void DynamicRegisterInfo::Dump () const
Definition at line 747 of file DynamicRegisterInfo.cpp.
References lldb_private::Stream::EOL(), lldb::eRegisterKindDWARF, lldb::eRegisterKindEHFrame, lldb::eRegisterKindGeneric, lldb::eRegisterKindProcessPlugin, lldb_private::FormatManager::GetFormatAsCString(), LLDB_INVALID_REGNUM, m_regs, m_sets, lldb_private::Stream::Printf(), and registers().
Finalize()
void DynamicRegisterInfo::Finalize (const lldb_private::ArchSpec & arch) protected
Definition at line 437 of file DynamicRegisterInfo.cpp.
References ConfigureOffsets(), lldb::eRegisterKindGeneric, lldb_private::ArchSpec::GetMachine(), lldb_private::ArchSpec::GetTriple(), LLDB_INVALID_REGNUM, LLDB_REGNUM_GENERIC_FLAGS, LLDB_REGNUM_GENERIC_FP, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_RA, LLDB_REGNUM_GENERIC_SP, m_finalized, m_invalidate_regs_map, m_is_reconfigurable, m_regs, m_set_reg_nums, m_sets, and m_value_regs_map.
Referenced by SetRegisterInfo(), and SetRegisterInfo().
GetNumRegisters()
size_t DynamicRegisterInfo::GetNumRegisters () const
Definition at line 679 of file DynamicRegisterInfo.cpp.
References m_regs.
Referenced by RegisterContextMemory::RegisterContextMemory().
GetNumRegisterSets()
size_t DynamicRegisterInfo::GetNumRegisterSets () const
Definition at line 681 of file DynamicRegisterInfo.cpp.
References m_sets.
GetRegisterDataByteSize()
size_t DynamicRegisterInfo::GetRegisterDataByteSize () const
Definition at line 683 of file DynamicRegisterInfo.cpp.
References m_reg_data_byte_size.
Referenced by lldb_private::ArchitectureAArch64::ReconfigureRegisterInfo(), and RegisterContextMemory::RegisterContextMemory().
GetRegisterInfo() [1/2]
const lldb_private::RegisterInfo * DynamicRegisterInfo::GetRegisterInfo (llvm::StringRef reg_name) const
Definition at line 800 of file DynamicRegisterInfo.cpp.
References m_regs.
GetRegisterInfo() [2/2]
const RegisterInfo * DynamicRegisterInfo::GetRegisterInfo (uint32_t kind, uint32_t num) const
Definition at line 694 of file DynamicRegisterInfo.cpp.
References ConvertRegisterKindToRegisterNumber(), LLDB_INVALID_REGNUM, and m_regs.
Referenced by ByteOffsetFromComposite(), ByteOffsetFromSlice(), lldb_private::ArchitectureAArch64::ReconfigureRegisterInfo(), and SetRegisterInfo().
GetRegisterInfoAtIndex()
const RegisterInfo * DynamicRegisterInfo::GetRegisterInfoAtIndex (uint32_t i) const
Definition at line 688 of file DynamicRegisterInfo.cpp.
References m_regs.
Referenced by ConfigureOffsets().
GetRegisterSet()
const RegisterSet * DynamicRegisterInfo::GetRegisterSet (uint32_t i) const
Definition at line 702 of file DynamicRegisterInfo.cpp.
References m_sets.
GetRegisterSetIndexByName()
uint32_t DynamicRegisterInfo::GetRegisterSetIndexByName (const lldb_private::ConstString & set_name, bool can_create)
Definition at line 709 of file DynamicRegisterInfo.cpp.
References lldb_private::ConstString::AsCString(), m_set_names, m_set_reg_nums, and m_sets.
Referenced by SetRegisterInfo().
IsReconfigurable()
bool DynamicRegisterInfo::IsReconfigurable ()
Definition at line 677 of file DynamicRegisterInfo.cpp.
References m_is_reconfigurable.
MoveFrom()
void DynamicRegisterInfo::MoveFrom (DynamicRegisterInfo && info) protected
Definition at line 46 of file DynamicRegisterInfo.cpp.
References DynamicRegisterInfo(), m_finalized, m_invalidate_regs_map, m_reg_data_byte_size, m_regs, m_set_names, m_set_reg_nums, m_sets, m_value_regs_map, and registers().
Referenced by DynamicRegisterInfo(), and operator=().
operator=() [1/2]
DynamicRegisterInfo & DynamicRegisterInfo::operator= (DynamicRegisterInfo && info)
Definition at line 41 of file DynamicRegisterInfo.cpp.
References DynamicRegisterInfo(), and MoveFrom().
operator=() [2/2]
DynamicRegisterInfo & lldb_private::DynamicRegisterInfo::operator= (DynamicRegisterInfo &) protected default
References DynamicRegisterInfo().
registers() [1/3]
template<> DynamicRegisterInfo::reg_collection_const_range lldb_private::DynamicRegisterInfo::registers () inline
Definition at line 138 of file DynamicRegisterInfo.h.
References m_regs.
registers() [2/3]
template<> DynamicRegisterInfo::reg_collection_range lldb_private::DynamicRegisterInfo::registers () inline
Definition at line 144 of file DynamicRegisterInfo.h.
References m_regs.
registers() [3/3]
template<typename T> T lldb_private::DynamicRegisterInfo::registers () delete
Referenced by Dump(), MoveFrom(), and lldb_private::ArchitectureAArch64::ReconfigureRegisterInfo().
SetRegisterInfo() [1/2]
size_t DynamicRegisterInfo::SetRegisterInfo (const lldb_private::StructuredData::Dictionary & dict, const lldb_private::ArchSpec & arch)
Definition at line 201 of file DynamicRegisterInfo.cpp.
References lldb_private::RegisterInfo::alt_name, lldb_private::ConstString::AsCString(), lldb_private::RegisterInfo::byte_offset, lldb_private::RegisterInfo::byte_size, ByteOffsetFromRegInfoDict(), Clear(), lldb_private::StructuredData::Object::DumpToStdout(), lldb::eEncodingUint, lldb::eFormatHex, lldb_private::RegisterInfo::encoding, lldb::eRegisterKindDWARF, lldb::eRegisterKindEHFrame, lldb::eRegisterKindGeneric, lldb::eRegisterKindLLDB, lldb::eRegisterKindProcessPlugin, Finalize(), lldb_private::RegisterInfo::format, lldb_private::ArchSpec::GetByteOrder(), lldb_private::ConstString::GetCString(), lldb_private::StructuredData::Array::GetItemAtIndexAsDictionary(), lldb_private::StructuredData::Array::GetItemAtIndexAsInteger(), lldb_private::StructuredData::Array::GetItemAtIndexAsString(), lldb_private::GetLog(), GetRegisterInfo(), lldb_private::StructuredData::Array::GetSize(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsArray(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsInteger(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsString(), lldb_private::RegisterInfo::kinds, LLDB_INVALID_REGNUM, LLDB_LOG_ERROR, m_finalized, m_invalidate_regs_map, m_reg_data_byte_size, m_regs, m_set_reg_nums, m_sets, lldb_private::RegisterInfo::name, lldb_private::Object, lldb_private::Args::StringToEncoding(), lldb_private::Args::StringToGenericRegister(), lldb_private::OptionArgParser::ToFormat(), and UINT64_MAX.
SetRegisterInfo() [2/2]
size_t DynamicRegisterInfo::SetRegisterInfo (std::vector< Register > && regs, const lldb_private::ArchSpec & arch)
Definition at line 394 of file DynamicRegisterInfo.cpp.
References lldb_private::DynamicRegisterInfo::Register::alt_name, lldb_private::ConstString::AsCString(), lldb_private::DynamicRegisterInfo::Register::byte_offset, lldb_private::DynamicRegisterInfo::Register::byte_size, lldb_private::DynamicRegisterInfo::Register::encoding, Finalize(), lldb_private::DynamicRegisterInfo::Register::flags_type, lldb_private::DynamicRegisterInfo::Register::format, GetRegisterSetIndexByName(), lldb_private::DynamicRegisterInfo::Register::invalidate_regs, m_finalized, m_invalidate_regs_map, m_regs, m_set_names, m_set_reg_nums, m_sets, m_value_reg_offset_map, m_value_regs_map, lldb_private::DynamicRegisterInfo::Register::name, lldb_private::DynamicRegisterInfo::Register::regnum_dwarf, lldb_private::DynamicRegisterInfo::Register::regnum_ehframe, lldb_private::DynamicRegisterInfo::Register::regnum_generic, lldb_private::DynamicRegisterInfo::Register::regnum_remote, lldb_private::DynamicRegisterInfo::Register::set_name, lldb_private::DynamicRegisterInfo::Register::value_reg_offset, and lldb_private::DynamicRegisterInfo::Register::value_regs.
Member Data Documentation
m_finalized
bool lldb_private::DynamicRegisterInfo::m_finalized = false protected
Definition at line 132 of file DynamicRegisterInfo.h.
Referenced by Clear(), Finalize(), MoveFrom(), SetRegisterInfo(), and SetRegisterInfo().
m_invalidate_regs_map
reg_to_regs_map lldb_private::DynamicRegisterInfo::m_invalidate_regs_map protected
Definition at line 128 of file DynamicRegisterInfo.h.
Referenced by ByteOffsetFromComposite(), ByteOffsetFromSlice(), Clear(), Finalize(), MoveFrom(), SetRegisterInfo(), and SetRegisterInfo().
m_is_reconfigurable
bool lldb_private::DynamicRegisterInfo::m_is_reconfigurable = false protected
Definition at line 133 of file DynamicRegisterInfo.h.
Referenced by Finalize(), and IsReconfigurable().
m_reg_data_byte_size
size_t lldb_private::DynamicRegisterInfo::m_reg_data_byte_size = 0u protected
Definition at line 130 of file DynamicRegisterInfo.h.
Referenced by Clear(), ConfigureOffsets(), GetRegisterDataByteSize(), MoveFrom(), and SetRegisterInfo().
m_regs
reg_collection lldb_private::DynamicRegisterInfo::m_regs protected
Definition at line 123 of file DynamicRegisterInfo.h.
Referenced by Clear(), ConfigureOffsets(), ConvertRegisterKindToRegisterNumber(), Dump(), Finalize(), GetNumRegisters(), GetRegisterInfo(), GetRegisterInfo(), GetRegisterInfoAtIndex(), MoveFrom(), registers(), SetRegisterInfo(), and SetRegisterInfo().
m_set_names
name_collection lldb_private::DynamicRegisterInfo::m_set_names protected
Definition at line 126 of file DynamicRegisterInfo.h.
Referenced by Clear(), GetRegisterSetIndexByName(), MoveFrom(), and SetRegisterInfo().
m_set_reg_nums
set_reg_num_collection lldb_private::DynamicRegisterInfo::m_set_reg_nums protected
Definition at line 125 of file DynamicRegisterInfo.h.
Referenced by Clear(), Finalize(), GetRegisterSetIndexByName(), MoveFrom(), SetRegisterInfo(), and SetRegisterInfo().
m_sets
set_collection lldb_private::DynamicRegisterInfo::m_sets protected
Definition at line 124 of file DynamicRegisterInfo.h.
Referenced by Clear(), Dump(), Finalize(), GetNumRegisterSets(), GetRegisterSet(), GetRegisterSetIndexByName(), MoveFrom(), SetRegisterInfo(), and SetRegisterInfo().
m_value_reg_offset_map
reg_offset_map lldb_private::DynamicRegisterInfo::m_value_reg_offset_map protected
Definition at line 129 of file DynamicRegisterInfo.h.
Referenced by ConfigureOffsets(), and SetRegisterInfo().
m_value_regs_map
reg_to_regs_map lldb_private::DynamicRegisterInfo::m_value_regs_map protected
Definition at line 127 of file DynamicRegisterInfo.h.
Referenced by ByteOffsetFromComposite(), ByteOffsetFromSlice(), Clear(), Finalize(), MoveFrom(), and SetRegisterInfo().
The documentation for this class was generated from the following files:
DynamicRegisterInfo.h
DynamicRegisterInfo.cpp