LLDB: RemoteNXMapTable::const_iterator Class Reference
RemoteNXMapTable::const_iterator Class Reference
Public Member Functions
const_iterator (RemoteNXMapTable &parent, int index)
const_iterator (const const_iterator &rhs)
const_iterator & operator= (const const_iterator &rhs)
bool operator== (const const_iterator &rhs) const
bool operator!= (const const_iterator &rhs) const
const_iterator & operator++ ()
element operator* () const
Private Member Functions
void AdvanceToValidIndex ()
Private Attributes
RemoteNXMapTable & m_parent
int m_index
Detailed Description
Definition at line 1340 of file AppleObjCRuntimeV2.cpp.
Constructor & Destructor Documentation
const_iterator() [1/2]
RemoteNXMapTable::const_iterator::const_iterator (RemoteNXMapTable & parent, int index) inline
Definition at line 1342 of file AppleObjCRuntimeV2.cpp.
References RemoteNXMapTable::m_count, and RemoteNXMapTable::m_process.
Referenced by operator++().
const_iterator() [2/2]
RemoteNXMapTable::const_iterator::const_iterator (const const_iterator & rhs) inline
Definition at line 1347 of file AppleObjCRuntimeV2.cpp.
References RemoteNXMapTable::m_num_buckets_minus_one, and RemoteNXMapTable::m_process.
Member Function Documentation
AdvanceToValidIndex()
void RemoteNXMapTable::const_iterator::AdvanceToValidIndex () inline private
Definition at line 1409 of file AppleObjCRuntimeV2.cpp.
Referenced by operator*().
operator!=()
bool RemoteNXMapTable::const_iterator::operator!= (const const_iterator & rhs) const inline
Definition at line 1368 of file AppleObjCRuntimeV2.cpp.
operator*()
element RemoteNXMapTable::const_iterator::operator* () const inline
Definition at line 1377 of file AppleObjCRuntimeV2.cpp.
References AdvanceToValidIndex(), m_index, and m_parent.
operator++()
const_iterator & RemoteNXMapTable::const_iterator::operator++ () inline
Definition at line 1372 of file AppleObjCRuntimeV2.cpp.
References const_iterator(), and RemoteNXMapTable::RemoteNXMapTable().
operator=()
const_iterator & RemoteNXMapTable::const_iterator::operator= (const const_iterator & rhs) inline
Definition at line 1352 of file AppleObjCRuntimeV2.cpp.
References LLDB_INVALID_ADDRESS, RemoteNXMapTable::m_buckets_ptr, RemoteNXMapTable::m_count, and RemoteNXMapTable::m_process.
operator==()
bool RemoteNXMapTable::const_iterator::operator== (const const_iterator & rhs) const inline
Definition at line 1359 of file AppleObjCRuntimeV2.cpp.
Member Data Documentation
m_index
int RemoteNXMapTable::const_iterator::m_index private
Definition at line 1433 of file AppleObjCRuntimeV2.cpp.
Referenced by operator*().
m_parent
RemoteNXMapTable& RemoteNXMapTable::const_iterator::m_parent private
Definition at line 1432 of file AppleObjCRuntimeV2.cpp.
Referenced by operator*().
The documentation for this class was generated from the following file:
AppleObjCRuntimeV2.cpp