LLDB: lldb_private::Mangled Class Reference
lldb_private::Mangled Class Reference
A class that handles mangled names.
#include "lldb/Core/Mangled.h"
Public Types
enum NamePreference { ePreferMangled , ePreferDemangled , ePreferDemangledWithoutArguments }
enum ManglingScheme {
eManglingSchemeNone = 0 , eManglingSchemeMSVC , eManglingSchemeItanium , eManglingSchemeRustV0 ,
eManglingSchemeD , eManglingSchemeSwift
}
using SkipMangledNameFn = bool(llvm::StringRef, ManglingScheme)
Function signature for filtering mangled names.
Public Member Functions
Mangled ()=default
Default constructor.
Mangled (ConstString name)
Construct with name.
Mangled (llvm::StringRef name)
bool operator== (const Mangled &rhs) const
bool operator!= (const Mangled &rhs) const
operator bool () const
Convert to bool operator.
void Clear ()
Clear the mangled and demangled values.
void Dump (Stream *s) const
Dump a description of this object to a Stream s.
void DumpDebug (Stream *s) const
Dump a debug description of this object to a Stream s.
ConstString GetDemangledName () const
Demangled name get accessor.
ConstString GetDisplayDemangledName () const
Display demangled name get accessor.
void SetDemangledName (ConstString name)
void SetMangledName (ConstString name)
ConstString GetMangledName () const
Mangled name get accessor.
ConstString GetName (NamePreference preference=ePreferDemangled) const
Best name get accessor.
bool NameMatches (ConstString name) const
Check if "name" matches either the mangled or demangled name.
bool NameMatches (const RegularExpression &regex) const
size_t MemorySize () const
Get the memory cost of this object.
void SetValue (ConstString name)
Set the string value in this object.
lldb::LanguageType GuessLanguage () const
Try to guess the language from the mangling.
bool GetRichManglingInfo (RichManglingContext &context, SkipMangledNameFn *skip_mangled_name)
Get rich mangling information.
bool Decode (const DataExtractor &data, lldb::offset_t *offset_ptr, const StringTableReader &strtab)
Decode a serialized version of this object from data.
void Encode (DataEncoder &encoder, ConstStringTable &strtab) const
Encode this object into a data encoder object.
const std::optional< DemangledNameInfo > & GetDemangledInfo () const
Retrieve DemangledNameInfo of the demangled name held by this object.
ConstString GetBaseName () const
Compute the base name (without namespace/class qualifiers) from the demangled name.
Static Public Member Functions
static int Compare (const Mangled &lhs, const Mangled &rhs)
Compare the mangled string values.
static Mangled::ManglingScheme GetManglingScheme (llvm::StringRef name)
Try to identify the mangling scheme used.
static bool IsMangledName (llvm::StringRef name)
Private Member Functions
ConstString GetDemangledNameImpl (bool force) const
If force is false, this function will re-use the previously demangled name (if any).
Private Attributes
ConstString m_mangled
The mangled version of the name.
ConstString m_demangled
Mutable so we can get it on demand with a const version of this object.
std::optional< DemangledNameInfo > m_demangled_info = std::nullopt
If available, holds information about where in m_demangled certain parts of the name (e.g., basename, arguments, etc.) begin and end.
Detailed Description
A class that handles mangled names.
Designed to handle mangled names. The demangled version of any names will be computed when the demangled name is accessed through the Demangled() accessor. This class can also tokenize the demangled version of the name for powerful searches. Functions and symbols could make instances of this class for their mangled names. Uniqued string pools are used for the mangled, demangled, and token string values to allow for faster comparisons and for efficient memory use.
Definition at line 34 of file Mangled.h.
Member Typedef Documentation
SkipMangledNameFn
using lldb_private::Mangled::SkipMangledNameFn = bool(llvm::StringRef, ManglingScheme)
Function signature for filtering mangled names.
Definition at line 215 of file Mangled.h.
Member Enumeration Documentation
ManglingScheme
enum lldb_private::Mangled::ManglingScheme
Enumerator
eManglingSchemeNone
eManglingSchemeMSVC
eManglingSchemeItanium
eManglingSchemeRustV0
eManglingSchemeD
eManglingSchemeSwift
Definition at line 42 of file Mangled.h.
NamePreference
enum lldb_private::Mangled::NamePreference
Enumerator
ePreferMangled
ePreferDemangled
ePreferDemangledWithoutArguments
Definition at line 36 of file Mangled.h.
Constructor & Destructor Documentation
Mangled() [1/3]
lldb_private::Mangled::Mangled () default
Default constructor.
Initialize with both mangled and demangled names empty.
Referenced by Compare(), operator!=(), and operator==().
Mangled() [2/3]
Mangled::Mangled (ConstString name) explicit
Construct with name.
Constructor with an optional string and auto-detect if name is mangled or not.
Parameters
[in] name The already const name to copy into this object.
Definition at line 93 of file Mangled.cpp.
References m_demangled, m_mangled, and SetValue().
Mangled() [3/3]
Mangled::Mangled (llvm::StringRef name) explicit
Definition at line 98 of file Mangled.cpp.
References SetValue().
Member Function Documentation
Clear()
void Mangled::Clear ()
Clear the mangled and demangled values.
Definition at line 112 of file Mangled.cpp.
References m_demangled, m_demangled_info, and m_mangled.
Compare()
int Mangled::Compare (const Mangled & lhs, const Mangled & rhs) static
Compare the mangled string values.
Compares the Mangled::GetName() string in lhs and rhs.
Parameters
[in] lhs A const reference to the Left Hand Side object to compare.
[in] rhs A const reference to the Right Hand Side object to compare.
Returns
-1 if lhs is less than rhs 0 if lhs is equal to rhs 1 if lhs is greater than rhs
Definition at line 119 of file Mangled.cpp.
References lldb_private::ConstString::Compare(), ePreferMangled, GetName(), and Mangled().
Referenced by SymbolContextsMightBeEquivalent().
Decode()
bool Mangled::Decode (const DataExtractor & data, lldb::offset_t * offset_ptr, const StringTableReader & strtab)
Decode a serialized version of this object from data.
Parameters
data The decoder object that references the serialized data.
offset_ptr A pointer that contains the offset from which the data will be decoded from that gets updated as data gets decoded.
strtab All strings in cache files are put into string tables for efficiency and cache file size reduction. Strings are stored as uint32_t string table offsets in the cache data.
Definition at line 477 of file Mangled.cpp.
References DemangledOnly, Empty, lldb_private::StringTableReader::Get(), lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU8(), m_demangled, m_demangled_info, m_mangled, MangledAndDemangled, and MangledOnly.
Dump()
void Mangled::Dump (Stream * s) const
Dump a description of this object to a Stream s.
Dump a Mangled object to stream s. We don't force our demangled name to be computed currently (we don't use the accessor).
Parameters
[in] s The stream to which to dump the object description.
Definition at line 392 of file Mangled.cpp.
References m_demangled, m_mangled, and lldb_private::Stream::Printf().
DumpDebug()
void Mangled::DumpDebug (Stream * s) const
Dump a debug description of this object to a Stream s.
Parameters
[in] s The stream to which to dump the object description.
Definition at line 404 of file Mangled.cpp.
References m_demangled, m_mangled, and lldb_private::Stream::Printf().
Encode()
void Mangled::Encode (DataEncoder & file, ConstStringTable & strtab) const
Encode this object into a data encoder object.
The encoding format for the Mangled object is as follows:
This allows this object to be serialized to disk.
Parameters
encoder A data encoder object that serialized bytes will be encoded into.
strtab All strings in cache files are put into string tables for efficiency and cache file size reduction. Strings are stored as uint32_t string table offsets in the cache data.
uint8_t encoding; char str1[]; (only if DemangledOnly, MangledOnly) char str2[]; (only if MangledAndDemangled)
The strings are stored as NULL terminated UTF8 strings and str1 and str2 are only saved if we need them based on the encoding.
Some mangled names have a mangled name that can be demangled by the built in demanglers. These kinds of mangled objects know when the mangled and demangled names are the counterparts for each other. This is done because demangling is very expensive and avoiding demangling the same name twice saves us a lot of compute time. For these kinds of names we only need to save the mangled name and have the encoding set to "MangledOnly".
If a mangled obejct has only a demangled name, then we save only that string and have the encoding set to "DemangledOnly".
Some mangled objects have both mangled and demangled names, but the demangled name can not be computed from the mangled name. This is often used for runtime named, like Objective C runtime V2 and V3 names. Both these names must be saved and the encoding is set to "MangledAndDemangled".
For a Mangled object with no names, we only need to set the encoding to "Empty" and not store any string values.
Definition at line 528 of file Mangled.cpp.
References lldb_private::ConstStringTable::Add(), lldb_private::DataEncoder::AppendU32(), lldb_private::DataEncoder::AppendU8(), DemangledOnly, Empty, m_demangled, m_mangled, MangledAndDemangled, and MangledOnly.
GetBaseName()
ConstString Mangled::GetBaseName () const
Compute the base name (without namespace/class qualifiers) from the demangled name.
For a demangled name like "ns::MyClass<int>::templateFunc", this returns just "templateFunc".
Returns
A ConstString containing the basename, or nullptr if computation fails.
Definition at line 560 of file Mangled.cpp.
References lldb_private::ConstString::AsCString(), GetDemangledInfo(), and GetDemangledName().
GetDemangledInfo()
std::optional< DemangledNameInfo > const & Mangled::GetDemangledInfo () const
Retrieve DemangledNameInfo of the demangled name held by this object.
Definition at line 288 of file Mangled.cpp.
References GetDemangledNameImpl(), and m_demangled_info.
Referenced by GetAndValidateInfo(), and GetBaseName().
GetDemangledName()
ConstString Mangled::GetDemangledName () const
Demangled name get accessor.
Returns
A const reference to the demangled name string object.
Definition at line 284 of file Mangled.cpp.
References GetDemangledNameImpl().
Referenced by lldb_private::Symtab::AppendSymbolNamesToMap(), lldb_private::Symbol::Compare(), lldb_private::CPlusPlusLanguage::FindBestAlternateFunctionMangledName(), GetAndValidateInfo(), GetBaseName(), lldb_private::CPlusPlusLanguage::GetDemangledFunctionNameWithoutArguments(), lldb_private::Language::GetDemangledFunctionNameWithoutArguments(), lldb::SBTypeMemberFunction::GetDemangledName(), lldb_private::Language::GetDisplayDemangledName(), GetDisplayDemangledName(), SymbolFilePDB::GetMangledForPDBFunc(), GetName(), lldb_private::ItaniumABILanguageRuntime::GetTypeInfo(), lldb_private::ItaniumABILanguageRuntime::GetVTableInfo(), lldb_private::Symtab::InitNameIndexes(), NameMatches(), NameMatches(), lldb_private::Module::LookupInfo::NameMatchesLookupInfo(), operator<<(), operator==(), ObjectFileELF::ParseSymbols(), ObjectFileMachO::ParseSymtab(), lldb_private::PersistentExpressionState::RegisterExecutionUnit(), and lldb_private::ObjCLanguage::SymbolNameFitsToLanguage().
GetDemangledNameImpl()
ConstString Mangled::GetDemangledNameImpl (bool force) const private
If force is false, this function will re-use the previously demangled name (if any).
If force is true (or the mangled name on this object was not previously demangled), demangle and cache the name.
Definition at line 299 of file Mangled.cpp.
References eManglingSchemeD, eManglingSchemeItanium, eManglingSchemeMSVC, eManglingSchemeNone, eManglingSchemeRustV0, eManglingSchemeSwift, GetDLangDemangledStr(), GetItaniumDemangledStr(), GetManglingScheme(), GetMSVCDemangledStr(), GetRustV0DemangledStr(), m_demangled, m_demangled_info, and m_mangled.
Referenced by GetDemangledInfo(), and GetDemangledName().
GetDisplayDemangledName()
ConstString Mangled::GetDisplayDemangledName () const
Display demangled name get accessor.
Returns
A const reference to the display demangled name string object.
Definition at line 354 of file Mangled.cpp.
References lldb_private::Language::FindPlugin(), GetDemangledName(), and GuessLanguage().
Referenced by CommandObjectMultiwordItaniumABI_Demangle::DoExecute(), and lldb_private::Symbol::GetDisplayName().
GetMangledName()
ConstString lldb_private::Mangled::GetMangledName () const inline
Mangled name get accessor.
Returns
The mangled name string object.
Definition at line 152 of file Mangled.h.
References m_mangled.
Referenced by lldb_private::ClangExpressionDeclMap::AddOneFunction(), lldb_private::Symtab::AppendSymbolNamesToMap(), lldb_private::Symbol::Compare(), GetAndValidateInfo(), lldb_private::CPlusPlusLanguage::GetDemangledFunctionNameWithoutArguments(), lldb_private::Language::GetDemangledFunctionNameWithoutArguments(), lldb_private::BreakpointLocation::GetDescription(), lldb_private::Symtab::InitNameIndexes(), lldb_private::CPPLanguageRuntime::IsSymbolARuntimeThunk(), operator<<(), ObjectFileELF::ParseSymbols(), and lldb_private::CPlusPlusLanguage::SymbolNameFitsToLanguage().
GetManglingScheme()
Mangled::ManglingScheme Mangled::GetManglingScheme (llvm::StringRef name) static
Try to identify the mangling scheme used.
Parameters
[in] name The name we are attempting to identify the mangling scheme for.
Returns
eManglingSchemeNone if no known mangling scheme could be identified for s, otherwise the enumerator for the mangling scheme detected.
Definition at line 43 of file Mangled.cpp.
References eManglingSchemeD, eManglingSchemeItanium, eManglingSchemeMSVC, eManglingSchemeNone, eManglingSchemeRustV0, and eManglingSchemeSwift.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::FindGlobalVariables(), GetDemangledNameImpl(), GetRichManglingInfo(), IsMangledName(), lldb_private::Module::LookupInfo::NameMatchesLookupInfo(), and lldb_private::CPlusPlusLanguage::SymbolNameFitsToLanguage().
GetName()
ConstString Mangled::GetName (Mangled::NamePreference preference = ePreferDemangled) const
Best name get accessor.
Parameters
[in] preference Which name would you prefer to get?
Returns
A const reference to the preferred name string object if this object has a valid name of that kind, else a const reference to the other name is returned.
Definition at line 369 of file Mangled.cpp.
References ePreferDemangled, ePreferDemangledWithoutArguments, ePreferMangled, lldb_private::Language::FindPlugin(), GetDemangledName(), GuessLanguage(), and m_mangled.
Referenced by Compare(), lldb_private::Symbol::Dump(), lldb_private::DynamicLoaderDarwin::FindEquivalentSymbols(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo::GetFileRangeMap(), lldb_private::Symbol::GetName(), lldb_private::Symbol::GetNameNoArguments(), DynamicLoaderHexagonDYLD::GetStepThroughTrampolinePlan(), DynamicLoaderPOSIXDYLD::GetStepThroughTrampolinePlan(), lldb_private::DynamicLoaderDarwin::GetStepThroughTrampolinePlan(), GetSymbolDeclarationFromAddress(), ObjectFileELF::ParseSymbols(), ObjectFileMachO::ParseSymtab(), PrintFunctionNameWithArgs(), and PrintFunctionNameWithArgs().
GetRichManglingInfo()
bool Mangled::GetRichManglingInfo (RichManglingContext & context, SkipMangledNameFn * skip_mangled_name)
Get rich mangling information.
This is optimized for batch processing while populating a name index. To get the pure demangled name string for a single entity, use GetDemangledName() instead.
For names that match the Itanium mangling scheme, this uses LLVM's ItaniumPartialDemangler. All other names fall back to LLDB's builtin parser currently.
This function is thread-safe when used with different context instances in different threads.
Parameters
[in] context The context for this function. A single instance can be stack- allocated in the caller's frame and used for multiple calls.
[in] skip_mangled_name A filtering function for skipping entities based on name and mangling scheme. This can be null if unused.
Returns
True on success, false otherwise.
Definition at line 228 of file Mangled.cpp.
References eManglingSchemeD, eManglingSchemeItanium, eManglingSchemeMSVC, eManglingSchemeNone, eManglingSchemeRustV0, eManglingSchemeSwift, lldb_private::RichManglingContext::FromCxxMethodName(), lldb_private::RichManglingContext::FromItaniumName(), GetManglingScheme(), GetMSVCDemangledStr(), m_demangled, and m_mangled.
Referenced by lldb_private::Symtab::InitNameIndexes().
GuessLanguage()
lldb::LanguageType Mangled::GuessLanguage () const
Try to guess the language from the mangling.
For a mangled name to have a language it must have both a mangled and a demangled name and it can be guessed from the mangling what the language is. Note: this will return C++ for any language that uses Itanium ABI mangling.
Standard C function names will return eLanguageTypeUnknown because they aren't mangled and it isn't clear what language the name represents (there will be no mangled name).
Returns
The language for the mangled/demangled name, eLanguageTypeUnknown if there is no mangled or demangled counterpart.
Definition at line 425 of file Mangled.cpp.
References lldb_private::Continue, lldb::eLanguageTypeUnknown, lldb_private::Language::ForEach(), l, and lldb_private::Stop.
Referenced by CommandObjectMultiwordItaniumABI_Demangle::DoExecute(), GetDisplayDemangledName(), lldb_private::Symbol::GetLanguage(), GetName(), and lldb_private::StackFrame::GuessLanguage().
IsMangledName()
bool Mangled::IsMangledName (llvm::StringRef name) static
Definition at line 39 of file Mangled.cpp.
References eManglingSchemeNone, and GetManglingScheme().
Referenced by lldb_private::ClangExpressionDeclMap::AddOneFunction(), SymbolFilePDB::CacheFunctionNames(), lldb_private::npdb::SymbolFileNativePDB::CacheGlobalBaseNames(), ExtractMangledNameFromFunctionCallLabel(), lldb_private::CPlusPlusLanguage::GetFunctionNameInfo(), and SetValue().
MemorySize()
size_t Mangled::MemorySize () const
Get the memory cost of this object.
Return the size in bytes that this object takes in memory. This returns the size in bytes of this object, not any shared string values it may refer to.
Returns
The number of bytes that this object occupies in memory.
Definition at line 415 of file Mangled.cpp.
References m_demangled, and m_mangled.
NameMatches() [1/2]
bool Mangled::NameMatches (const RegularExpression & regex) const
Definition at line 360 of file Mangled.cpp.
References lldb_private::RegularExpression::Execute(), GetDemangledName(), lldb_private::ConstString::GetStringRef(), and m_mangled.
NameMatches() [2/2]
bool lldb_private::Mangled::NameMatches (ConstString name) const inline
Check if "name" matches either the mangled or demangled name.
Parameters
[in] name A name to match against both strings.
Returns
True if name matches either name, false otherwise.
Definition at line 172 of file Mangled.h.
References GetDemangledName(), and m_mangled.
Referenced by lldb_private::plugin::dwarf::AppleDWARFIndex::GetGlobalVariables(), lldb_private::plugin::dwarf::DebugNamesDWARFIndex::GetGlobalVariables(), and lldb_private::SymbolContextSpecifier::SymbolContextMatches().
operator bool()
Mangled::operator bool () const explicit
Convert to bool operator.
This allows code to check any Mangled objects to see if they contain anything valid using code such as:
Mangled mangled(...);
if (mangled)
{ ...
Returns
Returns true if either the mangled or unmangled name is set, false if the object has an empty mangled and unmangled name.
Definition at line 109 of file Mangled.cpp.
References m_demangled, and m_mangled.
operator!=()
bool lldb_private::Mangled::operator!= (const Mangled & rhs) const inline
Definition at line 72 of file Mangled.h.
References Mangled().
operator==()
bool lldb_private::Mangled::operator== (const Mangled & rhs) const inline
Definition at line 67 of file Mangled.h.
References GetDemangledName(), m_mangled, and Mangled().
SetDemangledName()
void lldb_private::Mangled::SetDemangledName (ConstString name) inline
Definition at line 138 of file Mangled.h.
References m_demangled, and m_demangled_info.
Referenced by ObjectFilePECOFF::AppendFromExportTable(), SymbolFilePDB::GetMangledForPDBFunc(), DWARFASTParserClang::ParseFunctionFromDWARF(), ObjectFileELF::ParseSymbols(), and ObjectFileMachO::ParseSymtab().
SetMangledName()
void lldb_private::Mangled::SetMangledName (ConstString name) inline
Definition at line 143 of file Mangled.h.
References m_demangled_info, and m_mangled.
Referenced by SymbolFilePDB::GetMangledForPDBFunc(), DWARFASTParserClang::ParseFunctionFromDWARF(), ObjectFileELF::ParseSymbols(), and ObjectFileMachO::ParseSymtab().
SetValue()
void Mangled::SetValue (ConstString name)
Set the string value in this object.
This version auto detects if the string is mangled by inspecting the string value and looking for common mangling prefixes.
Parameters
[in] name The already const version of the name for this object.
Definition at line 124 of file Mangled.cpp.
References lldb_private::ConstString::GetStringRef(), IsMangledName(), m_demangled, m_demangled_info, and m_mangled.
Referenced by ObjectFilePECOFF::AppendFromCOFFSymbolTable(), ObjectFilePECOFF::AppendFromExportTable(), SymbolFilePDB::GetMangledForPDBFunc(), lldb_private::breakpad::SymbolFileBreakpad::GetOrCreateFunction(), Mangled(), Mangled(), DWARFASTParserClang::ParseFunctionFromDWARF(), ObjectFileCOFF::ParseSymtab(), ObjectFileMachO::ParseSymtab(), and ObjectFileXCOFF::ParseSymtab().
Member Data Documentation
m_demangled
ConstString lldb_private::Mangled::m_demangled mutable private
Mutable so we can get it on demand with a const version of this object.
Definition at line 307 of file Mangled.h.
Referenced by Clear(), Decode(), Dump(), DumpDebug(), Encode(), GetDemangledNameImpl(), GetRichManglingInfo(), Mangled(), MemorySize(), operator bool(), SetDemangledName(), and SetValue().
m_demangled_info
std::optional<DemangledNameInfo> lldb_private::Mangled::m_demangled_info = std::nullopt mutable private
If available, holds information about where in m_demangled certain parts of the name (e.g., basename, arguments, etc.) begin and end.
Definition at line 311 of file Mangled.h.
Referenced by Clear(), Decode(), GetDemangledInfo(), GetDemangledNameImpl(), SetDemangledName(), SetMangledName(), and SetValue().
m_mangled
ConstString lldb_private::Mangled::m_mangled private
The mangled version of the name.
Definition at line 303 of file Mangled.h.
Referenced by Clear(), Decode(), Dump(), DumpDebug(), Encode(), GetDemangledNameImpl(), GetMangledName(), GetName(), GetRichManglingInfo(), Mangled(), MemorySize(), NameMatches(), NameMatches(), operator bool(), operator==(), SetMangledName(), and SetValue().
The documentation for this class was generated from the following files:
Mangled.h
Mangled.cpp