LLDB: lldb_private::dil::ASTNode Class Reference
lldb_private::dil::ASTNode Class Reference abstract
The rest of the classes in this file, except for the Visitor class at the very end, define all the types of AST nodes used by the DIL parser and expression evaluator.
#include <DILAST.h>
Public Member Functions
ASTNode (uint32_t location, NodeKind kind)
virtual ~ASTNode ()=default
virtual llvm::Expected< lldb::ValueObjectSP > Accept (Visitor *v) const =0
uint32_t GetLocation () const
NodeKind GetKind () const
Private Attributes
uint32_t m_location
const NodeKind m_kind
Detailed Description
The rest of the classes in this file, except for the Visitor class at the very end, define all the types of AST nodes used by the DIL parser and expression evaluator.
The DIL parser parses the input string and creates the AST parse tree from the AST nodes. The resulting AST node tree gets passed to the DIL expression evaluator, which evaluates the DIL AST nodes and creates/returns a ValueObjectSP containing the result. Base class for AST nodes used by the Data Inspection Language (DIL) parser. All of the specialized types of AST nodes inherit from this (virtual) base class.
Definition at line 63 of file DILAST.h.
Constructor & Destructor Documentation
ASTNode()
lldb_private::dil::ASTNode::ASTNode (uint32_t location, NodeKind kind) inline
Definition at line 65 of file DILAST.h.
References m_kind, and m_location.
Referenced by lldb_private::dil::ArraySubscriptNode::ArraySubscriptNode(), lldb_private::dil::BitFieldExtractionNode::BitFieldExtractionNode(), lldb_private::dil::BooleanLiteralNode::BooleanLiteralNode(), lldb_private::dil::CastNode::CastNode(), lldb_private::dil::ArraySubscriptNode::classof(), lldb_private::dil::BitFieldExtractionNode::classof(), lldb_private::dil::BooleanLiteralNode::classof(), lldb_private::dil::CastNode::classof(), lldb_private::dil::ErrorNode::classof(), lldb_private::dil::FloatLiteralNode::classof(), lldb_private::dil::IdentifierNode::classof(), lldb_private::dil::IntegerLiteralNode::classof(), lldb_private::dil::MemberOfNode::classof(), lldb_private::dil::UnaryOpNode::classof(), lldb_private::dil::ErrorNode::ErrorNode(), lldb_private::dil::FloatLiteralNode::FloatLiteralNode(), lldb_private::dil::ArraySubscriptNode::GetBase(), lldb_private::dil::BitFieldExtractionNode::GetBase(), lldb_private::dil::MemberOfNode::GetBase(), lldb_private::dil::BitFieldExtractionNode::GetFirstIndex(), lldb_private::dil::ArraySubscriptNode::GetIndex(), lldb_private::dil::BitFieldExtractionNode::GetLastIndex(), lldb_private::dil::CastNode::GetOperand(), lldb_private::dil::UnaryOpNode::GetOperand(), lldb_private::dil::IdentifierNode::IdentifierNode(), lldb_private::dil::IntegerLiteralNode::IntegerLiteralNode(), lldb_private::dil::MemberOfNode::MemberOfNode(), and lldb_private::dil::UnaryOpNode::UnaryOpNode().
~ASTNode()
virtual lldb_private::dil::ASTNode::~ASTNode () virtual default
Member Function Documentation
Accept()
virtual llvm::Expected< lldb::ValueObjectSP > lldb_private::dil::ASTNode::Accept (Visitor * v) const pure virtual
Implemented in lldb_private::dil::ArraySubscriptNode, lldb_private::dil::BitFieldExtractionNode, lldb_private::dil::BooleanLiteralNode, lldb_private::dil::CastNode, lldb_private::dil::ErrorNode, lldb_private::dil::FloatLiteralNode, lldb_private::dil::IdentifierNode, lldb_private::dil::IntegerLiteralNode, lldb_private::dil::MemberOfNode, and lldb_private::dil::UnaryOpNode.
Referenced by lldb_private::dil::Interpreter::Evaluate().
GetKind()
NodeKind lldb_private::dil::ASTNode::GetKind () const inline
Definition at line 72 of file DILAST.h.
References m_kind.
Referenced by lldb_private::dil::ArraySubscriptNode::classof(), lldb_private::dil::BitFieldExtractionNode::classof(), lldb_private::dil::BooleanLiteralNode::classof(), lldb_private::dil::CastNode::classof(), lldb_private::dil::ErrorNode::classof(), lldb_private::dil::FloatLiteralNode::classof(), lldb_private::dil::IdentifierNode::classof(), lldb_private::dil::IntegerLiteralNode::classof(), lldb_private::dil::MemberOfNode::classof(), and lldb_private::dil::UnaryOpNode::classof().
GetLocation()
uint32_t lldb_private::dil::ASTNode::GetLocation () const inline
Definition at line 71 of file DILAST.h.
References m_location.
Referenced by lldb_private::dil::Interpreter::Evaluate(), lldb_private::dil::Interpreter::PickIntegerType(), lldb_private::dil::Interpreter::Visit(), lldb_private::dil::Interpreter::Visit(), lldb_private::dil::Interpreter::Visit(), lldb_private::dil::Interpreter::Visit(), lldb_private::dil::Interpreter::Visit(), lldb_private::dil::Interpreter::Visit(), and lldb_private::dil::Interpreter::Visit().
Member Data Documentation
m_kind
const NodeKind lldb_private::dil::ASTNode::m_kind private
Definition at line 76 of file DILAST.h.
Referenced by ASTNode(), and GetKind().
m_location
uint32_t lldb_private::dil::ASTNode::m_location private
Definition at line 75 of file DILAST.h.
Referenced by ASTNode(), and GetLocation().
The documentation for this class was generated from the following file:
DILAST.h