LLDB: lldb_private::ThreadCollection Class Reference
lldb_private::ThreadCollection Class Reference
#include <ThreadCollection.h>
Public Types
typedef std::vector< lldb::ThreadSP > collection
typedef LockingAdaptedIterable< std::recursive_mutex, collection > ThreadIterable
Public Member Functions
ThreadCollection ()
ThreadCollection (collection threads)
virtual ~ThreadCollection ()=default
uint32_t GetSize ()
void AddThread (const lldb::ThreadSP &thread_sp)
void AddThreadSortedByIndexID (const lldb::ThreadSP &thread_sp)
void InsertThread (const lldb::ThreadSP &thread_sp, uint32_t idx)
lldb::ThreadSP GetThreadAtIndex (uint32_t idx)
virtual ThreadIterable Threads ()
virtual std::recursive_mutex & GetMutex () const
Protected Attributes
collection m_threads
std::recursive_mutex m_mutex
Detailed Description
Definition at line 20 of file ThreadCollection.h.
Member Typedef Documentation
collection
typedef std::vector<lldb::ThreadSP> lldb_private::ThreadCollection::collection
Definition at line 22 of file ThreadCollection.h.
ThreadIterable
typedef LockingAdaptedIterable<std::recursive_mutex, collection> lldb_private::ThreadCollection::ThreadIterable
Definition at line 24 of file ThreadCollection.h.
Constructor & Destructor Documentation
ThreadCollection() [1/2]
ThreadCollection::ThreadCollection ()
Definition at line 19 of file ThreadCollection.cpp.
References m_mutex, and m_threads.
Referenced by lldb_private::ThreadList::ThreadList(), and lldb_private::ThreadList::ThreadList().
ThreadCollection() [2/2]
ThreadCollection::ThreadCollection (collection threads)
Definition at line 21 of file ThreadCollection.cpp.
References m_mutex, and m_threads.
~ThreadCollection()
virtual lldb_private::ThreadCollection::~ThreadCollection () virtual default
Member Function Documentation
AddThread()
void ThreadCollection::AddThread (const lldb::ThreadSP & thread_sp)
Definition at line 24 of file ThreadCollection.cpp.
References GetMutex(), and m_threads.
Referenced by lldb_private::minidump::ProcessMinidump::DoUpdateThreadList(), lldb_private::ProcessWindows::DoUpdateThreadList(), lldb_private::ScriptedProcess::DoUpdateThreadList(), ProcessElfCore::DoUpdateThreadList(), ProcessFreeBSDKernelCore::DoUpdateThreadList(), ProcessKDP::DoUpdateThreadList(), ProcessMachCore::DoUpdateThreadList(), lldb::SBThread::GetExtendedBacktraceThread(), lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::ParseThread(), and lldb_private::ThreadList::WillResume().
AddThreadSortedByIndexID()
void ThreadCollection::AddThreadSortedByIndexID (const lldb::ThreadSP & thread_sp)
Definition at line 29 of file ThreadCollection.cpp.
References GetMutex(), and m_threads.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::DoUpdateThreadList().
GetMutex()
virtual std::recursive_mutex & lldb_private::ThreadCollection::GetMutex () const inline virtual
Reimplemented in lldb_private::ThreadList.
Definition at line 49 of file ThreadCollection.h.
References m_mutex.
Referenced by AddThread(), AddThreadSortedByIndexID(), GetSize(), GetThreadAtIndex(), InsertThread(), and Threads().
GetSize()
uint32_t ThreadCollection::GetSize ()
Definition at line 54 of file ThreadCollection.cpp.
References GetMutex(), and m_threads.
GetThreadAtIndex()
ThreadSP ThreadCollection::GetThreadAtIndex (uint32_t idx)
Definition at line 59 of file ThreadCollection.cpp.
References GetMutex(), and m_threads.
InsertThread()
void ThreadCollection::InsertThread (const lldb::ThreadSP & thread_sp, uint32_t idx)
Definition at line 45 of file ThreadCollection.cpp.
References GetMutex(), and m_threads.
Threads()
virtual ThreadIterable lldb_private::ThreadCollection::Threads () inline virtual
Definition at line 45 of file ThreadCollection.h.
References GetMutex(), and m_threads.
Referenced by lldb_private::ProcessWindows::DoUpdateThreadList(), lldb_private::Process::HandleProcessStateChangedEvent(), SaveOffRegionsWithStackPointers(), and lldb_private::ThreadPlanStackMap::Update().
Member Data Documentation
m_mutex
std::recursive_mutex lldb_private::ThreadCollection::m_mutex mutable protected
Definition at line 53 of file ThreadCollection.h.
Referenced by GetMutex(), ThreadCollection(), and ThreadCollection().
m_threads
collection lldb_private::ThreadCollection::m_threads protected
Definition at line 52 of file ThreadCollection.h.
Referenced by AddThread(), AddThreadSortedByIndexID(), lldb_private::ThreadList::Clear(), lldb_private::ThreadList::Destroy(), lldb_private::ThreadList::DidResume(), lldb_private::ThreadList::DidStop(), lldb_private::ThreadList::DiscardThreadPlans(), lldb_private::ThreadList::FindThreadByID(), lldb_private::ThreadList::FindThreadByIndexID(), lldb_private::ThreadList::FindThreadByProtocolID(), lldb_private::ThreadList::Flush(), lldb_private::ThreadList::GetSelectedThread(), GetSize(), lldb_private::ThreadList::GetSize(), GetThreadAtIndex(), lldb_private::ThreadList::GetThreadAtIndex(), lldb_private::ThreadList::GetThreadSPForThreadPtr(), InsertThread(), lldb_private::ThreadList::operator=(), lldb_private::ThreadList::RefreshStateAfterStop(), lldb_private::ThreadList::RemoveThreadByID(), lldb_private::ThreadList::RemoveThreadByProtocolID(), lldb_private::ThreadList::SetShouldReportStop(), lldb_private::ThreadList::ShouldReportRun(), lldb_private::ThreadList::ShouldReportStop(), lldb_private::ThreadList::ShouldStop(), ThreadCollection(), ThreadCollection(), Threads(), lldb_private::ThreadList::Update(), and lldb_private::ThreadList::WillResume().
The documentation for this class was generated from the following files:
ThreadCollection.h
ThreadCollection.cpp