LLDB: lldb_private::SourceManager::SourceFileCache Class Reference
lldb_private::SourceManager::SourceFileCache Class Reference
The SourceFileCache class separates the source manager from the cache of source files.
#include <SourceManager.h>
Public Member Functions
SourceFileCache ()=default
~SourceFileCache ()=default
void AddSourceFile (const FileSpec &file_spec, FileSP file_sp)
void RemoveSourceFile (const FileSP &file_sp)
FileSP FindSourceFile (const FileSpec &file_spec) const
void Clear ()
void Dump (Stream &stream) const
Private Types
typedef std::map< FileSpec, FileSP > FileCache
Private Member Functions
void AddSourceFileImpl (const FileSpec &file_spec, FileSP file_sp)
Private Attributes
FileCache m_file_cache
llvm::sys::RWMutex m_mutex
Detailed Description
The SourceFileCache class separates the source manager from the cache of source files.
There is one source manager per Target but both the Debugger and the Process have their own source caches.
The SourceFileCache just handles adding, storing, removing and looking up source files. The caching policies are implemented in SourceManager::GetFile.
Definition at line 127 of file SourceManager.h.
Member Typedef Documentation
FileCache
typedef std::map<FileSpec, FileSP> lldb_private::SourceManager::SourceFileCache::FileCache private
Definition at line 145 of file SourceManager.h.
Constructor & Destructor Documentation
SourceFileCache()
lldb_private::SourceManager::SourceFileCache::SourceFileCache () default
~SourceFileCache()
lldb_private::SourceManager::SourceFileCache::~SourceFileCache () default
Member Function Documentation
AddSourceFile()
void SourceManager::SourceFileCache::AddSourceFile (const FileSpec & file_spec, FileSP file_sp)
Definition at line 836 of file SourceManager.cpp.
References AddSourceFileImpl(), and m_mutex.
AddSourceFileImpl()
void SourceManager::SourceFileCache::AddSourceFileImpl (const FileSpec & file_spec, FileSP file_sp) private
Definition at line 864 of file SourceManager.cpp.
References m_file_cache.
Referenced by AddSourceFile().
Clear()
void lldb_private::SourceManager::SourceFileCache::Clear () inline
Definition at line 138 of file SourceManager.h.
References m_file_cache.
Referenced by CommandObjectSourceCacheClear::DoExecute().
Dump()
void SourceManager::SourceFileCache::Dump (Stream & stream) const
Definition at line 885 of file SourceManager.cpp.
References lldb_private::Stream::Format(), m_file_cache, and lldb_private::toString().
Referenced by CommandObjectSourceCacheDump::DoExecute().
FindSourceFile()
SourceManager::FileSP SourceManager::SourceFileCache::FindSourceFile (const FileSpec & file_spec) const
Definition at line 875 of file SourceManager.cpp.
References m_file_cache, and m_mutex.
RemoveSourceFile()
void SourceManager::SourceFileCache::RemoveSourceFile (const FileSP & file_sp)
Definition at line 848 of file SourceManager.cpp.
References m_file_cache, and m_mutex.
Member Data Documentation
m_file_cache
FileCache lldb_private::SourceManager::SourceFileCache::m_file_cache private
Definition at line 146 of file SourceManager.h.
Referenced by AddSourceFileImpl(), Clear(), Dump(), FindSourceFile(), and RemoveSourceFile().
m_mutex
llvm::sys::RWMutex lldb_private::SourceManager::SourceFileCache::m_mutex mutable private
Definition at line 148 of file SourceManager.h.
Referenced by AddSourceFile(), FindSourceFile(), and RemoveSourceFile().
The documentation for this class was generated from the following files:
SourceManager.h
SourceManager.cpp