LLDB: EmulateInstructionMIPS Class Reference
EmulateInstructionMIPS Class Reference
#include <EmulateInstructionMIPS.h>
Classes
struct MipsOpcode
Public Member Functions
llvm::StringRef GetPluginName () override
bool SetTargetTriple (const lldb_private::ArchSpec &arch) override
EmulateInstructionMIPS (const lldb_private::ArchSpec &arch)
bool SupportsEmulatingInstructionsOfType (lldb_private::InstructionType inst_type) override
bool ReadInstruction () override
bool EvaluateInstruction (uint32_t evaluate_options) override
bool SetInstruction (const lldb_private::Opcode &insn_opcode, const lldb_private::Address &inst_addr, lldb_private::Target *target) override
bool TestEmulation (lldb_private::Stream &out_stream, lldb_private::ArchSpec &arch, lldb_private::OptionValueDictionary *test_data) override
std::optional< lldb_private::RegisterInfo > GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num) override
bool CreateFunctionEntryUnwind (lldb_private::UnwindPlan &unwind_plan) override
Public Member Functions inherited from lldb_private::EmulateInstruction
EmulateInstruction (const ArchSpec &arch)
~EmulateInstruction () override=default
virtual std::optional< uint32_t > GetLastInstrSize ()
virtual InstructionCondition GetInstructionCondition ()
std::optional< RegisterValue > ReadRegister (const RegisterInfo &reg_info)
uint64_t ReadRegisterUnsigned (const RegisterInfo &reg_info, uint64_t fail_value, bool *success_ptr)
bool WriteRegister (const Context &context, const RegisterInfo &ref_info, const RegisterValue &reg_value)
bool WriteRegisterUnsigned (const Context &context, const RegisterInfo &reg_info, uint64_t reg_value)
bool ReadRegister (lldb::RegisterKind reg_kind, uint32_t reg_num, RegisterValue &reg_value)
bool WriteRegister (const Context &context, lldb::RegisterKind reg_kind, uint32_t reg_num, const RegisterValue &reg_value)
uint64_t ReadRegisterUnsigned (lldb::RegisterKind reg_kind, uint32_t reg_num, uint64_t fail_value, bool *success_ptr)
bool WriteRegisterUnsigned (const Context &context, lldb::RegisterKind reg_kind, uint32_t reg_num, uint64_t reg_value)
size_t ReadMemory (const Context &context, lldb::addr_t addr, void *dst, size_t dst_len)
uint64_t ReadMemoryUnsigned (const Context &context, lldb::addr_t addr, size_t byte_size, uint64_t fail_value, bool *success_ptr)
bool WriteMemory (const Context &context, lldb::addr_t addr, const void *src, size_t src_len)
bool WriteMemoryUnsigned (const Context &context, lldb::addr_t addr, uint64_t uval, size_t uval_byte_size)
uint32_t GetAddressByteSize () const
lldb::ByteOrder GetByteOrder () const
const Opcode & GetOpcode () const
lldb::addr_t GetAddress () const
const ArchSpec & GetArchitecture () const
void SetBaton (void *baton)
void SetCallbacks (ReadMemoryCallback read_mem_callback, WriteMemoryCallback write_mem_callback, ReadRegisterCallback read_reg_callback, WriteRegisterCallback write_reg_callback)
void SetReadMemCallback (ReadMemoryCallback read_mem_callback)
void SetWriteMemCallback (WriteMemoryCallback write_mem_callback)
void SetReadRegCallback (ReadRegisterCallback read_reg_callback)
void SetWriteRegCallback (WriteRegisterCallback write_reg_callback)
std::optional< lldb::addr_t > ReadPC ()
bool WritePC (lldb::addr_t addr)
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static lldb_private::EmulateInstruction * CreateInstance (const lldb_private::ArchSpec &arch, lldb_private::InstructionType inst_type)
static bool SupportsEmulatingInstructionsOfTypeStatic (lldb_private::InstructionType inst_type)
Static Public Member Functions inherited from lldb_private::EmulateInstruction
static EmulateInstruction * FindPlugin (const ArchSpec &arch, InstructionType supported_inst_type, const char *plugin_name)
static const char * TranslateRegister (lldb::RegisterKind reg_kind, uint32_t reg_num, std::string &reg_name)
static size_t ReadMemoryFrame (EmulateInstruction *instruction, void *baton, const Context &context, lldb::addr_t addr, void *dst, size_t length)
static size_t WriteMemoryFrame (EmulateInstruction *instruction, void *baton, const Context &context, lldb::addr_t addr, const void *dst, size_t length)
static bool ReadRegisterFrame (EmulateInstruction *instruction, void *baton, const RegisterInfo *reg_info, RegisterValue &reg_value)
static bool WriteRegisterFrame (EmulateInstruction *instruction, void *baton, const Context &context, const RegisterInfo *reg_info, const RegisterValue &reg_value)
static size_t ReadMemoryDefault (EmulateInstruction *instruction, void *baton, const Context &context, lldb::addr_t addr, void *dst, size_t length)
static size_t WriteMemoryDefault (EmulateInstruction *instruction, void *baton, const Context &context, lldb::addr_t addr, const void *dst, size_t length)
static bool ReadRegisterDefault (EmulateInstruction *instruction, void *baton, const RegisterInfo *reg_info, RegisterValue &reg_value)
static bool WriteRegisterDefault (EmulateInstruction *instruction, void *baton, const Context &context, const RegisterInfo *reg_info, const RegisterValue &reg_value)
static bool GetBestRegisterKindAndNumber (const RegisterInfo *reg_info, lldb::RegisterKind &reg_kind, uint32_t &reg_num)
static uint32_t GetInternalRegisterNumber (RegisterContext *reg_ctx, const RegisterInfo &reg_info)
static std::unique_ptr< SingleStepBreakpointLocationsPredictor > CreateBreakpointLocationPredictor (std::unique_ptr< EmulateInstruction > emulator_up)
Protected Member Functions
uint32_t GetSizeOfInstruction (lldb_private::DataExtractor &data, uint64_t inst_addr)
bool Emulate_ADDiu (llvm::MCInst &insn)
bool Emulate_SUBU_ADDU (llvm::MCInst &insn)
bool Emulate_LUI (llvm::MCInst &insn)
bool Emulate_SW (llvm::MCInst &insn)
bool Emulate_LW (llvm::MCInst &insn)
bool Emulate_ADDIUSP (llvm::MCInst &insn)
bool Emulate_ADDIUS5 (llvm::MCInst &insn)
bool Emulate_SWSP (llvm::MCInst &insn)
bool Emulate_SWM16_32 (llvm::MCInst &insn)
bool Emulate_LWSP (llvm::MCInst &insn)
bool Emulate_LWM16_32 (llvm::MCInst &insn)
bool Emulate_JRADDIUSP (llvm::MCInst &insn)
bool Emulate_LDST_Imm (llvm::MCInst &insn)
bool Emulate_LDST_Reg (llvm::MCInst &insn)
bool Emulate_BXX_3ops (llvm::MCInst &insn)
bool Emulate_BXX_3ops_C (llvm::MCInst &insn)
bool Emulate_BXX_2ops (llvm::MCInst &insn)
bool Emulate_BXX_2ops_C (llvm::MCInst &insn)
bool Emulate_Bcond_Link_C (llvm::MCInst &insn)
bool Emulate_Bcond_Link (llvm::MCInst &insn)
bool Emulate_FP_branch (llvm::MCInst &insn)
bool Emulate_3D_branch (llvm::MCInst &insn)
bool Emulate_BAL (llvm::MCInst &insn)
bool Emulate_BALC (llvm::MCInst &insn)
bool Emulate_BC (llvm::MCInst &insn)
bool Emulate_J (llvm::MCInst &insn)
bool Emulate_JAL (llvm::MCInst &insn)
bool Emulate_JALR (llvm::MCInst &insn)
bool Emulate_JIALC (llvm::MCInst &insn)
bool Emulate_JIC (llvm::MCInst &insn)
bool Emulate_JR (llvm::MCInst &insn)
bool Emulate_BC1EQZ (llvm::MCInst &insn)
bool Emulate_BC1NEZ (llvm::MCInst &insn)
bool Emulate_BNZB (llvm::MCInst &insn)
bool Emulate_BNZH (llvm::MCInst &insn)
bool Emulate_BNZW (llvm::MCInst &insn)
bool Emulate_BNZD (llvm::MCInst &insn)
bool Emulate_BZB (llvm::MCInst &insn)
bool Emulate_BZH (llvm::MCInst &insn)
bool Emulate_BZW (llvm::MCInst &insn)
bool Emulate_BZD (llvm::MCInst &insn)
bool Emulate_MSA_Branch_DF (llvm::MCInst &insn, int element_byte_size, bool bnz)
bool Emulate_BNZV (llvm::MCInst &insn)
bool Emulate_BZV (llvm::MCInst &insn)
bool Emulate_MSA_Branch_V (llvm::MCInst &insn, bool bnz)
bool Emulate_B16_MM (llvm::MCInst &insn)
bool Emulate_Branch_MM (llvm::MCInst &insn)
bool Emulate_JALRx16_MM (llvm::MCInst &insn)
bool Emulate_JALx (llvm::MCInst &insn)
bool Emulate_JALRS (llvm::MCInst &insn)
bool nonvolatile_reg_p (uint32_t regnum)
const char * GetRegisterName (unsigned reg_num, bool alternate_name)
Static Protected Member Functions
static MipsOpcode * GetOpcodeForInstruction (llvm::StringRef name)
Private Attributes
std::unique_ptr< llvm::MCDisassembler > m_disasm
std::unique_ptr< llvm::MCDisassembler > m_alt_disasm
std::unique_ptr< llvm::MCSubtargetInfo > m_subtype_info
std::unique_ptr< llvm::MCSubtargetInfo > m_alt_subtype_info
std::unique_ptr< llvm::MCRegisterInfo > m_reg_info
llvm::MCTargetOptions m_mc_options
std::unique_ptr< llvm::MCAsmInfo > m_asm_info
std::unique_ptr< llvm::MCContext > m_context
std::unique_ptr< llvm::MCInstrInfo > m_insn_info
uint32_t m_next_inst_size
bool m_use_alt_disaasm
Additional Inherited Members
Public Types inherited from lldb_private::EmulateInstruction
enum ContextType {
eContextInvalid = 0 , eContextReadOpcode , eContextImmediate , eContextPushRegisterOnStack ,
eContextPopRegisterOffStack , eContextAdjustStackPointer , eContextSetFramePointer , eContextRestoreStackPointer ,
eContextAdjustBaseRegister , eContextAdjustPC , eContextRegisterPlusOffset , eContextRegisterStore ,
eContextRegisterLoad , eContextRelativeBranchImmediate , eContextAbsoluteBranchRegister , eContextSupervisorCall ,
eContextTableBranchReadMemory , eContextWriteRegisterRandomBits , eContextWriteMemoryRandomBits , eContextArithmetic ,
eContextAdvancePC , eContextReturnFromException
}
enum InfoType {
eInfoTypeRegisterPlusOffset , eInfoTypeRegisterPlusIndirectOffset , eInfoTypeRegisterToRegisterPlusOffset , eInfoTypeRegisterToRegisterPlusIndirectOffset ,
eInfoTypeRegisterRegisterOperands , eInfoTypeOffset , eInfoTypeRegister , eInfoTypeImmediate ,
eInfoTypeImmediateSigned , eInfoTypeAddress , eInfoTypeISAAndImmediate , eInfoTypeISAAndImmediateSigned ,
eInfoTypeISA , eInfoTypeNoArgs
}
typedef size_t(* ReadMemoryCallback) (EmulateInstruction *instruction, void *baton, const Context &context, lldb::addr_t addr, void *dst, size_t length)
typedef size_t(* WriteMemoryCallback) (EmulateInstruction *instruction, void *baton, const Context &context, lldb::addr_t addr, const void *dst, size_t length)
typedef bool(* ReadRegisterCallback) (EmulateInstruction *instruction, void *baton, const RegisterInfo *reg_info, RegisterValue &reg_value)
typedef bool(* WriteRegisterCallback) (EmulateInstruction *instruction, void *baton, const Context &context, const RegisterInfo *reg_info, const RegisterValue &reg_value)
typedef uint32_t InstructionCondition
Static Public Attributes inherited from lldb_private::EmulateInstruction
static const InstructionCondition UnconditionalCondition = UINT32_MAX
Protected Types inherited from lldb_private::EmulateInstruction
using BreakpointLocationsPredictorCreator
Protected Attributes inherited from lldb_private::EmulateInstruction
ArchSpec m_arch
void * m_baton = nullptr
ReadMemoryCallback m_read_mem_callback = &ReadMemoryDefault
WriteMemoryCallback m_write_mem_callback = &WriteMemoryDefault
ReadRegisterCallback m_read_reg_callback = &ReadRegisterDefault
WriteRegisterCallback m_write_reg_callback = &WriteRegisterDefault
lldb::addr_t m_addr = LLDB_INVALID_ADDRESS
Opcode m_opcode
Detailed Description
Definition at line 33 of file EmulateInstructionMIPS.h.
Constructor & Destructor Documentation
EmulateInstructionMIPS()
EmulateInstructionMIPS::EmulateInstructionMIPS (const lldb_private::ArchSpec & arch)
Definition at line 63 of file EmulateInstructionMIPS.cpp.
References lldb_private::ArchSpec::eCore_mips32, lldb_private::ArchSpec::eCore_mips32el, lldb_private::ArchSpec::eCore_mips32r2, lldb_private::ArchSpec::eCore_mips32r2el, lldb_private::ArchSpec::eCore_mips32r3, lldb_private::ArchSpec::eCore_mips32r3el, lldb_private::ArchSpec::eCore_mips32r5, lldb_private::ArchSpec::eCore_mips32r5el, lldb_private::ArchSpec::eCore_mips32r6, lldb_private::ArchSpec::eCore_mips32r6el, lldb_private::ArchSpec::eCore_mips64, lldb_private::ArchSpec::eCore_mips64el, lldb_private::ArchSpec::eCore_mips64r2, lldb_private::ArchSpec::eCore_mips64r2el, lldb_private::ArchSpec::eCore_mips64r3, lldb_private::ArchSpec::eCore_mips64r3el, lldb_private::ArchSpec::eCore_mips64r5, lldb_private::ArchSpec::eCore_mips64r5el, lldb_private::ArchSpec::eCore_mips64r6, lldb_private::ArchSpec::eCore_mips64r6el, lldb_private::ArchSpec::eMIPSAse_dsp, lldb_private::ArchSpec::eMIPSAse_dspr2, lldb_private::ArchSpec::eMIPSAse_micromips, lldb_private::ArchSpec::eMIPSAse_mips16, lldb_private::ArchSpec::eMIPSAse_msa, lldb_private::EmulateInstruction::EmulateInstruction(), lldb_private::ArchSpec::GetCore(), lldb_private::ArchSpec::GetFlags(), lldb_private::ArchSpec::GetTriple(), m_alt_disasm, m_alt_subtype_info, m_asm_info, m_context, m_disasm, m_insn_info, m_mc_options, m_next_inst_size, m_reg_info, m_subtype_info, and m_use_alt_disaasm.
Referenced by CreateInstance().
Member Function Documentation
CreateFunctionEntryUnwind()
bool EmulateInstructionMIPS::CreateFunctionEntryUnwind (lldb_private::UnwindPlan & unwind_plan) override virtual
Reimplemented from lldb_private::EmulateInstruction.
Definition at line 1122 of file EmulateInstructionMIPS.cpp.
References lldb_private::UnwindPlan::AppendRow(), lldb_private::UnwindPlan::Clear(), dwarf_pc_mips, dwarf_ra_mips, dwarf_sp_mips, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), lldb_private::UnwindPlan::SetRegisterKind(), lldb_private::UnwindPlan::Row::SetRegisterLocationToRegister(), lldb_private::UnwindPlan::SetReturnAddressRegister(), lldb_private::UnwindPlan::SetSourcedFromCompiler(), lldb_private::UnwindPlan::SetSourceName(), lldb_private::UnwindPlan::SetUnwindPlanForSignalTrap(), and lldb_private::UnwindPlan::SetUnwindPlanValidAtAllInstructions().
CreateInstance()
EmulateInstruction * EmulateInstructionMIPS::CreateInstance (const lldb_private::ArchSpec & arch, lldb_private::InstructionType inst_type) static
Definition at line 199 of file EmulateInstructionMIPS.cpp.
References EmulateInstructionMIPS(), lldb_private::ArchSpec::GetTriple(), and SupportsEmulatingInstructionsOfTypeStatic().
Referenced by Initialize(), and Terminate().
Emulate_3D_branch()
bool EmulateInstructionMIPS::Emulate_3D_branch (llvm::MCInst & insn) protected
Definition at line 2783 of file EmulateInstructionMIPS.cpp.
References dwarf_fcsr_mips, dwarf_pc_mips, lldb::eRegisterKindDWARF, m_insn_info, m_reg_info, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_ADDiu()
bool EmulateInstructionMIPS::Emulate_ADDiu (llvm::MCInst & insn) protected
Definition at line 1169 of file EmulateInstructionMIPS.cpp.
References dwarf_sp_mips, dwarf_zero_mips, lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb_private::EmulateInstruction::eContextImmediate, lldb::eRegisterKindDWARF, GetRegisterInfo(), m_reg_info, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetImmediateSigned(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::SignedBits(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_ADDIUS5()
bool EmulateInstructionMIPS::Emulate_ADDIUS5 (llvm::MCInst & insn) protected
Definition at line 1450 of file EmulateInstructionMIPS.cpp.
References dwarf_sp_mips, dwarf_zero_mips, lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb::eRegisterKindDWARF, GetRegisterInfo(), m_reg_info, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_ADDIUSP()
bool EmulateInstructionMIPS::Emulate_ADDIUSP (llvm::MCInst & insn) protected
Definition at line 1423 of file EmulateInstructionMIPS.cpp.
References dwarf_sp_mips, lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb::eRegisterKindDWARF, GetRegisterInfo(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_B16_MM()
bool EmulateInstructionMIPS::Emulate_B16_MM (llvm::MCInst & insn) protected
Definition at line 2151 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, lldb_private::EmulateInstruction::eContextRelativeBranchImmediate, lldb::eRegisterKindDWARF, m_insn_info, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetImmediate(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_BAL()
bool EmulateInstructionMIPS::Emulate_BAL (llvm::MCInst & insn) protected
Definition at line 2400 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_ra_mips, lldb::eRegisterKindDWARF, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_BALC()
bool EmulateInstructionMIPS::Emulate_BALC (llvm::MCInst & insn) protected
Definition at line 2431 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_ra_mips, lldb::eRegisterKindDWARF, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_BC()
bool EmulateInstructionMIPS::Emulate_BC (llvm::MCInst & insn) protected
Definition at line 2462 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, lldb::eRegisterKindDWARF, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_BC1EQZ()
bool EmulateInstructionMIPS::Emulate_BC1EQZ (llvm::MCInst & insn) protected
Definition at line 2704 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_zero_mips, lldb::eRegisterKindDWARF, m_reg_info, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_BC1NEZ()
bool EmulateInstructionMIPS::Emulate_BC1NEZ (llvm::MCInst & insn) protected
Definition at line 2740 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_zero_mips, lldb::eRegisterKindDWARF, m_reg_info, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_Bcond_Link()
bool EmulateInstructionMIPS::Emulate_Bcond_Link (llvm::MCInst & insn) protected
Definition at line 1983 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_ra_mips, dwarf_zero_mips, lldb::eRegisterKindDWARF, m_insn_info, m_reg_info, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_Bcond_Link_C()
bool EmulateInstructionMIPS::Emulate_Bcond_Link_C (llvm::MCInst & insn) protected
Definition at line 1914 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_ra_mips, dwarf_zero_mips, lldb::eRegisterKindDWARF, m_insn_info, m_reg_info, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_BNZB()
bool EmulateInstructionMIPS::Emulate_BNZB (llvm::MCInst & insn) protected
Definition at line 2835 of file EmulateInstructionMIPS.cpp.
References Emulate_MSA_Branch_DF().
Referenced by GetOpcodeForInstruction().
Emulate_BNZD()
bool EmulateInstructionMIPS::Emulate_BNZD (llvm::MCInst & insn) protected
Definition at line 2847 of file EmulateInstructionMIPS.cpp.
References Emulate_MSA_Branch_DF().
Referenced by GetOpcodeForInstruction().
Emulate_BNZH()
bool EmulateInstructionMIPS::Emulate_BNZH (llvm::MCInst & insn) protected
Definition at line 2839 of file EmulateInstructionMIPS.cpp.
References Emulate_MSA_Branch_DF().
Referenced by GetOpcodeForInstruction().
Emulate_BNZV()
bool EmulateInstructionMIPS::Emulate_BNZV (llvm::MCInst & insn) protected
Definition at line 2927 of file EmulateInstructionMIPS.cpp.
References Emulate_MSA_Branch_V().
Referenced by GetOpcodeForInstruction().
Emulate_BNZW()
bool EmulateInstructionMIPS::Emulate_BNZW (llvm::MCInst & insn) protected
Definition at line 2843 of file EmulateInstructionMIPS.cpp.
References Emulate_MSA_Branch_DF().
Referenced by GetOpcodeForInstruction().
Emulate_Branch_MM()
bool EmulateInstructionMIPS::Emulate_Branch_MM (llvm::MCInst & insn) protected
Definition at line 2178 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_ra_mips, dwarf_zero_mips, lldb_private::EmulateInstruction::eContextRelativeBranchImmediate, lldb::eRegisterKindDWARF, m_insn_info, m_next_inst_size, m_reg_info, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetImmediate(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_BXX_2ops()
bool EmulateInstructionMIPS::Emulate_BXX_2ops (llvm::MCInst & insn) protected
Definition at line 2034 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_zero_mips, lldb_private::EmulateInstruction::eContextRelativeBranchImmediate, lldb::eRegisterKindDWARF, m_insn_info, m_reg_info, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetImmediate(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_BXX_2ops_C()
bool EmulateInstructionMIPS::Emulate_BXX_2ops_C (llvm::MCInst & insn) protected
Definition at line 2091 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_zero_mips, lldb_private::EmulateInstruction::eContextRelativeBranchImmediate, lldb::eRegisterKindDWARF, m_insn_info, m_reg_info, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetImmediate(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_BXX_3ops()
bool EmulateInstructionMIPS::Emulate_BXX_3ops (llvm::MCInst & insn) protected
Definition at line 1785 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_zero_mips, lldb_private::EmulateInstruction::eContextRelativeBranchImmediate, lldb::eRegisterKindDWARF, m_insn_info, m_reg_info, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetImmediate(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_BXX_3ops_C()
bool EmulateInstructionMIPS::Emulate_BXX_3ops_C (llvm::MCInst & insn) protected
Definition at line 1835 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_zero_mips, lldb_private::EmulateInstruction::eContextRelativeBranchImmediate, lldb::eRegisterKindDWARF, IsAdd64bitOverflow(), m_insn_info, m_reg_info, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetImmediate(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_BZB()
bool EmulateInstructionMIPS::Emulate_BZB (llvm::MCInst & insn) protected
Definition at line 2851 of file EmulateInstructionMIPS.cpp.
References Emulate_MSA_Branch_DF().
Referenced by GetOpcodeForInstruction().
Emulate_BZD()
bool EmulateInstructionMIPS::Emulate_BZD (llvm::MCInst & insn) protected
Definition at line 2863 of file EmulateInstructionMIPS.cpp.
References Emulate_MSA_Branch_DF().
Referenced by GetOpcodeForInstruction().
Emulate_BZH()
bool EmulateInstructionMIPS::Emulate_BZH (llvm::MCInst & insn) protected
Definition at line 2855 of file EmulateInstructionMIPS.cpp.
References Emulate_MSA_Branch_DF().
Referenced by GetOpcodeForInstruction().
Emulate_BZV()
bool EmulateInstructionMIPS::Emulate_BZV (llvm::MCInst & insn) protected
Definition at line 2931 of file EmulateInstructionMIPS.cpp.
References Emulate_MSA_Branch_V().
Referenced by GetOpcodeForInstruction().
Emulate_BZW()
bool EmulateInstructionMIPS::Emulate_BZW (llvm::MCInst & insn) protected
Definition at line 2859 of file EmulateInstructionMIPS.cpp.
References Emulate_MSA_Branch_DF().
Referenced by GetOpcodeForInstruction().
Emulate_FP_branch()
bool EmulateInstructionMIPS::Emulate_FP_branch (llvm::MCInst & insn) protected
Definition at line 2665 of file EmulateInstructionMIPS.cpp.
References dwarf_fcsr_mips, dwarf_pc_mips, lldb::eRegisterKindDWARF, m_insn_info, m_reg_info, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_J()
bool EmulateInstructionMIPS::Emulate_J (llvm::MCInst & insn) protected
Definition at line 2485 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, lldb::eRegisterKindDWARF, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_JAL()
bool EmulateInstructionMIPS::Emulate_JAL (llvm::MCInst & insn) protected
Definition at line 2508 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_ra_mips, lldb::eRegisterKindDWARF, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_JALR()
bool EmulateInstructionMIPS::Emulate_JALR (llvm::MCInst & insn) protected
Definition at line 2539 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_zero_mips, lldb::eRegisterKindDWARF, m_reg_info, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_JALRS()
bool EmulateInstructionMIPS::Emulate_JALRS (llvm::MCInst & insn) protected
Definition at line 2363 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_zero_mips, lldb::eRegisterKindDWARF, m_reg_info, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_JALRx16_MM()
bool EmulateInstructionMIPS::Emulate_JALRx16_MM (llvm::MCInst & insn) protected
Definition at line 2279 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_ra_mips, dwarf_zero_mips, lldb::eRegisterKindDWARF, m_insn_info, m_reg_info, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_JALx()
bool EmulateInstructionMIPS::Emulate_JALx (llvm::MCInst & insn) protected
Definition at line 2318 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_ra_mips, lldb::eRegisterKindDWARF, m_insn_info, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_JIALC()
bool EmulateInstructionMIPS::Emulate_JIALC (llvm::MCInst & insn) protected
Definition at line 2574 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_ra_mips, dwarf_zero_mips, lldb::eRegisterKindDWARF, m_reg_info, pc, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_JIC()
bool EmulateInstructionMIPS::Emulate_JIC (llvm::MCInst & insn) protected
Definition at line 2612 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_zero_mips, lldb::eRegisterKindDWARF, m_reg_info, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_JR()
bool EmulateInstructionMIPS::Emulate_JR (llvm::MCInst & insn) protected
Definition at line 2638 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_zero_mips, lldb::eRegisterKindDWARF, m_reg_info, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_JRADDIUSP()
bool EmulateInstructionMIPS::Emulate_JRADDIUSP (llvm::MCInst & insn) protected
Definition at line 1732 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_ra_mips, dwarf_sp_mips, lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb::eRegisterKindDWARF, GetRegisterInfo(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_LDST_Imm()
bool EmulateInstructionMIPS::Emulate_LDST_Imm (llvm::MCInst & insn) protected
Definition at line 2970 of file EmulateInstructionMIPS.cpp.
References dwarf_bad_mips, dwarf_zero_mips, lldb_private::EmulateInstruction::eContextInvalid, lldb::eRegisterKindDWARF, GetRegisterInfo(), m_reg_info, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_LDST_Reg()
bool EmulateInstructionMIPS::Emulate_LDST_Reg (llvm::MCInst & insn) protected
Definition at line 3001 of file EmulateInstructionMIPS.cpp.
References dwarf_bad_mips, dwarf_zero_mips, lldb_private::EmulateInstruction::eContextInvalid, lldb::eRegisterKindDWARF, GetRegisterInfo(), m_reg_info, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_LUI()
bool EmulateInstructionMIPS::Emulate_LUI (llvm::MCInst & insn) protected
Definition at line 1406 of file EmulateInstructionMIPS.cpp.
References dwarf_zero_mips, lldb_private::EmulateInstruction::eContextImmediate, lldb::eRegisterKindDWARF, m_reg_info, lldb_private::EmulateInstruction::Context::SetImmediateSigned(), lldb_private::SignedBits(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_LW()
bool EmulateInstructionMIPS::Emulate_LW (llvm::MCInst & insn) protected
Definition at line 1283 of file EmulateInstructionMIPS.cpp.
References dwarf_bad_mips, dwarf_zero_mips, lldb_private::EmulateInstruction::eContextInvalid, lldb_private::EmulateInstruction::eContextPopRegisterOffStack, lldb::eRegisterKindDWARF, GetRegisterInfo(), m_reg_info, nonvolatile_reg_p(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::type, lldb_private::EmulateInstruction::WriteRegister(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_LWM16_32()
bool EmulateInstructionMIPS::Emulate_LWM16_32 (llvm::MCInst & insn) protected
Definition at line 1675 of file EmulateInstructionMIPS.cpp.
References dwarf_sp_mips, dwarf_zero_mips, lldb_private::EmulateInstruction::eContextPopRegisterOffStack, lldb::eRegisterKindDWARF, GetRegisterInfo(), m_reg_info, nonvolatile_reg_p(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegister().
Referenced by GetOpcodeForInstruction().
Emulate_LWSP()
bool EmulateInstructionMIPS::Emulate_LWSP (llvm::MCInst & insn) protected
Definition at line 1627 of file EmulateInstructionMIPS.cpp.
References dwarf_bad_mips, dwarf_sp_mips, dwarf_zero_mips, lldb_private::EmulateInstruction::eContextInvalid, lldb_private::EmulateInstruction::eContextPopRegisterOffStack, lldb::eRegisterKindDWARF, GetRegisterInfo(), m_reg_info, nonvolatile_reg_p(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetAddress(), lldb_private::EmulateInstruction::Context::type, lldb_private::EmulateInstruction::WriteRegister(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_MSA_Branch_DF()
bool EmulateInstructionMIPS::Emulate_MSA_Branch_DF (llvm::MCInst & insn, int element_byte_size, bool bnz) protected
Definition at line 2867 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_w0_mips, lldb_private::EmulateInstruction::eContextRelativeBranchImmediate, lldb::eRegisterKindDWARF, lldb_private::RegisterValue::GetBytes(), m_reg_info, pc, lldb_private::EmulateInstruction::ReadRegister(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by Emulate_BNZB(), Emulate_BNZD(), Emulate_BNZH(), Emulate_BNZW(), Emulate_BZB(), Emulate_BZD(), Emulate_BZH(), and Emulate_BZW().
Emulate_MSA_Branch_V()
bool EmulateInstructionMIPS::Emulate_MSA_Branch_V (llvm::MCInst & insn, bool bnz) protected
Definition at line 2935 of file EmulateInstructionMIPS.cpp.
References dwarf_pc_mips, dwarf_w0_mips, lldb_private::EmulateInstruction::eContextRelativeBranchImmediate, lldb::eRegisterKindDWARF, lldb_private::RegisterValue::GetAsUInt128(), m_reg_info, pc, lldb_private::EmulateInstruction::ReadRegister(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by Emulate_BNZV(), and Emulate_BZV().
Emulate_SUBU_ADDU()
bool EmulateInstructionMIPS::Emulate_SUBU_ADDU (llvm::MCInst & insn) protected
Definition at line 1327 of file EmulateInstructionMIPS.cpp.
References dwarf_sp_mips, dwarf_zero_mips, lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb_private::EmulateInstruction::eContextImmediate, lldb::eRegisterKindDWARF, GetRegisterInfo(), m_insn_info, m_reg_info, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetImmediateSigned(), lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_SW()
bool EmulateInstructionMIPS::Emulate_SW (llvm::MCInst & insn) protected
Definition at line 1221 of file EmulateInstructionMIPS.cpp.
References dwarf_bad_mips, dwarf_zero_mips, lldb::eByteOrderLittle, lldb_private::EmulateInstruction::eContextInvalid, lldb_private::EmulateInstruction::eContextPushRegisterOnStack, lldb::eRegisterKindDWARF, error(), GetRegisterInfo(), m_reg_info, nonvolatile_reg_p(), lldb_private::EmulateInstruction::ReadRegister(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), lldb_private::SignedBits(), lldb_private::EmulateInstruction::Context::type, lldb_private::EmulateInstruction::WriteMemory(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
Emulate_SWM16_32()
bool EmulateInstructionMIPS::Emulate_SWM16_32 (llvm::MCInst & insn) protected
Definition at line 1549 of file EmulateInstructionMIPS.cpp.
References dwarf_sp_mips, dwarf_zero_mips, lldb::eByteOrderLittle, lldb_private::EmulateInstruction::eContextPushRegisterOnStack, lldb::eRegisterKindDWARF, error(), GetRegisterInfo(), m_reg_info, nonvolatile_reg_p(), lldb_private::EmulateInstruction::ReadRegister(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteMemory().
Referenced by GetOpcodeForInstruction().
Emulate_SWSP()
bool EmulateInstructionMIPS::Emulate_SWSP (llvm::MCInst & insn) protected
Definition at line 1484 of file EmulateInstructionMIPS.cpp.
References lldb_private::RegisterInfo::byte_size, lldb_private::RegisterInfo::data(), dwarf_bad_mips, dwarf_sp_mips, dwarf_zero_mips, lldb::eByteOrderLittle, lldb_private::EmulateInstruction::eContextInvalid, lldb_private::EmulateInstruction::eContextPushRegisterOnStack, lldb::eRegisterKindDWARF, error(), GetRegisterInfo(), m_reg_info, nonvolatile_reg_p(), lldb_private::EmulateInstruction::ReadRegister(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), lldb_private::EmulateInstruction::Context::type, lldb_private::EmulateInstruction::WriteMemory(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
Referenced by GetOpcodeForInstruction().
EvaluateInstruction()
bool EmulateInstructionMIPS::EvaluateInstruction (uint32_t evaluate_options) override virtual
Implements lldb_private::EmulateInstruction.
Definition at line 1047 of file EmulateInstructionMIPS.cpp.
References EmulateInstructionMIPS::MipsOpcode::callback, dwarf_pc_mips, lldb::eRegisterKindDWARF, lldb_private::DataExtractor::GetByteSize(), lldb_private::DataExtractor::GetDataStart(), GetOpcodeForInstruction(), lldb_private::EmulateInstruction::m_addr, m_alt_disasm, m_disasm, m_insn_info, lldb_private::EmulateInstruction::m_opcode, m_use_alt_disaasm, lldb_private::EmulateInstruction::ReadRegisterUnsigned(), and lldb_private::EmulateInstruction::WriteRegisterUnsigned().
GetOpcodeForInstruction()
EmulateInstructionMIPS::MipsOpcode * EmulateInstructionMIPS::GetOpcodeForInstruction (llvm::StringRef name) static protected
Definition at line 670 of file EmulateInstructionMIPS.cpp.
References Emulate_3D_branch(), Emulate_ADDiu(), Emulate_ADDIUS5(), Emulate_ADDIUSP(), Emulate_B16_MM(), Emulate_BAL(), Emulate_BALC(), Emulate_BC(), Emulate_BC1EQZ(), Emulate_BC1NEZ(), Emulate_Bcond_Link(), Emulate_Bcond_Link_C(), Emulate_BNZB(), Emulate_BNZD(), Emulate_BNZH(), Emulate_BNZV(), Emulate_BNZW(), Emulate_Branch_MM(), Emulate_BXX_2ops(), Emulate_BXX_2ops_C(), Emulate_BXX_3ops(), Emulate_BXX_3ops_C(), Emulate_BZB(), Emulate_BZD(), Emulate_BZH(), Emulate_BZV(), Emulate_BZW(), Emulate_FP_branch(), Emulate_J(), Emulate_JAL(), Emulate_JALR(), Emulate_JALRS(), Emulate_JALRx16_MM(), Emulate_JALx(), Emulate_JIALC(), Emulate_JIC(), Emulate_JR(), Emulate_JRADDIUSP(), Emulate_LDST_Imm(), Emulate_LDST_Reg(), Emulate_LUI(), Emulate_LW(), Emulate_LWM16_32(), Emulate_LWSP(), Emulate_SUBU_ADDU(), Emulate_SW(), Emulate_SWM16_32(), and Emulate_SWSP().
Referenced by EvaluateInstruction().
GetPluginDescriptionStatic()
llvm::StringRef EmulateInstructionMIPS::GetPluginDescriptionStatic () static
Definition at line 194 of file EmulateInstructionMIPS.cpp.
Referenced by Initialize().
GetPluginName()
llvm::StringRef EmulateInstructionMIPS::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 61 of file EmulateInstructionMIPS.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef EmulateInstructionMIPS::GetPluginNameStatic () inline static
Definition at line 39 of file EmulateInstructionMIPS.h.
Referenced by GetPluginName(), and Initialize().
GetRegisterInfo()
std::optional< RegisterInfo > EmulateInstructionMIPS::GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num) override virtual
Implements lldb_private::EmulateInstruction.
Definition at line 587 of file EmulateInstructionMIPS.cpp.
References lldb_private::RegisterInfo::alt_name, lldb_private::RegisterInfo::byte_size, dwarf_config5_mips, dwarf_f31_mips, dwarf_fcsr_mips, dwarf_fir_mips, dwarf_mcsr_mips, dwarf_mir_mips, dwarf_pc_mips, dwarf_r30_mips, dwarf_ra_mips, dwarf_sp_mips, dwarf_sr_mips, dwarf_w0_mips, dwarf_w31_mips, dwarf_zero_mips, lldb::eEncodingUint, lldb::eEncodingVector, lldb::eFormatHex, lldb::eFormatVectorOfUInt8, lldb_private::RegisterInfo::encoding, lldb::eRegisterKindDWARF, lldb::eRegisterKindGeneric, lldb_private::RegisterInfo::format, GetRegisterName(), lldb_private::RegisterInfo::kinds, LLDB_INVALID_REGNUM, LLDB_REGNUM_GENERIC_FLAGS, LLDB_REGNUM_GENERIC_FP, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_RA, LLDB_REGNUM_GENERIC_SP, and lldb_private::RegisterInfo::name.
Referenced by Emulate_ADDiu(), Emulate_ADDIUS5(), Emulate_ADDIUSP(), Emulate_JRADDIUSP(), Emulate_LDST_Imm(), Emulate_LDST_Reg(), Emulate_LW(), Emulate_LWM16_32(), Emulate_LWSP(), Emulate_SUBU_ADDU(), Emulate_SW(), Emulate_SWM16_32(), and Emulate_SWSP().
GetRegisterName()
const char * EmulateInstructionMIPS::GetRegisterName (unsigned reg_num, bool alternate_name) protected
Definition at line 217 of file EmulateInstructionMIPS.cpp.
References dwarf_bad_mips, dwarf_cause_mips, dwarf_config5_mips, dwarf_f0_mips, dwarf_f10_mips, dwarf_f11_mips, dwarf_f12_mips, dwarf_f13_mips, dwarf_f14_mips, dwarf_f15_mips, dwarf_f16_mips, dwarf_f17_mips, dwarf_f18_mips, dwarf_f19_mips, dwarf_f1_mips, dwarf_f20_mips, dwarf_f21_mips, dwarf_f22_mips, dwarf_f23_mips, dwarf_f24_mips, dwarf_f25_mips, dwarf_f26_mips, dwarf_f27_mips, dwarf_f28_mips, dwarf_f29_mips, dwarf_f2_mips, dwarf_f30_mips, dwarf_f31_mips, dwarf_f3_mips, dwarf_f4_mips, dwarf_f5_mips, dwarf_f6_mips, dwarf_f7_mips, dwarf_f8_mips, dwarf_f9_mips, dwarf_fcsr_mips, dwarf_fir_mips, dwarf_gp_mips, dwarf_hi_mips, dwarf_lo_mips, dwarf_mcsr_mips, dwarf_mir_mips, dwarf_pc_mips, dwarf_r10_mips, dwarf_r11_mips, dwarf_r12_mips, dwarf_r13_mips, dwarf_r14_mips, dwarf_r15_mips, dwarf_r16_mips, dwarf_r17_mips, dwarf_r18_mips, dwarf_r19_mips, dwarf_r1_mips, dwarf_r20_mips, dwarf_r21_mips, dwarf_r22_mips, dwarf_r23_mips, dwarf_r24_mips, dwarf_r25_mips, dwarf_r26_mips, dwarf_r27_mips, dwarf_r2_mips, dwarf_r30_mips, dwarf_r3_mips, dwarf_r4_mips, dwarf_r5_mips, dwarf_r6_mips, dwarf_r7_mips, dwarf_r8_mips, dwarf_r9_mips, dwarf_ra_mips, dwarf_sp_mips, dwarf_sr_mips, dwarf_w0_mips, dwarf_w10_mips, dwarf_w11_mips, dwarf_w12_mips, dwarf_w13_mips, dwarf_w14_mips, dwarf_w15_mips, dwarf_w16_mips, dwarf_w17_mips, dwarf_w18_mips, dwarf_w19_mips, dwarf_w1_mips, dwarf_w20_mips, dwarf_w21_mips, dwarf_w22_mips, dwarf_w23_mips, dwarf_w24_mips, dwarf_w25_mips, dwarf_w26_mips, dwarf_w27_mips, dwarf_w28_mips, dwarf_w29_mips, dwarf_w2_mips, dwarf_w30_mips, dwarf_w31_mips, dwarf_w3_mips, dwarf_w4_mips, dwarf_w5_mips, dwarf_w6_mips, dwarf_w7_mips, dwarf_w8_mips, dwarf_w9_mips, and dwarf_zero_mips.
Referenced by GetRegisterInfo().
GetSizeOfInstruction()
uint32_t EmulateInstructionMIPS::GetSizeOfInstruction (lldb_private::DataExtractor & data, uint64_t inst_addr) protected
Definition at line 964 of file EmulateInstructionMIPS.cpp.
References lldb_private::DataExtractor::GetByteSize(), lldb_private::DataExtractor::GetDataStart(), m_alt_disasm, m_disasm, m_insn_info, and m_use_alt_disaasm.
Referenced by SetInstruction().
Initialize()
void EmulateInstructionMIPS::Initialize () static
Definition at line 185 of file EmulateInstructionMIPS.cpp.
References CreateInstance(), GetPluginDescriptionStatic(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
nonvolatile_reg_p()
bool EmulateInstructionMIPS::nonvolatile_reg_p (uint32_t regnum) protected
Definition at line 1148 of file EmulateInstructionMIPS.cpp.
References dwarf_gp_mips, dwarf_r16_mips, dwarf_r17_mips, dwarf_r18_mips, dwarf_r19_mips, dwarf_r20_mips, dwarf_r21_mips, dwarf_r22_mips, dwarf_r23_mips, dwarf_r30_mips, dwarf_ra_mips, and dwarf_sp_mips.
Referenced by Emulate_LW(), Emulate_LWM16_32(), Emulate_LWSP(), Emulate_SW(), Emulate_SWM16_32(), and Emulate_SWSP().
ReadInstruction()
bool EmulateInstructionMIPS::ReadInstruction () override virtual
Implements lldb_private::EmulateInstruction.
Definition at line 1030 of file EmulateInstructionMIPS.cpp.
References lldb_private::EmulateInstruction::eContextReadOpcode, lldb::eRegisterKindGeneric, lldb_private::EmulateInstruction::GetByteOrder(), LLDB_INVALID_ADDRESS, LLDB_REGNUM_GENERIC_PC, lldb_private::EmulateInstruction::m_addr, lldb_private::EmulateInstruction::m_opcode, lldb_private::EmulateInstruction::ReadMemoryUnsigned(), lldb_private::EmulateInstruction::ReadRegisterUnsigned(), lldb_private::EmulateInstruction::Context::SetNoArgs(), and lldb_private::EmulateInstruction::Context::type.
SetInstruction()
bool EmulateInstructionMIPS::SetInstruction (const lldb_private::Opcode & insn_opcode, const lldb_private::Address & inst_addr, lldb_private::Target * target) override virtual
Reimplemented from lldb_private::EmulateInstruction.
Definition at line 984 of file EmulateInstructionMIPS.cpp.
References lldb_private::eCodeAlternateISA, error(), lldb_private::EmulateInstruction::GetAddressByteSize(), lldb_private::Address::GetAddressClass(), lldb_private::EmulateInstruction::GetByteOrder(), lldb_private::Opcode::GetByteSize(), GetSizeOfInstruction(), LLDB_INVALID_ADDRESS, lldb_private::EmulateInstruction::m_addr, m_next_inst_size, m_use_alt_disaasm, lldb_private::Target::ReadMemory(), and lldb_private::EmulateInstruction::SetInstruction().
SetTargetTriple()
bool EmulateInstructionMIPS::SetTargetTriple (const lldb_private::ArchSpec & arch) override virtual
Implements lldb_private::EmulateInstruction.
Definition at line 212 of file EmulateInstructionMIPS.cpp.
References lldb_private::ArchSpec::GetTriple().
SupportsEmulatingInstructionsOfType()
bool EmulateInstructionMIPS::SupportsEmulatingInstructionsOfType (lldb_private::InstructionType inst_type) inline override virtual
Implements lldb_private::EmulateInstruction.
Definition at line 67 of file EmulateInstructionMIPS.h.
References SupportsEmulatingInstructionsOfTypeStatic().
SupportsEmulatingInstructionsOfTypeStatic()
bool EmulateInstructionMIPS::SupportsEmulatingInstructionsOfTypeStatic (lldb_private::InstructionType inst_type) inline static
Definition at line 47 of file EmulateInstructionMIPS.h.
References lldb_private::eInstructionTypeAll, lldb_private::eInstructionTypeAny, lldb_private::eInstructionTypePCModifying, and lldb_private::eInstructionTypePrologueEpilogue.
Referenced by CreateInstance(), and SupportsEmulatingInstructionsOfType().
Terminate()
void EmulateInstructionMIPS::Terminate () static
Definition at line 190 of file EmulateInstructionMIPS.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
TestEmulation()
bool EmulateInstructionMIPS::TestEmulation (lldb_private::Stream & out_stream, lldb_private::ArchSpec & arch, lldb_private::OptionValueDictionary * test_data) inline override virtual
Implements lldb_private::EmulateInstruction.
Definition at line 80 of file EmulateInstructionMIPS.h.
Member Data Documentation
m_alt_disasm
std::unique_ptr<llvm::MCDisassembler> EmulateInstructionMIPS::m_alt_disasm private
Definition at line 211 of file EmulateInstructionMIPS.h.
Referenced by EmulateInstructionMIPS(), EvaluateInstruction(), and GetSizeOfInstruction().
m_alt_subtype_info
std::unique_ptr<llvm::MCSubtargetInfo> EmulateInstructionMIPS::m_alt_subtype_info private
Definition at line 213 of file EmulateInstructionMIPS.h.
Referenced by EmulateInstructionMIPS().
m_asm_info
std::unique_ptr<llvm::MCAsmInfo> EmulateInstructionMIPS::m_asm_info private
Definition at line 216 of file EmulateInstructionMIPS.h.
Referenced by EmulateInstructionMIPS().
m_context
std::unique_ptr<llvm::MCContext> EmulateInstructionMIPS::m_context private
Definition at line 217 of file EmulateInstructionMIPS.h.
Referenced by EmulateInstructionMIPS().
m_disasm
std::unique_ptr<llvm::MCDisassembler> EmulateInstructionMIPS::m_disasm private
Definition at line 210 of file EmulateInstructionMIPS.h.
Referenced by EmulateInstructionMIPS(), EvaluateInstruction(), and GetSizeOfInstruction().
m_insn_info
std::unique_ptr<llvm::MCInstrInfo> EmulateInstructionMIPS::m_insn_info private
Definition at line 218 of file EmulateInstructionMIPS.h.
Referenced by Emulate_3D_branch(), Emulate_B16_MM(), Emulate_Bcond_Link(), Emulate_Bcond_Link_C(), Emulate_Branch_MM(), Emulate_BXX_2ops(), Emulate_BXX_2ops_C(), Emulate_BXX_3ops(), Emulate_BXX_3ops_C(), Emulate_FP_branch(), Emulate_JALRx16_MM(), Emulate_JALx(), Emulate_SUBU_ADDU(), EmulateInstructionMIPS(), EvaluateInstruction(), and GetSizeOfInstruction().
m_mc_options
llvm::MCTargetOptions EmulateInstructionMIPS::m_mc_options private
Definition at line 215 of file EmulateInstructionMIPS.h.
Referenced by EmulateInstructionMIPS().
m_next_inst_size
uint32_t EmulateInstructionMIPS::m_next_inst_size private
Definition at line 219 of file EmulateInstructionMIPS.h.
Referenced by Emulate_Branch_MM(), EmulateInstructionMIPS(), and SetInstruction().
m_reg_info
std::unique_ptr<llvm::MCRegisterInfo> EmulateInstructionMIPS::m_reg_info private
Definition at line 214 of file EmulateInstructionMIPS.h.
Referenced by Emulate_3D_branch(), Emulate_ADDiu(), Emulate_ADDIUS5(), Emulate_BC1EQZ(), Emulate_BC1NEZ(), Emulate_Bcond_Link(), Emulate_Bcond_Link_C(), Emulate_Branch_MM(), Emulate_BXX_2ops(), Emulate_BXX_2ops_C(), Emulate_BXX_3ops(), Emulate_BXX_3ops_C(), Emulate_FP_branch(), Emulate_JALR(), Emulate_JALRS(), Emulate_JALRx16_MM(), Emulate_JIALC(), Emulate_JIC(), Emulate_JR(), Emulate_LDST_Imm(), Emulate_LDST_Reg(), Emulate_LUI(), Emulate_LW(), Emulate_LWM16_32(), Emulate_LWSP(), Emulate_MSA_Branch_DF(), Emulate_MSA_Branch_V(), Emulate_SUBU_ADDU(), Emulate_SW(), Emulate_SWM16_32(), Emulate_SWSP(), and EmulateInstructionMIPS().
m_subtype_info
std::unique_ptr<llvm::MCSubtargetInfo> EmulateInstructionMIPS::m_subtype_info private
Definition at line 212 of file EmulateInstructionMIPS.h.
Referenced by EmulateInstructionMIPS().
m_use_alt_disaasm
bool EmulateInstructionMIPS::m_use_alt_disaasm private
Definition at line 220 of file EmulateInstructionMIPS.h.
Referenced by EmulateInstructionMIPS(), EvaluateInstruction(), GetSizeOfInstruction(), and SetInstruction().
The documentation for this class was generated from the following files:
EmulateInstructionMIPS.h
EmulateInstructionMIPS.cpp