LLDB: lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd Class Reference
lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd Class Reference
Classes
struct DictionaryItemDescriptor
Public Member Functions
NSConstantDictionarySyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
llvm::Expected< uint32_t > CalculateNumChildren () override
lldb::ValueObjectSP GetChildAtIndex (uint32_t idx) override
lldb::ChildCacheState Update () override
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
llvm::Expected< size_t > GetIndexOfChildWithName (ConstString name) override
Public Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
SyntheticChildrenFrontEnd (ValueObject &backend)
virtual ~SyntheticChildrenFrontEnd ()=default
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max)
uint32_t CalculateNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
virtual bool MightHaveChildren ()
virtual lldb::ValueObjectSP GetSyntheticValue ()
virtual ConstString GetSyntheticTypeName ()
Private Attributes
ExecutionContextRef m_exe_ctx_ref
CompilerType m_pair_type
uint8_t m_ptr_size = 8
lldb::ByteOrder m_order = lldb::eByteOrderInvalid
unsigned int m_size = 0
lldb::addr_t m_keys_ptr = LLDB_INVALID_ADDRESS
lldb::addr_t m_objects_ptr = LLDB_INVALID_ADDRESS
std::vector< DictionaryItemDescriptor > m_children
Additional Inherited Members
Public Types inherited from lldb_private::SyntheticChildrenFrontEnd
typedef std::shared_ptr< SyntheticChildrenFrontEnd > SharedPointer
typedef std::unique_ptr< SyntheticChildrenFrontEnd > UniquePointer
Protected Member Functions inherited from lldb_private::SyntheticChildrenFrontEnd
lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
Protected Attributes inherited from lldb_private::SyntheticChildrenFrontEnd
ValueObject & m_backend
Detailed Description
Definition at line 142 of file NSDictionary.cpp.
Constructor & Destructor Documentation
NSConstantDictionarySyntheticFrontEnd()
lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::NSConstantDictionarySyntheticFrontEnd (lldb::ValueObjectSP valobj_sp)
Definition at line 859 of file NSDictionary.cpp.
References lldb_private::SyntheticChildrenFrontEnd::SyntheticChildrenFrontEnd().
Member Function Documentation
CalculateNumChildren()
llvm::Expected< uint32_t > lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::CalculateNumChildren () override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 878 of file NSDictionary.cpp.
References m_size.
GetChildAtIndex()
lldb::ValueObjectSP lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::GetChildAtIndex (uint32_t idx) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 912 of file NSDictionary.cpp.
References lldb_private::SyntheticChildrenFrontEnd::CalculateNumChildrenIgnoringErrors(), lldb_private::SyntheticChildrenFrontEnd::CreateValueObjectFromData(), error(), GetLLDBNSPairType(), lldb_private::StreamString::GetString(), lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::DictionaryItemDescriptor::key_ptr, lldb_private::SyntheticChildrenFrontEnd::m_backend, m_children, m_exe_ctx_ref, m_keys_ptr, m_objects_ptr, m_order, m_pair_type, m_ptr_size, lldb_private::Stream::Printf(), lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::DictionaryItemDescriptor::val_ptr, and lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::DictionaryItemDescriptor::valobj_sp.
GetIndexOfChildWithName()
llvm::Expected< size_t > lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::GetIndexOfChildWithName (ConstString name) override virtual
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 864 of file NSDictionary.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::SyntheticChildrenFrontEnd::CalculateNumChildrenIgnoringErrors(), and lldb_private::formatters::ExtractIndexFromString().
Update()
lldb::ChildCacheState lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::Update () override virtual
This function is assumed to always succeed and if it fails, the front-end should know to deal with it in the correct way (most probably, by refusing to return any children).
The return value of Update should actually be interpreted as "ValueObjectSynthetic cache is good/bad". If this function returns lldb::ChildCacheState::eReuse, ValueObjectSynthetic is allowed to use the children it fetched previously and cached. Otherwise, ValueObjectSynthetic must throw away its cache, and query again for children.
Implements lldb_private::SyntheticChildrenFrontEnd.
Definition at line 884 of file NSDictionary.cpp.
References lldb::eRefetch, lldb::eReuse, error(), lldb_private::SyntheticChildrenFrontEnd::m_backend, m_exe_ctx_ref, m_keys_ptr, m_objects_ptr, m_order, m_ptr_size, and m_size.
Member Data Documentation
m_children
std::vector<DictionaryItemDescriptor> lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::m_children private
Definition at line 169 of file NSDictionary.cpp.
Referenced by GetChildAtIndex().
m_exe_ctx_ref
ExecutionContextRef lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::m_exe_ctx_ref private
Definition at line 155 of file NSDictionary.cpp.
Referenced by GetChildAtIndex(), and Update().
m_keys_ptr
lldb::addr_t lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::m_keys_ptr = LLDB_INVALID_ADDRESS private
Definition at line 160 of file NSDictionary.cpp.
Referenced by GetChildAtIndex(), and Update().
m_objects_ptr
lldb::addr_t lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::m_objects_ptr = LLDB_INVALID_ADDRESS private
Definition at line 161 of file NSDictionary.cpp.
Referenced by GetChildAtIndex(), and Update().
m_order
lldb::ByteOrder lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::m_order = lldb::eByteOrderInvalid private
Definition at line 158 of file NSDictionary.cpp.
Referenced by GetChildAtIndex(), and Update().
m_pair_type
CompilerType lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::m_pair_type private
Definition at line 156 of file NSDictionary.cpp.
Referenced by GetChildAtIndex().
m_ptr_size
uint8_t lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::m_ptr_size = 8 private
Definition at line 157 of file NSDictionary.cpp.
Referenced by GetChildAtIndex(), and Update().
m_size
unsigned int lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::m_size = 0 private
Definition at line 159 of file NSDictionary.cpp.
Referenced by CalculateNumChildren(), and Update().
The documentation for this class was generated from the following file:
NSDictionary.cpp