LLDB: lldb::SBQueueItem Class Reference
lldb::SBQueueItem Class Reference
#include <SBQueueItem.h>
Public Member Functions
SBQueueItem ()
~SBQueueItem ()
operator bool () const
bool IsValid () const
void Clear ()
lldb::QueueItemKind GetKind () const
void SetKind (lldb::QueueItemKind kind)
lldb::SBAddress GetAddress () const
void SetAddress (lldb::SBAddress addr)
SBThread GetExtendedBacktraceThread (const char *type)
Protected Member Functions
SBQueueItem (const lldb::QueueItemSP &queue_item_sp)
void SetQueueItem (const lldb::QueueItemSP &queue_item_sp)
Private Attributes
lldb::QueueItemSP m_queue_item_sp
Friends
class lldb_private::QueueImpl
Detailed Description
Definition at line 21 of file SBQueueItem.h.
Constructor & Destructor Documentation
SBQueueItem() [1/2]
SBQueueItem::SBQueueItem ()
Definition at line 24 of file SBQueueItem.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb_private::QueueImpl.
~SBQueueItem()
SBQueueItem::~SBQueueItem ()
Definition at line 32 of file SBQueueItem.cpp.
References m_queue_item_sp.
SBQueueItem() [2/2]
SBQueueItem::SBQueueItem (const lldb::QueueItemSP & queue_item_sp) protected
Definition at line 26 of file SBQueueItem.cpp.
References LLDB_INSTRUMENT_VA, and m_queue_item_sp.
Member Function Documentation
Clear()
void SBQueueItem::Clear ()
Definition at line 44 of file SBQueueItem.cpp.
References LLDB_INSTRUMENT_VA, and m_queue_item_sp.
GetAddress()
SBAddress SBQueueItem::GetAddress () const
Definition at line 74 of file SBQueueItem.cpp.
References LLDB_INSTRUMENT_VA, m_queue_item_sp, and lldb::SBAddress::SetAddress().
GetExtendedBacktraceThread()
SBThread SBQueueItem::GetExtendedBacktraceThread (const char * type)
Definition at line 92 of file SBQueueItem.cpp.
References LLDB_INSTRUMENT_VA, m_queue_item_sp, lldb::SBThread::SetThread(), and lldb_private::ProcessRunLock::ProcessRunLocker::TryLock().
GetKind()
lldb::QueueItemKind SBQueueItem::GetKind () const
Definition at line 56 of file SBQueueItem.cpp.
References lldb::eQueueItemKindUnknown, LLDB_INSTRUMENT_VA, and m_queue_item_sp.
IsValid()
bool SBQueueItem::IsValid () const
Definition at line 34 of file SBQueueItem.cpp.
References LLDB_INSTRUMENT_VA.
operator bool()
SBQueueItem::operator bool () const explicit
Definition at line 38 of file SBQueueItem.cpp.
References LLDB_INSTRUMENT_VA, and m_queue_item_sp.
SetAddress()
void SBQueueItem::SetAddress (lldb::SBAddress addr)
Definition at line 84 of file SBQueueItem.cpp.
References LLDB_INSTRUMENT_VA, m_queue_item_sp, and lldb::SBAddress::ref().
SetKind()
void SBQueueItem::SetKind (lldb::QueueItemKind kind)
Definition at line 66 of file SBQueueItem.cpp.
References LLDB_INSTRUMENT_VA, and m_queue_item_sp.
SetQueueItem()
void SBQueueItem::SetQueueItem (const lldb::QueueItemSP & queue_item_sp) protected
Definition at line 50 of file SBQueueItem.cpp.
References LLDB_INSTRUMENT_VA, and m_queue_item_sp.
Referenced by lldb_private::QueueImpl::GetPendingItemAtIndex(), and lldb_private::QueueImpl.
Friends And Related Symbol Documentation
lldb_private::QueueImpl
friend class lldb_private::QueueImpl friend
Definition at line 44 of file SBQueueItem.h.
References SBQueueItem(), and SetQueueItem().
Member Data Documentation
m_queue_item_sp
lldb::QueueItemSP lldb::SBQueueItem::m_queue_item_sp private
Definition at line 51 of file SBQueueItem.h.
Referenced by Clear(), GetAddress(), GetExtendedBacktraceThread(), GetKind(), operator bool(), SBQueueItem(), SetAddress(), SetKind(), SetQueueItem(), and ~SBQueueItem().
The documentation for this class was generated from the following files:
SBQueueItem.h
SBQueueItem.cpp