LLDB: lldb_private::dil::DILParser Class Reference
lldb_private::dil::DILParser Class Reference
Pure recursive descent parser for C++ like expressions.
#include <DILParser.h>
Public Member Functions
~DILParser ()=default
bool UseSynthetic ()
bool UseFragileIvar ()
bool CheckPtrVsMember ()
lldb::DynamicValueType UseDynamic ()
Static Public Member Functions
static llvm::Expected< ASTNodeUP > Parse (llvm::StringRef dil_input_expr, DILLexer lexer, std::shared_ptr< StackFrame > frame_sp, lldb::DynamicValueType use_dynamic, bool use_synthetic, bool fragile_ivar, bool check_ptr_vs_member)
Private Member Functions
DILParser (llvm::StringRef dil_input_expr, DILLexer lexer, std::shared_ptr< StackFrame > frame_sp, lldb::DynamicValueType use_dynamic, bool use_synthetic, bool fragile_ivar, bool check_ptr_vs_member, llvm::Error &error)
ASTNodeUP Run ()
ASTNodeUP ParseExpression ()
ASTNodeUP ParseUnaryExpression ()
ASTNodeUP ParsePostfixExpression ()
ASTNodeUP ParsePrimaryExpression ()
std::string ParseNestedNameSpecifier ()
std::string ParseIdExpression ()
std::string ParseUnqualifiedId ()
ASTNodeUP ParseNumericLiteral ()
ASTNodeUP ParseIntegerLiteral ()
ASTNodeUP ParseFloatingPointLiteral ()
ASTNodeUP ParseBooleanLiteral ()
ASTNodeUP ParseCastExpression ()
std::optional< CompilerType > ParseBuiltinType ()
std::optional< CompilerType > ParseTypeId ()
void ParseTypeSpecifierSeq (std::string &type_name)
std::optional< std::string > ParseTypeSpecifier ()
std::optional< std::string > ParseTypeName ()
CompilerType ResolveTypeDeclarators (CompilerType type, const std::vector< Token > &ptr_operators)
void BailOut (const std::string &error, uint32_t loc, uint16_t err_len)
void Expect (Token::Kind kind)
void ExpectOneOf (std::vector< Token::Kind > kinds_vec)
void TentativeParsingRollback (uint32_t saved_idx)
Token CurToken ()
Private Attributes
std::shared_ptr< StackFrame > m_ctx_scope
llvm::StringRef m_input_expr
DILLexer m_dil_lexer
llvm::Error & m_error
lldb::DynamicValueType m_use_dynamic
bool m_use_synthetic
bool m_fragile_ivar
bool m_check_ptr_vs_member
Detailed Description
Pure recursive descent parser for C++ like expressions.
EBNF grammar for the parser is described in lldb/docs/dil-expr-lang.ebnf
Definition at line 68 of file DILParser.h.
Constructor & Destructor Documentation
~DILParser()
lldb_private::dil::DILParser::~DILParser () default
DILParser()
lldb_private::dil::DILParser::DILParser (llvm::StringRef dil_input_expr, DILLexer lexer, std::shared_ptr< StackFrame > frame_sp, lldb::DynamicValueType use_dynamic, bool use_synthetic, bool fragile_ivar, bool check_ptr_vs_member, llvm::Error & error) explicit private
Definition at line 107 of file DILParser.cpp.
References error(), m_check_ptr_vs_member, m_ctx_scope, m_dil_lexer, m_error, m_fragile_ivar, m_input_expr, m_use_dynamic, and m_use_synthetic.
Referenced by Parse().
Member Function Documentation
BailOut()
void lldb_private::dil::DILParser::BailOut (const std::string & error, uint32_t loc, uint16_t err_len) private
Definition at line 664 of file DILParser.cpp.
References error(), m_dil_lexer, m_error, and m_input_expr.
Referenced by Expect(), ExpectOneOf(), ParseNestedNameSpecifier(), ParseNumericLiteral(), ParsePostfixExpression(), ParsePrimaryExpression(), and ResolveTypeDeclarators().
CheckPtrVsMember()
bool lldb_private::dil::DILParser::CheckPtrVsMember () inline
Definition at line 83 of file DILParser.h.
References m_check_ptr_vs_member.
CurToken()
Token lldb_private::dil::DILParser::CurToken () inline private
Definition at line 131 of file DILParser.h.
References m_dil_lexer.
Referenced by Expect(), ExpectOneOf(), ParseBooleanLiteral(), ParseBuiltinType(), ParseCastExpression(), ParseFloatingPointLiteral(), ParseIdExpression(), ParseIntegerLiteral(), ParseNestedNameSpecifier(), ParseNumericLiteral(), ParsePostfixExpression(), ParsePrimaryExpression(), ParseTypeId(), ParseTypeName(), ParseTypeSpecifier(), ParseUnaryExpression(), ParseUnqualifiedId(), and ResolveTypeDeclarators().
Expect()
void lldb_private::dil::DILParser::Expect (Token::Kind kind) private
Definition at line 740 of file DILParser.cpp.
References BailOut(), and CurToken().
Referenced by ParseCastExpression(), ParseIdExpression(), ParseNestedNameSpecifier(), ParsePostfixExpression(), ParsePrimaryExpression(), ParseUnqualifiedId(), and Run().
ExpectOneOf()
void lldb_private::dil::DILParser::ExpectOneOf (std::vector< Token::Kind > kinds_vec) private
Definition at line 747 of file DILParser.cpp.
References BailOut(), and CurToken().
Referenced by ParseBooleanLiteral().
Parse()
llvm::Expected< ASTNodeUP > lldb_private::dil::DILParser::Parse (llvm::StringRef dil_input_expr, DILLexer lexer, std::shared_ptr< StackFrame > frame_sp, lldb::DynamicValueType use_dynamic, bool use_synthetic, bool fragile_ivar, bool check_ptr_vs_member) static
Definition at line 90 of file DILParser.cpp.
References DILParser(), error(), and Run().
Referenced by lldb_private::StackFrame::DILGetValueForVariableExpressionPath().
ParseBooleanLiteral()
ASTNodeUP lldb_private::dil::DILParser::ParseBooleanLiteral () private
Definition at line 656 of file DILParser.cpp.
References CurToken(), ExpectOneOf(), lldb_private::dil::Token::GetLocation(), lldb_private::dil::Token::Is(), lldb_private::dil::Token::kw_false, lldb_private::dil::Token::kw_true, and m_dil_lexer.
Referenced by ParsePrimaryExpression().
ParseBuiltinType()
std::optional< CompilerType > lldb_private::dil::DILParser::ParseBuiltinType () private
Definition at line 440 of file DILParser.cpp.
References CurToken(), GetKind(), lldb_private::dil::Token::identifier, m_ctx_scope, m_dil_lexer, and TentativeParsingRollback().
Referenced by ParseTypeId().
ParseCastExpression()
ASTNodeUP lldb_private::dil::DILParser::ParseCastExpression () private
Definition at line 138 of file DILParser.cpp.
References CurToken(), lldb_private::dil::eNone, Expect(), lldb_private::dil::Token::GetLocation(), lldb_private::dil::Token::l_paren, m_dil_lexer, ParseCastExpression(), ParseTypeId(), ParseUnaryExpression(), lldb_private::dil::Token::r_paren, and TentativeParsingRollback().
Referenced by ParseCastExpression(), ParseExpression(), and ParseUnaryExpression().
ParseExpression()
ASTNodeUP lldb_private::dil::DILParser::ParseExpression () private
Definition at line 130 of file DILParser.cpp.
References ParseCastExpression().
Referenced by ParsePostfixExpression(), ParsePrimaryExpression(), and Run().
ParseFloatingPointLiteral()
ASTNodeUP lldb_private::dil::DILParser::ParseFloatingPointLiteral () private
Definition at line 724 of file DILParser.cpp.
References CurToken(), lldb_private::dil::Token::GetLocation(), and lldb_private::dil::Token::GetSpelling().
Referenced by ParseNumericLiteral().
ParseIdExpression()
std::string lldb_private::dil::DILParser::ParseIdExpression () private
Definition at line 564 of file DILParser.cpp.
References lldb_private::dil::Token::coloncolon, CurToken(), Expect(), lldb_private::dil::Token::GetSpelling(), lldb_private::dil::Token::identifier, m_dil_lexer, ParseNestedNameSpecifier(), and ParseUnqualifiedId().
Referenced by ParsePostfixExpression(), and ParsePrimaryExpression().
ParseIntegerLiteral()
ASTNodeUP lldb_private::dil::DILParser::ParseIntegerLiteral () private
Definition at line 699 of file DILParser.cpp.
References CurToken(), lldb_private::dil::Token::GetLocation(), lldb_private::dil::Token::GetSpelling(), lldb_private::dil::Long, lldb_private::dil::LongLong, and lldb_private::dil::None.
Referenced by ParseNumericLiteral().
ParseNestedNameSpecifier()
std::string lldb_private::dil::DILParser::ParseNestedNameSpecifier () private
Definition at line 319 of file DILParser.cpp.
References BailOut(), lldb_private::dil::Token::coloncolon, CurToken(), Expect(), GetKind(), lldb_private::dil::Token::GetSpelling(), lldb_private::dil::Token::identifier, lldb_private::dil::Token::l_paren, m_dil_lexer, ParseNestedNameSpecifier(), and lldb_private::dil::Token::r_paren.
Referenced by ParseIdExpression(), ParseNestedNameSpecifier(), and ParseTypeSpecifier().
ParseNumericLiteral()
ASTNodeUP lldb_private::dil::DILParser::ParseNumericLiteral () private
Definition at line 683 of file DILParser.cpp.
References BailOut(), CurToken(), lldb_private::dil::eErrorNode, lldb_private::dil::Token::integer_constant, m_dil_lexer, ParseFloatingPointLiteral(), and ParseIntegerLiteral().
Referenced by ParsePrimaryExpression().
ParsePostfixExpression()
ASTNodeUP lldb_private::dil::DILParser::ParsePostfixExpression () private
Definition at line 229 of file DILParser.cpp.
References lldb_private::dil::Token::arrow, BailOut(), lldb_private::dil::Token::colon, CurToken(), Expect(), GetKind(), lldb_private::dil::Token::GetKind(), lldb_private::dil::Token::GetLocation(), lldb_private::dil::Token::l_square, m_dil_lexer, lldb_private::dil::Token::minus, ParseExpression(), ParseIdExpression(), ParsePrimaryExpression(), lldb_private::dil::Token::period, and lldb_private::dil::Token::r_square.
Referenced by ParseUnaryExpression().
ParsePrimaryExpression()
ASTNodeUP lldb_private::dil::DILParser::ParsePrimaryExpression () private
Definition at line 284 of file DILParser.cpp.
References BailOut(), lldb_private::dil::Token::coloncolon, CurToken(), Expect(), lldb_private::dil::Token::float_constant, lldb_private::dil::Token::GetLocation(), lldb_private::dil::Token::identifier, lldb_private::dil::Token::integer_constant, lldb_private::dil::Token::kw_false, lldb_private::dil::Token::kw_true, lldb_private::dil::Token::l_paren, m_dil_lexer, ParseBooleanLiteral(), ParseExpression(), ParseIdExpression(), ParseNumericLiteral(), and lldb_private::dil::Token::r_paren.
Referenced by ParsePostfixExpression().
ParseTypeId()
std::optional< CompilerType > lldb_private::dil::DILParser::ParseTypeId () private
Definition at line 386 of file DILParser.cpp.
References lldb_private::dil::Token::amp, CurToken(), lldb_private::CompilerType::IsValid(), lldb_private::dil::LookupGlobalIdentifier(), lldb_private::dil::LookupIdentifier(), m_ctx_scope, m_dil_lexer, m_use_dynamic, ParseBuiltinType(), ParseTypeSpecifierSeq(), lldb_private::dil::ResolveTypeByName(), ResolveTypeDeclarators(), and lldb_private::dil::Token::star.
Referenced by ParseCastExpression().
ParseTypeName()
std::optional< std::string > lldb_private::dil::DILParser::ParseTypeName () private
Definition at line 538 of file DILParser.cpp.
References CurToken(), lldb_private::dil::Token::GetSpelling(), lldb_private::dil::Token::identifier, and m_dil_lexer.
Referenced by ParseTypeSpecifier().
ParseTypeSpecifier()
std::optional< std::string > lldb_private::dil::DILParser::ParseTypeSpecifier () private
Definition at line 490 of file DILParser.cpp.
References lldb_private::dil::Token::coloncolon, CurToken(), m_dil_lexer, ParseNestedNameSpecifier(), and ParseTypeName().
Referenced by ParseTypeSpecifierSeq().
ParseTypeSpecifierSeq()
void lldb_private::dil::DILParser::ParseTypeSpecifierSeq (std::string & type_name) private
Definition at line 474 of file DILParser.cpp.
References ParseTypeSpecifier().
Referenced by ParseTypeId().
ParseUnaryExpression()
ASTNodeUP lldb_private::dil::DILParser::ParseUnaryExpression () private
Definition at line 192 of file DILParser.cpp.
References lldb_private::dil::AddrOf, lldb_private::dil::Token::amp, CurToken(), lldb_private::dil::Deref, lldb_private::dil::Token::GetKind(), lldb_private::dil::Token::GetLocation(), m_dil_lexer, lldb_private::dil::Minus, lldb_private::dil::Token::minus, ParseCastExpression(), ParsePostfixExpression(), lldb_private::dil::Plus, lldb_private::dil::Token::plus, and lldb_private::dil::Token::star.
Referenced by ParseCastExpression().
ParseUnqualifiedId()
std::string lldb_private::dil::DILParser::ParseUnqualifiedId () private
Definition at line 609 of file DILParser.cpp.
References CurToken(), Expect(), lldb_private::dil::Token::GetSpelling(), lldb_private::dil::Token::identifier, and m_dil_lexer.
Referenced by ParseIdExpression().
ResolveTypeDeclarators()
CompilerType lldb_private::dil::DILParser::ResolveTypeDeclarators (CompilerType type, const std::vector< Token > & ptr_operators) private
Definition at line 617 of file DILParser.cpp.
References lldb_private::dil::Token::amp, BailOut(), CurToken(), lldb_private::CompilerType::GetLValueReferenceType(), lldb_private::CompilerType::GetPointerType(), lldb_private::CompilerType::IsReferenceType(), lldb_private::dil::Token::star, and lldb_private::CompilerType::TypeDescription().
Referenced by ParseTypeId().
Run()
ASTNodeUP lldb_private::dil::DILParser::Run () private
Definition at line 117 of file DILParser.cpp.
References lldb_private::dil::Token::eof, Expect(), and ParseExpression().
Referenced by Parse().
TentativeParsingRollback()
void lldb_private::dil::DILParser::TentativeParsingRollback (uint32_t saved_idx) inline private
Definition at line 125 of file DILParser.h.
References m_dil_lexer, and m_error.
Referenced by ParseBuiltinType(), and ParseCastExpression().
UseDynamic()
lldb::DynamicValueType lldb_private::dil::DILParser::UseDynamic () inline
Definition at line 85 of file DILParser.h.
References m_use_dynamic.
UseFragileIvar()
bool lldb_private::dil::DILParser::UseFragileIvar () inline
Definition at line 81 of file DILParser.h.
References m_fragile_ivar.
UseSynthetic()
bool lldb_private::dil::DILParser::UseSynthetic () inline
Definition at line 79 of file DILParser.h.
References m_use_synthetic.
Member Data Documentation
m_check_ptr_vs_member
bool lldb_private::dil::DILParser::m_check_ptr_vs_member private
Definition at line 148 of file DILParser.h.
Referenced by CheckPtrVsMember(), and DILParser().
m_ctx_scope
std::shared_ptr<StackFrame> lldb_private::dil::DILParser::m_ctx_scope private
Definition at line 136 of file DILParser.h.
Referenced by DILParser(), ParseBuiltinType(), and ParseTypeId().
m_dil_lexer
DILLexer lldb_private::dil::DILParser::m_dil_lexer private
Definition at line 140 of file DILParser.h.
Referenced by BailOut(), CurToken(), DILParser(), ParseBooleanLiteral(), ParseBuiltinType(), ParseCastExpression(), ParseIdExpression(), ParseNestedNameSpecifier(), ParseNumericLiteral(), ParsePostfixExpression(), ParsePrimaryExpression(), ParseTypeId(), ParseTypeName(), ParseTypeSpecifier(), ParseUnaryExpression(), ParseUnqualifiedId(), and TentativeParsingRollback().
m_error
llvm::Error& lldb_private::dil::DILParser::m_error private
Definition at line 143 of file DILParser.h.
Referenced by BailOut(), DILParser(), and TentativeParsingRollback().
m_fragile_ivar
bool lldb_private::dil::DILParser::m_fragile_ivar private
Definition at line 147 of file DILParser.h.
Referenced by DILParser(), and UseFragileIvar().
m_input_expr
llvm::StringRef lldb_private::dil::DILParser::m_input_expr private
Definition at line 138 of file DILParser.h.
Referenced by BailOut(), and DILParser().
m_use_dynamic
lldb::DynamicValueType lldb_private::dil::DILParser::m_use_dynamic private
Definition at line 145 of file DILParser.h.
Referenced by DILParser(), ParseTypeId(), and UseDynamic().
m_use_synthetic
bool lldb_private::dil::DILParser::m_use_synthetic private
Definition at line 146 of file DILParser.h.
Referenced by DILParser(), and UseSynthetic().
The documentation for this class was generated from the following files:
DILParser.h
DILParser.cpp