LLDB: lldb_private::OptionValueArray Class Reference
lldb_private::OptionValueArray Class Reference
#include <OptionValueArray.h>
Public Member Functions
OptionValueArray (uint32_t type_mask=UINT32_MAX, bool raw_value_dump=false)
~OptionValueArray () override=default
OptionValue::Type GetType () const override
void DumpValue (const ExecutionContext *exe_ctx, Stream &strm, uint32_t dump_mask) override
llvm::json::Value ToJSON (const ExecutionContext *exe_ctx) const override
Status SetValueFromString (llvm::StringRef value, VarSetOperationType op=eVarSetOperationAssign) override
void Clear () override
lldb::OptionValueSP DeepCopy (const lldb::OptionValueSP &new_parent) const override
bool IsAggregateValue () const override
lldb::OptionValueSP GetSubValue (const ExecutionContext *exe_ctx, llvm::StringRef name, Status &error) const override
size_t GetSize () const
lldb::OptionValueSP operator[] (size_t idx) const
lldb::OptionValueSP GetValueAtIndex (size_t idx) const
bool AppendValue (const lldb::OptionValueSP &value_sp)
bool InsertValue (size_t idx, const lldb::OptionValueSP &value_sp)
bool ReplaceValue (size_t idx, const lldb::OptionValueSP &value_sp)
bool DeleteValue (size_t idx)
size_t GetArgs (Args &args) const
Status SetArgs (const Args &args, VarSetOperationType op)
Public Member Functions inherited from lldb_private::Cloneable< OptionValueArray, OptionValue >
std::shared_ptr< typename OptionValue::TopmostBase > Clone () const override
Public Member Functions inherited from lldb_private::OptionValue
OptionValue ()=default
virtual ~OptionValue ()=default
OptionValue (const OptionValue &other)
OptionValue & operator= (const OptionValue &other)
virtual bool ValueIsTransparent () const
virtual const char * GetTypeAsCString () const
virtual void AutoComplete (CommandInterpreter &interpreter, CompletionRequest &request)
virtual Status SetSubValue (const ExecutionContext *exe_ctx, VarSetOperationType op, llvm::StringRef name, llvm::StringRef value)
virtual llvm::StringRef GetName () const
virtual bool DumpQualifiedName (Stream &strm) const
uint32_t GetTypeAsMask ()
OptionValueArch * GetAsArch ()
const OptionValueArch * GetAsArch () const
OptionValueArray * GetAsArray ()
const OptionValueArray * GetAsArray () const
OptionValueArgs * GetAsArgs ()
const OptionValueArgs * GetAsArgs () const
OptionValueBoolean * GetAsBoolean ()
const OptionValueBoolean * GetAsBoolean () const
OptionValueChar * GetAsChar ()
const OptionValueChar * GetAsChar () const
OptionValueDictionary * GetAsDictionary ()
const OptionValueDictionary * GetAsDictionary () const
OptionValueEnumeration * GetAsEnumeration ()
const OptionValueEnumeration * GetAsEnumeration () const
OptionValueFileSpec * GetAsFileSpec ()
const OptionValueFileSpec * GetAsFileSpec () const
OptionValueFileSpecList * GetAsFileSpecList ()
const OptionValueFileSpecList * GetAsFileSpecList () const
OptionValueFormat * GetAsFormat ()
const OptionValueFormat * GetAsFormat () const
OptionValueLanguage * GetAsLanguage ()
const OptionValueLanguage * GetAsLanguage () const
OptionValuePathMappings * GetAsPathMappings ()
const OptionValuePathMappings * GetAsPathMappings () const
OptionValueProperties * GetAsProperties ()
const OptionValueProperties * GetAsProperties () const
OptionValueRegex * GetAsRegex ()
const OptionValueRegex * GetAsRegex () const
OptionValueSInt64 * GetAsSInt64 ()
const OptionValueSInt64 * GetAsSInt64 () const
OptionValueString * GetAsString ()
const OptionValueString * GetAsString () const
OptionValueUInt64 * GetAsUInt64 ()
const OptionValueUInt64 * GetAsUInt64 () const
OptionValueUUID * GetAsUUID ()
const OptionValueUUID * GetAsUUID () const
OptionValueFormatEntity * GetAsFormatEntity ()
const OptionValueFormatEntity * GetAsFormatEntity () const
bool AppendFileSpecValue (FileSpec file_spec)
bool OptionWasSet () const
void SetOptionWasSet ()
void SetParent (const lldb::OptionValueSP &parent_sp)
lldb::OptionValueSP GetParent () const
void SetValueChangedCallback (std::function< void()> callback)
void NotifyValueChanged ()
template<typename T, std::enable_if_t<!std::is_pointer_v< T >, bool > = true>
std::optional< T > GetValueAs () const
template<typename T, typename U = typename std::remove_const< typename std::remove_pointer<T>::type>::type, std::enable_if_t< std::is_pointer_v< T >, bool > = true>
T GetValueAs () const
bool SetValueAs (bool v)
bool SetValueAs (char v)
bool SetValueAs (uint64_t v)
bool SetValueAs (int64_t v)
bool SetValueAs (UUID v)
bool SetValueAs (llvm::StringRef v)
bool SetValueAs (lldb::LanguageType v)
bool SetValueAs (lldb::Format v)
bool SetValueAs (FileSpec v)
bool SetValueAs (ArchSpec v)
bool SetValueAs (const FormatEntity::Entry &v)
template<typename T, std::enable_if_t< std::is_enum_v< T >, bool > = true>
bool SetValueAs (T t)
Protected Types
typedef std::vector< lldb::OptionValueSP > collection
Protected Types inherited from lldb_private::OptionValue
using TopmostBase = OptionValue
Protected Attributes
uint32_t m_type_mask
collection m_values
bool m_raw_value_dump
Protected Attributes inherited from lldb_private::OptionValue
lldb::OptionValueWP m_parent_wp
std::function< void()> m_callback
bool m_value_was_set = false
Additional Inherited Members
Public Types inherited from lldb_private::OptionValue
enum Type {
eTypeInvalid = 0 , eTypeArch , eTypeArgs , eTypeArray ,
eTypeBoolean , eTypeChar , eTypeDictionary , eTypeEnum ,
eTypeFileLineColumn , eTypeFileSpec , eTypeFileSpecList , eTypeFormat ,
eTypeLanguage , eTypePathMap , eTypeProperties , eTypeRegex ,
eTypeSInt64 , eTypeString , eTypeUInt64 , eTypeUUID ,
eTypeFormatEntity
}
enum {
eDumpOptionName = (1u << 0) , eDumpOptionType = (1u << 1) , eDumpOptionValue = (1u << 2) , eDumpOptionDescription = (1u << 3) ,
eDumpOptionRaw = (1u << 4) , eDumpOptionCommand = (1u << 5) , eDumpOptionDefaultValue = (1u << 6) , eDumpGroupValue = (eDumpOptionName | eDumpOptionType | eDumpOptionValue) ,
eDumpGroupHelp , eDumpGroupExport = (eDumpOptionCommand | eDumpOptionName | eDumpOptionValue)
}
Static Public Member Functions inherited from lldb_private::OptionValue
static const char * GetBuiltinTypeAsCString (Type t)
static uint32_t ConvertTypeToMask (OptionValue::Type type)
static OptionValue::Type ConvertTypeMaskToType (uint32_t type_mask)
static lldb::OptionValueSP CreateValueFromCStringForTypeMask (const char *value_cstr, uint32_t type_mask, Status &error)
Detailed Description
Definition at line 18 of file OptionValueArray.h.
Member Typedef Documentation
collection
typedef std::vector<lldb::OptionValueSP> lldb_private::OptionValueArray::collection protected
Definition at line 118 of file OptionValueArray.h.
Constructor & Destructor Documentation
OptionValueArray()
lldb_private::OptionValueArray::OptionValueArray (uint32_t type_mask = UINT32_MAX, bool raw_value_dump = false) inline
Definition at line 20 of file OptionValueArray.h.
References m_raw_value_dump, m_type_mask, and UINT32_MAX.
Referenced by DeepCopy().
~OptionValueArray()
lldb_private::OptionValueArray::~OptionValueArray () override default
Member Function Documentation
AppendValue()
bool lldb_private::OptionValueArray::AppendValue (const lldb::OptionValueSP & value_sp) inline
Definition at line 70 of file OptionValueArray.h.
References m_type_mask, and m_values.
Referenced by SetArgs().
Clear()
void lldb_private::OptionValueArray::Clear () inline override virtual
Implements lldb_private::OptionValue.
Definition at line 38 of file OptionValueArray.h.
References lldb_private::OptionValue::m_value_was_set, and m_values.
Referenced by SetArgs().
DeepCopy()
OptionValueSP OptionValueArray::DeepCopy (const lldb::OptionValueSP & new_parent) const override virtual
Reimplemented from lldb_private::OptionValue.
Definition at line 322 of file OptionValueArray.cpp.
References lldb_private::OptionValue::DeepCopy(), lldbassert, and OptionValueArray().
DeleteValue()
bool lldb_private::OptionValueArray::DeleteValue (size_t idx) inline
Definition at line 105 of file OptionValueArray.h.
References m_values.
DumpValue()
void OptionValueArray::DumpValue (const ExecutionContext * exe_ctx, Stream & strm, uint32_t dump_mask) override virtual
Implements lldb_private::OptionValue.
Definition at line 18 of file OptionValueArray.cpp.
References lldb_private::OptionValue::ConvertTypeMaskToType(), lldb_private::OptionValue::eDumpOptionCommand, lldb_private::OptionValue::eDumpOptionDefaultValue, lldb_private::OptionValue::eDumpOptionRaw, lldb_private::OptionValue::eDumpOptionType, lldb_private::OptionValue::eDumpOptionValue, lldb_private::Stream::EOL(), lldb_private::OptionValue::eTypeArray, lldb_private::OptionValue::eTypeBoolean, lldb_private::OptionValue::eTypeChar, lldb_private::OptionValue::eTypeDictionary, lldb_private::OptionValue::eTypeEnum, lldb_private::OptionValue::eTypeFileLineColumn, lldb_private::OptionValue::eTypeFileSpec, lldb_private::OptionValue::eTypeFileSpecList, lldb_private::OptionValue::eTypeFormat, lldb_private::OptionValue::eTypeInvalid, lldb_private::OptionValue::eTypePathMap, lldb_private::OptionValue::eTypeProperties, lldb_private::OptionValue::eTypeSInt64, lldb_private::OptionValue::eTypeString, lldb_private::OptionValue::eTypeUInt64, lldb_private::OptionValue::eTypeUUID, lldb_private::OptionValue::GetBuiltinTypeAsCString(), GetType(), lldb_private::OptionValue::GetTypeAsCString(), lldb_private::Stream::Indent(), lldb_private::Stream::IndentLess(), lldb_private::Stream::IndentMore(), m_raw_value_dump, m_type_mask, m_values, lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
GetArgs()
size_t OptionValueArray::GetArgs (Args & args) const
Definition at line 162 of file OptionValueArray.cpp.
References lldb_private::Args::AppendArgument(), lldb_private::Args::Clear(), lldb_private::Args::GetArgumentCount(), and m_values.
Referenced by lldb_private::OptionValueProperties::GetPropertyAtIndexAsArgs().
GetSize()
size_t lldb_private::OptionValueArray::GetSize () const inline
Definition at line 54 of file OptionValueArray.h.
References m_values.
Referenced by EmulationStateARM::LoadStateFromDictionary(), and SetArgs().
GetSubValue()
lldb::OptionValueSP OptionValueArray::GetSubValue (const ExecutionContext * exe_ctx, llvm::StringRef name, Status & error) const override virtual
Reimplemented from lldb_private::OptionValue.
Definition at line 105 of file OptionValueArray.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::OptionValue::GetTypeAsCString(), m_values, and UINT32_MAX.
GetType()
OptionValue::Type lldb_private::OptionValueArray::GetType () const inline override virtual
Implements lldb_private::OptionValue.
Definition at line 27 of file OptionValueArray.h.
References lldb_private::OptionValue::eTypeArray.
Referenced by DumpValue().
GetValueAtIndex()
lldb::OptionValueSP lldb_private::OptionValueArray::GetValueAtIndex (size_t idx) const inline
Definition at line 63 of file OptionValueArray.h.
References m_values.
Referenced by EmulationStateARM::LoadStateFromDictionary().
InsertValue()
bool lldb_private::OptionValueArray::InsertValue (size_t idx, const lldb::OptionValueSP & value_sp) inline
Definition at line 80 of file OptionValueArray.h.
References m_type_mask, and m_values.
IsAggregateValue()
bool lldb_private::OptionValueArray::IsAggregateValue () const inline override virtual
Reimplemented from lldb_private::OptionValue.
Definition at line 46 of file OptionValueArray.h.
operator[]()
lldb::OptionValueSP lldb_private::OptionValueArray::operator[] (size_t idx) const inline
Definition at line 56 of file OptionValueArray.h.
References m_values.
ReplaceValue()
bool lldb_private::OptionValueArray::ReplaceValue (size_t idx, const lldb::OptionValueSP & value_sp) inline
Definition at line 93 of file OptionValueArray.h.
References m_type_mask, and m_values.
SetArgs()
Status OptionValueArray::SetArgs (const Args & args, VarSetOperationType op)
Definition at line 174 of file OptionValueArray.cpp.
References AppendValue(), Clear(), lldb_private::OptionValue::CreateValueFromCStringForTypeMask(), error(), lldb_private::eVarSetOperationAppend, lldb_private::eVarSetOperationAssign, lldb_private::eVarSetOperationClear, lldb_private::eVarSetOperationInsertAfter, lldb_private::eVarSetOperationInsertBefore, lldb_private::eVarSetOperationInvalid, lldb_private::eVarSetOperationRemove, lldb_private::eVarSetOperationReplace, lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::Args::GetArgumentAtIndex(), lldb_private::Args::GetArgumentCount(), GetSize(), m_type_mask, lldb_private::OptionValue::m_value_was_set, and m_values.
Referenced by lldb_private::OptionValueProperties::SetPropertyAtIndexFromArgs(), and SetValueFromString().
SetValueFromString()
Status OptionValueArray::SetValueFromString (llvm::StringRef value, VarSetOperationType op = eVarSetOperationAssign) override virtual
Reimplemented from lldb_private::OptionValue.
Definition at line 95 of file OptionValueArray.cpp.
References error(), lldb_private::OptionValue::NotifyValueChanged(), and SetArgs().
ToJSON()
llvm::json::Value OptionValueArray::ToJSON (const ExecutionContext * exe_ctx) const override virtual
Implements lldb_private::OptionValue.
Definition at line 87 of file OptionValueArray.cpp.
References m_values.
Member Data Documentation
m_raw_value_dump
bool lldb_private::OptionValueArray::m_raw_value_dump protected
Definition at line 122 of file OptionValueArray.h.
Referenced by DumpValue(), and OptionValueArray().
m_type_mask
uint32_t lldb_private::OptionValueArray::m_type_mask protected
Definition at line 120 of file OptionValueArray.h.
Referenced by AppendValue(), DumpValue(), InsertValue(), OptionValueArray(), ReplaceValue(), and SetArgs().
m_values
collection lldb_private::OptionValueArray::m_values protected
Definition at line 121 of file OptionValueArray.h.
Referenced by AppendValue(), Clear(), DeleteValue(), DumpValue(), lldb_private::OptionValueArgs::GetArgs(), GetArgs(), GetSize(), GetSubValue(), GetValueAtIndex(), InsertValue(), operator[](), ReplaceValue(), SetArgs(), and ToJSON().
The documentation for this class was generated from the following files:
OptionValueArray.h
OptionValueArray.cpp