LLDB: lldb_private::BreakpointOptionGroup Class Reference
lldb_private::BreakpointOptionGroup Class Reference
Public Member Functions
BreakpointOptionGroup ()
~BreakpointOptionGroup () override=default
llvm::ArrayRef< OptionDefinition > GetDefinitions () override
Status SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext *execution_context) override
void OptionParsingStarting (ExecutionContext *execution_context) override
Status OptionParsingFinished (ExecutionContext *execution_context) override
const BreakpointOptions & GetBreakpointOptions ()
Public Member Functions inherited from lldb_private::OptionGroup
OptionGroup ()=default
virtual ~OptionGroup ()=default
Public Attributes
std::vector< std::string > m_commands
BreakpointOptions m_bp_opts
Detailed Description
Definition at line 85 of file CommandObjectBreakpoint.cpp.
Constructor & Destructor Documentation
BreakpointOptionGroup()
lldb_private::BreakpointOptionGroup::BreakpointOptionGroup () inline
Definition at line 87 of file CommandObjectBreakpoint.cpp.
References m_bp_opts.
~BreakpointOptionGroup()
lldb_private::BreakpointOptionGroup::~BreakpointOptionGroup () override default
Member Function Documentation
GetBreakpointOptions()
const BreakpointOptions & lldb_private::BreakpointOptionGroup::GetBreakpointOptions () inline
Definition at line 229 of file CommandObjectBreakpoint.cpp.
References m_bp_opts.
Referenced by CopyOverBreakpointOptions().
GetDefinitions()
llvm::ArrayRef< OptionDefinition > lldb_private::BreakpointOptionGroup::GetDefinitions () inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 91 of file CommandObjectBreakpoint.cpp.
OptionParsingFinished()
Status lldb_private::BreakpointOptionGroup::OptionParsingFinished (ExecutionContext * execution_context) inline override virtual
Reimplemented from lldb_private::OptionGroup.
Definition at line 216 of file CommandObjectBreakpoint.cpp.
References m_bp_opts, m_commands, and lldb_private::Status.
OptionParsingStarting()
void lldb_private::BreakpointOptionGroup::OptionParsingStarting (ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 211 of file CommandObjectBreakpoint.cpp.
References m_bp_opts, and m_commands.
SetOptionValue()
Status lldb_private::BreakpointOptionGroup::SetOptionValue (uint32_t option_idx, llvm::StringRef option_arg, ExecutionContext * execution_context) inline override virtual
Implements lldb_private::OptionGroup.
Definition at line 95 of file CommandObjectBreakpoint.cpp.
References lldb_private::CreateOptionParsingError(), lldb_private::BreakpointOptions::eCondition, lldb::eLanguageTypeUnknown, error(), lldb_private::Status::FromError(), lldb_private::g_bool_parsing_error_message, lldb_private::g_int_parsing_error_message, lldb_private::Language::GetLanguagesSupportingTypeSystemsForExpressions(), lldb_private::Language::GetLanguageTypeFromString(), lldb_private::ExecutionContext::GetThreadSP(), LLDB_INVALID_THREAD_ID, m_bp_opts, m_commands, lldb_private::OptionArgParser::ToBoolean(), and UINT32_MAX.
Member Data Documentation
m_bp_opts
BreakpointOptions lldb_private::BreakpointOptionGroup::m_bp_opts
Definition at line 232 of file CommandObjectBreakpoint.cpp.
Referenced by BreakpointOptionGroup(), GetBreakpointOptions(), OptionParsingFinished(), OptionParsingStarting(), and SetOptionValue().
m_commands
std::vector<std::string> lldb_private::BreakpointOptionGroup::m_commands
Definition at line 231 of file CommandObjectBreakpoint.cpp.
Referenced by OptionParsingFinished(), OptionParsingStarting(), and SetOptionValue().
The documentation for this class was generated from the following file:
CommandObjectBreakpoint.cpp