LLDB: lldb_private::ClangExpressionDeclMap::ParserVars Class Reference
lldb_private::ClangExpressionDeclMap::ParserVars Class Reference
The following values should not live beyond parsing.
Public Member Functions
ParserVars ()=default
Target * GetTarget ()
Public Attributes
ExecutionContext m_exe_ctx
The execution context to use when parsing.
SymbolContext m_sym_ctx
The symbol context to use in finding variables and types.
ClangPersistentVariables * m_persistent_vars
The persistent variables for the process.
bool m_enable_lookups = false
Set to true during parsing if we have found the first "$__lldb" name.
TargetInfo m_target_info
Basic information about the target.
Materializer * m_materializer = nullptr
If non-NULL, the materializer to use when reporting used variables.
clang::ASTConsumer * m_code_gen = nullptr
If non-NULL, a code generator that receives new top-level functions.
DiagnosticManager * m_diagnostics = nullptr
Private Member Functions
ParserVars (const ParserVars &)=delete
const ParserVars & operator= (const ParserVars &)=delete
Detailed Description
The following values should not live beyond parsing.
Definition at line 323 of file ClangExpressionDeclMap.h.
Constructor & Destructor Documentation
ParserVars() [1/2]
lldb_private::ClangExpressionDeclMap::ParserVars::ParserVars () default
Referenced by operator=(), and ParserVars().
ParserVars() [2/2]
lldb_private::ClangExpressionDeclMap::ParserVars::ParserVars (const ParserVars &) private delete
References ParserVars().
Member Function Documentation
GetTarget()
Target * lldb_private::ClangExpressionDeclMap::ParserVars::GetTarget () inline
Definition at line 327 of file ClangExpressionDeclMap.h.
References m_exe_ctx, and m_sym_ctx.
operator=()
const ParserVars & lldb_private::ClangExpressionDeclMap::ParserVars::operator= (const ParserVars &) private delete
References ParserVars().
Member Data Documentation
m_code_gen
clang::ASTConsumer* lldb_private::ClangExpressionDeclMap::ParserVars::m_code_gen = nullptr
If non-NULL, a code generator that receives new top-level functions.
Definition at line 346 of file ClangExpressionDeclMap.h.
m_diagnostics
DiagnosticManager* lldb_private::ClangExpressionDeclMap::ParserVars::m_diagnostics = nullptr
Definition at line 349 of file ClangExpressionDeclMap.h.
m_enable_lookups
bool lldb_private::ClangExpressionDeclMap::ParserVars::m_enable_lookups = false
Set to true during parsing if we have found the first "$__lldb" name.
Definition at line 340 of file ClangExpressionDeclMap.h.
m_exe_ctx
ExecutionContext lldb_private::ClangExpressionDeclMap::ParserVars::m_exe_ctx
The execution context to use when parsing.
Definition at line 335 of file ClangExpressionDeclMap.h.
Referenced by GetTarget().
m_materializer
Materializer* lldb_private::ClangExpressionDeclMap::ParserVars::m_materializer = nullptr
If non-NULL, the materializer to use when reporting used variables.
Definition at line 343 of file ClangExpressionDeclMap.h.
m_persistent_vars
ClangPersistentVariables* lldb_private::ClangExpressionDeclMap::ParserVars::m_persistent_vars
Initial value:
=
        nullptr
The persistent variables for the process.
Definition at line 338 of file ClangExpressionDeclMap.h.
m_sym_ctx
SymbolContext lldb_private::ClangExpressionDeclMap::ParserVars::m_sym_ctx
The symbol context to use in finding variables and types.
Definition at line 336 of file ClangExpressionDeclMap.h.
Referenced by GetTarget().
m_target_info
TargetInfo lldb_private::ClangExpressionDeclMap::ParserVars::m_target_info
Basic information about the target.
Definition at line 342 of file ClangExpressionDeclMap.h.
The documentation for this class was generated from the following file:
ClangExpressionDeclMap.h