LLDB: lldb_private::AppleObjCTypeEncodingParser Class Reference
lldb_private::AppleObjCTypeEncodingParser Class Reference
#include <AppleObjCTypeEncodingParser.h>
Classes
struct StructElement
Public Member Functions
AppleObjCTypeEncodingParser (ObjCLanguageRuntime &runtime)
~AppleObjCTypeEncodingParser () override=default
CompilerType RealizeType (TypeSystemClang &ast_ctx, const char *name, bool for_expression) override
Public Member Functions inherited from lldb_private::ObjCLanguageRuntime::EncodingToType
virtual ~EncodingToType ()
virtual CompilerType RealizeType (const char *name, bool for_expression)
Private Member Functions
clang::QualType BuildType (TypeSystemClang &clang_ast_ctx, llvm::StringRef &type, bool for_expression, uint32_t *bitfield_bit_size=nullptr)
clang::QualType BuildStruct (TypeSystemClang &ast_ctx, llvm::StringRef &type, bool for_expression)
clang::QualType BuildAggregate (TypeSystemClang &clang_ast_ctx, llvm::StringRef &type, bool for_expression, char opener, char closer, uint32_t kind)
clang::QualType BuildUnion (TypeSystemClang &ast_ctx, llvm::StringRef &type, bool for_expression)
clang::QualType BuildArray (TypeSystemClang &ast_ctx, llvm::StringRef &type, bool for_expression)
std::string ReadStructName (llvm::StringRef &type)
StructElement ReadStructElement (TypeSystemClang &ast_ctx, llvm::StringRef &type, bool for_expression)
clang::QualType BuildObjCObjectPointerType (TypeSystemClang &clang_ast_ctx, llvm::StringRef &type, bool for_expression)
uint32_t ReadNumber (llvm::StringRef &type)
std::optional< std::string > ReadQuotedString (llvm::StringRef &type)
Private Attributes
ObjCLanguageRuntime & m_runtime
Additional Inherited Members
Protected Attributes inherited from lldb_private::ObjCLanguageRuntime::EncodingToType
std::shared_ptr< TypeSystemClang > m_scratch_ast_ctx_sp
Detailed Description
Definition at line 19 of file AppleObjCTypeEncodingParser.h.
Constructor & Destructor Documentation
AppleObjCTypeEncodingParser()
AppleObjCTypeEncodingParser::AppleObjCTypeEncodingParser (ObjCLanguageRuntime & runtime)
Definition at line 34 of file AppleObjCTypeEncodingParser.cpp.
References lldb_private::Target::GetArchitecture(), lldb_private::Runtime::GetProcess(), lldb_private::Process::GetTarget(), lldb_private::ArchSpec::GetTriple(), m_runtime, and lldb_private::ObjCLanguageRuntime::EncodingToType::m_scratch_ast_ctx_sp.
~AppleObjCTypeEncodingParser()
lldb_private::AppleObjCTypeEncodingParser::~AppleObjCTypeEncodingParser () override default
Member Function Documentation
BuildAggregate()
clang::QualType AppleObjCTypeEncodingParser::BuildAggregate (TypeSystemClang & clang_ast_ctx, llvm::StringRef & type, bool for_expression, char opener, char closer, uint32_t kind) private
Definition at line 111 of file AppleObjCTypeEncodingParser.cpp.
References lldb_private::TypeSystemClang::AddFieldToRecordType(), lldb_private::TypeSystemClang::CompleteTagDeclarationDefinition(), lldb_private::TypeSystemClang::CreateRecordType(), lldb::eAccessPublic, lldb::eLanguageTypeC, lldb_private::ClangUtil::GetQualType(), lldb_private::StreamString::GetString(), lldb_private::TypeSystemClang::GetType(), lldb_private::Stream::Printf(), ReadStructElement(), ReadStructName(), and lldb_private::TypeSystemClang::StartTagDeclarationDefinition().
Referenced by BuildStruct(), and BuildUnion().
BuildArray()
clang::QualType AppleObjCTypeEncodingParser::BuildArray (TypeSystemClang & ast_ctx, llvm::StringRef & type, bool for_expression) private
Definition at line 170 of file AppleObjCTypeEncodingParser.cpp.
References _C_ARY_B, _C_ARY_E, BuildType(), lldb_private::TypeSystemClang::CreateArrayType(), lldb_private::ClangUtil::GetQualType(), and ReadNumber().
Referenced by BuildType().
BuildObjCObjectPointerType()
clang::QualType AppleObjCTypeEncodingParser::BuildObjCObjectPointerType (TypeSystemClang & clang_ast_ctx, llvm::StringRef & type, bool for_expression) private
Definition at line 191 of file AppleObjCTypeEncodingParser.cpp.
References _C_ARY_E, _C_ID, _C_STRUCT_E, _C_UNION_E, lldb_private::DeclVendor::FindTypes(), lldb_private::TypeSystemClang::getASTContext(), lldb_private::GetLog(), lldb_private::ClangUtil::GetQualType(), LLDB_LOG, m_runtime, ReadQuotedString(), and lldb_private::Types.
Referenced by BuildType().
BuildStruct()
clang::QualType AppleObjCTypeEncodingParser::BuildStruct (TypeSystemClang & ast_ctx, llvm::StringRef & type, bool for_expression) private
Definition at line 99 of file AppleObjCTypeEncodingParser.cpp.
References _C_STRUCT_B, _C_STRUCT_E, and BuildAggregate().
Referenced by BuildType().
BuildType()
clang::QualType AppleObjCTypeEncodingParser::BuildType (TypeSystemClang & clang_ast_ctx, llvm::StringRef & type, bool for_expression, uint32_t * bitfield_bit_size = nullptr) private
Definition at line 280 of file AppleObjCTypeEncodingParser.cpp.
References _C_ARY_B, _C_BFLD, _C_BOOL, _C_CHARPTR, _C_CHR, _C_CLASS, _C_CONST, _C_DBL, _C_FLT, _C_ID, _C_INT, _C_LNG, _C_LNG_LNG, _C_PTR, _C_SEL, _C_SHT, _C_STRUCT_B, _C_UCHR, _C_UINT, _C_ULNG, _C_ULNG_LNG, _C_UNDEF, _C_UNION_B, _C_USHT, _C_VOID, BuildArray(), BuildObjCObjectPointerType(), BuildStruct(), BuildType(), BuildUnion(), lldb_private::TypeSystemClang::getASTContext(), popChar(), and ReadNumber().
Referenced by BuildArray(), BuildType(), ReadStructElement(), and RealizeType().
BuildUnion()
clang::QualType AppleObjCTypeEncodingParser::BuildUnion (TypeSystemClang & ast_ctx, llvm::StringRef & type, bool for_expression) private
Definition at line 105 of file AppleObjCTypeEncodingParser.cpp.
References _C_UNION_B, _C_UNION_E, and BuildAggregate().
Referenced by BuildType().
ReadNumber()
uint32_t AppleObjCTypeEncodingParser::ReadNumber (llvm::StringRef & type) private
Definition at line 68 of file AppleObjCTypeEncodingParser.cpp.
References popChar().
Referenced by BuildArray(), and BuildType().
ReadQuotedString()
std::optional< std::string > AppleObjCTypeEncodingParser::ReadQuotedString (llvm::StringRef & type) private
Definition at line 54 of file AppleObjCTypeEncodingParser.cpp.
References lldb_private::StreamString::GetString(), popChar(), and lldb_private::Stream::Printf().
Referenced by BuildObjCObjectPointerType(), and ReadStructElement().
ReadStructElement()
AppleObjCTypeEncodingParser::StructElement AppleObjCTypeEncodingParser::ReadStructElement (TypeSystemClang & ast_ctx, llvm::StringRef & type, bool for_expression) private
Definition at line 83 of file AppleObjCTypeEncodingParser.cpp.
References lldb_private::AppleObjCTypeEncodingParser::StructElement::bitfield, BuildType(), lldb_private::AppleObjCTypeEncodingParser::StructElement::name, ReadQuotedString(), and lldb_private::AppleObjCTypeEncodingParser::StructElement::type.
Referenced by BuildAggregate().
ReadStructName()
std::string AppleObjCTypeEncodingParser::ReadStructName (llvm::StringRef & type) private
Definition at line 45 of file AppleObjCTypeEncodingParser.cpp.
References lldb_private::StreamString::GetString(), popChar(), and lldb_private::Stream::Printf().
Referenced by BuildAggregate().
RealizeType()
CompilerType AppleObjCTypeEncodingParser::RealizeType (TypeSystemClang & ast_ctx, const char * name, bool for_expression) override virtual
Implements lldb_private::ObjCLanguageRuntime::EncodingToType.
Definition at line 389 of file AppleObjCTypeEncodingParser.cpp.
References BuildType(), and lldb_private::TypeSystemClang::GetType().
Member Data Documentation
m_runtime
ObjCLanguageRuntime& lldb_private::AppleObjCTypeEncodingParser::m_runtime private
Definition at line 67 of file AppleObjCTypeEncodingParser.h.
Referenced by AppleObjCTypeEncodingParser(), and BuildObjCObjectPointerType().
The documentation for this class was generated from the following files:
AppleObjCTypeEncodingParser.h
AppleObjCTypeEncodingParser.cpp