LLDB: lldb::SBLanguageRuntime Class Reference
lldb::SBLanguageRuntime Class Reference
#include <SBLanguageRuntime.h>
Static Public Member Functions
static lldb::LanguageType GetLanguageTypeFromString (const char *string)
static const char * GetNameForLanguageType (lldb::LanguageType language)
static bool LanguageIsCPlusPlus (lldb::LanguageType language)
Returns whether the given language is any version of C++.
static bool LanguageIsObjC (lldb::LanguageType language)
Returns whether the given language is Obj-C or Obj-C++.
static bool LanguageIsCFamily (lldb::LanguageType language)
Returns whether the given language is any version of C, C++ or Obj-C.
static bool SupportsExceptionBreakpointsOnThrow (lldb::LanguageType language)
Returns whether the given language supports exception breakpoints on throw statements.
static bool SupportsExceptionBreakpointsOnCatch (lldb::LanguageType language)
Returns whether the given language supports exception breakpoints on catch statements.
static const char * GetThrowKeywordForLanguage (lldb::LanguageType language)
Returns the keyword used for throw statements in the given language, e.g.
static const char * GetCatchKeywordForLanguage (lldb::LanguageType language)
Returns the keyword used for catch statements in the given language, e.g.
Detailed Description
Definition at line 16 of file SBLanguageRuntime.h.
Member Function Documentation
GetCatchKeywordForLanguage()
const char * SBLanguageRuntime::GetCatchKeywordForLanguage (lldb::LanguageType language) static
Returns the keyword used for catch statements in the given language, e.g.
Python uses except. Returns nullptr if the language is not supported.
Definition at line 64 of file SBLanguageRuntime.cpp.
References lldb_private::ConstString::AsCString(), and lldb_private::Language::FindPlugin().
GetLanguageTypeFromString()
lldb::LanguageType SBLanguageRuntime::GetLanguageTypeFromString (const char * string) static
Definition at line 17 of file SBLanguageRuntime.cpp.
References lldb_private::Language::GetLanguageTypeFromString(), and LLDB_INSTRUMENT_VA.
GetNameForLanguageType()
const char * SBLanguageRuntime::GetNameForLanguageType (lldb::LanguageType language) static
Definition at line 24 of file SBLanguageRuntime.cpp.
References lldb_private::Language::GetNameForLanguageType(), and LLDB_INSTRUMENT_VA.
GetThrowKeywordForLanguage()
const char * SBLanguageRuntime::GetThrowKeywordForLanguage (lldb::LanguageType language) static
Returns the keyword used for throw statements in the given language, e.g.
Python uses raise. Returns nullptr if the language is not supported.
Definition at line 57 of file SBLanguageRuntime.cpp.
References lldb_private::ConstString::AsCString(), and lldb_private::Language::FindPlugin().
LanguageIsCFamily()
bool SBLanguageRuntime::LanguageIsCFamily (lldb::LanguageType language) static
Returns whether the given language is any version of C, C++ or Obj-C.
Definition at line 38 of file SBLanguageRuntime.cpp.
References lldb_private::Language::LanguageIsCFamily().
LanguageIsCPlusPlus()
bool SBLanguageRuntime::LanguageIsCPlusPlus (lldb::LanguageType language) static
Returns whether the given language is any version of C++.
Definition at line 30 of file SBLanguageRuntime.cpp.
References lldb_private::Language::LanguageIsCPlusPlus().
LanguageIsObjC()
bool SBLanguageRuntime::LanguageIsObjC (lldb::LanguageType language) static
Returns whether the given language is Obj-C or Obj-C++.
Definition at line 34 of file SBLanguageRuntime.cpp.
References lldb_private::Language::LanguageIsObjC().
SupportsExceptionBreakpointsOnCatch()
bool SBLanguageRuntime::SupportsExceptionBreakpointsOnCatch (lldb::LanguageType language) static
Returns whether the given language supports exception breakpoints on catch statements.
Definition at line 49 of file SBLanguageRuntime.cpp.
References lldb_private::Language::FindPlugin().
SupportsExceptionBreakpointsOnThrow()
bool SBLanguageRuntime::SupportsExceptionBreakpointsOnThrow (lldb::LanguageType language) static
Returns whether the given language supports exception breakpoints on throw statements.
Definition at line 42 of file SBLanguageRuntime.cpp.
References lldb_private::Language::FindPlugin().
The documentation for this class was generated from the following files:
SBLanguageRuntime.h
SBLanguageRuntime.cpp