LLDB: OutputWriterCLI Class Reference
OutputWriterCLI Class Reference
Public Member Functions
OutputWriterCLI (Stream &s, const TraceDumperOptions &options, Thread &thread)
void NoMoreData () override
Notify this writer that the cursor ran out of data.
void FunctionCallForest (const std::vector< TraceDumper::FunctionCallUP > &forest) override
Dump a function call forest.
void TraceItem (const TraceDumper::TraceItem &item) override
Dump a trace item (instruction, error or event).
Public Member Functions inherited from lldb_private::TraceDumper::OutputWriter
virtual ~OutputWriter ()=default
Private Member Functions
void DumpSegmentContext (const TraceDumper::FunctionCall::TracedSegment &segment)
void DumpUntracedContext (const TraceDumper::FunctionCall &function_call)
void DumpFunctionCallTree (const TraceDumper::FunctionCall &function_call)
Private Attributes
Stream & m_s
TraceDumperOptions m_options
bool m_was_prev_instruction_an_error = false
Detailed Description
Definition at line 113 of file TraceDumper.cpp.
Constructor & Destructor Documentation
OutputWriterCLI()
OutputWriterCLI::OutputWriterCLI (Stream & s, const TraceDumperOptions & options, Thread & thread) inline
Definition at line 115 of file TraceDumper.cpp.
References m_options, and m_s.
Member Function Documentation
DumpFunctionCallTree()
void OutputWriterCLI::DumpFunctionCallTree (const TraceDumper::FunctionCall & function_call) inline private
Definition at line 250 of file TraceDumper.cpp.
References DumpFunctionCallTree(), DumpSegmentContext(), DumpUntracedContext(), lldb_private::TraceDumper::FunctionCall::GetTracedSegments(), lldb_private::TraceDumper::FunctionCall::GetUntracedPrefixSegment(), and m_s.
Referenced by DumpFunctionCallTree(), and FunctionCallForest().
DumpSegmentContext()
void OutputWriterCLI::DumpSegmentContext (const TraceDumper::FunctionCall::TracedSegment & segment) inline private
Definition at line 205 of file TraceDumper.cpp.
References lldb_private::LineEntry::column, lldb_private::SymbolContext::DumpStopContext(), IsLineEntryValid(), lldb_private::LineEntry::line, lldb_private::SymbolContext::line_entry, and m_s.
Referenced by DumpFunctionCallTree().
DumpUntracedContext()
void OutputWriterCLI::DumpUntracedContext (const TraceDumper::FunctionCall & function_call) inline private
Definition at line 235 of file TraceDumper.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::SymbolContext::function, lldb_private::SymbolContext::GetFunctionName(), GetModuleName(), lldb_private::TraceDumper::FunctionCall::GetSymbolInfo(), lldb_private::TraceDumper::FunctionCall::IsError(), m_s, lldb_private::TraceDumper::SymbolInfo::sc, and lldb_private::SymbolContext::symbol.
Referenced by DumpFunctionCallTree().
FunctionCallForest()
void OutputWriterCLI::FunctionCallForest (const std::vector< TraceDumper::FunctionCallUP > & forest) inline override virtual
Dump a function call forest.
Implements lldb_private::TraceDumper::OutputWriter.
Definition at line 122 of file TraceDumper.cpp.
References DumpFunctionCallTree(), and m_s.
NoMoreData()
void OutputWriterCLI::NoMoreData () inline override virtual
Notify this writer that the cursor ran out of data.
Reimplemented from lldb_private::TraceDumper::OutputWriter.
Definition at line 120 of file TraceDumper.cpp.
References m_s.
TraceItem()
void OutputWriterCLI::TraceItem (const TraceDumper::TraceItem & item) inline override virtual
Dump a trace item (instruction, error or event).
Implements lldb_private::TraceDumper::OutputWriter.
Definition at line 130 of file TraceDumper.cpp.
References lldb_private::TraceDumper::TraceItem::cpu_id, lldb_private::TraceDumper::TraceItem::error, lldb::eTraceEventCPUChanged, lldb::eTraceEventDisabledHW, lldb::eTraceEventDisabledSW, lldb::eTraceEventHWClockTick, lldb::eTraceEventSyncPoint, lldb_private::TraceDumper::TraceItem::event, lldb_private::TraceCursor::EventKindToString(), GetModuleName(), lldb_private::TraceDumper::TraceItem::hw_clock, lldb_private::TraceDumper::TraceItem::id, IsSameInstructionSymbolContext(), lldb_private::TraceDumper::TraceItem::load_address, m_options, m_s, m_was_prev_instruction_an_error, lldb_private::TraceDumper::TraceItem::prev_symbol_info, lldb_private::TraceDumper::TraceItem::symbol_info, lldb_private::TraceDumper::TraceItem::sync_point_metadata, and lldb_private::TraceDumper::TraceItem::timestamp.
Member Data Documentation
m_options
TraceDumperOptions OutputWriterCLI::m_options private
Definition at line 277 of file TraceDumper.cpp.
Referenced by OutputWriterCLI(), and TraceItem().
m_s
Stream& OutputWriterCLI::m_s private
Definition at line 276 of file TraceDumper.cpp.
Referenced by DumpFunctionCallTree(), DumpSegmentContext(), DumpUntracedContext(), FunctionCallForest(), NoMoreData(), OutputWriterCLI(), and TraceItem().
m_was_prev_instruction_an_error
bool OutputWriterCLI::m_was_prev_instruction_an_error = false private
Definition at line 278 of file TraceDumper.cpp.
Referenced by TraceItem().
The documentation for this class was generated from the following file:
TraceDumper.cpp