LLDB: lldb_private::Language::ImageListTypeScavenger::Result Class Reference
lldb_private::Language::ImageListTypeScavenger::Result Class Reference
Public Member Functions
Result (CompilerType type)
bool IsValid () override
bool DumpToStream (Stream &stream, bool print_help_if_available) override
~Result () override=default
Private Attributes
CompilerType m_compiler_type
Detailed Description
Definition at line 68 of file Language.h.
Constructor & Destructor Documentation
Result()
lldb_private::Language::ImageListTypeScavenger::Result::Result (CompilerType type) inline
Definition at line 70 of file Language.h.
References m_compiler_type.
~Result()
lldb_private::Language::ImageListTypeScavenger::Result::~Result () override virtual default
Reimplemented from lldb_private::Language::TypeScavenger::Result.
Member Function Documentation
DumpToStream()
bool lldb_private::Language::ImageListTypeScavenger::Result::DumpToStream (Stream & stream, bool print_help_if_available) inline override virtual
Implements lldb_private::Language::TypeScavenger::Result.
Definition at line 74 of file Language.h.
References lldb_private::Stream::EOL(), IsValid(), and m_compiler_type.
IsValid()
bool lldb_private::Language::ImageListTypeScavenger::Result::IsValid () inline override virtual
Implements lldb_private::Language::TypeScavenger::Result.
Definition at line 72 of file Language.h.
References m_compiler_type.
Referenced by DumpToStream().
Member Data Documentation
m_compiler_type
CompilerType lldb_private::Language::ImageListTypeScavenger::Result::m_compiler_type private
Definition at line 86 of file Language.h.
Referenced by DumpToStream(), IsValid(), and Result().
The documentation for this class was generated from the following file:
Language.h