LLDB: lldb_private::mcp::DebuggerResourceProvider Class Reference
lldb_private::mcp::DebuggerResourceProvider Class Reference
#include <Resource.h>
Public Member Functions
virtual ~DebuggerResourceProvider ()=default
std::vector< lldb_protocol::mcp::Resource > GetResources () const override
llvm::Expected< lldb_protocol::mcp::ReadResourceResult > ReadResource (llvm::StringRef uri) const override
Public Member Functions inherited from lldb_protocol::mcp::ResourceProvider
ResourceProvider ()=default
virtual ~ResourceProvider ()=default
Static Private Member Functions
static lldb_protocol::mcp::Resource GetDebuggerResource (Debugger &debugger)
static lldb_protocol::mcp::Resource GetTargetResource (size_t target_idx, Target &target)
static llvm::Expected< lldb_protocol::mcp::ReadResourceResult > ReadDebuggerResource (llvm::StringRef uri, lldb::user_id_t debugger_id)
static llvm::Expected< lldb_protocol::mcp::ReadResourceResult > ReadTargetResource (llvm::StringRef uri, lldb::user_id_t debugger_id, size_t target_idx)
Detailed Description
Definition at line 23 of file source/Plugins/Protocol/MCP/Resource.h.
Constructor & Destructor Documentation
~DebuggerResourceProvider()
virtual lldb_private::mcp::DebuggerResourceProvider::~DebuggerResourceProvider () virtual default
Member Function Documentation
GetDebuggerResource()
lldb_protocol::mcp::Resource DebuggerResourceProvider::GetDebuggerResource (Debugger & debugger) static private
Definition at line 69 of file Resource.cpp.
References lldb_protocol::mcp::Resource::description, lldb_private::UserID::GetID(), lldb_private::Debugger::GetInstanceName(), kMimeTypeJSON, lldb_protocol::mcp::Resource::mimeType, lldb_protocol::mcp::Resource::name, and lldb_protocol::mcp::Resource::uri.
Referenced by GetResources().
GetResources()
std::vector< lldb_protocol::mcp::Resource > DebuggerResourceProvider::GetResources () const override virtual
Implements lldb_protocol::mcp::ResourceProvider.
Definition at line 103 of file Resource.cpp.
References lldb_private::Debugger::GetDebuggerAtIndex(), GetDebuggerResource(), lldb_private::Debugger::GetNumDebuggers(), lldb_private::TargetList::GetNumTargets(), lldb_private::TargetList::GetTargetAtIndex(), and GetTargetResource().
GetTargetResource()
lldb_protocol::mcp::Resource DebuggerResourceProvider::GetTargetResource (size_t target_idx, Target & target) static private
Definition at line 83 of file Resource.cpp.
References lldb_protocol::mcp::Resource::description, lldb_private::Target::GetDebugger(), lldb_private::Target::GetExecutableModulePointer(), lldb_private::UserID::GetID(), kMimeTypeJSON, lldb_protocol::mcp::Resource::mimeType, lldb_protocol::mcp::Resource::name, and lldb_protocol::mcp::Resource::uri.
Referenced by GetResources().
ReadDebuggerResource()
llvm::Expected< lldb_protocol::mcp::ReadResourceResult > DebuggerResourceProvider::ReadDebuggerResource (llvm::StringRef uri, lldb::user_id_t debugger_id) static private
Definition at line 164 of file Resource.cpp.
References lldb_protocol::mcp::ReadResourceResult::contents, createStringError(), lldb_private::Debugger::FindDebuggerWithID(), kMimeTypeJSON, lldb_protocol::mcp::TextResourceContents::mimeType, lldb_protocol::mcp::TextResourceContents::text, lldb_private::toJSON(), and lldb_protocol::mcp::TextResourceContents::uri.
Referenced by ReadResource().
ReadResource()
llvm::Expected< lldb_protocol::mcp::ReadResourceResult > DebuggerResourceProvider::ReadResource (llvm::StringRef uri) const override virtual
Implements lldb_protocol::mcp::ResourceProvider.
Definition at line 127 of file Resource.cpp.
References createStringError(), createUnsupportedURIError(), ReadDebuggerResource(), and ReadTargetResource().
ReadTargetResource()
llvm::Expected< lldb_protocol::mcp::ReadResourceResult > DebuggerResourceProvider::ReadTargetResource (llvm::StringRef uri, lldb::user_id_t debugger_id, size_t target_idx) static private
Definition at line 186 of file Resource.cpp.
References lldb_protocol::mcp::ReadResourceResult::contents, createStringError(), lldb_private::Debugger::FindDebuggerWithID(), lldb_private::TargetList::GetTargetAtIndex(), kMimeTypeJSON, lldb_protocol::mcp::TextResourceContents::mimeType, lldb_protocol::mcp::TextResourceContents::text, lldb_private::toJSON(), and lldb_protocol::mcp::TextResourceContents::uri.
Referenced by ReadResource().
The documentation for this class was generated from the following files:
source/Plugins/Protocol/MCP/Resource.h
Resource.cpp