LLDB: RegisterContextDarwin_x86_64 Class Reference
RegisterContextDarwin_x86_64 Class Reference abstract
#include <RegisterContextDarwin_x86_64.h>
Classes
struct EXC
struct FPU
struct GPR
struct MMSReg
struct XMMReg
Public Member Functions
RegisterContextDarwin_x86_64 (lldb_private::Thread &thread, uint32_t concrete_frame_idx)
~RegisterContextDarwin_x86_64 () override
void InvalidateAllRegisters () override
size_t GetRegisterCount () override
const lldb_private::RegisterInfo * GetRegisterInfoAtIndex (size_t reg) override
size_t GetRegisterSetCount () override
const lldb_private::RegisterSet * GetRegisterSet (size_t set) override
bool ReadRegister (const lldb_private::RegisterInfo *reg_info, lldb_private::RegisterValue &value) override
bool WriteRegister (const lldb_private::RegisterInfo *reg_info, const lldb_private::RegisterValue &value) override
bool ReadAllRegisterValues (lldb::WritableDataBufferSP &data_sp) override
bool WriteAllRegisterValues (const lldb::DataBufferSP &data_sp) override
uint32_t ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num) override
Convert from a given register numbering scheme to the lldb register numbering scheme.
bool HardwareSingleStep (bool enable) override
Public Member Functions inherited from lldb_private::RegisterContext
RegisterContext (Thread &thread, uint32_t concrete_frame_idx)
~RegisterContext () override
void InvalidateIfNeeded (bool force)
virtual lldb::ByteOrder GetByteOrder ()
virtual bool RegisterWriteCausesReconfigure (const llvm::StringRef name)
virtual bool ReconfigureRegisterInfo ()
virtual bool ReadAllRegisterValues (lldb_private::RegisterCheckpoint &reg_checkpoint)
virtual bool WriteAllRegisterValues (const lldb_private::RegisterCheckpoint &reg_checkpoint)
bool CopyFromRegisterContext (lldb::RegisterContextSP context)
virtual uint32_t NumSupportedHardwareBreakpoints ()
virtual uint32_t SetHardwareBreakpoint (lldb::addr_t addr, size_t size)
virtual bool ClearHardwareBreakpoint (uint32_t hw_idx)
virtual uint32_t NumSupportedHardwareWatchpoints ()
virtual uint32_t SetHardwareWatchpoint (lldb::addr_t addr, size_t size, bool read, bool write)
virtual bool ClearHardwareWatchpoint (uint32_t hw_index)
virtual Status ReadRegisterValueFromMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t src_addr, uint32_t src_len, RegisterValue &reg_value)
virtual Status WriteRegisterValueToMemory (const lldb_private::RegisterInfo *reg_info, lldb::addr_t dst_addr, uint32_t dst_len, const RegisterValue &reg_value)
virtual lldb::tid_t GetThreadID () const
virtual Thread & GetThread ()
const RegisterInfo * GetRegisterInfoByName (llvm::StringRef reg_name, uint32_t start_idx=0)
const RegisterInfo * GetRegisterInfo (lldb::RegisterKind reg_kind, uint32_t reg_num)
uint64_t GetPC (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetThreadPointer (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool GetPCForSymbolication (Address &address)
Get an address suitable for symbolication.
bool SetPC (uint64_t pc)
bool SetPC (Address addr)
uint64_t GetSP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetSP (uint64_t sp)
uint64_t GetFP (uint64_t fail_value=LLDB_INVALID_ADDRESS)
bool SetFP (uint64_t fp)
const char * GetRegisterName (uint32_t reg)
uint64_t GetReturnAddress (uint64_t fail_value=LLDB_INVALID_ADDRESS)
uint64_t GetFlags (uint64_t fail_value=0)
uint64_t ReadRegisterAsUnsigned (uint32_t reg, uint64_t fail_value)
uint64_t ReadRegisterAsUnsigned (const RegisterInfo *reg_info, uint64_t fail_value)
bool WriteRegisterFromUnsigned (uint32_t reg, uint64_t uval)
bool WriteRegisterFromUnsigned (const RegisterInfo *reg_info, uint64_t uval)
bool ConvertBetweenRegisterKinds (lldb::RegisterKind source_rk, uint32_t source_regnum, lldb::RegisterKind target_rk, uint32_t &target_regnum)
lldb::TargetSP CalculateTarget () override
lldb::ProcessSP CalculateProcess () override
lldb::ThreadSP CalculateThread () override
lldb::StackFrameSP CalculateStackFrame () override
void CalculateExecutionContext (ExecutionContext &exe_ctx) override
Reconstruct the object's execution context into sc.
uint32_t GetStopID () const
void SetStopID (uint32_t stop_id)
Public Member Functions inherited from lldb_private::ExecutionContextScope
virtual ~ExecutionContextScope ()=default
Protected Types
enum { GPRRegSet = 4 , FPURegSet = 5 , EXCRegSet = 6 }
enum { GPRWordCount = sizeof(GPR) / sizeof(uint32_t) , FPUWordCount = sizeof(FPU) / sizeof(uint32_t) , EXCWordCount = sizeof(EXC) / sizeof(uint32_t) }
enum { Read = 0 , Write = 1 , kNumErrors = 2 }
Protected Member Functions
void InvalidateAllRegisterStates ()
int GetError (int flavor, uint32_t err_idx) const
bool SetError (int flavor, uint32_t err_idx, int err)
bool RegisterSetIsCached (int set) const
void LogGPR (lldb_private::Log *log, const char *format,...)
int ReadGPR (bool force)
int ReadFPU (bool force)
int ReadEXC (bool force)
int WriteGPR ()
int WriteFPU ()
int WriteEXC ()
virtual int DoReadGPR (lldb::tid_t tid, int flavor, GPR &gpr)=0
virtual int DoReadFPU (lldb::tid_t tid, int flavor, FPU &fpu)=0
virtual int DoReadEXC (lldb::tid_t tid, int flavor, EXC &exc)=0
virtual int DoWriteGPR (lldb::tid_t tid, int flavor, const GPR &gpr)=0
virtual int DoWriteFPU (lldb::tid_t tid, int flavor, const FPU &fpu)=0
virtual int DoWriteEXC (lldb::tid_t tid, int flavor, const EXC &exc)=0
int ReadRegisterSet (uint32_t set, bool force)
int WriteRegisterSet (uint32_t set)
Protected Member Functions inherited from lldb_private::RegisterContext
virtual bool BehavesLikeZerothFrame () const
Indicates that this frame is currently executing code, that the PC value is not a return-pc but an actual executing instruction.
Static Protected Member Functions
static uint32_t GetRegisterNumber (uint32_t reg_kind, uint32_t reg_num)
static int GetSetForNativeRegNum (int reg_num)
static size_t GetRegisterInfosCount ()
static const lldb_private::RegisterInfo * GetRegisterInfos ()
Protected Attributes
GPR gpr
FPU fpu
EXC exc
int gpr_errs [2]
int fpu_errs [2]
int exc_errs [2]
Protected Attributes inherited from lldb_private::RegisterContext
Thread & m_thread
uint32_t m_concrete_frame_idx
uint32_t m_stop_id
Detailed Description
Definition at line 15 of file RegisterContextDarwin_x86_64.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
GPRWordCount
FPUWordCount
EXCWordCount
Definition at line 110 of file RegisterContextDarwin_x86_64.h.
anonymous enum
anonymous enum protected
Enumerator
GPRRegSet
FPURegSet
EXCRegSet
Definition at line 108 of file RegisterContextDarwin_x86_64.h.
anonymous enum
anonymous enum protected
Enumerator
Read
Write
kNumErrors
Definition at line 116 of file RegisterContextDarwin_x86_64.h.
Constructor & Destructor Documentation
RegisterContextDarwin_x86_64()
RegisterContextDarwin_x86_64::RegisterContextDarwin_x86_64 (lldb_private::Thread & thread, uint32_t concrete_frame_idx)
Definition at line 454 of file RegisterContextDarwin_x86_64.cpp.
References exc, exc_errs, fpu, fpu_errs, gpr, gpr_errs, kNumErrors, and lldb_private::RegisterContext::RegisterContext().
Referenced by RegisterContextDarwin_x86_64_Mach::RegisterContextDarwin_x86_64_Mach(), and RegisterContextKDP_x86_64::RegisterContextKDP_x86_64().
~RegisterContextDarwin_x86_64()
RegisterContextDarwin_x86_64::~RegisterContextDarwin_x86_64 () override default
Member Function Documentation
ConvertRegisterKindToRegisterNumber()
uint32_t RegisterContextDarwin_x86_64::ConvertRegisterKindToRegisterNumber (lldb::RegisterKind kind, uint32_t num) override virtual
Convert from a given register numbering scheme to the lldb register numbering scheme.
There may be multiple ways to enumerate the registers for a given architecture. ABI references will specify one to be used with DWARF, the register numberings from process plugin, there may be a variation used for eh_frame unwind instructions (e.g. on Darwin), and so on. Register 5 by itself is meaningless - RegisterKind enumeration tells you what context that number should be translated as.
Inside lldb, register numbers are in the eRegisterKindLLDB scheme; arguments which take a register number should take one in that scheme.
eRegisterKindGeneric is a special numbering scheme which gives us constant values for the pc, frame register, stack register, etc., for use within lldb. They may not be defined for all architectures but it allows generic code to translate these common registers into the lldb numbering scheme.
This method translates a given register kind + register number into the eRegisterKindLLDB register numbering.
Parameters
[in] kind The register numbering scheme (RegisterKind) that the following register number is in.
[in] num A register number in the 'kind' register numbering scheme.
Returns
The equivalent register number in the eRegisterKindLLDB numbering scheme, if possible, else LLDB_INVALID_REGNUM.
Reimplemented from lldb_private::RegisterContext.
Definition at line 923 of file RegisterContextDarwin_x86_64.cpp.
References ehframe_dwarf_fpu_stmm0, ehframe_dwarf_fpu_stmm1, ehframe_dwarf_fpu_stmm2, ehframe_dwarf_fpu_stmm3, ehframe_dwarf_fpu_stmm4, ehframe_dwarf_fpu_stmm5, ehframe_dwarf_fpu_stmm6, ehframe_dwarf_fpu_stmm7, ehframe_dwarf_fpu_xmm0, ehframe_dwarf_fpu_xmm1, ehframe_dwarf_fpu_xmm10, ehframe_dwarf_fpu_xmm11, ehframe_dwarf_fpu_xmm12, ehframe_dwarf_fpu_xmm13, ehframe_dwarf_fpu_xmm14, ehframe_dwarf_fpu_xmm15, ehframe_dwarf_fpu_xmm2, ehframe_dwarf_fpu_xmm3, ehframe_dwarf_fpu_xmm4, ehframe_dwarf_fpu_xmm5, ehframe_dwarf_fpu_xmm6, ehframe_dwarf_fpu_xmm7, ehframe_dwarf_fpu_xmm8, ehframe_dwarf_fpu_xmm9, ehframe_dwarf_gpr_r10, ehframe_dwarf_gpr_r11, ehframe_dwarf_gpr_r12, ehframe_dwarf_gpr_r13, ehframe_dwarf_gpr_r14, ehframe_dwarf_gpr_r15, ehframe_dwarf_gpr_r8, ehframe_dwarf_gpr_r9, ehframe_dwarf_gpr_rax, ehframe_dwarf_gpr_rbp, ehframe_dwarf_gpr_rbx, ehframe_dwarf_gpr_rcx, ehframe_dwarf_gpr_rdi, ehframe_dwarf_gpr_rdx, ehframe_dwarf_gpr_rip, ehframe_dwarf_gpr_rsi, ehframe_dwarf_gpr_rsp, lldb::eRegisterKindDWARF, lldb::eRegisterKindEHFrame, lldb::eRegisterKindGeneric, lldb::eRegisterKindLLDB, fpu_stmm0, fpu_stmm1, fpu_stmm2, fpu_stmm3, fpu_stmm4, fpu_stmm5, fpu_stmm6, fpu_stmm7, fpu_xmm0, fpu_xmm1, fpu_xmm10, fpu_xmm11, fpu_xmm12, fpu_xmm13, fpu_xmm14, fpu_xmm15, fpu_xmm2, fpu_xmm3, fpu_xmm4, fpu_xmm5, fpu_xmm6, fpu_xmm7, fpu_xmm8, fpu_xmm9, gpr_r10, gpr_r11, gpr_r12, gpr_r13, gpr_r14, gpr_r15, gpr_r8, gpr_r9, gpr_rax, gpr_rbp, gpr_rbx, gpr_rcx, gpr_rdi, gpr_rdx, gpr_rflags, gpr_rip, gpr_rsi, gpr_rsp, LLDB_INVALID_REGNUM, LLDB_REGNUM_GENERIC_FLAGS, LLDB_REGNUM_GENERIC_FP, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_RA, and LLDB_REGNUM_GENERIC_SP.
DoReadEXC()
virtual int RegisterContextDarwin_x86_64::DoReadEXC (lldb::tid_t tid, int flavor, EXC & exc) protected pure virtual
Implemented in RegisterContextDarwin_x86_64_Mach, RegisterContextKDP_x86_64, and RegisterContextMach_x86_64.
References exc.
Referenced by ReadEXC().
DoReadFPU()
virtual int RegisterContextDarwin_x86_64::DoReadFPU (lldb::tid_t tid, int flavor, FPU & fpu) protected pure virtual
Implemented in RegisterContextDarwin_x86_64_Mach, RegisterContextKDP_x86_64, and RegisterContextMach_x86_64.
References fpu.
Referenced by ReadFPU().
DoReadGPR()
virtual int RegisterContextDarwin_x86_64::DoReadGPR (lldb::tid_t tid, int flavor, GPR & gpr) protected pure virtual
Implemented in RegisterContextDarwin_x86_64_Mach, RegisterContextKDP_x86_64, and RegisterContextMach_x86_64.
References gpr.
Referenced by ReadGPR().
DoWriteEXC()
virtual int RegisterContextDarwin_x86_64::DoWriteEXC (lldb::tid_t tid, int flavor, const EXC & exc) protected pure virtual
Implemented in RegisterContextDarwin_x86_64_Mach, RegisterContextKDP_x86_64, and RegisterContextMach_x86_64.
References exc.
Referenced by WriteEXC().
DoWriteFPU()
virtual int RegisterContextDarwin_x86_64::DoWriteFPU (lldb::tid_t tid, int flavor, const FPU & fpu) protected pure virtual
Implemented in RegisterContextDarwin_x86_64_Mach, RegisterContextKDP_x86_64, and RegisterContextMach_x86_64.
References fpu.
Referenced by WriteFPU().
DoWriteGPR()
virtual int RegisterContextDarwin_x86_64::DoWriteGPR (lldb::tid_t tid, int flavor, const GPR & gpr) protected pure virtual
Implemented in RegisterContextDarwin_x86_64_Mach, RegisterContextKDP_x86_64, and RegisterContextMach_x86_64.
References gpr.
Referenced by WriteGPR().
GetError()
int RegisterContextDarwin_x86_64::GetError (int flavor, uint32_t err_idx) const inline protected
Definition at line 131 of file RegisterContextDarwin_x86_64.h.
References exc_errs, EXCRegSet, fpu_errs, FPURegSet, gpr_errs, GPRRegSet, and kNumErrors.
Referenced by ReadEXC(), ReadFPU(), ReadGPR(), RegisterSetIsCached(), WriteEXC(), WriteFPU(), and WriteGPR().
GetRegisterCount()
size_t RegisterContextDarwin_x86_64::GetRegisterCount () override virtual
Implements lldb_private::RegisterContext.
Definition at line 471 of file RegisterContextDarwin_x86_64.cpp.
References k_num_register_infos, and k_num_registers.
GetRegisterInfoAtIndex()
const RegisterInfo * RegisterContextDarwin_x86_64::GetRegisterInfoAtIndex (size_t reg) override virtual
Implements lldb_private::RegisterContext.
Definition at line 477 of file RegisterContextDarwin_x86_64.cpp.
References g_register_infos, k_num_register_infos, and k_num_registers.
GetRegisterInfos()
const lldb_private::RegisterInfo * RegisterContextDarwin_x86_64::GetRegisterInfos () static protected
Definition at line 489 of file RegisterContextDarwin_x86_64.cpp.
References g_register_infos.
GetRegisterInfosCount()
size_t RegisterContextDarwin_x86_64::GetRegisterInfosCount () static protected
Definition at line 484 of file RegisterContextDarwin_x86_64.cpp.
References k_num_register_infos.
GetRegisterNumber()
uint32_t RegisterContextDarwin_x86_64::GetRegisterNumber (uint32_t reg_kind, uint32_t reg_num) static protected
GetRegisterSet()
const RegisterSet * RegisterContextDarwin_x86_64::GetRegisterSet (size_t set) override virtual
Implements lldb_private::RegisterContext.
Definition at line 530 of file RegisterContextDarwin_x86_64.cpp.
References g_reg_sets, and k_num_regsets.
GetRegisterSetCount()
size_t RegisterContextDarwin_x86_64::GetRegisterSetCount () override virtual
Implements lldb_private::RegisterContext.
Definition at line 525 of file RegisterContextDarwin_x86_64.cpp.
References k_num_regsets.
GetSetForNativeRegNum()
int RegisterContextDarwin_x86_64::GetSetForNativeRegNum (int reg_num) static protected
Definition at line 536 of file RegisterContextDarwin_x86_64.cpp.
References exc_trapno, EXCRegSet, fpu_fcw, FPURegSet, GPRRegSet, and k_num_registers.
Referenced by ReadRegister(), and WriteRegister().
HardwareSingleStep()
bool RegisterContextDarwin_x86_64::HardwareSingleStep (bool enable) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 1032 of file RegisterContextDarwin_x86_64.cpp.
References gpr, ReadGPR(), and WriteGPR().
InvalidateAllRegisters()
void RegisterContextDarwin_x86_64::InvalidateAllRegisters () override virtual
Implements lldb_private::RegisterContext.
Reimplemented in RegisterContextDarwin_x86_64_Mach.
Definition at line 467 of file RegisterContextDarwin_x86_64.cpp.
References InvalidateAllRegisterStates().
InvalidateAllRegisterStates()
void RegisterContextDarwin_x86_64::InvalidateAllRegisterStates () inline protected
Definition at line 125 of file RegisterContextDarwin_x86_64.h.
References EXCRegSet, FPURegSet, GPRRegSet, Read, and SetError().
Referenced by InvalidateAllRegisters().
LogGPR()
void RegisterContextDarwin_x86_64::LogGPR (lldb_private::Log * log, const char * format, ...) protected
ReadAllRegisterValues()
bool RegisterContextDarwin_x86_64::ReadAllRegisterValues (lldb::WritableDataBufferSP & data_sp) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 883 of file RegisterContextDarwin_x86_64.cpp.
References exc, fpu, gpr, ReadEXC(), ReadFPU(), ReadGPR(), and REG_CONTEXT_SIZE.
ReadEXC()
int RegisterContextDarwin_x86_64::ReadEXC (bool force) protected
Definition at line 562 of file RegisterContextDarwin_x86_64.cpp.
References DoReadEXC(), exc, EXCRegSet, GetError(), lldb_private::RegisterContext::GetThreadID(), Read, RegisterSetIsCached(), and SetError().
Referenced by ReadAllRegisterValues(), and ReadRegisterSet().
ReadFPU()
int RegisterContextDarwin_x86_64::ReadFPU (bool force) protected
Definition at line 554 of file RegisterContextDarwin_x86_64.cpp.
References DoReadFPU(), fpu, FPURegSet, GetError(), lldb_private::RegisterContext::GetThreadID(), Read, RegisterSetIsCached(), and SetError().
Referenced by ReadAllRegisterValues(), and ReadRegisterSet().
ReadGPR()
int RegisterContextDarwin_x86_64::ReadGPR (bool force) protected
Definition at line 546 of file RegisterContextDarwin_x86_64.cpp.
References DoReadGPR(), GetError(), lldb_private::RegisterContext::GetThreadID(), gpr, GPRRegSet, Read, RegisterSetIsCached(), and SetError().
Referenced by HardwareSingleStep(), ReadAllRegisterValues(), and ReadRegisterSet().
ReadRegister()
bool RegisterContextDarwin_x86_64::ReadRegister (const lldb_private::RegisterInfo * reg_info, lldb_private::RegisterValue & value) override virtual
Implements lldb_private::RegisterContext.
Definition at line 632 of file RegisterContextDarwin_x86_64.cpp.
References lldb_private::RegisterInfo::byte_size, lldb::eRegisterKindLLDB, exc, exc_err, exc_faultvaddr, exc_trapno, fpu, fpu_cs, fpu_dp, fpu_ds, fpu_fcw, fpu_fop, fpu_fsw, fpu_ftw, fpu_ip, fpu_mxcsr, fpu_mxcsrmask, fpu_stmm0, fpu_stmm1, fpu_stmm2, fpu_stmm3, fpu_stmm4, fpu_stmm5, fpu_stmm6, fpu_stmm7, fpu_xmm0, fpu_xmm1, fpu_xmm10, fpu_xmm11, fpu_xmm12, fpu_xmm13, fpu_xmm14, fpu_xmm15, fpu_xmm2, fpu_xmm3, fpu_xmm4, fpu_xmm5, fpu_xmm6, fpu_xmm7, fpu_xmm8, fpu_xmm9, GetSetForNativeRegNum(), gpr, gpr_cs, gpr_fs, gpr_gs, gpr_r10, gpr_r11, gpr_r12, gpr_r13, gpr_r14, gpr_r15, gpr_r8, gpr_r9, gpr_rax, gpr_rbp, gpr_rbx, gpr_rcx, gpr_rdi, gpr_rdx, gpr_rflags, gpr_rip, gpr_rsi, gpr_rsp, lldb_private::endian::InlHostByteOrder(), lldb_private::RegisterInfo::kinds, ReadRegisterSet(), and lldb_private::RegisterValue::SetBytes().
ReadRegisterSet()
int RegisterContextDarwin_x86_64::ReadRegisterSet (uint32_t set, bool force) protected
Definition at line 603 of file RegisterContextDarwin_x86_64.cpp.
References EXCRegSet, FPURegSet, GPRRegSet, ReadEXC(), ReadFPU(), and ReadGPR().
Referenced by ReadRegister(), and WriteRegister().
RegisterSetIsCached()
bool RegisterContextDarwin_x86_64::RegisterSetIsCached (int set) const inline protected
Definition at line 171 of file RegisterContextDarwin_x86_64.h.
References GetError(), and Read.
Referenced by ReadEXC(), ReadFPU(), ReadGPR(), WriteEXC(), WriteFPU(), and WriteGPR().
SetError()
bool RegisterContextDarwin_x86_64::SetError (int flavor, uint32_t err_idx, int err) inline protected
Definition at line 149 of file RegisterContextDarwin_x86_64.h.
References exc_errs, EXCRegSet, fpu_errs, FPURegSet, gpr_errs, GPRRegSet, and kNumErrors.
Referenced by InvalidateAllRegisterStates(), ReadEXC(), ReadFPU(), ReadGPR(), RegisterContextDarwin_x86_64_Mach::SetRegisterDataFrom_LC_THREAD(), WriteEXC(), WriteFPU(), and WriteGPR().
WriteAllRegisterValues()
bool RegisterContextDarwin_x86_64::WriteAllRegisterValues (const lldb::DataBufferSP & data_sp) override virtual
Reimplemented from lldb_private::RegisterContext.
Definition at line 900 of file RegisterContextDarwin_x86_64.cpp.
References exc, fpu, gpr, REG_CONTEXT_SIZE, WriteEXC(), WriteFPU(), and WriteGPR().
WriteEXC()
int RegisterContextDarwin_x86_64::WriteEXC () protected
Definition at line 592 of file RegisterContextDarwin_x86_64.cpp.
References DoWriteEXC(), exc, EXCRegSet, GetError(), lldb_private::RegisterContext::GetThreadID(), Read, RegisterSetIsCached(), SetError(), and Write.
Referenced by WriteAllRegisterValues(), and WriteRegisterSet().
WriteFPU()
int RegisterContextDarwin_x86_64::WriteFPU () protected
Definition at line 581 of file RegisterContextDarwin_x86_64.cpp.
References DoWriteFPU(), fpu, FPURegSet, GetError(), lldb_private::RegisterContext::GetThreadID(), Read, RegisterSetIsCached(), SetError(), and Write.
Referenced by WriteAllRegisterValues(), and WriteRegisterSet().
WriteGPR()
int RegisterContextDarwin_x86_64::WriteGPR () protected
Definition at line 570 of file RegisterContextDarwin_x86_64.cpp.
References DoWriteGPR(), GetError(), lldb_private::RegisterContext::GetThreadID(), gpr, GPRRegSet, Read, RegisterSetIsCached(), SetError(), and Write.
Referenced by HardwareSingleStep(), WriteAllRegisterValues(), and WriteRegisterSet().
WriteRegister()
bool RegisterContextDarwin_x86_64::WriteRegister (const lldb_private::RegisterInfo * reg_info, const lldb_private::RegisterValue & value) override virtual
Implements lldb_private::RegisterContext.
Definition at line 757 of file RegisterContextDarwin_x86_64.cpp.
References lldb::eRegisterKindLLDB, exc, exc_err, exc_faultvaddr, exc_trapno, fpu, fpu_cs, fpu_dp, fpu_ds, fpu_fcw, fpu_fop, fpu_fsw, fpu_ftw, fpu_ip, fpu_mxcsr, fpu_mxcsrmask, fpu_stmm0, fpu_stmm1, fpu_stmm2, fpu_stmm3, fpu_stmm4, fpu_stmm5, fpu_stmm6, fpu_stmm7, fpu_xmm0, fpu_xmm1, fpu_xmm10, fpu_xmm11, fpu_xmm12, fpu_xmm13, fpu_xmm14, fpu_xmm15, fpu_xmm2, fpu_xmm3, fpu_xmm4, fpu_xmm5, fpu_xmm6, fpu_xmm7, fpu_xmm8, fpu_xmm9, lldb_private::RegisterValue::GetAsUInt16(), lldb_private::RegisterValue::GetAsUInt32(), lldb_private::RegisterValue::GetAsUInt64(), lldb_private::RegisterValue::GetAsUInt8(), lldb_private::RegisterValue::GetBytes(), lldb_private::RegisterValue::GetByteSize(), GetSetForNativeRegNum(), gpr, gpr_cs, gpr_fs, gpr_gs, gpr_r10, gpr_r11, gpr_r12, gpr_r13, gpr_r14, gpr_r15, gpr_r8, gpr_r9, gpr_rax, gpr_rbp, gpr_rbx, gpr_rcx, gpr_rdi, gpr_rdx, gpr_rflags, gpr_rip, gpr_rsi, gpr_rsp, lldb_private::RegisterInfo::kinds, ReadRegisterSet(), and WriteRegisterSet().
WriteRegisterSet()
int RegisterContextDarwin_x86_64::WriteRegisterSet (uint32_t set) protected
Definition at line 617 of file RegisterContextDarwin_x86_64.cpp.
References EXCRegSet, FPURegSet, GPRRegSet, WriteEXC(), WriteFPU(), and WriteGPR().
Referenced by WriteRegister().
Member Data Documentation
exc
EXC RegisterContextDarwin_x86_64::exc protected
Definition at line 120 of file RegisterContextDarwin_x86_64.h.
Referenced by DoReadEXC(), RegisterContextDarwin_x86_64_Mach::DoReadEXC(), RegisterContextKDP_x86_64::DoReadEXC(), RegisterContextMach_x86_64::DoReadEXC(), DoWriteEXC(), RegisterContextDarwin_x86_64_Mach::DoWriteEXC(), RegisterContextKDP_x86_64::DoWriteEXC(), RegisterContextMach_x86_64::DoWriteEXC(), ReadAllRegisterValues(), ReadEXC(), ReadRegister(), RegisterContextDarwin_x86_64(), RegisterContextDarwin_x86_64_Mach::SetRegisterDataFrom_LC_THREAD(), WriteAllRegisterValues(), WriteEXC(), WriteRegister(), and RegisterContextKDP_x86_64::~RegisterContextKDP_x86_64().
exc_errs
int RegisterContextDarwin_x86_64::exc_errs[2] protected
Definition at line 123 of file RegisterContextDarwin_x86_64.h.
Referenced by GetError(), RegisterContextDarwin_x86_64(), and SetError().
fpu
FPU RegisterContextDarwin_x86_64::fpu protected
Definition at line 119 of file RegisterContextDarwin_x86_64.h.
Referenced by DoReadFPU(), RegisterContextDarwin_x86_64_Mach::DoReadFPU(), RegisterContextKDP_x86_64::DoReadFPU(), RegisterContextMach_x86_64::DoReadFPU(), DoWriteFPU(), RegisterContextDarwin_x86_64_Mach::DoWriteFPU(), RegisterContextKDP_x86_64::DoWriteFPU(), RegisterContextMach_x86_64::DoWriteFPU(), ReadAllRegisterValues(), ReadFPU(), ReadRegister(), RegisterContextDarwin_x86_64(), WriteAllRegisterValues(), WriteFPU(), WriteRegister(), and RegisterContextKDP_x86_64::~RegisterContextKDP_x86_64().
fpu_errs
int RegisterContextDarwin_x86_64::fpu_errs[2] protected
Definition at line 122 of file RegisterContextDarwin_x86_64.h.
Referenced by GetError(), RegisterContextDarwin_x86_64(), and SetError().
gpr
GPR RegisterContextDarwin_x86_64::gpr protected
Definition at line 118 of file RegisterContextDarwin_x86_64.h.
Referenced by DoReadGPR(), RegisterContextDarwin_x86_64_Mach::DoReadGPR(), RegisterContextKDP_x86_64::DoReadGPR(), RegisterContextMach_x86_64::DoReadGPR(), DoWriteGPR(), RegisterContextDarwin_x86_64_Mach::DoWriteGPR(), RegisterContextKDP_x86_64::DoWriteGPR(), RegisterContextMach_x86_64::DoWriteGPR(), HardwareSingleStep(), ReadAllRegisterValues(), ReadGPR(), ReadRegister(), RegisterContextDarwin_x86_64(), RegisterContextDarwin_x86_64_Mach::SetRegisterDataFrom_LC_THREAD(), WriteAllRegisterValues(), WriteGPR(), WriteRegister(), and RegisterContextKDP_x86_64::~RegisterContextKDP_x86_64().
gpr_errs
int RegisterContextDarwin_x86_64::gpr_errs[2] protected
Definition at line 121 of file RegisterContextDarwin_x86_64.h.
Referenced by GetError(), RegisterContextDarwin_x86_64(), and SetError().
The documentation for this class was generated from the following files:
RegisterContextDarwin_x86_64.h
RegisterContextDarwin_x86_64.cpp