LLDB: ObjectFileMachO Class Reference
ObjectFileMachO Class Reference
#include <ObjectFileMachO.h>
Classes
struct DyldInfoCommandLargeOffsets
struct DysymtabCommandLargeOffsets
The LC_DYSYMTAB's dysymtab_command has 32-bit file offsets that we will use as virtual address offsets, and may need to span more than 4GB in virtual memory.
struct LCNoteEntry
struct LinkeditDataCommandLargeOffsets
struct MachOCorefileAllImageInfos
struct MachOCorefileImageEntry
A corefile may include metadata about all of the binaries that were present in the process when the corefile was taken.
struct SegmentParsingContext
struct SymtabCommandLargeOffsets
Public Member Functions
ObjectFileMachO (const lldb::ModuleSP &module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const lldb_private::FileSpec *file, lldb::offset_t offset, lldb::offset_t length)
ObjectFileMachO (const lldb::ModuleSP &module_sp, lldb::WritableDataBufferSP data_sp, const lldb::ProcessSP &process_sp, lldb::addr_t header_addr)
~ObjectFileMachO () override=default
bool isA (const void *ClassID) const override
bool ParseHeader () override
Attempts to parse the object header.
bool SetLoadAddress (lldb_private::Target &target, lldb::addr_t value, bool value_is_offset) override
Sets the load address for an entire module, assuming a rigid slide of sections, if possible in the implementation.
lldb::ByteOrder GetByteOrder () const override
Gets whether endian swapping should occur when extracting data from this object file.
bool IsExecutable () const override
Tells whether this object file is capable of being the main executable for a process.
bool IsDynamicLoader () const
bool IsSharedCacheBinary () const
bool IsKext () const
uint32_t GetAddressByteSize () const override
Gets the address size in bytes for the current object file.
lldb_private::AddressClass GetAddressClass (lldb::addr_t file_addr) override
Get the address type given a file address in an object file.
void ParseSymtab (lldb_private::Symtab &symtab) override
Parse the symbol table into the provides symbol table object.
bool IsStripped () override
Detect if this object file has been stripped of local symbols.
void CreateSections (lldb_private::SectionList &unified_section_list) override
void Dump (lldb_private::Stream *s) override
Dump a description of this object to a Stream.
lldb_private::ArchSpec GetArchitecture () override
Get the ArchSpec for this object file.
lldb_private::UUID GetUUID () override
Gets the UUID for this object file.
uint32_t GetDependentModules (lldb_private::FileSpecList &files) override
Extract the dependent modules from an object file.
lldb_private::FileSpecList GetReExportedLibraries () override
Gets the file spec list of libraries re-exported by this object file.
lldb_private::Address GetEntryPointAddress () override
Returns the address of the Entry Point in this object file - if the object file doesn't have an entry point (because it is not an executable file) then an invalid address is returned.
lldb_private::Address GetBaseAddress () override
Returns base address of this object file.
uint32_t GetNumThreadContexts () override
std::vector< std::tuple< lldb::offset_t, lldb::offset_t > > FindLC_NOTEByName (std::string name)
std::string GetIdentifierString () override
Some object files may have an identifier string embedded in them, e.g.
lldb_private::AddressableBits GetAddressableBits () override
Some object files may have the number of bits used for addressing embedded in them, e.g.
bool GetCorefileMainBinaryInfo (lldb::addr_t &value, bool &value_is_offset, lldb_private::UUID &uuid, ObjectFile::BinaryType &type) override
bool GetCorefileThreadExtraInfos (std::vector< lldb::tid_t > &tids) override
Get metadata about thread ids from the corefile.
lldb_private::StructuredData::ObjectSP GetCorefileProcessMetadata () override
Get process metadata from the corefile in a StructuredData dictionary.
bool LoadCoreFileImages (lldb_private::Process &process) override
Load binaries listed in a corefile.
lldb::RegisterContextSP GetThreadContextAtIndex (uint32_t idx, lldb_private::Thread &thread) override
ObjectFile::Type CalculateType () override
The object file should be able to calculate its type by looking at its file header and possibly the sections or other data in the object file.
ObjectFile::Strata CalculateStrata () override
The object file should be able to calculate the strata of the object file.
llvm::VersionTuple GetVersion () override
Get the object file version numbers.
llvm::VersionTuple GetMinimumOSVersion () override
Get the minimum OS version this object file can run on.
llvm::VersionTuple GetSDKVersion () override
Get the SDK OS version this object file was built with.
bool GetIsDynamicLinkEditor () override
Return true if this file is a dynamic link editor (dyld)
bool CanTrustAddressRanges () override
Can we trust the address ranges accelerator associated with this object file to be complete.
bool AllowAssemblyEmulationUnwindPlans () override
Returns if the function bounds for symbols in this symbol file are likely accurate.
lldb_private::Section * GetMachHeaderSection ()
bool IsGOTSection (const lldb_private::Section &section) const override
Returns true if the section is a global offset table section.
llvm::StringRef GetPluginName () override
Public Member Functions inherited from lldb_private::ObjectFile
ObjectFile (const lldb::ModuleSP &module_sp, const FileSpec *file_spec_ptr, lldb::offset_t file_offset, lldb::offset_t length, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset)
Construct with a parent module, offset, and header data.
ObjectFile (const lldb::ModuleSP &module_sp, const lldb::ProcessSP &process_sp, lldb::addr_t header_addr, lldb::DataExtractorSP extractor_sp)
~ObjectFile () override
Destructor.
virtual lldb::addr_t GetFileOffset () const
Returns the offset into a file at which this object resides.
virtual lldb::addr_t GetByteSize () const
virtual FileSpec & GetFileSpec ()
Get accessor to the object file specification.
virtual const FileSpec & GetFileSpec () const
Get const accessor to the object file specification.
virtual SectionList * GetSectionList (bool update_module_section_list=true)
Gets the section list for the currently selected architecture (and object for archives).
virtual void SectionFileAddressesChanged ()
Notify the ObjectFile that the file addresses in the Sections for this module have been changed.
Symtab * GetSymtab (bool can_create=true)
Gets the symbol table for the currently selected architecture (and object for archives).
virtual void RelocateSection (lldb_private::Section *section)
Perform relocations on the section if necessary.
virtual void ClearSymtab ()
Frees the symbol table.
virtual lldb_private::Address GetImageInfoAddress (Target *target)
Similar to Process::GetImageInfoAddress().
virtual bool GetCorefileMainBinaryInfo (lldb::addr_t &value, bool &value_is_offset, UUID &uuid, ObjectFile::BinaryType &type)
When the ObjectFile is a core file, lldb needs to locate the "binary" in the core file.
virtual void SetType (Type type)
In cases where the type can't be calculated (elf files), this routine allows someone to explicitly set it.
Type GetType ()
Strata GetStrata ()
size_t GetData (lldb::offset_t offset, size_t length, lldb::DataExtractorSP &data_sp) const
size_t CopyData (lldb::offset_t offset, size_t length, void *dst) const
virtual size_t ReadSectionData (Section *section, lldb::offset_t section_offset, void *dst, size_t dst_len)
virtual size_t ReadSectionData (Section *section, DataExtractor &section_data)
virtual size_t GetSectionDataSize (Section *section)
bool IsInMemory () const
Returns true if the object file exists only in memory.
virtual llvm::StringRef StripLinkerSymbolAnnotations (llvm::StringRef symbol_name) const
virtual std::vector< LoadableData > GetLoadableData (Target &target)
Loads this objfile to memory.
virtual std::unique_ptr< CallFrameInfo > CreateCallFrameInfo ()
Creates a plugin-specific call frame info.
uint32_t GetCacheHash ()
Get a hash that can be used for caching object file releated information.
std::string GetObjectName () const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Public Member Functions inherited from lldb_private::ModuleChild
ModuleChild (const lldb::ModuleSP &module_sp)
Construct with owning module.
~ModuleChild ()
Destructor.
const ModuleChild & operator= (const ModuleChild &rhs)
Assignment operator.
lldb::ModuleSP GetModule () const
Get const accessor for the module pointer.
void SetModule (const lldb::ModuleSP &module_sp)
Set accessor for the module pointer.
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static llvm::StringRef GetPluginNameStatic ()
static llvm::StringRef GetPluginDescriptionStatic ()
static lldb_private::ObjectFile * CreateInstance (const lldb::ModuleSP &module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const lldb_private::FileSpec *file, lldb::offset_t file_offset, lldb::offset_t length)
static lldb_private::ObjectFile * CreateMemoryInstance (const lldb::ModuleSP &module_sp, lldb::WritableDataBufferSP data_sp, const lldb::ProcessSP &process_sp, lldb::addr_t header_addr)
static size_t GetModuleSpecifications (const lldb_private::FileSpec &file, lldb::DataExtractorSP &extractor_sp, lldb::offset_t data_offset, lldb::offset_t file_offset, lldb::offset_t length, lldb_private::ModuleSpecList &specs)
static bool SaveCore (const lldb::ProcessSP &process_sp, lldb_private::SaveCoreOptions &options, lldb_private::Status &error)
static bool MagicBytesMatch (lldb::DataExtractorSP extractor_sp, lldb::addr_t offset, lldb::addr_t length)
static bool classof (const ObjectFile *obj)
static bool ParseHeader (lldb::DataExtractorSP &data, lldb::offset_t *data_offset_ptr, llvm::MachO::mach_header &header)
Static Public Member Functions inherited from lldb_private::ObjectFile
static lldb::ObjectFileSP FindPlugin (const lldb::ModuleSP &module_sp, const FileSpec *file_spec, lldb::offset_t file_offset, lldb::offset_t file_size, lldb::DataExtractorSP extractor_sp, lldb::offset_t &data_offset)
Find a ObjectFile plug-in that can parse file_spec.
static lldb::ObjectFileSP FindPlugin (const lldb::ModuleSP &module_sp, const lldb::ProcessSP &process_sp, lldb::addr_t header_addr, lldb::WritableDataBufferSP file_data_sp)
Find a ObjectFile plug-in that can parse a file in memory.
static size_t GetModuleSpecifications (const FileSpec &file, lldb::offset_t file_offset, lldb::offset_t file_size, ModuleSpecList &specs, lldb::DataExtractorSP=lldb::DataExtractorSP())
static size_t GetModuleSpecifications (const lldb_private::FileSpec &file, lldb::DataExtractorSP &extractor_sp, lldb::offset_t data_offset, lldb::offset_t file_offset, lldb::offset_t file_size, lldb_private::ModuleSpecList &specs)
static bool IsObjectFile (lldb_private::FileSpec file_spec)
static bool SplitArchivePathWithObject (llvm::StringRef path_with_object, lldb_private::FileSpec &archive_file, lldb_private::ConstString &archive_object, bool must_exist)
Split a path into a file path with object name.
static lldb::WritableDataBufferSP ReadMemory (const lldb::ProcessSP &process_sp, lldb::addr_t addr, size_t byte_size)
static lldb::SymbolType GetSymbolTypeFromName (llvm::StringRef name, lldb::SymbolType symbol_type_hint=lldb::eSymbolTypeUndefined)
static lldb::SectionType GetDWARFSectionTypeFromName (llvm::StringRef name)
Parses the section type from a section name for DWARF sections.
static lldb::DataBufferSP MapFileData (const FileSpec &file, uint64_t Size, uint64_t Offset)
Static Public Attributes
static char ID
Static Public Attributes inherited from lldb_private::ObjectFile
static char ID
Protected Types
typedef lldb_private::RangeVector< uint32_t, uint32_t, 8 > EncryptedFileRanges
typedef lldb_private::RangeVector< uint32_t, uint32_t > FileRangeArray
Protected Types inherited from lldb_private::ObjectFile
typedef NonNullSharedPtr< lldb_private::DataExtractor > DataExtractorNSP
Protected Member Functions
void GetProcessSharedCacheUUID (lldb_private::Process *, lldb::addr_t &base_addr, lldb_private::UUID &uuid)
Intended for same-host arm device debugging where lldb needs to detect libraries in the shared cache and augment the nlist entries with an on-disk dyld_shared_cache file.
void GetLLDBSharedCacheUUID (lldb::addr_t &base_addir, lldb_private::UUID &uuid)
Intended for same-host arm device debugging where lldb will read shared cache libraries out of its own memory instead of the remote process' memory as an optimization.
lldb::addr_t CalculateSectionLoadAddressForMemoryImage (lldb::addr_t mach_header_load_address, const lldb_private::Section *mach_header_section, const lldb_private::Section *section)
lldb_private::UUID GetSharedCacheUUID (lldb_private::FileSpec dyld_shared_cache, const lldb::ByteOrder byte_order, const uint32_t addr_byte_size)
size_t ParseSymtab ()
EncryptedFileRanges GetEncryptedFileRanges ()
void ProcessDysymtabCommand (const llvm::MachO::load_command &load_cmd, lldb::offset_t offset)
void ProcessSegmentCommand (const llvm::MachO::load_command &load_cmd, lldb::offset_t offset, uint32_t cmd_idx, SegmentParsingContext &context)
void SanitizeSegmentCommand (llvm::MachO::segment_command_64 &seg_cmd, uint32_t cmd_idx)
bool SectionIsLoadable (const lldb_private::Section *section)
MachOCorefileAllImageInfos GetCorefileAllImageInfos ()
Get the list of binary images that were present in the process when the corefile was produced.
Protected Member Functions inherited from lldb_private::ObjectFile
bool SetModulesArchitecture (const ArchSpec &new_arch)
Sets the architecture for a module.
Static Protected Member Functions
static lldb_private::UUID GetUUID (const llvm::MachO::mach_header &header, const lldb_private::DataExtractor &data, lldb::offset_t lc_offset)
static lldb_private::ArchSpec GetArchitecture (lldb::ModuleSP module_sp, const llvm::MachO::mach_header &header, const lldb_private::DataExtractor &data, lldb::offset_t lc_offset)
static void GetAllArchSpecs (const llvm::MachO::mach_header &header, const lldb_private::DataExtractor &data, lldb::offset_t lc_offset, lldb_private::ModuleSpec &base_spec, lldb_private::ModuleSpecList &all_specs)
Enumerate all ArchSpecs supported by this Mach-O file.
static lldb_private::ConstString GetSegmentNameTEXT ()
static lldb_private::ConstString GetSegmentNameDATA ()
static lldb_private::ConstString GetSegmentNameDATA_DIRTY ()
static lldb_private::ConstString GetSegmentNameDATA_CONST ()
static lldb_private::ConstString GetSegmentNameOBJC ()
static lldb_private::ConstString GetSegmentNameLINKEDIT ()
static lldb_private::ConstString GetSegmentNameDWARF ()
static lldb_private::ConstString GetSegmentNameLLVM_COV ()
static lldb_private::ConstString GetSectionNameEHFrame ()
static lldb_private::ConstString GetSectionNameLLDBNoNlist ()
Protected Attributes
llvm::MachO::mach_header m_header
llvm::MachO::dysymtab_command m_dysymtab
std::vector< llvm::MachO::section_64 > m_mach_sections
std::optional< llvm::VersionTuple > m_min_os_version
std::optional< llvm::VersionTuple > m_sdk_versions
lldb_private::Address m_entry_point_address
FileRangeArray m_thread_context_offsets
lldb::offset_t m_linkedit_original_offset = 0
lldb::addr_t m_text_address = LLDB_INVALID_ADDRESS
bool m_thread_context_offsets_valid
lldb_private::FileSpecList m_reexported_dylibs
bool m_allow_assembly_emulation_unwind_plans
Protected Attributes inherited from lldb_private::ObjectFile
FileSpec m_file
Type m_type
Strata m_strata
lldb::addr_t m_file_offset
The offset in bytes into the file, or the address in memory.
lldb::addr_t m_length
The length of this object file if it is known (can be zero if length is unknown or can't be determined).
DataExtractorNSP m_data_nsp
The data for this object file so things can be parsed lazily.
lldb::ProcessWP m_process_wp
const lldb::addr_t m_memory_addr
Set if the object file only exists in memory.
std::unique_ptr< lldb_private::SectionList > m_sections_up
std::unique_ptr< lldb_private::Symtab > m_symtab_up
std::unique_ptr< llvm::once_flag > m_symtab_once_up
We need a llvm::once_flag that we can use to avoid locking the module lock and deadlocking LLDB.
std::optional< uint32_t > m_cache_hash
Protected Attributes inherited from lldb_private::ModuleChild
lldb::ModuleWP m_module_wp
The Module that owns the object that inherits from this class.
Additional Inherited Members
Public Types inherited from lldb_private::ObjectFile
enum Type {
eTypeInvalid = 0 , eTypeCoreFile , eTypeExecutable , eTypeDebugInfo ,
eTypeDynamicLinker , eTypeObjectFile , eTypeSharedLibrary , eTypeStubLibrary ,
eTypeJIT , eTypeUnknown
}
enum Strata {
eStrataInvalid = 0 , eStrataUnknown , eStrataUser , eStrataKernel ,
eStrataRawImage , eStrataJIT
}
enum BinaryType {
eBinaryTypeInvalid = 0 , eBinaryTypeUnknown , eBinaryTypeKernel , eBinaryTypeUser ,
eBinaryTypeUserAllImageInfos , eBinaryTypeStandalone
}
If we have a corefile binary hint, this enum specifies the binary type which we can use to select the correct DynamicLoader plugin.
Static Protected Attributes inherited from lldb_private::ObjectFile
static size_t g_initial_bytes_to_read = 512
The number of bytes to read when going through the plugins.
Detailed Description
Definition at line 25 of file ObjectFileMachO.h.
Member Typedef Documentation
EncryptedFileRanges
typedef lldb_private::RangeVector<uint32_t, uint32_t, 8> ObjectFileMachO::EncryptedFileRanges protected
Definition at line 223 of file ObjectFileMachO.h.
FileRangeArray
typedef lldb_private::RangeVector<uint32_t, uint32_t> ObjectFileMachO::FileRangeArray protected
Definition at line 439 of file ObjectFileMachO.h.
Constructor & Destructor Documentation
ObjectFileMachO() [1/2]
ObjectFileMachO::ObjectFileMachO (const lldb::ModuleSP & module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const lldb_private::FileSpec * file, lldb::offset_t offset, lldb::offset_t length)
Definition at line 932 of file ObjectFileMachO.cpp.
References m_allow_assembly_emulation_unwind_plans, m_dysymtab, m_entry_point_address, m_header, m_mach_sections, m_reexported_dylibs, m_thread_context_offsets, m_thread_context_offsets_valid, and lldb_private::ObjectFile::ObjectFile().
Referenced by CreateMemoryInstance().
ObjectFileMachO() [2/2]
ObjectFileMachO::ObjectFileMachO (const lldb::ModuleSP & module_sp, lldb::WritableDataBufferSP data_sp, const lldb::ProcessSP & process_sp, lldb::addr_t header_addr)
Definition at line 947 of file ObjectFileMachO.cpp.
References m_allow_assembly_emulation_unwind_plans, m_dysymtab, m_entry_point_address, m_header, m_mach_sections, m_reexported_dylibs, m_thread_context_offsets, m_thread_context_offsets_valid, and lldb_private::ObjectFile::ObjectFile().
~ObjectFileMachO()
ObjectFileMachO::~ObjectFileMachO () override default
Member Function Documentation
AllowAssemblyEmulationUnwindPlans()
bool ObjectFileMachO::AllowAssemblyEmulationUnwindPlans () override virtual
Returns if the function bounds for symbols in this symbol file are likely accurate.
The unwinder can emulate the instructions of functions to understand prologue/epilogue code sequences, where registers are spilled on the stack, etc. This feature relies on having the correct start addresses of all functions. If the ObjectFile has a way to tell that symbols have been stripped and there's no way to reconstruct start addresses (e.g. LC_FUNCTION_STARTS on Mach-O, or eh_frame unwind info), the ObjectFile should indicate that assembly emulation should not be used for this module.
It is uncommon for this to return false. An ObjectFile needs to be sure that symbol start addresses are unavailable before false is returned. If it is unclear, this should return true.
Returns
Returns true if assembly emulation should be used for this module. Only returns false if the ObjectFile is sure that symbol addresses are insufficient for accurate assembly emulation.
Reimplemented from lldb_private::ObjectFile.
Definition at line 5919 of file ObjectFileMachO.cpp.
References m_allow_assembly_emulation_unwind_plans.
CalculateSectionLoadAddressForMemoryImage()
lldb::addr_t ObjectFileMachO::CalculateSectionLoadAddressForMemoryImage (lldb::addr_t mach_header_load_address, const lldb_private::Section * mach_header_section, const lldb_private::Section * section) protected
Definition at line 5995 of file ObjectFileMachO.cpp.
References lldb_private::Section::GetFileAddress(), lldb_private::ModuleChild::GetModule(), LLDB_INVALID_ADDRESS, and SectionIsLoadable().
Referenced by ParseSymtab(), and SetLoadAddress().
CalculateStrata()
ObjectFile::Strata ObjectFileMachO::CalculateStrata () override virtual
The object file should be able to calculate the strata of the object file.
Many object files for platforms might be for either user space debugging or for kernel debugging. If your object file subclass can figure this out, it will help with debugger plug-in selection when it comes time to debug.
Returns
The calculated object file strata for the current object file.
Implements lldb_private::ObjectFile.
Definition at line 5627 of file ObjectFileMachO.cpp.
References lldb_private::ObjectFile::eStrataKernel, lldb_private::ObjectFile::eStrataRawImage, lldb_private::ObjectFile::eStrataUnknown, lldb_private::ObjectFile::eStrataUser, lldb_private::ObjectFile::eTypeInvalid, lldb_private::ObjectFile::eTypeSharedLibrary, lldb_private::SectionList::FindSectionByName(), lldb_private::ObjectFile::GetSectionList(), GetUUID(), m_header, and lldb_private::ObjectFile::m_type.
Referenced by ParseSymtab().
CalculateType()
ObjectFile::Type ObjectFileMachO::CalculateType () override virtual
The object file should be able to calculate its type by looking at its file header and possibly the sections or other data in the object file.
The file type is used in the debugger to help select the correct plug- ins for the job at hand, so this is important to get right. If any eTypeXXX definitions do not match up with the type of file you are loading, please feel free to add a new enumeration value.
Returns
The calculated file type for the current object file.
Implements lldb_private::ObjectFile.
Definition at line 5584 of file ObjectFileMachO.cpp.
References lldb_private::ObjectFile::eStrataInvalid, lldb_private::ObjectFile::eStrataKernel, lldb_private::ObjectFile::eTypeCoreFile, lldb_private::ObjectFile::eTypeDebugInfo, lldb_private::ObjectFile::eTypeDynamicLinker, lldb_private::ObjectFile::eTypeExecutable, lldb_private::ObjectFile::eTypeObjectFile, lldb_private::ObjectFile::eTypeSharedLibrary, lldb_private::ObjectFile::eTypeStubLibrary, lldb_private::ObjectFile::eTypeUnknown, GetAddressByteSize(), GetUUID(), m_header, and lldb_private::ObjectFile::m_strata.
Referenced by GetDependentModules().
CanTrustAddressRanges()
bool ObjectFileMachO::CanTrustAddressRanges () override virtual
Can we trust the address ranges accelerator associated with this object file to be complete.
Reimplemented from lldb_private::ObjectFile.
Definition at line 5913 of file ObjectFileMachO.cpp.
References m_header.
classof()
bool ObjectFileMachO::classof (const ObjectFile * obj) inline static
Definition at line 79 of file ObjectFileMachO.h.
References ID, and lldb_private::ObjectFile::ObjectFile().
CreateInstance()
ObjectFile * ObjectFileMachO::CreateInstance (const lldb::ModuleSP & module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const lldb_private::FileSpec * file, lldb::offset_t file_offset, lldb::offset_t length) static
Definition at line 783 of file ObjectFileMachO.cpp.
References MagicBytesMatch(), lldb_private::ObjectFile::MapFileData(), and lldb_private::ObjectFile::ObjectFile().
Referenced by Initialize(), and Terminate().
CreateMemoryInstance()
ObjectFile * ObjectFileMachO::CreateMemoryInstance (const lldb::ModuleSP & module_sp, lldb::WritableDataBufferSP data_sp, const lldb::ProcessSP & process_sp, lldb::addr_t header_addr) static
Definition at line 816 of file ObjectFileMachO.cpp.
References MagicBytesMatch(), lldb_private::ObjectFile::ObjectFile(), and ObjectFileMachO().
Referenced by Initialize().
CreateSections()
void ObjectFileMachO::CreateSections (lldb_private::SectionList & unified_section_list) override virtual
Implements lldb_private::ObjectFile.
Definition at line 1870 of file ObjectFileMachO.cpp.
References ObjectFileMachO::SegmentParsingContext::FileAddressesChanged, GetEncryptedFileRanges(), lldb_private::ModuleChild::GetModule(), lldb_private::ObjectFile::m_data_nsp, m_header, lldb_private::ObjectFile::m_sections_up, MachHeaderSizeFromMagic(), ProcessDysymtabCommand(), and ProcessSegmentCommand().
Dump()
void ObjectFileMachO::Dump (lldb_private::Stream * s) override virtual
Dump a description of this object to a Stream.
Dump a description of the current contents of this object to the supplied stream s. The dumping should include the section list if it has been parsed, and the symbol table if it has been parsed.
Parameters
[in] s The stream to which to dump the object description.
Implements lldb_private::ObjectFile.
Definition at line 4560 of file ObjectFileMachO.cpp.
References lldb_private::Stream::AsRawOstream(), lldb_private::SectionList::Dump(), lldb_private::eSortOrderNone, GetAllArchSpecs(), lldb_private::ModuleSpec::GetArchitecture(), lldb_private::Stream::GetIndentLevel(), lldb_private::ModuleChild::GetModule(), lldb_private::ModuleSpecList::GetModuleSpecRefAtIndex(), lldb_private::ObjectFile::GetSectionList(), lldb_private::ModuleSpecList::GetSize(), lldb_private::ArchSpec::GetTriple(), lldb_private::Stream::Indent(), lldb_private::ObjectFile::m_data_nsp, lldb_private::ObjectFile::m_file, m_header, lldb_private::ObjectFile::m_symtab_up, MachHeaderSizeFromMagic(), lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and UINT32_MAX.
FindLC_NOTEByName()
std::vector< std::tuple< offset_t, offset_t > > ObjectFileMachO::FindLC_NOTEByName (std::string name)
Definition at line 5209 of file ObjectFileMachO.cpp.
References lldb_private::ModuleChild::GetModule(), lldb_private::ObjectFile::m_data_nsp, m_header, and MachHeaderSizeFromMagic().
Referenced by GetAddressableBits(), GetCorefileAllImageInfos(), GetCorefileMainBinaryInfo(), GetCorefileProcessMetadata(), and GetIdentifierString().
GetAddressableBits()
AddressableBits ObjectFileMachO::GetAddressableBits () override virtual
Some object files may have the number of bits used for addressing embedded in them, e.g.
a Mach-O core file using an LC_NOTE. These object files can return an AddressableBits object that can can be used to set the address masks in the Process.
Returns
Returns an AddressableBits object which can be used to set the address masks in the Process.
Reimplemented from lldb_private::ObjectFile.
Definition at line 5285 of file ObjectFileMachO.cpp.
References FindLC_NOTEByName(), lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), LLDB_LOGF, lldb_private::ObjectFile::m_data_nsp, lldb_private::Process, and lldb_private::AddressableBits::SetAddressableBits().
GetAddressByteSize()
uint32_t ObjectFileMachO::GetAddressByteSize () const override virtual
Gets the address size in bytes for the current object file.
Returns
The size of an address in bytes for the currently selected architecture (and object for archives). Returns zero if no architecture or object has been selected.
Implements lldb_private::ObjectFile.
Definition at line 1124 of file ObjectFileMachO.cpp.
References lldb_private::ObjectFile::m_data_nsp.
Referenced by CalculateType().
GetAddressClass()
AddressClass ObjectFileMachO::GetAddressClass (lldb::addr_t file_addr) override virtual
Get the address type given a file address in an object file.
Many binary file formats know what kinds This is primarily for ARM binaries, though it can be applied to any executable file format that supports different opcode types within the same binary. ARM binaries support having both ARM and Thumb within the same executable container. We need to be able to get
Returns
The size of an address in bytes for the currently selected architecture (and object for archives). Returns zero if no architecture or object has been selected.
Reimplemented from lldb_private::ObjectFile.
Definition at line 1128 of file ObjectFileMachO.cpp.
References lldb_private::eCode, lldb_private::eCodeAlternateISA, lldb_private::eData, lldb_private::eDebug, lldb_private::eRuntime, lldb::eSectionTypeAbsoluteAddress, lldb::eSectionTypeARMexidx, lldb::eSectionTypeARMextab, lldb::eSectionTypeCode, lldb::eSectionTypeCompactUnwind, lldb::eSectionTypeContainer, lldb::eSectionTypeCTF, lldb::eSectionTypeData, lldb::eSectionTypeData16, lldb::eSectionTypeData4, lldb::eSectionTypeData8, lldb::eSectionTypeDataCString, lldb::eSectionTypeDataCStringPointers, lldb::eSectionTypeDataObjCCFStrings, lldb::eSectionTypeDataObjCMessageRefs, lldb::eSectionTypeDataPointers, lldb::eSectionTypeDataSymbolAddress, lldb::eSectionTypeDebug, lldb::eSectionTypeDWARFAppleNames, lldb::eSectionTypeDWARFAppleNamespaces, lldb::eSectionTypeDWARFAppleObjC, lldb::eSectionTypeDWARFAppleTypes, lldb::eSectionTypeDWARFDebugAbbrev, lldb::eSectionTypeDWARFDebugAbbrevDwo, lldb::eSectionTypeDWARFDebugAddr, lldb::eSectionTypeDWARFDebugAranges, lldb::eSectionTypeDWARFDebugCuIndex, lldb::eSectionTypeDWARFDebugFrame, lldb::eSectionTypeDWARFDebugInfo, lldb::eSectionTypeDWARFDebugInfoDwo, lldb::eSectionTypeDWARFDebugLine, lldb::eSectionTypeDWARFDebugLineStr, lldb::eSectionTypeDWARFDebugLoc, lldb::eSectionTypeDWARFDebugLocDwo, lldb::eSectionTypeDWARFDebugLocLists, lldb::eSectionTypeDWARFDebugLocListsDwo, lldb::eSectionTypeDWARFDebugMacInfo, lldb::eSectionTypeDWARFDebugMacro, lldb::eSectionTypeDWARFDebugNames, lldb::eSectionTypeDWARFDebugPubNames, lldb::eSectionTypeDWARFDebugPubTypes, lldb::eSectionTypeDWARFDebugRanges, lldb::eSectionTypeDWARFDebugRngLists, lldb::eSectionTypeDWARFDebugRngListsDwo, lldb::eSectionTypeDWARFDebugStr, lldb::eSectionTypeDWARFDebugStrDwo, lldb::eSectionTypeDWARFDebugStrOffsets, lldb::eSectionTypeDWARFDebugStrOffsetsDwo, lldb::eSectionTypeDWARFDebugTuIndex, lldb::eSectionTypeDWARFDebugTypes, lldb::eSectionTypeDWARFDebugTypesDwo, lldb::eSectionTypeDWARFGNUDebugAltLink, lldb::eSectionTypeEHFrame, lldb::eSectionTypeELFDynamicLinkInfo, lldb::eSectionTypeELFDynamicSymbols, lldb::eSectionTypeELFRelocationEntries, lldb::eSectionTypeELFSymbolTable, lldb::eSectionTypeGoSymtab, lldb::eSectionTypeInvalid, lldb::eSectionTypeLLDBFormatters, lldb::eSectionTypeLLDBTypeSummaries, lldb::eSectionTypeOther, lldb::eSectionTypeSwiftModules, lldb::eSectionTypeWasmName, lldb::eSectionTypeZeroFill, lldb::eSymbolTypeAbsolute, lldb::eSymbolTypeAdditional, lldb::eSymbolTypeAny, lldb::eSymbolTypeBlock, lldb::eSymbolTypeCode, lldb::eSymbolTypeCommonBlock, lldb::eSymbolTypeCompiler, lldb::eSymbolTypeData, lldb::eSymbolTypeException, lldb::eSymbolTypeHeaderFile, lldb::eSymbolTypeInstrumentation, lldb::eSymbolTypeLineEntry, lldb::eSymbolTypeLineHeader, lldb::eSymbolTypeLocal, lldb::eSymbolTypeObjCClass, lldb::eSymbolTypeObjCIVar, lldb::eSymbolTypeObjCMetaClass, lldb::eSymbolTypeObjectFile, lldb::eSymbolTypeParam, lldb::eSymbolTypeReExported, lldb::eSymbolTypeResolver, lldb::eSymbolTypeRuntime, lldb::eSymbolTypeScopeBegin, lldb::eSymbolTypeScopeEnd, lldb::eSymbolTypeSourceFile, lldb::eSymbolTypeTrampoline, lldb::eSymbolTypeUndefined, lldb::eSymbolTypeVariable, lldb::eSymbolTypeVariableType, lldb_private::eUnknown, lldb_private::Symtab::FindSymbolContainingFileAddress(), lldb_private::Symbol::GetAddressRef(), lldb_private::Symbol::GetFlags(), lldb_private::Address::GetSection(), lldb_private::ObjectFile::GetSymtab(), lldb_private::Symbol::GetType(), m_header, MACHO_NLIST_ARM_SYMBOL_IS_THUMB, and lldb_private::Symbol::ValueIsAddress().
GetAllArchSpecs()
void ObjectFileMachO::GetAllArchSpecs (const llvm::MachO::mach_header & header, const lldb_private::DataExtractor & data, lldb::offset_t lc_offset, lldb_private::ModuleSpec & base_spec, lldb_private::ModuleSpecList & all_specs) static protected
Enumerate all ArchSpecs supported by this Mach-O file.
On macOS one Mach-O slice can contain multiple load commands: One load command for being loaded into a macOS process and one load command for being loaded into a macCatalyst process. In contrast to ObjectContainerUniversalMachO, this is the same binary that can be loaded into different contexts.
Definition at line 4715 of file ObjectFileMachO.cpp.
References lldb_private::ModuleSpecList::Append(), lldb_private::eArchTypeMachO, lldb_private::DataExtractor::ExtractBytes(), lldb_private::ModuleSpec::GetArchitecture(), lldb_private::DataExtractor::GetByteOrder(), GetOSName(), lldb_private::ArchSpec::GetTriple(), lldb_private::DataExtractor::GetU32(), GetUUID(), and lldb_private::ArchSpec::SetArchitecture().
Referenced by Dump(), GetArchitecture(), GetModuleSpecifications(), and ParseHeader().
GetArchitecture() [1/2]
ArchSpec ObjectFileMachO::GetArchitecture () override virtual
Get the ArchSpec for this object file.
Returns
The ArchSpec of this object file. In case of error, an invalid ArchSpec object is returned.
Implements lldb_private::ObjectFile.
Definition at line 5720 of file ObjectFileMachO.cpp.
References GetArchitecture(), lldb_private::ModuleChild::GetModule(), lldb_private::ObjectFile::m_data_nsp, m_header, and MachHeaderSizeFromMagic().
Referenced by GetArchitecture(), and ParseSymtab().
GetArchitecture() [2/2]
ArchSpec ObjectFileMachO::GetArchitecture (lldb::ModuleSP module_sp, const llvm::MachO::mach_header & header, const lldb_private::DataExtractor & data, lldb::offset_t lc_offset) static protected
Definition at line 4851 of file ObjectFileMachO.cpp.
References GetAllArchSpecs(), lldb_private::ModuleSpec::GetArchitecture(), lldb_private::ModuleSpecList::GetModuleSpecRefAtIndex(), lldb_private::ModuleSpecList::GetSize(), lldb_private::ArchSpec::IsCompatibleMatch(), and MachHeaderSizeFromMagic().
GetBaseAddress()
lldb_private::Address ObjectFileMachO::GetBaseAddress () override virtual
Returns base address of this object file.
This also sometimes referred to as the "preferred load address" or the "image base address". Addresses within object files are often expressed relative to this base. If this address corresponds to a specific section (usually the first byte of the first section) then the returned address will have this section set. Otherwise, the address will just have the offset member filled in, indicating that this represents a file address.
Reimplemented from lldb_private::ObjectFile.
Definition at line 5168 of file ObjectFileMachO.cpp.
References lldb_private::SectionList::FindSectionByName(), lldb_private::ObjectFile::GetSectionList(), GetSegmentNameTEXT(), lldb_private::Address::SetOffset(), and lldb_private::Address::SetSection().
GetByteOrder()
ByteOrder ObjectFileMachO::GetByteOrder () const override virtual
Gets whether endian swapping should occur when extracting data from this object file.
Returns
Returns true if endian swapping is needed, false otherwise.
Implements lldb_private::ObjectFile.
Definition at line 1104 of file ObjectFileMachO.cpp.
References lldb_private::ObjectFile::m_data_nsp.
GetCorefileAllImageInfos()
ObjectFileMachO::MachOCorefileAllImageInfos ObjectFileMachO::GetCorefileAllImageInfos () protected
Get the list of binary images that were present in the process when the corefile was produced.
Returns
The MachOCorefileAllImageInfos object returned will have IsValid() == false if the information is unavailable.
Definition at line 6711 of file ObjectFileMachO.cpp.
References ObjectFileMachO::MachOCorefileAllImageInfos::all_image_infos, lldb_private::DynamicLoader, FindLC_NOTEByName(), lldb_private::GetLog(), LLDB_LOGF, image_entry::load_address, lldb_private::ObjectFile::m_data_nsp, lldb_private::Object, lldb_private::Process, lldb_private::Symbols, and image_entry::uuid.
Referenced by LoadCoreFileImages().
GetCorefileMainBinaryInfo()
bool ObjectFileMachO::GetCorefileMainBinaryInfo (lldb::addr_t & value, bool & value_is_offset, lldb_private::UUID & uuid, ObjectFile::BinaryType & type) override
Definition at line 5323 of file ObjectFileMachO.cpp.
References lldb_private::UUID::Clear(), lldb_private::DynamicLoader, lldb_private::ObjectFile::eBinaryTypeInvalid, lldb_private::ObjectFile::eBinaryTypeKernel, lldb_private::ObjectFile::eBinaryTypeStandalone, lldb_private::ObjectFile::eBinaryTypeUnknown, lldb_private::ObjectFile::eBinaryTypeUser, lldb_private::ObjectFile::eBinaryTypeUserAllImageInfos, FindLC_NOTEByName(), lldb_private::UUID::GetAsString(), lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), LLDB_INVALID_ADDRESS, LLDB_LOGF, lldb_private::ObjectFile::m_data_nsp, lldb_private::Process, and lldb_private::Symbols.
GetCorefileProcessMetadata()
StructuredData::ObjectSP ObjectFileMachO::GetCorefileProcessMetadata () override virtual
Get process metadata from the corefile in a StructuredData dictionary.
The corefile may have notes (e.g. a Mach-O "process metadata" LC_NOTE) which provide metadata about the process and threads in a JSON or similar format.
Returns
A StructuredData object with the metadata in the note, if there is one. An empty shared pointer is returned if not metadata is found, or a problem parsing it.
Reimplemented from lldb_private::ObjectFile.
Definition at line 5496 of file ObjectFileMachO.cpp.
References FindLC_NOTEByName(), lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), LLDB_LOGF, lldb_private::ObjectFile::m_data_nsp, lldb_private::Object, lldb_private::StructuredData::ParseJSON(), lldb_private::Process, and lldb_private::Thread.
Referenced by GetCorefileThreadExtraInfos().
GetCorefileThreadExtraInfos()
bool ObjectFileMachO::GetCorefileThreadExtraInfos (std::vector< lldb::tid_t > & tids) override virtual
Get metadata about thread ids from the corefile.
The corefile may have metadata (e.g. a Mach-O "process metadata" LC_NOTE) which for the threads in the process; this method tries to retrieve them.
Parameters
[out] tids Filled in with a vector of tid_t's that matches the number of threads in the corefile (ObjectFile::GetNumThreadContexts). If a tid is not specified for one of the corefile threads, that entry in the vector will have LLDB_INVALID_THREAD_ID and the caller should assign a tid to the thread that does not conflict with the ones provided in this array. As additional metadata are added, this method may return a tids vector with no thread id's specified at all; the corefile may only specify one of the other metadata.
Returns
Returns true if thread metadata was found in this corefile.
Reimplemented from lldb_private::ObjectFile.
Definition at line 5444 of file ObjectFileMachO.cpp.
References lldb_private::StructuredData::Object::Dump(), lldb_private::StructuredData::Object::GetAsDictionary(), GetCorefileProcessMetadata(), lldb_private::StreamString::GetData(), lldb_private::StructuredData::Array::GetItemAtIndexAsDictionary(), lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), GetNumThreadContexts(), lldb_private::StructuredData::Array::GetSize(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsArray(), LLDB_INVALID_THREAD_ID, LLDB_LOGF, lldb_private::Object, lldb_private::Stream::Printf(), lldb_private::Process, and lldb_private::Thread.
GetDependentModules()
uint32_t ObjectFileMachO::GetDependentModules (lldb_private::FileSpecList & file_list) override virtual
Extract the dependent modules from an object file.
If an object file has information about which other images it depends on (such as shared libraries), this function will provide the list. Since many executables or shared libraries may depend on the same files, FileSpecList::AppendIfUnique(const FileSpec &) should be used to make sure any files that are added are not already in the list.
Parameters
[out] file_list A list of file specification objects that gets dependent files appended to.
Returns
The number of new files that were appended to file_list.
See also
FileSpecList::AppendIfUnique(const FileSpec &)
Implements lldb_private::ObjectFile.
Definition at line 4887 of file ObjectFileMachO.cpp.
References lldb_private::FileSpecList::AppendIfUnique(), CalculateType(), lldb_private::FileSpec::CopyByAppendingPathComponent(), lldb_private::FileSpec::CopyByRemovingLastPathComponent(), lldb_private::ObjectFile::eTypeExecutable, g_executable_path, g_loader_path, lldb_private::FileSpec::GetDirectory(), lldb_private::ModuleChild::GetModule(), lldb_private::ConstString::GetString(), lldb_private::FileSystem::Instance(), lldb_private::ObjectFile::m_data_nsp, lldb_private::ObjectFile::m_file, m_header, MachHeaderSizeFromMagic(), and lldb_private::FileSystem::Resolve().
GetEncryptedFileRanges()
ObjectFileMachO::EncryptedFileRanges ObjectFileMachO::GetEncryptedFileRanges () protected
Definition at line 1330 of file ObjectFileMachO.cpp.
References lldb_private::RangeVector< B, S, N >::Append(), lldb_private::ObjectFile::m_data_nsp, m_header, MachHeaderSizeFromMagic(), lldb_private::Range< B, S >::SetByteSize(), and lldb_private::Range< B, S >::SetRangeBase().
Referenced by CreateSections().
GetEntryPointAddress()
lldb_private::Address ObjectFileMachO::GetEntryPointAddress () override virtual
Returns the address of the Entry Point in this object file - if the object file doesn't have an entry point (because it is not an executable file) then an invalid address is returned.
Returns
Returns the entry address for this module.
Reimplemented from lldb_private::ObjectFile.
Definition at line 5006 of file ObjectFileMachO.cpp.
References lldb_private::Symtab::eDebugAny, lldb::eSymbolTypeCode, lldb_private::Symtab::eVisibilityAny, lldb_private::Symtab::FindFirstSymbolWithNameAndType(), lldb_private::SectionList::FindSectionByName(), lldb_private::Symbol::GetAddress(), lldb_private::SymbolContextList::GetContextAtIndex(), lldb_private::Address::GetFileAddress(), lldb_private::ModuleChild::GetModule(), lldb_private::ObjectFile::GetSectionList(), GetSegmentNameTEXT(), lldb_private::SymbolContextList::GetSize(), lldb_private::ObjectFile::GetSymtab(), IsDynamicLoader(), IsExecutable(), lldb_private::Address::IsValid(), LLDB_INVALID_ADDRESS, lldb_private::ObjectFile::m_data_nsp, m_entry_point_address, m_header, MachHeaderSizeFromMagic(), and lldb_private::SymbolContext::symbol.
GetIdentifierString()
std::string ObjectFileMachO::GetIdentifierString () override virtual
Some object files may have an identifier string embedded in them, e.g.
in a Mach-O core file using the LC_IDENT load command (which is obsolete, but can still be found in some old files)
Returns
Returns the identifier string if one exists, else an empty string.
Reimplemented from lldb_private::ObjectFile.
Definition at line 5239 of file ObjectFileMachO.cpp.
References lldb_private::DynamicLoader, FindLC_NOTEByName(), lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), LLDB_LOGF, lldb_private::ObjectFile::m_data_nsp, m_header, MachHeaderSizeFromMagic(), lldb_private::Process, and lldb_private::Symbols.
GetIsDynamicLinkEditor()
bool ObjectFileMachO::GetIsDynamicLinkEditor () override virtual
Return true if this file is a dynamic link editor (dyld)
Often times dyld has symbols that mirror symbols in libc and other shared libraries (like "malloc" and "free") and the user does not want to stop in these shared libraries by default. We can ask the ObjectFile if it is such a file and should be avoided for things like settings breakpoints and doing function lookups for expressions.
Reimplemented from lldb_private::ObjectFile.
Definition at line 5909 of file ObjectFileMachO.cpp.
References m_header.
GetLLDBSharedCacheUUID()
void ObjectFileMachO::GetLLDBSharedCacheUUID (lldb::addr_t & base_addir, lldb_private::UUID & uuid) protected
Intended for same-host arm device debugging where lldb will read shared cache libraries out of its own memory instead of the remote process' memory as an optimization.
If lldb's shared cache UUID does not match the process' shared cache UUID, this optimization should not be used.
Definition at line 5766 of file ObjectFileMachO.cpp.
References lldb_copy__dyld_process_cache_info::cacheBaseAddress, lldb_copy__dyld_process_cache_info::cacheUUID, lldb_private::UUID::Clear(), lldb_private::UUID::GetAsString(), lldb_private::GetLog(), lldb_private::UUID::IsValid(), LLDB_INVALID_ADDRESS, LLDB_LOGF, mach_task_self(), lldb_private::Process, and lldb_private::Symbols.
GetMachHeaderSection()
Section * ObjectFileMachO::GetMachHeaderSection ()
Definition at line 5923 of file ObjectFileMachO.cpp.
References lldb_private::SectionList::FindSectionByName(), lldb_private::Section::GetFileOffset(), lldb_private::ModuleChild::GetModule(), lldb_private::SectionList::GetSectionAtIndex(), lldb_private::ObjectFile::GetSectionList(), GetSegmentNameTEXT(), lldb_private::SectionList::GetSize(), and SectionIsLoadable().
Referenced by ParseSymtab(), and SetLoadAddress().
GetMinimumOSVersion()
llvm::VersionTuple ObjectFileMachO::GetMinimumOSVersion () override virtual
Get the minimum OS version this object file can run on.
Some object files have information that specifies the minimum OS version that they can be used on.
Returns
This function returns extracted version numbers as a llvm::VersionTuple. In case of error an empty VersionTuple is returned.
Reimplemented from lldb_private::ObjectFile.
Definition at line 5895 of file ObjectFileMachO.cpp.
References FindMinimumVersionInfo(), lldb_private::ObjectFile::m_data_nsp, m_header, m_min_os_version, and MachHeaderSizeFromMagic().
GetModuleSpecifications()
size_t ObjectFileMachO::GetModuleSpecifications (const lldb_private::FileSpec & file, lldb::DataExtractorSP & extractor_sp, lldb::offset_t data_offset, lldb::offset_t file_offset, lldb::offset_t length, lldb_private::ModuleSpecList & specs) static
Definition at line 830 of file ObjectFileMachO.cpp.
References GetAllArchSpecs(), lldb_private::ModuleSpec::GetFileSpec(), lldb_private::ModuleSpecList::GetSize(), MachHeaderSizeFromMagic(), MagicBytesMatch(), lldb_private::ObjectFile::MapFileData(), ParseHeader(), lldb_private::ModuleSpec::SetObjectOffset(), and lldb_private::ModuleSpec::SetObjectSize().
Referenced by Initialize().
GetNumThreadContexts()
uint32_t ObjectFileMachO::GetNumThreadContexts () override virtual
Reimplemented from lldb_private::ObjectFile.
Definition at line 5182 of file ObjectFileMachO.cpp.
References lldb_private::ModuleChild::GetModule(), lldb_private::ObjectFile::m_data_nsp, m_header, m_thread_context_offsets, m_thread_context_offsets_valid, MachHeaderSizeFromMagic(), lldb_private::Range< B, S >::SetByteSize(), and lldb_private::Range< B, S >::SetRangeBase().
Referenced by GetCorefileThreadExtraInfos(), and GetThreadContextAtIndex().
GetPluginDescriptionStatic()
llvm::StringRef ObjectFileMachO::GetPluginDescriptionStatic () inline static
Definition at line 46 of file ObjectFileMachO.h.
Referenced by Initialize().
GetPluginName()
llvm::StringRef ObjectFileMachO::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 170 of file ObjectFileMachO.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef ObjectFileMachO::GetPluginNameStatic () inline static
Definition at line 44 of file ObjectFileMachO.h.
Referenced by GetPluginName(), and Initialize().
GetProcessSharedCacheUUID()
void ObjectFileMachO::GetProcessSharedCacheUUID (lldb_private::Process * process, lldb::addr_t & base_addr, lldb_private::UUID & uuid) protected
Intended for same-host arm device debugging where lldb needs to detect libraries in the shared cache and augment the nlist entries with an on-disk dyld_shared_cache file.
The process will record the shared cache UUID so the on-disk cache can be matched or rejected correctly.
Definition at line 5732 of file ObjectFileMachO.cpp.
References lldb_private::UUID::Clear(), lldb_private::UUID::GetAsString(), lldb_private::Process::GetDynamicLoader(), lldb_private::GetLog(), lldb_private::DynamicLoader::GetSharedCacheInformation(), LLDB_INVALID_ADDRESS, LLDB_LOGF, lldb_private::Process, and lldb_private::Symbols.
Referenced by ParseSymtab().
GetReExportedLibraries()
lldb_private::FileSpecList ObjectFileMachO::GetReExportedLibraries () inline override virtual
Gets the file spec list of libraries re-exported by this object file.
If the object file format has the notion of one library re-exporting the symbols from another, the re-exported libraries will be returned in the FileSpecList.
Returns
Returns filespeclist.
Reimplemented from lldb_private::ObjectFile.
Definition at line 115 of file ObjectFileMachO.h.
References m_reexported_dylibs.
GetSDKVersion()
llvm::VersionTuple ObjectFileMachO::GetSDKVersion () override virtual
Get the SDK OS version this object file was built with.
Returns
This function returns extracted version numbers as a llvm::VersionTuple. In case of error an empty VersionTuple is returned.
Reimplemented from lldb_private::ObjectFile.
Definition at line 5902 of file ObjectFileMachO.cpp.
References FindMinimumVersionInfo(), lldb_private::ObjectFile::m_data_nsp, m_header, m_sdk_versions, and MachHeaderSizeFromMagic().
GetSectionNameEHFrame()
ConstString ObjectFileMachO::GetSectionNameEHFrame () static protected
Definition at line 903 of file ObjectFileMachO.cpp.
Referenced by ParseSymtab().
GetSectionNameLLDBNoNlist()
ConstString ObjectFileMachO::GetSectionNameLLDBNoNlist () static protected
Definition at line 908 of file ObjectFileMachO.cpp.
Referenced by ParseSymtab().
GetSegmentNameDATA()
ConstString ObjectFileMachO::GetSegmentNameDATA () static protected
Definition at line 868 of file ObjectFileMachO.cpp.
Referenced by ParseSymtab().
GetSegmentNameDATA_CONST()
ConstString ObjectFileMachO::GetSegmentNameDATA_CONST () static protected
Definition at line 878 of file ObjectFileMachO.cpp.
Referenced by ParseSymtab().
GetSegmentNameDATA_DIRTY()
ConstString ObjectFileMachO::GetSegmentNameDATA_DIRTY () static protected
Definition at line 873 of file ObjectFileMachO.cpp.
Referenced by ParseSymtab().
GetSegmentNameDWARF()
ConstString ObjectFileMachO::GetSegmentNameDWARF () static protected
Definition at line 893 of file ObjectFileMachO.cpp.
Referenced by SectionIsLoadable().
GetSegmentNameLINKEDIT()
ConstString ObjectFileMachO::GetSegmentNameLINKEDIT () static protected
Definition at line 888 of file ObjectFileMachO.cpp.
Referenced by ProcessSegmentCommand(), SanitizeSegmentCommand(), and SectionIsLoadable().
GetSegmentNameLLVM_COV()
ConstString ObjectFileMachO::GetSegmentNameLLVM_COV () static protected
Definition at line 898 of file ObjectFileMachO.cpp.
Referenced by SectionIsLoadable().
GetSegmentNameOBJC()
ConstString ObjectFileMachO::GetSegmentNameOBJC () static protected
Definition at line 883 of file ObjectFileMachO.cpp.
Referenced by ParseSymtab().
GetSegmentNameTEXT()
ConstString ObjectFileMachO::GetSegmentNameTEXT () static protected
Definition at line 863 of file ObjectFileMachO.cpp.
Referenced by GetBaseAddress(), GetEntryPointAddress(), GetMachHeaderSection(), ParseSymtab(), and SanitizeSegmentCommand().
GetSharedCacheUUID()
lldb_private::UUID ObjectFileMachO::GetSharedCacheUUID (lldb_private::FileSpec dyld_shared_cache, const lldb::ByteOrder byte_order, const uint32_t addr_byte_size) protected
GetThreadContextAtIndex()
lldb::RegisterContextSP ObjectFileMachO::GetThreadContextAtIndex (uint32_t idx, lldb_private::Thread & thread) override virtual
Reimplemented from lldb_private::ObjectFile.
Definition at line 5540 of file ObjectFileMachO.cpp.
References lldb_private::Range< B, S >::GetByteSize(), lldb_private::ModuleChild::GetModule(), GetNumThreadContexts(), lldb_private::Range< B, S >::GetRangeBase(), lldb_private::ObjectFile::m_data_nsp, m_header, m_thread_context_offsets, and m_thread_context_offsets_valid.
GetUUID() [1/2]
UUID ObjectFileMachO::GetUUID () override virtual
Gets the UUID for this object file.
If the object file format contains a UUID, the value should be returned. Else ObjectFile instances should return the MD5 checksum of all of the bytes for the object file (or memory for memory based object files).
Returns
The object file's UUID. In case of an error, an empty UUID is returned.
Implements lldb_private::ObjectFile.
Definition at line 4877 of file ObjectFileMachO.cpp.
References lldb_private::ModuleChild::GetModule(), GetUUID(), lldb_private::ObjectFile::m_data_nsp, m_header, and MachHeaderSizeFromMagic().
Referenced by CalculateStrata(), CalculateType(), GetAllArchSpecs(), GetUUID(), and SetLoadAddress().
GetUUID() [2/2]
UUID ObjectFileMachO::GetUUID (const llvm::MachO::mach_header & header, const lldb_private::DataExtractor & data, lldb::offset_t lc_offset) static protected
Definition at line 4598 of file ObjectFileMachO.cpp.
References lldb_private::DataExtractor::GetU32(), and lldb_private::DataExtractor::PeekData().
GetVersion()
llvm::VersionTuple ObjectFileMachO::GetVersion () override virtual
Get the object file version numbers.
Many object files have a set of version numbers that describe the version of the executable or shared library. Typically there are major, minor and build, but there may be more. This function will extract the versions from object files if they are available.
Returns
This function returns extracted version numbers as a llvm::VersionTuple. In case of error an empty VersionTuple is returned.
Reimplemented from lldb_private::ObjectFile.
Definition at line 5683 of file ObjectFileMachO.cpp.
References lldb_private::ModuleChild::GetModule(), lldb_private::ObjectFile::m_data_nsp, m_header, and MachHeaderSizeFromMagic().
Initialize()
void ObjectFileMachO::Initialize () static
Definition at line 773 of file ObjectFileMachO.cpp.
References CreateInstance(), CreateMemoryInstance(), GetModuleSpecifications(), GetPluginDescriptionStatic(), GetPluginNameStatic(), lldb_private::PluginManager::RegisterPlugin(), and SaveCore().
isA()
bool ObjectFileMachO::isA (const void * ClassID) const inline override virtual
Reimplemented from lldb_private::ObjectFile.
Definition at line 76 of file ObjectFileMachO.h.
References ID.
IsDynamicLoader()
bool ObjectFileMachO::IsDynamicLoader () const
Definition at line 1112 of file ObjectFileMachO.cpp.
References m_header.
Referenced by GetEntryPointAddress().
IsExecutable()
bool ObjectFileMachO::IsExecutable () const override virtual
Tells whether this object file is capable of being the main executable for a process.
Returns
true if it is, false otherwise.
Implements lldb_private::ObjectFile.
Definition at line 1108 of file ObjectFileMachO.cpp.
References m_header.
Referenced by GetEntryPointAddress().
IsGOTSection()
bool ObjectFileMachO::IsGOTSection (const lldb_private::Section & section) const override virtual
Returns true if the section is a global offset table section.
Reimplemented from lldb_private::ObjectFile.
Definition at line 5954 of file ObjectFileMachO.cpp.
References lldb_private::Section::GetName(), lldb_private::Section::GetObjectFile(), and lldb_private::Section::GetParent().
IsKext()
bool ObjectFileMachO::IsKext () const
Definition at line 1120 of file ObjectFileMachO.cpp.
References m_header.
IsSharedCacheBinary()
bool ObjectFileMachO::IsSharedCacheBinary () const
Definition at line 1116 of file ObjectFileMachO.cpp.
References m_header.
Referenced by ParseSymtab(), ProcessSegmentCommand(), and SanitizeSegmentCommand().
IsStripped()
bool ObjectFileMachO::IsStripped () override virtual
Detect if this object file has been stripped of local symbols.
Detect if this object file has been stripped of local symbols.
Returns
Return true if the object file has been stripped of local symbols.
Implements lldb_private::ObjectFile.
Definition at line 1299 of file ObjectFileMachO.cpp.
References lldb_private::ModuleChild::GetModule(), lldb_private::ObjectFile::m_data_nsp, m_dysymtab, m_header, and MachHeaderSizeFromMagic().
LoadCoreFileImages()
bool ObjectFileMachO::LoadCoreFileImages (lldb_private::Process & process) override virtual
Load binaries listed in a corefile.
A corefile may have metadata listing binaries that can be loaded, and the offsets at which they were loaded. This method will try to add them to the Target. If any binaries were loaded,
Parameters
[in] process Process where to load binaries.
Returns
Returns true if any binaries were loaded.
Reimplemented from lldb_private::ObjectFile.
Definition at line 6806 of file ObjectFileMachO.cpp.
References ObjectFileMachO::MachOCorefileAllImageInfos::all_image_infos, lldb_private::ModuleList::Append(), ObjectFileMachO::MachOCorefileImageEntry::currently_executing, lldb_private::DynamicLoader, error(), ObjectFileMachO::MachOCorefileImageEntry::filename, lldb_private::SectionList::FindSectionByName(), lldb_private::Process::Flush(), lldb_private::UUID::GetAsString(), GetCorefileAllImageInfos(), lldb_private::Target::GetDebugger(), lldb_private::GetLog(), lldb_private::Debugger::GetPlatformList(), lldb_private::ModuleList::GetSize(), lldb_private::Process::GetTarget(), lldb_private::UUID::IsValid(), LLDB_INVALID_ADDRESS, LLDB_LOGF, ObjectFileMachO::MachOCorefileImageEntry::load_address, lldb_private::DynamicLoader::LoadBinaryWithUUIDAndAddress(), lldb_private::PlatformList::LoadPlatformBinaryAndSetup(), lldb_private::Target::ModulesDidLoad(), lldb_private::Object, lldb_private::Log::Printf(), ObjectFileMachO::MachOCorefileImageEntry::segment_load_addresses, lldb_private::Target::SetSectionLoadAddress(), ObjectFileMachO::MachOCorefileImageEntry::slide, and ObjectFileMachO::MachOCorefileImageEntry::uuid.
MagicBytesMatch()
bool ObjectFileMachO::MagicBytesMatch (lldb::DataExtractorSP extractor_sp, lldb::addr_t offset, lldb::addr_t length) static
Definition at line 913 of file ObjectFileMachO.cpp.
References MachHeaderSizeFromMagic().
Referenced by CreateInstance(), CreateMemoryInstance(), and GetModuleSpecifications().
ParseHeader() [1/2]
bool ObjectFileMachO::ParseHeader () override virtual
Attempts to parse the object header.
This function is used as a test to see if a given plug-in instance can parse the header data already contained in ObjectFile::m_data_nsp. If an object file parser does not recognize that magic bytes in a header, false should be returned and the next plug-in can attempt to parse an object file.
Returns
Returns true if the header was parsed successfully, false otherwise.
Implements lldb_private::ObjectFile.
Definition at line 1014 of file ObjectFileMachO.cpp.
References lldb::eByteOrderBig, lldb::eByteOrderLittle, GetAllArchSpecs(), lldb_private::ModuleSpec::GetArchitecture(), lldb_private::ModuleChild::GetModule(), lldb_private::ModuleSpecList::GetModuleSpecRefAtIndex(), lldb_private::ModuleSpecList::GetSize(), lldb_private::endian::InlHostByteOrder(), lldb_private::ArchSpec::IsCompatibleMatch(), lldb_private::ArchSpec::IsValid(), lldb_private::ObjectFile::m_data_nsp, lldb_private::ObjectFile::m_file, lldb_private::ObjectFile::m_file_offset, m_header, lldb_private::ObjectFile::m_memory_addr, lldb_private::ObjectFile::m_process_wp, MachHeaderSizeFromMagic(), lldb_private::ObjectFile::MapFileData(), lldb_private::ObjectFile::ReadMemory(), and lldb_private::ObjectFile::SetModulesArchitecture().
Referenced by ProcessMachCore::CreateInstance(), and GetModuleSpecifications().
ParseHeader() [2/2]
bool ObjectFileMachO::ParseHeader (lldb::DataExtractorSP & data, lldb::offset_t * data_offset_ptr, llvm::MachO::mach_header & header) static
Definition at line 960 of file ObjectFileMachO.cpp.
References lldb::eByteOrderBig, lldb::eByteOrderLittle, and lldb_private::endian::InlHostByteOrder().
ParseSymtab() [1/2]
size_t ObjectFileMachO::ParseSymtab () protected
ParseSymtab() [2/2]
void ObjectFileMachO::ParseSymtab (lldb_private::Symtab & symtab) override virtual
Parse the symbol table into the provides symbol table object.
Symbol table parsing will be done once when this function is called by each object file plugin. All of the necessary locks will already be acquired before this function is called and the symbol table object to populate is supplied as an argument and doesn't need to be created by each plug-in.
Parameters
The symbol table to populate.
Implements lldb_private::ObjectFile.
Definition at line 2205 of file ObjectFileMachO.cpp.
References lldb_private::FileSpecList::Append(), lldb_private::ConstString::AsCString(), lldb_private::Range< B, S >::base, CalculateSectionLoadAddressForMemoryImage(), CalculateStrata(), lldb_private::Symbol::Clear(), lldb_private::FileSpec::ClearDirectory(), ObjectFileMachO::LinkeditDataCommandLargeOffsets::cmd, ObjectFileMachO::SymtabCommandLargeOffsets::cmd, ObjectFileMachO::LinkeditDataCommandLargeOffsets::dataoff, ObjectFileMachO::LinkeditDataCommandLargeOffsets::datasize, DebugSymbols, dyld_image_copy_uuid(), dyld_shared_cache_copy_uuid(), dyld_shared_cache_for_each_image(), lldb_private::DWARFCallFrameInfo::EH, lldb_private::eMemoryModuleLoadLevelComplete, lldb_private::eMemoryModuleLoadLevelMinimal, lldb_private::eMemoryModuleLoadLevelPartial, lldb_private::Mangled::ePreferMangled, lldb::eSectionTypeCode, lldb::eSectionTypeData, lldb::eSectionTypeData16, lldb::eSectionTypeData4, lldb::eSectionTypeData8, lldb::eSectionTypeDataCString, lldb::eSectionTypeDataCStringPointers, lldb::eSectionTypeDataSymbolAddress, lldb_private::ObjectFile::eStrataUser, lldb::eSymbolTypeAbsolute, lldb::eSymbolTypeAdditional, lldb::eSymbolTypeCode, lldb::eSymbolTypeCommonBlock, lldb::eSymbolTypeCompiler, lldb::eSymbolTypeData, lldb::eSymbolTypeException, lldb::eSymbolTypeHeaderFile, lldb::eSymbolTypeInstrumentation, lldb::eSymbolTypeInvalid, lldb::eSymbolTypeLineEntry, lldb::eSymbolTypeLocal, lldb::eSymbolTypeObjCClass, lldb::eSymbolTypeObjCIVar, lldb::eSymbolTypeObjCMetaClass, lldb::eSymbolTypeObjectFile, lldb::eSymbolTypeReExported, lldb::eSymbolTypeResolver, lldb::eSymbolTypeRuntime, lldb::eSymbolTypeScopeBegin, lldb::eSymbolTypeScopeEnd, lldb::eSymbolTypeSourceFile, lldb::eSymbolTypeTrampoline, lldb::eSymbolTypeUndefined, lldb::eSymbolTypeVariable, lldb::eSymbolTypeVariableType, lldb_private::ObjectFile::eTypeDebugInfo, ObjectFileMachO::DyldInfoCommandLargeOffsets::export_off, ObjectFileMachO::DyldInfoCommandLargeOffsets::export_size, lldb_private::SectionList::FindSectionByName(), lldb_private::Symtab::FindSymbolByID(), lldb_private::Symbol::GetAddressRef(), GetArchitecture(), lldb_private::Symbol::GetByteSize(), lldb_private::ConstString::GetCString(), lldb_private::Mangled::GetDemangledName(), lldb_private::RangeVector< B, S, N >::GetEntryAtIndex(), lldb_private::Address::GetFileAddress(), lldb_private::FileSpec::GetFilename(), lldb_private::FileSpecList::GetFileSpecAtIndex(), lldb_private::DWARFCallFrameInfo::GetFunctionAddressAndSizeVector(), lldb_private::GetLog(), GetMachHeaderSection(), lldb_private::Symbol::GetMangled(), lldb_private::TargetProperties::GetMemoryModuleLoadLevel(), lldb_private::ModuleChild::GetModule(), GetName(), lldb_private::Mangled::GetName(), lldb_private::Symtab::GetNumSymbols(), GetProcessSharedCacheUUID(), lldb_private::Address::GetSection(), MachSymtabSectionInfo::GetSection(), lldb_private::ObjectFile::GetSectionList(), GetSectionNameEHFrame(), GetSectionNameLLDBNoNlist(), GetSegmentNameDATA(), GetSegmentNameDATA_CONST(), GetSegmentNameDATA_DIRTY(), GetSegmentNameOBJC(), GetSegmentNameTEXT(), lldb_private::FileSpecList::GetSize(), lldb_private::RangeVector< B, S, N >::GetSize(), GetSymbolType(), lldb_private::ObjectFile::GetSymbolTypeFromName(), lldb_private::Symbol::GetType(), ObjectFileMachO::DysymtabCommandLargeOffsets::indirectsymoff, lldb_private::FileSystem::Instance(), lldb_private::ArchSpec::IsAlwaysThumbInstructions(), lldb_private::ObjectFile::IsInMemory(), IsSharedCacheBinary(), lldb_private::UUID::IsValid(), KERN_SUCCESS, LLDB_INVALID_ADDRESS, LLDB_LOG, LLDB_SCOPED_TIMERF, lldbassert, m_allow_assembly_emulation_unwind_plans, lldb_private::ObjectFile::m_data_nsp, m_dysymtab, lldb_private::ObjectFile::m_file, m_header, m_linkedit_original_offset, m_mach_sections, lldb_private::ObjectFile::m_memory_addr, m_reexported_dylibs, lldb_private::ObjectFile::m_type, mach_task_self(), MachHeaderSizeFromMagic(), MACHO_NLIST_ARM_SYMBOL_IS_THUMB, ObjectFileMachO::DysymtabCommandLargeOffsets::nindirectsyms, NonDebugSymbols, ObjectFileMachO::SymtabCommandLargeOffsets::nsyms, ParseNList(), ParseTrieEntries(), lldb_private::ObjectFile::ReadMemory(), lldb_private::Debugger::ReportError(), lldb_private::Symtab::Resize(), lldb_private::Symbol::SetByteSize(), lldb_private::Symbol::SetDebug(), lldb_private::Mangled::SetDemangledName(), lldb_private::Symbol::SetDemangledNameIsSynthesized(), lldb_private::Symbol::SetExternal(), lldb_private::FileSpec::SetFile(), lldb_private::Symbol::SetFlags(), lldb_private::Symbol::SetID(), lldb_private::Symbol::SetIsSynthetic(), lldb_private::Symbol::SetIsWeak(), lldb_private::Mangled::SetMangledName(), lldb_private::Address::SetOffset(), lldb_private::Symbol::SetReExportedSymbolName(), lldb_private::Symbol::SetReExportedSymbolSharedLibrary(), lldb_private::Address::SetSection(), lldb_private::Symbol::SetSizeIsSibling(), lldb_private::Symbol::SetType(), lldb_private::Mangled::SetValue(), ObjectFileMachO::SymtabCommandLargeOffsets::stroff, lldb_private::Symtab::SymbolAtIndex(), lldb_private::Symbols, ObjectFileMachO::SymtabCommandLargeOffsets::symoff, THUMB_ADDRESS_BIT_MASK, TRIE_SYMBOL_IS_THUMB, TryParseV2ObjCMetadataSymbol(), UINT32_MAX, UINT64_MAX, lldb_private::Unwind, and lldb_private::Log::Warning().
ProcessDysymtabCommand()
void ObjectFileMachO::ProcessDysymtabCommand (const llvm::MachO::load_command & load_cmd, lldb::offset_t offset) protected
Definition at line 1862 of file ObjectFileMachO.cpp.
References lldb_private::ObjectFile::m_data_nsp, and m_dysymtab.
Referenced by CreateSections().
ProcessSegmentCommand()
void ObjectFileMachO::ProcessSegmentCommand (const llvm::MachO::load_command & load_cmd, lldb::offset_t offset, uint32_t cmd_idx, SegmentParsingContext & context) protected
Definition at line 1567 of file ObjectFileMachO.cpp.
References lldb_private::SectionList::AddSection(), lldb_private::ConstString::AsCString(), lldb_private::ConstString::Clear(), ObjectFileMachO::SegmentParsingContext::EncryptedRanges, lldb::eSectionTypeContainer, lldb_private::ObjectFile::eTypeCoreFile, ObjectFileMachO::SegmentParsingContext::FileAddressesChanged, lldb_private::RangeVector< B, S, N >::FindEntryThatContains(), lldb_private::SectionList::FindSectionByName(), lldb_private::GetLog(), lldb_private::ModuleChild::GetModule(), GetSectionType(), GetSegmentNameLINKEDIT(), GetSegmentPermissions(), lldb_private::ObjectFile::GetType(), lldb_private::ObjectFile::IsInMemory(), IsSharedCacheBinary(), lldb_private::ObjectFile::m_data_nsp, m_header, m_mach_sections, lldb_private::ObjectFile::m_sections_up, m_text_address, ObjectFileMachO::SegmentParsingContext::NextSectionIdx, ObjectFileMachO::SegmentParsingContext::NextSegmentIdx, lldb_private::Log::Printf(), SanitizeSegmentCommand(), lldb_private::ConstString::SetTrimmedCStringWithLength(), lldb_private::Symbols, UINT32_MAX, and ObjectFileMachO::SegmentParsingContext::UnifiedList.
Referenced by CreateSections().
SanitizeSegmentCommand()
void ObjectFileMachO::SanitizeSegmentCommand (llvm::MachO::segment_command_64 & seg_cmd, uint32_t cmd_idx) protected
Definition at line 1359 of file ObjectFileMachO.cpp.
References lldb_private::ModuleChild::GetModule(), GetSegmentNameLINKEDIT(), GetSegmentNameTEXT(), lldb_private::ObjectFile::IsInMemory(), IsSharedCacheBinary(), lldb_private::ObjectFile::m_length, m_linkedit_original_offset, and m_text_address.
Referenced by ProcessSegmentCommand().
SaveCore()
bool ObjectFileMachO::SaveCore (const lldb::ProcessSP & process_sp, lldb_private::SaveCoreOptions & options, lldb_private::Status & error) static
Definition at line 6331 of file ObjectFileMachO.cpp.
References lldb_private::bits(), RegisterContextDarwin_arm64_Mach::Create_LC_THREAD(), RegisterContextDarwin_arm_Mach::Create_LC_THREAD(), RegisterContextDarwin_riscv32_Mach::Create_LC_THREAD(), RegisterContextDarwin_x86_64_Mach::Create_LC_THREAD(), CreateAllImageInfosPayload(), lldb_private::Stream::eBinary, lldb_private::File::eOpenOptionCanCreate, lldb_private::File::eOpenOptionTruncate, lldb_private::File::eOpenOptionWriteOnly, error(), lldb::eSaveCoreDirtyOnly, lldb::eSaveCoreUnspecified, lldb_private::Status::FromError(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::ArchSpec::GetAddressByteSize(), lldb_private::Target::GetArchitecture(), lldb_private::Debugger::GetAsyncOutputStream(), lldb_private::ArchSpec::GetByteOrder(), lldb_private::StreamString::GetData(), lldb_private::Target::GetDebugger(), lldb_private::ArchSpec::GetMachine(), lldb_private::ArchSpec::GetMachOCPUSubType(), lldb_private::ArchSpec::GetMachOCPUType(), lldb_private::SaveCoreOptions::GetOutputFile(), lldb_private::FileSpec::GetPath(), lldb_private::StreamString::GetSize(), lldb_private::ThreadList::GetSize(), lldb_private::StreamString::GetString(), lldb_private::SaveCoreOptions::GetStyle(), lldb_private::ThreadList::GetThreadAtIndex(), lldb_private::ArchSpec::GetTriple(), lldb_private::FileSystem::Instance(), LLDB_INVALID_ADDRESS_MASK, memory_read_error, lldb_private::FileSystem::Open(), lldb_private::Stream::PutHex32(), lldb_private::Stream::PutHex64(), lldb_private::Stream::PutRawBytes(), lldb_private::SaveCoreOptions::SetStyle(), segment::vmaddr, segment::vmsize, and lldb_private::Stream::Write().
Referenced by Initialize().
SectionIsLoadable()
bool ObjectFileMachO::SectionIsLoadable (const lldb_private::Section * section) protected
Definition at line 5968 of file ObjectFileMachO.cpp.
References lldb_private::ObjectFile::eStrataKernel, lldb_private::ObjectFile::eStrataRawImage, lldb_private::ModuleChild::GetModule(), lldb_private::Section::GetName(), GetSegmentNameDWARF(), GetSegmentNameLINKEDIT(), GetSegmentNameLLVM_COV(), lldb_private::ObjectFile::GetStrata(), lldb_private::Section::IsThreadSpecific(), and lldb_private::ObjectFile::m_process_wp.
Referenced by CalculateSectionLoadAddressForMemoryImage(), GetMachHeaderSection(), and SetLoadAddress().
SetLoadAddress()
bool ObjectFileMachO::SetLoadAddress (lldb_private::Target & target, lldb::addr_t value, bool value_is_offset) override virtual
Sets the load address for an entire module, assuming a rigid slide of sections, if possible in the implementation.
Returns
Returns true iff any section's load address changed.
Reimplemented from lldb_private::ObjectFile.
Definition at line 6008 of file ObjectFileMachO.cpp.
References CalculateSectionLoadAddressForMemoryImage(), lldb_private::DynamicLoader, lldb_private::UUID::GetAsString(), lldb_private::StreamString::GetData(), lldb_private::ObjectFile::GetFileSpec(), lldb_private::GetLog(), GetMachHeaderSection(), lldb_private::ModuleChild::GetModule(), lldb_private::FileSpec::GetPath(), lldb_private::SectionList::GetSectionAtIndex(), lldb_private::ObjectFile::GetSectionList(), lldb_private::SectionList::GetSize(), GetUUID(), LLDB_INVALID_ADDRESS, LLDB_LOGF, SectionIsLoadable(), and lldb_private::Target::SetSectionLoadAddress().
Terminate()
void ObjectFileMachO::Terminate () static
Definition at line 779 of file ObjectFileMachO.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Member Data Documentation
ID
char ObjectFileMachO::ID static
Definition at line 75 of file ObjectFileMachO.h.
Referenced by classof(), and isA().
m_allow_assembly_emulation_unwind_plans
bool ObjectFileMachO::m_allow_assembly_emulation_unwind_plans protected
Definition at line 446 of file ObjectFileMachO.h.
Referenced by AllowAssemblyEmulationUnwindPlans(), ObjectFileMachO(), ObjectFileMachO(), and ParseSymtab().
m_dysymtab
llvm::MachO::dysymtab_command ObjectFileMachO::m_dysymtab protected
Definition at line 435 of file ObjectFileMachO.h.
Referenced by IsStripped(), ObjectFileMachO(), ObjectFileMachO(), ParseSymtab(), and ProcessDysymtabCommand().
m_entry_point_address
lldb_private::Address ObjectFileMachO::m_entry_point_address protected
Definition at line 440 of file ObjectFileMachO.h.
Referenced by GetEntryPointAddress(), ObjectFileMachO(), and ObjectFileMachO().
m_header
llvm::MachO::mach_header ObjectFileMachO::m_header protected
Definition at line 423 of file ObjectFileMachO.h.
Referenced by CalculateStrata(), CalculateType(), CanTrustAddressRanges(), CreateSections(), Dump(), FindLC_NOTEByName(), GetAddressClass(), GetArchitecture(), GetDependentModules(), GetEncryptedFileRanges(), GetEntryPointAddress(), GetIdentifierString(), GetIsDynamicLinkEditor(), GetMinimumOSVersion(), GetNumThreadContexts(), GetSDKVersion(), GetThreadContextAtIndex(), GetUUID(), GetVersion(), IsDynamicLoader(), IsExecutable(), IsKext(), IsSharedCacheBinary(), IsStripped(), ObjectFileMachO(), ObjectFileMachO(), ParseHeader(), ParseSymtab(), and ProcessSegmentCommand().
m_linkedit_original_offset
lldb::offset_t ObjectFileMachO::m_linkedit_original_offset = 0 protected
Definition at line 442 of file ObjectFileMachO.h.
Referenced by ParseSymtab(), and SanitizeSegmentCommand().
m_mach_sections
std::vector<llvm::MachO::section_64> ObjectFileMachO::m_mach_sections protected
Definition at line 436 of file ObjectFileMachO.h.
Referenced by ObjectFileMachO(), ObjectFileMachO(), ParseSymtab(), and ProcessSegmentCommand().
m_min_os_version
std::optional<llvm::VersionTuple> ObjectFileMachO::m_min_os_version protected
Definition at line 437 of file ObjectFileMachO.h.
Referenced by GetMinimumOSVersion().
m_reexported_dylibs
lldb_private::FileSpecList ObjectFileMachO::m_reexported_dylibs protected
Definition at line 445 of file ObjectFileMachO.h.
Referenced by GetReExportedLibraries(), ObjectFileMachO(), ObjectFileMachO(), and ParseSymtab().
m_sdk_versions
std::optional<llvm::VersionTuple> ObjectFileMachO::m_sdk_versions protected
Definition at line 438 of file ObjectFileMachO.h.
Referenced by GetSDKVersion().
m_text_address
lldb::addr_t ObjectFileMachO::m_text_address = LLDB_INVALID_ADDRESS protected
Definition at line 443 of file ObjectFileMachO.h.
Referenced by ProcessSegmentCommand(), and SanitizeSegmentCommand().
m_thread_context_offsets
FileRangeArray ObjectFileMachO::m_thread_context_offsets protected
Definition at line 441 of file ObjectFileMachO.h.
Referenced by GetNumThreadContexts(), GetThreadContextAtIndex(), ObjectFileMachO(), and ObjectFileMachO().
m_thread_context_offsets_valid
bool ObjectFileMachO::m_thread_context_offsets_valid protected
Definition at line 444 of file ObjectFileMachO.h.
Referenced by GetNumThreadContexts(), GetThreadContextAtIndex(), ObjectFileMachO(), and ObjectFileMachO().
The documentation for this class was generated from the following files:
ObjectFileMachO.h
ObjectFileMachO.cpp