LLDB: lldb_private::ThreadPlanCallFunction Class Reference
lldb_private::ThreadPlanCallFunction Class Reference
#include <ThreadPlanCallFunction.h>
Public Member Functions
ThreadPlanCallFunction (Thread &thread, const Address &function, const CompilerType &return_type, llvm::ArrayRef< lldb::addr_t > args, const EvaluateExpressionOptions &options)
ThreadPlanCallFunction (Thread &thread, const Address &function, const EvaluateExpressionOptions &options)
~ThreadPlanCallFunction () override
void GetDescription (Stream *s, lldb::DescriptionLevel level) override
Print a description of this thread to the stream s.
bool ValidatePlan (Stream *error) override
Returns whether this plan could be successfully created.
bool ShouldStop (Event *event_ptr) override
Vote ShouldReportStop (Event *event_ptr) override
bool StopOthers () override
lldb::StateType GetPlanRunState () override
void DidPush () override
bool WillStop () override
bool MischiefManaged () override
lldb::ValueObjectSP GetReturnValueObject () override
lldb::addr_t GetFunctionStackPointer ()
void DidPop () override
virtual lldb::StopInfoSP GetRealStopInfo ()
lldb::addr_t GetStopAddress ()
void RestoreThreadState () override
void ThreadDestroyed () override
void SetStopOthers (bool new_value) override
Public Member Functions inherited from lldb_private::ThreadPlan
virtual ~ThreadPlan ()
const char * GetName () const
Returns the name of this thread plan.
Thread & GetThread ()
Returns the Thread that is using this thread plan.
Target & GetTarget ()
const Target & GetTarget () const
void ClearThreadCache ()
Clear the Thread* cache.
bool TracerExplainsStop ()
lldb::StateType RunState ()
bool PlanExplainsStop (Event *event_ptr)
virtual bool ShouldAutoContinue (Event *event_ptr)
Returns whether this thread plan overrides the ShouldStop of subsequently processed plans.
Vote ShouldReportRun (Event *event_ptr)
virtual bool SupportsResumeOthers ()
virtual bool ShouldRunBeforePublicStop ()
bool WillResume (lldb::StateType resume_state, bool current_plan)
bool IsControllingPlan ()
virtual bool IsLeafPlan ()
bool SetIsControllingPlan (bool value)
virtual bool OkayToDiscard ()
void SetOkayToDiscard (bool value)
bool GetPrivate ()
void SetPrivate (bool input)
ThreadPlanKind GetKind () const
bool IsPlanComplete ()
void SetPlanComplete (bool success=true)
virtual bool IsPlanStale ()
bool PlanSucceeded ()
virtual bool IsBasePlan ()
lldb::ThreadPlanTracerSP & GetThreadPlanTracer ()
void SetThreadPlanTracer (lldb::ThreadPlanTracerSP new_tracer_sp)
void DoTraceLog ()
virtual lldb::ExpressionVariableSP GetExpressionVariable ()
virtual bool IsVirtualStep ()
bool SetIterationCount (size_t count)
virtual lldb::RunDirection GetDirection () const
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Protected Member Functions
void ReportRegisterState (const char *message)
bool DoPlanExplainsStop (Event *event_ptr) override
virtual void SetReturnValue ()
bool ConstructorSetup (Thread &thread, ABI *&abi, lldb::addr_t &start_load_addr, lldb::addr_t &function_load_addr)
virtual void DoTakedown (bool success)
void SetBreakpoints ()
void ClearBreakpoints ()
bool BreakpointsExplainStop ()
Protected Member Functions inherited from lldb_private::ThreadPlan
ThreadPlan (ThreadPlanKind kind, const char *name, Thread &thread, Vote report_stop_vote, Vote report_run_vote)
virtual bool DoWillResume (lldb::StateType resume_state, bool current_plan)
void PushPlan (lldb::ThreadPlanSP &thread_plan_sp)
ThreadPlan * GetPreviousPlan ()
lldb::StopInfoSP GetPrivateStopInfo ()
void SetStopInfo (lldb::StopInfoSP stop_reason_sp)
bool IsUsuallyUnexplainedStopReason (lldb::StopReason)
Protected Attributes
bool m_valid
bool m_stop_other_threads
bool m_unwind_on_error
bool m_ignore_breakpoints
bool m_debug_execution
bool m_trap_exceptions
Address m_function_addr
Address m_start_addr
lldb::addr_t m_function_sp
lldb::ThreadPlanSP m_subplan_sp
LanguageRuntime * m_cxx_language_runtime
LanguageRuntime * m_objc_language_runtime
Thread::ThreadStateCheckpoint m_stored_thread_state
lldb::StopInfoSP m_real_stop_info_sp
StreamString m_constructor_errors
lldb::ValueObjectSP m_return_valobj_sp
bool m_takedown_done
bool m_should_clear_objc_exception_bp
bool m_should_clear_cxx_exception_bp
lldb::addr_t m_stop_address
Protected Attributes inherited from lldb_private::ThreadPlan
Status m_status
Process & m_process
lldb::tid_t m_tid
Vote m_report_stop_vote
Vote m_report_run_vote
bool m_takes_iteration_count
bool m_could_not_resolve_hw_bp
int32_t m_iteration_count = 1
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Private Member Functions
ThreadPlanCallFunction (const ThreadPlanCallFunction &)=delete
const ThreadPlanCallFunction & operator= (const ThreadPlanCallFunction &)=delete
Private Attributes
CompilerType m_return_type
Additional Inherited Members
Public Types inherited from lldb_private::ThreadPlan
enum ThreadPlanKind {
eKindGeneric , eKindNull , eKindBase , eKindCallFunction ,
eKindPython , eKindStepInstruction , eKindStepOut , eKindStepOverBreakpoint ,
eKindStepOverRange , eKindStepInRange , eKindRunToAddress , eKindStepThrough ,
eKindStepUntil , eKindSingleThreadTimeout
}
Detailed Description
Definition at line 20 of file ThreadPlanCallFunction.h.
Constructor & Destructor Documentation
ThreadPlanCallFunction() [1/3]
lldb_private::ThreadPlanCallFunction::ThreadPlanCallFunction (Thread & thread, const Address & function, const CompilerType & return_type, llvm::ArrayRef< lldb::addr_t > args, const EvaluateExpressionOptions & options)
References error().
Referenced by operator=(), ThreadPlanCallFunction(), lldb_private::ThreadPlanCallFunctionUsingABI::ThreadPlanCallFunctionUsingABI(), and lldb_private::ThreadPlanCallUserExpression::ThreadPlanCallUserExpression().
ThreadPlanCallFunction() [2/3]
ThreadPlanCallFunction::ThreadPlanCallFunction (Thread & thread, const Address & function, const EvaluateExpressionOptions & options)
Definition at line 130 of file ThreadPlanCallFunction.cpp.
References lldb_private::ThreadPlan::eKindCallFunction, lldb_private::eVoteNoOpinion, LLDB_INVALID_ADDRESS, m_constructor_errors, m_cxx_language_runtime, m_debug_execution, m_function_addr, m_function_sp, m_ignore_breakpoints, m_objc_language_runtime, m_real_stop_info_sp, m_return_type, m_return_valobj_sp, m_should_clear_cxx_exception_bp, m_should_clear_objc_exception_bp, m_start_addr, m_stop_address, m_stop_other_threads, m_stored_thread_state, m_subplan_sp, m_takedown_done, m_trap_exceptions, m_unwind_on_error, m_valid, and lldb_private::ThreadPlan::ThreadPlan().
~ThreadPlanCallFunction()
ThreadPlanCallFunction::~ThreadPlanCallFunction () override
Definition at line 148 of file ThreadPlanCallFunction.cpp.
References DoTakedown(), and lldb_private::ThreadPlan::PlanSucceeded().
ThreadPlanCallFunction() [3/3]
lldb_private::ThreadPlanCallFunction::ThreadPlanCallFunction (const ThreadPlanCallFunction &) private delete
References ThreadPlanCallFunction().
Member Function Documentation
BreakpointsExplainStop()
bool ThreadPlanCallFunction::BreakpointsExplainStop () protected
Definition at line 443 of file ThreadPlanCallFunction.cpp.
References lldb_private::GetLog(), lldb_private::ThreadPlan::GetPrivateStopInfo(), LLDB_LOGF, m_cxx_language_runtime, m_objc_language_runtime, m_trap_exceptions, lldb_private::ThreadPlan::SetPlanComplete(), and lldb_private::Step.
Referenced by DoPlanExplainsStop().
ClearBreakpoints()
void ThreadPlanCallFunction::ClearBreakpoints () protected
Definition at line 434 of file ThreadPlanCallFunction.cpp.
References m_cxx_language_runtime, m_objc_language_runtime, m_should_clear_cxx_exception_bp, m_should_clear_objc_exception_bp, and m_trap_exceptions.
Referenced by DoTakedown().
ConstructorSetup()
bool ThreadPlanCallFunction::ConstructorSetup (Thread & thread, ABI *& abi, lldb::addr_t & start_load_addr, lldb::addr_t & function_load_addr) protected
Definition at line 34 of file ThreadPlanCallFunction.cpp.
References error(), lldb_private::Target::GetEntryPointAddress(), lldb_private::GetLog(), lldb_private::ABI::GetRedZoneSize(), lldb_private::ThreadPlan::GetTarget(), lldb_private::Log::GetVerbose(), LLDB_LOGF, m_constructor_errors, m_function_addr, m_function_sp, m_start_addr, m_stored_thread_state, ReportRegisterState(), SetBreakpoints(), lldb_private::ThreadPlan::SetIsControllingPlan(), lldb_private::ThreadPlan::SetOkayToDiscard(), lldb_private::ThreadPlan::SetPrivate(), and lldb_private::Step.
Referenced by lldb_private::ThreadPlanCallFunctionUsingABI::ThreadPlanCallFunctionUsingABI().
DidPop()
void ThreadPlanCallFunction::DidPop () override virtual
Reimplemented from lldb_private::ThreadPlan.
Reimplemented in lldb_private::ThreadPlanCallUserExpression.
Definition at line 230 of file ThreadPlanCallFunction.cpp.
References DoTakedown(), and lldb_private::ThreadPlan::PlanSucceeded().
Referenced by lldb_private::ThreadPlanCallUserExpression::DidPop().
DidPush()
void ThreadPlanCallFunction::DidPush () override virtual
Reimplemented from lldb_private::ThreadPlan.
Reimplemented in lldb_private::ThreadPlanCallUserExpression.
Definition at line 380 of file ThreadPlanCallFunction.cpp.
References lldb_private::ThreadPlan::GetThread(), m_start_addr, m_stop_other_threads, m_subplan_sp, and lldb_private::Thread::SetStopInfoToNothing().
Referenced by lldb_private::ThreadPlanCallUserExpression::DidPush().
DoPlanExplainsStop()
bool ThreadPlanCallFunction::DoPlanExplainsStop (Event * event_ptr) override protected virtual
Implements lldb_private::ThreadPlan.
Definition at line 262 of file ThreadPlanCallFunction.cpp.
References BreakpointsExplainStop(), lldb::eStopReasonBreakpoint, lldb::eStopReasonNone, lldb_private::Stoppoint::GetID(), lldb_private::Process::ProcessEventData::GetInterruptedFromEvent(), lldb_private::GetLog(), lldb_private::ThreadPlan::GetPrivateStopInfo(), lldb_private::Breakpoint::IsInternal(), LLDB_LOG, LLDB_LOGF, m_ignore_breakpoints, lldb_private::ThreadPlan::m_process, m_real_stop_info_sp, m_subplan_sp, m_unwind_on_error, lldb_private::Process, lldb_private::ThreadPlan::SetPlanComplete(), lldb_private::Step, and lldb_private::Thread::StopReasonAsString().
Referenced by ShouldStop().
DoTakedown()
void ThreadPlanCallFunction::DoTakedown (bool success) protected virtual
Reimplemented in lldb_private::ThreadPlanCallUserExpression.
Definition at line 175 of file ThreadPlanCallFunction.cpp.
References ClearBreakpoints(), lldb_private::GetLog(), lldb_private::ThreadPlan::GetPrivateStopInfo(), lldb_private::ThreadPlan::GetThread(), lldb_private::Log::GetVerbose(), lldb_private::ThreadPlan::IsPlanComplete(), LLDB_LOGF, m_real_stop_info_sp, m_stop_address, m_stored_thread_state, m_takedown_done, lldb_private::ThreadPlan::m_tid, m_valid, ReportRegisterState(), lldb_private::ThreadPlan::SetPlanComplete(), SetReturnValue(), and lldb_private::Step.
Referenced by DidPop(), lldb_private::ThreadPlanCallUserExpression::DoTakedown(), and ~ThreadPlanCallFunction().
GetDescription()
void ThreadPlanCallFunction::GetDescription (Stream * s, lldb::DescriptionLevel level) override virtual
Print a description of this thread to the stream s.
thread. Don't expect that the result of GetThread is valid in the description method. This might get called when the underlying Thread has not been reported, so we only know the TID and not the thread.
Parameters
[in] s The stream to which to print the description.
[in] level The level of description desired. Note that eDescriptionLevelBrief will be used in the stop message printed when the plan is complete.
Implements lldb_private::ThreadPlan.
Reimplemented in lldb_private::ThreadPlanCallFunctionUsingABI, and lldb_private::ThreadPlanCallUserExpression.
Definition at line 232 of file ThreadPlanCallFunction.cpp.
References lldb::eDescriptionLevelBrief, lldb_private::ThreadPlan::GetTarget(), m_function_addr, and lldb_private::Stream::Printf().
Referenced by lldb_private::ThreadPlanCallUserExpression::GetDescription().
GetFunctionStackPointer()
lldb::addr_t lldb_private::ThreadPlanCallFunction::GetFunctionStackPointer () inline
Definition at line 69 of file ThreadPlanCallFunction.h.
References m_function_sp.
Referenced by lldb_private::LLVMUserExpression::DoExecute(), and lldb_private::ThreadPlanCallUserExpression::MischiefManaged().
GetPlanRunState()
StateType ThreadPlanCallFunction::GetPlanRunState () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 378 of file ThreadPlanCallFunction.cpp.
References lldb::eStateRunning.
GetRealStopInfo()
virtual lldb::StopInfoSP lldb_private::ThreadPlanCallFunction::GetRealStopInfo () inline virtual
Reimplemented in lldb_private::ThreadPlanCallUserExpression.
Definition at line 84 of file ThreadPlanCallFunction.h.
References lldb_private::ThreadPlan::GetPrivateStopInfo(), and m_real_stop_info_sp.
Referenced by lldb_private::ThreadPlanCallUserExpression::GetRealStopInfo().
GetReturnValueObject()
lldb::ValueObjectSP lldb_private::ThreadPlanCallFunction::GetReturnValueObject () inline override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 62 of file ThreadPlanCallFunction.h.
References m_return_valobj_sp.
GetStopAddress()
lldb::addr_t lldb_private::ThreadPlanCallFunction::GetStopAddress () inline
Definition at line 91 of file ThreadPlanCallFunction.h.
References m_stop_address.
Referenced by lldb_private::ThreadPlanCallUserExpression::GetRealStopInfo().
MischiefManaged()
bool ThreadPlanCallFunction::MischiefManaged () override virtual
Reimplemented from lldb_private::ThreadPlan.
Reimplemented in lldb_private::ThreadPlanCallUserExpression.
Definition at line 401 of file ThreadPlanCallFunction.cpp.
References lldb_private::GetLog(), lldb_private::ThreadPlan::IsPlanComplete(), LLDB_LOGF, lldb_private::ThreadPlan::MischiefManaged(), and lldb_private::Step.
operator=()
const ThreadPlanCallFunction & lldb_private::ThreadPlanCallFunction::operator= (const ThreadPlanCallFunction &) private delete
References ThreadPlanCallFunction().
ReportRegisterState()
void ThreadPlanCallFunction::ReportRegisterState (const char * message) protected
Definition at line 152 of file ThreadPlanCallFunction.cpp.
References lldb_private::DumpRegisterValue(), lldb::eFormatDefault, lldb_private::Stream::EOL(), lldb_private::GetLog(), lldb_private::Thread::GetRegisterContext(), lldb_private::RegisterContext::GetRegisterCount(), lldb_private::RegisterContext::GetRegisterInfoAtIndex(), lldb_private::StreamString::GetString(), lldb_private::ThreadPlan::GetThread(), lldb_private::Log::GetVerbose(), lldb_private::Log::PutCString(), lldb_private::Log::PutString(), lldb_private::RegisterContext::ReadRegister(), and lldb_private::Step.
Referenced by ConstructorSetup(), DoTakedown(), ShouldStop(), and lldb_private::ThreadPlanCallFunctionUsingABI::ThreadPlanCallFunctionUsingABI().
RestoreThreadState()
void ThreadPlanCallFunction::RestoreThreadState () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 474 of file ThreadPlanCallFunction.cpp.
References lldb_private::ThreadPlan::GetThread(), m_stored_thread_state, and lldb_private::Thread::RestoreThreadStateFromCheckpoint().
SetBreakpoints()
void ThreadPlanCallFunction::SetBreakpoints () protected
Definition at line 415 of file ThreadPlanCallFunction.cpp.
References lldb::eLanguageTypeC_plus_plus, lldb::eLanguageTypeObjC, m_cxx_language_runtime, m_objc_language_runtime, lldb_private::ThreadPlan::m_process, m_should_clear_cxx_exception_bp, m_should_clear_objc_exception_bp, and m_trap_exceptions.
Referenced by ConstructorSetup().
SetReturnValue()
void ThreadPlanCallFunction::SetReturnValue () protected virtual
Reimplemented in lldb_private::ThreadPlanCallFunctionUsingABI.
Definition at line 478 of file ThreadPlanCallFunction.cpp.
References lldb_private::ABI::GetReturnValueObject(), lldb_private::ThreadPlan::GetThread(), lldb_private::ThreadPlan::m_process, m_return_type, and m_return_valobj_sp.
Referenced by DoTakedown().
SetStopOthers()
void ThreadPlanCallFunction::SetStopOthers (bool new_value) override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 470 of file ThreadPlanCallFunction.cpp.
References m_subplan_sp.
ShouldReportStop()
Vote ThreadPlanCallFunction::ShouldReportStop (Event * event_ptr) override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 255 of file ThreadPlanCallFunction.cpp.
References lldb_private::eVoteYes, lldb_private::ThreadPlan::IsPlanComplete(), m_takedown_done, and lldb_private::ThreadPlan::ShouldReportStop().
ShouldStop()
bool ThreadPlanCallFunction::ShouldStop (Event * event_ptr) override virtual
Implements lldb_private::ThreadPlan.
Definition at line 362 of file ThreadPlanCallFunction.cpp.
References DoPlanExplainsStop(), lldb_private::ThreadPlan::IsPlanComplete(), and ReportRegisterState().
StopOthers()
bool ThreadPlanCallFunction::StopOthers () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 376 of file ThreadPlanCallFunction.cpp.
References m_stop_other_threads.
ThreadDestroyed()
void lldb_private::ThreadPlanCallFunction::ThreadDestroyed () inline override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 95 of file ThreadPlanCallFunction.h.
References m_takedown_done.
ValidatePlan()
bool ThreadPlanCallFunction::ValidatePlan (Stream * error) override virtual
Returns whether this plan could be successfully created.
Parameters
[in] error A stream to which to print some reason why the plan could not be created. Can be NULL.
Returns
true if the plan should be queued, false otherwise.
Implements lldb_private::ThreadPlan.
Definition at line 241 of file ThreadPlanCallFunction.cpp.
References error(), m_constructor_errors, and m_valid.
WillStop()
bool ThreadPlanCallFunction::WillStop () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 399 of file ThreadPlanCallFunction.cpp.
Member Data Documentation
m_constructor_errors
StreamString lldb_private::ThreadPlanCallFunction::m_constructor_errors protected
Definition at line 136 of file ThreadPlanCallFunction.h.
Referenced by ConstructorSetup(), ThreadPlanCallFunction(), and ValidatePlan().
m_cxx_language_runtime
LanguageRuntime* lldb_private::ThreadPlanCallFunction::m_cxx_language_runtime protected
Definition at line 128 of file ThreadPlanCallFunction.h.
Referenced by BreakpointsExplainStop(), ClearBreakpoints(), SetBreakpoints(), and ThreadPlanCallFunction().
m_debug_execution
bool lldb_private::ThreadPlanCallFunction::m_debug_execution protected
Definition at line 122 of file ThreadPlanCallFunction.h.
Referenced by ThreadPlanCallFunction().
m_function_addr
Address lldb_private::ThreadPlanCallFunction::m_function_addr protected
Definition at line 124 of file ThreadPlanCallFunction.h.
Referenced by ConstructorSetup(), GetDescription(), lldb_private::ThreadPlanCallFunctionUsingABI::GetDescription(), and ThreadPlanCallFunction().
m_function_sp
lldb::addr_t lldb_private::ThreadPlanCallFunction::m_function_sp protected
Definition at line 126 of file ThreadPlanCallFunction.h.
Referenced by ConstructorSetup(), GetFunctionStackPointer(), ThreadPlanCallFunction(), and lldb_private::ThreadPlanCallFunctionUsingABI::ThreadPlanCallFunctionUsingABI().
m_ignore_breakpoints
bool lldb_private::ThreadPlanCallFunction::m_ignore_breakpoints protected
Definition at line 121 of file ThreadPlanCallFunction.h.
Referenced by DoPlanExplainsStop(), and ThreadPlanCallFunction().
m_objc_language_runtime
LanguageRuntime* lldb_private::ThreadPlanCallFunction::m_objc_language_runtime protected
Definition at line 129 of file ThreadPlanCallFunction.h.
Referenced by BreakpointsExplainStop(), ClearBreakpoints(), SetBreakpoints(), and ThreadPlanCallFunction().
m_real_stop_info_sp
lldb::StopInfoSP lldb_private::ThreadPlanCallFunction::m_real_stop_info_sp protected
Definition at line 132 of file ThreadPlanCallFunction.h.
Referenced by DoPlanExplainsStop(), DoTakedown(), GetRealStopInfo(), and ThreadPlanCallFunction().
m_return_type
CompilerType lldb_private::ThreadPlanCallFunction::m_return_type private
Definition at line 148 of file ThreadPlanCallFunction.h.
Referenced by SetReturnValue(), and ThreadPlanCallFunction().
m_return_valobj_sp
lldb::ValueObjectSP lldb_private::ThreadPlanCallFunction::m_return_valobj_sp protected
Definition at line 137 of file ThreadPlanCallFunction.h.
Referenced by GetReturnValueObject(), SetReturnValue(), lldb_private::ThreadPlanCallFunctionUsingABI::SetReturnValue(), and ThreadPlanCallFunction().
m_should_clear_cxx_exception_bp
bool lldb_private::ThreadPlanCallFunction::m_should_clear_cxx_exception_bp protected
Definition at line 143 of file ThreadPlanCallFunction.h.
Referenced by ClearBreakpoints(), SetBreakpoints(), and ThreadPlanCallFunction().
m_should_clear_objc_exception_bp
bool lldb_private::ThreadPlanCallFunction::m_should_clear_objc_exception_bp protected
Definition at line 142 of file ThreadPlanCallFunction.h.
Referenced by ClearBreakpoints(), SetBreakpoints(), and ThreadPlanCallFunction().
m_start_addr
Address lldb_private::ThreadPlanCallFunction::m_start_addr protected
Definition at line 125 of file ThreadPlanCallFunction.h.
Referenced by ConstructorSetup(), DidPush(), and ThreadPlanCallFunction().
m_stop_address
lldb::addr_t lldb_private::ThreadPlanCallFunction::m_stop_address protected
Definition at line 144 of file ThreadPlanCallFunction.h.
Referenced by DoTakedown(), GetStopAddress(), and ThreadPlanCallFunction().
m_stop_other_threads
bool lldb_private::ThreadPlanCallFunction::m_stop_other_threads protected
Definition at line 119 of file ThreadPlanCallFunction.h.
Referenced by DidPush(), StopOthers(), and ThreadPlanCallFunction().
m_stored_thread_state
Thread::ThreadStateCheckpoint lldb_private::ThreadPlanCallFunction::m_stored_thread_state protected
Definition at line 130 of file ThreadPlanCallFunction.h.
Referenced by ConstructorSetup(), DoTakedown(), RestoreThreadState(), and ThreadPlanCallFunction().
m_subplan_sp
lldb::ThreadPlanSP lldb_private::ThreadPlanCallFunction::m_subplan_sp protected
Definition at line 127 of file ThreadPlanCallFunction.h.
Referenced by DidPush(), DoPlanExplainsStop(), SetStopOthers(), and ThreadPlanCallFunction().
m_takedown_done
bool lldb_private::ThreadPlanCallFunction::m_takedown_done protected
Definition at line 140 of file ThreadPlanCallFunction.h.
Referenced by DoTakedown(), ShouldReportStop(), ThreadDestroyed(), and ThreadPlanCallFunction().
m_trap_exceptions
bool lldb_private::ThreadPlanCallFunction::m_trap_exceptions protected
Definition at line 123 of file ThreadPlanCallFunction.h.
Referenced by BreakpointsExplainStop(), ClearBreakpoints(), SetBreakpoints(), and ThreadPlanCallFunction().
m_unwind_on_error
bool lldb_private::ThreadPlanCallFunction::m_unwind_on_error protected
Definition at line 120 of file ThreadPlanCallFunction.h.
Referenced by DoPlanExplainsStop(), and ThreadPlanCallFunction().
m_valid
bool lldb_private::ThreadPlanCallFunction::m_valid protected
Definition at line 118 of file ThreadPlanCallFunction.h.
Referenced by DoTakedown(), ThreadPlanCallFunction(), lldb_private::ThreadPlanCallFunctionUsingABI::ThreadPlanCallFunctionUsingABI(), and ValidatePlan().
The documentation for this class was generated from the following files:
ThreadPlanCallFunction.h
ThreadPlanCallFunction.cpp