LLDB: lldb_private::Property Class Reference
lldb_private::Property Class Reference
#include <Property.h>
Public Member Functions
Property (const PropertyDefinition &definition)
Property (llvm::StringRef name, llvm::StringRef desc, bool is_global, const lldb::OptionValueSP &value_sp)
llvm::StringRef GetName () const
llvm::StringRef GetDescription () const
const lldb::OptionValueSP & GetValue () const
void SetOptionValue (const lldb::OptionValueSP &value_sp)
bool IsValid () const
bool IsGlobal () const
void Dump (const ExecutionContext *exe_ctx, Stream &strm, uint32_t dump_mask) const
bool DumpQualifiedName (Stream &strm) const
void DumpDescription (CommandInterpreter &interpreter, Stream &strm, uint32_t output_width, bool display_qualified_name) const
void SetValueChangedCallback (std::function< void()> callback)
Protected Attributes
std::string m_name
std::string m_description
lldb::OptionValueSP m_value_sp
bool m_is_global
Detailed Description
Definition at line 38 of file Property.h.
Constructor & Destructor Documentation
Property() [1/2]
Property::Property (const PropertyDefinition & definition)
Definition at line 22 of file Property.cpp.
References lldb_private::OptionValue::ConvertTypeToMask(), lldb_private::PropertyDefinition::default_uint_value, lldb_private::PropertyDefinition::enum_values, lldb_private::OptionValue::eTypeDictionary, lldb_private::OptionValue::eTypeEnum, m_description, m_is_global, m_name, m_value_sp, and lldb_private::PropertyDefinition::type.
Property() [2/2]
Property::Property (llvm::StringRef name, llvm::StringRef desc, bool is_global, const lldb::OptionValueSP & value_sp)
Definition at line 232 of file Property.cpp.
References m_description, m_is_global, m_name, and m_value_sp.
Member Function Documentation
Dump()
void Property::Dump (const ExecutionContext * exe_ctx, Stream & strm, uint32_t dump_mask) const
Definition at line 247 of file Property.cpp.
References DumpQualifiedName(), lldb_private::OptionValue::eDumpOptionCommand, lldb_private::OptionValue::eDumpOptionDescription, lldb_private::OptionValue::eDumpOptionName, lldb_private::Stream::EOL(), GetDescription(), m_name, m_value_sp, and lldb_private::Stream::PutChar().
DumpDescription()
void Property::DumpDescription (CommandInterpreter & interpreter, Stream & strm, uint32_t output_width, bool display_qualified_name) const
Definition at line 275 of file Property.cpp.
References lldb_private::OptionValueProperties::DumpAllDescriptions(), DumpQualifiedName(), lldb_private::Stream::EOL(), lldb_private::StreamString::GetData(), GetDescription(), lldb_private::StreamString::GetString(), m_name, m_value_sp, lldb_private::CommandInterpreter::OutputFormattedHelpText(), and lldb_private::Stream::Printf().
DumpQualifiedName()
bool Property::DumpQualifiedName (Stream & strm) const
Definition at line 237 of file Property.cpp.
References m_name, m_value_sp, and lldb_private::Stream::PutChar().
Referenced by Dump(), and DumpDescription().
GetDescription()
llvm::StringRef lldb_private::Property::GetDescription () const inline
Definition at line 46 of file Property.h.
References m_description.
Referenced by Dump(), and DumpDescription().
GetName()
llvm::StringRef lldb_private::Property::GetName () const inline
Definition at line 45 of file Property.h.
References m_name.
GetValue()
const lldb::OptionValueSP & lldb_private::Property::GetValue () const inline
Definition at line 48 of file Property.h.
References m_value_sp.
Referenced by lldb_private::TargetProperties::GetExperimentalPropertyValue(), lldb_private::ProcessProperties::GetOSPluginReportsAllThreads(), lldb_private::OptionValueProperties::GetPropertyValueAtIndex(), lldb_private::TargetProperties::GetUseDIL(), lldb_private::OptionValueProperties::GetValueForKey(), lldb_private::ProcessProperties::SetOSPluginReportsAllThreads(), and lldb_private::TargetProperties::SetUseDIL().
IsGlobal()
bool lldb_private::Property::IsGlobal () const inline
Definition at line 56 of file Property.h.
References m_is_global.
IsValid()
bool lldb_private::Property::IsValid () const inline
Definition at line 54 of file Property.h.
References m_value_sp.
Referenced by lldb_private::OptionValueProperties::Initialize().
SetOptionValue()
void lldb_private::Property::SetOptionValue (const lldb::OptionValueSP & value_sp) inline
Definition at line 50 of file Property.h.
References m_value_sp.
SetValueChangedCallback()
void Property::SetValueChangedCallback (std::function< void()> callback)
Definition at line 306 of file Property.cpp.
References m_value_sp.
Member Data Documentation
m_description
std::string lldb_private::Property::m_description protected
Definition at line 71 of file Property.h.
Referenced by GetDescription(), Property(), and Property().
m_is_global
bool lldb_private::Property::m_is_global protected
Definition at line 73 of file Property.h.
Referenced by IsGlobal(), Property(), and Property().
m_name
std::string lldb_private::Property::m_name protected
Definition at line 70 of file Property.h.
Referenced by Dump(), DumpDescription(), DumpQualifiedName(), GetName(), Property(), and Property().
m_value_sp
lldb::OptionValueSP lldb_private::Property::m_value_sp protected
Definition at line 72 of file Property.h.
Referenced by Dump(), DumpDescription(), DumpQualifiedName(), GetValue(), IsValid(), Property(), Property(), SetOptionValue(), and SetValueChangedCallback().
The documentation for this class was generated from the following files:
Property.h
Property.cpp