LLDB: lldb_private::SymbolFileCommon Class Reference
lldb_private::SymbolFileCommon Class Reference abstract
Containing protected virtual methods for child classes to override.
#include <SymbolFile.h>
Public Member Functions
SymbolFileCommon (lldb::ObjectFileSP objfile_sp)
~SymbolFileCommon () override=default
uint32_t GetAbilities () override
Get a mask of what this symbol file supports for the object file that it was constructed with.
Symtab * GetSymtab (bool can_create=true) override
ObjectFile * GetObjectFile () override
const ObjectFile * GetObjectFile () const override
ObjectFile * GetMainObjectFile () override
void SectionFileAddressesChanged () override
Notify the SymbolFile that the file addresses in the Sections for this module have been changed.
uint32_t GetNumCompileUnits () override
lldb::CompUnitSP GetCompileUnitAtIndex (uint32_t idx) override
llvm::Expected< lldb::TypeSystemSP > GetTypeSystemForLanguage (lldb::LanguageType language) override
void Dump (Stream &s) override
uint64_t GetDebugInfoSize (bool load_all_debug_info=false) override
Metrics gathering functions.
bool GetDebugInfoIndexWasLoadedFromCache () const override
Accessors for the bool that indicates if the debug info index was loaded from, or saved to the module index cache.
void SetDebugInfoIndexWasLoadedFromCache () override
bool GetDebugInfoIndexWasSavedToCache () const override
void SetDebugInfoIndexWasSavedToCache () override
bool GetDebugInfoHadFrameVariableErrors () const override
Accessors for the bool that indicates if there was debug info, but errors stopped variables from being able to be displayed correctly.
void SetDebugInfoHadFrameVariableErrors () override
lldb::TypeSP MakeType (lldb::user_id_t uid, ConstString name, std::optional< uint64_t > byte_size, SymbolContextScope *context, lldb::user_id_t encoding_uid, Type::EncodingDataType encoding_uid_type, const Declaration &decl, const CompilerType &compiler_qual_type, Type::ResolveState compiler_type_resolve_state, uint32_t opaque_payload=0) override
This function is used to create types that belong to a SymbolFile.
lldb::TypeSP CopyType (const lldb::TypeSP &other_type) override
Public Member Functions inherited from lldb_private::SymbolFile
SymbolFile ()=default
~SymbolFile () override=default
virtual SymbolFile * GetBackingSymbolFile ()
SymbolFileOnDemand class overrides this to return the underlying backing SymbolFile implementation that loads on-demand.
virtual uint32_t CalculateAbilities ()=0
virtual std::recursive_mutex & GetModuleMutex () const
Symbols file subclasses should override this to return the Module that owns the TypeSystem that this symbol file modifies type information in.
virtual void InitializeObject ()
Initialize the SymbolFile object.
virtual bool GetLoadDebugInfoEnabled ()
Whether debug info will be loaded or not.
virtual void SetLoadDebugInfoEnabled ()
Specify debug info should be loaded.
virtual lldb::LanguageType ParseLanguage (CompileUnit &comp_unit)=0
virtual XcodeSDK ParseXcodeSDK (CompileUnit &comp_unit)
Return the Xcode SDK comp_unit was compiled against.
virtual llvm::SmallSet< lldb::LanguageType, 4 > ParseAllLanguages (CompileUnit &comp_unit)
This function exists because SymbolFileDWARFDebugMap may extra compile units which aren't exposed as "real" compile units.
virtual size_t ParseFunctions (CompileUnit &comp_unit)=0
virtual bool ParseLineTable (CompileUnit &comp_unit)=0
virtual bool ParseDebugMacros (CompileUnit &comp_unit)=0
virtual bool ForEachExternalModule (lldb_private::CompileUnit &comp_unit, llvm::DenseSet< lldb_private::SymbolFile * > &visited_symbol_files, llvm::function_ref< bool(Module &)> lambda)
Apply a lambda to each external lldb::Module referenced by this comp_unit.
virtual bool ParseSupportFiles (CompileUnit &comp_unit, SupportFileList &support_files)=0
virtual size_t ParseTypes (CompileUnit &comp_unit)=0
virtual bool ParseIsOptimized (CompileUnit &comp_unit)
virtual bool ParseImportedModules (const SymbolContext &sc, std::vector< SourceModule > &imported_modules)=0
virtual size_t ParseBlocksRecursive (Function &func)=0
virtual size_t ParseVariablesForContext (const SymbolContext &sc)=0
virtual Type * ResolveTypeUID (lldb::user_id_t type_uid)=0
virtual std::optional< ArrayInfo > GetDynamicArrayInfoForUID (lldb::user_id_t type_uid, const lldb_private::ExecutionContext *exe_ctx)=0
If type_uid points to an array type, return its characteristics.
virtual bool CompleteType (CompilerType &compiler_type)=0
virtual void ParseDeclsForContext (CompilerDeclContext decl_ctx)
virtual CompilerDecl GetDeclForUID (lldb::user_id_t uid)
virtual CompilerDeclContext GetDeclContextForUID (lldb::user_id_t uid)
virtual CompilerDeclContext GetDeclContextContainingUID (lldb::user_id_t uid)
virtual std::vector< CompilerContext > GetCompilerContextForUID (lldb::user_id_t uid)
virtual uint32_t ResolveSymbolContext (const Address &so_addr, lldb::SymbolContextItem resolve_scope, SymbolContext &sc)=0
Status GetFrameVariableError (StackFrame &frame)
Get an error that describes why variables might be missing for a given symbol context.
virtual Status CalculateFrameVariableError (StackFrame &frame)
Subclasses will override this function to for GetFrameVariableError().
virtual uint32_t ResolveSymbolContext (const SourceLocationSpec &src_location_spec, lldb::SymbolContextItem resolve_scope, SymbolContextList &sc_list)
virtual void DumpClangAST (Stream &s, llvm::StringRef filter, bool show_colors)
virtual void FindGlobalVariables (ConstString name, const CompilerDeclContext &parent_decl_ctx, uint32_t max_matches, VariableList &variables)
virtual void FindGlobalVariables (const RegularExpression &regex, uint32_t max_matches, VariableList &variables)
virtual void FindFunctions (const Module::LookupInfo &lookup_info, const CompilerDeclContext &parent_decl_ctx, bool include_inlines, SymbolContextList &sc_list)
virtual void FindFunctions (llvm::ArrayRef< Module::LookupInfo > lookup_infos, const CompilerDeclContext &parent_decl_ctx, bool include_inlines, SymbolContextList &sc_list)
virtual void FindFunctions (const RegularExpression &regex, bool include_inlines, SymbolContextList &sc_list)
virtual void FindTypes (const TypeQuery &query, TypeResults &results)
Find types using a type-matching object that contains all search parameters.
virtual void GetMangledNamesForFunction (const std::string &scope_qualified_name, std::vector< ConstString > &mangled_names)
virtual llvm::Expected< SymbolContext > ResolveFunctionCallLabel (FunctionCallLabel &label)
Resolves the function corresponding to the specified LLDB function call label.
virtual void GetTypes (lldb_private::SymbolContextScope *sc_scope, lldb::TypeClass type_mask, lldb_private::TypeList &type_list)=0
virtual void PreloadSymbols ()
virtual CompilerDeclContext FindNamespace (ConstString name, const CompilerDeclContext &parent_decl_ctx, bool only_root_namespaces=false)
Finds a namespace of name name and whose parent context is parent_decl_ctx.
virtual std::vector< std::unique_ptr< CallEdge > > ParseCallEdgesInFunction (UserID func_id)
virtual void AddSymbols (Symtab &symtab)
virtual lldb::UnwindPlanSP GetUnwindPlan (const Address &address, const RegisterInfoResolver &resolver)
virtual llvm::Expected< lldb::addr_t > GetParameterStackSize (const Symbol &symbol)
Return the number of stack bytes taken up by the parameters to this function.
virtual StatsDuration::Duration GetDebugInfoParseTime ()
Return the time taken to parse the debug information.
virtual StatsDuration::Duration GetDebugInfoIndexTime ()
Return the time it took to index the debug information in the object file.
virtual void ResetStatistics ()
Reset the statistics for the symbol file.
virtual ModuleList GetDebugInfoModules ()
Get the additional modules that this symbol file uses to parse debug info.
virtual bool GetSeparateDebugInfo (StructuredData::Dictionary &d, bool errors_only, bool load_all_debug_info=false)
Return true if separate debug info files are supported and this function succeeded, false otherwise.
virtual DWOStats GetDwoStats ()
Retrieves statistics about DWO files associated with this symbol file.
std::unordered_map< lldb::CompUnitSP, Args > GetCompileOptions ()
Returns a map of compilation unit to the compile option arguments associated with that compilation unit.
std::string GetObjectName () const
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
virtual llvm::StringRef GetPluginName ()=0
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Protected Member Functions
virtual uint32_t CalculateNumCompileUnits ()=0
virtual lldb::CompUnitSP ParseCompileUnitAtIndex (uint32_t idx)=0
virtual TypeList & GetTypeList ()
void SetCompileUnitAtIndex (uint32_t idx, const lldb::CompUnitSP &cu_sp)
Protected Member Functions inherited from lldb_private::SymbolFile
void AssertModuleLock ()
virtual void GetCompileOptions (std::unordered_map< lldb::CompUnitSP, lldb_private::Args > &args)
Protected Attributes
lldb::ObjectFileSP m_objfile_sp
std::optional< std::vector< lldb::CompUnitSP > > m_compile_units
TypeList m_type_list
uint32_t m_abilities = 0
bool m_calculated_abilities = false
bool m_index_was_loaded_from_cache = false
bool m_index_was_saved_to_cache = false
bool m_debug_info_had_variable_errors = false
Set to true if any variable feteching errors have been found when calling GetFrameVariableError().
Private Member Functions
SymbolFileCommon (const SymbolFileCommon &)=delete
const SymbolFileCommon & operator= (const SymbolFileCommon &)=delete
Private Attributes
Symtab * m_symtab = nullptr
Do not use m_symtab directly, as it may be freed.
Static Private Attributes
static char ID
LLVM RTTI support.
bool isA (const void *ClassID) const override
LLVM RTTI support.
static bool classof (const SymbolFileCommon *obj)
Additional Inherited Members
Public Types inherited from lldb_private::SymbolFile
enum Abilities {
CompileUnits = (1u << 0) , LineTables = (1u << 1) , Functions = (1u << 2) , Blocks = (1u << 3) ,
GlobalVariables = (1u << 4) , LocalVariables = (1u << 5) , VariableTypes = (1u << 6) , kAllAbilities = ((1u << 7) - 1u)
}
Static Public Member Functions inherited from lldb_private::SymbolFile
static SymbolFile * FindPlugin (lldb::ObjectFileSP objfile_sp)
static bool classof (const SymbolFile *obj)
Detailed Description
Containing protected virtual methods for child classes to override.
Most actual SymbolFile implementations should inherit from this class.
Definition at line 541 of file SymbolFile.h.
Constructor & Destructor Documentation
SymbolFileCommon() [1/2]
lldb_private::SymbolFileCommon::SymbolFileCommon (lldb::ObjectFileSP objfile_sp) inline
Definition at line 555 of file SymbolFile.h.
References m_objfile_sp.
Referenced by classof(), operator=(), lldb_private::breakpad::SymbolFileBreakpad::SymbolFileBreakpad(), SymbolFileCommon(), lldb_private::SymbolFileCTF::SymbolFileCTF(), lldb_private::plugin::dwarf::SymbolFileDWARF::SymbolFileDWARF(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::SymbolFileDWARFDebugMap(), lldb_private::SymbolFileJSON::SymbolFileJSON(), lldb_private::npdb::SymbolFileNativePDB::SymbolFileNativePDB(), SymbolFilePDB::SymbolFilePDB(), and SymbolFileSymtab::SymbolFileSymtab().
~SymbolFileCommon()
lldb_private::SymbolFileCommon::~SymbolFileCommon () override default
SymbolFileCommon() [2/2]
lldb_private::SymbolFileCommon::SymbolFileCommon (const SymbolFileCommon &) private delete
References SymbolFileCommon().
Member Function Documentation
CalculateNumCompileUnits()
virtual uint32_t lldb_private::SymbolFileCommon::CalculateNumCompileUnits () protected pure virtual
Implemented in lldb_private::breakpad::SymbolFileBreakpad, lldb_private::npdb::SymbolFileNativePDB, lldb_private::plugin::dwarf::SymbolFileDWARF, lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap, lldb_private::SymbolFileCTF, lldb_private::SymbolFileJSON, SymbolFilePDB, and SymbolFileSymtab.
Referenced by GetNumCompileUnits().
classof()
bool lldb_private::SymbolFileCommon::classof (const SymbolFileCommon * obj) inline static
Definition at line 551 of file SymbolFile.h.
References ID, isA(), and SymbolFileCommon().
CopyType()
lldb::TypeSP lldb_private::SymbolFileCommon::CopyType (const lldb::TypeSP & other_type) inline override virtual
Implements lldb_private::SymbolFile.
Definition at line 631 of file SymbolFile.h.
References lldb_private::SymbolFile::GetBackingSymbolFile(), and m_type_list.
Dump()
void SymbolFileCommon::Dump (Stream & s) override virtual
Implements lldb_private::SymbolFile.
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARF.
Definition at line 250 of file SymbolFile.cpp.
References lldb_private::eSortOrderNone, lldb_private::Stream::Format(), GetMainObjectFile(), lldb_private::PluginInterface::GetPluginName(), GetSymtab(), m_compile_units, m_type_list, lldb_private::Stream::PutChar(), and lldb_private::Stream::PutCString().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::Dump().
GetAbilities()
uint32_t lldb_private::SymbolFileCommon::GetAbilities () inline override virtual
Get a mask of what this symbol file supports for the object file that it was constructed with.
Each symbol file gets to respond with a mask of abilities that it supports for each object file. This happens when we are trying to figure out which symbol file plug-in will get used for a given object file. The plug-in that responds with the best mix of "SymbolFile::Abilities" bits set, will get chosen to be the symbol file parser. This allows each plug-in to check for sections that contain data a symbol file plug-in would need. For example the DWARF plug-in requires DWARF sections in a file that contain debug information. If the DWARF plug-in doesn't find these sections, it won't respond with many ability bits set, and we will probably fall back to the symbol table SymbolFile plug-in which uses any information in the symbol table. Also, plug-ins might check for some specific symbols in a symbol table in the case where the symbol table contains debug information (STABS and COFF). Not a lot of work should happen in these functions as the plug-in might not get selected due to another plug-in having more abilities. Any initialization work should be saved for "void SymbolFile::InitializeObject()" which will get called on the SymbolFile object with the best set of abilities.
Returns
A uint32_t mask containing bits from the SymbolFile::Abilities enumeration. Any bits that are set represent an ability that this symbol plug-in can parse from the object file.
Implements lldb_private::SymbolFile.
Definition at line 560 of file SymbolFile.h.
References lldb_private::SymbolFile::CalculateAbilities(), m_abilities, and m_calculated_abilities.
GetCompileUnitAtIndex()
CompUnitSP SymbolFileCommon::GetCompileUnitAtIndex (uint32_t idx) override virtual
Implements lldb_private::SymbolFile.
Definition at line 200 of file SymbolFile.cpp.
References lldb_private::SymbolFile::GetModuleMutex(), GetNumCompileUnits(), and ParseCompileUnitAtIndex().
Referenced by lldb_private::breakpad::SymbolFileBreakpad::FindFunctions(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetCompileOptions(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDWOId(), and lldb_private::breakpad::SymbolFileBreakpad::ResolveSymbolContext().
GetDebugInfoHadFrameVariableErrors()
bool lldb_private::SymbolFileCommon::GetDebugInfoHadFrameVariableErrors () const inline override virtual
Accessors for the bool that indicates if there was debug info, but errors stopped variables from being able to be displayed correctly.
See GetFrameVariableError() for details on what are considered errors.
Implements lldb_private::SymbolFile.
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 604 of file SymbolFile.h.
References m_debug_info_had_variable_errors.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetDebugInfoHadFrameVariableErrors().
GetDebugInfoIndexWasLoadedFromCache()
bool lldb_private::SymbolFileCommon::GetDebugInfoIndexWasLoadedFromCache () const inline override virtual
Accessors for the bool that indicates if the debug info index was loaded from, or saved to the module index cache.
In statistics it is handy to know if a module's debug info was loaded from or saved to the cache. When the debug info index is loaded from the cache startup times can be faster. When the cache is enabled and the debug info index is saved to the cache, debug sessions can be slower. These accessors can be accessed by the statistics and emitted to help track these costs.
Implements lldb_private::SymbolFile.
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 592 of file SymbolFile.h.
References m_index_was_loaded_from_cache.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetDebugInfoIndexWasLoadedFromCache().
GetDebugInfoIndexWasSavedToCache()
bool lldb_private::SymbolFileCommon::GetDebugInfoIndexWasSavedToCache () const inline override virtual
Implements lldb_private::SymbolFile.
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 598 of file SymbolFile.h.
References m_index_was_saved_to_cache.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetDebugInfoIndexWasSavedToCache().
GetDebugInfoSize()
uint64_t SymbolFileCommon::GetDebugInfoSize (bool load_all_debug_info = false) override virtual
Metrics gathering functions.
Return the size in bytes of all loaded debug information or total possible debug info in the symbol file.
If the debug information is contained in sections of an ObjectFile, then this call should add the size of all sections that contain debug information. Symbols the symbol tables are not considered debug information for this call to make it easy and quick for this number to be calculated. If the symbol file is all debug information, the size of the entire file should be returned. The default implementation of this function will iterate over all sections in a module and add up their debug info only section byte sizes.
Parameters
load_all_debug_info If true, force loading any symbol files if they are not yet loaded and add to the total size. Default to false.
Returns
Total currently loaded debug info size in bytes
Implements lldb_private::SymbolFile.
Reimplemented in lldb_private::npdb::SymbolFileNativePDB, lldb_private::plugin::dwarf::SymbolFileDWARF, and lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 238 of file SymbolFile.cpp.
References lldb_private::SectionList::GetDebugInfoSize(), and m_objfile_sp.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::GetDebugInfoSize().
GetMainObjectFile()
ObjectFile * SymbolFileCommon::GetMainObjectFile () override virtual
Implements lldb_private::SymbolFile.
Definition at line 177 of file SymbolFile.cpp.
References m_objfile_sp.
Referenced by Dump(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetSeparateDebugInfo(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetSeparateDebugInfo(), GetSymtab(), and SectionFileAddressesChanged().
GetNumCompileUnits()
uint32_t SymbolFileCommon::GetNumCompileUnits () override virtual
Implements lldb_private::SymbolFile.
Definition at line 190 of file SymbolFile.cpp.
References CalculateNumCompileUnits(), lldb_private::SymbolFile::GetModuleMutex(), and m_compile_units.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CalculateAbilities(), lldb_private::npdb::SymbolFileNativePDB::CreateGlobalVariable(), lldb_private::breakpad::SymbolFileBreakpad::FindFunctions(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetCompileOptions(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetCompileUnit(), GetCompileUnitAtIndex(), SymbolFilePDB::GetCompileUnitIndex(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetCompileUnitInfo(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetCompUnitInfo(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetCompUnitInfosForModule(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDWOId(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetModuleByOSOIndex(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetSeparateDebugInfo(), SymbolFilePDB::GetTypes(), lldb_private::npdb::SymbolFileNativePDB::ParseCompileUnitAtIndex(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ParseCompileUnitAtIndex(), SymbolFilePDB::ParseCompileUnitAtIndex(), lldb_private::breakpad::SymbolFileBreakpad::ResolveSymbolContext(), lldb_private::npdb::SymbolFileNativePDB::ResolveSymbolContext(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::SetCompileUnit(), SetCompileUnitAtIndex(), and lldb_private::plugin::dwarf::SymbolFileDWARF::UpdateExternalModuleListIfNeeded().
GetObjectFile() [1/2]
const ObjectFile * lldb_private::SymbolFileCommon::GetObjectFile () const inline override virtual
Implements lldb_private::SymbolFile.
Definition at line 571 of file SymbolFile.h.
References m_objfile_sp.
GetObjectFile() [2/2]
ObjectFile * lldb_private::SymbolFileCommon::GetObjectFile () inline override virtual
Implements lldb_private::SymbolFile.
Definition at line 570 of file SymbolFile.h.
References m_objfile_sp.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::CompleteType(), SymbolFilePDB::CompleteType(), lldb_private::npdb::SymbolFileNativePDB::CreateBlock(), lldb_private::npdb::SymbolFileNativePDB::CreateConstantSymbol(), lldb_private::npdb::SymbolFileNativePDB::CreateGlobalVariable(), lldb_private::npdb::SymbolFileNativePDB::CreateLocalVariable(), lldb_private::plugin::dwarf::SymbolFileDWARF::DeclContextMatchesThisSymbolFile(), lldb_private::plugin::dwarf::DWARFDebugInfoEntry::Extract(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindDefinitionDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindFunctions(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindFunctions(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindGlobalVariables(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindGlobalVariables(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindNamespace(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindTypes(), fixupExternalAddrZeroVariable(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetDebugInfoModules(), lldb_private::plugin::dwarf::DWARFUnit::GetDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwoSymbolFileForCompileUnit(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwpSymbolFile(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo::GetFileRangeMap(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetGlobalAranges(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetModuleByCompUnitInfo(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetModuleMutex(), GetPtrAuthMofidierPayload(), lldb_private::plugin::dwarf::DWARFUnit::GetRnglistData(), lldb_private::plugin::dwarf::DWARFUnit::GetRnglistTable(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetTypeForDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetTypeUnitSupportFiles(), lldb_private::plugin::dwarf::SymbolFileDWARF::InitializeObject(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::LinkOSOAddress(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseAndAppendGlobalVariable(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseCallEdgesInFunction(), DWARFASTParserClang::ParseChildMembers(), SymbolFilePDB::ParseCompileUnitFunctionForPDBFunc(), lldb_private::SymbolFileCTF::ParseFunctions(), lldb_private::SymbolFileCTF::ParseHeader(), DWARFASTParserClang::ParseObjCProperty(), lldb_private::SymbolFileCTF::ParseObjects(), DWARFASTParserClang::ParseRustVariantPart(), DWARFASTParserClang::ParseSingleMember(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE(), SymbolFilePDB::ParseVariableForPDBData(), PrepareContextToReceiveMembers(), lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveType(), lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveTypeUID(), SectionFileAddressesChanged(), lldb_private::plugin::dwarf::DWARFUnit::SetLoclistsBase(), and lldb_private::plugin::dwarf::SymbolFileDWARF::UpdateExternalModuleListIfNeeded().
GetSymtab()
Symtab * SymbolFileCommon::GetSymtab (bool can_create = true) override virtual
Implements lldb_private::SymbolFile.
Definition at line 163 of file SymbolFile.cpp.
References lldb_private::SymbolFile::AddSymbols(), GetMainObjectFile(), lldb_private::SymbolFile::GetModuleMutex(), lldb_private::ObjectFile::GetSymtab(), and m_symtab.
Referenced by Dump(), lldb_private::plugin::dwarf::SymbolFileDWARF::PreloadSymbols(), and SectionFileAddressesChanged().
GetTypeList()
virtual TypeList & lldb_private::SymbolFileCommon::GetTypeList () inline protected virtual
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARF.
Definition at line 643 of file SymbolFile.h.
References m_type_list.
Referenced by lldb_private::SymbolFileCTF::FindTypes(), lldb_private::SymbolFileCTF::FindTypesByRegex(), lldb_private::npdb::SymbolFileNativePDB::GetOrCreateType(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetTypeList(), and lldb_private::npdb::SymbolFileNativePDB::ParseTypes().
GetTypeSystemForLanguage()
llvm::Expected< TypeSystemSP > SymbolFileCommon::GetTypeSystemForLanguage (lldb::LanguageType language) override virtual
Implements lldb_private::SymbolFile.
Reimplemented in lldb_private::npdb::SymbolFileNativePDB, lldb_private::plugin::dwarf::SymbolFileDWARF, lldb_private::plugin::dwarf::SymbolFileDWARFDwo, and SymbolFilePDB.
Definition at line 228 of file SymbolFile.cpp.
References m_objfile_sp.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::GetTypeSystemForLanguage(), and lldb_private::SymbolFileCTF::InitializeObject().
isA()
bool lldb_private::SymbolFileCommon::isA (const void * ClassID) const inline override virtual
LLVM RTTI support.
Reimplemented from lldb_private::SymbolFile.
Reimplemented in lldb_private::npdb::SymbolFileNativePDB, lldb_private::plugin::dwarf::SymbolFileDWARF, lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap, lldb_private::plugin::dwarf::SymbolFileDWARFDwo, lldb_private::SymbolFileCTF, lldb_private::SymbolFileJSON, SymbolFilePDB, and SymbolFileSymtab.
Definition at line 548 of file SymbolFile.h.
References ID, and lldb_private::SymbolFile::isA().
Referenced by classof(), lldb_private::breakpad::SymbolFileBreakpad::isA(), lldb_private::npdb::SymbolFileNativePDB::isA(), lldb_private::plugin::dwarf::SymbolFileDWARF::isA(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::isA(), lldb_private::SymbolFileCTF::isA(), and lldb_private::SymbolFileJSON::isA().
MakeType()
lldb::TypeSP lldb_private::SymbolFileCommon::MakeType (lldb::user_id_t uid, ConstString name, std::optional< uint64_t > byte_size, SymbolContextScope * context, lldb::user_id_t encoding_uid, Type::EncodingDataType encoding_uid_type, const Declaration & decl, const CompilerType & compiler_qual_type, Type::ResolveState compiler_type_resolve_state, uint32_t opaque_payload = 0) inline override virtual
This function is used to create types that belong to a SymbolFile.
The symbol file will own a strong reference to the type in an internal type list.
Implements lldb_private::SymbolFile.
Definition at line 614 of file SymbolFile.h.
References m_type_list.
Referenced by lldb_private::SymbolFileCTF::CreateArray(), lldb_private::npdb::SymbolFileNativePDB::CreateArrayType(), lldb_private::npdb::SymbolFileNativePDB::CreateClassStructUnion(), lldb_private::SymbolFileCTF::CreateEnum(), lldb_private::SymbolFileCTF::CreateForward(), lldb_private::SymbolFileCTF::CreateFunction(), lldb_private::npdb::SymbolFileNativePDB::CreateFunctionType(), lldb_private::SymbolFileCTF::CreateInteger(), lldb_private::SymbolFileCTF::CreateModifier(), lldb_private::npdb::SymbolFileNativePDB::CreateModifierType(), lldb_private::npdb::SymbolFileNativePDB::CreatePointerType(), lldb_private::npdb::SymbolFileNativePDB::CreateProcedureType(), lldb_private::SymbolFileCTF::CreateRecord(), lldb_private::npdb::SymbolFileNativePDB::CreateSimpleType(), lldb_private::npdb::SymbolFileNativePDB::CreateTypedef(), lldb_private::SymbolFileCTF::CreateTypedef(), and lldb_private::SymbolFileCTF::ParseFunctions().
operator=()
const SymbolFileCommon & lldb_private::SymbolFileCommon::operator= (const SymbolFileCommon &) private delete
References SymbolFileCommon().
ParseCompileUnitAtIndex()
virtual lldb::CompUnitSP lldb_private::SymbolFileCommon::ParseCompileUnitAtIndex (uint32_t idx) protected pure virtual
Implemented in lldb_private::breakpad::SymbolFileBreakpad, lldb_private::npdb::SymbolFileNativePDB, lldb_private::plugin::dwarf::SymbolFileDWARF, lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap, lldb_private::SymbolFileCTF, lldb_private::SymbolFileJSON, SymbolFilePDB, and SymbolFileSymtab.
Referenced by GetCompileUnitAtIndex().
SectionFileAddressesChanged()
void SymbolFileCommon::SectionFileAddressesChanged () override virtual
Notify the SymbolFile that the file addresses in the Sections for this module have been changed.
Implements lldb_private::SymbolFile.
Definition at line 181 of file SymbolFile.cpp.
References GetMainObjectFile(), GetObjectFile(), GetSymtab(), and lldb_private::ObjectFile::SectionFileAddressesChanged().
SetCompileUnitAtIndex()
void SymbolFileCommon::SetCompileUnitAtIndex (uint32_t idx, const lldb::CompUnitSP & cu_sp) protected
Definition at line 211 of file SymbolFile.cpp.
References lldb_private::SymbolFile::GetModuleMutex(), GetNumCompileUnits(), m_compile_units, and UNUSED_IF_ASSERT_DISABLED.
Referenced by lldb_private::npdb::SymbolFileNativePDB::CreateCompileUnit(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseCompileUnit(), lldb_private::breakpad::SymbolFileBreakpad::ParseCompileUnitAtIndex(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ParseCompileUnitAtIndex(), SymbolFilePDB::ParseCompileUnitForUID(), and lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::SetCompileUnit().
SetDebugInfoHadFrameVariableErrors()
void lldb_private::SymbolFileCommon::SetDebugInfoHadFrameVariableErrors () inline override virtual
Implements lldb_private::SymbolFile.
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 607 of file SymbolFile.h.
References m_debug_info_had_variable_errors.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDwo::SetDebugInfoHadFrameVariableErrors().
SetDebugInfoIndexWasLoadedFromCache()
void lldb_private::SymbolFileCommon::SetDebugInfoIndexWasLoadedFromCache () inline override virtual
Implements lldb_private::SymbolFile.
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 595 of file SymbolFile.h.
References m_index_was_loaded_from_cache.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDwo::SetDebugInfoIndexWasLoadedFromCache().
SetDebugInfoIndexWasSavedToCache()
void lldb_private::SymbolFileCommon::SetDebugInfoIndexWasSavedToCache () inline override virtual
Implements lldb_private::SymbolFile.
Reimplemented in lldb_private::plugin::dwarf::SymbolFileDWARFDwo.
Definition at line 601 of file SymbolFile.h.
References m_index_was_saved_to_cache.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDwo::SetDebugInfoIndexWasSavedToCache().
Member Data Documentation
ID
char SymbolFileCommon::ID static private
LLVM RTTI support.
Definition at line 543 of file SymbolFile.h.
Referenced by classof(), and isA().
m_abilities
uint32_t lldb_private::SymbolFileCommon::m_abilities = 0 protected
Definition at line 652 of file SymbolFile.h.
Referenced by GetAbilities().
m_calculated_abilities
bool lldb_private::SymbolFileCommon::m_calculated_abilities = false protected
Definition at line 653 of file SymbolFile.h.
Referenced by GetAbilities().
m_compile_units
std::optional<std::vector<lldb::CompUnitSP> > lldb_private::SymbolFileCommon::m_compile_units protected
Definition at line 650 of file SymbolFile.h.
Referenced by Dump(), GetNumCompileUnits(), and SetCompileUnitAtIndex().
m_debug_info_had_variable_errors
bool lldb_private::SymbolFileCommon::m_debug_info_had_variable_errors = false protected
Set to true if any variable feteching errors have been found when calling GetFrameVariableError().
This will be emitted in the "statistics dump" information for a module.
Definition at line 659 of file SymbolFile.h.
Referenced by GetDebugInfoHadFrameVariableErrors(), and SetDebugInfoHadFrameVariableErrors().
m_index_was_loaded_from_cache
bool lldb_private::SymbolFileCommon::m_index_was_loaded_from_cache = false protected
Definition at line 654 of file SymbolFile.h.
Referenced by GetDebugInfoIndexWasLoadedFromCache(), and SetDebugInfoIndexWasLoadedFromCache().
m_index_was_saved_to_cache
bool lldb_private::SymbolFileCommon::m_index_was_saved_to_cache = false protected
Definition at line 655 of file SymbolFile.h.
Referenced by GetDebugInfoIndexWasSavedToCache(), and SetDebugInfoIndexWasSavedToCache().
m_objfile_sp
lldb::ObjectFileSP lldb_private::SymbolFileCommon::m_objfile_sp protected
Definition at line 646 of file SymbolFile.h.
Referenced by lldb_private::breakpad::SymbolFileBreakpad::AddSymbols(), lldb_private::npdb::SymbolFileNativePDB::AddSymbols(), lldb_private::SymbolFileJSON::AddSymbols(), SymbolFilePDB::AddSymbols(), lldb_private::breakpad::SymbolFileBreakpad::CalculateAbilities(), lldb_private::npdb::SymbolFileNativePDB::CalculateAbilities(), lldb_private::plugin::dwarf::SymbolFileDWARF::CalculateAbilities(), lldb_private::SymbolFileCTF::CalculateAbilities(), lldb_private::SymbolFileJSON::CalculateAbilities(), SymbolFilePDB::CalculateAbilities(), SymbolFileSymtab::CalculateAbilities(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CalculateFrameVariableError(), lldb_private::npdb::SymbolFileNativePDB::CreateCompileUnit(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindCompleteObjCDefinitionTypeForDIE(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FindCompleteObjCDefinitionTypeForDIE(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FindFunctions(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FindFunctions(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindGlobalVariables(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindGlobalVariables(), SymbolFilePDB::FindGlobalVariables(), SymbolFilePDB::FindGlobalVariables(), lldb_private::breakpad::SymbolFileBreakpad::GetBaseFileAddress(), lldb_private::breakpad::SymbolFileBreakpad::GetDebugInfoSize(), lldb_private::plugin::dwarf::SymbolFileDWARFDwo::GetDebugInfoSize(), GetDebugInfoSize(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwoSymbolFileForCompileUnit(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwpSymbolFile(), GetMainObjectFile(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetModuleByCompUnitInfo(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetObjCClassSymbol(), GetObjectFile(), GetObjectFile(), lldb_private::breakpad::SymbolFileBreakpad::GetOrCreateFunction(), lldb_private::breakpad::SymbolFileBreakpad::GetParameterStackSize(), lldb_private::npdb::SymbolFileNativePDB::GetTypeSystemForLanguage(), GetTypeSystemForLanguage(), SymbolFilePDB::GetTypeSystemForLanguage(), lldb_private::plugin::dwarf::SymbolFileDWARF::InitializeFirstCodeAddress(), lldb_private::npdb::SymbolFileNativePDB::InitializeObject(), lldb_private::SymbolFileCTF::InitializeObject(), SymbolFilePDB::InitializeObject(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::InitOSO(), lldb_private::breakpad::SymbolFileBreakpad::lines(), lldb_private::plugin::dwarf::SymbolFileDWARF::LoadSectionData(), lldb_private::breakpad::SymbolFileBreakpad::ParseBlocksRecursive(), lldb_private::breakpad::SymbolFileBreakpad::ParseCFIUnwindPlan(), lldb_private::breakpad::SymbolFileBreakpad::ParseCFIUnwindRow(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseCompileUnit(), lldb_private::breakpad::SymbolFileBreakpad::ParseCompileUnitAtIndex(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ParseCompileUnitAtIndex(), SymbolFileSymtab::ParseCompileUnitAtIndex(), SymbolFilePDB::ParseCompileUnitForUID(), lldb_private::breakpad::SymbolFileBreakpad::ParseCUData(), SymbolFileSymtab::ParseFunctions(), lldb_private::SymbolFileCTF::ParseHeader(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseImportedModules(), lldb_private::breakpad::SymbolFileBreakpad::ParseLineTableAndSupportFiles(), lldb_private::breakpad::SymbolFileBreakpad::ParseUnwindData(), lldb_private::breakpad::SymbolFileBreakpad::ParseWinUnwindPlan(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseXcodeSDK(), lldb_private::SymbolFileCTF::ResolveSymbolContext(), lldb_private::SymbolFileJSON::ResolveSymbolContext(), SymbolFileSymtab::ResolveSymbolContext(), lldb_private::breakpad::SymbolFileBreakpad::SaveAsDWARF(), SymbolFileCommon(), lldb_private::plugin::dwarf::SymbolFileDWARF::SymbolFileDWARF(), and lldb_private::plugin::dwarf::SymbolFileDWARF::UpdateExternalModuleListIfNeeded().
m_symtab
Symtab* lldb_private::SymbolFileCommon::m_symtab = nullptr private
Do not use m_symtab directly, as it may be freed.
Use GetSymtab() to access it instead.
Definition at line 667 of file SymbolFile.h.
Referenced by GetSymtab().
m_type_list
TypeList lldb_private::SymbolFileCommon::m_type_list protected
Definition at line 651 of file SymbolFile.h.
Referenced by CopyType(), Dump(), GetTypeList(), and MakeType().
The documentation for this class was generated from the following files:
SymbolFile.h
SymbolFile.cpp