LLDB: lldb::SBStream Class Reference
lldb::SBStream Class Reference
#include <SBStream.h>
Public Member Functions
SBStream ()
SBStream (SBStream &&rhs)
~SBStream ()
operator bool () const
bool IsValid () const
const char * GetData ()
size_t GetSize ()
__attribute__ ((format(printf, 2, 3))) void Printf(const char *format
void Print (const char *str)
void RedirectToFile (const char *path, bool append)
void RedirectToFile (lldb::SBFile file)
void RedirectToFile (lldb::FileSP file)
void RedirectToFileHandle (FILE *fh, bool transfer_fh_ownership)
void RedirectToFileDescriptor (int fd, bool transfer_fh_ownership)
void Clear ()
Protected Member Functions
lldb_private::Stream * operator-> ()
lldb_private::Stream * get ()
lldb_private::Stream & ref ()
Private Member Functions
SBStream (const SBStream &)=delete
const SBStream & operator= (const SBStream &)=delete
Private Attributes
std::unique_ptr< lldb_private::Stream > m_opaque_up
bool m_is_file = false
Friends
class SBAddress
class SBAddressRange
class SBAddressRangeList
class SBBlock
class SBBreakpoint
class SBBreakpointLocation
class SBBreakpointName
class SBCommandReturnObject
class SBCompileUnit
class SBData
class SBDebugger
class SBDeclaration
class SBEvent
class SBFileSpec
class SBFileSpecList
class SBFrame
class SBFrameList
class SBFunction
class SBInstruction
class SBInstructionList
class SBLaunchInfo
class SBLineEntry
class SBMemoryRegionInfo
class SBModule
class SBModuleSpec
class SBModuleSpecList
class SBProcess
class SBSection
class SBSourceManager
class SBStructuredData
class SBSymbol
class SBSymbolContext
class SBSymbolContextList
class SBTarget
class SBThread
class SBThreadPlan
class SBType
class SBTypeEnumMember
class SBTypeMemberFunction
class SBTypeMember
class SBValue
class SBWatchpoint
class lldb_private::ScriptInterpreter
Detailed Description
Definition at line 22 of file SBStream.h.
Constructor & Destructor Documentation
SBStream() [1/3]
SBStream::SBStream ()
Definition at line 23 of file SBStream.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by operator=(), SBStream(), and SBStream().
SBStream() [2/3]
SBStream::SBStream (SBStream && rhs)
Definition at line 27 of file SBStream.cpp.
References m_is_file, m_opaque_up, and SBStream().
~SBStream()
SBStream::~SBStream () default
References GetData(), GetSize(), and IsValid().
SBStream() [3/3]
lldb::SBStream::SBStream (const SBStream &) private delete
References SBStream().
Member Function Documentation
__attribute__()
lldb::SBStream::__attribute__ ((format(printf, 2, 3))) const
References Clear(), Print(), RedirectToFile(), RedirectToFileDescriptor(), and RedirectToFileHandle().
Clear()
void SBStream::Clear ()
Definition at line 184 of file SBStream.cpp.
References lldb_private::StreamString::Clear(), LLDB_INSTRUMENT_VA, m_is_file, and m_opaque_up.
Referenced by __attribute__().
get()
lldb_private::Stream * SBStream::get () protected
Definition at line 176 of file SBStream.cpp.
References m_opaque_up.
Referenced by lldb::SBSourceManager::DisplaySourceLinesWithLineNumbersAndColumn(), lldb::SBBreakpoint::GetDescription(), lldb::SBBreakpointName::GetDescription(), lldb::SBThreadPlan::GetDescription(), and lldb_private::ScriptInterpreter.
GetData()
const char * SBStream::GetData ()
Definition at line 44 of file SBStream.cpp.
References lldb_private::ConstString::GetCString(), lldb_private::StreamString::GetData(), LLDB_INSTRUMENT_VA, m_is_file, and m_opaque_up.
Referenced by lldb::SBTypeSummary::CreateWithCallback(), lldb::SBDebugger::GetSelectedTarget(), lldb::SBValue::GetSummary(), lldb::SBCommandInterpreter::HandleCommandsFromFile(), lldb::SBStructuredData::SetFromJSON(), lldb::SBDebugger::SetSelectedTarget(), and ~SBStream().
GetSize()
size_t SBStream::GetSize ()
Definition at line 56 of file SBStream.cpp.
References lldb_private::StreamString::GetSize(), LLDB_INSTRUMENT_VA, m_is_file, and m_opaque_up.
Referenced by lldb::SBTypeSummary::CreateWithCallback(), and ~SBStream().
IsValid()
bool SBStream::IsValid () const
Definition at line 32 of file SBStream.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBStream().
operator bool()
SBStream::operator bool () const explicit
Definition at line 36 of file SBStream.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
operator->()
lldb_private::Stream * SBStream::operator-> () protected
Definition at line 174 of file SBStream.cpp.
References m_opaque_up.
Referenced by lldb_private::ScriptInterpreter.
operator=()
const SBStream & lldb::SBStream::operator= (const SBStream &) private delete
References SBStream().
Print()
void SBStream::Print (const char * str)
Definition at line 65 of file SBStream.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by __attribute__(), and lldb::SBStructuredData::SetFromJSON().
RedirectToFile() [1/3]
void SBStream::RedirectToFile (const char * path, bool append)
Definition at line 80 of file SBStream.cpp.
References lldb_private::API, lldb_private::File::eOpenOptionAppend, lldb_private::File::eOpenOptionCanCreate, lldb_private::File::eOpenOptionTruncate, lldb_private::File::eOpenOptionWriteOnly, lldb_private::GetLog(), lldb_private::StreamString::GetString(), lldb_private::FileSystem::Instance(), LLDB_INSTRUMENT_VA, LLDB_LOG_ERROR, m_is_file, m_opaque_up, and lldb_private::FileSystem::Open().
Referenced by __attribute__(), RedirectToFile(), and RedirectToFileHandle().
RedirectToFile() [2/3]
void SBStream::RedirectToFile (lldb::FileSP file)
Definition at line 129 of file SBStream.cpp.
References lldb_private::StreamString::GetString(), LLDB_INSTRUMENT_VA, m_is_file, and m_opaque_up.
RedirectToFile() [3/3]
void SBStream::RedirectToFile (lldb::SBFile file)
Definition at line 124 of file SBStream.cpp.
References lldb::SBFile::GetFile(), LLDB_INSTRUMENT_VA, and RedirectToFile().
RedirectToFileDescriptor()
void SBStream::RedirectToFileDescriptor (int fd, bool transfer_fh_ownership)
Definition at line 153 of file SBStream.cpp.
References lldb_private::StreamString::GetString(), LLDB_INSTRUMENT_VA, m_is_file, and m_opaque_up.
Referenced by __attribute__().
RedirectToFileHandle()
void SBStream::RedirectToFileHandle (FILE * fh, bool transfer_fh_ownership)
Definition at line 117 of file SBStream.cpp.
References lldb_private::File::eOpenOptionReadWrite, LLDB_INSTRUMENT_VA, and RedirectToFile().
Referenced by __attribute__().
ref()
lldb_private::Stream & SBStream::ref () protected
Definition at line 178 of file SBStream.cpp.
References m_opaque_up.
Referenced by lldb::SBStructuredData::GetAsJSON(), lldb::SBAddress::GetDescription(), lldb::SBAddressRange::GetDescription(), lldb::SBAddressRangeList::GetDescription(), lldb::SBBlock::GetDescription(), lldb::SBBreakpointLocation::GetDescription(), lldb::SBCommandReturnObject::GetDescription(), lldb::SBCompileUnit::GetDescription(), lldb::SBData::GetDescription(), lldb::SBDebugger::GetDescription(), lldb::SBDeclaration::GetDescription(), lldb::SBEvent::GetDescription(), lldb::SBEvent::GetDescription(), lldb::SBFileSpec::GetDescription(), lldb::SBFileSpecList::GetDescription(), lldb::SBFrame::GetDescription(), lldb::SBFrameList::GetDescription(), lldb::SBInstruction::GetDescription(), lldb::SBInstructionList::GetDescription(), lldb::SBInstructionList::GetDescription(), lldb::SBLineEntry::GetDescription(), lldb::SBMemoryRegionInfo::GetDescription(), lldb::SBModule::GetDescription(), lldb::SBModuleSpec::GetDescription(), lldb::SBModuleSpecList::GetDescription(), lldb::SBProcess::GetDescription(), lldb::SBSection::GetDescription(), lldb::SBStructuredData::GetDescription(), lldb::SBSymbol::GetDescription(), lldb::SBSymbolContext::GetDescription(), lldb::SBSymbolContextList::GetDescription(), lldb::SBTarget::GetDescription(), lldb::SBThread::GetDescription(), lldb::SBType::GetDescription(), lldb::SBTypeEnumMember::GetDescription(), lldb::SBTypeMember::GetDescription(), lldb::SBTypeMemberFunction::GetDescription(), lldb::SBValue::GetDescription(), lldb::SBWatchpoint::GetDescription(), lldb::SBFrame::GetDescriptionWithFormat(), lldb::SBThread::GetDescriptionWithFormat(), lldb::SBValue::GetExpressionPath(), lldb::SBValue::GetExpressionPath(), lldb::SBThread::GetInfoItemByPathAsString(), lldb::SBProcess::GetStatus(), lldb::SBThread::GetStatus(), lldb::SBThread::GetStopDescription(), lldb::SBThread::GetStopReasonExtendedInfoAsJSON(), lldb_private::ScriptInterpreter, and lldb::SBInstruction::TestEmulation().
Friends And Related Symbol Documentation
lldb_private::ScriptInterpreter
friend class lldb_private::ScriptInterpreter friend
Definition at line 111 of file SBStream.h.
References get(), operator->(), and ref().
SBAddress
friend class SBAddress friend
Definition at line 68 of file SBStream.h.
References SBAddress.
Referenced by SBAddress.
SBAddressRange
friend class SBAddressRange friend
Definition at line 69 of file SBStream.h.
References SBAddressRange.
Referenced by SBAddressRange.
SBAddressRangeList
friend class SBAddressRangeList friend
Definition at line 70 of file SBStream.h.
References SBAddressRangeList.
Referenced by SBAddressRangeList.
SBBlock
friend class SBBlock friend
Definition at line 71 of file SBStream.h.
References SBBlock.
Referenced by SBBlock.
SBBreakpoint
friend class SBBreakpoint friend
Definition at line 72 of file SBStream.h.
References SBBreakpoint.
Referenced by SBBreakpoint.
SBBreakpointLocation
friend class SBBreakpointLocation friend
Definition at line 73 of file SBStream.h.
References SBBreakpointLocation.
Referenced by SBBreakpointLocation.
SBBreakpointName
friend class SBBreakpointName friend
Definition at line 74 of file SBStream.h.
References SBBreakpointName.
Referenced by SBBreakpointName.
SBCommandReturnObject
friend class SBCommandReturnObject friend
Definition at line 75 of file SBStream.h.
References SBCommandReturnObject.
Referenced by SBCommandReturnObject.
SBCompileUnit
friend class SBCompileUnit friend
Definition at line 76 of file SBStream.h.
References SBCompileUnit.
Referenced by SBCompileUnit.
SBData
friend class SBData friend
Definition at line 77 of file SBStream.h.
References SBData.
Referenced by SBData.
SBDebugger
friend class SBDebugger friend
Definition at line 78 of file SBStream.h.
References SBDebugger.
Referenced by SBDebugger.
SBDeclaration
friend class SBDeclaration friend
Definition at line 79 of file SBStream.h.
References SBDeclaration.
Referenced by SBDeclaration.
SBEvent
friend class SBEvent friend
Definition at line 80 of file SBStream.h.
References SBEvent.
Referenced by SBEvent.
SBFileSpec
friend class SBFileSpec friend
Definition at line 81 of file SBStream.h.
References SBFileSpec.
Referenced by SBFileSpec.
SBFileSpecList
friend class SBFileSpecList friend
Definition at line 82 of file SBStream.h.
References SBFileSpecList.
Referenced by SBFileSpecList.
SBFrame
friend class SBFrame friend
Definition at line 83 of file SBStream.h.
References SBFrame.
Referenced by SBFrame.
SBFrameList
friend class SBFrameList friend
Definition at line 84 of file SBStream.h.
References SBFrameList.
Referenced by SBFrameList.
SBFunction
friend class SBFunction friend
Definition at line 85 of file SBStream.h.
References SBFunction.
Referenced by SBFunction.
SBInstruction
friend class SBInstruction friend
Definition at line 86 of file SBStream.h.
References SBInstruction.
Referenced by SBInstruction.
SBInstructionList
friend class SBInstructionList friend
Definition at line 87 of file SBStream.h.
References SBInstructionList.
Referenced by SBInstructionList.
SBLaunchInfo
friend class SBLaunchInfo friend
Definition at line 88 of file SBStream.h.
References SBLaunchInfo.
Referenced by SBLaunchInfo.
SBLineEntry
friend class SBLineEntry friend
Definition at line 89 of file SBStream.h.
References SBLineEntry.
Referenced by SBLineEntry.
SBMemoryRegionInfo
friend class SBMemoryRegionInfo friend
Definition at line 90 of file SBStream.h.
References SBMemoryRegionInfo.
Referenced by SBMemoryRegionInfo.
SBModule
friend class SBModule friend
Definition at line 91 of file SBStream.h.
References SBModule.
Referenced by SBModule.
SBModuleSpec
friend class SBModuleSpec friend
Definition at line 92 of file SBStream.h.
References SBModuleSpec.
Referenced by SBModuleSpec.
SBModuleSpecList
friend class SBModuleSpecList friend
Definition at line 93 of file SBStream.h.
References SBModuleSpecList.
Referenced by SBModuleSpecList.
SBProcess
friend class SBProcess friend
Definition at line 94 of file SBStream.h.
References SBProcess.
Referenced by SBProcess.
SBSection
friend class SBSection friend
Definition at line 95 of file SBStream.h.
References SBSection.
Referenced by SBSection.
SBSourceManager
friend class SBSourceManager friend
Definition at line 96 of file SBStream.h.
References SBSourceManager.
Referenced by SBSourceManager.
SBStructuredData
friend class SBStructuredData friend
Definition at line 97 of file SBStream.h.
References SBStructuredData.
Referenced by SBStructuredData.
SBSymbol
friend class SBSymbol friend
Definition at line 98 of file SBStream.h.
References SBSymbol.
Referenced by SBSymbol.
SBSymbolContext
friend class SBSymbolContext friend
Definition at line 99 of file SBStream.h.
References SBSymbolContext.
Referenced by SBSymbolContext.
SBSymbolContextList
friend class SBSymbolContextList friend
Definition at line 100 of file SBStream.h.
References SBSymbolContextList.
Referenced by SBSymbolContextList.
SBTarget
friend class SBTarget friend
Definition at line 101 of file SBStream.h.
References SBTarget.
Referenced by SBTarget.
SBThread
friend class SBThread friend
Definition at line 102 of file SBStream.h.
References SBThread.
Referenced by SBThread.
SBThreadPlan
friend class SBThreadPlan friend
Definition at line 103 of file SBStream.h.
References SBThreadPlan.
Referenced by SBThreadPlan.
SBType
friend class SBType friend
Definition at line 104 of file SBStream.h.
References SBType.
Referenced by SBType.
SBTypeEnumMember
friend class SBTypeEnumMember friend
Definition at line 105 of file SBStream.h.
References SBTypeEnumMember.
Referenced by SBTypeEnumMember.
SBTypeMember
friend class SBTypeMember friend
Definition at line 107 of file SBStream.h.
References SBTypeMember.
Referenced by SBTypeMember.
SBTypeMemberFunction
friend class SBTypeMemberFunction friend
Definition at line 106 of file SBStream.h.
References SBTypeMemberFunction.
Referenced by SBTypeMemberFunction.
SBValue
friend class SBValue friend
Definition at line 108 of file SBStream.h.
References SBValue.
Referenced by SBValue.
SBWatchpoint
friend class SBWatchpoint friend
Definition at line 109 of file SBStream.h.
References SBWatchpoint.
Referenced by SBWatchpoint.
Member Data Documentation
m_is_file
bool lldb::SBStream::m_is_file = false private
Definition at line 123 of file SBStream.h.
Referenced by Clear(), GetData(), GetSize(), RedirectToFile(), RedirectToFile(), RedirectToFileDescriptor(), and SBStream().
m_opaque_up
std::unique_ptr<lldb_private::Stream> lldb::SBStream::m_opaque_up private
Definition at line 122 of file SBStream.h.
Referenced by Clear(), get(), GetData(), lldb_private::ScriptInterpreter::GetOpaqueTypeFromSBStream(), GetSize(), operator bool(), operator->(), RedirectToFile(), RedirectToFile(), RedirectToFileDescriptor(), ref(), SBStream(), and SBStream().
The documentation for this class was generated from the following files:
SBStream.h
SBStream.cpp