LLDB: lldb::SBFrameList Class Reference
lldb::SBFrameList Class Reference
Represents a list of SBFrame objects.
#include <SBFrameList.h>
Public Member Functions
SBFrameList ()
SBFrameList (const lldb::SBFrameList &rhs)
~SBFrameList ()
const lldb::SBFrameList & operator= (const lldb::SBFrameList &rhs)
operator bool () const
bool IsValid () const
uint32_t GetSize () const
Returns the number of frames in the list.
lldb::SBFrame GetFrameAtIndex (uint32_t idx) const
Returns the frame at the given index.
lldb::SBThread GetThread () const
Get the thread associated with this frame list.
void Clear ()
Clear all frames from this list.
bool GetDescription (lldb::SBStream &description) const
Get a description of this frame list.
Private Member Functions
SBFrameList (const lldb::StackFrameListSP &frame_list_sp)
void SetFrameList (const lldb::StackFrameListSP &frame_list_sp)
Private Attributes
lldb::StackFrameListSP m_opaque_sp
Friends
class SBThread
class lldb_private::python::SWIGBridge
class lldb_private::lua::SWIGBridge
class lldb_private::ScriptInterpreter
Detailed Description
Represents a list of SBFrame objects.
SBFrameList provides a way to iterate over stack frames lazily, materializing frames on-demand as they are accessed. This is more efficient than eagerly creating all frames upfront.
Definition at line 31 of file SBFrameList.h.
Constructor & Destructor Documentation
SBFrameList() [1/3]
SBFrameList::SBFrameList ()
Definition at line 20 of file SBFrameList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by lldb_private::ScriptInterpreter, operator=(), and SBFrameList().
SBFrameList() [2/3]
SBFrameList::SBFrameList (const lldb::SBFrameList & rhs)
Definition at line 22 of file SBFrameList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBFrameList().
~SBFrameList()
SBFrameList::~SBFrameList () default
References Clear(), GetDescription(), GetFrameAtIndex(), GetSize(), GetThread(), IsValid(), and operator=().
SBFrameList() [3/3]
SBFrameList::SBFrameList (const lldb::StackFrameListSP & frame_list_sp) private
Definition at line 37 of file SBFrameList.cpp.
References m_opaque_sp.
Member Function Documentation
Clear()
void SBFrameList::Clear ()
Clear all frames from this list.
Definition at line 81 of file SBFrameList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBFrameList().
GetDescription()
bool SBFrameList::GetDescription (lldb::SBStream & description) const
Get a description of this frame list.
Parameters
[in] description The stream to write the description to.
Returns
True if the description was successfully written.
Definition at line 88 of file SBFrameList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBStream::ref().
Referenced by ~SBFrameList().
GetFrameAtIndex()
SBFrame SBFrameList::GetFrameAtIndex (uint32_t idx) const
Returns the frame at the given index.
Parameters
[in] idx The index of the frame to retrieve (0-based).
Returns
An SBFrame object for the frame at the specified index. Returns an invalid SBFrame if idx is out of range.
Definition at line 63 of file SBFrameList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBFrame::SetFrameSP().
Referenced by ~SBFrameList().
GetSize()
uint32_t SBFrameList::GetSize () const
Returns the number of frames in the list.
Definition at line 55 of file SBFrameList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by ~SBFrameList().
GetThread()
SBThread SBFrameList::GetThread () const
Get the thread associated with this frame list.
Returns
An SBThread object representing the thread.
Definition at line 72 of file SBFrameList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, SBThread, and lldb::SBThread::SetThread().
Referenced by ~SBFrameList().
IsValid()
bool SBFrameList::IsValid () const
Definition at line 50 of file SBFrameList.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by ~SBFrameList().
operator bool()
SBFrameList::operator bool () const explicit
Definition at line 44 of file SBFrameList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator=()
const SBFrameList & SBFrameList::operator= (const lldb::SBFrameList & rhs)
Definition at line 29 of file SBFrameList.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBFrameList().
Referenced by ~SBFrameList().
SetFrameList()
void SBFrameList::SetFrameList (const lldb::StackFrameListSP & frame_list_sp) private
Definition at line 40 of file SBFrameList.cpp.
References m_opaque_sp.
Referenced by lldb::SBThread::GetFrames(), and lldb_private::ScriptInterpreter.
Friends And Related Symbol Documentation
lldb_private::lua::SWIGBridge
friend class lldb_private::lua::SWIGBridge friend
Definition at line 80 of file SBFrameList.h.
lldb_private::python::SWIGBridge
friend class lldb_private::python::SWIGBridge friend
Definition at line 79 of file SBFrameList.h.
lldb_private::ScriptInterpreter
friend class lldb_private::ScriptInterpreter friend
Definition at line 81 of file SBFrameList.h.
References SBFrameList(), and SetFrameList().
SBThread
friend class SBThread friend
Definition at line 77 of file SBFrameList.h.
References SBThread.
Referenced by GetThread(), and SBThread.
Member Data Documentation
m_opaque_sp
lldb::StackFrameListSP lldb::SBFrameList::m_opaque_sp private
Definition at line 91 of file SBFrameList.h.
Referenced by Clear(), GetDescription(), GetFrameAtIndex(), lldb_private::ScriptInterpreter::GetOpaqueTypeFromSBFrameList(), GetSize(), GetThread(), operator bool(), operator=(), SBFrameList(), SBFrameList(), SBFrameList(), and SetFrameList().
The documentation for this class was generated from the following files:
SBFrameList.h
SBFrameList.cpp