LLDB: lldb_private::python::SWIGBridge Class Reference
lldb_private::python::SWIGBridge Class Reference
#include <SWIGPythonBridge.h>
Static Public Member Functions
static PythonObject ToSWIGWrapper (std::unique_ptr< lldb::SBValue > value_sb)
static PythonObject ToSWIGWrapper (std::unique_ptr< lldb::SBCommandReturnObject > result_up)
static PythonObject ToSWIGWrapper (lldb::ValueObjectSP value_sp)
static PythonObject ToSWIGWrapper (lldb::TargetSP target_sp)
static PythonObject ToSWIGWrapper (lldb::ProcessSP process_sp)
static PythonObject ToSWIGWrapper (lldb::ModuleSP module_sp)
static PythonObject ToSWIGWrapper (lldb::ThreadPlanSP thread_plan_sp)
static PythonObject ToSWIGWrapper (lldb::BreakpointSP breakpoint_sp)
static PythonObject ToSWIGWrapper (Status &&status)
static PythonObject ToSWIGWrapper (const StructuredDataImpl &data_impl)
static PythonObject ToSWIGWrapper (lldb::ThreadSP thread_sp)
static PythonObject ToSWIGWrapper (lldb::StackFrameSP frame_sp)
static PythonObject ToSWIGWrapper (lldb::StackFrameListSP frames_sp)
static PythonObject ToSWIGWrapper (lldb::DebuggerSP debugger_sp)
static PythonObject ToSWIGWrapper (lldb::WatchpointSP watchpoint_sp)
static PythonObject ToSWIGWrapper (lldb::BreakpointLocationSP bp_loc_sp)
static PythonObject ToSWIGWrapper (lldb::TypeImplSP type_impl_sp)
static PythonObject ToSWIGWrapper (lldb::ExecutionContextRefSP ctx_sp)
static PythonObject ToSWIGWrapper (const TypeSummaryOptions &summary_options)
static PythonObject ToSWIGWrapper (const SymbolContext &sym_ctx)
static PythonObject ToSWIGWrapper (const Stream *stream)
static PythonObject ToSWIGWrapper (std::shared_ptr< lldb::SBStream > stream_sb)
static PythonObject ToSWIGWrapper (Event *event)
static PythonObject ToSWIGWrapper (lldb::ProcessAttachInfoSP attach_info_sp)
static PythonObject ToSWIGWrapper (lldb::ProcessLaunchInfoSP launch_info_sp)
static PythonObject ToSWIGWrapper (lldb::DataExtractorSP data_extractor_sp)
static PythonObject ToSWIGWrapper (lldb::DescriptionLevel level)
static PythonObject ToSWIGWrapper (std::unique_ptr< lldb::SBStructuredData > data_sb)
static PythonObject ToSWIGWrapper (std::unique_ptr< lldb::SBFileSpec > file_spec_sb)
static PythonObject ToSWIGWrapper (std::unique_ptr< lldb::SBModuleSpec > module_spec_sb)
static python::ScopedPythonObject< lldb::SBCommandReturnObject > ToSWIGWrapper (CommandReturnObject &cmd_retobj)
static llvm::Expected< bool > LLDBSwigPythonBreakpointCallbackFunction (const char *python_function_name, const char *session_dictionary_name, const lldb::StackFrameSP &sb_frame, const lldb::BreakpointLocationSP &sb_bp_loc, const lldb_private::StructuredDataImpl &args_impl)
static bool LLDBSwigPythonWatchpointCallbackFunction (const char *python_function_name, const char *session_dictionary_name, const lldb::StackFrameSP &sb_frame, const lldb::WatchpointSP &sb_wp)
static bool LLDBSwigPythonFormatterCallbackFunction (const char *python_function_name, const char *session_dictionary_name, lldb::TypeImplSP type_impl_sp)
static bool LLDBSwigPythonCallTypeScript (const char *python_function_name, const void *session_dictionary, const lldb::ValueObjectSP &valobj_sp, void **pyfunct_wrapper, const lldb::TypeSummaryOptionsSP &options_sp, std::string &retval)
static python::PythonObject LLDBSwigPythonCreateSyntheticProvider (const char *python_class_name, const char *session_dictionary_name, const lldb::ValueObjectSP &valobj_sp)
static python::PythonObject LLDBSwigPythonCreateCommandObject (const char *python_class_name, const char *session_dictionary_name, lldb::DebuggerSP debugger_sp)
static size_t LLDBSwigPython_CalculateNumChildren (PyObject *implementor, uint32_t max)
static PyObject * LLDBSwigPython_GetChildAtIndex (PyObject *implementor, uint32_t idx)
static uint32_t LLDBSwigPython_GetIndexOfChildWithName (PyObject *implementor, const char *child_name)
static lldb::ValueObjectSP LLDBSWIGPython_GetValueObjectSPFromSBValue (void *data)
static bool LLDBSwigPython_UpdateSynthProviderInstance (PyObject *implementor)
static bool LLDBSwigPython_MightHaveChildrenSynthProviderInstance (PyObject *implementor)
static PyObject * LLDBSwigPython_GetValueSynthProviderInstance (PyObject *implementor)
static bool LLDBSwigPythonCallCommand (const char *python_function_name, const char *session_dictionary_name, lldb::DebuggerSP debugger, const char *args, lldb_private::CommandReturnObject &cmd_retobj, lldb::ExecutionContextRefSP exe_ctx_ref_sp)
static bool LLDBSwigPythonCallCommandObject (PyObject *implementor, lldb::DebuggerSP debugger, const char *args, lldb_private::CommandReturnObject &cmd_retobj, lldb::ExecutionContextRefSP exe_ctx_ref_sp)
static bool LLDBSwigPythonCallParsedCommandObject (PyObject *implementor, lldb::DebuggerSP debugger, StructuredDataImpl &args_impl, lldb_private::CommandReturnObject &cmd_retobj, lldb::ExecutionContextRefSP exe_ctx_ref_sp)
static std::optional< std::string > LLDBSwigPythonGetRepeatCommandForScriptedCommand (PyObject *implementor, std::string &command)
static StructuredData::DictionarySP LLDBSwigPythonHandleArgumentCompletionForScriptedCommand (PyObject *implementor, std::vector< llvm::StringRef > &args_impl, size_t args_pos, size_t pos_in_arg)
static StructuredData::DictionarySP LLDBSwigPythonHandleOptionArgumentCompletionForScriptedCommand (PyObject *implementor, llvm::StringRef &long_option, size_t pos_in_arg)
static bool LLDBSwigPythonCallModuleInit (const char *python_module_name, const char *session_dictionary_name, lldb::DebuggerSP debugger)
static bool LLDBSwigPythonCallModuleNewTarget (const char *python_module_name, const char *session_dictionary_name, lldb::TargetSP target)
static python::PythonObject LLDBSWIGPythonCreateOSPlugin (const char *python_class_name, const char *session_dictionary_name, const lldb::ProcessSP &process_sp)
static python::PythonObject LLDBSWIGPython_CreateFrameRecognizer (const char *python_class_name, const char *session_dictionary_name)
static PyObject * LLDBSwigPython_GetRecognizedArguments (PyObject *implementor, const lldb::StackFrameSP &frame_sp)
static bool LLDBSwigPython_ShouldHide (PyObject *implementor, const lldb::StackFrameSP &frame_sp)
static bool LLDBSWIGPythonRunScriptKeywordProcess (const char *python_function_name, const char *session_dictionary_name, const lldb::ProcessSP &process, std::string &output)
static std::optional< std::string > LLDBSWIGPythonRunScriptKeywordThread (const char *python_function_name, const char *session_dictionary_name, lldb::ThreadSP thread)
static bool LLDBSWIGPythonRunScriptKeywordTarget (const char *python_function_name, const char *session_dictionary_name, const lldb::TargetSP &target, std::string &output)
static std::optional< std::string > LLDBSWIGPythonRunScriptKeywordFrame (const char *python_function_name, const char *session_dictionary_name, lldb::StackFrameSP frame)
static bool LLDBSWIGPythonRunScriptKeywordValue (const char *python_function_name, const char *session_dictionary_name, const lldb::ValueObjectSP &value, std::string &output)
static void * LLDBSWIGPython_GetDynamicSetting (void *module, const char *setting, const lldb::TargetSP &target_sp)
Detailed Description
Definition at line 77 of file SWIGPythonBridge.h.
Member Function Documentation
LLDBSwigPython_CalculateNumChildren()
size_t lldb_private::python::SWIGBridge::LLDBSwigPython_CalculateNumChildren (PyObject * implementor, uint32_t max) static
LLDBSWIGPython_CreateFrameRecognizer()
python::PythonObject lldb_private::python::SWIGBridge::LLDBSWIGPython_CreateFrameRecognizer (const char * python_class_name, const char * session_dictionary_name) static
LLDBSwigPython_GetChildAtIndex()
PyObject * lldb_private::python::SWIGBridge::LLDBSwigPython_GetChildAtIndex (PyObject * implementor, uint32_t idx) static
LLDBSWIGPython_GetDynamicSetting()
void * lldb_private::python::SWIGBridge::LLDBSWIGPython_GetDynamicSetting (void * module, const char * setting, const lldb::TargetSP & target_sp) static
LLDBSwigPython_GetIndexOfChildWithName()
uint32_t lldb_private::python::SWIGBridge::LLDBSwigPython_GetIndexOfChildWithName (PyObject * implementor, const char * child_name) static
LLDBSwigPython_GetRecognizedArguments()
PyObject * lldb_private::python::SWIGBridge::LLDBSwigPython_GetRecognizedArguments (PyObject * implementor, const lldb::StackFrameSP & frame_sp) static
LLDBSWIGPython_GetValueObjectSPFromSBValue()
lldb::ValueObjectSP lldb_private::python::SWIGBridge::LLDBSWIGPython_GetValueObjectSPFromSBValue (void * data) static
LLDBSwigPython_GetValueSynthProviderInstance()
PyObject * lldb_private::python::SWIGBridge::LLDBSwigPython_GetValueSynthProviderInstance (PyObject * implementor) static
LLDBSwigPython_MightHaveChildrenSynthProviderInstance()
bool lldb_private::python::SWIGBridge::LLDBSwigPython_MightHaveChildrenSynthProviderInstance (PyObject * implementor) static
LLDBSwigPython_ShouldHide()
bool lldb_private::python::SWIGBridge::LLDBSwigPython_ShouldHide (PyObject * implementor, const lldb::StackFrameSP & frame_sp) static
LLDBSwigPython_UpdateSynthProviderInstance()
bool lldb_private::python::SWIGBridge::LLDBSwigPython_UpdateSynthProviderInstance (PyObject * implementor) static
LLDBSwigPythonBreakpointCallbackFunction()
llvm::Expected< bool > lldb_private::python::SWIGBridge::LLDBSwigPythonBreakpointCallbackFunction (const char * python_function_name, const char * session_dictionary_name, const lldb::StackFrameSP & sb_frame, const lldb::BreakpointLocationSP & sb_bp_loc, const lldb_private::StructuredDataImpl & args_impl) static
LLDBSwigPythonCallCommand()
bool lldb_private::python::SWIGBridge::LLDBSwigPythonCallCommand (const char * python_function_name, const char * session_dictionary_name, lldb::DebuggerSP debugger, const char * args, lldb_private::CommandReturnObject & cmd_retobj, lldb::ExecutionContextRefSP exe_ctx_ref_sp) static
LLDBSwigPythonCallCommandObject()
bool lldb_private::python::SWIGBridge::LLDBSwigPythonCallCommandObject (PyObject * implementor, lldb::DebuggerSP debugger, const char * args, lldb_private::CommandReturnObject & cmd_retobj, lldb::ExecutionContextRefSP exe_ctx_ref_sp) static
LLDBSwigPythonCallModuleInit()
bool lldb_private::python::SWIGBridge::LLDBSwigPythonCallModuleInit (const char * python_module_name, const char * session_dictionary_name, lldb::DebuggerSP debugger) static
LLDBSwigPythonCallModuleNewTarget()
bool lldb_private::python::SWIGBridge::LLDBSwigPythonCallModuleNewTarget (const char * python_module_name, const char * session_dictionary_name, lldb::TargetSP target) static
LLDBSwigPythonCallParsedCommandObject()
bool lldb_private::python::SWIGBridge::LLDBSwigPythonCallParsedCommandObject (PyObject * implementor, lldb::DebuggerSP debugger, StructuredDataImpl & args_impl, lldb_private::CommandReturnObject & cmd_retobj, lldb::ExecutionContextRefSP exe_ctx_ref_sp) static
LLDBSwigPythonCallTypeScript()
bool lldb_private::python::SWIGBridge::LLDBSwigPythonCallTypeScript (const char * python_function_name, const void * session_dictionary, const lldb::ValueObjectSP & valobj_sp, void ** pyfunct_wrapper, const lldb::TypeSummaryOptionsSP & options_sp, std::string & retval) static
LLDBSwigPythonCreateCommandObject()
python::PythonObject lldb_private::python::SWIGBridge::LLDBSwigPythonCreateCommandObject (const char * python_class_name, const char * session_dictionary_name, lldb::DebuggerSP debugger_sp) static
LLDBSWIGPythonCreateOSPlugin()
python::PythonObject lldb_private::python::SWIGBridge::LLDBSWIGPythonCreateOSPlugin (const char * python_class_name, const char * session_dictionary_name, const lldb::ProcessSP & process_sp) static
LLDBSwigPythonCreateSyntheticProvider()
python::PythonObject lldb_private::python::SWIGBridge::LLDBSwigPythonCreateSyntheticProvider (const char * python_class_name, const char * session_dictionary_name, const lldb::ValueObjectSP & valobj_sp) static
LLDBSwigPythonFormatterCallbackFunction()
bool lldb_private::python::SWIGBridge::LLDBSwigPythonFormatterCallbackFunction (const char * python_function_name, const char * session_dictionary_name, lldb::TypeImplSP type_impl_sp) static
LLDBSwigPythonGetRepeatCommandForScriptedCommand()
std::optional< std::string > lldb_private::python::SWIGBridge::LLDBSwigPythonGetRepeatCommandForScriptedCommand (PyObject * implementor, std::string & command) static
LLDBSwigPythonHandleArgumentCompletionForScriptedCommand()
StructuredData::DictionarySP lldb_private::python::SWIGBridge::LLDBSwigPythonHandleArgumentCompletionForScriptedCommand (PyObject * implementor, std::vector< llvm::StringRef > & args_impl, size_t args_pos, size_t pos_in_arg) static
LLDBSwigPythonHandleOptionArgumentCompletionForScriptedCommand()
StructuredData::DictionarySP lldb_private::python::SWIGBridge::LLDBSwigPythonHandleOptionArgumentCompletionForScriptedCommand (PyObject * implementor, llvm::StringRef & long_option, size_t pos_in_arg) static
LLDBSWIGPythonRunScriptKeywordFrame()
std::optional< std::string > lldb_private::python::SWIGBridge::LLDBSWIGPythonRunScriptKeywordFrame (const char * python_function_name, const char * session_dictionary_name, lldb::StackFrameSP frame) static
LLDBSWIGPythonRunScriptKeywordProcess()
bool lldb_private::python::SWIGBridge::LLDBSWIGPythonRunScriptKeywordProcess (const char * python_function_name, const char * session_dictionary_name, const lldb::ProcessSP & process, std::string & output) static
LLDBSWIGPythonRunScriptKeywordTarget()
bool lldb_private::python::SWIGBridge::LLDBSWIGPythonRunScriptKeywordTarget (const char * python_function_name, const char * session_dictionary_name, const lldb::TargetSP & target, std::string & output) static
LLDBSWIGPythonRunScriptKeywordThread()
std::optional< std::string > lldb_private::python::SWIGBridge::LLDBSWIGPythonRunScriptKeywordThread (const char * python_function_name, const char * session_dictionary_name, lldb::ThreadSP thread) static
LLDBSWIGPythonRunScriptKeywordValue()
bool lldb_private::python::SWIGBridge::LLDBSWIGPythonRunScriptKeywordValue (const char * python_function_name, const char * session_dictionary_name, const lldb::ValueObjectSP & value, std::string & output) static
LLDBSwigPythonWatchpointCallbackFunction()
bool lldb_private::python::SWIGBridge::LLDBSwigPythonWatchpointCallbackFunction (const char * python_function_name, const char * session_dictionary_name, const lldb::StackFrameSP & sb_frame, const lldb::WatchpointSP & sb_wp) static
ToSWIGWrapper() [1/31]
python::ScopedPythonObject< lldb::SBCommandReturnObject > lldb_private::python::SWIGBridge::ToSWIGWrapper (CommandReturnObject & cmd_retobj) static
ToSWIGWrapper() [2/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (const Stream * stream) static
ToSWIGWrapper() [3/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (const StructuredDataImpl & data_impl) static
ToSWIGWrapper() [4/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (const SymbolContext & sym_ctx) static
ToSWIGWrapper() [5/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (const TypeSummaryOptions & summary_options) static
ToSWIGWrapper() [6/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (Event * event) static
ToSWIGWrapper() [7/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (lldb::BreakpointLocationSP bp_loc_sp) static
ToSWIGWrapper() [8/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (lldb::BreakpointSP breakpoint_sp) static
ToSWIGWrapper() [9/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (lldb::DataExtractorSP data_extractor_sp) static
ToSWIGWrapper() [10/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (lldb::DebuggerSP debugger_sp) static
ToSWIGWrapper() [11/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (lldb::DescriptionLevel level) static
ToSWIGWrapper() [12/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (lldb::ExecutionContextRefSP ctx_sp) static
ToSWIGWrapper() [13/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (lldb::ModuleSP module_sp) static
ToSWIGWrapper() [14/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (lldb::ProcessAttachInfoSP attach_info_sp) static
ToSWIGWrapper() [15/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (lldb::ProcessLaunchInfoSP launch_info_sp) static
ToSWIGWrapper() [16/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (lldb::ProcessSP process_sp) static
ToSWIGWrapper() [17/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (lldb::StackFrameListSP frames_sp) static
ToSWIGWrapper() [18/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (lldb::StackFrameSP frame_sp) static
ToSWIGWrapper() [19/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (lldb::TargetSP target_sp) static
ToSWIGWrapper() [20/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (lldb::ThreadPlanSP thread_plan_sp) static
ToSWIGWrapper() [21/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (lldb::ThreadSP thread_sp) static
ToSWIGWrapper() [22/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (lldb::TypeImplSP type_impl_sp) static
ToSWIGWrapper() [23/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (lldb::ValueObjectSP value_sp) static
ToSWIGWrapper() [24/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (lldb::WatchpointSP watchpoint_sp) static
ToSWIGWrapper() [25/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (Status && status) static
ToSWIGWrapper() [26/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (std::shared_ptr< lldb::SBStream > stream_sb) static
ToSWIGWrapper() [27/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (std::unique_ptr< lldb::SBCommandReturnObject > result_up) static
ToSWIGWrapper() [28/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (std::unique_ptr< lldb::SBFileSpec > file_spec_sb) static
ToSWIGWrapper() [29/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (std::unique_ptr< lldb::SBModuleSpec > module_spec_sb) static
ToSWIGWrapper() [30/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (std::unique_ptr< lldb::SBStructuredData > data_sb) static
ToSWIGWrapper() [31/31]
PythonObject lldb_private::python::SWIGBridge::ToSWIGWrapper (std::unique_ptr< lldb::SBValue > value_sb) static
Referenced by lldb_private::ScriptedPythonInterface::Transform(), lldb_private::ScriptedPythonInterface::Transform(), lldb_private::ScriptedPythonInterface::Transform(), lldb_private::ScriptedPythonInterface::Transform(), lldb_private::ScriptedPythonInterface::Transform(), lldb_private::ScriptedPythonInterface::Transform(), lldb_private::ScriptedPythonInterface::Transform(), lldb_private::ScriptedPythonInterface::Transform(), lldb_private::ScriptedPythonInterface::Transform(), lldb_private::ScriptedPythonInterface::Transform(), lldb_private::ScriptedPythonInterface::Transform(), lldb_private::ScriptedPythonInterface::Transform(), lldb_private::ScriptedPythonInterface::Transform(), lldb_private::ScriptedPythonInterface::Transform(), lldb_private::ScriptedPythonInterface::Transform(), lldb_private::ScriptedPythonInterface::Transform(), lldb_private::ScriptedPythonInterface::Transform(), lldb_private::ScriptedPythonInterface::Transform(), lldb_private::ScriptedPythonInterface::Transform(), and lldb_private::ScriptedPythonInterface::Transform().
The documentation for this class was generated from the following file:
SWIGPythonBridge.h