LLDB: lldb::SBCommand Class Reference
lldb::SBCommand Class Reference
#include <SBCommandInterpreter.h>
Public Member Functions
SBCommand ()
operator bool () const
bool IsValid ()
const char * GetName ()
const char * GetHelp ()
const char * GetHelpLong ()
void SetHelp (const char *)
void SetHelpLong (const char *)
uint32_t GetFlags ()
void SetFlags (uint32_t flags)
lldb::SBCommand AddMultiwordCommand (const char *name, const char *help=nullptr)
lldb::SBCommand AddCommand (const char *name, lldb::SBCommandPluginInterface *impl, const char *help=nullptr)
Add a new subcommand to the lldb::SBCommand.
lldb::SBCommand AddCommand (const char *name, lldb::SBCommandPluginInterface *impl, const char *help, const char *syntax)
Add a new subcommand to the lldb::SBCommand.
lldb::SBCommand AddCommand (const char *name, lldb::SBCommandPluginInterface *impl, const char *help, const char *syntax, const char *auto_repeat_command)
Add a new subcommand to the lldb::SBCommand.
Private Member Functions
SBCommand (lldb::CommandObjectSP cmd_sp)
Private Attributes
lldb::CommandObjectSP m_opaque_sp
Friends
class SBDebugger
class SBCommandInterpreter
Detailed Description
Definition at line 364 of file SBCommandInterpreter.h.
Constructor & Destructor Documentation
SBCommand() [1/2]
SBCommand::SBCommand ()
Definition at line 647 of file SBCommandInterpreter.cpp.
References LLDB_INSTRUMENT_VA.
SBCommand() [2/2]
SBCommand::SBCommand (lldb::CommandObjectSP cmd_sp) private
Definition at line 649 of file SBCommandInterpreter.cpp.
References m_opaque_sp.
Member Function Documentation
AddCommand() [1/3]
lldb::SBCommand SBCommand::AddCommand (const char * name, lldb::SBCommandPluginInterface * impl, const char * help, const char * syntax)
Add a new subcommand to the lldb::SBCommand.
The new command won't support autorepeat. If you need this functionality, use the override of this function that accepts the auto_repeat_command parameter.
Parameters
[in] name The name of the command.
[in] impl The handler of this command.
[in] help The general description to show as part of the help message of this command.
[in] syntax The syntax to show as part of the help message of this command. This could include a description of the different arguments and flags this command accepts.
Returns
A lldb::SBCommand representing the newly created command.
Definition at line 721 of file SBCommandInterpreter.cpp.
References AddCommand(), and LLDB_INSTRUMENT_VA.
AddCommand() [2/3]
lldb::SBCommand SBCommand::AddCommand (const char * name, lldb::SBCommandPluginInterface * impl, const char * help, const char * syntax, const char * auto_repeat_command)
Add a new subcommand to the lldb::SBCommand.
The new command won't support autorepeat. If you need this functionality, use the override of this function that accepts the auto_repeat_command parameter.
Parameters
[in] name The name of the command.
[in] impl The handler of this command.
[in] help The general description to show as part of the help message of this command.
[in] syntax The syntax to show as part of the help message of this command. This could include a description of the different arguments and flags this command accepts.
[in] auto_repeat_command Autorepeating is triggered when the user presses Enter successively after executing a command. If nullptr is provided, the previous exact command will be repeated. If "" is provided, autorepeating is disabled. Otherwise, the provided string is used as a repeat command.
Returns
A lldb::SBCommand representing the newly created command.
Definition at line 728 of file SBCommandInterpreter.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBCommand.
AddCommand() [3/3]
lldb::SBCommand SBCommand::AddCommand (const char * name, lldb::SBCommandPluginInterface * impl, const char * help = nullptr)
Add a new subcommand to the lldb::SBCommand.
The new command won't support autorepeat. If you need this functionality, use the override of this function that accepts the auto_repeat parameter.
Parameters
[in] name The name of the command.
[in] impl The handler of this command.
[in] help The general description to show as part of the help message of this command.
Returns
A lldb::SBCommand representing the newly created command.
Definition at line 713 of file SBCommandInterpreter.cpp.
References AddCommand(), and LLDB_INSTRUMENT_VA.
Referenced by AddCommand(), and AddCommand().
AddMultiwordCommand()
lldb::SBCommand SBCommand::AddMultiwordCommand (const char * name, const char * help = nullptr)
Definition at line 696 of file SBCommandInterpreter.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, lldb::SBCommand, and lldb_private::CommandObjectMultiword::SetRemovable().
GetFlags()
uint32_t SBCommand::GetFlags ()
Definition at line 747 of file SBCommandInterpreter.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetHelp()
const char * SBCommand::GetHelp ()
Definition at line 668 of file SBCommandInterpreter.cpp.
References lldb_private::ConstString::AsCString(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetHelpLong()
const char * SBCommand::GetHelpLong ()
Definition at line 675 of file SBCommandInterpreter.cpp.
References lldb_private::ConstString::AsCString(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetName()
const char * SBCommand::GetName ()
Definition at line 661 of file SBCommandInterpreter.cpp.
References lldb_private::ConstString::AsCString(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
IsValid()
bool SBCommand::IsValid ()
Definition at line 651 of file SBCommandInterpreter.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by AddCommand(), AddMultiwordCommand(), GetFlags(), GetHelp(), GetHelpLong(), GetName(), SetFlags(), SetHelp(), and SetHelpLong().
operator bool()
SBCommand::operator bool () const explicit
Definition at line 655 of file SBCommandInterpreter.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
SetFlags()
void SBCommand::SetFlags (uint32_t flags)
Definition at line 753 of file SBCommandInterpreter.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
SetHelp()
void SBCommand::SetHelp (const char * help)
Definition at line 682 of file SBCommandInterpreter.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
SetHelpLong()
void SBCommand::SetHelpLong (const char * help)
Definition at line 689 of file SBCommandInterpreter.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Friends And Related Symbol Documentation
SBCommandInterpreter
friend class SBCommandInterpreter friend
Definition at line 475 of file SBCommandInterpreter.h.
References SBCommandInterpreter.
Referenced by SBCommandInterpreter.
SBDebugger
friend class SBDebugger friend
Definition at line 474 of file SBCommandInterpreter.h.
References SBDebugger.
Referenced by SBDebugger.
Member Data Documentation
m_opaque_sp
lldb::CommandObjectSP lldb::SBCommand::m_opaque_sp private
Definition at line 479 of file SBCommandInterpreter.h.
Referenced by AddCommand(), AddMultiwordCommand(), GetFlags(), GetHelp(), GetHelpLong(), GetName(), operator bool(), SBCommand(), SetFlags(), SetHelp(), and SetHelpLong().
The documentation for this class was generated from the following files:
SBCommandInterpreter.h
SBCommandInterpreter.cpp