LLDB: lldb_private::minidump::LinuxProcStatus Class Reference
lldb_private::minidump::LinuxProcStatus Class Reference
#include <MinidumpTypes.h>
Public Member Functions
lldb::pid_t GetPid () const
Static Public Member Functions
static std::optional< LinuxProcStatus > Parse (llvm::ArrayRef< uint8_t > &data)
Public Attributes
llvm::StringRef proc_status
lldb::pid_t pid
Private Member Functions
LinuxProcStatus ()=default
Detailed Description
Definition at line 86 of file MinidumpTypes.h.
Constructor & Destructor Documentation
LinuxProcStatus()
lldb_private::minidump::LinuxProcStatus::LinuxProcStatus () private default
Referenced by Parse().
Member Function Documentation
GetPid()
lldb::pid_t LinuxProcStatus::GetPid () const
Definition at line 59 of file MinidumpTypes.cpp.
References pid.
Parse()
std::optional< LinuxProcStatus > LinuxProcStatus::Parse (llvm::ArrayRef< uint8_t > & data) static
Definition at line 39 of file MinidumpTypes.cpp.
References LinuxProcStatus(), pid, and proc_status.
Referenced by lldb_private::minidump::MinidumpParser::GetLinuxProcStatus().
Member Data Documentation
pid
lldb::pid_t lldb_private::minidump::LinuxProcStatus::pid
Definition at line 89 of file MinidumpTypes.h.
Referenced by GetPid(), and Parse().
proc_status
llvm::StringRef lldb_private::minidump::LinuxProcStatus::proc_status
Definition at line 88 of file MinidumpTypes.h.
Referenced by Parse().
The documentation for this class was generated from the following files:
MinidumpTypes.h
MinidumpTypes.cpp