LLDB: ABISysV_i386 Class Reference
ABISysV_i386 Class Reference
#include <ABISysV_i386.h>
Public Member Functions
~ABISysV_i386 () override=default
size_t GetRedZoneSize () const override
bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override
bool GetArgumentValues (lldb_private::Thread &thread, lldb_private::ValueList &values) const override
lldb_private::Status SetReturnValueObject (lldb::StackFrameSP &frame_sp, lldb::ValueObjectSP &new_value) override
lldb::ValueObjectSP GetReturnValueObjectImpl (lldb_private::Thread &thread, lldb_private::CompilerType &type) const override
lldb::UnwindPlanSP CreateFunctionEntryUnwindPlan () override
lldb::UnwindPlanSP CreateDefaultUnwindPlan () override
bool RegisterIsVolatile (const lldb_private::RegisterInfo *reg_info) override
bool CallFrameAddressIsValid (lldb::addr_t cfa) override
bool CodeAddressIsValid (lldb::addr_t pc) override
llvm::StringRef GetPluginName () override
Public Member Functions inherited from ABIX86_i386
uint32_t GetGenericNum (llvm::StringRef name) override
Return the generic number of the given register.
Public Member Functions inherited from lldb_private::MCBasedABI
void AugmentRegisterInfo (std::vector< DynamicRegisterInfo::Register > &regs) override
Public Member Functions inherited from lldb_private::ABI
~ABI () override
virtual bool PrepareTrivialCall (lldb_private::Thread &thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::Type &prototype, llvm::ArrayRef< CallArgument > args) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, CompilerType &type, bool persistent=true) const
lldb::ValueObjectSP GetReturnValueObject (Thread &thread, llvm::Type &type, bool persistent=true) const
virtual bool GetFallbackRegisterLocation (const RegisterInfo *reg_info, UnwindPlan::Row::AbstractRegisterLocation &unwind_regloc)
virtual lldb::addr_t FixAnyAddress (lldb::addr_t pc)
Use this method when you do not know, or do not care what kind of address you are fixing.
llvm::MCRegisterInfo & GetMCRegisterInfo ()
virtual bool GetPointerReturnRegister (const char *&name)
virtual uint64_t GetStackFrameSize ()
virtual lldb::addr_t FixCodeAddress (lldb::addr_t pc)
Some targets might use bits in a code address to indicate a mode switch.
virtual lldb::addr_t FixDataAddress (lldb::addr_t pc)
Public Member Functions inherited from lldb_private::PluginInterface
PluginInterface ()=default
virtual ~PluginInterface ()=default
PluginInterface (const PluginInterface &)=delete
PluginInterface & operator= (const PluginInterface &)=delete
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static lldb::ABISP CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec &arch)
static llvm::StringRef GetPluginNameStatic ()
Static Public Member Functions inherited from ABIX86
static void Initialize ()
static void Terminate ()
Static Public Member Functions inherited from lldb_private::MCBasedABI
static void MapRegisterName (std::string &reg, llvm::StringRef from_prefix, llvm::StringRef to_prefix)
If the register name is of the form "<from_prefix>[<number>]" then change the name to "<to_prefix>[<number>]".
Static Public Member Functions inherited from lldb_private::ABI
static lldb::ABISP FindPlugin (lldb::ProcessSP process_sp, const ArchSpec &arch)
Protected Member Functions
lldb::ValueObjectSP GetReturnValueObjectSimple (lldb_private::Thread &thread, lldb_private::CompilerType &ast_type) const
bool RegisterIsCalleeSaved (const lldb_private::RegisterInfo *reg_info)
Protected Member Functions inherited from ABIX86
void AugmentRegisterInfo (std::vector< lldb_private::DynamicRegisterInfo::Register > &regs) override
Protected Member Functions inherited from lldb_private::MCBasedABI
virtual std::pair< uint32_t, uint32_t > GetEHAndDWARFNums (llvm::StringRef reg)
Return eh_frame and dwarf numbers for the given register.
virtual std::string GetMCName (std::string reg)
For the given (capitalized) lldb register name, return the name of this register in the MCRegisterInfo struct.
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Protected Member Functions inherited from lldb_private::ABI
virtual lldb::ValueObjectSP GetReturnValueObjectImpl (Thread &thread, llvm::Type &ir_type) const
lldb::ProcessSP GetProcessSP () const
Request to get a Process shared pointer.
ABI (lldb::ProcessSP process_sp, std::unique_ptr< llvm::MCRegisterInfo > info_up)
Additional Inherited Members
Static Protected Member Functions inherited from lldb_private::ABI
static std::unique_ptr< llvm::MCRegisterInfo > MakeMCRegisterInfo (const ArchSpec &arch)
Utility function to construct a MCRegisterInfo using the ArchSpec triple.
Protected Attributes inherited from lldb_private::ABI
lldb::ProcessWP m_process_wp
std::unique_ptr< llvm::MCRegisterInfo > m_mc_register_info_up
Detailed Description
Definition at line 15 of file ABISysV_i386.h.
Constructor & Destructor Documentation
~ABISysV_i386()
ABISysV_i386::~ABISysV_i386 () override default
Member Function Documentation
CallFrameAddressIsValid()
bool ABISysV_i386::CallFrameAddressIsValid (lldb::addr_t cfa) inline override virtual
Implements lldb_private::ABI.
Definition at line 61 of file ABISysV_i386.h.
CodeAddressIsValid()
bool ABISysV_i386::CodeAddressIsValid (lldb::addr_t pc) inline override virtual
Implements lldb_private::ABI.
Definition at line 70 of file ABISysV_i386.h.
References pc, and UINT32_MAX.
CreateDefaultUnwindPlan()
UnwindPlanSP ABISysV_i386::CreateDefaultUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 648 of file ABISysV_i386.cpp.
References dwarf_ebp, dwarf_eip, dwarf_esp, lldb_private::eLazyBoolNo, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), lldb_private::UnwindPlan::Row::SetRegisterLocationToAtCFAPlusOffset(), lldb_private::UnwindPlan::Row::SetRegisterLocationToIsCFAPlusOffset(), and lldb_private::UnwindPlan::Row::SetUnspecifiedRegistersAreUndefined().
CreateFunctionEntryUnwindPlan()
UnwindPlanSP ABISysV_i386::CreateFunctionEntryUnwindPlan () override virtual
Implements lldb_private::ABI.
Definition at line 627 of file ABISysV_i386.cpp.
References dwarf_eip, dwarf_esp, lldb_private::eLazyBoolNo, lldb::eRegisterKindDWARF, lldb_private::UnwindPlan::Row::GetCFAValue(), lldb_private::UnwindPlan::Row::FAValue::SetIsRegisterPlusOffset(), lldb_private::UnwindPlan::Row::SetRegisterLocationToAtCFAPlusOffset(), and lldb_private::UnwindPlan::Row::SetRegisterLocationToIsCFAPlusOffset().
CreateInstance()
ABISP ABISysV_i386::CreateInstance (lldb::ProcessSP process_sp, const lldb_private::ArchSpec & arch) static
Definition at line 74 of file ABISysV_i386.cpp.
References lldb_private::ArchSpec::GetTriple(), and lldb_private::ABI::MakeMCRegisterInfo().
Referenced by Initialize(), and Terminate().
GetArgumentValues()
bool ABISysV_i386::GetArgumentValues (lldb_private::Thread & thread, lldb_private::ValueList & values) const override virtual
Implements lldb_private::ABI.
Definition at line 161 of file ABISysV_i386.cpp.
References lldb_private::CompilerType::GetBitSize(), lldb_private::Value::GetCompilerType(), lldb_private::Value::GetScalar(), lldb_private::ValueList::GetSize(), lldb_private::RegisterContext::GetSP(), lldb_private::ValueList::GetValueAtIndex(), lldb_private::CompilerType::IsIntegerOrEnumerationType(), lldb_private::CompilerType::IsPointerType(), ReadIntegerArgument(), and sp.
GetPluginName()
llvm::StringRef ABISysV_i386::GetPluginName () inline override virtual
Implements lldb_private::PluginInterface.
Definition at line 87 of file ABISysV_i386.h.
References GetPluginNameStatic().
GetPluginNameStatic()
llvm::StringRef ABISysV_i386::GetPluginNameStatic () inline static
Definition at line 85 of file ABISysV_i386.h.
Referenced by GetPluginName(), and Initialize().
GetRedZoneSize()
size_t ABISysV_i386::GetRedZoneSize () const inline override virtual
Implements lldb_private::ABI.
Definition at line 19 of file ABISysV_i386.h.
GetReturnValueObjectImpl()
ValueObjectSP ABISysV_i386::GetReturnValueObjectImpl (lldb_private::Thread & thread, lldb_private::CompilerType & type) const override virtual
Implements lldb_private::ABI.
Definition at line 594 of file ABISysV_i386.cpp.
References lldb_private::ValueObjectMemory::Create(), lldb::eRegisterKindLLDB, GetReturnValueObjectSimple(), and lldb_private::CompilerType::IsAggregateType().
GetReturnValueObjectSimple()
ValueObjectSP ABISysV_i386::GetReturnValueObjectSimple (lldb_private::Thread & thread, lldb_private::CompilerType & ast_type) const protected
Definition at line 357 of file ABISysV_i386.cpp.
References lldb_private::RegisterInfo::byte_size, lldb_private::ValueObjectConstResult::Create(), lldb_private::ValueObjectMemory::Create(), lldb::eRegisterKindLLDB, error(), lldb_private::RegisterValue::GetAsMemoryData(), lldb_private::CompilerType::GetByteSize(), lldb_private::RegisterValue::GetData(), lldb_private::DataExtractor::GetLongDouble(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::Value::GetScalar(), lldb_private::CompilerType::GetTypeInfo(), lldb_private::RegisterInfo::kinds, lldb_private::RegisterContext::ReadRegister(), lldb_private::Value::Scalar, lldb_private::Value::SetCompilerType(), lldb_private::Value::SetValueType(), and UINT32_MAX.
Referenced by GetReturnValueObjectImpl().
Initialize()
void ABISysV_i386::Initialize () static
Definition at line 712 of file ABISysV_i386.cpp.
References CreateInstance(), GetPluginNameStatic(), and lldb_private::PluginManager::RegisterPlugin().
Referenced by ABIX86::Initialize().
PrepareTrivialCall()
bool ABISysV_i386::PrepareTrivialCall (lldb_private::Thread & thread, lldb::addr_t sp, lldb::addr_t functionAddress, lldb::addr_t returnAddress, llvm::ArrayRef< lldb::addr_t > args) const override virtual
Implements lldb_private::ABI.
Definition at line 84 of file ABISysV_i386.cpp.
References lldb_private::RegisterInfo::byte_size, lldb_private::RegisterContext::ConvertRegisterKindToRegisterNumber(), lldb::eRegisterKindGeneric, error(), lldb_private::RegisterContext::GetRegisterInfoByName(), LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_SP, lldb_private::RegisterValue::SetUInt32(), sp, lldb_private::RegisterContext::WriteRegisterFromUnsigned(), and lldb_private::RegisterContext::WriteRegisterValueToMemory().
RegisterIsCalleeSaved()
bool ABISysV_i386::RegisterIsCalleeSaved (const lldb_private::RegisterInfo * reg_info) protected
Definition at line 675 of file ABISysV_i386.cpp.
References lldb_private::RegisterInfo::name.
Referenced by RegisterIsVolatile().
RegisterIsVolatile()
bool ABISysV_i386::RegisterIsVolatile (const lldb_private::RegisterInfo * reg_info) inline override virtual
Implements lldb_private::ABI.
Definition at line 43 of file ABISysV_i386.h.
References RegisterIsCalleeSaved().
SetReturnValueObject()
Status ABISysV_i386::SetReturnValueObject (lldb::StackFrameSP & frame_sp, lldb::ValueObjectSP & new_value) override virtual
Implements lldb_private::ABI.
Definition at line 201 of file ABISysV_i386.cpp.
References lldb_private::Status::AsCString(), error(), lldb_private::Status::Fail(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataExtractor::GetDouble(), lldb_private::DataExtractor::GetFloat(), lldb_private::DataExtractor::GetLongDouble(), lldb_private::DataExtractor::GetMaxU32(), lldb_private::RegisterContext::GetRegisterInfoByName(), lldb_private::CompilerType::GetTypeInfo(), lldb_private::RegisterValue::SetLongDouble(), lldb_private::RegisterValue::SetUInt32(), lldb_private::RegisterContext::WriteRegister(), and lldb_private::RegisterContext::WriteRegisterFromUnsigned().
Terminate()
void ABISysV_i386::Terminate () static
Definition at line 717 of file ABISysV_i386.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Referenced by ABIX86::Terminate().
The documentation for this class was generated from the following files:
ABISysV_i386.h
ABISysV_i386.cpp