LLDB: lldb_private::TypeSummaryImpl Class Reference
lldb_private::TypeSummaryImpl Class Reference abstract
#include <TypeSummary.h>
Classes
class Flags
Public Types
enum class Kind {
eSummaryString , eScript , eBytecode , eCallback ,
eInternal
}
typedef std::shared_ptr< TypeSummaryImpl > SharedPointer
Public Member Functions
virtual ~TypeSummaryImpl ()=default
Kind GetKind () const
bool Cascades () const
bool SkipsPointers () const
bool SkipsReferences () const
bool NonCacheable () const
virtual bool DoesPrintChildren (ValueObject *valobj) const
virtual bool DoesPrintEmptyAggregates () const
virtual bool DoesPrintValue (ValueObject *valobj) const
bool IsOneLiner () const
virtual bool HideNames (ValueObject *valobj) const
void SetCascades (bool value)
void SetSkipsPointers (bool value)
void SetSkipsReferences (bool value)
virtual void SetDoesPrintChildren (bool value)
virtual void SetDoesPrintValue (bool value)
void SetIsOneLiner (bool value)
virtual void SetHideNames (bool value)
virtual void SetNonCacheable (bool value)
uint32_t GetOptions ()
void SetOptions (uint32_t value)
uint32_t GetPtrMatchDepth ()
void SetPtrMatchDepth (uint32_t value)
virtual bool FormatObject (ValueObject *valobj, std::string &dest, const TypeSummaryOptions &options)=0
virtual std::string GetDescription ()=0
virtual std::string GetName ()=0
Get the name of the Type Summary Provider, either a C++ class, a summary string, or a script function name.
virtual std::string GetSummaryKindName ()
Get the name of the kind of Summary Provider, either c++, summary string, script or python.
uint32_t & GetRevision ()
Protected Member Functions
TypeSummaryImpl (Kind kind, const TypeSummaryImpl::Flags &flags, uint32_t ptr_match_depth=1)
Protected Attributes
uint32_t m_my_revision = 0
Flags m_flags
Private Member Functions
TypeSummaryImpl (const TypeSummaryImpl &)=delete
const TypeSummaryImpl & operator= (const TypeSummaryImpl &)=delete
Private Attributes
Kind m_kind
uint32_t m_ptr_match_depth = 1
Detailed Description
Definition at line 49 of file TypeSummary.h.
Member Typedef Documentation
SharedPointer
typedef std::shared_ptr<TypeSummaryImpl> lldb_private::TypeSummaryImpl::SharedPointer
Definition at line 279 of file TypeSummary.h.
Member Enumeration Documentation
Kind
enum class lldb_private::TypeSummaryImpl::Kind strong
Enumerator
eSummaryString
eScript
eBytecode
eCallback
eInternal
Definition at line 51 of file TypeSummary.h.
Constructor & Destructor Documentation
~TypeSummaryImpl()
virtual lldb_private::TypeSummaryImpl::~TypeSummaryImpl () virtual default
TypeSummaryImpl() [1/2]
TypeSummaryImpl::TypeSummaryImpl (Kind kind, const TypeSummaryImpl::Flags & flags, uint32_t ptr_match_depth = 1) protected
Definition at line 47 of file TypeSummary.cpp.
References m_flags, m_kind, and m_ptr_match_depth.
Referenced by lldb_private::BytecodeSummaryFormat::BytecodeSummaryFormat(), lldb_private::BytecodeSummaryFormat::classof(), lldb_private::CXXFunctionSummaryFormat::classof(), lldb_private::ScriptSummaryFormat::classof(), lldb_private::StringSummaryFormat::classof(), lldb_private::CXXFunctionSummaryFormat::CXXFunctionSummaryFormat(), operator=(), lldb_private::ScriptSummaryFormat::ScriptSummaryFormat(), lldb_private::StringSummaryFormat::StringSummaryFormat(), and TypeSummaryImpl().
TypeSummaryImpl() [2/2]
lldb_private::TypeSummaryImpl::TypeSummaryImpl (const TypeSummaryImpl &) private delete
References TypeSummaryImpl().
Member Function Documentation
Cascades()
bool lldb_private::TypeSummaryImpl::Cascades () const inline
Definition at line 206 of file TypeSummary.h.
References m_flags.
Referenced by lldb_private::BytecodeSummaryFormat::GetDescription(), lldb_private::CXXFunctionSummaryFormat::GetDescription(), lldb_private::ScriptSummaryFormat::GetDescription(), and lldb_private::StringSummaryFormat::GetDescription().
DoesPrintChildren()
virtual bool lldb_private::TypeSummaryImpl::DoesPrintChildren (ValueObject * valobj) const inline virtual
Definition at line 214 of file TypeSummary.h.
References m_flags.
Referenced by lldb_private::BytecodeSummaryFormat::GetDescription(), lldb_private::CXXFunctionSummaryFormat::GetDescription(), lldb_private::ScriptSummaryFormat::GetDescription(), and lldb_private::StringSummaryFormat::GetDescription().
DoesPrintEmptyAggregates()
virtual bool lldb_private::TypeSummaryImpl::DoesPrintEmptyAggregates () const inline virtual
Definition at line 218 of file TypeSummary.h.
References m_flags.
Referenced by lldb_private::ValueObjectPrinter::ShouldExpandEmptyAggregates().
DoesPrintValue()
virtual bool lldb_private::TypeSummaryImpl::DoesPrintValue (ValueObject * valobj) const inline virtual
Definition at line 222 of file TypeSummary.h.
References m_flags.
Referenced by lldb_private::BytecodeSummaryFormat::GetDescription(), lldb_private::CXXFunctionSummaryFormat::GetDescription(), lldb_private::ScriptSummaryFormat::GetDescription(), lldb_private::StringSummaryFormat::GetDescription(), and lldb_private::ValueObjectPrinter::PrintValueAndSummaryIfNeeded().
FormatObject()
virtual bool lldb_private::TypeSummaryImpl::FormatObject (ValueObject * valobj, std::string & dest, const TypeSummaryOptions & options) pure virtual
Implemented in lldb_private::BytecodeSummaryFormat, lldb_private::CXXFunctionSummaryFormat, lldb_private::ScriptSummaryFormat, and lldb_private::StringSummaryFormat.
Referenced by lldb_private::ValueObject::GetSummaryAsCString().
GetDescription()
virtual std::string lldb_private::TypeSummaryImpl::GetDescription () pure virtual
Implemented in lldb_private::BytecodeSummaryFormat, lldb_private::CXXFunctionSummaryFormat, lldb_private::ScriptSummaryFormat, and lldb_private::StringSummaryFormat.
GetKind()
Kind lldb_private::TypeSummaryImpl::GetKind () const inline
Definition at line 55 of file TypeSummary.h.
References m_kind.
GetName()
virtual std::string lldb_private::TypeSummaryImpl::GetName () pure virtual
Get the name of the Type Summary Provider, either a C++ class, a summary string, or a script function name.
Implemented in lldb_private::BytecodeSummaryFormat, lldb_private::CXXFunctionSummaryFormat, lldb_private::ScriptSummaryFormat, and lldb_private::StringSummaryFormat.
Referenced by lldb_private::SummaryStatisticsCache::GetSummaryStatisticsForProvider().
GetOptions()
uint32_t lldb_private::TypeSummaryImpl::GetOptions () inline
Definition at line 252 of file TypeSummary.h.
References m_flags.
GetPtrMatchDepth()
uint32_t lldb_private::TypeSummaryImpl::GetPtrMatchDepth () inline
Definition at line 256 of file TypeSummary.h.
References m_ptr_match_depth.
Referenced by lldb_private::CXXFunctionSummaryFormat::GetDescription(), lldb_private::ScriptSummaryFormat::GetDescription(), and lldb_private::StringSummaryFormat::GetDescription().
GetRevision()
uint32_t & lldb_private::TypeSummaryImpl::GetRevision () inline
Definition at line 277 of file TypeSummary.h.
References m_my_revision.
GetSummaryKindName()
std::string TypeSummaryImpl::GetSummaryKindName () virtual
Get the name of the kind of Summary Provider, either c++, summary string, script or python.
Definition at line 51 of file TypeSummary.cpp.
References eBytecode, eCallback, eInternal, eScript, eSummaryString, and m_kind.
Referenced by lldb_private::SummaryStatisticsCache::GetSummaryStatisticsForProvider().
HideNames()
virtual bool lldb_private::TypeSummaryImpl::HideNames (ValueObject * valobj) const inline virtual
Definition at line 228 of file TypeSummary.h.
References m_flags.
Referenced by lldb_private::StringSummaryFormat::FormatObject(), lldb_private::BytecodeSummaryFormat::GetDescription(), lldb_private::CXXFunctionSummaryFormat::GetDescription(), lldb_private::ScriptSummaryFormat::GetDescription(), and lldb_private::StringSummaryFormat::GetDescription().
IsOneLiner()
bool lldb_private::TypeSummaryImpl::IsOneLiner () const inline
Definition at line 226 of file TypeSummary.h.
References m_flags.
Referenced by lldb_private::StringSummaryFormat::FormatObject(), lldb_private::BytecodeSummaryFormat::GetDescription(), lldb_private::CXXFunctionSummaryFormat::GetDescription(), lldb_private::ScriptSummaryFormat::GetDescription(), and lldb_private::StringSummaryFormat::GetDescription().
NonCacheable()
bool lldb_private::TypeSummaryImpl::NonCacheable () const inline
Definition at line 212 of file TypeSummary.h.
References m_flags.
operator=()
const TypeSummaryImpl & lldb_private::TypeSummaryImpl::operator= (const TypeSummaryImpl &) private delete
References TypeSummaryImpl().
SetCascades()
void lldb_private::TypeSummaryImpl::SetCascades (bool value) inline
Definition at line 232 of file TypeSummary.h.
References m_flags.
SetDoesPrintChildren()
virtual void lldb_private::TypeSummaryImpl::SetDoesPrintChildren (bool value) inline virtual
Definition at line 238 of file TypeSummary.h.
References m_flags.
SetDoesPrintValue()
virtual void lldb_private::TypeSummaryImpl::SetDoesPrintValue (bool value) inline virtual
Definition at line 242 of file TypeSummary.h.
References m_flags.
SetHideNames()
virtual void lldb_private::TypeSummaryImpl::SetHideNames (bool value) inline virtual
Definition at line 248 of file TypeSummary.h.
References m_flags.
SetIsOneLiner()
void lldb_private::TypeSummaryImpl::SetIsOneLiner (bool value) inline
Definition at line 246 of file TypeSummary.h.
References m_flags.
SetNonCacheable()
virtual void lldb_private::TypeSummaryImpl::SetNonCacheable (bool value) inline virtual
Definition at line 250 of file TypeSummary.h.
References m_flags.
SetOptions()
void lldb_private::TypeSummaryImpl::SetOptions (uint32_t value) inline
Definition at line 254 of file TypeSummary.h.
References m_flags.
SetPtrMatchDepth()
void lldb_private::TypeSummaryImpl::SetPtrMatchDepth (uint32_t value) inline
Definition at line 258 of file TypeSummary.h.
References m_ptr_match_depth.
SetSkipsPointers()
void lldb_private::TypeSummaryImpl::SetSkipsPointers (bool value) inline
Definition at line 234 of file TypeSummary.h.
References m_flags.
SetSkipsReferences()
void lldb_private::TypeSummaryImpl::SetSkipsReferences (bool value) inline
Definition at line 236 of file TypeSummary.h.
References m_flags.
SkipsPointers()
bool lldb_private::TypeSummaryImpl::SkipsPointers () const inline
Definition at line 208 of file TypeSummary.h.
References m_flags.
Referenced by lldb_private::BytecodeSummaryFormat::GetDescription(), lldb_private::CXXFunctionSummaryFormat::GetDescription(), lldb_private::ScriptSummaryFormat::GetDescription(), and lldb_private::StringSummaryFormat::GetDescription().
SkipsReferences()
bool lldb_private::TypeSummaryImpl::SkipsReferences () const inline
Definition at line 210 of file TypeSummary.h.
References m_flags.
Referenced by lldb_private::BytecodeSummaryFormat::GetDescription(), lldb_private::CXXFunctionSummaryFormat::GetDescription(), lldb_private::ScriptSummaryFormat::GetDescription(), and lldb_private::StringSummaryFormat::GetDescription().
Member Data Documentation
m_flags
Flags lldb_private::TypeSummaryImpl::m_flags protected
Definition at line 283 of file TypeSummary.h.
Referenced by Cascades(), DoesPrintChildren(), DoesPrintEmptyAggregates(), DoesPrintValue(), GetOptions(), HideNames(), IsOneLiner(), NonCacheable(), SetCascades(), SetDoesPrintChildren(), SetDoesPrintValue(), SetHideNames(), SetIsOneLiner(), SetNonCacheable(), SetOptions(), SetSkipsPointers(), SetSkipsReferences(), SkipsPointers(), SkipsReferences(), and TypeSummaryImpl().
m_kind
Kind lldb_private::TypeSummaryImpl::m_kind private
Definition at line 289 of file TypeSummary.h.
Referenced by GetKind(), GetSummaryKindName(), and TypeSummaryImpl().
m_my_revision
uint32_t lldb_private::TypeSummaryImpl::m_my_revision = 0 protected
Definition at line 282 of file TypeSummary.h.
Referenced by GetRevision().
m_ptr_match_depth
uint32_t lldb_private::TypeSummaryImpl::m_ptr_match_depth = 1 private
Definition at line 290 of file TypeSummary.h.
Referenced by GetPtrMatchDepth(), SetPtrMatchDepth(), and TypeSummaryImpl().
The documentation for this class was generated from the following files:
TypeSummary.h
TypeSummary.cpp