LLDB: lldb::SBType Class Reference
lldb::SBType Class Reference
#include <SBType.h>
Public Member Functions
SBType ()
SBType (const lldb::SBType &rhs)
~SBType ()
operator bool () const
bool IsValid () const
uint64_t GetByteSize ()
uint64_t GetByteAlign ()
bool IsPointerType ()
bool IsReferenceType ()
bool IsFunctionType ()
bool IsPolymorphicClass ()
bool IsArrayType ()
bool IsVectorType ()
bool IsTypedefType ()
bool IsAnonymousType ()
bool IsScopedEnumerationType ()
bool IsAggregateType ()
lldb::SBType GetPointerType ()
lldb::SBType GetPointeeType ()
lldb::SBType GetReferenceType ()
lldb::SBType GetTypedefedType ()
lldb::SBType GetDereferencedType ()
lldb::SBType GetUnqualifiedType ()
lldb::SBType GetArrayElementType ()
lldb::SBType GetArrayType (uint64_t size)
lldb::SBType GetVectorElementType ()
lldb::SBType GetCanonicalType ()
lldb::SBType GetEnumerationIntegerType ()
lldb::BasicType GetBasicType ()
lldb::SBType GetBasicType (lldb::BasicType type)
uint32_t GetNumberOfFields ()
uint32_t GetNumberOfDirectBaseClasses ()
uint32_t GetNumberOfVirtualBaseClasses ()
lldb::SBTypeMember GetFieldAtIndex (uint32_t idx)
lldb::SBTypeMember GetDirectBaseClassAtIndex (uint32_t idx)
lldb::SBTypeMember GetVirtualBaseClassAtIndex (uint32_t idx)
lldb::SBTypeStaticField GetStaticFieldWithName (const char *name)
lldb::SBTypeEnumMemberList GetEnumMembers ()
uint32_t GetNumberOfTemplateArguments ()
lldb::SBType GetTemplateArgumentType (uint32_t idx)
lldb::SBValue GetTemplateArgumentValue (lldb::SBTarget target, uint32_t idx)
Returns the value of the non-type template parameter at index idx.
lldb::TemplateArgumentKind GetTemplateArgumentKind (uint32_t idx)
Return the TemplateArgumentKind of the template argument at index idx.
lldb::SBType GetFunctionReturnType ()
lldb::SBTypeList GetFunctionArgumentTypes ()
uint32_t GetNumberOfMemberFunctions ()
lldb::SBTypeMemberFunction GetMemberFunctionAtIndex (uint32_t idx)
lldb::SBModule GetModule ()
const char * GetName ()
const char * GetDisplayTypeName ()
lldb::TypeClass GetTypeClass ()
bool IsTypeComplete ()
uint32_t GetTypeFlags ()
bool GetDescription (lldb::SBStream &description, lldb::DescriptionLevel description_level)
lldb::SBType FindDirectNestedType (const char *name)
lldb::SBType & operator= (const lldb::SBType &rhs)
bool operator== (lldb::SBType &rhs)
bool operator!= (lldb::SBType &rhs)
Protected Member Functions
lldb_private::TypeImpl & ref ()
const lldb_private::TypeImpl & ref () const
lldb::TypeImplSP GetSP ()
void SetSP (const lldb::TypeImplSP &type_impl_sp)
SBType (const lldb_private::CompilerType &)
SBType (const lldb::TypeSP &)
SBType (const lldb::TypeImplSP &)
Protected Attributes
lldb::TypeImplSP m_opaque_sp
Friends
class SBFunction
class SBModule
class SBTarget
class SBTypeEnumMember
class SBTypeEnumMemberList
class SBTypeNameSpecifier
class SBTypeMember
class SBTypeMemberFunction
class SBTypeStaticField
class SBTypeList
class SBValue
class SBWatchpoint
class lldb_private::python::SWIGBridge
Detailed Description
Definition at line 139 of file SBType.h.
Constructor & Destructor Documentation
SBType() [1/5]
SBType::SBType ()
Definition at line 36 of file SBType.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by FindDirectNestedType(), GetArrayElementType(), GetArrayType(), GetBasicType(), GetCanonicalType(), GetDereferencedType(), GetEnumerationIntegerType(), GetFunctionArgumentTypes(), GetFunctionReturnType(), GetPointeeType(), GetPointerType(), GetReferenceType(), GetTemplateArgumentType(), GetTypedefedType(), GetUnqualifiedType(), GetVectorElementType(), operator!=(), operator=(), operator==(), and SBType().
SBType() [2/5]
SBType::SBType (const lldb::SBType & rhs)
Definition at line 46 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBType().
~SBType()
SBType::~SBType () default
SBType() [3/5]
SBType::SBType (const lldb_private::CompilerType & type) protected
Definition at line 38 of file SBType.cpp.
References m_opaque_sp.
SBType() [4/5]
SBType::SBType (const lldb::TypeSP & type_sp) protected
Definition at line 40 of file SBType.cpp.
References m_opaque_sp.
SBType() [5/5]
lldb::SBType::SBType (const lldb::TypeImplSP &) protected
Member Function Documentation
FindDirectNestedType()
SBType SBType::FindDirectNestedType (const char * name)
Definition at line 725 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBType().
GetArrayElementType()
SBType SBType::GetArrayElementType ()
Definition at line 222 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBType().
GetArrayType()
SBType SBType::GetArrayType (uint64_t size)
Definition at line 231 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBType().
GetBasicType() [1/2]
lldb::BasicType SBType::GetBasicType ()
Definition at line 445 of file SBType.cpp.
References lldb::eBasicTypeInvalid, IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetBasicType() [2/2]
SBType SBType::GetBasicType (lldb::BasicType type)
Definition at line 453 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBType().
GetByteAlign()
uint64_t SBType::GetByteAlign ()
Definition at line 136 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetByteSize()
uint64_t SBType::GetByteSize ()
Definition at line 126 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetCanonicalType()
lldb::SBType SBType::GetCanonicalType ()
Definition at line 427 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBType().
GetDereferencedType()
SBType SBType::GetDereferencedType ()
Definition at line 214 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBType().
GetDescription()
bool SBType::GetDescription (lldb::SBStream & description, lldb::DescriptionLevel description_level)
Definition at line 486 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, lldb_private::Stream::PutCString(), and lldb::SBStream::ref().
GetDirectBaseClassAtIndex()
SBTypeMember SBType::GetDirectBaseClassAtIndex (uint32_t idx)
Definition at line 500 of file SBType.cpp.
References IsValid(), lldb_private::CompilerType::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, lldb::SBTypeMember::reset(), and SBTypeMember.
GetDisplayTypeName()
const char * SBType::GetDisplayTypeName ()
Definition at line 629 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetEnumerationIntegerType()
SBType SBType::GetEnumerationIntegerType ()
Definition at line 435 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBType().
GetEnumMembers()
SBTypeEnumMemberList SBType::GetEnumMembers ()
Definition at line 542 of file SBType.cpp.
References lldb::SBTypeEnumMemberList::Append(), lldb_private::CompilerType::ForEachEnumerator(), IsValid(), lldb_private::CompilerType::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, SBTypeEnumMember, and SBTypeEnumMemberList.
GetFieldAtIndex()
SBTypeMember SBType::GetFieldAtIndex (uint32_t idx)
Definition at line 563 of file SBType.cpp.
References lldb_private::CompilerType::GetFieldAtIndex(), IsValid(), lldb_private::CompilerType::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, lldb::SBTypeMember::reset(), SBTypeMember, and lldb_private::ConstString::SetCString().
GetFunctionArgumentTypes()
lldb::SBTypeList SBType::GetFunctionArgumentTypes ()
Definition at line 313 of file SBType.cpp.
References lldb::SBTypeList::Append(), lldb_private::CompilerType::GetFunctionArgumentAtIndex(), lldb_private::CompilerType::GetNumberOfFunctionArguments(), IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, SBType(), and SBTypeList.
GetFunctionReturnType()
lldb::SBType SBType::GetFunctionReturnType ()
Definition at line 301 of file SBType.cpp.
References IsValid(), lldb_private::CompilerType::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, lldb::SBType, and SBType().
GetMemberFunctionAtIndex()
lldb::SBTypeMemberFunction SBType::GetMemberFunctionAtIndex (uint32_t idx)
Definition at line 336 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, lldb::SBTypeMemberFunction::reset(), and SBTypeMemberFunction.
GetModule()
lldb::SBModule SBType::GetModule ()
Definition at line 610 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and lldb::SBModule::SetSP().
GetName()
const char * SBType::GetName ()
Definition at line 621 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetNumberOfDirectBaseClasses()
uint32_t SBType::GetNumberOfDirectBaseClasses ()
Definition at line 462 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetNumberOfFields()
uint32_t SBType::GetNumberOfFields ()
Definition at line 478 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetNumberOfMemberFunctions()
uint32_t SBType::GetNumberOfMemberFunctions ()
Definition at line 327 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetNumberOfTemplateArguments()
uint32_t SBType::GetNumberOfTemplateArguments ()
Definition at line 645 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetNumberOfVirtualBaseClasses()
uint32_t SBType::GetNumberOfVirtualBaseClasses ()
Definition at line 470 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetPointeeType()
SBType SBType::GetPointeeType ()
Definition at line 190 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBType().
GetPointerType()
SBType SBType::GetPointerType ()
Definition at line 181 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBType().
GetReferenceType()
SBType SBType::GetReferenceType ()
Definition at line 198 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBType().
GetSP()
lldb::TypeImplSP SBType::GetSP () protected
Definition at line 82 of file SBType.cpp.
References m_opaque_sp.
Referenced by lldb::SBValue::Cast(), lldb::SBValue::CreateChildAtOffset(), lldb::SBTarget::CreateValueFromAddress(), lldb::SBValue::CreateValueFromAddress(), lldb::SBTarget::CreateValueFromData(), and lldb::SBValue::CreateValueFromData().
GetStaticFieldWithName()
SBTypeStaticField SBType::GetStaticFieldWithName (const char * name)
Definition at line 532 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBTypeStaticField.
GetTemplateArgumentKind()
lldb::TemplateArgumentKind SBType::GetTemplateArgumentKind (uint32_t idx)
Return the TemplateArgumentKind of the template argument at index idx.
Variadic argument packs are automatically expanded.
Definition at line 680 of file SBType.cpp.
References lldb::eTemplateArgumentKindNull, IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
Referenced by GetTemplateArgumentType(), and GetTemplateArgumentValue().
GetTemplateArgumentType()
lldb::SBType SBType::GetTemplateArgumentType (uint32_t idx)
Definition at line 654 of file SBType.cpp.
References lldb::eTemplateArgumentKindIntegral, lldb::eTemplateArgumentKindType, GetTemplateArgumentKind(), IsValid(), lldb_private::CompilerType::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBType().
GetTemplateArgumentValue()
lldb::SBValue SBType::GetTemplateArgumentValue (lldb::SBTarget target, uint32_t idx)
Returns the value of the non-type template parameter at index idx.
If idx is out-of-bounds or the template parameter doesn't have a value, returns an empty SBValue.
This function will expand parameter packs.
Definition at line 689 of file SBType.cpp.
References lldb_private::ValueObject::CreateValueObjectFromData(), lldb::eTemplateArgumentKindIntegral, lldb::eTemplateArgumentKindStructuralValue, lldb::SBTarget::GetSP(), GetTemplateArgumentKind(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetTypeClass()
lldb::TypeClass SBType::GetTypeClass ()
Definition at line 637 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetTypedefedType()
SBType SBType::GetTypedefedType ()
Definition at line 206 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBType().
GetTypeFlags()
uint32_t SBType::GetTypeFlags ()
Definition at line 602 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
GetUnqualifiedType()
lldb::SBType SBType::GetUnqualifiedType ()
Definition at line 419 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBType().
GetVectorElementType()
SBType SBType::GetVectorElementType ()
Definition at line 240 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, SBType(), and SetSP().
GetVirtualBaseClassAtIndex()
SBTypeMember SBType::GetVirtualBaseClassAtIndex (uint32_t idx)
Definition at line 516 of file SBType.cpp.
References IsValid(), lldb_private::CompilerType::IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, lldb::SBTypeMember::reset(), and SBTypeMember.
IsAggregateType()
bool SBType::IsAggregateType ()
Definition at line 293 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
IsAnonymousType()
bool SBType::IsAnonymousType ()
Definition at line 277 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
IsArrayType()
bool SBType::IsArrayType ()
Definition at line 156 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
IsFunctionType()
bool SBType::IsFunctionType ()
Definition at line 253 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
IsPointerType()
bool SBType::IsPointerType ()
Definition at line 148 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
IsPolymorphicClass()
bool SBType::IsPolymorphicClass ()
Definition at line 261 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
IsReferenceType()
bool SBType::IsReferenceType ()
Definition at line 173 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
IsScopedEnumerationType()
bool SBType::IsScopedEnumerationType ()
Definition at line 285 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
IsTypeComplete()
bool SBType::IsTypeComplete ()
Definition at line 589 of file SBType.cpp.
References lldb_private::CompilerType::IsCompleteType(), lldb_private::CompilerType::IsForcefullyCompleted(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
IsTypedefType()
bool SBType::IsTypedefType ()
Definition at line 269 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
IsValid()
bool SBType::IsValid () const
Definition at line 113 of file SBType.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by lldb::SBTypeList::Append(), lldb::SBValue::CreateChildAtOffset(), lldb::SBTarget::CreateValueFromAddress(), lldb::SBTarget::CreateValueFromData(), FindDirectNestedType(), GetArrayElementType(), GetArrayType(), GetBasicType(), GetBasicType(), GetByteAlign(), GetByteSize(), GetCanonicalType(), GetDereferencedType(), GetDirectBaseClassAtIndex(), GetDisplayTypeName(), GetEnumerationIntegerType(), GetEnumMembers(), GetFieldAtIndex(), GetFunctionArgumentTypes(), GetFunctionReturnType(), GetMemberFunctionAtIndex(), GetModule(), GetName(), GetNumberOfDirectBaseClasses(), GetNumberOfFields(), GetNumberOfMemberFunctions(), GetNumberOfTemplateArguments(), GetNumberOfVirtualBaseClasses(), GetPointeeType(), GetPointerType(), GetReferenceType(), GetStaticFieldWithName(), GetTemplateArgumentKind(), GetTemplateArgumentType(), GetTemplateArgumentValue(), GetTypeClass(), GetTypedefedType(), GetTypeFlags(), GetUnqualifiedType(), GetVectorElementType(), GetVirtualBaseClassAtIndex(), IsAggregateType(), IsAnonymousType(), IsArrayType(), IsFunctionType(), IsPointerType(), IsPolymorphicClass(), IsReferenceType(), IsScopedEnumerationType(), IsTypeComplete(), IsTypedefType(), IsVectorType(), operator!=(), operator==(), and lldb::SBTypeNameSpecifier::SBTypeNameSpecifier().
IsVectorType()
bool SBType::IsVectorType ()
Definition at line 165 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator bool()
SBType::operator bool () const explicit
Definition at line 117 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_sp.
operator!=()
bool SBType::operator!= (lldb::SBType & rhs)
Definition at line 70 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBType().
operator=()
SBType & SBType::operator= (const lldb::SBType & rhs)
Definition at line 88 of file SBType.cpp.
References LLDB_INSTRUMENT_VA, m_opaque_sp, and SBType().
operator==()
bool SBType::operator== (lldb::SBType & rhs)
Definition at line 58 of file SBType.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_sp, and SBType().
ref() [1/2]
TypeImpl & SBType::ref () protected
Definition at line 99 of file SBType.cpp.
References m_opaque_sp.
Referenced by lldb::SBFunction::GetType().
ref() [2/2]
const TypeImpl & SBType::ref () const protected
Definition at line 105 of file SBType.cpp.
References m_opaque_sp.
SetSP()
void SBType::SetSP (const lldb::TypeImplSP & type_impl_sp) protected
Definition at line 84 of file SBType.cpp.
References m_opaque_sp.
Referenced by lldb::SBTypeMemberFunction::GetArgumentTypeAtIndex(), lldb::SBTypeMemberFunction::GetReturnType(), lldb::SBTypeEnumMember::GetType(), lldb::SBTypeMember::GetType(), lldb::SBTypeMemberFunction::GetType(), lldb::SBValue::GetType(), and GetVectorElementType().
Friends And Related Symbol Documentation
lldb_private::python::SWIGBridge
friend class lldb_private::python::SWIGBridge friend
Definition at line 290 of file SBType.h.
SBFunction
friend class SBFunction friend
Definition at line 277 of file SBType.h.
References SBFunction.
Referenced by SBFunction.
SBModule
friend class SBModule friend
Definition at line 278 of file SBType.h.
References SBModule.
Referenced by SBModule.
SBTarget
friend class SBTarget friend
Definition at line 279 of file SBType.h.
References SBTarget.
Referenced by SBTarget.
SBTypeEnumMember
friend class SBTypeEnumMember friend
Definition at line 280 of file SBType.h.
References SBTypeEnumMember.
Referenced by GetEnumMembers(), and SBTypeEnumMember.
SBTypeEnumMemberList
friend class SBTypeEnumMemberList friend
Definition at line 281 of file SBType.h.
References SBTypeEnumMemberList.
Referenced by GetEnumMembers(), and SBTypeEnumMemberList.
SBTypeList
friend class SBTypeList friend
Definition at line 286 of file SBType.h.
References SBTypeList.
Referenced by GetFunctionArgumentTypes(), and SBTypeList.
SBTypeMember
friend class SBTypeMember friend
Definition at line 283 of file SBType.h.
References SBTypeMember.
Referenced by GetDirectBaseClassAtIndex(), GetFieldAtIndex(), GetVirtualBaseClassAtIndex(), and SBTypeMember.
SBTypeMemberFunction
friend class SBTypeMemberFunction friend
Definition at line 284 of file SBType.h.
References SBTypeMemberFunction.
Referenced by GetMemberFunctionAtIndex(), and SBTypeMemberFunction.
SBTypeNameSpecifier
friend class SBTypeNameSpecifier friend
Definition at line 282 of file SBType.h.
References SBTypeNameSpecifier.
Referenced by SBTypeNameSpecifier.
SBTypeStaticField
friend class SBTypeStaticField friend
Definition at line 285 of file SBType.h.
References SBTypeStaticField.
Referenced by GetStaticFieldWithName(), and SBTypeStaticField.
SBValue
friend class SBValue friend
Definition at line 287 of file SBType.h.
References SBValue.
Referenced by SBValue.
SBWatchpoint
friend class SBWatchpoint friend
Definition at line 288 of file SBType.h.
References SBWatchpoint.
Referenced by SBWatchpoint.
Member Data Documentation
m_opaque_sp
lldb::TypeImplSP lldb::SBType::m_opaque_sp protected
Definition at line 275 of file SBType.h.
Referenced by lldb::SBTypeList::Append(), FindDirectNestedType(), GetArrayElementType(), GetArrayType(), GetBasicType(), GetBasicType(), GetByteAlign(), GetByteSize(), GetCanonicalType(), GetDereferencedType(), GetDescription(), GetDirectBaseClassAtIndex(), GetDisplayTypeName(), GetEnumerationIntegerType(), GetEnumMembers(), GetFieldAtIndex(), GetFunctionArgumentTypes(), GetFunctionReturnType(), GetMemberFunctionAtIndex(), GetModule(), GetName(), GetNumberOfDirectBaseClasses(), GetNumberOfFields(), GetNumberOfMemberFunctions(), GetNumberOfTemplateArguments(), GetNumberOfVirtualBaseClasses(), GetPointeeType(), GetPointerType(), GetReferenceType(), GetSP(), GetStaticFieldWithName(), GetTemplateArgumentKind(), GetTemplateArgumentType(), GetTemplateArgumentValue(), GetTypeClass(), GetTypedefedType(), GetTypeFlags(), GetUnqualifiedType(), GetVectorElementType(), GetVirtualBaseClassAtIndex(), IsAggregateType(), IsAnonymousType(), IsArrayType(), IsFunctionType(), IsPointerType(), IsPolymorphicClass(), IsReferenceType(), IsScopedEnumerationType(), IsTypeComplete(), IsTypedefType(), IsVectorType(), operator bool(), operator!=(), operator=(), operator==(), ref(), ref(), SBType(), SBType(), SBType(), lldb::SBTypeNameSpecifier::SBTypeNameSpecifier(), and SetSP().
The documentation for this class was generated from the following files:
SBType.h
SBType.cpp