LLDB: lldb_private::StringTableReader Class Reference
lldb_private::StringTableReader Class Reference
Many cache files require string tables to store data efficiently.
#include <DataFileCache.h>
Public Member Functions
StringTableReader ()=default
llvm::StringRef Get (uint32_t offset) const
bool Decode (const DataExtractor &data, lldb::offset_t *offset_ptr)
Protected Attributes
llvm::StringRef m_data
All of the strings in the string table are contained in m_data.
Detailed Description
Many cache files require string tables to store data efficiently.
This class helps give out strings from a string table that was read from a cache file.
Definition at line 213 of file DataFileCache.h.
Constructor & Destructor Documentation
StringTableReader()
lldb_private::StringTableReader::StringTableReader () default
Member Function Documentation
Decode()
bool StringTableReader::Decode (const DataExtractor & data, lldb::offset_t * offset_ptr)
Definition at line 304 of file DataFileCache.cpp.
References lldb_private::DataExtractor::GetData(), lldb_private::DataExtractor::GetU32(), kStringTableIdentifier(), and m_data.
Referenced by lldb_private::Symtab::Decode(), and lldb_private::plugin::dwarf::DecodeIndexSet().
Get()
llvm::StringRef StringTableReader::Get (uint32_t offset) const
Definition at line 320 of file DataFileCache.cpp.
References m_data.
Referenced by lldb_private::Mangled::Decode(), lldb_private::plugin::dwarf::NameToDIE::Decode(), and DecodeCStrMap().
Member Data Documentation
m_data
llvm::StringRef lldb_private::StringTableReader::m_data protected
All of the strings in the string table are contained in m_data.
Definition at line 223 of file DataFileCache.h.
Referenced by Decode(), and Get().
The documentation for this class was generated from the following files:
DataFileCache.h
DataFileCache.cpp