LLDB: lldb_private::FormattersMatchCandidate Class Reference
lldb_private::FormattersMatchCandidate Class Reference
#include <FormatClasses.h>
Classes
struct Flags
Public Member Functions
FormattersMatchCandidate (ConstString name, ScriptInterpreter *script_interpreter, TypeImpl type, Flags flags, uint32_t ptr_stripped_depth=0)
~FormattersMatchCandidate ()=default
ConstString GetTypeName () const
TypeImpl GetType () const
ScriptInterpreter * GetScriptInterpreter () const
bool DidStripPointer () const
bool DidStripReference () const
bool DidStripTypedef () const
uint32_t GetPtrStrippedDepth () const
template<class Formatter>
bool IsMatch (const std::shared_ptr< Formatter > &formatter_sp) const
Private Attributes
ConstString m_type_name
ScriptInterpreter * m_script_interpreter
TypeImpl m_type
Flags m_flags
uint32_t m_ptr_stripped_depth
Detailed Description
Definition at line 45 of file FormatClasses.h.
Constructor & Destructor Documentation
FormattersMatchCandidate()
lldb_private::FormattersMatchCandidate::FormattersMatchCandidate (ConstString name, ScriptInterpreter * script_interpreter, TypeImpl type, Flags flags, uint32_t ptr_stripped_depth = 0) inline
Definition at line 77 of file FormatClasses.h.
References m_flags, m_ptr_stripped_depth, m_script_interpreter, m_type, and m_type_name.
~FormattersMatchCandidate()
lldb_private::FormattersMatchCandidate::~FormattersMatchCandidate () default
Member Function Documentation
DidStripPointer()
bool lldb_private::FormattersMatchCandidate::DidStripPointer () const inline
Definition at line 94 of file FormatClasses.h.
References m_flags.
Referenced by IsMatch().
DidStripReference()
bool lldb_private::FormattersMatchCandidate::DidStripReference () const inline
Definition at line 96 of file FormatClasses.h.
References m_flags.
Referenced by IsMatch().
DidStripTypedef()
bool lldb_private::FormattersMatchCandidate::DidStripTypedef () const inline
Definition at line 98 of file FormatClasses.h.
References m_flags.
Referenced by IsMatch().
GetPtrStrippedDepth()
uint32_t lldb_private::FormattersMatchCandidate::GetPtrStrippedDepth () const inline
Definition at line 100 of file FormatClasses.h.
References m_ptr_stripped_depth.
Referenced by IsMatch().
GetScriptInterpreter()
ScriptInterpreter * lldb_private::FormattersMatchCandidate::GetScriptInterpreter () const inline
Definition at line 90 of file FormatClasses.h.
References m_script_interpreter.
Referenced by lldb_private::TypeMatcher::Matches().
GetType()
TypeImpl lldb_private::FormattersMatchCandidate::GetType () const inline
Definition at line 88 of file FormatClasses.h.
References m_type.
Referenced by lldb_private::TypeMatcher::Matches().
GetTypeName()
ConstString lldb_private::FormattersMatchCandidate::GetTypeName () const inline
Definition at line 86 of file FormatClasses.h.
References m_type_name.
Referenced by lldb_private::TypeMatcher::Matches().
IsMatch()
template<class Formatter> bool lldb_private::FormattersMatchCandidate::IsMatch (const std::shared_ptr< Formatter > & formatter_sp) const inline
Definition at line 103 of file FormatClasses.h.
References DidStripPointer(), DidStripReference(), DidStripTypedef(), and GetPtrStrippedDepth().
Member Data Documentation
m_flags
Flags lldb_private::FormattersMatchCandidate::m_flags private
Definition at line 123 of file FormatClasses.h.
Referenced by DidStripPointer(), DidStripReference(), DidStripTypedef(), and FormattersMatchCandidate().
m_ptr_stripped_depth
uint32_t lldb_private::FormattersMatchCandidate::m_ptr_stripped_depth private
Definition at line 124 of file FormatClasses.h.
Referenced by FormattersMatchCandidate(), and GetPtrStrippedDepth().
m_script_interpreter
ScriptInterpreter* lldb_private::FormattersMatchCandidate::m_script_interpreter private
Definition at line 121 of file FormatClasses.h.
Referenced by FormattersMatchCandidate(), and GetScriptInterpreter().
m_type
TypeImpl lldb_private::FormattersMatchCandidate::m_type private
Definition at line 122 of file FormatClasses.h.
Referenced by FormattersMatchCandidate(), and GetType().
m_type_name
ConstString lldb_private::FormattersMatchCandidate::m_type_name private
Definition at line 118 of file FormatClasses.h.
Referenced by FormattersMatchCandidate(), and GetTypeName().
The documentation for this class was generated from the following file:
FormatClasses.h