LLDB: lldb_private::FreeBSDSignals Class Reference
lldb_private::FreeBSDSignals Class Reference
FreeBSD specific set of Unix signals.
#include <FreeBSDSignals.h>
Public Member Functions
FreeBSDSignals ()
Public Member Functions inherited from lldb_private::UnixSignals
UnixSignals ()
virtual ~UnixSignals ()
llvm::StringRef GetSignalAsStringRef (int32_t signo) const
llvm::StringRef GetSignalNumberDescription (int32_t signo) const
std::string GetSignalDescription (int32_t signo, std::optional< int32_t > code=std::nullopt, std::optional< lldb::addr_t > addr=std::nullopt, std::optional< lldb::addr_t > lower=std::nullopt, std::optional< lldb::addr_t > upper=std::nullopt, std::optional< uint32_t > pid=std::nullopt, std::optional< uint32_t > uid=std::nullopt) const
bool SignalIsValid (int32_t signo) const
int32_t GetSignalNumberFromName (const char *name) const
bool GetSignalInfo (int32_t signo, bool &should_suppress, bool &should_stop, bool &should_notify) const
Gets the information for a particular signal.
bool GetShouldSuppress (int32_t signo) const
bool SetShouldSuppress (int32_t signo, bool value)
bool SetShouldSuppress (const char *signal_name, bool value)
bool GetShouldStop (int32_t signo) const
bool SetShouldStop (int32_t signo, bool value)
bool SetShouldStop (const char *signal_name, bool value)
bool GetShouldNotify (int32_t signo) const
bool SetShouldNotify (int32_t signo, bool value)
bool SetShouldNotify (const char *signal_name, bool value)
bool ResetSignal (int32_t signo, bool reset_stop=true, bool reset_notify=true, bool reset_suppress=true)
int32_t GetFirstSignalNumber () const
int32_t GetNextSignalNumber (int32_t current_signal) const
int32_t GetNumSignals () const
int32_t GetSignalAtIndex (int32_t index) const
void AddSignal (int signo, llvm::StringRef name, bool default_suppress, bool default_stop, bool default_notify, llvm::StringRef description, llvm::StringRef alias=llvm::StringRef())
void AddSignalCode (int signo, int code, const llvm::StringLiteral description, SignalCodePrintOption print_option=SignalCodePrintOption::None)
void RemoveSignal (int signo)
void IncrementSignalHitCount (int signo)
Track how many times signals are hit as stop reasons.
llvm::json::Value GetHitCountStatistics () const
Get the hit count statistics for signals.
uint64_t GetVersion () const
std::vector< int32_t > GetFilteredSignals (std::optional< bool > should_suppress, std::optional< bool > should_stop, std::optional< bool > should_notify)
Private Member Functions
void Reset () override
Additional Inherited Members
Public Types inherited from lldb_private::UnixSignals
enum SignalCodePrintOption { None , Address , Bounds , Sender }
Static Public Member Functions inherited from lldb_private::UnixSignals
static lldb::UnixSignalsSP Create (const ArchSpec &arch)
static lldb::UnixSignalsSP CreateForHost ()
Protected Types inherited from lldb_private::UnixSignals
typedef std::map< int32_t, Signal > collection
Protected Member Functions inherited from lldb_private::UnixSignals
llvm::StringRef GetShortName (llvm::StringRef name) const
UnixSignals (const UnixSignals &rhs)
const UnixSignals & operator= (const UnixSignals &rhs)=delete
Protected Attributes inherited from lldb_private::UnixSignals
collection m_signals
uint64_t m_version = 0
Detailed Description
FreeBSD specific set of Unix signals.
Definition at line 17 of file FreeBSDSignals.h.
Constructor & Destructor Documentation
FreeBSDSignals()
FreeBSDSignals::FreeBSDSignals ()
Definition at line 31 of file FreeBSDSignals.cpp.
References Reset(), and lldb_private::UnixSignals::UnixSignals().
Member Function Documentation
Reset()
void FreeBSDSignals::Reset () override private virtual
Reimplemented from lldb_private::UnixSignals.
Definition at line 33 of file FreeBSDSignals.cpp.
References ADD_SIGCODE, lldb_private::UnixSignals::Address, lldb_private::UnixSignals::AddSignal(), lldb_private::UnixSignals::Reset(), SIGBUS, SIGFPE, SIGILL, and SIGSEGV.
Referenced by FreeBSDSignals().
The documentation for this class was generated from the following files:
FreeBSDSignals.h
FreeBSDSignals.cpp