LLDB: CoreSimulatorSupport::Device Class Reference
CoreSimulatorSupport::Device Class Reference
#include <PlatformiOSSimulatorCoreSimulatorSupport.h>
Public Types
enum class State : NSUInteger {
Creating , Shutdown , Booting , Booted ,
ShuttingDown
}
Public Member Functions
Device ()
Device (id d)
operator bool ()
std::string GetName () const
DeviceType GetDeviceType ()
DeviceRuntime GetDeviceRuntime ()
State GetState ()
bool Boot (lldb_private::Status &err)
bool Shutdown (lldb_private::Status &err)
std::string GetUDID () const
Process Spawn (lldb_private::ProcessLaunchInfo &launch_info)
Private Types
typedef unsigned long int NSUInteger
Private Attributes
id m_dev = nullptr
std::optional< DeviceType > m_dev_type
std::optional< DeviceRuntime > m_dev_runtime
Friends
class DeviceSet
Detailed Description
Definition at line 137 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
Member Typedef Documentation
NSUInteger
typedef unsigned long int CoreSimulatorSupport::Device::NSUInteger private
Definition at line 139 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
Member Enumeration Documentation
State
enum class CoreSimulatorSupport::Device::State : NSUInteger strong
Enumerator
Creating
Shutdown
Booting
Booted
ShuttingDown
Definition at line 142 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
Constructor & Destructor Documentation
Device() [1/2]
CoreSimulatorSupport::Device::Device ()
Definition at line 100 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References m_dev_runtime, and m_dev_type.
Device() [2/2]
CoreSimulatorSupport::Device::Device (id d)
Definition at line 102 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References m_dev, m_dev_runtime, and m_dev_type.
Member Function Documentation
Boot()
bool CoreSimulatorSupport::Device::Boot (lldb_private::Status & err)
Definition at line 342 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References lldb_private::Status::Clear(), error(), lldb_private::Status::FromErrorString(), kSimDeviceBootPersist, and m_dev.
Referenced by lldb_private::PlatformAppleSimulator::LaunchProcess().
GetDeviceRuntime()
CoreSimulatorSupport::DeviceRuntime CoreSimulatorSupport::Device::GetDeviceRuntime ()
Definition at line 228 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References m_dev, and m_dev_runtime.
GetDeviceType()
CoreSimulatorSupport::DeviceType CoreSimulatorSupport::Device::GetDeviceType ()
Definition at line 220 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References m_dev, and m_dev_type.
GetName()
std::string CoreSimulatorSupport::Device::GetName () const
Definition at line 205 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
Referenced by lldb_private::PlatformAppleSimulator::ConnectRemote(), and lldb_private::PlatformAppleSimulator::GetStatus().
GetState()
CoreSimulatorSupport::Device::State CoreSimulatorSupport::Device::GetState ()
Definition at line 107 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
Referenced by lldb_private::PlatformAppleSimulator::LaunchProcess().
GetUDID()
std::string CoreSimulatorSupport::Device::GetUDID () const
Definition at line 212 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
Referenced by lldb_private::PlatformAppleSimulator::ConnectRemote(), and lldb_private::PlatformAppleSimulator::GetStatus().
operator bool()
CoreSimulatorSupport::Device::operator bool () explicit
Definition at line 105 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References m_dev.
Shutdown()
bool CoreSimulatorSupport::Device::Shutdown (lldb_private::Status & err)
Definition at line 367 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References lldb_private::Status::Clear(), lldb_private::Status::FromErrorString(), and m_dev.
Spawn()
CoreSimulatorSupport::Process CoreSimulatorSupport::Device::Spawn (lldb_private::ProcessLaunchInfo & launch_info)
Definition at line 447 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References error(), lldb_private::Status::FromErrorString(), lldb_private::Args::GetArgumentCount(), lldb_private::ProcessInfo::GetArguments(), lldb_private::ProcessInfo::GetEnvironment(), lldb_private::ProcessLaunchInfo::GetFlags(), HandleFileAction(), kSimDeviceSpawnStderr, kSimDeviceSpawnStdin, kSimDeviceSpawnStdout, and lldb_private::Flags::Test().
Referenced by lldb_private::PlatformAppleSimulator::LaunchProcess().
Friends And Related Symbol Documentation
DeviceSet
friend class DeviceSet friend
Definition at line 177 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
References DeviceSet.
Referenced by DeviceSet.
Member Data Documentation
m_dev
id CoreSimulatorSupport::Device::m_dev = nullptr private
Definition at line 173 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
Referenced by Boot(), Device(), GetDeviceRuntime(), GetDeviceType(), operator bool(), and Shutdown().
m_dev_runtime
std::optional<DeviceRuntime> CoreSimulatorSupport::Device::m_dev_runtime private
Definition at line 175 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
Referenced by Device(), Device(), and GetDeviceRuntime().
m_dev_type
std::optional<DeviceType> CoreSimulatorSupport::Device::m_dev_type private
Definition at line 174 of file PlatformiOSSimulatorCoreSimulatorSupport.h.
Referenced by Device(), Device(), and GetDeviceType().
The documentation for this class was generated from the following files:
PlatformiOSSimulatorCoreSimulatorSupport.h
PlatformiOSSimulatorCoreSimulatorSupport.mm