LLDB: lldb_private::StopInfoUnixSignal Class Reference
lldb_private::StopInfoUnixSignal Class Reference
Public Member Functions
StopInfoUnixSignal (Thread &thread, int signo, const char *description, std::optional< int > code)
~StopInfoUnixSignal () override=default
StopReason GetStopReason () const override
bool ShouldStopSynchronous (Event *event_ptr) override
bool ShouldStop (Event *event_ptr) override
bool DoShouldNotify (Event *event_ptr) override
void WillResume (lldb::StateType resume_state) override
const char * GetDescription () override
bool ShouldSelect () const override
Returns true if this is a stop reason that should cause a thread to be selected when stopping.
uint32_t GetStopReasonDataCount () const override
uint64_t GetStopReasonDataAtIndex (uint32_t idx) override
Public Member Functions inherited from lldb_private::StopInfo
StopInfo (Thread &thread, uint64_t value)
virtual ~StopInfo ()=default
bool IsValid () const
void SetThread (const lldb::ThreadSP &thread_sp)
lldb::ThreadSP GetThread () const
uint64_t GetValue () const
void OverrideShouldNotify (bool override_value)
virtual bool ShouldNotify (Event *event_ptr)
virtual void SetDescription (const char *desc_cstr)
virtual std::optional< uint32_t > GetSuggestedStackFrameIndex (bool inlined_stack)
This gives the StopInfo a chance to suggest a stack frame to select.
virtual bool IsValidForOperatingSystemThread (Thread &thread)
virtual bool WasContinueInterrupted (Thread &thread)
A Continue operation can result in a false stop event before any execution has happened.
void OverrideShouldStop (bool override_value)
bool GetOverrideShouldStop ()
bool GetOverriddenShouldStopValue ()
StructuredData::ObjectSP GetExtendedInfo ()
virtual bool ShouldShow () const
Returns true if this is a stop reason that should be shown to a user when viewing the thread with this stop info.
Private Member Functions
bool IsShouldStopSignal () const
Private Attributes
std::optional< int > m_code
Additional Inherited Members
Static Public Member Functions inherited from lldb_private::StopInfo
static lldb::StopInfoSP CreateStopReasonWithBreakpointSiteID (Thread &thread, lldb::break_id_t break_id)
static lldb::StopInfoSP CreateStopReasonWithBreakpointSiteID (Thread &thread, lldb::break_id_t break_id, bool should_stop)
static lldb::StopInfoSP CreateStopReasonWithWatchpointID (Thread &thread, lldb::break_id_t watch_id, bool silently_continue=false)
static lldb::StopInfoSP CreateStopReasonWithSignal (Thread &thread, int signo, const char *description=nullptr, std::optional< int > code=std::nullopt)
static lldb::StopInfoSP CreateStopReasonWithInterrupt (Thread &thread, int signo, const char *description)
static lldb::StopInfoSP CreateStopReasonToTrace (Thread &thread)
static lldb::StopInfoSP CreateStopReasonWithPlan (lldb::ThreadPlanSP &plan, lldb::ValueObjectSP return_valobj_sp, lldb::ExpressionVariableSP expression_variable_sp)
static lldb::StopInfoSP CreateStopReasonWithException (Thread &thread, const char *description)
static lldb::StopInfoSP CreateStopReasonWithExec (Thread &thread)
static lldb::StopInfoSP CreateStopReasonProcessorTrace (Thread &thread, const char *description)
static lldb::StopInfoSP CreateStopReasonHistoryBoundary (Thread &thread, const char *description)
static lldb::StopInfoSP CreateStopReasonFork (Thread &thread, lldb::pid_t child_pid, lldb::tid_t child_tid)
static lldb::StopInfoSP CreateStopReasonVFork (Thread &thread, lldb::pid_t child_pid, lldb::tid_t child_tid)
static lldb::StopInfoSP CreateStopReasonVForkDone (Thread &thread)
static lldb::ValueObjectSP GetReturnValueObject (lldb::StopInfoSP &stop_info_sp)
static lldb::ExpressionVariableSP GetExpressionVariable (lldb::StopInfoSP &stop_info_sp)
static lldb::ValueObjectSP GetCrashingDereference (lldb::StopInfoSP &stop_info_sp, lldb::addr_t *crashing_address=nullptr)
Protected Member Functions inherited from lldb_private::StopInfo
virtual void PerformAction (Event *event_ptr)
bool HasTargetRunSinceMe ()
void MakeStopInfoValid ()
Protected Attributes inherited from lldb_private::StopInfo
lldb::ThreadWP m_thread_wp
uint32_t m_stop_id
uint32_t m_resume_id
uint64_t m_value
std::string m_description
LazyBool m_override_should_notify
LazyBool m_override_should_stop
StructuredData::ObjectSP m_extended_info
Detailed Description
Definition at line 1143 of file StopInfo.cpp.
Constructor & Destructor Documentation
StopInfoUnixSignal()
lldb_private::StopInfoUnixSignal::StopInfoUnixSignal (Thread & thread, int signo, const char * description, std::optional< int > code) inline
Definition at line 1145 of file StopInfo.cpp.
References m_code, lldb_private::StopInfo::SetDescription(), lldb_private::StopInfo::StopInfo(), and lldb_private::StopInfo::Thread.
~StopInfoUnixSignal()
lldb_private::StopInfoUnixSignal::~StopInfoUnixSignal () override default
Member Function Documentation
DoShouldNotify()
bool lldb_private::StopInfoUnixSignal::DoShouldNotify (Event * event_ptr) inline override virtual
Reimplemented from lldb_private::StopInfo.
Definition at line 1165 of file StopInfo.cpp.
References lldb_private::Process::ProcessEventData::AddRestartedReason(), lldb_private::Stream::Format(), lldb_private::StreamString::GetData(), lldb_private::StopInfo::m_thread_wp, and lldb_private::StopInfo::m_value.
GetDescription()
const char * lldb_private::StopInfoUnixSignal::GetDescription () inline override virtual
Reimplemented from lldb_private::StopInfo.
Definition at line 1193 of file StopInfo.cpp.
References lldb_private::StreamString::GetString(), m_code, lldb_private::StopInfo::m_description, lldb_private::StopInfo::m_thread_wp, lldb_private::StopInfo::m_value, and lldb_private::Stream::Printf().
GetStopReason()
StopReason lldb_private::StopInfoUnixSignal::GetStopReason () const inline override virtual
Implements lldb_private::StopInfo.
Definition at line 1153 of file StopInfo.cpp.
References lldb::eStopReasonSignal.
GetStopReasonDataAtIndex()
uint64_t lldb_private::StopInfoUnixSignal::GetStopReasonDataAtIndex (uint32_t idx) inline override virtual
Reimplemented from lldb_private::StopInfo.
Definition at line 1217 of file StopInfo.cpp.
References lldb_private::StopInfo::GetValue().
GetStopReasonDataCount()
uint32_t lldb_private::StopInfoUnixSignal::GetStopReasonDataCount () const inline override virtual
Reimplemented from lldb_private::StopInfo.
Definition at line 1216 of file StopInfo.cpp.
IsShouldStopSignal()
bool lldb_private::StopInfoUnixSignal::IsShouldStopSignal () const inline private
Definition at line 1227 of file StopInfo.cpp.
References lldb_private::StopInfo::m_thread_wp, and lldb_private::StopInfo::m_value.
Referenced by ShouldSelect(), and ShouldStop().
ShouldSelect()
bool lldb_private::StopInfoUnixSignal::ShouldSelect () const inline override virtual
Returns true if this is a stop reason that should cause a thread to be selected when stopping.
Reimplemented from lldb_private::StopInfo.
Definition at line 1214 of file StopInfo.cpp.
References IsShouldStopSignal().
ShouldStop()
bool lldb_private::StopInfoUnixSignal::ShouldStop (Event * event_ptr) inline override virtual
Reimplemented from lldb_private::StopInfo.
Definition at line 1162 of file StopInfo.cpp.
References IsShouldStopSignal().
ShouldStopSynchronous()
bool lldb_private::StopInfoUnixSignal::ShouldStopSynchronous (Event * event_ptr) inline override virtual
Reimplemented from lldb_private::StopInfo.
Definition at line 1155 of file StopInfo.cpp.
References lldb_private::StopInfo::m_thread_wp, and lldb_private::StopInfo::m_value.
WillResume()
void lldb_private::StopInfoUnixSignal::WillResume (lldb::StateType resume_state) inline override virtual
Reimplemented from lldb_private::StopInfo.
Definition at line 1184 of file StopInfo.cpp.
References lldb_private::StopInfo::m_thread_wp, and lldb_private::StopInfo::m_value.
Member Data Documentation
m_code
std::optional<int> lldb_private::StopInfoUnixSignal::m_code private
Definition at line 1225 of file StopInfo.cpp.
Referenced by GetDescription(), and StopInfoUnixSignal().
The documentation for this class was generated from the following file:
StopInfo.cpp