LLDB: lldb_private::python::PythonScript Class Reference
lldb_private::python::PythonScript Class Reference
#include <PythonDataObjects.h>
Public Member Functions
PythonScript (const char *script)
template<typename... Args>
llvm::Expected< PythonObject > operator() (Args &&... args)
Private Member Functions
llvm::Error Init ()
Private Attributes
const char * script
PythonCallable function
Detailed Description
Definition at line 730 of file PythonDataObjects.h.
Constructor & Destructor Documentation
PythonScript()
lldb_private::python::PythonScript::PythonScript (const char * script) inline
Definition at line 737 of file PythonDataObjects.h.
References function, and script.
Member Function Documentation
Init()
Error PythonScript::Init () private
Definition at line 1395 of file PythonDataObjects.cpp.
References lldb_private::python::As(), lldb_private::python::PythonModule::BuiltinsModule(), lldb_private::python::Empty, error(), lldb_private::python::exception(), function, lldb_private::python::PythonObject::get(), lldb_private::python::PythonDictionary::GetItem(), lldb_private::python::RunString(), script, lldb_private::python::PythonDictionary::SetItem(), and lldb_private::python::Take().
Referenced by operator()().
operator()()
template<typename... Args> llvm::Expected< PythonObject > lldb_private::python::PythonScript::operator() (Args &&... args) inline
Definition at line 740 of file PythonDataObjects.h.
References error(), function, and Init().
Member Data Documentation
function
PythonCallable lldb_private::python::PythonScript::function private
Definition at line 732 of file PythonDataObjects.h.
Referenced by Init(), operator()(), and PythonScript().
script
const char* lldb_private::python::PythonScript::script private
Definition at line 731 of file PythonDataObjects.h.
Referenced by Init(), and PythonScript().
The documentation for this class was generated from the following files:
PythonDataObjects.h
PythonDataObjects.cpp