LLDB: lldb_private::CommandReturnObject Class Reference
lldb_private::CommandReturnObject Class Reference
#include <CommandReturnObject.h>
Public Member Functions
CommandReturnObject (bool colors)
~CommandReturnObject ()=default
const std::string & GetCommand () const
Get the command as the user typed it.
void SetCommand (std::string command)
std::string GetInlineDiagnosticString (unsigned indent) const
Format any inline diagnostics with an indentation of indent.
llvm::StringRef GetOutputString () const
std::string GetErrorString (bool with_diagnostics=true) const
Return the errors as a string.
StructuredData::ObjectSP GetErrorData ()
Stream & GetOutputStream ()
Stream & GetErrorStream ()
void SetImmediateOutputFile (lldb::FileSP file_sp)
void SetImmediateErrorFile (lldb::FileSP file_sp)
void SetImmediateOutputStream (const lldb::StreamSP &stream_sp)
void SetImmediateErrorStream (const lldb::StreamSP &stream_sp)
lldb::StreamSP GetImmediateOutputStream () const
lldb::StreamSP GetImmediateErrorStream () const
void Clear ()
void AppendMessage (llvm::StringRef in_string)
void AppendMessageWithFormat (const char *format,...) __attribute__((format(printf
void void AppendNote (llvm::StringRef in_string)
void AppendNoteWithFormat (const char *format,...) __attribute__((format(printf
void void AppendWarning (llvm::StringRef in_string)
void AppendWarningWithFormat (const char *format,...) __attribute__((format(printf
void void AppendError (llvm::StringRef in_string)
void AppendErrorWithFormat (const char *format,...) __attribute__((format(printf
template<typename... Args>
void void AppendMessageWithFormatv (const char *format, Args &&...args)
template<typename... Args>
void AppendNoteWithFormatv (const char *format, Args &&...args)
template<typename... Args>
void AppendWarningWithFormatv (const char *format, Args &&...args)
template<typename... Args>
void AppendErrorWithFormatv (const char *format, Args &&...args)
void SetError (Status error)
void SetError (llvm::Error error)
void SetDiagnosticIndent (std::optional< uint16_t > indent)
std::optional< uint16_t > GetDiagnosticIndent () const
const ValueObjectList & GetValueObjectList () const
ValueObjectList & GetValueObjectList ()
lldb::ReturnStatus GetStatus () const
void SetStatus (lldb::ReturnStatus status)
bool Succeeded () const
bool HasResult () const
bool GetDidChangeProcessState () const
void SetDidChangeProcessState (bool b)
bool GetInteractive () const
void SetInteractive (bool b)
bool GetSuppressImmediateOutput () const
void SetSuppressImmediateOutput (bool b)
Private Types
enum { eStreamStringIndex = 0 , eImmediateStreamIndex = 1 }
Private Attributes
std::string m_command
StreamTee m_out_stream
StreamTee m_err_stream
std::vector< DiagnosticDetail > m_diagnostics
std::optional< uint16_t > m_diagnostic_indent
lldb::ReturnStatus m_status = lldb::eReturnStatusStarted
ValueObjectList m_value_objects
An optionally empty list of values produced by this command.
bool m_did_change_process_state = false
bool m_suppress_immediate_output = false
bool m_interactive = true
If true, then the input handle from the debugger will be hooked up.
bool m_colors
Detailed Description
Definition at line 29 of file CommandReturnObject.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
eStreamStringIndex
eImmediateStreamIndex
Definition at line 192 of file CommandReturnObject.h.
Constructor & Destructor Documentation
CommandReturnObject()
CommandReturnObject::CommandReturnObject (bool colors)
Definition at line 50 of file CommandReturnObject.cpp.
References m_colors, m_err_stream, and m_out_stream.
~CommandReturnObject()
lldb_private::CommandReturnObject::~CommandReturnObject () default
Member Function Documentation
AppendError()
void CommandReturnObject::AppendError (llvm::StringRef in_string)
Definition at line 125 of file CommandReturnObject.cpp.
References lldb::eReturnStatusFailed, error(), GetErrorStream(), and SetStatus().
Referenced by CommandObjectTargetSymbolsAdd::AddModuleSymbols(), CommandObjectTargetSymbolsAdd::AddSymbolsForFile(), CommandObjectTargetSymbolsAdd::AddSymbolsForFrame(), CommandObjectTargetSymbolsAdd::AddSymbolsForStack(), CommandObjectTargetSymbolsAdd::AddSymbolsForUUID(), AppendErrorWithFormatv(), lldb_private::CommandInterpreter::BuildAliasResult(), lldb_private::CommandObject::CheckRequirements(), CheckTargetForWatchpointOperations(), lldb_private::ScriptInterpreter::CollectDataForBreakpointCommandCallback(), lldb_private::ScriptInterpreter::CollectDataForWatchpointCommandCallback(), CommandObjectTypeCategoryDisable::CommandObjectTypeCategoryDisable(), CommandObjectSourceList::DisplayFunctionSource(), CommandObjectBreakpointAddAddress::DoExecute(), CommandObjectBreakpointAddException::DoExecute(), CommandObjectBreakpointAddFile::DoExecute(), CommandObjectBreakpointAddName::DoExecute(), CommandObjectBreakpointAddPattern::DoExecute(), CommandObjectBreakpointAddScripted::DoExecute(), CommandObjectBreakpointClear::DoExecute(), CommandObjectBreakpointCommandDelete::DoExecute(), CommandObjectBreakpointCommandList::DoExecute(), CommandObjectBreakpointDelete::DoExecute(), CommandObjectBreakpointEnable::DoExecute(), CommandObjectBreakpointList::DoExecute(), CommandObjectBreakpointNameAdd::DoExecute(), CommandObjectBreakpointNameConfigure::DoExecute(), CommandObjectBreakpointNameDelete::DoExecute(), CommandObjectBreakpointRead::DoExecute(), CommandObjectBreakpointSet::DoExecute(), CommandObjectCommandsContainerAdd::DoExecute(), CommandObjectCommandsContainerDelete::DoExecute(), CommandObjectCommandsDelete::DoExecute(), CommandObjectCommandsScriptAdd::DoExecute(), CommandObjectCommandsScriptImport::DoExecute(), CommandObjectCommandsSource::DoExecute(), CommandObjectCommandsUnalias::DoExecute(), CommandObjectDiagnosticsDump::DoExecute(), CommandObjectFrameDiagnose::DoExecute(), CommandObjectFrameRecognizerInfo::DoExecute(), CommandObjectFrameSelect::DoExecute(), CommandObjectLogEnable::DoExecute(), CommandObjectLogTimerDisable::DoExecute(), CommandObjectLogTimerDump::DoExecute(), CommandObjectLogTimerEnable::DoExecute(), CommandObjectLogTimerIncrement::DoExecute(), CommandObjectLogTimerReset::DoExecute(), CommandObjectMemoryFind::DoExecute(), CommandObjectMemoryHistory::DoExecute(), CommandObjectMemoryRead::DoExecute(), CommandObjectMemoryRegion::DoExecute(), CommandObjectMemoryTagRead::DoExecute(), CommandObjectMemoryTagWrite::DoExecute(), CommandObjectMemoryWrite::DoExecute(), CommandObjectMultiwordObjC_TaggedPointer_Info::DoExecute(), CommandObjectObjC_ClassTable_Dump::DoExecute(), CommandObjectPlatformConnect::DoExecute(), CommandObjectPlatformDisconnect::DoExecute(), CommandObjectPlatformFClose::DoExecute(), CommandObjectPlatformFOpen::DoExecute(), CommandObjectPlatformFRead::DoExecute(), CommandObjectPlatformFWrite::DoExecute(), CommandObjectPlatformInstall::DoExecute(), CommandObjectPlatformList::DoExecute(), CommandObjectPlatformMkDir::DoExecute(), CommandObjectPlatformProcessAttach::DoExecute(), CommandObjectPlatformProcessInfo::DoExecute(), CommandObjectPlatformProcessLaunch::DoExecute(), CommandObjectPlatformProcessList::DoExecute(), CommandObjectPlatformSelect::DoExecute(), CommandObjectPlatformSettings::DoExecute(), CommandObjectPlatformShell::DoExecute(), CommandObjectPlatformStatus::DoExecute(), CommandObjectPluginLoad::DoExecute(), CommandObjectProcessAttach::DoExecute(), CommandObjectProcessConnect::DoExecute(), CommandObjectProcessContinue::DoExecute(), CommandObjectProcessHandle::DoExecute(), CommandObjectProcessInterrupt::DoExecute(), CommandObjectProcessKDPPacketSend::DoExecute(), CommandObjectProcessKill::DoExecute(), CommandObjectProcessLaunch::DoExecute(), CommandObjectProcessSaveCore::DoExecute(), CommandObjectProcessStatus::DoExecute(), CommandObjectProcessTraceStop::DoExecute(), CommandObjectProtocolServerGet::DoExecute(), CommandObjectProtocolServerStart::DoExecute(), CommandObjectProtocolServerStop::DoExecute(), CommandObjectPythonFunction::DoExecute(), CommandObjectRegisterRead::DoExecute(), CommandObjectRegisterWrite::DoExecute(), CommandObjectScriptingObjectParsed::DoExecute(), CommandObjectScriptingObjectRaw::DoExecute(), CommandObjectScriptingRun::DoExecute(), CommandObjectSessionHistory::DoExecute(), CommandObjectSettingsAppend::DoExecute(), CommandObjectSettingsClear::DoExecute(), CommandObjectSettingsInsertAfter::DoExecute(), CommandObjectSettingsInsertBefore::DoExecute(), CommandObjectSettingsRemove::DoExecute(), CommandObjectSettingsReplace::DoExecute(), CommandObjectSettingsShow::DoExecute(), CommandObjectSettingsWrite::DoExecute(), CommandObjectSourceInfo::DoExecute(), CommandObjectStatsDisable::DoExecute(), CommandObjectStatsEnable::DoExecute(), CommandObjectTargetCreate::DoExecute(), CommandObjectTargetDelete::DoExecute(), CommandObjectTargetFrameProviderClear::DoExecute(), CommandObjectTargetFrameProviderRemove::DoExecute(), CommandObjectTargetModulesAdd::DoExecute(), CommandObjectTargetModulesDumpClangAST::DoExecute(), CommandObjectTargetModulesDumpClangPCMInfo::DoExecute(), CommandObjectTargetModulesDumpLineTable::DoExecute(), CommandObjectTargetModulesDumpObjfile::DoExecute(), CommandObjectTargetModulesDumpSections::DoExecute(), CommandObjectTargetModulesDumpSeparateDebugInfoFiles::DoExecute(), CommandObjectTargetModulesDumpSymfile::DoExecute(), CommandObjectTargetModulesDumpSymtab::DoExecute(), CommandObjectTargetModulesList::DoExecute(), CommandObjectTargetModulesLoad::DoExecute(), CommandObjectTargetModulesLookup::DoExecute(), CommandObjectTargetModulesSearchPathsAdd::DoExecute(), CommandObjectTargetModulesSearchPathsInsert::DoExecute(), CommandObjectTargetModulesSearchPathsQuery::DoExecute(), CommandObjectTargetModulesShowUnwind::DoExecute(), CommandObjectTargetSelect::DoExecute(), CommandObjectTargetSymbolsAdd::DoExecute(), CommandObjectTargetVariable::DoExecute(), CommandObjectThreadContinue::DoExecute(), CommandObjectThreadPlanList::DoExecute(), CommandObjectThreadReturn::DoExecute(), CommandObjectThreadSelect::DoExecute(), CommandObjectThreadStepWithTypeAndScope::DoExecute(), CommandObjectThreadUntil::DoExecute(), CommandObjectTraceDumpFunctionCalls::DoExecute(), CommandObjectTraceDumpInstructions::DoExecute(), CommandObjectTraceLoad::DoExecute(), CommandObjectTraceSave::DoExecute(), CommandObjectTraceSchema::DoExecute(), CommandObjectTypeFormatterDelete::DoExecute(), CommandObjectTypeSynthAdd::DoExecute(), CommandObjectWatchpointCommandDelete::DoExecute(), CommandObjectWatchpointCommandList::DoExecute(), CommandObjectWatchpointDelete::DoExecute(), CommandObjectWatchpointDisable::DoExecute(), CommandObjectWatchpointEnable::DoExecute(), CommandObjectWatchpointIgnore::DoExecute(), CommandObjectWatchpointList::DoExecute(), CommandObjectWatchpointModify::DoExecute(), lldb_private::CommandObjectApropos::DoExecute(), lldb_private::CommandObjectDisassemble::DoExecute(), lldb_private::CommandObjectDWIMPrint::DoExecute(), lldb_private::CommandObjectGUI::DoExecute(), lldb_private::CommandObjectHelp::DoExecute(), lldb_private::CommandObjectQuit::DoExecute(), lldb_private::CommandObjectRegexCommand::DoExecute(), sddarwinlog_private::EnableCommand::DoExecute(), CommandObjectTraceStop::DoExecuteOnThreads(), CommandObjectSourceInfo::DumpLinesForFrame(), lldb_private::CommandObjectMultiword::Execute(), lldb_private::CommandObjectProxy::Execute(), CommandObjectTypeSummaryAdd::Execute_StringSummary(), lldb_private::ScriptInterpreterLua::ExecuteOneLine(), GetDefaultFile(), lldb::SBCommandInterpreter::HandleCommand(), lldb_private::CommandInterpreter::HandleCommand(), lldb::SBCommandInterpreter::HandleCommandsFromFile(), CommandObjectThreadException::HandleOneThread(), CommandObjectThreadSiginfo::HandleOneThread(), lldb_private::CommandObject::ParseOptionsAndNotify(), lldb::SBCommandInterpreter::ResolveCommand(), lldb_private::CommandInterpreter::ResolveCommandImpl(), lldb_private::CommandInterpreter::SaveTranscript(), lldb::SBCommandReturnObject::SetError(), SetError(), lldb::SBCommandInterpreter::SourceInitFileInCurrentWorkingDirectory(), lldb::SBCommandInterpreter::SourceInitFileInGlobalDirectory(), lldb::SBCommandInterpreter::SourceInitFileInHomeDirectory(), lldb_private::CommandObjectMultiwordBreakpoint::VerifyIDs(), and CommandObjectTypeFormat::~CommandObjectTypeFormat().
AppendErrorWithFormat()
void CommandReturnObject::AppendErrorWithFormat (const char * format, ...)
Definition at line 53 of file CommandReturnObject.cpp.
References DumpStringToStreamWithNewline(), lldb::eReturnStatusFailed, error(), GetErrorStream(), lldb_private::StreamString::GetString(), lldb_private::Stream::PrintfVarArg(), and SetStatus().
Referenced by CommandObjectTargetSymbolsAdd::AddModuleSymbols(), CommandObjectTargetSymbolsAdd::AddSymbolsForFrame(), CommandObjectTargetSymbolsAdd::AddSymbolsForStack(), lldb_private::CommandInterpreter::BuildAliasCommandArgs(), lldb_private::CommandInterpreter::BuildAliasResult(), CopyOverBreakpointOptions(), CommandObjectScriptingObjectParsed::Create(), CommandObjectSourceList::DisplayFunctionSource(), CommandObjectBreakpointAddException::DoExecute(), CommandObjectBreakpointAddName::DoExecute(), CommandObjectBreakpointAddPattern::DoExecute(), CommandObjectBreakpointAddScripted::DoExecute(), CommandObjectBreakpointCommandDelete::DoExecute(), CommandObjectBreakpointCommandList::DoExecute(), CommandObjectBreakpointNameConfigure::DoExecute(), CommandObjectBreakpointSet::DoExecute(), CommandObjectBreakpointWrite::DoExecute(), CommandObjectCommandsContainerAdd::DoExecute(), CommandObjectCommandsContainerDelete::DoExecute(), CommandObjectCommandsDelete::DoExecute(), CommandObjectCommandsScriptAdd::DoExecute(), CommandObjectCommandsScriptDelete::DoExecute(), CommandObjectCommandsScriptImport::DoExecute(), CommandObjectCommandsSource::DoExecute(), CommandObjectCommandsUnalias::DoExecute(), CommandObjectDiagnosticsDump::DoExecute(), CommandObjectFrameRecognizerAdd::DoExecute(), CommandObjectFrameRecognizerInfo::DoExecute(), CommandObjectFrameSelect::DoExecute(), CommandObjectLogDisable::DoExecute(), CommandObjectLogDump::DoExecute(), CommandObjectLogEnable::DoExecute(), CommandObjectLogTimerDisable::DoExecute(), CommandObjectLogTimerDump::DoExecute(), CommandObjectLogTimerEnable::DoExecute(), CommandObjectLogTimerIncrement::DoExecute(), CommandObjectLogTimerReset::DoExecute(), CommandObjectMemoryHistory::DoExecute(), CommandObjectMemoryRead::DoExecute(), CommandObjectMemoryRegion::DoExecute(), CommandObjectMemoryTagWrite::DoExecute(), CommandObjectMemoryWrite::DoExecute(), CommandObjectMultiwordItaniumABI_Demangle::DoExecute(), CommandObjectPlatformConnect::DoExecute(), CommandObjectPlatformDisconnect::DoExecute(), CommandObjectPlatformInstall::DoExecute(), CommandObjectPlatformProcessInfo::DoExecute(), CommandObjectPlatformProcessLaunch::DoExecute(), CommandObjectPlatformProcessList::DoExecute(), CommandObjectProcessAttach::DoExecute(), CommandObjectProcessConnect::DoExecute(), CommandObjectProcessContinue::DoExecute(), CommandObjectProcessDetach::DoExecute(), CommandObjectProcessGDBRemotePacketMonitor::DoExecute(), CommandObjectProcessGDBRemotePacketSend::DoExecute(), CommandObjectProcessGDBRemotePacketXferSize::DoExecute(), CommandObjectProcessGDBRemoteSpeedTest::DoExecute(), CommandObjectProcessHandle::DoExecute(), CommandObjectProcessInterrupt::DoExecute(), CommandObjectProcessKDPPacketSend::DoExecute(), CommandObjectProcessKill::DoExecute(), CommandObjectProcessLoad::DoExecute(), CommandObjectProcessMinidumpDump::DoExecute(), CommandObjectProcessSaveCore::DoExecute(), CommandObjectProcessSignal::DoExecute(), CommandObjectProcessUnload::DoExecute(), CommandObjectRegisterRead::DoExecute(), CommandObjectRegisterWrite::DoExecute(), CommandObjectSettingsList::DoExecute(), CommandObjectSettingsWrite::DoExecute(), CommandObjectSourceList::DoExecute(), CommandObjectTargetCreate::DoExecute(), CommandObjectTargetDelete::DoExecute(), CommandObjectTargetFrameProviderRemove::DoExecute(), CommandObjectTargetModulesAdd::DoExecute(), CommandObjectTargetModulesDumpClangPCMInfo::DoExecute(), CommandObjectTargetModulesList::DoExecute(), CommandObjectTargetModulesLoad::DoExecute(), CommandObjectTargetModulesSearchPathsInsert::DoExecute(), CommandObjectTargetModulesShowUnwind::DoExecute(), CommandObjectTargetSelect::DoExecute(), CommandObjectTargetStopHookEnableDisable::DoExecute(), CommandObjectTargetSymbolsAdd::DoExecute(), CommandObjectTargetVariable::DoExecute(), CommandObjectThreadContinue::DoExecute(), CommandObjectThreadJump::DoExecute(), CommandObjectThreadPlanDiscard::DoExecute(), CommandObjectThreadPlanPrune::DoExecute(), CommandObjectThreadReturn::DoExecute(), CommandObjectThreadSelect::DoExecute(), CommandObjectThreadStepWithTypeAndScope::DoExecute(), CommandObjectThreadUntil::DoExecute(), CommandObjectTraceDump::DoExecute(), CommandObjectTraceLoad::DoExecute(), CommandObjectTraceSchema::DoExecute(), CommandObjectTypeFormatterDelete::DoExecute(), CommandObjectTypeFormatterList< FormatterType >::DoExecute(), CommandObjectWatchpointCommandDelete::DoExecute(), CommandObjectWatchpointCommandList::DoExecute(), CommandObjectWithFrameRecognizerArg::DoExecute(), lldb_private::CommandObjectDisassemble::DoExecute(), lldb_private::CommandObjectIterateOverThreads::DoExecute(), lldb_private::CommandObjectMultipleThreads::DoExecute(), lldb_private::ctf::CommandObjectThreadTraceExportCTF::DoExecute(), CommandObjectFrameRecognizerDelete::DoExecuteWithId(), CommandObjectFrameRecognizerDisable::DoExecuteWithId(), CommandObjectFrameRecognizerEnable::DoExecuteWithId(), DoPluginEnableDisable(), CommandObjectSourceInfo::DumpLinesForAddress(), CommandObjectSourceInfo::DumpLinesForFile(), CommandObjectSourceInfo::DumpLinesInFunctions(), lldb_private::CommandObjectMultiword::Execute(), CommandObjectTypeSummaryAdd::Execute_StringSummary(), CommandObjectTypeCategoryDisable::CommandOptions::GetDefinitions(), GetSingleThreadFromArgs(), CommandObjectTypeLookup::GuessLanguage(), lldb_private::CommandInterpreter::HandleCommand(), lldb_private::CommandInterpreter::HandleCommands(), lldb::SBCommandInterpreter::HandleCommandsFromFile(), lldb_private::CommandInterpreter::HandleCommandsFromFile(), CommandObjectThreadBacktrace::HandleOneThread(), CommandObjectThreadException::HandleOneThread(), CommandObjectThreadInfo::HandleOneThread(), CommandObjectThreadSiginfo::HandleOneThread(), lldb_private::CommandInterpreter::ResolveCommandImpl(), CommandObjectProcessLaunchOrAttach::StopProcessIfNecessary(), and lldb_private::CommandObjectMultiwordBreakpoint::VerifyIDs().
AppendErrorWithFormatv()
template<typename... Args> void lldb_private::CommandReturnObject::AppendErrorWithFormatv (const char * format, Args &&... args) inline
Definition at line 151 of file CommandReturnObject.h.
References AppendError().
Referenced by lldb_private::CommandObjectIterateOverThreads::BucketThread(), CommandObjectBreakpointAddAddress::DoExecute(), CommandObjectBreakpointAddFile::DoExecute(), CommandObjectBreakpointDelete::DoExecute(), CommandObjectBreakpointEnable::DoExecute(), CommandObjectBreakpointNameConfigure::DoExecute(), CommandObjectCommandsScriptAdd::DoExecute(), CommandObjectMemoryTagRead::DoExecute(), CommandObjectMemoryTagWrite::DoExecute(), CommandObjectMultiwordObjC_TaggedPointer_Info::DoExecute(), CommandObjectPlatformDisconnect::DoExecute(), CommandObjectPlatformFClose::DoExecute(), CommandObjectPlatformFRead::DoExecute(), CommandObjectPlatformFWrite::DoExecute(), CommandObjectPlatformProcessInfo::DoExecute(), CommandObjectPlatformProcessList::DoExecute(), CommandObjectProcessContinue::DoExecute(), CommandObjectProcessSaveCore::DoExecute(), CommandObjectProtocolServerGet::DoExecute(), CommandObjectProtocolServerStart::DoExecute(), CommandObjectProtocolServerStop::DoExecute(), CommandObjectRegisterRead::DoExecute(), CommandObjectTargetCreate::DoExecute(), CommandObjectTargetVariable::DoExecute(), CommandObjectThreadStepWithTypeAndScope::DoExecute(), lldb_private::CommandObjectDWIMPrint::DoExecute(), lldb_private::ctf::CommandObjectThreadTraceExportCTF::DoExecute(), lldb_private::CommandObjectParsed::Execute(), lldb_private::ScriptInterpreterLua::ExecuteOneLine(), lldb_private::CommandInterpreter::HandleCommands(), lldb_private::CommandInterpreter::HandleCommandsFromFile(), and lldb_private::CommandInterpreter::SaveTranscript().
AppendMessage()
void CommandReturnObject::AppendMessage (llvm::StringRef in_string)
Definition at line 107 of file CommandReturnObject.cpp.
References GetOutputStream().
Referenced by lldb::SBCommandReturnObject::AppendMessage(), AppendMessageWithFormatv(), CommandObjectBreakpointDelete::DoExecute(), CommandObjectBreakpointList::DoExecute(), CommandObjectBreakpointNameList::DoExecute(), CommandObjectBreakpointRead::DoExecute(), CommandObjectMemoryFind::DoExecute(), CommandObjectMemoryTagRead::DoExecute(), CommandObjectProcessAttach::DoExecute(), CommandObjectProcessContinue::DoExecute(), CommandObjectProcessKDPPacketSend::DoExecute(), CommandObjectProcessLaunch::DoExecute(), CommandObjectTargetFrameProviderList::DoExecute(), CommandObjectThreadContinue::DoExecute(), CommandObjectThreadStepWithTypeAndScope::DoExecute(), CommandObjectThreadUntil::DoExecute(), CommandObjectTraceSchema::DoExecute(), CommandObjectWatchpointDelete::DoExecute(), CommandObjectWatchpointList::DoExecute(), lldb_private::CommandObjectIterateOverThreads::DoExecute(), CommandObjectMemoryRegion::DumpRegion(), lldb_private::CommandInterpreter::GetHelp(), lldb_private::CommandInterpreter::HandleCommands(), and lldb::SBCommandReturnObject::PutCString().
AppendMessageWithFormat()
void CommandReturnObject::AppendMessageWithFormat (const char * format, ...)
Definition at line 71 of file CommandReturnObject.cpp.
References GetOutputStream(), lldb_private::StreamString::GetString(), and lldb_private::Stream::PrintfVarArg().
Referenced by CommandObjectTargetSymbolsAdd::AddModuleSymbols(), CommandObjectSourceList::DisplayFunctionSource(), CommandObjectBreakpointCommandList::DoExecute(), CommandObjectBreakpointDelete::DoExecute(), CommandObjectBreakpointEnable::DoExecute(), CommandObjectBreakpointNameList::DoExecute(), CommandObjectMemoryFind::DoExecute(), CommandObjectMultiwordItaniumABI_Demangle::DoExecute(), CommandObjectPlatformFClose::DoExecute(), CommandObjectPlatformFOpen::DoExecute(), CommandObjectPlatformFRead::DoExecute(), CommandObjectPlatformFWrite::DoExecute(), CommandObjectPlatformProcessList::DoExecute(), CommandObjectProcessAttach::DoExecute(), CommandObjectProcessContinue::DoExecute(), CommandObjectProcessLaunch::DoExecute(), CommandObjectProcessLoad::DoExecute(), CommandObjectProcessSaveCore::DoExecute(), CommandObjectProcessStatus::DoExecute(), CommandObjectProcessUnload::DoExecute(), CommandObjectTargetCreate::DoExecute(), CommandObjectTargetFrameProviderList::DoExecute(), CommandObjectTargetFrameProviderRegister::DoExecute(), CommandObjectTargetFrameProviderRemove::DoExecute(), CommandObjectTargetModulesLoad::DoExecute(), CommandObjectThreadContinue::DoExecute(), CommandObjectThreadUntil::DoExecute(), CommandObjectWatchpointCommandList::DoExecute(), CommandObjectWatchpointDelete::DoExecute(), CommandObjectWatchpointDisable::DoExecute(), CommandObjectWatchpointEnable::DoExecute(), CommandObjectWatchpointIgnore::DoExecute(), CommandObjectWatchpointList::DoExecute(), CommandObjectWatchpointModify::DoExecute(), lldb_private::CommandObjectApropos::DoExecute(), lldb_private::CommandObjectVersion::DoExecute(), CommandObjectMemoryRegion::DumpRegion(), lldb_private::CommandInterpreter::GetHelp(), lldb_private::CommandInterpreter::HandleCommands(), lldb_private::CommandInterpreter::ResolveCommand(), and lldb_private::CommandInterpreter::SaveTranscript().
AppendMessageWithFormatv()
template<typename... Args> void void lldb_private::CommandReturnObject::AppendMessageWithFormatv (const char * format, Args &&... args) inline
Definition at line 136 of file CommandReturnObject.h.
References AppendMessage(), and AppendMessageWithFormatv().
Referenced by AppendMessageWithFormatv(), CommandObjectMemoryTagRead::DoExecute(), CommandObjectPlatformProcessList::DoExecute(), CommandObjectProtocolServerGet::DoExecute(), CommandObjectProtocolServerStart::DoExecute(), CommandObjectStatsDump::DoExecute(), CommandObjectTargetCreate::DoExecute(), CommandObjectTraceLoad::DoExecute(), CommandObjectTraceSave::DoExecute(), lldb_private::CommandObjectApropos::DoExecute(), CommandObjectMemoryRegion::DumpRegion(), and lldb_private::CommandInterpreter::HandleCommands().
AppendNote()
void CommandReturnObject::AppendNote (llvm::StringRef in_string)
Definition at line 113 of file CommandReturnObject.cpp.
References GetOutputStream(), and note().
Referenced by AppendNoteWithFormatv(), CommandObjectSourceList::DoExecute(), and lldb_private::CommandObjectDWIMPrint::DoExecute().
AppendNoteWithFormat()
void CommandReturnObject::AppendNoteWithFormat (const char * format, ...)
Definition at line 83 of file CommandReturnObject.cpp.
References GetOutputStream(), lldb_private::StreamString::GetString(), note(), and lldb_private::Stream::PrintfVarArg().
AppendNoteWithFormatv()
template<typename... Args> void lldb_private::CommandReturnObject::AppendNoteWithFormatv (const char * format, Args &&... args) inline
Definition at line 141 of file CommandReturnObject.h.
References AppendNote().
Referenced by CommandObjectSourceList::DoExecute(), and lldb_private::CommandObjectDWIMPrint::DoExecute().
AppendWarning()
void CommandReturnObject::AppendWarning (llvm::StringRef in_string)
Definition at line 119 of file CommandReturnObject.cpp.
References GetErrorStream(), and warning().
Referenced by CommandObjectTargetSymbolsAdd::AddModuleSymbols(), sddarwinlog_private::EnableCommand::AppendStrictSourcesWarning(), lldb::SBCommandReturnObject::AppendWarning(), AppendWarningWithFormatv(), CommandObjectBreakpointAddName::DoExecute(), CommandObjectBreakpointSet::DoExecute(), CommandObjectFrameRecognizerAdd::DoExecute(), CommandObjectMemoryRead::DoExecute(), CommandObjectProcessLaunch::DoExecute(), CommandObjectStatsDump::DoExecute(), CommandObjectThreadJump::DoExecute(), CommandObjectThreadReturn::DoExecute(), CommandObjectThreadStepWithTypeAndScope::DoExecute(), lldb_private::CommandObjectDisassemble::GetNameRanges(), and lldb_private::CommandInterpreter::SourceInitFileCwd().
AppendWarningWithFormat()
void CommandReturnObject::AppendWarningWithFormat (const char * format, ...)
Definition at line 95 of file CommandReturnObject.cpp.
References GetErrorStream(), lldb_private::StreamString::GetString(), lldb_private::Stream::PrintfVarArg(), and warning().
Referenced by CommandObjectTargetSymbolsAdd::AddModuleSymbols(), CommandObjectMemoryRead::DoExecute(), CommandObjectProcessAttach::DoExecute(), CommandObjectSourceInfo::DoExecute(), CommandObjectTargetModulesDumpClangAST::DoExecute(), CommandObjectTargetModulesDumpLineTable::DoExecute(), CommandObjectTargetModulesDumpObjfile::DoExecute(), CommandObjectTargetModulesDumpSections::DoExecute(), CommandObjectTargetModulesDumpSeparateDebugInfoFiles::DoExecute(), CommandObjectTargetModulesDumpSymfile::DoExecute(), CommandObjectTargetModulesDumpSymtab::DoExecute(), CommandObjectTargetModulesLookup::DoExecute(), lldb_private::CommandObjectDisassemble::DoExecute(), CommandObjectSourceInfo::DumpLinesInFunctions(), and WarnOnPotentialUnquotedUnsignedType().
AppendWarningWithFormatv()
template<typename... Args> void lldb_private::CommandReturnObject::AppendWarningWithFormatv (const char * format, Args &&... args) inline
Definition at line 146 of file CommandReturnObject.h.
References AppendWarning().
Clear()
void CommandReturnObject::Clear ()
Definition at line 189 of file CommandReturnObject.cpp.
References lldb_private::StreamString::Clear(), lldb::eReturnStatusStarted, eStreamStringIndex, m_diagnostics, m_did_change_process_state, m_err_stream, m_interactive, m_out_stream, m_status, and m_suppress_immediate_output.
Referenced by lldb::SBCommandReturnObject::Clear(), CommandObjectBreakpointDelete::DoExecute(), and CommandObjectProcessContinue::DoExecute().
GetCommand()
const std::string & lldb_private::CommandReturnObject::GetCommand () const inline
Get the command as the user typed it.
Empty string if commands were run on behalf of lldb.
Definition at line 37 of file CommandReturnObject.h.
References m_command.
GetDiagnosticIndent()
std::optional< uint16_t > lldb_private::CommandReturnObject::GetDiagnosticIndent () const inline
Definition at line 163 of file CommandReturnObject.h.
References m_diagnostic_indent.
GetDidChangeProcessState()
bool CommandReturnObject::GetDidChangeProcessState () const
Definition at line 204 of file CommandReturnObject.cpp.
References m_did_change_process_state.
Referenced by lldb_private::CommandInterpreter::HandleCommands().
GetErrorData()
StructuredData::ObjectSP CommandReturnObject::GetErrorData ()
Definition at line 172 of file CommandReturnObject.cpp.
References m_diagnostics, and lldb_private::Serialize().
GetErrorStream()
Stream & lldb_private::CommandReturnObject::GetErrorStream () inline
Definition at line 69 of file CommandReturnObject.h.
References eStreamStringIndex, and m_err_stream.
Referenced by CommandObjectTargetSymbolsAdd::AddModuleSymbols(), AppendError(), AppendErrorWithFormat(), AppendWarning(), AppendWarningWithFormat(), CommandObjectFrameSelect::DoExecute(), CommandObjectLogDisable::DoExecute(), CommandObjectLogDump::DoExecute(), CommandObjectLogEnable::DoExecute(), CommandObjectSourceInfo::DoExecute(), CommandObjectTargetModulesDumpLineTable::DoExecute(), CommandObjectTargetModulesDumpObjfile::DoExecute(), CommandObjectTargetModulesDumpSections::DoExecute(), CommandObjectTargetModulesDumpSeparateDebugInfoFiles::DoExecute(), CommandObjectTargetModulesDumpSymfile::DoExecute(), CommandObjectTargetModulesDumpSymtab::DoExecute(), CommandObjectTargetModulesList::DoExecute(), CommandObjectTargetModulesLookup::DoExecute(), CommandObjectTargetVariable::DoExecute(), lldb_private::CommandObjectDisassemble::DoExecute(), lldb_private::CommandObjectDWIMPrint::DoExecute(), lldb_private::CommandObjectRegexCommand::DoExecute(), and CommandObjectTargetModulesLookup::LookupInModule().
GetErrorString()
std::string CommandReturnObject::GetErrorString (bool with_diagnostics = true) const
Return the errors as a string.
If with_diagnostics is true, all diagnostics are also rendered into the string. Otherwise the expectation is that they are fetched with GetInlineDiagnosticString().
Definition at line 161 of file CommandReturnObject.cpp.
References eStreamStringIndex, lldb_private::StreamString::GetString(), m_colors, m_diagnostics, m_err_stream, and lldb_private::RenderDiagnosticDetails().
Referenced by lldb_private::mcp::CommandTool::Call(), CompleteLineEntry(), lldb_private::Debugger::Destroy(), lldb::SBCommandReturnObject::GetErrorSize(), lldb_private::CommandInterpreter::HandleCommand(), and lldb_private::CommandInterpreter::HandleCommands().
GetImmediateErrorStream()
lldb::StreamSP lldb_private::CommandReturnObject::GetImmediateErrorStream () const inline
Definition at line 109 of file CommandReturnObject.h.
References eImmediateStreamIndex, and m_err_stream.
Referenced by lldb_private::BreakpointOptions::BreakpointOptionsCallbackFunction(), and lldb_private::CommandInterpreter::HandleCommands().
GetImmediateOutputStream()
lldb::StreamSP lldb_private::CommandReturnObject::GetImmediateOutputStream () const inline
Definition at line 105 of file CommandReturnObject.h.
References eImmediateStreamIndex, and m_out_stream.
Referenced by lldb_private::BreakpointOptions::BreakpointOptionsCallbackFunction(), CommandObjectProcessGDBRemoteSpeedTest::DoExecute(), and lldb_private::CommandInterpreter::HandleCommands().
GetInlineDiagnosticString()
std::string CommandReturnObject::GetInlineDiagnosticString (unsigned indent) const
Format any inline diagnostics with an indentation of indent.
Definition at line 151 of file CommandReturnObject.cpp.
References eImmediateStreamIndex, lldb_private::StreamString::GetString(), m_colors, m_diagnostics, m_err_stream, and lldb_private::RenderDiagnosticDetails().
GetInteractive()
bool CommandReturnObject::GetInteractive () const
Definition at line 212 of file CommandReturnObject.cpp.
References m_interactive.
Referenced by lldb_private::CommandInterpreter::HandleCommands().
GetOutputStream()
Stream & lldb_private::CommandReturnObject::GetOutputStream () inline
Definition at line 59 of file CommandReturnObject.h.
References eStreamStringIndex, and m_out_stream.
Referenced by AppendMessage(), AppendMessageWithFormat(), AppendNote(), AppendNoteWithFormat(), CommandObjectTypeCategoryDefine::CommandObjectTypeCategoryDefine(), CommandObjectTypeSynth::CommandObjectTypeSynth(), CommandObjectSourceList::DisplayFunctionSource(), CommandObjectBreakpointAddAddress::DoExecute(), CommandObjectBreakpointAddException::DoExecute(), CommandObjectBreakpointAddFile::DoExecute(), CommandObjectBreakpointAddName::DoExecute(), CommandObjectBreakpointAddPattern::DoExecute(), CommandObjectBreakpointAddScripted::DoExecute(), CommandObjectBreakpointClear::DoExecute(), CommandObjectBreakpointCommandList::DoExecute(), CommandObjectBreakpointList::DoExecute(), CommandObjectBreakpointRead::DoExecute(), CommandObjectBreakpointSet::DoExecute(), CommandObjectCommandsScriptDelete::DoExecute(), CommandObjectDiagnosticsDump::DoExecute(), CommandObjectFormatterInfo< FormatterType >::DoExecute(), CommandObjectFrameDiagnose::DoExecute(), CommandObjectFrameInfo::DoExecute(), CommandObjectFrameRecognizerInfo::DoExecute(), CommandObjectFrameRecognizerList::DoExecute(), CommandObjectFrameSelect::DoExecute(), CommandObjectLogList::DoExecute(), CommandObjectLogTimerDisable::DoExecute(), CommandObjectLogTimerDump::DoExecute(), CommandObjectMemoryFind::DoExecute(), CommandObjectMemoryHistory::DoExecute(), CommandObjectMemoryRead::DoExecute(), CommandObjectMemoryWrite::DoExecute(), CommandObjectMultiwordObjC_TaggedPointer_Info::DoExecute(), CommandObjectObjC_ClassTable_Dump::DoExecute(), CommandObjectPlatformConnect::DoExecute(), CommandObjectPlatformDisconnect::DoExecute(), CommandObjectPlatformList::DoExecute(), CommandObjectPlatformProcessInfo::DoExecute(), CommandObjectPlatformProcessLaunch::DoExecute(), CommandObjectPlatformProcessList::DoExecute(), CommandObjectPlatformSelect::DoExecute(), CommandObjectPlatformShell::DoExecute(), CommandObjectPlatformStatus::DoExecute(), CommandObjectProcessConnect::DoExecute(), CommandObjectProcessGDBRemotePacketHistory::DoExecute(), CommandObjectProcessGDBRemotePacketMonitor::DoExecute(), CommandObjectProcessGDBRemotePacketSend::DoExecute(), CommandObjectProcessGDBRemoteSpeedTest::DoExecute(), CommandObjectProcessHandle::DoExecute(), CommandObjectProcessMinidumpDump::DoExecute(), CommandObjectProcessStatus::DoExecute(), CommandObjectRegisterRead::DoExecute(), CommandObjectScriptingExtensionList::DoExecute(), CommandObjectSessionHistory::DoExecute(), CommandObjectSettingsList::DoExecute(), CommandObjectSettingsShow::DoExecute(), CommandObjectSourceCacheDump::DoExecute(), CommandObjectSourceInfo::DoExecute(), CommandObjectSourceList::DoExecute(), CommandObjectTargetDelete::DoExecute(), CommandObjectTargetDumpSectionLoadList::DoExecute(), CommandObjectTargetDumpTypesystem::DoExecute(), CommandObjectTargetFrameProviderList::DoExecute(), CommandObjectTargetList::DoExecute(), CommandObjectTargetModulesDumpClangAST::DoExecute(), CommandObjectTargetModulesDumpClangPCMInfo::DoExecute(), CommandObjectTargetModulesDumpLineTable::DoExecute(), CommandObjectTargetModulesDumpObjfile::DoExecute(), CommandObjectTargetModulesDumpSections::DoExecute(), CommandObjectTargetModulesDumpSeparateDebugInfoFiles::DoExecute(), CommandObjectTargetModulesDumpSymfile::DoExecute(), CommandObjectTargetModulesDumpSymtab::DoExecute(), CommandObjectTargetModulesList::DoExecute(), CommandObjectTargetModulesLookup::DoExecute(), CommandObjectTargetModulesSearchPathsList::DoExecute(), CommandObjectTargetModulesSearchPathsQuery::DoExecute(), CommandObjectTargetModulesShowUnwind::DoExecute(), CommandObjectTargetSelect::DoExecute(), CommandObjectTargetShowLaunchEnvironment::DoExecute(), CommandObjectTargetStopHookList::DoExecute(), CommandObjectTargetVariable::DoExecute(), CommandObjectThreadList::DoExecute(), CommandObjectThreadPlanList::DoExecute(), CommandObjectThreadReturn::DoExecute(), CommandObjectTraceDumpFunctionCalls::DoExecute(), CommandObjectTraceDumpInstructions::DoExecute(), CommandObjectTypeFormatterList< FormatterType >::DoExecute(), CommandObjectWatchpointCommandList::DoExecute(), CommandObjectWatchpointList::DoExecute(), lldb_private::CommandObjectApropos::DoExecute(), lldb_private::CommandObjectDisassemble::DoExecute(), lldb_private::CommandObjectDWIMPrint::DoExecute(), lldb_private::CommandObjectHelp::DoExecute(), lldb_private::CommandObjectIterateOverThreads::DoExecute(), lldb_private::CommandObjectRegexCommand::DoExecute(), lldb_private::CommandObjectVersion::DoExecute(), sddarwinlog_private::StatusCommand::DoExecute(), CommandObjectThreadBacktrace::DoExtendedBacktrace(), CommandObjectTargetVariable::DumpGlobalVariableList(), CommandObjectSourceInfo::DumpLinesForAddress(), CommandObjectSourceInfo::DumpLinesForFile(), CommandObjectSourceInfo::DumpLinesForFrame(), CommandObjectSourceInfo::DumpLinesInFunctions(), lldb_private::CommandObject::GenerateHelpText(), lldb_private::CommandInterpreter::GetHelp(), CommandObjectTypeCategoryDefine::GetOptions(), CommandObjectThreadBacktrace::HandleOneThread(), CommandObjectThreadException::HandleOneThread(), CommandObjectThreadInfo::HandleOneThread(), CommandObjectThreadPlanList::HandleOneThread(), CommandObjectThreadSiginfo::HandleOneThread(), CommandObjectTraceDumpInfo::HandleOneThread(), CommandObjectTargetModulesLookup::LookupHere(), CommandObjectTargetModulesLookup::LookupInModule(), and lldb_private::ScriptInterpreterIORedirect::ScriptInterpreterIORedirect().
GetOutputString()
llvm::StringRef lldb_private::CommandReturnObject::GetOutputString () const inline
Definition at line 44 of file CommandReturnObject.h.
References eStreamStringIndex, and m_out_stream.
Referenced by lldb_private::mcp::CommandTool::Call(), lldb_private::Debugger::Destroy(), CommandObjectPythonFunction::DoExecute(), CommandObjectScriptingObjectParsed::DoExecute(), CommandObjectScriptingObjectRaw::DoExecute(), lldb::SBCommandReturnObject::GetOutputSize(), lldb_private::CommandInterpreter::HandleCommand(), and lldb_private::CommandInterpreter::HandleCommands().
GetStatus()
ReturnStatus CommandReturnObject::GetStatus () const
Definition at line 178 of file CommandReturnObject.cpp.
References m_status.
Referenced by CommandObjectPythonFunction::DoExecute(), CommandObjectScriptingObjectParsed::DoExecute(), CommandObjectScriptingObjectRaw::DoExecute(), lldb::SBCommandReturnObject::GetDescription(), lldb::SBCommandReturnObject::GetStatus(), lldb_private::CommandInterpreter::HandleCommand(), lldb_private::CommandInterpreter::HandleCommands(), lldb_private::Target::StopHookCommandLine::HandleStop(), and lldb_private::REPL::IOHandlerInputComplete().
GetSuppressImmediateOutput()
bool CommandReturnObject::GetSuppressImmediateOutput () const
Definition at line 216 of file CommandReturnObject.cpp.
References m_suppress_immediate_output.
GetValueObjectList() [1/2]
ValueObjectList & lldb_private::CommandReturnObject::GetValueObjectList () inline
Definition at line 169 of file CommandReturnObject.h.
References m_value_objects.
GetValueObjectList() [2/2]
const ValueObjectList & lldb_private::CommandReturnObject::GetValueObjectList () const inline
Definition at line 167 of file CommandReturnObject.h.
References m_value_objects.
Referenced by CommandObjectFrameDiagnose::DoExecute(), lldb_private::CommandObjectDWIMPrint::DoExecute(), and CommandObjectTargetVariable::DumpGlobalVariableList().
HasResult()
bool CommandReturnObject::HasResult () const
Definition at line 184 of file CommandReturnObject.cpp.
References lldb::eReturnStatusSuccessContinuingResult, lldb::eReturnStatusSuccessFinishResult, and m_status.
Referenced by lldb::SBCommandReturnObject::HasResult().
SetCommand()
void lldb_private::CommandReturnObject::SetCommand (std::string command) inline
Definition at line 39 of file CommandReturnObject.h.
References m_command.
Referenced by lldb_private::CommandInterpreter::HandleCommand().
SetDiagnosticIndent()
void lldb_private::CommandReturnObject::SetDiagnosticIndent (std::optional< uint16_t > indent) inline
Definition at line 159 of file CommandReturnObject.h.
References m_diagnostic_indent.
Referenced by lldb_private::CommandObjectDWIMPrint::DoExecute(), and lldb_private::CommandInterpreter::HandleCommand().
SetDidChangeProcessState()
void CommandReturnObject::SetDidChangeProcessState (bool b)
Definition at line 208 of file CommandReturnObject.cpp.
References m_did_change_process_state.
Referenced by CommandObjectProcessAttach::DoExecute(), CommandObjectProcessContinue::DoExecute(), CommandObjectProcessLaunch::DoExecute(), CommandObjectThreadContinue::DoExecute(), CommandObjectThreadStepWithTypeAndScope::DoExecute(), and CommandObjectThreadUntil::DoExecute().
SetError() [1/2]
void CommandReturnObject::SetError (llvm::Error error)
Definition at line 139 of file CommandReturnObject.cpp.
References AppendError(), lldb::eReturnStatusFailed, error(), m_diagnostics, and SetStatus().
SetError() [2/2]
void CommandReturnObject::SetError (Status error)
Definition at line 135 of file CommandReturnObject.cpp.
References error(), and SetError().
Referenced by CommandObjectBreakpointAddException::DoExecute(), CommandObjectMemoryTagRead::DoExecute(), CommandObjectMemoryTagWrite::DoExecute(), CommandObjectTargetCreate::DoExecute(), CommandObjectTargetFrameProviderRegister::DoExecute(), CommandObjectTargetModulesAdd::DoExecute(), CommandObjectThreadJump::DoExecute(), CommandObjectThreadStepWithTypeAndScope::DoExecute(), CommandObjectThreadUntil::DoExecute(), lldb_private::CommandObjectDWIMPrint::DoExecute(), lldb_private::CommandObjectRegexCommand::DoExecute(), lldb_private::trace_intel_pt::CommandObjectProcessTraceStartIntelPT::DoExecute(), lldb_private::trace_intel_pt::CommandObjectThreadTraceStartIntelPT::DoExecuteOnThreads(), CommandObjectTargetSymbolsAdd::DownloadObjectAndSymbolFile(), lldb_private::CommandObject::ParseOptions(), lldb::SBCommandReturnObject::SetError(), SetError(), and lldb_private::CommandObjectMultiwordBreakpoint::VerifyIDs().
SetImmediateErrorFile()
void lldb_private::CommandReturnObject::SetImmediateErrorFile (lldb::FileSP file_sp) inline
Definition at line 86 of file CommandReturnObject.h.
References eImmediateStreamIndex, m_err_stream, and m_suppress_immediate_output.
Referenced by lldb_private::ScriptInterpreterIORedirect::ScriptInterpreterIORedirect(), and lldb::SBCommandReturnObject::SetImmediateErrorFile().
SetImmediateErrorStream()
void lldb_private::CommandReturnObject::SetImmediateErrorStream (const lldb::StreamSP & stream_sp) inline
Definition at line 99 of file CommandReturnObject.h.
References eImmediateStreamIndex, m_err_stream, and m_suppress_immediate_output.
Referenced by lldb_private::BreakpointOptions::BreakpointOptionsCallbackFunction(), and lldb_private::REPL::IOHandlerInputComplete().
SetImmediateOutputFile()
void lldb_private::CommandReturnObject::SetImmediateOutputFile (lldb::FileSP file_sp) inline
Definition at line 79 of file CommandReturnObject.h.
References eImmediateStreamIndex, m_out_stream, and m_suppress_immediate_output.
Referenced by lldb_private::ScriptInterpreterIORedirect::ScriptInterpreterIORedirect(), and lldb::SBCommandReturnObject::SetImmediateOutputFile().
SetImmediateOutputStream()
void lldb_private::CommandReturnObject::SetImmediateOutputStream (const lldb::StreamSP & stream_sp) inline
Definition at line 93 of file CommandReturnObject.h.
References eImmediateStreamIndex, m_out_stream, and m_suppress_immediate_output.
Referenced by lldb_private::BreakpointOptions::BreakpointOptionsCallbackFunction(), CommandObjectProcessGDBRemoteSpeedTest::DoExecute(), lldb_private::Target::StopHookCommandLine::HandleStop(), and lldb_private::REPL::IOHandlerInputComplete().
SetInteractive()
void CommandReturnObject::SetInteractive (bool b)
Definition at line 214 of file CommandReturnObject.cpp.
References m_interactive.
Referenced by lldb::SBCommandInterpreter::HandleCommand(), lldb_private::CommandInterpreter::HandleCommands(), and lldb_private::Target::StopHookCommandLine::HandleStop().
SetStatus()
void CommandReturnObject::SetStatus (lldb::ReturnStatus status)
Definition at line 176 of file CommandReturnObject.cpp.
References m_status.
Referenced by CommandObjectTargetSymbolsAdd::AddModuleSymbols(), AppendError(), AppendErrorWithFormat(), lldb_private::CommandInterpreter::BuildAliasCommandArgs(), CommandObjectTypeSynth::CommandObjectTypeSynth(), CommandObjectBreakpointAddAddress::DoExecute(), CommandObjectBreakpointAddException::DoExecute(), CommandObjectBreakpointAddFile::DoExecute(), CommandObjectBreakpointAddName::DoExecute(), CommandObjectBreakpointAddPattern::DoExecute(), CommandObjectBreakpointAddScripted::DoExecute(), CommandObjectBreakpointClear::DoExecute(), CommandObjectBreakpointCommandList::DoExecute(), CommandObjectBreakpointDelete::DoExecute(), CommandObjectBreakpointEnable::DoExecute(), CommandObjectBreakpointList::DoExecute(), CommandObjectBreakpointSet::DoExecute(), CommandObjectBreakpointWrite::DoExecute(), CommandObjectCommandsContainerAdd::DoExecute(), CommandObjectCommandsContainerDelete::DoExecute(), CommandObjectCommandsDelete::DoExecute(), CommandObjectCommandsScriptAdd::DoExecute(), CommandObjectCommandsScriptClear::DoExecute(), CommandObjectCommandsScriptDelete::DoExecute(), CommandObjectCommandsScriptImport::DoExecute(), CommandObjectCommandsScriptList::DoExecute(), CommandObjectCommandsSource::DoExecute(), CommandObjectCommandsUnalias::DoExecute(), CommandObjectDiagnosticsDump::DoExecute(), CommandObjectFrameInfo::DoExecute(), CommandObjectFrameRecognizerAdd::DoExecute(), CommandObjectFrameRecognizerClear::DoExecute(), CommandObjectFrameRecognizerInfo::DoExecute(), CommandObjectFrameRecognizerList::DoExecute(), CommandObjectFrameSelect::DoExecute(), CommandObjectLogDisable::DoExecute(), CommandObjectLogDump::DoExecute(), CommandObjectLogEnable::DoExecute(), CommandObjectLogList::DoExecute(), CommandObjectLogTimerDisable::DoExecute(), CommandObjectLogTimerDump::DoExecute(), CommandObjectLogTimerEnable::DoExecute(), CommandObjectLogTimerIncrement::DoExecute(), CommandObjectLogTimerReset::DoExecute(), CommandObjectMemoryFind::DoExecute(), CommandObjectMemoryHistory::DoExecute(), CommandObjectMemoryRead::DoExecute(), CommandObjectMemoryRegion::DoExecute(), CommandObjectMemoryTagRead::DoExecute(), CommandObjectMemoryTagWrite::DoExecute(), CommandObjectMemoryWrite::DoExecute(), CommandObjectMultiwordItaniumABI_Demangle::DoExecute(), CommandObjectMultiwordObjC_TaggedPointer_Info::DoExecute(), CommandObjectObjC_ClassTable_Dump::DoExecute(), CommandObjectPlatformConnect::DoExecute(), CommandObjectPlatformDisconnect::DoExecute(), CommandObjectPlatformFClose::DoExecute(), CommandObjectPlatformFOpen::DoExecute(), CommandObjectPlatformFRead::DoExecute(), CommandObjectPlatformFWrite::DoExecute(), CommandObjectPlatformInstall::DoExecute(), CommandObjectPlatformList::DoExecute(), CommandObjectPlatformMkDir::DoExecute(), CommandObjectPlatformProcessAttach::DoExecute(), CommandObjectPlatformProcessLaunch::DoExecute(), CommandObjectPlatformProcessList::DoExecute(), CommandObjectPlatformSelect::DoExecute(), CommandObjectPlatformShell::DoExecute(), CommandObjectPlatformStatus::DoExecute(), CommandObjectPluginLoad::DoExecute(), CommandObjectProcessAttach::DoExecute(), CommandObjectProcessContinue::DoExecute(), CommandObjectProcessDetach::DoExecute(), CommandObjectProcessGDBRemotePacketHistory::DoExecute(), CommandObjectProcessGDBRemotePacketMonitor::DoExecute(), CommandObjectProcessGDBRemotePacketSend::DoExecute(), CommandObjectProcessGDBRemotePacketXferSize::DoExecute(), CommandObjectProcessGDBRemoteSpeedTest::DoExecute(), CommandObjectProcessHandle::DoExecute(), CommandObjectProcessInterrupt::DoExecute(), CommandObjectProcessKDPPacketSend::DoExecute(), CommandObjectProcessKill::DoExecute(), CommandObjectProcessLaunch::DoExecute(), CommandObjectProcessLoad::DoExecute(), CommandObjectProcessMinidumpDump::DoExecute(), CommandObjectProcessSaveCore::DoExecute(), CommandObjectProcessSignal::DoExecute(), CommandObjectProcessStatus::DoExecute(), CommandObjectProcessTraceStop::DoExecute(), CommandObjectProcessUnload::DoExecute(), CommandObjectProtocolServerGet::DoExecute(), CommandObjectProtocolServerStart::DoExecute(), CommandObjectPythonFunction::DoExecute(), CommandObjectRegisterWrite::DoExecute(), CommandObjectScriptingObjectParsed::DoExecute(), CommandObjectScriptingObjectRaw::DoExecute(), CommandObjectScriptingRun::DoExecute(), CommandObjectSessionHistory::DoExecute(), CommandObjectSessionSave::DoExecute(), CommandObjectSettingsAppend::DoExecute(), CommandObjectSettingsClear::DoExecute(), CommandObjectSettingsInsertAfter::DoExecute(), CommandObjectSettingsInsertBefore::DoExecute(), CommandObjectSettingsList::DoExecute(), CommandObjectSettingsRemove::DoExecute(), CommandObjectSettingsReplace::DoExecute(), CommandObjectSettingsShow::DoExecute(), CommandObjectSourceCacheClear::DoExecute(), CommandObjectSourceCacheDump::DoExecute(), CommandObjectSourceInfo::DoExecute(), CommandObjectSourceList::DoExecute(), CommandObjectStatsDisable::DoExecute(), CommandObjectStatsDump::DoExecute(), CommandObjectStatsEnable::DoExecute(), CommandObjectTargetCreate::DoExecute(), CommandObjectTargetDelete::DoExecute(), CommandObjectTargetDumpSectionLoadList::DoExecute(), CommandObjectTargetDumpTypesystem::DoExecute(), CommandObjectTargetFrameProviderClear::DoExecute(), CommandObjectTargetFrameProviderList::DoExecute(), CommandObjectTargetFrameProviderRemove::DoExecute(), CommandObjectTargetList::DoExecute(), CommandObjectTargetModulesAdd::DoExecute(), CommandObjectTargetModulesDumpClangAST::DoExecute(), CommandObjectTargetModulesDumpClangPCMInfo::DoExecute(), CommandObjectTargetModulesDumpLineTable::DoExecute(), CommandObjectTargetModulesDumpObjfile::DoExecute(), CommandObjectTargetModulesDumpSections::DoExecute(), CommandObjectTargetModulesDumpSeparateDebugInfoFiles::DoExecute(), CommandObjectTargetModulesDumpSymfile::DoExecute(), CommandObjectTargetModulesDumpSymtab::DoExecute(), CommandObjectTargetModulesList::DoExecute(), CommandObjectTargetModulesLookup::DoExecute(), CommandObjectTargetModulesSearchPathsAdd::DoExecute(), CommandObjectTargetModulesSearchPathsClear::DoExecute(), CommandObjectTargetModulesSearchPathsInsert::DoExecute(), CommandObjectTargetModulesSearchPathsList::DoExecute(), CommandObjectTargetModulesSearchPathsQuery::DoExecute(), CommandObjectTargetSelect::DoExecute(), CommandObjectTargetShowLaunchEnvironment::DoExecute(), CommandObjectTargetStopHookEnableDisable::DoExecute(), CommandObjectTargetStopHookList::DoExecute(), CommandObjectTargetSymbolsAdd::DoExecute(), CommandObjectThreadContinue::DoExecute(), CommandObjectThreadJump::DoExecute(), CommandObjectThreadList::DoExecute(), CommandObjectThreadPlanDiscard::DoExecute(), CommandObjectThreadPlanList::DoExecute(), CommandObjectThreadPlanPrune::DoExecute(), CommandObjectThreadReturn::DoExecute(), CommandObjectThreadSelect::DoExecute(), CommandObjectThreadStepWithTypeAndScope::DoExecute(), CommandObjectThreadUntil::DoExecute(), CommandObjectTraceDump::DoExecute(), CommandObjectTraceLoad::DoExecute(), CommandObjectTraceSave::DoExecute(), CommandObjectTraceSchema::DoExecute(), CommandObjectTypeFormatterClear::DoExecute(), CommandObjectTypeFormatterDelete::DoExecute(), CommandObjectTypeFormatterList< FormatterType >::DoExecute(), CommandObjectWatchpointCommandDelete::DoExecute(), CommandObjectWatchpointCommandList::DoExecute(), CommandObjectWatchpointDelete::DoExecute(), CommandObjectWatchpointDisable::DoExecute(), CommandObjectWatchpointEnable::DoExecute(), CommandObjectWatchpointIgnore::DoExecute(), CommandObjectWatchpointList::DoExecute(), CommandObjectWatchpointModify::DoExecute(), lldb_private::CommandObjectApropos::DoExecute(), lldb_private::CommandObjectDisassemble::DoExecute(), lldb_private::CommandObjectDWIMPrint::DoExecute(), lldb_private::CommandObjectGUI::DoExecute(), lldb_private::CommandObjectHelp::DoExecute(), lldb_private::CommandObjectIterateOverThreads::DoExecute(), lldb_private::CommandObjectQuit::DoExecute(), lldb_private::CommandObjectRegexCommand::DoExecute(), lldb_private::CommandObjectVersion::DoExecute(), lldb_private::trace_intel_pt::CommandObjectProcessTraceStartIntelPT::DoExecute(), sddarwinlog_private::EnableCommand::DoExecute(), sddarwinlog_private::StatusCommand::DoExecute(), CommandObjectTraceStop::DoExecuteOnThreads(), lldb_private::trace_intel_pt::CommandObjectThreadTraceStartIntelPT::DoExecuteOnThreads(), CommandObjectFrameRecognizerDelete::DoExecuteWithId(), CommandObjectFrameRecognizerDisable::DoExecuteWithId(), CommandObjectFrameRecognizerEnable::DoExecuteWithId(), DoPluginEnableDisable(), CommandObjectTypeSummaryAdd::Execute_StringSummary(), lldb_private::CommandObject::GenerateHelpText(), lldb_private::CommandInterpreter::HandleCommand(), lldb_private::CommandInterpreter::HandleCommands(), lldb_private::CommandInterpreter::HandleCommandsFromFile(), CommandObjectTargetModulesLookup::LookupHere(), CommandObjectTargetModulesLookup::LookupInModule(), lldb_private::CommandObject::ParseOptions(), lldb_private::CommandInterpreter::ResolveCommand(), lldb_private::CommandInterpreter::SaveTranscript(), SetError(), lldb::SBCommandReturnObject::SetStatus(), lldb_private::CommandInterpreter::SourceInitFile(), lldb_private::CommandInterpreter::SourceInitFileCwd(), lldb_private::CommandInterpreter::SourceInitFileGlobal(), lldb_private::CommandInterpreter::SourceInitFileHome(), CommandObjectProcessLaunchOrAttach::StopProcessIfNecessary(), lldb_private::CommandObjectMultiwordBreakpoint::VerifyIDs(), and CommandObjectTypeCategoryDisable::~CommandObjectTypeCategoryDisable().
SetSuppressImmediateOutput()
void CommandReturnObject::SetSuppressImmediateOutput (bool b)
Definition at line 220 of file CommandReturnObject.cpp.
References m_suppress_immediate_output.
Referenced by lldb_private::CommandInterpreter::HandleCommands().
Succeeded()
bool CommandReturnObject::Succeeded () const
Definition at line 180 of file CommandReturnObject.cpp.
References lldb::eReturnStatusSuccessContinuingResult, and m_status.
Referenced by lldb_private::mcp::CommandTool::Call(), CommandObjectScriptingObjectParsed::Create(), lldb_private::Debugger::Destroy(), CommandObjectBreakpointCommandDelete::DoExecute(), CommandObjectBreakpointCommandList::DoExecute(), CommandObjectBreakpointDelete::DoExecute(), CommandObjectBreakpointEnable::DoExecute(), CommandObjectBreakpointList::DoExecute(), CommandObjectBreakpointModify::DoExecute(), CommandObjectBreakpointNameAdd::DoExecute(), CommandObjectBreakpointNameDelete::DoExecute(), CommandObjectBreakpointWrite::DoExecute(), CommandObjectCommandsScriptAdd::DoExecute(), CommandObjectLogTimerDisable::DoExecute(), CommandObjectLogTimerDump::DoExecute(), CommandObjectLogTimerEnable::DoExecute(), CommandObjectLogTimerIncrement::DoExecute(), CommandObjectLogTimerReset::DoExecute(), CommandObjectProcessAttach::DoExecute(), CommandObjectProcessContinue::DoExecute(), CommandObjectTraceStop::DoExecuteOnThreads(), lldb_private::trace_intel_pt::CommandObjectThreadTraceStartIntelPT::DoExecuteOnThreads(), CommandObjectTypeSummaryAdd::Execute_StringSummary(), lldb_private::CommandInterpreter::HandleCommand(), lldb_private::CommandInterpreter::HandleCommands(), sddarwinlog_private::RunEnableCommand(), CommandObjectProcessLaunchOrAttach::StopProcessIfNecessary(), and lldb::SBCommandReturnObject::Succeeded().
Member Data Documentation
m_colors
bool lldb_private::CommandReturnObject::m_colors private
Definition at line 211 of file CommandReturnObject.h.
Referenced by CommandReturnObject(), GetErrorString(), and GetInlineDiagnosticString().
m_command
std::string lldb_private::CommandReturnObject::m_command private
Definition at line 194 of file CommandReturnObject.h.
Referenced by GetCommand(), and SetCommand().
m_diagnostic_indent
std::optional<uint16_t> lldb_private::CommandReturnObject::m_diagnostic_indent private
Definition at line 199 of file CommandReturnObject.h.
Referenced by GetDiagnosticIndent(), and SetDiagnosticIndent().
m_diagnostics
std::vector<DiagnosticDetail> lldb_private::CommandReturnObject::m_diagnostics private
Definition at line 198 of file CommandReturnObject.h.
Referenced by Clear(), GetErrorData(), GetErrorString(), GetInlineDiagnosticString(), and SetError().
m_did_change_process_state
bool lldb_private::CommandReturnObject::m_did_change_process_state = false private
Definition at line 206 of file CommandReturnObject.h.
Referenced by Clear(), GetDidChangeProcessState(), and SetDidChangeProcessState().
m_err_stream
StreamTee lldb_private::CommandReturnObject::m_err_stream private
Definition at line 197 of file CommandReturnObject.h.
Referenced by Clear(), CommandReturnObject(), GetErrorStream(), GetErrorString(), GetImmediateErrorStream(), GetInlineDiagnosticString(), SetImmediateErrorFile(), and SetImmediateErrorStream().
m_interactive
bool lldb_private::CommandReturnObject::m_interactive = true private
If true, then the input handle from the debugger will be hooked up.
Definition at line 210 of file CommandReturnObject.h.
Referenced by Clear(), GetInteractive(), and SetInteractive().
m_out_stream
StreamTee lldb_private::CommandReturnObject::m_out_stream private
Definition at line 196 of file CommandReturnObject.h.
Referenced by Clear(), CommandReturnObject(), GetImmediateOutputStream(), GetOutputStream(), GetOutputString(), SetImmediateOutputFile(), and SetImmediateOutputStream().
m_status
lldb::ReturnStatus lldb_private::CommandReturnObject::m_status = lldb::eReturnStatusStarted private
Definition at line 201 of file CommandReturnObject.h.
Referenced by Clear(), GetStatus(), HasResult(), SetStatus(), and Succeeded().
m_suppress_immediate_output
bool lldb_private::CommandReturnObject::m_suppress_immediate_output = false private
Definition at line 207 of file CommandReturnObject.h.
Referenced by Clear(), GetSuppressImmediateOutput(), SetImmediateErrorFile(), SetImmediateErrorStream(), SetImmediateOutputFile(), SetImmediateOutputStream(), and SetSuppressImmediateOutput().
m_value_objects
ValueObjectList lldb_private::CommandReturnObject::m_value_objects private
An optionally empty list of values produced by this command.
Definition at line 204 of file CommandReturnObject.h.
Referenced by GetValueObjectList(), and GetValueObjectList().
The documentation for this class was generated from the following files:
CommandReturnObject.h
CommandReturnObject.cpp