LLDB: lldb_private::Broadcaster Class Reference
lldb_private::Broadcaster Class Reference
An event broadcasting class.
#include "lldb/Utility/Broadcaster.h"
Classes
class BroadcasterImpl
BroadcasterImpl contains the actual Broadcaster implementation.
Public Member Functions
Broadcaster (lldb::BroadcasterManagerSP manager_sp, std::string name)
Construct with a broadcaster with a name.
virtual ~Broadcaster ()
Destructor.
void CheckInWithManager ()
void BroadcastEvent (lldb::EventSP &event_sp)
Broadcast an event which has no associated data.
void BroadcastEventIfUnique (lldb::EventSP &event_sp)
void BroadcastEvent (uint32_t event_type, const lldb::EventDataSP &event_data_sp)
void BroadcastEvent (uint32_t event_type)
void BroadcastEventIfUnique (uint32_t event_type)
void Clear ()
virtual void AddInitialEventsToListener (const lldb::ListenerSP &listener_sp, uint32_t requested_events)
uint32_t AddListener (const lldb::ListenerSP &listener_sp, uint32_t event_mask)
Listen for any events specified by event_mask.
const std::string & GetBroadcasterName ()
Get this broadcaster's name.
bool GetEventNames (Stream &s, const uint32_t event_mask, bool prefix_with_broadcaster_name) const
Get the event name(s) for one or more event bits.
void SetEventName (uint32_t event_mask, const char *name)
Set the name for an event bit.
const char * GetEventName (uint32_t event_mask) const
bool EventTypeHasListeners (uint32_t event_type)
bool RemoveListener (const lldb::ListenerSP &listener_sp, uint32_t event_mask=UINT32_MAX)
Removes a Listener from this broadcasters list and frees the event bits specified by event_mask that were previously acquired by listener (assuming listener was listening to this object) for other listener objects to use.
bool HijackBroadcaster (const lldb::ListenerSP &listener_sp, uint32_t event_mask=UINT32_MAX)
Provides a simple mechanism to temporarily redirect events from broadcaster.
bool IsHijackedForEvent (uint32_t event_mask)
void RestoreBroadcaster ()
Restore the state of the Broadcaster from a previous hijack attempt.
virtual llvm::StringRef GetBroadcasterClass () const
This needs to be filled in if you are going to register the broadcaster with the broadcaster manager and do broadcaster class matching.
lldb::BroadcasterManagerSP GetManager ()
void SetPrimaryListener (lldb::ListenerSP listener_sp)
lldb::ListenerSP GetPrimaryListener ()
Protected Types
typedef std::shared_ptr< BroadcasterImpl > BroadcasterImplSP
typedef std::weak_ptr< BroadcasterImpl > BroadcasterImplWP
Protected Member Functions
BroadcasterImplSP GetBroadcasterImpl ()
const char * GetHijackingListenerName ()
Private Member Functions
Broadcaster (const Broadcaster &)=delete
const Broadcaster & operator= (const Broadcaster &)=delete
Private Attributes
BroadcasterImplSP m_broadcaster_sp
lldb::BroadcasterManagerSP m_manager_sp
const std::string m_broadcaster_name
The name of this broadcaster object.
Friends
class Listener
class Event
Detailed Description
An event broadcasting class.
The Broadcaster class is designed to be subclassed by objects that wish to vend events in a multi-threaded environment. Broadcaster objects can each vend 32 events. Each event is represented by a bit in a 32 bit value and these bits can be set:
See also
Broadcaster::SetEventBits(uint32_t) or cleared:
Broadcaster::ResetEventBits(uint32_t) When an event gets set the Broadcaster object will notify the Listener object that is listening for the event (if there is one).
Subclasses should provide broadcast bit definitions for any events they vend, typically using an enumeration:
class Foo : public Broadcaster
{
public:
// Broadcaster event bits definitions.
enum
{
    eBroadcastBitOne   = (1 << 0),
    eBroadcastBitTwo   = (1 << 1),
    eBroadcastBitThree = (1 << 2),
    ...
};
Definition at line 146 of file Broadcaster.h.
Member Typedef Documentation
BroadcasterImplSP
typedef std::shared_ptr<BroadcasterImpl> lldb_private::Broadcaster::BroadcasterImplSP protected
Definition at line 464 of file Broadcaster.h.
BroadcasterImplWP
typedef std::weak_ptr<BroadcasterImpl> lldb_private::Broadcaster::BroadcasterImplWP protected
Definition at line 465 of file Broadcaster.h.
Constructor & Destructor Documentation
Broadcaster() [1/2]
Broadcaster::Broadcaster (lldb::BroadcasterManagerSP manager_sp, std::string name)
Construct with a broadcaster with a name.
Parameters
[in] manager_sp A shared pointer to the BroadcasterManager that will manage this broadcaster.
[in] name A std::string of the name that this broadcaster will have.
Definition at line 26 of file Broadcaster.cpp.
References GetBroadcasterName(), lldb_private::GetLog(), LLDB_LOG, m_broadcaster_name, m_broadcaster_sp, m_manager_sp, and lldb_private::Object.
Referenced by Broadcaster(), lldb_private::CommandInterpreter::CommandInterpreter(), lldb_private::process_gdb_remote::GDBRemoteClientBase::GDBRemoteClientBase(), operator=(), lldb_private::Process::Process(), lldb_private::Target::Target(), lldb_private::TargetList::TargetList(), lldb_private::Thread::Thread(), and lldb_private::ThreadedCommunication::ThreadedCommunication().
~Broadcaster()
Broadcaster::~Broadcaster () virtual
Destructor.
The destructor is virtual since this class gets subclassed.
Definition at line 38 of file Broadcaster.cpp.
References Clear(), GetBroadcasterName(), lldb_private::GetLog(), LLDB_LOG, and lldb_private::Object.
Broadcaster() [2/2]
lldb_private::Broadcaster::Broadcaster (const Broadcaster &) private delete
References Broadcaster().
Member Function Documentation
AddInitialEventsToListener()
void Broadcaster::AddInitialEventsToListener (const lldb::ListenerSP & listener_sp, uint32_t requested_events) virtual
Definition at line 131 of file Broadcaster.cpp.
AddListener()
uint32_t lldb_private::Broadcaster::AddListener (const lldb::ListenerSP & listener_sp, uint32_t event_mask) inline
Listen for any events specified by event_mask.
Only one listener can listen to each event bit in a given Broadcaster. Once a listener has acquired an event bit, no other broadcaster will have access to it until it is relinquished by the first listener that gets it. The actual event bits that get acquired by listener may be different from what is requested in event_mask, and to track this the actual event bits that are acquired get returned.
Parameters
[in] listener_sp The Listener object that wants to monitor the events that get broadcast by this object.
[in] event_mask A bit mask that indicates which events the listener is asking to monitor.
Returns
The actual event bits that were acquired by listener.
Definition at line 213 of file Broadcaster.h.
References m_broadcaster_sp.
Referenced by lldb_private::Process::SetShadowListener(), lldb_private::Listener::StartListeningForEvents(), and lldb_private::Listener::StartListeningForEvents().
BroadcastEvent() [1/3]
void lldb_private::Broadcaster::BroadcastEvent (lldb::EventSP & event_sp) inline
Broadcast an event which has no associated data.
Definition at line 168 of file Broadcaster.h.
References m_broadcaster_sp.
Referenced by lldb_private::Thread::BroadcastSelectedFrameChange(), lldb_private::Process::BroadcastStructuredData(), lldb_private::Process::DestroyImpl(), lldb_private::Process::Detach(), lldb_private::Process::Halt(), lldb_private::Process::HandlePrivateEvent(), lldb_private::Target::ModulesDidLoad(), lldb_private::Target::ModulesDidUnload(), lldb_private::Target::NotifyBreakpointChanged(), lldb_private::Target::NotifyBreakpointChanged(), lldb_private::process_gdb_remote::GDBRemoteClientBase::OnRunPacketSent(), PrivateReportDiagnostic(), PrivateReportProgress(), lldb_private::ThreadedCommunication::ReadThread(), lldb_private::Thread::ReturnFromFrame(), lldb_private::Process::RunPrivateStateThread(), lldb_private::Process::RunThreadPlan(), lldb_private::Process::SendAsyncInterrupt(), lldb_private::TargetList::SendAsyncInterrupt(), lldb_private::Watchpoint::SendWatchpointChangedEvent(), lldb_private::Debugger::SetPropertyValue(), lldb_private::Debugger::StopEventHandlerThread(), lldb_private::ThreadedCommunication::StopReadThread(), lldb_private::Target::SymbolsDidLoad(), and lldb_private::CommandInterpreter::UpdatePrompt().
BroadcastEvent() [2/3]
void lldb_private::Broadcaster::BroadcastEvent (uint32_t event_type) inline
Definition at line 181 of file Broadcaster.h.
References m_broadcaster_sp.
BroadcastEvent() [3/3]
void lldb_private::Broadcaster::BroadcastEvent (uint32_t event_type, const lldb::EventDataSP & event_data_sp) inline
Definition at line 176 of file Broadcaster.h.
References m_broadcaster_sp.
BroadcastEventIfUnique() [1/2]
void lldb_private::Broadcaster::BroadcastEventIfUnique (lldb::EventSP & event_sp) inline
Definition at line 172 of file Broadcaster.h.
References m_broadcaster_sp.
Referenced by lldb_private::ThreadedCommunication::AppendBytesToCache(), lldb_private::Process::AppendSTDERR(), lldb_private::Process::AppendSTDOUT(), and lldb_private::Process::BroadcastAsyncProfileData().
BroadcastEventIfUnique() [2/2]
void lldb_private::Broadcaster::BroadcastEventIfUnique (uint32_t event_type) inline
Definition at line 185 of file Broadcaster.h.
References m_broadcaster_sp.
CheckInWithManager()
void Broadcaster::CheckInWithManager ()
Definition at line 46 of file Broadcaster.cpp.
References m_manager_sp.
Referenced by lldb_private::CommandInterpreter::CommandInterpreter(), lldb_private::Process::Process(), lldb_private::Target::Target(), lldb_private::TargetList::TargetList(), lldb_private::Thread::Thread(), and lldb_private::ThreadedCommunication::ThreadedCommunication().
Clear()
void lldb_private::Broadcaster::Clear () inline
Definition at line 189 of file Broadcaster.h.
References m_broadcaster_sp.
Referenced by lldb_private::Process::Finalize(), and ~Broadcaster().
EventTypeHasListeners()
bool lldb_private::Broadcaster::EventTypeHasListeners (uint32_t event_type) inline
Definition at line 251 of file Broadcaster.h.
References m_broadcaster_sp.
Referenced by lldb_private::Thread::BroadcastSelectedFrameChange(), lldb_private::Target::NotifyBreakpointChanged(), lldb_private::Target::NotifyBreakpointChanged(), PrivateReportDiagnostic(), PrivateReportProgress(), and lldb_private::Thread::ReturnFromFrame().
GetBroadcasterClass()
llvm::StringRef Broadcaster::GetBroadcasterClass () const virtual
This needs to be filled in if you are going to register the broadcaster with the broadcaster manager and do broadcaster class matching.
FIXME: Probably should make a ManagedBroadcaster subclass with all the bits needed to work with the BroadcasterManager, so that it is clearer how to add one.
Reimplemented in lldb_private::CommandInterpreter, lldb_private::Process, lldb_private::Target, lldb_private::TargetList, lldb_private::Thread, and lldb_private::ThreadedCommunication.
Definition at line 376 of file Broadcaster.cpp.
Referenced by lldb_private::Debugger::DefaultEventHandler(), lldb::SBEvent::GetBroadcasterClass(), lldb_private::BroadcastEventSpec::operator<(), and lldb_private::BroadcasterManager::SignUpListenersForBroadcaster().
GetBroadcasterImpl()
BroadcasterImplSP lldb_private::Broadcaster::GetBroadcasterImpl () inline protected
Definition at line 467 of file Broadcaster.h.
References m_broadcaster_sp.
Referenced by lldb_private::Listener::BroadcasterWillDestruct(), lldb_private::Listener::HandleBroadcastEvent(), lldb_private::Event::SetBroadcaster(), lldb_private::Listener::StartListeningForEvents(), lldb_private::Listener::StartListeningForEvents(), and lldb_private::Listener::StopListeningForEvents().
GetBroadcasterName()
const std::string & lldb_private::Broadcaster::GetBroadcasterName () inline
Get this broadcaster's name.
Returns
A reference to a constant std::string containing the name of the broadcaster.
Definition at line 223 of file Broadcaster.h.
References m_broadcaster_name.
Referenced by Broadcaster(), lldb_private::Event::Dump(), lldb_private::Broadcaster::BroadcasterImpl::GetEventNames(), lldb_private::Broadcaster::BroadcasterImpl::HijackBroadcaster(), lldb_private::Broadcaster::BroadcasterImpl::PrivateBroadcastEvent(), lldb_private::Broadcaster::BroadcasterImpl::RestoreBroadcaster(), lldb_private::ThreadedCommunication::StartReadThread(), ~Broadcaster(), and lldb_private::ThreadedCommunication::~ThreadedCommunication().
GetEventName()
const char * lldb_private::Broadcaster::GetEventName (uint32_t event_mask) const inline
Definition at line 247 of file Broadcaster.h.
References m_broadcaster_sp.
GetEventNames()
bool lldb_private::Broadcaster::GetEventNames (Stream & s, const uint32_t event_mask, bool prefix_with_broadcaster_name) const inline
Get the event name(s) for one or more event bits.
Parameters
[in] event_mask A bit mask that indicates which events to get names for.
Returns
The NULL terminated C string name of this Broadcaster.
Definition at line 232 of file Broadcaster.h.
References m_broadcaster_sp.
Referenced by lldb_private::Event::Dump().
GetHijackingListenerName()
const char * lldb_private::Broadcaster::GetHijackingListenerName () inline protected
Definition at line 469 of file Broadcaster.h.
References m_broadcaster_sp.
Referenced by lldb_private::Process::StateChangedIsExternallyHijacked(), and lldb_private::Process::StateChangedIsHijackedForSynchronousResume().
GetManager()
lldb::BroadcasterManagerSP lldb_private::Broadcaster::GetManager ()
GetPrimaryListener()
lldb::ListenerSP lldb_private::Broadcaster::GetPrimaryListener () inline
Definition at line 319 of file Broadcaster.h.
References m_broadcaster_sp.
Referenced by lldb_private::Process::GetNextEvent(), lldb_private::Process::GetStateChangedEvents(), and lldb_private::Process::PeekAtStateChangedEvents().
HijackBroadcaster()
bool lldb_private::Broadcaster::HijackBroadcaster (const lldb::ListenerSP & listener_sp, uint32_t event_mask = UINT32_MAX) inline
Provides a simple mechanism to temporarily redirect events from broadcaster.
When you call this function passing in a listener and event type mask, all events from the broadcaster matching the mask will now go to the hijacking listener. Only one hijack can occur at a time. If we need more than this we will have to implement a Listener stack.
Parameters
[in] listener_sp A Listener object. You do not need to call StartListeningForEvents for this broadcaster (that would fail anyway since the event bits would most likely be taken by the listener(s) you are usurping.
[in] event_mask The event bits listener wishes to hijack.
Returns
True if the event mask could be hijacked, false otherwise.
See also
uint32_t Broadcaster::AddListener (Listener*, uint32_t)
Definition at line 294 of file Broadcaster.h.
References m_broadcaster_sp, and UINT32_MAX.
Referenced by lldb_private::Process::HijackProcessEvents().
IsHijackedForEvent()
bool lldb_private::Broadcaster::IsHijackedForEvent (uint32_t event_mask) inline
Definition at line 299 of file Broadcaster.h.
References m_broadcaster_sp.
Referenced by lldb_private::Process::HandlePrivateEvent(), lldb_private::Process::StateChangedIsExternallyHijacked(), and lldb_private::Process::StateChangedIsHijackedForSynchronousResume().
operator=()
const Broadcaster & lldb_private::Broadcaster::operator= (const Broadcaster &) private delete
References Broadcaster().
RemoveListener()
bool lldb_private::Broadcaster::RemoveListener (const lldb::ListenerSP & listener_sp, uint32_t event_mask = UINT32_MAX) inline
Removes a Listener from this broadcasters list and frees the event bits specified by event_mask that were previously acquired by listener (assuming listener was listening to this object) for other listener objects to use.
Parameters
[in] listener_sp A Listener object that previously called AddListener.
[in] event_mask The event bits listener wishes to relinquish.
Returns
True if the listener was listening to this broadcaster and was removed, false otherwise.
See also
uint32_t Broadcaster::AddListener (Listener*, uint32_t)
Definition at line 271 of file Broadcaster.h.
References m_broadcaster_sp, and UINT32_MAX.
Referenced by lldb_private::Broadcaster::BroadcasterImpl::RemoveListener(), lldb_private::Broadcaster::BroadcasterImpl::SetPrimaryListener(), and lldb_private::Listener::StopListeningForEvents().
RestoreBroadcaster()
void lldb_private::Broadcaster::RestoreBroadcaster () inline
Restore the state of the Broadcaster from a previous hijack attempt.
Definition at line 304 of file Broadcaster.h.
References m_broadcaster_sp.
Referenced by lldb_private::Process::RestoreProcessEvents().
SetEventName()
void lldb_private::Broadcaster::SetEventName (uint32_t event_mask, const char * name) inline
Set the name for an event bit.
Parameters
[in] event_mask A bit mask that indicates which events the listener is asking to monitor.
Definition at line 243 of file Broadcaster.h.
References m_broadcaster_sp.
Referenced by lldb_private::CommandInterpreter::CommandInterpreter(), lldb_private::Process::Process(), lldb_private::Target::Target(), and lldb_private::ThreadedCommunication::ThreadedCommunication().
SetPrimaryListener()
void lldb_private::Broadcaster::SetPrimaryListener (lldb::ListenerSP listener_sp) inline
Definition at line 315 of file Broadcaster.h.
References m_broadcaster_sp.
Referenced by lldb_private::Process::Process().
Friends And Related Symbol Documentation
Event
friend class Event friend
Definition at line 148 of file Broadcaster.h.
References Event.
Referenced by Event, lldb_private::Process::PeekAtStateChangedEvents(), lldb_private::Thread::RefreshStateAfterStop(), lldb_private::Process::RunThreadPlan(), lldb_private::Process::SetPrivateState(), lldb_private::Process::ShouldBroadcastEvent(), lldb_private::Thread::ShouldReportRun(), lldb_private::Thread::ShouldReportStop(), lldb_private::Thread::ShouldStop(), and lldb_private::CommandInterpreter::UpdatePrompt().
Listener
friend class Listener friend
Definition at line 147 of file Broadcaster.h.
References Listener.
Referenced by Listener, lldb_private::Process::Process(), and lldb_private::process_gdb_remote::ProcessGDBRemote::ProcessGDBRemote().
Member Data Documentation
m_broadcaster_name
const std::string lldb_private::Broadcaster::m_broadcaster_name private
The name of this broadcaster object.
Definition at line 478 of file Broadcaster.h.
Referenced by Broadcaster(), and GetBroadcasterName().
m_broadcaster_sp
BroadcasterImplSP lldb_private::Broadcaster::m_broadcaster_sp private
Definition at line 474 of file Broadcaster.h.
Referenced by AddListener(), Broadcaster(), BroadcastEvent(), BroadcastEvent(), BroadcastEvent(), BroadcastEventIfUnique(), BroadcastEventIfUnique(), Clear(), EventTypeHasListeners(), GetBroadcasterImpl(), GetEventName(), GetEventNames(), GetHijackingListenerName(), GetPrimaryListener(), HijackBroadcaster(), IsHijackedForEvent(), RemoveListener(), RestoreBroadcaster(), SetEventName(), and SetPrimaryListener().
m_manager_sp
lldb::BroadcasterManagerSP lldb_private::Broadcaster::m_manager_sp private
Definition at line 475 of file Broadcaster.h.
Referenced by Broadcaster(), and CheckInWithManager().
The documentation for this class was generated from the following files:
Broadcaster.h
Broadcaster.cpp