LLDB: lldb_private::Environment::Envp Class Reference
lldb_private::Environment::Envp Class Reference
#include <Environment.h>
Public Member Functions
Envp (Envp &&RHS)=default
Envp & operator= (Envp &&RHS)=default
char *const * get () const
operator char *const * () const
Private Member Functions
Envp (const Environment &Env)
char * make_entry (llvm::StringRef Key, llvm::StringRef Value)
Envp (const Envp &)=delete
Envp & operator= (const Envp &)=delete
Private Attributes
llvm::BumpPtrAllocator Allocator
char ** Data
Friends
class Environment
Detailed Description
Definition at line 22 of file Environment.h.
Constructor & Destructor Documentation
Envp() [1/3]
lldb_private::Environment::Envp::Envp (Envp && RHS) default
References Envp().
Referenced by Envp(), Envp(), operator=(), and operator=().
Envp() [2/3]
Environment::Envp::Envp (const Environment & Env) explicit private
Definition at line 28 of file Environment.cpp.
References Allocator, Data, Environment, and make_entry().
Envp() [3/3]
lldb_private::Environment::Envp::Envp (const Envp &) private delete
References Envp().
Member Function Documentation
get()
char *const * lldb_private::Environment::Envp::get () const inline
Definition at line 27 of file Environment.h.
References Data.
Referenced by lldb_private::Args::Args(), LaunchProcessPosixSpawn(), and operator char *const *().
make_entry()
char * Environment::Envp::make_entry (llvm::StringRef Key, llvm::StringRef Value) private
Definition at line 13 of file Environment.cpp.
References Allocator.
Referenced by Envp().
operator char *const *()
lldb_private::Environment::Envp::operator char *const * () const inline
Definition at line 28 of file Environment.h.
References get().
operator=() [1/2]
Envp & lldb_private::Environment::Envp::operator= (const Envp &) private delete
References Envp().
operator=() [2/2]
Envp & lldb_private::Environment::Envp::operator= (Envp && RHS) default
References Envp().
Friends And Related Symbol Documentation
Environment
friend class Environment friend
Definition at line 35 of file Environment.h.
References Environment.
Referenced by Environment, and Envp().
Member Data Documentation
Allocator
llvm::BumpPtrAllocator lldb_private::Environment::Envp::Allocator private
Definition at line 37 of file Environment.h.
Referenced by Envp(), and make_entry().
Data
char** lldb_private::Environment::Envp::Data private
Definition at line 38 of file Environment.h.
Referenced by Envp(), and get().
The documentation for this class was generated from the following files:
Environment.h
Environment.cpp