LLDB: lldb_private::ValueObject Class Reference
lldb_private::ValueObject Class Reference abstract
ValueObject:
#include <ValueObject.h>
Classes
struct AddrAndType
struct Bitflags
class ChildrenManager
class EvaluationPoint
struct GetValueForExpressionPathOptions
Public Types
enum GetExpressionPathFormat { eGetExpressionPathFormatDereferencePointers = 1 , eGetExpressionPathFormatHonorPointers }
enum ValueObjectRepresentationStyle {
eValueObjectRepresentationStyleValue = 1 , eValueObjectRepresentationStyleSummary , eValueObjectRepresentationStyleLanguageSpecific , eValueObjectRepresentationStyleLocation ,
eValueObjectRepresentationStyleChildrenCount , eValueObjectRepresentationStyleType , eValueObjectRepresentationStyleName , eValueObjectRepresentationStyleExpressionPath
}
enum ExpressionPathScanEndReason {
eExpressionPathScanEndReasonEndOfString = 1 , eExpressionPathScanEndReasonNoSuchChild , eExpressionPathScanEndReasonNoSuchSyntheticChild , eExpressionPathScanEndReasonEmptyRangeNotAllowed ,
eExpressionPathScanEndReasonDotInsteadOfArrow , eExpressionPathScanEndReasonArrowInsteadOfDot , eExpressionPathScanEndReasonFragileIVarNotAllowed , eExpressionPathScanEndReasonRangeOperatorNotAllowed ,
eExpressionPathScanEndReasonRangeOperatorInvalid , eExpressionPathScanEndReasonArrayRangeOperatorMet , eExpressionPathScanEndReasonBitfieldRangeOperatorMet , eExpressionPathScanEndReasonUnexpectedSymbol ,
eExpressionPathScanEndReasonTakingAddressFailed , eExpressionPathScanEndReasonDereferencingFailed , eExpressionPathScanEndReasonRangeOperatorExpanded , eExpressionPathScanEndReasonSyntheticValueMissing ,
eExpressionPathScanEndReasonUnknown = 0xFFFF
}
enum ExpressionPathEndResultType {
eExpressionPathEndResultTypePlain = 1 , eExpressionPathEndResultTypeBitfield , eExpressionPathEndResultTypeBoundedRange , eExpressionPathEndResultTypeUnboundedRange ,
eExpressionPathEndResultTypeValueObjectList , eExpressionPathEndResultTypeInvalid = 0xFFFF
}
enum ExpressionPathAftermath { eExpressionPathAftermathNothing = 1 , eExpressionPathAftermathDereference , eExpressionPathAftermathTakeAddress }
enum ClearUserVisibleDataItems {
eClearUserVisibleDataItemsNothing = 1u << 0 , eClearUserVisibleDataItemsValue = 1u << 1 , eClearUserVisibleDataItemsSummary = 1u << 2 , eClearUserVisibleDataItemsLocation = 1u << 3 ,
eClearUserVisibleDataItemsDescription = 1u << 4 , eClearUserVisibleDataItemsSyntheticChildren = 1u << 5 , eClearUserVisibleDataItemsAllStrings , eClearUserVisibleDataItemsAll = 0xFFFF
}
enum class PrintableRepresentationSpecialCases : bool { eDisable = false , eAllow = true }
Public Member Functions
virtual ~ValueObject ()
const EvaluationPoint & GetUpdatePoint () const
EvaluationPoint & GetUpdatePoint ()
const ExecutionContextRef & GetExecutionContextRef () const
lldb::TargetSP GetTargetSP () const
lldb::ProcessSP GetProcessSP () const
lldb::ThreadSP GetThreadSP () const
lldb::StackFrameSP GetFrameSP () const
void SetNeedsUpdate ()
CompilerType GetCompilerType ()
virtual TypeImpl GetTypeImpl ()
virtual bool CanProvideValue ()
virtual llvm::Expected< uint64_t > GetByteSize ()=0
virtual lldb::ValueType GetValueType () const =0
virtual ConstString GetTypeName ()
virtual ConstString GetDisplayTypeName ()
virtual ConstString GetQualifiedTypeName ()
lldb::LanguageType GetObjectRuntimeLanguage ()
uint32_t GetTypeInfo (CompilerType *pointee_or_element_compiler_type=nullptr)
bool IsPointerType ()
bool IsArrayType ()
bool IsScalarType ()
bool IsPointerOrReferenceType ()
bool IsPossibleDynamicType ()
bool IsNilReference ()
bool IsUninitializedReference ()
virtual bool IsBaseClass ()
bool IsBaseClass (uint32_t &depth)
virtual bool IsDereferenceOfParent ()
bool IsIntegerType (bool &is_signed)
virtual void GetExpressionPath (Stream &s, GetExpressionPathFormat=eGetExpressionPathFormatDereferencePointers)
lldb::ValueObjectSP GetValueForExpressionPath (llvm::StringRef expression, ExpressionPathScanEndReason *reason_to_stop=nullptr, ExpressionPathEndResultType *final_value_type=nullptr, const GetValueForExpressionPathOptions &options=GetValueForExpressionPathOptions::DefaultOptions(), ExpressionPathAftermath *final_task_on_target=nullptr)
virtual bool IsInScope ()
virtual lldb::offset_t GetByteOffset ()
virtual uint32_t GetBitfieldBitSize ()
virtual uint32_t GetBitfieldBitOffset ()
bool IsBitfield ()
virtual const char * GetValueAsCString ()
virtual bool GetValueAsCString (const lldb_private::TypeFormatImpl &format, std::string &destination)
bool GetValueAsCString (lldb::Format format, std::string &destination)
virtual uint64_t GetValueAsUnsigned (uint64_t fail_value, bool *success=nullptr)
virtual int64_t GetValueAsSigned (int64_t fail_value, bool *success=nullptr)
llvm::Expected< llvm::APSInt > GetValueAsAPSInt ()
If the current ValueObject is of an appropriate type, convert the value to an APSInt and return that.
llvm::Expected< llvm::APFloat > GetValueAsAPFloat ()
If the current ValueObject is of an appropriate type, convert the value to an APFloat and return that.
llvm::Expected< bool > GetValueAsBool ()
If the current ValueObject is of an appropriate type, convert the value to a boolean and return that.
void SetValueFromInteger (const llvm::APInt &value, Status &error)
Update an existing integer ValueObject with a new integer value.
void SetValueFromInteger (lldb::ValueObjectSP new_val_sp, Status &error)
Update an existing integer ValueObject with an integer value created frome 'new_val_sp'.
virtual bool SetValueFromCString (const char *value_str, Status &error)
virtual lldb::ModuleSP GetModule ()
Return the module associated with this value object in case the value is from an executable file and might have its data in sections of the file.
ValueObject * GetRoot ()
ValueObject * FollowParentChain (std::function< bool(ValueObject *)>)
Given a ValueObject, loop over itself and its parent, and its parent's parent, .
virtual bool GetDeclaration (Declaration &decl)
const Status & GetError ()
ConstString GetName () const
lldb::user_id_t GetID () const
Returns a unique id for this ValueObject.
virtual lldb::ValueObjectSP GetChildAtIndex (uint32_t idx, bool can_create=true)
lldb::ValueObjectSP GetChildAtNamePath (llvm::ArrayRef< llvm::StringRef > names)
virtual lldb::ValueObjectSP GetChildMemberWithName (llvm::StringRef name, bool can_create=true)
virtual llvm::Expected< size_t > GetIndexOfChildWithName (llvm::StringRef name)
llvm::Expected< uint32_t > GetNumChildren (uint32_t max=UINT32_MAX)
uint32_t GetNumChildrenIgnoringErrors (uint32_t max=UINT32_MAX)
Like GetNumChildren but returns 0 on error.
bool HasChildren ()
const Value & GetValue () const
Value & GetValue ()
virtual bool ResolveValue (Scalar &scalar)
virtual bool IsLogicalTrue (Status &error)
virtual const char * GetLocationAsCString ()
const char * GetSummaryAsCString (lldb::LanguageType lang=lldb::eLanguageTypeUnknown)
bool GetSummaryAsCString (TypeSummaryImpl *summary_ptr, std::string &destination, lldb::LanguageType lang=lldb::eLanguageTypeUnknown)
bool GetSummaryAsCString (std::string &destination, const TypeSummaryOptions &options)
bool GetSummaryAsCString (TypeSummaryImpl *summary_ptr, std::string &destination, const TypeSummaryOptions &options)
llvm::Expected< std::string > GetObjectDescription ()
bool HasSpecialPrintableRepresentation (ValueObjectRepresentationStyle val_obj_display, lldb::Format custom_format)
bool DumpPrintableRepresentation (Stream &s, ValueObjectRepresentationStyle val_obj_display=eValueObjectRepresentationStyleSummary, lldb::Format custom_format=lldb::eFormatInvalid, PrintableRepresentationSpecialCases special=PrintableRepresentationSpecialCases::eAllow, bool do_dump_error=true)
bool GetValueIsValid () const
bool GetValueDidChange ()
bool UpdateValueIfNeeded (bool update_format=true)
bool UpdateFormatsIfNeeded ()
lldb::ValueObjectSP GetSP ()
void SetName (ConstString name)
Change the name of the current ValueObject.
virtual AddrAndType GetAddressOf (bool scalar_is_load_address=true)
AddrAndType GetPointerValue ()
lldb::ValueObjectSP GetSyntheticChild (ConstString key) const
lldb::ValueObjectSP GetSyntheticArrayMember (size_t index, bool can_create)
lldb::ValueObjectSP GetSyntheticBitFieldChild (uint32_t from, uint32_t to, bool can_create)
lldb::ValueObjectSP GetSyntheticExpressionPathChild (const char *expression, bool can_create)
virtual lldb::ValueObjectSP GetSyntheticChildAtOffset (uint32_t offset, const CompilerType &type, bool can_create, ConstString name_const_str=ConstString())
virtual lldb::ValueObjectSP GetSyntheticBase (uint32_t offset, const CompilerType &type, bool can_create, ConstString name_const_str=ConstString())
virtual lldb::ValueObjectSP GetDynamicValue (lldb::DynamicValueType valueType)
lldb::DynamicValueType GetDynamicValueType ()
virtual lldb::ValueObjectSP GetStaticValue ()
virtual lldb::ValueObjectSP GetNonSyntheticValue ()
lldb::ValueObjectSP GetSyntheticValue ()
virtual bool HasSyntheticValue ()
virtual bool IsSynthetic ()
lldb::ValueObjectSP GetQualifiedRepresentationIfAvailable (lldb::DynamicValueType dynValue, bool synthValue)
virtual lldb::ValueObjectSP CreateConstantValue (ConstString name)
virtual lldb::ValueObjectSP Dereference (Status &error)
virtual lldb::ValueObjectSP Clone (ConstString new_name)
Creates a copy of the ValueObject with a new name and setting the current ValueObject as its parent.
virtual lldb::ValueObjectSP AddressOf (Status &error)
virtual lldb::addr_t GetLiveAddress ()
virtual void SetLiveAddress (lldb::addr_t addr=LLDB_INVALID_ADDRESS, AddressType address_type=eAddressTypeLoad)
lldb::ValueObjectSP Cast (const CompilerType &compiler_type)
virtual lldb::ValueObjectSP DoCast (const CompilerType &compiler_type)
virtual lldb::ValueObjectSP CastPointerType (const char *name, CompilerType &ast_type)
virtual lldb::ValueObjectSP CastPointerType (const char *name, lldb::TypeSP &type_sp)
lldb::addr_t GetLoadAddress ()
Return the target load address associated with this value object.
llvm::Expected< lldb::ValueObjectSP > CastDerivedToBaseType (CompilerType type, const llvm::ArrayRef< uint32_t > &base_type_indices)
Take a ValueObject whose type is an inherited class, and cast it to 'type', which should be one of its base classes.
llvm::Expected< lldb::ValueObjectSP > CastBaseToDerivedType (CompilerType type, uint64_t offset)
Take a ValueObject whose type is a base class, and cast it to 'type', which should be one of its derived classes.
lldb::ValueObjectSP CastToBasicType (CompilerType type)
lldb::ValueObjectSP CastToEnumType (CompilerType type)
lldb::ValueObjectSP GetVTable ()
If this object represents a C++ class with a vtable, return an object that represents the virtual function table.
void ValueUpdated ()
virtual bool IsDynamic ()
virtual bool DoesProvideSyntheticValue ()
virtual bool IsSyntheticChildrenGenerated ()
virtual void SetSyntheticChildrenGenerated (bool b)
virtual SymbolContextScope * GetSymbolContextScope ()
llvm::Error Dump (Stream &s)
llvm::Error Dump (Stream &s, const DumpValueObjectOptions &options)
lldb::ValueObjectSP Persist ()
bool IsCStringContainer (bool check_pointer=false)
Returns true if this is a char* or a char[] if it is a char* and check_pointer is true, it also checks that the pointer is valid.
std::pair< size_t, bool > ReadPointedString (lldb::WritableDataBufferSP &buffer_sp, Status &error, bool honor_array)
virtual size_t GetPointeeData (DataExtractor &data, uint32_t item_idx=0, uint32_t item_count=1)
virtual uint64_t GetData (DataExtractor &data, Status &error)
virtual bool SetData (DataExtractor &data, Status &error)
virtual bool GetIsConstant () const
bool NeedsUpdating ()
void SetIsConstant ()
lldb::Format GetFormat () const
virtual void SetFormat (lldb::Format format)
virtual lldb::LanguageType GetPreferredDisplayLanguage ()
void SetPreferredDisplayLanguage (lldb::LanguageType lt)
lldb::TypeSummaryImplSP GetSummaryFormat ()
void SetSummaryFormat (lldb::TypeSummaryImplSP format)
void SetDerefValobj (ValueObject *deref)
ValueObject * GetDerefValobj ()
void SetValueFormat (lldb::TypeFormatImplSP format)
lldb::TypeFormatImplSP GetValueFormat ()
void SetSyntheticChildren (const lldb::SyntheticChildrenSP &synth_sp)
lldb::SyntheticChildrenSP GetSyntheticChildren ()
virtual ValueObject * GetParent ()
virtual const ValueObject * GetParent () const
ValueObject * GetNonBaseClassParent ()
void SetAddressTypeOfChildren (AddressType at)
AddressType GetAddressTypeOfChildren ()
void SetHasCompleteType ()
virtual bool MightHaveChildren ()
Find out if a ValueObject might have children.
virtual lldb::VariableSP GetVariable ()
virtual bool IsRuntimeSupportValue ()
virtual uint64_t GetLanguageFlags ()
virtual void SetLanguageFlags (uint64_t flags)
llvm::ArrayRef< uint8_t > GetLocalBuffer () const
Returns the local buffer that this ValueObject points to if it's available.
Static Public Member Functions
static lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx)
static lldb::ValueObjectSP CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext &exe_ctx, const EvaluateExpressionOptions &options)
static lldb::ValueObjectSP CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext &exe_ctx, CompilerType type, bool do_deref=true)
Given an address either create a value object containing the value at that address, or create a value object containing the address itself (pointer value), depending on whether the parameter 'do_deref' is true or false.
static lldb::ValueObjectSP CreateValueObjectFromData (llvm::StringRef name, const DataExtractor &data, const ExecutionContext &exe_ctx, CompilerType type)
static lldb::ValueObjectSP CreateValueObjectFromAPInt (lldb::TargetSP target, const llvm::APInt &v, CompilerType type, llvm::StringRef name)
Create a value object containing the given APInt value.
static lldb::ValueObjectSP CreateValueObjectFromAPFloat (lldb::TargetSP target, const llvm::APFloat &v, CompilerType type, llvm::StringRef name)
Create a value object containing the given APFloat value.
static lldb::ValueObjectSP CreateValueObjectFromScalar (lldb::TargetSP target, Scalar &s, CompilerType type, llvm::StringRef name)
Create a value object containing the given Scalar value.
static lldb::ValueObjectSP CreateValueObjectFromBool (lldb::TargetSP target, bool value, llvm::StringRef name)
Create a value object containing the given boolean value.
static lldb::ValueObjectSP CreateValueObjectFromNullptr (lldb::TargetSP target, CompilerType type, llvm::StringRef name)
Create a nullptr value object with the specified type (must be a nullptr type).
Protected Types
typedef ClusterManager< ValueObject > ValueObjectManager
Protected Member Functions
ValueObject (ExecutionContextScope *exe_scope, ValueObjectManager &manager, AddressType child_ptr_or_ref_addr_type=eAddressTypeLoad)
Use this constructor to create a "root variable object".
ValueObject (ValueObject &parent)
Use this constructor to create a ValueObject owned by another ValueObject.
ValueObjectManager * GetManager ()
virtual bool UpdateValue ()=0
virtual LazyBool CanUpdateWithInvalidExecutionContext ()
virtual void CalculateDynamicValue (lldb::DynamicValueType use_dynamic)
virtual lldb::DynamicValueType GetDynamicValueTypeImpl ()
virtual bool HasDynamicValueTypeInfo ()
virtual void CalculateSyntheticValue ()
virtual ValueObject * CreateChildAtIndex (size_t idx)
Should only be called by ValueObject::GetChildAtIndex().
virtual ValueObject * CreateSyntheticArrayMember (size_t idx)
Should only be called by ValueObject::GetSyntheticArrayMember().
virtual llvm::Expected< uint32_t > CalculateNumChildren (uint32_t max=UINT32_MAX)=0
Should only be called by ValueObject::GetNumChildren().
void SetNumChildren (uint32_t num_children)
void SetValueDidChange (bool value_changed)
void SetValueIsValid (bool valid)
void ClearUserVisibleData (uint32_t items=ValueObject::eClearUserVisibleDataItemsAllStrings)
void AddSyntheticChild (ConstString key, ValueObject *valobj)
DataExtractor & GetDataExtractor ()
void ClearDynamicTypeInformation ()
virtual CompilerType GetCompilerTypeImpl ()=0
const char * GetLocationAsCStringImpl (const Value &value, const DataExtractor &data)
bool IsChecksumEmpty ()
void SetPreferredDisplayLanguageIfNeeded (lldb::LanguageType)
virtual void DoUpdateChildrenAddressType (ValueObject &valobj)
Protected Attributes
ValueObject * m_parent = nullptr
The parent value object, or nullptr if this has no parent.
ValueObject * m_root = nullptr
The root of the hierarchy for this ValueObject (or nullptr if never calculated).
EvaluationPoint m_update_point
Stores both the stop id and the full context at which this value was last updated.
ConstString m_name
The name of this object.
DataExtractor m_data
A data extractor that can be used to extract the value.
Value m_value
Status m_error
An error object that can describe any errors that occur when updating values.
std::string m_value_str
Cached value string that will get cleared if/when the value is updated.
std::string m_old_value_str
Cached old value string from the last time the value was gotten.
std::string m_location_str
Cached location string that will get cleared if/when the value is updated.
std::string m_summary_str
Cached summary string that will get cleared if/when the value is updated.
std::string m_object_desc_str
Cached result of the "object printer".
CompilerType m_override_type
If the type of the value object should be overridden, the type to impose.
ValueObjectManager * m_manager = nullptr
This object is managed by the root object (any ValueObject that gets created without a parent.) The manager gets passed through all the generations of dependent objects, and will keep the whole cluster of objects alive as long as a shared pointer to any of them has been handed out.
ChildrenManager m_children
std::map< ConstString, ValueObject * > m_synthetic_children
ValueObject * m_dynamic_value = nullptr
ValueObject * m_synthetic_value = nullptr
ValueObject * m_deref_valobj = nullptr
lldb::ValueObjectSP m_addr_of_valobj_sp
We have to hold onto a shared pointer to this one because it is created as an independent ValueObjectConstResult, which isn't managed by us.
lldb::Format m_format = lldb::eFormatDefault
lldb::Format m_last_format = lldb::eFormatDefault
uint32_t m_last_format_mgr_revision = 0
lldb::TypeSummaryImplSP m_type_summary_sp
lldb::TypeFormatImplSP m_type_format_sp
lldb::SyntheticChildrenSP m_synthetic_children_sp
ProcessModID m_user_id_of_forced_summary
AddressType m_address_type_of_ptr_or_ref_children = eAddressTypeInvalid
llvm::SmallVector< uint8_t, 16 > m_value_checksum
lldb::LanguageType m_preferred_display_language = lldb::eLanguageTypeUnknown
uint64_t m_language_flags = 0
UserID m_id
Unique identifier for every value object.
struct lldb_private::ValueObject::Bitflags m_flags
Private Member Functions
void UpdateChildrenAddressType ()
lldb::ValueObjectSP GetValueForExpressionPath_Impl (llvm::StringRef expression_cstr, ExpressionPathScanEndReason *reason_to_stop, ExpressionPathEndResultType *final_value_type, const GetValueForExpressionPathOptions &options, ExpressionPathAftermath *final_task_on_target)
ValueObject (const ValueObject &)=delete
const ValueObject & operator= (const ValueObject &)=delete
Friends
class ValueObjectChild
class ExpressionVariable
class Target
class ValueObjectConstResultImpl
class ValueObjectSynthetic
Detailed Description
ValueObject:
This abstract class provides an interface to a particular value, be it a register, a local or global variable, that is evaluated in some particular scope. The ValueObject also has the capability of being the "child" of some other variable object, and in turn of having children. If a ValueObject is a root variable object - having no parent - then it must be constructed with respect to some particular ExecutionContextScope. If it is a child, it inherits the ExecutionContextScope from its parent. The ValueObject will update itself if necessary before fetching its value, summary, object description, etc. But it will always update itself in the ExecutionContextScope with which it was originally created. A brief note on life cycle management for ValueObjects. This is a little tricky because a ValueObject can contain various other ValueObjects - the Dynamic Value, its children, the dereference value, etc. Any one of these can be handed out as a shared pointer, but for that contained value object to be valid, the root object and potentially other of the value objects need to stay around. We solve this problem by handing out shared pointers to the Value Object and any of its dependents using a shared ClusterManager. This treats each shared pointer handed out for the entire cluster as a reference to the whole cluster. The whole cluster will stay around until the last reference is released.
The ValueObject mostly handle this automatically, if a value object is made with a Parent ValueObject, then it adds itself to the ClusterManager of the parent. It does mean that external to the ValueObjects we should only ever make available ValueObjectSP's, never ValueObjects or pointers to them. So all the "Root level" ValueObject derived constructors should be private, and should implement a Create function that new's up object and returns a Shared Pointer that it gets from the GetSP() method.
However, if you are making an derived ValueObject that will be contained in a parent value object, you should just hold onto a pointer to it internally, and by virtue of passing the parent ValueObject into its constructor, it will be added to the ClusterManager for the parent. Then if you ever hand out a Shared Pointer to the contained ValueObject, just do so by calling GetSP() on the contained object.
Definition at line 105 of file ValueObject.h.
Member Typedef Documentation
ValueObjectManager
typedef ClusterManager<ValueObject> lldb_private::ValueObject::ValueObjectManager protected
Definition at line 892 of file ValueObject.h.
Member Enumeration Documentation
ClearUserVisibleDataItems
enum lldb_private::ValueObject::ClearUserVisibleDataItems
Enumerator
eClearUserVisibleDataItemsNothing
eClearUserVisibleDataItemsValue
eClearUserVisibleDataItemsSummary
eClearUserVisibleDataItemsLocation
eClearUserVisibleDataItemsDescription
eClearUserVisibleDataItemsSyntheticChildren
eClearUserVisibleDataItemsAllStrings
eClearUserVisibleDataItemsAll
Definition at line 182 of file ValueObject.h.
ExpressionPathAftermath
enum lldb_private::ValueObject::ExpressionPathAftermath
Enumerator
eExpressionPathAftermathNothing
Just return it.
eExpressionPathAftermathDereference
Dereference the target.
eExpressionPathAftermathTakeAddress
Take target's address.
Definition at line 173 of file ValueObject.h.
ExpressionPathEndResultType
enum lldb_private::ValueObject::ExpressionPathEndResultType
Enumerator
eExpressionPathEndResultTypePlain
Anything but...
eExpressionPathEndResultTypeBitfield
A bitfield.
eExpressionPathEndResultTypeBoundedRange
A range [low-high].
eExpressionPathEndResultTypeUnboundedRange
A range [].
eExpressionPathEndResultTypeValueObjectList
Several items in a VOList.
eExpressionPathEndResultTypeInvalid
Definition at line 159 of file ValueObject.h.
ExpressionPathScanEndReason
enum lldb_private::ValueObject::ExpressionPathScanEndReason
Enumerator
eExpressionPathScanEndReasonEndOfString
Out of data to parse.
eExpressionPathScanEndReasonNoSuchChild
Child element not found.
eExpressionPathScanEndReasonNoSuchSyntheticChild
(Synthetic) child element not found.
eExpressionPathScanEndReasonEmptyRangeNotAllowed
[] only allowed for arrays.
eExpressionPathScanEndReasonDotInsteadOfArrow
. used when -> should be used.
eExpressionPathScanEndReasonArrowInsteadOfDot
-> used when . should be used.
eExpressionPathScanEndReasonFragileIVarNotAllowed
ObjC ivar expansion not allowed.
eExpressionPathScanEndReasonRangeOperatorNotAllowed
[] not allowed by options.
eExpressionPathScanEndReasonRangeOperatorInvalid
[] not valid on objects other than scalars, pointers or arrays.
eExpressionPathScanEndReasonArrayRangeOperatorMet
[] is good for arrays, but I cannot parse it.
eExpressionPathScanEndReasonBitfieldRangeOperatorMet
[] is good for bitfields, but I cannot parse after it.
eExpressionPathScanEndReasonUnexpectedSymbol
Something is malformed in he expression.
eExpressionPathScanEndReasonTakingAddressFailed
Impossible to apply & operator.
eExpressionPathScanEndReasonDereferencingFailed
Impossible to apply * operator.
eExpressionPathScanEndReasonRangeOperatorExpanded
[] was expanded into a VOList.
eExpressionPathScanEndReasonSyntheticValueMissing
getting the synthetic children failed.
eExpressionPathScanEndReasonUnknown
Definition at line 123 of file ValueObject.h.
GetExpressionPathFormat
enum lldb_private::ValueObject::GetExpressionPathFormat
Enumerator
eGetExpressionPathFormatDereferencePointers
eGetExpressionPathFormatHonorPointers
Definition at line 107 of file ValueObject.h.
PrintableRepresentationSpecialCases
enum class lldb_private::ValueObject::PrintableRepresentationSpecialCases : bool strong
Enumerator
eDisable
eAllow
Definition at line 546 of file ValueObject.h.
ValueObjectRepresentationStyle
enum lldb_private::ValueObject::ValueObjectRepresentationStyle
Enumerator
eValueObjectRepresentationStyleValue
eValueObjectRepresentationStyleSummary
eValueObjectRepresentationStyleLanguageSpecific
eValueObjectRepresentationStyleLocation
eValueObjectRepresentationStyleChildrenCount
eValueObjectRepresentationStyleType
eValueObjectRepresentationStyleName
eValueObjectRepresentationStyleExpressionPath
Definition at line 112 of file ValueObject.h.
Constructor & Destructor Documentation
~ValueObject()
ValueObject::~ValueObject () virtual default
ValueObject() [1/3]
ValueObject::ValueObject (ExecutionContextScope * exe_scope, ValueObjectManager & manager, AddressType child_ptr_or_ref_addr_type = eAddressTypeLoad) protected
Use this constructor to create a "root variable object".
The ValueObject will be locked to this context through-out its lifespan.
Definition at line 99 of file ValueObject.cpp.
References lldb_private::ExecutionContextScope::CalculateTarget(), g_value_obj_uid, lldb_private::ArchSpec::GetAddressByteSize(), lldb_private::ArchSpec::GetByteOrder(), m_address_type_of_ptr_or_ref_children, m_data, m_id, m_manager, and m_update_point.
Referenced by AddSyntheticChild(), lldb_private::ValueObjectCast::Create(), lldb_private::ValueObjectRecognizerSynthesizedValue::Create(), lldb_private::ValueObjectVTable::Create(), CreateChildAtIndex(), lldb_private::ValueObjectConstResult::CreateChildAtIndex(), lldb_private::ValueObjectRegisterSet::CreateChildAtIndex(), lldb_private::ValueObjectVTable::CreateChildAtIndex(), CreateSyntheticArrayMember(), lldb_private::ValueObjectConstResult::CreateSyntheticArrayMember(), lldb_private::ValueObjectRegisterSet::CreateSyntheticArrayMember(), lldb_private::ValueObjectVTable::CreateSyntheticArrayMember(), DoUpdateChildrenAddressType(), lldb_private::ValueObjectVariable::DoUpdateChildrenAddressType(), FollowParentChain(), GetAddressTypeOfChildren(), lldb_private::ValueObject::ChildrenManager::GetChildAtIndex(), GetChildAtIndex(), lldb_private::ValueObjectRegisterSet::GetChildMemberWithName(), GetDerefValobj(), GetDynamicValueType(), GetExpressionPath(), GetFormat(), GetModule(), GetNonBaseClassParent(), GetParent(), GetParent(), lldb_private::ValueObjectCast::GetParent(), lldb_private::ValueObjectCast::GetParent(), GetRoot(), GetSyntheticArrayMember(), GetValueForExpressionPath_Impl(), ValueObjectVTableChild::IsInScope(), operator=(), lldb_private::ValueObject::ChildrenManager::SetChildAtIndex(), SetDerefValobj(), lldb_private::ValueObjectVTable::UpdateValue(), ValueObjectVTableChild::UpdateValue(), ValueObject(), ValueObject(), lldb_private::ValueObjectCast::ValueObjectCast(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectMemory::ValueObjectMemory(), lldb_private::ValueObjectMemory::ValueObjectMemory(), lldb_private::ValueObjectRecognizerSynthesizedValue::ValueObjectRecognizerSynthesizedValue(), lldb_private::ValueObjectRegister::ValueObjectRegister(), lldb_private::ValueObjectRegister::ValueObjectRegister(), lldb_private::ValueObjectRegisterSet::ValueObjectRegisterContext, lldb_private::ValueObjectRegister::ValueObjectRegisterSet, lldb_private::ValueObjectRegisterSet::ValueObjectRegisterSet(), ValueObjectSynthetic, lldb_private::ValueObjectVariable::ValueObjectVariable(), lldb_private::ValueObjectVTable::ValueObjectVTable(), ValueObjectVTableChild::ValueObjectVTableChild(), lldb_private::ValueObjectCast::~ValueObjectCast(), and lldb_private::ValueObjectVTable::~ValueObjectVTable().
ValueObject() [2/3]
ValueObject::ValueObject (ValueObject & parent) protected
Use this constructor to create a ValueObject owned by another ValueObject.
It will inherit the ExecutionContext of its parent.
Definition at line 88 of file ValueObject.cpp.
References g_value_obj_uid, lldb_private::DataExtractor::GetAddressByteSize(), lldb_private::DataExtractor::GetByteOrder(), GetDataExtractor(), GetManager(), GetUpdatePoint(), m_data, m_flags, m_id, lldb_private::ValueObject::Bitflags::m_is_synthetic_children_generated, m_manager, m_parent, m_update_point, and ValueObject().
ValueObject() [3/3]
lldb_private::ValueObject::ValueObject (const ValueObject &) private delete
References ValueObject().
Member Function Documentation
AddressOf()
ValueObjectSP ValueObject::AddressOf (Status & error) virtual
Reimplemented in lldb_private::ValueObjectConstResult, lldb_private::ValueObjectConstResultCast, and lldb_private::ValueObjectConstResultChild.
Definition at line 2877 of file ValueObject.cpp.
References lldb_private::ValueObjectConstResult::Create(), lldb_private::eAddressTypeFile, lldb_private::eAddressTypeHost, lldb_private::eAddressTypeInvalid, lldb_private::eAddressTypeLoad, error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::ExecutionContext::GetAddressByteSize(), GetAddressOf(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), GetCompilerType(), lldb_private::StreamString::GetData(), GetExecutionContextRef(), GetExpressionPath(), lldb_private::CompilerType::GetPointerType(), lldb_private::endian::InlHostByteOrder(), LLDB_INVALID_ADDRESS, m_addr_of_valobj_sp, and m_name.
AddSyntheticChild()
void ValueObject::AddSyntheticChild (ConstString key, ValueObject * valobj) protected
Definition at line 1762 of file ValueObject.cpp.
References m_synthetic_children, and ValueObject().
Referenced by GetSyntheticArrayMember(), GetSyntheticBase(), GetSyntheticBitFieldChild(), GetSyntheticChildAtOffset(), and GetSyntheticExpressionPathChild().
CalculateDynamicValue()
void ValueObject::CalculateDynamicValue (lldb::DynamicValueType use_dynamic) protected virtual
Definition at line 2029 of file ValueObject.cpp.
References ClearDynamicTypeInformation(), lldb::eNoDynamicValues, GetExecutionContextRef(), lldb_private::ExecutionContext::GetProcessPtr(), IsDynamic(), lldb_private::Process::IsPossibleDynamicValue(), and m_dynamic_value.
Referenced by GetDynamicValue().
CalculateNumChildren()
virtual llvm::Expected< uint32_t > lldb_private::ValueObject::CalculateNumChildren (uint32_t max = UINT32_MAX) protected pure virtual
Should only be called by ValueObject::GetNumChildren().
Implemented in lldb_private::ValueObjectCast, lldb_private::ValueObjectChild, lldb_private::ValueObjectConstResult, lldb_private::ValueObjectDynamicValue, lldb_private::ValueObjectMemory, lldb_private::ValueObjectRecognizerSynthesizedValue, lldb_private::ValueObjectRegister, lldb_private::ValueObjectRegisterSet, lldb_private::ValueObjectSynthetic, lldb_private::ValueObjectVariable, lldb_private::ValueObjectVTable, and ValueObjectVTableChild.
References UINT32_MAX.
Referenced by GetNumChildren().
CalculateSyntheticValue()
void ValueObject::CalculateSyntheticValue () protected virtual
Reimplemented in lldb_private::ValueObjectSynthetic.
Definition at line 2008 of file ValueObject.cpp.
References GetTargetSP(), m_synthetic_children_sp, m_synthetic_value, UpdateFormatsIfNeeded(), and ValueObjectSynthetic.
Referenced by GetSyntheticValue(), and HasSyntheticValue().
CanProvideValue()
bool ValueObject::CanProvideValue () virtual
Reimplemented in lldb_private::ValueObjectSynthetic.
Definition at line 3740 of file ValueObject.cpp.
References GetCompilerType(), lldb_private::CompilerType::GetTypeInfo(), and lldb_private::CompilerType::IsValid().
Referenced by DumpPrintableRepresentation(), lldb_private::TypeFormatImpl_EnumType::FormatObject(), lldb_private::TypeFormatImpl_Format::FormatObject(), GetExpressionPath(), GetValueAsAPFloat(), GetValueAsAPSInt(), GetValueAsSigned(), GetValueAsUnsigned(), lldb_private::ValueObjectCast::UpdateValue(), lldb_private::ValueObjectDynamicValue::UpdateValue(), lldb_private::ValueObjectMemory::UpdateValue(), lldb_private::ValueObjectVariable::UpdateValue(), and UpdateValueIfNeeded().
CanUpdateWithInvalidExecutionContext()
virtual LazyBool lldb_private::ValueObject::CanUpdateWithInvalidExecutionContext () inline protected virtual
Reimplemented in lldb_private::ValueObjectChild, lldb_private::ValueObjectDynamicValue, and lldb_private::ValueObjectSynthetic.
Definition at line 1048 of file ValueObject.h.
References lldb_private::eLazyBoolCalculate.
Referenced by lldb_private::ValueObjectChild::CanUpdateWithInvalidExecutionContext(), and NeedsUpdating().
Cast()
ValueObjectSP ValueObject::Cast (const CompilerType & compiler_type)
Definition at line 2925 of file ValueObject.cpp.
References lldb_private::ValueObjectConstResult::Create(), DoCast(), error(), lldb_private::Status::FromErrorString(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::CompilerType::GetByteSize(), GetByteSize(), GetCompilerType(), GetExecutionContextRef(), lldb_private::Value::LoadAddress, and m_value.
Referenced by lldb_private::formatters::GetDesugaredSmartPointerValue().
CastBaseToDerivedType()
llvm::Expected< lldb::ValueObjectSP > ValueObject::CastBaseToDerivedType (CompilerType type, uint64_t offset)
Take a ValueObject whose type is a base class, and cast it to 'type', which should be one of its derived classes.
'base_type_indices' contains the indices of direct base classes on the path from the ValueObject's current type to 'type'
Definition at line 3084 of file ValueObject.cpp.
References CreateValueObjectFromAddress(), error(), GetCompilerType(), GetLoadAddress(), lldb_private::CompilerType::GetNonReferenceType(), lldb_private::CompilerType::GetPointeeType(), lldb_private::CompilerType::GetPointerType(), GetTargetSP(), GetValueAsUnsigned(), lldb_private::CompilerType::IsPointerType(), lldb_private::CompilerType::IsReferenceType(), lldb_private::CompilerType::IsValid(), and lldb_private::CompilerType::TypeDescription().
CastDerivedToBaseType()
llvm::Expected< lldb::ValueObjectSP > ValueObject::CastDerivedToBaseType (CompilerType type, const llvm::ArrayRef< uint32_t > & base_type_indices)
Take a ValueObject whose type is an inherited class, and cast it to 'type', which should be one of its base classes.
'base_type_indices' contains the indices of direct base classes on the path from the ValueObject's current type to 'type'
Definition at line 3013 of file ValueObject.cpp.
References lldb_private::CompilerType::CompareTypes(), CreateValueObjectFromAddress(), GetCompilerType(), lldb_private::CompilerType::GetNonReferenceType(), lldb_private::CompilerType::GetPointeeType(), GetSP(), GetTargetSP(), lldb_private::CompilerType::IsPointerType(), and lldb_private::CompilerType::IsReferenceType().
CastPointerType() [1/2]
ValueObjectSP ValueObject::CastPointerType (const char * name, CompilerType & ast_type) virtual
Definition at line 2965 of file ValueObject.cpp.
References lldb_private::ValueObject::AddrAndType::address, lldb_private::ValueObjectMemory::Create(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), GetExecutionContextRef(), GetPointerValue(), and LLDB_INVALID_ADDRESS.
CastPointerType() [2/2]
ValueObjectSP ValueObject::CastPointerType (const char * name, lldb::TypeSP & type_sp) virtual
Definition at line 2979 of file ValueObject.cpp.
References lldb_private::ValueObject::AddrAndType::address, lldb_private::ValueObjectMemory::Create(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), GetExecutionContextRef(), GetPointerValue(), and LLDB_INVALID_ADDRESS.
CastToBasicType()
lldb::ValueObjectSP ValueObject::CastToBasicType (CompilerType type)
Definition at line 3148 of file ValueObject.cpp.
References lldb_private::ValueObjectConstResult::Create(), lldb_private::Scalar::CreateAPFloatFromAPFloat(), lldb_private::Scalar::CreateAPFloatFromAPSInt(), CreateValueObjectFromAPFloat(), CreateValueObjectFromAPInt(), CreateValueObjectFromBool(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::CompilerType::GetBasicTypeEnumeration(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::CompilerType::GetByteSize(), GetByteSize(), GetCompilerType(), GetExecutionContextRef(), GetTargetSP(), GetValueAsAPFloat(), GetValueAsAPSInt(), GetValueAsUnsigned(), HasFloatingRepresentation(), integer, lldb_private::CompilerType::IsBoolean(), lldb_private::CompilerType::IsEnumerationType(), lldb_private::CompilerType::IsInteger(), lldb_private::CompilerType::IsNullPtrType(), lldb_private::CompilerType::IsPointerType(), lldb_private::CompilerType::IsScalarType(), and lldb_private::CompilerType::IsSigned().
CastToEnumType()
lldb::ValueObjectSP ValueObject::CastToEnumType (CompilerType type)
Definition at line 3304 of file ValueObject.cpp.
References lldb_private::ValueObjectConstResult::Create(), CreateValueObjectFromAPInt(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::CompilerType::GetByteSize(), GetCompilerType(), GetExecutionContextRef(), GetTargetSP(), GetValueAsAPFloat(), GetValueAsAPSInt(), HasFloatingRepresentation(), integer, lldb_private::CompilerType::IsEnumerationType(), lldb_private::CompilerType::IsInteger(), and lldb_private::CompilerType::IsSigned().
ClearDynamicTypeInformation()
void ValueObject::ClearDynamicTypeInformation () protected
Definition at line 242 of file ValueObject.cpp.
References m_flags, m_last_format_mgr_revision, m_override_type, SetSummaryFormat(), SetSyntheticChildren(), and SetValueFormat().
Referenced by CalculateDynamicValue(), and lldb_private::ValueObjectDynamicValue::UpdateValue().
ClearUserVisibleData()
void ValueObject::ClearUserVisibleData (uint32_t items = ValueObject::eClearUserVisibleDataItemsAllStrings) protected
Definition at line 3494 of file ValueObject.cpp.
References eClearUserVisibleDataItemsDescription, eClearUserVisibleDataItemsLocation, eClearUserVisibleDataItemsSummary, eClearUserVisibleDataItemsSyntheticChildren, eClearUserVisibleDataItemsValue, m_location_str, m_object_desc_str, m_summary_str, m_synthetic_value, and m_value_str.
Referenced by SetFormat(), lldb_private::ValueObjectSynthetic::SetFormat(), SetNeedsUpdate(), SetSummaryFormat(), SetSyntheticChildren(), SetValueFormat(), UpdateValueIfNeeded(), and ValueUpdated().
Clone()
lldb::ValueObjectSP ValueObject::Clone (ConstString new_name) virtual
Creates a copy of the ValueObject with a new name and setting the current ValueObject as its parent.
It should be used when we want to change the name of a ValueObject without modifying the actual ValueObject itself (e.g. sythetic child provider).
Definition at line 2961 of file ValueObject.cpp.
References lldb_private::ValueObjectCast::Create(), and GetCompilerType().
CreateChildAtIndex()
ValueObject * ValueObject::CreateChildAtIndex (size_t idx) protected virtual
Should only be called by ValueObject::GetChildAtIndex().
Returns
A ValueObject managed by this ValueObject's manager.
Reimplemented in lldb_private::ValueObjectConstResult, lldb_private::ValueObjectConstResultCast, lldb_private::ValueObjectConstResultChild, lldb_private::ValueObjectRegisterSet, and lldb_private::ValueObjectVTable.
Definition at line 496 of file ValueObject.cpp.
References lldb_private::eAddressTypeInvalid, lldb_private::CompilerType::GetChildCompilerTypeAtIndex(), GetCompilerType(), GetExecutionContextRef(), lldb_private::GetLog(), LLDB_LOG_ERROR, lldb_private::Types, ValueObject(), and ValueObjectChild.
Referenced by GetChildAtIndex().
CreateConstantValue()
ValueObjectSP ValueObject::CreateConstantValue (ConstString name) virtual
Definition at line 2737 of file ValueObject.cpp.
References lldb_private::ValueObjectConstResult::Create(), GetAddressOf(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), GetCompilerType(), GetExecutionContextRef(), GetModule(), lldb_private::Value::GetValueAsData(), GetValueAsUnsigned(), IsBitfield(), m_data, m_error, m_value, lldb_private::DataExtractor::SetAddressByteSize(), lldb_private::DataExtractor::SetByteOrder(), UINT64_MAX, and UpdateValueIfNeeded().
CreateSyntheticArrayMember()
ValueObject * ValueObject::CreateSyntheticArrayMember (size_t idx) protected virtual
Should only be called by ValueObject::GetSyntheticArrayMember().
Returns
A ValueObject managed by this ValueObject's manager.
Reimplemented in lldb_private::ValueObjectConstResult, lldb_private::ValueObjectConstResultCast, lldb_private::ValueObjectConstResultChild, lldb_private::ValueObjectRegisterSet, and lldb_private::ValueObjectVTable.
Definition at line 531 of file ValueObject.cpp.
References lldb_private::eAddressTypeInvalid, lldb_private::CompilerType::GetChildCompilerTypeAtIndex(), GetCompilerType(), GetExecutionContextRef(), lldb_private::GetLog(), GetSyntheticValue(), LLDB_LOG_ERROR, lldb_private::Types, ValueObject(), and ValueObjectChild.
Referenced by GetSyntheticArrayMember().
CreateValueObjectFromAddress()
lldb::ValueObjectSP ValueObject::CreateValueObjectFromAddress (llvm::StringRef name, uint64_t address, const ExecutionContext & exe_ctx, CompilerType type, bool do_deref = true) static
Given an address either create a value object containing the value at that address, or create a value object containing the address itself (pointer value), depending on whether the parameter 'do_deref' is true or false.
Definition at line 3550 of file ValueObject.cpp.
References lldb_private::ValueObjectConstResult::Create(), lldb_private::ExecutionContext::GetAddressByteSize(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::ExecutionContext::GetByteOrder(), lldb_private::CompilerType::GetPointerType(), and lldb_private::Value::LoadAddress.
Referenced by lldb_private::dil::ArrayToPointerConversion(), CastBaseToDerivedType(), CastDerivedToBaseType(), lldb::SBTarget::CreateValueFromAddress(), lldb::SBValue::CreateValueFromAddress(), lldb_private::SyntheticChildrenFrontEnd::CreateValueObjectFromAddress(), lldb_private::formatters::NSAttributedStringSummaryProvider(), lldb_private::formatters::ObjCSELSummaryProvider(), and lldb_private::dil::Interpreter::Visit().
CreateValueObjectFromAPFloat()
lldb::ValueObjectSP ValueObject::CreateValueObjectFromAPFloat (lldb::TargetSP target, const llvm::APFloat & v, CompilerType type, llvm::StringRef name) static
Create a value object containing the given APFloat value.
Definition at line 3607 of file ValueObject.cpp.
References CreateValueObjectFromAPInt().
Referenced by CastToBasicType().
CreateValueObjectFromAPInt()
lldb::ValueObjectSP ValueObject::CreateValueObjectFromAPInt (lldb::TargetSP target, const llvm::APInt & v, CompilerType type, llvm::StringRef name) static
Create a value object containing the given APInt value.
Definition at line 3594 of file ValueObject.cpp.
References CreateValueObjectFromData(), lldb_private::ExecutionContext::GetAddressByteSize(), lldb_private::ExecutionContext::GetByteOrder(), and lldb_private::CompilerType::GetByteSize().
Referenced by CastToBasicType(), CastToEnumType(), and CreateValueObjectFromAPFloat().
CreateValueObjectFromBool()
lldb::ValueObjectSP ValueObject::CreateValueObjectFromBool (lldb::TargetSP target, bool value, llvm::StringRef name) static
Create a value object containing the given boolean value.
Definition at line 3621 of file ValueObject.cpp.
References CreateValueObjectFromData(), lldb::eBasicTypeBool, lldb_private::ExecutionContext::GetAddressByteSize(), lldb_private::ExecutionContext::GetByteOrder(), and lldb_private::CompilerType::GetByteSize().
Referenced by CastToBasicType(), lldb::SBValue::CreateBoolValue(), and lldb_private::dil::Interpreter::Visit().
CreateValueObjectFromData()
lldb::ValueObjectSP ValueObject::CreateValueObjectFromData (llvm::StringRef name, const DataExtractor & data, const ExecutionContext & exe_ctx, CompilerType type) static
Definition at line 3580 of file ValueObject.cpp.
References lldb_private::ValueObjectConstResult::Create(), lldb_private::eAddressTypeLoad, lldb_private::ExecutionContext::GetBestExecutionContextScope(), and LLDB_INVALID_ADDRESS.
Referenced by lldb::SBTarget::CreateValueFromData(), lldb::SBValue::CreateValueFromData(), CreateValueObjectFromAPInt(), CreateValueObjectFromBool(), lldb_private::SyntheticChildrenFrontEnd::CreateValueObjectFromData(), CreateValueObjectFromNullptr(), ExtractFields(), lldb_private::ItaniumABILanguageRuntime::GetExceptionObjectForThread(), lldb::SBType::GetTemplateArgumentValue(), lldb_private::formatters::NSError_SummaryProvider(), and lldb_private::formatters::ObjCSELSummaryProvider().
CreateValueObjectFromExpression() [1/2]
lldb::ValueObjectSP ValueObject::CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext & exe_ctx) static
Definition at line 3527 of file ValueObject.cpp.
References CreateValueObjectFromExpression().
Referenced by lldb::SBTarget::CreateValueFromExpression(), lldb::SBValue::CreateValueFromExpression(), lldb_private::SyntheticChildrenFrontEnd::CreateValueObjectFromExpression(), and CreateValueObjectFromExpression().
CreateValueObjectFromExpression() [2/2]
lldb::ValueObjectSP ValueObject::CreateValueObjectFromExpression (llvm::StringRef name, llvm::StringRef expression, const ExecutionContext & exe_ctx, const EvaluateExpressionOptions & options) static
Definition at line 3534 of file ValueObject.cpp.
References lldb_private::ExecutionContext::GetFrameSP(), and lldb_private::ExecutionContext::GetTargetSP().
CreateValueObjectFromNullptr()
lldb::ValueObjectSP ValueObject::CreateValueObjectFromNullptr (lldb::TargetSP target, CompilerType type, llvm::StringRef name) static
Create a nullptr value object with the specified type (must be a nullptr type).
Definition at line 3644 of file ValueObject.cpp.
References CreateValueObjectFromData(), lldb_private::ExecutionContext::GetAddressByteSize(), lldb_private::ExecutionContext::GetByteOrder(), lldb_private::CompilerType::GetByteSize(), and lldb_private::CompilerType::IsNullPtrType().
CreateValueObjectFromScalar()
lldb::ValueObjectSP ValueObject::CreateValueObjectFromScalar (lldb::TargetSP target, Scalar & s, CompilerType type, llvm::StringRef name) static
Create a value object containing the given Scalar value.
Definition at line 3613 of file ValueObject.cpp.
References lldb_private::ValueObjectConstResult::Create(), and lldb_private::ExecutionContext::GetBestExecutionContextScope().
Referenced by lldb_private::dil::Interpreter::UnaryConversion(), lldb_private::dil::Interpreter::Visit(), lldb_private::dil::Interpreter::Visit(), and lldb_private::dil::Interpreter::Visit().
Dereference()
ValueObjectSP ValueObject::Dereference (Status & error) virtual
Reimplemented in lldb_private::ValueObjectConstResult, lldb_private::ValueObjectConstResultCast, and lldb_private::ValueObjectConstResultChild.
Definition at line 2797 of file ValueObject.cpp.
References lldb_private::eAddressTypeInvalid, error(), lldb_private::Status::FromErrorStringWithFormat(), GetChildMemberWithName(), GetCompilerType(), lldb_private::StreamString::GetData(), lldb_private::CompilerType::GetDereferencedType(), GetExecutionContextRef(), GetExpressionPath(), lldb_private::GetLog(), lldb_private::CompilerType::GetPointeeType(), GetPreferredDisplayLanguage(), GetTypeName(), HasSyntheticValue(), IsSynthetic(), lldb_private::Language::LanguageIsObjC(), LLDB_LOG, m_deref_valobj, lldb_private::ConstString::SetCString(), lldb_private::Types, and ValueObjectChild.
Referenced by DereferenceValueOrAlternate(), lldb_private::formatters::DumpCxxSmartPtrPointerSummary(), lldb_private::FormatEntity::Formatter::DumpValue(), lldb_private::UserExpression::Evaluate(), GetPointeeData(), and lldb_private::formatters::ObjCBOOLSummaryProvider().
DoCast()
ValueObjectSP ValueObject::DoCast (const CompilerType & compiler_type) virtual
Reimplemented in lldb_private::ValueObjectConstResult, lldb_private::ValueObjectConstResultCast, and lldb_private::ValueObjectConstResultChild.
Definition at line 2921 of file ValueObject.cpp.
References lldb_private::ValueObjectCast::Create(), and GetName().
Referenced by Cast().
DoesProvideSyntheticValue()
virtual bool lldb_private::ValueObject::DoesProvideSyntheticValue () inline virtual
Reimplemented in lldb_private::ValueObjectSynthetic.
Definition at line 689 of file ValueObject.h.
DoUpdateChildrenAddressType()
virtual void lldb_private::ValueObject::DoUpdateChildrenAddressType (ValueObject & valobj) inline protected virtual
Reimplemented in lldb_private::ValueObjectVariable.
Definition at line 1105 of file ValueObject.h.
References ValueObject().
Referenced by UpdateChildrenAddressType().
Dump() [1/2]
llvm::Error ValueObject::Dump (Stream & s)
Definition at line 2727 of file ValueObject.cpp.
References Dump().
Referenced by Dump().
Dump() [2/2]
llvm::Error ValueObject::Dump (Stream & s, const DumpValueObjectOptions & options)
Definition at line 2731 of file ValueObject.cpp.
References lldb_private::ValueObjectPrinter::PrintValueObject().
DumpPrintableRepresentation()
bool ValueObject::DumpPrintableRepresentation (Stream & s, ValueObjectRepresentationStyle val_obj_display = eValueObjectRepresentationStyleSummary, lldb::Format custom_format = lldb::eFormatInvalid, PrintableRepresentationSpecialCases special = PrintableRepresentationSpecialCases::eAllow, bool do_dump_error = true)
Definition at line 1343 of file ValueObject.cpp.
References lldb_private::Flags::AnySet(), CanProvideValue(), eAllow, lldb::eByteOrderInvalid, lldb::eFormatBinary, lldb::eFormatBoolean, lldb::eFormatBytes, lldb::eFormatBytesWithASCII, lldb::eFormatChar, lldb::eFormatCharArray, lldb::eFormatCharPrintable, lldb::eFormatComplex, lldb::eFormatComplexFloat, lldb::eFormatComplexInteger, lldb::eFormatCString, lldb::eFormatDecimal, lldb::eFormatDefault, lldb::eFormatEnum, lldb::eFormatFloat, lldb::eFormatFloat128, lldb::eFormatHex, lldb::eFormatHexUppercase, lldb::eFormatInvalid, lldb::eFormatOctal, lldb::eFormatOSType, lldb::eFormatPointer, lldb::eFormatUnicode16, lldb::eFormatUnicode32, lldb::eFormatUnsigned, lldb::eFormatVectorOfChar, lldb::eFormatVectorOfFloat32, lldb::eFormatVectorOfFloat64, lldb::eFormatVectorOfSInt16, lldb::eFormatVectorOfSInt32, lldb::eFormatVectorOfSInt64, lldb::eFormatVectorOfSInt8, lldb::eFormatVectorOfUInt128, lldb::eFormatVectorOfUInt16, lldb::eFormatVectorOfUInt32, lldb::eFormatVectorOfUInt64, lldb::eFormatVectorOfUInt8, error(), eValueObjectRepresentationStyleChildrenCount, eValueObjectRepresentationStyleExpressionPath, eValueObjectRepresentationStyleLanguageSpecific, eValueObjectRepresentationStyleLocation, eValueObjectRepresentationStyleName, eValueObjectRepresentationStyleSummary, eValueObjectRepresentationStyleType, eValueObjectRepresentationStyleValue, GetChildAtIndex(), GetCompilerType(), GetExpressionPath(), GetLocationAsCString(), GetName(), GetNumChildren(), GetNumChildrenIgnoringErrors(), GetObjectDescription(), lldb_private::FormatManager::GetSingleItemFormat(), lldb_private::StreamString::GetString(), lldb_private::ConstString::GetStringRef(), GetSummaryAsCString(), GetTypeInfo(), GetTypeName(), GetValueAsCString(), IsCStringContainer(), m_error, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream(), ReadPointedString(), SetFormat(), lldb_private::Flags::Test(), and lldb_private::toString().
Referenced by lldb_private::FormatEntity::Formatter::DumpValue().
FollowParentChain()
ValueObject * ValueObject::FollowParentChain (std::function< bool(ValueObject *)> f)
Given a ValueObject, loop over itself and its parent, and its parent's parent, .
. until either the given callback returns false, or you end up at a null pointer
Definition at line 3677 of file ValueObject.cpp.
References m_parent, and ValueObject().
Referenced by GetRoot().
GetAddressOf()
ValueObject::AddrAndType ValueObject::GetAddressOf (bool scalar_is_load_address = true) virtual
Reimplemented in lldb_private::ValueObjectConstResult, and lldb_private::ValueObjectConstResultChild.
Definition at line 1608 of file ValueObject.cpp.
References lldb_private::eAddressTypeLoad, lldb_private::Value::FileAddress, lldb_private::Value::HostAddress, lldb_private::Value::Invalid, IsBitfield(), LLDB_INVALID_ADDRESS, lldb_private::Value::LoadAddress, m_value, lldb_private::Value::Scalar, and UpdateValueIfNeeded().
Referenced by AddressOf(), CreateConstantValue(), lldb_private::formatters::GetArrayAddressOrPointerValue(), GetLoadAddress(), GetPointeeData(), GetValueAsBool(), lldb_private::ItaniumABILanguageRuntime::GetVTableInfo(), ReadPointedString(), and lldb_private::ValueObjectVTable::UpdateValue().
GetAddressTypeOfChildren()
AddressType ValueObject::GetAddressTypeOfChildren ()
Definition at line 3687 of file ValueObject.cpp.
References lldb_private::eAddressTypeInvalid, GetAddressTypeOfChildren(), GetRoot(), m_address_type_of_ptr_or_ref_children, and ValueObject().
Referenced by GetAddressTypeOfChildren(), GetPointerValue(), GetVTableAddress(), and lldb_private::ValueObjectChild::UpdateValue().
GetBitfieldBitOffset()
virtual uint32_t lldb_private::ValueObject::GetBitfieldBitOffset () inline virtual
Reimplemented in lldb_private::ValueObjectChild.
Definition at line 426 of file ValueObject.h.
Referenced by lldb_private::TypeFormatImpl_Format::FormatObject(), IsBitfield(), and ResolveValue().
GetBitfieldBitSize()
virtual uint32_t lldb_private::ValueObject::GetBitfieldBitSize () inline virtual
Reimplemented in lldb_private::ValueObjectChild.
Definition at line 424 of file ValueObject.h.
Referenced by lldb_private::FormatEntity::Formatter::DumpValue(), lldb_private::TypeFormatImpl_Format::FormatObject(), lldb_private::FormatManager::GetPossibleMatches(), IsBitfield(), and ResolveValue().
GetByteOffset()
virtual lldb::offset_t lldb_private::ValueObject::GetByteOffset () inline virtual
Reimplemented in lldb_private::ValueObjectChild.
Definition at line 422 of file ValueObject.h.
GetByteSize()
virtual llvm::Expected< uint64_t > lldb_private::ValueObject::GetByteSize () pure virtual
Implemented in lldb_private::ValueObjectCast, lldb_private::ValueObjectChild, lldb_private::ValueObjectConstResult, lldb_private::ValueObjectDynamicValue, lldb_private::ValueObjectMemory, lldb_private::ValueObjectRecognizerSynthesizedValue, lldb_private::ValueObjectRegister, lldb_private::ValueObjectRegisterSet, lldb_private::ValueObjectSynthetic, lldb_private::ValueObjectVariable, lldb_private::ValueObjectVTable, and ValueObjectVTableChild.
Referenced by Cast(), CastToBasicType(), GetPointeeData(), GetSyntheticBitFieldChild(), SetData(), SetValueFromCString(), and SetValueFromInteger().
GetChildAtIndex()
ValueObjectSP ValueObject::GetChildAtIndex (uint32_t idx, bool can_create = true) virtual
Reimplemented in lldb_private::ValueObjectSynthetic.
Definition at line 379 of file ValueObject.cpp.
References CreateChildAtIndex(), GetNumChildrenIgnoringErrors(), GetSP(), IsPossibleDynamicType(), m_children, UpdateValueIfNeeded(), and ValueObject().
Referenced by DumpPrintableRepresentation(), lldb_private::ValueObjectPrinter::GenerateChild(), lldb_private::formatters::GetFirstValueOfLibCXXCompressedPair(), GetPointeeData(), lldb_private::formatters::GetSecondValueOfLibCXXCompressedPair(), lldb_private::formatters::ObjCBOOLSummaryProvider(), lldb_private::ValueObjectPrinter::PrintChildrenOneLiner(), and lldb_private::FormatManager::ShouldPrintAsOneLiner().
GetChildAtNamePath()
lldb::ValueObjectSP ValueObject::GetChildAtNamePath (llvm::ArrayRef< llvm::StringRef > names)
Definition at line 400 of file ValueObject.cpp.
References GetSP().
Referenced by ExtractMsvcStlStringData(), and lldb_private::formatters::LibStdcppStringSummaryProvider().
GetChildMemberWithName()
ValueObjectSP ValueObject::GetChildMemberWithName (llvm::StringRef name, bool can_create = true) virtual
Reimplemented in lldb_private::ValueObjectRegisterSet, and lldb_private::ValueObjectSynthetic.
Definition at line 420 of file ValueObject.cpp.
References GetCompilerType(), lldb_private::CompilerType::GetIndexOfChildMemberWithName(), GetSP(), IsPossibleDynamicType(), and UpdateValueIfNeeded().
Referenced by Dereference(), formatStringViewImpl(), formatStringViewImpl(), lldb_private::formatters::GetChildMemberWithName(), lldb_private::formatters::GetFirstValueOfLibCXXCompressedPair(), lldb_private::formatters::GetSecondValueOfLibCXXCompressedPair(), LibCxx::GetSizeMember(), LibStdcpp::GetSizeMember(), LibCxx::GetStartMember(), LibStdcpp::GetStartMember(), lldb_private::formatters::GetValueOrOldCompressedPair(), lldb_private::formatters::IsMsvcStlMapLike(), lldb_private::formatters::IsMsvcStlTreeIter(), lldb_private::formatters::LibcxxChronoMonthSummaryProvider(), LibcxxChronoTimepointDaysSummaryProvider(), LibcxxChronoTimePointSecondsSummaryProvider(), lldb_private::formatters::LibcxxChronoWeekdaySummaryProvider(), lldb_private::formatters::LibcxxChronoYearMonthDaySummaryProvider(), LibcxxExtractOrderingValue(), LibStdcppExtractOrderingValue(), and MsvcStlExtractOrderingValue().
GetCompilerType()
CompilerType ValueObject::GetCompilerType ()
Definition at line 252 of file ValueObject.cpp.
References GetCompilerTypeImpl(), GetExecutionContextRef(), GetObjectRuntimeLanguage(), GetProcessSP(), GetUpdatePoint(), m_flags, and m_override_type.
Referenced by AddressOf(), lldb_private::dil::ArrayToPointerConversion(), lldb_private::ValueObjectCast::CalculateNumChildren(), lldb_private::ValueObjectChild::CalculateNumChildren(), lldb_private::ValueObjectConstResult::CalculateNumChildren(), lldb_private::ValueObjectDynamicValue::CalculateNumChildren(), lldb_private::ValueObjectRegister::CalculateNumChildren(), lldb_private::ValueObjectVariable::CalculateNumChildren(), CanProvideValue(), Cast(), CastBaseToDerivedType(), CastDerivedToBaseType(), CastToBasicType(), CastToEnumType(), Clone(), lldb_private::formatters::CMTimeSummaryProvider(), CopyExpressionResult(), lldb_private::AppleObjCRuntime::CouldHaveDynamicValue(), lldb_private::GNUstepObjCRuntime::CouldHaveDynamicValue(), CreateChildAtIndex(), CreateConstantValue(), CreateSyntheticArrayMember(), Dereference(), DerefToNSErrorPointer(), lldb_private::ValueObjectVariable::DoUpdateChildrenAddressType(), DumpPrintableRepresentation(), lldb_private::FormatEntity::Formatter::DumpValue(), ExtractFields(), lldb_private::AppleObjCRuntime::FixUpDynamicType(), lldb_private::GNUstepObjCRuntime::FixUpDynamicType(), lldb_private::ItaniumABILanguageRuntime::FixUpDynamicType(), lldb_private::ValueObjectConstResult::GetByteSize(), lldb_private::ValueObjectVariable::GetByteSize(), GetChildMemberWithName(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), lldb_private::ValueObjectConstResultCast::GetCompilerType(), lldb_private::ValueObjectConstResultChild::GetCompilerType(), lldb_private::formatters::GetDesugaredSmartPointerValue(), lldb_private::ValueObjectChild::GetDisplayTypeName(), lldb_private::ValueObjectConstResult::GetDisplayTypeName(), lldb_private::ValueObjectDynamicValue::GetDisplayTypeName(), lldb_private::ItaniumABILanguageRuntime::GetDynamicTypeAndAddress(), GetExpressionPath(), lldb_private::CPlusPlusLanguage::GetHardcodedSummaries(), lldb_private::CPlusPlusLanguage::GetHardcodedSynthetics(), GetIndexOfChildWithName(), lldb_private::AppleObjCRuntime::GetObjectDescription(), GetObjectRuntimeLanguage(), GetPointeeData(), lldb_private::ObjCLanguage::GetPossibleFormattersMatches(), lldb_private::FormatManager::GetPossibleMatches(), GetQualifiedTypeName(), lldb_private::ValueObjectChild::GetQualifiedTypeName(), GetSummaryAsCString(), GetSyntheticBitFieldChild(), GetTypeImpl(), GetTypeInfo(), GetTypeName(), lldb_private::ValueObjectChild::GetTypeName(), lldb_private::ValueObjectConstResult::GetTypeName(), lldb_private::ValueObjectRegister::GetTypeName(), GetValueAsAPFloat(), GetValueAsAPSInt(), GetValueAsBool(), GetVTableAddress(), lldb_private::ItaniumABILanguageRuntime::GetVTableInfo(), lldb_private::formatters::GetWCharByteSize(), IsArrayType(), IsIntegerType(), lldb_private::formatters::IsMsvcStlOrdering(), lldb_private::formatters::IsMsvcStlStringType(), lldb_private::formatters::IsMsvcStlStringViewType(), lldb_private::ObjCLanguage::IsNilReference(), IsPointerOrReferenceType(), IsPointerType(), IsPossibleDynamicType(), IsScalarType(), lldb_private::formatters::NSAttributedStringSummaryProvider(), lldb_private::formatters::NSBundleSummaryProvider(), lldb_private::formatters::NSNotificationSummaryProvider(), lldb_private::formatters::NSStringSummaryProvider(), lldb_private::formatters::NSTimeZoneSummaryProvider(), lldb_private::formatters::NSURLSummaryProvider(), lldb_private::formatters::ObjCBOOLSummaryProvider(), lldb_private::formatters::ObjCSELSummaryProvider(), lldb_private::ValueObjectPrinter::PrintValueAndSummaryIfNeeded(), ReadPointedString(), SetData(), SetValueFromCString(), SetValueFromInteger(), SetValueFromInteger(), lldb_private::FormatManager::ShouldPrintAsOneLiner(), lldb_private::ValueObjectCast::UpdateValue(), lldb_private::ValueObjectChild::UpdateValue(), and lldb_private::ValueObjectVariable::UpdateValue().
GetCompilerTypeImpl()
virtual CompilerType lldb_private::ValueObject::GetCompilerTypeImpl () protected pure virtual
Implemented in lldb_private::ValueObjectCast, lldb_private::ValueObjectChild, lldb_private::ValueObjectConstResult, lldb_private::ValueObjectDynamicValue, lldb_private::ValueObjectMemory, lldb_private::ValueObjectRecognizerSynthesizedValue, lldb_private::ValueObjectRegister, lldb_private::ValueObjectRegisterSet, lldb_private::ValueObjectSynthetic, lldb_private::ValueObjectVariable, lldb_private::ValueObjectVTable, and ValueObjectVTableChild.
Referenced by GetCompilerType().
GetData()
uint64_t ValueObject::GetData (DataExtractor & data, Status & error) virtual
Definition at line 774 of file ValueObject.cpp.
References error(), lldb_private::DataExtractor::GetByteSize(), GetExecutionContextRef(), GetModule(), m_data, m_value, lldb_private::DataExtractor::SetAddressByteSize(), lldb_private::DataExtractor::SetByteOrder(), and UpdateValueIfNeeded().
Referenced by CharSummaryProvider(), lldb_private::TypeFormatImpl_EnumType::FormatObject(), lldb_private::TypeFormatImpl_Format::FormatObject(), lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::GetChildAtIndex(), GetVTableAddress(), lldb_private::formatters::ObjCSELSummaryProvider(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), and lldb_private::formatters::WCharSummaryProvider().
GetDataExtractor()
DataExtractor & ValueObject::GetDataExtractor () protected
Definition at line 282 of file ValueObject.cpp.
References m_data, and UpdateValueIfNeeded().
Referenced by GetSyntheticBitFieldChild(), ReadPointedString(), and ValueObject().
GetDeclaration()
bool ValueObject::GetDeclaration (Declaration & decl) virtual
Reimplemented in lldb_private::ValueObjectDynamicValue, lldb_private::ValueObjectSynthetic, and lldb_private::ValueObjectVariable.
Definition at line 1757 of file ValueObject.cpp.
References lldb_private::Declaration::Clear().
Referenced by lldb_private::ValueObjectDynamicValue::GetDeclaration(), and lldb_private::ValueObjectSynthetic::GetDeclaration().
GetDerefValobj()
ValueObject * lldb_private::ValueObject::GetDerefValobj () inline
Definition at line 810 of file ValueObject.h.
References m_deref_valobj, and ValueObject().
GetDisplayTypeName()
virtual ConstString lldb_private::ValueObject::GetDisplayTypeName () inline virtual
Reimplemented in lldb_private::ValueObjectChild, lldb_private::ValueObjectConstResult, lldb_private::ValueObjectDynamicValue, lldb_private::ValueObjectMemory, lldb_private::ValueObjectSynthetic, lldb_private::ValueObjectVariable, and lldb_private::ValueObjectVTable.
Definition at line 367 of file ValueObject.h.
References GetTypeName().
Referenced by lldb_private::ValueObjectPrinter::PrintDecl().
GetDynamicValue()
ValueObjectSP ValueObject::GetDynamicValue (lldb::DynamicValueType valueType) virtual
Reimplemented in lldb_private::ValueObjectConstResult, and lldb_private::ValueObjectSynthetic.
Definition at line 2043 of file ValueObject.cpp.
References CalculateDynamicValue(), lldb::eNoDynamicValues, IsDynamic(), and m_dynamic_value.
Referenced by GetQualifiedRepresentationIfAvailable().
GetDynamicValueType()
lldb::DynamicValueType ValueObject::GetDynamicValueType ()
Definition at line 3696 of file ValueObject.cpp.
References lldb::eNoDynamicValues, GetDynamicValueTypeImpl(), HasDynamicValueTypeInfo(), m_parent, and ValueObject().
Referenced by lldb_private::FormatEntity::Formatter::DumpValue(), lldb_private::DumpValueObjectOptions::DumpValueObjectOptions(), and UpdateFormatsIfNeeded().
GetDynamicValueTypeImpl()
virtual lldb::DynamicValueType lldb_private::ValueObject::GetDynamicValueTypeImpl () inline protected virtual
Reimplemented in lldb_private::ValueObjectDynamicValue.
Definition at line 1054 of file ValueObject.h.
References lldb::eNoDynamicValues.
Referenced by GetDynamicValueType().
GetError()
const Status & ValueObject::GetError ()
Definition at line 287 of file ValueObject.cpp.
References m_error, and UpdateValueIfNeeded().
Referenced by lldb_private::ValueObjectPrinter::GetValueSummaryError(), and lldb_private::ValueObjectChild::UpdateValue().
GetExecutionContextRef()
const ExecutionContextRef & lldb_private::ValueObject::GetExecutionContextRef () const inline
Definition at line 330 of file ValueObject.h.
References m_update_point.
Referenced by AddressOf(), CalculateDynamicValue(), lldb_private::ValueObjectCast::CalculateNumChildren(), lldb_private::ValueObjectChild::CalculateNumChildren(), lldb_private::ValueObjectConstResult::CalculateNumChildren(), lldb_private::ValueObjectDynamicValue::CalculateNumChildren(), lldb_private::ValueObjectMemory::CalculateNumChildren(), lldb_private::ValueObjectRegister::CalculateNumChildren(), lldb_private::ValueObjectVariable::CalculateNumChildren(), Cast(), CastPointerType(), CastPointerType(), CastToBasicType(), CastToEnumType(), lldb_private::ValueObjectSynthetic::CopyValueData(), CreateChildAtIndex(), CreateConstantValue(), CreateSyntheticArrayMember(), lldb_private::formatters::CXXFunctionPointerSummaryProvider(), Dereference(), lldb_private::ValueObjectVariable::DoUpdateChildrenAddressType(), ExtractFields(), lldb_private::StringSummaryFormat::FormatObject(), lldb_private::TypeFormatImpl_EnumType::FormatObject(), lldb_private::TypeFormatImpl_Format::FormatObject(), lldb_private::ValueObjectCast::GetByteSize(), lldb_private::ValueObjectConstResult::GetByteSize(), lldb_private::ValueObjectDynamicValue::GetByteSize(), lldb_private::ValueObjectMemory::GetByteSize(), lldb_private::ValueObjectVariable::GetByteSize(), lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::GetChildAtIndex(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), GetCompilerType(), lldb_private::ValueObjectRegister::GetCompilerTypeImpl(), GetData(), lldb_private::ValueObjectConstResult::GetDynamicValue(), lldb_private::AppleObjCRuntime::GetObjectDescription(), GetObjectDescription(), GetPointeeData(), lldb_private::FormatManager::GetPossibleMatches(), GetSummaryAsCString(), GetSyntheticBase(), GetSyntheticChildAtOffset(), GetVBaseBitOffset(), lldb_private::ItaniumABILanguageRuntime::GetVTableInfo(), lldb_private::ValueObjectVariable::IsInScope(), IsPossibleDynamicType(), lldb_private::formatters::NSError_SummaryProvider(), lldb_private::formatters::ObjCSELSummaryProvider(), ReadPointedString(), ResolveValue(), SetData(), lldb_private::ValueObjectVariable::SetData(), SetValueFromCString(), lldb_private::ValueObjectVariable::SetValueFromCString(), lldb_private::ValueObjectCast::UpdateValue(), lldb_private::ValueObjectChild::UpdateValue(), lldb_private::ValueObjectDynamicValue::UpdateValue(), lldb_private::ValueObjectMemory::UpdateValue(), lldb_private::ValueObjectRegister::UpdateValue(), lldb_private::ValueObjectRegisterSet::UpdateValue(), lldb_private::ValueObjectVariable::UpdateValue(), and ValueObjectVTableChild::UpdateValue().
GetExpressionPath()
void ValueObject::GetExpressionPath (Stream & s, GetExpressionPathFormat epformat = eGetExpressionPathFormatDereferencePointers) virtual
Reimplemented in lldb_private::ValueObjectRegister, and lldb_private::ValueObjectSynthetic.
Definition at line 2101 of file ValueObject.cpp.
References CanProvideValue(), eGetExpressionPathFormatDereferencePointers, eGetExpressionPathFormatHonorPointers, GetCompilerType(), lldb_private::ConstString::GetCString(), GetExpressionPath(), GetName(), GetNonBaseClassParent(), GetParent(), lldb_private::CompilerType::GetPointeeType(), lldb_private::CompilerType::GetTypeInfo(), GetTypeName(), GetValueAsCString(), GetValueAsUnsigned(), lldb_private::CompilerType::IsArrayType(), IsBaseClass(), IsDereferenceOfParent(), lldb_private::ConstString::IsEmpty(), IsPointerOrReferenceType(), lldb_private::CompilerType::IsPointerType(), LLDB_INVALID_ADDRESS, lldb_private::Value::LoadAddress, m_flags, m_name, m_value, lldb_private::Stream::Printf(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), UpdateValueIfNeeded(), and ValueObject().
Referenced by AddressOf(), Dereference(), DumpPrintableRepresentation(), GetExpressionPath(), lldb_private::ValueObjectSynthetic::GetExpressionPath(), and lldb_private::ValueObjectPrinter::PrintDecl().
GetFormat()
lldb::Format ValueObject::GetFormat () const
Definition at line 3706 of file ValueObject.cpp.
References lldb::eFormatDefault, m_format, m_parent, and ValueObject().
Referenced by GetValueAsCString(), and lldb_private::ValueObjectPrinter::GetValueSummaryError().
GetFrameSP()
lldb::StackFrameSP lldb_private::ValueObject::GetFrameSP () const inline
Definition at line 346 of file ValueObject.h.
References m_update_point.
Referenced by GetPreferredDisplayLanguage().
GetID()
lldb::user_id_t lldb_private::ValueObject::GetID () const inline
Returns a unique id for this ValueObject.
Definition at line 490 of file ValueObject.h.
References m_id.
Referenced by lldb_private::ValueObjectList::FindValueObjectByUID(), and lldb_private::ScriptedSyntheticChildren::FrontEnd::FrontEnd().
GetIndexOfChildWithName()
llvm::Expected< size_t > ValueObject::GetIndexOfChildWithName (llvm::StringRef name) virtual
Reimplemented in lldb_private::ValueObjectRegisterSet, and lldb_private::ValueObjectSynthetic.
Definition at line 414 of file ValueObject.cpp.
References GetCompilerType(), and lldb_private::CompilerType::GetIndexOfChildWithName().
GetIsConstant()
virtual bool lldb_private::ValueObject::GetIsConstant () const inline virtual
Reimplemented in lldb_private::ValueObjectDynamicValue, and lldb_private::ValueObjectSynthetic.
Definition at line 774 of file ValueObject.h.
References m_update_point.
Referenced by UpdateValueIfNeeded().
GetLanguageFlags()
virtual uint64_t lldb_private::ValueObject::GetLanguageFlags () inline virtual
Reimplemented in lldb_private::ValueObjectDynamicValue, and lldb_private::ValueObjectSynthetic.
Definition at line 874 of file ValueObject.h.
References m_language_flags.
Referenced by lldb_private::ValueObjectDynamicValue::GetLanguageFlags(), and lldb_private::ValueObjectSynthetic::GetLanguageFlags().
GetLiveAddress()
virtual lldb::addr_t lldb_private::ValueObject::GetLiveAddress () inline virtual
Reimplemented in lldb_private::ValueObjectConstResult.
Definition at line 634 of file ValueObject.h.
References LLDB_INVALID_ADDRESS.
GetLoadAddress()
lldb::addr_t ValueObject::GetLoadAddress ()
Return the target load address associated with this value object.
Definition at line 2992 of file ValueObject.cpp.
References lldb_private::eAddressTypeFile, lldb_private::eAddressTypeHost, lldb_private::eAddressTypeInvalid, GetAddressOf(), lldb_private::Address::GetLoadAddress(), GetModule(), GetTargetSP(), and LLDB_INVALID_ADDRESS.
Referenced by lldb_private::dil::ArrayToPointerConversion(), and CastBaseToDerivedType().
GetLocalBuffer()
llvm::ArrayRef< uint8_t > ValueObject::GetLocalBuffer () const
Returns the local buffer that this ValueObject points to if it's available.
Returns
The local buffer if this value object's value points to a host address, and if that buffer can be determined. Otherwise, returns an empty ArrayRef.
TODO: Because a ValueObject's Value can point to any arbitrary memory location, it is possible that we can't find what what buffer we're pointing to, and thus also can't know its size. See the comment in Value::m_value for a more thorough explanation of why that is.
Definition at line 858 of file ValueObject.cpp.
References lldb_private::Value::HostAddress, LLDB_INVALID_ADDRESS, m_data, and m_value.
GetLocationAsCString()
virtual const char * lldb_private::ValueObject::GetLocationAsCString () inline virtual
Reimplemented in lldb_private::ValueObjectVariable.
Definition at line 522 of file ValueObject.h.
References GetLocationAsCStringImpl(), m_data, and m_value.
Referenced by DumpPrintableRepresentation(), lldb_private::FormatEntity::Formatter::DumpValue(), and lldb_private::ValueObjectVariable::GetLocationAsCString().
GetLocationAsCStringImpl()
const char * ValueObject::GetLocationAsCStringImpl (const Value & value, const DataExtractor & data) protected
Definition at line 292 of file ValueObject.cpp.
References lldb_private::RegisterInfo::alt_name, lldb::eEncodingVector, lldb_private::RegisterInfo::encoding, lldb_private::Value::FileAddress, lldb_private::DataExtractor::GetAddressByteSize(), lldb_private::Value::GetContextType(), lldb_private::Value::GetRegisterInfo(), lldb_private::Value::GetScalar(), lldb_private::StreamString::GetString(), lldb_private::Value::GetValueType(), lldb_private::Value::HostAddress, lldb_private::Value::Invalid, LLDB_INVALID_ADDRESS, lldb_private::Value::LoadAddress, m_location_str, lldb_private::RegisterInfo::name, lldb_private::Stream::Printf(), lldb_private::Value::RegisterInfo, lldb_private::Value::Scalar, lldb_private::Scalar::ULongLong(), and UpdateValueIfNeeded().
Referenced by GetLocationAsCString(), and lldb_private::ValueObjectVariable::GetLocationAsCString().
GetManager()
ValueObjectManager * lldb_private::ValueObject::GetManager () inline protected
Definition at line 1044 of file ValueObject.h.
References m_manager.
Referenced by ValueObject().
GetModule()
ModuleSP ValueObject::GetModule () virtual
Return the module associated with this value object in case the value is from an executable file and might have its data in sections of the file.
This can be used for variables.
Reimplemented in lldb_private::ValueObjectMemory, and lldb_private::ValueObjectVariable.
Definition at line 3661 of file ValueObject.cpp.
References GetModule(), GetRoot(), and ValueObject().
Referenced by lldb_private::ValueObjectSynthetic::CopyValueData(), CreateConstantValue(), lldb_private::formatters::GetArrayAddressOrPointerValue(), GetData(), GetLoadAddress(), GetModule(), GetPointeeData(), ResolveValue(), lldb_private::ValueObjectCast::UpdateValue(), lldb_private::ValueObjectChild::UpdateValue(), lldb_private::ValueObjectDynamicValue::UpdateValue(), and ValueObjectVTableChild::UpdateValue().
GetName()
ConstString lldb_private::ValueObject::GetName () const inline
Definition at line 487 of file ValueObject.h.
References m_name.
Referenced by lldb_private::ValueObjectSynthetic::CalculateNumChildren(), DoCast(), DumpPrintableRepresentation(), lldb_private::ValueObjectList::FindValueObjectByValueName(), lldb_private::ValueObjectSynthetic::GetChildAtIndex(), lldb_private::TypeSystemClang::GetChildCompilerTypeAtIndex(), GetExpressionPath(), lldb_private::ValueObjectPrinter::GetRootNameForDisplay(), IsRuntimeSupportValue(), UpdateFormatsIfNeeded(), lldb_private::ValueObjectDynamicValue::UpdateValue(), lldb_private::ValueObjectSynthetic::UpdateValue(), lldb_private::ValueObjectDynamicValue::ValueObjectDynamicValue(), lldb_private::ValueObjectRecognizerSynthesizedValue::ValueObjectRecognizerSynthesizedValue(), and lldb_private::ValueObjectSynthetic::ValueObjectSynthetic().
GetNonBaseClassParent()
ValueObject * ValueObject::GetNonBaseClassParent ()
Definition at line 2076 of file ValueObject.cpp.
References GetNonBaseClassParent(), GetParent(), IsBaseClass(), and ValueObject().
Referenced by GetExpressionPath(), and GetNonBaseClassParent().
GetNonSyntheticValue()
virtual lldb::ValueObjectSP lldb_private::ValueObject::GetNonSyntheticValue () inline virtual
Reimplemented in lldb_private::ValueObjectSynthetic.
Definition at line 610 of file ValueObject.h.
References GetSP().
Referenced by GetAlternateValue(), lldb_private::formatters::GetLibCxxAtomicValue(), lldb_private::formatters::IsLibCxxAtomic(), lldb_private::formatters::IsMsvcStlAtomic(), lldb_private::formatters::IsMsvcStlDeque(), lldb_private::formatters::IsMsvcStlList(), lldb_private::formatters::IsMsvcStlOptional(), lldb_private::formatters::IsMsvcStlSmartPointer(), lldb_private::formatters::IsMsvcStlSpan(), lldb_private::formatters::IsMsvcStlTuple(), lldb_private::formatters::IsMsvcStlUniquePtr(), lldb_private::formatters::IsMsvcStlUnordered(), lldb_private::formatters::IsMsvcStlVariant(), lldb_private::formatters::LibcxxFunctionSummaryProvider(), lldb_private::formatters::LibcxxSmartPointerSummaryProvider(), lldb_private::formatters::LibcxxStdSliceArraySummaryProvider(), lldb_private::formatters::LibcxxUniquePointerSummaryProvider(), lldb_private::formatters::LibcxxVariantSummaryProvider(), lldb_private::formatters::LibStdcppSmartPointerSummaryProvider(), lldb_private::formatters::LibStdcppVariantSummaryProvider(), lldb_private::formatters::MsvcStlSmartPointerSummaryProvider(), lldb_private::formatters::MsvcStlTreeIterSummaryProvider(), lldb_private::formatters::MsvcStlUniquePtrSummaryProvider(), lldb_private::formatters::MsvcStlVariantSummaryProvider(), and lldb_private::formatters::StdlibCoroutineHandleSummaryProvider().
GetNumChildren()
llvm::Expected< uint32_t > ValueObject::GetNumChildren (uint32_t max = UINT32_MAX)
Definition at line 448 of file ValueObject.cpp.
References CalculateNumChildren(), m_children, m_flags, SetNumChildren(), UINT32_MAX, and UpdateValueIfNeeded().
Referenced by DumpPrintableRepresentation(), lldb_private::ValueObjectPrinter::GetMaxNumChildrenToPrint(), GetNumChildrenIgnoringErrors(), and lldb_private::FormatManager::ShouldPrintAsOneLiner().
GetNumChildrenIgnoringErrors()
uint32_t ValueObject::GetNumChildrenIgnoringErrors (uint32_t max = UINT32_MAX)
Like GetNumChildren but returns 0 on error.
You probably shouldn't be using this function. It exists primarily to ease the transition to more pervasive error handling while not all APIs have been updated.
Definition at line 469 of file ValueObject.cpp.
References lldb_private::DataFormatters, lldb_private::GetLog(), GetNumChildren(), and LLDB_LOG_ERRORV.
Referenced by DumpPrintableRepresentation(), lldb_private::FormatEntity::Formatter::DumpValue(), lldb_private::formatters::GenericOptionalSummaryProvider(), GetChildAtIndex(), lldb_private::formatters::GetSecondValueOfLibCXXCompressedPair(), HasChildren(), and MightHaveChildren().
GetObjectDescription()
llvm::Expected< std::string > ValueObject::GetObjectDescription ()
Definition at line 1021 of file ValueObject.cpp.
References lldb::eLanguageTypeObjC, error(), GetExecutionContextRef(), lldb_private::Process::GetLanguageRuntime(), GetObjectRuntimeLanguage(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::StreamString::GetString(), lldb_private::Language::LanguageIsCFamily(), m_object_desc_str, and UpdateValueIfNeeded().
Referenced by DumpPrintableRepresentation(), and lldb_private::ValueObjectPrinter::PrintValueObject().
GetObjectRuntimeLanguage()
lldb::LanguageType lldb_private::ValueObject::GetObjectRuntimeLanguage () inline
Definition at line 373 of file ValueObject.h.
References GetCompilerType(), and lldb_private::CompilerType::GetMinimumLanguage().
Referenced by lldb_private::LanguageCategory::Get(), lldb_private::TypeCategoryMap::Get(), GetCompilerType(), GetObjectDescription(), lldb_private::FormatManager::GetPossibleMatches(), IsLogicalTrue(), lldb_private::CPlusPlusLanguage::IsNilReference(), IsNilReference(), lldb_private::Process::IsPossibleDynamicValue(), IsUninitializedReference(), SetValueFromCString(), lldb_private::ValueObjectVTable::UpdateValue(), and ValueObjectVTableChild::UpdateValue().
GetParent() [1/2]
virtual ValueObject * lldb_private::ValueObject::GetParent () inline virtual
Reimplemented in lldb_private::ValueObjectCast, lldb_private::ValueObjectDynamicValue, and lldb_private::ValueObjectSynthetic.
Definition at line 838 of file ValueObject.h.
References m_parent, and ValueObject().
Referenced by DerefToNSErrorPointer(), ExtractFields(), GetExpressionPath(), GetNonBaseClassParent(), IsBaseClass(), lldb_private::ValueObjectVTable::IsInScope(), ValueObjectVTableChild::IsInScope(), lldb_private::ValueObjectVTable::UpdateValue(), and ValueObjectVTableChild::UpdateValue().
GetParent() [2/2]
virtual const ValueObject * lldb_private::ValueObject::GetParent () const inline virtual
Reimplemented in lldb_private::ValueObjectCast, lldb_private::ValueObjectDynamicValue, and lldb_private::ValueObjectSynthetic.
Definition at line 840 of file ValueObject.h.
References m_parent, and ValueObject().
GetPointeeData()
size_t ValueObject::GetPointeeData (DataExtractor & data, uint32_t item_idx = 0, uint32_t item_count = 1) virtual
Reimplemented in lldb_private::ValueObjectConstResult, lldb_private::ValueObjectConstResultCast, and lldb_private::ValueObjectConstResultChild.
Definition at line 671 of file ValueObject.cpp.
References lldb_private::DataBufferHeap::CopyData(), Dereference(), lldb_private::eAddressTypeFile, lldb_private::eAddressTypeHost, lldb_private::eAddressTypeInvalid, lldb_private::eAddressTypeLoad, error(), GetAddressOf(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::CompilerType::GetByteSize(), GetByteSize(), GetChildAtIndex(), GetCompilerType(), GetExecutionContextRef(), GetModule(), GetPointerValue(), lldb_private::ExecutionContext::GetTargetPtr(), GetTypeInfo(), LLDB_INVALID_ADDRESS, m_value, lldb_private::Target::ReadMemory(), lldb_private::DataBufferHeap::SetByteSize(), lldb_private::DataExtractor::SetData(), lldb_private::Address::SetLoadAddress(), and Target.
Referenced by ReadPointedString().
GetPointerValue()
ValueObject::AddrAndType ValueObject::GetPointerValue ()
Definition at line 1636 of file ValueObject.cpp.
References lldb_private::Value::FileAddress, GetAddressTypeOfChildren(), lldb_private::Value::HostAddress, lldb_private::Value::Invalid, LLDB_INVALID_ADDRESS, lldb_private::Value::LoadAddress, m_data, m_value, lldb_private::Value::Scalar, and UpdateValueIfNeeded().
Referenced by CastPointerType(), CastPointerType(), lldb_private::formatters::CXXFunctionPointerSummaryProvider(), lldb_private::TypeFormatImpl_Format::FormatObject(), lldb_private::formatters::GetArrayAddressOrPointerValue(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), lldb_private::AppleObjCRuntimeV1::GetDynamicTypeAndAddress(), lldb_private::AppleObjCRuntimeV2::GetDynamicTypeAndAddress(), lldb_private::ItaniumABILanguageRuntime::GetDynamicTypeAndAddress(), GetPointeeData(), lldb_private::ItaniumABILanguageRuntime::GetTypeInfo(), lldb_private::ItaniumABILanguageRuntime::GetVTableInfo(), IsCStringContainer(), ReadPointedString(), lldb_private::ValueObjectPrinter::ShouldPrintChildren(), and lldb_private::ValueObjectChild::UpdateValue().
GetPreferredDisplayLanguage()
lldb::LanguageType ValueObject::GetPreferredDisplayLanguage () virtual
Reimplemented in lldb_private::ValueObjectConstResult, lldb_private::ValueObjectDynamicValue, and lldb_private::ValueObjectSynthetic.
Definition at line 3716 of file ValueObject.cpp.
References lldb_private::SymbolContext::comp_unit, lldb::eLanguageTypeUnknown, GetFrameSP(), GetPreferredDisplayLanguage(), GetRoot(), and m_preferred_display_language.
Referenced by Dereference(), lldb_private::DumpValueObjectOptions::DumpValueObjectOptions(), GetPreferredDisplayLanguage(), GetSummaryAsCString(), lldb_private::ValueObjectPrinter::GetValueSummaryError(), Persist(), and lldb_private::ValueObjectPrinter::PrintDecl().
GetProcessSP()
lldb::ProcessSP lldb_private::ValueObject::GetProcessSP () const inline
Definition at line 338 of file ValueObject.h.
References m_update_point.
Referenced by lldb_private::formatters::CFBagSummaryProvider(), lldb_private::formatters::CFBinaryHeapSummaryProvider(), lldb_private::formatters::CFBitVectorSummaryProvider(), lldb_private::AppleObjCRuntimeV1::ClassDescriptorV1::ClassDescriptorV1(), DerefToNSErrorPointer(), ExtractFields(), lldb_private::TypeFormatImpl_EnumType::FormatObject(), GetCompilerType(), lldb_private::AppleObjCRuntimeV2::GetDynamicTypeAndAddress(), lldb_private::AppleObjCRuntime::GetObjectDescription(), lldb_private::ObjCLanguage::GetPossibleFormattersMatches(), lldb_private::AppleObjCRuntimeV2::GetPreferredLanguageRuntime(), IsRuntimeSupportValue(), lldb_private::formatters::NSArraySummaryProvider(), lldb_private::formatters::NSBundleSummaryProvider(), lldb_private::formatters::NSDataSummaryProvider(), lldb_private::formatters::NSDateSummaryProvider(), lldb_private::formatters::NSDecimalNumberSummaryProvider(), lldb_private::formatters::NSDictionarySummaryProvider(), lldb_private::formatters::NSError_SummaryProvider(), lldb_private::formatters::NSIndexSetSummaryProvider(), lldb_private::formatters::NSIndirectTaggedString_SummaryProvider(), lldb_private::formatters::NSMachPortSummaryProvider(), lldb_private::formatters::NSNotificationSummaryProvider(), lldb_private::formatters::NSNumberSummaryProvider(), lldb_private::formatters::NSSetSummaryProvider(), lldb_private::formatters::NSStringSummaryProvider(), lldb_private::formatters::NSTimeZoneSummaryProvider(), lldb_private::formatters::NSURLSummaryProvider(), lldb_private::formatters::ObjCBooleanSummaryProvider(), lldb_private::formatters::ObjCClassSummaryProvider(), lldb_private::ValueObjectChild::UpdateValue(), lldb_private::ValueObjectVTable::UpdateValue(), and ValueObjectVTableChild::UpdateValue().
GetQualifiedRepresentationIfAvailable()
ValueObjectSP ValueObject::GetQualifiedRepresentationIfAvailable (lldb::DynamicValueType dynValue, bool synthValue)
Definition at line 2766 of file ValueObject.cpp.
References lldb::eDynamicCanRunTarget, lldb::eDynamicDontRunTarget, lldb::eNoDynamicValues, GetDynamicValue(), GetSP(), GetStaticValue(), and IsDynamic().
Referenced by lldb_private::FormatEntity::Formatter::DumpValue(), and lldb_private::FormatManager::GetTypeForCache().
GetQualifiedTypeName()
virtual ConstString lldb_private::ValueObject::GetQualifiedTypeName () inline virtual
Reimplemented in lldb_private::ValueObjectChild, lldb_private::ValueObjectDynamicValue, lldb_private::ValueObjectRegisterSet, lldb_private::ValueObjectSynthetic, lldb_private::ValueObjectVariable, and lldb_private::ValueObjectVTable.
Definition at line 369 of file ValueObject.h.
References GetCompilerType(), and lldb_private::CompilerType::GetTypeName().
Referenced by lldb_private::ValueObjectPrinter::PrintDecl().
GetRoot()
ValueObject * ValueObject::GetRoot ()
Definition at line 3668 of file ValueObject.cpp.
References FollowParentChain(), m_parent, m_root, and ValueObject().
Referenced by GetAddressTypeOfChildren(), GetModule(), GetPreferredDisplayLanguage(), lldb_private::ValueObjectChild::IsInScope(), and UpdateChildrenAddressType().
GetSP()
lldb::ValueObjectSP lldb_private::ValueObject::GetSP () inline
Definition at line 569 of file ValueObject.h.
References m_manager.
Referenced by lldb_private::formatters::BlockPointerSummaryProvider(), lldb_private::ValueObjectConstResultImpl::Cast(), CastDerivedToBaseType(), lldb_private::ValueObjectCast::Create(), lldb::SBTypeSummary::CreateWithCallback(), lldb_private::BytecodeSummaryFormat::FormatObject(), lldb_private::ScriptSummaryFormat::FormatObject(), lldb_private::BytecodeSyntheticChildren::FrontEnd::FrontEnd(), lldb_private::ScriptedSyntheticChildren::FrontEnd::FrontEnd(), GetChildAtIndex(), lldb_private::ValueObjectSynthetic::GetChildAtIndex(), GetChildAtNamePath(), GetChildMemberWithName(), lldb_private::ValueObjectRegisterSet::GetChildMemberWithName(), lldb_private::formatters::GetDesugaredSmartPointerValue(), lldb_private::ValueObjectSynthetic::GetDynamicValue(), lldb_private::CXXSyntheticChildren::GetFrontEnd(), GetNonSyntheticValue(), GetQualifiedRepresentationIfAvailable(), GetStaticValue(), lldb_private::ValueObjectSynthetic::GetStaticValue(), GetSyntheticArrayMember(), GetSyntheticBase(), GetSyntheticBitFieldChild(), GetSyntheticChildAtOffset(), GetValueForExpressionPath_Impl(), lldb_private::formatters::LibStdcppUniquePointerSummaryProvider(), lldb_private::formatters::ObjCBOOLSummaryProvider(), and lldb_private::formatters::VectorTypeSummaryProvider().
GetStaticValue()
virtual lldb::ValueObjectSP lldb_private::ValueObject::GetStaticValue () inline virtual
Reimplemented in lldb_private::ValueObjectDynamicValue, and lldb_private::ValueObjectSynthetic.
Definition at line 608 of file ValueObject.h.
References GetSP().
Referenced by lldb_private::FormatManager::GetPossibleMatches(), and GetQualifiedRepresentationIfAvailable().
GetSummaryAsCString() [1/4]
const char * ValueObject::GetSummaryAsCString (lldb::LanguageType lang = lldb::eLanguageTypeUnknown)
Definition at line 639 of file ValueObject.cpp.
References GetSummaryAsCString(), GetSummaryFormat(), m_summary_str, lldb_private::TypeSummaryOptions::SetLanguage(), and UpdateValueIfNeeded().
Referenced by DumpPrintableRepresentation(), GetSummaryAsCString(), GetSummaryAsCString(), GetSummaryAsCString(), and lldb_private::ValueObjectPrinter::GetValueSummaryError().
GetSummaryAsCString() [2/4]
bool ValueObject::GetSummaryAsCString (std::string & destination, const TypeSummaryOptions & options)
Definition at line 651 of file ValueObject.cpp.
References GetSummaryAsCString(), and GetSummaryFormat().
GetSummaryAsCString() [3/4]
bool ValueObject::GetSummaryAsCString (TypeSummaryImpl * summary_ptr, std::string & destination, const TypeSummaryOptions & options)
Definition at line 584 of file ValueObject.cpp.
References lldb::eLanguageTypeUnknown, lldb_private::TypeSummaryImpl::FormatObject(), GetCompilerType(), GetExecutionContextRef(), lldb_private::TypeSummaryOptions::GetLanguage(), GetPreferredDisplayLanguage(), GetTargetSP(), HasSyntheticValue(), m_flags, m_synthetic_value, lldb_private::TypeSummaryOptions::SetLanguage(), and UpdateValueIfNeeded().
GetSummaryAsCString() [4/4]
bool ValueObject::GetSummaryAsCString (TypeSummaryImpl * summary_ptr, std::string & destination, lldb::LanguageType lang = lldb::eLanguageTypeUnknown)
Definition at line 577 of file ValueObject.cpp.
References GetSummaryAsCString().
GetSummaryFormat()
lldb::TypeSummaryImplSP lldb_private::ValueObject::GetSummaryFormat () inline
Definition at line 798 of file ValueObject.h.
References m_type_summary_sp, and UpdateFormatsIfNeeded().
Referenced by GetSummaryAsCString(), GetSummaryAsCString(), lldb_private::ValueObjectPrinter::GetSummaryFormatter(), and lldb_private::FormatManager::ShouldPrintAsOneLiner().
GetSymbolContextScope()
SymbolContextScope * ValueObject::GetSymbolContextScope () virtual
Reimplemented in lldb_private::ValueObjectVariable.
Definition at line 3518 of file ValueObject.cpp.
References m_parent.
GetSyntheticArrayMember()
ValueObjectSP ValueObject::GetSyntheticArrayMember (size_t index, bool can_create)
Definition at line 1824 of file ValueObject.cpp.
References AddSyntheticChild(), CreateSyntheticArrayMember(), GetSP(), GetSyntheticChild(), IsArrayType(), IsPointerType(), and ValueObject().
Referenced by lldb_private::ValueObjectPrinter::GenerateChild().
GetSyntheticBase()
ValueObjectSP ValueObject::GetSyntheticBase (uint32_t offset, const CompilerType & type, bool can_create, ConstString name_const_str = ConstString()) virtual
Definition at line 1924 of file ValueObject.cpp.
References AddSyntheticChild(), lldb_private::ConstString::AsCString(), lldb_private::eAddressTypeInvalid, lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::CompilerType::GetByteSize(), GetExecutionContextRef(), GetSP(), GetSyntheticChild(), lldb_private::CompilerType::GetTypeName(), lldb_private::ConstString::IsEmpty(), lldb_private::ConstString::SetCString(), and ValueObjectChild.
GetSyntheticBitFieldChild()
ValueObjectSP ValueObject::GetSyntheticBitFieldChild (uint32_t from, uint32_t to, bool can_create)
Definition at line 1851 of file ValueObject.cpp.
References AddSyntheticChild(), lldb_private::eAddressTypeInvalid, lldb::eByteOrderBig, GetByteSize(), GetCompilerType(), GetDataExtractor(), GetSP(), GetSyntheticChild(), IsScalarType(), and ValueObjectChild.
GetSyntheticChild()
ValueObjectSP ValueObject::GetSyntheticChild (ConstString key) const
Definition at line 1766 of file ValueObject.cpp.
References m_synthetic_children.
Referenced by GetSyntheticArrayMember(), GetSyntheticBase(), GetSyntheticBitFieldChild(), GetSyntheticChildAtOffset(), and GetSyntheticExpressionPathChild().
GetSyntheticChildAtOffset()
ValueObjectSP ValueObject::GetSyntheticChildAtOffset (uint32_t offset, const CompilerType & type, bool can_create, ConstString name_const_str = ConstString()) virtual
Reimplemented in lldb_private::ValueObjectConstResult, lldb_private::ValueObjectConstResultCast, and lldb_private::ValueObjectConstResultChild.
Definition at line 1887 of file ValueObject.cpp.
References AddSyntheticChild(), lldb_private::eAddressTypeInvalid, lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::CompilerType::GetByteSize(), GetExecutionContextRef(), GetSP(), GetSyntheticChild(), lldb_private::ConstString::IsEmpty(), lldb_private::ConstString::SetString(), and ValueObjectChild.
Referenced by lldb_private::formatters::CMTimeSummaryProvider(), lldb_private::formatters::NSBundleSummaryProvider(), lldb_private::formatters::NSNotificationSummaryProvider(), lldb_private::formatters::NSStringSummaryProvider(), lldb_private::formatters::NSTimeZoneSummaryProvider(), and lldb_private::formatters::NSURLSummaryProvider().
GetSyntheticChildren()
lldb::SyntheticChildrenSP lldb_private::ValueObject::GetSyntheticChildren () inline
Definition at line 829 of file ValueObject.h.
References m_synthetic_children_sp, and UpdateFormatsIfNeeded().
GetSyntheticExpressionPathChild()
ValueObjectSP ValueObject::GetSyntheticExpressionPathChild (const char * expression, bool can_create)
Definition at line 1980 of file ValueObject.cpp.
References AddSyntheticChild(), GetSyntheticChild(), GetValueForExpressionPath(), and SkipLeadingExpressionPathSeparators().
GetSyntheticValue()
ValueObjectSP ValueObject::GetSyntheticValue ()
Definition at line 2056 of file ValueObject.cpp.
References CalculateSyntheticValue(), and m_synthetic_value.
Referenced by CreateSyntheticArrayMember(), lldb_private::FormatEntity::Formatter::DumpValue(), GetAlternateValue(), and lldb_private::formatters::MsvcStlAtomicSummaryProvider().
GetTargetSP()
lldb::TargetSP lldb_private::ValueObject::GetTargetSP () const inline
Definition at line 334 of file ValueObject.h.
References m_update_point.
Referenced by CalculateSyntheticValue(), CastBaseToDerivedType(), CastDerivedToBaseType(), CastToBasicType(), CastToEnumType(), CharStringSummaryProvider(), lldb_private::FormatEntity::Formatter::DumpValue(), lldb_private::BytecodeSummaryFormat::FormatObject(), lldb_private::ScriptSummaryFormat::FormatObject(), lldb_private::TypeFormatImpl_EnumType::FormatObject(), lldb_private::TypeFormatImpl_Format::FormatObject(), lldb_private::ScriptedSyntheticChildren::FrontEnd::FrontEnd(), lldb_private::AppleObjCRuntimeV2::GetDynamicTypeAndAddress(), GetLoadAddress(), lldb_private::AppleObjCRuntime::GetObjectDescription(), lldb_private::ObjCLanguage::GetPossibleFormattersMatches(), lldb_private::FormatManager::GetPossibleMatches(), GetSummaryAsCString(), lldb_private::formatters::NSAttributedStringSummaryProvider(), lldb_private::formatters::NSStringSummaryProvider(), Persist(), lldb_private::ValueObjectPrinter::PrintChildrenIfNeeded(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::ReadBufferAndDumpToStreamOptions(), lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::ReadStringAndDumpToStreamOptions(), SetValueFromInteger(), SetValueFromInteger(), lldb_private::FormatManager::ShouldPrintAsOneLiner(), lldb_private::ValueObjectDynamicValue::UpdateValue(), lldb_private::ValueObjectVTable::UpdateValue(), ValueObjectVTableChild::UpdateValue(), lldb_private::ValueObjectMemory::ValueObjectMemory(), lldb_private::ValueObjectMemory::ValueObjectMemory(), and lldb_private::formatters::WCharStringSummaryProvider().
GetThreadSP()
lldb::ThreadSP lldb_private::ValueObject::GetThreadSP () const inline
Definition at line 342 of file ValueObject.h.
References m_update_point.
GetTypeImpl()
virtual TypeImpl lldb_private::ValueObject::GetTypeImpl () inline virtual
Reimplemented in lldb_private::ValueObjectDynamicValue.
Definition at line 355 of file ValueObject.h.
References GetCompilerType().
GetTypeInfo()
uint32_t lldb_private::ValueObject::GetTypeInfo (CompilerType * pointee_or_element_compiler_type = nullptr) inline
Definition at line 378 of file ValueObject.h.
References GetCompilerType(), and lldb_private::CompilerType::GetTypeInfo().
Referenced by DumpPrintableRepresentation(), lldb_private::FormatEntity::Formatter::DumpValue(), DumpValueWithLLVMFormat(), lldb_private::UserExpression::Evaluate(), GetPointeeData(), HasSpecialPrintableRepresentation(), IsCStringContainer(), MightHaveChildren(), ReadPointedString(), and lldb_private::ValueObjectChild::UpdateValue().
GetTypeName()
virtual ConstString lldb_private::ValueObject::GetTypeName () inline virtual
Reimplemented in lldb_private::ValueObjectChild, lldb_private::ValueObjectConstResult, lldb_private::ValueObjectDynamicValue, lldb_private::ValueObjectMemory, lldb_private::ValueObjectRegister, lldb_private::ValueObjectRegisterSet, lldb_private::ValueObjectSynthetic, lldb_private::ValueObjectVariable, and lldb_private::ValueObjectVTable.
Definition at line 365 of file ValueObject.h.
References GetCompilerType(), and lldb_private::CompilerType::GetTypeName().
Referenced by lldb_private::formatters::CFBagSummaryProvider(), lldb_private::formatters::CFBinaryHeapSummaryProvider(), lldb_private::formatters::CFBitVectorSummaryProvider(), Dereference(), DumpPrintableRepresentation(), lldb_private::FormatEntity::Formatter::DumpValue(), GetDisplayTypeName(), GetExpressionPath(), and lldb_private::ItaniumABILanguageRuntime::GetTypeInfo().
GetUpdatePoint() [1/2]
EvaluationPoint & lldb_private::ValueObject::GetUpdatePoint () inline
Definition at line 328 of file ValueObject.h.
References m_update_point.
GetUpdatePoint() [2/2]
const EvaluationPoint & lldb_private::ValueObject::GetUpdatePoint () const inline
Definition at line 326 of file ValueObject.h.
References m_update_point.
Referenced by GetCompilerType(), and ValueObject().
GetValue() [1/2]
Value & lldb_private::ValueObject::GetValue () inline
Definition at line 513 of file ValueObject.h.
References m_value.
GetValue() [2/2]
const Value & lldb_private::ValueObject::GetValue () const inline
Definition at line 511 of file ValueObject.h.
References m_value.
Referenced by lldb_private::ValueObjectSynthetic::CopyValueData(), lldb_private::ValueObjectVariable::DoUpdateChildrenAddressType(), lldb_private::TypeFormatImpl_Format::FormatObject(), GetValueAsCString(), IRInterpreter::Interpret(), lldb_private::ValueObjectPrinter::IsInstancePointer(), Persist(), and lldb_private::ValueObjectChild::UpdateValue().
GetValueAsAPFloat()
llvm::Expected< llvm::APFloat > ValueObject::GetValueAsAPFloat ()
If the current ValueObject is of an appropriate type, convert the value to an APFloat and return that.
Otherwise return an error.
Definition at line 1175 of file ValueObject.cpp.
References CanProvideValue(), lldb_private::Scalar::GetAPFloat(), GetCompilerType(), HasFloatingRepresentation(), and ResolveValue().
Referenced by CastToBasicType(), CastToEnumType(), and GetValueAsBool().
GetValueAsAPSInt()
llvm::Expected< llvm::APSInt > ValueObject::GetValueAsAPSInt ()
If the current ValueObject is of an appropriate type, convert the value to an APSInt and return that.
Otherwise return an error.
Definition at line 1153 of file ValueObject.cpp.
References CanProvideValue(), lldb_private::Scalar::GetAPSInt(), GetCompilerType(), IsPointerType(), and ResolveValue().
Referenced by CastToBasicType(), CastToEnumType(), and GetValueAsBool().
GetValueAsBool()
llvm::Expected< bool > ValueObject::GetValueAsBool ()
If the current ValueObject is of an appropriate type, convert the value to a boolean and return that.
Otherwise return an error.
Definition at line 1191 of file ValueObject.cpp.
References lldb_private::ValueObject::AddrAndType::address, GetAddressOf(), GetCompilerType(), GetValueAsAPFloat(), GetValueAsAPSInt(), HasFloatingRepresentation(), lldb_private::CompilerType::IsArrayType(), lldb_private::CompilerType::IsInteger(), lldb_private::CompilerType::IsPointerType(), and lldb_private::CompilerType::IsUnscopedEnumerationType().
GetValueAsCString() [1/3]
const char * ValueObject::GetValueAsCString () virtual
Definition at line 1076 of file ValueObject.cpp.
References lldb::eFormatDefault, lldb::eFormatUnsigned, lldb_private::RegisterInfo::format, lldb_private::Value::GetCompilerType(), lldb_private::CompilerType::GetFormat(), GetFormat(), GetValue(), GetValueAsCString(), m_flags, m_last_format, m_old_value_str, m_type_format_sp, m_value, m_value_str, lldb_private::Value::RegisterInfo, SetValueDidChange(), and UpdateValueIfNeeded().
Referenced by CharSummaryProvider(), DumpPrintableRepresentation(), lldb_private::BytecodeSummaryFormat::FormatObject(), GetExpressionPath(), GetValueAsCString(), GetValueAsCString(), and lldb_private::ValueObjectPrinter::GetValueSummaryError().
GetValueAsCString() [2/3]
bool ValueObject::GetValueAsCString (const lldb_private::TypeFormatImpl & format, std::string & destination) virtual
Definition at line 1063 of file ValueObject.cpp.
References lldb_private::TypeFormatImpl::FormatObject(), and UpdateValueIfNeeded().
GetValueAsCString() [3/3]
bool ValueObject::GetValueAsCString (lldb::Format format, std::string & destination)
Definition at line 1071 of file ValueObject.cpp.
References GetValueAsCString().
GetValueAsSigned()
int64_t ValueObject::GetValueAsSigned (int64_t fail_value, bool * success = nullptr) virtual
Definition at line 1135 of file ValueObject.cpp.
References CanProvideValue(), lldb_private::Scalar::MakeSigned(), ResolveValue(), and lldb_private::Scalar::SLongLong().
Referenced by lldb_private::formatters::CFAbsoluteTimeSummaryProvider(), and DumpValueWithLLVMFormat().
GetValueAsUnsigned()
uint64_t ValueObject::GetValueAsUnsigned (uint64_t fail_value, bool * success = nullptr) virtual
Definition at line 1117 of file ValueObject.cpp.
References CanProvideValue(), lldb_private::Scalar::MakeUnsigned(), ResolveValue(), and lldb_private::Scalar::ULongLong().
Referenced by CastBaseToDerivedType(), CastToBasicType(), lldb_private::formatters::CFBagSummaryProvider(), lldb_private::formatters::CFBinaryHeapSummaryProvider(), lldb_private::formatters::CFBitVectorSummaryProvider(), lldb_private::AppleObjCRuntimeV1::ClassDescriptorV1::ClassDescriptorV1(), CopyExpressionResult(), CreateConstantValue(), DerefToNSErrorPointer(), lldb_private::formatters::DumpCxxSmartPtrPointerSummary(), DumpValueWithLLVMFormat(), ExtractFields(), GetExpressionPath(), GetVTableAddress(), lldb_private::CPlusPlusLanguage::IsNilReference(), lldb_private::ObjCLanguage::IsNilReference(), lldb_private::formatters::NSArraySummaryProvider(), lldb_private::formatters::NSAttributedStringSummaryProvider(), lldb_private::formatters::NSBundleSummaryProvider(), lldb_private::formatters::NSDataSummaryProvider(), lldb_private::formatters::NSDateSummaryProvider(), lldb_private::formatters::NSDecimalNumberSummaryProvider(), lldb_private::formatters::NSDictionarySummaryProvider(), lldb_private::formatters::NSIndexSetSummaryProvider(), lldb_private::formatters::NSMachPortSummaryProvider(), lldb_private::formatters::NSNotificationSummaryProvider(), lldb_private::formatters::NSNumberSummaryProvider(), lldb_private::formatters::NSSetSummaryProvider(), lldb_private::formatters::NSStringSummaryProvider(), lldb_private::formatters::NSTimeZoneSummaryProvider(), lldb_private::formatters::NSURLSummaryProvider(), lldb_private::formatters::ObjCBooleanSummaryProvider(), lldb_private::formatters::ObjCClassSummaryProvider(), lldb_private::formatters::ObjCSELSummaryProvider(), lldb_private::ValueObjectPrinter::PrintChildrenIfNeeded(), lldb_private::ValueObjectDynamicValue::SetData(), lldb_private::ValueObjectDynamicValue::SetValueFromCString(), and ValueObjectVTableChild::UpdateValue().
GetValueDidChange()
bool lldb_private::ValueObject::GetValueDidChange () inline
Definition at line 563 of file ValueObject.h.
References m_flags.
GetValueForExpressionPath()
ValueObjectSP ValueObject::GetValueForExpressionPath (llvm::StringRef expression, ExpressionPathScanEndReason * reason_to_stop = nullptr, ExpressionPathEndResultType * final_value_type = nullptr, const GetValueForExpressionPathOptions & options = GetValueForExpressionPathOptions::DefaultOptions(), ExpressionPathAftermath * final_task_on_target = nullptr)
Definition at line 2249 of file ValueObject.cpp.
References DereferenceValueOrAlternate(), eExpressionPathAftermathDereference, eExpressionPathAftermathNothing, eExpressionPathAftermathTakeAddress, eExpressionPathEndResultTypeInvalid, eExpressionPathEndResultTypePlain, eExpressionPathScanEndReasonDereferencingFailed, eExpressionPathScanEndReasonTakingAddressFailed, eExpressionPathScanEndReasonUnknown, error(), GetValueForExpressionPath_Impl(), and lldb_private::ValueObject::GetValueForExpressionPathOptions::m_synthetic_children_traversal.
Referenced by lldb_private::FormatEntity::Formatter::DumpValue(), ExpandIndexedExpression(), and GetSyntheticExpressionPathChild().
GetValueForExpressionPath_Impl()
ValueObjectSP ValueObject::GetValueForExpressionPath_Impl (llvm::StringRef expression_cstr, ExpressionPathScanEndReason * reason_to_stop, ExpressionPathEndResultType * final_value_type, const GetValueForExpressionPathOptions & options, ExpressionPathAftermath * final_task_on_target) private
Definition at line 2318 of file ValueObject.cpp.
References lldb_private::Flags::AllClear(), DereferenceValueOrAlternate(), eExpressionPathAftermathDereference, eExpressionPathAftermathNothing, eExpressionPathEndResultTypeBitfield, eExpressionPathEndResultTypeBoundedRange, eExpressionPathEndResultTypeInvalid, eExpressionPathEndResultTypePlain, eExpressionPathEndResultTypeUnboundedRange, eExpressionPathScanEndReasonArrayRangeOperatorMet, eExpressionPathScanEndReasonArrowInsteadOfDot, eExpressionPathScanEndReasonDereferencingFailed, eExpressionPathScanEndReasonDotInsteadOfArrow, eExpressionPathScanEndReasonEmptyRangeNotAllowed, eExpressionPathScanEndReasonEndOfString, eExpressionPathScanEndReasonFragileIVarNotAllowed, eExpressionPathScanEndReasonNoSuchChild, eExpressionPathScanEndReasonRangeOperatorInvalid, eExpressionPathScanEndReasonRangeOperatorNotAllowed, eExpressionPathScanEndReasonSyntheticValueMissing, eExpressionPathScanEndReasonUnexpectedSymbol, lldb::eLanguageTypeObjC, error(), GetAlternateValue(), GetSP(), lldb_private::CompilerType::GetTypeInfo(), lldb_private::ValueObject::GetValueForExpressionPathOptions::m_allow_bitfields_syntax, lldb_private::ValueObject::GetValueForExpressionPathOptions::m_check_dot_vs_arrow_syntax, lldb_private::ValueObject::GetValueForExpressionPathOptions::m_no_fragile_ivar, lldb_private::ValueObject::GetValueForExpressionPathOptions::m_synthetic_children_traversal, lldb_private::Flags::Reset(), lldb_private::Flags::Test(), and ValueObject().
Referenced by GetValueForExpressionPath().
GetValueFormat()
lldb::TypeFormatImplSP lldb_private::ValueObject::GetValueFormat () inline
Definition at line 817 of file ValueObject.h.
References m_type_format_sp, and UpdateFormatsIfNeeded().
GetValueIsValid()
bool lldb_private::ValueObject::GetValueIsValid () const inline
Definition at line 559 of file ValueObject.h.
References m_flags.
Referenced by UpdateValueIfNeeded().
GetValueType()
virtual lldb::ValueType lldb_private::ValueObject::GetValueType () const pure virtual
Implemented in lldb_private::ValueObjectCast, lldb_private::ValueObjectChild, lldb_private::ValueObjectConstResult, lldb_private::ValueObjectDynamicValue, lldb_private::ValueObjectMemory, lldb_private::ValueObjectRecognizerSynthesizedValue, lldb_private::ValueObjectRegister, lldb_private::ValueObjectRegisterSet, lldb_private::ValueObjectSynthetic, lldb_private::ValueObjectVariable, lldb_private::ValueObjectVTable, and ValueObjectVTableChild.
Referenced by lldb_private::formatters::CXXFunctionPointerSummaryProvider(), and lldb_private::CPlusPlusLanguage::GetHardcodedSummaries().
GetVariable()
virtual lldb::VariableSP lldb_private::ValueObject::GetVariable () inline virtual
Reimplemented in lldb_private::ValueObjectDynamicValue, lldb_private::ValueObjectSynthetic, and lldb_private::ValueObjectVariable.
Definition at line 870 of file ValueObject.h.
Referenced by IsRuntimeSupportValue(), SetValueFromInteger(), and SetValueFromInteger().
GetVTable()
lldb::ValueObjectSP ValueObject::GetVTable ()
If this object represents a C++ class with a vtable, return an object that represents the virtual function table.
If the object isn't a class with a vtable, return a valid ValueObject with the error set correctly.
Definition at line 3776 of file ValueObject.cpp.
References lldb_private::ValueObjectVTable::Create().
HasChildren()
bool lldb_private::ValueObject::HasChildren () inline
Definition at line 509 of file ValueObject.h.
References GetNumChildrenIgnoringErrors().
HasDynamicValueTypeInfo()
virtual bool lldb_private::ValueObject::HasDynamicValueTypeInfo () inline protected virtual
Reimplemented in lldb_private::ValueObjectDynamicValue.
Definition at line 1058 of file ValueObject.h.
Referenced by GetDynamicValueType().
HasSpecialPrintableRepresentation()
bool ValueObject::HasSpecialPrintableRepresentation (ValueObjectRepresentationStyle val_obj_display, lldb::Format custom_format)
Definition at line 1310 of file ValueObject.cpp.
References lldb_private::Flags::AnySet(), lldb::eFormatBytes, lldb::eFormatBytesWithASCII, lldb::eFormatChar, lldb::eFormatCharArray, lldb::eFormatCString, lldb::eFormatVectorOfChar, lldb::eFormatVectorOfFloat32, lldb::eFormatVectorOfFloat64, lldb::eFormatVectorOfSInt16, lldb::eFormatVectorOfSInt32, lldb::eFormatVectorOfSInt64, lldb::eFormatVectorOfSInt8, lldb::eFormatVectorOfUInt128, lldb::eFormatVectorOfUInt16, lldb::eFormatVectorOfUInt32, lldb::eFormatVectorOfUInt64, lldb::eFormatVectorOfUInt8, eValueObjectRepresentationStyleValue, GetTypeInfo(), IsCStringContainer(), and lldb_private::Flags::Test().
Referenced by lldb_private::FormatEntity::Formatter::DumpValue().
HasSyntheticValue()
bool ValueObject::HasSyntheticValue () virtual
Reimplemented in lldb_private::ValueObjectSynthetic.
Definition at line 2065 of file ValueObject.cpp.
References CalculateSyntheticValue(), m_synthetic_children_sp, m_synthetic_value, and UpdateFormatsIfNeeded().
Referenced by Dereference(), and GetSummaryAsCString().
IsArrayType()
bool lldb_private::ValueObject::IsArrayType () inline
Definition at line 384 of file ValueObject.h.
References GetCompilerType(), and lldb_private::CompilerType::IsArrayType().
Referenced by lldb_private::formatters::GetArrayAddressOrPointerValue(), and GetSyntheticArrayMember().
IsBaseClass() [1/2]
virtual bool lldb_private::ValueObject::IsBaseClass () inline virtual
Reimplemented in lldb_private::ValueObjectChild, and lldb_private::ValueObjectDynamicValue.
Definition at line 398 of file ValueObject.h.
Referenced by DerefToNSErrorPointer(), ExtractFields(), GetExpressionPath(), GetNonBaseClassParent(), IsBaseClass(), and lldb_private::ValueObjectPrinter::IsInstancePointer().
IsBaseClass() [2/2]
bool ValueObject::IsBaseClass (uint32_t & depth)
Definition at line 2086 of file ValueObject.cpp.
References GetParent(), and IsBaseClass().
IsBitfield()
bool lldb_private::ValueObject::IsBitfield () inline
Definition at line 428 of file ValueObject.h.
References GetBitfieldBitOffset(), and GetBitfieldBitSize().
Referenced by CreateConstantValue(), lldb_private::FormatEntity::Formatter::DumpValue(), and GetAddressOf().
IsChecksumEmpty()
bool lldb_private::ValueObject::IsChecksumEmpty () inline protected
Definition at line 1100 of file ValueObject.h.
References m_value_checksum.
Referenced by UpdateValueIfNeeded().
IsCStringContainer()
bool ValueObject::IsCStringContainer (bool check_pointer = false)
Returns true if this is a char* or a char[] if it is a char* and check_pointer is true, it also checks that the pointer is valid.
Definition at line 656 of file ValueObject.cpp.
References lldb_private::ValueObject::AddrAndType::address, lldb_private::Flags::AnySet(), GetPointerValue(), GetTypeInfo(), lldb_private::CompilerType::IsCharType(), LLDB_INVALID_ADDRESS, and lldb_private::Flags::Test().
Referenced by DumpPrintableRepresentation(), and HasSpecialPrintableRepresentation().
IsDereferenceOfParent()
virtual bool lldb_private::ValueObject::IsDereferenceOfParent () inline virtual
Reimplemented in lldb_private::ValueObjectChild.
Definition at line 402 of file ValueObject.h.
Referenced by GetExpressionPath().
IsDynamic()
virtual bool lldb_private::ValueObject::IsDynamic () inline virtual
Reimplemented in lldb_private::ValueObjectDynamicValue, and lldb_private::ValueObjectSynthetic.
Definition at line 687 of file ValueObject.h.
Referenced by CalculateDynamicValue(), GetDynamicValue(), lldb_private::ValueObjectConstResult::GetDynamicValue(), lldb_private::FormatManager::GetPossibleMatches(), GetQualifiedRepresentationIfAvailable(), and lldb_private::Process::IsPossibleDynamicValue().
IsInScope()
virtual bool lldb_private::ValueObject::IsInScope () inline virtual
Reimplemented in lldb_private::ValueObjectCast, lldb_private::ValueObjectChild, lldb_private::ValueObjectConstResult, lldb_private::ValueObjectDynamicValue, lldb_private::ValueObjectMemory, lldb_private::ValueObjectSynthetic, lldb_private::ValueObjectVariable, lldb_private::ValueObjectVTable, and ValueObjectVTableChild.
Definition at line 420 of file ValueObject.h.
Referenced by lldb_private::ValueObjectPrinter::CheckScopeIfNeeded(), lldb_private::ValueObjectChild::IsInScope(), lldb_private::ValueObjectVTable::IsInScope(), and UpdateValueIfNeeded().
IsIntegerType()
bool lldb_private::ValueObject::IsIntegerType (bool & is_signed) inline
Definition at line 404 of file ValueObject.h.
References GetCompilerType(), and lldb_private::CompilerType::IsIntegerType().
IsLogicalTrue()
bool ValueObject::IsLogicalTrue (Status & error) virtual
Definition at line 354 of file ValueObject.cpp.
References lldb_private::eLazyBoolCalculate, lldb_private::eLazyBoolNo, lldb_private::eLazyBoolYes, error(), lldb_private::Language::FindPlugin(), lldb_private::Status::FromErrorString(), GetObjectRuntimeLanguage(), ResolveValue(), and lldb_private::Scalar::ULongLong().
IsNilReference()
bool ValueObject::IsNilReference ()
Definition at line 1801 of file ValueObject.cpp.
References lldb_private::Language::FindPlugin(), and GetObjectRuntimeLanguage().
Referenced by lldb_private::ValueObjectPrinter::IsNil().
IsPointerOrReferenceType()
bool lldb_private::ValueObject::IsPointerOrReferenceType () inline
Definition at line 388 of file ValueObject.h.
References GetCompilerType(), and lldb_private::CompilerType::IsPointerOrReferenceType().
Referenced by GetExpressionPath().
IsPointerType()
bool lldb_private::ValueObject::IsPointerType () inline
Definition at line 382 of file ValueObject.h.
References GetCompilerType(), and lldb_private::CompilerType::IsPointerType().
Referenced by lldb_private::formatters::CFBagSummaryProvider(), lldb_private::formatters::CFBinaryHeapSummaryProvider(), lldb_private::formatters::CFBitVectorSummaryProvider(), lldb_private::formatters::GetArrayAddressOrPointerValue(), GetSyntheticArrayMember(), GetValueAsAPSInt(), and lldb_private::CPlusPlusLanguage::IsNilReference().
IsPossibleDynamicType()
bool ValueObject::IsPossibleDynamicType ()
Definition at line 1775 of file ValueObject.cpp.
References GetCompilerType(), GetExecutionContextRef(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::CompilerType::IsPossibleDynamicType(), and lldb_private::Process::IsPossibleDynamicValue().
Referenced by GetChildAtIndex(), and GetChildMemberWithName().
IsRuntimeSupportValue()
bool ValueObject::IsRuntimeSupportValue () virtual
Definition at line 1784 of file ValueObject.cpp.
References lldb_private::Process::GetLanguageRuntime(), GetName(), GetProcessSP(), and GetVariable().
IsScalarType()
bool lldb_private::ValueObject::IsScalarType () inline
Definition at line 386 of file ValueObject.h.
References GetCompilerType(), and lldb_private::CompilerType::IsScalarType().
Referenced by GetSyntheticBitFieldChild().
IsSynthetic()
virtual bool lldb_private::ValueObject::IsSynthetic () inline virtual
Reimplemented in lldb_private::ValueObjectRecognizerSynthesizedValue, and lldb_private::ValueObjectSynthetic.
Definition at line 616 of file ValueObject.h.
Referenced by Dereference(), lldb_private::FormatEntity::Formatter::DumpValue(), lldb_private::DumpValueObjectOptions::DumpValueObjectOptions(), GetAlternateValue(), and lldb_private::FormatManager::GetTypeForCache().
IsSyntheticChildrenGenerated()
virtual bool lldb_private::ValueObject::IsSyntheticChildrenGenerated () inline virtual
Reimplemented in lldb_private::ValueObjectDynamicValue, and lldb_private::ValueObjectSynthetic.
Definition at line 691 of file ValueObject.h.
References m_flags.
IsUninitializedReference()
bool ValueObject::IsUninitializedReference ()
Definition at line 1808 of file ValueObject.cpp.
References lldb_private::Language::FindPlugin(), and GetObjectRuntimeLanguage().
Referenced by lldb_private::ValueObjectPrinter::IsUninitialized().
MightHaveChildren()
bool ValueObject::MightHaveChildren () virtual
Find out if a ValueObject might have children.
This call is much more efficient than CalculateNumChildren() as it doesn't need to complete the underlying type. This is designed to be used in a UI environment in order to detect if the disclosure triangle should be displayed or not.
This function returns true for class, union, structure, pointers, references, arrays and more. Again, it does so without doing any expensive type completion.
Returns
Returns true if the ValueObject might have children, or false otherwise.
Reimplemented in lldb_private::ValueObjectSynthetic.
Definition at line 478 of file ValueObject.cpp.
References GetNumChildrenIgnoringErrors(), and GetTypeInfo().
Referenced by lldb_private::ValueObjectPrinter::ShouldPrintEmptyBrackets().
NeedsUpdating()
bool lldb_private::ValueObject::NeedsUpdating () inline
Definition at line 776 of file ValueObject.h.
References CanUpdateWithInvalidExecutionContext(), lldb_private::eLazyBoolYes, and m_update_point.
Referenced by UpdateValueIfNeeded().
operator=()
const ValueObject & lldb_private::ValueObject::operator= (const ValueObject &) private delete
References ValueObject().
Persist()
ValueObjectSP ValueObject::Persist ()
Definition at line 3748 of file ValueObject.cpp.
References lldb_private::ValueObjectConstResult::Create(), lldb_private::PersistentExpressionState::CreatePersistentVariable(), lldb_private::ExpressionVariable::EVIsProgramReference, lldb_private::PersistentExpressionState::GetNextPersistentVariableName(), GetPreferredDisplayLanguage(), GetTargetSP(), GetValue(), and UpdateValueIfNeeded().
ReadPointedString()
std::pair< size_t, bool > ValueObject::ReadPointedString (lldb::WritableDataBufferSP & buffer_sp, Status & error, bool honor_array)
Definition at line 884 of file ValueObject.cpp.
References lldb_private::ValueObject::AddrAndType::address, lldb_private::Flags::AnySet(), CopyStringDataToBufferSP(), lldb_private::eAddressTypeHost, error(), lldb_private::Status::FromErrorString(), GetAddressOf(), lldb_private::DataExtractor::GetByteSize(), GetCompilerType(), GetDataExtractor(), GetExecutionContextRef(), lldb_private::TargetProperties::GetMaximumSizeOfStringSummary(), GetPointeeData(), GetPointerValue(), lldb_private::ExecutionContext::GetTargetPtr(), GetTypeInfo(), lldb_private::CompilerType::IsArrayType(), lldb_private::CompilerType::IsCharType(), LLDB_INVALID_ADDRESS, lldb_private::DataExtractor::PeekCStr(), lldb_private::DataExtractor::PeekData(), lldb_private::Stream::Printf(), Target, lldb_private::Flags::Test(), and lldb_private::ValueObject::AddrAndType::type.
Referenced by DumpPrintableRepresentation().
ResolveValue()
bool ValueObject::ResolveValue (Scalar & scalar) virtual
Reimplemented in lldb_private::ValueObjectRegister.
Definition at line 336 of file ValueObject.cpp.
References lldb_private::Scalar::ExtractBitfield(), GetBitfieldBitOffset(), GetBitfieldBitSize(), GetExecutionContextRef(), GetModule(), lldb_private::Scalar::IsValid(), m_value, lldb_private::Value::ResolveValue(), and UpdateValueIfNeeded().
Referenced by lldb_private::AppleObjCRuntime::GetObjectDescription(), GetValueAsAPFloat(), GetValueAsAPSInt(), GetValueAsSigned(), GetValueAsUnsigned(), and IsLogicalTrue().
SetAddressTypeOfChildren()
void lldb_private::ValueObject::SetAddressTypeOfChildren (AddressType at) inline
Definition at line 844 of file ValueObject.h.
References m_address_type_of_ptr_or_ref_children.
Referenced by lldb_private::ValueObjectVariable::DoUpdateChildrenAddressType(), lldb_private::ValueObjectCast::UpdateValue(), lldb_private::ValueObjectChild::ValueObjectChild(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), and lldb_private::ValueObjectConstResult::ValueObjectConstResult().
SetData()
bool ValueObject::SetData (DataExtractor & data, Status & error) virtual
Reimplemented in lldb_private::ValueObjectDynamicValue, lldb_private::ValueObjectRegister, and lldb_private::ValueObjectVariable.
Definition at line 792 of file ValueObject.cpp.
References lldb_private::Status::AsCString(), lldb_private::DataExtractor::CopyByteOrderedData(), error(), lldb_private::Value::FileAddress, lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), GetByteSize(), GetCompilerType(), lldb_private::DataExtractor::GetDataStart(), lldb_private::CompilerType::GetEncoding(), GetExecutionContextRef(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::Value::HostAddress, lldb_private::Value::Invalid, LLDB_INVALID_ADDRESS, lldb_private::Value::LoadAddress, m_data, m_value, lldb_private::Value::Scalar, SetNeedsUpdate(), lldb_private::Status::Success(), UpdateValueIfNeeded(), and lldb_private::Process::WriteMemory().
Referenced by lldb_private::ValueObjectVariable::SetData(), and SetValueFromInteger().
SetDerefValobj()
void lldb_private::ValueObject::SetDerefValobj (ValueObject * deref) inline
Definition at line 808 of file ValueObject.h.
References m_deref_valobj, and ValueObject().
SetFormat()
virtual void lldb_private::ValueObject::SetFormat (lldb::Format format) inline virtual
Reimplemented in lldb_private::ValueObjectSynthetic.
Definition at line 786 of file ValueObject.h.
References ClearUserVisibleData(), eClearUserVisibleDataItemsValue, and m_format.
Referenced by DumpPrintableRepresentation(), lldb_private::ValueObjectSynthetic::SetFormat(), lldb_private::ValueObjectVTable::ValueObjectVTable(), and ValueObjectVTableChild::ValueObjectVTableChild().
SetHasCompleteType()
void lldb_private::ValueObject::SetHasCompleteType () inline
Definition at line 850 of file ValueObject.h.
References m_flags.
SetIsConstant()
void lldb_private::ValueObject::SetIsConstant () inline
Definition at line 782 of file ValueObject.h.
References m_update_point.
Referenced by lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), and lldb_private::ValueObjectConstResult::ValueObjectConstResult().
SetLanguageFlags()
virtual void lldb_private::ValueObject::SetLanguageFlags (uint64_t flags) inline virtual
Reimplemented in lldb_private::ValueObjectDynamicValue, and lldb_private::ValueObjectSynthetic.
Definition at line 876 of file ValueObject.h.
References m_language_flags.
Referenced by lldb_private::ValueObjectDynamicValue::SetLanguageFlags(), lldb_private::ValueObjectSynthetic::SetLanguageFlags(), and lldb_private::ValueObjectChild::ValueObjectChild().
SetLiveAddress()
virtual void lldb_private::ValueObject::SetLiveAddress (lldb::addr_t addr = LLDB_INVALID_ADDRESS, AddressType address_type = eAddressTypeLoad) inline virtual
Reimplemented in lldb_private::ValueObjectConstResult.
Definition at line 636 of file ValueObject.h.
References lldb_private::eAddressTypeLoad, and LLDB_INVALID_ADDRESS.
SetName()
void lldb_private::ValueObject::SetName (ConstString name) inline
Change the name of the current ValueObject.
Should not be used from a synthetic child provider as it would change the name of the non synthetic child as well.
Definition at line 574 of file ValueObject.h.
References m_name.
Referenced by lldb_private::ValueObjectVTable::UpdateValue(), lldb_private::ValueObjectCast::ValueObjectCast(), lldb_private::ValueObjectDynamicValue::ValueObjectDynamicValue(), lldb_private::ValueObjectMemory::ValueObjectMemory(), lldb_private::ValueObjectMemory::ValueObjectMemory(), lldb_private::ValueObjectRecognizerSynthesizedValue::ValueObjectRecognizerSynthesizedValue(), lldb_private::ValueObjectSynthetic::ValueObjectSynthetic(), and ValueObjectVTableChild::ValueObjectVTableChild().
SetNeedsUpdate()
void ValueObject::SetNeedsUpdate ()
Definition at line 235 of file ValueObject.cpp.
References ClearUserVisibleData(), eClearUserVisibleDataItemsValue, and m_update_point.
Referenced by SetData(), lldb_private::ValueObjectDynamicValue::SetData(), lldb_private::ValueObjectRegister::SetData(), lldb_private::ValueObjectVariable::SetData(), SetValueFromCString(), lldb_private::ValueObjectDynamicValue::SetValueFromCString(), lldb_private::ValueObjectRegister::SetValueFromCString(), and lldb_private::ValueObjectVariable::SetValueFromCString().
SetNumChildren()
void ValueObject::SetNumChildren (uint32_t num_children) protected
Definition at line 491 of file ValueObject.cpp.
References m_children, and m_flags.
Referenced by GetNumChildren().
SetPreferredDisplayLanguage()
void lldb_private::ValueObject::SetPreferredDisplayLanguage (lldb::LanguageType lt) inline
Definition at line 794 of file ValueObject.h.
References m_preferred_display_language.
Referenced by lldb_private::ValueObjectDynamicValue::SetPreferredDisplayLanguage(), lldb_private::ValueObjectSynthetic::SetPreferredDisplayLanguage(), and SetPreferredDisplayLanguageIfNeeded().
SetPreferredDisplayLanguageIfNeeded()
void ValueObject::SetPreferredDisplayLanguageIfNeeded (lldb::LanguageType lt) protected
Definition at line 3735 of file ValueObject.cpp.
References lldb::eLanguageTypeUnknown, m_preferred_display_language, and SetPreferredDisplayLanguage().
SetSummaryFormat()
void lldb_private::ValueObject::SetSummaryFormat (lldb::TypeSummaryImplSP format) inline
Definition at line 803 of file ValueObject.h.
References ClearUserVisibleData(), eClearUserVisibleDataItemsSummary, and m_type_summary_sp.
Referenced by ClearDynamicTypeInformation(), and UpdateFormatsIfNeeded().
SetSyntheticChildren()
void lldb_private::ValueObject::SetSyntheticChildren (const lldb::SyntheticChildrenSP & synth_sp) inline
Definition at line 822 of file ValueObject.h.
References ClearUserVisibleData(), eClearUserVisibleDataItemsSyntheticChildren, and m_synthetic_children_sp.
Referenced by ClearDynamicTypeInformation(), and UpdateFormatsIfNeeded().
SetSyntheticChildrenGenerated()
virtual void lldb_private::ValueObject::SetSyntheticChildrenGenerated (bool b) inline virtual
Reimplemented in lldb_private::ValueObjectDynamicValue, and lldb_private::ValueObjectSynthetic.
Definition at line 695 of file ValueObject.h.
References m_flags.
Referenced by lldb_private::ValueObjectDynamicValue::SetSyntheticChildrenGenerated(), and lldb_private::ValueObjectSynthetic::SetSyntheticChildrenGenerated().
SetValueDidChange()
void lldb_private::ValueObject::SetValueDidChange (bool value_changed) inline protected
Definition at line 1078 of file ValueObject.h.
References m_flags.
Referenced by GetValueAsCString(), lldb_private::ValueObjectCast::UpdateValue(), lldb_private::ValueObjectDynamicValue::UpdateValue(), lldb_private::ValueObjectMemory::UpdateValue(), lldb_private::ValueObjectRegister::UpdateValue(), lldb_private::ValueObjectRegisterSet::UpdateValue(), lldb_private::ValueObjectVariable::UpdateValue(), lldb_private::ValueObjectVTable::UpdateValue(), ValueObjectVTableChild::UpdateValue(), and UpdateValueIfNeeded().
SetValueFormat()
void lldb_private::ValueObject::SetValueFormat (lldb::TypeFormatImplSP format) inline
Definition at line 812 of file ValueObject.h.
References ClearUserVisibleData(), eClearUserVisibleDataItemsValue, and m_type_format_sp.
Referenced by ClearDynamicTypeInformation(), and UpdateFormatsIfNeeded().
SetValueFromCString()
bool ValueObject::SetValueFromCString (const char * value_str, Status & error) virtual
Reimplemented in lldb_private::ValueObjectDynamicValue, lldb_private::ValueObjectRegister, lldb_private::ValueObjectSynthetic, and lldb_private::ValueObjectVariable.
Definition at line 1670 of file ValueObject.cpp.
References ConvertBoolean(), lldb_private::DataExtractor::CopyByteOrderedData(), error(), lldb_private::Value::FileAddress, lldb_private::Status::FromErrorString(), GetByteSize(), GetCompilerType(), lldb_private::Scalar::GetData(), lldb_private::CompilerType::GetEncoding(), GetExecutionContextRef(), GetObjectRuntimeLanguage(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::Value::HostAddress, lldb_private::Value::Invalid, LLDB_INVALID_ADDRESS, lldb_private::Value::LoadAddress, m_data, m_value, lldb_private::Value::Scalar, lldb_private::DataExtractor::SetByteOrder(), SetNeedsUpdate(), lldb_private::Scalar::SetValueFromCString(), UpdateValueIfNeeded(), and lldb_private::Process::WriteScalarToMemory().
Referenced by lldb_private::ValueObjectVariable::SetValueFromCString().
SetValueFromInteger() [1/2]
void ValueObject::SetValueFromInteger (const llvm::APInt & value, Status & error)
Update an existing integer ValueObject with a new integer value.
This is only intended to be used with 'temporary' ValueObjects, i.e. ones that are not associated with program variables. It does not update program memory, registers, stack, etc.
Definition at line 1211 of file ValueObject.cpp.
References error(), lldb_private::Status::FromErrorString(), GetByteSize(), GetCompilerType(), GetTargetSP(), GetVariable(), HasFloatingRepresentation(), lldb_private::CompilerType::IsInteger(), lldb_private::CompilerType::IsPointerType(), lldb_private::CompilerType::IsScalarType(), lldb_private::CompilerType::IsUnscopedEnumerationType(), and SetData().
Referenced by SetValueFromInteger().
SetValueFromInteger() [2/2]
void ValueObject::SetValueFromInteger (lldb::ValueObjectSP new_val_sp, Status & error)
Update an existing integer ValueObject with an integer value created frome 'new_val_sp'.
This is only intended to be used with 'temporary' ValueObjects, i.e. ones that are not associated with program variables. It does not update program memory, registers, stack, etc.
Definition at line 1250 of file ValueObject.cpp.
References error(), lldb_private::Status::FromErrorString(), GetCompilerType(), GetTargetSP(), GetVariable(), HasFloatingRepresentation(), lldb_private::CompilerType::IsInteger(), lldb_private::CompilerType::IsPointerType(), lldb_private::CompilerType::IsScalarType(), lldb_private::CompilerType::IsUnscopedEnumerationType(), and SetValueFromInteger().
SetValueIsValid()
void lldb_private::ValueObject::SetValueIsValid (bool valid) inline protected
Definition at line 1082 of file ValueObject.h.
References m_flags.
Referenced by lldb_private::ValueObjectCast::UpdateValue(), lldb_private::ValueObjectChild::UpdateValue(), lldb_private::ValueObjectConstResult::UpdateValue(), lldb_private::ValueObjectDynamicValue::UpdateValue(), lldb_private::ValueObjectMemory::UpdateValue(), lldb_private::ValueObjectRegister::UpdateValue(), lldb_private::ValueObjectRegisterSet::UpdateValue(), lldb_private::ValueObjectSynthetic::UpdateValue(), lldb_private::ValueObjectVariable::UpdateValue(), lldb_private::ValueObjectVTable::UpdateValue(), ValueObjectVTableChild::UpdateValue(), UpdateValueIfNeeded(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), and lldb_private::ValueObjectConstResult::ValueObjectConstResult().
UpdateChildrenAddressType()
void lldb_private::ValueObject::UpdateChildrenAddressType () inline private
Definition at line 1108 of file ValueObject.h.
References DoUpdateChildrenAddressType(), and GetRoot().
Referenced by UpdateValueIfNeeded().
UpdateFormatsIfNeeded()
bool ValueObject::UpdateFormatsIfNeeded ()
Definition at line 210 of file ValueObject.cpp.
References lldb_private::DataFormatters, lldb_private::DataVisualization::GetCurrentRevision(), GetDynamicValueType(), lldb_private::DataVisualization::GetFormat(), lldb_private::GetLog(), GetName(), lldb_private::DataVisualization::GetSummaryFormat(), lldb_private::DataVisualization::GetSyntheticChildren(), LLDB_LOGF, m_last_format_mgr_revision, SetSummaryFormat(), SetSyntheticChildren(), and SetValueFormat().
Referenced by CalculateSyntheticValue(), GetSummaryFormat(), GetSyntheticChildren(), GetValueFormat(), HasSyntheticValue(), and UpdateValueIfNeeded().
UpdateValue()
virtual bool lldb_private::ValueObject::UpdateValue () protected pure virtual
Implemented in lldb_private::ValueObjectCast, lldb_private::ValueObjectChild, lldb_private::ValueObjectConstResult, lldb_private::ValueObjectDynamicValue, lldb_private::ValueObjectMemory, lldb_private::ValueObjectRecognizerSynthesizedValue, lldb_private::ValueObjectRegister, lldb_private::ValueObjectRegisterSet, lldb_private::ValueObjectSynthetic, lldb_private::ValueObjectVariable, lldb_private::ValueObjectVTable, and ValueObjectVTableChild.
Referenced by UpdateValueIfNeeded().
UpdateValueIfNeeded()
bool ValueObject::UpdateValueIfNeeded (bool update_format = true)
Definition at line 119 of file ValueObject.cpp.
References CanProvideValue(), ClearUserVisibleData(), eClearUserVisibleDataItemsDescription, eClearUserVisibleDataItemsSummary, eClearUserVisibleDataItemsValue, lldb_private::Status::FromErrorString(), GetIsConstant(), GetValueIsValid(), IsChecksumEmpty(), IsInScope(), m_data, m_error, m_flags, m_old_value_str, m_update_point, m_value_checksum, m_value_str, NeedsUpdating(), SetValueDidChange(), SetValueIsValid(), UpdateChildrenAddressType(), UpdateFormatsIfNeeded(), and UpdateValue().
Referenced by lldb_private::ValueObjectDynamicValue::CalculateNumChildren(), lldb_private::ValueObjectSynthetic::CalculateNumChildren(), lldb_private::ValueObjectVTable::CalculateNumChildren(), lldb_private::ValueObjectSynthetic::CanProvideValue(), lldb_private::ValueObjectSynthetic::CopyValueData(), CreateConstantValue(), lldb_private::ValueObjectSynthetic::DoesProvideSyntheticValue(), GetAddressOf(), lldb_private::ValueObjectDynamicValue::GetByteSize(), GetChildAtIndex(), lldb_private::ValueObjectSynthetic::GetChildAtIndex(), GetChildMemberWithName(), lldb_private::ValueObjectSynthetic::GetChildMemberWithName(), lldb_private::ValueObjectDynamicValue::GetCompilerTypeImpl(), GetData(), GetDataExtractor(), lldb_private::ValueObjectDynamicValue::GetDisplayTypeName(), GetError(), GetExpressionPath(), lldb_private::ValueObjectSynthetic::GetIndexOfChildWithName(), GetLocationAsCStringImpl(), GetNumChildren(), GetObjectDescription(), GetPointerValue(), lldb_private::ValueObjectDynamicValue::GetQualifiedTypeName(), GetSummaryAsCString(), GetSummaryAsCString(), lldb_private::ValueObjectDynamicValue::GetTypeImpl(), lldb_private::ValueObjectDynamicValue::GetTypeName(), GetValueAsCString(), GetValueAsCString(), Persist(), ResolveValue(), lldb_private::ValueObjectRegister::ResolveValue(), SetData(), lldb_private::ValueObjectDynamicValue::SetData(), lldb_private::ValueObjectVariable::SetData(), SetValueFromCString(), lldb_private::ValueObjectDynamicValue::SetValueFromCString(), lldb_private::ValueObjectVariable::SetValueFromCString(), and lldb_private::ValueObjectChild::UpdateValue().
ValueUpdated()
void lldb_private::ValueObject::ValueUpdated () inline
Definition at line 681 of file ValueObject.h.
References ClearUserVisibleData(), eClearUserVisibleDataItemsDescription, eClearUserVisibleDataItemsSummary, and eClearUserVisibleDataItemsValue.
Friends And Related Symbol Documentation
ExpressionVariable
friend class ExpressionVariable friend
Definition at line 1030 of file ValueObject.h.
References ExpressionVariable.
Referenced by ExpressionVariable.
Target
friend class Target friend
Definition at line 1031 of file ValueObject.h.
References Target.
Referenced by GetPointeeData(), ReadPointedString(), Target, lldb_private::ValueObjectDynamicValue::UpdateValue(), lldb_private::ValueObjectMemory::UpdateValue(), and lldb_private::ValueObjectVariable::UpdateValue().
ValueObjectChild
friend class ValueObjectChild friend
Definition at line 1029 of file ValueObject.h.
References ValueObjectChild.
Referenced by CreateChildAtIndex(), CreateSyntheticArrayMember(), Dereference(), GetSyntheticBase(), GetSyntheticBitFieldChild(), GetSyntheticChildAtOffset(), and ValueObjectChild.
ValueObjectConstResultImpl
friend class ValueObjectConstResultImpl friend
Definition at line 1032 of file ValueObject.h.
References ValueObjectConstResultImpl.
Referenced by ValueObjectConstResultImpl.
ValueObjectSynthetic
friend class ValueObjectSynthetic friend
Definition at line 1033 of file ValueObject.h.
References lldb_private::eAddressTypeLoad, ValueObject(), and ValueObjectSynthetic.
Referenced by CalculateSyntheticValue(), and ValueObjectSynthetic.
Member Data Documentation
m_addr_of_valobj_sp
lldb::ValueObjectSP lldb_private::ValueObject::m_addr_of_valobj_sp protected
We have to hold onto a shared pointer to this one because it is created as an independent ValueObjectConstResult, which isn't managed by us.
Definition at line 985 of file ValueObject.h.
Referenced by AddressOf().
m_address_type_of_ptr_or_ref_children
AddressType lldb_private::ValueObject::m_address_type_of_ptr_or_ref_children = eAddressTypeInvalid protected
Definition at line 994 of file ValueObject.h.
Referenced by GetAddressTypeOfChildren(), SetAddressTypeOfChildren(), and ValueObject().
m_children
ChildrenManager lldb_private::ValueObject::m_children protected
Definition at line 976 of file ValueObject.h.
Referenced by GetChildAtIndex(), GetNumChildren(), SetNumChildren(), and lldb_private::ValueObjectRegisterSet::UpdateValue().
m_data
DataExtractor lldb_private::ValueObject::m_data protected
A data extractor that can be used to extract the value.
Definition at line 949 of file ValueObject.h.
Referenced by lldb_private::ValueObjectSynthetic::CopyValueData(), CreateConstantValue(), GetData(), GetDataExtractor(), GetLocalBuffer(), GetLocationAsCString(), lldb_private::ValueObjectVariable::GetLocationAsCString(), GetPointerValue(), SetData(), SetValueFromCString(), lldb_private::ValueObjectCast::UpdateValue(), lldb_private::ValueObjectChild::UpdateValue(), lldb_private::ValueObjectDynamicValue::UpdateValue(), lldb_private::ValueObjectMemory::UpdateValue(), lldb_private::ValueObjectRegister::UpdateValue(), lldb_private::ValueObjectVariable::UpdateValue(), ValueObjectVTableChild::UpdateValue(), UpdateValueIfNeeded(), ValueObject(), ValueObject(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), and lldb_private::ValueObjectConstResult::ValueObjectConstResult().
m_deref_valobj
ValueObject* lldb_private::ValueObject::m_deref_valobj = nullptr protected
Definition at line 981 of file ValueObject.h.
Referenced by Dereference(), GetDerefValobj(), and SetDerefValobj().
m_dynamic_value
ValueObject* lldb_private::ValueObject::m_dynamic_value = nullptr protected
Definition at line 979 of file ValueObject.h.
Referenced by CalculateDynamicValue(), GetDynamicValue(), and lldb_private::ValueObjectConstResult::GetDynamicValue().
m_error
Status lldb_private::ValueObject::m_error protected
An error object that can describe any errors that occur when updating values.
Definition at line 953 of file ValueObject.h.
Referenced by lldb_private::ValueObjectSynthetic::CopyValueData(), CreateConstantValue(), DumpPrintableRepresentation(), GetError(), lldb_private::ValueObjectCast::UpdateValue(), lldb_private::ValueObjectChild::UpdateValue(), lldb_private::ValueObjectDynamicValue::UpdateValue(), lldb_private::ValueObjectMemory::UpdateValue(), lldb_private::ValueObjectRegister::UpdateValue(), lldb_private::ValueObjectRegisterSet::UpdateValue(), lldb_private::ValueObjectSynthetic::UpdateValue(), lldb_private::ValueObjectVariable::UpdateValue(), lldb_private::ValueObjectVTable::UpdateValue(), ValueObjectVTableChild::UpdateValue(), UpdateValueIfNeeded(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), and lldb_private::ValueObjectConstResult::ValueObjectConstResult().
m_flags
struct lldb_private::ValueObject::Bitflags lldb_private::ValueObject::m_flags protected
Referenced by ClearDynamicTypeInformation(), GetCompilerType(), GetExpressionPath(), GetNumChildren(), GetSummaryAsCString(), GetValueAsCString(), GetValueDidChange(), GetValueIsValid(), IsSyntheticChildrenGenerated(), SetHasCompleteType(), SetNumChildren(), SetSyntheticChildrenGenerated(), SetValueDidChange(), SetValueIsValid(), lldb_private::ValueObjectSynthetic::UpdateValue(), lldb_private::ValueObjectVTable::UpdateValue(), UpdateValueIfNeeded(), and ValueObject().
m_format
lldb::Format lldb_private::ValueObject::m_format = lldb::eFormatDefault protected
Definition at line 987 of file ValueObject.h.
Referenced by GetFormat(), and SetFormat().
m_id
UserID lldb_private::ValueObject::m_id protected
Unique identifier for every value object.
Definition at line 1003 of file ValueObject.h.
Referenced by GetID(), ValueObject(), and ValueObject().
m_language_flags
uint64_t lldb_private::ValueObject::m_language_flags = 0 protected
Definition at line 1000 of file ValueObject.h.
Referenced by GetLanguageFlags(), and SetLanguageFlags().
m_last_format
lldb::Format lldb_private::ValueObject::m_last_format = lldb::eFormatDefault protected
Definition at line 988 of file ValueObject.h.
Referenced by GetValueAsCString().
m_last_format_mgr_revision
uint32_t lldb_private::ValueObject::m_last_format_mgr_revision = 0 protected
Definition at line 989 of file ValueObject.h.
Referenced by ClearDynamicTypeInformation(), and UpdateFormatsIfNeeded().
m_location_str
std::string lldb_private::ValueObject::m_location_str protected
Cached location string that will get cleared if/when the value is updated.
Definition at line 959 of file ValueObject.h.
Referenced by ClearUserVisibleData(), and GetLocationAsCStringImpl().
m_manager
ValueObjectManager* lldb_private::ValueObject::m_manager = nullptr protected
This object is managed by the root object (any ValueObject that gets created without a parent.) The manager gets passed through all the generations of dependent objects, and will keep the whole cluster of objects alive as long as a shared pointer to any of them has been handed out.
Shared pointers to value objects must always be made with the GetSP method.
Definition at line 974 of file ValueObject.h.
Referenced by GetManager(), GetSP(), ValueObject(), and ValueObject().
m_name
ConstString lldb_private::ValueObject::m_name protected
The name of this object.
Definition at line 947 of file ValueObject.h.
Referenced by AddressOf(), lldb_private::ValueObjectRegister::ConstructObject(), GetExpressionPath(), GetName(), SetName(), lldb_private::ValueObjectRegisterSet::UpdateValue(), lldb_private::ValueObjectChild::ValueObjectChild(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResultCast::ValueObjectConstResultCast(), lldb_private::ValueObjectConstResultChild::ValueObjectConstResultChild(), lldb_private::ValueObjectRegisterSet::ValueObjectRegisterSet(), and lldb_private::ValueObjectVariable::ValueObjectVariable().
m_object_desc_str
std::string lldb_private::ValueObject::m_object_desc_str protected
Cached result of the "object printer".
This differs from the summary in that the summary is consed up by us, the object_desc_string is builtin.
Definition at line 964 of file ValueObject.h.
Referenced by ClearUserVisibleData(), and GetObjectDescription().
m_old_value_str
std::string lldb_private::ValueObject::m_old_value_str protected
Cached old value string from the last time the value was gotten.
Definition at line 957 of file ValueObject.h.
Referenced by GetValueAsCString(), and UpdateValueIfNeeded().
m_override_type
CompilerType lldb_private::ValueObject::m_override_type protected
If the type of the value object should be overridden, the type to impose.
Definition at line 966 of file ValueObject.h.
Referenced by ClearDynamicTypeInformation(), and GetCompilerType().
m_parent
ValueObject* lldb_private::ValueObject::m_parent = nullptr protected
The parent value object, or nullptr if this has no parent.
Definition at line 938 of file ValueObject.h.
Referenced by lldb_private::ValueObjectDynamicValue::CalculateNumChildren(), lldb_private::ValueObjectRecognizerSynthesizedValue::CalculateNumChildren(), lldb_private::ValueObjectSynthetic::CanProvideValue(), lldb_private::ValueObjectChild::CanUpdateWithInvalidExecutionContext(), lldb_private::ValueObjectSynthetic::CreateSynthFilter(), FollowParentChain(), lldb_private::ValueObjectDynamicValue::GetByteSize(), lldb_private::ValueObjectRecognizerSynthesizedValue::GetByteSize(), lldb_private::ValueObjectSynthetic::GetByteSize(), lldb_private::ValueObjectDynamicValue::GetCompilerTypeImpl(), lldb_private::ValueObjectRecognizerSynthesizedValue::GetCompilerTypeImpl(), lldb_private::ValueObjectSynthetic::GetCompilerTypeImpl(), lldb_private::ValueObjectDynamicValue::GetDeclaration(), lldb_private::ValueObjectSynthetic::GetDeclaration(), lldb_private::ValueObjectDynamicValue::GetDisplayTypeName(), lldb_private::ValueObjectSynthetic::GetDisplayTypeName(), lldb_private::ValueObjectSynthetic::GetDynamicValue(), GetDynamicValueType(), lldb_private::ValueObjectSynthetic::GetDynamicValueType(), GetFormat(), lldb_private::ValueObjectDynamicValue::GetLanguageFlags(), lldb_private::ValueObjectSynthetic::GetLanguageFlags(), lldb_private::ValueObjectSynthetic::GetNonSyntheticValue(), GetParent(), GetParent(), lldb_private::ValueObjectCast::GetParent(), lldb_private::ValueObjectCast::GetParent(), lldb_private::ValueObjectDynamicValue::GetParent(), lldb_private::ValueObjectDynamicValue::GetParent(), lldb_private::ValueObjectSynthetic::GetParent(), lldb_private::ValueObjectSynthetic::GetParent(), lldb_private::ValueObjectDynamicValue::GetPreferredDisplayLanguage(), lldb_private::ValueObjectSynthetic::GetPreferredDisplayLanguage(), lldb_private::ValueObjectDynamicValue::GetQualifiedTypeName(), lldb_private::ValueObjectSynthetic::GetQualifiedTypeName(), GetRoot(), lldb_private::ValueObjectDynamicValue::GetStaticValue(), lldb_private::ValueObjectSynthetic::GetStaticValue(), GetSymbolContextScope(), lldb_private::ValueObjectDynamicValue::GetTypeImpl(), lldb_private::ValueObjectDynamicValue::GetTypeName(), lldb_private::ValueObjectSynthetic::GetTypeName(), lldb_private::ValueObjectCast::GetValueType(), lldb_private::ValueObjectChild::GetValueType(), lldb_private::ValueObjectDynamicValue::GetValueType(), lldb_private::ValueObjectSynthetic::GetValueType(), lldb_private::ValueObjectDynamicValue::GetVariable(), lldb_private::ValueObjectSynthetic::GetVariable(), lldb_private::ValueObjectDynamicValue::IsBaseClass(), lldb_private::ValueObjectSynthetic::IsDynamic(), lldb_private::ValueObjectCast::IsInScope(), lldb_private::ValueObjectDynamicValue::IsInScope(), lldb_private::ValueObjectSynthetic::IsInScope(), lldb_private::ValueObjectDynamicValue::IsSyntheticChildrenGenerated(), lldb_private::ValueObjectSynthetic::IsSyntheticChildrenGenerated(), lldb_private::ValueObjectDynamicValue::SetData(), lldb_private::ValueObjectSynthetic::SetFormat(), lldb_private::ValueObjectDynamicValue::SetLanguageFlags(), lldb_private::ValueObjectSynthetic::SetLanguageFlags(), lldb_private::ValueObjectDynamicValue::SetPreferredDisplayLanguage(), lldb_private::ValueObjectSynthetic::SetPreferredDisplayLanguage(), lldb_private::ValueObjectDynamicValue::SetSyntheticChildrenGenerated(), lldb_private::ValueObjectSynthetic::SetSyntheticChildrenGenerated(), lldb_private::ValueObjectDynamicValue::SetValueFromCString(), lldb_private::ValueObjectSynthetic::SetValueFromCString(), lldb_private::ValueObjectCast::UpdateValue(), lldb_private::ValueObjectChild::UpdateValue(), lldb_private::ValueObjectDynamicValue::UpdateValue(), lldb_private::ValueObjectRecognizerSynthesizedValue::UpdateValue(), lldb_private::ValueObjectSynthetic::UpdateValue(), ValueObject(), and lldb_private::ValueObjectSynthetic::ValueObjectSynthetic().
m_preferred_display_language
lldb::LanguageType lldb_private::ValueObject::m_preferred_display_language = lldb::eLanguageTypeUnknown protected
Definition at line 998 of file ValueObject.h.
Referenced by GetPreferredDisplayLanguage(), lldb_private::ValueObjectConstResult::GetPreferredDisplayLanguage(), lldb_private::ValueObjectDynamicValue::GetPreferredDisplayLanguage(), lldb_private::ValueObjectSynthetic::GetPreferredDisplayLanguage(), SetPreferredDisplayLanguage(), and SetPreferredDisplayLanguageIfNeeded().
m_root
ValueObject* lldb_private::ValueObject::m_root = nullptr protected
The root of the hierarchy for this ValueObject (or nullptr if never calculated).
Definition at line 941 of file ValueObject.h.
Referenced by GetRoot().
m_summary_str
std::string lldb_private::ValueObject::m_summary_str protected
Cached summary string that will get cleared if/when the value is updated.
Definition at line 961 of file ValueObject.h.
Referenced by ClearUserVisibleData(), and GetSummaryAsCString().
m_synthetic_children
std::map<ConstString, ValueObject *> lldb_private::ValueObject::m_synthetic_children protected
Definition at line 977 of file ValueObject.h.
Referenced by AddSyntheticChild(), and GetSyntheticChild().
m_synthetic_children_sp
lldb::SyntheticChildrenSP lldb_private::ValueObject::m_synthetic_children_sp protected
Definition at line 992 of file ValueObject.h.
Referenced by CalculateSyntheticValue(), GetSyntheticChildren(), HasSyntheticValue(), and SetSyntheticChildren().
m_synthetic_value
ValueObject* lldb_private::ValueObject::m_synthetic_value = nullptr protected
Definition at line 980 of file ValueObject.h.
Referenced by CalculateSyntheticValue(), ClearUserVisibleData(), GetSummaryAsCString(), GetSyntheticValue(), and HasSyntheticValue().
m_type_format_sp
lldb::TypeFormatImplSP lldb_private::ValueObject::m_type_format_sp protected
Definition at line 991 of file ValueObject.h.
Referenced by GetValueAsCString(), GetValueFormat(), and SetValueFormat().
m_type_summary_sp
lldb::TypeSummaryImplSP lldb_private::ValueObject::m_type_summary_sp protected
Definition at line 990 of file ValueObject.h.
Referenced by GetSummaryFormat(), and SetSummaryFormat().
m_update_point
EvaluationPoint lldb_private::ValueObject::m_update_point protected
Stores both the stop id and the full context at which this value was last updated.
When we are asked to update the value object, we check whether the context & stop id are the same before updating.
Definition at line 945 of file ValueObject.h.
Referenced by GetExecutionContextRef(), GetFrameSP(), GetIsConstant(), GetProcessSP(), GetTargetSP(), GetThreadSP(), GetUpdatePoint(), GetUpdatePoint(), NeedsUpdating(), SetIsConstant(), SetNeedsUpdate(), lldb_private::ValueObjectCast::UpdateValue(), lldb_private::ValueObjectDynamicValue::UpdateValue(), UpdateValueIfNeeded(), ValueObject(), and ValueObject().
m_user_id_of_forced_summary
ProcessModID lldb_private::ValueObject::m_user_id_of_forced_summary protected
Definition at line 993 of file ValueObject.h.
m_value
Value lldb_private::ValueObject::m_value protected
Definition at line 950 of file ValueObject.h.
Referenced by Cast(), lldb_private::ValueObjectSynthetic::CopyValueData(), CreateConstantValue(), GetAddressOf(), lldb_private::ValueObjectCast::GetByteSize(), lldb_private::ValueObjectDynamicValue::GetByteSize(), lldb_private::ValueObjectConstResult::GetCompilerTypeImpl(), lldb_private::ValueObjectDynamicValue::GetCompilerTypeImpl(), ValueObjectVTableChild::GetCompilerTypeImpl(), GetData(), GetExpressionPath(), GetLocalBuffer(), GetLocationAsCString(), GetPointeeData(), GetPointerValue(), GetValue(), GetValue(), GetValueAsCString(), ResolveValue(), SetData(), SetValueFromCString(), lldb_private::ValueObjectCast::UpdateValue(), lldb_private::ValueObjectChild::UpdateValue(), lldb_private::ValueObjectDynamicValue::UpdateValue(), lldb_private::ValueObjectMemory::UpdateValue(), lldb_private::ValueObjectRecognizerSynthesizedValue::UpdateValue(), lldb_private::ValueObjectRegister::UpdateValue(), lldb_private::ValueObjectVariable::UpdateValue(), lldb_private::ValueObjectVTable::UpdateValue(), ValueObjectVTableChild::UpdateValue(), lldb_private::ValueObjectCast::ValueObjectCast(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectMemory::ValueObjectMemory(), and lldb_private::ValueObjectMemory::ValueObjectMemory().
m_value_checksum
llvm::SmallVector<uint8_t, 16> lldb_private::ValueObject::m_value_checksum protected
Definition at line 996 of file ValueObject.h.
Referenced by IsChecksumEmpty(), and UpdateValueIfNeeded().
m_value_str
std::string lldb_private::ValueObject::m_value_str protected
Cached value string that will get cleared if/when the value is updated.
Definition at line 955 of file ValueObject.h.
Referenced by ClearUserVisibleData(), GetValueAsCString(), and UpdateValueIfNeeded().
The documentation for this class was generated from the following files:
ValueObject.h
ValueObject.cpp