LLDB: lldb::SBStringList Class Reference
lldb::SBStringList Class Reference
#include <SBStringList.h>
Public Member Functions
SBStringList ()
SBStringList (const lldb::SBStringList &rhs)
const SBStringList & operator= (const SBStringList &rhs)
~SBStringList ()
operator bool () const
bool IsValid () const
void AppendString (const char *str)
void AppendList (const char **strv, int strc)
void AppendList (const lldb::SBStringList &strings)
uint32_t GetSize () const
const char * GetStringAtIndex (size_t idx)
const char * GetStringAtIndex (size_t idx) const
void Clear ()
Protected Member Functions
SBStringList (const lldb_private::StringList *lldb_strings)
void AppendList (const lldb_private::StringList &strings)
lldb_private::StringList * operator-> ()
const lldb_private::StringList * operator-> () const
const lldb_private::StringList & operator* () const
Private Attributes
std::unique_ptr< lldb_private::StringList > m_opaque_up
Friends
class SBCommandInterpreter
class SBDebugger
class SBBreakpoint
class SBBreakpointLocation
class SBBreakpointName
class SBStructuredData
Detailed Description
Definition at line 16 of file SBStringList.h.
Constructor & Destructor Documentation
SBStringList() [1/3]
SBStringList::SBStringList ()
Definition at line 17 of file SBStringList.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by AppendList(), operator=(), SBStringList(), and SBStructuredData.
SBStringList() [2/3]
SBStringList::SBStringList (const lldb::SBStringList & rhs)
Definition at line 24 of file SBStringList.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBStringList().
~SBStringList()
SBStringList::~SBStringList () default
References AppendList(), AppendString(), Clear(), GetSize(), GetStringAtIndex(), and IsValid().
SBStringList() [3/3]
SBStringList::SBStringList (const lldb_private::StringList * lldb_strings) protected
Definition at line 19 of file SBStringList.cpp.
References m_opaque_up.
Member Function Documentation
AppendList() [1/3]
void SBStringList::AppendList (const char ** strv, int strc)
Definition at line 76 of file SBStringList.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBBreakpoint::GetCommandLineCommands(), lldb::SBBreakpointLocation::GetCommandLineCommands(), lldb::SBBreakpointName::GetCommandLineCommands(), lldb::SBCommandInterpreter::HandleCompletionWithDescriptions(), SBStructuredData, and ~SBStringList().
AppendList() [2/3]
void SBStringList::AppendList (const lldb::SBStringList & strings)
Definition at line 87 of file SBStringList.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBStringList().
AppendList() [3/3]
void SBStringList::AppendList (const lldb_private::StringList & strings) protected
Definition at line 97 of file SBStringList.cpp.
References IsValid(), and m_opaque_up.
AppendString()
void SBStringList::AppendString (const char * str)
Definition at line 65 of file SBStringList.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBTarget::GetBreakpointNames(), lldb::SBEnvironment::GetEntries(), lldb::SBBreakpoint::GetNames(), and ~SBStringList().
Clear()
void SBStringList::Clear ()
Definition at line 130 of file SBStringList.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBTarget::GetBreakpointNames(), and ~SBStringList().
GetSize()
uint32_t SBStringList::GetSize () const
Definition at line 103 of file SBStringList.cpp.
References IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBTarget::BreakpointCreateBySourceRegex(), lldb::SBTarget::BreakpointsCreateFromFile(), lldb::SBProcess::LoadImageUsingPaths(), lldb::SBBreakpoint::SetCommandLineCommands(), lldb::SBBreakpointLocation::SetCommandLineCommands(), lldb::SBBreakpointName::SetCommandLineCommands(), lldb::SBEnvironment::SetEntries(), and ~SBStringList().
GetStringAtIndex() [1/2]
const char * SBStringList::GetStringAtIndex (size_t idx)
Definition at line 112 of file SBStringList.cpp.
References lldb_private::ConstString::GetCString(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_up.
Referenced by lldb::SBTarget::BreakpointCreateBySourceRegex(), lldb::SBTarget::BreakpointsCreateFromFile(), lldb::SBProcess::LoadImageUsingPaths(), lldb::SBEnvironment::SetEntries(), and ~SBStringList().
GetStringAtIndex() [2/2]
const char * SBStringList::GetStringAtIndex (size_t idx) const
Definition at line 121 of file SBStringList.cpp.
References lldb_private::ConstString::GetCString(), IsValid(), LLDB_INSTRUMENT_VA, and m_opaque_up.
IsValid()
bool SBStringList::IsValid () const
Definition at line 55 of file SBStringList.cpp.
References LLDB_INSTRUMENT_VA.
Referenced by AppendList(), AppendList(), AppendList(), AppendString(), Clear(), GetSize(), GetStringAtIndex(), GetStringAtIndex(), operator->(), and ~SBStringList().
operator bool()
SBStringList::operator bool () const explicit
Definition at line 59 of file SBStringList.cpp.
References LLDB_INSTRUMENT_VA, and m_opaque_up.
operator*()
const lldb_private::StringList & SBStringList::operator* () const protected
Definition at line 51 of file SBStringList.cpp.
References m_opaque_up.
Referenced by SBStructuredData.
operator->() [1/2]
lldb_private::StringList * SBStringList::operator-> () protected
Definition at line 40 of file SBStringList.cpp.
References IsValid(), and m_opaque_up.
Referenced by SBStructuredData.
operator->() [2/2]
const lldb_private::StringList * SBStringList::operator-> () const protected
Definition at line 47 of file SBStringList.cpp.
References m_opaque_up.
operator=()
const SBStringList & SBStringList::operator= (const SBStringList & rhs)
Definition at line 30 of file SBStringList.cpp.
References lldb_private::clone(), LLDB_INSTRUMENT_VA, m_opaque_up, and SBStringList().
Friends And Related Symbol Documentation
SBBreakpoint
friend class SBBreakpoint friend
Definition at line 47 of file SBStringList.h.
References SBBreakpoint.
Referenced by SBBreakpoint.
SBBreakpointLocation
friend class SBBreakpointLocation friend
Definition at line 48 of file SBStringList.h.
References SBBreakpointLocation.
Referenced by SBBreakpointLocation.
SBBreakpointName
friend class SBBreakpointName friend
Definition at line 49 of file SBStringList.h.
References SBBreakpointName.
Referenced by SBBreakpointName.
SBCommandInterpreter
friend class SBCommandInterpreter friend
Definition at line 45 of file SBStringList.h.
References SBCommandInterpreter.
Referenced by SBCommandInterpreter.
SBDebugger
friend class SBDebugger friend
Definition at line 46 of file SBStringList.h.
References SBDebugger.
Referenced by SBDebugger.
SBStructuredData
friend class SBStructuredData friend
Definition at line 50 of file SBStringList.h.
References AppendList(), operator*(), operator->(), SBStringList(), and SBStructuredData.
Referenced by SBStructuredData.
Member Data Documentation
m_opaque_up
std::unique_ptr<lldb_private::StringList> lldb::SBStringList::m_opaque_up private
Definition at line 63 of file SBStringList.h.
Referenced by AppendList(), AppendList(), AppendList(), AppendString(), Clear(), GetSize(), GetStringAtIndex(), GetStringAtIndex(), operator bool(), operator*(), operator->(), operator->(), operator=(), SBStringList(), and SBStringList().
The documentation for this class was generated from the following files:
SBStringList.h
SBStringList.cpp