LLDB: lldb_private::ThreadPlanBase Class Reference
lldb_private::ThreadPlanBase Class Reference
#include <ThreadPlanBase.h>
Public Member Functions
~ThreadPlanBase () override
void GetDescription (Stream *s, lldb::DescriptionLevel level) override
Print a description of this thread to the stream s.
bool ValidatePlan (Stream *error) override
Returns whether this plan could be successfully created.
bool ShouldStop (Event *event_ptr) override
Vote ShouldReportStop (Event *event_ptr) override
bool StopOthers () override
lldb::StateType GetPlanRunState () override
bool WillStop () override
bool MischiefManaged () override
bool OkayToDiscard () override
bool IsBasePlan () override
lldb::RunDirection GetDirection () const override
Public Member Functions inherited from lldb_private::ThreadPlan
virtual ~ThreadPlan ()
const char * GetName () const
Returns the name of this thread plan.
Thread & GetThread ()
Returns the Thread that is using this thread plan.
Target & GetTarget ()
const Target & GetTarget () const
void ClearThreadCache ()
Clear the Thread* cache.
bool TracerExplainsStop ()
lldb::StateType RunState ()
bool PlanExplainsStop (Event *event_ptr)
virtual bool ShouldAutoContinue (Event *event_ptr)
Returns whether this thread plan overrides the ShouldStop of subsequently processed plans.
Vote ShouldReportRun (Event *event_ptr)
virtual void SetStopOthers (bool new_value)
virtual bool SupportsResumeOthers ()
virtual bool ShouldRunBeforePublicStop ()
bool WillResume (lldb::StateType resume_state, bool current_plan)
bool IsControllingPlan ()
virtual bool IsLeafPlan ()
bool SetIsControllingPlan (bool value)
void SetOkayToDiscard (bool value)
virtual void ThreadDestroyed ()
bool GetPrivate ()
void SetPrivate (bool input)
virtual void DidPush ()
virtual void DidPop ()
ThreadPlanKind GetKind () const
bool IsPlanComplete ()
void SetPlanComplete (bool success=true)
virtual bool IsPlanStale ()
bool PlanSucceeded ()
lldb::ThreadPlanTracerSP & GetThreadPlanTracer ()
void SetThreadPlanTracer (lldb::ThreadPlanTracerSP new_tracer_sp)
void DoTraceLog ()
virtual lldb::ValueObjectSP GetReturnValueObject ()
virtual lldb::ExpressionVariableSP GetExpressionVariable ()
virtual void RestoreThreadState ()
virtual bool IsVirtualStep ()
bool SetIterationCount (size_t count)
Public Member Functions inherited from lldb_private::UserID
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Protected Member Functions
bool DoWillResume (lldb::StateType resume_state, bool current_plan) override
bool DoPlanExplainsStop (Event *event_ptr) override
ThreadPlanBase (Thread &thread)
Protected Member Functions inherited from lldb_private::ThreadPlan
ThreadPlan (ThreadPlanKind kind, const char *name, Thread &thread, Vote report_stop_vote, Vote report_run_vote)
void PushPlan (lldb::ThreadPlanSP &thread_plan_sp)
ThreadPlan * GetPreviousPlan ()
lldb::StopInfoSP GetPrivateStopInfo ()
void SetStopInfo (lldb::StopInfoSP stop_reason_sp)
bool IsUsuallyUnexplainedStopReason (lldb::StopReason)
Private Member Functions
ThreadPlanBase (const ThreadPlanBase &)=delete
const ThreadPlanBase & operator= (const ThreadPlanBase &)=delete
Friends
class Process
lldb::ThreadPlanSP Thread::QueueBasePlan (bool abort_other_plans)
Additional Inherited Members
Public Types inherited from lldb_private::ThreadPlan
enum ThreadPlanKind {
eKindGeneric , eKindNull , eKindBase , eKindCallFunction ,
eKindPython , eKindStepInstruction , eKindStepOut , eKindStepOverBreakpoint ,
eKindStepOverRange , eKindStepInRange , eKindRunToAddress , eKindStepThrough ,
eKindStepUntil , eKindSingleThreadTimeout
}
Protected Attributes inherited from lldb_private::ThreadPlan
Status m_status
Process & m_process
lldb::tid_t m_tid
Vote m_report_stop_vote
Vote m_report_run_vote
bool m_takes_iteration_count
bool m_could_not_resolve_hw_bp
int32_t m_iteration_count = 1
Protected Attributes inherited from lldb_private::UserID
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Detailed Description
Definition at line 23 of file ThreadPlanBase.h.
Constructor & Destructor Documentation
~ThreadPlanBase()
ThreadPlanBase::~ThreadPlanBase () override default
References error().
ThreadPlanBase() [1/2]
ThreadPlanBase::ThreadPlanBase (Thread & thread) protected
Definition at line 30 of file ThreadPlanBase.cpp.
References lldb_private::ThreadPlan::eKindBase, lldb_private::eVoteNoOpinion, lldb_private::eVoteYes, lldb_private::ThreadPlan::m_thread, lldb_private::ThreadPlan::SetIsControllingPlan(), lldb_private::ThreadPlan::SetThreadPlanTracer(), and lldb_private::ThreadPlan::ThreadPlan().
Referenced by operator=(), and ThreadPlanBase().
ThreadPlanBase() [2/2]
lldb_private::ThreadPlanBase::ThreadPlanBase (const ThreadPlanBase &) private delete
References ThreadPlanBase().
Member Function Documentation
DoPlanExplainsStop()
bool ThreadPlanBase::DoPlanExplainsStop (Event * event_ptr) override protected virtual
Implements lldb_private::ThreadPlan.
Definition at line 55 of file ThreadPlanBase.cpp.
References lldb_private::ThreadPlan::TracerExplainsStop().
DoWillResume()
bool ThreadPlanBase::DoWillResume (lldb::StateType resume_state, bool current_plan) override protected virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 185 of file ThreadPlanBase.cpp.
References lldb_private::eVoteNo, lldb_private::eVoteNoOpinion, lldb_private::ThreadPlan::m_report_run_vote, and lldb_private::ThreadPlan::m_report_stop_vote.
GetDescription()
void ThreadPlanBase::GetDescription (Stream * s, lldb::DescriptionLevel level) override virtual
Print a description of this thread to the stream s.
thread. Don't expect that the result of GetThread is valid in the description method. This might get called when the underlying Thread has not been reported, so we only know the TID and not the thread.
Parameters
[in] s The stream to which to print the description.
[in] level The level of description desired. Note that eDescriptionLevelBrief will be used in the stop message printed when the plan is complete.
Implements lldb_private::ThreadPlan.
Definition at line 49 of file ThreadPlanBase.cpp.
References lldb_private::Stream::Printf().
GetDirection()
RunDirection ThreadPlanBase::GetDirection () const override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 200 of file ThreadPlanBase.cpp.
References lldb_private::ThreadPlan::m_process.
GetPlanRunState()
StateType ThreadPlanBase::GetPlanRunState () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 181 of file ThreadPlanBase.cpp.
References lldb::eStateRunning.
IsBasePlan()
bool lldb_private::ThreadPlanBase::IsBasePlan () inline override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 39 of file ThreadPlanBase.h.
MischiefManaged()
bool ThreadPlanBase::MischiefManaged () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 195 of file ThreadPlanBase.cpp.
OkayToDiscard()
bool lldb_private::ThreadPlanBase::OkayToDiscard () inline override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 37 of file ThreadPlanBase.h.
operator=()
const ThreadPlanBase & lldb_private::ThreadPlanBase::operator= (const ThreadPlanBase &) private delete
References ThreadPlanBase().
ShouldReportStop()
Vote ThreadPlanBase::ShouldReportStop (Event * event_ptr) override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 61 of file ThreadPlanBase.cpp.
References lldb_private::eVoteNoOpinion, lldb_private::eVoteYes, lldb_private::Thread::GetStopInfo(), and lldb_private::ThreadPlan::GetThread().
ShouldStop()
bool ThreadPlanBase::ShouldStop (Event * event_ptr) override virtual
Implements lldb_private::ThreadPlan.
Definition at line 73 of file ThreadPlanBase.cpp.
References lldb_private::Thread::DiscardThreadPlans(), lldb::eStopReasonBreakpoint, lldb::eStopReasonException, lldb::eStopReasonExec, lldb::eStopReasonInvalid, lldb::eStopReasonNone, lldb::eStopReasonSignal, lldb::eStopReasonThreadExiting, lldb::eStopReasonWatchpoint, lldb_private::eVoteNo, lldb_private::eVoteNoOpinion, lldb_private::eVoteYes, lldb_private::GetLog(), lldb_private::ThreadPlan::GetPrivateStopInfo(), lldb_private::ThreadPlan::GetThread(), LLDB_LOGF, lldb_private::ThreadPlan::m_report_run_vote, lldb_private::ThreadPlan::m_report_stop_vote, lldb_private::ThreadPlan::m_tid, and lldb_private::Step.
StopOthers()
bool ThreadPlanBase::StopOthers () override virtual
Reimplemented from lldb_private::ThreadPlan.
Definition at line 179 of file ThreadPlanBase.cpp.
ValidatePlan()
bool ThreadPlanBase::ValidatePlan (Stream * error) override virtual
Returns whether this plan could be successfully created.
Parameters
[in] error A stream to which to print some reason why the plan could not be created. Can be NULL.
Returns
true if the plan should be queued, false otherwise.
Implements lldb_private::ThreadPlan.
Definition at line 53 of file ThreadPlanBase.cpp.
References error().
WillStop()
bool ThreadPlanBase::WillStop () override virtual
Implements lldb_private::ThreadPlan.
Definition at line 183 of file ThreadPlanBase.cpp.
Friends And Related Symbol Documentation
Process
friend class Process friend
Definition at line 24 of file ThreadPlanBase.h.
References Process.
Referenced by Process.
Thread::QueueBasePlan
lldb::ThreadPlanSP Thread::QueueBasePlan (bool abort_other_plans) friend
The documentation for this class was generated from the following files:
ThreadPlanBase.h
ThreadPlanBase.cpp