LLDB: DeclContextOverride Class Reference
DeclContextOverride Class Reference
Classes
struct Backup
Public Member Functions
DeclContextOverride ()=default
void OverrideAllDeclsFromContainingFunction (clang::Decl *decl)
~DeclContextOverride ()
Private Member Functions
void OverrideOne (clang::Decl *decl)
bool ChainPassesThrough (clang::Decl *decl, clang::DeclContext *base, clang::DeclContext *(clang::Decl::*contextFromDecl)(), clang::DeclContext *(clang::DeclContext::*contextFromContext)())
clang::Decl * GetEscapedChild (clang::Decl *decl, clang::DeclContext *base=nullptr)
void Override (clang::Decl *decl)
Private Attributes
llvm::DenseMap< clang::Decl *, Backup > m_backups
Detailed Description
Definition at line 108 of file ClangASTImporter.cpp.
Constructor & Destructor Documentation
DeclContextOverride()
DeclContextOverride::DeclContextOverride () default
~DeclContextOverride()
DeclContextOverride::~DeclContextOverride () inline
Definition at line 211 of file ClangASTImporter.cpp.
References m_backups.
Member Function Documentation
ChainPassesThrough()
bool DeclContextOverride::ChainPassesThrough (clang::Decl * decl, clang::DeclContext * base, clang::DeclContext *(clang::Decl::* contextFromDecl)(), clang::DeclContext *(clang::DeclContext::* contextFromContext)()) inline private
Definition at line 134 of file ClangASTImporter.cpp.
Referenced by GetEscapedChild().
GetEscapedChild()
clang::Decl * DeclContextOverride::GetEscapedChild (clang::Decl * decl, clang::DeclContext * base = nullptr) inline private
Definition at line 148 of file ClangASTImporter.cpp.
References ChainPassesThrough(), and GetEscapedChild().
Referenced by GetEscapedChild(), and Override().
Override()
void DeclContextOverride::Override (clang::Decl * decl) inline private
Definition at line 179 of file ClangASTImporter.cpp.
References lldb_private::Expressions, GetEscapedChild(), lldb_private::GetLog(), LLDB_LOG, lldbassert, and OverrideOne().
Referenced by OverrideAllDeclsFromContainingFunction().
OverrideAllDeclsFromContainingFunction()
void DeclContextOverride::OverrideAllDeclsFromContainingFunction (clang::Decl * decl) inline
Definition at line 197 of file ClangASTImporter.cpp.
References Override().
Referenced by lldb_private::ClangASTImporter::DeportDecl(), and lldb_private::ClangASTImporter::DeportType().
OverrideOne()
void DeclContextOverride::OverrideOne (clang::Decl * decl) inline private
Definition at line 117 of file ClangASTImporter.cpp.
References m_backups.
Referenced by Override().
Member Data Documentation
m_backups
llvm::DenseMap<clang::Decl *, Backup> DeclContextOverride::m_backups private
Definition at line 115 of file ClangASTImporter.cpp.
Referenced by OverrideOne(), and ~DeclContextOverride().
The documentation for this class was generated from the following file:
ClangASTImporter.cpp