LLDB: lldb_private::ObjCLanguageRuntime::TaggedPointerVendor Class Reference
lldb_private::ObjCLanguageRuntime::TaggedPointerVendor Class Reference abstract
#include <ObjCLanguageRuntime.h>
Public Member Functions
virtual ~TaggedPointerVendor ()=default
virtual bool IsPossibleTaggedPointer (lldb::addr_t ptr)=0
virtual ObjCLanguageRuntime::ClassDescriptorSP GetClassDescriptor (lldb::addr_t ptr)=0
Protected Member Functions
TaggedPointerVendor ()=default
Private Member Functions
TaggedPointerVendor (const TaggedPointerVendor &)=delete
const TaggedPointerVendor & operator= (const TaggedPointerVendor &)=delete
Detailed Description
Definition at line 193 of file ObjCLanguageRuntime.h.
Constructor & Destructor Documentation
~TaggedPointerVendor()
virtual lldb_private::ObjCLanguageRuntime::TaggedPointerVendor::~TaggedPointerVendor () virtual default
TaggedPointerVendor() [1/2]
lldb_private::ObjCLanguageRuntime::TaggedPointerVendor::TaggedPointerVendor () protected default
Referenced by operator=(), TaggedPointerVendor(), and lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2::TaggedPointerVendorV2().
TaggedPointerVendor() [2/2]
lldb_private::ObjCLanguageRuntime::TaggedPointerVendor::TaggedPointerVendor (const TaggedPointerVendor &) private delete
References TaggedPointerVendor().
Member Function Documentation
GetClassDescriptor()
virtual ObjCLanguageRuntime::ClassDescriptorSP lldb_private::ObjCLanguageRuntime::TaggedPointerVendor::GetClassDescriptor (lldb::addr_t ptr) pure virtual
Implemented in lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorExtended, lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorLegacy, and lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted.
Referenced by CommandObjectMultiwordObjC_TaggedPointer_Info::DoExecute().
IsPossibleTaggedPointer()
virtual bool lldb_private::ObjCLanguageRuntime::TaggedPointerVendor::IsPossibleTaggedPointer (lldb::addr_t ptr) pure virtual
Implemented in lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorLegacy, and lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorRuntimeAssisted.
Referenced by CommandObjectMultiwordObjC_TaggedPointer_Info::DoExecute().
operator=()
const TaggedPointerVendor & lldb_private::ObjCLanguageRuntime::TaggedPointerVendor::operator= (const TaggedPointerVendor &) private delete
References TaggedPointerVendor().
The documentation for this class was generated from the following file:
ObjCLanguageRuntime.h