LLDB: lldb_private::python::PythonBytes Class Reference
lldb_private::python::PythonBytes Class Reference
#include <PythonDataObjects.h>
Public Member Functions
PythonBytes (llvm::ArrayRef< uint8_t > bytes)
PythonBytes (const uint8_t *bytes, size_t length)
llvm::ArrayRef< uint8_t > GetBytes () const
size_t GetSize () const
void SetBytes (llvm::ArrayRef< uint8_t > stringbytes)
StructuredData::StringSP CreateStructuredString () const
TypedPythonObject (PyRefType type, PyObject *py_obj)
TypedPythonObject ()=default
Public Member Functions inherited from lldb_private::python::TypedPythonObject< PythonBytes >
TypedPythonObject (PyRefType type, PyObject *py_obj)
Public Member Functions inherited from lldb_private::python::PythonObject
PythonObject ()=default
PythonObject (PyRefType type, PyObject *py_obj)
PythonObject (const PythonObject &rhs)
PythonObject (PythonObject &&rhs)
~PythonObject ()
void Reset ()
void Dump (Stream &strm) const
PyObject * get () const
PyObject * release ()
PythonObject & operator= (PythonObject other)
PyObjectType GetObjectType () const
PythonString Repr () const
PythonString Str () const
PythonObject ResolveName (llvm::StringRef name) const
template<typename T>
T ResolveName (llvm::StringRef name) const
bool HasAttribute (llvm::StringRef attribute) const
PythonObject GetAttributeValue (llvm::StringRef attribute) const
bool IsNone () const
bool IsValid () const
bool IsAllocated () const
operator bool () const
template<typename T>
T AsType () const
StructuredData::ObjectSP CreateStructuredObject () const
template<typename... T>
llvm::Expected< PythonObject > CallMethod (const char *name, const T &... t) const
template<typename... T>
llvm::Expected< PythonObject > Call (const T &... t) const
llvm::Expected< PythonObject > GetAttribute (const llvm::Twine &name) const
llvm::Expected< PythonObject > GetType () const
llvm::Expected< bool > IsTrue ()
llvm::Expected< long long > AsLongLong () const
llvm::Expected< unsigned long long > AsUnsignedLongLong () const
llvm::Expected< unsigned long long > AsModuloUnsignedLongLong () const
llvm::Expected< bool > IsInstance (const PythonObject &cls)
Static Public Member Functions
static bool Check (PyObject *py_obj)
Static Public Member Functions inherited from lldb_private::python::PythonObject
static PythonObject ResolveNameWithDictionary (llvm::StringRef name, const PythonDictionary &dict)
template<typename T>
static T ResolveNameWithDictionary (llvm::StringRef name, const PythonDictionary &dict)
Additional Inherited Members
Protected Attributes inherited from lldb_private::python::PythonObject
PyObject * m_py_obj = nullptr
Detailed Description
Definition at line 412 of file PythonDataObjects.h.
Constructor & Destructor Documentation
PythonBytes() [1/2]
PythonBytes::PythonBytes (llvm::ArrayRef< uint8_t > bytes) explicit
Definition at line 289 of file PythonDataObjects.cpp.
References SetBytes().
PythonBytes() [2/2]
PythonBytes::PythonBytes (const uint8_t * bytes, size_t length)
Definition at line 291 of file PythonDataObjects.cpp.
References SetBytes().
Member Function Documentation
Check()
bool PythonBytes::Check (PyObject * py_obj) static
Definition at line 295 of file PythonDataObjects.cpp.
Referenced by lldb_private::python::PythonObject::GetObjectType().
CreateStructuredString()
StructuredData::StringSP PythonBytes::CreateStructuredString () const
Definition at line 323 of file PythonDataObjects.cpp.
References lldb_private::python::PythonObject::m_py_obj.
Referenced by lldb_private::python::PythonObject::CreateStructuredObject().
GetBytes()
llvm::ArrayRef< uint8_t > PythonBytes::GetBytes () const
Definition at line 301 of file PythonDataObjects.cpp.
References lldb_private::python::PythonObject::IsValid(), and lldb_private::python::PythonObject::m_py_obj.
GetSize()
size_t PythonBytes::GetSize () const
Definition at line 312 of file PythonDataObjects.cpp.
References lldb_private::python::PythonObject::IsValid(), and lldb_private::python::PythonObject::m_py_obj.
SetBytes()
void PythonBytes::SetBytes (llvm::ArrayRef< uint8_t > stringbytes)
Definition at line 318 of file PythonDataObjects.cpp.
References lldb_private::python::Take().
Referenced by PythonBytes(), and PythonBytes().
TypedPythonObject() [1/2]
lldb_private::python::TypedPythonObject< T >::TypedPythonObject () default
TypedPythonObject() [2/2]
lldb_private::python::TypedPythonObject< T >::TypedPythonObject (PyRefType type, PyObject * py_obj) inline
Definition at line 400 of file PythonDataObjects.h.
The documentation for this class was generated from the following files:
PythonDataObjects.h
PythonDataObjects.cpp