LLDB: Cocoa.cpp File Reference
Cocoa.cpp File Reference
#include "Cocoa.h"
#include "NSString.h"
#include "ObjCConstants.h"
#include "Plugins/LanguageRuntime/ObjC/AppleObjCRuntime/AppleObjCRuntime.h"
#include "Plugins/TypeSystem/Clang/TypeSystemClang.h"
#include "lldb/Core/Mangled.h"
#include "lldb/DataFormatters/FormattersHelpers.h"
#include "lldb/DataFormatters/StringPrinter.h"
#include "lldb/DataFormatters/TypeSummary.h"
#include "lldb/Host/Time.h"
#include "lldb/Target/Language.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/Endian.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/Stream.h"
#include "lldb/ValueObject/ValueObject.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/bit.h"
Classes
struct DoubleBits
struct TaggedDoubleBits
class ObjCClassSyntheticChildrenFrontEnd
Functions
static void NSNumber_FormatChar (ValueObject &valobj, Stream &stream, char value, lldb::LanguageType lang)
static void NSNumber_FormatShort (ValueObject &valobj, Stream &stream, short value, lldb::LanguageType lang)
static void NSNumber_FormatInt (ValueObject &valobj, Stream &stream, int value, lldb::LanguageType lang)
static void NSNumber_FormatLong (ValueObject &valobj, Stream &stream, int64_t value, lldb::LanguageType lang)
static void NSNumber_FormatInt128 (ValueObject &valobj, Stream &stream, const llvm::APInt &value, lldb::LanguageType lang)
static void NSNumber_FormatFloat (ValueObject &valobj, Stream &stream, float value, lldb::LanguageType lang)
static void NSNumber_FormatDouble (ValueObject &valobj, Stream &stream, double value, lldb::LanguageType lang)
static uint64_t decodeExponent (uint64_t exp)
static double decodeTaggedTimeInterval (uint64_t encodedTimeInterval)
Variables
const int TAGGED_DATE_EXPONENT_BIAS = 0x3ef
Bias value for tagged pointer exponents.
Function Documentation
decodeExponent()
uint64_t decodeExponent (uint64_t exp) static
Definition at line 876 of file Cocoa.cpp.
References TAGGED_DATE_EXPONENT_BIAS.
Referenced by decodeTaggedTimeInterval().
decodeTaggedTimeInterval()
double decodeTaggedTimeInterval (uint64_t encodedTimeInterval) static
Definition at line 882 of file Cocoa.cpp.
References decodeExponent(), DoubleBits::exponent, TaggedDoubleBits::exponent, DoubleBits::fraction, TaggedDoubleBits::fraction, DoubleBits::sign, TaggedDoubleBits::sign, and TaggedDoubleBits::unused.
Referenced by lldb_private::formatters::NSDateSummaryProvider().
NSNumber_FormatChar()
void NSNumber_FormatChar (ValueObject & valobj, Stream & stream, char value, lldb::LanguageType lang) static
Definition at line 341 of file Cocoa.cpp.
References lldb_private::Language::FindPlugin(), and lldb_private::Stream::Printf().
Referenced by lldb_private::formatters::NSNumberSummaryProvider().
NSNumber_FormatDouble()
void NSNumber_FormatDouble (ValueObject & valobj, Stream & stream, double value, lldb::LanguageType lang) static
Definition at line 423 of file Cocoa.cpp.
References lldb_private::Language::FindPlugin(), and lldb_private::Stream::Printf().
Referenced by lldb_private::formatters::NSNumberSummaryProvider().
NSNumber_FormatFloat()
void NSNumber_FormatFloat (ValueObject & valobj, Stream & stream, float value, lldb::LanguageType lang) static
Definition at line 410 of file Cocoa.cpp.
References lldb_private::Language::FindPlugin(), and lldb_private::Stream::Printf().
Referenced by lldb_private::formatters::NSNumberSummaryProvider().
NSNumber_FormatInt()
void NSNumber_FormatInt (ValueObject & valobj, Stream & stream, int value, lldb::LanguageType lang) static
Definition at line 367 of file Cocoa.cpp.
References lldb_private::Language::FindPlugin(), and lldb_private::Stream::Printf().
Referenced by lldb_private::formatters::NSNumberSummaryProvider().
NSNumber_FormatInt128()
void NSNumber_FormatInt128 (ValueObject & valobj, Stream & stream, const llvm::APInt & value, lldb::LanguageType lang) static
Definition at line 393 of file Cocoa.cpp.
References lldb_private::Language::FindPlugin(), and lldb_private::Stream::PutCString().
Referenced by lldb_private::formatters::NSNumberSummaryProvider().
NSNumber_FormatLong()
void NSNumber_FormatLong (ValueObject & valobj, Stream & stream, int64_t value, lldb::LanguageType lang) static
Definition at line 380 of file Cocoa.cpp.
References lldb_private::Language::FindPlugin(), and lldb_private::Stream::Printf().
Referenced by lldb_private::formatters::NSNumberSummaryProvider().
NSNumber_FormatShort()
void NSNumber_FormatShort (ValueObject & valobj, Stream & stream, short value, lldb::LanguageType lang) static
Definition at line 354 of file Cocoa.cpp.
References lldb_private::Language::FindPlugin(), and lldb_private::Stream::Printf().
Referenced by lldb_private::formatters::NSNumberSummaryProvider().
Variable Documentation
TAGGED_DATE_EXPONENT_BIAS
const int TAGGED_DATE_EXPONENT_BIAS = 0x3ef
Bias value for tagged pointer exponents.
Recommended values: 0x3e3: encodes all dates between distantPast and distantFuture except for the range within about 1e-28 second of the reference date. 0x3ef: encodes all dates for a few million years beyond distantPast and distantFuture, except within about 1e-25 second of the reference date.
Definition at line 861 of file Cocoa.cpp.
Referenced by decodeExponent().