LLDB: Host.cpp File Reference
Host.cpp File Reference
#include <cerrno>
#include <climits>
#include <cstdlib>
#include <sys/types.h>
#include <dlfcn.h>
#include <grp.h>
#include <netdb.h>
#include <pwd.h>
#include <spawn.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>
#include <csignal>
#include "lldb/Host/FileAction.h"
#include "lldb/Host/FileSystem.h"
#include "lldb/Host/Host.h"
#include "lldb/Host/HostInfo.h"
#include "lldb/Host/HostProcess.h"
#include "lldb/Host/MonitoringProcessLauncher.h"
#include "lldb/Host/ProcessLaunchInfo.h"
#include "lldb/Host/ProcessLauncher.h"
#include "lldb/Host/ThreadLauncher.h"
#include "lldb/Host/posix/ConnectionFileDescriptorPosix.h"
#include "lldb/Utility/FileSpec.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/Predicate.h"
#include "lldb/Utility/Status.h"
#include "lldb/lldb-private-forward.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/Errno.h"
#include "llvm/Support/FileSystem.h"
#include "lldb/Host/posix/ProcessLauncherPosixFork.h"
Classes
class ScopedPThreadCancelDisabler
struct ShellInfo
Functions
static thread_result_t MonitorChildProcessThreadFunction (::pid_t pid, Host::MonitorChildProcessCallback callback)
static bool CheckForMonitorCancellation ()
static void MonitorShellCommand (std::shared_ptr< ShellInfo > shell_info, lldb::pid_t pid, int signo, int status)
Variables
static constexpr Log::Category g_categories []
static Log::Channel g_system_channel (g_categories, SystemLog::System)
static Log g_system_log (g_system_channel)
char ** environ
Function Documentation
CheckForMonitorCancellation()
bool CheckForMonitorCancellation () static
Definition at line 160 of file common/Host.cpp.
Referenced by MonitorChildProcessThreadFunction().
MonitorChildProcessThreadFunction()
thread_result_t MonitorChildProcessThreadFunction (::pid_t pid, Host::MonitorChildProcessCallback callback) static
Definition at line 173 of file common/Host.cpp.
References CheckForMonitorCancellation(), lldb_private::GetLog(), LLDB_LOG, and lldb_private::Process.
Referenced by lldb_private::Host::StartMonitoringChildProcess().
MonitorShellCommand()
void MonitorShellCommand (std::shared_ptr< ShellInfo > shell_info, lldb::pid_t pid, int signo, int status) static
Definition at line 377 of file common/Host.cpp.
References lldb_private::eBroadcastAlways.
Referenced by lldb_private::Host::RunShellCommand().
Variable Documentation
environ
char** environ
Definition at line 111 of file common/Host.cpp.
Referenced by lldb_private::Host::GetEnvironment().
g_categories
Log::Category g_categories[] static constexpr
Initial value:
= {
    {{"system"}, {"system log"}, SystemLog::System}}
Definition at line 94 of file common/Host.cpp.
Referenced by lldb_private::Timer::Category::Category(), lldb_private::Timer::DumpCategoryTimes(), and lldb_private::Timer::ResetCategoryTimes().
g_system_channel
Log::Channel g_system_channel(g_categories, SystemLog::System) (g_categories , SystemLog::System) static
Referenced by lldb_private::LogChannelFor< SystemLog >().
g_system_log
Log g_system_log(g_system_channel) (g_system_channel) static
Referenced by lldb_private::LogChannelSystem::Initialize(), and lldb_private::LogChannelSystem::Terminate().