LLDB: CommandObjectPlugin.cpp File Reference
CommandObjectPlugin.cpp File Reference
#include "CommandObjectPlugin.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Host/OptionParser.h"
#include "lldb/Interpreter/CommandInterpreter.h"
#include "lldb/Interpreter/CommandReturnObject.h"
#include "CommandOptions.inc"
Classes
class CommandObjectPluginLoad
class CommandObjectPluginList
class CommandObjectPluginEnable
class CommandObjectPluginDisable
Macros
#define LLDB_OPTIONS_plugin_list
Functions
static void DoPluginEnableDisable (Args &command, CommandReturnObject &result, bool enable)
Macro Definition Documentation
LLDB_OPTIONS_plugin_list
#define LLDB_OPTIONS_plugin_list
Definition at line 114 of file CommandObjectPlugin.cpp.
Function Documentation
DoPluginEnableDisable()
void DoPluginEnableDisable (Args & command, CommandReturnObject & result, bool enable) static
Definition at line 272 of file CommandObjectPlugin.cpp.
References lldb_private::CommandReturnObject::AppendErrorWithFormat(), lldb::eReturnStatusSuccessFinishResult, lldb_private::Args::GetArgumentCount(), and lldb_private::CommandReturnObject::SetStatus().
Referenced by CommandObjectPluginDisable::DoExecute(), and CommandObjectPluginEnable::DoExecute().