LLDB: CommandReturnObject.cpp File Reference
CommandReturnObject.cpp File Reference
#include "lldb/Interpreter/CommandReturnObject.h"
#include "lldb/Host/common/DiagnosticsRendering.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/StreamString.h"
Functions
static llvm::raw_ostream & error (Stream &strm)
static llvm::raw_ostream & warning (Stream &strm)
static llvm::raw_ostream & note (Stream &strm)
static void DumpStringToStreamWithNewline (Stream &strm, const std::string &s)
Function Documentation
DumpStringToStreamWithNewline()
void DumpStringToStreamWithNewline (Stream & strm, const std::string & s) static
Definition at line 36 of file CommandReturnObject.cpp.
References lldb_private::Stream::EOL(), and lldb_private::Stream::Write().
Referenced by lldb_private::CommandReturnObject::AppendErrorWithFormat().
error()
llvm::raw_ostream & error (Stream & strm) static
Definition at line 18 of file CommandReturnObject.cpp.
References lldb_private::Stream::AsRawOstream().
Referenced by lldb::SBCommandReturnObject::__attribute__(), lldb_private::formatters::Foundation1437::__NSArrayMSize(), lldb_private::formatters::Foundation1437::__NSArrayMSize_Impl(), lldb_private::formatters::Foundation1437::__NSDictionaryMSize(), lldb_private::formatters::Foundation1437::__NSDictionaryMSize_Impl(), lldb_private::formatters::Foundation1436::__NSFrozenArrayMSize(), lldb_private::formatters::Foundation1437::__NSSetMSize(), lldb_private::formatters::Foundation1437::__NSSetMSize_Impl(), lldb_private::DomainSocket::Accept(), lldb_private::TCPSocket::Accept(), lldb_private::mcp::ProtocolServerMCP::AcceptCallback(), lldb_private::ConnectionFileDescriptor::AcceptSocket(), lldb_private::Socket::AcceptSocket(), MinidumpFileBuilder::AddDirectory(), MinidumpFileBuilder::AddExceptions(), CommandObjectTypeFilterAdd::AddFilter(), MinidumpFileBuilder::AddHeaderAndCalculateDirectories(), MinidumpFileBuilder::AddLinuxFileStreams(), MinidumpFileBuilder::AddLLDBGeneratedStream(), lldb::SBBreakpoint::AddLocation(), lldb_private::BreakpointLocationList::AddLocation(), MinidumpFileBuilder::AddMemoryList(), MinidumpFileBuilder::AddMemoryList_32(), MinidumpFileBuilder::AddMemoryList_64(), MinidumpFileBuilder::AddMiscInfo(), lldb::SBTarget::AddModule(), MinidumpFileBuilder::AddModuleList(), CommandObjectTargetSymbolsAdd::AddModuleSymbols(), lldb_private::Target::AddNameToBreakpoint(), lldb_private::Target::AddNameToBreakpoint(), lldb::SBBreakpoint::AddNameWithErrorHandling(), AddPosixSpawnFileAction(), lldb::SBValue::AddressOf(), lldb_private::ValueObject::AddressOf(), lldb_private::ValueObjectConstResult::AddressOf(), lldb_private::ValueObjectConstResultCast::AddressOf(), lldb_private::ValueObjectConstResultChild::AddressOf(), lldb_private::ValueObjectConstResultImpl::AddressOf(), MinidumpFileBuilder::AddSystemInfo(), lldb_private::SaveCoreOptions::AddThread(), MinidumpFileBuilder::AddThreadList(), lldb_private::AllocatedMemoryCache::AllocateMemory(), lldb_private::Process::AllocateMemory(), lldb_private::ProcessDebugger::AllocateMemory(), lldb_private::AllocatedMemoryCache::AllocatePage(), lldb_private::Value::AppendDataToHostBuffer(), lldb_private::CommandReturnObject::AppendError(), lldb_private::trace_intel_pt::DecodedThread::AppendError(), lldb_private::CommandReturnObject::AppendErrorWithFormat(), lldb::SBTarget::AppendImageSearchPath(), lldb_private::Disassembler::AppendInstructions(), CommandObjectCommandsAddRegex::AppendRegexSubstitution(), lldb_private::OptionValueString::AppendToCurrentValue(), lldb_private::ScriptedFrameProviderPythonInterface::AppliesToThread(), lldb::SBPlatform::Attach(), lldb::SBTarget::Attach(), lldb_private::Platform::Attach(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::Attach(), lldb_private::PlatformWindows::Attach(), lldb_private::Process::Attach(), lldb_private::Target::Attach(), PlatformPOSIX::Attach(), lldb_private::ProcessDebugger::AttachProcess(), lldb::SBTarget::AttachToProcessWithID(), lldb::SBTarget::AttachToProcessWithName(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::AttachWaitProcess(), UnwindAssembly_x86::AugmentUnwindPlanFromCallSite(), SystemRuntimeMacOSX::BacktraceRecordingHeadersInitialized(), lldb_private::dil::DILParser::BailOut(), lldb_private::transport::Binder< Proto >::Bind(), CoreSimulatorSupport::Device::Boot(), lldb::SBTarget::BreakpointCreateFromScript(), lldb_private::BreakpointResolverName::BreakpointResolverName(), lldb_private::npdb::SymbolFileNativePDB::BuildParentMap(), lldb_private::ConnectionFileDescriptor::BytesAvailable(), lldb_private::NativeProcessWindows::CacheLoadedModules(), lldb_private::plugin::dwarf::SymbolFileDWARF::CalculateAbilities(), SymbolFilePDB::CalculateAbilities(), lldb_private::BytecodeSyntheticChildren::FrontEnd::CalculateNumChildren(), lldb_private::ScriptedThread::CalculateStopInfo(), lldb_private::Platform::CallLocateModuleCallbackIfSet(), lldb_private::Process::CallocateMemory(), lldb_private::ScriptedPythonInterface::CallStaticMethod(), lldb_private::HostThreadPosix::Cancel(), lldb_private::HostThreadWindows::Cancel(), ProcessElfCore::CanDebug(), ProcessMachCore::CanDebug(), IRInterpreter::CanInterpret(), DynamicLoaderDarwinKernel::CanLoadImage(), DynamicLoaderMacOS::CanLoadImage(), DynamicLoaderMacOSXDYLD::CanLoadImage(), lldb_private::ValueObject::Cast(), lldb_private::ValueObject::CastBaseToDerivedType(), lldb_private::formatters::CFBagSummaryProvider(), lldb_private::formatters::CFBinaryHeapSummaryProvider(), lldb_private::formatters::CFBitVectorSummaryProvider(), CharSummaryProvider(), ProcessMachCore::CheckAddressForDyldOrKernel(), CheckIfWatchpointsSupported(), CheckPsbPeriod(), lldb_private::ScriptedInterface::CheckStructuredDataObject(), lldb_private::Lua::CheckSyntax(), lldb_private::BreakpointLocationList::ClearAllBreakpointSites(), lldb_private::NativeRegisterContextDBReg::ClearAllHardwareBreakpoints(), lldb_private::NativeRegisterContextDBReg::ClearAllHardwareWatchpoints(), lldb_private::NativeRegisterContextDBReg_x86::ClearAllHardwareWatchpoints(), lldb_private::Process::ClearBreakpointSiteByID(), lldb_private::NativeRegisterContextDBReg::ClearHardwareBreakpoint(), lldb_private::NativeRegisterContextDBReg::ClearHardwareWatchpoint(), lldb_private::NativeRegisterContextDBReg_x86::ClearHardwareWatchpoint(), lldb_private::NativeRegisterContextDBReg_x86::ClearWatchpointHit(), CloneError(), lldb::SBFile::Close(), lldb_private::NativeFile::Close(), lldb_private::Socket::Close(), lldb_private::FileCache::CloseFile(), lldb_private::Platform::CloseFile(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::CloseFile(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::CloseFile(), lldb_private::RemoteAwarePlatform::CloseFile(), lldb_private::CommandAlias::CommandAlias(), CommandObjectTypeCategoryEnable::CommandOptions::CommandOptions(), CommandObjectTypeFilterAdd::CommandOptions::CommandOptions(), lldb_private::IRExecutionUnit::CommitOneAllocation(), CompleteLineEntry(), lldb_private::CommandCompletions::CompleteModifiableCmdPathArgs(), SystemRuntimeMacOSX::CompleteQueueItem(), lldb_private::npdb::PdbAstBuilderClang::CompleteTagDecl(), lldb_private::BreakpointLocation::ConditionSaysStop(), lldb_private::ObjCLanguageRuntime::ObjCExceptionPrecondition::ConfigurePrecondition(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ConfigureRemoteStructuredData(), lldb_private::DomainSocket::Connect(), lldb_private::TCPSocket::Connect(), lldb_private::Platform::ConnectProcess(), lldb_private::platform_android::PlatformAndroidRemoteGDBServer::ConnectProcess(), lldb_private::RemoteAwarePlatform::ConnectProcess(), lldb_private::Platform::ConnectProcessSynchronous(), lldb::SBTarget::ConnectRemote(), lldb_private::Platform::ConnectRemote(), lldb_private::platform_android::PlatformAndroid::ConnectRemote(), lldb_private::platform_android::PlatformAndroidRemoteGDBServer::ConnectRemote(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::ConnectRemote(), lldb_private::PlatformAppleSimulator::ConnectRemote(), lldb_private::PlatformWindows::ConnectRemote(), lldb_private::Process::ConnectRemote(), PlatformPOSIX::ConnectRemote(), lldb_private::ConnectionFileDescriptor::ConnectSocket(), ConnectToAdb(), lldb_private::process_gdb_remote::ProcessGDBRemote::ConnectToDebugserver(), lldb_private::Platform::ConnectToWaitingProcesses(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::ConnectToWaitingProcesses(), lldb_private::RemoteAwarePlatform::ConnectToWaitingProcesses(), lldb_private::ThreadPlanCallFunction::ConstructorSetup(), lldb_private::ProcessLaunchInfo::ConvertArgumentsForLaunchingInShell(), lldb_private::CppModuleConfiguration::CppModuleConfiguration(), lldb_private::dil::DILLexer::Create(), lldb_private::OptionValueUInt64::Create(), lldb_private::SerialPort::Create(), lldb_private::Socket::Create(), lldb_private::ValueObjectConstResult::Create(), PluginInfo::Create(), lldb_private::ScriptedProcessInterface::CreateBreakpoint(), lldb_private::ScriptedProcessPythonInterface::CreateBreakpoint(), lldb_private::Target::CreateBreakpoint(), lldb_private::Target::CreateBreakpointAtUserEntry(), lldb_private::Target::CreateBreakpointsFromFile(), lldb_private::Process::CreateBreakpointSite(), lldb_private::UDPSocket::CreateConnected(), lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::CreateEmptyProcess(), lldb_private::Target::CreateExceptionBreakpoint(), lldb_private::Breakpoint::CreateFromStructuredData(), lldb_private::BreakpointOptions::CommandData::CreateFromStructuredData(), lldb_private::BreakpointOptions::CreateFromStructuredData(), lldb_private::BreakpointResolver::CreateFromStructuredData(), lldb_private::BreakpointResolverAddress::CreateFromStructuredData(), lldb_private::BreakpointResolverFileLine::CreateFromStructuredData(), lldb_private::BreakpointResolverFileRegex::CreateFromStructuredData(), lldb_private::BreakpointResolverName::CreateFromStructuredData(), lldb_private::BreakpointResolverScripted::CreateFromStructuredData(), lldb_private::ExceptionSearchFilter::CreateFromStructuredData(), lldb_private::SearchFilter::CreateFromStructuredData(), lldb_private::SearchFilterByModule::CreateFromStructuredData(), lldb_private::SearchFilterByModuleList::CreateFromStructuredData(), lldb_private::SearchFilterByModuleListAndCU::CreateFromStructuredData(), lldb_private::SearchFilterForUnconstrainedSearches::CreateFromStructuredData(), lldb_private::ThreadSpec::CreateFromStructuredData(), lldb_private::npdb::PdbAstBuilderClang::CreateFunctionDecl(), lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorV2::CreateInstance(), lldb_private::ClangREPL::CreateInstance(), lldb_private::ScriptedProcess::CreateInstance(), lldb_private::PipePosix::CreateNew(), lldb_private::PipePosix::CreateNew(), lldb::SBTrace::CreateNewCursor(), sddarwinlog_private::ExactMatchFilterRule::CreateOperation(), sddarwinlog_private::RegexFilterRule::CreateOperation(), lldb_private::TCPSocket::CreatePair(), lldb_private::OptionGroupPlatform::CreatePlatformWithOptions(), lldb_private::ScriptedPythonInterface::CreatePluginObject(), lldb::SBFrame::CreateProcessIsRunningExprEvalError(), lldb_private::ScriptedThread::CreateRegisterContextForFrame(), sddarwinlog_private::FilterRule::CreateRule(), lldb_private::Socket::CreateSocket(), lldb_private::TCPSocket::CreateSocket(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::CreateSymlink(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::CreateSymlink(), lldb_private::ValueObjectSynthetic::CreateSynthFilter(), lldb::SBDebugger::CreateTarget(), lldb::SBDebugger::CreateTargetWithFileAndArch(), lldb::SBDebugger::CreateTargetWithFileAndTargetTriple(), lldb_private::OperatingSystemPythonInterface::CreateThread(), lldb::SBTarget::CreateTrace(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_i386(), lldb_private::CompactUnwindInfo::CreateUnwindPlan_x86_64(), lldb_private::OptionValue::CreateValueFromCStringForTypeMask(), lldb_private::Target::CreateWatchpoint(), lldb_private::PipePosix::CreateWithUniqueName(), lldb_private::PipeWindows::CreateWithUniqueName(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::DataAvailableCallback(), lldb::SBProcess::DeallocateMemory(), lldb_private::Process::DeallocateMemory(), lldb_private::plugin::dwarf::SymbolFileDWARF::DebugAbbrev(), lldb_private::DebuggerThread::DebuggerThreadAttachRoutine(), lldb_private::DebuggerThread::DebuggerThreadLaunchRoutine(), lldb_private::Platform::DebugProcess(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::DebugProcess(), lldb_private::PlatformAppleSimulator::DebugProcess(), lldb_private::PlatformDarwin::DebugProcess(), lldb_private::PlatformQemuUser::DebugProcess(), lldb_private::PlatformWasm::DebugProcess(), lldb_private::PlatformWindows::DebugProcess(), PlatformPOSIX::DebugProcess(), lldb_private::trace_intel_pt::TraceIntelPT::Decode(), MinidumpFileBuilder::DeleteFile(), lldb_private::platform_android::PlatformAndroidRemoteGDBServer::DeleteForwardPort(), lldb_private::platform_android::AdbClient::DeletePortForwarding(), EntityResultVariable::Dematerialize(), lldb_private::Materializer::Dematerializer::Dematerialize(), lldb::SBValue::Dereference(), lldb_private::ValueObject::Dereference(), lldb_private::ValueObjectConstResult::Dereference(), lldb_private::ValueObjectConstResultCast::Dereference(), lldb_private::ValueObjectConstResultChild::Dereference(), lldb_private::ValueObjectConstResultImpl::Dereference(), DereferenceValueOrAlternate(), DerefToNSErrorPointer(), lldb_private::Process::DestroyImpl(), lldb_private::ProcessDebugger::DestroyProcess(), lldb_private::NativeProcessWindows::Detach(), lldb_private::Process::Detach(), lldb_private::process_freebsd::NativeProcessFreeBSD::Detach(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::Detach(), lldb_private::process_linux::NativeProcessLinux::Detach(), lldb_private::process_netbsd::NativeProcessNetBSD::Detach(), lldb_private::ProcessDebugger::DetachProcess(), lldb_private::DynamicLoaderWindowsDYLD::DidAttach(), lldb_private::wasm::DynamicLoaderWasmDYLD::DidAttach(), lldb_private::process_gdb_remote::ProcessGDBRemote::DidFork(), lldb_private::DynamicLoaderWindowsDYLD::DidLaunch(), lldb_private::process_gdb_remote::ProcessGDBRemote::DidVFork(), lldb_private::StackFrame::DILGetValueForVariableExpressionPath(), lldb_private::dil::DILParser::DILParser(), lldb_private::process_gdb_remote::ProcessGDBRemote::DisableBreakpointSite(), lldb_private::ProcessWindows::DisableBreakpointSite(), ProcessKDP::DisableBreakpointSite(), lldb_private::Process::DisableBreakpointSiteByID(), lldb_private::Process::DisableSoftwareBreakpoint(), lldb_private::Process::DisableWatchpoint(), lldb_private::process_gdb_remote::ProcessGDBRemote::DisableWatchpoint(), lldb_private::ProcessWindows::DisableWatchpoint(), lldb_private::ConnectionFileDescriptor::Disconnect(), lldb_private::Platform::DisconnectRemote(), lldb_private::platform_android::PlatformAndroid::DisconnectRemote(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::DisconnectRemote(), lldb_private::PlatformWindows::DisconnectRemote(), PlatformPOSIX::DisconnectRemote(), DiskFilesOrDirectories(), lldb_private::ScriptedPythonInterface::Dispatch(), lldb_private::Process::DoAllocateMemory(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoAllocateMemory(), lldb_private::ProcessWindows::DoAllocateMemory(), ProcessKDP::DoAllocateMemory(), lldb_private::ScriptedProcess::DoAttach(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoAttachToProcessWithID(), lldb_private::ProcessWindows::DoAttachToProcessWithID(), ProcessKDP::DoAttachToProcessWithID(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoAttachToProcessWithName(), ProcessKDP::DoAttachToProcessWithName(), lldb_private::Platform::DoConnectProcess(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoConnectRemote(), ProcessKDP::DoConnectRemote(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoDeallocateMemory(), ProcessKDP::DoDeallocateMemory(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoDetach(), lldb_private::ProcessWindows::DoDetach(), ProcessKDP::DoDetach(), lldb_private::OperatingSystemPythonInterface::DoesPluginReportAllThreads(), CommandObjectBreakpointAddAddress::DoExecute(), CommandObjectBreakpointAddFile::DoExecute(), CommandObjectBreakpointAddScripted::DoExecute(), CommandObjectBreakpointDelete::DoExecute(), CommandObjectBreakpointEnable::DoExecute(), CommandObjectBreakpointNameAdd::DoExecute(), CommandObjectBreakpointNameConfigure::DoExecute(), CommandObjectBreakpointNameList::DoExecute(), CommandObjectBreakpointRead::DoExecute(), CommandObjectBreakpointSet::DoExecute(), CommandObjectBreakpointWrite::DoExecute(), CommandObjectCommandsAddRegex::DoExecute(), CommandObjectCommandsScriptDelete::DoExecute(), CommandObjectCommandsScriptImport::DoExecute(), CommandObjectDiagnosticsDump::DoExecute(), CommandObjectFrameDiagnose::DoExecute(), CommandObjectLogDisable::DoExecute(), CommandObjectLogDump::DoExecute(), CommandObjectLogEnable::DoExecute(), CommandObjectMemoryFind::DoExecute(), CommandObjectMemoryHistory::DoExecute(), CommandObjectMemoryRead::DoExecute(), CommandObjectMemoryRegion::DoExecute(), CommandObjectMemoryTagRead::DoExecute(), CommandObjectMemoryTagWrite::DoExecute(), CommandObjectMemoryWrite::DoExecute(), CommandObjectMultiwordObjC_TaggedPointer_Info::DoExecute(), CommandObjectPlatformConnect::DoExecute(), CommandObjectPlatformDisconnect::DoExecute(), CommandObjectPlatformFClose::DoExecute(), CommandObjectPlatformFOpen::DoExecute(), CommandObjectPlatformFRead::DoExecute(), CommandObjectPlatformFWrite::DoExecute(), CommandObjectPlatformInstall::DoExecute(), CommandObjectPlatformMkDir::DoExecute(), CommandObjectPlatformProcessInfo::DoExecute(), CommandObjectPlatformProcessLaunch::DoExecute(), CommandObjectPlatformSelect::DoExecute(), CommandObjectPlatformShell::DoExecute(), CommandObjectPluginLoad::DoExecute(), CommandObjectProcessAttach::DoExecute(), CommandObjectProcessConnect::DoExecute(), CommandObjectProcessContinue::DoExecute(), CommandObjectProcessDetach::DoExecute(), CommandObjectProcessInterrupt::DoExecute(), CommandObjectProcessKDPPacketSend::DoExecute(), CommandObjectProcessKill::DoExecute(), CommandObjectProcessLaunch::DoExecute(), CommandObjectProcessLoad::DoExecute(), CommandObjectProcessSaveCore::DoExecute(), CommandObjectProcessSignal::DoExecute(), CommandObjectProcessUnload::DoExecute(), CommandObjectProtocolServerStart::DoExecute(), CommandObjectProtocolServerStop::DoExecute(), CommandObjectPythonFunction::DoExecute(), CommandObjectRegisterWrite::DoExecute(), CommandObjectScriptingObjectParsed::DoExecute(), CommandObjectScriptingObjectRaw::DoExecute(), CommandObjectSettingsAppend::DoExecute(), CommandObjectSettingsClear::DoExecute(), CommandObjectSettingsInsertAfter::DoExecute(), CommandObjectSettingsInsertBefore::DoExecute(), CommandObjectSettingsRemove::DoExecute(), CommandObjectSettingsReplace::DoExecute(), CommandObjectSettingsSet::DoExecute(), CommandObjectSettingsShow::DoExecute(), CommandObjectSettingsWrite::DoExecute(), CommandObjectTargetCreate::DoExecute(), CommandObjectTargetModulesAdd::DoExecute(), CommandObjectTargetModulesLoad::DoExecute(), CommandObjectTargetVariable::DoExecute(), CommandObjectThreadContinue::DoExecute(), CommandObjectThreadReturn::DoExecute(), CommandObjectThreadStepWithTypeAndScope::DoExecute(), CommandObjectThreadUntil::DoExecute(), CommandObjectTraceDump::DoExecute(), CommandObjectTraceSchema::DoExecute(), CommandObjectTypeLookup::DoExecute(), CommandObjectWatchpointCommandAdd::DoExecute(), lldb_private::CommandObjectDWIMPrint::DoExecute(), sddarwinlog_private::EnableCommand::DoExecute(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoGetMemoryRegionInfo(), lldb_private::ScriptedProcess::DoGetMemoryRegionInfo(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoHalt(), ProcessKDP::DoHalt(), DynamicLoaderMacOSXDYLD::DoInitialImageFetch(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoLaunch(), lldb_private::ProcessWindows::DoLaunch(), lldb_private::ScriptedProcess::DoLaunch(), ProcessKDP::DoLaunch(), lldb_private::minidump::ProcessMinidump::DoLoadCore(), ProcessElfCore::DoLoadCore(), ProcessMachCore::DoLoadCore(), lldb_private::Platform::DoLoadImage(), lldb_private::PlatformWindows::DoLoadImage(), PlatformPOSIX::DoLoadImage(), lldb_private::LockFileBase::DoLock(), RegisterContextKDP_arm64::DoReadDBG(), RegisterContextKDP_arm::DoReadDBG(), RegisterContextKDP_arm64::DoReadEXC(), RegisterContextKDP_arm::DoReadEXC(), RegisterContextKDP_x86_64::DoReadEXC(), RegisterContextKDP_arm64::DoReadFPU(), RegisterContextKDP_arm::DoReadFPU(), RegisterContextKDP_x86_64::DoReadFPU(), RegisterContextKDP_arm64::DoReadGPR(), RegisterContextKDP_arm::DoReadGPR(), RegisterContextKDP_x86_64::DoReadGPR(), lldb_private::minidump::ProcessMinidump::DoReadMemory(), lldb_private::Process::DoReadMemory(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoReadMemory(), lldb_private::ProcessTrace::DoReadMemory(), lldb_private::ProcessWindows::DoReadMemory(), lldb_private::ScriptedProcess::DoReadMemory(), ProcessElfCore::DoReadMemory(), ProcessFreeBSDKernelCore::DoReadMemory(), ProcessKDP::DoReadMemory(), ProcessMachCore::DoReadMemory(), lldb_private::process_linux::NativeRegisterContextLinux::DoReadRegisterValue(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoResume(), lldb_private::ProcessWindows::DoResume(), ProcessKDP::DoResume(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoSignal(), ProcessKDP::DoSignal(), lldb_private::OptionArgParser::DoToAddress(), lldb_private::ScriptedProcess::DoUpdateThreadList(), ProcessFreeBSDKernelCore::DoUpdateThreadList(), ProcessKDP::DoWillAttachToProcessWithID(), ProcessKDP::DoWillAttachToProcessWithName(), ProcessKDP::DoWillLaunch(), lldb_private::Platform::DownloadModuleSlice(), lldb_private::platform_android::PlatformAndroid::DownloadModuleSlice(), CommandObjectTargetSymbolsAdd::DownloadObjectAndSymbolFile(), lldb_private::PluginManager::DownloadObjectAndSymbolFile(), lldb_private::SymbolLocatorDebugSymbols::DownloadObjectAndSymbolFile(), lldb_private::SymbolLocatorDefault::DownloadObjectAndSymbolFile(), lldb_private::platform_android::PlatformAndroid::DownloadSymbolFile(), lldb_private::SymbolLocator::DownloadSymbolFileAsync(), RegisterContextKDP_arm64::DoWriteDBG(), RegisterContextKDP_arm::DoWriteDBG(), RegisterContextKDP_arm64::DoWriteEXC(), RegisterContextKDP_arm::DoWriteEXC(), RegisterContextKDP_x86_64::DoWriteEXC(), RegisterContextKDP_arm64::DoWriteFPU(), RegisterContextKDP_arm::DoWriteFPU(), RegisterContextKDP_x86_64::DoWriteFPU(), RegisterContextKDP_arm64::DoWriteGPR(), RegisterContextKDP_arm::DoWriteGPR(), RegisterContextKDP_x86_64::DoWriteGPR(), lldb_private::Process::DoWriteMemory(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoWriteMemory(), lldb_private::ProcessWindows::DoWriteMemory(), lldb_private::ScriptedProcess::DoWriteMemory(), ProcessKDP::DoWriteMemory(), lldb_private::PseudoConsole::DrainInitSequences(), lldb_private::BreakpointResolver::Dump(), lldb_private::Diagnostics::Dump(), dump_type_value(), lldb_private::formatters::DumpCxxSmartPtrPointerSummary(), MinidumpFileBuilder::DumpDirectories(), DumpDwoFilesTable(), MinidumpFileBuilder::DumpFile(), MinidumpFileBuilder::DumpHeader(), DumpOsoFilesTable(), CommunicationKDP::DumpPacket(), lldb_private::ValueObject::DumpPrintableRepresentation(), lldb_private::OptionValueProperties::DumpPropertyValue(), lldb_private::Watchpoint::DumpSnapshots(), lldb_private::FormatEntity::Formatter::DumpValue(), CommandObjectTargetVariable::DumpValueObject(), DynamicLoaderDarwinKernel::DynamicLoaderDarwinKernel(), lldb_private::Disassembler::ElideMixedSourceAndDisassemblyLine(), EmulateInstructionMIPS64::Emulate_SD(), EmulateInstructionMIPS::Emulate_SW(), EmulateInstructionMIPS::Emulate_SWM16_32(), EmulateInstructionMIPS::Emulate_SWSP(), EmulateInstructionARM64::EmulateLDPSTP(), EmulateInstructionARM64::EmulateLDRSTRImm(), lldb_private::process_gdb_remote::ProcessGDBRemote::EnableBreakpointSite(), lldb_private::ProcessWindows::EnableBreakpointSite(), lldb_private::ScriptedProcess::EnableBreakpointSite(), ProcessKDP::EnableBreakpointSite(), lldb_private::Process::EnableBreakpointSiteByID(), lldb_private::OptionParser::EnableError(), lldb::SBDebugger::EnableLog(), lldb_private::StructuredDataDarwinLog::EnableNow(), lldb_private::NativeProcessProtocol::EnableSoftwareBreakpoint(), lldb_private::Process::EnableSoftwareBreakpoint(), lldb_private::Process::EnableWatchpoint(), lldb_private::process_gdb_remote::ProcessGDBRemote::EnableWatchpoint(), lldb_private::ProcessWindows::EnableWatchpoint(), EnsureFDFlags(), EnsureFDFlags(), EnsureFDFlags(), lldb_private::SaveCoreOptions::EnsureValidConfiguration(), EnterSyncMode(), lldb_private::ScriptedInterface::ErrorWithMessage(), lldb_private::process_gdb_remote::ProcessGDBRemote::EstablishConnectionIfNeeded(), lldb_private::DWARFExpression::Evaluate(), lldb_private::UserExpression::Evaluate(), Evaluate_DW_OP_deref_size(), lldb_private::dil::Interpreter::EvaluateAndDereference(), lldb::SBTarget::EvaluateExpression(), lldb_private::CommandObjectExpression::EvaluateExpression(), PlatformPOSIX::EvaluateLibdlExpression(), ExceptionMaskValidator(), lldb_private::CommandObjectParsed::Execute(), CommandObjectTypeSummaryAdd::Execute_StringSummary(), lldb_private::platform_android::AdbSyncService::ExecuteCommand(), lldb_private::ScriptedThreadPlanPythonInterface::ExplainsStop(), lldb_protocol::mcp::ProtocolDescriptor::Extract(), lldb_private::plugin::dwarf::DWARFDebugAranges::extract(), lldb_private::PlatformDarwin::ExtractCrashInfoAnnotations(), ExtractDestroyFunction(), ExtractFields(), ExtractRuntimeGlobalSymbol(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject(), lldb_private::FormatEntity::ExtractVariableInfo(), lldb_private::FunctionCaller::FetchFunctionResults(), lldb_private::ScriptedThread::FetchThreadExtendedInfo(), lldb_private::ClassDescriptorV2::iVarsStorage::fill(), lldb_private::StructuredDataDarwinLog::FilterLaunchInfo(), lldb_private::CoreFileMemoryRanges::FinalizeCoreFileSaveRanges(), OptionGroupReadMemory::FinalizeSettings(), find_cached_path(), lldb_private::BreakpointIDList::FindAndReplaceIDRanges(), lldb_private::SymbolContext::FindBestGlobalDataSymbol(), lldb_private::Target::FindBreakpointName(), lldb_private::BreakpointList::FindBreakpointsByName(), ProcessElfCore::FindBuidIdInCoreMemory(), FindEntry(), lldb_private::ClangExpressionDeclMap::FindExternalVisibleDecls(), lldb::SBProcess::FindInMemory(), lldb_private::Process::FindInMemory(), lldb_private::Process::FindInMemory(), DYLDRendezvous::FindMetadata(), HexagonDYLDRendezvous::FindMetadata(), lldb::SBProcess::FindRangesInMemory(), lldb_private::Process::FindRangesInMemory(), FindUnusedPort(), UnwindAssembly_x86::FirstNonPrologueInsn(), MinidumpFileBuilder::FixThreadStacks(), lldb_private::NativeProcessProtocol::FixupBreakpointPCAsNeeded(), lldb::SBFile::Flush(), lldb_private::NativeFile::Flush(), MinidumpFileBuilder::FlushBufferToDisk(), lldb_private::Debugger::FlushProcessOutput(), lldb_private::ForEachFormatterInModule(), lldb_private::FormatEntity::Formatter::Format(), llvm::format_provider< lldb_private::Status >::format(), lldb_private::Log::FormatError(), lldb_private::BytecodeSummaryFormat::FormatObject(), lldb_private::TypeFormatImpl_EnumType::FormatObject(), lldb_private::TypeFormatImpl_Format::FormatObject(), lldb_private::FormatEntity::Formatter::FormatStringRef(), CommandObjectTypeSummaryClear::FormatterSpecificDeletion(), CommandObjectTypeSummaryList::FormatterSpecificList(), lldb_private::IRMemoryMap::Free(), lldb_private::Status::FromError(), lldb_protocol::mcp::fromJSON(), lldb_private::BytecodeSyntheticChildren::FrontEnd::FrontEnd(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::GDBRemoteCommunicationServer(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::GDBRemoteCommunicationServerPlatform(), lldb_private::ScriptInterpreterPythonImpl::GenerateFunction(), lldb_private::ScriptInterpreterPythonImpl::GenerateTypeScriptFunction(), lldb_private::ScriptInterpreterPythonImpl::GenerateWatchpointCommandCallbackData(), lldb_private::ModuleCache::Get(), lldb::SBData::GetAddress(), CoreSimulatorSupport::DeviceSet::GetAllDevices(), lldb::SBPlatform::GetAllProcesses(), lldb_private::ModuleCache::GetAndPut(), lldb_private::ArchitectureArm::GetArchitectureUnwindPlan(), ABIMacOSX_arm64::GetArgumentValues(), ABIMacOSX_arm::GetArgumentValues(), ABISysV_arm64::GetArgumentValues(), ABISysV_arm::GetArgumentValues(), lldb::SBStructuredData::GetAsJSON(), lldb_private::RegisterValue::GetAsMemoryData(), lldb_private::Scalar::GetAsMemoryData(), lldb_private::Status::GetAsStructuredData(), lldb::SBProcess::GetAsyncProfileData(), lldb_private::Process::GetAsyncProfileData(), lldb_private::process_netbsd::NativeProcessNetBSD::GetAuxvData(), CoreSimulatorSupport::DeviceSet::GetAvailableDevices(), lldb_private::AppleObjCRuntime::GetBacktraceThreadFromException(), lldb::SBExpressionOptions::GetBooleanLanguageOption(), lldb_private::SingleStepBreakpointLocationsPredictor::GetBreakpointLocationAddress(), lldb::SBBreakpointNameImpl::GetBreakpointName(), lldb_private::Platform::GetCachedExecutable(), lldb_private::Platform::GetCachedSharedModule(), lldb_private::Address::GetCallableLoadAddress(), lldb_private::IndirectCallEdge::GetCallee(), lldb_private::ScriptedProcessPythonInterface::GetCapabilities(), lldb_private::BytecodeSyntheticChildren::FrontEnd::GetChildAtIndex(), lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::GetChildAtIndex(), lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< D32, D64 >::GetChildAtIndex(), lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::GetChildAtIndex(), lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSCFDictionarySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSCFSetSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSDictionary1SyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSDictionaryISyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSSetISyntheticFrontEnd::GetChildAtIndex(), lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorLegacy::GetClassDescriptor(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), lldb_private::AppleGetQueuesHandler::GetCurrentQueues(), lldb::SBSaveCoreOptions::GetCurrentSizeInBytes(), lldb_private::SaveCoreOptions::GetCurrentSizeInBytes(), lldb::SBValue::GetData(), lldb_private::ValueObject::GetData(), lldb_private::ScriptedBreakpointPythonInterface::GetDepth(), lldb::SBStructuredData::GetDescription(), lldb::SBValue::GetDescription(), lldb_private::ScriptedFrameProviderPythonInterface::GetDescription(), lldb_private::StructuredDataDarwinLog::GetDescription(), lldb_private::ThreadPlanStepRange::GetDescription(), lldb::SBFrame::GetDescriptionWithFormat(), lldb::SBThread::GetDescriptionWithFormat(), lldb_private::ScriptedFramePythonInterface::GetDisplayFunctionName(), lldb::SBData::GetDouble(), lldb_private::ScriptedFrame::GetDynamicRegisterInfo(), lldb_private::ScriptedThread::GetDynamicRegisterInfo(), lldb_private::ScriptInterpreter::GetDynamicSettings(), lldb_private::ItaniumABILanguageRuntime::GetDynamicTypeAndAddress(), lldb_private::NativeProcessELF::GetELFImageInfoAddress(), lldb_private::RegularExpression::GetError(), lldb_private::Status::GetError(), lldb_private::ItaniumABILanguageRuntime::GetExceptionObjectForThread(), SystemRuntimeMacOSX::GetExtendedBacktraceFromItemRef(), SystemRuntimeMacOSX::GetExtendedBacktraceThread(), lldb_private::ScriptedThreadPythonInterface::GetExtendedInfo(), UnwindAssembly_x86::GetFastUnwindPlan(), lldb_private::platform_android::PlatformAndroid::GetFile(), PlatformPOSIX::GetFile(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetFileExists(), lldb_private::NativeProcessWindows::GetFileLoadAddress(), lldb_private::process_freebsd::NativeProcessFreeBSD::GetFileLoadAddress(), lldb_private::process_linux::NativeProcessLinux::GetFileLoadAddress(), lldb_private::process_netbsd::NativeProcessNetBSD::GetFileLoadAddress(), lldb_private::Platform::GetFilePermissions(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::GetFilePermissions(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetFilePermissions(), lldb_private::NativeFile::GetFileSpec(), lldb::SBData::GetFloat(), lldb_private::ScriptedFrameProvider::GetFrameAtIndex(), lldb_private::ScriptedFrameProviderPythonInterface::GetFrameAtIndex(), GetFreeBSDProcessUserAndGroup(), PlatformPOSIX::GetFullNameForDylib(), lldb_private::Target::GetFunctionCallerForLanguage(), lldb_private::ScriptedFramePythonInterface::GetFunctionName(), CommandObjectCommandsAddRegex::CommandOptions::GetHelp(), lldb_private::ScriptedFramePythonInterface::GetID(), ObjectFileELF::GetImageInfoAddress(), lldb_private::BytecodeSyntheticChildren::FrontEnd::GetIndexOfChildWithName(), lldb::SBDebugger::GetInternalVariableValue(), lldb_private::AppleObjCRuntimeV1::GetISAHashTablePointer(), lldb_private::AppleObjCRuntimeV2::GetISAHashTablePointer(), lldb_private::AppleGetItemInfoHandler::GetItemInfo(), lldb_private::MemoryCache::GetL2CacheLine(), SystemRuntimeMacOSX::GetLibdispatchQueueAddressFromThreadQAddress(), lldb_private::IOHandlerEditline::GetLine(), lldb_private::IOHandlerEditline::GetLines(), lldb_private::Process::GetLoadAddressPermissions(), lldb_private::ScriptedProcess::GetLoadedDynamicLibrariesInfos(), lldb_private::ScriptedProcessPythonInterface::GetLoadedImages(), lldb_private::NativeProcessWindows::GetLoadedModuleFileSpec(), lldb_private::process_freebsd::NativeProcessFreeBSD::GetLoadedModuleFileSpec(), lldb_private::process_linux::NativeProcessLinux::GetLoadedModuleFileSpec(), lldb_private::process_netbsd::NativeProcessNetBSD::GetLoadedModuleFileSpec(), lldb_private::ScriptedBreakpointPythonInterface::GetLocationDescription(), lldb::SBData::GetLongDouble(), ProcessElfCore::GetMainExecutablePath(), lldb_private::IRMemoryMap::GetMemoryData(), lldb_private::Module::GetMemoryObjectFile(), lldb_private::ScriptedProcessInterface::GetMemoryRegionContainingAddress(), lldb_private::ScriptedProcessPythonInterface::GetMemoryRegionContainingAddress(), lldb_private::Process::GetMemoryRegionInfo(), lldb_private::process_freebsd::NativeProcessFreeBSD::GetMemoryRegionInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetMemoryRegionInfo(), lldb_private::process_linux::NativeProcessLinux::GetMemoryRegionInfo(), lldb_private::process_netbsd::NativeProcessNetBSD::GetMemoryRegionInfo(), lldb_private::ProcessDebugger::GetMemoryRegionInfo(), lldb_private::Process::GetMemoryRegions(), lldb_private::ScriptedProcess::GetMemoryRegions(), lldb_private::SaveCoreOptions::GetMemoryRegionsToSave(), lldb_private::ScriptedProcess::GetMetadata(), lldb_private::ScriptedProcessPythonInterface::GetMetadata(), GetModuleSpecInfoFromUUIDDictionary(), lldb_private::minidump::MinidumpParser::GetModuleUUID(), lldb_private::process_freebsd::NativeThreadFreeBSD::GetName(), lldb_private::process_netbsd::NativeThreadNetBSD::GetName(), lldb_private::ScriptedThreadPythonInterface::GetName(), GetNetBSDProcessUserAndGroup(), lldb_private::SingleStepBreakpointLocationsPredictor::GetNextInstructionAddress(), UnwindAssembly_x86::GetNonCallSiteUnwindPlanFromAssembly(), UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly(), DynamicLoaderMacOS::GetNotificationFuncAddrFromImageInfos(), lldb_private::AppleObjCRuntime::GetObjectDescription(), lldb_private::ValueObject::GetObjectDescription(), CommandObjectTypeFilterAdd::GetOptions(), lldb_private::PlatformList::GetOrCreate(), lldb_private::PlatformList::GetOrCreate(), lldb_private::minidump::ProcessMinidump::GetOrCreateModule(), lldb_private::Target::GetOrCreateModule(), RegisterContextFreeBSDKernelCore_arm64::GetOsreldate(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::GetPacketAndSendResponse(), lldb_private::ScriptedFramePythonInterface::GetPC(), SystemRuntimeMacOSX::GetPendingItemRefsForQueue(), lldb_private::AppleGetPendingItemsHandler::GetPendingItems(), lldb_private::File::GetPermissions(), lldb_private::ValueObject::GetPointeeData(), lldb_private::ScriptedFrameProviderPythonInterface::GetPriority(), lldb_private::ScriptedProcessPythonInterface::GetProcessID(), lldb_private::ScriptedPlatformPythonInterface::GetProcessInfo(), lldb_private::platform_android::PlatformAndroid::GetPropertyPackageName(), lldb_private::Properties::GetPropertyValue(), lldb_private::ScriptedThreadPythonInterface::GetQueue(), SystemRuntimeMacOSX::GetQueueIDFromThreadQAddress(), SystemRuntimeMacOSX::GetQueueKind(), SystemRuntimeMacOSX::GetQueueNameFromThreadQAddress(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetQXferMemoryMapRegionInfo(), lldb_private::ScriptedFrame::GetRegisterContext(), lldb_private::ScriptedFramePythonInterface::GetRegisterContext(), lldb_private::ScriptedThreadPythonInterface::GetRegisterContext(), lldb_private::OperatingSystemPythonInterface::GetRegisterContextForTID(), lldb_private::ScriptedFramePythonInterface::GetRegisterInfo(), lldb_private::ScriptedThreadPythonInterface::GetRegisterInfo(), GetRegistersAsJSON(), lldb_private::Platform::GetRemoteSharedModule(), lldb_private::ScriptInterpreterPythonImpl::GetRepeatCommandForScriptedCommand(), GetResponseError(), ABIMacOSX_arm64::GetReturnValueObjectImpl(), ABIMacOSX_arm::GetReturnValueObjectImpl(), ABISysV_arm64::GetReturnValueObjectImpl(), ABISysV_arm::GetReturnValueObjectImpl(), ABISysV_mips64::GetReturnValueObjectImpl(), ABISysV_i386::GetReturnValueObjectSimple(), ABISysV_ppc::GetReturnValueObjectSimple(), ABISysV_x86_64::GetReturnValueObjectSimple(), ABIWindows_x86_64::GetReturnValueObjectSimple(), GetReturnValuePassedInMemory(), lldb_private::IRExecutionUnit::GetRunnableInfo(), lldb_private::ScriptedThreadPlanPythonInterface::GetRunState(), lldb_private::ScriptedThreadPythonInterface::GetScriptedFramePluginName(), lldb_private::ScriptedProcessPythonInterface::GetScriptedThreadPluginName(), lldb_private::platform_android::PlatformAndroid::GetSdkVersion(), ObjectFileELF::GetSectionHeaderInfo(), DynamicLoaderMacOSXDYLD::GetSharedCacheInformation(), lldb_private::ModuleList::GetSharedModule(), lldb_private::Platform::GetSharedModule(), lldb_private::PlatformAppleSimulator::GetSharedModule(), lldb_private::PlatformDarwin::GetSharedModule(), lldb_private::PlatformMacOSX::GetSharedModule(), lldb_private::PlatformRemoteDarwinDevice::GetSharedModule(), lldb_private::ScriptedBreakpointPythonInterface::GetShortHelp(), lldb_private::process_linux::NativeThreadLinux::GetSiginfo(), lldb::SBData::GetSignedInt16(), lldb::SBData::GetSignedInt32(), lldb::SBData::GetSignedInt64(), lldb::SBData::GetSignedInt8(), lldb_private::ValueImpl::GetSP(), lldb_private::Thread::GetStackFrameList(), lldb_private::ScriptedThreadPythonInterface::GetStackFrames(), lldb_private::ScriptedThreadPythonInterface::GetState(), StringExtractorGDBRemote::GetStatus(), lldb_private::ScriptedPythonInterface::GetStatusFromMethod(), lldb_private::ScriptInterpreter::GetStatusFromSBError(), lldb::SBProcess::GetSTDERR(), lldb_private::Process::GetSTDERR(), lldb::SBProcess::GetSTDOUT(), lldb_private::Process::GetSTDOUT(), lldb_private::AppleObjCTrampolineHandler::GetStepThroughDispatchPlan(), lldb_private::DynamicLoaderDarwin::GetStepThroughTrampolinePlan(), lldb_private::ScriptedThreadPlanPythonInterface::GetStopDescription(), lldb_private::ScriptedThreadPythonInterface::GetStopReason(), lldb::SBData::GetString(), lldb_private::OptionValue::GetSubValue(), lldb_private::OptionValueArray::GetSubValue(), lldb_private::OptionValueDictionary::GetSubValue(), lldb_private::OptionValueProperties::GetSubValue(), lldb_private::ScriptedFramePythonInterface::GetSymbolContext(), lldb_private::PlatformAppleSimulator::GetSymbolFile(), lldb_private::PlatformRemoteDarwinDevice::GetSymbolFile(), lldb_private::AppleObjCRuntimeV2::GetTaggedPointerObfuscator(), lldb_private::minidump::MinidumpParser::GetThreadContextWow64(), lldb_private::ScriptedThreadPythonInterface::GetThreadID(), lldb_private::OperatingSystemPythonInterface::GetThreadInfo(), lldb_private::AppleGetThreadItemInfoHandler::GetThreadItemInfo(), lldb_private::DynamicLoaderDarwin::GetThreadLocalData(), lldb_private::ScriptedProcessPythonInterface::GetThreadsInfo(), lldb_private::Status::GetType(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetTypeUnitSupportFiles(), lldb::SBData::GetUnsignedInt16(), lldb::SBData::GetUnsignedInt32(), lldb::SBData::GetUnsignedInt64(), lldb::SBData::GetUnsignedInt8(), lldb_private::Target::GetUserExpressionForLanguage(), GetValObjFromIntRegs(), GetValObjFromIntRegs(), lldb_private::Value::GetValueAsData(), lldb::SBValue::GetValueAsSigned(), lldb::SBValue::GetValueAsUnsigned(), lldb_private::ValueObject::GetValueForExpressionPath(), lldb_private::ValueObject::GetValueForExpressionPath_Impl(), lldb_private::BorrowedStackFrame::GetValueForVariableExpressionPath(), lldb_private::ScriptedFrame::GetValueForVariableExpressionPath(), lldb_private::StackFrame::GetValueForVariableExpressionPath(), lldb::SBFrame::GetValueForVariablePath(), lldb_private::ScriptedFrameInterface::GetValueObjectForVariableExpression(), lldb_private::Variable::GetValuesForVariableExpressionPath(), lldb_private::ValueObjectPrinter::GetValueSummaryError(), lldb_private::npdb::GetVariableLocationInfo(), lldb_private::ScriptedFramePythonInterface::GetVariables(), lldb_private::ItaniumABILanguageRuntime::GetVTableInfo(), lldb_private::NativeRegisterContextDBReg::GetWatchpointHitIndex(), lldb_private::NativeRegisterContextDBReg_x86::GetWatchpointHitIndex(), lldb_private::process_freebsd::NativeProcessFreeBSD::Halt(), lldb_private::process_linux::NativeProcessLinux::Halt(), lldb_private::Process::HaltPrivate(), lldb_private::ProcessDebugger::HaltProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_C(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_g(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_I(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_interrupt(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_k(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_M(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_memory_read(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_P(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_p(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qFileLoadAddress(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qLaunchGDBServer(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qMemoryRegionInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qMemoryRegionInfoSupported(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qMemTags(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_QNonStop(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_QPassSignals(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qPlatform_chmod(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qPlatform_mkdir(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_QRestoreRegisterState(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_QSaveRegisterState(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_vAttach(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_vAttachOrWait(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_vAttachWait(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_vCont(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_Close(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_pRead(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_pWrite(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_symlink(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_unlink(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_vKill(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_Z(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_z(), lldb_private::RISCVSingleStepBreakpointLocationsPredictor::HandleAtomicSequence(), lldb_private::CommandInterpreter::HandleCommand(), lldb_private::CommandInterpreter::HandleCommandsFromFile(), HandleFileAction(), CommandObjectThreadException::HandleOneThread(), CommandObjectThreadSiginfo::HandleOneThread(), CommandObjectBreakpointRead::CommandOptions::HandleOptionArgumentCompletion(), lldb::SBDebugger::HandleProcessEvent(), lldb_private::Debugger::HandleProcessEvent(), lldb_private::DebuggerThread::HandleRipEvent(), lldb_private::ScriptedStopHookPythonInterface::HandleStop(), IncludePerfEventParanoidMessageInError(), lldb_private::python::PythonScript::Init(), lldb_private::AppleObjCRuntimeV1::ClassDescriptorV1::Initialize(), lldb_private::SystemInitializerCommon::Initialize(), lldb_private::SystemInitializerFull::Initialize(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::InitializeConnection(), lldb::SBDebugger::InitializeWithErrorHandling(), lldb::SBPlatform::Install(), lldb_private::Platform::Install(), lldb_private::Target::Install(), installExecutable(), lldb_private::platform_android::AdbClient::internalShell(), IRInterpreter::Interpret(), lldb_private::FormatterBytecode::Interpret(), lldb_private::NativeProcessProtocol::Interrupt(), lldb_private::process_linux::NativeProcessLinux::Interrupt(), CommandObjectCommandsScriptAdd::IOHandlerInputComplete(), CommandObjectTypeSummaryAdd::IOHandlerInputComplete(), CommandObjectTypeSynthAdd::IOHandlerInputComplete(), IOHandlerLuaInterpreter::IOHandlerInputComplete(), lldb_private::CommandInterpreter::IOHandlerInputComplete(), lldb_private::REPL::IOHandlerInputComplete(), lldb_private::ScriptInterpreterPythonImpl::IOHandlerPythonInterpreter, lldb_private::ScriptedProcessPythonInterface::IsAlive(), lldb_private::ScriptedFramePythonInterface::IsArtificial(), lldb_private::ScriptedFramePythonInterface::IsHidden(), lldb_private::AppleObjCRuntimeV2::SharedCacheImageHeaders::IsImageLoaded(), lldb_private::ScriptedFramePythonInterface::IsInlined(), lldb_private::Language::IsLogicalTrue(), lldb_private::ValueObject::IsLogicalTrue(), lldb_private::AppleObjCRuntimeV2::TaggedPointerVendorLegacy::IsPossibleTaggedPointer(), lldb_private::HostProcessPosix::IsRunning(), lldb_private::AppleObjCRuntimeV2::IsSharedCacheImageLoaded(), lldb_private::ScriptedThreadPlanPythonInterface::IsStale(), lldb_private::NativeRegisterContextDBReg_x86::IsWatchpointHit(), lldb_private::NativeRegisterContextDBReg_x86::IsWatchpointVacant(), lldb_private::HostThreadPosix::Join(), lldb_private::HostThreadWindows::Join(), lldb_private::ThreadedCommunication::JoinReadThread(), lldb_private::process_aix::NativeProcessAIX::Kill(), lldb_private::process_freebsd::NativeProcessFreeBSD::Kill(), lldb_private::process_linux::NativeProcessLinux::Kill(), lldb_private::process_netbsd::NativeProcessNetBSD::Kill(), lldb::SBPlatform::Launch(), lldb::SBTarget::Launch(), lldb::SBTarget::Launch(), lldb_private::process_freebsd::NativeProcessFreeBSD::Manager::Launch(), lldb_private::Target::Launch(), lldb_private::process_gdb_remote::ProcessGDBRemote::LaunchAndConnectToDebugserver(), lldb_private::platform_android::PlatformAndroidRemoteGDBServer::LaunchGDBServer(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::LaunchGDBServer(), lldb_private::Process::LaunchPrivate(), lldb_private::Host::LaunchProcess(), lldb_private::MonitoringProcessLauncher::LaunchProcess(), lldb_private::Platform::LaunchProcess(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::LaunchProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::LaunchProcess(), lldb_private::ProcessDebugger::LaunchProcess(), lldb_private::ProcessLauncher::LaunchProcess(), lldb_private::ProcessLauncherPosixFork::LaunchProcess(), lldb_private::ProcessLauncherWindows::LaunchProcess(), LaunchProcessPosixSpawn(), LaunchProcessXPC(), lldb::SBTarget::LaunchSimple(), lldb_private::IRMemoryMap::Leak(), lldb_private::StackFrame::LegacyGetValueForVariableExpressionPath(), lldb_private::DomainSocket::Listen(), lldb_private::TCPSocket::Listen(), lldb_private::ScriptedPlatformPythonInterface::ListProcesses(), lldb::SBValue::LLDB_DEPRECATED(), lldb::SBProcess::LLDB_DEPRECATED_FIXME(), lldb::SBValue::LLDB_DEPRECATED_FIXME(), lldb::SBError::lldb_private::python::SWIGBridge, lldb_private::ScriptedThread::LoadArtificialStackFrames(), lldb_private::DynamicLoader::LoadBinaryWithUUIDAndAddress(), lldb::SBTarget::LoadCore(), lldb::SBTarget::LoadCore(), lldb_private::Process::LoadCore(), ObjectFileMachO::LoadCoreFileImages(), lldb_private::Platform::LoadImage(), DynamicLoaderFreeBSDKernel::KModImageInfo::LoadImageUsingMemoryModule(), lldb::SBProcess::LoadImageUsingPaths(), lldb_private::Platform::LoadImageUsingPaths(), DynamicLoaderDarwinKernel::LoadKernelModuleIfNeeded(), lldb_private::Lua::LoadModule(), DynamicLoaderPOSIXDYLD::LoadModuleAtAddress(), lldb_private::Debugger::LoadPlugin(), LoadPluginCallback(), lldb_private::ScriptInterpreter::LoadPluginModule(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::LoadQXferMemoryMap(), lldb_private::ScriptInterpreter::LoadScriptingModule(), lldb_private::ScriptInterpreterLua::LoadScriptingModule(), LoadScriptingResourceForModule(), lldb_private::Module::LoadScriptingResourceInTarget(), lldb_private::ModuleList::LoadScriptingResourcesInTarget(), lldb::SBDebugger::LoadTraceFromFile(), lldb::SBTrace::LoadTraceFromFile(), LoadValueFromConsecutiveGPRRegisters(), LoadValueFromConsecutiveGPRRegisters(), LookForDsymNextToExecutablePath(), lldb_private::MainLoopPosix::MainLoopPosix(), lldb_protocol::mcp::ProtocolDescriptor::Make(), lldb_private::platform_android::PlatformAndroidRemoteGDBServer::MakeConnectURL(), lldb_private::Platform::MakeDirectory(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::MakeDirectory(), lldb_private::UtilityFunction::MakeFunctionCaller(), PlatformPOSIX::MakeLoadImageUtilityFunction(), lldb_private::IRMemoryMap::Malloc(), lldb_private::Materializer::Materialize(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::MaybeCloseInferiorTerminalConnection(), lldb_private::plugin::dwarf::DebugNamesDWARFIndex::MaybeLogLookupError(), MissingDeclContext::MissingDeclContext(), lldb_private::Breakpoint::ModulesChanged(), lldb_private::process_linux::NativeProcessLinux::MonitorSignal(), lldb_private::process_freebsd::NativeProcessFreeBSD::MonitorSIGTRAP(), lldb_private::process_linux::NativeProcessLinux::MonitorSIGTRAP(), lldb_private::process_netbsd::NativeProcessNetBSD::MonitorSIGTRAP(), lldb_private::NativeProcessELF::NativeProcessProtocol(), DynamicLoaderMacOS::NotifyBreakpointHit(), lldb_private::process_linux::NativeProcessLinux::NotifyTracersOfNewThread(), lldb_private::process_linux::NativeProcessLinux::NotifyTracersOfThreadDestroyed(), lldb_private::formatters::NSArraySummaryProvider(), lldb_private::formatters::NSAttributedStringSummaryProvider(), lldb_private::formatters::NSDataSummaryProvider(), lldb_private::formatters::NSDateSummaryProvider(), lldb_private::formatters::NSDecimalNumberSummaryProvider(), lldb_private::formatters::NSDictionarySummaryProvider(), lldb_private::formatters::NSError_SummaryProvider(), lldb_private::formatters::NSIndexSetSummaryProvider(), lldb_private::formatters::NSMachPortSummaryProvider(), lldb_private::formatters::NSNumberSummaryProvider(), lldb_private::formatters::NSSetSummaryProvider(), lldb_private::formatters::NSStringSummaryProvider(), lldb_private::NativeRegisterContextDBReg::NumSupportedHardwareBreakpoints(), lldb_private::NativeRegisterContextDBReg::NumSupportedHardwareWatchpoints(), lldb_private::formatters::ObjCSELSummaryProvider(), lldb_private::NativeProcessWindows::OnDebugException(), lldb_private::ProcessWindows::OnDebuggerConnected(), lldb_private::IDebugDelegate::OnDebuggerError(), lldb_private::LocalDebugDelegate::OnDebuggerError(), lldb_private::NativeDebugDelegate::OnDebuggerError(), lldb_private::ProcessDebugger::OnDebuggerError(), lldb_private::ProcessWindows::OnDebuggerError(), lldb_private::transport::Binder< Proto >::OnError(), lldb_private::ProcessDebugger::OnExitProcess(), lldb_private::REPL::OnExpressionEvaluated(), lldb_private::DynamicLoaderWindowsDYLD::OnLoadModule(), lldb_private::transport::IOTransport< Proto >::OnRead(), lldb_private::PipePosix::OpenAsReader(), lldb_private::FileCache::OpenFile(), lldb_private::Platform::OpenFile(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::OpenFile(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::OpenFile(), lldb_private::RemoteAwarePlatform::OpenFile(), lldb_private::PseudoConsole::OpenPseudoConsole(), lldb_private::Host::OpenURL(), lldb_private::python::PythonScript::operator()(), lldb_private::transport::Binder< Proto >::ReplyOnce::operator()(), lldb_private::MemoryCache::operator=(), CommandObjectBreakpointAddFile::CommandOptions::OptionParsingFinished(), lldb_private::OptionGroup::OptionParsingFinished(), lldb_private::OptionGroupOptions::OptionParsingFinished(), lldb_private::OptionGroupPythonClassWithDict::OptionParsingFinished(), lldb_private::Options::OptionParsingFinished(), CommandObjectTypeFilterAdd::CommandOptions::OptionParsingStarting(), lldb_private::OptionValueFormatEntity::OptionValueFormatEntity(), lldb_private::ArchitectureArm::OverrideStopInfo(), ELFLinuxPrPsInfo::Parse(), ELFLinuxPrStatus::Parse(), lldb_private::dil::DILParser::Parse(), lldb_private::minidump::MinidumpMiscInfo::Parse(), lldb_private::Options::Parse(), sddarwinlog_private::ParseAutoEnableOptions(), lldb_private::plugin::dwarf::DWARFASTParser::ParseChildArrayInfo(), lldb_private::plugin::dwarf::DWARFUnit::ParseDWARFLocationList(), ParseEntry(), sddarwinlog_private::EnableOptions::ParseFilterRule(), RemoteNXMapTable::ParseHeader(), ParseHostIOPacketResponse(), ParseInlineeLineTableForCompileUnit(), ParseInternal(), lldb_private::StructuredData::ParseJSONFromFile(), lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::ParseKernel(), ParseLLVMLineTablePrologue(), lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::ParseModule(), ProcessElfCore::parseNetBSDNotes(), lldb_private::CommandObject::ParseOptions(), lldb_private::CommandObject::ParseOptionsAndNotify(), lldb_private::process_gdb_remote::ProcessGDBRemote::ParsePythonTargetDefinition(), ObjectFileELF::ParseRISCVAttributes(), CommandObjectScriptingObjectParsed::CommandOptions::ParseUsageMaskFromArray(), lldb_private::plugin::dwarf::SymbolFileWasm::ParseVendorDWARFOpcode(), lldb_private::platform_android::PlatformAndroidRemoteGDBServer::PlatformAndroidRemoteGDBServer(), lldb_private::process_netbsd::NativeProcessNetBSD::PopulateMemoryRegionCache(), SystemRuntimeMacOSX::PopulateQueueList(), SystemRuntimeMacOSX::PopulateQueuesUsingLibBTR(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread(), ABIMacOSX_i386::PrepareTrivialCall(), ABISysV_i386::PrepareTrivialCall(), ABISysV_mips64::PrepareTrivialCall(), ABISysV_mips::PrepareTrivialCall(), ABISysV_ppc64::PrepareTrivialCall(), ABISysV_ppc::PrepareTrivialCall(), ABISysV_s390x::PrepareTrivialCall(), ABISysV_x86_64::PrepareTrivialCall(), ABIWindows_x86_64::PrepareTrivialCall(), lldb_private::CommandInterpreter::PreprocessCommand(), lldb_private::CommandInterpreter::PreprocessToken(), lldb_private::ValueObjectPrinter::PrintChild(), lldb_private::ClangREPL::PrintOneVariable(), ProcessFreeBSDKernelCore::PrintUnreadMessage(), lldb_private::Process::PrivateResume(), CoreSimulatorSupport::Process::Process(), CoreSimulatorSupport::Process::Process(), ProcessAliasOptionsArgs(), lldb_private::ProcessStructReader::ProcessStructReader(), lldb_private::process_freebsd::NativeProcessFreeBSD::PtraceWrapper(), lldb_private::process_linux::NativeProcessLinux::PtraceWrapper(), lldb_private::process_netbsd::NativeProcessNetBSD::PtraceWrapper(), lldb_private::platform_android::AdbSyncService::PullFileChunk(), lldb_private::platform_android::AdbSyncService::PullFileImpl(), lldb_private::platform_android::AdbSyncService::PushFileImpl(), PushToLinuxGuardedControlStack(), lldb_private::ModuleCache::Put(), lldb_private::Platform::PutFile(), lldb_private::platform_android::PlatformAndroid::PutFile(), lldb::SBProcess::PutSTDIN(), lldb_private::Process::PutSTDIN(), lldb_private::process_gdb_remote::ProcessGDBRemote::PutSTDIN(), lldb::SBThreadPlan::QueueThreadPlanForRunToAddress(), lldb::SBThreadPlan::QueueThreadPlanForRunToAddress(), lldb::SBThreadPlan::QueueThreadPlanForStepInRange(), lldb::SBThreadPlan::QueueThreadPlanForStepInRange(), lldb::SBThreadPlan::QueueThreadPlanForStepOut(), lldb::SBThreadPlan::QueueThreadPlanForStepOut(), lldb::SBThreadPlan::QueueThreadPlanForStepOverRange(), lldb::SBThreadPlan::QueueThreadPlanForStepOverRange(), lldb::SBThreadPlan::QueueThreadPlanForStepScripted(), lldb::SBThreadPlan::QueueThreadPlanForStepScripted(), lldb::SBThreadPlan::QueueThreadPlanForStepScripted(), lldb::SBThreadPlan::QueueThreadPlanForStepSingleInstruction(), lldb::SBFile::Read(), lldb_private::ClassDescriptorV2::class_ro_t::Read(), lldb_private::ClassDescriptorV2::class_rw_t::Read(), lldb_private::ClassDescriptorV2::ivar_list_t::Read(), lldb_private::ClassDescriptorV2::ivar_t::Read(), lldb_private::ClassDescriptorV2::method_list_t::Read(), lldb_private::ClassDescriptorV2::method_t::Read(), lldb_private::ClassDescriptorV2::objc_class_t::Read(), lldb_private::ClassDescriptorV2::relative_list_entry_t::Read(), lldb_private::ClassDescriptorV2::relative_list_list_t::Read(), lldb_private::ConnectionFileDescriptor::Read(), lldb_private::MemoryCache::Read(), lldb_private::NativeFile::Read(), lldb_private::NativeFile::Read(), lldb_private::PipePosix::Read(), lldb_private::Socket::Read(), lldb_private::ClassDescriptorV2::Read_class_row(), read_register_u128(), ReadAdbMessage(), ReadAllBytes(), DynamicLoaderMacOSXDYLD::ReadAllImageInfosStructure(), DynamicLoaderFreeBSDKernel::ReadAllKmods(), RegisterContextMemory::ReadAllRegisterValues(), ReadBytes(), lldb_private::Process::ReadCStringFromMemory(), lldb_private::Process::ReadCStringFromMemory(), lldb_private::Target::ReadCStringFromMemory(), lldb_private::Target::ReadCStringFromMemory(), DynamicLoaderFreeBSDKernel::ReadELFHeader(), lldb_private::formatters::ReadEncodedBufferAndDumpToStream(), lldb_private::FileCache::ReadFile(), lldb_private::Platform::ReadFile(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::ReadFile(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ReadFile(), lldb_private::RemoteAwarePlatform::ReadFile(), lldb_private::RegisterContextUnwind::ReadFrameAddress(), lldb_private::Type::ReadFromMemory(), DynamicLoaderMacOSXDYLD::ReadImageInfos(), lldb_private::Target::ReadInstructions(), ReadInt(), ReadIntegerArgument(), ReadIntegerArgument(), ReadIntegerArgument(), ReadIntegerArgument(), ReadIntegerArgument(), ReadIntegerArgument(), ReadIntegerArgument(), JITLoaderGDB::ReadJITDescriptorImpl(), ReadJITEntry(), DynamicLoaderDarwinKernel::ReadKextSummaries(), DynamicLoaderDarwinKernel::ReadKextSummaryHeader(), DynamicLoaderFreeBSDKernel::ReadKmodsListHeader(), SystemRuntimeMacOSX::ReadLibdispatchOffsets(), SystemRuntimeMacOSX::ReadLibdispatchTSDIndexes(), SystemRuntimeMacOSX::ReadLibpthreadOffsets(), lldb_private::FileSystem::Readlink(), DynamicLoaderDarwinKernel::ReadMachHeader(), DynamicLoaderMacOSXDYLD::ReadMachHeader(), lldb::SBTarget::ReadMemory(), lldb_private::IRMemoryMap::ReadMemory(), lldb_private::minidump::ProcessMinidump::ReadMemory(), lldb_private::ObjectFile::ReadMemory(), lldb_private::Process::ReadMemory(), lldb_private::process_freebsd::NativeProcessFreeBSD::ReadMemory(), lldb_private::process_linux::NativeProcessLinux::ReadMemory(), lldb_private::process_netbsd::NativeProcessNetBSD::ReadMemory(), lldb_private::ProcessDebugger::ReadMemory(), lldb_private::ProcessTrace::ReadMemory(), lldb_private::Target::ReadMemory(), lldb_private::wasm::ProcessWasm::ReadMemory(), ProcessElfCore::ReadMemory(), ProcessMachCore::ReadMemory(), lldb_private::ScriptedProcessInterface::ReadMemoryAtAddress(), lldb_private::ScriptedProcessPythonInterface::ReadMemoryAtAddress(), lldb_private::EmulateInstruction::ReadMemoryFrame(), lldb_private::Target::ReadMemoryFromFileCache(), lldb_private::Process::ReadMemoryFromInferior(), lldb_private::Process::ReadMemoryInChunks(), DynamicLoaderFreeBSDKernel::KModImageInfo::ReadMemoryModule(), lldb_private::process_gdb_remote::ProcessGDBRemote::ReadMemoryRanges(), lldb_private::process_linux::NativeProcessLinux::ReadMemoryTags(), lldb_private::NativeProcessProtocol::ReadMemoryWithoutTrap(), lldb_private::platform_android::AdbClient::ReadMessageStream(), lldb_private::Process::ReadModuleFromMemory(), lldb_private::minidump::ProcessMinidump::ReadModuleList(), lldb_private::ValueObject::ReadPointedString(), DYLDRendezvous::ReadPointer(), HexagonDYLDRendezvous::ReadPointer(), lldb_private::DynamicLoader::ReadPointer(), lldb_private::IRMemoryMap::ReadPointerFromMemory(), lldb_private::Process::ReadPointerFromMemory(), lldb_private::Target::ReadPointerFromMemory(), ReadProcessMemory(), lldb::SBData::ReadRawData(), lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::ReadRegions(), lldb_private::minidump::RegisterContextMinidump_ARM64::ReadRegister(), lldb_private::minidump::RegisterContextMinidump_ARM::ReadRegister(), lldb_private::process_gdb_remote::GDBRemoteRegisterContext::ReadRegister(), lldb_private::wasm::RegisterContextWasm::ReadRegister(), RegisterContextCorePOSIX_arm64::ReadRegister(), RegisterContextCorePOSIX_loongarch64::ReadRegister(), RegisterContextCorePOSIX_riscv32::ReadRegister(), RegisterContextCorePOSIX_riscv64::ReadRegister(), RegisterContextCorePOSIX_x86::ReadRegister(), RegisterContextFreeBSDKernelCore_arm64::ReadRegister(), RegisterContextFreeBSDKernelCore_i386::ReadRegister(), RegisterContextFreeBSDKernelCore_x86_64::ReadRegister(), lldb_private::NativeRegisterContext::ReadRegisterAsUnsigned(), ReadRegisterCallback(), lldb_private::NativeRegisterContext::ReadRegisterValueFromMemory(), lldb_private::RegisterContext::ReadRegisterValueFromMemory(), lldb_private::RegisterContextUnwind::ReadRegisterValueFromRegisterLocation(), ReadResponseStatus(), lldb_private::IRMemoryMap::ReadScalarFromMemory(), lldb_private::Process::ReadScalarIntegerFromMemory(), lldb_private::Target::ReadScalarIntegerFromMemory(), lldb_private::ObjectFile::ReadSectionData(), ObjectFileELF::ReadSectionData(), lldb_private::Process::ReadSignedIntegerFromMemory(), lldb_private::Target::ReadSignedIntegerFromMemory(), DYLDRendezvous::ReadStringFromMemory(), HexagonDYLDRendezvous::ReadStringFromMemory(), lldb_private::Target::ReadStringFromMemory(), lldb_private::NativeProcessELF::ReadSVR4LibraryInfo(), lldb_private::platform_android::AdbSyncService::ReadSyncHeader(), lldb_private::ThreadedCommunication::ReadThread(), lldb_private::Process::ReadUnsignedIntegerFromMemory(), lldb_private::Target::ReadUnsignedIntegerFromMemory(), lldb_private::DynamicLoader::ReadUnsignedIntWithSizeInBytes(), DYLDRendezvous::ReadWord(), HexagonDYLDRendezvous::ReadWord(), MinidumpFileBuilder::ReadWriteMemoryInChunks(), lldb_private::ScriptedPythonInterface::ReassignPtrsOrRefsArgs(), lldb_private::AbortWithPayloadFrameRecognizer::RecognizeFrame(), RecurseCopy_Callback(), ObjectFileELF::RefineModuleDetailsFromNote(), lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::RefreshTrampolines(), lldb_private::RegisterContextUnifiedCore::RegisterContextUnifiedCore(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::RegisterMemberFunctionHandler(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::RegisterPacketHandlers(), lldb_private::MainLoopBase::RegisterReadObject(), lldb_private::MainLoopPosix::RegisterReadObject(), lldb_private::MainLoopWindows::RegisterReadObject(), lldb::SBTarget::RegisterScriptedFrameProvider(), lldb_private::MainLoopPosix::RegisterSignal(), lldb_private::process_freebsd::NativeProcessFreeBSD::ReinitializeThreads(), lldb_private::process_netbsd::NativeProcessNetBSD::ReinitializeThreads(), lldb::SBProcess::RemoteAttachToProcessWithID(), lldb::SBProcess::RemoteLaunch(), RemoteNXMapTable::RemoteNXMapTable(), lldb_private::NativeProcessProtocol::RemoveHardwareBreakpoint(), lldb::SBTarget::RemoveScriptedFrameProvider(), lldb_private::NativeProcessProtocol::RemoveSoftwareBreakpoint(), lldb_private::NativeProcessProtocol::RemoveWatchpoint(), replace_all(), lldb_private::BreakpointLocationList::ResolveAllBreakpointSites(), lldb_private::platform_android::AdbClient::ResolveDeviceID(), lldb_private::Platform::ResolveExecutable(), DynamicLoaderPOSIXDYLD::ResolveExecutableModule(), lldb_private::Process::ResolveIndirectFunction(), lldb_private::ScriptedBreakpointPythonInterface::ResolverCallback(), DYLDRendezvous::ResolveRendezvousAddress(), ResolveRendezvousAddress(), lldb_private::Platform::ResolveSymbolFile(), lldb_private::Value::ResolveValue(), lldb::SBThread::Resume(), lldb::SBThread::Resume(), lldb_private::NativeProcessWindows::Resume(), lldb_private::Process::Resume(), lldb_private::process_linux::NativeProcessLinux::Resume(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::ResumeProcess(), lldb_private::Process::ResumeSynchronous(), lldb_private::ReportRetriever::RetrieveReportData(), RetrieveString(), RetrieveString(), lldb_private::ScriptedPythonInterface::ReverseTransform(), lldb_private::ScriptedPythonInterface::ReverseTransform(), lldb_private::ScriptedPythonInterface::ReverseTransform(), IOHandlerProcessSTDIO::Run(), lldb_private::Lua::Run(), lldb_private::MainLoopPosix::Run(), lldb_private::MainLoopWindows::Run(), lldb_private::REPL::RunLoop(), lldb_private::Process::RunPrivateStateThread(), lldb::SBDebugger::RunREPL(), lldb_private::ScriptInterpreter::RunScriptBasedCommand(), lldb_private::ScriptInterpreter::RunScriptBasedCommand(), lldb_private::ScriptInterpreterPythonImpl::RunScriptBasedCommand(), lldb_private::ScriptInterpreter::RunScriptBasedParsedCommand(), lldb_private::ScriptInterpreterPythonImpl::RunScriptBasedParsedCommand(), lldb_private::ScriptInterpreter::RunScriptFormatKeyword(), lldb_private::ScriptInterpreter::RunScriptFormatKeyword(), lldb_private::ScriptInterpreter::RunScriptFormatKeyword(), lldb_private::ScriptInterpreter::RunScriptFormatKeyword(), lldb_private::ScriptInterpreter::RunScriptFormatKeyword(), lldb_private::ScriptInterpreterPythonImpl::RunScriptFormatKeyword(), lldb_private::ScriptInterpreterPythonImpl::RunScriptFormatKeyword(), RunScriptFormatKeyword(), lldb_private::Host::RunShellCommand(), lldb_private::Target::RunStopHooks(), lldb_private::Process::RunThreadPlan(), lldb::SBThread::RunToAddress(), lldb::SBThread::RunToAddress(), lldb::SBProcess::SaveCore(), lldb::SBProcess::SaveCore(), lldb_private::PluginManager::SaveCore(), lldb_private::process_freebsd::NativeProcessFreeBSD::SaveCore(), lldb_private::process_gdb_remote::ProcessGDBRemote::SaveCore(), lldb_private::process_netbsd::NativeProcessNetBSD::SaveCore(), ObjectFileMachO::SaveCore(), ObjectFileMinidump::SaveCore(), ObjectFilePECOFF::SaveCore(), lldb_private::SaveMiniDump(), lldb::SBTrace::SaveToDisk(), lldb_private::CommandInterpreter::SaveTranscript(), lldb::SBFormat::SBFormat(), lldb::SBModule::SBModule(), lldb_private::CompactUnwindInfo::ScanIndex(), lldb_private::ScriptedProcess::ScriptedProcess(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointLocationSP >(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointLocationSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointSP >(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::DataExtractorSP >(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::DataExtractorSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::DescriptionLevel >(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::DescriptionLevel >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ExecutionContextRefSP >(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ExecutionContextRefSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessAttachInfoSP >(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessAttachInfoSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessLaunchInfoSP >(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessLaunchInfoSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameListSP >(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameListSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameSP >(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StreamSP >(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StreamSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ThreadSP >(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ThreadSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectListSP >(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectListSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectSP >(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectSP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< StructuredData::ArraySP >(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< StructuredData::ArraySP >(), ScriptedPythonInterface::ExtractValueFromPythonObject< StructuredData::DictionarySP >(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< StructuredData::DictionarySP >(), lldb_private::BreakpointResolverAddress::SearchCallback(), SelectHelper::Select(), SelectTargetDevice(), SendAdbMessage(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendEnvironmentPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendErrorResponse(), lldb_private::process_gdb_remote::ProcessGDBRemote::SendEventData(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendLaunchArchPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendLaunchEventDataPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::SendProcessOutput(), CommunicationKDP::SendRawRequest(), CommunicationKDP::SendRequestReadMemory(), CommunicationKDP::SendRequestReadRegisters(), CommunicationKDP::SendRequestWriteMemory(), CommunicationKDP::SendRequestWriteRegisters(), lldb_private::platform_android::AdbSyncService::SendSyncRequest(), lldb_private::Target::SerializeBreakpointsToFile(), lldb_private::Target::SetArchitecture(), lldb_private::OptionValueArray::SetArgs(), lldb_private::OptionValueDictionary::SetArgs(), lldb::SBExpressionOptions::SetBooleanLanguageOption(), lldb_private::ScriptInterpreter::SetBreakpointCommandCallback(), lldb_private::ScriptInterpreterPythonImpl::SetBreakpointCommandCallback(), lldb_private::ScriptInterpreterPythonImpl::SetBreakpointCommandCallback(), lldb_private::ScriptInterpreter::SetBreakpointCommandCallbackFunction(), lldb_private::Watchpoint::SetCondition(), lldb_private::OptionValueString::SetCurrentValue(), lldb::SBData::SetData(), lldb::SBValue::SetData(), lldb_private::ValueObject::SetData(), lldb_private::ValueObjectDynamicValue::SetData(), lldb_private::ValueObjectRegister::SetData(), lldb_private::ValueObjectVariable::SetData(), lldb::SBData::SetDataWithOwnership(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetDetachOnError(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetDisableASLR(), lldb_private::plugin::dwarf::DWARFUnit::SetDwoError(), lldb_private::BreakpointLocation::SetEnabled(), lldb::SBCommandReturnObject::SetError(), lldb_private::CommandReturnObject::SetError(), lldb_private::CommandReturnObject::SetError(), ValueListImpl::SetError(), lldb::SBDebugger::SetErrorFile(), SetErrorWithJSON(), lldb_private::Platform::SetFilePermissions(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::SetFilePermissions(), lldb::SBStructuredData::SetFromJSON(), lldb_private::RegisterValue::SetFromMemoryData(), lldb_private::NativeRegisterContextDBReg::SetHardwareBreakpoint(), lldb_private::process_freebsd::NativeThreadFreeBSD::SetHardwareBreakpoint(), lldb_private::process_linux::NativeThreadLinux::SetHardwareBreakpoint(), lldb_private::process_netbsd::NativeThreadNetBSD::SetHardwareBreakpoint(), lldb_private::NativeRegisterContextDBReg::SetHardwareWatchpoint(), lldb_private::NativeRegisterContextDBReg_x86::SetHardwareWatchpoint(), lldb_private::NativeRegisterContextDBReg_x86::SetHardwareWatchpointWithIndex(), lldb::SBDebugger::SetInputFile(), EmulateInstructionMIPS::SetInstruction(), lldb::SBDebugger::SetInternalVariable(), lldb_private::Breakpoint::SetIsHardware(), lldb_private::python::PythonDictionary::SetItemForKey(), lldb_private::Socket::SetLastError(), lldb::SBPlatform::SetLocateModuleCallback(), CommandObjectScriptingObjectParsed::CommandOptions::SetOptionsFromArray(), BreakpointAccessOptionGroup::SetOptionValue(), BreakpointDummyOptionGroup::SetOptionValue(), BreakpointNameOptionGroup::SetOptionValue(), BreakpointNamesOptionGroup::SetOptionValue(), CommandObjectBreakpointAddAddress::CommandOptions::SetOptionValue(), CommandObjectBreakpointAddException::CommandOptions::SetOptionValue(), CommandObjectBreakpointAddFile::CommandOptions::SetOptionValue(), CommandObjectBreakpointAddName::CommandOptions::SetOptionValue(), CommandObjectBreakpointAddPattern::CommandOptions::SetOptionValue(), CommandObjectBreakpointAddScripted::CommandOptions::SetOptionValue(), CommandObjectBreakpointClear::CommandOptions::SetOptionValue(), CommandObjectBreakpointCommandDelete::CommandOptions::SetOptionValue(), CommandObjectBreakpointDelete::CommandOptions::SetOptionValue(), CommandObjectBreakpointList::CommandOptions::SetOptionValue(), CommandObjectBreakpointRead::CommandOptions::SetOptionValue(), CommandObjectBreakpointSet::CommandOptions::SetOptionValue(), CommandObjectBreakpointWrite::CommandOptions::SetOptionValue(), CommandObjectCommandsAlias::CommandOptions::SetOptionValue(), CommandObjectCommandsContainerAdd::CommandOptions::SetOptionValue(), CommandObjectCommandsScriptAdd::CommandOptions::SetOptionValue(), CommandObjectCommandsScriptImport::CommandOptions::SetOptionValue(), CommandObjectCommandsSource::CommandOptions::SetOptionValue(), CommandObjectDiagnosticsDump::CommandOptions::SetOptionValue(), CommandObjectFrameDiagnose::CommandOptions::SetOptionValue(), CommandObjectFrameRecognizerAdd::CommandOptions::SetOptionValue(), CommandObjectFrameSelect::CommandOptions::SetOptionValue(), CommandObjectLogDump::CommandOptions::SetOptionValue(), CommandObjectLogEnable::CommandOptions::SetOptionValue(), CommandObjectMemoryFind::OptionGroupFindMemory::SetOptionValue(), CommandObjectMemoryWrite::OptionGroupWriteMemory::SetOptionValue(), CommandObjectObjC_ClassTable_Dump::CommandOptions::SetOptionValue(), CommandObjectPlatformFRead::CommandOptions::SetOptionValue(), CommandObjectPlatformFWrite::CommandOptions::SetOptionValue(), CommandObjectPlatformProcessList::CommandOptions::SetOptionValue(), CommandObjectPlatformShell::CommandOptions::SetOptionValue(), CommandObjectProcessConnect::CommandOptions::SetOptionValue(), CommandObjectProcessContinue::CommandOptions::SetOptionValue(), CommandObjectProcessDetach::CommandOptions::SetOptionValue(), CommandObjectProcessHandle::CommandOptions::SetOptionValue(), CommandObjectProcessLoad::CommandOptions::SetOptionValue(), CommandObjectProcessSaveCore::CommandOptions::SetOptionValue(), CommandObjectRegisterRead::CommandOptions::SetOptionValue(), CommandObjectScriptingExtensionList::CommandOptions::SetOptionValue(), CommandObjectScriptingObjectParsed::CommandOptions::SetOptionValue(), CommandObjectScriptingRun::CommandOptions::SetOptionValue(), CommandObjectSessionHistory::CommandOptions::SetOptionValue(), CommandObjectSettingsRead::CommandOptions::SetOptionValue(), CommandObjectSettingsWrite::CommandOptions::SetOptionValue(), CommandObjectSourceInfo::CommandOptions::SetOptionValue(), CommandObjectSourceList::CommandOptions::SetOptionValue(), CommandObjectStatsDump::CommandOptions::SetOptionValue(), CommandObjectTargetModulesDumpSeparateDebugInfoFiles::CommandOptions::SetOptionValue(), CommandObjectTargetModulesDumpSymtab::CommandOptions::SetOptionValue(), CommandObjectTargetModulesList::CommandOptions::SetOptionValue(), CommandObjectTargetModulesLookup::CommandOptions::SetOptionValue(), CommandObjectTargetModulesShowUnwind::CommandOptions::SetOptionValue(), CommandObjectTargetStopHookAdd::CommandOptions::SetOptionValue(), CommandObjectTargetStopHookList::CommandOptions::SetOptionValue(), CommandObjectThreadBacktrace::CommandOptions::SetOptionValue(), CommandObjectThreadInfo::CommandOptions::SetOptionValue(), CommandObjectThreadJump::CommandOptions::SetOptionValue(), CommandObjectThreadReturn::CommandOptions::SetOptionValue(), CommandObjectThreadUntil::CommandOptions::SetOptionValue(), CommandObjectTraceDump::CommandOptions::SetOptionValue(), CommandObjectTraceDumpFunctionCalls::CommandOptions::SetOptionValue(), CommandObjectTraceDumpInfo::CommandOptions::SetOptionValue(), CommandObjectTraceDumpInstructions::CommandOptions::SetOptionValue(), CommandObjectTraceLoad::CommandOptions::SetOptionValue(), CommandObjectTraceSave::CommandOptions::SetOptionValue(), CommandObjectTraceSchema::CommandOptions::SetOptionValue(), CommandObjectTypeFormatAdd::CommandOptions::SetOptionValue(), CommandObjectTypeFormatterClear::CommandOptions::SetOptionValue(), CommandObjectTypeFormatterDelete::CommandOptions::SetOptionValue(), CommandObjectTypeFormatterList< FormatterType >::CommandOptions::SetOptionValue(), CommandObjectTypeLookup::CommandOptions::SetOptionValue(), CommandObjectTypeSummaryAdd::CommandOptions::SetOptionValue(), CommandObjectTypeSynthAdd::CommandOptions::SetOptionValue(), CommandObjectWatchpointIgnore::CommandOptions::SetOptionValue(), CommandObjectWatchpointList::CommandOptions::SetOptionValue(), CommandObjectWatchpointModify::CommandOptions::SetOptionValue(), lldb_private::BreakpointOptionGroup::SetOptionValue(), lldb_private::CommandObjectDisassemble::CommandOptions::SetOptionValue(), lldb_private::CommandObjectExpression::CommandOptions::SetOptionValue(), lldb_private::CommandObjectHelp::CommandOptions::SetOptionValue(), lldb_private::CommandObjectVersion::CommandOptions::SetOptionValue(), lldb_private::CommandOptionsProcessAttach::SetOptionValue(), lldb_private::CommandOptionsProcessLaunch::SetOptionValue(), lldb_private::ctf::CommandObjectThreadTraceExportCTF::CommandOptions::SetOptionValue(), lldb_private::OptionGroupArchitecture::SetOptionValue(), lldb_private::OptionGroupBoolean::SetOptionValue(), lldb_private::OptionGroupFile::SetOptionValue(), lldb_private::OptionGroupFileList::SetOptionValue(), lldb_private::OptionGroupFormat::SetOptionValue(), lldb_private::OptionGroupOptions::SetOptionValue(), lldb_private::OptionGroupOutputFile::SetOptionValue(), lldb_private::OptionGroupPlatform::SetOptionValue(), lldb_private::OptionGroupPlatform::SetOptionValue(), lldb_private::OptionGroupPlatformCaching::SetOptionValue(), lldb_private::OptionGroupPlatformRSync::SetOptionValue(), lldb_private::OptionGroupPlatformSSH::SetOptionValue(), lldb_private::OptionGroupPythonClassWithDict::SetOptionValue(), lldb_private::OptionGroupString::SetOptionValue(), lldb_private::OptionGroupUInt64::SetOptionValue(), lldb_private::OptionGroupUUID::SetOptionValue(), lldb_private::OptionGroupValueObjectDisplay::SetOptionValue(), lldb_private::OptionGroupVariable::SetOptionValue(), lldb_private::OptionGroupWatchpoint::SetOptionValue(), lldb_private::trace_intel_pt::CommandObjectProcessTraceStartIntelPT::CommandOptions::SetOptionValue(), lldb_private::trace_intel_pt::CommandObjectThreadTraceStartIntelPT::CommandOptions::SetOptionValue(), OptionGroupDependents::SetOptionValue(), OptionGroupReadMemory::SetOptionValue(), OptionPermissions::SetOptionValue(), sddarwinlog_private::EnableOptions::SetOptionValue(), ThreadStepScopeOptionGroup::SetOptionValue(), lldb::SBDebugger::SetOutputFile(), lldb_private::SaveCoreOptions::SetPluginName(), lldb_private::platform_android::AdbClient::SetPortForwarding(), lldb_private::platform_android::AdbClient::SetPortForwarding(), lldb_private::SaveCoreOptions::SetProcess(), lldb_private::Debugger::SetPropertyValue(), ABIMacOSX_arm64::SetReturnValueObject(), ABIMacOSX_arm::SetReturnValueObject(), ABIMacOSX_i386::SetReturnValueObject(), ABISysV_arm64::SetReturnValueObject(), ABISysV_arm::SetReturnValueObject(), ABISysV_hexagon::SetReturnValueObject(), ABISysV_i386::SetReturnValueObject(), ABISysV_mips64::SetReturnValueObject(), ABISysV_mips::SetReturnValueObject(), ABISysV_ppc64::SetReturnValueObject(), ABISysV_ppc::SetReturnValueObject(), ABISysV_s390x::SetReturnValueObject(), ABISysV_x86_64::SetReturnValueObject(), ABIWindows_x86_64::SetReturnValueObject(), lldb_private::Target::StopHookScripted::SetScriptCallback(), lldb::SBBreakpoint::SetScriptCallbackBody(), lldb::SBBreakpointLocation::SetScriptCallbackBody(), lldb::SBBreakpointName::SetScriptCallbackBody(), lldb::SBBreakpoint::SetScriptCallbackFunction(), lldb::SBBreakpointLocation::SetScriptCallbackFunction(), lldb::SBBreakpointName::SetScriptCallbackFunction(), SetSoftwareBreakpoint(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetSTDERR(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetSTDIN(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::SetSTDIOFileDescriptor(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetSTDOUT(), lldb_private::OptionValueDictionary::SetSubValue(), lldb_private::OptionValueProperties::SetSubValue(), lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo(), lldb_private::RegisterValue::SetType(), lldb_private::AppleObjCTrampolineHandler::SetupDispatchFunction(), lldb_private::AppleGetItemInfoHandler::SetupGetItemInfoFunction(), lldb_private::AppleGetPendingItemsHandler::SetupGetPendingItemsFunction(), lldb_private::AppleGetQueuesHandler::SetupGetQueuesFunction(), lldb_private::AppleGetThreadItemInfoHandler::SetupGetThreadItemInfoFunction(), lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::VTableRegion::SetUpRegion(), lldb_private::NativeProcessSoftwareSingleStep::SetupSoftwareSingleStepping(), lldb_private::platform_android::AdbSyncService::SetupSyncConnection(), lldb_private::Scalar::SetValueFromCString(), lldb_private::ValueObject::SetValueFromCString(), lldb_private::ValueObjectDynamicValue::SetValueFromCString(), lldb_private::ValueObjectRegister::SetValueFromCString(), lldb_private::ValueObjectSynthetic::SetValueFromCString(), lldb_private::ValueObjectVariable::SetValueFromCString(), lldb_private::RegisterValue::SetValueFromData(), lldb_private::Scalar::SetValueFromData(), lldb_private::ValueObject::SetValueFromInteger(), lldb_private::ValueObject::SetValueFromInteger(), lldb_private::OptionValue::SetValueFromString(), lldb_private::OptionValueArch::SetValueFromString(), lldb_private::OptionValueArray::SetValueFromString(), lldb_private::OptionValueBoolean::SetValueFromString(), lldb_private::OptionValueChar::SetValueFromString(), lldb_private::OptionValueDictionary::SetValueFromString(), lldb_private::OptionValueEnumeration::SetValueFromString(), lldb_private::OptionValueFileColonLine::SetValueFromString(), lldb_private::OptionValueFileSpec::SetValueFromString(), lldb_private::OptionValueFileSpecList::SetValueFromString(), lldb_private::OptionValueFormat::SetValueFromString(), lldb_private::OptionValueFormatEntity::SetValueFromString(), lldb_private::OptionValueLanguage::SetValueFromString(), lldb_private::OptionValuePathMappings::SetValueFromString(), lldb_private::OptionValueProperties::SetValueFromString(), lldb_private::OptionValueRegex::SetValueFromString(), lldb_private::OptionValueSInt64::SetValueFromString(), lldb_private::OptionValueString::SetValueFromString(), lldb_private::OptionValueUInt64::SetValueFromString(), lldb_private::OptionValueUUID::SetValueFromString(), lldb_private::RegisterValue::SetValueFromString(), lldb_private::NativeThreadWindows::SetWatchpoint(), lldb_private::process_freebsd::NativeThreadFreeBSD::SetWatchpoint(), lldb_private::process_linux::NativeThreadLinux::SetWatchpoint(), lldb_private::process_netbsd::NativeThreadNetBSD::SetWatchpoint(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SetWorkingDir(), lldb_private::SharedSocket::SharedSocket(), lldb_private::platform_android::AdbClient::Shell(), lldb_private::platform_android::AdbClient::ShellToFile(), lldb_private::AppleThreadPlanStepThroughDirectDispatch::ShouldStop(), lldb_private::ScriptedThreadPlanPythonInterface::ShouldStop(), lldb_private::StopInfoWatchpoint::ShouldStopSynchronous(), lldb_private::process_freebsd::NativeProcessFreeBSD::SigchldHandler(), lldb_private::process_netbsd::NativeProcessNetBSD::SigchldHandler(), lldb_private::HostProcessPosix::Signal(), lldb_private::NativeProcessWindows::Signal(), lldb_private::Process::Signal(), lldb_private::process_freebsd::NativeProcessFreeBSD::Signal(), lldb_private::process_linux::NativeProcessLinux::Signal(), lldb_private::process_netbsd::NativeProcessNetBSD::Signal(), lldb_private::process_linux::NativeProcessLinux::SignalIfAllThreadsStopped(), CoreSimulatorSupport::Device::Spawn(), lldb::SBTrace::Start(), lldb::SBTrace::Start(), lldb_private::mcp::ProtocolServerMCP::Start(), lldb_private::process_linux::IntelPTPerThreadProcessTrace::Start(), lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::StartSTDIOForwarding(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::Stat(), lldb_private::platform_android::AdbSyncService::StatImpl(), lldb_private::Status::Status(), lldb_private::Thread::StepIn(), lldb::SBThread::StepInstruction(), lldb::SBThread::StepInstruction(), lldb::SBThread::StepInto(), lldb::SBThread::StepInto(), lldb::SBThread::StepOut(), lldb::SBThread::StepOut(), lldb_private::Thread::StepOut(), lldb::SBThread::StepOutOfFrame(), lldb::SBThread::StepOutOfFrame(), lldb::SBThread::StepOver(), lldb::SBThread::StepOver(), lldb_private::Thread::StepOver(), lldb::SBThread::StepUsingScriptedThreadPlan(), lldb::SBTrace::Stop(), lldb::SBTrace::Stop(), lldb_private::DebuggerThread::StopDebugging(), lldb_private::Process::StopForDestroyOrDetach(), lldb_private::process_netbsd::NativeProcessNetBSD::StopProcess(), lldb_private::ThreadedCommunication::StopReadThread(), lldb_private::NativeProcessWindows::StopThread(), lldb_private::BreakpointID::StringIsBreakpointName(), lldb_private::npdb::SymbolFileNativePDB::StripMangledFunctionName(), lldb::SBThread::Suspend(), lldb::SBThread::Suspend(), lldb_private::FileSystem::Symlink(), lldb_private::NativeFile::Sync(), lldb_private::Socket::TcpConnect(), lldb_private::Socket::TcpListen(), lldb_private::HostProcessWindows::Terminate(), lldb_private::mcp::ProtocolServerMCP::Terminate(), lldb_private::ProtocolServer::Terminate(), lldb_private::ThreadPlanCallFunction::ThreadPlanCallFunction(), lldb_private::OptionArgParser::ToFormat(), lldb_protocol::mcp::toJSON(), lldb_private::OptionArgParser::ToOptionEnum(), lldb_private::process_linux::IntelPTCollector::TraceStart(), lldb_private::process_linux::IntelPTCollector::TraceStop(), lldb_private::ScriptedPythonInterface::TransformBack(), lldb_private::FormatterBytecode::TypeCheck(), lldb_private::FormatterBytecode::TypeCheck(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::Unlink(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::Unlink(), PlatformPOSIX::UnloadImage(), lldb_private::LockFileBase::Unlock(), lldb_private::Thread::UnwindInnermostExpression(), lldb_private::BytecodeSyntheticChildren::FrontEnd::Update(), lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd::Update(), lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::Update(), lldb_private::formatters::GenericNSArrayMSyntheticFrontEnd< D32, D64 >::Update(), lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< D32, D64 >::Update(), lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::Update(), lldb_private::formatters::LibcxxStdRangesRefViewSyntheticFrontEnd::Update(), lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::Update(), lldb_private::formatters::NSDictionaryISyntheticFrontEnd::Update(), lldb_private::formatters::NSSetISyntheticFrontEnd::Update(), NSErrorSyntheticFrontEnd::Update(), lldb_private::process_gdb_remote::ProcessGDBRemote::UpdateAutomaticSignalFiltering(), DYLDRendezvous::UpdateBaseAddrIfNecessary(), lldb_private::plugin::dwarf::SymbolFileDWARF::UpdateExternalModuleListIfNeeded(), lldb_private::CFBasicHash::UpdateFor(), lldb_private::AppleObjCRuntimeV2::SharedCacheImageHeaders::UpdateIfNeeded(), lldb_private::AppleObjCRuntimeV2::DynamicClassInfoExtractor::UpdateISAToDescriptorMap(), lldb_private::AppleObjCRuntimeV1::UpdateISAToDescriptorMapIfNeeded(), lldb_private::AppleThreadPlanStepThroughObjCTrampoline::ValidatePlan(), lldb_private::ScriptedThreadPlan::ValidatePlan(), lldb_private::ThreadPlan::ValidatePlan(), lldb_private::ThreadPlanBase::ValidatePlan(), lldb_private::ThreadPlanCallFunction::ValidatePlan(), lldb_private::ThreadPlanCallOnFunctionExit::ValidatePlan(), lldb_private::ThreadPlanNull::ValidatePlan(), lldb_private::ThreadPlanRunToAddress::ValidatePlan(), lldb_private::ThreadPlanSingleThreadTimeout::ValidatePlan(), lldb_private::ThreadPlanStepInstruction::ValidatePlan(), lldb_private::ThreadPlanStepOut::ValidatePlan(), lldb_private::ThreadPlanStepOverBreakpoint::ValidatePlan(), lldb_private::ThreadPlanStepRange::ValidatePlan(), lldb_private::ThreadPlanStepThrough::ValidatePlan(), lldb_private::ThreadPlanStepUntil::ValidatePlan(), lldb_private::ValueObjectConstResult::ValueObjectConstResult(), lldb_private::ValueObjectConstResult::ValueObjectConstResultImpl, lldb_private::VASprintf(), lldb_private::dil::Interpreter::Visit(), lldb_private::dil::Interpreter::Visit(), lldb_private::process_gdb_remote::GDBRemoteCommunication::WaitForPacketNoLock(), CommunicationKDP::WaitForPacketWithTimeoutMicroSecondsNoLock(), WaitPid(), WaitPid(), lldb_private::AppleObjCRuntimeV2::WarnIfNoClassesCached(), lldb::SBValue::Watch(), lldb::SBValue::Watch(), lldb::SBTarget::WatchAddress(), lldb_private::Watchpoint::WatchedValueReportable(), lldb::SBTarget::WatchpointCreateByAddress(), lldb::SBValue::WatchPointee(), lldb_private::formatters::WCharSummaryProvider(), lldb_private::process_gdb_remote::ProcessGDBRemote::WillLaunchOrAttach(), lldb::SBFile::Write(), lldb_private::ConnectionFileDescriptor::Write(), lldb_private::NativeFile::Write(), lldb_private::NativeFile::Write(), lldb_private::PipePosix::Write(), lldb_private::Socket::Write(), lldb_protocol::mcp::ServerInfo::Write(), RegisterContextMemory::WriteAllRegisterValues(), lldb_private::FileCache::WriteFile(), lldb_private::Platform::WriteFile(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::WriteFile(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteFile(), lldb_private::RemoteAwarePlatform::WriteFile(), lldb_private::FunctionCaller::WriteFunctionArguments(), lldb_private::IRMemoryMap::WriteMemory(), lldb_private::Process::WriteMemory(), lldb_private::process_freebsd::NativeProcessFreeBSD::WriteMemory(), lldb_private::process_linux::NativeProcessLinux::WriteMemory(), lldb_private::process_netbsd::NativeProcessNetBSD::WriteMemory(), lldb_private::ProcessDebugger::WriteMemory(), lldb_private::ScriptedProcessInterface::WriteMemoryAtAddress(), lldb_private::ScriptedProcessPythonInterface::WriteMemoryAtAddress(), lldb_private::EmulateInstruction::WriteMemoryFrame(), lldb_private::Process::WriteMemoryPrivate(), lldb_private::process_linux::NativeProcessLinux::WriteMemoryTags(), lldb_private::IRExecutionUnit::WriteNow(), lldb_private::Process::WriteObjectFile(), lldb_private::process_gdb_remote::ProcessGDBRemote::WriteObjectFile(), lldb_private::IRMemoryMap::WritePointerToMemory(), lldb_private::Process::WritePointerToMemory(), RegisterContextMemory::WriteRegister(), lldb_private::process_linux::NativeRegisterContextLinux::WriteRegisterRaw(), WriteRegisterValueInHexFixedWidth(), lldb_private::NativeRegisterContext::WriteRegisterValueToMemory(), lldb_private::RegisterContext::WriteRegisterValueToMemory(), lldb_private::RegisterContextUnwind::WriteRegisterValueToRegisterLocation(), lldb_private::IRMemoryMap::WriteScalarToMemory(), lldb_private::Process::WriteScalarToMemory(), WriteString(), xcrun(), lldb_private::AllocatedMemoryCache::~AllocatedMemoryCache(), lldb_private::AppleThreadPlanStepThroughObjCTrampoline::~AppleThreadPlanStepThroughObjCTrampoline(), lldb_private::BorrowedStackFrame::~BorrowedStackFrame(), lldb_private::BreakpointOptions::~BreakpointOptions(), lldb_private::BreakpointResolverAddress::~BreakpointResolverAddress(), lldb_private::BreakpointResolverScripted::~BreakpointResolverScripted(), lldb_private::ClangREPL::~ClangREPL(), CommandObjectTypeFilterAdd::~CommandObjectTypeFilterAdd(), CommandObjectTypeSynthAdd::~CommandObjectTypeSynthAdd(), lldb_private::ExceptionSearchFilter::~ExceptionSearchFilter(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::~GDBRemoteCommunicationServer(), lldb_private::MemoryCache::~MemoryCache(), lldb_private::OptionValueUInt64::~OptionValueUInt64(), PlatformPOSIX::~PlatformPOSIX(), lldb_private::wasm::ProcessWasm::~ProcessWasm(), lldb::SBData::~SBData(), lldb::SBExpressionOptions::~SBExpressionOptions(), lldb::SBPlatform::~SBPlatform(), lldb::SBSaveCoreOptions::~SBSaveCoreOptions(), lldb::SBTarget::~SBTarget(), lldb::SBThread::~SBThread(), lldb::SBThreadPlan::~SBThreadPlan(), lldb::SBValue::~SBValue(), lldb_private::ScriptInterpreterLua::~ScriptInterpreterLua(), lldb_private::SearchFilter::~SearchFilter(), lldb_private::SearchFilterByModule::~SearchFilterByModule(), lldb_private::SearchFilterByModuleList::~SearchFilterByModuleList(), lldb_private::SearchFilterByModuleListAndCU::~SearchFilterByModuleListAndCU(), lldb_private::SearchFilterForUnconstrainedSearches::~SearchFilterForUnconstrainedSearches(), lldb_private::SingleStepBreakpointLocationsPredictor::~SingleStepBreakpointLocationsPredictor(), lldb_private::SymbolContext::~SymbolContext(), lldb_private::ThreadPlanBase::~ThreadPlanBase(), lldb_private::ThreadPlanNull::~ThreadPlanNull(), lldb_private::ThreadPlanStepInstruction::~ThreadPlanStepInstruction(), lldb_private::ThreadPlanStepOverBreakpoint::~ThreadPlanStepOverBreakpoint(), lldb_private::ValueObjectConstResult::~ValueObjectConstResult(), lldb_private::ValueObjectConstResultCast::~ValueObjectConstResultCast(), lldb_private::ValueObjectConstResultChild::~ValueObjectConstResultChild(), lldb_private::ValueObjectConstResultImpl::~ValueObjectConstResultImpl(), and lldb_private::ValueObjectVariable::~ValueObjectVariable().
note()
llvm::raw_ostream & note (Stream & strm) static
Definition at line 30 of file CommandReturnObject.cpp.
References lldb_private::Stream::AsRawOstream().
Referenced by lldb_private::CommandReturnObject::AppendNote(), lldb_private::CommandReturnObject::AppendNoteWithFormat(), ProcessElfCore::FindBuidIdInCoreMemory(), ProcessElfCore::parseFreeBSDNotes(), ProcessElfCore::parseLinuxNotes(), ProcessElfCore::parseNetBSDNotes(), ProcessElfCore::parseOpenBSDNotes(), ProcessElfCore::parseSegment(), and ObjectFileELF::RefineModuleDetailsFromNote().
warning()
llvm::raw_ostream & warning (Stream & strm) static
Definition at line 24 of file CommandReturnObject.cpp.
References lldb_private::Stream::AsRawOstream().
Referenced by lldb_private::TraceGetStateResponse::AddWarning(), lldb_private::CommandReturnObject::AppendWarning(), lldb_private::CommandReturnObject::AppendWarningWithFormat(), InstrumentationBoundsSafetyStopInfo::ComputeStopReasonAndSuggestedStackFrameWithoutDebugInfo(), lldb_private::ClangExpressionDeclMap::FindExternalVisibleDecls(), and lldb_private::Trace::RefreshLiveProcessState().