LLDB: FileSystem.cpp File Reference
FileSystem.cpp File Reference
#include "lldb/Host/FileSystem.h"
#include "lldb/Utility/DataBufferLLVM.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Errno.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/Threading.h"
#include <cerrno>
#include <climits>
#include <cstdarg>
#include <cstdio>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <sys/stat.h>
#include <termios.h>
#include <unistd.h>
#include <algorithm>
#include <fstream>
#include <memory>
#include <optional>
#include <vector>
Functions
template<typename T>
static std::unique_ptr< T > GetMemoryBuffer (const llvm::Twine &path, uint64_t size, uint64_t offset, bool is_volatile)
static int OpenWithFS (const FileSystem &fs, const char *path, int flags, int mode)
static int GetOpenFlags (File::OpenOptions options)
static mode_t GetOpenMode (uint32_t permissions)
Function Documentation
GetMemoryBuffer()
template<typename T> std::unique_ptr< T > GetMemoryBuffer (const llvm::Twine & path, uint64_t size, uint64_t offset, bool is_volatile) static
Definition at line 267 of file common/FileSystem.cpp.
Referenced by lldb_private::FileSystem::CreateDataBuffer(), and lldb_private::FileSystem::CreateWritableDataBuffer().
GetOpenFlags()
int GetOpenFlags (File::OpenOptions options) static
Definition at line 373 of file common/FileSystem.cpp.
References lldb_private::File::eOpenOptionAppend, lldb_private::File::eOpenOptionCanCreate, lldb_private::File::eOpenOptionCanCreateNewOnly, lldb_private::File::eOpenOptionCloseOnExec, lldb_private::File::eOpenOptionDontFollowSymlinks, lldb_private::File::eOpenOptionNonBlocking, lldb_private::File::eOpenOptionReadOnly, lldb_private::File::eOpenOptionReadWrite, lldb_private::File::eOpenOptionTruncate, lldb_private::File::eOpenOptionWriteOnly, and O_NONBLOCK.
Referenced by lldb_private::FileSystem::Open().
GetOpenMode()
mode_t GetOpenMode (uint32_t permissions) static
Definition at line 416 of file common/FileSystem.cpp.
References S_IRGRP, S_IROTH, S_IRUSR, S_IWGRP, S_IWOTH, S_IWUSR, S_IXGRP, S_IXOTH, and S_IXUSR.
Referenced by lldb_private::FileSystem::Open().
OpenWithFS()
int OpenWithFS (const FileSystem & fs, const char * path, int flags, int mode) static
Definition at line 368 of file common/FileSystem.cpp.
Referenced by lldb_private::FileSystem::Open().