LLDB: CommandObjectType.cpp File Reference
CommandObjectType.cpp File Reference
#include "CommandObjectType.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/IOHandler.h"
#include "lldb/DataFormatters/DataVisualization.h"
#include "lldb/DataFormatters/FormatClasses.h"
#include "lldb/Host/Config.h"
#include "lldb/Host/OptionParser.h"
#include "lldb/Host/StreamFile.h"
#include "lldb/Interpreter/CommandInterpreter.h"
#include "lldb/Interpreter/CommandObject.h"
#include "lldb/Interpreter/CommandOptionArgumentTable.h"
#include "lldb/Interpreter/CommandReturnObject.h"
#include "lldb/Interpreter/OptionArgParser.h"
#include "lldb/Interpreter/OptionGroupFormat.h"
#include "lldb/Interpreter/OptionValueBoolean.h"
#include "lldb/Interpreter/OptionValueLanguage.h"
#include "lldb/Interpreter/OptionValueString.h"
#include "lldb/Interpreter/Options.h"
#include "lldb/Symbol/Symbol.h"
#include "lldb/Target/Language.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/RegularExpression.h"
#include "lldb/Utility/StringList.h"
#include "lldb/lldb-forward.h"
#include "llvm/ADT/STLExtras.h"
#include <algorithm>
#include <functional>
#include <memory>
#include "CommandOptions.inc"
Classes
class ScriptAddOptions
class SynthAddOptions
class CommandObjectTypeSummaryAdd
class CommandObjectTypeSummaryAdd::CommandOptions
class CommandObjectTypeSynthAdd
class CommandObjectTypeSynthAdd::CommandOptions
class CommandObjectTypeFormatAdd
class CommandObjectTypeFormatAdd::CommandOptions
class CommandObjectTypeFormatterDelete
class CommandObjectTypeFormatterDelete::CommandOptions
class CommandObjectTypeFormatterClear
class CommandObjectTypeFormatterClear::CommandOptions
class CommandObjectTypeFormatDelete
class CommandObjectTypeFormatClear
class CommandObjectTypeFormatterList< FormatterType >
class CommandObjectTypeFormatterList< FormatterType >::CommandOptions
class CommandObjectTypeFormatList
class CommandObjectTypeSummaryDelete
class CommandObjectTypeSummaryClear
class CommandObjectTypeSummaryList
class CommandObjectTypeCategoryDefine
class CommandObjectTypeCategoryDefine::CommandOptions
class CommandObjectTypeCategoryEnable
class CommandObjectTypeCategoryEnable::CommandOptions
class CommandObjectTypeCategoryDelete
class CommandObjectTypeCategoryDisable
class CommandObjectTypeCategoryDisable::CommandOptions
class CommandObjectTypeCategoryList
class CommandObjectTypeFilterList
class CommandObjectTypeSynthList
class CommandObjectTypeFilterDelete
class CommandObjectTypeSynthDelete
class CommandObjectTypeFilterClear
class CommandObjectTypeSynthClear
class CommandObjectTypeFilterAdd
class CommandObjectTypeFilterAdd::CommandOptions
class CommandObjectTypeLookup
class CommandObjectTypeLookup::CommandOptions
class CommandObjectFormatterInfo< FormatterType >
class CommandObjectTypeFormat
class CommandObjectTypeSynth
class CommandObjectTypeFilter
class CommandObjectTypeCategory
class CommandObjectTypeSummary
Macros
#define LLDB_OPTIONS_type_summary_add
#define LLDB_OPTIONS_type_synth_add
#define LLDB_OPTIONS_type_format_add
#define LLDB_OPTIONS_type_formatter_delete
#define LLDB_OPTIONS_type_formatter_clear
#define LLDB_OPTIONS_type_formatter_list
#define LLDB_OPTIONS_type_category_define
#define LLDB_OPTIONS_type_category_enable
#define LLDB_OPTIONS_type_category_disable
#define LLDB_OPTIONS_type_filter_add
#define LLDB_OPTIONS_type_lookup
Functions
static bool WarnOnPotentialUnquotedUnsignedType (Args &command, CommandReturnObject &result)
const char * FormatCategoryToString (FormatCategoryItem item, bool long_name)
static bool FixArrayTypeNameWithRegex (ConstString &type_name)
Variables
static const char * g_synth_addreader_instructions
Macro Definition Documentation
LLDB_OPTIONS_type_category_define
#define LLDB_OPTIONS_type_category_define
Definition at line 1614 of file CommandObjectType.cpp.
LLDB_OPTIONS_type_category_disable
#define LLDB_OPTIONS_type_category_disable
Definition at line 1843 of file CommandObjectType.cpp.
LLDB_OPTIONS_type_category_enable
#define LLDB_OPTIONS_type_category_enable
Definition at line 1701 of file CommandObjectType.cpp.
LLDB_OPTIONS_type_filter_add
#define LLDB_OPTIONS_type_filter_add
Definition at line 2219 of file CommandObjectType.cpp.
LLDB_OPTIONS_type_format_add
#define LLDB_OPTIONS_type_format_add
Definition at line 522 of file CommandObjectType.cpp.
LLDB_OPTIONS_type_formatter_clear
#define LLDB_OPTIONS_type_formatter_clear
Definition at line 877 of file CommandObjectType.cpp.
LLDB_OPTIONS_type_formatter_delete
#define LLDB_OPTIONS_type_formatter_delete
Definition at line 720 of file CommandObjectType.cpp.
LLDB_OPTIONS_type_formatter_list
#define LLDB_OPTIONS_type_formatter_list
Definition at line 982 of file CommandObjectType.cpp.
LLDB_OPTIONS_type_lookup
#define LLDB_OPTIONS_type_lookup
Definition at line 2455 of file CommandObjectType.cpp.
LLDB_OPTIONS_type_summary_add
#define LLDB_OPTIONS_type_summary_add
Definition at line 119 of file CommandObjectType.cpp.
LLDB_OPTIONS_type_synth_add
#define LLDB_OPTIONS_type_synth_add
Definition at line 300 of file CommandObjectType.cpp.
Function Documentation
FixArrayTypeNameWithRegex()
bool FixArrayTypeNameWithRegex (ConstString & type_name) static
Definition at line 1491 of file CommandObjectType.cpp.
Referenced by CommandObjectTypeFilterAdd::CommandOptions::SetOptionValue().
FormatCategoryToString()
const char * FormatCategoryToString (FormatCategoryItem item, bool long_name)
Definition at line 103 of file CommandObjectType.cpp.
References lldb_private::eFormatCategoryItemFilter, lldb_private::eFormatCategoryItemFormat, lldb_private::eFormatCategoryItemSummary, and lldb_private::eFormatCategoryItemSynth.
Referenced by CommandObjectTypeFormatterDelete::CommandObjectTypeFormatterDelete().
WarnOnPotentialUnquotedUnsignedType()
bool WarnOnPotentialUnquotedUnsignedType (Args & command, CommandReturnObject & result) static
Definition at line 82 of file CommandObjectType.cpp.
References lldb_private::CommandReturnObject::AppendWarningWithFormat(), lldb_private::Args::empty(), and lldb_private::Args::entries().
Referenced by CommandObjectTypeSynthAdd::DoExecute().
Variable Documentation
g_synth_addreader_instructions
const char* g_synth_addreader_instructions static
Initial value:
=
    "Enter your Python command(s). Type 'DONE' to end.\n"
    "You must define a Python class with these methods:\n"
    "    def __init__(self, valobj, internal_dict):\n"
    "    def num_children(self):\n"
    "    def get_child_at_index(self, index):\n"
    "    def get_child_index(self, name):\n"
    "    def update(self):\n"
    "        '''Optional'''\n"
    "class synthProvider:\n"
Definition at line 289 of file CommandObjectType.cpp.
Referenced by CommandObjectTypeSynthAdd::IOHandlerActivated().