LLDB: CommandObjectMemory.cpp File Reference
CommandObjectMemory.cpp File Reference
#include "CommandObjectMemory.h"
#include "CommandObjectMemoryTag.h"
#include "lldb/Core/DumpDataExtractor.h"
#include "lldb/Core/Section.h"
#include "lldb/Expression/ExpressionVariable.h"
#include "lldb/Host/OptionParser.h"
#include "lldb/Interpreter/CommandOptionArgumentTable.h"
#include "lldb/Interpreter/CommandReturnObject.h"
#include "lldb/Interpreter/OptionArgParser.h"
#include "lldb/Interpreter/OptionGroupFormat.h"
#include "lldb/Interpreter/OptionGroupMemoryTag.h"
#include "lldb/Interpreter/OptionGroupOutputFile.h"
#include "lldb/Interpreter/OptionGroupValueObjectDisplay.h"
#include "lldb/Interpreter/OptionValueLanguage.h"
#include "lldb/Interpreter/OptionValueString.h"
#include "lldb/Interpreter/Options.h"
#include "lldb/Symbol/SymbolFile.h"
#include "lldb/Symbol/TypeList.h"
#include "lldb/Target/ABI.h"
#include "lldb/Target/Language.h"
#include "lldb/Target/MemoryHistory.h"
#include "lldb/Target/MemoryRegionInfo.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/Args.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/ValueObject/ValueObjectMemory.h"
#include "llvm/Support/MathExtras.h"
#include <cinttypes>
#include <memory>
#include <optional>
#include "CommandOptions.inc"
Classes
class OptionGroupReadMemory
class CommandObjectMemoryRead
class CommandObjectMemoryFind
class CommandObjectMemoryFind::OptionGroupFindMemory
class CommandObjectMemoryWrite
class CommandObjectMemoryWrite::OptionGroupWriteMemory
class CommandObjectMemoryHistory
class CommandObjectMemoryRegion
class CommandObjectMemoryRegion::OptionGroupMemoryRegion
Macros
#define LLDB_OPTIONS_memory_read
#define ALL_KEYWORDS
#define KEYWORD(s)
#define KEYWORD(s)
#define LLDB_OPTIONS_memory_find
#define LLDB_OPTIONS_memory_write
#define LLDB_OPTIONS_memory_region
Functions
static llvm::Error CopyExpressionResult (ValueObject &result, DataBufferHeap &buffer, ExecutionContextScope *scope)
static llvm::Expected< ValueObjectSP > EvaluateExpression (llvm::StringRef expression, StackFrame &frame, Process &process)
Macro Definition Documentation
ALL_KEYWORDS
#define ALL_KEYWORDS
Value:
  KEYWORD("const")                                                             \
  KEYWORD("volatile")                                                          \
  KEYWORD("restrict")                                                          \
  KEYWORD("struct")                                                            \
  KEYWORD("class")                                                             \
  KEYWORD("union")
Referenced by CommandObjectMemoryRead::DoExecute().
KEYWORD [1/2]
#define KEYWORD (s)
Value:
s,
KEYWORD [2/2]
#define KEYWORD (s)
Value:
(sizeof(s) - 1),
LLDB_OPTIONS_memory_find
#define LLDB_OPTIONS_memory_find
Definition at line 878 of file CommandObjectMemory.cpp.
LLDB_OPTIONS_memory_read
#define LLDB_OPTIONS_memory_read
Definition at line 47 of file CommandObjectMemory.cpp.
LLDB_OPTIONS_memory_region
#define LLDB_OPTIONS_memory_region
Definition at line 1605 of file CommandObjectMemory.cpp.
LLDB_OPTIONS_memory_write
#define LLDB_OPTIONS_memory_write
Definition at line 1146 of file CommandObjectMemory.cpp.
Function Documentation
CopyExpressionResult()
llvm::Error CopyExpressionResult (ValueObject & result, DataBufferHeap & buffer, ExecutionContextScope * scope) static
Definition at line 881 of file CommandObjectMemory.cpp.
References lldb_private::DataBufferHeap::CopyData(), lldb_private::CompilerType::GetByteSize(), lldb_private::ValueObject::GetCompilerType(), and lldb_private::ValueObject::GetValueAsUnsigned().
Referenced by CommandObjectMemoryFind::DoExecute().
EvaluateExpression()
llvm::Expected< ValueObjectSP > EvaluateExpression (llvm::StringRef expression, StackFrame & frame, Process & process) static
Definition at line 916 of file CommandObjectMemory.cpp.
References lldb::eExpressionCompleted, lldb_private::Target::EvaluateExpression(), and lldb_private::Process::GetTarget().
Referenced by CommandObjectMemoryFind::DoExecute().