LLDB: CommandObjectThread.cpp File Reference
CommandObjectThread.cpp File Reference
#include "CommandObjectThread.h"
#include <memory>
#include <optional>
#include <sstream>
#include "CommandObjectThreadUtil.h"
#include "CommandObjectTrace.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Host/OptionParser.h"
#include "lldb/Interpreter/CommandInterpreter.h"
#include "lldb/Interpreter/CommandOptionArgumentTable.h"
#include "lldb/Interpreter/CommandReturnObject.h"
#include "lldb/Interpreter/OptionArgParser.h"
#include "lldb/Interpreter/OptionGroupPythonClassWithDict.h"
#include "lldb/Interpreter/Options.h"
#include "lldb/Symbol/CompileUnit.h"
#include "lldb/Symbol/Function.h"
#include "lldb/Symbol/LineEntry.h"
#include "lldb/Symbol/LineTable.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/SystemRuntime.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Target/ThreadPlan.h"
#include "lldb/Target/ThreadPlanStepInRange.h"
#include "lldb/Target/Trace.h"
#include "lldb/Target/TraceDumper.h"
#include "lldb/Utility/State.h"
#include "lldb/ValueObject/ValueObject.h"
#include "CommandOptions.inc"
Classes
class CommandObjectThreadBacktrace
class CommandObjectThreadBacktrace::CommandOptions
class ThreadStepScopeOptionGroup
class CommandObjectThreadStepWithTypeAndScope
class CommandObjectThreadContinue
class CommandObjectThreadUntil
class CommandObjectThreadUntil::CommandOptions
class CommandObjectThreadSelect
class CommandObjectThreadSelect::OptionGroupThreadSelect
class CommandObjectThreadList
class CommandObjectThreadInfo
class CommandObjectThreadInfo::CommandOptions
class CommandObjectThreadException
class CommandObjectThreadSiginfo
class CommandObjectThreadReturn
class CommandObjectThreadReturn::CommandOptions
class CommandObjectThreadJump
class CommandObjectThreadJump::CommandOptions
class CommandObjectThreadPlanList
class CommandObjectThreadPlanList::CommandOptions
class CommandObjectThreadPlanDiscard
class CommandObjectThreadPlanPrune
class CommandObjectMultiwordThreadPlan
class CommandObjectTraceExport
class CommandObjectTraceStart
class CommandObjectTraceStop
class CommandObjectTraceDumpFunctionCalls
class CommandObjectTraceDumpFunctionCalls::CommandOptions
class CommandObjectTraceDumpInstructions
class CommandObjectTraceDumpInstructions::CommandOptions
class CommandObjectTraceDumpInfo
class CommandObjectTraceDumpInfo::CommandOptions
class CommandObjectMultiwordTraceDump
class CommandObjectMultiwordTrace
Macros
#define LLDB_OPTIONS_thread_backtrace
#define LLDB_OPTIONS_thread_step_scope
#define LLDB_OPTIONS_thread_until
#define LLDB_OPTIONS_thread_select
#define LLDB_OPTIONS_thread_info
#define LLDB_OPTIONS_thread_return
#define LLDB_OPTIONS_thread_jump
#define LLDB_OPTIONS_thread_plan_list
#define LLDB_OPTIONS_thread_trace_dump_function_calls
#define LLDB_OPTIONS_thread_trace_dump_instructions
#define LLDB_OPTIONS_thread_trace_dump_info
Functions
static ThreadSP GetSingleThreadFromArgs (ExecutionContext &exe_ctx, Args &args, CommandReturnObject &result)
Macro Definition Documentation
LLDB_OPTIONS_thread_backtrace
#define LLDB_OPTIONS_thread_backtrace
Definition at line 45 of file CommandObjectThread.cpp.
LLDB_OPTIONS_thread_info
#define LLDB_OPTIONS_thread_info
Definition at line 1259 of file CommandObjectThread.cpp.
LLDB_OPTIONS_thread_jump
#define LLDB_OPTIONS_thread_jump
Definition at line 1617 of file CommandObjectThread.cpp.
LLDB_OPTIONS_thread_plan_list
#define LLDB_OPTIONS_thread_plan_list
Definition at line 1757 of file CommandObjectThread.cpp.
LLDB_OPTIONS_thread_return
#define LLDB_OPTIONS_thread_return
Definition at line 1465 of file CommandObjectThread.cpp.
LLDB_OPTIONS_thread_select
#define LLDB_OPTIONS_thread_select
Definition at line 1091 of file CommandObjectThread.cpp.
LLDB_OPTIONS_thread_step_scope
#define LLDB_OPTIONS_thread_step_scope
Definition at line 260 of file CommandObjectThread.cpp.
LLDB_OPTIONS_thread_trace_dump_function_calls
#define LLDB_OPTIONS_thread_trace_dump_function_calls
Definition at line 2119 of file CommandObjectThread.cpp.
LLDB_OPTIONS_thread_trace_dump_info
#define LLDB_OPTIONS_thread_trace_dump_info
Definition at line 2427 of file CommandObjectThread.cpp.
LLDB_OPTIONS_thread_trace_dump_instructions
#define LLDB_OPTIONS_thread_trace_dump_instructions
Definition at line 2224 of file CommandObjectThread.cpp.
LLDB_OPTIONS_thread_until
#define LLDB_OPTIONS_thread_until
Definition at line 787 of file CommandObjectThread.cpp.
Function Documentation
GetSingleThreadFromArgs()
ThreadSP GetSingleThreadFromArgs (ExecutionContext & exe_ctx, Args & args, CommandReturnObject & result) static
Definition at line 2099 of file CommandObjectThread.cpp.
References lldb_private::CommandReturnObject::AppendErrorWithFormat(), lldb_private::ThreadList::FindThreadByIndexID(), lldb_private::Args::GetArgumentAtIndex(), lldb_private::Args::GetArgumentCount(), lldb_private::ExecutionContext::GetProcessRef(), lldb_private::Process::GetThreadList(), and lldb_private::ExecutionContext::GetThreadSP().
Referenced by CommandObjectTraceDumpFunctionCalls::DoExecute(), and CommandObjectTraceDumpInstructions::DoExecute().