LLDB: CommandObjectVersion.cpp File Reference
CommandObjectVersion.cpp File Reference
#include "CommandObjectVersion.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Interpreter/CommandReturnObject.h"
#include "lldb/Version/Version.h"
#include "llvm/ADT/StringExtras.h"
#include "CommandOptions.inc"
Macros
#define LLDB_OPTIONS_version
Functions
static void dump (const StructuredData::Array &array, Stream &s)
static void dump (const StructuredData::Dictionary &config, Stream &s)
Macro Definition Documentation
LLDB_OPTIONS_version
#define LLDB_OPTIONS_version
Definition at line 19 of file CommandObjectVersion.cpp.
Function Documentation
dump() [1/2]
void dump (const StructuredData::Array & array, Stream & s) static
Definition at line 34 of file CommandObjectVersion.cpp.
References lldb_private::StructuredData::Array::ForEach().
Referenced by lldb_private::CommandObjectVersion::DoExecute(), dump(), and lldb_private::Target::GetOrCreateModule().
dump() [2/2]
void dump (const StructuredData::Dictionary & config, Stream & s) static
Definition at line 45 of file CommandObjectVersion.cpp.
References dump(), lldb_private::StructuredData::Dictionary::ForEach(), lldb_private::StructuredData::Object::GetAsDictionary(), and lldb_private::StructuredData::Dictionary::GetValueForKey().