LLDB: CommandAlias.cpp File Reference
CommandAlias.cpp File Reference
#include "lldb/Interpreter/CommandAlias.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormatAdapters.h"
#include "lldb/Interpreter/CommandInterpreter.h"
#include "lldb/Interpreter/CommandObject.h"
#include "lldb/Interpreter/CommandReturnObject.h"
#include "lldb/Interpreter/Options.h"
#include "lldb/Utility/StreamString.h"
Functions
static llvm::Error ProcessAliasOptionsArgs (lldb::CommandObjectSP &cmd_obj_sp, llvm::StringRef options_args, OptionArgVectorSP &option_arg_vector_sp)
Function Documentation
ProcessAliasOptionsArgs()
llvm::Error ProcessAliasOptionsArgs (lldb::CommandObjectSP & cmd_obj_sp, llvm::StringRef options_args, OptionArgVectorSP & option_arg_vector_sp) static
Definition at line 25 of file CommandAlias.cpp.
References lldb_private::Args::entries(), error(), lldb_private::CommandInterpreter::g_argument, lldb_private::Options::NotifyOptionParsingStarting(), lldb_private::Options::ParseAlias(), and lldb_private::Options::VerifyPartialOptions().
Referenced by lldb_private::CommandAlias::CommandAlias().