LLDB: CommandObjectLog.cpp File Reference
CommandObjectLog.cpp File Reference
#include "CommandObjectLog.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Host/OptionParser.h"
#include "lldb/Interpreter/CommandOptionArgumentTable.h"
#include "lldb/Interpreter/CommandReturnObject.h"
#include "lldb/Interpreter/OptionArgParser.h"
#include "lldb/Interpreter/OptionValueEnumeration.h"
#include "lldb/Interpreter/OptionValueUInt64.h"
#include "lldb/Interpreter/Options.h"
#include "lldb/Utility/Args.h"
#include "lldb/Utility/FileSpec.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/Stream.h"
#include "lldb/Utility/Timer.h"
#include "CommandOptions.inc"
Classes
class CommandObjectLogEnable
class CommandObjectLogEnable::CommandOptions
class CommandObjectLogDisable
class CommandObjectLogList
class CommandObjectLogDump
class CommandObjectLogDump::CommandOptions
class CommandObjectLogTimerEnable
class CommandObjectLogTimerDisable
class CommandObjectLogTimerDump
class CommandObjectLogTimerReset
class CommandObjectLogTimerIncrement
class CommandObjectLogTimer
Macros
#define LLDB_OPTIONS_log_enable
#define LLDB_OPTIONS_log_dump
Functions
static void CompleteEnableDisable (CompletionRequest &request)
Common completion logic for log enable/disable.
Macro Definition Documentation
LLDB_OPTIONS_log_dump
#define LLDB_OPTIONS_log_dump
Definition at line 30 of file CommandObjectLog.cpp.
LLDB_OPTIONS_log_enable
#define LLDB_OPTIONS_log_enable
Definition at line 27 of file CommandObjectLog.cpp.
Function Documentation
CompleteEnableDisable()
void CompleteEnableDisable (CompletionRequest & request) static
Common completion logic for log enable/disable.
Definition at line 34 of file CommandObjectLog.cpp.
References lldb_private::Log::ForEachChannelCategory(), lldb_private::Args::GetArgumentAtIndex(), lldb_private::CompletionRequest::GetCursorIndex(), lldb_private::CompletionRequest::GetParsedLine(), lldb_private::Log::ListChannels(), and lldb_private::CompletionRequest::TryCompleteCurrentArg().
Referenced by CommandObjectLogDisable::HandleArgumentCompletion(), CommandObjectLogDump::HandleArgumentCompletion(), and CommandObjectLogEnable::HandleArgumentCompletion().