LLDB: CommandObjectWatchpoint.cpp File Reference
CommandObjectWatchpoint.cpp File Reference
#include "CommandObjectWatchpoint.h"
#include "CommandObjectWatchpointCommand.h"
#include <memory>
#include <vector>
#include "llvm/ADT/StringRef.h"
#include "lldb/Breakpoint/Watchpoint.h"
#include "lldb/Breakpoint/WatchpointList.h"
#include "lldb/Host/OptionParser.h"
#include "lldb/Interpreter/CommandInterpreter.h"
#include "lldb/Interpreter/CommandOptionArgumentTable.h"
#include "lldb/Interpreter/CommandReturnObject.h"
#include "lldb/Symbol/Function.h"
#include "lldb/Symbol/Variable.h"
#include "lldb/Symbol/VariableList.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/ValueObject/ValueObject.h"
#include "CommandOptions.inc"
Classes
class CommandObjectWatchpointList
class CommandObjectWatchpointList::CommandOptions
class CommandObjectWatchpointEnable
class CommandObjectWatchpointDisable
class CommandObjectWatchpointDelete
class CommandObjectWatchpointDelete::CommandOptions
class CommandObjectWatchpointIgnore
class CommandObjectWatchpointIgnore::CommandOptions
class CommandObjectWatchpointModify
class CommandObjectWatchpointModify::CommandOptions
class CommandObjectWatchpointSetVariable
class CommandObjectWatchpointSetExpression
class CommandObjectWatchpointSet
Macros
#define LLDB_OPTIONS_watchpoint_list
#define LLDB_OPTIONS_watchpoint_delete
#define LLDB_OPTIONS_watchpoint_ignore
#define LLDB_OPTIONS_watchpoint_modify
Functions
static void AddWatchpointDescription (Stream &s, Watchpoint &wp, lldb::DescriptionLevel level)
static bool CheckTargetForWatchpointOperations (Target &target, CommandReturnObject &result)
static int32_t WithRSAIndex (llvm::StringRef Arg)
Variables
static const char * RSA [4] = {"-", "to", "To", "TO"}
Macro Definition Documentation
LLDB_OPTIONS_watchpoint_delete
#define LLDB_OPTIONS_watchpoint_delete
Definition at line 404 of file CommandObjectWatchpoint.cpp.
LLDB_OPTIONS_watchpoint_ignore
#define LLDB_OPTIONS_watchpoint_ignore
Definition at line 523 of file CommandObjectWatchpoint.cpp.
LLDB_OPTIONS_watchpoint_list
#define LLDB_OPTIONS_watchpoint_list
Definition at line 142 of file CommandObjectWatchpoint.cpp.
LLDB_OPTIONS_watchpoint_modify
#define LLDB_OPTIONS_watchpoint_modify
Definition at line 635 of file CommandObjectWatchpoint.cpp.
Function Documentation
AddWatchpointDescription()
void AddWatchpointDescription (Stream & s, Watchpoint & wp, lldb::DescriptionLevel level) static
Definition at line 34 of file CommandObjectWatchpoint.cpp.
References lldb_private::Stream::EOL(), lldb_private::Watchpoint::GetDescription(), lldb_private::Stream::IndentLess(), and lldb_private::Stream::IndentMore().
Referenced by CommandObjectWatchpointList::DoExecute().
CheckTargetForWatchpointOperations()
bool CheckTargetForWatchpointOperations (Target & target, CommandReturnObject & result) static
Definition at line 42 of file CommandObjectWatchpoint.cpp.
References lldb_private::CommandReturnObject::AppendError(), and lldb_private::Target::GetProcessSP().
Referenced by CommandObjectWatchpointDelete::DoExecute(), CommandObjectWatchpointDisable::DoExecute(), CommandObjectWatchpointEnable::DoExecute(), CommandObjectWatchpointIgnore::DoExecute(), and CommandObjectWatchpointModify::DoExecute().
WithRSAIndex()
int32_t WithRSAIndex (llvm::StringRef Arg) static
Definition at line 58 of file CommandObjectWatchpoint.cpp.
References RSA.
Referenced by lldb_private::CommandObjectMultiwordWatchpoint::VerifyWatchpointIDs().
Variable Documentation
RSA
const char* RSA[4] = {"-", "to", "To", "TO"} static
Definition at line 55 of file CommandObjectWatchpoint.cpp.
Referenced by lldb_private::CommandObjectMultiwordWatchpoint::VerifyWatchpointIDs(), and WithRSAIndex().