LLDB: CommandCompletions.cpp File Reference
CommandCompletions.cpp File Reference
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSet.h"
#include "lldb/Breakpoint/Watchpoint.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/DataFormatters/DataVisualization.h"
#include "lldb/Host/FileSystem.h"
#include "lldb/Interpreter/CommandCompletions.h"
#include "lldb/Interpreter/CommandInterpreter.h"
#include "lldb/Interpreter/CommandObject.h"
#include "lldb/Interpreter/CommandObjectMultiword.h"
#include "lldb/Interpreter/OptionValueProperties.h"
#include "lldb/Symbol/CompileUnit.h"
#include "lldb/Symbol/Variable.h"
#include "lldb/Target/Language.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/FileSpec.h"
#include "lldb/Utility/FileSpecList.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/Utility/TildeExpressionResolver.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
Classes
struct CommonCompletionElement
Typedefs
typedef void(* CompletionCallback) (CommandInterpreter &interpreter, CompletionRequest &request, lldb_private::SearchFilter *searcher)
Functions
static bool regex_chars (const char comp)
static void DiskFilesOrDirectories (const llvm::Twine &partial_name, bool only_directories, CompletionRequest &request, TildeExpressionResolver &Resolver)
static void DiskFilesOrDirectories (const llvm::Twine &partial_name, bool only_directories, StringList &matches, TildeExpressionResolver &Resolver)
static void DiskFilesOrDirectories (CompletionRequest &request, bool only_directories)
Typedef Documentation
CompletionCallback
typedef void(* CompletionCallback) (CommandInterpreter &interpreter, CompletionRequest &request, lldb_private::SearchFilter *searcher)
Definition at line 43 of file CommandCompletions.cpp.
Function Documentation
DiskFilesOrDirectories() [1/3]
void DiskFilesOrDirectories (CompletionRequest & request, bool only_directories) static
Definition at line 497 of file CommandCompletions.cpp.
References DiskFilesOrDirectories(), and lldb_private::CompletionRequest::GetCursorArgumentPrefix().
DiskFilesOrDirectories() [2/3]
void DiskFilesOrDirectories (const llvm::Twine & partial_name, bool only_directories, CompletionRequest & request, TildeExpressionResolver & Resolver) static
Definition at line 346 of file CommandCompletions.cpp.
References lldb_private::CompletionRequest::AddCompletion(), lldb_private::FileSystem::DirBegin(), error(), lldb_private::FileSystem::GetStatus(), lldb_private::FileSystem::Instance(), lldb_private::FileSystem::IsDirectory(), lldb_private::Normal, lldb_private::Partial, PATH_MAX, lldb_private::TildeExpressionResolver::ResolveExact(), lldb_private::TildeExpressionResolver::ResolvePartial(), lldb_private::FileSystem::ResolveSymbolicLink(), and lldb_private::CompletionRequest::ShouldAddCompletions().
Referenced by lldb_private::CommandCompletions::DiskDirectories(), lldb_private::CommandCompletions::DiskDirectories(), lldb_private::CommandCompletions::DiskFiles(), lldb_private::CommandCompletions::DiskFiles(), DiskFilesOrDirectories(), and DiskFilesOrDirectories().
DiskFilesOrDirectories() [3/3]
void DiskFilesOrDirectories (const llvm::Twine & partial_name, bool only_directories, StringList & matches, TildeExpressionResolver & Resolver) static
Definition at line 487 of file CommandCompletions.cpp.
References DiskFilesOrDirectories(), and lldb_private::CompletionResult::GetMatches().
regex_chars()
bool regex_chars (const char comp) static
Definition at line 195 of file CommandCompletions.cpp.