LLDB: CommandObjectBreakpoint.cpp File Reference
CommandObjectBreakpoint.cpp File Reference
#include "CommandObjectBreakpoint.h"
#include "CommandObjectBreakpointCommand.h"
#include "lldb/Breakpoint/Breakpoint.h"
#include "lldb/Breakpoint/BreakpointIDList.h"
#include "lldb/Breakpoint/BreakpointLocation.h"
#include "lldb/Host/OptionParser.h"
#include "lldb/Interpreter/CommandInterpreter.h"
#include "lldb/Interpreter/CommandOptionArgumentTable.h"
#include "lldb/Interpreter/CommandReturnObject.h"
#include "lldb/Interpreter/OptionArgParser.h"
#include "lldb/Interpreter/OptionGroupPythonClassWithDict.h"
#include "lldb/Interpreter/OptionValueBoolean.h"
#include "lldb/Interpreter/OptionValueFileColonLine.h"
#include "lldb/Interpreter/OptionValueString.h"
#include "lldb/Interpreter/OptionValueUInt64.h"
#include "lldb/Interpreter/Options.h"
#include "lldb/Target/Language.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/ThreadSpec.h"
#include "lldb/Utility/RegularExpression.h"
#include "lldb/Utility/StreamString.h"
#include "llvm/Support/FormatAdapters.h"
#include <memory>
#include <optional>
#include <vector>
#include "CommandOptions.inc"
Classes
class lldb_private::BreakpointOptionGroup
class BreakpointNamesOptionGroup
class BreakpointDummyOptionGroup
class CommandObjectBreakpointAddAddress
class CommandObjectBreakpointAddAddress::CommandOptions
class CommandObjectBreakpointAddException
class CommandObjectBreakpointAddException::CommandOptions
class CommandObjectBreakpointAddFile
class CommandObjectBreakpointAddFile::CommandOptions
class CommandObjectBreakpointAddName
class CommandObjectBreakpointAddName::CommandOptions
class CommandObjectBreakpointAddPattern
class CommandObjectBreakpointAddPattern::CommandOptions
class CommandObjectBreakpointAddScripted
class CommandObjectBreakpointAddScripted::CommandOptions
class CommandObjectBreakpointAdd
class CommandObjectBreakpointSet
class CommandObjectBreakpointSet::CommandOptions
class CommandObjectBreakpointModify
class CommandObjectBreakpointEnable
class CommandObjectBreakpointDisable
class CommandObjectBreakpointList
class CommandObjectBreakpointList::CommandOptions
class CommandObjectBreakpointClear
class CommandObjectBreakpointClear::CommandOptions
class CommandObjectBreakpointDelete
class CommandObjectBreakpointDelete::CommandOptions
class BreakpointNameOptionGroup
class BreakpointAccessOptionGroup
class CommandObjectBreakpointNameConfigure
class CommandObjectBreakpointNameAdd
class CommandObjectBreakpointNameDelete
class CommandObjectBreakpointNameList
class CommandObjectBreakpointName
class CommandObjectBreakpointRead
class CommandObjectBreakpointRead::CommandOptions
class CommandObjectBreakpointWrite
class CommandObjectBreakpointWrite::CommandOptions
Macros
#define LLDB_OPTIONS_breakpoint_modify
#define LLDB_OPTIONS_breakpoint_names
#define LLDB_OPTIONS_breakpoint_dummy
#define LLDB_OPTIONS_breakpoint_add_address
#define LLDB_OPTIONS_breakpoint_add_exception
#define LLDB_OPTIONS_breakpoint_add_file
#define LLDB_OPTIONS_breakpoint_add_name
#define LLDB_OPTIONS_breakpoint_add_pattern
#define LLDB_OPTIONS_breakpoint_add_scripted
#define LLDB_OPTIONS_breakpoint_add
#define LLDB_OPTIONS_breakpoint_set
#define LLDB_OPTIONS_breakpoint_list
#define LLDB_OPTIONS_breakpoint_clear
#define LLDB_OPTIONS_breakpoint_delete
#define LLDB_OPTIONS_breakpoint_name
#define LLDB_OPTIONS_breakpoint_access
#define LLDB_OPTIONS_breakpoint_read
#define LLDB_OPTIONS_breakpoint_write
Functions
static void AddBreakpointDescription (Stream *s, Breakpoint *bp, lldb::DescriptionLevel level)
static bool GetDefaultFile (Target &target, StackFrame *cur_frame, FileSpec &file, CommandReturnObject &result)
static bool CopyOverBreakpointOptions (BreakpointSP bp_sp, BreakpointOptionGroup &bp_opts, const std::vector< std::string > &bp_names, CommandReturnObject &result)
static llvm::Expected< LanguageType > GetExceptionLanguageForLanguage (llvm::StringRef lang_name, char short_option='\0', llvm::StringRef long_option={})
static Status CompleteLineEntry (ExecutionContext &exe_ctx, OptionValueFileColonLine &line_entry)
Macro Definition Documentation
LLDB_OPTIONS_breakpoint_access
#define LLDB_OPTIONS_breakpoint_access
Definition at line 2815 of file CommandObjectBreakpoint.cpp.
LLDB_OPTIONS_breakpoint_add
#define LLDB_OPTIONS_breakpoint_add
Definition at line 1464 of file CommandObjectBreakpoint.cpp.
LLDB_OPTIONS_breakpoint_add_address
#define LLDB_OPTIONS_breakpoint_add_address
Definition at line 320 of file CommandObjectBreakpoint.cpp.
LLDB_OPTIONS_breakpoint_add_exception
#define LLDB_OPTIONS_breakpoint_add_exception
Definition at line 528 of file CommandObjectBreakpoint.cpp.
LLDB_OPTIONS_breakpoint_add_file
#define LLDB_OPTIONS_breakpoint_add_file
Definition at line 673 of file CommandObjectBreakpoint.cpp.
LLDB_OPTIONS_breakpoint_add_name
#define LLDB_OPTIONS_breakpoint_add_name
Definition at line 954 of file CommandObjectBreakpoint.cpp.
LLDB_OPTIONS_breakpoint_add_pattern
#define LLDB_OPTIONS_breakpoint_add_pattern
Definition at line 1147 of file CommandObjectBreakpoint.cpp.
LLDB_OPTIONS_breakpoint_add_scripted
#define LLDB_OPTIONS_breakpoint_add_scripted
Definition at line 1340 of file CommandObjectBreakpoint.cpp.
LLDB_OPTIONS_breakpoint_clear
#define LLDB_OPTIONS_breakpoint_clear
Definition at line 2436 of file CommandObjectBreakpoint.cpp.
LLDB_OPTIONS_breakpoint_delete
#define LLDB_OPTIONS_breakpoint_delete
Definition at line 2573 of file CommandObjectBreakpoint.cpp.
LLDB_OPTIONS_breakpoint_dummy
#define LLDB_OPTIONS_breakpoint_dummy
Definition at line 282 of file CommandObjectBreakpoint.cpp.
LLDB_OPTIONS_breakpoint_list
#define LLDB_OPTIONS_breakpoint_list
Definition at line 2306 of file CommandObjectBreakpoint.cpp.
LLDB_OPTIONS_breakpoint_modify
#define LLDB_OPTIONS_breakpoint_modify
Definition at line 82 of file CommandObjectBreakpoint.cpp.
LLDB_OPTIONS_breakpoint_name
#define LLDB_OPTIONS_breakpoint_name
Definition at line 2753 of file CommandObjectBreakpoint.cpp.
LLDB_OPTIONS_breakpoint_names
#define LLDB_OPTIONS_breakpoint_names
Definition at line 238 of file CommandObjectBreakpoint.cpp.
LLDB_OPTIONS_breakpoint_read
#define LLDB_OPTIONS_breakpoint_read
Definition at line 3310 of file CommandObjectBreakpoint.cpp.
LLDB_OPTIONS_breakpoint_set
#define LLDB_OPTIONS_breakpoint_set
Definition at line 1503 of file CommandObjectBreakpoint.cpp.
LLDB_OPTIONS_breakpoint_write
#define LLDB_OPTIONS_breakpoint_write
Definition at line 3491 of file CommandObjectBreakpoint.cpp.
Function Documentation
AddBreakpointDescription()
void AddBreakpointDescription (Stream * s, Breakpoint * bp, lldb::DescriptionLevel level) static
Definition at line 40 of file CommandObjectBreakpoint.cpp.
References lldb_private::Stream::EOL(), lldb_private::Breakpoint::GetDescription(), lldb_private::Stream::IndentLess(), and lldb_private::Stream::IndentMore().
Referenced by CommandObjectBreakpointList::DoExecute().
CompleteLineEntry()
Status CompleteLineEntry (ExecutionContext & exe_ctx, OptionValueFileColonLine & line_entry) static
Definition at line 362 of file CommandObjectBreakpoint.cpp.
References error(), lldb_private::Target::GetDebugger(), GetDefaultFile(), lldb_private::CommandReturnObject::GetErrorString(), lldb_private::OptionValueFileColonLine::GetFileSpec(), lldb_private::ExecutionContext::GetFramePtr(), lldb_private::OptionValueFileColonLine::GetLineNumber(), lldb_private::ExecutionContext::GetTargetPtr(), lldb_private::Debugger::GetUseColor(), and lldb_private::OptionValueFileColonLine::SetFile().
Referenced by CommandObjectBreakpointAddFile::CommandOptions::OptionParsingFinished(), and CommandObjectBreakpointAddFile::CommandOptions::SetOptionValue().
CopyOverBreakpointOptions()
bool CopyOverBreakpointOptions (BreakpointSP bp_sp, BreakpointOptionGroup & bp_opts, const std::vector< std::string > & bp_names, CommandReturnObject & result) static
Definition at line 325 of file CommandObjectBreakpoint.cpp.
References lldb_private::Target::AddNameToBreakpoint(), lldb_private::CommandReturnObject::AppendErrorWithFormat(), lldb_private::Status::Fail(), lldb_private::BreakpointOptionGroup::GetBreakpointOptions(), and lldb_private::Target::RemoveBreakpointByID().
Referenced by CommandObjectBreakpointAddAddress::DoExecute(), CommandObjectBreakpointAddException::DoExecute(), CommandObjectBreakpointAddFile::DoExecute(), CommandObjectBreakpointAddName::DoExecute(), CommandObjectBreakpointAddPattern::DoExecute(), and CommandObjectBreakpointAddScripted::DoExecute().
GetDefaultFile()
bool GetDefaultFile (Target & target, StackFrame * cur_frame, FileSpec & file, CommandReturnObject & result) static
Definition at line 48 of file CommandObjectBreakpoint.cpp.
References lldb_private::CommandReturnObject::AppendError(), lldb_private::SourceManager::GetDefaultFileAndLine(), lldb_private::LineEntry::GetFile(), lldb_private::Target::GetSourceManager(), lldb_private::StackFrame::GetSymbolContext(), lldb_private::StackFrame::HasDebugInformation(), and lldb_private::SymbolContext::line_entry.
Referenced by CompleteLineEntry(), CommandObjectBreakpointAddFile::DoExecute(), CommandObjectBreakpointAddPattern::DoExecute(), and CommandObjectBreakpointSet::DoExecute().
GetExceptionLanguageForLanguage()
llvm::Expected< LanguageType > GetExceptionLanguageForLanguage (llvm::StringRef lang_name, char short_option = '\0', llvm::StringRef long_option = {}) static
Definition at line 349 of file CommandObjectBreakpoint.cpp.
Referenced by CommandObjectBreakpointAddException::DoExecute(), and CommandObjectBreakpointSet::CommandOptions::SetOptionValue().