LLDB: ConstString.cpp File Reference
ConstString.cpp File Reference
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/Stream.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/iterator.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/DJB.h"
#include "llvm/Support/FormatProviders.h"
#include "llvm/Support/RWMutex.h"
#include "llvm/Support/Threading.h"
#include <array>
#include <utility>
#include <cinttypes>
#include <cstdint>
#include <cstring>
Classes
class Pool
struct Pool::PoolEntry
Functions
static Pool & StringPool ()
Function Documentation
StringPool()
Pool & StringPool () static
Definition at line 201 of file ConstString.cpp.
Referenced by lldb_private::ConstString::ConstString(), lldb_private::ConstString::ConstString(), lldb_private::ConstString::ConstString(), lldb_private::ConstString::GetMangledCounterpart(), lldb_private::ConstString::GetMemoryStats(), lldb_private::ConstString::SetCString(), lldb_private::ConstString::SetCStringWithLength(), lldb_private::ConstString::SetString(), lldb_private::ConstString::SetStringWithMangledCounterpart(), and lldb_private::ConstString::SetTrimmedCStringWithLength().