LLDB: CoreFileMemoryRanges.cpp File Reference
CoreFileMemoryRanges.cpp File Reference
#include "lldb/Target/CoreFileMemoryRanges.h"
Typedefs
using Entry = CoreFileMemoryRanges::Entry
Functions
static bool Overlaps (const Entry *region_one, const Entry *region_two)
static bool IntersectHelper (const Entry *region_one, const Entry *region_two)
static bool OnlyIntersects (const Entry *region_one, const Entry *region_two)
static bool PermissionsMatch (const Entry *region_one, const Entry *region_two)
Typedef Documentation
Entry
using Entry = CoreFileMemoryRanges::Entry
Definition at line 14 of file CoreFileMemoryRanges.cpp.
Function Documentation
IntersectHelper()
bool IntersectHelper (const Entry * region_one, const Entry * region_two) static
Definition at line 21 of file CoreFileMemoryRanges.cpp.
Referenced by OnlyIntersects().
OnlyIntersects()
bool OnlyIntersects (const Entry * region_one, const Entry * region_two) static
Definition at line 26 of file CoreFileMemoryRanges.cpp.
References IntersectHelper().
Referenced by lldb_private::CoreFileMemoryRanges::FinalizeCoreFileSaveRanges().
Overlaps()
bool Overlaps (const Entry * region_one, const Entry * region_two) static
Definition at line 16 of file CoreFileMemoryRanges.cpp.
Referenced by lldb_private::CoreFileMemoryRanges::FinalizeCoreFileSaveRanges(), and lldb_private::RegisterFlags::Field::PaddingDistance().
PermissionsMatch()
bool PermissionsMatch (const Entry * region_one, const Entry * region_two) static
Definition at line 31 of file CoreFileMemoryRanges.cpp.
Referenced by lldb_private::CoreFileMemoryRanges::FinalizeCoreFileSaveRanges().