LLDB: Coroutines.cpp File Reference
Coroutines.cpp File Reference
#include "Coroutines.h"
#include "Plugins/TypeSystem/Clang/TypeSystemClang.h"
#include "lldb/Symbol/Function.h"
#include "lldb/Symbol/VariableList.h"
Functions
static lldb::addr_t GetCoroFramePtrFromHandle (ValueObjectSP valobj_sp)
static Function * ExtractDestroyFunction (lldb::TargetSP target_sp, lldb::addr_t frame_ptr_addr)
static CompilerType InferArtificialCoroType (Function *destroy_func, ConstString var_name)
Function Documentation
ExtractDestroyFunction()
Function * ExtractDestroyFunction (lldb::TargetSP target_sp, lldb::addr_t frame_ptr_addr) static
Definition at line 43 of file Coroutines.cpp.
References lldb_private::Address::CalculateSymbolContextFunction(), and error().
Referenced by lldb_private::formatters::StdlibCoroutineHandleSyntheticFrontEnd::Update().
GetCoroFramePtrFromHandle()
lldb::addr_t GetCoroFramePtrFromHandle (ValueObjectSP valobj_sp) static
Definition at line 19 of file Coroutines.cpp.
References lldb_private::eAddressTypeLoad, LLDB_INVALID_ADDRESS, and lldbassert.
Referenced by lldb_private::formatters::StdlibCoroutineHandleSummaryProvider(), and lldb_private::formatters::StdlibCoroutineHandleSyntheticFrontEnd::Update().
InferArtificialCoroType()
CompilerType InferArtificialCoroType (Function * destroy_func, ConstString var_name) static
Definition at line 64 of file Coroutines.cpp.
References lldb_private::Function::GetBlock(), lldb_private::Block::GetBlockVariableList(), and lldb_private::Type::GetForwardCompilerType().
Referenced by lldb_private::formatters::StdlibCoroutineHandleSyntheticFrontEnd::Update().