LLDB: CPlusPlusLanguage.cpp File Reference
CPlusPlusLanguage.cpp File Reference
#include "CPlusPlusLanguage.h"
#include <cctype>
#include <cstring>
#include <functional>
#include <memory>
#include <mutex>
#include <set>
#include "llvm/ADT/StringRef.h"
#include "llvm/Demangle/ItaniumDemangle.h"
#include "lldb/Core/DemangledNameInfo.h"
#include "lldb/Core/Mangled.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/UniqueCStringMap.h"
#include "lldb/DataFormatters/CXXFunctionPointer.h"
#include "lldb/DataFormatters/DataVisualization.h"
#include "lldb/DataFormatters/FormattersHelpers.h"
#include "lldb/DataFormatters/VectorType.h"
#include "lldb/Interpreter/OptionValueProperties.h"
#include "lldb/Symbol/SymbolFile.h"
#include "lldb/Symbol/VariableList.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/RegularExpression.h"
#include "lldb/ValueObject/ValueObjectVariable.h"
#include "BlockPointer.h"
#include "CPlusPlusNameParser.h"
#include "Coroutines.h"
#include "CxxStringTypes.h"
#include "Generic.h"
#include "LibCxx.h"
#include "LibCxxAtomic.h"
#include "LibCxxVariant.h"
#include "LibStdcpp.h"
#include "MSVCUndecoratedNameParser.h"
#include "MsvcStl.h"
#include "lldb/lldb-enumerations.h"
#include "LanguageCPlusPlusProperties.inc"
#include "LanguageCPlusPlusPropertiesEnum.inc"
Macros
#define LLDB_PROPERTIES_language_cplusplus
#define LLDB_PROPERTIES_language_cplusplus
Enumerations
enum
Functions
static bool ReverseFindMatchingChars (const llvm::StringRef &s, const llvm::StringRef &left_right_chars, size_t &left_pos, size_t &right_pos, size_t pos=llvm::StringRef::npos)
static bool IsTrivialBasename (const llvm::StringRef &basename)
static bool IsTrivialContext (llvm::StringRef context)
A context is trivial if an only if it matches this pattern.
static bool PrettyPrintFunctionNameWithArgs (Stream &out_stream, char const *full_name, ExecutionContextScope *exe_scope, VariableList const &args)
Writes out the function name in 'full_name' to 'out_stream' but replaces each argument type with the variable name and the corresponding pretty-printed value.
static llvm::Expected< std::pair< llvm::StringRef, DemangledNameInfo > > GetAndValidateInfo (const SymbolContext &sc)
static llvm::Expected< llvm::StringRef > GetDemangledBasename (const SymbolContext &sc)
static llvm::Expected< llvm::StringRef > GetDemangledTemplateArguments (const SymbolContext &sc)
static llvm::Expected< llvm::StringRef > GetDemangledReturnTypeLHS (const SymbolContext &sc)
static llvm::Expected< llvm::StringRef > GetDemangledFunctionQualifiers (const SymbolContext &sc)
static llvm::Expected< llvm::StringRef > GetDemangledReturnTypeRHS (const SymbolContext &sc)
static llvm::Expected< llvm::StringRef > GetDemangledScope (const SymbolContext &sc)
static llvm::Expected< llvm::StringRef > GetDemangledFunctionSuffix (const SymbolContext &sc)
static bool PrintDemangledArgumentList (Stream &s, const SymbolContext &sc)
static void LoadLibCxxFormatters (lldb::TypeCategoryImplSP cpp_category_sp)
static void RegisterStdStringSummaryProvider (const lldb::TypeCategoryImplSP &category_sp, llvm::StringRef string_ty, llvm::StringRef char_ty, lldb::TypeSummaryImplSP summary_sp)
static void RegisterStdStringViewSummaryProvider (const lldb::TypeCategoryImplSP &category_sp, llvm::StringRef string_ty, llvm::StringRef char_ty, lldb::TypeSummaryImplSP summary_sp)
static void LoadLibStdcppFormatters (lldb::TypeCategoryImplSP cpp_category_sp)
static lldb_private::SyntheticChildrenFrontEnd * GenericSmartPointerSyntheticFrontEndCreator (CXXSyntheticChildren *children, lldb::ValueObjectSP valobj_sp)
static bool GenericSmartPointerSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
static lldb_private::SyntheticChildrenFrontEnd * GenericUniquePtrSyntheticFrontEndCreator (CXXSyntheticChildren *children, lldb::ValueObjectSP valobj_sp)
static bool GenericUniquePtrSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
static SyntheticChildrenFrontEnd * GenericTupleSyntheticFrontEndCreator (CXXSyntheticChildren *children, lldb::ValueObjectSP valobj_sp)
static SyntheticChildrenFrontEnd * GenericVectorSyntheticFrontEndCreator (CXXSyntheticChildren *children, lldb::ValueObjectSP valobj_sp)
static SyntheticChildrenFrontEnd * GenericListSyntheticFrontEndCreator (CXXSyntheticChildren *children, lldb::ValueObjectSP valobj_sp)
static SyntheticChildrenFrontEnd * GenericForwardListSyntheticFrontEndCreator (CXXSyntheticChildren *children, lldb::ValueObjectSP valobj_sp)
static SyntheticChildrenFrontEnd * GenericOptionalSyntheticFrontEndCreator (CXXSyntheticChildren *children, lldb::ValueObjectSP valobj_sp)
static SyntheticChildrenFrontEnd * GenericVariantSyntheticFrontEndCreator (CXXSyntheticChildren *children, lldb::ValueObjectSP valobj_sp)
static bool GenericVariantSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
static SyntheticChildrenFrontEnd * GenericUnorderedSyntheticFrontEndCreator (CXXSyntheticChildren *children, ValueObjectSP valobj_sp)
static SyntheticChildrenFrontEnd * GenericMapLikeSyntheticFrontEndCreator (CXXSyntheticChildren *children, ValueObjectSP valobj_sp)
static SyntheticChildrenFrontEnd * GenericDequeSyntheticFrontEndCreator (CXXSyntheticChildren *children, ValueObjectSP valobj_sp)
static SyntheticChildrenFrontEnd * GenericSpanSyntheticFrontEndCreator (CXXSyntheticChildren *children, ValueObjectSP valobj_sp)
static bool GenericPartialOrderingSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
static bool GenericWeakOrderingSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
static bool GenericStrongOrderingSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
static void LoadCommonStlFormatters (lldb::TypeCategoryImplSP cpp_category_sp)
Load formatters that are formatting types from more than one STL.
static void LoadMsvcStlFormatters (lldb::TypeCategoryImplSP cpp_category_sp)
static void LoadSystemFormatters (lldb::TypeCategoryImplSP cpp_category_sp)
static VariableListSP GetFunctionVariableList (const SymbolContext &sc)
static bool PrintFunctionNameWithArgs (Stream &s, const ExecutionContext *exe_ctx, const SymbolContext &sc)
static PluginProperties & GetGlobalPluginProperties ()
Macro Definition Documentation
LLDB_PROPERTIES_language_cplusplus [1/2]
#define LLDB_PROPERTIES_language_cplusplus
Definition at line 2600 of file CPlusPlusLanguage.cpp.
LLDB_PROPERTIES_language_cplusplus [2/2]
#define LLDB_PROPERTIES_language_cplusplus
Definition at line 2600 of file CPlusPlusLanguage.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Definition at line 2603 of file CPlusPlusLanguage.cpp.
Function Documentation
GenericDequeSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * GenericDequeSyntheticFrontEndCreator (CXXSyntheticChildren * children, ValueObjectSP valobj_sp) static
Definition at line 1670 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::IsMsvcStlDeque(), and lldb_private::formatters::MsvcStlDequeSyntheticFrontEndCreator().
Referenced by LoadCommonStlFormatters().
GenericForwardListSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * GenericForwardListSyntheticFrontEndCreator (CXXSyntheticChildren * children, lldb::ValueObjectSP valobj_sp) static
Definition at line 1602 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::IsMsvcStlList(), and lldb_private::formatters::MsvcStlForwardListSyntheticFrontEndCreator().
Referenced by LoadCommonStlFormatters().
GenericListSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * GenericListSyntheticFrontEndCreator (CXXSyntheticChildren * children, lldb::ValueObjectSP valobj_sp) static
Definition at line 1590 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::IsMsvcStlList(), and lldb_private::formatters::MsvcStlListSyntheticFrontEndCreator().
Referenced by LoadCommonStlFormatters().
GenericMapLikeSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * GenericMapLikeSyntheticFrontEndCreator (CXXSyntheticChildren * children, ValueObjectSP valobj_sp) static
Definition at line 1658 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::IsMsvcStlMapLike(), and lldb_private::formatters::MsvcStlMapLikeSyntheticFrontEndCreator().
Referenced by LoadCommonStlFormatters().
GenericOptionalSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * GenericOptionalSyntheticFrontEndCreator (CXXSyntheticChildren * children, lldb::ValueObjectSP valobj_sp) static
Definition at line 1615 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::IsMsvcStlOptional(), lldb_private::formatters::LibStdcppOptionalSyntheticFrontEndCreator(), and lldb_private::formatters::MsvcStlOptionalSyntheticFrontEndCreator().
Referenced by LoadCommonStlFormatters().
GenericPartialOrderingSummaryProvider()
bool GenericPartialOrderingSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options) static
Definition at line 1693 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::IsMsvcStlOrdering(), lldb_private::formatters::LibStdcppPartialOrderingSummaryProvider(), and lldb_private::formatters::MsvcStlPartialOrderingSummaryProvider().
Referenced by LoadCommonStlFormatters().
GenericSmartPointerSummaryProvider()
bool GenericSmartPointerSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options) static
Definition at line 1539 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::IsMsvcStlSmartPointer(), lldb_private::formatters::LibStdcppSmartPointerSummaryProvider(), and lldb_private::formatters::MsvcStlSmartPointerSummaryProvider().
Referenced by LoadCommonStlFormatters().
GenericSmartPointerSyntheticFrontEndCreator()
lldb_private::SyntheticChildrenFrontEnd * GenericSmartPointerSyntheticFrontEndCreator (CXXSyntheticChildren * children, lldb::ValueObjectSP valobj_sp) static
Definition at line 1528 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::IsMsvcStlSmartPointer(), lldb_private::formatters::LibStdcppSharedPtrSyntheticFrontEndCreator(), and lldb_private::formatters::MsvcStlSmartPointerSyntheticFrontEndCreator().
Referenced by LoadCommonStlFormatters().
GenericSpanSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * GenericSpanSyntheticFrontEndCreator (CXXSyntheticChildren * children, ValueObjectSP valobj_sp) static
Definition at line 1682 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::IsMsvcStlSpan(), lldb_private::formatters::LibStdcppSpanSyntheticFrontEndCreator(), and lldb_private::formatters::MsvcStlSpanSyntheticFrontEndCreator().
Referenced by LoadCommonStlFormatters().
GenericStrongOrderingSummaryProvider()
bool GenericStrongOrderingSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options) static
Definition at line 1709 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::IsMsvcStlOrdering(), lldb_private::formatters::LibStdcppStrongOrderingSummaryProvider(), and lldb_private::formatters::MsvcStlStrongOrderingSummaryProvider().
Referenced by LoadCommonStlFormatters().
GenericTupleSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * GenericTupleSyntheticFrontEndCreator (CXXSyntheticChildren * children, lldb::ValueObjectSP valobj_sp) static
Definition at line 1565 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::IsMsvcStlTuple(), lldb_private::formatters::LibStdcppTupleSyntheticFrontEndCreator(), and lldb_private::formatters::MsvcStlTupleSyntheticFrontEndCreator().
Referenced by LoadCommonStlFormatters().
GenericUniquePtrSummaryProvider()
bool GenericUniquePtrSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options) static
Definition at line 1557 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::IsMsvcStlUniquePtr(), lldb_private::formatters::LibStdcppUniquePointerSummaryProvider(), and lldb_private::formatters::MsvcStlUniquePtrSummaryProvider().
Referenced by LoadCommonStlFormatters().
GenericUniquePtrSyntheticFrontEndCreator()
lldb_private::SyntheticChildrenFrontEnd * GenericUniquePtrSyntheticFrontEndCreator (CXXSyntheticChildren * children, lldb::ValueObjectSP valobj_sp) static
Definition at line 1547 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::IsMsvcStlUniquePtr(), lldb_private::formatters::LibStdcppUniquePtrSyntheticFrontEndCreator(), and lldb_private::formatters::MsvcStlUniquePtrSyntheticFrontEndCreator().
Referenced by LoadCommonStlFormatters().
GenericUnorderedSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * GenericUnorderedSyntheticFrontEndCreator (CXXSyntheticChildren * children, ValueObjectSP valobj_sp) static
Definition at line 1645 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::IsMsvcStlUnordered(), and lldb_private::formatters::MsvcStlUnorderedSyntheticFrontEndCreator().
Referenced by LoadCommonStlFormatters().
GenericVariantSummaryProvider()
bool GenericVariantSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options) static
Definition at line 1637 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::IsMsvcStlVariant(), lldb_private::formatters::LibStdcppVariantSummaryProvider(), and lldb_private::formatters::MsvcStlVariantSummaryProvider().
Referenced by LoadCommonStlFormatters().
GenericVariantSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * GenericVariantSyntheticFrontEndCreator (CXXSyntheticChildren * children, lldb::ValueObjectSP valobj_sp) static
Definition at line 1626 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::IsMsvcStlVariant(), and lldb_private::formatters::MsvcStlVariantSyntheticFrontEndCreator().
Referenced by LoadCommonStlFormatters().
GenericVectorSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * GenericVectorSyntheticFrontEndCreator (CXXSyntheticChildren * children, lldb::ValueObjectSP valobj_sp) static
Definition at line 1576 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::MsvcStlVectorSyntheticFrontEndCreator().
Referenced by LoadCommonStlFormatters().
GenericWeakOrderingSummaryProvider()
bool GenericWeakOrderingSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options) static
Definition at line 1701 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::IsMsvcStlOrdering(), lldb_private::formatters::LibStdcppWeakOrderingSummaryProvider(), and lldb_private::formatters::MsvcStlWeakOrderingSummaryProvider().
Referenced by LoadCommonStlFormatters().
GetAndValidateInfo()
llvm::Expected< std::pair< llvm::StringRef, DemangledNameInfo > > GetAndValidateInfo (const SymbolContext & sc) static
Definition at line 260 of file CPlusPlusLanguage.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::Mangled::GetDemangledInfo(), lldb_private::Mangled::GetDemangledName(), lldb_private::Mangled::GetMangledName(), lldb_private::SymbolContext::GetPossiblyInlinedFunctionName(), and lldb_private::ConstString::GetStringRef().
Referenced by GetDemangledBasename(), GetDemangledFunctionQualifiers(), GetDemangledFunctionSuffix(), GetDemangledReturnTypeLHS(), GetDemangledReturnTypeRHS(), GetDemangledScope(), GetDemangledTemplateArguments(), and PrintDemangledArgumentList().
GetDemangledBasename()
llvm::Expected< llvm::StringRef > GetDemangledBasename (const SymbolContext & sc) static
Definition at line 286 of file CPlusPlusLanguage.cpp.
References GetAndValidateInfo(), and lldb_private::CPlusPlusLanguage::GetDemangledBasename().
GetDemangledFunctionQualifiers()
llvm::Expected< llvm::StringRef > GetDemangledFunctionQualifiers (const SymbolContext & sc) static
Definition at line 358 of file CPlusPlusLanguage.cpp.
References GetAndValidateInfo(), and lldb_private::CPlusPlusLanguage::GetDemangledFunctionQualifiers().
GetDemangledFunctionSuffix()
llvm::Expected< llvm::StringRef > GetDemangledFunctionSuffix (const SymbolContext & sc) static
Definition at line 424 of file CPlusPlusLanguage.cpp.
References GetAndValidateInfo(), and lldb_private::CPlusPlusLanguage::GetDemangledFunctionSuffix().
GetDemangledReturnTypeLHS()
llvm::Expected< llvm::StringRef > GetDemangledReturnTypeLHS (const SymbolContext & sc) static
Definition at line 336 of file CPlusPlusLanguage.cpp.
References GetAndValidateInfo(), and lldb_private::CPlusPlusLanguage::GetDemangledReturnTypeLHS().
GetDemangledReturnTypeRHS()
llvm::Expected< llvm::StringRef > GetDemangledReturnTypeRHS (const SymbolContext & sc) static
Definition at line 382 of file CPlusPlusLanguage.cpp.
References GetAndValidateInfo(), and lldb_private::CPlusPlusLanguage::GetDemangledReturnTypeRHS().
GetDemangledScope()
llvm::Expected< llvm::StringRef > GetDemangledScope (const SymbolContext & sc) static
Definition at line 403 of file CPlusPlusLanguage.cpp.
References GetAndValidateInfo(), and lldb_private::CPlusPlusLanguage::GetDemangledScope().
GetDemangledTemplateArguments()
llvm::Expected< llvm::StringRef > GetDemangledTemplateArguments (const SymbolContext & sc) static
Definition at line 315 of file CPlusPlusLanguage.cpp.
References GetAndValidateInfo(), and lldb_private::CPlusPlusLanguage::GetDemangledTemplateArguments().
GetFunctionVariableList()
VariableListSP GetFunctionVariableList (const SymbolContext & sc) static
Definition at line 2253 of file CPlusPlusLanguage.cpp.
References lldb_private::SymbolContext::block, lldb_private::SymbolContext::function, lldb_private::Function::GetBlock(), lldb_private::Block::GetBlockVariableList(), and lldb_private::Block::GetContainingInlinedBlock().
GetGlobalPluginProperties()
PluginProperties & GetGlobalPluginProperties () static
Definition at line 2625 of file CPlusPlusLanguage.cpp.
IsTrivialBasename()
bool IsTrivialBasename (const llvm::StringRef & basename) static
Definition at line 181 of file CPlusPlusLanguage.cpp.
Referenced by lldb_private::CPlusPlusLanguage::CxxMethodName::TrySimplifiedParse().
IsTrivialContext()
bool IsTrivialContext (llvm::StringRef context) static
A context is trivial if an only if it matches this pattern.
"^\s*([A-Za-z_:]*)\s*$". for example function foo::bar::func() has a trivial context but. but foo<int>::bar::func() doesn't.
Definition at line 214 of file CPlusPlusLanguage.cpp.
Referenced by lldb_private::CPlusPlusLanguage::CxxMethodName::TrySimplifiedParse().
LoadCommonStlFormatters()
void LoadCommonStlFormatters (lldb::TypeCategoryImplSP cpp_category_sp) static
Load formatters that are formatting types from more than one STL.
Definition at line 1717 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::AddCXXSummary(), lldb_private::formatters::AddCXXSynthetic(), lldb_private::formatters::ContainerSizeSummaryProvider(), lldb::eFormatterMatchRegex, GenericDequeSyntheticFrontEndCreator(), GenericForwardListSyntheticFrontEndCreator(), lldb_private::formatters::GenericInitializerListSyntheticFrontEndCreator(), GenericListSyntheticFrontEndCreator(), GenericMapLikeSyntheticFrontEndCreator(), lldb_private::formatters::GenericOptionalSummaryProvider(), GenericOptionalSyntheticFrontEndCreator(), GenericPartialOrderingSummaryProvider(), GenericSmartPointerSummaryProvider(), GenericSmartPointerSyntheticFrontEndCreator(), GenericSpanSyntheticFrontEndCreator(), GenericStrongOrderingSummaryProvider(), GenericTupleSyntheticFrontEndCreator(), GenericUniquePtrSummaryProvider(), GenericUniquePtrSyntheticFrontEndCreator(), GenericUnorderedSyntheticFrontEndCreator(), GenericVariantSummaryProvider(), GenericVariantSyntheticFrontEndCreator(), GenericVectorSyntheticFrontEndCreator(), GenericWeakOrderingSummaryProvider(), lldb_private::formatters::IsMsvcStlStringType(), lldb_private::formatters::IsMsvcStlStringViewType(), lldb_private::formatters::LibStdcppStringSummaryProvider(), lldb_private::formatters::LibStdcppWStringViewSummaryProvider(), lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::ASCII >(), lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::UTF16 >(), lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::UTF32 >(), lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::UTF8 >(), lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::ASCII >(), lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::ASCII >(), lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::UTF16 >(), lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::UTF32 >(), lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::UTF8 >(), lldb_private::formatters::MsvcStlWStringSummaryProvider(), lldb_private::formatters::MsvcStlWStringViewSummaryProvider(), RegisterStdStringSummaryProvider(), RegisterStdStringViewSummaryProvider(), lldb_private::SyntheticChildren::Flags::SetCascades(), lldb_private::TypeSummaryImpl::Flags::SetCascades(), lldb_private::TypeSummaryImpl::Flags::SetDontShowChildren(), lldb_private::TypeSummaryImpl::Flags::SetDontShowValue(), lldb_private::SyntheticChildren::Flags::SetFrontEndWantsDereference(), lldb_private::TypeSummaryImpl::Flags::SetHideItemNames(), lldb_private::TypeSummaryImpl::Flags::SetShowMembersOneLiner(), lldb_private::SyntheticChildren::Flags::SetSkipPointers(), lldb_private::TypeSummaryImpl::Flags::SetSkipPointers(), lldb_private::SyntheticChildren::Flags::SetSkipReferences(), and lldb_private::TypeSummaryImpl::Flags::SetSkipReferences().
Referenced by lldb_private::CPlusPlusLanguage::GetFormatters().
LoadLibCxxFormatters()
void LoadLibCxxFormatters (lldb::TypeCategoryImplSP cpp_category_sp) static
Definition at line 746 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::AddCXXSummary(), lldb_private::formatters::AddCXXSynthetic(), lldb_private::formatters::ContainerSizeSummaryProvider(), lldb::eFormatterMatchRegex, lldb_private::formatters::GenericOptionalSummaryProvider(), lldb_private::formatters::LibCxxAtomicSummaryProvider(), lldb_private::formatters::LibcxxAtomicSyntheticFrontEndCreator(), lldb_private::formatters::LibcxxBitsetSyntheticFrontEndCreator(), lldb_private::formatters::LibcxxChronoLocalDaysSummaryProvider(), lldb_private::formatters::LibcxxChronoLocalSecondsSummaryProvider(), lldb_private::formatters::LibcxxChronoMonthSummaryProvider(), lldb_private::formatters::LibcxxChronoSysDaysSummaryProvider(), lldb_private::formatters::LibcxxChronoSysSecondsSummaryProvider(), lldb_private::formatters::LibcxxChronoWeekdaySummaryProvider(), lldb_private::formatters::LibcxxChronoYearMonthDaySummaryProvider(), lldb_private::formatters::LibcxxFunctionSummaryProvider(), lldb_private::formatters::LibCxxMapIteratorSyntheticFrontEndCreator(), lldb_private::formatters::LibcxxOptionalSyntheticFrontEndCreator(), lldb_private::formatters::LibcxxPartialOrderingSummaryProvider(), lldb_private::formatters::LibcxxQueueFrontEndCreator(), lldb_private::formatters::LibcxxSharedPtrSyntheticFrontEndCreator(), lldb_private::formatters::LibcxxSmartPointerSummaryProvider(), lldb_private::formatters::LibcxxStdForwardListSyntheticFrontEndCreator(), lldb_private::formatters::LibcxxStdListSyntheticFrontEndCreator(), lldb_private::formatters::LibcxxStdMapSyntheticFrontEndCreator(), lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEndCreator(), lldb_private::formatters::LibcxxStdRangesRefViewSyntheticFrontEndCreator(), lldb_private::formatters::LibcxxStdSliceArraySummaryProvider(), lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEndCreator(), lldb_private::formatters::LibcxxStdSpanSyntheticFrontEndCreator(), lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEndCreator(), lldb_private::formatters::LibcxxStdValarraySyntheticFrontEndCreator(), lldb_private::formatters::LibcxxStdVectorSyntheticFrontEndCreator(), lldb_private::formatters::LibcxxStringSummaryProviderASCII(), lldb_private::formatters::LibcxxStringSummaryProviderUTF16(), lldb_private::formatters::LibcxxStringSummaryProviderUTF32(), lldb_private::formatters::LibcxxStringViewSummaryProviderASCII(), lldb_private::formatters::LibcxxStringViewSummaryProviderUTF16(), lldb_private::formatters::LibcxxStringViewSummaryProviderUTF32(), lldb_private::formatters::LibcxxStrongOrderingSummaryProvider(), lldb_private::formatters::LibcxxTupleFrontEndCreator(), lldb_private::formatters::LibcxxUniquePointerSummaryProvider(), lldb_private::formatters::LibcxxUniquePtrSyntheticFrontEndCreator(), lldb_private::formatters::LibCxxUnorderedMapIteratorSyntheticFrontEndCreator(), lldb_private::formatters::LibcxxVariantFrontEndCreator(), lldb_private::formatters::LibcxxVariantSummaryProvider(), lldb_private::formatters::LibCxxVectorIteratorSyntheticFrontEndCreator(), lldb_private::formatters::LibcxxWeakOrderingSummaryProvider(), lldb_private::formatters::LibcxxWStringSummaryProvider(), lldb_private::formatters::LibcxxWStringViewSummaryProvider(), lldb_private::SyntheticChildren::Flags::SetCascades(), lldb_private::TypeSummaryImpl::Flags::SetCascades(), lldb_private::TypeSummaryImpl::Flags::SetDontShowChildren(), lldb_private::TypeSummaryImpl::Flags::SetDontShowValue(), lldb_private::SyntheticChildren::Flags::SetFrontEndWantsDereference(), lldb_private::TypeSummaryImpl::Flags::SetHideItemNames(), lldb_private::TypeSummaryImpl::Flags::SetShowMembersOneLiner(), lldb_private::SyntheticChildren::Flags::SetSkipPointers(), lldb_private::TypeSummaryImpl::Flags::SetSkipPointers(), lldb_private::SyntheticChildren::Flags::SetSkipReferences(), lldb_private::TypeSummaryImpl::Flags::SetSkipReferences(), lldb_private::formatters::StdlibCoroutineHandleSummaryProvider(), and lldb_private::formatters::StdlibCoroutineHandleSyntheticFrontEndCreator().
Referenced by lldb_private::CPlusPlusLanguage::GetFormatters().
LoadLibStdcppFormatters()
void LoadLibStdcppFormatters (lldb::TypeCategoryImplSP cpp_category_sp) static
Definition at line 1352 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::AddCXXSummary(), lldb_private::formatters::AddCXXSynthetic(), lldb_private::formatters::ContainerSizeSummaryProvider(), lldb::eFormatterMatchExact, lldb::eFormatterMatchRegex, lldb_private::formatters::LibStdcppBitsetSyntheticFrontEndCreator(), lldb_private::formatters::LibstdcppMapIteratorSyntheticFrontEndCreator(), lldb_private::formatters::LibStdcppStringSummaryProvider(), lldb_private::formatters::LibStdcppUniquePtrSyntheticFrontEndCreator(), lldb_private::formatters::LibStdcppVectorIteratorSyntheticFrontEndCreator(), lldb_private::SyntheticChildren::Flags::SetCascades(), lldb_private::TypeSummaryImpl::Flags::SetCascades(), lldb_private::TypeSummaryImpl::Flags::SetDontShowChildren(), lldb_private::TypeSummaryImpl::Flags::SetDontShowValue(), lldb_private::SyntheticChildren::Flags::SetFrontEndWantsDereference(), lldb_private::TypeSummaryImpl::Flags::SetHideItemNames(), lldb_private::TypeSummaryImpl::Flags::SetShowMembersOneLiner(), lldb_private::SyntheticChildren::Flags::SetSkipPointers(), lldb_private::TypeSummaryImpl::Flags::SetSkipPointers(), lldb_private::SyntheticChildren::Flags::SetSkipReferences(), lldb_private::TypeSummaryImpl::Flags::SetSkipReferences(), lldb_private::formatters::StdlibCoroutineHandleSummaryProvider(), and lldb_private::formatters::StdlibCoroutineHandleSyntheticFrontEndCreator().
Referenced by lldb_private::CPlusPlusLanguage::GetFormatters().
LoadMsvcStlFormatters()
void LoadMsvcStlFormatters (lldb::TypeCategoryImplSP cpp_category_sp) static
Definition at line 1940 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::AddCXXSummary(), lldb_private::formatters::AddCXXSynthetic(), lldb_private::formatters::MsvcStlAtomicSummaryProvider(), lldb_private::formatters::MsvcStlAtomicSyntheticFrontEndCreator(), lldb_private::formatters::MsvcStlStringSummaryProvider(), lldb_private::formatters::MsvcStlTreeIterSummaryProvider(), lldb_private::formatters::MsvcStlTreeIterSyntheticFrontEndCreator(), RegisterStdStringSummaryProvider(), lldb_private::SyntheticChildren::Flags::SetCascades(), lldb_private::TypeSummaryImpl::Flags::SetCascades(), lldb_private::TypeSummaryImpl::Flags::SetDontShowChildren(), lldb_private::TypeSummaryImpl::Flags::SetDontShowValue(), lldb_private::TypeSummaryImpl::Flags::SetHideItemNames(), lldb_private::TypeSummaryImpl::Flags::SetShowMembersOneLiner(), lldb_private::SyntheticChildren::Flags::SetSkipPointers(), lldb_private::TypeSummaryImpl::Flags::SetSkipPointers(), lldb_private::SyntheticChildren::Flags::SetSkipReferences(), and lldb_private::TypeSummaryImpl::Flags::SetSkipReferences().
Referenced by lldb_private::CPlusPlusLanguage::GetFormatters().
LoadSystemFormatters()
void LoadSystemFormatters (lldb::TypeCategoryImplSP cpp_category_sp) static
Definition at line 1996 of file CPlusPlusLanguage.cpp.
References lldb_private::formatters::AddCXXSummary(), lldb_private::formatters::Char16StringSummaryProvider(), lldb_private::formatters::Char16SummaryProvider(), lldb_private::formatters::Char32StringSummaryProvider(), lldb_private::formatters::Char32SummaryProvider(), lldb_private::formatters::Char8StringSummaryProvider(), lldb_private::formatters::Char8SummaryProvider(), lldb_private::TypeSummaryImpl::Flags::SetCascades(), lldb_private::TypeSummaryImpl::Flags::SetDontShowChildren(), lldb_private::TypeSummaryImpl::Flags::SetDontShowValue(), lldb_private::TypeSummaryImpl::Flags::SetHideItemNames(), lldb_private::TypeSummaryImpl::Flags::SetShowMembersOneLiner(), lldb_private::TypeSummaryImpl::Flags::SetSkipPointers(), lldb_private::TypeSummaryImpl::Flags::SetSkipReferences(), lldb_private::formatters::WCharStringSummaryProvider(), and lldb_private::formatters::WCharSummaryProvider().
Referenced by lldb_private::CPlusPlusLanguage::GetFormatters().
PrettyPrintFunctionNameWithArgs()
bool PrettyPrintFunctionNameWithArgs (Stream & out_stream, char const * full_name, ExecutionContextScope * exe_scope, VariableList const & args) static
Writes out the function name in 'full_name' to 'out_stream' but replaces each argument type with the variable name and the corresponding pretty-printed value.
Definition at line 228 of file CPlusPlusLanguage.cpp.
References lldb_private::Language::MethodName::GetQualifiers(), lldb_private::Language::MethodName::GetReturnType(), lldb_private::Language::MethodName::GetScopeQualifiedName(), lldb_private::Language::MethodName::IsValid(), lldb_private::FormatEntity::PrettyPrintFunctionArguments(), lldb_private::Stream::PutChar(), and lldb_private::Stream::PutCString().
PrintDemangledArgumentList()
bool PrintDemangledArgumentList (Stream & s, const SymbolContext & sc) static
Definition at line 444 of file CPlusPlusLanguage.cpp.
References GetAndValidateInfo(), lldb_private::CPlusPlusLanguage::GetDemangledFunctionArguments(), lldb_private::GetLog(), lldb_private::Language, LLDB_LOG_ERROR, and lldb_private::SymbolContext::symbol.
Referenced by lldb_private::CPlusPlusLanguage::HandleFrameFormatVariable().
PrintFunctionNameWithArgs()
bool PrintFunctionNameWithArgs (Stream & s, const ExecutionContext * exe_ctx, const SymbolContext & sc) static
Definition at line 2263 of file CPlusPlusLanguage.cpp.
References lldb_private::VariableList::AppendVariablesWithScope(), lldb_private::ConstString::AsCString(), lldb_private::Mangled::ePreferDemangled, lldb::eValueTypeVariableArgument, lldb_private::SymbolContext::function, lldb_private::ExecutionContext::GetBestExecutionContextScope(), GetFunctionVariableList(), lldb_private::Mangled::GetName(), lldb_private::SymbolContext::GetPossiblyInlinedFunctionName(), lldb_private::VariableList::GetSize(), PrettyPrintFunctionNameWithArgs(), and lldb_private::Stream::PutCString().
RegisterStdStringSummaryProvider()
void RegisterStdStringSummaryProvider (const lldb::TypeCategoryImplSP & category_sp, llvm::StringRef string_ty, llvm::StringRef char_ty, lldb::TypeSummaryImplSP summary_sp) static
Definition at line 1307 of file CPlusPlusLanguage.cpp.
References lldb::eFormatterMatchExact, and lldb::eFormatterMatchRegex.
Referenced by LoadCommonStlFormatters(), and LoadMsvcStlFormatters().
RegisterStdStringViewSummaryProvider()
void RegisterStdStringViewSummaryProvider (const lldb::TypeCategoryImplSP & category_sp, llvm::StringRef string_ty, llvm::StringRef char_ty, lldb::TypeSummaryImplSP summary_sp) static
Definition at line 1330 of file CPlusPlusLanguage.cpp.
References lldb::eFormatterMatchExact, and lldb::eFormatterMatchRegex.
Referenced by LoadCommonStlFormatters().
ReverseFindMatchingChars()
bool ReverseFindMatchingChars (const llvm::StringRef & s, const llvm::StringRef & left_right_chars, size_t & left_pos, size_t & right_pos, size_t pos = llvm::StringRef::npos) static
Definition at line 152 of file CPlusPlusLanguage.cpp.
Referenced by lldb_private::CPlusPlusLanguage::CxxMethodName::GetBasenameNoTemplateParameters(), and lldb_private::CPlusPlusLanguage::CxxMethodName::TrySimplifiedParse().