LLDB: CPPLanguageRuntime.cpp File Reference
CPPLanguageRuntime.cpp File Reference
#include <cstring>
#include <iostream>
#include <memory>
#include "CPPLanguageRuntime.h"
#include "VerboseTrapFrameRecognizer.h"
#include "llvm/ADT/StringRef.h"
#include "lldb/Symbol/Block.h"
#include "lldb/Symbol/Variable.h"
#include "lldb/Symbol/VariableList.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/UniqueCStringMap.h"
#include "lldb/Symbol/CompileUnit.h"
#include "lldb/Target/ABI.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/SectionLoadList.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/StackFrameRecognizer.h"
#include "lldb/Target/ThreadPlanRunToAddress.h"
#include "lldb/Target/ThreadPlanStepInRange.h"
#include "lldb/Utility/Timer.h"
Classes
class LibCXXFrameRecognizer
A frame recognizer that is installed to hide libc++ implementation details from the backtrace.
struct LibCXXFrameRecognizer::LibCXXHiddenFrame
Functions
bool contains_lambda_identifier (llvm::StringRef &str_ref)
CPPLanguageRuntime::LibCppStdFunctionCallableInfo line_entry_helper (Target &target, const SymbolContext &sc, Symbol *symbol, llvm::StringRef first_template_param_sref, bool has_invoke)
Variables
static ConstString g_this = ConstString("this")
static ConstString g_promise = ConstString("__promise")
static ConstString g_coro_frame = ConstString("__coro_frame")
Function Documentation
contains_lambda_identifier()
bool contains_lambda_identifier (llvm::StringRef & str_ref)
Definition at line 139 of file CPPLanguageRuntime.cpp.
Referenced by lldb_private::CPPLanguageRuntime::FindLibCppStdFunctionCallableInfo(), and line_entry_helper().
line_entry_helper()
CPPLanguageRuntime::LibCppStdFunctionCallableInfo line_entry_helper (Target & target, const SymbolContext & sc, Symbol * symbol, llvm::StringRef first_template_param_sref, bool has_invoke)
Definition at line 144 of file CPPLanguageRuntime.cpp.
References lldb_private::Address::CalculateSymbolContextLineEntry(), lldb_private::CPPLanguageRuntime::LibCppStdFunctionCallableInfo::callable_address, lldb_private::CPPLanguageRuntime::LibCppStdFunctionCallableInfo::callable_case, lldb_private::CPPLanguageRuntime::LibCppStdFunctionCallableInfo::callable_line_entry, lldb_private::CPPLanguageRuntime::LibCppStdFunctionCallableInfo::callable_symbol, contains_lambda_identifier(), lldb_private::Address::GetCallableLoadAddress(), lldb_private::SymbolContext::GetFunctionOrSymbolAddress(), and lldb_private::Target::ResolveLoadAddress().
Referenced by lldb_private::CPPLanguageRuntime::FindLibCppStdFunctionCallableInfo().
Variable Documentation
g_coro_frame
ConstString g_coro_frame = ConstString("__coro_frame") static
Definition at line 42 of file CPPLanguageRuntime.cpp.
Referenced by lldb_private::CPPLanguageRuntime::IsAllowedRuntimeValue().
g_promise
ConstString g_promise = ConstString("__promise") static
Definition at line 41 of file CPPLanguageRuntime.cpp.
Referenced by lldb_private::CPPLanguageRuntime::IsAllowedRuntimeValue().
g_this
ConstString g_this = ConstString("this") static
Definition at line 39 of file CPPLanguageRuntime.cpp.
Referenced by lldb_private::CPPLanguageRuntime::GetStepThroughTrampolinePlan(), and lldb_private::CPPLanguageRuntime::IsAllowedRuntimeValue().