LLDB: CppModuleConfiguration.cpp File Reference
CppModuleConfiguration.cpp File Reference
#include "CppModuleConfiguration.h"
#include "ClangHost.h"
#include "lldb/Host/FileSystem.h"
#include "llvm/TargetParser/Triple.h"
#include <optional>
Functions
static llvm::SmallVector< std::string, 2 > getTargetIncludePaths (const llvm::Triple &triple)
static std::optional< llvm::StringRef > guessIncludePath (llvm::StringRef path_to_file, llvm::StringRef pattern)
Returns the include path matching the given pattern for the given file path (or std::nullopt if the path doesn't match the pattern).
static std::string MakePath (llvm::StringRef lhs, llvm::StringRef rhs)
Utility function for just appending two paths.
Function Documentation
getTargetIncludePaths()
llvm::SmallVector< std::string, 2 > getTargetIncludePaths (const llvm::Triple & triple) static
Definition at line 36 of file CppModuleConfiguration.cpp.
Referenced by lldb_private::CppModuleConfiguration::analyzeFile().
guessIncludePath()
std::optional< llvm::StringRef > guessIncludePath (llvm::StringRef path_to_file, llvm::StringRef pattern) static
Returns the include path matching the given pattern for the given file path (or std::nullopt if the path doesn't match the pattern).
Definition at line 52 of file CppModuleConfiguration.cpp.
Referenced by lldb_private::CppModuleConfiguration::analyzeFile().
MakePath()
std::string MakePath (llvm::StringRef lhs, llvm::StringRef rhs) static
Utility function for just appending two paths.
Definition at line 101 of file CppModuleConfiguration.cpp.
Referenced by lldb_private::CppModuleConfiguration::hasValidConfig().