LLDB: CxxStringTypes.cpp File Reference
CxxStringTypes.cpp File Reference
#include "CxxStringTypes.h"
#include "llvm/Support/ConvertUTF.h"
#include "Plugins/TypeSystem/Clang/TypeSystemClang.h"
#include "lldb/DataFormatters/FormattersHelpers.h"
#include "lldb/DataFormatters/StringPrinter.h"
#include "lldb/DataFormatters/TypeSummary.h"
#include "lldb/Host/Time.h"
#include "lldb/Target/SectionLoadList.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/Endian.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/Stream.h"
#include "lldb/ValueObject/ValueObject.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
#include <algorithm>
#include <optional>
Functions
static constexpr std::pair< const char *, Format > getElementTraits (StringElementType ElemType)
template<StringElementType ElemType>
static bool CharStringSummaryProvider (ValueObject &valobj, Stream &stream)
template<StringElementType ElemType>
static bool CharSummaryProvider (ValueObject &valobj, Stream &stream)
template bool lldb_private::formatters::StringBufferSummaryProvider< StringElementType::ASCII > (Stream &, const TypeSummaryOptions &, lldb::ValueObjectSP, uint64_t, std::string)
template bool lldb_private::formatters::StringBufferSummaryProvider< StringElementType::UTF8 > (Stream &, const TypeSummaryOptions &, lldb::ValueObjectSP, uint64_t, std::string)
template bool lldb_private::formatters::StringBufferSummaryProvider< StringElementType::UTF16 > (Stream &, const TypeSummaryOptions &, lldb::ValueObjectSP, uint64_t, std::string)
template bool lldb_private::formatters::StringBufferSummaryProvider< StringElementType::UTF32 > (Stream &, const TypeSummaryOptions &, lldb::ValueObjectSP, uint64_t, std::string)
Function Documentation
CharStringSummaryProvider()
template<StringElementType ElemType> bool CharStringSummaryProvider (ValueObject & valobj, Stream & stream) static
Definition at line 52 of file CxxStringTypes.cpp.
References lldb_private::formatters::GetArrayAddressOrPointerValue(), getElementTraits(), lldb_private::ValueObject::GetTargetSP(), lldb_private::Address::IsValid(), lldb_private::Stream::Printf(), lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream(), lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::SetLocation(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetPrefixToken(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetStream(), and lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::SetTargetSP().
Referenced by lldb_private::formatters::Char16StringSummaryProvider(), lldb_private::formatters::Char32StringSummaryProvider(), and lldb_private::formatters::Char8StringSummaryProvider().
CharSummaryProvider()
template<StringElementType ElemType> bool CharSummaryProvider (ValueObject & valobj, Stream & stream) static
Definition at line 70 of file CxxStringTypes.cpp.
References error(), lldb_private::ValueObject::GetData(), getElementTraits(), lldb_private::ValueObject::GetValueAsCString(), lldb_private::Stream::Printf(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetBinaryZeroIsTerminator(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::SetData(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetPrefixToken(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetQuote(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetSourceSize(), and lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetStream().
Referenced by lldb_private::formatters::Char16SummaryProvider(), lldb_private::formatters::Char32SummaryProvider(), and lldb_private::formatters::Char8SummaryProvider().
getElementTraits()
constexpr std::pair< const char *, Format > getElementTraits (StringElementType ElemType) static constexpr
Definition at line 38 of file CxxStringTypes.cpp.
References lldb::eFormatInvalid, lldb::eFormatUnicode16, lldb::eFormatUnicode32, and lldb::eFormatUnicode8.
Referenced by CharStringSummaryProvider(), and CharSummaryProvider().
lldb_private::formatters::StringBufferSummaryProvider< StringElementType::ASCII >()
template bool lldb_private::formatters::StringBufferSummaryProvider< StringElementType::ASCII > (Stream & , const TypeSummaryOptions & , lldb::ValueObjectSP , uint64_t , std::string)
References lldb_private::formatters::StringBufferSummaryProvider().
lldb_private::formatters::StringBufferSummaryProvider< StringElementType::UTF16 >()
template bool lldb_private::formatters::StringBufferSummaryProvider< StringElementType::UTF16 > (Stream & , const TypeSummaryOptions & , lldb::ValueObjectSP , uint64_t , std::string)
References lldb_private::formatters::StringBufferSummaryProvider().
lldb_private::formatters::StringBufferSummaryProvider< StringElementType::UTF32 >()
template bool lldb_private::formatters::StringBufferSummaryProvider< StringElementType::UTF32 > (Stream & , const TypeSummaryOptions & , lldb::ValueObjectSP , uint64_t , std::string)
References lldb_private::formatters::StringBufferSummaryProvider().
lldb_private::formatters::StringBufferSummaryProvider< StringElementType::UTF8 >()
template bool lldb_private::formatters::StringBufferSummaryProvider< StringElementType::UTF8 > (Stream & , const TypeSummaryOptions & , lldb::ValueObjectSP , uint64_t , std::string)
References lldb_private::formatters::StringBufferSummaryProvider().