LLDB: DataVisualization.cpp File Reference
DataVisualization.cpp File Reference
#include "lldb/DataFormatters/DataVisualization.h"
Functions
static FormatManager & GetFormatManager ()
Function Documentation
GetFormatManager()
FormatManager & GetFormatManager () static
Definition at line 15 of file DataVisualization.cpp.
Referenced by lldb_private::DataVisualization::Categories::Add(), lldb_private::DataVisualization::NamedSummaryFormats::Add(), lldb_private::DataVisualization::AnyMatches(), lldb_private::DataVisualization::Categories::Clear(), lldb_private::DataVisualization::Categories::Clear(), lldb_private::DataVisualization::NamedSummaryFormats::Clear(), lldb_private::DataVisualization::Categories::Delete(), lldb_private::DataVisualization::NamedSummaryFormats::Delete(), lldb_private::DataVisualization::Categories::Disable(), lldb_private::DataVisualization::Categories::Disable(), lldb_private::DataVisualization::Categories::Disable(), lldb_private::DataVisualization::Categories::DisableStar(), lldb_private::DataVisualization::Categories::Enable(), lldb_private::DataVisualization::Categories::Enable(), lldb_private::DataVisualization::Categories::Enable(), lldb_private::DataVisualization::Categories::EnableStar(), lldb_private::DataVisualization::ForceUpdate(), lldb_private::DataVisualization::Categories::ForEach(), lldb_private::DataVisualization::NamedSummaryFormats::ForEach(), lldb_private::DataVisualization::Categories::GetCategory(), lldb_private::DataVisualization::Categories::GetCategory(), lldb_private::DataVisualization::Categories::GetCategoryAtIndex(), lldb_private::DataVisualization::Categories::GetCount(), lldb_private::DataVisualization::NamedSummaryFormats::GetCount(), lldb_private::DataVisualization::GetCurrentRevision(), lldb_private::DataVisualization::GetFilterForType(), lldb_private::DataVisualization::GetFormat(), lldb_private::DataVisualization::GetFormatForType(), lldb_private::DataVisualization::GetSummaryFormat(), lldb_private::DataVisualization::NamedSummaryFormats::GetSummaryFormat(), lldb_private::DataVisualization::GetSummaryForType(), lldb_private::DataVisualization::GetSyntheticChildren(), lldb_private::DataVisualization::GetSyntheticForType(), and lldb_private::DataVisualization::ShouldPrintAsOneLiner().