LLDB: DataExtractor.cpp File Reference
DataExtractor.cpp File Reference
#include "lldb/Utility/DataExtractor.h"
#include "lldb/lldb-defines.h"
#include "lldb/lldb-enumerations.h"
#include "lldb/lldb-forward.h"
#include "lldb/lldb-types.h"
#include "lldb/Utility/DataBuffer.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/LLDBAssert.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/Stream.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/Utility/UUID.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MD5.h"
#include "llvm/Support/MathExtras.h"
#include <algorithm>
#include <array>
#include <cassert>
#include <cstdint>
#include <string>
#include <cctype>
#include <cinttypes>
#include <cstring>
Functions
static uint16_t ReadInt16 (const unsigned char *ptr, offset_t offset)
static uint32_t ReadInt32 (const unsigned char *ptr, offset_t offset=0)
static uint64_t ReadInt64 (const unsigned char *ptr, offset_t offset=0)
static uint16_t ReadInt16 (const void *ptr)
static uint16_t ReadSwapInt16 (const unsigned char *ptr, offset_t offset)
static uint32_t ReadSwapInt32 (const unsigned char *ptr, offset_t offset)
static uint64_t ReadSwapInt64 (const unsigned char *ptr, offset_t offset)
static uint16_t ReadSwapInt16 (const void *ptr)
static uint32_t ReadSwapInt32 (const void *ptr)
static uint64_t ReadSwapInt64 (const void *ptr)
static uint64_t ReadMaxInt64 (const uint8_t *data, size_t byte_size, ByteOrder byte_order)
Function Documentation
ReadInt16() [1/2]
uint16_t ReadInt16 (const unsigned char * ptr, offset_t offset) inline static
Definition at line 44 of file DataExtractor.cpp.
Referenced by lldb_private::DataExtractor::GetU16(), and lldb_private::DataExtractor::GetU16_unchecked().
ReadInt16() [2/2]
uint16_t ReadInt16 (const void * ptr) inline static
Definition at line 64 of file DataExtractor.cpp.
ReadInt32()
uint32_t ReadInt32 (const unsigned char * ptr, offset_t offset = 0) inline static
Definition at line 50 of file DataExtractor.cpp.
Referenced by lldb_private::DataExtractor::GetU32_unchecked().
ReadInt64()
uint64_t ReadInt64 (const unsigned char * ptr, offset_t offset = 0) inline static
Definition at line 57 of file DataExtractor.cpp.
Referenced by lldb_private::DataExtractor::GetU64_unchecked().
ReadMaxInt64()
uint64_t ReadMaxInt64 (const uint8_t * data, size_t byte_size, ByteOrder byte_order) inline static
Definition at line 109 of file DataExtractor.cpp.
References lldb::eByteOrderBig, and lldb::eByteOrderLittle.
Referenced by lldb_private::DataExtractor::GetMaxU64(), and lldb_private::DataExtractor::GetMaxU64_unchecked().
ReadSwapInt16() [1/2]
uint16_t ReadSwapInt16 (const unsigned char * ptr, offset_t offset) inline static
Definition at line 70 of file DataExtractor.cpp.
Referenced by lldb_private::DataExtractor::GetU16(), lldb_private::DataExtractor::GetU16(), and lldb_private::DataExtractor::GetU16_unchecked().
ReadSwapInt16() [2/2]
uint16_t ReadSwapInt16 (const void * ptr) inline static
Definition at line 91 of file DataExtractor.cpp.
ReadSwapInt32() [1/2]
uint32_t ReadSwapInt32 (const unsigned char * ptr, offset_t offset) inline static
Definition at line 77 of file DataExtractor.cpp.
Referenced by lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU32(), and lldb_private::DataExtractor::GetU32_unchecked().
ReadSwapInt32() [2/2]
uint32_t ReadSwapInt32 (const void * ptr) inline static
Definition at line 97 of file DataExtractor.cpp.
ReadSwapInt64() [1/2]
uint64_t ReadSwapInt64 (const unsigned char * ptr, offset_t offset) inline static
Definition at line 84 of file DataExtractor.cpp.
Referenced by lldb_private::DataExtractor::GetU64(), lldb_private::DataExtractor::GetU64(), and lldb_private::DataExtractor::GetU64_unchecked().
ReadSwapInt64() [2/2]
uint64_t ReadSwapInt64 (const void * ptr) inline static
Definition at line 103 of file DataExtractor.cpp.