LLDB: DebuggerThread.cpp File Reference
DebuggerThread.cpp File Reference
#include "DebuggerThread.h"
#include "ExceptionRecord.h"
#include "IDebugDelegate.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Host/ProcessLaunchInfo.h"
#include "lldb/Host/ThreadLauncher.h"
#include "lldb/Host/windows/AutoHandle.h"
#include "lldb/Host/windows/HostProcessWindows.h"
#include "lldb/Host/windows/HostThreadWindows.h"
#include "lldb/Host/windows/ProcessLauncherWindows.h"
#include "lldb/Target/Process.h"
#include "lldb/Utility/FileSpec.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/Predicate.h"
#include "lldb/Utility/Status.h"
#include "Plugins/Process/Windows/Common/ProcessWindowsLog.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/ConvertUTF.h"
#include "llvm/Support/Threading.h"
#include "llvm/Support/raw_ostream.h"
#include <optional>
#include <psapi.h>
Macros
#define STATUS_WX86_BREAKPOINT 0x4000001FL
Functions
static std::optional< std::string > GetFileNameFromHandleFallback (HANDLE hFile)
Macro Definition Documentation
STATUS_WX86_BREAKPOINT
#define STATUS_WX86_BREAKPOINT 0x4000001FL
Definition at line 37 of file DebuggerThread.cpp.
Referenced by lldb_private::DebuggerThread::DebugLoop(), lldb_private::DebuggerThread::HandleExceptionEvent(), and lldb_private::NativeProcessWindows::OnDebugException().
Function Documentation
GetFileNameFromHandleFallback()
std::optional< std::string > GetFileNameFromHandleFallback (HANDLE hFile) static
Definition at line 448 of file DebuggerThread.cpp.
References lldb_private::AutoHandle::get(), and lldb_private::AutoHandle::IsValid().
Referenced by lldb_private::DebuggerThread::HandleLoadDllEvent().