LLDB: DebuggerEvents.cpp File Reference
DebuggerEvents.cpp File Reference
#include "lldb/Core/DebuggerEvents.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/Progress.h"
#include "llvm/Support/WithColor.h"
Functions
template<typename T>
static const T * GetEventDataFromEventImpl (const Event *event_ptr)
Function Documentation
GetEventDataFromEventImpl()
template<typename T> const T * GetEventDataFromEventImpl (const Event * event_ptr) static
Definition at line 19 of file DebuggerEvents.cpp.
References lldb_private::Event::GetData().
Referenced by lldb_private::DiagnosticEventData::GetEventDataFromEvent(), lldb_private::ProgressEventData::GetEventDataFromEvent(), and lldb_private::SymbolChangeEventData::GetEventDataFromEvent().