LLDB: Debugger.cpp File Reference
Debugger.cpp File Reference
#include "lldb/Core/Debugger.h"
#include "lldb/Breakpoint/Breakpoint.h"
#include "lldb/Core/DebuggerEvents.h"
#include "lldb/Core/FormatEntity.h"
#include "lldb/Core/Mangled.h"
#include "lldb/Core/ModuleList.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Progress.h"
#include "lldb/Core/ProtocolServer.h"
#include "lldb/Core/StreamAsynchronousIO.h"
#include "lldb/Core/Telemetry.h"
#include "lldb/DataFormatters/DataVisualization.h"
#include "lldb/Expression/REPL.h"
#include "lldb/Host/Config.h"
#include "lldb/Host/File.h"
#include "lldb/Host/FileSystem.h"
#include "lldb/Host/HostInfo.h"
#include "lldb/Host/StreamFile.h"
#include "lldb/Host/Terminal.h"
#include "lldb/Host/ThreadLauncher.h"
#include "lldb/Host/XML.h"
#include "lldb/Interpreter/CommandInterpreter.h"
#include "lldb/Interpreter/CommandReturnObject.h"
#include "lldb/Interpreter/OptionValue.h"
#include "lldb/Interpreter/OptionValueLanguage.h"
#include "lldb/Interpreter/OptionValueProperties.h"
#include "lldb/Interpreter/OptionValueSInt64.h"
#include "lldb/Interpreter/OptionValueString.h"
#include "lldb/Interpreter/Property.h"
#include "lldb/Interpreter/ScriptInterpreter.h"
#include "lldb/Symbol/Function.h"
#include "lldb/Symbol/Symbol.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Target/Language.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/StructuredDataPlugin.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/TargetList.h"
#include "lldb/Target/Thread.h"
#include "lldb/Target/ThreadList.h"
#include "lldb/Utility/AnsiTerminal.h"
#include "lldb/Utility/Event.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Listener.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/State.h"
#include "lldb/Utility/Stream.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/Version/Version.h"
#include "lldb/lldb-enumerations.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/iterator.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/DynamicLibrary.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/ThreadPool.h"
#include "llvm/Support/Threading.h"
#include "llvm/Support/raw_ostream.h"
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <list>
#include <memory>
#include <mutex>
#include <optional>
#include <set>
#include <string>
#include <system_error>
#include <unistd.h>
#include "CoreProperties.inc"
#include "CorePropertiesEnum.inc"
#include "llvm/Config/Targets.def"
Namespaces
namespace lldb_private
A class that represents a running process on the host machine.
Macros
#define LLDB_PROPERTIES_debugger
#define LLDB_PROPERTIES_debugger
#define LLDB_PROPERTIES_testing
#define LLDB_PROPERTIES_testing
#define LLVM_TARGET(target)
Enumerations
enum
enum
Functions
static FileSystem::EnumerateDirectoryResult LoadPluginCallback (void *baton, llvm::sys::fs::file_type ft, llvm::StringRef path)
static int OpenPipe (int fds[2], std::size_t size)
static void PrivateReportProgress (Debugger &debugger, uint64_t progress_id, std::string title, std::string details, uint64_t completed, uint64_t total, bool is_debugger_specific, uint32_t progress_broadcast_bit)
static void PrivateReportDiagnostic (Debugger &debugger, Severity severity, std::string message, bool debugger_specific)
static std::shared_ptr< LogHandler > CreateLogHandler (LogHandlerKind log_handler_kind, int fd, bool should_close, size_t buffer_size)
static bool RequiresFollowChildWorkaround (const Process &process)
static void AddBoolConfigEntry (StructuredData::Dictionary &dict, llvm::StringRef name, bool value, llvm::StringRef description)
static void AddLLVMTargets (StructuredData::Dictionary &dict)
Variables
static lldb::user_id_t g_unique_id = 1
static size_t g_debugger_event_thread_stack_bytes = 8 * 1024 * 1024
static std::recursive_mutex * g_debugger_list_mutex_ptr
static Debugger::DebuggerList * g_debugger_list_ptr
static llvm::DefaultThreadPool * g_thread_pool = nullptr
static constexpr OptionEnumValueElement g_show_disassembly_enum_values []
static constexpr OptionEnumValueElement g_language_enumerators []
static constexpr OptionEnumValueElement g_dwim_print_verbosities []
static constexpr OptionEnumValueElement s_stop_show_column_values []
Macro Definition Documentation
LLDB_PROPERTIES_debugger [1/2]
#define LLDB_PROPERTIES_debugger
Definition at line 197 of file Debugger.cpp.
LLDB_PROPERTIES_debugger [2/2]
#define LLDB_PROPERTIES_debugger
Definition at line 197 of file Debugger.cpp.
LLDB_PROPERTIES_testing [1/2]
#define LLDB_PROPERTIES_testing
Definition at line 206 of file Debugger.cpp.
LLDB_PROPERTIES_testing [2/2]
#define LLDB_PROPERTIES_testing
Definition at line 206 of file Debugger.cpp.
LLVM_TARGET
#define LLVM_TARGET (target)
Value:
  array_up->AddItem(std::make_unique<StructuredData::String>(#target));
Enumeration Type Documentation
anonymous enum
anonymous enum
Definition at line 200 of file Debugger.cpp.
anonymous enum
anonymous enum
Definition at line 209 of file Debugger.cpp.
Function Documentation
AddBoolConfigEntry()
void AddBoolConfigEntry (StructuredData::Dictionary & dict, llvm::StringRef name, bool value, llvm::StringRef description) static
Definition at line 2484 of file Debugger.cpp.
References lldb_private::StructuredData::Dictionary::AddItem().
Referenced by lldb_private::Debugger::GetBuildConfiguration().
AddLLVMTargets()
void AddLLVMTargets (StructuredData::Dictionary & dict) static
Definition at line 2493 of file Debugger.cpp.
References lldb_private::StructuredData::Dictionary::AddItem().
Referenced by lldb_private::Debugger::GetBuildConfiguration().
CreateLogHandler()
std::shared_ptr< LogHandler > CreateLogHandler (LogHandlerKind log_handler_kind, int fd, bool should_close, size_t buffer_size) static
Definition at line 1843 of file Debugger.cpp.
References lldb_private::eLogHandlerCallback, lldb_private::eLogHandlerCircular, lldb_private::eLogHandlerStream, and lldb_private::eLogHandlerSystem.
Referenced by lldb_private::Debugger::EnableLog().
LoadPluginCallback()
FileSystem::EnumerateDirectoryResult LoadPluginCallback (void * baton, llvm::sys::fs::file_type ft, llvm::StringRef path) static
Definition at line 808 of file Debugger.cpp.
References lldb_private::FileSystem::eEnumerateDirectoryResultEnter, lldb_private::FileSystem::eEnumerateDirectoryResultNext, lldb_private::FileSystem::eEnumerateDirectoryResultQuit, error(), lldb_private::FileSpec::GetFileNameExtension(), lldb_private::FileSystem::Instance(), lldb_private::Debugger::LoadPlugin(), and lldb_private::FileSystem::Resolve().
Referenced by lldb_private::PluginManager::Initialize(), and lldb_private::Debugger::InstanceInitialize().
OpenPipe()
int OpenPipe (int fds[2], std::size_t size) inline static
Definition at line 1164 of file Debugger.cpp.
Referenced by lldb_private::Debugger::SetInputString().
PrivateReportDiagnostic()
void PrivateReportDiagnostic (Debugger & debugger, Severity severity, std::string message, bool debugger_specific) static
Definition at line 1740 of file Debugger.cpp.
References lldb_private::Broadcaster::BroadcastEvent(), lldb_private::DiagnosticEventData::Dump(), lldb::eBroadcastBitError, lldb::eBroadcastBitWarning, lldb::eSeverityError, lldb::eSeverityInfo, lldb::eSeverityWarning, lldb_private::Broadcaster::EventTypeHasListeners(), lldb_private::Debugger::GetAsyncErrorStream(), and lldb_private::Debugger::GetBroadcaster().
Referenced by lldb_private::Debugger::ReportDiagnosticImpl().
PrivateReportProgress()
void PrivateReportProgress (Debugger & debugger, uint64_t progress_id, std::string title, std::string details, uint64_t completed, uint64_t total, bool is_debugger_specific, uint32_t progress_broadcast_bit) static
Definition at line 1695 of file Debugger.cpp.
References lldb_private::Broadcaster::BroadcastEvent(), lldb_private::Event, lldb_private::Broadcaster::EventTypeHasListeners(), and lldb_private::Debugger::GetBroadcaster().
Referenced by lldb_private::Debugger::ReportProgress().
RequiresFollowChildWorkaround()
bool RequiresFollowChildWorkaround (const Process & process) static
Definition at line 2129 of file Debugger.cpp.
References lldb_private::eFollowChild, and lldb_private::ProcessProperties::GetFollowForkMode().
Referenced by lldb_private::Debugger::DefaultEventHandler().
Variable Documentation
g_debugger_event_thread_stack_bytes
size_t g_debugger_event_thread_stack_bytes = 8 * 1024 * 1024 static
Definition at line 106 of file Debugger.cpp.
Referenced by lldb_private::Debugger::StartEventHandlerThread().
g_debugger_list_mutex_ptr
std::recursive_mutex* g_debugger_list_mutex_ptr static
Initial value:
=
    nullptr
Definition at line 110 of file Debugger.cpp.
Referenced by lldb_private::Debugger::CreateInstance(), lldb_private::Debugger::DebuggersRequestingInterruption(), lldb_private::Debugger::Destroy(), lldb_private::Debugger::FindDebuggerWithID(), lldb_private::Debugger::FindDebuggerWithInstanceName(), lldb_private::Debugger::FindTargetWithProcess(), lldb_private::Debugger::FindTargetWithProcessID(), lldb_private::Debugger::GetDebuggerAtIndex(), lldb_private::Debugger::GetNumDebuggers(), lldb_private::Debugger::Initialize(), lldb_private::Debugger::ReportDiagnosticImpl(), lldb_private::Debugger::ReportProgress(), lldb_private::Debugger::ReportSymbolChange(), and lldb_private::Debugger::Terminate().
g_debugger_list_ptr
Debugger::DebuggerList* g_debugger_list_ptr static
Initial value:
=
    nullptr
Definition at line 112 of file Debugger.cpp.
Referenced by lldb_private::Debugger::CreateInstance(), lldb_private::Debugger::DebuggersRequestingInterruption(), lldb_private::Debugger::Destroy(), lldb_private::Debugger::FindDebuggerWithID(), lldb_private::Debugger::FindDebuggerWithInstanceName(), lldb_private::Debugger::FindTargetWithProcess(), lldb_private::Debugger::FindTargetWithProcessID(), lldb_private::Debugger::GetDebuggerAtIndex(), lldb_private::Debugger::GetNumDebuggers(), lldb_private::Debugger::Initialize(), lldb_private::Debugger::ReportDiagnosticImpl(), lldb_private::Debugger::ReportProgress(), lldb_private::Debugger::ReportSymbolChange(), and lldb_private::Debugger::Terminate().
g_dwim_print_verbosities
OptionEnumValueElement g_dwim_print_verbosities[] static constexpr
Initial value:
= {
    {eDWIMPrintVerbosityNone, "none",
     "Use no verbosity when running dwim-print."},
    {eDWIMPrintVerbosityExpression, "expression",
     "Use partial verbosity when running dwim-print - display a message when "
     "`expression` evaluation is used."},
    {eDWIMPrintVerbosityFull, "full",
     "Use full verbosity when running dwim-print."},
}
Definition at line 159 of file Debugger.cpp.
g_language_enumerators
OptionEnumValueElement g_language_enumerators[] static constexpr
Initial value:
= {
    {
        eScriptLanguageNone,
        "none",
        "Disable scripting languages.",
    },
    {
        eScriptLanguagePython,
        "python",
        "Select python as the default scripting language.",
    },
    {
        eScriptLanguageDefault,
        "default",
        "Select the lldb default as the default scripting language.",
    },
}
Definition at line 141 of file Debugger.cpp.
g_show_disassembly_enum_values
OptionEnumValueElement g_show_disassembly_enum_values[] static constexpr
Initial value:
= {
    {
        lldb::eStopDisassemblyTypeNever,
        "never",
        "Never show disassembly when displaying a stop context.",
    },
    {
        lldb::eStopDisassemblyTypeNoDebugInfo,
        "no-debuginfo",
        "Show disassembly when there is no debug information.",
    },
    {
        lldb::eStopDisassemblyTypeNoSource,
        "no-source",
        "Show disassembly when there is no source information, or the source "
        "file "
        "is missing when displaying a stop context.",
    },
    {
        lldb::eStopDisassemblyTypeAlways,
        "always",
        "Always show disassembly when displaying a stop context.",
    },
}
Definition at line 116 of file Debugger.cpp.
g_thread_pool
llvm::DefaultThreadPool* g_thread_pool = nullptr static
Definition at line 114 of file Debugger.cpp.
Referenced by lldb_private::Debugger::GetThreadPool(), lldb_private::Debugger::Initialize(), and lldb_private::Debugger::Terminate().
g_unique_id
lldb::user_id_t g_unique_id = 1 static
Definition at line 105 of file Debugger.cpp.
Referenced by lldb_private::Debugger::Debugger(), lldb_private::Module::Module(), lldb_private::Module::Module(), and lldb_private::Module::Module().
s_stop_show_column_values
OptionEnumValueElement s_stop_show_column_values[] static constexpr
Initial value:
= {
    {
        eStopShowColumnAnsiOrCaret,
        "ansi-or-caret",
        "Highlight the stop column with ANSI terminal codes when color/ANSI "
        "mode is enabled; otherwise, fall back to using a text-only caret (^) "
        "as if \"caret-only\" mode was selected.",
    },
    {
        eStopShowColumnAnsi,
        "ansi",
        "Highlight the stop column with ANSI terminal codes when running LLDB "
        "with color/ANSI enabled.",
    },
    {
        eStopShowColumnCaret,
        "caret",
        "Highlight the stop column with a caret character (^) underneath the "
        "stop column. This method introduces a new line in source listings "
        "that display thread stop locations.",
    },
    {
        eStopShowColumnNone,
        "none",
        "Do not highlight the stop column.",
    },
}
Definition at line 169 of file Debugger.cpp.