LLDB: DiagnosticManager.cpp File Reference
DiagnosticManager.cpp File Reference
#include "lldb/Expression/DiagnosticManager.h"
#include "llvm/Support/ErrorHandling.h"
#include "lldb/Utility/ErrorMessages.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/StreamString.h"
Classes
class ExpressionCategory
A std::error_code category for eErrorTypeExpression.
Functions
ExpressionCategory & expression_category ()
static llvm::StringRef StringForSeverity (lldb::Severity severity)
Function Documentation
expression_category()
ExpressionCategory & expression_category ()
Definition at line 29 of file DiagnosticManager.cpp.
Referenced by lldb_private::ExpressionError::ExpressionError().
StringForSeverity()
llvm::StringRef StringForSeverity (lldb::Severity severity) static
Definition at line 40 of file DiagnosticManager.cpp.
References lldb::eSeverityError, lldb::eSeverityInfo, and lldb::eSeverityWarning.
Referenced by lldb_private::DiagnosticManager::GetString(), and lldb_private::ExpressionError::message().