LLDB: Disassembler.cpp File Reference
Disassembler.cpp File Reference
#include "lldb/Core/Disassembler.h"
#include "lldb/Core/AddressRange.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/EmulateInstruction.h"
#include "lldb/Core/Mangled.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleList.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/SourceManager.h"
#include "lldb/Host/FileSystem.h"
#include "lldb/Interpreter/OptionValue.h"
#include "lldb/Interpreter/OptionValueArray.h"
#include "lldb/Interpreter/OptionValueDictionary.h"
#include "lldb/Interpreter/OptionValueRegex.h"
#include "lldb/Interpreter/OptionValueString.h"
#include "lldb/Interpreter/OptionValueUInt64.h"
#include "lldb/Symbol/Function.h"
#include "lldb/Symbol/Symbol.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Symbol/Variable.h"
#include "lldb/Symbol/VariableList.h"
#include "lldb/Target/ABI.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/SectionLoadList.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/DataExtractor.h"
#include "lldb/Utility/RegularExpression.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/Stream.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/Utility/Timer.h"
#include "lldb/lldb-private-enumerations.h"
#include "lldb/lldb-private-interfaces.h"
#include "lldb/lldb-private-types.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Compiler.h"
#include "llvm/TargetParser/Triple.h"
#include <cstdint>
#include <cstring>
#include <utility>
#include <cassert>
Macros
#define DEFAULT_DISASM_BYTE_SIZE 32
Functions
static Address ResolveAddress (Target &target, const Address &addr)
static void AddVariableAnnotationToVector (std::vector< VariableAnnotation > &annotations, VariableAnnotation annotation_entity, const bool is_live)
Variables
static constexpr const llvm::StringLiteral kUndefLocation = "undef"
static constexpr const llvm::StringLiteral kUndefLocationFormatted = "<undef>"
Macro Definition Documentation
DEFAULT_DISASM_BYTE_SIZE
#define DEFAULT_DISASM_BYTE_SIZE 32
Definition at line 59 of file Disassembler.cpp.
Function Documentation
AddVariableAnnotationToVector()
void AddVariableAnnotationToVector (std::vector< VariableAnnotation > & annotations, VariableAnnotation annotation_entity, const bool is_live) static
Definition at line 292 of file Disassembler.cpp.
References lldb_private::VariableAnnotation::is_live, kUndefLocation, and lldb_private::VariableAnnotation::location_description.
Referenced by lldb_private::VariableAnnotator::AnnotateStructured().
ResolveAddress()
Address ResolveAddress (Target & target, const Address & addr) static
Definition at line 111 of file Disassembler.cpp.
References lldb_private::Target::GetImages(), lldb_private::Address::GetOffset(), lldb_private::Target::HasLoadedSections(), lldb_private::Address::IsSectionOffset(), lldb_private::Address::IsValid(), lldb_private::ModuleList::ResolveFileAddress(), and lldb_private::Target::ResolveLoadAddress().
Referenced by lldb_private::Disassembler::AppendInstructions().
Variable Documentation
kUndefLocation
const llvm::StringLiteral kUndefLocation = "undef" static constexpr
Definition at line 289 of file Disassembler.cpp.
Referenced by AddVariableAnnotationToVector(), and lldb_private::VariableAnnotator::Annotate().
kUndefLocationFormatted
const llvm::StringLiteral kUndefLocationFormatted = "<undef>" static constexpr
Definition at line 290 of file Disassembler.cpp.
Referenced by lldb_private::VariableAnnotator::Annotate().