LLDB: DumpRegisterValue.cpp File Reference
DumpRegisterValue.cpp File Reference
#include "lldb/Core/DumpRegisterValue.h"
#include "lldb/Core/DumpDataExtractor.h"
#include "lldb/DataFormatters/DumpValueObjectOptions.h"
#include "lldb/Target/RegisterFlags.h"
#include "lldb/Utility/DataExtractor.h"
#include "lldb/Utility/Endian.h"
#include "lldb/Utility/RegisterValue.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/ValueObject/ValueObject.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
#include "lldb/lldb-private-types.h"
#include "llvm/ADT/bit.h"
Functions
template<typename T>
static void dump_type_value (lldb_private::CompilerType &fields_type, T value, lldb_private::ExecutionContextScope *exe_scope, const lldb_private::RegisterInfo &reg_info, lldb_private::Stream &strm)
Function Documentation
dump_type_value()
template<typename T> void dump_type_value (lldb_private::CompilerType & fields_type, T value, lldb_private::ExecutionContextScope * exe_scope, const lldb_private::RegisterInfo & reg_info, lldb_private::Stream & strm) static
Definition at line 25 of file DumpRegisterValue.cpp.
References lldb_private::ExecutionContextScope::CalculateProcess(), lldb_private::ValueObjectConstResult::Create(), lldb::eByteOrderLittle, error(), lldb_private::RegisterInfo::flags_type, lldb_private::endian::InlHostByteOrder(), lldb_private::RegisterFlags::ReverseFieldOrder(), lldb_private::DumpValueObjectOptions::SetChildPrintingDecider(), lldb_private::DumpValueObjectOptions::SetHideRootType(), and toString().
Referenced by lldb_private::DumpRegisterValue().