LLDB: DWARFCallFrameInfo.cpp File Reference
DWARFCallFrameInfo.cpp File Reference
#include "lldb/Symbol/DWARFCallFrameInfo.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/Section.h"
#include "lldb/Core/dwarf.h"
#include "lldb/Host/Host.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Symbol/UnwindPlan.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/ArchSpec.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/Timer.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include <cstdint>
#include <cstring>
#include <list>
#include <optional>
Functions
static uint64_t GetGNUEHPointer (const DataExtractor &DE, lldb::offset_t *offset_ptr, uint32_t eh_ptr_enc, addr_t pc_rel_addr, addr_t text_addr, addr_t data_addr)
static bool IsCIEMarker (uint64_t cie_id, bool is_64bit, DWARFCallFrameInfo::Type type)
Function Documentation
GetGNUEHPointer()
uint64_t GetGNUEHPointer (const DataExtractor & DE, lldb::offset_t * offset_ptr, uint32_t eh_ptr_enc, addr_t pc_rel_addr, addr_t text_addr, addr_t data_addr) static
Definition at line 38 of file DWARFCallFrameInfo.cpp.
References DW_EH_PE_MASK_ENCODING, lldb_private::DataExtractor::GetAddress(), lldb_private::DataExtractor::GetAddressByteSize(), lldb_private::DataExtractor::GetSLEB128(), lldb_private::DataExtractor::GetU16(), lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU64(), lldb_private::DataExtractor::GetULEB128(), and LLDB_INVALID_ADDRESS.
Referenced by lldb_private::DWARFCallFrameInfo::GetFDEIndex(), lldb_private::DWARFCallFrameInfo::ParseCIE(), and lldb_private::DWARFCallFrameInfo::ParseFDE().
IsCIEMarker()
bool IsCIEMarker (uint64_t cie_id, bool is_64bit, DWARFCallFrameInfo::Type type) static
Definition at line 154 of file DWARFCallFrameInfo.cpp.
References lldb_private::DWARFCallFrameInfo::EH.
Referenced by lldb_private::DWARFCallFrameInfo::GetFDEIndex(), and lldb_private::DWARFCallFrameInfo::ParseCIE().