LLDB: DWARFUnit.cpp File Reference
DWARFUnit.cpp File Reference
#include "DWARFUnit.h"
#include "lldb/Core/Module.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Utility/LLDBAssert.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/Utility/Timer.h"
#include "llvm/DebugInfo/DWARF/DWARFAddressRange.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugAbbrev.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugLoc.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugRangeList.h"
#include "llvm/Object/Error.h"
#include "DWARFCompileUnit.h"
#include "DWARFDebugAranges.h"
#include "DWARFDebugInfo.h"
#include "DWARFTypeUnit.h"
#include "LogChannelDWARF.h"
#include "SymbolFileDWARFDwo.h"
#include <optional>
Functions
template<typename ListTableType>
static llvm::Expected< ListTableType > ParseListTableHeader (const llvm::DWARFDataExtractor &data, uint64_t offset, DwarfFormat format)
static bool CompareDIEOffset (const DWARFDebugInfoEntry &die, const dw_offset_t die_offset)
static llvm::StringRef removeHostnameFromPathname (llvm::StringRef path_from_dwarf)
Variables
int g_verbose
Function Documentation
CompareDIEOffset()
bool CompareDIEOffset (const DWARFDebugInfoEntry & die, const dw_offset_t die_offset) static
Definition at line 662 of file DWARFUnit.cpp.
References lldb_private::plugin::dwarf::DWARFDebugInfoEntry::GetOffset().
Referenced by lldb_private::plugin::dwarf::DWARFUnit::GetDIE().
ParseListTableHeader()
template<typename ListTableType> llvm::Expected< ListTableType > ParseListTableHeader (const llvm::DWARFDataExtractor & data, uint64_t offset, DwarfFormat format) static
Definition at line 486 of file DWARFUnit.cpp.
Referenced by lldb_private::plugin::dwarf::DWARFUnit::GetRnglistTable().
removeHostnameFromPathname()
llvm::StringRef removeHostnameFromPathname (llvm::StringRef path_from_dwarf) static
Definition at line 941 of file DWARFUnit.cpp.
Referenced by lldb_private::plugin::dwarf::DWARFUnit::ComputeCompDirAndGuessPathStyle().
Variable Documentation
g_verbose
int g_verbose extern