LLDB: DWARFDIE.cpp File Reference
DWARFDIE.cpp File Reference
#include "DWARFDIE.h"
#include "DWARFASTParser.h"
#include "DWARFDebugInfo.h"
#include "DWARFDebugInfoEntry.h"
#include "DWARFDeclContext.h"
#include "DWARFUnit.h"
#include "LogChannelDWARF.h"
#include "lldb/Symbol/Type.h"
#include "llvm/ADT/iterator.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/DebugInfo/DWARF/DWARFAddressRange.h"
#include "llvm/DebugInfo/DWARF/DWARFTypePrinter.h"
#include "llvm/Support/raw_ostream.h"
Functions
static CompilerContext GetContextEntry (DWARFDIE die, bool derive_template_names)
static void GetDeclContextImpl (DWARFDIE die, bool derive_template_names, llvm::SmallSet< lldb::user_id_t, 4 > &seen, std::vector< CompilerContext > &context)
static void GetTypeLookupContextImpl (DWARFDIE die, bool derive_template_names, llvm::SmallSet< lldb::user_id_t, 4 > &seen, std::vector< CompilerContext > &context)
static DWARFDeclContext GetDWARFDeclContextImpl (DWARFDIE die)
static DWARFDIE GetParentDeclContextDIEImpl (DWARFDIE die)
Function Documentation
GetContextEntry()
CompilerContext GetContextEntry (DWARFDIE die, bool derive_template_names) static
Definition at line 381 of file DWARFDIE.cpp.
References lldb_private::Builtin, lldb_private::ClassOrStruct, lldb_private::Enum, lldb_private::Function, lldb_private::plugin::dwarf::DWARFDIE::GetName(), lldb_private::Module, lldb_private::Namespace, lldb_private::plugin::dwarf::DWARFBaseDIE::Tag(), lldb_private::Typedef, lldb_private::Union, and lldb_private::Variable.
Referenced by GetDeclContextImpl(), and GetTypeLookupContextImpl().
GetDeclContextImpl()
void GetDeclContextImpl (DWARFDIE die, bool derive_template_names, llvm::SmallSet< lldb::user_id_t, 4 > & seen, std::vector< CompilerContext > & context) static
Definition at line 423 of file DWARFDIE.cpp.
References GetContextEntry(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetID(), lldb_private::plugin::dwarf::DWARFDIE::GetParent(), lldb_private::plugin::dwarf::DWARFDIE::GetReferencedDIE(), and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
Referenced by lldb_private::plugin::dwarf::DWARFDIE::GetDeclContext().
GetDWARFDeclContextImpl()
DWARFDeclContext GetDWARFDeclContextImpl (DWARFDIE die) static
Definition at line 511 of file DWARFDIE.cpp.
References lldb_private::plugin::dwarf::DWARFDeclContext::AppendDeclContext(), lldb_private::plugin::dwarf::DWARFDIE::GetName(), lldb_private::plugin::dwarf::DWARFDIE::GetParentDeclContextDIE(), and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
Referenced by lldb_private::plugin::dwarf::DWARFDIE::GetDWARFDeclContext().
GetParentDeclContextDIEImpl()
DWARFDIE GetParentDeclContextDIEImpl (DWARFDIE die) static
Definition at line 530 of file DWARFDIE.cpp.
References lldb_private::plugin::dwarf::DWARFDIE::GetParent(), lldb_private::plugin::dwarf::DWARFDIE::GetParentDeclContextDIE(), lldb_private::plugin::dwarf::DWARFDIE::GetReferencedDIE(), and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
Referenced by lldb_private::plugin::dwarf::DWARFDIE::GetParentDeclContextDIE().
GetTypeLookupContextImpl()
void GetTypeLookupContextImpl (DWARFDIE die, bool derive_template_names, llvm::SmallSet< lldb::user_id_t, 4 > & seen, std::vector< CompilerContext > & context) static
Definition at line 464 of file DWARFDIE.cpp.
References GetContextEntry(), lldb_private::plugin::dwarf::DWARFBaseDIE::GetID(), lldb_private::plugin::dwarf::DWARFDIE::GetParent(), and lldb_private::plugin::dwarf::DWARFBaseDIE::Tag().
Referenced by lldb_private::plugin::dwarf::DWARFDIE::GetTypeLookupContext().