LLDB: DYLDRendezvous.cpp File Reference
DYLDRendezvous.cpp File Reference
#include "lldb/Core/Module.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Symbol/Symbol.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Target/Platform.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/ArchSpec.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/Status.h"
#include "llvm/Support/Path.h"
#include "DYLDRendezvous.h"
Functions
static bool isLoadBiasIncorrect (Target &target, const std::string &file_path)
Function Documentation
isLoadBiasIncorrect()
bool isLoadBiasIncorrect (Target & target, const std::string & file_path) static
Definition at line 627 of file DYLDRendezvous.cpp.
References lldb_private::Target::GetArchitecture(), lldb_private::Target::GetPlatform(), and lldb_private::ArchSpec::GetTriple().
Referenced by DYLDRendezvous::UpdateBaseAddrIfNecessary().