LLDB: DynamicLoaderDarwinKernel.cpp File Reference
DynamicLoaderDarwinKernel.cpp File Reference
#include "Plugins/ObjectFile/Mach-O/ObjectFileMachO.h"
#include "Plugins/Platform/MacOSX/PlatformDarwinKernel.h"
#include "lldb/Breakpoint/StoppointCallbackContext.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Progress.h"
#include "lldb/Core/Section.h"
#include "lldb/Interpreter/OptionValueProperties.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Target/OperatingSystem.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Target/ThreadPlanRunToAddress.h"
#include "lldb/Utility/AddressableBits.h"
#include "lldb/Utility/DataBuffer.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/State.h"
#include "DynamicLoaderDarwinKernel.h"
#include <algorithm>
#include <memory>
#include "DynamicLoaderDarwinKernelProperties.inc"
#include "DynamicLoaderDarwinKernelPropertiesEnum.inc"
Classes
class DynamicLoaderDarwinKernelProperties
Macros
#define DEBUG_PRINTF(fmt, ...)
#define LLDB_PROPERTIES_dynamicloaderdarwinkernel
#define LLDB_PROPERTIES_dynamicloaderdarwinkernel
Enumerations
enum KASLRScanType { eKASLRScanNone = 0 , eKASLRScanLowgloAddresses , eKASLRScanNearPC , eKASLRScanExhaustiveScan }
enum
Functions
static DynamicLoaderDarwinKernelProperties & GetGlobalProperties ()
static bool is_kernel (Module *module)
Variables
static constexpr OptionEnumValueElement g_kaslr_kernel_scan_enum_values []
Macro Definition Documentation
DEBUG_PRINTF
#define DEBUG_PRINTF (fmt, ...)
Definition at line 43 of file DynamicLoaderDarwinKernel.cpp.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::FindCompleteObjCDefinitionTypeForDIE(), DynamicLoaderMacOSXDYLD::InitializeFromAllImageInfos(), DynamicLoaderDarwinKernel::PrivateInitialize(), lldb_private::DynamicLoaderDarwin::PrivateInitialize(), DynamicLoaderDarwinKernel::PrivateProcessStateChanged(), lldb_private::DynamicLoaderDarwin::PrivateProcessStateChanged(), DynamicLoaderMacOSXDYLD::SetNotificationBreakpoint(), and DynamicLoaderDarwinKernel::SetNotificationBreakpointIfNeeded().
LLDB_PROPERTIES_dynamicloaderdarwinkernel [1/2]
#define LLDB_PROPERTIES_dynamicloaderdarwinkernel
Definition at line 92 of file DynamicLoaderDarwinKernel.cpp.
LLDB_PROPERTIES_dynamicloaderdarwinkernel [2/2]
#define LLDB_PROPERTIES_dynamicloaderdarwinkernel
Definition at line 92 of file DynamicLoaderDarwinKernel.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Definition at line 95 of file DynamicLoaderDarwinKernel.cpp.
KASLRScanType
enum KASLRScanType
Enumerator
eKASLRScanNone
eKASLRScanLowgloAddresses
eKASLRScanNearPC
eKASLRScanExhaustiveScan
Definition at line 56 of file DynamicLoaderDarwinKernel.cpp.
Function Documentation
GetGlobalProperties()
DynamicLoaderDarwinKernelProperties & GetGlobalProperties () static
Definition at line 130 of file DynamicLoaderDarwinKernel.cpp.
Referenced by lldb_private::StructuredDataDarwinLog::AddInitCompletionHook(), DynamicLoaderDarwinKernel::DebuggerInitialize(), lldb_private::platform_android::PlatformAndroid::DebuggerInitialize(), lldb_private::PlatformDarwin::DebuggerInitialize(), lldb_private::PlatformQemuUser::DebuggerInitialize(), lldb_private::PlatformWasm::DebuggerInitialize(), lldb_private::StructuredDataDarwinLog::DebuggerInitialize(), lldb_private::PlatformQemuUser::DebugProcess(), lldb_private::PlatformWasm::DebugProcess(), lldb_private::StructuredDataDarwinLog::FilterLaunchInfo(), lldb_private::PlatformQemuUser::GetEnvironment(), lldb_private::PlatformDarwin::GetExtraStartupCommands(), lldb_private::platform_android::PlatformAndroid::GetRunAs(), lldb_private::PlatformQemuUser::GetSupportedArchitectures(), lldb_private::StructuredDataDarwinLog::ModulesDidLoad(), DynamicLoaderDarwinKernel::ParseKextSummaries(), DynamicLoaderDarwinKernel::SearchForKernelNearPC(), DynamicLoaderDarwinKernel::SearchForKernelViaExhaustiveSearch(), and DynamicLoaderDarwinKernel::SearchForKernelWithDebugHints().
is_kernel()
bool is_kernel (Module * module) static
Definition at line 135 of file DynamicLoaderDarwinKernel.cpp.
References lldb_private::ObjectFile::eStrataKernel, lldb_private::ObjectFile::eTypeExecutable, lldb_private::ObjectFile::GetStrata(), and lldb_private::ObjectFile::GetType().
Referenced by DynamicLoaderDarwinKernel::CheckForKernelImageAtAddress(), DynamicLoaderDarwinKernel::CreateInstance(), DynamicLoaderFreeBSDKernel::CreateInstance(), DynamicLoaderFreeBSDKernel::FindKernelAtLoadAddress(), DynamicLoaderDarwinKernel::KextImageInfo::LoadImageUsingMemoryModule(), DynamicLoaderDarwinKernel::LoadKernelModuleIfNeeded(), DynamicLoaderFreeBSDKernel::LoadKernelModules(), DynamicLoaderFreeBSDKernel::ParseKmods(), DynamicLoaderDarwinKernel::KextImageInfo::ReadMemoryModule(), DynamicLoaderFreeBSDKernel::KModImageInfo::ReadMemoryModule(), DynamicLoaderDarwinKernel::SearchForKernelAtSameLoadAddr(), DynamicLoaderDarwinKernel::KextImageInfo::SetIsKernel(), DynamicLoaderFreeBSDKernel::KModImageInfo::SetIsKernel(), and DynamicLoaderDarwinKernel::KextImageInfo::SetModule().
Variable Documentation
g_kaslr_kernel_scan_enum_values
OptionEnumValueElement g_kaslr_kernel_scan_enum_values[] static constexpr
Initial value:
= {
    {
        eKASLRScanNone,
        "none",
        "Do not read memory looking for a Darwin kernel when attaching.",
    },
    {
        eKASLRScanLowgloAddresses,
        "basic",
        "Check for the Darwin kernel's load addr in the lowglo page "
        "(boot-args=debug) only.",
    },
    {
        eKASLRScanNearPC,
        "fast-scan",
        "Scan near the pc value on attach to find the Darwin kernel's load "
        "address.",
    },
    {
        eKASLRScanExhaustiveScan,
        "exhaustive-scan",
        "Scan through the entire potential address range of Darwin kernel "
        "(only on 32-bit targets).",
    },
}
Definition at line 66 of file DynamicLoaderDarwinKernel.cpp.