LLDB: DynamicLoaderPOSIXDYLD.cpp File Reference
DynamicLoaderPOSIXDYLD.cpp File Reference
#include "DynamicLoaderPOSIXDYLD.h"
#include "Plugins/ObjectFile/Placeholder/ObjectFilePlaceholder.h"
#include "lldb/Breakpoint/BreakpointLocation.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Section.h"
#include "lldb/Symbol/Function.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Target/MemoryRegionInfo.h"
#include "lldb/Target/Platform.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Target/ThreadPlanRunToAddress.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/ProcessInfo.h"
#include "llvm/Support/ThreadPool.h"
#include <memory>
#include <optional>
Functions
static void AddThreadLocalMemoryRegions (Process &process, ThreadSP &thread_sp, std::vector< MemoryRegionInfo > &ranges)
static void AddLinkMapSections (Process &process, std::vector< MemoryRegionInfo > &ranges)
Function Documentation
AddLinkMapSections()
void AddLinkMapSections (Process & process, std::vector< MemoryRegionInfo > & ranges) static
Definition at line 989 of file DynamicLoaderPOSIXDYLD.cpp.
References lldb_private::Status::Fail(), lldb_private::ObjectFile::GetImageInfoAddress(), lldb_private::Target::GetImages(), lldb_private::Address::GetLoadAddress(), lldb_private::Process::GetMemoryRegionInfo(), lldb_private::ModuleList::GetModuleAtIndex(), lldb_private::ModuleList::GetSize(), lldb_private::Process::GetTarget(), and LLDB_INVALID_ADDRESS.
Referenced by DynamicLoaderPOSIXDYLD::CalculateDynamicSaveCoreRanges().
AddThreadLocalMemoryRegions()
void AddThreadLocalMemoryRegions (Process & process, ThreadSP & thread_sp, std::vector< MemoryRegionInfo > & ranges) static
Definition at line 957 of file DynamicLoaderPOSIXDYLD.cpp.
References lldb::eRegisterKindGeneric, lldb_private::Status::Fail(), lldb_private::RegisterValue::GetAsUInt64(), lldb_private::Process::GetMemoryRegionInfo(), LLDB_REGNUM_GENERIC_TP, and UINT64_MAX.
Referenced by DynamicLoaderPOSIXDYLD::CalculateDynamicSaveCoreRanges().