LLDB: DynamicLoader.cpp File Reference
DynamicLoader.cpp File Reference
#include "lldb/Target/DynamicLoader.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleList.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Progress.h"
#include "lldb/Core/Section.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Target/MemoryRegionInfo.h"
#include "lldb/Target/Platform.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/lldb-private-interfaces.h"
#include "llvm/ADT/StringRef.h"
#include <memory>
#include <cassert>
Functions
static ModuleSP ReadUnnamedMemoryModule (Process *process, addr_t addr, llvm::StringRef name)
Function Documentation
ReadUnnamedMemoryModule()
ModuleSP ReadUnnamedMemoryModule (Process * process, addr_t addr, llvm::StringRef name) static
Definition at line 199 of file DynamicLoader.cpp.
References lldb_private::DynamicLoader, lldb_private::GetLog(), LLDB_LOG_ERROR, and lldb_private::Process::ReadModuleFromMemory().
Referenced by lldb_private::DynamicLoader::LoadBinaryWithUUIDAndAddress().