LLDB: DynamicLoaderFreeBSDKernel.cpp File Reference
DynamicLoaderFreeBSDKernel.cpp File Reference
#include "lldb/Breakpoint/StoppointCallbackContext.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Section.h"
#include "lldb/Host/StreamFile.h"
#include "lldb/Interpreter/OptionValueProperties.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Target/OperatingSystem.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Target/ThreadPlanRunToAddress.h"
#include "lldb/Utility/DataBuffer.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/State.h"
#include "Plugins/ObjectFile/ELF/ObjectFileELF.h"
#include "DynamicLoaderFreeBSDKernel.h"
#include <memory>
#include <mutex>
Functions
static bool is_kernel (Module *module)
static bool is_kmod (Module *module)
static bool is_reloc (Module *module)
Function Documentation
is_kernel()
bool is_kernel (Module * module) static
Definition at line 56 of file DynamicLoaderFreeBSDKernel.cpp.
References lldb_private::ObjectFile::eStrataKernel, lldb_private::ObjectFile::eStrataUnknown, lldb_private::ObjectFile::eTypeExecutable, lldb_private::ObjectFile::GetStrata(), and lldb_private::ObjectFile::GetType().
is_kmod()
bool is_kmod (Module * module) static
Definition at line 72 of file DynamicLoaderFreeBSDKernel.cpp.
References lldb_private::ObjectFile::eTypeObjectFile, lldb_private::ObjectFile::eTypeSharedLibrary, lldb_private::Module::GetObjectFile(), and lldb_private::ObjectFile::GetType().
Referenced by DynamicLoaderFreeBSDKernel::KModImageInfo::LoadImageUsingMemoryModule(), and DynamicLoaderFreeBSDKernel::ParseKmods().
is_reloc()
bool is_reloc (Module * module) static
Definition at line 85 of file DynamicLoaderFreeBSDKernel.cpp.
References lldb_private::ObjectFile::eTypeObjectFile, lldb_private::Module::GetObjectFile(), and lldb_private::ObjectFile::GetType().
Referenced by DynamicLoaderFreeBSDKernel::KModImageInfo::LoadImageUsingMemoryModule().