LLDB: DynamicLoaderHexagonDYLD.cpp File Reference
DynamicLoaderHexagonDYLD.cpp File Reference
#include "lldb/Breakpoint/BreakpointLocation.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Section.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Target/ThreadPlanRunToAddress.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "DynamicLoaderHexagonDYLD.h"
#include <memory>
Functions
static lldb::addr_t findSymbolAddress (Process *proc, ConstString findName)
static int ReadInt (Process *process, addr_t addr)
Function Documentation
findSymbolAddress()
lldb::addr_t findSymbolAddress (Process * proc, ConstString findName) static
Definition at line 50 of file DynamicLoaderHexagonDYLD.cpp.
References lldb_private::ConstString::Compare(), findSymbolAddress(), lldb_private::Symbol::GetAddress(), lldb_private::Address::GetLoadAddress(), lldb_private::Symbol::GetName(), lldb_private::Symtab::GetNumSymbols(), lldb_private::ObjectFile::GetSymtab(), LLDB_INVALID_ADDRESS, and lldb_private::Symtab::SymbolAtIndex().
Referenced by findSymbolAddress(), DynamicLoaderHexagonDYLD::RendezvousBreakpointHit(), and DynamicLoaderHexagonDYLD::SetRendezvousBreakpoint().
ReadInt()
int ReadInt (Process * process, addr_t addr) static
Definition at line 539 of file DynamicLoaderHexagonDYLD.cpp.
References error(), and lldb_private::Process::ReadUnsignedIntegerFromMemory().
Referenced by DynamicLoaderHexagonDYLD::GetThreadLocalData().