LLDB: ELFHeader.cpp File Reference
ELFHeader.cpp File Reference
#include <cstring>
#include "lldb/Core/Section.h"
#include "lldb/Utility/DataExtractor.h"
#include "lldb/Utility/Stream.h"
#include "ELFHeader.h"
Macros
#define ENUM_TO_CSTR(e)
Functions
static bool GetMaxU64 (const lldb_private::DataExtractor &data, lldb::offset_t *offset, uint64_t *value, uint32_t byte_size)
static bool GetMaxU64 (const lldb_private::DataExtractor &data, lldb::offset_t *offset, uint64_t *value, uint32_t byte_size, uint32_t count)
static bool GetMaxS64 (const lldb_private::DataExtractor &data, lldb::offset_t *offset, int64_t *value, uint32_t byte_size)
static bool GetMaxS64 (const lldb_private::DataExtractor &data, lldb::offset_t *offset, int64_t *value, uint32_t byte_size, uint32_t count)
Macro Definition Documentation
ENUM_TO_CSTR
#define ENUM_TO_CSTR (e)
Value:
  case e:                                                                      \
    return #e
Definition at line 259 of file ELFHeader.cpp.
Function Documentation
GetMaxS64() [1/2]
bool GetMaxS64 (const lldb_private::DataExtractor & data, lldb::offset_t * offset, int64_t * value, uint32_t byte_size) static
Definition at line 47 of file ELFHeader.cpp.
References lldb_private::DataExtractor::GetMaxS64().
Referenced by GetMaxS64(), elf::ELFDynamic::Parse(), and elf::ELFRela::Parse().
GetMaxS64() [2/2]
bool GetMaxS64 (const lldb_private::DataExtractor & data, lldb::offset_t * offset, int64_t * value, uint32_t byte_size, uint32_t count) static
Definition at line 55 of file ELFHeader.cpp.
References GetMaxS64().
GetMaxU64() [1/2]
bool GetMaxU64 (const lldb_private::DataExtractor & data, lldb::offset_t * offset, uint64_t * value, uint32_t byte_size) static
Definition at line 25 of file ELFHeader.cpp.
References lldb_private::DataExtractor::GetMaxU64().
Referenced by GetMaxU64(), elf::ELFHeader::Parse(), elf::ELFProgramHeader::Parse(), elf::ELFRel::Parse(), elf::ELFRela::Parse(), elf::ELFSectionHeader::Parse(), and elf::ELFSymbol::Parse().
GetMaxU64() [2/2]
bool GetMaxU64 (const lldb_private::DataExtractor & data, lldb::offset_t * offset, uint64_t * value, uint32_t byte_size, uint32_t count) static
Definition at line 33 of file ELFHeader.cpp.
References GetMaxU64().