LLDB: FileSpecList.cpp File Reference
FileSpecList.cpp File Reference
#include "lldb/Utility/FileSpecList.h"
#include "lldb/Target/Statistics.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/RealpathPrefixes.h"
#include "lldb/Utility/Stream.h"
#include <cstdint>
#include <utility>
Enumerations
enum IsCompatibleResult { kNoMatch = 0 , kOnlyFileMatch = 1 , kBothDirectoryAndFileMatch = 2 }
Functions
static size_t FindFileIndex (size_t start_idx, const FileSpec &file_spec, bool full, size_t num_files, std::function< const FileSpec &(size_t)> get_ith)
IsCompatibleResult IsCompatible (const FileSpec &curr_file, const FileSpec &file_spec)
Enumeration Type Documentation
IsCompatibleResult
enum IsCompatibleResult
Enumerator
kNoMatch
kOnlyFileMatch
kBothDirectoryAndFileMatch
Definition at line 115 of file FileSpecList.cpp.
Function Documentation
FindFileIndex()
size_t FindFileIndex (size_t start_idx, const FileSpec & file_spec, bool full, size_t num_files, std::function< const FileSpec &(size_t)> get_ith) static
Definition at line 75 of file FileSpecList.cpp.
References lldb_private::FileSpec::Equal(), lldb_private::ConstString::Equals(), lldb_private::FileSpec::GetDirectory(), lldb_private::FileSpec::GetFilename(), lldb_private::FileSpec::IsCaseSensitive(), lldb_private::ConstString::IsEmpty(), and UINT32_MAX.
IsCompatible()
IsCompatibleResult IsCompatible (const FileSpec & curr_file, const FileSpec & file_spec)
Definition at line 121 of file FileSpecList.cpp.
References lldb_private::FileSpec::Equal(), lldb_private::FileSpec::FileEquals(), lldb_private::FileSpec::GetDirectory(), lldb_private::ConstString::GetStringRef(), lldb_private::FileSpec::IsCaseSensitive(), lldb_private::ConstString::IsEmpty(), lldb_private::FileSpec::IsRelative(), kBothDirectoryAndFileMatch, kNoMatch, and kOnlyFileMatch.
Referenced by lldb_private::SupportFileList::FindCompatibleIndex().