LLDB: FormatManager.cpp File Reference
FormatManager.cpp File Reference
#include "lldb/DataFormatters/FormatManager.h"
#include "lldb/Core/Debugger.h"
#include "lldb/DataFormatters/FormattersHelpers.h"
#include "lldb/DataFormatters/LanguageCategory.h"
#include "lldb/Interpreter/ScriptInterpreter.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/Language.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/ValueObject/ValueObject.h"
#include "llvm/ADT/STLExtras.h"
Classes
struct FormatInfo
Macros
#define FORMAT_LOG(Message)
Functions
static bool GetFormatFromFormatChar (char format_char, Format &format)
static bool GetFormatFromFormatName (llvm::StringRef format_name, Format &format)
Variables
static constexpr FormatInfo g_format_infos []
static uint32_t g_num_format_infos = std::size(g_format_infos)
Macro Definition Documentation
FORMAT_LOG
#define FORMAT_LOG (Message)
Value:
"[%s] " Message, FormatterKind<ImplSP>
Definition at line 626 of file FormatManager.cpp.
Referenced by lldb_private::FormatManager::Get(), and lldb_private::FormatManager::GetCached().
Function Documentation
GetFormatFromFormatChar()
bool GetFormatFromFormatChar (char format_char, Format & format) static
Definition at line 84 of file FormatManager.cpp.
References lldb::eFormatInvalid, g_format_infos, and g_num_format_infos.
Referenced by lldb_private::FormatManager::GetFormatFromCString().
GetFormatFromFormatName()
bool GetFormatFromFormatName (llvm::StringRef format_name, Format & format) static
Definition at line 95 of file FormatManager.cpp.
References lldb::eFormatInvalid, g_format_infos, and g_num_format_infos.
Referenced by lldb_private::FormatManager::GetFormatFromCString().
Variable Documentation
g_format_infos
FormatInfo g_format_infos[] static constexpr
Definition at line 34 of file FormatManager.cpp.
Referenced by lldb_private::FormatManager::GetFormatAsCString(), lldb_private::FormatManager::GetFormatAsFormatChar(), GetFormatFromFormatChar(), and GetFormatFromFormatName().
g_num_format_infos
uint32_t g_num_format_infos = std::size(g_format_infos) static
Definition at line 82 of file FormatManager.cpp.
Referenced by lldb_private::FormatManager::GetFormatAsFormatChar(), GetFormatFromFormatChar(), and GetFormatFromFormatName().