LLDB: FormatCache.cpp File Reference
FormatCache.cpp File Reference
#include "lldb/DataFormatters/FormatCache.h"
Namespaces
namespace lldb_private
A class that represents a running process on the host machine.
Functions
template<>
bool lldb_private::FormatCache::Entry::IsCached< lldb::TypeFormatImplSP > ()
template<>
bool lldb_private::FormatCache::Entry::IsCached< lldb::TypeSummaryImplSP > ()
template<>
bool lldb_private::FormatCache::Entry::IsCached< lldb::SyntheticChildrenSP > ()
template bool FormatCache::Get< lldb::TypeFormatImplSP > (ConstString, lldb::TypeFormatImplSP &)
Explicit instantiations for the three types.
template bool FormatCache::Get< lldb::TypeSummaryImplSP > (ConstString, lldb::TypeSummaryImplSP &)
template bool FormatCache::Get< lldb::SyntheticChildrenSP > (ConstString, lldb::SyntheticChildrenSP &)
Function Documentation
FormatCache::Get< lldb::SyntheticChildrenSP >()
template bool FormatCache::Get< lldb::SyntheticChildrenSP > (ConstString , lldb::SyntheticChildrenSP &)
References lldb_private::FormatCache::Get().
FormatCache::Get< lldb::TypeFormatImplSP >()
template bool FormatCache::Get< lldb::TypeFormatImplSP > (ConstString , lldb::TypeFormatImplSP &)
Explicit instantiations for the three types.
References lldb_private::FormatCache::Get().
FormatCache::Get< lldb::TypeSummaryImplSP >()
template bool FormatCache::Get< lldb::TypeSummaryImplSP > (ConstString , lldb::TypeSummaryImplSP &)
References lldb_private::FormatCache::Get().