LLDB: FormatEntity.cpp File Reference
FormatEntity.cpp File Reference
#include "lldb/Core/FormatEntity.h"
#include "lldb/Core/Address.h"
#include "lldb/Core/AddressRange.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/DumpRegisterValue.h"
#include "lldb/Core/Module.h"
#include "lldb/DataFormatters/DataVisualization.h"
#include "lldb/DataFormatters/FormatClasses.h"
#include "lldb/DataFormatters/FormatManager.h"
#include "lldb/DataFormatters/TypeSummary.h"
#include "lldb/Expression/ExpressionVariable.h"
#include "lldb/Interpreter/CommandInterpreter.h"
#include "lldb/Symbol/Block.h"
#include "lldb/Symbol/CompileUnit.h"
#include "lldb/Symbol/CompilerType.h"
#include "lldb/Symbol/Function.h"
#include "lldb/Symbol/LineEntry.h"
#include "lldb/Symbol/Symbol.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Symbol/VariableList.h"
#include "lldb/Target/BorrowedStackFrame.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/ExecutionContextScope.h"
#include "lldb/Target/Language.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/SectionLoadList.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/StopInfo.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/AnsiTerminal.h"
#include "lldb/Utility/ArchSpec.h"
#include "lldb/Utility/CompletionRequest.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/FileSpec.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/RegisterValue.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/Stream.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/Utility/StringList.h"
#include "lldb/Utility/StructuredData.h"
#include "lldb/ValueObject/ValueObject.h"
#include "lldb/ValueObject/ValueObjectVariable.h"
#include "lldb/lldb-defines.h"
#include "lldb/lldb-forward.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Regex.h"
#include "llvm/TargetParser/Triple.h"
#include <cassert>
#include <cctype>
#include <cinttypes>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <type_traits>
#include <utility>
Namespaces
namespace lldb_private
A class that represents a running process on the host machine.
Macros
#define _TO_STR2(_val)
#define _TO_STR(_val)
#define ENUM_TO_CSTR(eee)
Typedefs
using Definition = lldb_private::FormatEntity::Entry::Definition
using Entry = FormatEntity::Entry
using EntryType = FormatEntity::Entry::Type
Enumerations
enum FileKind { FileError = 0 , Basename , Dirname , Fullpath }
Functions
template<typename T>
static bool RunScriptFormatKeyword (Stream &s, const SymbolContext *sc, const ExecutionContext *exe_ctx, T t, const char *script_function_name)
static bool DumpAddressAndContent (Stream &s, const SymbolContext *sc, const ExecutionContext *exe_ctx, const Address &addr, bool print_file_addr_or_load_addr)
static bool DumpAddressOffsetFromFunction (Stream &s, const SymbolContext *sc, const ExecutionContext *exe_ctx, const Address &format_addr, bool concrete_only, bool no_padding, bool print_zero_offsets)
static bool ScanBracketedRange (llvm::StringRef subpath, size_t &close_bracket_index, const char *&var_name_final_if_array_range, int64_t &index_lower, int64_t &index_higher)
static bool DumpFile (Stream &s, const FileSpec &file, FileKind file_kind)
static bool DumpRegister (Stream &s, StackFrame *frame, RegisterKind reg_kind, uint32_t reg_num, Format format)
static ValueObjectSP ExpandIndexedExpression (ValueObject *valobj, size_t index, bool deref_pointer)
static char ConvertValueObjectStyleToChar (ValueObject::ValueObjectRepresentationStyle style)
static bool DumpValueWithLLVMFormat (Stream &s, llvm::StringRef options, ValueObject &valobj)
static bool DumpRegister (Stream &s, StackFrame *frame, const char *reg_name, Format format)
static bool FormatThreadExtendedInfoRecurse (const FormatEntity::Entry &entry, const StructuredData::ObjectSP &thread_info_dictionary, const SymbolContext *sc, const ExecutionContext *exe_ctx, Stream &s)
static bool IsToken (const char *var_name_begin, const char *var)
static std::pair< char const *, char const * > ParseBaseName (char const *full_name)
Parses the basename out of a demangled function name that may include function arguments.
static void PrettyPrintFunctionNameWithArgs (Stream &out_stream, char const *full_name, ExecutionContextScope *exe_scope, VariableList const &args)
Writes out the function name in 'full_name' to 'out_stream' but replaces each argument type with the variable name and the corresponding pretty-printed value.
static VariableListSP GetFunctionVariableList (const SymbolContext &sc)
static bool PrintFunctionNameWithArgs (Stream &s, const ExecutionContext *exe_ctx, const SymbolContext &sc)
static bool HandleFunctionNameWithArgs (Stream &s, const ExecutionContext *exe_ctx, const SymbolContext &sc)
static bool DumpCommaSeparatedChildEntryNames (Stream &s, const Definition *parent)
static Status ParseEntry (const llvm::StringRef &format_str, const Definition *parent, FormatEntity::Entry &entry)
static const Definition * FindEntry (const llvm::StringRef &format_str, const Definition *parent, llvm::StringRef &remainder)
static Status ParseInternal (llvm::StringRef &format, Entry &parent_entry, uint32_t depth)
static std::string MakeMatch (const llvm::StringRef &prefix, const char *suffix)
static void AddMatches (const Definition *def, const llvm::StringRef &prefix, const llvm::StringRef &match_prefix, StringList &matches)
Variables
constexpr Definition g_string_entry []
constexpr Definition g_addr_entries []
constexpr Definition g_file_child_entries []
constexpr Definition g_frame_child_entries []
constexpr Definition g_function_child_entries []
constexpr Definition g_line_child_entries []
constexpr Definition g_module_child_entries []
constexpr Definition g_process_child_entries []
constexpr Definition g_svar_child_entries []
constexpr Definition g_var_child_entries []
constexpr Definition g_thread_child_entries []
constexpr Definition g_target_child_entries []
constexpr Definition g_progress_child_entries []
constexpr Definition g_ansi_fg_entries []
constexpr Definition g_ansi_bg_entries []
constexpr Definition g_ansi_entries []
constexpr Definition g_script_child_entries []
constexpr Definition g_top_level_entries []
constexpr Definition g_root
static llvm::Regex LLVMFormatPattern {"x[-+]?\\d*|n|d", llvm::Regex::IgnoreCase}
Options supported by format_provider<T> for integral arithmetic types.
Macro Definition Documentation
_TO_STR
#define _TO_STR (_val)
Value:
_TO_STR2(_val)
Definition at line 190 of file FormatEntity.cpp.
_TO_STR2
#define _TO_STR2 (_val)
Value:
#_val
Definition at line 189 of file FormatEntity.cpp.
ENUM_TO_CSTR
#define ENUM_TO_CSTR (eee)
Value:
  case FormatEntity::Entry::Type::eee:                                         \
    return #eee
Definition at line 338 of file FormatEntity.cpp.
Referenced by elf::ELFSymbol::bindingToCString(), lldb_private::minidump::MinidumpParser::GetStreamTypeAsString(), elf::ELFSymbol::sectionIndexToCString(), lldb_private::FormatEntity::Entry::TypeToCString(), and elf::ELFSymbol::typeToCString().
Typedef Documentation
Definition
using Definition = lldb_private::FormatEntity::Entry::Definition
Definition at line 84 of file FormatEntity.cpp.
Entry
using Entry = FormatEntity::Entry
Definition at line 85 of file FormatEntity.cpp.
EntryType
using EntryType = FormatEntity::Entry::Type
Definition at line 86 of file FormatEntity.cpp.
Enumeration Type Documentation
FileKind
enum FileKind
Enumerator
FileError
Basename
Dirname
Fullpath
Definition at line 88 of file FormatEntity.cpp.
Function Documentation
AddMatches()
void AddMatches (const Definition * def, const llvm::StringRef & prefix, const llvm::StringRef & match_prefix, StringList & matches) static
Definition at line 2576 of file FormatEntity.cpp.
References lldb_private::StringList::AppendString(), lldb_private::FormatEntity::Entry::Definition::children, MakeMatch(), lldb_private::FormatEntity::Entry::Definition::name, and lldb_private::FormatEntity::Entry::Definition::num_children.
Referenced by lldb_private::FormatEntity::AutoComplete().
ConvertValueObjectStyleToChar()
char ConvertValueObjectStyleToChar (ValueObject::ValueObjectRepresentationStyle style) static
Definition at line 703 of file FormatEntity.cpp.
References lldb_private::ValueObject::eValueObjectRepresentationStyleChildrenCount, lldb_private::ValueObject::eValueObjectRepresentationStyleExpressionPath, lldb_private::ValueObject::eValueObjectRepresentationStyleLanguageSpecific, lldb_private::ValueObject::eValueObjectRepresentationStyleLocation, lldb_private::ValueObject::eValueObjectRepresentationStyleName, lldb_private::ValueObject::eValueObjectRepresentationStyleSummary, lldb_private::ValueObject::eValueObjectRepresentationStyleType, and lldb_private::ValueObject::eValueObjectRepresentationStyleValue.
Referenced by lldb_private::FormatEntity::Formatter::DumpValue().
DumpAddressAndContent()
bool DumpAddressAndContent (Stream & s, const SymbolContext * sc, const ExecutionContext * exe_ctx, const Address & addr, bool print_file_addr_or_load_addr) static
Definition at line 474 of file FormatEntity.cpp.
References lldb_private::Address::Dump(), lldb_private::Address::DumpStyleLoadAddress, lldb_private::Address::DumpStyleModuleWithFileAddress, lldb_private::ArchSpec::GetAddressByteSize(), lldb_private::Target::GetArchitecture(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::Address::GetFileAddress(), lldb_private::Address::GetLoadAddress(), lldb_private::Target::GetTargetFromContexts(), LLDB_INVALID_ADDRESS, and lldb_private::Stream::Printf().
Referenced by lldb_private::FormatEntity::Formatter::Format().
DumpAddressOffsetFromFunction()
bool DumpAddressOffsetFromFunction (Stream & s, const SymbolContext * sc, const ExecutionContext * exe_ctx, const Address & format_addr, bool concrete_only, bool no_padding, bool print_zero_offsets) static
Definition at line 504 of file FormatEntity.cpp.
References lldb_private::SymbolContext::block, lldb_private::SymbolContext::function, lldb_private::Function::GetAddress(), lldb_private::Symbol::GetAddressRef(), lldb_private::AddressRange::GetBaseAddress(), lldb_private::Block::GetContainingInlinedBlock(), lldb_private::Address::GetFileAddress(), lldb_private::Address::GetLoadAddress(), lldb_private::Address::GetModule(), lldb_private::Block::GetRangeContainingAddress(), lldb_private::Target::GetTargetFromContexts(), lldb_private::Address::IsValid(), lldb_private::Stream::Printf(), lldb_private::SymbolContext::symbol, and lldb_private::Symbol::ValueIsAddress().
Referenced by lldb_private::FormatEntity::Formatter::Format().
DumpCommaSeparatedChildEntryNames()
bool DumpCommaSeparatedChildEntryNames (Stream & s, const Definition * parent) static
Definition at line 2093 of file FormatEntity.cpp.
References lldb_private::FormatEntity::Entry::Definition::children, lldb_private::FormatEntity::Entry::Definition::name, lldb_private::FormatEntity::Entry::Definition::num_children, lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
Referenced by ParseEntry().
DumpFile()
bool DumpFile (Stream & s, const FileSpec & file, FileKind file_kind) static
Definition at line 623 of file FormatEntity.cpp.
References Basename, Dirname, FileError, Fullpath, lldb_private::FileSpec::GetDirectory(), and lldb_private::FileSpec::GetFilename().
Referenced by lldb_private::FormatEntity::Formatter::Format().
DumpRegister() [1/2]
bool DumpRegister (Stream & s, StackFrame * frame, const char * reg_name, Format format) static
Definition at line 1077 of file FormatEntity.cpp.
References lldb_private::DumpRegisterValue(), lldb_private::StackFrame::GetRegisterContext(), lldb_private::RegisterContext::GetRegisterInfoByName(), and lldb_private::RegisterContext::ReadRegister().
DumpRegister() [2/2]
bool DumpRegister (Stream & s, StackFrame * frame, RegisterKind reg_kind, uint32_t reg_num, Format format) static
Definition at line 652 of file FormatEntity.cpp.
References lldb_private::RegisterContext::ConvertRegisterKindToRegisterNumber(), lldb_private::DumpRegisterValue(), lldb_private::StackFrame::GetRegisterContext(), lldb_private::RegisterContext::GetRegisterInfoAtIndex(), LLDB_INVALID_REGNUM, and lldb_private::RegisterContext::ReadRegister().
Referenced by lldb_private::FormatEntity::Formatter::Format().
DumpValueWithLLVMFormat()
bool DumpValueWithLLVMFormat (Stream & s, llvm::StringRef options, ValueObject & valobj) static
Definition at line 730 of file FormatEntity.cpp.
References lldb_private::ValueObject::GetTypeInfo(), lldb_private::ValueObject::GetValueAsSigned(), lldb_private::ValueObject::GetValueAsUnsigned(), integer, LLVMFormatPattern, and lldb_private::Stream::Write().
Referenced by lldb_private::FormatEntity::Formatter::DumpValue().
ExpandIndexedExpression()
ValueObjectSP ExpandIndexedExpression (ValueObject * valobj, size_t index, bool deref_pointer) static
Definition at line 676 of file FormatEntity.cpp.
References lldb_private::DataFormatters, lldb_private::ValueObject::eExpressionPathAftermathDereference, lldb_private::ValueObject::eExpressionPathAftermathNothing, lldb_private::GetLog(), lldb_private::ValueObject::GetValueForExpressionPath(), LLDB_LOG, and LLDB_LOGF.
Referenced by lldb_private::FormatEntity::Formatter::DumpValue().
FindEntry()
const Definition * FindEntry (const llvm::StringRef & format_str, const Definition * parent, llvm::StringRef & remainder) static
Definition at line 2193 of file FormatEntity.cpp.
References lldb_private::FormatEntity::Entry::Definition::children, error(), FindEntry(), lldb_private::FormatEntity::Entry::Definition::name, and lldb_private::FormatEntity::Entry::Definition::num_children.
Referenced by lldb_private::FormatEntity::AutoComplete(), and FindEntry().
FormatThreadExtendedInfoRecurse()
bool FormatThreadExtendedInfoRecurse (const FormatEntity::Entry & entry, const StructuredData::ObjectSP & thread_info_dictionary, const SymbolContext * sc, const ExecutionContext * exe_ctx, Stream & s) static
Definition at line 1096 of file FormatEntity.cpp.
References lldb::eStructuredDataTypeArray, lldb::eStructuredDataTypeDictionary, lldb::eStructuredDataTypeFloat, lldb::eStructuredDataTypeInteger, lldb::eStructuredDataTypeString, lldb_private::Stream::Format(), lldb_private::Stream::Printf(), lldb_private::FormatEntity::Entry::printf_format, and lldb_private::FormatEntity::Entry::string.
Referenced by lldb_private::FormatEntity::Formatter::Format().
GetFunctionVariableList()
VariableListSP GetFunctionVariableList (const SymbolContext & sc) static
Definition at line 1202 of file FormatEntity.cpp.
References lldb_private::SymbolContext::block, lldb_private::SymbolContext::function, lldb_private::Function::GetBlock(), lldb_private::Block::GetBlockVariableList(), and lldb_private::Block::GetContainingInlinedBlock().
Referenced by lldb_private::CPlusPlusLanguage::HandleFrameFormatVariable(), PrintFunctionNameWithArgs(), and PrintFunctionNameWithArgs().
HandleFunctionNameWithArgs()
bool HandleFunctionNameWithArgs (Stream & s, const ExecutionContext * exe_ctx, const SymbolContext & sc) static
Definition at line 1240 of file FormatEntity.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::Language::eNameWithArgs, lldb_private::Language::FindPlugin(), lldb_private::SymbolContext::function, lldb_private::Language::GetFunctionDisplayName(), lldb_private::Function::GetLanguage(), lldb_private::Symbol::GetLanguage(), lldb_private::Symbol::GetName(), lldb_private::StreamString::GetString(), PrintFunctionNameWithArgs(), lldb_private::Stream::PutCString(), and lldb_private::SymbolContext::symbol.
Referenced by lldb_private::FormatEntity::Formatter::Format().
IsToken()
bool IsToken (const char * var_name_begin, const char * var) inline static
Definition at line 1133 of file FormatEntity.cpp.
Referenced by ParseBaseName().
MakeMatch()
std::string MakeMatch (const llvm::StringRef & prefix, const char * suffix) static
Definition at line 2569 of file FormatEntity.cpp.
Referenced by AddMatches(), and lldb_private::FormatEntity::AutoComplete().
ParseBaseName()
std::pair< char const *, char const * > ParseBaseName (char const * full_name) static
Parses the basename out of a demangled function name that may include function arguments.
Supports template functions.
Returns pointers to the opening and closing parenthesis of full_name. Can return nullptr for either parenthesis if none is exists.
Definition at line 1145 of file FormatEntity.cpp.
References IsToken().
Referenced by PrettyPrintFunctionNameWithArgs().
ParseEntry()
Status ParseEntry (const llvm::StringRef & format_str, const Definition * parent, FormatEntity::Entry & entry) static
Definition at line 2107 of file FormatEntity.cpp.
References lldb_private::FormatEntity::Entry::Definition::children, lldb_private::FormatEntity::Entry::Definition::data, DumpCommaSeparatedChildEntryNames(), error(), lldb_private::FormatEntity::Entry::EscapeCode, lldb_private::Status::FromErrorStringWithFormat(), lldb_private::StreamString::GetData(), lldb_private::FormatEntity::Entry::Invalid, lldb_private::FormatEntity::Entry::Definition::keep_separator, lldb_private::FormatEntity::Entry::Definition::name, lldb_private::FormatEntity::Entry::Definition::num_children, lldb_private::FormatEntity::Entry::number, lldb_private::FormatEntity::Entry::ParentNumber, lldb_private::FormatEntity::Entry::ParentString, ParseEntry(), lldb_private::Stream::Printf(), lldb_private::FormatEntity::Entry::Root, lldb_private::FormatEntity::Entry::Definition::string, lldb_private::FormatEntity::Entry::string, lldb_private::FormatEntity::Entry::Definition::type, and lldb_private::FormatEntity::Entry::type.
Referenced by ParseEntry(), and ParseInternal().
ParseInternal()
Status ParseInternal (llvm::StringRef & format, Entry & parent_entry, uint32_t depth) static
Definition at line 2223 of file FormatEntity.cpp.
References lldb_private::FormatEntity::Entry::AppendChar(), lldb_private::FormatEntity::Entry::AppendEntry(), lldb_private::FormatEntity::Entry::AppendText(), lldb_private::FormatEntity::Entry::deref, error(), lldb_private::ValueObject::eValueObjectRepresentationStyleChildrenCount, lldb_private::ValueObject::eValueObjectRepresentationStyleExpressionPath, lldb_private::ValueObject::eValueObjectRepresentationStyleLocation, lldb_private::ValueObject::eValueObjectRepresentationStyleName, lldb_private::ValueObject::eValueObjectRepresentationStyleSummary, lldb_private::ValueObject::eValueObjectRepresentationStyleType, lldb_private::ValueObject::eValueObjectRepresentationStyleValue, lldb_private::FormatEntity::ExtractVariableInfo(), lldb_private::FormatEntity::Entry::fmt, lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), g_root, lldb_private::FormatManager::GetFormatFromCString(), LLVMFormatPattern, lldb_private::FormatEntity::Entry::number, ParseEntry(), ParseInternal(), lldb_private::FormatEntity::Entry::printf_format, lldb_private::FormatEntity::Entry::Scope, lldb_private::FormatEntity::Entry::StartAlternative(), lldb_private::FormatEntity::Entry::string, lldb_private::FormatEntity::Entry::ThreadID, lldb_private::FormatEntity::Entry::ThreadProtocolID, lldb_private::FormatEntity::Entry::type, lldb_private::FormatEntity::Entry::Variable, and lldb_private::FormatEntity::Entry::VariableSynthetic.
Referenced by lldb_private::FormatEntity::Parse(), and ParseInternal().
PrettyPrintFunctionNameWithArgs()
void PrettyPrintFunctionNameWithArgs (Stream & out_stream, char const * full_name, ExecutionContextScope * exe_scope, VariableList const & args) static
Writes out the function name in 'full_name' to 'out_stream' but replaces each argument type with the variable name and the corresponding pretty-printed value.
Definition at line 1182 of file FormatEntity.cpp.
References ParseBaseName(), lldb_private::FormatEntity::PrettyPrintFunctionArguments(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), and lldb_private::Stream::Write().
Referenced by PrintFunctionNameWithArgs(), and PrintFunctionNameWithArgs().
PrintFunctionNameWithArgs()
bool PrintFunctionNameWithArgs (Stream & s, const ExecutionContext * exe_ctx, const SymbolContext & sc) static
Definition at line 1212 of file FormatEntity.cpp.
References lldb_private::VariableList::AppendVariablesWithScope(), lldb_private::ConstString::AsCString(), lldb_private::Mangled::ePreferDemangled, lldb::eValueTypeVariableArgument, lldb_private::SymbolContext::function, lldb_private::ExecutionContext::GetBestExecutionContextScope(), GetFunctionVariableList(), lldb_private::Mangled::GetName(), lldb_private::SymbolContext::GetPossiblyInlinedFunctionName(), lldb_private::VariableList::GetSize(), PrettyPrintFunctionNameWithArgs(), and lldb_private::Stream::PutCString().
Referenced by lldb_private::CPlusPlusLanguage::GetFunctionDisplayName(), and HandleFunctionNameWithArgs().
RunScriptFormatKeyword()
template<typename T> bool RunScriptFormatKeyword (Stream & s, const SymbolContext * sc, const ExecutionContext * exe_ctx, T t, const char * script_function_name) static
Definition at line 449 of file FormatEntity.cpp.
References error(), lldb_private::Target::GetDebugger(), lldb_private::Debugger::GetScriptInterpreter(), lldb_private::Target::GetTargetFromContexts(), lldb_private::Stream::Printf(), and lldb_private::ScriptInterpreter::RunScriptFormatKeyword().
Referenced by lldb_private::FormatEntity::Formatter::DumpValue(), and lldb_private::FormatEntity::Formatter::Format().
ScanBracketedRange()
bool ScanBracketedRange (llvm::StringRef subpath, size_t & close_bracket_index, const char *& var_name_final_if_array_range, int64_t & index_lower, int64_t & index_higher) static
Definition at line 565 of file FormatEntity.cpp.
References lldb_private::DataFormatters, lldb_private::GetLog(), and LLDB_LOGF.
Referenced by lldb_private::FormatEntity::Formatter::DumpValue().
Variable Documentation
g_addr_entries
Definition g_addr_entries[] constexpr
Initial value:
= {
    Definition("load", EntryType::AddressLoad),
    Definition("file", EntryType::AddressFile)}
Definition at line 93 of file FormatEntity.cpp.
g_ansi_bg_entries
Definition g_ansi_bg_entries[] constexpr
Initial value:
= {
    Definition("black",
               ANSI_ESC_START _TO_STR(ANSI_BG_COLOR_BLACK) ANSI_ESC_END),
    Definition("red", ANSI_ESC_START _TO_STR(ANSI_BG_COLOR_RED) ANSI_ESC_END),
    Definition("green",
               ANSI_ESC_START _TO_STR(ANSI_BG_COLOR_GREEN) ANSI_ESC_END),
    Definition("yellow",
               ANSI_ESC_START _TO_STR(ANSI_BG_COLOR_YELLOW) ANSI_ESC_END),
    Definition("blue", ANSI_ESC_START _TO_STR(ANSI_BG_COLOR_BLUE) ANSI_ESC_END),
    Definition("purple",
               ANSI_ESC_START _TO_STR(ANSI_BG_COLOR_PURPLE) ANSI_ESC_END),
    Definition("cyan", ANSI_ESC_START _TO_STR(ANSI_BG_COLOR_CYAN) ANSI_ESC_END),
    Definition("white",
               ANSI_ESC_START _TO_STR(ANSI_BG_COLOR_WHITE) ANSI_ESC_END),
}
Definition at line 208 of file FormatEntity.cpp.
g_ansi_entries
Definition g_ansi_entries[] constexpr
Initial value:
= {
    Entry::DefinitionWithChildren("fg", EntryType::Invalid, g_ansi_fg_entries),
    Entry::DefinitionWithChildren("bg", EntryType::Invalid, g_ansi_bg_entries),
    Definition("normal", ANSI_ESC_START _TO_STR(ANSI_CTRL_NORMAL) ANSI_ESC_END),
    Definition("bold", ANSI_ESC_START _TO_STR(ANSI_CTRL_BOLD) ANSI_ESC_END),
    Definition("faint", ANSI_ESC_START _TO_STR(ANSI_CTRL_FAINT) ANSI_ESC_END),
    Definition("italic", ANSI_ESC_START _TO_STR(ANSI_CTRL_ITALIC) ANSI_ESC_END),
    Definition("underline",
               ANSI_ESC_START _TO_STR(ANSI_CTRL_UNDERLINE) ANSI_ESC_END),
    Definition("slow-blink",
               ANSI_ESC_START _TO_STR(ANSI_CTRL_SLOW_BLINK) ANSI_ESC_END),
    Definition("fast-blink",
               ANSI_ESC_START _TO_STR(ANSI_CTRL_FAST_BLINK) ANSI_ESC_END),
    Definition("negative",
               ANSI_ESC_START _TO_STR(ANSI_CTRL_IMAGE_NEGATIVE) ANSI_ESC_END),
    Definition("conceal",
               ANSI_ESC_START _TO_STR(ANSI_CTRL_CONCEAL) ANSI_ESC_END),
    Definition("crossed-out",
               ANSI_ESC_START _TO_STR(ANSI_CTRL_CROSSED_OUT) ANSI_ESC_END),
}
Definition at line 224 of file FormatEntity.cpp.
g_ansi_fg_entries
Definition g_ansi_fg_entries[] constexpr
Initial value:
= {
    Definition("black",
               ANSI_ESC_START _TO_STR(ANSI_FG_COLOR_BLACK) ANSI_ESC_END),
    Definition("red", ANSI_ESC_START _TO_STR(ANSI_FG_COLOR_RED) ANSI_ESC_END),
    Definition("green",
               ANSI_ESC_START _TO_STR(ANSI_FG_COLOR_GREEN) ANSI_ESC_END),
    Definition("yellow",
               ANSI_ESC_START _TO_STR(ANSI_FG_COLOR_YELLOW) ANSI_ESC_END),
    Definition("blue", ANSI_ESC_START _TO_STR(ANSI_FG_COLOR_BLUE) ANSI_ESC_END),
    Definition("purple",
               ANSI_ESC_START _TO_STR(ANSI_FG_COLOR_PURPLE) ANSI_ESC_END),
    Definition("cyan", ANSI_ESC_START _TO_STR(ANSI_FG_COLOR_CYAN) ANSI_ESC_END),
    Definition("white",
               ANSI_ESC_START _TO_STR(ANSI_FG_COLOR_WHITE) ANSI_ESC_END),
}
Definition at line 192 of file FormatEntity.cpp.
g_file_child_entries
Definition g_file_child_entries[] constexpr
Initial value:
= {
    Definition("basename", EntryType::ParentNumber, FileKind::Basename),
    Definition("dirname", EntryType::ParentNumber, FileKind::Dirname),
    Definition("fullpath", EntryType::ParentNumber, FileKind::Fullpath)}
Definition at line 97 of file FormatEntity.cpp.
g_frame_child_entries
Definition g_frame_child_entries[] constexpr
Initial value:
= {
    Definition("index", EntryType::FrameIndex),
    Definition("pc", EntryType::FrameRegisterPC),
    Definition("fp", EntryType::FrameRegisterFP),
    Definition("sp", EntryType::FrameRegisterSP),
    Definition("flags", EntryType::FrameRegisterFlags),
    Definition("no-debug", EntryType::FrameNoDebug),
    Entry::DefinitionWithChildren("reg", EntryType::FrameRegisterByName,
                                  g_string_entry),
    Definition("is-artificial", EntryType::FrameIsArtificial),
    Definition("kind", EntryType::FrameKind),
    Definition("borrowed-info", EntryType::FrameBorrowedInfo),
}
Definition at line 102 of file FormatEntity.cpp.
g_function_child_entries
Definition g_function_child_entries[] constexpr
Initial value:
= {
    Definition("id", EntryType::FunctionID),
    Definition("name", EntryType::FunctionName),
    Definition("name-without-args", EntryType::FunctionNameNoArgs),
    Definition("name-with-args", EntryType::FunctionNameWithArgs),
    Definition("mangled-name", EntryType::FunctionMangledName),
    Definition("addr-offset", EntryType::FunctionAddrOffset),
    Definition("concrete-only-addr-offset-no-padding",
               EntryType::FunctionAddrOffsetConcrete),
    Definition("line-offset", EntryType::FunctionLineOffset),
    Definition("pc-offset", EntryType::FunctionPCOffset),
    Definition("initial-function", EntryType::FunctionInitial),
    Definition("changed", EntryType::FunctionChanged),
    Definition("is-optimized", EntryType::FunctionIsOptimized),
    Definition("is-inlined", EntryType::FunctionIsInlined),
    Definition("prefix", EntryType::FunctionPrefix),
    Definition("scope", EntryType::FunctionScope),
    Definition("basename", EntryType::FunctionBasename),
    Definition("name-qualifiers", EntryType::FunctionNameQualifiers),
    Definition("template-arguments", EntryType::FunctionTemplateArguments),
    Definition("formatted-arguments", EntryType::FunctionFormattedArguments),
    Definition("return-left", EntryType::FunctionReturnLeft),
    Definition("return-right", EntryType::FunctionReturnRight),
    Definition("qualifiers", EntryType::FunctionQualifiers),
    Definition("suffix", EntryType::FunctionSuffix),
}
Definition at line 116 of file FormatEntity.cpp.
g_line_child_entries
Definition g_line_child_entries[] constexpr
Initial value:
= {
    Entry::DefinitionWithChildren("file", EntryType::LineEntryFile,
                                  g_file_child_entries),
    Definition("number", EntryType::LineEntryLineNumber),
    Definition("column", EntryType::LineEntryColumn),
    Definition("start-addr", EntryType::LineEntryStartAddress),
    Definition("end-addr", EntryType::LineEntryEndAddress),
}
Definition at line 143 of file FormatEntity.cpp.
g_module_child_entries
Definition g_module_child_entries[] constexpr
Initial value:
= {Entry::DefinitionWithChildren(
    "file", EntryType::ModuleFile, g_file_child_entries)}
Definition at line 152 of file FormatEntity.cpp.
g_process_child_entries
Definition g_process_child_entries[] constexpr
Initial value:
= {
    Definition("id", EntryType::ProcessID),
    Definition("name", EntryType::ProcessFile, FileKind::Basename),
    Entry::DefinitionWithChildren("file", EntryType::ProcessFile,
                                  g_file_child_entries)}
Definition at line 155 of file FormatEntity.cpp.
g_progress_child_entries
Definition g_progress_child_entries[] constexpr
Initial value:
= {
    Definition("count", EntryType::ProgressCount),
    Definition("message", EntryType::ProgressMessage)}
Definition at line 185 of file FormatEntity.cpp.
g_root
Definition g_root constexpr
Initial value:
= Entry::DefinitionWithChildren(
    "<root>", EntryType::Root, g_top_level_entries)
Definition at line 288 of file FormatEntity.cpp.
Referenced by lldb_private::FormatEntity::AutoComplete(), and ParseInternal().
g_script_child_entries
Definition g_script_child_entries[] constexpr
Initial value:
= {
    Definition("frame", EntryType::ScriptFrame),
    Definition("process", EntryType::ScriptProcess),
    Definition("target", EntryType::ScriptTarget),
    Definition("thread", EntryType::ScriptThread),
    Definition("var", EntryType::ScriptVariable),
    Definition("svar", EntryType::ScriptVariableSynthetic),
    Definition("thread", EntryType::ScriptThread)}
Definition at line 245 of file FormatEntity.cpp.
g_string_entry
Definition g_string_entry[] constexpr
Initial value:
= {
    Definition("*", EntryType::ParentString)}
Definition at line 90 of file FormatEntity.cpp.
g_svar_child_entries
Definition g_svar_child_entries[] constexpr
Initial value:
= {
    Definition("*", EntryType::ParentString)}
Definition at line 161 of file FormatEntity.cpp.
g_target_child_entries
Definition g_target_child_entries[] constexpr
Initial value:
= {
    Definition("arch", EntryType::TargetArch),
    Entry::DefinitionWithChildren("file", EntryType::TargetFile,
                                  g_file_child_entries)}
Definition at line 180 of file FormatEntity.cpp.
g_thread_child_entries
Definition g_thread_child_entries[] constexpr
Initial value:
= {
    Definition("id", EntryType::ThreadID),
    Definition("protocol_id", EntryType::ThreadProtocolID),
    Definition("index", EntryType::ThreadIndexID),
    Entry::DefinitionWithChildren("info", EntryType::ThreadInfo,
                                  g_string_entry),
    Definition("queue", EntryType::ThreadQueue),
    Definition("name", EntryType::ThreadName),
    Definition("stop-reason", EntryType::ThreadStopReason),
    Definition("stop-reason-raw", EntryType::ThreadStopReasonRaw),
    Definition("return-value", EntryType::ThreadReturnValue),
    Definition("completed-expression", EntryType::ThreadCompletedExpression)}
Definition at line 167 of file FormatEntity.cpp.
g_top_level_entries
Definition g_top_level_entries[] constexpr
Definition at line 254 of file FormatEntity.cpp.
g_var_child_entries
Definition g_var_child_entries[] constexpr
Initial value:
= {
    Definition("*", EntryType::ParentString)}
Definition at line 164 of file FormatEntity.cpp.
LLVMFormatPattern
llvm::Regex LLVMFormatPattern {"x[-+]?\\d*|n|d", llvm::Regex::IgnoreCase} static
Options supported by format_provider<T> for integral arithmetic types.
See table in FormatProviders.h.
Definition at line 728 of file FormatEntity.cpp.
Referenced by DumpValueWithLLVMFormat(), and ParseInternal().