LLDB: GDBRemoteCommunicationServerCommon.cpp File Reference
GDBRemoteCommunicationServerCommon.cpp File Reference
#include "GDBRemoteCommunicationServerCommon.h"
#include <cerrno>
#include <chrono>
#include <cstring>
#include <optional>
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Host/Config.h"
#include "lldb/Host/File.h"
#include "lldb/Host/FileAction.h"
#include "lldb/Host/FileSystem.h"
#include "lldb/Host/Host.h"
#include "lldb/Host/HostInfo.h"
#include "lldb/Host/SafeMachO.h"
#include "lldb/Interpreter/OptionArgParser.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Target/Platform.h"
#include "lldb/Utility/Endian.h"
#include "lldb/Utility/GDBRemote.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/Utility/StructuredData.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/JSON.h"
#include "llvm/TargetParser/Triple.h"
#include "ProcessGDBRemoteLog.h"
#include "lldb/Utility/StringExtractorGDBRemote.h"
#include "Plugins/Process/gdb-remote/GDBRemoteErrno.def"
Macros
#define HANDLE_ERRNO(name, value)
Functions
static GDBErrno system_errno_to_gdb (int err)
template<typename T, typename U>
static void fill_clamp (T &dest, U src, typename T::value_type fallback)
Variables
static const uint32_t g_default_packet_timeout_sec = 0
Macro Definition Documentation
HANDLE_ERRNO
#define HANDLE_ERRNO (name, value)
Value:
  case name:                                                                   \
    return GDB_##name;
Function Documentation
fill_clamp()
template<typename T, typename U> void fill_clamp (T & dest, U src, typename T::value_type fallback) static
Definition at line 775 of file GDBRemoteCommunicationServerCommon.cpp.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_FStat().
system_errno_to_gdb()
GDBErrno system_errno_to_gdb (int err) static
Definition at line 502 of file GDBRemoteCommunicationServerCommon.cpp.
References lldb_private::process_gdb_remote::GDB_EUNKNOWN.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_Close(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_FStat(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_Open(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_pRead(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_pWrite(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_vFile_unlink().
Variable Documentation
g_default_packet_timeout_sec
const uint32_t g_default_packet_timeout_sec = 0 static
Definition at line 57 of file GDBRemoteCommunicationServerCommon.cpp.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qHostInfo().