LLDB: GDBRemoteCommunicationClient.cpp File Reference
GDBRemoteCommunicationClient.cpp File Reference
#include "GDBRemoteCommunicationClient.h"
#include <cmath>
#include <sys/stat.h>
#include <numeric>
#include <optional>
#include <sstream>
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Host/HostInfo.h"
#include "lldb/Host/SafeMachO.h"
#include "lldb/Host/XML.h"
#include "lldb/Symbol/Symbol.h"
#include "lldb/Target/MemoryRegionInfo.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/UnixSignals.h"
#include "lldb/Utility/Args.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/LLDBAssert.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/State.h"
#include "lldb/Utility/StreamString.h"
#include "ProcessGDBRemote.h"
#include "ProcessGDBRemoteLog.h"
#include "lldb/Host/Config.h"
#include "lldb/Utility/StringExtractorGDBRemote.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/JSON.h"
#include "Plugins/Process/gdb-remote/GDBRemoteErrno.def"
Macros
#define HANDLE_ERRNO(name, value)
Functions
static void ParseOSType (llvm::StringRef value, std::string &os_name, std::string &environment)
static void MakeSpeedTestPacket (StreamString &packet, uint32_t send_size, uint32_t recv_size)
duration< float > calculate_standard_deviation (const std::vector< duration< float > > &v)
static int gdb_errno_to_system (int err)
static uint64_t ParseHostIOPacketResponse (StringExtractorGDBRemote &response, uint64_t fail_result, Status &error)
static std::optional< ModuleSpec > ParseModuleSpec (StructuredData::Dictionary *dict)
Macro Definition Documentation
HANDLE_ERRNO
#define HANDLE_ERRNO (name, value)
Value:
  case GDB_##name:                                                             \
    return name;
Function Documentation
calculate_standard_deviation()
duration< float > calculate_standard_deviation (const std::vector< duration< float > > & v)
Definition at line 2472 of file GDBRemoteCommunicationClient.cpp.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::TestPacketSpeed().
gdb_errno_to_system()
int gdb_errno_to_system (int err) static
Definition at line 3076 of file GDBRemoteCommunicationClient.cpp.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::CreateSymlink(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetFilePermissions(), ParseHostIOPacketResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ReadFile(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::Unlink(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteFile().
MakeSpeedTestPacket()
void MakeSpeedTestPacket (StreamString & packet, uint32_t send_size, uint32_t recv_size) static
Definition at line 2454 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::StreamString::Clear(), lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::TestPacketSpeed().
ParseHostIOPacketResponse()
uint64_t ParseHostIOPacketResponse (StringExtractorGDBRemote & response, uint64_t fail_result, Status & error) static
Definition at line 3087 of file GDBRemoteCommunicationClient.cpp.
References lldb::eErrorTypeGeneric, lldb::eErrorTypePOSIX, error(), gdb_errno_to_system(), StringExtractor::GetChar(), StringExtractor::GetS32(), StringExtractor::SetFilePos(), and lldb_private::Status.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::CloseFile(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::OpenFile().
ParseModuleSpec()
std::optional< ModuleSpec > ParseModuleSpec (StructuredData::Dictionary * dict) static
Definition at line 3918 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::ModuleSpec::GetArchitecture(), lldb_private::ModuleSpec::GetFileSpec(), lldb_private::ArchSpec::GetTriple(), lldb_private::ModuleSpec::GetUUID(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsInteger(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsString(), integer, lldb_private::UUID::SetFromStringRef(), lldb_private::ModuleSpec::SetObjectOffset(), lldb_private::ModuleSpec::SetObjectSize(), and lldb_private::ArchSpec::SetTriple().
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetModulesInfo().
ParseOSType()
void ParseOSType (llvm::StringRef value, std::string & os_name, std::string & environment) static
Definition at line 1217 of file GDBRemoteCommunicationClient.cpp.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetCurrentProcessInfo(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetHostInfo().