LLDB: GDBRemoteCommunicationServerLLGS.cpp File Reference
GDBRemoteCommunicationServerLLGS.cpp File Reference
#include <cerrno>
#include "lldb/Host/Config.h"
#include <chrono>
#include <cstring>
#include <limits>
#include <optional>
#include <thread>
#include "GDBRemoteCommunicationServerLLGS.h"
#include "lldb/Host/ConnectionFileDescriptor.h"
#include "lldb/Host/Debug.h"
#include "lldb/Host/File.h"
#include "lldb/Host/FileAction.h"
#include "lldb/Host/FileSystem.h"
#include "lldb/Host/Host.h"
#include "lldb/Host/HostInfo.h"
#include "lldb/Host/PosixApi.h"
#include "lldb/Host/Socket.h"
#include "lldb/Host/common/NativeProcessProtocol.h"
#include "lldb/Host/common/NativeRegisterContext.h"
#include "lldb/Host/common/NativeThreadProtocol.h"
#include "lldb/Target/MemoryRegionInfo.h"
#include "lldb/Utility/Args.h"
#include "lldb/Utility/DataBuffer.h"
#include "lldb/Utility/Endian.h"
#include "lldb/Utility/GDBRemote.h"
#include "lldb/Utility/LLDBAssert.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/State.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/Utility/UnimplementedError.h"
#include "lldb/Utility/UriParser.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/JSON.h"
#include "llvm/Support/ScopedPrinter.h"
#include "llvm/TargetParser/Triple.h"
#include "ProcessGDBRemote.h"
#include "ProcessGDBRemoteLog.h"
#include "lldb/Utility/StringExtractorGDBRemote.h"
Functions
static void AppendHexValue (StreamString &response, const uint8_t *buf, uint32_t buf_size, bool swap)
static llvm::StringRef GetEncodingNameOrEmpty (const RegisterInfo &reg_info)
static llvm::StringRef GetFormatNameOrEmpty (const RegisterInfo &reg_info)
static llvm::StringRef GetKindGenericOrEmpty (const RegisterInfo &reg_info)
static void CollectRegNums (const uint32_t *reg_num, StreamString &response, bool usehex)
static void WriteRegisterValueInHexFixedWidth (StreamString &response, NativeRegisterContext &reg_ctx, const RegisterInfo &reg_info, const RegisterValue *reg_value_p, lldb::ByteOrder byte_order)
static std::optional< json::Object > GetRegistersAsJSON (NativeThreadProtocol &thread)
static const char * GetStopReasonString (StopReason stop_reason)
static llvm::Expected< json::Array > GetJSONThreadsInfo (NativeProcessProtocol &process, bool abridged)
static bool ResumeActionListStopsAllThreads (ResumeActionList &actions)
Function Documentation
AppendHexValue()
void AppendHexValue (StreamString & response, const uint8_t * buf, uint32_t buf_size, bool swap) static
Definition at line 514 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::Stream::PutHex8(), and swap().
Referenced by WriteRegisterValueInHexFixedWidth().
CollectRegNums()
void CollectRegNums (const uint32_t * reg_num, StreamString & response, bool usehex) static
Definition at line 665 of file GDBRemoteCommunicationServerLLGS.cpp.
References LLDB_INVALID_REGNUM, lldb_private::Stream::Printf(), and lldb_private::Stream::PutChar().
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::BuildTargetXml(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qRegisterInfo().
GetEncodingNameOrEmpty()
llvm::StringRef GetEncodingNameOrEmpty (const RegisterInfo & reg_info) static
Definition at line 526 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb::eEncodingIEEE754, lldb::eEncodingSint, lldb::eEncodingUint, lldb::eEncodingVector, and lldb_private::RegisterInfo::encoding.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::BuildTargetXml(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qRegisterInfo().
GetFormatNameOrEmpty()
llvm::StringRef GetFormatNameOrEmpty (const RegisterInfo & reg_info) static
Definition at line 541 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb::eFormatAddressInfo, lldb::eFormatBinary, lldb::eFormatBoolean, lldb::eFormatBytes, lldb::eFormatBytesWithASCII, lldb::eFormatChar, lldb::eFormatCharArray, lldb::eFormatCharPrintable, lldb::eFormatComplex, lldb::eFormatComplexInteger, lldb::eFormatCString, lldb::eFormatDecimal, lldb::eFormatDefault, lldb::eFormatEnum, lldb::eFormatFloat, lldb::eFormatFloat128, lldb::eFormatHex, lldb::eFormatHexFloat, lldb::eFormatHexUppercase, lldb::eFormatInstruction, lldb::eFormatOctal, lldb::eFormatOSType, lldb::eFormatPointer, lldb::eFormatUnicode16, lldb::eFormatUnicode32, lldb::eFormatUnicode8, lldb::eFormatUnsigned, lldb::eFormatVectorOfChar, lldb::eFormatVectorOfFloat16, lldb::eFormatVectorOfFloat32, lldb::eFormatVectorOfFloat64, lldb::eFormatVectorOfSInt16, lldb::eFormatVectorOfSInt32, lldb::eFormatVectorOfSInt64, lldb::eFormatVectorOfSInt8, lldb::eFormatVectorOfUInt128, lldb::eFormatVectorOfUInt16, lldb::eFormatVectorOfUInt32, lldb::eFormatVectorOfUInt64, lldb::eFormatVectorOfUInt8, lldb::eFormatVoid, and lldb_private::RegisterInfo::format.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::BuildTargetXml(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qRegisterInfo().
GetJSONThreadsInfo()
llvm::Expected< json::Array > GetJSONThreadsInfo (NativeProcessProtocol & process, bool abridged) static
Definition at line 791 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::ThreadStopInfo::data, lldb_private::ThreadStopInfo::data_count, lldb_private::ThreadStopInfo::details, lldb::eStopReasonException, lldb_private::ThreadStopInfo::exception, lldb_private::NativeProcessProtocol::GetID(), lldb_private::GetLog(), GetRegistersAsJSON(), GetStopReasonString(), LLDB_LOGF, lldb_private::Process, lldb_private::ThreadStopInfo::reason, lldb_private::ThreadStopInfo::signo, lldb_private::Thread, lldb_private::NativeProcessProtocol::Threads(), and lldb_private::ThreadStopInfo::type.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_jThreadsInfo(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread().
GetKindGenericOrEmpty()
llvm::StringRef GetKindGenericOrEmpty (const RegisterInfo & reg_info) static
Definition at line 630 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb::eRegisterKindGeneric, lldb_private::RegisterInfo::kinds, LLDB_REGNUM_GENERIC_ARG1, LLDB_REGNUM_GENERIC_ARG2, LLDB_REGNUM_GENERIC_ARG3, LLDB_REGNUM_GENERIC_ARG4, LLDB_REGNUM_GENERIC_ARG5, LLDB_REGNUM_GENERIC_ARG6, LLDB_REGNUM_GENERIC_ARG7, LLDB_REGNUM_GENERIC_ARG8, LLDB_REGNUM_GENERIC_FLAGS, LLDB_REGNUM_GENERIC_FP, LLDB_REGNUM_GENERIC_PC, LLDB_REGNUM_GENERIC_RA, LLDB_REGNUM_GENERIC_SP, and LLDB_REGNUM_GENERIC_TP.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::BuildTargetXml(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qRegisterInfo().
GetRegistersAsJSON()
std::optional< json::Object > GetRegistersAsJSON (NativeThreadProtocol & thread) static
Definition at line 703 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb::eByteOrderBig, error(), lldb_private::Full, lldb_private::NativeRegisterContext::GetExpeditedRegisters(), lldb_private::GetLog(), lldb_private::NativeRegisterContext::GetRegisterInfoAtIndex(), lldb_private::StreamString::GetString(), LLDB_LOGF, lldb_private::Minimal, lldb_private::RegisterInfo::name, lldb_private::NativeRegisterContext::ReadRegister(), lldb_private::Thread, lldb_private::RegisterInfo::value_regs, and WriteRegisterValueInHexFixedWidth().
Referenced by GetJSONThreadsInfo().
GetStopReasonString()
const char * GetStopReasonString (StopReason stop_reason) static
Definition at line 755 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb::eStopReasonBreakpoint, lldb::eStopReasonException, lldb::eStopReasonExec, lldb::eStopReasonFork, lldb::eStopReasonHistoryBoundary, lldb::eStopReasonInstrumentation, lldb::eStopReasonInterrupt, lldb::eStopReasonInvalid, lldb::eStopReasonNone, lldb::eStopReasonPlanComplete, lldb::eStopReasonProcessorTrace, lldb::eStopReasonSignal, lldb::eStopReasonThreadExiting, lldb::eStopReasonTrace, lldb::eStopReasonVFork, lldb::eStopReasonVForkDone, and lldb::eStopReasonWatchpoint.
Referenced by GetJSONThreadsInfo(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread().
ResumeActionListStopsAllThreads()
bool ResumeActionListStopsAllThreads (ResumeActionList & actions) static
Definition at line 1772 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb::eStateSuspended, lldb_private::ResumeActionList::GetActionForThread(), lldb_private::ResumeActionList::GetSize(), and LLDB_INVALID_THREAD_ID.
Referenced by lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_vCont().
WriteRegisterValueInHexFixedWidth()
void WriteRegisterValueInHexFixedWidth (StreamString & response, NativeRegisterContext & reg_ctx, const RegisterInfo & reg_info, const RegisterValue * reg_value_p, lldb::ByteOrder byte_order) static
Definition at line 677 of file GDBRemoteCommunicationServerLLGS.cpp.
References AppendHexValue(), lldb_private::RegisterInfo::byte_size, lldb::eByteOrderLittle, error(), lldb_private::RegisterValue::GetBytes(), lldb_private::RegisterValue::GetByteSize(), and lldb_private::NativeRegisterContext::ReadRegister().
Referenced by GetRegistersAsJSON(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread().