LLDB: GNUstepObjCRuntime.cpp File Reference
GNUstepObjCRuntime.cpp File Reference
#include "GNUstepObjCRuntime.h"
#include "Plugins/TypeSystem/Clang/TypeSystemClang.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Expression/UtilityFunction.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/ArchSpec.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/ValueObject/ValueObject.h"
Functions
static bool CanModuleBeGNUstepObjCLibrary (const ModuleSP &module_sp, const llvm::Triple &TT)
static bool ScanForGNUstepObjCLibraryCandidate (const ModuleList &modules, const llvm::Triple &TT)
Function Documentation
CanModuleBeGNUstepObjCLibrary()
bool CanModuleBeGNUstepObjCLibrary (const ModuleSP & module_sp, const llvm::Triple & TT) static
Definition at line 40 of file GNUstepObjCRuntime.cpp.
References lldb_private::FileSpec::GetFilename(), and lldb_private::ConstString::GetStringRef().
Referenced by ScanForGNUstepObjCLibraryCandidate().
ScanForGNUstepObjCLibraryCandidate()
bool ScanForGNUstepObjCLibraryCandidate (const ModuleList & modules, const llvm::Triple & TT) static
Definition at line 55 of file GNUstepObjCRuntime.cpp.
References CanModuleBeGNUstepObjCLibrary(), lldb_private::ModuleList::GetModuleAtIndex(), lldb_private::ModuleList::GetMutex(), and lldb_private::ModuleList::GetSize().
Referenced by lldb_private::GNUstepObjCRuntime::CreateInstance().