LLDB: HexagonDYLDRendezvous.cpp File Reference
HexagonDYLDRendezvous.cpp File Reference
#include "lldb/Core/Module.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Symbol/Symbol.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/Status.h"
#include "HexagonDYLDRendezvous.h"
Functions
static addr_t ResolveRendezvousAddress (Process *process)
Locates the address of the rendezvous structure.
Function Documentation
ResolveRendezvousAddress()
addr_t ResolveRendezvousAddress (Process * process) static
Locates the address of the rendezvous structure.
Returns the address on success and LLDB_INVALID_ADDRESS on failure.
Definition at line 25 of file HexagonDYLDRendezvous.cpp.
References error(), lldb_private::Process::GetImageInfoAddress(), LLDB_INVALID_ADDRESS, and lldb_private::Process::ReadPointerFromMemory().
Referenced by HexagonDYLDRendezvous::Resolve().