LLDB: HostNetBSD.cpp File Reference
HostNetBSD.cpp File Reference
#include <cstdio>
#include <dlfcn.h>
#include <execinfo.h>
#include <sys/proc.h>
#include <sys/sysctl.h>
#include <sys/types.h>
#include <climits>
#include <kvm.h>
#include <sys/exec.h>
#include <sys/ptrace.h>
#include "lldb/Host/FileSystem.h"
#include "lldb/Host/Host.h"
#include "lldb/Host/HostInfo.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/DataExtractor.h"
#include "lldb/Utility/Endian.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/NameMatches.h"
#include "lldb/Utility/ProcessInfo.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/StreamString.h"
#include "llvm/Object/ELF.h"
#include "llvm/TargetParser/Host.h"
Namespaces
namespace lldb_private
A class that represents a running process on the host machine.
Functions
static bool GetNetBSDProcessArgs (const ProcessInstanceInfoMatch *match_info_ptr, ProcessInstanceInfo &process_info)
static bool GetNetBSDProcessCPUType (ProcessInstanceInfo &process_info)
static bool GetNetBSDProcessUserAndGroup (ProcessInstanceInfo &process_info)
Function Documentation
GetNetBSDProcessArgs()
bool GetNetBSDProcessArgs (const ProcessInstanceInfoMatch * match_info_ptr, ProcessInstanceInfo & process_info) static
Definition at line 45 of file HostNetBSD.cpp.
References lldb_private::Args::AppendArgument(), lldb_private::ProcessInfo::GetArguments(), lldb_private::DataExtractor::GetCStr(), lldb_private::ConstString::GetCString(), lldb_private::ProcessInfo::GetExecutableFile(), lldb_private::FileSpec::GetFilename(), lldb_private::ProcessInfo::GetName(), lldb_private::ProcessInstanceInfoMatch::GetNameMatchType(), lldb_private::ProcessInfo::GetProcessID(), lldb_private::ProcessInstanceInfoMatch::GetProcessInfo(), lldb_private::endian::InlHostByteOrder(), lldb_private::NameMatches(), lldb_private::DataExtractor::PeekData(), lldb_private::ProcessInfo::ProcessIDIsValid(), lldb_private::ProcessInfo::SetArg0(), and lldb_private::FileSpec::SetFile().
GetNetBSDProcessCPUType()
bool GetNetBSDProcessCPUType (ProcessInstanceInfo & process_info) static
Definition at line 98 of file HostNetBSD.cpp.
References lldb_private::ArchSpec::Clear(), lldb_private::FileSystem::CreateDataBuffer(), lldb_private::ProcessInfo::GetArchitecture(), lldb_private::ProcessInfo::GetExecutableFile(), lldb_private::GetLog(), lldb_private::Host, lldb_private::FileSystem::Instance(), LLDB_LOG, and lldb_private::ProcessInfo::ProcessIDIsValid().
GetNetBSDProcessUserAndGroup()
bool GetNetBSDProcessUserAndGroup (ProcessInstanceInfo & process_info) static
Definition at line 130 of file HostNetBSD.cpp.
References error(), lldb_private::ProcessInfo::GetProcessID(), LLDB_INVALID_PROCESS_ID, lldb_private::ProcessInfo::ProcessIDIsValid(), lldb_private::ProcessInstanceInfo::SetEffectiveGroupID(), lldb_private::ProcessInstanceInfo::SetEffectiveUserID(), lldb_private::ProcessInfo::SetGroupID(), lldb_private::ProcessInstanceInfo::SetParentProcessID(), lldb_private::ProcessInfo::SetUserID(), and UINT32_MAX.