LLDB: InstrumentationRuntimeBoundsSafety.cpp File Reference
InstrumentationRuntimeBoundsSafety.cpp File Reference
#include "InstrumentationRuntimeBoundsSafety.h"
#include "Plugins/Process/Utility/HistoryThread.h"
#include "lldb/Breakpoint/StoppointCallbackContext.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Symbol/Block.h"
#include "lldb/Symbol/Symbol.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Symbol/Variable.h"
#include "lldb/Symbol/VariableList.h"
#include "lldb/Target/InstrumentationRuntimeStopInfo.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/SectionLoadList.h"
#include "lldb/Target/StopInfo.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/RegisterValue.h"
#include "lldb/Utility/RegularExpression.h"
#include "clang/CodeGen/ModuleBuilder.h"
#include <memory>
#include <type_traits>
Classes
class InstrumentationBoundsSafetyStopInfo
Macros
#define SOFT_TRAP_CATEGORY_PREFIX "Soft "
#define SOFT_TRAP_FALLBACK_CATEGORY SOFT_TRAP_CATEGORY_PREFIX "Bounds check failed"
Typedefs
using ComputedStopInfo
Functions
constexpr llvm::StringLiteral BoundsSafetySoftTrapMinimal ("__bounds_safety_soft_trap")
constexpr llvm::StringLiteral BoundsSafetySoftTrapStr ("__bounds_safety_soft_trap_s")
constexpr std::array< llvm::StringLiteral, 2 > getBoundsSafetySoftTrapRuntimeFuncs ()
template<typename T, typename... ArgTys>
T LogBeforeReturn (ArgTys &&...Args)
template<typename... ArgTys>
ComputedStopInfo LogFailedCSI (ArgTys &&...Args)
Macro Definition Documentation
SOFT_TRAP_CATEGORY_PREFIX
#define SOFT_TRAP_CATEGORY_PREFIX "Soft "
Definition at line 49 of file InstrumentationRuntimeBoundsSafety.cpp.
Referenced by InstrumentationBoundsSafetyStopInfo::ComputeStopReasonAndSuggestedStackFrameWithDebugInfo().
SOFT_TRAP_FALLBACK_CATEGORY
#define SOFT_TRAP_FALLBACK_CATEGORY SOFT_TRAP_CATEGORY_PREFIX "Bounds check failed"
Definition at line 50 of file InstrumentationRuntimeBoundsSafety.cpp.
Referenced by InstrumentationBoundsSafetyStopInfo::ComputeStopReasonAndSuggestedStackFrameWithoutDebugInfo(), and InstrumentationBoundsSafetyStopInfo::InstrumentationBoundsSafetyStopInfo().
Typedef Documentation
ComputedStopInfo
using ComputedStopInfo
Initial value:
    std::pair<std::optional<std::string>, std::optional<uint32_t>>
Definition at line 53 of file InstrumentationRuntimeBoundsSafety.cpp.
Function Documentation
BoundsSafetySoftTrapMinimal()
llvm::StringLiteral BoundsSafetySoftTrapMinimal ("__bounds_safety_soft_trap") constexpr
Referenced by InstrumentationBoundsSafetyStopInfo::ComputeStopReasonAndSuggestedStackFrameWithoutDebugInfo(), and getBoundsSafetySoftTrapRuntimeFuncs().
BoundsSafetySoftTrapStr()
llvm::StringLiteral BoundsSafetySoftTrapStr ("__bounds_safety_soft_trap_s") constexpr
Referenced by InstrumentationBoundsSafetyStopInfo::ComputeStopReasonAndSuggestedStackFrameWithoutDebugInfo(), and getBoundsSafetySoftTrapRuntimeFuncs().
getBoundsSafetySoftTrapRuntimeFuncs()
std::array< llvm::StringLiteral, 2 > getBoundsSafetySoftTrapRuntimeFuncs () constexpr
Definition at line 45 of file InstrumentationRuntimeBoundsSafety.cpp.
References BoundsSafetySoftTrapMinimal(), and BoundsSafetySoftTrapStr().
Referenced by lldb_private::InstrumentationRuntimeBoundsSafety::Activate(), and lldb_private::InstrumentationRuntimeBoundsSafety::CheckIfRuntimeIsValid().
LogBeforeReturn()
template<typename T, typename... ArgTys> T LogBeforeReturn (ArgTys &&... Args) nodiscard
Definition at line 134 of file InstrumentationRuntimeBoundsSafety.cpp.
References lldb_private::GetLog(), lldb_private::InstrumentationRuntime, and LLDB_LOG.
Referenced by lldb_private::InstrumentationRuntimeBoundsSafety::Activate(), LogFailedCSI(), and lldb_private::InstrumentationRuntimeBoundsSafety::NotifyBreakpointHit().
LogFailedCSI()
template<typename... ArgTys> ComputedStopInfo LogFailedCSI (ArgTys &&... Args) nodiscard
Definition at line 140 of file InstrumentationRuntimeBoundsSafety.cpp.
References LogBeforeReturn().
Referenced by InstrumentationBoundsSafetyStopInfo::ComputeStopReasonAndSuggestedStackFrame(), InstrumentationBoundsSafetyStopInfo::ComputeStopReasonAndSuggestedStackFrameWithDebugInfo(), and InstrumentationBoundsSafetyStopInfo::ComputeStopReasonAndSuggestedStackFrameWithoutDebugInfo().