LLDB: IntelPTMultiCoreTrace.cpp File Reference
IntelPTMultiCoreTrace.cpp File Reference
#include "IntelPTMultiCoreTrace.h"
#include "Plugins/Process/POSIX/ProcessPOSIXLog.h"
#include "Procfs.h"
#include <optional>
Functions
static bool IsTotalBufferLimitReached (ArrayRef< cpu_id_t > cores, const TraceIntelPTStartRequest &request)
static Error IncludePerfEventParanoidMessageInError (Error &&error)
Function Documentation
IncludePerfEventParanoidMessageInError()
Error IncludePerfEventParanoidMessageInError (Error && error) static
Definition at line 27 of file IntelPTMultiCoreTrace.cpp.
References createStringError(), error(), and lldb_private::toString().
Referenced by lldb_private::process_linux::IntelPTMultiCoreTrace::StartOnAllCores().
IsTotalBufferLimitReached()
bool IsTotalBufferLimitReached (ArrayRef< cpu_id_t > cores, const TraceIntelPTStartRequest & request) static
Definition at line 19 of file IntelPTMultiCoreTrace.cpp.
References lldb_private::TraceIntelPTStartRequest::ipt_trace_size, and lldb_private::TraceIntelPTStartRequest::process_buffer_size_limit.
Referenced by lldb_private::process_linux::IntelPTMultiCoreTrace::StartOnAllCores().