LLDB: IntelPTSingleBufferTrace.cpp File Reference
IntelPTSingleBufferTrace.cpp File Reference
#include "IntelPTSingleBufferTrace.h"
#include "Plugins/Process/POSIX/ProcessPOSIXLog.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/StreamString.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/TargetParser/Host.h"
#include <linux/perf_event.h>
#include <sstream>
#include <sys/syscall.h>
#include <unistd.h>
Enumerations
enum IntelPTConfigFileType { Hex = 0 , ZeroOne , Decimal , BitOffset }
Functions
static Expected< uint32_t > ReadIntelPTConfigFile (const char *file, IntelPTConfigFileType type)
static Error CheckPsbPeriod (size_t psb_period)
Variables
const char kOSEventIntelPTTypeFile []
const char kPSBPeriodCapFile []
const char kPSBPeriodValidValuesFile []
const char kPSBPeriodBitOffsetFile []
const char kTSCBitOffsetFile []
Enumeration Type Documentation
IntelPTConfigFileType
enum IntelPTConfigFileType
Enumerator
Hex
ZeroOne
Decimal
BitOffset
Definition at line 40 of file IntelPTSingleBufferTrace.cpp.
Function Documentation
CheckPsbPeriod()
Error CheckPsbPeriod (size_t psb_period) static
Definition at line 112 of file IntelPTSingleBufferTrace.cpp.
References createStringError(), error(), Hex, kPSBPeriodCapFile, kPSBPeriodValidValuesFile, ReadIntelPTConfigFile(), and ZeroOne.
ReadIntelPTConfigFile()
Expected< uint32_t > ReadIntelPTConfigFile (const char * file, IntelPTConfigFileType type) static
Definition at line 51 of file IntelPTSingleBufferTrace.cpp.
References BitOffset, createStringError(), Decimal, Hex, and ZeroOne.
Referenced by CheckPsbPeriod(), and lldb_private::process_linux::GetIntelPTOSEventType().
Variable Documentation
kOSEventIntelPTTypeFile
const char kOSEventIntelPTTypeFile[]
Initial value:
=
    "/sys/bus/event_source/devices/intel_pt/type"
Definition at line 25 of file IntelPTSingleBufferTrace.cpp.
Referenced by lldb_private::process_linux::GetIntelPTOSEventType().
kPSBPeriodBitOffsetFile
const char kPSBPeriodBitOffsetFile[]
Initial value:
=
    "/sys/bus/event_source/devices/intel_pt/format/psb_period"
Definition at line 34 of file IntelPTSingleBufferTrace.cpp.
kPSBPeriodCapFile
const char kPSBPeriodCapFile[]
Initial value:
=
    "/sys/bus/event_source/devices/intel_pt/caps/psb_cyc"
Definition at line 28 of file IntelPTSingleBufferTrace.cpp.
Referenced by CheckPsbPeriod().
kPSBPeriodValidValuesFile
const char kPSBPeriodValidValuesFile[]
Initial value:
=
    "/sys/bus/event_source/devices/intel_pt/caps/psb_periods"
Definition at line 31 of file IntelPTSingleBufferTrace.cpp.
Referenced by CheckPsbPeriod().
kTSCBitOffsetFile
const char kTSCBitOffsetFile[]
Initial value:
=
    "/sys/bus/event_source/devices/intel_pt/format/tsc"
Definition at line 37 of file IntelPTSingleBufferTrace.cpp.