LLDB: IRExecutionUnit.cpp File Reference
IRExecutionUnit.cpp File Reference
#include "llvm/ExecutionEngine/ExecutionEngine.h"
#include "llvm/ExecutionEngine/ObjectCache.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DiagnosticHandler.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/raw_ostream.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Disassembler.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/Section.h"
#include "lldb/Expression/Expression.h"
#include "lldb/Expression/IRExecutionUnit.h"
#include "lldb/Expression/ObjectFileJIT.h"
#include "lldb/Host/HostInfo.h"
#include "lldb/Symbol/CompileUnit.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Symbol/SymbolFile.h"
#include "lldb/Symbol/SymbolVendor.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/Language.h"
#include "lldb/Target/LanguageRuntime.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/DataExtractor.h"
#include "lldb/Utility/LLDBAssert.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/lldb-defines.h"
#include <optional>
Classes
class LoadAddressResolver
Functions
static llvm::Expected< lldb::addr_t > ResolveFunctionCallLabel (FunctionCallLabel &label, const lldb_private::SymbolContext &sc, bool &symbol_was_missing_weak)
Returns address of the function referred to by the special function call label label.
Function Documentation
ResolveFunctionCallLabel()
llvm::Expected< lldb::addr_t > ResolveFunctionCallLabel (FunctionCallLabel & label, const lldb_private::SymbolContext & sc, bool & symbol_was_missing_weak) static
Returns address of the function referred to by the special function call label label.
Definition at line 726 of file IRExecutionUnit.cpp.
References lldb_private::SymbolContextList::Append(), LLDB_INVALID_ADDRESS, lldb_private::FunctionCallLabel::module_id, LoadAddressResolver::Resolve(), and lldb_private::SymbolContext::target_sp.
Referenced by lldb_private::IRExecutionUnit::FindSymbol().