LLDB: IRInterpreter.cpp File Reference
IRInterpreter.cpp File Reference
#include "lldb/Expression/IRInterpreter.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Expression/DiagnosticManager.h"
#include "lldb/Expression/IRExecutionUnit.h"
#include "lldb/Expression/IRMemoryMap.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/DataExtractor.h"
#include "lldb/Utility/Endian.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/Scalar.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/ValueObject/ValueObject.h"
#include "lldb/Target/ABI.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Target/ThreadPlan.h"
#include "lldb/Target/ThreadPlanCallFunctionUsingABI.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/Support/raw_ostream.h"
#include <map>
Classes
class InterpreterStackFrame
Enumerations
enum class LLDBLog
Functions
static std::string PrintValue (const Value *value, bool truncate=false)
static std::string PrintType (const Type *type, bool truncate=false)
static bool CanIgnoreCall (const CallInst *call)
static bool CanResolveConstant (llvm::Constant *constant)
Variables
static const char * unsupported_opcode_error
static const char * unsupported_operand_error
static const char * interpreter_internal_error
static const char * interrupt_error
static const char * bad_value_error
static const char * memory_allocation_error
static const char * memory_write_error = "Interpreter couldn't write to memory"
static const char * memory_read_error = "Interpreter couldn't read from memory"
static const char * timeout_error
static const char * too_many_functions_error
Enumeration Type Documentation
LLDBLog
enum class lldb_private::LLDBLog : Log::MaskType strong
Definition at line 18 of file LLDBLog.h.
Function Documentation
CanIgnoreCall()
bool CanIgnoreCall (const CallInst * call) static
Definition at line 73 of file IRInterpreter.cpp.
Referenced by IRInterpreter::CanInterpret(), and IRInterpreter::Interpret().
CanResolveConstant()
bool CanResolveConstant (llvm::Constant * constant) static
Definition at line 481 of file IRInterpreter.cpp.
References CanResolveConstant().
Referenced by IRInterpreter::CanInterpret(), and CanResolveConstant().
PrintType()
std::string PrintType (const Type * type, bool truncate = false) static
Definition at line 64 of file IRInterpreter.cpp.
Referenced by IRInterpreter::CanInterpret(), and IRForTarget::MaybeHandleVariable().
PrintValue()
std::string PrintValue (const Value * value, bool truncate = false) static
Definition at line 48 of file IRInterpreter.cpp.
Referenced by IRInterpreter::CanInterpret(), IRForTarget::CreateResultVariable(), IRForTarget::HandleSymbol(), ObjcObjectChecker::InspectInstruction(), IRInterpreter::Interpret(), InterpreterStackFrame::MakeArgument(), IRForTarget::MaybeHandleCallArguments(), IRForTarget::MaybeHandleVariable(), IRForTarget::ReplaceVariables(), IRForTarget::RewritePersistentAlloc(), InterpreterStackFrame::SummarizeValue(), and IRForTarget::UnfoldConstant().
Variable Documentation
bad_value_error
const char* bad_value_error static
Initial value:
=
    "Interpreter couldn't resolve a value during execution"
Definition at line 470 of file IRInterpreter.cpp.
Referenced by IRInterpreter::Interpret().
interpreter_internal_error
const char* interpreter_internal_error static
Initial value:
=
    "Interpreter encountered an internal error"
Definition at line 466 of file IRInterpreter.cpp.
Referenced by IRInterpreter::CanInterpret(), and IRInterpreter::Interpret().
interrupt_error
const char* interrupt_error static
Initial value:
=
    "Interrupted while interpreting expression"
Definition at line 468 of file IRInterpreter.cpp.
Referenced by IRInterpreter::Interpret().
memory_allocation_error
const char* memory_allocation_error static
Initial value:
=
    "Interpreter couldn't allocate memory"
Definition at line 472 of file IRInterpreter.cpp.
Referenced by IRInterpreter::Interpret().
memory_read_error
const char* memory_read_error = "Interpreter couldn't read from memory" static
Definition at line 475 of file IRInterpreter.cpp.
Referenced by IRInterpreter::Interpret(), and ObjectFileMachO::SaveCore().
memory_write_error
const char* memory_write_error = "Interpreter couldn't write to memory" static
Definition at line 474 of file IRInterpreter.cpp.
Referenced by IRInterpreter::Interpret().
timeout_error
const char* timeout_error static
Initial value:
=
    "Reached timeout while interpreting expression"
Definition at line 476 of file IRInterpreter.cpp.
Referenced by IRInterpreter::Interpret().
too_many_functions_error
const char* too_many_functions_error static
Initial value:
=
    "Interpreter doesn't handle modules with multiple function bodies."
Definition at line 478 of file IRInterpreter.cpp.
Referenced by IRInterpreter::CanInterpret().
unsupported_opcode_error
const char* unsupported_opcode_error static
Initial value:
=
    "Interpreter doesn't handle one of the expression's opcodes"
Definition at line 462 of file IRInterpreter.cpp.
Referenced by IRInterpreter::CanInterpret(), and IRInterpreter::Interpret().
unsupported_operand_error
const char* unsupported_operand_error static
Initial value:
=
    "Interpreter doesn't handle one of the expression's operands"
Definition at line 464 of file IRInterpreter.cpp.
Referenced by IRInterpreter::CanInterpret().