LLDB: JITLoaderGDB.cpp File Reference
JITLoaderGDB.cpp File Reference
#include "JITLoaderGDB.h"
#include "Plugins/ObjectFile/Mach-O/ObjectFileMachO.h"
#include "lldb/Breakpoint/Breakpoint.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Section.h"
#include "lldb/Interpreter/OptionValueProperties.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Symbol/Symbol.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Symbol/SymbolVendor.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/SectionLoadList.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/LLDBAssert.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/StreamString.h"
#include "llvm/Support/MathExtras.h"
#include <memory>
#include "JITLoaderGDBProperties.inc"
#include "JITLoaderGDBPropertiesEnum.inc"
Macros
#define LLDB_PROPERTIES_jitloadergdb
#define LLDB_PROPERTIES_jitloadergdb
Functions
static PluginProperties & GetGlobalPluginProperties ()
template<typename ptr_t>
static bool ReadJITEntry (const addr_t from_addr, Process *process, jit_code_entry< ptr_t > *entry)
static void updateSectionLoadAddress (const SectionList &section_list, Target &target, uint64_t symbolfile_addr, uint64_t symbolfile_size, uint64_t &vmaddrheuristic, uint64_t &min_addr, uint64_t &max_addr)
Macro Definition Documentation
LLDB_PROPERTIES_jitloadergdb [1/2]
#define LLDB_PROPERTIES_jitloadergdb
Definition at line 81 of file JITLoaderGDB.cpp.
LLDB_PROPERTIES_jitloadergdb [2/2]
#define LLDB_PROPERTIES_jitloadergdb
Definition at line 81 of file JITLoaderGDB.cpp.
Function Documentation
GetGlobalPluginProperties()
PluginProperties & GetGlobalPluginProperties () static
Definition at line 110 of file JITLoaderGDB.cpp.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::BuildDynamicRegisterInfo(), JITLoaderGDB::CreateInstance(), JITLoaderGDB::DebuggerInitialize(), lldb_private::CPlusPlusLanguage::DebuggerInitialize(), lldb_private::plugin::dwarf::SymbolFileDWARF::DebuggerInitialize(), lldb_private::process_gdb_remote::ProcessGDBRemote::DebuggerInitialize(), lldb_private::SymbolLocatorDebuginfod::DebuggerInitialize(), ObjectFilePECOFF::DebuggerInitialize(), ProcessKDP::DebuggerInitialize(), SymbolFilePDB::DebuggerInitialize(), GetFileForModule(), lldb_private::CPlusPlusLanguage::GetFunctionNameFormat(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetLoadedModuleList(), ObjectFilePECOFF::GetModuleSpecifications(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetPacketTimeout(), lldb_private::plugin::dwarf::SymbolFileDWARF::InitializeObject(), lldb_private::process_gdb_remote::ProcessGDBRemote::ProcessGDBRemote(), ProcessKDP::ProcessKDP(), and SymbolFilePDB::UseNativePDB().
ReadJITEntry()
template<typename ptr_t> bool ReadJITEntry (const addr_t from_addr, Process * process, jit_code_entry< ptr_t > * entry) static
Definition at line 116 of file JITLoaderGDB.cpp.
References error(), lldb_private::DataExtractor::GetAddress(), lldb_private::Target::GetArchitecture(), lldb_private::Process::GetByteOrder(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::DataBufferHeap::GetByteSize(), lldb_private::ArchSpec::GetCore(), lldb_private::Process::GetTarget(), lldb_private::DataExtractor::GetU64(), lldb_private::ArchSpec::kCore_x86_32_first, lldb_private::ArchSpec::kCore_x86_32_last, lldbassert, and lldb_private::Process::ReadMemory().
Referenced by JITLoaderGDB::ReadJITDescriptorImpl().
updateSectionLoadAddress()
void updateSectionLoadAddress (const SectionList & section_list, Target & target, uint64_t symbolfile_addr, uint64_t symbolfile_size, uint64_t & vmaddrheuristic, uint64_t & min_addr, uint64_t & max_addr) static
Definition at line 226 of file JITLoaderGDB.cpp.
References lldb_private::SectionList::GetSectionAtIndex(), lldb_private::SectionList::GetSize(), lldb_private::Target::SetSectionLoadAddress(), and updateSectionLoadAddress().
Referenced by JITLoaderGDB::ReadJITDescriptorImpl(), and updateSectionLoadAddress().