LLDB: LanguageCategory.cpp File Reference
LanguageCategory.cpp File Reference
#include "lldb/DataFormatters/LanguageCategory.h"
#include "lldb/DataFormatters/FormatManager.h"
#include "lldb/DataFormatters/TypeCategory.h"
#include "lldb/DataFormatters/TypeFormat.h"
#include "lldb/DataFormatters/TypeSummary.h"
#include "lldb/DataFormatters/TypeSynthetic.h"
#include "lldb/Target/Language.h"
Namespaces
namespace lldb_private
A class that represents a running process on the host machine.
Functions
template<>
auto & lldb_private::LanguageCategory::GetHardcodedFinder< lldb::TypeFormatImplSP > ()
template<>
auto & lldb_private::LanguageCategory::GetHardcodedFinder< lldb::TypeSummaryImplSP > ()
template<>
auto & lldb_private::LanguageCategory::GetHardcodedFinder< lldb::SyntheticChildrenSP > ()
template bool lldb_private::LanguageCategory::Get< lldb::TypeFormatImplSP > (FormattersMatchData &, lldb::TypeFormatImplSP &)
Explicit instantiations for the three types.
template bool lldb_private::LanguageCategory::Get< lldb::TypeSummaryImplSP > (FormattersMatchData &, lldb::TypeSummaryImplSP &)
template bool lldb_private::LanguageCategory::Get< lldb::SyntheticChildrenSP > (FormattersMatchData &, lldb::SyntheticChildrenSP &)
template bool LanguageCategory::GetHardcoded< lldb::TypeFormatImplSP > (FormatManager &, FormattersMatchData &, lldb::TypeFormatImplSP &)
Explicit instantiations for the three types.
template bool LanguageCategory::GetHardcoded< lldb::TypeSummaryImplSP > (FormatManager &, FormattersMatchData &, lldb::TypeSummaryImplSP &)
template bool LanguageCategory::GetHardcoded< lldb::SyntheticChildrenSP > (FormatManager &, FormattersMatchData &, lldb::SyntheticChildrenSP &)
Function Documentation
LanguageCategory::GetHardcoded< lldb::SyntheticChildrenSP >()
template bool LanguageCategory::GetHardcoded< lldb::SyntheticChildrenSP > (FormatManager & , FormattersMatchData & , lldb::SyntheticChildrenSP &)
References lldb_private::LanguageCategory::GetHardcoded().
LanguageCategory::GetHardcoded< lldb::TypeFormatImplSP >()
template bool LanguageCategory::GetHardcoded< lldb::TypeFormatImplSP > (FormatManager & , FormattersMatchData & , lldb::TypeFormatImplSP &)
Explicit instantiations for the three types.
References lldb_private::LanguageCategory::GetHardcoded().
LanguageCategory::GetHardcoded< lldb::TypeSummaryImplSP >()
template bool LanguageCategory::GetHardcoded< lldb::TypeSummaryImplSP > (FormatManager & , FormattersMatchData & , lldb::TypeSummaryImplSP &)
References lldb_private::LanguageCategory::GetHardcoded().