LLDB: Language.cpp File Reference
Language.cpp File Reference
#include <functional>
#include <map>
#include <mutex>
#include "lldb/Target/Language.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Interpreter/OptionValueProperties.h"
#include "lldb/Symbol/SymbolFile.h"
#include "lldb/Symbol/TypeList.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/Stream.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/Support/Threading.h"
#include "TargetProperties.inc"
#include "TargetPropertiesEnum.inc"
Classes
struct language_name_pair
Macros
#define LLDB_PROPERTIES_language
#define LLDB_PROPERTIES_language
Typedefs
typedef std::unique_ptr< Language > LanguageUP
typedef std::map< lldb::LanguageType, LanguageUP > LanguagesMap
Enumerations
enum
Functions
static LanguagesMap & GetLanguagesMap ()
static std::mutex & GetLanguagesMutex ()
static std::optional< llvm::dwarf::SourceLanguage > ToDwarfSourceLanguage (lldb::LanguageType language_type)
Variables
struct language_name_pair language_names []
static uint32_t num_languages
Macro Definition Documentation
LLDB_PROPERTIES_language [1/2]
#define LLDB_PROPERTIES_language
Definition at line 32 of file Language.cpp.
LLDB_PROPERTIES_language [2/2]
#define LLDB_PROPERTIES_language
Definition at line 32 of file Language.cpp.
Typedef Documentation
LanguagesMap
typedef std::map<lldb::LanguageType, LanguageUP> LanguagesMap
Definition at line 30 of file Language.cpp.
LanguageUP
typedef std::unique_ptr<Language> LanguageUP
Definition at line 29 of file Language.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Definition at line 35 of file Language.cpp.
Function Documentation
GetLanguagesMap()
LanguagesMap & GetLanguagesMap () static
Definition at line 61 of file Language.cpp.
Referenced by lldb_private::Language::FindPlugin(), and lldb_private::Language::ForEach().
GetLanguagesMutex()
std::mutex & GetLanguagesMutex () static
Definition at line 72 of file Language.cpp.
Referenced by lldb_private::Language::FindPlugin(), and lldb_private::Language::ForEach().
ToDwarfSourceLanguage()
std::optional< llvm::dwarf::SourceLanguage > ToDwarfSourceLanguage (lldb::LanguageType language_type) static
Definition at line 593 of file Language.cpp.
References lldb::eLanguageTypeLastStandardLanguage, and lldb::eLanguageTypeMipsAssembler.
Referenced by lldb_private::SourceLanguage::SourceLanguage().
Variable Documentation
language_names
struct language_name_pair language_names[]
Definition at line 232 of file Language.cpp.
Referenced by lldb_private::Language::ForAllLanguages(), lldb_private::Language::GetLanguageTypeFromString(), lldb_private::Language::GetNameForLanguageType(), lldb_private::Language::PrintAllLanguages(), and lldb_private::Language::PrintSupportedLanguagesForExpressions().
num_languages
uint32_t num_languages static
Initial value:
=
    sizeof(language_names) / sizeof(struct language_name_pair)
Definition at line 297 of file Language.cpp.
Referenced by lldb_private::Language::ForAllLanguages(), lldb_private::Language::GetNameForLanguageType(), lldb_private::Language::PrintAllLanguages(), and lldb_private::Language::PrintSupportedLanguagesForExpressions().