LLDB: LibCxx.cpp File Reference
LibCxx.cpp File Reference
#include "LibCxx.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/FormatEntity.h"
#include "lldb/DataFormatters/FormattersHelpers.h"
#include "lldb/DataFormatters/StringPrinter.h"
#include "lldb/DataFormatters/TypeSummary.h"
#include "lldb/DataFormatters/VectorIterator.h"
#include "lldb/Target/SectionLoadList.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/Endian.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/Stream.h"
#include "lldb/ValueObject/ValueObject.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
#include "Plugins/Language/CPlusPlus/CxxStringTypes.h"
#include "Plugins/Language/CPlusPlus/Generic.h"
#include "Plugins/LanguageRuntime/CPlusPlus/CPPLanguageRuntime.h"
#include "Plugins/TypeSystem/Clang/TypeSystemClang.h"
#include "lldb/lldb-enumerations.h"
#include "lldb/lldb-forward.h"
#include <optional>
#include <tuple>
Functions
static void consumeInlineNamespace (llvm::StringRef &name)
static std::optional< int64_t > LibcxxExtractOrderingValue (ValueObject &valobj)
static ValueObjectSP ExtractLibCxxStringData (ValueObject &valobj)
static std::optional< std::pair< uint64_t, ValueObjectSP > > ExtractLibcxxStringInfo (ValueObject &valobj)
Determine the size in bytes of valobj (a libc++ std::string object) and extract its data payload.
template<StringPrinter::StringElementType element_type>
static bool LibcxxStringSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options, std::string prefix_token)
template<StringPrinter::StringElementType element_type>
static bool formatStringImpl (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options, std::string prefix_token)
static std::tuple< bool, ValueObjectSP, size_t > LibcxxExtractStringViewData (ValueObject &valobj)
template<StringPrinter::StringElementType element_type>
static bool formatStringViewImpl (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options, std::string prefix_token)
static bool LibcxxChronoTimePointSecondsSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options, const char *fmt)
static bool LibcxxChronoTimepointDaysSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options, const char *fmt)
Function Documentation
consumeInlineNamespace()
void consumeInlineNamespace (llvm::StringRef & name) static
Definition at line 40 of file LibCxx.cpp.
Referenced by lldb_private::formatters::isStdTemplate().
ExtractLibCxxStringData()
ValueObjectSP ExtractLibCxxStringData (ValueObject & valobj) static
Definition at line 531 of file LibCxx.cpp.
References lldb_private::formatters::GetFirstValueOfLibCXXCompressedPair(), and lldb_private::formatters::GetValueOrOldCompressedPair().
Referenced by ExtractLibcxxStringInfo().
ExtractLibcxxStringInfo()
std::optional< std::pair< uint64_t, ValueObjectSP > > ExtractLibcxxStringInfo (ValueObject & valobj) static
Determine the size in bytes of valobj (a libc++ std::string object) and extract its data payload.
Return the size + payload pair.
Definition at line 547 of file LibCxx.cpp.
References lldb_private::DataFormatters, ExtractLibCxxStringData(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::GetLog(), l, LLDB_INVALID_OFFSET, and LLDB_LOG_ERROR.
Referenced by LibcxxStringSummaryProvider(), and lldb_private::formatters::LibcxxWStringSummaryProvider().
formatStringImpl()
template<StringPrinter::StringElementType element_type> bool formatStringImpl (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options, std::string prefix_token) static
Definition at line 675 of file LibCxx.cpp.
References lldb_private::StreamString::GetData(), and LibcxxStringSummaryProvider().
Referenced by lldb_private::formatters::LibcxxStringSummaryProviderASCII(), lldb_private::formatters::LibcxxStringSummaryProviderUTF16(), and lldb_private::formatters::LibcxxStringSummaryProviderUTF32().
formatStringViewImpl()
template<StringPrinter::StringElementType element_type> bool formatStringViewImpl (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options, std::string prefix_token) static
Definition at line 730 of file LibCxx.cpp.
References LibcxxExtractStringViewData(), and lldb_private::formatters::StringBufferSummaryProvider().
Referenced by lldb_private::formatters::LibcxxStringViewSummaryProviderASCII(), lldb_private::formatters::LibcxxStringViewSummaryProviderUTF16(), lldb_private::formatters::LibcxxStringViewSummaryProviderUTF32(), lldb_private::formatters::LibStdcppStringViewSummaryProvider(), and lldb_private::formatters::LibStdcppWStringViewSummaryProvider().
LibcxxChronoTimepointDaysSummaryProvider()
bool LibcxxChronoTimepointDaysSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options, const char * fmt) static
Definition at line 858 of file LibCxx.cpp.
References lldb_private::ValueObject::GetChildMemberWithName(), and lldb_private::Stream::Printf().
Referenced by lldb_private::formatters::LibcxxChronoLocalDaysSummaryProvider(), and lldb_private::formatters::LibcxxChronoSysDaysSummaryProvider().
LibcxxChronoTimePointSecondsSummaryProvider()
bool LibcxxChronoTimePointSecondsSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options, const char * fmt) static
Definition at line 802 of file LibCxx.cpp.
References lldb_private::ValueObject::GetChildMemberWithName(), and lldb_private::Stream::Printf().
Referenced by lldb_private::formatters::LibcxxChronoLocalSecondsSummaryProvider(), and lldb_private::formatters::LibcxxChronoSysSecondsSummaryProvider().
LibcxxExtractOrderingValue()
std::optional< int64_t > LibcxxExtractOrderingValue (ValueObject & valobj) static
Definition at line 250 of file LibCxx.cpp.
References lldb_private::ValueObject::GetChildMemberWithName().
Referenced by lldb_private::formatters::LibcxxPartialOrderingSummaryProvider(), lldb_private::formatters::LibcxxStrongOrderingSummaryProvider(), and lldb_private::formatters::LibcxxWeakOrderingSummaryProvider().
LibcxxExtractStringViewData()
std::tuple< bool, ValueObjectSP, size_t > LibcxxExtractStringViewData (ValueObject & valobj) static
Definition at line 710 of file LibCxx.cpp.
References lldb_private::formatters::GetChildMemberWithName().
Referenced by formatStringViewImpl(), and lldb_private::formatters::LibcxxWStringViewSummaryProvider().
LibcxxStringSummaryProvider()
template<StringPrinter::StringElementType element_type> bool LibcxxStringSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options, std::string prefix_token) static
Definition at line 661 of file LibCxx.cpp.
References ExtractLibcxxStringInfo(), and lldb_private::formatters::StringBufferSummaryProvider().
Referenced by formatStringImpl().