LLDB: LibCxxUnorderedMap.cpp File Reference
LibCxxUnorderedMap.cpp File Reference
#include "LibCxx.h"
#include "Plugins/TypeSystem/Clang/TypeSystemClang.h"
#include "lldb/DataFormatters/FormattersHelpers.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/Endian.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/Stream.h"
#include "lldb/ValueObject/ValueObject.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Error.h"
Classes
class lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd
class lldb_private::formatters::LibCxxUnorderedMapIteratorSyntheticFrontEnd
Namespaces
namespace lldb_private
A class that represents a running process on the host machine.
namespace lldb_private::formatters
Functions
static bool isUnorderedMap (ConstString type_name)
static ValueObjectSP GetTreePointer (ValueObject &table)
Function Documentation
GetTreePointer()
ValueObjectSP GetTreePointer (ValueObject & table) static
Definition at line 239 of file LibCxxUnorderedMap.cpp.
References lldb_private::formatters::GetFirstValueOfLibCXXCompressedPair(), and lldb_private::formatters::GetValueOrOldCompressedPair().
Referenced by lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::Update().
isUnorderedMap()
bool isUnorderedMap (ConstString type_name) static
Definition at line 95 of file LibCxxUnorderedMap.cpp.
References lldb_private::formatters::isStdTemplate().
Referenced by lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::GetElementType().