LLDB: LibStdcpp.cpp File Reference
LibStdcpp.cpp File Reference
#include "LibStdcpp.h"
#include "LibCxx.h"
#include "Plugins/Language/CPlusPlus/CxxStringTypes.h"
#include "Plugins/Language/CPlusPlus/Generic.h"
#include "Plugins/TypeSystem/Clang/TypeSystemClang.h"
#include "lldb/DataFormatters/FormattersHelpers.h"
#include "lldb/DataFormatters/StringPrinter.h"
#include "lldb/DataFormatters/VectorIterator.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/Endian.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/Stream.h"
#include "lldb/ValueObject/ValueObject.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
#include <optional>
Functions
template<StringPrinter::StringElementType element_type>
static bool formatStringViewImpl (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options, std::string prefix_token)
template<StringElementType element_type>
static constexpr const char * getPrefixToken ()
template bool lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::ASCII > (ValueObject &, Stream &, const TypeSummaryOptions &)
template bool lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::UTF8 > (ValueObject &, Stream &, const TypeSummaryOptions &)
template bool lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::UTF16 > (ValueObject &, Stream &, const TypeSummaryOptions &)
template bool lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::UTF32 > (ValueObject &, Stream &, const TypeSummaryOptions &)
static uint64_t LibStdcppVariantNposValue (size_t index_byte_size)
static std::optional< int64_t > LibStdcppExtractOrderingValue (ValueObject &valobj)
Function Documentation
formatStringViewImpl()
template<StringPrinter::StringElementType element_type> bool formatStringViewImpl (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options, std::string prefix_token) static
Definition at line 252 of file LibStdcpp.cpp.
References lldb_private::ValueObject::GetChildMemberWithName(), lldb_private::StreamString::GetData(), and lldb_private::formatters::StringBufferSummaryProvider().
getPrefixToken()
template<StringElementType element_type> constexpr const char * getPrefixToken () static constexpr
Definition at line 299 of file LibStdcpp.cpp.
Referenced by lldb_private::formatters::LibStdcppStringViewSummaryProvider().
LibStdcppExtractOrderingValue()
std::optional< int64_t > LibStdcppExtractOrderingValue (ValueObject & valobj) static
Definition at line 499 of file LibStdcpp.cpp.
References lldb_private::ValueObject::GetChildMemberWithName().
Referenced by lldb_private::formatters::LibStdcppPartialOrderingSummaryProvider(), lldb_private::formatters::LibStdcppStrongOrderingSummaryProvider(), and lldb_private::formatters::LibStdcppWeakOrderingSummaryProvider().
LibStdcppVariantNposValue()
uint64_t LibStdcppVariantNposValue (size_t index_byte_size) static
Definition at line 452 of file LibStdcpp.cpp.
Referenced by lldb_private::formatters::LibStdcppVariantSummaryProvider().
lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::ASCII >()
template bool lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::ASCII > (ValueObject & , Stream & , const TypeSummaryOptions &)
References lldb_private::formatters::LibStdcppStringViewSummaryProvider().
Referenced by LoadCommonStlFormatters().
lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::UTF16 >()
template bool lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::UTF16 > (ValueObject & , Stream & , const TypeSummaryOptions &)
References lldb_private::formatters::LibStdcppStringViewSummaryProvider().
Referenced by LoadCommonStlFormatters().
lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::UTF32 >()
template bool lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::UTF32 > (ValueObject & , Stream & , const TypeSummaryOptions &)
References lldb_private::formatters::LibStdcppStringViewSummaryProvider().
Referenced by LoadCommonStlFormatters().
lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::UTF8 >()
template bool lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::UTF8 > (ValueObject & , Stream & , const TypeSummaryOptions &)
References lldb_private::formatters::LibStdcppStringViewSummaryProvider().
Referenced by LoadCommonStlFormatters().