LLDB: Host.cpp File Reference
Host.cpp File Reference
#include <cerrno>
#include <cstdio>
#include <cstring>
#include <dirent.h>
#include <fcntl.h>
#include <optional>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/utsname.h>
#include <unistd.h>
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Object/ELF.h"
#include "llvm/Support/ScopedPrinter.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/ProcessInfo.h"
#include "lldb/Utility/Status.h"
#include "lldb/Host/FileSystem.h"
#include "lldb/Host/Host.h"
#include "lldb/Host/HostInfo.h"
#include "lldb/Host/linux/Host.h"
#include "lldb/Host/posix/Support.h"
#include "lldb/Utility/DataExtractor.h"
Namespaces
namespace lldb_private
A class that represents a running process on the host machine.
Functions
static bool GetStatusInfo (::pid_t Pid, ProcessInstanceInfo &ProcessInfo, ProcessState &State, ::pid_t &TracerPid, ::pid_t &Tgid)
static bool IsDirNumeric (const char *dname)
static ArchSpec GetELFProcessCPUType (llvm::StringRef exe_path)
static void GetProcessArgs (::pid_t pid, ProcessInstanceInfo &process_info)
static void GetExePathAndArch (::pid_t pid, ProcessInstanceInfo &process_info)
static void GetProcessEnviron (::pid_t pid, ProcessInstanceInfo &process_info)
static bool GetProcessAndStatInfo (::pid_t pid, ProcessInstanceInfo &process_info, ProcessState &State, ::pid_t &tracerpid)
Function Documentation
GetELFProcessCPUType()
ArchSpec GetELFProcessCPUType (llvm::StringRef exe_path) static
Definition at line 234 of file linux/Host.cpp.
References lldb_private::FileSystem::CreateDataBuffer(), lldb_private::GetLog(), lldb_private::Host, lldb_private::FileSystem::Instance(), and LLDB_LOG.
Referenced by GetExePathAndArch().
GetExePathAndArch()
void GetExePathAndArch (::pid_t pid, ProcessInstanceInfo & process_info) static
Definition at line 274 of file linux/Host.cpp.
References lldb::eErrorTypePOSIX, GetELFProcessCPUType(), lldb_private::ProcessInfo::GetExecutableFile(), lldb_private::GetLog(), LLDB_LOG, PATH_MAX, lldb_private::Process, lldb_private::ProcessInfo::SetArchitecture(), lldb_private::FileSpec::SetFile(), and lldb_private::Status.
Referenced by GetProcessAndStatInfo().
GetProcessAndStatInfo()
bool GetProcessAndStatInfo (::pid_t pid, ProcessInstanceInfo & process_info, ProcessState & State, ::pid_t & tracerpid) static
Definition at line 316 of file linux/Host.cpp.
References lldb_private::ProcessInstanceInfo::Clear(), GetExePathAndArch(), GetProcessArgs(), GetProcessEnviron(), GetStatusInfo(), and lldb_private::ProcessInfo::SetProcessID().
GetProcessArgs()
void GetProcessArgs (::pid_t pid, ProcessInstanceInfo & process_info) static
Definition at line 258 of file linux/Host.cpp.
References lldb_private::Args::AppendArgument(), lldb_private::ProcessInfo::GetArguments(), lldb_private::getProcFile(), and lldb_private::ProcessInfo::SetArg0().
Referenced by GetProcessAndStatInfo().
GetProcessEnviron()
void GetProcessEnviron (::pid_t pid, ProcessInstanceInfo & process_info) static
Definition at line 301 of file linux/Host.cpp.
References lldb_private::ProcessInfo::GetEnvironment(), lldb_private::getProcFile(), and lldb_private::Environment::insert().
Referenced by GetProcessAndStatInfo().
GetStatusInfo()
bool GetStatusInfo (::pid_t Pid, ProcessInstanceInfo & ProcessInfo, ProcessState & State, ::pid_t & TracerPid, ::pid_t & Tgid) static
Definition at line 86 of file linux/Host.cpp.
References convert(), lldb_private::GetLog(), lldb_private::getProcFile(), lldb_private::Host, LLDB_LOG, lldb_private::ProcessInfo::SetGroupID(), lldb_private::ProcessInfo::SetUserID(), lldb_private::ProcessInstanceInfo::timespec::tv_sec, and lldb_private::ProcessInstanceInfo::timespec::tv_usec.
Referenced by GetProcessAndStatInfo().
IsDirNumeric()
bool IsDirNumeric (const char * dname) static
Definition at line 226 of file linux/Host.cpp.