LLDB: LinuxProcMaps.cpp File Reference
LinuxProcMaps.cpp File Reference
#include "LinuxProcMaps.h"
#include "lldb/Target/MemoryRegionInfo.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/StringExtractor.h"
#include "llvm/ADT/StringRef.h"
#include <optional>
Enumerations
enum class MapsKind { Maps , SMaps }
Functions
static llvm::Expected< MemoryRegionInfo > ProcMapError (const char *msg, MapsKind kind)
static llvm::Expected< MemoryRegionInfo > ParseMemoryRegionInfoFromProcMapsLine (llvm::StringRef maps_line, MapsKind maps_kind)
Enumeration Type Documentation
MapsKind
enum class MapsKind strong
Enumerator
Maps
SMaps
Definition at line 18 of file LinuxProcMaps.cpp.
Function Documentation
ParseMemoryRegionInfoFromProcMapsLine()
llvm::Expected< MemoryRegionInfo > ParseMemoryRegionInfoFromProcMapsLine (llvm::StringRef maps_line, MapsKind maps_kind) static
Definition at line 27 of file LinuxProcMaps.cpp.
References lldb_private::MemoryRegionInfo::eDontKnow, lldb_private::MemoryRegionInfo::eNo, lldb_private::MemoryRegionInfo::eYes, StringExtractor::GetBytesLeft(), StringExtractor::GetChar(), StringExtractor::GetHexMaxU64(), lldb_private::MemoryRegionInfo::GetRange(), StringExtractor::GetU64(), StringExtractor::Peek(), ProcMapError(), lldb_private::MemoryRegionInfo::SetExecutable(), lldb_private::MemoryRegionInfo::SetMapped(), lldb_private::MemoryRegionInfo::SetName(), lldb_private::Range< B, S >::SetRangeBase(), lldb_private::Range< B, S >::SetRangeEnd(), lldb_private::MemoryRegionInfo::SetReadable(), lldb_private::MemoryRegionInfo::SetShared(), lldb_private::MemoryRegionInfo::SetWritable(), and StringExtractor::SkipSpaces().
Referenced by lldb_private::ParseLinuxMapRegions(), and lldb_private::ParseLinuxSMapRegions().
ProcMapError()
llvm::Expected< MemoryRegionInfo > ProcMapError (const char * msg, MapsKind kind) static
Definition at line 20 of file LinuxProcMaps.cpp.
References Maps.
Referenced by lldb_private::ParseLinuxSMapRegions(), and ParseMemoryRegionInfoFromProcMapsLine().