LLDB: LockFilePosix.cpp File Reference
LockFilePosix.cpp File Reference
#include "lldb/Host/posix/LockFilePosix.h"
#include "llvm/Support/Errno.h"
#include <fcntl.h>
#include <unistd.h>
Functions
static Status fileLock (int fd, int cmd, int lock_type, const uint64_t start, const uint64_t len)
Function Documentation
fileLock()
Status fileLock (int fd, int cmd, int lock_type, const uint64_t start, const uint64_t len) static
Definition at line 19 of file LockFilePosix.cpp.
References lldb_private::Status::FromErrno(), and lldb_private::Status.
Referenced by lldb_private::LockFilePosix::DoReadLock(), lldb_private::LockFileWindows::DoReadLock(), lldb_private::LockFilePosix::DoTryReadLock(), lldb_private::LockFileWindows::DoTryReadLock(), lldb_private::LockFilePosix::DoTryWriteLock(), lldb_private::LockFileWindows::DoTryWriteLock(), lldb_private::LockFilePosix::DoUnlock(), lldb_private::LockFilePosix::DoWriteLock(), and lldb_private::LockFileWindows::DoWriteLock().