LLDB: LockFileBase.cpp File Reference
LockFileBase.cpp File Reference
#include "lldb/Host/LockFileBase.h"
Functions
static Status AlreadyLocked ()
static Status NotLocked ()
Function Documentation
AlreadyLocked()
Status AlreadyLocked () static
Definition at line 14 of file LockFileBase.cpp.
References lldb_private::Status::FromErrorString().
Referenced by lldb_private::LockFileBase::DoLock().
NotLocked()
Status NotLocked () static
Definition at line 18 of file LockFileBase.cpp.
References lldb_private::Status::FromErrorString().
Referenced by lldb_private::LockFileBase::Unlock().