LLDB: MinidumpFileBuilder.h File Reference
MinidumpFileBuilder.h File Reference
Structure holding data neccessary for minidump file creation.
#include <cstddef>
#include <cstdint>
#include <map>
#include <unordered_map>
#include <utility>
#include <variant>
#include "lldb/Core/Progress.h"
#include "lldb/Symbol/SaveCoreOptions.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/Status.h"
#include "lldb/lldb-forward.h"
#include "lldb/lldb-types.h"
#include "llvm/BinaryFormat/Minidump.h"
#include "llvm/Object/Minidump.h"
Classes
class MinidumpFileBuilder
Minidump writer for Linux.
Functions
lldb_private::Status WriteString (const std::string &to_write, lldb_private::DataBufferHeap *buffer)
Detailed Description
Structure holding data neccessary for minidump file creation.
The class MinidumpFileWriter is used to hold the data that will eventually be dumped to the file.
Definition in file MinidumpFileBuilder.h.
Function Documentation
WriteString()
lldb_private::Status WriteString (const std::string & to_write, lldb_private::DataBufferHeap * buffer)
Definition at line 225 of file MinidumpFileBuilder.cpp.
References lldb_private::DataBufferHeap::AppendData(), error(), and lldb_private::Status::FromErrorStringWithFormat().
Referenced by MinidumpFileBuilder::AddModuleList(), and MinidumpFileBuilder::AddSystemInfo().