LLDB: ModuleList.cpp File Reference
ModuleList.cpp File Reference
#include "lldb/Core/ModuleList.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Host/FileSystem.h"
#include "lldb/Interpreter/OptionValueFileSpec.h"
#include "lldb/Interpreter/OptionValueFileSpecList.h"
#include "lldb/Interpreter/OptionValueProperties.h"
#include "lldb/Interpreter/Property.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Symbol/TypeList.h"
#include "lldb/Symbol/VariableList.h"
#include "lldb/Target/Platform.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/ArchSpec.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/FileSpecList.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/UUID.h"
#include "lldb/lldb-defines.h"
#include "llvm/Support/ThreadPool.h"
#include "clang/Driver/Driver.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Threading.h"
#include "llvm/Support/raw_ostream.h"
#include <chrono>
#include <memory>
#include <mutex>
#include <string>
#include <utility>
#include "CoreProperties.inc"
#include "CorePropertiesEnum.inc"
Namespaces
namespace lldb_private
A class that represents a running process on the host machine.
Macros
#define LLDB_PROPERTIES_modulelist
#define LLDB_PROPERTIES_modulelist
Functions
static SharedModuleListInfo & GetSharedModuleListInfo ()
static SharedModuleList & GetSharedModuleList ()
Macro Definition Documentation
LLDB_PROPERTIES_modulelist [1/2]
#define LLDB_PROPERTIES_modulelist
Definition at line 71 of file ModuleList.cpp.
LLDB_PROPERTIES_modulelist [2/2]
#define LLDB_PROPERTIES_modulelist
Definition at line 71 of file ModuleList.cpp.
Function Documentation
GetSharedModuleList()
SharedModuleList & GetSharedModuleList () static
Definition at line 1024 of file ModuleList.cpp.
References GetSharedModuleListInfo().
Referenced by lldb_private::ModuleList::FindSharedModule(), lldb_private::ModuleList::FindSharedModules(), lldb_private::ModuleList::GetSharedModule(), lldb_private::ModuleList::ModuleIsInCache(), lldb_private::ModuleList::RemoveOrphanSharedModules(), lldb_private::ModuleList::RemoveSharedModule(), and lldb_private::ModuleList::RemoveSharedModuleIfOrphaned().
GetSharedModuleListInfo()
SharedModuleListInfo & GetSharedModuleListInfo () static
Definition at line 1010 of file ModuleList.cpp.
Referenced by lldb_private::ModuleList::GetGlobalModuleListProperties(), and GetSharedModuleList().