LLDB: MsvcStl.cpp File Reference
MsvcStl.cpp File Reference
#include "MsvcStl.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/FormatEntity.h"
#include "lldb/DataFormatters/StringPrinter.h"
#include "lldb/DataFormatters/TypeSummary.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/Stream.h"
#include "lldb/ValueObject/ValueObject.h"
#include "Plugins/Language/CPlusPlus/CxxStringTypes.h"
#include "lldb/lldb-forward.h"
#include <optional>
#include <tuple>
Functions
template<StringElementType element_type>
static constexpr uint64_t StringElementByteSize ()
static ValueObjectSP ExtractMsvcStlStringData (ValueObject &valobj)
static std::optional< std::pair< uint64_t, ValueObjectSP > > ExtractMsvcStlStringInfo (ValueObject &valobj, uint64_t element_size)
Determine the size in bytes of valobj (a MSVC STL std::string object) and extract its data payload.
template<StringPrinter::StringElementType element_type>
static bool MsvcStlStringSummaryProviderImpl (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options, std::string prefix_token)
template<StringPrinter::StringElementType element_type>
static bool formatStringImpl (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options, std::string prefix_token)
template<StringPrinter::StringElementType element_type>
static bool formatStringViewImpl (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options, std::string prefix_token)
template<>
bool lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::ASCII > (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options)
template<>
bool lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::UTF8 > (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options)
template<>
bool lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::UTF16 > (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options)
template<>
bool lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::UTF32 > (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options)
template<>
bool lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::ASCII > (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options)
template<>
bool lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::UTF8 > (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options)
template<>
bool lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::UTF16 > (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options)
template<>
bool lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::UTF32 > (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options)
static std::optional< int64_t > MsvcStlExtractOrderingValue (ValueObject &valobj)
Function Documentation
ExtractMsvcStlStringData()
ValueObjectSP ExtractMsvcStlStringData (ValueObject & valobj) static
Definition at line 46 of file MsvcStl.cpp.
References lldb_private::ValueObject::GetChildAtNamePath().
Referenced by ExtractMsvcStlStringInfo().
ExtractMsvcStlStringInfo()
std::optional< std::pair< uint64_t, ValueObjectSP > > ExtractMsvcStlStringInfo (ValueObject & valobj, uint64_t element_size) static
Determine the size in bytes of valobj (a MSVC STL std::string object) and extract its data payload.
Return the size + payload pair.
Definition at line 53 of file MsvcStl.cpp.
References ExtractMsvcStlStringData().
Referenced by MsvcStlStringSummaryProviderImpl().
formatStringImpl()
template<StringPrinter::StringElementType element_type> bool formatStringImpl (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options, std::string prefix_token) static
Definition at line 102 of file MsvcStl.cpp.
References lldb_private::StreamString::GetData(), and MsvcStlStringSummaryProviderImpl().
Referenced by lldb_private::formatters::MsvcStlWStringSummaryProvider().
formatStringViewImpl()
template<StringPrinter::StringElementType element_type> bool formatStringViewImpl (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options, std::string prefix_token) static
Definition at line 116 of file MsvcStl.cpp.
References lldb_private::ValueObject::GetChildMemberWithName(), lldb_private::StreamString::GetData(), and lldb_private::formatters::StringBufferSummaryProvider().
Referenced by lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::ASCII >(), lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::UTF16 >(), lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::UTF32 >(), lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::UTF8 >(), and lldb_private::formatters::MsvcStlWStringViewSummaryProvider().
lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::ASCII >()
template<> bool lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::ASCII > (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options)
Definition at line 162 of file MsvcStl.cpp.
References lldb_private::formatters::MsvcStlStringSummaryProvider(), and MsvcStlStringSummaryProviderImpl().
Referenced by LoadCommonStlFormatters().
lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::UTF16 >()
template<> bool lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::UTF16 > (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options)
Definition at line 176 of file MsvcStl.cpp.
References lldb_private::formatters::MsvcStlStringSummaryProvider(), and MsvcStlStringSummaryProviderImpl().
lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::UTF32 >()
template<> bool lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::UTF32 > (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options)
Definition at line 183 of file MsvcStl.cpp.
References lldb_private::formatters::MsvcStlStringSummaryProvider(), and MsvcStlStringSummaryProviderImpl().
lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::UTF8 >()
template<> bool lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::UTF8 > (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options)
Definition at line 169 of file MsvcStl.cpp.
References lldb_private::formatters::MsvcStlStringSummaryProvider(), and MsvcStlStringSummaryProviderImpl().
lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::ASCII >()
template<> bool lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::ASCII > (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options)
Definition at line 198 of file MsvcStl.cpp.
References formatStringViewImpl(), and lldb_private::formatters::MsvcStlStringViewSummaryProvider().
Referenced by LoadCommonStlFormatters().
lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::UTF16 >()
template<> bool lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::UTF16 > (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options)
Definition at line 212 of file MsvcStl.cpp.
References formatStringViewImpl(), and lldb_private::formatters::MsvcStlStringViewSummaryProvider().
Referenced by LoadCommonStlFormatters().
lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::UTF32 >()
template<> bool lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::UTF32 > (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options)
Definition at line 219 of file MsvcStl.cpp.
References formatStringViewImpl(), and lldb_private::formatters::MsvcStlStringViewSummaryProvider().
Referenced by LoadCommonStlFormatters().
lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::UTF8 >()
template<> bool lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::UTF8 > (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options)
Definition at line 205 of file MsvcStl.cpp.
References formatStringViewImpl(), and lldb_private::formatters::MsvcStlStringViewSummaryProvider().
Referenced by LoadCommonStlFormatters().
MsvcStlExtractOrderingValue()
std::optional< int64_t > MsvcStlExtractOrderingValue (ValueObject & valobj) static
Definition at line 232 of file MsvcStl.cpp.
References lldb_private::ValueObject::GetChildMemberWithName().
Referenced by lldb_private::formatters::MsvcStlPartialOrderingSummaryProvider(), lldb_private::formatters::MsvcStlStrongOrderingSummaryProvider(), and lldb_private::formatters::MsvcStlWeakOrderingSummaryProvider().
MsvcStlStringSummaryProviderImpl()
template<StringPrinter::StringElementType element_type> bool MsvcStlStringSummaryProviderImpl (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options, std::string prefix_token) static
Definition at line 89 of file MsvcStl.cpp.
References ExtractMsvcStlStringInfo(), lldb_private::formatters::StringBufferSummaryProvider(), and StringElementByteSize().
Referenced by formatStringImpl(), lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::ASCII >(), lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::UTF16 >(), lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::UTF32 >(), and lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::UTF8 >().
StringElementByteSize()
template<StringElementType element_type> constexpr uint64_t StringElementByteSize () static constexpr
Definition at line 33 of file MsvcStl.cpp.
Referenced by MsvcStlStringSummaryProviderImpl().