LLDB: lldb_private::formatters Namespace Reference
lldb_private::formatters Namespace Reference
Namespaces
namespace CallStackArray
namespace ConstantArray
namespace Foundation1010
namespace Foundation1100
namespace Foundation1300
namespace Foundation1428
namespace Foundation1430
namespace Foundation1436
namespace Foundation1437
Classes
class BlockPointerSyntheticFrontEnd
class GenericInitializerListSyntheticFrontEnd
class GenericNSArrayISyntheticFrontEnd
class GenericNSArrayMSyntheticFrontEnd
class GenericNSDictionaryMSyntheticFrontEnd
class GenericNSSetMSyntheticFrontEnd
struct InferiorSizedWord
class LibCxxMapIteratorSyntheticFrontEnd
class LibcxxSharedPtrSyntheticFrontEnd
class LibcxxStdAtomicSyntheticFrontEnd
class LibcxxStdMapSyntheticFrontEnd
class LibcxxStdProxyArraySyntheticFrontEnd
Data formatter for libc++'s std::"proxy_array".
class LibcxxStdRangesRefViewSyntheticFrontEnd
class LibcxxStdSliceArraySyntheticFrontEnd
Data formatter for libc++'s std::slice_array.
class LibcxxStdSpanSyntheticFrontEnd
class LibcxxStdUnorderedMapSyntheticFrontEnd
class LibcxxStdValarraySyntheticFrontEnd
class LibcxxStdVectorSyntheticFrontEnd
class LibcxxUniquePtrSyntheticFrontEnd
class LibCxxUnorderedMapIteratorSyntheticFrontEnd
class LibcxxVectorBoolSyntheticFrontEnd
class LibStdcppSpanSyntheticFrontEnd
class MsvcStlAtomicSyntheticFrontEnd
class MsvcStlDequeSyntheticFrontEnd
class MsvcStlSmartPointerSyntheticFrontEnd
class MsvcStlSpanSyntheticFrontEnd
class MsvcStlTreeIterSyntheticFrontEnd
class MsvcStlTreeSyntheticFrontEnd
class MsvcStlUniquePtrSyntheticFrontEnd
class MsvcStlVectorBoolSyntheticFrontEnd
class MsvcStlVectorSyntheticFrontEnd
class NSArray0SyntheticFrontEnd
class NSArray1SyntheticFrontEnd
class NSArray_Additionals
class NSArrayMSyntheticFrontEndBase
class NSCFDictionarySyntheticFrontEnd
class NSCFSetSyntheticFrontEnd
class NSConstantDictionarySyntheticFrontEnd
class NSDictionary1SyntheticFrontEnd
class NSDictionary_Additionals
class NSDictionaryISyntheticFrontEnd
class NSSet_Additionals
class NSSetISyntheticFrontEnd
class NSString_Additionals
class StdlibCoroutineHandleSyntheticFrontEnd
Synthetic children frontend for std::coroutine_handle<promise_type> from libc++, libstdc++ and MSVC STL.
class StringPrinter
class VectorIteratorSyntheticFrontEnd
class VectorTypeSyntheticFrontEnd
Functions
bool CXXFunctionPointerSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
void AddFormat (TypeCategoryImpl::SharedPointer category_sp, lldb::Format format, llvm::StringRef type_name, TypeFormatImpl::Flags flags, bool regex=false)
void AddSummary (TypeCategoryImpl::SharedPointer category_sp, lldb::TypeSummaryImplSP summary_sp, llvm::StringRef type_name, bool regex=false)
void AddStringSummary (TypeCategoryImpl::SharedPointer category_sp, const char *string, llvm::StringRef type_name, TypeSummaryImpl::Flags flags, bool regex=false)
void AddOneLineSummary (TypeCategoryImpl::SharedPointer category_sp, llvm::StringRef type_name, TypeSummaryImpl::Flags flags, bool regex=false)
void AddCXXSummary (TypeCategoryImpl::SharedPointer category_sp, CXXFunctionSummaryFormat::Callback funct, const char *description, llvm::StringRef type_name, TypeSummaryImpl::Flags flags, bool regex=false)
Add a summary that is implemented by a C++ callback.
void AddCXXSynthetic (TypeCategoryImpl::SharedPointer category_sp, CXXSyntheticChildren::CreateFrontEndCallback generator, const char *description, llvm::StringRef type_name, ScriptedSyntheticChildren::Flags flags, bool regex=false)
Add a synthetic that is implemented by a C++ callback.
void AddFilter (TypeCategoryImpl::SharedPointer category_sp, std::vector< std::string > children, const char *description, llvm::StringRef type_name, ScriptedSyntheticChildren::Flags flags, bool regex=false)
std::optional< size_t > ExtractIndexFromString (const char *item_name)
void DumpCxxSmartPtrPointerSummary (Stream &stream, ValueObject &ptr, const TypeSummaryOptions &options)
Prints the summary for the pointer value of a C++ std::unique_ptr/std::shared_ptr/std::weak_ptr.
bool ContainerSizeSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
Address GetArrayAddressOrPointerValue (ValueObject &valobj)
time_t GetOSXEpoch ()
bool VectorTypeSummaryProvider (ValueObject &, Stream &, const TypeSummaryOptions &)
SyntheticChildrenFrontEnd * VectorTypeSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
template<typename SourceDataType>
static bool ReadEncodedBufferAndDumpToStream (StringElementType elem_type, const StringPrinter::ReadStringAndDumpToStreamOptions &options, llvm::ConversionResult(*ConvertFunction)(const SourceDataType **, const SourceDataType *, llvm::UTF8 **, llvm::UTF8 *, llvm::ConversionFlags))
template<>
bool StringPrinter::ReadStringAndDumpToStream< StringElementType::UTF8 > (const ReadStringAndDumpToStreamOptions &options)
template<>
bool StringPrinter::ReadStringAndDumpToStream< StringElementType::UTF16 > (const ReadStringAndDumpToStreamOptions &options)
template<>
bool StringPrinter::ReadStringAndDumpToStream< StringElementType::UTF32 > (const ReadStringAndDumpToStreamOptions &options)
template<>
bool StringPrinter::ReadStringAndDumpToStream< StringElementType::ASCII > (const ReadStringAndDumpToStreamOptions &options)
template<>
bool StringPrinter::ReadBufferAndDumpToStream< StringElementType::UTF8 > (const ReadBufferAndDumpToStreamOptions &options)
template<>
bool StringPrinter::ReadBufferAndDumpToStream< StringElementType::UTF16 > (const ReadBufferAndDumpToStreamOptions &options)
template<>
bool StringPrinter::ReadBufferAndDumpToStream< StringElementType::UTF32 > (const ReadBufferAndDumpToStreamOptions &options)
template<>
bool StringPrinter::ReadBufferAndDumpToStream< StringElementType::ASCII > (const ReadBufferAndDumpToStreamOptions &options)
bool BlockPointerSummaryProvider (ValueObject &, Stream &, const TypeSummaryOptions &)
SyntheticChildrenFrontEnd * BlockPointerSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
bool StdlibCoroutineHandleSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
Summary provider for std::coroutine_handle<T> from libc++, libstdc++ and MSVC STL.
SyntheticChildrenFrontEnd * StdlibCoroutineHandleSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
bool Char8StringSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool Char16StringSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool Char32StringSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool WCharStringSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool Char8SummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool Char16SummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool Char32SummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool WCharSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
std::optional< uint64_t > GetWCharByteSize (ValueObject &valobj)
template<StringPrinter::StringElementType element_type>
bool StringBufferSummaryProvider (Stream &stream, const TypeSummaryOptions &summary_options, lldb::ValueObjectSP location_sp, uint64_t size, std::string prefix_token)
Print a summary for a string buffer to stream.
bool GenericOptionalSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
lldb::ValueObjectSP GetDesugaredSmartPointerValue (ValueObject &ptr, ValueObject &container)
Return the ValueObjectSP of the underlying pointer member whose type is a desugared 'std::shared_ptr::element_type *'.
SyntheticChildrenFrontEnd * GenericInitializerListSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP valobj_sp)
lldb::ValueObjectSP GetChildMemberWithName (ValueObject &obj, llvm::ArrayRef< ConstString > alternative_names)
Find a child member of obj_sp, trying all alternative names in order.
lldb::ValueObjectSP GetFirstValueOfLibCXXCompressedPair (ValueObject &pair)
lldb::ValueObjectSP GetSecondValueOfLibCXXCompressedPair (ValueObject &pair)
std::pair< lldb::ValueObjectSP, bool > GetValueOrOldCompressedPair (ValueObject &obj, llvm::StringRef child_name, llvm::StringRef compressed_pair_name)
Returns the ValueObjectSP of the child of obj.
bool isStdTemplate (ConstString type_name, llvm::StringRef type)
bool LibcxxStringSummaryProviderASCII (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options)
bool LibcxxStringSummaryProviderUTF16 (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options)
bool LibcxxStringSummaryProviderUTF32 (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options)
bool LibcxxWStringSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibcxxStringViewSummaryProviderASCII (ValueObject &valueObj, Stream &stream, const TypeSummaryOptions &summary_options)
bool LibcxxStringViewSummaryProviderUTF16 (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options)
bool LibcxxStringViewSummaryProviderUTF32 (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options)
bool LibcxxWStringViewSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibcxxStdSliceArraySummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibcxxSmartPointerSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibcxxUniquePointerSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibcxxFunctionSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibcxxPartialOrderingSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibcxxWeakOrderingSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibcxxStrongOrderingSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
SyntheticChildrenFrontEnd * LibcxxVectorBoolSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
bool LibcxxSpanSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
Formatter for libc++ std::span<>.
SyntheticChildrenFrontEnd * LibCxxVectorIteratorSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibcxxBitsetSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibcxxSharedPtrSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibcxxUniquePtrSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibcxxStdVectorSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibcxxStdValarraySyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibcxxStdSliceArraySyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibcxxStdProxyArraySyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibcxxStdListSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibcxxStdForwardListSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibcxxStdMapSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibCxxMapIteratorSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibcxxStdUnorderedMapSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibCxxUnorderedMapIteratorSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibcxxQueueFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibcxxTupleFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibcxxOptionalSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP valobj_sp)
SyntheticChildrenFrontEnd * LibcxxVariantFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP valobj_sp)
SyntheticChildrenFrontEnd * LibcxxStdSpanSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibcxxStdRangesRefViewSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
bool LibcxxChronoSysSecondsSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibcxxChronoSysDaysSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibcxxChronoLocalSecondsSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibcxxChronoLocalDaysSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibcxxChronoMonthSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibcxxChronoWeekdaySummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibcxxChronoYearMonthDaySummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool IsLibCxxAtomic (ValueObject &valobj)
lldb::ValueObjectSP GetLibCxxAtomicValue (ValueObject &valobj)
bool LibCxxAtomicSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
SyntheticChildrenFrontEnd * LibcxxAtomicSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
bool LibcxxVariantSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibStdcppStringSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
template<StringPrinter::StringElementType element_type>
bool LibStdcppStringViewSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibStdcppWStringViewSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibStdcppSmartPointerSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibStdcppUniquePointerSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibStdcppVariantSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibStdcppPartialOrderingSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibStdcppWeakOrderingSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool LibStdcppStrongOrderingSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
SyntheticChildrenFrontEnd * LibstdcppMapIteratorSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibStdcppSpanSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibStdcppTupleSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibStdcppBitsetSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibStdcppOptionalSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibStdcppVectorIteratorSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibStdcppSharedPtrSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * LibStdcppUniquePtrSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
bool IsMsvcStlStringType (ValueObject &valobj)
bool IsMsvcStlStringViewType (ValueObject &valobj)
template<StringPrinter::StringElementType element_type>
bool MsvcStlStringSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options)
bool MsvcStlWStringSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
template<StringPrinter::StringElementType element_type>
bool MsvcStlStringViewSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &summary_options)
bool MsvcStlWStringViewSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool IsMsvcStlOrdering (ValueObject &valobj)
bool MsvcStlPartialOrderingSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool MsvcStlWeakOrderingSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool MsvcStlStrongOrderingSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool IsMsvcStlSmartPointer (ValueObject &valobj)
bool MsvcStlSmartPointerSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
lldb_private::SyntheticChildrenFrontEnd * MsvcStlSmartPointerSyntheticFrontEndCreator (lldb::ValueObjectSP valobj_sp)
bool IsMsvcStlUniquePtr (ValueObject &valobj)
bool MsvcStlUniquePtrSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
lldb_private::SyntheticChildrenFrontEnd * MsvcStlUniquePtrSyntheticFrontEndCreator (lldb::ValueObjectSP valobj_sp)
bool IsMsvcStlTuple (ValueObject &valobj)
SyntheticChildrenFrontEnd * MsvcStlTupleSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP valobj_sp)
bool IsMsvcStlVector (ValueObject &valobj)
lldb_private::SyntheticChildrenFrontEnd * MsvcStlVectorSyntheticFrontEndCreator (lldb::ValueObjectSP valobj_sp)
bool IsMsvcStlList (ValueObject &valobj)
SyntheticChildrenFrontEnd * MsvcStlForwardListSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP valobj_sp)
SyntheticChildrenFrontEnd * MsvcStlListSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP valobj_sp)
bool IsMsvcStlOptional (ValueObject &valobj)
SyntheticChildrenFrontEnd * MsvcStlOptionalSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP valobj_sp)
bool IsMsvcStlVariant (ValueObject &valobj)
bool MsvcStlVariantSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
SyntheticChildrenFrontEnd * MsvcStlVariantSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP valobj_sp)
bool IsMsvcStlAtomic (ValueObject &valobj)
bool MsvcStlAtomicSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
SyntheticChildrenFrontEnd * MsvcStlAtomicSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP valobj_sp)
bool IsMsvcStlUnordered (ValueObject &valobj)
SyntheticChildrenFrontEnd * MsvcStlUnorderedSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP valobj_sp)
bool IsMsvcStlTreeIter (ValueObject &valobj)
bool MsvcStlTreeIterSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
lldb_private::SyntheticChildrenFrontEnd * MsvcStlTreeIterSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP valobj_sp)
bool IsMsvcStlMapLike (ValueObject &valobj)
lldb_private::SyntheticChildrenFrontEnd * MsvcStlMapLikeSyntheticFrontEndCreator (lldb::ValueObjectSP valobj_sp)
bool IsMsvcStlDeque (ValueObject &valobj)
SyntheticChildrenFrontEnd * MsvcStlDequeSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP valobj_sp)
bool IsMsvcStlSpan (ValueObject &valobj)
SyntheticChildrenFrontEnd * MsvcStlSpanSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP valobj_sp)
bool CFBagSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool CFBinaryHeapSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool CFBitVectorSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool CFAbsoluteTimeSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool NSIndexSetSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool NSArraySummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
template<bool needs_at>
bool NSDataSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool NSNumberSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool NSDecimalNumberSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool NSNotificationSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool NSTimeZoneSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool NSMachPortSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool NSDateSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool NSBundleSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool NSURLSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
template bool NSDataSummaryProvider< true > (ValueObject &, Stream &, const TypeSummaryOptions &)
template bool NSDataSummaryProvider< false > (ValueObject &, Stream &, const TypeSummaryOptions &)
SyntheticChildrenFrontEnd * NSArraySyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
SyntheticChildrenFrontEnd * NSIndexPathSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
bool ObjCClassSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
SyntheticChildrenFrontEnd * ObjCClassSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
bool ObjCBOOLSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool ObjCBooleanSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
template<bool is_sel_ptr>
bool ObjCSELSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
template bool ObjCSELSummaryProvider< true > (ValueObject &, Stream &, const TypeSummaryOptions &)
template bool ObjCSELSummaryProvider< false > (ValueObject &, Stream &, const TypeSummaryOptions &)
bool NSError_SummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool NSException_SummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
SyntheticChildrenFrontEnd * NSErrorSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP valobj_sp)
SyntheticChildrenFrontEnd * NSExceptionSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP valobj_sp)
bool CMTimeSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
template<bool name_entries>
bool NSDictionarySummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
template bool NSDictionarySummaryProvider< true > (ValueObject &, Stream &, const TypeSummaryOptions &)
template bool NSDictionarySummaryProvider< false > (ValueObject &, Stream &, const TypeSummaryOptions &)
SyntheticChildrenFrontEnd * NSDictionarySyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
template<bool cf_style>
bool NSSetSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
SyntheticChildrenFrontEnd * NSSetSyntheticFrontEndCreator (CXXSyntheticChildren *, lldb::ValueObjectSP)
bool NSStringSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool NSTaggedString_SummaryProvider (ValueObject &valobj, ObjCLanguageRuntime::ClassDescriptorSP descriptor, Stream &stream, const TypeSummaryOptions &summary_options)
bool NSIndirectTaggedString_SummaryProvider (ValueObject &valobj, ObjCLanguageRuntime::ClassDescriptorSP descriptor, Stream &stream, const TypeSummaryOptions &summary_options)
bool NSAttributedStringSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
bool NSMutableAttributedStringSummaryProvider (ValueObject &valobj, Stream &stream, const TypeSummaryOptions &options)
Function Documentation
AddCXXSummary()
void lldb_private::formatters::AddCXXSummary (TypeCategoryImpl::SharedPointer category_sp, CXXFunctionSummaryFormat::Callback funct, const char * description, llvm::StringRef type_name, TypeSummaryImpl::Flags flags, bool regex = false)
Add a summary that is implemented by a C++ callback.
Definition at line 64 of file FormattersHelpers.cpp.
References lldb::eFormatterMatchExact, and lldb::eFormatterMatchRegex.
Referenced by LoadCommonStlFormatters(), LoadCoreMediaFormatters(), LoadLibCxxFormatters(), LoadLibStdcppFormatters(), LoadMsvcStlFormatters(), LoadObjCFormatters(), and LoadSystemFormatters().
AddCXXSynthetic()
void lldb_private::formatters::AddCXXSynthetic (TypeCategoryImpl::SharedPointer category_sp, CXXSyntheticChildren::CreateFrontEndCallback generator, const char * description, llvm::StringRef type_name, ScriptedSyntheticChildren::Flags flags, bool regex = false)
Add a synthetic that is implemented by a C++ callback.
Definition at line 76 of file FormattersHelpers.cpp.
References lldb::eFormatterMatchExact, and lldb::eFormatterMatchRegex.
Referenced by LoadCommonStlFormatters(), LoadLibCxxFormatters(), LoadLibStdcppFormatters(), LoadMsvcStlFormatters(), and LoadObjCFormatters().
AddFilter()
void lldb_private::formatters::AddFilter (TypeCategoryImpl::SharedPointer category_sp, std::vector< std::string > children, const char * description, llvm::StringRef type_name, ScriptedSyntheticChildren::Flags flags, bool regex = false)
Definition at line 88 of file FormattersHelpers.cpp.
References lldb::eFormatterMatchExact, and lldb::eFormatterMatchRegex.
AddFormat()
void lldb_private::formatters::AddFormat (TypeCategoryImpl::SharedPointer category_sp, lldb::Format format, llvm::StringRef type_name, TypeFormatImpl::Flags flags, bool regex = false)
Definition at line 25 of file FormattersHelpers.cpp.
References lldb::eFormatterMatchExact, and lldb::eFormatterMatchRegex.
Referenced by lldb_private::FormatManager::LoadSystemFormatters().
AddOneLineSummary()
void lldb_private::formatters::AddOneLineSummary (TypeCategoryImpl::SharedPointer category_sp, llvm::StringRef type_name, TypeSummaryImpl::Flags flags, bool regex = false)
Definition at line 53 of file FormattersHelpers.cpp.
References lldb::eFormatterMatchExact, lldb::eFormatterMatchRegex, and lldb_private::TypeSummaryImpl::Flags::SetShowMembersOneLiner().
Referenced by LoadObjCFormatters().
AddStringSummary()
void lldb_private::formatters::AddStringSummary (TypeCategoryImpl::SharedPointer category_sp, const char * string, llvm::StringRef type_name, TypeSummaryImpl::Flags flags, bool regex = false)
Definition at line 43 of file FormattersHelpers.cpp.
References lldb::eFormatterMatchExact, and lldb::eFormatterMatchRegex.
Referenced by LoadObjCFormatters(), and lldb_private::FormatManager::LoadVectorFormatters().
AddSummary()
void lldb_private::formatters::AddSummary (TypeCategoryImpl::SharedPointer category_sp, lldb::TypeSummaryImplSP summary_sp, llvm::StringRef type_name, bool regex = false)
Definition at line 35 of file FormattersHelpers.cpp.
References lldb::eFormatterMatchExact, and lldb::eFormatterMatchRegex.
BlockPointerSummaryProvider()
bool lldb_private::formatters::BlockPointerSummaryProvider (ValueObject & valobj, Stream & s, const TypeSummaryOptions &)
Definition at line 164 of file BlockPointer.cpp.
References BlockPointerSyntheticFrontEndCreator(), lldb_private::DataFormatters, lldb::eDynamicDontRunTarget, lldb_private::SyntheticChildrenFrontEnd::GetChildAtIndex(), lldb_private::SyntheticChildrenFrontEnd::GetIndexOfChildWithName(), lldb_private::GetLog(), lldb_private::ValueObject::GetSP(), LLDB_LOG_ERROR, lldb_private::Stream::Printf(), and lldb_private::SyntheticChildrenFrontEnd::Update().
Referenced by lldb_private::CPlusPlusLanguage::GetHardcodedSummaries().
BlockPointerSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::BlockPointerSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by BlockPointerSummaryProvider(), and lldb_private::CPlusPlusLanguage::GetHardcodedSynthetics().
CFAbsoluteTimeSummaryProvider()
bool lldb_private::formatters::CFAbsoluteTimeSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 29 of file CF.cpp.
References GetOSXEpoch(), lldb_private::ValueObject::GetValueAsSigned(), and lldb_private::Stream::Printf().
Referenced by LoadObjCFormatters().
CFBagSummaryProvider()
bool lldb_private::formatters::CFBagSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 45 of file CF.cpp.
References error(), lldb_private::Language::FindPlugin(), lldb_private::ObjCLanguageRuntime::Get(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), lldb_private::TypeSummaryOptions::GetLanguage(), lldb_private::ValueObject::GetProcessSP(), lldb_private::ValueObject::GetTypeName(), lldb_private::ValueObject::GetValueAsUnsigned(), lldb_private::ValueObject::IsPointerType(), and lldb_private::Stream::Printf().
Referenced by LoadObjCFormatters().
CFBinaryHeapSummaryProvider()
bool lldb_private::formatters::CFBinaryHeapSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 223 of file CF.cpp.
References error(), lldb_private::Language::FindPlugin(), lldb_private::ObjCLanguageRuntime::Get(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), lldb_private::TypeSummaryOptions::GetLanguage(), lldb_private::ValueObject::GetProcessSP(), lldb_private::ValueObject::GetTypeName(), lldb_private::ValueObject::GetValueAsUnsigned(), lldb_private::ValueObject::IsPointerType(), and lldb_private::Stream::Printf().
Referenced by LoadObjCFormatters().
CFBitVectorSummaryProvider()
bool lldb_private::formatters::CFBitVectorSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 105 of file CF.cpp.
References error(), lldb_private::ObjCLanguageRuntime::Get(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), lldb_private::ValueObject::GetProcessSP(), lldb_private::ValueObject::GetTypeName(), lldb_private::ValueObject::GetValueAsUnsigned(), lldb_private::ValueObject::IsPointerType(), and lldb_private::Stream::Printf().
Referenced by LoadObjCFormatters().
Char16StringSummaryProvider()
bool lldb_private::formatters::Char16StringSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 102 of file CxxStringTypes.cpp.
References CharStringSummaryProvider().
Referenced by LoadSystemFormatters().
Char16SummaryProvider()
bool lldb_private::formatters::Char16SummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 152 of file CxxStringTypes.cpp.
References CharSummaryProvider().
Referenced by LoadSystemFormatters().
Char32StringSummaryProvider()
bool lldb_private::formatters::Char32StringSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 107 of file CxxStringTypes.cpp.
References CharStringSummaryProvider().
Referenced by LoadSystemFormatters().
Char32SummaryProvider()
bool lldb_private::formatters::Char32SummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 157 of file CxxStringTypes.cpp.
References CharSummaryProvider().
Referenced by LoadSystemFormatters().
Char8StringSummaryProvider()
bool lldb_private::formatters::Char8StringSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 97 of file CxxStringTypes.cpp.
References CharStringSummaryProvider().
Referenced by LoadSystemFormatters().
Char8SummaryProvider()
bool lldb_private::formatters::Char8SummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 147 of file CxxStringTypes.cpp.
References CharSummaryProvider().
Referenced by LoadSystemFormatters().
CMTimeSummaryProvider()
bool lldb_private::formatters::CMTimeSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 22 of file CoreMedia.cpp.
References lldb::eEncodingSint, lldb_private::TypeSystem::GetBuiltinTypeForEncodingAndBitSize(), lldb_private::ValueObject::GetCompilerType(), lldb_private::ValueObject::GetSyntheticChildAtOffset(), lldb_private::CompilerType::GetTypeSystem(), lldb_private::CompilerType::IsValid(), and lldb_private::Stream::Printf().
Referenced by LoadCoreMediaFormatters().
ContainerSizeSummaryProvider()
bool lldb_private::formatters::ContainerSizeSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 150 of file FormattersHelpers.cpp.
References lldb_private::FormatEntity::Formatter::FormatStringRef().
Referenced by LoadCommonStlFormatters(), LoadLibCxxFormatters(), and LoadLibStdcppFormatters().
CXXFunctionPointerSummaryProvider()
bool lldb_private::formatters::CXXFunctionPointerSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 24 of file CXXFunctionPointer.cpp.
References lldb_private::Address::Dump(), lldb_private::Address::DumpStyleResolvedDescription, lldb_private::Address::DumpStyleSectionNameOffset, lldb_private::eAddressTypeFile, lldb_private::eAddressTypeHost, lldb_private::eAddressTypeInvalid, lldb_private::eAddressTypeLoad, lldb::eValueTypeVTableEntry, lldb_private::ArchSpec::GetAddressByteSize(), lldb_private::Target::GetArchitecture(), lldb_private::ExecutionContext::GetBestExecutionContextScope(), lldb_private::StreamString::GetData(), lldb_private::ValueObject::GetExecutionContextRef(), lldb_private::ValueObject::GetPointerValue(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::Address::GetSection(), lldb_private::StreamString::GetSize(), lldb_private::ExecutionContext::GetTargetPtr(), lldb_private::ValueObject::GetValueType(), lldb_private::Target::HasLoadedSections(), lldb_private::Address::IsValid(), LLDB_INVALID_ADDRESS, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), lldb_private::Target::ResolveLoadAddress(), and lldb_private::Address::SetLoadAddress().
Referenced by lldb_private::CPlusPlusLanguage::GetHardcodedSummaries().
DumpCxxSmartPtrPointerSummary()
void lldb_private::formatters::DumpCxxSmartPtrPointerSummary (Stream & stream, ValueObject & ptr, const TypeSummaryOptions & options)
Prints the summary for the pointer value of a C++ std::unique_ptr/std::shared_ptr/std::weak_ptr.
Definition at line 131 of file FormattersHelpers.cpp.
References lldb_private::ValueObject::Dereference(), lldb_private::ValueObject::eDisable, lldb::eFormatInvalid, error(), lldb_private::ValueObject::eValueObjectRepresentationStyleSummary, lldb_private::ValueObject::GetValueAsUnsigned(), and lldb_private::Stream::Printf().
Referenced by LibcxxSmartPointerSummaryProvider(), LibcxxUniquePointerSummaryProvider(), LibStdcppSmartPointerSummaryProvider(), MsvcStlSmartPointerSummaryProvider(), and MsvcStlUniquePtrSummaryProvider().
ExtractIndexFromString()
std::optional< size_t > lldb_private::formatters::ExtractIndexFromString (const char * item_name)
Definition at line 102 of file FormattersHelpers.cpp.
Referenced by lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >::GetIndexOfChildWithName(), lldb_private::formatters::GenericNSArrayISyntheticFrontEnd< D32, D64, Inline >::GetIndexOfChildWithName(), lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< D32, D64 >::GetIndexOfChildWithName(), lldb_private::formatters::GenericNSSetMSyntheticFrontEnd< D32, D64 >::GetIndexOfChildWithName(), lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::LibcxxStdSpanSyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::LibcxxStdValarraySyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::LibcxxStdVectorSyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::LibcxxVectorBoolSyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::LibStdcppSpanSyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::MsvcStlDequeSyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::MsvcStlSpanSyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::MsvcStlTreeSyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::MsvcStlVectorBoolSyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::MsvcStlVectorSyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::NSArrayMSyntheticFrontEndBase::GetIndexOfChildWithName(), lldb_private::formatters::NSCFDictionarySyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::NSCFSetSyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::NSDictionaryISyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::NSSetISyntheticFrontEnd::GetIndexOfChildWithName(), lldb_private::formatters::VectorTypeSyntheticFrontEnd::GetIndexOfChildWithName(), and NSIndexPathSyntheticFrontEnd::GetIndexOfChildWithName().
GenericInitializerListSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::GenericInitializerListSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP valobj_sp)
Definition at line 135 of file GenericInitializerList.cpp.
References LibCxx::GetStartMember().
Referenced by LoadCommonStlFormatters().
GenericOptionalSummaryProvider()
bool lldb_private::formatters::GenericOptionalSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 20 of file GenericOptional.cpp.
References lldb_private::ValueObject::GetNumChildrenIgnoringErrors(), and lldb_private::Stream::Printf().
Referenced by LoadCommonStlFormatters(), and LoadLibCxxFormatters().
GetArrayAddressOrPointerValue()
Address lldb_private::formatters::GetArrayAddressOrPointerValue (ValueObject & valobj)
Definition at line 116 of file FormattersHelpers.cpp.
References lldb_private::ValueObject::AddrAndType::address, lldb_private::eAddressTypeFile, lldb_private::ValueObject::GetAddressOf(), lldb_private::ValueObject::GetModule(), lldb_private::ValueObject::GetPointerValue(), lldb_private::ValueObject::IsArrayType(), lldb_private::ValueObject::IsPointerType(), LLDB_INVALID_ADDRESS, and lldb_private::ValueObject::AddrAndType::type.
Referenced by CharStringSummaryProvider(), and WCharStringSummaryProvider().
GetChildMemberWithName()
lldb::ValueObjectSP lldb_private::formatters::GetChildMemberWithName (ValueObject & obj, llvm::ArrayRef< ConstString > alternative_names)
Find a child member of obj_sp, trying all alternative names in order.
Definition at line 63 of file LibCxx.cpp.
References lldb_private::ValueObject::GetChildMemberWithName().
Referenced by LibcxxExtractStringViewData(), LibcxxVariantSummaryProvider(), lldb_private::formatters::LibcxxStdRangesRefViewSyntheticFrontEnd::Update(), lldb_private::formatters::LibcxxStdSpanSyntheticFrontEnd::Update(), and lldb_private::formatters::VectorIteratorSyntheticFrontEnd::Update().
GetDesugaredSmartPointerValue()
lldb::ValueObjectSP lldb_private::formatters::GetDesugaredSmartPointerValue (ValueObject & ptr, ValueObject & container)
Return the ValueObjectSP of the underlying pointer member whose type is a desugared 'std::shared_ptr::element_type *'.
Definition at line 13 of file Generic.cpp.
References lldb_private::ValueObject::Cast(), lldb_private::ValueObject::GetCompilerType(), lldb_private::CompilerType::GetNonReferenceType(), lldb_private::ValueObject::GetSP(), and lldb_private::CompilerType::GetTypeTemplateArgument().
Referenced by lldb_private::formatters::LibcxxSharedPtrSyntheticFrontEnd::Update(), and lldb_private::formatters::MsvcStlSmartPointerSyntheticFrontEnd::Update().
GetFirstValueOfLibCXXCompressedPair()
lldb::ValueObjectSP lldb_private::formatters::GetFirstValueOfLibCXXCompressedPair (ValueObject & pair)
Definition at line 75 of file LibCxx.cpp.
References lldb_private::ValueObject::GetChildAtIndex(), and lldb_private::ValueObject::GetChildMemberWithName().
Referenced by lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::CalculateNumChildrenForOldCompressedPairLayout(), lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::CalculateNumChildrenImpl(), ExtractLibCxxStringData(), GetDataPointer(), lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::GetNodeType(), GetTreePointer(), LibcxxUniquePointerSummaryProvider(), and lldb_private::formatters::LibcxxUniquePtrSyntheticFrontEnd::Update().
GetLibCxxAtomicValue()
ValueObjectSP lldb_private::formatters::GetLibCxxAtomicValue (ValueObject & valobj)
Definition at line 53 of file LibCxxAtomic.cpp.
References lldb_private::ValueObject::GetNonSyntheticValue().
Referenced by LibCxxAtomicSummaryProvider(), and lldb_private::formatters::LibcxxStdAtomicSyntheticFrontEnd::Update().
GetOSXEpoch()
time_t lldb_private::formatters::GetOSXEpoch ()
Definition at line 1227 of file Cocoa.cpp.
Referenced by CFAbsoluteTimeSummaryProvider(), and NSDateSummaryProvider().
GetSecondValueOfLibCXXCompressedPair()
lldb::ValueObjectSP lldb_private::formatters::GetSecondValueOfLibCXXCompressedPair (ValueObject & pair)
Definition at line 89 of file LibCxx.cpp.
References lldb_private::ValueObject::GetChildAtIndex(), lldb_private::ValueObject::GetChildMemberWithName(), and lldb_private::ValueObject::GetNumChildrenIgnoringErrors().
Referenced by lldb_private::formatters::LibcxxUniquePtrSyntheticFrontEnd::Update().
GetValueOrOldCompressedPair()
std::pair< lldb::ValueObjectSP, bool > lldb_private::formatters::GetValueOrOldCompressedPair (ValueObject & obj, llvm::StringRef child_name, llvm::StringRef compressed_pair_name)
Returns the ValueObjectSP of the child of obj.
If obj has no child named child_name, returns the __compressed_pair child instead with compressed_pair_name, if one exists.
Latest libc++ wrap the compressed children in an anonymous structure. The anon_struct_idx indicates the location of this struct.
The returned boolean is true if the returned child was has an old-style libc++ __compressed_pair layout.
If no child was found returns a nullptr.
Definition at line 106 of file LibCxx.cpp.
References lldb_private::ValueObject::GetChildMemberWithName(), and isStdTemplate().
Referenced by lldb_private::formatters::LibcxxStdMapSyntheticFrontEnd::CalculateNumChildren(), lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::CalculateNumChildrenImpl(), ExtractLibCxxStringData(), GetDataPointer(), lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::GetNodeType(), GetTreePointer(), LibcxxUniquePointerSummaryProvider(), and lldb_private::formatters::LibcxxUniquePtrSyntheticFrontEnd::Update().
GetWCharByteSize()
std::optional< uint64_t > lldb_private::formatters::GetWCharByteSize (ValueObject & valobj)
Definition at line 203 of file CxxStringTypes.cpp.
References lldb::eBasicTypeWChar, lldb_private::CompilerType::GetBasicTypeFromAST(), lldb_private::CompilerType::GetByteSize(), and lldb_private::ValueObject::GetCompilerType().
Referenced by LibcxxWStringSummaryProvider(), LibcxxWStringViewSummaryProvider(), LibStdcppWStringViewSummaryProvider(), WCharStringSummaryProvider(), and WCharSummaryProvider().
IsLibCxxAtomic()
bool lldb_private::formatters::IsLibCxxAtomic (ValueObject & valobj)
Definition at line 150 of file LibCxxAtomic.cpp.
References lldb_private::ValueObject::GetNonSyntheticValue().
IsMsvcStlAtomic()
bool lldb_private::formatters::IsMsvcStlAtomic (ValueObject & valobj)
Definition at line 115 of file MsvcStlAtomic.cpp.
References lldb_private::ValueObject::GetNonSyntheticValue().
IsMsvcStlDeque()
bool lldb_private::formatters::IsMsvcStlDeque (ValueObject & valobj)
Definition at line 170 of file MsvcStlDeque.cpp.
References lldb_private::ValueObject::GetNonSyntheticValue().
Referenced by GenericDequeSyntheticFrontEndCreator().
IsMsvcStlList()
bool lldb_private::formatters::IsMsvcStlList (ValueObject & valobj)
Definition at line 640 of file GenericList.cpp.
References lldb_private::ValueObject::GetNonSyntheticValue().
Referenced by GenericForwardListSyntheticFrontEndCreator(), and GenericListSyntheticFrontEndCreator().
IsMsvcStlMapLike()
bool lldb_private::formatters::IsMsvcStlMapLike (ValueObject & valobj)
Definition at line 399 of file MsvcStlTree.cpp.
References lldb_private::ValueObject::GetChildMemberWithName().
Referenced by GenericMapLikeSyntheticFrontEndCreator().
IsMsvcStlOptional()
bool lldb_private::formatters::IsMsvcStlOptional (ValueObject & valobj)
Definition at line 155 of file GenericOptional.cpp.
References lldb_private::ValueObject::GetNonSyntheticValue().
Referenced by GenericOptionalSyntheticFrontEndCreator().
IsMsvcStlOrdering()
bool lldb_private::formatters::IsMsvcStlOrdering (ValueObject & valobj)
Definition at line 226 of file MsvcStl.cpp.
References lldb_private::ValueObject::GetCompilerType(), and lldb_private::CompilerType::GetIndexOfChildMemberWithName().
Referenced by GenericPartialOrderingSummaryProvider(), GenericStrongOrderingSummaryProvider(), and GenericWeakOrderingSummaryProvider().
IsMsvcStlSmartPointer()
bool lldb_private::formatters::IsMsvcStlSmartPointer (ValueObject & valobj)
Definition at line 17 of file MsvcStlSmartPointer.cpp.
References lldb_private::ValueObject::GetNonSyntheticValue().
Referenced by GenericSmartPointerSummaryProvider(), and GenericSmartPointerSyntheticFrontEndCreator().
IsMsvcStlSpan()
bool lldb_private::formatters::IsMsvcStlSpan (ValueObject & valobj)
Definition at line 120 of file MsvcStlSpan.cpp.
References lldb_private::ValueObject::GetNonSyntheticValue().
Referenced by GenericSpanSyntheticFrontEndCreator().
IsMsvcStlStringType()
bool lldb_private::formatters::IsMsvcStlStringType (ValueObject & valobj)
Definition at line 142 of file MsvcStl.cpp.
References lldb_private::ValueObject::GetCompilerType(), and lldb_private::CompilerType::GetIndexOfChildMemberWithName().
Referenced by LoadCommonStlFormatters().
IsMsvcStlStringViewType()
bool lldb_private::formatters::IsMsvcStlStringViewType (ValueObject & valobj)
Definition at line 148 of file MsvcStl.cpp.
References lldb_private::ValueObject::GetCompilerType(), and lldb_private::CompilerType::GetIndexOfChildMemberWithName().
Referenced by LoadCommonStlFormatters().
IsMsvcStlTreeIter()
bool lldb_private::formatters::IsMsvcStlTreeIter (ValueObject & valobj)
Definition at line 363 of file MsvcStlTree.cpp.
References lldb_private::ValueObject::GetChildMemberWithName().
IsMsvcStlTuple()
bool lldb_private::formatters::IsMsvcStlTuple (ValueObject & valobj)
Definition at line 92 of file MsvcStlTuple.cpp.
References lldb_private::ValueObject::GetNonSyntheticValue().
Referenced by GenericTupleSyntheticFrontEndCreator().
IsMsvcStlUniquePtr()
bool lldb_private::formatters::IsMsvcStlUniquePtr (ValueObject & valobj)
Definition at line 185 of file MsvcStlSmartPointer.cpp.
References lldb_private::ValueObject::GetNonSyntheticValue().
Referenced by GenericUniquePtrSummaryProvider(), and GenericUniquePtrSyntheticFrontEndCreator().
IsMsvcStlUnordered()
bool lldb_private::formatters::IsMsvcStlUnordered (ValueObject & valobj)
Definition at line 58 of file MsvcStlUnordered.cpp.
References lldb_private::ValueObject::GetNonSyntheticValue().
Referenced by GenericUnorderedSyntheticFrontEndCreator().
IsMsvcStlVariant()
bool lldb_private::formatters::IsMsvcStlVariant (ValueObject & valobj)
Definition at line 95 of file MsvcStlVariant.cpp.
References lldb_private::ValueObject::GetNonSyntheticValue().
Referenced by GenericVariantSummaryProvider(), and GenericVariantSyntheticFrontEndCreator().
IsMsvcStlVector()
bool lldb_private::formatters::IsMsvcStlVector (ValueObject & valobj)
isStdTemplate()
bool lldb_private::formatters::isStdTemplate (ConstString type_name, llvm::StringRef type)
Definition at line 54 of file LibCxx.cpp.
References consumeInlineNamespace(), and lldb_private::ConstString::GetStringRef().
Referenced by lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::GetElementType(), GetValueOrOldCompressedPair(), and isUnorderedMap().
LibCxxAtomicSummaryProvider()
bool lldb_private::formatters::LibCxxAtomicSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 70 of file LibCxxAtomic.cpp.
References GetLibCxxAtomicValue(), and lldb_private::Stream::Printf().
Referenced by LoadLibCxxFormatters().
LibcxxAtomicSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibcxxAtomicSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibCxxFormatters().
LibcxxBitsetSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibcxxBitsetSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibCxxFormatters().
LibcxxChronoLocalDaysSummaryProvider()
bool lldb_private::formatters::LibcxxChronoLocalDaysSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 905 of file LibCxx.cpp.
References LibcxxChronoTimepointDaysSummaryProvider().
Referenced by LoadLibCxxFormatters().
LibcxxChronoLocalSecondsSummaryProvider()
bool lldb_private::formatters::LibcxxChronoLocalSecondsSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 851 of file LibCxx.cpp.
References LibcxxChronoTimePointSecondsSummaryProvider().
Referenced by LoadLibCxxFormatters().
LibcxxChronoMonthSummaryProvider()
bool lldb_private::formatters::LibcxxChronoMonthSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 911 of file LibCxx.cpp.
References lldb_private::ValueObject::GetChildMemberWithName(), and lldb_private::Stream::Printf().
Referenced by LoadLibCxxFormatters().
LibcxxChronoSysDaysSummaryProvider()
bool lldb_private::formatters::LibcxxChronoSysDaysSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 899 of file LibCxx.cpp.
References LibcxxChronoTimepointDaysSummaryProvider().
Referenced by LoadLibCxxFormatters().
LibcxxChronoSysSecondsSummaryProvider()
bool lldb_private::formatters::LibcxxChronoSysSecondsSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 845 of file LibCxx.cpp.
References LibcxxChronoTimePointSecondsSummaryProvider().
Referenced by LoadLibCxxFormatters().
LibcxxChronoWeekdaySummaryProvider()
bool lldb_private::formatters::LibcxxChronoWeekdaySummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 932 of file LibCxx.cpp.
References lldb_private::ValueObject::GetChildMemberWithName(), and lldb_private::Stream::Printf().
Referenced by LoadLibCxxFormatters().
LibcxxChronoYearMonthDaySummaryProvider()
bool lldb_private::formatters::LibcxxChronoYearMonthDaySummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 953 of file LibCxx.cpp.
References lldb_private::ValueObject::GetChildMemberWithName(), and lldb_private::Stream::Printf().
Referenced by LoadLibCxxFormatters().
LibcxxFunctionSummaryProvider()
bool lldb_private::formatters::LibcxxFunctionSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 134 of file LibCxx.cpp.
References lldb_private::CPPLanguageRuntime::LibCppStdFunctionCallableInfo::callable_case, lldb_private::CPPLanguageRuntime::LibCppStdFunctionCallableInfo::callable_line_entry, lldb_private::CPPLanguageRuntime::LibCppStdFunctionCallableInfo::callable_symbol, lldb_private::CPPLanguageRuntime::CallableObject, lldb_private::CPPLanguageRuntime::FindLibCppStdFunctionCallableInfo(), lldb_private::CPPLanguageRuntime::FreeOrMemberFunction, lldb_private::CPPLanguageRuntime::Get(), lldb_private::ConstString::GetCString(), lldb_private::LineEntry::GetFile(), lldb_private::FileSpec::GetFilename(), lldb_private::Symbol::GetName(), lldb_private::ValueObject::GetNonSyntheticValue(), lldb_private::ExecutionContext::GetProcessPtr(), lldb_private::CPPLanguageRuntime::Invalid, lldb_private::CPPLanguageRuntime::Lambda, lldb_private::LineEntry::line, lldb_private::CPPLanguageRuntime::LibCppStdFunctionCallableInfo::member_f_pointer_value, and lldb_private::Stream::Printf().
Referenced by LoadLibCxxFormatters().
LibCxxMapIteratorSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibCxxMapIteratorSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibCxxFormatters().
LibcxxOptionalSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibcxxOptionalSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP valobj_sp)
Referenced by LoadLibCxxFormatters().
LibcxxPartialOrderingSummaryProvider()
bool lldb_private::formatters::LibcxxPartialOrderingSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 261 of file LibCxx.cpp.
References LibcxxExtractOrderingValue().
Referenced by LoadLibCxxFormatters().
LibcxxQueueFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibcxxQueueFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibCxxFormatters().
LibcxxSharedPtrSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibcxxSharedPtrSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibCxxFormatters().
LibcxxSmartPointerSummaryProvider()
bool lldb_private::formatters::LibcxxSmartPointerSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 182 of file LibCxx.cpp.
References DumpCxxSmartPtrPointerSummary(), lldb_private::ValueObject::GetNonSyntheticValue(), and lldb_private::Stream::Printf().
Referenced by LoadLibCxxFormatters().
LibcxxSpanSummaryProvider()
bool lldb_private::formatters::LibcxxSpanSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Formatter for libc++ std::span<>.
LibcxxStdForwardListSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibcxxStdForwardListSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibCxxFormatters().
LibcxxStdListSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibcxxStdListSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibCxxFormatters().
LibcxxStdMapSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibcxxStdMapSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibCxxFormatters().
LibcxxStdProxyArraySyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibcxxStdProxyArraySyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibCxxFormatters().
LibcxxStdRangesRefViewSyntheticFrontEndCreator()
lldb_private::SyntheticChildrenFrontEnd * lldb_private::formatters::LibcxxStdRangesRefViewSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP valobj_sp)
Definition at line 75 of file LibCxxRangesRefView.cpp.
References lldb_private::CompilerType::IsValid().
Referenced by LoadLibCxxFormatters().
LibcxxStdSliceArraySummaryProvider()
bool lldb_private::formatters::LibcxxStdSliceArraySummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 22 of file LibCxxSliceArray.cpp.
References lldb_private::ValueObject::GetNonSyntheticValue(), and lldb_private::Stream::Printf().
Referenced by LoadLibCxxFormatters().
LibcxxStdSliceArraySyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibcxxStdSliceArraySyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibCxxFormatters().
LibcxxStdSpanSyntheticFrontEndCreator()
lldb_private::SyntheticChildrenFrontEnd * lldb_private::formatters::LibcxxStdSpanSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP valobj_sp)
Definition at line 145 of file LibCxxSpan.cpp.
References lldb_private::CompilerType::GetNumTemplateArguments(), and lldb_private::CompilerType::IsValid().
Referenced by LoadLibCxxFormatters().
LibcxxStdUnorderedMapSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibCxxFormatters().
LibcxxStdValarraySyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibcxxStdValarraySyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibCxxFormatters().
LibcxxStdVectorSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibcxxStdVectorSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibCxxFormatters().
LibcxxStringSummaryProviderASCII()
bool lldb_private::formatters::LibcxxStringSummaryProviderASCII (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options)
Definition at line 688 of file LibCxx.cpp.
References formatStringImpl().
Referenced by LoadLibCxxFormatters().
LibcxxStringSummaryProviderUTF16()
bool lldb_private::formatters::LibcxxStringSummaryProviderUTF16 (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options)
Definition at line 695 of file LibCxx.cpp.
References formatStringImpl().
Referenced by LoadLibCxxFormatters().
LibcxxStringSummaryProviderUTF32()
bool lldb_private::formatters::LibcxxStringSummaryProviderUTF32 (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options)
Definition at line 702 of file LibCxx.cpp.
References formatStringImpl().
Referenced by LoadLibCxxFormatters().
LibcxxStringViewSummaryProviderASCII()
bool lldb_private::formatters::LibcxxStringViewSummaryProviderASCII (ValueObject & valueObj, Stream & stream, const TypeSummaryOptions & summary_options)
Definition at line 748 of file LibCxx.cpp.
References formatStringViewImpl().
Referenced by LoadLibCxxFormatters().
LibcxxStringViewSummaryProviderUTF16()
bool lldb_private::formatters::LibcxxStringViewSummaryProviderUTF16 (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options)
Definition at line 755 of file LibCxx.cpp.
References formatStringViewImpl().
Referenced by LoadLibCxxFormatters().
LibcxxStringViewSummaryProviderUTF32()
bool lldb_private::formatters::LibcxxStringViewSummaryProviderUTF32 (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options)
Definition at line 762 of file LibCxx.cpp.
References formatStringViewImpl().
Referenced by LoadLibCxxFormatters().
LibcxxStrongOrderingSummaryProvider()
bool lldb_private::formatters::LibcxxStrongOrderingSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 306 of file LibCxx.cpp.
References LibcxxExtractOrderingValue().
Referenced by LoadLibCxxFormatters().
LibcxxTupleFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibcxxTupleFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibCxxFormatters().
LibcxxUniquePointerSummaryProvider()
bool lldb_private::formatters::LibcxxUniquePointerSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 228 of file LibCxx.cpp.
References DumpCxxSmartPtrPointerSummary(), GetFirstValueOfLibCXXCompressedPair(), lldb_private::ValueObject::GetNonSyntheticValue(), and GetValueOrOldCompressedPair().
Referenced by LoadLibCxxFormatters().
LibcxxUniquePtrSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibcxxUniquePtrSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibCxxFormatters().
LibCxxUnorderedMapIteratorSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibCxxUnorderedMapIteratorSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibCxxFormatters().
LibcxxVariantFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibcxxVariantFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP valobj_sp)
Referenced by LoadLibCxxFormatters().
LibcxxVariantSummaryProvider()
bool lldb_private::formatters::LibcxxVariantSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 147 of file LibCxxVariant.cpp.
References GetChildMemberWithName(), lldb_private::CompilerType::GetDisplayTypeName(), lldb_private::ValueObject::GetNonSyntheticValue(), lldb_private::CompilerType::GetTypeTemplateArgument(), and lldb_private::Stream::Printf().
Referenced by LoadLibCxxFormatters().
LibcxxVectorBoolSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibcxxVectorBoolSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
LibCxxVectorIteratorSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibCxxVectorIteratorSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibCxxFormatters().
LibcxxWeakOrderingSummaryProvider()
bool lldb_private::formatters::LibcxxWeakOrderingSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 285 of file LibCxx.cpp.
References LibcxxExtractOrderingValue().
Referenced by LoadLibCxxFormatters().
LibcxxWStringSummaryProvider()
bool lldb_private::formatters::LibcxxWStringSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 631 of file LibCxx.cpp.
References ExtractLibcxxStringInfo(), GetWCharByteSize(), and StringBufferSummaryProvider().
Referenced by LoadLibCxxFormatters().
LibcxxWStringViewSummaryProvider()
bool lldb_private::formatters::LibcxxWStringViewSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 769 of file LibCxx.cpp.
References GetWCharByteSize(), LibcxxExtractStringViewData(), and StringBufferSummaryProvider().
Referenced by LoadLibCxxFormatters().
LibStdcppBitsetSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibStdcppBitsetSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibStdcppFormatters().
LibstdcppMapIteratorSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibstdcppMapIteratorSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibStdcppFormatters().
LibStdcppOptionalSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibStdcppOptionalSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by GenericOptionalSyntheticFrontEndCreator().
LibStdcppPartialOrderingSummaryProvider()
bool lldb_private::formatters::LibStdcppPartialOrderingSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 510 of file LibStdcpp.cpp.
References LibStdcppExtractOrderingValue().
Referenced by GenericPartialOrderingSummaryProvider().
LibStdcppSharedPtrSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibStdcppSharedPtrSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by GenericSmartPointerSyntheticFrontEndCreator().
LibStdcppSmartPointerSummaryProvider()
bool lldb_private::formatters::LibStdcppSmartPointerSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 407 of file LibStdcpp.cpp.
References DumpCxxSmartPtrPointerSummary(), lldb_private::ValueObject::GetNonSyntheticValue(), and lldb_private::Stream::Printf().
Referenced by GenericSmartPointerSummaryProvider().
LibStdcppSpanSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibStdcppSpanSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP valobj_sp)
Definition at line 102 of file LibStdcppSpan.cpp.
References lldb_private::CompilerType::GetNumTemplateArguments().
Referenced by GenericSpanSyntheticFrontEndCreator().
LibStdcppStringSummaryProvider()
bool lldb_private::formatters::LibStdcppStringSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 240 of file LibStdcpp.cpp.
References lldb_private::ValueObject::GetChildAtNamePath().
Referenced by LoadCommonStlFormatters(), and LoadLibStdcppFormatters().
LibStdcppStringViewSummaryProvider()
template<StringPrinter::StringElementType element_type> bool lldb_private::formatters::LibStdcppStringViewSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 314 of file LibStdcpp.cpp.
References formatStringViewImpl(), and getPrefixToken().
Referenced by lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::ASCII >(), lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::UTF16 >(), lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::UTF32 >(), and lldb_private::formatters::LibStdcppStringViewSummaryProvider< StringElementType::UTF8 >().
LibStdcppStrongOrderingSummaryProvider()
bool lldb_private::formatters::LibStdcppStrongOrderingSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 556 of file LibStdcpp.cpp.
References LibStdcppExtractOrderingValue().
Referenced by GenericStrongOrderingSummaryProvider().
LibStdcppTupleSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibStdcppTupleSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by GenericTupleSyntheticFrontEndCreator().
LibStdcppUniquePointerSummaryProvider()
bool lldb_private::formatters::LibStdcppUniquePointerSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 169 of file LibStdcppUniquePointer.cpp.
References lldb_private::ValueObject::GetSP().
Referenced by GenericUniquePtrSummaryProvider().
LibStdcppUniquePtrSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibStdcppUniquePtrSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by GenericUniquePtrSyntheticFrontEndCreator(), and LoadLibStdcppFormatters().
LibStdcppVariantSummaryProvider()
bool lldb_private::formatters::LibStdcppVariantSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 463 of file LibStdcpp.cpp.
References lldb_private::ValueObject::GetNonSyntheticValue(), LibStdcppVariantNposValue(), and lldb_private::Stream::Printf().
Referenced by GenericVariantSummaryProvider().
LibStdcppVectorIteratorSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::LibStdcppVectorIteratorSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibStdcppFormatters().
LibStdcppWeakOrderingSummaryProvider()
bool lldb_private::formatters::LibStdcppWeakOrderingSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 535 of file LibStdcpp.cpp.
References LibStdcppExtractOrderingValue().
Referenced by GenericWeakOrderingSummaryProvider().
LibStdcppWStringViewSummaryProvider()
bool lldb_private::formatters::LibStdcppWStringViewSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 278 of file LibStdcpp.cpp.
References formatStringViewImpl(), and GetWCharByteSize().
Referenced by LoadCommonStlFormatters().
MsvcStlAtomicSummaryProvider()
bool lldb_private::formatters::MsvcStlAtomicSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 100 of file MsvcStlAtomic.cpp.
References lldb_private::ValueObject::GetSyntheticValue().
Referenced by LoadMsvcStlFormatters().
MsvcStlAtomicSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::MsvcStlAtomicSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP valobj_sp)
Referenced by LoadMsvcStlFormatters().
MsvcStlDequeSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::MsvcStlDequeSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP valobj_sp)
Referenced by GenericDequeSyntheticFrontEndCreator().
MsvcStlForwardListSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::MsvcStlForwardListSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP valobj_sp)
Referenced by GenericForwardListSyntheticFrontEndCreator().
MsvcStlListSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::MsvcStlListSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP valobj_sp)
Referenced by GenericListSyntheticFrontEndCreator().
MsvcStlMapLikeSyntheticFrontEndCreator()
lldb_private::SyntheticChildrenFrontEnd * lldb_private::formatters::MsvcStlMapLikeSyntheticFrontEndCreator (lldb::ValueObjectSP valobj_sp)
Referenced by GenericMapLikeSyntheticFrontEndCreator().
MsvcStlOptionalSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::MsvcStlOptionalSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP valobj_sp)
Referenced by GenericOptionalSyntheticFrontEndCreator().
MsvcStlPartialOrderingSummaryProvider()
bool lldb_private::formatters::MsvcStlPartialOrderingSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 243 of file MsvcStl.cpp.
References MsvcStlExtractOrderingValue().
Referenced by GenericPartialOrderingSummaryProvider().
MsvcStlSmartPointerSummaryProvider()
bool lldb_private::formatters::MsvcStlSmartPointerSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 24 of file MsvcStlSmartPointer.cpp.
References DumpCxxSmartPtrPointerSummary(), lldb_private::ValueObject::GetNonSyntheticValue(), and lldb_private::Stream::Printf().
Referenced by GenericSmartPointerSummaryProvider().
MsvcStlSmartPointerSyntheticFrontEndCreator()
lldb_private::SyntheticChildrenFrontEnd * lldb_private::formatters::MsvcStlSmartPointerSyntheticFrontEndCreator (lldb::ValueObjectSP valobj_sp)
Referenced by GenericSmartPointerSyntheticFrontEndCreator().
MsvcStlSpanSyntheticFrontEndCreator()
lldb_private::SyntheticChildrenFrontEnd * lldb_private::formatters::MsvcStlSpanSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP valobj_sp)
Definition at line 127 of file MsvcStlSpan.cpp.
Referenced by GenericSpanSyntheticFrontEndCreator().
MsvcStlStringSummaryProvider()
template<StringPrinter::StringElementType element_type> bool lldb_private::formatters::MsvcStlStringSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options)
Referenced by lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::ASCII >(), lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::UTF16 >(), lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::UTF32 >(), lldb_private::formatters::MsvcStlStringSummaryProvider< StringElementType::UTF8 >(), and LoadMsvcStlFormatters().
MsvcStlStringViewSummaryProvider()
template<StringPrinter::StringElementType element_type> bool lldb_private::formatters::MsvcStlStringViewSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & summary_options)
Referenced by lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::ASCII >(), lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::UTF16 >(), lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::UTF32 >(), and lldb_private::formatters::MsvcStlStringViewSummaryProvider< StringElementType::UTF8 >().
MsvcStlStrongOrderingSummaryProvider()
bool lldb_private::formatters::MsvcStlStrongOrderingSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 288 of file MsvcStl.cpp.
References MsvcStlExtractOrderingValue().
Referenced by GenericStrongOrderingSummaryProvider().
MsvcStlTreeIterSummaryProvider()
bool lldb_private::formatters::MsvcStlTreeIterSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 367 of file MsvcStlTree.cpp.
References lldb_private::ValueObject::GetNonSyntheticValue(), and lldb_private::Stream::Printf().
Referenced by LoadMsvcStlFormatters().
MsvcStlTreeIterSyntheticFrontEndCreator()
lldb_private::SyntheticChildrenFrontEnd * lldb_private::formatters::MsvcStlTreeIterSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP valobj_sp)
Referenced by LoadMsvcStlFormatters().
MsvcStlTupleSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::MsvcStlTupleSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP valobj_sp)
Referenced by GenericTupleSyntheticFrontEndCreator().
MsvcStlUniquePtrSummaryProvider()
bool lldb_private::formatters::MsvcStlUniquePtrSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 192 of file MsvcStlSmartPointer.cpp.
References DumpCxxSmartPtrPointerSummary(), and lldb_private::ValueObject::GetNonSyntheticValue().
Referenced by GenericUniquePtrSummaryProvider().
MsvcStlUniquePtrSyntheticFrontEndCreator()
lldb_private::SyntheticChildrenFrontEnd * lldb_private::formatters::MsvcStlUniquePtrSyntheticFrontEndCreator (lldb::ValueObjectSP valobj_sp)
Referenced by GenericUniquePtrSyntheticFrontEndCreator().
MsvcStlUnorderedSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::MsvcStlUnorderedSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP valobj_sp)
Referenced by GenericUnorderedSyntheticFrontEndCreator().
MsvcStlVariantSummaryProvider()
bool lldb_private::formatters::MsvcStlVariantSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 102 of file MsvcStlVariant.cpp.
References lldb_private::CompilerType::GetDisplayTypeName(), lldb_private::ValueObject::GetNonSyntheticValue(), lldb_private::CompilerType::GetTypedefedType(), lldb_private::CompilerType::GetTypeTemplateArgument(), lldb_private::CompilerType::IsTypedefType(), and lldb_private::Stream::Printf().
Referenced by GenericVariantSummaryProvider().
MsvcStlVariantSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::MsvcStlVariantSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP valobj_sp)
Referenced by GenericVariantSyntheticFrontEndCreator().
MsvcStlVectorSyntheticFrontEndCreator()
lldb_private::SyntheticChildrenFrontEnd * lldb_private::formatters::MsvcStlVectorSyntheticFrontEndCreator (lldb::ValueObjectSP valobj_sp)
Referenced by GenericVectorSyntheticFrontEndCreator().
MsvcStlWeakOrderingSummaryProvider()
bool lldb_private::formatters::MsvcStlWeakOrderingSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 267 of file MsvcStl.cpp.
References MsvcStlExtractOrderingValue().
Referenced by GenericWeakOrderingSummaryProvider().
MsvcStlWStringSummaryProvider()
bool lldb_private::formatters::MsvcStlWStringSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 154 of file MsvcStl.cpp.
References formatStringImpl().
Referenced by LoadCommonStlFormatters().
MsvcStlWStringViewSummaryProvider()
bool lldb_private::formatters::MsvcStlWStringViewSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 190 of file MsvcStl.cpp.
References formatStringViewImpl().
Referenced by LoadCommonStlFormatters().
NSArraySummaryProvider()
bool lldb_private::formatters::NSArraySummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 329 of file NSArray.cpp.
References lldb_private::formatters::Foundation1437::__NSArrayMSize(), lldb_private::formatters::Foundation1436::__NSFrozenArrayMSize(), error(), lldb_private::Language::FindPlugin(), lldb_private::ObjCLanguageRuntime::Get(), lldb_private::formatters::NSArray_Additionals::GetAdditionalSummaries(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), lldb_private::AppleObjCRuntime::GetFoundationVersion(), lldb_private::TypeSummaryOptions::GetLanguage(), lldb_private::ValueObject::GetProcessSP(), lldb_private::ValueObject::GetValueAsUnsigned(), lldb_private::ConstString::IsEmpty(), and lldb_private::Stream::Printf().
Referenced by LoadObjCFormatters().
NSArraySyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::NSArraySyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadObjCFormatters().
NSAttributedStringSummaryProvider()
bool lldb_private::formatters::NSAttributedStringSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 283 of file NSString.cpp.
References lldb_private::ValueObject::CreateValueObjectFromAddress(), error(), lldb_private::ValueObject::GetCompilerType(), lldb_private::ValueObject::GetTargetSP(), lldb_private::ValueObject::GetValueAsUnsigned(), and NSStringSummaryProvider().
Referenced by LoadObjCFormatters(), and NSMutableAttributedStringSummaryProvider().
NSBundleSummaryProvider()
bool lldb_private::formatters::NSBundleSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 38 of file Cocoa.cpp.
References lldb::eBasicTypeObjCID, lldb_private::ObjCLanguageRuntime::Get(), lldb_private::CompilerType::GetBasicTypeFromAST(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), lldb_private::ValueObject::GetCompilerType(), lldb_private::StreamString::GetData(), lldb_private::ValueObject::GetProcessSP(), lldb_private::StreamString::GetSize(), lldb_private::ValueObject::GetSyntheticChildAtOffset(), lldb_private::ValueObject::GetValueAsUnsigned(), NSStringSummaryProvider(), and lldb_private::Stream::Printf().
Referenced by LoadObjCFormatters().
NSDataSummaryProvider()
template<bool needs_at> bool lldb_private::formatters::NSDataSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 1065 of file Cocoa.cpp.
References error(), lldb_private::ObjCLanguageRuntime::Get(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), lldb_private::ValueObject::GetProcessSP(), lldb_private::ValueObject::GetValueAsUnsigned(), and lldb_private::Stream::Printf().
Referenced by LoadObjCFormatters().
NSDataSummaryProvider< false >()
template bool lldb_private::formatters::NSDataSummaryProvider< false > (ValueObject & , Stream & , const TypeSummaryOptions &) extern
NSDataSummaryProvider< true >()
template bool lldb_private::formatters::NSDataSummaryProvider< true > (ValueObject & , Stream & , const TypeSummaryOptions &) extern
NSDateSummaryProvider()
bool lldb_private::formatters::NSDateSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 902 of file Cocoa.cpp.
References decodeTaggedTimeInterval(), error(), lldb_private::ObjCLanguageRuntime::Get(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), GetOSXEpoch(), lldb_private::ValueObject::GetProcessSP(), lldb_private::ValueObject::GetValueAsUnsigned(), lldb_private::ConstString::IsEmpty(), and lldb_private::Stream::Printf().
Referenced by LoadObjCFormatters().
NSDecimalNumberSummaryProvider()
bool lldb_private::formatters::NSDecimalNumberSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 729 of file Cocoa.cpp.
References error(), lldb_private::ValueObject::GetProcessSP(), lldb_private::ValueObject::GetValueAsUnsigned(), and lldb_private::Stream::Printf().
Referenced by NSNumberSummaryProvider().
NSDictionarySummaryProvider()
template<bool name_entries> bool lldb_private::formatters::NSDictionarySummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 398 of file NSDictionary.cpp.
References lldb_private::formatters::Foundation1437::__NSDictionaryMSize(), error(), lldb_private::Language::FindPlugin(), lldb_private::ObjCLanguageRuntime::Get(), lldb_private::formatters::NSDictionary_Additionals::GetAdditionalSummaries(), lldb_private::CFBasicHash::GetCount(), lldb_private::AppleObjCRuntime::GetFoundationVersion(), lldb_private::TypeSummaryOptions::GetLanguage(), lldb_private::ObjCLanguageRuntime::GetNonKVOClassDescriptor(), lldb_private::ValueObject::GetProcessSP(), lldb_private::ValueObject::GetValueAsUnsigned(), lldb_private::ConstString::IsEmpty(), lldb_private::Stream::Printf(), and lldb_private::CFBasicHash::Update().
Referenced by LoadObjCFormatters().
NSDictionarySummaryProvider< false >()
template bool lldb_private::formatters::NSDictionarySummaryProvider< false > (ValueObject & , Stream & , const TypeSummaryOptions &) extern
NSDictionarySummaryProvider< true >()
template bool lldb_private::formatters::NSDictionarySummaryProvider< true > (ValueObject & , Stream & , const TypeSummaryOptions &) extern
NSDictionarySyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::NSDictionarySyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadObjCFormatters().
NSError_SummaryProvider()
bool lldb_private::formatters::NSError_SummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 54 of file NSError.cpp.
References lldb_private::ValueObject::CreateValueObjectFromData(), DerefToNSErrorPointer(), lldb::eBasicTypeVoid, lldb_private::StreamString::Empty(), error(), lldb_private::formatters::InferiorSizedWord::GetAsData(), lldb_private::StreamString::GetData(), lldb_private::ValueObject::GetExecutionContextRef(), lldb_private::ScratchTypeSystemClang::GetForTarget(), lldb_private::ValueObject::GetProcessSP(), LLDB_INVALID_ADDRESS, NSStringSummaryProvider(), and lldb_private::Stream::Printf().
Referenced by LoadObjCFormatters().
NSErrorSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::NSErrorSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP valobj_sp)
Referenced by LoadObjCFormatters().
NSException_SummaryProvider()
bool lldb_private::formatters::NSException_SummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 99 of file NSException.cpp.
References lldb_private::StreamString::Empty(), ExtractFields(), lldb_private::StreamString::GetData(), NSStringSummaryProvider(), and lldb_private::Stream::Printf().
Referenced by LoadObjCFormatters().
NSExceptionSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::NSExceptionSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP valobj_sp)
Referenced by LoadObjCFormatters().
NSIndexPathSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::NSIndexPathSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP valobj_sp)
Definition at line 318 of file NSIndexPath.cpp.
Referenced by LoadObjCFormatters().
NSIndexSetSummaryProvider()
bool lldb_private::formatters::NSIndexSetSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 233 of file Cocoa.cpp.
References error(), lldb_private::ObjCLanguageRuntime::Get(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), lldb_private::AppleObjCRuntime::GetFoundationVersion(), lldb_private::ValueObject::GetProcessSP(), lldb_private::ValueObject::GetValueAsUnsigned(), and lldb_private::Stream::Printf().
Referenced by LoadObjCFormatters().
NSIndirectTaggedString_SummaryProvider()
bool lldb_private::formatters::NSIndirectTaggedString_SummaryProvider (ValueObject & valobj, ObjCLanguageRuntime::ClassDescriptorSP descriptor, Stream & stream, const TypeSummaryOptions & summary_options)
Definition at line 377 of file NSString.cpp.
References lldb_private::Status::Fail(), lldb_private::Language::FindPlugin(), lldb_private::Stream::Format(), lldb_private::TypeSummaryOptions::GetLanguage(), lldb_private::ValueObject::GetProcessSP(), and lldb_private::Stream::PutCString().
Referenced by NSStringSummaryProvider().
NSMachPortSummaryProvider()
bool lldb_private::formatters::NSMachPortSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 187 of file Cocoa.cpp.
References error(), lldb_private::ObjCLanguageRuntime::Get(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), lldb_private::ValueObject::GetProcessSP(), lldb_private::ValueObject::GetValueAsUnsigned(), and lldb_private::Stream::Printf().
Referenced by LoadObjCFormatters().
NSMutableAttributedStringSummaryProvider()
bool lldb_private::formatters::NSMutableAttributedStringSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 312 of file NSString.cpp.
References NSAttributedStringSummaryProvider().
Referenced by LoadObjCFormatters().
NSNotificationSummaryProvider()
bool lldb_private::formatters::NSNotificationSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 138 of file Cocoa.cpp.
References lldb_private::ObjCLanguageRuntime::Get(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), lldb_private::ValueObject::GetCompilerType(), lldb_private::StreamString::GetData(), lldb_private::ValueObject::GetProcessSP(), lldb_private::StreamString::GetSize(), lldb_private::ValueObject::GetSyntheticChildAtOffset(), lldb_private::ValueObject::GetValueAsUnsigned(), NSStringSummaryProvider(), and lldb_private::Stream::Printf().
Referenced by LoadObjCFormatters().
NSNumberSummaryProvider()
bool lldb_private::formatters::NSNumberSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 436 of file Cocoa.cpp.
References _C_CHR, _C_INT, _C_LNG, _C_LNG_LNG, _C_SHT, _C_UCHR, _C_UINT, _C_ULNG, _C_ULNG_LNG, _C_USHT, lldb_private::DataFormatters, error(), lldb_private::ObjCLanguageRuntime::Get(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), lldb_private::AppleObjCRuntime::GetFoundationVersion(), lldb_private::TypeSummaryOptions::GetLanguage(), lldb_private::GetLog(), lldb_private::ValueObject::GetProcessSP(), lldb_private::ValueObject::GetValueAsUnsigned(), NSDecimalNumberSummaryProvider(), NSNumber_FormatChar(), NSNumber_FormatDouble(), NSNumber_FormatFloat(), NSNumber_FormatInt(), NSNumber_FormatInt128(), NSNumber_FormatLong(), NSNumber_FormatShort(), ObjCBooleanSummaryProvider(), lldb_private::Log::Printf(), and lldb_private::Stream::Printf().
Referenced by LoadObjCFormatters().
NSSetSummaryProvider()
template<bool cf_style> template bool lldb_private::formatters::NSSetSummaryProvider< false > (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 227 of file NSSet.cpp.
References lldb_private::formatters::Foundation1437::__NSSetMSize(), error(), lldb_private::Language::FindPlugin(), lldb_private::ObjCLanguageRuntime::Get(), lldb_private::formatters::NSSet_Additionals::GetAdditionalSummaries(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), lldb_private::CFBasicHash::GetCount(), lldb_private::AppleObjCRuntime::GetFoundationVersion(), lldb_private::TypeSummaryOptions::GetLanguage(), lldb_private::ValueObject::GetProcessSP(), lldb_private::ValueObject::GetValueAsUnsigned(), lldb_private::ConstString::IsEmpty(), lldb_private::Stream::Printf(), and lldb_private::CFBasicHash::Update().
Referenced by LoadObjCFormatters().
NSSetSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::NSSetSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadObjCFormatters().
NSStringSummaryProvider()
bool lldb_private::formatters::NSStringSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 33 of file NSString.cpp.
References lldb::eBasicTypeUnsignedInt, lldb::eByteOrderLittle, error(), lldb::eTypeSummaryUncapped, lldb_private::Language::FindPlugin(), lldb_private::ObjCLanguageRuntime::Get(), lldb_private::formatters::NSString_Additionals::GetAdditionalSummaries(), lldb_private::CompilerType::GetBasicTypeFromAST(), lldb_private::TypeSummaryOptions::GetCapping(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), lldb_private::ValueObject::GetCompilerType(), lldb_private::ConstString::GetCString(), lldb_private::TypeSummaryOptions::GetLanguage(), lldb_private::ValueObject::GetProcessSP(), lldb_private::ConstString::GetStringRef(), lldb_private::ValueObject::GetSyntheticChildAtOffset(), lldb_private::ValueObject::GetTargetSP(), lldb_private::ValueObject::GetValueAsUnsigned(), NSIndirectTaggedString_SummaryProvider(), NSTaggedString_SummaryProvider(), lldb_private::Stream::Printf(), lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetBinaryZeroIsTerminator(), lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::SetHasSourceSize(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetIgnoreMaxLength(), lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::SetLocation(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetNeedsZeroTermination(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetPrefixToken(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetQuote(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetSourceSize(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetStream(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetSuffixToken(), and lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::SetTargetSP().
Referenced by lldb_private::AppleObjCRuntime::GetBacktraceThreadFromException(), LoadObjCFormatters(), NSAttributedStringSummaryProvider(), NSBundleSummaryProvider(), NSError_SummaryProvider(), NSException_SummaryProvider(), NSNotificationSummaryProvider(), NSTimeZoneSummaryProvider(), and NSURLSummaryProvider().
NSTaggedString_SummaryProvider()
bool lldb_private::formatters::NSTaggedString_SummaryProvider (ValueObject & valobj, ObjCLanguageRuntime::ClassDescriptorSP descriptor, Stream & stream, const TypeSummaryOptions & summary_options)
Definition at line 317 of file NSString.cpp.
References lldb_private::Language::FindPlugin(), lldb_private::TypeSummaryOptions::GetLanguage(), and lldb_private::Stream::Printf().
Referenced by NSStringSummaryProvider().
NSTimeZoneSummaryProvider()
bool lldb_private::formatters::NSTimeZoneSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 89 of file Cocoa.cpp.
References lldb_private::ObjCLanguageRuntime::Get(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), lldb_private::ValueObject::GetCompilerType(), lldb_private::StreamString::GetData(), lldb_private::ValueObject::GetProcessSP(), lldb_private::StreamString::GetSize(), lldb_private::ValueObject::GetSyntheticChildAtOffset(), lldb_private::ValueObject::GetValueAsUnsigned(), NSStringSummaryProvider(), and lldb_private::Stream::Printf().
Referenced by LoadObjCFormatters().
NSURLSummaryProvider()
bool lldb_private::formatters::NSURLSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 778 of file Cocoa.cpp.
References lldb_private::StreamString::Clear(), lldb_private::StreamString::Empty(), lldb_private::Language::FindPlugin(), lldb_private::ObjCLanguageRuntime::Get(), lldb_private::ObjCLanguageRuntime::GetClassDescriptor(), lldb_private::ValueObject::GetCompilerType(), lldb_private::TypeSummaryOptions::GetLanguage(), lldb_private::ValueObject::GetProcessSP(), lldb_private::StreamString::GetString(), lldb_private::ValueObject::GetSyntheticChildAtOffset(), lldb_private::ValueObject::GetValueAsUnsigned(), NSStringSummaryProvider(), NSURLSummaryProvider(), and UNUSED_IF_ASSERT_DISABLED.
Referenced by LoadObjCFormatters(), and NSURLSummaryProvider().
ObjCBooleanSummaryProvider()
bool lldb_private::formatters::ObjCBooleanSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 1159 of file Cocoa.cpp.
References lldb_private::ObjCLanguageRuntime::Get(), lldb_private::ValueObject::GetProcessSP(), lldb_private::ValueObject::GetValueAsUnsigned(), LLDB_INVALID_ADDRESS, and lldb_private::Stream::PutCString().
Referenced by NSNumberSummaryProvider().
ObjCBOOLSummaryProvider()
bool lldb_private::formatters::ObjCBOOLSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 1128 of file Cocoa.cpp.
References lldb_private::ValueObject::Dereference(), lldb_private::Status::Fail(), lldb_private::ValueObject::GetChildAtIndex(), lldb_private::ValueObject::GetCompilerType(), lldb_private::ValueObject::GetSP(), lldb_private::CompilerType::GetTypeInfo(), and lldb_private::Stream::Printf().
Referenced by LoadObjCFormatters().
ObjCClassSummaryProvider()
bool lldb_private::formatters::ObjCClassSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 1004 of file Cocoa.cpp.
References lldb_private::ConstString::AsCString(), lldb_private::ObjCLanguageRuntime::Get(), lldb_private::ObjCLanguageRuntime::GetClassDescriptorFromISA(), lldb_private::ValueObject::GetProcessSP(), lldb_private::ValueObject::GetValueAsUnsigned(), lldb_private::ConstString::IsEmpty(), and lldb_private::Stream::Printf().
Referenced by LoadObjCFormatters().
ObjCClassSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::ObjCClassSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadObjCFormatters().
ObjCSELSummaryProvider()
template<bool is_sel_ptr> bool lldb_private::formatters::ObjCSELSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 1189 of file Cocoa.cpp.
References lldb_private::ValueObject::CreateValueObjectFromAddress(), lldb_private::ValueObject::CreateValueObjectFromData(), lldb::eBasicTypeChar, error(), lldb_private::CompilerType::GetBasicTypeFromAST(), lldb_private::ValueObject::GetCompilerType(), lldb_private::ValueObject::GetData(), lldb_private::ValueObject::GetExecutionContextRef(), lldb_private::CompilerType::GetPointerType(), lldb_private::ValueObject::GetValueAsUnsigned(), LLDB_INVALID_ADDRESS, and lldb_private::Stream::Printf().
Referenced by LoadObjCFormatters().
ObjCSELSummaryProvider< false >()
template bool lldb_private::formatters::ObjCSELSummaryProvider< false > (ValueObject & , Stream & , const TypeSummaryOptions &) extern
ObjCSELSummaryProvider< true >()
template bool lldb_private::formatters::ObjCSELSummaryProvider< true > (ValueObject & , Stream & , const TypeSummaryOptions &) extern
ReadEncodedBufferAndDumpToStream()
template<typename SourceDataType> bool lldb_private::formatters::ReadEncodedBufferAndDumpToStream (StringElementType elem_type, const StringPrinter::ReadStringAndDumpToStreamOptions & options, llvm::ConversionResult(* ConvertFunction)(const SourceDataType **, const SourceDataType *, llvm::UTF8 **, llvm::UTF8 *, llvm::ConversionFlags)) static
Definition at line 396 of file StringPrinter.cpp.
References DumpEncodedBufferToStream(), error(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetIgnoreMaxLength(), lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::GetLocation(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetNeedsZeroTermination(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetSourceSize(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetStream(), lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::GetTargetSP(), lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::HasSourceSize(), LLDB_INVALID_ADDRESS, lldb_private::Stream::Printf(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetBinaryZeroIsTerminator(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::SetData(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::SetIsTruncated(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetNeedsZeroTermination(), and lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetSourceSize().
Referenced by StringPrinter::ReadStringAndDumpToStream< StringElementType::ASCII >(), StringPrinter::ReadStringAndDumpToStream< StringElementType::UTF16 >(), StringPrinter::ReadStringAndDumpToStream< StringElementType::UTF32 >(), and StringPrinter::ReadStringAndDumpToStream< StringElementType::UTF8 >().
StdlibCoroutineHandleSummaryProvider()
bool lldb_private::formatters::StdlibCoroutineHandleSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Summary provider for std::coroutine_handle<T> from libc++, libstdc++ and MSVC STL.
Definition at line 84 of file Coroutines.cpp.
References GetCoroFramePtrFromHandle(), lldb_private::ValueObject::GetNonSyntheticValue(), LLDB_INVALID_ADDRESS, and lldb_private::Stream::Printf().
Referenced by LoadLibCxxFormatters(), and LoadLibStdcppFormatters().
StdlibCoroutineHandleSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::StdlibCoroutineHandleSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by LoadLibCxxFormatters(), and LoadLibStdcppFormatters().
StringBufferSummaryProvider()
template<StringPrinter::StringElementType element_type> bool lldb_private::formatters::StringBufferSummaryProvider (Stream & stream, const TypeSummaryOptions & summary_options, lldb::ValueObjectSP location_sp, uint64_t size, std::string prefix_token)
Print a summary for a string buffer to stream.
Parameters
[in] stream The output stream to print the summary to.
[in] summary_options Options for printing the string contents. This function respects the capping.
[in] location_sp ValueObject of a pointer to the string being printed.
[in] size The size of the buffer pointed to by location_sp.
[in] prefix_token A prefix before the double quotes (e.g. 'u' results in u"...").
Returns
Returns whether the string buffer was successfully printed.
Referenced by formatStringViewImpl(), formatStringViewImpl(), formatStringViewImpl(), LibcxxStringSummaryProvider(), LibcxxWStringSummaryProvider(), LibcxxWStringViewSummaryProvider(), lldb_private::formatters::StringBufferSummaryProvider< StringElementType::ASCII >(), lldb_private::formatters::StringBufferSummaryProvider< StringElementType::UTF16 >(), lldb_private::formatters::StringBufferSummaryProvider< StringElementType::UTF32 >(), lldb_private::formatters::StringBufferSummaryProvider< StringElementType::UTF8 >(), and MsvcStlStringSummaryProviderImpl().
StringPrinter::ReadBufferAndDumpToStream< StringElementType::ASCII >()
template<> bool lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream< StringElementType::ASCII > (const ReadBufferAndDumpToStreamOptions & options)
Definition at line 543 of file StringPrinter.cpp.
References lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream(), and StringPrinter::ReadBufferAndDumpToStream< StringElementType::UTF8 >().
StringPrinter::ReadBufferAndDumpToStream< StringElementType::UTF16 >()
template<> bool lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream< StringElementType::UTF16 > (const ReadBufferAndDumpToStreamOptions & options)
Definition at line 529 of file StringPrinter.cpp.
References DumpEncodedBufferToStream(), and lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream().
StringPrinter::ReadBufferAndDumpToStream< StringElementType::UTF32 >()
template<> bool lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream< StringElementType::UTF32 > (const ReadBufferAndDumpToStreamOptions & options)
Definition at line 536 of file StringPrinter.cpp.
References DumpEncodedBufferToStream(), and lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream().
StringPrinter::ReadBufferAndDumpToStream< StringElementType::UTF8 >()
template<> bool lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream< StringElementType::UTF8 > (const ReadBufferAndDumpToStreamOptions & options)
Definition at line 522 of file StringPrinter.cpp.
References DumpEncodedBufferToStream(), and lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream().
Referenced by StringPrinter::ReadBufferAndDumpToStream< StringElementType::ASCII >().
StringPrinter::ReadStringAndDumpToStream< StringElementType::ASCII >()
template<> bool lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream< StringElementType::ASCII > (const ReadStringAndDumpToStreamOptions & options)
Definition at line 515 of file StringPrinter.cpp.
References ReadEncodedBufferAndDumpToStream(), and lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream().
StringPrinter::ReadStringAndDumpToStream< StringElementType::UTF16 >()
template<> bool lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream< StringElementType::UTF16 > (const ReadStringAndDumpToStreamOptions & options)
Definition at line 501 of file StringPrinter.cpp.
References ReadEncodedBufferAndDumpToStream(), and lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream().
StringPrinter::ReadStringAndDumpToStream< StringElementType::UTF32 >()
template<> bool lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream< StringElementType::UTF32 > (const ReadStringAndDumpToStreamOptions & options)
Definition at line 508 of file StringPrinter.cpp.
References ReadEncodedBufferAndDumpToStream(), and lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream().
StringPrinter::ReadStringAndDumpToStream< StringElementType::UTF8 >()
template<> bool lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream< StringElementType::UTF8 > (const ReadStringAndDumpToStreamOptions & options)
Definition at line 494 of file StringPrinter.cpp.
References ReadEncodedBufferAndDumpToStream(), and lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream().
VectorTypeSummaryProvider()
bool lldb_private::formatters::VectorTypeSummaryProvider (ValueObject & valobj, Stream & s, const TypeSummaryOptions &)
Definition at line 297 of file VectorType.cpp.
References lldb::eDynamicDontRunTarget, lldb_private::ValueObject::GetSP(), lldb_private::Stream::Printf(), lldb_private::Stream::PutChar(), and VectorTypeSyntheticFrontEndCreator().
Referenced by lldb_private::CPlusPlusLanguage::GetHardcodedSummaries().
VectorTypeSyntheticFrontEndCreator()
SyntheticChildrenFrontEnd * lldb_private::formatters::VectorTypeSyntheticFrontEndCreator (CXXSyntheticChildren * , lldb::ValueObjectSP)
Referenced by lldb_private::CPlusPlusLanguage::GetHardcodedSynthetics(), and VectorTypeSummaryProvider().
WCharStringSummaryProvider()
bool lldb_private::formatters::WCharStringSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 112 of file CxxStringTypes.cpp.
References GetArrayAddressOrPointerValue(), lldb_private::ValueObject::GetTargetSP(), GetWCharByteSize(), lldb_private::Address::IsValid(), lldb_private::Stream::Printf(), lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream(), lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::SetLocation(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetPrefixToken(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetStream(), and lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::SetTargetSP().
Referenced by LoadSystemFormatters().
WCharSummaryProvider()
bool lldb_private::formatters::WCharSummaryProvider (ValueObject & valobj, Stream & stream, const TypeSummaryOptions & options)
Definition at line 162 of file CxxStringTypes.cpp.
References error(), lldb_private::ValueObject::GetData(), GetWCharByteSize(), lldb_private::Stream::Printf(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetBinaryZeroIsTerminator(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::SetData(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetPrefixToken(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetQuote(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetSourceSize(), and lldb_private::formatters::StringPrinter::DumpToStreamOptions::SetStream().
Referenced by LoadSystemFormatters().