LLDB: lldb_private::endian Namespace Reference
lldb_private::endian Namespace Reference
Classes
union EndianTest
Functions
lldb::ByteOrder InlHostByteOrder ()
Variables
static union lldb_private::endian::EndianTest endianTest = {0x01020304}
Function Documentation
InlHostByteOrder()
lldb::ByteOrder lldb_private::endian::InlHostByteOrder () inline
Definition at line 25 of file Endian.h.
References endianTest.
Referenced by lldb_private::ValueObject::AddressOf(), lldb_private::ValueObjectConstResultImpl::AddressOf(), lldb_private::Value::AppendDataToHostBuffer(), lldb_private::DataExtractor::Clear(), ConvertPDBLocationToDWARFExpression(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoAttachToProcessWithName(), CommandObjectProcessKDPPacketSend::DoExecute(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoWriteMemory(), dump_type_value(), lldb_private::DataExtractor::Get(), lldb_private::ArmUnwindInfo::GetByteAtOffset(), DynamicLoaderDarwinKernel::KextImageInfo::GetByteOrder(), lldb_private::ExecutionContext::GetByteOrder(), lldb_private::RegisterValue::GetByteOrder(), DynamicLoaderDarwinKernel::GetByteOrderFromMagic(), DynamicLoaderMacOSXDYLD::GetByteOrderFromMagic(), lldb_private::Scalar::GetData(), lldb_private::Scalar::GetData(), lldb_private::Opcode::GetDataByteOrder(), lldb_private::Opcode::GetEndianSwap(), GetFreeBSDProcessArgs(), lldb_private::DataExtractor::GetLongDouble(), GetMacOSXProcessArgs(), GetNetBSDProcessArgs(), GetOpenBSDProcessArgs(), lldb_private::DataExtractor::GetU16(), lldb_private::DataExtractor::GetU16(), lldb_private::DataExtractor::GetU16_unchecked(), lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU32_unchecked(), lldb_private::DataExtractor::GetU64(), lldb_private::DataExtractor::GetU64(), lldb_private::DataExtractor::GetU64_unchecked(), lldb_private::Value::GetValueAsData(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qHostInfo(), lldb_private::plugin::dwarf::ManualDWARFIndex::LoadFromCache(), ObjectFileMachO::ParseHeader(), ObjectFileMachO::ParseHeader(), ParseMachOHeader(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread(), lldb_private::Stream::PutDouble(), lldb_private::Stream::PutFloat(), lldb_private::Stream::PutLongDouble(), lldb_private::Stream::PutPointer(), lldb_private::DataEncoder::PutU16(), lldb_private::DataEncoder::PutU32(), lldb_private::DataEncoder::PutU64(), ReadCStringFromMemory(), DynamicLoaderMacOSXDYLD::ReadMachHeader(), EmulationStateARM::ReadPseudoMemory(), RegisterContextCorePOSIX_arm64::ReadRegister(), RegisterContextDarwin_arm64::ReadRegister(), RegisterContextDarwin_x86_64::ReadRegister(), lldb_private::plugin::dwarf::ManualDWARFIndex::SaveToCache(), lldb_private::Symtab::SaveToCache(), lldb_private::RegisterValue::SetValueFromData(), lldb_private::Scalar::SetValueFromData(), lldb_private::EmulateInstructionARM::TestEmulation(), lldb_private::CFBasicHash::UpdateFor(), lldb_private::DWARFExpression::UpdateValue(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteAllRegisters(), EmulationStateARM::WritePseudoMemory(), and lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::WriteRegister().
Variable Documentation
endianTest
union lldb_private::endian::EndianTest lldb_private::endian::endianTest = {0x01020304} static
Referenced by InlHostByteOrder().