LLDB: lldb_private::FormatterBytecode Namespace Reference
lldb_private::FormatterBytecode Namespace Reference
Classes
struct DataStack
Typedefs
using ControlStackElement = llvm::StringRef
using ControlStack = std::vector<ControlStackElement>
using DataStackElement
Enumerations
enum DataType : uint8_t {
Any , String , Int , UInt ,
Object , Type , Selector
}
enum OpCodes : uint8_t
enum Selectors : uint8_t
enum Signatures : uint8_t
Functions
llvm::Error Interpret (ControlStack &control, DataStack &data, Signatures sig)
static llvm::Error FormatImpl (DataStack &data)
Implement the @format function.
static llvm::Error TypeCheck (llvm::ArrayRef< DataStackElement > data, DataType type)
static llvm::Error TypeCheck (llvm::ArrayRef< DataStackElement > data, DataType type1, DataType type2)
static llvm::Error TypeCheck (llvm::ArrayRef< DataStackElement > data, DataType type1, DataType type2, DataType type3)
Typedef Documentation
ControlStack
using lldb_private::FormatterBytecode::ControlStack = std::vector<ControlStackElement>
Definition at line 40 of file FormatterBytecode.h.
ControlStackElement
using lldb_private::FormatterBytecode::ControlStackElement = llvm::StringRef
Definition at line 39 of file FormatterBytecode.h.
DataStackElement
using lldb_private::FormatterBytecode::DataStackElement
Initial value:
    std::variant<std::string, uint64_t, int64_t, lldb::ValueObjectSP,
                 CompilerType, Selectors>
Definition at line 41 of file FormatterBytecode.h.
Enumeration Type Documentation
DataType
enum lldb_private::FormatterBytecode::DataType : uint8_t
Enumerator
Any
String
Int
UInt
Object
Type
Selector
Definition at line 19 of file FormatterBytecode.h.
OpCodes
enum lldb_private::FormatterBytecode::OpCodes : uint8_t
Definition at line 21 of file FormatterBytecode.h.
Selectors
enum lldb_private::FormatterBytecode::Selectors : uint8_t
Definition at line 27 of file FormatterBytecode.h.
Signatures
enum lldb_private::FormatterBytecode::Signatures : uint8_t
Definition at line 33 of file FormatterBytecode.h.
Function Documentation
FormatImpl()
llvm::Error lldb_private::FormatterBytecode::FormatImpl (DataStack & data) static
Implement the @format function.
Definition at line 88 of file FormatterBytecode.cpp.
References lldb_private::Align(), lldb_private::FormatterBytecode::DataStack::Pop(), lldb_private::FormatterBytecode::DataStack::Push(), and lldb_private::toString().
Referenced by Interpret().
Interpret()
llvm::Error lldb_private::FormatterBytecode::Interpret (ControlStack & control, DataStack & data, Signatures sig)
Activate the top most block from the control stack.
Fetch the next byte in the instruction stream.
Definition at line 185 of file FormatterBytecode.cpp.
References Any, BINOP, BINOP_CHECKZERO, lldb_private::DataFormatters, error(), FormatImpl(), lldb_private::GetLog(), Int, LLDB_LOGV, Object, pc, lldb_private::FormatterBytecode::DataStack::Pop(), POP_VALOBJ, lldb_private::FormatterBytecode::DataStack::PopAny(), lldb_private::FormatterBytecode::DataStack::Push(), Selector, SHIFTOP, String, lldb_private::toString(), Type, TYPE_CHECK, and UInt.
Referenced by lldb_private::BytecodeSyntheticChildren::FrontEnd::CalculateNumChildren(), lldb_private::BytecodeSummaryFormat::FormatObject(), lldb_private::BytecodeSyntheticChildren::FrontEnd::FrontEnd(), lldb_private::BytecodeSyntheticChildren::FrontEnd::GetChildAtIndex(), lldb_private::BytecodeSyntheticChildren::FrontEnd::GetIndexOfChildWithName(), and lldb_private::BytecodeSyntheticChildren::FrontEnd::Update().
TypeCheck() [1/3]
llvm::Error lldb_private::FormatterBytecode::TypeCheck (llvm::ArrayRef< DataStackElement > data, DataType type) static
Definition at line 134 of file FormatterBytecode.cpp.
References Any, Int, Object, Selector, String, Type, and UInt.
Referenced by TypeCheck(), and TypeCheck().
TypeCheck() [2/3]
llvm::Error lldb_private::FormatterBytecode::TypeCheck (llvm::ArrayRef< DataStackElement > data, DataType type1, DataType type2) static
Definition at line 171 of file FormatterBytecode.cpp.
References error(), and TypeCheck().
TypeCheck() [3/3]
llvm::Error lldb_private::FormatterBytecode::TypeCheck (llvm::ArrayRef< DataStackElement > data, DataType type1, DataType type2, DataType type3) static
Definition at line 178 of file FormatterBytecode.cpp.
References error(), and TypeCheck().