LLDB: lldb_private::dil Namespace Reference
lldb_private::dil Namespace Reference
Classes
class ArraySubscriptNode
class ASTNode
The rest of the classes in this file, except for the Visitor class at the very end, define all the types of AST nodes used by the DIL parser and expression evaluator.
class BitFieldExtractionNode
class BooleanLiteralNode
class CastNode
class DILDiagnosticError
class DILLexer
Class for doing the simple lexing required by DIL.
class DILParser
Pure recursive descent parser for C++ like expressions.
class ErrorNode
class FloatLiteralNode
class IdentifierNode
class IntegerLiteralNode
class Interpreter
class MemberOfNode
class Token
Class defining the tokens generated by the DIL lexer and used by the DIL parser.
class UnaryOpNode
class Visitor
This class contains one Visit method for each specialized type of DIL AST node.
Typedefs
using ASTNodeUP = std::unique_ptr<ASTNode>
Enumerations
enum class NodeKind {
eArraySubscriptNode , eBitExtractionNode , eBooleanLiteralNode , eCastNode ,
eErrorNode , eFloatLiteralNode , eIdentifierNode , eIntegerLiteralNode ,
eMemberOfNode , eUnaryOpNode
}
The various types DIL AST nodes (used by the DIL parser).
enum class UnaryOpKind { AddrOf , Deref , Minus , Plus }
The Unary operators recognized by DIL.
enum class CastKind { eArithmetic , eEnumeration , ePointer , eNone }
The type casts allowed by DIL.
enum class IntegerTypeSuffix { None , Long , LongLong }
enum class ErrorCode : unsigned char { kOk = 0 , kInvalidExpressionSyntax , kUndeclaredIdentifier , kUnknown }
Functions
lldb::ValueObjectSP LookupIdentifier (llvm::StringRef name_ref, std::shared_ptr< StackFrame > frame_sp, lldb::DynamicValueType use_dynamic)
Given the name of an identifier (variable name, member name, type name, etc.), find the ValueObject for that name (if it exists), excluding global variables, and create and return an IdentifierInfo object containing all the relevant information about that object (for DIL parsing and evaluating).
lldb::ValueObjectSP LookupGlobalIdentifier (llvm::StringRef name_ref, std::shared_ptr< StackFrame > frame_sp, lldb::TargetSP target_sp, lldb::DynamicValueType use_dynamic)
Given the name of an identifier, check to see if it matches the name of a global variable.
llvm::Expected< lldb::TypeSystemSP > GetTypeSystemFromCU (std::shared_ptr< StackFrame > ctx)
lldb::ValueObjectSP GetDynamicOrSyntheticValue (lldb::ValueObjectSP value_sp, lldb::DynamicValueType use_dynamic, bool use_synthetic)
static CompilerType GetBasicType (lldb::TypeSystemSP type_system, lldb::BasicType basic_type)
static lldb::ValueObjectSP ArrayToPointerConversion (ValueObject &valobj, ExecutionContextScope &ctx, llvm::StringRef name)
static lldb::VariableSP DILFindVariable (ConstString name, VariableList &variable_list)
static bool IsLetter (char c)
static bool IsDigit (char c)
static std::optional< llvm::StringRef > IsWord (llvm::StringRef expr, llvm::StringRef &remainder)
static bool IsNumberBodyChar (char ch)
static std::optional< llvm::StringRef > IsNumber (llvm::StringRef &remainder, bool &isFloat)
static llvm::Error IsNotAllowedByMode (llvm::StringRef expr, Token token, lldb::DILMode mode)
CompilerType ResolveTypeByName (const std::string &name, ExecutionContextScope &ctx_scope)
Typedef Documentation
ASTNodeUP
using lldb_private::dil::ASTNodeUP = std::unique_ptr<ASTNode>
Definition at line 79 of file DILAST.h.
Enumeration Type Documentation
CastKind
enum class lldb_private::dil::CastKind strong
The type casts allowed by DIL.
Enumerator
eArithmetic
Casting to a scalar.
eEnumeration
Casting from a scalar to an enumeration type.
ePointer
Casting to a pointer type.
eNone
Invalid promotion type (results in error).
Definition at line 42 of file DILAST.h.
ErrorCode
enum class lldb_private::dil::ErrorCode : unsigned char strong
Enumerator
kOk
kInvalidExpressionSyntax
kUndeclaredIdentifier
kUnknown
Definition at line 31 of file DILParser.h.
IntegerTypeSuffix
enum class lldb_private::dil::IntegerTypeSuffix strong
Enumerator
None
Long
LongLong
Definition at line 195 of file DILAST.h.
NodeKind
enum class lldb_private::dil::NodeKind strong
The various types DIL AST nodes (used by the DIL parser).
Enumerator
eArraySubscriptNode
eBitExtractionNode
eBooleanLiteralNode
eCastNode
eErrorNode
eFloatLiteralNode
eIdentifierNode
eIntegerLiteralNode
eMemberOfNode
eUnaryOpNode
Definition at line 20 of file DILAST.h.
UnaryOpKind
enum class lldb_private::dil::UnaryOpKind strong
The Unary operators recognized by DIL.
Enumerator
AddrOf
Deref
Minus
Plus
Definition at line 34 of file DILAST.h.
Function Documentation
ArrayToPointerConversion()
lldb::ValueObjectSP lldb_private::dil::ArrayToPointerConversion (ValueObject & valobj, ExecutionContextScope & ctx, llvm::StringRef name) static
Definition at line 55 of file DILEval.cpp.
References lldb_private::ExecutionContextScope::CalculateExecutionContext(), lldb_private::ValueObject::CreateValueObjectFromAddress(), lldb_private::CompilerType::GetArrayElementType(), lldb_private::ValueObject::GetCompilerType(), lldb_private::ValueObject::GetLoadAddress(), and lldb_private::CompilerType::GetPointerType().
Referenced by lldb_private::dil::Interpreter::UnaryConversion(), and lldb_private::dil::Interpreter::Visit().
DILFindVariable()
lldb::VariableSP lldb_private::dil::DILFindVariable (ConstString name, VariableList & variable_list) static
Definition at line 130 of file DILEval.cpp.
References lldb_private::ConstString::GetStringRef().
Referenced by LookupGlobalIdentifier().
GetBasicType()
CompilerType lldb_private::dil::GetBasicType (lldb::TypeSystemSP type_system, lldb::BasicType basic_type) static
Definition at line 47 of file DILEval.cpp.
Referenced by lldb_private::dil::Interpreter::UnaryConversion(), and lldb_private::dil::Interpreter::Visit().
GetDynamicOrSyntheticValue()
lldb::ValueObjectSP lldb_private::dil::GetDynamicOrSyntheticValue (lldb::ValueObjectSP value_sp, lldb::DynamicValueType use_dynamic, bool use_synthetic)
Definition at line 26 of file DILEval.cpp.
References lldb::eNoDynamicValues.
GetTypeSystemFromCU()
llvm::Expected< lldb::TypeSystemSP > lldb_private::dil::GetTypeSystemFromCU (std::shared_ptr< StackFrame > ctx)
Definition at line 49 of file DILParser.cpp.
References lldb_private::SymbolContext::comp_unit, lldb_private::CompileUnit::GetLanguage(), and lldb_private::SymbolContext::module_sp.
Referenced by lldb_private::dil::Interpreter::UnaryConversion(), lldb_private::dil::Interpreter::Visit(), and lldb_private::dil::Interpreter::Visit().
IsDigit()
bool lldb_private::dil::IsDigit (char c) static
Definition at line 67 of file DILLexer.cpp.
Referenced by IsNumber(), IsNumberBodyChar(), and IsWord().
IsLetter()
bool lldb_private::dil::IsLetter (char c) static
Definition at line 63 of file DILLexer.cpp.
Referenced by IsNumberBodyChar(), and IsWord().
IsNotAllowedByMode()
llvm::Error lldb_private::dil::IsNotAllowedByMode (llvm::StringRef expr, Token token, lldb::DILMode mode) static
Definition at line 114 of file DILLexer.cpp.
References lldb::eDILModeFull, lldb::eDILModeLegacy, lldb::eDILModeSimple, lldb_private::dil::Token::GetLocation(), and lldb_private::dil::Token::IsOneOf().
Referenced by lldb_private::dil::DILLexer::Create().
IsNumber()
std::optional< llvm::StringRef > lldb_private::dil::IsNumber (llvm::StringRef & remainder, bool & isFloat) static
Definition at line 87 of file DILLexer.cpp.
References IsDigit(), and IsNumberBodyChar().
Referenced by lldb_private::dil::DILLexer::Lex().
IsNumberBodyChar()
bool lldb_private::dil::IsNumberBodyChar (char ch) static
Definition at line 83 of file DILLexer.cpp.
References IsDigit(), and IsLetter().
Referenced by IsNumber().
IsWord()
std::optional< llvm::StringRef > lldb_private::dil::IsWord (llvm::StringRef expr, llvm::StringRef & remainder) static
Definition at line 71 of file DILLexer.cpp.
References IsDigit(), and IsLetter().
Referenced by lldb_private::dil::DILLexer::Lex().
LookupGlobalIdentifier()
lldb::ValueObjectSP lldb_private::dil::LookupGlobalIdentifier (llvm::StringRef name_ref, std::shared_ptr< StackFrame > frame_sp, lldb::TargetSP target_sp, lldb::DynamicValueType use_dynamic)
Given the name of an identifier, check to see if it matches the name of a global variable.
If so, find the ValueObject for that global variable, and create and return an IdentifierInfo object containing all the relevant informatin about it.
Definition at line 155 of file DILEval.cpp.
References lldb_private::SymbolContext::comp_unit, lldb_private::ValueObjectVariable::Create(), DILFindVariable(), lldb_private::VariableList::Empty(), and lldb_private::CompileUnit::GetVariableList().
Referenced by lldb_private::dil::DILParser::ParseTypeId(), and lldb_private::dil::Interpreter::Visit().
LookupIdentifier()
lldb::ValueObjectSP lldb_private::dil::LookupIdentifier (llvm::StringRef name_ref, std::shared_ptr< StackFrame > frame_sp, lldb::DynamicValueType use_dynamic)
Given the name of an identifier (variable name, member name, type name, etc.), find the ValueObject for that name (if it exists), excluding global variables, and create and return an IdentifierInfo object containing all the relevant information about that object (for DIL parsing and evaluating).
Definition at line 196 of file DILEval.cpp.
References lldb_private::ValueObjectRegister::Create(), and lldb_private::SymbolContext::GetInstanceVariableName().
Referenced by lldb_private::dil::DILParser::ParseTypeId(), and lldb_private::dil::Interpreter::Visit().
ResolveTypeByName()
CompilerType lldb_private::dil::ResolveTypeByName (const std::string & name, ExecutionContextScope & ctx_scope)
Definition at line 58 of file DILParser.cpp.
References lldb_private::ExecutionContextScope::CalculateTarget(), lldb_private::ModuleList::FindTypes(), lldb_private::TypeResults::GetFirstType(), lldb_private::ConstString::GetStringRef(), lldb_private::CompilerType::GetTypeName(), and lldb_private::CompilerType::IsValid().
Referenced by lldb_private::dil::DILParser::ParseTypeId().