LLDB: lldb_private::FormatEntity Namespace Reference
lldb_private::FormatEntity Namespace Reference
Classes
struct Entry
class Formatter
Functions
Status Parse (const llvm::StringRef &format, Entry &entry)
Status ExtractVariableInfo (llvm::StringRef &format_str, llvm::StringRef &variable_name, llvm::StringRef &variable_format)
void AutoComplete (lldb_private::CompletionRequest &request)
bool FormatFileSpec (const FileSpec &file, Stream &s, llvm::StringRef elements, llvm::StringRef element_format)
void PrettyPrintFunctionArguments (Stream &out_stream, VariableList const &args, ExecutionContextScope *exe_scope)
For each variable in 'args' this function writes the variable name and it's pretty-printed value representation to 'out_stream' in following format:
Function Documentation
AutoComplete()
void lldb_private::FormatEntity::AutoComplete (lldb_private::CompletionRequest & request)
Definition at line 2592 of file FormatEntity.cpp.
References lldb_private::CompletionRequest::AddCompletion(), lldb_private::CompletionRequest::AddCompletions(), AddMatches(), FindEntry(), g_root, lldb_private::CompletionRequest::GetCursorArgumentPrefix(), MakeMatch(), and lldb_private::FormatEntity::Entry::Definition::num_children.
Referenced by lldb_private::OptionValueFormatEntity::AutoComplete().
ExtractVariableInfo()
Status lldb_private::FormatEntity::ExtractVariableInfo (llvm::StringRef & format_str, llvm::StringRef & variable_name, llvm::StringRef & variable_format)
Definition at line 2523 of file FormatEntity.cpp.
References error(), and lldb_private::Status::FromErrorStringWithFormat().
Referenced by ParseInternal().
FormatFileSpec()
bool lldb_private::FormatEntity::FormatFileSpec (const FileSpec & file, Stream & s, llvm::StringRef elements, llvm::StringRef element_format)
Definition at line 2553 of file FormatEntity.cpp.
References lldb_private::Stream::AsRawOstream(), lldb_private::FileSpec::Dump(), lldb_private::FileSpec::GetFilename(), lldb_private::ConstString::GetStringRef(), and lldb_private::Stream::PutCString().
Parse()
Status lldb_private::FormatEntity::Parse (const llvm::StringRef & format, Entry & entry)
Definition at line 2710 of file FormatEntity.cpp.
References lldb_private::FormatEntity::Entry::Clear(), ParseInternal(), lldb_private::FormatEntity::Entry::Root, and lldb_private::FormatEntity::Entry::type.
Referenced by lldb_private::InstructionList::Dump(), DumpInstToLog(), lldb_private::Debugger::FormatDisassemblerAddress(), lldb_private::FormatEntity::Formatter::FormatStringRef(), lldb::SBInstruction::GetDescription(), lldb::SBInstructionList::GetDescription(), lldb_private::OptionValueFormatEntity::OptionValueFormatEntity(), lldb::SBInstruction::Print(), lldb_private::Disassembler::PrintInstructions(), lldb::SBFormat::SBFormat(), lldb_private::StringSummaryFormat::SetSummaryString(), and lldb_private::OptionValueFormatEntity::SetValueFromString().
PrettyPrintFunctionArguments()
void lldb_private::FormatEntity::PrettyPrintFunctionArguments (Stream & out_stream, VariableList const & args, ExecutionContextScope * exe_scope)
For each variable in 'args' this function writes the variable name and it's pretty-printed value representation to 'out_stream' in following format:
/// name_1=repr_1, name_2=repr_2 ...
///
Definition at line 2658 of file FormatEntity.cpp.
References lldb_private::ExecutionContextScope::CalculateTarget(), lldb_private::ValueObjectVariable::Create(), lldb_private::ValueObject::eAllow, lldb::eFormatDefault, lldb_private::StringSummaryFormat::FormatObject(), lldb_private::VariableList::GetSize(), lldb_private::StreamString::GetString(), lldb_private::VariableList::GetVariableAtIndex(), lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and lldb_private::DataVisualization::ShouldPrintAsOneLiner().
Referenced by lldb_private::CPlusPlusLanguage::HandleFrameFormatVariable(), PrettyPrintFunctionNameWithArgs(), and PrettyPrintFunctionNameWithArgs().