LLDB: lldb_private::formatters::Foundation1436 Namespace Reference
lldb_private::formatters::Foundation1436 Namespace Reference
Classes
struct IDD32
struct IDD64
Typedefs
using NSArrayI_TransferSyntheticFrontEnd
using NSArrayISyntheticFrontEnd
using NSFrozenArrayMSyntheticFrontEnd
Functions
uint64_t __NSFrozenArrayMSize (lldb_private::Process &process, lldb::addr_t valobj_addr, Status &error)
Typedef Documentation
NSArrayI_TransferSyntheticFrontEnd
using lldb_private::formatters::Foundation1436::NSArrayI_TransferSyntheticFrontEnd
Initial value:
        GenericNSArrayISyntheticFrontEnd<IDD32, IDD64, false>
Definition at line 263 of file NSArray.cpp.
NSArrayISyntheticFrontEnd
using lldb_private::formatters::Foundation1436::NSArrayISyntheticFrontEnd
Initial value:
        GenericNSArrayISyntheticFrontEnd<IDD32, IDD64, true>
Definition at line 266 of file NSArray.cpp.
NSFrozenArrayMSyntheticFrontEnd
using lldb_private::formatters::Foundation1436::NSFrozenArrayMSyntheticFrontEnd
Initial value:
        Foundation1437::NSArrayMSyntheticFrontEnd
Definition at line 269 of file NSArray.cpp.
Function Documentation
__NSFrozenArrayMSize()
uint64_t lldb_private::formatters::Foundation1436::__NSFrozenArrayMSize (lldb_private::Process & process, lldb::addr_t valobj_addr, Status & error)
Definition at line 273 of file NSArray.cpp.
References lldb_private::formatters::Foundation1437::__NSArrayMSize(), and error().
Referenced by lldb_private::formatters::NSArraySummaryProvider().