LLDB: lldb_private::formatters::Foundation1437 Namespace Reference
lldb_private::formatters::Foundation1437 Namespace Reference
Classes
struct DataDescriptor
struct DataDescriptor_32
struct DataDescriptor_64
Typedefs
using NSArrayMSyntheticFrontEnd
using NSDictionaryMSyntheticFrontEnd
using NSSetMSyntheticFrontEnd
Functions
template<typename DD>
uint64_t __NSArrayMSize_Impl (lldb_private::Process &process, lldb::addr_t valobj_addr, Status &error)
uint64_t __NSArrayMSize (lldb_private::Process &process, lldb::addr_t valobj_addr, Status &error)
template<typename DD>
uint64_t __NSDictionaryMSize_Impl (lldb_private::Process &process, lldb::addr_t valobj_addr, Status &error)
uint64_t __NSDictionaryMSize (lldb_private::Process &process, lldb::addr_t valobj_addr, Status &error)
template<typename DD>
uint64_t __NSSetMSize_Impl (lldb_private::Process &process, lldb::addr_t valobj_addr, Status &error)
uint64_t __NSSetMSize (lldb_private::Process &process, lldb::addr_t valobj_addr, Status &error)
Variables
static const uint64_t NSDictionaryCapacities []
static const size_t NSDictionaryNumSizeBuckets
Typedef Documentation
NSArrayMSyntheticFrontEnd
using lldb_private::formatters::Foundation1437::NSArrayMSyntheticFrontEnd
Initial value:
     GenericNSArrayMSyntheticFrontEnd<
        DataDescriptor<uint32_t>, DataDescriptor<uint64_t>>
Definition at line 156 of file NSArray.cpp.
NSDictionaryMSyntheticFrontEnd
using lldb_private::formatters::Foundation1437::NSDictionaryMSyntheticFrontEnd
Initial value:
    GenericNSDictionaryMSyntheticFrontEnd<DataDescriptor_32, DataDescriptor_64>
Definition at line 363 of file NSDictionary.cpp.
NSSetMSyntheticFrontEnd
using lldb_private::formatters::Foundation1437::NSSetMSyntheticFrontEnd
Initial value:
      GenericNSSetMSyntheticFrontEnd<DataDescriptor_32, DataDescriptor_64>
Definition at line 195 of file NSSet.cpp.
Function Documentation
__NSArrayMSize()
uint64_t lldb_private::formatters::Foundation1437::__NSArrayMSize (lldb_private::Process & process, lldb::addr_t valobj_addr, Status & error)
Definition at line 176 of file NSArray.cpp.
References __NSArrayMSize_Impl(), error(), and lldb_private::Process::GetAddressByteSize().
Referenced by lldb_private::formatters::Foundation1436::__NSFrozenArrayMSize(), and lldb_private::formatters::NSArraySummaryProvider().
__NSArrayMSize_Impl()
template<typename DD> uint64_t lldb_private::formatters::Foundation1437::__NSArrayMSize_Impl (lldb_private::Process & process, lldb::addr_t valobj_addr, Status & error)
Definition at line 162 of file NSArray.cpp.
References error(), lldb_private::Process::GetAddressByteSize(), and lldb_private::Process::ReadMemory().
Referenced by __NSArrayMSize().
__NSDictionaryMSize()
uint64_t lldb_private::formatters::Foundation1437::__NSDictionaryMSize (lldb_private::Process & process, lldb::addr_t valobj_addr, Status & error)
Definition at line 382 of file NSDictionary.cpp.
References __NSDictionaryMSize_Impl(), error(), and lldb_private::Process::GetAddressByteSize().
Referenced by lldb_private::formatters::NSDictionarySummaryProvider().
__NSDictionaryMSize_Impl()
template<typename DD> uint64_t lldb_private::formatters::Foundation1437::__NSDictionaryMSize_Impl (lldb_private::Process & process, lldb::addr_t valobj_addr, Status & error)
Definition at line 368 of file NSDictionary.cpp.
References error(), lldb_private::Process::GetAddressByteSize(), and lldb_private::Process::ReadMemory().
Referenced by __NSDictionaryMSize().
__NSSetMSize()
uint64_t lldb_private::formatters::Foundation1437::__NSSetMSize (lldb_private::Process & process, lldb::addr_t valobj_addr, Status & error)
Definition at line 214 of file NSSet.cpp.
References __NSSetMSize_Impl(), error(), and lldb_private::Process::GetAddressByteSize().
Referenced by lldb_private::formatters::NSSetSummaryProvider().
__NSSetMSize_Impl()
template<typename DD> uint64_t lldb_private::formatters::Foundation1437::__NSSetMSize_Impl (lldb_private::Process & process, lldb::addr_t valobj_addr, Status & error)
Definition at line 200 of file NSSet.cpp.
References error(), lldb_private::Process::GetAddressByteSize(), and lldb_private::Process::ReadMemory().
Referenced by __NSSetMSize().
Variable Documentation
NSDictionaryCapacities
const uint64_t lldb_private::formatters::Foundation1437::NSDictionaryCapacities[] static
Initial value:
= {
        0, 3, 7, 13, 23, 41, 71, 127, 191, 251, 383, 631, 1087, 1723,
        2803, 4523, 7351, 11959, 19447, 31231, 50683, 81919, 132607,
        214519, 346607, 561109, 907759, 1468927, 2376191, 3845119,
        6221311, 10066421, 16287743, 26354171, 42641881, 68996069,
        111638519, 180634607, 292272623, 472907251
    }
Definition at line 324 of file NSDictionary.cpp.
NSDictionaryNumSizeBuckets
const size_t lldb_private::formatters::Foundation1437::NSDictionaryNumSizeBuckets static
Initial value:
=
        sizeof(NSDictionaryCapacities) / sizeof(uint64_t)
Definition at line 332 of file NSDictionary.cpp.