LLDB: lldb_private::breakpad Namespace Reference
lldb_private::breakpad Namespace Reference
Classes
class FileRecord
class FuncRecord
class InfoRecord
class InlineOriginRecord
class InlineRecord
class LineRecord
class ModuleRecord
class ObjectFileBreakpad
class PublicRecord
class Record
class StackCFIRecord
class StackWinRecord
class SymbolFileBreakpad
Functions
llvm::StringRef toString (Record::Kind K)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, Record::Kind K)
bool operator== (const ModuleRecord &L, const ModuleRecord &R)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const ModuleRecord &R)
bool operator== (const InfoRecord &L, const InfoRecord &R)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const InfoRecord &R)
bool operator== (const FileRecord &L, const FileRecord &R)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const FileRecord &R)
bool operator== (const InlineOriginRecord &L, const InlineOriginRecord &R)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const InlineOriginRecord &R)
bool operator== (const FuncRecord &L, const FuncRecord &R)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const FuncRecord &R)
bool operator== (const InlineRecord &L, const InlineRecord &R)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const InlineRecord &R)
bool operator== (const LineRecord &L, const LineRecord &R)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const LineRecord &R)
bool operator== (const PublicRecord &L, const PublicRecord &R)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const PublicRecord &R)
bool operator== (const StackCFIRecord &L, const StackCFIRecord &R)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const StackCFIRecord &R)
bool operator== (const StackWinRecord &L, const StackWinRecord &R)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const StackWinRecord &R)
Function Documentation
operator<<() [1/11]
llvm::raw_ostream & lldb_private::breakpad::operator<< (llvm::raw_ostream & OS, const FileRecord & R)
Definition at line 253 of file BreakpadRecords.cpp.
References lldb_private::breakpad::FileRecord::Name, lldb_private::breakpad::FileRecord::Number, and lldb_private::OS.
operator<<() [2/11]
llvm::raw_ostream & lldb_private::breakpad::operator<< (llvm::raw_ostream & OS, const FuncRecord & R)
Definition at line 322 of file BreakpadRecords.cpp.
References lldb_private::breakpad::FuncRecord::Address, lldb_private::breakpad::FuncRecord::Multiple, lldb_private::breakpad::FuncRecord::Name, lldb_private::OS, lldb_private::breakpad::FuncRecord::ParamSize, and lldb_private::breakpad::FuncRecord::Size.
operator<<() [3/11]
llvm::raw_ostream & lldb_private::breakpad::operator<< (llvm::raw_ostream & OS, const InfoRecord & R)
Definition at line 224 of file BreakpadRecords.cpp.
References lldb_private::UUID::GetAsString(), lldb_private::breakpad::InfoRecord::ID, and lldb_private::OS.
operator<<() [4/11]
llvm::raw_ostream & lldb_private::breakpad::operator<< (llvm::raw_ostream & OS, const InlineOriginRecord & R)
Definition at line 264 of file BreakpadRecords.cpp.
References lldb_private::breakpad::InlineOriginRecord::Name, lldb_private::breakpad::InlineOriginRecord::Number, and lldb_private::OS.
operator<<() [5/11]
llvm::raw_ostream & lldb_private::breakpad::operator<< (llvm::raw_ostream & OS, const InlineRecord & R)
Definition at line 371 of file BreakpadRecords.cpp.
References lldb_private::breakpad::InlineRecord::CallSiteFileNum, lldb_private::breakpad::InlineRecord::CallSiteLineNum, lldb_private::breakpad::InlineRecord::InlineNestLevel, lldb_private::breakpad::InlineRecord::OriginNum, lldb_private::OS, and lldb_private::breakpad::InlineRecord::Ranges.
operator<<() [6/11]
llvm::raw_ostream & lldb_private::breakpad::operator<< (llvm::raw_ostream & OS, const LineRecord & R)
Definition at line 410 of file BreakpadRecords.cpp.
References lldb_private::breakpad::LineRecord::Address, lldb_private::breakpad::LineRecord::FileNum, lldb_private::breakpad::LineRecord::LineNum, lldb_private::OS, and lldb_private::breakpad::LineRecord::Size.
operator<<() [7/11]
llvm::raw_ostream & lldb_private::breakpad::operator<< (llvm::raw_ostream & OS, const ModuleRecord & R)
Definition at line 197 of file BreakpadRecords.cpp.
References lldb_private::breakpad::ModuleRecord::Arch, lldb_private::UUID::GetAsString(), lldb_private::breakpad::ModuleRecord::ID, lldb_private::breakpad::ModuleRecord::OS, and lldb_private::OS.
operator<<() [8/11]
llvm::raw_ostream & lldb_private::breakpad::operator<< (llvm::raw_ostream & OS, const PublicRecord & R)
Definition at line 431 of file BreakpadRecords.cpp.
References lldb_private::breakpad::PublicRecord::Address, lldb_private::breakpad::PublicRecord::Multiple, lldb_private::breakpad::PublicRecord::Name, lldb_private::OS, and lldb_private::breakpad::PublicRecord::ParamSize.
operator<<() [9/11]
llvm::raw_ostream & lldb_private::breakpad::operator<< (llvm::raw_ostream & OS, const StackCFIRecord & R)
Definition at line 476 of file BreakpadRecords.cpp.
References lldb_private::breakpad::StackCFIRecord::Address, lldb_private::OS, lldb_private::breakpad::StackCFIRecord::Size, and lldb_private::breakpad::StackCFIRecord::UnwindRules.
operator<<() [10/11]
llvm::raw_ostream & lldb_private::breakpad::operator<< (llvm::raw_ostream & OS, const StackWinRecord & R)
Definition at line 554 of file BreakpadRecords.cpp.
References lldb_private::breakpad::StackWinRecord::CodeSize, lldb_private::breakpad::StackWinRecord::LocalSize, lldb_private::OS, lldb_private::breakpad::StackWinRecord::ParameterSize, lldb_private::breakpad::StackWinRecord::ProgramString, lldb_private::breakpad::StackWinRecord::RVA, and lldb_private::breakpad::StackWinRecord::SavedRegisterSize.
operator<<() [11/11]
llvm::raw_ostream & lldb_private::breakpad::operator<< (llvm::raw_ostream & OS, Record::Kind K) inline
Definition at line 55 of file BreakpadRecords.h.
References lldb_private::OS, and toString().
operator==() [1/10]
bool lldb_private::breakpad::operator== (const FileRecord & L, const FileRecord & R) inline
Definition at line 99 of file BreakpadRecords.h.
References lldb_private::breakpad::FileRecord::Name, and lldb_private::breakpad::FileRecord::Number.
operator==() [2/10]
bool lldb_private::breakpad::operator== (const FuncRecord & L, const FuncRecord & R)
Definition at line 318 of file BreakpadRecords.cpp.
References lldb_private::breakpad::FuncRecord::Address, lldb_private::breakpad::FuncRecord::Multiple, lldb_private::breakpad::FuncRecord::Name, lldb_private::breakpad::FuncRecord::ParamSize, and lldb_private::breakpad::FuncRecord::Size.
operator==() [3/10]
bool lldb_private::breakpad::operator== (const InfoRecord & L, const InfoRecord & R) inline
Definition at line 84 of file BreakpadRecords.h.
References lldb_private::breakpad::InfoRecord::ID.
operator==() [4/10]
bool lldb_private::breakpad::operator== (const InlineOriginRecord & L, const InlineOriginRecord & R) inline
Definition at line 114 of file BreakpadRecords.h.
References lldb_private::breakpad::InlineOriginRecord::Name, and lldb_private::breakpad::InlineOriginRecord::Number.
operator==() [5/10]
bool lldb_private::breakpad::operator== (const InlineRecord & L, const InlineRecord & R)
Definition at line 364 of file BreakpadRecords.cpp.
References lldb_private::breakpad::InlineRecord::CallSiteFileNum, lldb_private::breakpad::InlineRecord::CallSiteLineNum, lldb_private::breakpad::InlineRecord::InlineNestLevel, lldb_private::breakpad::InlineRecord::OriginNum, and lldb_private::breakpad::InlineRecord::Ranges.
operator==() [6/10]
bool lldb_private::breakpad::operator== (const LineRecord & L, const LineRecord & R)
Definition at line 406 of file BreakpadRecords.cpp.
References lldb_private::breakpad::LineRecord::Address, lldb_private::breakpad::LineRecord::FileNum, lldb_private::breakpad::LineRecord::LineNum, and lldb_private::breakpad::LineRecord::Size.
operator==() [7/10]
bool lldb_private::breakpad::operator== (const ModuleRecord & L, const ModuleRecord & R) inline
Definition at line 71 of file BreakpadRecords.h.
References lldb_private::breakpad::ModuleRecord::Arch, lldb_private::breakpad::ModuleRecord::ID, and lldb_private::breakpad::ModuleRecord::OS.
operator==() [8/10]
bool lldb_private::breakpad::operator== (const PublicRecord & L, const PublicRecord & R)
Definition at line 427 of file BreakpadRecords.cpp.
References lldb_private::breakpad::PublicRecord::Address, lldb_private::breakpad::PublicRecord::Multiple, lldb_private::breakpad::PublicRecord::Name, and lldb_private::breakpad::PublicRecord::ParamSize.
operator==() [9/10]
bool lldb_private::breakpad::operator== (const StackCFIRecord & L, const StackCFIRecord & R)
Definition at line 471 of file BreakpadRecords.cpp.
References lldb_private::breakpad::StackCFIRecord::Address, lldb_private::breakpad::StackCFIRecord::Size, and lldb_private::breakpad::StackCFIRecord::UnwindRules.
operator==() [10/10]
bool lldb_private::breakpad::operator== (const StackWinRecord & L, const StackWinRecord & R)
Definition at line 547 of file BreakpadRecords.cpp.
References lldb_private::breakpad::StackWinRecord::CodeSize, lldb_private::breakpad::StackWinRecord::LocalSize, lldb_private::breakpad::StackWinRecord::ParameterSize, lldb_private::breakpad::StackWinRecord::ProgramString, lldb_private::breakpad::StackWinRecord::RVA, and lldb_private::breakpad::StackWinRecord::SavedRegisterSize.
toString()
llvm::StringRef lldb_private::breakpad::toString (Record::Kind K)
Definition at line 562 of file BreakpadRecords.cpp.
References lldb_private::breakpad::Record::File, lldb_private::breakpad::Record::Func, lldb_private::breakpad::Record::Info, lldb_private::breakpad::Record::Inline, lldb_private::breakpad::Record::InlineOrigin, lldb_private::breakpad::Record::Line, lldb_private::breakpad::Record::Module, lldb_private::breakpad::Record::Public, lldb_private::breakpad::Record::StackCFI, and lldb_private::breakpad::Record::StackWin.
Referenced by lldb_private::breakpad::ObjectFileBreakpad::CreateSections(), lldb_private::breakpad::SymbolFileBreakpad::LineIterator::LineIterator(), lldb_private::breakpad::SymbolFileBreakpad::LineIterator::LineIterator(), and operator<<().