LLDB: lldb_private::python Namespace Reference
lldb_private::python Namespace Reference
Classes
class GIL
class NullTerminated
struct PassthroughFormat
class PythonBoolean
class PythonByteArray
class PythonBytes
class PythonCallable
class PythonDictionary
class PythonException
class PythonFile
struct PythonFormat
struct PythonFormat< bool >
struct PythonFormat< char * >
struct PythonFormat< char >
struct PythonFormat< const char * >
struct PythonFormat< int >
struct PythonFormat< long >
struct PythonFormat< long long >
struct PythonFormat< PyObject * >
struct PythonFormat< short >
struct PythonFormat< T, typename std::enable_if< std::is_base_of< PythonObject, T >::value >::type >
struct PythonFormat< unsigned char >
struct PythonFormat< unsigned int >
struct PythonFormat< unsigned long >
struct PythonFormat< unsigned long long >
struct PythonFormat< unsigned short >
class PythonInteger
class PythonList
class PythonModule
class PythonObject
class PythonScript
class PythonString
class PythonTuple
class ScopedPythonObject
A class that automatically clears an SB object when it goes out of scope.
class StructuredPythonObject
class SWIGBridge
class TypedPythonObject
Typedefs
typedef struct swig_type_info swig_type_info
Enumerations
enum class PyObjectType {
Unknown , None , Boolean , Integer ,
Dictionary , List , String , Bytes ,
ByteArray , Module , Callable , Tuple ,
File
}
enum class PyRefType { Borrowed , Owned }
enum class PyInitialValue { Invalid , Empty }
Functions
template<typename T>
T Take (PyObject *obj)
template<typename T>
T Retain (PyObject *obj)
llvm::Error nullDeref ()
llvm::Error exception (const char *s=nullptr)
llvm::Error keyError ()
const char * py2_const_cast (const char *s)
template<typename T>
llvm::Expected< T > As (llvm::Expected< PythonObject > &&obj)
template<>
llvm::Expected< bool > As< bool > (llvm::Expected< PythonObject > &&obj)
template<>
llvm::Expected< long long > As< long long > (llvm::Expected< PythonObject > &&obj)
template<>
llvm::Expected< unsigned long long > As< unsigned long long > (llvm::Expected< PythonObject > &&obj)
template<>
llvm::Expected< std::string > As< std::string > (llvm::Expected< PythonObject > &&obj)
template<typename T>
T unwrapOrSetPythonException (llvm::Expected< T > expected)
template<typename T>
T unwrapIgnoringErrors (llvm::Expected< T > expected)
llvm::Expected< PythonObject > runStringOneLine (const llvm::Twine &string, const PythonDictionary &globals, const PythonDictionary &locals)
llvm::Expected< PythonObject > runStringMultiLine (const llvm::Twine &string, const PythonDictionary &globals, const PythonDictionary &locals)
PyObject * RunString (const char *str, int start, PyObject *globals, PyObject *locals)
int RunSimpleString (const char *str)
python::PythonObject ToSWIGHelper (void *obj, swig_type_info *info)
void * LLDBSWIGPython_CastPyObjectToSBData (PyObject *data)
void * LLDBSWIGPython_CastPyObjectToSBBreakpoint (PyObject *data)
void * LLDBSWIGPython_CastPyObjectToSBBreakpointLocation (PyObject *data)
void * LLDBSWIGPython_CastPyObjectToSBAttachInfo (PyObject *data)
void * LLDBSWIGPython_CastPyObjectToSBLaunchInfo (PyObject *data)
void * LLDBSWIGPython_CastPyObjectToSBError (PyObject *data)
void * LLDBSWIGPython_CastPyObjectToSBEvent (PyObject *data)
void * LLDBSWIGPython_CastPyObjectToSBStream (PyObject *data)
void * LLDBSWIGPython_CastPyObjectToSBThread (PyObject *data)
void * LLDBSWIGPython_CastPyObjectToSBFrame (PyObject *data)
void * LLDBSWIGPython_CastPyObjectToSBSymbolContext (PyObject *data)
void * LLDBSWIGPython_CastPyObjectToSBValue (PyObject *data)
void * LLDBSWIGPython_CastPyObjectToSBValueList (PyObject *data)
void * LLDBSWIGPython_CastPyObjectToSBMemoryRegionInfo (PyObject *data)
void * LLDBSWIGPython_CastPyObjectToSBExecutionContext (PyObject *data)
void * LLDBSWIGPython_CastPyObjectToSBFrameList (PyObject *data)
Typedef Documentation
swig_type_info
typedef struct swig_type_info lldb_private::python::swig_type_info
Definition at line 37 of file SWIGPythonBridge.h.
Enumeration Type Documentation
PyInitialValue
enum class lldb_private::python::PyInitialValue strong
Enumerator
Invalid
Empty
Definition at line 181 of file PythonDataObjects.h.
PyObjectType
enum class lldb_private::python::PyObjectType strong
Enumerator
Unknown
None
Boolean
Integer
Dictionary
List
String
Bytes
ByteArray
Module
Callable
Tuple
File
Definition at line 81 of file PythonDataObjects.h.
PyRefType
enum class lldb_private::python::PyRefType strong
Enumerator
Borrowed
Owned
Definition at line 97 of file PythonDataObjects.h.
Function Documentation
As()
template<typename T> llvm::Expected< T > lldb_private::python::As (llvm::Expected< PythonObject > && obj)
Definition at line 376 of file PythonDataObjects.h.
References Borrowed.
Referenced by lldb_private::python::PythonCallable::GetArgInfo(), lldb_private::ScriptInterpreterPython::GetInterpreterInfo(), lldb_private::ScriptInterpreterPythonImpl::GetSysModuleDictionary(), and lldb_private::python::PythonScript::Init().
As< bool >()
template<> llvm::Expected< bool > lldb_private::python::As< bool > (llvm::Expected< PythonObject > && obj)
Referenced by GetOptionsForPyObject().
As< long long >()
template<> llvm::Expected< long long > lldb_private::python::As< long long > (llvm::Expected< PythonObject > && obj)
As< std::string >()
template<> llvm::Expected< std::string > lldb_private::python::As< std::string > (llvm::Expected< PythonObject > && obj)
Referenced by lldb_private::python::PythonException::ReadBacktrace().
As< unsigned long long >()
template<> llvm::Expected< unsigned long long > lldb_private::python::As< unsigned long long > (llvm::Expected< PythonObject > && obj)
exception()
llvm::Error lldb_private::python::exception (const char * s = nullptr) inline
Definition at line 170 of file PythonDataObjects.h.
Referenced by lldb_private::python::PythonObject::AsLongLong(), lldb_private::python::PythonObject::AsModuloUnsignedLongLong(), lldb_private::python::PythonObject::AsUnsignedLongLong(), lldb_private::python::PythonString::AsUTF8(), lldb_private::python::PythonObject::Call(), lldb_private::python::PythonObject::CallMethod(), lldb_private::python::PythonFile::Check(), lldb_private::python::PythonFile::FromFile(), lldb_private::python::PythonModule::Get(), lldb_private::python::PythonObject::GetAttribute(), lldb_private::python::PythonDictionary::GetItem(), lldb_private::python::PythonObject::GetType(), lldb_private::python::PythonModule::Import(), lldb_private::python::PythonScript::Init(), lldb_private::python::PythonObject::IsInstance(), lldb_private::python::PythonObject::IsTrue(), runStringMultiLine(), runStringOneLine(), and lldb_private::python::PythonDictionary::SetItem().
keyError()
llvm::Error lldb_private::python::keyError () inline
Definition at line 174 of file PythonDataObjects.h.
Referenced by lldb_private::python::PythonDictionary::GetItem().
LLDBSWIGPython_CastPyObjectToSBAttachInfo()
void * lldb_private::python::LLDBSWIGPython_CastPyObjectToSBAttachInfo (PyObject * data)
Referenced by ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessAttachInfoSP >().
LLDBSWIGPython_CastPyObjectToSBBreakpoint()
void * lldb_private::python::LLDBSWIGPython_CastPyObjectToSBBreakpoint (PyObject * data)
Referenced by ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointSP >().
LLDBSWIGPython_CastPyObjectToSBBreakpointLocation()
void * lldb_private::python::LLDBSWIGPython_CastPyObjectToSBBreakpointLocation (PyObject * data)
Referenced by ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointLocationSP >().
LLDBSWIGPython_CastPyObjectToSBData()
void * lldb_private::python::LLDBSWIGPython_CastPyObjectToSBData (PyObject * data)
Referenced by ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::DataExtractorSP >().
LLDBSWIGPython_CastPyObjectToSBError()
void * lldb_private::python::LLDBSWIGPython_CastPyObjectToSBError (PyObject * data)
Referenced by lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject().
LLDBSWIGPython_CastPyObjectToSBEvent()
void * lldb_private::python::LLDBSWIGPython_CastPyObjectToSBEvent (PyObject * data)
Referenced by lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject().
LLDBSWIGPython_CastPyObjectToSBExecutionContext()
void * lldb_private::python::LLDBSWIGPython_CastPyObjectToSBExecutionContext (PyObject * data)
Referenced by ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ExecutionContextRefSP >().
LLDBSWIGPython_CastPyObjectToSBFrame()
void * lldb_private::python::LLDBSWIGPython_CastPyObjectToSBFrame (PyObject * data)
Referenced by ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameSP >().
LLDBSWIGPython_CastPyObjectToSBFrameList()
void * lldb_private::python::LLDBSWIGPython_CastPyObjectToSBFrameList (PyObject * data)
Referenced by ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameListSP >().
LLDBSWIGPython_CastPyObjectToSBLaunchInfo()
void * lldb_private::python::LLDBSWIGPython_CastPyObjectToSBLaunchInfo (PyObject * data)
Referenced by ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessLaunchInfoSP >().
LLDBSWIGPython_CastPyObjectToSBMemoryRegionInfo()
void * lldb_private::python::LLDBSWIGPython_CastPyObjectToSBMemoryRegionInfo (PyObject * data)
LLDBSWIGPython_CastPyObjectToSBStream()
void * lldb_private::python::LLDBSWIGPython_CastPyObjectToSBStream (PyObject * data)
Referenced by ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StreamSP >().
LLDBSWIGPython_CastPyObjectToSBSymbolContext()
void * lldb_private::python::LLDBSWIGPython_CastPyObjectToSBSymbolContext (PyObject * data)
Referenced by lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject().
LLDBSWIGPython_CastPyObjectToSBThread()
void * lldb_private::python::LLDBSWIGPython_CastPyObjectToSBThread (PyObject * data)
Referenced by ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ThreadSP >().
LLDBSWIGPython_CastPyObjectToSBValue()
void * lldb_private::python::LLDBSWIGPython_CastPyObjectToSBValue (PyObject * data)
Referenced by ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectSP >().
LLDBSWIGPython_CastPyObjectToSBValueList()
void * lldb_private::python::LLDBSWIGPython_CastPyObjectToSBValueList (PyObject * data)
Referenced by ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectListSP >().
nullDeref()
llvm::Error lldb_private::python::nullDeref () inline
Definition at line 165 of file PythonDataObjects.h.
Referenced by lldb_private::python::PythonObject::AsLongLong(), lldb_private::python::PythonObject::AsModuloUnsignedLongLong(), lldb_private::python::PythonObject::AsUnsignedLongLong(), lldb_private::python::PythonString::AsUTF8(), lldb_private::python::PythonModule::Get(), lldb_private::python::PythonCallable::GetArgInfo(), lldb_private::python::PythonObject::GetAttribute(), lldb_private::python::PythonDictionary::GetItem(), lldb_private::python::PythonObject::GetType(), lldb_private::python::PythonObject::IsInstance(), lldb_private::python::PythonObject::IsTrue(), runStringMultiLine(), runStringOneLine(), and lldb_private::python::PythonDictionary::SetItem().
py2_const_cast()
const char * lldb_private::python::py2_const_cast (const char * s) inline
Definition at line 179 of file PythonDataObjects.h.
Referenced by lldb_private::python::PythonObject::Call(), and lldb_private::python::PythonObject::CallMethod().
Retain()
template<typename T> T lldb_private::python::Retain (PyObject * obj)
Definition at line 133 of file PythonDataObjects.h.
References Borrowed.
Referenced by lldb_private::python::PythonFile::FromFile(), lldb_private::python::PythonModule::Get(), lldb_private::python::PythonModule::GetDictionary(), and lldb_private::python::PythonDictionary::GetItem().
RunSimpleString()
int lldb_private::python::RunSimpleString (const char * str)
Definition at line 1472 of file PythonDataObjects.cpp.
References RunString().
Referenced by lldb_private::IOHandlerPythonInterpreter::Run(), and lldb_private::ScriptInterpreterPythonImpl::ScriptInterpreterPythonImpl().
RunString()
PyObject * lldb_private::python::RunString (const char * str, int start, PyObject * globals, PyObject * locals)
Definition at line 1454 of file PythonDataObjects.cpp.
Referenced by lldb_private::python::PythonScript::Init(), RunSimpleString(), and runStringMultiLine().
runStringMultiLine()
llvm::Expected< PythonObject > lldb_private::python::runStringMultiLine (const llvm::Twine & string, const PythonDictionary & globals, const PythonDictionary & locals)
Definition at line 1442 of file PythonDataObjects.cpp.
References exception(), lldb_private::python::PythonObject::get(), lldb_private::python::PythonObject::IsValid(), nullDeref(), RunString(), and Take().
runStringOneLine()
llvm::Expected< PythonObject > lldb_private::python::runStringOneLine (const llvm::Twine & string, const PythonDictionary & globals, const PythonDictionary & locals)
Definition at line 1416 of file PythonDataObjects.cpp.
References exception(), lldb_private::python::PythonObject::get(), lldb_private::python::PythonObject::IsValid(), nullDeref(), and Take().
Take()
template<typename T> T lldb_private::python::Take (PyObject * obj)
Definition at line 115 of file PythonDataObjects.h.
References Owned.
Referenced by lldb_private::python::PythonObject::Call(), lldb_private::python::PythonObject::CallMethod(), lldb_private::python::PythonFile::FromFile(), lldb_private::python::PythonString::FromUTF8(), lldb_private::python::PythonObject::GetAttribute(), lldb_private::python::PythonObject::GetType(), lldb_private::python::PythonModule::Import(), lldb_private::python::PythonScript::Init(), lldb_private::python::PythonByteArray::PythonByteArray(), lldb_private::python::PythonDictionary::PythonDictionary(), lldb_private::python::PythonList::PythonList(), lldb_private::python::PythonList::PythonList(), lldb_private::python::PythonTuple::PythonTuple(), lldb_private::python::PythonTuple::PythonTuple(), runStringMultiLine(), runStringOneLine(), lldb_private::python::PythonBytes::SetBytes(), lldb_private::python::PythonInteger::SetInteger(), and lldb_private::python::PythonBoolean::SetValue().
ToSWIGHelper()
python::PythonObject lldb_private::python::ToSWIGHelper (void * obj, swig_type_info * info)
Referenced by lldb_private::python::ScopedPythonObject< T >::ScopedPythonObject().
unwrapIgnoringErrors()
template<typename T> T lldb_private::python::unwrapIgnoringErrors (llvm::Expected< T > expected)
Definition at line 698 of file PythonDataObjects.h.
Referenced by lldb_private::ScriptInterpreterPython::GetInterpreterInfo().
unwrapOrSetPythonException()
template<typename T> T lldb_private::python::unwrapOrSetPythonException (llvm::Expected< T > expected)
Definition at line 685 of file PythonDataObjects.h.