LLDB: lldb_private::plugin::dwarf Namespace Reference
lldb_private::plugin::dwarf Namespace Reference
Classes
class AppleDWARFIndex
class DebugMapModule
class DebugNamesDWARFIndex
class DIERef
Identifies a DWARF debug info entry within a given Module.
class DWARFASTParser
class DWARFAttribute
class DWARFAttributes
class DWARFBaseDIE
class DWARFCompileUnit
class DWARFContext
class DWARFDebugAranges
class DWARFDebugInfo
class DWARFDebugInfoEntry
DWARFDebugInfoEntry objects assume that they are living in one big vector and do pointer arithmetic on their this pointers.
class DWARFDebugMacroEntry
class DWARFDebugMacroHeader
class DWARFDeclContext
class DWARFDIE
class DWARFFormValue
class DWARFIndex
class DWARFTypeUnit
class DWARFUnit
struct IndexSet
class ManualDWARFIndex
class NameToDIE
class SymbolFileDWARF
class SymbolFileDWARFDebugMap
class SymbolFileDWARFDwo
class SymbolFileWasm
class UniqueDWARFASTType
class UniqueDWARFASTTypeList
class UniqueDWARFASTTypeMap
Typedefs
typedef std::vector< DIERef > DIEArray
typedef std::shared_ptr< DWARFUnit > DWARFUnitSP
Enumerations
enum DWARFProducer {
eProducerInvalid = 0 , eProducerClang , eProducerGCC , eProducerSwift ,
eProducerOther
}
Functions
bool operator== (const DWARFBaseDIE &lhs, const DWARFBaseDIE &rhs)
bool operator!= (const DWARFBaseDIE &lhs, const DWARFBaseDIE &rhs)
llvm::StringRef DW_TAG_value_to_name (dw_tag_t tag)
std::optional< IndexSet< NameToDIE > > DecodeIndexSet (const DataExtractor &data, lldb::offset_t *offset_ptr)
void EncodeIndexSet (const IndexSet< NameToDIE > &set, DataEncoder &encoder)
Typedef Documentation
DIEArray
typedef std::vector<DIERef> lldb_private::plugin::dwarf::DIEArray
Definition at line 136 of file DIERef.h.
DWARFUnitSP
typedef std::shared_ptr<DWARFUnit> lldb_private::plugin::dwarf::DWARFUnitSP
Definition at line 33 of file DWARFUnit.h.
Enumeration Type Documentation
DWARFProducer
enum lldb_private::plugin::dwarf::DWARFProducer
Enumerator
eProducerInvalid
eProducerClang
eProducerGCC
eProducerSwift
eProducerOther
Definition at line 35 of file DWARFUnit.h.
Function Documentation
DecodeIndexSet()
std::optional< IndexSet< NameToDIE > > lldb_private::plugin::dwarf::DecodeIndexSet (const DataExtractor & data, lldb::offset_t * offset_ptr)
Definition at line 41 of file ManualDWARFIndexSet.cpp.
References CURRENT_CACHE_VERSION, lldb_private::StringTableReader::Decode(), lldb_private::plugin::dwarf::IndexSet< T >::function_basenames, lldb_private::plugin::dwarf::IndexSet< T >::function_fullnames, lldb_private::plugin::dwarf::IndexSet< T >::function_methods, lldb_private::plugin::dwarf::IndexSet< T >::function_selectors, lldb_private::DataExtractor::GetData(), lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU8(), lldb_private::plugin::dwarf::IndexSet< T >::globals, kIdentifierManualDWARFIndex(), lldb_private::plugin::dwarf::IndexSet< T >::namespaces, lldb_private::plugin::dwarf::IndexSet< T >::objc_class_selectors, and lldb_private::plugin::dwarf::IndexSet< T >::types.
Referenced by lldb_private::plugin::dwarf::ManualDWARFIndex::Decode().
DW_TAG_value_to_name()
llvm::StringRef lldb_private::plugin::dwarf::DW_TAG_value_to_name (dw_tag_t tag)
Definition at line 18 of file DWARFDefines.cpp.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::CompleteType(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindDefinitionDIE(), DWARFASTParserClang::MapDeclDIEToDefDIE(), lldb_private::plugin::dwarf::DWARFDeclContext::operator<<, lldb_private::plugin::dwarf::SymbolFileDWARF::ParseAndAppendGlobalVariable(), DWARFASTParserClang::ParseEnum(), DWARFASTParserClang::ParseObjCMethod(), DWARFASTParserClang::ParseSingleMember(), DWARFASTParserClang::ParseStructureLikeDIE(), DWARFASTParserClang::ParseTypeFromDWARF(), DWARFASTParserClang::ParseTypeModifier(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariableDIE(), lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveType(), and lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveTypeUID().
EncodeIndexSet()
void lldb_private::plugin::dwarf::EncodeIndexSet (const IndexSet< NameToDIE > & set, DataEncoder & encoder)
Definition at line 102 of file ManualDWARFIndexSet.cpp.
References lldb_private::DataEncoder::AppendData(), lldb_private::DataEncoder::AppendU32(), lldb_private::DataEncoder::AppendU8(), CURRENT_CACHE_VERSION, lldb_private::ConstStringTable::Encode(), lldb_private::plugin::dwarf::IndexSet< T >::function_basenames, lldb_private::plugin::dwarf::IndexSet< T >::function_fullnames, lldb_private::plugin::dwarf::IndexSet< T >::function_methods, lldb_private::plugin::dwarf::IndexSet< T >::function_selectors, lldb_private::DataEncoder::GetAddressByteSize(), lldb_private::DataEncoder::GetByteOrder(), lldb_private::DataEncoder::GetData(), lldb_private::plugin::dwarf::IndexSet< T >::globals, kIdentifierManualDWARFIndex(), lldb_private::plugin::dwarf::IndexSet< T >::namespaces, lldb_private::plugin::dwarf::IndexSet< T >::objc_class_selectors, and lldb_private::plugin::dwarf::IndexSet< T >::types.
Referenced by lldb_private::plugin::dwarf::ManualDWARFIndex::Encode().
operator!=()
bool lldb_private::plugin::dwarf::operator!= (const DWARFBaseDIE & lhs, const DWARFBaseDIE & rhs)
Definition at line 122 of file DWARFBaseDIE.cpp.
operator==()
bool lldb_private::plugin::dwarf::operator== (const DWARFBaseDIE & lhs, const DWARFBaseDIE & rhs)
Definition at line 118 of file DWARFBaseDIE.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), and lldb_private::plugin::dwarf::DWARFBaseDIE::GetDIE().