LLDB: CoreSimulatorSupport Namespace Reference
CoreSimulatorSupport Namespace Reference
Classes
class Device
class DeviceRuntime
class DeviceSet
class DeviceType
class ModelIdentifier
class OSVersion
class Process
Functions
bool operator> (const OSVersion &lhs, const OSVersion &rhs)
bool operator> (const ModelIdentifier &lhs, const ModelIdentifier &rhs)
bool operator< (const OSVersion &lhs, const OSVersion &rhs)
bool operator< (const ModelIdentifier &lhs, const ModelIdentifier &rhs)
bool operator== (const OSVersion &lhs, const OSVersion &rhs)
bool operator== (const ModelIdentifier &lhs, const ModelIdentifier &rhs)
bool operator!= (const OSVersion &lhs, const OSVersion &rhs)
bool operator!= (const ModelIdentifier &lhs, const ModelIdentifier &rhs)
Function Documentation
operator!=() [1/2]
bool CoreSimulatorSupport::operator!= (const ModelIdentifier & lhs, const ModelIdentifier & rhs)
Definition at line 327 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References CoreSimulatorSupport::ModelIdentifier::GetFamily(), CoreSimulatorSupport::ModelIdentifier::GetNumVersions(), CoreSimulatorSupport::ModelIdentifier::GetVersionAtIndex(), and l.
operator!=() [2/2]
bool CoreSimulatorSupport::operator!= (const OSVersion & lhs, const OSVersion & rhs)
Definition at line 315 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References CoreSimulatorSupport::OSVersion::GetNumVersions(), CoreSimulatorSupport::OSVersion::GetVersionAtIndex(), and l.
operator<() [1/2]
bool CoreSimulatorSupport::operator< (const ModelIdentifier & lhs, const ModelIdentifier & rhs)
Definition at line 273 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References CoreSimulatorSupport::ModelIdentifier::GetFamily(), CoreSimulatorSupport::ModelIdentifier::GetNumVersions(), CoreSimulatorSupport::ModelIdentifier::GetVersionAtIndex(), and l.
operator<() [2/2]
bool CoreSimulatorSupport::operator< (const OSVersion & lhs, const OSVersion & rhs)
Definition at line 261 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References CoreSimulatorSupport::OSVersion::GetNumVersions(), CoreSimulatorSupport::OSVersion::GetVersionAtIndex(), and l.
operator==() [1/2]
bool CoreSimulatorSupport::operator== (const ModelIdentifier & lhs, const ModelIdentifier & rhs)
Definition at line 300 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References CoreSimulatorSupport::ModelIdentifier::GetFamily(), CoreSimulatorSupport::ModelIdentifier::GetNumVersions(), CoreSimulatorSupport::ModelIdentifier::GetVersionAtIndex(), and l.
operator==() [2/2]
bool CoreSimulatorSupport::operator== (const OSVersion & lhs, const OSVersion & rhs)
Definition at line 288 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References CoreSimulatorSupport::OSVersion::GetNumVersions(), CoreSimulatorSupport::OSVersion::GetVersionAtIndex(), and l.
operator>() [1/2]
bool CoreSimulatorSupport::operator> (const ModelIdentifier & lhs, const ModelIdentifier & rhs)
Definition at line 247 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References CoreSimulatorSupport::ModelIdentifier::GetFamily(), CoreSimulatorSupport::ModelIdentifier::GetNumVersions(), CoreSimulatorSupport::ModelIdentifier::GetVersionAtIndex(), and l.
operator>() [2/2]
bool CoreSimulatorSupport::operator> (const OSVersion & lhs, const OSVersion & rhs)
Definition at line 235 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References CoreSimulatorSupport::OSVersion::GetNumVersions(), CoreSimulatorSupport::OSVersion::GetVersionAtIndex(), and l.