LLDB: lldb_private::process_gdb_remote Namespace Reference
lldb_private::process_gdb_remote Namespace Reference
Classes
class GDBRemoteClientBase
class GDBRemoteCommunication
class GDBRemoteCommunicationClient
class GDBRemoteCommunicationHistory
The history keeps a circular buffer of GDB remote packets.
class GDBRemoteCommunicationServer
class GDBRemoteCommunicationServerCommon
class GDBRemoteCommunicationServerLLGS
class GDBRemoteCommunicationServerPlatform
class GDBRemoteDynamicRegisterInfo
struct GDBRemoteFStatData
class GDBRemoteRegisterContext
struct PidTid
class ProcessGDBRemote
class ProcessGDBRemoteLog
struct QOffsets
The offsets used by the target when relocating the executable.
class ThreadGDBRemote
Typedefs
typedef std::shared_ptr< GDBRemoteDynamicRegisterInfo > GDBRemoteDynamicRegisterInfoSP
Enumerations
enum GDBStoppointType {
eStoppointInvalid = -1 , eBreakpointSoftware = 0 , eBreakpointHardware , eWatchpointWrite ,
eWatchpointRead , eWatchpointReadWrite
}
enum class CompressionType {
None = 0 , ZlibDeflate , LZFSE , LZ4 ,
LZMA
}
enum GDBErrno { GDB_EUNKNOWN = 9999 }
enum class GDBRLog : Log::MaskType {
Async = Log::ChannelFlag<0> , Breakpoints = Log::ChannelFlag<1> , Comm = Log::ChannelFlag<2> , Memory = Log::ChannelFlag<3> ,
MemoryDataLong = Log::ChannelFlag<4> , MemoryDataShort = Log::ChannelFlag<5> , Packets = Log::ChannelFlag<6> , Process = Log::ChannelFlag<7> ,
Step = Log::ChannelFlag<8> , Thread = Log::ChannelFlag<9> , Watchpoints = Log::ChannelFlag<10>
}
Functions
bool operator== (const QOffsets &a, const QOffsets &b)
llvm::raw_ostream & operator<< (llvm::raw_ostream &os, const QOffsets &offsets)
std::string LLGSArgToURL (llvm::StringRef url_arg, bool reverse_connect)
static std::vector< DynamicRegisterInfo::Register > GetRegisters_aarch64 ()
static std::vector< DynamicRegisterInfo::Register > GetRegisters_msp430 ()
static std::vector< DynamicRegisterInfo::Register > GetRegisters_x86 ()
static std::vector< DynamicRegisterInfo::Register > GetRegisters_x86_64 ()
std::vector< DynamicRegisterInfo::Register > GetFallbackRegisters (const ArchSpec &arch_to_use)
LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE ()
Typedef Documentation
GDBRemoteDynamicRegisterInfoSP
typedef std::shared_ptr<GDBRemoteDynamicRegisterInfo> lldb_private::process_gdb_remote::GDBRemoteDynamicRegisterInfoSP
Definition at line 33 of file GDBRemoteRegisterContext.h.
Enumeration Type Documentation
CompressionType
enum class lldb_private::process_gdb_remote::CompressionType strong
Enumerator
None
ZlibDeflate
LZFSE
LZ4
LZMA
Definition at line 33 of file GDBRemoteCommunication.h.
GDBErrno
enum lldb_private::process_gdb_remote::GDBErrno
Enumerator
GDB_EUNKNOWN
Definition at line 63 of file GDBRemoteCommunication.h.
GDBRLog
enum class lldb_private::process_gdb_remote::GDBRLog : Log::MaskType strong
Enumerator
Async
Breakpoints
Comm
Memory
MemoryDataLong
MemoryDataShort
Packets
Process
Step
Thread
Watchpoints
Definition at line 18 of file ProcessGDBRemoteLog.h.
GDBStoppointType
enum lldb_private::process_gdb_remote::GDBStoppointType
Enumerator
eStoppointInvalid
eBreakpointSoftware
eBreakpointHardware
eWatchpointWrite
eWatchpointRead
eWatchpointReadWrite
Definition at line 24 of file GDBRemoteCommunication.h.
Function Documentation
GetFallbackRegisters()
std::vector< DynamicRegisterInfo::Register > lldb_private::process_gdb_remote::GetFallbackRegisters (const ArchSpec & arch_to_use)
Definition at line 83 of file GDBRemoteRegisterFallback.cpp.
References lldb_private::ArchSpec::GetMachine(), GetRegisters_aarch64(), GetRegisters_msp430(), GetRegisters_x86(), and GetRegisters_x86_64().
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::BuildDynamicRegisterInfo().
GetRegisters_aarch64()
std::vector< DynamicRegisterInfo::Register > lldb_private::process_gdb_remote::GetRegisters_aarch64 () static
Definition at line 24 of file GDBRemoteRegisterFallback.cpp.
References pc, R32, R64, sp, x19, x20, x21, x22, x23, x24, x25, x26, x27, and x28.
Referenced by GetFallbackRegisters().
GetRegisters_msp430()
std::vector< DynamicRegisterInfo::Register > lldb_private::process_gdb_remote::GetRegisters_msp430 () static
Definition at line 39 of file GDBRemoteRegisterFallback.cpp.
References fp, pc, r10, r11, r12, r13, r14, r15, R16, r8, r9, and sp.
Referenced by GetFallbackRegisters().
GetRegisters_x86()
std::vector< DynamicRegisterInfo::Register > lldb_private::process_gdb_remote::GetRegisters_x86 () static
Definition at line 51 of file GDBRemoteRegisterFallback.cpp.
References eax, ebp, ebx, ecx, edi, edx, eip, esi, esp, and R32.
Referenced by GetFallbackRegisters().
GetRegisters_x86_64()
std::vector< DynamicRegisterInfo::Register > lldb_private::process_gdb_remote::GetRegisters_x86_64 () static
Definition at line 64 of file GDBRemoteRegisterFallback.cpp.
References r10, r11, r12, r13, r14, r15, R32, R64, r8, r9, rax, rbp, rbx, rcx, rdi, rdx, rip, rsi, and rsp.
Referenced by GetFallbackRegisters().
LLGSArgToURL()
std::string lldb_private::process_gdb_remote::LLGSArgToURL (llvm::StringRef url_arg, bool reverse_connect)
Definition at line 4387 of file GDBRemoteCommunicationServerLLGS.cpp.
References lldb_private::Socket::DecodeHostAndPort(), and lldb_private::URI::Parse().
LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE()
lldb_private::process_gdb_remote::LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE ()
operator<<()
llvm::raw_ostream & lldb_private::process_gdb_remote::operator<< (llvm::raw_ostream & os, const QOffsets & offsets)
Definition at line 53 of file GDBRemoteCommunicationClient.cpp.
References lldb_private::process_gdb_remote::QOffsets::offsets, and lldb_private::process_gdb_remote::QOffsets::segments.
operator==()
bool lldb_private::process_gdb_remote::operator== (const QOffsets & a, const QOffsets & b) inline
Definition at line 49 of file GDBRemoteCommunicationClient.h.
References lldb_private::process_gdb_remote::QOffsets::offsets, and lldb_private::process_gdb_remote::QOffsets::segments.