LLDB: lldb_private::instrumentation Namespace Reference
lldb_private::instrumentation Namespace Reference
Classes
class Instrumenter
RAII object for instrumenting LLDB API functions.
Functions
template<typename T, std::enable_if_t< std::is_fundamental< T >::value, int > = 0>
void stringify_append (llvm::raw_string_ostream &ss, const T &t)
template<typename T, std::enable_if_t<!std::is_fundamental< T >::value, int > = 0>
void stringify_append (llvm::raw_string_ostream &ss, const T &t)
template<typename T>
void stringify_append (llvm::raw_string_ostream &ss, T *t)
template<typename T>
void stringify_append (llvm::raw_string_ostream &ss, const T *t)
template<>
void stringify_append< char > (llvm::raw_string_ostream &ss, const char *t)
template<>
void stringify_append< std::nullptr_t > (llvm::raw_string_ostream &ss, const std::nullptr_t &t)
template<typename Head>
void stringify_helper (llvm::raw_string_ostream &ss, const Head &head)
template<typename Head, typename... Tail>
void stringify_helper (llvm::raw_string_ostream &ss, const Head &head, const Tail &...tail)
template<typename... Ts>
std::string stringify_args (const Ts &...ts)
Function Documentation
stringify_append() [1/4]
template<typename T, std::enable_if_t< std::is_fundamental< T >::value, int > = 0> void lldb_private::instrumentation::stringify_append (llvm::raw_string_ostream & ss, const T & t) inline
Definition at line 25 of file Instrumentation.h.
Referenced by stringify_helper(), and stringify_helper().
stringify_append() [2/4]
template<typename T, std::enable_if_t<!std::is_fundamental< T >::value, int > = 0> void lldb_private::instrumentation::stringify_append (llvm::raw_string_ostream & ss, const T & t) inline
Definition at line 30 of file Instrumentation.h.
stringify_append() [3/4]
template<typename T> void lldb_private::instrumentation::stringify_append (llvm::raw_string_ostream & ss, const T * t) inline
Definition at line 40 of file Instrumentation.h.
stringify_append() [4/4]
template<typename T> void lldb_private::instrumentation::stringify_append (llvm::raw_string_ostream & ss, T * t) inline
Definition at line 35 of file Instrumentation.h.
stringify_append< char >()
template<> void lldb_private::instrumentation::stringify_append< char > (llvm::raw_string_ostream & ss, const char * t) inline
Definition at line 45 of file Instrumentation.h.
stringify_append< std::nullptr_t >()
template<> void lldb_private::instrumentation::stringify_append< std::nullptr_t > (llvm::raw_string_ostream & ss, const std::nullptr_t & t) inline
Definition at line 51 of file Instrumentation.h.
stringify_args()
template<typename... Ts> std::string lldb_private::instrumentation::stringify_args (const Ts &... ts) inline
Definition at line 69 of file Instrumentation.h.
References stringify_helper().
stringify_helper() [1/2]
template<typename Head> void lldb_private::instrumentation::stringify_helper (llvm::raw_string_ostream & ss, const Head & head) inline
Definition at line 57 of file Instrumentation.h.
References stringify_append().
Referenced by stringify_args(), and stringify_helper().
stringify_helper() [2/2]
template<typename Head, typename... Tail> void lldb_private::instrumentation::stringify_helper (llvm::raw_string_ostream & ss, const Head & head, const Tail &... tail) inline
Definition at line 62 of file Instrumentation.h.
References stringify_append(), and stringify_helper().