LLDB: lldb_private::telemetry Namespace Reference
lldb_private::telemetry Namespace Reference
Classes
struct ClientInfo
struct CommandInfo
struct DebuggerInfo
struct ExecutableModuleInfo
struct ExitDescription
Describes an exit status.
struct LLDBBaseTelemetryInfo
struct LLDBConfig
struct LLDBEntryKind
class NoOpTelemetryManager
struct ProcessExitInfo
struct ScopedDispatcher
Helper RAII class for collecting telemetry.
class TelemetryManager
The base Telemetry manager instance in LLDB.
Typedefs
using SteadyTimePoint
Defines a convenient type for timestamp of various events.
Functions
static uint64_t ToNanosec (const SteadyTimePoint Point)
static std::string MakeUUID ()
static std::optional< std::chrono::nanoseconds > GetAsNanosec (StructuredData::Dictionary *dict, llvm::StringRef key)
Typedef Documentation
SteadyTimePoint
using lldb_private::telemetry::SteadyTimePoint
Initial value:
 std::chrono::time_point<std::chrono::steady_clock,
                                                std::chrono::nanoseconds>
Defines a convenient type for timestamp of various events.
Definition at line 75 of file Telemetry.h.
Function Documentation
GetAsNanosec()
std::optional< std::chrono::nanoseconds > lldb_private::telemetry::GetAsNanosec (StructuredData::Dictionary * dict, llvm::StringRef key) static
Definition at line 124 of file Telemetry.cpp.
References lldb_private::GetLog(), lldb_private::StructuredData::Dictionary::GetValueForKey(), LLDB_LOG, and lldb_private::Object.
Referenced by lldb_private::telemetry::TelemetryManager::DispatchClientTelemetry().
MakeUUID()
std::string lldb_private::telemetry::MakeUUID () static
Definition at line 41 of file Telemetry.cpp.
References lldb_private::UUID::Generate(), and lldb_private::UUID::GetAsString().
Referenced by lldb_private::telemetry::TelemetryManager::TelemetryManager().
ToNanosec()
uint64_t lldb_private::telemetry::ToNanosec (const SteadyTimePoint Point) static
Definition at line 32 of file Telemetry.cpp.
Referenced by lldb_private::telemetry::LLDBBaseTelemetryInfo::serialize().