LLDB: lldb_private Namespace Reference
lldb_private Namespace Reference
A class that represents a running process on the host machine.
Namespaces
namespace ansi
namespace breakpad
namespace ClangExpressionUtil
namespace ctf
namespace curses
namespace dil
namespace endian
namespace FormatEntity
namespace FormatterBytecode
namespace formatters
namespace instrumentation
namespace line_editor
namespace lua
namespace lzma
namespace mcp
namespace minidump
namespace NETBSD
Core files PT_NOTE segment descriptor types.
namespace npdb
namespace OPENBSD
namespace OperandMatchers
namespace platform_aix
namespace platform_android
namespace platform_freebsd
namespace platform_gdb_server
namespace platform_linux
namespace platform_netbsd
namespace platform_openbsd
namespace plugin
namespace postfix
namespace process_aix
namespace process_freebsd
namespace process_gdb_remote
namespace process_linux
namespace process_netbsd
namespace python
namespace sve
namespace telemetry
namespace trace_intel_pt
namespace transport
namespace wasm
namespace x86_64_with_base
Classes
class ABI
class AbortWithPayloadFrameRecognizer
class AbortWithPayloadRecognizedStackFrame
class AbstractSocket
class Address
A section + offset based address class.
class AddressableBits
A class which holds the metadata from a remote stub/corefile note about how many bits are used for addressing on this target.
struct AddressData
class AddressDataArray
class AddressRange
A section + offset based address range class.
class AddressRangeListImpl
class AddressRanges
class AddressResolver
General Outline: The AddressResolver is a Searcher.
class AddressResolverFileLine
"lldb/Core/AddressResolverFileLine.h" This class finds address for source file and line.
class AllocatedBlock
class AllocatedMemoryCache
class AppleGetItemInfoHandler
class AppleGetPendingItemsHandler
class AppleGetQueuesHandler
class AppleGetThreadItemInfoHandler
class AppleObjCDeclVendor
class AppleObjCExternalASTSource
class AppleObjCRuntime
class AppleObjCRuntimeV1
class AppleObjCRuntimeV2
class AppleObjCTrampolineHandler
class AppleObjCTypeEncodingParser
class ApplePropertyList
class AppleThreadPlanStepThroughDirectDispatch
class AppleThreadPlanStepThroughObjCTrampoline
class Architecture
class ArchitectureAArch64
class ArchitectureArm
class ArchitectureMips
class ArchitecturePPC64
class ArchSpec
An architecture specification class.
class Args
A command line argument class.
class Arm64RegisterFlagsDetector
This class manages the storage and detection of register field information.
class ARMSingleStepBreakpointLocationsPredictor
class ArmUnwindInfo
class AssertFrameRecognizer
When a thread stops, it checks depending on the platform if the top frame is an abort stack frame.
class AssertRecognizedStackFrame
Holds the stack frame where the assert is called from.
class ASTConsumerForwarder
Wraps an ASTConsumer into an SemaConsumer.
class ASTResultSynthesizer
"lldb/Expression/ASTResultSynthesizer.h" Adds a result variable declaration to the ASTs for an expression.
class ASTStructExtractor
"lldb/Expression/ASTStructExtractor.h" Extracts and describes the argument structure for a wrapped function.
struct AugmentedRangeData
class AutoHandle
struct B
class Baton
A class designed to wrap callback batons so they can cleanup any acquired resources.
class Block
A class that describes a single lexical block.
class BorrowedStackFrame
"lldb/Target/BorrowedStackFrame.h"
class Breakpoint
General Outline: A breakpoint has four main parts, a filter, a resolver, the list of breakpoint locations that have been determined for the filter/resolver pair, and finally a set of options for the breakpoint.
class BreakpointID
class BreakpointIDList
class BreakpointList
General Outline: Allows adding and removing breakpoints and find by ID and index.
class BreakpointLocation
General Outline: A breakpoint location is defined by the breakpoint that produces it, and the address that resulted in this particular instantiation.
class BreakpointLocationCollection
class BreakpointLocationList
"lldb/Breakpoint/BreakpointLocationList.h" This class is used by Breakpoint to manage a list of breakpoint locations, each breakpoint location in the list has a unique ID, and is unique by Address as well.
class BreakpointName
class BreakpointOptionGroup
class BreakpointOptions
"lldb/Breakpoint/BreakpointOptions.h" Class that manages the options on a breakpoint or breakpoint location.
class BreakpointPrecondition
class BreakpointResolver
General Outline: The BreakpointResolver is a Searcher.
class BreakpointResolverAddress
"lldb/Breakpoint/BreakpointResolverAddress.h" This class sets breakpoints on a given Address.
class BreakpointResolverFileLine
"lldb/Breakpoint/BreakpointResolverFileLine.h" This class sets breakpoints by file and line.
class BreakpointResolverFileRegex
"lldb/Breakpoint/BreakpointResolverFileRegex.h" This class sets breakpoints by file and line.
class BreakpointResolverName
"lldb/Breakpoint/BreakpointResolverName.h" This class sets breakpoints on a given function name, either by exact match or by regular expression.
class BreakpointResolverScripted
"lldb/Breakpoint/BreakpointResolverScripted.h" This class sets breakpoints on a given Address.
class BreakpointSite
Class that manages the actual breakpoint that will be inserted into the running program.
class Broadcaster
An event broadcasting class.
class BroadcasterManager
class BroadcastEventSpec
lldb::BroadcastEventSpec
class BytecodeSummaryFormat
A summary formatter that is defined in LLDB formmater bytecode.
class BytecodeSyntheticChildren
A synthetic formatter that is defined in LLDB formmater bytecode.
struct CacheSignature
A signature for a given file on disk.
class CallbackLogHandler
class CallEdge
Represent a call made within a Function.
class CallFrameInfo
class CallSiteParameter
Represent the locations of a parameter at a call site, both in the caller and in the callee.
class CFBasicHash
class Checksum
class ClangASTImporter
Manages and observes all Clang AST node importing in LLDB.
class ClangASTMetadata
class ClangASTSource
Provider for named objects defined in the debug info for Clang.
class ClangDiagnostic
class ClangDynamicCheckerFunctions
class ClangExpressionDeclMap
"lldb/Expression/ClangExpressionDeclMap.h" Manages named entities that are defined in LLDB's debug information.
class ClangExpressionHelper
class ClangExpressionParser
"lldb/Expression/ClangExpressionParser.h" Encapsulates an instance of Clang that can parse expressions.
class ClangExpressionSourceCode
class ClangExpressionVariable
"lldb/Expression/ClangExpressionVariable.h" Encapsulates one variable for the expression parser.
class ClangExternalASTSourceCallbacks
class ClangFunctionCaller
"lldb/Expression/ClangFunctionCaller.h" Encapsulates a function that can be called.
class ClangHighlighter
class ClangModulesDeclVendor
class ClangPersistentVariables
"lldb/Expression/ClangPersistentVariables.h" Manages persistent values that need to be preserved between expression invocations.
class ClangREPL
Implements a Clang-based REPL for C languages on top of LLDB's REPL framework.
class ClangUserExpression
"lldb/Expression/ClangUserExpression.h" Encapsulates a single expression for use with Clang
struct ClangUtil
class ClangUtilityFunction
"lldb/Expression/ClangUtilityFunction.h" Encapsulates a single expression for use with Clang
class ClassDescriptorV2
class ClassDescriptorV2Tagged
class Cloneable
A class that implements CRTP-based "virtual constructor" idiom.
class CloneableECError
Common base class for all error-code errors.
class CloneableError
Going a bit against the spirit of llvm::Error, lldb_private::Status need to store errors long-term and sometimes copy them.
class ClusterManager
class CommandAlias
class CommandCompletions
class CommandHistory
class CommandInterpreter
class CommandInterpreterRunOptions
class CommandInterpreterRunResult
class CommandObject
class CommandObjectApropos
class CommandObjectBreakpointCommand
class CommandObjectDiagnostics
class CommandObjectDisassemble
class CommandObjectDWIMPrint
Implements dwim-print, a printing command that chooses the most direct, efficient, and resilient means of printing a given expression.
class CommandObjectExpression
class CommandObjectGUI
class CommandObjectHelp
class CommandObjectIterateOverThreads
class CommandObjectLanguage
class CommandObjectLog
class CommandObjectMemory
class CommandObjectMemoryTag
class CommandObjectMultipleThreads
Class similar to CommandObjectIterateOverThreads, but which performs an action on multiple threads at once instead of iterating over each thread.
class CommandObjectMultiword
class CommandObjectMultiwordBreakpoint
class CommandObjectMultiwordCommands
class CommandObjectMultiwordFrame
class CommandObjectMultiwordProcess
class CommandObjectMultiwordScripting
class CommandObjectMultiwordSettings
class CommandObjectMultiwordSource
class CommandObjectMultiwordTarget
class CommandObjectMultiwordThread
class CommandObjectMultiwordWatchpoint
class CommandObjectParsed
class CommandObjectPlatform
class CommandObjectPlugin
class CommandObjectProtocolServer
class CommandObjectProxy
class CommandObjectQuit
class CommandObjectRaw
class CommandObjectRegexCommand
class CommandObjectRegister
class CommandObjectSession
class CommandObjectStats
class CommandObjectTrace
class CommandObjectTraceProxy
This class works by delegating the logic to the actual trace plug-in that can support the current process.
class CommandObjectType
class CommandObjectVersion
class CommandObjectWatchpointCommand
class CommandOptionsProcessAttach
class CommandOptionsProcessLaunch
class CommandPluginInterfaceImplementation
class CommandReturnObject
class Communication
An abstract communications class.
class CompactUnwindInfo
struct CompilerContext
CompilerContext allows an array of these items to be passed to perform detailed lookups in SymbolVendor and SymbolFile functions.
class CompilerDecl
Represents a generic declaration such as a function declaration.
class CompilerDeclContext
Represents a generic declaration context in a program.
class CompilerType
Generic representation of a type in a programming language.
class CompileUnit
A class that describes a compilation unit.
class CompletionRequest
"lldb/Utility/ArgCompletionRequest.h"
class CompletionResult
class Connection
A communication connection class.
class ConnectionConPTY
A read only Connection implementation for the Windows ConPTY.
class ConnectionFileDescriptor
class ConnectionGenericFile
class ConstString
A uniqued constant string class.
struct ConstStringStats
class ConstStringTable
Many cache files require string tables to store data efficiently.
struct CoreDefinition
struct CoreFileMemoryRange
class CoreFileMemoryRanges
struct CoreNote
class CPlusPlusLanguage
class CPlusPlusNameParser
class CPPLanguageRuntime
class CppModuleConfiguration
A Clang configuration when importing C++ modules.
struct CTFArray
struct CTFConst
struct CTFEnum
struct CTFForward
struct CTFFunction
struct CTFInteger
struct CTFModifier
struct CTFPointer
struct CTFRecord
struct CTFRestrict
struct CTFStruct
struct CTFType
struct CTFTypedef
struct CTFUnion
struct CTFVolatile
struct CXXFunctionSummaryFormat
class CxxModuleHandler
Handles importing decls into an ASTContext with an attached C++ module.
class CXXSyntheticChildren
class DataBuffer
A pure virtual protocol class for abstracted read only data buffers.
class DataBufferHeap
A subclass of DataBuffer that stores a data buffer on the heap.
class DataBufferLLVM
class DataBufferUnowned
class DataEncoder
An binary data encoding class.
class DataExtractor
An data extractor class.
class DataFileCache
This class enables data to be cached into a directory using the llvm caching code.
class DataVisualization
class Debugger
A class to manage flag bits.
class DebuggerStats
class DebuggerThread
class DebugMacroEntry
class DebugMacros
class Declaration
A class that describes the declaration location of a lldb object.
class DeclFromParser
class DeclFromUser
class DeclVendor
struct DecodeResult
class DefaultHighlighter
A default highlighter that only highlights the user cursor, but doesn't do any other highlighting.
struct DemangledNameInfo
Stores information about where certain portions of a demangled function name begin and end.
class Diagnostic
struct DiagnosticDetail
A compiler-independent representation of an lldb_private::Diagnostic.
class DiagnosticError
class DiagnosticEventData
class DiagnosticManager
class Diagnostics
Diagnostics are a collection of files to help investigate bugs and troubleshoot issues.
class DirectCallEdge
A direct call site.
class Disassembler
class DomainSocket
class DumpValueObjectOptions
class DWARFCallFrameInfo
class DWARFDataExtractor
class DWARFExpression
"lldb/Expression/DWARFExpression.h" Encapsulates a DWARF location expression and interprets it.
class DWARFExpressionList
"lldb/Expression/DWARFExpressionList.h" Encapsulates a range map from file address range to a single DWARF location expression.
struct DWOStats
Holds statistics about DWO (Debug With Object) files.
class DynamicCheckerFunctions
Encapsulates dynamic check functions used by expressions.
class DynamicLoader
A plug-in interface definition class for dynamic loaders.
class DynamicLoaderDarwin
class DynamicLoaderWindowsDYLD
class DynamicRegisterInfo
class Editline
Instances of Editline provide an abstraction over libedit's EditLine facility.
class ElapsedTime
A class that measures elapsed time in an exception safe way.
class EmulateInstruction
"lldb/Core/EmulateInstruction.h" A class that allows emulation of CPU opcodes.
class EmulateInstructionARM
class EmulateInstructionLoongArch
class EmulateInstructionPPC64
class EmulateInstructionRISCV
class Environment
class EvaluateExpressionOptions
class Event
class EventData
class EventDataBytes
class EventDataReceipt
class EventDataStructuredData
This class handles one or more StructuredData::Dictionary entries that are raised for structured data events.
class ExceptionRecord
class ExceptionSearchFilter
class ExecuteScriptOptions
class ExecutionContext
"lldb/Target/ExecutionContext.h" A class that contains an execution context.
class ExecutionContextRef
Execution context objects refer to objects in the execution of the program that is being debugged.
class ExecutionContextScope
"lldb/Target/ExecutionContextScope.h" Inherit from this if your object can reconstruct its execution context.
class Executor
class Expression
Encapsulates a single expression for use in lldb.
class ExpressionError
An llvm::Error used to communicate diagnostics in Status.
class ExpressionParser
"lldb/Expression/ExpressionParser.h" Encapsulates an instance of a compiler that can parse expressions.
class ExpressionSourceCode
class ExpressionTypeSystemHelper
"lldb/Expression/ExpressionTypeSystemHelper.h" A helper object that the Expression can pass to its ExpressionParser to provide generic information that any type of expression will need to supply.
class ExpressionVariable
class ExpressionVariableList
"lldb/Expression/ExpressionVariable.h" A list of variable references.
class ExternalASTSourceWrapper
Wraps an ExternalASTSource into an ExternalSemaSource.
class FieldEnum
class File
An abstract base class for files.
class FileAction
class FileCache
class FileLineResolver
This class finds address for source file and line.
class FileSpec
A file utility class.
class FileSpecList
A file collection class.
class FileSystem
class Flags
A class to manage flags.
class FormatCache
class FormatManager
class FormattersContainer
class FormattersMatchCandidate
class FormattersMatchData
union FPR
class FreeBSDSignals
FreeBSD specific set of Unix signals.
class Function
A class that describes a function.
class FunctionCaller
Encapsulates a function that can be called.
struct FunctionCallLabel
Holds parsed information about a function call label that LLDB attaches as an AsmLabel to function AST nodes it parses from debug-info.
class FunctionInfo
A class that contains generic function information.
class FuncUnwinders
struct FXSAVE
struct GDBRemotePacket
GDB remote packet as used by the GDB remote communication history.
class GDBRemoteSignals
Initially carries signals defined by the GDB Remote Serial Protocol.
class GNUstepObjCRuntime
class HardcodedFormatters
struct HardwareBreakpoint
class Highlighter
Annotates source code with color attributes.
class HighlighterManager
Manages the available highlighters.
struct HighlightStyle
Represents style that the highlighter should apply to the given source code.
class HistoryThread
A thread object representing a backtrace from a previous point in the process execution.
class HistoryUnwind
class Host
A class that provides host computer information.
class HostInfoAIX
class HostInfoAndroid
class HostInfoBase
class HostInfoFreeBSD
class HostInfoLinux
class HostInfoMacOSX
class HostInfoNetBSD
class HostInfoOpenBSD
class HostInfoPosix
class HostInfoWindows
class HostNativeProcessBase
class HostNativeThreadBase
class HostProcess
class HostProcessPosix
class HostProcessWindows
class HostThread
class HostThreadMacOSX
class HostThreadPosix
class HostThreadWindows
class HTRBlock
Block structure representing a sequence of trace "units" (ie instructions).
class HTRBlockLayer
HTR layer composed of blocks of the trace.
class HTRBlockMetadata
Metadata associated with an HTR block See lldb/docs/htr.rst for comprehensive HTR documentation.
class HTRInstructionLayer
"Base" layer of HTR representing the dynamic instructions of the trace.
class IDebugDelegate
class IFormatChangeListener
class IHTRLayer
HTR layer interface See lldb/docs/htr.rst for comprehensive HTR documentation.
class IndirectCallEdge
An indirect call site.
class InlineFunctionInfo
A class that describes information for an inlined function.
struct InstrPattern
class Instruction
class InstructionList
class InstrumentationRuntime
class InstrumentationRuntimeASan
class InstrumentationRuntimeBoundsSafety
class InstrumentationRuntimeMainThreadChecker
class InstrumentationRuntimeStopInfo
class InstrumentationRuntimeTSan
class InstrumentationRuntimeUBSan
struct IntelPTDataKinds
class IOHandler
class IOHandlerConfirm
class IOHandlerCursesGUI
class IOHandlerDelegate
A delegate class for use with IOHandler subclasses.
class IOHandlerDelegateMultiline
class IOHandlerEditline
class IOHandlerProcessSTDIOWindows
class IOHandlerPythonInterpreter
class IOHandlerStack
class IOObject
class IRDynamicChecks
"lldb/Expression/IRDynamicChecks.h" Adds dynamic checks to a user-entered expression to reduce its likelihood of crashing
class IRExecutionUnit
"lldb/Expression/IRExecutionUnit.h" Contains the IR and, optionally, JIT- compiled code for a module.
class IRMemoryMap
Encapsulates memory that may exist in the process but must also be available in the host process.
class ItaniumABILanguageRuntime
class ITSession
class JITLoader
A plug-in interface definition class for JIT loaders.
class JITLoaderList
Class used by the Process to hold a list of its JITLoaders.
struct JSONSection
struct JSONSymbol
struct JSONUINT64
Helper structure to help parse long numbers that can't be easily represented by a JSON number that is compatible with Javascript (52 bits) or that can also be represented as hex.
class Language
class LanguageCategory
class LanguageProperties
class LanguageRuntime
struct LanguageSet
A SmallBitVector that represents a set of source languages (lldb::LanguageType).
class LineEntry
A line table entry class.
class LineTable
A line table class.
struct LinuxPerfZeroTscConversion
jLLDBTraceGetState gdb-remote packet
class LinuxSignals
Linux specific set of Unix signals.
class Listener
class LLVMUserExpression
"lldb/Expression/LLVMUserExpression.h" Encapsulates a one-time expression for use in lldb.
class LoadedModuleInfoList
class LoadScriptOptions
class LocalDebugDelegate
class LockableStreamFile
class LockedStreamFile
class LockFileBase
class LockFilePosix
class LockFileWindows
class LockingAdaptedIterable
class Log
class LogChannelDWARF
class LogChannelSystem
class LogHandler
class Lua
class MachKernelError
FIXME: Move these declarations closer to where they're used.
class MainLoopBase
class MainLoopPosix
class MainLoopWindows
class Mangled
A class that handles mangled names.
class Materializer
class MCBasedABI
class MemoryCache
class MemoryHistory
class MemoryHistoryASan
class MemoryMonitor
class MemoryRegionInfo
class MemoryRegionInfos
class MemoryTagManager
class MemoryTagManagerAArch64MTE
class MemoryTagMap
MemoryTagMap provides a way to give a sparse read result when reading memory tags for a range.
struct MMSReg
struct MMSRegComp
class Module
A class that describes an executable image and its associated object and symbol files.
class ModuleCache
A module cache class.
class ModuleChild
A mix in class that contains a pointer back to the module that owns the object which inherits from it.
class ModuleDependencyCollectorAdaptor
struct ModuleFunctionSearchOptions
Options used by Module::FindFunctions.
class ModuleList
A collection class for Module objects.
class ModuleListProperties
class ModuleSpec
class ModuleSpecList
struct ModuleStats
A class that represents statistics for a since lldb_private::Module.
class MonitoringProcessLauncher
struct MPX
struct MPXCsr
struct MPXReg
class NameSearchContext
"lldb/Expression/ClangASTSource.h" Container for all objects relevant to a single name lookup
class NativeDebugDelegate
class NativeFile
class NativeProcessELF
Abstract class that extends NativeProcessProtocol with ELF specific logic.
class NativeProcessProtocol
class NativeProcessSoftwareSingleStep
class NativeProcessWindows
class NativeRegisterContext
class NativeRegisterContextDBReg
class NativeRegisterContextDBReg_arm
class NativeRegisterContextDBReg_arm64
class NativeRegisterContextDBReg_loongarch
class NativeRegisterContextDBReg_x86
class NativeRegisterContextRegisterInfo
class NativeRegisterContextWindows
class NativeThreadProtocol
class NativeThreadWindows
struct NativeWatchpoint
class NativeWatchpointList
class NetBSDSignals
NetBSD specific set of Unix signals.
class NonNullSharedPtr
A non-nullable shared pointer that always holds a valid object.
class ObjCLanguage
class ObjCLanguageRuntime
class ObjCPlusPlusLanguage
class ObjectContainer
A plug-in interface definition class for object containers.
class ObjectContainerMachOFileset
class ObjectFile
A plug-in interface definition class for object file parsers.
class ObjectFileJIT
class ObjectFileJITDelegate
class ObjectFileJSON
class ObjectFilePDB
class Opcode
class OpenBSDSignals
OpenBSD specific set of Unix signals.
class OperatingSystem
A plug-in interface definition class for halted OS helpers.
class OperatingSystemInterface
class OperatingSystemPythonInterface
struct Option
class OptionalClangModuleID
A Clang module ID.
struct OptionArgElement
struct OptionArgParser
struct OptionDefinition
struct OptionEnumValueElement
class OptionGroup
class OptionGroupArchitecture
class OptionGroupBoolean
class OptionGroupFile
class OptionGroupFileList
class OptionGroupFormat
class OptionGroupMemoryTag
class OptionGroupOptions
class OptionGroupOutputFile
class OptionGroupPlatform
class OptionGroupPlatformCaching
class OptionGroupPlatformRSync
class OptionGroupPlatformSSH
class OptionGroupPythonClassWithDict
class OptionGroupString
class OptionGroupUInt64
class OptionGroupUUID
class OptionGroupValueObjectDisplay
class OptionGroupVariable
class OptionGroupWatchpoint
class OptionParseError
An llvm::Error that represents an option parsing diagnostic.
class OptionParser
class Options
A command line option parsing protocol class.
class OptionsWithRaw
A pair of an option list with a 'raw' string as a suffix.
struct OptionValidator
class OptionValue
class OptionValueArch
class OptionValueArgs
class OptionValueArray
class OptionValueBoolean
class OptionValueChar
class OptionValueDictionary
class OptionValueEnumeration
class OptionValueFileColonLine
class OptionValueFileSpec
class OptionValueFileSpecList
class OptionValueFormat
class OptionValueFormatEntity
class OptionValueLanguage
class OptionValuePathMappings
class OptionValueProperties
class OptionValueRegex
class OptionValueSInt64
class OptionValueString
class OptionValueUInt64
class OptionValueUUID
class PathMappingList
class PersistentExpressionState
class PipeBase
class PipePosix
A posix-based implementation of Pipe, a class that abtracts unix style pipes.
class PipeWindows
class Platform
A plug-in interface definition class for debug platform that includes many platform abilities such as:
class PlatformAppleSimulator
class PlatformDarwin
class PlatformDarwinDevice
Abstract Darwin platform with a potential device support directory.
class PlatformDarwinKernel
class PlatformList
class PlatformMacOSX
class PlatformProperties
class PlatformQemuUser
class PlatformRemoteAppleBridge
class PlatformRemoteAppleTV
class PlatformRemoteAppleWatch
class PlatformRemoteAppleXR
class PlatformRemoteDarwinDevice
class PlatformRemoteiOS
class PlatformRemoteMacOSX
class PlatformWasm
class PlatformWasmRemoteGDBServer
class PlatformWindows
class PluginInterface
class PluginManager
struct PluginNamespace
class PosixPlatformCommandOptionValidator
class PostMortemProcess
Base class for all processes that don't represent a live process, such as coredumps or processes traced in the past.
class Predicate
A C++ wrapper class for providing threaded access to a value of type T.
class Process
A plug-in interface definition class for debugging a process.
class ProcessAttachInfo
class ProcessDebugger
class ProcessExperimentalProperties
class ProcessInfo
class ProcessInfoList
class ProcessInstanceInfo
class ProcessInstanceInfoMatch
class ProcessKDPLog
class ProcessLauncher
class ProcessLauncherPosixFork
class ProcessLauncherWindows
class ProcessLaunchInfo
class ProcessModID
class ProcessPOSIXLog
class ProcessProperties
class ProcessRunLock
A class used to prevent the process from starting while other threads are accessing its data, and prevent access to its data while it is running.
class ProcessStructReader
class ProcessTrace
Class that represents a defunct process loaded on memory via the "trace load" command.
class ProcessWindows
class ProcessWindowsData
class ProcessWindowsLog
class ProcThreadAttributeList
This class manages the lifetime of a PROC_THREAD_ATTRIBUTE_LIST, which is used with STARTUPINFOEX.
class Progress
A Progress indicator helper class.
class ProgressEventData
class Properties
class Property
struct PropertyCollectionDefinition
struct PropertyDefinition
class ProtocolServer
class PseudoConsole
class PseudoInstruction
class PseudoTerminal
A pseudo terminal helper class.
class Queue
class QueueImpl
class QueueItem
class QueueList
struct Range
struct RangeData
class RangeDataVector
class RangeVector
struct Rd
class RealpathPrefixes
class RecognizedStackFrame
This class provides extra information about a stack frame that was provided by a specific stack frame recognizer.
struct RegInfo
class RegInfoBasedABI
class RegisterCheckpoint
class RegisterContext
class RegisterContextDummy
class RegisterContextHistory
class RegisterContextLinux_x86
class RegisterContextThreadMemory
class RegisterContextUnifiedCore
class RegisterContextUnwind
class RegisterContextWindows
struct RegisteredPluginInfo
class RegisterFlags
struct RegisterInfo
Every register is described in detail including its name, alternate name (optional), encoding, size in bytes and the default display format.
class RegisterInfoAndSetInterface
class RegisterInfoInterface
RegisterInfo interface to patch RegisterInfo structure for archs.
struct RegisterInfos_x86_64_with_base_shared
struct RegisterSet
Registers are grouped into register sets.
class RegisterTypeBuilder
class RegisterTypeBuilderClang
class RegisterValue
struct RegsetDesc
class RegularExpression
class RemoteAwarePlatform
A base class for platforms which automatically want to be able to forward operations to a remote platform instance (such as PlatformRemoteGDBServer).
class REPL
class ReportRetriever
struct ResumeAction
class ResumeActionList
class RichManglingContext
Uniform wrapper for access to rich mangling information from different providers.
class RISCVSingleStepBreakpointLocationsPredictor
class RotatingLogHandler
struct Rs
class Runtime
class RustTreeSitterHighlighter
struct RxC
Unified RISC-V C register encoding.
class SaveCoreOptions
class SBCommandReturnObjectImpl
class SBLaunchInfoImpl
class Scalar
class ScratchTypeSystemClang
The TypeSystemClang instance used for the scratch ASTContext in a lldb::Target.
class ScriptedBreakpointInterface
class ScriptedBreakpointPythonInterface
class ScriptedFrame
class ScriptedFrameInterface
class ScriptedFrameProvider
struct ScriptedFrameProviderDescriptor
This struct contains the metadata needed to instantiate a frame provider and optional filters to control which threads it applies to.
class ScriptedFrameProviderInterface
class ScriptedFrameProviderPythonInterface
class ScriptedFramePythonInterface
class ScriptedInterface
class ScriptedInterfaceUsages
class ScriptedMetadata
class ScriptedPlatformInterface
class ScriptedPlatformPythonInterface
class ScriptedProcess
class ScriptedProcessInterface
class ScriptedProcessPythonInterface
class ScriptedPythonInterface
class ScriptedStackFrameRecognizer
Python implementation for frame recognizers.
class ScriptedStopHookInterface
class ScriptedStopHookPythonInterface
class ScriptedSyntheticChildren
class ScriptedThread
class ScriptedThreadInterface
class ScriptedThreadPlan
class ScriptedThreadPlanInterface
class ScriptedThreadPlanPythonInterface
class ScriptedThreadPythonInterface
class ScriptInterpreter
class ScriptInterpreterIORedirect
class ScriptInterpreterLocker
class ScriptInterpreterLua
class ScriptInterpreterNone
class ScriptInterpreterPython
Abstract interface for the Python script interpreter.
class ScriptInterpreterPythonImpl
class ScriptInterpreterPythonInterfaces
class ScriptObject
struct ScriptSummaryFormat
class Searcher
General Outline: Provides the callback and search depth for the SearchFilter search.
class SearchFilter
General Outline: Provides the callback and search depth for the SearchFilter search.
class SearchFilterByModule
This is a SearchFilter that restricts the search to a given module.
class SearchFilterByModuleList
class SearchFilterByModuleListAndCU
class SearchFilterForUnconstrainedSearches
"lldb/Core/SearchFilter.h" This is a SearchFilter that searches through all modules.
class Section
class SectionList
class SectionLoadHistory
class SectionLoadList
class SemaSourceWithPriorities
A ExternalSemaSource multiplexer that prioritizes its sources.
class SerialPort
struct SharedCacheImageInfo
class SharedSocket
class SingleStepBreakpointLocationsPredictor
class Socket
class SocketAddress
struct SourceLanguage
A type-erased pair of llvm::dwarf::SourceLanguageName and version.
class SourceLocationSpec
"lldb/Core/SourceLocationSpec.h" A source location specifier class.
class SourceManager
class SourceManagerImpl
struct SourceModule
Information needed to import a source-language module.
class StackFrame
This base class provides an interface to stack frames.
class StackFrameList
class StackFrameRecognizer
A base class for frame recognizers.
class StackFrameRecognizerManager
Class that provides a registry of known stack frame recognizers.
class StackID
class StandardTildeExpressionResolver
class StatisticsMap
A class to count time for plugins.
struct StatisticsOptions
class StatsDuration
struct StatsSuccessFail
A class to count success/fail statistics.
class Status
An error handling class.
class Statusline
class StopCondition
class StopInfo
class StopInfoBreakpoint
class StopInfoException
class StopInfoExec
class StopInfoFork
class StopInfoHistoryBoundary
class StopInfoInterrupt
class StopInfoMachException
class StopInfoProcessorTrace
class StopInfoThreadPlan
class StopInfoTrace
class StopInfoUnixSignal
class StopInfoVFork
class StopInfoVForkDone
class StopInfoWatchpoint
struct StoppedExecutionContext
A wrapper class representing an execution context with non-null Target and Process pointers, a locked API mutex and a locked ProcessRunLock.
class Stoppoint
class StoppointCallbackContext
General Outline: When we hit a breakpoint we need to package up whatever information is needed to evaluate breakpoint commands and conditions.
class StoppointHitCounter
class StoppointSite
class StopPointSiteList
class Stream
A stream class that can stream formatted output to a file.
class StreamAsynchronousIO
A stream meant for asynchronously printing output.
class StreamBuffer
class StreamFile
class StreamGDBRemote
class StreamLogHandler
class StreamString
class StreamTee
class StringList
struct StringSummaryFormat
class StringTableReader
Many cache files require string tables to store data efficiently.
class StructuredData
A class which can hold structured data.
class StructuredDataDarwinLog
class StructuredDataImpl
class StructuredDataPlugin
Plugin that supports process-related structured data sent asynchronously from the debug monitor (e.g.
class SummaryStatistics
A class that represents statistics about a TypeSummaryProviders invocations.
class SummaryStatisticsCache
A class that wraps a std::map of SummaryStatistics objects behind a mutex.
class SupportFile
Wraps a FileSpec and an optional Checksum.
class SupportFileList
A list of support files for a CompileUnit.
struct SVR4LibraryInfo
class SwiftTreeSitterHighlighter
class Symbol
class SymbolChangeEventData
class SymbolContext
Defines a symbol context baton that can be handed other debug core functions.
class SymbolContextList
Defines a list of symbol context objects.
class SymbolContextScope
"lldb/Symbol/SymbolContextScope.h" Inherit from this if your object is part of a symbol context and can reconstruct its symbol context.
class SymbolContextSpecifier
class SymbolFile
Provides public interface for all SymbolFiles.
class SymbolFileCommon
Containing protected virtual methods for child classes to override.
class SymbolFileCTF
class SymbolFileJSON
class SymbolFileOnDemand
SymbolFileOnDemand wraps an actual SymbolFile by providing on demand symbol parsing/indexing to improve performance.
class SymbolFileType
struct SymbolLocation
Stores a function module spec, symbol name and possibly an alternate symbol name.
class SymbolLocator
class SymbolLocatorDebuginfod
class SymbolLocatorDebugSymbols
class SymbolLocatorDefault
class Symbols
class SymbolVendor
class Symtab
class SyntheticChildren
class SyntheticChildrenFrontEnd
class SyntheticFrameProvider
Base class for all synthetic frame providers.
class SyntheticStackFrameList
A StackFrameList that wraps another StackFrameList and uses a SyntheticFrameProvider to lazily provide frames from either the provider or the underlying real stack frame list.
class SyntheticValueProviderFrontEnd
class SystemInitializer
class SystemInitializerCommon
Initializes common lldb functionality.
class SystemInitializerFull
Initializes lldb.
class SystemLifetimeManager
class SystemLogHandler
Log handler that emits log messages to the operating system log.
class SystemRuntime
A plug-in interface definition class for system runtimes.
struct TableValidator
struct TableValidator< eArgTypeLastArg >
class TaggedASTDecl
class TaggedASTType
class Target
class TargetExperimentalProperties
class TargetList
class TargetProperties
class TargetStats
A class that represents statistics for a since lldb_private::Target.
class TargetThreadWindows
class TCPSocket
class TeeLogHandler
A T-style log handler that multiplexes messages to two log handlers.
class Terminal
class TerminalState
A RAII-friendly terminal state saving/restoring class.
struct TestingProperties
Global properties used in the LLDB testsuite.
class Thread
class ThreadCollection
class ThreadedCommunication
"lldb/Core/ThreadedCommunication.h" Variation of Communication that supports threaded reads.
class ThreadLauncher
class ThreadList
class ThreadPlan
class ThreadPlanAssemblyTracer
class ThreadPlanBase
class ThreadPlanCallFunction
class ThreadPlanCallFunctionUsingABI
class ThreadPlanCallOnFunctionExit
This thread plan calls a function object when the current function exits.
class ThreadPlanCallUserExpression
class ThreadPlanNull
class ThreadPlanRunToAddress
class ThreadPlanShouldStopHere
class ThreadPlanSingleThreadTimeout
class ThreadPlanStack
class ThreadPlanStackMap
class ThreadPlanStepInRange
class ThreadPlanStepInstruction
class ThreadPlanStepOut
class ThreadPlanStepOverBreakpoint
class ThreadPlanStepOverRange
class ThreadPlanStepRange
class ThreadPlanStepThrough
class ThreadPlanStepUntil
class ThreadPlanTracer
class ThreadPostMortemTrace
Thread implementation used for representing threads gotten from trace session files, which are similar to threads from core files.
class ThreadProperties
class ThreadSafeDenseMap
class ThreadSafeDenseSet
class ThreadSafeValue
class ThreadSpec
struct ThreadStopInfo
class TieredFormatterContainer
class TildeExpressionResolver
class Timeout
class TimeoutResumeAll
class Timer
A timer class that simplifies common timing metrics.
class Trace
A plug-in interface definition class for trace information.
struct TraceBinaryData
struct TraceCpuState
class TraceCursor
Class used for iterating over the instructions of a thread's trace, among other kinds of information.
class TraceDumper
Class used to dump the instructions of a TraceCursor using its current state and granularity.
struct TraceDumperOptions
Class that holds the configuration used by TraceDumper for traversing and dumping instructions.
class TraceExporter
A plug-in interface definition class for trace exporters.
struct TraceGetBinaryDataRequest
jLLDBTraceGetBinaryData gdb-remote packet
struct TraceGetStateRequest
}
struct TraceGetStateResponse
class TraceHTR
Top-level HTR class See lldb/docs/htr.rst for comprehensive HTR documentation.
struct TraceIntelPTGetStateResponse
struct TraceIntelPTStartRequest
jLLDBTraceStart gdb-remote packet
struct TraceStartRequest
jLLDBTraceStart gdb-remote packet
struct TraceStopRequest
jLLDBTraceStop gdb-remote packet
struct TraceSupportedResponse
jLLDBTraceSupported gdb-remote packet
struct TraceThreadState
struct TrackingOutputBuffer
An OutputBuffer which keeps a record of where certain parts of a demangled name begin/end (e.g., basename, scope, argument list, etc.).
class TreeSitterHighlighter
class Type
struct type128
struct type256
class TypeAndOrName
Sometimes you can find the name of the type corresponding to an object, but we don't have debug information for it.
class TypeCategoryImpl
class TypeCategoryMap
class TypedBaton
class TypeEnumMemberImpl
class TypeEnumMemberListImpl
class TypeFilterImpl
class TypeFormatImpl
class TypeFormatImpl_EnumType
class TypeFormatImpl_Format
class TypeImpl
class TypeList
class TypeListImpl
class TypeMap
class TypeMatcher
Class for matching type names.
class TypeMemberFunctionImpl
class TypeMemberImpl
class TypeNameSpecifierImpl
class TypePayloadClang
The implementation of lldb::Type's m_payload field for TypeSystemClang.
class TypeQuery
A class that contains all state required for type lookups.
class TypeResults
This class tracks the state and results of a TypeQuery.
class TypeSummaryImpl
class TypeSummaryOptions
class TypeSystem
Interface for representing a type system.
class TypeSystemClang
A TypeSystem implementation based on Clang.
class TypeSystemMap
class UDPSocket
class UnimplementedError
class UniqueCStringMap
class UnixSignals
class UntypedBaton
class Unwind
class UnwindAssembly
class UnwindLLDB
class UnwindPlan
class UnwindTable
struct URI
class UserExpression
Encapsulates a one-time expression for use in lldb.
class UserID
A mix in class that contains a generic user ID.
class UserIDResolver
An abstract interface for things that know how to map numeric user/group IDs into names.
class UtilityFunction
"lldb/Expression/UtilityFunction.h" Encapsulates a bit of source code that provides a function that is callable
class UtilityFunctionScope
RAII guard that should be acquired when an utility function is called within a given process.
class UUID
Represents UUID's of various sizes.
class Value
class ValueImpl
class ValueList
class ValueLocker
struct ValueMapIterator
class ValueObject
ValueObject:
class ValueObjectCast
A ValueObject that represents a given value represented as a different type.
class ValueObjectChild
A child of another ValueObject.
class ValueObjectConstResult
A frozen ValueObject copied into host memory.
class ValueObjectConstResultCast
class ValueObjectConstResultChild
class ValueObjectConstResultImpl
A class wrapping common implementation details for operations in ValueObjectConstResult (& Child) that may need to jump from the host memory space into the target's memory space.
class ValueObjectDynamicValue
A ValueObject that represents memory at a given address, viewed as some set lldb type.
class ValueObjectList
A collection of ValueObject values that.
class ValueObjectMemory
A ValueObject that represents memory at a given address, viewed as some set lldb type.
class ValueObjectPrinter
class ValueObjectRecognizerSynthesizedValue
ValueObject subclass that presents the passed ValueObject as a recognized value with the specified ValueType.
class ValueObjectRegister
class ValueObjectRegisterSet
class ValueObjectSynthetic
A ValueObject that obtains its children from some source other than real information.
class ValueObjectUpdater
A value object class that is seeded with the static variable value and it vends the user facing value object.
class ValueObjectVariable
A ValueObject that contains a root variable that may or may not have children.
class ValueObjectVTable
A class that represents a virtual function table for a C++ class.
class Variable
struct VariableAnnotation
Structured data for a single variable annotation.
class VariableAnnotator
Tracks live variable annotations across instructions and produces per-instruction "events" like name = RDI or name = <undef>.
class VariableList
class VerboseTrapFrameRecognizer
When a thread stops, it checks the current frame contains a Verbose Trap diagnostic.
class VerboseTrapRecognizedStackFrame
Holds the stack frame that caused the Verbose trap and the inlined stop reason message.
class VirtualDataExtractor
A DataExtractor subclass that allows reading data at virtual addresses using a lookup table that maps virtual address ranges to physical offsets.
class VMRange
struct WaitStatus
class Watchpoint
class WatchpointAlgorithms
class WatchpointList
This class is used by Watchpoint to manage a list of watchpoints,.
class WatchpointOptions
"lldb/Breakpoint/WatchpointOptions.h" Class that manages the options on a watchpoint.
class WatchpointResource
class Win32Error
class WritableDataBuffer
class WritableDataBufferLLVM
class x86AssemblyInspectionEngine
class XcodeSDK
An abstraction for Xcode-style SDKs that works like ArchSpec.
class XMLDocument
class XMLNode
struct XMMReg
struct XSAVE
struct XSAVE_HDR
struct YMM
struct YMMHReg
struct YMMReg
class ZipFile
In Android API level 23 and above, bionic dynamic linker is able to load .so file directly from APK or .zip file.
class ZipFileResolver
In Android API level 23 and above, bionic dynamic linker is able to load .so file directly from APK or .zip file.
Typedefs
using BreakpointLocations = std::vector<lldb::addr_t>
using GetPluginInfo = std::function<std::vector<RegisteredPluginInfo>()>
using SetPluginEnabled = std::function<bool(llvm::StringRef, bool)>
typedef std::vector< FormattersMatchCandidate > FormattersMatchVector
typedef std::vector< lldb::LanguageType > CandidateLanguagesVector
typedef std::vector< std::unique_ptr< Diagnostic > > DiagnosticList
using HardwareBreakpointMap = std::map<lldb::addr_t, HardwareBreakpoint>
typedef std::vector< ProcessInstanceInfo > ProcessInstanceInfoList
typedef HOST_INFO_TYPE HostInfo
typedef HostProcessPosix HostNativeProcess
typedef HostThreadPosix HostNativeThread
typedef LockFilePosix LockFile
using MainLoop = MainLoopPosix
typedef PipePosix Pipe
using PTY = PseudoTerminal
typedef int NativeSocket
typedef NativeSocket shared_fd_t
using handle_t = void *
typedef void * XMLNodeImpl
typedef void * XMLDocumentImpl
typedef std::vector< std::string > NamePath
typedef std::function< bool(const XMLNode &node)> NodeCallback
typedef std::function< bool(const llvm::StringRef &name, const llvm::StringRef &value)> AttributeCallback
typedef std::vector< std::tuple< lldb::CommandArgumentType, const char * > > OptionGroupFormatUsageTextVector
typedef std::vector< std::tuple< std::string, int, std::string > > OptionArgVector
typedef std::shared_ptr< OptionArgVector > OptionArgVectorSP
typedef std::vector< OptionArgElement > OptionElementVector
typedef lldb::ABISP(* ABICreateInstance) (lldb::ProcessSP process_sp, const ArchSpec &arch)
typedef std::unique_ptr< Architecture >(* ArchitectureCreateInstance) (const ArchSpec &arch)
typedef lldb::DisassemblerSP(* DisassemblerCreateInstance) (const ArchSpec &arch, const char *flavor, const char *cpu, const char *features)
typedef DynamicLoader *(* DynamicLoaderCreateInstance) (Process *process, bool force)
typedef lldb::JITLoaderSP(* JITLoaderCreateInstance) (Process *process, bool force)
typedef ObjectContainer *(* ObjectContainerCreateInstance) (const lldb::ModuleSP &module_sp, lldb::DataBufferSP &data_sp, lldb::offset_t data_offset, const FileSpec *file, lldb::offset_t offset, lldb::offset_t length)
typedef ObjectContainer *(* ObjectContainerCreateMemoryInstance) (const lldb::ModuleSP &module_sp, lldb::WritableDataBufferSP data_sp, const lldb::ProcessSP &process_sp, lldb::addr_t offset)
typedef size_t(* ObjectFileGetModuleSpecifications) (const FileSpec &file, lldb::DataExtractorSP &extractor_sp, lldb::offset_t data_offset, lldb::offset_t file_offset, lldb::offset_t length, ModuleSpecList &module_specs)
typedef ObjectFile *(* ObjectFileCreateInstance) (const lldb::ModuleSP &module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const FileSpec *file, lldb::offset_t file_offset, lldb::offset_t length)
typedef ObjectFile *(* ObjectFileCreateMemoryInstance) (const lldb::ModuleSP &module_sp, lldb::WritableDataBufferSP data_sp, const lldb::ProcessSP &process_sp, lldb::addr_t offset)
typedef bool(* ObjectFileSaveCore) (const lldb::ProcessSP &process_sp, lldb_private::SaveCoreOptions &options, Status &error)
typedef EmulateInstruction *(* EmulateInstructionCreateInstance) (const ArchSpec &arch, InstructionType inst_type)
typedef OperatingSystem *(* OperatingSystemCreateInstance) (Process *process, bool force)
typedef Language *(* LanguageCreateInstance) (lldb::LanguageType language)
typedef LanguageRuntime *(* LanguageRuntimeCreateInstance) (Process *process, lldb::LanguageType language)
typedef lldb::CommandObjectSP(* LanguageRuntimeGetCommandObject) (CommandInterpreter &interpreter)
typedef lldb::BreakpointPreconditionSP(* LanguageRuntimeGetExceptionPrecondition) (lldb::LanguageType language, bool throw_bp)
typedef lldb::StructuredDataPluginSP(* StructuredDataPluginCreateInstance) (Process &process)
typedef Status(* StructuredDataFilterLaunchInfo) (ProcessLaunchInfo &launch_info, Target *target)
typedef SystemRuntime *(* SystemRuntimeCreateInstance) (Process *process)
typedef lldb::PlatformSP(* PlatformCreateInstance) (bool force, const ArchSpec *arch)
typedef lldb::ProcessSP(* ProcessCreateInstance) (lldb::TargetSP target_sp, lldb::ListenerSP listener_sp, const FileSpec *crash_file_path, bool can_connect)
typedef lldb::ProtocolServerUP(* ProtocolServerCreateInstance) ()
typedef lldb::RegisterTypeBuilderSP(* RegisterTypeBuilderCreateInstance) (Target &target)
typedef lldb::ScriptInterpreterSP(* ScriptInterpreterCreateInstance) (Debugger &debugger)
typedef FileSpec(* ScriptInterpreterGetPath) ()
typedef llvm::Expected< lldb::SyntheticFrameProviderSP >(* ScriptedFrameProviderCreateInstance) (lldb::StackFrameListSP input_frames, const lldb_private::ScriptedFrameProviderDescriptor &descriptor)
typedef llvm::Expected< lldb::SyntheticFrameProviderSP >(* SyntheticFrameProviderCreateInstance) (lldb::StackFrameListSP input_frames, const std::vector< lldb_private::ThreadSpec > &thread_specs)
typedef SymbolFile *(* SymbolFileCreateInstance) (lldb::ObjectFileSP objfile_sp)
typedef SymbolVendor *(* SymbolVendorCreateInstance) (const lldb::ModuleSP &module_sp, lldb_private::Stream *feedback_strm)
typedef SymbolLocator *(* SymbolLocatorCreateInstance) ()
typedef std::optional< ModuleSpec >(* SymbolLocatorLocateExecutableObjectFile) (const ModuleSpec &module_spec)
typedef std::optional< FileSpec >(* SymbolLocatorFindSymbolFileInBundle) (const FileSpec &dsym_bundle_fspec, const UUID *uuid, const ArchSpec *arch)
typedef std::optional< FileSpec >(* SymbolLocatorLocateExecutableSymbolFile) (const ModuleSpec &module_spec, const FileSpecList &default_search_paths)
typedef bool(* SymbolLocatorDownloadObjectAndSymbolFile) (ModuleSpec &module_spec, Status &error, bool force_lookup, bool copy_executable)
using BreakpointHitCallback
typedef bool(* WatchpointHitCallback) (void *baton, StoppointCallbackContext *context, lldb::user_id_t watch_id)
typedef bool(* ThreadPlanShouldStopHereCallback) (ThreadPlan *current_plan, Flags &flags, lldb::FrameComparison operation, Status &status, void *baton)
typedef lldb::ThreadPlanSP(* ThreadPlanStepFromHereCallback) (ThreadPlan *current_plan, Flags &flags, lldb::FrameComparison operation, Status &status, void *baton)
typedef UnwindAssembly *(* UnwindAssemblyCreateInstance) (const ArchSpec &arch)
typedef lldb::MemoryHistorySP(* MemoryHistoryCreateInstance) (const lldb::ProcessSP &process_sp)
typedef lldb::InstrumentationRuntimeType(* InstrumentationRuntimeGetType) ()
typedef lldb::InstrumentationRuntimeSP(* InstrumentationRuntimeCreateInstance) (const lldb::ProcessSP &process_sp)
typedef lldb::TypeSystemSP(* TypeSystemCreateInstance) (lldb::LanguageType language, Module *module, Target *target)
typedef lldb::REPLSP(* REPLCreateInstance) (Status &error, lldb::LanguageType language, Debugger *debugger, Target *target, const char *repl_options)
typedef bool(* ScriptedInterfaceCreateInstance) (lldb::ScriptLanguage language, ScriptedInterfaceUsages usages)
typedef Highlighter *(* HighlighterCreateInstance) (lldb::LanguageType language)
typedef int(* ComparisonFunction) (const void *, const void *)
typedef void(* DebuggerInitializeCallback) (Debugger &debugger)
typedef llvm::SmallString< 256 > PathSmallString
typedef llvm::sys::DynamicLibrary(* LoadPluginCallbackType) (const lldb::DebuggerSP &debugger_sp, const FileSpec &spec, Status &error)
using OptionEnumValues = llvm::ArrayRef<OptionEnumValueElement>
typedef struct lldb_private::type128 type128
typedef struct lldb_private::type256 type256
using ValueObjectProviderTy
Functor that returns a ValueObjectSP for a variable given its name and the StackFrame of interest.
typedef void(* DebuggerDestroyCallback) (lldb::user_id_t debugger_id, void *baton)
typedef bool(* CommandOverrideCallbackWithResult) (void *baton, const char **argv, lldb_private::CommandReturnObject &result)
typedef std::shared_ptr< DebugMacros > DebugMacrosSP
using CallSiteParameterArray = llvm::SmallVector<CallSiteParameter, 0>
A vector of CallSiteParameter.
typedef TaggedASTType< 0 > TypeFromParser
typedef TaggedASTType< 1 > TypeFromUser
typedef std::map< lldb::InstrumentationRuntimeType, lldb::InstrumentationRuntimeSP > InstrumentationRuntimeCollection
typedef std::vector< lldb::ThreadSP > HistoryThreads
typedef llvm::SmallVector< lldb::addr_t, 6 > MmapArgList
using StatsClock = std::chrono::high_resolution_clock
using StatsTimepoint = std::chrono::time_point<StatsClock>
typedef std::shared_ptr< SummaryStatistics > SummaryStatisticsSP
typedef void(* LLDBAssertCallback) (llvm::StringRef message, llvm::StringRef backtrace, llvm::StringRef prompt)
The default LLDB assert callback, which prints to stderr.
typedef NonNullSharedPtr< lldb_private::SupportFile > SupportFileNSP
using RISCVInst
typedef std::function< bool(llvm::Expected< MemoryRegionInfo >)> LinuxMapCallback
typedef std::shared_ptr< IDebugDelegate > DebugDelegateSP
typedef std::shared_ptr< DebuggerThread > DebuggerThreadSP
typedef std::shared_ptr< ExceptionRecord > ExceptionRecordSP
typedef std::unique_ptr< ExceptionRecord > ExceptionRecordUP
typedef std::shared_ptr< ProcessWindows > ProcessWindowsSP
typedef std::shared_ptr< NativeDebugDelegate > NativeDebugDelegateSP
typedef std::unique_ptr< lldb_private::HTRBlockLayer > HTRBlockLayerUP
typedef std::unique_ptr< lldb_private::HTRInstructionLayer > HTRInstructionLayerUP
typedef llvm::Expected< lldb::TraceSP >(* TraceCreateInstanceFromBundle) (const llvm::json::Value &trace_bundle_description, llvm::StringRef session_file_dir, lldb_private::Debugger &debugger)
Trace.
typedef llvm::Expected< lldb::TraceSP >(* TraceCreateInstanceForLiveProcess) (Process &process)
typedef llvm::Expected< lldb::TraceExporterUP >(* TraceExporterCreateInstance) ()
typedef lldb::CommandObjectSP(* ThreadTraceExportCommandCreator) (CommandInterpreter &interpreter)
Enumerations
enum DiagnosticOrigin {
eDiagnosticOriginUnknown = 0 , eDiagnosticOriginLLDB , eDiagnosticOriginClang , eDiagnosticOriginSwift ,
eDiagnosticOriginLLVM
}
enum class ExpeditedRegs { Minimal , Full }
enum class SystemLog : Log::MaskType { System = Log::ChannelFlag<0> }
enum StepType {
eStepTypeNone , eStepTypeTrace , eStepTypeTraceOver , eStepTypeInto ,
eStepTypeOver , eStepTypeOut , eStepTypeScripted
}
enum AddressType { eAddressTypeInvalid = 0 , eAddressTypeFile , eAddressTypeLoad , eAddressTypeHost }
enum class AddressClass {
eInvalid , eUnknown , eCode , eCodeAlternateISA ,
eData , eDebug , eRuntime
}
enum Vote { eVoteNo = -1 , eVoteNoOpinion = 0 , eVoteYes = 1 }
enum ArchitectureType {
eArchTypeInvalid , eArchTypeMachO , eArchTypeELF , eArchTypeCOFF ,
eArchTypeXCOFF , kNumArchTypes
}
enum VarSetOperationType {
eVarSetOperationReplace , eVarSetOperationInsertBefore , eVarSetOperationInsertAfter , eVarSetOperationRemove ,
eVarSetOperationAppend , eVarSetOperationClear , eVarSetOperationAssign , eVarSetOperationInvalid
}
Settable state variable types.
enum ArgumentRepetitionType {
eArgRepeatPlain , eArgRepeatOptional , eArgRepeatPlus , eArgRepeatStar ,
eArgRepeatRange , eArgRepeatPairPlain , eArgRepeatPairOptional , eArgRepeatPairPlus ,
eArgRepeatPairStar , eArgRepeatPairRange , eArgRepeatPairRangeOptional
}
enum SortOrder { eSortOrderNone , eSortOrderByAddress , eSortOrderByName , eSortOrderBySize }
enum LazyBool { eLazyBoolCalculate = -1 , eLazyBoolNo = 0 , eLazyBoolYes = 1 }
enum InstructionType { eInstructionTypeAny , eInstructionTypePrologueEpilogue , eInstructionTypePCModifying , eInstructionTypeAll }
Instruction types.
enum FormatCategoryItem { eFormatCategoryItemSummary = 1 , eFormatCategoryItemFilter = 1 << 1 , eFormatCategoryItemSynth = 1 << 2 , eFormatCategoryItemFormat = 1 << 3 }
Format category entry types.
enum ExecutionPolicy { eExecutionPolicyOnlyWhenNeeded , eExecutionPolicyNever , eExecutionPolicyAlways , eExecutionPolicyTopLevel }
Expression execution policies.
enum ScriptedCommandSynchronicity { eScriptedCommandSynchronicitySynchronous , eScriptedCommandSynchronicityAsynchronous , eScriptedCommandSynchronicityCurrentValue }
enum LanguageRuntimeDescriptionDisplayVerbosity { eLanguageRuntimeDescriptionDisplayVerbosityCompact , eLanguageRuntimeDescriptionDisplayVerbosityFull }
enum MemoryModuleLoadLevel { eMemoryModuleLoadLevelMinimal , eMemoryModuleLoadLevelPartial , eMemoryModuleLoadLevelComplete }
enum FollowForkMode { eFollowParent , eFollowChild }
enum class LineStatus { Success , Status , Done }
enum class TypeValidatorResult : bool { Success = true , Failure = false }
enum class CompilerContextKind : uint16_t {
Invalid = 0 , TranslationUnit = 1 , Module = 1 << 1 , Namespace = 1 << 2 ,
ClassOrStruct = 1 << 3 , Union = 1 << 5 , Function = 1 << 6 , Variable = 1 << 7 ,
Enum = 1 << 8 , Typedef = 1 << 9 , Builtin = 1 << 10 , Any = 1 << 15 ,
AnyType = Any | ClassOrStruct | Union | Enum | Typedef | Builtin , AnyDeclContext = Any | Namespace | ClassOrStruct | Union | Enum | Function , LLVM_MARK_AS_BITMASK_ENUM =(AnyDeclContext)
}
enum StatisticKind {
ExpressionSuccessful = 0 , ExpressionFailure = 1 , FrameVarSuccess = 2 , FrameVarFailure = 3 ,
StatisticMax = 4
}
enum LogHandlerKind {
eLogHandlerStream , eLogHandlerCallback , eLogHandlerCircular , eLogHandlerSystem ,
eLogHandlerDefault = eLogHandlerStream
}
enum LoadDependentFiles { eLoadDependentsDefault , eLoadDependentsYes , eLoadDependentsNo }
enum class IterationAction { Continue = 0 , Stop }
Useful for callbacks whose return type indicates whether to continue iteration or short-circuit.
enum class HistoryPCType { Returns , ReturnsNoZerothFrame , Calls }
Specifies the type of PCs when creating a HistoryThread.
enum class AppleArm64ExceptionClass : unsigned
enum MmapFlags { eMmapFlagsPrivate = 1 , eMmapFlagsAnon = 2 }
enum InlineStrategy { eInlineBreakpointsNever = 0 , eInlineBreakpointsHeaders , eInlineBreakpointsAlways }
enum LoadScriptFromSymFile { eLoadScriptFromSymFileTrue , eLoadScriptFromSymFileFalse , eLoadScriptFromSymFileWarn }
enum LoadCWDlldbinitFile { eLoadCWDlldbinitTrue , eLoadCWDlldbinitFalse , eLoadCWDlldbinitWarn }
enum ImportStdModule { eImportStdModuleFalse , eImportStdModuleFallback , eImportStdModuleTrue }
enum DynamicClassInfoHelper { eDynamicClassInfoHelperAuto , eDynamicClassInfoHelperRealizedClassesStruct , eDynamicClassInfoHelperCopyRealizedClassList , eDynamicClassInfoHelperGetRealizedClassList }
enum class CompletionMode { Normal , Partial , RewriteLine }
enum class LLDBLog : Log::MaskType {
API = Log::ChannelFlag<0> , AST = Log::ChannelFlag<1> , Breakpoints = Log::ChannelFlag<2> , Commands = Log::ChannelFlag<3> ,
Communication = Log::ChannelFlag<4> , Connection = Log::ChannelFlag<5> , DataFormatters = Log::ChannelFlag<6> , Demangle = Log::ChannelFlag<7> ,
DynamicLoader = Log::ChannelFlag<8> , Events = Log::ChannelFlag<9> , Expressions = Log::ChannelFlag<10> , Host = Log::ChannelFlag<11> ,
JITLoader = Log::ChannelFlag<12> , Language = Log::ChannelFlag<13> , MMap = Log::ChannelFlag<14> , Modules = Log::ChannelFlag<15> ,
Object = Log::ChannelFlag<16> , OS = Log::ChannelFlag<17> , Platform = Log::ChannelFlag<18> , Process = Log::ChannelFlag<19> ,
Script = Log::ChannelFlag<20> , State = Log::ChannelFlag<21> , Step = Log::ChannelFlag<22> , Symbols = Log::ChannelFlag<23> ,
SystemRuntime = Log::ChannelFlag<24> , Target = Log::ChannelFlag<25> , Temporary = Log::ChannelFlag<26> , Thread = Log::ChannelFlag<27> ,
Types = Log::ChannelFlag<28> , Unwind = Log::ChannelFlag<29> , Watchpoints = Log::ChannelFlag<30> , OnDemand = Log::ChannelFlag<31> ,
Source = Log::ChannelFlag<32> , Disassembler = Log::ChannelFlag<33> , InstrumentationRuntime = Log::ChannelFlag<34> , LLVM_MARK_AS_BITMASK_ENUM =(InstrumentationRuntime)
}
enum class NameMatch {
Ignore , Equals , Contains , StartsWith ,
EndsWith , RegularExpression
}
enum PredicateBroadcastType { eBroadcastNever , eBroadcastAlways , eBroadcastOnChange }
enum class KDPLog : Log::MaskType {
Async = Log::ChannelFlag<0> , Breakpoints = Log::ChannelFlag<1> , Comm = Log::ChannelFlag<2> , MemoryDataLong = Log::ChannelFlag<3> ,
MemoryDataShort = Log::ChannelFlag<4> , Memory = Log::ChannelFlag<5> , Packets = Log::ChannelFlag<6> , Process = Log::ChannelFlag<7> ,
Step = Log::ChannelFlag<8> , Thread = Log::ChannelFlag<9> , Watchpoints = Log::ChannelFlag<10>
}
enum class POSIXLog : Log::MaskType {
Breakpoints = Log::ChannelFlag<0> , Memory = Log::ChannelFlag<1> , Process = Log::ChannelFlag<2> , Ptrace = Log::ChannelFlag<3> ,
Registers = Log::ChannelFlag<4> , Thread = Log::ChannelFlag<5> , Watchpoints = Log::ChannelFlag<6> , Trace = Log::ChannelFlag<7>
}
enum ARM_ShifterType {
SRType_LSL , SRType_LSR , SRType_ASR , SRType_ROR ,
SRType_RRX , SRType_Invalid
}
enum MmapProt { eMmapProtNone = 0 , eMmapProtExec = 1 , eMmapProtRead = 2 , eMmapProtWrite = 4 }
enum {
k_first_gpr_arm = 0 , gpr_r0_arm = k_first_gpr_arm , gpr_r1_arm , gpr_r2_arm ,
gpr_r3_arm , gpr_r4_arm , gpr_r5_arm , gpr_r6_arm ,
gpr_r7_arm , gpr_r8_arm , gpr_r9_arm , gpr_r10_arm ,
gpr_r11_arm , gpr_r12_arm , gpr_r13_arm , gpr_sp_arm = gpr_r13_arm ,
gpr_r14_arm , gpr_lr_arm = gpr_r14_arm , gpr_r15_arm , gpr_pc_arm = gpr_r15_arm ,
gpr_cpsr_arm , k_last_gpr_arm = gpr_cpsr_arm , k_first_fpr_arm , fpu_s0_arm = k_first_fpr_arm ,
fpu_s1_arm , fpu_s2_arm , fpu_s3_arm , fpu_s4_arm ,
fpu_s5_arm , fpu_s6_arm , fpu_s7_arm , fpu_s8_arm ,
fpu_s9_arm , fpu_s10_arm , fpu_s11_arm , fpu_s12_arm ,
fpu_s13_arm , fpu_s14_arm , fpu_s15_arm , fpu_s16_arm ,
fpu_s17_arm , fpu_s18_arm , fpu_s19_arm , fpu_s20_arm ,
fpu_s21_arm , fpu_s22_arm , fpu_s23_arm , fpu_s24_arm ,
fpu_s25_arm , fpu_s26_arm , fpu_s27_arm , fpu_s28_arm ,
fpu_s29_arm , fpu_s30_arm , fpu_s31_arm , fpu_fpscr_arm ,
fpu_d0_arm , fpu_d1_arm , fpu_d2_arm , fpu_d3_arm ,
fpu_d4_arm , fpu_d5_arm , fpu_d6_arm , fpu_d7_arm ,
fpu_d8_arm , fpu_d9_arm , fpu_d10_arm , fpu_d11_arm ,
fpu_d12_arm , fpu_d13_arm , fpu_d14_arm , fpu_d15_arm ,
fpu_d16_arm , fpu_d17_arm , fpu_d18_arm , fpu_d19_arm ,
fpu_d20_arm , fpu_d21_arm , fpu_d22_arm , fpu_d23_arm ,
fpu_d24_arm , fpu_d25_arm , fpu_d26_arm , fpu_d27_arm ,
fpu_d28_arm , fpu_d29_arm , fpu_d30_arm , fpu_d31_arm ,
fpu_q0_arm , fpu_q1_arm , fpu_q2_arm , fpu_q3_arm ,
fpu_q4_arm , fpu_q5_arm , fpu_q6_arm , fpu_q7_arm ,
fpu_q8_arm , fpu_q9_arm , fpu_q10_arm , fpu_q11_arm ,
fpu_q12_arm , fpu_q13_arm , fpu_q14_arm , fpu_q15_arm ,
k_last_fpr_arm = fpu_q15_arm , exc_exception_arm , exc_fsr_arm , exc_far_arm ,
dbg_bvr0_arm , dbg_bvr1_arm , dbg_bvr2_arm , dbg_bvr3_arm ,
dbg_bvr4_arm , dbg_bvr5_arm , dbg_bvr6_arm , dbg_bvr7_arm ,
dbg_bvr8_arm , dbg_bvr9_arm , dbg_bvr10_arm , dbg_bvr11_arm ,
dbg_bvr12_arm , dbg_bvr13_arm , dbg_bvr14_arm , dbg_bvr15_arm ,
dbg_bcr0_arm , dbg_bcr1_arm , dbg_bcr2_arm , dbg_bcr3_arm ,
dbg_bcr4_arm , dbg_bcr5_arm , dbg_bcr6_arm , dbg_bcr7_arm ,
dbg_bcr8_arm , dbg_bcr9_arm , dbg_bcr10_arm , dbg_bcr11_arm ,
dbg_bcr12_arm , dbg_bcr13_arm , dbg_bcr14_arm , dbg_bcr15_arm ,
dbg_wvr0_arm , dbg_wvr1_arm , dbg_wvr2_arm , dbg_wvr3_arm ,
dbg_wvr4_arm , dbg_wvr5_arm , dbg_wvr6_arm , dbg_wvr7_arm ,
dbg_wvr8_arm , dbg_wvr9_arm , dbg_wvr10_arm , dbg_wvr11_arm ,
dbg_wvr12_arm , dbg_wvr13_arm , dbg_wvr14_arm , dbg_wvr15_arm ,
dbg_wcr0_arm , dbg_wcr1_arm , dbg_wcr2_arm , dbg_wcr3_arm ,
dbg_wcr4_arm , dbg_wcr5_arm , dbg_wcr6_arm , dbg_wcr7_arm ,
dbg_wcr8_arm , dbg_wcr9_arm , dbg_wcr10_arm , dbg_wcr11_arm ,
dbg_wcr12_arm , dbg_wcr13_arm , dbg_wcr14_arm , dbg_wcr15_arm ,
k_num_registers_arm , k_num_gpr_registers_arm = k_last_gpr_arm - k_first_gpr_arm + 1 , k_num_fpr_registers_arm = k_last_fpr_arm - k_first_fpr_arm + 1
}
enum {
k_first_gpr_arm64 , gpr_x0_arm64 = k_first_gpr_arm64 , gpr_x1_arm64 , gpr_x2_arm64 ,
gpr_x3_arm64 , gpr_x4_arm64 , gpr_x5_arm64 , gpr_x6_arm64 ,
gpr_x7_arm64 , gpr_x8_arm64 , gpr_x9_arm64 , gpr_x10_arm64 ,
gpr_x11_arm64 , gpr_x12_arm64 , gpr_x13_arm64 , gpr_x14_arm64 ,
gpr_x15_arm64 , gpr_x16_arm64 , gpr_x17_arm64 , gpr_x18_arm64 ,
gpr_x19_arm64 , gpr_x20_arm64 , gpr_x21_arm64 , gpr_x22_arm64 ,
gpr_x23_arm64 , gpr_x24_arm64 , gpr_x25_arm64 , gpr_x26_arm64 ,
gpr_x27_arm64 , gpr_x28_arm64 , gpr_fp_arm64 , gpr_lr_arm64 ,
gpr_sp_arm64 , gpr_pc_arm64 , gpr_cpsr_arm64 , gpr_w0_arm64 ,
gpr_w1_arm64 , gpr_w2_arm64 , gpr_w3_arm64 , gpr_w4_arm64 ,
gpr_w5_arm64 , gpr_w6_arm64 , gpr_w7_arm64 , gpr_w8_arm64 ,
gpr_w9_arm64 , gpr_w10_arm64 , gpr_w11_arm64 , gpr_w12_arm64 ,
gpr_w13_arm64 , gpr_w14_arm64 , gpr_w15_arm64 , gpr_w16_arm64 ,
gpr_w17_arm64 , gpr_w18_arm64 , gpr_w19_arm64 , gpr_w20_arm64 ,
gpr_w21_arm64 , gpr_w22_arm64 , gpr_w23_arm64 , gpr_w24_arm64 ,
gpr_w25_arm64 , gpr_w26_arm64 , gpr_w27_arm64 , gpr_w28_arm64 ,
k_last_gpr_arm64 = gpr_w28_arm64 , k_first_fpr_arm64 , fpu_v0_arm64 = k_first_fpr_arm64 , fpu_v1_arm64 ,
fpu_v2_arm64 , fpu_v3_arm64 , fpu_v4_arm64 , fpu_v5_arm64 ,
fpu_v6_arm64 , fpu_v7_arm64 , fpu_v8_arm64 , fpu_v9_arm64 ,
fpu_v10_arm64 , fpu_v11_arm64 , fpu_v12_arm64 , fpu_v13_arm64 ,
fpu_v14_arm64 , fpu_v15_arm64 , fpu_v16_arm64 , fpu_v17_arm64 ,
fpu_v18_arm64 , fpu_v19_arm64 , fpu_v20_arm64 , fpu_v21_arm64 ,
fpu_v22_arm64 , fpu_v23_arm64 , fpu_v24_arm64 , fpu_v25_arm64 ,
fpu_v26_arm64 , fpu_v27_arm64 , fpu_v28_arm64 , fpu_v29_arm64 ,
fpu_v30_arm64 , fpu_v31_arm64 , fpu_s0_arm64 , fpu_s1_arm64 ,
fpu_s2_arm64 , fpu_s3_arm64 , fpu_s4_arm64 , fpu_s5_arm64 ,
fpu_s6_arm64 , fpu_s7_arm64 , fpu_s8_arm64 , fpu_s9_arm64 ,
fpu_s10_arm64 , fpu_s11_arm64 , fpu_s12_arm64 , fpu_s13_arm64 ,
fpu_s14_arm64 , fpu_s15_arm64 , fpu_s16_arm64 , fpu_s17_arm64 ,
fpu_s18_arm64 , fpu_s19_arm64 , fpu_s20_arm64 , fpu_s21_arm64 ,
fpu_s22_arm64 , fpu_s23_arm64 , fpu_s24_arm64 , fpu_s25_arm64 ,
fpu_s26_arm64 , fpu_s27_arm64 , fpu_s28_arm64 , fpu_s29_arm64 ,
fpu_s30_arm64 , fpu_s31_arm64 , fpu_d0_arm64 , fpu_d1_arm64 ,
fpu_d2_arm64 , fpu_d3_arm64 , fpu_d4_arm64 , fpu_d5_arm64 ,
fpu_d6_arm64 , fpu_d7_arm64 , fpu_d8_arm64 , fpu_d9_arm64 ,
fpu_d10_arm64 , fpu_d11_arm64 , fpu_d12_arm64 , fpu_d13_arm64 ,
fpu_d14_arm64 , fpu_d15_arm64 , fpu_d16_arm64 , fpu_d17_arm64 ,
fpu_d18_arm64 , fpu_d19_arm64 , fpu_d20_arm64 , fpu_d21_arm64 ,
fpu_d22_arm64 , fpu_d23_arm64 , fpu_d24_arm64 , fpu_d25_arm64 ,
fpu_d26_arm64 , fpu_d27_arm64 , fpu_d28_arm64 , fpu_d29_arm64 ,
fpu_d30_arm64 , fpu_d31_arm64 , fpu_fpsr_arm64 , fpu_fpcr_arm64 ,
k_last_fpr_arm64 = fpu_fpcr_arm64 , exc_far_arm64 , exc_esr_arm64 , exc_exception_arm64 ,
dbg_bvr0_arm64 , dbg_bvr1_arm64 , dbg_bvr2_arm64 , dbg_bvr3_arm64 ,
dbg_bvr4_arm64 , dbg_bvr5_arm64 , dbg_bvr6_arm64 , dbg_bvr7_arm64 ,
dbg_bvr8_arm64 , dbg_bvr9_arm64 , dbg_bvr10_arm64 , dbg_bvr11_arm64 ,
dbg_bvr12_arm64 , dbg_bvr13_arm64 , dbg_bvr14_arm64 , dbg_bvr15_arm64 ,
dbg_bcr0_arm64 , dbg_bcr1_arm64 , dbg_bcr2_arm64 , dbg_bcr3_arm64 ,
dbg_bcr4_arm64 , dbg_bcr5_arm64 , dbg_bcr6_arm64 , dbg_bcr7_arm64 ,
dbg_bcr8_arm64 , dbg_bcr9_arm64 , dbg_bcr10_arm64 , dbg_bcr11_arm64 ,
dbg_bcr12_arm64 , dbg_bcr13_arm64 , dbg_bcr14_arm64 , dbg_bcr15_arm64 ,
dbg_wvr0_arm64 , dbg_wvr1_arm64 , dbg_wvr2_arm64 , dbg_wvr3_arm64 ,
dbg_wvr4_arm64 , dbg_wvr5_arm64 , dbg_wvr6_arm64 , dbg_wvr7_arm64 ,
dbg_wvr8_arm64 , dbg_wvr9_arm64 , dbg_wvr10_arm64 , dbg_wvr11_arm64 ,
dbg_wvr12_arm64 , dbg_wvr13_arm64 , dbg_wvr14_arm64 , dbg_wvr15_arm64 ,
dbg_wcr0_arm64 , dbg_wcr1_arm64 , dbg_wcr2_arm64 , dbg_wcr3_arm64 ,
dbg_wcr4_arm64 , dbg_wcr5_arm64 , dbg_wcr6_arm64 , dbg_wcr7_arm64 ,
dbg_wcr8_arm64 , dbg_wcr9_arm64 , dbg_wcr10_arm64 , dbg_wcr11_arm64 ,
dbg_wcr12_arm64 , dbg_wcr13_arm64 , dbg_wcr14_arm64 , dbg_wcr15_arm64 ,
k_num_registers_arm64 , k_num_gpr_registers_arm64 = k_last_gpr_arm64 - k_first_gpr_arm64 + 1 , k_num_fpr_registers_arm64 = k_last_fpr_arm64 - k_first_fpr_arm64 + 1
}
enum {
k_first_gpr_s390x , lldb_r0_s390x = k_first_gpr_s390x , lldb_r1_s390x , lldb_r2_s390x ,
lldb_r3_s390x , lldb_r4_s390x , lldb_r5_s390x , lldb_r6_s390x ,
lldb_r7_s390x , lldb_r8_s390x , lldb_r9_s390x , lldb_r10_s390x ,
lldb_r11_s390x , lldb_r12_s390x , lldb_r13_s390x , lldb_r14_s390x ,
lldb_r15_s390x , lldb_acr0_s390x , lldb_acr1_s390x , lldb_acr2_s390x ,
lldb_acr3_s390x , lldb_acr4_s390x , lldb_acr5_s390x , lldb_acr6_s390x ,
lldb_acr7_s390x , lldb_acr8_s390x , lldb_acr9_s390x , lldb_acr10_s390x ,
lldb_acr11_s390x , lldb_acr12_s390x , lldb_acr13_s390x , lldb_acr14_s390x ,
lldb_acr15_s390x , lldb_pswm_s390x , lldb_pswa_s390x , k_last_gpr_s390x = lldb_pswa_s390x ,
k_first_fpr_s390x , lldb_f0_s390x = k_first_fpr_s390x , lldb_f1_s390x , lldb_f2_s390x ,
lldb_f3_s390x , lldb_f4_s390x , lldb_f5_s390x , lldb_f6_s390x ,
lldb_f7_s390x , lldb_f8_s390x , lldb_f9_s390x , lldb_f10_s390x ,
lldb_f11_s390x , lldb_f12_s390x , lldb_f13_s390x , lldb_f14_s390x ,
lldb_f15_s390x , lldb_fpc_s390x , k_last_fpr_s390x = lldb_fpc_s390x , k_first_linux_s390x ,
lldb_orig_r2_s390x = k_first_linux_s390x , lldb_last_break_s390x , lldb_system_call_s390x , k_last_linux_s390x = lldb_system_call_s390x ,
k_num_registers_s390x , k_num_gpr_registers_s390x = k_last_gpr_s390x - k_first_gpr_s390x + 1 , k_num_fpr_registers_s390x = k_last_fpr_s390x - k_first_fpr_s390x + 1 , k_num_linux_registers_s390x = k_last_linux_s390x - k_first_linux_s390x + 1 ,
k_num_user_registers_s390x
}
enum {
k_first_gpr_i386 , lldb_eax_i386 = k_first_gpr_i386 , lldb_ebx_i386 , lldb_ecx_i386 ,
lldb_edx_i386 , lldb_edi_i386 , lldb_esi_i386 , lldb_ebp_i386 ,
lldb_esp_i386 , lldb_eip_i386 , lldb_eflags_i386 , lldb_cs_i386 ,
lldb_fs_i386 , lldb_gs_i386 , lldb_ss_i386 , lldb_ds_i386 ,
lldb_es_i386 , k_first_alias_i386 , lldb_ax_i386 = k_first_alias_i386 , lldb_bx_i386 ,
lldb_cx_i386 , lldb_dx_i386 , lldb_di_i386 , lldb_si_i386 ,
lldb_bp_i386 , lldb_sp_i386 , lldb_ah_i386 , lldb_bh_i386 ,
lldb_ch_i386 , lldb_dh_i386 , lldb_al_i386 , lldb_bl_i386 ,
lldb_cl_i386 , lldb_dl_i386 , k_last_alias_i386 = lldb_dl_i386 , k_last_gpr_i386 = k_last_alias_i386 ,
k_first_fpr_i386 , lldb_fctrl_i386 = k_first_fpr_i386 , lldb_fstat_i386 , lldb_ftag_i386 ,
lldb_fop_i386 , lldb_fiseg_i386 , lldb_fioff_i386 , lldb_foseg_i386 ,
lldb_fooff_i386 , lldb_mxcsr_i386 , lldb_mxcsrmask_i386 , lldb_st0_i386 ,
lldb_st1_i386 , lldb_st2_i386 , lldb_st3_i386 , lldb_st4_i386 ,
lldb_st5_i386 , lldb_st6_i386 , lldb_st7_i386 , lldb_mm0_i386 ,
lldb_mm1_i386 , lldb_mm2_i386 , lldb_mm3_i386 , lldb_mm4_i386 ,
lldb_mm5_i386 , lldb_mm6_i386 , lldb_mm7_i386 , lldb_xmm0_i386 ,
lldb_xmm1_i386 , lldb_xmm2_i386 , lldb_xmm3_i386 , lldb_xmm4_i386 ,
lldb_xmm5_i386 , lldb_xmm6_i386 , lldb_xmm7_i386 , k_last_fpr_i386 = lldb_xmm7_i386 ,
k_first_avx_i386 , lldb_ymm0_i386 = k_first_avx_i386 , lldb_ymm1_i386 , lldb_ymm2_i386 ,
lldb_ymm3_i386 , lldb_ymm4_i386 , lldb_ymm5_i386 , lldb_ymm6_i386 ,
lldb_ymm7_i386 , k_last_avx_i386 = lldb_ymm7_i386 , k_first_mpxr_i386 , lldb_bnd0_i386 = k_first_mpxr_i386 ,
lldb_bnd1_i386 , lldb_bnd2_i386 , lldb_bnd3_i386 , k_last_mpxr_i386 = lldb_bnd3_i386 ,
k_first_mpxc_i386 , lldb_bndcfgu_i386 = k_first_mpxc_i386 , lldb_bndstatus_i386 , k_last_mpxc_i386 = lldb_bndstatus_i386 ,
k_first_dbr_i386 , lldb_dr0_i386 = k_first_dbr_i386 , lldb_dr1_i386 , lldb_dr2_i386 ,
lldb_dr3_i386 , lldb_dr4_i386 , lldb_dr5_i386 , lldb_dr6_i386 ,
lldb_dr7_i386 , k_last_dbr_i386 = lldb_dr7_i386 , k_num_registers_i386 , k_num_gpr_registers_i386 = k_last_gpr_i386 - k_first_gpr_i386 + 1 ,
k_num_fpr_registers_i386 = k_last_fpr_i386 - k_first_fpr_i386 + 1 , k_num_avx_registers_i386 = k_last_avx_i386 - k_first_avx_i386 + 1 , k_num_mpx_registers_i386 = k_last_mpxc_i386 - k_first_mpxr_i386 + 1 , k_num_user_registers_i386 ,
k_num_dbr_registers_i386 = k_last_dbr_i386 - k_first_dbr_i386 + 1
}
enum {
k_first_gpr_x86_64 , lldb_rax_x86_64 = k_first_gpr_x86_64 , lldb_rbx_x86_64 , lldb_rcx_x86_64 ,
lldb_rdx_x86_64 , lldb_rdi_x86_64 , lldb_rsi_x86_64 , lldb_rbp_x86_64 ,
lldb_rsp_x86_64 , lldb_r8_x86_64 , lldb_r9_x86_64 , lldb_r10_x86_64 ,
lldb_r11_x86_64 , lldb_r12_x86_64 , lldb_r13_x86_64 , lldb_r14_x86_64 ,
lldb_r15_x86_64 , lldb_rip_x86_64 , lldb_rflags_x86_64 , lldb_cs_x86_64 ,
lldb_fs_x86_64 , lldb_gs_x86_64 , lldb_ss_x86_64 , lldb_ds_x86_64 ,
lldb_es_x86_64 , k_first_alias_x86_64 , lldb_eax_x86_64 = k_first_alias_x86_64 , lldb_ebx_x86_64 ,
lldb_ecx_x86_64 , lldb_edx_x86_64 , lldb_edi_x86_64 , lldb_esi_x86_64 ,
lldb_ebp_x86_64 , lldb_esp_x86_64 , lldb_r8d_x86_64 , lldb_r9d_x86_64 ,
lldb_r10d_x86_64 , lldb_r11d_x86_64 , lldb_r12d_x86_64 , lldb_r13d_x86_64 ,
lldb_r14d_x86_64 , lldb_r15d_x86_64 , lldb_ax_x86_64 , lldb_bx_x86_64 ,
lldb_cx_x86_64 , lldb_dx_x86_64 , lldb_di_x86_64 , lldb_si_x86_64 ,
lldb_bp_x86_64 , lldb_sp_x86_64 , lldb_r8w_x86_64 , lldb_r9w_x86_64 ,
lldb_r10w_x86_64 , lldb_r11w_x86_64 , lldb_r12w_x86_64 , lldb_r13w_x86_64 ,
lldb_r14w_x86_64 , lldb_r15w_x86_64 , lldb_ah_x86_64 , lldb_bh_x86_64 ,
lldb_ch_x86_64 , lldb_dh_x86_64 , lldb_al_x86_64 , lldb_bl_x86_64 ,
lldb_cl_x86_64 , lldb_dl_x86_64 , lldb_dil_x86_64 , lldb_sil_x86_64 ,
lldb_bpl_x86_64 , lldb_spl_x86_64 , lldb_r8l_x86_64 , lldb_r9l_x86_64 ,
lldb_r10l_x86_64 , lldb_r11l_x86_64 , lldb_r12l_x86_64 , lldb_r13l_x86_64 ,
lldb_r14l_x86_64 , lldb_r15l_x86_64 , k_last_alias_x86_64 = lldb_r15l_x86_64 , k_last_gpr_x86_64 = k_last_alias_x86_64 ,
k_first_fpr_x86_64 , lldb_fctrl_x86_64 = k_first_fpr_x86_64 , lldb_fstat_x86_64 , lldb_ftag_x86_64 ,
lldb_fop_x86_64 , lldb_fiseg_x86_64 , lldb_fioff_x86_64 , lldb_fip_x86_64 ,
lldb_foseg_x86_64 , lldb_fooff_x86_64 , lldb_fdp_x86_64 , lldb_mxcsr_x86_64 ,
lldb_mxcsrmask_x86_64 , lldb_st0_x86_64 , lldb_st1_x86_64 , lldb_st2_x86_64 ,
lldb_st3_x86_64 , lldb_st4_x86_64 , lldb_st5_x86_64 , lldb_st6_x86_64 ,
lldb_st7_x86_64 , lldb_mm0_x86_64 , lldb_mm1_x86_64 , lldb_mm2_x86_64 ,
lldb_mm3_x86_64 , lldb_mm4_x86_64 , lldb_mm5_x86_64 , lldb_mm6_x86_64 ,
lldb_mm7_x86_64 , lldb_xmm0_x86_64 , lldb_xmm1_x86_64 , lldb_xmm2_x86_64 ,
lldb_xmm3_x86_64 , lldb_xmm4_x86_64 , lldb_xmm5_x86_64 , lldb_xmm6_x86_64 ,
lldb_xmm7_x86_64 , lldb_xmm8_x86_64 , lldb_xmm9_x86_64 , lldb_xmm10_x86_64 ,
lldb_xmm11_x86_64 , lldb_xmm12_x86_64 , lldb_xmm13_x86_64 , lldb_xmm14_x86_64 ,
lldb_xmm15_x86_64 , k_last_fpr_x86_64 = lldb_xmm15_x86_64 , k_first_avx_x86_64 , lldb_ymm0_x86_64 = k_first_avx_x86_64 ,
lldb_ymm1_x86_64 , lldb_ymm2_x86_64 , lldb_ymm3_x86_64 , lldb_ymm4_x86_64 ,
lldb_ymm5_x86_64 , lldb_ymm6_x86_64 , lldb_ymm7_x86_64 , lldb_ymm8_x86_64 ,
lldb_ymm9_x86_64 , lldb_ymm10_x86_64 , lldb_ymm11_x86_64 , lldb_ymm12_x86_64 ,
lldb_ymm13_x86_64 , lldb_ymm14_x86_64 , lldb_ymm15_x86_64 , k_last_avx_x86_64 = lldb_ymm15_x86_64 ,
k_first_mpxr_x86_64 , lldb_bnd0_x86_64 = k_first_mpxr_x86_64 , lldb_bnd1_x86_64 , lldb_bnd2_x86_64 ,
lldb_bnd3_x86_64 , k_last_mpxr_x86_64 = lldb_bnd3_x86_64 , k_first_mpxc_x86_64 , lldb_bndcfgu_x86_64 = k_first_mpxc_x86_64 ,
lldb_bndstatus_x86_64 , k_last_mpxc_x86_64 = lldb_bndstatus_x86_64 , k_first_dbr_x86_64 , lldb_dr0_x86_64 = k_first_dbr_x86_64 ,
lldb_dr1_x86_64 , lldb_dr2_x86_64 , lldb_dr3_x86_64 , lldb_dr4_x86_64 ,
lldb_dr5_x86_64 , lldb_dr6_x86_64 , lldb_dr7_x86_64 , k_last_dbr_x86_64 = lldb_dr7_x86_64 ,
k_num_registers_x86_64 , k_num_gpr_registers_x86_64 = k_last_gpr_x86_64 - k_first_gpr_x86_64 + 1 , k_num_fpr_registers_x86_64 = k_last_fpr_x86_64 - k_first_fpr_x86_64 + 1 , k_num_avx_registers_x86_64 = k_last_avx_x86_64 - k_first_avx_x86_64 + 1 ,
k_num_mpx_registers_x86_64 = k_last_mpxc_x86_64 - k_first_mpxr_x86_64 + 1 , k_num_user_registers_x86_64 , k_num_dbr_registers_x86_64 = k_last_dbr_x86_64 - k_first_dbr_x86_64 + 1
}
enum {
ehframe_eax_i386 = 0 , ehframe_ecx_i386 , ehframe_edx_i386 , ehframe_ebx_i386 ,
ehframe_esp_i386 , ehframe_ebp_i386 , ehframe_esi_i386 , ehframe_edi_i386 ,
ehframe_eip_i386 , ehframe_eflags_i386 , ehframe_st0_i386 = 12 , ehframe_st1_i386 ,
ehframe_st2_i386 , ehframe_st3_i386 , ehframe_st4_i386 , ehframe_st5_i386 ,
ehframe_st6_i386 , ehframe_st7_i386 , ehframe_xmm0_i386 = 21 , ehframe_xmm1_i386 ,
ehframe_xmm2_i386 , ehframe_xmm3_i386 , ehframe_xmm4_i386 , ehframe_xmm5_i386 ,
ehframe_xmm6_i386 , ehframe_xmm7_i386 , ehframe_mm0_i386 = 29 , ehframe_mm1_i386 ,
ehframe_mm2_i386 , ehframe_mm3_i386 , ehframe_mm4_i386 , ehframe_mm5_i386 ,
ehframe_mm6_i386 , ehframe_mm7_i386
}
enum {
dwarf_eax_i386 = 0 , dwarf_ecx_i386 , dwarf_edx_i386 , dwarf_ebx_i386 ,
dwarf_esp_i386 , dwarf_ebp_i386 , dwarf_esi_i386 , dwarf_edi_i386 ,
dwarf_eip_i386 , dwarf_eflags_i386 , dwarf_st0_i386 = 11 , dwarf_st1_i386 ,
dwarf_st2_i386 , dwarf_st3_i386 , dwarf_st4_i386 , dwarf_st5_i386 ,
dwarf_st6_i386 , dwarf_st7_i386 , dwarf_xmm0_i386 = 21 , dwarf_xmm1_i386 ,
dwarf_xmm2_i386 , dwarf_xmm3_i386 , dwarf_xmm4_i386 , dwarf_xmm5_i386 ,
dwarf_xmm6_i386 , dwarf_xmm7_i386 , dwarf_mm0_i386 = 29 , dwarf_mm1_i386 ,
dwarf_mm2_i386 , dwarf_mm3_i386 , dwarf_mm4_i386 , dwarf_mm5_i386 ,
dwarf_mm6_i386 , dwarf_mm7_i386 , dwarf_fctrl_i386 = 37 , dwarf_fstat_i386 = 38 ,
dwarf_mxcsr_i386 = 39 , dwarf_es_i386 = 40 , dwarf_cs_i386 = 41 , dwarf_ss_i386 = 42 ,
dwarf_ds_i386 = 43 , dwarf_fs_i386 = 44 , dwarf_gs_i386 = 45 , dwarf_bnd0_i386 = 101 ,
dwarf_bnd1_i386 , dwarf_bnd2_i386 , dwarf_bnd3_i386
}
enum {
dwarf_rax_x86_64 = 0 , dwarf_rdx_x86_64 , dwarf_rcx_x86_64 , dwarf_rbx_x86_64 ,
dwarf_rsi_x86_64 , dwarf_rdi_x86_64 , dwarf_rbp_x86_64 , dwarf_rsp_x86_64 ,
dwarf_r8_x86_64 = 8 , dwarf_r9_x86_64 , dwarf_r10_x86_64 , dwarf_r11_x86_64 ,
dwarf_r12_x86_64 , dwarf_r13_x86_64 , dwarf_r14_x86_64 , dwarf_r15_x86_64 ,
dwarf_rip_x86_64 = 16 , dwarf_xmm0_x86_64 = 17 , dwarf_xmm1_x86_64 , dwarf_xmm2_x86_64 ,
dwarf_xmm3_x86_64 , dwarf_xmm4_x86_64 , dwarf_xmm5_x86_64 , dwarf_xmm6_x86_64 ,
dwarf_xmm7_x86_64 , dwarf_xmm8_x86_64 , dwarf_xmm9_x86_64 , dwarf_xmm10_x86_64 ,
dwarf_xmm11_x86_64 , dwarf_xmm12_x86_64 , dwarf_xmm13_x86_64 , dwarf_xmm14_x86_64 ,
dwarf_xmm15_x86_64 , dwarf_st0_x86_64 = 33 , dwarf_st1_x86_64 , dwarf_st2_x86_64 ,
dwarf_st3_x86_64 , dwarf_st4_x86_64 , dwarf_st5_x86_64 , dwarf_st6_x86_64 ,
dwarf_st7_x86_64 , dwarf_mm0_x86_64 = 41 , dwarf_mm1_x86_64 , dwarf_mm2_x86_64 ,
dwarf_mm3_x86_64 , dwarf_mm4_x86_64 , dwarf_mm5_x86_64 , dwarf_mm6_x86_64 ,
dwarf_mm7_x86_64 , dwarf_rflags_x86_64 = 49 , dwarf_es_x86_64 = 50 , dwarf_cs_x86_64 ,
dwarf_ss_x86_64 , dwarf_ds_x86_64 , dwarf_fs_x86_64 , dwarf_gs_x86_64 ,
dwarf_fs_base_x86_64 = 58 , dwarf_gs_base_x86_64 = 59 , dwarf_mxcsr_x86_64 = 64 , dwarf_fctrl_x86_64 ,
dwarf_fstat_x86_64 , dwarf_ymm0h_x86_64 = 67 , dwarf_ymm1h_x86_64 , dwarf_ymm2h_x86_64 ,
dwarf_ymm3h_x86_64 , dwarf_ymm4h_x86_64 , dwarf_ymm5h_x86_64 , dwarf_ymm6h_x86_64 ,
dwarf_ymm7h_x86_64 , dwarf_ymm8h_x86_64 , dwarf_ymm9h_x86_64 , dwarf_ymm10h_x86_64 ,
dwarf_ymm11h_x86_64 , dwarf_ymm12h_x86_64 , dwarf_ymm13h_x86_64 , dwarf_ymm14h_x86_64 ,
dwarf_ymm15h_x86_64 , dwarf_bnd0_x86_64 = 126 , dwarf_bnd1_x86_64 , dwarf_bnd2_x86_64 ,
dwarf_bnd3_x86_64
}
enum class WindowsLog : Log::MaskType {
Breakpoints = Log::ChannelFlag<0> , Event = Log::ChannelFlag<1> , Exception = Log::ChannelFlag<2> , Memory = Log::ChannelFlag<3> ,
Process = Log::ChannelFlag<4> , Registers = Log::ChannelFlag<5> , Step = Log::ChannelFlag<6> , Thread = Log::ChannelFlag<7>
}
enum class DWARFLog : Log::MaskType {
DebugInfo = Log::ChannelFlag<0> , DebugLine = Log::ChannelFlag<1> , DebugMap = Log::ChannelFlag<2> , Lookups = Log::ChannelFlag<3> ,
TypeCompletion = Log::ChannelFlag<4> , SplitDwarf = Log::ChannelFlag<5>
}
enum {
UNWIND_X86_REG_NONE = 0 , UNWIND_X86_REG_EBX = 1 , UNWIND_X86_REG_ECX = 2 , UNWIND_X86_REG_EDX = 3 ,
UNWIND_X86_REG_EDI = 4 , UNWIND_X86_REG_ESI = 5 , UNWIND_X86_REG_EBP = 6
}
enum {
UNWIND_X86_64_REG_NONE = 0 , UNWIND_X86_64_REG_RBX = 1 , UNWIND_X86_64_REG_R12 = 2 , UNWIND_X86_64_REG_R13 = 3 ,
UNWIND_X86_64_REG_R14 = 4 , UNWIND_X86_64_REG_R15 = 5 , UNWIND_X86_64_REG_RBP = 6
}
enum WasmVirtualRegisterKinds { eWasmTagNotAWasmLocation = 0 , eWasmTagLocal = 1 , eWasmTagGlobal = 2 , eWasmTagOperandStack = 3 }
Functions
bool operator< (const Address &lhs, const Address &rhs)
bool operator> (const Address &lhs, const Address &rhs)
bool operator== (const Address &lhs, const Address &rhs)
bool operator!= (const Address &lhs, const Address &rhs)
bool operator== (const Declaration &lhs, const Declaration &rhs)
lldb::offset_t DumpDataExtractor (const DataExtractor &DE, Stream *s, lldb::offset_t offset, lldb::Format item_format, size_t item_byte_size, size_t item_count, size_t num_per_line, uint64_t base_addr, uint32_t item_bit_size, uint32_t item_bit_offset, ExecutionContextScope *exe_scope=nullptr, bool show_memory_tags=false)
Dumps item_count objects into the stream s.
void DumpHexBytes (Stream *s, const void *src, size_t src_len, uint32_t bytes_per_line, lldb::addr_t base_addr)
void DumpRegisterInfo (Stream &strm, RegisterContext &ctx, const RegisterInfo &info, uint32_t terminal_width)
void DoDumpRegisterInfo (Stream &strm, const char *name, const char *alt_name, uint32_t byte_size, const std::vector< const char * > &invalidates, const std::vector< const char * > &read_from, const std::vector< std::pair< const char *, uint32_t > > &in_sets, const RegisterFlags *flags_type, uint32_t terminal_width)
void DumpRegisterValue (const RegisterValue &reg_val, Stream &s, const RegisterInfo &reg_info, bool prefix_with_name, bool prefix_with_alt_name, lldb::Format format, uint32_t reg_name_right_align_at=0, ExecutionContextScope *exe_scope=nullptr, bool print_flags=false, lldb::TargetSP target_sp=nullptr)
Stream & operator<< (Stream &s, const Mangled &obj)
Stream & operator<< (Stream &s, const SourceLocationSpec &loc)
Dump a SourceLocationSpec object to a stream.
bool operator== (const SourceManager::File &lhs, const SourceManager::File &rhs)
std::string toString (FormatterBytecode::OpCodes op)
std::string toString (FormatterBytecode::Selectors sel)
std::string toString (FormatterBytecode::Signatures sig)
void LoadTypeSummariesForModule (lldb::ModuleSP module_sp)
Load type summaries embedded in the binary.
void LoadFormattersForModule (lldb::ModuleSP module_sp)
Load data formatters embedded in the binary.
llvm::ErrorOr< std::unique_ptr< llvm::MemoryBuffer > > getProcFile (::pid_t pid, ::pid_t tid, const llvm::Twine &file)
StructuredData::ObjectSP Serialize (llvm::ArrayRef< DiagnosticDetail > details)
void RenderDiagnosticDetails (Stream &stream, std::optional< uint16_t > offset_in_command, bool show_inline, llvm::ArrayRef< DiagnosticDetail > details, bool force_ascii=false)
Renders an array of DiagnosticDetail instances.
LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE ()
template<>
Log::Channel & LogChannelFor< SystemLog > ()
bool operator== (WaitStatus a, WaitStatus b)
bool operator!= (WaitStatus a, WaitStatus b)
std::optional< lldb::pid_t > getPIDForTID (lldb::pid_t tid)
llvm::ErrorOr< std::unique_ptr< llvm::MemoryBuffer > > getProcFile (::pid_t pid, const llvm::Twine &file)
llvm::ErrorOr< std::unique_ptr< llvm::MemoryBuffer > > getProcFile (const llvm::Twine &file)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const Socket::HostAndPort &HP)
template<typename ValueType>
int AddNamesMatchingPartialString (const std::map< std::string, ValueType, std::less<> > &in_map, llvm::StringRef cmd_str, StringList &matches, StringList *descriptions=nullptr)
template<typename ValueType>
size_t FindLongestCommandWord (std::map< std::string, ValueType, std::less<> > &dict)
llvm::StringRef RegisterNameHelpTextCallback ()
llvm::StringRef BreakpointIDHelpTextCallback ()
llvm::StringRef BreakpointIDRangeHelpTextCallback ()
llvm::StringRef BreakpointNameHelpTextCallback ()
llvm::StringRef GDBFormatHelpTextCallback ()
llvm::StringRef FormatHelpTextCallback ()
llvm::StringRef LanguageTypeHelpTextCallback ()
llvm::StringRef SummaryStringHelpTextCallback ()
llvm::StringRef ExprPathHelpTextCallback ()
llvm::StringRef arch_helper ()
llvm::Error CreateOptionParsingError (llvm::StringRef option_arg, const char short_option, llvm::StringRef long_option={}, llvm::StringRef additional_context={})
Creates an error that represents the failure to parse an command line option argument.
std::string GetStatDescription (lldb_private::StatisticKind K)
bool operator== (const CompilerDecl &lhs, const CompilerDecl &rhs)
bool operator!= (const CompilerDecl &lhs, const CompilerDecl &rhs)
bool operator== (const CompilerDeclContext &lhs, const CompilerDeclContext &rhs)
bool operator!= (const CompilerDeclContext &lhs, const CompilerDeclContext &rhs)
bool operator== (const CompilerType &lhs, const CompilerType &rhs)
bool operator!= (const CompilerType &lhs, const CompilerType &rhs)
bool operator< (const LineEntry &lhs, const LineEntry &rhs)
Less than operator.
bool operator== (const SymbolContext &lhs, const SymbolContext &rhs)
bool operator!= (const SymbolContext &lhs, const SymbolContext &rhs)
bool operator== (const SymbolContextList &lhs, const SymbolContextList &rhs)
bool operator!= (const SymbolContextList &lhs, const SymbolContextList &rhs)
llvm::raw_ostream & operator<< (llvm::raw_ostream &os, const CompilerContext &rhs)
FLAGS_ENUM (TypeQueryOptions)
AppleArm64ExceptionClass getAppleArm64ExceptionClass (uint32_t esr)
Get the Apple ARM64 exception class encoded within esr.
const char * toString (AppleArm64ExceptionClass EC)
void RegisterAssertFrameRecognizer (Process *process)
Registers the assert stack frame recognizer.
void addSupplementaryRegister (std::vector< DynamicRegisterInfo::Register > &regs, DynamicRegisterInfo::Register new_reg_info)
llvm::Expected< StoppedExecutionContext > GetStoppedExecutionContext (const ExecutionContextRef *exe_ctx_ref_ptr)
llvm::Expected< StoppedExecutionContext > GetStoppedExecutionContext (const lldb::ExecutionContextRefSP &exe_ctx_ref_ptr)
bool operator< (const MemoryRegionInfo &lhs, const MemoryRegionInfo &rhs)
bool operator< (const MemoryRegionInfo &lhs, lldb::addr_t rhs)
bool operator< (lldb::addr_t lhs, const MemoryRegionInfo &rhs)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const MemoryRegionInfo &Info)
bool operator== (const ProcessModID &lhs, const ProcessModID &rhs)
bool operator!= (const ProcessModID &lhs, const ProcessModID &rhs)
bool operator== (const StackID &lhs, const StackID &rhs)
bool operator!= (const StackID &lhs, const StackID &rhs)
bool operator< (const StackID &lhs, const StackID &rhs)
OptionEnumValues GetDynamicValueTypes ()
bool operator< (const ArchSpec &lhs, const ArchSpec &rhs)
operator.
bool operator== (const ArchSpec &lhs, const ArchSpec &rhs)
bool operator!= (const ArchSpec &lhs, const ArchSpec &rhs)
bool ParseMachCPUDashSubtypeTriple (llvm::StringRef triple_str, ArchSpec &arch)
Stream & operator<< (Stream &s, ConstString str)
Stream the string value str to the stream s.
std::string toString (lldb::ExpressionResults e)
Produce a human-readable rendition of an ExpressionResults value.
Stream & operator<< (Stream &s, const FileSpec &f)
Dump a FileSpec object to a stream.
void _lldb_assert (bool expression, const char *expr_text, const char *func, const char *file, unsigned int line, std::once_flag &once_flag)
Don't use _lldb_assert directly.
void SetLLDBAssertCallback (LLDBAssertCallback callback)
Replace the LLDB assert callback.
void InitializeLldbChannel ()
template<>
Log::Channel & LogChannelFor< LLDBLog > ()
template<typename Cat>
Log::Channel & LogChannelFor ()=delete
template<typename Cat>
Log * GetLog (Cat mask)
Retrieve the Log object for the channel associated with the given log enum.
bool NameMatches (llvm::StringRef name, NameMatch match_type, llvm::StringRef match)
llvm::APFloat::cmpResult compare (Scalar lhs, Scalar rhs)
const Scalar operator+ (const Scalar &lhs, const Scalar &rhs)
const Scalar operator- (Scalar lhs, Scalar rhs)
const Scalar operator/ (Scalar lhs, Scalar rhs)
const Scalar operator* (Scalar lhs, Scalar rhs)
const Scalar operator& (Scalar lhs, Scalar rhs)
const Scalar operator| (Scalar lhs, Scalar rhs)
const Scalar operator% (Scalar lhs, Scalar rhs)
const Scalar operator^ (Scalar lhs, Scalar rhs)
const Scalar operator<< (const Scalar &lhs, const Scalar &rhs)
const Scalar operator>> (const Scalar &lhs, const Scalar &rhs)
bool operator== (const Scalar &lhs, const Scalar &rhs)
bool operator!= (const Scalar &lhs, const Scalar &rhs)
bool operator< (const Scalar &lhs, const Scalar &rhs)
bool operator<= (const Scalar &lhs, const Scalar &rhs)
bool operator> (const Scalar &lhs, const Scalar &rhs)
bool operator>= (const Scalar &lhs, const Scalar &rhs)
llvm::raw_ostream & operator<< (llvm::raw_ostream &os, const Scalar &scalar)
const char * StateAsCString (lldb::StateType state)
Converts a StateType to a C string.
bool StateIsRunningState (lldb::StateType state)
Check if a state represents a state where the process or thread is running.
bool StateIsStoppedState (lldb::StateType state, bool must_exist)
Check if a state represents a state where the process or thread is stopped.
const char * GetPermissionsAsCString (uint32_t permissions)
void DumpAddress (llvm::raw_ostream &s, uint64_t addr, uint32_t addr_size, const char *prefix=nullptr, const char *suffix=nullptr)
Output an address value to this stream.
void DumpAddressRange (llvm::raw_ostream &s, uint64_t lo_addr, uint64_t hi_addr, uint32_t addr_size, const char *prefix=nullptr, const char *suffix=nullptr)
Output an address range to this stream.
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const URI &U)
bool operator== (const UserID &lhs, const UserID &rhs)
bool operator!= (const UserID &lhs, const UserID &rhs)
Stream & operator<< (Stream &strm, const UserID &uid)
Stream the UserID object to a Stream.
bool VASprintf (llvm::SmallVectorImpl< char > &buf, const char *fmt, va_list args)
bool operator== (const VMRange &lhs, const VMRange &rhs)
bool operator!= (const VMRange &lhs, const VMRange &rhs)
bool operator< (const VMRange &lhs, const VMRange &rhs)
bool operator<= (const VMRange &lhs, const VMRange &rhs)
bool operator> (const VMRange &lhs, const VMRange &rhs)
bool operator>= (const VMRange &lhs, const VMRange &rhs)
const char * GetVersion ()
Retrieves a string representing the complete LLDB version, which includes the lldb version number, as well as embedded compiler versions and the vendor tag.
template<typename T>
std::unique_ptr< T > clone (const std::unique_ptr< T > &src)
template<typename T>
std::shared_ptr< T > clone (const std::shared_ptr< T > &src)
template<>
bool FormatCache::Entry::IsCached< lldb::TypeFormatImplSP > ()
template<>
bool FormatCache::Entry::IsCached< lldb::TypeSummaryImplSP > ()
template<>
bool FormatCache::Entry::IsCached< lldb::SyntheticChildrenSP > ()
std::string toString (const FormatterBytecode::DataStack &data)
static bool skipPadding (llvm::DataExtractor &section, llvm::DataExtractor::Cursor &cursor)
static void ForEachFormatterInModule (Module &module, SectionType section_type, std::function< void(llvm::DataExtractor, llvm::StringRef)> fn)
static BytecodeSyntheticChildren::SyntheticBytecodeImplementation CreateSyntheticImpl (llvm::MutableArrayRef< std::unique_ptr< llvm::MemoryBuffer > > methods)
template<>
auto & LanguageCategory::GetHardcodedFinder< lldb::TypeFormatImplSP > ()
template<>
auto & LanguageCategory::GetHardcodedFinder< lldb::TypeSummaryImplSP > ()
template<>
auto & LanguageCategory::GetHardcodedFinder< lldb::SyntheticChildrenSP > ()
static llvm::raw_ostream & PrintSeverity (Stream &stream, lldb::Severity severity)
template<class D2, template< class D > class TD, class D1>
TD< D2 > DynCast (TD< D1 > source)
bool ComputeClangResourceDirectory (FileSpec &lldb_shlib_spec, FileSpec &file_spec, bool verify)
FileSpec GetClangResourceDir ()
template<typename... Ts>
static std::optional< std::tuple< Ts... > > zipOpt (std::optional< Ts > &&...ts)
Returns all values wrapped in Optional, or std::nullopt if any of the values is std::nullopt.
constexpr int32_t SignExt (uint32_t imm)
template<typename T>
constexpr std::enable_if_t< sizeof(T)<=4, uint64_t > SextW (T value)
template<typename T>
constexpr uint64_t ZextD (T value)
constexpr uint32_t DecodeJImm (uint32_t inst)
constexpr uint32_t DecodeIImm (uint32_t inst)
constexpr uint32_t DecodeBImm (uint32_t inst)
constexpr uint32_t DecodeSImm (uint32_t inst)
constexpr uint32_t DecodeUImm (uint32_t inst)
static uint32_t GPREncodingToLLDB (uint32_t reg_encode)
static uint32_t FPREncodingToLLDB (uint32_t reg_encode)
static std::optional< RegisterInfo > GPREncodingToRegisterInfo (EmulateInstructionRISCV &emulator, uint32_t reg_encode)
static bool CompareB (uint64_t rs1, uint64_t rs2, uint32_t funct3)
template<typename I>
static std::enable_if_t< is_load< I >||is_store< I >, std::optional< uint64_t > > LoadStoreAddr (EmulateInstructionRISCV &emulator, I inst)
template<typename I, typename T, typename E>
static std::enable_if_t< is_load< I >, bool > Load (EmulateInstructionRISCV &emulator, I inst, uint64_t(*extend)(E))
template<typename I, typename T>
static std::enable_if_t< is_store< I >, bool > Store (EmulateInstructionRISCV &emulator, I inst)
template<typename I>
static std::enable_if_t< is_amo_add< I >||is_amo_bit_op< I >||is_amo_swap< I >||is_amo_cmp< I >, std::optional< uint64_t > > AtomicAddr (EmulateInstructionRISCV &emulator, I inst, unsigned int align)
template<typename I, typename T>
static std::enable_if_t< is_amo_swap< I >, bool > AtomicSwap (EmulateInstructionRISCV &emulator, I inst, int align, uint64_t(*extend)(T))
template<typename I, typename T>
static std::enable_if_t< is_amo_add< I >, bool > AtomicADD (EmulateInstructionRISCV &emulator, I inst, int align, uint64_t(*extend)(T))
template<typename I, typename T>
static std::enable_if_t< is_amo_bit_op< I >, bool > AtomicBitOperate (EmulateInstructionRISCV &emulator, I inst, int align, uint64_t(*extend)(T), T(*operate)(T, T))
template<typename I, typename T>
static std::enable_if_t< is_amo_cmp< I >, bool > AtomicCmp (EmulateInstructionRISCV &emulator, I inst, int align, uint64_t(*extend)(T), T(*cmp)(T, T))
bool AtomicSequence (EmulateInstructionRISCV &emulator)
template<typename T>
static RISCVInst DecodeUType (uint32_t inst)
template<typename T>
static RISCVInst DecodeJType (uint32_t inst)
template<typename T>
static RISCVInst DecodeIType (uint32_t inst)
template<typename T>
static RISCVInst DecodeBType (uint32_t inst)
template<typename T>
static RISCVInst DecodeSType (uint32_t inst)
template<typename T>
static RISCVInst DecodeRType (uint32_t inst)
template<typename T>
static RISCVInst DecodeRShamtType (uint32_t inst)
template<typename T>
static RISCVInst DecodeRRS1Type (uint32_t inst)
template<typename T>
static RISCVInst DecodeR4Type (uint32_t inst)
constexpr RxC DecodeCR_RD (uint32_t inst)
constexpr RxC DecodeCI_RD (uint32_t inst)
constexpr RxC DecodeCR_RS1 (uint32_t inst)
constexpr RxC DecodeCI_RS1 (uint32_t inst)
constexpr RxC DecodeCR_RS2 (uint32_t inst)
constexpr RxC DecodeCIW_RD (uint32_t inst)
constexpr RxC DecodeCL_RD (uint32_t inst)
constexpr RxC DecodeCA_RD (uint32_t inst)
constexpr RxC DecodeCB_RD (uint32_t inst)
constexpr RxC DecodeCL_RS1 (uint32_t inst)
constexpr RxC DecodeCS_RS1 (uint32_t inst)
constexpr RxC DecodeCA_RS1 (uint32_t inst)
constexpr RxC DecodeCB_RS1 (uint32_t inst)
constexpr RxC DecodeCSS_RS2 (uint32_t inst)
constexpr RxC DecodeCS_RS2 (uint32_t inst)
constexpr RxC DecodeCA_RS2 (uint32_t inst)
RISCVInst DecodeC_LWSP (uint32_t inst)
RISCVInst DecodeC_LDSP (uint32_t inst)
RISCVInst DecodeC_SWSP (uint32_t inst)
RISCVInst DecodeC_SDSP (uint32_t inst)
RISCVInst DecodeC_LW (uint32_t inst)
RISCVInst DecodeC_LD (uint32_t inst)
RISCVInst DecodeC_SW (uint32_t inst)
RISCVInst DecodeC_SD (uint32_t inst)
RISCVInst DecodeC_J (uint32_t inst)
RISCVInst DecodeC_JR (uint32_t inst)
RISCVInst DecodeC_JALR (uint32_t inst)
constexpr uint16_t BOffset (uint32_t inst)
RISCVInst DecodeC_BNEZ (uint32_t inst)
RISCVInst DecodeC_BEQZ (uint32_t inst)
RISCVInst DecodeC_LI (uint32_t inst)
RISCVInst DecodeC_LUI_ADDI16SP (uint32_t inst)
RISCVInst DecodeC_ADDI (uint32_t inst)
RISCVInst DecodeC_ADDIW (uint32_t inst)
RISCVInst DecodeC_ADDI4SPN (uint32_t inst)
RISCVInst DecodeC_SLLI (uint32_t inst)
RISCVInst DecodeC_SRLI (uint32_t inst)
RISCVInst DecodeC_SRAI (uint32_t inst)
RISCVInst DecodeC_ANDI (uint32_t inst)
RISCVInst DecodeC_MV (uint32_t inst)
RISCVInst DecodeC_ADD (uint32_t inst)
RISCVInst DecodeC_AND (uint32_t inst)
RISCVInst DecodeC_OR (uint32_t inst)
RISCVInst DecodeC_XOR (uint32_t inst)
RISCVInst DecodeC_SUB (uint32_t inst)
RISCVInst DecodeC_SUBW (uint32_t inst)
RISCVInst DecodeC_ADDW (uint32_t inst)
RISCVInst DecodeC_FLW (uint32_t inst)
RISCVInst DecodeC_FSW (uint32_t inst)
RISCVInst DecodeC_FLWSP (uint32_t inst)
RISCVInst DecodeC_FSWSP (uint32_t inst)
RISCVInst DecodeC_FLDSP (uint32_t inst)
RISCVInst DecodeC_FSDSP (uint32_t inst)
RISCVInst DecodeC_FLD (uint32_t inst)
RISCVInst DecodeC_FSD (uint32_t inst)
U_TYPE_INST (LUI)
U_TYPE_INST (AUIPC)
J_TYPE_INST (JAL)
I_TYPE_INST (JALR)
I_TYPE_INST (LB)
I_TYPE_INST (LH)
I_TYPE_INST (LW)
I_TYPE_INST (LBU)
I_TYPE_INST (LHU)
S_TYPE_INST (SB)
S_TYPE_INST (SH)
S_TYPE_INST (SW)
I_TYPE_INST (ADDI)
I_TYPE_INST (SLTI)
I_TYPE_INST (SLTIU)
I_TYPE_INST (XORI)
I_TYPE_INST (ORI)
I_TYPE_INST (ANDI)
R_TYPE_INST (ADD)
R_TYPE_INST (SUB)
R_TYPE_INST (SLL)
R_TYPE_INST (SLT)
R_TYPE_INST (SLTU)
R_TYPE_INST (XOR)
R_TYPE_INST (SRL)
R_TYPE_INST (SRA)
R_TYPE_INST (OR)
R_TYPE_INST (AND)
I_TYPE_INST (LWU)
I_TYPE_INST (LD)
S_TYPE_INST (SD)
R_SHAMT_TYPE_INST (SLLI)
R_SHAMT_TYPE_INST (SRLI)
R_SHAMT_TYPE_INST (SRAI)
I_TYPE_INST (ADDIW)
R_SHAMT_TYPE_INST (SLLIW)
R_SHAMT_TYPE_INST (SRLIW)
R_SHAMT_TYPE_INST (SRAIW)
R_TYPE_INST (ADDW)
R_TYPE_INST (SUBW)
R_TYPE_INST (SLLW)
R_TYPE_INST (SRLW)
R_TYPE_INST (SRAW)
R_TYPE_INST (MUL)
R_TYPE_INST (MULH)
R_TYPE_INST (MULHSU)
R_TYPE_INST (MULHU)
R_TYPE_INST (DIV)
R_TYPE_INST (DIVU)
R_TYPE_INST (REM)
R_TYPE_INST (REMU)
R_TYPE_INST (MULW)
R_TYPE_INST (DIVW)
R_TYPE_INST (DIVUW)
R_TYPE_INST (REMW)
R_TYPE_INST (REMUW)
R_RS1_TYPE_INST (LR_W)
R_TYPE_INST (SC_W)
R_TYPE_INST (AMOSWAP_W)
R_TYPE_INST (AMOADD_W)
R_TYPE_INST (AMOXOR_W)
R_TYPE_INST (AMOAND_W)
R_TYPE_INST (AMOOR_W)
R_TYPE_INST (AMOMIN_W)
R_TYPE_INST (AMOMAX_W)
R_TYPE_INST (AMOMINU_W)
R_TYPE_INST (AMOMAXU_W)
R_RS1_TYPE_INST (LR_D)
R_TYPE_INST (SC_D)
R_TYPE_INST (AMOSWAP_D)
R_TYPE_INST (AMOADD_D)
R_TYPE_INST (AMOXOR_D)
R_TYPE_INST (AMOAND_D)
R_TYPE_INST (AMOOR_D)
R_TYPE_INST (AMOMIN_D)
R_TYPE_INST (AMOMAX_D)
R_TYPE_INST (AMOMINU_D)
R_TYPE_INST (AMOMAXU_D)
I_TYPE_INST (FLW)
S_TYPE_INST (FSW)
R4_TYPE_INST (FMADD_S)
R4_TYPE_INST (FMSUB_S)
R4_TYPE_INST (FNMADD_S)
R4_TYPE_INST (FNMSUB_S)
R_TYPE_INST (FADD_S)
R_TYPE_INST (FSUB_S)
R_TYPE_INST (FMUL_S)
R_TYPE_INST (FDIV_S)
I_TYPE_INST (FSQRT_S)
R_TYPE_INST (FSGNJ_S)
R_TYPE_INST (FSGNJN_S)
R_TYPE_INST (FSGNJX_S)
R_TYPE_INST (FMIN_S)
R_TYPE_INST (FMAX_S)
I_TYPE_INST (FCVT_W_S)
I_TYPE_INST (FCVT_WU_S)
I_TYPE_INST (FMV_X_W)
R_TYPE_INST (FEQ_S)
R_TYPE_INST (FLT_S)
R_TYPE_INST (FLE_S)
I_TYPE_INST (FCLASS_S)
I_TYPE_INST (FCVT_S_W)
I_TYPE_INST (FCVT_S_WU)
I_TYPE_INST (FMV_W_X)
I_TYPE_INST (FCVT_L_S)
I_TYPE_INST (FCVT_LU_S)
I_TYPE_INST (FCVT_S_L)
I_TYPE_INST (FCVT_S_LU)
I_TYPE_INST (FLD)
S_TYPE_INST (FSD)
R4_TYPE_INST (FMADD_D)
R4_TYPE_INST (FMSUB_D)
R4_TYPE_INST (FNMSUB_D)
R4_TYPE_INST (FNMADD_D)
R_TYPE_INST (FADD_D)
R_TYPE_INST (FSUB_D)
R_TYPE_INST (FMUL_D)
R_TYPE_INST (FDIV_D)
I_TYPE_INST (FSQRT_D)
R_TYPE_INST (FSGNJ_D)
R_TYPE_INST (FSGNJN_D)
R_TYPE_INST (FSGNJX_D)
R_TYPE_INST (FMIN_D)
R_TYPE_INST (FMAX_D)
I_TYPE_INST (FCVT_S_D)
I_TYPE_INST (FCVT_D_S)
R_TYPE_INST (FEQ_D)
R_TYPE_INST (FLT_D)
R_TYPE_INST (FLE_D)
I_TYPE_INST (FCLASS_D)
I_TYPE_INST (FCVT_W_D)
I_TYPE_INST (FCVT_WU_D)
I_TYPE_INST (FCVT_D_W)
I_TYPE_INST (FCVT_D_WU)
I_TYPE_INST (FCVT_L_D)
I_TYPE_INST (FCVT_LU_D)
I_TYPE_INST (FMV_X_D)
I_TYPE_INST (FCVT_D_L)
I_TYPE_INST (FCVT_D_LU)
I_TYPE_INST (FMV_D_X)
INVALID_INST (INVALID)
Invalid and reserved instructions, the inst fields are used for debugging.
INVALID_INST (RESERVED)
INVALID_INST (EBREAK)
INVALID_INST (HINT)
INVALID_INST (NOP)
constexpr uint32_t DecodeRD (uint32_t inst)
constexpr uint32_t DecodeRS1 (uint32_t inst)
constexpr uint32_t DecodeRS2 (uint32_t inst)
constexpr uint32_t DecodeRS3 (uint32_t inst)
constexpr uint32_t DecodeFunct3 (uint32_t inst)
constexpr uint32_t DecodeFunct2 (uint32_t inst)
constexpr uint32_t DecodeFunct7 (uint32_t inst)
constexpr int32_t DecodeRM (uint32_t inst)
constexpr uint64_t NanBoxing (uint64_t val)
RISC-V spec: The upper bits of a valid NaN-boxed value must be all 1s.
constexpr uint32_t NanUnBoxing (uint64_t val)
std::tuple< lldb::ModuleSP, HistoryPCType > GetPreferredAsanModule (const Target &target)
On Darwin, if LLDB loaded libclang_rt, it's coming from a locally built compiler-rt, and we should prefer it in favour of the system sanitizers when running InstrumentationRuntime utility expressions that use symbols from the sanitizer libraries.
void RegisterVerboseTrapFrameRecognizer (Process &process)
bool fromJSON (const json::Value &value, ObjectFileJSON::Header &header, json::Path path)
bool fromJSON (const json::Value &value, ObjectFileJSON::Body &body, json::Path path)
bool fromJSON (const llvm::json::Value &value, ObjectFileJSON::Header &header, llvm::json::Path path)
bool fromJSON (const llvm::json::Value &value, ObjectFileJSON::Body &body, llvm::json::Path path)
bool SaveMiniDump (const lldb::ProcessSP &process_sp, SaveCoreOptions &core_options, lldb_private::Status &error)
DataExtractor getRegset (llvm::ArrayRef< CoreNote > Notes, const llvm::Triple &Triple, llvm::ArrayRef< RegsetDesc > RegsetDescs)
template<>
Log::Channel & LogChannelFor< process_gdb_remote::GDBRLog > ()
template<>
Log::Channel & LogChannelFor< KDPLog > ()
template lldb::addr_t NativeProcessELF::GetELFImageInfoAddress< llvm::ELF::Elf32_Ehdr, llvm::ELF::Elf32_Phdr, llvm::ELF::Elf32_Dyn > ()
template lldb::addr_t NativeProcessELF::GetELFImageInfoAddress< llvm::ELF::Elf64_Ehdr, llvm::ELF::Elf64_Phdr, llvm::ELF::Elf64_Dyn > ()
template<>
Log::Channel & LogChannelFor< POSIXLog > ()
static const char * ARMCondCodeToString (uint32_t CC)
static bool ARMConditionPassed (const uint32_t condition, const uint32_t cpsr)
static uint32_t Align (uint32_t val, uint32_t alignment)
static uint32_t DecodeImmShift (const uint32_t type, const uint32_t imm5, ARM_ShifterType &shift_t)
static uint32_t DecodeImmShiftThumb (const uint32_t opcode, ARM_ShifterType &shift_t)
static uint32_t DecodeImmShiftARM (const uint32_t opcode, ARM_ShifterType &shift_t)
static uint32_t DecodeImmShift (const ARM_ShifterType shift_t, const uint32_t imm5)
static ARM_ShifterType DecodeRegShift (const uint32_t type)
static uint32_t LSL_C (const uint32_t value, const uint32_t amount, uint32_t &carry_out, bool *success)
static uint32_t LSL (const uint32_t value, const uint32_t amount, bool *success)
static uint32_t LSR_C (const uint32_t value, const uint32_t amount, uint32_t &carry_out, bool *success)
static uint32_t LSR (const uint32_t value, const uint32_t amount, bool *success)
static uint32_t ASR_C (const uint32_t value, const uint32_t amount, uint32_t &carry_out, bool *success)
static uint32_t ASR (const uint32_t value, const uint32_t amount, bool *success)
static uint32_t ROR_C (const uint32_t value, const uint32_t amount, uint32_t &carry_out, bool *success)
static uint32_t ROR (const uint32_t value, const uint32_t amount, bool *success)
static uint32_t RRX_C (const uint32_t value, const uint32_t carry_in, uint32_t &carry_out, bool *success)
static uint32_t RRX (const uint32_t value, const uint32_t carry_in, bool *success)
static uint32_t Shift_C (const uint32_t value, ARM_ShifterType type, const uint32_t amount, const uint32_t carry_in, uint32_t &carry_out, bool *success)
static uint32_t Shift (const uint32_t value, ARM_ShifterType type, const uint32_t amount, const uint32_t carry_in, bool *success)
static uint32_t bits (const uint32_t val, const uint32_t msbit, const uint32_t lsbit)
static uint32_t bit (const uint32_t val, const uint32_t msbit)
static uint32_t ror (uint32_t val, uint32_t N, uint32_t shift)
static uint32_t ARMExpandImm_C (uint32_t opcode, uint32_t carry_in, uint32_t &carry_out)
static uint32_t ARMExpandImm (uint32_t opcode)
static uint32_t ThumbExpandImm_C (uint32_t opcode, uint32_t carry_in, uint32_t &carry_out)
static uint32_t ThumbExpandImm (uint32_t opcode)
static uint32_t ThumbImm12 (uint32_t opcode)
static uint32_t ThumbImm7Scaled (uint32_t opcode)
static uint32_t ThumbImm8Scaled (uint32_t opcode)
static bool BadReg (uint32_t n)
bool InferiorCallMmap (Process *proc, lldb::addr_t &allocated_addr, lldb::addr_t addr, lldb::addr_t length, unsigned prot, unsigned flags, lldb::addr_t fd, lldb::addr_t offset)
bool InferiorCallMunmap (Process *proc, lldb::addr_t addr, lldb::addr_t length)
static uint64_t Bits64 (const uint64_t bits, const uint32_t msbit, const uint32_t lsbit)
static uint32_t Bits32 (const uint32_t bits, const uint32_t msbit, const uint32_t lsbit)
static uint32_t Bit32 (const uint32_t bits, const uint32_t bit)
static uint64_t Bit64 (const uint64_t bits, const uint32_t bit)
static void SetBits32 (uint32_t &bits, const uint32_t msbit, const uint32_t lsbit, const uint32_t val)
static void SetBit32 (uint32_t &bits, const uint32_t bit, const uint32_t val)
static uint32_t Rotr32 (uint32_t bits, uint32_t amt)
static uint32_t Rotl32 (uint32_t bits, uint32_t amt)
static uint64_t MaskUpToBit (const uint64_t bit)
static uint32_t BitCount (uint64_t x)
static bool BitIsSet (const uint64_t value, const uint64_t bit)
static bool BitIsClear (const uint64_t value, const uint64_t bit)
static uint64_t UnsignedBits (const uint64_t value, const uint64_t msbit, const uint64_t lsbit)
static int64_t SignedBits (const uint64_t value, const uint64_t msbit, const uint64_t lsbit)
void ParseLinuxMapRegions (llvm::StringRef linux_map, LinuxMapCallback const &callback)
void ParseLinuxSMapRegions (llvm::StringRef linux_smap, LinuxMapCallback const &callback)
YMMReg XStateToYMM (const void *xmm_bytes, const void *ymmh_bytes)
void YMMToXState (const YMMReg &input, void *xmm_bytes, void *ymmh_bytes)
uint16_t AbridgedToFullTagWord (uint8_t abridged_tw, uint16_t sw, llvm::ArrayRef< MMSReg > st_regs)
uint8_t FullToAbridgedTagWord (uint16_t tw)
RegInfo & GetRegInfoShared (llvm::Triple::ArchType arch_type, bool with_base)
static bool ShouldUseLLDBServer ()
static void DumpAdditionalExceptionInformation (llvm::raw_ostream &stream, const ExceptionRecordSP &exception)
template<>
Log::Channel & LogChannelFor< WindowsLog > ()
int luaopen_lldb (lua_State *L)
template<>
StructuredData::ArraySP ScriptedPythonInterface::ExtractValueFromPythonObject< StructuredData::ArraySP > (python::PythonObject &p, Status &error)
template<>
StructuredData::DictionarySP ScriptedPythonInterface::ExtractValueFromPythonObject< StructuredData::DictionarySP > (python::PythonObject &p, Status &error)
template<>
lldb::StreamSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StreamSP > (python::PythonObject &p, Status &error)
template<>
lldb::ThreadSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ThreadSP > (python::PythonObject &p, Status &error)
template<>
lldb::StackFrameSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameSP > (python::PythonObject &p, Status &error)
template<>
lldb::BreakpointSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointSP > (python::PythonObject &p, Status &error)
template<>
lldb::BreakpointLocationSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointLocationSP > (python::PythonObject &p, Status &error)
template<>
lldb::ProcessAttachInfoSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessAttachInfoSP > (python::PythonObject &p, Status &error)
template<>
lldb::ProcessLaunchInfoSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessLaunchInfoSP > (python::PythonObject &p, Status &error)
template<>
lldb::DataExtractorSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::DataExtractorSP > (python::PythonObject &p, Status &error)
template<>
std::optional< MemoryRegionInfo > ScriptedPythonInterface::ExtractValueFromPythonObject< std::optional< MemoryRegionInfo > > (python::PythonObject &p, Status &error)
template<>
lldb::ExecutionContextRefSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ExecutionContextRefSP > (python::PythonObject &p, Status &error)
template<>
lldb::DescriptionLevel ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::DescriptionLevel > (python::PythonObject &p, Status &error)
template<>
lldb::StackFrameListSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameListSP > (python::PythonObject &p, Status &error)
template<>
lldb::ValueObjectSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectSP > (python::PythonObject &p, Status &error)
template<>
lldb::ValueObjectListSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectListSP > (python::PythonObject &p, Status &error)
template<>
Log::Channel & LogChannelFor< DWARFLog > ()
void RegisterAbortWithPayloadFrameRecognizer (Process *process)
llvm::json::Value toJSON (const TraceHTR &htr)
llvm::json::Value toJSON (const HTRBlock &block)
llvm::json::Value toJSON (const HTRBlockMetadata &metadata)
HTRBlockLayerUP BasicSuperBlockMerge (IHTRLayer &layer)
The HTR passes are defined below:
FLAGS_ANONYMOUS_ENUM ()
bool GetAbortLocation (llvm::Triple::OSType os, SymbolLocation &location)
Fetches the abort frame location depending on the current platform.
bool GetAssertLocation (llvm::Triple::OSType os, SymbolLocation &location)
Fetches the assert frame location depending on the current platform.
static void DefaultAssertCallback (llvm::StringRef message, llvm::StringRef backtrace, llvm::StringRef prompt)
The default callback prints to stderr.
bool fromJSON (const json::Value &value, JSONUINT64 &uint64, Path path)
bool fromJSON (const json::Value &value, TraceIntelPTStartRequest &packet, Path path)
bool fromJSON (const json::Value &value, LinuxPerfZeroTscConversion &packet, json::Path path)
bool fromJSON (const json::Value &value, TraceIntelPTGetStateResponse &packet, json::Path path)
uint32_t GetWasmVirtualRegisterTag (size_t reg)
uint32_t GetWasmVirtualRegisterIndex (size_t reg)
uint32_t GetWasmRegister (uint8_t tag, uint32_t index)
void SetLLDBErrorLog (Log *log)
Getter and setter for the error log (see g_error_log).
Log * GetLLDBErrorLog ()
bool fromJSON (const llvm::json::Value &value, TraceSupportedResponse &info, llvm::json::Path path)
llvm::json::Value toJSON (const TraceSupportedResponse &packet)
bool fromJSON (const llvm::json::Value &value, TraceStartRequest &packet, llvm::json::Path path)
llvm::json::Value toJSON (const TraceStartRequest &packet)
bool fromJSON (const llvm::json::Value &value, TraceStopRequest &packet, llvm::json::Path path)
llvm::json::Value toJSON (const TraceStopRequest &packet)
bool fromJSON (const llvm::json::Value &value, TraceGetStateRequest &packet, llvm::json::Path path)
llvm::json::Value toJSON (const TraceGetStateRequest &packet)
bool fromJSON (const llvm::json::Value &value, TraceBinaryData &packet, llvm::json::Path path)
llvm::json::Value toJSON (const TraceBinaryData &packet)
bool fromJSON (const llvm::json::Value &value, TraceThreadState &packet, llvm::json::Path path)
llvm::json::Value toJSON (const TraceThreadState &packet)
bool fromJSON (const llvm::json::Value &value, TraceCpuState &packet, llvm::json::Path path)
llvm::json::Value toJSON (const TraceCpuState &packet)
bool fromJSON (const llvm::json::Value &value, TraceGetStateResponse &packet, llvm::json::Path path)
llvm::json::Value toJSON (const TraceGetStateResponse &packet)
bool fromJSON (const llvm::json::Value &value, lldb_private::TraceGetBinaryDataRequest &packet, llvm::json::Path path)
llvm::json::Value toJSON (const TraceGetBinaryDataRequest &packet)
jLLDBTraceGetBinaryData
bool fromJSON (const llvm::json::Value &value, TraceIntelPTStartRequest &packet, llvm::json::Path path)
llvm::json::Value toJSON (const TraceIntelPTStartRequest &packet)
llvm::json::Value toJSON (const JSONUINT64 &uint64, bool hex)
bool fromJSON (const llvm::json::Value &value, JSONUINT64 &uint64, llvm::json::Path path)
bool fromJSON (const llvm::json::Value &value, LinuxPerfZeroTscConversion &packet, llvm::json::Path path)
llvm::json::Value toJSON (const LinuxPerfZeroTscConversion &packet)
bool fromJSON (const llvm::json::Value &value, TraceIntelPTGetStateResponse &packet, llvm::json::Path path)
llvm::json::Value toJSON (const TraceIntelPTGetStateResponse &packet)
template bool LanguageCategory::Get< lldb::TypeFormatImplSP > (FormattersMatchData &, lldb::TypeFormatImplSP &)
Explicit instantiations for the three types.
template bool LanguageCategory::Get< lldb::TypeSummaryImplSP > (FormattersMatchData &, lldb::TypeSummaryImplSP &)
template bool LanguageCategory::Get< lldb::SyntheticChildrenSP > (FormattersMatchData &, lldb::SyntheticChildrenSP &)
bool fromJSON (const json::Value &value, TraceSupportedResponse &packet, Path path)
jLLDBTraceSupported
bool fromJSON (const json::Value &value, TraceStartRequest &packet, Path path)
bool fromJSON (const json::Value &value, TraceStopRequest &packet, Path path)
bool fromJSON (const json::Value &value, TraceGetStateRequest &packet, Path path)
jLLDBTraceGetState
bool fromJSON (const json::Value &value, TraceBinaryData &packet, Path path)
bool fromJSON (const json::Value &value, TraceThreadState &packet, Path path)
bool fromJSON (const json::Value &value, TraceGetStateResponse &packet, Path path)
bool fromJSON (const json::Value &value, TraceCpuState &packet, json::Path path)
bool fromJSON (const json::Value &value, TraceGetBinaryDataRequest &packet, Path path)
Variables
static constexpr OptionEnumValueElement g_auto_download_enum_values []
static constexpr OptionEnumValueElement g_shared_cache_use_enum_values []
const uint32_t LLDB_INVALID_COMPILER_ID = UINT32_MAX
constexpr llvm::StringRef FunctionCallLabelPrefix = "$__lldb_func"
LLDB attaches this prefix to mangled names of functions that get called from JITted expressions.
static constexpr OptionEnumValueElement g_corefile_save_style []
static constexpr OptionEnumValueElement g_description_verbosity_type []
static constexpr OptionEnumValueElement g_sort_option_enumeration []
static constexpr OptionEnumValueElement g_dependents_enumeration []
static constexpr OptionEnumValueElement g_script_option_enumeration []
static constexpr OptionEnumValueElement g_log_handler_type []
static constexpr OptionEnumValueElement g_script_synchro_type []
static constexpr OptionEnumValueElement g_running_mode []
static constexpr OptionEnumValueElement g_exception_stage []
static constexpr OptionEnumValueElement g_name_match_style []
static constexpr OptionEnumValueElement g_completion_type []
static constexpr CommandObject::ArgumentTableEntry g_argument_table []
static constexpr llvm::StringLiteral g_bool_parsing_error_message
static constexpr llvm::StringLiteral g_int_parsing_error_message
static constexpr llvm::StringLiteral g_language_parsing_error_message
TableValidator< 0 > validator
static constexpr uint32_t RISCV_GPR_SP = 2
static constexpr uint32_t RISCV_GPR_FP = 8
constexpr uint32_t BEQ = 0b000
constexpr uint32_t BNE = 0b001
constexpr uint32_t BLT = 0b100
constexpr uint32_t BGE = 0b101
constexpr uint32_t BLTU = 0b110
constexpr uint32_t BGEU = 0b111
template<typename T>
constexpr bool is_load
template<typename T>
constexpr bool is_store
template<typename T>
constexpr bool is_amo_add
template<typename T>
constexpr bool is_amo_bit_op
template<typename T>
constexpr bool is_amo_swap
template<typename T>
constexpr bool is_amo_cmp
static const InstrPattern PATTERNS []
constexpr uint8_t RV32 = 1
constexpr uint8_t RV64 = 2
constexpr uint8_t RV128 = 4
constexpr RegsetDesc FPR_Desc []
constexpr RegsetDesc AARCH64_SVE_Desc []
constexpr RegsetDesc AARCH64_SSVE_Desc []
constexpr RegsetDesc AARCH64_ZA_Desc []
constexpr RegsetDesc AARCH64_ZT_Desc []
constexpr RegsetDesc AARCH64_PAC_Desc []
constexpr RegsetDesc AARCH64_TLS_Desc []
constexpr RegsetDesc AARCH64_MTE_Desc []
constexpr RegsetDesc AARCH64_FPMR_Desc []
constexpr RegsetDesc AARCH64_GCS_Desc []
constexpr RegsetDesc AARCH64_POE_Desc []
constexpr RegsetDesc ARM_VFP_Desc []
constexpr RegsetDesc PPC_VMX_Desc []
constexpr RegsetDesc PPC_VSX_Desc []
LLVM_PACKED_END
static std::atomic< LLDBAssertCallback > g_lldb_assert_callback
static const uint32_t kWasmVirtualRegisterTagMask = 0x03
static const uint32_t kWasmVirtualRegisterIndexMask = 0x3fffffff
static const uint32_t kWasmVirtualRegisterTagShift = 30
Detailed Description
A class that represents a running process on the host machine.
See docs/lldb-gdb-remote.txt for more information.
Enumerations for broadcasting.
HostProcess allows querying and manipulation of processes running on the host machine. It is not intended to be represent a process which is being debugged, although the native debug engine of a platform may likely back inferior processes by a HostProcess.
HostProcess is implemented using static polymorphism so that on any given platform, an instance of HostProcess will always be able to bind statically to the concrete Process implementation for that platform. See HostInfo for more details.
Do not use system-dependent types, like size_t, because they might cause issues when compiling on arm.
Typedef Documentation
ABICreateInstance
typedef lldb::ABISP(* lldb_private::ABICreateInstance) (lldb::ProcessSP process_sp, const ArchSpec &arch)
Definition at line 31 of file lldb-private-interfaces.h.
ArchitectureCreateInstance
typedef std::unique_ptr< Architecture >(* lldb_private::ArchitectureCreateInstance) (const ArchSpec &arch)
Definition at line 33 of file lldb-private-interfaces.h.
AttributeCallback
typedef std::function<bool(const llvm::StringRef &name, const llvm::StringRef &value)> lldb_private::AttributeCallback
Definition at line 44 of file XML.h.
BreakpointHitCallback
using lldb_private::BreakpointHitCallback
Initial value:
    std::function<bool(void *baton, StoppointCallbackContext *context,
                       lldb::user_id_t break_id, lldb::user_id_t break_loc_id)>
Definition at line 114 of file lldb-private-interfaces.h.
BreakpointLocations
using lldb_private::BreakpointLocations = std::vector<lldb::addr_t>
Definition at line 39 of file EmulateInstruction.h.
CallSiteParameterArray
using lldb_private::CallSiteParameterArray = llvm::SmallVector<CallSiteParameter, 0>
A vector of CallSiteParameter.
Definition at line 262 of file Function.h.
CandidateLanguagesVector
typedef std::vector<lldb::LanguageType> lldb_private::CandidateLanguagesVector
Definition at line 128 of file FormatClasses.h.
CommandOverrideCallbackWithResult
typedef bool(* lldb_private::CommandOverrideCallbackWithResult) (void *baton, const char **argv, lldb_private::CommandReturnObject &result)
Definition at line 153 of file lldb-private-types.h.
ComparisonFunction
typedef int(* lldb_private::ComparisonFunction) (const void *, const void *)
Definition at line 143 of file lldb-private-interfaces.h.
DebugDelegateSP
typedef std::shared_ptr<IDebugDelegate> lldb_private::DebugDelegateSP
Definition at line 35 of file ForwardDecl.h.
DebuggerDestroyCallback
typedef void(* lldb_private::DebuggerDestroyCallback) (lldb::user_id_t debugger_id, void *baton)
Definition at line 151 of file lldb-private-types.h.
DebuggerInitializeCallback
typedef void(* lldb_private::DebuggerInitializeCallback) (Debugger &debugger)
Definition at line 144 of file lldb-private-interfaces.h.
DebuggerThreadSP
typedef std::shared_ptr<DebuggerThread> lldb_private::DebuggerThreadSP
Definition at line 36 of file ForwardDecl.h.
DebugMacrosSP
typedef std::shared_ptr<DebugMacros> lldb_private::DebugMacrosSP
Definition at line 22 of file DebugMacros.h.
DiagnosticList
typedef std::vector<std::unique_ptr<Diagnostic> > lldb_private::DiagnosticList
Definition at line 101 of file DiagnosticManager.h.
DisassemblerCreateInstance
typedef lldb::DisassemblerSP(* lldb_private::DisassemblerCreateInstance) (const ArchSpec &arch, const char *flavor, const char *cpu, const char *features)
Definition at line 35 of file lldb-private-interfaces.h.
DynamicLoaderCreateInstance
typedef DynamicLoader *(* lldb_private::DynamicLoaderCreateInstance) (Process *process, bool force)
Definition at line 38 of file lldb-private-interfaces.h.
EmulateInstructionCreateInstance
typedef EmulateInstruction *(* lldb_private::EmulateInstructionCreateInstance) (const ArchSpec &arch, InstructionType inst_type)
Definition at line 63 of file lldb-private-interfaces.h.
ExceptionRecordSP
typedef std::shared_ptr<ExceptionRecord> lldb_private::ExceptionRecordSP
Definition at line 37 of file ForwardDecl.h.
ExceptionRecordUP
typedef std::unique_ptr<ExceptionRecord> lldb_private::ExceptionRecordUP
Definition at line 38 of file ForwardDecl.h.
FormattersMatchVector
typedef std::vector<FormattersMatchCandidate> lldb_private::FormattersMatchVector
Definition at line 127 of file FormatClasses.h.
GetPluginInfo
using lldb_private::GetPluginInfo = std::function<std::vector<RegisteredPluginInfo>()>
Definition at line 77 of file PluginManager.h.
handle_t
using lldb_private::handle_t = void *
Definition at line 20 of file MainLoopWindows.h.
HardwareBreakpointMap
using lldb_private::HardwareBreakpointMap = std::map<lldb::addr_t, HardwareBreakpoint>
Definition at line 23 of file NativeBreakpointList.h.
HighlighterCreateInstance
typedef Highlighter *(* lldb_private::HighlighterCreateInstance) (lldb::LanguageType language)
Definition at line 142 of file lldb-private-interfaces.h.
HistoryThreads
typedef std::vector<lldb::ThreadSP> lldb_private::HistoryThreads
Definition at line 20 of file MemoryHistory.h.
HostInfo
typedef HOST_INFO_TYPE lldb_private::HostInfo
Definition at line 67 of file HostInfo.h.
HostNativeProcess
typedef HostProcessPosix lldb_private::HostNativeProcess
Definition at line 20 of file HostNativeProcess.h.
HostNativeThread
typedef HostThreadPosix lldb_private::HostNativeThread
Definition at line 21 of file HostNativeThreadForward.h.
HTRBlockLayerUP
typedef std::unique_ptr<lldb_private::HTRBlockLayer> lldb_private::HTRBlockLayerUP
Definition at line 299 of file TraceHTR.h.
HTRInstructionLayerUP
typedef std::unique_ptr<lldb_private::HTRInstructionLayer> lldb_private::HTRInstructionLayerUP
Definition at line 301 of file TraceHTR.h.
InstrumentationRuntimeCollection
typedef std::map<lldb::InstrumentationRuntimeType, lldb::InstrumentationRuntimeSP> lldb_private::InstrumentationRuntimeCollection
Definition at line 25 of file InstrumentationRuntime.h.
InstrumentationRuntimeCreateInstance
typedef lldb::InstrumentationRuntimeSP(* lldb_private::InstrumentationRuntimeCreateInstance) (const lldb::ProcessSP &process_sp)
Definition at line 131 of file lldb-private-interfaces.h.
InstrumentationRuntimeGetType
typedef lldb::InstrumentationRuntimeType(* lldb_private::InstrumentationRuntimeGetType) ()
Definition at line 130 of file lldb-private-interfaces.h.
JITLoaderCreateInstance
typedef lldb::JITLoaderSP(* lldb_private::JITLoaderCreateInstance) (Process *process, bool force)
Definition at line 40 of file lldb-private-interfaces.h.
LanguageCreateInstance
typedef Language *(* lldb_private::LanguageCreateInstance) (lldb::LanguageType language)
Definition at line 67 of file lldb-private-interfaces.h.
LanguageRuntimeCreateInstance
typedef LanguageRuntime *(* lldb_private::LanguageRuntimeCreateInstance) (Process *process, lldb::LanguageType language)
Definition at line 68 of file lldb-private-interfaces.h.
LanguageRuntimeGetCommandObject
typedef lldb::CommandObjectSP(* lldb_private::LanguageRuntimeGetCommandObject) (CommandInterpreter &interpreter)
Definition at line 70 of file lldb-private-interfaces.h.
LanguageRuntimeGetExceptionPrecondition
typedef lldb::BreakpointPreconditionSP(* lldb_private::LanguageRuntimeGetExceptionPrecondition) (lldb::LanguageType language, bool throw_bp)
Definition at line 72 of file lldb-private-interfaces.h.
LinuxMapCallback
typedef std::function<bool(llvm::Expected<MemoryRegionInfo>)> lldb_private::LinuxMapCallback
Definition at line 18 of file LinuxProcMaps.h.
LLDBAssertCallback
typedef void(* lldb_private::LLDBAssertCallback) (llvm::StringRef message, llvm::StringRef backtrace, llvm::StringRef prompt)
The default LLDB assert callback, which prints to stderr.
Definition at line 47 of file LLDBAssert.h.
LoadPluginCallbackType
typedef llvm::sys::DynamicLibrary(* lldb_private::LoadPluginCallbackType) (const lldb::DebuggerSP &debugger_sp, const FileSpec &spec, Status &error)
Definition at line 32 of file lldb-private-types.h.
LockFile
typedef LockFilePosix lldb_private::LockFile
Definition at line 20 of file LockFile.h.
MainLoop
using lldb_private::MainLoop = MainLoopPosix
Definition at line 20 of file MainLoop.h.
MemoryHistoryCreateInstance
typedef lldb::MemoryHistorySP(* lldb_private::MemoryHistoryCreateInstance) (const lldb::ProcessSP &process_sp)
Definition at line 128 of file lldb-private-interfaces.h.
MmapArgList
typedef llvm::SmallVector<lldb::addr_t, 6> lldb_private::MmapArgList
Definition at line 64 of file Platform.h.
NamePath
typedef std::vector<std::string> lldb_private::NamePath
Definition at line 40 of file XML.h.
NativeDebugDelegateSP
typedef std::shared_ptr<NativeDebugDelegate> lldb_private::NativeDebugDelegateSP
Definition at line 25 of file NativeProcessWindows.h.
NativeSocket
typedef int lldb_private::NativeSocket
Definition at line 41 of file Socket.h.
NodeCallback
typedef std::function<bool(const XMLNode &node)> lldb_private::NodeCallback
Definition at line 41 of file XML.h.
ObjectContainerCreateInstance
typedef ObjectContainer *(* lldb_private::ObjectContainerCreateInstance) (const lldb::ModuleSP &module_sp, lldb::DataBufferSP &data_sp, lldb::offset_t data_offset, const FileSpec *file, lldb::offset_t offset, lldb::offset_t length)
Definition at line 42 of file lldb-private-interfaces.h.
ObjectContainerCreateMemoryInstance
typedef ObjectContainer *(* lldb_private::ObjectContainerCreateMemoryInstance) (const lldb::ModuleSP &module_sp, lldb::WritableDataBufferSP data_sp, const lldb::ProcessSP &process_sp, lldb::addr_t offset)
Definition at line 46 of file lldb-private-interfaces.h.
ObjectFileCreateInstance
typedef ObjectFile *(* lldb_private::ObjectFileCreateInstance) (const lldb::ModuleSP &module_sp, lldb::DataExtractorSP extractor_sp, lldb::offset_t data_offset, const FileSpec *file, lldb::offset_t file_offset, lldb::offset_t length)
Definition at line 53 of file lldb-private-interfaces.h.
ObjectFileCreateMemoryInstance
typedef ObjectFile *(* lldb_private::ObjectFileCreateMemoryInstance) (const lldb::ModuleSP &module_sp, lldb::WritableDataBufferSP data_sp, const lldb::ProcessSP &process_sp, lldb::addr_t offset)
Definition at line 57 of file lldb-private-interfaces.h.
ObjectFileGetModuleSpecifications
typedef size_t(* lldb_private::ObjectFileGetModuleSpecifications) (const FileSpec &file, lldb::DataExtractorSP &extractor_sp, lldb::offset_t data_offset, lldb::offset_t file_offset, lldb::offset_t length, ModuleSpecList &module_specs)
Definition at line 49 of file lldb-private-interfaces.h.
ObjectFileSaveCore
typedef bool(* lldb_private::ObjectFileSaveCore) (const lldb::ProcessSP &process_sp, lldb_private::SaveCoreOptions &options, Status &error)
Definition at line 60 of file lldb-private-interfaces.h.
OperatingSystemCreateInstance
typedef OperatingSystem *(* lldb_private::OperatingSystemCreateInstance) (Process *process, bool force)
Definition at line 65 of file lldb-private-interfaces.h.
OptionArgVector
typedef std::vector<std::tuple<std::string, int, std::string> > lldb_private::OptionArgVector
Definition at line 29 of file Options.h.
OptionArgVectorSP
typedef std::shared_ptr<OptionArgVector> lldb_private::OptionArgVectorSP
Definition at line 30 of file Options.h.
OptionElementVector
typedef std::vector<OptionArgElement> lldb_private::OptionElementVector
Definition at line 43 of file Options.h.
OptionEnumValues
using lldb_private::OptionEnumValues = llvm::ArrayRef<OptionEnumValueElement>
Definition at line 132 of file lldb-private-types.h.
OptionGroupFormatUsageTextVector
typedef std::vector<std::tuple<lldb::CommandArgumentType, const char *> > lldb_private::OptionGroupFormatUsageTextVector
Definition at line 20 of file OptionGroupFormat.h.
PathSmallString
typedef llvm::SmallString<256> lldb_private::PathSmallString
Definition at line 30 of file lldb-private-types.h.
Pipe
typedef PipePosix lldb_private::Pipe
Definition at line 20 of file Pipe.h.
PlatformCreateInstance
typedef lldb::PlatformSP(* lldb_private::PlatformCreateInstance) (bool force, const ArchSpec *arch)
Definition at line 80 of file lldb-private-interfaces.h.
ProcessCreateInstance
typedef lldb::ProcessSP(* lldb_private::ProcessCreateInstance) (lldb::TargetSP target_sp, lldb::ListenerSP listener_sp, const FileSpec *crash_file_path, bool can_connect)
Definition at line 82 of file lldb-private-interfaces.h.
ProcessInstanceInfoList
typedef std::vector< ProcessInstanceInfo > lldb_private::ProcessInstanceInfoList
Definition at line 32 of file Host.h.
ProcessWindowsSP
typedef std::shared_ptr<ProcessWindows> lldb_private::ProcessWindowsSP
Definition at line 21 of file LocalDebugDelegate.h.
ProtocolServerCreateInstance
typedef lldb::ProtocolServerUP(* lldb_private::ProtocolServerCreateInstance) ()
Definition at line 85 of file lldb-private-interfaces.h.
PTY
using lldb_private::PTY = PseudoTerminal
Definition at line 33 of file ProcessLaunchInfo.h.
RegisterTypeBuilderCreateInstance
typedef lldb::RegisterTypeBuilderSP(* lldb_private::RegisterTypeBuilderCreateInstance) (Target &target)
Definition at line 86 of file lldb-private-interfaces.h.
REPLCreateInstance
typedef lldb::REPLSP(* lldb_private::REPLCreateInstance) (Status &error, lldb::LanguageType language, Debugger *debugger, Target *target, const char *repl_options)
Definition at line 135 of file lldb-private-interfaces.h.
RISCVInst
using lldb_private::RISCVInst
Initial value:
 std::variant<
    LUI, AUIPC, JAL, JALR, B, LB, LH, LW, LBU, LHU, SB, SH, SW, ADDI, SLTI,
    SLTIU, XORI, ORI, ANDI, ADD, SUB, SLL, SLT, SLTU, XOR, SRL, SRA, OR, AND,
    LWU, LD, SD, SLLI, SRLI, SRAI, ADDIW, SLLIW, SRLIW, SRAIW, ADDW, SUBW, SLLW,
    SRLW, SRAW, MUL, MULH, MULHSU, MULHU, DIV, DIVU, REM, REMU, MULW, DIVW,
    DIVUW, REMW, REMUW, LR_W, SC_W, AMOSWAP_W, AMOADD_W, AMOXOR_W, AMOAND_W,
    AMOOR_W, AMOMIN_W, AMOMAX_W, AMOMINU_W, AMOMAXU_W, LR_D, SC_D, AMOSWAP_D,
    AMOADD_D, AMOXOR_D, AMOAND_D, AMOOR_D, AMOMIN_D, AMOMAX_D, AMOMINU_D,
    AMOMAXU_D, FLW, FSW, FMADD_S, FMSUB_S, FNMADD_S, FNMSUB_S, FADD_S, FSUB_S,
    FMUL_S, FDIV_S, FSQRT_S, FSGNJ_S, FSGNJN_S, FSGNJX_S, FMIN_S, FMAX_S,
    FCVT_W_S, FCVT_WU_S, FMV_X_W, FEQ_S, FLT_S, FLE_S, FCLASS_S, FCVT_S_W,
    FCVT_S_WU, FMV_W_X, FCVT_L_S, FCVT_LU_S, FCVT_S_L, FCVT_S_LU, FLD, FSD,
    FMADD_D, FMSUB_D, FNMSUB_D, FNMADD_D, FADD_D, FSUB_D, FMUL_D, FDIV_D,
    FSQRT_D, FSGNJ_D, FSGNJN_D, FSGNJX_D, FMIN_D, FMAX_D, FCVT_S_D, FCVT_D_S,
    FEQ_D, FLT_D, FLE_D, FCLASS_D, FCVT_W_D, FCVT_WU_D, FCVT_D_W, FCVT_D_WU,
    FCVT_L_D, FCVT_LU_D, FMV_X_D, FCVT_D_L, FCVT_D_LU, FMV_D_X, INVALID, EBREAK,
    RESERVED, HINT, NOP>
Definition at line 275 of file RISCVInstructions.h.
ScriptedFrameProviderCreateInstance
typedef llvm::Expected< lldb::SyntheticFrameProviderSP >(* lldb_private::ScriptedFrameProviderCreateInstance) (lldb::StackFrameListSP input_frames, const lldb_private::ScriptedFrameProviderDescriptor &descriptor)
Definition at line 91 of file lldb-private-interfaces.h.
ScriptedInterfaceCreateInstance
typedef bool(* lldb_private::ScriptedInterfaceCreateInstance) (lldb::ScriptLanguage language, ScriptedInterfaceUsages usages)
Definition at line 139 of file lldb-private-interfaces.h.
ScriptInterpreterCreateInstance
typedef lldb::ScriptInterpreterSP(* lldb_private::ScriptInterpreterCreateInstance) (Debugger &debugger)
Definition at line 88 of file lldb-private-interfaces.h.
ScriptInterpreterGetPath
typedef FileSpec(* lldb_private::ScriptInterpreterGetPath) ()
Definition at line 90 of file lldb-private-interfaces.h.
SetPluginEnabled
using lldb_private::SetPluginEnabled = std::function<bool(llvm::StringRef, bool)>
Definition at line 78 of file PluginManager.h.
shared_fd_t
typedef NativeSocket lldb_private::shared_fd_t
Definition at line 42 of file Socket.h.
StatsClock
using lldb_private::StatsClock = std::chrono::high_resolution_clock
Definition at line 29 of file Statistics.h.
StatsTimepoint
using lldb_private::StatsTimepoint = std::chrono::time_point<StatsClock>
Definition at line 30 of file Statistics.h.
StructuredDataFilterLaunchInfo
typedef Status(* lldb_private::StructuredDataFilterLaunchInfo) (ProcessLaunchInfo &launch_info, Target *target)
Definition at line 77 of file lldb-private-interfaces.h.
StructuredDataPluginCreateInstance
typedef lldb::StructuredDataPluginSP(* lldb_private::StructuredDataPluginCreateInstance) (Process &process)
Definition at line 75 of file lldb-private-interfaces.h.
SummaryStatisticsSP
typedef std::shared_ptr<SummaryStatistics> lldb_private::SummaryStatisticsSP
Definition at line 33 of file Statistics.h.
SupportFileNSP
typedef NonNullSharedPtr<lldb_private::SupportFile> lldb_private::SupportFileNSP
Definition at line 80 of file SupportFile.h.
SymbolFileCreateInstance
typedef SymbolFile *(* lldb_private::SymbolFileCreateInstance) (lldb::ObjectFileSP objfile_sp)
Definition at line 99 of file lldb-private-interfaces.h.
SymbolLocatorCreateInstance
typedef SymbolLocator *(* lldb_private::SymbolLocatorCreateInstance) ()
Definition at line 104 of file lldb-private-interfaces.h.
SymbolLocatorDownloadObjectAndSymbolFile
typedef bool(* lldb_private::SymbolLocatorDownloadObjectAndSymbolFile) (ModuleSpec &module_spec, Status &error, bool force_lookup, bool copy_executable)
Definition at line 111 of file lldb-private-interfaces.h.
SymbolLocatorFindSymbolFileInBundle
typedef std::optional< FileSpec >(* lldb_private::SymbolLocatorFindSymbolFileInBundle) (const FileSpec &dsym_bundle_fspec, const UUID *uuid, const ArchSpec *arch)
Definition at line 107 of file lldb-private-interfaces.h.
SymbolLocatorLocateExecutableObjectFile
typedef std::optional< ModuleSpec >(* lldb_private::SymbolLocatorLocateExecutableObjectFile) (const ModuleSpec &module_spec)
Definition at line 105 of file lldb-private-interfaces.h.
SymbolLocatorLocateExecutableSymbolFile
typedef std::optional< FileSpec >(* lldb_private::SymbolLocatorLocateExecutableSymbolFile) (const ModuleSpec &module_spec, const FileSpecList &default_search_paths)
Definition at line 109 of file lldb-private-interfaces.h.
SymbolVendorCreateInstance
typedef SymbolVendor *(* lldb_private::SymbolVendorCreateInstance) (const lldb::ModuleSP &module_sp, lldb_private::Stream *feedback_strm)
Definition at line 100 of file lldb-private-interfaces.h.
SyntheticFrameProviderCreateInstance
typedef llvm::Expected< lldb::SyntheticFrameProviderSP >(* lldb_private::SyntheticFrameProviderCreateInstance) (lldb::StackFrameListSP input_frames, const std::vector< lldb_private::ThreadSpec > &thread_specs)
Definition at line 95 of file lldb-private-interfaces.h.
SystemRuntimeCreateInstance
typedef SystemRuntime *(* lldb_private::SystemRuntimeCreateInstance) (Process *process)
Definition at line 79 of file lldb-private-interfaces.h.
ThreadPlanShouldStopHereCallback
typedef bool(* lldb_private::ThreadPlanShouldStopHereCallback) (ThreadPlan *current_plan, Flags &flags, lldb::FrameComparison operation, Status &status, void *baton)
Definition at line 121 of file lldb-private-interfaces.h.
ThreadPlanStepFromHereCallback
typedef lldb::ThreadPlanSP(* lldb_private::ThreadPlanStepFromHereCallback) (ThreadPlan *current_plan, Flags &flags, lldb::FrameComparison operation, Status &status, void *baton)
Definition at line 124 of file lldb-private-interfaces.h.
ThreadTraceExportCommandCreator
typedef lldb::CommandObjectSP(* lldb_private::ThreadTraceExportCommandCreator) (CommandInterpreter &interpreter)
Definition at line 153 of file lldb-private-interfaces.h.
TraceCreateInstanceForLiveProcess
typedef llvm::Expected< lldb::TraceSP >(* lldb_private::TraceCreateInstanceForLiveProcess) (Process &process)
Definition at line 150 of file lldb-private-interfaces.h.
TraceCreateInstanceFromBundle
typedef llvm::Expected< lldb::TraceSP >(* lldb_private::TraceCreateInstanceFromBundle) (const llvm::json::Value &trace_bundle_description, llvm::StringRef session_file_dir, lldb_private::Debugger &debugger)
Trace.
Definition at line 147 of file lldb-private-interfaces.h.
TraceExporterCreateInstance
typedef llvm::Expected< lldb::TraceExporterUP >(* lldb_private::TraceExporterCreateInstance) ()
Definition at line 152 of file lldb-private-interfaces.h.
type128
typedef struct lldb_private::type128 lldb_private::type128
type256
typedef struct lldb_private::type256 lldb_private::type256
TypeFromParser
typedef TaggedASTType<0> lldb_private::TypeFromParser
Definition at line 40 of file TaggedASTType.h.
TypeFromUser
typedef TaggedASTType<1> lldb_private::TypeFromUser
Definition at line 41 of file TaggedASTType.h.
TypeSystemCreateInstance
typedef lldb::TypeSystemSP(* lldb_private::TypeSystemCreateInstance) (lldb::LanguageType language, Module *module, Target *target)
Definition at line 133 of file lldb-private-interfaces.h.
UnwindAssemblyCreateInstance
typedef UnwindAssembly *(* lldb_private::UnwindAssemblyCreateInstance) (const ArchSpec &arch)
Definition at line 127 of file lldb-private-interfaces.h.
ValueObjectProviderTy
using lldb_private::ValueObjectProviderTy
Initial value:
    std::function<lldb::ValueObjectSP(ConstString, StackFrame *)>
Functor that returns a ValueObjectSP for a variable given its name and the StackFrame of interest.
Used primarily in the Materializer to refetch a ValueObject when the ExecutionContextScope changes.
Definition at line 148 of file lldb-private-types.h.
WatchpointHitCallback
typedef bool(* lldb_private::WatchpointHitCallback) (void *baton, StoppointCallbackContext *context, lldb::user_id_t watch_id)
Definition at line 118 of file lldb-private-interfaces.h.
XMLDocumentImpl
typedef void* lldb_private::XMLDocumentImpl
Definition at line 35 of file XML.h.
XMLNodeImpl
typedef void* lldb_private::XMLNodeImpl
Definition at line 34 of file XML.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
dwarf_rax_x86_64
dwarf_rdx_x86_64
dwarf_rcx_x86_64
dwarf_rbx_x86_64
dwarf_rsi_x86_64
dwarf_rdi_x86_64
dwarf_rbp_x86_64
dwarf_rsp_x86_64
dwarf_r8_x86_64
dwarf_r9_x86_64
dwarf_r10_x86_64
dwarf_r11_x86_64
dwarf_r12_x86_64
dwarf_r13_x86_64
dwarf_r14_x86_64
dwarf_r15_x86_64
dwarf_rip_x86_64
dwarf_xmm0_x86_64
dwarf_xmm1_x86_64
dwarf_xmm2_x86_64
dwarf_xmm3_x86_64
dwarf_xmm4_x86_64
dwarf_xmm5_x86_64
dwarf_xmm6_x86_64
dwarf_xmm7_x86_64
dwarf_xmm8_x86_64
dwarf_xmm9_x86_64
dwarf_xmm10_x86_64
dwarf_xmm11_x86_64
dwarf_xmm12_x86_64
dwarf_xmm13_x86_64
dwarf_xmm14_x86_64
dwarf_xmm15_x86_64
dwarf_st0_x86_64
dwarf_st1_x86_64
dwarf_st2_x86_64
dwarf_st3_x86_64
dwarf_st4_x86_64
dwarf_st5_x86_64
dwarf_st6_x86_64
dwarf_st7_x86_64
dwarf_mm0_x86_64
dwarf_mm1_x86_64
dwarf_mm2_x86_64
dwarf_mm3_x86_64
dwarf_mm4_x86_64
dwarf_mm5_x86_64
dwarf_mm6_x86_64
dwarf_mm7_x86_64
dwarf_rflags_x86_64
dwarf_es_x86_64
dwarf_cs_x86_64
dwarf_ss_x86_64
dwarf_ds_x86_64
dwarf_fs_x86_64
dwarf_gs_x86_64
dwarf_fs_base_x86_64
dwarf_gs_base_x86_64
dwarf_mxcsr_x86_64
dwarf_fctrl_x86_64
dwarf_fstat_x86_64
dwarf_ymm0h_x86_64
dwarf_ymm1h_x86_64
dwarf_ymm2h_x86_64
dwarf_ymm3h_x86_64
dwarf_ymm4h_x86_64
dwarf_ymm5h_x86_64
dwarf_ymm6h_x86_64
dwarf_ymm7h_x86_64
dwarf_ymm8h_x86_64
dwarf_ymm9h_x86_64
dwarf_ymm10h_x86_64
dwarf_ymm11h_x86_64
dwarf_ymm12h_x86_64
dwarf_ymm13h_x86_64
dwarf_ymm14h_x86_64
dwarf_ymm15h_x86_64
dwarf_bnd0_x86_64
dwarf_bnd1_x86_64
dwarf_bnd2_x86_64
dwarf_bnd3_x86_64
Definition at line 139 of file RegisterContext_x86.h.
anonymous enum
anonymous enum
Enumerator
k_first_gpr_arm64
gpr_x0_arm64
gpr_x1_arm64
gpr_x2_arm64
gpr_x3_arm64
gpr_x4_arm64
gpr_x5_arm64
gpr_x6_arm64
gpr_x7_arm64
gpr_x8_arm64
gpr_x9_arm64
gpr_x10_arm64
gpr_x11_arm64
gpr_x12_arm64
gpr_x13_arm64
gpr_x14_arm64
gpr_x15_arm64
gpr_x16_arm64
gpr_x17_arm64
gpr_x18_arm64
gpr_x19_arm64
gpr_x20_arm64
gpr_x21_arm64
gpr_x22_arm64
gpr_x23_arm64
gpr_x24_arm64
gpr_x25_arm64
gpr_x26_arm64
gpr_x27_arm64
gpr_x28_arm64
gpr_fp_arm64
gpr_lr_arm64
gpr_sp_arm64
gpr_pc_arm64
gpr_cpsr_arm64
gpr_w0_arm64
gpr_w1_arm64
gpr_w2_arm64
gpr_w3_arm64
gpr_w4_arm64
gpr_w5_arm64
gpr_w6_arm64
gpr_w7_arm64
gpr_w8_arm64
gpr_w9_arm64
gpr_w10_arm64
gpr_w11_arm64
gpr_w12_arm64
gpr_w13_arm64
gpr_w14_arm64
gpr_w15_arm64
gpr_w16_arm64
gpr_w17_arm64
gpr_w18_arm64
gpr_w19_arm64
gpr_w20_arm64
gpr_w21_arm64
gpr_w22_arm64
gpr_w23_arm64
gpr_w24_arm64
gpr_w25_arm64
gpr_w26_arm64
gpr_w27_arm64
gpr_w28_arm64
k_last_gpr_arm64
k_first_fpr_arm64
fpu_v0_arm64
fpu_v1_arm64
fpu_v2_arm64
fpu_v3_arm64
fpu_v4_arm64
fpu_v5_arm64
fpu_v6_arm64
fpu_v7_arm64
fpu_v8_arm64
fpu_v9_arm64
fpu_v10_arm64
fpu_v11_arm64
fpu_v12_arm64
fpu_v13_arm64
fpu_v14_arm64
fpu_v15_arm64
fpu_v16_arm64
fpu_v17_arm64
fpu_v18_arm64
fpu_v19_arm64
fpu_v20_arm64
fpu_v21_arm64
fpu_v22_arm64
fpu_v23_arm64
fpu_v24_arm64
fpu_v25_arm64
fpu_v26_arm64
fpu_v27_arm64
fpu_v28_arm64
fpu_v29_arm64
fpu_v30_arm64
fpu_v31_arm64
fpu_s0_arm64
fpu_s1_arm64
fpu_s2_arm64
fpu_s3_arm64
fpu_s4_arm64
fpu_s5_arm64
fpu_s6_arm64
fpu_s7_arm64
fpu_s8_arm64
fpu_s9_arm64
fpu_s10_arm64
fpu_s11_arm64
fpu_s12_arm64
fpu_s13_arm64
fpu_s14_arm64
fpu_s15_arm64
fpu_s16_arm64
fpu_s17_arm64
fpu_s18_arm64
fpu_s19_arm64
fpu_s20_arm64
fpu_s21_arm64
fpu_s22_arm64
fpu_s23_arm64
fpu_s24_arm64
fpu_s25_arm64
fpu_s26_arm64
fpu_s27_arm64
fpu_s28_arm64
fpu_s29_arm64
fpu_s30_arm64
fpu_s31_arm64
fpu_d0_arm64
fpu_d1_arm64
fpu_d2_arm64
fpu_d3_arm64
fpu_d4_arm64
fpu_d5_arm64
fpu_d6_arm64
fpu_d7_arm64
fpu_d8_arm64
fpu_d9_arm64
fpu_d10_arm64
fpu_d11_arm64
fpu_d12_arm64
fpu_d13_arm64
fpu_d14_arm64
fpu_d15_arm64
fpu_d16_arm64
fpu_d17_arm64
fpu_d18_arm64
fpu_d19_arm64
fpu_d20_arm64
fpu_d21_arm64
fpu_d22_arm64
fpu_d23_arm64
fpu_d24_arm64
fpu_d25_arm64
fpu_d26_arm64
fpu_d27_arm64
fpu_d28_arm64
fpu_d29_arm64
fpu_d30_arm64
fpu_d31_arm64
fpu_fpsr_arm64
fpu_fpcr_arm64
k_last_fpr_arm64
exc_far_arm64
exc_esr_arm64
exc_exception_arm64
dbg_bvr0_arm64
dbg_bvr1_arm64
dbg_bvr2_arm64
dbg_bvr3_arm64
dbg_bvr4_arm64
dbg_bvr5_arm64
dbg_bvr6_arm64
dbg_bvr7_arm64
dbg_bvr8_arm64
dbg_bvr9_arm64
dbg_bvr10_arm64
dbg_bvr11_arm64
dbg_bvr12_arm64
dbg_bvr13_arm64
dbg_bvr14_arm64
dbg_bvr15_arm64
dbg_bcr0_arm64
dbg_bcr1_arm64
dbg_bcr2_arm64
dbg_bcr3_arm64
dbg_bcr4_arm64
dbg_bcr5_arm64
dbg_bcr6_arm64
dbg_bcr7_arm64
dbg_bcr8_arm64
dbg_bcr9_arm64
dbg_bcr10_arm64
dbg_bcr11_arm64
dbg_bcr12_arm64
dbg_bcr13_arm64
dbg_bcr14_arm64
dbg_bcr15_arm64
dbg_wvr0_arm64
dbg_wvr1_arm64
dbg_wvr2_arm64
dbg_wvr3_arm64
dbg_wvr4_arm64
dbg_wvr5_arm64
dbg_wvr6_arm64
dbg_wvr7_arm64
dbg_wvr8_arm64
dbg_wvr9_arm64
dbg_wvr10_arm64
dbg_wvr11_arm64
dbg_wvr12_arm64
dbg_wvr13_arm64
dbg_wvr14_arm64
dbg_wvr15_arm64
dbg_wcr0_arm64
dbg_wcr1_arm64
dbg_wcr2_arm64
dbg_wcr3_arm64
dbg_wcr4_arm64
dbg_wcr5_arm64
dbg_wcr6_arm64
dbg_wcr7_arm64
dbg_wcr8_arm64
dbg_wcr9_arm64
dbg_wcr10_arm64
dbg_wcr11_arm64
dbg_wcr12_arm64
dbg_wcr13_arm64
dbg_wcr14_arm64
dbg_wcr15_arm64
k_num_registers_arm64
k_num_gpr_registers_arm64
k_num_fpr_registers_arm64
Definition at line 16 of file lldb-arm64-register-enums.h.
anonymous enum
anonymous enum
Enumerator
k_first_gpr_s390x
lldb_r0_s390x
lldb_r1_s390x
lldb_r2_s390x
lldb_r3_s390x
lldb_r4_s390x
lldb_r5_s390x
lldb_r6_s390x
lldb_r7_s390x
lldb_r8_s390x
lldb_r9_s390x
lldb_r10_s390x
lldb_r11_s390x
lldb_r12_s390x
lldb_r13_s390x
lldb_r14_s390x
lldb_r15_s390x
lldb_acr0_s390x
lldb_acr1_s390x
lldb_acr2_s390x
lldb_acr3_s390x
lldb_acr4_s390x
lldb_acr5_s390x
lldb_acr6_s390x
lldb_acr7_s390x
lldb_acr8_s390x
lldb_acr9_s390x
lldb_acr10_s390x
lldb_acr11_s390x
lldb_acr12_s390x
lldb_acr13_s390x
lldb_acr14_s390x
lldb_acr15_s390x
lldb_pswm_s390x
lldb_pswa_s390x
k_last_gpr_s390x
k_first_fpr_s390x
lldb_f0_s390x
lldb_f1_s390x
lldb_f2_s390x
lldb_f3_s390x
lldb_f4_s390x
lldb_f5_s390x
lldb_f6_s390x
lldb_f7_s390x
lldb_f8_s390x
lldb_f9_s390x
lldb_f10_s390x
lldb_f11_s390x
lldb_f12_s390x
lldb_f13_s390x
lldb_f14_s390x
lldb_f15_s390x
lldb_fpc_s390x
k_last_fpr_s390x
k_first_linux_s390x
lldb_orig_r2_s390x
lldb_last_break_s390x
lldb_system_call_s390x
k_last_linux_s390x
k_num_registers_s390x
k_num_gpr_registers_s390x
k_num_fpr_registers_s390x
k_num_linux_registers_s390x
k_num_user_registers_s390x
Definition at line 16 of file lldb-s390x-register-enums.h.
anonymous enum
anonymous enum
Enumerator
k_first_gpr_i386
lldb_eax_i386
lldb_ebx_i386
lldb_ecx_i386
lldb_edx_i386
lldb_edi_i386
lldb_esi_i386
lldb_ebp_i386
lldb_esp_i386
lldb_eip_i386
lldb_eflags_i386
lldb_cs_i386
lldb_fs_i386
lldb_gs_i386
lldb_ss_i386
lldb_ds_i386
lldb_es_i386
k_first_alias_i386
lldb_ax_i386
lldb_bx_i386
lldb_cx_i386
lldb_dx_i386
lldb_di_i386
lldb_si_i386
lldb_bp_i386
lldb_sp_i386
lldb_ah_i386
lldb_bh_i386
lldb_ch_i386
lldb_dh_i386
lldb_al_i386
lldb_bl_i386
lldb_cl_i386
lldb_dl_i386
k_last_alias_i386
k_last_gpr_i386
k_first_fpr_i386
lldb_fctrl_i386
lldb_fstat_i386
lldb_ftag_i386
lldb_fop_i386
lldb_fiseg_i386
lldb_fioff_i386
lldb_foseg_i386
lldb_fooff_i386
lldb_mxcsr_i386
lldb_mxcsrmask_i386
lldb_st0_i386
lldb_st1_i386
lldb_st2_i386
lldb_st3_i386
lldb_st4_i386
lldb_st5_i386
lldb_st6_i386
lldb_st7_i386
lldb_mm0_i386
lldb_mm1_i386
lldb_mm2_i386
lldb_mm3_i386
lldb_mm4_i386
lldb_mm5_i386
lldb_mm6_i386
lldb_mm7_i386
lldb_xmm0_i386
lldb_xmm1_i386
lldb_xmm2_i386
lldb_xmm3_i386
lldb_xmm4_i386
lldb_xmm5_i386
lldb_xmm6_i386
lldb_xmm7_i386
k_last_fpr_i386
k_first_avx_i386
lldb_ymm0_i386
lldb_ymm1_i386
lldb_ymm2_i386
lldb_ymm3_i386
lldb_ymm4_i386
lldb_ymm5_i386
lldb_ymm6_i386
lldb_ymm7_i386
k_last_avx_i386
k_first_mpxr_i386
lldb_bnd0_i386
lldb_bnd1_i386
lldb_bnd2_i386
lldb_bnd3_i386
k_last_mpxr_i386
k_first_mpxc_i386
lldb_bndcfgu_i386
lldb_bndstatus_i386
k_last_mpxc_i386
k_first_dbr_i386
lldb_dr0_i386
lldb_dr1_i386
lldb_dr2_i386
lldb_dr3_i386
lldb_dr4_i386
lldb_dr5_i386
lldb_dr6_i386
lldb_dr7_i386
k_last_dbr_i386
k_num_registers_i386
k_num_gpr_registers_i386
k_num_fpr_registers_i386
k_num_avx_registers_i386
k_num_mpx_registers_i386
k_num_user_registers_i386
k_num_dbr_registers_i386
Definition at line 16 of file lldb-x86-register-enums.h.
anonymous enum
anonymous enum
Enumerator
k_first_gpr_x86_64
lldb_rax_x86_64
lldb_rbx_x86_64
lldb_rcx_x86_64
lldb_rdx_x86_64
lldb_rdi_x86_64
lldb_rsi_x86_64
lldb_rbp_x86_64
lldb_rsp_x86_64
lldb_r8_x86_64
lldb_r9_x86_64
lldb_r10_x86_64
lldb_r11_x86_64
lldb_r12_x86_64
lldb_r13_x86_64
lldb_r14_x86_64
lldb_r15_x86_64
lldb_rip_x86_64
lldb_rflags_x86_64
lldb_cs_x86_64
lldb_fs_x86_64
lldb_gs_x86_64
lldb_ss_x86_64
lldb_ds_x86_64
lldb_es_x86_64
k_first_alias_x86_64
lldb_eax_x86_64
lldb_ebx_x86_64
lldb_ecx_x86_64
lldb_edx_x86_64
lldb_edi_x86_64
lldb_esi_x86_64
lldb_ebp_x86_64
lldb_esp_x86_64
lldb_r8d_x86_64
lldb_r9d_x86_64
lldb_r10d_x86_64
lldb_r11d_x86_64
lldb_r12d_x86_64
lldb_r13d_x86_64
lldb_r14d_x86_64
lldb_r15d_x86_64
lldb_ax_x86_64
lldb_bx_x86_64
lldb_cx_x86_64
lldb_dx_x86_64
lldb_di_x86_64
lldb_si_x86_64
lldb_bp_x86_64
lldb_sp_x86_64
lldb_r8w_x86_64
lldb_r9w_x86_64
lldb_r10w_x86_64
lldb_r11w_x86_64
lldb_r12w_x86_64
lldb_r13w_x86_64
lldb_r14w_x86_64
lldb_r15w_x86_64
lldb_ah_x86_64
lldb_bh_x86_64
lldb_ch_x86_64
lldb_dh_x86_64
lldb_al_x86_64
lldb_bl_x86_64
lldb_cl_x86_64
lldb_dl_x86_64
lldb_dil_x86_64
lldb_sil_x86_64
lldb_bpl_x86_64
lldb_spl_x86_64
lldb_r8l_x86_64
lldb_r9l_x86_64
lldb_r10l_x86_64
lldb_r11l_x86_64
lldb_r12l_x86_64
lldb_r13l_x86_64
lldb_r14l_x86_64
lldb_r15l_x86_64
k_last_alias_x86_64
k_last_gpr_x86_64
k_first_fpr_x86_64
lldb_fctrl_x86_64
lldb_fstat_x86_64
lldb_ftag_x86_64
lldb_fop_x86_64
lldb_fiseg_x86_64
lldb_fioff_x86_64
lldb_fip_x86_64
lldb_foseg_x86_64
lldb_fooff_x86_64
lldb_fdp_x86_64
lldb_mxcsr_x86_64
lldb_mxcsrmask_x86_64
lldb_st0_x86_64
lldb_st1_x86_64
lldb_st2_x86_64
lldb_st3_x86_64
lldb_st4_x86_64
lldb_st5_x86_64
lldb_st6_x86_64
lldb_st7_x86_64
lldb_mm0_x86_64
lldb_mm1_x86_64
lldb_mm2_x86_64
lldb_mm3_x86_64
lldb_mm4_x86_64
lldb_mm5_x86_64
lldb_mm6_x86_64
lldb_mm7_x86_64
lldb_xmm0_x86_64
lldb_xmm1_x86_64
lldb_xmm2_x86_64
lldb_xmm3_x86_64
lldb_xmm4_x86_64
lldb_xmm5_x86_64
lldb_xmm6_x86_64
lldb_xmm7_x86_64
lldb_xmm8_x86_64
lldb_xmm9_x86_64
lldb_xmm10_x86_64
lldb_xmm11_x86_64
lldb_xmm12_x86_64
lldb_xmm13_x86_64
lldb_xmm14_x86_64
lldb_xmm15_x86_64
k_last_fpr_x86_64
k_first_avx_x86_64
lldb_ymm0_x86_64
lldb_ymm1_x86_64
lldb_ymm2_x86_64
lldb_ymm3_x86_64
lldb_ymm4_x86_64
lldb_ymm5_x86_64
lldb_ymm6_x86_64
lldb_ymm7_x86_64
lldb_ymm8_x86_64
lldb_ymm9_x86_64
lldb_ymm10_x86_64
lldb_ymm11_x86_64
lldb_ymm12_x86_64
lldb_ymm13_x86_64
lldb_ymm14_x86_64
lldb_ymm15_x86_64
k_last_avx_x86_64
k_first_mpxr_x86_64
lldb_bnd0_x86_64
lldb_bnd1_x86_64
lldb_bnd2_x86_64
lldb_bnd3_x86_64
k_last_mpxr_x86_64
k_first_mpxc_x86_64
lldb_bndcfgu_x86_64
lldb_bndstatus_x86_64
k_last_mpxc_x86_64
k_first_dbr_x86_64
lldb_dr0_x86_64
lldb_dr1_x86_64
lldb_dr2_x86_64
lldb_dr3_x86_64
lldb_dr4_x86_64
lldb_dr5_x86_64
lldb_dr6_x86_64
lldb_dr7_x86_64
k_last_dbr_x86_64
k_num_registers_x86_64
k_num_gpr_registers_x86_64
k_num_fpr_registers_x86_64
k_num_avx_registers_x86_64
k_num_mpx_registers_x86_64
k_num_user_registers_x86_64
k_num_dbr_registers_x86_64
Definition at line 140 of file lldb-x86-register-enums.h.
anonymous enum
anonymous enum
Enumerator
UNWIND_X86_REG_NONE
UNWIND_X86_REG_EBX
UNWIND_X86_REG_ECX
UNWIND_X86_REG_EDX
UNWIND_X86_REG_EDI
UNWIND_X86_REG_ESI
UNWIND_X86_REG_EBP
Definition at line 58 of file CompactUnwindInfo.cpp.
anonymous enum
anonymous enum
Enumerator
ehframe_eax_i386
ehframe_ecx_i386
ehframe_edx_i386
ehframe_ebx_i386
ehframe_esp_i386
ehframe_ebp_i386
ehframe_esi_i386
ehframe_edi_i386
ehframe_eip_i386
ehframe_eflags_i386
ehframe_st0_i386
ehframe_st1_i386
ehframe_st2_i386
ehframe_st3_i386
ehframe_st4_i386
ehframe_st5_i386
ehframe_st6_i386
ehframe_st7_i386
ehframe_xmm0_i386
ehframe_xmm1_i386
ehframe_xmm2_i386
ehframe_xmm3_i386
ehframe_xmm4_i386
ehframe_xmm5_i386
ehframe_xmm6_i386
ehframe_xmm7_i386
ehframe_mm0_i386
ehframe_mm1_i386
ehframe_mm2_i386
ehframe_mm3_i386
ehframe_mm4_i386
ehframe_mm5_i386
ehframe_mm6_i386
ehframe_mm7_i386
Definition at line 25 of file RegisterContext_x86.h.
anonymous enum
anonymous enum
Enumerator
k_first_gpr_arm
gpr_r0_arm
gpr_r1_arm
gpr_r2_arm
gpr_r3_arm
gpr_r4_arm
gpr_r5_arm
gpr_r6_arm
gpr_r7_arm
gpr_r8_arm
gpr_r9_arm
gpr_r10_arm
gpr_r11_arm
gpr_r12_arm
gpr_r13_arm
gpr_sp_arm
gpr_r14_arm
gpr_lr_arm
gpr_r15_arm
gpr_pc_arm
gpr_cpsr_arm
k_last_gpr_arm
k_first_fpr_arm
fpu_s0_arm
fpu_s1_arm
fpu_s2_arm
fpu_s3_arm
fpu_s4_arm
fpu_s5_arm
fpu_s6_arm
fpu_s7_arm
fpu_s8_arm
fpu_s9_arm
fpu_s10_arm
fpu_s11_arm
fpu_s12_arm
fpu_s13_arm
fpu_s14_arm
fpu_s15_arm
fpu_s16_arm
fpu_s17_arm
fpu_s18_arm
fpu_s19_arm
fpu_s20_arm
fpu_s21_arm
fpu_s22_arm
fpu_s23_arm
fpu_s24_arm
fpu_s25_arm
fpu_s26_arm
fpu_s27_arm
fpu_s28_arm
fpu_s29_arm
fpu_s30_arm
fpu_s31_arm
fpu_fpscr_arm
fpu_d0_arm
fpu_d1_arm
fpu_d2_arm
fpu_d3_arm
fpu_d4_arm
fpu_d5_arm
fpu_d6_arm
fpu_d7_arm
fpu_d8_arm
fpu_d9_arm
fpu_d10_arm
fpu_d11_arm
fpu_d12_arm
fpu_d13_arm
fpu_d14_arm
fpu_d15_arm
fpu_d16_arm
fpu_d17_arm
fpu_d18_arm
fpu_d19_arm
fpu_d20_arm
fpu_d21_arm
fpu_d22_arm
fpu_d23_arm
fpu_d24_arm
fpu_d25_arm
fpu_d26_arm
fpu_d27_arm
fpu_d28_arm
fpu_d29_arm
fpu_d30_arm
fpu_d31_arm
fpu_q0_arm
fpu_q1_arm
fpu_q2_arm
fpu_q3_arm
fpu_q4_arm
fpu_q5_arm
fpu_q6_arm
fpu_q7_arm
fpu_q8_arm
fpu_q9_arm
fpu_q10_arm
fpu_q11_arm
fpu_q12_arm
fpu_q13_arm
fpu_q14_arm
fpu_q15_arm
k_last_fpr_arm
exc_exception_arm
exc_fsr_arm
exc_far_arm
dbg_bvr0_arm
dbg_bvr1_arm
dbg_bvr2_arm
dbg_bvr3_arm
dbg_bvr4_arm
dbg_bvr5_arm
dbg_bvr6_arm
dbg_bvr7_arm
dbg_bvr8_arm
dbg_bvr9_arm
dbg_bvr10_arm
dbg_bvr11_arm
dbg_bvr12_arm
dbg_bvr13_arm
dbg_bvr14_arm
dbg_bvr15_arm
dbg_bcr0_arm
dbg_bcr1_arm
dbg_bcr2_arm
dbg_bcr3_arm
dbg_bcr4_arm
dbg_bcr5_arm
dbg_bcr6_arm
dbg_bcr7_arm
dbg_bcr8_arm
dbg_bcr9_arm
dbg_bcr10_arm
dbg_bcr11_arm
dbg_bcr12_arm
dbg_bcr13_arm
dbg_bcr14_arm
dbg_bcr15_arm
dbg_wvr0_arm
dbg_wvr1_arm
dbg_wvr2_arm
dbg_wvr3_arm
dbg_wvr4_arm
dbg_wvr5_arm
dbg_wvr6_arm
dbg_wvr7_arm
dbg_wvr8_arm
dbg_wvr9_arm
dbg_wvr10_arm
dbg_wvr11_arm
dbg_wvr12_arm
dbg_wvr13_arm
dbg_wvr14_arm
dbg_wvr15_arm
dbg_wcr0_arm
dbg_wcr1_arm
dbg_wcr2_arm
dbg_wcr3_arm
dbg_wcr4_arm
dbg_wcr5_arm
dbg_wcr6_arm
dbg_wcr7_arm
dbg_wcr8_arm
dbg_wcr9_arm
dbg_wcr10_arm
dbg_wcr11_arm
dbg_wcr12_arm
dbg_wcr13_arm
dbg_wcr14_arm
dbg_wcr15_arm
k_num_registers_arm
k_num_gpr_registers_arm
k_num_fpr_registers_arm
Definition at line 16 of file lldb-arm-register-enums.h.
anonymous enum
anonymous enum
Enumerator
dwarf_eax_i386
dwarf_ecx_i386
dwarf_edx_i386
dwarf_ebx_i386
dwarf_esp_i386
dwarf_ebp_i386
dwarf_esi_i386
dwarf_edi_i386
dwarf_eip_i386
dwarf_eflags_i386
dwarf_st0_i386
dwarf_st1_i386
dwarf_st2_i386
dwarf_st3_i386
dwarf_st4_i386
dwarf_st5_i386
dwarf_st6_i386
dwarf_st7_i386
dwarf_xmm0_i386
dwarf_xmm1_i386
dwarf_xmm2_i386
dwarf_xmm3_i386
dwarf_xmm4_i386
dwarf_xmm5_i386
dwarf_xmm6_i386
dwarf_xmm7_i386
dwarf_mm0_i386
dwarf_mm1_i386
dwarf_mm2_i386
dwarf_mm3_i386
dwarf_mm4_i386
dwarf_mm5_i386
dwarf_mm6_i386
dwarf_mm7_i386
dwarf_fctrl_i386
dwarf_fstat_i386
dwarf_mxcsr_i386
dwarf_es_i386
dwarf_cs_i386
dwarf_ss_i386
dwarf_ds_i386
dwarf_fs_i386
dwarf_gs_i386
dwarf_bnd0_i386
dwarf_bnd1_i386
dwarf_bnd2_i386
dwarf_bnd3_i386
Definition at line 76 of file RegisterContext_x86.h.
anonymous enum
anonymous enum
Enumerator
UNWIND_X86_64_REG_NONE
UNWIND_X86_64_REG_RBX
UNWIND_X86_64_REG_R12
UNWIND_X86_64_REG_R13
UNWIND_X86_64_REG_R14
UNWIND_X86_64_REG_R15
UNWIND_X86_64_REG_RBP
Definition at line 86 of file CompactUnwindInfo.cpp.
AddressClass
enum class lldb_private::AddressClass strong
Enumerator
eInvalid
eUnknown
eCode
eCodeAlternateISA
eData
eDebug
eRuntime
Definition at line 50 of file lldb-private-enumerations.h.
AddressType
enum lldb_private::AddressType
Enumerator
eAddressTypeInvalid
eAddressTypeFile
Address is an address as found in an object or symbol file.
eAddressTypeLoad
Address is an address as in the current target inferior process.
eAddressTypeHost
Address is an address in the process that is running this code.
Definition at line 32 of file lldb-private-enumerations.h.
AppleArm64ExceptionClass
enum class lldb_private::AppleArm64ExceptionClass : unsigned strong
Definition at line 16 of file AppleArm64ExceptionClass.h.
ArchitectureType
enum lldb_private::ArchitectureType
Enumerator
eArchTypeInvalid
eArchTypeMachO
eArchTypeELF
eArchTypeCOFF
eArchTypeXCOFF
kNumArchTypes
Definition at line 63 of file lldb-private-enumerations.h.
ArgumentRepetitionType
enum lldb_private::ArgumentRepetitionType
Enumerator
eArgRepeatPlain
eArgRepeatOptional
eArgRepeatPlus
eArgRepeatStar
eArgRepeatRange
eArgRepeatPairPlain
eArgRepeatPairOptional
eArgRepeatPairPlus
eArgRepeatPairStar
eArgRepeatPairRange
eArgRepeatPairRangeOptional
Definition at line 97 of file lldb-private-enumerations.h.
ARM_ShifterType
enum lldb_private::ARM_ShifterType
Enumerator
SRType_LSL
SRType_LSR
SRType_ASR
SRType_ROR
SRType_RRX
SRType_Invalid
Definition at line 22 of file ARMDefines.h.
CompilerContextKind
enum class lldb_private::CompilerContextKind : uint16_t strong
Enumerator
Invalid
TranslationUnit
Module
Namespace
ClassOrStruct
Union
Function
Variable
Enum
Typedef
Builtin
Any
AnyType
Match any type.
AnyDeclContext
Math any declaration context.
LLVM_MARK_AS_BITMASK_ENUM
Definition at line 197 of file lldb-private-enumerations.h.
CompletionMode
enum class lldb_private::CompletionMode strong
Enumerator
Normal
The current token has been completed.
The client should indicate this to the user (usually this is done by adding a trailing space behind the token). Example: "command sub" -> "command subcommand " (note the trailing space).
Partial
The current token has been partially completed.
This means that we found a completion, but that the token is still incomplete. Examples for this are file paths, where we want to complete "/bi" to "/bin/", but the file path token is still incomplete after the completion. Clients should not indicate to the user that this is a full completion (e.g. by not inserting the usual trailing space after a successful completion). Example: "file /us" -> "file /usr/" (note the missing trailing space).
RewriteLine
The full line has been rewritten by the completion.
Example: "alias name" -> "other_command full_name".
Definition at line 19 of file CompletionRequest.h.
DiagnosticOrigin
enum lldb_private::DiagnosticOrigin
Enumerator
eDiagnosticOriginUnknown
eDiagnosticOriginLLDB
eDiagnosticOriginClang
eDiagnosticOriginSwift
eDiagnosticOriginLLVM
Definition at line 48 of file DiagnosticManager.h.
DWARFLog
enum class lldb_private::DWARFLog : Log::MaskType strong
Enumerator
DebugInfo
DebugLine
DebugMap
Lookups
TypeCompletion
SplitDwarf
Definition at line 17 of file LogChannelDWARF.h.
DynamicClassInfoHelper
enum lldb_private::DynamicClassInfoHelper
Enumerator
eDynamicClassInfoHelperAuto
eDynamicClassInfoHelperRealizedClassesStruct
eDynamicClassInfoHelperCopyRealizedClassList
eDynamicClassInfoHelperGetRealizedClassList
Definition at line 74 of file Target.h.
ExecutionPolicy
enum lldb_private::ExecutionPolicy
Expression execution policies.
Enumerator
eExecutionPolicyOnlyWhenNeeded
eExecutionPolicyNever
eExecutionPolicyAlways
eExecutionPolicyTopLevel
Definition at line 146 of file lldb-private-enumerations.h.
ExpeditedRegs
enum class lldb_private::ExpeditedRegs strong
Enumerator
Minimal
Full
Definition at line 19 of file NativeRegisterContext.h.
FollowForkMode
enum lldb_private::FollowForkMode
Enumerator
eFollowParent
eFollowChild
Definition at line 178 of file lldb-private-enumerations.h.
FormatCategoryItem
enum lldb_private::FormatCategoryItem
Format category entry types.
Enumerator
eFormatCategoryItemSummary
eFormatCategoryItemFilter
eFormatCategoryItemSynth
eFormatCategoryItemFormat
Definition at line 138 of file lldb-private-enumerations.h.
HistoryPCType
enum class lldb_private::HistoryPCType strong
Specifies the type of PCs when creating a HistoryThread.
Returns - Usually, when LLDB unwinds the stack or we retrieve a stack trace via backtrace() we are collecting return addresses (except for the topmost frame which is the actual PC). LLDB then maps these return addresses back to call addresses to give accurate source line annotations.
ReturnsNoZerothFrame - Some trace providers (e.g., libsanitizers traces) collect return addresses but prune the topmost frames, so we should skip the special treatment of frame 0.
Calls - Other trace providers (e.g., ASan compiler-rt runtime) already perform this mapping, so we need to prevent LLDB from doing it again.
Enumerator
Returns
PCs are return addresses, except for topmost frame.
ReturnsNoZerothFrame
All PCs are return addresses.
Calls
PCs are call addresses.
Definition at line 261 of file lldb-private-enumerations.h.
ImportStdModule
enum lldb_private::ImportStdModule
Enumerator
eImportStdModuleFalse
eImportStdModuleFallback
eImportStdModuleTrue
Definition at line 68 of file Target.h.
InlineStrategy
enum lldb_private::InlineStrategy
Enumerator
eInlineBreakpointsNever
eInlineBreakpointsHeaders
eInlineBreakpointsAlways
Definition at line 50 of file Target.h.
InstructionType
enum lldb_private::InstructionType
Instruction types.
Enumerator
eInstructionTypeAny
eInstructionTypePrologueEpilogue
eInstructionTypePCModifying
eInstructionTypeAll
Definition at line 126 of file lldb-private-enumerations.h.
IterationAction
enum class lldb_private::IterationAction strong
Useful for callbacks whose return type indicates whether to continue iteration or short-circuit.
Enumerator
Continue
Stop
Definition at line 246 of file lldb-private-enumerations.h.
KDPLog
enum class lldb_private::KDPLog : Log::MaskType strong
Enumerator
Async
Breakpoints
Comm
MemoryDataLong
MemoryDataShort
Memory
Packets
Process
Step
Thread
Watchpoints
Definition at line 17 of file ProcessKDPLog.h.
LanguageRuntimeDescriptionDisplayVerbosity
enum lldb_private::LanguageRuntimeDescriptionDisplayVerbosity
Enumerator
eLanguageRuntimeDescriptionDisplayVerbosityCompact
eLanguageRuntimeDescriptionDisplayVerbosityFull
Definition at line 162 of file lldb-private-enumerations.h.
LazyBool
enum lldb_private::LazyBool
Enumerator
eLazyBoolCalculate
eLazyBoolNo
eLazyBoolYes
Definition at line 123 of file lldb-private-enumerations.h.
LineStatus
enum class lldb_private::LineStatus strong
Enumerator
Success
Status
Done
Definition at line 184 of file lldb-private-enumerations.h.
LLDBLog
enum class lldb_private::LLDBLog : Log::MaskType strong
Enumerator
API
AST
Breakpoints
Commands
Communication
Connection
DataFormatters
Demangle
DynamicLoader
Events
Expressions
Host
JITLoader
Language
MMap
Modules
Object
OS
Platform
Process
Script
State
Step
Symbols
SystemRuntime
Target
Temporary
Thread
Types
Unwind
Watchpoints
OnDemand
Source
Disassembler
InstrumentationRuntime
LLVM_MARK_AS_BITMASK_ENUM
Definition at line 18 of file LLDBLog.h.
LoadCWDlldbinitFile
enum lldb_private::LoadCWDlldbinitFile
Enumerator
eLoadCWDlldbinitTrue
eLoadCWDlldbinitFalse
eLoadCWDlldbinitWarn
Definition at line 62 of file Target.h.
LoadDependentFiles
enum lldb_private::LoadDependentFiles
Enumerator
eLoadDependentsDefault
eLoadDependentsYes
eLoadDependentsNo
Definition at line 238 of file lldb-private-enumerations.h.
LoadScriptFromSymFile
enum lldb_private::LoadScriptFromSymFile
Enumerator
eLoadScriptFromSymFileTrue
eLoadScriptFromSymFileFalse
eLoadScriptFromSymFileWarn
Definition at line 56 of file Target.h.
LogHandlerKind
enum lldb_private::LogHandlerKind
Enumerator
eLogHandlerStream
eLogHandlerCallback
eLogHandlerCircular
eLogHandlerSystem
eLogHandlerDefault
Definition at line 230 of file lldb-private-enumerations.h.
MemoryModuleLoadLevel
enum lldb_private::MemoryModuleLoadLevel
Enumerator
eMemoryModuleLoadLevelMinimal
eMemoryModuleLoadLevelPartial
eMemoryModuleLoadLevelComplete
Definition at line 171 of file lldb-private-enumerations.h.
MmapFlags
enum lldb_private::MmapFlags
Enumerator
eMmapFlagsPrivate
eMmapFlagsAnon
Definition at line 46 of file Platform.h.
MmapProt
enum lldb_private::MmapProt
Enumerator
eMmapProtNone
eMmapProtExec
eMmapProtRead
eMmapProtWrite
Definition at line 20 of file InferiorCallPOSIX.h.
NameMatch
enum class lldb_private::NameMatch strong
Enumerator
Ignore
Equals
Contains
StartsWith
EndsWith
RegularExpression
Definition at line 15 of file NameMatches.h.
POSIXLog
enum class lldb_private::POSIXLog : Log::MaskType strong
Enumerator
Breakpoints
Memory
Process
Ptrace
Registers
Thread
Watchpoints
Trace
Definition at line 18 of file ProcessPOSIXLog.h.
PredicateBroadcastType
enum lldb_private::PredicateBroadcastType
Enumerator
eBroadcastNever
No broadcast will be sent when the value is modified.
eBroadcastAlways
Always send a broadcast when the value is modified.
eBroadcastOnChange
Only broadcast if the value changes when the value is modified.
Definition at line 27 of file Predicate.h.
ScriptedCommandSynchronicity
enum lldb_private::ScriptedCommandSynchronicity
Enumerator
eScriptedCommandSynchronicitySynchronous
eScriptedCommandSynchronicityAsynchronous
eScriptedCommandSynchronicityCurrentValue
Definition at line 154 of file lldb-private-enumerations.h.
SortOrder
enum lldb_private::SortOrder
Enumerator
eSortOrderNone
eSortOrderByAddress
eSortOrderByName
eSortOrderBySize
Definition at line 113 of file lldb-private-enumerations.h.
StatisticKind
enum lldb_private::StatisticKind
Enumerator
ExpressionSuccessful
ExpressionFailure
FrameVarSuccess
FrameVarFailure
StatisticMax
Definition at line 221 of file lldb-private-enumerations.h.
StepType
enum lldb_private::StepType
Enumerator
eStepTypeNone
eStepTypeTrace
Single step one instruction.
eStepTypeTraceOver
Single step one instruction, stepping over.
eStepTypeInto
Single step into a specified context.
eStepTypeOver
Single step over a specified context.
eStepTypeOut
Single step out a specified context.
eStepTypeScripted
A step type implemented by the script interpreter.
Definition at line 21 of file lldb-private-enumerations.h.
SystemLog
enum class lldb_private::SystemLog : Log::MaskType strong
Enumerator
System
Definition at line 38 of file Host.h.
TypeValidatorResult
enum class lldb_private::TypeValidatorResult : bool strong
Enumerator
Success
Failure
Definition at line 194 of file lldb-private-enumerations.h.
VarSetOperationType
enum lldb_private::VarSetOperationType
Settable state variable types.
Enumerator
eVarSetOperationReplace
eVarSetOperationInsertBefore
eVarSetOperationInsertAfter
eVarSetOperationRemove
eVarSetOperationAppend
eVarSetOperationClear
eVarSetOperationAssign
eVarSetOperationInvalid
Definition at line 86 of file lldb-private-enumerations.h.
Vote
enum lldb_private::Vote
Enumerator
eVoteNo
eVoteNoOpinion
eVoteYes
Definition at line 61 of file lldb-private-enumerations.h.
WasmVirtualRegisterKinds
enum lldb_private::WasmVirtualRegisterKinds
Enumerator
eWasmTagNotAWasmLocation
eWasmTagLocal
eWasmTagGlobal
eWasmTagOperandStack
Definition at line 27 of file WasmVirtualRegisters.h.
WindowsLog
enum class lldb_private::WindowsLog : Log::MaskType strong
Enumerator
Breakpoints
Event
Exception
Memory
Process
Registers
Step
Thread
Definition at line 17 of file ProcessWindowsLog.h.
Function Documentation
_lldb_assert()
void lldb_private::_lldb_assert (bool expression, const char * expr_text, const char * func, const char * file, unsigned int line, std::once_flag & once_flag)
Don't use _lldb_assert directly.
Use the lldbassert macro instead so that LLDB asserts become regular asserts in NDEBUG builds.
Definition at line 36 of file LLDBAssert.cpp.
References g_lldb_assert_callback.
AbridgedToFullTagWord()
uint16_t lldb_private::AbridgedToFullTagWord (uint8_t abridged_tw, uint16_t sw, llvm::ArrayRef< MMSReg > st_regs)
Definition at line 16 of file RegisterContext_x86.cpp.
AddNamesMatchingPartialString()
template<typename ValueType> int lldb_private::AddNamesMatchingPartialString (const std::map< std::string, ValueType, std::less<> > & in_map, llvm::StringRef cmd_str, StringList & matches, StringList * descriptions = nullptr)
Definition at line 37 of file CommandObject.h.
References lldb_private::StringList::AppendString().
Referenced by lldb_private::CommandInterpreter::GetAliasCommandObject(), lldb_private::CommandInterpreter::GetAliasFullName(), lldb_private::CommandInterpreter::GetCommandNamesMatchingPartialString(), lldb_private::CommandInterpreter::GetCommandSP(), lldb_private::CommandObjectMultiword::GetSubcommandSP(), lldb_private::CommandInterpreter::GetUserCommandObject(), and lldb_private::CommandObjectMultiword::HandleCompletion().
addSupplementaryRegister()
void lldb_private::addSupplementaryRegister (std::vector< DynamicRegisterInfo::Register > & regs, DynamicRegisterInfo::Register new_reg_info)
Definition at line 807 of file DynamicRegisterInfo.cpp.
References lldb_private::DynamicRegisterInfo::Register::value_regs.
Referenced by addCombinedRegisters(), addPartialRegisters(), and addPartialRegisters().
Align()
uint32_t lldb_private::Align (uint32_t val, uint32_t alignment) inline static
Definition at line 21 of file ARMUtils.h.
Referenced by lldb_private::EmulateInstructionARM::EmulateADR(), lldb_private::EmulateInstructionARM::EmulateBLXImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRBLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRHLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRRtPCRelative(), lldb_private::EmulateInstructionARM::EmulateLDRSBLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRSHLiteral(), lldb_private::EmulateInstructionARM::EmulateVLDR(), and lldb_private::FormatterBytecode::FormatImpl().
arch_helper()
llvm::StringRef lldb_private::arch_helper ()
Definition at line 291 of file CommandOptionArgumentTable.cpp.
References lldb_private::StreamString::Empty(), lldb_private::StreamString::GetString(), lldb_private::StringList::Join(), lldb_private::ArchSpec::ListSupportedArchNames(), and lldb_private::Stream::Printf().
ARMCondCodeToString()
const char * lldb_private::ARMCondCodeToString (uint32_t CC) inline static
Definition at line 71 of file ARMDefines.h.
References COND_AL, COND_EQ, COND_GE, COND_GT, COND_HI, COND_HS, COND_LE, COND_LO, COND_LS, COND_LT, COND_MI, COND_NE, COND_PL, COND_VC, and COND_VS.
ARMConditionPassed()
bool lldb_private::ARMConditionPassed (const uint32_t condition, const uint32_t cpsr) inline static
Definition at line 107 of file ARMDefines.h.
References COND_AL, COND_CC, COND_CS, COND_EQ, COND_GE, COND_GT, COND_HI, COND_LE, COND_LS, COND_LT, COND_MI, COND_NE, COND_PL, COND_UNCOND, COND_VC, and COND_VS.
Referenced by lldb_private::ArchitectureArm::OverrideStopInfo().
ARMExpandImm()
uint32_t lldb_private::ARMExpandImm (uint32_t opcode) inline static
Definition at line 295 of file ARMUtils.h.
References ARMExpandImm_C().
Referenced by lldb_private::EmulateInstructionARM::EmulateADCImm(), lldb_private::EmulateInstructionARM::EmulateADDImmARM(), lldb_private::EmulateInstructionARM::EmulateADDRdSPImm(), lldb_private::EmulateInstructionARM::EmulateADR(), lldb_private::EmulateInstructionARM::EmulateCMNImm(), lldb_private::EmulateInstructionARM::EmulateCMPImm(), lldb_private::EmulateInstructionARM::EmulateRSBImm(), lldb_private::EmulateInstructionARM::EmulateRSCImm(), lldb_private::EmulateInstructionARM::EmulateSBCImm(), lldb_private::EmulateInstructionARM::EmulateSUBImmARM(), lldb_private::EmulateInstructionARM::EmulateSUBIPSPImm(), lldb_private::EmulateInstructionARM::EmulateSUBR7IPImm(), lldb_private::EmulateInstructionARM::EmulateSUBSPcLrEtc(), and lldb_private::EmulateInstructionARM::EmulateSUBSPImm().
ARMExpandImm_C()
uint32_t lldb_private::ARMExpandImm_C (uint32_t opcode, uint32_t carry_in, uint32_t & carry_out) inline static
Definition at line 280 of file ARMUtils.h.
References Bit32(), bits(), and ror().
Referenced by ARMExpandImm(), lldb_private::EmulateInstructionARM::EmulateANDImm(), lldb_private::EmulateInstructionARM::EmulateBICImm(), lldb_private::EmulateInstructionARM::EmulateEORImm(), lldb_private::EmulateInstructionARM::EmulateMOVRdImm(), lldb_private::EmulateInstructionARM::EmulateMVNImm(), lldb_private::EmulateInstructionARM::EmulateORRImm(), lldb_private::EmulateInstructionARM::EmulateTEQImm(), and lldb_private::EmulateInstructionARM::EmulateTSTImm().
ASR()
uint32_t lldb_private::ASR (const uint32_t value, const uint32_t amount, bool * success) inline static
Definition at line 157 of file ARMUtils.h.
References ASR_C().
ASR_C()
uint32_t lldb_private::ASR_C (const uint32_t value, const uint32_t amount, uint32_t & carry_out, bool * success) inline static
Definition at line 139 of file ARMUtils.h.
References Bit32(), BitIsSet(), and UnsignedBits().
Referenced by ASR(), and Shift_C().
AtomicADD()
template<typename I, typename T> std::enable_if_t< is_amo_add< I >, bool > lldb_private::AtomicADD (EmulateInstructionRISCV & emulator, I inst, int align, uint64_t(* extend)(T)) static
Definition at line 350 of file EmulateInstructionRISCV.cpp.
References AtomicAddr(), lldb_private::EmulateInstructionRISCV::ReadMem(), and zipOpt().
Referenced by lldb_private::Executor::operator()(), and lldb_private::Executor::operator()().
AtomicAddr()
template<typename I> std::enable_if_t< is_amo_add< I >||is_amo_bit_op< I >||is_amo_swap< I >||is_amo_cmp< I >, std::optional< uint64_t > > lldb_private::AtomicAddr (EmulateInstructionRISCV & emulator, I inst, unsigned int align) static
Definition at line 321 of file EmulateInstructionRISCV.cpp.
Referenced by AtomicADD(), AtomicBitOperate(), AtomicCmp(), and AtomicSwap().
AtomicBitOperate()
template<typename I, typename T> std::enable_if_t< is_amo_bit_op< I >, bool > lldb_private::AtomicBitOperate (EmulateInstructionRISCV & emulator, I inst, int align, uint64_t(* extend)(T), T(* operate)(T, T)) static
Definition at line 367 of file EmulateInstructionRISCV.cpp.
References AtomicAddr(), lldb_private::EmulateInstructionRISCV::ReadMem(), and zipOpt().
Referenced by lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), and lldb_private::Executor::operator()().
AtomicCmp()
template<typename I, typename T> std::enable_if_t< is_amo_cmp< I >, bool > lldb_private::AtomicCmp (EmulateInstructionRISCV & emulator, I inst, int align, uint64_t(* extend)(T), T(* cmp)(T, T)) static
Definition at line 384 of file EmulateInstructionRISCV.cpp.
References AtomicAddr(), lldb_private::EmulateInstructionRISCV::ReadMem(), and zipOpt().
Referenced by lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), and lldb_private::Executor::operator()().
AtomicSequence()
bool lldb_private::AtomicSequence (EmulateInstructionRISCV & emulator)
Definition at line 399 of file EmulateInstructionRISCV.cpp.
References BNE, pc, lldb_private::EmulateInstructionRISCV::ReadInstructionAt(), lldb_private::EmulateInstruction::ReadPC(), SextW(), and lldb_private::EmulateInstruction::WritePC().
Referenced by lldb_private::Executor::operator()(), and lldb_private::Executor::operator()().
AtomicSwap()
template<typename I, typename T> std::enable_if_t< is_amo_swap< I >, bool > lldb_private::AtomicSwap (EmulateInstructionRISCV & emulator, I inst, int align, uint64_t(* extend)(T)) static
Definition at line 333 of file EmulateInstructionRISCV.cpp.
References AtomicAddr(), lldb_private::EmulateInstructionRISCV::ReadMem(), and zipOpt().
Referenced by lldb_private::Executor::operator()(), and lldb_private::Executor::operator()().
BadReg()
bool lldb_private::BadReg (uint32_t n) inline static
Definition at line 373 of file ARMUtils.h.
Referenced by lldb_private::EmulateInstructionARM::EmulateADCImm(), lldb_private::EmulateInstructionARM::EmulateADCReg(), lldb_private::EmulateInstructionARM::EmulateADDImmThumb(), lldb_private::EmulateInstructionARM::EmulateADR(), lldb_private::EmulateInstructionARM::EmulateANDImm(), lldb_private::EmulateInstructionARM::EmulateANDReg(), lldb_private::EmulateInstructionARM::EmulateBICImm(), lldb_private::EmulateInstructionARM::EmulateBICReg(), lldb_private::EmulateInstructionARM::EmulateBXJRm(), lldb_private::EmulateInstructionARM::EmulateCMNReg(), lldb_private::EmulateInstructionARM::EmulateCMPReg(), lldb_private::EmulateInstructionARM::EmulateEORImm(), lldb_private::EmulateInstructionARM::EmulateEORReg(), lldb_private::EmulateInstructionARM::EmulateLDRBImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRBRegister(), lldb_private::EmulateInstructionARM::EmulateLDRDImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRHImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRHRegister(), lldb_private::EmulateInstructionARM::EmulateLDRRegister(), lldb_private::EmulateInstructionARM::EmulateLDRSBRegister(), lldb_private::EmulateInstructionARM::EmulateLDRSHImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRSHRegister(), lldb_private::EmulateInstructionARM::EmulateMOVRdImm(), lldb_private::EmulateInstructionARM::EmulateMOVRdRm(), lldb_private::EmulateInstructionARM::EmulateMUL(), lldb_private::EmulateInstructionARM::EmulateMVNReg(), lldb_private::EmulateInstructionARM::EmulateORRImm(), lldb_private::EmulateInstructionARM::EmulateORRReg(), lldb_private::EmulateInstructionARM::EmulatePUSH(), lldb_private::EmulateInstructionARM::EmulateRSBImm(), lldb_private::EmulateInstructionARM::EmulateRSBReg(), lldb_private::EmulateInstructionARM::EmulateSBCImm(), lldb_private::EmulateInstructionARM::EmulateSBCReg(), lldb_private::EmulateInstructionARM::EmulateShiftImm(), lldb_private::EmulateInstructionARM::EmulateShiftReg(), lldb_private::EmulateInstructionARM::EmulateSTRBThumb(), lldb_private::EmulateInstructionARM::EmulateSTRDImm(), lldb_private::EmulateInstructionARM::EmulateSTREX(), lldb_private::EmulateInstructionARM::EmulateSTRHRegister(), lldb_private::EmulateInstructionARM::EmulateSTRRegister(), lldb_private::EmulateInstructionARM::EmulateSUBImmThumb(), lldb_private::EmulateInstructionARM::EmulateSUBReg(), lldb_private::EmulateInstructionARM::EmulateSUBSPReg(), lldb_private::EmulateInstructionARM::EmulateSXTB(), lldb_private::EmulateInstructionARM::EmulateSXTH(), lldb_private::EmulateInstructionARM::EmulateTB(), lldb_private::EmulateInstructionARM::EmulateTEQImm(), lldb_private::EmulateInstructionARM::EmulateTEQReg(), lldb_private::EmulateInstructionARM::EmulateTSTImm(), lldb_private::EmulateInstructionARM::EmulateTSTReg(), lldb_private::EmulateInstructionARM::EmulateUXTB(), and lldb_private::EmulateInstructionARM::EmulateUXTH().
BasicSuperBlockMerge()
HTRBlockLayerUP lldb_private::BasicSuperBlockMerge (IHTRLayer & layer)
The HTR passes are defined below:
Creates a new layer by merging the "basic super blocks" in the current layer
A "basic super block" is the longest sequence of blocks that always occur in the same order. (The concept is akin to “Basic Block" in compiler theory, but refers to dynamic occurrences rather than CFG nodes)
Procedure to find all basic super blocks:
For each block, compute the number of distinct predecessor and successor blocks. Predecessor - the block that occurs directly before (to the left of) the current block Successor - the block that occurs directly after (to the right of) the current block
A block with more than one distinct successor is always the start of a super block, the super block will continue until the next block with more than one distinct predecessor or successor.
The implementation makes use of two terms - 'heads' and 'tails' known as the 'endpoints' of a basic super block: A 'head' is defined to be a block in the trace that doesn't have a unique predecessor A 'tail' is defined to be a block in the trace that doesn't have a unique successor
A basic super block is defined to be a sequence of blocks between two endpoints
A head represents the start of the next group, so the current group ends at the block preceding the head and the next group begins with this head block
A tail represents the end of the current group, so the current group ends with the tail block and the next group begins with the following block.
See lldb/docs/htr.rst for comprehensive HTR documentation
Parameters
[in] layer The layer to execute the pass on.
Returns
A new layer instance representing the merge of blocks in the previous layer
Definition at line 250 of file TraceHTR.cpp.
References lldb_private::HTRBlockMetadata::GetFirstInstructionLoadAddress(), lldb_private::IHTRLayer::GetLayerId(), lldb_private::IHTRLayer::GetMetadataByIndex(), lldb_private::IHTRLayer::GetNumUnits(), and lldb_private::IHTRLayer::MergeUnits().
Referenced by lldb_private::TraceHTR::ExecutePasses().
bit()
uint32_t lldb_private::bit (const uint32_t val, const uint32_t msbit) inline static
Definition at line 270 of file ARMUtils.h.
References bits().
Referenced by Bit32(), Bit64(), BitIsClear(), BitIsSet(), lldb_private::RegisterValue::ClearBit(), lldb_private::Scalar::ClearBit(), lldb_private::EmulateInstructionARM::EmulateMUL(), lldb_private::Broadcaster::BroadcasterImpl::GetEventNames(), lldb_private::Target::GetScratchTypeSystems(), lldb_private::Flags::IsClear(), MaskUpToBit(), lldb_private::RegisterValue::SetBit(), lldb_private::Scalar::SetBit(), SetBit32(), lldb_private::OptionValueLanguage::SetValueFromString(), lldb_private::Flags::Test(), and lldb_private::CommandCompletions::TypeLanguages().
Bit32()
uint32_t lldb_private::Bit32 (const uint32_t bits, const uint32_t bit) inline static
Definition at line 36 of file InstructionUtils.h.
References bit(), and bits().
Referenced by ARMExpandImm_C(), ASR_C(), lldb_private::EmulateInstructionARM::CPSRWriteByInstr(), lldb_private::EmulateInstructionARM::EmulateADDImmThumb(), lldb_private::EmulateInstructionARM::EmulateADDReg(), lldb_private::EmulateInstructionARM::EmulateADDSPImm(), EmulateInstructionARM64::EmulateADDSUBImm(), EmulateInstructionARM64::EmulateB(), lldb_private::EmulateInstructionARM::EmulateB(), lldb_private::EmulateInstructionARM::EmulateBLXImmediate(), lldb_private::EmulateInstructionARM::EmulateCB(), EmulateInstructionARM64::EmulateCBZ(), lldb_private::EmulateInstructionARM::EmulateCMPReg(), EmulateInstructionARM64::EmulateLDPSTP(), lldb_private::EmulateInstructionARM::EmulateLDRRegister(), EmulateInstructionARM64::EmulateLDRSTRImm(), lldb_private::EmulateInstructionARM::EmulateMOVRdImm(), lldb_private::EmulateInstructionARM::EmulateMOVRdRm(), lldb_private::EmulateInstructionARM::EmulateMUL(), lldb_private::EmulateInstructionARM::EmulatePOP(), lldb_private::EmulateInstructionARM::EmulatePUSH(), lldb_private::EmulateInstructionARM::EmulateRFE(), EmulateInstructionARM64::EmulateTBZ(), lldb_private::EmulateInstructionARM::EmulateVLD1Multiple(), lldb_private::EmulateInstructionARM::EmulateVLD1Single(), lldb_private::EmulateInstructionARM::EmulateVLD1SingleAll(), lldb_private::EmulateInstructionARM::EmulateVLDM(), lldb_private::EmulateInstructionARM::EmulateVLDR(), lldb_private::EmulateInstructionARM::EmulateVPOP(), lldb_private::EmulateInstructionARM::EmulateVPUSH(), lldb_private::EmulateInstructionARM::EmulateVST1Multiple(), lldb_private::EmulateInstructionARM::EmulateVST1Single(), lldb_private::EmulateInstructionARM::EmulateVSTM(), lldb_private::EmulateInstructionARM::EmulateVSTR(), LSL_C(), LSR_C(), lldb_private::ArchitectureArm::OverrideStopInfo(), ROR_C(), RRX_C(), ThumbExpandImm_C(), and lldb_private::EmulateInstructionARM::WriteFlags().
Bit64()
uint64_t lldb_private::Bit64 (const uint64_t bits, const uint32_t bit) inline static
Definition at line 40 of file InstructionUtils.h.
References bit(), and bits().
Referenced by EmulateInstructionARM64::AddWithCarry().
BitCount()
uint32_t lldb_private::BitCount (uint64_t x) inline static
Definition at line 80 of file InstructionUtils.h.
Referenced by lldb_private::EmulateInstructionARM::EmulateLDM(), lldb_private::EmulateInstructionARM::EmulateLDMDA(), lldb_private::EmulateInstructionARM::EmulateLDMDB(), lldb_private::EmulateInstructionARM::EmulateLDMIB(), lldb_private::EmulateInstructionARM::EmulatePOP(), lldb_private::EmulateInstructionARM::EmulatePUSH(), lldb_private::EmulateInstructionARM::EmulateSTM(), lldb_private::EmulateInstructionARM::EmulateSTMDA(), lldb_private::EmulateInstructionARM::EmulateSTMDB(), and lldb_private::EmulateInstructionARM::EmulateSTMIB().
BitIsClear()
bool lldb_private::BitIsClear (const uint64_t value, const uint64_t bit) inline static
Definition at line 93 of file InstructionUtils.h.
References bit().
Referenced by lldb_private::EmulateInstructionARM::BXWritePC(), lldb_private::EmulateInstructionARM::EmulateLDM(), lldb_private::EmulateInstructionARM::EmulateLDMDA(), lldb_private::EmulateInstructionARM::EmulateLDMDB(), lldb_private::EmulateInstructionARM::EmulateLDMIB(), lldb_private::EmulateInstructionARM::EmulateLDRBImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRBRegister(), lldb_private::EmulateInstructionARM::EmulateLDRDImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRDRegister(), lldb_private::EmulateInstructionARM::EmulateLDRHImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRHLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRHRegister(), lldb_private::EmulateInstructionARM::EmulateLDRImmediateARM(), lldb_private::EmulateInstructionARM::EmulateLDRRegister(), lldb_private::EmulateInstructionARM::EmulateLDRRtRnImm(), lldb_private::EmulateInstructionARM::EmulateLDRSBImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRSBRegister(), lldb_private::EmulateInstructionARM::EmulateLDRSHImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRSHLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRSHRegister(), lldb_private::EmulateInstructionARM::EmulateSTRBImmARM(), lldb_private::EmulateInstructionARM::EmulateSTRDImm(), lldb_private::EmulateInstructionARM::EmulateSTRDReg(), lldb_private::EmulateInstructionARM::EmulateSTRHRegister(), lldb_private::EmulateInstructionARM::EmulateSTRImmARM(), lldb_private::EmulateInstructionARM::EmulateSTRRegister(), lldb_private::EmulateInstructionARM::EmulateSTRRtSP(), lldb_private::EmulateInstructionARM::EmulateSTRThumb(), lldb_private::EmulateInstructionARM::EmulateSUBReg(), lldb_private::EmulateInstructionARM::EmulateVLD1Single(), lldb_private::EmulateInstructionARM::EmulateVLD1SingleAll(), and lldb_private::EmulateInstructionARM::EmulateVST1Single().
BitIsSet()
bool lldb_private::BitIsSet (const uint64_t value, const uint64_t bit) inline static
Definition at line 89 of file InstructionUtils.h.
References bit().
Referenced by ASR_C(), lldb_private::EmulateInstructionARM::BXWritePC(), lldb_private::EmulateInstructionARM::CPSRWriteByInstr(), lldb_private::EmulateInstructionARM::EmulateADCImm(), lldb_private::EmulateInstructionARM::EmulateADCReg(), lldb_private::EmulateInstructionARM::EmulateADDImmARM(), lldb_private::EmulateInstructionARM::EmulateADDImmThumb(), lldb_private::EmulateInstructionARM::EmulateADDReg(), lldb_private::EmulateInstructionARM::EmulateADDRegShift(), lldb_private::EmulateInstructionARM::EmulateANDImm(), lldb_private::EmulateInstructionARM::EmulateANDReg(), lldb_private::EmulateInstructionARM::EmulateBICImm(), lldb_private::EmulateInstructionARM::EmulateBICReg(), lldb_private::EmulateInstructionARM::EmulateCB(), lldb_private::EmulateInstructionARM::EmulateEORImm(), lldb_private::EmulateInstructionARM::EmulateEORReg(), lldb_private::EmulateInstructionARM::EmulateLDM(), lldb_private::EmulateInstructionARM::EmulateLDMDA(), lldb_private::EmulateInstructionARM::EmulateLDMDB(), lldb_private::EmulateInstructionARM::EmulateLDMIB(), lldb_private::EmulateInstructionARM::EmulateLDRBImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRBLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRBRegister(), lldb_private::EmulateInstructionARM::EmulateLDRDImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRDRegister(), lldb_private::EmulateInstructionARM::EmulateLDRHImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRHLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRHRegister(), lldb_private::EmulateInstructionARM::EmulateLDRImmediateARM(), lldb_private::EmulateInstructionARM::EmulateLDRRegister(), lldb_private::EmulateInstructionARM::EmulateLDRRtPCRelative(), lldb_private::EmulateInstructionARM::EmulateLDRRtRnImm(), lldb_private::EmulateInstructionARM::EmulateLDRSBImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRSBLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRSBRegister(), lldb_private::EmulateInstructionARM::EmulateLDRSHImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRSHLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRSHRegister(), lldb_private::EmulateInstructionARM::EmulateMOVRdImm(), lldb_private::EmulateInstructionARM::EmulateMOVRdRm(), lldb_private::EmulateInstructionARM::EmulateMUL(), lldb_private::EmulateInstructionARM::EmulateMVNImm(), lldb_private::EmulateInstructionARM::EmulateMVNReg(), lldb_private::EmulateInstructionARM::EmulateORRImm(), lldb_private::EmulateInstructionARM::EmulateORRReg(), lldb_private::EmulateInstructionARM::EmulatePOP(), lldb_private::EmulateInstructionARM::EmulatePUSH(), lldb_private::EmulateInstructionARM::EmulateRFE(), lldb_private::EmulateInstructionARM::EmulateRSBImm(), lldb_private::EmulateInstructionARM::EmulateRSBReg(), lldb_private::EmulateInstructionARM::EmulateRSCImm(), lldb_private::EmulateInstructionARM::EmulateRSCReg(), lldb_private::EmulateInstructionARM::EmulateSBCImm(), lldb_private::EmulateInstructionARM::EmulateSBCReg(), lldb_private::EmulateInstructionARM::EmulateShiftImm(), lldb_private::EmulateInstructionARM::EmulateShiftReg(), lldb_private::EmulateInstructionARM::EmulateSTM(), lldb_private::EmulateInstructionARM::EmulateSTMDA(), lldb_private::EmulateInstructionARM::EmulateSTMDB(), lldb_private::EmulateInstructionARM::EmulateSTMIB(), lldb_private::EmulateInstructionARM::EmulateSTRBImmARM(), lldb_private::EmulateInstructionARM::EmulateSTRBThumb(), lldb_private::EmulateInstructionARM::EmulateSTRDImm(), lldb_private::EmulateInstructionARM::EmulateSTRDReg(), lldb_private::EmulateInstructionARM::EmulateSTRHRegister(), lldb_private::EmulateInstructionARM::EmulateSTRImmARM(), lldb_private::EmulateInstructionARM::EmulateSTRRegister(), lldb_private::EmulateInstructionARM::EmulateSTRRtSP(), lldb_private::EmulateInstructionARM::EmulateSTRThumb(), lldb_private::EmulateInstructionARM::EmulateSUBImmARM(), lldb_private::EmulateInstructionARM::EmulateSUBImmThumb(), lldb_private::EmulateInstructionARM::EmulateSUBReg(), lldb_private::EmulateInstructionARM::EmulateSUBSPImm(), lldb_private::EmulateInstructionARM::EmulateSUBSPReg(), lldb_private::EmulateInstructionARM::EmulateTB(), lldb_private::EmulateInstructionARM::EmulateVLD1Multiple(), lldb_private::EmulateInstructionARM::EmulateVLD1SingleAll(), lldb_private::EmulateInstructionARM::EmulateVLDM(), lldb_private::EmulateInstructionARM::EmulateVLDR(), lldb_private::EmulateInstructionARM::EmulateVST1Multiple(), lldb_private::EmulateInstructionARM::EmulateVSTM(), lldb_private::EmulateInstructionARM::EmulateVSTR(), and SignedBits().
bits()
uint32_t lldb_private::bits (const uint32_t val, const uint32_t msbit, const uint32_t lsbit) inline static
Definition at line 265 of file ARMUtils.h.
References Bits32().
Referenced by ARMExpandImm_C(), bit(), Bit32(), Bit64(), Bits32(), Bits64(), EmulateInstructionARM64::BranchTo(), CommandObjectProcessStatus::DoExecute(), DumpDataExtractor(), EmulateInstructionARM64::EmulateBcond(), EmulateInstructionARM64::EmulateCBZ(), lldb_private::EmulateInstructionARM::EmulateLDM(), lldb_private::EmulateInstructionARM::EmulateLDMDA(), lldb_private::EmulateInstructionARM::EmulateLDMDB(), lldb_private::EmulateInstructionARM::EmulateLDMIB(), lldb_private::EmulateInstructionARM::EmulateLDRHImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRHLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRHRegister(), lldb_private::EmulateInstructionARM::EmulateLDRRegister(), lldb_private::EmulateInstructionARM::EmulateLDRRtPCRelative(), lldb_private::EmulateInstructionARM::EmulateLDRRtRnImm(), lldb_private::EmulateInstructionARM::EmulateLDRSHImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRSHLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRSHRegister(), lldb_private::EmulateInstructionARM::EmulatePOP(), lldb_private::EmulateInstructionARM::EmulatePUSH(), lldb_private::EmulateInstructionARM::EmulateSTM(), lldb_private::EmulateInstructionARM::EmulateSTMDA(), lldb_private::EmulateInstructionARM::EmulateSTMDB(), lldb_private::EmulateInstructionARM::EmulateSTMIB(), lldb_private::EmulateInstructionARM::EmulateSTRHRegister(), lldb_private::EmulateInstructionARM::EmulateSTRRegister(), lldb_private::EmulateInstructionARM::EmulateSTRThumb(), EmulateInstructionARM64::EmulateTBZ(), lldb_private::Executor::FMV_f2i(), GetBytes(), lldb_private::RegisterFlags::Field::GetMaxValue(), lldb_private::Scalar::IntegralPromote(), lldb_private::SymbolFileCTF::ParseType(), lldb_private::Rs::ReadAPFloat(), Rotl32(), Rotr32(), ObjectFileMachO::SaveCore(), SetBit32(), SetBits32(), lldb_private::ProcessProperties::SetHighmemVirtualAddressableBits(), lldb_private::ProcessProperties::SetVirtualAddressableBits(), ThumbExpandImm_C(), ThumbImm12(), ThumbImm7Scaled(), ThumbImm8Scaled(), ToAPInt(), lldb_private::Scalar::TruncOrExtendTo(), and lldb_private::ProcessProperties::~ProcessProperties().
Bits32()
uint32_t lldb_private::Bits32 (const uint32_t bits, const uint32_t msbit, const uint32_t lsbit) inline static
Definition at line 29 of file InstructionUtils.h.
References bits().
Referenced by bits(), lldb_private::EmulateInstructionARM::CPSRWriteByInstr(), lldb_private::EmulateInstructionARM::CurrentCond(), lldb_private::EmulateInstructionARM::CurrentModeIsPrivileged(), DecodeImmShiftARM(), DecodeImmShiftThumb(), lldb_private::EmulateInstructionARM::EmulateADCImm(), lldb_private::EmulateInstructionARM::EmulateADCReg(), lldb_private::EmulateInstructionPPC64::EmulateADDI(), lldb_private::EmulateInstructionARM::EmulateADDImmARM(), lldb_private::EmulateInstructionARM::EmulateADDImmThumb(), lldb_private::EmulateInstructionARM::EmulateADDRdSPImm(), lldb_private::EmulateInstructionARM::EmulateADDReg(), lldb_private::EmulateInstructionARM::EmulateADDRegShift(), lldb_private::EmulateInstructionARM::EmulateADDSPImm(), lldb_private::EmulateInstructionARM::EmulateADDSPRm(), EmulateInstructionARM64::EmulateADDSUBImm(), lldb_private::EmulateInstructionARM::EmulateADR(), lldb_private::EmulateInstructionARM::EmulateANDImm(), lldb_private::EmulateInstructionARM::EmulateANDReg(), EmulateInstructionARM64::EmulateB(), lldb_private::EmulateInstructionARM::EmulateB(), lldb_private::EmulateInstructionLoongArch::EmulateB64(), lldb_private::EmulateInstructionLoongArch::EmulateBCEQZ64(), lldb_private::EmulateInstructionLoongArch::EmulateBCNEZ64(), EmulateInstructionARM64::EmulateBcond(), lldb_private::EmulateInstructionLoongArch::EmulateBEQ64(), lldb_private::EmulateInstructionLoongArch::EmulateBEQZ64(), lldb_private::EmulateInstructionLoongArch::EmulateBGE64(), lldb_private::EmulateInstructionLoongArch::EmulateBGEU64(), lldb_private::EmulateInstructionARM::EmulateBICImm(), lldb_private::EmulateInstructionARM::EmulateBICReg(), lldb_private::EmulateInstructionLoongArch::EmulateBL64(), lldb_private::EmulateInstructionLoongArch::EmulateBLT64(), lldb_private::EmulateInstructionLoongArch::EmulateBLTU64(), lldb_private::EmulateInstructionARM::EmulateBLXImmediate(), lldb_private::EmulateInstructionARM::EmulateBLXRm(), lldb_private::EmulateInstructionLoongArch::EmulateBNE64(), lldb_private::EmulateInstructionLoongArch::EmulateBNEZ64(), lldb_private::EmulateInstructionARM::EmulateBXJRm(), lldb_private::EmulateInstructionARM::EmulateBXRm(), lldb_private::EmulateInstructionARM::EmulateCB(), EmulateInstructionARM64::EmulateCBZ(), lldb_private::EmulateInstructionARM::EmulateCMNImm(), lldb_private::EmulateInstructionARM::EmulateCMNReg(), lldb_private::EmulateInstructionARM::EmulateCMPImm(), lldb_private::EmulateInstructionARM::EmulateCMPReg(), lldb_private::EmulateInstructionARM::EmulateEORImm(), lldb_private::EmulateInstructionARM::EmulateEORReg(), lldb_private::EmulateInstructionARM::EmulateIT(), lldb_private::EmulateInstructionLoongArch::EmulateJIRL64(), lldb_private::EmulateInstructionPPC64::EmulateLD(), lldb_private::EmulateInstructionARM::EmulateLDM(), lldb_private::EmulateInstructionARM::EmulateLDMDA(), lldb_private::EmulateInstructionARM::EmulateLDMDB(), lldb_private::EmulateInstructionARM::EmulateLDMIB(), EmulateInstructionARM64::EmulateLDPSTP(), lldb_private::EmulateInstructionARM::EmulateLDRBImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRBLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRBRegister(), lldb_private::EmulateInstructionARM::EmulateLDRDImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRDRegister(), lldb_private::EmulateInstructionARM::EmulateLDRHImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRHLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRHRegister(), lldb_private::EmulateInstructionARM::EmulateLDRImmediateARM(), lldb_private::EmulateInstructionARM::EmulateLDRRegister(), lldb_private::EmulateInstructionARM::EmulateLDRRtPCRelative(), lldb_private::EmulateInstructionARM::EmulateLDRRtRnImm(), lldb_private::EmulateInstructionARM::EmulateLDRSBImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRSBLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRSBRegister(), lldb_private::EmulateInstructionARM::EmulateLDRSHImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRSHLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRSHRegister(), EmulateInstructionARM64::EmulateLDRSTRImm(), lldb_private::EmulateInstructionPPC64::EmulateMFSPR(), lldb_private::EmulateInstructionARM::EmulateMOVRdImm(), lldb_private::EmulateInstructionARM::EmulateMOVRdRm(), lldb_private::EmulateInstructionARM::EmulateMUL(), lldb_private::EmulateInstructionARM::EmulateMVNImm(), lldb_private::EmulateInstructionARM::EmulateMVNReg(), lldb_private::EmulateInstructionPPC64::EmulateOR(), lldb_private::EmulateInstructionARM::EmulateORRImm(), lldb_private::EmulateInstructionARM::EmulateORRReg(), lldb_private::EmulateInstructionARM::EmulatePOP(), lldb_private::EmulateInstructionARM::EmulatePUSH(), lldb_private::EmulateInstructionARM::EmulateRFE(), lldb_private::EmulateInstructionARM::EmulateRSBImm(), lldb_private::EmulateInstructionARM::EmulateRSBReg(), lldb_private::EmulateInstructionARM::EmulateRSCImm(), lldb_private::EmulateInstructionARM::EmulateRSCReg(), lldb_private::EmulateInstructionARM::EmulateSBCImm(), lldb_private::EmulateInstructionARM::EmulateSBCReg(), lldb_private::EmulateInstructionARM::EmulateShiftImm(), lldb_private::EmulateInstructionARM::EmulateShiftReg(), lldb_private::EmulateInstructionPPC64::EmulateSTD(), lldb_private::EmulateInstructionARM::EmulateSTM(), lldb_private::EmulateInstructionARM::EmulateSTMDA(), lldb_private::EmulateInstructionARM::EmulateSTMDB(), lldb_private::EmulateInstructionARM::EmulateSTMIB(), lldb_private::EmulateInstructionARM::EmulateSTRBImmARM(), lldb_private::EmulateInstructionARM::EmulateSTRBThumb(), lldb_private::EmulateInstructionARM::EmulateSTRDImm(), lldb_private::EmulateInstructionARM::EmulateSTRDReg(), lldb_private::EmulateInstructionARM::EmulateSTREX(), lldb_private::EmulateInstructionARM::EmulateSTRHRegister(), lldb_private::EmulateInstructionARM::EmulateSTRImmARM(), lldb_private::EmulateInstructionARM::EmulateSTRRegister(), lldb_private::EmulateInstructionARM::EmulateSTRRtSP(), lldb_private::EmulateInstructionARM::EmulateSTRThumb(), lldb_private::EmulateInstructionARM::EmulateSUBImmARM(), lldb_private::EmulateInstructionARM::EmulateSUBImmThumb(), lldb_private::EmulateInstructionARM::EmulateSUBReg(), lldb_private::EmulateInstructionARM::EmulateSUBSPcLrEtc(), lldb_private::EmulateInstructionARM::EmulateSUBSPImm(), lldb_private::EmulateInstructionARM::EmulateSUBSPReg(), lldb_private::EmulateInstructionARM::EmulateSVC(), lldb_private::EmulateInstructionARM::EmulateSXTB(), lldb_private::EmulateInstructionARM::EmulateSXTH(), lldb_private::EmulateInstructionARM::EmulateTB(), EmulateInstructionARM64::EmulateTBZ(), lldb_private::EmulateInstructionARM::EmulateTEQImm(), lldb_private::EmulateInstructionARM::EmulateTEQReg(), lldb_private::EmulateInstructionARM::EmulateTSTImm(), lldb_private::EmulateInstructionARM::EmulateTSTReg(), lldb_private::EmulateInstructionARM::EmulateUXTB(), lldb_private::EmulateInstructionARM::EmulateUXTH(), lldb_private::EmulateInstructionARM::EmulateVLD1Multiple(), lldb_private::EmulateInstructionARM::EmulateVLD1Single(), lldb_private::EmulateInstructionARM::EmulateVLD1SingleAll(), lldb_private::EmulateInstructionARM::EmulateVLDM(), lldb_private::EmulateInstructionARM::EmulateVLDR(), lldb_private::EmulateInstructionARM::EmulateVPOP(), lldb_private::EmulateInstructionARM::EmulateVPUSH(), lldb_private::EmulateInstructionARM::EmulateVST1Multiple(), lldb_private::EmulateInstructionARM::EmulateVST1Single(), lldb_private::EmulateInstructionARM::EmulateVSTM(), lldb_private::EmulateInstructionARM::EmulateVSTR(), lldb_private::ITSession::GetCond(), lldb_private::ITSession::InitIT(), lldb_private::ITSession::ITAdvance(), RegisterContextDarwin_arm::NumSupportedHardwareBreakpoints(), RegisterContextDarwin_arm::NumSupportedHardwareWatchpoints(), lldb_private::ArchitectureArm::OverrideStopInfo(), lldb_private::EmulateInstructionARM::ReadInstruction(), and RRX_C().
Bits64()
uint64_t lldb_private::Bits64 (const uint64_t bits, const uint32_t msbit, const uint32_t lsbit) inline static
Definition at line 21 of file InstructionUtils.h.
References bits().
Referenced by EmulateInstructionARM64::AddWithCarry(), lldb_private::EmulateInstructionARM::EmulateVLD1Single(), lldb_private::EmulateInstructionARM::EmulateVLD1SingleAll(), lldb_private::EmulateInstructionARM::EmulateVST1Multiple(), lldb_private::EmulateInstructionARM::EmulateVST1Single(), lldb_private::EmulateInstructionARM::EmulateVSTM(), and lldb_private::EmulateInstructionARM::EmulateVSTR().
BOffset()
uint16_t lldb_private::BOffset (uint32_t inst) constexpr
Definition at line 138 of file RISCVCInstructions.h.
Referenced by DecodeC_BEQZ(), and DecodeC_BNEZ().
BreakpointIDHelpTextCallback()
llvm::StringRef lldb_private::BreakpointIDHelpTextCallback ()
Definition at line 36 of file CommandOptionArgumentTable.cpp.
BreakpointIDRangeHelpTextCallback()
llvm::StringRef lldb_private::BreakpointIDRangeHelpTextCallback ()
Definition at line 55 of file CommandOptionArgumentTable.cpp.
BreakpointNameHelpTextCallback()
llvm::StringRef lldb_private::BreakpointNameHelpTextCallback ()
Definition at line 74 of file CommandOptionArgumentTable.cpp.
clone() [1/2]
template<typename T> std::shared_ptr< T > lldb_private::clone (const std::shared_ptr< T > & src)
Definition at line 23 of file Utils.h.
clone() [2/2]
template<typename T> std::unique_ptr< T > lldb_private::clone (const std::unique_ptr< T > & src)
Definition at line 17 of file Utils.h.
Referenced by CloneError(), lldb_private::OptionValue::DeepCopy(), lldb::SBAddress::operator=(), lldb::SBAddressRange::operator=(), lldb::SBAttachInfo::operator=(), lldb::SBCommandReturnObject::operator=(), lldb::SBDeclaration::operator=(), lldb::SBEnvironment::operator=(), lldb::SBExpressionOptions::operator=(), lldb::SBFileSpec::operator=(), lldb::SBFileSpecList::operator=(), lldb::SBFormat::operator=(), lldb::SBFrame::operator=(), lldb::SBLineEntry::operator=(), lldb::SBMemoryRegionInfo::operator=(), lldb::SBModuleSpec::operator=(), lldb::SBProcessInfo::operator=(), lldb::SBProcessInfoList::operator=(), lldb::SBScriptObject::operator=(), lldb::SBStatisticsOptions::operator=(), lldb::SBStringList::operator=(), lldb::SBSymbolContext::operator=(), lldb::SBSymbolContextList::operator=(), lldb::SBThread::operator=(), lldb::SBTypeEnumMember::operator=(), lldb::SBTypeStaticField::operator=(), lldb::SBWatchpointOptions::operator=(), lldb::SBAddress::SBAddress(), lldb::SBAddressRange::SBAddressRange(), lldb::SBAttachInfo::SBAttachInfo(), lldb::SBCommandReturnObject::SBCommandReturnObject(), lldb::SBDeclaration::SBDeclaration(), lldb::SBEnvironment::SBEnvironment(), lldb::SBExpressionOptions::SBExpressionOptions(), lldb::SBFileSpec::SBFileSpec(), lldb::SBFileSpecList::SBFileSpecList(), lldb::SBFormat::SBFormat(), lldb::SBFrame::SBFrame(), lldb::SBLineEntry::SBLineEntry(), lldb::SBMemoryRegionInfo::SBMemoryRegionInfo(), lldb::SBModuleSpec::SBModuleSpec(), lldb::SBProcessInfo::SBProcessInfo(), lldb::SBProcessInfoList::SBProcessInfoList(), lldb::SBScriptObject::SBScriptObject(), lldb::SBStatisticsOptions::SBStatisticsOptions(), lldb::SBStringList::SBStringList(), lldb::SBSymbolContext::SBSymbolContext(), lldb::SBSymbolContextList::SBSymbolContextList(), lldb::SBThread::SBThread(), lldb::SBTypeEnumMember::SBTypeEnumMember(), lldb::SBTypeStaticField::SBTypeStaticField(), lldb::SBTypeSummaryOptions::SBTypeSummaryOptions(), and lldb::SBWatchpointOptions::SBWatchpointOptions().
compare()
APFloat::cmpResult lldb_private::compare (Scalar lhs, Scalar rhs)
Definition at line 872 of file Scalar.cpp.
References lldb_private::Scalar::e_float, lldb_private::Scalar::e_int, lldb_private::Scalar::e_void, lldb_private::Scalar::m_float, lldb_private::Scalar::m_integer, lldb_private::Scalar::m_type, and lldb_private::Scalar::PromoteToMaxType().
Referenced by lldb_private::ProcessModID::MemoryIDEqual(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), lldb_private::RangeDataVector< lldb::addr_t, lldb::addr_t, DWARFExpression, 0, DWARFExpressionCompare >::RangeDataVector(), lldb_private::RangeDataVector< lldb::addr_t, lldb::addr_t, DWARFExpression, 0, DWARFExpressionCompare >::RangeDataVector(), lldb_private::RangeDataVector< lldb::addr_t, lldb::addr_t, DWARFExpression, 0, DWARFExpressionCompare >::Sort(), and lldb_private::ProcessModID::StopIDEqual().
CompareB()
bool lldb_private::CompareB (uint64_t rs1, uint64_t rs2, uint32_t funct3) static
Definition at line 184 of file EmulateInstructionRISCV.cpp.
References BEQ, BGE, BGEU, BLT, BLTU, and BNE.
ComputeClangResourceDirectory()
bool lldb_private::ComputeClangResourceDirectory (FileSpec & lldb_shlib_spec, FileSpec & file_spec, bool verify)
Definition at line 88 of file ClangHost.cpp.
References DefaultComputeClangResourceDirectory(), lldb_private::FileSpec::GetPath(), lldb_private::FileSystem::Instance(), lldb_private::FileSystem::Resolve(), lldb_private::FileSpec::SetDirectory(), and VerifyClangPath().
Referenced by GetClangResourceDir().
CreateOptionParsingError()
llvm::Error lldb_private::CreateOptionParsingError (llvm::StringRef option_arg, const char short_option, llvm::StringRef long_option = {}, llvm::StringRef additional_context = {})
Creates an error that represents the failure to parse an command line option argument.
This creates an error containing all information needed to show the developer what went wrong when parsing their command. It is recommended to use this instead of writing an error by hand.
Parameters
[in] option_arg The argument that was attempted to be parsed.
[in] short_option The short form of the option. For example, if the flag is -f, the short option is "f".
[in] long_option The long form of the option. This field is optional. If the flag is –force, then the long option is "force".
[in] additional_context This is extra context that will get included in the error. This field is optional.
Returns
An llvm::Error that contains a standardized format for what went wrong when parsing and why.
Definition at line 1362 of file Options.cpp.
Referenced by BreakpointAccessOptionGroup::SetOptionValue(), BreakpointNameOptionGroup::SetOptionValue(), BreakpointNamesOptionGroup::SetOptionValue(), CommandObjectBreakpointAddAddress::CommandOptions::SetOptionValue(), CommandObjectBreakpointAddFile::CommandOptions::SetOptionValue(), CommandObjectBreakpointAddName::CommandOptions::SetOptionValue(), CommandObjectBreakpointAddPattern::CommandOptions::SetOptionValue(), CommandObjectBreakpointRead::CommandOptions::SetOptionValue(), CommandObjectBreakpointSet::CommandOptions::SetOptionValue(), and lldb_private::BreakpointOptionGroup::SetOptionValue().
CreateSyntheticImpl()
BytecodeSyntheticChildren::SyntheticBytecodeImplementation lldb_private::CreateSyntheticImpl (llvm::MutableArrayRef< std::unique_ptr< llvm::MemoryBuffer > > methods) static
Definition at line 148 of file FormatterSection.cpp.
References lldb_private::BytecodeSyntheticChildren::SyntheticBytecodeImplementation::get_child_at_index, lldb_private::BytecodeSyntheticChildren::SyntheticBytecodeImplementation::get_child_index, lldb_private::BytecodeSyntheticChildren::SyntheticBytecodeImplementation::init, lldb_private::BytecodeSyntheticChildren::SyntheticBytecodeImplementation::num_children, and lldb_private::BytecodeSyntheticChildren::SyntheticBytecodeImplementation::update.
Referenced by LoadFormattersForModule().
DecodeBImm()
uint32_t lldb_private::DecodeBImm (uint32_t inst) constexpr
Definition at line 87 of file EmulateInstructionRISCV.cpp.
Referenced by DecodeBType().
DecodeBType()
template<typename T> RISCVInst lldb_private::DecodeBType (uint32_t inst) static
Definition at line 462 of file EmulateInstructionRISCV.cpp.
References DecodeBImm(), DecodeFunct3(), DecodeRS1(), and DecodeRS2().
DecodeC_ADD()
RISCVInst lldb_private::DecodeC_ADD (uint32_t inst)
Definition at line 268 of file RISCVCInstructions.h.
References DecodeCR_RD(), and DecodeCR_RS2().
DecodeC_ADDI()
RISCVInst lldb_private::DecodeC_ADDI (uint32_t inst)
Definition at line 194 of file RISCVCInstructions.h.
References DecodeCI_RD().
DecodeC_ADDI4SPN()
RISCVInst lldb_private::DecodeC_ADDI4SPN (uint32_t inst)
Definition at line 214 of file RISCVCInstructions.h.
References DecodeCIW_RD(), and gpr_sp_riscv.
DecodeC_ADDIW()
RISCVInst lldb_private::DecodeC_ADDIW (uint32_t inst)
Definition at line 204 of file RISCVCInstructions.h.
References DecodeCI_RD().
DecodeC_ADDW()
RISCVInst lldb_private::DecodeC_ADDW (uint32_t inst)
Definition at line 298 of file RISCVCInstructions.h.
References DecodeCA_RD(), and DecodeCA_RS2().
DecodeC_AND()
RISCVInst lldb_private::DecodeC_AND (uint32_t inst)
Definition at line 273 of file RISCVCInstructions.h.
References DecodeCA_RD(), and DecodeCA_RS2().
DecodeC_ANDI()
RISCVInst lldb_private::DecodeC_ANDI (uint32_t inst)
Definition at line 252 of file RISCVCInstructions.h.
References DecodeCB_RD().
DecodeC_BEQZ()
RISCVInst lldb_private::DecodeC_BEQZ (uint32_t inst)
Definition at line 154 of file RISCVCInstructions.h.
References BOffset(), and DecodeCB_RS1().
DecodeC_BNEZ()
RISCVInst lldb_private::DecodeC_BNEZ (uint32_t inst)
Definition at line 146 of file RISCVCInstructions.h.
References BOffset(), and DecodeCB_RS1().
DecodeC_FLD()
RISCVInst lldb_private::DecodeC_FLD (uint32_t inst)
Definition at line 344 of file RISCVCInstructions.h.
References DecodeCL_RD(), and DecodeCL_RS1().
DecodeC_FLDSP()
RISCVInst lldb_private::DecodeC_FLDSP (uint32_t inst)
Definition at line 330 of file RISCVCInstructions.h.
References DecodeCI_RD(), and gpr_sp_riscv.
DecodeC_FLW()
RISCVInst lldb_private::DecodeC_FLW (uint32_t inst)
Definition at line 302 of file RISCVCInstructions.h.
References DecodeCL_RD(), and DecodeCL_RS1().
DecodeC_FLWSP()
RISCVInst lldb_private::DecodeC_FLWSP (uint32_t inst)
Definition at line 316 of file RISCVCInstructions.h.
References DecodeCI_RD(), and gpr_sp_riscv.
DecodeC_FSD()
RISCVInst lldb_private::DecodeC_FSD (uint32_t inst)
Definition at line 350 of file RISCVCInstructions.h.
References DecodeCS_RS1(), and DecodeCS_RS2().
DecodeC_FSDSP()
RISCVInst lldb_private::DecodeC_FSDSP (uint32_t inst)
Definition at line 338 of file RISCVCInstructions.h.
References DecodeCSS_RS2(), and gpr_sp_riscv.
DecodeC_FSW()
RISCVInst lldb_private::DecodeC_FSW (uint32_t inst)
Definition at line 309 of file RISCVCInstructions.h.
References DecodeCS_RS1(), and DecodeCS_RS2().
DecodeC_FSWSP()
RISCVInst lldb_private::DecodeC_FSWSP (uint32_t inst)
Definition at line 324 of file RISCVCInstructions.h.
References DecodeCSS_RS2(), and gpr_sp_riscv.
DecodeC_J()
RISCVInst lldb_private::DecodeC_J (uint32_t inst)
Definition at line 110 of file RISCVCInstructions.h.
DecodeC_JALR()
RISCVInst lldb_private::DecodeC_JALR (uint32_t inst)
Definition at line 131 of file RISCVCInstructions.h.
References DecodeCR_RS1().
DecodeC_JR()
RISCVInst lldb_private::DecodeC_JR (uint32_t inst)
Definition at line 124 of file RISCVCInstructions.h.
References DecodeCR_RS1().
DecodeC_LD()
RISCVInst lldb_private::DecodeC_LD (uint32_t inst)
Definition at line 91 of file RISCVCInstructions.h.
References DecodeCL_RD(), and DecodeCL_RS1().
DecodeC_LDSP()
RISCVInst lldb_private::DecodeC_LDSP (uint32_t inst)
Definition at line 62 of file RISCVCInstructions.h.
References DecodeCI_RD(), and gpr_sp_riscv.
DecodeC_LI()
RISCVInst lldb_private::DecodeC_LI (uint32_t inst)
Definition at line 162 of file RISCVCInstructions.h.
References DecodeCI_RD().
DecodeC_LUI_ADDI16SP()
RISCVInst lldb_private::DecodeC_LUI_ADDI16SP (uint32_t inst)
Definition at line 170 of file RISCVCInstructions.h.
References DecodeCI_RD(), and gpr_sp_riscv.
DecodeC_LW()
RISCVInst lldb_private::DecodeC_LW (uint32_t inst)
Definition at line 84 of file RISCVCInstructions.h.
References DecodeCL_RD(), and DecodeCL_RS1().
DecodeC_LWSP()
RISCVInst lldb_private::DecodeC_LWSP (uint32_t inst)
Definition at line 52 of file RISCVCInstructions.h.
References DecodeCI_RD(), and gpr_sp_riscv.
DecodeC_MV()
RISCVInst lldb_private::DecodeC_MV (uint32_t inst)
Definition at line 260 of file RISCVCInstructions.h.
References DecodeCR_RD(), and DecodeCR_RS2().
DecodeC_OR()
RISCVInst lldb_private::DecodeC_OR (uint32_t inst)
Definition at line 278 of file RISCVCInstructions.h.
References DecodeCA_RD(), and DecodeCA_RS2().
DecodeC_SD()
RISCVInst lldb_private::DecodeC_SD (uint32_t inst)
Definition at line 104 of file RISCVCInstructions.h.
References DecodeCS_RS1(), and DecodeCS_RS2().
DecodeC_SDSP()
RISCVInst lldb_private::DecodeC_SDSP (uint32_t inst)
Definition at line 78 of file RISCVCInstructions.h.
References DecodeCSS_RS2(), and gpr_sp_riscv.
DecodeC_SLLI()
RISCVInst lldb_private::DecodeC_SLLI (uint32_t inst)
Definition at line 228 of file RISCVCInstructions.h.
References DecodeCI_RD().
DecodeC_SRAI()
RISCVInst lldb_private::DecodeC_SRAI (uint32_t inst)
Definition at line 244 of file RISCVCInstructions.h.
References DecodeCB_RD().
DecodeC_SRLI()
RISCVInst lldb_private::DecodeC_SRLI (uint32_t inst)
Definition at line 236 of file RISCVCInstructions.h.
References DecodeCB_RD().
DecodeC_SUB()
RISCVInst lldb_private::DecodeC_SUB (uint32_t inst)
Definition at line 288 of file RISCVCInstructions.h.
References DecodeCA_RD(), and DecodeCA_RS2().
DecodeC_SUBW()
RISCVInst lldb_private::DecodeC_SUBW (uint32_t inst)
Definition at line 293 of file RISCVCInstructions.h.
References DecodeCA_RD(), and DecodeCA_RS2().
DecodeC_SW()
RISCVInst lldb_private::DecodeC_SW (uint32_t inst)
Definition at line 97 of file RISCVCInstructions.h.
References DecodeCS_RS1(), and DecodeCS_RS2().
DecodeC_SWSP()
RISCVInst lldb_private::DecodeC_SWSP (uint32_t inst)
Definition at line 72 of file RISCVCInstructions.h.
References DecodeCSS_RS2(), and gpr_sp_riscv.
DecodeC_XOR()
RISCVInst lldb_private::DecodeC_XOR (uint32_t inst)
Definition at line 283 of file RISCVCInstructions.h.
References DecodeCA_RD(), and DecodeCA_RS2().
DecodeCA_RD()
RxC lldb_private::DecodeCA_RD (uint32_t inst) constexpr
Definition at line 40 of file RISCVCInstructions.h.
Referenced by DecodeC_ADDW(), DecodeC_AND(), DecodeC_OR(), DecodeC_SUB(), DecodeC_SUBW(), DecodeC_XOR(), DecodeCA_RS1(), DecodeCB_RD(), DecodeCB_RS1(), DecodeCL_RS1(), and DecodeCS_RS1().
DecodeCA_RS1()
RxC lldb_private::DecodeCA_RS1 (uint32_t inst) constexpr
Definition at line 45 of file RISCVCInstructions.h.
References DecodeCA_RD().
DecodeCA_RS2()
RxC lldb_private::DecodeCA_RS2 (uint32_t inst) constexpr
Definition at line 50 of file RISCVCInstructions.h.
References DecodeCIW_RD().
Referenced by DecodeC_ADDW(), DecodeC_AND(), DecodeC_OR(), DecodeC_SUB(), DecodeC_SUBW(), and DecodeC_XOR().
DecodeCB_RD()
RxC lldb_private::DecodeCB_RD (uint32_t inst) constexpr
Definition at line 41 of file RISCVCInstructions.h.
References DecodeCA_RD().
Referenced by DecodeC_ANDI(), DecodeC_SRAI(), and DecodeC_SRLI().
DecodeCB_RS1()
RxC lldb_private::DecodeCB_RS1 (uint32_t inst) constexpr
Definition at line 46 of file RISCVCInstructions.h.
References DecodeCA_RD().
Referenced by DecodeC_BEQZ(), and DecodeC_BNEZ().
DecodeCI_RD()
RxC lldb_private::DecodeCI_RD (uint32_t inst) constexpr
Definition at line 31 of file RISCVCInstructions.h.
References DecodeRD().
Referenced by DecodeC_ADDI(), DecodeC_ADDIW(), DecodeC_FLDSP(), DecodeC_FLWSP(), DecodeC_LDSP(), DecodeC_LI(), DecodeC_LUI_ADDI16SP(), DecodeC_LWSP(), and DecodeC_SLLI().
DecodeCI_RS1()
RxC lldb_private::DecodeCI_RS1 (uint32_t inst) constexpr
Definition at line 33 of file RISCVCInstructions.h.
References DecodeRD().
DecodeCIW_RD()
RxC lldb_private::DecodeCIW_RD (uint32_t inst) constexpr
Definition at line 38 of file RISCVCInstructions.h.
Referenced by DecodeC_ADDI4SPN(), DecodeCA_RS2(), DecodeCL_RD(), and DecodeCS_RS2().
DecodeCL_RD()
RxC lldb_private::DecodeCL_RD (uint32_t inst) constexpr
Definition at line 39 of file RISCVCInstructions.h.
References DecodeCIW_RD().
Referenced by DecodeC_FLD(), DecodeC_FLW(), DecodeC_LD(), and DecodeC_LW().
DecodeCL_RS1()
RxC lldb_private::DecodeCL_RS1 (uint32_t inst) constexpr
Definition at line 43 of file RISCVCInstructions.h.
References DecodeCA_RD().
Referenced by DecodeC_FLD(), DecodeC_FLW(), DecodeC_LD(), and DecodeC_LW().
DecodeCR_RD()
RxC lldb_private::DecodeCR_RD (uint32_t inst) constexpr
Definition at line 30 of file RISCVCInstructions.h.
References DecodeRD().
Referenced by DecodeC_ADD(), and DecodeC_MV().
DecodeCR_RS1()
RxC lldb_private::DecodeCR_RS1 (uint32_t inst) constexpr
Definition at line 32 of file RISCVCInstructions.h.
References DecodeRD().
Referenced by DecodeC_JALR(), and DecodeC_JR().
DecodeCR_RS2()
RxC lldb_private::DecodeCR_RS2 (uint32_t inst) constexpr
Definition at line 34 of file RISCVCInstructions.h.
Referenced by DecodeC_ADD(), DecodeC_MV(), and DecodeCSS_RS2().
DecodeCS_RS1()
RxC lldb_private::DecodeCS_RS1 (uint32_t inst) constexpr
Definition at line 44 of file RISCVCInstructions.h.
References DecodeCA_RD().
Referenced by DecodeC_FSD(), DecodeC_FSW(), DecodeC_SD(), and DecodeC_SW().
DecodeCS_RS2()
RxC lldb_private::DecodeCS_RS2 (uint32_t inst) constexpr
Definition at line 49 of file RISCVCInstructions.h.
References DecodeCIW_RD().
Referenced by DecodeC_FSD(), DecodeC_FSW(), DecodeC_SD(), and DecodeC_SW().
DecodeCSS_RS2()
RxC lldb_private::DecodeCSS_RS2 (uint32_t inst) constexpr
Definition at line 48 of file RISCVCInstructions.h.
References DecodeCR_RS2().
Referenced by DecodeC_FSDSP(), DecodeC_FSWSP(), DecodeC_SDSP(), and DecodeC_SWSP().
DecodeFunct2()
uint32_t lldb_private::DecodeFunct2 (uint32_t inst) constexpr
Definition at line 322 of file RISCVInstructions.h.
DecodeFunct3()
uint32_t lldb_private::DecodeFunct3 (uint32_t inst) constexpr
Definition at line 321 of file RISCVInstructions.h.
Referenced by DecodeBType(), and DecodeRM().
DecodeFunct7()
uint32_t lldb_private::DecodeFunct7 (uint32_t inst) constexpr
Definition at line 325 of file RISCVInstructions.h.
DecodeIImm()
uint32_t lldb_private::DecodeIImm (uint32_t inst) constexpr
Definition at line 83 of file EmulateInstructionRISCV.cpp.
Referenced by DecodeIType().
DecodeImmShift() [1/2]
uint32_t lldb_private::DecodeImmShift (const ARM_ShifterType shift_t, const uint32_t imm5) inline static
Definition at line 69 of file ARMUtils.h.
References DecodeImmShift().
DecodeImmShift() [2/2]
uint32_t lldb_private::DecodeImmShift (const uint32_t type, const uint32_t imm5, ARM_ShifterType & shift_t) inline static
Definition at line 25 of file ARMUtils.h.
References SRType_ASR, SRType_Invalid, SRType_LSL, SRType_LSR, SRType_ROR, SRType_RRX, and UINT32_MAX.
Referenced by DecodeImmShift(), DecodeImmShiftARM(), DecodeImmShiftThumb(), lldb_private::EmulateInstructionARM::EmulateLDRBRegister(), lldb_private::EmulateInstructionARM::EmulateLDRRegister(), lldb_private::EmulateInstructionARM::EmulateShiftImm(), and lldb_private::EmulateInstructionARM::EmulateSTRRegister().
DecodeImmShiftARM()
uint32_t lldb_private::DecodeImmShiftARM (const uint32_t opcode, ARM_ShifterType & shift_t) inline static
Definition at line 64 of file ARMUtils.h.
References Bits32(), and DecodeImmShift().
Referenced by lldb_private::EmulateInstructionARM::EmulateADCReg(), lldb_private::EmulateInstructionARM::EmulateADDReg(), lldb_private::EmulateInstructionARM::EmulateANDReg(), lldb_private::EmulateInstructionARM::EmulateBICReg(), lldb_private::EmulateInstructionARM::EmulateCMNReg(), lldb_private::EmulateInstructionARM::EmulateCMPReg(), lldb_private::EmulateInstructionARM::EmulateEORReg(), lldb_private::EmulateInstructionARM::EmulateMVNReg(), lldb_private::EmulateInstructionARM::EmulateORRReg(), lldb_private::EmulateInstructionARM::EmulateRSBReg(), lldb_private::EmulateInstructionARM::EmulateRSCReg(), lldb_private::EmulateInstructionARM::EmulateSBCReg(), lldb_private::EmulateInstructionARM::EmulateSUBReg(), lldb_private::EmulateInstructionARM::EmulateSUBSPcLrEtc(), lldb_private::EmulateInstructionARM::EmulateSUBSPReg(), lldb_private::EmulateInstructionARM::EmulateTEQReg(), and lldb_private::EmulateInstructionARM::EmulateTSTReg().
DecodeImmShiftThumb()
uint32_t lldb_private::DecodeImmShiftThumb (const uint32_t opcode, ARM_ShifterType & shift_t) inline static
Definition at line 55 of file ARMUtils.h.
References Bits32(), and DecodeImmShift().
Referenced by lldb_private::EmulateInstructionARM::EmulateADCReg(), lldb_private::EmulateInstructionARM::EmulateANDReg(), lldb_private::EmulateInstructionARM::EmulateBICReg(), lldb_private::EmulateInstructionARM::EmulateCMNReg(), lldb_private::EmulateInstructionARM::EmulateCMPReg(), lldb_private::EmulateInstructionARM::EmulateEORReg(), lldb_private::EmulateInstructionARM::EmulateMVNReg(), lldb_private::EmulateInstructionARM::EmulateORRReg(), lldb_private::EmulateInstructionARM::EmulateRSBReg(), lldb_private::EmulateInstructionARM::EmulateSBCReg(), lldb_private::EmulateInstructionARM::EmulateSUBReg(), lldb_private::EmulateInstructionARM::EmulateSUBSPReg(), lldb_private::EmulateInstructionARM::EmulateTEQReg(), and lldb_private::EmulateInstructionARM::EmulateTSTReg().
DecodeIType()
template<typename T> RISCVInst lldb_private::DecodeIType (uint32_t inst) static
Definition at line 458 of file EmulateInstructionRISCV.cpp.
References DecodeIImm(), DecodeRD(), and DecodeRS1().
DecodeJImm()
uint32_t lldb_private::DecodeJImm (uint32_t inst) constexpr
Definition at line 76 of file EmulateInstructionRISCV.cpp.
Referenced by DecodeJType().
DecodeJType()
template<typename T> RISCVInst lldb_private::DecodeJType (uint32_t inst) static
Definition at line 454 of file EmulateInstructionRISCV.cpp.
References DecodeJImm(), and DecodeRD().
DecodeR4Type()
template<typename T> RISCVInst lldb_private::DecodeR4Type (uint32_t inst) static
Definition at line 483 of file EmulateInstructionRISCV.cpp.
References DecodeRD(), DecodeRM(), DecodeRS1(), DecodeRS2(), and DecodeRS3().
DecodeRD()
uint32_t lldb_private::DecodeRD (uint32_t inst) constexpr
Definition at line 315 of file RISCVInstructions.h.
Referenced by DecodeCI_RD(), DecodeCI_RS1(), DecodeCR_RD(), DecodeCR_RS1(), DecodeIType(), DecodeJType(), DecodeR4Type(), DecodeRRS1Type(), DecodeRShamtType(), DecodeRType(), and DecodeUType().
DecodeRegShift()
ARM_ShifterType lldb_private::DecodeRegShift (const uint32_t type) inline static
Definition at line 75 of file ARMUtils.h.
References SRType_ASR, SRType_Invalid, SRType_LSL, SRType_LSR, and SRType_ROR.
Referenced by lldb_private::EmulateInstructionARM::EmulateADDRegShift().
DecodeRM()
int32_t lldb_private::DecodeRM (uint32_t inst) constexpr
Definition at line 329 of file RISCVInstructions.h.
References DecodeFunct3().
Referenced by DecodeR4Type().
DecodeRRS1Type()
template<typename T> RISCVInst lldb_private::DecodeRRS1Type (uint32_t inst) static
Definition at line 479 of file EmulateInstructionRISCV.cpp.
References DecodeRD(), and DecodeRS1().
DecodeRS1()
uint32_t lldb_private::DecodeRS1 (uint32_t inst) constexpr
Definition at line 316 of file RISCVInstructions.h.
Referenced by DecodeBType(), DecodeIType(), DecodeR4Type(), DecodeRRS1Type(), DecodeRShamtType(), DecodeRType(), and DecodeSType().
DecodeRS2()
uint32_t lldb_private::DecodeRS2 (uint32_t inst) constexpr
Definition at line 317 of file RISCVInstructions.h.
Referenced by DecodeBType(), DecodeR4Type(), DecodeRShamtType(), DecodeRType(), and DecodeSType().
DecodeRS3()
uint32_t lldb_private::DecodeRS3 (uint32_t inst) constexpr
Definition at line 318 of file RISCVInstructions.h.
Referenced by DecodeR4Type().
DecodeRShamtType()
template<typename T> RISCVInst lldb_private::DecodeRShamtType (uint32_t inst) static
Definition at line 475 of file EmulateInstructionRISCV.cpp.
References DecodeRD(), DecodeRS1(), and DecodeRS2().
DecodeRType()
template<typename T> RISCVInst lldb_private::DecodeRType (uint32_t inst) static
Definition at line 471 of file EmulateInstructionRISCV.cpp.
References DecodeRD(), DecodeRS1(), and DecodeRS2().
DecodeSImm()
uint32_t lldb_private::DecodeSImm (uint32_t inst) constexpr
Definition at line 94 of file EmulateInstructionRISCV.cpp.
Referenced by DecodeSType().
DecodeSType()
template<typename T> RISCVInst lldb_private::DecodeSType (uint32_t inst) static
Definition at line 467 of file EmulateInstructionRISCV.cpp.
References DecodeRS1(), DecodeRS2(), and DecodeSImm().
DecodeUImm()
uint32_t lldb_private::DecodeUImm (uint32_t inst) constexpr
Definition at line 99 of file EmulateInstructionRISCV.cpp.
References SextW().
Referenced by DecodeUType().
DecodeUType()
template<typename T> RISCVInst lldb_private::DecodeUType (uint32_t inst) static
Definition at line 450 of file EmulateInstructionRISCV.cpp.
References DecodeRD(), and DecodeUImm().
DefaultAssertCallback()
void lldb_private::DefaultAssertCallback (llvm::StringRef message, llvm::StringRef backtrace, llvm::StringRef prompt) static
The default callback prints to stderr.
Definition at line 25 of file LLDBAssert.cpp.
DoDumpRegisterInfo()
void lldb_private::DoDumpRegisterInfo (Stream & strm, const char * name, const char * alt_name, uint32_t byte_size, const std::vector< const char * > & invalidates, const std::vector< const char * > & read_from, const std::vector< std::pair< const char *, uint32_t > > & in_sets, const RegisterFlags * flags_type, uint32_t terminal_width)
Referenced by DumpRegisterInfo().
DumpAdditionalExceptionInformation()
void lldb_private::DumpAdditionalExceptionInformation (llvm::raw_ostream & stream, const ExceptionRecordSP & exception) static
Definition at line 316 of file ProcessWindows.cpp.
Referenced by lldb_private::ProcessWindows::RefreshStateAfterStop().
DumpAddress()
void lldb_private::DumpAddress (llvm::raw_ostream & s, uint64_t addr, uint32_t addr_size, const char * prefix = nullptr, const char * suffix = nullptr)
Output an address value to this stream.
Put an address addr out to the stream with optional prefix and suffix strings.
Parameters
[in] s The output stream.
[in] addr An address value.
[in] addr_size Size in bytes of the address, used for formatting.
[in] prefix A prefix C string. If nullptr, no prefix will be output.
[in] suffix A suffix C string. If nullptr, no suffix will be output.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 108 of file Stream.cpp.
Referenced by lldb_private::Address::Dump(), lldb_private::AddressRange::Dump(), lldb_private::plugin::dwarf::DWARFFormValue::Dump(), DumpAddressRange(), DumpDataExtractor(), DumpSymbolContextList(), lldb_private::ThreadPlanRunToAddress::GetDescription(), lldb_private::ThreadPlanStepInstruction::GetDescription(), lldb_private::ThreadPlanStepThrough::GetDescription(), LookupAddressInModule(), LookupSymbolInModule(), lldb_private::ThreadPlanStepInRange::ShouldStop(), lldb_private::ThreadPlanStepInstruction::ShouldStop(), lldb_private::ThreadPlanStepOverRange::ShouldStop(), and lldb_private::ThreadPlanRunToAddress::ValidatePlan().
DumpAddressRange()
void lldb_private::DumpAddressRange (llvm::raw_ostream & s, uint64_t lo_addr, uint64_t hi_addr, uint32_t addr_size, const char * prefix = nullptr, const char * suffix = nullptr)
Output an address range to this stream.
Put an address range lo_addr - hi_addr out to the stream with optional prefix and suffix strings.
Parameters
[in] s The output stream.
[in] lo_addr The start address of the address range.
[in] hi_addr The end address of the address range.
[in] addr_size Size in bytes of the address, used for formatting.
[in] prefix A prefix C string. If nullptr, no prefix will be output.
[in] suffix A suffix C string. If nullptr, no suffix will be output.
Examples
/home/buildbot/as-worker-4/publish-doxygen-docs/llvm-project/lldb/include/lldb/Utility/Stream.h.
Definition at line 120 of file Stream.cpp.
References DumpAddress().
Referenced by lldb_private::Address::Dump(), lldb_private::AddressRange::Dump(), lldb_private::Block::Dump(), lldb_private::VMRange::Dump(), lldb_private::Block::DumpAddressRanges(), and lldb_private::Block::GetDescription().
DumpDataExtractor()
lldb::offset_t lldb_private::DumpDataExtractor (const DataExtractor & DE, Stream * s, lldb::offset_t offset, lldb::Format item_format, size_t item_byte_size, size_t item_count, size_t num_per_line, uint64_t base_addr, uint32_t item_bit_size, uint32_t item_bit_offset, ExecutionContextScope * exe_scope = nullptr, bool show_memory_tags = false)
Dumps item_count objects into the stream s.
Dumps item_count objects using item_format, each of which are item_byte_size bytes long starting at offset offset bytes into the contained data, into the stream s. num_per_line objects will be dumped on each line before a new line will be output. If base_addr is a valid address, then each new line of output will be preceded by the address value plus appropriate offset, and a colon and space. Bitfield values can be dumped by calling this function multiple times with the same start offset, format and size, yet differing item_bit_size and item_bit_offset values.
Parameters
[in] s The stream to dump the output to. This value can not be nullptr.
[in] offset The offset into the data at which to start dumping.
[in] item_format The format to use when dumping each item.
[in] item_byte_size The byte size of each item.
[in] item_count The number of items to dump.
[in] num_per_line The number of items to display on each line.
[in] base_addr The base address that gets added to the offset displayed on each line if the value is valid. Is base_addr is LLDB_INVALID_ADDRESS then no address values will be prepended to any lines.
[in] item_bit_size If the value to display is a bitfield, this value should be the number of bits that the bitfield item has within the item's byte size value. This function will need to be called multiple times with identical offset and item_byte_size values in order to display multiple bitfield values that exist within the same integer value. If the items being displayed are not bitfields, this value should be zero.
[in] item_bit_offset If the value to display is a bitfield, this value should be the offset in bits, or shift right amount, that the bitfield item occupies within the item's byte size value. This function will need to be called multiple times with identical offset and item_byte_size values in order to display multiple bitfield values that exist within the same integer value. If the items being displayed are not bitfields, this value should be zero.
[in] exe_scope If provided, this will be used to lookup language specific information, address information and memory tags. (if they are requested by the other options)
[in] show_memory_tags If exe_scope and base_addr are valid, include memory tags in the output. This does not apply to certain formats.
Returns
The offset at which dumping ended.
Definition at line 350 of file DumpDataExtractor.cpp.
References lldb_private::Stream::AsRawOstream(), bits(), lldb_private::ExecutionContextScope::CalculateProcess(), lldb_private::ExecutionContextScope::CalculateTarget(), lldb_private::Address::Dump(), DumpAddress(), DumpAPInt(), DumpCharacter(), DumpDataExtractor(), DumpInstructions(), lldb_private::Address::DumpStyleModuleWithFileAddress, lldb_private::Address::DumpStyleResolvedDescription, lldb_private::Address::DumpStyleResolvedPointerDescription, lldb::eByteOrderBig, lldb::eFormatAddressInfo, lldb::eFormatBinary, lldb::eFormatBoolean, lldb::eFormatBytes, lldb::eFormatBytesWithASCII, lldb::eFormatChar, lldb::eFormatCharArray, lldb::eFormatCharPrintable, lldb::eFormatComplex, lldb::eFormatComplexInteger, lldb::eFormatCString, lldb::eFormatDecimal, lldb::eFormatDefault, lldb::eFormatEnum, lldb::eFormatFloat, lldb::eFormatFloat128, lldb::eFormatHex, lldb::eFormatHexFloat, lldb::eFormatHexUppercase, lldb::eFormatInstruction, lldb::eFormatOctal, lldb::eFormatOSType, lldb::eFormatPointer, lldb::eFormatUnicode16, lldb::eFormatUnicode32, lldb::eFormatUnsigned, lldb::eFormatVectorOfChar, lldb::eFormatVectorOfFloat16, lldb::eFormatVectorOfFloat32, lldb::eFormatVectorOfFloat64, lldb::eFormatVectorOfSInt16, lldb::eFormatVectorOfSInt32, lldb::eFormatVectorOfSInt64, lldb::eFormatVectorOfSInt8, lldb::eFormatVectorOfUInt128, lldb::eFormatVectorOfUInt16, lldb::eFormatVectorOfUInt32, lldb::eFormatVectorOfUInt64, lldb::eFormatVectorOfUInt8, lldb_private::Stream::EOL(), lldb_private::Stream::Format(), lldb_private::Stream::GetAddressByteSize(), GetAPInt(), lldb_private::DataExtractor::GetByteOrder(), lldb_private::DataExtractor::GetByteSize(), lldb_private::DataExtractor::GetCStr(), lldb_private::DataExtractor::GetData(), lldb_private::DataExtractor::GetDouble(), lldb_private::DataExtractor::GetFloat(), GetFloatSemantics(), lldb_private::Target::GetGlobalProperties(), lldb_private::DataExtractor::GetLongDouble(), lldb_private::DataExtractor::GetMaxS64Bitfield(), lldb_private::DataExtractor::GetMaxU64Bitfield(), GetMemoryTags(), lldb_private::DataExtractor::GetU16(), lldb_private::DataExtractor::GetU32(), lldb_private::DataExtractor::GetU8(), LLDB_INVALID_ADDRESS, LLDB_INVALID_OFFSET, NON_PRINTABLE_CHAR, lldb_private::Stream::Printf(), printMemoryTags(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), lldb_private::Address::SetOffset(), TryDumpSpecialEscapedChar(), and lldb_private::DataExtractor::ValidOffset().
Referenced by CommandObjectMemoryFind::DoExecute(), CommandObjectMemoryRead::DoExecute(), CommandObjectProcessMinidumpDump::DoExecute(), DumpDataExtractor(), DumpHexBytes(), CommunicationKDP::DumpPacket(), DumpRegisterValue(), lldb_private::TypeSystemClang::DumpTypeValue(), DumpUInt(), lldb_private::TypeFormatImpl_Format::FormatObject(), lldb::SBData::GetDescription(), ReadCStringFromMemory(), and UnwindAssemblyInstEmulation::WriteMemory().
DumpHexBytes()
void lldb_private::DumpHexBytes (Stream * s, const void * src, size_t src_len, uint32_t bytes_per_line, lldb::addr_t base_addr)
Definition at line 906 of file DumpDataExtractor.cpp.
References DumpDataExtractor(), lldb::eByteOrderLittle, and lldb::eFormatBytes.
Referenced by CommunicationKDP::CheckForPacket(), CommunicationKDP::DumpPacket(), EntityPersistentVariable::DumpToLog(), EntityRegister::DumpToLog(), EntityResultVariable::DumpToLog(), EntitySymbol::DumpToLog(), and EntityVariableBase::DumpToLog().
DumpRegisterInfo()
void lldb_private::DumpRegisterInfo (Stream & strm, RegisterContext & ctx, const RegisterInfo & info, uint32_t terminal_width)
Definition at line 19 of file DumpRegisterInfo.cpp.
References lldb_private::RegisterInfo::alt_name, lldb_private::RegisterInfo::byte_size, DoDumpRegisterInfo(), lldb::eRegisterKindLLDB, lldb_private::RegisterInfo::flags_type, lldb_private::RegisterContext::GetRegisterInfo(), lldb_private::RegisterContext::GetRegisterInfoAtIndex(), lldb_private::RegisterContext::GetRegisterSet(), lldb_private::RegisterContext::GetRegisterSetCount(), lldb_private::RegisterInfo::invalidate_regs, LLDB_INVALID_REGNUM, lldb_private::RegisterInfo::name, lldb_private::RegisterSet::name, lldb_private::RegisterSet::num_registers, lldb_private::RegisterSet::registers, and lldb_private::RegisterInfo::value_regs.
DumpRegisterValue()
void lldb_private::DumpRegisterValue (const RegisterValue & reg_val, Stream & s, const RegisterInfo & reg_info, bool prefix_with_name, bool prefix_with_alt_name, lldb::Format format, uint32_t reg_name_right_align_at = 0, ExecutionContextScope * exe_scope = nullptr, bool print_flags = false, lldb::TargetSP target_sp = nullptr)
Definition at line 61 of file DumpRegisterValue.cpp.
References lldb_private::RegisterInfo::alt_name, lldb_private::RegisterInfo::byte_size, dump_type_value(), DumpDataExtractor(), lldb::eFormatDefault, lldb_private::Stream::EOL(), lldb_private::RegisterInfo::flags_type, lldb_private::RegisterInfo::format, lldb_private::RegisterValue::GetAsUInt32(), lldb_private::RegisterValue::GetAsUInt64(), lldb_private::RegisterValue::GetData(), lldb_private::StreamString::GetString(), LLDB_INVALID_ADDRESS, lldb_private::RegisterInfo::name, lldb_private::Stream::Printf(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), and UINT32_MAX.
Referenced by CommandObjectRegisterRead::DumpRegister(), DumpRegister(), DumpRegister(), lldb_private::ThreadPlanAssemblyTracer::Log(), UnwindAssemblyInstEmulation::ReadRegister(), lldb_private::ThreadPlanCallFunction::ReportRegisterState(), UnwindAssemblyInstEmulation::WriteRegister(), and lldb_private::EmulateInstruction::WriteRegisterDefault().
DynCast()
template<class D2, template< class D > class TD, class D1> TD< D2 > lldb_private::DynCast (TD< D1 > source)
Definition at line 496 of file ClangASTImporter.h.
Referenced by ExtractBaseOffsets(), and lldb_private::ClangASTImporter::importRecordLayoutFromOrigin().
ExprPathHelpTextCallback()
llvm::StringRef lldb_private::ExprPathHelpTextCallback ()
Definition at line 256 of file CommandOptionArgumentTable.cpp.
FindLongestCommandWord()
template<typename ValueType> size_t lldb_private::FindLongestCommandWord (std::map< std::string, ValueType, std::less<> > & dict)
Definition at line 58 of file CommandObject.h.
Referenced by lldb_private::CommandObjectMultiword::GenerateHelpText(), and lldb_private::CommandInterpreter::GetHelp().
FLAGS_ANONYMOUS_ENUM()
lldb_private::FLAGS_ANONYMOUS_ENUM ()
Definition at line 35 of file CompactUnwindInfo.cpp.
FLAGS_ENUM()
lldb_private::FLAGS_ENUM (TypeQueryOptions)
If set, TypeQuery::m_context contains an exact context that must match the full context. If not set, TypeQuery::m_context can contain a partial type match where the full context isn't fully specified.
If set, TypeQuery::m_context is a clang module compiler context. If not set TypeQuery::m_context is normal type lookup context.
If set, the query will ignore all Module entries in the type context, even for exact matches.
If set, all anonymous namespaces in the context must be matched exactly by the pattern. Otherwise, superfluous namespaces are skipped.
When true, the find types call should stop the query as soon as a single matching type is found. When false, the type query should find all matching types.
Definition at line 68 of file Type.h.
ForEachFormatterInModule()
void lldb_private::ForEachFormatterInModule (Module & module, SectionType section_type, std::function< void(llvm::DataExtractor, llvm::StringRef)> fn) static
Definition at line 36 of file FormatterSection.cpp.
References DataFormatters, error(), lldb_private::DataExtractor::GetAsLLVM(), lldb_private::DataVisualization::Categories::GetCategory(), lldb_private::Module::GetFileSpec(), GetLog(), LLDB_LOG, LLDB_LOG_ERROR, and skipPadding().
Referenced by LoadFormattersForModule(), and LoadTypeSummariesForModule().
FormatCache::Entry::IsCached< lldb::SyntheticChildrenSP >()
template<> bool lldb_private::FormatCache::Entry::IsCached< lldb::SyntheticChildrenSP > ()
Definition at line 62 of file FormatCache.cpp.
FormatCache::Entry::IsCached< lldb::TypeFormatImplSP >()
template<> bool lldb_private::FormatCache::Entry::IsCached< lldb::TypeFormatImplSP > ()
Definition at line 56 of file FormatCache.cpp.
FormatCache::Entry::IsCached< lldb::TypeSummaryImplSP >()
template<> bool lldb_private::FormatCache::Entry::IsCached< lldb::TypeSummaryImplSP > ()
Definition at line 59 of file FormatCache.cpp.
FormatHelpTextCallback()
llvm::StringRef lldb_private::FormatHelpTextCallback ()
Definition at line 136 of file CommandOptionArgumentTable.cpp.
References lldb::eFormatDefault, lldb_private::StreamString::Flush(), lldb_private::FormatManager::GetFormatAsCString(), lldb_private::FormatManager::GetFormatAsFormatChar(), lldb_private::StreamString::GetString(), lldb::kNumFormats, lldb_private::Stream::Printf(), and lldb_private::Stream::PutChar().
FPREncodingToLLDB()
uint32_t lldb_private::FPREncodingToLLDB (uint32_t reg_encode) static
Definition at line 111 of file EmulateInstructionRISCV.cpp.
References fpr_f0_riscv, and LLDB_INVALID_REGNUM.
Referenced by lldb_private::Rs::ReadAPFloat(), and lldb_private::Rd::WriteAPFloat().
fromJSON() [1/30]
bool lldb_private::fromJSON (const json::Value & value, JSONUINT64 & uint64, Path path)
Definition at line 32 of file TraceIntelPTGDBRemotePackets.cpp.
References lldb_private::JSONUINT64::value.
fromJSON() [2/30]
bool lldb_private::fromJSON (const json::Value & value, LinuxPerfZeroTscConversion & packet, json::Path path)
Definition at line 97 of file TraceIntelPTGDBRemotePackets.cpp.
References lldb_private::LinuxPerfZeroTscConversion::time_mult, lldb_private::LinuxPerfZeroTscConversion::time_shift, and lldb_private::LinuxPerfZeroTscConversion::time_zero.
fromJSON() [3/30]
bool lldb_private::fromJSON (const json::Value & value, ObjectFileJSON::Body & body, json::Path path)
Definition at line 294 of file ObjectFileJSON.cpp.
References lldb_private::ObjectFileJSON::Body::sections, and lldb_private::ObjectFileJSON::Body::symbols.
fromJSON() [4/30]
bool lldb_private::fromJSON (const json::Value & value, ObjectFileJSON::Header & header, json::Path path)
Definition at line 287 of file ObjectFileJSON.cpp.
References lldb_private::ObjectFileJSON::Header::triple, lldb_private::ObjectFileJSON::Header::type, and lldb_private::ObjectFileJSON::Header::uuid.
fromJSON() [5/30]
bool lldb_private::fromJSON (const json::Value & value, TraceBinaryData & packet, Path path)
Definition at line 78 of file TraceGDBRemotePackets.cpp.
References lldb_private::TraceBinaryData::kind, and lldb_private::TraceBinaryData::size.
fromJSON() [6/30]
bool lldb_private::fromJSON (const json::Value & value, TraceCpuState & packet, json::Path path)
Definition at line 119 of file TraceGDBRemotePackets.cpp.
References lldb_private::TraceCpuState::binary_data, and lldb_private::TraceCpuState::id.
fromJSON() [7/30]
bool lldb_private::fromJSON (const json::Value & value, TraceGetBinaryDataRequest & packet, Path path)
Definition at line 144 of file TraceGDBRemotePackets.cpp.
References lldb_private::TraceGetBinaryDataRequest::cpu_id, lldb_private::TraceGetBinaryDataRequest::kind, lldb_private::TraceGetBinaryDataRequest::tid, and lldb_private::TraceGetBinaryDataRequest::type.
fromJSON() [8/30]
bool lldb_private::fromJSON (const json::Value & value, TraceGetStateRequest & packet, Path path)
jLLDBTraceGetState
Definition at line 68 of file TraceGDBRemotePackets.cpp.
References lldb_private::TraceGetStateRequest::type.
fromJSON() [9/30]
bool lldb_private::fromJSON (const json::Value & value, TraceGetStateResponse & packet, Path path)
Definition at line 98 of file TraceGDBRemotePackets.cpp.
References lldb_private::TraceGetStateResponse::cpus, lldb_private::TraceGetStateResponse::process_binary_data, lldb_private::TraceGetStateResponse::traced_threads, and lldb_private::TraceGetStateResponse::warnings.
fromJSON() [10/30]
bool lldb_private::fromJSON (const json::Value & value, TraceIntelPTGetStateResponse & packet, json::Path path)
Definition at line 109 of file TraceIntelPTGDBRemotePackets.cpp.
References fromJSON(), lldb_private::TraceIntelPTGetStateResponse::tsc_perf_zero_conversion, and lldb_private::TraceIntelPTGetStateResponse::using_cgroup_filtering.
fromJSON() [11/30]
bool lldb_private::fromJSON (const json::Value & value, TraceIntelPTStartRequest & packet, Path path)
Definition at line 45 of file TraceIntelPTGDBRemotePackets.cpp.
References lldb_private::TraceIntelPTStartRequest::disable_cgroup_filtering, lldb_private::TraceIntelPTStartRequest::enable_tsc, fromJSON(), lldb_private::TraceIntelPTStartRequest::ipt_trace_size, lldb_private::TraceStartRequest::IsProcessTracing(), lldb_private::TraceIntelPTStartRequest::per_cpu_tracing, lldb_private::TraceIntelPTStartRequest::process_buffer_size_limit, and lldb_private::TraceIntelPTStartRequest::psb_period.
fromJSON() [12/30]
bool lldb_private::fromJSON (const json::Value & value, TraceStartRequest & packet, Path path)
Definition at line 34 of file TraceGDBRemotePackets.cpp.
References lldb_private::TraceStartRequest::tids, and lldb_private::TraceStartRequest::type.
fromJSON() [13/30]
bool lldb_private::fromJSON (const json::Value & value, TraceStopRequest & packet, Path path)
Definition at line 56 of file TraceGDBRemotePackets.cpp.
References lldb_private::TraceStopRequest::tids, and lldb_private::TraceStopRequest::type.
fromJSON() [14/30]
bool lldb_private::fromJSON (const json::Value & value, TraceSupportedResponse & packet, Path path)
jLLDBTraceSupported
Definition at line 17 of file TraceGDBRemotePackets.cpp.
References lldb_private::TraceSupportedResponse::description, and lldb_private::TraceSupportedResponse::name.
fromJSON() [15/30]
bool lldb_private::fromJSON (const json::Value & value, TraceThreadState & packet, Path path)
Definition at line 87 of file TraceGDBRemotePackets.cpp.
References lldb_private::TraceThreadState::binary_data, and lldb_private::TraceThreadState::tid.
fromJSON() [16/30]
bool lldb_private::fromJSON (const llvm::json::Value & value, JSONUINT64 & uint64, llvm::json::Path path)
fromJSON() [17/30]
bool lldb_private::fromJSON (const llvm::json::Value & value, LinuxPerfZeroTscConversion & packet, llvm::json::Path path)
fromJSON() [18/30]
bool lldb_private::fromJSON (const llvm::json::Value & value, lldb_private::TraceGetBinaryDataRequest & packet, llvm::json::Path path)
fromJSON() [19/30]
bool lldb_private::fromJSON (const llvm::json::Value & value, ObjectFileJSON::Body & body, llvm::json::Path path)
fromJSON() [20/30]
bool lldb_private::fromJSON (const llvm::json::Value & value, ObjectFileJSON::Header & header, llvm::json::Path path)
fromJSON() [21/30]
bool lldb_private::fromJSON (const llvm::json::Value & value, TraceBinaryData & packet, llvm::json::Path path)
fromJSON() [22/30]
bool lldb_private::fromJSON (const llvm::json::Value & value, TraceCpuState & packet, llvm::json::Path path)
fromJSON() [23/30]
bool lldb_private::fromJSON (const llvm::json::Value & value, TraceGetStateRequest & packet, llvm::json::Path path)
fromJSON() [24/30]
bool lldb_private::fromJSON (const llvm::json::Value & value, TraceGetStateResponse & packet, llvm::json::Path path)
fromJSON() [25/30]
bool lldb_private::fromJSON (const llvm::json::Value & value, TraceIntelPTGetStateResponse & packet, llvm::json::Path path)
fromJSON() [26/30]
bool lldb_private::fromJSON (const llvm::json::Value & value, TraceIntelPTStartRequest & packet, llvm::json::Path path)
fromJSON() [27/30]
bool lldb_private::fromJSON (const llvm::json::Value & value, TraceStartRequest & packet, llvm::json::Path path)
fromJSON() [28/30]
bool lldb_private::fromJSON (const llvm::json::Value & value, TraceStopRequest & packet, llvm::json::Path path)
fromJSON() [29/30]
bool lldb_private::fromJSON (const llvm::json::Value & value, TraceSupportedResponse & info, llvm::json::Path path)
Referenced by lldb_private::mcp::CommandTool::Call(), lldb_private::ObjectFileJSON::CreateInstance(), fromJSON(), fromJSON(), lldb_private::ObjectFileJSON::GetModuleSpecifications(), and lldb_private::transport::Binder< Proto >::Parse().
fromJSON() [30/30]
bool lldb_private::fromJSON (const llvm::json::Value & value, TraceThreadState & packet, llvm::json::Path path)
FullToAbridgedTagWord()
uint8_t lldb_private::FullToAbridgedTagWord (uint16_t tw)
Definition at line 49 of file RegisterContext_x86.cpp.
GDBFormatHelpTextCallback()
llvm::StringRef lldb_private::GDBFormatHelpTextCallback ()
Definition at line 99 of file CommandOptionArgumentTable.cpp.
GetAbortLocation()
bool lldb_private::GetAbortLocation (llvm::Triple::OSType os, SymbolLocation & location)
Fetches the abort frame location depending on the current platform.
Parameters
[in] os The target's os type.
[in,out] location The struct that will contain the abort module spec and symbol names.
Returns
true, if the platform is supported false, otherwise.
Definition at line 26 of file AssertFrameRecognizer.cpp.
References GetLog(), LLDB_LOG, lldb_private::SymbolLocation::module_spec, lldb_private::SymbolLocation::symbols, lldb_private::SymbolLocation::symbols_are_regex, and Unwind.
Referenced by RegisterAssertFrameRecognizer().
getAppleArm64ExceptionClass()
AppleArm64ExceptionClass lldb_private::getAppleArm64ExceptionClass (uint32_t esr) inline
Get the Apple ARM64 exception class encoded within esr.
Definition at line 22 of file AppleArm64ExceptionClass.h.
Referenced by ThreadMachCore::CalculateStopInfo().
GetAssertLocation()
bool lldb_private::GetAssertLocation (llvm::Triple::OSType os, SymbolLocation & location)
Fetches the assert frame location depending on the current platform.
Parameters
[in] os The target's os type.
[in,out] location The struct that will contain the assert module spec and symbol names.
Returns
true, if the platform is supported false, otherwise.
Definition at line 59 of file AssertFrameRecognizer.cpp.
References GetLog(), LLDB_LOG, lldb_private::SymbolLocation::module_spec, lldb_private::SymbolLocation::symbols, and Unwind.
Referenced by lldb_private::AssertFrameRecognizer::RecognizeFrame().
GetClangResourceDir()
FileSpec lldb_private::GetClangResourceDir ()
Definition at line 159 of file ClangHost.cpp.
References ComputeClangResourceDirectory(), GetLog(), lldb_private::FileSpec::GetPath(), Host, and LLDB_LOGF.
Referenced by lldb_private::CppModuleConfiguration::CppModuleConfiguration(), lldb_private::ClangModulesDeclVendor::Create(), lldb::SBHostOS::GetLLDBPath(), and SetupModuleHeaderPaths().
GetDynamicValueTypes()
OptionEnumValues lldb_private::GetDynamicValueTypes ()
Definition at line 4250 of file Target.cpp.
References g_dynamic_value_types.
Referenced by lldb_private::OptionGroupValueObjectDisplay::SetOptionValue().
GetLLDBErrorLog()
Log * lldb_private::GetLLDBErrorLog ()
Definition at line 470 of file Log.cpp.
References g_error_log.
GetLog()
template<typename Cat> Log * lldb_private::GetLog (Cat mask)
Retrieve the Log object for the channel associated with the given log enum.
Returns a valid Log object if any of the provided categories are enabled. Otherwise, returns nullptr.
Definition at line 332 of file Log.h.
References lldb_private::Log::Channel::GetLog(), and LogChannelFor().
Referenced by lldb_private::DomainSocket::Accept(), lldb_private::TCPSocket::Accept(), lldb_private::mcp::ProtocolServerMCP::AcceptCallback(), lldb_private::InstrumentationRuntimeBoundsSafety::Activate(), lldb_private::platform_android::AdbClient::AdbClient(), lldb_private::platform_android::AdbClient::AdbClient(), lldb_private::platform_android::AdbSyncService::AdbSyncService(), DynamicLoaderMacOS::AddBinaries(), lldb_private::Target::AddBreakpoint(), lldb_private::PlatformDarwin::AddClangModuleCompilationOptionsForSDKType(), lldb_private::ClangExpressionDeclMap::AddContextClassType(), lldb_private::Listener::AddEvent(), lldb_private::TypeSystemClang::AddFieldToRecordType(), lldb_private::UnwindLLDB::AddFirstFrame(), lldb_private::NameSearchContext::AddFunDecl(), lldb_private::RegisterContextWindows::AddHardwareBreakpoint(), lldb_private::StructuredDataDarwinLog::AddInitCompletionHook(), lldb_private::BreakpointLocationList::AddLocation(), lldb_private::BreakpointResolver::AddLocation(), lldb_private::BreakpointResolver::AddLocation(), MinidumpFileBuilder::AddMemoryList_32(), MinidumpFileBuilder::AddMemoryList_64(), MinidumpFileBuilder::AddModuleList(), DynamicLoaderMacOSXDYLD::AddModulesUsingImageInfosAddress(), lldb_private::DynamicLoaderDarwin::AddModulesUsingPreloadedModules(), lldb_private::ClangExpressionDeclMap::AddOneFunction(), lldb_private::ClangExpressionDeclMap::AddOneGenericVariable(), lldb_private::UnwindLLDB::AddOneMoreFrame(), lldb_private::ClangExpressionDeclMap::AddOneRegister(), lldb_private::ClangExpressionDeclMap::AddOneType(), lldb_private::ClangExpressionDeclMap::AddOneVariable(), lldb_private::ClangExpressionDeclMap::AddOneVariable(), lldb_private::ClangExpressionDeclMap::AddOneVariable(), lldb_private::ClangExpressionDeclMap::AddPersistentVariable(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::AddProcessThreads(), AddPtraceScopeNote(), lldb_private::Block::AddRange(), PDBASTParser::AddRecordMembers(), lldb_private::breakpad::SymbolFileBreakpad::AddSymbols(), lldb_private::process_freebsd::NativeProcessFreeBSD::AddThread(), lldb_private::process_linux::NativeProcessLinux::AddThread(), lldb_private::process_netbsd::NativeProcessNetBSD::AddThread(), MinidumpFileBuilder::AddThreadList(), lldb_private::ObjCLanguageRuntime::AddToMethodCache(), lldb_private::ObjCLanguageRuntime::AddToMethodCache(), lldb_private::ClangExpressionDeclMap::AddValueToStruct(), lldb_private::IRExecutionUnit::MemoryManager::allocateCodeSection(), lldb_private::IRExecutionUnit::MemoryManager::allocateDataSection(), lldb_private::AllocatedMemoryCache::AllocateMemory(), lldb_private::ProcessDebugger::AllocateMemory(), lldb_private::AllocatedMemoryCache::AllocatePage(), lldb_private::ThreadedCommunication::AppendBytesToCache(), ObjectFilePECOFF::AppendFromCOFFSymbolTable(), ObjectFilePECOFF::AppendFromExportTable(), ApplyELF32ABS32RelRelocation(), ApplyELF64ABS32Relocation(), lldb_private::Target::ApplyNameToBreakpoints(), lldb_private::process_gdb_remote::ProcessGDBRemote::AsyncThread(), ProcessKDP::AsyncThread(), lldb_private::WatchpointAlgorithms::AtomizeWatchpointRequest(), lldb_private::process_aix::NativeProcessAIX::Attach(), lldb_private::process_aix::NativeProcessAIX::Manager::Attach(), lldb_private::process_freebsd::NativeProcessFreeBSD::Manager::Attach(), lldb_private::process_linux::NativeProcessLinux::Attach(), lldb_private::process_linux::NativeProcessLinux::Manager::Attach(), lldb_private::process_netbsd::NativeProcessNetBSD::Manager::Attach(), PlatformPOSIX::Attach(), lldb_private::Process::AttachCompletionHandler::AttachCompletionHandler(), lldb_private::ProcessDebugger::AttachProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::AttachToProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::AttachWaitProcess(), lldb_private::formatters::BlockPointerSummaryProvider(), lldb_private::formatters::BlockPointerSyntheticFrontEnd::BlockPointerSyntheticFrontEnd(), DynamicLoaderDarwinKernel::BreakpointHit(), lldb_private::ThreadPlanCallFunction::BreakpointsExplainStop(), lldb_private::Broadcaster::Broadcaster(), lldb_private::plugin::dwarf::DWARFCompileUnit::BuildAddressRangeTable(), lldb_private::process_gdb_remote::ProcessGDBRemote::BuildDynamicRegisterInfo(), lldb_private::plugin::dwarf::DWARFDebugInfoEntry::BuildFunctionAddressRangeTable(), lldb_private::AppleObjCTypeEncodingParser::BuildObjCObjectPointerType(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::BuildTargetXml(), lldb_private::ConnectionFileDescriptor::BytesAvailable(), lldb_private::RegisterContextWindows::CacheAllRegisterValues(), lldb_private::BytecodeSyntheticChildren::FrontEnd::CalculateNumChildren(), lldb_private::ValueObjectSynthetic::CalculateNumChildren(), lldb_private::SyntheticChildrenFrontEnd::CalculateNumChildrenIgnoringErrors(), lldb_private::Platform::CallLocateModuleCallbackIfSet(), IOHandlerProcessSTDIO::Cancel(), lldb_private::Process::CanJIT(), ProcessMachCore::CheckAddressForDyldOrKernel(), DynamicLoaderDarwinKernel::CheckForKernelImageAtAddress(), DynamicLoaderFreeBSDKernel::CheckForKernelImageAtAddress(), CommunicationKDP::CheckForPacket(), lldb_private::process_gdb_remote::GDBRemoteCommunication::CheckForPacket(), lldb_private::InstrumentationRuntimeBoundsSafety::CheckIfRuntimeIsValid(), lldb_private::ClangExpressionParser::ClangExpressionParser(), lldb_private::Listener::Clear(), lldb_private::Status::Clear(), lldb_private::BreakpointLocationList::ClearAllBreakpointSites(), lldb_private::NativeRegisterContextDBReg::ClearAllHardwareBreakpoints(), lldb_private::Target::ClearAllWatchpointHistoricValues(), lldb_private::Target::ClearAllWatchpointHitCounts(), lldb_private::NativeRegisterContextDBReg::ClearHardwareBreakpoint(), lldb_private::NativeRegisterContextDBReg::ClearHardwareWatchpoint(), lldb_private::ThreadPlanStepRange::ClearNextBranchBreakpoint(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::ClearProcessSpecificData(), lldb_private::ObjectFile::ClearSymtab(), lldb_private::Socket::Close(), lldb_private::ConnectionFileDescriptor::CloseCommandPipe(), lldb_private::plugin::dwarf::SymbolFileDWARF::CollectCallEdges(), lldb_private::process_linux::NativeProcessLinux::Manager::CollectThread(), lldb_private::CommandAlias::CommandAlias(), lldb_private::ASTResultSynthesizer::CommitPersistentDecls(), lldb_private::ClangFunctionCaller::CompileFunction(), lldb_private::ClangUserExpression::Complete(), lldb_private::ClangASTImporter::CompleteAndFetchChildren(), lldb_private::Process::CompleteAttach(), lldb_private::ClangASTSource::CompleteNamespaceMap(), DWARFASTParserClang::CompleteRecordType(), lldb_private::AppleObjCExternalASTSource::CompleteType(), lldb_private::AppleObjCExternalASTSource::CompleteType(), lldb_private::ClangASTSource::CompleteType(), lldb_private::plugin::dwarf::SymbolFileDWARF::CompleteType(), lldb_private::SymbolFileCTF::CompleteType(), SymbolFilePDB::CompleteType(), ComputeNumRangesMultiMemRead(), lldb_private::HostInfoBase::ComputePathRelativeToLibrary(), InstrumentationBoundsSafetyStopInfo::ComputeStopReasonAndSuggestedStackFrame(), InstrumentationBoundsSafetyStopInfo::ComputeStopReasonAndSuggestedStackFrameWithoutDebugInfo(), lldb_private::HostInfoMacOSX::ComputeSupportExeDirectory(), ComputeTargetFrame(), lldb_private::BreakpointLocation::ConditionSaysStop(), lldb_private::ConnectionFileDescriptor::Connect(), lldb_private::ConnectionGenericFile::Connect(), lldb_private::TCPSocket::Connect(), lldb_private::ConnectionFileDescriptor::ConnectionFileDescriptor(), lldb_private::ConnectionFileDescriptor::ConnectionFileDescriptor(), lldb_private::platform_android::PlatformAndroidRemoteGDBServer::ConnectRemote(), ConnectToAdb(), lldb_private::process_gdb_remote::ProcessGDBRemote::ConnectToDebugserver(), lldb_private::ConnectionFileDescriptor::ConnectUDP(), lldb_private::plugin::dwarf::SymbolFileDWARF::ConstructFunctionDemangledName(), lldb_private::ThreadPlanCallFunction::ConstructorSetup(), lldb_private::DebuggerThread::ContinueAsyncException(), lldb_private::Process::ControlPrivateStateThread(), ConvertDWARFCallingConventionToClang(), lldb_private::ClangASTImporter::CopyDecl(), lldb_private::ClangASTImporter::CopyType(), lldb_private::ClangModulesDeclVendor::Create(), lldb_private::ScriptedFrame::Create(), lldb_private::TypeSystemClang::CreateASTContext(), ObjectFilePECOFF::CreateBinary(), ObjectFileXCOFF::CreateBinary(), lldb_private::ValueObject::CreateChildAtIndex(), lldb_private::ValueObjectConstResultImpl::CreateChildAtIndex(), lldb_private::npdb::SymbolFileNativePDB::CreateClassStructUnion(), lldb_private::UDPSocket::CreateConnected(), lldb_private::process_linux::CreateContextSwitchTracePerfEvent(), lldb_private::ObjectFileJSON::CreateInstance(), lldb_private::platform_aix::PlatformAIX::CreateInstance(), lldb_private::platform_android::PlatformAndroid::CreateInstance(), lldb_private::platform_freebsd::PlatformFreeBSD::CreateInstance(), lldb_private::platform_linux::PlatformLinux::CreateInstance(), lldb_private::platform_netbsd::PlatformNetBSD::CreateInstance(), lldb_private::platform_openbsd::PlatformOpenBSD::CreateInstance(), lldb_private::PlatformAppleSimulator::CreateInstance(), lldb_private::PlatformRemoteAppleBridge::CreateInstance(), lldb_private::PlatformRemoteAppleTV::CreateInstance(), lldb_private::PlatformRemoteAppleWatch::CreateInstance(), lldb_private::PlatformRemoteAppleXR::CreateInstance(), lldb_private::PlatformRemoteiOS::CreateInstance(), lldb_private::PlatformRemoteMacOSX::CreateInstance(), lldb_private::PlatformWasm::CreateInstance(), lldb_private::ScriptedProcess::CreateInstance(), lldb_private::SyntheticFrameProvider::CreateInstance(), lldb_private::wasm::ObjectFileWasm::CreateInstance(), ObjectFileCOFF::CreateInstance(), lldb_private::ScriptedPythonInterface::CreatePluginObject(), CreateRegionsCacheFromLinuxMaps(), CreateRegionsCacheFromMemoryInfoList(), CreateRegionsCacheFromMemoryList(), lldb_private::TargetThreadWindows::CreateRegisterContextForFrame(), ThreadElfCore::CreateRegisterContextForFrame(), lldb_private::wasm::ObjectFileWasm::CreateSections(), DWARFASTParserClang::CreateStaticMemberVariable(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::CreateSymlink(), lldb_private::ValueObject::CreateSyntheticArrayMember(), lldb_private::ValueObjectConstResultImpl::CreateSyntheticArrayMember(), lldb::SBDebugger::CreateTarget(), lldb::SBDebugger::CreateTarget(), lldb::SBDebugger::CreateTargetWithFileAndArch(), lldb::SBDebugger::CreateTargetWithFileAndTargetTriple(), lldb_private::Target::CreateWatchpoint(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::DataAvailableCallback(), lldb_private::DataFileCache::DataFileCache(), lldb_private::InstrumentationRuntimeBoundsSafety::Deactivate(), lldb_private::AllocatedMemoryCache::DeallocateMemory(), lldb_private::ProcessDebugger::DeallocateMemory(), lldb_private::plugin::dwarf::SymbolFileDWARF::DebugAbbrev(), lldb_private::DebuggerThread::DebugAttach(), lldb_private::DebuggerThread::DebuggerThreadAttachRoutine(), lldb_private::DebuggerThread::DebuggerThreadLaunchRoutine(), lldb_private::DebuggerThread::DebugLaunch(), lldb_private::DebuggerThread::DebugLoop(), lldb_private::Platform::DebugProcess(), lldb_private::PlatformQemuUser::DebugProcess(), lldb_private::PlatformWasm::DebugProcess(), lldb_private::PlatformWindows::DebugProcess(), PlatformPOSIX::DebugProcess(), lldb_private::plugin::dwarf::SymbolFileDWARF::DeclContextMatchesThisSymbolFile(), SymbolFilePDB::DeclContextMatchesThisSymbolFile(), lldb_private::EmulateInstructionRISCV::Decode(), lldb_private::wasm::ObjectFileWasm::DecodeNextSection(), lldb_private::process_gdb_remote::GDBRemoteCommunication::DecompressPacket(), lldb_private::BreakpointResolverFileLine::DeduceSourceMapping(), DefaultComputeClangResourceDirectory(), lldb_private::ThreadPlanShouldStopHere::DefaultShouldStopHereCallback(), lldb_private::ThreadPlanStepInRange::DefaultShouldStopHereCallback(), lldb_private::ThreadPlanShouldStopHere::DefaultStepFromHereCallback(), MinidumpFileBuilder::DeleteFile(), lldb_private::platform_android::PlatformAndroidRemoteGDBServer::DeleteForwardPort(), lldb::SBDebugger::DeleteTarget(), EntityPersistentVariable::Dematerialize(), EntityRegister::Dematerialize(), EntitySymbol::Dematerialize(), EntityVariableBase::Dematerialize(), lldb_private::Materializer::Dematerializer::Dematerialize(), lldb_private::ClangASTImporter::DeportDecl(), lldb_private::ClangASTImporter::DeportType(), lldb_private::ValueObject::Dereference(), lldb_private::ProcessDebugger::DestroyProcess(), lldb_private::NativeProcessWindows::Detach(), lldb_private::ProcessDebugger::DetachProcess(), DynamicLoaderPOSIXDYLD::DidAttach(), lldb_private::DynamicLoaderWindowsDYLD::DidAttach(), lldb_private::ProcessTrace::DidAttach(), lldb_private::wasm::DynamicLoaderWasmDYLD::DidAttach(), ProcessKDP::DidAttach(), lldb_private::Process::DidExec(), lldb_private::process_gdb_remote::ProcessGDBRemote::DidFork(), DynamicLoaderPOSIXDYLD::DidLaunch(), lldb_private::DynamicLoaderWindowsDYLD::DidLaunch(), lldb_private::process_gdb_remote::ProcessGDBRemote::DidLaunchOrAttach(), lldb_private::ThreadPlanSingleThreadTimeout::DidPop(), lldb_private::process_gdb_remote::ProcessGDBRemote::DidVFork(), lldb_private::Target::DisableAllBreakpoints(), lldb_private::Target::DisableAllowedBreakpoints(), lldb_private::Target::DisableAllWatchpoints(), lldb_private::Target::DisableBreakpointByID(), lldb_private::process_gdb_remote::ProcessGDBRemote::DisableBreakpointSite(), lldb_private::ProcessWindows::DisableBreakpointSite(), lldb_private::Process::DisableSoftwareBreakpoint(), lldb_private::process_gdb_remote::ProcessGDBRemote::DisableWatchpoint(), lldb_private::Target::DisableWatchpointByID(), lldb::SBFrame::Disassemble(), lldb_private::IRExecutionUnit::DisassembleFunction(), lldb_private::Thread::DiscardPlan(), lldb_private::Thread::DiscardThreadPlans(), lldb_private::Thread::DiscardThreadPlansUpToPlan(), lldb_private::Communication::Disconnect(), lldb_private::ConnectionFileDescriptor::Disconnect(), lldb_private::ConnectionGenericFile::Disconnect(), lldb::SBDebugger::DispatchClientTelemetry(), lldb_private::telemetry::TelemetryManager::DispatchClientTelemetry(), lldb_private::telemetry::ScopedDispatcher< Info >::DispatchNow(), lldb_private::ScriptInterpreterPythonImpl::Locker::DoAcquireLock(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoAllocateMemory(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoAttachToProcessWithID(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoConnectRemote(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoDestroy(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoDetach(), lldb_private::ProcessWindows::DoDetach(), ProcessKDP::DoDetach(), CommandObjectTargetModulesSearchPathsAdd::DoExecute(), lldb_private::LLVMUserExpression::DoExecute(), lldb_private::ScriptInterpreterPythonImpl::Locker::DoFreeLock(), lldb_private::wasm::UnwindWasm::DoGetFrameCount(), DynamicLoaderMacOS::DoInitialImageFetch(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoLaunch(), lldb_private::ScriptedProcess::DoLaunch(), ProcessMachCore::DoLoadCore(), lldb_private::ScriptedThreadPlan::DoPlanExplainsStop(), lldb_private::ThreadPlanCallFunction::DoPlanExplainsStop(), lldb_private::ThreadPlanNull::DoPlanExplainsStop(), lldb_private::ThreadPlanSingleThreadTimeout::DoPlanExplainsStop(), lldb_private::ThreadPlanStepInRange::DoPlanExplainsStop(), lldb_private::ThreadPlanStepOverBreakpoint::DoPlanExplainsStop(), lldb_private::ThreadPlanStepOverRange::DoPlanExplainsStop(), lldb_private::ClangExpressionParser::DoPrepareForExecution(), lldb_private::process_linux::NativeRegisterContextLinux::DoReadRegisterValue(), lldb_private::trace_intel_pt::TraceIntelPT::DoRefreshLiveProcessState(), lldb_private::NativeThreadWindows::DoResume(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoResume(), lldb_private::ProcessWindows::DoResume(), lldb_private::ScriptedProcess::DoResume(), lldb_private::TargetThreadWindows::DoResume(), ProcessKDP::DoResume(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoSignal(), lldb_private::process_linux::NativeProcessLinux::DoStopIDBumped(), lldb_private::ThreadPlanCallFunction::DoTakedown(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoUpdateThreadList(), lldb_private::ProcessWindows::DoUpdateThreadList(), ProcessKDP::DoUpdateThreadList(), lldb_private::ThreadPlanStepInRange::DoWillResume(), lldb_private::ThreadPlanStepOverRange::DoWillResume(), lldb_private::SymbolLocatorDebugSymbols::DownloadObjectAndSymbolFile(), lldb_private::platform_android::PlatformAndroid::DownloadSymbolFile(), lldb_private::process_linux::NativeRegisterContextLinux::DoWriteRegisterValue(), SymbolFilePDB::DumpClangAST(), lldb_private::FormatEntity::Formatter::DumpValue(), lldb_private::EmulateInstructionPPC64::EmulateADDI(), lldb_private::EmulateInstructionPPC64::EmulateLD(), lldb_private::EmulateInstructionPPC64::EmulateMFSPR(), lldb_private::EmulateInstructionPPC64::EmulateOR(), lldb_private::EmulateInstructionPPC64::EmulateSTD(), lldb_private::Target::EnableAllBreakpoints(), lldb_private::Target::EnableAllowedBreakpoints(), lldb_private::Target::EnableAllWatchpoints(), lldb_private::Target::EnableBreakpointByID(), lldb_private::process_gdb_remote::ProcessGDBRemote::EnableBreakpointSite(), lldb_private::ProcessWindows::EnableBreakpointSite(), lldb_private::StructuredDataDarwinLog::EnableNow(), lldb_private::NativeProcessProtocol::EnableSoftwareBreakpoint(), lldb_private::Process::EnableSoftwareBreakpoint(), lldb_private::process_gdb_remote::ProcessGDBRemote::EnableWatchpoint(), lldb_private::Target::EnableWatchpointByID(), DynamicLoaderPOSIXDYLD::EntryBreakpointHit(), lldb_private::ScriptedInterface::ErrorWithMessage(), lldb_private::DWARFExpression::Evaluate(), lldb_private::UserExpression::Evaluate(), lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::EvaluateExpression(), lldb::SBTarget::EvaluateExpression(), lldb_private::Target::EvaluateExpression(), lldb_private::FunctionCaller::ExecuteFunction(), ExpandIndexedExpression(), lldb_private::plugin::dwarf::DWARFDebugAranges::extract(), lldb_private::PlatformDarwin::ExtractCrashInfoAnnotations(), ExtractDataMemberLocation(), ExtractLibcxxStringInfo(), FailExceptionParsing(), lldb_private::SyntheticStackFrameList::FetchFramesUpTo(), lldb_private::FunctionCaller::FetchFunctionResults(), lldb_private::process_gdb_remote::ThreadGDBRemote::FetchThreadExtendedInfo(), lldb_private::ClassDescriptorV2::iVarsStorage::fill(), lldb_private::ClangASTSource::FillNamespaceMap(), lldb_private::BreakpointResolverFileLine::FilterContexts(), lldb_private::Target::FinalizeFileActions(), lldb_private::LLVMUserExpression::FinalizeJITExecution(), lldb::SBTarget::FindBreakpointsByName(), lldb_private::PlatformDarwin::FindBundleBinaryInExecSearchPaths(), lldb_private::SupportFileList::FindCompatibleIndex(), lldb_private::ClangASTSource::FindCompleteType(), lldb_private::ClangASTSource::FindDeclInModules(), lldb_private::ClangASTSource::FindDeclInObjCRuntime(), lldb_private::AppleObjCDeclVendor::FindDecls(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindDefinitionDIE(), lldb_private::ClangASTSource::FindExternalLexicalDecls(), lldb_private::ClangASTSource::FindExternalVisibleDecls(), lldb_private::ClangASTSource::FindExternalVisibleDecls(), lldb_private::ClangExpressionDeclMap::FindExternalVisibleDecls(), lldb_private::ClangExpressionDeclMap::FindExternalVisibleDecls(), lldb_private::AppleObjCExternalASTSource::FindExternalVisibleDeclsByName(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindFunctions(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindFunctions(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindGlobalVariables(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindGlobalVariables(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindNamespace(), SymbolFilePDB::FindNamespace(), lldb_private::Listener::FindNextEventInternal(), lldb_private::ClangASTSource::FindObjCMethodDecls(), lldb_private::ClangASTSource::FindObjCMethodDeclsWithOrigin(), lldb_private::ClangASTSource::FindObjCPropertyAndIvarDecls(), lldb_private::ClangASTSource::FindObjCPropertyAndIvarDeclsWithOrigin(), lldb::SBFrame::FindRegister(), lldb_private::IRExecutionUnit::FindSymbol(), lldb_private::DynamicLoaderDarwin::FindTargetModuleForImageInfo(), lldb_private::plugin::dwarf::SymbolFileDWARF::FindTypes(), lldb::SBFrame::FindValue(), lldb::SBFrame::FindValue(), lldb::SBFrame::FindVariable(), lldb::SBFrame::FindVariable(), lldb_private::AppleObjCDeclVendor::FinishDecl(), lldb_private::NativeProcessProtocol::FixupBreakpointPCAsNeeded(), ForEachFormatterInModule(), lldb_private::ClangASTImporter::ForgetDestination(), lldb_private::ClangASTImporter::ForgetSource(), lldb_private::FormatEntity::Formatter::Format(), lldb_private::TypeFormatImpl_Format::FormatObject(), ForwardPortWithAdb(), lldb_private::ThreadPlanStepInRange::FrameMatchesAvoidCriteria(), lldb_private::IRMemoryMap::Free(), lldb_private::AllocatedBlock::FreeBlock(), lldb_private::RichManglingContext::FromItaniumName(), lldb_private::BytecodeSyntheticChildren::FrontEnd::FrontEnd(), lldb_private::CPlusPlusLanguage::GenerateAlternateFunctionManglings(), lldb_private::FormatManager::Get(), lldb_private::TypeCategoryMap::Get(), GetAbortLocation(), lldb_private::RegisterContextUnwind::GetAbstractRegisterLocation(), DYLDRendezvous::GetAction(), ObjectFileMachO::GetAddressableBits(), lldb_private::minidump::MinidumpParser::GetArchitecture(), lldb_private::ArchitectureArm::GetArchitectureUnwindPlan(), lldb_private::telemetry::GetAsNanosec(), GetAssertLocation(), lldb_private::Process::GetAsyncProfileData(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetAuxvData(), lldb::SBFrame::GetBlock(), lldb_private::ArchitectureMips::GetBreakableLoadAddress(), lldb_private::RISCVSingleStepBreakpointLocationsPredictor::GetBreakpointLocations(), lldb_private::TypeSystemClang::GetBuiltinTypeForDWARFEncodingAndBitSize(), lldb_private::FormatManager::GetCached(), lldb_private::DataFileCache::GetCachedData(), lldb_private::Platform::GetCachedSharedModule(), lldb_private::Function::GetCallEdges(), lldb_private::IndirectCallEdge::GetCallee(), lldb::SBFrame::GetCFA(), lldb_private::DWARFCallFrameInfo::GetCFIData(), lldb_private::BytecodeSyntheticChildren::FrontEnd::GetChildAtIndex(), lldb_private::ValueObjectSynthetic::GetChildAtIndex(), GetClangResourceDir(), lldb_private::ValueObjectRegister::GetCompilerTypeImpl(), lldb::SBFrame::GetCompileUnit(), ObjectFileMachO::GetCorefileAllImageInfos(), ObjectFileMachO::GetCorefileMainBinaryInfo(), ObjectFileMachO::GetCorefileProcessMetadata(), ObjectFileMachO::GetCorefileThreadExtraInfos(), lldb::SBThread::GetCurrentException(), lldb::SBThread::GetCurrentExceptionBacktrace(), lldb_private::StackFrameList::GetCurrentInlinedDepth(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetCurrentProcessAndThreadIDs(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetCurrentProcessInfo(), lldb_private::AppleGetQueuesHandler::GetCurrentQueues(), GetDebugserverPath(), SymbolFilePDB::GetDeclContextContainingUID(), SymbolFilePDB::GetDeclContextForUID(), SymbolFilePDB::GetDeclForUID(), lldb::SBFrame::GetDescription(), lldb::SBThread::GetDescription(), lldb_private::ScriptedThreadPlan::GetDescription(), lldb::SBThread::GetDescriptionWithFormat(), lldb::SBFrame::GetDisplayFunctionName(), GetDLangDemangledStr(), lldb::SBDebugger::GetDummyTarget(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDWARFParser(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwoSymbolFileForCompileUnit(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwpSymbolFile(), GetELFProcessCPUType(), lldb_private::Listener::GetEventInternal(), lldb_private::Process::GetEventsPrivate(), GetExePathAndArch(), lldb::SBThread::GetExtendedBacktraceOriginatingIndexID(), lldb::SBThread::GetExtendedBacktraceThread(), lldb_private::platform_android::PlatformAndroid::GetFile(), lldb_private::SourceManager::GetFile(), PlatformPOSIX::GetFile(), GetFileForModule(), lldb_private::PlatformRemoteDarwinDevice::GetFileInSDK(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::GetFilePermissions(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo::GetFileRangeMap(), lldb_private::minidump::MinidumpParser::GetFilteredModuleList(), lldb_private::ScratchTypeSystemClang::GetForTarget(), lldb::SBFrame::GetFP(), lldb::SBThread::GetFrameAtIndex(), lldb_private::StackFrameList::GetFrameAtIndex(), lldb::SBFrame::GetFrameBlock(), lldb::SBFrame::GetFrameID(), lldb::SBThread::GetFrames(), lldb::SBFrame::GetFunction(), lldb::SBFrame::GetFunctionName(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetGlobalAranges(), lldb_private::NativeRegisterContextDBReg::GetHardwareBreakHitIndex(), lldb_private::NativeProcessProtocol::GetHardwareDebugSupportInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetHostInfo(), ObjectFileMachO::GetIdentifierString(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetImageInfoAddress(), lldb::SBThread::GetIndexID(), lldb_private::BytecodeSyntheticChildren::FrontEnd::GetIndexOfChildWithName(), lldb::SBThread::GetInfoItemByPathAsString(), lldb_private::ThreadPlanAssemblyTracer::GetIntPointerType(), GetItaniumDemangledStr(), lldb_private::AppleGetItemInfoHandler::GetItemInfo(), GetJSONThreadsInfo(), lldb::SBFrame::GetLanguageSpecificData(), lldb_private::UnwindPlan::GetLastRow(), lldb::SBFrame::GetLineEntry(), ObjectFileMachO::GetLLDBSharedCacheUUID(), lldb_private::CallEdge::GetLoadAddress(), lldb_private::ScriptedProcess::GetLoadedDynamicLibrariesInfos(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetLoadedModuleList(), lldb_private::Breakpoint::BreakpointEventData::GetLogChannel(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetMaxMemorySize(), lldb_private::ProcessDebugger::GetMemoryRegionInfo(), lldb_private::ClassDescriptorV2::GetMethodList(), lldb::SBFrame::GetModule(), GetModuleConfig(), lldb_private::PlatformDarwin::GetModuleFromSharedCaches(), lldb_private::minidump::MinidumpParser::GetModuleList(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::GetModuleSpec(), lldb_private::process_gdb_remote::ProcessGDBRemote::GetModuleSpec(), lldb_private::ObjectFileJSON::GetModuleSpecifications(), ObjectFileCOFF::GetModuleSpecifications(), ObjectFileELF::GetModuleSpecifications(), ObjectFilePECOFF::GetModuleSpecifications(), GetModuleSpecInfoFromUUIDDictionary(), GetMSVCDemangledStr(), lldb::SBThread::GetName(), lldb_private::process_freebsd::NativeThreadFreeBSD::GetName(), lldb_private::process_netbsd::NativeThreadNetBSD::GetName(), lldb_private::TargetThreadWindows::GetName(), GetNetBSDProcessCPUType(), UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly(), lldb_private::ValueObject::GetNumChildrenIgnoringErrors(), lldb::SBThread::GetNumFrames(), lldb_private::UnwindLLDB::GetOneMoreFrame(), lldb_private::breakpad::SymbolFileBreakpad::GetOrCreateFunction(), lldb_private::minidump::ProcessMinidump::GetOrCreateModule(), lldb_private::Target::GetOrCreateModule(), lldb_private::SymbolContext::GetParentOfInlinedScope(), lldb::SBFrame::GetPC(), lldb_private::NativeRegisterContext::GetPC(), lldb::SBFrame::GetPCAddress(), SymbolFilePDB::GetPDBAstParser(), lldb_private::AppleGetPendingItemsHandler::GetPendingItems(), lldb_private::Target::GetPersistentExpressionStateForLanguage(), lldb_private::ScriptedThreadPlan::GetPlanRunState(), lldb_private::ThreadPlanNull::GetPlanRunState(), lldb_private::TypeSystemClang::GetPointerByteSize(), lldb::SBThread::GetProcess(), ObjectFileMachO::GetProcessSharedCacheUUID(), getProcFile(), getProcFile(), getProcFile(), lldb::SBDebugger::GetPrompt(), lldb::SBThread::GetQueue(), lldb::SBThread::GetQueueID(), lldb::SBThread::GetQueueName(), lldb::SBFrame::GetRegisters(), GetRegistersAsJSON(), lldb_private::IRExecutionUnit::GetRemoteAddressForLocal(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetRemoteQSupported(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::GetRemoteWorkingDirectory(), GetResponseError(), ABISysV_ppc64::GetReturnValueObjectSimple(), lldb_private::UnwindPlan::GetRowAtIndex(), lldb_private::IRExecutionUnit::GetRunnableInfo(), GetRustV0DemangledStr(), lldb_private::Target::GetScratchTypeSystems(), lldb_private::platform_android::PlatformAndroid::GetSdkVersion(), ObjectFileELF::GetSectionHeaderInfo(), lldb::SBThread::GetSelectedFrame(), lldb::SBDebugger::GetSelectedPlatform(), lldb::SBDebugger::GetSelectedTarget(), lldb_private::ModuleList::GetSharedModule(), lldb_private::PlatformRemoteDarwinDevice::GetSharedModule(), lldb_private::PlatformDarwinDevice::GetSharedModuleWithLocalCache(), lldb::SBThread::GetSiginfo(), lldb_private::process_freebsd::NativeThreadFreeBSD::GetSiginfo(), lldb::SBFrame::GetSP(), lldb_private::Thread::GetStackFrameList(), lldb_private::DynamicLoaderDarwin::GetStartAddress(), lldb_private::Process::GetStateChangedEvents(), lldb_private::Process::GetStateChangedEventsPrivate(), lldb_private::IRExecutionUnit::GetStaticInitializers(), lldb::SBThread::GetStatus(), lldb_private::Thread::GetStatus(), GetStatusInfo(), lldb_private::Process::GetSTDERR(), lldb_private::Process::GetSTDOUT(), lldb_private::AppleObjCTrampolineHandler::GetStepThroughDispatchPlan(), DynamicLoaderDarwinKernel::GetStepThroughTrampolinePlan(), DynamicLoaderFreeBSDKernel::GetStepThroughTrampolinePlan(), lldb_private::DynamicLoaderDarwin::GetStepThroughTrampolinePlan(), lldb::SBThread::GetStopDescription(), lldb::SBThread::GetStopDescription(), lldb::SBThread::GetStopReason(), lldb_private::NativeThreadWindows::GetStopReason(), lldb_private::process_freebsd::NativeThreadFreeBSD::GetStopReason(), lldb_private::process_linux::NativeThreadLinux::GetStopReason(), lldb_private::process_netbsd::NativeThreadNetBSD::GetStopReason(), lldb::SBThread::GetStopReasonDataAtIndex(), lldb::SBThread::GetStopReasonDataCount(), lldb::SBThread::GetStopReasonExtendedBacktraces(), lldb::SBThread::GetStopReasonExtendedInfoAsJSON(), lldb::SBThread::GetStopReturnValue(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::GetSupportedStructuredDataPlugins(), lldb::SBFrame::GetSymbol(), lldb_private::IRExecutionUnit::MemoryManager::GetSymbolAddressAndPresence(), lldb::SBFrame::GetSymbolContext(), lldb_private::PlatformRemoteDarwinDevice::GetSymbolFile(), lldb_private::ClangExpressionSourceCode::GetText(), lldb::SBFrame::GetThread(), lldb_private::minidump::MinidumpParser::GetThreadContextWow64(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::GetThreadFromSuffix(), lldb::SBThread::GetThreadID(), lldb_private::AppleGetThreadItemInfoHandler::GetThreadItemInfo(), DynamicLoaderHexagonDYLD::GetThreadLocalData(), DynamicLoaderPOSIXDYLD::GetThreadLocalData(), lldb_private::FunctionCaller::GetThreadPlanToCallFunction(), lldb_private::minidump::MinidumpParser::GetThreads(), lldb_private::Process::GetThreadStatus(), lldb_private::TreeSitterHighlighter::GetTSState(), lldb_private::ItaniumABILanguageRuntime::GetTypeInfo(), lldb_private::plugin::dwarf::AppleDWARFIndex::GetTypes(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetTypeUnitSupportFiles(), lldb_private::CompactUnwindInfo::GetUnwindPlan(), lldb_private::CompilerType::GetValueAsScalar(), lldb_private::Value::GetValueByteSize(), lldb::SBFrame::GetValueForVariablePath(), lldb::SBFrame::GetValueForVariablePath(), lldb::SBFrame::GetVariables(), lldb::SBFrame::GetVariables(), lldb::SBFrame::GetVariables(), lldb_private::ClangExpressionDeclMap::GetVariableValue(), lldb_private::NativeRegisterContextDBReg::GetWatchpointAddress(), lldb_private::NativeRegisterContextDBReg::GetWatchpointHitAddress(), lldb_private::NativeRegisterContextDBReg::GetWatchpointHitIndex(), lldb_private::NativeRegisterContextDBReg_arm64::GetWatchpointSize(), lldb_private::NativeRegisterContextDBReg_arm::GetWatchpointSize(), lldb_private::NativeRegisterContextDBReg_loongarch::GetWatchpointSize(), lldb_private::HostInfoMacOSX::GetXcodeContentsDirectory(), GetXcodeSDK(), lldb::SBFrame::GuessLanguage(), lldb_private::StackFrame::GuessValueForAddress(), lldb_private::ProcessDebugger::HaltProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle__M(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle__m(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_A(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_C(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_c(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_D(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_g(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_H(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_I(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_interrupt(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_jThreadsInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_k(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_M(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_memory_read(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_P(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_p(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::Handle_qLaunchGDBServer(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qMemoryRegionInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qMemoryRegionInfoSupported(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_QMemTags(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qMemTags(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_QNonStop(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_QRestoreRegisterState(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_QSaveRegisterState(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_qThreadStopInfo(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qUserName(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_s(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_vAttach(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_vAttachOrWait(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_vAttachWait(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_vCont(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_vRun(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_Z(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::Handle_z(), lldb_private::StructuredDataDarwinLog::HandleArrivalOfStructuredData(), lldb_private::RISCVSingleStepBreakpointLocationsPredictor::HandleAtomicSequence(), lldb_private::CommandInterpreter::HandleCommand(), lldb_private::DebuggerThread::HandleCreateProcessEvent(), lldb_private::DebuggerThread::HandleCreateThreadEvent(), ClangDiagnosticManagerAdapter::HandleDiagnostic(), lldb_private::ThreadPlanSingleThreadTimeout::HandleEvent(), lldb_private::DebuggerThread::HandleExceptionEvent(), lldb_private::DebuggerThread::HandleExitProcessEvent(), lldb_private::DebuggerThread::HandleExitThreadEvent(), lldb_private::CPlusPlusLanguage::HandleFrameFormatVariable(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::HandleInferiorState_Exited(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::HandleInferiorState_Stopped(), lldb_private::DebuggerThread::HandleLoadDllEvent(), lldb_private::Process::HandlePrivateEvent(), lldb_private::DebuggerThread::HandleRipEvent(), HandleStoppedEvent(), lldb_private::ThreadPlanSingleThreadTimeout::HandleTimeout(), lldb_private::DebuggerThread::HandleUnloadDllEvent(), lldb_private::Broadcaster::BroadcasterImpl::HijackBroadcaster(), lldb_private::HistoryThread::HistoryThread(), lldb_private::ThreadPlanStepThrough::HitOurBackstopBreakpoint(), lldb_private::Target::IgnoreAllWatchpoints(), lldb_private::Target::IgnoreWatchpointByID(), lldb_private::ClangASTImporter::ASTImporterDelegate::ImportDefinitionTo(), lldb_private::ClangASTImporter::ASTImporterDelegate::Imported(), lldb_private::ClangASTImporter::ASTImporterDelegate::ImportImpl(), lldb_private::ClangASTImporter::importRecordLayoutFromOrigin(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexUnit(), lldb_private::StructuredDataDarwinLog::InitCompletionHookCallback(), lldb_private::SystemInitializerFull::Initialize(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::InitializeDelegate(), DynamicLoaderMacOSXDYLD::InitializeFromAllImageInfos(), lldb_private::RegisterContextUnwind::InitializeNonZerothFrame(), lldb_private::npdb::SymbolFileNativePDB::InitializeObject(), lldb_private::plugin::dwarf::SymbolFileDWARF::InitializeObject(), lldb_private::SymbolFileCTF::InitializeObject(), lldb_private::RegisterContextUnwind::InitializeZerothFrame(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::InitOSO(), lldb_private::ThreadPlanStepRange::InRange(), lldb_private::FunctionCaller::InsertFunction(), ObjcObjectChecker::InspectInstruction(), lldb_private::Platform::Install(), InstrumentationBoundsSafetyStopInfo::InstrumentationBoundsSafetyStopInfo(), lldb_private::instrumentation::Instrumenter::Instrumenter(), lldb_private::FormatterBytecode::Interpret(), lldb_private::process_linux::NativeProcessLinux::Interrupt(), lldb_private::ThreadPlanShouldStopHere::InvokeShouldStopHereCallback(), lldb::SBFrame::IsArtificial(), lldb::SBFrame::IsHidden(), lldb::SBFrame::IsInlined(), lldb_private::ScriptedThreadPlan::IsPlanStale(), lldb_private::ThreadPlanStepInstruction::IsPlanStale(), lldb_private::ThreadPlanStepRange::IsPlanStale(), lldb::SBThread::IsStopped(), lldb::SBThread::IsSuspended(), lldb::SBFrame::IsSynthetic(), lldb_private::ThreadPlanSingleThreadTimeout::IsTimeoutAsyncInterrupt(), JITLoaderGDB::JITDebugBreakpointHit(), Kernel32::Kernel32(), lldb_private::process_aix::NativeProcessAIX::Kill(), lldb_private::process_freebsd::NativeProcessFreeBSD::Kill(), lldb_private::process_linux::NativeProcessLinux::Kill(), lldb_private::process_netbsd::NativeProcessNetBSD::Kill(), lldb_private::Platform::KillProcess(), lldb_private::process_aix::NativeProcessAIX::Manager::Launch(), lldb_private::process_freebsd::NativeProcessFreeBSD::Manager::Launch(), lldb_private::process_linux::NativeProcessLinux::Manager::Launch(), lldb_private::process_netbsd::NativeProcessNetBSD::Manager::Launch(), lldb_private::Target::Launch(), lldb_private::process_gdb_remote::ProcessGDBRemote::LaunchAndConnectToDebugserver(), lldb_private::platform_android::PlatformAndroidRemoteGDBServer::LaunchGDBServer(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerPlatform::LaunchGDBServer(), lldb_private::MonitoringProcessLauncher::LaunchProcess(), lldb_private::Platform::LaunchProcess(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::LaunchProcess(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::LaunchProcess(), lldb_private::ProcessDebugger::LaunchProcess(), LaunchProcessPosixSpawn(), LaunchProcessXPC(), lldb_private::TCPSocket::Listen(), lldb_private::Listener::Listener(), DynamicLoaderHexagonDYLD::LoadAllCurrentModules(), DynamicLoaderPOSIXDYLD::LoadAllCurrentModules(), ProcessMachCore::LoadBinariesAndSetDYLD(), ProcessMachCore::LoadBinariesViaExhaustiveSearch(), ProcessMachCore::LoadBinariesViaMetadata(), ProcessMachCore::LoadBinaryViaLowmemUUID(), lldb_private::DynamicLoader::LoadBinaryWithUUIDAndAddress(), lldb_private::Process::LoadCore(), ObjectFileMachO::LoadCoreFileImages(), LoadFormattersForModule(), DynamicLoaderDarwinKernel::KextImageInfo::LoadImageUsingMemoryModule(), DynamicLoaderFreeBSDKernel::KModImageInfo::LoadImageUsingMemoryModule(), DynamicLoaderPOSIXDYLD::LoadInterpreterModule(), DynamicLoaderFreeBSDKernel::LoadKernelModules(), loadMatchingPDBFile(), lldb_private::DynamicLoader::LoadModuleAtAddress(), lldb_private::wasm::DynamicLoaderWasmDYLD::LoadModuleAtAddress(), LoadPluginCallback(), LoadTypeSummariesForModule(), DynamicLoaderPOSIXDYLD::LoadVDSO(), LocateDSYMInVincinityOfExecutable(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableObjectFile(), LocateMacOSXFilesUsingDebugSymbols(), lldb_private::process_gdb_remote::GDBRemoteClientBase::ContinueLock::lock(), LogBeforeReturn(), LogConfigError(), lldb_private::TypeSystemClang::LogCreation(), lldb_private::ThreadPlanStepThrough::LookForPlanToStepThroughFromCurrentPC(), lldb_private::plugin::dwarf::DWARFDIE::LookupDeepestBlock(), lldb_private::ClangExpressionDeclMap::LookupInModulesDeclVendor(), lldb_private::ClangASTSource::LookupInNamespace(), lldb_private::ClangExpressionDeclMap::LookUpLldbClass(), lldb_private::ClangExpressionDeclMap::LookUpLldbObjCClass(), EntityPersistentVariable::MakeAllocation(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::MakeDirectory(), lldb_private::ABI::MakeMCRegisterInfo(), lldb_private::IRMemoryMap::Malloc(), map_shared_cache_binary_segments(), DWARFASTParserClang::MapDeclDIEToDefDIE(), lldb_private::Process::MapSupportedStructuredDataPlugins(), lldb_private::ClangASTImporter::ASTImporterDelegate::MarkDeclImported(), EntityPersistentVariable::Materialize(), EntityRegister::Materialize(), EntitySymbol::Materialize(), EntityVariableBase::Materialize(), lldb_private::Materializer::Materialize(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::MaybeCloseInferiorTerminalConnection(), MaybeLogLaunchInfo(), lldb_private::plugin::dwarf::DebugNamesDWARFIndex::MaybeLogLookupError(), lldb_private::process_linux::NativeThreadLinux::MaybeLogStateChange(), lldb_private::ASTResultSynthesizer::MaybeRecordPersistentType(), lldb_private::Module::MergeArchitecture(), lldb_private::Target::MergeArchitecture(), lldb_private::ScriptedThreadPlan::MischiefManaged(), lldb_private::ThreadPlanCallFunction::MischiefManaged(), lldb_private::ThreadPlanCallUserExpression::MischiefManaged(), lldb_private::ThreadPlanNull::MischiefManaged(), lldb_private::ThreadPlanRunToAddress::MischiefManaged(), lldb_private::ThreadPlanSingleThreadTimeout::MischiefManaged(), lldb_private::ThreadPlanStepInstruction::MischiefManaged(), lldb_private::ThreadPlanStepOut::MischiefManaged(), lldb_private::ThreadPlanStepOverBreakpoint::MischiefManaged(), lldb_private::ThreadPlanStepRange::MischiefManaged(), lldb_private::ThreadPlanStepThrough::MischiefManaged(), lldb_private::ThreadPlanStepUntil::MischiefManaged(), lldb_private::Module::Module(), lldb_private::Module::Module(), lldb_private::Breakpoint::ModuleReplaced(), lldb_private::Breakpoint::ModulesChanged(), lldb_private::StructuredDataDarwinLog::ModulesDidLoad(), lldb_private::process_linux::NativeProcessLinux::MonitorBreakpoint(), lldb_private::process_linux::NativeProcessLinux::MonitorCallback(), MonitorChildProcessThreadFunction(), lldb_private::process_freebsd::NativeProcessFreeBSD::MonitorClone(), lldb_private::process_linux::NativeProcessLinux::MonitorClone(), lldb_private::process_netbsd::NativeProcessNetBSD::MonitorClone(), lldb_private::process_gdb_remote::ProcessGDBRemote::MonitorDebugserverProcess(), lldb_private::process_freebsd::NativeProcessFreeBSD::MonitorExited(), lldb_private::process_netbsd::NativeProcessNetBSD::MonitorExited(), lldb_private::ProcessLaunchInfo::MonitorProcess(), lldb_private::process_freebsd::NativeProcessFreeBSD::MonitorSignal(), lldb_private::process_linux::NativeProcessLinux::MonitorSignal(), lldb_private::process_netbsd::NativeProcessNetBSD::MonitorSignal(), lldb_private::process_freebsd::NativeProcessFreeBSD::MonitorSIGTRAP(), lldb_private::process_linux::NativeProcessLinux::MonitorSIGTRAP(), lldb_private::process_netbsd::NativeProcessNetBSD::MonitorSIGTRAP(), lldb_private::process_linux::NativeProcessLinux::MonitorTrace(), lldb_private::process_linux::NativeProcessLinux::MonitorWatchpoint(), lldb_private::process_gdb_remote::ProcessGDBRemote::NewThreadNotifyBreakpointHit(), lldb_private::ThreadPlanStepRange::NextRangeBreakpointExplainsStop(), lldb_private::ProcessLaunchInfo::NoOpMonitorCallback(), lldb_private::ReportRetriever::NotifyBreakpointHit(), lldb_private::NativeProcessProtocol::NotifyDidExec(), lldb_private::process_linux::NativeProcessLinux::NotifyTracersOfNewThread(), lldb_private::process_linux::NativeProcessLinux::NotifyTracersOfThreadDestroyed(), lldb_private::formatters::NSNumberSummaryProvider(), NullDiagnosticConsumer::NullDiagnosticConsumer(), lldb_private::NativeRegisterContextDBReg::NumSupportedHardwareBreakpoints(), lldb_private::NativeRegisterContextDBReg::NumSupportedHardwareWatchpoints(), lldb_private::ObjectFile::ObjectFile(), lldb_private::ObjectFile::ObjectFile(), lldb_private::NativeProcessWindows::OnDebugException(), lldb_private::ProcessDebugger::OnDebugException(), lldb_private::ProcessWindows::OnDebugException(), lldb_private::NativeProcessWindows::OnDebuggerConnected(), lldb_private::ProcessWindows::OnDebuggerConnected(), lldb_private::ProcessDebugger::OnDebuggerError(), lldb_private::ProcessWindows::OnDebuggerError(), lldb_private::NativeProcessWindows::OnExitProcess(), lldb_private::ProcessWindows::OnExitProcess(), lldb_private::ConnectionFileDescriptor::OpenCommandPipe(), lldb_private::PseudoConsole::OpenPseudoConsole(), lldb_private::Host::OpenURL(), lldb::SBFrame::operator bool(), lldb::SBThread::operator bool(), lldb_private::ExecutionContextRef::operator=(), DeclContextOverride::Override(), ELFNote::Parse(), lldb_private::ClangUserExpression::Parse(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseAndAppendGlobalVariable(), sddarwinlog_private::ParseAutoEnableOptions(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseBlocksRecursive(), lldb_private::breakpad::SymbolFileBreakpad::ParseCFIUnwindRow(), SymbolFilePDB::ParseCompileUnitFunctionForPDBFunc(), lldb_private::breakpad::SymbolFileBreakpad::ParseCUData(), DWARFASTParserClang::ParseCXXMethod(), SymbolFilePDB::ParseDeclsForContext(), ObjectFilePECOFF::ParseDependentModules(), lldb_private::plugin::dwarf::DWARFUnit::ParseDWARFLocationList(), DWARFASTParserClang::ParseEnum(), lldb_private::DWARFCallFrameInfo::ParseFDE(), lldb_private::breakpad::SymbolFileBreakpad::ParseFileRecords(), ParseFreeBSDPrPsInfo(), ParseFreeBSDPrStatus(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseFunction(), lldb_private::SymbolFileCTF::ParseFunctions(), lldb_private::SymbolFileCTF::ParseHeader(), lldb_private::breakpad::SymbolFileBreakpad::ParseInlineOriginRecords(), DynamicLoaderDarwinKernel::ParseKextSummaries(), DynamicLoaderFreeBSDKernel::ParseKmods(), ParseLLVMLineTable(), ParseLLVMLineTablePrologue(), lldb_private::SymbolFileCTF::ParseObjects(), InstructionLLVMC::ParseOperands(), ObjectFileELF::ParseRISCVAttributes(), ParseStructuredDataPacket(), DWARFASTParserClang::ParseStructureLikeDIE(), DWARFASTParserClang::ParseSubroutine(), lldb_private::DirectCallEdge::ParseSymbolFileAndResolve(), lldb_private::ObjectFileJSON::ParseSymtab(), ObjectFileCOFF::ParseSymtab(), ObjectFileMachO::ParseSymtab(), ObjectFileXCOFF::ParseSymtab(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseType(), DWARFASTParserClang::ParseTypeFromDWARF(), DWARFASTParserClang::ParseTypeModifier(), lldb_private::SymbolFileCTF::ParseTypes(), lldb_private::plugin::dwarf::DWARFDebugInfo::ParseUnitsFor(), lldb_private::breakpad::SymbolFileBreakpad::ParseUnwindData(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariablesForContext(), lldb_private::plugin::dwarf::SymbolFileWasm::ParseVendorDWARFOpcode(), lldb_private::breakpad::SymbolFileBreakpad::ParseWinUnwindPlan(), lldb_private::Process::PeekAtStateChangedEvents(), lldb_private::Process::AttachCompletionHandler::PerformAction(), lldb_private::StopInfoBreakpoint::PerformAction(), lldb_private::StopInfoWatchpoint::PerformAction(), lldb_private::UnwindPlan::PlanValidAtAddress(), lldb_private::Platform::Platform(), lldb_private::Thread::PopPlan(), lldb_private::minidump::MinidumpParser::PopulateMemoryRanges(), lldb_private::process_freebsd::NativeProcessFreeBSD::PopulateMemoryRegionCache(), lldb_private::process_linux::NativeProcessLinux::PopulateMemoryRegionCache(), lldb_private::process_netbsd::NativeProcessNetBSD::PopulateMemoryRegionCache(), SystemRuntimeMacOSX::PopulateQueuesUsingLibBTR(), lldb_private::WatchpointAlgorithms::PowerOf2Watchpoints(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::PrepareStopReplyPacketForThread(), ABIMacOSX_arm64::PrepareTrivialCall(), ABISysV_arm64::PrepareTrivialCall(), ABISysV_loongarch::PrepareTrivialCall(), ABISysV_mips64::PrepareTrivialCall(), ABISysV_mips::PrepareTrivialCall(), ABISysV_ppc64::PrepareTrivialCall(), ABISysV_ppc::PrepareTrivialCall(), ABISysV_s390x::PrepareTrivialCall(), ABISysV_x86_64::PrepareTrivialCall(), ABIWindows_x86_64::PrepareTrivialCall(), PrintDemangledArgumentList(), ProcessFreeBSDKernelCore::PrintUnreadMessage(), lldb_private::ValueObjectPrinter::PrintValueObject(), lldb_private::Broadcaster::BroadcasterImpl::PrivateBroadcastEvent(), lldb_private::Process::PrivateResume(), DynamicLoaderPOSIXDYLD::ProbeEntry(), lldb_private::Process::Process(), lldb_private::process_linux::IntelPTMultiCoreTrace::ProcessDidStop(), lldb_private::process_gdb_remote::ProcessGDBRemote::ProcessGDBRemote(), lldb_private::RichManglingContext::processIPDStrResult(), ObjectFileMachO::ProcessSegmentCommand(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::ProcessStateChanged(), lldb_private::ProcessStructReader::ProcessStructReader(), ProcessVmReadvSupported(), lldb_private::process_linux::IntelPTMultiCoreTrace::ProcessWillResume(), PtraceDisplayBytes(), lldb_private::process_aix::NativeProcessAIX::PtraceWrapper(), lldb_private::process_freebsd::NativeProcessFreeBSD::PtraceWrapper(), lldb_private::process_linux::NativeProcessLinux::PtraceWrapper(), lldb_private::process_netbsd::NativeProcessNetBSD::PtraceWrapper(), lldb_private::ThreadPlanSingleThreadTimeout::PushNewWithTimeout(), lldb_private::Thread::PushPlan(), lldb_private::Process::PushProcessIOHandler(), PushToLinuxGuardedControlStack(), lldb_private::Platform::PutFile(), PlatformPOSIX::PutFile(), lldb_private::python::PythonException::PythonException(), lldb_private::ThreadPlanStepOut::QueueInlinedStepPlan(), lldb_private::ClassDescriptorV2::relative_list_entry_t::Read(), lldb_private::ClassDescriptorV2::relative_list_list_t::Read(), lldb_private::Communication::Read(), lldb_private::ConnectionFileDescriptor::Read(), lldb_private::ConnectionGenericFile::Read(), lldb_private::Socket::Read(), lldb_private::ThreadedCommunication::Read(), lldb_private::process_gdb_remote::GDBRemoteRegisterContext::ReadAllRegisterValues(), JITLoaderGDB::ReadJITDescriptorImpl(), lldb_private::IRMemoryMap::ReadMemory(), lldb_private::process_freebsd::NativeProcessFreeBSD::ReadMemory(), lldb_private::process_linux::NativeProcessLinux::ReadMemory(), lldb_private::process_netbsd::NativeProcessNetBSD::ReadMemory(), lldb_private::ProcessDebugger::ReadMemory(), UnwindAssemblyInstEmulation::ReadMemory(), DynamicLoaderDarwinKernel::KextImageInfo::ReadMemoryModule(), DynamicLoaderFreeBSDKernel::KModImageInfo::ReadMemoryModule(), lldb_private::process_gdb_remote::ProcessGDBRemote::ReadMemoryRanges(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ReadMemoryTags(), lldb_private::Process::ReadModuleFromMemory(), lldb_private::minidump::ProcessMinidump::ReadModuleList(), lldb_private::process_gdb_remote::GDBRemoteCommunication::ReadPacket(), lldb_private::AppleObjCTrampolineHandler::AppleObjCVTables::ReadRegions(), lldb_private::wasm::RegisterContextWasm::ReadRegister(), RegisterContextFreeBSDKernelCore_arm64::ReadRegister(), UnwindAssemblyInstEmulation::ReadRegister(), lldb_private::NativeRegisterContext::ReadRegisterAsUnsigned(), lldb_private::process_gdb_remote::GDBRemoteRegisterContext::ReadRegisterBytes(), lldb_private::ThreadedCommunication::ReadThread(), ReadUnnamedMemoryModule(), MinidumpFileBuilder::ReadWriteMemoryInChunks(), lldb_private::AbortWithPayloadFrameRecognizer::RecognizeFrame(), lldb_private::AssertFrameRecognizer::RecognizeFrame(), lldb_private::VerboseTrapFrameRecognizer::RecognizeFrame(), lldb_private::ASTResultSynthesizer::RecordPersistentDecl(), lldb::SBStream::RedirectToFile(), ObjectFileELF::RefineModuleDetailsFromNote(), lldb_private::Trace::RefreshLiveProcessState(), DynamicLoaderHexagonDYLD::RefreshModules(), lldb_private::ProcessWindows::RefreshStateAfterStop(), lldb_private::ThreadList::RefreshStateAfterStop(), lldb_private::PersistentExpressionState::RegisterExecutionUnit(), lldb_private::Target::RemoveAllBreakpoints(), lldb_private::Target::RemoveAllowedBreakpoints(), lldb_private::Target::RemoveAllWatchpoints(), lldb_private::Target::RemoveBreakpointByID(), DynamicLoaderMacOSXDYLD::RemoveModulesUsingImageInfosAddress(), lldb_private::NativeProcessProtocol::RemoveSoftwareBreakpoint(), lldb_private::process_freebsd::NativeProcessFreeBSD::RemoveThread(), lldb_private::process_netbsd::NativeProcessNetBSD::RemoveThread(), lldb_private::Target::RemoveWatchpointByID(), DynamicLoaderHexagonDYLD::RendezvousBreakpointHit(), DynamicLoaderPOSIXDYLD::RendezvousBreakpointHit(), lldb_private::Debugger::ReportInterruption(), lldb_private::ThreadPlanCallFunction::ReportRegisterState(), lldb_private::process_linux::NativeThreadLinux::RequestStop(), lldb_private::AllocatedBlock::ReserveBlock(), lldb_private::StackFrameList::ResetCurrentInlinedDepth(), DYLDRendezvous::Resolve(), lldb_private::BreakpointLocationList::ResolveAllBreakpointSites(), lldb_private::Type::ResolveCompilerType(), lldb_private::platform_android::AdbClient::ResolveDeviceID(), DynamicLoaderPOSIXDYLD::ResolveExecutableModule(), lldb_private::ScriptedBreakpointPythonInterface::ResolverCallback(), DYLDRendezvous::ResolveRendezvousAddress(), lldb_private::RealpathPrefixes::ResolveSymlinks(), lldb_private::plugin::dwarf::SymbolFileDWARF::ResolveTypeUID(), lldb_private::SymbolFileCTF::ResolveTypeUID(), SymbolFilePDB::ResolveTypeUID(), lldb_private::Broadcaster::BroadcasterImpl::RestoreBroadcaster(), lldb::SBThread::Resume(), lldb_private::NativeProcessWindows::Resume(), lldb_private::Process::Resume(), lldb_private::process_freebsd::NativeProcessFreeBSD::Resume(), lldb_private::process_linux::NativeProcessLinux::Resume(), lldb_private::process_netbsd::NativeProcessNetBSD::Resume(), lldb_private::ThreadPlanSingleThreadTimeout::ResumeFromPrevState(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::ResumeProcess(), lldb_private::Process::ResumeSynchronous(), lldb_private::process_linux::NativeProcessLinux::ResumeThread(), IOHandlerProcessSTDIO::Run(), lldb_private::IOHandlerProcessSTDIOWindows::Run(), lldb_private::IRDynamicChecks::runOnModule(), lldb_private::Process::RunPrivateStateThread(), lldb_private::Target::RunStopHooks(), lldb_private::Process::RunThreadPlan(), lldb::SBThread::SafeToCallFunctions(), ObjectFileMinidump::SaveCore(), lldb_private::RegisterContextUnwind::SavedLocationForRegister(), lldb_private::CommandInterpreter::SaveTranscript(), ScanBracketedRange(), lldb_private::ClangUserExpression::ScanContext(), lldb_private::CompactUnwindInfo::ScanIndex(), lldb_private::AddressResolverFileLine::SearchCallback(), lldb_private::BreakpointResolverAddress::SearchCallback(), lldb_private::BreakpointResolverName::SearchCallback(), lldb_private::ClangExpressionDeclMap::SearchPersistenDecls(), lldb_private::StackFrameList::SelectMostRelevantFrame(), SelectTargetDevice(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendAck(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendContinuePacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendGDBStoppointTypePacket(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServer::SendIllFormedResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendNack(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndReceiveResponseWithOutputSupport(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteClientBase::SendPacketAndWaitForResponseNoLock(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::SendProcessOutput(), lldb_private::process_gdb_remote::GDBRemoteCommunication::SendRawPacketNoLock(), CommunicationKDP::SendRequestAndGetReply(), CommunicationKDP::SendRequestPacketNoLock(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::SendStopReasonForState(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendThreadSpecificPacketAndWaitForResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceGetBinaryData(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceGetState(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceStart(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceStop(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceSupported(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::SendWResponse(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::ServeSymbolLookups(), lldb_private::ArchSpec::SetArchitecture(), lldb_private::Target::SetArchitecture(), lldb_private::DataFileCache::SetCachedData(), lldb_private::Process::SetCodeAddressMask(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::SetContinueThreadID(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::SetCurrentThreadID(), lldb_private::Process::SetDataAddressMask(), lldb_private::Target::SetDefaultArchitecture(), lldb_private::Target::SetExecutableModule(), lldb_private::NativeProcessProtocol::SetExitStatus(), lldb_private::Process::SetExitStatus(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::SetFilePermissions(), lldb_private::ExecutionContextRef::SetFrameSP(), lldb_private::NativeProcessProtocol::SetHardwareBreakpoint(), lldb_private::NativeRegisterContextDBReg::SetHardwareBreakpoint(), lldb_private::NativeRegisterContextDBReg::SetHardwareWatchpoint(), lldb_private::NativeRegisterContextDBReg_x86::SetHardwareWatchpoint(), lldb_private::Process::SetHighmemCodeAddressMask(), lldb_private::Process::SetHighmemDataAddressMask(), lldb_private::Breakpoint::SetIsHardware(), JITLoaderGDB::SetJITBreakpoint(), lldb_private::process_gdb_remote::ProcessGDBRemote::SetLastStopPacket(), lldb_private::ObjectFileJSON::SetLoadAddress(), ObjectFileMachO::SetLoadAddress(), lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint(), lldb::SBFrame::SetPC(), lldb_private::Process::SetPrivateState(), lldb_private::Process::SetProcessExitStatus(), lldb_private::Process::SetPublicState(), lldb_private::DynamicRegisterInfo::SetRegisterInfo(), lldb_private::Platform::SetRemoteWorkingDirectory(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::SetRemoteWorkingDirectory(), DynamicLoaderHexagonDYLD::SetRendezvousBreakpoint(), DynamicLoaderPOSIXDYLD::SetRendezvousBreakpoint(), lldb_private::SectionLoadList::SetSectionLoadAddress(), lldb_private::SectionLoadList::SetSectionUnloaded(), lldb_private::SectionLoadList::SetSectionUnloaded(), lldb::SBThread::SetSelectedFrame(), lldb_private::Thread::SetSelectedFrameByIndexNoisily(), lldb::SBDebugger::SetSelectedPlatform(), lldb::SBDebugger::SetSelectedTarget(), lldb_private::NativeProcessProtocol::SetSoftwareBreakpoint(), lldb_private::Thread::SetStopInfo(), lldb_private::process_linux::NativeThreadLinux::SetStoppedByExec(), lldb_private::process_freebsd::NativeThreadFreeBSD::SetStoppedBySignal(), lldb_private::process_linux::NativeThreadLinux::SetStoppedBySignal(), lldb_private::process_netbsd::NativeThreadNetBSD::SetStoppedBySignal(), lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo(), lldb_private::process_gdb_remote::ProcessGDBRemote::SetThreadStopInfo(), lldb_private::ClangUserExpression::SetupCppModuleImports(), SetupDeclVendor(), lldb_private::AppleObjCTrampolineHandler::SetupDispatchFunction(), lldb_private::AppleGetItemInfoHandler::SetupGetItemInfoFunction(), lldb_private::AppleGetPendingItemsHandler::SetupGetPendingItemsFunction(), lldb_private::AppleGetQueuesHandler::SetupGetQueuesFunction(), lldb_private::AppleGetThreadItemInfoHandler::SetupGetThreadItemInfoFunction(), SetupLangOpts(), SetupModuleHeaderPaths(), lldb_private::ProcessLaunchInfo::SetUpPtyRedirection(), lldb_private::ThreadPlanStepOut::SetupReturnAddress(), SetupTargetOpts(), lldb_private::NativeProcessProtocol::SetWatchpoint(), lldb_private::Platform::SetWorkingDirectory(), lldb_private::Process::ShouldBroadcastEvent(), lldb_private::Thread::ShouldReportRun(), lldb_private::ThreadList::ShouldReportRun(), lldb_private::Thread::ShouldReportStop(), lldb_private::ThreadList::ShouldReportStop(), lldb_private::ThreadPlan::ShouldReportStop(), lldb_private::ThreadPlanStepRange::ShouldReportStop(), lldb_private::AppleThreadPlanStepThroughDirectDispatch::ShouldStop(), lldb_private::AppleThreadPlanStepThroughObjCTrampoline::ShouldStop(), lldb_private::BreakpointLocation::ShouldStop(), lldb_private::Process::ProcessEventData::ShouldStop(), lldb_private::ScriptedThreadPlan::ShouldStop(), lldb_private::Thread::ShouldStop(), lldb_private::ThreadList::ShouldStop(), lldb_private::ThreadPlanBase::ShouldStop(), lldb_private::ThreadPlanNull::ShouldStop(), lldb_private::ThreadPlanStepInRange::ShouldStop(), lldb_private::ThreadPlanStepInstruction::ShouldStop(), lldb_private::ThreadPlanStepOverRange::ShouldStop(), lldb_private::StopInfoBreakpoint::ShouldStopSynchronous(), lldb_private::StopInfoWatchpoint::ShouldStopSynchronous(), lldb_private::process_freebsd::NativeProcessFreeBSD::SigchldHandler(), lldb_private::process_linux::NativeProcessLinux::Manager::SigchldHandler(), lldb_private::process_netbsd::NativeProcessNetBSD::SigchldHandler(), lldb_private::process_linux::NativeProcessLinux::Signal(), lldb_private::process_linux::NativeProcessLinux::SignalIfAllThreadsStopped(), lldb_private::mcp::ProtocolServerMCP::Start(), lldb_private::process_linux::IntelPTSingleBufferTrace::Start(), lldb_private::process_gdb_remote::ProcessGDBRemote::StartAsyncThread(), ProcessKDP::StartAsyncThread(), lldb_private::process_gdb_remote::GDBRemoteCommunication::StartDebugserverProcess(), lldb_private::Debugger::StartEventHandlerThread(), lldb_private::Debugger::StartIOHandlerThread(), lldb_private::Listener::StartListeningForEvents(), lldb_private::Listener::StartListeningForEvents(), lldb_private::process_gdb_remote::ProcessGDBRemote::StartNoticingNewThreads(), lldb_private::Process::StartPrivateStateThread(), lldb_private::ThreadedCommunication::StartReadThread(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::StartSTDIOForwarding(), lldb_private::Process::PrivateStateThread::StartupThread(), lldb_private::process_gdb_remote::ProcessGDBRemote::StopAsyncThread(), ProcessKDP::StopAsyncThread(), lldb_private::DebuggerThread::StopDebugging(), lldb_private::Process::StopForDestroyOrDetach(), lldb_private::process_gdb_remote::ProcessGDBRemote::StopNoticingNewThreads(), lldb_private::Process::StopPrivateStateThread(), lldb_private::process_netbsd::NativeProcessNetBSD::StopProcess(), lldb_private::ThreadedCommunication::StopReadThread(), lldb_private::process_linux::NativeProcessLinux::StopRunningThreads(), lldb_private::process_linux::NativeProcessLinux::StopTrackingThread(), lldb_private::StreamFile::StreamFile(), lldb_private::npdb::SymbolFileNativePDB::StripMangledFunctionName(), lldb_private::NativeProcessProtocol::SynchronouslyNotifyProcessStateChanged(), lldb_private::Process::SyncIOHandler(), lldb_private::process_gdb_remote::GDBRemoteClientBase::Lock::SyncWithContinueThread(), lldb_private::ASTResultSynthesizer::SynthesizeBodyResult(), lldb_private::ASTResultSynthesizer::SynthesizeFunctionResult(), lldb_private::ASTResultSynthesizer::SynthesizeObjCMethodResult(), lldb_private::StackFrameList::SynthesizeTailCallFrames(), lldb_private::Target::Target(), lldb_private::Socket::TcpConnect(), lldb_private::Socket::TcpListen(), TemplateParameterAllowsValue(), lldb_private::mcp::ProtocolServerMCP::Terminate(), lldb_private::Thread::Thread(), lldb_private::HostNativeThreadBase::ThreadCreateTrampoline(), lldb_private::ThreadedCommunication::ThreadedCommunication(), lldb_private::process_gdb_remote::ThreadGDBRemote::ThreadGDBRemote(), ThreadKDP::ThreadKDP(), lldb_private::ThreadPlanStepThrough::ThreadPlanStepThrough(), lldb_private::process_linux::NativeProcessLinux::ThreadWasCreated(), lldb_private::ThreadPlanSingleThreadTimeout::TimeoutThreadFunc(), lldb_private::ASTResultSynthesizer::TransformTopLevelDecl(), lldb_private::RegisterContextUnwind::TryAdoptArchitectureUnwindPlan(), lldb_private::CxxModuleHandler::tryInstantiateStdTemplate(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::Unlink(), lldb_private::DynamicLoaderDarwin::UnloadAllImages(), lldb_private::DynamicLoaderDarwin::UnloadImages(), lldb_private::RegisterContextUnwind::UnwindLogMsg(), lldb_private::RegisterContextUnwind::UnwindLogMsgVerbose(), lldb_private::BytecodeSyntheticChildren::FrontEnd::Update(), lldb_private::formatters::GenericInitializerListSyntheticFrontEnd< StandardImpl >::Update(), lldb_private::formatters::LibcxxStdSpanSyntheticFrontEnd::Update(), lldb_private::formatters::LibcxxStdUnorderedMapSyntheticFrontEnd::Update(), lldb_private::formatters::LibcxxStdVectorSyntheticFrontEnd::Update(), lldb_private::formatters::LibStdcppSpanSyntheticFrontEnd::Update(), lldb_private::formatters::MsvcStlSpanSyntheticFrontEnd::Update(), lldb_private::formatters::MsvcStlVectorSyntheticFrontEnd::Update(), lldb_private::process_gdb_remote::ProcessGDBRemote::UpdateAutomaticSignalFiltering(), ProcessElfCore::UpdateBuildIdForNTFileEntries(), DYLDRendezvous::UpdateExecutablePath(), lldb_private::ValueObject::UpdateFormatsIfNeeded(), lldb_private::AppleObjCRuntimeV1::UpdateISAToDescriptorMapIfNeeded(), UpdateRegister(), UpdateRegister(), lldb_private::PlatformDarwinDevice::UpdateSDKDirectoryInfosIfNeeded(), DYLDRendezvous::UpdateSOEntries(), DYLDRendezvous::UpdateSOEntriesFromRemote(), lldb_private::DynamicLoaderDarwin::UpdateSpecialBinariesFromPreloadedModules(), lldb_private::ValueObjectDynamicValue::UpdateValue(), lldb_private::ValueObjectSynthetic::UpdateValue(), lldb_private::DynamicLoaderDarwin::UseDYLDSPI(), lldb_private::ThreadPlanNull::ValidatePlan(), lldb_private::Watchpoint::VariableWatchpointDisabler(), VerifyClangPath(), lldb_private::ProcessDebugger::WaitForDebuggerConnection(), lldb_private::process_gdb_remote::GDBRemoteCommunication::WaitForPacketNoLock(), CommunicationKDP::WaitForPacketWithTimeoutMicroSecondsNoLock(), lldb_private::Process::WaitForProcessToStop(), WaitPid(), WaitPid(), lldb_private::StopInfoMachException::WasContinueInterrupted(), lldb_private::Watchpoint::Watchpoint(), lldb_private::NativeRegisterContextDBReg::WatchpointIsEnabled(), lldb_private::process_gdb_remote::ThreadGDBRemote::WillResume(), lldb_private::ThreadList::WillResume(), lldb_private::ThreadPlan::WillResume(), lldb_private::ScriptedThreadPlan::WillStop(), lldb_private::ThreadPlanNull::WillStop(), lldb_private::ThreadPlanSingleThreadTimeout::WillStop(), lldb_private::Communication::Write(), lldb_private::ConnectionFileDescriptor::Write(), lldb_private::ConnectionGenericFile::Write(), lldb_private::Socket::Write(), lldb_private::process_gdb_remote::GDBRemoteRegisterContext::WriteAllRegisterValues(), lldb_private::IRMemoryMap::WriteMemory(), lldb_private::process_freebsd::NativeProcessFreeBSD::WriteMemory(), lldb_private::process_linux::NativeProcessLinux::WriteMemory(), lldb_private::process_netbsd::NativeProcessNetBSD::WriteMemory(), lldb_private::ProcessDebugger::WriteMemory(), UnwindAssemblyInstEmulation::WriteMemory(), lldb_private::IRExecutionUnit::WriteNow(), UnwindAssemblyInstEmulation::WriteRegister(), lldb_private::process_gdb_remote::GDBRemoteRegisterContext::WriteRegisterBytes(), xcrun(), lldb_private::platform_android::AdbClient::~AdbClient(), lldb_private::platform_android::AdbSyncService::~AdbSyncService(), lldb_private::Broadcaster::~Broadcaster(), lldb_private::ConnectionFileDescriptor::~ConnectionFileDescriptor(), lldb_private::HistoryThread::~HistoryThread(), lldb_private::Listener::~Listener(), lldb_private::Module::~Module(), lldb_private::ObjectFile::~ObjectFile(), lldb_private::Process::~Process(), lldb_private::Target::~Target(), lldb_private::Thread::~Thread(), lldb_private::ThreadedCommunication::~ThreadedCommunication(), lldb_private::process_gdb_remote::ThreadGDBRemote::~ThreadGDBRemote(), and ThreadKDP::~ThreadKDP().
GetPermissionsAsCString()
const char * lldb_private::GetPermissionsAsCString (uint32_t permissions)
Definition at line 44 of file State.cpp.
Referenced by lldb_private::AllocatedMemoryCache::AllocateMemory(), lldb_private::AllocatedMemoryCache::AllocatePage(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoAllocateMemory(), and CommunicationKDP::DumpPacket().
getPIDForTID()
std::optional< lldb::pid_t > lldb_private::getPIDForTID (lldb::pid_t tid)
Definition at line 423 of file linux/Host.cpp.
References GetStatusInfo(), and LLDB_INVALID_PROCESS_ID.
Referenced by lldb_private::process_linux::NativeProcessLinux::MonitorClone().
GetPreferredAsanModule()
std::tuple< lldb::ModuleSP, HistoryPCType > lldb_private::GetPreferredAsanModule (const Target & target)
On Darwin, if LLDB loaded libclang_rt, it's coming from a locally built compiler-rt, and we should prefer it in favour of the system sanitizers when running InstrumentationRuntime utility expressions that use symbols from the sanitizer libraries.
This helper searches the target for such a dylib. Returns nullptr if no such dylib was found.
Definition at line 17 of file Utility.cpp.
References Calls, Continue, lldb_private::ModuleList::ForEach(), lldb_private::Target::GetArchitecture(), lldb_private::Target::GetImages(), lldb_private::ArchSpec::GetTriple(), and Stop.
Referenced by lldb_private::MemoryHistoryASan::GetHistoryThreads(), and lldb_private::ReportRetriever::RetrieveReportData().
getProcFile() [1/3]
llvm::ErrorOr< std::unique_ptr< llvm::MemoryBuffer > > lldb_private::getProcFile (::pid_t pid, ::pid_t tid, const llvm::Twine & file)
Definition at line 15 of file aix/Support.cpp.
References GetLog(), Host, and LLDB_LOG.
Referenced by lldb_private::process_aix::NativeProcessAIX::GetAuxvData(), lldb_private::process_linux::NativeProcessLinux::GetAuxvData(), GetExePathAndIds(), lldb_private::process_linux::NativeThreadLinux::GetName(), GetProcessArgs(), GetProcessEnviron(), lldb_private::process_linux::GetProcfsCpuInfo(), lldb_private::HostInfoAIX::GetProgramFileSpec(), lldb_private::process_linux::GetPtraceScope(), GetStatusInfo(), GetStatusInfo(), and lldb_private::process_linux::NativeProcessLinux::PopulateMemoryRegionCache().
getProcFile() [2/3]
llvm::ErrorOr< std::unique_ptr< llvm::MemoryBuffer > > lldb_private::getProcFile (::pid_t pid, const llvm::Twine & file)
Definition at line 15 of file posix/Support.cpp.
References GetLog(), Host, and LLDB_LOG.
getProcFile() [3/3]
llvm::ErrorOr< std::unique_ptr< llvm::MemoryBuffer > > lldb_private::getProcFile (const llvm::Twine & file)
Definition at line 25 of file posix/Support.cpp.
References GetLog(), Host, and LLDB_LOG.
GetRegInfoShared()
RegInfo & lldb_private::GetRegInfoShared (llvm::Triple::ArchType arch_type, bool with_base)
Definition at line 238 of file RegisterInfos_x86_64_with_base_shared.cpp.
References lldb_private::RegInfo::first_dr, lldb_private::RegInfo::first_fpr, lldb_private::RegInfo::first_mm, lldb_private::RegInfo::first_st, lldb_private::RegInfo::first_xmm, lldb_private::RegInfo::first_ymm, lldb_private::RegInfo::gpr_flags, lldb_private::x86_64_with_base::k_first_fpr, k_first_fpr_i386, k_first_fpr_x86_64, lldb_private::x86_64_with_base::k_last_fpr, k_last_fpr_i386, k_last_fpr_x86_64, lldb_private::x86_64_with_base::k_last_gpr, k_last_gpr_i386, k_last_gpr_x86_64, lldb_private::x86_64_with_base::k_num_avx_registers, k_num_avx_registers_i386, k_num_avx_registers_x86_64, lldb_private::x86_64_with_base::k_num_fpr_registers, k_num_fpr_registers_i386, k_num_fpr_registers_x86_64, lldb_private::x86_64_with_base::k_num_gpr_registers, k_num_gpr_registers_i386, k_num_gpr_registers_x86_64, lldb_private::x86_64_with_base::k_num_registers, k_num_registers_i386, k_num_registers_x86_64, lldb_private::RegInfo::last_fpr, lldb_private::RegInfo::last_gpr, lldb_private::RegInfo::last_mm, lldb_private::RegInfo::last_st, lldb_private::RegInfo::last_xmm, lldb_private::RegInfo::last_ymm, lldb_private::x86_64_with_base::lldb_dr0, lldb_dr0_i386, lldb_dr0_x86_64, lldb_eflags_i386, lldb_private::x86_64_with_base::lldb_mm0, lldb_mm0_i386, lldb_mm0_x86_64, lldb_private::x86_64_with_base::lldb_mm7, lldb_mm7_i386, lldb_mm7_x86_64, lldb_private::x86_64_with_base::lldb_rflags, lldb_rflags_x86_64, lldb_private::x86_64_with_base::lldb_st0, lldb_st0_i386, lldb_st0_x86_64, lldb_private::x86_64_with_base::lldb_st7, lldb_st7_i386, lldb_st7_x86_64, lldb_private::x86_64_with_base::lldb_xmm0, lldb_xmm0_i386, lldb_xmm0_x86_64, lldb_private::x86_64_with_base::lldb_xmm15, lldb_xmm15_x86_64, lldb_xmm7_i386, lldb_private::x86_64_with_base::lldb_ymm0, lldb_ymm0_i386, lldb_ymm0_x86_64, lldb_private::x86_64_with_base::lldb_ymm15, lldb_ymm15_x86_64, lldb_ymm7_i386, lldb_private::RegInfo::num_avx_registers, lldb_private::RegInfo::num_fpr_registers, lldb_private::RegInfo::num_gpr_registers, and lldb_private::RegInfo::num_registers.
Referenced by RegisterContextLinuxCore_x86::GetRegInfo(), and RegisterContextPOSIX_x86::GetRegInfo().
getRegset()
DataExtractor lldb_private::getRegset (llvm::ArrayRef< CoreNote > Notes, const llvm::Triple & Triple, llvm::ArrayRef< RegsetDesc > RegsetDescs)
Definition at line 29 of file RegisterUtilities.cpp.
References getNoteType(), lldb_private::CoreNote::info, and ELFNote::n_type.
Referenced by RegisterContextCorePOSIX_arm64::Create(), RegisterContextCorePOSIX_riscv64::Create(), RegisterContextCorePOSIX_arm::RegisterContextCorePOSIX_arm(), RegisterContextCorePOSIX_arm64::RegisterContextCorePOSIX_arm64(), RegisterContextCorePOSIX_loongarch64::RegisterContextCorePOSIX_loongarch64(), RegisterContextCorePOSIX_powerpc::RegisterContextCorePOSIX_powerpc(), RegisterContextCorePOSIX_ppc64le::RegisterContextCorePOSIX_ppc64le(), RegisterContextCorePOSIX_s390x::RegisterContextCorePOSIX_s390x(), and RegisterContextCorePOSIX_x86::RegisterContextCorePOSIX_x86().
GetStatDescription()
std::string lldb_private::GetStatDescription (lldb_private::StatisticKind K) inline
Definition at line 267 of file lldb-private-enumerations.h.
References ExpressionFailure, ExpressionSuccessful, FrameVarFailure, FrameVarSuccess, and StatisticMax.
GetStoppedExecutionContext() [1/2]
llvm::Expected< StoppedExecutionContext > lldb_private::GetStoppedExecutionContext (const ExecutionContextRef * exe_ctx_ref_ptr)
Definition at line 137 of file ExecutionContext.cpp.
References lldb_private::ExecutionContextRef::GetFrameSP(), lldb_private::ExecutionContextRef::GetProcessSP(), lldb_private::ExecutionContextRef::GetTargetSP(), lldb_private::ExecutionContextRef::GetThreadSP(), lldb_private::ExecutionContextRef::m_frame_list_id, and lldb_private::ProcessRunLock::ProcessRunLocker::TryLock().
Referenced by lldb::SBFrame::Disassemble(), lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::FindRegister(), lldb::SBFrame::FindValue(), lldb::SBFrame::FindValue(), lldb::SBFrame::FindVariable(), lldb::SBFrame::FindVariable(), lldb::SBFrame::GetBlock(), lldb::SBFrame::GetCFA(), lldb::SBFrame::GetCompileUnit(), lldb::SBThread::GetCurrentException(), lldb::SBThread::GetCurrentExceptionBacktrace(), lldb::SBFrame::GetDescription(), lldb::SBThread::GetDescription(), lldb::SBFrame::GetDescriptionWithFormat(), lldb::SBThread::GetDescriptionWithFormat(), lldb::SBFrame::GetDisplayFunctionName(), lldb::SBThread::GetExtendedBacktraceOriginatingIndexID(), lldb::SBThread::GetExtendedBacktraceThread(), lldb::SBFrame::GetFP(), lldb::SBThread::GetFrameAtIndex(), lldb::SBFrame::GetFrameBlock(), lldb::SBFrame::GetFrameID(), lldb::SBThread::GetFrames(), lldb::SBFrame::GetFunction(), lldb::SBFrame::GetFunctionName(), lldb::SBThread::GetIndexID(), lldb::SBThread::GetInfoItemByPathAsString(), lldb::SBFrame::GetLanguageSpecificData(), lldb::SBFrame::GetLineEntry(), lldb::SBFrame::GetModule(), lldb::SBThread::GetName(), lldb::SBThread::GetNumFrames(), lldb::SBFrame::GetPC(), lldb::SBFrame::GetPCAddress(), lldb::SBThread::GetProcess(), lldb::SBThread::GetQueue(), lldb::SBThread::GetQueueID(), lldb::SBThread::GetQueueName(), lldb::SBFrame::GetRegisters(), lldb::SBThread::GetSelectedFrame(), lldb::SBThread::GetSiginfo(), lldb::SBFrame::GetSP(), lldb::SBThread::GetStatus(), lldb::SBThread::GetStopDescription(), lldb::SBThread::GetStopDescription(), lldb::SBThread::GetStopReason(), lldb::SBThread::GetStopReasonDataAtIndex(), lldb::SBThread::GetStopReasonDataCount(), lldb::SBThread::GetStopReasonExtendedBacktraces(), lldb::SBThread::GetStopReasonExtendedInfoAsJSON(), lldb::SBThread::GetStopReturnValue(), lldb::SBFrame::GetSymbol(), lldb::SBFrame::GetSymbolContext(), lldb::SBFrame::GetThread(), lldb::SBThread::GetThreadID(), lldb::SBFrame::GetValueForVariablePath(), lldb::SBFrame::GetValueForVariablePath(), lldb::SBFrame::GetVariables(), lldb::SBFrame::GetVariables(), lldb::SBFrame::GetVariables(), lldb::SBFrame::GuessLanguage(), lldb::SBFrame::IsArtificial(), lldb::SBFrame::IsHidden(), lldb::SBFrame::IsInlined(), lldb::SBThread::IsStopped(), lldb::SBThread::IsSuspended(), lldb::SBFrame::IsSynthetic(), lldb::SBThread::JumpToLine(), lldb::SBFrame::operator bool(), lldb::SBThread::operator bool(), lldb_private::Statusline::Redraw(), lldb::SBThread::Resume(), lldb::SBThread::ReturnFromFrame(), lldb::SBThread::RunToAddress(), lldb::SBThread::SafeToCallFunctions(), lldb::SBFrame::SetPC(), lldb::SBThread::SetSelectedFrame(), lldb::SBThread::StepInstruction(), lldb::SBThread::StepInto(), lldb::SBThread::StepOut(), lldb::SBThread::StepOutOfFrame(), lldb::SBThread::StepOver(), lldb::SBThread::StepOverUntil(), lldb::SBThread::StepUsingScriptedThreadPlan(), lldb::SBThread::Suspend(), and lldb::SBThread::UnwindInnermostExpression().
GetStoppedExecutionContext() [2/2]
llvm::Expected< StoppedExecutionContext > lldb_private::GetStoppedExecutionContext (const lldb::ExecutionContextRefSP & exe_ctx_ref_ptr)
GetVersion()
const char * lldb_private::GetVersion ()
Retrieves a string representing the complete LLDB version, which includes the lldb version number, as well as embedded compiler versions and the vendor tag.
Definition at line 38 of file Version.cpp.
References GetLLDBRepository(), GetLLDBRevision(), and GetLLDBVersion().
Referenced by lldb_private::Debugger::AssertCallback(), lldb_private::Debugger::CreateInstance(), lldb_private::CommandObjectVersion::DoExecute(), lldb::SBDebugger::GetVersionString(), and lldb_private::SystemInitializerFull::Initialize().
GetWasmRegister()
uint32_t lldb_private::GetWasmRegister (uint8_t tag, uint32_t index) inline
Definition at line 46 of file WasmVirtualRegisters.h.
References kWasmVirtualRegisterIndexMask, kWasmVirtualRegisterTagMask, and kWasmVirtualRegisterTagShift.
Referenced by lldb_private::plugin::dwarf::SymbolFileWasm::ParseVendorDWARFOpcode().
GetWasmVirtualRegisterIndex()
uint32_t lldb_private::GetWasmVirtualRegisterIndex (size_t reg) inline
Definition at line 42 of file WasmVirtualRegisters.h.
References kWasmVirtualRegisterIndexMask.
Referenced by lldb_private::wasm::RegisterContextWasm::GetRegisterInfoAtIndex().
GetWasmVirtualRegisterTag()
uint32_t lldb_private::GetWasmVirtualRegisterTag (size_t reg) inline
Definition at line 38 of file WasmVirtualRegisters.h.
References kWasmVirtualRegisterTagMask, and kWasmVirtualRegisterTagShift.
Referenced by lldb_private::wasm::RegisterContextWasm::GetRegisterInfoAtIndex().
GPREncodingToLLDB()
uint32_t lldb_private::GPREncodingToLLDB (uint32_t reg_encode) static
Definition at line 103 of file EmulateInstructionRISCV.cpp.
References gpr_x0_riscv, gpr_x1_riscv, and LLDB_INVALID_REGNUM.
Referenced by GPREncodingToRegisterInfo(), lldb_private::Executor::operator()(), lldb_private::Rs::Read(), and lldb_private::Rd::Write().
GPREncodingToRegisterInfo()
std::optional< RegisterInfo > lldb_private::GPREncodingToRegisterInfo (EmulateInstructionRISCV & emulator, uint32_t reg_encode) static
Definition at line 119 of file EmulateInstructionRISCV.cpp.
References lldb::eRegisterKindLLDB, lldb_private::EmulateInstructionRISCV::GetRegisterInfo(), GPREncodingToLLDB(), and LLDB_INVALID_REGNUM.
Referenced by Load(), and Store().
I_TYPE_INST() [1/43]
lldb_private::I_TYPE_INST (ADDI)
I_TYPE_INST() [2/43]
lldb_private::I_TYPE_INST (ADDIW)
I_TYPE_INST() [3/43]
lldb_private::I_TYPE_INST (ANDI)
I_TYPE_INST() [4/43]
lldb_private::I_TYPE_INST (FCLASS_D)
I_TYPE_INST() [5/43]
lldb_private::I_TYPE_INST (FCLASS_S)
I_TYPE_INST() [6/43]
lldb_private::I_TYPE_INST (FCVT_D_L)
I_TYPE_INST() [7/43]
lldb_private::I_TYPE_INST (FCVT_D_LU)
I_TYPE_INST() [8/43]
lldb_private::I_TYPE_INST (FCVT_D_S)
I_TYPE_INST() [9/43]
lldb_private::I_TYPE_INST (FCVT_D_W)
I_TYPE_INST() [10/43]
lldb_private::I_TYPE_INST (FCVT_D_WU)
I_TYPE_INST() [11/43]
lldb_private::I_TYPE_INST (FCVT_L_D)
I_TYPE_INST() [12/43]
lldb_private::I_TYPE_INST (FCVT_L_S)
I_TYPE_INST() [13/43]
lldb_private::I_TYPE_INST (FCVT_LU_D)
I_TYPE_INST() [14/43]
lldb_private::I_TYPE_INST (FCVT_LU_S)
I_TYPE_INST() [15/43]
lldb_private::I_TYPE_INST (FCVT_S_D)
I_TYPE_INST() [16/43]
lldb_private::I_TYPE_INST (FCVT_S_L)
I_TYPE_INST() [17/43]
lldb_private::I_TYPE_INST (FCVT_S_LU)
I_TYPE_INST() [18/43]
lldb_private::I_TYPE_INST (FCVT_S_W)
I_TYPE_INST() [19/43]
lldb_private::I_TYPE_INST (FCVT_S_WU)
I_TYPE_INST() [20/43]
lldb_private::I_TYPE_INST (FCVT_W_D)
I_TYPE_INST() [21/43]
lldb_private::I_TYPE_INST (FCVT_W_S)
I_TYPE_INST() [22/43]
lldb_private::I_TYPE_INST (FCVT_WU_D)
I_TYPE_INST() [23/43]
lldb_private::I_TYPE_INST (FCVT_WU_S)
I_TYPE_INST() [24/43]
lldb_private::I_TYPE_INST (FLD)
I_TYPE_INST() [25/43]
lldb_private::I_TYPE_INST (FLW)
I_TYPE_INST() [26/43]
lldb_private::I_TYPE_INST (FMV_D_X)
I_TYPE_INST() [27/43]
lldb_private::I_TYPE_INST (FMV_W_X)
I_TYPE_INST() [28/43]
lldb_private::I_TYPE_INST (FMV_X_D)
I_TYPE_INST() [29/43]
lldb_private::I_TYPE_INST (FMV_X_W)
I_TYPE_INST() [30/43]
lldb_private::I_TYPE_INST (FSQRT_D)
I_TYPE_INST() [31/43]
lldb_private::I_TYPE_INST (FSQRT_S)
I_TYPE_INST() [32/43]
lldb_private::I_TYPE_INST (JALR)
I_TYPE_INST() [33/43]
lldb_private::I_TYPE_INST (LB)
I_TYPE_INST() [34/43]
lldb_private::I_TYPE_INST (LBU)
I_TYPE_INST() [35/43]
lldb_private::I_TYPE_INST (LD)
I_TYPE_INST() [36/43]
lldb_private::I_TYPE_INST (LH)
I_TYPE_INST() [37/43]
lldb_private::I_TYPE_INST (LHU)
I_TYPE_INST() [38/43]
lldb_private::I_TYPE_INST (LW)
I_TYPE_INST() [39/43]
lldb_private::I_TYPE_INST (LWU)
I_TYPE_INST() [40/43]
lldb_private::I_TYPE_INST (ORI)
I_TYPE_INST() [41/43]
lldb_private::I_TYPE_INST (SLTI)
I_TYPE_INST() [42/43]
lldb_private::I_TYPE_INST (SLTIU)
I_TYPE_INST() [43/43]
lldb_private::I_TYPE_INST (XORI)
InferiorCallMmap()
bool lldb_private::InferiorCallMmap (Process * proc, lldb::addr_t & allocated_addr, lldb::addr_t addr, lldb::addr_t length, unsigned prot, unsigned flags, lldb::addr_t fd, lldb::addr_t offset)
Definition at line 36 of file InferiorCallPOSIX.cpp.
References lldb_private::StackFrame::CalculateExecutionContext(), lldb::eBasicTypeVoid, lldb::eExpressionCompleted, lldb::eLanguageTypeC, eMmapProtExec, eMmapProtNone, eMmapProtRead, eMmapProtWrite, lldb_private::ModuleList::FindFunctions(), lldb_private::Process::GetAddressByteSize(), lldb_private::Target::GetArchitecture(), lldb_private::CompilerType::GetBasicTypeFromAST(), lldb_private::SymbolContextList::GetContextAtIndex(), lldb_private::ThreadList::GetExpressionExecutionThread(), lldb_private::SymbolContext::GetFunctionOrSymbolAddress(), lldb_private::Target::GetImages(), lldb_private::Target::GetPlatform(), lldb_private::CompilerType::GetPointerType(), lldb_private::Target::GetScratchTypeSystemForLanguage(), lldb_private::SymbolContextList::GetSize(), lldb_private::Process::GetTarget(), lldb_private::Process::GetThreadList(), lldb_private::ProcessProperties::GetUtilityExpressionTimeout(), lldb_private::ModuleFunctionSearchOptions::include_inlines, lldb_private::ModuleFunctionSearchOptions::include_symbols, lldb_private::Address::IsValid(), LLDB_INVALID_ADDRESS, PROT_EXEC, PROT_NONE, PROT_READ, PROT_WRITE, lldb_private::Process::RunThreadPlan(), lldb_private::EvaluateExpressionOptions::SetDebug(), lldb_private::EvaluateExpressionOptions::SetIgnoreBreakpoints(), lldb_private::EvaluateExpressionOptions::SetStopOthers(), lldb_private::EvaluateExpressionOptions::SetTimeout(), lldb_private::EvaluateExpressionOptions::SetTrapExceptions(), lldb_private::EvaluateExpressionOptions::SetTryAllThreads(), lldb_private::EvaluateExpressionOptions::SetUnwindOnError(), UINT32_MAX, and UINT64_MAX.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::DoAllocateMemory().
InferiorCallMunmap()
bool lldb_private::InferiorCallMunmap (Process * proc, lldb::addr_t addr, lldb::addr_t length)
Definition at line 129 of file InferiorCallPOSIX.cpp.
References lldb_private::StackFrame::CalculateExecutionContext(), lldb::eExpressionCompleted, lldb_private::ModuleList::FindFunctions(), lldb_private::SymbolContextList::GetContextAtIndex(), lldb_private::ThreadList::GetExpressionExecutionThread(), lldb_private::SymbolContext::GetFunctionOrSymbolAddress(), lldb_private::Target::GetImages(), lldb_private::SymbolContextList::GetSize(), lldb_private::Process::GetTarget(), lldb_private::Process::GetThreadList(), lldb_private::ProcessProperties::GetUtilityExpressionTimeout(), lldb_private::ModuleFunctionSearchOptions::include_inlines, lldb_private::ModuleFunctionSearchOptions::include_symbols, lldb_private::Address::IsValid(), lldb_private::Process::RunThreadPlan(), lldb_private::EvaluateExpressionOptions::SetDebug(), lldb_private::EvaluateExpressionOptions::SetIgnoreBreakpoints(), lldb_private::EvaluateExpressionOptions::SetStopOthers(), lldb_private::EvaluateExpressionOptions::SetTimeout(), lldb_private::EvaluateExpressionOptions::SetTrapExceptions(), lldb_private::EvaluateExpressionOptions::SetTryAllThreads(), and lldb_private::EvaluateExpressionOptions::SetUnwindOnError().
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::DoDeallocateMemory().
InitializeLldbChannel()
void lldb_private::InitializeLldbChannel ()
Definition at line 87 of file LLDBLog.cpp.
References g_log_channel, and lldb_private::Log::Register().
Referenced by lldb_private::SystemInitializerCommon::Initialize().
INVALID_INST() [1/5]
lldb_private::INVALID_INST (EBREAK)
INVALID_INST() [2/5]
lldb_private::INVALID_INST (HINT)
INVALID_INST() [3/5]
lldb_private::INVALID_INST (INVALID)
Invalid and reserved instructions, the inst fields are used for debugging.
INVALID_INST() [4/5]
lldb_private::INVALID_INST (NOP)
INVALID_INST() [5/5]
lldb_private::INVALID_INST (RESERVED)
J_TYPE_INST()
lldb_private::J_TYPE_INST (JAL)
LanguageCategory::Get< lldb::SyntheticChildrenSP >()
template bool lldb_private::LanguageCategory::Get< lldb::SyntheticChildrenSP > (FormattersMatchData & , lldb::SyntheticChildrenSP &)
References lldb_private::LanguageCategory::Get().
Referenced by lldb_private::FormatManager::GetSyntheticChildren().
LanguageCategory::Get< lldb::TypeFormatImplSP >()
template bool lldb_private::LanguageCategory::Get< lldb::TypeFormatImplSP > (FormattersMatchData & , lldb::TypeFormatImplSP &)
Explicit instantiations for the three types.
References lldb_private::LanguageCategory::Get().
Referenced by lldb_private::FormatManager::GetFormat().
LanguageCategory::Get< lldb::TypeSummaryImplSP >()
template bool lldb_private::LanguageCategory::Get< lldb::TypeSummaryImplSP > (FormattersMatchData & , lldb::TypeSummaryImplSP &)
References lldb_private::LanguageCategory::Get().
Referenced by lldb_private::FormatManager::GetSummaryFormat().
LanguageCategory::GetHardcodedFinder< lldb::SyntheticChildrenSP >()
template<> auto & lldb_private::LanguageCategory::GetHardcodedFinder< lldb::SyntheticChildrenSP > ()
Definition at line 83 of file LanguageCategory.cpp.
References lldb_private::LanguageCategory::GetHardcodedFinder().
LanguageCategory::GetHardcodedFinder< lldb::TypeFormatImplSP >()
template<> auto & lldb_private::LanguageCategory::GetHardcodedFinder< lldb::TypeFormatImplSP > ()
Definition at line 73 of file LanguageCategory.cpp.
References lldb_private::LanguageCategory::GetHardcodedFinder().
LanguageCategory::GetHardcodedFinder< lldb::TypeSummaryImplSP >()
template<> auto & lldb_private::LanguageCategory::GetHardcodedFinder< lldb::TypeSummaryImplSP > ()
Definition at line 78 of file LanguageCategory.cpp.
References lldb_private::LanguageCategory::GetHardcodedFinder().
LanguageTypeHelpTextCallback()
llvm::StringRef lldb_private::LanguageTypeHelpTextCallback ()
Definition at line 163 of file CommandOptionArgumentTable.cpp.
References lldb_private::StreamString::Flush(), lldb_private::StreamString::GetString(), and lldb_private::Language::PrintAllLanguages().
LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE()
lldb_private::LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE ()
Load()
template<typename I, typename T, typename E> std::enable_if_t< is_load< I >, bool > lldb_private::Load (EmulateInstructionRISCV & emulator, I inst, uint64_t(* extend)(E)) static
Definition at line 245 of file EmulateInstructionRISCV.cpp.
References lldb_private::EmulateInstruction::eContextPopRegisterOffStack, lldb_private::EmulateInstruction::eContextRegisterLoad, GPREncodingToRegisterInfo(), LoadStoreAddr(), lldb_private::EmulateInstruction::ReadMemoryUnsigned(), RISCV_GPR_SP, lldb_private::EmulateInstruction::Context::SetAddress(), and lldb_private::EmulateInstruction::Context::type.
Referenced by lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), and lldb_private::Executor::operator()().
LoadFormattersForModule()
void lldb_private::LoadFormattersForModule (lldb::ModuleSP module_sp)
Load data formatters embedded in the binary.
These are formatters provided by the authors of the code using LLDB formatter bytecode.
Definition at line 161 of file FormatterSection.cpp.
References CreateSyntheticImpl(), DataFormatters, lldb::eFormatterMatchExact, lldb::eFormatterMatchRegex, lldb::eSectionTypeLLDBFormatters, ForEachFormatterInModule(), lldb_private::DataVisualization::Categories::GetCategory(), GetLog(), kSignatureCount, LLDB_LOG, and LLDB_LOG_ERROR.
Referenced by lldb_private::Target::ModulesDidLoad().
LoadStoreAddr()
template<typename I> std::enable_if_t< is_load< I >||is_store< I >, std::optional< uint64_t > > lldb_private::LoadStoreAddr (EmulateInstructionRISCV & emulator, I inst) static
Definition at line 236 of file EmulateInstructionRISCV.cpp.
Referenced by Load(), and Store().
LoadTypeSummariesForModule()
void lldb_private::LoadTypeSummariesForModule (lldb::ModuleSP module_sp)
Load type summaries embedded in the binary.
These are type summaries provided by the authors of the code.
Definition at line 105 of file FormatterSection.cpp.
References DataFormatters, lldb::eFormatterMatchExact, lldb::eFormatterMatchRegex, lldb::eSectionTypeLLDBTypeSummaries, ForEachFormatterInModule(), lldb_private::DataVisualization::Categories::GetCategory(), GetLog(), LLDB_LOG, and LLDB_LOG_ERROR.
Referenced by lldb_private::Target::ModulesDidLoad().
LogChannelFor()
template<typename Cat> Log::Channel & lldb_private::LogChannelFor () delete
Referenced by GetLog().
LogChannelFor< DWARFLog >()
template<> Log::Channel & lldb_private::LogChannelFor< DWARFLog > ()
Definition at line 30 of file LogChannelDWARF.cpp.
References g_channel.
LogChannelFor< KDPLog >()
template<> Log::Channel & lldb_private::LogChannelFor< KDPLog > ()
Definition at line 34 of file ProcessKDPLog.cpp.
References g_channel.
LogChannelFor< LLDBLog >()
template<> Log::Channel & lldb_private::LogChannelFor< LLDBLog > ()
Definition at line 83 of file LLDBLog.cpp.
References g_log_channel.
LogChannelFor< POSIXLog >()
template<> Log::Channel & lldb_private::LogChannelFor< POSIXLog > ()
Definition at line 27 of file ProcessPOSIXLog.cpp.
References g_channel.
LogChannelFor< process_gdb_remote::GDBRLog >()
template<> Log::Channel & lldb_private::LogChannelFor< process_gdb_remote::GDBRLog > ()
LogChannelFor< SystemLog >()
template<> Log::Channel & lldb_private::LogChannelFor< SystemLog > ()
Definition at line 100 of file common/Host.cpp.
References g_system_channel.
LogChannelFor< WindowsLog >()
template<> Log::Channel & lldb_private::LogChannelFor< WindowsLog > ()
Definition at line 26 of file ProcessWindowsLog.cpp.
References g_channel.
LSL()
uint32_t lldb_private::LSL (const uint32_t value, const uint32_t amount, bool * success) inline static
Definition at line 102 of file ARMUtils.h.
References LSL_C().
Referenced by lldb_private::EmulateInstructionARM::EmulateTB().
LSL_C()
uint32_t lldb_private::LSL_C (const uint32_t value, const uint32_t amount, uint32_t & carry_out, bool * success) inline static
Definition at line 91 of file ARMUtils.h.
References Bit32().
Referenced by LSL(), and Shift_C().
LSR()
uint32_t lldb_private::LSR (const uint32_t value, const uint32_t amount, bool * success) inline static
Definition at line 126 of file ARMUtils.h.
References LSR_C().
LSR_C()
uint32_t lldb_private::LSR_C (const uint32_t value, const uint32_t amount, uint32_t & carry_out, bool * success) inline static
Definition at line 115 of file ARMUtils.h.
References Bit32().
Referenced by LSR(), and Shift_C().
luaopen_lldb()
int lldb_private::luaopen_lldb (lua_State * L)
Referenced by lldb_private::Lua::Lua().
MaskUpToBit()
uint64_t lldb_private::MaskUpToBit (const uint64_t bit) inline static
Definition at line 73 of file InstructionUtils.h.
References bit().
Referenced by SignedBits(), and UnsignedBits().
NameMatches()
bool lldb_private::NameMatches (llvm::StringRef name, NameMatch match_type, llvm::StringRef match)
Definition at line 15 of file NameMatches.cpp.
References Contains, EndsWith, Equals, lldb_private::RegularExpression::Execute(), Ignore, RegularExpression, and StartsWith.
Referenced by GetFreeBSDProcessArgs(), GetMacOSXProcessArgs(), GetNetBSDProcessArgs(), GetOpenBSDProcessArgs(), and lldb_private::ProcessInstanceInfoMatch::NameMatches().
NanBoxing()
uint64_t lldb_private::NanBoxing (uint64_t val) constexpr
RISC-V spec: The upper bits of a valid NaN-boxed value must be all 1s.
Definition at line 332 of file RISCVInstructions.h.
NanUnBoxing()
uint32_t lldb_private::NanUnBoxing (uint64_t val) constexpr
Definition at line 335 of file RISCVInstructions.h.
NativeProcessELF::GetELFImageInfoAddress< llvm::ELF::Elf32_Ehdr, llvm::ELF::Elf32_Phdr, llvm::ELF::Elf32_Dyn >()
template lldb::addr_t lldb_private::NativeProcessELF::GetELFImageInfoAddress< llvm::ELF::Elf32_Ehdr, llvm::ELF::Elf32_Phdr, llvm::ELF::Elf32_Dyn > ()
References lldb_private::NativeProcessELF::GetELFImageInfoAddress().
NativeProcessELF::GetELFImageInfoAddress< llvm::ELF::Elf64_Ehdr, llvm::ELF::Elf64_Phdr, llvm::ELF::Elf64_Dyn >()
template lldb::addr_t lldb_private::NativeProcessELF::GetELFImageInfoAddress< llvm::ELF::Elf64_Ehdr, llvm::ELF::Elf64_Phdr, llvm::ELF::Elf64_Dyn > ()
References lldb_private::NativeProcessELF::GetELFImageInfoAddress().
operator!=() [1/13]
bool lldb_private::operator!= (const Address & lhs, const Address & rhs)
Definition at line 1017 of file Address.cpp.
References lldb_private::Address::GetOffset(), and lldb_private::Address::GetSection().
operator!=() [2/13]
bool lldb_private::operator!= (const ArchSpec & lhs, const ArchSpec & rhs)
Definition at line 1410 of file ArchSpec.cpp.
operator!=() [3/13]
bool lldb_private::operator!= (const CompilerDecl & lhs, const CompilerDecl & rhs)
Definition at line 50 of file CompilerDecl.cpp.
References lldb_private::CompilerDecl::GetOpaqueDecl(), and lldb_private::CompilerDecl::GetTypeSystem().
operator!=() [4/13]
bool lldb_private::operator!= (const CompilerDeclContext & lhs, const CompilerDeclContext & rhs)
Definition at line 75 of file CompilerDeclContext.cpp.
References lldb_private::CompilerDeclContext::GetOpaqueDeclContext(), and lldb_private::CompilerDeclContext::GetTypeSystem().
operator!=() [5/13]
bool lldb_private::operator!= (const CompilerType & lhs, const CompilerType & rhs)
Definition at line 1225 of file CompilerType.cpp.
operator!=() [6/13]
bool lldb_private::operator!= (const ProcessModID & lhs, const ProcessModID & rhs) inline
Definition at line 344 of file Process.h.
References lldb_private::ProcessModID::MemoryIDEqual(), and lldb_private::ProcessModID::StopIDEqual().
operator!=() [7/13]
bool lldb_private::operator!= (const Scalar & lhs, const Scalar & rhs)
Definition at line 896 of file Scalar.cpp.
References compare().
operator!=() [8/13]
bool lldb_private::operator!= (const StackID & lhs, const StackID & rhs)
Definition at line 68 of file StackID.cpp.
operator!=() [9/13]
bool lldb_private::operator!= (const SymbolContext & lhs, const SymbolContext & rhs)
Definition at line 355 of file SymbolContext.cpp.
operator!=() [10/13]
bool lldb_private::operator!= (const SymbolContextList & lhs, const SymbolContextList & rhs)
Definition at line 1323 of file SymbolContext.cpp.
operator!=() [11/13]
bool lldb_private::operator!= (const UserID & lhs, const UserID & rhs) inline
Definition at line 64 of file UserID.h.
References lldb_private::UserID::GetID().
operator!=() [12/13]
bool lldb_private::operator!= (const VMRange & lhs, const VMRange & rhs)
Definition at line 47 of file VMRange.cpp.
operator!=() [13/13]
bool lldb_private::operator!= (WaitStatus a, WaitStatus b) inline
Definition at line 76 of file Host.h.
operator%()
const Scalar lldb_private::operator% (Scalar lhs, Scalar rhs)
Definition at line 613 of file Scalar.cpp.
References lldb_private::Scalar::e_int, lldb_private::Scalar::e_void, lldb_private::Scalar::IsZero(), lldb_private::Scalar::m_integer, lldb_private::Scalar::m_type, and lldb_private::Scalar::PromoteToMaxType().
operator&()
const Scalar lldb_private::operator& (Scalar lhs, Scalar rhs)
Definition at line 591 of file Scalar.cpp.
References lldb_private::Scalar::e_int, lldb_private::Scalar::e_void, lldb_private::Scalar::m_integer, lldb_private::Scalar::m_type, and lldb_private::Scalar::PromoteToMaxType().
operator*()
const Scalar lldb_private::operator* (Scalar lhs, Scalar rhs)
Definition at line 574 of file Scalar.cpp.
References lldb_private::Scalar::e_float, lldb_private::Scalar::e_int, lldb_private::Scalar::e_void, lldb_private::Scalar::m_float, lldb_private::Scalar::m_integer, lldb_private::Scalar::m_type, and lldb_private::Scalar::PromoteToMaxType().
operator+()
const Scalar lldb_private::operator+ (const Scalar & lhs, const Scalar & rhs)
Definition at line 529 of file Scalar.cpp.
operator-()
const Scalar lldb_private::operator- (Scalar lhs, Scalar rhs)
Definition at line 535 of file Scalar.cpp.
References lldb_private::Scalar::e_float, lldb_private::Scalar::e_int, lldb_private::Scalar::e_void, lldb_private::Scalar::m_float, lldb_private::Scalar::m_integer, lldb_private::Scalar::m_type, and lldb_private::Scalar::PromoteToMaxType().
operator/()
const Scalar lldb_private::operator/ (Scalar lhs, Scalar rhs)
Definition at line 552 of file Scalar.cpp.
References lldb_private::Scalar::e_float, lldb_private::Scalar::e_int, lldb_private::Scalar::e_void, lldb_private::Scalar::IsZero(), lldb_private::Scalar::m_float, lldb_private::Scalar::m_integer, lldb_private::Scalar::m_type, and lldb_private::Scalar::PromoteToMaxType().
operator<() [1/9]
bool lldb_private::operator< (const Address & lhs, const Address & rhs)
Definition at line 980 of file Address.cpp.
References lldb_private::Address::GetFileAddress(), and lldb_private::Address::GetModule().
operator<() [2/9]
bool lldb_private::operator< (const ArchSpec & lhs, const ArchSpec & rhs)
operator.
Tests two ArchSpec objects to see if lhs is less than rhs.
Parameters
[in] lhs The Left Hand Side ArchSpec object to compare.
[in] rhs The Left Hand Side ArchSpec object to compare.
Returns
true if lhs is less than rhs
Definition at line 1400 of file ArchSpec.cpp.
References lldb_private::ArchSpec::GetCore().
operator<() [3/9]
bool lldb_private::operator< (const LineEntry & lhs, const LineEntry & rhs)
Less than operator.
Parameters
[in] lhs The Left Hand Side const LineEntry object reference.
[in] rhs The Right Hand Side const LineEntry object reference.
Returns
Returns true if lhs < rhs, false otherwise.
Definition at line 144 of file LineEntry.cpp.
References lldb_private::LineEntry::Compare().
operator<() [4/9]
bool lldb_private::operator< (const MemoryRegionInfo & lhs, const MemoryRegionInfo & rhs) inline
Definition at line 161 of file MemoryRegionInfo.h.
References lldb_private::MemoryRegionInfo::GetRange().
operator<() [5/9]
bool lldb_private::operator< (const MemoryRegionInfo & lhs, lldb::addr_t rhs) inline
Definition at line 166 of file MemoryRegionInfo.h.
References lldb_private::MemoryRegionInfo::GetRange(), and lldb_private::Range< B, S >::GetRangeBase().
operator<() [6/9]
bool lldb_private::operator< (const Scalar & lhs, const Scalar & rhs)
Definition at line 900 of file Scalar.cpp.
References compare().
operator<() [7/9]
bool lldb_private::operator< (const StackID & lhs, const StackID & rhs)
Definition at line 72 of file StackID.cpp.
References lldb_private::SymbolContext::block, lldb_private::SymbolContextScope::CalculateSymbolContext(), lldb_private::Block::Contains(), lldb_private::SymbolContext::function, lldb_private::StackID::GetCallFrameAddressWithoutMetadata(), and lldb_private::StackID::GetSymbolContextScope().
operator<() [8/9]
bool lldb_private::operator< (const VMRange & lhs, const VMRange & rhs)
Definition at line 51 of file VMRange.cpp.
References lldb_private::VMRange::GetBaseAddress(), and lldb_private::VMRange::GetEndAddress().
operator<() [9/9]
bool lldb_private::operator< (lldb::addr_t lhs, const MemoryRegionInfo & rhs) inline
Definition at line 170 of file MemoryRegionInfo.h.
References lldb_private::MemoryRegionInfo::GetRange(), and lldb_private::Range< B, S >::GetRangeBase().
operator<<() [1/11]
const Scalar lldb_private::operator<< (const Scalar & lhs, const Scalar & rhs)
Definition at line 636 of file Scalar.cpp.
operator<<() [2/11]
llvm::raw_ostream & lldb_private::operator<< (llvm::raw_ostream & os, const CompilerContext & rhs)
Definition at line 43 of file Type.cpp.
References lldb_private::CompilerContext::Dump(), and lldb_private::StreamString::GetString().
operator<<() [3/11]
llvm::raw_ostream & lldb_private::operator<< (llvm::raw_ostream & OS, const MemoryRegionInfo & Info)
Definition at line 13 of file MemoryRegionInfo.cpp.
References OS.
operator<<() [4/11]
llvm::raw_ostream & lldb_private::operator<< (llvm::raw_ostream & os, const Scalar & scalar)
Definition at line 944 of file Scalar.cpp.
References lldb_private::StreamString::GetString(), and lldb_private::Scalar::GetValue().
operator<<() [5/11]
llvm::raw_ostream & lldb_private::operator<< (llvm::raw_ostream & OS, const Socket::HostAndPort & HP)
Definition at line 492 of file Socket.cpp.
References lldb_private::Socket::HostAndPort::hostname, OS, and lldb_private::Socket::HostAndPort::port.
operator<<() [6/11]
llvm::raw_ostream & lldb_private::operator<< (llvm::raw_ostream & OS, const URI & U)
Definition at line 20 of file UriParser.cpp.
References lldb_private::URI::hostname, OS, lldb_private::URI::path, lldb_private::URI::port, and lldb_private::URI::scheme.
operator<<() [7/11]
Stream & lldb_private::operator<< (Stream & s, const FileSpec & f)
Dump a FileSpec object to a stream.
Definition at line 252 of file FileSpec.cpp.
References lldb_private::Stream::AsRawOstream(), and lldb_private::FileSpec::Dump().
operator<<() [8/11]
Stream & lldb_private::operator<< (Stream & s, const Mangled & obj)
operator<<() [9/11]
Stream & lldb_private::operator<< (Stream & s, const SourceLocationSpec & loc)
Dump a SourceLocationSpec object to a stream.
Definition at line 42 of file SourceLocationSpec.cpp.
References lldb_private::SourceLocationSpec::Dump().
operator<<() [10/11]
Stream & lldb_private::operator<< (Stream & s, ConstString str)
Stream the string value str to the stream s.
Definition at line 235 of file ConstString.cpp.
References lldb_private::ConstString::GetCString().
operator<<() [11/11]
Stream & lldb_private::operator<< (Stream & strm, const UserID & uid)
Stream the UserID object to a Stream.
Definition at line 17 of file UserID.cpp.
References lldb_private::UserID::GetID(), and lldb_private::Stream::Printf().
operator<=() [1/2]
bool lldb_private::operator<= (const Scalar & lhs, const Scalar & rhs)
Definition at line 904 of file Scalar.cpp.
References compare().
operator<=() [2/2]
bool lldb_private::operator<= (const VMRange & lhs, const VMRange & rhs)
Definition at line 59 of file VMRange.cpp.
operator==() [1/15]
bool lldb_private::operator== (const Address & lhs, const Address & rhs)
Definition at line 1011 of file Address.cpp.
References lldb_private::Address::GetOffset(), and lldb_private::Address::GetSection().
operator==() [2/15]
bool lldb_private::operator== (const ArchSpec & lhs, const ArchSpec & rhs)
Definition at line 1406 of file ArchSpec.cpp.
References lldb_private::ArchSpec::GetCore().
operator==() [3/15]
bool lldb_private::operator== (const CompilerDecl & lhs, const CompilerDecl & rhs)
Definition at line 44 of file CompilerDecl.cpp.
References lldb_private::CompilerDecl::GetOpaqueDecl(), and lldb_private::CompilerDecl::GetTypeSystem().
operator==() [4/15]
bool lldb_private::operator== (const CompilerDeclContext & lhs, const CompilerDeclContext & rhs)
Definition at line 69 of file CompilerDeclContext.cpp.
References lldb_private::CompilerDeclContext::GetOpaqueDeclContext(), and lldb_private::CompilerDeclContext::GetTypeSystem().
operator==() [5/15]
bool lldb_private::operator== (const CompilerType & lhs, const CompilerType & rhs)
Definition at line 1219 of file CompilerType.cpp.
References lldb_private::CompilerType::GetOpaqueQualType(), and lldb_private::CompilerType::GetTypeSystem().
operator==() [6/15]
bool lldb_private::operator== (const Declaration & lhs, const Declaration & rhs)
Definition at line 79 of file Declaration.cpp.
References lldb_private::Declaration::GetColumn(), lldb_private::Declaration::GetFile(), and lldb_private::Declaration::GetLine().
operator==() [7/15]
bool lldb_private::operator== (const ProcessModID & lhs, const ProcessModID & rhs) inline
Definition at line 337 of file Process.h.
operator==() [8/15]
bool lldb_private::operator== (const Scalar & lhs, const Scalar & rhs)
Definition at line 892 of file Scalar.cpp.
References compare().
operator==() [9/15]
bool lldb_private::operator== (const SourceManager::File & lhs, const SourceManager::File & rhs)
Definition at line 759 of file SourceManager.cpp.
References lldb_private::SupportFile::eEqualChecksumIfSet, lldb_private::SourceManager::File::GetSupportFile(), and lldb_private::SourceManager::File::m_mod_time.
operator==() [10/15]
bool lldb_private::operator== (const StackID & lhs, const StackID & rhs)
Definition at line 53 of file StackID.cpp.
References lldb_private::StackID::GetCallFrameAddressWithoutMetadata(), lldb_private::StackID::GetPC(), and lldb_private::StackID::GetSymbolContextScope().
operator==() [11/15]
bool lldb_private::operator== (const SymbolContext & lhs, const SymbolContext & rhs)
Definition at line 325 of file SymbolContext.cpp.
References lldb_private::SymbolContext::CompareWithoutSymbol(), and lldb_private::SymbolContext::symbol.
operator==() [12/15]
bool lldb_private::operator== (const SymbolContextList & lhs, const SymbolContextList & rhs)
Definition at line 1306 of file SymbolContext.cpp.
References lldb_private::SymbolContextList::GetContextAtIndex(), and lldb_private::SymbolContextList::GetSize().
operator==() [13/15]
bool lldb_private::operator== (const UserID & lhs, const UserID & rhs) inline
Definition at line 60 of file UserID.h.
References lldb_private::UserID::GetID().
operator==() [14/15]
bool lldb_private::operator== (const VMRange & lhs, const VMRange & rhs)
Definition at line 42 of file VMRange.cpp.
References lldb_private::VMRange::GetBaseAddress(), and lldb_private::VMRange::GetEndAddress().
operator==() [15/15]
bool lldb_private::operator== (WaitStatus a, WaitStatus b) inline
Definition at line 72 of file Host.h.
References lldb_private::WaitStatus::status, and lldb_private::WaitStatus::type.
operator>() [1/3]
bool lldb_private::operator> (const Address & lhs, const Address & rhs)
Definition at line 995 of file Address.cpp.
References lldb_private::Address::GetFileAddress(), and lldb_private::Address::GetModule().
operator>() [2/3]
bool lldb_private::operator> (const Scalar & lhs, const Scalar & rhs)
Definition at line 909 of file Scalar.cpp.
References compare().
operator>() [3/3]
bool lldb_private::operator> (const VMRange & lhs, const VMRange & rhs)
Definition at line 63 of file VMRange.cpp.
operator>=() [1/2]
bool lldb_private::operator>= (const Scalar & lhs, const Scalar & rhs)
Definition at line 913 of file Scalar.cpp.
References compare().
operator>=() [2/2]
bool lldb_private::operator>= (const VMRange & lhs, const VMRange & rhs)
Definition at line 67 of file VMRange.cpp.
operator>>()
const Scalar lldb_private::operator>> (const Scalar & lhs, const Scalar & rhs)
Definition at line 642 of file Scalar.cpp.
operator^()
const Scalar lldb_private::operator^ (Scalar lhs, Scalar rhs)
Definition at line 625 of file Scalar.cpp.
References lldb_private::Scalar::e_int, lldb_private::Scalar::e_void, lldb_private::Scalar::m_integer, lldb_private::Scalar::m_type, and lldb_private::Scalar::PromoteToMaxType().
operator|()
const Scalar lldb_private::operator| (Scalar lhs, Scalar rhs)
Definition at line 602 of file Scalar.cpp.
References lldb_private::Scalar::e_int, lldb_private::Scalar::e_void, lldb_private::Scalar::m_integer, lldb_private::Scalar::m_type, and lldb_private::Scalar::PromoteToMaxType().
ParseLinuxMapRegions()
void lldb_private::ParseLinuxMapRegions (llvm::StringRef linux_map, LinuxMapCallback const & callback)
Definition at line 123 of file LinuxProcMaps.cpp.
References Maps, and ParseMemoryRegionInfoFromProcMapsLine().
Referenced by CreateRegionsCacheFromLinuxMaps(), and lldb_private::process_linux::NativeProcessLinux::PopulateMemoryRegionCache().
ParseLinuxSMapRegions()
void lldb_private::ParseLinuxSMapRegions (llvm::StringRef linux_smap, LinuxMapCallback const & callback)
Definition at line 134 of file LinuxProcMaps.cpp.
References lldb_private::MemoryRegionInfo::eNo, lldb_private::MemoryRegionInfo::eYes, ParseMemoryRegionInfoFromProcMapsLine(), ProcMapError(), and SMaps.
Referenced by lldb_private::process_linux::NativeProcessLinux::PopulateMemoryRegionCache().
ParseMachCPUDashSubtypeTriple()
bool lldb_private::ParseMachCPUDashSubtypeTriple (llvm::StringRef triple_str, ArchSpec & arch)
Definition at line 745 of file ArchSpec.cpp.
References eArchTypeMachO, lldb_private::ArchSpec::GetTriple(), and lldb_private::ArchSpec::SetArchitecture().
Referenced by lldb_private::ArchSpec::SetTriple().
PrintSeverity()
llvm::raw_ostream & lldb_private::PrintSeverity (Stream & stream, lldb::Severity severity) static
Definition at line 65 of file DiagnosticsRendering.cpp.
References lldb_private::Stream::AsRawOstream(), lldb::eSeverityError, lldb::eSeverityInfo, and lldb::eSeverityWarning.
Referenced by RenderDiagnosticDetails().
R4_TYPE_INST() [1/8]
lldb_private::R4_TYPE_INST (FMADD_D)
R4_TYPE_INST() [2/8]
lldb_private::R4_TYPE_INST (FMADD_S)
R4_TYPE_INST() [3/8]
lldb_private::R4_TYPE_INST (FMSUB_D)
R4_TYPE_INST() [4/8]
lldb_private::R4_TYPE_INST (FMSUB_S)
R4_TYPE_INST() [5/8]
lldb_private::R4_TYPE_INST (FNMADD_D)
R4_TYPE_INST() [6/8]
lldb_private::R4_TYPE_INST (FNMADD_S)
R4_TYPE_INST() [7/8]
lldb_private::R4_TYPE_INST (FNMSUB_D)
R4_TYPE_INST() [8/8]
lldb_private::R4_TYPE_INST (FNMSUB_S)
R_RS1_TYPE_INST() [1/2]
lldb_private::R_RS1_TYPE_INST (LR_D)
R_RS1_TYPE_INST() [2/2]
lldb_private::R_RS1_TYPE_INST (LR_W)
R_SHAMT_TYPE_INST() [1/6]
lldb_private::R_SHAMT_TYPE_INST (SLLI)
R_SHAMT_TYPE_INST() [2/6]
lldb_private::R_SHAMT_TYPE_INST (SLLIW)
R_SHAMT_TYPE_INST() [3/6]
lldb_private::R_SHAMT_TYPE_INST (SRAI)
R_SHAMT_TYPE_INST() [4/6]
lldb_private::R_SHAMT_TYPE_INST (SRAIW)
R_SHAMT_TYPE_INST() [5/6]
lldb_private::R_SHAMT_TYPE_INST (SRLI)
R_SHAMT_TYPE_INST() [6/6]
lldb_private::R_SHAMT_TYPE_INST (SRLIW)
R_TYPE_INST() [1/72]
lldb_private::R_TYPE_INST (ADD)
R_TYPE_INST() [2/72]
lldb_private::R_TYPE_INST (ADDW)
R_TYPE_INST() [3/72]
lldb_private::R_TYPE_INST (AMOADD_D)
R_TYPE_INST() [4/72]
lldb_private::R_TYPE_INST (AMOADD_W)
R_TYPE_INST() [5/72]
lldb_private::R_TYPE_INST (AMOAND_D)
R_TYPE_INST() [6/72]
lldb_private::R_TYPE_INST (AMOAND_W)
R_TYPE_INST() [7/72]
lldb_private::R_TYPE_INST (AMOMAX_D)
R_TYPE_INST() [8/72]
lldb_private::R_TYPE_INST (AMOMAX_W)
R_TYPE_INST() [9/72]
lldb_private::R_TYPE_INST (AMOMAXU_D)
R_TYPE_INST() [10/72]
lldb_private::R_TYPE_INST (AMOMAXU_W)
R_TYPE_INST() [11/72]
lldb_private::R_TYPE_INST (AMOMIN_D)
R_TYPE_INST() [12/72]
lldb_private::R_TYPE_INST (AMOMIN_W)
R_TYPE_INST() [13/72]
lldb_private::R_TYPE_INST (AMOMINU_D)
R_TYPE_INST() [14/72]
lldb_private::R_TYPE_INST (AMOMINU_W)
R_TYPE_INST() [15/72]
lldb_private::R_TYPE_INST (AMOOR_D)
R_TYPE_INST() [16/72]
lldb_private::R_TYPE_INST (AMOOR_W)
R_TYPE_INST() [17/72]
lldb_private::R_TYPE_INST (AMOSWAP_D)
R_TYPE_INST() [18/72]
lldb_private::R_TYPE_INST (AMOSWAP_W)
R_TYPE_INST() [19/72]
lldb_private::R_TYPE_INST (AMOXOR_D)
R_TYPE_INST() [20/72]
lldb_private::R_TYPE_INST (AMOXOR_W)
R_TYPE_INST() [21/72]
lldb_private::R_TYPE_INST (AND)
R_TYPE_INST() [22/72]
lldb_private::R_TYPE_INST (DIV)
R_TYPE_INST() [23/72]
lldb_private::R_TYPE_INST (DIVU)
R_TYPE_INST() [24/72]
lldb_private::R_TYPE_INST (DIVUW)
R_TYPE_INST() [25/72]
lldb_private::R_TYPE_INST (DIVW)
R_TYPE_INST() [26/72]
lldb_private::R_TYPE_INST (FADD_D)
R_TYPE_INST() [27/72]
lldb_private::R_TYPE_INST (FADD_S)
R_TYPE_INST() [28/72]
lldb_private::R_TYPE_INST (FDIV_D)
R_TYPE_INST() [29/72]
lldb_private::R_TYPE_INST (FDIV_S)
R_TYPE_INST() [30/72]
lldb_private::R_TYPE_INST (FEQ_D)
R_TYPE_INST() [31/72]
lldb_private::R_TYPE_INST (FEQ_S)
R_TYPE_INST() [32/72]
lldb_private::R_TYPE_INST (FLE_D)
R_TYPE_INST() [33/72]
lldb_private::R_TYPE_INST (FLE_S)
R_TYPE_INST() [34/72]
lldb_private::R_TYPE_INST (FLT_D)
R_TYPE_INST() [35/72]
lldb_private::R_TYPE_INST (FLT_S)
R_TYPE_INST() [36/72]
lldb_private::R_TYPE_INST (FMAX_D)
R_TYPE_INST() [37/72]
lldb_private::R_TYPE_INST (FMAX_S)
R_TYPE_INST() [38/72]
lldb_private::R_TYPE_INST (FMIN_D)
R_TYPE_INST() [39/72]
lldb_private::R_TYPE_INST (FMIN_S)
R_TYPE_INST() [40/72]
lldb_private::R_TYPE_INST (FMUL_D)
R_TYPE_INST() [41/72]
lldb_private::R_TYPE_INST (FMUL_S)
R_TYPE_INST() [42/72]
lldb_private::R_TYPE_INST (FSGNJ_D)
R_TYPE_INST() [43/72]
lldb_private::R_TYPE_INST (FSGNJ_S)
R_TYPE_INST() [44/72]
lldb_private::R_TYPE_INST (FSGNJN_D)
R_TYPE_INST() [45/72]
lldb_private::R_TYPE_INST (FSGNJN_S)
R_TYPE_INST() [46/72]
lldb_private::R_TYPE_INST (FSGNJX_D)
R_TYPE_INST() [47/72]
lldb_private::R_TYPE_INST (FSGNJX_S)
R_TYPE_INST() [48/72]
lldb_private::R_TYPE_INST (FSUB_D)
R_TYPE_INST() [49/72]
lldb_private::R_TYPE_INST (FSUB_S)
R_TYPE_INST() [50/72]
lldb_private::R_TYPE_INST (MUL)
R_TYPE_INST() [51/72]
lldb_private::R_TYPE_INST (MULH)
R_TYPE_INST() [52/72]
lldb_private::R_TYPE_INST (MULHSU)
R_TYPE_INST() [53/72]
lldb_private::R_TYPE_INST (MULHU)
R_TYPE_INST() [54/72]
lldb_private::R_TYPE_INST (MULW)
R_TYPE_INST() [55/72]
lldb_private::R_TYPE_INST (OR)
R_TYPE_INST() [56/72]
lldb_private::R_TYPE_INST (REM)
R_TYPE_INST() [57/72]
lldb_private::R_TYPE_INST (REMU)
R_TYPE_INST() [58/72]
lldb_private::R_TYPE_INST (REMUW)
R_TYPE_INST() [59/72]
lldb_private::R_TYPE_INST (REMW)
R_TYPE_INST() [60/72]
lldb_private::R_TYPE_INST (SC_D)
R_TYPE_INST() [61/72]
lldb_private::R_TYPE_INST (SC_W)
R_TYPE_INST() [62/72]
lldb_private::R_TYPE_INST (SLL)
R_TYPE_INST() [63/72]
lldb_private::R_TYPE_INST (SLLW)
R_TYPE_INST() [64/72]
lldb_private::R_TYPE_INST (SLT)
R_TYPE_INST() [65/72]
lldb_private::R_TYPE_INST (SLTU)
R_TYPE_INST() [66/72]
lldb_private::R_TYPE_INST (SRA)
R_TYPE_INST() [67/72]
lldb_private::R_TYPE_INST (SRAW)
R_TYPE_INST() [68/72]
lldb_private::R_TYPE_INST (SRL)
R_TYPE_INST() [69/72]
lldb_private::R_TYPE_INST (SRLW)
R_TYPE_INST() [70/72]
lldb_private::R_TYPE_INST (SUB)
R_TYPE_INST() [71/72]
lldb_private::R_TYPE_INST (SUBW)
R_TYPE_INST() [72/72]
lldb_private::R_TYPE_INST (XOR)
RegisterAbortWithPayloadFrameRecognizer()
void lldb_private::RegisterAbortWithPayloadFrameRecognizer (Process * process)
Definition at line 28 of file AbortWithPayloadFrameRecognizer.cpp.
References lldb_private::StackFrameRecognizerManager::AddRecognizer(), lldb_private::Mangled::ePreferDemangled, lldb_private::Target::GetFrameRecognizerManager(), and lldb_private::Process::GetTarget().
Referenced by SystemRuntimeMacOSX::SystemRuntimeMacOSX().
RegisterAssertFrameRecognizer()
void lldb_private::RegisterAssertFrameRecognizer (Process * process)
Registers the assert stack frame recognizer.
Parameters
[in] process The process that is currently asserting. This will give us information on the target and the platform.
Definition at line 80 of file AssertFrameRecognizer.cpp.
References lldb_private::StackFrameRecognizerManager::AddRecognizer(), lldb_private::Mangled::ePreferDemangled, GetAbortLocation(), lldb_private::Target::GetArchitecture(), lldb_private::FileSpec::GetFilename(), lldb_private::Target::GetFrameRecognizerManager(), lldb_private::ConstString::GetStringRef(), lldb_private::Process::GetTarget(), lldb_private::ArchSpec::GetTriple(), lldb_private::SymbolLocation::module_spec, lldb_private::SymbolLocation::symbols, and lldb_private::SymbolLocation::symbols_are_regex.
Referenced by lldb_private::Process::Process().
RegisterNameHelpTextCallback()
llvm::StringRef lldb_private::RegisterNameHelpTextCallback ()
Definition at line 18 of file CommandOptionArgumentTable.cpp.
RegisterVerboseTrapFrameRecognizer()
void lldb_private::RegisterVerboseTrapFrameRecognizer (Process & process)
Definition at line 124 of file VerboseTrapFrameRecognizer.cpp.
References lldb_private::StackFrameRecognizerManager::AddRecognizer(), lldb_private::Mangled::ePreferDemangled, lldb_private::Target::GetFrameRecognizerManager(), and lldb_private::Process::GetTarget().
Referenced by lldb_private::CPPLanguageRuntime::CPPLanguageRuntime().
RenderDiagnosticDetails()
void lldb_private::RenderDiagnosticDetails (Stream & stream, std::optional< uint16_t > offset_in_command, bool show_inline, llvm::ArrayRef< DiagnosticDetail > details, bool force_ascii = false)
Renders an array of DiagnosticDetail instances.
Parameters
[in] stream The stream to render the diagnostics to.
offset_in_command An optional offset to the column position of the diagnostic in the source.
show_inline Whether to show the diagnostics inline.
details The array of DiagnosticsDetail to render.
force_ascii Whether to force ascii rendering. If false, Unicode characters will be used if the output file supports them.
See also
lldb_private::Terminal::SupportsUnicode
Definition at line 87 of file DiagnosticsRendering.cpp.
References PrintSeverity(), lldb_private::DiagnosticDetail::source_location, and lldb_private::Terminal::SupportsUnicode().
Referenced by lldb_private::CommandReturnObject::GetErrorString(), and lldb_private::CommandReturnObject::GetInlineDiagnosticString().
ROR()
uint32_t lldb_private::ROR (const uint32_t value, const uint32_t amount, bool * success) inline static
Definition at line 182 of file ARMUtils.h.
References ROR_C().
Referenced by lldb_private::EmulateInstructionARM::EmulateLDRImmediateARM(), lldb_private::EmulateInstructionARM::EmulateLDRRegister(), lldb_private::EmulateInstructionARM::EmulateLDRRtPCRelative(), lldb_private::EmulateInstructionARM::EmulateSXTB(), lldb_private::EmulateInstructionARM::EmulateSXTH(), lldb_private::EmulateInstructionARM::EmulateUXTB(), and lldb_private::EmulateInstructionARM::EmulateUXTH().
ror()
uint32_t lldb_private::ror (uint32_t val, uint32_t N, uint32_t shift) static
Definition at line 274 of file ARMUtils.h.
Referenced by ARMExpandImm_C(), and ThumbExpandImm_C().
ROR_C()
uint32_t lldb_private::ROR_C (const uint32_t value, const uint32_t amount, uint32_t & carry_out, bool * success) inline static
Definition at line 170 of file ARMUtils.h.
References Bit32().
Referenced by ROR(), and Shift_C().
Rotl32()
uint32_t lldb_private::Rotl32 (uint32_t bits, uint32_t amt) inline static
Definition at line 67 of file InstructionUtils.h.
References bits().
Rotr32()
uint32_t lldb_private::Rotr32 (uint32_t bits, uint32_t amt) inline static
Definition at line 61 of file InstructionUtils.h.
References bits().
RRX()
uint32_t lldb_private::RRX (const uint32_t value, const uint32_t carry_in, bool * success) inline static
Definition at line 202 of file ARMUtils.h.
References RRX_C().
RRX_C()
uint32_t lldb_private::RRX_C (const uint32_t value, const uint32_t carry_in, uint32_t & carry_out, bool * success) inline static
Definition at line 195 of file ARMUtils.h.
References Bit32(), and Bits32().
Referenced by RRX(), and Shift_C().
S_TYPE_INST() [1/6]
lldb_private::S_TYPE_INST (FSD)
S_TYPE_INST() [2/6]
lldb_private::S_TYPE_INST (FSW)
S_TYPE_INST() [3/6]
lldb_private::S_TYPE_INST (SB)
S_TYPE_INST() [4/6]
lldb_private::S_TYPE_INST (SD)
S_TYPE_INST() [5/6]
lldb_private::S_TYPE_INST (SH)
S_TYPE_INST() [6/6]
lldb_private::S_TYPE_INST (SW)
SaveMiniDump()
bool lldb_private::SaveMiniDump (const lldb::ProcessSP & process_sp, SaveCoreOptions & core_options, lldb_private::Status & error)
Definition at line 23 of file WindowsMiniDump.cpp.
References lldb::eErrorTypeWin32, error(), lldb_private::Status::FromErrorString(), lldb_private::SaveCoreOptions::GetOutputFile(), and Status.
Referenced by ObjectFilePECOFF::SaveCore().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointLocationSP >()
template<> lldb::BreakpointLocationSP lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointLocationSP > (python::PythonObject & p, Status & error)
References error(), and lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointSP >()
template<> lldb::BreakpointSP lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointSP > (python::PythonObject & p, Status & error)
References error(), and lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::DataExtractorSP >()
template<> lldb::DataExtractorSP lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::DataExtractorSP > (python::PythonObject & p, Status & error)
References error(), and lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::DescriptionLevel >()
template<> lldb::DescriptionLevel lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::DescriptionLevel > (python::PythonObject & p, Status & error)
References error(), and lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ExecutionContextRefSP >()
template<> lldb::ExecutionContextRefSP lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ExecutionContextRefSP > (python::PythonObject & p, Status & error)
References error(), and lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessAttachInfoSP >()
template<> lldb::ProcessAttachInfoSP lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessAttachInfoSP > (python::PythonObject & p, Status & error)
References error(), and lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessLaunchInfoSP >()
template<> lldb::ProcessLaunchInfoSP lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessLaunchInfoSP > (python::PythonObject & p, Status & error)
References error(), and lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameListSP >()
template<> lldb::StackFrameListSP lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameListSP > (python::PythonObject & p, Status & error)
References error(), and lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameSP >()
template<> lldb::StackFrameSP lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameSP > (python::PythonObject & p, Status & error)
References error(), and lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StreamSP >()
template<> lldb::StreamSP lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StreamSP > (python::PythonObject & p, Status & error)
References error(), and lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ThreadSP >()
template<> lldb::ThreadSP lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ThreadSP > (python::PythonObject & p, Status & error)
References error(), and lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectListSP >()
template<> lldb::ValueObjectListSP lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectListSP > (python::PythonObject & p, Status & error)
References error(), and lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectSP >()
template<> lldb::ValueObjectSP lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectSP > (python::PythonObject & p, Status & error)
References error(), and lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject().
ScriptedPythonInterface::ExtractValueFromPythonObject< std::optional< MemoryRegionInfo > >()
template<> std::optional< MemoryRegionInfo > lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< std::optional< MemoryRegionInfo > > (python::PythonObject & p, Status & error)
ScriptedPythonInterface::ExtractValueFromPythonObject< StructuredData::ArraySP >()
template<> StructuredData::ArraySP lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< StructuredData::ArraySP > (python::PythonObject & p, Status & error)
References error(), and lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject().
ScriptedPythonInterface::ExtractValueFromPythonObject< StructuredData::DictionarySP >()
template<> StructuredData::DictionarySP lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject< StructuredData::DictionarySP > (python::PythonObject & p, Status & error)
References error(), and lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject().
Serialize()
StructuredData::ObjectSP lldb_private::Serialize (llvm::ArrayRef< DiagnosticDetail > details)
Definition at line 25 of file DiagnosticsRendering.cpp.
References lldb::eSeverityError, lldb::eSeverityInfo, and lldb::eSeverityWarning.
Referenced by lldb_private::StructuredData::Object::DumpToStdout(), lldb_private::DiagnosticError::GetAsStructuredData(), and lldb_private::CommandReturnObject::GetErrorData().
SetBit32()
void lldb_private::SetBit32 (uint32_t & bits, const uint32_t bit, const uint32_t val) inline static
Definition at line 55 of file InstructionUtils.h.
References bit(), bits(), and SetBits32().
Referenced by lldb_private::EmulateInstructionARM::EmulateMUL(), and lldb_private::EmulateInstructionARM::WriteFlags().
SetBits32()
void lldb_private::SetBits32 (uint32_t & bits, const uint32_t msbit, const uint32_t lsbit, const uint32_t val) inline static
Definition at line 46 of file InstructionUtils.h.
References bits().
Referenced by lldb_private::ITSession::ITAdvance(), and SetBit32().
SetLLDBAssertCallback()
void lldb_private::SetLLDBAssertCallback (LLDBAssertCallback callback)
Replace the LLDB assert callback.
Definition at line 66 of file LLDBAssert.cpp.
References g_lldb_assert_callback.
Referenced by lldb_private::SystemInitializerFull::Initialize().
SetLLDBErrorLog()
void lldb_private::SetLLDBErrorLog (Log * log)
Getter and setter for the error log (see g_error_log).
The error log is set to the system log in SystemInitializerFull. We can't use the system log directly because that would violate the layering between Utility and Host.
Definition at line 468 of file Log.cpp.
References g_error_log.
Referenced by lldb_private::SystemInitializerFull::Initialize().
SextW()
template<typename T> std::enable_if_t< sizeof(T)<=4, uint64_t > lldb_private::SextW (T value) constexpr
Definition at line 67 of file EmulateInstructionRISCV.cpp.
Referenced by AtomicSequence(), DecodeUImm(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), and lldb_private::Executor::operator()().
Shift()
uint32_t lldb_private::Shift (const uint32_t value, ARM_ShifterType type, const uint32_t amount, const uint32_t carry_in, bool * success) inline static
Definition at line 253 of file ARMUtils.h.
References Shift_C().
Referenced by lldb_private::EmulateInstructionARM::EmulateADCReg(), lldb_private::EmulateInstructionARM::EmulateADDReg(), lldb_private::EmulateInstructionARM::EmulateADDRegShift(), lldb_private::EmulateInstructionARM::EmulateADDSPRm(), lldb_private::EmulateInstructionARM::EmulateCMNReg(), lldb_private::EmulateInstructionARM::EmulateCMPReg(), lldb_private::EmulateInstructionARM::EmulateLDRBRegister(), lldb_private::EmulateInstructionARM::EmulateLDRHRegister(), lldb_private::EmulateInstructionARM::EmulateLDRRegister(), lldb_private::EmulateInstructionARM::EmulateLDRSBRegister(), lldb_private::EmulateInstructionARM::EmulateLDRSHRegister(), lldb_private::EmulateInstructionARM::EmulateRSBReg(), lldb_private::EmulateInstructionARM::EmulateRSCReg(), lldb_private::EmulateInstructionARM::EmulateSBCReg(), lldb_private::EmulateInstructionARM::EmulateSTRHRegister(), lldb_private::EmulateInstructionARM::EmulateSTRRegister(), lldb_private::EmulateInstructionARM::EmulateSUBReg(), lldb_private::EmulateInstructionARM::EmulateSUBSPcLrEtc(), and lldb_private::EmulateInstructionARM::EmulateSUBSPReg().
Shift_C()
uint32_t lldb_private::Shift_C (const uint32_t value, ARM_ShifterType type, const uint32_t amount, const uint32_t carry_in, uint32_t & carry_out, bool * success) inline static
Definition at line 213 of file ARMUtils.h.
References ASR_C(), LSL_C(), LSR_C(), ROR_C(), RRX_C(), SRType_ASR, SRType_LSL, SRType_LSR, SRType_ROR, and SRType_RRX.
Referenced by lldb_private::EmulateInstructionARM::EmulateANDReg(), lldb_private::EmulateInstructionARM::EmulateASRImm(), lldb_private::EmulateInstructionARM::EmulateASRReg(), lldb_private::EmulateInstructionARM::EmulateBICReg(), lldb_private::EmulateInstructionARM::EmulateEORReg(), lldb_private::EmulateInstructionARM::EmulateLSLImm(), lldb_private::EmulateInstructionARM::EmulateLSLReg(), lldb_private::EmulateInstructionARM::EmulateLSRImm(), lldb_private::EmulateInstructionARM::EmulateLSRReg(), lldb_private::EmulateInstructionARM::EmulateMVNReg(), lldb_private::EmulateInstructionARM::EmulateORRReg(), lldb_private::EmulateInstructionARM::EmulateRORImm(), lldb_private::EmulateInstructionARM::EmulateRORReg(), lldb_private::EmulateInstructionARM::EmulateRRX(), lldb_private::EmulateInstructionARM::EmulateShiftImm(), lldb_private::EmulateInstructionARM::EmulateShiftReg(), lldb_private::EmulateInstructionARM::EmulateTEQReg(), lldb_private::EmulateInstructionARM::EmulateTSTReg(), and Shift().
ShouldUseLLDBServer()
bool lldb_private::ShouldUseLLDBServer () static
Definition at line 95 of file ProcessWindows.cpp.
Referenced by lldb_private::ProcessWindows::Initialize().
SignedBits()
int64_t lldb_private::SignedBits (const uint64_t value, const uint64_t msbit, const uint64_t lsbit) inline static
Definition at line 104 of file InstructionUtils.h.
References BitIsSet(), MaskUpToBit(), and UnsignedBits().
Referenced by EmulateInstructionMIPS::Emulate_ADDiu(), EmulateInstructionMIPS64::Emulate_DADDiu(), EmulateInstructionMIPS64::Emulate_LUI(), EmulateInstructionMIPS::Emulate_LUI(), EmulateInstructionMIPS64::Emulate_SD(), and EmulateInstructionMIPS::Emulate_SW().
SignExt()
int32_t lldb_private::SignExt (uint32_t imm) constexpr
Definition at line 63 of file EmulateInstructionRISCV.cpp.
Referenced by lldb_private::RISCVSingleStepBreakpointLocationsPredictor::HandleAtomicSequence(), lldb_private::Executor::operator()(), and Store().
skipPadding()
bool lldb_private::skipPadding (llvm::DataExtractor & section, llvm::DataExtractor::Cursor & cursor) static
Definition at line 23 of file FormatterSection.cpp.
Referenced by ForEachFormatterInModule().
StateAsCString()
const char * lldb_private::StateAsCString (lldb::StateType state)
Converts a StateType to a C string.
Parameters
[in] state The StateType object to convert.
Returns
A NULL terminated C string that describes state. The returned string comes from constant string buffers and does not need to be freed.
Definition at line 14 of file State.cpp.
References lldb::eStateAttaching, lldb::eStateConnected, lldb::eStateCrashed, lldb::eStateDetached, lldb::eStateExited, lldb::eStateInvalid, lldb::eStateLaunching, lldb::eStateRunning, lldb::eStateStepping, lldb::eStateStopped, lldb::eStateSuspended, and lldb::eStateUnloaded.
Referenced by CommandObjectTargetSymbolsAdd::AddSymbolsForFrame(), CommandObjectTargetSymbolsAdd::AddSymbolsForStack(), lldb_private::process_gdb_remote::ProcessGDBRemote::DoConnectRemote(), CommandObjectPlatformProcessLaunch::DoExecute(), CommandObjectProcessContinue::DoExecute(), CommandObjectProcessKDPPacketSend::DoExecute(), CommandObjectThreadContinue::DoExecute(), ProcessKDP::DoResume(), lldb_private::Process::ProcessEventData::Dump(), DumpTargetInfo(), lldb_private::UserExpression::Evaluate(), llvm::format_provider< lldb::StateType >::format(), lldb::SBProcess::GetDescription(), lldb_private::Process::GetStateChangedEventsPrivate(), lldb_private::Process::GetStatus(), lldb_private::NativeThreadWindows::GetStopReason(), lldb_private::process_freebsd::NativeThreadFreeBSD::GetStopReason(), lldb_private::process_linux::NativeThreadLinux::GetStopReason(), lldb_private::process_netbsd::NativeThreadNetBSD::GetStopReason(), lldb_private::Process::Halt(), lldb_private::Process::HandlePrivateEvent(), lldb_private::Process::HandleProcessStateChangedEvent(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::InitializeDelegate(), lldb_private::ThreadPlanSingleThreadTimeout::IsTimeoutAsyncInterrupt(), lldb_private::process_freebsd::NativeProcessFreeBSD::Kill(), lldb_private::process_netbsd::NativeProcessNetBSD::Kill(), lldb_private::Target::Launch(), lldb_private::Process::LoadCore(), lldb_private::UtilityFunction::MakeFunctionCaller(), lldb_private::Process::PeekAtStateChangedEvents(), lldb_private::Process::AttachCompletionHandler::PerformAction(), DynamicLoaderDarwinKernel::PrivateInitialize(), lldb_private::DynamicLoaderDarwin::PrivateInitialize(), DynamicLoaderDarwinKernel::PrivateProcessStateChanged(), lldb_private::DynamicLoaderDarwin::PrivateProcessStateChanged(), lldb_private::Process::PrivateResume(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerLLGS::ProcessStateChanged(), lldb_private::NativeProcessWindows::Resume(), lldb_private::process_freebsd::NativeProcessFreeBSD::Resume(), lldb_private::process_linux::NativeProcessLinux::Resume(), lldb_private::process_netbsd::NativeProcessNetBSD::Resume(), lldb_private::Process::ResumeSynchronous(), lldb_private::Process::RunPrivateStateThread(), lldb_private::Process::RunThreadPlan(), DynamicLoaderMacOSXDYLD::SetNotificationBreakpoint(), DynamicLoaderDarwinKernel::SetNotificationBreakpointIfNeeded(), lldb_private::Process::SetPrivateState(), lldb_private::Process::SetPublicState(), lldb_private::Process::ShouldBroadcastEvent(), lldb_private::Thread::ShouldReportRun(), lldb::SBDebugger::StateAsCString(), lldb_private::Process::StopForDestroyOrDetach(), lldb_private::process_gdb_remote::ThreadGDBRemote::WillResume(), and lldb_private::ThreadPlan::WillResume().
StateIsRunningState()
bool lldb_private::StateIsRunningState (lldb::StateType state)
Check if a state represents a state where the process or thread is running.
Parameters
[in] state The StateType enumeration value
Returns
true if the state represents a process or thread state where the process or thread is running, false otherwise.
Definition at line 68 of file State.cpp.
References lldb::eStateAttaching, lldb::eStateConnected, lldb::eStateCrashed, lldb::eStateDetached, lldb::eStateExited, lldb::eStateInvalid, lldb::eStateLaunching, lldb::eStateRunning, lldb::eStateStepping, lldb::eStateStopped, lldb::eStateSuspended, and lldb::eStateUnloaded.
Referenced by lldb_private::ThreadList::DidStop(), lldb_private::Process::Halt(), lldb_private::Process::HandlePrivateEvent(), IOHandlerProcessSTDIO::Interrupt(), lldb_private::IOHandlerProcessSTDIOWindows::Interrupt(), lldb_private::CommandInterpreter::IOHandlerInterrupt(), lldb_private::Process::IsRunning(), lldb_private::process_linux::NativeProcessLinux::MonitorSIGTRAP(), IOHandlerProcessSTDIO::Run(), lldb_private::IOHandlerProcessSTDIOWindows::Run(), lldb_private::Process::RunPrivateStateThread(), lldb_private::process_linux::NativeProcessLinux::SignalIfAllThreadsStopped(), lldb::SBDebugger::StateIsRunningState(), lldb_private::process_linux::NativeProcessLinux::StopRunningThreads(), and lldb_private::process_linux::NativeProcessLinux::ThreadWasCreated().
StateIsStoppedState()
bool lldb_private::StateIsStoppedState (lldb::StateType state, bool must_exist)
Check if a state represents a state where the process or thread is stopped.
Stopped can mean stopped when the process is still around, or stopped when the process has exited or doesn't exist yet. The must_exist argument tells us which of these cases is desired.
Parameters
[in] state The StateType enumeration value
[in] must_exist A boolean that indicates the thread must also be alive so states like unloaded or exited won't return true.
Returns
true if the state represents a process or thread state where the process or thread is stopped. If must_exist is true, then the process can't be exited or unloaded, otherwise exited and unloaded or other states where the process no longer exists are considered to be stopped.
Definition at line 89 of file State.cpp.
References lldb::eStateAttaching, lldb::eStateConnected, lldb::eStateCrashed, lldb::eStateDetached, lldb::eStateExited, lldb::eStateInvalid, lldb::eStateLaunching, lldb::eStateRunning, lldb::eStateStepping, lldb::eStateStopped, lldb::eStateSuspended, and lldb::eStateUnloaded.
Referenced by CommandObjectTargetSymbolsAdd::AddSymbolsForFrame(), CommandObjectTargetSymbolsAdd::AddSymbolsForStack(), CommandObjectProcessKDPPacketSend::DoExecute(), DumpTargetInfo(), lldb_private::ExecutionContext::ExecutionContext(), lldb_private::ScriptedProcess::ForceScriptedState(), lldb_private::Process::GetStatus(), lldb_private::Value::GetValueAsData(), lldb_private::process_freebsd::NativeProcessFreeBSD::Halt(), lldb_private::Process::HandlePrivateEvent(), lldb_private::Debugger::HandleProcessEvent(), lldb_private::process_linux::NativeProcessLinux::Interrupt(), lldb::SBThread::IsStopped(), lldb_private::process_linux::NativeThreadLinux::IsStopped(), lldb_private::Process::LoadCore(), lldb_private::process_linux::NativeProcessLinux::MonitorSignal(), lldb_private::Process::ResumeSynchronous(), lldb_private::Process::RunPrivateStateThread(), lldb_private::Process::SetPrivateState(), lldb_private::ExecutionContextRef::SetProcessPtr(), lldb_private::Process::SetPublicState(), lldb_private::NativeProcessProtocol::SetState(), lldb_private::ExecutionContextRef::SetThreadPtr(), lldb::SBDebugger::StateIsStoppedState(), lldb_private::Thread::StepIn(), lldb_private::Thread::StepOut(), lldb_private::Thread::StepOver(), lldb_private::Process::UpdateQueueListIfNeeded(), lldb_private::Process::UpdateThreadListIfNeeded(), lldb_private::Process::WaitForProcessStopPrivate(), and lldb_private::Process::WaitForProcessToStop().
Store()
template<typename I, typename T> std::enable_if_t< is_store< I >, bool > lldb_private::Store (EmulateInstructionRISCV & emulator, I inst) static
Definition at line 281 of file EmulateInstructionRISCV.cpp.
References lldb_private::EmulateInstruction::eContextPushRegisterOnStack, lldb_private::EmulateInstruction::eContextRegisterStore, GPREncodingToRegisterInfo(), LoadStoreAddr(), RISCV_GPR_SP, lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset(), SignExt(), and lldb_private::EmulateInstruction::Context::type.
Referenced by lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), and lldb_private::Executor::operator()().
SummaryStringHelpTextCallback()
llvm::StringRef lldb_private::SummaryStringHelpTextCallback ()
Definition at line 181 of file CommandOptionArgumentTable.cpp.
ThumbExpandImm()
uint32_t lldb_private::ThumbExpandImm (uint32_t opcode) inline static
Definition at line 342 of file ARMUtils.h.
References ThumbExpandImm_C().
Referenced by lldb_private::EmulateInstructionARM::EmulateADCImm(), lldb_private::EmulateInstructionARM::EmulateADDSPImm(), lldb_private::EmulateInstructionARM::EmulateCMNImm(), lldb_private::EmulateInstructionARM::EmulateCMPImm(), lldb_private::EmulateInstructionARM::EmulateRSBImm(), lldb_private::EmulateInstructionARM::EmulateSBCImm(), lldb_private::EmulateInstructionARM::EmulateSUBImmThumb(), and lldb_private::EmulateInstructionARM::EmulateSUBSPImm().
ThumbExpandImm_C()
uint32_t lldb_private::ThumbExpandImm_C (uint32_t opcode, uint32_t carry_in, uint32_t & carry_out) inline static
Definition at line 304 of file ARMUtils.h.
References bit, Bit32(), bits(), and ror().
Referenced by lldb_private::EmulateInstructionARM::EmulateADDImmThumb(), lldb_private::EmulateInstructionARM::EmulateANDImm(), lldb_private::EmulateInstructionARM::EmulateBICImm(), lldb_private::EmulateInstructionARM::EmulateEORImm(), lldb_private::EmulateInstructionARM::EmulateMOVRdImm(), lldb_private::EmulateInstructionARM::EmulateMVNImm(), lldb_private::EmulateInstructionARM::EmulateORRImm(), lldb_private::EmulateInstructionARM::EmulateTEQImm(), lldb_private::EmulateInstructionARM::EmulateTSTImm(), and ThumbExpandImm().
ThumbImm12()
uint32_t lldb_private::ThumbImm12 (uint32_t opcode) inline static
Definition at line 351 of file ARMUtils.h.
References bit, and bits().
Referenced by lldb_private::EmulateInstructionARM::EmulateADR(), lldb_private::EmulateInstructionARM::EmulateSUBImmThumb(), and lldb_private::EmulateInstructionARM::EmulateSUBSPImm().
ThumbImm7Scaled()
uint32_t lldb_private::ThumbImm7Scaled (uint32_t opcode) inline static
Definition at line 360 of file ARMUtils.h.
References bits().
Referenced by lldb_private::EmulateInstructionARM::EmulateADDSPImm(), and lldb_private::EmulateInstructionARM::EmulateSUBSPImm().
ThumbImm8Scaled()
uint32_t lldb_private::ThumbImm8Scaled (uint32_t opcode) inline static
Definition at line 366 of file ARMUtils.h.
References bits().
Referenced by lldb_private::EmulateInstructionARM::EmulateADR().
toJSON() [1/16]
llvm::json::Value lldb_private::toJSON (const HTRBlock & block)
Definition at line 475 of file TraceHTR.cpp.
References lldb_private::HTRBlock::GetMetadata().
toJSON() [2/16]
llvm::json::Value lldb_private::toJSON (const HTRBlockMetadata & metadata)
Definition at line 480 of file TraceHTR.cpp.
References lldb_private::HTRBlockMetadata::GetFunctionCalls(), and lldb_private::HTRBlockMetadata::GetNumInstructions().
toJSON() [3/16]
json::Value lldb_private::toJSON (const JSONUINT64 & uint64, bool hex)
Definition at line 25 of file TraceIntelPTGDBRemotePackets.cpp.
References lldb_private::JSONUINT64::value.
toJSON() [4/16]
json::Value lldb_private::toJSON (const LinuxPerfZeroTscConversion & packet)
Definition at line 89 of file TraceIntelPTGDBRemotePackets.cpp.
References lldb_private::LinuxPerfZeroTscConversion::time_mult, lldb_private::LinuxPerfZeroTscConversion::time_shift, lldb_private::LinuxPerfZeroTscConversion::time_zero, and toJSON().
toJSON() [5/16]
json::Value lldb_private::toJSON (const TraceBinaryData & packet)
Definition at line 83 of file TraceGDBRemotePackets.cpp.
References lldb_private::TraceBinaryData::kind, Object, and lldb_private::TraceBinaryData::size.
toJSON() [6/16]
json::Value lldb_private::toJSON (const TraceCpuState & packet)
Definition at line 129 of file TraceGDBRemotePackets.cpp.
References lldb_private::TraceCpuState::binary_data, lldb_private::TraceCpuState::id, and Object.
toJSON() [7/16]
json::Value lldb_private::toJSON (const lldb_private::TraceGetBinaryDataRequest & packet)
jLLDBTraceGetBinaryData
Definition at line 137 of file TraceGDBRemotePackets.cpp.
References lldb_private::TraceGetBinaryDataRequest::cpu_id, lldb_private::TraceGetBinaryDataRequest::kind, Object, lldb_private::TraceGetBinaryDataRequest::tid, and lldb_private::TraceGetBinaryDataRequest::type.
toJSON() [8/16]
json::Value lldb_private::toJSON (const TraceGetStateRequest & packet)
Definition at line 74 of file TraceGDBRemotePackets.cpp.
References Object, and lldb_private::TraceGetStateRequest::type.
toJSON() [9/16]
json::Value lldb_private::toJSON (const TraceGetStateResponse & packet)
Definition at line 106 of file TraceGDBRemotePackets.cpp.
References lldb_private::TraceGetStateResponse::cpus, Object, lldb_private::TraceGetStateResponse::process_binary_data, lldb_private::TraceGetStateResponse::traced_threads, and lldb_private::TraceGetStateResponse::warnings.
toJSON() [10/16]
llvm::json::Value lldb_private::toJSON (const TraceHTR & htr)
Definition at line 385 of file TraceHTR.cpp.
References lldb_private::TraceHTR::GetBlockLayers(), lldb_private::HTRBlockMetadata::GetFirstInstructionLoadAddress(), lldb_private::TraceHTR::GetInstructionLayer(), lldb_private::IHTRLayer::GetLayerId(), lldb_private::HTRBlock::GetMetadata(), lldb_private::HTRInstructionLayer::GetMetadataByIndex(), lldb_private::HTRBlockMetadata::GetMostFrequentlyCalledFunction(), lldb_private::HTRBlockMetadata::GetNumInstructions(), and toJSON().
toJSON() [11/16]
json::Value lldb_private::toJSON (const TraceIntelPTGetStateResponse & packet)
Definition at line 117 of file TraceIntelPTGDBRemotePackets.cpp.
References toJSON(), lldb_private::TraceIntelPTGetStateResponse::tsc_perf_zero_conversion, and lldb_private::TraceIntelPTGetStateResponse::using_cgroup_filtering.
toJSON() [12/16]
json::Value lldb_private::toJSON (const TraceIntelPTStartRequest & packet)
Definition at line 63 of file TraceIntelPTGDBRemotePackets.cpp.
References lldb_private::TraceIntelPTStartRequest::disable_cgroup_filtering, lldb_private::TraceIntelPTStartRequest::enable_tsc, lldb_private::TraceIntelPTStartRequest::ipt_trace_size, lldb_private::TraceIntelPTStartRequest::per_cpu_tracing, lldb_private::TraceIntelPTStartRequest::process_buffer_size_limit, lldb_private::TraceIntelPTStartRequest::psb_period, and toJSON().
toJSON() [13/16]
json::Value lldb_private::toJSON (const TraceStartRequest & packet)
Definition at line 39 of file TraceGDBRemotePackets.cpp.
References Object, lldb_private::TraceStartRequest::tids, and lldb_private::TraceStartRequest::type.
toJSON() [14/16]
json::Value lldb_private::toJSON (const TraceStopRequest & packet)
Definition at line 61 of file TraceGDBRemotePackets.cpp.
References Object, lldb_private::TraceStopRequest::tids, and lldb_private::TraceStopRequest::type.
toJSON() [15/16]
json::Value lldb_private::toJSON (const TraceSupportedResponse & packet)
Definition at line 24 of file TraceGDBRemotePackets.cpp.
References lldb_private::TraceSupportedResponse::description, lldb_private::TraceSupportedResponse::name, and Object.
Referenced by lldb_private::transport::Binder< Proto >::Bind(), lldb_private::transport::Binder< Proto >::Bind(), lldb_private::TraceHTR::Export(), lldb_private::process_linux::IntelPTCollector::GetState(), lldb_private::mcp::DebuggerResourceProvider::ReadDebuggerResource(), lldb_private::mcp::DebuggerResourceProvider::ReadTargetResource(), lldb_private::transport::Binder< ProtocolDescriptor >::Received(), lldb_private::transport::Binder< ProtocolDescriptor >::Received(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceGetBinaryData(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceGetState(), lldb_private::process_gdb_remote::GDBRemoteCommunicationClient::SendTraceStop(), toJSON(), toJSON(), toJSON(), and toJSON().
toJSON() [16/16]
json::Value lldb_private::toJSON (const TraceThreadState & packet)
Definition at line 93 of file TraceGDBRemotePackets.cpp.
References lldb_private::TraceThreadState::binary_data, Object, and lldb_private::TraceThreadState::tid.
toString() [1/6]
const char * lldb_private::toString (AppleArm64ExceptionClass EC) inline
Definition at line 38 of file AppleArm64ExceptionClass.h.
toString() [2/6]
std::string lldb_private::toString (const FormatterBytecode::DataStack & data)
Definition at line 58 of file FormatterBytecode.cpp.
References toString().
toString() [3/6]
std::string lldb_private::toString (FormatterBytecode::OpCodes op)
Definition at line 23 of file FormatterBytecode.cpp.
Referenced by PSBBlockDecoder::AppendInstructionAndDetectAnomalies(), lldb_private::ScriptInterpreterLua::BreakpointCallbackFunction(), ThreadMachCore::CalculateStopInfo(), lldb_private::trace_intel_pt::TraceIntelPTMultiCpuDecoder::CorrelateContextSwitchesAndIntelPtTraces(), lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::CreateJSONError(), lldb_private::SourceManager::DisplaySourceLinesWithLineNumbersUsingLastFile(), CommandObjectFrameDiagnose::DoExecute(), CommandObjectMemoryRead::DoExecute(), CommandObjectProcessTraceStop::DoExecute(), CommandObjectTraceSave::DoExecute(), lldb_private::CommandObjectDisassemble::DoExecute(), lldb_private::CommandObjectDWIMPrint::DoExecute(), lldb_private::ctf::CommandObjectThreadTraceExportCTF::DoExecute(), lldb_private::LLVMUserExpression::DoExecute(), CommandObjectTraceStop::DoExecuteOnThreads(), lldb_private::CommandObjectTraceProxy::DoGetProxyCommandObject(), lldb_private::ScriptedProcess::DoUpdateThreadList(), lldb_private::Diagnostics::Dump(), lldb_private::Diagnostics::Dump(), lldb_private::SourceManager::SourceFileCache::Dump(), DumpAPInt(), lldb_private::ValueObject::DumpPrintableRepresentation(), lldb_private::Watchpoint::DumpSnapshots(), lldb_private::trace_intel_pt::TraceIntelPT::DumpTraceInfo(), lldb_private::trace_intel_pt::TraceIntelPT::DumpTraceInfoAsJson(), CommandObjectTargetVariable::DumpValueObject(), lldb_private::FunctionCaller::ExecuteFunction(), lldb_private::process_linux::IntelPTCollector::FetchPerfTscConversionParameters(), find_cached_path(), lldb_private::FormatEntity::Formatter::Format(), lldb_private::FormatterBytecode::FormatImpl(), lldb_private::BytecodeSummaryFormat::FormatObject(), lldb::SBValue::GetDescription(), lldb_private::ScriptedFrameProvider::GetFrameAtIndex(), lldb_private::CommandObjectDisassemble::GetNameRanges(), lldb_private::AppleObjCRuntime::GetObjectDescription(), lldb_private::CommandObjectTraceProxy::GetProxyCommandObject(), lldb_private::plugin::dwarf::DWARFUnit::GetRnglistTable(), lldb_private::PlatformMacOSX::GetSDKDirectory(), lldb_private::process_linux::IntelPTCollector::GetState(), lldb_private::Breakpoint::GetStatistics(), GetXcodeSDKDir(), CommandObjectThreadException::HandleOneThread(), CommandObjectThreadSiginfo::HandleOneThread(), IncludePerfEventParanoidMessageInError(), lldb_private::FormatterBytecode::Interpret(), IOHandlerLuaInterpreter::IOHandlerInputComplete(), IOHandlerLuaInterpreter::IOHandlerIsInputComplete(), lldb_private::ScriptedThread::LoadArtificialStackFrames(), lldb::SBTrace::LoadTraceFromFile(), EntityPersistentVariable::MakeAllocation(), EntityResultVariable::Materialize(), EntityVariableBase::Materialize(), ExpressionCategory::message(), lldb_private::Trace::OnDataFileRead(), lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::ParseModule(), lldb_private::LLVMUserExpression::PrepareToExecuteJITExpression(), lldb_private::CommandInterpreter::PreprocessToken(), lldb_private::ValueObjectPrinter::PrintChild(), lldb_private::ClangREPL::PrintOneVariable(), lldb_private::Trace::RefreshLiveProcessState(), lldb_private::Module::RegisterXcodeSDK(), lldb_private::plugin::dwarf::DWARFUnit::SetLoclistsBase(), lldb_private::NativeProcessSoftwareSingleStep::SetupSoftwareSingleStepping(), toString(), and lldb_private::ScriptInterpreterLua::WatchpointCallbackFunction().
toString() [4/6]
std::string lldb_private::toString (FormatterBytecode::Selectors sel)
Definition at line 36 of file FormatterBytecode.cpp.
toString() [5/6]
std::string lldb_private::toString (FormatterBytecode::Signatures sig)
Definition at line 47 of file FormatterBytecode.cpp.
toString() [6/6]
std::string lldb_private::toString (lldb::ExpressionResults e)
Produce a human-readable rendition of an ExpressionResults value.
Definition at line 14 of file ErrorMessages.cpp.
References lldb::eExpressionCompleted, lldb::eExpressionDiscarded, lldb::eExpressionHitBreakpoint, lldb::eExpressionInterrupted, lldb::eExpressionParseError, lldb::eExpressionResultUnavailable, lldb::eExpressionSetupError, lldb::eExpressionStoppedForDebug, lldb::eExpressionThreadVanished, and lldb::eExpressionTimedOut.
U_TYPE_INST() [1/2]
lldb_private::U_TYPE_INST (AUIPC)
U_TYPE_INST() [2/2]
lldb_private::U_TYPE_INST (LUI)
UnsignedBits()
uint64_t lldb_private::UnsignedBits (const uint64_t value, const uint64_t msbit, const uint64_t lsbit) inline static
Definition at line 97 of file InstructionUtils.h.
References MaskUpToBit().
Referenced by lldb_private::EmulateInstructionARM::AddWithCarry(), ASR_C(), EmulateInstructionARM64::ConditionHolds(), lldb_private::EmulateInstructionARM::ConditionPassed(), lldb_private::EmulateInstructionARM::CurrentCond(), and SignedBits().
VASprintf()
bool lldb_private::VASprintf (llvm::SmallVectorImpl< char > & buf, const char * fmt, va_list args)
Definition at line 19 of file VASprintf.cpp.
References error().
Referenced by lldb_private::Status::FromErrorStringWithFormat(), lldb_private::Stream::PrintfAsRawHex8(), lldb_private::File::PrintfVarArg(), lldb_private::Stream::PrintfVarArg(), lldb_private::RegisterContextUnwind::UnwindLogMsg(), lldb_private::RegisterContextUnwind::UnwindLogMsgVerbose(), lldb_private::Log::VAError(), lldb_private::Log::VAFormatf(), lldb_private::Log::VAPrintf(), and lldb_private::Log::Warning().
XStateToYMM()
YMMReg lldb_private::XStateToYMM (const void * xmm_bytes, const void * ymmh_bytes) inline
Definition at line 374 of file RegisterContext_x86.h.
References lldb_private::YMMReg::bytes.
Referenced by RegisterContextPOSIX_x86::CopyXSTATEtoYMM().
YMMToXState()
void lldb_private::YMMToXState (const YMMReg & input, void * xmm_bytes, void * ymmh_bytes) inline
Definition at line 384 of file RegisterContext_x86.h.
References lldb_private::YMMReg::bytes.
Referenced by RegisterContextPOSIX_x86::CopyYMMtoXSTATE().
ZextD()
template<typename T> uint64_t lldb_private::ZextD (T value) constexpr
Definition at line 72 of file EmulateInstructionRISCV.cpp.
Referenced by lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), and lldb_private::Executor::operator()().
zipOpt()
template<typename... Ts> std::optional< std::tuple< Ts... > > lldb_private::zipOpt (std::optional< Ts > &&... ts) static
Returns all values wrapped in Optional, or std::nullopt if any of the values is std::nullopt.
Definition at line 45 of file EmulateInstructionRISCV.cpp.
Referenced by AtomicADD(), AtomicBitOperate(), AtomicCmp(), AtomicSwap(), lldb_private::Executor::F_Compare(), lldb_private::Executor::F_MAX_MIN(), lldb_private::Executor::F_Op(), lldb_private::Executor::F_SignInj(), lldb_private::Executor::F_SignInjXor(), lldb_private::Executor::F_Store(), lldb_private::Executor::FMA(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), and lldb_private::Executor::operator()().
Variable Documentation
AARCH64_FPMR_Desc
RegsetDesc lldb_private::AARCH64_FPMR_Desc[] constexpr
Initial value:
= {
    {llvm::Triple::Linux, llvm::Triple::aarch64, llvm::ELF::NT_ARM_FPMR},
}
Definition at line 147 of file RegisterUtilities.h.
Referenced by RegisterContextCorePOSIX_arm64::Create(), and RegisterContextCorePOSIX_arm64::RegisterContextCorePOSIX_arm64().
AARCH64_GCS_Desc
RegsetDesc lldb_private::AARCH64_GCS_Desc[] constexpr
Initial value:
= {
    {llvm::Triple::Linux, llvm::Triple::aarch64, llvm::ELF::NT_ARM_GCS},
}
Definition at line 151 of file RegisterUtilities.h.
Referenced by RegisterContextCorePOSIX_arm64::Create(), and RegisterContextCorePOSIX_arm64::RegisterContextCorePOSIX_arm64().
AARCH64_MTE_Desc
RegsetDesc lldb_private::AARCH64_MTE_Desc[] constexpr
Initial value:
= {
    {llvm::Triple::Linux, llvm::Triple::aarch64,
     llvm::ELF::NT_ARM_TAGGED_ADDR_CTRL},
}
Definition at line 142 of file RegisterUtilities.h.
Referenced by RegisterContextCorePOSIX_arm64::Create(), and RegisterContextCorePOSIX_arm64::RegisterContextCorePOSIX_arm64().
AARCH64_PAC_Desc
RegsetDesc lldb_private::AARCH64_PAC_Desc[] constexpr
Initial value:
= {
    {llvm::Triple::Linux, llvm::Triple::aarch64, llvm::ELF::NT_ARM_PAC_MASK},
}
Definition at line 134 of file RegisterUtilities.h.
Referenced by RegisterContextCorePOSIX_arm64::Create(), and RegisterContextCorePOSIX_arm64::RegisterContextCorePOSIX_arm64().
AARCH64_POE_Desc
RegsetDesc lldb_private::AARCH64_POE_Desc[] constexpr
Initial value:
= {
    {llvm::Triple::Linux, llvm::Triple::aarch64, llvm::ELF::NT_ARM_POE},
}
Definition at line 155 of file RegisterUtilities.h.
Referenced by RegisterContextCorePOSIX_arm64::Create(), and RegisterContextCorePOSIX_arm64::RegisterContextCorePOSIX_arm64().
AARCH64_SSVE_Desc
RegsetDesc lldb_private::AARCH64_SSVE_Desc[] constexpr
Initial value:
= {
    {llvm::Triple::Linux, llvm::Triple::aarch64, llvm::ELF::NT_ARM_SSVE},
}
Definition at line 122 of file RegisterUtilities.h.
Referenced by RegisterContextCorePOSIX_arm64::Create(), and RegisterContextCorePOSIX_arm64::RegisterContextCorePOSIX_arm64().
AARCH64_SVE_Desc
RegsetDesc lldb_private::AARCH64_SVE_Desc[] constexpr
Initial value:
= {
    {llvm::Triple::Linux, llvm::Triple::aarch64, llvm::ELF::NT_ARM_SVE},
}
Definition at line 118 of file RegisterUtilities.h.
Referenced by RegisterContextCorePOSIX_arm64::Create(), and RegisterContextCorePOSIX_arm64::RegisterContextCorePOSIX_arm64().
AARCH64_TLS_Desc
RegsetDesc lldb_private::AARCH64_TLS_Desc[] constexpr
Initial value:
= {
    {llvm::Triple::Linux, llvm::Triple::aarch64, llvm::ELF::NT_ARM_TLS},
}
Definition at line 138 of file RegisterUtilities.h.
Referenced by RegisterContextCorePOSIX_arm64::Create(), and RegisterContextCorePOSIX_arm64::RegisterContextCorePOSIX_arm64().
AARCH64_ZA_Desc
RegsetDesc lldb_private::AARCH64_ZA_Desc[] constexpr
Initial value:
= {
    {llvm::Triple::Linux, llvm::Triple::aarch64, llvm::ELF::NT_ARM_ZA},
}
Definition at line 126 of file RegisterUtilities.h.
Referenced by RegisterContextCorePOSIX_arm64::Create(), and RegisterContextCorePOSIX_arm64::RegisterContextCorePOSIX_arm64().
AARCH64_ZT_Desc
RegsetDesc lldb_private::AARCH64_ZT_Desc[] constexpr
Initial value:
= {
    {llvm::Triple::Linux, llvm::Triple::aarch64, llvm::ELF::NT_ARM_ZT},
}
Definition at line 130 of file RegisterUtilities.h.
Referenced by RegisterContextCorePOSIX_arm64::Create(), and RegisterContextCorePOSIX_arm64::RegisterContextCorePOSIX_arm64().
ARM_VFP_Desc
RegsetDesc lldb_private::ARM_VFP_Desc[] constexpr
Initial value:
= {
    {llvm::Triple::FreeBSD, llvm::Triple::arm, llvm::ELF::NT_ARM_VFP},
    {llvm::Triple::Linux, llvm::Triple::arm, llvm::ELF::NT_ARM_VFP},
}
Definition at line 159 of file RegisterUtilities.h.
Referenced by RegisterContextCorePOSIX_arm::RegisterContextCorePOSIX_arm().
BEQ
uint32_t lldb_private::BEQ = 0b000 constexpr
Definition at line 55 of file EmulateInstructionRISCV.cpp.
Referenced by CompareB().
BGE
uint32_t lldb_private::BGE = 0b101 constexpr
Definition at line 58 of file EmulateInstructionRISCV.cpp.
Referenced by CompareB().
BGEU
uint32_t lldb_private::BGEU = 0b111 constexpr
Definition at line 60 of file EmulateInstructionRISCV.cpp.
Referenced by CompareB().
BLT
uint32_t lldb_private::BLT = 0b100 constexpr
Definition at line 57 of file EmulateInstructionRISCV.cpp.
Referenced by CompareB().
BLTU
uint32_t lldb_private::BLTU = 0b110 constexpr
Definition at line 59 of file EmulateInstructionRISCV.cpp.
Referenced by CompareB().
BNE
uint32_t lldb_private::BNE = 0b001 constexpr
Definition at line 56 of file EmulateInstructionRISCV.cpp.
Referenced by AtomicSequence(), and CompareB().
FPR_Desc
RegsetDesc lldb_private::FPR_Desc[] constexpr
Initial value:
= {
    {llvm::Triple::FreeBSD, llvm::Triple::x86, llvm::ELF::NT_X86_XSTATE},
    {llvm::Triple::FreeBSD, llvm::Triple::UnknownArch, llvm::ELF::NT_FPREGSET},
    {llvm::Triple::Linux, llvm::Triple::x86, llvm::ELF::NT_PRXFPREG},
    {llvm::Triple::Linux, llvm::Triple::UnknownArch, llvm::ELF::NT_FPREGSET},
    {llvm::Triple::NetBSD, llvm::Triple::aarch64, NETBSD::AARCH64::NT_FPREGS},
    {llvm::Triple::NetBSD, llvm::Triple::x86, NETBSD::I386::NT_FPREGS},
    {llvm::Triple::NetBSD, llvm::Triple::x86_64, NETBSD::AMD64::NT_FPREGS},
    {llvm::Triple::OpenBSD, llvm::Triple::UnknownArch, OPENBSD::NT_FPREGS},
}
Definition at line 102 of file RegisterUtilities.h.
Referenced by RegisterContextCorePOSIX_riscv64::Create(), RegisterContextCorePOSIX_arm64::RegisterContextCorePOSIX_arm64(), RegisterContextCorePOSIX_loongarch64::RegisterContextCorePOSIX_loongarch64(), RegisterContextCorePOSIX_powerpc::RegisterContextCorePOSIX_powerpc(), RegisterContextCorePOSIX_ppc64le::RegisterContextCorePOSIX_ppc64le(), RegisterContextCorePOSIX_s390x::RegisterContextCorePOSIX_s390x(), and RegisterContextCorePOSIX_x86::RegisterContextCorePOSIX_x86().
FunctionCallLabelPrefix
llvm::StringRef lldb_private::FunctionCallLabelPrefix = "$__lldb_func" inline constexpr
LLDB attaches this prefix to mangled names of functions that get called from JITted expressions.
Definition at line 151 of file Expression.h.
Referenced by lldb_private::IRExecutionUnit::FindSymbol(), lldb_private::FunctionCallLabel::fromString(), and lldb_private::FunctionCallLabel::toString().
g_argument_table
CommandObject::ArgumentTableEntry lldb_private::g_argument_table[] static constexpr
Definition at line 235 of file CommandOptionArgumentTable.h.
Referenced by lldb_private::CommandObject::FindArgumentDataByType(), lldb_private::CommandObject::GetArgumentDescriptionAsCString(), lldb_private::CommandObject::GetArgumentHelp(), lldb_private::CommandObject::GetArgumentName(), lldb_private::CommandObject::GetArgumentTypeAsCString(), and lldb_private::CommandObject::LookupArgumentName().
g_auto_download_enum_values
OptionEnumValueElement lldb_private::g_auto_download_enum_values[] static constexpr
Initial value:
= {
    {
        lldb::eSymbolDownloadOff,
        "off",
        "Disable automatically downloading symbols.",
    },
    {
        lldb::eSymbolDownloadBackground,
        "background",
        "Download symbols in the background for images as they appear in the "
        "backtrace.",
    },
    {
        lldb::eSymbolDownloadForeground,
        "foreground",
        "Download symbols in the foreground for images as they appear in the "
        "backtrace.",
    },
}
Definition at line 51 of file ModuleList.h.
g_bool_parsing_error_message
llvm::StringLiteral lldb_private::g_bool_parsing_error_message static constexpr
Initial value:
=
    "Failed to parse as boolean"
Definition at line 367 of file Options.h.
Referenced by BreakpointAccessOptionGroup::SetOptionValue(), BreakpointNameOptionGroup::SetOptionValue(), CommandObjectBreakpointAddFile::CommandOptions::SetOptionValue(), CommandObjectBreakpointAddName::CommandOptions::SetOptionValue(), CommandObjectBreakpointAddPattern::CommandOptions::SetOptionValue(), CommandObjectBreakpointSet::CommandOptions::SetOptionValue(), and lldb_private::BreakpointOptionGroup::SetOptionValue().
g_completion_type
OptionEnumValueElement lldb_private::g_completion_type[] static constexpr
Definition at line 178 of file CommandOptionArgumentTable.h.
g_corefile_save_style
OptionEnumValueElement lldb_private::g_corefile_save_style[] static constexpr
Initial value:
= {
    {lldb::eSaveCoreFull, "full", "Create a core file with all memory saved"},
    {lldb::eSaveCoreDirtyOnly, "modified-memory",
     "Create a corefile with only modified memory saved"},
    {lldb::eSaveCoreStackOnly, "stack",
     "Create a corefile with only stack  memory saved"},
}
Definition at line 16 of file CommandOptionArgumentTable.h.
g_dependents_enumeration
OptionEnumValueElement lldb_private::g_dependents_enumeration[] static constexpr
Initial value:
= {
    {
        eLoadDependentsDefault,
        "default",
        "Only load dependents when the target is an executable.",
    },
    {
        eLoadDependentsNo,
        "true",
        "Don't load dependents, even if the target is an executable.",
    },
    {
        eLoadDependentsYes,
        "false",
        "Load dependents, even if the target is not an executable.",
    },
}
Definition at line 62 of file CommandOptionArgumentTable.h.
g_description_verbosity_type
OptionEnumValueElement lldb_private::g_description_verbosity_type[] static constexpr
Initial value:
= {
    {
        eLanguageRuntimeDescriptionDisplayVerbosityCompact,
        "compact",
        "Only show the description string",
    },
    {
        eLanguageRuntimeDescriptionDisplayVerbosityFull,
        "full",
        "Show the full output, including persistent variable's name and type",
    },
}
Definition at line 24 of file CommandOptionArgumentTable.h.
g_exception_stage
OptionEnumValueElement lldb_private::g_exception_stage[] static constexpr
Initial value:
= {
    {lldb::eExceptionStageThrow, "throw", "Stop when the exception is thrown."},
    {lldb::eExceptionStageReThrow, "re-throw",
     "Stop when the exception is re-thrown."},
    {lldb::eExceptionStageCatch, "catch", "Stop when the exception is caught."},
}
Definition at line 157 of file CommandOptionArgumentTable.h.
g_int_parsing_error_message
llvm::StringLiteral lldb_private::g_int_parsing_error_message static constexpr
Initial value:
=
    "Failed to parse as integer"
Definition at line 369 of file Options.h.
Referenced by BreakpointNameOptionGroup::SetOptionValue(), CommandObjectBreakpointAddFile::CommandOptions::SetOptionValue(), CommandObjectBreakpointSet::CommandOptions::SetOptionValue(), and lldb_private::BreakpointOptionGroup::SetOptionValue().
g_language_parsing_error_message
llvm::StringLiteral lldb_private::g_language_parsing_error_message static constexpr
Initial value:
=
    "Unknown language"
Definition at line 371 of file Options.h.
Referenced by CommandObjectBreakpointAddName::CommandOptions::SetOptionValue(), and CommandObjectBreakpointSet::CommandOptions::SetOptionValue().
g_lldb_assert_callback
std::atomic<LLDBAssertCallback> lldb_private::g_lldb_assert_callback static
Initial value:
=
    &DefaultAssertCallback
Definition at line 33 of file LLDBAssert.cpp.
Referenced by _lldb_assert(), and SetLLDBAssertCallback().
g_log_handler_type
OptionEnumValueElement lldb_private::g_log_handler_type[] static constexpr
Initial value:
= {
    {
        eLogHandlerDefault,
        "default",
        "Use the default (stream) log handler",
    },
    {
        eLogHandlerStream,
        "stream",
        "Write log messages to the debugger output stream or to a file if one "
        "is specified. A buffer size (in bytes) can be specified with -b. If "
        "no buffer size is specified the output is unbuffered.",
    },
    {
        eLogHandlerCircular,
        "circular",
        "Write log messages to a fixed size circular buffer. A buffer size "
        "(number of messages) must be specified with -b.",
    },
    {
        eLogHandlerSystem,
        "os",
        "Write log messages to the operating system log.",
    },
}
Definition at line 106 of file CommandOptionArgumentTable.h.
g_name_match_style
OptionEnumValueElement lldb_private::g_name_match_style[] static constexpr
Initial value:
= {
    {lldb::eNameMatchStyleAuto, "auto",
     "Match against the leaf nodes of the identifier, or against methods or "
     "selectors."},
    {lldb::eNameMatchStyleFull, "full", "Match the full identifier name."},
    {lldb::eNameMatchStyleBase, "base",
     "Match against the leaf node of the identifier."},
    {lldb::eNameMatchStyleMethod, "method", "Match only against method names."},
    {lldb::eNameMatchStyleSelector, "selector",
     "Match only against selector names."},
    {lldb::eNameMatchStyleRegex, "regex",
     "Match the identifier using a regular expression."},
}
Definition at line 164 of file CommandOptionArgumentTable.h.
g_running_mode
OptionEnumValueElement lldb_private::g_running_mode[] static constexpr
Initial value:
= {
    {lldb::eOnlyThisThread, "this-thread", "Run only this thread"},
    {lldb::eAllThreads, "all-threads", "Run all threads"},
    {lldb::eOnlyDuringStepping, "while-stepping",
     "Run only this thread while stepping"},
}
Definition at line 150 of file CommandOptionArgumentTable.h.
g_script_option_enumeration
OptionEnumValueElement lldb_private::g_script_option_enumeration[] static constexpr
Initial value:
= {
    {
        lldb::eScriptLanguageNone,
        "command",
        "Commands are in the lldb command interpreter language",
    },
    {
        lldb::eScriptLanguagePython,
        "python",
        "Commands are in the Python language.",
    },
    {
        lldb::eScriptLanguageLua,
        "lua",
        "Commands are in the Lua language.",
    },
    {
        lldb::eScriptLanguageNone,
        "default",
        "Commands are in the default scripting language.",
    },
}
Definition at line 83 of file CommandOptionArgumentTable.h.
g_script_synchro_type
OptionEnumValueElement lldb_private::g_script_synchro_type[] static constexpr
Initial value:
= {
    {
        eScriptedCommandSynchronicitySynchronous,
        "synchronous",
        "Run synchronous",
    },
    {
        eScriptedCommandSynchronicityAsynchronous,
        "asynchronous",
        "Run asynchronous",
    },
    {
        eScriptedCommandSynchronicityCurrentValue,
        "current",
        "Do not alter current setting",
    },
}
Definition at line 132 of file CommandOptionArgumentTable.h.
g_shared_cache_use_enum_values
OptionEnumValueElement lldb_private::g_shared_cache_use_enum_values[] static constexpr
Initial value:
= {
    {
        lldb::eSymbolSharedCacheUseHostLLDBMemory,
        "host-lldb-memory",
        "Get binaries from the host lldb in-memory shared cache.",
    },
    {
        lldb::eSymbolSharedCacheUseHostSharedCache,
        "host-shared-cache",
        "Get binaries from the host shared cache.",
    },
    {
        lldb::eSymbolSharedCacheUseHostAndInferiorSharedCache,
        "host-and-inferior-shared-cache",
        "Get binaries from the host and inferior's shared caches.",
    },
    {
        lldb::eSymbolSharedCacheUseInferiorSharedCacheOnly,
        "inferior-shared-cache-only",
        "Get binaries from inferior's shared cache only.",
    },
}
Definition at line 71 of file ModuleList.h.
g_sort_option_enumeration
OptionEnumValueElement lldb_private::g_sort_option_enumeration[] static constexpr
Initial value:
= {
    {
        eSortOrderNone,
        "none",
        "No sorting, use the original symbol table order.",
    },
    {
        eSortOrderByAddress,
        "address",
        "Sort output by symbol address.",
    },
    {
        eSortOrderByName,
        "name",
        "Sort output by symbol name.",
    },
    {
        eSortOrderBySize,
        "size",
        "Sort output by symbol byte size.",
    },
}
Definition at line 37 of file CommandOptionArgumentTable.h.
is_amo_add
template<typename T> bool lldb_private::is_amo_add constexpr
Initial value:
=
    std::is_same_v<T, AMOADD_W> || std::is_same_v<T, AMOADD_D>
Definition at line 214 of file EmulateInstructionRISCV.cpp.
is_amo_bit_op
template<typename T> bool lldb_private::is_amo_bit_op constexpr
Initial value:
=
    std::is_same_v<T, AMOXOR_W> || std::is_same_v<T, AMOXOR_D> ||
    std::is_same_v<T, AMOAND_W> || std::is_same_v<T, AMOAND_D> ||
    std::is_same_v<T, AMOOR_W> || std::is_same_v<T, AMOOR_D>
Definition at line 218 of file EmulateInstructionRISCV.cpp.
is_amo_cmp
template<typename T> bool lldb_private::is_amo_cmp constexpr
Initial value:
=
    std::is_same_v<T, AMOMIN_W> || std::is_same_v<T, AMOMIN_D> ||
    std::is_same_v<T, AMOMAX_W> || std::is_same_v<T, AMOMAX_D> ||
    std::is_same_v<T, AMOMINU_W> || std::is_same_v<T, AMOMINU_D> ||
    std::is_same_v<T, AMOMAXU_W> || std::is_same_v<T, AMOMAXU_D>
Definition at line 228 of file EmulateInstructionRISCV.cpp.
is_amo_swap
template<typename T> bool lldb_private::is_amo_swap constexpr
Initial value:
=
    std::is_same_v<T, AMOSWAP_W> || std::is_same_v<T, AMOSWAP_D>
Definition at line 224 of file EmulateInstructionRISCV.cpp.
is_load
template<typename T> bool lldb_private::is_load constexpr
Initial value:
=
    std::is_same_v<T, LB> || std::is_same_v<T, LH> || std::is_same_v<T, LW> ||
    std::is_same_v<T, LD> || std::is_same_v<T, LBU> || std::is_same_v<T, LHU> ||
    std::is_same_v<T, LWU>
Definition at line 204 of file EmulateInstructionRISCV.cpp.
is_store
template<typename T> bool lldb_private::is_store constexpr
Initial value:
= std::is_same_v<T, SB> || std::is_same_v<T, SH> ||
                          std::is_same_v<T, SW> || std::is_same_v<T, SD>
Definition at line 210 of file EmulateInstructionRISCV.cpp.
kWasmVirtualRegisterIndexMask
const uint32_t lldb_private::kWasmVirtualRegisterIndexMask = 0x3fffffff static
Definition at line 35 of file WasmVirtualRegisters.h.
Referenced by GetWasmRegister(), and GetWasmVirtualRegisterIndex().
kWasmVirtualRegisterTagMask
const uint32_t lldb_private::kWasmVirtualRegisterTagMask = 0x03 static
Definition at line 34 of file WasmVirtualRegisters.h.
Referenced by GetWasmRegister(), and GetWasmVirtualRegisterTag().
kWasmVirtualRegisterTagShift
const uint32_t lldb_private::kWasmVirtualRegisterTagShift = 30 static
Definition at line 36 of file WasmVirtualRegisters.h.
Referenced by GetWasmRegister(), and GetWasmVirtualRegisterTag().
LLDB_INVALID_COMPILER_ID
const uint32_t lldb_private::LLDB_INVALID_COMPILER_ID = UINT32_MAX
Definition at line 56 of file DiagnosticManager.h.
LLVM_PACKED_END
lldb_private::LLVM_PACKED_END
Definition at line 261 of file RegisterContext_x86.h.
PATTERNS
const InstrPattern lldb_private::PATTERNS[] static
Definition at line 488 of file EmulateInstructionRISCV.cpp.
Referenced by lldb_private::EmulateInstructionRISCV::Decode().
PPC_VMX_Desc
RegsetDesc lldb_private::PPC_VMX_Desc[] constexpr
Initial value:
= {
    {llvm::Triple::FreeBSD, llvm::Triple::UnknownArch, llvm::ELF::NT_PPC_VMX},
    {llvm::Triple::Linux, llvm::Triple::UnknownArch, llvm::ELF::NT_PPC_VMX},
}
Definition at line 164 of file RegisterUtilities.h.
Referenced by RegisterContextCorePOSIX_powerpc::RegisterContextCorePOSIX_powerpc(), and RegisterContextCorePOSIX_ppc64le::RegisterContextCorePOSIX_ppc64le().
PPC_VSX_Desc
RegsetDesc lldb_private::PPC_VSX_Desc[] constexpr
Initial value:
= {
    {llvm::Triple::Linux, llvm::Triple::UnknownArch, llvm::ELF::NT_PPC_VSX},
}
Definition at line 169 of file RegisterUtilities.h.
Referenced by RegisterContextCorePOSIX_ppc64le::RegisterContextCorePOSIX_ppc64le().
RISCV_GPR_FP
uint32_t lldb_private::RISCV_GPR_FP = 8 static constexpr
Definition at line 40 of file EmulateInstructionRISCV.cpp.
Referenced by lldb_private::Executor::operator()().
RISCV_GPR_SP
uint32_t lldb_private::RISCV_GPR_SP = 2 static constexpr
Definition at line 39 of file EmulateInstructionRISCV.cpp.
Referenced by Load(), lldb_private::Executor::operator()(), and Store().
RV128
uint8_t lldb_private::RV128 = 4 constexpr
Definition at line 295 of file RISCVInstructions.h.
RV32
uint8_t lldb_private::RV32 = 1 constexpr
Definition at line 293 of file RISCVInstructions.h.
Referenced by lldb_private::EmulateInstructionRISCV::Decode().
RV64
uint8_t lldb_private::RV64 = 2 constexpr
Definition at line 294 of file RISCVInstructions.h.
Referenced by lldb_private::EmulateInstructionRISCV::Decode().
validator
TableValidator<0> lldb_private::validator
Definition at line 311 of file CommandOptionArgumentTable.cpp.
Referenced by lldb_private::OptionValueString::OptionValueString(), lldb_private::OptionValueString::OptionValueString(), lldb_private::OptionValueString::OptionValueString(), lldb_private::Options::Parse(), and lldb_private::OptionValueString::SetValidator().