LLDB: lldb_private::sve Namespace Reference
lldb_private::sve Namespace Reference
Classes
struct user_sve_header
Typedefs
using user_za_header = user_sve_header
Functions
uint16_t vl_valid (uint16_t vl)
uint16_t vq_from_vl (uint16_t vl)
uint16_t vl_from_vq (uint16_t vq)
uint16_t SigZRegSize (uint16_t vq)
uint16_t SigPRegSize (uint16_t vq)
uint16_t SigFFRSize (uint16_t vq)
uint32_t SigRegsOffset ()
uint32_t SigZRegsOffset ()
uint32_t SigZRegOffset (uint16_t vq, uint16_t n)
uint32_t SigZRegsSize (uint16_t vq)
uint32_t SigPRegsOffset (uint16_t vq)
uint32_t SigPRegOffset (uint16_t vq, uint16_t n)
uint32_t SigpRegsSize (uint16_t vq)
uint32_t SigFFROffset (uint16_t vq)
uint32_t SigRegsSize (uint16_t vq)
uint32_t SVESigContextSize (uint16_t vq)
uint16_t PTraceRegsOffset ()
uint32_t PTraceFPSIMDSize (uint16_t vq, uint16_t flags)
uint32_t PTraceZRegSize (uint16_t vq)
uint32_t PTracePRegSize (uint16_t vq)
uint32_t PTraceFFRSize (uint16_t vq)
uint32_t SigToPTrace (uint32_t offset)
uint32_t PTraceZRegsOffset (uint16_t vq)
uint32_t PTraceZRegOffset (uint16_t vq, uint16_t n)
uint32_t PTraceZRegsSize (uint16_t vq)
uint32_t PTracePRegsOffset (uint16_t vq)
uint32_t PTracePRegOffset (uint16_t vq, uint16_t n)
uint32_t PTracePRegsSize (uint16_t vq)
uint32_t PTraceFFROffset (uint16_t vq)
uint32_t PTraceFPSROffset (uint16_t vq)
uint32_t PTraceFPCROffset (uint16_t vq)
uint32_t PTraceSVESize (uint16_t vq, uint16_t flags)
uint32_t PTraceSize (uint16_t vq, uint16_t flags)
Variables
const uint16_t vq_bytes = 16
const uint16_t vq_min = 1
const uint16_t vq_max = 512
const uint16_t vl_min = vq_min * vq_bytes
const uint16_t vl_max = vq_max * vq_bytes
const uint16_t num_of_zregs = 32
const uint16_t num_of_pregs = 16
const uint16_t sve_context_size = 16
const uint16_t ptrace_regs_mask = 1 << 0
const uint16_t ptrace_regs_fpsimd = 0
const uint16_t ptrace_regs_sve = ptrace_regs_mask
const uint32_t ptrace_fpsimd_offset = PTraceRegsOffset()
const uint32_t fpsr_size = sizeof(uint32_t)
const uint32_t fpcr_size = sizeof(uint32_t)
const uint32_t ptrace_sve_offset = PTraceRegsOffset()
Typedef Documentation
user_za_header
using lldb_private::sve::user_za_header = user_sve_header
Definition at line 155 of file LinuxPTraceDefines_arm64sve.h.
Function Documentation
PTraceFFROffset()
uint32_t lldb_private::sve::PTraceFFROffset (uint16_t vq) inline
Definition at line 261 of file LinuxPTraceDefines_arm64sve.h.
References SigFFROffset(), and SigToPTrace().
Referenced by PTraceFPSROffset().
PTraceFFRSize()
uint32_t lldb_private::sve::PTraceFFRSize (uint16_t vq) inline
Definition at line 226 of file LinuxPTraceDefines_arm64sve.h.
References SigFFRSize().
Referenced by PTraceFPSROffset().
PTraceFPCROffset()
uint32_t lldb_private::sve::PTraceFPCROffset (uint16_t vq) inline
Definition at line 270 of file LinuxPTraceDefines_arm64sve.h.
References fpsr_size, and PTraceFPSROffset().
Referenced by PTraceSVESize(), and RegisterContextCorePOSIX_arm64::ReadRegister().
PTraceFPSIMDSize()
uint32_t lldb_private::sve::PTraceFPSIMDSize (uint16_t vq, uint16_t flags) inline
Definition at line 195 of file LinuxPTraceDefines_arm64sve.h.
Referenced by PTraceSize().
PTraceFPSROffset()
uint32_t lldb_private::sve::PTraceFPSROffset (uint16_t vq) inline
Definition at line 265 of file LinuxPTraceDefines_arm64sve.h.
References PTraceFFROffset(), PTraceFFRSize(), and vq_bytes.
Referenced by PTraceFPCROffset(), and RegisterContextCorePOSIX_arm64::ReadRegister().
PTracePRegOffset()
uint32_t lldb_private::sve::PTracePRegOffset (uint16_t vq, uint16_t n) inline
Definition at line 253 of file LinuxPTraceDefines_arm64sve.h.
References SigPRegOffset(), and SigToPTrace().
Referenced by PTracePRegsSize().
PTracePRegSize()
uint32_t lldb_private::sve::PTracePRegSize (uint16_t vq) inline
Definition at line 224 of file LinuxPTraceDefines_arm64sve.h.
References SigPRegSize().
PTracePRegsOffset()
uint32_t lldb_private::sve::PTracePRegsOffset (uint16_t vq) inline
Definition at line 249 of file LinuxPTraceDefines_arm64sve.h.
References SigPRegsOffset(), and SigToPTrace().
Referenced by PTracePRegsSize().
PTracePRegsSize()
uint32_t lldb_private::sve::PTracePRegsSize (uint16_t vq) inline
Definition at line 257 of file LinuxPTraceDefines_arm64sve.h.
References num_of_pregs, PTracePRegOffset(), and PTracePRegsOffset().
PTraceRegsOffset()
uint16_t lldb_private::sve::PTraceRegsOffset () inline
Definition at line 173 of file LinuxPTraceDefines_arm64sve.h.
References vq_bytes.
Referenced by SigToPTrace().
PTraceSize()
uint32_t lldb_private::sve::PTraceSize (uint16_t vq, uint16_t flags) inline
Definition at line 284 of file LinuxPTraceDefines_arm64sve.h.
References ptrace_fpsimd_offset, ptrace_regs_mask, ptrace_regs_sve, ptrace_sve_offset, PTraceFPSIMDSize(), and PTraceSVESize().
PTraceSVESize()
uint32_t lldb_private::sve::PTraceSVESize (uint16_t vq, uint16_t flags) inline
Definition at line 279 of file LinuxPTraceDefines_arm64sve.h.
References fpcr_size, ptrace_sve_offset, PTraceFPCROffset(), and vq_bytes.
Referenced by PTraceSize().
PTraceZRegOffset()
uint32_t lldb_private::sve::PTraceZRegOffset (uint16_t vq, uint16_t n) inline
Definition at line 241 of file LinuxPTraceDefines_arm64sve.h.
References SigToPTrace(), and SigZRegOffset().
Referenced by PTraceZRegsSize().
PTraceZRegSize()
uint32_t lldb_private::sve::PTraceZRegSize (uint16_t vq) inline
Definition at line 222 of file LinuxPTraceDefines_arm64sve.h.
References SigZRegSize().
PTraceZRegsOffset()
uint32_t lldb_private::sve::PTraceZRegsOffset (uint16_t vq) inline
Definition at line 237 of file LinuxPTraceDefines_arm64sve.h.
References SigToPTrace(), and SigZRegsOffset().
PTraceZRegsSize()
uint32_t lldb_private::sve::PTraceZRegsSize (uint16_t vq) inline
Definition at line 245 of file LinuxPTraceDefines_arm64sve.h.
References num_of_zregs, PTraceZRegOffset(), SigRegsOffset(), and SigToPTrace().
SigFFROffset()
uint32_t lldb_private::sve::SigFFROffset (uint16_t vq) inline
Definition at line 134 of file LinuxPTraceDefines_arm64sve.h.
References SigPRegsOffset(), and SigpRegsSize().
Referenced by PTraceFFROffset(), and SigRegsSize().
SigFFRSize()
uint16_t lldb_private::sve::SigFFRSize (uint16_t vq) inline
Definition at line 106 of file LinuxPTraceDefines_arm64sve.h.
References SigPRegSize().
Referenced by PTraceFFRSize(), and SigRegsSize().
SigPRegOffset()
uint32_t lldb_private::sve::SigPRegOffset (uint16_t vq, uint16_t n) inline
Definition at line 126 of file LinuxPTraceDefines_arm64sve.h.
References SigPRegSize(), and SigPRegsOffset().
Referenced by PTracePRegOffset(), and SigpRegsSize().
SigPRegSize()
uint16_t lldb_private::sve::SigPRegSize (uint16_t vq) inline
Definition at line 105 of file LinuxPTraceDefines_arm64sve.h.
References vq_bytes.
Referenced by PTracePRegSize(), SigFFRSize(), and SigPRegOffset().
SigPRegsOffset()
uint32_t lldb_private::sve::SigPRegsOffset (uint16_t vq) inline
Definition at line 122 of file LinuxPTraceDefines_arm64sve.h.
References SigRegsOffset(), and SigZRegsSize().
Referenced by PTracePRegsOffset(), SigFFROffset(), SigPRegOffset(), and SigpRegsSize().
SigpRegsSize()
uint32_t lldb_private::sve::SigpRegsSize (uint16_t vq) inline
Definition at line 130 of file LinuxPTraceDefines_arm64sve.h.
References num_of_pregs, SigPRegOffset(), and SigPRegsOffset().
Referenced by SigFFROffset().
SigRegsOffset()
uint32_t lldb_private::sve::SigRegsOffset () inline
Definition at line 108 of file LinuxPTraceDefines_arm64sve.h.
References sve_context_size, and vq_bytes.
Referenced by RegisterContextCorePOSIX_arm64::CalculateSVEOffset(), PTraceZRegsSize(), SigPRegsOffset(), SigRegsSize(), SigToPTrace(), SigZRegOffset(), SigZRegsOffset(), SigZRegsSize(), and SVESigContextSize().
SigRegsSize()
uint32_t lldb_private::sve::SigRegsSize (uint16_t vq) inline
Definition at line 138 of file LinuxPTraceDefines_arm64sve.h.
References SigFFROffset(), SigFFRSize(), and SigRegsOffset().
Referenced by SVESigContextSize().
SigToPTrace()
uint32_t lldb_private::sve::SigToPTrace (uint32_t offset) inline
Definition at line 231 of file LinuxPTraceDefines_arm64sve.h.
References PTraceRegsOffset(), and SigRegsOffset().
Referenced by PTraceFFROffset(), PTracePRegOffset(), PTracePRegsOffset(), PTraceZRegOffset(), PTraceZRegsOffset(), and PTraceZRegsSize().
SigZRegOffset()
uint32_t lldb_private::sve::SigZRegOffset (uint16_t vq, uint16_t n) inline
Definition at line 114 of file LinuxPTraceDefines_arm64sve.h.
References SigRegsOffset(), and SigZRegSize().
Referenced by PTraceZRegOffset(), and SigZRegsSize().
SigZRegSize()
uint16_t lldb_private::sve::SigZRegSize (uint16_t vq) inline
Definition at line 104 of file LinuxPTraceDefines_arm64sve.h.
References vq_bytes.
Referenced by PTraceZRegSize(), and SigZRegOffset().
SigZRegsOffset()
uint32_t lldb_private::sve::SigZRegsOffset () inline
Definition at line 112 of file LinuxPTraceDefines_arm64sve.h.
References SigRegsOffset().
Referenced by PTraceZRegsOffset().
SigZRegsSize()
uint32_t lldb_private::sve::SigZRegsSize (uint16_t vq) inline
Definition at line 118 of file LinuxPTraceDefines_arm64sve.h.
References num_of_zregs, SigRegsOffset(), and SigZRegOffset().
Referenced by SigPRegsOffset().
SVESigContextSize()
uint32_t lldb_private::sve::SVESigContextSize (uint16_t vq) inline
Definition at line 142 of file LinuxPTraceDefines_arm64sve.h.
References SigRegsOffset(), and SigRegsSize().
vl_from_vq()
uint16_t lldb_private::sve::vl_from_vq (uint16_t vq) inline
Definition at line 42 of file LinuxPTraceDefines_arm64sve.h.
References vq_bytes.
vl_valid()
uint16_t lldb_private::sve::vl_valid (uint16_t vl) inline
Definition at line 37 of file LinuxPTraceDefines_arm64sve.h.
References vl_max, vl_min, and vq_bytes.
Referenced by RegisterContextCorePOSIX_arm64::ConfigureRegisterContext().
vq_from_vl()
uint16_t lldb_private::sve::vq_from_vl (uint16_t vl) inline
Definition at line 41 of file LinuxPTraceDefines_arm64sve.h.
References vq_bytes.
Referenced by RegisterContextCorePOSIX_arm64::ConfigureRegisterContext(), and RegisterContextCorePOSIX_arm64::ReadRegister().
Variable Documentation
fpcr_size
const uint32_t lldb_private::sve::fpcr_size = sizeof(uint32_t)
Definition at line 229 of file LinuxPTraceDefines_arm64sve.h.
Referenced by PTraceSVESize().
fpsr_size
const uint32_t lldb_private::sve::fpsr_size = sizeof(uint32_t)
Definition at line 228 of file LinuxPTraceDefines_arm64sve.h.
Referenced by PTraceFPCROffset().
num_of_pregs
const uint16_t lldb_private::sve::num_of_pregs = 16
Definition at line 35 of file LinuxPTraceDefines_arm64sve.h.
Referenced by PTracePRegsSize(), and SigpRegsSize().
num_of_zregs
const uint16_t lldb_private::sve::num_of_zregs = 32
Definition at line 34 of file LinuxPTraceDefines_arm64sve.h.
Referenced by PTraceZRegsSize(), and SigZRegsSize().
ptrace_fpsimd_offset
const uint32_t lldb_private::sve::ptrace_fpsimd_offset = PTraceRegsOffset()
Definition at line 192 of file LinuxPTraceDefines_arm64sve.h.
Referenced by RegisterContextCorePOSIX_arm64::CalculateSVEOffset(), PTraceSize(), and RegisterContextCorePOSIX_arm64::ReadRegister().
ptrace_regs_fpsimd
const uint16_t lldb_private::sve::ptrace_regs_fpsimd = 0
Definition at line 159 of file LinuxPTraceDefines_arm64sve.h.
Referenced by RegisterContextCorePOSIX_arm64::ConfigureRegisterContext().
ptrace_regs_mask
const uint16_t lldb_private::sve::ptrace_regs_mask = 1 << 0
Definition at line 158 of file LinuxPTraceDefines_arm64sve.h.
Referenced by RegisterContextCorePOSIX_arm64::ConfigureRegisterContext(), PTraceSize(), and RegisterContextCorePOSIX_arm64::RegisterContextCorePOSIX_arm64().
ptrace_regs_sve
const uint16_t lldb_private::sve::ptrace_regs_sve = ptrace_regs_mask
Definition at line 160 of file LinuxPTraceDefines_arm64sve.h.
Referenced by RegisterContextCorePOSIX_arm64::ConfigureRegisterContext(), PTraceSize(), and RegisterContextCorePOSIX_arm64::RegisterContextCorePOSIX_arm64().
ptrace_sve_offset
const uint32_t lldb_private::sve::ptrace_sve_offset = PTraceRegsOffset()
Definition at line 235 of file LinuxPTraceDefines_arm64sve.h.
Referenced by PTraceSize(), and PTraceSVESize().
sve_context_size
const uint16_t lldb_private::sve::sve_context_size = 16
Definition at line 51 of file LinuxPTraceDefines_arm64sve.h.
Referenced by SigRegsOffset().
vl_max
const uint16_t lldb_private::sve::vl_max = vq_max * vq_bytes
Definition at line 32 of file LinuxPTraceDefines_arm64sve.h.
Referenced by vl_valid().
vl_min
const uint16_t lldb_private::sve::vl_min = vq_min * vq_bytes
Definition at line 31 of file LinuxPTraceDefines_arm64sve.h.
Referenced by vl_valid().
vq_bytes
const uint16_t lldb_private::sve::vq_bytes = 16
Definition at line 26 of file LinuxPTraceDefines_arm64sve.h.
Referenced by PTraceFPSROffset(), PTraceRegsOffset(), PTraceSVESize(), SigPRegSize(), SigRegsOffset(), SigZRegSize(), vl_from_vq(), vl_valid(), and vq_from_vl().
vq_max
const uint16_t lldb_private::sve::vq_max = 512
Definition at line 29 of file LinuxPTraceDefines_arm64sve.h.
vq_min
const uint16_t lldb_private::sve::vq_min = 1
Definition at line 28 of file LinuxPTraceDefines_arm64sve.h.