LLDB: NativeProcessSoftwareSingleStep.cpp File Reference
NativeProcessSoftwareSingleStep.cpp File Reference
#include "NativeProcessSoftwareSingleStep.h"
#include "lldb/Core/EmulateInstruction.h"
#include "lldb/Host/common/NativeRegisterContext.h"
#include "lldb/Utility/RegisterValue.h"
#include <unordered_map>
Functions
static size_t ReadMemoryCallback (EmulateInstruction *instruction, void *baton, const EmulateInstruction::Context &context, lldb::addr_t addr, void *dst, size_t length)
static bool ReadRegisterCallback (EmulateInstruction *instruction, void *baton, const RegisterInfo *reg_info, RegisterValue &reg_value)
static bool WriteRegisterCallback (EmulateInstruction *instruction, void *baton, const EmulateInstruction::Context &context, const RegisterInfo *reg_info, const RegisterValue &reg_value)
static size_t WriteMemoryCallback (EmulateInstruction *instruction, void *baton, const EmulateInstruction::Context &context, lldb::addr_t addr, const void *dst, size_t length)
static Status SetSoftwareBreakpoint (lldb::addr_t bp_addr, unsigned bp_size, NativeProcessProtocol &process)
Function Documentation
ReadMemoryCallback()
size_t ReadMemoryCallback (EmulateInstruction * instruction, void * baton, const EmulateInstruction::Context & context, lldb::addr_t addr, void * dst, size_t length) static
Definition at line 36 of file NativeProcessSoftwareSingleStep.cpp.
References lldb_private::NativeProcessProtocol::ReadMemory().
Referenced by lldb_private::NativeProcessSoftwareSingleStep::SetupSoftwareSingleStepping().
ReadRegisterCallback()
bool ReadRegisterCallback (EmulateInstruction * instruction, void * baton, const RegisterInfo * reg_info, RegisterValue & reg_value) static
Definition at line 46 of file NativeProcessSoftwareSingleStep.cpp.
References lldb::eRegisterKindDWARF, error(), lldb_private::NativeRegisterContext::GetRegisterInfo(), lldb_private::RegisterInfo::kinds, and lldb_private::NativeRegisterContext::ReadRegister().
Referenced by lldb_private::NativeProcessSoftwareSingleStep::SetupSoftwareSingleStepping().
SetSoftwareBreakpoint()
Status SetSoftwareBreakpoint (lldb::addr_t bp_addr, unsigned bp_size, NativeProcessProtocol & process) static
Definition at line 90 of file NativeProcessSoftwareSingleStep.cpp.
References error(), lldb_private::NativeProcessProtocol::SetBreakpoint(), and lldb_private::Status.
Referenced by lldb_private::NativeProcessSoftwareSingleStep::SetupSoftwareSingleStepping().
WriteMemoryCallback()
size_t WriteMemoryCallback (EmulateInstruction * instruction, void * baton, const EmulateInstruction::Context & context, lldb::addr_t addr, const void * dst, size_t length) static
Definition at line 83 of file NativeProcessSoftwareSingleStep.cpp.
Referenced by lldb_private::NativeProcessSoftwareSingleStep::SetupSoftwareSingleStepping().
WriteRegisterCallback()
bool WriteRegisterCallback (EmulateInstruction * instruction, void * baton, const EmulateInstruction::Context & context, const RegisterInfo * reg_info, const RegisterValue & reg_value) static
Definition at line 73 of file NativeProcessSoftwareSingleStep.cpp.
References lldb::eRegisterKindDWARF, and lldb_private::RegisterInfo::kinds.
Referenced by lldb_private::NativeProcessSoftwareSingleStep::SetupSoftwareSingleStepping().