LLDB: NativeProcessAIX.cpp File Reference
NativeProcessAIX.cpp File Reference
#include "NativeProcessAIX.h"
#include "Plugins/Process/POSIX/ProcessPOSIXLog.h"
#include "lldb/Host/Host.h"
#include "lldb/Host/HostInfo.h"
#include "lldb/Host/HostProcess.h"
#include "lldb/Host/ProcessLaunchInfo.h"
#include "lldb/Host/posix/ProcessLauncherPosixFork.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/State.h"
#include "lldb/Utility/Status.h"
#include "llvm/Support/Errno.h"
#include "llvm/Support/Error.h"
#include <cerrno>
#include <cstdint>
#include <cstring>
#include <sstream>
#include <string>
#include <sys/ptrace.h>
#include <unistd.h>
Functions
static llvm::Error SetFDFlags (int fd, int flags)
static std::optional< std::pair< lldb::pid_t, WaitStatus > > WaitPid ()
Variables
static constexpr unsigned k_ptrace_word_size = sizeof(void *)
Function Documentation
SetFDFlags()
llvm::Error SetFDFlags (int fd, int flags) static
Definition at line 41 of file NativeProcessAIX.cpp.
Referenced by lldb_private::process_aix::NativeProcessAIX::NativeProcessAIX().
WaitPid()
std::optional< std::pair< lldb::pid_t, WaitStatus > > WaitPid () static
Definition at line 112 of file NativeProcessAIX.cpp.
References lldb_private::WaitStatus::Decode(), lldb::eErrorTypePOSIX, error(), lldb_private::GetLog(), LLDB_LOG, and lldb_private::Process.
Referenced by lldb_private::process_aix::NativeProcessAIX::Manager::SigchldHandler(), and lldb_private::process_linux::NativeProcessLinux::Manager::SigchldHandler().
Variable Documentation
k_ptrace_word_size
unsigned k_ptrace_word_size = sizeof(void *) static constexpr
Definition at line 35 of file NativeProcessAIX.cpp.
Referenced by lldb_private::process_linux::NativeProcessLinux::ReadMemory(), and lldb_private::process_linux::NativeProcessLinux::WriteMemory().