LLDB: NativeRegisterContextDBReg_x86.cpp File Reference
NativeRegisterContextDBReg_x86.cpp File Reference
#include "NativeRegisterContextDBReg_x86.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/RegisterValue.h"
#include "Plugins/Process/Utility/lldb-x86-register-enums.h"
Functions
static uint64_t GetStatusBit (uint32_t wp_index)
static uint64_t GetEnableBit (uint32_t wp_index)
static uint64_t GetBothEnableBitMask (uint32_t wp_index)
static uint64_t GetWatchTypeBits (uint32_t watch_flags, uint32_t wp_index)
static uint64_t GetWatchSizeBits (uint32_t size, uint32_t wp_index)
static uint64_t GetWatchControlBitmask (uint32_t wp_index)
Variables
static constexpr uint64_t watchpoint_all_control_bit_mask = 0xFFFF00FF
Function Documentation
GetBothEnableBitMask()
uint64_t GetBothEnableBitMask (uint32_t wp_index) inline static
Definition at line 34 of file NativeRegisterContextDBReg_x86.cpp.
Referenced by lldb_private::NativeRegisterContextDBReg_x86::ClearHardwareWatchpoint(), and GetWatchControlBitmask().
GetEnableBit()
uint64_t GetEnableBit (uint32_t wp_index) inline static
Definition at line 25 of file NativeRegisterContextDBReg_x86.cpp.
Referenced by lldb_private::NativeRegisterContextDBReg_x86::IsWatchpointVacant(), and lldb_private::NativeRegisterContextDBReg_x86::SetHardwareWatchpointWithIndex().
GetStatusBit()
uint64_t GetStatusBit (uint32_t wp_index) inline static
Definition at line 18 of file NativeRegisterContextDBReg_x86.cpp.
Referenced by lldb_private::NativeRegisterContextDBReg_x86::ClearWatchpointHit(), and lldb_private::NativeRegisterContextDBReg_x86::IsWatchpointHit().
GetWatchControlBitmask()
uint64_t GetWatchControlBitmask (uint32_t wp_index) inline static
Definition at line 71 of file NativeRegisterContextDBReg_x86.cpp.
References GetBothEnableBitMask().
Referenced by lldb_private::NativeRegisterContextDBReg_x86::SetHardwareWatchpointWithIndex().
GetWatchSizeBits()
uint64_t GetWatchSizeBits (uint32_t size, uint32_t wp_index) inline static
Definition at line 54 of file NativeRegisterContextDBReg_x86.cpp.
Referenced by lldb_private::NativeRegisterContextDBReg_x86::SetHardwareWatchpointWithIndex().
GetWatchTypeBits()
uint64_t GetWatchTypeBits (uint32_t watch_flags, uint32_t wp_index) inline static
Definition at line 41 of file NativeRegisterContextDBReg_x86.cpp.
Referenced by lldb_private::NativeRegisterContextDBReg_x86::SetHardwareWatchpointWithIndex().
Variable Documentation
watchpoint_all_control_bit_mask
uint64_t watchpoint_all_control_bit_mask = 0xFFFF00FF static constexpr
Definition at line 81 of file NativeRegisterContextDBReg_x86.cpp.
Referenced by lldb_private::NativeRegisterContextDBReg_x86::ClearAllHardwareWatchpoints().