LLDB: NativeProcessFreeBSD.cpp File Reference
NativeProcessFreeBSD.cpp File Reference
#include "NativeProcessFreeBSD.h"
#include <sys/types.h>
#include <sys/ptrace.h>
#include <sys/sysctl.h>
#include <sys/user.h>
#include <sys/wait.h>
#include <machine/elf.h>
#include "Plugins/Process/POSIX/ProcessPOSIXLog.h"
#include "lldb/Host/HostProcess.h"
#include "lldb/Host/posix/ProcessLauncherPosixFork.h"
#include "lldb/Target/Process.h"
#include "lldb/Utility/State.h"
#include "llvm/Support/Errno.h"
Functions
static Status EnsureFDFlags (int fd, int flags)
static Status CanTrace ()
Function Documentation
CanTrace()
Status CanTrace () static
Definition at line 51 of file NativeProcessFreeBSD.cpp.
References lldb_private::Status::FromErrorString().
Referenced by lldb_private::process_freebsd::NativeProcessFreeBSD::GetFileLoadAddress(), lldb_private::process_freebsd::NativeProcessFreeBSD::GetLoadedModuleFileSpec(), lldb_private::process_freebsd::NativeProcessFreeBSD::Manager::Launch(), and lldb_private::process_freebsd::NativeProcessFreeBSD::PtraceWrapper().
EnsureFDFlags()
Status EnsureFDFlags (int fd, int flags) static
Definition at line 34 of file NativeProcessFreeBSD.cpp.
References error(), and lldb_private::Status::FromErrno().
Referenced by lldb_private::process_freebsd::NativeProcessFreeBSD::NativeProcessFreeBSD(), lldb_private::process_linux::NativeProcessLinux::NativeProcessLinux(), and lldb_private::process_netbsd::NativeProcessNetBSD::NativeProcessNetBSD().