LLDB: NSDictionary.cpp File Reference
NSDictionary.cpp File Reference
#include <mutex>
#include "clang/AST/DeclCXX.h"
#include "CFBasicHash.h"
#include "NSDictionary.h"
#include "Plugins/LanguageRuntime/ObjC/AppleObjCRuntime/AppleObjCRuntime.h"
#include "Plugins/TypeSystem/Clang/TypeSystemClang.h"
#include "lldb/DataFormatters/FormattersHelpers.h"
#include "lldb/Target/Language.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/Endian.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/Stream.h"
#include "lldb/ValueObject/ValueObject.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
Classes
class lldb_private::formatters::NSDictionaryISyntheticFrontEnd
struct lldb_private::formatters::NSDictionaryISyntheticFrontEnd::DataDescriptor_32
struct lldb_private::formatters::NSDictionaryISyntheticFrontEnd::DataDescriptor_64
struct lldb_private::formatters::NSDictionaryISyntheticFrontEnd::DictionaryItemDescriptor
class lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd
struct lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::DictionaryItemDescriptor
class lldb_private::formatters::NSCFDictionarySyntheticFrontEnd
struct lldb_private::formatters::NSCFDictionarySyntheticFrontEnd::DictionaryItemDescriptor
class lldb_private::formatters::NSDictionary1SyntheticFrontEnd
class lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< D32, D64 >
struct lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< D32, D64 >::DictionaryItemDescriptor
class lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd
struct lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd::DataDescriptor_32
struct lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd::DataDescriptor_64
struct lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd::DictionaryItemDescriptor
Namespaces
namespace lldb_private
A class that represents a running process on the host machine.
namespace lldb_private::formatters
namespace lldb_private::formatters::Foundation1100
namespace lldb_private::formatters::Foundation1428
namespace lldb_private::formatters::Foundation1437
Typedefs
using lldb_private::formatters::Foundation1428::NSDictionaryMSyntheticFrontEnd
using lldb_private::formatters::Foundation1437::NSDictionaryMSyntheticFrontEnd
Functions
static CompilerType GetLLDBNSPairType (TargetSP target_sp)
template<typename DD>
uint64_t lldb_private::formatters::Foundation1437::__NSDictionaryMSize_Impl (lldb_private::Process &process, lldb::addr_t valobj_addr, Status &error)
uint64_t lldb_private::formatters::Foundation1437::__NSDictionaryMSize (lldb_private::Process &process, lldb::addr_t valobj_addr, Status &error)
Variables
static const uint64_t lldb_private::formatters::Foundation1437::NSDictionaryCapacities []
static const size_t lldb_private::formatters::Foundation1437::NSDictionaryNumSizeBuckets
Function Documentation
GetLLDBNSPairType()
CompilerType GetLLDBNSPairType (TargetSP target_sp) static
Definition at line 66 of file NSDictionary.cpp.
References lldb_private::TypeSystemClang::AddFieldToRecordType(), lldb_private::TypeSystemClang::CompleteTagDeclarationDefinition(), lldb::eAccessPublic, lldb::eBasicTypeObjCID, lldb::eLanguageTypeC, lldb_private::ScratchTypeSystemClang::GetForTarget(), and lldb_private::TypeSystemClang::StartTagDeclarationDefinition().
Referenced by lldb_private::formatters::Foundation1100::NSDictionaryMSyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::GenericNSDictionaryMSyntheticFrontEnd< D32, D64 >::GetChildAtIndex(), lldb_private::formatters::NSCFDictionarySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSConstantDictionarySyntheticFrontEnd::GetChildAtIndex(), lldb_private::formatters::NSDictionary1SyntheticFrontEnd::GetChildAtIndex(), and lldb_private::formatters::NSDictionaryISyntheticFrontEnd::GetChildAtIndex().