LLDB: NSException.cpp File Reference
NSException.cpp File Reference
#include "clang/AST/DeclCXX.h"
#include "Cocoa.h"
#include "lldb/DataFormatters/FormattersHelpers.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/Endian.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/Stream.h"
#include "lldb/ValueObject/ValueObject.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
#include "Plugins/Language/ObjC/NSString.h"
#include "Plugins/LanguageRuntime/ObjC/ObjCLanguageRuntime.h"
#include "Plugins/TypeSystem/Clang/TypeSystemClang.h"
Classes
class NSExceptionSyntheticFrontEnd
Functions
static bool ExtractFields (ValueObject &valobj, ValueObjectSP *name_sp, ValueObjectSP *reason_sp, ValueObjectSP *userinfo_sp, ValueObjectSP *reserved_sp)
Function Documentation
ExtractFields()
bool ExtractFields (ValueObject & valobj, ValueObjectSP * name_sp, ValueObjectSP * reason_sp, ValueObjectSP * userinfo_sp, ValueObjectSP * reserved_sp) static
Definition at line 30 of file NSException.cpp.
References lldb_private::Flags::AllClear(), lldb_private::ValueObject::CreateValueObjectFromData(), lldb::eBasicTypeVoid, error(), lldb_private::formatters::InferiorSizedWord::GetAsData(), lldb_private::ValueObject::GetCompilerType(), lldb_private::ValueObject::GetExecutionContextRef(), lldb_private::ScratchTypeSystemClang::GetForTarget(), lldb_private::ValueObject::GetParent(), lldb_private::ValueObject::GetProcessSP(), lldb_private::CompilerType::GetTypeInfo(), lldb_private::ValueObject::GetValueAsUnsigned(), lldb_private::ValueObject::IsBaseClass(), and LLDB_INVALID_ADDRESS.
Referenced by lldb_private::formatters::NSException_SummaryProvider(), and NSExceptionSyntheticFrontEnd::Update().