LLDB: ObjCLanguage.cpp File Reference
ObjCLanguage.cpp File Reference
#include <mutex>
#include "ObjCLanguage.h"
#include "Plugins/ExpressionParser/Clang/ClangUtil.h"
#include "Plugins/TypeSystem/Clang/TypeSystemClang.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/DataFormatters/DataVisualization.h"
#include "lldb/DataFormatters/FormattersHelpers.h"
#include "lldb/Symbol/CompilerType.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/ValueObject/ValueObject.h"
#include "llvm/Support/Threading.h"
#include "Plugins/ExpressionParser/Clang/ClangModulesDeclVendor.h"
#include "Plugins/LanguageRuntime/ObjC/ObjCLanguageRuntime.h"
#include "CF.h"
#include "Cocoa.h"
#include "CoreMedia.h"
#include "NSDictionary.h"
#include "NSSet.h"
#include "NSString.h"
Functions
static void LoadObjCFormatters (TypeCategoryImplSP objc_category_sp)
static void LoadCoreMediaFormatters (TypeCategoryImplSP objc_category_sp)
Function Documentation
LoadCoreMediaFormatters()
void LoadCoreMediaFormatters (TypeCategoryImplSP objc_category_sp) static
Definition at line 851 of file ObjCLanguage.cpp.
References lldb_private::formatters::AddCXXSummary(), lldb_private::formatters::CMTimeSummaryProvider(), lldb_private::TypeSummaryImpl::Flags::SetCascades(), lldb_private::TypeSummaryImpl::Flags::SetDontShowChildren(), lldb_private::TypeSummaryImpl::Flags::SetDontShowValue(), lldb_private::TypeSummaryImpl::Flags::SetHideItemNames(), lldb_private::TypeSummaryImpl::Flags::SetShowMembersOneLiner(), lldb_private::TypeSummaryImpl::Flags::SetSkipPointers(), and lldb_private::TypeSummaryImpl::Flags::SetSkipReferences().
Referenced by lldb_private::ObjCLanguage::GetFormatters().
LoadObjCFormatters()
void LoadObjCFormatters (TypeCategoryImplSP objc_category_sp) static
Definition at line 245 of file ObjCLanguage.cpp.
References lldb_private::formatters::AddCXXSummary(), lldb_private::formatters::AddCXXSynthetic(), lldb_private::formatters::AddOneLineSummary(), lldb_private::formatters::AddStringSummary(), lldb_private::formatters::CFAbsoluteTimeSummaryProvider(), lldb_private::formatters::CFBagSummaryProvider(), lldb_private::formatters::CFBinaryHeapSummaryProvider(), lldb_private::formatters::CFBitVectorSummaryProvider(), lldb::eFormatterMatchExact, lldb_private::formatters::NSArraySummaryProvider(), lldb_private::formatters::NSArraySyntheticFrontEndCreator(), lldb_private::formatters::NSAttributedStringSummaryProvider(), lldb_private::formatters::NSBundleSummaryProvider(), lldb_private::formatters::NSDataSummaryProvider(), lldb_private::formatters::NSDateSummaryProvider(), lldb_private::formatters::NSDictionarySummaryProvider(), lldb_private::formatters::NSDictionarySyntheticFrontEndCreator(), lldb_private::formatters::NSError_SummaryProvider(), lldb_private::formatters::NSErrorSyntheticFrontEndCreator(), lldb_private::formatters::NSException_SummaryProvider(), lldb_private::formatters::NSExceptionSyntheticFrontEndCreator(), lldb_private::formatters::NSIndexPathSyntheticFrontEndCreator(), lldb_private::formatters::NSIndexSetSummaryProvider(), lldb_private::formatters::NSMachPortSummaryProvider(), lldb_private::formatters::NSMutableAttributedStringSummaryProvider(), lldb_private::formatters::NSNotificationSummaryProvider(), lldb_private::formatters::NSNumberSummaryProvider(), lldb_private::formatters::NSSetSummaryProvider(), lldb_private::formatters::NSSetSyntheticFrontEndCreator(), lldb_private::formatters::NSStringSummaryProvider(), lldb_private::formatters::NSTimeZoneSummaryProvider(), lldb_private::formatters::NSURLSummaryProvider(), lldb_private::formatters::ObjCBOOLSummaryProvider(), lldb_private::formatters::ObjCClassSummaryProvider(), lldb_private::formatters::ObjCClassSyntheticFrontEndCreator(), lldb_private::formatters::ObjCSELSummaryProvider(), lldb_private::SyntheticChildren::Flags::SetCascades(), lldb_private::TypeSummaryImpl::Flags::SetCascades(), lldb_private::TypeSummaryImpl::Flags::SetDontShowChildren(), lldb_private::TypeSummaryImpl::Flags::SetDontShowValue(), lldb_private::TypeSummaryImpl::Flags::SetHideItemNames(), lldb_private::TypeSummaryImpl::Flags::SetShowMembersOneLiner(), lldb_private::SyntheticChildren::Flags::SetSkipPointers(), lldb_private::TypeSummaryImpl::Flags::SetSkipPointers(), lldb_private::SyntheticChildren::Flags::SetSkipReferences(), and lldb_private::TypeSummaryImpl::Flags::SetSkipReferences().
Referenced by lldb_private::ObjCLanguage::GetFormatters().