LLDB: ObjectContainerBSDArchive.cpp File Reference
ObjectContainerBSDArchive.cpp File Reference
#include "ObjectContainerBSDArchive.h"
#include <ar.h>
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Host/FileSystem.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Utility/ArchSpec.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Stream.h"
#include "lldb/Utility/Timer.h"
#include "llvm/Object/Archive.h"
#include "llvm/Support/MemoryBuffer.h"
Functions
FileSpec GetChildFileSpecificationsFromThin (llvm::StringRef childPath, const FileSpec &parentFileSpec)
Variables
Log * l = GetLog(LLDBLog::Object)
Function Documentation
GetChildFileSpecificationsFromThin()
FileSpec GetChildFileSpecificationsFromThin (llvm::StringRef childPath, const FileSpec & parentFileSpec)
Definition at line 386 of file ObjectContainerBSDArchive.cpp.
References lldb_private::FileSpec::GetDirectory(), and lldb_private::ConstString::GetStringRef().
Referenced by ObjectContainerBSDArchive::GetModuleSpecifications(), and ObjectContainerBSDArchive::GetObjectFile().
Variable Documentation
l
Log* l = GetLog(LLDBLog::Object)
Definition at line 76 of file ObjectContainerBSDArchive.cpp.
Referenced by ExtractLibcxxStringInfo(), lldb_private::Mangled::GuessLanguage(), lldb_private::ScratchTypeSystemClang::InferIsolatedASTKindFromLangOpts(), lldb_private::Symtab::InitNameIndexes(), lldb_private::StringList::LogDump(), lldb_private::XcodeSDK::Merge(), CoreSimulatorSupport::operator!=(), CoreSimulatorSupport::operator!=(), CoreSimulatorSupport::operator<(), CoreSimulatorSupport::operator<(), CoreSimulatorSupport::operator==(), CoreSimulatorSupport::operator==(), CoreSimulatorSupport::operator>(), CoreSimulatorSupport::operator>(), ObjectContainerBSDArchive::Archive::ParseObjects(), lldb_private::npdb::SegmentOffsetLength::SegmentOffsetLength(), lldb::SBTypeSummaryOptions::SetLanguage(), and lldb_private::formatters::StringPrinter::ReadStringAndDumpToStreamOptions::SetLocation().