LLDB: ObjectContainerMachOFileset.cpp File Reference
ObjectContainerMachOFileset.cpp File Reference
#include "ObjectContainerMachOFileset.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/ArchSpec.h"
#include "lldb/Utility/DataBuffer.h"
#include "lldb/Utility/Stream.h"
#include <optional>
Functions
static uint32_t MachHeaderSizeFromMagic (uint32_t magic)
static std::optional< mach_header > ParseMachOHeader (DataExtractor &extractor)
static bool ParseFileset (DataExtractor &extractor, mach_header header, std::vector< ObjectContainerMachOFileset::Entry > &entries, std::optional< lldb::addr_t > load_addr=std::nullopt)
Function Documentation
MachHeaderSizeFromMagic()
uint32_t MachHeaderSizeFromMagic (uint32_t magic) static
Definition at line 86 of file ObjectContainerMachOFileset.cpp.
Referenced by ObjectFileMachO::CreateSections(), ObjectFileMachO::Dump(), ObjectFileMachO::FindLC_NOTEByName(), ObjectFileMachO::GetArchitecture(), ObjectFileMachO::GetArchitecture(), ObjectFileMachO::GetDependentModules(), ObjectFileMachO::GetEncryptedFileRanges(), ObjectFileMachO::GetEntryPointAddress(), ObjectFileMachO::GetIdentifierString(), ObjectFileMachO::GetMinimumOSVersion(), ObjectFileMachO::GetModuleSpecifications(), ObjectFileMachO::GetNumThreadContexts(), ObjectFileMachO::GetSDKVersion(), ObjectFileMachO::GetUUID(), ObjectFileMachO::GetVersion(), ObjectFileMachO::IsStripped(), ObjectFileMachO::MagicBytesMatch(), ParseFileset(), lldb_private::ObjectContainerMachOFileset::ParseHeader(), lldb_private::ObjectContainerMachOFileset::ParseHeader(), ObjectFileMachO::ParseHeader(), and ObjectFileMachO::ParseSymtab().
ParseFileset()
bool ParseFileset (DataExtractor & extractor, mach_header header, std::vector< ObjectContainerMachOFileset::Entry > & entries, std::optional< lldb::addr_t > load_addr = std::nullopt) static
Definition at line 137 of file ObjectContainerMachOFileset.cpp.
References lldb_private::DataExtractor::CopyData(), lldb_private::DataExtractor::GetCStr(), lldb_private::DataExtractor::GetU32(), MachHeaderSizeFromMagic(), and segment::vmaddr.
Referenced by lldb_private::ObjectContainerMachOFileset::ParseHeader(), and lldb_private::ObjectContainerMachOFileset::ParseHeader().
ParseMachOHeader()
std::optional< mach_header > ParseMachOHeader (DataExtractor & extractor) static
Definition at line 99 of file ObjectContainerMachOFileset.cpp.
References lldb::eByteOrderBig, lldb::eByteOrderLittle, lldb_private::DataExtractor::GetU32(), lldb_private::endian::InlHostByteOrder(), lldb_private::DataExtractor::SetAddressByteSize(), and lldb_private::DataExtractor::SetByteOrder().
Referenced by lldb_private::ObjectContainerMachOFileset::ParseHeader(), and lldb_private::ObjectContainerMachOFileset::ParseHeader().