LLDB: ObjectFileXCOFF.cpp File Reference
ObjectFileXCOFF.cpp File Reference
#include "ObjectFileXCOFF.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Progress.h"
#include "lldb/Core/Section.h"
#include "lldb/Host/FileSystem.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/ArchSpec.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/DataExtractor.h"
#include "lldb/Utility/FileSpecList.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/RangeMap.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/Stream.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/XCOFF.h"
#include "llvm/Object/XCOFFObjectFile.h"
#include "llvm/Support/MemoryBuffer.h"
#include <algorithm>
#include <cassert>
#include <cstring>
#include <unordered_map>
Functions
static uint32_t XCOFFHeaderSizeFromMagic (uint32_t magic)
static lldb::SymbolType MapSymbolType (llvm::object::SymbolRef::Type sym_type)
template<typename T>
static auto GetSections (llvm::object::XCOFFObjectFile *binary)
Function Documentation
GetSections()
template<typename T> auto GetSections (llvm::object::XCOFFObjectFile * binary) static
Definition at line 315 of file ObjectFileXCOFF.cpp.
Referenced by ObjectFileXCOFF::CreateSectionsWithBitness().
MapSymbolType()
lldb::SymbolType MapSymbolType (llvm::object::SymbolRef::Type sym_type) static
Definition at line 198 of file ObjectFileXCOFF.cpp.
References lldb::eSymbolTypeCode, lldb::eSymbolTypeData, lldb::eSymbolTypeInvalid, and lldb::eSymbolTypeSourceFile.
Referenced by ObjectFileXCOFF::ParseSymtab().
XCOFFHeaderSizeFromMagic()
uint32_t XCOFFHeaderSizeFromMagic (uint32_t magic) static
Definition at line 151 of file ObjectFileXCOFF.cpp.
Referenced by ObjectFileXCOFF::MagicBytesMatch().