LLDB: Host.cpp File Reference
Host.cpp File Reference
#include <sys/types.h>
#include <sys/signal.h>
#include <sys/exec.h>
#include <sys/proc.h>
#include <sys/ptrace.h>
#include <sys/sysctl.h>
#include <sys/user.h>
#include <cstdio>
#include "lldb/Host/Host.h"
#include "lldb/Host/HostInfo.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/DataExtractor.h"
#include "lldb/Utility/Endian.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/NameMatches.h"
#include "lldb/Utility/ProcessInfo.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/StreamString.h"
#include "llvm/TargetParser/Host.h"
Namespaces
namespace lldb_private
A class that represents a running process on the host machine.
Functions
static bool GetOpenBSDProcessArgs (const ProcessInstanceInfoMatch *match_info_ptr, ProcessInstanceInfo &process_info)
static bool GetOpenBSDProcessCPUType (ProcessInstanceInfo &process_info)
static bool GetOpenBSDProcessUserAndGroup (ProcessInstanceInfo &process_info)
Function Documentation
GetOpenBSDProcessArgs()
bool GetOpenBSDProcessArgs (const ProcessInstanceInfoMatch * match_info_ptr, ProcessInstanceInfo & process_info) static
Definition at line 41 of file openbsd/Host.cpp.
References lldb_private::Args::AppendArgument(), lldb_private::ProcessInfo::GetArguments(), lldb_private::DataExtractor::GetCStr(), lldb_private::ConstString::GetCString(), lldb_private::ProcessInfo::GetExecutableFile(), lldb_private::FileSpec::GetFilename(), lldb_private::ProcessInfo::GetName(), lldb_private::ProcessInstanceInfoMatch::GetNameMatchType(), lldb_private::ProcessInfo::GetProcessID(), lldb_private::ProcessInstanceInfoMatch::GetProcessInfo(), lldb_private::endian::InlHostByteOrder(), lldb_private::NameMatches(), lldb_private::DataExtractor::PeekData(), lldb_private::ProcessInfo::ProcessIDIsValid(), and lldb_private::FileSpec::SetFile().
GetOpenBSDProcessCPUType()
bool GetOpenBSDProcessCPUType (ProcessInstanceInfo & process_info) static
Definition at line 88 of file openbsd/Host.cpp.
References lldb_private::ArchSpec::Clear(), lldb_private::ProcessInfo::GetArchitecture(), and lldb_private::ProcessInfo::ProcessIDIsValid().
GetOpenBSDProcessUserAndGroup()
bool GetOpenBSDProcessUserAndGroup (ProcessInstanceInfo & process_info) static
Definition at line 98 of file openbsd/Host.cpp.
References lldb_private::ProcessInfo::GetProcessID(), LLDB_INVALID_PROCESS_ID, lldb_private::ProcessInfo::ProcessIDIsValid(), lldb_private::ProcessInstanceInfo::SetEffectiveGroupID(), lldb_private::ProcessInstanceInfo::SetEffectiveUserID(), lldb_private::ProcessInfo::SetGroupID(), lldb_private::ProcessInstanceInfo::SetParentProcessID(), lldb_private::ProcessInfo::SetUserID(), and UINT32_MAX.