LLDB: Options.cpp File Reference
Options.cpp File Reference
#include "lldb/Interpreter/Options.h"
#include <algorithm>
#include <bitset>
#include <map>
#include <set>
#include "lldb/Host/OptionParser.h"
#include "lldb/Host/common/DiagnosticsRendering.h"
#include "lldb/Interpreter/CommandCompletions.h"
#include "lldb/Interpreter/CommandInterpreter.h"
#include "lldb/Interpreter/CommandObject.h"
#include "lldb/Interpreter/CommandReturnObject.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/AnsiTerminal.h"
#include "lldb/Utility/StreamString.h"
#include "llvm/ADT/STLExtras.h"
Classes
class lldb_private::OptionParseError
An llvm::Error that represents an option parsing diagnostic.
Namespaces
namespace lldb_private
A class that represents a running process on the host machine.
Enumerations
enum OptionDisplayType { eDisplayBestOption , eDisplayShortOption , eDisplayLongOption }
Functions
static bool PrintOption (const OptionDefinition &opt_def, OptionDisplayType display_type, const char *header, const char *footer, bool show_optional, Stream &strm)
static std::vector< char * > GetArgvForParsing (const Args &args)
static Args::const_iterator FindOriginalIter (const char *arg, const Args &original)
static size_t FindOriginalIndex (const char *arg, const Args &original)
static Args ReconstituteArgsAfterParsing (llvm::ArrayRef< char * > parsed, const Args &original)
static size_t FindArgumentIndexForOption (const Args &args, const Option &long_option)
static std::string BuildShortOptions (const Option *long_options)
Enumeration Type Documentation
OptionDisplayType
enum OptionDisplayType
Enumerator
eDisplayBestOption
eDisplayShortOption
eDisplayLongOption
Definition at line 304 of file Options.cpp.
Function Documentation
BuildShortOptions()
std::string BuildShortOptions (const Option * long_options) static
Definition at line 902 of file Options.cpp.
References lldb_private::Option::definition, lldb_private::OptionParser::eNoArgument, lldb_private::OptionParser::eOptionalArgument, and lldb_private::OptionParser::eRequiredArgument.
Referenced by lldb_private::Options::Parse(), lldb_private::Options::ParseAlias(), and lldb_private::Options::ParseForCompletion().
FindArgumentIndexForOption()
size_t FindArgumentIndexForOption (const Args & args, const Option & long_option) static
Definition at line 888 of file Options.cpp.
References lldb_private::Option::definition, lldb_private::OptionDefinition::long_option, and lldb_private::Option::val.
Referenced by lldb_private::Options::ParseAlias().
FindOriginalIndex()
size_t FindOriginalIndex (const char * arg, const Args & original) static
Definition at line 871 of file Options.cpp.
References lldb_private::Args::begin(), and FindOriginalIter().
Referenced by lldb_private::Options::ParseForCompletion().
FindOriginalIter()
Args::const_iterator FindOriginalIter (const char * arg, const Args & original) static
Definition at line 864 of file Options.cpp.
References lldb_private::Args::ArgEntry::c_str().
Referenced by FindOriginalIndex(), and ReconstituteArgsAfterParsing().
GetArgvForParsing()
std::vector< char * > GetArgvForParsing (const Args & args) static
Definition at line 853 of file Options.cpp.
Referenced by lldb_private::Options::Parse(), lldb_private::Options::ParseAlias(), and lldb_private::Options::ParseForCompletion().
PrintOption()
bool PrintOption (const OptionDefinition & opt_def, OptionDisplayType display_type, const char * header, const char * footer, bool show_optional, Stream & strm) static
Definition at line 310 of file Options.cpp.
References lldb_private::OptionDefinition::argument_type, eDisplayLongOption, eDisplayShortOption, lldb_private::OptionParser::eNoArgument, lldb_private::OptionParser::eOptionalArgument, lldb_private::OptionParser::eRequiredArgument, lldb_private::CommandObject::GetArgumentName(), lldb_private::OptionDefinition::HasShortOption(), lldb_private::OptionDefinition::long_option, lldb_private::OptionDefinition::option_has_arg, lldb_private::Stream::Printf(), lldb_private::Stream::PutChar(), lldb_private::Stream::PutCString(), lldb_private::OptionDefinition::required, and lldb_private::OptionDefinition::short_option.
Referenced by lldb_private::Options::GenerateOptionUsage().
ReconstituteArgsAfterParsing()
Args ReconstituteArgsAfterParsing (llvm::ArrayRef< char * > parsed, const Args & original) static
Definition at line 877 of file Options.cpp.
References lldb_private::Args::AppendArgument(), lldb_private::Args::end(), and FindOriginalIter().
Referenced by lldb_private::Options::Parse().