LLDB: OptionValueString.cpp File Reference
OptionValueString.cpp File Reference
#include "lldb/Interpreter/OptionValueString.h"
#include "lldb/Host/OptionParser.h"
#include "lldb/Interpreter/OptionValue.h"
#include "lldb/Utility/Args.h"
#include "lldb/Utility/Stream.h"
Functions
static void DumpString (Stream &strm, const std::string &str, bool escape, bool raw)
Function Documentation
DumpString()
void DumpString (Stream & strm, const std::string & str, bool escape, bool raw) static
Definition at line 19 of file OptionValueString.cpp.
References DumpString(), lldb_private::Args::ExpandEscapedCharacters(), lldb_private::Stream::PutCString(), and lldb_private::Stream::QuotedCString().
Referenced by DumpString(), and lldb_private::OptionValueString::DumpValue().