LLDB: OptionGroupVariable.cpp File Reference
OptionGroupVariable.cpp File Reference
#include "lldb/Interpreter/OptionGroupVariable.h"
#include "lldb/DataFormatters/DataVisualization.h"
#include "lldb/Host/OptionParser.h"
#include "lldb/Interpreter/CommandInterpreter.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/Status.h"
Functions
static Status ValidateNamedSummary (const char *str, void *)
static Status ValidateSummaryString (const char *str, void *)
Variables
static constexpr OptionDefinition g_variable_options []
static constexpr auto g_num_frame_options = 4
static const auto g_variable_options_noframe
Function Documentation
ValidateNamedSummary()
Status ValidateNamedSummary (const char * str, void *) static
Definition at line 58 of file OptionGroupVariable.cpp.
References lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataVisualization::NamedSummaryFormats::GetSummaryFormat(), and lldb_private::Status.
Referenced by lldb_private::OptionGroupVariable::OptionGroupVariable().
ValidateSummaryString()
Status ValidateSummaryString (const char * str, void *) static
Definition at line 70 of file OptionGroupVariable.cpp.
References lldb_private::Status::FromErrorStringWithFormat(), and lldb_private::Status.
Referenced by lldb_private::OptionGroupVariable::OptionGroupVariable().
Variable Documentation
g_num_frame_options
auto g_num_frame_options = 4 static constexpr
Definition at line 53 of file OptionGroupVariable.cpp.
g_variable_options
OptionDefinition g_variable_options[] static constexpr
Initial value:
= {
    {LLDB_OPT_SET_1 | LLDB_OPT_SET_2, false, "no-args", 'a',
     OptionParser::eNoArgument, nullptr, {}, 0, eArgTypeNone,
     "Omit function arguments."},
    {LLDB_OPT_SET_1 | LLDB_OPT_SET_2, false, "no-recognized-args", 't',
     OptionParser::eNoArgument, nullptr, {}, 0, eArgTypeNone,
     "Omit recognized function arguments."},
    {LLDB_OPT_SET_1 | LLDB_OPT_SET_2, false, "no-locals", 'l',
     OptionParser::eNoArgument, nullptr, {}, 0, eArgTypeNone,
     "Omit local variables."},
    {LLDB_OPT_SET_1 | LLDB_OPT_SET_2, false, "show-globals", 'g',
     OptionParser::eNoArgument, nullptr, {}, 0, eArgTypeNone,
     "Show the current frame source file global and static variables."},
    {LLDB_OPT_SET_1 | LLDB_OPT_SET_2, false, "show-declaration", 'c',
     OptionParser::eNoArgument, nullptr, {}, 0, eArgTypeNone,
     "Show variable declaration information (source file and line where the "
     "variable was declared)."},
    {LLDB_OPT_SET_1 | LLDB_OPT_SET_2, false, "regex", 'r',
     OptionParser::eNoArgument, nullptr, {}, 0, eArgTypeRegularExpression,
     "The <variable-name> argument for name lookups are regular expressions."},
    {LLDB_OPT_SET_1 | LLDB_OPT_SET_2, false, "scope", 's',
     OptionParser::eNoArgument, nullptr, {}, 0, eArgTypeNone,
     "Show variable scope (argument, local, global, static)."},
    {LLDB_OPT_SET_1, false, "summary", 'y', OptionParser::eRequiredArgument,
     nullptr, {}, 0, eArgTypeName,
     "Specify the summary that the variable output should use."},
    {LLDB_OPT_SET_2, false, "summary-string", 'z',
     OptionParser::eRequiredArgument, nullptr, {}, 0, eArgTypeName,
     "Specify a summary string to use to format the variable output."},
}
Definition at line 22 of file OptionGroupVariable.cpp.
Referenced by lldb_private::OptionGroupVariable::GetDefinitions(), and lldb_private::OptionGroupVariable::SetOptionValue().
g_variable_options_noframe
const auto g_variable_options_noframe static
Initial value:
=
    llvm::ArrayRef<OptionDefinition>(g_variable_options)
        .drop_front(g_num_frame_options)
Definition at line 54 of file OptionGroupVariable.cpp.
Referenced by lldb_private::OptionGroupVariable::GetDefinitions(), and lldb_private::OptionGroupVariable::SetOptionValue().