LLDB: PdbAstBuilderClang.cpp File Reference
PdbAstBuilderClang.cpp File Reference
#include "PdbAstBuilderClang.h"
#include "llvm/DebugInfo/CodeView/CVTypeVisitor.h"
#include "llvm/DebugInfo/CodeView/LazyRandomTypeCollection.h"
#include "llvm/DebugInfo/CodeView/RecordName.h"
#include "llvm/DebugInfo/CodeView/SymbolDeserializer.h"
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
#include "llvm/DebugInfo/CodeView/SymbolRecordHelpers.h"
#include "llvm/DebugInfo/CodeView/TypeDeserializer.h"
#include "llvm/DebugInfo/CodeView/TypeVisitorCallbacks.h"
#include "llvm/DebugInfo/PDB/Native/DbiStream.h"
#include "llvm/DebugInfo/PDB/Native/PublicsStream.h"
#include "llvm/DebugInfo/PDB/Native/SymbolStream.h"
#include "llvm/DebugInfo/PDB/Native/TpiStream.h"
#include "llvm/Demangle/MicrosoftDemangle.h"
#include "PdbUtil.h"
#include "Plugins/ExpressionParser/Clang/ClangASTMetadata.h"
#include "Plugins/ExpressionParser/Clang/ClangUtil.h"
#include "Plugins/Language/CPlusPlus/MSVCUndecoratedNameParser.h"
#include "Plugins/TypeSystem/Clang/TypeSystemClang.h"
#include "SymbolFileNativePDB.h"
#include "UdtRecordCompleter.h"
#include "lldb/Core/Module.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Utility/LLDBAssert.h"
#include <optional>
#include <string_view>
Functions
static clang::TagTypeKind TranslateUdtKind (const TagRecord &cr)
static bool IsCVarArgsFunction (llvm::ArrayRef< TypeIndex > args)
static bool AnyScopesHaveTemplateParams (llvm::ArrayRef< llvm::ms_demangle::Node * > scopes)
static std::optional< clang::CallingConv > TranslateCallingConvention (llvm::codeview::CallingConvention conv)
static bool IsAnonymousNamespaceName (llvm::StringRef name)
static bool isLocalVariableType (SymbolKind K)
static bool isTagDecl (clang::DeclContext &context)
static bool isFunctionDecl (clang::DeclContext &context)
static bool isBlockDecl (clang::DeclContext &context)
static CVSymbolArray skipFunctionParameters (clang::Decl &decl, const CVSymbolArray &symbols)
Function Documentation
AnyScopesHaveTemplateParams()
bool AnyScopesHaveTemplateParams (llvm::ArrayRef< llvm::ms_demangle::Node * > scopes) static
Definition at line 125 of file PdbAstBuilderClang.cpp.
Referenced by lldb_private::npdb::PdbAstBuilderClang::CreateDeclInfoForType().
IsAnonymousNamespaceName()
bool IsAnonymousNamespaceName (llvm::StringRef name) static
Definition at line 160 of file PdbAstBuilderClang.cpp.
Referenced by PDBASTParser::GetDeclContextContainingSymbol(), and lldb_private::npdb::PdbAstBuilderClang::GetOrCreateNamespaceDecl().
isBlockDecl()
bool isBlockDecl (clang::DeclContext & context) static
Definition at line 1291 of file PdbAstBuilderClang.cpp.
Referenced by lldb_private::npdb::PdbAstBuilderClang::ParseDeclsForContext(), and lldb_private::npdb::PdbAstBuilderClang::ParseDeclsForSimpleContext().
IsCVarArgsFunction()
bool IsCVarArgsFunction (llvm::ArrayRef< TypeIndex > args) static
Definition at line 118 of file PdbAstBuilderClang.cpp.
Referenced by lldb_private::npdb::PdbAstBuilderClang::CreateFunctionType().
isFunctionDecl()
bool isFunctionDecl (clang::DeclContext & context) static
Definition at line 1287 of file PdbAstBuilderClang.cpp.
Referenced by lldb_private::npdb::PdbAstBuilderClang::ParseDeclsForContext(), and lldb_private::npdb::PdbAstBuilderClang::ParseDeclsForSimpleContext().
isLocalVariableType()
bool isLocalVariableType (SymbolKind K) static
Definition at line 233 of file PdbAstBuilderClang.cpp.
Referenced by lldb_private::npdb::PdbAstBuilderClang::GetOrCreateSymbolForId(), and skipFunctionParameters().
isTagDecl()
bool isTagDecl (clang::DeclContext & context) static
Definition at line 1283 of file PdbAstBuilderClang.cpp.
Referenced by lldb_private::npdb::PdbAstBuilderClang::ParseDeclsForContext().
skipFunctionParameters()
CVSymbolArray skipFunctionParameters (clang::Decl & decl, const CVSymbolArray & symbols) static
Definition at line 1387 of file PdbAstBuilderClang.cpp.
References isLocalVariableType().
Referenced by lldb_private::npdb::PdbAstBuilderClang::ParseBlockChildren().
TranslateCallingConvention()
std::optional< clang::CallingConv > TranslateCallingConvention (llvm::codeview::CallingConvention conv) static
Definition at line 135 of file PdbAstBuilderClang.cpp.
Referenced by lldb_private::npdb::PdbAstBuilderClang::CreateFunctionType(), and PDBASTParser::CreateLLDBTypeFromPDBType().
TranslateUdtKind()
clang::TagTypeKind TranslateUdtKind (const TagRecord & cr) static
Definition at line 100 of file PdbAstBuilderClang.cpp.
References lldbassert.
Referenced by PDBASTParser::CompleteTypeFromUDT(), PDBASTParser::CreateLLDBTypeFromPDBType(), and lldb_private::npdb::PdbAstBuilderClang::CreateRecordType().