LLDB: PdbFPOProgramToDWARFExpression.cpp File Reference
PdbFPOProgramToDWARFExpression.cpp File Reference
#include "PdbFPOProgramToDWARFExpression.h"
#include "CodeViewRegisterMapping.h"
#include "lldb/Symbol/PostfixExpression.h"
#include "lldb/Utility/LLDBAssert.h"
#include "lldb/Utility/Stream.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/DebugInfo/CodeView/CodeView.h"
#include "llvm/DebugInfo/CodeView/EnumTables.h"
#include "llvm/Support/ScopedPrinter.h"
Functions
static uint32_t ResolveLLDBRegisterNum (llvm::StringRef reg_name, llvm::Triple::ArchType arch_type)
static Node * ResolveFPOProgram (llvm::StringRef program, llvm::StringRef register_name, llvm::Triple::ArchType arch_type, llvm::BumpPtrAllocator &alloc)
Function Documentation
ResolveFPOProgram()
Node * ResolveFPOProgram (llvm::StringRef program, llvm::StringRef register_name, llvm::Triple::ArchType arch_type, llvm::BumpPtrAllocator & alloc) static
Definition at line 54 of file PdbFPOProgramToDWARFExpression.cpp.
References lldb_private::postfix::SymbolNode::GetName(), LLDB_INVALID_REGNUM, lldb_private::postfix::MakeNode(), lldb_private::postfix::ParseFPOProgram(), ResolveLLDBRegisterNum(), and lldb_private::postfix::ResolveSymbols().
Referenced by lldb_private::npdb::TranslateFPOProgramToDWARFExpression().
ResolveLLDBRegisterNum()
uint32_t ResolveLLDBRegisterNum (llvm::StringRef reg_name, llvm::Triple::ArchType arch_type) static
Definition at line 26 of file PdbFPOProgramToDWARFExpression.cpp.
References lldb_private::npdb::GetLLDBRegisterNumber(), and LLDB_INVALID_REGNUM.
Referenced by ResolveFPOProgram().