LLDB: PDBLocationToDWARFExpression.cpp File Reference
PDBLocationToDWARFExpression.cpp File Reference
#include "PDBLocationToDWARFExpression.h"
#include "lldb/Core/Section.h"
#include "lldb/Core/dwarf.h"
#include "lldb/Expression/DWARFExpression.h"
#include "lldb/Symbol/Variable.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/StreamBuffer.h"
#include "llvm/DebugInfo/CodeView/CodeView.h"
#include "llvm/DebugInfo/PDB/IPDBSession.h"
#include "llvm/DebugInfo/PDB/PDBSymbolData.h"
#include "Plugins/SymbolFile/NativePDB/CodeViewRegisterMapping.h"
#include "Plugins/SymbolFile/NativePDB/PdbFPOProgramToDWARFExpression.h"
Functions
static std::unique_ptr< IPDBFrameData > GetCorrespondingFrameData (const IPDBSession &session, const Variable::RangeList &ranges)
static bool EmitVFrameEvaluationDWARFExpression (llvm::StringRef program, llvm::Triple::ArchType arch_type, Stream &stream)
DWARFExpression ConvertPDBLocationToDWARFExpression (ModuleSP module, const PDBSymbolData &symbol, const Variable::RangeList &ranges, bool &is_constant)
Function Documentation
ConvertPDBLocationToDWARFExpression()
DWARFExpression ConvertPDBLocationToDWARFExpression (ModuleSP module, const PDBSymbolData & symbol, const Variable::RangeList & ranges, bool & is_constant)
Definition at line 67 of file PDBLocationToDWARFExpression.cpp.
References lldb_private::Stream::eBinary, lldb::eByteOrderInvalid, EmitVFrameEvaluationDWARFExpression(), lldb::eRegisterKindDWARF, lldb::eRegisterKindGeneric, lldb::eRegisterKindLLDB, lldb_private::SectionList::FindSectionByID(), lldb_private::ArchSpec::GetAddressByteSize(), lldb_private::ArchSpec::GetByteOrder(), GetCorrespondingFrameData(), lldb_private::StreamBuffer< N >::GetData(), lldb_private::npdb::GetLLDBRegisterNumber(), lldb_private::ArchSpec::GetMachine(), lldb_private::StreamBuffer< N >::GetSize(), lldb_private::endian::InlHostByteOrder(), LLDB_INVALID_REGNUM, LLDB_REGNUM_GENERIC_FP, lldb_private::Stream::PutHex8(), lldb_private::Stream::PutMaxHex64(), lldb_private::Stream::PutRawBytes(), lldb_private::Stream::PutSLEB128(), lldb_private::Stream::PutULEB128(), and lldb_private::DWARFExpression::SetRegisterKind().
Referenced by SymbolFilePDB::ParseVariableForPDBData().
EmitVFrameEvaluationDWARFExpression()
bool EmitVFrameEvaluationDWARFExpression (llvm::StringRef program, llvm::Triple::ArchType arch_type, Stream & stream) static
Definition at line 60 of file PDBLocationToDWARFExpression.cpp.
References lldb_private::npdb::TranslateFPOProgramToDWARFExpression().
Referenced by ConvertPDBLocationToDWARFExpression().
GetCorrespondingFrameData()
std::unique_ptr< IPDBFrameData > GetCorrespondingFrameData (const IPDBSession & session, const Variable::RangeList & ranges) static
Definition at line 32 of file PDBLocationToDWARFExpression.cpp.
References lldb_private::RangeVector< B, S, N >::GetEntryAtIndex(), and lldb_private::RangeVector< B, S, N >::GetSize().
Referenced by ConvertPDBLocationToDWARFExpression().