LLDB: PECallFrameInfo.cpp File Reference
PECallFrameInfo.cpp File Reference
#include "PECallFrameInfo.h"
#include "ObjectFilePECOFF.h"
#include "Plugins/Process/Utility/lldb-x86-register-enums.h"
#include "lldb/Symbol/UnwindPlan.h"
#include "llvm/Support/Win64EH.h"
Classes
struct EHInstruction
class UnwindCodesIterator
class EHProgramBuilder
class EHProgramRange
Typedefs
using EHProgram = std::vector<EHInstruction>
Functions
template<typename T>
static const T * TypedRead (const DataExtractor &data_extractor, offset_t &offset, offset_t size=sizeof(T))
Typedef Documentation
EHProgram
using EHProgram = std::vector<EHInstruction>
Definition at line 33 of file PECallFrameInfo.cpp.
Function Documentation
TypedRead()
template<typename T> const T * TypedRead (const DataExtractor & data_extractor, offset_t & offset, offset_t size = sizeof(T)) static
Definition at line 14 of file PECallFrameInfo.cpp.
References lldb_private::DataExtractor::GetData().
Referenced by PECallFrameInfo::FindRuntimeFunctionIntersectsWithRange(), and UnwindCodesIterator::GetNext().