LLDB: PlatformiOSSimulatorCoreSimulatorSupport.mm File Reference
PlatformiOSSimulatorCoreSimulatorSupport.mm File Reference
#include "PlatformiOSSimulatorCoreSimulatorSupport.h"
#include <CoreFoundation/CoreFoundation.h>
#include <Foundation/Foundation.h>
#include "lldb/Host/PseudoTerminal.h"
#include "lldb/Host/FileAction.h"
#include "llvm/ADT/StringRef.h"
Classes
class SimServiceContext
protocol <LLDBCoreSimulatorSupport>
Macros
#define kSimDeviceBootPersist
#define kSimDeviceSpawnEnvironment
#define kSimDeviceSpawnStdin @"stdin" /* An NSNumber corresponding to a fd */
#define kSimDeviceSpawnStdout
#define kSimDeviceSpawnStderr
#define kSimDeviceSpawnArguments
#define kSimDeviceSpawnWaitForDebugger @"wait_for_debugger" /* An NSNumber (bool) */
#define kSimDeviceSpawnStandalone @"standalone"
Functions
static Status HandleFileAction (ProcessLaunchInfo &launch_info, NSMutableDictionary *options, NSString *key, const int fd, lldb::FileSP &file)
Macro Definition Documentation
kSimDeviceBootPersist
#define kSimDeviceBootPersist
Value:
  @"persist" /* An NSNumber (boolean) indicating whether or not the session    \
                should outlive the calling process (default false) */
Referenced by CoreSimulatorSupport::Device::Boot().
kSimDeviceSpawnArguments
#define kSimDeviceSpawnArguments
Value:
  @"arguments" /* An NSArray of strings to use as the argv array.  If not      \
                  provided, path will be argv[0] */
kSimDeviceSpawnEnvironment
#define kSimDeviceSpawnEnvironment
Value:
  @"environment" /* An NSDictionary (NSStrings -> NSStrings) of environment    \
                    key/values */
kSimDeviceSpawnStandalone
#define kSimDeviceSpawnStandalone @"standalone"
kSimDeviceSpawnStderr
#define kSimDeviceSpawnStderr
Value:
                                           @"stderr" /* An NSNumber corresponding to a fd   \
                                           */
Referenced by CoreSimulatorSupport::Device::Spawn().
kSimDeviceSpawnStdin
#define kSimDeviceSpawnStdin @"stdin" /* An NSNumber corresponding to a fd */
Referenced by CoreSimulatorSupport::Device::Spawn().
kSimDeviceSpawnStdout
#define kSimDeviceSpawnStdout
Value:
                                           @"stdout" /* An NSNumber corresponding to a fd   \
                                           */
Referenced by CoreSimulatorSupport::Device::Spawn().
kSimDeviceSpawnWaitForDebugger
#define kSimDeviceSpawnWaitForDebugger @"wait_for_debugger" /* An NSNumber (bool) */
Function Documentation
HandleFileAction()
Status HandleFileAction (ProcessLaunchInfo & launch_info, NSMutableDictionary * options, NSString * key, const int fd, lldb::FileSP & file) static
Definition at line 378 of file PlatformiOSSimulatorCoreSimulatorSupport.mm.
References lldb_private::Status::AsCString(), lldb_private::FileAction::eFileActionClose, lldb_private::FileAction::eFileActionDuplicate, lldb_private::FileAction::eFileActionNone, lldb_private::FileAction::eFileActionOpen, lldb_private::File::eOpenOptionReadOnly, lldb_private::File::eOpenOptionReadWrite, lldb_private::File::eOpenOptionWriteOnly, error(), lldb_private::Status::FromErrno(), lldb_private::Status::FromError(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::FileAction::GetAction(), lldb_private::FileAction::GetActionArgument(), lldb_private::ProcessLaunchInfo::GetFileActionForFD(), lldb_private::FileAction::GetFileSpec(), lldb_private::FileSpec::GetPath(), lldb_private::PseudoTerminal::GetPrimaryFileDescriptor(), lldb_private::ProcessLaunchInfo::GetPTY(), lldb_private::PseudoTerminal::GetSecondaryFileDescriptor(), lldb_private::PseudoTerminal::GetSecondaryName(), lldb_private::PseudoTerminal::invalid_fd, lldb_private::PseudoTerminal::OpenSecondary(), S_IRUSR, and S_IWUSR.
Referenced by CoreSimulatorSupport::Device::Spawn().