LLDB: PlatformDarwin.cpp File Reference
PlatformDarwin.cpp File Reference
#include "PlatformDarwin.h"
#include <cstring>
#include <algorithm>
#include <memory>
#include <mutex>
#include <optional>
#include "lldb/Breakpoint/BreakpointLocation.h"
#include "lldb/Breakpoint/BreakpointSite.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Section.h"
#include "lldb/Host/Host.h"
#include "lldb/Host/HostInfo.h"
#include "lldb/Host/XML.h"
#include "lldb/Interpreter/CommandInterpreter.h"
#include "lldb/Interpreter/OptionValueProperties.h"
#include "lldb/Interpreter/OptionValueString.h"
#include "lldb/Interpreter/Options.h"
#include "lldb/Symbol/CompileUnit.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Symbol/SymbolFile.h"
#include "lldb/Symbol/SymbolVendor.h"
#include "lldb/Target/DynamicLoader.h"
#include "lldb/Target/Platform.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/ProcessInfo.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/Timer.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringTable.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Threading.h"
#include "llvm/Support/VersionTuple.h"
#include "clang/Options/Options.inc"
#include "PlatformMacOSXProperties.inc"
#include "PlatformMacOSXPropertiesEnum.inc"
Classes
class PlatformDarwinProperties
Macros
#define OPTTABLE_STR_TABLE_CODE
#define LLDB_PROPERTIES_platformdarwin
#define LLDB_PROPERTIES_platformdarwin
#define OPTION(PREFIX_OFFSET, NAME_OFFSET, VAR, ...)
Enumerations
enum
Functions
static Status ExceptionMaskValidator (const char *string, void *unused)
static PlatformDarwinProperties & GetGlobalProperties ()
static FileSpecList LocateExecutableScriptingResourcesFromDSYM (Stream &feedback_stream, FileSpec module_spec, const Target &target, const FileSpec &symfile_spec)
static llvm::ArrayRef< const char * > GetCompatibleArchs (ArchSpec::Core core)
static FileSpec GetXcodeSelectPath ()
static FileSpec GetCommandLineToolsLibraryPath ()
static llvm::Expected< lldb_private::FileSpec > ResolveSDKPathFromDebugInfo (lldb_private::Target *target)
Variables
static uint32_t g_initialize_count = 0
Macro Definition Documentation
LLDB_PROPERTIES_platformdarwin [1/2]
#define LLDB_PROPERTIES_platformdarwin
Definition at line 122 of file PlatformDarwin.cpp.
LLDB_PROPERTIES_platformdarwin [2/2]
#define LLDB_PROPERTIES_platformdarwin
Definition at line 122 of file PlatformDarwin.cpp.
OPTION
#define OPTION (PREFIX_OFFSET, NAME_OFFSET, VAR, ...)
Value:
  llvm::StringRef opt_##VAR = OptionStrTable[NAME_OFFSET];                     \
  (void)opt_##VAR;
OPTTABLE_STR_TABLE_CODE
#define OPTTABLE_STR_TABLE_CODE
Definition at line 59 of file PlatformDarwin.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Definition at line 126 of file PlatformDarwin.cpp.
Function Documentation
ExceptionMaskValidator()
Status ExceptionMaskValidator (const char * string, void * unused) static
Definition at line 63 of file PlatformDarwin.cpp.
References error(), and lldb_private::Status::FromErrorStringWithFormat().
Referenced by lldb_private::PlatformDarwin::DebuggerInitialize().
GetCommandLineToolsLibraryPath()
FileSpec GetCommandLineToolsLibraryPath () static
Definition at line 789 of file PlatformDarwin.cpp.
References lldb_private::FileSpec::AppendPathComponent(), GetXcodeSelectPath(), and lldb_private::FileSystem::Instance().
Referenced by lldb_private::PlatformDarwin::GetSDKDirectoryForModules(), and lldb_private::PlatformDarwin::LocateExecutable().
GetCompatibleArchs()
llvm::ArrayRef< const char * > GetCompatibleArchs (ArchSpec::Core core) static
Definition at line 558 of file PlatformDarwin.cpp.
References lldb_private::ArchSpec::eCore_arm_arm64, lldb_private::ArchSpec::eCore_arm_arm64e, lldb_private::ArchSpec::eCore_arm_armv4, lldb_private::ArchSpec::eCore_arm_armv5, lldb_private::ArchSpec::eCore_arm_armv6, lldb_private::ArchSpec::eCore_arm_armv6m, lldb_private::ArchSpec::eCore_arm_armv7, lldb_private::ArchSpec::eCore_arm_armv7em, lldb_private::ArchSpec::eCore_arm_armv7f, lldb_private::ArchSpec::eCore_arm_armv7k, lldb_private::ArchSpec::eCore_arm_armv7m, and lldb_private::ArchSpec::eCore_arm_armv7s.
Referenced by lldb_private::PlatformDarwin::ARMGetSupportedArchitectures().
GetGlobalProperties()
PlatformDarwinProperties & GetGlobalProperties () static
Definition at line 161 of file PlatformDarwin.cpp.
GetXcodeSelectPath()
FileSpec GetXcodeSelectPath () static
Definition at line 677 of file PlatformDarwin.cpp.
References lldb_private::FileSystem::Instance(), lldb_private::Host::RunShellCommand(), and lldb_private::Status::Success().
Referenced by GetCommandLineToolsLibraryPath().
LocateExecutableScriptingResourcesFromDSYM()
FileSpecList LocateExecutableScriptingResourcesFromDSYM (Stream & feedback_stream, FileSpec module_spec, const Target & target, const FileSpec & symfile_spec) static
Definition at line 203 of file PlatformDarwin.cpp.
References lldb_private::FileSpecList::Append(), lldb_private::ConstString::GetCString(), lldb_private::StreamString::GetData(), lldb_private::Target::GetDebugger(), lldb_private::FileSpec::GetDirectory(), lldb_private::FileSpec::GetFilename(), lldb_private::FileSpec::GetFileNameStrippingExtension(), lldb_private::FileSpec::GetPath(), lldb_private::Debugger::GetScriptInterpreter(), lldb_private::StreamString::GetString(), lldb_private::FileSystem::Instance(), lldb_private::ScriptInterpreter::IsReservedWord(), lldb_private::Stream::Printf(), lldb_private::FileSystem::Resolve(), and lldb_private::FileSpec::SetFilename().
Referenced by lldb_private::PlatformDarwin::LocateExecutableScriptingResources().
ResolveSDKPathFromDebugInfo()
llvm::Expected< lldb_private::FileSpec > ResolveSDKPathFromDebugInfo (lldb_private::Target * target) static
Definition at line 1094 of file PlatformDarwin.cpp.
References lldb_private::SymbolFile::GetCompileUnitAtIndex(), lldb_private::Target::GetExecutableModule(), lldb_private::SymbolFile::GetNumCompileUnits(), lldb_private::XcodeSDK::GetSysroot(), lldb_private::FileSystem::Instance(), lldb_private::XcodeSDK::Merge(), and lldb_private::SymbolFile::ParseXcodeSDK().
Variable Documentation
g_initialize_count
uint32_t g_initialize_count = 0 static
Definition at line 90 of file PlatformDarwin.cpp.