LLDB: PlatformQemuUser.cpp File Reference
PlatformQemuUser.cpp File Reference
#include "Plugins/Platform/QemuUser/PlatformQemuUser.h"
#include "Plugins/Process/gdb-remote/ProcessGDBRemote.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Host/FileSystem.h"
#include "lldb/Host/ProcessLaunchInfo.h"
#include "lldb/Interpreter/OptionValueProperties.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Listener.h"
#include "lldb/Utility/Log.h"
#include "PlatformQemuUserProperties.inc"
#include "PlatformQemuUserPropertiesEnum.inc"
Macros
#define LLDB_PROPERTIES_platformqemuuser
#define LLDB_PROPERTIES_platformqemuuser
Functions
static PluginProperties & GetGlobalProperties ()
static auto get_arg_range (const Args &args)
static Environment ComputeLaunchEnvironment (Environment target, Environment host)
Macro Definition Documentation
LLDB_PROPERTIES_platformqemuuser [1/2]
#define LLDB_PROPERTIES_platformqemuuser
Definition at line 27 of file PlatformQemuUser.cpp.
LLDB_PROPERTIES_platformqemuuser [2/2]
#define LLDB_PROPERTIES_platformqemuuser
Definition at line 27 of file PlatformQemuUser.cpp.
Function Documentation
ComputeLaunchEnvironment()
Environment ComputeLaunchEnvironment (Environment target, Environment host) static
Definition at line 126 of file PlatformQemuUser.cpp.
References lldb_private::Environment::compose().
Referenced by lldb_private::PlatformQemuUser::DebugProcess().
get_arg_range()
auto get_arg_range (const Args & args) static
Definition at line 117 of file PlatformQemuUser.cpp.
References lldb_private::Args::GetArgumentArrayRef().
Referenced by lldb_private::PlatformQemuUser::DebugProcess(), and lldb_private::PlatformWasm::DebugProcess().
GetGlobalProperties()
PluginProperties & GetGlobalProperties () static
Definition at line 72 of file PlatformQemuUser.cpp.