LLDB: PlatformPOSIX.cpp File Reference
PlatformPOSIX.cpp File Reference
#include "PlatformPOSIX.h"
#include "Plugins/Platform/gdb-server/PlatformRemoteGDBServer.h"
#include "Plugins/TypeSystem/Clang/TypeSystemClang.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Module.h"
#include "lldb/Expression/DiagnosticManager.h"
#include "lldb/Expression/FunctionCaller.h"
#include "lldb/Expression/UserExpression.h"
#include "lldb/Expression/UtilityFunction.h"
#include "lldb/Host/File.h"
#include "lldb/Host/FileCache.h"
#include "lldb/Host/FileSystem.h"
#include "lldb/Host/Host.h"
#include "lldb/Host/HostInfo.h"
#include "lldb/Host/ProcessLaunchInfo.h"
#include "lldb/Target/DynamicLoader.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/FileSpec.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/ValueObject/ValueObject.h"
#include "llvm/ADT/ScopeExit.h"
#include <optional>
Functions
static uint32_t chown_file (Platform *platform, const char *path, uint32_t uid=UINT32_MAX, uint32_t gid=UINT32_MAX)
Function Documentation
chown_file()
uint32_t chown_file (Platform * platform, const char * path, uint32_t uid = UINT32_MAX, uint32_t gid = UINT32_MAX) static
Definition at line 69 of file PlatformPOSIX.cpp.
References lldb_private::StreamString::GetData(), lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), lldb_private::Platform::RunShellCommand(), and UINT32_MAX.
Referenced by PlatformPOSIX::PutFile().