LLDB: Platform.cpp File Reference
Platform.cpp File Reference
#include <algorithm>
#include <csignal>
#include <fstream>
#include <memory>
#include <optional>
#include <vector>
#include "lldb/Breakpoint/BreakpointIDList.h"
#include "lldb/Breakpoint/BreakpointLocation.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Host/FileCache.h"
#include "lldb/Host/FileSystem.h"
#include "lldb/Host/Host.h"
#include "lldb/Host/HostInfo.h"
#include "lldb/Host/OptionParser.h"
#include "lldb/Interpreter/OptionValueFileSpec.h"
#include "lldb/Interpreter/OptionValueProperties.h"
#include "lldb/Interpreter/Property.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Target/ModuleCache.h"
#include "lldb/Target/Platform.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/UnixSignals.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/FileSpec.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/StructuredData.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "TargetProperties.inc"
#include "TargetPropertiesEnum.inc"
Classes
struct RecurseCopyBaton
Macros
#define MAP_PRIVATE 2
#define MAP_ANON 0x1000
#define LLDB_PROPERTIES_platform
#define LLDB_PROPERTIES_platform
Functions
static PlatformSP & GetHostPlatformSP ()
static FileSystem::EnumerateDirectoryResult RecurseCopy_Callback (void *baton, llvm::sys::fs::file_type ft, llvm::StringRef path)
Variables
static constexpr OptionDefinition g_rsync_option_table []
static constexpr OptionDefinition g_ssh_option_table []
static constexpr OptionDefinition g_caching_option_table []
Macro Definition Documentation
LLDB_PROPERTIES_platform [1/2]
#define LLDB_PROPERTIES_platform
Definition at line 65 of file Platform.cpp.
LLDB_PROPERTIES_platform [2/2]
#define LLDB_PROPERTIES_platform
Definition at line 65 of file Platform.cpp.
MAP_ANON
#define MAP_ANON 0x1000
Definition at line 49 of file Platform.cpp.
MAP_PRIVATE
#define MAP_PRIVATE 2
Definition at line 48 of file Platform.cpp.
Function Documentation
GetHostPlatformSP()
PlatformSP & GetHostPlatformSP () static
Definition at line 56 of file Platform.cpp.
Referenced by lldb_private::Platform::GetHostPlatform(), and lldb_private::Platform::SetHostPlatform().
RecurseCopy_Callback()
FileSystem::EnumerateDirectoryResult RecurseCopy_Callback (void * baton, llvm::sys::fs::file_type ft, llvm::StringRef path) static
Definition at line 383 of file Platform.cpp.
References lldb_private::Status::AsCString(), lldb_private::Platform::CreateSymlink(), RecurseCopyBaton::dst, lldb_private::FileSystem::eEnumerateDirectoryResultNext, lldb_private::FileSystem::eEnumerateDirectoryResultQuit, lldb_private::FileSystem::EnumerateDirectory(), error(), RecurseCopyBaton::error, lldb_private::Status::Fail(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::FileSpec::GetFilename(), lldb_private::FileSpec::GetPath(), lldb_private::FileSpec::GetPathAsConstString(), lldb_private::FileSystem::Instance(), lldb_private::Platform::MakeDirectory(), RecurseCopyBaton::platform_ptr, lldb_private::Platform::PutFile(), lldb_private::FileSystem::Readlink(), RecurseCopy_Callback(), lldb_private::FileSpec::SetDirectory(), lldb_private::FileSpec::SetFilename(), and lldb_private::Status.
Referenced by lldb_private::Platform::Install(), and RecurseCopy_Callback().
Variable Documentation
g_caching_option_table
OptionDefinition g_caching_option_table[] static constexpr
Initial value:
= {
    {LLDB_OPT_SET_ALL, false, "local-cache-dir", 'c',
     OptionParser::eRequiredArgument, nullptr, {}, 0, eArgTypePath,
     "Path in which to store local copies of files."},
}
Definition at line 1313 of file Platform.cpp.
Referenced by lldb_private::OptionGroupPlatformCaching::GetDefinitions().
g_rsync_option_table
OptionDefinition g_rsync_option_table[] static constexpr
Initial value:
= {
    {LLDB_OPT_SET_ALL, false, "rsync", 'r', OptionParser::eNoArgument, nullptr,
     {}, 0, eArgTypeNone, "Enable rsync."},
    {LLDB_OPT_SET_ALL, false, "rsync-opts", 'R',
     OptionParser::eRequiredArgument, nullptr, {}, 0, eArgTypeCommandName,
     "Platform-specific options required for rsync to work."},
    {LLDB_OPT_SET_ALL, false, "rsync-prefix", 'P',
     OptionParser::eRequiredArgument, nullptr, {}, 0, eArgTypeCommandName,
     "Platform-specific rsync prefix put before the remote path."},
    {LLDB_OPT_SET_ALL, false, "ignore-remote-hostname", 'i',
     OptionParser::eNoArgument, nullptr, {}, 0, eArgTypeNone,
     "Do not automatically fill in the remote hostname when composing the "
     "rsync command."},
}
Definition at line 1290 of file Platform.cpp.
Referenced by lldb_private::OptionGroupPlatformRSync::GetDefinitions().
g_ssh_option_table
OptionDefinition g_ssh_option_table[] static constexpr
Initial value:
= {
    {LLDB_OPT_SET_ALL, false, "ssh", 's', OptionParser::eNoArgument, nullptr,
     {}, 0, eArgTypeNone, "Enable SSH."},
    {LLDB_OPT_SET_ALL, false, "ssh-opts", 'S', OptionParser::eRequiredArgument,
     nullptr, {}, 0, eArgTypeCommandName,
     "Platform-specific options required for SSH to work."},
}
Definition at line 1305 of file Platform.cpp.
Referenced by lldb_private::OptionGroupPlatformSSH::GetDefinitions().