LLDB: PlatformAndroidRemoteGDBServer.cpp File Reference
PlatformAndroidRemoteGDBServer.cpp File Reference
#include "lldb/Host/ConnectionFileDescriptor.h"
#include "lldb/Host/common/TCPSocket.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/UriParser.h"
#include "PlatformAndroidRemoteGDBServer.h"
#include <optional>
#include <sstream>
Functions
static Status ForwardPortWithAdb (const uint16_t local_port, const uint16_t remote_port, llvm::StringRef remote_socket_name, const std::optional< AdbClient::UnixSocketNamespace > &socket_namespace, std::string &device_id)
static Status DeleteForwardPortWithAdb (uint16_t local_port, const std::string &device_id)
static Status FindUnusedPort (uint16_t &port)
Variables
static const lldb::pid_t g_remote_platform_pid
Function Documentation
DeleteForwardPortWithAdb()
Status DeleteForwardPortWithAdb (uint16_t local_port, const std::string & device_id) static
Definition at line 60 of file PlatformAndroidRemoteGDBServer.cpp.
References lldb_private::platform_android::AdbClient::DeletePortForwarding().
Referenced by lldb_private::platform_android::PlatformAndroidRemoteGDBServer::DeleteForwardPort(), and lldb_private::platform_android::PlatformAndroidRemoteGDBServer::~PlatformAndroidRemoteGDBServer().
FindUnusedPort()
Status FindUnusedPort (uint16_t & port) static
Definition at line 66 of file PlatformAndroidRemoteGDBServer.cpp.
References error().
Referenced by lldb_private::platform_android::PlatformAndroidRemoteGDBServer::MakeConnectURL().
ForwardPortWithAdb()
Status ForwardPortWithAdb (const uint16_t local_port, const uint16_t remote_port, llvm::StringRef remote_socket_name, const std::optional< AdbClient::UnixSocketNamespace > & socket_namespace, std::string & device_id) static
Definition at line 29 of file PlatformAndroidRemoteGDBServer.cpp.
References lldb_private::Status::FromError(), lldb_private::Status::FromErrorString(), lldb_private::GetLog(), LLDB_LOGF, lldb_private::Platform, lldb_private::platform_android::AdbClient::ResolveDeviceID(), and lldb_private::platform_android::AdbClient::SetPortForwarding().
Referenced by lldb_private::platform_android::PlatformAndroidRemoteGDBServer::MakeConnectURL().
Variable Documentation
g_remote_platform_pid
const lldb::pid_t g_remote_platform_pid static
Initial value:
=
    0
Definition at line 26 of file PlatformAndroidRemoteGDBServer.cpp.
Referenced by lldb_private::platform_android::PlatformAndroidRemoteGDBServer::ConnectRemote(), and lldb_private::platform_android::PlatformAndroidRemoteGDBServer::DisconnectRemote().