LLDB: PlatformDarwinDevice.cpp File Reference
PlatformDarwinDevice.cpp File Reference
#include "PlatformDarwinDevice.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleList.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Host/HostInfo.h"
#include "lldb/Target/DynamicLoader.h"
#include "lldb/Utility/FileSpec.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include <optional>
Functions
static lldb_private::Status MakeCacheFolderForFile (const FileSpec &module_cache_spec)
static lldb_private::Status BringInRemoteFile (Platform *platform, const lldb_private::ModuleSpec &module_spec, const FileSpec &module_cache_spec)
Function Documentation
BringInRemoteFile()
lldb_private::Status BringInRemoteFile (Platform * platform, const lldb_private::ModuleSpec & module_spec, const FileSpec & module_cache_spec) static
Definition at line 289 of file PlatformDarwinDevice.cpp.
References lldb_private::Platform::GetFile(), lldb_private::ModuleSpec::GetFileSpec(), and MakeCacheFolderForFile().
Referenced by lldb_private::PlatformDarwinDevice::GetSharedModuleWithLocalCache().
MakeCacheFolderForFile()
lldb_private::Status MakeCacheFolderForFile (const FileSpec & module_cache_spec) static
Definition at line 282 of file PlatformDarwinDevice.cpp.
References lldb_private::FileSpec::CopyByRemovingLastPathComponent(), and lldb_private::FileSpec::GetPath().
Referenced by BringInRemoteFile().