LLDB: PluginManager.cpp File Reference
PluginManager.cpp File Reference
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Host/FileSystem.h"
#include "lldb/Host/HostInfo.h"
#include "lldb/Interpreter/OptionValueProperties.h"
#include "lldb/Symbol/SaveCoreOptions.h"
#include "lldb/Target/Process.h"
#include "lldb/Utility/FileSpec.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/StringList.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/DynamicLibrary.h"
#include "llvm/Support/ErrorExtras.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <map>
#include <memory>
#include <mutex>
#include <string>
#include <utility>
#include <vector>
Classes
struct PluginInfo
struct PluginDir
struct PluginInstance< Callback >
class PluginInstances< Instance >
struct LanguageRuntimeInstance
struct ObjectFileInstance
struct ObjectContainerInstance
struct RegisterTypeBuilderInstance
struct ScriptInterpreterInstance
struct StructuredDataPluginInstance
struct SymbolLocatorInstance
struct TraceInstance
struct TraceExporterInstance
struct InstrumentationRuntimeInstance
struct TypeSystemInstance
struct ScriptedInterfaceInstance
struct REPLInstance
struct HighlighterInstance
Typedefs
typedef bool(* PluginInitCallback) ()
typedef void(* PluginTermCallback) ()
typedef llvm::SmallDenseMap< FileSpec, PluginInfo > DynamicPluginMap
typedef PluginInstance< ABICreateInstance > ABIInstance
typedef PluginInstances< ABIInstance > ABIInstances
typedef PluginInstance< ArchitectureCreateInstance > ArchitectureInstance
typedef PluginInstances< ArchitectureInstance > ArchitectureInstances
typedef PluginInstance< DisassemblerCreateInstance > DisassemblerInstance
typedef PluginInstances< DisassemblerInstance > DisassemblerInstances
typedef PluginInstance< DynamicLoaderCreateInstance > DynamicLoaderInstance
typedef PluginInstances< DynamicLoaderInstance > DynamicLoaderInstances
typedef PluginInstance< JITLoaderCreateInstance > JITLoaderInstance
typedef PluginInstances< JITLoaderInstance > JITLoaderInstances
typedef PluginInstance< EmulateInstructionCreateInstance > EmulateInstructionInstance
typedef PluginInstances< EmulateInstructionInstance > EmulateInstructionInstances
typedef PluginInstance< OperatingSystemCreateInstance > OperatingSystemInstance
typedef PluginInstances< OperatingSystemInstance > OperatingSystemInstances
typedef PluginInstance< LanguageCreateInstance > LanguageInstance
typedef PluginInstances< LanguageInstance > LanguageInstances
typedef PluginInstances< LanguageRuntimeInstance > LanguageRuntimeInstances
typedef PluginInstance< SystemRuntimeCreateInstance > SystemRuntimeInstance
typedef PluginInstances< SystemRuntimeInstance > SystemRuntimeInstances
typedef PluginInstances< ObjectFileInstance > ObjectFileInstances
typedef PluginInstances< ObjectContainerInstance > ObjectContainerInstances
typedef PluginInstance< PlatformCreateInstance > PlatformInstance
typedef PluginInstances< PlatformInstance > PlatformInstances
typedef PluginInstance< ProcessCreateInstance > ProcessInstance
typedef PluginInstances< ProcessInstance > ProcessInstances
typedef PluginInstance< ProtocolServerCreateInstance > ProtocolServerInstance
typedef PluginInstances< ProtocolServerInstance > ProtocolServerInstances
typedef PluginInstances< RegisterTypeBuilderInstance > RegisterTypeBuilderInstances
typedef PluginInstances< ScriptInterpreterInstance > ScriptInterpreterInstances
typedef PluginInstance< SyntheticFrameProviderCreateInstance > SyntheticFrameProviderInstance
typedef PluginInstance< ScriptedFrameProviderCreateInstance > ScriptedFrameProviderInstance
typedef PluginInstances< SyntheticFrameProviderInstance > SyntheticFrameProviderInstances
typedef PluginInstances< ScriptedFrameProviderInstance > ScriptedFrameProviderInstances
typedef PluginInstances< StructuredDataPluginInstance > StructuredDataPluginInstances
typedef PluginInstance< SymbolFileCreateInstance > SymbolFileInstance
typedef PluginInstances< SymbolFileInstance > SymbolFileInstances
typedef PluginInstance< SymbolVendorCreateInstance > SymbolVendorInstance
typedef PluginInstances< SymbolVendorInstance > SymbolVendorInstances
typedef PluginInstances< SymbolLocatorInstance > SymbolLocatorInstances
typedef PluginInstances< TraceInstance > TraceInstances
typedef PluginInstances< TraceExporterInstance > TraceExporterInstances
typedef PluginInstance< UnwindAssemblyCreateInstance > UnwindAssemblyInstance
typedef PluginInstances< UnwindAssemblyInstance > UnwindAssemblyInstances
typedef PluginInstance< MemoryHistoryCreateInstance > MemoryHistoryInstance
typedef PluginInstances< MemoryHistoryInstance > MemoryHistoryInstances
typedef PluginInstances< InstrumentationRuntimeInstance > InstrumentationRuntimeInstances
typedef PluginInstances< TypeSystemInstance > TypeSystemInstances
typedef PluginInstances< ScriptedInterfaceInstance > ScriptedInterfaceInstances
typedef PluginInstances< REPLInstance > REPLInstances
typedef PluginInstances< HighlighterInstance > HighlighterInstances
Functions
static std::recursive_mutex & GetPluginMapMutex ()
static DynamicPluginMap & GetPluginMap ()
static bool PluginIsLoaded (const FileSpec &plugin_file_spec)
static void SetPluginInfo (const FileSpec &plugin_file_spec, PluginInfo plugin_info)
template<typename FPtrTy>
static FPtrTy CastToFPtr (void *VPtr)
static FileSystem::EnumerateDirectoryResult LoadPluginCallback (void *baton, llvm::sys::fs::file_type ft, llvm::StringRef path)
static ABIInstances & GetABIInstances ()
static ArchitectureInstances & GetArchitectureInstances ()
static DisassemblerInstances & GetDisassemblerInstances ()
static DynamicLoaderInstances & GetDynamicLoaderInstances ()
static JITLoaderInstances & GetJITLoaderInstances ()
static EmulateInstructionInstances & GetEmulateInstructionInstances ()
static OperatingSystemInstances & GetOperatingSystemInstances ()
static LanguageInstances & GetLanguageInstances ()
static LanguageRuntimeInstances & GetLanguageRuntimeInstances ()
static SystemRuntimeInstances & GetSystemRuntimeInstances ()
static ObjectFileInstances & GetObjectFileInstances ()
static ObjectContainerInstances & GetObjectContainerInstances ()
static PlatformInstances & GetPlatformInstances ()
static ProcessInstances & GetProcessInstances ()
static ProtocolServerInstances & GetProtocolServerInstances ()
static RegisterTypeBuilderInstances & GetRegisterTypeBuilderInstances ()
static ScriptInterpreterInstances & GetScriptInterpreterInstances ()
static SyntheticFrameProviderInstances & GetSyntheticFrameProviderInstances ()
static ScriptedFrameProviderInstances & GetScriptedFrameProviderInstances ()
static StructuredDataPluginInstances & GetStructuredDataPluginInstances ()
static SymbolFileInstances & GetSymbolFileInstances ()
static SymbolVendorInstances & GetSymbolVendorInstances ()
static SymbolLocatorInstances & GetSymbolLocatorInstances ()
static TraceInstances & GetTracePluginInstances ()
static TraceExporterInstances & GetTraceExporterInstances ()
static UnwindAssemblyInstances & GetUnwindAssemblyInstances ()
static MemoryHistoryInstances & GetMemoryHistoryInstances ()
static InstrumentationRuntimeInstances & GetInstrumentationRuntimeInstances ()
static TypeSystemInstances & GetTypeSystemInstances ()
static ScriptedInterfaceInstances & GetScriptedInterfaceInstances ()
static REPLInstances & GetREPLInstances ()
static HighlighterInstances & GetHighlighterInstances ()
static lldb::OptionValuePropertiesSP GetDebuggerPropertyForPlugins (Debugger &debugger, llvm::StringRef plugin_type_name, llvm::StringRef plugin_type_desc, bool can_create)
static lldb::OptionValuePropertiesSP GetDebuggerPropertyForPluginsOldStyle (Debugger &debugger, llvm::StringRef plugin_type_name, llvm::StringRef plugin_type_desc, bool can_create)
static lldb::OptionValuePropertiesSP GetSettingForPlugin (Debugger &debugger, llvm::StringRef setting_name, llvm::StringRef plugin_type_name, GetDebuggerPropertyForPluginsPtr get_debugger_property=GetDebuggerPropertyForPlugins)
static bool CreateSettingForPlugin (Debugger &debugger, llvm::StringRef plugin_type_name, llvm::StringRef plugin_type_desc, const lldb::OptionValuePropertiesSP &properties_sp, llvm::StringRef description, bool is_global_property, GetDebuggerPropertyForPluginsPtr get_debugger_property=GetDebuggerPropertyForPlugins)
static constexpr llvm::StringLiteral kDynamicLoaderPluginName ("dynamic-loader")
static constexpr llvm::StringLiteral kPlatformPluginName ("platform")
static constexpr llvm::StringLiteral kProcessPluginName ("process")
static constexpr llvm::StringLiteral kTracePluginName ("trace")
static constexpr llvm::StringLiteral kObjectFilePluginName ("object-file")
static constexpr llvm::StringLiteral kSymbolFilePluginName ("symbol-file")
static constexpr llvm::StringLiteral kSymbolLocatorPluginName ("symbol-locator")
static constexpr llvm::StringLiteral kJITLoaderPluginName ("jit-loader")
static constexpr llvm::StringLiteral kStructuredDataPluginName ("structured-data")
static constexpr llvm::StringLiteral kCPlusPlusLanguagePlugin ("cplusplus")
static const char * kOperatingSystemPluginName ("os")
Variables
static constexpr llvm::StringLiteral g_plugin_prefix = "liblldbPlugin"
Typedef Documentation
ABIInstance
typedef PluginInstance<ABICreateInstance> ABIInstance
Definition at line 618 of file PluginManager.cpp.
ABIInstances
typedef PluginInstances<ABIInstance> ABIInstances
Definition at line 619 of file PluginManager.cpp.
ArchitectureInstance
typedef PluginInstance<ArchitectureCreateInstance> ArchitectureInstance
Definition at line 642 of file PluginManager.cpp.
ArchitectureInstances
typedef PluginInstances<ArchitectureInstance> ArchitectureInstances
Definition at line 643 of file PluginManager.cpp.
DisassemblerInstance
typedef PluginInstance<DisassemblerCreateInstance> DisassemblerInstance
Definition at line 673 of file PluginManager.cpp.
DisassemblerInstances
typedef PluginInstances<DisassemblerInstance> DisassemblerInstances
Definition at line 674 of file PluginManager.cpp.
DynamicLoaderInstance
typedef PluginInstance<DynamicLoaderCreateInstance> DynamicLoaderInstance
Definition at line 706 of file PluginManager.cpp.
DynamicLoaderInstances
typedef PluginInstances<DynamicLoaderInstance> DynamicLoaderInstances
Definition at line 707 of file PluginManager.cpp.
DynamicPluginMap
typedef llvm::SmallDenseMap<FileSpec, PluginInfo> DynamicPluginMap
Definition at line 68 of file PluginManager.cpp.
EmulateInstructionInstance
typedef PluginInstance<EmulateInstructionCreateInstance> EmulateInstructionInstance
Definition at line 768 of file PluginManager.cpp.
EmulateInstructionInstances
typedef PluginInstances<EmulateInstructionInstance> EmulateInstructionInstances
Definition at line 769 of file PluginManager.cpp.
HighlighterInstances
typedef PluginInstances<HighlighterInstance> HighlighterInstances
Definition at line 2082 of file PluginManager.cpp.
InstrumentationRuntimeInstances
typedef PluginInstances<InstrumentationRuntimeInstance> InstrumentationRuntimeInstances
Definition at line 1870 of file PluginManager.cpp.
JITLoaderInstance
typedef PluginInstance<JITLoaderCreateInstance> JITLoaderInstance
Definition at line 740 of file PluginManager.cpp.
JITLoaderInstances
typedef PluginInstances<JITLoaderInstance> JITLoaderInstances
Definition at line 741 of file PluginManager.cpp.
LanguageInstance
typedef PluginInstance<LanguageCreateInstance> LanguageInstance
Definition at line 835 of file PluginManager.cpp.
LanguageInstances
typedef PluginInstances<LanguageInstance> LanguageInstances
Definition at line 836 of file PluginManager.cpp.
LanguageRuntimeInstances
typedef PluginInstances<LanguageRuntimeInstance> LanguageRuntimeInstances
Definition at line 879 of file PluginManager.cpp.
MemoryHistoryInstance
typedef PluginInstance<MemoryHistoryCreateInstance> MemoryHistoryInstance
Definition at line 1829 of file PluginManager.cpp.
MemoryHistoryInstances
typedef PluginInstances<MemoryHistoryInstance> MemoryHistoryInstances
Definition at line 1830 of file PluginManager.cpp.
ObjectContainerInstances
typedef PluginInstances<ObjectContainerInstance> ObjectContainerInstances
Definition at line 1106 of file PluginManager.cpp.
ObjectFileInstances
typedef PluginInstances<ObjectFileInstance> ObjectFileInstances
Definition at line 967 of file PluginManager.cpp.
OperatingSystemInstance
typedef PluginInstance<OperatingSystemCreateInstance> OperatingSystemInstance
Definition at line 801 of file PluginManager.cpp.
OperatingSystemInstances
typedef PluginInstances<OperatingSystemInstance> OperatingSystemInstances
Definition at line 802 of file PluginManager.cpp.
PlatformInstance
typedef PluginInstance<PlatformCreateInstance> PlatformInstance
Definition at line 1150 of file PluginManager.cpp.
PlatformInstances
typedef PluginInstances<PlatformInstance> PlatformInstances
Definition at line 1151 of file PluginManager.cpp.
PluginInitCallback
typedef bool(* PluginInitCallback) ()
Definition at line 40 of file PluginManager.cpp.
PluginTermCallback
typedef void(* PluginTermCallback) ()
Definition at line 41 of file PluginManager.cpp.
ProcessInstance
typedef PluginInstance<ProcessCreateInstance> ProcessInstance
Definition at line 1199 of file PluginManager.cpp.
ProcessInstances
typedef PluginInstances<ProcessInstance> ProcessInstances
Definition at line 1200 of file PluginManager.cpp.
ProtocolServerInstance
typedef PluginInstance<ProtocolServerCreateInstance> ProtocolServerInstance
Definition at line 1248 of file PluginManager.cpp.
ProtocolServerInstances
typedef PluginInstances<ProtocolServerInstance> ProtocolServerInstances
Definition at line 1249 of file PluginManager.cpp.
RegisterTypeBuilderInstances
typedef PluginInstances<RegisterTypeBuilderInstance> RegisterTypeBuilderInstances
Definition at line 1289 of file PluginManager.cpp.
REPLInstances
typedef PluginInstances<REPLInstance> REPLInstances
Definition at line 2036 of file PluginManager.cpp.
ScriptedFrameProviderInstance
typedef PluginInstance<ScriptedFrameProviderCreateInstance> ScriptedFrameProviderInstance
Definition at line 1392 of file PluginManager.cpp.
ScriptedFrameProviderInstances
typedef PluginInstances<ScriptedFrameProviderInstance> ScriptedFrameProviderInstances
Definition at line 1396 of file PluginManager.cpp.
ScriptedInterfaceInstances
typedef PluginInstances<ScriptedInterfaceInstance> ScriptedInterfaceInstances
Definition at line 1978 of file PluginManager.cpp.
ScriptInterpreterInstances
typedef PluginInstances<ScriptInterpreterInstance> ScriptInterpreterInstances
Definition at line 1333 of file PluginManager.cpp.
StructuredDataPluginInstances
typedef PluginInstances<StructuredDataPluginInstance> StructuredDataPluginInstances
Definition at line 1459 of file PluginManager.cpp.
SymbolFileInstance
typedef PluginInstance<SymbolFileCreateInstance> SymbolFileInstance
Definition at line 1500 of file PluginManager.cpp.
SymbolFileInstances
typedef PluginInstances<SymbolFileInstance> SymbolFileInstances
Definition at line 1501 of file PluginManager.cpp.
SymbolLocatorInstances
typedef PluginInstances<SymbolLocatorInstance> SymbolLocatorInstances
Definition at line 1576 of file PluginManager.cpp.
SymbolVendorInstance
typedef PluginInstance<SymbolVendorCreateInstance> SymbolVendorInstance
Definition at line 1527 of file PluginManager.cpp.
SymbolVendorInstances
typedef PluginInstances<SymbolVendorInstance> SymbolVendorInstances
Definition at line 1528 of file PluginManager.cpp.
SyntheticFrameProviderInstance
typedef PluginInstance<SyntheticFrameProviderCreateInstance> SyntheticFrameProviderInstance
Definition at line 1390 of file PluginManager.cpp.
SyntheticFrameProviderInstances
typedef PluginInstances<SyntheticFrameProviderInstance> SyntheticFrameProviderInstances
Definition at line 1394 of file PluginManager.cpp.
SystemRuntimeInstance
typedef PluginInstance<SystemRuntimeCreateInstance> SystemRuntimeInstance
Definition at line 922 of file PluginManager.cpp.
SystemRuntimeInstances
typedef PluginInstances<SystemRuntimeInstance> SystemRuntimeInstances
Definition at line 923 of file PluginManager.cpp.
TraceExporterInstances
typedef PluginInstances<TraceExporterInstance> TraceExporterInstances
Definition at line 1762 of file PluginManager.cpp.
TraceInstances
typedef PluginInstances<TraceInstance> TraceInstances
Definition at line 1696 of file PluginManager.cpp.
TypeSystemInstances
typedef PluginInstances<TypeSystemInstance> TypeSystemInstances
Definition at line 1920 of file PluginManager.cpp.
UnwindAssemblyInstance
typedef PluginInstance<UnwindAssemblyCreateInstance> UnwindAssemblyInstance
Definition at line 1802 of file PluginManager.cpp.
UnwindAssemblyInstances
typedef PluginInstances<UnwindAssemblyInstance> UnwindAssemblyInstances
Definition at line 1803 of file PluginManager.cpp.
Function Documentation
CastToFPtr()
template<typename FPtrTy> FPtrTy CastToFPtr (void * VPtr) static
Definition at line 93 of file PluginManager.cpp.
Referenced by PluginInfo::Create().
CreateSettingForPlugin()
bool CreateSettingForPlugin (Debugger & debugger, llvm::StringRef plugin_type_name, llvm::StringRef plugin_type_desc, const lldb::OptionValuePropertiesSP & properties_sp, llvm::StringRef description, bool is_global_property, GetDebuggerPropertyForPluginsPtr get_debugger_property = GetDebuggerPropertyForPlugins) static
Definition at line 2224 of file PluginManager.cpp.
References GetDebuggerPropertyForPlugins().
Referenced by lldb_private::PluginManager::CreateSettingForCPlusPlusLanguagePlugin(), lldb_private::PluginManager::CreateSettingForDynamicLoaderPlugin(), lldb_private::PluginManager::CreateSettingForJITLoaderPlugin(), lldb_private::PluginManager::CreateSettingForObjectFilePlugin(), lldb_private::PluginManager::CreateSettingForPlatformPlugin(), lldb_private::PluginManager::CreateSettingForProcessPlugin(), lldb_private::PluginManager::CreateSettingForStructuredDataPlugin(), lldb_private::PluginManager::CreateSettingForSymbolFilePlugin(), lldb_private::PluginManager::CreateSettingForSymbolLocatorPlugin(), and lldb_private::PluginManager::CreateSettingForTracePlugin().
GetABIInstances()
ABIInstances & GetABIInstances () static
Definition at line 621 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::GetABICreateCallbackAtIndex(), lldb_private::PluginManager::GetABIPluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetABIPluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetArchitectureInstances()
ArchitectureInstances & GetArchitectureInstances () static
Definition at line 645 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::CreateArchitectureInstance(), lldb_private::PluginManager::GetArchitecturePluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetArchitecturePluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetDebuggerPropertyForPlugins()
lldb::OptionValuePropertiesSP GetDebuggerPropertyForPlugins (Debugger & debugger, llvm::StringRef plugin_type_name, llvm::StringRef plugin_type_desc, bool can_create) static
Definition at line 2126 of file PluginManager.cpp.
References lldb_private::Properties::GetValueProperties().
Referenced by lldb_private::PluginManager::CreateSettingForOperatingSystemPlugin(), CreateSettingForPlugin(), lldb_private::PluginManager::GetSettingForOperatingSystemPlugin(), and GetSettingForPlugin().
GetDebuggerPropertyForPluginsOldStyle()
lldb::OptionValuePropertiesSP GetDebuggerPropertyForPluginsOldStyle (Debugger & debugger, llvm::StringRef plugin_type_name, llvm::StringRef plugin_type_desc, bool can_create) static
Definition at line 2165 of file PluginManager.cpp.
References lldb_private::Properties::GetValueProperties().
Referenced by lldb_private::PluginManager::CreateSettingForPlatformPlugin(), and lldb_private::PluginManager::GetSettingForPlatformPlugin().
GetDisassemblerInstances()
DisassemblerInstances & GetDisassemblerInstances () static
Definition at line 676 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::GetDisassemblerCreateCallbackAtIndex(), lldb_private::PluginManager::GetDisassemblerCreateCallbackForPluginName(), lldb_private::PluginManager::GetDisassemblerPluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetDisassemblerPluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetDynamicLoaderInstances()
DynamicLoaderInstances & GetDynamicLoaderInstances () static
Definition at line 709 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::DebuggerInitialize(), lldb_private::PluginManager::GetDynamicLoaderCreateCallbackAtIndex(), lldb_private::PluginManager::GetDynamicLoaderCreateCallbackForPluginName(), lldb_private::PluginManager::GetDynamicLoaderPluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetDynamicLoaderPluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetEmulateInstructionInstances()
EmulateInstructionInstances & GetEmulateInstructionInstances () static
Definition at line 771 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::GetEmulateInstructionCreateCallbackAtIndex(), lldb_private::PluginManager::GetEmulateInstructionCreateCallbackForPluginName(), lldb_private::PluginManager::GetEmulateInstructionPluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetEmulateInstructionPluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetHighlighterInstances()
HighlighterInstances & GetHighlighterInstances () static
Definition at line 2084 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::GetHighlighterCreateCallbackAtIndex(), lldb_private::PluginManager::RegisterPlugin(), and lldb_private::PluginManager::UnregisterPlugin().
GetInstrumentationRuntimeInstances()
InstrumentationRuntimeInstances & GetInstrumentationRuntimeInstances () static
Definition at line 1872 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::GetInstrumentationRuntimeCreateCallbackAtIndex(), lldb_private::PluginManager::GetInstrumentationRuntimeGetTypeCallbackAtIndex(), lldb_private::PluginManager::GetInstrumentationRuntimePluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetInstrumentationRuntimePluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetJITLoaderInstances()
JITLoaderInstances & GetJITLoaderInstances () static
Definition at line 743 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::DebuggerInitialize(), lldb_private::PluginManager::GetJITLoaderCreateCallbackAtIndex(), lldb_private::PluginManager::GetJITLoaderPluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetJITLoaderPluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetLanguageInstances()
LanguageInstances & GetLanguageInstances () static
Definition at line 838 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::DebuggerInitialize(), lldb_private::PluginManager::GetLanguageCreateCallbackAtIndex(), lldb_private::PluginManager::GetLanguagePluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetLanguagePluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetLanguageRuntimeInstances()
LanguageRuntimeInstances & GetLanguageRuntimeInstances () static
Definition at line 881 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::GetLanguageRuntimeCreateCallbackAtIndex(), lldb_private::PluginManager::GetLanguageRuntimeGetCommandObjectAtIndex(), lldb_private::PluginManager::GetLanguageRuntimeGetExceptionPreconditionAtIndex(), lldb_private::PluginManager::GetLanguageRuntimePluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetLanguageRuntimePluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetMemoryHistoryInstances()
MemoryHistoryInstances & GetMemoryHistoryInstances () static
Definition at line 1832 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::GetMemoryHistoryCreateCallbackAtIndex(), lldb_private::PluginManager::GetMemoryHistoryPluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetMemoryHistoryPluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetObjectContainerInstances()
ObjectContainerInstances & GetObjectContainerInstances () static
Definition at line 1108 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::GetObjectContainerCreateCallbackAtIndex(), lldb_private::PluginManager::GetObjectContainerCreateMemoryCallbackAtIndex(), lldb_private::PluginManager::GetObjectContainerGetModuleSpecificationsCallbackAtIndex(), lldb_private::PluginManager::GetObjectContainerPluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetObjectContainerPluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetObjectFileInstances()
ObjectFileInstances & GetObjectFileInstances () static
Definition at line 969 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::DebuggerInitialize(), lldb_private::PluginManager::GetObjectFileCreateCallbackAtIndex(), lldb_private::PluginManager::GetObjectFileCreateMemoryCallbackAtIndex(), lldb_private::PluginManager::GetObjectFileCreateMemoryCallbackForPluginName(), lldb_private::PluginManager::GetObjectFileGetModuleSpecificationsCallbackAtIndex(), lldb_private::PluginManager::GetObjectFilePluginInfo(), lldb_private::PluginManager::GetSaveCorePluginNames(), lldb_private::PluginManager::IsRegisteredObjectFilePluginName(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SaveCore(), lldb_private::PluginManager::SetObjectFilePluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetOperatingSystemInstances()
OperatingSystemInstances & GetOperatingSystemInstances () static
Definition at line 804 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::DebuggerInitialize(), lldb_private::PluginManager::GetOperatingSystemCreateCallbackAtIndex(), lldb_private::PluginManager::GetOperatingSystemCreateCallbackForPluginName(), lldb_private::PluginManager::GetOperatingSystemPluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetOperatingSystemPluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetPlatformInstances()
PlatformInstances & GetPlatformInstances () static
Definition at line 1153 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::AutoCompletePlatformName(), lldb_private::PluginManager::DebuggerInitialize(), lldb_private::PluginManager::GetPlatformCreateCallbackAtIndex(), lldb_private::PluginManager::GetPlatformCreateCallbackForPluginName(), lldb_private::PluginManager::GetPlatformPluginDescriptionAtIndex(), lldb_private::PluginManager::GetPlatformPluginInfo(), lldb_private::PluginManager::GetPlatformPluginNameAtIndex(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetPlatformPluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetPluginMap()
DynamicPluginMap & GetPluginMap () static
Definition at line 75 of file PluginManager.cpp.
Referenced by PluginIsLoaded(), SetPluginInfo(), and lldb_private::PluginManager::Terminate().
GetPluginMapMutex()
std::recursive_mutex & GetPluginMapMutex () static
Definition at line 70 of file PluginManager.cpp.
Referenced by PluginIsLoaded(), SetPluginInfo(), and lldb_private::PluginManager::Terminate().
GetProcessInstances()
ProcessInstances & GetProcessInstances () static
Definition at line 1202 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::AutoCompleteProcessName(), lldb_private::PluginManager::DebuggerInitialize(), lldb_private::PluginManager::GetProcessCreateCallbackAtIndex(), lldb_private::PluginManager::GetProcessCreateCallbackForPluginName(), lldb_private::PluginManager::GetProcessPluginDescriptionAtIndex(), lldb_private::PluginManager::GetProcessPluginInfo(), lldb_private::PluginManager::GetProcessPluginNameAtIndex(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetProcessPluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetProtocolServerInstances()
ProtocolServerInstances & GetProtocolServerInstances () static
Definition at line 1251 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::GetProtocolCreateCallbackForPluginName(), lldb_private::PluginManager::GetProtocolServerPluginNameAtIndex(), lldb_private::PluginManager::RegisterPlugin(), and lldb_private::PluginManager::UnregisterPlugin().
GetRegisterTypeBuilderInstances()
RegisterTypeBuilderInstances & GetRegisterTypeBuilderInstances () static
Definition at line 1291 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::GetRegisterTypeBuilder(), lldb_private::PluginManager::GetRegisterTypeBuilderPluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetRegisterTypeBuilderPluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetREPLInstances()
REPLInstances & GetREPLInstances () static
Definition at line 2038 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::GetREPLAllTypeSystemSupportedLanguages(), lldb_private::PluginManager::GetREPLCreateCallbackAtIndex(), lldb_private::PluginManager::GetREPLPluginInfo(), lldb_private::PluginManager::GetREPLSupportedLanguagesAtIndex(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetREPLPluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetScriptedFrameProviderInstances()
ScriptedFrameProviderInstances & GetScriptedFrameProviderInstances () static
Definition at line 1403 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::GetScriptedFrameProviderCreateCallbackAtIndex(), lldb_private::PluginManager::RegisterPlugin(), and lldb_private::PluginManager::UnregisterPlugin().
GetScriptedInterfaceInstances()
ScriptedInterfaceInstances & GetScriptedInterfaceInstances () static
Definition at line 1980 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::DebuggerInitialize(), lldb_private::PluginManager::GetNumScriptedInterfaces(), lldb_private::PluginManager::GetScriptedInterfaceDescriptionAtIndex(), lldb_private::PluginManager::GetScriptedInterfaceLanguageAtIndex(), lldb_private::PluginManager::GetScriptedInterfaceNameAtIndex(), lldb_private::PluginManager::GetScriptedInterfacePluginInfo(), lldb_private::PluginManager::GetScriptedInterfaceUsagesAtIndex(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetScriptedInterfacePluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetScriptInterpreterInstances()
ScriptInterpreterInstances & GetScriptInterpreterInstances () static
Definition at line 1335 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::GetScriptInterpreterCreateCallbackAtIndex(), lldb_private::PluginManager::GetScriptInterpreterForLanguage(), lldb_private::PluginManager::GetScriptInterpreterLibraryPath(), lldb_private::PluginManager::GetScriptInterpreterPluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetScriptInterpreterPluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetSettingForPlugin()
lldb::OptionValuePropertiesSP GetSettingForPlugin (Debugger & debugger, llvm::StringRef setting_name, llvm::StringRef plugin_type_name, GetDebuggerPropertyForPluginsPtr get_debugger_property = GetDebuggerPropertyForPlugins) static
Definition at line 2208 of file PluginManager.cpp.
References GetDebuggerPropertyForPlugins().
Referenced by lldb_private::PluginManager::GetSettingForCPlusPlusLanguagePlugin(), lldb_private::PluginManager::GetSettingForDynamicLoaderPlugin(), lldb_private::PluginManager::GetSettingForJITLoaderPlugin(), lldb_private::PluginManager::GetSettingForObjectFilePlugin(), lldb_private::PluginManager::GetSettingForPlatformPlugin(), lldb_private::PluginManager::GetSettingForProcessPlugin(), lldb_private::PluginManager::GetSettingForStructuredDataPlugin(), lldb_private::PluginManager::GetSettingForSymbolFilePlugin(), and lldb_private::PluginManager::GetSettingForSymbolLocatorPlugin().
GetStructuredDataPluginInstances()
StructuredDataPluginInstances & GetStructuredDataPluginInstances () static
Definition at line 1461 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::DebuggerInitialize(), lldb_private::PluginManager::GetStructuredDataFilterCallbackAtIndex(), lldb_private::PluginManager::GetStructuredDataPluginCreateCallbackAtIndex(), lldb_private::PluginManager::GetStructuredDataPluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetStructuredDataPluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetSymbolFileInstances()
SymbolFileInstances & GetSymbolFileInstances () static
Definition at line 1503 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::DebuggerInitialize(), lldb_private::PluginManager::GetSymbolFileCreateCallbackAtIndex(), lldb_private::PluginManager::GetSymbolFilePluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetSymbolFilePluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetSymbolLocatorInstances()
SymbolLocatorInstances & GetSymbolLocatorInstances () static
Definition at line 1578 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::DebuggerInitialize(), lldb_private::PluginManager::DownloadObjectAndSymbolFile(), lldb_private::PluginManager::FindSymbolFileInBundle(), lldb_private::PluginManager::GetSymbolLocatorCreateCallbackAtIndex(), lldb_private::PluginManager::GetSymbolLocatorPluginInfo(), lldb_private::PluginManager::LocateExecutableObjectFile(), lldb_private::PluginManager::LocateExecutableSymbolFile(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetSymbolLocatorPluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetSymbolVendorInstances()
SymbolVendorInstances & GetSymbolVendorInstances () static
Definition at line 1530 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::GetSymbolVendorCreateCallbackAtIndex(), lldb_private::PluginManager::GetSymbolVendorPluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetSymbolVendorPluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetSyntheticFrameProviderInstances()
SyntheticFrameProviderInstances & GetSyntheticFrameProviderInstances () static
Definition at line 1398 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::GetSyntheticFrameProviderCreateCallbackForPluginName(), lldb_private::PluginManager::RegisterPlugin(), and lldb_private::PluginManager::UnregisterPlugin().
GetSystemRuntimeInstances()
SystemRuntimeInstances & GetSystemRuntimeInstances () static
Definition at line 925 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::GetSystemRuntimeCreateCallbackAtIndex(), lldb_private::PluginManager::GetSystemRuntimePluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetSystemRuntimePluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetTraceExporterInstances()
TraceExporterInstances & GetTraceExporterInstances () static
Definition at line 1764 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::GetThreadTraceExportCommandCreatorAtIndex(), lldb_private::PluginManager::GetTraceExporterCreateCallback(), lldb_private::PluginManager::GetTraceExporterPluginInfo(), lldb_private::PluginManager::GetTraceExporterPluginNameAtIndex(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetTraceExporterPluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetTracePluginInstances()
TraceInstances & GetTracePluginInstances () static
Definition at line 1698 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::DebuggerInitialize(), lldb_private::PluginManager::GetTraceCreateCallback(), lldb_private::PluginManager::GetTraceCreateCallbackForLiveProcess(), lldb_private::PluginManager::GetTracePluginInfo(), lldb_private::PluginManager::GetTraceSchema(), lldb_private::PluginManager::GetTraceSchema(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetTracePluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetTypeSystemInstances()
TypeSystemInstances & GetTypeSystemInstances () static
Definition at line 1922 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::GetAllTypeSystemSupportedLanguagesForExpressions(), lldb_private::PluginManager::GetAllTypeSystemSupportedLanguagesForTypes(), lldb_private::PluginManager::GetTypeSystemCreateCallbackAtIndex(), lldb_private::PluginManager::GetTypeSystemPluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetTypeSystemPluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
GetUnwindAssemblyInstances()
UnwindAssemblyInstances & GetUnwindAssemblyInstances () static
Definition at line 1805 of file PluginManager.cpp.
Referenced by lldb_private::PluginManager::GetUnwindAssemblyCreateCallbackAtIndex(), lldb_private::PluginManager::GetUnwindAssemblyPluginInfo(), lldb_private::PluginManager::RegisterPlugin(), lldb_private::PluginManager::SetUnwindAssemblyPluginEnabled(), and lldb_private::PluginManager::UnregisterPlugin().
kCPlusPlusLanguagePlugin()
constexpr llvm::StringLiteral kCPlusPlusLanguagePlugin ("cplusplus") static constexpr
Referenced by lldb_private::PluginManager::CreateSettingForCPlusPlusLanguagePlugin(), and lldb_private::PluginManager::GetSettingForCPlusPlusLanguagePlugin().
kDynamicLoaderPluginName()
constexpr llvm::StringLiteral kDynamicLoaderPluginName ("dynamic-loader") static constexpr
Referenced by lldb_private::PluginManager::CreateSettingForDynamicLoaderPlugin(), and lldb_private::PluginManager::GetSettingForDynamicLoaderPlugin().
kJITLoaderPluginName()
constexpr llvm::StringLiteral kJITLoaderPluginName ("jit-loader") static constexpr
Referenced by lldb_private::PluginManager::CreateSettingForJITLoaderPlugin(), and lldb_private::PluginManager::GetSettingForJITLoaderPlugin().
kObjectFilePluginName()
constexpr llvm::StringLiteral kObjectFilePluginName ("object-file") static constexpr
Referenced by lldb_private::PluginManager::CreateSettingForObjectFilePlugin(), and lldb_private::PluginManager::GetSettingForObjectFilePlugin().
kOperatingSystemPluginName()
const char * kOperatingSystemPluginName ("os") static
Referenced by lldb_private::PluginManager::CreateSettingForOperatingSystemPlugin(), and lldb_private::PluginManager::GetSettingForOperatingSystemPlugin().
kPlatformPluginName()
constexpr llvm::StringLiteral kPlatformPluginName ("platform") static constexpr
Referenced by lldb_private::PluginManager::CreateSettingForPlatformPlugin(), and lldb_private::PluginManager::GetSettingForPlatformPlugin().
kProcessPluginName()
constexpr llvm::StringLiteral kProcessPluginName ("process") static constexpr
Referenced by lldb_private::PluginManager::CreateSettingForProcessPlugin(), and lldb_private::PluginManager::GetSettingForProcessPlugin().
kStructuredDataPluginName()
constexpr llvm::StringLiteral kStructuredDataPluginName ("structured-data") static constexpr
Referenced by lldb_private::PluginManager::CreateSettingForStructuredDataPlugin(), and lldb_private::PluginManager::GetSettingForStructuredDataPlugin().
kSymbolFilePluginName()
constexpr llvm::StringLiteral kSymbolFilePluginName ("symbol-file") static constexpr
Referenced by lldb_private::PluginManager::CreateSettingForSymbolFilePlugin(), and lldb_private::PluginManager::GetSettingForSymbolFilePlugin().
kSymbolLocatorPluginName()
constexpr llvm::StringLiteral kSymbolLocatorPluginName ("symbol-locator") static constexpr
Referenced by lldb_private::PluginManager::CreateSettingForSymbolLocatorPlugin(), and lldb_private::PluginManager::GetSettingForSymbolLocatorPlugin().
kTracePluginName()
constexpr llvm::StringLiteral kTracePluginName ("trace") static constexpr
Referenced by lldb_private::PluginManager::CreateSettingForTracePlugin().
LoadPluginCallback()
FileSystem::EnumerateDirectoryResult LoadPluginCallback (void * baton, llvm::sys::fs::file_type ft, llvm::StringRef path) static
Definition at line 167 of file PluginManager.cpp.
References PluginInfo::Create(), lldb_private::FileSystem::eEnumerateDirectoryResultEnter, lldb_private::FileSystem::eEnumerateDirectoryResultNext, g_plugin_prefix, lldb_private::FileSpec::GetFilename(), lldb_private::FileSpec::GetFileNameExtension(), lldb_private::GetLog(), lldb_private::ConstString::GetStringRef(), lldb_private::Host, lldb_private::FileSystem::Instance(), LLDB_LOG_ERROR, PluginDir::LoadOnlyWithLLDBPrefix, PluginIsLoaded(), lldb_private::FileSystem::Resolve(), and SetPluginInfo().
PluginIsLoaded()
bool PluginIsLoaded (const FileSpec & plugin_file_spec) static
Definition at line 80 of file PluginManager.cpp.
References GetPluginMap(), and GetPluginMapMutex().
Referenced by LoadPluginCallback().
SetPluginInfo()
void SetPluginInfo (const FileSpec & plugin_file_spec, PluginInfo plugin_info) static
Definition at line 85 of file PluginManager.cpp.
References GetPluginMap(), and GetPluginMapMutex().
Referenced by LoadPluginCallback().
Variable Documentation
g_plugin_prefix
llvm::StringLiteral g_plugin_prefix = "liblldbPlugin" static constexpr
Definition at line 97 of file PluginManager.cpp.
Referenced by PluginInfo::Create(), and LoadPluginCallback().