LLDB: PosixSpawnResponsible.h File Reference
PosixSpawnResponsible.h File Reference
#include <spawn.h>
#include <dispatch/dispatch.h>
#include <dlfcn.h>
Functions
errno_t responsibility_spawnattrs_setdisclaim (posix_spawnattr_t *attrs, bool disclaim)
static int setup_posix_spawn_responsible_flag (posix_spawnattr_t *attr)
Function Documentation
responsibility_spawnattrs_setdisclaim()
errno_t responsibility_spawnattrs_setdisclaim (posix_spawnattr_t * attrs, bool disclaim)
Referenced by setup_posix_spawn_responsible_flag().
setup_posix_spawn_responsible_flag()
int setup_posix_spawn_responsible_flag (posix_spawnattr_t * attr) inline static
Definition at line 20 of file PosixSpawnResponsible.h.
References responsibility_spawnattrs_setdisclaim().
Referenced by LaunchProcessPosixSpawn().