LLDB: ProcessLauncherPosixFork.cpp File Reference
ProcessLauncherPosixFork.cpp File Reference
#include "lldb/Host/posix/ProcessLauncherPosixFork.h"
#include "lldb/Host/FileSystem.h"
#include "lldb/Host/Host.h"
#include "lldb/Host/HostProcess.h"
#include "lldb/Host/Pipe.h"
#include "lldb/Host/ProcessLaunchInfo.h"
#include "lldb/Utility/FileSpec.h"
#include "lldb/Utility/Log.h"
#include "llvm/Support/Errno.h"
#include <climits>
#include <fcntl.h>
#include <sys/ptrace.h>
#include <sys/wait.h>
#include <unistd.h>
#include <csignal>
#include <sstream>
Functions
static void write_string (int error_fd, const char *str)
static void ExitWithError (int error_fd, const char *operation)
static void DisableASLR (int error_fd)
static void DupDescriptor (int error_fd, const char *file, int fd, int flags)
static void ChildFunc (int error_fd, const ForkLaunchInfo &info)
static std::vector< ForkFileAction > MakeForkActions (const ProcessLaunchInfo &info)
Function Documentation
ChildFunc()
void ChildFunc (int error_fd, const ForkLaunchInfo & info) static
Definition at line 113 of file ProcessLauncherPosixFork.cpp.
References DisableASLR(), DupDescriptor(), lldb_private::FileAction::eFileActionClose, lldb_private::FileAction::eFileActionDuplicate, lldb_private::FileAction::eFileActionNone, lldb_private::FileAction::eFileActionOpen, and ExitWithError().
Referenced by lldb_private::ProcessLauncherPosixFork::LaunchProcess().
DisableASLR()
void DisableASLR (int error_fd) static
Definition at line 53 of file ProcessLauncherPosixFork.cpp.
References ExitWithError().
Referenced by ChildFunc().
DupDescriptor()
void DupDescriptor (int error_fd, const char * file, int fd, int flags) static
Definition at line 66 of file ProcessLauncherPosixFork.cpp.
References ExitWithError(), lldb_private::FileSystem::Instance(), and lldb_private::FileSystem::Open().
Referenced by ChildFunc().
ExitWithError()
void ExitWithError (int error_fd, const char * operation) static
Definition at line 44 of file ProcessLauncherPosixFork.cpp.
References write_string().
Referenced by ChildFunc(), DisableASLR(), and DupDescriptor().
MakeForkActions()
std::vector< ForkFileAction > MakeForkActions (const ProcessLaunchInfo & info) static
Definition at line 236 of file ProcessLauncherPosixFork.cpp.
References lldb_private::ProcessLaunchInfo::GetFileActionAtIndex(), and lldb_private::ProcessLaunchInfo::GetNumFileActions().
write_string()
void write_string (int error_fd, const char * str) static
Definition at line 39 of file ProcessLauncherPosixFork.cpp.
Referenced by ExitWithError().