LLDB: ProcessGDBRemoteLog.cpp File Reference
ProcessGDBRemoteLog.cpp File Reference
#include "ProcessGDBRemoteLog.h"
#include "ProcessGDBRemote.h"
#include "llvm/Support/Threading.h"
Variables
static constexpr Log::Category g_categories []
static Log::Channel g_channel (g_categories, GDBRLog::Packets)
Variable Documentation
g_categories
Log::Category g_categories[] static constexpr
Initial value:
= {
    {{"async"}, {"log asynchronous activity"}, GDBRLog::Async},
    {{"break"}, {"log breakpoints"}, GDBRLog::Breakpoints},
    {{"comm"}, {"log communication activity"}, GDBRLog::Comm},
    {{"packets"}, {"log gdb remote packets"}, GDBRLog::Packets},
    {{"memory"}, {"log memory reads and writes"}, GDBRLog::Memory},
    {{"data-short"},
     {"log memory bytes for memory reads and writes for short transactions "
      "only"},
     GDBRLog::MemoryDataShort},
    {{"data-long"},
     {"log memory bytes for memory reads and writes for all transactions"},
     GDBRLog::MemoryDataLong},
    {{"process"}, {"log process events and activities"}, GDBRLog::Process},
    {{"step"}, {"log step related activities"}, GDBRLog::Step},
    {{"thread"}, {"log thread events and activities"}, GDBRLog::Thread},
    {{"watch"}, {"log watchpoint related activities"}, GDBRLog::Watchpoints},
}
Definition at line 17 of file ProcessGDBRemoteLog.cpp.
g_channel
Log::Channel g_channel(g_categories, GDBRLog::Packets) (g_categories , GDBRLog::Packets) static
Referenced by lldb_private::LogChannelDWARF::Initialize(), lldb_private::process_gdb_remote::ProcessGDBRemoteLog::Initialize(), lldb_private::ProcessKDPLog::Initialize(), lldb_private::ProcessPOSIXLog::Initialize(), lldb_private::ProcessWindowsLog::Initialize(), lldb_private::LogChannelFor< DWARFLog >(), lldb_private::LogChannelFor< KDPLog >(), lldb_private::LogChannelFor< POSIXLog >(), and lldb_private::LogChannelFor< WindowsLog >().