LLDB: ProcessElfCore.cpp File Reference
ProcessElfCore.cpp File Reference
#include <cstdlib>
#include <memory>
#include <mutex>
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Section.h"
#include "lldb/Target/ABI.h"
#include "lldb/Target/DynamicLoader.h"
#include "lldb/Target/MemoryRegionInfo.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/UnixSignals.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/State.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/Support/Threading.h"
#include "Plugins/DynamicLoader/POSIX-DYLD/DynamicLoaderPOSIXDYLD.h"
#include "Plugins/ObjectFile/ELF/ObjectFileELF.h"
#include "Plugins/Process/elf-core/RegisterUtilities.h"
#include "ProcessElfCore.h"
#include "ThreadElfCore.h"
Functions
static void ParseFreeBSDPrStatus (ThreadData &thread_data, const DataExtractor &data, bool lp64)
static void ParseFreeBSDPrPsInfo (ProcessElfCore &process, const DataExtractor &data, bool lp64)
static llvm::Error ParseNetBSDProcInfo (const DataExtractor &data, uint32_t &cpi_nlwps, uint32_t &cpi_signo, uint32_t &cpi_siglwp, uint32_t &cpi_pid)
static void ParseOpenBSDProcInfo (ThreadData &thread_data, const DataExtractor &data)
Function Documentation
ParseFreeBSDPrPsInfo()
void ParseFreeBSDPrPsInfo (ProcessElfCore & process, const DataExtractor & data, bool lp64) static
Definition at line 577 of file ProcessElfCore.cpp.
References lldb_private::GetLog(), lldb_private::DataExtractor::GetU32(), LLDB_LOGF, lldb_private::Process, and lldb_private::Process::SetID().
Referenced by ProcessElfCore::parseFreeBSDNotes().
ParseFreeBSDPrStatus()
void ParseFreeBSDPrStatus (ThreadData & thread_data, const DataExtractor & data, bool lp64) static
Definition at line 549 of file ProcessElfCore.cpp.
References lldb_private::DataExtractor::GetByteSize(), lldb_private::GetLog(), lldb_private::DataExtractor::GetU32(), ThreadData::gpregset, LLDB_LOGF, lldb_private::Process, ThreadData::signo, and ThreadData::tid.
Referenced by ProcessElfCore::parseFreeBSDNotes().
ParseNetBSDProcInfo()
llvm::Error ParseNetBSDProcInfo (const DataExtractor & data, uint32_t & cpi_nlwps, uint32_t & cpi_signo, uint32_t & cpi_siglwp, uint32_t & cpi_pid) static
Definition at line 597 of file ProcessElfCore.cpp.
References lldb_private::DataExtractor::GetU32(), lldb_private::NETBSD::NT_PROCINFO_CPI_EGID_SIZE, lldb_private::NETBSD::NT_PROCINFO_CPI_EUID_SIZE, lldb_private::NETBSD::NT_PROCINFO_CPI_NAME_SIZE, lldb_private::NETBSD::NT_PROCINFO_CPI_PGRP_SIZE, lldb_private::NETBSD::NT_PROCINFO_CPI_PPID_SIZE, lldb_private::NETBSD::NT_PROCINFO_CPI_RGID_SIZE, lldb_private::NETBSD::NT_PROCINFO_CPI_RUID_SIZE, lldb_private::NETBSD::NT_PROCINFO_CPI_SID_SIZE, lldb_private::NETBSD::NT_PROCINFO_CPI_SIGCATCH_SIZE, lldb_private::NETBSD::NT_PROCINFO_CPI_SIGCODE_SIZE, lldb_private::NETBSD::NT_PROCINFO_CPI_SIGIGNORE_SIZE, lldb_private::NETBSD::NT_PROCINFO_CPI_SIGMASK_SIZE, lldb_private::NETBSD::NT_PROCINFO_CPI_SIGPEND_SIZE, lldb_private::NETBSD::NT_PROCINFO_CPI_SVGID_SIZE, lldb_private::NETBSD::NT_PROCINFO_CPI_SVUID_SIZE, and lldb_private::NETBSD::NT_PROCINFO_SIZE.
Referenced by ProcessElfCore::parseNetBSDNotes().
ParseOpenBSDProcInfo()
void ParseOpenBSDProcInfo (ThreadData & thread_data, const DataExtractor & data) static
Definition at line 641 of file ProcessElfCore.cpp.
References lldb_private::DataExtractor::GetU32(), and ThreadData::signo.
Referenced by ProcessElfCore::parseOpenBSDNotes().