LLDB: ProcessDebugger.cpp File Reference
ProcessDebugger.cpp File Reference
#include "ProcessDebugger.h"
#include "lldb/Host/windows/windows.h"
#include <psapi.h>
#include "lldb/Host/FileSystem.h"
#include "lldb/Host/HostNativeProcessBase.h"
#include "lldb/Host/HostProcess.h"
#include "lldb/Host/HostThread.h"
#include "lldb/Host/ProcessLaunchInfo.h"
#include "lldb/Target/MemoryRegionInfo.h"
#include "lldb/Target/Process.h"
#include "llvm/Support/ConvertUTF.h"
#include "llvm/Support/Error.h"
#include "DebuggerThread.h"
#include "ExceptionRecord.h"
#include "ProcessWindowsLog.h"
Namespaces
namespace lldb_private
A class that represents a running process on the host machine.
Functions
static DWORD ConvertLldbToWinApiProtect (uint32_t protect)
static bool IsPageReadable (uint32_t protect)
static bool IsPageWritable (uint32_t protect)
static bool IsPageExecutable (uint32_t protect)
Function Documentation
ConvertLldbToWinApiProtect()
DWORD ConvertLldbToWinApiProtect (uint32_t protect) static
Definition at line 32 of file ProcessDebugger.cpp.
Referenced by lldb_private::ProcessDebugger::AllocateMemory().
IsPageExecutable()
bool IsPageExecutable (uint32_t protect) static
Definition at line 59 of file ProcessDebugger.cpp.
Referenced by lldb_private::ProcessDebugger::GetMemoryRegionInfo().
IsPageReadable()
bool IsPageReadable (uint32_t protect) static
Definition at line 50 of file ProcessDebugger.cpp.
Referenced by lldb_private::ProcessDebugger::GetMemoryRegionInfo().
IsPageWritable()
bool IsPageWritable (uint32_t protect) static
Definition at line 54 of file ProcessDebugger.cpp.
Referenced by lldb_private::ProcessDebugger::GetMemoryRegionInfo().