LLDB: Process.cpp File Reference
Process.cpp File Reference
#include <atomic>
#include <memory>
#include <mutex>
#include <optional>
#include "llvm/ADT/ScopeExit.h"
#include "llvm/Support/ScopedPrinter.h"
#include "llvm/Support/Threading.h"
#include "lldb/Breakpoint/BreakpointLocation.h"
#include "lldb/Breakpoint/StoppointCallbackContext.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Progress.h"
#include "lldb/Core/Telemetry.h"
#include "lldb/Expression/DiagnosticManager.h"
#include "lldb/Expression/DynamicCheckerFunctions.h"
#include "lldb/Expression/UserExpression.h"
#include "lldb/Expression/UtilityFunction.h"
#include "lldb/Host/ConnectionFileDescriptor.h"
#include "lldb/Host/FileSystem.h"
#include "lldb/Host/Host.h"
#include "lldb/Host/HostInfo.h"
#include "lldb/Host/OptionParser.h"
#include "lldb/Host/Pipe.h"
#include "lldb/Host/Terminal.h"
#include "lldb/Host/ThreadLauncher.h"
#include "lldb/Interpreter/CommandInterpreter.h"
#include "lldb/Interpreter/OptionArgParser.h"
#include "lldb/Interpreter/OptionValueProperties.h"
#include "lldb/Symbol/Function.h"
#include "lldb/Symbol/Symbol.h"
#include "lldb/Target/ABI.h"
#include "lldb/Target/AssertFrameRecognizer.h"
#include "lldb/Target/DynamicLoader.h"
#include "lldb/Target/InstrumentationRuntime.h"
#include "lldb/Target/JITLoader.h"
#include "lldb/Target/JITLoaderList.h"
#include "lldb/Target/Language.h"
#include "lldb/Target/LanguageRuntime.h"
#include "lldb/Target/MemoryHistory.h"
#include "lldb/Target/MemoryRegionInfo.h"
#include "lldb/Target/OperatingSystem.h"
#include "lldb/Target/Platform.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/StopInfo.h"
#include "lldb/Target/StructuredDataPlugin.h"
#include "lldb/Target/SystemRuntime.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/TargetList.h"
#include "lldb/Target/Thread.h"
#include "lldb/Target/ThreadPlan.h"
#include "lldb/Target/ThreadPlanBase.h"
#include "lldb/Target/ThreadPlanCallFunction.h"
#include "lldb/Target/ThreadPlanStack.h"
#include "lldb/Target/UnixSignals.h"
#include "lldb/Utility/AddressableBits.h"
#include "lldb/Utility/Event.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/NameMatches.h"
#include "lldb/Utility/ProcessInfo.h"
#include "lldb/Utility/SelectHelper.h"
#include "lldb/Utility/State.h"
#include "lldb/Utility/Timer.h"
#include "TargetProperties.inc"
#include "TargetPropertiesEnum.inc"
Classes
class ProcessOptionValueProperties
class ProcessExperimentalOptionValueProperties
class IOHandlerProcessSTDIO
Macros
#define LLDB_PROPERTIES_process
#define LLDB_PROPERTIES_process
#define LLDB_PROPERTIES_process_experimental
#define LLDB_PROPERTIES_process_experimental
Enumerations
enum { ePropertyExperimental }
enum
Functions
static microseconds GetOneThreadExpressionTimeout (const EvaluateExpressionOptions &options)
static Timeout< std::micro > GetExpressionTimeout (const EvaluateExpressionOptions &options, bool before_first_timeout)
static std::optional< ExpressionResults > HandleStoppedEvent (lldb::tid_t thread_id, const ThreadPlanSP &thread_plan_sp, RestorePlanState &restorer, const EventSP &event_sp, EventSP &event_to_broadcast_sp, const EvaluateExpressionOptions &options, bool handle_interrupts)
static CoreFileMemoryRange CreateCoreFileMemoryRange (const lldb_private::MemoryRegionInfo &region)
static bool AddDirtyPages (const lldb_private::MemoryRegionInfo &region, CoreFileMemoryRanges &ranges)
static void AddRegion (const lldb_private::MemoryRegionInfo &region, bool try_dirty_pages, CoreFileMemoryRanges &ranges)
static void SaveDynamicLoaderSections (Process &process, const SaveCoreOptions &options, CoreFileMemoryRanges &ranges, std::set< addr_t > &stack_ends)
static void SaveOffRegionsWithStackPointers (Process &process, const SaveCoreOptions &core_options, const MemoryRegionInfos &regions, CoreFileMemoryRanges &ranges, std::set< addr_t > &stack_ends)
static void GetCoreFileSaveRangesFull (Process &process, const MemoryRegionInfos &regions, CoreFileMemoryRanges &ranges, std::set< addr_t > &stack_ends)
static void GetCoreFileSaveRangesDirtyOnly (Process &process, const MemoryRegionInfos &regions, CoreFileMemoryRanges &ranges, std::set< addr_t > &stack_ends)
static void GetCoreFileSaveRangesStackOnly (Process &process, const MemoryRegionInfos &regions, CoreFileMemoryRanges &ranges, std::set< addr_t > &stack_ends)
static lldb_private::MemoryRegionInfo Intersect (const lldb_private::MemoryRegionInfo &lhs, const lldb_private::MemoryRegionInfo::RangeType &rhs)
static void GetUserSpecifiedCoreFileSaveRanges (Process &process, const MemoryRegionInfos &regions, const SaveCoreOptions &options, CoreFileMemoryRanges &ranges)
Variables
static constexpr OptionEnumValueElement g_follow_fork_mode_values []
static constexpr unsigned g_string_read_width = 256
Macro Definition Documentation
LLDB_PROPERTIES_process [1/2]
#define LLDB_PROPERTIES_process
Definition at line 122 of file Process.cpp.
LLDB_PROPERTIES_process [2/2]
#define LLDB_PROPERTIES_process
Definition at line 122 of file Process.cpp.
LLDB_PROPERTIES_process_experimental [1/2]
#define LLDB_PROPERTIES_process_experimental
Definition at line 131 of file Process.cpp.
LLDB_PROPERTIES_process_experimental [2/2]
#define LLDB_PROPERTIES_process_experimental
Definition at line 131 of file Process.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ePropertyExperimental
Definition at line 125 of file Process.cpp.
anonymous enum
anonymous enum
Definition at line 134 of file Process.cpp.
Function Documentation
AddDirtyPages()
bool AddDirtyPages (const lldb_private::MemoryRegionInfo & region, CoreFileMemoryRanges & ranges) static
Definition at line 6688 of file Process.cpp.
References lldb_private::RangeDataVector< B, S, T, N, Compare >::Append(), lldb_private::MemoryRegionInfo::GetDirtyPageList(), lldb_private::MemoryRegionInfo::GetLLDBPermissions(), and lldb_private::MemoryRegionInfo::GetPageSize().
Referenced by AddRegion(), and GetCoreFileSaveRangesDirtyOnly().
AddRegion()
void AddRegion (const lldb_private::MemoryRegionInfo & region, bool try_dirty_pages, CoreFileMemoryRanges & ranges) static
Definition at line 6727 of file Process.cpp.
References AddDirtyPages(), lldb_private::RangeDataVector< B, S, T, N, Compare >::Append(), CreateCoreFileMemoryRange(), lldb_private::Range< B, S >::GetByteSize(), lldb_private::MemoryRegionInfo::GetLLDBPermissions(), lldb_private::MemoryRegionInfo::GetRange(), and lldb_private::Range< B, S >::GetRangeBase().
Referenced by GetCoreFileSaveRangesDirtyOnly(), GetCoreFileSaveRangesFull(), GetCoreFileSaveRangesStackOnly(), GetUserSpecifiedCoreFileSaveRanges(), SaveDynamicLoaderSections(), and SaveOffRegionsWithStackPointers().
CreateCoreFileMemoryRange()
CoreFileMemoryRange CreateCoreFileMemoryRange (const lldb_private::MemoryRegionInfo & region) static
Definition at line 6679 of file Process.cpp.
References lldb_private::Range< B, S >::GetByteSize(), lldb_private::MemoryRegionInfo::GetLLDBPermissions(), lldb_private::MemoryRegionInfo::GetRange(), and lldb_private::Range< B, S >::GetRangeBase().
Referenced by AddRegion().
GetCoreFileSaveRangesDirtyOnly()
void GetCoreFileSaveRangesDirtyOnly (Process & process, const MemoryRegionInfos & regions, CoreFileMemoryRanges & ranges, std::set< addr_t > & stack_ends) static
Definition at line 6826 of file Process.cpp.
References AddDirtyPages(), AddRegion(), and lldb_private::MemoryRegionInfo::eYes.
Referenced by lldb_private::Process::CalculateCoreFileSaveRanges().
GetCoreFileSaveRangesFull()
void GetCoreFileSaveRangesFull (Process & process, const MemoryRegionInfos & regions, CoreFileMemoryRanges & ranges, std::set< addr_t > & stack_ends) static
Definition at line 6810 of file Process.cpp.
References AddRegion().
Referenced by lldb_private::Process::CalculateCoreFileSaveRanges().
GetCoreFileSaveRangesStackOnly()
void GetCoreFileSaveRangesStackOnly (Process & process, const MemoryRegionInfos & regions, CoreFileMemoryRanges & ranges, std::set< addr_t > & stack_ends) static
Definition at line 6858 of file Process.cpp.
References AddRegion(), and lldb_private::MemoryRegionInfo::eYes.
Referenced by lldb_private::Process::CalculateCoreFileSaveRanges().
GetExpressionTimeout()
Timeout< std::micro > GetExpressionTimeout (const EvaluateExpressionOptions & options, bool before_first_timeout) static
Definition at line 5055 of file Process.cpp.
References GetOneThreadExpressionTimeout(), lldb_private::EvaluateExpressionOptions::GetStopOthers(), lldb_private::EvaluateExpressionOptions::GetTimeout(), and lldb_private::EvaluateExpressionOptions::GetTryAllThreads().
Referenced by lldb_private::Process::RunThreadPlan().
GetOneThreadExpressionTimeout()
microseconds GetOneThreadExpressionTimeout (const EvaluateExpressionOptions & options) static
Definition at line 5035 of file Process.cpp.
References lldb_private::EvaluateExpressionOptions::GetOneThreadTimeout(), and lldb_private::EvaluateExpressionOptions::GetTimeout().
Referenced by GetExpressionTimeout().
GetUserSpecifiedCoreFileSaveRanges()
void GetUserSpecifiedCoreFileSaveRanges (Process & process, const MemoryRegionInfos & regions, const SaveCoreOptions & options, CoreFileMemoryRanges & ranges) static
Definition at line 6887 of file Process.cpp.
References AddRegion(), lldb_private::SaveCoreOptions::GetCoreFileMemoryRanges(), and Intersect().
Referenced by lldb_private::Process::CalculateCoreFileSaveRanges().
HandleStoppedEvent()
std::optional< ExpressionResults > HandleStoppedEvent (lldb::tid_t thread_id, const ThreadPlanSP & thread_plan_sp, RestorePlanState & restorer, const EventSP & event_sp, EventSP & event_to_broadcast_sp, const EvaluateExpressionOptions & options, bool handle_interrupts) static
Definition at line 5072 of file Process.cpp.
References lldb_private::EvaluateExpressionOptions::DoesIgnoreBreakpoints(), lldb_private::EvaluateExpressionOptions::DoesUnwindOnError(), lldb::eExpressionCompleted, lldb::eExpressionHitBreakpoint, lldb::eExpressionInterrupted, lldb::eExpressionThreadVanished, lldb::eStopReasonBreakpoint, lldb_private::Process::ProcessEventData::GetInterruptedFromEvent(), lldb_private::GetLog(), LLDB_LOG, lldb_private::Process, and lldb_private::Step.
Referenced by lldb_private::Process::RunThreadPlan().
Intersect()
lldb_private::MemoryRegionInfo Intersect (const lldb_private::MemoryRegionInfo & lhs, const lldb_private::MemoryRegionInfo::RangeType & rhs) static
Definition at line 6877 of file Process.cpp.
References lldb_private::MemoryRegionInfo::GetLLDBPermissions(), lldb_private::MemoryRegionInfo::GetRange(), lldb_private::Range< B, S >::Intersect(), and lldb_private::MemoryRegionInfo::SetLLDBPermissions().
Referenced by GetUserSpecifiedCoreFileSaveRanges().
SaveDynamicLoaderSections()
void SaveDynamicLoaderSections (Process & process, const SaveCoreOptions & options, CoreFileMemoryRanges & ranges, std::set< addr_t > & stack_ends) static
Definition at line 6743 of file Process.cpp.
References AddRegion(), lldb_private::DynamicLoader::CalculateDynamicSaveCoreRanges(), lldb_private::Process::GetDynamicLoader(), and lldb_private::SaveCoreOptions::ShouldThreadBeSaved().
Referenced by lldb_private::Process::CalculateCoreFileSaveRanges().
SaveOffRegionsWithStackPointers()
void SaveOffRegionsWithStackPointers (Process & process, const SaveCoreOptions & core_options, const MemoryRegionInfos & regions, CoreFileMemoryRanges & ranges, std::set< addr_t > & stack_ends) static
Definition at line 6766 of file Process.cpp.
References AddRegion(), lldb_private::Process::GetABI(), lldb_private::Process::GetMemoryRegionInfo(), lldb_private::MemoryRegionInfo::GetRange(), lldb_private::Range< B, S >::GetRangeEnd(), lldb_private::Process::GetThreadList(), lldb_private::Range< B, S >::SetByteSize(), lldb_private::Range< B, S >::SetRangeBase(), lldb_private::SaveCoreOptions::ShouldThreadBeSaved(), sp, lldb_private::Status::Success(), and lldb_private::ThreadCollection::Threads().
Referenced by lldb_private::Process::CalculateCoreFileSaveRanges().
Variable Documentation
g_follow_fork_mode_values
OptionEnumValueElement g_follow_fork_mode_values[] static constexpr
Initial value:
= {
    {
        eFollowParent,
        "parent",
        "Continue tracing the parent process and detach the child.",
    },
    {
        eFollowChild,
        "child",
        "Trace the child process and detach the parent.",
    },
}
Definition at line 107 of file Process.cpp.
g_string_read_width
unsigned g_string_read_width = 256 static constexpr
Definition at line 120 of file Process.cpp.
Referenced by lldb_private::Process::ReadCStringFromMemory(), and lldb_private::Process::ReadCStringsFromMemory().