LLDB: RegisterContextMinidump_x86_64.cpp File Reference
RegisterContextMinidump_x86_64.cpp File Reference
#include "RegisterContextMinidump_x86_64.h"
#include "lldb/Utility/DataBufferHeap.h"
Functions
static llvm::MutableArrayRef< uint8_t > getDestRegister (uint8_t *context, const RegisterInfo &reg)
static void writeRegister (const void *reg_src, uint8_t *context, const RegisterInfo &reg)
static void writeBaseRegister (const void *reg_src, uint8_t *context, const RegisterInfo &reg)
Function Documentation
getDestRegister()
llvm::MutableArrayRef< uint8_t > getDestRegister (uint8_t * context, const RegisterInfo & reg) static
Definition at line 19 of file RegisterContextMinidump_x86_64.cpp.
References lldb::eRegisterKindLLDB, lldb_private::RegisterInfo::kinds, lldb_private::lldb_cs_x86_64, lldb_private::lldb_ds_x86_64, lldb_private::lldb_es_x86_64, lldb_private::lldb_fs_x86_64, lldb_private::lldb_gs_x86_64, lldb_private::lldb_rflags_x86_64, lldb_private::lldb_ss_x86_64, and lldb_private::RegisterInfo::mutable_data().
Referenced by writeRegister().
writeBaseRegister()
void writeBaseRegister (const void * reg_src, uint8_t * context, const RegisterInfo & reg) static
Definition at line 51 of file RegisterContextMinidump_x86_64.cpp.
References lldb_private::RegisterInfo::mutable_data().
Referenced by lldb_private::minidump::ConvertMinidumpContext_x86_64().
writeRegister()
void writeRegister (const void * reg_src, uint8_t * context, const RegisterInfo & reg) static
Definition at line 41 of file RegisterContextMinidump_x86_64.cpp.
References getDestRegister().
Referenced by lldb_private::minidump::ConvertMinidumpContext_x86_64().