LLDB: RegisterContextLinux_s390x.cpp File Reference
RegisterContextLinux_s390x.cpp File Reference
#include "RegisterContextLinux_s390x.h"
#include "RegisterContextPOSIX_s390x.h"
#include "RegisterInfos_s390x.h"
Macros
#define DECLARE_REGISTER_INFOS_S390X_STRUCT
Functions
static const RegisterInfo * GetRegisterInfoPtr (const ArchSpec &target_arch)
static uint32_t GetRegisterInfoCount (const ArchSpec &target_arch)
static uint32_t GetUserRegisterInfoCount (const ArchSpec &target_arch)
Macro Definition Documentation
DECLARE_REGISTER_INFOS_S390X_STRUCT
#define DECLARE_REGISTER_INFOS_S390X_STRUCT
Definition at line 16 of file RegisterContextLinux_s390x.cpp.
Function Documentation
GetRegisterInfoCount()
uint32_t GetRegisterInfoCount (const ArchSpec & target_arch) static
Definition at line 30 of file RegisterContextLinux_s390x.cpp.
References lldb_private::ArchSpec::GetMachine(), and lldb_private::k_num_registers_s390x.
Referenced by RegisterContextLinux_s390x::RegisterContextLinux_s390x(), RegisterInfoPOSIX_arm::RegisterInfoPOSIX_arm(), RegisterInfoPOSIX_ppc64::RegisterInfoPOSIX_ppc64(), and RegisterInfoPOSIX_ppc64le::RegisterInfoPOSIX_ppc64le().
GetRegisterInfoPtr()
const RegisterInfo * GetRegisterInfoPtr (const ArchSpec & target_arch) static
Definition at line 20 of file RegisterContextLinux_s390x.cpp.
References lldb_private::ArchSpec::GetMachine().
Referenced by RegisterContextLinux_s390x::RegisterContextLinux_s390x(), RegisterInfoPOSIX_arm::RegisterInfoPOSIX_arm(), RegisterInfoPOSIX_ppc64::RegisterInfoPOSIX_ppc64(), and RegisterInfoPOSIX_ppc64le::RegisterInfoPOSIX_ppc64le().
GetUserRegisterInfoCount()
uint32_t GetUserRegisterInfoCount (const ArchSpec & target_arch) static
Definition at line 40 of file RegisterContextLinux_s390x.cpp.
References lldb_private::ArchSpec::GetMachine(), lldb_private::k_num_linux_registers_s390x, and lldb_private::k_num_user_registers_s390x.
Referenced by RegisterContextLinux_s390x::RegisterContextLinux_s390x().