LLDB: RegisterContextUnwind.cpp File Reference
RegisterContextUnwind.cpp File Reference
#include "lldb/Target/RegisterContextUnwind.h"
#include "lldb/Core/Address.h"
#include "lldb/Core/AddressRange.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/Value.h"
#include "lldb/Expression/DWARFExpressionList.h"
#include "lldb/Symbol/ArmUnwindInfo.h"
#include "lldb/Symbol/CallFrameInfo.h"
#include "lldb/Symbol/DWARFCallFrameInfo.h"
#include "lldb/Symbol/FuncUnwinders.h"
#include "lldb/Symbol/Function.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Symbol/Symbol.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Symbol/SymbolFile.h"
#include "lldb/Target/ABI.h"
#include "lldb/Target/DynamicLoader.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/LanguageRuntime.h"
#include "lldb/Target/Platform.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/SectionLoadList.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/RegisterValue.h"
#include "lldb/Utility/VASPrintf.h"
#include "lldb/lldb-private.h"
#include <cassert>
#include <memory>
Functions
static ConstString GetSymbolOrFunctionName (const SymbolContext &sym_ctx)
static bool CallFrameAddressIsValid (ABISP abi_sp, lldb::addr_t cfa)
Function Documentation
CallFrameAddressIsValid()
bool CallFrameAddressIsValid (ABISP abi_sp, lldb::addr_t cfa) static
Definition at line 55 of file RegisterContextUnwind.cpp.
References LLDB_INVALID_ADDRESS.
Referenced by lldb_private::RegisterContextUnwind::ForceSwitchToFallbackUnwindPlan(), lldb_private::RegisterContextUnwind::InitializeNonZerothFrame(), lldb_private::RegisterContextUnwind::ReadFrameAddress(), and lldb_private::RegisterContextUnwind::TryFallbackUnwindPlan().
GetSymbolOrFunctionName()
ConstString GetSymbolOrFunctionName (const SymbolContext & sym_ctx) static
Definition at line 47 of file RegisterContextUnwind.cpp.
References lldb_private::SymbolContext::function, lldb_private::Function::GetName(), lldb_private::Symbol::GetName(), and lldb_private::SymbolContext::symbol.
Referenced by lldb_private::RegisterContextUnwind::GetFullUnwindPlanForFrame(), lldb_private::RegisterContextUnwind::InitializeNonZerothFrame(), lldb_private::RegisterContextUnwind::InitializeZerothFrame(), and lldb_private::RegisterContextUnwind::PropagateTrapHandlerFlagFromUnwindPlan().