LLDB: RegisterFlags.cpp File Reference
RegisterFlags.cpp File Reference
#include "lldb/Target/RegisterFlags.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/StreamString.h"
#include "llvm/ADT/StringExtras.h"
#include <limits>
#include <numeric>
#include <optional>
Functions
static StreamString FormatCell (const StreamString &content, unsigned column_width)
static void EmitTable (std::string &out, std::array< std::string, 3 > &table)
static void DumpEnumerators (StreamString &strm, size_t indent, size_t current_width, uint32_t max_width, const FieldEnum::Enumerators &enumerators)
Function Documentation
DumpEnumerators()
void DumpEnumerators (StreamString & strm, size_t indent, size_t current_width, uint32_t max_width, const FieldEnum::Enumerators & enumerators) static
Definition at line 246 of file RegisterFlags.cpp.
References lldb_private::StreamString::GetString(), and lldb_private::Stream::Printf().
Referenced by lldb_private::RegisterFlags::DumpEnums().
EmitTable()
void EmitTable (std::string & out, std::array< std::string, 3 > & table) static
Definition at line 177 of file RegisterFlags.cpp.
Referenced by lldb_private::RegisterFlags::AsTable().
FormatCell()
StreamString FormatCell (const StreamString & content, unsigned column_width) static
Definition at line 161 of file RegisterFlags.cpp.
References lldb_private::StreamString::GetString(), and lldb_private::Stream::Printf().
Referenced by lldb_private::RegisterFlags::AsTable().