LLDB: REPL.cpp File Reference
REPL.cpp File Reference
#include "lldb/Expression/REPL.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Expression/ExpressionVariable.h"
#include "lldb/Expression/UserExpression.h"
#include "lldb/Host/HostInfo.h"
#include "lldb/Host/StreamFile.h"
#include "lldb/Interpreter/CommandInterpreter.h"
#include "lldb/Interpreter/CommandReturnObject.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/AnsiTerminal.h"
#include <memory>
Functions
static bool ReadCode (const std::string &path, std::string &code, lldb::StreamFileSP &error_sp)
bool QuitCommandOverrideCallback (void *baton, const char **argv)
Function Documentation
QuitCommandOverrideCallback()
bool QuitCommandOverrideCallback (void * baton, const char ** argv)
Definition at line 550 of file REPL.cpp.
References lldb_private::Target::GetProcessSP().
Referenced by lldb_private::REPL::RunLoop().
ReadCode()
bool ReadCode (const std::string & path, std::string & code, lldb::StreamFileSP & error_sp) static
Definition at line 191 of file REPL.cpp.
References lldb_private::FileSystem::Instance().
Referenced by lldb_private::REPL::IOHandlerInputComplete().