LLDB: Resource.cpp File Reference
Resource.cpp File Reference
#include "Resource.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Module.h"
#include "lldb/Protocol/MCP/MCPError.h"
Functions
template<typename... Args>
static llvm::Error createStringError (const char *format, Args &&...args)
static llvm::Error createUnsupportedURIError (llvm::StringRef uri)
Variables
static constexpr llvm::StringLiteral kMimeTypeJSON = "application/json"
Function Documentation
createStringError()
template<typename... Args> llvm::Error createStringError (const char * format, Args &&... args) static
Definition at line 59 of file Resource.cpp.
Referenced by BuildModulesSection(), lldb_private::mcp::CommandTool::Call(), CheckPsbPeriod(), lldb_private::trace_intel_pt::TraceIntelPTMultiCpuDecoder::CorrelateContextSwitchesAndIntelPtTraces(), lldb_private::process_linux::CreateContextSwitchTracePerfEvent(), createInvalidPlugInError(), createInvalidPlugInError(), lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::CreateJSONError(), lldb_private::trace_intel_pt::TraceIntelPT::Decode(), PSBBlockAnomalyDetector::DetectAnomaly(), lldb_private::process_linux::PerfEvent::DisableWithIoctl(), lldb_private::trace_intel_pt::TraceIntelPTMultiCpuDecoder::DoCorrelateContextSwitchesAndIntelPtTraces(), lldb_private::CommandObjectTraceProxy::DoGetProxyCommandObject(), lldb_private::process_linux::PerfEvent::DoMmap(), lldb_private::trace_intel_pt::TraceIntelPT::DoRefreshLiveProcessState(), lldb_private::process_linux::PerfEvent::EnableWithIoctl(), lldb_private::process_linux::IntelPTCollector::FetchPerfTscConversionParameters(), lldb_private::Trace::FindPluginForLiveProcess(), lldb_private::process_linux::IntelPTCollector::GetBinaryData(), lldb_private::trace_intel_pt::TraceIntelPT::GetCPUInfoForLiveProcess(), lldb_private::Trace::GetLiveCpuBinaryData(), lldb_private::Trace::GetLiveProcessBinaryData(), lldb_private::Trace::GetLiveProcessState(), lldb_private::Trace::GetLiveThreadBinaryData(), lldb_private::Trace::GetLiveTraceBinaryData(), lldb_private::Trace::GetPostMortemCpuDataFile(), lldb_private::Trace::GetPostMortemThreadDataFile(), lldb_private::process_linux::GetPtraceScope(), lldb_private::process_linux::PerfEvent::GetReadOnlyAuxBuffer(), lldb_private::process_linux::PerfEvent::GetReadOnlyDataBuffer(), lldb_private::process_linux::IntelPTThreadTraceCollection::GetTracedThread(), IncludePerfEventParanoidMessageInError(), lldb_private::Trace::LoadPostMortemTraceFromFile(), lldb_private::process_linux::PerfEvent::MmapAuxBuffer(), lldb_private::NativeProcessWindows::NativeProcessWindows(), lldb_private::Trace::OnDataFileRead(), lldb_private::trace_intel_pt::TraceIntelPTBundleLoader::ParseModule(), PSBBlockDecoder::ProcessPTEventTSC(), lldb_private::mcp::DebuggerResourceProvider::ReadDebuggerResource(), ReadIntelPTConfigFile(), lldb_private::mcp::DebuggerResourceProvider::ReadResource(), lldb_private::mcp::DebuggerResourceProvider::ReadTargetResource(), RecoverExecutionsFromConsecutiveRecords(), lldb_private::platform_android::AdbClient::ResolveDeviceID(), lldb_protocol::mcp::Server::ResourcesReadHandler(), perf_event_header::SanityCheck(), SaveTraceBundleDescription(), SetupPythonRuntimeLibrary(), lldb_private::trace_intel_pt::SplitTraceIntoPSBBlock(), lldb_private::mcp::ProtocolServerMCP::Start(), lldb_private::process_linux::IntelPTSingleBufferTrace::Start(), lldb_private::Trace::Start(), lldb_private::trace_intel_pt::TraceIntelPT::Start(), lldb_private::process_linux::IntelPTMultiCoreTrace::StartOnAllCores(), lldb_private::Status::Status(), lldb_private::mcp::ProtocolServerMCP::Stop(), lldb_private::Trace::Stop(), lldb_private::Trace::Stop(), lldb_private::process_linux::IntelPTCollector::TraceStart(), lldb_private::process_linux::IntelPTMultiCoreTrace::TraceStart(), lldb_private::process_linux::IntelPTPerThreadProcessTrace::TraceStart(), lldb_private::process_linux::IntelPTThreadTraceCollection::TraceStart(), lldb_private::process_linux::IntelPTMultiCoreTrace::TraceStop(), lldb_private::process_linux::IntelPTThreadTraceCollection::TraceStop(), lldb_private::process_linux::IntelPTMultiCoreTrace::TryGetBinaryData(), and WriteBytesToDisk().
createUnsupportedURIError()
llvm::Error createUnsupportedURIError (llvm::StringRef uri) static
Definition at line 64 of file Resource.cpp.
Referenced by lldb_private::mcp::DebuggerResourceProvider::ReadResource().
Variable Documentation
kMimeTypeJSON
llvm::StringLiteral kMimeTypeJSON = "application/json" static constexpr
Definition at line 56 of file Resource.cpp.
Referenced by lldb_private::mcp::DebuggerResourceProvider::GetDebuggerResource(), lldb_private::mcp::DebuggerResourceProvider::GetTargetResource(), lldb_private::mcp::DebuggerResourceProvider::ReadDebuggerResource(), and lldb_private::mcp::DebuggerResourceProvider::ReadTargetResource().