LLDB: SBDebugger.cpp File Reference
SBDebugger.cpp File Reference
#include "lldb/API/SBDebugger.h"
#include "SystemInitializerFull.h"
#include "lldb/Utility/Instrumentation.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/API/SBBroadcaster.h"
#include "lldb/API/SBCommandInterpreter.h"
#include "lldb/API/SBCommandInterpreterRunOptions.h"
#include "lldb/API/SBCommandReturnObject.h"
#include "lldb/API/SBError.h"
#include "lldb/API/SBEvent.h"
#include "lldb/API/SBFile.h"
#include "lldb/API/SBFrame.h"
#include "lldb/API/SBListener.h"
#include "lldb/API/SBProcess.h"
#include "lldb/API/SBSourceManager.h"
#include "lldb/API/SBStream.h"
#include "lldb/API/SBStringList.h"
#include "lldb/API/SBStructuredData.h"
#include "lldb/API/SBTarget.h"
#include "lldb/API/SBThread.h"
#include "lldb/API/SBTrace.h"
#include "lldb/API/SBTypeCategory.h"
#include "lldb/API/SBTypeFilter.h"
#include "lldb/API/SBTypeFormat.h"
#include "lldb/API/SBTypeNameSpecifier.h"
#include "lldb/API/SBTypeSummary.h"
#include "lldb/API/SBTypeSynthetic.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/DebuggerEvents.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Progress.h"
#include "lldb/Core/StructuredDataImpl.h"
#include "lldb/DataFormatters/DataVisualization.h"
#include "lldb/Host/Config.h"
#include "lldb/Host/StreamFile.h"
#include "lldb/Host/XML.h"
#include "lldb/Initialization/SystemLifetimeManager.h"
#include "lldb/Interpreter/CommandInterpreter.h"
#include "lldb/Interpreter/OptionArgParser.h"
#include "lldb/Interpreter/OptionGroupPlatform.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/TargetList.h"
#include "lldb/Utility/Args.h"
#include "lldb/Utility/Diagnostics.h"
#include "lldb/Utility/State.h"
#include "lldb/Version/Version.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/DynamicLibrary.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/PrettyStackTrace.h"
#include "llvm/Support/Signals.h"
Functions
static void DumpDiagnostics (void *cookie)
static llvm::ArrayRef< const char * > GetCategoryArray (const char **categories)
Variables
static llvm::ManagedStatic< SystemLifetimeManager > g_debugger_lifetime
Function Documentation
DumpDiagnostics()
void DumpDiagnostics (void * cookie) static
Definition at line 199 of file SBDebugger.cpp.
References lldb_private::Diagnostics::Dump(), and lldb_private::Diagnostics::Instance().
Referenced by lldb::SBDebugger::PrintDiagnosticsOnError().
GetCategoryArray()
llvm::ArrayRef< const char * > GetCategoryArray (const char ** categories) static
Definition at line 1618 of file SBDebugger.cpp.
Referenced by lldb::SBDebugger::EnableLog().
Variable Documentation
g_debugger_lifetime
llvm::ManagedStatic<SystemLifetimeManager> g_debugger_lifetime static
Definition at line 69 of file SBDebugger.cpp.
Referenced by lldb::SBDebugger::InitializeWithErrorHandling(), and lldb::SBDebugger::Terminate().