LLDB: SBFrame.cpp File Reference
SBFrame.cpp File Reference
#include <algorithm>
#include <set>
#include <string>
#include "lldb/API/SBFrame.h"
#include "lldb/lldb-types.h"
#include "Utils.h"
#include "lldb/Core/Address.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Expression/ExpressionVariable.h"
#include "lldb/Expression/UserExpression.h"
#include "lldb/Host/Host.h"
#include "lldb/Symbol/Block.h"
#include "lldb/Symbol/Function.h"
#include "lldb/Symbol/Symbol.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Symbol/Variable.h"
#include "lldb/Symbol/VariableList.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/StackFrameRecognizer.h"
#include "lldb/Target/StackID.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/Instrumentation.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Stream.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
#include "lldb/ValueObject/ValueObjectRegister.h"
#include "lldb/ValueObject/ValueObjectVariable.h"
#include "lldb/API/SBAddress.h"
#include "lldb/API/SBDebugger.h"
#include "lldb/API/SBExpressionOptions.h"
#include "lldb/API/SBFormat.h"
#include "lldb/API/SBStream.h"
#include "lldb/API/SBStructuredData.h"
#include "lldb/API/SBSymbolContext.h"
#include "lldb/API/SBThread.h"
#include "lldb/API/SBValue.h"
#include "lldb/API/SBVariablesOptions.h"
#include "llvm/Support/PrettyStackTrace.h"
Enumerations
enum WasInterrupted { Yes , No }
Functions
static bool IsInRequestedScope (bool statics, bool arguments, bool locals, Variable &var)
Returns true if the variable is in any of the requested scopes.
static std::pair< WasInterrupted, Status > FetchVariablesUnlessInterrupted (const lldb::SBVariablesOptions &options, StackFrame &frame, SBValueList &value_list, Debugger &dbg, std::function< SBValue(ValueObjectSP, bool)> to_sbvalue)
Populates value_list with the variables from frame according to options.
static llvm::SmallVector< ValueObjectSP > FetchRecognizedArguments (const SBVariablesOptions &options, StackFrame &frame, SBTarget target)
Populates value_list with recognized arguments of frame according to options.
Enumeration Type Documentation
WasInterrupted
enum WasInterrupted
Enumerator
Yes
No
Definition at line 710 of file SBFrame.cpp.
Function Documentation
FetchRecognizedArguments()
llvm::SmallVector< ValueObjectSP > FetchRecognizedArguments (const SBVariablesOptions & options, StackFrame & frame, SBTarget target) static
Populates value_list with recognized arguments of frame according to options.
Definition at line 772 of file SBFrame.cpp.
References lldb::SBVariablesOptions::GetIncludeRecognizedArguments(), and lldb_private::StackFrame::GetRecognizedFrame().
Referenced by lldb::SBFrame::GetVariables().
FetchVariablesUnlessInterrupted()
std::pair< WasInterrupted, Status > FetchVariablesUnlessInterrupted (const lldb::SBVariablesOptions & options, StackFrame & frame, SBValueList & value_list, Debugger & dbg, std::function< SBValue(ValueObjectSP, bool)> to_sbvalue) static
Populates value_list with the variables from frame according to options.
This method checks whether the Debugger received an interrupt before processing every variable, returning WasInterrupted::yes in that case.
Definition at line 716 of file SBFrame.cpp.
References lldb::SBValueList::Append(), lldb::eNoDynamicValues, lldb::SBVariablesOptions::GetIncludeArguments(), lldb::SBVariablesOptions::GetIncludeLocals(), lldb::SBVariablesOptions::GetIncludeRuntimeSupportValues(), lldb::SBVariablesOptions::GetIncludeStatics(), lldb::SBVariablesOptions::GetInScopeOnly(), lldb_private::VariableList::GetSize(), lldb::SBVariablesOptions::GetUseDynamic(), lldb_private::StackFrame::GetValueObjectForFrameVariable(), lldb_private::StackFrame::GetVariableList(), INTERRUPT_REQUESTED, IsInRequestedScope(), No, and Yes.
Referenced by lldb::SBFrame::GetVariables().
IsInRequestedScope()
bool IsInRequestedScope (bool statics, bool arguments, bool locals, Variable & var) static
Returns true if the variable is in any of the requested scopes.
Definition at line 690 of file SBFrame.cpp.
References lldb::eValueTypeVariableArgument, lldb::eValueTypeVariableGlobal, lldb::eValueTypeVariableLocal, lldb::eValueTypeVariableStatic, lldb::eValueTypeVariableThreadLocal, and lldb_private::Variable::GetScope().
Referenced by FetchVariablesUnlessInterrupted().