LLDB: SBModule.cpp File Reference
SBModule.cpp File Reference
#include "lldb/API/SBModule.h"
#include "lldb/API/SBAddress.h"
#include "lldb/API/SBFileSpec.h"
#include "lldb/API/SBModuleSpec.h"
#include "lldb/API/SBProcess.h"
#include "lldb/API/SBStream.h"
#include "lldb/API/SBSymbolContextList.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/Section.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Symbol/SymbolFile.h"
#include "lldb/Symbol/Symtab.h"
#include "lldb/Symbol/TypeSystem.h"
#include "lldb/Symbol/VariableList.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/Instrumentation.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/ValueObject/ValueObjectList.h"
#include "lldb/ValueObject/ValueObjectVariable.h"
Functions
static Symtab * GetUnifiedSymbolTable (const lldb::ModuleSP &module_sp)
Function Documentation
GetUnifiedSymbolTable()
Symtab * GetUnifiedSymbolTable (const lldb::ModuleSP & module_sp) static
Definition at line 293 of file SBModule.cpp.
Referenced by lldb::SBModule::FindSymbol(), lldb::SBModule::FindSymbols(), lldb::SBModule::GetNumSymbols(), and lldb::SBModule::GetSymbolAtIndex().