LLDB: SBValue.cpp File Reference
SBValue.cpp File Reference
#include "lldb/API/SBValue.h"
#include "lldb/Utility/Instrumentation.h"
#include "lldb/API/SBDeclaration.h"
#include "lldb/API/SBStream.h"
#include "lldb/API/SBTypeFilter.h"
#include "lldb/API/SBTypeFormat.h"
#include "lldb/API/SBTypeSummary.h"
#include "lldb/API/SBTypeSynthetic.h"
#include "lldb/Breakpoint/Watchpoint.h"
#include "lldb/Core/Declaration.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/Section.h"
#include "lldb/Core/Value.h"
#include "lldb/DataFormatters/DataVisualization.h"
#include "lldb/DataFormatters/DumpValueObjectOptions.h"
#include "lldb/Symbol/Block.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Symbol/Type.h"
#include "lldb/Symbol/Variable.h"
#include "lldb/Symbol/VariableList.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/DataExtractor.h"
#include "lldb/Utility/Scalar.h"
#include "lldb/Utility/Stream.h"
#include "lldb/ValueObject/ValueObject.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
#include "lldb/API/SBDebugger.h"
#include "lldb/API/SBExpressionOptions.h"
#include "lldb/API/SBFrame.h"
#include "lldb/API/SBProcess.h"
#include "lldb/API/SBTarget.h"
#include "lldb/API/SBThread.h"
#include "lldb/lldb-enumerations.h"
#include <memory>
Functions
static DumpValueObjectOptions GetDumpOptions (lldb::DescriptionLevel description_level, lldb::DynamicValueType dyn, bool use_synthetic)
Function Documentation
GetDumpOptions()
DumpValueObjectOptions GetDumpOptions (lldb::DescriptionLevel description_level, lldb::DynamicValueType dyn, bool use_synthetic) static
Definition at line 1104 of file SBValue.cpp.
References lldb::eDescriptionLevelBrief, lldb::eDescriptionLevelInitial, lldb::eDescriptionLevelVerbose, lldb_private::DumpValueObjectOptions::SetAllowOnelinerMode(), lldb_private::DumpValueObjectOptions::SetHideRootName(), lldb_private::DumpValueObjectOptions::SetHideRootType(), lldb_private::DumpValueObjectOptions::SetShowLocation(), lldb_private::DumpValueObjectOptions::SetShowTypes(), lldb_private::DumpValueObjectOptions::SetUseDynamicType(), and lldb_private::DumpValueObjectOptions::SetUseSyntheticValue().
Referenced by lldb::SBValue::GetDescription().