LLDB: ScriptInterpreter.cpp File Reference
ScriptInterpreter.cpp File Reference
#include "lldb/Interpreter/ScriptInterpreter.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Host/ConnectionFileDescriptor.h"
#include "lldb/Host/Pipe.h"
#include "lldb/Host/PseudoTerminal.h"
#include "lldb/Interpreter/CommandReturnObject.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/Stream.h"
#include "lldb/Utility/StringList.h"
#include "lldb/ValueObject/ValueObject.h"
#include <cstdio>
#include <cstdlib>
#include <memory>
#include <optional>
#include <string>
Functions
static void ReadThreadBytesReceived (void *baton, const void *src, size_t src_len)
Function Documentation
ReadThreadBytesReceived()
void ReadThreadBytesReceived (void * baton, const void * src, size_t src_len) static
Definition at line 217 of file ScriptInterpreter.cpp.
References lldb_private::Stream::Flush(), and lldb_private::Stream::Write().
Referenced by lldb_private::ScriptInterpreterIORedirect::ScriptInterpreterIORedirect().