LLDB: ScriptedPythonInterface.cpp File Reference
ScriptedPythonInterface.cpp File Reference
#include "lldb/Host/Config.h"
#include "lldb/Utility/Log.h"
#include "lldb/lldb-enumerations.h"
#include "../lldb-python.h"
#include "../ScriptInterpreterPythonImpl.h"
#include "ScriptedPythonInterface.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/ValueObject/ValueObjectList.h"
#include <optional>
Functions
template<>
StructuredData::ArraySP ScriptedPythonInterface::ExtractValueFromPythonObject< StructuredData::ArraySP > (python::PythonObject &p, Status &error)
template<>
StructuredData::DictionarySP ScriptedPythonInterface::ExtractValueFromPythonObject< StructuredData::DictionarySP > (python::PythonObject &p, Status &error)
template<>
lldb::StreamSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StreamSP > (python::PythonObject &p, Status &error)
template<>
lldb::StackFrameSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameSP > (python::PythonObject &p, Status &error)
template<>
lldb::ThreadSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ThreadSP > (python::PythonObject &p, Status &error)
template<>
lldb::DataExtractorSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::DataExtractorSP > (python::PythonObject &p, Status &error)
template<>
lldb::BreakpointSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointSP > (python::PythonObject &p, Status &error)
template<>
lldb::BreakpointLocationSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointLocationSP > (python::PythonObject &p, Status &error)
template<>
lldb::ProcessAttachInfoSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessAttachInfoSP > (python::PythonObject &p, Status &error)
template<>
lldb::ProcessLaunchInfoSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessLaunchInfoSP > (python::PythonObject &p, Status &error)
template<>
std::optional< MemoryRegionInfo > ScriptedPythonInterface::ExtractValueFromPythonObject< std::optional< MemoryRegionInfo > > (python::PythonObject &p, Status &error)
template<>
lldb::ExecutionContextRefSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ExecutionContextRefSP > (python::PythonObject &p, Status &error)
template<>
lldb::DescriptionLevel ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::DescriptionLevel > (python::PythonObject &p, Status &error)
template<>
lldb::StackFrameListSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameListSP > (python::PythonObject &p, Status &error)
template<>
lldb::ValueObjectSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectSP > (python::PythonObject &p, Status &error)
template<>
lldb::ValueObjectListSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectListSP > (python::PythonObject &p, Status &error)
Function Documentation
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointLocationSP >()
template<> lldb::BreakpointLocationSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointLocationSP > (python::PythonObject & p, Status & error)
Definition at line 155 of file ScriptedPythonInterface.cpp.
References error(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject(), lldb_private::Status::FromErrorStringWithFormat(), and lldb_private::python::LLDBSWIGPython_CastPyObjectToSBBreakpointLocation().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointSP >()
template<> lldb::BreakpointSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::BreakpointSP > (python::PythonObject & p, Status & error)
Definition at line 139 of file ScriptedPythonInterface.cpp.
References error(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::python::PythonObject::get(), and lldb_private::python::LLDBSWIGPython_CastPyObjectToSBBreakpoint().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::DataExtractorSP >()
template<> lldb::DataExtractorSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::DataExtractorSP > (python::PythonObject & p, Status & error)
Definition at line 123 of file ScriptedPythonInterface.cpp.
References error(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::python::PythonObject::get(), and lldb_private::python::LLDBSWIGPython_CastPyObjectToSBData().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::DescriptionLevel >()
template<> lldb::DescriptionLevel ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::DescriptionLevel > (python::PythonObject & p, Status & error)
Definition at line 241 of file ScriptedPythonInterface.cpp.
References lldb_private::python::PythonObject::AsUnsignedLongLong(), lldb::eDescriptionLevelBrief, error(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject(), lldb_private::Status::FromError(), lldb::kNumDescriptionLevels, and lldb_private::Status.
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ExecutionContextRefSP >()
template<> lldb::ExecutionContextRefSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ExecutionContextRefSP > (python::PythonObject & p, Status & error)
Definition at line 222 of file ScriptedPythonInterface.cpp.
References error(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject(), lldb_private::Status::FromErrorStringWithFormat(), and lldb_private::python::LLDBSWIGPython_CastPyObjectToSBExecutionContext().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessAttachInfoSP >()
template<> lldb::ProcessAttachInfoSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessAttachInfoSP > (python::PythonObject & p, Status & error)
Definition at line 173 of file ScriptedPythonInterface.cpp.
References error(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject(), lldb_private::Status::FromErrorStringWithFormat(), and lldb_private::python::LLDBSWIGPython_CastPyObjectToSBAttachInfo().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessLaunchInfoSP >()
template<> lldb::ProcessLaunchInfoSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ProcessLaunchInfoSP > (python::PythonObject & p, Status & error)
Definition at line 188 of file ScriptedPythonInterface.cpp.
References error(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject(), lldb_private::Status::FromErrorStringWithFormat(), and lldb_private::python::LLDBSWIGPython_CastPyObjectToSBLaunchInfo().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameListSP >()
template<> lldb::StackFrameListSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameListSP > (python::PythonObject & p, Status & error)
Definition at line 259 of file ScriptedPythonInterface.cpp.
References error(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::python::PythonObject::get(), and lldb_private::python::LLDBSWIGPython_CastPyObjectToSBFrameList().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameSP >()
template<> lldb::StackFrameSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StackFrameSP > (python::PythonObject & p, Status & error)
Definition at line 83 of file ScriptedPythonInterface.cpp.
References error(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject(), lldb_private::Status::FromErrorString(), lldb_private::python::PythonObject::get(), and lldb_private::python::LLDBSWIGPython_CastPyObjectToSBFrame().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StreamSP >()
template<> lldb::StreamSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::StreamSP > (python::PythonObject & p, Status & error)
Definition at line 70 of file ScriptedPythonInterface.cpp.
References error(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject(), lldb_private::Status::FromErrorString(), lldb_private::python::PythonObject::get(), and lldb_private::python::LLDBSWIGPython_CastPyObjectToSBStream().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ThreadSP >()
template<> lldb::ThreadSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ThreadSP > (python::PythonObject & p, Status & error)
Definition at line 96 of file ScriptedPythonInterface.cpp.
References error(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject(), lldb_private::Status::FromErrorString(), lldb_private::python::PythonObject::get(), and lldb_private::python::LLDBSWIGPython_CastPyObjectToSBThread().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectListSP >()
template<> lldb::ValueObjectListSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectListSP > (python::PythonObject & p, Status & error)
Definition at line 291 of file ScriptedPythonInterface.cpp.
References error(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::python::PythonObject::get(), ValueListImpl::GetSize(), ValueListImpl::GetValueAtIndex(), and lldb_private::python::LLDBSWIGPython_CastPyObjectToSBValueList().
ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectSP >()
template<> lldb::ValueObjectSP ScriptedPythonInterface::ExtractValueFromPythonObject< lldb::ValueObjectSP > (python::PythonObject & p, Status & error)
Definition at line 276 of file ScriptedPythonInterface.cpp.
References error(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::python::PythonObject::get(), and lldb_private::python::LLDBSWIGPython_CastPyObjectToSBValue().
ScriptedPythonInterface::ExtractValueFromPythonObject< std::optional< MemoryRegionInfo > >()
template<> std::optional< MemoryRegionInfo > ScriptedPythonInterface::ExtractValueFromPythonObject< std::optional< MemoryRegionInfo > > (python::PythonObject & p, Status & error)
Definition at line 188 of file ScriptedPythonInterface.cpp.
ScriptedPythonInterface::ExtractValueFromPythonObject< StructuredData::ArraySP >()
template<> StructuredData::ArraySP ScriptedPythonInterface::ExtractValueFromPythonObject< StructuredData::ArraySP > (python::PythonObject & p, Status & error)
Definition at line 30 of file ScriptedPythonInterface.cpp.
References lldb_private::python::Borrowed, lldb_private::python::PythonList::CreateStructuredArray(), error(), lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject(), and lldb_private::python::PythonObject::get().
ScriptedPythonInterface::ExtractValueFromPythonObject< StructuredData::DictionarySP >()
template<> StructuredData::DictionarySP ScriptedPythonInterface::ExtractValueFromPythonObject< StructuredData::DictionarySP > (python::PythonObject & p, Status & error)
Definition at line 38 of file ScriptedPythonInterface.cpp.
References lldb_private::python::Borrowed, lldb_private::python::PythonDictionary::CreateStructuredDictionary(), error(), and lldb_private::ScriptedPythonInterface::ExtractValueFromPythonObject().