LLDB: SourceManager.cpp File Reference
SourceManager.cpp File Reference
#include "lldb/Core/SourceManager.h"
#include "lldb/Core/Address.h"
#include "lldb/Core/AddressRange.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/FormatEntity.h"
#include "lldb/Core/Highlighter.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleList.h"
#include "lldb/Host/FileSystem.h"
#include "lldb/Symbol/CompileUnit.h"
#include "lldb/Symbol/Function.h"
#include "lldb/Symbol/LineEntry.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Target/PathMappingList.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/AnsiTerminal.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/DataBuffer.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/RegularExpression.h"
#include "lldb/Utility/Stream.h"
#include "lldb/Utility/SupportFile.h"
#include "lldb/lldb-enumerations.h"
#include "llvm/ADT/Twine.h"
#include <future>
#include <memory>
#include <optional>
#include <utility>
#include <cassert>
#include <cstdio>
Namespaces
namespace lldb_private
A class that represents a running process on the host machine.
Functions
static bool is_newline_char (char ch)
static void resolve_tilde (FileSpec &file_spec)
static std::string toString (const Checksum &checksum)
static bool should_highlight_source (DebuggerSP debugger_sp)
static bool should_show_stop_column_with_ansi (DebuggerSP debugger_sp)
static bool should_show_stop_column_with_caret (DebuggerSP debugger_sp)
static bool should_show_stop_line_with_ansi (DebuggerSP debugger_sp)
Function Documentation
is_newline_char()
bool is_newline_char (char ch) inline static
Definition at line 56 of file SourceManager.cpp.
Referenced by lldb_private::SourceManager::File::CalculateLineOffsets(), and lldb_private::SourceManager::File::DisplaySourceLines().
resolve_tilde()
void resolve_tilde (FileSpec & file_spec) static
Definition at line 58 of file SourceManager.cpp.
References lldb_private::ConstString::GetCString(), lldb_private::FileSpec::GetDirectory(), lldb_private::FileSystem::Instance(), and lldb_private::FileSystem::Resolve().
Referenced by lldb_private::SourceManager::File::SetSupportFile().
should_highlight_source()
bool should_highlight_source (DebuggerSP debugger_sp) static
Definition at line 175 of file SourceManager.cpp.
Referenced by lldb_private::SourceManager::File::DisplaySourceLines().
should_show_stop_column_with_ansi()
bool should_show_stop_column_with_ansi (DebuggerSP debugger_sp) static
Definition at line 187 of file SourceManager.cpp.
References lldb::eStopShowColumnAnsi, and lldb::eStopShowColumnAnsiOrCaret.
Referenced by lldb_private::SourceManager::File::DisplaySourceLines().
should_show_stop_column_with_caret()
bool should_show_stop_column_with_caret (DebuggerSP debugger_sp) static
Definition at line 206 of file SourceManager.cpp.
References lldb::eStopShowColumnAnsiOrCaret, and lldb::eStopShowColumnCaret.
Referenced by lldb_private::SourceManager::DisplaySourceLinesWithLineNumbersUsingLastFile().
should_show_stop_line_with_ansi()
bool should_show_stop_line_with_ansi (DebuggerSP debugger_sp) static
Definition at line 223 of file SourceManager.cpp.
Referenced by lldb_private::SourceManager::DisplaySourceLinesWithLineNumbersUsingLastFile().
toString()
std::string toString (const Checksum & checksum) static
Definition at line 65 of file SourceManager.cpp.
References lldb_private::Checksum::digest().
Referenced by dump_type_value().