LLDB: Status.cpp File Reference
Status.cpp File Reference
#include "lldb/Utility/Status.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/VASPrintf.h"
#include "lldb/lldb-defines.h"
#include "lldb/lldb-enumerations.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Errno.h"
#include "llvm/Support/FormatProviders.h"
#include <cerrno>
#include <cstdarg>
#include <string>
#include <system_error>
#include <cstdint>
Namespaces
namespace llvm
Functions
static llvm::Error ErrorFromEnums (Status::ValueType err, ErrorType type, std::string msg)
static llvm::Error CloneError (const llvm::Error &error)
Creates a deep copy of all known errors and converts all other errors to a new llvm::StringError.
static ErrorType ErrorCodeToErrorType (std::error_code ec)
Function Documentation
CloneError()
llvm::Error CloneError (const llvm::Error & error) static
Creates a deep copy of all known errors and converts all other errors to a new llvm::StringError.
Definition at line 121 of file Status.cpp.
References lldb_private::clone(), and error().
Referenced by lldb_private::Status::ToError().
ErrorCodeToErrorType()
ErrorType ErrorCodeToErrorType (std::error_code ec) static
Definition at line 234 of file Status.cpp.
References lldb::eErrorTypeGeneric, lldb::eErrorTypeInvalid, and lldb::eErrorTypePOSIX.
Referenced by lldb_private::CloneableECError::GetErrorType(), and lldb_private::Status::GetType().
ErrorFromEnums()
llvm::Error ErrorFromEnums (Status::ValueType err, ErrorType type, std::string msg) static
Definition at line 61 of file Status.cpp.
References lldb::eErrorTypeMachKernel, lldb::eErrorTypePOSIX, and lldb::eErrorTypeWin32.
Referenced by lldb_private::Status::Status().