LLDB: Statistics.cpp File Reference
Statistics.cpp File Reference
#include "lldb/Target/Statistics.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Interpreter/CommandInterpreter.h"
#include "lldb/Symbol/SymbolFile.h"
#include "lldb/Target/DynamicLoader.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/UnixSignals.h"
#include "lldb/Utility/StructuredData.h"
Functions
static void EmplaceSafeString (llvm::json::Object &obj, llvm::StringRef key, const std::string &str)
static double elapsed (const StatsTimepoint &start, const StatsTimepoint &end)
Function Documentation
elapsed()
double elapsed (const StatsTimepoint & start, const StatsTimepoint & end) static
Definition at line 40 of file Statistics.cpp.
References elapsed().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARF::DebugAbbrev(), lldb_private::Symtab::Decode(), elapsed(), lldb_private::plugin::dwarf::DWARFUnit::ExtractDIEsRWLocked(), lldb_private::plugin::dwarf::DWARFUnit::ExtractUnitDIENoDwoIfNeeded(), lldb_private::ObjectFile::GetSymtab(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetTypeUnitSupportFiles(), lldb_private::CommandInterpreter::HandleCommand(), lldb_private::plugin::dwarf::ManualDWARFIndex::IndexImpl(), lldb_private::Symtab::InitNameIndexes(), lldb_private::PluginManager::LocateExecutableObjectFile(), lldb_private::PluginManager::LocateExecutableSymbolFile(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseDebugMacros(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseLineTable(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseSupportFiles(), ObjectFileELF::ParseSymtab(), lldb_private::platform_android::AdbClient::ReadMessageStream(), lldb_private::Breakpoint::ResolveBreakpoint(), lldb_private::Breakpoint::ResolveBreakpointInModules(), lldb_private::Breakpoint::ResolveBreakpointInModules(), lldb_private::Target::SetExecutableModule(), lldb_private::TargetStats::ToJSON(), and lldb_private::ElapsedTime::~ElapsedTime().
EmplaceSafeString()
void EmplaceSafeString (llvm::json::Object & obj, llvm::StringRef key, const std::string & str) static
Definition at line 26 of file Statistics.cpp.
Referenced by lldb_private::ModuleStats::ToJSON().