LLDB: StopInfoMachException.cpp File Reference
StopInfoMachException.cpp File Reference
#include "StopInfoMachException.h"
#include "lldb/lldb-forward.h"
#include "lldb/Breakpoint/Watchpoint.h"
#include "lldb/Symbol/Symbol.h"
#include "lldb/Target/ABI.h"
#include "lldb/Target/DynamicLoader.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Target/ThreadPlan.h"
#include "lldb/Target/UnixSignals.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/StreamString.h"
#include <optional>
Classes
struct PtrauthInstructionInfo
Information about a pointer-authentication related instruction.
Functions
static std::optional< PtrauthInstructionInfo > GetPtrauthInstructionInfo (Target &target, const ArchSpec &arch, const Address &at_addr)
Get any pointer-authentication related information about the instruction at address at_addr.
static void DescribeAddressBriefly (Stream &strm, const Address &addr, Target &target)
Describe the load address of addr using the format filename:line:col.
Variables
static constexpr uint8_t g_mte_tag_shift = 64 - 8
static constexpr addr_t g_mte_tag_mask = (addr_t)0x0f << g_mte_tag_shift
Function Documentation
DescribeAddressBriefly()
void DescribeAddressBriefly (Stream & strm, const Address & addr, Target & target) static
Describe the load address of addr using the format filename:line:col.
Definition at line 71 of file StopInfoMachException.cpp.
References lldb::eDescriptionLevelBrief, lldb_private::Address::GetDescription(), lldb_private::Address::GetLoadAddress(), lldb_private::StreamString::GetString(), and lldb_private::Stream::Printf().
Referenced by lldb_private::StopInfoMachException::DeterminePtrauthFailure().
GetPtrauthInstructionInfo()
std::optional< PtrauthInstructionInfo > GetPtrauthInstructionInfo (Target & target, const ArchSpec & arch, const Address & at_addr) static
Get any pointer-authentication related information about the instruction at address at_addr.
Definition at line 47 of file StopInfoMachException.cpp.
References lldb_private::Disassembler::DisassembleRange(), and lldb_private::InstructionList::GetInstructionAtIndex().
Referenced by lldb_private::StopInfoMachException::DeterminePtrauthFailure().
Variable Documentation
g_mte_tag_mask
addr_t g_mte_tag_mask = (addr_t)0x0f << g_mte_tag_shift static constexpr
Definition at line 94 of file StopInfoMachException.cpp.
Referenced by lldb_private::StopInfoMachException::DetermineTagMismatch().
g_mte_tag_shift
uint8_t g_mte_tag_shift = 64 - 8 static constexpr
Definition at line 93 of file StopInfoMachException.cpp.
Referenced by lldb_private::StopInfoMachException::DetermineTagMismatch().