LLDB: StringExtractorGDBRemote.cpp File Reference
StringExtractorGDBRemote.cpp File Reference
#include "lldb/Utility/StringExtractorGDBRemote.h"
#include <cctype>
#include <cstring>
#include <optional>
Macros
#define PACKET_MATCHES(s)
#define PACKET_STARTS_WITH(s)
Functions
static bool OKErrorNotSupportedResponseValidator (void *, const StringExtractorGDBRemote &response)
static bool JSONResponseValidator (void *, const StringExtractorGDBRemote &response)
static bool ASCIIHexBytesResponseValidator (void *, const StringExtractorGDBRemote &response)
Macro Definition Documentation
PACKET_MATCHES
#define PACKET_MATCHES (s)
Value:
  ((packet_size == (sizeof(s) - 1)) && (strcmp((packet_cstr), (s)) == 0))
Referenced by StringExtractorGDBRemote::GetServerPacketType().
PACKET_STARTS_WITH
#define PACKET_STARTS_WITH (s)
Value:
  ((packet_size >= (sizeof(s) - 1)) &&                                         \
   ::strncmp(packet_cstr, s, (sizeof(s) - 1)) == 0)
Referenced by StringExtractorGDBRemote::GetServerPacketType().
Function Documentation
ASCIIHexBytesResponseValidator()
bool ASCIIHexBytesResponseValidator (void * , const StringExtractorGDBRemote & response) static
Definition at line 575 of file StringExtractorGDBRemote.cpp.
References StringExtractorGDBRemote::eAck, StringExtractorGDBRemote::eError, StringExtractorGDBRemote::eNack, StringExtractorGDBRemote::eOK, StringExtractorGDBRemote::eResponse, StringExtractorGDBRemote::eUnsupported, StringExtractorGDBRemote::GetResponseType(), and StringExtractor::GetStringRef().
Referenced by StringExtractorGDBRemote::SetResponseValidatorToASCIIHexBytes().
JSONResponseValidator()
bool JSONResponseValidator (void * , const StringExtractorGDBRemote & response) static
Definition at line 543 of file StringExtractorGDBRemote.cpp.
References StringExtractorGDBRemote::eAck, StringExtractorGDBRemote::eError, StringExtractorGDBRemote::eNack, StringExtractorGDBRemote::eOK, StringExtractorGDBRemote::eResponse, StringExtractorGDBRemote::eUnsupported, StringExtractorGDBRemote::GetResponseType(), and StringExtractor::GetStringRef().
Referenced by StringExtractorGDBRemote::SetResponseValidatorToJSON().
OKErrorNotSupportedResponseValidator()
bool OKErrorNotSupportedResponseValidator (void * , const StringExtractorGDBRemote & response) static
Definition at line 527 of file StringExtractorGDBRemote.cpp.
References StringExtractorGDBRemote::eAck, StringExtractorGDBRemote::eError, StringExtractorGDBRemote::eNack, StringExtractorGDBRemote::eOK, StringExtractorGDBRemote::eResponse, StringExtractorGDBRemote::eUnsupported, and StringExtractorGDBRemote::GetResponseType().
Referenced by StringExtractorGDBRemote::SetResponseValidatorToOKErrorNotSupported().