LLDB: StringPrinter.cpp File Reference
StringPrinter.cpp File Reference
#include "lldb/DataFormatters/StringPrinter.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Target/Language.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/Status.h"
#include "lldb/ValueObject/ValueObject.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/ConvertUTF.h"
#include <cctype>
#include <locale>
#include <memory>
Classes
class DecodedCharBuffer
DecodedCharBuffer stores the decoded contents of a single character.
Namespaces
namespace lldb_private
A class that represents a running process on the host machine.
namespace lldb_private::formatters
Typedefs
using GetPrintableElementType = StringPrinter::GetPrintableElementType
using StringElementType = StringPrinter::StringElementType
using EscapingHelper
Functions
template<StringElementType type>
static DecodedCharBuffer GetPrintableImpl (uint8_t *buffer, uint8_t *buffer_end, uint8_t *&next, StringPrinter::EscapeStyle escape_style)
static bool isprint32 (char32_t codepoint)
DecodedCharBuffer attemptASCIIEscape (llvm::UTF32 c, StringPrinter::EscapeStyle escape_style)
template<>
DecodedCharBuffer GetPrintableImpl< StringElementType::ASCII > (uint8_t *buffer, uint8_t *buffer_end, uint8_t *&next, StringPrinter::EscapeStyle escape_style)
template<>
DecodedCharBuffer GetPrintableImpl< StringElementType::UTF8 > (uint8_t *buffer, uint8_t *buffer_end, uint8_t *&next, StringPrinter::EscapeStyle escape_style)
static DecodedCharBuffer GetPrintable (StringElementType type, uint8_t *buffer, uint8_t *buffer_end, uint8_t *&next, StringPrinter::EscapeStyle escape_style)
static EscapingHelper GetDefaultEscapingHelper (GetPrintableElementType elem_type, StringPrinter::EscapeStyle escape_style)
template<typename SourceDataType>
static bool DumpEncodedBufferToStream (GetPrintableElementType style, llvm::ConversionResult(*ConvertFunction)(const SourceDataType **, const SourceDataType *, llvm::UTF8 **, llvm::UTF8 *, llvm::ConversionFlags), const StringPrinter::ReadBufferAndDumpToStreamOptions &dump_options)
Read a string encoded in accordance with.
template<typename SourceDataType>
static bool lldb_private::formatters::ReadEncodedBufferAndDumpToStream (StringElementType elem_type, const StringPrinter::ReadStringAndDumpToStreamOptions &options, llvm::ConversionResult(*ConvertFunction)(const SourceDataType **, const SourceDataType *, llvm::UTF8 **, llvm::UTF8 *, llvm::ConversionFlags))
template<>
bool lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream< StringElementType::UTF8 > (const ReadStringAndDumpToStreamOptions &options)
template<>
bool lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream< StringElementType::UTF16 > (const ReadStringAndDumpToStreamOptions &options)
template<>
bool lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream< StringElementType::UTF32 > (const ReadStringAndDumpToStreamOptions &options)
template<>
bool lldb_private::formatters::StringPrinter::ReadStringAndDumpToStream< StringElementType::ASCII > (const ReadStringAndDumpToStreamOptions &options)
template<>
bool lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream< StringElementType::UTF8 > (const ReadBufferAndDumpToStreamOptions &options)
template<>
bool lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream< StringElementType::UTF16 > (const ReadBufferAndDumpToStreamOptions &options)
template<>
bool lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream< StringElementType::UTF32 > (const ReadBufferAndDumpToStreamOptions &options)
template<>
bool lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream< StringElementType::ASCII > (const ReadBufferAndDumpToStreamOptions &options)
Typedef Documentation
EscapingHelper
using EscapingHelper
Initial value:
    std::function<DecodedCharBuffer(uint8_t *, uint8_t *, uint8_t *&)>
Definition at line 58 of file StringPrinter.cpp.
GetPrintableElementType
using GetPrintableElementType = StringPrinter::GetPrintableElementType
Definition at line 28 of file StringPrinter.cpp.
StringElementType
using StringElementType = StringPrinter::StringElementType
Definition at line 29 of file StringPrinter.cpp.
Function Documentation
attemptASCIIEscape()
DecodedCharBuffer attemptASCIIEscape (llvm::UTF32 c, StringPrinter::EscapeStyle escape_style)
Definition at line 96 of file StringPrinter.cpp.
References lldb_private::formatters::StringPrinter::Swift.
Referenced by GetPrintableImpl< StringElementType::ASCII >(), and GetPrintableImpl< StringElementType::UTF8 >().
DumpEncodedBufferToStream()
template<typename SourceDataType> bool DumpEncodedBufferToStream (GetPrintableElementType style, llvm::ConversionResult(* ConvertFunction)(const SourceDataType **, const SourceDataType *, llvm::UTF8 **, llvm::UTF8 *, llvm::ConversionFlags), const StringPrinter::ReadBufferAndDumpToStreamOptions & dump_options) static
Read a string encoded in accordance with.
Template Parameters
SourceDataType from a host-side LLDB buffer, then pretty-print it to a stream using style.
Definition at line 256 of file StringPrinter.cpp.
References lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetBinaryZeroIsTerminator(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::GetData(), GetDefaultEscapingHelper(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetEscapeNonPrintables(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetEscapeStyle(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStreamOptions::GetIsTruncated(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetPrefixToken(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetQuote(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetSourceSize(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetStream(), lldb_private::formatters::StringPrinter::DumpToStreamOptions::GetSuffixToken(), and lldb_private::Stream::Printf().
Referenced by lldb_private::formatters::ReadEncodedBufferAndDumpToStream(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream< StringElementType::UTF16 >(), lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream< StringElementType::UTF32 >(), and lldb_private::formatters::StringPrinter::ReadBufferAndDumpToStream< StringElementType::UTF8 >().
GetDefaultEscapingHelper()
EscapingHelper GetDefaultEscapingHelper (GetPrintableElementType elem_type, StringPrinter::EscapeStyle escape_style) static
Definition at line 237 of file StringPrinter.cpp.
References GetPrintable().
Referenced by DumpEncodedBufferToStream().
GetPrintable()
DecodedCharBuffer GetPrintable (StringElementType type, uint8_t * buffer, uint8_t * buffer_end, uint8_t *& next, StringPrinter::EscapeStyle escape_style) static
Definition at line 218 of file StringPrinter.cpp.
References GetPrintableImpl< StringElementType::ASCII >(), and GetPrintableImpl< StringElementType::UTF8 >().
Referenced by GetDefaultEscapingHelper().
GetPrintableImpl()
template<StringElementType type> DecodedCharBuffer GetPrintableImpl (uint8_t * buffer, uint8_t * buffer_end, uint8_t *& next, StringPrinter::EscapeStyle escape_style) static
GetPrintableImpl< StringElementType::ASCII >()
template<> DecodedCharBuffer GetPrintableImpl< StringElementType::ASCII > (uint8_t * buffer, uint8_t * buffer_end, uint8_t *& next, StringPrinter::EscapeStyle escape_style)
Definition at line 136 of file StringPrinter.cpp.
References attemptASCIIEscape(), lldb_private::formatters::StringPrinter::CXX, DecodedCharBuffer::GetSize(), lldbassert, and lldb_private::formatters::StringPrinter::Swift.
Referenced by GetPrintable(), and GetPrintableImpl< StringElementType::UTF8 >().
GetPrintableImpl< StringElementType::UTF8 >()
template<> DecodedCharBuffer GetPrintableImpl< StringElementType::UTF8 > (uint8_t * buffer, uint8_t * buffer_end, uint8_t *& next, StringPrinter::EscapeStyle escape_style)
Definition at line 169 of file StringPrinter.cpp.
References attemptASCIIEscape(), lldb_private::formatters::StringPrinter::CXX, GetPrintableImpl< StringElementType::ASCII >(), DecodedCharBuffer::GetSize(), isprint32(), lldbassert, lldb_private::formatters::StringPrinter::Swift, and UNUSED_IF_ASSERT_DISABLED.
Referenced by GetPrintable().
isprint32()
bool isprint32 (char32_t codepoint) static
Definition at line 69 of file StringPrinter.cpp.
Referenced by GetPrintableImpl< StringElementType::UTF8 >().