LLDB: lldb_private::ClassDescriptorV2::ivar_list_t Struct Reference
lldb_private::ClassDescriptorV2::ivar_list_t Struct Reference
Public Member Functions
bool Read (Process *process, lldb::addr_t addr)
Public Attributes
uint32_t m_entsize
uint32_t m_count
lldb::addr_t m_first_ptr
Detailed Description
Definition at line 187 of file AppleObjCClassDescriptorV2.h.
Member Function Documentation
Read()
bool ClassDescriptorV2::ivar_list_t::Read (Process * process, lldb::addr_t addr)
Definition at line 367 of file AppleObjCClassDescriptorV2.cpp.
References error(), lldb_private::Process::GetAddressByteSize(), lldb_private::Process::GetByteOrder(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::DataExtractor::GetU32_unchecked(), m_count, m_entsize, m_first_ptr, and lldb_private::Process::ReadMemory().
Referenced by lldb_private::ClassDescriptorV2::Describe().
Member Data Documentation
m_count
uint32_t lldb_private::ClassDescriptorV2::ivar_list_t::m_count
Definition at line 189 of file AppleObjCClassDescriptorV2.h.
Referenced by lldb_private::ClassDescriptorV2::Describe(), and Read().
m_entsize
uint32_t lldb_private::ClassDescriptorV2::ivar_list_t::m_entsize
Definition at line 188 of file AppleObjCClassDescriptorV2.h.
Referenced by lldb_private::ClassDescriptorV2::Describe(), and Read().
m_first_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::ivar_list_t::m_first_ptr
Definition at line 190 of file AppleObjCClassDescriptorV2.h.
Referenced by lldb_private::ClassDescriptorV2::Describe(), and Read().
The documentation for this struct was generated from the following files:
AppleObjCClassDescriptorV2.h
AppleObjCClassDescriptorV2.cpp