LLDB: lldb_private::FormattersMatchCandidate::Flags Struct Reference
lldb_private::FormattersMatchCandidate::Flags Struct Reference
#include <FormatClasses.h>
Public Member Functions
Flags WithStrippedPointer ()
Flags WithStrippedReference ()
Flags WithStrippedTypedef ()
Public Attributes
bool stripped_pointer = false
bool stripped_reference = false
bool stripped_typedef = false
Detailed Description
Definition at line 50 of file FormatClasses.h.
Member Function Documentation
WithStrippedPointer()
Flags lldb_private::FormattersMatchCandidate::Flags::WithStrippedPointer () inline
Definition at line 56 of file FormatClasses.h.
References stripped_pointer.
Referenced by lldb_private::FormatManager::GetPossibleMatches().
WithStrippedReference()
Flags lldb_private::FormattersMatchCandidate::Flags::WithStrippedReference () inline
Definition at line 63 of file FormatClasses.h.
References stripped_reference.
Referenced by lldb_private::FormatManager::GetPossibleMatches().
WithStrippedTypedef()
Flags lldb_private::FormattersMatchCandidate::Flags::WithStrippedTypedef () inline
Definition at line 70 of file FormatClasses.h.
References stripped_typedef.
Referenced by lldb_private::FormatManager::GetPossibleMatches().
Member Data Documentation
stripped_pointer
bool lldb_private::FormattersMatchCandidate::Flags::stripped_pointer = false
Definition at line 51 of file FormatClasses.h.
Referenced by WithStrippedPointer().
stripped_reference
bool lldb_private::FormattersMatchCandidate::Flags::stripped_reference = false
Definition at line 52 of file FormatClasses.h.
Referenced by WithStrippedReference().
stripped_typedef
bool lldb_private::FormattersMatchCandidate::Flags::stripped_typedef = false
Definition at line 53 of file FormatClasses.h.
Referenced by WithStrippedTypedef().
The documentation for this struct was generated from the following file:
FormatClasses.h