LLDB: lldb_private::Rs Struct Reference
lldb_private::Rs Struct Reference
#include <RISCVInstructions.h>
Public Member Functions
std::optional< uint64_t > Read (EmulateInstructionRISCV &emulator)
std::optional< int32_t > ReadI32 (EmulateInstructionRISCV &emulator)
std::optional< int64_t > ReadI64 (EmulateInstructionRISCV &emulator)
std::optional< uint32_t > ReadU32 (EmulateInstructionRISCV &emulator)
std::optional< llvm::APFloat > ReadAPFloat (EmulateInstructionRISCV &emulator, bool isDouble)
Public Attributes
uint32_t rs
Detailed Description
Definition at line 28 of file RISCVInstructions.h.
Member Function Documentation
Read()
std::optional< uint64_t > lldb_private::Rs::Read (EmulateInstructionRISCV & emulator)
Definition at line 149 of file EmulateInstructionRISCV.cpp.
References lldb::eRegisterKindLLDB, lldb_private::RegisterValue::GetAsUInt64(), lldb_private::GPREncodingToLLDB(), lldb_private::EmulateInstruction::ReadRegister(), and rs.
Referenced by lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), lldb_private::Executor::operator()(), ReadI32(), ReadI64(), and ReadU32().
ReadAPFloat()
std::optional< APFloat > lldb_private::Rs::ReadAPFloat (EmulateInstructionRISCV & emulator, bool isDouble)
Definition at line 172 of file EmulateInstructionRISCV.cpp.
References lldb_private::bits(), lldb::eRegisterKindLLDB, lldb_private::FPREncodingToLLDB(), lldb_private::RegisterValue::GetAsUInt64(), lldb_private::EmulateInstruction::ReadRegister(), and rs.
ReadI32()
std::optional< int32_t > lldb_private::Rs::ReadI32 (EmulateInstructionRISCV & emulator)
Definition at line 157 of file EmulateInstructionRISCV.cpp.
References Read().
Referenced by lldb_private::Executor::operator()(), and lldb_private::Executor::operator()().
ReadI64()
std::optional< int64_t > lldb_private::Rs::ReadI64 (EmulateInstructionRISCV & emulator)
Definition at line 162 of file EmulateInstructionRISCV.cpp.
References Read().
Referenced by lldb_private::Executor::operator()(), and lldb_private::Executor::operator()().
ReadU32()
std::optional< uint32_t > lldb_private::Rs::ReadU32 (EmulateInstructionRISCV & emulator)
Definition at line 167 of file EmulateInstructionRISCV.cpp.
References Read().
Referenced by lldb_private::Executor::operator()(), and lldb_private::Executor::operator()().
Member Data Documentation
rs
uint32_t lldb_private::Rs::rs
Definition at line 29 of file RISCVInstructions.h.
Referenced by Read(), and ReadAPFloat().
The documentation for this struct was generated from the following files:
RISCVInstructions.h
EmulateInstructionRISCV.cpp