LLDB: lldb_private::ValueObject::GetValueForExpressionPathOptions Struct Reference
lldb_private::ValueObject::GetValueForExpressionPathOptions Struct Reference
#include <ValueObject.h>
Public Types
enum class SyntheticChildrenTraversal { None , ToSynthetic , FromSynthetic , Both }
Public Member Functions
GetValueForExpressionPathOptions (bool dot=false, bool no_ivar=false, bool bitfield=true, SyntheticChildrenTraversal synth_traverse=SyntheticChildrenTraversal::ToSynthetic)
GetValueForExpressionPathOptions & DoCheckDotVsArrowSyntax ()
GetValueForExpressionPathOptions & DontCheckDotVsArrowSyntax ()
GetValueForExpressionPathOptions & DoAllowFragileIVar ()
GetValueForExpressionPathOptions & DontAllowFragileIVar ()
GetValueForExpressionPathOptions & DoAllowBitfieldSyntax ()
GetValueForExpressionPathOptions & DontAllowBitfieldSyntax ()
GetValueForExpressionPathOptions & SetSyntheticChildrenTraversal (SyntheticChildrenTraversal traverse)
Static Public Member Functions
static const GetValueForExpressionPathOptions DefaultOptions ()
Public Attributes
bool m_check_dot_vs_arrow_syntax
bool m_no_fragile_ivar
bool m_allow_bitfields_syntax
SyntheticChildrenTraversal m_synthetic_children_traversal
Detailed Description
Definition at line 196 of file ValueObject.h.
Member Enumeration Documentation
SyntheticChildrenTraversal
enum class lldb_private::ValueObject::GetValueForExpressionPathOptions::SyntheticChildrenTraversal strong
Enumerator
None
ToSynthetic
FromSynthetic
Both
Definition at line 197 of file ValueObject.h.
Constructor & Destructor Documentation
GetValueForExpressionPathOptions()
lldb_private::ValueObject::GetValueForExpressionPathOptions::GetValueForExpressionPathOptions (bool dot = false, bool no_ivar = false, bool bitfield = true, SyntheticChildrenTraversal synth_traverse = SyntheticChildrenTraversal::ToSynthetic) inline
Definition at line 209 of file ValueObject.h.
References m_allow_bitfields_syntax, m_check_dot_vs_arrow_syntax, m_no_fragile_ivar, m_synthetic_children_traversal, and ToSynthetic.
Referenced by DefaultOptions(), DoAllowBitfieldSyntax(), DoAllowFragileIVar(), DoCheckDotVsArrowSyntax(), DontAllowBitfieldSyntax(), DontAllowFragileIVar(), and DontCheckDotVsArrowSyntax().
Member Function Documentation
DefaultOptions()
const GetValueForExpressionPathOptions lldb_private::ValueObject::GetValueForExpressionPathOptions::DefaultOptions () inline static
Definition at line 253 of file ValueObject.h.
References GetValueForExpressionPathOptions().
DoAllowBitfieldSyntax()
GetValueForExpressionPathOptions & lldb_private::ValueObject::GetValueForExpressionPathOptions::DoAllowBitfieldSyntax () inline
Definition at line 237 of file ValueObject.h.
References GetValueForExpressionPathOptions(), and m_allow_bitfields_syntax.
Referenced by lldb_private::FormatEntity::Formatter::DumpValue().
DoAllowFragileIVar()
GetValueForExpressionPathOptions & lldb_private::ValueObject::GetValueForExpressionPathOptions::DoAllowFragileIVar () inline
Definition at line 227 of file ValueObject.h.
References GetValueForExpressionPathOptions(), and m_no_fragile_ivar.
Referenced by lldb_private::FormatEntity::Formatter::DumpValue().
DoCheckDotVsArrowSyntax()
GetValueForExpressionPathOptions & lldb_private::ValueObject::GetValueForExpressionPathOptions::DoCheckDotVsArrowSyntax () inline
Definition at line 217 of file ValueObject.h.
References GetValueForExpressionPathOptions(), and m_check_dot_vs_arrow_syntax.
DontAllowBitfieldSyntax()
GetValueForExpressionPathOptions & lldb_private::ValueObject::GetValueForExpressionPathOptions::DontAllowBitfieldSyntax () inline
Definition at line 242 of file ValueObject.h.
References GetValueForExpressionPathOptions(), and m_allow_bitfields_syntax.
DontAllowFragileIVar()
GetValueForExpressionPathOptions & lldb_private::ValueObject::GetValueForExpressionPathOptions::DontAllowFragileIVar () inline
Definition at line 232 of file ValueObject.h.
References GetValueForExpressionPathOptions(), and m_no_fragile_ivar.
DontCheckDotVsArrowSyntax()
GetValueForExpressionPathOptions & lldb_private::ValueObject::GetValueForExpressionPathOptions::DontCheckDotVsArrowSyntax () inline
Definition at line 222 of file ValueObject.h.
References GetValueForExpressionPathOptions(), and m_check_dot_vs_arrow_syntax.
Referenced by lldb_private::FormatEntity::Formatter::DumpValue().
SetSyntheticChildrenTraversal()
GetValueForExpressionPathOptions & lldb_private::ValueObject::GetValueForExpressionPathOptions::SetSyntheticChildrenTraversal (SyntheticChildrenTraversal traverse) inline
Definition at line 248 of file ValueObject.h.
References m_synthetic_children_traversal.
Referenced by lldb_private::FormatEntity::Formatter::DumpValue().
Member Data Documentation
m_allow_bitfields_syntax
bool lldb_private::ValueObject::GetValueForExpressionPathOptions::m_allow_bitfields_syntax
Definition at line 206 of file ValueObject.h.
Referenced by DoAllowBitfieldSyntax(), DontAllowBitfieldSyntax(), lldb_private::ValueObject::GetValueForExpressionPath_Impl(), and GetValueForExpressionPathOptions().
m_check_dot_vs_arrow_syntax
bool lldb_private::ValueObject::GetValueForExpressionPathOptions::m_check_dot_vs_arrow_syntax
Definition at line 204 of file ValueObject.h.
Referenced by DoCheckDotVsArrowSyntax(), DontCheckDotVsArrowSyntax(), lldb_private::ValueObject::GetValueForExpressionPath_Impl(), and GetValueForExpressionPathOptions().
m_no_fragile_ivar
bool lldb_private::ValueObject::GetValueForExpressionPathOptions::m_no_fragile_ivar
Definition at line 205 of file ValueObject.h.
Referenced by DoAllowFragileIVar(), DontAllowFragileIVar(), lldb_private::ValueObject::GetValueForExpressionPath_Impl(), and GetValueForExpressionPathOptions().
m_synthetic_children_traversal
SyntheticChildrenTraversal lldb_private::ValueObject::GetValueForExpressionPathOptions::m_synthetic_children_traversal
Definition at line 207 of file ValueObject.h.
Referenced by lldb_private::ValueObject::GetValueForExpressionPath(), lldb_private::ValueObject::GetValueForExpressionPath_Impl(), GetValueForExpressionPathOptions(), and SetSyntheticChildrenTraversal().
The documentation for this struct was generated from the following file:
ValueObject.h