LLDB: lldb_private::StringSummaryFormat Struct Reference
lldb_private::StringSummaryFormat Struct Reference
#include <TypeSummary.h>
Public Member Functions
StringSummaryFormat (const TypeSummaryImpl::Flags &flags, const char *f, uint32_t ptr_match_depth=1)
~StringSummaryFormat () override=default
const char * GetSummaryString () const
void SetSummaryString (const char *f)
bool FormatObject (ValueObject *valobj, std::string &dest, const TypeSummaryOptions &options) override
std::string GetDescription () override
std::string GetName () override
Get the name of the Type Summary Provider, either a C++ class, a summary string, or a script function name.
Public Member Functions inherited from lldb_private::TypeSummaryImpl
virtual ~TypeSummaryImpl ()=default
Kind GetKind () const
bool Cascades () const
bool SkipsPointers () const
bool SkipsReferences () const
bool NonCacheable () const
virtual bool DoesPrintChildren (ValueObject *valobj) const
virtual bool DoesPrintEmptyAggregates () const
virtual bool DoesPrintValue (ValueObject *valobj) const
bool IsOneLiner () const
virtual bool HideNames (ValueObject *valobj) const
void SetCascades (bool value)
void SetSkipsPointers (bool value)
void SetSkipsReferences (bool value)
virtual void SetDoesPrintChildren (bool value)
virtual void SetDoesPrintValue (bool value)
void SetIsOneLiner (bool value)
virtual void SetHideNames (bool value)
virtual void SetNonCacheable (bool value)
uint32_t GetOptions ()
void SetOptions (uint32_t value)
uint32_t GetPtrMatchDepth ()
void SetPtrMatchDepth (uint32_t value)
virtual std::string GetSummaryKindName ()
Get the name of the kind of Summary Provider, either c++, summary string, script or python.
uint32_t & GetRevision ()
Static Public Member Functions
static bool classof (const TypeSummaryImpl *S)
Public Attributes
std::string m_format_str
FormatEntity::Entry m_format
Status m_error
Private Member Functions
StringSummaryFormat (const StringSummaryFormat &)=delete
const StringSummaryFormat & operator= (const StringSummaryFormat &)=delete
Additional Inherited Members
Public Types inherited from lldb_private::TypeSummaryImpl
enum class Kind {
eSummaryString , eScript , eBytecode , eCallback ,
eInternal
}
typedef std::shared_ptr< TypeSummaryImpl > SharedPointer
Protected Member Functions inherited from lldb_private::TypeSummaryImpl
TypeSummaryImpl (Kind kind, const TypeSummaryImpl::Flags &flags, uint32_t ptr_match_depth=1)
Protected Attributes inherited from lldb_private::TypeSummaryImpl
uint32_t m_my_revision = 0
Flags m_flags
Detailed Description
Definition at line 296 of file TypeSummary.h.
Constructor & Destructor Documentation
StringSummaryFormat() [1/2]
StringSummaryFormat::StringSummaryFormat (const TypeSummaryImpl::Flags & flags, const char * f, uint32_t ptr_match_depth = 1)
Definition at line 67 of file TypeSummary.cpp.
References lldb_private::TypeSummaryImpl::eSummaryString, m_format_str, SetSummaryString(), and lldb_private::TypeSummaryImpl::TypeSummaryImpl().
Referenced by operator=(), and StringSummaryFormat().
~StringSummaryFormat()
lldb_private::StringSummaryFormat::~StringSummaryFormat () override default
StringSummaryFormat() [2/2]
lldb_private::StringSummaryFormat::StringSummaryFormat (const StringSummaryFormat &) private delete
References StringSummaryFormat().
Member Function Documentation
classof()
bool lldb_private::StringSummaryFormat::classof (const TypeSummaryImpl * S) inline static
Definition at line 317 of file TypeSummary.h.
References lldb_private::TypeSummaryImpl::eSummaryString, and lldb_private::TypeSummaryImpl::TypeSummaryImpl().
FormatObject()
bool StringSummaryFormat::FormatObject (ValueObject * valobj, std::string & dest, const TypeSummaryOptions & options) override virtual
Implements lldb_private::TypeSummaryImpl.
Definition at line 86 of file TypeSummary.cpp.
References lldb_private::FormatEntity::Formatter::Format(), lldb_private::AddressRange::GetBaseAddress(), lldb_private::ValueObject::GetExecutionContextRef(), lldb_private::ExecutionContext::GetFramePtr(), lldb_private::StreamString::GetString(), lldb_private::StackFrame::GetSymbolContext(), lldb_private::TypeSummaryImpl::HideNames(), lldb_private::TypeSummaryImpl::IsOneLiner(), lldb_private::SymbolContext::line_entry, m_format, lldb_private::ValueObjectPrinter::PrintChildrenOneLiner(), and lldb_private::LineEntry::range.
Referenced by lldb_private::FormatEntity::PrettyPrintFunctionArguments().
GetDescription()
std::string StringSummaryFormat::GetDescription () override virtual
Implements lldb_private::TypeSummaryImpl.
Definition at line 121 of file TypeSummary.cpp.
References lldb_private::TypeSummaryImpl::Cascades(), lldb_private::TypeSummaryImpl::DoesPrintChildren(), lldb_private::TypeSummaryImpl::DoesPrintValue(), lldb_private::TypeSummaryImpl::GetPtrMatchDepth(), lldb_private::StreamString::GetString(), lldb_private::TypeSummaryImpl::HideNames(), lldb_private::TypeSummaryImpl::IsOneLiner(), m_error, m_format_str, lldb_private::Stream::Printf(), lldb_private::TypeSummaryImpl::SkipsPointers(), and lldb_private::TypeSummaryImpl::SkipsReferences().
GetName()
std::string StringSummaryFormat::GetName () override virtual
Get the name of the Type Summary Provider, either a C++ class, a summary string, or a script function name.
Implements lldb_private::TypeSummaryImpl.
Definition at line 138 of file TypeSummary.cpp.
References m_format_str.
GetSummaryString()
const char * lldb_private::StringSummaryFormat::GetSummaryString () const inline
Definition at line 306 of file TypeSummary.h.
References m_format_str.
operator=()
const StringSummaryFormat & lldb_private::StringSummaryFormat::operator= (const StringSummaryFormat &) private delete
References StringSummaryFormat().
SetSummaryString()
void StringSummaryFormat::SetSummaryString (const char * f)
Definition at line 75 of file TypeSummary.cpp.
References m_error, m_format, m_format_str, and lldb_private::FormatEntity::Parse().
Referenced by StringSummaryFormat().
Member Data Documentation
m_error
Status lldb_private::StringSummaryFormat::m_error
Definition at line 299 of file TypeSummary.h.
Referenced by GetDescription(), and SetSummaryString().
m_format
FormatEntity::Entry lldb_private::StringSummaryFormat::m_format
Definition at line 298 of file TypeSummary.h.
Referenced by FormatObject(), and SetSummaryString().
m_format_str
std::string lldb_private::StringSummaryFormat::m_format_str
Definition at line 297 of file TypeSummary.h.
Referenced by GetDescription(), GetName(), GetSummaryString(), SetSummaryString(), and StringSummaryFormat().
The documentation for this struct was generated from the following files:
TypeSummary.h
TypeSummary.cpp