LLDB: LibCxx Struct Reference
LibCxx Struct Reference
Static Public Member Functions
static ValueObjectSP GetStartMember (ValueObject &backend)
static ValueObjectSP GetSizeMember (ValueObject &backend)
Detailed Description
Definition at line 32 of file GenericInitializerList.cpp.
Member Function Documentation
GetSizeMember()
ValueObjectSP LibCxx::GetSizeMember (ValueObject & backend) inline static
Definition at line 37 of file GenericInitializerList.cpp.
References lldb_private::ValueObject::GetChildMemberWithName().
GetStartMember()
ValueObjectSP LibCxx::GetStartMember (ValueObject & backend) inline static
Definition at line 33 of file GenericInitializerList.cpp.
References lldb_private::ValueObject::GetChildMemberWithName().
Referenced by lldb_private::formatters::GenericInitializerListSyntheticFrontEndCreator().
The documentation for this struct was generated from the following file:
GenericInitializerList.cpp