LLDB: lldb_private::SharedCacheImageInfo Struct Reference
lldb_private::SharedCacheImageInfo Struct Reference
#include <HostInfoBase.h>
Public Member Functions
SharedCacheImageInfo ()
SharedCacheImageInfo (ConstString filename, UUID uuid, lldb::DataExtractorSP extractor_sp)
SharedCacheImageInfo (ConstString filename, UUID uuid, lldb::DataExtractorSP(*create_data_extractor)(void *image), void *image_baton)
lldb::DataExtractorSP GetExtractor ()
ConstString GetFilename () const
const UUID & GetUUID () const
void * GetImageBaton ()
void SetExtractor (lldb::DataExtractorSP extractor_sp)
void SetImageBaton (void *image_baton)
void SetDataExtractorCreateFunction (lldb::DataExtractorSP(*create_data_extractor)(void *image))
Private Attributes
ConstString m_filename
UUID m_uuid
lldb::DataExtractorSP m_extractor_sp
lldb::DataExtractorSP(* m_create_data_extractor)(void *image)
void * m_image_baton
Detailed Description
Definition at line 31 of file HostInfoBase.h.
Constructor & Destructor Documentation
SharedCacheImageInfo() [1/3]
lldb_private::SharedCacheImageInfo::SharedCacheImageInfo () inline
Definition at line 32 of file HostInfoBase.h.
References m_create_data_extractor, m_extractor_sp, m_filename, m_image_baton, and m_uuid.
SharedCacheImageInfo() [2/3]
lldb_private::SharedCacheImageInfo::SharedCacheImageInfo (ConstString filename, UUID uuid, lldb::DataExtractorSP extractor_sp) inline
Definition at line 35 of file HostInfoBase.h.
References m_create_data_extractor, m_extractor_sp, m_filename, m_image_baton, and m_uuid.
SharedCacheImageInfo() [3/3]
lldb_private::SharedCacheImageInfo::SharedCacheImageInfo (ConstString filename, UUID uuid, lldb::DataExtractorSP(* create_data_extractor)(void *image), void * image_baton) inline
Definition at line 39 of file HostInfoBase.h.
References m_create_data_extractor, m_extractor_sp, m_filename, m_image_baton, and m_uuid.
Member Function Documentation
GetExtractor()
lldb::DataExtractorSP lldb_private::SharedCacheImageInfo::GetExtractor () inline
Definition at line 47 of file HostInfoBase.h.
References m_create_data_extractor, m_extractor_sp, and m_image_baton.
Referenced by lldb_private::DynamicLoaderDarwin::FindTargetModuleForImageInfo(), and lldb_private::PlatformDarwin::GetModuleFromSharedCaches().
GetFilename()
ConstString lldb_private::SharedCacheImageInfo::GetFilename () const inline
Definition at line 52 of file HostInfoBase.h.
References m_filename.
GetImageBaton()
void * lldb_private::SharedCacheImageInfo::GetImageBaton ()
GetUUID()
const UUID & lldb_private::SharedCacheImageInfo::GetUUID () const inline
Definition at line 53 of file HostInfoBase.h.
References m_uuid.
Referenced by lldb_private::DynamicLoaderDarwin::FindTargetModuleForImageInfo(), lldb_private::PlatformDarwin::GetModuleFromSharedCaches(), lldb_private::SymbolLocatorDebugSymbols::LocateExecutableObjectFile(), and LocateMacOSXFilesUsingDebugSymbols().
SetDataExtractorCreateFunction()
void lldb_private::SharedCacheImageInfo::SetDataExtractorCreateFunction (lldb::DataExtractorSP(* create_data_extractor)(void *image))
SetExtractor()
void lldb_private::SharedCacheImageInfo::SetExtractor (lldb::DataExtractorSP extractor_sp) inline
Definition at line 55 of file HostInfoBase.h.
References m_extractor_sp.
SetImageBaton()
void lldb_private::SharedCacheImageInfo::SetImageBaton (void * image_baton) inline
Definition at line 58 of file HostInfoBase.h.
References m_image_baton.
Member Data Documentation
m_create_data_extractor
lldb::DataExtractorSP(* lldb_private::SharedCacheImageInfo::m_create_data_extractor) (void *image) private
Definition at line 66 of file HostInfoBase.h.
Referenced by GetExtractor(), SharedCacheImageInfo(), SharedCacheImageInfo(), and SharedCacheImageInfo().
m_extractor_sp
lldb::DataExtractorSP lldb_private::SharedCacheImageInfo::m_extractor_sp private
Definition at line 65 of file HostInfoBase.h.
Referenced by GetExtractor(), SetExtractor(), SharedCacheImageInfo(), SharedCacheImageInfo(), and SharedCacheImageInfo().
m_filename
ConstString lldb_private::SharedCacheImageInfo::m_filename private
Definition at line 63 of file HostInfoBase.h.
Referenced by GetFilename(), SharedCacheImageInfo(), SharedCacheImageInfo(), and SharedCacheImageInfo().
m_image_baton
void* lldb_private::SharedCacheImageInfo::m_image_baton private
Definition at line 67 of file HostInfoBase.h.
Referenced by GetExtractor(), SetImageBaton(), SharedCacheImageInfo(), SharedCacheImageInfo(), and SharedCacheImageInfo().
m_uuid
UUID lldb_private::SharedCacheImageInfo::m_uuid private
Definition at line 64 of file HostInfoBase.h.
Referenced by GetUUID(), SharedCacheImageInfo(), SharedCacheImageInfo(), and SharedCacheImageInfo().
The documentation for this struct was generated from the following file:
HostInfoBase.h