LLDB: lldb_private::DumpValueObjectOptions::PointerDepth Struct Reference
lldb_private::DumpValueObjectOptions::PointerDepth Struct Reference
#include <DumpValueObjectOptions.h>
Public Member Functions
PointerDepth Decremented () const
bool CanAllowExpansion () const
Public Attributes
uint32_t m_count = 0
Detailed Description
Definition at line 24 of file DumpValueObjectOptions.h.
Member Function Documentation
CanAllowExpansion()
bool DumpValueObjectOptions::PointerDepth::CanAllowExpansion () const
Definition at line 501 of file ValueObjectPrinter.cpp.
References m_count.
Referenced by lldb_private::ValueObjectPrinter::PrintChildrenIfNeeded(), and lldb_private::ValueObjectPrinter::ShouldPrintChildren().
Decremented()
PointerDepth lldb_private::DumpValueObjectOptions::PointerDepth::Decremented () const inline
Definition at line 27 of file DumpValueObjectOptions.h.
References m_count.
Referenced by lldb_private::ValueObjectPrinter::PrintChild().
Member Data Documentation
m_count
uint32_t lldb_private::DumpValueObjectOptions::PointerDepth::m_count = 0
Definition at line 25 of file DumpValueObjectOptions.h.
Referenced by CanAllowExpansion(), and Decremented().
The documentation for this struct was generated from the following files:
DumpValueObjectOptions.h
ValueObjectPrinter.cpp