LLDB: ELFNote Struct Reference
ELFNote Struct Reference
#include <ObjectFileELF.h>
Public Member Functions
ELFNote ()=default
bool Parse (const lldb_private::DataExtractor &data, lldb::offset_t *offset)
Parse an ELFNote entry from the given DataExtractor starting at position offset.
size_t GetByteSize () const
Public Attributes
elf::elf_word n_namesz = 0
elf::elf_word n_descsz = 0
elf::elf_word n_type = 0
std::string n_name
Detailed Description
Definition at line 25 of file ObjectFileELF.h.
Constructor & Destructor Documentation
ELFNote()
ELFNote::ELFNote () default
Member Function Documentation
GetByteSize()
size_t ELFNote::GetByteSize () const inline
Definition at line 48 of file ObjectFileELF.h.
References n_descsz, and n_namesz.
Parse()
bool ELFNote::Parse (const lldb_private::DataExtractor & data, lldb::offset_t * offset)
Parse an ELFNote entry from the given DataExtractor starting at position offset.
Parameters
[in] data The DataExtractor to read from.
[in,out] offset Pointer to an offset in the data. On return the offset will be advanced by the number of bytes read.
Returns
True if the ELFRel entry was successfully read and false otherwise.
Definition at line 250 of file ObjectFileELF.cpp.
References lldb_private::DataExtractor::ExtractBytes(), lldb_private::DataExtractor::GetByteOrder(), lldb_private::DataExtractor::GetCStr(), lldb_private::GetLog(), lldb_private::DataExtractor::GetU32(), LLDB_LOGF, n_name, n_namesz, and lldb_private::Symbols.
Member Data Documentation
n_descsz
elf::elf_word ELFNote::n_descsz = 0
Definition at line 27 of file ObjectFileELF.h.
Referenced by GetByteSize().
n_name
std::string ELFNote::n_name
Definition at line 30 of file ObjectFileELF.h.
Referenced by Parse().
n_namesz
elf::elf_word ELFNote::n_namesz = 0
Definition at line 26 of file ObjectFileELF.h.
Referenced by GetByteSize(), and Parse().
n_type
elf::elf_word ELFNote::n_type = 0
Definition at line 28 of file ObjectFileELF.h.
Referenced by lldb_private::getRegset().
The documentation for this struct was generated from the following files:
ObjectFileELF.h
ObjectFileELF.cpp