LLDB: lldb_private::CTFModifier Struct Reference
lldb_private::CTFModifier Struct Reference
#include <CTFTypes.h>
Public Attributes
uint32_t type
Public Attributes inherited from lldb_private::CTFType
Kind kind
lldb::user_id_t uid
llvm::StringRef name
Protected Member Functions
CTFModifier (Kind kind, lldb::user_id_t uid, uint32_t type)
Static Protected Member Functions
static bool classof (const CTFType *T)
Additional Inherited Members
Public Types inherited from lldb_private::CTFType
enum Kind : uint32_t {
eUnknown = 0 , eInteger = 1 , eFloat = 2 , ePointer = 3 ,
eArray = 4 , eFunction = 5 , eStruct = 6 , eUnion = 7 ,
eEnum = 8 , eForward = 9 , eTypedef = 10 , eVolatile = 11 ,
eConst = 12 , eRestrict = 13 , eSlice = 14
}
Public Member Functions inherited from lldb_private::CTFType
CTFType (Kind kind, lldb::user_id_t uid, llvm::StringRef name)
Detailed Description
Definition at line 55 of file CTFTypes.h.
Constructor & Destructor Documentation
CTFModifier()
lldb_private::CTFModifier::CTFModifier (Kind kind, lldb::user_id_t uid, uint32_t type) inline protected
Definition at line 57 of file CTFTypes.h.
References lldb_private::CTFType::CTFType(), lldb_private::CTFType::kind, type, and lldb_private::CTFType::uid.
Referenced by lldb_private::CTFConst::CTFConst(), lldb_private::CTFPointer::CTFPointer(), lldb_private::CTFRestrict::CTFRestrict(), and lldb_private::CTFVolatile::CTFVolatile().
Member Function Documentation
classof()
bool lldb_private::CTFModifier::classof (const CTFType * T) inline static protected
Definition at line 60 of file CTFTypes.h.
References lldb_private::CTFType::CTFType(), lldb_private::CTFType::eConst, lldb_private::CTFType::ePointer, lldb_private::CTFType::eRestrict, and lldb_private::CTFType::eVolatile.
Member Data Documentation
type
uint32_t lldb_private::CTFModifier::type
Definition at line 66 of file CTFTypes.h.
Referenced by lldb_private::SymbolFileCTF::CreateModifier(), lldb_private::CTFConst::CTFConst(), CTFModifier(), lldb_private::CTFPointer::CTFPointer(), lldb_private::CTFRestrict::CTFRestrict(), and lldb_private::CTFVolatile::CTFVolatile().
The documentation for this struct was generated from the following file:
CTFTypes.h