LLDB: lldb_private::CPlusPlusNameParser::Range Struct Reference
lldb_private::CPlusPlusNameParser::Range Struct Reference
Public Member Functions
Range ()=default
Range (size_t begin, size_t end)
size_t size () const
bool empty () const
Public Attributes
size_t begin_index = 0
size_t end_index = 0
Detailed Description
Definition at line 69 of file CPlusPlusNameParser.h.
Constructor & Destructor Documentation
Range() [1/2]
lldb_private::CPlusPlusNameParser::Range::Range () default
Range() [2/2]
lldb_private::CPlusPlusNameParser::Range::Range (size_t begin, size_t end) inline
Definition at line 74 of file CPlusPlusNameParser.h.
References begin_index, and end_index.
Member Function Documentation
empty()
bool lldb_private::CPlusPlusNameParser::Range::empty () const inline
Definition at line 80 of file CPlusPlusNameParser.h.
References size().
Referenced by lldb_private::CPlusPlusNameParser::GetTextForRange().
size()
size_t lldb_private::CPlusPlusNameParser::Range::size () const inline
Definition at line 78 of file CPlusPlusNameParser.h.
References begin_index, and end_index.
Referenced by empty().
Member Data Documentation
begin_index
size_t lldb_private::CPlusPlusNameParser::Range::begin_index = 0
Definition at line 70 of file CPlusPlusNameParser.h.
Referenced by lldb_private::CPlusPlusNameParser::GetTextForRange(), Range(), and size().
end_index
size_t lldb_private::CPlusPlusNameParser::Range::end_index = 0
Definition at line 71 of file CPlusPlusNameParser.h.
Referenced by lldb_private::CPlusPlusNameParser::GetTextForRange(), Range(), and size().
The documentation for this struct was generated from the following file:
CPlusPlusNameParser.h