LLDB: llvm::DenseMapInfo< lldb_private::UUID > Struct Reference
llvm::DenseMapInfo< lldb_private::UUID > Struct Reference
DenseMapInfo implementation.
#include <UUID.h>
Static Public Member Functions
static lldb_private::UUID getEmptyKey ()
static lldb_private::UUID getTombstoneKey ()
static unsigned getHashValue (lldb_private::UUID uuid)
static bool isEqual (lldb_private::UUID LHS, lldb_private::UUID RHS)
Detailed Description
DenseMapInfo implementation.
Definition at line 122 of file UUID.h.
Member Function Documentation
getEmptyKey()
lldb_private::UUID llvm::DenseMapInfo< lldb_private::UUID >::getEmptyKey () inline static
Definition at line 123 of file UUID.h.
getHashValue()
unsigned llvm::DenseMapInfo< lldb_private::UUID >::getHashValue (lldb_private::UUID uuid) inline static
Definition at line 129 of file UUID.h.
References lldb_private::UUID::GetBytes(), and getHashValue().
Referenced by getHashValue().
getTombstoneKey()
lldb_private::UUID llvm::DenseMapInfo< lldb_private::UUID >::getTombstoneKey () inline static
Definition at line 126 of file UUID.h.
isEqual()
bool llvm::DenseMapInfo< lldb_private::UUID >::isEqual (lldb_private::UUID LHS, lldb_private::UUID RHS) inline static
Definition at line 132 of file UUID.h.
The documentation for this struct was generated from the following file:
UUID.h