LLDB: llvm::DenseMapInfo< lldb_private::FileSpec > Struct Reference
llvm::DenseMapInfo< lldb_private::FileSpec > Struct Reference
DenseMapInfo implementation.
#include <FileSpec.h>
Static Public Member Functions
static lldb_private::FileSpec getEmptyKey ()
static lldb_private::FileSpec getTombstoneKey ()
static unsigned getHashValue (lldb_private::FileSpec file_spec)
static bool isEqual (lldb_private::FileSpec LHS, lldb_private::FileSpec RHS)
Detailed Description
DenseMapInfo implementation.
Definition at line 472 of file FileSpec.h.
Member Function Documentation
getEmptyKey()
lldb_private::FileSpec llvm::DenseMapInfo< lldb_private::FileSpec >::getEmptyKey () inline static
Definition at line 473 of file FileSpec.h.
getHashValue()
unsigned llvm::DenseMapInfo< lldb_private::FileSpec >::getHashValue (lldb_private::FileSpec file_spec) inline static
Definition at line 479 of file FileSpec.h.
References lldb_private::FileSpec::GetDirectory(), lldb_private::FileSpec::GetFilename(), and lldb_private::FileSpec::GetPathStyle().
getTombstoneKey()
lldb_private::FileSpec llvm::DenseMapInfo< lldb_private::FileSpec >::getTombstoneKey () inline static
Definition at line 476 of file FileSpec.h.
isEqual()
bool llvm::DenseMapInfo< lldb_private::FileSpec >::isEqual (lldb_private::FileSpec LHS, lldb_private::FileSpec RHS) inline static
Definition at line 488 of file FileSpec.h.
The documentation for this struct was generated from the following file:
FileSpec.h