LLDB: lldb_private::ClangUtil Struct Reference
lldb_private::ClangUtil Struct Reference
#include <ClangUtil.h>
Static Public Member Functions
static bool IsClangType (const CompilerType &ct)
static clang::Decl * GetDecl (const CompilerDecl &decl)
Returns the clang::Decl of the given CompilerDecl.
static clang::QualType GetQualType (const CompilerType &ct)
static clang::QualType GetCanonicalQualType (const CompilerType &ct)
static CompilerType RemoveFastQualifiers (const CompilerType &ct)
static clang::TagDecl * GetAsTagDecl (const CompilerType &type)
static std::string DumpDecl (const clang::Decl *d)
Returns a textual representation of the given Decl's AST.
static std::string ToString (const clang::Type *t)
Returns a textual representation of the given type.
static std::string ToString (const CompilerType &c)
Returns a textual representation of the given CompilerType (assuming its underlying type is a Clang type).
Detailed Description
Definition at line 24 of file ClangUtil.h.
Member Function Documentation
DumpDecl()
std::string ClangUtil::DumpDecl (const clang::Decl * d) static
Returns a textual representation of the given Decl's AST.
Does not deserialize any child nodes.
Definition at line 68 of file ClangUtil.cpp.
Referenced by lldb_private::ClangExpressionDeclMap::AddContextClassType(), lldb_private::ClangExpressionDeclMap::AddOneFunction(), lldb_private::ClangExpressionDeclMap::AddOneGenericVariable(), lldb_private::ClangExpressionDeclMap::AddOneRegister(), lldb_private::ClangExpressionDeclMap::AddOneVariable(), lldb_private::ClangExpressionDeclMap::AddOneVariable(), lldb_private::ClangExpressionDeclMap::AddOneVariable(), lldb_private::AppleObjCExternalASTSource::CompleteType(), lldb_private::AppleObjCExternalASTSource::CompleteType(), lldb_private::ClangASTSource::CompleteType(), lldb_private::ClangASTSource::FindExternalLexicalDecls(), lldb_private::ClangASTSource::FindObjCMethodDecls(), lldb_private::ClangASTSource::FindObjCMethodDeclsWithOrigin(), lldb_private::ClangASTSource::FindObjCPropertyAndIvarDeclsWithOrigin(), and lldb_private::AppleObjCDeclVendor::FinishDecl().
GetAsTagDecl()
clang::TagDecl * ClangUtil::GetAsTagDecl (const CompilerType & type) static
Definition at line 60 of file ClangUtil.cpp.
References GetCanonicalQualType().
Referenced by DWARFASTParserClang::CompleteTypeFromDWARF(), lldb_private::TypeSystemClang::GetAsTagDecl(), and lldb_private::TypeSystemClang::RequireCompleteType().
GetCanonicalQualType()
QualType ClangUtil::GetCanonicalQualType (const CompilerType & ct) static
Definition at line 44 of file ClangUtil.cpp.
References GetQualType(), and IsClangType().
Referenced by lldb_private::ClangASTImporter::CanImport(), lldb_private::TypeSystemClang::DumpTypeName(), lldb_private::TypeSystemClang::GetAsEnumDecl(), lldb_private::TypeSystemClang::GetAsObjCInterfaceDecl(), lldb_private::TypeSystemClang::GetAsRecordDecl(), GetAsTagDecl(), lldb_private::TypeSystemClang::GetCXXClassName(), lldb_private::ClangASTImporter::Import(), lldb_private::TypeSystemClang::IsCXXClassType(), lldb_private::TypeSystemClang::IsObjCClassType(), lldb_private::TypeSystemClang::IsObjCObjectOrInterfaceType(), and lldb_private::TypeSystemClang::IsObjCObjectPointerType().
GetDecl()
clang::Decl * ClangUtil::GetDecl (const CompilerDecl & decl) static
Returns the clang::Decl of the given CompilerDecl.
CompilerDecl has to be valid and represent a clang::Decl.
Definition at line 31 of file ClangUtil.cpp.
References lldb_private::CompilerDecl::GetOpaqueDecl(), and lldb_private::CompilerDecl::GetTypeSystem().
Referenced by lldb_private::ClangASTSource::FindDeclInModules(), lldb_private::ClangASTSource::FindDeclInObjCRuntime(), lldb_private::ClangASTSource::FindObjCMethodDecls(), lldb_private::ClangASTSource::FindObjCPropertyAndIvarDecls(), lldb_private::npdb::PdbAstBuilderClang::FromCompilerDecl(), lldb_private::ClangExpressionDeclMap::LookupFunction(), and lldb_private::ClangExpressionDeclMap::LookupInModulesDeclVendor().
GetQualType()
QualType ClangUtil::GetQualType (const CompilerType & ct) static
Definition at line 36 of file ClangUtil.cpp.
References lldb_private::CompilerType::GetOpaqueQualType(), and IsClangType().
Referenced by PDBASTParser::AddEnumValue(), lldb_private::TypeSystemClang::AddFieldToRecordType(), lldb_private::NameSearchContext::AddFunDecl(), lldb_private::TypeSystemClang::AddMethodToCXXRecordType(), lldb_private::TypeSystemClang::AddMethodToObjCObjectType(), lldb_private::TypeSystemClang::AddObjCClassProperty(), lldb_private::NameSearchContext::AddTypeDecl(), lldb_private::NameSearchContext::AddVarDecl(), lldb_private::TypeSystemClang::AddVariableToRecordType(), lldb_private::TypeSystemClang::AreTypesSame(), lldb_private::AppleObjCTypeEncodingParser::BuildAggregate(), lldb_private::AppleObjCTypeEncodingParser::BuildArray(), ObjCRuntimeMethodType::BuildMethod(), lldb_private::AppleObjCTypeEncodingParser::BuildObjCObjectPointerType(), lldb_private::TypeSystemClang::CompleteTagDeclarationDefinition(), lldb_private::ClangASTImporter::CopyType(), lldb_private::TypeSystemClang::CreateArrayType(), lldb_private::TypeSystemClang::CreateEnumerationType(), lldb_private::TypeSystemClang::CreateFunctionDeclaration(), lldb_private::TypeSystemClang::CreateFunctionType(), lldb_private::TypeSystemClang::CreateMemberPointerType(), lldb_private::TypeSystemClang::CreateParameterDeclaration(), lldb_private::ClangASTImporter::DeportType(), lldb_private::TypeSystemClang::DumpFromSymbolFile(), lldb_private::TypeSystemClang::DumpTypeDescription(), DWARFASTParserClang::ExtractIntFromFormValue(), lldb_private::ClangASTSource::FindCompleteType(), lldb_private::AppleObjCDeclVendor::FinishDecl(), lldb_private::npdb::PdbAstBuilderClang::FromCompilerType(), lldb_private::TypeSystemClang::GetAsTypedefDecl(), lldb_private::TypeSystemClang::GetBuiltinTypeForDWARFEncodingAndBitSize(), GetCanonicalQualType(), DWARFASTParserClang::GetClangDeclForDIE(), lldb_private::TypeSystemClang::GetDeclarationName(), lldb_private::TypeSystemClang::GetDeclContextForType(), PDBASTParser::GetDeclForSymbol(), lldb_private::TypeSystemClang::GetEnumerationIntegerType(), lldb_private::ClangASTSource::GuardedCopyType(), lldb_private::TypeSystemClang::IsTemplateType(), lldb_private::ClangExpressionDeclMap::LookUpLldbClass(), MakeAPValue(), IRForTarget::MaybeHandleVariable(), DWARFASTParserClang::ParseArrayType(), DWARFASTParserClang::ParseSubroutine(), DWARFASTParserClang::ParseTemplateDIE(), DWARFASTParserClang::ParseTypeFromClangModule(), PrepareContextToReceiveMembers(), RemoveFastQualifiers(), lldb_private::TypeSystemClang::StartTagDeclarationDefinition(), and ToString().
IsClangType()
bool ClangUtil::IsClangType (const CompilerType & ct) static
Definition at line 17 of file ClangUtil.cpp.
References lldb_private::CompilerType::GetOpaqueQualType(), and lldb_private::CompilerType::GetTypeSystem().
Referenced by lldb_private::NameSearchContext::AddTypeDecl(), lldb_private::ClangASTImporter::CanImport(), lldb_private::TypeSystemClang::CreateFunctionType(), lldb_private::TypeSystemClang::DumpTypeName(), lldb_private::ClangASTSource::FindCompleteType(), GetCanonicalQualType(), lldb_private::ObjCLanguage::GetPossibleFormattersMatches(), GetQualType(), lldb_private::ClangASTImporter::Import(), lldb_private::TypeSystemClang::IsObjCClassType(), lldb_private::TypeSystemClang::IsObjCObjectOrInterfaceType(), lldb_private::TypeSystemClang::IsObjCObjectPointerType(), and RemoveFastQualifiers().
RemoveFastQualifiers()
CompilerType ClangUtil::RemoveFastQualifiers (const CompilerType & ct) static
Definition at line 51 of file ClangUtil.cpp.
References GetQualType(), lldb_private::CompilerType::GetTypeSystem(), and IsClangType().
Referenced by lldb_private::ClangASTImporter::CanImport(), lldb_private::plugin::dwarf::SymbolFileDWARF::CompleteType(), lldb_private::TypeSystemClang::DumpTypeName(), lldb_private::TypeSystemClang::GetTypeForFormatters(), lldb_private::plugin::dwarf::SymbolFileDWARF::HasForwardDeclForCompilerType(), lldb_private::ClangASTImporter::Import(), and DWARFASTParserClang::ParseStructureLikeDIE().
ToString() [1/2]
std::string ClangUtil::ToString (const clang::Type * t) static
Returns a textual representation of the given type.
Definition at line 80 of file ClangUtil.cpp.
Referenced by lldb_private::ClangExpressionDeclMap::AddContextClassType(), lldb_private::ClangExpressionDeclMap::AddOneVariable(), lldb_private::ClangExpressionDeclMap::AddOneVariable(), and lldb_private::ClangExpressionDeclMap::LookUpLldbObjCClass().
ToString() [2/2]
std::string ClangUtil::ToString (const CompilerType & c) static
Returns a textual representation of the given CompilerType (assuming its underlying type is a Clang type).
Definition at line 84 of file ClangUtil.cpp.
References GetQualType().
The documentation for this struct was generated from the following files:
ClangUtil.h
ClangUtil.cpp