LLDB: lldb_private::SourceLanguage Struct Reference
lldb_private::SourceLanguage Struct Reference
A type-erased pair of llvm::dwarf::SourceLanguageName and version.
#include <lldb-private-types.h>
Public Member Functions
SourceLanguage ()=default
SourceLanguage (lldb::LanguageType language_type)
SourceLanguage (uint16_t name, uint32_t version)
SourceLanguage (std::optional< std::pair< uint16_t, uint32_t > > name_vers)
operator bool () const
lldb::LanguageType AsLanguageType () const
llvm::StringRef GetDescription () const
bool IsC () const
bool IsObjC () const
bool IsCPlusPlus () const
Public Attributes
uint16_t name = 0
uint32_t version = 0
Detailed Description
A type-erased pair of llvm::dwarf::SourceLanguageName and version.
Definition at line 103 of file lldb-private-types.h.
Constructor & Destructor Documentation
SourceLanguage() [1/4]
lldb_private::SourceLanguage::SourceLanguage () default
SourceLanguage() [2/4]
SourceLanguage::SourceLanguage (lldb::LanguageType language_type) explicit
Definition at line 605 of file Language.cpp.
References name, ToDwarfSourceLanguage(), and version.
SourceLanguage() [3/4]
lldb_private::SourceLanguage::SourceLanguage (uint16_t name, uint32_t version) inline
Definition at line 107 of file lldb-private-types.h.
References name, and version.
SourceLanguage() [4/4]
lldb_private::SourceLanguage::SourceLanguage (std::optional< std::pair< uint16_t, uint32_t > > name_vers) inline explicit
Definition at line 110 of file lldb-private-types.h.
References name, and version.
Member Function Documentation
AsLanguageType()
lldb::LanguageType SourceLanguage::AsLanguageType () const
Definition at line 618 of file Language.cpp.
References lldb::eLanguageTypeUnknown, name, and version.
Referenced by lldb_private::ClangExpressionParser::ClangExpressionParser(), CommandObjectTypeLookup::CommandObjectTypeLookup(), lldb_private::CommandObjectDWIMPrint::DoExecute(), lldb_private::UserExpression::Evaluate(), lldb_private::StackFrame::GetLanguageSpecificData(), lldb_private::Target::GetUserExpressionForLanguage(), lldb::SBFrame::GuessLanguage(), lldb_private::ClangDynamicCheckerFunctions::Install(), and SetupLangOpts().
GetDescription()
llvm::StringRef SourceLanguage::GetDescription () const
Definition at line 625 of file Language.cpp.
References name, and version.
Referenced by lldb_private::Language::GetDisplayNameForLanguageType(), and lldb_private::Target::GetUserExpressionForLanguage().
IsC()
bool SourceLanguage::IsC () const
Definition at line 629 of file Language.cpp.
References name.
IsCPlusPlus()
bool SourceLanguage::IsCPlusPlus () const
Definition at line 635 of file Language.cpp.
References name.
IsObjC()
bool SourceLanguage::IsObjC () const
Definition at line 631 of file Language.cpp.
References name.
Referenced by lldb_private::CommandObjectDWIMPrint::DoExecute().
operator bool()
lldb_private::SourceLanguage::operator bool () const inline explicit
Definition at line 115 of file lldb-private-types.h.
References name.
Member Data Documentation
name
uint16_t lldb_private::SourceLanguage::name = 0
Definition at line 122 of file lldb-private-types.h.
Referenced by AsLanguageType(), lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::EvaluateExpression(), GetDescription(), IsC(), IsCPlusPlus(), IsObjC(), operator bool(), SourceLanguage(), SourceLanguage(), and SourceLanguage().
version
uint32_t lldb_private::SourceLanguage::version = 0
Definition at line 123 of file lldb-private-types.h.
Referenced by AsLanguageType(), lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::EvaluateExpression(), lldb::SBFrame::EvaluateExpression(), GetDescription(), SourceLanguage(), SourceLanguage(), and SourceLanguage().
The documentation for this struct was generated from the following files:
lldb-private-types.h
Language.cpp