LLDB: lldb_private::ClassDescriptorV2::objc_class_t Struct Reference
lldb_private::ClassDescriptorV2::objc_class_t Struct Reference
Public Member Functions
objc_class_t ()=default
void Clear ()
bool Read (Process *process, lldb::addr_t addr)
Public Attributes
ObjCLanguageRuntime::ObjCISA m_isa = 0
ObjCLanguageRuntime::ObjCISA m_superclass = 0
lldb::addr_t m_cache_ptr = 0
lldb::addr_t m_vtable_ptr = 0
lldb::addr_t m_data_ptr = 0
uint8_t m_flags = 0
Detailed Description
Definition at line 82 of file AppleObjCClassDescriptorV2.h.
Constructor & Destructor Documentation
objc_class_t()
lldb_private::ClassDescriptorV2::objc_class_t::objc_class_t () default
Member Function Documentation
Clear()
void lldb_private::ClassDescriptorV2::objc_class_t::Clear () inline
Definition at line 92 of file AppleObjCClassDescriptorV2.h.
References m_cache_ptr, m_data_ptr, m_flags, m_isa, m_superclass, and m_vtable_ptr.
Read()
bool ClassDescriptorV2::objc_class_t::Read (Process * process, lldb::addr_t addr)
Definition at line 47 of file AppleObjCClassDescriptorV2.cpp.
References error(), lldb_private::Process::GetABI(), lldb_private::DataExtractor::GetAddress_unchecked(), lldb_private::Process::GetAddressByteSize(), lldb_private::Process::GetByteOrder(), lldb_private::WritableDataBuffer::GetBytes(), GetClassDataMask(), m_cache_ptr, m_data_ptr, m_flags, m_isa, m_superclass, m_vtable_ptr, and lldb_private::Process::ReadMemory().
Member Data Documentation
m_cache_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::objc_class_t::m_cache_ptr = 0
Definition at line 85 of file AppleObjCClassDescriptorV2.h.
Referenced by Clear(), and Read().
m_data_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::objc_class_t::m_data_ptr = 0
Definition at line 87 of file AppleObjCClassDescriptorV2.h.
Referenced by Clear(), Read(), and lldb_private::ClassDescriptorV2::Read_class_row().
m_flags
uint8_t lldb_private::ClassDescriptorV2::objc_class_t::m_flags = 0
Definition at line 88 of file AppleObjCClassDescriptorV2.h.
Referenced by Clear(), and Read().
m_isa
ObjCLanguageRuntime::ObjCISA lldb_private::ClassDescriptorV2::objc_class_t::m_isa = 0
Definition at line 83 of file AppleObjCClassDescriptorV2.h.
Referenced by Clear(), and Read().
m_superclass
ObjCLanguageRuntime::ObjCISA lldb_private::ClassDescriptorV2::objc_class_t::m_superclass = 0
Definition at line 84 of file AppleObjCClassDescriptorV2.h.
Referenced by Clear(), and Read().
m_vtable_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::objc_class_t::m_vtable_ptr = 0
Definition at line 86 of file AppleObjCClassDescriptorV2.h.
Referenced by Clear(), and Read().
The documentation for this struct was generated from the following files:
AppleObjCClassDescriptorV2.h
AppleObjCClassDescriptorV2.cpp