LLDB: lldb_private::ClassDescriptorV2::ivar_t Struct Reference
lldb_private::ClassDescriptorV2::ivar_t Struct Reference
Public Member Functions
bool Read (Process *process, lldb::addr_t addr)
Static Public Member Functions
static size_t GetSize (Process *process)
Public Attributes
lldb::addr_t m_offset_ptr
lldb::addr_t m_name_ptr
lldb::addr_t m_type_ptr
uint32_t m_alignment
uint32_t m_size
std::string m_name
std::string m_type
Detailed Description
Definition at line 195 of file AppleObjCClassDescriptorV2.h.
Member Function Documentation
GetSize()
size_t lldb_private::ClassDescriptorV2::ivar_t::GetSize (Process * process) inline static
Definition at line 205 of file AppleObjCClassDescriptorV2.h.
References lldb_private::Process::GetAddressByteSize().
Referenced by lldb_private::ClassDescriptorV2::Describe(), and Read().
Read()
bool ClassDescriptorV2::ivar_t::Read (Process * process, lldb::addr_t addr)
Definition at line 391 of file AppleObjCClassDescriptorV2.cpp.
References error(), lldb_private::DataExtractor::GetAddress_unchecked(), lldb_private::Process::GetAddressByteSize(), lldb_private::Process::GetByteOrder(), lldb_private::WritableDataBuffer::GetBytes(), GetSize(), lldb_private::DataExtractor::GetU32_unchecked(), m_alignment, m_name, m_name_ptr, m_offset_ptr, m_size, m_type, m_type_ptr, lldb_private::Process::ReadCStringFromMemory(), and lldb_private::Process::ReadMemory().
Referenced by lldb_private::ClassDescriptorV2::Describe().
Member Data Documentation
m_alignment
uint32_t lldb_private::ClassDescriptorV2::ivar_t::m_alignment
Definition at line 199 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_name
std::string lldb_private::ClassDescriptorV2::ivar_t::m_name
Definition at line 202 of file AppleObjCClassDescriptorV2.h.
Referenced by lldb_private::ClassDescriptorV2::Describe(), and Read().
m_name_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::ivar_t::m_name_ptr
Definition at line 197 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_offset_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::ivar_t::m_offset_ptr
Definition at line 196 of file AppleObjCClassDescriptorV2.h.
Referenced by lldb_private::ClassDescriptorV2::Describe(), and Read().
m_size
uint32_t lldb_private::ClassDescriptorV2::ivar_t::m_size
Definition at line 200 of file AppleObjCClassDescriptorV2.h.
Referenced by lldb_private::ClassDescriptorV2::Describe(), and Read().
m_type
std::string lldb_private::ClassDescriptorV2::ivar_t::m_type
Definition at line 203 of file AppleObjCClassDescriptorV2.h.
Referenced by lldb_private::ClassDescriptorV2::Describe(), and Read().
m_type_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::ivar_t::m_type_ptr
Definition at line 198 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
The documentation for this struct was generated from the following files:
AppleObjCClassDescriptorV2.h
AppleObjCClassDescriptorV2.cpp