LLDB: PlatformXRSimulator Struct Reference
PlatformXRSimulator Struct Reference
XRSimulator Plugin.
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static PlatformSP CreateInstance (bool force, const ArchSpec *arch)
Detailed Description
XRSimulator Plugin.
Definition at line 610 of file PlatformAppleSimulator.cpp.
Member Function Documentation
CreateInstance()
PlatformSP PlatformXRSimulator::CreateInstance (bool force, const ArchSpec * arch) inline static
Definition at line 620 of file PlatformAppleSimulator.cpp.
References CoreSimulatorSupport::DeviceType::appleXR, lldb_private::PlatformAppleSimulator::CreateInstance(), g_xros_description, g_xros_plugin_name, and lldb_private::XcodeSDK::XRSimulator.
Referenced by Initialize(), and Terminate().
Initialize()
void PlatformXRSimulator::Initialize () inline static
Definition at line 611 of file PlatformAppleSimulator.cpp.
References CreateInstance(), g_xros_description, g_xros_plugin_name, and lldb_private::PluginManager::RegisterPlugin().
Referenced by lldb_private::PlatformAppleSimulator::Initialize().
Terminate()
void PlatformXRSimulator::Terminate () inline static
Definition at line 616 of file PlatformAppleSimulator.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Referenced by lldb_private::PlatformAppleSimulator::Terminate().
The documentation for this struct was generated from the following file:
PlatformAppleSimulator.cpp