LLDB: StructuredData.cpp File Reference
StructuredData.cpp File Reference
#include "lldb/Utility/StructuredData.h"
#include "lldb/Utility/FileSpec.h"
#include "lldb/Utility/Status.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/MemoryBuffer.h"
#include <cerrno>
#include <cinttypes>
#include <cstdlib>
Functions
static StructuredData::ObjectSP ParseJSONValue (json::Value &value)
static StructuredData::ObjectSP ParseJSONObject (json::Object *object)
static StructuredData::ObjectSP ParseJSONArray (json::Array *array)
Function Documentation
ParseJSONArray()
StructuredData::ObjectSP ParseJSONArray (json::Array * array) static
Definition at line 97 of file StructuredData.cpp.
References ParseJSONValue().
Referenced by ParseJSONValue().
ParseJSONObject()
StructuredData::ObjectSP ParseJSONObject (json::Object * object) static
Definition at line 86 of file StructuredData.cpp.
References ParseJSONValue().
Referenced by ParseJSONValue().
ParseJSONValue()
StructuredData::ObjectSP ParseJSONValue (json::Value & value) static
Definition at line 58 of file StructuredData.cpp.
References ParseJSONArray(), and ParseJSONObject().
Referenced by lldb_private::StructuredData::ParseJSON(), ParseJSONArray(), lldb_private::StructuredData::ParseJSONFromFile(), and ParseJSONObject().