LLDB: lldb_private::telemetry::LLDBBaseTelemetryInfo Struct Reference
lldb_private::telemetry::LLDBBaseTelemetryInfo Struct Reference
#include <Telemetry.h>
Public Member Functions
llvm::telemetry::KindType getKind () const override
void serialize (llvm::telemetry::Serializer &serializer) const override
Static Public Member Functions
static bool classof (const llvm::telemetry::TelemetryInfo *t)
Public Attributes
SteadyTimePoint start_time
Start time of an event.
std::optional< SteadyTimePoint > end_time
End time of an event - may be empty if not meaningful.
lldb::user_id_t debugger_id = LLDB_INVALID_UID
Debugger * debugger = nullptr
Detailed Description
Definition at line 77 of file Telemetry.h.
Member Function Documentation
classof()
bool lldb_private::telemetry::LLDBBaseTelemetryInfo::classof (const llvm::telemetry::TelemetryInfo * t) inline static
Definition at line 92 of file Telemetry.h.
References lldb_private::telemetry::LLDBEntryKind::BaseInfo.
getKind()
llvm::telemetry::KindType lldb_private::telemetry::LLDBBaseTelemetryInfo::getKind () const inline override
Definition at line 88 of file Telemetry.h.
References lldb_private::telemetry::LLDBEntryKind::BaseInfo.
Referenced by serialize().
serialize()
void lldb_private::telemetry::LLDBBaseTelemetryInfo::serialize (llvm::telemetry::Serializer & serializer) const override
Definition at line 47 of file Telemetry.cpp.
References end_time, getKind(), start_time, and lldb_private::telemetry::ToNanosec().
Referenced by lldb_private::telemetry::ClientInfo::serialize(), lldb_private::telemetry::CommandInfo::serialize(), lldb_private::telemetry::DebuggerInfo::serialize(), lldb_private::telemetry::ExecutableModuleInfo::serialize(), and lldb_private::telemetry::ProcessExitInfo::serialize().
Member Data Documentation
debugger
Debugger* lldb_private::telemetry::LLDBBaseTelemetryInfo::debugger = nullptr
Definition at line 85 of file Telemetry.h.
Referenced by lldb_private::Debugger::Clear(), lldb_private::telemetry::TelemetryManager::DispatchClientTelemetry(), and lldb_private::telemetry::TelemetryManager::preDispatch().
debugger_id
lldb::user_id_t lldb_private::telemetry::LLDBBaseTelemetryInfo::debugger_id = LLDB_INVALID_UID
Definition at line 84 of file Telemetry.h.
Referenced by lldb_private::telemetry::TelemetryManager::preDispatch().
end_time
std::optional<SteadyTimePoint> lldb_private::telemetry::LLDBBaseTelemetryInfo::end_time
End time of an event - may be empty if not meaningful.
Definition at line 81 of file Telemetry.h.
Referenced by lldb_private::telemetry::TelemetryManager::DispatchClientTelemetry(), and serialize().
start_time
SteadyTimePoint lldb_private::telemetry::LLDBBaseTelemetryInfo::start_time
Start time of an event.
Definition at line 79 of file Telemetry.h.
Referenced by lldb_private::telemetry::TelemetryManager::DispatchClientTelemetry(), and serialize().
The documentation for this struct was generated from the following files:
Telemetry.h
Telemetry.cpp