LLDB: lldb_private::CXXFunctionSummaryFormat Struct Reference
lldb_private::CXXFunctionSummaryFormat Struct Reference
#include <TypeSummary.h>
Public Types
typedef std::function< bool(ValueObject &, Stream &, const TypeSummaryOptions &)> Callback
typedef std::shared_ptr< CXXFunctionSummaryFormat > SharedPointer
Public Types inherited from lldb_private::TypeSummaryImpl
enum class Kind {
eSummaryString , eScript , eBytecode , eCallback ,
eInternal
}
typedef std::shared_ptr< TypeSummaryImpl > SharedPointer
Public Member Functions
CXXFunctionSummaryFormat (const TypeSummaryImpl::Flags &flags, Callback impl, const char *description, uint32_t ptr_match_depth=1)
~CXXFunctionSummaryFormat () override=default
Callback GetBackendFunction () const
const char * GetTextualInfo () const
void SetBackendFunction (Callback cb_func)
void SetTextualInfo (const char *descr)
bool FormatObject (ValueObject *valobj, std::string &dest, const TypeSummaryOptions &options) override
std::string GetDescription () override
std::string GetName () override
Get the name of the Type Summary Provider, either a C++ class, a summary string, or a script function name.
Public Member Functions inherited from lldb_private::TypeSummaryImpl
virtual ~TypeSummaryImpl ()=default
Kind GetKind () const
bool Cascades () const
bool SkipsPointers () const
bool SkipsReferences () const
bool NonCacheable () const
virtual bool DoesPrintChildren (ValueObject *valobj) const
virtual bool DoesPrintEmptyAggregates () const
virtual bool DoesPrintValue (ValueObject *valobj) const
bool IsOneLiner () const
virtual bool HideNames (ValueObject *valobj) const
void SetCascades (bool value)
void SetSkipsPointers (bool value)
void SetSkipsReferences (bool value)
virtual void SetDoesPrintChildren (bool value)
virtual void SetDoesPrintValue (bool value)
void SetIsOneLiner (bool value)
virtual void SetHideNames (bool value)
virtual void SetNonCacheable (bool value)
uint32_t GetOptions ()
void SetOptions (uint32_t value)
uint32_t GetPtrMatchDepth ()
void SetPtrMatchDepth (uint32_t value)
virtual std::string GetSummaryKindName ()
Get the name of the kind of Summary Provider, either c++, summary string, script or python.
uint32_t & GetRevision ()
Static Public Member Functions
static bool classof (const TypeSummaryImpl *S)
Public Attributes
Callback m_impl
std::string m_description
Private Member Functions
CXXFunctionSummaryFormat (const CXXFunctionSummaryFormat &)=delete
const CXXFunctionSummaryFormat & operator= (const CXXFunctionSummaryFormat &)=delete
Additional Inherited Members
Protected Member Functions inherited from lldb_private::TypeSummaryImpl
TypeSummaryImpl (Kind kind, const TypeSummaryImpl::Flags &flags, uint32_t ptr_match_depth=1)
Protected Attributes inherited from lldb_private::TypeSummaryImpl
uint32_t m_my_revision = 0
Flags m_flags
Detailed Description
Definition at line 327 of file TypeSummary.h.
Member Typedef Documentation
Callback
typedef std::function<bool(ValueObject &, Stream &, const TypeSummaryOptions &)> lldb_private::CXXFunctionSummaryFormat::Callback
Definition at line 332 of file TypeSummary.h.
SharedPointer
typedef std::shared_ptr<CXXFunctionSummaryFormat> lldb_private::CXXFunctionSummaryFormat::SharedPointer
Definition at line 367 of file TypeSummary.h.
Constructor & Destructor Documentation
CXXFunctionSummaryFormat() [1/2]
CXXFunctionSummaryFormat::CXXFunctionSummaryFormat (const TypeSummaryImpl::Flags & flags, Callback impl, const char * description, uint32_t ptr_match_depth = 1)
Definition at line 140 of file TypeSummary.cpp.
References lldb_private::TypeSummaryImpl::eCallback, m_description, m_impl, and lldb_private::TypeSummaryImpl::TypeSummaryImpl().
Referenced by CXXFunctionSummaryFormat(), and operator=().
~CXXFunctionSummaryFormat()
lldb_private::CXXFunctionSummaryFormat::~CXXFunctionSummaryFormat () override default
CXXFunctionSummaryFormat() [2/2]
lldb_private::CXXFunctionSummaryFormat::CXXFunctionSummaryFormat (const CXXFunctionSummaryFormat &) private delete
References CXXFunctionSummaryFormat().
Member Function Documentation
classof()
bool lldb_private::CXXFunctionSummaryFormat::classof (const TypeSummaryImpl * S) inline static
Definition at line 361 of file TypeSummary.h.
References lldb_private::TypeSummaryImpl::eCallback, and lldb_private::TypeSummaryImpl::TypeSummaryImpl().
FormatObject()
bool CXXFunctionSummaryFormat::FormatObject (ValueObject * valobj, std::string & dest, const TypeSummaryOptions & options) override virtual
Implements lldb_private::TypeSummaryImpl.
Definition at line 146 of file TypeSummary.cpp.
References lldb_private::StreamString::GetString(), and m_impl.
GetBackendFunction()
Callback lldb_private::CXXFunctionSummaryFormat::GetBackendFunction () const inline
Definition at line 343 of file TypeSummary.h.
References m_impl.
GetDescription()
std::string CXXFunctionSummaryFormat::GetDescription () override virtual
Implements lldb_private::TypeSummaryImpl.
Definition at line 157 of file TypeSummary.cpp.
References lldb_private::TypeSummaryImpl::Cascades(), lldb_private::TypeSummaryImpl::DoesPrintChildren(), lldb_private::TypeSummaryImpl::DoesPrintValue(), lldb_private::TypeSummaryImpl::GetPtrMatchDepth(), lldb_private::StreamString::GetString(), lldb_private::TypeSummaryImpl::HideNames(), lldb_private::TypeSummaryImpl::IsOneLiner(), m_description, lldb_private::Stream::Printf(), lldb_private::TypeSummaryImpl::SkipsPointers(), and lldb_private::TypeSummaryImpl::SkipsReferences().
GetName()
std::string CXXFunctionSummaryFormat::GetName () override virtual
Get the name of the Type Summary Provider, either a C++ class, a summary string, or a script function name.
Implements lldb_private::TypeSummaryImpl.
Definition at line 171 of file TypeSummary.cpp.
References m_description.
GetTextualInfo()
const char * lldb_private::CXXFunctionSummaryFormat::GetTextualInfo () const inline
Definition at line 345 of file TypeSummary.h.
References m_description.
operator=()
const CXXFunctionSummaryFormat & lldb_private::CXXFunctionSummaryFormat::operator= (const CXXFunctionSummaryFormat &) private delete
References CXXFunctionSummaryFormat().
SetBackendFunction()
void lldb_private::CXXFunctionSummaryFormat::SetBackendFunction (Callback cb_func) inline
Definition at line 347 of file TypeSummary.h.
References m_impl.
SetTextualInfo()
void lldb_private::CXXFunctionSummaryFormat::SetTextualInfo (const char * descr) inline
Definition at line 349 of file TypeSummary.h.
References m_description.
Member Data Documentation
m_description
std::string lldb_private::CXXFunctionSummaryFormat::m_description
Definition at line 335 of file TypeSummary.h.
Referenced by CXXFunctionSummaryFormat(), GetDescription(), GetName(), GetTextualInfo(), and SetTextualInfo().
m_impl
Callback lldb_private::CXXFunctionSummaryFormat::m_impl
Definition at line 334 of file TypeSummary.h.
Referenced by CXXFunctionSummaryFormat(), FormatObject(), GetBackendFunction(), and SetBackendFunction().
The documentation for this struct was generated from the following files:
TypeSummary.h
TypeSummary.cpp