LLDB: lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo Struct Reference
lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo Struct Reference
#include <SymbolFileDWARFDebugMap.h>
Public Member Functions
CompileUnitInfo ()=default
const FileRangeMap & GetFileRangeMap (SymbolFileDWARFDebugMap *exe_symfile)
Public Attributes
FileSpec so_file
ConstString oso_path
llvm::sys::TimePoint oso_mod_time
Status oso_load_error
OSOInfoSP oso_sp
llvm::SmallVector< lldb::CompUnitSP, 2 > compile_units_sps
The compile units that an object file contains.
llvm::SmallDenseMap< uint64_t, uint64_t, 2 > id_to_index_map
A map from the compile unit ID to its index in the vector.
uint32_t first_symbol_index = UINT32_MAX
uint32_t last_symbol_index = UINT32_MAX
uint32_t first_symbol_id = UINT32_MAX
uint32_t last_symbol_id = UINT32_MAX
FileRangeMap file_range_map
bool file_range_map_valid = false
Detailed Description
Definition at line 170 of file SymbolFileDWARFDebugMap.h.
Constructor & Destructor Documentation
CompileUnitInfo()
lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo::CompileUnitInfo () default
References lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::SymbolFileDWARFDebugMap().
Member Function Documentation
GetFileRangeMap()
const SymbolFileDWARFDebugMap::FileRangeMap & SymbolFileDWARFDebugMap::CompileUnitInfo::GetFileRangeMap (SymbolFileDWARFDebugMap * exe_symfile)
const uint32_t fun_resolve_flags = SymbolContext::Module | eSymbolContextCompUnit | eSymbolContextFunction;
Definition at line 59 of file SymbolFileDWARFDebugMap.cpp.
References lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::AddOSOFileRange(), lldb_private::ObjectFile::ClearSymtab(), lldb_private::DebugMap, lldb_private::Symtab::eDebugNo, lldb_private::Mangled::ePreferMangled, lldb::eSymbolTypeCode, lldb::eSymbolTypeData, lldb_private::Symtab::eVisibilityAny, file_range_map, file_range_map_valid, lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FinalizeOSOFileRanges(), lldb_private::Symtab::FindFirstSymbolWithNameAndType(), lldb_private::Symbol::GetAddressRef(), lldb_private::Symbol::GetByteSize(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetCompUnitInfosForModule(), lldb_private::Address::GetFileAddress(), lldb_private::GetLog(), lldb_private::Symbol::GetMangled(), lldb_private::ModuleChild::GetModule(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetModuleByCompUnitInfo(), lldb_private::Mangled::GetName(), lldb_private::Module::GetObjectFile(), lldb_private::SymbolFileCommon::GetObjectFile(), lldb_private::Module::GetSpecificationDescription(), lldb_private::ObjectFile::GetSymtab(), lldb_private::Symbol::GetType(), lldb_private::Symbol::IsDebug(), LLDB_LOGF, lldb_private::Symtab::SymbolAtIndex(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::SymbolFileDWARFDebugMap(), UINT32_MAX, and lldb_private::Symbol::ValueIsAddress().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::AddOSOARanges(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FinalizeOSOFileRanges(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::LinkOSOAddress(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::LinkOSOFileAddress(), and lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::LinkOSOLineTable().
Member Data Documentation
compile_units_sps
llvm::SmallVector<lldb::CompUnitSP, 2> lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo::compile_units_sps
The compile units that an object file contains.
Definition at line 177 of file SymbolFileDWARFDebugMap.h.
file_range_map
FileRangeMap lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo::file_range_map
Definition at line 184 of file SymbolFileDWARFDebugMap.h.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::AddOSOFileRange(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FinalizeOSOFileRanges(), and GetFileRangeMap().
file_range_map_valid
bool lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo::file_range_map_valid = false
Definition at line 185 of file SymbolFileDWARFDebugMap.h.
Referenced by GetFileRangeMap().
first_symbol_id
uint32_t lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo::first_symbol_id = UINT32_MAX
Definition at line 182 of file SymbolFileDWARFDebugMap.h.
first_symbol_index
uint32_t lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo::first_symbol_index = UINT32_MAX
Definition at line 180 of file SymbolFileDWARFDebugMap.h.
id_to_index_map
llvm::SmallDenseMap<uint64_t, uint64_t, 2> lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo::id_to_index_map
A map from the compile unit ID to its index in the vector.
Definition at line 179 of file SymbolFileDWARFDebugMap.h.
last_symbol_id
uint32_t lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo::last_symbol_id = UINT32_MAX
Definition at line 183 of file SymbolFileDWARFDebugMap.h.
last_symbol_index
uint32_t lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo::last_symbol_index = UINT32_MAX
Definition at line 181 of file SymbolFileDWARFDebugMap.h.
oso_load_error
Status lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo::oso_load_error
Definition at line 174 of file SymbolFileDWARFDebugMap.h.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CalculateFrameVariableError(), and lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetModuleByCompUnitInfo().
oso_mod_time
llvm::sys::TimePoint lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo::oso_mod_time
Definition at line 173 of file SymbolFileDWARFDebugMap.h.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetModuleByCompUnitInfo().
oso_path
ConstString lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo::oso_path
Definition at line 172 of file SymbolFileDWARFDebugMap.h.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CalculateFrameVariableError(), and lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetModuleByCompUnitInfo().
oso_sp
OSOInfoSP lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo::oso_sp
Definition at line 175 of file SymbolFileDWARFDebugMap.h.
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FinalizeOSOFileRanges(), and lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetModuleByCompUnitInfo().
so_file
FileSpec lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::CompileUnitInfo::so_file
Definition at line 171 of file SymbolFileDWARFDebugMap.h.
The documentation for this struct was generated from the following files:
SymbolFileDWARFDebugMap.h
SymbolFileDWARFDebugMap.cpp