LLDB: lldb_private::AppleObjCRuntimeV2::DescriptorMapUpdateResult Struct Reference
lldb_private::AppleObjCRuntimeV2::DescriptorMapUpdateResult Struct Reference
Public Member Functions
DescriptorMapUpdateResult (bool ran, bool retry, uint32_t found)
Static Public Member Functions
static DescriptorMapUpdateResult Fail ()
static DescriptorMapUpdateResult Success (uint32_t found)
static DescriptorMapUpdateResult Retry ()
Public Attributes
bool m_update_ran
bool m_retry_update
uint32_t m_num_found
Detailed Description
Definition at line 289 of file AppleObjCRuntimeV2.h.
Constructor & Destructor Documentation
DescriptorMapUpdateResult()
lldb_private::AppleObjCRuntimeV2::DescriptorMapUpdateResult::DescriptorMapUpdateResult (bool ran, bool retry, uint32_t found) inline
Definition at line 294 of file AppleObjCRuntimeV2.h.
References m_num_found, m_retry_update, and m_update_ran.
Referenced by Fail(), Retry(), and Success().
Member Function Documentation
Fail()
DescriptorMapUpdateResult lldb_private::AppleObjCRuntimeV2::DescriptorMapUpdateResult::Fail () inline static
Definition at line 302 of file AppleObjCRuntimeV2.h.
References DescriptorMapUpdateResult().
Retry()
DescriptorMapUpdateResult lldb_private::AppleObjCRuntimeV2::DescriptorMapUpdateResult::Retry () inline static
Definition at line 308 of file AppleObjCRuntimeV2.h.
References DescriptorMapUpdateResult().
Success()
DescriptorMapUpdateResult lldb_private::AppleObjCRuntimeV2::DescriptorMapUpdateResult::Success (uint32_t found) inline static
Definition at line 304 of file AppleObjCRuntimeV2.h.
References DescriptorMapUpdateResult().
Member Data Documentation
m_num_found
uint32_t lldb_private::AppleObjCRuntimeV2::DescriptorMapUpdateResult::m_num_found
Definition at line 292 of file AppleObjCRuntimeV2.h.
Referenced by DescriptorMapUpdateResult().
m_retry_update
bool lldb_private::AppleObjCRuntimeV2::DescriptorMapUpdateResult::m_retry_update
Definition at line 291 of file AppleObjCRuntimeV2.h.
Referenced by DescriptorMapUpdateResult().
m_update_ran
bool lldb_private::AppleObjCRuntimeV2::DescriptorMapUpdateResult::m_update_ran
Definition at line 290 of file AppleObjCRuntimeV2.h.
Referenced by DescriptorMapUpdateResult().
The documentation for this struct was generated from the following file:
AppleObjCRuntimeV2.h