LLDB: lldb_private::AddressData< B, T > Struct Template Reference
lldb_private::AddressData< B, T > Struct Template Reference
#include <RangeMap.h>
Public Types
typedef B BaseType
typedef T DataType
Public Member Functions
AddressData ()
AddressData (B a, DataType d)
bool operator< (const AddressData &rhs) const
bool operator== (const AddressData &rhs) const
bool operator!= (const AddressData &rhs) const
Public Attributes
BaseType addr
DataType data
Detailed Description
template<typename B, typename T>
struct lldb_private::AddressData< B, T >
Definition at line 732 of file RangeMap.h.
Member Typedef Documentation
BaseType
template<typename B, typename T> typedef B lldb_private::AddressData< B, T >::BaseType
Definition at line 733 of file RangeMap.h.
DataType
template<typename B, typename T> typedef T lldb_private::AddressData< B, T >::DataType
Definition at line 734 of file RangeMap.h.
Constructor & Destructor Documentation
AddressData() [1/2]
template<typename B, typename T> lldb_private::AddressData< B, T >::AddressData () inline
Definition at line 739 of file RangeMap.h.
References addr, and data.
Referenced by operator!=(), operator<(), and operator==().
AddressData() [2/2]
template<typename B, typename T> lldb_private::AddressData< B, T >::AddressData (B a, DataType d) inline
Definition at line 741 of file RangeMap.h.
References addr, and data.
Member Function Documentation
operator!=()
template<typename B, typename T> bool lldb_private::AddressData< B, T >::operator!= (const AddressData< B, T > & rhs) const inline
Definition at line 753 of file RangeMap.h.
References addr, AddressData(), and data.
operator<()
template<typename B, typename T> bool lldb_private::AddressData< B, T >::operator< (const AddressData< B, T > & rhs) const inline
Definition at line 743 of file RangeMap.h.
References addr, AddressData(), and data.
operator==()
template<typename B, typename T> bool lldb_private::AddressData< B, T >::operator== (const AddressData< B, T > & rhs) const inline
Definition at line 749 of file RangeMap.h.
References addr, AddressData(), and data.
Member Data Documentation
addr
template<typename B, typename T> BaseType lldb_private::AddressData< B, T >::addr
Definition at line 736 of file RangeMap.h.
Referenced by AddressData(), AddressData(), lldb_private::AddressDataArray< B, T, N >::BaseLessThan(), lldb_private::AddressDataArray< B, T, N >::FindEntry(), operator!=(), operator<(), and operator==().
data
template<typename B, typename T> DataType lldb_private::AddressData< B, T >::data
Definition at line 737 of file RangeMap.h.
Referenced by AddressData(), AddressData(), operator!=(), operator<(), and operator==().
The documentation for this struct was generated from the following file:
RangeMap.h