LLDB: lldb_private::Process::Notifications Struct Reference
lldb_private::Process::Notifications Struct Reference
A notification structure that can be used by clients to listen for changes in a process's lifetime.
#include <Process.h>
Public Attributes
void * baton
void(* initialize)(void *baton, Process *process)
void(* process_state_changed)(void *baton, Process *process, lldb::StateType state)
Detailed Description
A notification structure that can be used by clients to listen for changes in a process's lifetime.
See also
RegisterNotificationCallbacks (const Notifications&)
UnregisterNotificationCallbacks (const Notifications&)
Definition at line 415 of file Process.h.
Member Data Documentation
baton
void* lldb_private::Process::Notifications::baton
Definition at line 416 of file Process.h.
Referenced by lldb_private::Process::RegisterNotificationCallbacks(), and lldb_private::Process::UnregisterNotificationCallbacks().
initialize
void(* lldb_private::Process::Notifications::initialize) (void *baton, Process *process)
Definition at line 417 of file Process.h.
Referenced by lldb_private::Process::RegisterNotificationCallbacks(), and lldb_private::Process::UnregisterNotificationCallbacks().
process_state_changed
void(* lldb_private::Process::Notifications::process_state_changed) (void *baton, Process *process, lldb::StateType state)
Definition at line 418 of file Process.h.
Referenced by lldb_private::Process::UnregisterNotificationCallbacks().
The documentation for this struct was generated from the following file:
Process.h