LLDB: lldb_private::process_gdb_remote::GDBRemoteClientBase::ContinueDelegate Struct Reference
lldb_private::process_gdb_remote::GDBRemoteClientBase::ContinueDelegate Struct Reference abstract
#include <GDBRemoteClientBase.h>
Public Member Functions
virtual ~ContinueDelegate ()
virtual void HandleAsyncStdout (llvm::StringRef out)=0
virtual void HandleAsyncMisc (llvm::StringRef data)=0
virtual void HandleStopReply ()=0
virtual void HandleAsyncStructuredDataPacket (llvm::StringRef data)=0
Process asynchronously-received structured data.
Detailed Description
Definition at line 30 of file GDBRemoteClientBase.h.
Constructor & Destructor Documentation
~ContinueDelegate()
GDBRemoteClientBase::ContinueDelegate::~ContinueDelegate () virtual default
Member Function Documentation
HandleAsyncMisc()
virtual void lldb_private::process_gdb_remote::GDBRemoteClientBase::ContinueDelegate::HandleAsyncMisc (llvm::StringRef data) pure virtual
Implemented in lldb_private::process_gdb_remote::ProcessGDBRemote.
Referenced by lldb_private::process_gdb_remote::GDBRemoteClientBase::SendContinuePacketAndWaitForResponse().
HandleAsyncStdout()
virtual void lldb_private::process_gdb_remote::GDBRemoteClientBase::ContinueDelegate::HandleAsyncStdout (llvm::StringRef out) pure virtual
Implemented in lldb_private::process_gdb_remote::ProcessGDBRemote.
Referenced by lldb_private::process_gdb_remote::GDBRemoteClientBase::SendContinuePacketAndWaitForResponse().
HandleAsyncStructuredDataPacket()
virtual void lldb_private::process_gdb_remote::GDBRemoteClientBase::ContinueDelegate::HandleAsyncStructuredDataPacket (llvm::StringRef data) pure virtual
Process asynchronously-received structured data.
Parameters
[in] data The complete data packet, expected to start with JSON-async.
Implemented in lldb_private::process_gdb_remote::ProcessGDBRemote.
Referenced by lldb_private::process_gdb_remote::GDBRemoteClientBase::SendContinuePacketAndWaitForResponse().
HandleStopReply()
virtual void lldb_private::process_gdb_remote::GDBRemoteClientBase::ContinueDelegate::HandleStopReply () pure virtual
Implemented in lldb_private::process_gdb_remote::ProcessGDBRemote.
Referenced by lldb_private::process_gdb_remote::GDBRemoteClientBase::SendContinuePacketAndWaitForResponse().
The documentation for this struct was generated from the following files:
GDBRemoteClientBase.h
GDBRemoteClientBase.cpp