LLDB: lldb_private::ClassDescriptorV2::method_list_t Struct Reference
lldb_private::ClassDescriptorV2::method_list_t Struct Reference
Public Member Functions
bool Read (Process *process, lldb::addr_t addr)
Public Attributes
uint16_t m_entsize
bool m_is_small
bool m_has_direct_selector
bool m_has_relative_types
uint32_t m_count
lldb::addr_t m_first_ptr
Detailed Description
Definition at line 139 of file AppleObjCClassDescriptorV2.h.
Member Function Documentation
Read()
bool ClassDescriptorV2::method_list_t::Read (Process * process, lldb::addr_t addr)
Definition at line 237 of file AppleObjCClassDescriptorV2.cpp.
References error(), lldb_private::Process::GetABI(), lldb_private::Process::GetAddressByteSize(), lldb_private::Process::GetByteOrder(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::DataExtractor::GetU32_unchecked(), m_count, m_entsize, m_first_ptr, m_has_direct_selector, m_has_relative_types, m_is_small, and lldb_private::Process::ReadMemory().
Referenced by lldb_private::ClassDescriptorV2::GetMethodList().
Member Data Documentation
m_count
uint32_t lldb_private::ClassDescriptorV2::method_list_t::m_count
Definition at line 144 of file AppleObjCClassDescriptorV2.h.
Referenced by lldb_private::ClassDescriptorV2::ProcessMethodList(), and Read().
m_entsize
uint16_t lldb_private::ClassDescriptorV2::method_list_t::m_entsize
Definition at line 140 of file AppleObjCClassDescriptorV2.h.
Referenced by lldb_private::ClassDescriptorV2::GetMethodList(), lldb_private::ClassDescriptorV2::ProcessMethodList(), and Read().
m_first_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::method_list_t::m_first_ptr
Definition at line 145 of file AppleObjCClassDescriptorV2.h.
Referenced by lldb_private::ClassDescriptorV2::ProcessMethodList(), and Read().
m_has_direct_selector
bool lldb_private::ClassDescriptorV2::method_list_t::m_has_direct_selector
Definition at line 142 of file AppleObjCClassDescriptorV2.h.
Referenced by lldb_private::ClassDescriptorV2::ProcessMethodList(), and Read().
m_has_relative_types
bool lldb_private::ClassDescriptorV2::method_list_t::m_has_relative_types
Definition at line 143 of file AppleObjCClassDescriptorV2.h.
Referenced by lldb_private::ClassDescriptorV2::ProcessMethodList(), and Read().
m_is_small
bool lldb_private::ClassDescriptorV2::method_list_t::m_is_small
Definition at line 141 of file AppleObjCClassDescriptorV2.h.
Referenced by lldb_private::ClassDescriptorV2::GetMethodList(), lldb_private::ClassDescriptorV2::ProcessMethodList(), and Read().
The documentation for this struct was generated from the following files:
AppleObjCClassDescriptorV2.h
AppleObjCClassDescriptorV2.cpp