LLDB: lldb_private::BreakpointOptions::CommandData Struct Reference
lldb_private::BreakpointOptions::CommandData Struct Reference
#include <BreakpointOptions.h>
Public Member Functions
CommandData ()=default
CommandData (const StringList &user_source, lldb::ScriptLanguage interp)
virtual ~CommandData ()=default
StructuredData::ObjectSP SerializeToStructuredData ()
Static Public Member Functions
static const char * GetSerializationKey ()
static std::unique_ptr< CommandData > CreateFromStructuredData (const StructuredData::Dictionary &options_dict, Status &error)
Public Attributes
StringList user_source
std::string script_source
enum lldb::ScriptLanguage interpreter
bool stop_on_error = true
Private Types
enum class OptionNames : uint32_t { UserSource = 0 , Interpreter , StopOnError , LastOptionName }
Static Private Member Functions
static const char * GetKey (OptionNames enum_value)
Static Private Attributes
static const char * g_option_names [static_cast< uint32_t >(OptionNames::LastOptionName)]
Detailed Description
Definition at line 46 of file BreakpointOptions.h.
Member Enumeration Documentation
OptionNames
enum class lldb_private::BreakpointOptions::CommandData::OptionNames : uint32_t strong private
Enumerator
UserSource
Interpreter
StopOnError
LastOptionName
Definition at line 70 of file BreakpointOptions.h.
Constructor & Destructor Documentation
CommandData() [1/2]
lldb_private::BreakpointOptions::CommandData::CommandData () default
Referenced by lldb_private::ScriptInterpreterLua::CommandDataLua::CommandDataLua(), lldb_private::ScriptInterpreterLua::CommandDataLua::CommandDataLua(), lldb_private::ScriptInterpreterPython::CommandDataPython::CommandDataPython(), lldb_private::ScriptInterpreterPython::CommandDataPython::CommandDataPython(), and CreateFromStructuredData().
CommandData() [2/2]
lldb_private::BreakpointOptions::CommandData::CommandData (const StringList & user_source, lldb::ScriptLanguage interp) inline
Definition at line 49 of file BreakpointOptions.h.
References interpreter, stop_on_error, and user_source.
~CommandData()
virtual lldb_private::BreakpointOptions::CommandData::~CommandData () virtual default
Member Function Documentation
CreateFromStructuredData()
std::unique_ptr< BreakpointOptions::CommandData > BreakpointOptions::CommandData::CreateFromStructuredData (const StructuredData::Dictionary & options_dict, Status & error) static
Definition at line 60 of file BreakpointOptions.cpp.
References CommandData(), error(), lldb::eScriptLanguageUnknown, lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormatv(), lldb_private::BreakpointOptions::GetKey(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsArray(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsBoolean(), lldb_private::StructuredData::Dictionary::GetValueForKeyAsString(), Interpreter, StopOnError, lldb_private::ScriptInterpreter::StringToLanguage(), user_source, and UserSource.
Referenced by lldb_private::BreakpointOptions::CreateFromStructuredData().
GetKey()
const char * lldb_private::BreakpointOptions::CommandData::GetKey (OptionNames enum_value) inline static private
Definition at line 80 of file BreakpointOptions.h.
References g_option_names.
Referenced by SerializeToStructuredData().
GetSerializationKey()
const char * lldb_private::BreakpointOptions::CommandData::GetSerializationKey () inline static
Definition at line 54 of file BreakpointOptions.h.
Referenced by lldb_private::BreakpointOptions::CreateFromStructuredData(), and lldb_private::BreakpointOptions::SerializeToStructuredData().
SerializeToStructuredData()
StructuredData::ObjectSP BreakpointOptions::CommandData::SerializeToStructuredData ()
Definition at line 32 of file BreakpointOptions.cpp.
References GetKey(), Interpreter, interpreter, lldb_private::ScriptInterpreter::LanguageToString(), script_source, stop_on_error, StopOnError, user_source, and UserSource.
Member Data Documentation
g_option_names
const char * BreakpointOptions::CommandData::g_option_names static private
Initial value:
{
        "UserSource", "ScriptSource", "StopOnError"}
Definition at line 78 of file BreakpointOptions.h.
Referenced by GetKey().
interpreter
enum lldb::ScriptLanguage lldb_private::BreakpointOptions::CommandData::interpreter
Initial value:
=
        lldb::eScriptLanguageNone
Definition at line 64 of file BreakpointOptions.h.
Referenced by CommandData(), lldb_private::ScriptInterpreterLua::CommandDataLua::CommandDataLua(), lldb_private::ScriptInterpreterLua::CommandDataLua::CommandDataLua(), lldb_private::ScriptInterpreterPython::CommandDataPython::CommandDataPython(), lldb_private::ScriptInterpreterPython::CommandDataPython::CommandDataPython(), and SerializeToStructuredData().
script_source
std::string lldb_private::BreakpointOptions::CommandData::script_source
Definition at line 63 of file BreakpointOptions.h.
Referenced by SerializeToStructuredData().
stop_on_error
bool lldb_private::BreakpointOptions::CommandData::stop_on_error = true
Definition at line 67 of file BreakpointOptions.h.
Referenced by lldb_private::BreakpointOptions::BreakpointOptionsCallbackFunction(), CommandData(), and SerializeToStructuredData().
user_source
StringList lldb_private::BreakpointOptions::CommandData::user_source
Definition at line 62 of file BreakpointOptions.h.
Referenced by lldb_private::BreakpointOptions::BreakpointOptionsCallbackFunction(), CommandData(), CreateFromStructuredData(), lldb_private::BreakpointOptions::GetCommandLineCallbacks(), and SerializeToStructuredData().
The documentation for this struct was generated from the following files:
BreakpointOptions.h
BreakpointOptions.cpp