LLDB: lldb_private::EmulateInstruction::Context Struct Reference
lldb_private::EmulateInstruction::Context Struct Reference
#include <EmulateInstruction.h>
Classes
union ContextInfo
Public Member Functions
enum InfoType GetInfoType () const
Context ()=default
void SetRegisterPlusOffset (RegisterInfo base_reg, int64_t signed_offset)
void SetRegisterPlusIndirectOffset (RegisterInfo base_reg, RegisterInfo offset_reg)
void SetRegisterToRegisterPlusOffset (RegisterInfo data_reg, RegisterInfo base_reg, int64_t offset)
void SetRegisterToRegisterPlusIndirectOffset (RegisterInfo base_reg, RegisterInfo offset_reg, RegisterInfo data_reg)
void SetRegisterRegisterOperands (RegisterInfo op1_reg, RegisterInfo op2_reg)
void SetOffset (int64_t signed_offset)
void SetRegister (RegisterInfo reg)
void SetImmediate (uint64_t immediate)
void SetImmediateSigned (int64_t signed_immediate)
void SetAddress (lldb::addr_t address)
void SetISAAndImmediate (uint32_t isa, uint32_t data)
void SetISAAndImmediateSigned (uint32_t isa, int32_t data)
void SetISA (uint32_t isa)
void SetNoArgs ()
void Dump (Stream &s, EmulateInstruction *instruction) const
Public Attributes
ContextType type = eContextInvalid
union lldb_private::EmulateInstruction::Context::ContextInfo info
Private Attributes
enum InfoType info_type = eInfoTypeNoArgs
Detailed Description
Definition at line 219 of file EmulateInstruction.h.
Constructor & Destructor Documentation
Context()
lldb_private::EmulateInstruction::Context::Context () default
Member Function Documentation
Dump()
void EmulateInstruction::Context::Dump (Stream & s, EmulateInstruction * instruction) const
Definition at line 373 of file EmulateInstruction.cpp.
References lldb_private::EmulateInstruction::eContextAbsoluteBranchRegister, lldb_private::EmulateInstruction::eContextAdjustBaseRegister, lldb_private::EmulateInstruction::eContextAdjustStackPointer, lldb_private::EmulateInstruction::eContextArithmetic, lldb_private::EmulateInstruction::eContextImmediate, lldb_private::EmulateInstruction::eContextPopRegisterOffStack, lldb_private::EmulateInstruction::eContextPushRegisterOnStack, lldb_private::EmulateInstruction::eContextReadOpcode, lldb_private::EmulateInstruction::eContextRegisterLoad, lldb_private::EmulateInstruction::eContextRegisterPlusOffset, lldb_private::EmulateInstruction::eContextRegisterStore, lldb_private::EmulateInstruction::eContextRelativeBranchImmediate, lldb_private::EmulateInstruction::eContextReturnFromException, lldb_private::EmulateInstruction::eContextSetFramePointer, lldb_private::EmulateInstruction::eContextSupervisorCall, lldb_private::EmulateInstruction::eContextTableBranchReadMemory, lldb_private::EmulateInstruction::eContextWriteMemoryRandomBits, lldb_private::EmulateInstruction::eContextWriteRegisterRandomBits, lldb_private::EmulateInstruction::eInfoTypeAddress, lldb_private::EmulateInstruction::eInfoTypeImmediate, lldb_private::EmulateInstruction::eInfoTypeImmediateSigned, lldb_private::EmulateInstruction::eInfoTypeISA, lldb_private::EmulateInstruction::eInfoTypeISAAndImmediate, lldb_private::EmulateInstruction::eInfoTypeISAAndImmediateSigned, lldb_private::EmulateInstruction::eInfoTypeNoArgs, lldb_private::EmulateInstruction::eInfoTypeOffset, lldb_private::EmulateInstruction::eInfoTypeRegister, lldb_private::EmulateInstruction::eInfoTypeRegisterPlusIndirectOffset, lldb_private::EmulateInstruction::eInfoTypeRegisterPlusOffset, lldb_private::EmulateInstruction::eInfoTypeRegisterRegisterOperands, lldb_private::EmulateInstruction::eInfoTypeRegisterToRegisterPlusIndirectOffset, lldb_private::EmulateInstruction::eInfoTypeRegisterToRegisterPlusOffset, lldb_private::EmulateInstruction::EmulateInstruction(), GetInfoType(), info, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and type.
Referenced by UnwindAssemblyInstEmulation::ReadMemory(), lldb_private::EmulateInstruction::ReadMemoryDefault(), UnwindAssemblyInstEmulation::WriteMemory(), lldb_private::EmulateInstruction::WriteMemoryDefault(), UnwindAssemblyInstEmulation::WriteRegister(), and lldb_private::EmulateInstruction::WriteRegisterDefault().
GetInfoType()
enum InfoType lldb_private::EmulateInstruction::Context::GetInfoType () const inline
Definition at line 226 of file EmulateInstruction.h.
References info_type.
Referenced by Dump(), UnwindAssemblyInstEmulation::WriteMemory(), and UnwindAssemblyInstEmulation::WriteRegister().
SetAddress()
void lldb_private::EmulateInstruction::Context::SetAddress (lldb::addr_t address) inline
Definition at line 342 of file EmulateInstruction.h.
References lldb_private::EmulateInstruction::eInfoTypeAddress, info, and info_type.
Referenced by EmulateInstructionMIPS::Emulate_LW(), EmulateInstructionMIPS::Emulate_LWM16_32(), EmulateInstructionMIPS::Emulate_LWSP(), lldb_private::EmulateInstructionARM::EmulateLDM(), EmulateInstructionARM64::EmulateLDPSTP(), lldb_private::EmulateInstructionARM::EmulateLDRBImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRBRegister(), lldb_private::EmulateInstructionARM::EmulateLDRDImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRDRegister(), lldb_private::EmulateInstructionARM::EmulateLDRHImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRHRegister(), lldb_private::EmulateInstructionARM::EmulateLDRImmediateARM(), lldb_private::EmulateInstructionARM::EmulateLDRRegister(), lldb_private::EmulateInstructionARM::EmulateLDRSBImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRSBRegister(), lldb_private::EmulateInstructionARM::EmulateLDRSHImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRSHRegister(), EmulateInstructionARM64::EmulateLDRSTRImm(), lldb_private::EmulateInstructionARM::EmulatePOP(), lldb_private::EmulateInstructionARM::EmulateSTRBThumb(), lldb_private::EmulateInstructionARM::EmulateSTRDImm(), lldb_private::EmulateInstructionARM::EmulateSTRDReg(), lldb_private::EmulateInstructionARM::EmulateSTRHRegister(), lldb_private::EmulateInstructionARM::EmulateSTRRegister(), lldb_private::EmulateInstructionARM::EmulateSTRThumb(), lldb_private::EmulateInstructionARM::EmulateVPOP(), and lldb_private::Load().
SetImmediate()
void lldb_private::EmulateInstruction::Context::SetImmediate (uint64_t immediate) inline
Definition at line 332 of file EmulateInstruction.h.
References lldb_private::EmulateInstruction::eInfoTypeImmediate, info, and info_type.
Referenced by EmulateInstructionMIPS::Emulate_B16_MM(), EmulateInstructionMIPS::Emulate_Branch_MM(), EmulateInstructionMIPS64::Emulate_BXX_2ops(), EmulateInstructionMIPS::Emulate_BXX_2ops(), EmulateInstructionMIPS64::Emulate_BXX_2ops_C(), EmulateInstructionMIPS::Emulate_BXX_2ops_C(), EmulateInstructionMIPS64::Emulate_BXX_3ops(), EmulateInstructionMIPS::Emulate_BXX_3ops(), EmulateInstructionMIPS64::Emulate_BXX_3ops_C(), EmulateInstructionMIPS::Emulate_BXX_3ops_C(), lldb_private::EmulateInstructionARM::EmulateLDRBLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRImmediateARM(), lldb_private::EmulateInstructionARM::EmulateLDRRegister(), lldb_private::EmulateInstructionARM::EmulateSTRImmARM(), and lldb_private::EmulateInstructionARM::EmulateSUBSPcLrEtc().
SetImmediateSigned()
void lldb_private::EmulateInstruction::Context::SetImmediateSigned (int64_t signed_immediate) inline
Definition at line 337 of file EmulateInstruction.h.
References lldb_private::EmulateInstruction::eInfoTypeImmediateSigned, info, and info_type.
Referenced by EmulateInstructionMIPS::Emulate_ADDiu(), EmulateInstructionMIPS64::Emulate_DADDiu(), EmulateInstructionMIPS64::Emulate_DSUBU_DADDU(), EmulateInstructionMIPS64::Emulate_LUI(), EmulateInstructionMIPS::Emulate_LUI(), EmulateInstructionMIPS::Emulate_SUBU_ADDU(), EmulateInstructionARM64::EmulateB(), EmulateInstructionARM64::EmulateBcond(), EmulateInstructionARM64::EmulateCBZ(), lldb_private::EmulateInstructionARM::EmulateLDMIB(), EmulateInstructionARM64::EmulateLDPSTP(), lldb_private::EmulateInstructionARM::EmulateLDRRtRnImm(), EmulateInstructionARM64::EmulateLDRSTRImm(), lldb_private::EmulateInstructionARM::EmulatePOP(), lldb_private::EmulateInstructionARM::EmulatePUSH(), lldb_private::EmulateInstructionARM::EmulateSTM(), lldb_private::EmulateInstructionARM::EmulateSTMIB(), lldb_private::EmulateInstructionARM::EmulateSTRRtSP(), lldb_private::EmulateInstructionARM::EmulateSUBSPImm(), EmulateInstructionARM64::EmulateTBZ(), lldb_private::EmulateInstructionARM::EmulateVLDM(), lldb_private::EmulateInstructionARM::EmulateVPOP(), and lldb_private::EmulateInstructionARM::EmulateVPUSH().
SetISA()
void lldb_private::EmulateInstruction::Context::SetISA (uint32_t isa) inline
Definition at line 358 of file EmulateInstruction.h.
References lldb_private::EmulateInstruction::eInfoTypeISA, info, and info_type.
Referenced by lldb_private::EmulateInstructionARM::BXWritePC().
SetISAAndImmediate()
void lldb_private::EmulateInstruction::Context::SetISAAndImmediate (uint32_t isa, uint32_t data) inline
Definition at line 346 of file EmulateInstruction.h.
References lldb_private::EmulateInstruction::eInfoTypeISAAndImmediate, info, and info_type.
Referenced by lldb_private::EmulateInstructionARM::EmulateSVC().
SetISAAndImmediateSigned()
void lldb_private::EmulateInstruction::Context::SetISAAndImmediateSigned (uint32_t isa, int32_t data) inline
Definition at line 352 of file EmulateInstruction.h.
References lldb_private::EmulateInstruction::eInfoTypeISAAndImmediateSigned, info, and info_type.
Referenced by lldb_private::EmulateInstructionARM::EmulateB(), lldb_private::EmulateInstructionARM::EmulateBLXImmediate(), and lldb_private::EmulateInstructionARM::EmulateCB().
SetNoArgs()
void lldb_private::EmulateInstruction::Context::SetNoArgs () inline
Definition at line 363 of file EmulateInstruction.h.
References lldb_private::EmulateInstruction::eInfoTypeNoArgs, and info_type.
Referenced by lldb_private::EmulateInstructionARM::EmulateADCImm(), lldb_private::EmulateInstructionARM::EmulateADCReg(), lldb_private::EmulateInstructionARM::EmulateADR(), lldb_private::EmulateInstructionARM::EmulateANDImm(), lldb_private::EmulateInstructionARM::EmulateANDReg(), lldb_private::EmulateInstructionARM::EmulateBICImm(), lldb_private::EmulateInstructionARM::EmulateBICReg(), lldb_private::EmulateInstructionARM::EmulateCMNImm(), lldb_private::EmulateInstructionARM::EmulateCMNReg(), lldb_private::EmulateInstructionARM::EmulateCMPImm(), lldb_private::EmulateInstructionARM::EmulateCMPReg(), lldb_private::EmulateInstructionARM::EmulateEORImm(), lldb_private::EmulateInstructionARM::EmulateEORReg(), lldb_private::EmulateInstructionARM::EmulateMOVRdImm(), lldb_private::EmulateInstructionARM::EmulateMVNImm(), lldb_private::EmulateInstructionARM::EmulateMVNReg(), lldb_private::EmulateInstructionARM::EmulateORRImm(), lldb_private::EmulateInstructionARM::EmulateORRReg(), lldb_private::EmulateInstructionARM::EmulateRSBImm(), lldb_private::EmulateInstructionARM::EmulateRSBReg(), lldb_private::EmulateInstructionARM::EmulateRSCImm(), lldb_private::EmulateInstructionARM::EmulateRSCReg(), lldb_private::EmulateInstructionARM::EmulateSBCImm(), lldb_private::EmulateInstructionARM::EmulateSBCReg(), lldb_private::EmulateInstructionARM::EmulateShiftImm(), lldb_private::EmulateInstructionARM::EmulateShiftReg(), lldb_private::EmulateInstructionARM::EmulateSUBImmThumb(), lldb_private::EmulateInstructionARM::EmulateSUBSPImm(), lldb_private::EmulateInstructionARM::EmulateTEQImm(), lldb_private::EmulateInstructionARM::EmulateTEQReg(), lldb_private::EmulateInstructionARM::EmulateTSTImm(), lldb_private::EmulateInstructionARM::EmulateTSTReg(), EmulateInstructionARM64::EvaluateInstruction(), lldb_private::EmulateInstructionARM::EvaluateInstruction(), lldb_private::EmulateInstructionPPC64::EvaluateInstruction(), EmulateInstructionARM64::ReadInstruction(), EmulateInstructionMIPS64::ReadInstruction(), EmulateInstructionMIPS::ReadInstruction(), lldb_private::EmulateInstructionARM::ReadInstruction(), lldb_private::EmulateInstructionLoongArch::ReadInstruction(), lldb_private::EmulateInstructionPPC64::ReadInstruction(), lldb_private::EmulateInstructionRISCV::ReadMem(), lldb_private::EmulateInstructionRISCV::SetAccruedExceptions(), lldb_private::Rd::Write(), lldb_private::Rd::WriteAPFloat(), lldb_private::EmulateInstructionARM::WriteBits32Unknown(), lldb_private::EmulateInstructionARM::WriteBits32UnknownToMemory(), lldb_private::EmulateInstructionRISCV::WriteMem(), and lldb_private::EmulateInstruction::WritePC().
SetOffset()
void lldb_private::EmulateInstruction::Context::SetOffset (int64_t signed_offset) inline
Definition at line 322 of file EmulateInstruction.h.
References lldb_private::EmulateInstruction::eInfoTypeOffset, info, and info_type.
Referenced by lldb_private::EmulateInstructionARM::EmulateRFE().
SetRegister()
void lldb_private::EmulateInstruction::Context::SetRegister (RegisterInfo reg) inline
Definition at line 327 of file EmulateInstruction.h.
References lldb_private::EmulateInstruction::eInfoTypeRegister, info, and info_type.
Referenced by lldb_private::EmulateInstructionARM::EmulateBLXRm(), lldb_private::EmulateInstructionARM::EmulateBXJRm(), lldb_private::EmulateInstructionARM::EmulateBXRm(), lldb_private::EmulateInstructionPPC64::EmulateOR(), lldb_private::EmulateInstructionARM::EmulateSXTB(), lldb_private::EmulateInstructionARM::EmulateSXTH(), lldb_private::EmulateInstructionARM::EmulateUXTB(), and lldb_private::EmulateInstructionARM::EmulateUXTH().
SetRegisterPlusIndirectOffset()
void lldb_private::EmulateInstruction::Context::SetRegisterPlusIndirectOffset (RegisterInfo base_reg, RegisterInfo offset_reg) inline
Definition at line 290 of file EmulateInstruction.h.
References lldb_private::EmulateInstruction::eInfoTypeRegisterPlusIndirectOffset, info, and info_type.
Referenced by lldb_private::EmulateInstructionARM::EmulateLDRHRegister(), lldb_private::EmulateInstructionARM::EmulateLDRSBRegister(), and lldb_private::EmulateInstructionARM::EmulateLDRSHRegister().
SetRegisterPlusOffset()
void lldb_private::EmulateInstruction::Context::SetRegisterPlusOffset (RegisterInfo base_reg, int64_t signed_offset) inline
Definition at line 284 of file EmulateInstruction.h.
References lldb_private::EmulateInstruction::eInfoTypeRegisterPlusOffset, info, and info_type.
Referenced by EmulateInstructionMIPS::Emulate_ADDiu(), EmulateInstructionMIPS::Emulate_ADDIUS5(), EmulateInstructionMIPS::Emulate_ADDIUSP(), EmulateInstructionMIPS64::Emulate_DADDiu(), EmulateInstructionMIPS64::Emulate_DSUBU_DADDU(), EmulateInstructionMIPS::Emulate_JRADDIUSP(), EmulateInstructionMIPS::Emulate_SUBU_ADDU(), lldb_private::EmulateInstructionARM::EmulateADDImmARM(), lldb_private::EmulateInstructionARM::EmulateADDImmThumb(), lldb_private::EmulateInstructionARM::EmulateADDRdSPImm(), lldb_private::EmulateInstructionARM::EmulateADDSPImm(), EmulateInstructionARM64::EmulateADDSUBImm(), lldb_private::EmulateInstructionARM::EmulateLDM(), lldb_private::EmulateInstructionARM::EmulateLDMIB(), lldb_private::EmulateInstructionARM::EmulateLDRBRegister(), lldb_private::EmulateInstructionARM::EmulateLDRHImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRHLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRImmediateARM(), lldb_private::EmulateInstructionARM::EmulateLDRRegister(), lldb_private::EmulateInstructionARM::EmulateLDRRtPCRelative(), lldb_private::EmulateInstructionARM::EmulateLDRRtRnImm(), lldb_private::EmulateInstructionARM::EmulateLDRSBImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRSBLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRSHImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRSHLiteral(), lldb_private::EmulateInstructionARM::EmulateMOVRdRm(), lldb_private::EmulateInstructionARM::EmulateMOVRdSP(), lldb_private::EmulateInstructionARM::EmulatePOP(), lldb_private::EmulateInstructionARM::EmulateRFE(), lldb_private::EmulateInstructionARM::EmulateSTM(), lldb_private::EmulateInstructionARM::EmulateSTMIB(), lldb_private::EmulateInstructionARM::EmulateSUBImmARM(), lldb_private::EmulateInstructionARM::EmulateSUBIPSPImm(), lldb_private::EmulateInstructionARM::EmulateSUBR7IPImm(), lldb_private::EmulateInstructionARM::EmulateVLD1Multiple(), lldb_private::EmulateInstructionARM::EmulateVLD1Single(), lldb_private::EmulateInstructionARM::EmulateVLD1SingleAll(), lldb_private::EmulateInstructionARM::EmulateVLDM(), lldb_private::EmulateInstructionARM::EmulateVLDR(), lldb_private::EmulateInstructionARM::EmulateVST1Multiple(), lldb_private::EmulateInstructionARM::EmulateVST1Single(), and lldb_private::EmulateInstructionARM::EmulateVSTM().
SetRegisterRegisterOperands()
void lldb_private::EmulateInstruction::Context::SetRegisterRegisterOperands (RegisterInfo op1_reg, RegisterInfo op2_reg) inline
Definition at line 315 of file EmulateInstruction.h.
References lldb_private::EmulateInstruction::eInfoTypeRegisterRegisterOperands, info, and info_type.
Referenced by lldb_private::EmulateInstructionARM::EmulateADDReg(), lldb_private::EmulateInstructionARM::EmulateADDRegShift(), lldb_private::EmulateInstructionARM::EmulateADDSPRm(), lldb_private::EmulateInstructionARM::EmulateMUL(), lldb_private::EmulateInstructionARM::EmulateSUBReg(), and lldb_private::EmulateInstructionARM::EmulateSUBSPReg().
SetRegisterToRegisterPlusIndirectOffset()
void lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusIndirectOffset (RegisterInfo base_reg, RegisterInfo offset_reg, RegisterInfo data_reg) inline
Definition at line 306 of file EmulateInstruction.h.
References lldb_private::EmulateInstruction::eInfoTypeRegisterToRegisterPlusIndirectOffset, info, and info_type.
Referenced by lldb_private::EmulateInstructionARM::EmulateSTRDReg(), and lldb_private::EmulateInstructionARM::EmulateSTRHRegister().
SetRegisterToRegisterPlusOffset()
void lldb_private::EmulateInstruction::Context::SetRegisterToRegisterPlusOffset (RegisterInfo data_reg, RegisterInfo base_reg, int64_t offset) inline
Definition at line 297 of file EmulateInstruction.h.
References lldb_private::EmulateInstruction::eInfoTypeRegisterToRegisterPlusOffset, info, and info_type.
Referenced by EmulateInstructionMIPS64::Emulate_SD(), EmulateInstructionMIPS::Emulate_SW(), EmulateInstructionMIPS::Emulate_SWM16_32(), EmulateInstructionMIPS::Emulate_SWSP(), lldb_private::EmulateInstructionPPC64::EmulateADDI(), lldb_private::EmulateInstructionPPC64::EmulateLD(), EmulateInstructionARM64::EmulateLDPSTP(), lldb_private::EmulateInstructionARM::EmulateLDRBImmediate(), EmulateInstructionARM64::EmulateLDRSTRImm(), lldb_private::EmulateInstructionARM::EmulatePUSH(), lldb_private::EmulateInstructionPPC64::EmulateSTD(), lldb_private::EmulateInstructionARM::EmulateSTM(), lldb_private::EmulateInstructionARM::EmulateSTMIB(), lldb_private::EmulateInstructionARM::EmulateSTRBImmARM(), lldb_private::EmulateInstructionARM::EmulateSTRBThumb(), lldb_private::EmulateInstructionARM::EmulateSTRDImm(), lldb_private::EmulateInstructionARM::EmulateSTREX(), lldb_private::EmulateInstructionARM::EmulateSTRImmARM(), lldb_private::EmulateInstructionARM::EmulateSTRRegister(), lldb_private::EmulateInstructionARM::EmulateSTRRtSP(), lldb_private::EmulateInstructionARM::EmulateSTRThumb(), lldb_private::EmulateInstructionARM::EmulateVPUSH(), lldb_private::EmulateInstructionARM::EmulateVST1Multiple(), lldb_private::EmulateInstructionARM::EmulateVST1Single(), lldb_private::EmulateInstructionARM::EmulateVSTM(), lldb_private::EmulateInstructionARM::EmulateVSTR(), and lldb_private::Store().
Member Data Documentation
info
union lldb_private::EmulateInstruction::Context::ContextInfo lldb_private::EmulateInstruction::Context::info
Referenced by Dump(), SetAddress(), SetImmediate(), SetImmediateSigned(), SetISA(), SetISAAndImmediate(), SetISAAndImmediateSigned(), SetOffset(), SetRegister(), SetRegisterPlusIndirectOffset(), SetRegisterPlusOffset(), SetRegisterRegisterOperands(), SetRegisterToRegisterPlusIndirectOffset(), SetRegisterToRegisterPlusOffset(), UnwindAssemblyInstEmulation::WriteMemory(), and UnwindAssemblyInstEmulation::WriteRegister().
info_type
enum InfoType lldb_private::EmulateInstruction::Context::info_type = eInfoTypeNoArgs private
Definition at line 223 of file EmulateInstruction.h.
Referenced by GetInfoType(), SetAddress(), SetImmediate(), SetImmediateSigned(), SetISA(), SetISAAndImmediate(), SetISAAndImmediateSigned(), SetNoArgs(), SetOffset(), SetRegister(), SetRegisterPlusIndirectOffset(), SetRegisterPlusOffset(), SetRegisterRegisterOperands(), SetRegisterToRegisterPlusIndirectOffset(), and SetRegisterToRegisterPlusOffset().
type
ContextType lldb_private::EmulateInstruction::Context::type = eContextInvalid
Definition at line 220 of file EmulateInstruction.h.
Referenced by Dump(), EmulateInstructionMIPS::Emulate_ADDiu(), EmulateInstructionMIPS::Emulate_ADDIUS5(), EmulateInstructionMIPS::Emulate_ADDIUSP(), EmulateInstructionMIPS::Emulate_B16_MM(), EmulateInstructionMIPS::Emulate_Branch_MM(), EmulateInstructionMIPS64::Emulate_BXX_2ops(), EmulateInstructionMIPS::Emulate_BXX_2ops(), EmulateInstructionMIPS64::Emulate_BXX_2ops_C(), EmulateInstructionMIPS::Emulate_BXX_2ops_C(), EmulateInstructionMIPS64::Emulate_BXX_3ops(), EmulateInstructionMIPS::Emulate_BXX_3ops(), EmulateInstructionMIPS64::Emulate_BXX_3ops_C(), EmulateInstructionMIPS::Emulate_BXX_3ops_C(), EmulateInstructionMIPS64::Emulate_DADDiu(), EmulateInstructionMIPS64::Emulate_DSUBU_DADDU(), EmulateInstructionMIPS::Emulate_JRADDIUSP(), EmulateInstructionMIPS64::Emulate_LD(), EmulateInstructionMIPS64::Emulate_LDST_Imm(), EmulateInstructionMIPS::Emulate_LDST_Imm(), EmulateInstructionMIPS64::Emulate_LDST_Reg(), EmulateInstructionMIPS::Emulate_LDST_Reg(), EmulateInstructionMIPS64::Emulate_LUI(), EmulateInstructionMIPS::Emulate_LUI(), EmulateInstructionMIPS::Emulate_LW(), EmulateInstructionMIPS::Emulate_LWM16_32(), EmulateInstructionMIPS::Emulate_LWSP(), EmulateInstructionMIPS64::Emulate_MSA_Branch_DF(), EmulateInstructionMIPS::Emulate_MSA_Branch_DF(), EmulateInstructionMIPS64::Emulate_MSA_Branch_V(), EmulateInstructionMIPS::Emulate_MSA_Branch_V(), EmulateInstructionMIPS64::Emulate_SD(), EmulateInstructionMIPS::Emulate_SUBU_ADDU(), EmulateInstructionMIPS::Emulate_SW(), EmulateInstructionMIPS::Emulate_SWM16_32(), EmulateInstructionMIPS::Emulate_SWSP(), lldb_private::EmulateInstructionARM::EmulateADCImm(), lldb_private::EmulateInstructionARM::EmulateADCReg(), lldb_private::EmulateInstructionPPC64::EmulateADDI(), lldb_private::EmulateInstructionARM::EmulateADDImmARM(), lldb_private::EmulateInstructionARM::EmulateADDImmThumb(), lldb_private::EmulateInstructionARM::EmulateADDRdSPImm(), lldb_private::EmulateInstructionARM::EmulateADDReg(), lldb_private::EmulateInstructionARM::EmulateADDRegShift(), lldb_private::EmulateInstructionARM::EmulateADDSPImm(), lldb_private::EmulateInstructionARM::EmulateADDSPRm(), EmulateInstructionARM64::EmulateADDSUBImm(), lldb_private::EmulateInstructionARM::EmulateADR(), lldb_private::EmulateInstructionARM::EmulateANDImm(), lldb_private::EmulateInstructionARM::EmulateANDReg(), EmulateInstructionARM64::EmulateB(), lldb_private::EmulateInstructionARM::EmulateB(), EmulateInstructionARM64::EmulateBcond(), lldb_private::EmulateInstructionARM::EmulateBICImm(), lldb_private::EmulateInstructionARM::EmulateBICReg(), lldb_private::EmulateInstructionARM::EmulateBLXImmediate(), lldb_private::EmulateInstructionARM::EmulateBLXRm(), lldb_private::EmulateInstructionARM::EmulateBXJRm(), lldb_private::EmulateInstructionARM::EmulateBXRm(), lldb_private::EmulateInstructionARM::EmulateCB(), EmulateInstructionARM64::EmulateCBZ(), lldb_private::EmulateInstructionARM::EmulateCMNImm(), lldb_private::EmulateInstructionARM::EmulateCMNReg(), lldb_private::EmulateInstructionARM::EmulateCMPImm(), lldb_private::EmulateInstructionARM::EmulateCMPReg(), lldb_private::EmulateInstructionARM::EmulateEORImm(), lldb_private::EmulateInstructionARM::EmulateEORReg(), lldb_private::EmulateInstructionPPC64::EmulateLD(), lldb_private::EmulateInstructionARM::EmulateLDM(), lldb_private::EmulateInstructionARM::EmulateLDMDA(), lldb_private::EmulateInstructionARM::EmulateLDMDB(), lldb_private::EmulateInstructionARM::EmulateLDMIB(), EmulateInstructionARM64::EmulateLDPSTP(), lldb_private::EmulateInstructionARM::EmulateLDRBImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRBLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRBRegister(), lldb_private::EmulateInstructionARM::EmulateLDRDImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRDRegister(), lldb_private::EmulateInstructionARM::EmulateLDRHImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRHLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRHRegister(), lldb_private::EmulateInstructionARM::EmulateLDRImmediateARM(), lldb_private::EmulateInstructionARM::EmulateLDRRegister(), lldb_private::EmulateInstructionARM::EmulateLDRRtPCRelative(), lldb_private::EmulateInstructionARM::EmulateLDRRtRnImm(), lldb_private::EmulateInstructionARM::EmulateLDRSBImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRSBLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRSBRegister(), lldb_private::EmulateInstructionARM::EmulateLDRSHImmediate(), lldb_private::EmulateInstructionARM::EmulateLDRSHLiteral(), lldb_private::EmulateInstructionARM::EmulateLDRSHRegister(), EmulateInstructionARM64::EmulateLDRSTRImm(), lldb_private::EmulateInstructionPPC64::EmulateMFSPR(), lldb_private::EmulateInstructionARM::EmulateMOVRdImm(), lldb_private::EmulateInstructionARM::EmulateMOVRdRm(), lldb_private::EmulateInstructionARM::EmulateMOVRdSP(), lldb_private::EmulateInstructionARM::EmulateMUL(), lldb_private::EmulateInstructionARM::EmulateMVNImm(), lldb_private::EmulateInstructionARM::EmulateMVNReg(), lldb_private::EmulateInstructionPPC64::EmulateOR(), lldb_private::EmulateInstructionARM::EmulateORRImm(), lldb_private::EmulateInstructionARM::EmulateORRReg(), lldb_private::EmulateInstructionARM::EmulatePOP(), lldb_private::EmulateInstructionARM::EmulatePUSH(), lldb_private::EmulateInstructionARM::EmulateRFE(), lldb_private::EmulateInstructionARM::EmulateRSBImm(), lldb_private::EmulateInstructionARM::EmulateRSBReg(), lldb_private::EmulateInstructionARM::EmulateRSCImm(), lldb_private::EmulateInstructionARM::EmulateRSCReg(), lldb_private::EmulateInstructionARM::EmulateSBCImm(), lldb_private::EmulateInstructionARM::EmulateSBCReg(), lldb_private::EmulateInstructionARM::EmulateShiftImm(), lldb_private::EmulateInstructionARM::EmulateShiftReg(), lldb_private::EmulateInstructionPPC64::EmulateSTD(), lldb_private::EmulateInstructionARM::EmulateSTM(), lldb_private::EmulateInstructionARM::EmulateSTMDA(), lldb_private::EmulateInstructionARM::EmulateSTMDB(), lldb_private::EmulateInstructionARM::EmulateSTMIB(), lldb_private::EmulateInstructionARM::EmulateSTRBImmARM(), lldb_private::EmulateInstructionARM::EmulateSTRBThumb(), lldb_private::EmulateInstructionARM::EmulateSTRDImm(), lldb_private::EmulateInstructionARM::EmulateSTRDReg(), lldb_private::EmulateInstructionARM::EmulateSTREX(), lldb_private::EmulateInstructionARM::EmulateSTRHRegister(), lldb_private::EmulateInstructionARM::EmulateSTRImmARM(), lldb_private::EmulateInstructionARM::EmulateSTRRegister(), lldb_private::EmulateInstructionARM::EmulateSTRRtSP(), lldb_private::EmulateInstructionARM::EmulateSTRThumb(), lldb_private::EmulateInstructionARM::EmulateSUBImmARM(), lldb_private::EmulateInstructionARM::EmulateSUBImmThumb(), lldb_private::EmulateInstructionARM::EmulateSUBIPSPImm(), lldb_private::EmulateInstructionARM::EmulateSUBR7IPImm(), lldb_private::EmulateInstructionARM::EmulateSUBReg(), lldb_private::EmulateInstructionARM::EmulateSUBSPcLrEtc(), lldb_private::EmulateInstructionARM::EmulateSUBSPImm(), lldb_private::EmulateInstructionARM::EmulateSUBSPReg(), lldb_private::EmulateInstructionARM::EmulateSVC(), lldb_private::EmulateInstructionARM::EmulateSXTB(), lldb_private::EmulateInstructionARM::EmulateSXTH(), lldb_private::EmulateInstructionARM::EmulateTB(), EmulateInstructionARM64::EmulateTBZ(), lldb_private::EmulateInstructionARM::EmulateTEQImm(), lldb_private::EmulateInstructionARM::EmulateTEQReg(), lldb_private::EmulateInstructionARM::EmulateTSTImm(), lldb_private::EmulateInstructionARM::EmulateTSTReg(), lldb_private::EmulateInstructionARM::EmulateUXTB(), lldb_private::EmulateInstructionARM::EmulateUXTH(), lldb_private::EmulateInstructionARM::EmulateVLD1Multiple(), lldb_private::EmulateInstructionARM::EmulateVLD1Single(), lldb_private::EmulateInstructionARM::EmulateVLD1SingleAll(), lldb_private::EmulateInstructionARM::EmulateVLDM(), lldb_private::EmulateInstructionARM::EmulateVLDR(), lldb_private::EmulateInstructionARM::EmulateVPOP(), lldb_private::EmulateInstructionARM::EmulateVPUSH(), lldb_private::EmulateInstructionARM::EmulateVST1Multiple(), lldb_private::EmulateInstructionARM::EmulateVST1Single(), lldb_private::EmulateInstructionARM::EmulateVSTM(), lldb_private::EmulateInstructionARM::EmulateVSTR(), EmulateInstructionARM64::EvaluateInstruction(), lldb_private::EmulateInstructionARM::EvaluateInstruction(), lldb_private::EmulateInstructionPPC64::EvaluateInstruction(), lldb_private::Load(), EmulateInstructionARM64::ReadInstruction(), EmulateInstructionMIPS64::ReadInstruction(), EmulateInstructionMIPS::ReadInstruction(), lldb_private::EmulateInstructionARM::ReadInstruction(), lldb_private::EmulateInstructionLoongArch::ReadInstruction(), lldb_private::EmulateInstructionPPC64::ReadInstruction(), lldb_private::EmulateInstructionRISCV::ReadMem(), lldb_private::EmulateInstructionRISCV::SetAccruedExceptions(), lldb_private::Store(), lldb_private::Rd::Write(), lldb_private::Rd::WriteAPFloat(), lldb_private::EmulateInstructionARM::WriteBits32Unknown(), lldb_private::EmulateInstructionARM::WriteBits32UnknownToMemory(), lldb_private::EmulateInstructionRISCV::WriteMem(), UnwindAssemblyInstEmulation::WriteMemory(), lldb_private::EmulateInstruction::WritePC(), and UnwindAssemblyInstEmulation::WriteRegister().
The documentation for this struct was generated from the following files:
EmulateInstruction.h
EmulateInstruction.cpp