LLDB: lldb_private::ObjCLanguageRuntime::ClassAndSelStr Struct Reference
lldb_private::ObjCLanguageRuntime::ClassAndSelStr Struct Reference
Public Member Functions
ClassAndSelStr ()=default
ClassAndSelStr (lldb::addr_t in_class_addr, llvm::StringRef in_sel_name)
bool operator== (const ClassAndSelStr &rhs)
bool operator< (const ClassAndSelStr &rhs) const
Public Attributes
lldb::addr_t class_addr = LLDB_INVALID_ADDRESS
ConstString sel_name
Detailed Description
Definition at line 397 of file ObjCLanguageRuntime.h.
Constructor & Destructor Documentation
ClassAndSelStr() [1/2]
lldb_private::ObjCLanguageRuntime::ClassAndSelStr::ClassAndSelStr () default
Referenced by operator<(), and operator==().
ClassAndSelStr() [2/2]
lldb_private::ObjCLanguageRuntime::ClassAndSelStr::ClassAndSelStr (lldb::addr_t in_class_addr, llvm::StringRef in_sel_name) inline
Definition at line 400 of file ObjCLanguageRuntime.h.
References class_addr, and sel_name.
Member Function Documentation
operator<()
bool lldb_private::ObjCLanguageRuntime::ClassAndSelStr::operator< (const ClassAndSelStr & rhs) const inline
Definition at line 407 of file ObjCLanguageRuntime.h.
References class_addr, ClassAndSelStr(), lldb_private::ConstString::Compare(), and sel_name.
operator==()
bool lldb_private::ObjCLanguageRuntime::ClassAndSelStr::operator== (const ClassAndSelStr & rhs) inline
Definition at line 403 of file ObjCLanguageRuntime.h.
References class_addr, ClassAndSelStr(), and sel_name.
Member Data Documentation
class_addr
lldb::addr_t lldb_private::ObjCLanguageRuntime::ClassAndSelStr::class_addr = LLDB_INVALID_ADDRESS
Definition at line 416 of file ObjCLanguageRuntime.h.
Referenced by ClassAndSelStr(), operator<(), and operator==().
sel_name
ConstString lldb_private::ObjCLanguageRuntime::ClassAndSelStr::sel_name
Definition at line 417 of file ObjCLanguageRuntime.h.
Referenced by ClassAndSelStr(), operator<(), and operator==().
The documentation for this struct was generated from the following file:
ObjCLanguageRuntime.h