LLDB: lldb_protocol::mcp::ServerInfo Struct Reference
lldb_protocol::mcp::ServerInfo Struct Reference
Information about this instance of lldb's MCP server for lldb-mcp to use to coordinate connecting an lldb-mcp client.
#include <Server.h>
Static Public Member Functions
static llvm::Expected< ServerInfoHandle > Write (const ServerInfo &)
Writes the server info into a unique file in ~/.lldb.
static llvm::Expected< std::vector< ServerInfo > > Load ()
Loads any server info saved in ~/.lldb.
Public Attributes
std::string connection_uri
Detailed Description
Information about this instance of lldb's MCP server for lldb-mcp to use to coordinate connecting an lldb-mcp client.
Definition at line 87 of file Server.h.
Member Function Documentation
Load()
Expected< std::vector< ServerInfo > > ServerInfo::Load () static
Loads any server info saved in ~/.lldb.
Definition at line 87 of file Server.cpp.
References lldb_private::FileSystem::CreateDataBuffer(), lldb_private::FileSystem::DirBegin(), and lldb_private::FileSystem::Instance().
Write()
Expected< ServerInfoHandle > ServerInfo::Write (const ServerInfo & info) static
Writes the server info into a unique file in ~/.lldb.
Definition at line 62 of file Server.cpp.
References lldb_private::FileSpec::CopyByAppendingPathComponent(), lldb_private::File::eOpenOptionCanCreate, lldb_private::File::eOpenOptionTruncate, lldb_private::File::eOpenOptionWriteOnly, error(), lldb_private::FileSpec::GetPath(), lldb_private::FileSystem::Instance(), lldb_private::FileSystem::Open(), and lldb_protocol::mcp::toJSON().
Referenced by lldb_private::mcp::ProtocolServerMCP::Start().
Member Data Documentation
connection_uri
std::string lldb_protocol::mcp::ServerInfo::connection_uri
Definition at line 88 of file Server.h.
Referenced by lldb_protocol::mcp::toJSON().
The documentation for this struct was generated from the following files:
Server.h
Server.cpp