LLDB: lldb_private::Rd Struct Reference
lldb_private::Rd Struct Reference
#include <RISCVInstructions.h>
Public Member Functions
bool Write (EmulateInstructionRISCV &emulator, uint64_t value)
bool WriteAPFloat (EmulateInstructionRISCV &emulator, llvm::APFloat value)
Public Attributes
uint32_t rd
Detailed Description
Definition at line 22 of file RISCVInstructions.h.
Member Function Documentation
Write()
bool lldb_private::Rd::Write (EmulateInstructionRISCV & emulator, uint64_t value)
Definition at line 127 of file EmulateInstructionRISCV.cpp.
References lldb_private::EmulateInstruction::eContextRegisterStore, lldb::eRegisterKindLLDB, lldb_private::GPREncodingToLLDB(), rd, lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::RegisterValue::SetUInt64(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegister().
WriteAPFloat()
bool lldb_private::Rd::WriteAPFloat (EmulateInstructionRISCV & emulator, llvm::APFloat value)
Definition at line 138 of file EmulateInstructionRISCV.cpp.
References lldb_private::EmulateInstruction::eContextRegisterStore, lldb::eRegisterKindLLDB, lldb_private::FPREncodingToLLDB(), rd, lldb_private::EmulateInstruction::Context::SetNoArgs(), lldb_private::RegisterValue::SetUInt64(), lldb_private::EmulateInstruction::Context::type, and lldb_private::EmulateInstruction::WriteRegister().
Member Data Documentation
rd
uint32_t lldb_private::Rd::rd
Definition at line 23 of file RISCVInstructions.h.
Referenced by Write(), and WriteAPFloat().
The documentation for this struct was generated from the following files:
RISCVInstructions.h
EmulateInstructionRISCV.cpp