LLDB: lldb_private::ObjCLanguageRuntime::ClassAndSel Struct Reference
lldb_private::ObjCLanguageRuntime::ClassAndSel Struct Reference
Public Member Functions
ClassAndSel ()=default
ClassAndSel (lldb::addr_t in_class_addr, lldb::addr_t in_sel_addr)
bool operator== (const ClassAndSel &rhs)
bool operator< (const ClassAndSel &rhs) const
Public Attributes
lldb::addr_t class_addr = LLDB_INVALID_ADDRESS
lldb::addr_t sel_addr = LLDB_INVALID_ADDRESS
Detailed Description
Definition at line 375 of file ObjCLanguageRuntime.h.
Constructor & Destructor Documentation
ClassAndSel() [1/2]
lldb_private::ObjCLanguageRuntime::ClassAndSel::ClassAndSel () default
Referenced by operator<(), and operator==().
ClassAndSel() [2/2]
lldb_private::ObjCLanguageRuntime::ClassAndSel::ClassAndSel (lldb::addr_t in_class_addr, lldb::addr_t in_sel_addr) inline
Definition at line 378 of file ObjCLanguageRuntime.h.
References class_addr, and sel_addr.
Member Function Documentation
operator<()
bool lldb_private::ObjCLanguageRuntime::ClassAndSel::operator< (const ClassAndSel & rhs) const inline
Definition at line 388 of file ObjCLanguageRuntime.h.
References class_addr, ClassAndSel(), and sel_addr.
operator==()
bool lldb_private::ObjCLanguageRuntime::ClassAndSel::operator== (const ClassAndSel & rhs) inline
Definition at line 381 of file ObjCLanguageRuntime.h.
References class_addr, ClassAndSel(), and sel_addr.
Member Data Documentation
class_addr
lldb::addr_t lldb_private::ObjCLanguageRuntime::ClassAndSel::class_addr = LLDB_INVALID_ADDRESS
Definition at line 393 of file ObjCLanguageRuntime.h.
Referenced by ClassAndSel(), operator<(), and operator==().
sel_addr
lldb::addr_t lldb_private::ObjCLanguageRuntime::ClassAndSel::sel_addr = LLDB_INVALID_ADDRESS
Definition at line 394 of file ObjCLanguageRuntime.h.
Referenced by ClassAndSel(), operator<(), and operator==().
The documentation for this struct was generated from the following file:
ObjCLanguageRuntime.h