LLDB: lldb_private::StatisticsOptions Struct Reference
lldb_private::StatisticsOptions Struct Reference
#include <Statistics.h>
Public Member Functions
void SetSummaryOnly (bool value)
bool GetSummaryOnly () const
void SetLoadAllDebugInfo (bool value)
bool GetLoadAllDebugInfo () const
void SetIncludeTargets (bool value)
bool GetIncludeTargets () const
void SetIncludeModules (bool value)
bool GetIncludeModules () const
void SetIncludeTranscript (bool value)
bool GetIncludeTranscript () const
void SetIncludePlugins (bool value)
bool GetIncludePlugins () const
Private Attributes
std::optional< bool > m_summary_only
std::optional< bool > m_load_all_debug_info
std::optional< bool > m_include_targets
std::optional< bool > m_include_modules
std::optional< bool > m_include_transcript
std::optional< bool > m_include_plugins
Detailed Description
Definition at line 183 of file Statistics.h.
Member Function Documentation
GetIncludeModules()
bool lldb_private::StatisticsOptions::GetIncludeModules () const inline
Definition at line 202 of file Statistics.h.
References GetSummaryOnly(), and m_include_modules.
Referenced by lldb_private::DebuggerStats::ReportStatistics(), and lldb_private::TargetStats::ToJSON().
GetIncludePlugins()
bool lldb_private::StatisticsOptions::GetIncludePlugins () const inline
Definition at line 216 of file Statistics.h.
References m_include_plugins.
Referenced by lldb_private::DebuggerStats::ReportStatistics().
GetIncludeTargets()
bool lldb_private::StatisticsOptions::GetIncludeTargets () const inline
Definition at line 194 of file Statistics.h.
References m_include_targets.
Referenced by lldb_private::DebuggerStats::ReportStatistics().
GetIncludeTranscript()
bool lldb_private::StatisticsOptions::GetIncludeTranscript () const inline
Definition at line 211 of file Statistics.h.
References m_include_transcript.
Referenced by CommandObjectStatsDump::DoExecute(), and lldb_private::DebuggerStats::ReportStatistics().
GetLoadAllDebugInfo()
bool lldb_private::StatisticsOptions::GetLoadAllDebugInfo () const inline
Definition at line 189 of file Statistics.h.
References m_load_all_debug_info.
Referenced by lldb_private::DebuggerStats::ReportStatistics().
GetSummaryOnly()
bool lldb_private::StatisticsOptions::GetSummaryOnly () const inline
Definition at line 186 of file Statistics.h.
References m_summary_only.
Referenced by GetIncludeModules(), lldb_private::DebuggerStats::ReportStatistics(), and lldb_private::TargetStats::ToJSON().
SetIncludeModules()
void lldb_private::StatisticsOptions::SetIncludeModules (bool value) inline
Definition at line 201 of file Statistics.h.
References m_include_modules.
SetIncludePlugins()
void lldb_private::StatisticsOptions::SetIncludePlugins (bool value) inline
Definition at line 215 of file Statistics.h.
References m_include_plugins.
SetIncludeTargets()
void lldb_private::StatisticsOptions::SetIncludeTargets (bool value) inline
Definition at line 193 of file Statistics.h.
References m_include_targets.
SetIncludeTranscript()
void lldb_private::StatisticsOptions::SetIncludeTranscript (bool value) inline
Definition at line 210 of file Statistics.h.
References m_include_transcript.
SetLoadAllDebugInfo()
void lldb_private::StatisticsOptions::SetLoadAllDebugInfo (bool value) inline
Definition at line 188 of file Statistics.h.
References m_load_all_debug_info.
SetSummaryOnly()
void lldb_private::StatisticsOptions::SetSummaryOnly (bool value) inline
Definition at line 185 of file Statistics.h.
References m_summary_only.
Member Data Documentation
m_include_modules
std::optional<bool> lldb_private::StatisticsOptions::m_include_modules private
Definition at line 227 of file Statistics.h.
Referenced by GetIncludeModules(), and SetIncludeModules().
m_include_plugins
std::optional<bool> lldb_private::StatisticsOptions::m_include_plugins private
Definition at line 229 of file Statistics.h.
Referenced by GetIncludePlugins(), and SetIncludePlugins().
m_include_targets
std::optional<bool> lldb_private::StatisticsOptions::m_include_targets private
Definition at line 226 of file Statistics.h.
Referenced by GetIncludeTargets(), and SetIncludeTargets().
m_include_transcript
std::optional<bool> lldb_private::StatisticsOptions::m_include_transcript private
Definition at line 228 of file Statistics.h.
Referenced by GetIncludeTranscript(), and SetIncludeTranscript().
m_load_all_debug_info
std::optional<bool> lldb_private::StatisticsOptions::m_load_all_debug_info private
Definition at line 225 of file Statistics.h.
Referenced by GetLoadAllDebugInfo(), and SetLoadAllDebugInfo().
m_summary_only
std::optional<bool> lldb_private::StatisticsOptions::m_summary_only private
Definition at line 224 of file Statistics.h.
Referenced by GetSummaryOnly(), and SetSummaryOnly().
The documentation for this struct was generated from the following file:
Statistics.h