LLDB: lldb_private::CompilerContext Struct Reference
lldb_private::CompilerContext Struct Reference
CompilerContext allows an array of these items to be passed to perform detailed lookups in SymbolVendor and SymbolFile functions.
#include <Type.h>
Public Member Functions
CompilerContext (CompilerContextKind t, ConstString n)
bool operator== (const CompilerContext &rhs) const
bool operator!= (const CompilerContext &rhs) const
void Dump (Stream &s) const
Public Attributes
CompilerContextKind kind
ConstString name
Detailed Description
CompilerContext allows an array of these items to be passed to perform detailed lookups in SymbolVendor and SymbolFile functions.
Definition at line 52 of file Type.h.
Constructor & Destructor Documentation
CompilerContext()
lldb_private::CompilerContext::CompilerContext (CompilerContextKind t, ConstString n) inline
Definition at line 53 of file Type.h.
References kind, and name.
Referenced by operator!=(), and operator==().
Member Function Documentation
Dump()
void CompilerContext::Dump (Stream & s) const
Definition at line 206 of file Type.cpp.
References lldb_private::AnyType, lldb_private::ClassOrStruct, lldb_private::Enum, lldb_private::Function, kind, lldb_private::Module, name, lldb_private::Namespace, lldb_private::TranslationUnit, lldb_private::Typedef, lldb_private::Union, and lldb_private::Variable.
Referenced by lldb_private::operator<<().
operator!=()
bool lldb_private::CompilerContext::operator!= (const CompilerContext & rhs) const inline
Definition at line 58 of file Type.h.
References CompilerContext().
operator==()
bool lldb_private::CompilerContext::operator== (const CompilerContext & rhs) const inline
Definition at line 55 of file Type.h.
References CompilerContext(), kind, and name.
Member Data Documentation
kind
CompilerContextKind lldb_private::CompilerContext::kind
Definition at line 62 of file Type.h.
Referenced by CompilerContext(), Dump(), and operator==().
name
ConstString lldb_private::CompilerContext::name
Definition at line 63 of file Type.h.
Referenced by CompilerContext(), Dump(), operator==(), and lldb_private::plugin::dwarf::DebugNamesDWARFIndex::SameAsEntryContext().
The documentation for this struct was generated from the following files:
Type.h
Type.cpp