LLDB: ELFLinuxPrStatus Struct Reference
ELFLinuxPrStatus Struct Reference
#include <ThreadElfCore.h>
Public Member Functions
ELFLinuxPrStatus ()
lldb_private::Status Parse (const lldb_private::DataExtractor &data, const lldb_private::ArchSpec &arch)
Static Public Member Functions
static std::optional< ELFLinuxPrStatus > Populate (const lldb::ThreadSP &thread_sp)
static size_t GetSize (const lldb_private::ArchSpec &arch)
Public Attributes
int32_t si_signo
int32_t si_code
int32_t si_errno
int16_t pr_cursig
uint64_t pr_sigpend
uint64_t pr_sighold
uint32_t pr_pid
uint32_t pr_ppid
uint32_t pr_pgrp
uint32_t pr_sid
compat_timeval pr_utime
compat_timeval pr_stime
compat_timeval pr_cutime
compat_timeval pr_cstime
Detailed Description
Definition at line 43 of file ThreadElfCore.h.
Constructor & Destructor Documentation
ELFLinuxPrStatus()
ELFLinuxPrStatus::ELFLinuxPrStatus ()
Definition at line 278 of file ThreadElfCore.cpp.
References ELFLinuxPrStatus().
Referenced by ELFLinuxPrStatus(), GetSize(), and Populate().
Member Function Documentation
GetSize()
size_t ELFLinuxPrStatus::GetSize (const lldb_private::ArchSpec & arch) static
Definition at line 282 of file ThreadElfCore.cpp.
References lldb_private::ArchSpec::eCore_x86_32_i386, lldb_private::ArchSpec::eCore_x86_32_i486, ELFLinuxPrStatus(), lldb_private::ArchSpec::GetAddressByteSize(), and lldb_private::ArchSpec::GetCore().
Referenced by Parse(), and ProcessElfCore::parseLinuxNotes().
Parse()
Status ELFLinuxPrStatus::Parse (const lldb_private::DataExtractor & data, const lldb_private::ArchSpec & arch)
Definition at line 296 of file ThreadElfCore.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::DataExtractor::GetAddress(), lldb_private::DataExtractor::GetByteSize(), GetSize(), lldb_private::DataExtractor::GetU16(), lldb_private::DataExtractor::GetU32(), pr_cstime, pr_cursig, pr_cutime, pr_pgrp, pr_pid, pr_ppid, pr_sid, pr_sighold, pr_sigpend, pr_stime, pr_utime, si_code, si_errno, and si_signo.
Referenced by ProcessElfCore::parseLinuxNotes().
Populate()
std::optional< ELFLinuxPrStatus > ELFLinuxPrStatus::Populate (const lldb::ThreadSP & thread_sp) static
Definition at line 347 of file ThreadElfCore.cpp.
References copy_timespecs(), ELFLinuxPrStatus(), lldb_private::ProcessInstanceInfo::GetCumulativeSystemTime(), lldb_private::ProcessInstanceInfo::GetCumulativeUserTime(), lldb_private::ProcessInstanceInfo::GetParentProcessID(), lldb_private::ProcessInstanceInfo::GetProcessGroupID(), lldb_private::ProcessInstanceInfo::GetProcessSessionID(), lldb_private::ProcessInstanceInfo::GetSystemTime(), lldb_private::ProcessInstanceInfo::GetUserTime(), pr_cstime, pr_cutime, pr_pgrp, pr_pid, pr_ppid, pr_sid, pr_stime, and pr_utime.
Member Data Documentation
pr_cstime
compat_timeval ELFLinuxPrStatus::pr_cstime
Definition at line 61 of file ThreadElfCore.h.
Referenced by Parse(), and Populate().
pr_cursig
int16_t ELFLinuxPrStatus::pr_cursig
Definition at line 48 of file ThreadElfCore.h.
Referenced by Parse(), and ProcessElfCore::parseLinuxNotes().
pr_cutime
compat_timeval ELFLinuxPrStatus::pr_cutime
Definition at line 60 of file ThreadElfCore.h.
Referenced by Parse(), and Populate().
pr_pgrp
uint32_t ELFLinuxPrStatus::pr_pgrp
Definition at line 55 of file ThreadElfCore.h.
Referenced by Parse(), and Populate().
pr_pid
uint32_t ELFLinuxPrStatus::pr_pid
Definition at line 53 of file ThreadElfCore.h.
Referenced by Parse(), ProcessElfCore::parseLinuxNotes(), and Populate().
pr_ppid
uint32_t ELFLinuxPrStatus::pr_ppid
Definition at line 54 of file ThreadElfCore.h.
Referenced by Parse(), and Populate().
pr_sid
uint32_t ELFLinuxPrStatus::pr_sid
Definition at line 56 of file ThreadElfCore.h.
Referenced by Parse(), and Populate().
pr_sighold
uint64_t ELFLinuxPrStatus::pr_sighold
Definition at line 51 of file ThreadElfCore.h.
Referenced by Parse().
pr_sigpend
uint64_t ELFLinuxPrStatus::pr_sigpend
Definition at line 50 of file ThreadElfCore.h.
Referenced by Parse().
pr_stime
compat_timeval ELFLinuxPrStatus::pr_stime
Definition at line 59 of file ThreadElfCore.h.
Referenced by Parse(), and Populate().
pr_utime
compat_timeval ELFLinuxPrStatus::pr_utime
Definition at line 58 of file ThreadElfCore.h.
Referenced by Parse(), and Populate().
si_code
int32_t ELFLinuxPrStatus::si_code
Definition at line 45 of file ThreadElfCore.h.
Referenced by Parse().
si_errno
int32_t ELFLinuxPrStatus::si_errno
Definition at line 46 of file ThreadElfCore.h.
Referenced by Parse().
si_signo
int32_t ELFLinuxPrStatus::si_signo
Definition at line 44 of file ThreadElfCore.h.
Referenced by Parse().
The documentation for this struct was generated from the following files:
ThreadElfCore.h
ThreadElfCore.cpp