LLDB: NSIndexPathSyntheticFrontEnd::Impl::InlinedIndexes Struct Reference
NSIndexPathSyntheticFrontEnd::Impl::InlinedIndexes Struct Reference
Public Member Functions
void SetIndexes (uint64_t value, Process &p)
size_t GetNumIndexes ()
lldb::ValueObjectSP GetIndexAtIndex (size_t idx, const CompilerType &desired_type)
void Clear ()
InlinedIndexes ()
Private Member Functions
size_t _lengthForInlinePayload (uint32_t ptr_size)
std::pair< uint64_t, bool > _indexAtPositionForInlinePayload (size_t pos)
Private Attributes
uint64_t m_indexes = 0
size_t m_count = 0
uint32_t m_ptr_size = 0
Process * m_process = nullptr
Detailed Description
Definition at line 175 of file NSIndexPath.cpp.
Constructor & Destructor Documentation
InlinedIndexes()
NSIndexPathSyntheticFrontEnd::Impl::InlinedIndexes::InlinedIndexes () inline
Definition at line 219 of file NSIndexPath.cpp.
Member Function Documentation
_indexAtPositionForInlinePayload()
std::pair< uint64_t, bool > NSIndexPathSyntheticFrontEnd::Impl::InlinedIndexes::_indexAtPositionForInlinePayload (size_t pos) inline private
Definition at line 237 of file NSIndexPath.cpp.
References m_indexes, m_ptr_size, PACKED_INDEX_SHIFT_32(), and PACKED_INDEX_SHIFT_64().
Referenced by GetIndexAtIndex().
_lengthForInlinePayload()
size_t NSIndexPathSyntheticFrontEnd::Impl::InlinedIndexes::_lengthForInlinePayload (uint32_t ptr_size) inline private
Definition at line 228 of file NSIndexPath.cpp.
References m_count, m_indexes, and m_ptr_size.
Referenced by SetIndexes().
Clear()
void NSIndexPathSyntheticFrontEnd::Impl::InlinedIndexes::Clear () inline
Definition at line 212 of file NSIndexPath.cpp.
References m_count, m_indexes, m_process, and m_ptr_size.
GetIndexAtIndex()
lldb::ValueObjectSP NSIndexPathSyntheticFrontEnd::Impl::InlinedIndexes::GetIndexAtIndex (size_t idx, const CompilerType & desired_type) inline
Definition at line 185 of file NSIndexPath.cpp.
References _indexAtPositionForInlinePayload(), lldb_private::ValueObjectConstResult::Create(), lldb_private::StreamString::GetString(), m_process, m_ptr_size, lldb_private::Stream::Printf(), and lldb_private::Value::SetCompilerType().
GetNumIndexes()
size_t NSIndexPathSyntheticFrontEnd::Impl::InlinedIndexes::GetNumIndexes () inline
Definition at line 183 of file NSIndexPath.cpp.
References m_count.
SetIndexes()
void NSIndexPathSyntheticFrontEnd::Impl::InlinedIndexes::SetIndexes (uint64_t value, Process & p) inline
Definition at line 177 of file NSIndexPath.cpp.
References _lengthForInlinePayload(), lldb_private::Process::GetAddressByteSize(), m_indexes, and m_process.
Member Data Documentation
m_count
size_t NSIndexPathSyntheticFrontEnd::Impl::InlinedIndexes::m_count = 0 private
Definition at line 223 of file NSIndexPath.cpp.
Referenced by _lengthForInlinePayload(), Clear(), and GetNumIndexes().
m_indexes
uint64_t NSIndexPathSyntheticFrontEnd::Impl::InlinedIndexes::m_indexes = 0 private
Definition at line 222 of file NSIndexPath.cpp.
Referenced by _indexAtPositionForInlinePayload(), _lengthForInlinePayload(), Clear(), and SetIndexes().
m_process
Process* NSIndexPathSyntheticFrontEnd::Impl::InlinedIndexes::m_process = nullptr private
Definition at line 225 of file NSIndexPath.cpp.
Referenced by Clear(), GetIndexAtIndex(), and SetIndexes().
m_ptr_size
uint32_t NSIndexPathSyntheticFrontEnd::Impl::InlinedIndexes::m_ptr_size = 0 private
Definition at line 224 of file NSIndexPath.cpp.
Referenced by _indexAtPositionForInlinePayload(), _lengthForInlinePayload(), Clear(), and GetIndexAtIndex().
The documentation for this struct was generated from the following file:
NSIndexPath.cpp