LLDB: lldb_private::ClassDescriptorV2::relative_list_entry_t Struct Reference
lldb_private::ClassDescriptorV2::relative_list_entry_t Struct Reference
Public Member Functions
bool Read (Process *process, lldb::addr_t addr)
Public Attributes
uint16_t m_image_index
int64_t m_list_offset
Detailed Description
Definition at line 218 of file AppleObjCClassDescriptorV2.h.
Member Function Documentation
Read()
bool ClassDescriptorV2::relative_list_entry_t::Read (Process * process, lldb::addr_t addr)
Definition at line 422 of file AppleObjCClassDescriptorV2.cpp.
References error(), lldb_private::Process::GetAddressByteSize(), lldb_private::Process::GetByteOrder(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::GetLog(), lldb_private::DataExtractor::GetU64_unchecked(), LLDB_LOG, m_image_index, m_list_offset, lldb_private::Process::ReadMemory(), and lldb_private::Types.
Member Data Documentation
m_image_index
uint16_t lldb_private::ClassDescriptorV2::relative_list_entry_t::m_image_index
Definition at line 219 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_list_offset
int64_t lldb_private::ClassDescriptorV2::relative_list_entry_t::m_list_offset
Definition at line 220 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
The documentation for this struct was generated from the following files:
AppleObjCClassDescriptorV2.h
AppleObjCClassDescriptorV2.cpp