LLDB: lldb_private::minidump::MinidumpMiscInfo Struct Reference
lldb_private::minidump::MinidumpMiscInfo Struct Reference
#include <MinidumpTypes.h>
Public Member Functions
std::optional< lldb::pid_t > GetPid () const
Static Public Member Functions
static const MinidumpMiscInfo * Parse (llvm::ArrayRef< uint8_t > &data)
Public Attributes
llvm::support::ulittle32_t size
llvm::support::ulittle32_t flags1
llvm::support::ulittle32_t process_id
llvm::support::ulittle32_t process_create_time
llvm::support::ulittle32_t process_user_time
llvm::support::ulittle32_t process_kernel_time
Detailed Description
Definition at line 69 of file MinidumpTypes.h.
Member Function Documentation
GetPid()
std::optional< lldb::pid_t > MinidumpMiscInfo::GetPid () const
Definition at line 28 of file MinidumpTypes.cpp.
References flags1, process_id, and lldb_private::minidump::ProcessID.
Referenced by lldb_private::minidump::MinidumpParser::GetPid().
Parse()
const MinidumpMiscInfo * MinidumpMiscInfo::Parse (llvm::ArrayRef< uint8_t > & data) static
Definition at line 19 of file MinidumpTypes.cpp.
References lldb_private::minidump::consumeObject(), and error().
Referenced by lldb_private::minidump::MinidumpParser::GetMiscInfo().
Member Data Documentation
flags1
llvm::support::ulittle32_t lldb_private::minidump::MinidumpMiscInfo::flags1
Definition at line 72 of file MinidumpTypes.h.
Referenced by MinidumpFileBuilder::AddMiscInfo(), and GetPid().
process_create_time
llvm::support::ulittle32_t lldb_private::minidump::MinidumpMiscInfo::process_create_time
Definition at line 74 of file MinidumpTypes.h.
process_id
llvm::support::ulittle32_t lldb_private::minidump::MinidumpMiscInfo::process_id
Definition at line 73 of file MinidumpTypes.h.
Referenced by MinidumpFileBuilder::AddMiscInfo(), and GetPid().
process_kernel_time
llvm::support::ulittle32_t lldb_private::minidump::MinidumpMiscInfo::process_kernel_time
Definition at line 76 of file MinidumpTypes.h.
process_user_time
llvm::support::ulittle32_t lldb_private::minidump::MinidumpMiscInfo::process_user_time
Definition at line 75 of file MinidumpTypes.h.
size
llvm::support::ulittle32_t lldb_private::minidump::MinidumpMiscInfo::size
Definition at line 70 of file MinidumpTypes.h.
Referenced by MinidumpFileBuilder::AddMiscInfo().
The documentation for this struct was generated from the following files:
MinidumpTypes.h
MinidumpTypes.cpp