LLDB: lldb_private::ClassDescriptorV2::class_rw_t Struct Reference
lldb_private::ClassDescriptorV2::class_rw_t Struct Reference
Public Member Functions
bool Read (Process *process, lldb::addr_t addr)
Public Attributes
uint32_t m_flags
uint32_t m_version
lldb::addr_t m_ro_ptr
union {
lldb::addr_t m_method_list_ptr
lldb::addr_t m_method_lists_ptr
};
lldb::addr_t m_properties_ptr
lldb::addr_t m_protocols_ptr
Detailed Description
Definition at line 124 of file AppleObjCClassDescriptorV2.h.
Member Function Documentation
Read()
bool ClassDescriptorV2::class_rw_t::Read (Process * process, lldb::addr_t addr)
Definition at line 89 of file AppleObjCClassDescriptorV2.cpp.
References error(), lldb_private::Process::GetABI(), lldb_private::DataExtractor::GetAddress_unchecked(), lldb_private::Process::GetAddressByteSize(), lldb_private::Process::GetByteOrder(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::DataExtractor::GetU32_unchecked(), m_flags, m_method_list_ptr, m_properties_ptr, m_ro_ptr, m_version, and lldb_private::Process::ReadMemory().
Member Data Documentation
[union]
union { ... } lldb_private::ClassDescriptorV2::class_rw_t
m_flags
uint32_t lldb_private::ClassDescriptorV2::class_rw_t::m_flags
Definition at line 125 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_method_list_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::class_rw_t::m_method_list_ptr
Definition at line 130 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_method_lists_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::class_rw_t::m_method_lists_ptr
Definition at line 131 of file AppleObjCClassDescriptorV2.h.
m_properties_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::class_rw_t::m_properties_ptr
Definition at line 133 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_protocols_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::class_rw_t::m_protocols_ptr
Definition at line 134 of file AppleObjCClassDescriptorV2.h.
m_ro_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::class_rw_t::m_ro_ptr
Definition at line 128 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_version
uint32_t lldb_private::ClassDescriptorV2::class_rw_t::m_version
Definition at line 126 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
The documentation for this struct was generated from the following files:
AppleObjCClassDescriptorV2.h
AppleObjCClassDescriptorV2.cpp