LLDB: PluginInfo Struct Reference
PluginInfo Struct Reference
Public Member Functions
PluginInfo ()=default
PluginInfo (const PluginInfo &)=delete
PluginInfo & operator= (const PluginInfo &)=delete
PluginInfo (PluginInfo &&)=default
PluginInfo & operator= (PluginInfo &&)=default
~PluginInfo ()
Static Public Member Functions
static llvm::Expected< PluginInfo > Create (const FileSpec &path)
Private Attributes
llvm::sys::DynamicLibrary library
PluginInitCallback plugin_init_callback = nullptr
PluginTermCallback plugin_term_callback = nullptr
Detailed Description
Definition at line 43 of file PluginManager.cpp.
Constructor & Destructor Documentation
PluginInfo() [1/3]
PluginInfo::PluginInfo () default
Referenced by Create(), operator=(), operator=(), PluginInfo(), and PluginInfo().
PluginInfo() [2/3]
PluginInfo::PluginInfo (const PluginInfo &) delete
References PluginInfo().
PluginInfo() [3/3]
PluginInfo::PluginInfo (PluginInfo &&) default
References PluginInfo().
~PluginInfo()
PluginInfo::~PluginInfo () inline
Definition at line 52 of file PluginManager.cpp.
References library, and plugin_term_callback.
Member Function Documentation
Create()
llvm::Expected< PluginInfo > PluginInfo::Create (const FileSpec & path) static
Definition at line 119 of file PluginManager.cpp.
References CastToFPtr(), error(), g_plugin_prefix, lldb_private::FileSpec::GetFileNameStrippingExtension(), lldb_private::FileSpec::GetPath(), lldb_private::ConstString::GetStringRef(), library, plugin_init_callback, plugin_term_callback, and PluginInfo().
Referenced by LoadPluginCallback().
operator=() [1/2]
PluginInfo & PluginInfo::operator= (const PluginInfo &) delete
References PluginInfo().
operator=() [2/2]
PluginInfo & PluginInfo::operator= (PluginInfo &&) default
References PluginInfo().
Member Data Documentation
library
llvm::sys::DynamicLibrary PluginInfo::library private
Definition at line 63 of file PluginManager.cpp.
Referenced by Create(), and ~PluginInfo().
plugin_init_callback
PluginInitCallback PluginInfo::plugin_init_callback = nullptr private
Definition at line 64 of file PluginManager.cpp.
Referenced by Create().
plugin_term_callback
PluginTermCallback PluginInfo::plugin_term_callback = nullptr private
Definition at line 65 of file PluginManager.cpp.
Referenced by Create(), and ~PluginInfo().
The documentation for this struct was generated from the following file:
PluginManager.cpp