LLDB: PlatformAppleTVSimulator Struct Reference
PlatformAppleTVSimulator Struct Reference
Apple TV Simulator Plugin.
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static PlatformSP CreateInstance (bool force, const ArchSpec *arch)
Detailed Description
Apple TV Simulator Plugin.
Definition at line 529 of file PlatformAppleSimulator.cpp.
Member Function Documentation
CreateInstance()
PlatformSP PlatformAppleTVSimulator::CreateInstance (bool force, const ArchSpec * arch) inline static
Definition at line 539 of file PlatformAppleSimulator.cpp.
References CoreSimulatorSupport::DeviceType::appleTV, lldb_private::XcodeSDK::AppleTVSimulator, lldb_private::PlatformAppleSimulator::CreateInstance(), g_tvos_description, g_tvos_plugin_name, and shouldSkipSimulatorPlatform().
Referenced by Initialize(), and Terminate().
Initialize()
void PlatformAppleTVSimulator::Initialize () inline static
Definition at line 530 of file PlatformAppleSimulator.cpp.
References CreateInstance(), g_tvos_description, g_tvos_plugin_name, and lldb_private::PluginManager::RegisterPlugin().
Referenced by lldb_private::PlatformAppleSimulator::Initialize().
Terminate()
void PlatformAppleTVSimulator::Terminate () inline static
Definition at line 535 of file PlatformAppleSimulator.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Referenced by lldb_private::PlatformAppleSimulator::Terminate().
The documentation for this struct was generated from the following file:
PlatformAppleSimulator.cpp