LLDB: lldb_private::TypeCategoryImpl::ForEachCallback< T > Struct Template Reference
lldb_private::TypeCategoryImpl::ForEachCallback< T > Struct Template Reference
#include <TypeCategory.h>
Public Member Functions
template<typename Callable>
ForEachCallback (Callable c)
Public Attributes
std::function< bool(const TypeMatcher &, const std::shared_ptr< T > &)> callback
Detailed Description
template<typename T>
struct lldb_private::TypeCategoryImpl::ForEachCallback< T >
Definition at line 183 of file TypeCategory.h.
Constructor & Destructor Documentation
ForEachCallback()
template<typename T> template<typename Callable> lldb_private::TypeCategoryImpl::ForEachCallback< T >::ForEachCallback (Callable c) inline
Definition at line 187 of file TypeCategory.h.
References callback.
Member Data Documentation
callback
template<typename T> std::function<bool(const TypeMatcher &, const std::shared_ptr<T> &)> lldb_private::TypeCategoryImpl::ForEachCallback< T >::callback
Definition at line 189 of file TypeCategory.h.
Referenced by lldb_private::TypeCategoryImpl::ForEach(), lldb_private::TypeCategoryImpl::ForEach(), lldb_private::TypeCategoryImpl::ForEach(), lldb_private::TypeCategoryImpl::ForEach(), and ForEachCallback().
The documentation for this struct was generated from the following file:
TypeCategory.h