LLDB: lldb_private::Args::ArgEntry Struct Reference
lldb_private::Args::ArgEntry Struct Reference
#include <Args.h>
Public Member Functions
ArgEntry ()=default
ArgEntry (llvm::StringRef str, char quote, std::optional< uint16_t > column)
llvm::StringRef ref () const
const char * c_str () const
bool IsQuoted () const
Returns true if this argument was quoted in any way.
char GetQuoteChar () const
std::optional< uint16_t > GetPos () const
size_t GetLength () const
Private Member Functions
char * data ()
Private Attributes
std::unique_ptr< char[]> ptr
char quote = '\0'
std::optional< uint16_t > column
The position of the argument in the original argument string.
Friends
class Args
Detailed Description
Definition at line 35 of file Args.h.
Constructor & Destructor Documentation
ArgEntry() [1/2]
lldb_private::Args::ArgEntry::ArgEntry () default
References column, and quote.
ArgEntry() [2/2]
Args::ArgEntry::ArgEntry (llvm::StringRef str, char quote, std::optional< uint16_t > column)
Definition at line 161 of file Args.cpp.
References column, data(), ptr, quote, and lldb_private::Args::size().
Member Function Documentation
c_str()
const char * lldb_private::Args::ArgEntry::c_str () const inline
Definition at line 51 of file Args.h.
References ptr.
Referenced by lldb_private::CommandInterpreter::BuildAliasResult(), lldb_private::CommandObjectParsed::Execute(), FindOriginalIter(), and ref().
data()
char * lldb_private::Args::ArgEntry::data () inline private
Definition at line 44 of file Args.h.
References ptr.
Referenced by ArgEntry().
GetLength()
size_t lldb_private::Args::ArgEntry::GetLength () const inline
Definition at line 57 of file Args.h.
References ref().
GetPos()
std::optional< uint16_t > lldb_private::Args::ArgEntry::GetPos () const inline
Definition at line 56 of file Args.h.
References column.
Referenced by lldb_private::OptionParseError::OptionParseError().
GetQuoteChar()
char lldb_private::Args::ArgEntry::GetQuoteChar () const inline
Definition at line 55 of file Args.h.
References quote.
Referenced by lldb_private::CommandInterpreter::BuildAliasResult(), lldb_private::CommandObjectParsed::Execute(), lldb::SBCommandInterpreter::HandleCompletionWithDescriptions(), and lldb_private::Editline::TabCommand().
IsQuoted()
bool lldb_private::Args::ArgEntry::IsQuoted () const inline
Returns true if this argument was quoted in any way.
Definition at line 54 of file Args.h.
References quote.
Referenced by lldb::SBCommandInterpreter::HandleCompletionWithDescriptions(), lldb_private::Options::ParseForCompletion(), lldb_private::OptionsWithRaw::SetFromString(), and lldb_private::Editline::TabCommand().
ref()
llvm::StringRef lldb_private::Args::ArgEntry::ref () const inline
Definition at line 50 of file Args.h.
References c_str().
Referenced by lldb_private::CommandInterpreter::BuildAliasResult(), lldb_private::CommandObjectParsed::Execute(), GetLength(), CommandObjectSourceList::GetRepeatCommand(), and lldb_private::Options::ParseForCompletion().
Friends And Related Symbol Documentation
Args
friend class Args friend
Definition at line 37 of file Args.h.
References Args.
Referenced by Args.
Member Data Documentation
column
std::optional<uint16_t> lldb_private::Args::ArgEntry::column private
The position of the argument in the original argument string.
Definition at line 42 of file Args.h.
Referenced by ArgEntry(), ArgEntry(), and GetPos().
ptr
std::unique_ptr<char[]> lldb_private::Args::ArgEntry::ptr private
Definition at line 39 of file Args.h.
Referenced by ArgEntry(), c_str(), and data().
quote
char lldb_private::Args::ArgEntry::quote = '\0' private
Definition at line 40 of file Args.h.
Referenced by ArgEntry(), ArgEntry(), GetQuoteChar(), and IsQuoted().
The documentation for this struct was generated from the following files:
Args.h
Args.cpp