LLDB: lldb_private::TreeSitterHighlighter::TSState Struct Reference
lldb_private::TreeSitterHighlighter::TSState Struct Reference
Public Member Functions
TSState ()=default
TSState & operator= (const TSState &)=delete
TSState (const TSState &)=delete
~TSState ()
operator bool () const
Public Attributes
TSParser * parser = nullptr
TSQuery * query = nullptr
Detailed Description
Definition at line 59 of file TreeSitterHighlighter.h.
Constructor & Destructor Documentation
TSState() [1/2]
lldb_private::TreeSitterHighlighter::TSState::TSState () default
Referenced by operator=(), and TSState().
TSState() [2/2]
lldb_private::TreeSitterHighlighter::TSState::TSState (const TSState &) delete
References TSState().
~TSState()
TreeSitterHighlighter::TSState::~TSState ()
Definition at line 18 of file TreeSitterHighlighter.cpp.
References parser, and query.
Member Function Documentation
operator bool()
TreeSitterHighlighter::TSState::operator bool () const explicit
Definition at line 25 of file TreeSitterHighlighter.cpp.
References parser, and query.
operator=()
TSState & lldb_private::TreeSitterHighlighter::TSState::operator= (const TSState &) delete
References TSState().
Member Data Documentation
parser
TSParser* lldb_private::TreeSitterHighlighter::TSState::parser = nullptr
Definition at line 66 of file TreeSitterHighlighter.h.
Referenced by lldb_private::TreeSitterHighlighter::Highlight(), operator bool(), and ~TSState().
query
TSQuery* lldb_private::TreeSitterHighlighter::TSState::query = nullptr
Definition at line 67 of file TreeSitterHighlighter.h.
Referenced by lldb_private::TreeSitterHighlighter::Highlight(), operator bool(), and ~TSState().
The documentation for this struct was generated from the following files:
TreeSitterHighlighter.h
TreeSitterHighlighter.cpp