LLDB: PlatformAppleWatchSimulator Struct Reference
PlatformAppleWatchSimulator Struct Reference
Apple Watch Simulator Plugin.
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static PlatformSP CreateInstance (bool force, const ArchSpec *arch)
Detailed Description
Apple Watch Simulator Plugin.
Definition at line 570 of file PlatformAppleSimulator.cpp.
Member Function Documentation
CreateInstance()
PlatformSP PlatformAppleWatchSimulator::CreateInstance (bool force, const ArchSpec * arch) inline static
Definition at line 581 of file PlatformAppleSimulator.cpp.
References CoreSimulatorSupport::DeviceType::appleWatch, lldb_private::PlatformAppleSimulator::CreateInstance(), g_watchos_description, g_watchos_plugin_name, shouldSkipSimulatorPlatform(), and lldb_private::XcodeSDK::WatchSimulator.
Referenced by Initialize(), and Terminate().
Initialize()
void PlatformAppleWatchSimulator::Initialize () inline static
Definition at line 571 of file PlatformAppleSimulator.cpp.
References CreateInstance(), g_watchos_description, g_watchos_plugin_name, and lldb_private::PluginManager::RegisterPlugin().
Referenced by lldb_private::PlatformAppleSimulator::Initialize().
Terminate()
void PlatformAppleWatchSimulator::Terminate () inline static
Definition at line 576 of file PlatformAppleSimulator.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Referenced by lldb_private::PlatformAppleSimulator::Terminate().
The documentation for this struct was generated from the following file:
PlatformAppleSimulator.cpp