LLDB: lldb_private::Process::PreResumeCallbackAndBaton Struct Reference
lldb_private::Process::PreResumeCallbackAndBaton Struct Reference
#include <Process.h>
Public Member Functions
PreResumeCallbackAndBaton (PreResumeActionCallback in_callback, void *in_baton)
bool operator== (const PreResumeCallbackAndBaton &rhs)
Public Attributes
bool(* callback)(void *)
void * baton
Detailed Description
Definition at line 3185 of file Process.h.
Constructor & Destructor Documentation
PreResumeCallbackAndBaton()
lldb_private::Process::PreResumeCallbackAndBaton::PreResumeCallbackAndBaton (PreResumeActionCallback in_callback, void * in_baton) inline
Definition at line 3188 of file Process.h.
References baton, and callback.
Referenced by operator==().
Member Function Documentation
operator==()
bool lldb_private::Process::PreResumeCallbackAndBaton::operator== (const PreResumeCallbackAndBaton & rhs) inline
Definition at line 3191 of file Process.h.
References baton, callback, and PreResumeCallbackAndBaton().
Member Data Documentation
baton
void* lldb_private::Process::PreResumeCallbackAndBaton::baton
Definition at line 3187 of file Process.h.
Referenced by operator==(), PreResumeCallbackAndBaton(), and lldb_private::Process::RunPreResumeActions().
callback
bool(* lldb_private::Process::PreResumeCallbackAndBaton::callback) (void *)
Definition at line 3186 of file Process.h.
Referenced by operator==(), PreResumeCallbackAndBaton(), and lldb_private::Process::RunPreResumeActions().
The documentation for this struct was generated from the following file:
Process.h