LLDB: lldb_private::LineEntry Class Reference
lldb_private::LineEntry Class Reference
A line table entry class.
#include "lldb/Symbol/LineEntry.h"
Public Member Functions
LineEntry ()
Default constructor.
void Clear ()
Clear the object's state.
bool Dump (Stream *s, Target *target, bool show_file, Address::DumpStyle style, Address::DumpStyle fallback_style, bool show_range) const
Dump a description of this object to a Stream.
bool GetDescription (Stream *s, lldb::DescriptionLevel level, CompileUnit *cu, Target *target, bool show_address_only) const
bool DumpStopContext (Stream *s, bool show_fullpaths) const
Dumps information specific to a process that stops at this line entry to the supplied stream s.
bool IsValid () const
Check if a line entry object is valid.
AddressRange GetSameLineContiguousAddressRange (bool include_inlined_functions) const
Give the range for this LineEntry + any additional LineEntries for this same source line that are contiguous.
void ApplyFileMappings (lldb::TargetSP target_sp)
Apply file mappings from target.source-map to the LineEntry's file.
const FileSpec & GetFile () const
Helper to access the file.
Static Public Member Functions
static int Compare (const LineEntry &lhs, const LineEntry &rhs)
Compare two LineEntry objects.
Public Attributes
AddressRange range
The section offset address range for this line entry.
bool synthetic = false
This gets set for LineEntries created without a valid address range.
SupportFileNSP file_sp
The source file, possibly mapped by the target.source-map setting.
SupportFileNSP original_file_sp
The original source file, from debug info.
uint32_t line = LLDB_INVALID_LINE_NUMBER
The source line number, or LLDB_INVALID_LINE_NUMBER if there is no line number information.
uint16_t column = 0
The column number of the source line, or zero if there is no column information.
uint16_t is_start_of_statement: 1
Indicates this entry is the beginning of a statement.
uint16_t is_start_of_basic_block: 1
Indicates this entry is the beginning of a basic block.
uint16_t is_prologue_end: 1
Indicates this entry is one (of possibly many) where execution should be suspended for an entry breakpoint of a function.
uint16_t is_epilogue_begin: 1
Indicates this entry is one (of possibly many) where execution should be suspended for an exit breakpoint of a function.
uint16_t is_terminal_entry: 1
Indicates this entry is that of the first byte after the end of a sequence of target machine instructions.
Detailed Description
A line table entry class.
Definition at line 21 of file LineEntry.h.
Constructor & Destructor Documentation
LineEntry()
LineEntry::LineEntry ()
Default constructor.
Initialize all member variables to invalid values.
Definition at line 16 of file LineEntry.cpp.
References file_sp, is_epilogue_begin, is_prologue_end, is_start_of_basic_block, is_start_of_statement, is_terminal_entry, original_file_sp, range, and synthetic.
Referenced by Compare().
Member Function Documentation
ApplyFileMappings()
void LineEntry::ApplyFileMappings (lldb::TargetSP target_sp)
Apply file mappings from target.source-map to the LineEntry's file.
Parameters
[in] target_sp Shared pointer to the target this LineEntry belongs to.
Definition at line 245 of file LineEntry.cpp.
References file_sp, and original_file_sp.
Referenced by lldb_private::StackFrameList::FetchFramesUpTo(), lldb_private::Module::ResolveSymbolContextForAddress(), and lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint().
Clear()
void LineEntry::Clear ()
Clear the object's state.
Clears all member variables to invalid values.
Definition at line 22 of file LineEntry.cpp.
References column, file_sp, is_epilogue_begin, is_prologue_end, is_start_of_basic_block, is_start_of_statement, is_terminal_entry, line, LLDB_INVALID_LINE_NUMBER, original_file_sp, and range.
Referenced by lldb_private::Address::CalculateSymbolContextLineEntry(), lldb_private::Variable::DumpDeclaration(), lldb_private::LineTable::GetLineEntryAtIndex(), and lldb::SBSymbolContext::SetLineEntry().
Compare()
int LineEntry::Compare (const LineEntry & lhs, const LineEntry & rhs) static
Compare two LineEntry objects.
Parameters
[in] lhs The Left Hand Side const LineEntry object reference.
[in] rhs The Right Hand Side const LineEntry object reference.
Returns
-1 if lhs < rhs 0 if lhs == rhs 1 if lhs > rhs
Definition at line 148 of file LineEntry.cpp.
References column, lldb_private::FileSpec::Compare(), lldb_private::Address::CompareFileAddress(), lldb_private::AddressRange::GetBaseAddress(), lldb_private::AddressRange::GetByteSize(), GetFile(), is_terminal_entry, line, LineEntry(), and range.
Referenced by lldb_private::BreakpointResolver::AddLocation(), lldb_private::SymbolContext::CompareWithoutSymbol(), lldb_private::SymbolContext::GetAddressRangeFromHereToEndLine(), lldb_private::BreakpointLocation::GetSuggestedStackFrameIndex(), lldb::SBLineEntry::operator!=(), lldb_private::operator<(), and lldb::SBLineEntry::operator==().
Dump()
bool LineEntry::Dump (Stream * s, Target * target, bool show_file, Address::DumpStyle style, Address::DumpStyle fallback_style, bool show_range) const
Dump a description of this object to a Stream.
Dump a description of the contents of this object to the supplied stream s.
Parameters
[in] s The stream to which to dump the object description.
[in] show_file If true, display the filename with the line entry which requires that the compile unit object comp_unit be a valid pointer.
[in] style The display style for the section offset address.
Returns
Returns true if the address was able to be displayed using style. File and load addresses may be unresolved and it may not be possible to display a valid address value. Returns false if the address was not able to be properly dumped.
See also
Address::DumpStyle
Definition at line 61 of file LineEntry.cpp.
References column, GetFile(), is_epilogue_begin, is_prologue_end, is_start_of_basic_block, is_start_of_statement, is_terminal_entry, line, lldb_private::Stream::Printf(), and range.
Referenced by lldb_private::LineTable::Dump(), and GetDescription().
DumpStopContext()
bool LineEntry::DumpStopContext (Stream * s, bool show_fullpaths) const
Dumps information specific to a process that stops at this line entry to the supplied stream s.
Parameters
[in] s The stream to which to dump the object description.
Returns
Returns true if the file and line were properly dumped, false otherwise.
Definition at line 40 of file LineEntry.cpp.
References lldb_private::Stream::AsRawOstream(), column, lldb_private::ConstString::Dump(), lldb_private::FileSpec::Dump(), file_sp, lldb_private::FileSpec::GetFilename(), line, lldb_private::Stream::Printf(), and lldb_private::Stream::PutChar().
Referenced by lldb_private::BreakpointLocation::GetDescription().
GetDescription()
bool LineEntry::GetDescription (Stream * s, lldb::DescriptionLevel level, CompileUnit * cu, Target * target, bool show_address_only) const
Definition at line 96 of file LineEntry.cpp.
References column, Dump(), lldb_private::Address::DumpStyleFileAddress, lldb_private::Address::DumpStyleLoadAddress, lldb_private::Address::DumpStyleModuleWithFileAddress, lldb::eDescriptionLevelBrief, lldb::eDescriptionLevelFull, lldb_private::Stream::EOL(), GetFile(), is_epilogue_begin, is_prologue_end, is_start_of_basic_block, is_start_of_statement, is_terminal_entry, line, lldb_private::Stream::Printf(), and range.
Referenced by CommandObjectSourceInfo::DumpFileLinesInCompUnit(), CommandObjectSourceInfo::DumpLinesInSymbolContexts(), and lldb_private::LineTable::GetDescription().
GetFile()
const FileSpec & lldb_private::LineEntry::GetFile () const inline
Helper to access the file.
Definition at line 134 of file LineEntry.h.
References file_sp.
Referenced by Compare(), CommandObjectThreadJump::DoExecute(), Dump(), CommandObjectSourceInfo::DumpFileLinesInCompUnit(), CommandObjectSourceInfo::DumpLinesInSymbolContexts(), lldb_private::Disassembler::ElideMixedSourceAndDisassemblyLine(), FileLineAndColumnMatches(), lldb_private::BreakpointResolverFileLine::FilterContexts(), GetDefaultFile(), lldb_private::Address::GetDescription(), GetDescription(), lldb_private::Thread::GetStatus(), lldb_private::BreakpointLocation::GetSuggestedStackFrameIndex(), lldb_private::ClangExpressionSourceCode::GetText(), lldb_private::formatters::LibcxxFunctionSummaryProvider(), CommandObjectSourceList::SourceInfo::operator<(), lldb_private::Disassembler::PrintInstructions(), lldb_private::CompileUnit::ResolveSymbolContext(), lldb_private::StackFrameList::SetDefaultFileAndLineToSelectedFrame(), lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint(), lldb_private::Thread::SetSelectedFrameByIndexNoisily(), and lldb::SBThread::StepOverUntil().
GetSameLineContiguousAddressRange()
AddressRange LineEntry::GetSameLineContiguousAddressRange (bool include_inlined_functions) const
Give the range for this LineEntry + any additional LineEntries for this same source line that are contiguous.
A compiler may emit multiple line entries for a single source line, e.g. to indicate subexpressions at different columns. This method will get the AddressRange for all of the LineEntries for this source line that are contiguous. Line entries with a line number of 0 are treated specially - these are compiler-generated line table entries that the user did not write in their source code, and we want to skip past in the debugger. If this LineEntry is for line 32, and the following LineEntry is for line 0, we will extend the range to include the AddressRange of the line 0 LineEntry (and it will include the range of the following LineEntries that match either 32 or 0.)
When include_inlined_functions is true inlined functions with a call site at this LineEntry will also be included in the complete range.
If the initial LineEntry this method is called on is a line #0, only the range of continuous LineEntries with line #0 will be included in the complete range.
Parameters
[in] include_inlined_functions Whether to include inlined functions at the same line or not.
Returns
The contiguous AddressRange for this source line.
Definition at line 183 of file LineEntry.cpp.
References lldb_private::SymbolContext::block, lldb_private::Address::CalculateSymbolContext(), lldb_private::SupportFile::eEqualFileSpecAndChecksumIfSet, lldb_private::AddressRange::Extend(), lldb_private::AddressRange::GetBaseAddress(), lldb_private::AddressRange::GetByteSize(), lldb_private::Block::GetContainingInlinedBlock(), lldb_private::Block::GetContainingInlinedBlockWithCallSite(), IsValid(), line, lldb_private::SymbolContext::line_entry, original_file_sp, range, and lldb_private::Address::Slide().
Referenced by lldb_private::Thread::QueueThreadPlanForStepInRange(), lldb_private::Thread::QueueThreadPlanForStepOverRange(), and lldb_private::ThreadPlanStepOut::SetupReturnAddress().
IsValid()
bool LineEntry::IsValid () const
Check if a line entry object is valid.
Returns
Returns true if the line entry contains a valid section offset address, file index, and line number, false otherwise.
Definition at line 35 of file LineEntry.cpp.
References line, LLDB_INVALID_LINE_NUMBER, range, and synthetic.
Referenced by lldb_private::SymbolContextList::AppendIfUnique(), lldb_private::Address::CalculateSymbolContextLineEntry(), lldb_private::CommandObjectDisassemble::GetCurrentLineRanges(), lldb_private::Disassembler::GetFunctionDeclLineEntry(), llvm::DenseMapInfo< lldb_private::SymbolContext >::getHashValue(), GetSameLineContiguousAddressRange(), lldb_private::ClangExpressionSourceCode::GetText(), lldb_private::ThreadPlanStepRange::InRange(), IsLineEntryValid(), lldb_private::Disassembler::PrintInstructions(), lldb_private::CompileUnit::ResolveSymbolContext(), lldb_private::Module::ResolveSymbolContextForAddress(), lldb::SBLineEntry::SetLine(), lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint(), lldb_private::ThreadPlanStepOut::SetupReturnAddress(), lldb_private::ThreadPlanStepOverRange::ShouldStop(), and lldb::SBThread::StepOverUntil().
Member Data Documentation
column
uint16_t lldb_private::LineEntry::column = 0
The column number of the source line, or zero if there is no column information.
Definition at line 155 of file LineEntry.h.
Referenced by Clear(), Compare(), lldb_private::LineTable::ConvertEntryAtIndexToLineEntry(), Dump(), OutputWriterCLI::DumpSegmentContext(), DumpStopContext(), lldb_private::Disassembler::ElideMixedSourceAndDisassemblyLine(), FileLineAndColumnMatches(), lldb_private::Address::GetDescription(), GetDescription(), llvm::DenseMapInfo< lldb_private::SymbolContext >::getHashValue(), lldb_private::SymbolContext::GetParentOfInlinedScope(), lldb_private::BreakpointLocation::GetSuggestedStackFrameIndex(), lldb_private::Disassembler::PrintInstructions(), lldb_private::CompileUnit::ResolveSymbolContext(), lldb::SBLineEntry::SetColumn(), and lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint().
file_sp
SupportFileNSP lldb_private::LineEntry::file_sp
The source file, possibly mapped by the target.source-map setting.
Definition at line 144 of file LineEntry.h.
Referenced by ApplyFileMappings(), Clear(), lldb_private::LineTable::ConvertEntryAtIndexToLineEntry(), CommandObjectSourceList::DisplayFunctionSource(), CommandObjectSourceList::DoExecute(), DumpStopContext(), lldb_private::BreakpointResolverFileLine::FilterContexts(), lldb_private::SourceManager::GetDefaultFileAndLine(), GetFile(), lldb_private::Disassembler::GetFunctionDeclLineEntry(), lldb_private::SymbolContext::GetParentOfInlinedScope(), lldb_private::Function::GetSourceInfo(), lldb_private::Function::GetStartLineSourceInfo(), LineEntry(), lldb_private::Disassembler::PrintInstructions(), lldb_private::StackFrameList::SetDefaultFileAndLineToSelectedFrame(), lldb::SBLineEntry::SetFileSpec(), and lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint().
is_epilogue_begin
uint16_t lldb_private::LineEntry::is_epilogue_begin
Indicates this entry is one (of possibly many) where execution should be suspended for an exit breakpoint of a function.
Definition at line 169 of file LineEntry.h.
Referenced by Clear(), lldb_private::LineTable::ConvertEntryAtIndexToLineEntry(), Dump(), GetDescription(), and LineEntry().
is_prologue_end
uint16_t lldb_private::LineEntry::is_prologue_end
Indicates this entry is one (of possibly many) where execution should be suspended for an entry breakpoint of a function.
Definition at line 165 of file LineEntry.h.
Referenced by Clear(), lldb_private::LineTable::ConvertEntryAtIndexToLineEntry(), Dump(), GetDescription(), lldb_private::Function::GetPrologueByteSize(), and LineEntry().
is_start_of_basic_block
uint16_t lldb_private::LineEntry::is_start_of_basic_block
Indicates this entry is the beginning of a basic block.
Definition at line 161 of file LineEntry.h.
Referenced by Clear(), lldb_private::LineTable::ConvertEntryAtIndexToLineEntry(), Dump(), GetDescription(), and LineEntry().
is_start_of_statement
uint16_t lldb_private::LineEntry::is_start_of_statement
Indicates this entry is the beginning of a statement.
Definition at line 158 of file LineEntry.h.
Referenced by Clear(), lldb_private::LineTable::ConvertEntryAtIndexToLineEntry(), Dump(), GetDescription(), and LineEntry().
is_terminal_entry
uint16_t lldb_private::LineEntry::is_terminal_entry
Indicates this entry is that of the first byte after the end of a sequence of target machine instructions.
Definition at line 173 of file LineEntry.h.
Referenced by Clear(), Compare(), lldb_private::LineTable::ConvertEntryAtIndexToLineEntry(), Dump(), GetDescription(), llvm::DenseMapInfo< lldb_private::SymbolContext >::getHashValue(), and LineEntry().
line
uint32_t lldb_private::LineEntry::line = LLDB_INVALID_LINE_NUMBER
The source line number, or LLDB_INVALID_LINE_NUMBER if there is no line number information.
Definition at line 151 of file LineEntry.h.
Referenced by Clear(), Compare(), lldb_private::LineTable::ConvertEntryAtIndexToLineEntry(), lldb_private::ThreadPlanShouldStopHere::DefaultShouldStopHereCallback(), lldb_private::ThreadPlanShouldStopHere::DefaultStepFromHereCallback(), CommandObjectSourceList::DisplayFunctionSource(), CommandObjectThreadJump::DoExecute(), CommandObjectThreadUntil::DoExecute(), Dump(), CommandObjectSourceInfo::DumpFileLinesInCompUnit(), CommandObjectSourceInfo::DumpLinesInSymbolContexts(), OutputWriterCLI::DumpSegmentContext(), DumpStopContext(), lldb_private::Disassembler::ElideMixedSourceAndDisassemblyLine(), FileLineAndColumnMatches(), lldb_private::BreakpointResolverFileLine::FilterContexts(), lldb_private::SourceManager::GetDefaultFileAndLine(), lldb_private::Address::GetDescription(), lldb_private::BreakpointLocation::GetDescription(), GetDescription(), llvm::DenseMapInfo< lldb_private::SymbolContext >::getHashValue(), lldb_private::SymbolContext::GetParentOfInlinedScope(), lldb_private::Function::GetPrologueByteSize(), lldb_private::Symbol::GetPrologueByteSize(), GetSameLineContiguousAddressRange(), lldb_private::Function::GetSourceInfo(), lldb_private::Function::GetStartLineSourceInfo(), lldb_private::Thread::GetStatus(), lldb_private::BreakpointLocation::GetSuggestedStackFrameIndex(), lldb_private::ClangExpressionSourceCode::GetText(), lldb_private::ThreadPlanStepRange::InRange(), IsLineEntryValid(), IsValid(), lldb_private::formatters::LibcxxFunctionSummaryProvider(), CommandObjectSourceList::SourceInfo::operator!=(), CommandObjectSourceList::SourceInfo::operator<(), CommandObjectSourceList::SourceInfo::operator==(), lldb_private::Disassembler::PrintInstructions(), lldb_private::CompileUnit::ResolveSymbolContext(), lldb_private::StackFrameList::SetDefaultFileAndLineToSelectedFrame(), lldb::SBLineEntry::SetLine(), lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint(), lldb_private::BreakpointResolver::SetSCMatchesByLine(), lldb_private::Thread::SetSelectedFrameByIndexNoisily(), and lldb_private::SymbolContextSpecifier::SymbolContextMatches().
original_file_sp
SupportFileNSP lldb_private::LineEntry::original_file_sp
The original source file, from debug info.
Definition at line 147 of file LineEntry.h.
Referenced by ApplyFileMappings(), Clear(), lldb_private::LineTable::ConvertEntryAtIndexToLineEntry(), lldb_private::LineTable::Dump(), lldb_private::Disassembler::GetFunctionDeclLineEntry(), lldb_private::SymbolContext::GetParentOfInlinedScope(), GetSameLineContiguousAddressRange(), lldb_private::ThreadPlanStepRange::InRange(), LineEntry(), CommandObjectSourceList::SourceInfo::operator!=(), CommandObjectSourceList::SourceInfo::operator==(), lldb_private::Disassembler::PrintInstructions(), lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint(), and lldb_private::ThreadPlanStepOverRange::ShouldStop().
range
AddressRange lldb_private::LineEntry::range
The section offset address range for this line entry.
Definition at line 137 of file LineEntry.h.
Referenced by lldb_private::BreakpointResolver::AddLocation(), Clear(), Compare(), lldb_private::LineTable::ConvertEntryAtIndexToLineEntry(), lldb_private::ThreadPlanShouldStopHere::DefaultStepFromHereCallback(), CommandObjectThreadStepWithTypeAndScope::DoExecute(), CommandObjectThreadUntil::DoExecute(), Dump(), lldb_private::StringSummaryFormat::FormatObject(), lldb_private::SymbolContext::GetAddressRangeFromHereToEndLine(), lldb_private::CommandObjectDisassemble::GetCurrentLineRanges(), GetDescription(), llvm::DenseMapInfo< lldb_private::SymbolContext >::getHashValue(), lldb_private::SymbolContext::GetParentOfInlinedScope(), lldb_private::Function::GetPrologueByteSize(), lldb_private::Symbol::GetPrologueByteSize(), GetSameLineContiguousAddressRange(), lldb_private::ThreadPlanStepRange::InRange(), IsValid(), LineEntry(), lldb_private::CompileUnit::ResolveSymbolContext(), lldb_private::ThreadPlanStepRange::SetNextBranchBreakpoint(), lldb_private::BreakpointLocation::SetPreferredLineEntry(), lldb_private::BreakpointResolver::SetSCMatchesByLine(), lldb_private::ThreadPlanStepOverRange::ShouldStop(), and lldb::SBThread::StepInto().
synthetic
bool lldb_private::LineEntry::synthetic = false
This gets set for LineEntries created without a valid address range.
When set, LineEntry::IsValid doesn't check the range validity.
Definition at line 141 of file LineEntry.h.
Referenced by IsValid(), LineEntry(), and lldb::SBLineEntry::SetLine().
The documentation for this class was generated from the following files:
LineEntry.h
LineEntry.cpp