LLDB: lldb_private::UniqueCStringMap< T >::Compare Struct Reference
lldb_private::UniqueCStringMap< T >::Compare Struct Reference
#include <UniqueCStringMap.h>
Public Member Functions
bool operator() (const Entry &lhs, const Entry &rhs)
bool operator() (const Entry &lhs, ConstString rhs)
bool operator() (ConstString lhs, const Entry &rhs)
bool operator() (ConstString lhs, ConstString rhs)
int ThreeWay (ConstString lhs, ConstString rhs)
Detailed Description
template<typename T>
struct lldb_private::UniqueCStringMap< T >::Compare
Definition at line 209 of file UniqueCStringMap.h.
Member Function Documentation
operator()() [1/4]
template<typename T> bool lldb_private::UniqueCStringMap< T >::Compare::operator() (const Entry & lhs, const Entry & rhs) inline
Definition at line 210 of file UniqueCStringMap.h.
References lldb_private::UniqueCStringMap< T >::Entry::cstring, and operator()().
Referenced by operator()(), operator()(), and operator()().
operator()() [2/4]
template<typename T> bool lldb_private::UniqueCStringMap< T >::Compare::operator() (const Entry & lhs, ConstString rhs) inline
Definition at line 214 of file UniqueCStringMap.h.
References lldb_private::UniqueCStringMap< T >::Entry::cstring, and operator()().
operator()() [3/4]
template<typename T> bool lldb_private::UniqueCStringMap< T >::Compare::operator() (ConstString lhs, const Entry & rhs) inline
Definition at line 218 of file UniqueCStringMap.h.
References lldb_private::UniqueCStringMap< T >::Entry::cstring, and operator()().
operator()() [4/4]
template<typename T> bool lldb_private::UniqueCStringMap< T >::Compare::operator() (ConstString lhs, ConstString rhs) inline
Definition at line 222 of file UniqueCStringMap.h.
References ThreeWay().
ThreeWay()
template<typename T> int lldb_private::UniqueCStringMap< T >::Compare::ThreeWay (ConstString lhs, ConstString rhs) inline
Definition at line 229 of file UniqueCStringMap.h.
References lldb_private::ConstString::GetCString().
Referenced by operator()().
The documentation for this struct was generated from the following file:
UniqueCStringMap.h