LLDB: lldb_private::UserID Class Reference
lldb_private::UserID Class Reference
A mix in class that contains a generic user ID.
#include "lldb/Core/UserID.h"
Public Member Functions
UserID (lldb::user_id_t uid=LLDB_INVALID_UID)
Construct with optional user ID.
~UserID ()=default
Destructor.
void Clear ()
Clears the object state.
lldb::user_id_t GetID () const
Get accessor for the user ID.
void SetID (lldb::user_id_t uid)
Set accessor for the user ID.
Protected Attributes
lldb::user_id_t m_uid
The user ID that uniquely identifies an object.
Detailed Description
A mix in class that contains a generic user ID.
UserID is designed as a mix in class that can contain an integer based unique identifier for a variety of objects in lldb.
The value for this identifier is chosen by each parser plug-in. A value should be chosen that makes sense for each kind of object and should allow quick access to further and more in depth parsing.
Symbol table entries can use this to store the original symbol table index, functions can use it to store the symbol table index or the DWARF offset.
Definition at line 31 of file UserID.h.
Constructor & Destructor Documentation
UserID()
lldb_private::UserID::UserID (lldb::user_id_t uid = LLDB_INVALID_UID) inline
Construct with optional user ID.
Definition at line 33 of file UserID.h.
References LLDB_INVALID_UID, and m_uid.
Referenced by lldb_private::Block::Block(), lldb_private::CompileUnit::CompileUnit(), lldb_private::Debugger::Debugger(), lldb_private::Block::Dump(), lldb_private::CompileUnit::Dump(), lldb_private::Function::Dump(), lldb_private::Type::Dump(), lldb_private::Variable::Dump(), lldb_private::plugin::dwarf::DWARFUnit::DWARFUnit(), lldb_private::Function::Function(), lldb_private::Block::GetDescription(), lldb_private::CompileUnit::GetDescription(), lldb_private::Function::GetDescription(), lldb_private::Type::GetDescription(), lldb_private::Module::Module(), lldb_private::Module::Module(), lldb_private::Module::Module(), lldb_private::RegisterCheckpoint::RegisterCheckpoint(), lldb_private::Section::Section(), lldb_private::Section::Section(), lldb_private::Target::StopHook::StopHook(), lldb_private::Target::StopHook::StopHook(), lldb_private::SymbolFileType::SymbolFileType(), lldb_private::SymbolFileType::SymbolFileType(), lldb_private::Thread::Thread(), lldb_private::Type::Type(), lldb_private::Type::Type(), and lldb_private::Variable::Variable().
~UserID()
lldb_private::UserID::~UserID () default
Destructor.
Member Function Documentation
Clear()
void lldb_private::UserID::Clear () inline
Clears the object state.
Clears the object contents back to a default invalid state.
Definition at line 41 of file UserID.h.
References LLDB_INVALID_UID, and m_uid.
GetID()
lldb::user_id_t lldb_private::UserID::GetID () const inline
Get accessor for the user ID.
Returns
The user ID.
Definition at line 47 of file UserID.h.
References m_uid.
Referenced by lldb_private::ClangExpressionDeclMap::AddOneFunction(), lldb_private::Block::AddRange(), lldb_private::AppleThreadPlanStepThroughDirectDispatch::AppleThreadPlanStepThroughDirectDispatch(), PDBASTParser::CreateLLDBTypeFromPDBType(), lldb_private::process_gdb_remote::ThreadGDBRemote::CreateRegisterContextForFrame(), lldb_private::Debugger::Debugger(), lldb_private::Thread::DiscardThreadPlans(), lldb_private::Thread::DiscardThreadPlansUpToPlan(), CommandObjectThreadSelect::DoExecute(), lldb_private::LLVMUserExpression::DoExecute(), lldb_private::ThreadPlanNull::DoPlanExplainsStop(), lldb_private::Block::Dump(), lldb_private::Section::Dump(), lldb_private::StackID::Dump(), lldb_private::Variable::Dump(), lldb_private::Block::DumpSymbolContext(), lldb_private::CompileUnit::DumpSymbolContext(), lldb_private::Function::DumpSymbolContext(), lldb_private::Block::FindBlockByID(), lldb_private::Function::GetCallEdges(), lldb_private::Function::GetCompilerContext(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetCompileUnit(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::GetCompUnitInfo(), lldb_private::mcp::DebuggerResourceProvider::GetDebuggerResource(), lldb_private::Variable::GetDecl(), lldb_private::Block::GetDeclContext(), lldb_private::Function::GetDeclContext(), lldb_private::Variable::GetDeclContext(), lldb_private::Target::StopHook::GetDescription(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDWARFCompileUnit(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetDwoSymbolFileForCompileUnit(), lldb_private::breakpad::SymbolFileBreakpad::GetOrCreateFunction(), lldb_private::SymbolContext::GetParentOfInlinedScope(), lldb_private::Thread::GetPlans(), lldb_private::Thread::GetProtocolID(), lldb_private::Thread::GetStackFrameList(), lldb_private::Thread::GetStatus(), lldb_private::mcp::DebuggerResourceProvider::GetTargetResource(), lldb_private::SymbolFileType::GetType(), SymbolFilePDB::GetTypes(), lldb_private::npdb::GetVariableLocationInfo(), lldb_private::wasm::ThreadWasm::GetWasmCallStack(), lldb_private::Debugger::HandleDestroyCallback(), IOHandlerLuaInterpreter::IOHandlerLuaInterpreter(), DynamicLoaderMacOS::NotifyBreakpointHit(), DynamicLoaderMacOSXDYLD::NotifyBreakpointHit(), lldb_private::operator!=(), lldb_private::operator<<(), lldb_private::operator==(), lldb_private::breakpad::SymbolFileBreakpad::ParseBlocksRecursive(), lldb_private::npdb::SymbolFileNativePDB::ParseBlocksRecursive(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseBlocksRecursive(), SymbolFilePDB::ParseBlocksRecursive(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseCallEdgesInFunction(), lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::ParseCallEdgesInFunction(), lldb_private::SymbolFileOnDemand::ParseCallEdgesInFunction(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseCompileUnit(), SymbolFilePDB::ParseCompileUnitLineTable(), DWARFASTParserClang::ParseCXXMethod(), lldb_private::npdb::SymbolFileNativePDB::ParseFunctions(), SymbolFilePDB::ParseFunctions(), lldb_private::npdb::SymbolFileNativePDB::ParseLanguage(), SymbolFilePDB::ParseLanguage(), lldb_private::breakpad::SymbolFileBreakpad::ParseLineTable(), lldb_private::npdb::SymbolFileNativePDB::ParseLineTable(), lldb_private::breakpad::SymbolFileBreakpad::ParseSupportFiles(), lldb_private::npdb::SymbolFileNativePDB::ParseSupportFiles(), SymbolFilePDB::ParseSupportFiles(), ObjectFileELF::ParseSymbolTable(), ObjectFileELF::ParseSymtab(), SymbolFilePDB::ParseTypes(), lldb_private::npdb::SymbolFileNativePDB::ParseVariablesForCompileUnit(), lldb_private::npdb::SymbolFileNativePDB::ParseVariablesForContext(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariablesForContext(), SymbolFilePDB::ParseVariablesForContext(), lldb_private::plugin::dwarf::SymbolFileDWARF::ParseVariablesInFunctionContextRecursive(), lldb_private::StopInfoBreakpoint::PerformAction(), lldb_private::StopInfoWatchpoint::PerformAction(), lldb_private::Type::ResolveCompilerType(), lldb_private::Thread::ReturnFromFrameWithIndex(), lldb_private::Thread::SetStopInfo(), lldb_private::Thread::ShouldReportRun(), lldb_private::Thread::ShouldReportStop(), lldb_private::Thread::ShouldStop(), lldb_private::Thread::StepIn(), lldb_private::Thread::StepOut(), lldb_private::Thread::StepOver(), lldb_private::Target::StopHook::StopHook(), lldb_private::SymbolFileType::SymbolFileType(), lldb_private::Thread::Thread(), lldb_private::process_gdb_remote::ThreadGDBRemote::ThreadGDBRemote(), ThreadKDP::ThreadKDP(), lldb_private::ThreadPlan::ThreadPlan(), lldb_private::process_gdb_remote::GDBRemoteRegisterContext::WriteAllRegisterValues(), lldb_private::HistoryThread::~HistoryThread(), lldb_private::Thread::~Thread(), lldb_private::process_gdb_remote::ThreadGDBRemote::~ThreadGDBRemote(), and ThreadKDP::~ThreadKDP().
SetID()
void lldb_private::UserID::SetID (lldb::user_id_t uid) inline
Set accessor for the user ID.
Parameters
[in] uid The new user ID.
Definition at line 53 of file UserID.h.
References m_uid.
Referenced by lldb_private::process_gdb_remote::GDBRemoteRegisterContext::ReadAllRegisterValues(), and lldb_private::ThreadPlan::ThreadPlan().
Member Data Documentation
m_uid
lldb::user_id_t lldb_private::UserID::m_uid protected
The user ID that uniquely identifies an object.
Definition at line 57 of file UserID.h.
Referenced by Clear(), GetID(), SetID(), and UserID().
The documentation for this class was generated from the following file:
UserID.h