LLDB: lldb_private::URI Struct Reference
lldb_private::URI Struct Reference
#include <UriParser.h>
Public Member Functions
bool operator== (const URI &R) const
Static Public Member Functions
static std::optional< URI > Parse (llvm::StringRef uri)
Public Attributes
llvm::StringRef scheme
llvm::StringRef hostname
std::optional< uint16_t > port
llvm::StringRef path
Detailed Description
Definition at line 21 of file UriParser.h.
Member Function Documentation
operator==()
bool lldb_private::URI::operator== (const URI & R) const inline
Definition at line 27 of file UriParser.h.
References hostname, path, port, and scheme.
Parse()
std::optional< URI > URI::Parse (llvm::StringRef uri) static
Definition at line 28 of file UriParser.cpp.
References hostname, path, port, and scheme.
Referenced by lldb_private::platform_android::PlatformAndroidRemoteGDBServer::ConnectProcess(), lldb_private::platform_android::PlatformAndroid::ConnectRemote(), lldb_private::platform_android::PlatformAndroidRemoteGDBServer::ConnectRemote(), lldb_private::platform_gdb_server::PlatformRemoteGDBServer::ConnectRemote(), CommandObjectProtocolServerStart::DoExecute(), and lldb_private::process_gdb_remote::LLGSArgToURL().
Member Data Documentation
hostname
llvm::StringRef lldb_private::URI::hostname
Definition at line 23 of file UriParser.h.
Referenced by lldb_private::operator<<(), operator==(), and Parse().
path
llvm::StringRef lldb_private::URI::path
Definition at line 25 of file UriParser.h.
Referenced by lldb_private::operator<<(), operator==(), and Parse().
port
std::optional<uint16_t> lldb_private::URI::port
Definition at line 24 of file UriParser.h.
Referenced by lldb_private::operator<<(), operator==(), and Parse().
scheme
llvm::StringRef lldb_private::URI::scheme
Definition at line 22 of file UriParser.h.
Referenced by lldb_private::operator<<(), operator==(), and Parse().
The documentation for this struct was generated from the following files:
UriParser.h
UriParser.cpp