LLDB: lldb_private::FormatterBytecode::DataStack Struct Reference
lldb_private::FormatterBytecode::DataStack Struct Reference
#include <FormatterBytecode.h>
Public Member Functions
DataStack ()=default
DataStack (lldb::ValueObjectSP initial_value)
void Push (DataStackElement el)
template<typename T>
T Pop ()
DataStackElement PopAny ()
Detailed Description
Definition at line 44 of file FormatterBytecode.h.
Constructor & Destructor Documentation
DataStack() [1/2]
lldb_private::FormatterBytecode::DataStack::DataStack () default
DataStack() [2/2]
lldb_private::FormatterBytecode::DataStack::DataStack (lldb::ValueObjectSP initial_value) inline
Definition at line 46 of file FormatterBytecode.h.
Member Function Documentation
Pop()
template<typename T> T lldb_private::FormatterBytecode::DataStack::Pop () inline
Definition at line 49 of file FormatterBytecode.h.
Referenced by lldb_private::FormatterBytecode::FormatImpl(), and lldb_private::FormatterBytecode::Interpret().
PopAny()
DataStackElement lldb_private::FormatterBytecode::DataStack::PopAny () inline
Definition at line 54 of file FormatterBytecode.h.
Referenced by lldb_private::FormatterBytecode::Interpret().
Push()
void lldb_private::FormatterBytecode::DataStack::Push (DataStackElement el) inline
Definition at line 48 of file FormatterBytecode.h.
Referenced by lldb_private::FormatterBytecode::FormatImpl(), and lldb_private::FormatterBytecode::Interpret().
The documentation for this struct was generated from the following file:
FormatterBytecode.h