LLDB: llvm::format_provider< lldb_private::dil::Token > Struct Reference
llvm::format_provider< lldb_private::dil::Token > Struct Reference
#include <DILLexer.h>
Static Public Member Functions
static void format (const lldb_private::dil::Token &t, raw_ostream &OS, llvm::StringRef Options)
Detailed Description
Definition at line 146 of file DILLexer.h.
Member Function Documentation
format()
void llvm::format_provider< lldb_private::dil::Token >::format (const lldb_private::dil::Token & t, raw_ostream & OS, llvm::StringRef Options) inline static
Definition at line 147 of file DILLexer.h.
References lldb_private::dil::Token::GetKind(), lldb_private::dil::Token::GetSpelling(), and lldb_private::dil::Token::GetTokenName().
The documentation for this struct was generated from the following file:
DILLexer.h