LLDB: PlatformiOSSimulator Struct Reference
PlatformiOSSimulator Struct Reference
IPhone Simulator Plugin.
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static PlatformSP CreateInstance (bool force, const ArchSpec *arch)
Detailed Description
IPhone Simulator Plugin.
Definition at line 484 of file PlatformAppleSimulator.cpp.
Member Function Documentation
CreateInstance()
PlatformSP PlatformiOSSimulator::CreateInstance (bool force, const ArchSpec * arch) inline static
Definition at line 494 of file PlatformAppleSimulator.cpp.
References lldb_private::PlatformAppleSimulator::CreateInstance(), g_ios_description, g_ios_plugin_name, CoreSimulatorSupport::DeviceType::iPhone, lldb_private::XcodeSDK::iPhoneSimulator, and shouldSkipSimulatorPlatform().
Referenced by Initialize(), and Terminate().
Initialize()
void PlatformiOSSimulator::Initialize () inline static
Definition at line 485 of file PlatformAppleSimulator.cpp.
References CreateInstance(), g_ios_description, g_ios_plugin_name, and lldb_private::PluginManager::RegisterPlugin().
Referenced by lldb_private::PlatformAppleSimulator::Initialize().
Terminate()
void PlatformiOSSimulator::Terminate () inline static
Definition at line 490 of file PlatformAppleSimulator.cpp.
References CreateInstance(), and lldb_private::PluginManager::UnregisterPlugin().
Referenced by lldb_private::PlatformAppleSimulator::Terminate().
The documentation for this struct was generated from the following file:
PlatformAppleSimulator.cpp