LLDB: lldb_private::WaitStatus Struct Reference
lldb_private::WaitStatus Struct Reference
#include <Host.h>
Public Types
enum Type : uint8_t { Exit , Signal , Stop }
Public Member Functions
WaitStatus (Type type, uint8_t status)
Static Public Member Functions
static WaitStatus Decode (int wstatus)
Public Attributes
Type type
uint8_t status
Detailed Description
Definition at line 54 of file Host.h.
Member Enumeration Documentation
Type
enum lldb_private::WaitStatus::Type : uint8_t
Enumerator
Exit
Signal
Stop
Definition at line 55 of file Host.h.
Constructor & Destructor Documentation
WaitStatus()
lldb_private::WaitStatus::WaitStatus (Type type, uint8_t status) inline
Definition at line 67 of file Host.h.
References status, and type.
Referenced by Decode().
Member Function Documentation
Decode()
WaitStatus lldb_private::WaitStatus::Decode (int wstatus) static
References WaitStatus().
Referenced by lldb_private::process_linux::NativeProcessLinux::Manager::CollectThread(), lldb_private::process_aix::NativeProcessAIX::Manager::Launch(), lldb_private::process_freebsd::NativeProcessFreeBSD::Manager::Launch(), lldb_private::process_linux::NativeProcessLinux::Manager::Launch(), lldb_private::process_netbsd::NativeProcessNetBSD::Manager::Launch(), lldb_private::process_freebsd::NativeProcessFreeBSD::SigchldHandler(), lldb_private::process_netbsd::NativeProcessNetBSD::SigchldHandler(), WaitPid(), and WaitPid().
Member Data Documentation
status
uint8_t lldb_private::WaitStatus::status
Definition at line 65 of file Host.h.
Referenced by lldb_private::operator==(), lldb_private::process_freebsd::NativeProcessFreeBSD::SigchldHandler(), lldb_private::process_linux::NativeProcessLinux::Manager::SigchldHandler(), lldb_private::process_netbsd::NativeProcessNetBSD::SigchldHandler(), and WaitStatus().
type
Type lldb_private::WaitStatus::type
Definition at line 64 of file Host.h.
Referenced by lldb_private::process_linux::NativeProcessLinux::MonitorCallback(), lldb_private::operator==(), lldb_private::process_freebsd::NativeProcessFreeBSD::SigchldHandler(), lldb_private::process_linux::NativeProcessLinux::Manager::SigchldHandler(), lldb_private::process_netbsd::NativeProcessNetBSD::SigchldHandler(), lldb_private::process_linux::NativeProcessLinux::TryHandleWaitStatus(), and WaitStatus().
The documentation for this struct was generated from the following file:
Host.h