LLDB: lldb_private::ClangASTImporter::DeclOrigin Struct Reference
lldb_private::ClangASTImporter::DeclOrigin Struct Reference
#include <ClangASTImporter.h>
Public Member Functions
DeclOrigin ()=default
DeclOrigin (clang::ASTContext *_ctx, clang::Decl *_decl)
DeclOrigin (const DeclOrigin &rhs)
void operator= (const DeclOrigin &rhs)
bool Valid () const
Public Attributes
clang::ASTContext * ctx = nullptr
clang::Decl * decl = nullptr
Detailed Description
Definition at line 242 of file ClangASTImporter.h.
Constructor & Destructor Documentation
DeclOrigin() [1/3]
lldb_private::ClangASTImporter::DeclOrigin::DeclOrigin () default
Referenced by DeclOrigin(), and operator=().
DeclOrigin() [2/3]
lldb_private::ClangASTImporter::DeclOrigin::DeclOrigin (clang::ASTContext * _ctx, clang::Decl * _decl) inline
Definition at line 245 of file ClangASTImporter.h.
References ctx, and decl.
DeclOrigin() [3/3]
lldb_private::ClangASTImporter::DeclOrigin::DeclOrigin (const DeclOrigin & rhs) inline
Definition at line 251 of file ClangASTImporter.h.
References ctx, decl, and DeclOrigin().
Member Function Documentation
operator=()
void lldb_private::ClangASTImporter::DeclOrigin::operator= (const DeclOrigin & rhs) inline
Definition at line 256 of file ClangASTImporter.h.
References ctx, decl, and DeclOrigin().
Valid()
bool lldb_private::ClangASTImporter::DeclOrigin::Valid () const inline
Definition at line 261 of file ClangASTImporter.h.
References ctx, and decl.
Referenced by lldb_private::ClangASTImporter::CompleteAndFetchChildren(), lldb_private::ClangASTImporter::CompleteObjCInterfaceDecl(), lldb_private::ClangASTImporter::CompleteTagDecl(), lldb_private::ClangASTSource::CompleteType(), lldb_private::ClangASTSource::FindExternalLexicalDecls(), lldb_private::ClangASTSource::FindObjCMethodDecls(), lldb_private::ClangASTImporter::GetDeclMetadata(), lldb_private::DeclFromParser< D >::GetOrigin(), lldb_private::ClangASTImporter::ASTContextMetadata::hasOrigin(), lldb_private::ClangASTImporter::ASTImporterDelegate::Imported(), lldb_private::ClangASTImporter::ASTImporterDelegate::ImportImpl(), and lldb_private::ClangASTImporter::LayoutRecordType().
Member Data Documentation
ctx
clang::ASTContext* lldb_private::ClangASTImporter::DeclOrigin::ctx = nullptr
Definition at line 263 of file ClangASTImporter.h.
Referenced by lldb_private::ClangASTImporter::CompleteAndFetchChildren(), lldb_private::ClangASTImporter::CompleteObjCInterfaceDecl(), lldb_private::ClangASTImporter::CompleteTagDecl(), DeclOrigin(), DeclOrigin(), lldb_private::ClangASTSource::FindExternalLexicalDecls(), lldb_private::ClangASTImporter::GetDeclMetadata(), lldb_private::ClangASTImporter::ASTImporterDelegate::Imported(), lldb_private::ClangASTImporter::ASTImporterDelegate::ImportImpl(), operator=(), lldb_private::ClangASTImporter::ASTContextMetadata::setOrigin(), and Valid().
decl
clang::Decl* lldb_private::ClangASTImporter::DeclOrigin::decl = nullptr
Definition at line 264 of file ClangASTImporter.h.
Referenced by lldb_private::ClangASTImporter::CompleteAndFetchChildren(), lldb_private::ClangASTImporter::CompleteObjCInterfaceDecl(), lldb_private::ClangASTImporter::CompleteTagDecl(), lldb_private::ClangASTSource::CompleteType(), DeclOrigin(), DeclOrigin(), lldb_private::ClangASTSource::FindExternalLexicalDecls(), lldb_private::ClangASTSource::FindObjCMethodDecls(), lldb_private::ClangASTImporter::GetDeclMetadata(), lldb_private::DeclFromParser< D >::GetOrigin(), lldb_private::ClangASTImporter::ASTImporterDelegate::Imported(), lldb_private::ClangASTImporter::ASTImporterDelegate::ImportImpl(), operator=(), lldb_private::ClangASTImporter::ASTContextMetadata::setOrigin(), and Valid().
The documentation for this struct was generated from the following file:
ClangASTImporter.h