LLDB: CommandObjectScriptingObjectParsed::CommandOptions::EnumValueStorage Struct Reference
CommandObjectScriptingObjectParsed::CommandOptions::EnumValueStorage Struct Reference
Public Member Functions
EnumValueStorage ()
EnumValueStorage (std::string in_str_val, std::string in_usage, size_t in_value)
EnumValueStorage (const EnumValueStorage &in)
EnumValueStorage & operator= (const EnumValueStorage &in)
void SetElement (size_t in_value)
Public Attributes
std::string value
std::string usage
OptionEnumValueElement element
Detailed Description
Definition at line 1767 of file CommandObjectCommands.cpp.
Constructor & Destructor Documentation
EnumValueStorage() [1/3]
CommandObjectScriptingObjectParsed::CommandOptions::EnumValueStorage::EnumValueStorage () inline
Definition at line 1768 of file CommandObjectCommands.cpp.
References element.
Referenced by EnumValueStorage(), and operator=().
EnumValueStorage() [2/3]
CommandObjectScriptingObjectParsed::CommandOptions::EnumValueStorage::EnumValueStorage (std::string in_str_val, std::string in_usage, size_t in_value) inline
Definition at line 1774 of file CommandObjectCommands.cpp.
References SetElement(), usage, and value.
EnumValueStorage() [3/3]
CommandObjectScriptingObjectParsed::CommandOptions::EnumValueStorage::EnumValueStorage (const EnumValueStorage & in) inline
Definition at line 1779 of file CommandObjectCommands.cpp.
References element, EnumValueStorage(), SetElement(), usage, value, and lldb_private::OptionEnumValueElement::value.
Member Function Documentation
operator=()
EnumValueStorage & CommandObjectScriptingObjectParsed::CommandOptions::EnumValueStorage::operator= (const EnumValueStorage & in) inline
Definition at line 1784 of file CommandObjectCommands.cpp.
References element, EnumValueStorage(), SetElement(), usage, value, and lldb_private::OptionEnumValueElement::value.
SetElement()
void CommandObjectScriptingObjectParsed::CommandOptions::EnumValueStorage::SetElement (size_t in_value) inline
Definition at line 1791 of file CommandObjectCommands.cpp.
References element, usage, and value.
Referenced by EnumValueStorage(), EnumValueStorage(), and operator=().
Member Data Documentation
element
OptionEnumValueElement CommandObjectScriptingObjectParsed::CommandOptions::EnumValueStorage::element
Definition at line 1799 of file CommandObjectCommands.cpp.
Referenced by EnumValueStorage(), EnumValueStorage(), operator=(), and SetElement().
usage
std::string CommandObjectScriptingObjectParsed::CommandOptions::EnumValueStorage::usage
Definition at line 1798 of file CommandObjectCommands.cpp.
Referenced by EnumValueStorage(), EnumValueStorage(), operator=(), and SetElement().
value
std::string CommandObjectScriptingObjectParsed::CommandOptions::EnumValueStorage::value
Definition at line 1797 of file CommandObjectCommands.cpp.
Referenced by EnumValueStorage(), EnumValueStorage(), operator=(), and SetElement().
The documentation for this struct was generated from the following file:
CommandObjectCommands.cpp