LLDB: CommandObjectSourceList::SourceInfo Struct Reference
CommandObjectSourceList::SourceInfo Struct Reference
Public Member Functions
SourceInfo (ConstString name, const LineEntry &line_entry)
SourceInfo ()=default
bool IsValid () const
bool operator== (const SourceInfo &rhs) const
bool operator!= (const SourceInfo &rhs) const
bool operator< (const SourceInfo &rhs) const
Public Attributes
ConstString function
LineEntry line_entry
Detailed Description
Definition at line 728 of file CommandObjectSource.cpp.
Constructor & Destructor Documentation
SourceInfo() [1/2]
CommandObjectSourceList::SourceInfo::SourceInfo (ConstString name, const LineEntry & line_entry) inline
Definition at line 732 of file CommandObjectSource.cpp.
References function, and line_entry.
Referenced by operator!=(), operator<(), and operator==().
SourceInfo() [2/2]
CommandObjectSourceList::SourceInfo::SourceInfo () default
Member Function Documentation
IsValid()
bool CommandObjectSourceList::SourceInfo::IsValid () const inline
Definition at line 737 of file CommandObjectSource.cpp.
References function, and line_entry.
Referenced by CommandObjectSourceList::DisplayFunctionSource(), and CommandObjectSourceList::DoExecute().
operator!=()
bool CommandObjectSourceList::SourceInfo::operator!= (const SourceInfo & rhs) const inline
Definition at line 747 of file CommandObjectSource.cpp.
References lldb_private::SupportFile::eEqualFileSpecAndChecksumIfSet, function, lldb_private::LineEntry::line, line_entry, lldb_private::LineEntry::original_file_sp, and SourceInfo().
operator<()
bool CommandObjectSourceList::SourceInfo::operator< (const SourceInfo & rhs) const inline
Definition at line 755 of file CommandObjectSource.cpp.
References function, lldb_private::ConstString::GetCString(), lldb_private::FileSpec::GetDirectory(), lldb_private::LineEntry::GetFile(), lldb_private::FileSpec::GetFilename(), lldb_private::LineEntry::line, line_entry, and SourceInfo().
operator==()
bool CommandObjectSourceList::SourceInfo::operator== (const SourceInfo & rhs) const inline
Definition at line 739 of file CommandObjectSource.cpp.
References lldb_private::SupportFile::eEqualFileSpecAndChecksumIfSet, function, lldb_private::LineEntry::line, line_entry, lldb_private::LineEntry::original_file_sp, and SourceInfo().
Member Data Documentation
function
ConstString CommandObjectSourceList::SourceInfo::function
Definition at line 729 of file CommandObjectSource.cpp.
Referenced by CommandObjectSourceList::DisplayFunctionSource(), IsValid(), operator!=(), operator<(), operator==(), and SourceInfo().
line_entry
LineEntry CommandObjectSourceList::SourceInfo::line_entry
Definition at line 730 of file CommandObjectSource.cpp.
Referenced by CommandObjectSourceList::DisplayFunctionSource(), IsValid(), operator!=(), operator<(), operator==(), and SourceInfo().
The documentation for this struct was generated from the following file:
CommandObjectSource.cpp