LLDB: llvm::DenseMapInfo< lldb_private::SymbolContext > Struct Reference
llvm::DenseMapInfo< lldb_private::SymbolContext > Struct Reference
DenseMapInfo implementation.
#include <SymbolContext.h>
Static Public Member Functions
static lldb_private::SymbolContext getEmptyKey ()
static lldb_private::SymbolContext getTombstoneKey ()
static unsigned getHashValue (const lldb_private::SymbolContext &sc)
static bool isEqual (const lldb_private::SymbolContext &lhs, const lldb_private::SymbolContext &rhs)
Detailed Description
DenseMapInfo implementation.
Definition at line 519 of file SymbolContext.h.
Member Function Documentation
getEmptyKey()
lldb_private::SymbolContext llvm::DenseMapInfo< lldb_private::SymbolContext >::getEmptyKey () inline static
Definition at line 520 of file SymbolContext.h.
References lldb_private::SymbolContext::function.
getHashValue()
unsigned llvm::DenseMapInfo< lldb_private::SymbolContext >::getHashValue (const lldb_private::SymbolContext & sc) inline static
Definition at line 532 of file SymbolContext.h.
References lldb_private::SymbolContext::block, lldb_private::LineEntry::column, lldb_private::SymbolContext::comp_unit, lldb_private::SymbolContext::function, lldb_private::AddressRange::GetBaseAddress(), lldb_private::AddressRange::GetByteSize(), lldb_private::Address::GetFileAddress(), lldb_private::LineEntry::is_terminal_entry, lldb_private::LineEntry::IsValid(), lldb_private::LineEntry::line, lldb_private::SymbolContext::line_entry, lldb_private::SymbolContext::module_sp, lldb_private::LineEntry::range, lldb_private::SymbolContext::target_sp, and lldb_private::SymbolContext::variable.
getTombstoneKey()
lldb_private::SymbolContext llvm::DenseMapInfo< lldb_private::SymbolContext >::getTombstoneKey () inline static
Definition at line 526 of file SymbolContext.h.
References lldb_private::SymbolContext::function.
isEqual()
bool llvm::DenseMapInfo< lldb_private::SymbolContext >::isEqual (const lldb_private::SymbolContext & lhs, const lldb_private::SymbolContext & rhs) inline static
Definition at line 548 of file SymbolContext.h.
References lldb_private::SymbolContext::CompareConsideringPossiblyNullSymbol(), and lldb_private::SymbolContext::function.
The documentation for this struct was generated from the following file:
SymbolContext.h