LLDB: lldb_private::ScriptSummaryFormat Struct Reference
lldb_private::ScriptSummaryFormat Struct Reference
#include <TypeSummary.h>
Public Types
typedef std::shared_ptr< ScriptSummaryFormat > SharedPointer
Public Types inherited from lldb_private::TypeSummaryImpl
enum class Kind {
eSummaryString , eScript , eBytecode , eCallback ,
eInternal
}
typedef std::shared_ptr< TypeSummaryImpl > SharedPointer
Public Member Functions
ScriptSummaryFormat (const TypeSummaryImpl::Flags &flags, const char *function_name, const char *python_script=nullptr, uint32_t ptr_match_depth=1)
~ScriptSummaryFormat () override=default
const char * GetFunctionName () const
const char * GetPythonScript () const
void SetFunctionName (const char *function_name)
void SetPythonScript (const char *script)
bool FormatObject (ValueObject *valobj, std::string &dest, const TypeSummaryOptions &options) override
std::string GetDescription () override
std::string GetName () override
Get the name of the Type Summary Provider, either a C++ class, a summary string, or a script function name.
Public Member Functions inherited from lldb_private::TypeSummaryImpl
virtual ~TypeSummaryImpl ()=default
Kind GetKind () const
bool Cascades () const
bool SkipsPointers () const
bool SkipsReferences () const
bool NonCacheable () const
virtual bool DoesPrintChildren (ValueObject *valobj) const
virtual bool DoesPrintEmptyAggregates () const
virtual bool DoesPrintValue (ValueObject *valobj) const
bool IsOneLiner () const
virtual bool HideNames (ValueObject *valobj) const
void SetCascades (bool value)
void SetSkipsPointers (bool value)
void SetSkipsReferences (bool value)
virtual void SetDoesPrintChildren (bool value)
virtual void SetDoesPrintValue (bool value)
void SetIsOneLiner (bool value)
virtual void SetHideNames (bool value)
virtual void SetNonCacheable (bool value)
uint32_t GetOptions ()
void SetOptions (uint32_t value)
uint32_t GetPtrMatchDepth ()
void SetPtrMatchDepth (uint32_t value)
virtual std::string GetSummaryKindName ()
Get the name of the kind of Summary Provider, either c++, summary string, script or python.
uint32_t & GetRevision ()
Static Public Member Functions
static bool classof (const TypeSummaryImpl *S)
Public Attributes
std::string m_function_name
std::string m_python_script
std::string m_script_formatter_name
StructuredData::ObjectSP m_script_function_sp
Private Member Functions
ScriptSummaryFormat (const ScriptSummaryFormat &)=delete
const ScriptSummaryFormat & operator= (const ScriptSummaryFormat &)=delete
Additional Inherited Members
Protected Member Functions inherited from lldb_private::TypeSummaryImpl
TypeSummaryImpl (Kind kind, const TypeSummaryImpl::Flags &flags, uint32_t ptr_match_depth=1)
Protected Attributes inherited from lldb_private::TypeSummaryImpl
uint32_t m_my_revision = 0
Flags m_flags
Detailed Description
Definition at line 376 of file TypeSummary.h.
Member Typedef Documentation
SharedPointer
typedef std::shared_ptr<ScriptSummaryFormat> lldb_private::ScriptSummaryFormat::SharedPointer
Definition at line 419 of file TypeSummary.h.
Constructor & Destructor Documentation
ScriptSummaryFormat() [1/2]
ScriptSummaryFormat::ScriptSummaryFormat (const TypeSummaryImpl::Flags & flags, const char * function_name, const char * python_script = nullptr, uint32_t ptr_match_depth = 1)
Definition at line 173 of file TypeSummary.cpp.
References lldb_private::TypeSummaryImpl::eScript, m_function_name, m_python_script, m_script_formatter_name, m_script_function_sp, and lldb_private::TypeSummaryImpl::TypeSummaryImpl().
Referenced by operator=(), and ScriptSummaryFormat().
~ScriptSummaryFormat()
lldb_private::ScriptSummaryFormat::~ScriptSummaryFormat () override default
ScriptSummaryFormat() [2/2]
lldb_private::ScriptSummaryFormat::ScriptSummaryFormat (const ScriptSummaryFormat &) private delete
References ScriptSummaryFormat().
Member Function Documentation
classof()
bool lldb_private::ScriptSummaryFormat::classof (const TypeSummaryImpl * S) inline static
Definition at line 415 of file TypeSummary.h.
References lldb_private::TypeSummaryImpl::eScript, and lldb_private::TypeSummaryImpl::TypeSummaryImpl().
FormatObject()
bool ScriptSummaryFormat::FormatObject (ValueObject * valobj, std::string & dest, const TypeSummaryOptions & options) override virtual
Implements lldb_private::TypeSummaryImpl.
Definition at line 195 of file TypeSummary.cpp.
References lldb_private::ScriptInterpreter::GetScriptedSummary(), lldb_private::ValueObject::GetSP(), lldb_private::ValueObject::GetTargetSP(), m_function_name, and m_script_function_sp.
GetDescription()
std::string ScriptSummaryFormat::GetDescription () override virtual
Implements lldb_private::TypeSummaryImpl.
Definition at line 220 of file TypeSummary.cpp.
References lldb_private::TypeSummaryImpl::Cascades(), lldb_private::TypeSummaryImpl::DoesPrintChildren(), lldb_private::TypeSummaryImpl::DoesPrintValue(), lldb_private::TypeSummaryImpl::GetPtrMatchDepth(), lldb_private::StreamString::GetString(), lldb_private::TypeSummaryImpl::HideNames(), lldb_private::TypeSummaryImpl::IsOneLiner(), m_function_name, m_python_script, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), lldb_private::TypeSummaryImpl::SkipsPointers(), and lldb_private::TypeSummaryImpl::SkipsReferences().
GetFunctionName()
const char * lldb_private::ScriptSummaryFormat::GetFunctionName () const inline
Definition at line 389 of file TypeSummary.h.
References m_function_name.
GetName()
std::string ScriptSummaryFormat::GetName () override virtual
Get the name of the Type Summary Provider, either a C++ class, a summary string, or a script function name.
Implements lldb_private::TypeSummaryImpl.
Definition at line 243 of file TypeSummary.cpp.
References m_script_formatter_name.
GetPythonScript()
const char * lldb_private::ScriptSummaryFormat::GetPythonScript () const inline
Definition at line 391 of file TypeSummary.h.
References m_python_script.
operator=()
const ScriptSummaryFormat & lldb_private::ScriptSummaryFormat::operator= (const ScriptSummaryFormat &) private delete
References ScriptSummaryFormat().
SetFunctionName()
void lldb_private::ScriptSummaryFormat::SetFunctionName (const char * function_name) inline
Definition at line 393 of file TypeSummary.h.
References m_function_name, and m_python_script.
SetPythonScript()
void lldb_private::ScriptSummaryFormat::SetPythonScript (const char * script) inline
Definition at line 401 of file TypeSummary.h.
References m_python_script.
Member Data Documentation
m_function_name
std::string lldb_private::ScriptSummaryFormat::m_function_name
Definition at line 377 of file TypeSummary.h.
Referenced by FormatObject(), GetDescription(), GetFunctionName(), ScriptSummaryFormat(), and SetFunctionName().
m_python_script
std::string lldb_private::ScriptSummaryFormat::m_python_script
Definition at line 378 of file TypeSummary.h.
Referenced by GetDescription(), GetPythonScript(), ScriptSummaryFormat(), SetFunctionName(), and SetPythonScript().
m_script_formatter_name
std::string lldb_private::ScriptSummaryFormat::m_script_formatter_name
Definition at line 379 of file TypeSummary.h.
Referenced by GetName(), and ScriptSummaryFormat().
m_script_function_sp
StructuredData::ObjectSP lldb_private::ScriptSummaryFormat::m_script_function_sp
Definition at line 380 of file TypeSummary.h.
Referenced by FormatObject(), and ScriptSummaryFormat().
The documentation for this struct was generated from the following files:
TypeSummary.h
TypeSummary.cpp