LLDB: lldb_private::UnwindLLDB::Cursor Struct Reference
lldb_private::UnwindLLDB::Cursor Struct Reference
Public Member Functions
Cursor ()=default
Public Attributes
lldb::addr_t start_pc
lldb::addr_t cfa = LLDB_INVALID_ADDRESS
lldb_private::SymbolContext sctx
RegisterContextLLDBSP reg_ctx_lldb_sp
Private Member Functions
Cursor (const Cursor &)=delete
const Cursor & operator= (const Cursor &)=delete
Detailed Description
Definition at line 125 of file UnwindLLDB.h.
Constructor & Destructor Documentation
Cursor() [1/2]
lldb_private::UnwindLLDB::Cursor::Cursor () default
Referenced by Cursor(), and operator=().
Cursor() [2/2]
lldb_private::UnwindLLDB::Cursor::Cursor (const Cursor &) private delete
References Cursor().
Member Function Documentation
operator=()
const Cursor & lldb_private::UnwindLLDB::Cursor::operator= (const Cursor &) private delete
References Cursor().
Member Data Documentation
cfa
lldb::addr_t lldb_private::UnwindLLDB::Cursor::cfa = LLDB_INVALID_ADDRESS
Definition at line 129 of file UnwindLLDB.h.
reg_ctx_lldb_sp
RegisterContextLLDBSP lldb_private::UnwindLLDB::Cursor::reg_ctx_lldb_sp
Definition at line 134 of file UnwindLLDB.h.
Referenced by lldb_private::UnwindLLDB::DoCreateRegisterContextForFrame().
sctx
lldb_private::SymbolContext lldb_private::UnwindLLDB::Cursor::sctx
Definition at line 131 of file UnwindLLDB.h.
start_pc
lldb::addr_t lldb_private::UnwindLLDB::Cursor::start_pc
Initial value:
=
        LLDB_INVALID_ADDRESS
Definition at line 126 of file UnwindLLDB.h.
The documentation for this struct was generated from the following file:
UnwindLLDB.h