LLDB: lldb_private::ClassDescriptorV2::class_ro_t Struct Reference
lldb_private::ClassDescriptorV2::class_ro_t Struct Reference
Public Member Functions
bool Read (Process *process, lldb::addr_t addr)
Public Attributes
uint32_t m_flags
uint32_t m_instanceStart
uint32_t m_instanceSize
uint32_t m_reserved
lldb::addr_t m_ivarLayout_ptr
lldb::addr_t m_name_ptr
lldb::addr_t m_baseMethods_ptr
lldb::addr_t m_baseProtocols_ptr
lldb::addr_t m_ivars_ptr
lldb::addr_t m_weakIvarLayout_ptr
lldb::addr_t m_baseProperties_ptr
std::string m_name
Detailed Description
Definition at line 104 of file AppleObjCClassDescriptorV2.h.
Member Function Documentation
Read()
bool ClassDescriptorV2::class_ro_t::Read (Process * process, lldb::addr_t addr)
Definition at line 139 of file AppleObjCClassDescriptorV2.cpp.
References error(), lldb_private::DataExtractor::GetAddress_unchecked(), lldb_private::Process::GetAddressByteSize(), lldb_private::Process::GetByteOrder(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::DataBufferHeap::GetByteSize(), lldb_private::DataExtractor::GetU32_unchecked(), m_baseMethods_ptr, m_baseProperties_ptr, m_baseProtocols_ptr, m_flags, m_instanceSize, m_instanceStart, m_ivarLayout_ptr, m_ivars_ptr, m_name, m_name_ptr, m_reserved, m_weakIvarLayout_ptr, lldb_private::Process::ReadCStringFromMemory(), and lldb_private::Process::ReadMemory().
Member Data Documentation
m_baseMethods_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::class_ro_t::m_baseMethods_ptr
Definition at line 112 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_baseProperties_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::class_ro_t::m_baseProperties_ptr
Definition at line 117 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_baseProtocols_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::class_ro_t::m_baseProtocols_ptr
Definition at line 113 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_flags
uint32_t lldb_private::ClassDescriptorV2::class_ro_t::m_flags
Definition at line 105 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_instanceSize
uint32_t lldb_private::ClassDescriptorV2::class_ro_t::m_instanceSize
Definition at line 107 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_instanceStart
uint32_t lldb_private::ClassDescriptorV2::class_ro_t::m_instanceStart
Definition at line 106 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_ivarLayout_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::class_ro_t::m_ivarLayout_ptr
Definition at line 110 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_ivars_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::class_ro_t::m_ivars_ptr
Definition at line 114 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_name
std::string lldb_private::ClassDescriptorV2::class_ro_t::m_name
Definition at line 119 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_name_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::class_ro_t::m_name_ptr
Definition at line 111 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_reserved
uint32_t lldb_private::ClassDescriptorV2::class_ro_t::m_reserved
Definition at line 108 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_weakIvarLayout_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::class_ro_t::m_weakIvarLayout_ptr
Definition at line 116 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
The documentation for this struct was generated from the following files:
AppleObjCClassDescriptorV2.h
AppleObjCClassDescriptorV2.cpp