LLDB: elf::ELFDynamic Class Reference
elf::ELFDynamic Class Reference
Represents an entry in an ELF dynamic table.
#include <ELFHeader.h>
Public Member Functions
ELFDynamic ()
bool Parse (const lldb_private::DataExtractor &data, lldb::offset_t *offset)
Parse an ELFDynamic entry from the given DataExtractor starting at position offset.
Public Attributes
elf_sxword d_tag
Type of dynamic table entry.
union {
elf_xword d_val
Integer value of the table entry.
elf_addr d_ptr
Pointer value of the table entry.
};
Detailed Description
Represents an entry in an ELF dynamic table.
Definition at line 276 of file ELFHeader.h.
Constructor & Destructor Documentation
ELFDynamic()
ELFDynamic::ELFDynamic ()
Definition at line 404 of file ELFHeader.cpp.
References ELFDynamic().
Referenced by ELFDynamic().
Member Function Documentation
Parse()
bool ELFDynamic::Parse (const lldb_private::DataExtractor & data, lldb::offset_t * offset)
Parse an ELFDynamic entry from the given DataExtractor starting at position offset.
The address size of the DataExtractor determines if a 32 or 64 bit object is to be parsed.
Parameters
[in] data The DataExtractor to read from. The address size of the extractor determines if a 32 or 64 bit object should be read.
[in,out] offset Pointer to an offset in the data. On return the offset will be advanced by the number of bytes read.
Returns
True if the ELFDynamic entry was successfully read and false otherwise.
Definition at line 406 of file ELFHeader.cpp.
References d_tag, lldb_private::DataExtractor::GetAddressByteSize(), and GetMaxS64().
Referenced by ObjectFileELF::ParseDynamicSymbols().
Member Data Documentation
[union]
union { ... } elf::ELFDynamic
d_ptr
elf_addr elf::ELFDynamic::d_ptr
Pointer value of the table entry.
Definition at line 280 of file ELFHeader.h.
Referenced by ObjectFileELF::ParseSymtab(), and ObjectFileELF::ReadDataFromDynamic().
d_tag
elf_sxword elf::ELFDynamic::d_tag
Type of dynamic table entry.
Definition at line 277 of file ELFHeader.h.
Referenced by ObjectFileELF::GetImageInfoAddress(), Parse(), and ObjectFileELF::ParseDynamicSymbols().
d_val
elf_xword elf::ELFDynamic::d_val
Integer value of the table entry.
Definition at line 279 of file ELFHeader.h.
Referenced by ObjectFileELF::GetDynstrData(), ObjectFileELF::GetDynsymDataFromDynamic(), and ObjectFileELF::PLTRelocationType().
The documentation for this class was generated from the following files:
ELFHeader.h
ELFHeader.cpp