LLDB: lldb_private::OptionArgParser Struct Reference
lldb_private::OptionArgParser Struct Reference
#include <OptionArgParser.h>
Static Public Member Functions
static lldb::addr_t ToAddress (const ExecutionContext *exe_ctx, llvm::StringRef s, lldb::addr_t fail_value, Status *error_ptr)
Try to parse an address.
static lldb::addr_t ToRawAddress (const ExecutionContext *exe_ctx, llvm::StringRef s, lldb::addr_t fail_value, Status *error_ptr)
As for ToAddress but do not remove non-address bits from the result.
static bool ToBoolean (llvm::StringRef s, bool fail_value, bool *success_ptr)
static llvm::Expected< bool > ToBoolean (llvm::StringRef option_name, llvm::StringRef option_arg)
static char ToChar (llvm::StringRef s, char fail_value, bool *success_ptr)
static int64_t ToOptionEnum (llvm::StringRef s, const OptionEnumValues &enum_values, int32_t fail_value, Status &error)
static lldb::ScriptLanguage ToScriptLanguage (llvm::StringRef s, lldb::ScriptLanguage fail_value, bool *success_ptr)
static Status ToFormat (const char *s, lldb::Format &format, size_t *byte_size_ptr)
Static Private Member Functions
static std::optional< lldb::addr_t > DoToAddress (const ExecutionContext *exe_ctx, llvm::StringRef s, Status *error)
Detailed Description
Definition at line 18 of file OptionArgParser.h.
Member Function Documentation
DoToAddress()
std::optional< lldb::addr_t > OptionArgParser::DoToAddress (const ExecutionContext * exe_ctx, llvm::StringRef s, Status * error) static private
Definition at line 184 of file OptionArgParser.cpp.
References lldb_private::Status::Clear(), lldb::eExpressionCompleted, error(), lldb_private::RegisterValue::eTypeInvalid, lldb_private::Target::EvaluateExpression(), lldb_private::RegularExpression::Execute(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::RegisterValue::GetAsUInt64(), lldb_private::ExecutionContext::GetFramePtr(), lldb_private::StackFrame::GetRegisterContext(), lldb_private::ExecutionContext::GetTargetPtr(), lldb_private::RegisterValue::GetType(), LLDB_INVALID_ADDRESS, lldb_private::EvaluateExpressionOptions::SetCoerceToId(), lldb_private::EvaluateExpressionOptions::SetKeepInMemory(), lldb_private::EvaluateExpressionOptions::SetTryAllThreads(), lldb_private::EvaluateExpressionOptions::SetUnwindOnError(), and ToAddress().
Referenced by ToAddress(), and ToRawAddress().
ToAddress()
lldb::addr_t OptionArgParser::ToAddress (const ExecutionContext * exe_ctx, llvm::StringRef s, lldb::addr_t fail_value, Status * error_ptr) static
Try to parse an address.
If it succeeds return the address with the non-address bits removed.
Definition at line 167 of file OptionArgParser.cpp.
References DoToAddress(), and lldb_private::ExecutionContext::GetProcessPtr().
Referenced by CommandObjectBreakpointAddAddress::DoExecute(), CommandObjectMemoryFind::DoExecute(), CommandObjectMemoryHistory::DoExecute(), CommandObjectMemoryRead::DoExecute(), CommandObjectMemoryRegion::DoExecute(), CommandObjectMemoryWrite::DoExecute(), DoToAddress(), CommandObjectBreakpointAddFile::CommandOptions::SetOptionValue(), CommandObjectBreakpointAddName::CommandOptions::SetOptionValue(), CommandObjectBreakpointSet::CommandOptions::SetOptionValue(), CommandObjectSourceInfo::CommandOptions::SetOptionValue(), CommandObjectSourceList::CommandOptions::SetOptionValue(), CommandObjectTargetModulesList::CommandOptions::SetOptionValue(), CommandObjectTargetModulesLookup::CommandOptions::SetOptionValue(), CommandObjectTargetModulesShowUnwind::CommandOptions::SetOptionValue(), CommandObjectThreadJump::CommandOptions::SetOptionValue(), CommandObjectThreadUntil::CommandOptions::SetOptionValue(), and lldb_private::CommandObjectDisassemble::CommandOptions::SetOptionValue().
ToBoolean() [1/2]
llvm::Expected< bool > OptionArgParser::ToBoolean (llvm::StringRef option_name, llvm::StringRef option_arg) static
Definition at line 38 of file OptionArgParser.cpp.
References ToBoolean().
ToBoolean() [2/2]
bool OptionArgParser::ToBoolean (llvm::StringRef s, bool fail_value, bool * success_ptr) static
Definition at line 21 of file OptionArgParser.cpp.
Referenced by CommandObjectTypeFilterAdd::AddFilter(), CommandObjectLogTimerIncrement::DoExecute(), CommandObjectMemoryWrite::DoExecute(), CommandObjectProcessHandle::DoExecute(), CommandObjectWatchpointCommandAdd::DoExecute(), lldb_private::process_gdb_remote::GDBRemoteCommunicationServerCommon::Handle_qfProcessInfo(), BreakpointAccessOptionGroup::SetOptionValue(), CommandObjectBreakpointAddFile::CommandOptions::SetOptionValue(), CommandObjectBreakpointAddName::CommandOptions::SetOptionValue(), CommandObjectBreakpointAddPattern::CommandOptions::SetOptionValue(), CommandObjectBreakpointSet::CommandOptions::SetOptionValue(), CommandObjectFrameRecognizerAdd::CommandOptions::SetOptionValue(), CommandObjectProcessDetach::CommandOptions::SetOptionValue(), CommandObjectStatsDump::CommandOptions::SetOptionValue(), CommandObjectTargetModulesShowUnwind::CommandOptions::SetOptionValue(), CommandObjectTargetStopHookAdd::CommandOptions::SetOptionValue(), CommandObjectThreadBacktrace::CommandOptions::SetOptionValue(), CommandObjectThreadReturn::CommandOptions::SetOptionValue(), CommandObjectTypeFormatAdd::CommandOptions::SetOptionValue(), CommandObjectTypeSummaryAdd::CommandOptions::SetOptionValue(), CommandObjectTypeSynthAdd::CommandOptions::SetOptionValue(), lldb_private::BreakpointOptionGroup::SetOptionValue(), lldb_private::CommandObjectExpression::CommandOptions::SetOptionValue(), lldb_private::CommandOptionsProcessLaunch::SetOptionValue(), lldb_private::OptionGroupValueObjectDisplay::SetOptionValue(), sddarwinlog_private::EnableOptions::SetOptionValue(), ThreadStepScopeOptionGroup::SetOptionValue(), lldb_private::OptionValueBoolean::SetValueFromString(), and ToBoolean().
ToChar()
char OptionArgParser::ToChar (llvm::StringRef s, char fail_value, bool * success_ptr) static
Definition at line 52 of file OptionArgParser.cpp.
Referenced by lldb_private::OptionValueChar::SetValueFromString().
ToFormat()
Status OptionArgParser::ToFormat (const char * s, lldb::Format & format, size_t * byte_size_ptr) static
Definition at line 95 of file OptionArgParser.cpp.
References lldb::eFormatDefault, lldb::eFormatInvalid, lldb_private::Stream::EOL(), error(), lldb_private::Status::FromErrorStringWithFormat(), lldb_private::FormatManager::GetFormatAsCString(), lldb_private::FormatManager::GetFormatAsFormatChar(), lldb_private::FormatManager::GetFormatFromCString(), lldb_private::StreamString::GetString(), lldb::kNumFormats, lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and lldb_private::Status.
Referenced by lldb_private::process_gdb_remote::ProcessGDBRemote::BuildDynamicRegisterInfo(), lldb_private::DynamicRegisterInfo::SetRegisterInfo(), and lldb_private::OptionValueFormat::SetValueFromString().
ToOptionEnum()
int64_t OptionArgParser::ToOptionEnum (llvm::StringRef s, const OptionEnumValues & enum_values, int32_t fail_value, Status & error) static
Definition at line 64 of file OptionArgParser.cpp.
References error(), lldb_private::Status::FromErrorString(), lldb_private::StreamString::GetString(), lldb_private::Stream::Printf(), lldb_private::Stream::PutCString(), and lldb_private::Status.
Referenced by CommandObjectWatchpointCommandAdd::DoExecute(), CommandObjectBreakpointAddException::CommandOptions::SetOptionValue(), CommandObjectBreakpointAddName::CommandOptions::SetOptionValue(), CommandObjectCommandsScriptAdd::CommandOptions::SetOptionValue(), CommandObjectLogEnable::CommandOptions::SetOptionValue(), CommandObjectProcessSaveCore::CommandOptions::SetOptionValue(), CommandObjectScriptingExtensionList::CommandOptions::SetOptionValue(), CommandObjectScriptingRun::CommandOptions::SetOptionValue(), CommandObjectTargetModulesDumpSymtab::CommandOptions::SetOptionValue(), CommandObjectThreadUntil::CommandOptions::SetOptionValue(), lldb_private::CommandObjectExpression::CommandOptions::SetOptionValue(), lldb_private::OptionGroupValueObjectDisplay::SetOptionValue(), lldb_private::OptionGroupWatchpoint::SetOptionValue(), OptionGroupDependents::SetOptionValue(), and ThreadStepScopeOptionGroup::SetOptionValue().
ToRawAddress()
lldb::addr_t OptionArgParser::ToRawAddress (const ExecutionContext * exe_ctx, llvm::StringRef s, lldb::addr_t fail_value, Status * error_ptr) static
As for ToAddress but do not remove non-address bits from the result.
Definition at line 159 of file OptionArgParser.cpp.
References DoToAddress().
Referenced by CommandObjectMemoryTagRead::DoExecute(), CommandObjectMemoryTagWrite::DoExecute(), CommandObjectMultiwordObjC_TaggedPointer_Info::DoExecute(), and CommandObjectMemoryTagWrite::OptionGroupTagWrite::SetOptionValue().
ToScriptLanguage()
lldb::ScriptLanguage OptionArgParser::ToScriptLanguage (llvm::StringRef s, lldb::ScriptLanguage fail_value, bool * success_ptr) static
Definition at line 140 of file OptionArgParser.cpp.
References lldb::eScriptLanguageDefault, lldb::eScriptLanguageLua, lldb::eScriptLanguageNone, and lldb::eScriptLanguagePython.
Referenced by lldb::SBDebugger::GetScriptingLanguage().
The documentation for this struct was generated from the following files:
OptionArgParser.h
OptionArgParser.cpp