LLDB: lldb_private::ClassDescriptorV2::relative_list_list_t Struct Reference
lldb_private::ClassDescriptorV2::relative_list_list_t Struct Reference
Public Member Functions
bool Read (Process *process, lldb::addr_t addr)
Public Attributes
uint32_t m_entsize
uint32_t m_count
lldb::addr_t m_first_ptr
Detailed Description
Definition at line 225 of file AppleObjCClassDescriptorV2.h.
Member Function Documentation
Read()
bool ClassDescriptorV2::relative_list_list_t::Read (Process * process, lldb::addr_t addr)
Definition at line 448 of file AppleObjCClassDescriptorV2.cpp.
References error(), lldb_private::Process::GetAddressByteSize(), lldb_private::Process::GetByteOrder(), lldb_private::WritableDataBuffer::GetBytes(), lldb_private::GetLog(), lldb_private::DataExtractor::GetU32_unchecked(), LLDB_LOG, m_count, m_entsize, m_first_ptr, lldb_private::Process::ReadMemory(), and lldb_private::Types.
Member Data Documentation
m_count
uint32_t lldb_private::ClassDescriptorV2::relative_list_list_t::m_count
Definition at line 227 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_entsize
uint32_t lldb_private::ClassDescriptorV2::relative_list_list_t::m_entsize
Definition at line 226 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_first_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::relative_list_list_t::m_first_ptr
Definition at line 228 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
The documentation for this struct was generated from the following files:
AppleObjCClassDescriptorV2.h
AppleObjCClassDescriptorV2.cpp