LLDB: lldb_private::SymbolFileCTF::ctf_stype_t Struct Reference
lldb_private::SymbolFileCTF::ctf_stype_t Struct Reference
Public Member Functions
bool IsLargeType () const
uint32_t GetStructSize () const
uint32_t GetType () const
uint32_t GetSize () const
Public Attributes
uint32_t name
uint32_t info
union {
uint32_t size
uint32_t type
};
Detailed Description
Definition at line 195 of file SymbolFileCTF.h.
Member Function Documentation
GetSize()
uint32_t lldb_private::SymbolFileCTF::ctf_stype_t::GetSize () const inline
Definition at line 210 of file SymbolFileCTF.h.
References size.
Referenced by lldb_private::SymbolFileCTF::ParseType().
GetStructSize()
uint32_t lldb_private::SymbolFileCTF::ctf_stype_t::GetStructSize () const inline
Definition at line 204 of file SymbolFileCTF.h.
References IsLargeType().
GetType()
uint32_t lldb_private::SymbolFileCTF::ctf_stype_t::GetType () const inline
Definition at line 209 of file SymbolFileCTF.h.
References type.
Referenced by lldb_private::SymbolFileCTF::ParseType().
IsLargeType()
bool lldb_private::SymbolFileCTF::ctf_stype_t::IsLargeType () const inline
Definition at line 203 of file SymbolFileCTF.h.
References size.
Referenced by GetStructSize().
Member Data Documentation
[union]
union { ... } lldb_private::SymbolFileCTF::ctf_stype_t
info
uint32_t lldb_private::SymbolFileCTF::ctf_stype_t::info
Definition at line 197 of file SymbolFileCTF.h.
Referenced by lldb_private::SymbolFileCTF::ParseType().
name
uint32_t lldb_private::SymbolFileCTF::ctf_stype_t::name
Definition at line 196 of file SymbolFileCTF.h.
Referenced by lldb_private::SymbolFileCTF::ParseType().
size
uint32_t lldb_private::SymbolFileCTF::ctf_stype_t::size
Definition at line 199 of file SymbolFileCTF.h.
Referenced by GetSize(), IsLargeType(), and lldb_private::SymbolFileCTF::ParseType().
type
uint32_t lldb_private::SymbolFileCTF::ctf_stype_t::type
Definition at line 200 of file SymbolFileCTF.h.
Referenced by GetType().
The documentation for this struct was generated from the following file:
SymbolFileCTF.h