LLDB: StructuredDataDarwinLog.cpp File Reference
StructuredDataDarwinLog.cpp File Reference
#include "StructuredDataDarwinLog.h"
#include <cstring>
#include <memory>
#include <sstream>
#include "lldb/Breakpoint/StoppointCallbackContext.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Host/OptionParser.h"
#include "lldb/Interpreter/CommandInterpreter.h"
#include "lldb/Interpreter/CommandObjectMultiword.h"
#include "lldb/Interpreter/CommandReturnObject.h"
#include "lldb/Interpreter/OptionArgParser.h"
#include "lldb/Interpreter/OptionValueProperties.h"
#include "lldb/Interpreter/OptionValueString.h"
#include "lldb/Interpreter/Property.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/ThreadPlanCallOnFunctionExit.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/RegularExpression.h"
#include "llvm/ADT/StringMap.h"
#include "StructuredDataDarwinLogProperties.inc"
#include "StructuredDataDarwinLogPropertiesEnum.inc"
Classes
class sddarwinlog_private::StructuredDataDarwinLogProperties
class sddarwinlog_private::FilterRule
class sddarwinlog_private::RegexFilterRule
class sddarwinlog_private::ExactMatchFilterRule
class sddarwinlog_private::EnableOptions
class sddarwinlog_private::EnableCommand
class sddarwinlog_private::StatusCommand
Provides the status command.
class sddarwinlog_private::BaseCommand
Provides the darwin-log base command.
Namespaces
namespace sddarwinlog_private
Macros
#define DARWIN_LOG_TYPE_VALUE "DarwinLog"
#define LLDB_PROPERTIES_darwinlog
Code to handle the StructuredDataDarwinLog settings.
#define LLDB_PROPERTIES_darwinlog
Code to handle the StructuredDataDarwinLog settings.
Typedefs
using sddarwinlog_private::EnableOptionsSP = std::shared_ptr<EnableOptions>
using sddarwinlog_private::OptionsMap
using sddarwinlog_private::FilterRuleSP = std::shared_ptr<FilterRule>
using sddarwinlog_private::FilterRules = std::vector<FilterRuleSP>
Enumerations
enum
Functions
static OptionsMap & sddarwinlog_private::GetGlobalOptionsMap ()
static std::mutex & sddarwinlog_private::GetGlobalOptionsMapLock ()
EnableOptionsSP sddarwinlog_private::GetGlobalEnableOptions (const DebuggerSP &debugger_sp)
void sddarwinlog_private::SetGlobalEnableOptions (const DebuggerSP &debugger_sp, const EnableOptionsSP &options_sp)
static StructuredDataDarwinLogProperties & sddarwinlog_private::GetGlobalProperties ()
static llvm::StringRef sddarwinlog_private::GetDarwinLogTypeName ()
static llvm::StringRef sddarwinlog_private::GetLogEventType ()
static void sddarwinlog_private::RegisterFilterOperations ()
EnableOptionsSP sddarwinlog_private::ParseAutoEnableOptions (Status &error, Debugger &debugger)
bool sddarwinlog_private::RunEnableCommand (CommandInterpreter &interpreter)
static void SetErrorWithJSON (Status &error, const char *message, StructuredData::Object &object)
Variables
const uint64_t sddarwinlog_private::NANOS_PER_MICRO = 1000
const uint64_t sddarwinlog_private::NANOS_PER_MILLI = NANOS_PER_MICRO * 1000
const uint64_t sddarwinlog_private::NANOS_PER_SECOND = NANOS_PER_MILLI * 1000
const uint64_t sddarwinlog_private::NANOS_PER_MINUTE = NANOS_PER_SECOND * 60
const uint64_t sddarwinlog_private::NANOS_PER_HOUR = NANOS_PER_MINUTE * 60
static bool sddarwinlog_private::DEFAULT_FILTER_FALLTHROUGH_ACCEPTS = true
static bool sddarwinlog_private::s_is_explicitly_enabled
Global, sticky enable switch.
const char *const sddarwinlog_private::s_filter_attributes []
static constexpr OptionDefinition sddarwinlog_private::g_enable_option_table []
Provides the main on-off switch for enabling darwin logging.
Macro Definition Documentation
DARWIN_LOG_TYPE_VALUE
#define DARWIN_LOG_TYPE_VALUE "DarwinLog"
Definition at line 37 of file StructuredDataDarwinLog.cpp.
LLDB_PROPERTIES_darwinlog [1/2]
#define LLDB_PROPERTIES_darwinlog
Code to handle the StructuredDataDarwinLog settings.
Definition at line 112 of file StructuredDataDarwinLog.cpp.
LLDB_PROPERTIES_darwinlog [2/2]
#define LLDB_PROPERTIES_darwinlog
Code to handle the StructuredDataDarwinLog settings.
Definition at line 112 of file StructuredDataDarwinLog.cpp.
Function Documentation
SetErrorWithJSON()
void SetErrorWithJSON (Status & error, const char * message, StructuredData::Object & object) static
Definition at line 1115 of file StructuredDataDarwinLog.cpp.
References error(), lldb_private::StreamString::Flush(), lldb_private::Status::FromErrorString(), lldb_private::Status::FromErrorStringWithFormat(), and lldb_private::StreamString::GetData().
Referenced by lldb_private::StructuredDataDarwinLog::GetDescription().