LLDB: lldb_private::ClassDescriptorV2::method_t Struct Reference
lldb_private::ClassDescriptorV2::method_t Struct Reference
Public Member Functions
bool Read (DataExtractor &extractor, Process *process, lldb::addr_t addr, lldb::addr_t relative_string_base_addr, bool is_small, bool has_direct_sel, bool has_relative_types)
Static Public Member Functions
static size_t GetSize (Process *process, bool is_small)
static void ReadNames (llvm::MutableArrayRef< method_t > methods, Process &process)
Fill in m_name and m_types efficiently by batching read requests.
Public Attributes
lldb::addr_t m_name_ptr
lldb::addr_t m_types_ptr
lldb::addr_t m_imp_ptr
std::string m_name
std::string m_types
Detailed Description
Definition at line 153 of file AppleObjCClassDescriptorV2.h.
Member Function Documentation
GetSize()
size_t lldb_private::ClassDescriptorV2::method_t::GetSize (Process * process, bool is_small) inline static
Definition at line 161 of file AppleObjCClassDescriptorV2.h.
References lldb_private::Process::GetAddressByteSize().
Referenced by lldb_private::ClassDescriptorV2::GetMethodList(), and lldb_private::ClassDescriptorV2::ReadMethods().
Read()
bool ClassDescriptorV2::method_t::Read (DataExtractor & extractor, Process * process, lldb::addr_t addr, lldb::addr_t relative_string_base_addr, bool is_small, bool has_direct_sel, bool has_relative_types)
Definition at line 330 of file AppleObjCClassDescriptorV2.cpp.
References error(), lldb_private::DataExtractor::GetAddress_unchecked(), lldb_private::DataExtractor::GetU32_unchecked(), LLDB_INVALID_ADDRESS, m_imp_ptr, m_name_ptr, m_types_ptr, and lldb_private::Process::ReadPointerFromMemory().
ReadNames()
void ClassDescriptorV2::method_t::ReadNames (llvm::MutableArrayRef< method_t > methods, Process & process) static
Fill in m_name and m_types efficiently by batching read requests.
Definition at line 268 of file AppleObjCClassDescriptorV2.cpp.
References lldb_private::Process::ReadCStringsFromMemory().
Referenced by lldb_private::ClassDescriptorV2::ReadMethods().
Member Data Documentation
m_imp_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::method_t::m_imp_ptr
Definition at line 156 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_name
std::string lldb_private::ClassDescriptorV2::method_t::m_name
Definition at line 158 of file AppleObjCClassDescriptorV2.h.
m_name_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::method_t::m_name_ptr
Definition at line 154 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
m_types
std::string lldb_private::ClassDescriptorV2::method_t::m_types
Definition at line 159 of file AppleObjCClassDescriptorV2.h.
m_types_ptr
lldb::addr_t lldb_private::ClassDescriptorV2::method_t::m_types_ptr
Definition at line 155 of file AppleObjCClassDescriptorV2.h.
Referenced by Read().
The documentation for this struct was generated from the following files:
AppleObjCClassDescriptorV2.h
AppleObjCClassDescriptorV2.cpp