LLDB: lldb_private::TestingProperties Struct Reference
lldb_private::TestingProperties Struct Reference
Global properties used in the LLDB testsuite.
#include <Debugger.h>
Public Member Functions
TestingProperties ()
bool GetInjectVarLocListError () const
Public Member Functions inherited from lldb_private::Properties
Properties ()
Properties (const lldb::OptionValuePropertiesSP &collection_sp)
virtual ~Properties ()
lldb::OptionValuePropertiesSP GetValueProperties () const
virtual lldb::OptionValueSP GetPropertyValue (const ExecutionContext *exe_ctx, llvm::StringRef property_path, Status &error) const
virtual Status SetPropertyValue (const ExecutionContext *exe_ctx, VarSetOperationType op, llvm::StringRef property_path, llvm::StringRef value)
virtual Status DumpPropertyValue (const ExecutionContext *exe_ctx, Stream &strm, llvm::StringRef property_path, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllPropertyValues (const ExecutionContext *exe_ctx, Stream &strm, uint32_t dump_mask, bool is_json=false)
virtual void DumpAllDescriptions (CommandInterpreter &interpreter, Stream &strm) const
size_t Apropos (llvm::StringRef keyword, std::vector< const Property * > &matching_properties) const
template<typename T>
T GetPropertyAtIndexAs (uint32_t idx, T default_value, const ExecutionContext *exe_ctx=nullptr) const
template<typename T, typename U = typename std::remove_pointer<T>::type, std::enable_if_t< std::is_pointer_v< T >, bool > = true>
const U * GetPropertyAtIndexAs (uint32_t idx, const ExecutionContext *exe_ctx=nullptr) const
template<typename T>
bool SetPropertyAtIndex (uint32_t idx, T t, const ExecutionContext *exe_ctx=nullptr) const
Static Public Member Functions
static TestingProperties & GetGlobalTestingProperties ()
Static Public Member Functions inherited from lldb_private::Properties
static llvm::StringRef GetExperimentalSettingsName ()
static bool IsSettingExperimental (llvm::StringRef setting)
Additional Inherited Members
Protected Attributes inherited from lldb_private::Properties
lldb::OptionValuePropertiesSP m_collection_sp
Detailed Description
Global properties used in the LLDB testsuite.
Definition at line 75 of file Debugger.h.
Constructor & Destructor Documentation
TestingProperties()
TestingProperties::TestingProperties ()
Definition at line 216 of file Debugger.cpp.
References lldb_private::Properties::m_collection_sp.
Referenced by GetGlobalTestingProperties().
Member Function Documentation
GetGlobalTestingProperties()
TestingProperties & TestingProperties::GetGlobalTestingProperties () static
Definition at line 227 of file Debugger.cpp.
References TestingProperties().
Referenced by lldb_private::Variable::Variable().
GetInjectVarLocListError()
bool TestingProperties::GetInjectVarLocListError () const
Definition at line 221 of file Debugger.cpp.
References lldb_private::Properties::GetPropertyAtIndexAs().
The documentation for this struct was generated from the following files:
Debugger.h
Debugger.cpp