LLDB: SymbolFileDWARFDebugMap.cpp File Reference
SymbolFileDWARFDebugMap.cpp File Reference
#include "SymbolFileDWARFDebugMap.h"
#include "DWARFCompileUnit.h"
#include "DWARFDebugAranges.h"
#include "DWARFDebugInfo.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleList.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Progress.h"
#include "lldb/Core/Section.h"
#include "lldb/Host/FileSystem.h"
#include "lldb/Utility/RangeMap.h"
#include "lldb/Utility/RegularExpression.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/Utility/StructuredData.h"
#include "lldb/Utility/Timer.h"
#include "lldb/Symbol/CompileUnit.h"
#include "lldb/Symbol/LineTable.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Symbol/SymbolVendor.h"
#include "lldb/Symbol/TypeMap.h"
#include "lldb/Symbol/VariableList.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/ErrorExtras.h"
#include "llvm/Support/ScopedPrinter.h"
#include "lldb/Target/StackFrame.h"
#include "LogChannelDWARF.h"
#include "SymbolFileDWARF.h"
#include "lldb/lldb-private-enumerations.h"
#include <memory>
#include <optional>
Classes
class lldb_private::plugin::dwarf::DebugMapModule
Namespaces
namespace lldb_private
A class that represents a running process on the host machine.
namespace lldb_private::plugin
namespace lldb_private::plugin::dwarf
Functions
static void RemoveFunctionsWithModuleNotEqualTo (const ModuleSP &module_sp, SymbolContextList &sc_list, uint32_t start_idx)
Function Documentation
RemoveFunctionsWithModuleNotEqualTo()
void RemoveFunctionsWithModuleNotEqualTo (const ModuleSP & module_sp, SymbolContextList & sc_list, uint32_t start_idx) static
Definition at line 1072 of file SymbolFileDWARFDebugMap.cpp.
References lldb_private::SymbolContext::function, lldb_private::Function::GetAddress(), lldb_private::SymbolContextList::GetContextAtIndex(), lldb_private::Address::GetSection(), lldb_private::SymbolContextList::GetSize(), and lldb_private::SymbolContextList::RemoveContextAtIndex().
Referenced by lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FindFunctions(), and lldb_private::plugin::dwarf::SymbolFileDWARFDebugMap::FindFunctions().