LLDB: SymbolFileCTF.cpp File Reference
SymbolFileCTF.cpp File Reference
#include "SymbolFileCTF.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Host/Config.h"
#include "lldb/Symbol/CompileUnit.h"
#include "lldb/Symbol/Function.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Symbol/Symbol.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Symbol/Symtab.h"
#include "lldb/Symbol/TypeList.h"
#include "lldb/Symbol/TypeMap.h"
#include "lldb/Symbol/Variable.h"
#include "lldb/Symbol/VariableList.h"
#include "lldb/Utility/DataExtractor.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/RegularExpression.h"
#include "lldb/Utility/StreamBuffer.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/Utility/Timer.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/MemoryBuffer.h"
#include "Plugins/ExpressionParser/Clang/ClangASTMetadata.h"
#include "Plugins/TypeSystem/Clang/TypeSystemClang.h"
#include <memory>
#include <optional>
Functions
static uint32_t GetEncoding (uint32_t data)
Return the integer display representation encoded in the given data.
static uint32_t GetBits (uint32_t data)
Return the integral width in bits encoded in the given data.
uint32_t GetKind (uint32_t data)
Return the type kind encoded in the given data.
uint32_t GetVLen (uint32_t data)
Return the variable length encoded in the given data.
static uint32_t GetBytes (uint32_t bits)
static clang::TagTypeKind TranslateRecordKind (CTFType::Kind type)
static DWARFExpression CreateDWARFExpression (ModuleSP module_sp, const Symbol &symbol)
Function Documentation
CreateDWARFExpression()
DWARFExpression CreateDWARFExpression (ModuleSP module_sp, const Symbol & symbol) static
Definition at line 860 of file SymbolFileCTF.cpp.
References lldb_private::Stream::eBinary, lldb::eRegisterKindDWARF, lldb_private::ArchSpec::GetAddressByteSize(), lldb_private::ArchSpec::GetByteOrder(), lldb_private::StreamBuffer< N >::GetData(), lldb_private::Symbol::GetFileAddress(), lldb_private::StreamBuffer< N >::GetSize(), lldb_private::Stream::PutHex8(), lldb_private::Stream::PutMaxHex64(), and lldb_private::DWARFExpression::SetRegisterKind().
Referenced by lldb_private::SymbolFileCTF::ParseObjects().
GetBits()
uint32_t GetBits (uint32_t data) static
Return the integral width in bits encoded in the given data.
Definition at line 302 of file SymbolFileCTF.cpp.
Referenced by lldb_private::SymbolFileCTF::ParseType().
GetBytes()
uint32_t GetBytes (uint32_t bits) static
Definition at line 319 of file SymbolFileCTF.cpp.
References lldb_private::bits().
Referenced by lldb_private::SymbolFileCTF::CreateInteger().
GetEncoding()
uint32_t GetEncoding (uint32_t data) static
Return the integer display representation encoded in the given data.
Definition at line 296 of file SymbolFileCTF.cpp.
Referenced by lldb_private::SymbolFileCTF::ParseType().
GetKind()
uint32_t GetKind (uint32_t data)
Return the type kind encoded in the given data.
Definition at line 308 of file SymbolFileCTF.cpp.
Referenced by lldb_private::ThreadPlanStack::GetInnermostExpression(), lldb_private::dil::DILParser::ParseBuiltinType(), lldb_private::SymbolFileCTF::ParseFunctions(), lldb_private::dil::DILParser::ParseNestedNameSpecifier(), lldb_private::dil::DILParser::ParsePostfixExpression(), and lldb_private::SymbolFileCTF::ParseType().
GetVLen()
uint32_t GetVLen (uint32_t data)
Return the variable length encoded in the given data.
Definition at line 314 of file SymbolFileCTF.cpp.
Referenced by lldb_private::SymbolFileCTF::ParseFunctions(), and lldb_private::SymbolFileCTF::ParseType().
TranslateRecordKind()
clang::TagTypeKind TranslateRecordKind (CTFType::Kind type) static
Definition at line 321 of file SymbolFileCTF.cpp.
References lldb_private::CTFType::eStruct, lldb_private::CTFType::eUnion, and lldbassert.
Referenced by lldb_private::SymbolFileCTF::CreateRecord().