LLDB: SymbolFileNativePDB.cpp File Reference
SymbolFileNativePDB.cpp File Reference
#include "SymbolFileNativePDB.h"
#include "Plugins/ExpressionParser/Clang/ClangUtil.h"
#include "Plugins/Language/CPlusPlus/MSVCUndecoratedNameParser.h"
#include "Plugins/ObjectFile/PDB/ObjectFilePDB.h"
#include "Plugins/SymbolFile/PDB/SymbolFilePDB.h"
#include "Plugins/TypeSystem/Clang/TypeSystemClang.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Symbol/CompileUnit.h"
#include "lldb/Symbol/LineTable.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Symbol/SymbolVendor.h"
#include "lldb/Symbol/Variable.h"
#include "lldb/Symbol/VariableList.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "llvm/DebugInfo/CodeView/CVRecord.h"
#include "llvm/DebugInfo/CodeView/CVTypeVisitor.h"
#include "llvm/DebugInfo/CodeView/DebugLinesSubsection.h"
#include "llvm/DebugInfo/CodeView/LazyRandomTypeCollection.h"
#include "llvm/DebugInfo/CodeView/RecordName.h"
#include "llvm/DebugInfo/CodeView/SymbolDeserializer.h"
#include "llvm/DebugInfo/CodeView/SymbolRecordHelpers.h"
#include "llvm/DebugInfo/CodeView/TypeDeserializer.h"
#include "llvm/DebugInfo/PDB/Native/DbiStream.h"
#include "llvm/DebugInfo/PDB/Native/GlobalsStream.h"
#include "llvm/DebugInfo/PDB/Native/InfoStream.h"
#include "llvm/DebugInfo/PDB/Native/ModuleDebugStream.h"
#include "llvm/DebugInfo/PDB/Native/NativeSession.h"
#include "llvm/DebugInfo/PDB/Native/PDBFile.h"
#include "llvm/DebugInfo/PDB/Native/PublicsStream.h"
#include "llvm/DebugInfo/PDB/Native/SymbolStream.h"
#include "llvm/DebugInfo/PDB/Native/TpiStream.h"
#include "llvm/DebugInfo/PDB/PDB.h"
#include "llvm/DebugInfo/PDB/PDBTypes.h"
#include "llvm/Demangle/MicrosoftDemangle.h"
#include "llvm/Object/COFF.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/BinaryStreamReader.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/MemoryBuffer.h"
#include "DWARFLocationExpression.h"
#include "PdbSymUid.h"
#include "PdbUtil.h"
#include "UdtRecordCompleter.h"
#include <optional>
#include <string_view>
Functions
static lldb::LanguageType TranslateLanguage (PDB_Lang lang)
static std::optional< std::string > findMatchingPDBFilePath (llvm::StringRef original_pdb_path, llvm::StringRef exe_path)
static std::unique_ptr< PDBFile > loadMatchingPDBFile (std::string exe_path, llvm::BumpPtrAllocator &allocator)
static bool IsFunctionPrologue (const CompilandIndexItem &cci, lldb::addr_t addr)
static bool IsFunctionEpilogue (const CompilandIndexItem &cci, lldb::addr_t addr)
static llvm::StringRef GetSimpleTypeName (SimpleTypeKind kind)
static bool IsClassRecord (TypeLeafKind kind)
static std::optional< CVTagRecord > GetNestedTagDefinition (const NestedTypeRecord &Record, const CVTagRecord &parent, TpiStream &tpi)
static std::string GetUnqualifiedTypeName (const TagRecord &record)
static bool NeedsResolvedCompileUnit (uint32_t resolve_scope)
Function Documentation
findMatchingPDBFilePath()
std::optional< std::string > findMatchingPDBFilePath (llvm::StringRef original_pdb_path, llvm::StringRef exe_path) static
Definition at line 90 of file SymbolFileNativePDB.cpp.
References lldb_private::FileSpec::CopyByAppendingPathComponent(), lldb_private::FileSpec::CopyByRemovingLastPathComponent(), lldb_private::FileSystem::Exists(), lldb_private::Target::GetDefaultDebugFileSearchPaths(), lldb_private::FileSpec::GetFilename(), lldb_private::FileSpec::GetPath(), lldb_private::FileSpec::GuessPathStyle(), and lldb_private::FileSystem::Instance().
Referenced by loadMatchingPDBFile().
GetNestedTagDefinition()
std::optional< CVTagRecord > GetNestedTagDefinition (const NestedTypeRecord & Record, const CVTagRecord & parent, TpiStream & tpi) static
Definition at line 304 of file SymbolFileNativePDB.cpp.
References lldb_private::npdb::CVTagRecord::asTag(), lldb_private::npdb::CVTagRecord::create(), and lldb_private::npdb::IsTagRecord().
Referenced by lldb_private::npdb::SymbolFileNativePDB::BuildParentMap().
GetSimpleTypeName()
llvm::StringRef GetSimpleTypeName (SimpleTypeKind kind) static
Definition at line 194 of file SymbolFileNativePDB.cpp.
Referenced by lldb_private::npdb::SymbolFileNativePDB::CreateModifierType(), and lldb_private::npdb::SymbolFileNativePDB::CreateSimpleType().
GetUnqualifiedTypeName()
std::string GetUnqualifiedTypeName (const TagRecord & record) static
Definition at line 708 of file SymbolFileNativePDB.cpp.
References MSVCUndecoratedNameParser::DropScope().
Referenced by lldb_private::npdb::SymbolFileNativePDB::CreateClassStructUnion().
IsClassRecord()
bool IsClassRecord (TypeLeafKind kind) static
Definition at line 292 of file SymbolFileNativePDB.cpp.
Referenced by lldb_private::npdb::SymbolFileNativePDB::CreateType().
IsFunctionEpilogue()
bool IsFunctionEpilogue (const CompilandIndexItem & cci, lldb::addr_t addr) static
Definition at line 183 of file SymbolFileNativePDB.cpp.
Referenced by lldb_private::npdb::SymbolFileNativePDB::ParseLineTable().
IsFunctionPrologue()
bool IsFunctionPrologue (const CompilandIndexItem & cci, lldb::addr_t addr) static
Definition at line 177 of file SymbolFileNativePDB.cpp.
Referenced by lldb_private::npdb::SymbolFileNativePDB::ParseLineTable().
loadMatchingPDBFile()
std::unique_ptr< PDBFile > loadMatchingPDBFile (std::string exe_path, llvm::BumpPtrAllocator & allocator) static
Definition at line 124 of file SymbolFileNativePDB.cpp.
References findMatchingPDBFilePath(), lldb_private::GetLog(), LLDB_LOG, lldb_private::ObjectFilePDB::loadPDBFile(), and lldb_private::Symbols.
Referenced by lldb_private::npdb::SymbolFileNativePDB::CalculateAbilities().
NeedsResolvedCompileUnit()
bool NeedsResolvedCompileUnit (uint32_t resolve_scope) static
Definition at line 1263 of file SymbolFileNativePDB.cpp.
TranslateLanguage()
lldb::LanguageType TranslateLanguage (PDB_Lang lang) static
Definition at line 70 of file SymbolFileNativePDB.cpp.
References lldb::eLanguageTypeC, lldb::eLanguageTypeC_plus_plus, lldb::eLanguageTypeObjC, lldb::eLanguageTypeObjC_plus_plus, lldb::eLanguageTypeRust, lldb::eLanguageTypeSwift, and lldb::eLanguageTypeUnknown.
Referenced by lldb_private::npdb::SymbolFileNativePDB::CreateCompileUnit(), SymbolFilePDB::ParseCompileUnitForUID(), lldb_private::npdb::SymbolFileNativePDB::ParseLanguage(), and SymbolFilePDB::ParseLanguage().