LLDB: SymbolVendorMacOSX.cpp File Reference
SymbolVendorMacOSX.cpp File Reference
#include "SymbolVendorMacOSX.h"
#include <cstring>
#include "Plugins/ObjectFile/Mach-O/ObjectFileMachO.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Section.h"
#include "lldb/Host/Host.h"
#include "lldb/Host/XML.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/Utility/Timer.h"
Functions
static bool UUIDsMatch (Module *module, ObjectFile *ofile, lldb_private::Stream *feedback_strm)
Function Documentation
UUIDsMatch()
bool UUIDsMatch (Module * module, ObjectFile * ofile, lldb_private::Stream * feedback_strm) static
Definition at line 34 of file SymbolVendorMacOSX.cpp.
References lldb_private::Stream::AsRawOstream(), lldb_private::FileSpec::Dump(), lldb_private::UUID::Dump(), lldb_private::Stream::EOL(), lldb_private::ObjectFile::GetFileSpec(), lldb_private::Module::GetUUID(), lldb_private::ObjectFile::GetUUID(), lldb_private::Stream::PutChar(), and lldb_private::Stream::PutCString().
Referenced by SymbolVendorMacOSX::CreateInstance().