LLDB: SymbolLocatorDebuginfod.cpp File Reference
SymbolLocatorDebuginfod.cpp File Reference
#include "SymbolLocatorDebuginfod.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Interpreter/OptionValueString.h"
#include "lldb/Utility/Args.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "llvm/Debuginfod/Debuginfod.h"
#include "llvm/Debuginfod/HTTPClient.h"
#include "SymbolLocatorDebuginfodProperties.inc"
#include "SymbolLocatorDebuginfodPropertiesEnum.inc"
Macros
#define LLDB_PROPERTIES_symbollocatordebuginfod
#define LLDB_PROPERTIES_symbollocatordebuginfod
Functions
static PluginProperties & GetGlobalPluginProperties ()
static llvm::StringRef getFileName (const ModuleSpec &module_spec, std::string url_path)
static std::optional< FileSpec > GetFileForModule (const ModuleSpec &module_spec, std::function< std::string(llvm::object::BuildID)> UrlBuilder)
Macro Definition Documentation
LLDB_PROPERTIES_symbollocatordebuginfod [1/2]
#define LLDB_PROPERTIES_symbollocatordebuginfod
Definition at line 27 of file SymbolLocatorDebuginfod.cpp.
LLDB_PROPERTIES_symbollocatordebuginfod [2/2]
#define LLDB_PROPERTIES_symbollocatordebuginfod
Definition at line 27 of file SymbolLocatorDebuginfod.cpp.
Function Documentation
GetFileForModule()
std::optional< FileSpec > GetFileForModule (const ModuleSpec & module_spec, std::function< std::string(llvm::object::BuildID)> UrlBuilder) static
Definition at line 162 of file SymbolLocatorDebuginfod.cpp.
References lldb_private::UUID::GetBytes(), getFileName(), lldb_private::ModuleList::GetGlobalModuleListProperties(), GetGlobalPluginProperties(), lldb_private::GetLog(), lldb_private::ModuleSpec::GetUUID(), lldb_private::UUID::IsValid(), LLDB_LOGV, and lldb_private::Symbols.
Referenced by lldb_private::SymbolLocatorDebuginfod::LocateExecutableObjectFile(), and lldb_private::SymbolLocatorDebuginfod::LocateExecutableSymbolFile().
getFileName()
llvm::StringRef getFileName (const ModuleSpec & module_spec, std::string url_path) static
Definition at line 143 of file SymbolLocatorDebuginfod.cpp.
References lldb_private::FileSpec::GetFilename(), lldb_private::ModuleSpec::GetFileSpec(), lldb_private::ConstString::GetStringRef(), and lldb_private::ModuleSpec::GetSymbolFileSpec().
Referenced by GetFileForModule().
GetGlobalPluginProperties()
PluginProperties & GetGlobalPluginProperties () static
Definition at line 100 of file SymbolLocatorDebuginfod.cpp.