LLDB: SymbolFileBreakpad.cpp File Reference
SymbolFileBreakpad.cpp File Reference
#include "Plugins/SymbolFile/Breakpad/SymbolFileBreakpad.h"
#include "Plugins/ObjectFile/Breakpad/BreakpadRecords.h"
#include "Plugins/ObjectFile/Breakpad/ObjectFileBreakpad.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Section.h"
#include "lldb/Host/FileSystem.h"
#include "lldb/Symbol/CompileUnit.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Symbol/SymbolVendor.h"
#include "lldb/Symbol/TypeMap.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/StreamString.h"
#include "llvm/ADT/StringExtras.h"
#include <optional>
Classes
class lldb_private::breakpad::SymbolFileBreakpad::LineIterator
Functions
static std::optional< std::pair< llvm::StringRef, llvm::StringRef > > GetRule (llvm::StringRef &unwind_rules)
static const RegisterInfo * ResolveRegister (const llvm::Triple &triple, const SymbolFile::RegisterInfoResolver &resolver, llvm::StringRef name)
static const RegisterInfo * ResolveRegisterOrRA (const llvm::Triple &triple, const SymbolFile::RegisterInfoResolver &resolver, llvm::StringRef name)
Function Documentation
GetRule()
std::optional< std::pair< llvm::StringRef, llvm::StringRef > > GetRule (llvm::StringRef & unwind_rules) static
Definition at line 515 of file SymbolFileBreakpad.cpp.
Referenced by lldb_private::breakpad::SymbolFileBreakpad::ParseCFIUnwindRow().
ResolveRegister()
const RegisterInfo * ResolveRegister (const llvm::Triple & triple, const SymbolFile::RegisterInfoResolver & resolver, llvm::StringRef name) static
Definition at line 544 of file SymbolFileBreakpad.cpp.
References lldb_private::SymbolFile::RegisterInfoResolver::ResolveName().
Referenced by lldb_private::breakpad::SymbolFileBreakpad::ParseCFIUnwindRow(), lldb_private::breakpad::SymbolFileBreakpad::ParseWinUnwindPlan(), and ResolveRegisterOrRA().
ResolveRegisterOrRA()
const RegisterInfo * ResolveRegisterOrRA (const llvm::Triple & triple, const SymbolFile::RegisterInfoResolver & resolver, llvm::StringRef name) static
Definition at line 557 of file SymbolFileBreakpad.cpp.
References lldb::eRegisterKindGeneric, LLDB_REGNUM_GENERIC_PC, lldb_private::SymbolFile::RegisterInfoResolver::ResolveNumber(), and ResolveRegister().
Referenced by lldb_private::breakpad::SymbolFileBreakpad::ParseCFIUnwindRow().