LLDB: SymbolVendorELF.cpp File Reference
SymbolVendorELF.cpp File Reference
#include "SymbolVendorELF.h"
#include <cstring>
#include "Plugins/ObjectFile/ELF/ObjectFileELF.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/Section.h"
#include "lldb/Host/Host.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/Utility/Timer.h"
Functions
static bool IsDwpSymbolFile (const lldb::ModuleSP &module_sp, const FileSpec &file_spec)
Function Documentation
IsDwpSymbolFile()
bool IsDwpSymbolFile (const lldb::ModuleSP & module_sp, const FileSpec & file_spec) static
Definition at line 48 of file SymbolVendorELF.cpp.
References ObjectFileELF::classof(), lldb::eSectionTypeDWARFDebugCuIndex, lldb_private::ObjectFile::FindPlugin(), and lldb_private::FileSystem::Instance().
Referenced by SymbolVendorELF::CreateInstance().