LLDB: SymbolFilePDB.cpp File Reference
SymbolFilePDB.cpp File Reference
#include "SymbolFilePDB.h"
#include "PDBASTParser.h"
#include "PDBLocationToDWARFExpression.h"
#include "clang/Lex/Lexer.h"
#include "Plugins/TypeSystem/Clang/TypeSystemClang.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Mangled.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Symbol/CompileUnit.h"
#include "lldb/Symbol/LineTable.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Symbol/SymbolVendor.h"
#include "lldb/Symbol/TypeList.h"
#include "lldb/Symbol/TypeMap.h"
#include "lldb/Symbol/Variable.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/RegularExpression.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/DebugInfo/PDB/ConcreteSymbolEnumerator.h"
#include "llvm/DebugInfo/PDB/GenericError.h"
#include "llvm/DebugInfo/PDB/IPDBDataStream.h"
#include "llvm/DebugInfo/PDB/IPDBEnumChildren.h"
#include "llvm/DebugInfo/PDB/IPDBLineNumber.h"
#include "llvm/DebugInfo/PDB/IPDBSectionContrib.h"
#include "llvm/DebugInfo/PDB/IPDBSourceFile.h"
#include "llvm/DebugInfo/PDB/IPDBTable.h"
#include "llvm/DebugInfo/PDB/PDBSymbol.h"
#include "llvm/DebugInfo/PDB/PDBSymbolBlock.h"
#include "llvm/DebugInfo/PDB/PDBSymbolCompiland.h"
#include "llvm/DebugInfo/PDB/PDBSymbolCompilandDetails.h"
#include "llvm/DebugInfo/PDB/PDBSymbolData.h"
#include "llvm/DebugInfo/PDB/PDBSymbolExe.h"
#include "llvm/DebugInfo/PDB/PDBSymbolFunc.h"
#include "llvm/DebugInfo/PDB/PDBSymbolFuncDebugEnd.h"
#include "llvm/DebugInfo/PDB/PDBSymbolFuncDebugStart.h"
#include "llvm/DebugInfo/PDB/PDBSymbolPublicSymbol.h"
#include "llvm/DebugInfo/PDB/PDBSymbolTypeBuiltin.h"
#include "llvm/DebugInfo/PDB/PDBSymbolTypeEnum.h"
#include "llvm/DebugInfo/PDB/PDBSymbolTypeFunctionSig.h"
#include "llvm/DebugInfo/PDB/PDBSymbolTypeTypedef.h"
#include "llvm/DebugInfo/PDB/PDBSymbolTypeUDT.h"
#include "Plugins/Language/CPlusPlus/MSVCUndecoratedNameParser.h"
#include "Plugins/SymbolFile/NativePDB/SymbolFileNativePDB.h"
#include "SymbolFilePDBProperties.inc"
#include "SymbolFilePDBPropertiesEnum.inc"
Macros
#define LLDB_PROPERTIES_symbolfilepdb
#define LLDB_PROPERTIES_symbolfilepdb
Functions
static size_t ParseFunctionBlocksForPDBSymbol (uint64_t func_file_vm_addr, const llvm::pdb::PDBSymbol *pdb_symbol, lldb_private::Block *parent_block, bool is_top_parent)
Macro Definition Documentation
LLDB_PROPERTIES_symbolfilepdb [1/2]
#define LLDB_PROPERTIES_symbolfilepdb
Definition at line 101 of file SymbolFilePDB.cpp.
LLDB_PROPERTIES_symbolfilepdb [2/2]
#define LLDB_PROPERTIES_symbolfilepdb
Definition at line 101 of file SymbolFilePDB.cpp.
Function Documentation
ParseFunctionBlocksForPDBSymbol()
size_t ParseFunctionBlocksForPDBSymbol (uint64_t func_file_vm_addr, const llvm::pdb::PDBSymbol * pdb_symbol, lldb_private::Block * parent_block, bool is_top_parent) static
Definition at line 487 of file SymbolFilePDB.cpp.
References lldb_private::Block::AddRange(), lldb_private::Block::CreateChild(), lldb_private::Block::FinalizeRanges(), lldb_private::Block::FindBlockByID(), and ParseFunctionBlocksForPDBSymbol().
Referenced by SymbolFilePDB::ParseBlocksRecursive(), and ParseFunctionBlocksForPDBSymbol().