LLDB: Symtab.cpp File Reference
Symtab.cpp File Reference
#include <map>
#include <set>
#include "lldb/Core/DataFileCache.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/RichManglingContext.h"
#include "lldb/Core/Section.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Symbol/Symbol.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Symbol/Symtab.h"
#include "lldb/Target/Language.h"
#include "lldb/Utility/DataEncoder.h"
#include "lldb/Utility/Endian.h"
#include "lldb/Utility/RegularExpression.h"
#include "lldb/Utility/Stream.h"
#include "lldb/Utility/Timer.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/DJB.h"
Classes
struct SymbolSortInfo
struct SymbolSearchInfo
Functions
static int CompareSymbolID (const void *key, const void *p)
static bool lldb_skip_name (llvm::StringRef mangled, Mangled::ManglingScheme scheme)
static void AddSectionsToRangeMap (SectionList *sectlist, RangeVector< addr_t, addr_t > &section_ranges)
constexpr llvm::StringLiteral kIdentifierCStrMap ("CMAP")
static void EncodeCStrMap (DataEncoder &encoder, ConstStringTable &strtab, const UniqueCStringMap< uint32_t > &cstr_map)
bool DecodeCStrMap (const DataExtractor &data, lldb::offset_t *offset_ptr, const StringTableReader &strtab, UniqueCStringMap< uint32_t > &cstr_map)
constexpr llvm::StringLiteral kIdentifierSymbolTable ("SYMB")
Variables
constexpr uint32_t CURRENT_CACHE_VERSION = 1
Function Documentation
AddSectionsToRangeMap()
void AddSectionsToRangeMap (SectionList * sectlist, RangeVector< addr_t, addr_t > & section_ranges) static
Definition at line 905 of file Symtab.cpp.
References AddSectionsToRangeMap(), lldb_private::RangeVector< B, S, N >::Append(), lldb_private::SectionList::GetNumSections(), lldb_private::SectionList::GetSectionAtIndex(), lldb_private::Range< B, S >::SetByteSize(), and lldb_private::Range< B, S >::SetRangeBase().
Referenced by AddSectionsToRangeMap(), and lldb_private::Symtab::InitAddressIndexes().
CompareSymbolID()
int CompareSymbolID (const void * key, const void * p) static
Definition at line 209 of file Symtab.cpp.
Referenced by lldb_private::Symtab::FindSymbolByID().
DecodeCStrMap()
bool DecodeCStrMap (const DataExtractor & data, lldb::offset_t * offset_ptr, const StringTableReader & strtab, UniqueCStringMap< uint32_t > & cstr_map)
Definition at line 1205 of file Symtab.cpp.
References lldb_private::UniqueCStringMap< T >::Append(), lldb_private::StringTableReader::Get(), lldb_private::DataExtractor::GetData(), lldb_private::DataExtractor::GetU32(), kIdentifierCStrMap(), lldb_private::UniqueCStringMap< T >::Reserve(), and lldb_private::UniqueCStringMap< T >::Sort().
Referenced by lldb_private::Symtab::Decode().
EncodeCStrMap()
void EncodeCStrMap (DataEncoder & encoder, ConstStringTable & strtab, const UniqueCStringMap< uint32_t > & cstr_map) static
Definition at line 1193 of file Symtab.cpp.
References lldb_private::ConstStringTable::Add(), lldb_private::DataEncoder::AppendData(), lldb_private::DataEncoder::AppendU32(), lldb_private::UniqueCStringMap< T >::GetSize(), and kIdentifierCStrMap().
Referenced by lldb_private::Symtab::Encode().
kIdentifierCStrMap()
llvm::StringLiteral kIdentifierCStrMap ("CMAP") constexpr
Referenced by DecodeCStrMap(), and EncodeCStrMap().
kIdentifierSymbolTable()
llvm::StringLiteral kIdentifierSymbolTable ("SYMB") constexpr
Referenced by lldb_private::Symtab::Decode(), and lldb_private::Symtab::Encode().
lldb_skip_name()
bool lldb_skip_name (llvm::StringRef mangled, Mangled::ManglingScheme scheme) static
Definition at line 244 of file Symtab.cpp.
References lldb_private::Mangled::eManglingSchemeD, lldb_private::Mangled::eManglingSchemeItanium, lldb_private::Mangled::eManglingSchemeMSVC, lldb_private::Mangled::eManglingSchemeNone, lldb_private::Mangled::eManglingSchemeRustV0, and lldb_private::Mangled::eManglingSchemeSwift.
Referenced by lldb_private::Symtab::InitNameIndexes().
Variable Documentation
CURRENT_CACHE_VERSION
uint32_t CURRENT_CACHE_VERSION = 1 constexpr
Definition at line 1236 of file Symtab.cpp.