LLDB: Target.cpp File Reference
Target.cpp File Reference
#include "lldb/Target/Target.h"
#include "lldb/Breakpoint/Breakpoint.h"
#include "lldb/Breakpoint/BreakpointIDList.h"
#include "lldb/Breakpoint/BreakpointPrecondition.h"
#include "lldb/Breakpoint/BreakpointResolver.h"
#include "lldb/Breakpoint/BreakpointResolverAddress.h"
#include "lldb/Breakpoint/BreakpointResolverFileLine.h"
#include "lldb/Breakpoint/BreakpointResolverFileRegex.h"
#include "lldb/Breakpoint/BreakpointResolverName.h"
#include "lldb/Breakpoint/BreakpointResolverScripted.h"
#include "lldb/Breakpoint/Watchpoint.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Module.h"
#include "lldb/Core/ModuleSpec.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Core/SearchFilter.h"
#include "lldb/Core/Section.h"
#include "lldb/Core/SourceManager.h"
#include "lldb/Core/StructuredDataImpl.h"
#include "lldb/Core/Telemetry.h"
#include "lldb/DataFormatters/FormatterSection.h"
#include "lldb/Expression/DiagnosticManager.h"
#include "lldb/Expression/ExpressionVariable.h"
#include "lldb/Expression/REPL.h"
#include "lldb/Expression/UserExpression.h"
#include "lldb/Expression/UtilityFunction.h"
#include "lldb/Host/Host.h"
#include "lldb/Host/PosixApi.h"
#include "lldb/Host/StreamFile.h"
#include "lldb/Interpreter/CommandInterpreter.h"
#include "lldb/Interpreter/CommandReturnObject.h"
#include "lldb/Interpreter/Interfaces/ScriptedBreakpointInterface.h"
#include "lldb/Interpreter/Interfaces/ScriptedStopHookInterface.h"
#include "lldb/Interpreter/OptionGroupWatchpoint.h"
#include "lldb/Interpreter/OptionValues.h"
#include "lldb/Interpreter/Property.h"
#include "lldb/Symbol/Function.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Symbol/Symbol.h"
#include "lldb/Target/ABI.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/Language.h"
#include "lldb/Target/LanguageRuntime.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/RegisterTypeBuilder.h"
#include "lldb/Target/SectionLoadList.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/StackFrameRecognizer.h"
#include "lldb/Target/SystemRuntime.h"
#include "lldb/Target/Thread.h"
#include "lldb/Target/ThreadSpec.h"
#include "lldb/Target/UnixSignals.h"
#include "lldb/Utility/Event.h"
#include "lldb/Utility/FileSpec.h"
#include "lldb/Utility/LLDBAssert.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/RealpathPrefixes.h"
#include "lldb/Utility/State.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/Utility/Timer.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/ErrorExtras.h"
#include "llvm/Support/ThreadPool.h"
#include <memory>
#include <mutex>
#include <optional>
#include <sstream>
#include "TargetProperties.inc"
#include "TargetPropertiesEnum.inc"
Classes
class TargetOptionValueProperties
class TargetExperimentalOptionValueProperties
Macros
#define LLDB_PROPERTIES_target
#define LLDB_PROPERTIES_target
#define LLDB_PROPERTIES_target_experimental
#define LLDB_PROPERTIES_target_experimental
Enumerations
enum x86DisassemblyFlavor { eX86DisFlavorDefault , eX86DisFlavorIntel , eX86DisFlavorATT }
enum { ePropertyExperimental }
enum
Functions
template<typename Installer>
static Status installExecutable (const Installer &installer)
static bool CheckIfWatchpointsSupported (Target *target, Status &error)
static void LoadScriptingResourceForModule (const ModuleSP &module_sp, Target *target)
Variables
static std::atomic< lldb::user_id_t > g_target_unique_id {1}
static constexpr OptionEnumValueElement g_dynamic_value_types []
static constexpr OptionEnumValueElement g_inline_breakpoint_enums []
static constexpr OptionEnumValueElement g_x86_dis_flavor_value_types []
static constexpr OptionEnumValueElement g_import_std_module_value_types []
static constexpr OptionEnumValueElement g_dynamic_class_info_helper_value_types []
static constexpr OptionEnumValueElement g_hex_immediate_style_values []
static constexpr OptionEnumValueElement g_load_script_from_sym_file_values []
static constexpr OptionEnumValueElement g_load_cwd_lldbinit_values []
static constexpr OptionEnumValueElement g_memory_module_load_level_values []
constexpr llvm::StringLiteral s_cpp_ignore_context_qualifiers_option
Macro Definition Documentation
LLDB_PROPERTIES_target [1/2]
#define LLDB_PROPERTIES_target
Definition at line 4409 of file Target.cpp.
LLDB_PROPERTIES_target [2/2]
#define LLDB_PROPERTIES_target
Definition at line 4409 of file Target.cpp.
LLDB_PROPERTIES_target_experimental [1/2]
#define LLDB_PROPERTIES_target_experimental
Definition at line 4444 of file Target.cpp.
LLDB_PROPERTIES_target_experimental [2/2]
#define LLDB_PROPERTIES_target_experimental
Definition at line 4444 of file Target.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ePropertyExperimental
Definition at line 4412 of file Target.cpp.
anonymous enum
anonymous enum
Definition at line 4447 of file Target.cpp.
x86DisassemblyFlavor
enum x86DisassemblyFlavor
Enumerator
eX86DisFlavorDefault
eX86DisFlavorIntel
eX86DisFlavorATT
Definition at line 4277 of file Target.cpp.
Function Documentation
CheckIfWatchpointsSupported()
bool CheckIfWatchpointsSupported (Target * target, Status & error) static
Definition at line 935 of file Target.cpp.
References error(), lldb_private::Status::FromErrorStringWithFormat(), and lldb_private::Target::GetProcessSP().
Referenced by lldb_private::Target::CreateWatchpoint().
installExecutable()
template<typename Installer> Status installExecutable (const Installer & installer) static
Definition at line 147 of file Target.cpp.
References error(), and lldb_private::Status.
Referenced by lldb_private::Target::Install().
LoadScriptingResourceForModule()
void LoadScriptingResourceForModule (const ModuleSP & module_sp, Target * target) static
Definition at line 1545 of file Target.cpp.
References error(), lldb_private::Debugger::GetAsyncErrorStream(), lldb_private::StreamString::GetData(), lldb_private::Target::GetDebugger(), and lldb_private::StreamString::GetSize().
Referenced by lldb_private::Target::ModulesDidLoad().
Variable Documentation
g_dynamic_class_info_helper_value_types
OptionEnumValueElement g_dynamic_class_info_helper_value_types[] static constexpr
Initial value:
= {
        {
            eDynamicClassInfoHelperAuto,
            "auto",
            "Automatically determine the most appropriate method for the "
            "target OS.",
        },
        {eDynamicClassInfoHelperRealizedClassesStruct, "RealizedClassesStruct",
         "Prefer using the realized classes struct."},
        {eDynamicClassInfoHelperCopyRealizedClassList, "CopyRealizedClassList",
         "Prefer using the CopyRealizedClassList API."},
        {eDynamicClassInfoHelperGetRealizedClassList, "GetRealizedClassList",
         "Prefer using the GetRealizedClassList API."},
}
Definition at line 4324 of file Target.cpp.
g_dynamic_value_types
OptionEnumValueElement g_dynamic_value_types[] static constexpr
Initial value:
= {
    {
        eNoDynamicValues,
        "no-dynamic-values",
        "Don't calculate the dynamic type of values",
    },
    {
        eDynamicCanRunTarget,
        "run-target",
        "Calculate the dynamic type of values "
        "even if you have to run the target.",
    },
    {
        eDynamicDontRunTarget,
        "no-run-target",
        "Calculate the dynamic type of values, but don't run the target.",
    },
}
Definition at line 4231 of file Target.cpp.
Referenced by lldb_private::GetDynamicValueTypes().
g_hex_immediate_style_values
OptionEnumValueElement g_hex_immediate_style_values[] static constexpr
Initial value:
= {
    {
        Disassembler::eHexStyleC,
        "c",
        "C-style (0xffff).",
    },
    {
        Disassembler::eHexStyleAsm,
        "asm",
        "Asm-style (0ffffh).",
    },
}
Definition at line 4339 of file Target.cpp.
g_import_std_module_value_types
OptionEnumValueElement g_import_std_module_value_types[] static constexpr
Initial value:
= {
    {
        eImportStdModuleFalse,
        "false",
        "Never import the 'std' C++ module in the expression parser.",
    },
    {
        eImportStdModuleFallback,
        "fallback",
        "Retry evaluating expressions with an imported 'std' C++ module if they"
        " failed to parse without the module. This allows evaluating more "
        "complex expressions involving C++ standard library types."
    },
    {
        eImportStdModuleTrue,
        "true",
        "Always import the 'std' C++ module. This allows evaluating more "
        "complex expressions involving C++ standard library types. This feature"
        " is experimental."
    },
}
Definition at line 4301 of file Target.cpp.
g_inline_breakpoint_enums
OptionEnumValueElement g_inline_breakpoint_enums[] static constexpr
Initial value:
= {
    {
        eInlineBreakpointsNever,
        "never",
        "Never look for inline breakpoint locations (fastest). This setting "
        "should only be used if you know that no inlining occurs in your"
        "programs.",
    },
    {
        eInlineBreakpointsHeaders,
        "headers",
        "Only check for inline breakpoint locations when setting breakpoints "
        "in header files, but not when setting breakpoint in implementation "
        "source files (default).",
    },
    {
        eInlineBreakpointsAlways,
        "always",
        "Always look for inline breakpoint locations when setting file and "
        "line breakpoints (slower but most accurate).",
    },
}
Definition at line 4254 of file Target.cpp.
g_load_cwd_lldbinit_values
OptionEnumValueElement g_load_cwd_lldbinit_values[] static constexpr
Initial value:
= {
    {
        eLoadCWDlldbinitTrue,
        "true",
        "Load .lldbinit files from current directory",
    },
    {
        eLoadCWDlldbinitFalse,
        "false",
        "Do not load .lldbinit files from current directory",
    },
    {
        eLoadCWDlldbinitWarn,
        "warn",
        "Warn about loading .lldbinit files from current directory",
    },
}
Definition at line 4370 of file Target.cpp.
g_load_script_from_sym_file_values
OptionEnumValueElement g_load_script_from_sym_file_values[] static constexpr
Initial value:
= {
    {
        eLoadScriptFromSymFileTrue,
        "true",
        "Load debug scripts inside symbol files",
    },
    {
        eLoadScriptFromSymFileFalse,
        "false",
        "Do not load debug scripts inside symbol files.",
    },
    {
        eLoadScriptFromSymFileWarn,
        "warn",
        "Warn about debug scripts inside symbol files but do not load them.",
    },
}
Definition at line 4352 of file Target.cpp.
g_memory_module_load_level_values
OptionEnumValueElement g_memory_module_load_level_values[] static constexpr
Initial value:
= {
    {
        eMemoryModuleLoadLevelMinimal,
        "minimal",
        "Load minimal information when loading modules from memory. Currently "
        "this setting loads sections only.",
    },
    {
        eMemoryModuleLoadLevelPartial,
        "partial",
        "Load partial information when loading modules from memory. Currently "
        "this setting loads sections and function bounds.",
    },
    {
        eMemoryModuleLoadLevelComplete,
        "complete",
        "Load complete information when loading modules from memory. Currently "
        "this setting loads sections and all symbols.",
    },
}
Definition at line 4388 of file Target.cpp.
g_target_unique_id
std::atomic<lldb::user_id_t> g_target_unique_id {1} static
Definition at line 144 of file Target.cpp.
Referenced by lldb_private::Target::Target().
g_x86_dis_flavor_value_types
OptionEnumValueElement g_x86_dis_flavor_value_types[] static constexpr
Initial value:
= {
    {
        eX86DisFlavorDefault,
        "default",
        "Disassembler default (currently att).",
    },
    {
        eX86DisFlavorIntel,
        "intel",
        "Intel disassembler flavor.",
    },
    {
        eX86DisFlavorATT,
        "att",
        "AT&T disassembler flavor.",
    },
}
Definition at line 4283 of file Target.cpp.
Referenced by lldb_private::TargetProperties::GetDisassemblyFlavor().
s_cpp_ignore_context_qualifiers_option
llvm::StringLiteral s_cpp_ignore_context_qualifiers_option constexpr
Initial value:
=
    "c++-ignore-context-qualifiers"
Definition at line 5427 of file Target.cpp.
Referenced by lldb_private::EvaluateExpressionOptions::GetCppIgnoreContextQualifiers(), and lldb_private::EvaluateExpressionOptions::SetCppIgnoreContextQualifiers().