LLDB: Terminal.cpp File Reference
Terminal.cpp File Reference
#include "lldb/Host/Terminal.h"
#include "lldb/Host/Config.h"
#include "lldb/Host/PosixApi.h"
#include "llvm/ADT/STLExtras.h"
#include <csignal>
#include <fcntl.h>
#include <optional>
Classes
struct lldb_private::Terminal::Data
Functions
static llvm::Error termiosMissingError ()
Function Documentation
termiosMissingError()
llvm::Error termiosMissingError () static
Definition at line 34 of file Terminal.cpp.
Referenced by lldb_private::Terminal::GetData(), lldb_private::Terminal::SetBaudRate(), lldb_private::Terminal::SetCanonical(), lldb_private::Terminal::SetData(), lldb_private::Terminal::SetEcho(), lldb_private::Terminal::SetHardwareFlowControl(), lldb_private::Terminal::SetParity(), lldb_private::Terminal::SetParityCheck(), lldb_private::Terminal::SetRaw(), and lldb_private::Terminal::SetStopBits().