LLDB: Timer.cpp File Reference
Timer.cpp File Reference
#include "lldb/Utility/Timer.h"
#include "lldb/Utility/Stream.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/Signposts.h"
#include <algorithm>
#include <map>
#include <mutex>
#include <utility>
#include <vector>
#include <cassert>
#include <cinttypes>
#include <cstdarg>
#include <cstdio>
Macros
#define TIMER_INDENT_AMOUNT 2
Functions
static std::mutex & GetFileMutex ()
static TimerStack & GetTimerStackForCurrentThread ()
static bool CategoryMapIteratorSortCriterion (const Stats &lhs, const Stats &rhs)
Variables
static llvm::ManagedStatic< llvm::SignpostEmitter > Signposts
Allows llvm::Timer to emit signposts when supported.
Macro Definition Documentation
TIMER_INDENT_AMOUNT
#define TIMER_INDENT_AMOUNT 2
Definition at line 26 of file Timer.cpp.
Referenced by lldb_private::Timer::~Timer().
Function Documentation
CategoryMapIteratorSortCriterion()
bool CategoryMapIteratorSortCriterion (const Stats & lhs, const Stats & rhs) static
Definition at line 125 of file Timer.cpp.
Referenced by lldb_private::Timer::DumpCategoryTimes().
GetFileMutex()
std::mutex & GetFileMutex () static
Definition at line 38 of file Timer.cpp.
Referenced by lldb_private::Timer::~Timer().
GetTimerStackForCurrentThread()
TimerStack & GetTimerStackForCurrentThread () static
Definition at line 43 of file Timer.cpp.
Referenced by lldb_private::Timer::Timer(), and lldb_private::Timer::~Timer().
Variable Documentation
Signposts
llvm::ManagedStatic<llvm::SignpostEmitter> Signposts static
Allows llvm::Timer to emit signposts when supported.
Definition at line 34 of file Timer.cpp.
Referenced by lldb_private::Timer::Timer(), and lldb_private::Timer::~Timer().