LLDB: TraceIntelPTMultiCpuDecoder.cpp File Reference
TraceIntelPTMultiCpuDecoder.cpp File Reference
#include "TraceIntelPTMultiCpuDecoder.h"
#include "TraceIntelPT.h"
#include "llvm/Support/Error.h"
#include <optional>
Functions
static Expected< std::vector< PSBBlock > > GetPSBBlocksForCPU (TraceIntelPT &trace, cpu_id_t cpu_id)
Function Documentation
GetPSBBlocksForCPU()
Expected< std::vector< PSBBlock > > GetPSBBlocksForCPU (TraceIntelPT & trace, cpu_id_t cpu_id) static
Definition at line 93 of file TraceIntelPTMultiCpuDecoder.cpp.
References lldb_private::IntelPTDataKinds::kIptTrace, lldb_private::Trace::OnCpuBinaryDataRead(), and lldb_private::trace_intel_pt::SplitTraceIntoPSBBlock().
Referenced by lldb_private::trace_intel_pt::TraceIntelPTMultiCpuDecoder::DoCorrelateContextSwitchesAndIntelPtTraces().