LLDB: TypeCategoryMap.cpp File Reference
TypeCategoryMap.cpp File Reference
#include "lldb/DataFormatters/TypeCategoryMap.h"
#include "lldb/DataFormatters/FormatClasses.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
Functions
template void TypeCategoryMap::Get< lldb::TypeFormatImplSP > (FormattersMatchData &match_data, lldb::TypeFormatImplSP &retval)
Explicit instantiations for the three types.
template void TypeCategoryMap::Get< lldb::TypeSummaryImplSP > (FormattersMatchData &match_data, lldb::TypeSummaryImplSP &retval)
template void TypeCategoryMap::Get< lldb::SyntheticChildrenSP > (FormattersMatchData &match_data, lldb::SyntheticChildrenSP &retval)
Function Documentation
TypeCategoryMap::Get< lldb::SyntheticChildrenSP >()
template void TypeCategoryMap::Get< lldb::SyntheticChildrenSP > (FormattersMatchData & match_data, lldb::SyntheticChildrenSP & retval)
References lldb_private::TypeCategoryMap::Get().
TypeCategoryMap::Get< lldb::TypeFormatImplSP >()
template void TypeCategoryMap::Get< lldb::TypeFormatImplSP > (FormattersMatchData & match_data, lldb::TypeFormatImplSP & retval)
Explicit instantiations for the three types.
References lldb_private::TypeCategoryMap::Get().
TypeCategoryMap::Get< lldb::TypeSummaryImplSP >()
template void TypeCategoryMap::Get< lldb::TypeSummaryImplSP > (FormattersMatchData & match_data, lldb::TypeSummaryImplSP & retval)
References lldb_private::TypeCategoryMap::Get().