LLDB: TypeSystem.cpp File Reference
TypeSystem.cpp File Reference
#include "lldb/Symbol/TypeSystem.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Expression/UtilityFunction.h"
#include "lldb/Symbol/CompilerType.h"
#include "lldb/Target/Language.h"
#include "llvm/ADT/DenseSet.h"
#include <optional>
Functions
static TypeSystemSP CreateInstanceHelper (lldb::LanguageType language, Module *module, Target *target)
Variables
static const size_t g_num_small_bitvector_bits = 64 - 8
A 64-bit SmallBitVector is only small up to 64-7 bits, and the setBitsInMask interface wants to write full bytes.
Function Documentation
CreateInstanceHelper()
TypeSystemSP CreateInstanceHelper (lldb::LanguageType language, Module * module, Target * target) static
Definition at line 42 of file TypeSystem.cpp.
References lldb_private::PluginManager::GetTypeSystemCreateCallbackAtIndex().
Referenced by lldb_private::TypeSystem::CreateInstance(), and lldb_private::TypeSystem::CreateInstance().
Variable Documentation
g_num_small_bitvector_bits
const size_t g_num_small_bitvector_bits = 64 - 8 static
A 64-bit SmallBitVector is only small up to 64-7 bits, and the setBitsInMask interface wants to write full bytes.
Definition at line 23 of file TypeSystem.cpp.