LLDB: UniqueDWARFASTType.cpp File Reference
UniqueDWARFASTType.cpp File Reference
#include "UniqueDWARFASTType.h"
#include "SymbolFileDWARF.h"
#include "lldb/Core/Declaration.h"
#include "lldb/Target/Language.h"
Functions
static bool IsStructOrClassTag (llvm::dwarf::Tag Tag)
static bool IsSizeAndDeclarationMatching (UniqueDWARFASTType const &udt, DWARFDIE const &die, const lldb_private::Declaration &decl, const int32_t byte_size, bool is_forward_declaration)
Function Documentation
IsSizeAndDeclarationMatching()
bool IsSizeAndDeclarationMatching (UniqueDWARFASTType const & udt, DWARFDIE const & die, const lldb_private::Declaration & decl, const int32_t byte_size, bool is_forward_declaration) static
Definition at line 23 of file UniqueDWARFASTType.cpp.
References lldb_private::plugin::dwarf::DWARFBaseDIE::GetCU(), lldb_private::plugin::dwarf::SymbolFileDWARF::GetLanguage(), lldb_private::Language::LanguageIsCPlusPlus(), lldb_private::plugin::dwarf::UniqueDWARFASTType::m_byte_size, lldb_private::plugin::dwarf::UniqueDWARFASTType::m_declaration, and lldb_private::plugin::dwarf::UniqueDWARFASTType::m_is_forward_declaration.
Referenced by lldb_private::plugin::dwarf::UniqueDWARFASTTypeList::Find().
IsStructOrClassTag()
bool IsStructOrClassTag (llvm::dwarf::Tag Tag) static
Definition at line 18 of file UniqueDWARFASTType.cpp.