LLDB: UnwindTable.cpp File Reference
UnwindTable.cpp File Reference
#include "lldb/Symbol/UnwindTable.h"
#include <cstdio>
#include <optional>
#include "lldb/Core/Module.h"
#include "lldb/Core/Section.h"
#include "lldb/Symbol/ArmUnwindInfo.h"
#include "lldb/Symbol/CallFrameInfo.h"
#include "lldb/Symbol/CompactUnwindInfo.h"
#include "lldb/Symbol/DWARFCallFrameInfo.h"
#include "lldb/Symbol/FuncUnwinders.h"
#include "lldb/Symbol/ObjectFile.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Symbol/SymbolVendor.h"
Functions
static Address GetFunctionOrSymbolAddress (const Address &addr, const SymbolContext &sc)
Function Documentation
GetFunctionOrSymbolAddress()
Address GetFunctionOrSymbolAddress (const Address & addr, const SymbolContext & sc) static
Definition at line 125 of file UnwindTable.cpp.
References lldb_private::SymbolContext::GetFunctionOrSymbolAddress(), and lldb_private::Address::IsValid().
Referenced by lldb_private::UnwindTable::GetFuncUnwindersContainingAddress(), and lldb_private::UnwindTable::GetUncachedFuncUnwindersContainingAddress().