LLDB: UnwindAssemblyInstEmulation.cpp File Reference
UnwindAssemblyInstEmulation.cpp File Reference
#include "UnwindAssemblyInstEmulation.h"
#include "lldb/Core/Address.h"
#include "lldb/Core/Disassembler.h"
#include "lldb/Core/DumpDataExtractor.h"
#include "lldb/Core/DumpRegisterValue.h"
#include "lldb/Core/FormatEntity.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/ArchSpec.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/DataExtractor.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/Status.h"
#include "lldb/Utility/StreamString.h"
#include "llvm/ADT/SmallSet.h"
#include <deque>
Functions
static void DumpUnwindRowsToLog (Log *log, AddressRange range, const UnwindPlan &unwind_plan)
static void DumpInstToLog (Log *log, Instruction &inst, const InstructionList &inst_list)
Function Documentation
DumpInstToLog()
void DumpInstToLog (Log * log, Instruction & inst, const InstructionList & inst_list) static
Definition at line 67 of file UnwindAssemblyInstEmulation.cpp.
References lldb_private::Instruction::Dump(), lldb_private::InstructionList::GetMaxOpcocdeByteSize(), lldb_private::StreamString::GetString(), lldb_private::Log::GetVerbose(), lldb_private::FormatEntity::Parse(), and lldb_private::Log::PutString().
Referenced by UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly().
DumpUnwindRowsToLog()
void DumpUnwindRowsToLog (Log * log, AddressRange range, const UnwindPlan & unwind_plan) static
Definition at line 55 of file UnwindAssemblyInstEmulation.cpp.
References lldb_private::UnwindPlan::Dump(), lldb_private::AddressRange::GetBaseAddress(), lldb_private::AddressRange::GetByteSize(), lldb_private::Address::GetFileAddress(), lldb_private::StreamString::GetString(), lldb_private::Log::GetVerbose(), lldb_private::Stream::Printf(), and lldb_private::Log::PutString().
Referenced by UnwindAssemblyInstEmulation::GetNonCallSiteUnwindPlanFromAssembly().