LLDB: UnwindPlan.cpp File Reference
UnwindPlan.cpp File Reference
#include "lldb/Symbol/UnwindPlan.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/ConstString.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/DebugInfo/DIContext.h"
#include "llvm/DebugInfo/DWARF/DWARFExpressionPrinter.h"
#include "llvm/DebugInfo/DWARF/LowLevel/DWARFExpression.h"
#include <optional>
Classes
struct RowLess
Functions
static std::optional< std::pair< lldb::ByteOrder, uint32_t > > GetByteOrderAndAddrSize (Thread *thread)
static void DumpDWARFExpr (Stream &s, llvm::ArrayRef< uint8_t > expr, Thread *thread)
static void DumpRegisterName (Stream &s, const UnwindPlan *unwind_plan, Thread *thread, uint32_t reg_num)
Function Documentation
DumpDWARFExpr()
void DumpDWARFExpr (Stream & s, llvm::ArrayRef< uint8_t > expr, Thread * thread) static
Definition at line 87 of file UnwindPlan.cpp.
References lldb_private::Stream::AsRawOstream(), lldb::eByteOrderLittle, GetByteOrderAndAddrSize(), and lldb_private::Stream::PutCString().
Referenced by lldb_private::UnwindPlan::Row::AbstractRegisterLocation::Dump(), and lldb_private::UnwindPlan::Row::FAValue::Dump().
DumpRegisterName()
void DumpRegisterName (Stream & s, const UnwindPlan * unwind_plan, Thread * thread, uint32_t reg_num) static
Definition at line 165 of file UnwindPlan.cpp.
References lldb_private::UnwindPlan::GetRegisterInfo(), lldb_private::RegisterInfo::name, lldb_private::Stream::Printf(), and lldb_private::Stream::PutCString().
Referenced by lldb_private::UnwindPlan::Row::Dump(), and lldb_private::UnwindPlan::Row::FAValue::Dump().
GetByteOrderAndAddrSize()
std::optional< std::pair< lldb::ByteOrder, uint32_t > > GetByteOrderAndAddrSize (Thread * thread) static
Definition at line 77 of file UnwindPlan.cpp.
References lldb_private::ArchSpec::GetAddressByteSize(), and lldb_private::ArchSpec::GetByteOrder().
Referenced by DumpDWARFExpr().