LLDB: UUID.cpp File Reference
UUID.cpp File Reference
#include "lldb/Utility/UUID.h"
#include "lldb/Utility/Stream.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/RandomNumberGenerator.h"
#include <cctype>
#include <chrono>
#include <climits>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <random>
Functions
static bool separate (size_t count)
static int xdigit_to_int (char ch)
Function Documentation
separate()
bool separate (size_t count) inline static
Definition at line 29 of file UUID.cpp.
Referenced by lldb_private::UUID::GetAsString(), and lldb_private::ProcessLaunchInfo::SetLaunchInSeparateProcessGroup().
xdigit_to_int()
int xdigit_to_int (char ch) inline static
Definition at line 70 of file UUID.cpp.
Referenced by lldb_private::UUID::DecodeUUIDBytesFromString().