LLDB: ValueObjectChild.cpp File Reference
ValueObjectChild.cpp File Reference
#include "lldb/ValueObject/ValueObjectChild.h"
#include "lldb/Core/Value.h"
#include "lldb/Symbol/CompilerType.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/Process.h"
#include "lldb/Utility/Flags.h"
#include "lldb/Utility/Scalar.h"
#include "lldb/Utility/Status.h"
#include "lldb/lldb-forward.h"
#include <functional>
#include <memory>
#include <vector>
#include <cstdio>
#include <cstring>
Functions
static void AdjustForBitfieldness (ConstString &name, uint8_t bitfield_bit_size)
Function Documentation
AdjustForBitfieldness()
void AdjustForBitfieldness (ConstString & name, uint8_t bitfield_bit_size) static
Definition at line 59 of file ValueObjectChild.cpp.
References lldb_private::ConstString::SetString().
Referenced by lldb_private::ValueObjectChild::GetDisplayTypeName(), lldb_private::ValueObjectChild::GetQualifiedTypeName(), and lldb_private::ValueObjectChild::GetTypeName().