LLDB: ValueObjectPrinter.cpp File Reference
ValueObjectPrinter.cpp File Reference
#include "lldb/DataFormatters/ValueObjectPrinter.h"
#include "lldb/DataFormatters/DataVisualization.h"
#include "lldb/Interpreter/CommandInterpreter.h"
#include "lldb/Target/Language.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/Stream.h"
#include "lldb/ValueObject/ValueObject.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/MathExtras.h"
#include <cstdint>
#include <memory>
#include <optional>
Functions
static const char * maybeNewline (const std::string &s)
static bool IsPointerValue (const CompilerType &type)
static constexpr size_t PhysicalIndexForLogicalIndex (size_t base, size_t stride, size_t logical)
Function Documentation
IsPointerValue()
bool IsPointerValue (const CompilerType & type) static
Definition at line 375 of file ValueObjectPrinter.cpp.
References lldb_private::Flags::AllClear(), lldb_private::Flags::AnySet(), and lldb_private::CompilerType::GetTypeInfo().
Referenced by lldb_private::ValueObjectPrinter::PrintValueAndSummaryIfNeeded().
maybeNewline()
const char * maybeNewline (const std::string & s) static
Definition at line 75 of file ValueObjectPrinter.cpp.
Referenced by lldb_private::ValueObjectPrinter::PrintObjectDescriptionIfNeeded().
PhysicalIndexForLogicalIndex()
constexpr size_t PhysicalIndexForLogicalIndex (size_t base, size_t stride, size_t logical) static constexpr
Definition at line 691 of file ValueObjectPrinter.cpp.
Referenced by lldb_private::ValueObjectPrinter::GenerateChild().