LLDB: ValueObject.cpp File Reference
ValueObject.cpp File Reference
#include "lldb/ValueObject/ValueObject.h"
#include "lldb/Core/Address.h"
#include "lldb/Core/Declaration.h"
#include "lldb/Core/Module.h"
#include "lldb/DataFormatters/DataVisualization.h"
#include "lldb/DataFormatters/DumpValueObjectOptions.h"
#include "lldb/DataFormatters/FormatManager.h"
#include "lldb/DataFormatters/StringPrinter.h"
#include "lldb/DataFormatters/TypeFormat.h"
#include "lldb/DataFormatters/TypeSummary.h"
#include "lldb/DataFormatters/ValueObjectPrinter.h"
#include "lldb/Expression/ExpressionVariable.h"
#include "lldb/Host/Config.h"
#include "lldb/Symbol/CompileUnit.h"
#include "lldb/Symbol/CompilerType.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Symbol/Type.h"
#include "lldb/Symbol/Variable.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/Language.h"
#include "lldb/Target/LanguageRuntime.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Target/ThreadList.h"
#include "lldb/Utility/DataBuffer.h"
#include "lldb/Utility/DataBufferHeap.h"
#include "lldb/Utility/Flags.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/Scalar.h"
#include "lldb/Utility/Stream.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/ValueObject/ValueObjectCast.h"
#include "lldb/ValueObject/ValueObjectChild.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
#include "lldb/ValueObject/ValueObjectDynamicValue.h"
#include "lldb/ValueObject/ValueObjectMemory.h"
#include "lldb/ValueObject/ValueObjectSynthetic.h"
#include "lldb/ValueObject/ValueObjectVTable.h"
#include "lldb/lldb-enumerations.h"
#include "llvm/Support/Compiler.h"
#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <memory>
#include <optional>
#include <tuple>
#include <cassert>
#include <cinttypes>
#include <cstdio>
#include <cstring>
Namespaces
namespace lldb_private
A class that represents a running process on the host machine.
Functions
static bool HasFloatingRepresentation (CompilerType ct)
static bool CopyStringDataToBufferSP (const StreamString &source, lldb::WritableDataBufferSP &destination)
static const char * ConvertBoolean (lldb::LanguageType language_type, const char *value_str)
static const char * SkipLeadingExpressionPathSeparators (const char *expression)
static ValueObjectSP GetAlternateValue (ValueObject &valobj, ValueObject::GetValueForExpressionPathOptions::SyntheticChildrenTraversal synth_traversal)
static ValueObjectSP DereferenceValueOrAlternate (ValueObject &valobj, ValueObject::GetValueForExpressionPathOptions::SyntheticChildrenTraversal synth_traversal, Status &error)
Variables
static user_id_t g_value_obj_uid = 0
Function Documentation
ConvertBoolean()
const char * ConvertBoolean (lldb::LanguageType language_type, const char * value_str) static
Definition at line 1658 of file ValueObject.cpp.
References lldb_private::Language::FindPlugin().
Referenced by lldb_private::ValueObject::SetValueFromCString().
CopyStringDataToBufferSP()
bool CopyStringDataToBufferSP (const StreamString & source, lldb::WritableDataBufferSP & destination) static
Definition at line 874 of file ValueObject.cpp.
References lldb_private::StreamString::GetString().
Referenced by lldb_private::ValueObject::ReadPointedString().
DereferenceValueOrAlternate()
ValueObjectSP DereferenceValueOrAlternate (ValueObject & valobj, ValueObject::GetValueForExpressionPathOptions::SyntheticChildrenTraversal synth_traversal, Status & error) static
Definition at line 2233 of file ValueObject.cpp.
References lldb_private::ValueObject::Dereference(), error(), and GetAlternateValue().
Referenced by lldb_private::ValueObject::GetValueForExpressionPath(), and lldb_private::ValueObject::GetValueForExpressionPath_Impl().
GetAlternateValue()
ValueObjectSP GetAlternateValue (ValueObject & valobj, ValueObject::GetValueForExpressionPathOptions::SyntheticChildrenTraversal synth_traversal) static
Definition at line 2212 of file ValueObject.cpp.
References lldb_private::ValueObject::GetNonSyntheticValue(), lldb_private::ValueObject::GetSyntheticValue(), and lldb_private::ValueObject::IsSynthetic().
Referenced by DereferenceValueOrAlternate(), and lldb_private::ValueObject::GetValueForExpressionPath_Impl().
HasFloatingRepresentation()
bool HasFloatingRepresentation (CompilerType ct) static
Definition at line 83 of file ValueObject.cpp.
References lldb_private::CompilerType::GetTypeInfo().
Referenced by lldb_private::ValueObject::CastToBasicType(), lldb_private::ValueObject::CastToEnumType(), lldb_private::ValueObject::GetValueAsAPFloat(), lldb_private::ValueObject::GetValueAsBool(), lldb_private::ValueObject::SetValueFromInteger(), and lldb_private::ValueObject::SetValueFromInteger().
SkipLeadingExpressionPathSeparators()
const char * SkipLeadingExpressionPathSeparators (const char * expression) static
Definition at line 1969 of file ValueObject.cpp.
Referenced by lldb_private::ValueObject::GetSyntheticExpressionPathChild().
Variable Documentation
g_value_obj_uid
user_id_t g_value_obj_uid = 0 static
Definition at line 77 of file ValueObject.cpp.
Referenced by lldb_private::ValueObject::ValueObject(), and lldb_private::ValueObject::ValueObject().