LLDB: Variable.cpp File Reference
Variable.cpp File Reference
#include "lldb/Symbol/Variable.h"
#include "lldb/Core/Debugger.h"
#include "lldb/Core/Module.h"
#include "lldb/Symbol/Block.h"
#include "lldb/Symbol/CompileUnit.h"
#include "lldb/Symbol/CompilerDecl.h"
#include "lldb/Symbol/CompilerDeclContext.h"
#include "lldb/Symbol/Function.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Symbol/SymbolFile.h"
#include "lldb/Symbol/Type.h"
#include "lldb/Symbol/TypeSystem.h"
#include "lldb/Symbol/VariableList.h"
#include "lldb/Target/ABI.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/RegisterContext.h"
#include "lldb/Target/StackFrame.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/Thread.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Utility/RegularExpression.h"
#include "lldb/Utility/Stream.h"
#include "lldb/ValueObject/ValueObject.h"
#include "lldb/ValueObject/ValueObjectVariable.h"
#include "llvm/ADT/Twine.h"
Functions
static void PrivateAutoComplete (StackFrame *frame, llvm::StringRef partial_path, const llvm::Twine &prefix_path, const CompilerType &compiler_type, CompletionRequest &request)
static void PrivateAutoCompleteMembers (StackFrame *frame, const std::string &partial_member_name, llvm::StringRef partial_path, const llvm::Twine &prefix_path, const CompilerType &compiler_type, CompletionRequest &request)
Function Documentation
PrivateAutoComplete()
void PrivateAutoComplete (StackFrame * frame, llvm::StringRef partial_path, const llvm::Twine & prefix_path, const CompilerType & compiler_type, CompletionRequest & request) static
Definition at line 540 of file Variable.cpp.
References lldb_private::CompletionRequest::AddCompletion(), lldb_private::CompilerType::GetCanonicalType(), lldb_private::Type::GetForwardCompilerType(), lldb_private::CompilerType::GetNumChildren(), lldb_private::CompilerType::GetPointeeType(), lldb_private::CompilerType::GetTypeClass(), lldb_private::StackFrame::GetVariableList(), lldb_private::CompilerType::IsValid(), PrivateAutoComplete(), and PrivateAutoCompleteMembers().
Referenced by lldb_private::Variable::AutoComplete(), PrivateAutoComplete(), and PrivateAutoCompleteMembers().
PrivateAutoCompleteMembers()
void PrivateAutoCompleteMembers (StackFrame * frame, const std::string & partial_member_name, llvm::StringRef partial_path, const llvm::Twine & prefix_path, const CompilerType & compiler_type, CompletionRequest & request) static
Definition at line 478 of file Variable.cpp.
References lldb_private::CompletionRequest::AddCompletion(), lldb_private::CompilerType::GetCanonicalType(), lldb_private::CompilerType::GetDirectBaseClassAtIndex(), lldb_private::CompilerType::GetFieldAtIndex(), lldb_private::CompilerType::GetNumDirectBaseClasses(), lldb_private::CompilerType::GetNumFields(), lldb_private::CompilerType::GetNumVirtualBaseClasses(), lldb_private::CompilerType::GetVirtualBaseClassAtIndex(), PrivateAutoComplete(), and PrivateAutoCompleteMembers().
Referenced by PrivateAutoComplete(), and PrivateAutoCompleteMembers().