LLDB: VerboseTrapFrameRecognizer.cpp File Reference
VerboseTrapFrameRecognizer.cpp File Reference
#include "VerboseTrapFrameRecognizer.h"
#include "lldb/Core/Module.h"
#include "lldb/Symbol/Function.h"
#include "lldb/Symbol/SymbolContext.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/StackFrameRecognizer.h"
#include "lldb/Target/Target.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "clang/CodeGen/ModuleBuilder.h"
Namespaces
namespace lldb_private
A class that represents a running process on the host machine.
Functions
static StackFrameSP FindMostRelevantFrame (Thread &selected_thread)
The 0th frame is the artificial inline frame generated to store the verbose_trap message.
void lldb_private::RegisterVerboseTrapFrameRecognizer (Process &process)
Function Documentation
FindMostRelevantFrame()
StackFrameSP FindMostRelevantFrame (Thread & selected_thread) static
The 0th frame is the artificial inline frame generated to store the verbose_trap message.
So, starting with the current parent frame, find the first frame that's not inside of the STL.
Definition at line 22 of file VerboseTrapFrameRecognizer.cpp.
References lldb_private::Thread::GetStackFrameAtIndex(), and lldb_private::ConstString::GetStringRef().
Referenced by lldb_private::VerboseTrapFrameRecognizer::RecognizeFrame().