LLDB: Version.cpp File Reference
Version.cpp File Reference
#include "lldb/Version/Version.h"
#include "VCSVersion.inc"
#include "lldb/Version/Version.inc"
#include "clang/Basic/Version.h"
Functions
static const char * GetLLDBVersion ()
static const char * GetLLDBRevision ()
static const char * GetLLDBRepository ()
Function Documentation
GetLLDBRepository()
const char * GetLLDBRepository () static
Definition at line 30 of file Version.cpp.
Referenced by lldb_private::GetVersion().
GetLLDBRevision()
const char * GetLLDBRevision () static
Definition at line 22 of file Version.cpp.
Referenced by lldb_private::GetVersion().
GetLLDBVersion()
const char * GetLLDBVersion () static
Definition at line 14 of file Version.cpp.
Referenced by lldb_private::GetVersion().