LLDB: ProcessRunLock.cpp File Reference
ProcessRunLock.cpp File Reference
#include "lldb/Host/ProcessRunLock.h"
#include "lldb/Host/windows/windows.h"
Functions
static PSRWLOCK GetLock (lldb::rwlock_t lock)
static bool ReadLock (lldb::rwlock_t rwlock)
static bool ReadUnlock (lldb::rwlock_t rwlock)
static bool WriteLock (lldb::rwlock_t rwlock)
static bool WriteUnlock (lldb::rwlock_t rwlock)
Function Documentation
GetLock()
PSRWLOCK GetLock (lldb::rwlock_t lock) static
Definition at line 12 of file windows/ProcessRunLock.cpp.
Referenced by ReadLock(), ReadUnlock(), WriteLock(), and WriteUnlock().
ReadLock()
bool ReadLock (lldb::rwlock_t rwlock) static
Definition at line 16 of file windows/ProcessRunLock.cpp.
References GetLock().
ReadUnlock()
bool ReadUnlock (lldb::rwlock_t rwlock) static
Definition at line 21 of file windows/ProcessRunLock.cpp.
References GetLock().
WriteLock()
bool WriteLock (lldb::rwlock_t rwlock) static
Definition at line 26 of file windows/ProcessRunLock.cpp.
References GetLock().
WriteUnlock()
bool WriteUnlock (lldb::rwlock_t rwlock) static
Definition at line 31 of file windows/ProcessRunLock.cpp.
References GetLock().