LLDB: XcodeSDK.cpp File Reference
XcodeSDK.cpp File Reference
#include "lldb/Utility/XcodeSDK.h"
#include "lldb/Utility/FileSpec.h"
#include "lldb/lldb-types.h"
#include "llvm/TargetParser/Triple.h"
#include <string>
Functions
static llvm::StringRef GetName (XcodeSDK::Type type)
static XcodeSDK::Type ParseSDKName (llvm::StringRef &name)
static llvm::VersionTuple ParseSDKVersion (llvm::StringRef &name)
static bool ParseAppleInternalSDK (llvm::StringRef &name)
Function Documentation
GetName()
llvm::StringRef GetName (XcodeSDK::Type type) static
Definition at line 21 of file XcodeSDK.cpp.
References lldb_private::XcodeSDK::AppleTVOS, lldb_private::XcodeSDK::AppleTVSimulator, lldb_private::XcodeSDK::BridgeOS, lldb_private::XcodeSDK::iPhoneOS, lldb_private::XcodeSDK::iPhoneSimulator, lldb_private::XcodeSDK::Linux, lldb_private::XcodeSDK::MacOSX, lldb_private::XcodeSDK::unknown, lldb_private::XcodeSDK::watchOS, lldb_private::XcodeSDK::WatchSimulator, lldb_private::XcodeSDK::XROS, and lldb_private::XcodeSDK::XRSimulator.
Referenced by EntityVariableBase::Dematerialize(), DynamicLoaderDarwinKernel::KextImageInfo::LoadImageUsingMemoryModule(), EntityVariableBase::Materialize(), DynamicLoaderDarwinKernel::ParseKextSummaries(), ObjectFileMachO::ParseSymtab(), EntityValueObject::SetupValueObject(), lldb_private::RegisterFlags::Field::ToXML(), lldb_private::TypeMatcher::TypeMatcher(), and lldb_private::XcodeSDK::XcodeSDK().
ParseAppleInternalSDK()
bool ParseAppleInternalSDK (llvm::StringRef & name) static
Definition at line 112 of file XcodeSDK.cpp.
Referenced by lldb_private::XcodeSDK::IsAppleInternalSDK(), and lldb_private::XcodeSDK::Parse().
ParseSDKName()
XcodeSDK::Type ParseSDKName (llvm::StringRef & name) static
Definition at line 67 of file XcodeSDK.cpp.
References lldb_private::XcodeSDK::AppleTVOS, lldb_private::XcodeSDK::AppleTVSimulator, lldb_private::XcodeSDK::BridgeOS, lldb_private::XcodeSDK::iPhoneOS, lldb_private::XcodeSDK::iPhoneSimulator, lldb_private::XcodeSDK::Linux, lldb_private::XcodeSDK::MacOSX, lldb_private::XcodeSDK::numSDKTypes, lldb_private::XcodeSDK::unknown, lldb_private::XcodeSDK::watchOS, lldb_private::XcodeSDK::WatchSimulator, lldb_private::XcodeSDK::XROS, and lldb_private::XcodeSDK::XRSimulator.
Referenced by lldb_private::XcodeSDK::GetType(), lldb_private::XcodeSDK::GetVersion(), lldb_private::XcodeSDK::IsAppleInternalSDK(), and lldb_private::XcodeSDK::Parse().
ParseSDKVersion()
llvm::VersionTuple ParseSDKVersion (llvm::StringRef & name) static
Definition at line 95 of file XcodeSDK.cpp.
Referenced by lldb_private::XcodeSDK::GetVersion(), lldb_private::XcodeSDK::IsAppleInternalSDK(), and lldb_private::XcodeSDK::Parse().